### ISSUE TITLE
Add comments for translators to distinguish tool names with tooltips

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#10544]
Author Name: **maris-gis-gmail-com -** (maris-gis-gmail-com -)
Original Redmine Issue: [485](https://issues.qgis.org/issues/485)

Redmine category:translations_and_international
Assignee: nobody -

---
Please add some comments for translators where particular string will be used. For some strings it is not possible to distinguish tool names (menu entires) from window titles, tooltips and other help related content.

I.e. "Add a Vector Layer" - it can be an action (menu item), tool tip or window title. In other languages it may be required to translate it differently depending on context. Currently only way to find phrase context is to write in garbage and then run app and look for garbage.

**Comment by alexbruy** [comment]
Closing as context is available when using Qt Linguist
