### ISSUE TITLE
Renaming a layer using an already existing name should issue a warning

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#11596]
Author Name: **nikos -** (nikos -)
Original Redmine Issue: [1536](https://issues.qgis.org/issues/1536)

Redmine category:map_legend
Assignee: nobody -

---
An error message should appear if one tries, by mistake, to use a name for a layer (in the legend of course) which is already used for another layer.

Thank you, Nikos

**Comment by alexbruy** [comment]
Do we really need such warning?

**Comment by nyalldawson** [comment]
No, this is a wontfix
