### ISSUE TITLE
add missing svg image sources

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#11645]
Author Name: **Paolo Cavallini** (@pcav)
Original Redmine Issue: [1585](https://issues.qgis.org/issues/1585)
Affected QGIS version: 3.0.0
Redmine category:gui

---
Most svg images are missing from source code (only derived png are there). Please add them.

**Comment by alexbruy** [comment]
Should be closed? As far as I can see vast majority of PNG images are GRASS GIS icons and they are PNG also in the upstream repository.

**Comment by pcav** [comment]
I agree GRASS icons may be left as they are. I'd close it after chacking the other remaining PNGs are of little relevance as well.
