### ISSUE TITLE
Keyboard shortcut for moving the cursor

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#11886]
Author Name: **alobo -** (alobo -)
Original Redmine Issue: [1826](https://issues.qgis.org/issues/1826)

Redmine category:map_canvas

---
Keyboard shortcuts (i.e. Ctrl+ ->) for moving the cursor
with no mouse, adding a cross-hair would be handy.

We could have Ctrl+ -> for moving by steps of
n pixels (n being customizable) and
Ctrl+Shift+ -> for moving by small steps (even subpixel) for
precision placement.

**Comment by alexbruy** [comment]
Canvas navigation can be done with arrows. Closing.
