### ISSUE TITLE
"For in the field" mode

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#11888]
Author Name: **alobo -** (alobo -)
Original Redmine Issue: [1828](https://issues.qgis.org/issues/1828)

Redmine category:gui
Assignee: nobody -

---
Create "For in the field" mode and "For in the office" mode by 
defining sets of keyboard shortcuts and other interactive 
qgis behavior. The user could create his/her own modes by
modifying these sets.

"For in the field" mode should make minimal use of the mouse.

**Comment by roya0045** [comment]
Shortcuts can be set. If you use shortcuts without a mouse, keeping them when you have a mouse should not be a downside and so a specific shortcut mode should not be needed. But that's just me.

**Comment by alexbruy** [comment]
Already possible with different profiles.
