### ISSUE TITLE
Group Transparency/Opacity for Legend Groups

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#11958]
Author Name: **Andreas Neumann** (@andreasneumann)
Original Redmine Issue: [1898](https://issues.qgis.org/issues/1898)

Redmine category:symbology

---
It would be nice if we could have group transparency (on groups of layers). This is a concept available in SVG (and potentially other technologies). The difference is that with group opacity/transparency, the layers in the group are rendered first individually (with or without opacity) and then the transparency is added on the intermediate rendering result of the group as a whole.

The difference is clearly seen if you have layers in a group where polygons of different layers overlap. You don't want opacity on the individual layers (since this would change colors), but you want to be able to set the opacity on the parent group, for being able to have a background base map shine through.

Here are two links on the topic:
http://www.w3.org/TR/SVG/masking.html#ObjectAndGroupOpacityProperties and http://labs.trolltech.com/blogs/2009/04/23/layered-rendering-part-2-it-helps-solve-many-problems/

---

Related issue(s): #13498 (relates)
Redmine related issue(s): [3438](https://issues.qgis.org/issues/3438)

---

**Comment by nyalldawson** [comment]
This was implemented in 3.24
