### ISSUE TITLE
Use QtSql for database access instead of native sqlite calls

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#12059]
Author Name: **Tim Sutton** (Tim Sutton)
Original Redmine Issue: [1999](https://issues.qgis.org/issues/1999)

Redmine category:projection_support
Assignee: Tim Sutton

---
Rationale:

Using the native sqlite approach (e.g. in [[QgsCoordinateReferenceSystem]]) requires including redundant source code withing our code base since Qt already provides an sqlite access layer. In addition in comparison to [[QtSql]], the sqlite native code is verbose and inconsistent with the general Qt4 based approach we take in our coding. Lastly, it should be noted that at some stage in the future we may wish to use other database backends to store application data. For example, enterprise users may wish to store these data in a centralised [[PostgreSQL]] database. Using the [[QtSql]] module would make moving to such an environment trivial.

I am attaching a first stab at moving sqlite code to [[QtSql]]. Note this code is not production ready and coverage through the code base is not yet complete. As such this patch has not yet been applied to trunk until it is ready for prime time.

---

- [qgis_qtsqlite_patch_v1.diff](https://issues.qgis.org/attachments/download/2391/qgis_qtsqlite_patch_v1.diff) (Tim Sutton)

**Comment by nyalldawson** [comment]
This is a wont-fix. We have nice c++11 style wrappers for the sqlite api now which are heavily used throughout QGIS in preference over the QtSql api.
