### ISSUE TITLE
inconsistency in the GUI: commas and full stops

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#12118]
Author Name: **Paolo Cavallini** (@pcav)
Original Redmine Issue: [2058](https://issues.qgis.org/issues/2058)

Redmine category:gui

---
There are inconsistencies in the GUI, when using it with a non-en locale (tested in Italian): in the table editor one must put "." for decimal, while in options (eg radius for snapping) "." is not accepted and "," must be used instead
The behaviour should be consistent, and follow the locale

**Comment by nyalldawson** [comment]
Many fixes have been made regarding this issue. If any remaining issues are encountered with locale decimal handling then please open specific tickets for each of these.
