### ISSUE TITLE
Locale settings not working as it should

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#12463]
Author Name: **pinux -** (pinux -)
Original Redmine Issue: [2403](https://issues.qgis.org/issues/2403)

Redmine category:gui
Assignee: nobody -

---
In the locale settings it should be possible to choose the language used by the software without changing the locale for the time or number formatting. For example I can choose as language English but the locale for the number and time formatting can remain the system locale (Italian). Also check the bug #12118 for another problems with the locale.

**Comment by alexbruy** [comment]
Already possible in recent versions.
