### ISSUE TITLE
split v.generalize GRASS module in two

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#12818]
Author Name: **Paolo Cavallini** (@pcav)
Original Redmine Issue: [2758](https://issues.qgis.org/issues/2758)

Redmine category:grass

---
As it stans, the v.generalize GRASS module in QGIS is too complex. It would be better to split it in two:

- one for simplification

- one for smoothing

leaving only the options that are relevant for each case.

**Comment by suricactus** [comment]
Isn't this against the current QGIS UI paradigm regarding the GRASS modules? Each module has only one generic instance in the Processing Panel. It seems this feature request has been already implemented but did not pass from 2 to 3 https://github.com/qgis/QGIS/pull/2776 I would suggest this being closed.

**Comment by gioman** [comment]
> Isn't this against the current QGIS UI paradigm regarding the GRASS modules? Each module has only one generic instance in the Processing Panel. It seems this feature request has been already implemented but did not pass from 2 to 3 #2776 I would suggest this being closed.

The tool have been split in the past, and then re-merged into one, as it is now.
