### ISSUE TITLE
Georeference's plugin can work with changes of projections

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#12950]
Author Name: **Luiz Motta** (@lmotta)
Original Redmine Issue: [2890](https://issues.qgis.org/issues/2890)

Redmine category:c++_plugins/georeferencer
Assignee: mmassing -

---
The patch allows Georeference´s plugin work changes of projections.

1) The display of GCP's in QGis mapcanvas  with 
projection changes in QGis (property of project - Coordinate Reference System)

2) The reference coordinates (Map) in GCP table change when new setting of EPSG in plugin.

3) Show EPSG (reference coordinates) in table of GCP and dialog input coordinate (EPSG of Qgis mapcanvas)

---

- [georeferencer_paths_lmotta.2.zip](https://issues.qgis.org/attachments/download/2807/georeferencer_paths_lmotta.2.zip) (Luiz Motta)
- [georeferencer_diff_lmotta.zip](https://issues.qgis.org/attachments/download/2806/georeferencer_diff_lmotta.zip) (Luiz Motta)
- [georeferencer_paths_lmotta.zip](https://issues.qgis.org/attachments/download/2808/georeferencer_paths_lmotta.zip) (Luiz Motta)

**Comment by roya0045** [comment]
@gioman do you feel that the patch that closed #39314 should also close this?

**Comment by gioman** [comment]
> @gioman do you feel that #39584 should have closed this?

@roya0045 will check.

**Comment by gioman** [comment]
> @gioman do you feel that #39584 should have closed this?

@roya0045 yes, I think so. Please reopen if necessary.
