### ISSUE TITLE
Metadata section report uncorrect dimension of archive for 3D shapefiles

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#13006]
Author Name: **aperi2007 -** (aperi2007 -)
Original Redmine Issue: [2946](https://issues.qgis.org/issues/2946)

Redmine category:vectors

---
In the property -> metadata section
for shapefiles archive was reported always the 2D version of the geometry.
Example:
for a shapefile of 3D arcs shapefile,
in the metadata section the geometry reported is always Line not Line3D.

---

- [patch_for_ticket_2946.diff](https://issues.qgis.org/attachments/download/2836/patch_for_ticket_2946.diff) (Giuseppe Sucameli)

**Comment by alexbruy** [comment]
Seems already fixed.

**Comment by gioman** [comment]
It is reported ok now.
