### ISSUE TITLE
Cannot access disk from remote desktop connection drives when remotely accessing Quantum GIS

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#13012]
Author Name: **infobleep -** (infobleep -)
Original Redmine Issue: [2952](https://issues.qgis.org/issues/2952)

Redmine category:data_provider
Assignee: nobody -

---
I was recently accessing Quantum GIS, installed on a Windows 2003 server, using a remote desktop connection in Windows XP. To access all the local and network drives attached to my computer, I set up a disk from remote desktop connection.

However Quantum GIS couldn't access any of the drives set up in this way. They simply did not appear in the list of drives when going to open files. Only the local drives and those mapped directly on Windows Sever 2003 were accessible.

**Comment by m-kuhn** [comment]
Is this still an issue?

**Comment by pjshelton** [comment]
Using QGIS 3.18.0 remoting from a Windows 10 to a Windows 10 and setting up a mapped drive to a third Windows 10 box from the machine that was remoted into, I was able to see the newly mapped drive on the third box in QGIS.  Not quite the setup as described by OP but the best I can do.

**Comment by m-kuhn** [comment]
Thank you for testing @pjshelton . If I understand you correctly, in your tests everything works as expected?
In this case I'm tempted to close this 11 year old issue.

**Comment by pjshelton** [comment]
Yes.
