### ISSUE TITLE
Projection information – some handbook or more info in QGIS

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#13128]
Author Name: **Jhelebrant -** (Jhelebrant -)
Original Redmine Issue: [3068](https://issues.qgis.org/issues/3068)

Redmine category:documentation_and_help
Assignee: Otto Dassau

---
Hi,
I had a small problem related with projection. I knew, that I should convert my data in WGS84 to S-42 (Pulkovo 1942) for some reason (use with some exotic software) but in QGIS I found a lot of "Pulkovo" projection and did not know which one to use for my area (Czech Republic). I did not have any internet connection available but luckily remembered, that in Kosmo I saw some info about area used for particular projections and later found there which "Pulkovo" is determined for Czech Republic. So this takes me to the idea, that it would be nice to have similar info also in QGIS (could be solved as "bubble" help) or if there is any document or app where is possible to find this information.

The possibility to list projections used for selected area would be also nice, but I cannot have everything I want :-)

What do you think?

PS: as an inspiration I attached two screenshots of Kosmo layer projection dialog where you can see additional information for each projection.

---

- [projekce_kosmo01.png](https://issues.qgis.org/attachments/download/2888/projekce_kosmo01.png) (Jhelebrant -)
- [projekce_kosmo02.png](https://issues.qgis.org/attachments/download/2889/projekce_kosmo02.png) (Jhelebrant -)

**Comment by alexbruy** [comment]
I think with recent move to Proj6 and related updates in QGIS we can close this. Please reopen if necessary
