### ISSUE TITLE
Feature cache

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#13260]
Author Name: **Martin Dobias** (@wonder-sk)
Original Redmine Issue: [3200](https://issues.qgis.org/issues/3200)

Redmine category:vectors
Assignee: Martin Dobias

---
It would be nice to have caching of features within vector layers. With caching, we could speed up the rendering by not fetching the data from (slow) data source on every render and store the features for some time in the memory.

Attached patch has been developed about more than one year ago as a first attempt to add this functionality to QGIS. It will have to be modified in order to be usable with current svn trunk. It has been shown with the patch that 2x speed up can be achieved (and maybe more). The patch also needs more testing / improvements as it modifies various areas within the core.

---

- [featurecache_patch.diff](https://issues.qgis.org/attachments/download/2937/featurecache_patch.diff) (Martin Dobias)

**Comment by alexbruy** [comment]
If I'm not wrong this already implemented.
