### ISSUE TITLE
Text alignment in Print Composer Legend

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#13299]
Author Name: **Micha Silver** (@micha-silver)
Original Redmine Issue: [3239](https://issues.qgis.org/issues/3239)

Redmine category:map_legend
Assignee: Marco Hugentobler

---
A helpful enhancement for Right-to-Left languages:
Please add alignment options (align-right and align-center) to the items,titles and symbols in the Legend on Print Composer

**Comment by kaplanlior** [comment]
We at Kaplan Open Source (https://kaplanopensource.co.il) decided to sponsor development of this feature request on behalf of the Israeli and other RTL speaking communities. Fix is expected in version 3.10.

**Comment by roya0045** [comment]
Nyall implemented this, can be closed.

**Comment by nyalldawson** [comment]
Yes, thanks!

**Comment by micha-silver** [comment]
Thanks very much! I'll test ASAP

**Comment by kaplanlior** [comment]
@micha-silver This is the feature we sponsored. It's already tested (:
