### ISSUE TITLE
Enhancement: option to "trim other layers to match"

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#13313]
Author Name: **Alister Hood** (@AlisterH)
Original Redmine Issue: [3253](https://issues.qgis.org/issues/3253)

Redmine category:symbology

---
*Task:*
It would be useful to be able to use a polygon to temporarily mask other layers.
e.g. if you have a layer of boundaries for catchments (or provinces or something), to only display content within one particular catchment.

*Current way of achieving the task:*
I think the most flexible way to achieve this at the moment is:
1. create a set of new mask layers, by subtracting each catchment from a polygon bigger than the area of interest.  
2. put these layers above everything else.  
3. only turn on the mask layer which corresponds to the area of interest.  
This method is fine for the work I do myself, because I work with only a small number of areas.  But it would not be practical with a large number.

*Proposed new feature*
I think the best way to do it would be to add an option "trim other layers to extent" (there is probably a better way of wording this - some people might think "extent" implies a rectangular area or something).
This would allow the user to mask all map content outside a polygon layer or whatever subset of the layer is defined (by the query builder).
A logical place for the option would be on the "general" tab in the "layer properties" dialogue, as this is where the layer subset is shown.

N.B. sorry if I haven't picked the appropriate Component; I'm not sure which it should be.

---

- [untitled.JPG](https://issues.qgis.org/attachments/download/2975/untitled.JPG) (Alister Hood)

**Comment by alexbruy** [comment]
If I understand correctly this is already possible.

**Comment by AlisterH** [comment]
Yes, "Invert Polygon" styling; sorry, I forgot that I had this ticket.

**Comment by AlisterH** [comment]
Note that it still has the limitation of not hiding labels, but I think it might be better to leave #13317 open for that.
