### ISSUE TITLE
Explode selected features

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#13338]
Author Name: **pinux -** (pinux -)
Original Redmine Issue: [3278](https://issues.qgis.org/issues/3278)

Redmine category:digitising

---
In Digitizing toolbar next to 'Merge selected features' would be useful to have a tool 'Explode selected features', so that a multipart feature can become siglepart.

---

Related issue(s): #13892 (relates)
Redmine related issue(s): [3834](https://issues.qgis.org/issues/3834)

---

**Comment by SrNetoChan** [comment]
You can achieve this using the split parts tools, the multipart to single part tool in replace in place mode, and using the multipart split plugin.
