### ISSUE TITLE
Add a flag "Label only selected features"

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#13558]
Author Name: **Paolo Cavallini** (@pcav)
Original Redmine Issue: [3498](https://issues.qgis.org/issues/3498)

Redmine category:labelling

---
It would be useful to add such a flag; currently this can be done with several workarounds, but all of them are rather ugly

**Comment by nyalldawson** [comment]
This can be done via expressions (is_selected) now - I don't see a compelling need to add an explicit ui setting for it.
