### ISSUE TITLE
Thousands separator

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#13627]
Author Name: **andskog -** (andskog -)
Original Redmine Issue: [3567](https://issues.qgis.org/issues/3567)

Redmine category:gui

---
Would it be possible and desirable to implement thousands separators in QG scales, coordinates etc. to improve readability?

**Comment by JLZIMMERMANN** [comment]
Would be welcome to add separators for scalebar, and in style GUI when working on labels and graphic rendering.
![image](https://user-images.githubusercontent.com/4929752/89730909-4a27ae80-da43-11ea-912f-d7a2c887ae1f.png)
![image](https://user-images.githubusercontent.com/4929752/89730917-5a3f8e00-da43-11ea-8593-83596173e619.png)
![image](https://user-images.githubusercontent.com/4929752/89730923-662b5000-da43-11ea-8b57-653055dc3f5c.png)

**Comment by alexbruy** [comment]
Already possible
