### ISSUE TITLE
[FEATURE] Extended tooltips for tool bars

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#13678]
Author Name: **Nathan Woodrow** (@NathanW2)
Original Redmine Issue: [3619](https://issues.qgis.org/issues/3619)

Redmine category:documentation_and_help
Assignee: Nathan Woodrow

---
Attached is a patch that I have been working on that adds more information to most tool tips to explain what the tool does.  I think this would be good for new users to qgis.  See image for example.

![image](http://i.imgur.com/M5Ii9.png)

I have done most of the main ones but will work on more over time.

---

- [tooltips.diff](https://issues.qgis.org/attachments/download/3163/tooltips.diff) (Nathan Woodrow)

**Comment by nyalldawson** [comment]
Patch is severely out of sync with current code base
