### ISSUE TITLE
Composer legend items inherit label font settings

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#13742]
Author Name: **John Tull** (John Tull)
Original Redmine Issue: [3683](https://issues.qgis.org/issues/3683)

Redmine category:map_composer/printing
Assignee: Marco Hugentobler

---
It would be nice for items in the composer legend to inherit the font properties that are used in the map canvas. This could be optional, perhaps a check item in the legend options. E.g., a point layer might have ng labels with Helvetica font size 10, italics, and purple with a yellow buffer in the map canvas. The legend item for that layer would also be size 10, italics, Helvetica and purple with a yellow buffer.

**Comment by nyalldawson** [comment]
Duplicate of #23066
