### ISSUE TITLE
Drag & drop of layers between qgis instances

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#13750]
Author Name: **peppo -** (peppo -)
Original Redmine Issue: [3691](https://issues.qgis.org/issues/3691)

Redmine category:map_legend

---
It would be nice to use drag&drop Layers between different instances of qgis. When I have a layer with a style in some old project and I would like to use the same layer in another project, i need to do the following.

In the old project: look up the source, save the style

In the new (existing) project: open the source, load the style

It would be cool to have this via drag and drop.

**Comment by alexbruy** [comment]
Drag and drop between instances works fine in 3.10/master. Closing.

**Comment by 3nids** [comment]
I have a PR that I will update soon for this: https://github.com/qgis/QGIS/pull/35382

**Comment by alexbruy** [comment]
Duplicates #20467.
