### ISSUE TITLE
improvement of spatial selection

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#13762]
Author Name: **jannekevandijk -** (jannekevandijk -)
Original Redmine Issue: [3703](https://issues.qgis.org/issues/3703)

Redmine category:c++_plugins/spatial_query

---
basically something similar to [[ArcGis]] 'select by location', where you
are able to:
1. select features in multiple layers
2. select using a buffer without having to create buffers first (eg select features within a distance of selected features of another layer)
(or should this be two seperate tickets?)

**Comment by alexbruy** [comment]
Selecting in multiple layers can be done with batch processing mode. Probably this can be closed.
