### ISSUE TITLE
Conflation tool for points

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#13770]
Author Name: **joshdoe -** (joshdoe -)
Original Redmine Issue: [3711](https://issues.qgis.org/issues/3711)

Redmine category:unknown

---
I'm interested in conflating points from two datasets, as I've asked "on this GIS.StackExchange.com question":http://gis.stackexchange.com/questions/8262. There doesn't seem to be anything available for this seemingly simple process. I'm aware of the JCS Conflation Suite and [[RoadMatcher]] (OpenJUMP plugins), but they handle the more complex cases of conflating edges and polygons. Maybe there's another term used instead of conflation when dealing with just points.

I'm interested in using this with [[OpenStreetMap]] (OSM), and I've posted "my thoughts on a workflow":http://wiki.openstreetmap.org/wiki/Conflation/Nodes for such a tool. I'm considering JOSM, but QGIS is another option since it works well with OSM data.

**Comment by alexbruy** [comment]
If I understand correctly, this functionality now available as "Detect dataset changes" tool in Processing toolbox.

**Comment by pwnage101** [comment]
Conflation refers to the process of combining geographic information from overlapping sources, where features from different sources may not line up perfectly.  "Detect dataset changes" is specifically for comparing different versions _of the same dataset_ (i.e. one source).  It seems to me that "Detect dataset changes" requires that all overlapping points share the exact same coordinates---i.e. the deviation tolerance is 0.  Conflation, on the other hand, would allow some finite tolerance.

**Comment by sfkeller** [comment]
See also following QGIS plugins (Python, possibly defunct):
* Offline-MapMatching (2022): https://plugins.qgis.org/plugins/Offline-MapMatching/ 
* Assisted-MapMatching (2021): https://plugins.qgis.org/plugins/Assisted-MapMatching/
