### ISSUE TITLE
Clicking inside the polygon with the Node tool

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#13811]
Author Name: **Maxim Dubinin** (@simgislab)
Original Redmine Issue: [3752](https://issues.qgis.org/issues/3752)

Redmine category:digitising

---
Right now, one needs to click on the edge of the polygon. This is rather inconvinient, because a) you have to aim hard and b) if you don't see the whole polygon and you click on the adjacent boundary between two you don't really know which ones nodes you've just activated.

Example (guess which polygon's nodes are activated): http://gis-lab.info/images/screenshots/20110417-87o-14kb.jpg

One should be able to click inside the polygon and have nodes selected.

---

Related issue(s): #18673 (relates), #19362 (relates)
Redmine related issue(s): [10234](https://issues.qgis.org/issues/10234), [11022](https://issues.qgis.org/issues/11022)

---

**Comment by uclaros** [comment]
It's been some time one can lock on a polygon by right clicking for the vertex tool. Also delete a part by clicking inside it. I guess this could close?
