### ISSUE TITLE
Random points  in symbol layer properties

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#13818]
Author Name: **lorex -** (lorex -)
Original Redmine Issue: [3759](https://issues.qgis.org/issues/3759)

Redmine category:symbology

---
Add the random option for points like gvsig 

[[Image(http://wiki.gfoss.it/images/Symbol_properties_random.jpg)]]

**Comment by suricactus** [comment]
This is already fixed in https://github.com/qgis/QGIS/pull/32456 . This issue should be closed.
