### ISSUE TITLE
PostGIS connections: take them from PgAdmin3?

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#13828]
Author Name: **Paolo Cavallini** (@pcav)
Original Redmine Issue: [3769](https://issues.qgis.org/issues/3769)

Redmine category:data_provider/postgis

---
It seems interesting to load the connection settings for [[PostGIS]] from
those in .pgadmin3 (or syncing them both), so the user should not repeat the config twice.

**Comment by alexbruy** [comment]
Should we close this?

**Comment by pcav** [comment]
Very low priority in any case, feel free to close it if you prefer.
