### ISSUE TITLE
if column name used for symbology changed, QGIS should ask when applying a QML file

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#13833]
Author Name: **Giovanni Manghi** (@gioman)
Original Redmine Issue: [3775](https://issues.qgis.org/issues/3775)

Redmine category:symbology

---
Take a vector and apply some kind of styling to it, then save the QML style file.

Change the name of the column used for styling and try re-apply the QML file:

QGIS will fail to style the vector as in the QML file the column name is now wrong.

In this cases QGIS should warn the user and allow him/her to choose the column to be used to style the vector.

---

Related issue(s): #17324 (duplicates)
Redmine related issue(s): [8582](https://issues.qgis.org/issues/8582)

---

**Comment by pjshelton** [comment]
![image](https://user-images.githubusercontent.com/39154868/103122222-1932d800-46cb-11eb-99d6-fce5700fc2ca.png)

This can be closed now as QGIS now stops and allows you to chose which attribute to use if the attribute named  in the qml does not exist.

**Comment by pjshelton** [comment]
@gioman  this is now complete
