### ISSUE TITLE
Symbols are incorrectly cropped in map canvas if rotated

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#13837]
Author Name: **Alister Hood** (@AlisterH)
Original Redmine Issue: [3779](https://issues.qgis.org/issues/3779)
Affected QGIS version: 3.6.0
Redmine category:map_canvas

---
For a point layer, if I use a rectangle "simple symbol", and specify a rotation, the symbol is rotated in the map canvas, but it also has the corners cut off as if it has been cropped to fit in the area that it would have occupied if it was not rotated.

See attached screenshot (with a symbol dimension of 5m).

This problem does not seem to affect the composer, but note that it has its own bug with rotated symbols (#13836).

---

- [cut_off.PNG](https://issues.qgis.org/attachments/download/3243/cut_off.PNG) (Alister Hood)

**Comment by pjshelton** [comment]
Hi,
Using v3.16.3 on Windows 10, I am unable to reproduce this for both svg markers or simple markers.
![image](https://user-images.githubusercontent.com/39154868/106368499-9cfc7600-6395-11eb-99a3-ad197b555312.png)
and
![image](https://user-images.githubusercontent.com/39154868/106368515-c1f0e900-6395-11eb-9be6-f89023f56e93.png)

**Comment by pjshelton** [comment]
@nyalldawson, has this been resoved?

**Comment by nyalldawson** [comment]
I vaguely recall a related fix...

**Comment by pjshelton** [comment]
@AlisterH,

Is this still a problem?  I was unable to reproduce in V3.16.3

**Comment by AlisterH** [comment]
Yeah, I've got 3.14 in front of me and can't reproduce there either.
