### ISSUE TITLE
"Screen scaling" setting to control the screen size of things defined in points or mm

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#13841]
Author Name: **Alister Hood** (@AlisterH)
Original Redmine Issue: [3783](https://issues.qgis.org/issues/3783)

Redmine category:map_canvas

---
With the new labelling engine (I have not tested with the old):
If the label font size is set in points (instead of map units), then on a typical monitor the labels are displayed in the map canvas at approximately the same size as they are printed on paper.  If I remember correctly (I'll check tomorrow), the same is true for vector symbols if their size is set in mm instead of map units.

Changing the DPI setting in the operation system does not affect the size (at least in Windows - perhaps someone could test in another operating system).  Presumably this means that QGIS (or maybe an underlying library such as QT) is using some "typical" value for screen DPI.  This is likely to be 72dpi or 91dpi or something.

You might think it would be good for the size to change depending on the DPI setting in the operating system, so that if this was set correctly then the labels and symbols would be exactly the same size on paper as on the screen.  BUT in reality this would be bad, for the same reason that the current behaviour is bad: _screen dpi is normally much lower than any printer output, so small labels and symbols which are easily legible on paper are not legible on the screen_.  

I think ideally QGIS should have its own setting to control the screen rendering size of labels and symbols (if they are not defined in map units).  I'm not sure what the best name for the setting would be - maybe something like "Screen scaling factor".  The units should be in DPI, so that if someone _does_ want things to be exactly the same height on paper as on the screen, they can simply set it to the actual DPI of their monitor.

**Comment by nyalldawson** [comment]
Canvas magnification permits this

**Comment by AlisterH** [comment]
For anyone else wondering where to look:
Settings>Options>Rendering>Rendering Behaviour>Magnification Level
And if you open an additional map view you can change the magnification level for it.

**Comment by AlisterH** [comment]
Oh, it's in the status bar too of course, and if you lock the scale zooming changes the magnification instead.
