### ISSUE TITLE
Add a button to separate the selected parts of a multipart feature while editing

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#13892]
Author Name: **elcuco -** (elcuco -)
Original Redmine Issue: [3834](https://issues.qgis.org/issues/3834)

Redmine category:digitising

---
When editing a feature (point, line or polygon), is often necessary to use the "Merge selected features". And if we merge nonadjacent features (lines or polygons) we create a multipart feature. But what if we want to do the opposite, ie separate a multipart feature into its individual, component features. This would be useful if we needed to alter the attributes of one of the elements in a multipart feature.
I realize that menu Vector has a tool for it but it creates a new shapefile every time we use it, thus sometimes isn't very practical.
So, add a button in the Digitizing toolbar, next to the "Merge selected features" button to separate the selected parts of a multipart feature.

---

Related issue(s): #13338 (relates)
Redmine related issue(s): [3278](https://issues.qgis.org/issues/3278)

---

**Comment by alexbruy** [comment]
Duplicates #13338.
