### ISSUE TITLE
Ability to lock map scale in print composer

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#13923]
Author Name: **marisn -** (marisn -)
Original Redmine Issue: [3865](https://issues.qgis.org/issues/3865)

Redmine category:map_composer/printing

---
When resizing map view in print composer, it automaticaly changes map scale. It would be nice, if it would be possible to lock scale and then it would not change when resizing map view. I.e. to create a printout 1:10 000 no mater how large is map extent.

---

Related issue(s): #18517 (relates), #20804 (duplicates)
Redmine related issue(s): [10036](https://issues.qgis.org/issues/10036), [12698](https://issues.qgis.org/issues/12698)

---

**Comment by jgrocha** [comment]
The map scale can be locked (by enter a value using Data defined override). Then, the map can be resized. The scale does not change. I think the desired behaviour is already supported.
