### ISSUE TITLE
Html formatted labels

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#14063]
Author Name: **Borys Jurgiel** (@borysiasty)
Original Redmine Issue: [4080](https://issues.qgis.org/issues/4080)

Redmine category:map_canvas
Assignee: Nathan Woodrow

---
In addition to expression based labels (#13548), it would be great to have a partial html formatting (e.g. <font size> <b> <i> <br> and <hr>) 
Especially the horizontal line is often required:

some_field || '<hr/>' || another_field

---

- [HTML_Editor.jpg](https://issues.qgis.org/attachments/download/7182/HTML_Editor.jpg) (Azlan Budi)
- [htmllabels.png](https://issues.qgis.org/attachments/download/9613/htmllabels.png) (Nathan Woodrow)

**Comment by alexbruy** [comment]
Duplicates #32098.
