### ISSUE TITLE
Split Features tool: lines are split also at every self-intersection

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#14070]
Author Name: **jcnotter -** (jcnotter -)
Original Redmine Issue: [4087](https://issues.qgis.org/issues/4087)
Affected QGIS version: 3.7(master)
Redmine category:digitising

---
When you use this function to a location, it splits the polyline at each intersections on the polyline and you get a lot of polylines and not 2 as you want
Example : for separating the return track, you get many little tracks ...

---

- [temp.zip](https://issues.qgis.org/attachments/download/3342/temp.zip) (jcnotter -)
- [split.zip](https://issues.qgis.org/attachments/download/9117/split.zip) (Pedro Venâncio)

---

Related issue(s): #29256 (duplicates)
Redmine related issue(s): [21439](https://issues.qgis.org/issues/21439)

---

**Comment by Gusterson** [comment]
Still an issue in QGIS v3.8

**Comment by MoStorm** [comment]
And still an issue in QGIS 3.15.0-Master...

I have tested on temporary scratch layers and PostGIS layers... Both will split a linestring at every intersection, if splitting at any point.

**Comment by paalmiso** [comment]
I've just spent debugging this problem whole day until I've found this open issue. Is there any data I can offer to help diagnose this problem?

**Comment by ainthek** [comment]
uff, same problem here on 3.15.0-Master.
Any workaround ? another algorithm ? way to reconstruct single lines back ?
I have overlaping polylines, and I need to split them on overlap points. from 2 lines I get 2000 lines, instead of 4.
thanx ;-(

**Comment by MMR100** [comment]
@ainthek  as a workaround: 

- I create a buffer of my polylines, 

- cut the buffer where needed 

- then dissolve the lines based on a unique attribute in the buffer layer.

**Comment by Sneeci** [comment]
I have currently the same issue using it on my builder : https://gis.stackexchange.com/questions/393228/qgis-using-split-lines-with-lines-makes-unwanted-cut-on-self-overlapping-lines
Anyone managed to avoid this problem?

**Comment by Pedro-Murteira** [comment]
Still valid on QGIS 3.22.3. (Windows 10)
