### ISSUE TITLE
New Feature: show Raster Band number on Layer Panel entries.

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#14124]
Author Name: **Thaddeus -** (Thaddeus -)
Original Redmine Issue: [4144](https://issues.qgis.org/issues/4144)

Redmine category:rasters
Assignee: Tim Sutton

---
New Feature: show Raster Band number on Layer Panel entries.

In QGIS 1.7 it is very hard to figure out the Raster data one is working on, specially if the project contains many Raster Bands and/or layers or is shared with someone else.

IMHO, it should simply be tagged along the existing "Display classification attribute names in legend", ie, if layer is Raster, show "Band 3" or so accordingly.

It should also be on the "Metadata" tab of "Layer Properties" and other places too.

**Comment by alexbruy** [comment]
Already fixed.
