### ISSUE TITLE
GPS Traking

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#14127]
Author Name: **elcuco -** (elcuco -)
Original Redmine Issue: [4150](https://issues.qgis.org/issues/4150)

Redmine category:gps_live_tracking

---
Hi!
The Live GPS Traking should include more informations such as:
   Dilution of precision (eg. PDOṔ; GDOP)
   Availability of SBAS (WAAS/EGNOS)
   The ability to choose the quality parameters to collect data (maximum PDOP; collect only in 3D and/or DGPS)
   Also, the ability to capture points/vertex by averaging GPS positions (determined by the user); Also it could capture lines or areas by streaming GPS position by time or by distance (the user chooses it's favorite and it's value).
These feature could improve the Live GPS Traking.
Best Regards,
Pedro Ferreira

**Comment by nyalldawson** [comment]
This should be reopened as individual, atomic feature requests
(Some of this has already been solved)
