### ISSUE TITLE
Add ability to refresh the extent of a WFS layer

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#14219]
Author Name: **Alister Hood** (@AlisterH)
Original Redmine Issue: [4280](https://issues.qgis.org/issues/4280)

Redmine category:web_services_clients/wfs

---
After adding a WFS layer with the option "only request features overlapping the current view extent", if the user pans or zooms out, to show all the features in the new map extent they would currently need to remove the WFS layer and add it again.

I don't know much about how WFS works, and whether it would be possible to update the layer extents on-the-fly (like a WMS layer).  But even if that isn't possible, it might be good to add a feature to "update layer to current map extent".

**Comment by DelazJ** [comment]
Based on https://github.com/qgis/QGIS/issues/14219#issuecomment-495615962 is this still an issue? Seems it has been implemented/fixed...

**Comment by alexbruy** [comment]
Closing for the lack of feedback.

**Comment by AlisterH** [comment]
Yes, I think we can consider this implemented (it now always updates).
