### ISSUE TITLE
Store projects in databases

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#14259]
Author Name: **Cupertino Miranda** (Cupertino Miranda)
Original Redmine Issue: [4322](https://issues.qgis.org/issues/4322)

Redmine category:project_loading/saving

---
The idea is to be able to store projects within a central database system.

In a bigger multi-user working scenario, layers are stored within a centralized postgres database.
On the other hand, the environment to access those centralized databases is stored independently locally.

When considering that many of the users of the system might not know anything how the database is organized, it might happen that such users could change properties related to the viewing and editing of those tables jeopardizing correctness of the tables.

In my precise use case, I helped someone define a complex layout of geo tables and relations. After that we created a project with all of the subtleties, on how such tables would be edited and viewed.
Everything perfect up until now ! ;-)
The problem was that we needed to distribute this project through all of its users, and although distribution is problematic, it is even more problematic that its users can modify the project.

For example, imagine a layer that is originally configure to show a combo box (Value Map) with two elements, any of its users can access that same property, edit it, change the value map and start producing mistakes that only very late might be detected.

Using the databases, it might be possible to distribute projects as well as check for permissions on editing its features.

**Comment by alexbruy** [comment]
Already possible.
