### ISSUE TITLE
Making url's in WMS Query response clickable

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#14262]
Author Name: **Tim Couwelier** (Tim Couwelier)
Original Redmine Issue: [4325](https://issues.qgis.org/issues/4325)

Redmine category:web_services_clients/wms

---
In follow-up of this thread on the QGis forums (http://forum.qgis.org/viewtopic.php?f=2&t=9317&sid=5685153a6922412e5102f781eb1bd81f)

Some WMS servers give responses through the info tool that hold url information.
Whereas on user created vector datasets, one can make this possible through 'Actions', this is not possible for WMS layers.

This could be an enhancement to the information tool.

PS: I do hope I put this up in the right spot, as this is a first for me.

**Comment by alexbruy** [comment]
Should be fixed in 539b7cb. Please reopen if necessary.
