### ISSUE TITLE
add resample option/tool to gdal tools

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#14378]
Author Name: **Giovanni Allegri** (@giohappy)
Original Redmine Issue: [4448](https://issues.qgis.org/issues/4448)

Redmine category:processing/gdal

---
I suggest to add another option to those listed in #12990, to let users create a resampled raster setting the output pixel size. Actually it can be done maually setting the -tr option to gdal_translate (e.g. inside the Gdal Translate tool).
We could provide a new tool dedicated to it (Gdal Resample?) or add an option to the Gdal Translate widget.

**Comment by alexbruy** [comment]
Implemented in c224a01
