### ISSUE TITLE
Imported GPS data should be automatically grouped

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#14394]
Author Name: **Gerhardus Geldenhuis** (@ggeldenhuis)
Original Redmine Issue: [4467](https://issues.qgis.org/issues/4467)

Redmine category:map_legend

---
When I import data from my Garmin GPS I get:
track points
route points
tracks
routes
way points

All of these are separate top layers. This is not a big problem until I start importing multiple gpx files. It would be very nice if all items contained within a gpx file could be automatically grouped in a newly created group that takes the name of the file you are importing.

This request is very specific with regards to data that I have worked with but I am sure the concept could be more generically applied to other data that gets imported.

**Comment by alexbruy** [comment]
Probably can be closed as request is quite specific and there is a workaround.
