### ISSUE TITLE
Add a 2 cases if() command to Raster Calculator

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#14403]
Author Name: **alobo -** (alobo -)
Original Redmine Issue: [4476](https://issues.qgis.org/issues/4476)

Redmine category:rasters

---
An if() command with 2 cases output would be most useful:

if(condition, result1, result2)

where the output value is result1 if condition==T and result2 otherwise.

Agus

**Comment by AlisterH** [comment]
I don't think this ticket was really waiting for feedback.  
The question was asked "Was your feature request about a way to have conditions in the raster calculator or about the syntax of the condition?"
The answer was that the request was about the way to have conditions, but now that we know there is a way, the syntax is "weird" and an if() syntax would be more useful.

That's not to say that keeping the ticket open will achieve anything...

**Comment by AlisterH** [comment]
I see #16517 is still open - maybe this can be considered a duplicate of it, and closed.
