### ISSUE TITLE
Add a filter for the "values" list in the query builder and similar dialogs

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#14514]
Author Name: **Giovanni Manghi** (@gioman)
Original Redmine Issue: [4609](https://issues.qgis.org/issues/4609)

Redmine category:gui

---
It should be like the one is now available in CRS selection dialog.

Why: When you hit "all" to show all the values that are in one column, it is likely to have A LOT of values, and find/select the right one can be likely a not handy task.

**Comment by alexbruy** [comment]
Already fixed.
