### ISSUE TITLE
Drop file to Layers not possible when panel is floating

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#14547]
Author Name: **andskog -** (andskog -)
Original Redmine Issue: [4649](https://issues.qgis.org/issues/4649)

Redmine category:gui

---
When, as by default, the Layers panel is docked in QGIS, I can drag and drop GIS files on it. However, if I undock the panel, this feature doesn't work. Is this a bug? (Using 1.7.2)

**Comment by YoannQDQ** [comment]
This is no longer the case.
