### ISSUE TITLE
Add general option to show a dialog to allow enter the name of a (custom) CRS

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#14589]
Author Name: **Giovanni Manghi** (@gioman)
Original Redmine Issue: [4705](https://issues.qgis.org/issues/4705)

Redmine category:projection_support

---
When adding a layer in QGIS that has an explicit CRS that doesn't match anything in the internal QGIS database, then a custom CRS is added, but this has no name.

The new "select CRS" dialog just filters names and official codes (like EPSG) not internal codes.

So, it would be highly valuable to allow the user enter a proper name for custom CRS as they are added to the internal DB by QGIS.

**Comment by nyalldawson** [comment]
You can already rename custom projections via the custom projection dialog
