### ISSUE TITLE
Add the ability to 'Draw a text buffer' to Font Marker's

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#14676]
Author Name: **MRick -** (MRick -)
Original Redmine Issue: [4839](https://issues.qgis.org/issues/4839)

Redmine category:symbology

---
Actually, if we want to have a text symbol layer it is impossible, the only way available is to enter a single letter (font marker).
It is missing the possibility to enter a word or a phrase instead of text as a layer with the following optional settings:
- Font
- Font style (normal, black, italic etc)
- Font size
- Color
- Buffer
- On the line, above (select distance), up (select distance)
- Rotate
- Invert (left to right or right to left, top to bottom or bottom to top)

And so, this makes useless the font marker, since it is more advanced and the font marker is buggy: I can't use dingbats, a lot of special characters are not supported and the window to display the characters map is very very very slow.

**Comment by pjshelton** [comment]
In QGIS 3.16 the font marker now does everything that this feature request asks for except 
for adding a buffer.

I found the character map to be quite responsive, and able to display all printable char.

We can select fonts,
font style,
color
rotate
use the standard 9 point anchor grid for location around the point
invert
add a phrase, or even make it data dependent.
I have also tested with a font from the dingbat family.

@gioman can we please change the name of this to "Add the ability to 'Draw a text buffer' to Font Marker's",  or close and open another with that name.

**Comment by nyalldawson** [comment]
This was implemented through support for setting a stroke on the font marker symbol layer
