### ISSUE TITLE
Join attributes - add the option of creating a shapefile with matching attributes only

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#14728]
Author Name: **Filipe Dias** (@fsdias)
Original Redmine Issue: [4924](https://issues.qgis.org/issues/4924)

Redmine category:vectors
Assignee: Marco Hugentobler

---
Currently the output of the join function keeps all records/features of both shapefiles/tables. It would be useful to add the option of keeping only matching records/features during the table join.

This exists in ArcGIS and is explained in this link, under "Joining attributes in one table to another".

http://webhelp.esri.com/arcgiSDEsktop/9.3/index.cfm?TopicName=Joining_tables

Apparently the join function of mmqgis only keeps matching records.

**Comment by alexbruy** [comment]
Probably we can close this as Processing provides join algorithm which outputs both matching and non-matching records as two separate outputs.

**Comment by alexbruy** [comment]
Closing as Processing tool provides this functionality. Please reopen if necessary.
