### ISSUE TITLE
Add option to avoid intersection of new polygons when doing a (geometry) copy/paste operation

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#14778]
Author Name: **Giovanni Manghi** (@gioman)
Original Redmine Issue: [4997](https://issues.qgis.org/issues/4997)

Redmine category:digitising

---
subject says it all.

**Comment by uclaros** [comment]
@gioman avoid overlaps has been implemented for paste operations, I guess this can close

**Comment by gioman** [comment]
> @gioman avoid overlaps has been implemented for paste operations, I guess this can close

@uclaros thanks!
