### ISSUE TITLE
A window should display a message about D&D feature

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#14896]
Author Name: **Luca Casagrande** (Luca Casagrande)
Original Redmine Issue: [5138](https://issues.qgis.org/issues/5138)

Redmine category:db_manager

---
I think that would be good to have a reference about the drag and drop feature; something like an info window (with a "Don't show anymore checkbox") when starting the plugin.

**Comment by nyalldawson** [comment]
wontfix
