### ISSUE TITLE
ability to temporarily override or toggle all snapping

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#14904]
Author Name: **Alister Hood** (@AlisterH)
Original Redmine Issue: [5152](https://issues.qgis.org/issues/5152)

Redmine category:digitising

---
(previously #10719)
It would be good if there was a way to temporarily override snapping, rather than having to turn it off for each layer in the snapping options, and then turn it back on again for each layer.

According to the user manual the OpenStreetMap plugin disables snapping if you hold the ctrl key down while clicking, so it would probably be good to do the same.  Would this interfere with any current behaviour?

A slightly different approach is what some CAD programs do - you toggle snapping on and off by pressing something like F3.  This approach would probably require something in the status bar to display the current state - I guess there should be a checkbox in the status bar, then you could also toggle it with the mouse.

**Comment by uclaros** [comment]
Toggle snapping has a changeable shortcut defaulting to 'S'. This can close
