### ISSUE TITLE
Rendering Symbol level: merge the boundary when the level is the same

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#14953]
Author Name: **aperi2007 -** (aperi2007 -)
Original Redmine Issue: [5217](https://issues.qgis.org/issues/5217)

Redmine category:symbology

---
Hi, I guess in the rule rendering, using the symbol level, when two feature are touching on a portion each-other and both have the same value for symbol level, the boundary could be merge disappearing.
In the image I attach to this ticket, there are two feature with the same value in the rulerendering, so both has the same level in the symbol-level order. I guess the two boundary (I circled they with a red line) where they are touching each-other should disappeared.

---

- [image1.gif](https://issues.qgis.org/attachments/download/4336/image1.gif) (aperi2007 -)

**Comment by pjshelton** [comment]
This is a special case of #27540.
This and #17943 and #27540 and #21642 are all requesting a general Merge connected objects for symbology.

**Comment by nyalldawson** [comment]
This can be closed -- the desired functionality exists and has already been explained in the previous comments
