### ISSUE TITLE
Modify default options in QGIS

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#14952]
Author Name: **Simon Georget** (@simogeo)
Original Redmine Issue: [5216](https://issues.qgis.org/issues/5216)

Redmine category:unknown

---
It would be nice if we could change default QGIS options. 
For example, the default font used by QGIS composer on my system is ubuntu. I'd like to change that.
Another point, I'd like when creating an object, to have no border! 

A user option file (like in scite editor for example), would be worth value.

Here is the basic idea. It should, fore sure, be adapted since I do not know how QGIS configuration options are stored, now.

```
composer.default_font = 'Arial';
composer.default_object.border.width = 0; 

```

That come from gis.stackexchange : http://gis.stackexchange.com/questions/21845/modify-default-options-in-qgis

**Comment by suricactus** [comment]
This is already present. This issue should be closed.
Configure fonts:
![image](https://user-images.githubusercontent.com/2820439/76494361-56c8bc00-643d-11ea-9755-e640d684e9f7.png)
Configure default styles:
![image](https://user-images.githubusercontent.com/2820439/76494550-c474e800-643d-11ea-9d9c-3ae893b81542.png)
