### ISSUE TITLE
No default Point geometry when creating a new Vector layer

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#14983]
Author Name: **Richard Duivenvoorde** (@rduivenvoorde)
Original Redmine Issue: [5249](https://issues.qgis.org/issues/5249)

Redmine category:gui

---
Several times I have created a new *Point* layer (after setting 10 attributes) while what I wanted was to create a *Polygon* layer. 

It would be nice if the create Vector layer dialog NOT choose a default geometry type Point for me, but would just complain when I try to create it without choosing one of the options.

ps this is an example of a PaperCut issue see https://issues.qgis.org/projects/quantum-gis/wiki/OneHundredPaperCuts

**Comment by suricactus** [comment]
I think this is already the case - by default there is no geometry type. Close?

**Comment by gioman** [comment]
> I think this is already the case - by default there is no geometry type.

it is still the case (for shp) and for other data sources (i.e. gpkg) it defaults to geometryless. What is being asked it to default to nothing, making mandatory for the user to choose one option.

**Comment by rduivenvoorde** [comment]
Yes, indeed. Now by default you have a 'geometry-less' shp or gpkg :-(
WHO EVER (as a geo-guy) want that ;-) 
So I would indeed opt for a mandatory option which you HAVE to choose first.
Thanks
