### ISSUE TITLE
Automatic reporting of errors

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#15055]
Author Name: **Paolo Cavallini** (@pcav)
Original Redmine Issue: [5370](https://issues.qgis.org/issues/5370)

Redmine category:processing/gui

---
It would be nice if in case of an error, the user could automatically send the log (by clicking on an OK button) to a mailing list, so that errors could be compared, and automatically archived.

**Comment by roya0045** [comment]
Isn't this what the crash logs are now?
