### ISSUE TITLE
Add ”Select by rectangle” in modeler

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#15089]
Author Name: **Magnus Nilsson** (Magnus Nilsson)
Original Redmine Issue: [5453](https://issues.qgis.org/issues/5453)

Redmine category:processing/modeller
Assignee: Victor Olaya

---
Add possibility to select multiple objects with ”Select by rectangle” in modeler.

---

Related issue(s): #24173 (duplicates)
Redmine related issue(s): [16263](https://issues.qgis.org/issues/16263)

---

**Comment by nyalldawson** [comment]
Implemented in 3.14
