### ISSUE TITLE
Add support for undo/redo actions, such as deleting an object in modeler

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#15097]
Author Name: **Magnus Nilsson** (Magnus Nilsson)
Original Redmine Issue: [5471](https://issues.qgis.org/issues/5471)

Redmine category:processing/modeller
Assignee: Victor Olaya

---
Add support for undo/redo actions, such as deleting an object in modeler

---

Related issue(s): #24172 (duplicates)
Redmine related issue(s): [16262](https://issues.qgis.org/issues/16262)

---

**Comment by nyalldawson** [comment]
Implemented in 3.14
