### ISSUE TITLE
Support for group boxes

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#15090]
Author Name: **Magnus Nilsson** (Magnus Nilsson)
Original Redmine Issue: [5455](https://issues.qgis.org/issues/5455)

Redmine category:processing/modeller
Assignee: Victor Olaya

---
Add support for adding boxes around a set of tools that perform a task together, i.e. creating groups of tools in the modeler. That would help organize the model better.

---

Related issue(s): #26886 (duplicates)
Redmine related issue(s): [19056](https://issues.qgis.org/issues/19056)

---

**Comment by alexbruy** [comment]
Already possible in master.
