### ISSUE TITLE
Support copy/paste of objects in modeler

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#15101]
Author Name: **Magnus Nilsson** (Magnus Nilsson)
Original Redmine Issue: [5479](https://issues.qgis.org/issues/5479)

Redmine category:processing/modeller
Assignee: Victor Olaya

---
I´d like to see support for copy/paste of objects in modeler. Sometimes you need multiple versions of the same tool, so being able to copy/paste would help.

---

Related issue(s): #24190 (duplicates)
Redmine related issue(s): [16280](https://issues.qgis.org/issues/16280)

---

**Comment by alexbruy** [comment]
Already possible in master
