### ISSUE TITLE
add tooltip on fields in identify window / attribute window / feature form

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#15144]
Author Name: **Regis Haubourg** (@haubourg)
Original Redmine Issue: [5559](https://issues.qgis.org/issues/5559)

Redmine category:gui

---
Many times, fields name are short and not explicit enough to understand their meaning. 
Comments are already available in fields properties and are perfect for that. Thoses comments are really nicely integrated when using Postgis.
 
I would love to have tooltips displaying comments, real name if alias is used and maybe field type and precision. see attached pictures for examples
Anyone interested in it?

---

- [qgis_field_comment_tooltip.jpg](https://issues.qgis.org/attachments/download/4453/qgis_field_comment_tooltip.jpg) (Regis Haubourg)

**Comment by suricactus** [comment]
This is easy to fix and nice to have. I would suggest to add a function `QString QgsField::displayNameTooltip()`, that returns the desired tooltip, similar to `QgsField::displayNameWithAlias()` and `QgsField::displayName()`. This way the field tooltips can be unified across the tools and plugins.

![image](https://user-images.githubusercontent.com/2820439/76914904-45abff00-68c4-11ea-9f8c-27916afe0527.png)
