### ISSUE TITLE
Defining column types for CSV imports

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#15179]
Author Name: **Kenton Ngo** (Kenton Ngo)
Original Redmine Issue: [5606](https://issues.qgis.org/issues/5606)

Redmine category:data_provider/delimited_text_

---
At work we use Mac OS X. Microsoft Office for Mac no longer supports DBF exports, and much of our data that we'd like mapped lives in Excel-compatible files. 

I'm currently exporting as CSV using this workaround, but it requires me to create a CSVT file, an annoying extra step. http://underdark.wordpress.com/2011/03/07/how-to-specify-data-types-of-csv-columns-for-use-in-qgis/

Is there any way to eliminate this extra step by allowing a user to define the column types at import?

---

Related issue(s): #14176 (duplicates), #21113 (duplicates)
Redmine related issue(s): [4212](https://issues.qgis.org/issues/4212), [13038](https://issues.qgis.org/issues/13038)

---

**Comment by haubourg** [comment]
closed duplicate of https://github.com/qgis/QGIS/issues/21113
