### ISSUE TITLE
OWS metadata URL

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#15241]
Author Name: **Brent Wood** (Brent Wood)
Original Redmine Issue: [5727](https://issues.qgis.org/issues/5727)

Redmine category:unknown

---

Earlier versions of QGIS had the (very useful for me) full getfeature URL listed in the metadata for WMS/WFS layers.

This was a very useful bit of text to paste into a browser to either get a WMS image, or to help debug the underlying WMS/WFS service.

Recent versions of QGIS no longer provide the full GetMap/GetFeature URL, at least not that I can see. It is somewhat painful to handcraft the full URL with all parameters.

Is it possible to restore this item to the metadata list for OWS layers in future versions?

**Comment by alexbruy** [comment]
Should be fixed in master. Please check.

**Comment by pathmapper** [comment]
@alexbruy just checked with QGIS 3.16, for

- WFS: https://geoservices.krzn.de/security-proxy/services/wfs_kvie_jagdbezirke
There is no `getFeatureUrl` at all.

- WMS: https://www.wms.nrw.de/geobasis/wms_nw_dop
There is a `getMapUrl`, but it's not complete - it shows: "advertised but ignored":
![grafik](https://user-images.githubusercontent.com/20856381/97573906-bd114780-19ea-11eb-9580-19e0adb3a7b2.png)
