### ISSUE TITLE
define new or edit existing colorbrewer schemes

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#15425]
Author Name: **Otto Dassau** (Otto Dassau)
Original Redmine Issue: [6064](https://issues.qgis.org/issues/6064)

Redmine category:symbology

---
Hi,

to define new colorbrewer schemes, like Spectral, Set2, etc it is currently necessary to edit /src/core/symbology-ng/qgscolorbrewerpalette.h and compile QGIS. It would be a nice feature to be able to define new colorbrewer schemes in QGIS without the need to recompile or to change the random color ramps in the style manager.

Regards
Otto

**Comment by pjshelton** [comment]
Between Catalog: cpt-city and Catalog: ColorBrewer most of the ColorBrewer colour ramps are already in QGIS. 

However, if there is a colour ramp you want that is not in the pre-configured set, you can create a new colour ramp using the 
Gradient ramp and edit it as you want.  it will save in the default list.

@gioman this can be closed as complete
