### ISSUE TITLE
Allow manually change project CRS from project properties when OTFR is OFF

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#15435]
Author Name: **Giovanni Allegri** (@giohappy)
Original Redmine Issue: [6081](https://issues.qgis.org/issues/6081)

Redmine category:gui

---
It's not easy to explain :)
I have EPSG:4326 as default CRS, with OTFR activated. I change the CRS (e.g. select EPSG:3003) but when I deactivate OTFR, the CRS is rolled back to EPSG:4326. If I activate OTFR again, EPSG:3003 is selected again.
I have to "Apply" the selected CRS before deactivating OTFR to make QGis keep the selected CRS.
If it's not clear I will try to explain with a video...

**Comment by nyalldawson** [comment]
No longer applies since QGIS 3.0
