### ISSUE TITLE
Tab-stops inside label

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#15449]
Author Name: **Matthias Kuhn** (@m-kuhn)
Original Redmine Issue: [6106](https://issues.qgis.org/issues/6106)

Redmine category:labelling

---
To arrange info in a tabular look, it is common to use tab-stops. Inside the Print Composer, when adding a label it is possible to layout the text with tabs (In Item Properties / Label )

Nevertheless, this layout is not reflected inside the actual label.

E.g.
I want to add some information like:
```
Source:  OpenStreetMap
Date:    27.7.2012
Author:  Matthias Kuhn

```
I want the values to be in the same horizontal offset, but they are not aligned.

Is this already possible (maybe with another tool than label)?

If not:
- Different fonts and their spacings could be a problem. So maybe it would be necessary to add a ruler to control tab-stops to the label text field?

- With an additional table tool this could be achieved as well

**Comment by pjshelton** [comment]
@m-kuhn in version 3.16.3 you can now put a fixed table on a  print composer.  This satisfies your alignment requirement.
![image](https://user-images.githubusercontent.com/39154868/107180214-ff9fe280-6a23-11eb-9977-53debd9c0b1b.png)

Would you be okay if this gets closed?

@gioman

**Comment by gioman** [comment]
> Would you be okay if this gets closed?
> 
> @gioman

@pjshelton I'll let Matthias @m-kuhn  decide if he is ok with it.

**Comment by m-kuhn** [comment]
Long time ago this was. Thanks for answering 👍 

This can be used to fulfill the original requirement in the example.
I assume there are some requirements which are still hard to do (optional rows in an atlas?) but happy to close this and open a new one when/whoever has this updated requirement.
