### ISSUE TITLE
Add "libqt4-sql-psql" and "libqt4-sql-sqlite" as dependencies (otherwise eVis won't work)

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#15472]
Author Name: **Giovanni Manghi** (@gioman)
Original Redmine Issue: [6144](https://issues.qgis.org/issues/6144)

Redmine category:build/install

---
Otherwise core tools like eVis won't work out of the box under Linux.

**Comment by nyalldawson** [comment]
The evis plugin has been removed for qgis 3.14 and is no longer supported
