### ISSUE TITLE
store settings for recently used algorithms

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#15481]
Author Name: **Salvatore Larosa** (@slarosa)
Original Redmine Issue: [6160](https://issues.qgis.org/issues/6160)

Redmine category:processing/gui
Assignee: Victor Olaya

---
Would be useful add the support to store settings for recently used algs, especially for FieldPyculator alg and other in which is need to write of the code, so speed up the operation!

**Comment by alexbruy** [comment]
In master it is possible to save algorithm settings as JSON and paste them back. Does it fixes this?
