### ISSUE TITLE
load geophoto

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#15494]
Author Name: **Giovanni Manghi** (@gioman)
Original Redmine Issue: [6180](https://issues.qgis.org/issues/6180)

Redmine category:db_manager

---
moved from https://trac.faunalia.it/qgis_plugins/ticket/4

It will be also useful to add geotagged photos, extracting their localization

---

Related issue(s): #24650 (duplicates)
Redmine related issue(s): [16751](https://issues.qgis.org/issues/16751)

---

**Comment by nyalldawson** [comment]
A native processing algorithm to do this is now available
