### ISSUE TITLE
Should be able to use groups/filter etc to select styles for import/export

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#15540]
Author Name: **Alister Hood** (@AlisterH)
Original Redmine Issue: [6231](https://issues.qgis.org/issues/6231)

Redmine category:gui

---
In the "Styles import/export" dialogue all the styles are mixed up, regardless of the type of style (Marker, line, etc), the group, or whether they are your own custom styles or predefined ones that come with QGIS.  There is no way of sorting or filtering - all you can do is "select all", or go through manually and select the ones you want.

There really should be a way to use the capabilities of the main style manager dialogue (filtering, grouping, and the tabs for different types of style) to select the styles for import/export.  

I don't know how the gui for this would be best done - maybe just a tool in the main style manager dialogue to mark styles for export/import, then when you've marked all the ones you want you hit the export/import button.  Maybe multiple selection is sufficient for this... I guess things can remain selected when you click on another tab, but what about when it is hidden because you change the filter?

**Comment by alexbruy** [comment]
Already possible
