### ISSUE TITLE
External HTML img maptips

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#15554]
Author Name: **Rocco Pispico** (Rocco Pispico)
Original Redmine Issue: [6247](https://issues.qgis.org/issues/6247)

Redmine category:unknown
Assignee: Nathan Woodrow

---
I try to set <img src="www.repubblica.it" />

**Comment by YoannQDQ** [comment]
`QgsMapTip `has been using `QWebView `since QGIS 2.16 (cf. 45227e51d88a822409ef04e3c932fb10d4fc2a85).
Closing as resolved
