### ISSUE TITLE
Open file folder / location

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#15606]
Author Name: **James Stott** (@jamesstott)
Original Redmine Issue: [6314](https://issues.qgis.org/issues/6314)

Redmine category:unknown

---
Would it be possible to add an option to the Layer / Right click menu to open the folder of a layer that comes from a file (shp, tab, csv etc).

For files that cannot be edited directly in QGIS I often find myself navigating to the file and then opening it in other software (MapInfo, Excel / LibreOffice) or when I want to email someone a layer that I already have open. Having this ability would allow me to use QGIS to open the folder of the dataset automatically and then open the file by either dragging it to the other application or by double clicking it to launch the relevant application.

At the moment I copy the file path from the Metadata tab in layer properties (minus the filename).

**Comment by Saijin-Naib** [comment]
I too would love to see this feature, especially with the nature of how and where temporary processing results get stored.

Having a button somewhere (right-click context menu in the layer list? A button on the Layer Properties GUI, perhaps in the information/source tab?) would be incredibly helpful.

**Comment by roya0045** [comment]
@Saijin-Naib you know that if you go in property-­>information you can click the link, its one more click but it also selects the layer. I feel like this is pretty much solved.

**Comment by Saijin-Naib** [comment]
I'm aware of the hyperlink to the data file, and I whole-heartedly disagree that this solves this use-case. That opens the product directly in the Operating System's default application, which does not (always) present the same file-management capabilities that one would likely be looking for when trying to find the containing folder of a piece of data. For instance, move/copy/rename, etc.

**Comment by baswein** [comment]
I too would use this function. Or at least the ability to add a keyboard shortcut that opened the file browser to the location of the currently selected layer. 
In 3.20 on windows the hyperlink file path does open the file browser (windows explorer). 
![file_path](https://user-images.githubusercontent.com/15817745/145683153-12da2b45-74e8-4902-a531-525a62f2a820.gif)

**Comment by alexbruy** [comment]
This is already possible, there is a "Show in Files" item in the context menu which opens file manager.

**Comment by baswein** [comment]
@alexbruy  thanks for looking into this however I'm not seeing it in the context menu on Windows 10 QGIS 3.23. Am I missing something? 
![image](https://user-images.githubusercontent.com/15817745/148391774-991b1e3e-584c-4c6e-9e60-f07f9de33eb8.png)
