### ISSUE TITLE
WCS: the button to cancel download does nothing

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#15615]
Author Name: **Paolo Cavallini** (@pcav)
Original Redmine Issue: [6332](https://issues.qgis.org/issues/6332)
Affected QGIS version: 3.4.5
Redmine category:web_services_clients/wcs

---
One is forced to kill QGIS in this case

**Comment by benoitdm-oslandia** [comment]
Can you add a WCS source example that is slow enough to illustrate the issue?

**Comment by benoitdm-oslandia** [comment]
Work correctly in master branch with https://elevation.nationalmap.gov/arcgis/services/3DEPElevation/ImageServer/WCSServer and 'save layer as' function: download stop properly when cancel clicked.

**Comment by gioman** [comment]
> Seems to correctly in master branch with https://elevation.nationalmap.gov/arcgis/services/3DEPElevation/ImageServer/WCSServer and 'save layer as' function: download stop properly when cancel clicked.

@benoitdm-oslandia thanks for looking into this. When we ask questions to the issuer we add the "feedback" label to the ticket, so we know it is expected some kind of feedback. If after a few weeks we don't get any answer, then we close the ticket if we can't replicate the issue.

**Comment by benoitdm-oslandia** [comment]
thanks @gioman

**Comment by gioman** [comment]
> Seems to work correctly in master branch with https://elevation.nationalmap.gov/arcgis/services/3DEPElevation/ImageServer/WCSServer and 'save layer as' function: download stop properly when cancel clicked.

Closing as fixed/implemented.
