### ISSUE TITLE
"Current Visible Extent" for Raster calculator

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#15778]
Author Name: **Jonathan Moules** (Jonathan Moules)
Original Redmine Issue: [6587](https://issues.qgis.org/issues/6587)

Redmine category:raster_calculator

---
The Raster Calculator has a "current layer extent" button to allow easy creation of correctly sized rasters.

My suggestion is to add another button: "Current Visible Extent" which when clicked will fill in the bounds etc for the current visible extent.

**Comment by ismailsunni** [comment]
Duplicate https://github.com/qgis/QGIS/issues/45247
