### ISSUE TITLE
Preview in expression builder not always showing

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#15803]
Author Name: **Paolo Cavallini** (@pcav)
Original Redmine Issue: [6616](https://issues.qgis.org/issues/6616)
Affected QGIS version: 3.0.0
Redmine category:gui

---
The preview in the field calculator expression builder is often missing. This happens because the expression text is evaluated against the first feature in the layer. If the expression doesn't evaluate for the first feature there will be no text. 

Thanks Nathan for the explanation.

**Comment by alexbruy** [comment]
Now it is possible to switch between features for the preview. Probably can be closed.
