### ISSUE TITLE
Add support for "unknown" units

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#15801]
Author Name: **Sandro Santilli** (@strk)
Original Redmine Issue: [6614](https://issues.qgis.org/issues/6614)

Redmine category:unknown

---
It often happens that qgis doesn't know what the units of the input data are.
In those cases qgis currently makes a guess, but the guess is often wrong, and surely arbitrary.

This ticket is to add support for "unknown" units, and ensure all tools use a centralized
view of what the current map units are so that all agree on the units.

For tools that really want to show a unit name, we should use a name which clearly reflects the unknown.
The unit could be called just "unit" (Area: 32 square units) or could be picked up from this nicelist:
http://en.wikipedia.org/wiki/List_of_humorous_units_of_measurement

**Comment by nyalldawson** [comment]
This can be closed -- QGIS has supported "unknown" crs/units since 3.0
