### ISSUE TITLE
Curved labels : max angle delta between letters

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#15845]
Author Name: **Laurent Gasnier** (Laurent Gasnier)
Original Redmine Issue: [6673](https://issues.qgis.org/issues/6673)

Redmine category:labelling

---
Hi,
In new labeling tool, it would be useful for the user to set the value of the max angle delta between letters (like MAXOVERLAPANGLE of Mapserver).

See attached screenshot test_anno_curv_roubion2.png: Black labels are drawn by a WMS Mapserver layer, red labels by QGIS.

The label "Le Roubion" is drawn only if MAXOVERLAPANGLE is set to 30 in .map file (with default value, it's not drawn).

---

- [test_anno_curv_roubion2.png](https://issues.qgis.org/attachments/download/5062/test_anno_curv_roubion2.png) (Laurent Gasnier)
- [test_anno_curv_roubion_outside_angle_40.png](https://issues.qgis.org/attachments/download/5140/test_anno_curv_roubion_outside_angle_40.png) (Laurent Gasnier)
- [test_canal_de_bourgogne.png](https://issues.qgis.org/attachments/download/5141/test_canal_de_bourgogne.png) (Laurent Gasnier)
- [labels.jpg](https://issues.qgis.org/attachments/download/5144/labels.jpg) (Regis Haubourg)

---

Related issue(s): #15916 (relates)
Redmine related issue(s): [6763](https://issues.qgis.org/issues/6763)

---

**Comment by pjshelton** [comment]
@haubourg Did #29994 fix this particular problem? 
the labeling gui has allowed for adjusting the maximum angle between curved characters, both inside and outside now for a number of versions.

Can we call this closed?

@gioman?

**Comment by haubourg** [comment]
Thanks for the cleanup! Yes we can close this.
