### ISSUE TITLE
"Save as" - Allow to specify field names when they need to be shortened

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#15872]
Author Name: **Alister Hood** (@AlisterH)
Original Redmine Issue: [6707](https://issues.qgis.org/issues/6707)

Redmine category:vectors
Assignee: Marco Hugentobler

---
When doing "save as" with a joined table, the field names are typically truncated a lot.  They are also truncated when doing "save as" to a format which does not allow field names as long as in the original layer.

This behaviour could be improved, e.g. when the names need to be truncated a dialog could be provided allowing the user to specify field names.

**Comment by alexbruy** [comment]
Already possible
