### ISSUE TITLE
Use more robust format (e.g. standard csv) when copying features to an external program

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#15876]
Author Name: **Alister Hood** (@AlisterH)
Original Redmine Issue: [6711](https://issues.qgis.org/issues/6711)

Redmine category:vectors

---
If you copy and paste vector features from QGIS into another program such as a text editor or a spreadsheet, it uses a simple tab separated format, with each feature on a new line, and no escaping mechanism.  This is not very robust - wouldn't it be better to copy in a standard csv format or something?

To demonstrate, open the attached shapefile, select all the features, and copy them to a text editor or spreadsheet.  Because one of the features has newlines in the first field, you don't get a sensible result.

---

- [test_copy.zip](https://issues.qgis.org/attachments/download/5084/test_copy.zip) (Alister Hood)

**Comment by alexbruy** [comment]
Seems already fixed. Please reopen if necessary.

**Comment by AlisterH** [comment]
Yes, attributes with newlines are now quoted.
The result is still a little strange when pasted into Excel, but I'm blaming Excel :)
