### ISSUE TITLE
replace the vector query builder with the new expression builder

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#15992]
Author Name: **Giovanni Manghi** (@gioman)
Original Redmine Issue: [6858](https://issues.qgis.org/issues/6858)

Redmine category:vectors
Assignee: Nathan Woodrow

---
Nathan I give this to you, but if it is not the case please remove yourself.

The new expression builder seems to have been added in many places (like for example in the WFS client, where anyway it doesn't seems to be able to retrieve layer column values) but not in the vector query builder.

**Comment by pathmapper** [comment]
@gioman is this resolved with https://github.com/qgis/QGIS/pull/40071?

**Comment by gioman** [comment]
> @gioman is this resolved with #40071?

No, but it seems clear now that what was originally requested is not so easy to implement, so closing.
