### ISSUE TITLE
new feature request: split polygons with another layer

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#16124]
Author Name: **Andrea Spisni** (Andrea Spisni)
Original Redmine Issue: [7034](https://issues.qgis.org/issues/7034)

Redmine category:unknown

---
Hy there,
Hy would like tio suggest a new feature to be included in qgis: split polygons with another layer (similar to ArcGIS).
The command should split an input polygons layer based on a field of another layer. The output will be different shp files according to field value.

**Comment by alexbruy** [comment]
Can we close this?

**Comment by alexbruy** [comment]
Closing as requested functionality available via Processing.
