### ISSUE TITLE
Inconsistent use of strings

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#16137]
Author Name: **Paolo Cavallini** (@pcav)
Original Redmine Issue: [7050](https://issues.qgis.org/issues/7050)
Affected QGIS version: 3.0.0
Redmine category:gui

---
Several strings are used with different capitalization in the code, e.g.

* Null Null NULL and NODATA NoData and nodata
* "Horizontal and vertical" and "Horizontal and Vertical"
* HTML, Html, and html

Better adhere to a standard (which?)

**Comment by nyalldawson** [comment]
Let's tackle this on a case by case basis. This ticket hasn't had any movement in 7 years, so another approach is needed
