### ISSUE TITLE
Snapping priority - Prioritise vertices over lines

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#16143]
Author Name: **Stuart Ladd** (Stuart Ladd)
Original Redmine Issue: [7058](https://issues.qgis.org/issues/7058)

Redmine category:digitising

---
Supposing I have several polyline/gon layers when digitising, or even just one layer:

First geomerty, A, has a line (or part of a polygon).
Second geometry, B, has 2 vertices (and the line between) snapped to a segment of A's line.

When I digitise a new geometry that needs to meet those 2 vertices exactly (either contained inside B or 100% non-intersecting with B, or overlapping), the digitiser snaps to the line but cannot snap accurately to the vertices.

It would be nice to have a tighter snap when you approach a vertex which happens to lie on a line. And/or some kind of indicator/highlighting of what is being snapped to (a la Illustrator for example).

Because of variations in layers and perhaps wanting to overlap, the 'Avoid Int' option does not acheive what is needed.

**Comment by alexbruy** [comment]
Still valid?

**Comment by olivierdalang** [comment]
No we can close the issue 👍
