### ISSUE TITLE
"All support formats" file open option

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#16175]
Author Name: **Jonathan Moules** (Jonathan Moules)
Original Redmine Issue: [7094](https://issues.qgis.org/issues/7094)

Redmine category:gui

---
Currently when opening a file, be it vector, raster, or style, the file-open dialog has only allows one supported filetype to be shown at once.
I.e. When opening a style, you can via either *.qml or *.sld, but not simultaneously.

What QGIS should do (and ArcGIS and MS Excel both do this) is have a default option which is "All supported formats". In the case of Styles it would show both QML and SLD at the same time. In the case of rasters or vectors it would show applicable formats that QGIS supports.

If the user wants to only see one specific format (i.e. .shp), they can still select it from the drop-down menu.

Note: This is different from "All Formats" - which shows formats that are unsupported too.

**Comment by alexbruy** [comment]
Duplicates #13239.
