### ISSUE TITLE
Show layer groups in "identifiable layers" and "snapping options" panels

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#16209]
Author Name: **Giovanni Manghi** (@gioman)
Original Redmine Issue: [7145](https://issues.qgis.org/issues/7145)

Redmine category:gui

---
On large projects the layers are very often organized in groups.

So when you open "identifiable layers" if groups are not shown you see a very long list of layers, and detecting what is to be checked and what not is very hard.

ideally in this panel the structure of the TOC should be replicated.

**Comment by jdugge** [comment]
This seems to have been implemented in the meantime:
![Project_properties_data_sources](https://user-images.githubusercontent.com/2399255/59204410-dcfb5d80-8ba0-11e9-9582-06f36ca5838a.png)
![project_snapping_options](https://user-images.githubusercontent.com/2399255/59204415-df5db780-8ba0-11e9-87af-3c7f02c7c730.png)

It would be useful to also display the layer groups in the "Add Layer to Legend" dialog for the Legend layout item, which currently still uses a flat list.

![Add_layer_to_legend](https://user-images.githubusercontent.com/2399255/59204598-44b1a880-8ba1-11e9-96af-63c4453e4c7f.png)
