### ISSUE TITLE
Loading WMS services from ArcGIS

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#16325]
Author Name: **santiago Horcajo** (santiago Horcajo)
Original Redmine Issue: [7345](https://issues.qgis.org/issues/7345)

Redmine category:web_services_clients/wms

---
In QGIS 1.8, when you load a full WMS service from ArcGIS, the layers are presented in the reverse order as proyected in ArcGIS. The only way now to solve the problem is to select the different layers of the WMS service in the QGIS form one by one and down to top. If you have many layers this can be a bit lengthy.
May be it could be created a button to reverse the order of the layers in "Layer order" section of the form.
Thank in advance,
Santiago Horcajo

**Comment by alexbruy** [comment]
Still true with master/3.12?
