### ISSUE TITLE
allow measure tool to apply to existing features

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#16366]
Author Name: **John Sankey** (John Sankey)
Original Redmine Issue: [7397](https://issues.qgis.org/issues/7397)

Redmine category:unknown

---
Currently, it seems that the measure tool only works for an existing feature if that feature is retraced on the fly. It would save a huge amount of work with complex features if it would measure the currently selected feature; even better if it could also sum the measure of all features in a layer. (If it already does this, a reply to
http://gis.stackexchange.com/questions/54663/qgis-1-8-0-mac-where-is-measure-window-or-measure-area-symbol
would be most appreciated.)

**Comment by DelazJ** [comment]
If I understand correctly, this is about using area function or the statistics panel. So should probably be closed. @alexbruy ?
