### ISSUE TITLE
raster calculator really needs support for conditional statements (to allow reclassify rasters)

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#16517]
Author Name: **Giovanni Manghi** (@gioman)
Original Redmine Issue: [7581](https://issues.qgis.org/issues/7581)

Redmine category:rasters

---
One of the most common tasks a user can do in a raster workflow is to reclassify raster maps.

At this stage the raster calculator does not support conditional statements, so it is not possible to say (for example):

(ASTGTM2_N37W026_dem@1<=30)=1 OR (ASTGTM2_N37W026_dem@1>30)=2 OR (ASTGTM2_N37W026_dem@1>200)=5

the workaround is awful

(ASTGTM2_N37W026_dem@1<=30)*1 + (ASTGTM2_N37W026_dem@1>30)*2 + (ASTGTM2_N37W026_dem@1>200)*3

as the raster calc just return 1 or 0, so the user must multiply for the needed value doing also a few sums along the way (because it is not possible to use conditions).

---

Related issue(s): #19926 (relates)
Redmine related issue(s): [11682](https://issues.qgis.org/issues/11682)

---

**Comment by hermarman** [comment]
I would add not only it is important for aesthetical or practical reasons, as already mentioned. With the current syntax there is no way to perform short-cut boolean evaluation, therefore it is not possible to perform a task as simple as checking for zeroes in the denominator before calculating a division to assign a flag value other than NaN.
