### ISSUE TITLE
Make AutoIndentation possible in python console

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#16561]
Author Name: **vinayan Parameswaran** (vinayan Parameswaran)
Original Redmine Issue: [7640](https://issues.qgis.org/issues/7640)

Redmine category:python_plugins

---
It would be great to have auto indentation after ':' signs.

For example, the below snippet would fail.

```
lst = ['a','b','c','d']
for i in lst:
print i
  File "<input>", line 2
    print i
        ^
IndentationError: expected an indented block

```

To make it work, we need to add required spaces to indent the lines after the ':' sign
```
lst = ['a','b','c','d']
for i in lst:
    print i
a
b
c
d

```

**Comment by YoannQDQ** [comment]
This already works (since at least QGIS 3.0 I believe)
