### ISSUE TITLE
Customization, Warning when disabling settings menu

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#16640]
Author Name: **Matthias Kuhn** (@m-kuhn)
Original Redmine Issue: [7733](https://issues.qgis.org/issues/7733)

Redmine category:customisation_framework

---
Currently it is possible to disable the settings menu with the customization tool.
It is a valid operation, but hard to undo, because it's disabling its own UI.
This should either be hidden and only enabled, when the user clicks a "Advanced" checkbox or spitting out a warning to make the user aware of what he's doing and telling him also, how to undo this.

**Comment by suricactus** [comment]
This is no longer the case, should be closed.
