### ISSUE TITLE
Add option to see feature count by default

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#16671]
Author Name: **Giovanni Manghi** (@gioman)
Original Redmine Issue: [7775](https://issues.qgis.org/issues/7775)

Redmine category:map_legend

---
It would be good to have a new option to allow the user see the vector feature count by default after adding a vector in a project.

**Comment by flowrean** [comment]
I think what was meant is avoiding having to right click, and always showing the feature counts without requiring user interaction.

**Comment by pathmapper** [comment]
Implemented by @nyalldawson in https://github.com/qgis/QGIS/pull/48088
