### ISSUE TITLE
Layer name in Properties window

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#16714]
Author Name: **Pekka Sarkola** (@posikifi)
Original Redmine Issue: [7831](https://issues.qgis.org/issues/7831)

Redmine category:unknown

---
There could be some misunderstandings in "Layer properties" when you change Layer name.

I think after "displayed as", text should not be in side textbox, but just plain text. See image.

Tested on Win7, master revision A60e74a

---

- [LayerName.png](https://issues.qgis.org/attachments/download/5692/LayerName.png) (Pekka Sarkola)

**Comment by suricactus** [comment]
The "displayed as" box is already rendered differently and the confusion should be gone. Close.
![image](https://user-images.githubusercontent.com/2820439/76499628-ca6fc680-6447-11ea-8dc2-4c1dac7afca3.png)
