### ISSUE TITLE
Color name tooltips in 'Select Color' dialog box

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#16744]
Author Name: **Thomas McAdam** (Thomas McAdam)
Original Redmine Issue: [7869](https://issues.qgis.org/issues/7869)

Redmine category:unknown

---
People who suffer from color blindness or color perception problems, can depend heavily on the rollover tooltips in the color select dialogs. It would be great to have these color tooltips in QGIS. Color blindness effects 7-10% of men and 0.5-1% women, so I am sure this would benefit many users.

**Comment by nyalldawson** [comment]
This has been around since 2.x
