### ISSUE TITLE
Make mapping/editing of infrastructure networks easier

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#16783]
Author Name: **timmie -** (timmie -)
Original Redmine Issue: [7911](https://issues.qgis.org/issues/7911)

Redmine category:digitising

---
A typical infrastructure network (water, gas, electricity, telecom) usually has:
* nodes (pump station, substation, hub)
* lines (pipes, cables)

Please add functionality to logically relate these objects 
* node type
* start node of line (from)
* end node of line (to)

help editing:
* when a node is moved (digitization), the connected lines shall be shifted
* provide analysis (near, connected to)

**Comment by alexbruy** [comment]
Probably should be closed as request is quite specific and better to have such functionality as plugin.
