### ISSUE TITLE
Expose invert selection as a map tool

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#16791]
Author Name: **Nathan Woodrow** (@NathanW2)
Original Redmine Issue: [7919](https://issues.qgis.org/issues/7919)

Redmine category:gui
Assignee: Nathan Woodrow

---
The invert selection operation can only be done by the attribute table.  Should be a map tool as well.

**Comment by suricactus** [comment]
Not sure if you meant this  7 years ago, but it seems it is already there?
![image](https://user-images.githubusercontent.com/2820439/76499095-cb542880-6446-11ea-9ed1-e69b5064654a.png)
