### ISSUE TITLE
Meaning of scale field not explained in Print Composer

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#16832]
Author Name: **Aren Cambre** (Aren Cambre)
Original Redmine Issue: [7975](https://issues.qgis.org/issues/7975)

Redmine category:map_composer/printing

---
In Print Composer's *Item Properties* pane is a *Scale* field. The meaning of this field is not explained. All I can figure out is if I reduce the number in it, that zooms in within the currently-selected item.

Note that this is not a support request. This is a feature request for the UI to do a better job explaining what this field means. I _guess_ it has something to do with the number of projection units displayed on the horizontal dimension of the viewport of the item, but I am not sure.

**Comment by DelazJ** [comment]
Should we close this one?
