### ISSUE TITLE
DBManager - Add a stop button to SQL Window

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#16983]
Author Name: **James Stott** (@jamesstott)
Original Redmine Issue: [8157](https://issues.qgis.org/issues/8157)

Redmine category:db_manager

---
Sometimes you can run a query that isn't quite correct (even though its syntax is correct and it executes) or you can create a query that simply takes far to long to complete. Or both of these two things at the same time. 

It would be useful to have a button that allows you to stop executing the query, similar to that in the Query dialog in pgadmin.

Currently, QGIS just goes into 'Not Responding' mode in Windows. So you either have to wait for the query to finish, or you have to close QGIS down (and subsequently lose the SQL code you have typed). 

Of course, I should remember to test all my queries in pgadmin first, but this would still be a good feature to add.

**Comment by gioman** [comment]
This has been added, but actually is not working https://github.com/qgis/QGIS/issues/38092
