### ISSUE TITLE
Encryption of Passwords in qgs files

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#16999]
Author Name: **Jonathan Moules** (Jonathan Moules)
Original Redmine Issue: [8180](https://issues.qgis.org/issues/8180)

Redmine category:project_loading/saving

---
At least with Oracle (and the others? I have no way to test), when a project is stored as a qgs file, the password is stored in plaintext:

            <datasource>dbname='co_gislive.world' host=10.76.112.32 port=1521 user='OSMM' password='password_here_in_plain_text' estimatedmetadata=true srid=27700 type=POLYGON table="OSMM"."AGRICULTURE_MIDLANDS" (SDO_GEOMETRY) sql=</datasource>

It should be encrypted, probably using AES-256 and a unique salt I guess. I don't know if this carries for other passwords stored by QGIS, either database or WMS/WFS etc - ideally they should all be encrypted.

Using Master 226c524

---

Related issue(s): #14669 (duplicates), #17685 (relates), #24908 (duplicates)
Redmine related issue(s): [4823](https://issues.qgis.org/issues/4823), [9030](https://issues.qgis.org/issues/9030), [17009](https://issues.qgis.org/issues/17009)

---

**Comment by nyalldawson** [comment]
This is now possible via the inbuilt authentication system
