### ISSUE TITLE
Give us a panel that shows load times of layers

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#17014]
Author Name: **Aren Cambre** (Aren Cambre)
Original Redmine Issue: [8196](https://issues.qgis.org/issues/8196)

Redmine category:gui

---
Please give us a panel that shows load times and other relevant diagnostic information, at a glance, for layers. It's a lot of trial and error and deep investgiation to deal with slow-loading projects that have several layers. It's not always obvious which ones need more optimization or removal.

I'm hoping for something like an additional panel that is refreshed with new info every time the canvas is redrawn.

**Comment by nyalldawson** [comment]
This was added in 3.16
