### ISSUE TITLE
Provide export settings ability

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#17040]
Author Name: **Nathan Woodrow** (@NathanW2)
Original Redmine Issue: [8226](https://issues.qgis.org/issues/8226)

Redmine category:unknown

---
We should provide a way (in settings) to export the current settings so they can be exported to another machine or backed up.

This can be handy for backing up you current settings.

This should also reduce the number of questions about moving settings like this one http://gis.stackexchange.com/questions/57540/can-i-transfer-custom-qgis-settings-from-one-computer-to-another/57543#57543.  The answer to that question also contains incorrect information about what can safely moved. As simple as it is to be able to just export the settings from the registry,./config, /Library/, people seem to keep saying it can't be done or you can't do it safely, which of course is incorrect.

---

Related issue(s): #18348 (relates)
Redmine related issue(s): [9817](https://issues.qgis.org/issues/9817)

---

**Comment by alexbruy** [comment]
Probably should be closed as all settings now stored in the profile directory which can be easily copied across machines.
