### ISSUE TITLE
Allow access to the startup tips from the help menu

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#17106]
Author Name: **Alister Hood** (@AlisterH)
Original Redmine Issue: [8313](https://issues.qgis.org/issues/8313)

Redmine category:gui

---
Some programs allow access to their startup tips from the help menu.  This is particularly useful if you have enabled the option not to show tips at startup.  It would be nice to have this in QGIS.

**Comment by alexbruy** [comment]
Startup tips were removed. Closing.
