### ISSUE TITLE
Add option to suppress feature form for new features to project and layer properties

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#17265]
Author Name: **Larry Shaffer** (Larry Shaffer)
Original Redmine Issue: [8505](https://issues.qgis.org/issues/8505)

Redmine category:digitising

---
Currently, this is an app-wide option, but should be pretty straightforward to implement for project and layer properties.

I think all should be implemented with preference as so:
```
layer -> project -> app

```

**Comment by alexbruy** [comment]
Closing, as this option already present.
