### ISSUE TITLE
Possibility to use field for auto offset (for use in conjunction with size scale)... "offset scale"?

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#17273]
Author Name: **Jonas Malaco Filho** (@jonasmalacofilho)
Original Redmine Issue: [8517](https://issues.qgis.org/issues/8517)

Redmine category:symbology

---
Especially when trying to view data on roads (such as vehicle counts per hour per segment), it's already very helpful to use automatic size scaling binded to a appropriate field. However, to proper visualize data according to direction of flow it's necessary to use some offset; ideally, the offset should be just enough to balance the line width out of center. Therefore I think It would be a huge improvement to allow the offset field to be set based on a field, in a way similar to size scaling.

If I'm not mistaken, the offset behavior should resemble
offset(field)=flat_offset*field/2
because we want
offset(field)=width(field)/2
, with width(field)=flat_width*field

Another way to tackle this would be render vector lines optionally off-center (to the right or to the left); than, the offset could remain as is. While this is generally the approach taken by other GIS/modelling software when showing this types of data (Inro Emme, PTV Visum and Caliper TransCAD take the render off-center (to the right) for these cases), I expected the QGIS way of doing to be similar to size scaling. And by allowing offset scaling by field the user would have much more flexibility...

I would very much like to implement this (since I have a particular use for it), but I would need some guidance on where things are/go on the source tree.

**Comment by pjshelton** [comment]
![image](https://user-images.githubusercontent.com/39154868/103165522-c2610600-4864-11eb-993d-e4c963173b7b.png)

This can now be be closed as the offset can be data defined as well as the stroke width.  This works very well except for a couple of edge cases.

@NathanW2, @gioman
