### ISSUE TITLE
Doing calculations with CRS projections set "On The Fly"

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#17308]
Author Name: **Charles Rethman** (Charles Rethman)
Original Redmine Issue: [8559](https://issues.qgis.org/issues/8559)

Redmine category:projection_support

---
If you have data in a certain projection--say long-lat WGS84--and you want to do a calculation that can only be done in a different projection--e.g. geometry, like area--you should be able to re-project all your data "on the fly" (including to a custom or user-defined CRS) and then do the calculation, using the coordinates of your data that come from the "on the fly" projection. Shouldn't have to save the re-projected data in the new projection and then open it in it's own projection first before doing the calculations (as seems to be the case now).

This is a basic functionality in ArcMap.

**Comment by nyalldawson** [comment]
Possible since QGIS 3.0
