### ISSUE TITLE
Zoom map to the selected row from attributes table

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#17316]
Author Name: **Rémi Bovard** (@rbovard)
Original Redmine Issue: [8570](https://issues.qgis.org/issues/8570)

Redmine category:unknown

---
Zoom map to the selected row from attributes table when double click on the row number (left margin).

This is really a feature that I miss when I used to work with ArcGIS.

---

Related issue(s): #26511 (copied_to)
Redmine related issue(s): [18623](https://issues.qgis.org/issues/18623)

---

**Comment by alexbruy** [comment]
Duplicates #26511.

**Comment by Samweli** [comment]
see discussion here https://github.com/qgis/QGIS/pull/33322
