### ISSUE TITLE
Duplicate entry in ellipsoid selector

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#17398]
Author Name: **Paolo Cavallini** (@pcav)
Original Redmine Issue: [8669](https://issues.qgis.org/issues/8669)
Affected QGIS version: 3.0.0
Redmine category:projection_support

---
In Project properties>General, the list of entries for ellipsoid has a duplicate entry: WGS 84 and WGS84, apparently with the same parameters

**Comment by nyalldawson** [comment]
Fixed in 3.8 and for builds based on proj >= 6.0
