### ISSUE TITLE
World file created from Project->Save as image has wrong extension for various other uses

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#17454]
Author Name: **Andrew DeMerchant** (Andrew DeMerchant)
Original Redmine Issue: [8739](https://issues.qgis.org/issues/8739)

Redmine category:unknown

---
It looks like when you "save as image", the extension for the world file that gets created is just the extension of the image type, plus a "w". So, a png becomes pngw, jpg becomes jpgw, etc. I think this is the way that GDAL works, which would explain things - but it would be nice if it used the alternate method so that it would work with things like Autocad, for example, without having to manually rename the file. A lot of software uses the other naming method where you take the first and last letter and then add a w to those. So jpg becomes jpw, tif becomes tfw, etc. 

It's obviously very easy to rename manually - but like I said, it would just be a nice little change if it did this out of the box.

**Comment by AlisterH** [comment]
The description in this ticket is out of date, so could perhaps be closed.
"Project>Import/Export>Export Map to Image" produces a .jgw if you save to jpeg format.

It doesn't produce a world file at all if you save to .tif - in my mind it would be nice if it did.

**Comment by AlisterH** [comment]
Anyone want to close this ticket (fixed as per my previous comment)?
@gioman?
