### ISSUE TITLE
PDF output types & placement.

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#17528]
Author Name: **James Harvey** (James Harvey)
Original Redmine Issue: [8845](https://issues.qgis.org/issues/8845)

Redmine category:map_composer/printing

---
I am having difficulty with placing PDF files out of QGIS into Adobe InDesign. There could be an issue also with the type of PDF that gets outputted. 

It would be good to have more support for different PDF specs and PDF output types that can be changed in an output settings screen. At the moment I am having to convert the PDF files to EPS files to place them in Adobe InDesign CS5.5 as the PDF output cannot be used directly. Would save me a lot of time if I can import these PDFs directly into Adobe InDesign.

**Comment by DelazJ** [comment]
> I have updated my Adobe Master Collection to the newer Creative Cloud software and I am able to import PDFs exported from QGIS 2.9.0 directly into Adobe InDesign without any need for PDFx3 conversion. One less step in my process, but a big time saver. This might help someone else in publishing.

Should this report be closed, then?

**Comment by AlisterH** [comment]
Hey, probably worth closing.  This ticket is very old, long, and not obvious what is actually requested.
If necessary someone can open a new ticket with a specific request.
