### ISSUE TITLE
Don't show provider specific layer data source string

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#17548]
Author Name: **Jonathan Moules** (Jonathan Moules)
Original Redmine Issue: [8868](https://issues.qgis.org/issues/8868)

Redmine category:map_legend

---
The "layer source" for a WMS layer when you go to layer properties says something like:

crs=EPSG:27700&featureCount=10&format=image/png&layers=z_OS_Vector_Basemap&styles=&url=http://wppgeog3/geoserver/ows

Obviously that's invalid.

**Comment by nyalldawson** [comment]
Fixed since 3.6
