### ISSUE TITLE
Better support for georeferenced pdf

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#17588]
Author Name: **Yannick Portier** (Yannick Portier)
Original Redmine Issue: [8912](https://issues.qgis.org/issues/8912)

Redmine category:unknown

---
ability to import / load maps in pdf format such as USGS maps

---

- [20.png](https://issues.qgis.org/attachments/download/6387/20.png) (Giovanni Manghi)

**Comment by nyalldawson** [comment]
This is fixed since forever
