### ISSUE TITLE
tools algorithms transparency

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#17589]
Author Name: **Yannick Portier** (Yannick Portier)
Original Redmine Issue: [8913](https://issues.qgis.org/issues/8913)

Redmine category:unknown

---
ability to view the algorithm (source code) that tools are running in the same way that Whitebox is implementing
reference :
http://www.uoguelph.ca/~hydrogeo/Whitebox/Help/AboutTheWhiteboxPhilosophyAndLogo.html

**Comment by alexbruy** [comment]
I think this is a won'tfix. You can always check source code at GitHub.
