### ISSUE TITLE
Processing in a standalone QGIS app

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#17619]
Author Name: **Joshua Arnott** (@snorfalorpagus)
Original Redmine Issue: [8955](https://issues.qgis.org/issues/8955)

Redmine category:processing/core
Assignee: Victor Olaya

---
Currently it is not possible to use the processing module in a standalone QGIS application/script.

This is due in part to a dependence on the iface object, which is only available when running as a plugin within QGIS. In addition to this there will be issues with calling external programs/scripts using subprocess.Popen related to paths.

I've attached an example script (processing_standalone.py) which uses a mock iface object to allow the plugin to load. This can be used to run the 'qgis:*' algorithms, as they don't have any external dependencies. More work is needed to get things working with GRASS and SAGA, etc.

---

- [processing_standalone.py](https://issues.qgis.org/attachments/download/6411/processing_standalone.py) (Joshua Arnott)

**Comment by alexbruy** [comment]
Now Processing intergarted much better into QGIS core and can be used in standalone apps.
