### ISSUE TITLE
Make imported CSV tables editable within QGIS

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#17658]
Author Name: **Martin Jung** (Martin Jung)
Original Redmine Issue: [9001](https://issues.qgis.org/issues/9001)

Redmine category:gui

---
I think this would really improve the usability of QGIS and is probably not that hard to implement (i would guess). Just needs a connector and table-writer for QGIS to change cells and write new rows to an existing file.

See this and many other GIS-SE question where someone wondered why they can not edit a loaded table.
http://gis.stackexchange.com/questions/76396/why-cant-i-edit-attribute-table-imported-through-text-as-layer

**Comment by alexbruy** [comment]
This depends on the data provider, e.g. GDAL allows editing of the CSV, while delimited text provider don't.
