### ISSUE TITLE
"No data" in multi-band data

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#17697]
Author Name: **Jonathan Moules** (Jonathan Moules)
Original Redmine Issue: [9043](https://issues.qgis.org/issues/9043)

Redmine category:rasters

---
I'm going to put this as a "feature request" though it might be considered a bug.

I have three band raster data. On the "transparency" page I've set "0" to be "no data". The problem is, if even one of the three bands has a "0", QGIS renders the entire pixel as being "no data". As such I get entire fields filled with "no data" speckles because a single band (red) is often 0.

I'd suggest allowing the user to set "no data" on a per-band basis or requiring that *all* symbolised pixels be no data before rendering as no-data.

**Comment by alexbruy** [comment]
Should be closed?
