### ISSUE TITLE
be able to select Measure Tool unit for measurements when GCS 

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#17720]
Author Name: **Antonio Locandro** (Antonio Locandro)
Original Redmine Issue: [9074](https://issues.qgis.org/issues/9074)

Redmine category:unknown

---
When I select the measure tool, specially in GCS the default option is degrees and it tells me (OTF off). What I would like to do is select from the menu itself what units I want the measurements done (m, ft, nm, sm, etc) without selecting a PCS. This is achievable using the Vincenty Formula implementation as other COTS software gives you the option (geodesic, planimetric, etc)

In a PCS I would think this would be useful if I want to measure ft, m, sm, nm, etc since it would be just a simple conversion from one unit to another

**Comment by suricactus** [comment]
There is a select box to choose the unit, no matter the coordinate system (screenshot taken with single layer and project both in EPSG:4326)
![image](https://user-images.githubusercontent.com/2820439/76571715-cdf36400-64c0-11ea-9fc7-e4f8cdfd7454.png)

**Comment by suricactus** [comment]
Close.
