### ISSUE TITLE
Move 'add layers' to file menu

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#17735]
Author Name: **Noone Noone** (Noone Noone)
Original Redmine Issue: [9090](https://issues.qgis.org/issues/9090)

Redmine category:gui

---
Currently the Layer menu includes a lot of stuff, so on medium size displays as laptops the menu gets scrollbars (see attachment).

I suggest moving the 'Add x layer' menuitems to the File menu, even for other reasons:
* Endusers expect I/O related things in File menu
* currently Layer mixes several aspects (one layer, current layer, multiple layers, ...)

A single entry as 'Add vector layer...' or 'import' would be great. All the single filetypes can be submenu entries for quick access.

---

- [qgis_layer_menu.png](https://issues.qgis.org/attachments/download/6476/qgis_layer_menu.png) (Noone Noone)

**Comment by suricactus** [comment]
Currently "Layers" is not the longest menu, it is the "Edit" one. Also you cannot change years of physical memory where you add layers.
The attached menu items are already grouped under "Add Layer" menu:
![Screenshot_20200313_000440](https://user-images.githubusercontent.com/2820439/76570656-7d7b0700-64be-11ea-8581-a2f6c72031d6.png)
