### ISSUE TITLE
Offer a global OSM TMS as default map services

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#17743]
Author Name: **Noone Noone** (Noone Noone)
Original Redmine Issue: [9098](https://issues.qgis.org/issues/9098)

Redmine category:data_provider

---
More and more novice users join GIS even due to open data (encouraged citizens...datajournalists) and QGIS is one of the few open solutions to view and analyse geodata. A very first bad impression is, that they need to find a provider for a background-layer, to get a global orientation of their data and to check if it's projection is ok.

Thus, I recommend to add a list of global TMS/WMTS to QGIS to improve user experience. This might need further discussions on the server policies before you add a server to the list http://wiki.openstreetmap.org/wiki/TMS So people don't have to understand about all kind of protocols, find a service that suites also for their area etc.

**Comment by alexbruy** [comment]
Already available.
