### ISSUE TITLE
Use columns aliases when doing a "save as..." of a layer/table with a join

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#17766]
Author Name: **Giovanni Manghi** (@gioman)
Original Redmine Issue: [9129](https://issues.qgis.org/issues/9129)

Redmine category:vectors

---
When doing a join and then saving the resulting layer/table with the "save as..." option, the joined column names are given the name of the join layer, then a "_" and then eventually the name of the other layer, or more probably a number because of the 10 char limit for shapefiles.

I would be good to allow the user choose to give to columns the string used as aliases. This would be handy for joins but maybe it can be useful also in other cases.

**Comment by alexbruy** [comment]
Already possible.
