### ISSUE TITLE
Extend layer window with toolbar

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#17763]
Author Name: **Noone Noone** (Noone Noone)
Original Redmine Issue: [9126](https://issues.qgis.org/issues/9126)

Redmine category:gui

---
Currently tools that are related to the layer widget are only within the context menu of layers. This is bad, as
* they are 'hidden' by default
* they don't refer to the current clicked layer, but to all layers (more specific: the layer list itself)

So I suggest to move the expand/collapse/add group feature to a smal toolbar at the top of the layer window. You might have a look how the Eclipse team designed it:
![eclipse_outline_window.png](https://issues.qgis.org/attachments/download/6511/eclipse_outline_window.png)

---

- [eclipse_outline_window.png](https://issues.qgis.org/attachments/download/6511/eclipse_outline_window.png) (Noone Noone)
- [gimp_layer_window.png](https://issues.qgis.org/attachments/download/7056/gimp_layer_window.png) (Noone Noone)

**Comment by alexbruy** [comment]
Implemented in 3.x
