### ISSUE TITLE
Customisation menu improvements

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#17826]
Author Name: **Jonathan Moules** (Jonathan Moules)
Original Redmine Issue: [9198](https://issues.qgis.org/issues/9198)

Redmine category:customisation_framework

---
Following from #17769

I'd suggest that only one column should be shown "Label". If label is empty then show the ObjectName.
Showing the objectName as standard as is done currently only adds clutter. The "Description" column is empty for everything I've looked at so seems superfluous; no-one is using it.

This would create a customisation panel that is much easier to read and therefore use.

**Comment by alexbruy** [comment]
Showing only label can be confusing when there are multiple widgets with the same label.
