### ISSUE TITLE
Differentiate add layer dialogs

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#17821]
Author Name: **Jonathan Moules** (Jonathan Moules)
Original Redmine Issue: [9193](https://issues.qgis.org/issues/9193)

Redmine category:gui

---
QGIS has lots of "Add layer" dialogs which all look extremely similar. How about adding some big text somewhere (and the Icon for that dialog) somewhere on the dialog so the user always knows which one they're on?
So in the top right it could say: "WFS" and have next to it the WFS globe icon.

---

- [Clipboard01.png](https://issues.qgis.org/attachments/download/6566/Clipboard01.png) (Jonathan Moules)

**Comment by alexbruy** [comment]
This should be fixed with DatasourceManager. Please reopen if necessary.
