### ISSUE TITLE
Improved defaults when creating new columns in attribute table

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#17846]
Author Name: **Michael Goldstein** (Michael Goldstein)
Original Redmine Issue: [9225](https://issues.qgis.org/issues/9225)

Redmine category:unknown

---
The suggestion is that the New Column dialog from the attributes table provide more useful defaults.  On my installation, if I add a Decimal Number column, it defaults to Width of 1 and Precision of 0.  If you accept these defaults, it means that the real number column you've just created can only store single digit integers, which is completely nonsensical.  But for a new user, with an overwhelming amount of detail to absorb, I ignored these settings and it caused the labeling routine to fail, since the x, y, and rotation values I set were getting changed when the file was stored.  It took me a couple of hours of patient analysis to figure out what was going wrong.

A simple routine that forced a reasonable default for each kind of column (string, integer, real) would be a huge improvement over the current setup.  One could get more complicated and have the routine remember the last setting and use that as a default (perhaps with some logic to question settings that make little or no sense), or allow users to reset the default.

**Comment by alexbruy** [comment]
Duplicates #16581.
