### ISSUE TITLE
Preselect field in Label dialogue

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#17891]
Author Name: **Noone Noone** (Noone Noone)
Original Redmine Issue: [9279](https://issues.qgis.org/issues/9279)

Redmine category:gui

---
If you enable the "Label this layer with ... " checkbox at the label dialog within the layer options, currently there is no field selected and the user might forget about it, as he sees a "lorem ipsum" and might get confused as he expects this static string to be rendered first. To avoid this behaviour, I recommend a few slightly changes:
* preselect the first layer data field (not lat/lon/alt)
* display a list of first 1..3 first items of this field as demo text

I also recommend to move the demo field down to the bottom of dialog, below the preferences frame. This might improve the workflow, as it triggers the input-process-output methology. I also recommend to display a "transparency pattern":http://www-personal.umich.edu/~bazald/l/faq/gimp_transparency.png in the sample widget, to avoid the interpretation as a regular edit-box with a white background and to allow the user to check style visibility on bright and dark background at twice.

**Comment by alexbruy** [comment]
Already fixed in master.
