### ISSUE TITLE
Tolerance (snapping) during analyses

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#17933]
Author Name: **Paolo Cavallini** (@pcav)
Original Redmine Issue: [9326](https://issues.qgis.org/issues/9326)

Redmine category:processing/qgis

---
In case of layers with essentially the same shapes, with different precision, the diff between these layers produces a number of virtually 0 width polygons.
These microareas are tricky and time consuming to remove (if they are isolated, a possible solution is to select and remove those smaller than an arbitrary threshold, but if they are linked to some "real" polygons, this will not work).

I suggest to add a parameter in analyses, to either snap original data within a threshold before running the analysis, or to clean up the results afterwards

**Comment by alexbruy** [comment]
Probably we can close this, as Processing now offers several tool for snapping which can be used before doing analysis.

**Comment by pcav** [comment]
Agreed, thanks
