### ISSUE TITLE
Load GPX: do not load empty layers

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#17953]
Author Name: **Paolo Cavallini** (@pcav)
Original Redmine Issue: [9351](https://issues.qgis.org/issues/9351)

Redmine category:c++_plugins/gps_plugin

---
When loading a GPX, by default tracks, routes, and waypoints are loaded, even if empty. For the user it mey be difficult to understand that a layer is present, with 0 geometries.
I suggest to avoid loading empty layers. A warning should be given to the user (either a notification "Layer not loaded because empty" or a note on the dialog "Note: empty layers will not be loaded").
Seems easy to implement.

**Comment by alexbruy** [comment]
Thinking a bit more about it, implemeting this will make GPS Tools behave differently from the main application as QGIS itself loads empty shapefiles/tables.

**Comment by pcav** [comment]
That's true. I don't see a reason why one user would like to load also the layers without features when loading a non-empty GPX, however.

**Comment by pcav** [comment]
An empty shp can be edited, so in this case I see a reason.
