### ISSUE TITLE
Simplification of layers when exporting composition to svg

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#18029]
Author Name: **Nyall Dawson** (@nyalldawson)
Original Redmine Issue: [9435](https://issues.qgis.org/issues/9435)

Redmine category:map_composer/printing
Assignee: Nyall Dawson

---
QGIS should have an option to simplify map layers when exporting to svg. Otherwise complex map layers result in svg shapes with 1000's of vertices, which results in large file sizes and causes some svg editing software to hang. We could utilise the simplification code already present in QGIS, and just make sure a sensible default simplifaction factor is chosen and have an option to enable/disable this simplification when exporting.

**Comment by nyalldawson** [comment]
Implemented in 3.10
