### ISSUE TITLE
attribute table isn't refreshed after save

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#18063]
Author Name: **Vincent Mora** (@vmora)
Original Redmine Issue: [9471](https://issues.qgis.org/issues/9471)

Redmine category:unknown
Assignee: Matthias Kuhn

---
This is an issue when you have underlying triggers that will change the table when you save your modifications.

The only workaround is to close and reopen the table.

The refresh can be used to fix #11719

---

- [test_9471.qgs](https://issues.qgis.org/attachments/download/6720/test_9471.qgs) (Vincent Mora)
- [test_9471.sqlite](https://issues.qgis.org/attachments/download/6721/test_9471.sqlite) (Vincent Mora)

**Comment by m-kuhn** [comment]
I think this is now solved with layer dependencies?

I'll close it, feel free to reopen if there is a reason.
