### ISSUE TITLE
Replace help with pages from the manual

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#18075]
Author Name: **Paolo Cavallini** (@pcav)
Original Redmine Issue: [9483](https://issues.qgis.org/issues/9483)

Redmine category:documentation_and_help
Assignee: Richard Duivenvoorde

---
Translating help files in GUI is always the most painful part, and I am convinced it
is not the most useful one, as the content is often obsolete and not aligned with the
manual.
My suggestion is to:

* remove the help
* replace it with the relevant manpage, either including it or adding a link to the
manual
* ship the manual together with the package (problem: shipping all the languages will
be very heavy).

---

Related issue(s): #17312 (duplicates)
Redmine related issue(s): [8564](https://issues.qgis.org/issues/8564)

---

**Comment by alexbruy** [comment]
Closing as now help points to the documentation. Please reopen if necessary.
