### ISSUE TITLE
Allow to specify a bounding box column in addition to the geometry column

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#18107]
Author Name: **Sandro Santilli** (@strk)
Original Redmine Issue: [9516](https://issues.qgis.org/issues/9516)

Redmine category:data_provider/postgis

---
Some sql queries build the geometry column on-the-fly, but can still return a bounding box from a real table. The most notable example is a query constructing a topology face geometry or centroid as used by the TopoViewer in db_manager.
Such queries cannot use an index unless you put the indexed bounding box column as one of the && inputs.

Immagine another case: you want to show a buffer of points in a table. Also in this case there's no index on the buffer, but there is one (possibly) on the points...

In both cases if you could specify the name of a column to use for spatial filtering, rather than using the single "geometry column", operations could be much faster.
Given you cannot edit queries there's no problem with that part...

Not sure if this is only related to the postgis data provider. Sounds like something that could need to be put in the QgsDataSourceUri class

\\cc @jef

**Comment by strk** [comment]
Another possible approach, more generic, would be to allow label substitution in the query, as requested in #14306

**Comment by strk** [comment]
PR https://github.com/qgis/QGIS/pull/31468 is ready for review, implements support for `bbox` custom parameter in DataSourceURI for PostgreSQL
