### ISSUE TITLE
add manual entry to coordinate capture

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#18115]
Author Name: **Gavin Fleming** (@gubuntu)
Original Redmine Issue: [9525](https://issues.qgis.org/issues/9525)

Redmine category:unknown

---
I often need to project single coordinate pairs (as in cs2cs or gdaltransform). I cannot find an equivalent in QGIS. To me the obvious place to put this would be to have the option of manual input coordinate entry into the coordinate capture panel.

**Comment by nyalldawson** [comment]
This would best be addressed by a 3rd party plugin adding a new dock for this functionality
