### ISSUE TITLE
Allow QGIS Relations to use composite keys

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#18120]
Author Name: **cgsbob -** (cgsbob -)
Original Redmine Issue: [9531](https://issues.qgis.org/issues/9531)

Redmine category:data_provider

---
I am working on using QGIS to enter borehole data using QGIS Relations.  It is a snap to create 1:1 and 1:N relations on one foreign key, but it is impossible to work with composite keys (such as the relationship between SAMPLE_DATA and SOILS_INDICES_LAB in the relations.jpg).  

---

- [relations.jpg](https://issues.qgis.org/attachments/download/6764/relations.jpg) (cgsbob -)

**Comment by nyalldawson** [comment]
This was implemented
