### ISSUE TITLE
Layer Alias in Snapping option dialog

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#18190]
Author Name: **Rocco Pispico** (Rocco Pispico)
Original Redmine Issue: [9616](https://issues.qgis.org/issues/9616)

Redmine category:unknown

---
I have a lot of layers with a very long and coded name.
These names are quite the same except a letter or a number inside it.

In the set snapping option dialog is hard to know which layer choose.

So i tried to set an alias but in the dialog is reported the original name.

I think is easy to put the alias name if setted or report name and alias together.

TIA

**Comment by alexbruy** [comment]
Already fixed in master.
