### ISSUE TITLE
Search as you type lookup in forms

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#18294]
Author Name: **cgsbob -** (cgsbob -)
Original Redmine Issue: [9744](https://issues.qgis.org/issues/9744)

Redmine category:gui

---
If you use a Value relation edit widget and the "domain table" that is used with this widget has many entries, you would have scroll a lot to find the value you are looking for.  If you can type into that widget and have it search as you type, it would save a lot of time.

**Comment by alexbruy** [comment]
Value relation now supports completer.
