### ISSUE TITLE
Add a distance analysis tool

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#18451]
Author Name: **Giovanni Manghi** (@gioman)
Original Redmine Issue: [9950](https://issues.qgis.org/issues/9950)

Redmine category:processing/core
Assignee: Victor Olaya

---
Among QGIS out of the box tools we really miss a tool that can computes min (and max) distances between features of the same layer or different layers.

The distance matrix tool just works for points layers and does not create a line output representing the min distances.

The v.distance GRASS module work only to compute distances from point to other features, it is anyway not working in Processing because this module does not produce a new output but modifies the input (there is a ticket about this issue).

To computes min/max distances the user is left with the Spatialite/PostGIS solution, that is out of reach for most of the people.

PS
SL/PostGIS seems anyway the only solution when the number of features is relatively high, as both the distance matrix tool and native grass v.distance are really slow.

**Comment by root676** [comment]
I think this ticket can be closed. We now have the `Join by nearest` algorithm which features exactly the same behaviour (including xy values for start and endpoint of shortest lines between features of all geometry types).
