### ISSUE TITLE
Composer map coordinates on opaque background

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#18477]
Author Name:  (@sergethedev17)
Original Redmine Issue: [9983](https://issues.qgis.org/issues/9983)

Redmine category:map_composer/printing

---
It is possible to display coordinates on a map in Composer, by checking *Show grid* and *Draw coordinates* checkboxes in *Item properties* panel.
Sometimes it is difficult to see coordinates when they are displayed *Inside frame*, because the text blends in with other map contents.

It would be great to specify a background colour for the coordinates, similarly to *Background* settings for the map itself.

**Comment by nyalldawson** [comment]
This is fixed in 3.16
