### ISSUE TITLE
Constrain feature movement to horizontal or vertical axis

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#18476]
Author Name: **Serge Rozentsvet** (@sergethedev17)
Original Redmine Issue: [9982](https://issues.qgis.org/issues/9982)

Redmine category:vectors

---
It would be helpful to be able to move features (points, lines, polygons) along X or Y axis (horizontally or vertically).
This would be ideally achieved by holding down the Shift key to constrain movement along an axis.

A similar feature was recently implemented for moving objects in Composer.

**Comment by alexbruy** [comment]
Possible with advanced digitizing panel.
