### ISSUE TITLE
Table Creation within Print Composer

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#18505]
Author Name: **Antonio Locandro** (Antonio Locandro)
Original Redmine Issue: [10019](https://issues.qgis.org/issues/10019)

Redmine category:map_composer/printing

---
QGIS could benefit from having an easy way to create tables to add information on layouts/print composer similar to excel or calc in which one can add rows, columns, merge them and insert data within QGIS without need to do it externally and then bring it back in, it would be also useful if data can be dynamically updated either from attribute data from layers or via external files like CSV, XML etc

Sample table I am working on 

---

- [table.png](https://issues.qgis.org/attachments/download/7111/table.png) (Antonio Locandro)

**Comment by suricactus** [comment]
This is already present as "Add Fixed Table"
![image](https://user-images.githubusercontent.com/2820439/76618473-4eea4400-6531-11ea-957d-51458e7c6544.png)
