### ISSUE TITLE
lock scale and extents in composer

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#18517]
Author Name: **Gavin Fleming** (@gubuntu)
Original Redmine Issue: [10036](https://issues.qgis.org/issues/10036)

Redmine category:map_composer/printing

---
Sometime one needs to make a map with a specific scale AND a specific extent. And then choose a page size to suit. At the moment you can't change one of these without affecting the other. What would help is a 'lock' tickbox for both scale and extent, in which case the map would dynamically resize as you changed any of the parameters while keeping the other one fixed. 

---

Related issue(s): #13923 (relates)
Redmine related issue(s): [3865](https://issues.qgis.org/issues/3865)

---

**Comment by alexbruy** [comment]
Probably related to #20236

**Comment by Stapawe** [comment]
Please
Thank you in advance

**Comment by jgrocha** [comment]
This is possible by locking the scale and/or extent using a data defined override.

**Comment by 3nids** [comment]
I don't think this is very handy, and I'd rather have a checkbox to do the locking.
I would recommend keeping the issue open.

**Comment by jgrocha** [comment]
> I don't think this is very handy, and I'd rather have a checkbox to do the locking.
> I would recommend keeping the issue open.

Yes, seems reasonable to keep it open as a usability issue. Technically it is supported.
