### ISSUE TITLE
Allow specification of Size (=diameter) in Data-Defined Properties

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#18627]
Author Name: **Johannes Kroeger** (Johannes Kroeger)
Original Redmine Issue: [10173](https://issues.qgis.org/issues/10173)

Redmine category:symbology

---
I have some point data. I want to use circles as symbols for them. The circles should have a size defined by an numeric attribute.
In the Data-Defined Properties there is only the option "Size (area)" which requires calculating[*] instead of simply using my attribute.

Please add the option to use an attribute value as Size property.
This Size should be the same as you can specify normally in the styling options (i.e. the diameter).

-----
[*] Even then, it gives me results that don't seem correct. I used $pi*("diameter"/2)^2.

**Comment by pjshelton** [comment]
The only way I could find, in version 3.16, to create a circle was as a simple marker or a SVG marker.  Both these methods now only give you the diameter as the "size".  This can be a data driven expression. 

@gioman I think this one can be closed,
