### ISSUE TITLE
Expression based label load expressions from file

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#18643]
Author Name: **Antonio Locandro** (Antonio Locandro)
Original Redmine Issue: [10190](https://issues.qgis.org/issues/10190)

Redmine category:unknown

---
When using Expression based labels one can create complex expressions, I know that currently one gets the most recent them but having the option to save an expression to a file and load them would be nice to have in my opinion

**Comment by alexbruy** [comment]
This is possible now, there is an option to save expression as "User expression" and then export these user expressions to file/load user expressions from file.
