### ISSUE TITLE
Snapping option - Add Spinner to Tolerance

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#18659]
Author Name: **Antonio Locandro** (Antonio Locandro)
Original Redmine Issue: [10213](https://issues.qgis.org/issues/10213)

Redmine category:digitising

---
It would be nice to have a spinner for the Tolerance so I can set the desired tolerance with my mouse, Also I think the default 6 decimal precision is excessive so maybe having 0.00 and spinner work in 1 increments? like

0.00
1.00
2.00
3.00

---

- [SNAPPING_SPINNER.png](https://issues.qgis.org/attachments/download/7189/SNAPPING_SPINNER.png) (Antonio Locandro)

**Comment by alexbruy** [comment]
Probably should be closed. Spinboxes added and they accept floats. Scrolling will change integer part however, but this should be acceptable for most cases.
