### ISSUE TITLE
Add expressions to diagrams (tab position)

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#18670]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [10226](https://issues.qgis.org/issues/10226)

Redmine category:symbology

---
Hi,
In the layer's properties, there is now the possibility to add expressions on size and attributes fields of diagrams tab. I think it would be nice if we can have the same possibility about the position of the pie/charts, at least on x and y coordinates. 
Thanks!

**Comment by suricactus** [comment]
As far as I get his issue, it seems this is already possible?
![image](https://user-images.githubusercontent.com/2820439/76621582-6aa51880-6538-11ea-8c02-797e9cdc9044.png)

**Comment by DelazJ** [comment]
Yes, this is now possible. Should be closed.
