### ISSUE TITLE
Freeze using "Select By Location" (or the spatial query tool) for complex polygon and points

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#18695]
Author Name: **Neil Benny** (Neil Benny)
Original Redmine Issue: [10263](https://issues.qgis.org/issues/10263)
Affected QGIS version: 3.5(master)
Redmine category:c++_plugins/spatial_query

---
Using QGIS 2.2 (tested in current nightly build of 2.3). 32bit version (replicated issue in 64bit version). 

QGIS goes slow, then crashes when doing a "select by location" on points inside a polygon when using a very complex polygon. This is an issue with flooding data in the way it is provided by the Scottish Environment Protection Agency (single polygon converted from a raster - very complex - see attached). 

I had thought this problem had been solved in the new release, but we have the same issue as laid out before. 

The data in the zip file attached seems to cause the problem - it is one of the pieces of flood data and some OSM data (I can't include the original dataset because it is a secure dataset to do with vulnerable people). Both files are in British National Grid 27700. 

When the "Select by Location" analysis is run, the window remains open and hangs, it doesn't crash, but it has been left overnight processing and has not completed. When you try and cancel the operation, QGIS crashes entirely. 

---

- [error_data.zip](https://issues.qgis.org/attachments/download/7243/error_data.zip) (Neil Benny)

**Comment by roya0045** [comment]
No crash in 3.12 on windows, seems fine.

**Comment by alexbruy** [comment]
No crash and in master it works much faster then in 2.x
