### ISSUE TITLE
transportation network management

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#18698]
Author Name: **MRick -** (MRick -)
Original Redmine Issue: [10266](https://issues.qgis.org/issues/10266)

Redmine category:unknown

---
There was a QGIS plugin developed by a French company that allowed transportation networks management, but development as ceased and there was no update for 3 years. It will work only with QGIS 1.0 … But since it is open source, maybe the code could be useful? Plus it respects French transits norms of classifications.
https://github.com/Potimart/Potimart

Would it be possible to use this as a base to develop a plugin or a QGIS feature to be able to manage transportation networks from it?
I know there is a lot of demand from users to be able to manage transits directly from QGIS, a feature which unavailable actually.

---

- [Capture_d’écran_2014-06-03_à_01.58.51.png](https://issues.qgis.org/attachments/download/7307/Capture_d%E2%80%99%C3%A9cran_2014-06-03_%C3%A0_01.58.51.png) (MRick -)
- [Capture_d’écran_2014-06-03_à_01.55.31.png](https://issues.qgis.org/attachments/download/7308/Capture_d%E2%80%99%C3%A9cran_2014-06-03_%C3%A0_01.55.31.png) (MRick -)
- [Capture_d’écran_2014-06-03_à_01.55.46.png](https://issues.qgis.org/attachments/download/7309/Capture_d%E2%80%99%C3%A9cran_2014-06-03_%C3%A0_01.55.46.png) (MRick -)
- [Capture_d’écran_2014-06-03_à_01.57.55.png](https://issues.qgis.org/attachments/download/7310/Capture_d%E2%80%99%C3%A9cran_2014-06-03_%C3%A0_01.57.55.png) (MRick -)
- [Capture_d’écran_2014-06-03_à_01.58.24.png](https://issues.qgis.org/attachments/download/7311/Capture_d%E2%80%99%C3%A9cran_2014-06-03_%C3%A0_01.58.24.png) (MRick -)
- [Capture_d’écran_2014-06-03_à_01.58.41.png](https://issues.qgis.org/attachments/download/7312/Capture_d%E2%80%99%C3%A9cran_2014-06-03_%C3%A0_01.58.41.png) (MRick -)
- [25.png](https://issues.qgis.org/attachments/download/7317/25.png) (Giovanni Manghi)

**Comment by alexbruy** [comment]
Probably should be closed as it is about 3rd part plugin/scripts with limited country-specific usage.
