### ISSUE TITLE
Action widget in drag and drop form

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#18711]
Author Name: **Andreas Neumann** (@andreasneumann)
Original Redmine Issue: [10282](https://issues.qgis.org/issues/10282)

Redmine category:gui

---
It should be possible to include a button into a drag and drop form that starts an action assigned to the layer.

**Comment by alexbruy** [comment]
Seems already possible.

**Comment by andreasneumann** [comment]
Yes -  @elpaso implemented this for us.

Wasn't aware that I already had a feature request for this  in 2014 ;-)
