### ISSUE TITLE
Mode Defined Interval

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#18720]
Author Name: **Antonio Locandro** (Antonio Locandro)
Original Redmine Issue: [10292](https://issues.qgis.org/issues/10292)

Redmine category:symbology

---
Add a mode in which the interval size would be set manually

Use case: You want the interval size to be exactly 10

You can try to do it with Pretty Breaks but it is time consuming and it works first looking if it can classify for example by 2000,1000,500,200 etc

Maybe Pretty breaks should be replaced by "Defined Interval" as defining the interval would achieve what Pretty Breaks does, but extends it

When selecting defined interval Classes should be grayed out and Interval Size shown

**Comment by pjshelton** [comment]
I am assuming that this is for graduated Symbology. 

Pretty Breaks is still there as a mode.  And once you classify, you can double click on the Values and a dialog box opens where you can change the lower and upper values of the class to what ever you want.

And there is also the ability to add new classes.  Even though they land at the front of the list on creation they can be dragged to any location in the list.

@gioman this can be closed.
