### ISSUE TITLE
cmake find-python machinery cannot find python on Debian with MultiArch

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#18732]
Author Name: **Richard Duivenvoorde** (@rduivenvoorde)
Original Redmine Issue: [10307](https://issues.qgis.org/issues/10307)

Redmine category:build/install

---
Running Debian Testing with Multiarch option (eg needed for Skype....)
https://wiki.debian.org/Multiarch/HOWTO

This means that my libpython2.7.so is in
/usr/lib/x86_64-linux-gnu/libpython2.7.so
and not in 
/usr/lib

Not sure if this is Debian specific, but (though not trivial for me, I tried) it seems doable to add this
/usr/lib/i386-linux-gnu and /usr/lib/x86_64-linux-gnu/ to some search path?

(I manage anyway, because I know and add as a var in cmake. but...)

**Comment by suricactus** [comment]
Python 2.7 dependency is outdated by 2020, close.
