### ISSUE TITLE
Increase plugin download timeout

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#18808]
Author Name: **Bas Couwenberg** (@sebastic)
Original Redmine Issue: [10391](https://issues.qgis.org/issues/10391)

Redmine category:plugin_manager
Assignee: Borys Jurgiel

---
Back in March when the plugin server was moving to a new host, Francesco P. Lovergine filed "Debian Bug #742688":https://bugs.debian.org/742688 in which he reported problems updating the plugins.

The problem was tracked down to http://plugins.qgis.org/plugins/plugins.xml being slow and QGIS giving up the download too soon.

He suggests to increase the timeout to better handle situations like these.

Better diagnostics why the plugins cannot be updated/installed would also be appreciated as well as more redundancy in support infrastructure.

I'm forwarding this request as suggested by Alex Mandel in the "mailinglist thread":http://thread.gmane.org/gmane.comp.gis.grass.pkg.devel/18958/focus=887.

**Comment by suricactus** [comment]
This is already in place. https://github.com/qgis/QGIS/blob/master/python/pyplugin_installer/installer_data.py#L370 the configuration is inherited from `QgsNetworkAccessManager`.

![image](https://user-images.githubusercontent.com/2820439/76620030-f452e700-6534-11ea-9026-a7eadd94f15b.png)
