### ISSUE TITLE
Use field values for numerical / string entries when the algorithm is executed iteratively

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#18835]
Author Name: **Michael Douchin** (@mdouchin)
Original Redmine Issue: [10420](https://issues.qgis.org/issues/10420)

Redmine category:processing/core
Assignee: Victor Olaya

---
Processing allows to use an expression to calculate the value of a "number" entry. See http://docs.qgis.org/2.2/en/docs/user_manual/processing/toolbox.html#the-algorithm-dialog

When using a script or algorithm in "iterating" mode (green arrow next to one vector layer entry), it could be handy to be able to use one or more field names of this layer in the expression, so that the entry numbers or string can be calculated with an expression like 

```"somefield" * 2 + "otherfield"
```

**Comment by nyalldawson** [comment]
This is possible using data defined overrides for the parameters now
