### ISSUE TITLE
Basic Statistics button on Attribute table 

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#18859]
Author Name: **Randal Hale** (@rjhale1971)
Original Redmine Issue: [10447](https://issues.qgis.org/issues/10447)

Redmine category:attribute_table

---
I was wondering if it would be difficult to add a Statistics (Vector menu -> Analysis Tools -> Basic Statistics) to the attribute window. For instance I had two features selected and wanted to find the total area. I had to drop back to the Main QGIS Menu to find out this information. Had their been a button there on the table it would have made more sense. 

Just wondering. Keep up the good work

**Comment by roya0045** [comment]
Isn't the statistic panel sufficient? Maybe it wasn't present when this ticket was made but I think the panel is sufficient to cover this.

**Comment by rjhale1971** [comment]
Oh it is - and sorry - I completely forgot this had been filed. Close it out. I think when the request was made that wasn't around.

**Comment by roya0045** [comment]
@gioman Thanks for the quick follow-up!
