### ISSUE TITLE
If layer has labels it is always refreshed when activating/deactivating any other layer

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#18853]
Author Name: **Giovanni Manghi** (@gioman)
Original Redmine Issue: [10441](https://issues.qgis.org/issues/10441)
Affected QGIS version: 3.7(master)
Redmine category:map_canvas

---
Subject says it all, seems not necessary and it happens also with "render caching" active.

**Comment by nyalldawson** [comment]
This is fixed
