### ISSUE TITLE
Enable Incremental rendering of WMT-S tiles onto map canvas

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#18865]
Author Name: **Jeremy Palmer** (@palmerj)
Original Redmine Issue: [10453](https://issues.qgis.org/issues/10453)

Redmine category:map_canvas
Assignee: Martin Dobias

---
In QGIS 2.2 if you checked "Use render caching where possible to speed up redraws" in the rendering options WMT-S tiles were drawn  immediately after download on the screen.  Under QGIS 2.4 this no longer happens - with or without MTR enabled

This feature should be added back in as it really improves usability and makes the application more responsive.

**Comment by nyalldawson** [comment]
Fixed since 2.18
