### ISSUE TITLE
Further reduce vertex marker size

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#18912]
Author Name: **James Harvey** (James Harvey)
Original Redmine Issue: [10502](https://issues.qgis.org/issues/10502)

Redmine category:digitising

---
It would be nice to drop the vertex marker size less than 1 in the application settings. Sometimes the update won't apply either if I try dropping it from 3 down to 1. I would like to have much finer vertex crosses (eg .5 ) and also adjust colouring of them.

**Comment by alexbruy** [comment]
Already possible.
