### ISSUE TITLE
QgsPoint Z axis / 2.5D support 

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#18911]
Author Name: **SC SC** (SC SC)
Original Redmine Issue: [10501](https://issues.qgis.org/issues/10501)

Redmine category:unknown

---
In QgsPoint api documentation is possible read
```
Currently no Z axis / 2.5D support is implemented.

```

when a official support?

now it is important view z coordinate in a map feature

**Comment by suricactus** [comment]
This is possible now https://qgis.org/api/classQgsPoint.html#acf221ee34a130f9e7f24476401f29d4e . Close
