### ISSUE TITLE
Allow math expressions in print composer size and position controls

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#18952]
Author Name: **Alexandre Neto** (@SrNetoChan)
Original Redmine Issue: [10544](https://issues.qgis.org/issues/10544)

Redmine category:map_composer/printing

---
One very handy feature that many design software have is the ability to use simple math expressions in size and position controls fields.

For instance, if you have an item with a height of x, and you want to double it's height, you would be able to simply type after the x value '* 2' and press enter. The control would solve the math expression and set the new value. The same could be done with +, - , / and even %

**Comment by suricactus** [comment]
This particular feature request for x,y,h,w is already working. I guess should be closed and open a new one if something is omitted.
![Peek 2020-03-13 14-57](https://user-images.githubusercontent.com/2820439/76622810-ebfdaa80-653a-11ea-8ae6-d2bf7d381eb1.gif)
