### ISSUE TITLE
Legend and scale bar - do not refresh the size of the box

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#18963]
Author Name: **Lucien Blandenier** (Lucien Blandenier)
Original Redmine Issue: [10556](https://issues.qgis.org/issues/10556)

Redmine category:map_composer/printing

---
Hello,

Could it be possible to fix the box size of the legend and the scale bar? When refreshing the content of the legend, the box resize automatically to fit the content. It would be great to fix it with a checkbox.

Thanks

**Comment by roya0045** [comment]
Pretty sure this can be closed.
