### ISSUE TITLE
Correctly import qgis 2.0.1 symbology in later releases

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#19110]
Author Name: **Gabriele Monfardini** (@gabrimonfa)
Original Redmine Issue: [10723](https://issues.qgis.org/issues/10723)

Redmine category:symbology

---
*New description:*

Since QGIS 2.2 a few aspect of the symbolgy have been changed, this can lead to issue when importing projects made with 2.0.1.

See comments for details, in particular: https://github.com/qgis/QGIS/issues/19110#issuecomment-495833328

It would be good to have a routine that can handle with this cases.

----------------------
*Old description:*

Hi all,

I've found a regression in a 2.0.1 project.
Border stylization is not preserved when opening the project in 2.2.0-Valmiera or in trunk (QGIS 2.3.0-master revision:abcc5a).

I've reproduced the problem in a small test case.
The zip file contain a shapefile and a 2.0.1 project.

Attached images show the obtained results in:
* 2.0.1 (in Windows 32 bit)
* 2.2.0 (in Windows 32 bit)
* trunk (revision abcc5a in Linux 64 bit)

For me is a serious problem. 
I had several complex sytlization made with 2.0.1 and I cannot use any later version since I cannot afford to make again the stylization.

---

- [qgis-2.0.1-Dufour_win32.png](https://issues.qgis.org/attachments/download/7524/qgis-2.0.1-Dufour_win32.png) (Gabriele Monfardini)
- [qgis-2.2.0-Valmiera_win32.png](https://issues.qgis.org/attachments/download/7525/qgis-2.2.0-Valmiera_win32.png) (Gabriele Monfardini)
- [qgis-trunk_linux64.png](https://issues.qgis.org/attachments/download/7526/qgis-trunk_linux64.png) (Gabriele Monfardini)
- [prova.zip](https://issues.qgis.org/attachments/download/7527/prova.zip) (Gabriele Monfardini)

**Comment by nyalldawson** [comment]
Fixing this now is not worth the effort
