### ISSUE TITLE
wheel zoom using predefined scales

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#19200]
Author Name: **Kalle Kronholm** (Kalle Kronholm)
Original Redmine Issue: [10825](https://issues.qgis.org/issues/10825)

Redmine category:map_canvas

---
I have background maps from tile-services. These only look nice at predifined zoom-levels, which I have set in the "options" under "predifined scales". I can change the zoom-behaviour of my mouse-wheel in "options". There, under "mouse wheel action", I suggest an option where the wheel scrolls through the predefined scales.

**Comment by haubourg** [comment]
It works currently using project scales. Please reopen if necessary
