### ISSUE TITLE
Quick Search panel

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#19224]
Author Name: **Per Gammerath** (Per Gammerath)
Original Redmine Issue: [10853](https://issues.qgis.org/issues/10853)

Redmine category:vectors

---
At the moment we use the OSM-search plugin to navigate our maps. However, this plugin only works if you are online. We do have an address shapefile that could be used in conjunction with Select by Expression, but it's a cumbersome procedure. So what I would really like, is a search panel like OSM-search, that can search in a specific layer and specific columns. I have attached an image that should explain what I'm looking for.

---

- [Clipboard01.jpg](https://issues.qgis.org/attachments/download/7619/Clipboard01.jpg) (Per Gammerath)

**Comment by alexbruy** [comment]
Closing, as there is a plugin with required functionality. Please reopen if necessary.
