### ISSUE TITLE
Browser: add support to PostGIS raster

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#19239]
Author Name: **Paolo Cavallini** (@pcav)
Original Redmine Issue: [10871](https://issues.qgis.org/issues/10871)

Redmine category:browser

---
Currently raster tables are not visible in the browser. They are in DB Manager.

---

Related issue(s): #20953 (duplicates)
Redmine related issue(s): [12861](https://issues.qgis.org/issues/12861)

---

**Comment by nyalldawson** [comment]
This was fixed for 3.10

**Comment by pcav** [comment]
Great, thanks.
