### ISSUE TITLE
Add a shortcut icon for the plugin manager on the plugin toolbar

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#19288]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [10929](https://issues.qgis.org/issues/10929)

Redmine category:unknown

---
I'm developing a plugin and as I'm newbie in programmation, I *frequently need* to deactivate/reactivate my plugin in the plugin manager to check how works the modifications I've just done. Instead of :
- clicking Plugin menu
- then clicking Install/Manage the plugins
before u reach the list of plugins, I think a shortcut icon on the plugin toolbar would be very helpful (even if I finally assign a key shortcut to it)

**Comment by suricactus** [comment]
I do agree that a plugin icon is not needed and it will further clutter the interface. There is a dedicated menu entry "Plugins" and "Manage and install plugins..." is the first item, which is a good UX. @DelazJ are you convinced by now, that we don't need a toolbar icon for this?

**Comment by DelazJ** [comment]
> The diagram can also be placed by data-defining the :guilabel:`X` and :guilabel:`Y`
coordinate fields.

Euh... TBH, I selfishly adopted the Plugin Reloader and lived years without needing this icon so yes, the request can be closed, without any problem.
Thanks for triaging.
