### ISSUE TITLE
link metadata stored with the layer.

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#19356]
Author Name: **Alain FERRATON** (@FERRATON)
Original Redmine Issue: [11016](https://issues.qgis.org/issues/11016)

Redmine category:unknown

---
URL metadata in the Metadata tab is only saved in the project file.

Would it be possible to load / save the URL automatically if a metadata file is attached with the source layer.
example: shp.xml for shapefiles

another file format (qml?) for other sources.

see also # 3795

**Comment by nyalldawson** [comment]
> another file format (qml?) for other sources.

This is done already, with the .qmd extension
