### ISSUE TITLE
I'd like a plugin to configure the mouse buttons

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#19367]
Author Name: **Mathilde Gouret** (Mathilde Gouret)
Original Redmine Issue: [11028](https://issues.qgis.org/issues/11028)

Redmine category:customisation_framework

---
I have a mouse without scroll wheel and I find it rather hard to navigate (zoom in or out) in Qgis. 
Is there a way to develop a plugin that would allow the user to configure its mouse buttons ? In my case I would be interested to be able to congigure 1 button as the zoom in (as the scroll wheel does) and the other one as the zoom out.
But I'm also thinking that this plugin could allow the user to choose more options for its additional mouse buttons (Personaly I have 4 buttons, but I know that many mise can have more).

**Comment by alexbruy** [comment]
Closing as this is request for a plugin, not QGIS feature.
