### ISSUE TITLE
Pdf auto-open

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#19451]
Author Name: **Per Gammerath** (Per Gammerath)
Original Redmine Issue: [11122](https://issues.qgis.org/issues/11122)

Redmine category:unknown

---
I would appreciate an option to auto-open pdf files after they are generated.

**Comment by nyalldawson** [comment]
Implemented since QGIS 3 -- at least, there's an option to open the file explorer and highlight the generated file. I don't think explicitly opening it is a necessary extra setting given that this already exists.
