### ISSUE TITLE
make it possible to deactivate tips popup by command line option

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#19532]
Author Name: **Gerald Richter** (Gerald Richter)
Original Redmine Issue: [11222](https://issues.qgis.org/issues/11222)

Redmine category:gui

---
since it might be of use to see the tips when starting in interactive mode,
but undesired if QGIS is started in batch mode, since the tips popup interrupts the flow,

*it were great, if* the tips didn't come up when e.g. the --nologo option is set.

**Comment by alexbruy** [comment]
Startup tips were removed. Closing.
