### ISSUE TITLE
alternative layer coordinate readout with canvas orientation flip option

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#19599]
Author Name: **Gavin Fleming** (@gubuntu)
Original Redmine Issue: [11303](https://issues.qgis.org/issues/11303)

Redmine category:unknown

---
It would be useful in many cases to have a dynamic mouse coordinate readout in additional CRSs besides the canvas CRS. These additional CRSs could be chosen from a layer or from the CRS catalog and the readout(s) could be to the left of the canvas coord readout in the status bar. 

One use case is for working in a south-oriented CRS (as in South Africa) and wanting to view the map with north up but still see south-oriented coordinates.

An additional option in the south-oriented case would be to flip the canvas instead from the usual enu to wsu. 

As an interim solution for the first option above is to use the coordinate capture plugin, although tracking the alternative coordinates stops when you switch to other tasks.

**Comment by nyalldawson** [comment]
This would best be addressed by a 3rd party plugin
