### ISSUE TITLE
Allow editing gdal commands in processing

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#19619]
Author Name: **Paolo Cavallini** (@pcav)
Original Redmine Issue: [11323](https://issues.qgis.org/issues/11323)

Redmine category:processing/gdal

---
See the implementation in GDALTools itself. Thi, together with the next feature req, would allow to get rid of the duplication between GDALTools and Processing

---

Related issue(s): #22568 (relates), #23032 (duplicates), #28451 (duplicates)
Redmine related issue(s): [14600](https://issues.qgis.org/issues/14600), [15090](https://issues.qgis.org/issues/15090), [20631](https://issues.qgis.org/issues/20631)

---

**Comment by alexbruy** [comment]
I'm +1 to what @nyalldawson said. Editing command line does not fit into Processing world.

**Comment by alexbruy** [comment]
Passing additional command line parameters Implemented in c224a01. I think we can close this now.
