### ISSUE TITLE
 When using data defined colors the map legend shows always a black symbol

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#19761]
Author Name: **Fabien Cerbelaud** (Fabien Cerbelaud)
Original Redmine Issue: [11491](https://issues.qgis.org/issues/11491)

Redmine category:map_legend

---
Hi,
When I used a fields with color attribute to define colors in source of propertie definition for a thematic analysis the color is ok on the map but there is no color in legend. The color provides from a csv file joined with my shapefile. The problem still exist in map composer.

---

- [CLC_nomenclature_05.csv](https://issues.qgis.org/attachments/download/7998/CLC_nomenclature_05.csv) (Fabien Cerbelaud)
- [legend_color.jpg](https://issues.qgis.org/attachments/download/7999/legend_color.jpg) (Fabien Cerbelaud)
- [custom_legend.png](https://issues.qgis.org/attachments/download/8350/custom_legend.png) (Vincent Mora)

---

Related issue(s): #16952 (relates), #19032 (relates), #20452 (duplicates), #21536 (relates), #22241 (duplicates), #23755 (duplicates)
Redmine related issue(s): [8118](https://issues.qgis.org/issues/8118), [10629](https://issues.qgis.org/issues/10629), [12267](https://issues.qgis.org/issues/12267), [13491](https://issues.qgis.org/issues/13491), [14244](https://issues.qgis.org/issues/14244), [15835](https://issues.qgis.org/issues/15835)

---

**Comment by Bernd-Vogelgesang** [comment]
As there has been no solution for this problem over the last years (besides that there are no black symbols but now random colours in the legend, which doesn't help much as well), I would suggest to **remove the option for data-driven colours** in categorized layers, cause obviously none found a workaround to make them work, but instead leads many people into the same trap.

**Comment by roya0045** [comment]
@Bernd-Vogelgesang The fix is to just set this param instead of having 0 https://github.com/qgis/QGIS/issues/39882#issuecomment-723669783
