### ISSUE TITLE
One to many / many to one joins

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#19775]
Author Name: **Ed Hudspeth** (Ed Hudspeth)
Original Redmine Issue: [11505](https://issues.qgis.org/issues/11505)

Redmine category:relations

---
Currently, any join performed on a table is a one to one join - it would be great to perform one to many joins.

Example:
Table A = Towns
Table B = Customers (aspatial)

Join on Town name - currently only returns the first customer name it gets to, it would be good to list all.

**Comment by haubourg** [comment]
Cleaning session:

I think we have relations usefull for forms and individual edits. 
We have relational expressions allowing to do updates on several tables
We have virtual layer to take benefit of SQL power on any datasource
We have real databases underneath to play seriously when needed. 

I think the need raised here is inspired by ArcXXX that allows to propagate selections with one-to-many relations. I've always found it was a really unstraightful and cumbersome way of doing relational updates. 
I personaly wouldn't go this way, but  if someone has clear ideas of what to bring feel free.

**Comment by kylefelipe** [comment]
To join tables 1:N, N:N we can use DB Manager  to load a new layer, and then save as file...
Just navigate to Virtual Layers > Qgis Layer

![image](https://user-images.githubusercontent.com/24795382/59512067-45428b80-8e8e-11e9-8f58-50aa91b9fe68.png)
Select an layer and start a new SQL window...
U can use SQLite sintax to perform the join... 

https://sqlite.org/index.html
http://www.sqlitetutorial.net/
