### ISSUE TITLE
WFS server: artifacts when precision= 0 decimals

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#19776]
Author Name: **Paolo Cavallini** (@pcav)
Original Redmine Issue: [11506](https://issues.qgis.org/issues/11506)
Affected QGIS version: 3.4.5
Redmine category:qgis_server

---
If setting WFS decimals to 0 for a layer, the LizMap zoom to layer returns artifacts (lines pointing down to nowhere).

---

- [wfs_0_decimals.png](https://issues.qgis.org/attachments/download/8007/wfs_0_decimals.png) (Paolo Cavallini)
- [wfs_8_decimals.png](https://issues.qgis.org/attachments/download/8008/wfs_8_decimals.png) (Paolo Cavallini)

**Comment by gioman** [comment]
Tested, not an issue anymore.
