### ISSUE TITLE
ogr2ogr to merge several shapefiles in a folder

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#19888]
Author Name: **Filipe Dias** (@fsdias)
Original Redmine Issue: [11635](https://issues.qgis.org/issues/11635)

Redmine category:processing/gdal
Assignee: Giovanni Manghi

---
ogr2ogr can be used to merge several shapefiles. It would be useful to have an ogr2ogr based tool that merges several shapefiles stored in a folder. Here's an example code written by Darren Cope:

mkdir merged
for %f in (*.shp) do (
if not exist merged\\merged.shp (
ogr2ogr -f “esri shapefile” merged\\merged.shp %f) else (
ogr2ogr -f “esri shapefile” -update -append merged\\merged.shp %f -nln Merged )
)

Source: http://darrencope.com/2010/05/07/merge-a-directory-of-shapefiles-using-ogr/

**Comment by alexbruy** [comment]
Superseded by #29495
