### ISSUE TITLE
Save / export as image doesn't remember last used file type

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#19985]
Author Name: **marisn -** (marisn -)
Original Redmine Issue: [11752](https://issues.qgis.org/issues/11752)

Redmine category:gui

---
Both Print composer and main application options of saving as an image are affected.

Steps to reproduce:
* Project -> Save as image
* Choose "PNG" as an image type, save image
* Repeat aforementioned steps

Result:
When repeating exporting / saving as an image, the first of supported file formats is offered by default (BMP), although previously other more common file type has been used.

Expected result:
A last used file format is offered on next save / export. In provided test case it should be PNG when "Save as image" dialog is opened for a second time.

Tested with 2.7 f00db95 on ~AMD64 Gentoo with Qt 4.8.6

**Comment by alexbruy** [comment]
Fixed in master.
