### ISSUE TITLE
Set grid coordinate background color

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#19995]
Author Name: **Serge Rozentsvet** (@sergethedev17)
Original Redmine Issue: [11763](https://issues.qgis.org/issues/11763)

Redmine category:project_loading/saving

---
Current map Grids functionality in Composer allows setting of font foreground color for grid coordinates (see screenshot 1).
It may be difficult to see grid coordinates displayed "Inside frame" if there are other objects or text (eg map labels) underneath the coordinates.

Please add an option to set Background color for coordinates, similar to Background in layer labels (see screenshot 2).

---

- [screenshot1.png](https://issues.qgis.org/attachments/download/8155/screenshot1.png) (Serge Rozentsvet)
- [screenshot2.png](https://issues.qgis.org/attachments/download/8156/screenshot2.png) (Serge Rozentsvet)

**Comment by antoniolocandro** [comment]
I think this is now possible? Maybe time to close this issue

![image](https://user-images.githubusercontent.com/4627073/155356615-5799a72a-8b7e-472c-98e8-13d1836b5281.png)
