### ISSUE TITLE
Server Search in WMS dialog does not give feedback for empty search or results

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#20030]
Author Name: **Richard Duivenvoorde** (@rduivenvoorde)
Original Redmine Issue: [11806](https://issues.qgis.org/issues/11806)

Redmine category:web_services_clients/wms

---
In the Add Layer from WMS Server there is a tab 'Server Search' which uses the following service:

http://geopole.org/wms/search?search=&type=rss

This is working perfectly IF you type a word with one or more results, but if you are like me, and try to just search (NO search word), hoping you would just receive the first 50 hits or so then it looks like it is not working: there is not feed back.
The same if you do a search for a non excisting term like 'xxx'.

So feature request:
- if there is NO search term given: a message: 'please provide a search term'
- if NO results come back, a message: 'your search for xxx provided no results' 
(or anything better an native english speaker comes up with :-)

**Comment by alexbruy** [comment]
WMS Search was removed, see #35954.
