### ISSUE TITLE
Add visual changelog entries as QGIS startup tooltips

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#20046]
Author Name: **Paolo Cavallini** (@pcav)
Original Redmine Issue: [11828](https://issues.qgis.org/issues/11828)

Redmine category:documentation_and_help

---
QGIS tips could be made richer by adding individual visual changelog entries as separate tips. In this way, user will learn more quickly about new features for each version, with minimal effort and no duplication.
Currently the tips are cpp source and images are part of the resources:

https://github.com/qgis/QGIS/blob/master/src/app/qgstipfactory.cpp#L162

Visual changelog items can be exported to rst or html, but currently on one page. Some hacking will be needed to do such automatically.

So we could choose:

* copying the text into the ccp file by hand (duplication, not nice, but simple)
* (when user is online) to deeplink to the website with url's like:
http://qgis.org/en/site/forusers/visualchangelog260/#feature-color-palettes
and show those in the tips (I do not like the idea of leaving offline users orphans)
* rework the tips, so to separate the C++ frame and the rst content, and take the content straight from the documentation (this wouls also make translation easier and not duplicated).

Thanks Richard for hints.

**Comment by alexbruy** [comment]
Startup tips were removed. Closing.
