### ISSUE TITLE
QGIS startup is slow on windows with --configpath option

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#20061]
Author Name: **Regis Haubourg** (@haubourg)
Original Redmine Issue: [11845](https://issues.qgis.org/issues/11845)
Affected QGIS version: 2.6.0
Redmine category:project_loading/saving

---
Hi all, 
we experience very slow startup (from 1 to 5 minutes) on windows with QGIS 2.x (last test with 2.6.1) when using remote profiles with @--configpath@ option. 
Whole topic and process monitor logs are available "here":http://osgeo-org.1560.x6.nabble.com/QGIS-slow-startup-on-windows-td5177403.html.
This is related to QGIS trying to create files in @C:\\Windows\\CSC\\v2.0.6\\@, a system folder dedicated to store offline data, and that has special permissions.. 

Second startup is sometimes fast, sometimes slow. 

---

- [repetitive_ini_reading_pattern.jpg](https://issues.qgis.org/attachments/download/8205/repetitive_ini_reading_pattern.jpg) (Regis Haubourg)

**Comment by haubourg** [comment]
I reopen this issue, according to this [message](http://osgeo-org.1560.x6.nabble.com/QGIS-Developer-Profiler-tp5438376p5438423.html), this still occurs

**Comment by NathanW2** [comment]
I don't think it's related to this honestly.  I suspect it a few other
things.  Nyall and I (well mainly Nyall have been looking at some stuff
around slow start up times)

**Comment by Pedro-Murteira** [comment]
@haubourg Hello, is this still a problem in more recent releases?
