### ISSUE TITLE
Close without Saving lacks a keyboard shortcut

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#20104]
Author Name: **Sandro Santilli** (@strk)
Original Redmine Issue: [11890](https://issues.qgis.org/issues/11890)

Redmine category:gui

---
I cannot close qgis from the keyboard. alt-F4 prompts me but I can only pick "Cancel" or "Save", while "Close without Saving" does not have a keystroke selector.

I'm assigning to Anita in case it was intentional for some design reason ...
Feel free to unassign :)

**Comment by alexbruy** [comment]
In QGIS 3.x we now use standard QMessageBox, and all buttons does not have underlined text. However they can be accessible via cursor/Tab key. Probably can be closed.
