### ISSUE TITLE
labelling equidistant points in feature style

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#20166]
Author Name: **Rodrigo Principe** (@fitoprincipe)
Original Redmine Issue: [11958](https://issues.qgis.org/issues/11958)

Redmine category:labelling

---
I found the way to put points in a line at equidistant (in map units), and I think it is great!. But why not go feather? It would be helpful to label those points with the actual distance. I hope you understand me. I upload an simple example. Thanks!

---

- [propuesta_QGIS_antes.jpeg](https://issues.qgis.org/attachments/download/8273/propuesta_QGIS_antes.jpeg) (Rodrigo Principe)
- [propuesta_QGIS_desp.jpeg](https://issues.qgis.org/attachments/download/8274/propuesta_QGIS_desp.jpeg) (Rodrigo Principe)

**Comment by pjshelton** [comment]
#39263 has a much fuller description of what is being asked for.

@fitoprincipe, Be aware that (as of 3.16.1) a marker line does not guarantee that measure will start from the beginning of the feature, it depends entirely on whether the start of the line is visible.  You are only guaranteed that the marks you do see are that far apart.

**Comment by gioman** [comment]
Duplicate of https://github.com/qgis/QGIS/issues/39263
