### ISSUE TITLE
Progress indication when exporting from map composer

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#20227]
Author Name: **Samuel Ingarfield** (Samuel Ingarfield)
Original Redmine Issue: [12024](https://issues.qgis.org/issues/12024)

Redmine category:map_composer/printing

---
Currently, when exporting projects to PDF, the map composer window & QGIS just freeze until the render is complete. For complex projects this can take many tens of minutes. It would be good if we could have some indication of progress during this process, so users don't end up killing the process thinking it has died.

I would imagine that this could take the form of a progress bar, with some extra info (ie, rendering rasters; rendering labels etc)

Given that most of this info is emitted by builds with debug enabled anyway I wouldn't imagine that this would be too much work.

**Comment by alexbruy** [comment]
Duplicates #14747.
