### ISSUE TITLE
Lock the scale in the map view

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#20236]
Author Name: **Oskar Karlin** (@Oskarlin)
Original Redmine Issue: [12033](https://issues.qgis.org/issues/12033)

Redmine category:unknown

---
I'm making printed maps in QGIS and need to know how the symbols and labels look exactly in a certain scale. I could select the scale in the map view but everything is a little bit zoomed out. It's hard to see the details. I could go into the print composer and zoom in there to have a closeup look but it's kind of a hassle to have two windows open all the time and in the print composer I have to refresh the map each time I do a change.

So, I'd like to have the possibility to freeze the map view to a certain scale so that when I zoom in, the symbols etc stay in the selected scale!

---

- [Screen_Shot_2015-01-23_at_13.03.32.png](https://issues.qgis.org/attachments/download/8322/Screen_Shot_2015-01-23_at_13.03.32.png) (Oskar Karlin)
- [Screen_Shot_2015-01-23_at_13.03.49.png](https://issues.qgis.org/attachments/download/8323/Screen_Shot_2015-01-23_at_13.03.49.png) (Oskar Karlin)

**Comment by alexbruy** [comment]
Seems issue was solved, closing.
