### ISSUE TITLE
Allow transfer of rasters from QGIS to PostGIS through DBManager

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#20240]
Author Name: **Guillaume Larocque** (@glaroc)
Original Redmine Issue: [12037](https://issues.qgis.org/issues/12037)

Redmine category:unknown

---
There doesn't appear to be a way to transfer files from QGIS to PostGIS in DBManager, either through a DBManager menu item or through drag and drop from the filesystem, QGIS Browser or QGIS layer manager. Note that this issue is not the same as #14632, which describes importing FROM QGIS to PostGIS. That part is already implemented. What this issues is asking for is the other way around... from QGIS to PostGIS.

**Comment by alexbruy** [comment]
Duplicates #14632.
