### ISSUE TITLE
Function Editor in Expression widget : a button to delete a useless function

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#20260]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [12058](https://issues.qgis.org/issues/12058)

Redmine category:expressions
Assignee: Nathan Woodrow

---
Hi,
It could be nice to have a button that helps to delete wrong or useless custom functions in the function Editor tab in expression dialog.

**Comment by alexbruy** [comment]
Duplicates #27513.
