### ISSUE TITLE
Paths with backslash instead of slash on Windows

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#20280]
Author Name: **Miroslav Umlauf** (@mirouml)
Original Redmine Issue: [12084](https://issues.qgis.org/issues/12084)

Redmine category:unknown

---
Any chance to have paths on Windows with backslash instead of slash as it properly should be? I mean show it in "Layer source", metadata properties, maybe also saved in project file?

**Comment by nyalldawson** [comment]
This should already be fixed in most places, although there's a chance there's still some places where the non-native slashes are shown. New bug reports should be created if any of these are found.
