### ISSUE TITLE
Saving results of Topology Checker plugin into a separate file

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#20294]
Author Name: **Andrea De Felici** (Andrea De Felici)
Original Redmine Issue: [12099](https://issues.qgis.org/issues/12099)

Redmine category:c++_plugins/topology_checker

---
Hi to all,
it would be very useful to save the results of Topology Checker plugin into a separate shapefile with the "wrong geometries" found, or as a simple "report" in a text file form containing the list of the geometries having some problems, so we could send that files to people working with other GIS systems to help them to find objects that have to be fixed.

Thank you very much

Andrea De Felici

**Comment by alexbruy** [comment]
Duplicates #16653.

**Comment by magerlin** [comment]
I can see several parallel posts on this issue which are all marked as "Closed".

But as far as I can see it i still not possible to store the results in latest version (3.26.3)?

**Comment by Bandersnatchie** [comment]
I agree, this is still not solved! We want to export the "Topologie Errors"  as vector data.
