### ISSUE TITLE
dbManager: store queries also globally

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#20315]
Author Name: **Stefan Blumentrath** (@ninsbl)
Original Redmine Issue: [12121](https://issues.qgis.org/issues/12121)

Redmine category:db_manager

---
PostGIS/Spatialite queries are often written project specific. However, they might also be re-purposed in other projects / contexts or by other colleagues (the "share your code" idea), so similar projects do not have to start from scratch. In order to be able to share queries more simply among projects or colleagues (e.g. as a kind of templates for more general purpose queries) it would be useful if dbManager could store queries also globally and not only within QGIS project files (as it is the case at the moment).

**Comment by alexbruy** [comment]
In master there is an option to import/export queries. Closing.
