### ISSUE TITLE
Set QGIS Proxy settings before installation

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#20318]
Author Name: **armin11 -** (armin11 -)
Original Redmine Issue: [12124](https://issues.qgis.org/issues/12124)

Redmine category:build/install

---
Actually the proxy is configured in {home}/.config/QGIS/QGIS2.conf 
This file is generated when the specific user starts QGIS for the first time and the changes which are made under the Option menu are stored to this file too.
A problem occurs under a distributed environment. Maybe qgis should be distributed to different clients in by using packages. The package distributing systems only installs qgis on the specific client, but is not able to define the proxy settings at this time. 
It would be better to allow the default proxy settings to be defined at /etc/qgis/ level - maybe as a template for {home}/.config/QGIS/QGIS2.conf and not to set it by the application itself :-( .

**Comment by alexbruy** [comment]
In 3.x there is a support for global settings file where one can set desired defaults. Closing.
