### ISSUE TITLE
Export/Print Print Composers from the command line

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#20320]
Author Name: **Samuel Ingarfield** (Samuel Ingarfield)
Original Redmine Issue: [12126](https://issues.qgis.org/issues/12126)

Redmine category:map_composer/printing

---
Often, I have projects with many print composers defined. These projects involve dynamic data that changes frequently (pulled from some backend database). It would be good if there were a way to export print composers (which have been previously defined) from the command line, so that this can be batch/shell scripted.

Something like 
@qgis --export-print-composer name-of-composer -f pdf -o output-file.pdf@

**Comment by Gustry** [comment]
There is now qgis_process :

```
qgis_process run native:printlayouttopdf
```
