### ISSUE TITLE
Digitize/edit features using coordinates

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#20332]
Author Name: **Nicholas Duggan** (Nicholas Duggan)
Original Redmine Issue: [12138](https://issues.qgis.org/issues/12138)

Redmine category:digitising

---
Although QGIS provides the ability to add points through WKT, CSV and even POSTGIS, this is doesn't help when you need to add another point or move a vertex to another exact coordinate...what do you do? 
Other software supports this kind of functionality and it is used frequently for survey to alter and add points for interpolation.
Currently the only option is Numerical Digtize, a QGIS Plugin, obviously you need to know that it exists to be able to use it, this still misses some functionality though.
When training, this is a common question that is asked of me.

**Comment by uclaros** [comment]
This functionality is available for quite some time now either with *Advanced Digitizing Tools* or the *Vertex tool*
