### ISSUE TITLE
Using 'multi layered' TTF symbols

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#20366]
Author Name: **Rohrer Daniel** (Rohrer Daniel)
Original Redmine Issue: [12175](https://issues.qgis.org/issues/12175)

Redmine category:symbology

---
Hello,

I try to work with the TTF font Cadastra downloadable from

http://www.cadastre.ch/internet/cadastre/fr/home/products/cadastra_map.html

This CadastraSymbol_TTF.zip Police consists of 2 "layers" 1 for the symbol; 1 to the symbol of the mask.

Installed ubuntu 14.04, using commands

```
sudo gnome-font-viewer CadastraSymbol.ttf
sudo gnome-font-viewer CadastraMask.ttf

```

This font is available in 2 distinct definitions in LibreOffice, while in QGIS, it appears "that" made in its release: Layer 1 + Layer 2, all in one color (=> so unusable).

Is it possible use those in the same way as LibreOffice (TTF layers separated)?

Thank you for your commitment,

Best Regards

Daniel

---

- [cadastradefrit.zip](https://issues.qgis.org/attachments/download/8409/cadastradefrit.zip) (Rohrer Daniel)

**Comment by nyalldawson** [comment]
The font download link is broken, and I can't find any replacement. Closing this as not-reproducible.
