### ISSUE TITLE
Add support for margins for grid frames

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#20400]
Author Name: **Roscoe Lawrence** (Roscoe Lawrence)
Original Redmine Issue: [12211](https://issues.qgis.org/issues/12211)

Redmine category:map_composer/printing

---
When creating a frame for a grid, it will be useful if the margin can be set.
The desired effect can be viewed in the attached images.

---

- [with_margins.png](https://issues.qgis.org/attachments/download/8428/with_margins.png) (Roscoe Lawrence)
- [without_margin.png](https://issues.qgis.org/attachments/download/8429/without_margin.png) (Roscoe Lawrence)

**Comment by nyalldawson** [comment]
Implemented as of QGIS 3.6
