### ISSUE TITLE
Advanced Digitizing - finishing up tool

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#20425]
Author Name: **Klas Karlsson** (@klakar)
Original Redmine Issue: [12240](https://issues.qgis.org/issues/12240)

Redmine category:digitising

---
The new advanced digitizing panel (CAD tools) is great. To make it even better I'd like a function to finish an object more easily.

The last vertex in a rectangular object would be 90 degrees to the starting vertex... Is it possible to snap, not only at a common angle towards the previous vertex, but also to the first?

(img: AdvDig_dblSnapping.jpg)

If it was possible to snap to "self", you could also use alt+a to "lock" angle, and use cursor to snap to first vertex. This I imagine may be harder to acheive (snap to self)?

What I would essentially like, is a way to cleanly and easily finish an object.

---

- [AdvDig_dblSnapping.jpg](https://issues.qgis.org/attachments/download/8448/AdvDig_dblSnapping.jpg) (Klas Karlsson)

**Comment by LKajan** [comment]
As far I understood the request right this is possible at least from 3.16 with advanced digitizing tools when self snapping is enabled in native project snapping options.
