### ISSUE TITLE
Options for multiple scalebars

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#20518]
Author Name: **Nicholas Duggan** (Nicholas Duggan)
Original Redmine Issue: [12342](https://issues.qgis.org/issues/12342)

Redmine category:map_composer/printing

---
Hi, Simple request, would you be able to put in an option on the scalebar menu so that the text can be put underneath the scalebar? By this I am referring to the ticks middle and ticks down options.
Frequently I deal with offshore mapping which requires a scalebar in nautical miles and also metres and I often have to make the map in ArcGIS because there is no tidy way of adding 2 scalebars appropriately. The common method in other software is to have a "ticks up" and a "ticks down" with the text above and below.

**Comment by roya0045** [comment]
This is implemented in the display submenu.
