### ISSUE TITLE
Coordinate System GUI Improvement

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#20517]
Author Name: **Nicholas Duggan** (Nicholas Duggan)
Original Redmine Issue: [12341](https://issues.qgis.org/issues/12341)

Redmine category:projection_support

---
The current Coordiate system interface for QGIS (as of 2.0) is no longer (in my personal opinion) suitable. 
As good as it is to be able to search datum and coordinate systems by SRS/EPSG the GUI is quite difficult to see what the false eastings/ false northing are or other information related to the coordinate system being used. I currently struggle to see which transformation is being used for each of the data I am using in the data frame (if at any at all) and when there is a situation where I need to create a coordinate system to make my map more accurate, I have to do it in a text file and apply it - then check on the map - then adjust.....
It would be useful to have an interactive GUI like the one in ArcGIS or CADCorp where all the relevant coordinate system information is displayed and when the layer properties are accessed, the relevant coordinate transformation can be seen for that data relevant to the data frame.
To really shine, it would be amazing if QGIS can add something which the other DON'T have - the coordinate system suitability. Each coordinate system has a level of accuracy, this can be directlt linked to scale - it would be fantastic & a huge development to have this displayed on the GUI or data frame to feedback to the user on the suitability of their coordinate system.

**Comment by nyalldawson** [comment]
Should be fixed in current versions -- this has been considerably re-worked
