### ISSUE TITLE
Weighted concentration renderer: difficult to remove weights

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#20526]
Author Name: **Paolo Cavallini** (@pcav)
Original Redmine Issue: [12351](https://issues.qgis.org/issues/12351)
Affected QGIS version: 3.0.0
Redmine category:gui

---
If I select one field as a weight for the concentration renderer, to remove it I cannot select an empty field, but I have to erase the content by hand. A minor issue, but annoying nevertheless.

**Comment by alexbruy** [comment]
Seems fixed by #36666.
