### ISSUE TITLE
add "shape://slash" geoserver like symbology

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#20523]
Author Name: **Oskar Karlin** (@Oskarlin)
Original Redmine Issue: [12348](https://issues.qgis.org/issues/12348)

Redmine category:symbology

---
Is it possible to create a line with a line pattern in a fixed angle? See attached map image. 

In Geoserver it's apparently called "shape://slash"?

I have managed to create a marker line with a line at 45° but that one is always 45° from the lines angle at that point (see second attachment). I want it to be fixed. 

If it's not possible, I'd like to make a feature request!

---

- [slash-line.png](https://issues.qgis.org/attachments/download/8492/slash-line.png) (Oskar Karlin)
- [markerline.png](https://issues.qgis.org/attachments/download/8493/markerline.png) (Oskar Karlin)

**Comment by nyalldawson** [comment]
This is possible either via line pattern fills or hatched line symbol layers
