### ISSUE TITLE
Allow controlling and moving curved labels along line

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#20563]
Author Name: **Alexandre Neto** (@SrNetoChan)
Original Redmine Issue: [12389](https://issues.qgis.org/issues/12389)

Redmine category:labelling

---
Using data defined properties, it's possible to move and fix label's position by using the move label tool to drag and drop it to the desired position. For horizontal and vertical labels, it works as expected giving the user very nice control over the output.

For curved labels, it would be nice if we could control the position of the label on the line, keeping it curved, but fixing its position relatively with the line beginning (or its end). In that case, the move label tool should be able to control a variable containing the label position. moving it back and forward in the line.

**Comment by pjshelton** [comment]
The ability to control the position of the label on the line has been implemented in the North Road update to QGIS 3.16. 

 The move label tool does not keep the label on the line.

**Comment by pjshelton** [comment]
please see #33374 for why we want to keep the current behaviour even if it has to be renamed "detach label from curve"
