### ISSUE TITLE
Disable the line edit about filepath destination in dialogs

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#20578]
Author Name: **Etienne Trimaille** (@Gustry)
Original Redmine Issue: [12405](https://issues.qgis.org/issues/12405)

Redmine category:gui

---
When users are using the "save as" function or others algorithms from the raster or vector menu, they "very" often use the line edit to put the name of the file and not the full file path.
Then an error will occur, because they can't write in the root folder.

Is it possible to disable this line edit by default ?
However, I know that a lot of us use this line edit, so we may add an option in the settings to unlock these lines edits.
Or improve the UI to highlight the "browse" button.

**Comment by alexbruy** [comment]
See also #20106.

**Comment by alexbruy** [comment]
There is also a bugreport #35651
