### ISSUE TITLE
Add random function with seed to expressions

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#20630]
Author Name: **Olivier Dalang** (@olivierdalang)
Original Redmine Issue: [12482](https://issues.qgis.org/issues/12482)

Redmine category:expressions

---
Hi !

When using data defined values, it's hard to use the rand() function, because a new random number is generated all the time.

A symbol with this as polygon fill color:
@color_hsl(rand(0,360),100,50)@
will be changing color at each redraw, making the map look like a disco party (not saying it's not nice ;) ).

Why not add another random function where one could specify a seed, so that the random number is always the same. Typically, one would use the feature's ID as the seed.
@color_hsl(rand_seed($id,0,360),100,50)@
This way, the random color would always be the same, hopefully even across different setups.

Thanks !

Olivier

**Comment by suricactus** [comment]
This was fixed and merged as part of 3.12 release. The issue should be closed.
