### ISSUE TITLE
Positioning histograms with QGIS 2.8

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#20699]
Author Name: **Fred Dobruszkes** (Fred Dobruszkes)
Original Redmine Issue: [12559](https://issues.qgis.org/issues/12559)

Redmine category:diagrams

---
I try to draw a map with histograms related to points (namely, selected European airports) rather than to areas as apparently more commonly done.

In term of position, I realise the histograms are vertically centred on the points. This procedure is likely derived from the assumption that in case of polygons instead of points, it makes sense to locate histograms at the centre of spatial units (all readers would thus spontaneously make the link between histograms and places).

Yet with points, such positioning algorithm involves that histograms’ bases can be far away from the related points. For instance, considering the attached map, histograms for Madrid and Barcelona airports have their base in Algeria, while Rome is in the sea, Brussels in France and Athens in Crete. In my mind, this does not make sense because most readers would spontaneously make the link between the histogram’s basis and the supposed related places.

What do you think? Any reasonable solution?

Many thanks in advance.

Fred

---

- [histo.png](https://issues.qgis.org/attachments/download/8580/histo.png) (Fred Dobruszkes)

**Comment by pjshelton** [comment]
![image](https://user-images.githubusercontent.com/39154868/103082882-d91a1980-4626-11eb-9455-bb40189e6f8b.png)

We could probably close out this request as there is now various ways to locate the bottom of all diagrams.
