### ISSUE TITLE
atlas - export only certain pages

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#20763]
Author Name: **Jesse McMillan** (Jesse McMillan)
Original Redmine Issue: [12650](https://issues.qgis.org/issues/12650)

Redmine category:map_composer/printing

---
I would like the ability to export only certain pages from an atlas.
For instance:I have an atlas with 149 pages, and I update pages 3,5,7-10. I would like to export those pages for reprint to a single PDF. Exporting the entire 149 again to print just those is time consuming, but if I could just export the 6 pages I updated it would be great.

---

- [buttons-1qgis.PNG](https://issues.qgis.org/attachments/download/8634/buttons-1qgis.PNG) (Jesse McMillan)
- [buttons-2arcgis.PNG](https://issues.qgis.org/attachments/download/8635/buttons-2arcgis.PNG) (Jesse McMillan)
- [export-arcgis.PNG](https://issues.qgis.org/attachments/download/8636/export-arcgis.PNG) (Jesse McMillan)

**Comment by roya0045** [comment]
The atlas bar now lets you select the atlas feature that you want, thus addressing this.
