### ISSUE TITLE
QGIS should backup settings before save

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#20791]
Author Name: **marisn -** (marisn -)
Original Redmine Issue: [12684](https://issues.qgis.org/issues/12684)

Redmine category:unknown

---
As per title - QGIS app should make a backup copy of settings file(s) before writing out a new configuration.

Rationale - during a quite long georeferencing session with QGIS 2.9.0 (8b37ea2), at some point something went south and all QGIS settings were lost. First I observed missing WMS providers during the same work session, then, after restart of QGIS, I was greeted with a pristine, first time run QGIS configuration. Costed me all WMS service providers with their configuration :( Afterwards I haven't been able to reproduce configuration loss thus this is a wish on automatic backups not a bug report on configuration loss.

---

Related issue(s): #21541 (relates)
Redmine related issue(s): [13496](https://issues.qgis.org/issues/13496)

---

**Comment by m-kuhn** [comment]
@marisn is this still valid?

**Comment by marisn** [comment]
> @marisn is this still valid?

Qt 5.10 has enabled by default QSettings::AtomicSyncRequired and thus data loss should not happen any more.  This bug now can be closed.

**Comment by m-kuhn** [comment]
Thanks
