### ISSUE TITLE
Add option for "Save as Image" to create a georeferenced file

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#20795]
Author Name: **Michael Sumner** (Michael Sumner)
Original Redmine Issue: [12689](https://issues.qgis.org/issues/12689)

Redmine category:projection_support

---
Currently both the TIF and TIFF options for Project/Save as Image only create TIFF file with world file (.tif/.tifw or .tiff/.tiffw pairs). 

Please add the ability to create a fully georeferenced GeoTIFF that includes the projection metadata. Currently these files are not useable as maps without manually adding this information.

**Comment by nyalldawson** [comment]
Implemented in 3.10
