### ISSUE TITLE
Data defined opacity for vector features

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#20868]
Author Name: **Olivier Dalang** (@olivierdalang)
Original Redmine Issue: [12769](https://issues.qgis.org/issues/12769)

Redmine category:symbology

---
Hi !

Lately, more and more settings got data-definable. But it seems opacity/transparency was somewhat forgotten !

Of course, it's possible to achieve the result by data-defining the color of each symbol layer, but then one must hardcode the color in the code.

So I'd suggest adding the ability to data-define transparency, which I think can be useful in a lot of cases.

Thanks !!

Olivier

---

Related issue(s): #21108 (relates)
Redmine related issue(s): [13033](https://issues.qgis.org/issues/13033)

---

**Comment by nyalldawson** [comment]
This was implemented already
