### ISSUE TITLE
Generate Mailing Labels

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#20907]
Author Name: **Keith Kie** (Keith Kie)
Original Redmine Issue: [12811](https://issues.qgis.org/issues/12811)

Redmine category:unknown

---
Hello QGIS community! This is my first post on here so my apologies for its roughness. I tried a search for "mailing labels" to see if a feature request has already been requested and nothing showed up in the results, so I felt it would be okay to submit a new ticket.

+A little background+: I work for a small municipality and I noticed mailing label generation is the primary function of most of our city GIS users. However QGIS doesn't have an easy way to do this. A stack-exchange search showed end users making custom scripts and programs to handle parsing the data out and getting mailing labels generated (which isn't pretty, it's time consuming, and leaves human error as a risk, most end users are planners/building inspectors/code enforcement/or other departments who do NOT have an IT background).

+Why this is important+: Municipalities have to follow a lot of rules and procedures, among them are notifying residents 300 to 500 feet from a construction project, paint, sealing, chemical fumes, parade routes, event parking permits, etc. Currently most cities have to rely on commercial products to meet this need, its very expensive and smaller rural townships and municipalities struggle to make ends meet, most staff wear multiple hats to get the jobs done. We need the help.

+Objective+: Basically its taking a property (or properties) usually selected by their Associated Parcel Number (APN), buffering to the correct distance (dissolved if more than one parcel), selecting every parcel that is even barely in the buffer zone, and generating owner or renter mailing information (generic "current resident" or something) that can be printed on basic Avery (or other brand) mailing labels.

So something like this is a bit of a challenge to make "user friendly", and I know it would probably take a tremendous amount of time and dedication to implement a plugin or core feature into QGIS, and all I can do is ask very nicely if any volunteer would like to take this project on. I know several towns and communities that will be singing your praises forever.

Thank you and all the best,
Keith

**Comment by alexbruy** [comment]
Maybe I misunderstands, but isn't this doable with atlas priting?

**Comment by alexbruy** [comment]
Closing for the lack of feedback. Please reopen if necessary.
