### ISSUE TITLE
option to separately set the transparency and contour line rubberband

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#21026]
Author Name: **Alain FERRATON** (@FERRATON)
Original Redmine Issue: [12946](https://issues.qgis.org/issues/12946)

Redmine category:map_canvas

---
Currently the line color option of rubberband does not separately set the transparency of the contour.
It would be nice to be able to have such an opaque contour line associated with a transparent fill.

**Comment by alexbruy** [comment]
Already possible.
