### ISSUE TITLE
Selection toolbar

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#21045]
Author Name: **Saber Razmjooei** (@saberraz)
Original Redmine Issue: [12967](https://issues.qgis.org/issues/12967)

Redmine category:gui

---
I think we should have a seprate toolbar for "Selection". Currently, there is "Attributes" toolbar which contains spatial selection (not really attribute).
Other items like "Select by location" can be moved to the "Selection" toolbar too.

**Comment by alexbruy** [comment]
See also #20350.
