### ISSUE TITLE
Adding new attribute "Height of geoid" to QgsGPSInformation

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#21076]
Author Name: **Holger Eberhardt** (Holger Eberhardt)
Original Redmine Issue: [12999](https://issues.qgis.org/issues/12999)

Redmine category:unknown

---
I am trying to use QGIS for collecting points with height information in the field. The positional information comes from a precision RTK GPS (precision +/- 2 cm). I have to grab the height information from the "elevation" attribute of the actual QgsGPSInformation object, but this is value is a geodetic height that has been calculated in the GPS with quite inaccurate methods. Therefore this height can differ clearly from the accurate geodetic height (37 cm in my test area). It would be much better / more precise to record the ellipsoidal height and apply a precise value for the local difference between ellipsoidal and geodetic height (quasigeoid undulation).

I think this possibility could be easily implemented in QGIS, because the NMEA sentence "GGA" contains the information "Height of geoid (mean sea level) above WGS84 ellipsoid" (see e.g. http://www.gpsinformation.org/dale/nmea.htm#position ). If this information could be added as a new attribute to the QgsGPSInformation, the "ellipsoidal height" is easily calculated as the sum of "geodetic height" an "geoid height".

I think this would greatly improve the possibilities of QGIS for collecting precise 3D positional data!

Thanks for reading

theudebert

**Comment by nyalldawson** [comment]
Fixed by 74d053242eaecc029e2855e02f73aef3196c8c88
