### ISSUE TITLE
Add interactive editing tools using spatial operators (difference, buffer, clip..)

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#21122]
Author Name: **Regis Haubourg** (@haubourg)
Original Redmine Issue: [13050](https://issues.qgis.org/issues/13050)

Redmine category:digitising

---
We have users here missing some very handy Mapinfo digitizing tools. Those tools allow to modify features inside the currently edited layer, without any need to create new layers and copy-paste. 

That would require for some operators to define source and target features (intersect, clip, difference), for others, selection is enough (buffer). See attached picture to explain what MI does. 

This has been discussed some years ago (Anita should remember that) but I couldn't dig that topic out of archives.  

Cheers
Régis 

---

- [digitizing_in_MI.png](https://issues.qgis.org/attachments/download/8885/digitizing_in_MI.png) (Regis Haubourg)
- [clip.gif](https://issues.qgis.org/attachments/download/12346/clip.gif) (Jan Lippmann)

**Comment by DelazJ** [comment]
@haubourg can we consider this as fixed and close it?

**Comment by suricactus** [comment]
Close?

**Comment by j-lippmann** [comment]
With "edit in place" Feature there are some improvements. I Think the theme digitising needs a QEP because of missing tools and reduce geometry errors...

Closing this issue is ok.
