### ISSUE TITLE
Add WMS-T (time) support

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#21152]
Author Name: **Anita Graser** (@anitagraser)
Original Redmine Issue: [13085](https://issues.qgis.org/issues/13085)

Redmine category:web_services_clients/wms

---
Add support for WMS with time support to Add WMS layer.

http://docs.geoserver.org/latest/en/user/services/wms/time.html

http://mapserver.org/ogc/wms_time.html

---

Related issue(s): #17507 (relates)
Redmine related issue(s): [8809](https://issues.qgis.org/issues/8809)

---

**Comment by alexbruy** [comment]
Probably can be closed now as this functionality was added to master recently.
