### ISSUE TITLE
Unexpected behaviour in QGIS when saving the duplicate of a point shape

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#21161]
Author Name: **Jan Becker** (Jan Becker)
Original Redmine Issue: [13094](https://issues.qgis.org/issues/13094)

Redmine category:map_legend

---
Hello everyone,

I recognized an unexpexted behaviour in QGIS. I have a point shape and needed a copy of it to delete some points for some analyzing. When I finished editing the copy I was saving it and realized that it overwrites the original shape.

Here is what I did:

1. I loaded a point shape.
2. I duplicate the layer by left clicking on the layer and choosing 'Duplicate'.
3. I delete some points in the duplicated layer and finish it by clicking 'Save layer edits'.
4. When I refresh, the changes are also done for the original layer.

I know that I just create a duplicate of the layer and not the data, but I guess it would be better to have an option that asks if you want to overwrite the original shape file or if you want to save the duplicate as a new. Otherwise it is irritating and giving an unexpexted behaviour.

Best regards

**Comment by DelazJ** [comment]
Should we close this one. Seems to be a misuse of the "duplicate layer" function...

**Comment by gioman** [comment]
> Seems to be a misuse of the "duplicate layer" function..

correct.
