### ISSUE TITLE
Georeferencer: Ability to produce compressed output

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#21175]
Author Name: **Bernd Vogelgesang** (Bernd Vogelgesang)
Original Redmine Issue: [13110](https://issues.qgis.org/issues/13110)

Redmine category:c++_plugins/georeferencer

---
I'm currently using the Georeferencer heavily to import scanned fieldmaps from A3 paper maps. As it is import to see every little detail, I scan those maps with 600dpi, saved as jpg.

The only output option for the resulting raster is GeoTiff so far, which ends up in file sizes above 1 Gb, so I have to manually translate them with the raster tools to jpg to get 80 Mb files, which perform so much better in my cloud-synced work environment than the original monsters, which I than have to delete to save space.

It would be very nice to be freed from these extra steps by getting the option to save to other formats than those huge GeoTiffs directly from within the Georeferencer.

**Comment by roya0045** [comment]
A compression setting is present, this can be closed.
