### ISSUE TITLE
Handle Bad Layers Dialog Improvements

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#21190]
Author Name: **Andrew Carne** (@Andcarne)
Original Redmine Issue: [13125](https://issues.qgis.org/issues/13125)

Redmine category:gui

---
When selecting multiple layers and clicking the Browse button in the Handle Bad Layers dialog, it always seems to default to the OSGEO bin directory. Would it be possible to have it remember the last location, like it does when handling an individual layer?

This would expedite re-linking a number of bad layers with a common directory structure.

Another improvement would be if the single file relink would default to the correct extension based on the file being relinked, as opposed to just remembering the last file type relinked.

**Comment by alexbruy** [comment]
Please check is this solved in master, there were some work done on this dialog.

**Comment by roya0045** [comment]
Auto-finder work on all or selected layer, this should address this.

**Comment by alexbruy** [comment]
Closing for the lack of feedback. Please reopen if necessary.
