### ISSUE TITLE
QGIS LTR version checks for latest non-LTR QGIS version

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#21240]
Author Name: **Richard Duivenvoorde** (@rduivenvoorde)
Original Redmine Issue: [13178](https://issues.qgis.org/issues/13178)

Redmine category:unknown

---
See this thread: https://lists.osgeo.org/pipermail/qgis-developer/2015-August/038715.html

Currently when you use the menu item: 
 Help/Check QGIS Version 
in current LTR version 2.8.3, it reports back that 2.10.1 is the latest version, and the users is urged to download that:
 http://qgis.org/version.txt

It would be better if the LTR version checks for a version.ltr.txt.

Feature Request:
Another outcome of the discussion is that maybe QGIS should check it's latest version every now and then and report to the user if there is newer (either LTR or stable) version available. It should not become a 'nag-screen' though...

**Comment by DelazJ** [comment]
I wonder if #23318 and this one are not duplicates (nor if they are not closed by commits at the end of #31298)

**Comment by m-kuhn** [comment]
Fixed in qgis/QGIS-Website@e105333
