### ISSUE TITLE
Topology Checker (output/export)

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#21266]
Author Name: **Erik van der Knaap** (Erik van der Knaap)
Original Redmine Issue: [13205](https://issues.qgis.org/issues/13205)

Redmine category:unknown

---
I use the plugin "Toplogy Checker". I don't know who is responsable for this tool. But it is great. Is it possible to generate a output vector layer (shape) from the  generated output?

---

- [export_selection.jpg](https://issues.qgis.org/attachments/download/8979/export_selection.jpg) (Erik van der Knaap)

**Comment by TriformDaniel** [comment]
Copy of https://github.com/qgis/QGIS/issues/20294 right?

**Comment by alexbruy** [comment]
Duplicates #20294.
