### ISSUE TITLE
Save as Layer

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#21311]
Author Name: **Roberto BobMaX** (Roberto BobMaX)
Original Redmine Issue: [13250](https://issues.qgis.org/issues/13250)

Redmine category:c++_plugins/topology_checker

---
I noticed that the "Topology Checker" C++ plugin  does not permit to save  problematic elements in a layer.

I think this would be a very useful thing.

Thank you

Roberto

**Comment by alexbruy** [comment]
Duplicates #20294.
