### ISSUE TITLE
Available plugin list ordered by date

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#21328]
Author Name: **stefano campus** (@skampus)
Original Redmine Issue: [13267](https://issues.qgis.org/issues/13267)

Redmine category:unknown

---
Given the increasing number of plugins, I think it's useful to be able to have the opportunity to list them in order of date of publication.
You do not always have the time to watch the new plugin list that empties closing QGIS

stefano

**Comment by alexbruy** [comment]
Duplicates #33463.
