### ISSUE TITLE
Relative paths to files and photos

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#21342]
Author Name: **didier peeters** (@dd-a)
Original Redmine Issue: [13283](https://issues.qgis.org/issues/13283)

Redmine category:browser

---
Although there is a setting in the project properties stating that relative paths must be used, it is not possible for photos or files, like in the forms widgets.  
This is not consistent (relative paths can be used for resources like svg's for example) and seems to be a rather common problem in QGis, according to other open tickets.  This is especially a difficulty when sharing a project between several users.

**Comment by davidafuller01** [comment]
+1. This issue makes it impossible to share projects with photos unless you are literally on an old school "LAN shared drive."

**Comment by gioman** [comment]
> +1. This issue makes it impossible to share projects with photos unless you are literally on an old school "LAN shared drive."

@davidafuller01 

![Screenshot_20201002_112351](https://user-images.githubusercontent.com/1951107/94913890-f44f1000-04a1-11eb-916f-1dfc6fd325d1.png)

**Comment by gioman** [comment]
I think this should be closed.

**Comment by davidafuller01** [comment]
@gioman - I have toggled the Attributes Form settings as you've shown above for Photo -> Widget Type = Attachment, but the photo does not display for the Map Tip using a very simple bit of HTML:
`<img src="file:///[% photo %]">`

Does the src syntax need to change?

My test for this is very simple:
- The .qgz file is in a folder at the same level as a folder (with subfolders) containing photos
- Photos display as a Map Tip
- Close the .qgz, I move the folder containing the .qgz and the photo folder / subfolders to another folder
- Reopen the .qgz; Map Tips are now broken

BTW... At the Project level, I do not have a Project home set and have Save paths = relative set.
BTW2... I am on macOS using 3.10.10 and have tested with 3.14.16 with the same result.

**Comment by gioman** [comment]
@davidafuller01 

this ticket is about the form view, not map tips.

For the form view you have to do as I shown up here, moving the project file and the folder containing the photos (keeping the same relative position) is NOT breaking things, at least here on Linux and Windows. I can test also on macOS but really should not make any difference.

For map tips only absolute paths seems to be supported, but you can workaround it with the @project_folder QGIS variable, i.e.

<img src=file://[%  @project_folder  %]/[% "foto" %] width=200px>

Also in this case moving the project file and the photo folder is NOT breaking things here.
