### ISSUE TITLE
Rounded corners on print layout elements 

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#21367]
Author Name: **Jamie Portman** (Jamie Portman)
Original Redmine Issue: [13309](https://issues.qgis.org/issues/13309)

Redmine category:map_composer/printing

---
It would be great to add options for rounded corners on print layout elements other than the shapes - mostly the Legend and Map Frame.
At the moment, if i want a legend with roubded corners, it is required to make the legend have no fill/border and then add a rectangle behind... that is fine for a one off, but if making an Atlas with a legend that changes, the user has to keep resizing the box to match the legend.

**Comment by alexbruy** [comment]
Duplicates #20589.
