### ISSUE TITLE
Toggle feature selected when using Node tool

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#21390]
Author Name: **Jamie Portman** (Jamie Portman)
Original Redmine Issue: [13337](https://issues.qgis.org/issues/13337)

Redmine category:digitising

---
This may not be a feature request (if someone can tell me how to do it).

When you have a polygon layer that has no gaps (is a seamless coverage) it is often hard/impossible to select some features with the node editing tool!
For instance, if one polygon is completely encompassed by another (or multiple) and the surrounding polygons are 'higher' in the table, then it doesn't matter where on the boundary you click, it never ever highlights the one you want.

The only way around it we have found is to move a node on the surrounding layer away... make the necessary changes and then move the first polygon back to where it was originally.
It is just tedious, when all that is required is a hot-key to allow you to toggle through the features until the one you want is selected.

Even having features show by categories doesn't help, as it you toggle a particular group off, the node edit tool will still select them even though you can visually see them.

**Comment by uclaros** [comment]
> I have seen similar feature in Mapinfo. This is a feature request.

I am not aware of the Mapinfo implementation, but the Vertex tool can subsequently select overlapping features by right-clicking inside them.
Should this be closed as implemented?
