### ISSUE TITLE
Option to turn off timed messages in Settings/Options/General

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#21413]
Author Name: **Piotr Kania** (Piotr Kania)
Original Redmine Issue: [13360](https://issues.qgis.org/issues/13360)

Redmine category:map_canvas

---
Hi! 
In "Settings/Options/General/Timeout for timed messages or dialogs" user can't set 0 or 1 value, only 2 or more. I'd like to turn off those messages and I tried to set "0" value - I'm on win7 x64 sp1, qgis dev 2.11.0-67

**Comment by nyalldawson** [comment]
This is a wontfix - those messages are used to show important feedback to users, removing them is not supported
