### ISSUE TITLE
label engine to support shrink to fit label in polygon?

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#21444]
Author Name: **Abdelilah ADIBA** (Abdelilah ADIBA)
Original Redmine Issue: [13392](https://issues.qgis.org/issues/13392)

Redmine category:labelling

---
actual QGIS labelling do not support shrink font size to fit label in polygon, this feature is important to avoid collision in some case, please when this feature could be done ?

**Comment by pjshelton** [comment]
This should also be available for labeling lines.

**Comment by pjshelton** [comment]
#32762 is asking for the same thing

**Comment by gioman** [comment]
Closing as duplicate.
