### ISSUE TITLE
Georeferencer produce images in wrong crs in 2.10 and master

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#21450]
Author Name: **Gerhard Spieles** (Gerhard Spieles)
Original Redmine Issue: [13398](https://issues.qgis.org/issues/13398)
Affected QGIS version: 3.7(master)
Redmine category:c++_plugins/georeferencer

---
in QGIS 2.6.1, georeferencing results (tif-images) are correct produced in the choosen crs.
In 2.10 and master, georeferencing in EPSG 25832 results in a tif georeferenced in crs EPSG 3044.

You have also now two steps to bring QGIS to start georeferencing work. First click on the icon starting the referencing work, results in a popup mask asking for the transformation type, although p.e. "helemert" ist preconfigured. Give all information into the mask, press OK button and nothing happens. Then you have to click the button for starting referencing work again to do the output process. (in 2.6.1, referecing work starts by click on OK in the first mask)

Projects with data in 2.6.1 and 2.11 are attached as zip-archiv

---

- [test.zip](https://issues.qgis.org/attachments/download/9092/test.zip) (Gerhard Spieles)

---

Related issue(s): #25337 (duplicates)
Redmine related issue(s): [17440](https://issues.qgis.org/issues/17440)

---

**Comment by alexbruy** [comment]
Duplicates #28146 and #26695
