### ISSUE TITLE
FreeCAD integration with/within QGIS

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#21623]
Author Name: **MRick -** (MRick -)
Original Redmine Issue: [13581](https://issues.qgis.org/issues/13581)

Redmine category:unknown

---
FreeCAD is Python 2D/3D CAD package with parametric functions.
http://www.freecadweb.org/wiki/?title=About_FreeCAD

It CAD also be used in console mode only and controled by the command line.
http://www.freecadweb.org/wiki/index.php?title=Start_up_and_Configuration

FreeCAD can be run as a simple Python module.

Do you think QGIS could interfer through a plugin and/or scripts to get advanced CAD features from FreeCAD?

FreeCAD could be used for 3D design as well. For example, I want to get a building and then georeference it inside QGIS is the way of SketchUp does.
So FreeCAD could be used to get 3D design inside QGIS.

And maybe it could bring features to create an AutoCAD Map and/or AutoCAD Civil like bundle(s).

Just a set of ideas I wanted to share while I'm using both of them and like both of them.

**Comment by luzpaz** [comment]
Related threads:  
* [Thread tracking FreeCAD & QGIS integration](https://forum.freecadweb.org/viewtopic.php?t=22390)  
* https://www.github.com/joelgraff/freecad.trails
* https://github.com/HakanSeven12/FreeCAD-Geomatics-Workbench
* [Civil engineering feature implementation (Transportation Engineering)](https://forum.freecadweb.org/viewtopic.php?f=8&t=22277) (FC forum thread)

**Comment by alexbruy** [comment]
Please start discussion in the developer mailing list, which is the right place for such things.
