### ISSUE TITLE
Merge connected lines option for Marker line interval

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#21642]
Author Name: **Matt Sim** (Matt Sim)
Original Redmine Issue: [13600](https://issues.qgis.org/issues/13600)

Redmine category:symbology

---
Similar to the label rending option "Merge connected lines to avoid duplicate labels". It would be great if the Marker lines could be merged, allowing the marker placement interval to be consistent across connected features.

**Comment by pjshelton** [comment]
I would like this to also be able to have a second option that allows for considering marker line direction.  Pease see #38205 for the discussion.

**Comment by pjshelton** [comment]
#17943 raises the possibility that some lines would be "connected", for only part of their length.  This request would ideally also have the ability, (option), to match those parts of lines that are the "same" and render that part of those lines as only one line.

**Comment by pjshelton** [comment]
This and #17943 and #27540 are all requesting a general Merge connected objects for symbology.

**Comment by nyalldawson** [comment]
@pjshelton I'd propose a new "merged features" renderer, which acts a little like the existing inverted polygon renderer "merge polygons before rendering" option, but which works for both polygon and line layers (and doesn't invert!).

**Comment by pjshelton** [comment]
@nyalldawson is that as simple as opening a new Feature Request with the title "Merged features" renderer and a summary of what it should and should not be able to do?  (The summary would in part be taken from the three existing requests, and then, close the existing request?)

**Comment by nyalldawson** [comment]
@pjshelton actually i started work on this a few months back already :laughing: see https://github.com/nyalldawson/QGIS/commits/merge_renderer . Hoping to finish it this holiday season...

**Comment by pjshelton** [comment]
@nyalldawson I wait with anticipation to see your new renderer finished.

**Comment by gioman** [comment]
> actually i started work on this a few months back already laughing see https://github.com/nyalldawson/QGIS/commits/merge_renderer .

@nyalldawson this is great!

**Comment by pjshelton** [comment]
#14953  is a special case of #27540.
