### ISSUE TITLE
Provide function to "update Legend" after manually editing style class values

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#21649]
Author Name: **Johannes Kroeger** (Johannes Kroeger)
Original Redmine Issue: [13611](https://issues.qgis.org/issues/13611)

Redmine category:symbology

---
QGIS automatically provides legend texts for graduated style classes if for example the Equal Interval mode is chosen. If a user manually edits the values of class boundaries in the style, the legend value texts become false.

Please provide a way to "update the legend texts according to the class boundaries".

See the attached screenshot as illustration of the problem.

---

- [value_vs_legend_text.png](https://issues.qgis.org/attachments/download/9195/value_vs_legend_text.png) (Johannes Kroeger)

**Comment by kannes** [comment]
Checking again, the legend is not automatically updated for any classification mode if I manually edit the class break values in 3.8.

**Comment by roya0045** [comment]
This seems fixed in 3.12 without auto-update active.

**Comment by kannes** [comment]
Confirming that this works fine (I tested *with* auto-update active).
