### ISSUE TITLE
GRASS plugin shell: please implement Crtl-V Ctrl-C

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#21663]
Author Name: **Paolo Cavallini** (@pcav)
Original Redmine Issue: [13625](https://issues.qgis.org/issues/13625)

Redmine category:grass

---
Currently copy-paste can be done with the middle button. It would be good to also implement the Crtl-V and Ctlr-C method.

**Comment by nyalldawson** [comment]
The grass console was removed and is no longer supported
