### ISSUE TITLE
Templated input parameter

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#21698]
Author Name: **Giovanni Allegri** (@giohappy)
Original Redmine Issue: [13663](https://issues.qgis.org/issues/13663)

Redmine category:processing/core
Assignee: Victor Olaya

---
The cases where a raster calculator or a QGIS expression needs to be used inside e model or a script, it can be useful to let the user configure only some parts of the expression. E.g. in an Extract by Attributes algorithm I could have "MYFIELD = X". It would be great if the two strings "MYFIELD" and "X" could be obtained from inputs and interpolated inside a template string like "{0} = {1}".
There are various way to design such an input parameter type. This is just a feature request. 

(If I will find the time I will try to develop some proposals and maybe submit a PR)

**Comment by alexbruy** [comment]
Should be possible in master.
