### ISSUE TITLE
Integrated Metadata-Editor 

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#21713]
Author Name: **Flo Ju** (Flo Ju)
Original Redmine Issue: [13681](https://issues.qgis.org/issues/13681)

Redmine category:metadata

---
Integrate Metadata-Editor supporting FGDC, ISO19115, ISO19139 (INSPIRE Comp.,...). 
Available PlugIns like MetaTools or QSphere seem to be quite unstable at the moment (not running on different QGIS-installations at the moment). 
Metadata-editing would be a usefull out-of-the-box feature.

**Comment by nyalldawson** [comment]
This is implemented already
