### ISSUE TITLE
Option to save batch processing tasks (Processing Toolbox)

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#21744]
Author Name: **Lars Scharfenberg** (Lars Scharfenberg)
Original Redmine Issue: [13717](https://issues.qgis.org/issues/13717)

Redmine category:unknown

---
An option to save batch processing tasks (created from the Processing toolbox) would be great, or a history for those tasks similar to how it's handled in ArcGIS, especially when you have to enter a large number of filenames/directories and have to repeat the whole process when you mistyped something.

**Comment by alexbruy** [comment]
Already possible in master.
