### ISSUE TITLE
include Python pip in macosx installer

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#21803]
Author Name: **Richard Duivenvoorde** (@rduivenvoorde)
Original Redmine Issue: [13777](https://issues.qgis.org/issues/13777)

Redmine category:build/install
Assignee: William Kyngesburye

---
After discussion in Hackfest Las Palmas about using pip for plugins itself OR plugin dependencies, the plan came up to make it easier for windows/mac users to use pip by adding it in the QGIS installer

combined with maybe showing the dependencies in the plugin metadata, it is a first step to instruct users to install the dependencies via pip.

in future it then is maybe possible to let QGIS/PluginManager all pip install on that dependencies

but first step would be to make pip available to the end user

**Comment by m-kuhn** [comment]
@PeterPetrik is this issue still valid?

**Comment by PeterPetrik** [comment]
nope
