### ISSUE TITLE
keep invalid layers

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#21800]
Author Name: **Gavin Fleming** (@gubuntu)
Original Redmine Issue: [13774](https://issues.qgis.org/issues/13774)

Redmine category:unknown

---
If I can't load a layer on opening a project, for example if a database is unavailable, I would like the layer to remain in the project (or at least have the option to keep it or lose it), even if it's temporarily unusable. Then, the next time I open the project and the data source is available, the layer is there and I haven't lost any properties.

**Comment by GISsymbology** [comment]
The feature is present starting from QGIS 3.6
