### ISSUE TITLE
Include the closed source ESRI FileGeoDB library in standalone installer

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#21812]
Author Name: **Corey Burger** (@CoreyBurger)
Original Redmine Issue: [13786](https://issues.qgis.org/issues/13786)

Redmine category:data_provider/ogr

---
The default QGIS install (2.12) doesn't include R/W access to ESRI FileGBs (it used to and it go dropped about 2.8). Given the popularity of Arc* products, shipping this should be part of the basic functionality of QGIS.

Here is a great example of another user frustrated with the same issue:
http://gis.stackexchange.com/questions/167939/need-file-geodatabase-gdb-read-write-support-in-qgis

**Comment by agiudiceandrea** [comment]
@Pedro-Murteira it seems to me this is fixed since long time with the OSGeo4W Standalone Installers.
