### ISSUE TITLE
Tool to create dynamic leader lines

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#21845]
Author Name: **Paul Kanelli** (Paul Kanelli)
Original Redmine Issue: [13820](https://issues.qgis.org/issues/13820)

Redmine category:labelling

---
A tool to create dynamic leader lines might be helpful for some users.

http://gis.stackexchange.com/questions/153894/how-to-create-dynamic-leader-lines

---

- [label_connectors.jpg](https://issues.qgis.org/attachments/download/9321/label_connectors.jpg) (Paul Kanelli)

**Comment by alexbruy** [comment]
Looks very similar to label callouts. Closing?

**Comment by nyalldawson** [comment]
This is implemented
