### ISSUE TITLE
Labelling - place label horizontally outside the polygon

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#21858]
Author Name: **Darek Bobak** (Darek Bobak)
Original Redmine Issue: [13834](https://issues.qgis.org/issues/13834)

Redmine category:labelling

---
I'm working in archaeology. And I often have to label polygon layer which has polygons not connected to each other. The best way to label it would be to place labels horizontally, just by the edge of the polygon but OUTSIDE of the polygon. I'm attaching the sample from other software.

---

- [labelling.png](https://issues.qgis.org/attachments/download/9317/labelling.png) (Darek Bobak)

**Comment by basilrabi** [comment]
@gioman , I suggest to close this issue since #36106 seems to address this.
