### ISSUE TITLE
Export GeoTIFFs instead of TIFFs

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#21916]
Author Name: **Arun Ganesh** (Arun Ganesh)
Original Redmine Issue: [13894](https://issues.qgis.org/issues/13894)

Redmine category:map_composer/printing

---
I exported a TIFF from the composer later found out I cant import it back into Qgis as it is not a GeoTIFF. Also Qgis does not read the world file which 

The default output should just be a GeoTIFF for ease of use.

**Comment by roya0045** [comment]
Georeferenced tiff can be exported. I guess this can be closed.
