### ISSUE TITLE
"Add Circular String" is not deactivatable by Settings > Customization

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#21923]
Author Name: **Thomas Nogatz** (@TomNog)
Original Redmine Issue: [13901](https://issues.qgis.org/issues/13901)

Redmine category:customisation_framework

---
A possibility to deactivate the "Add Circular String" Button would be fine. Cannot find it in Settings > Customization > Toolbars > mDigitizeToolBar.

**Comment by DelazJ** [comment]
While looking into this issue, I realized that the kind of actions that are not shown in the ToolBars section are of [QWidgetAction](https://doc.qt.io/qt-5/qwidgetaction.html) type (see `action->metaObject()->className()` appended to action label in following screenshot ) - Also some actions/widgets(?) are missing an objectName.
![image](https://user-images.githubusercontent.com/7983394/62850698-f2e1e780-bce3-11e9-9bb1-f3626cbb92c3.png)
After I spent a lot of (actually too much) time with my no-skills c++ trying to figure out how I could get the actions related to these widgets and loop over them, I'd better share this finding and focus on something else :disappointed: 
Hope that helps.
