### ISSUE TITLE
Extract Nodes tool - Add option to specify which points

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#21961]
Author Name: **Dominik Schmid** (@Doemelti)
Original Redmine Issue: [13946](https://issues.qgis.org/issues/13946)

Redmine category:unknown

---
The _Extract Nodes_ tool is quite useful in its current state, nonetheless would gain a lot if it were extended to include an option to specify which points (ALL, START, END, MID, BOTH ENDS) should be extracted.

**Comment by alexbruy** [comment]
Does "Extract specific vertices" from Processing fills your needs?

**Comment by Doemelti** [comment]
I think so. MID needs some extra work, but the others can be easily extracted that way. Thanks for the hint!
