### ISSUE TITLE
Install / Build / Setup

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#22003]
Author Name: **Dietmar Berthold** (Dietmar Berthold)
Original Redmine Issue: [13989](https://issues.qgis.org/issues/13989)

Redmine category:build/install

---
Installing QGIS (under Windows OS) is very very time-consuming because of the huge amount of small files to be unpacked/copied. Each installation is a full installation. There is a need for a customizable setup. Not each user needs a full QGIS for his work, some users only want to open existing QGIS projects and simply navigate in the map. For these users it is not necessary to install all of the complex functionality, tools, button bars, extensions etc. This way, one could reduce the time needed for the setup and the GUI will become more clear (customizing the GUI after installation can be omitted).

**Comment by alexbruy** [comment]
As Jürgen said you can use OSGeo4W installer. Also you can create profiles and share them via network.
