### ISSUE TITLE
DB Manager: commit on versioned layers fails

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#22026]
Author Name: **Paolo Cavallini** (@pcav)
Original Redmine Issue: [14013](https://issues.qgis.org/issues/14013)
Affected QGIS version: 3.0.0
Redmine category:db_manager

---
Currently the commit to the DB fails for versioned layers, because the original ID (which is not NULLable) is not filled (it must be done by hand, which is not nice). Presumably a function to copy the ID from the original one (for updates), or adding a new one in case of inserts, should be added.

**Comment by alexbruy** [comment]
Can we close this? Seems was fixed month ago.
