### ISSUE TITLE
DB Manager: 'Import vector layer' dialoge should remain open after importing a layer/file

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#22111]
Author Name: **Paul Kanelli** (Paul Kanelli)
Original Redmine Issue: [14105](https://issues.qgis.org/issues/14105)

Redmine category:unknown

---
When creating a new table in the DB Manager the 'Create Table' dialogue remains open. That's a very useful feature when creating more than one table. But after importing a layer/file in the DB Manager the 'Import vector layer' dialogue is closed and all options got lost. So importing more than one layer/file isn't that user-friendly.

**Comment by alexbruy** [comment]
Already fixed.
