### ISSUE TITLE
Implement Better Filtering for WFS layers

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#22122]
Author Name: **Jeremy Palmer** (@palmerj)
Original Redmine Issue: [14120](https://issues.qgis.org/issues/14120)

Redmine category:web_services_clients/wfs

---
It would be good to completely re-implement the current WFS client filtering logic to something similar to what the OGR WFS driver does. Currently WFS filters are created using the QGIS expression builder, which then transforms the filter to OGC XML during the layer setup. This current approach which has a couple of issues:

* translating the expression to OGC XML often fails as many QGIS expression functions can not be translated to OGC equivalents. This is not clear to the user
* once the layer is created you can't go back and change the filter.

IMHO it would be easier to set a provider filter using query builder using SQL and then transform that SQL to OGC XML, much like what GDAL/OGR does - see http://www.gdal.org/drv_wfs.html. This would also be a better option if a WFS 2.0 client was implemented in the case of join syntax.

**Comment by pathmapper** [comment]
> IMHO it would be easier to set a provider filter using query builder using SQL and then transform that SQL to OGC XML

Looks like this is now the case since https://github.com/qgis/QGIS/pull/40071, see also https://github.com/qgis/QGIS/issues/42800.
