### ISSUE TITLE
<se:ElseFilter/> nor working when styling data with sld

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#22172]
Author Name: **Radek Zdansky** (Radek Zdansky)
Original Redmine Issue: [14170](https://issues.qgis.org/issues/14170)
Affected QGIS version: 3.2
Redmine category:symbology

---
As is stated in the description, <se:ElseFilter/> is not working properly when styling data with sld (tested in 2.8.3 and 2.12.3)

QGIS just styles data as though there was no ElseFilter, so if I want to use a default style that should be used on all objects that have met no filter in sld file, QGIS styles all the data regardless with that default style in addition to any rules that have been met - therefore rendering them twice. This is a problem when rendering icons especially, because they overlap, which is not very visually appealing.

I have attached two images to let you see what I mean.

QGIS:

![image](http://i.imgur.com/kqYkc0K.png)

GeoServer, using the same sld:
![image](http://i.imgur.com/ATqW7q6.png)

I have attached my shp and sld in a rar, so it could be tested more.

---

- [dopravni_znacky.rar](https://issues.qgis.org/attachments/download/9506/dopravni_znacky.rar) (Radek Zdansky)
- [Screenshot_20171016_113426.png](https://issues.qgis.org/attachments/download/11550/Screenshot_20171016_113426.png) (Giovanni Manghi)

---

Related issue(s): #23356 (duplicates)
Redmine related issue(s): [15430](https://issues.qgis.org/issues/15430)

---

**Comment by Pedro-Murteira** [comment]
Still valid on QGIS 3.22.4 and 3.24.0.
