### ISSUE TITLE
Options for new raster layer 

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#22202]
Author Name: **Anatoliy Dunaev** (Anatoliy Dunaev)
Original Redmine Issue: [14200](https://issues.qgis.org/issues/14200)

Redmine category:rasters

---
Hello!
Very often when I create a new raster layer it is created as single band grey with linear interpolation by default. However It will be very useful if user can change the default styles of new raster layers.

**Comment by alexbruy** [comment]
You can assign default style for layers in the project properties.
