### ISSUE TITLE
Manual labeling: reset position and orientation to NULL

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#22357]
Author Name: **Denis Rouzaud** (@3nids)
Original Redmine Issue: [14375](https://issues.qgis.org/issues/14375)

Redmine category:labelling
Assignee: Martin Dobias

---
It would be nice to be able to reset position and orientation of labels using map tools.
The idea would be similar to the show/hide label map tool:

click on the label to move/rotate it
shift+click on the feature to reset position/orientation

**Comment by patogit** [comment]
@3nids How was this implemented? In QGIS 3.28 I activate the "move label" tool, then I move a label, then I shift click the label, but it does not reset to NULL.

**Comment by 3nids** [comment]
I don't think this what ever implemented.

**Comment by patogit** [comment]
So, how can we reopen this issue? Maybe I'm missing something. Please tell me if I'm wrong: right now, in QGIS 3.28.x, and all previous versions, manually moving a label is a one-way action. In other words, once I move a label, there is no way to return the label to automatic positioning? Never? I would greatly benefit from a simple button or shift-click to remove manual positioning from a label, and return it to automatic positioning.

**Comment by nicogodet** [comment]
It would be a nice feature to have indeed !

**Comment by nyalldawson** [comment]
You should be using the existing "pin/unpin labels" tool for this, which allows removing the fixed manual positions of labels by shift-dragging over them.

Alternatively if you use the move label tool, pickup a label, and then press "delete" then the pinned location will be removed.

**Comment by patogit** [comment]
Ok, thank you very much for the explanation! Thanks to your comment, now I know what to look for, and I found the documentation: https://docs.qgis.org/3.28/en/docs/user_manual/working_with_vector/vector_properties.html?highlight=unpin#the-label-toolbar .
