### ISSUE TITLE
Add a (un)check all option in Project Properties --> Identify layers

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#22404]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [14424](https://issues.qgis.org/issues/14424)

Redmine category:unknown

---
In Project properties, any layer added to the project is by default set to identifiable. It may be nice to have the ability to check or uncheck all at once.

**Comment by alexbruy** [comment]
Duplicates #22405.
