### ISSUE TITLE
Add tools to organize/tag plugins

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#22416]
Author Name: **Andrew McAninch** (@spaceof7)
Original Redmine Issue: [14437](https://issues.qgis.org/issues/14437)

Redmine category:unknown

---
With the hundreds of plugins available I think adding some tools to manage plugins would be really useful.  There are a good number of plugins that are regional or are not at all relevant to the sort of work I do in a GIS and being able to tag these as hidden would be helpful for reducing the number of plugins I need to sort through when I'm searching for a tool.  I also will see new plugins that I don't have an immediate use for but I know will be useful in the future, and Id like a way to be able to tag these too.  I suppose I'm looking for the ability to manage/view different lists/sets of plugins.

**Comment by skampus** [comment]
I think it is enough to have the possibility of ordering the plugins by date of publication or update
