### ISSUE TITLE
Attribute table icons too small on HiDPI

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#22450]
Author Name: **Anita Graser** (@anitagraser)
Original Redmine Issue: [14472](https://issues.qgis.org/issues/14472)
Affected QGIS version: 3.3(master)
Redmine category:gui

---
The icons in the attribute table toolbar are considerably smaller than the main window toolbar icons. 

Also, the switch to form view icon is smaller than the neighboring table view icon.

![attributetable.png](https://issues.qgis.org/attachments/download/9694/attributetable.png)

---

- [attributetable.png](https://issues.qgis.org/attachments/download/9694/attributetable.png) (Anita Graser)

---

Related issue(s): #19434 (relates)
Redmine related issue(s): [11103](https://issues.qgis.org/issues/11103)

---

**Comment by nyalldawson** [comment]
Not an issue on current versions
