### ISSUE TITLE
Using the SAGA dissolve tool from within QGIS: specify summary statistics

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#22484]
Author Name: **Mattias Lindman** (Mattias Lindman)
Original Redmine Issue: [14511](https://issues.qgis.org/issues/14511)

Redmine category:processing/saga

---
When using the SAGA dissolve tool from within the SAGA software it is possible to specify the summary statistics to be calculated on the dissolved polygons. When using the SAGA dissolve tool through the SAGA toolbox in QGIS it is however only possible to specify the attributes on which the polygons shall be dissolved.

By browsing the submitted issues on dissolve I sense that it is recommended to use the SAGA dissolve tool rather than the tool implemented in QGIS. As the SAGA dissolve tool provides summary statistics I consider that it would be convenient if this functionality was available from within QGIS.

**Comment by alexbruy** [comment]
SAGA Provider was not maintained and now remowed from QGIS (see #50834). Users are encouraged to use the 3rd-party plugins instead.
