### ISSUE TITLE
Attach comments to a component in model builder

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#22491]
Author Name: **Magnus Nilsson** (Magnus Nilsson)
Original Redmine Issue: [14518](https://issues.qgis.org/issues/14518)

Redmine category:processing/modeller
Assignee: Victor Olaya

---
Hi
I would like to see support for adding/attaching comments to any component. That would, for example, help explaining why a specific tool is used. It should be possible to move and resize it. Great for documentation purposes. I have attached a not so nice sketch of how I see it.

---

- [Comment.JPG](https://issues.qgis.org/attachments/download/9725/Comment.JPG) (Magnus Nilsson)

**Comment by nyalldawson** [comment]
Implemented in 3.14
