### ISSUE TITLE
Atlas only displaying 499 Feature in Drop Down

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#22566]
Author Name: **Steven Oliver** (Steven Oliver)
Original Redmine Issue: [14598](https://issues.qgis.org/issues/14598)

Redmine category:map_composer/printing

---
In Atlas Mode, The dropdown menu only displays 499 features.  You can use the arrows to move to the next feature, so I am pretty sure that the data is there, but the setting for the drop down was set to 499.  Would like to know if their was a way to change that setting locally, or would it have to be coded.  Desired length could be 100,000 since I deal with land parcels. !attached_image!

---

- [qgiserror.jpg](https://issues.qgis.org/attachments/download/9784/qgiserror.jpg) (Steven Oliver)

**Comment by nyalldawson** [comment]
Fixed in recent versions
