### ISSUE TITLE
Add a "comment" field in DB Manager (postgis) import

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#22607]
Author Name: **didier peeters** (@dd-a)
Original Redmine Issue: [14643](https://issues.qgis.org/issues/14643)

Redmine category:db_manager

---
I wish there was a "Comment" field in the import interface of the DB Manager, at least for PostGIS (I don't know about the other DB connections).  
Currently existing comments on a table stored in PostGIS are displayed in the General Information in the Info tab, which is good and usefull, but there seems to be no possibility to add some (or update !) directly from QGis.

**Comment by alexbruy** [comment]
Already implemented in master
