### ISSUE TITLE
Rearrange icons in advanced digitizing toolbar

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#22706]
Author Name: **Reinhard Reiterer** (Reinhard Reiterer)
Original Redmine Issue: [14749](https://issues.qgis.org/issues/14749)

Redmine category:gui

---
Grouping the ring/multigeometry tool icons may help to make the advanced digitizing toolbar more user-friendly.

---

- [advanced_digitizing_toolbar.png](https://issues.qgis.org/attachments/download/9867/advanced_digitizing_toolbar.png) (Reinhard Reiterer)

**Comment by alexbruy** [comment]
These icons grouped by their purpose not geometry type, e.g. first tools which create new feature/part, then tools to remove feature/part etc.
