### ISSUE TITLE
Filtering in QGIS browser only returns result in already opened folders or databases

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#22726]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [14769](https://issues.qgis.org/issues/14769)
Affected QGIS version: 3.0.0
Redmine category:browser

---
Open a new instance of QGIS and open the browser panel if not already done
Click on the filter button and make a search for a file/table/folder you know that exists. QGIS will only returns drives/DB that have such "search text" in their name.
Let's clear the search text and now extend one of the listed drives/DB. If you make a new search, content of this drive is now taken into account, but not its subfolders.
....and so on...

If I need to open the right folder to be able to have my file returned by the search, better open it directly. This makes the search tool useless so I set the priority level at blocker.

**Comment by gioman** [comment]
@DelazJ seems fixed to me.

**Comment by gioman** [comment]
Closing for lack of further feedback.
