### ISSUE TITLE
Default WMS servers wrong

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#22754]
Author Name: **Paolo Cavallini** (@pcav)
Original Redmine Issue: [14797](https://issues.qgis.org/issues/14797)
Affected QGIS version: 3.0.0
Redmine category:web_services_clients/wms

---
The button Add default WMS servers in he Add WMS dialog add two entries:
* http://wms.lizardtech.com/lizardtech/iserv/ows
* http://www2.dmsolutions.ca/cgi-bin/mswms_gmap
Both of which throw an error:

* Error downloading http://wms.lizardtech.com/lizardtech/iserv/ows?SERVICE=WMS&REQUEST=GetCapabilities - server replied: Bad Request
* Host www2.dmsolutions.ca not found

Please remove them, better to add working ones (check e.g. MetaSearch plugin for a list), best if the two lists (WMS and Mettasearch, possibly also WFS) would be integrated.

**Comment by alexbruy** [comment]
Closing as original issue was fixed and there is #29873 to remove this button completely.
