### ISSUE TITLE
Improve new color ramp creation

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#22818]
Author Name: **Paolo Cavallini** (@pcav)
Original Redmine Issue: [14865](https://issues.qgis.org/issues/14865)

Redmine category:gui

---
I think we could improve the UX for creating new colour ramps by:

* setting the default to cpt-city instead of the gradient
* renaming cpt-city (it is nice to pay tribute to the original creator of the set, but the name is not understandable for users)
* possibly removing other options (I think they are all included in cpt-city, e.g. ColorBrewer).

**Comment by nyalldawson** [comment]
Let's close this one -- it would be better to make separate issues for each individual request.
