### ISSUE TITLE
[GPS Information Panel] Add vertex symbols in rubberband when we collect a polygon

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#22871]
Author Name: **João Gaspar** (@jonnyforestGIS)
Original Redmine Issue: [14920](https://issues.qgis.org/issues/14920)

Redmine category:c++_plugins/gps_plugin

---
Is difficult understand when we work in the field with Tablet PC to see the first collected point of the polygon. Sometimes the result we add more than one vertex and we only see this behavior when we add the polygon.

**Comment by nyalldawson** [comment]
This is possible now -- the track can be set to any QGIS symbol, so you can add vertex markers and any other symbol styling in there
