### ISSUE TITLE
Customization: the widget catcher can't select icon from a toolbar when it's under a group of icons

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#22967]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [15020](https://issues.qgis.org/issues/15020)
Affected QGIS version: 3.0.0
Redmine category:customisation_framework

---
E.g., with the widget catcher, you can't graphically select "select features" tools from the Attribute toolbar given that these tools are grouped together

**Comment by PeterPetrik** [comment]
cc @DelazJ
