### ISSUE TITLE
Customization: add a search box to easily find widgets

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#22970]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [15023](https://issues.qgis.org/issues/15023)

Redmine category:customisation_framework

---
Considering the amount of widgets, it can be handy to have a search box in the Customization panel to easily find items you are looking for.

**Comment by DelazJ** [comment]
Fixed in #30956. To close.
