### ISSUE TITLE
Manage Layers Toolbar - Add GeoPackage Layer

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#23012]
Author Name: **Reinhard Reiterer** (Reinhard Reiterer)
Original Redmine Issue: [15069](https://issues.qgis.org/issues/15069)

Redmine category:browser

---
Pleas implement a button/dialog in the 'Manage Layers Toolbar' to add a GeoPackage layer.

---

- [add_geopackage_layer.png](https://issues.qgis.org/attachments/download/10035/add_geopackage_layer.png) (Reinhard Reiterer)

**Comment by alexbruy** [comment]
Closing as we now have everything in the Datasource Manager and Manager layers toolbar most likely will gone in next major release.

**Comment by m-kuhn** [comment]
> Closing as we now have everything in the Datasource Manager and Manager layers toolbar most likely will gone in next major release.

Did I miss something?

**Comment by alexbruy** [comment]
Well, maybe I'm wrong, but I remember discussion about it. And now it is hidden by default.

**Comment by m-kuhn** [comment]
Yes, I also remember that there was a discussion about it. I was not sure about the outcome.
For me the gpkg button has no priority (I can very well live with drag and drop from file browser / QGIS browser / db manager / ds manager for this purpose), so I don't mind this issue being closed.

Does someone know where the discussion wrt dropping the toolbar was?
What are others opinions? @gioman @haubourg @elpaso @timlinux
