### ISSUE TITLE
No rubberband when switching from "Add circular string" (and by radius) to "Add feature" tool

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#23011]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [15068](https://issues.qgis.org/issues/15068)
Affected QGIS version: 3.0.0
Redmine category:digitising

---
While digitizing line or polygon feature, you can switch between the simple "Add feature" and "Add circular string" tools.
When switching from "Add feature" to "Add circular string", the rubberband is active and help to follow the geometry being drawn.
But when switching from "Add circular string" (or by radius) to "Add feature" tool, no rubberband is displayed and the user can think that something is going wrong with the digitizing process.

---

Related issue(s): #26143 (relates)
Redmine related issue(s): [18252](https://issues.qgis.org/issues/18252)

---

**Comment by roya0045** [comment]
From what I see the switch is still wonky, now when switching from circle to feature the first point of the circle is not used as the first point of the feature but instead the top of the circle becomes the initial point of the feature.

**Comment by Pedro-Murteira** [comment]
> From what I see the switch is still wonky, now when switching from circle to feature the first point of the circle is not used as the first point of the feature but instead the top of the circle becomes the initial point of the feature

I can confirm this is still happening using QGIS 3.22.2.

**Comment by uclaros** [comment]
This should be fixed after #46687, can you still replicate in master?
