### ISSUE TITLE
"Pretty Break" for raster styling

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#23050]
Author Name: **Kyle Somerville** (Kyle Somerville)
Original Redmine Issue: [15108](https://issues.qgis.org/issues/15108)

Redmine category:unknown

---
It would be useful to have a "pretty break" option (identical to that available for vector styling) when styling rasters with color maps, as a quick solution to manually setting minima and maxima and using equal interval banding.

**Comment by alexbruy** [comment]
Duplicates #18582.
