### ISSUE TITLE
Digitizing: Reshape tool doesn't take into account selection

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#23088]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [15149](https://issues.qgis.org/issues/15149)
Affected QGIS version: 3.0.0
Redmine category:digitising

---
Unlike many tools of the Advanced Digitizing tool, The "reshape tool" doesn't consider selection when reshaping. It reshapes all overlaping features, selected or not.

**Comment by olivierdalang** [comment]
Shouldn't we consider this as a serious issue ? (data corruption)

It's very easy (just happened to me) to destroy geometries as you don't see the damage if you have an opaque style.

**Comment by gioman** [comment]
> Shouldn't we consider this as a serious issue ? (data corruption)

I agree.
