### ISSUE TITLE
Mention how to sign up to this system right there on the login page

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#23104]
Author Name: **Dan Jacobson** (@jidanni)
Original Redmine Issue: [15165](https://issues.qgis.org/issues/15165)

Redmine category:unknown

---
User lands at this bug tracker.
User sees "sign in" in top right corner.
User clicks it.
User might not already have an account.
User finds no information on how to establish an account.

**Comment by alexbruy** [comment]
Closing as bugtracker now at GitHub and there is a clear "Sign Up" link.
