### ISSUE TITLE
Digitizing: "Add Ring" tool doesn't consider all the overlapping features

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#23113]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [15174](https://issues.qgis.org/issues/15174)
Affected QGIS version: 3.0.0
Redmine category:digitising

---
Open a layer, toggle to edition and add two polygon features that overlap.
select the "Add ring" tool and add a ring where the two features overlap.
Only the first feature contains a hole, not the second one.
If the features are selected beforehand, only the first feature is again pierced, ignoring the selection of the second feature.

I think in both case, both features should contain holes.( The Split features would have split both features - selected or not)

---

Related issue(s): #23114 (relates)
Redmine related issue(s): [15175](https://issues.qgis.org/issues/15175)

---

**Comment by Pedro-Murteira** [comment]
This bug no longer occurs on versions 3.16.14 and 3.22.1. (Tested on both Linux UBUNTU 20.04 and windows 10).

**Comment by DelazJ** [comment]
Tested on 3.22.1 Ubuntu 20.04 and still occurs (only a single polygon is pierced while both should (in both cases: selected or not)

https://user-images.githubusercontent.com/7983394/145734735-5f39c7ea-0b19-44df-8186-ecb4bc760059.mp4

**Comment by lbartoletti** [comment]
Today, you can only add a ring on the current layer.

I guess, one wants to add a ring also on selected features for the other layers. I'll try to rewrite it like this.
