### ISSUE TITLE
Add a list of vector formats and QGIS capabilities regarding them

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#23126]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [15187](https://issues.qgis.org/issues/15187)

Redmine category:unknown

---
In Settings --> Options --> GDAL are listed all raster formats QGIS can read and/or write.
It might be nice to have such list for vectors too (will help to acknowledge people that shapefile is not the single format they can work with).

**Comment by DelazJ** [comment]
A duplicate of #18738
