### ISSUE TITLE
SQLite: All attributes are displayed as NULL in attribute panel

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#23205]
Author Name: **Casper Børgesen** (Casper Børgesen)
Original Redmine Issue: [15269](https://issues.qgis.org/issues/15269)
Affected QGIS version: master
Redmine category:unknown

---
I have a case with a SQLite dataset containing two layers. A line layer and a polygon layer. Both layers have attributes with values. I have opened both layers in QGIS.

- When performing a _identify features_ on features in the two layers the result looks fine. 
- When opening the _Attribute Panel_ on either of the layers all values are @NULL@.

I would expect the _Attribute Panel_ to display the correct attribute values of all the features and not just a collection of @NULL@'s.

I produced this in MASTER (3d72837) using the attached SQLite test dataset. I have also reproduced this in 2.14.1.

---

- [Areas.sqlite](https://issues.qgis.org/attachments/download/10191/Areas.sqlite) (Casper Børgesen)

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
