### ISSUE TITLE
Enable compression by default for GeoTIFFs

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#23221]
Author Name: **belg4mit -** (belg4mit -)
Original Redmine Issue: [15286](https://issues.qgis.org/issues/15286)

Redmine category:rasters

---
Add -co COMPRESS=DEFLATE flag when generating GeoTIFFs e.g; Rasterize; to greatly reduce demand on user disks.

**Comment by alexbruy** [comment]
There is an option to choose desired compression profile in GDAL algorithms.
