### ISSUE TITLE
photos don't reduce or scale down when resizing the attribute table form view

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#23223]
Author Name: **Donovan Cameron** (@saultdon)
Original Redmine Issue: [15289](https://issues.qgis.org/issues/15289)
Affected QGIS version: 2.16.0
Redmine category:forms

---
I've set up some point files with a FullPath field, which points to the full path of a photo as a photo widget and set to "auto" for the width and height.

Opening the attribute table it looks ok (picture 01), then when I make the attribute table window larger the image gets larger appropriately (picture 02).

But when I then make the attribute table window smaller or back to it's original size the photo does not scale down accordingly (picture 03).

---

- [01_-_Resize_based_on_auto_setting.png](https://issues.qgis.org/attachments/download/10205/01_-_Resize_based_on_auto_setting.png) (Donovan Cameron)
- [02_-_resized_larger_when_stretching_attribute_table_in_form_view_larger.png](https://issues.qgis.org/attachments/download/10206/02_-_resized_larger_when_stretching_attribute_table_in_form_view_larger.png) (Donovan Cameron)
- [03_-_resize_not_scaling_back_down_when_attribute_table_windows_is_made_smaller.png](https://issues.qgis.org/attachments/download/10207/03_-_resize_not_scaling_back_down_when_attribute_table_windows_is_made_smaller.png) (Donovan Cameron)

**Comment by pascatl** [comment]
I've got the same issue with QGIS 3.4(LTR)
