### ISSUE TITLE
Switching to Singleband gray does not fill Min/Max

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#23240]
Author Name: **Johannes Kroeger** (Johannes Kroeger)
Original Redmine Issue: [15308](https://issues.qgis.org/issues/15308)
Affected QGIS version: master
Redmine category:unknown

---
If you use a raster image and switch to "Singleband gray" in the Layer Styling panel it will not automatically load the Min/Max.

If you do the same in the Style properties dialog you automatically get "0" for both (which is an error).

The pseudocolor options automatically load values for me, please do the same for gray.

I would also suggest automatically applying "Stretch to MinMax" Contrast enhancement as user friendly default.

I am on 7343b36, Linux.

**Comment by kannes** [comment]
Can't reproduce it in 3.8, please close.
