### ISSUE TITLE
(Shape file) Layer extent not updated on project load

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#23268]
Author Name: **Casper Børgesen** (Casper Børgesen)
Original Redmine Issue: [15336](https://issues.qgis.org/issues/15336)
Affected QGIS version: master
Redmine category:unknown

---
I have a QGIS project file with shape file layer A.

Shape file layer A contains one feature. I have another shape file B, which is not loaded into the QGIS project, and it contains one feature which is at a different location than the feature in layer A.

If I close the QGIS project, switch the names of the two Shape files and open the QGIS project, the zoom-to-extent moves the map to the location of the feature in layer A, but this time its actually layer B, which is loaded in QGIS.

Thus the extent of shape file layers in QGIS projects are NOT updated upon loading. Looking at the metadata pane under the layers properties, confirms the wrong extent.

Is this the expected behavior?

---

- [data_A.dbf](https://issues.qgis.org/attachments/download/10234/data_A.dbf) (Casper Børgesen)
- [data_A.prj](https://issues.qgis.org/attachments/download/10235/data_A.prj) (Casper Børgesen)
- [data_A.shp](https://issues.qgis.org/attachments/download/10236/data_A.shp) (Casper Børgesen)
- [data_A.shx](https://issues.qgis.org/attachments/download/10237/data_A.shx) (Casper Børgesen)
- [data_B.dbf](https://issues.qgis.org/attachments/download/10238/data_B.dbf) (Casper Børgesen)
- [data_B.prj](https://issues.qgis.org/attachments/download/10239/data_B.prj) (Casper Børgesen)
- [data_B.shp](https://issues.qgis.org/attachments/download/10240/data_B.shp) (Casper Børgesen)
- [data_B.shx](https://issues.qgis.org/attachments/download/10241/data_B.shx) (Casper Børgesen)
- [project.qgs](https://issues.qgis.org/attachments/download/10242/project.qgs) (Casper Børgesen)

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
