### ISSUE TITLE
LTR should prompt to upgrade to new LTR version, not to new QGIS non-LTR version

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#23318]
Author Name: **Steve Lowman** (Steve Lowman)
Original Redmine Issue: [15388](https://issues.qgis.org/issues/15388)

Redmine category:unknown

---
On opening the 2.14 LTR application, a message displayed for a short time near the bottom of the screen prompts users to upgrade to 2.16, but there is no prompt to upgrade to the latest LTR version.

Assuming that most LTR users wish to stay with the LTR for its full duration, would it be better for the LTR instead to prompt to upgrade to the latest 2.14 LTR version, not to 2.16?

---

Related issue(s): #24053 (duplicates)
Redmine related issue(s): [16141](https://issues.qgis.org/issues/16141)

---

**Comment by m-kuhn** [comment]
Duplicate of #21240
