### ISSUE TITLE
Unused mouse clicks could toggle layer on and off when panning

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#23314]
Author Name: **Dan Jacobson** (@jidanni)
Original Redmine Issue: [15384](https://issues.qgis.org/issues/15384)

Redmine category:actions

---
With Pan Map activated, (hand shaped cursor),
the user wishes to
pan the map,
toggle top layer off,
pan the map,
toggle top layer back on,
...

Currently he must
move the mouse off the map, to Layers panel, center the mouse upon the layer's
checkbox and click for each toggle.

It would be more helpful to allow the right click, or any other unused
mouse action, to do this. Hopefully immediately without going into menus
either.

That you might want to put more choices on the right click than just
"wasting it" for only "toggle layer on/off", could be configurable.

**Comment by AlisterH** [comment]
I think I saw a plugin that implemented Regis' suggestion.
And I'd suggest closing this ticket as "wontfix", anyway.

**Comment by haubourg** [comment]
thanks @AlisterH for the cleanup ! I closed it
