### ISSUE TITLE
Difficulty editing table fields - previous text underlaid

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#23393]
Author Name: **Patrick Dunford** (@enzedrailmaps)
Original Redmine Issue: [15467](https://issues.qgis.org/issues/15467)
Affected QGIS version: master
Redmine category:unknown

---
When overwriting text in existing field the text is still displayed at the same time as what you are typing. See attached photo.

The white text is the original text in the field and the black text is what you are typing.

786a59c

---

- [20160820_081754.jpg](https://issues.qgis.org/attachments/download/10330/20160820_081754.jpg) (Patrick Dunford)

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
