### ISSUE TITLE
SVG symbol export adds invalid stroke parameters

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#23405]
Author Name: **Andrea Aime** (@aaime)
Original Redmine Issue: [15481](https://issues.qgis.org/issues/15481)
Affected QGIS version: master
Redmine category:unknown

---
Exporting a SVG based symbol results in invalid SLD, as follow:

```
         <se:PolygonSymbolizer>
            <se:Fill>
              <se:GraphicFill>
                <se:Graphic>
                  <se:ExternalGraphic>
                    <se:OnlineResource xlink:type="simple" xlink:href="transport/amenity=airport.svg"/>
                    <se:Format>image/svg+xml</se:Format>
                  </se:ExternalGraphic>
                  <se:Size>71</se:Size>
                  <se:SvgParameter name="stroke">#000000</se:SvgParameter>
                  <se:SvgParameter name="stroke-width">4</se:SvgParameter>
                </se:Graphic>
              </se:GraphicFill>
            </se:Fill>
          </se:PolygonSymbolizer>

```

The SvgParameters are not part of the Graphic nor ExternalGraphic, it's simply not possible to setup a stroke color for SVGs in SE, at most one can apply a color replacement (which could be used for the fill)

**Comment by alexbruy** [comment]
Seems fixed in master. SVGs exported to SLD as parametric SVG, then as plain SVG without parameters and finally as well-known marker with the right colors.
