### ISSUE TITLE
Impossible to unset map tips on a layer

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#23400]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [15474](https://issues.qgis.org/issues/15474)
Affected QGIS version: 3.0.0
Redmine category:map_tools

---
In vector layer properties > Display, once you chose a field to use for map tip and apply, there seems to not be a way to deactivate it, except turning off the map tip tool itself. This solution is not the best one given that you can have many layers for which you have activated the map tip and just want to remove one of them.

**Comment by alexbruy** [comment]
Actually you can delete any text (including field name) in the expression field at the bottom of the dialog and no map tips will be shown for the layer. Closing?

**Comment by DelazJ** [comment]
Sorry, I'm unable to delete the field (it's reset -alphabetically?- anytime I click elsewhere) and I have nothing in the expression field at the bottom of the dialog, unless i misunderstand
![displayMapTip](https://user-images.githubusercontent.com/7983394/79702989-10bb0f80-82a9-11ea-8153-d074ae7582a0.gif)

**Comment by alexbruy** [comment]
Hmm, that's strange it works for me. I will investigate.

**Comment by alexbruy** [comment]
Oh, it is a bit more complex.

For maptips and labels we use same display expression which is either first field or field with "interesting" name (see #30245). There is no way for now to reset it to empty string. Probably we need to separate displayExpression and maptips.

**Comment by Pedro-Murteira** [comment]
I can still replicate this on QGIS 3.16.14 and 3.22.1, even if I erase a display name, the map tip will always show when doing a mouseover on a feature on canvas.

**Comment by YoannQDQ** [comment]
Not ideal, but you can hide the map tip for a specific layer by specifying an empty string in the DisplayName. Or really any invalid expression.
