### ISSUE TITLE
Need support for multiple versions of Qgis on Linux computer

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#23415]
Author Name: **Patrick Dunford** (@enzedrailmaps)
Original Redmine Issue: [15491](https://issues.qgis.org/issues/15491)

Redmine category:unknown

---
When I used to run Qgis on Windows it was easy to run multiple versions on the same computer, meaning I could run the latest beta alongside a stable version, because the installation manager (OSGeo4W) can be installed to different paths without any issues.

This appears to be very different in Linux installs because they use the package manager in each distro, which doesn't appear to offer the ability to change the install path easily, unless every single package dependency can also be in a different path.

The only option I have had so far to run multiple versions on Linux is to create a separate virtual machine for each version. Oracle VirtualBox, however, has turned out to cause issues with the operation of Qgis in these virtual machines, making them very difficult to use for this purpose. (I guess this is understandable in that the keyboard, video and mouse emulations aren't really designed with this kind of scenario in mind)

It would seem the only option remaining to me is to skip the beta program altogether and just work with stable versions in future, given there are at the time of writing about 50 bugs that can crash the development version, and one of them is very material to the work I am doing with Qgis.

**Comment by alexbruy** [comment]
As mentioned above, this is possible by building from source or using docker.
