### ISSUE TITLE
"Create single-part geometries instead of multi-part" option broken

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#23411]
Author Name: **Reinhard Reiterer** (Reinhard Reiterer)
Original Redmine Issue: [15487](https://issues.qgis.org/issues/15487)
Affected QGIS version: 2.16.1
Redmine category:db_manager
Assignee: Sandro Santilli

---
When importing multi-part geometries the "Create single-part geometries instead of multi-part" option throws an error:

@Error 7
Feature write errors:
Creation error for features from #0 to #0. Provider errors was: 
PostGIS error while adding features: FEHLER:  Geometry type (MultiPolygon) does not match column type (Polygon)@

---

- [error_7.png](https://issues.qgis.org/attachments/download/10342/error_7.png) (Reinhard Reiterer)

**Comment by pcav** [comment]
I confirm the issue also in case of a single line, see attached. It does not happen vor scratch layer.
[errore _processamento.zip](https://github.com/qgis/QGIS/files/3690537/errore._processamento.zip)

**Comment by gioman** [comment]
duplicate https://github.com/qgis/QGIS/issues/32089 (also because this ticket was correctly closed as the user was mislead by the option name).
