### ISSUE TITLE
Distribute Graphical Elements

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#23424]
Author Name: **tonkin support** (tonkin support)
Original Redmine Issue: [15500](https://issues.qgis.org/issues/15500)

Redmine category:map_tools

---
As used in an ArcGIS layout environment, the ability to distribute graphic elements would be useful in the QGIS composer. At present the align feature works well but could be supplemented by a distribute feature that allows the following functions:

The graphics are distributed with equal spacing between the centroid of each graphic:
Distribute Horizontally
Distribute Vertically
Make Same Size
Make Same Width
Make Same Height
Fit to Margins
Fit Width to Margins
Fit Height to Margins

Note this is a direct copy of the functions available in ArcGIS.

**Comment by alexbruy** [comment]
Seems already possible.
