### ISSUE TITLE
No Help for MetaSearch Core Plugin

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#23479]
Author Name: **Joana Simoes** (@doublebyte1)
Original Redmine Issue: [15556](https://issues.qgis.org/issues/15556)
Affected QGIS version: master
Redmine category:unknown

---
Whenever I try to access the help from this plugin, via "Web->MetaSearch->Help", a browser is opened with this error message:

"
Not Found

The requested URL /2.99/en/docs/user_manual/plugins/plugins_metasearch.html was not found on this server.
"

**Comment by gioman** [comment]
works now.
