### ISSUE TITLE
In spatial views, QGIS shows only 100 rows in attribute-table, when view has more than 100 objects

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#23522]
Author Name: **Gerhard Spieles** (Gerhard Spieles)
Original Redmine Issue: [15599](https://issues.qgis.org/issues/15599)
Affected QGIS version: 3.0.0
Redmine category:db_manager

---
In spatial views, created with SQL-Statement in dbmanager, attribute-table shows errors and wrong results, when view contains more then 100 objects. Save the view as shape, attribute-table has the correct attributes.
Virtual layer, generated with SQL-Statement shows attribute-table also correct.

QGIS project, spatialite db and shape are attached

Tested itwith 2.14, 2.16 and master

---

- [test.zip](https://issues.qgis.org/attachments/download/10402/test.zip) (Gerhard Spieles)
- [spatialite_view_show_only_100_features_in_attrribute_table_.jpg](https://issues.qgis.org/attachments/download/11490/spatialite_view_show_only_100_features_in_attrribute_table_.jpg) (Gerhard Spieles)
- [spatialite_view_show_right_result_in_attrribute_table_after_filterdelete_.jpg](https://issues.qgis.org/attachments/download/11491/spatialite_view_show_right_result_in_attrribute_table_after_filterdelete_.jpg) (Gerhard Spieles)
- [dbmanager_writes_in_metadata_geometriecolums.jpg](https://issues.qgis.org/attachments/download/11492/dbmanager_writes_in_metadata_geometriecolums.jpg) (Gerhard Spieles)
- [view_parent_child_all_manualy_write_in_views_geometry_colums.jpg](https://issues.qgis.org/attachments/download/11493/view_parent_child_all_manualy_write_in_views_geometry_colums.jpg) (Gerhard Spieles)
- [Spatialite views in QGIS 218.13.pdf](https://issues.qgis.org/attachments/download/11509/Spatialite%20views%20in%20QGIS%20218.13.pdf) (Gerhard Spieles)
- [view_spatialite.zip](https://issues.qgis.org/attachments/download/11510/view_spatialite.zip) (Gerhard Spieles)

**Comment by CoMartinez** [comment]
Issue is still present in 3.12
When the spatialite view is opened in Qgis, the layer shows 0 entity and only 100 in the attribute table.
Also, if you try to select entities with the selection tool, it doesn't select right entities.
If you right click on your layer, click "Update SQL layer" and just click update on the low-right corner of the DB manager window, it fixes the issue.
You can reproduce the issue with any view inside Spatialite DB.

**Comment by gioman** [comment]
See also https://github.com/qgis/QGIS/issues/40642

**Comment by Pedro-Murteira** [comment]
@CoMartinez Hello, did you come across this issue in more recent versions?

**Comment by Pixelfahnder** [comment]
@Pedro-Murteira I see this behaviour in 3.34.0-Prizren as well.
