### ISSUE TITLE
Query Builder Test button returns message with inadequate number of rows

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#23528]
Author Name: **Nikolay Lebedev** (Nikolay Lebedev)
Original Redmine Issue: [15605](https://issues.qgis.org/issues/15605)
Affected QGIS version: master
Redmine category:data_provider

---
Tested in provider filter layer property on a postgis layer. When generating a where clause with Query Builder and hitting Test button the message comes up and says 'The where clause returned N rows'. N in this case is the total number of rows in the table, not the number of filtered rows. Then the filter itself works fine - I can see an expected number of rows in attribute table, etc.
I guess this was done to speed up this message, but it's quite handy and gets a bit confusing seeing the same number of rows (total) returned when testing different queries.

Tested on master (e7c9400, python3, qt5), 2.16 and 2.14.

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
