### ISSUE TITLE
Support setting custom HTTP headers in WMS layer request

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#23585]
Author Name: **Jerome Anthony** (Jerome Anthony)
Original Redmine Issue: [15662](https://issues.qgis.org/issues/15662)

Redmine category:browser
Assignee: Jerome Anthony

---
Allow addition of custom HTTP headers when adding a WMS layer. This will be useful when user wants to use for instance JWT authentication using 'Authorization' header.

**Comment by chrishens** [comment]
This would be nice to have!

**Comment by drnextgis** [comment]
It seems to be already implemented and can be closed.

![image](https://user-images.githubusercontent.com/866124/173808356-96270eee-3c34-485f-9932-70fc6138673e.png)

**Comment by frwg** [comment]
This is missing in `3.22.4-Białowieża`
