### ISSUE TITLE
drag'n'drop from legend doesn't ask for confirmation of removal

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#23622]
Author Name: **Denis Rouzaud** (@3nids)
Original Redmine Issue: [15699](https://issues.qgis.org/issues/15699)
Affected QGIS version: master
Redmine category:map_legend
Assignee: Martin Dobias

---
When draging layers from legend of a first QGIS app to another one the layers are removed from it.
I think it would be better either:
* ask for removal or not
* just drop in new app without removing from first one

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
