### ISSUE TITLE
Processing: help users in setting up paths

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#23675]
Author Name: **Paolo Cavallini** (@pcav)
Original Redmine Issue: [15753](https://issues.qgis.org/issues/15753)
Affected QGIS version: 3.6.0
Redmine category:processing/core

---
People are very often into trouble when it comes to enter the path to specific backends for Processing (e.g. OTB, LASTools, etc.).
Possible partial solutions:

    add a check, so if the user enters a wrong path or the filepath instead of the folder, a small dialog with a short explanation can pop up
    adding a small help button close to the path text box can also help.

Possibly a separate issue: it seems that a user has to enter a path *including* the filename, even when a folder is necessary: pretty confusing IMHO.

**Comment by pcav** [comment]
See also #29189

**Comment by ElijahElliotP** [comment]
I think this possibly belongs here:
My issue is in following the setup instructions for OTB "any path" can be chosen for the library and program path (and QGIS does not have an issue activating OTB). 
![image](https://user-images.githubusercontent.com/28412116/116400172-bcba0380-a7f7-11eb-89db-746a5d7b377c.png)
![image](https://user-images.githubusercontent.com/28412116/116400019-8c726500-a7f7-11eb-9c69-910f497a3a43.png)

however the provider path may not contain spaces apparently, at runtime:
![image](https://user-images.githubusercontent.com/28412116/116400090-a14ef880-a7f7-11eb-8e44-5dd2333ca6f3.png)
![image](https://user-images.githubusercontent.com/28412116/116400238-d4918780-a7f7-11eb-9546-9ce15b9758c7.png)
I hope I have added this issue in the correct place.

**Comment by gioman** [comment]
>  I hope I have added this issue in the correct place.

@ElijahElliotP try put those paths between double quotes.

**Comment by alexbruy** [comment]
Closing as GRASS Processing provider don't have a path setting anymore and all other providers except OTB were moved out of core. OTB most likely will be moved to community plugin too.
