### ISSUE TITLE
[composer] allow expressions for legend item text

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#23692]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [15770](https://issues.qgis.org/issues/15770)

Redmine category:unknown

---
In the layer panel, it's possible to show the count of features on any layer. And this count can be shown in the composer legend.
Sometimes, instead of the number of features, it might be interesting to show in the legend the total area covered by a class.

Now that aggregate functions are availbale, It could be nice to be able to show total length/area of features of a class, or statistics on a particular field of the layer, or any other combination...

**Comment by nyalldawson** [comment]
This is now possible
