### ISSUE TITLE
attribute table: virtual field values are not updated when underlying field values changes

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#23709]
Author Name: **Mathieu Pellerin - nIRV** (Mathieu Pellerin - nIRV)
Original Redmine Issue: [15789](https://issues.qgis.org/issues/15789)
Affected QGIS version: master
Redmine category:attribute_table

---
On master, the displayed values of virtual field(s) within an attribute table are not updated when the underlying field values are changed. The user has to close the attribute table and re-open the window to see the changes. 

*Steps to reproduce*
1. Create a new project and add a vector dataset
1. Open the layer properties window, and go to the Fields section
1. Create a new virtual field with a simple expression that relies on a field present in the dataset (for e.g., "my_numerical_field * 2")
1. Apply the change and close the properties window
1. Open the attribute table window, and take a look at the virtual field values to verify the expression work
1. Switch edit mode on via the attribute table window's toolbar button
1. Click on a cell to change the value of the field you're using in your virutal field's expression
1. Notice how the virtual field isn't updating
1. Switch edit mode off and save the changes to the dataset
1. Notice how the virtual field isn't updating
1. Click on the refresh toolbar button
1. Notice how the virtual field isn't updating

While this is not a crucial issue per say (the user can close and re-open the window without losing data, etc.), it'd be important to have virtual fields updating values as underlying data is changed as those occur.

**Comment by gioman** [comment]
> * Click on the refresh toolbar button
> 
> * Notice how the virtual field isn't updating

@nirvn now it is updating after clicking the refresh button. Closing?

**Comment by gioman** [comment]
@nirvn closing or this is still an issue for you?

**Comment by gioman** [comment]
@nirvn ping

**Comment by gioman** [comment]
@nirvn ping

**Comment by nirvn** [comment]
I'll check
