### ISSUE TITLE
Geometry generator creates too many geometries for multipart input

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#23730]
Author Name: **Anita Graser** (@anitagraser)
Original Redmine Issue: [15810](https://issues.qgis.org/issues/15810)
Affected QGIS version: 3.4.5
Redmine category:symbology
Assignee: Nyall Dawson

---
I'm using geometry generator to buffer island polygons and style them with a dashed outline. The style looks wrong if applied to multipart features. It seems like the geometry generator computes the buffer around all features for every part of the multipart feature. So if there are three parts, all buffers are drawn three times on top of each other. 

I can work around it with a more elaborate expression, but I think that's not how it is supposed to be:

```
if (
  @geometry_part_count > 1,
  buffer( geometry_n( $geometry, @geometry_part_num), 0.5 ),
  buffer( $geometry, 0.5 )
)

```

**Comment by raymondnijssen** [comment]
Today I hit this one as well (in 3.11). It is even easier to reproduce:

1. Open any polygon layer containing multipart polygons
2. Set fill colour semi transparent
3. Switch symbol layer to geometry generator

The initial expression $geometry already returns the polygons N times.

**Comment by raymondnijssen** [comment]
![image](https://user-images.githubusercontent.com/681851/69669434-22014680-1092-11ea-8a15-84934e31eb98.png)

**Comment by raymondnijssen** [comment]
Tried to figure out what is going on. Actually, the variable $geometry contains only 1 (multi)polygon which is correct. So the error happens at render level, cause qgis is *drawing* the polygon N times.

I found out by labeling the layer with expression: geom_to_wkt($geometry) which shows the expected strings.

**Comment by raymondnijssen** [comment]
Tried to figure out what is going on. Actually, the variable $geometry contains only 1 (multi)polygon which is correct. So the error happens at render level, cause qgis is *drawing* the polygon N times.

I found out by labeling the layer with expression: geom_to_wkt($geometry) which shows the expected strings.

**Comment by roya0045** [comment]
> Tried to figure out what is going on. Actually, the variable $geometry contains only 1 (multi)polygon which is correct. So the error happens at render level, cause qgis is _drawing_ the polygon N times.
> 
> I found out by labeling the layer with expression: geom_to_wkt($geometry) which shows the expected strings.

It sounds like it applies the function for each part of the multipart and since the function make a multipart feature this is what occurs. Though I'm not sure in this case if it would be good or possible to trat the multipart as a singlepart during evaluation. 

What occurs when you generate a line from the feature to a label, I assume all the parts would have a line in this case.

I guess there could be an option to only evaluate once per feature, somewhere in the dialog.

**Comment by raymondnijssen** [comment]
Thanks!!
