### ISSUE TITLE
add halos to grid labels in print composer

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#23754]
Author Name: **Donovan Cameron** (@saultdon)
Original Redmine Issue: [15834](https://issues.qgis.org/issues/15834)

Redmine category:map_composer/printing

---
It would be great to be able to add halos to grid labels in the print composer.

**Comment by antoniolocandro** [comment]
Is this the same as halos?
![image](https://user-images.githubusercontent.com/4627073/155359134-60957a6c-4e2c-4f4e-9f5c-77746e232cc6.png)
