### ISSUE TITLE
Layer Properties: Mix "No labels" and "Blocking" labels options into a single one

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#23819]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [15902](https://issues.qgis.org/issues/15902)

Redmine category:labelling
Assignee: Nyall Dawson

---
The old "Discourage other labels from covering features in this layer" option to manage labels has been renamed to "blocking" (which I find not really comprehensive and leads to really ugly and meaningless translation - not all translators check the context before translating; I would have preferred labels like "Use as obstacles for labels", "Set features as obstacles"...)
But...
now that there's a "no label" option, is there a need to have a "blocking" one (actually, a "no label" configuration with hard-coded obstacles management)?
What about:
- keep only the "no label" option
- move the blocking as an option (maybe a checkbox) of "no labels": set the obstacles-related configurations, allowing
  - to reuse the obstacles widget to fine tune the blocking of labels
  - to get rid of all these greyed options of "show labels for this layer" (what about simply rename this into "Show labels"?) which disturb the user.

**Comment by nyalldawson** [comment]
Fixed in master
