### ISSUE TITLE
Add checkbox when using 'Save As' to keep original style

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#23828]
Author Name: **Pavel Diptan** (Pavel Diptan)
Original Redmine Issue: [15911](https://issues.qgis.org/issues/15911)

Redmine category:unknown

---
When using QGIS to create multiple versions of the same shapefile, it would be great to have an option to maintain the original shapefile style and automatically apply it onto the newly created shapefile.

So under the current behavior:
1. You have a line shapefile called 1d_nwk_Culvert_v01_L.shp with a red arrow style applied to it
1. You right click on 1d_nwk_Culvert_*v01*_L in the Layers Panel and click 'Save As'
1. In the Save vector layer as you specify 'ESRI Shapefile' and 'File name' to be 1d_nwk_Culvert_*v02*_L.shp
1. You click OK and QGIS creates the new shapefile with the default line style of a normal line with random colour (not as red arrow from original)

I propose that points 1 and 2 are the same while 3-4 are different:
1. You have a line shapefile called 1d_nwk_Culvert_v01_L.shp with a red arrow style applied to it
1. You right click on 1d_nwk_Culvert_*v01*_L in the Layers Panel and click 'Save As'
1. In the Save vector layer as you specify 'ESRI Shapefile' and 'File name' to be 1d_nwk_Culvert_*v02*_L.shp and tick a checkbox "Keep original style"
1. You click OK and QGIS creates the new shapefile keeping the original 1d_nwk_Culvert_*v01*_L's style (red arrow)

**Comment by alexbruy** [comment]
See also #23340.
