### ISSUE TITLE
Add other formats than text/plain to QGIS WMS GetFeatureInfo requests

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#23839]
Author Name: **Fabian Thalemann** (Fabian Thalemann)
Original Redmine Issue: [15922](https://issues.qgis.org/issues/15922)

Redmine category:web_services_clients/wms

---
Hello all,
I'm facing the same problem as the original poster of an old ticket from 2012 (#15340): QGIS still does not support GetFeatureInfo requests in any other format than text/plain. This is known and even highlighted in the most recent QGIS documentation (http://docs.qgis.org/testing/en/docs/user_manual/working_with_ogc/ogc_client_support.html#ogc-wms): "Identity Formats — The list of MIME-types the server can respond with when you use the Identify tool. Currently, QGIS supports the text-plain type."
This situation is very unfortunate: I would like to make use of several WMS right now which have text/xml as the only allowed request format. What aperi2007 wrote in the mentioned old ticket ("A server wms always add the text/plain as available format type. So is impossible to have a server wms with only the text/xml.") is apparently wrong.
I have contacted the persons who run the WMS of interest to ask them if they could be so kind to change their server configuration, but they are rather pointing back at the software I'm using. So if anyone is able to add a wider range of GetFeatureInfo request formats to the QGIS desktop software I would be very thankful!

Best regards

Fabian

**Comment by alexbruy** [comment]
As Jürgen already said, QGIS does support various formats for identify if server advertises them. Please reopen if still valid.
