### ISSUE TITLE
2to3 fix_signal issue

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#23840]
Author Name: **dr -** (dr -)
Original Redmine Issue: [15923](https://issues.qgis.org/issues/15923)
Affected QGIS version: master
Redmine category:python_plugins

---
With 2to3 fix_signal I've got the following code changes:

```
-        QObject.connect(self.downloader, SIGNAL("replyFinished(QString, int, int)"), self.networkReplyFinished)
+        self.downloader.replyFinished.connect(self.networkReplyFinished)

```

But when I run plugin I get an error:

```
self.downloader.replyFinished.connect(self.networkReplyFinished)
AttributeError: 'function' object has no attribute 'connect'

```

Maybe I have to add some modifications manually?

**Comment by alexbruy** [comment]
@gioman should we close this? To me looks like this issue is not valid anymore as most plugins already migrated to Python3
