### ISSUE TITLE
Save and stop editing for all layers

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#23866]
Author Name: **Reinhard Reiterer** (Reinhard Reiterer)
Original Redmine Issue: [15950](https://issues.qgis.org/issues/15950)

Redmine category:digitising

---
A "Save and stop editing for all layers' option in the 'Current Edits' menu would be quite helpful!

**Comment by alexbruy** [comment]
Saving edits for all layer already possible. There is #23158 about toggling editing for all layers.
