### ISSUE TITLE
Identify results panel: tweaks for usability

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#23884]
Author Name: **Paolo Cavallini** (@pcav)
Original Redmine Issue: [15968](https://issues.qgis.org/issues/15968)
Affected QGIS version: 3.0.0
Redmine category:gui

---
The panel requires IMHO a bit of love:
* when querying several rasters, a too deep tree is displayed
* the closed state of tree is restored at each query, so the user is required a lot of useless clicks
* the column widths are not shrunk to actual data, so sometimes the value column is hidden, other times data are truncated, and it is not always easy for the user noticing of these missing info.

---

- [identif1.png](https://issues.qgis.org/attachments/download/10592/identif1.png) (Paolo Cavallini)

**Comment by alexbruy** [comment]
Probably we should close this and address each issue/feature separately.

**Comment by gioman** [comment]
> Probably we should close this and address each issue/feature separately.

@alexbruy agree. @pcav can you file separate tickets? thanks.
