### ISSUE TITLE
Pie chart orientation: widdershins

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#23905]
Author Name: **belg4mit -** (belg4mit -)
Original Redmine Issue: [15989](https://issues.qgis.org/issues/15989)

Redmine category:diagrams

---
The diagrams options supports counting from 3, 6, 9 or 12 o'clock positions, but all counting is done counter-clockwise. Most pie charts (and clocks) run the other direction, and a radio button to toggle this might be nice.

**Comment by nyalldawson** [comment]
Implemented in 3.12
