### ISSUE TITLE
Joining label and object with a little line

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#23911]
Author Name: **Cyprien Pouzenc** (@Cypouz)
Original Redmine Issue: [15995](https://issues.qgis.org/issues/15995)

Redmine category:labelling

---
In case of flexible label distance (cf. #23457), it could be awesome to have the possibility to join the label and its corresponding object with a little curved line.

**Comment by nyalldawson** [comment]
Done for 3.10
