### ISSUE TITLE
Improvements to Processing:qgis:network analysis

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#23926]
Author Name: **Paolo Cavallini** (@pcav)
Original Redmine Issue: [16011](https://issues.qgis.org/issues/16011)

Redmine category:processing/qgis

---
I suggest to:
* display start and end point for shortest path (point to point)
* send a message to the user in case something goes wrong (e.g. tolerance is too low, so no path is generated)
* default speed (5) seems to low
* if the projection is in degrees (e.g. EPSG:4326), and the user chooses a too high tolerance (e.g. 2 degrees), the path is apparently not computed; better warn the user about this.

**Comment by alexbruy** [comment]
Displaying start and end points is not possible as Processing tools should run in non-inetractive mode. Although new point layer output can be added to store these points but personally I'm not sure this is useful as start and end points can be easily retrieved from the generated shortest path layer.

Algorithms throw exception if there is no route from start to end point which is the canonical way for Processing tools to report errors.

In the master default speed set to 50 km/h.

Seems this can be closed.
