### ISSUE TITLE
Symbol layer tree: Move the  "Enable (symbol) layer" option nearer

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#23939]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [16024](https://issues.qgis.org/issues/16024)

Redmine category:symbology

---
In the layer symbol tree, you can now decide to set visible or not some of the symbols. This is done thanks to the "Enable layer" option at the bottom of the symbol properties.
I do not find obvious the placement of this option. IMO, given that this option directly changes the rendering of the symbol, it would be nice to have it placed near the symbol tree frame, actually inside the frame, beside each related symbol. Maybe a visibility column with checkbox and data-defined widget (not sure what it'd look like)
Another option is to add it under the tree frame. Currently the "lock layer's color" button under the frame is a layer level property, same as layer visibility.

**Comment by nyalldawson** [comment]
This was by design -- the setting is an advanced one, and placing it higher in the widget would cause the most used settings to be pushed down and possibly hidden below scrollbars.
