### ISSUE TITLE
Multi geometry on oracle table

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#23975]
Author Name: **dany Lefeuvre** (dany Lefeuvre)
Original Redmine Issue: [16060](https://issues.qgis.org/issues/16060)
Affected QGIS version: 3.6.0
Redmine category:data_provider/oracle

---
Qgis crash if I use Oracle Table with multi Geometry. The function "Include additional geometry attributes" not work properly.

**Comment by troopa81** [comment]
There is actually some issues with table containing different type of geometries. The PR #34358 will fix them when merged. 

If I remember correctly there is data with mixed geometry type in QGIS tests and so far, I never see QGIS crash. Could you provide a sample of your data and what you're doing so I can reproduce the issue

**Comment by gioman** [comment]
> There is actually some issues with table containing different type of geometries. The PR #34358 will fix them when merged.

assuming fixed.
