### ISSUE TITLE
Native support Leader Lines to Labels

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#23995]
Author Name: **Ger CO** (Ger CO)
Original Redmine Issue: [16080](https://issues.qgis.org/issues/16080)

Redmine category:unknown

---
Please integrate the option to draw lines between features to be labeled and the correcponding labels.
This feature is available withing plugins, but for project exchange reasons this cruvial features should be core functionality

**Comment by alexbruy** [comment]
Duplicates #21845.
