### ISSUE TITLE
Feature count for {rule-based,categorized,graduated} renderer wrong when using joined fields upon project load

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#24000]
Author Name: **Mathieu Pellerin - nIRV** (Mathieu Pellerin - nIRV)
Original Redmine Issue: [16086](https://issues.qgis.org/issues/16086)
Affected QGIS version: master
Redmine category:map_legend

---
When [x] show feature count is active on a {rule-based,categorized,graduated} renderer layer relying on a joined layer field, the layer's children counts (including composer legend items) will return 0 upon project load, and will stick to that wrong count unless a category is added/deleted.

Educated guess: upon project load, the feature count takes place prior to joining layer(s), resulting in the wrong 0 count.

*Steps to reproduce*
1. Launch QGIS and open the attached test project (count.qgs)
1. Notice the layer count on the layer panel is wrong (says 0 when you'll clearly see styled polygons on the map)
1. Open the style dock, and add a category to the categorized renderer (i.e. push the [+] button)
1. Notice the feature counts are now correct

---

- [count.zip](https://issues.qgis.org/attachments/download/10676/count.zip) (Mathieu Pellerin - nIRV)

**Comment by gioman** [comment]
This seems fixed now.
