### ISSUE TITLE
Composer: LatLon Grid-Draw coordinates problem of decimal values in metric srs on global scales

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#24019]
Author Name: **Juraj Betak** (@jurajbetak)
Original Redmine Issue: [16107](https://issues.qgis.org/issues/16107)
Affected QGIS version: master
Redmine category:unknown

---
Composer > GRID > Draw coordinates

I have a world map in metric srs like epsg:54003 or epsg:3857 and I want to draw LatLon grid with DECIMAL values (CRS set to epsg:4326).

It works nicely, unless the map zoom is at e.g. continental level;
however it works strange from certain zoom/scale (close to global level); many LatLon values appear in the grid. See screenshots attached.
The same behavior in v2.18.3, v2.16.3 on Windows and 2.16.3 on Linux.

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
