### ISSUE TITLE
identify features' highlight missing on graduated renderer using expression-based column

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#24046]
Author Name: **Mathieu Pellerin - nIRV** (Mathieu Pellerin - nIRV)
Original Redmine Issue: [16134](https://issues.qgis.org/issues/16134)
Affected QGIS version: master
Redmine category:symbology

---
Here's an interesting one: when a vector layer's renderer is set to graduated, and its graduation column is an expression, the identify features' semi-transparent red highlight (to identify which feature(s) is overlapping with the canvas mouse click) is missing. It's not the end of the world, but it's rather perplexing when you don't know what's going on.

*Steps to reproduce*
1. Open the attached id_highlight_gone test project
1. Select the Identify Feature tool
1. Click on one of the polygons
1. Notice that while the polygon clicked is correctly returned in the identify feature panel, there is no semi-transparent red polygon overlay on the canvas
1. Open the style dock, and switch the layer's graduated renderer to rule-based (rules will be automatically transferred over)
1. Return to the canvas with the Identify Feature tool, and click on one of the polygons
1. notice the semi-transparent red polygon overlay is there

---

- [id_highlight_gone.zip](https://issues.qgis.org/attachments/download/10692/id_highlight_gone.zip) (Mathieu Pellerin - nIRV)

**Comment by gioman** [comment]
This seems fixed now.
