### ISSUE TITLE
Processing : execute sql alg does not work with input2 ... inputN parameters

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#24041]
Author Name: **jd lom** (@lejedi76)
Original Redmine Issue: [16129](https://issues.qgis.org/issues/16129)
Affected QGIS version: 3.5(master)
Redmine category:processing/qgis

---

In ExecuteSQL.py, the layerIdx variable is not incremented.

Best regards,

---

Related issue(s): #28487 (duplicates)
Redmine related issue(s): [20667](https://issues.qgis.org/issues/20667)

---

**Comment by troopa81** [comment]
Proposed PR: https://github.com/qgis/QGIS/pull/30442
