### ISSUE TITLE
legend of proportionate circles: circles should be centered, not left justified

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#24060]
Author Name: **mlennert -** (mlennert -)
Original Redmine Issue: [16148](https://issues.qgis.org/issues/16148)

Redmine category:map_composer/printing

---
When creating a legend of proportionate circles in the map composer, the circles are drawn left justified. 
It would be nice if they  were centered, or if the user could at least chose to center them. 
I'm attaching an image to show the problem.

I'm classifying this as a feature request but hesitated to classify it as a bug since IMHO the current solution does not make the legend usable for professional cartography.

---

- [symbol_size_legend_left_justified.png](https://issues.qgis.org/attachments/download/10712/symbol_size_legend_left_justified.png) (mlennert -)

**Comment by alexbruy** [comment]
Seems already fixed. Closing.
