### ISSUE TITLE
The new searchbox in the Layer properties dialog prevents minimization of the icons left panel

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#24103]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [16193](https://issues.qgis.org/issues/16193)
Affected QGIS version: 3.4.4
Redmine category:gui

---
The screenshot might be more explanatory
Other dialogs (Options, Raster(didn't check)) might be also concerned

---

- [searchbox.png](https://issues.qgis.org/attachments/download/10736/searchbox.png) (Harrissou Santanna)
- [options_searchbox resize.png](https://issues.qgis.org/attachments/download/14496/options_searchbox%20resize.png) (Harrissou Santanna)

**Comment by alexbruy** [comment]
Seems alredy fixed, please check.

**Comment by DelazJ** [comment]
I can't see any difference from my first screenshot. This is the minimal size I could get when reducing the left panel in 4ee3d22.
![image](https://user-images.githubusercontent.com/7983394/79704539-47e1ee80-82b2-11ea-8edf-d8fa7bb451e3.png)
Now, is it something worth a fix? I have no idea what it would require.

**Comment by alexbruy** [comment]
Weird. It looks fine here on Linux
![linux](https://user-images.githubusercontent.com/776954/79723654-c9f00880-82ee-11ea-87a6-3fd0e4f991d4.png)
and Windows
![windows](https://user-images.githubusercontent.com/776954/79723661-cd838f80-82ee-11ea-83b0-a8b97d78feff.png)

Probably system related. Which DE/theme are you using? I suspect it is Gnome. Any chance to test with other DE?

**Comment by pcav** [comment]
In my case, Gnome3, it works correctly.

**Comment by DelazJ** [comment]
hmm.. Gnome 3.28 here on Ubuntu 18.04. Will test on other environments.

**Comment by gioman** [comment]
@DelazJ can we close this?

**Comment by DelazJ** [comment]
Yes, let's close it. I still have the issue (i moved to focal meanwhile) but since it seems to work fine for everyone else, I might have some local "bad thing". The only inconvenience is that I can't reduce that panel while taking screenshot, so not a big deal
