### ISSUE TITLE
Symbol selector dialog: Clicking on the "data-defined override" button disables its configuration

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#24114]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [16204](https://issues.qgis.org/issues/16204)
Affected QGIS version: master
Redmine category:unknown
Assignee: Nyall Dawson

---
Add a point layer
In layer styling (I live update activated though not sure it has something to do with the issue), Symbology, single symbol
At the Marker level, use the "Assistant.." to modify the size of symbols
Now select the "simple marker" level and click on the data-defined override icon (which should be yellow) near the Size option
The yellow color disappear and the data-defined effects removed from the map canvas. This happens also if you select the Size option from the Marker level.
Note however that the settings you entered in the Symbol Size dialog are still present.

I don't know if it's due to this issue but I couldn't figure out how the Assistant could be ignored later in the settings.

Master 3496871

**Comment by gioman** [comment]
Cannot replicate on the latest master, reopen if necessary.

**Comment by DelazJ** [comment]
Cannot either 👍
