### ISSUE TITLE
Color Maps with labels that contain commas

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#24112]
Author Name: **Darren Kavanagh** (@dkav)
Original Redmine Issue: [16202](https://issues.qgis.org/issues/16202)
Affected QGIS version: 2.18.2
Redmine category:rasters

---
Scope - Single Band Pseudocolor Renderer (qgssinglebandpseudocolorrendererwidget.cpp)

Exported color maps labels that contain commas are exported without enclosing the label within double quotes. Example output:
> _1,255,255,255,255,Label, with comma_

Importing color maps that contain labels with commas results in an error: 
> _The following lines contain errors ..._ .

Manually adding double quotes to label and importing gives the same error.

To correct this problem a different column separator could be used or new logic written to output and parse text fields like a CSV file.

**Comment by dkav** [comment]
@nyalldawson this bug still exists in QGIS 3.14.15-Pi. Do I need to open a new issue?
