### ISSUE TITLE
"Line Pattern Fill" symbol layer should not embed "Draw line only inside polygon" property for line sub symbol

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#24131]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [16221](https://issues.qgis.org/issues/16221)
Affected QGIS version: 2.18.3
Redmine category:symbology

---
Symbolize a polygon layer with the Line Pattern Fill symbol layer type
Under the "Line Pattern Fill" level, You have a "Line" --> "Simple line" symbol layer by default.
Given that this pattern is all about filling the polygon and does not interact with its boundary, having a "Draw line only inside polygon" property available is not coherent.

Actually the dialog should be populated by the default properties of "Simple line" symbol layer instead of using "Outline: Simple line" dialog.

**Comment by DelazJ** [comment]
@gioman still valid for 3.10. Can you reopen, please?
