### ISSUE TITLE
Diagrams don't render if all values are negative

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#24166]
Author Name: **Daniel Moreira** (Daniel Moreira)
Original Redmine Issue: [16256](https://issues.qgis.org/issues/16256)
Affected QGIS version: 3.0.0
Redmine category:diagrams

---
Left click on layer -> Properties -> Diagrams -> Attributes. If all columns on the 'Attribute' list are negative it fails to render the resulting graphic.

**Comment by alexbruy** [comment]
Which diagram type is used? I have tested and text diargams works fine, as well as histograms.

**Comment by alexbruy** [comment]
Stacked bar diagrams were fixed by #37924. Please reopen if necessary.
