### ISSUE TITLE
Issue connecting QgsVectorLayer.committedAttributesAdded under QGIS3 Windows

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#24178]
Author Name: **enrico ferreguti** (@enricofer)
Original Redmine Issue: [16268](https://issues.qgis.org/issues/16268)
Affected QGIS version: master
Redmine category:python_plugins

---
I am migrating a plugin to QGIS3 and under Windows with the latest qgis-dev release(build 1182816) 
I get an error connecting to well know QgsVectorLayer signals:
vectorlayer.committedAttributesAdded.connect(self.attributes_added) or vectorlayer.committedFeaturesAdded.connect(self.features_added)
give:
TypeError: C++ type 'QList' is not supported as a signal argument type

asking in Qgis developer list Matthias Kuhn states that:

"here on fedora it works
def test(layer, features):
    print(layer, features)
l.committedFeaturesAdded.connect(test)
So it seems to be a build issue, not a change in QGIS itself."

**Comment by alexbruy** [comment]
Closed for the lack of feedback. Please reopen if necessary.
