### ISSUE TITLE
Resizing tools in processing modeler

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#24189]
Author Name: **Magnus Nilsson** (Magnus Nilsson)
Original Redmine Issue: [16279](https://issues.qgis.org/issues/16279)

Redmine category:processing/modeller
Assignee: Victor Olaya

---
I would like to be able to resize the tools (at least up to a certain limit) in the modeler, since they sometimes are too small for the description that I have entered.

**Comment by nyalldawson** [comment]
Possible in 3.14
