### ISSUE TITLE
Spatial Bookmark Panel: add more precision & user interactivity

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#24188]
Author Name: **Tobias Wendorff** (Tobias Wendorff)
Original Redmine Issue: [16278](https://issues.qgis.org/issues/16278)

Redmine category:gui

---
Based on experience in daily work with QGIS, I've got this feature request to "Spatial Bookmark Panel":

1. Don't clip/round the precision of bookmarks! Right now, the precision is limited to two. Way not enough for some tasks! Perhaps this is a bug right now?
1. Allow the users to store an addition scale. I know, the BBOX already hints to the scale (right now, it's buggy since the precision is too low), but often it's needed to "zoom out" or in given that fixed extent.
1. Allow copy and paste to the values in bookmark panel. It's very faulty to type in the values manually - perhaps this is a bug right now?
1. Allow copy and paste to a whole line in bookmarks panel. Often, it's much more easy to communicate with a user, by sending him a BBOX or loading the one, he has sent by text mail or IM.
1. Create a switch to make the order of bookmark coordinate "WMS" compatible. Right now, it's "xMin, yMan, xMin, xMax" while WMS has Min/Max swiched. Don't make this default of course, just give the user to possibility to change it.

**Comment by alexbruy** [comment]
Please re-test with master. There were some work done on spatial bookmarks.

**Comment by nyalldawson** [comment]
Closing due to lack of feedback
