### ISSUE TITLE
Add SQL window to browser panel

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#24195]
Author Name: **Reinhard Reiterer** (Reinhard Reiterer)
Original Redmine Issue: [16285](https://issues.qgis.org/issues/16285)

Redmine category:browser

---
SSIA...

---

- [16285.png](https://issues.qgis.org/attachments/download/10793/16285.png) (Reinhard Reiterer)

**Comment by nyalldawson** [comment]
@elpaso we can close this one, right?
