### ISSUE TITLE
Batch Processing Can Only Remove Last Entry

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#24217]
Author Name: **Spencer Gardner** (@spencerrecneps)
Original Redmine Issue: [16307](https://issues.qgis.org/issues/16307)

Redmine category:processing/core

---
If I want to remove a line from my batch process, the interface only allows me to remove the last line of the entire list. This is a problem when I use saved batch settings because I may only want to run the last few lines in the batch process but there is no way to remove the first lines.

How to replicate:
1. Open a batch process dialog
1. Add multiple lines
1. Select the top line
1. Click the button to remove a line

What happens:
The last line in the batch process is removed.

What should happen:
The line that is selected is removed.

**Comment by alexbruy** [comment]
Already fixed.
