### ISSUE TITLE
Adding the same short_name option on multiple layers is possible

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#24227]
Author Name: **Tudor Bărăscu** (@tudorbarascu)
Original Redmine Issue: [16317](https://issues.qgis.org/issues/16317)
Affected QGIS version: 3.7(master)
Redmine category:qgis_server
Assignee: Alessandro Pasotti

---
Adding the same short_name option on multiple layers is possible.
Accessing that short_name in a GetMap request results in only the first layer that was given that specific short_name to be called.
This could lead to confusion for big projects where by accident people use the same short_name for multiple layers.

How to reproduce:
Use the same short_name for at least two layers.
The GetMap request using the short_name point to the first layer that was given short_name.

**Comment by Pedro-Murteira** [comment]
This is still true on QGIS 3.16.14 and 3.22.1.

**Comment by Gustry** [comment]
I'm not sure if I understand the ticket @Pedro-Murteira 
Shortnames must be unique indeed. Use the QGIS project server validator, last item in the QGIS server tab of your project properties. Il will warn you if you have duplicates.

You can use the checkbox "use layer ID for shortname" if needed.

**Comment by gioman** [comment]
> Use the QGIS project server validator, last item in the QGIS server tab of your project properties. Il will warn you if you have duplicates.

@Gustry agree, can we close this @tudorbarascu ?

**Comment by tudorbarascu** [comment]
From my part, yes.. as there is a workaround.
It should still be a bug though as it lets you do it and you have to manually check and some will clearly miss this step.
For the sake of closing down issues.. we can close it, sure.

**Comment by Pedro-Murteira** [comment]
@Gustry thank you for your feedback and for also pointing me out that funcionality. 
"One or more layers or groups have the same name or short name. Both the 'name' and 'short name' for layers and groups must be unique" I understand now.
