### ISSUE TITLE
keyboard shortcut for "Deselect Features from All Layers" button doesn't work

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#24262]
Author Name: **Piotr Kania** (Piotr Kania)
Original Redmine Issue: [16352](https://issues.qgis.org/issues/16352)
Affected QGIS version: master
Redmine category:unknown

---
QGIS version 2.99.0-Master code revision cd7b19c, win 7 sp1 x64 home edition. If I set keyboard shortcut for "Deselect Features from All Layers" button - it doesn't work. Others shortcuts work as expected.

**Comment by baswein** [comment]
I just tried this and it worked as expected. 
QGIS version
3.10.2-A Coruña
QGIS code revision
d4cd3cfe5a
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.3
Running against GDAL/OGR
3.0.3
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.0
Running against PROJ
Rel. 6.3.0, January 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
BivariateLegend; 
DataPlotly; 
inkscape2symbol-master; 
MagneticDeclination; 
processing_r; 
Qgis2threejs; 
qgis2web; 
qgsAzimuth; 
QuickOSM; 
quick_map_services; 
toolbargenerator; 
workbench; 
db_manager; 
MetaSearch; 
processing
