### ISSUE TITLE
Opacity of raster not changing in Print Composer

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#24296]
Author Name: **Brent Fallarcuna** (Brent Fallarcuna)
Original Redmine Issue: [16387](https://issues.qgis.org/issues/16387)

Redmine category:map_legend

---
I am adjusting my raster DEMS opacity. I set the 0-100 m (white) elevation's raster opacity to 0% so that the flat areas of my land are clearly seen.
As I add this raster to my legend, the opacity does not change. Unfortunately, I cannot use a white background for my legend as a turnaround solution because may legend background also had an adjusted opacity.
I am repeatedly experiencing this bug every time I try to add a raster legend with adjusted opacity.

**Comment by nyalldawson** [comment]
This was fixed a long time ago
