### ISSUE TITLE
Print Composer allow legend arrangement

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#24353]
Author Name: **Antonio Viscomi** (@Antoviscomi)
Original Redmine Issue: [16444](https://issues.qgis.org/issues/16444)

Redmine category:map_composer/printing

---
In the legend of print composer (QGIS 2.18.6), 
is impossible to rearrange the  internal records of a categorized group layer.
In canvas is active "filter to map content" (because the shapefile contains about 40,000 records of which only 4 are visible in the map).

**Comment by roya0045** [comment]
This seems fixed
