### ISSUE TITLE
Can a project 'remember' where the Composer output was saved?

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#24361]
Author Name: **Johanna Botman** (Johanna Botman)
Original Redmine Issue: [16452](https://issues.qgis.org/issues/16452)

Redmine category:map_composer/printing

---
I work with many projects, and often come back to one after a number of years, and save my PDF and JPG files to a fairly complicated directory structure. Currently, QGIS remembers where I last saved my output, but I would like for it to remember where it saved the output for that particular project.
Is that possible?

**Comment by nyalldawson** [comment]
Implemented since QGIS 3
