### ISSUE TITLE
Name of print composers changed from QGIS 2 to 3 without warning

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#24380]
Author Name: **Konradin Fischer** (@kfischerar)
Original Redmine Issue: [16471](https://issues.qgis.org/issues/16471)
Affected QGIS version: master
Redmine category:map_composer/printing

---
we have an existing project in 2.18.6 (win7) and several composers with real names for example "situation 1:1000" included. If we open the project in qgis 3 the name of the composer changes to "composer 1", "composer 2" and so one

**Comment by nyalldawson** [comment]
Closing due to lack of feedback. If it's still an issue, we need a sample project to test with.
