### ISSUE TITLE
Using @parent with aggregate doesn't return expected results

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#24389]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [16481](https://issues.qgis.org/issues/16481)
Affected QGIS version: master
Redmine category:expressions

---
I have a polygon layer I would like to style according to the presence of features of another layer (site_concours).
Hence I used
```
 aggregate( layer:='site_concours', aggregate:='count', expression:="gid", filter:=contains( geometry( @parent ), $geometry ) )

```
to highlight polygon features that contains my site_concours features. As you can see in the attached map, the green polygons are not coherent with the orange ones. I unsuccessfully tried different geometry predicates with categorized or rule-based rendering (note that the results returned were always the same).

Added a project to replicate.

---

- [_parent_aggregate.PNG](https://issues.qgis.org/attachments/download/10903/_parent_aggregate.PNG) (Harrissou Santanna)
- [aggregates.7z](https://issues.qgis.org/attachments/download/10904/aggregates.7z) (Harrissou Santanna)

**Comment by gioman** [comment]
@DelazJ works are expected here on QGIS master/3.13.

**Comment by gioman** [comment]
Closing for lack of further feedback.
