### ISSUE TITLE
"Allow NULL values" in Date/Time widget meaningless 

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#24402]
Author Name: **zicke -** (zicke -)
Original Redmine Issue: [16496](https://issues.qgis.org/issues/16496)
Affected QGIS version: master
Redmine category:edit_widget

---
The field "aupdate" has a NOT NULL constraint in the geopackage (attached). In such cases the checkbox "Allow NULL values" in the Date/Time widget should be greyed out.

---

- [alw_vernetzung_test3.gpkg](https://issues.qgis.org/attachments/download/10920/alw_vernetzung_test3.gpkg) (zicke -)

**Comment by alexbruy** [comment]
Already fixed.
