### ISSUE TITLE
QML style is not applied to a specific raster layer

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#24406]
Author Name: **dr -** (dr -)
Original Redmine Issue: [16500](https://issues.qgis.org/issues/16500)
Affected QGIS version: master
Redmine category:symbology

---
1) Open QGIS and add raster layer @hrsl_bfa.tif@
2) Properties - Style - Style - Load Style - @qml/hrsl_bfa.qml@. Layer appearance is changed at canvas. But when you click @Apply@ - canvas becomes black.

Dataset: https://www.dropbox.com/s/lt595zahtlpnuhv/hrsl_bfa.zip?dl=0

**Comment by alexbruy** [comment]
Closed for the lack of feedback. Please reopen if necessary.
