### ISSUE TITLE
Print Composer: Adjust word wrap in legend item by length (pixel or number of characters)

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#24446]
Author Name: **Patrice Pineault** (Patrice Pineault)
Original Redmine Issue: [16540](https://issues.qgis.org/issues/16540)

Redmine category:map_legend

---
It would be nice to be able to specify the maximum number of characters or pixels a legend column could be. If the legend item is longer than the value, it would automatically display the item's text on several lines in order to fit the width of the column.

**Comment by nyalldawson** [comment]
Duplicate of #25172
