### ISSUE TITLE
round off corners in shape (QGIS)

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#24461]
Author Name: **Tobias Hurtienne** (Tobias Hurtienne)
Original Redmine Issue: [16559](https://issues.qgis.org/issues/16559)

Redmine category:geometry

---
Hallo,
i would like to round off the corners in a given shape with a certain radius in QGIS. Does somebody has any idea?

Tobias

**Comment by alexbruy** [comment]
This is not the right place for such questions, I would suggest to use one of the [support and discussion channels](https://qgis.org/en/site/forusers/support.html) to get some help. Bugtracker should be used to report bugs and ask for new features.
