### ISSUE TITLE
Plugin installation for all domain-users

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#24478]
Author Name: **Yannick Günther** (Yannick Günther)
Original Redmine Issue: [16576](https://issues.qgis.org/issues/16576)

Redmine category:plugin_manager
Assignee: Borys Jurgiel

---
Hello,
while trying to install plugins (in this case the semi-automatic-classification plugin) for machines in a computer pool (win 10 x64 environment), it was not possible to install plugins for all domain-users respectively as an admin. Is it generally possible?  I am not exactly versed in the mechanics of functioning concerning QGIS and it's plugins, but in my growing distress i decided to approach you with this problem. The users have to re-install the plugin every time they access the machine. Do you have any ideas? The version is QGIS 2.18.4. 

Thank you very much for your advice,
best regards

**Comment by alexbruy** [comment]
Please use other support channels (e.g. mailing lists, gis.stackexchange, IRC...) for questions like this.
