### ISSUE TITLE
Select tool feature picker

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#24541]
Author Name: **Karl-Magnus Jonsson** (@karl-magnus)
Original Redmine Issue: [16641](https://issues.qgis.org/issues/16641)

Redmine category:map_tools

---
I’ve had a thought of improvement of the select tool. When there is several features in the same (or almost the same) location in one layer it is difficult to select one particular feature. Could we have the same functionality with select tool as with identify? Right click gets you a pull-down menu with potential features and you can select one from the list that gets selected. Or as it says in the documetation for identify: right click will fetch all the snapped features from all the visible layers. This will open a context menu, allowing the user to choose more precisely the features to identify (select). 

A workaround is to use the identify tool with right click. At the bottom of the list you can open the attribute table and select the desired features from the table. Works but one step more.

---

- [select_dialog_mockup.png](https://issues.qgis.org/attachments/download/11018/select_dialog_mockup.png) (Karl-Magnus Jonsson)

**Comment by kannes** [comment]
QGIS 3.18 (maybe earlier) does this, this issue can be closed.

![grafik](https://user-images.githubusercontent.com/7661092/111810821-b5d5d200-88d6-11eb-939b-614a53cb6662.png)

**Comment by karl-magnus** [comment]
Yes, I confirm. We ordered it to be in 3.18 See https://github.com/qgis/QGIS/pull/40248 and https://changelog.qgis.org/en/qgis/version/3.18/#select-feature-context-menu
