### ISSUE TITLE
Add order_by parameter to concatenate aggregate function

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#24561]
Author Name: **jd lom** (@lejedi76)
Original Redmine Issue: [16662](https://issues.qgis.org/issues/16662)

Redmine category:expressions

---
It would be nice to have an *order_by* parameter in *concatenate* function.

Something like that :

concatenate("town_name",group_by:="state",concatenator:=',', order_by:="population") 
concatenate("town_name",group_by:="state",concatenator:=',', order_by:=$area) 

Regards,

**Comment by nyalldawson** [comment]
Implemented in 3.8
