### ISSUE TITLE
When saving project, main windows changes size

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#24597]
Author Name: **Mark Johnson** (Mark Johnson)
Original Redmine Issue: [16698](https://issues.qgis.org/issues/16698)
Affected QGIS version: master
Redmine category:gui

---
During the saving of a project, the main QGIS window will revert - when full screen - to 100% Width and about 50% Height.
When resized (but not full screen), size remains when saving a project.

Base on code from the 2017-06-08.

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
