### ISSUE TITLE
Data Source Manager reset values on changes

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#24618]
Author Name: **Klas Karlsson** (@klakar)
Original Redmine Issue: [16719](https://issues.qgis.org/issues/16719)
Affected QGIS version: master
Redmine category:data_provider/delimited_text_

---
The new Data Source Manager resets some options when you change previous options when adding "Delimited Text".

If I first choose "No Geometry" under geometry definition, and then change "File Format", specifically when changing "Custom Delimiter", the geometry will reset to "Point Coordinates".

If at all possible, changes in settings should not reset settings already made.

---

- [Screenshot at 2017-06-18 09_04_55.png](https://issues.qgis.org/attachments/download/11080/Screenshot%20at%202017-06-18%2009_04_55.png) (Klas Karlsson)

**Comment by alexbruy** [comment]
Not reproducible on 3.10/3.12/master.
