### ISSUE TITLE
tests/src/core/testqgsogcutils.cpp Port away from qt_qhash_seed which is going away in Qt 5.9

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#24623]
Author Name: **Bruno Friedmann** (@tigerfoot)
Original Redmine Issue: [16724](https://issues.qgis.org/issues/16724)
Affected QGIS version: master
Redmine category:tests_suite

---
tests/src/core/testqgsogcutils.cpp doesn't build with QT59

see
https://codereview.qt-project.org/188474

qSetGlobalQHashSeed exists since Qt 5.6, but this project seems to
require 5.3, so I added a Qt version ifdef.
Thanks to David Faure and Fabian Vogt for pointers.

---

- [upstream_fix_qt59_private_api_call.patch](https://issues.qgis.org/attachments/download/11082/upstream_fix_qt59_private_api_call.patch) (Bruno Friedmann)

**Comment by gioman** [comment]
Is this still relevant?

**Comment by alexbruy** [comment]
Already fixed.
