### ISSUE TITLE
The scaling bar go in the "space" after having activate the atlas

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#24628]
Author Name: **Gladal PS** (Gladal PS)
Original Redmine Issue: [16729](https://issues.qgis.org/issues/16729)
Affected QGIS version: 3.2.1
Redmine category:map_composer/printing

---
After having activated the atlas, the X position of my scale bar change in 10000000mm. I put images to illustrate the bug.
The problem occured on the same project than #24627

---

- [before.png](https://issues.qgis.org/attachments/download/11085/before.png) (Gladal PS)
- [After.png](https://issues.qgis.org/attachments/download/11086/After.png) (Gladal PS)

**Comment by nyalldawson** [comment]
Can't be reproduced with the supplied information - please open a new ticket with a sample project if it's still an issue.
