### ISSUE TITLE
Add layer-centric expression functions

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#24632]
Author Name: **Nikolay Lebedev** (Nikolay Lebedev)
Original Redmine Issue: [16733](https://issues.qgis.org/issues/16733)

Redmine category:expressions

---
While there are a lot of feature-centric functions, there is no function to get layer as a whole with it's properties. It would be nice to have a @get_layer('layer_name')@ function, returning a layer object. And complementary functions like @feature_count(layer)@ and @extent(layer)@ etc. that use layer object as input and return it's properties.

**Comment by suricactus** [comment]
This is already implemented as `layer_property` and should be closed:

> @feature_count(layer)
> @extent(layer)
```
layer_property(@<!-- -->layer_id', 'extent')
layer_property(@<!-- -->layer_name, 'count')
```

**Comment by NicolasCadieux** [comment]
But how do we do this when the layer is a model input? using @inputraster, 'name' does not work.
Thanks

**Comment by NicolasCadieux** [comment]
I was finally able using the following method:
Inputraster -> Export layer(s) information ->  Execute SQL (SELECT name FROM input1) -> List unique values. @List_unique_values_UNIQUE_VALUES can be use in layer properties.
ex:
layer_property(@List_unique_values_UNIQUE_VALUES', 'extent')
