### ISSUE TITLE
Browser Panel: unable to find all the connected drives

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#24641]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [16742](https://issues.qgis.org/issues/16742)
Affected QGIS version: 3.4.5
Redmine category:browser

---
The browser panel doesn't show all the drives I can connect to. Actually it fails to show a drive I pluged in as a network drive.
As you can see in the screenshot, the "SIG" folder (which is a folder on the macOS company network) doesn't appear in the browser panel.
However, I can have access to that folder if I use the classic Add vector/raster layer tool.

---

- [browser_missingdrives.PNG](https://issues.qgis.org/attachments/download/11095/browser_missingdrives.PNG) (Harrissou Santanna)

**Comment by LDalby** [comment]
I still have this issue in 3.10.1 on mac OS (10.14.6).
In the Browser shared drives never show up, but using Jeroen Hovens's workaround allows me to access the shares just fine.

Any chance that this issue could be solved in a future version?

**Comment by gioman** [comment]
Confirmed also here on 3.10.1/Catalina.

**Comment by mradamcox** [comment]
Just found this same issue in QGIS 3.4 on macOS 10.14 (Mojave), and the workaround solves it. Thanks for that!

**Comment by PeterPetrik** [comment]
On MacOS I believe it is duplicate of https://github.com/qgis/QGIS/issues/29702, which is fixed by https://github.com/qgis/QGIS/pull/39096
