### ISSUE TITLE
Make autosaver plugin a core feature

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#24707]
Author Name: **Nikolay Lebedev** (Nikolay Lebedev)
Original Redmine Issue: [16808](https://issues.qgis.org/issues/16808)

Redmine category:project_loading/saving

---
Please add ability to setup autosaving current project.
This is much needed since QGIS isn't perfectly stable, like OS it runs on, power outlets, etc. 
Autosave event can be fired on any style change or timely or could be customised.

**Comment by alexbruy** [comment]
Duplicates #19650.
