### ISSUE TITLE
Opening Browser show No such signal warnings (errors?) in Qt Log Messages

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#24713]
Author Name: **Richard Duivenvoorde** (@rduivenvoorde)
Original Redmine Issue: [16814](https://issues.qgis.org/issues/16814)
Affected QGIS version: master
Redmine category:browser

---
See attachment.

Upon first opening of the Data Source Manager, a lot of 'No such signal' messages show up in the Log Messages Panel when it is open.

---

- [QobjectConnectMsgs.png](https://issues.qgis.org/attachments/download/11145/QobjectConnectMsgs.png) (Richard Duivenvoorde)

**Comment by alexbruy** [comment]
Seems already fixed in master.
