### ISSUE TITLE
Add toggle labels to layer context menu

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#24753]
Author Name: **Nikolay Lebedev** (Nikolay Lebedev)
Original Redmine Issue: [16854](https://issues.qgis.org/issues/16854)

Redmine category:gui

---
Please add Toggle labels on/off to layer context menu. 
I can't express how much I miss this feature from ArcGIS. 
This should be quite easy to implement IMHO.

**Comment by kannes** [comment]
This would be superbly useful when using QGIS as explorative data analysis tool or for cartography in general.

**Comment by alexbruy** [comment]
Duplicates #22600.
