### ISSUE TITLE
Add grouping items in Composer item list

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#24754]
Author Name: **Nikolay Lebedev** (Nikolay Lebedev)
Original Redmine Issue: [16855](https://issues.qgis.org/issues/16855)

Redmine category:map_composer/printing

---
Composer item list get's crowded very easily. 
Can this list be a tree with grouping by page or something? (Better custom grouping)
Item groups are represented by separate records in this list, which isn't great UX.

**Comment by YoannQDQ** [comment]
Superseded by #27022
