### ISSUE TITLE
Native XYZ provider only appears in browser. It should also be listed in new unified button

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#24776]
Author Name: **Regis Haubourg** (@haubourg)
Original Redmine Issue: [16877](https://issues.qgis.org/issues/16877)

Redmine category:gui

---
Finding the new xyz connection is only possible in the browser dock, it should at least be also in unified button, and for the sake of UI consistency be in Menu/Layer and associated toolbar (which I agree is already too crowded).

**Comment by alexbruy** [comment]
Fixed in master recently.
