### ISSUE TITLE
Data Source Manager / Browser gives a message for every source that does not have crs info

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#24815]
Author Name: **Richard Duivenvoorde** (@rduivenvoorde)
Original Redmine Issue: [16916](https://issues.qgis.org/issues/16916)
Affected QGIS version: master
Redmine category:browser

---
Not sure if this is by design, but if I use the Browser and have a directory with some data files without crs info (shapefile without the .prj file), I get every time(!) I select that file, I get the message CRS was undefined: defaulting to project CRS....

Going to another file and going back I have it again for the same file, WITHOUT even loading it!

Off course I understand to read the metadata which is shown nowadays in the browser you have to load the data, but I think it is overkill to see this message when browsing.

Would it not be better to only show it when it is actually loaded?
OR (in my view) even better, do not show it in the messagebar so loudly, but just show it in the browser-metadata!

I would even be in favour to retire this message anyway, because it pops up also when you load a GML file via the python interface etc. I see it to often, and have to tell people: don't worry... bla bal

---

- [crsmsg.png](https://issues.qgis.org/attachments/download/11254/crsmsg.png) (Richard Duivenvoorde)
- [p.zip](https://issues.qgis.org/attachments/download/11255/p.zip) (Richard Duivenvoorde)

**Comment by alexbruy** [comment]
Shoiuld be fixed. Please reopen if necessary.
