### ISSUE TITLE
Canvas rotation makes features vanish

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#24851]
Author Name: **Johannes Kroeger** (Johannes Kroeger)
Original Redmine Issue: [16952](https://issues.qgis.org/issues/16952)
Affected QGIS version: 2.18.11
Redmine category:map_canvas

---
I noticed some data vanishing on non -180/-90/0/90/180 angles of map canvas rotatio in a recent project. See the attached collage for examples.

To reproduce:

Load ftp://eclipse.ncdc.noaa.gov/pub/ibtracs/v03r09/all/shp/Allstorms.ibtracs_all_points.v03r09.zip
Set the EPSG to 3031.
Rotate the canvas to get a gap. If it does not appear, you might need to pan or zoom a bit. It seems to happen more often if you zoom out (eg to layer extents).

It might be the combination of OTF reprojection and canvas rotation. I could not reproduce this in another CRS, not even 3032.

---

- [3031 with canvas rotation.png](https://issues.qgis.org/attachments/download/11289/3031%20with%20canvas%20rotation.png) (Johannes Kroeger)

**Comment by kannes** [comment]
This still happens in 3.8, please re-open.

-- | -- | -- | --
-- | -- | -- | --
QGIS version | 3.8.0-Zanzibar | QGIS code branch | Release 3.8
Compiled against Qt | 5.13.0 | Running against Qt | 5.13.0
Compiled against GDAL/OGR | 3.0.0 | Running against GDAL/OGR | 3.0.0
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
PostgreSQL Client Version | 11.4 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 6.1.0 | Running against PROJ | Rel. 6.1.0, May 15th, 2019
OS Version | Arch Linux |   |

**Comment by Pedro-Murteira** [comment]
I'm not being able to reproduce this issue on QGIS 3.22.4 and 3.24.0. @kannes Hello, it's been a while, but do you remember which data you used to confirm this issue?

**Comment by kannes** [comment]
It is kinda hard to reproduce, I did not manage to get artifacts as blatant as in 2017 in EPSG:3031 but I got this in EPSG:3035 just by moving the canvas a tiny bit, no rotation involved. You can see the gap at ~12 o'clock. Reproducing it might depend on exact extents and shape of the canvas I guess.


![gap](https://user-images.githubusercontent.com/7661092/155179636-33cc5f50-5e65-4ba6-b7b0-cc3b28c59fc4.png)

![no gap](https://user-images.githubusercontent.com/7661092/155179640-bc899721-b115-4e54-be40-f25869661335.png)

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>


QGIS version | 3.25.0-Master | QGIS code revision | f3657c88601
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.10.2
GDAL/OGR version | 3.5.0dev-6e6aff451d-dirty
PROJ version | 8.2.0
EPSG Registry database version | v10.038 (2021-10-21)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.37.2
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.2.0
QScintilla2 version | 2.13.1
OS version | Arch Linux
  |   |   |  
This copy of QGIS writes debugging output.
  |   |   |  
...

</body></html>

**Comment by kannes** [comment]
Sorry, forgot the file: https://transfer.sh/RvxNKf/Allstorms.ibtracs_all_points.v03r09.zip will be online for two weeks. I can re-upload it any time.

**Comment by gioman** [comment]
> but I got this in EPSG:3035 just by moving the canvas a tiny bit, no rotation involved.

@kannes you are reprojecting a dataset in a global CRS, and with data all over the globe, into a "local" (europe) CRS. That you get some artifact is pretty much expected, especially for the data that is on the other side of the globe compared to the boundaries of validity of the CRS of the project.

![image](https://user-images.githubusercontent.com/1951107/155181402-e3ff6358-25a5-403e-8178-4c6dbb0e26d3.png)

**Comment by kannes** [comment]
Good call! But I managed to reproduce this in a orthographic projection as well:
`+proj=ortho +lat_0=39 +lon_0=139 +x_0=0 +y_0=0 +a=6371000 +b=6371000 +units=m +no_defs`

![gaps](https://user-images.githubusercontent.com/7661092/155184877-2b6885c4-ade0-4aa8-926b-a997fcaf20c0.gif)

**Comment by gioman** [comment]
> Good call! But I managed to reproduce this in a orthographic projection as well:

@kannes maybe you are onto something, but still is unrelated to this ticket, I think.

**Comment by kannes** [comment]
Hm, are you sure? To me it seems like it could be the same issue. Maybe we would just need to update the title? Otherwise I'd say close this one and I will open a new one with "features near the anti-meridian not getting rendered"

**Comment by gioman** [comment]
> Hm, are you sure? To me it seems like it could be the same issue. Maybe we would just need to update the title? Otherwise I'd say close this one and I will open a new one with "features near the anti-meridian not getting rendered"

@kannes no rotation involved in what you show in the last image you posted. I'll say new ticket and close this one.

**Comment by kannes** [comment]
No problem, I will make a new issue for the identified remaining problem tomorrow :)
