### ISSUE TITLE
Expose processing's densify to geometry generator

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#24853]
Author Name: **Johannes Kroeger** (Johannes Kroeger)
Original Redmine Issue: [16954](https://issues.qgis.org/issues/16954)

Redmine category:symbology

---
I would love to be able to densify geometries when using the geometry generator in styling. Please expose Processing's Densify algorithm as function there.

**Comment by antoniolocandro** [comment]
I would like to put a nudge on this, referencing this https://github.com/qgis/QGIS/issues/45810

I could try to get the effect I am looking by using a geometry generator bounds($geometry), however changing projections will require the ability to do densification prior to rendering

![image](https://user-images.githubusercontent.com/4627073/140077743-6f098e3d-e0f7-401a-ae57-40bad741bf4c.png)
