### ISSUE TITLE
Add blending modes for layer groups

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#24860]
Author Name: **Johannes Kroeger** (Johannes Kroeger)
Original Redmine Issue: [16961](https://issues.qgis.org/issues/16961)

Redmine category:symbology

---
At the moment layer blending modes apply throughout all layers.

It would be great if we could limit them to layer groups, so that an affect achieved by blending a certain group of layers would not further affect other layers.

It would be great if we could also set one specific blending mode on the layer group itself.

This would make the use of blending modes for styling much more versatile.

**Comment by nyalldawson** [comment]
This was implemented for 3.24
