### ISSUE TITLE
Unresponsive ArcGis MapServer layer makes QGIS eat CPU after being closed

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#24891]
Author Name: **Johannes Kroeger** (Johannes Kroeger)
Original Redmine Issue: [16992](https://issues.qgis.org/issues/16992)
Affected QGIS version: 3.6.0
Redmine category:web_services_clients/arcgis
Assignee: Sandro Mani

---
Layers -> Add Layer -> Add ArcGIS Mapserver Layer and use this URL http://www.geoportal.lt/inspire-services/rest/services/INSPIRE/Transport_networks_CommonTransportElements/MapServer
Then connect to it and add any of the layers.
Then close QGIS while it tries to fetch imagery from the server (it is timing out for me).

QGIS' window will vanish but QGIS keeps running in the background. At some point it starts eating all CPU with 3 threads for me. Ctrl-C won't kill it, I had to @kill -9@.

This is my pstree in such moment and I attached strace to the process to see what is going on:
```
  │   ├─bash(21710)───qgis(24443)─┬─{qgis}(24445)
  │   │                           ├─{qgis}(24474)
  │   │                           ├─{qgis}(24476)
  │   │                           ├─{qgis}(24477)
  │   │                           ├─{qgis}(24480)
  │   │                           ├─{qgis}(24481)
  │   │                           ├─{qgis}(24482)
  │   │                           └─{qgis}(24483)

1. strace -p 24443
strace: Process 24443 attached
futex(0xf0e396230, FUTEX_WAIT_PRIVATE, 0, NULL^Cstrace: Process 24443 detached
 <detached ...>
1. strace -p 24445
strace: Process 24445 attached
select(5, [4], NULL, NULL, NULL^Cstrace: Process 24445 detached
 <detached ...>
1. strace -p 24476
strace: Process 24476 attached
restart_syscall(<... resuming interrupted restart_syscall ...>^Cstrace: Process 24476 detached
 <detached ...>
1. strace -p 24477
strace: Process 24477 attached
restart_syscall(<... resuming interrupted restart_syscall ...>^Cstrace: Process 24477 detached
 <detached ...>
1. strace -p 24482
strace: Process 24482 attached
restart_syscall(<... resuming interrupted restart_syscall ...>^Cstrace: Process 24482 detached
 <detached ...>
1. strace -p 24483
strace: Process 24483 attached
restart_syscall(<... resuming interrupted restart_syscall ...>^Cstrace: Process 24483 detached
 <detached ...>

```

Those always only gave that one line, nothing else.
The other three processes however are throwing the following lines over and over again.

```
24474:	poll([{fd=18, events=POLLIN}, {fd=20, events=POLLIN}], 2, 0) = 1 ([{fd=20, revents=POLLIN|POLLERR|POLLHUP}])
24480:	poll([{fd=25, events=POLLIN}, {fd=26, events=POLLIN}], 2, -1) = 1 ([{fd=26, revents=POLLIN}])
24481:	poll([{fd=27, events=POLLIN}, {fd=28, events=POLLIN}], 2, -1) = 1 ([{fd=28, revents=POLLIN}])

```

I tried replicating this in QGIS master but there clicking "Add" for the layers did not result in anything. :o)

**Comment by Pedro-Murteira** [comment]
I can replicate the crash, it happens while trying to add single layers into the project. Sometimes QGIS simply crashes and sometimes it becomes unresponsive, causing a timeout. I could not reproduce the CPU usage part. (QGIS 3.22.3.)

**Comment by nyalldawson** [comment]
Is this still reproducible using the original description? Ie arcgis mapserver layers? I'm unable to reproduce on current supported versions
