### ISSUE TITLE
Enabling more options in the dialog when exporting PDF or Image from Map Composer

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#24943]
Author Name: **Juraj Betak** (@jurajbetak)
Original Redmine Issue: [17044](https://issues.qgis.org/issues/17044)

Redmine category:map_composer/printing

---
QGIS > Map Composer > Export as image > *.TIF
QGIS > Map Composer > Export as PDF > *.PDF

It would be nice to set e.g. compression type of my exported map to TIF or PNG, or set compression level when saving to JPG, or more settings for PDF export (namely handling fonts, text to curves, compression and/or downsampling for bitmaps, etc.)
Already discussed on forums:
https://gis.stackexchange.com/questions/123585/save-map-in-raster-format-from-qgis-using-compression
https://gis.stackexchange.com/questions/252760/how-to-apply-compression-e-g-lzw-when-exporting-a-map-from-qgis-composer-to-t

**Comment by alexbruy** [comment]
Duplicates #20014.
