### ISSUE TITLE
Add some examples to the collect function

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#24962]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [17063](https://issues.qgis.org/issues/17063)

Redmine category:expressions

---
The collect function in expression dialog has an example that is almost the description and doesn't help to understand what you can do with it and how. More examples could be nice. Thanks

**Comment by suricactus** [comment]
I disagree, the example is quite clear.

If the current layer has 3 elements, then the result will be:
```
geom_to_wkt(collect(make_point(1,2))) 
-- results in: 'MultiPoint ((1 2),(1 2),(1 2))'
```
