### ISSUE TITLE
Customize composer keyboard shortcuts

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25011]
Author Name: **Juraj Betak** (@jurajbetak)
Original Redmine Issue: [17112](https://issues.qgis.org/issues/17112)

Redmine category:map_composer/printing
Assignee: Nyall Dawson

---
Settings - Configure shortcuts  … does not include composer tools.
Is it possible to customize it here or some other place?

**Comment by YoannQDQ** [comment]
Implemented since QGIS 3.30
