### ISSUE TITLE
master using too much memory

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25018]
Author Name: **Patrick Dunford** (@enzedrailmaps)
Original Redmine Issue: [17119](https://issues.qgis.org/issues/17119)
Affected QGIS version: master
Redmine category:map_canvas

---
I have a project with about a thousand layers including currently about 600 raster images totalling about 6 GB. These are not fixed layers, I just open some aerial photos for the area I am currently mapping, so I can have a variable number of rasters open at any one time.

If I open this in a January build e.g. 313ec55 it uses about 5 GB of memory in the gui editor.

If I open it in the latest nightly 1caaa2e it uses 19 GB of memory with 433 of the rasters displayed. The VM only has 12 GB physical ram so it starts paging like crazy.

If I turn off displaying the aerial images in the gui it drops memory usage massively.

This looks like the composer issue, loading all the layers in memory even if they aren't actually needed.

If there is an expectation of loading all the layers into memory to speed up refresh, we need a setting to be able to turn this behaviour on or off, as for projects with very large amounts of data, the disk paging needed to deal with the large memory allocation obviates any benefit from refreshing layer data from memory instead of disk.

**Comment by roya0045** [comment]
Still valid?

**Comment by gioman** [comment]
Closing for lack of feedback.

**Comment by wanghai1988** [comment]
The latest version of this problem still exists
