### ISSUE TITLE
Editing behavior of filtered layers is inconsistent

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25023]
Author Name: **Giovanni Manghi** (@gioman)
Original Redmine Issue: [17124](https://issues.qgis.org/issues/17124)
Affected QGIS version: 3.2.2
Redmine category:vectors

---
Seen on 2.14, 2.18 and master.

Add a shapefile
Set a filter > vector continues editable
Save project, close project and reopen it > layer is not editable
Clear filter > still not editable
Save project, close project and reopen it > layer editable

---

Related issue(s): #25092 (duplicates), #25143 (relates), #27524 (relates)
Redmine related issue(s): [17193](https://issues.qgis.org/issues/17193), [17245](https://issues.qgis.org/issues/17245), [19699](https://issues.qgis.org/issues/19699)

---

**Comment by gioman** [comment]
Does not seems to be the case anymore.
