### ISSUE TITLE
CGAL in QGIS

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25034]
Author Name: **Bernardo Chrispim Baron** (Bernardo Chrispim Baron)
Original Redmine Issue: [17135](https://issues.qgis.org/issues/17135)

Redmine category:c++_plugins

---
The "Computational Geometry Algorithms Library (CGAL)":https://www.cgal.org provides some complex geometric computations, many of which are not included in any of QGIS' current toolboxes despite being quite useful for geographic analysis (e.g. "triangulations, voronoi diagrams, boolean operations, point set processing, arrangements of curves, surface and volume mesh generation, geometry processing, alpha shapes, convex hull algorithms, shape analysis, AABB and KD trees"). It is "licensed under GPL and LGPL":https://www.cgal.org/license.html and written in C++ with python bindings, so I imagine its packages would be relatively easy to implement in QGIS as a plugin or toolbox.

**Comment by alexbruy** [comment]
This feature request should be filed against OSGeo4W tracker at [https://trac.osgeo.org/osgeo4w](https://trac.osgeo.org/osgeo4w).
