### ISSUE TITLE
DB Manager only shows some type of rasters

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25040]
Author Name: **Giovanni Manghi** (@gioman)
Original Redmine Issue: [17141](https://issues.qgis.org/issues/17141)
Affected QGIS version: 3.3(master)
Redmine category:db_manager

---
This was observed on master with ones of the GPKG samples:

http://www.geopackage.org/data/gdal_sample_v1.2_spi_nonlinear_webp_elevation.gpkg

See attached image, as you can see only certain type of rasters (byte?) are shown in DB Manager while the others show only in browser.

---

- [Screenshot_20170914_115618.png](https://issues.qgis.org/attachments/download/11412/Screenshot_20170914_115618.png) (Giovanni Manghi)
- [Screenshot-2018-09-25-13-48-26.png](https://issues.qgis.org/attachments/download/13351/Screenshot-2018-09-25-13-48-26.png) (Loïc BARTOLETTI)

**Comment by gioman** [comment]
Works fine now.
