### ISSUE TITLE
Georeferencer seems properly not to close the opened file handle after closing georef window, open a new file, even create new or open another project.

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25056]
Author Name: **sand thorn** (sand thorn)
Original Redmine Issue: [17157](https://issues.qgis.org/issues/17157)
Affected QGIS version: 3.4.4
Redmine category:c++_plugins/georeferencer

---
How to reproduce:
1. Open Georeferencer.
2. Open a raster.
3. From this point, the file handles stay held forever until application exits.
  -  Reset georefence/open another file/close window/new project: don't affect existing of file handles.
  -  One can not move/rename/write the file.

This can be considered a minor pet peeve, when you want to move things around after that.

Suggestions:
Release file handle on 
- menu command
- close georeferencer window 
would be convenient.

**Comment by alexbruy** [comment]
Please test with latest master.

**Comment by alexbruy** [comment]
Closed for the lack of feedback. Please reopen if necessary.
