### ISSUE TITLE
Rubber band is not correctly displayed when map is rotated

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25095]
Author Name: **Loïc BARTOLETTI** (@lbartoletti)
Original Redmine Issue: [17196](https://issues.qgis.org/issues/17196)
Affected QGIS version: 3.5(master)
Redmine category:map_canvas

---
When you draw complex geometry (especially with Circular string), the rubber band is not correctly displayed when map is rotated and especially when the map have many objects or rasters.

What I mean by not correctly displayed is the presence of artefact or broken line/curve.

Tested with QGis 2.18 Windows and QGis 2.99 Debian

---

- [Sans titre.png](https://issues.qgis.org/attachments/download/11451/Sans%20titre.png) (Loïc BARTOLETTI)
- [circularringartefacts.png](https://issues.qgis.org/attachments/download/11551/circularringartefacts.png) (Richard Duivenvoorde)

**Comment by Pedro-Murteira** [comment]
Still an issue on QGIS 3.16.14 and 3.22.1.
