### ISSUE TITLE
Turning Multi edit mode off does not go back to table view

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25099]
Author Name: **Alexandre Neto** (@SrNetoChan)
Original Redmine Issue: [17200](https://issues.qgis.org/issues/17200)
Affected QGIS version: master
Redmine category:attribute_table

---
In the attribute table, If the user starts a multi edit mode session while in table view, when he turns it off, the attribute table will end up in Form view instead.

I think the right UX behaviour would be for the multi edit mode to remember the view mode the user was using before.

!anim.gif!

This affects both master and QGIS 2.18.

---

- [anim.gif](https://issues.qgis.org/attachments/download/11455/anim.gif) (Alexandre Neto)

**Comment by SrNetoChan** [comment]
This still happens in QGIS 3.9. @gioman can you remove the feedback label, please?

**Comment by SrNetoChan** [comment]
Can you add the GUI\UX label as well?
