### ISSUE TITLE
Oracle Table list acting strange

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25113]
Author Name: **Richard Duivenvoorde** (@rduivenvoorde)
Original Redmine Issue: [17214](https://issues.qgis.org/issues/17214)
Affected QGIS version: 3.4.5
Redmine category:data_provider/oracle
Assignee: Jürgen Fischer

---
Testing viewing Oracle tables here in current master 6cd8b4c83e

After making a succesfull connection you get presented a (tree) table of all layers.

Some strange things happening here:

- if your table does not have a primary key (that is the column Primary key column is emtpy), you can double click in the cell (of that table): you are then presented with a Query Builder window, BUT adding a Field name then does not work. Looks like there should not be a Query Builder there?

- if you click one row (select a table), then the Add button will be enabled. BUT if you select click another row, it is ADDED to the selection (so you have to rows selected)
I think that is strange, normally you select another row, and maybe can add rows to the selection by using the shift button or so?

- if you have 2 rows selected, and DEselect one row, then the 'Add' button is disabled and connot be used anymore... selecting a second row again enables the button...
Looks like the enabling/disabling is not in sync with what you see?

---

- [oraclemsg.png](https://issues.qgis.org/attachments/download/11482/oraclemsg.png) (Richard Duivenvoorde)
- [oraclemsg2.png](https://issues.qgis.org/attachments/download/11483/oraclemsg2.png) (Richard Duivenvoorde)

**Comment by Pedro-Murteira** [comment]
@rduivenvoorde Hello, is this still valid on recent releases?

**Comment by rduivenvoorde** [comment]
Mmm, have to find an Oracle db for that to test...
Will come back here...

**Comment by rduivenvoorde** [comment]
Ok, just checked, and it now looks much better.
As you can see on the screenies, QGIS was working on an older WindowsServer machine, now they have Win10 like servers, and the rows/tree behave OK.
Let's close it.
