### ISSUE TITLE
Better error reporting within Expressions

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25114]
Author Name: **Tim Hancock** (Tim Hancock)
Original Redmine Issue: [17215](https://issues.qgis.org/issues/17215)

Redmine category:expressions

---
This is not strictly a bug report. More it is a request to improve the error reporting within Expressions. When an Expression fails, the Expression will stop without providing any details of the error (or that it has stopped). If the details of the error can be provided in some manner, it would greatly assist in debugging. An example would be a type conversion failure when trying to assign a float to an int.

**Comment by alexbruy** [comment]
Should be fixed in master, please check.
