### ISSUE TITLE
llvm-5 compiler selection fails on OS X

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25115]
Author Name: **David Liontooth** (David Liontooth)
Original Redmine Issue: [17216](https://issues.qgis.org/issues/17216)
Affected QGIS version: master
Redmine category:build/install

---
On an up-to-date OS X Sierra, using QGIS git master and MacPorts' llvm-5.0 , I set the compilers:

  export CC=/opt/local/libexec/llvm-5.0/bin/clang
  export CXX=/opt/local/libexec/llvm-5.0/bin/clang++

Configure is happy -- up to a point:

-- The C compiler identification is Clang 5.0.0
-- The CXX compiler identification is Clang 5.0.0
-- Check for working C compiler: /opt/local/libexec/llvm-5.0/bin/clang
-- Check for working C compiler: /opt/local/libexec/llvm-5.0/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/local/libexec/llvm-5.0/bin/clang++
-- Check for working CXX compiler: /opt/local/libexec/llvm-5.0/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done

But then complains:

  CMake Error in src/core/CMakeLists.txt:
  No known features for CXX compiler

  "Clang"

  version 5.0.0.

What am I doing wrong?

**Comment by nyalldawson** [comment]
Closing due to lack of feedback
