### ISSUE TITLE
Create an empty Geopackage DB

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25116]
Author Name: **shenriod -** (shenriod -)
Original Redmine Issue: [17217](https://issues.qgis.org/issues/17217)

Redmine category:browser

---
Currently it is not possible to create an empty Geopackage DB. One can only create a new layer in a (new or existing) Geopackage DB. There are cases where I don't want to create a new layer. I only want to create an empty Geopackage, so that I can later, e.g., import a bunch of shapefiles into it.
 
Of course, I can create a geopackage layer and delete it later, but this is not super intuitive for the users

Discussion here: https://lists.osgeo.org/pipermail/qgis-user/2017-September/040774.html 
General call for features reparding support of Geopackage: https://docs.google.com/document/d/1xp36eR0DYThpTCNsWUam5JhFKVjOVpmRObwWSPjkrbc/edit#

**Comment by rendzina** [comment]
Was this ever resolved? It would be a useful feature.

**Comment by elpaso** [comment]
If it would, this issue would probably be closed.

**Comment by jubilee2** [comment]
this is work for me on 3.10
```python
processing.run("native:package", {'LAYERS':[],'OUTPUT':'C:/gis/gis.gpkg','OVERWRITE':False,'SAVE_STYLES':True})
```
