### ISSUE TITLE
Snap is offseted when the map is rotated

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25136]
Author Name: **Loïc BARTOLETTI** (@lbartoletti)
Original Redmine Issue: [17237](https://issues.qgis.org/issues/17237)
Affected QGIS version: 3.5(master)
Redmine category:digitising

---
When you want snap a segment and the map is rotated, the highlighted segment have an offset (seems to be the higher the value of the rotation is, the higher the offset is.)

Tested with QGis 2.18 and master

---

- [Sans titre.png](https://issues.qgis.org/attachments/download/11506/Sans%20titre.png) (Loïc BARTOLETTI)

**Comment by uclaros** [comment]
@lbartoletti I can't reproduce this, can you still?

**Comment by Pedro-Murteira** [comment]
@lbartoletti same as @uclaros I can't also replicate this on QGIS 3.16.15 and 3.22.2.
