### ISSUE TITLE
use a selection as input for a Query Builder

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25139]
Author Name: **Mike Cusi** (Mike Cusi)
Original Redmine Issue: [17241](https://issues.qgis.org/issues/17241)

Redmine category:expressions

---
I would like to be able to use my current selection to create a filter I can use in query builder to display only the selected records/features.

**Comment by brulien** [comment]
This feature would be really usefull to get easily a subset of layers with huge number of features ...

**Comment by alexbruy** [comment]
Duplicates #21832.
