### ISSUE TITLE
"orig_ogc_fid" field is added to filtered shapefiles in QGIS master

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25143]
Author Name: **Patrick Dunford** (@enzedrailmaps)
Original Redmine Issue: [17245](https://issues.qgis.org/issues/17245)
Affected QGIS version: master
Redmine category:vectors

---
*new description:*
when filtering a shapefile in QGIS master a new field "orig_ogc_fid" is "added" to the table. This goes away when the filter is removed.

*old description:*
Could not commit changes to layer cwnmVariableYards

Errors: ERROR: 1 feature(s) not added.
  
  Provider errors:
      OGR error creating feature -2: 

also when adding the new feature an extra field is displayed on the form which is called orig_ogc_fid, I don't know what this field is used for or why it is displayed.

---

- [17245.7z](https://issues.qgis.org/attachments/download/11511/17245.7z) (Patrick Dunford)

---

Related issue(s): #25023 (relates)
Redmine related issue(s): [17124](https://issues.qgis.org/issues/17124)

---

**Comment by gioman** [comment]
None of the issues discussed here seems to be relevant anymore.
