### ISSUE TITLE
QGIS 3 vertex editor problems

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25141]
Author Name: **Andreas Neumann** (@andreasneumann)
Original Redmine Issue: [17243](https://issues.qgis.org/issues/17243)
Affected QGIS version: 3.5(master)
Redmine category:editing

---
In QGIS 3, the behaviour of the vertex editor panel, has been changed in conjunction with the refactoring of the interactive node editing on canvas.

However, the usability of the built-in node editor panel (the one with the list of coordinates) suffered a lot.

Currently I see the following issues:

* Vertex editor does not automatically open as it did in 2.18. It can be discussed if the automatic opening of the panel as it happened in 2.18 is useful, because most of the time users don't need exact coordinates, but if this behaviour is changed, the user should at least be able to open the panel on demand from the list of available panel. The vertex editor panel is not in this list currently.
* In QGIS 2.18 if a vertex is interactively selected in the canvas, the list in the vertex editor list scrolls to the selected vertex index and highlights the coordinates of the selected vertex - otherwise the use doesn't know which coordinate he is actually editing. In QGIS 3 this scrolling and highlighting of the coordinates in the list does not work anymore.
* In QGIS 3, the vertex editor panel autocloses as soon as another vertex is selected. Very annoying and makes the editor quite unusable.

---

Related issue(s): #27735 (relates)
Redmine related issue(s): [19911](https://issues.qgis.org/issues/19911)

---

**Comment by uclaros** [comment]
Issue 2 is also fixed. I guess this can close.

**Comment by gioman** [comment]
All the the three described issues seem fixed to me, please reopen if necessary.
