### ISSUE TITLE
New node tool snapping index out of sync for transaction groups (and triggers in the DB)

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25142]
Author Name: **Regis Haubourg** (@haubourg)
Original Redmine Issue: [17244](https://issues.qgis.org/issues/17244)
Affected QGIS version: 3.4.2
Redmine category:editing

---
Hi, 
This is something that happened in the past I guess. 

When playing with new node tool with database updating other features than the currently edited one, 
the snapping index is quickly out of sync. It worked correctly in 2.18 (issue was in 2.16 IIRW)

See the video here: [[https://youtu.be/Miex5XarR3g]]

---

- [bug_17244.sql](https://issues.qgis.org/attachments/download/12303/bug_17244.sql) (Regis Haubourg)
- [17244_node_index_broken.qgs](https://issues.qgis.org/attachments/download/12304/17244_node_index_broken.qgs) (Regis Haubourg)

**Comment by troopa81** [comment]
@mhugo I close this ticket since circular dependencies are now possible.
