### ISSUE TITLE
Choosing 'layer_styles' schema

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25163]
Author Name: **Frédéric CLOITRE** (@lpofredc)
Original Redmine Issue: [17265](https://issues.qgis.org/issues/17265)

Redmine category:data_provider

---
For projects with shared spatial databases, it would be interesting to add the ability to choose the default schema to store the layer_styles table. In cases where each user has his own schema, there is no direct possibility to share the styles saved by default. layer_styles is created independently in each of the user shcemas.

In my situation, I had to work around this constraint by creating views of a single public.layer_styles table for each user and automatically executed rules for the insert, update, delete actions to automatically save the new data in the main table public.layer_styles (cf. attachement). Regarding to source code: https://github.com/qgis/QGIS/blob/8deed6c49742bf01d4d49a369fe52a7100fcf107/src/providers/postgres/qgspostgresprovider.cpp

Sincerely.

---

- [qgis_layer_style.sql](https://issues.qgis.org/attachments/download/11533/qgis_layer_style.sql) (Frédéric CLOITRE)

**Comment by gioman** [comment]
Duplicates: https://github.com/qgis/QGIS/issues/38617
