### ISSUE TITLE
QGIS crashes when trying to save edits on Oracle Spatial layers added using the OGR drivers (not the native provider)

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25209]
Author Name: **Giovanni Manghi** (@gioman)
Original Redmine Issue: [17311](https://issues.qgis.org/issues/17311)
Affected QGIS version: 3.5(master)
Redmine category:data_provider/ogr

---
Subject says it all. No crash if the same layer is edited with the native Oracle provider.

Also with the OGR driver the layers do not seems to load all features when zooming at full extent. If zooming in all expected features are drawn. Again this does not happen is loading the layer with the native provider.

**Comment by alexbruy** [comment]
@gioman is this still an issue with latest LTR/master?
