### ISSUE TITLE
Change default setting to 'Checked' for Processing Options "Use filename as layer name" 

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25201]
Author Name: **Steve Lowman** (Steve Lowman)
Original Redmine Issue: [17303](https://issues.qgis.org/issues/17303)

Redmine category:processing/core
Assignee: Victor Olaya

---
The 2.14 ftools in the Vector menu always set the layer name to be the same as the file name, which seems more sensible than the other option.

The Processing tools now in the Vector menu follow the Processing Option "Use filename as layer name", which is currently has a default setting of 'Unchecked'. Many users will not easily find the Processing Option to change this. (Currently, if they do find this possibility, they will then encounter the bug reported in #24338 but this is another issue)

I suggest changing the default setting to 'Checked' for "Use filename as layer name" will be better for most users.

**Comment by alexbruy** [comment]
Duplicates #20840
