### ISSUE TITLE
Current implementation of multiple-layer style paste doesn't work for the command menu "Layer / Paste Style".

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25214]
Author Name: **sand thorn** (sand thorn)
Original Redmine Issue: [17316](https://issues.qgis.org/issues/17316)
Affected QGIS version: 3.4.4
Redmine category:gui

---
I'm not sure this should be categorized as a bug or just a feature request.

from a closed feature request: #18748
*copy/paste style for multiple layers*

It seems that this got implemented only through tree view menu (right-click)

But when using menu "Layer / Paste Style", it only pastes on the latest select layer, and if you select a group, Paste command is just grayed out.

If the menu command also works, you will be able to just map a keyboard shortcut to Paste on multiple selected or group selected. That would be awesome.

Thank you.

**Comment by Pedro-Murteira** [comment]
This is still a valid issue using QGIS 3.16.15 and 3.22.2. Right click > style > paste style works on multiple layers just fine. Layer Menu > Paste style only pastes on the last selected layer.
