### ISSUE TITLE
3D Viewer: QGIS Crash when activating 3D Map view and 3D renderer

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25213]
Author Name: **Luca Casagrande** (Luca Casagrande)
Original Redmine Issue: [17315](https://issues.qgis.org/issues/17315)
Affected QGIS version: master
Redmine category:3d

---
QGIS cc96f51e62 Installed with OSGeo4W64

* Load test data (but any other data didn't work for me)
* Start the New 3D Map View
* Enable 3D renderer in the Layer Styling Panel

The crash report window will open without any contents.
QGIS Main window does not respond.

---

- [test3d.zip](https://issues.qgis.org/attachments/download/11575/test3d.zip) (Luca Casagrande)

---

Related issue(s): #25313 (relates), #25684 (duplicates), #25848 (duplicates), #26163 (duplicates), #27052 (duplicates), #27490 (duplicates), #27714 (duplicates), #28564 (relates)
Redmine related issue(s): [17416](https://issues.qgis.org/issues/17416), [17788](https://issues.qgis.org/issues/17788), [17952](https://issues.qgis.org/issues/17952), [18272](https://issues.qgis.org/issues/18272), [19223](https://issues.qgis.org/issues/19223), [19665](https://issues.qgis.org/issues/19665), [19890](https://issues.qgis.org/issues/19890), [20744](https://issues.qgis.org/issues/20744)

---

**Comment by gioman** [comment]
Closing for the lack of feedback.

**Comment by pjshelton** [comment]
## User Feedback

I open QGIS, I load in one dem tiff, and one point feature layer.  the point layer is x,y,z with the z value 0 in all points.  With the 3D symbology as none I open a 3D view.
This works fine, I can zoom, pan, tilt, and view my dem and points.

I then set the terain dialog to dem, and set it to the dem tiff loaded earlier.  This still works fine.  and I can still zoom and pan and tilt the 3D view. 

I close the 3D view, and set the 3D symbology to a cilinder diameter of 100 and hight of 200, (as my dem is only 1000x1000 metres this makes it easy to spot the points in the 3D view. 
I open a 3D view and my dem and the points are all rendered, I go and set the terain to the dem and QGIS crashes.

## Report Details

**Crash ID**: [fac13d67e9b37fe59242a5fff76427ac01c35861](https://github.com/qgis/QGIS/search?q=fac13d67e9b37fe59242a5fff76427ac01c35861&type=Issues)


**Stack Trace**
<pre>
QVector<QPointF>::first :
QgsDemHeightMapGenerator::heightAt qgsdemterraintileloader_p.cpp:293
Qgs3DUtils::extractPointPositions qgs3dutils.cpp:357
QgsInstancedPoint3DSymbolHandler::processFeature qgspoint3dsymbol_p.cpp:113
<lambda_658571170e9bb80885fc69fa9096f85e>::operator() qgsvectorlayerchunkloader_p.cpp:100
QtConcurrent::RunFunctionTask<void>::run qtconcurrentrunbase.h:136
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>


**QGIS Info**
QGIS Version: 3.14.0-Pi
QGIS code revision: 9f7028fd23
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763
