### ISSUE TITLE
When using rule based labels the caption cannot be centred on a polygon feature

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25236]
Author Name: **Patrick Dunford** (@enzedrailmaps)
Original Redmine Issue: [17339](https://issues.qgis.org/issues/17339)
Affected QGIS version: master
Redmine category:labelling

---
I have a few layers with polygons that use a caption with a single letter. When the layer has just a single label for every polygon then I can centre the label and it looks good. If I switch the layer to use rule based captioning the label cannot be centered. See the sample photos attached.

---

- [Oma1M-313ec55.png](https://issues.qgis.org/attachments/download/11597/Oma1M-313ec55.png) (Patrick Dunford)
- [Oma1M-6297d19.png](https://issues.qgis.org/attachments/download/11598/Oma1M-6297d19.png) (Patrick Dunford)

**Comment by nyalldawson** [comment]
Closed due to lack of feedback
