### ISSUE TITLE
Right clicking layer in canvas causes zoom out to 1,000,000

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25245]
Author Name: **Patrick Dunford** (@enzedrailmaps)
Original Redmine Issue: [17348](https://issues.qgis.org/issues/17348)
Affected QGIS version: master
Redmine category:map_canvas

---
In my project I am right clicking on the names of the layers in the layer list to view or change layer properties. When I do this, very often the zoom level on the canvas will suddenly go right out to over 1:1,000,000.

This is observed with the master 6297d19 but not with earlier ones such as 313ec55.

---

- [qgis2.mp4](https://issues.qgis.org/attachments/download/11602/qgis2.mp4) (Patrick Dunford)

**Comment by roya0045** [comment]
This seems fixed in 3.12

**Comment by gioman** [comment]
Closing for lack of feedback.
