### ISSUE TITLE
Draw Effects not saved

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25255]
Author Name: **Jeffrey Bostoen** (Jeffrey Bostoen)
Original Redmine Issue: [17358](https://issues.qgis.org/issues/17358)
Affected QGIS version: 3.4.4
Redmine category:project_loading/saving

---
I'm using QGIS 2.18.13. Been working on a project for some hours now. 
I had some project filec orruptions - not sure what the issue there is, assuming virtual layers.

But here's a bug I can reproduce easily in my current project.
I have a virtual layer (currently simply selects all features from a shapefile layer. I'm using this because I want to be able to set a filter on the shapefile layer and have it applied on several layers at once). 
In this layer, I'm using categorized symbols.
The symbol is in fact a Geometry Generator, generating a polygon.

Now, whenever I go to Geometry Generator -> Fill -> Simple Fill and set draw effects, they're applied.
Same goes for just applying the draw effect on the Geometry Generator.

I save the project.
I reopen the project. 
Draw filter is gone, whether I set it on the actual generator or on the fill.

---

- [style_issue.png](https://issues.qgis.org/attachments/download/14411/style_issue.png) (Alessandro  Cristofori)

**Comment by geomondego** [comment]
working with Win10 and QGIS 3.16.3

**Comment by gioman** [comment]
Closing for lack of feedback.
