### ISSUE TITLE
Node Tool Selects Invisible Objects

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25259]
Author Name: **Ryan Desmond** (@rddesmond)
Original Redmine Issue: [17362](https://issues.qgis.org/issues/17362)
Affected QGIS version: master
Redmine category:editing

---
The node tool, selection happens without regard to the visibility of the object.  In the simple case (procedure 1), you can simply set the layer to invisible and show that object selection is still possible.  In a more complex case (procedure 2), a portion of a layer is made invisible (with categorized style rules).

With the existing node tool, procedure one is a bit unnatural, because you can only select features on the currently selected layer.  The second procedure is a much more natural use case. 
 One or both of these cases may be OBE by the new node tool in 3.0.

## Procedure 1:

1. Create a polygon scratch layer
1. Edit the layer
1. Select add feature and insert an object
1. Select the "Node Tool"
1. Toggle layer visibility to hide it
1. Click where a node would be on the newly hidden object

## Procedure 2:

1. Create a polygon scratch layer
1. Edit the layer
1. Select add feature and insert two objects
1. Select "Open Attribute table"
1. Add a new column and categorize each of the objects uniquely (e.g. 1, 2, ..)
1. Select the "Node Tool"
1. In Properties / Style, set the style to be categorized by the new column and hit "classify"
1. Unselect one of the categories
1. Click where a node would be on the newly hidden object

## Expected

Visible objects are selectable, but invisible objects are not.

## Actual

In both cases, the objects which aren't visible are selected to edit.

**Comment by AlisterH** [comment]
I have tested in 3.8.3 and this is still valid.
After step 9 in the Feb 26 procedure it is possible to delete the node in the invisible feature, or move it if you selected it together with a node in a visible feature.  I think it may not be possible to move it by itself.

**Comment by haubourg** [comment]
confirmed. Deletion of nodes is still possible for invisible classes. But you can explicitly select and view this node. So, is it a bug or a feature? IMO it's not that clear.

**Comment by AlisterH** [comment]
I think it is fair enough to call it a bug - it is counterintuitive and can get in the way of what the user is trying to do.

**Comment by andreasneumann** [comment]
I also think that this is a bug. In most cases it is unwanted behaviour and definitely very confusing for users.
