### ISSUE TITLE
Symbol needed in layer list for filter applied

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25251]
Author Name: **Patrick Dunford** (@enzedrailmaps)
Original Redmine Issue: [17354](https://issues.qgis.org/issues/17354)

Redmine category:map_canvas

---
For comparison, when a layer is put into edit mode, a yellow pencil symbol appears next to the layer's name.

Could it be possible to have a symbol that indicates a layer is filtered.

**Comment by phidrho** [comment]
@enzedrailmaps @gioman
this feature request can be closed, it's implemented a while ago
