### ISSUE TITLE
add space between grid frame and map in composer

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25293]
Author Name: **Gavin Fleming** (@gubuntu)
Original Redmine Issue: [17396](https://issues.qgis.org/issues/17396)

Redmine category:map_composer/printing

---
Many maps have a space between the graticule frame and the map. It would be really useful to have this as a configurable option in QGIS Composer. 

If there is a gap, it would be nice to then have more options for labelling - outside the frame, inside the map, inside the frame etc. 

In my case I am trying to emulate South African topographic maps, example attached or full image at http://i.imgur.com/UmIUPVA.jpg

---

- [Screen Shot 2017-11-03 at 16.23.25.png](https://issues.qgis.org/attachments/download/11635/Screen%20Shot%202017-11-03%20at%2016.23.25.png) (Gavin Fleming)

**Comment by nyalldawson** [comment]
Implemented as of QGIS 3.6
