### ISSUE TITLE
Enable custom color (ie expression or virtual attribute) to define style of lines in attribute table

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25303]
Author Name: **Mathieu Bossaert** (Mathieu Bossaert)
Original Redmine Issue: [17406](https://issues.qgis.org/issues/17406)

Redmine category:map_composer/printing

---
Good Moring,

In order to create reports with maps and table from the print composer, we would like to highlight some rows or cells in the attribute table.

Conditionnal formatting is great but does not exists on the print composer side.

For now I use a workaround by generating tables as html code on the database side but it's just a workaround with inconvinients

An "easy" step could be to allow the use of expression and/or field value in the table appearence dialog boxes as this one :
 
https://docs.qgis.org/2.18/en/docs/user_manual/print_composer/composer_items/composer_attribute_table.html#appearance

Thanks a lot for your attention

Mathieu Bossaert

**Comment by alexbruy** [comment]
Now layer conditional formatting can be used in the composer attribute tables.
