### ISSUE TITLE
Windows does not show unicode characters

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25301]
Author Name: **Matthias Kuhn** (@m-kuhn)
Original Redmine Issue: [17404](https://issues.qgis.org/issues/17404)
Affected QGIS version: master
Redmine category:gui

---
For constraint reporting unicode characters are used but they show up as ? on Windows.

It's probably a font issue.

---

- [image001.png](https://issues.qgis.org/attachments/download/11639/image001.png) (Matthias Kuhn)

**Comment by jdugge** [comment]
This works for me on Windows 10.0.18363 with QGIS 3.12.1

![image](https://user-images.githubusercontent.com/2399255/80311879-80b62200-87e2-11ea-8610-c9831b55fdab.png)
