### ISSUE TITLE
Custom Certificate Configuration on 2.99 on Ubuntu 17.10

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25342]
Author Name: **Randal Hale** (@rjhale1971)
Original Redmine Issue: [17445](https://issues.qgis.org/issues/17445)
Affected QGIS version: master
Redmine category:unknown

---
I just did a new install on Ubuntu 17.10 of QGIS 2.99. When I first start it I'm getting a Custom Certificate Configuration menu appearing and it's reporting an error: * Unable To Get Local Issuer Certificate: The issuer certificate of a locally looked up certificate could not be found and SSL Errors occurred accessing this URL: https://version.qgis.org/version.txt

I have libqca2-plugin-ossl installed. If I click abort QGIS starts fine. If I start QGIS again the Custom Certificate Configuration appears After QGIS starts (and not before). 

---

Related issue(s): #25480 (duplicates)
Redmine related issue(s): [17583](https://issues.qgis.org/issues/17583)

---

**Comment by BenjaminMichael** [comment]
This issue is valid for 3.8.3

**Comment by alexbruy** [comment]
Please check with 3.10 and/or master

**Comment by alexbruy** [comment]
Closing for the lack of feedback. Please reopen if necessary.
