### ISSUE TITLE
Layer symbology in layer panel behaves weirdly when the legend entries for diagram size with "Separated legend items" option is updated

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25359]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [17462](https://issues.qgis.org/issues/17462)
Affected QGIS version: master
Redmine category:diagrams

---
In Vector Layer Properties dialog --> Diagrams, set a pie chart diagram and add your fields
In the Size tab, set a variable size in order to enable in the Rendering tab, the "legend entries for diagram size" button
Click the legend entries button and open the Data-defined size legend
Select the "Separated legend items" and apply.
Click OK in the vector layer dialog.
Expand the layer in the Layers panel (as it should have been collapsed according to #25358)

Reopend the "Data-defined size legend" dialog and update the title. Validate.
You should lose the separated proportional symbols in the Layers panel: often I get some square sized symbols that progressively (click by click) or automatically (after i click outside QGIS) become what is shown in legendpreview2

Note that collapsing then Expanding the layer shows a clean legend with full symbols.

---

- [legendpreview2.PNG](https://issues.qgis.org/attachments/download/11684/legendpreview2.PNG) (Harrissou Santanna)

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.

**Comment by DelazJ** [comment]
Still valid on 3.9, with same workaround. @gioman 
Btw, I think it's more an issue with preview in the layers panel than symbology itself. So maybe the tag should be updated

**Comment by DelazJ** [comment]
> please reopen if necessary.

Please do! I (and many other old reports authors) have no mean to reopen "our" issues (@qgib took ownership :angry: )

**Comment by Pedro-Murteira** [comment]
@DelazJ I can replicate the first part of your report (as I have already stated in #25358), but not the rest, it seems to work out just fine. Either I'm missing a step here, or the issue is fixed. Could you give a try aswell? (Tested on Windows and macOS, QGIS 3.22.2.)

**Comment by alexbruy** [comment]
Can't reproduce with the latest master (a2643b801c9b3a765ce5e0fabd235762f25aa7fe).
