### ISSUE TITLE
Inconsistent behaviour of the preview frame in Data-defined size legend in Diagram properties

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25360]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [17463](https://issues.qgis.org/issues/17463)
Affected QGIS version: master
Redmine category:diagrams

---
Vector layer properties --> Diagrams --> Rendering --> Legend entries for diagram size (you need to use a compatible diagram such as pie chart, with variable size)
Select the Separated legend items
Click one of the items shown in the preview frame, if nothing happens click another one, and then and then. (sometimes, one click is enough)
At some point the different items you clicked on are merged to show a unique rectangular band in the preview frame, with no values shown.
Also note that the title disappeared.

---

- [preview_sizelegend.PNG](https://issues.qgis.org/attachments/download/11683/preview_sizelegend.PNG) (Harrissou Santanna)

**Comment by gioman** [comment]
@DelazJ seems fixed to me, correct?

**Comment by DelazJ** [comment]
I think so
