### ISSUE TITLE
Preview in Data-defined size legend dialog doesn't scale symbols size when separated legend items options is selected

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25361]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [17464](https://issues.qgis.org/issues/17464)
Affected QGIS version: master
Redmine category:diagrams

---
In Vector Layer Properties dialog --> Diagrams, set a pie chart diagram and add your fields
In the Size tab, set a variable size in order to enable in the Rendering tab, the "legend entries for diagram size" button
Click the legend entries button and open the Data-defined size legend

Select the "Separated legend items"
In the preview section the symbols are displayed as a square symbol.

I think the user would expect to see them the way they would be displayed in the legend, with real proportions and vertically aligned.

**Comment by gioman** [comment]
@DelazJ pretty much still true it seems, right?

**Comment by DelazJ** [comment]
@gioman I made a quick and dirty test and I can't confirm. The default circular marker symbol renders correctly, I got circles, they are correctly aligned. Seems fixed afaict.
