### ISSUE TITLE
An option to decrease/increase symbol at the end

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25403]
Author Name: **Alexey T** (@Xeenych)
Original Redmine Issue: [17506](https://issues.qgis.org/issues/17506)

Redmine category:symbology

---
For line features there is an option in OCAD to make symbol size decrease or increase along line.
This allows to make some cute graphics.
I would like to see similar option in QGIS.

---

- [1.jpg](https://issues.qgis.org/attachments/download/11713/1.jpg) (Alexey T)

**Comment by pjshelton** [comment]
@Xeenych
![image](https://user-images.githubusercontent.com/39154868/103446829-abd90580-4ccf-11eb-82d0-848484d66f7e.png)

As of at least 3.16 and earlier, this has been achievable.   To produce most of the effects you will have to use LinestringM.

There is geometry generator option for symbology and you can use the functions  tapered_buffer( $geometry, start_width, end_width) or  buffer_by_m( $geometry), or a Marker line where the the size of the  maker is data defined by m(  line_interpolate_point(  $geometry , @geometry_point_num*[same value as the interval size] ))

@gioman this one can be closed.

**Comment by gioman** [comment]
> @gioman this one can be closed.

@pjshelton thanks for checking all this (old) feature requests!
