### ISSUE TITLE
SaveAs Geopackage: TEXT fields are converted to TEXT(255)

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25405]
Author Name: **Richard Duivenvoorde** (@rduivenvoorde)
Original Redmine Issue: [17508](https://issues.qgis.org/issues/17508)
Affected QGIS version: 3.7(master)
Redmine category:data_provider/ogr

---

Connecting to a WFS like:
http://geozet.koop.overheid.nl/wfs?version=1.0.0&request=GetCapabilities
then >70000 features layer: geozet:bekendmakingen_punt

That data has one attribute 'beschrijving' (description) which as about 350 chars.
So when you save as GeoPackage you cannot set a size, so QGIS tells you:

Warning 1: Value of field 'beschrijving' has 274 characters, whereas maximum allowed is 255.
Warning 1: Value of field 'beschrijving' has 288 characters, whereas maximum allowed is 255.
Warning 1: Value of field 'beschrijving' has 284 characters, whereas maximum allowed is 255.
Warning 1: Value of field 'beschrijving' has 629 characters, whereas maximum allowed is 255.
Warning 1: Value of field 'titel' has 264 characters, whereas maximum allowed is 255.
Warning 1: Value of field 'beschrijving' has 264 characters, whereas maximum allowed is 255.
More than 1000 errors or warnings have been reported. No more will be reported from now.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

---

- [1Eh7xisXno](https://issues.qgis.org/attachments/download/11719/1Eh7xisXno) (Richard Duivenvoorde)

**Comment by rouault** [comment]
This issue has been fixed. There's no longer a 255 character limit
