### ISSUE TITLE
Windows: cannot save updates in csv file opened as OGR vector layer

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25421]
Author Name: **Olga Grabek** (Olga Grabek)
Original Redmine Issue: [17524](https://issues.qgis.org/issues/17524)
Affected QGIS version: master
Redmine category:vectors

---
Steps to reproduce:

1. Choose _Add vector layer_ option
2. Load attached csv file
3. When file is loaded as a layer, choose _Open Attribute Table_
4. Choose _Toggle editing mode_
5. Choose _Save Edits_

The error is thrown: "OGR error syncing to disk: Cannot rename files"

It seems to be problem only on Windows (tested on two devices with Windows 10). On Mac everything seems to be working.

---

- [package_18.csv](https://issues.qgis.org/attachments/download/11726/package_18.csv) (Olga Grabek)

**Comment by gioman** [comment]
Duplicate of https://github.com/qgis/QGIS/issues/35144
