### ISSUE TITLE
Automatically populate layer metadata for WMS layers

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25445]
Author Name: **James Passmore** (@nmtoken)
Original Redmine Issue: [17548](https://issues.qgis.org/issues/17548)

Redmine category:web_services_clients/wms

---
When right clicking on a WMS layer in the Layers Panel and selecting properties No information or metadata is provided about the service 

===

QGIS version
2.99.0-Master
QGIS code revision
cd0ba91
Compiled against Qt
5.5.1
Running against Qt
5.5.1
Compiled against GDAL/OGR
2.2.2
Running against GDAL/OGR
2.2.2
Compiled against GEOS
3.5.1-CAPI-1.9.1
Running against GEOS
3.5.1-CAPI-1.9.1 r4246
PostgreSQL Client Version
9.5.2
SpatiaLite Version
4.3.0a
QWT Version
6.1.2
PROJ.4 Version
492
QScintilla2 Version
2.9.1
This copy of QGIS writes debugging output.

**Comment by alexbruy** [comment]
Related to #31921
