### ISSUE TITLE
[layer properties] Selected item in the Join tab is not highlighted 

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25450]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [17553](https://issues.qgis.org/issues/17553)
Affected QGIS version: master
Redmine category:gui

---
In the layer properties dialog > Join tab, clicking a row does nothing. you first feel like nothing is selected but after few tests i understand that it was just not highlighted.
This is problematic when you have more than one joined layer. Which one is "selected"? am I trying to remove the right one?

**Comment by alexbruy** [comment]
Looks like already fixed. Please retest with master.

**Comment by alexbruy** [comment]
Closing for the lack of feedback. Please reopen if necessary.

**Comment by DelazJ** [comment]
OK. The selection is highlighted.
