### ISSUE TITLE
3D Map View: Add zoom tools

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25466]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [17569](https://issues.qgis.org/issues/17569)

Redmine category:3d

---
It could be nice to have zoom in, zoom out and zoom to canvas extent to help move in the 3D Map View (if it's common - but would be helpful).

**Comment by ismailsunni** [comment]
@DelazJ Zoom in and out is added in the 3D navigation. https://github.com/qgis/QGIS/pull/30105

**Comment by DelazJ** [comment]
Thanks @ismailsunni

**Comment by alexbruy** [comment]
Closing?

**Comment by ismailsunni** [comment]
@alexbruy I think yes
