### ISSUE TITLE
3D Map View: Add a note on how to swith to 3D representation

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25464]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [17567](https://issues.qgis.org/issues/17567)

Redmine category:3d

---
When you first time open a 3D Map View, you have a 2D rendering. And what to do to switch to 3D environment is not obvious...
So maybe a comment should be added in this way until the shift is done. Where? No idea.

**Comment by ismailsunni** [comment]
@saberraz  navigation is added now: https://github.com/qgis/QGIS/pull/30105

**Comment by saberraz** [comment]
Thanks @ismailsunni ...lets close the ticket!
