### ISSUE TITLE
r.in.lidar and other r.* tools Error: 'Raster map not found'  (worked until QGIS 2.18.14, GRASS 7.2.0)

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25508]
Author Name: **Alen Mangafic** (@mazingaro)
Original Redmine Issue: [17611](https://issues.qgis.org/issues/17611)
Affected QGIS version: 3.6.0
Redmine category:processing/grass

---
The r.in.lidar in QGIS 2.18.14 and in GRASS 7.0.3 in Linux Mint and Windows 10 do the same error when running the tool:

    Algorithm r.in.lidar - Creates a raster map from LAS LiDAR points using univariate statistics. starting...
    g.proj -c proj4="+proj=tmerc +lat_0=0 +lon_0=15 +k=0.9999 +x_0=500000 +y_0=-5000000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"
    g.region n=92000.0 s=91000.0 e=396000.0 w=395000.0 res=1
    r.in.lidar input="/home/alen/Desktop/TM_395_91.laz" method=mean type=FCELL zscale="1" percent="100" resolution="1" -e -o output=output412a4072b5e749b8b5eaa46a1e1a183f --overwrite
    g.region raster=output412a4072b5e749b8b5eaa46a1e1a183f
    r.out.gdal --overwrite -c createopt="TFW=YES,COMPRESS=LZW" input=output412a4072b5e749b8b5eaa46a1e1a183f output="/home/alen/Desktop/obmocje.tif"
    Cleaning up temporary files... 
    Starting GRASS GIS... 
    Executing '/home/alen/.qgis2//processing/grass7_batch_job.sh' ... 
    Default region was updated to the new projection, but if you have multiple mapsets `g.region -d` should be run in each to update the region from the default 
    Projection information updated 
    ERROR: Unable to open file 
    ERROR: Raster map not found 
    ERROR: Raster map or group not found 
    Execution of '/home/alen/.qgis2//processing/grass7_batch_job.sh' finished. 
    Cleaning up temporary files... 
    Cleaning up temporary files... 
    Starting GRASS GIS... 
    Executing '/home/alen/.qgis2//processing/grass7_batch_job.sh' ... 
    ERROR: Raster map not found 
    ERROR: Raster map or group not found 
    Execution of '/home/alen/.qgis2//processing/grass7_batch_job.sh' finished. 
    Cleaning up temporary files..

For Windows 10 I tried for both the OSGeo4W install and the direct install. I tried it also with QGIS 2.16.x and 2.14.x for both the OS. In Linux Mint I apt-get autoremoved/autocleaned always after. 
In Windows 10, if I install GRASS 7.2.2 separately and run the tool from it, it works well. I tried to reconnect QGIS with the separate GRASS install, but it does the same error again.

It worked until a few updates ago; it works well in QGIS 2.18.5 with GRASS 7.2.0
I noticed that also other r.* GRASS tools don't work anymore.

**Comment by alexbruy** [comment]
Just tested several r.* tools and they work fine for me. I would suggest to close this issue and open separate ticket for r.in.lidar

**Comment by luipir** [comment]
ping @mazingaro, new issue tracking is passed from redmine to github, please do further actions here instead of readmine.

**Comment by alexbruy** [comment]
Closing as most r.* tools works fine. Please open new tickets if necessary.

**Comment by luipir** [comment]
tnx for cleaning old issue
