### ISSUE TITLE
Spatial SQL queries are not working (wrong, empty result) in DB Manager for GeoPackage datasources

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25510]
Author Name: **Samuel Fernando Mesa Giraldo** (Samuel Fernando Mesa Giraldo)
Original Redmine Issue: [17613](https://issues.qgis.org/issues/17613)
Affected QGIS version: master
Redmine category:db_manager

---
*New description:*

Affects both 2.18.14 and master.

The same spatial queries are ok for Spatialite datasources.

Also using virtual layers seems to work as expected.

A query like:

SELECT fid, ST_Buffer(geom,100) AS geom
FROM points

for a GPKG datasource will result in a layer (loaded using the "load as new layer" option) that has the same geometry as the source one (and is empty).

*Old description:*
I'm trying to apply some spatial SQL functions like ST_BUFFER in a point layer.  The output is correct in the database manager but the representation is incorrect on the canvas.

!{width:600px}https://i.imgur.com/p3YO9PF.png!

The output is supposed to be a polygon layer.

!{width:600px}https://i.imgur.com/1h26Ipo.png!

---

- [test_points.gpkg](https://issues.qgis.org/attachments/download/11801/test_points.gpkg) (Samuel Fernando Mesa Giraldo)

**Comment by alexbruy** [comment]
Duplicates #/27914
