### ISSUE TITLE
Error with  Proccesing tools and GeoPackage (QGIS v2.99)

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25511]
Author Name: **Samuel Fernando Mesa Giraldo** (Samuel Fernando Mesa Giraldo)
Original Redmine Issue: [17614](https://issues.qgis.org/issues/17614)
Affected QGIS version: master
Redmine category:processing/core
Assignee: Victor Olaya

---
I'm using the default GeoPackage format for databases, but when I try to use a processing tool of GDAL, GRASS GIS or SAGA GIS, it does not recognize the format or it just closes unexpectedly. I have used _Buffer Vector_ from GDAL, _v.buffer.distance_ from GRASS GIS and F_ixed distance buffer_ from SAGA GIS and none with results.

In the case of GDAL, it always converts the layer to SHAPEFILE and consequently does not recognize the shortened fields. 

In the case of GRASS GIS, it always appears that the GPKG format is not recognized.

In the case of SAGA GIS, returns the following error, closing the QGIS program:

```
(Make sure 'QTextCursor' is registered using qRegisterMetaType().)
src/core/qgsmessagelog.cpp: 27: (logMessage) [1ms] [thread:0x7f66d8008f30] 2017-12-03T21:31:03 Processing[0] SAGA execution commands
shapes_tools "Shapes Buffer"  -SHAPES "/tmp/processing_ce203365cf1d4a0dba6dc6c42a7923fb/88f882df27f04f47ba0de04def37c1b7/SHAPES.shp" -DIST_FIELD_DEFAULT 100.0 -NZONES 1 -DARC 5.0 -DISSOLVE true -POLY_INNER false -BUFFER "/home/samtux/tmp/salida.gpkg"
*** Error in `./qgis': double free or corruption (!prev): 0x0000564e272961e0 ***
Abortado (`core' generado)

```

---

- [test_points.gpkg](https://issues.qgis.org/attachments/download/11802/test_points.gpkg) (Samuel Fernando Mesa Giraldo)

**Comment by alexbruy** [comment]
Works fine in master
