### ISSUE TITLE
[Print composer] "Crop to content" when exporting adds a black band when items are not placed on the paper 

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25519]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [17622](https://issues.qgis.org/issues/17622)
Affected QGIS version: 3.5(master)
Redmine category:map_composer/printing

---
Open a print composer
Add items
Add an item out of the paper area
Export to image with the "crop to content" option checked.
You get a black band when out of the paper frame.
Note that when the item placed out of the paper does not have a transparent background, the black band does not cover this item.

---

- [croppedLayout.png](https://issues.qgis.org/attachments/download/14127/croppedLayout.png) (Harrissou Santanna)

**Comment by nyalldawson** [comment]
Closing as wont-fix.
