### ISSUE TITLE
If the current feature ($geometry) falls outside the canvas's visibility area, the geometry generated with the geometry generator symbology is no longer visible

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25520]
Author Name: **salvatore fiandaca** (salvatore fiandaca)
Original Redmine Issue: [17623](https://issues.qgis.org/issues/17623)
Affected QGIS version: 3.0.0
Redmine category:symbology

---
sorry if I use google translator.

adding a geometry-generator layer to a layer (example: buffer ($ geometry, 100)), if the current feature ($ geometry) falls outside the canvas's visibility area, the buffer is no longer visible.

---

- [bug.7z](https://issues.qgis.org/attachments/download/11807/bug.7z) (salvatore fiandaca)

**Comment by roya0045** [comment]
This is resolved in 3.12.
