### ISSUE TITLE
"money"  type (postgresql) interpreted as string 

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25529]
Author Name: **Loïc BARTOLETTI** (@lbartoletti)
Original Redmine Issue: [17632](https://issues.qgis.org/issues/17632)
Affected QGIS version: 3.5(master)
Redmine category:field_calculator

---
In composer and virtual field, I have this error.

Try to add numeric fields and return NULL (decimal field for virtual field) or a string concatenation into composer.

---

- [composer.png](https://issues.qgis.org/attachments/download/11811/composer.png) (Loïc BARTOLETTI)
- [virtual_field.png](https://issues.qgis.org/attachments/download/11812/virtual_field.png) (Loïc BARTOLETTI)

**Comment by Pedro-Murteira** [comment]
Still valid on QGIS 3.16.15 and 3.22.2.

**Comment by strk** [comment]
Use of "money" type is discouraged: https://wiki.postgresql.org/wiki/Don't_Do_This#Don.27t_use_money

That said, what is the desired behavior ? Should it be treated as numeric ?

**Comment by strk** [comment]
PR GH-57513 threats those money values as numbers, @Pedro-Murteira @lbartoletti would you mind giving it a try ?
