### ISSUE TITLE
"Reloading QGIS" from the crash report dialog fails to reopen the project

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25532]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [17635](https://issues.qgis.org/issues/17635)
Affected QGIS version: 3.1(master)
Redmine category:project_loading/saving
Assignee: Nathan Woodrow

---
I'm working on a project stored on the network and i get a crash
I click on the "Reload QGIS" button which is supposed to relaunch QGIS and reopen the project. Btw, this label is not really obvious that it would reopen the project. Maybe something like "Reload Project" instead?
Anyway... QGIS is relaunched but it fails to reopen the project as he tries to find it in the c:\osgeo4w\bin folder.
And in case of a path with spaces, it takes pieces of text for layers, returning "The layer is invalid: the layer xxx is invalid and could not be added to the project" in the messagebar.

---

- [ReloadFails.PNG](https://issues.qgis.org/attachments/download/11814/ReloadFails.PNG) (Harrissou Santanna)

**Comment by AlisterH** [comment]
> in case of a path with spaces, it takes pieces of text for layers, returning "The layer is invalid: the layer xxx is invalid and could not be added to the project" in the messagebar.

This is still true in 3.12, I can't see any evidence of the rest.
