### ISSUE TITLE
Merging features/attributes: Allow the use of fields widget in the Merge row

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25557]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [17660](https://issues.qgis.org/issues/17660)

Redmine category:digitising

---
When merging features, it could be nice that in the "Merge attributes/features" dialog that pops up, the last row where user sets the values to apply shows the same widget applied to the fields ie if I use a drop-down, checkbox, ... in the layer for the fields then the "Merge" row should also show these widgets. 
Note that these widgets are already used for the existing features shown in the dialog

**Comment by nyalldawson** [comment]
Duplicate of #23833
