### ISSUE TITLE
ssl error: certificate validate failed with postgis and qgis 2.18.15

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25569]
Author Name: **Frédéric CLOITRE** (@lpofredc)
Original Redmine Issue: [17672](https://issues.qgis.org/issues/17672)
Affected QGIS version: 3.4.3
Redmine category:authentication_system

---
Hi,

This morning, I updated my computer which updated my version 2.18.14 of QGIS to version 2.18.15. 
Since this update, I can no longer connect to a PostGIS database that requires the ssl (sslmode = require) mode.

Error message is: ```ssl error: certificate validate failed
```.

I tried with a downgrade to previous ltr (2.14.11) and it works.

Any idea?

Thanks.

---

- [Sélection_026.png](https://issues.qgis.org/attachments/download/12287/S%C3%A9lection_026.png) (Frédéric CLOITRE)
- [Saisir les identifiants_263.png](https://issues.qgis.org/attachments/download/14037/Saisir%20les%20identifiants_263.png) (Frédéric CLOITRE)

**Comment by dvictori** [comment]
I'm also seeing this on QGIS 3.4.4-Madeira. Could not test on 3.4.11

**Comment by alasarr** [comment]
Hello,

I'm having the same issue on QGIS3.6 and QGIS3.10, both of them on OSX. 

It looks QGIS is not able to send the root certificate. I reported it too at [gis.stackexchange.com](https://gis.stackexchange.com/questions/348037/qgis-connection-to-postgis-via-ssl)

**Comment by alasarr** [comment]
I've just realized there is a tab in Preferences->Authentication->Manage Certificates->Authorities to add the authority.

Once I added the authority it works. 

BTW, I'll create a feature request to try to improve the UI. I think it would be better to ask for all the connection parameters at the connetion interface (client.crt, client.key and root.crt).

**Comment by alexbruy** [comment]
Closing, as there is a way to add additional authorities. Please reopen if necessary.

**Comment by thiagoquinaia** [comment]
QGIS 3.40.4 where.
So, Not every cloud server provides the 3 files key.pem, client.crt and root.crt. And in this case? For example, I'm trying to connect my server Postgres in QGIS using the Tembo.io service, and I couldn't. And it worked in pgAdmin and Node.js...

![image](https://github.com/user-attachments/assets/0dc67928-9e69-43e6-b851-7853593c41b6)

**Comment by agiudiceandrea** [comment]
@thiagoquinaia please create a new issue report.

**Comment by thiagoquinaia** [comment]
> [@thiagoquinaia](https://github.com/thiagoquinaia) please create a new issue report.

Thanks man! I opened it here https://github.com/qgis/QGIS/issues/60754
