### ISSUE TITLE
Give more hints to user when qgis help fails to find a page

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25563]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [17666](https://issues.qgis.org/issues/17666)

Redmine category:documentation_and_help

---
When the help system fails to find a working page the user gets:
> QGIS help is currently not available. This is likely because:
>
>    No internet connection is available
>    The offline help files are not available or the location of these files is not properly configured
>    No help content is available for the requested topic
>
> Please check that the correct location of the offline help files is specified in the QGIS options dialog (Settings → Options →System).

Maybe, the error message could show the last link it tried to open and couldn't find: it will help the user know if the error is local (URL badly constructed for example) or upstream (for example, some issues with docs site (redirection?)). See #25562.

**Comment by alexbruy** [comment]
Actually all messages, including full URL, are logged in the Message Log. Can we close this?

**Comment by DelazJ** [comment]
> Actually all messages, including full URL, are logged in the Message Log. Can we close this?

I'm not sure every user is aware of this. So either we add kind of "see more details in Message log" or as suggested above, show the url we fail to open.
I remember I spent quite some time trying to understand why my request failed despite everything looked fine when I filed this report. A QGIS bug it was...
