### ISSUE TITLE
[globe plugin] build failure with recent osgearth (FeatureQueryTool removal)

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25593]
Author Name: **landry Landry Breuil** (@landryb)
Original Redmine Issue: [17696](https://issues.qgis.org/issues/17696)
Affected QGIS version: master
Redmine category:c++_plugins/globe
Assignee: Pirmin Kalberer

---
In osgearth 2.9/master, featurequerytool was removed in  https://github.com/gwaldron/osgearth/commit/9c8dd703fcbc5730e6df1bf17372423fadd7cb30 while this class is used by the globe plugin: https://github.com/qgis/QGIS/search?utf8=%E2%9C%93&q=featurequerytool&type=

Tried to workaround it by shuffling header includes but it will fail anyway:

```
/usr/obj/ports/qgis-2.99pre20171213/QGIS-ea49c8276c1685345e019280e28f9095f7c314fb/src/plugins/globe/globe_plugin.cpp:421:27: error: allocation of incomplete ty
pe 'osgEarth::Util::FeatureQueryTool'                                                                                                                            mFeatureQueryTool = new osgEarth::Util::FeatureQueryTool();

```

Can anyone try to adapt globe code for newer osgearth APIs ?

**Comment by nyalldawson** [comment]
The globe plugin has been removed - users are encouraged to use 3d map windows instead now
