### ISSUE TITLE
scale lock doesn't work when resizing canvas

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25592]
Author Name: **Denis Rouzaud** (@3nids)
Original Redmine Issue: [17695](https://issues.qgis.org/issues/17695)
Affected QGIS version: 3.1(master)
Redmine category:map_canvas
Assignee: Denis Rouzaud

---
the scale isn't maintain when the map canvas is resized

both master and 2.18

**Comment by SrNetoChan** [comment]
Could not reproduce on 3.16.3 or master (3.17 https://github.com/qgis/QGIS/commit/fba5093f18) changing the mapcanvas size, the qgis window size or both still keeps the locked scale.

![Peek 2021-01-31 00-28](https://user-images.githubusercontent.com/3607161/106371351-55f18f00-635b-11eb-8f22-83bf2b36e57c.gif)


I think we can close this one. @gioman
