### ISSUE TITLE
Custom SVG styles paths saved as absolute not relative

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25605]
Author Name: **Patrick Dunford** (@enzedrailmaps)
Original Redmine Issue: [17708](https://issues.qgis.org/issues/17708)
Affected QGIS version: master
Redmine category:symbology

---
This seems to be just happening in more recent masters
When you export out styles to a file then the SVG path is stored as the full path not a relative path
This makes no sense when the custom SVG file used for the style happens to be in the same path as the style xml file.

---

- [ms453.xml](https://issues.qgis.org/attachments/download/11844/ms453.xml) (Patrick Dunford)

**Comment by gioman** [comment]
see https://github.com/qgis/QGIS/issues/25604#issuecomment-768466868

**Comment by gioman** [comment]
Closing for lack of feedback.
