### ISSUE TITLE
CRS selector: Extent is not displayed for all CRS

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25614]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [17718](https://issues.qgis.org/issues/17718)
Affected QGIS version: 3.7(master)
Redmine category:gui

---
I've asked "question about this on list":http://osgeo-org.1560.x6.nabble.com/QGIS-Developer-Is-the-map-preview-in-CRS-selector-dialog-broken-td5342748.html and got no answer so I'm reporting it here as I feel it's a bug: in the Coordinate Reference System selector dialog, the new map preview showing the extent of the selected CRS does not do that for all the CRSes. After some trial, I can't tell which kind of CRS shows or not its extent (though many or all EPSG:4-digits seem to show their extent).

---

- [crsExtent.PNG](https://issues.qgis.org/attachments/download/14561/crsExtent.PNG) (Harrissou Santanna)

**Comment by nyalldawson** [comment]
Should be fixed in 3.8 and for proj 6 based builds
