### ISSUE TITLE
Importing SLD : attributes names are not quoted in the expression

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25621]
Author Name: **Olivier Dalang** (@olivierdalang)
Original Redmine Issue: [17725](https://issues.qgis.org/issues/17725)
Affected QGIS version: master
Redmine category:symbology

---
Hi,

When importing an SLD with some basic rules, attributes name are not quoted in the expression. This means that they can easily clash with keywords/function, and thus the expression will be invalid.

Example :

```
...
<ogc:Filter>
    <ogc:PropertyIsEqualTo>
        <ogc:PropertyName>boundary</ogc:PropertyName>
        <ogc:Literal>administrative</ogc:Literal>
    </ogc:PropertyIsEqualTo>
</ogc:Filter>
...

```

will generate the following rule:

```
boundary = 'administrative'

```

And since boundary is the name of a function, this makes an error (expecting "(")

Thanks !

**Comment by alexbruy** [comment]
Seems fixed in master. Please retest.

**Comment by gioman** [comment]
Closing for lack of further feedback.
