### ISSUE TITLE
Add tools for Py3Qt5 in OSGeo4W

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25631]
Author Name: **Loïc BARTOLETTI** (@lbartoletti)
Original Redmine Issue: [17735](https://issues.qgis.org/issues/17735)

Redmine category:windows_package
Assignee: Jürgen Fischer

---
Hi,

Can we have in the osgeo4w package the usual tools to build python plugins in QGis (qt5-designer, pyuic5, QGis 2.9/3 custom widgets...)?

Regards

**Comment by alexbruy** [comment]
Seems fixed. Please reopen if necessary.
