### ISSUE TITLE
automatic label placement between range of distances

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25652]
Author Name: **Kepes Ádám** (Kepes Ádám)
Original Redmine Issue: [17756](https://issues.qgis.org/issues/17756)

Redmine category:labelling

---
when having to write too many labels they can be crowded. If label placement distance from point would be given to a range (0.5mm - 3 mm for example), qgis engine would be able to find a much better way for placing labels.

**Comment by pjshelton** [comment]
#23457 is requesting the same thing.

**Comment by gioman** [comment]
Closing as duplicate.
