### ISSUE TITLE
[Node tool] Misleading message when deleting all nodes of a ring or a part

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25650]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [17754](https://issues.qgis.org/issues/17754)
Affected QGIS version: master
Redmine category:digitising

---
Select a polygon feature with a ring
Use the node tool to select the ring vertices and delete them
You get in the messagebar: "Geometry has been cleared. Use the add part tool to set geometry for this feature." which is a wrong message given that there's still a geometry attached to the feature. This also occurs when a part of a multi-part geometry is deleted with node tool.
Note that using the dedicated "delete ring" or "delete part" tools do not trigger this message.

This message should be shown only when there's no more geometry attached to the feature.

Only master is concerned given that it looks impossible to remove all the vertices of a ring or a part (unless it's a single part feature) in 2.18

**Comment by uclaros** [comment]
This is no longer valid. Also the ring deletion issue mentioned in the comment has it's own bug report #35428
I guess this can close.

**Comment by DelazJ** [comment]
> This is no longer valid.

@uclaros Can you elaborate on what is no longer valid, please? I just tried (removing a ring or a part with vertex tool) and still get the message the the geometry has been cleared and that i should use the add part tool to set a geometry. There was still a geometry for the feature. 
master (not the latest commit but one week old max) ubuntu 18.04

**Comment by uclaros** [comment]
I am very sorry, I was testing on my local build that included my last PR. This bug has the same cause as #35428, so it should be fixed once #35439 is merged!
