### ISSUE TITLE
add feature to open and read spreadsheets as layers!

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25665]
Author Name: **Kepes Ádám** (Kepes Ádám)
Original Redmine Issue: [17769](https://issues.qgis.org/issues/17769)

Redmine category:data_source_manager

---
In previous qgis versions there were "spreadsheet layers" module, with wich user could add xls and ods files, reading them as attribute tables. This could be a very useful feature!

**Comment by kannes** [comment]
> But you can open them directly in QGIS either by Add vector layer button or by drag and drop. 

There is no such open in the `Add vector layer` menu or `Data Source Manager | Vector` dialog.

**Comment by kannes** [comment]
This was kinda of a duplicate of #18347

**Comment by DelazJ** [comment]
> There is no such open in the Add vector layer menu or Data Source Manager | Vector dialog.

Isn't it what the "Add" button at the bottom of these dialogs does? Or do I miss something?

**Comment by kannes** [comment]
Oops, you are right. It is not user-friendly though as they are not vector files but spreadsheets.

**Comment by jdugge** [comment]
XLS and XLSX spreadsheet layers can already be opened through GDAL. The formats are listed in the [Vector drivers list](https://gdal.org/drivers/vector/index.html) that the [QGIS documentation refers to](https://docs.qgis.org/3.10/en/docs/user_manual/managing_data_source/supported_data.html#vector-data), so this feature request can probably be closed.

**Comment by gioman** [comment]
Closing as it is already possible.
