### ISSUE TITLE
No Retina / HiDPI support on macOS

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25669]
Author Name: **Michal Jurewicz** (Michal Jurewicz)
Original Redmine Issue: [17773](https://issues.qgis.org/issues/17773)
Affected QGIS version: master
Redmine category:mac_os_specific

---
According to plans, QGIS 3.0 should support HiDPI displays. However current master 2.99 doesn't support Retina od MacOS on canvas. Icons and menu text is OK, byt all graphic and text on map canvas and on print composer is still low resolution. Please see attached screenshot. Icons are nice but points on map are very pixelated.

---

- [Zrzut ekranu 2018-01-02 o 07.24.44.png](https://issues.qgis.org/attachments/download/11888/Zrzut%20ekranu%202018-01-02%20o%2007.24.44.png) (Michal Jurewicz)
- [QGIS322-RESOLUTION-MAC.png](https://issues.qgis.org/attachments/download/13333/QGIS322-RESOLUTION-MAC.png) (Ugo Santana)
- [Zrzut ekranu 2018-11-13 o 09.21.37.png](https://issues.qgis.org/attachments/download/13763/Zrzut%20ekranu%202018-11-13%20o%2009.21.37.png) (Michal Jurewicz)

---

Related issue(s): #23900 (relates)
Redmine related issue(s): [15984](https://issues.qgis.org/issues/15984)

---

**Comment by adam52** [comment]
I just install QGIS 3.12 (first via Homebrew and then reinstalled from binary). Neither version supports Retina within the map area. I am on a macbook pro with Retina display, running High Sierra.

**Comment by 3nids** [comment]
@adam52 do you have "display scaling" enabled ?

**Comment by adam52** [comment]
@3nids Thanks getting back to me. It actually looks like only the splash screen and the simple markers (circles, etc.) used for spatial point layers are low res. Everything else looks great!

**Comment by Forrestus** [comment]
I still have rasters, icons and map canvas rendered in low resolution. The GUI is in high resolution.

I'm using **QGIS 3.14.0-Pi** on MacBook Pro with retina display running macOS Catalina. I've read every thread I could find.

<img width="491" alt="Zrzut ekranu 2020-07-3 o 12 49 31" src="https://user-images.githubusercontent.com/44900924/86462922-cafcd780-bd2c-11ea-9729-9d3c74f12c65.png">

**Comment by Rikuoja** [comment]
I am getting the same problem with all raster maps even with High (512x512/192 DPI) resolution selected. The GUI and polygons are in hi res. 
<img width="792" alt="image" src="https://user-images.githubusercontent.com/9367712/122528133-ae80aa80-d024-11eb-8949-08aebfdd2770.png">

**Comment by n0rdlicht** [comment]
Having a potentially related issue in QGIS 3.22.3 on macOS 12.2.

In my case any raster layer is positioned and/or scaled incorrectly compared to vector layers. This is true for both local Geotiffs and remote WM(T)S services or the default XYZ OpenStreetMap layer.

Is there any fix or workaround available?

<details>


QGIS version | 3.22.3-Białowieża | 
-- | --
QGIS code revision | 1628765ec7
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | 12.3
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 12.2
  |   
Active Python plugins
QNEAT3 | 1.0.4
swissgeodownloader | 1.1
gml_application_schema_toolbox | 1.3.1
SpatialDataPackageExport | 0.2.0
swiss_locator | 1.3.6
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.5
</details>

**Comment by gioman** [comment]
> Is there any fix or workaround available?

@n0rdlicht it has already been fixed for 3.24, which is due vert soon.

**Comment by n0rdlicht** [comment]
> > Is there any fix or workaround available?
> 
> @n0rdlicht it has already been fixed for 3.24, which is due vert soon.

many thanks. Looking forward and maybe trying the pre-release.

**Comment by n0rdlicht** [comment]
Tried the nightly build. Seems to be fixed on my end.

**Comment by bmerciergallay** [comment]
fixed how ? I really don't get how it's still this way. I've never had correct raster display on mac with hidpi, interface is fine but rasters have always been pixelated, and still are in 3.26

**Comment by nyalldawson** [comment]
This is fixed in QGIS 3.32 -- please open new tickets for individual outstanding issues if any are encountered on this version
