### ISSUE TITLE
Text goes over itself in text areas on display that has different display scaling than the main display.

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25673]
Author Name: **Lauri Kajan** (@lkajan)
Original Redmine Issue: [17777](https://issues.qgis.org/issues/17777)
Affected QGIS version: master
Redmine category:gui

---
Text is unreadable in textboxes for example on expression dialog or python console. Characters go over each other and cursor is located in wrong place (see image).

This happens when qgis is used on a display that has different display scaling than main display.

My main display has scaling 100% and the external monitor has 150%.

---

- [expression_dialog_hidpi.PNG](https://issues.qgis.org/attachments/download/11893/expression_dialog_hidpi.PNG) (Lauri Kajan)

**Comment by alexbruy** [comment]
Probably related to #25669.

**Comment by gioman** [comment]
Closing for lack of feedback.
