### ISSUE TITLE
Customization: no way to hide the Locator widget

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25675]
Author Name: **Borys Jurgiel** (@borysiasty)
Original Redmine Issue: [17779](https://issues.qgis.org/issues/17779)
Affected QGIS version: 3.7(master)
Redmine category:customisation_framework
Assignee: Nyall Dawson

---
The Locator Widget is not listed in the QgsCustomizationDialog, as it has no objectName.

After setting its objectName, it's properly included to the tree, however, unticking its checbox is not effective.

**Comment by DelazJ** [comment]
I confirm: setting the objectName() displays the widget in the list but it's not removed, unless deactivating the whole status bar.

**Comment by alexbruy** [comment]
Seems duplicate of #22968.

**Comment by borysiasty** [comment]
Not really a duplicate. The Locator bar is not hideable at all, while the other ticket only concerns the widget catcher (and you can still hide those elements with checkbokses).

**Comment by Pedro-Murteira** [comment]
I can still confirm in later versions, that by default, the locator widget is still not present in the QgsCustomizationDialog since it has no objectName associated with it. (QGIS 3.16.15 and 3.22.2.)
