### ISSUE TITLE
new composer attribute table sort abilty

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25671]
Author Name: **Kepes Ádám** (Kepes Ádám)
Original Redmine Issue: [17775](https://issues.qgis.org/issues/17775)

Redmine category:map_composer/printing

---
The next feature would be useful:

Qgis attribute tables in composer can only be sorted by visible fields. But there are cases when i don't want the field wich the sorting based on to be visible.

Qgis neither lets write random expressions at the sort table window, only written, already visible field expressions can be used for sorting table rows.

**Comment by nyalldawson** [comment]
Closing as duplicate of above

**Comment by 3nids** [comment]
the above issue is on another repo!
