### ISSUE TITLE
Snapping Tool

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25699]
Author Name: **Randal Hale** (@rjhale1971)
Original Redmine Issue: [17803](https://issues.qgis.org/issues/17803)
Affected QGIS version: master
Redmine category:digitising

---
This may not be a bug but I thought I'd report it. If I add a layer for digitizing I have two choices for snapping units: Meters and Pixels. I added data in EPSG:2274 and changed my projection to 2274 and I still have two choices - meters and pixels. I know in the "foot" side of the world this might cause some angst.

**Comment by gioman** [comment]
Closing for lack of feedback.
