### ISSUE TITLE
easy possibility to make non-geometry table to geometry layer (in cases delimited text layer opening can't solve)

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25706]
Author Name: **Kepes Ádám** (Kepes Ádám)
Original Redmine Issue: [17810](https://issues.qgis.org/issues/17810)

Redmine category:geometry

---
Put the case that i have this kind of delimited text layer file:

SS,OP20,FP21,AR120.00000,ZE90.00000,SD10.0000,--04_ko

After opening it with only as an attribute table, i make a virtual field from "OP20" -> 20 and "FP21" -> 21 point numbers, than I connect them with another table wich contains these point numbers with their coordinates. After that, i would like to make automatic and length-labeled lines between these points, with making it to be a line-geometry layer. At least with a WKT generated virtual self-set virtual field.

I am sure there is an ability to do that now, but it must be a hard way. An easy way for that would be very useful and widely, dynamically usable!

**Comment by alexbruy** [comment]
Looks like duplicate of #19939.
