### ISSUE TITLE
scale changing even when freezes 

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25730]
Author Name: **Lee Han** (Lee Han)
Original Redmine Issue: [17836](https://issues.qgis.org/issues/17836)
Affected QGIS version: master
Redmine category:map_canvas

---
If you freeze the scale of the canevas, when you raise the width of the layer panel, scale is changing.
Is it a normal behaviour ?

**Comment by roya0045** [comment]
Seems fixed in 3.12

**Comment by gioman** [comment]
Closing for lack of feedback.
