### ISSUE TITLE
2D profile window needed when drawing in 3D and working with tons of 3D data

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25751]
Author Name: **Jakob Lanstorp** (Jakob Lanstorp)
Original Redmine Issue: [17856](https://issues.qgis.org/issues/17856)

Redmine category:3d

---
If the 3D windows reaches a point where data like subsurface geological layers can be visualized - need will come for a 2D profile window. Working with geological 3D models requires a lot of input like boreholes and geophysical data. This massive input will obfuscate the 3D windows making it almost useless. When we make 3D geological models at work with software like Geoscene-3D nobody really use the 3D windows for anything. The 2D profile window - defined from a buffered polyline in a 2D map window - is where you model layers and add points in 2D. The points converts automatically to 3D points in relation to either profile line or if they are snapped to an existing 3D geometry in the 2D profile map. Interpolation on 3D points delivers the resulting 3D layer.

Also other 3D subsurface data like drinking water pipes, sewer networks and power lines could benefit from a 2D profile window.

---

Related issue(s): #29356 (relates)
Redmine related issue(s): [21540](https://issues.qgis.org/issues/21540)

---

**Comment by wonder-sk** [comment]
This has been added in QGIS 3.26 already - closing
