### ISSUE TITLE
QGIS 3.0 (2.99 dev) GRASS-Tools in Toolbox with PostGIS and Geopackage Layers 

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25766]
Author Name: **Flo Ju** (Flo Ju)
Original Redmine Issue: [17871](https://issues.qgis.org/issues/17871)
Affected QGIS version: master
Redmine category:grass

---
GRASS-functions in the toolbox (e.g. v.buffer) allow to select GPKG or PostGIS-Layers as Source - the execution fails. Just works if layer is converted to SHP before. Maybe the UI can support users with this issue (only valid datatypes selectable or warning)... or support of this sources.

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
