### ISSUE TITLE
CRS differences

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25779]
Author Name: **Bogdan Rosca** (Bogdan Rosca)
Original Redmine Issue: [17884](https://issues.qgis.org/issues/17884)
Affected QGIS version: master
Redmine category:projection_support

---
Today I noticed a diffecence in CRS parameters for Romania EPSG: 3844 between QGIS stable 2.18 and development version (2.99.0-269). The differences are in the transformation parameters:
- *the correct ones from QGIS 2.18*
```
+proj=sterea +lat_0=46 +lon_0=25 +k=0.99975 +x_0=500000 +y_0=500000 +ellps=krass +towgs84=2.329,-147.042,-92.08,0.309,-0.325,-0.497,5.69 +units=m +no_defs

```
- *and the old ones used in development version, specific for Poland*
```
+proj=sterea +lat_0=46 +lon_0=25 +k=0.99975 +x_0=500000 +y_0=500000 +ellps=krass +towgs84=33.4,-146.6,-76.3,-0.359,-0.053,0.844,-0.84 +units=m +no_defs

```
This difference can cause a 200m shifting in case of reprojection.

**Comment by nyalldawson** [comment]
This should be fixed in 3.8 when built using proj 6.0 or later. If not, it's a bug in the proj library and needs filing there.
