### ISSUE TITLE
select features by value select wrong geometries in layers with defined relations when you search from fields in child layer

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25785]
Author Name: **Gerhard Spieles** (Gerhard Spieles)
Original Redmine Issue: [17890](https://issues.qgis.org/issues/17890)
Affected QGIS version: 3.0.0
Redmine category:relations
Assignee: Matthias Kuhn

---
Select features by value reports in the selection form "The relation is not valid. Please make sure, your relation definitions are OK."
The results from values defined in fields in the many part (child layer) in selection form are wrong.

I checked the relation definition in project properities and it is ok. The identify feature form shows the right datas.
Screenshot is attached.

---

- [selectfeaturesbyvlaueinrelations.jpg](https://issues.qgis.org/attachments/download/11959/selectfeaturesbyvlaueinrelations.jpg) (Gerhard Spieles)

**Comment by roya0045** [comment]
Is this still valid with the recent changes to this area of the code?

**Comment by gioman** [comment]
Closing for lack of feedback.
