### ISSUE TITLE
No reason given when failing to load file

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25833]
Author Name: **Johannes Kroeger** (Johannes Kroeger)
Original Redmine Issue: [17937](https://issues.qgis.org/issues/17937)
Affected QGIS version: master
Redmine category:unknown

---
1. Prepare garbage data

$ dd if=/dev/urandom of=random bs=1M count=1
1+0 records in
1+0 records out
1048576 bytes (1.0 MB, 1.0 MiB) copied, 0.0470943 s, 22.3 MB/s

2. Try to load it in QGIS

$ qgis-git random

3. QGIS shows a red message above the recent project list, saying "CRITICAL	Layer is not valid : The layer /tmp/random is not a valid layer and can not be added to the map. Reason: ". The same message (plus a timestamp) is available in the messages log.

There is no reason given.

**Comment by kannes** [comment]
It says "`Invalid Data Source: /tmp/random is not a valid or recognized data source.`", nice!

Please close this issue.
