### ISSUE TITLE
Add GeoJSON from a https URL on Windows fails due to a SSL certificate problem

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25843]
Author Name: **David Piles** (David Piles)
Original Redmine Issue: [17947](https://issues.qgis.org/issues/17947)
Affected QGIS version: 3.4.4
Redmine category:data_provider

---
Trying to add a Geojson in QGIS Desktop from a url from the dialog add vector layer by protocol, gives error.
"Invalid data source https: // ......... .geojson is not a valid or recognized data source".
The same geojson, if I open it in local works, online gives that error.
It doesn't work with http, or with https.
If you copy the content of the geojson in the URI, it shows it to you.
It has not worked for me in the QGIS Desktop 2.18.14 and QGIS Desktop 2.18.16, windows versions.

---

- [qgis.jpg](https://issues.qgis.org/attachments/download/12097/qgis.jpg) (David Piles)

---

Related issue(s): #28717 (duplicates)
Redmine related issue(s): [20898](https://issues.qgis.org/issues/20898)

---

**Comment by gisnederland** [comment]
QGis 3.8.0, Win10, 1809 (=x64). 
Same `SSL certificate problem: unable to get local issuer certificate` error here, with geojson from https://open.data.amsterdam.nl/Projecten_Amsterdam_GeoJson.json
Could **not** solve it by adding the ```
GDAL_HTTP_USERAGENT = 
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.362``` entry to QGis' options/variables. 
Solved it by adding it as Windows system variables (and restarting QGis)

**Comment by nirvn** [comment]
This is fixed via @jef-n 's update of the libcurl package. The fix will be incorporated into the next point release standalone installer and is available already for those using the package-based osgeo4w installer.
