### ISSUE TITLE
[Digitising] Add ability to edit Z and M values from advanced digitizing panel

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25865]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [17969](https://issues.qgis.org/issues/17969)

Redmine category:digitising

---
While looking for some old discussion on vertex editor, I found http://osgeo-org.1560.x6.nabble.com/QGIS-Developer-QGIS-3-vertex-editor-problems-td5336971.html in which Regis said about the vertex editor
> The use case I know is more typing z / m values easily than entering XY.
> X/Y typing is not so difficult using the advanced editor panel (just type "x" then paste the X, "y" then paste) . It requires less mouse clicks for sure than the node editor panel. 
> We maybe could add the z and m SpinBox with z and m shortcuts too there.  

Given that it looks like a good idea to me, here's the feature request...

**Comment by DelazJ** [comment]
See also #31105 and #29415

**Comment by 3nids** [comment]
I'm -0 here. 

The panel is a construction panel and we currently don't have any mean to construct in 3d (tilt and pitch angles) neither a visualisation (like a profile view, maybe with 3D map canvas but it would not be straightforward).

**Comment by nyalldawson** [comment]
Implemented for 3.22
