### ISSUE TITLE
Pan to feature / Zoom to feature behave exactly the same

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25860]
Author Name: **Kory Roberts** (Kory Roberts)
Original Redmine Issue: [17964](https://issues.qgis.org/issues/17964)
Affected QGIS version: master
Redmine category:attribute_table

---
Open attribute table.  Right click a row.  Select "Pan to feature".  Move the map, maybe zoom out some.  Right click a row.  Select "Zoom to feature".  Both behave EXACTLY the same, so far as I can tell.  Maybe I just don't understand how they are supposed to function, but I would presume pan is supposed to just pan the map and zoom is supposed to ZOOM IN the map (which it doesn't).

**Comment by alexbruy** [comment]
I'd say this is a "won't fix".
