### ISSUE TITLE
Cartographic point labeling should take symbol bounds into account by default

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25866]
Author Name: **Johannes Kroeger** (Johannes Kroeger)
Original Redmine Issue: [17970](https://issues.qgis.org/issues/17970)
Affected QGIS version: master
Redmine category:labelling

---
By default the cartographic point labeling does not take symbol bounds into account which means the labels will likely overlap the symbols and thus look bad. This made me wonder if the feature was broken. I had expected great results just by switching to it.

Setting the "Distance offset from" to "From symbol bounds" makes them look fantastic.

Please make that setting the default! I would also suggest making the cartographic mode the default in any case ;)

---

- [cartographic default.png](https://issues.qgis.org/attachments/download/12024/cartographic%20default.png) (Johannes Kroeger)
- [around point.png](https://issues.qgis.org/attachments/download/12025/around%20point.png) (Johannes Kroeger)
- [cartographic offset symbol bounds.png](https://issues.qgis.org/attachments/download/12026/cartographic%20offset%20symbol%20bounds.png) (Johannes Kroeger)

**Comment by nyalldawson** [comment]
Still the case on 3.6.3
