### ISSUE TITLE
[Layouts] Button menus behavior is not consistent with main window's

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25899]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [18003](https://issues.qgis.org/issues/18003)
Affected QGIS version: 3.7(master)
Redmine category:map_composer/printing

---
In the layout dialog, the toolbars are full of button menus (I don't know if that's the real naming but I mean those buttons that offer a drop-down to select the desired command): align items, raise items, export atlas...
Clicking one of these buttons offers a list from which you can select an action. But the icon stays the same and next time you want to play the same action, you'll again need to click a first time to expand the list and a second time to select your command.
This is not the behavior in the main window where tools like "select features using an expression", "Move features", "regular shape tools", "Measure..." all switch to the selected command, allowing the user to perform the same action with one click (instead of two).

**Comment by alexbruy** [comment]
@nyalldawson was it implemented in such way on purpose or maybe we should update these buttons to match main window UI?

**Comment by nyalldawson** [comment]
I think we should consider them on a case-by-case basis. I agree that the "Export atlas" one would be useful to remember the last used format, but I think for align/reorder then you're likely to be wanting a different option every time you hit this button, so remembering the last action would actually make the button a bit less usable.
