### ISSUE TITLE
QGIS deleted attribute's value

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25908]
Author Name: **Jadwiga Trojak** (@troyaqgis)
Original Redmine Issue: [18012](https://issues.qgis.org/issues/18012)
Affected QGIS version: master
Redmine category:attribute_table

---
When I removed fields in Attribute Table QGIS deleted attribute's value in first row.
Applies to shapefiles.

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
