### ISSUE TITLE
no refresh using notify in postgis

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25917]
Author Name: **Lee Han** (Lee Han)
Original Redmine Issue: [18021](https://issues.qgis.org/issues/18021)
Affected QGIS version: 3.4.2
Redmine category:data_provider/postgis

---
following this : http://oslandia.com/en/2017/10/07/refresh-your-maps-from-postgresql/.
I checked the two boxes in the rendering tab, and used 'refresh qgis' message.
Then in a psql shell, I write @listen qgis@,
I import a shp in my database,
I write @Notify qgis, 'refresh qgis' ;@
All that I get in return is : @Asynchronous notification "qgis" with payload "refresh qgis" received from server process with PID 1848@
And the canevas is unchanged.
Did I miss something ?

Postgres 9.3 ; qgis 2.99 ; windows 7

---

- [Capture.PNG](https://issues.qgis.org/attachments/download/13902/Capture.PNG) (Lee Han)

**Comment by gduls** [comment]
Please note that issue #38986 has been closed by me.
**The NOTIFY command must come from an SSL enabled connection.**

**Comment by gioman** [comment]
> Please note that issue #38986 has been closed by me.
> **The NOTIFY command must come from an SSL enabled connection.**

closing as duplicate.
