### ISSUE TITLE
Custom projections/transformations using a PROJ init-file fails.

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25918]
Author Name: **Kristian Evers** (@kbevers)
Original Redmine Issue: [18022](https://issues.qgis.org/issues/18022)
Affected QGIS version: master
Redmine category:projection_support

---
QGIS can't create custom projections that uses PROJ.4 init-files. As seen on the attached screenshot, when I enter the PROJ.4 parameters - in this case “+init=C:\dev\NordicTransformations\resources\DK:UTM32N” - the test works fine but when I try to save it, I am presented with the message "The proj4 definition of 'Init-test' is not valid". Since the test works the problem is not that the file can’t be found or that the definition is invalid - it is something else. I suspect there's some faulty logic at play here since the transformation obviously works. It has been suggested that the problem might be that there is not an inverse transformation available, which is not the case either.

I experience the same behavior in both QGIS2 and QGIS3.

The reason I want to define custom CRS's is that I only want to maintain the projections/transformations that I need in one place instead of many. Also, until QGIS adopts the new features in the comming version of PROJ, this is the only viable way to access the advanced transformations that the new PROJ version allows.

I have marked this as an easy fix. Having looked at the affected code months ago, it seems to be a rather localized problem. It is my best guess that this can be fixed quickly by someone familiar with the code.

---

- [QGIS_CRS.PNG](https://issues.qgis.org/attachments/download/12093/QGIS_CRS.PNG) (Kristian Evers)
- [custom-init](https://issues.qgis.org/attachments/download/12094/custom-init) (Kristian Evers)

**Comment by kbevers** [comment]
This is still present in QGIS 3.4 and 3.6.

**Comment by AsgerPetersen** [comment]
This also fails when the `init` file is located in the `PROJ_LIB` folder and therefore found automatically by Proj.

For example QGIS for Mac packages init files coming from https://github.com/OSGeo/proj-datumgrid in its PROJ_LIB folder.
