### ISSUE TITLE
Minimal width of the "Report Organizer" panel is too big!

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25916]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [18020](https://issues.qgis.org/issues/18020)
Affected QGIS version: master
Redmine category:map_composer/printing

---
See the screenshot attached, I can't reduce the width of that panel. I guess that it's because in-depth options can offer layer and field comboboxes and the panel is sized by default for this "full" configuration but on smaller screens, it consumes space. Better allow scrollbars (and maybe also reduce comboboxes size)

---

- [bigReportOrganizer.PNG](https://issues.qgis.org/attachments/download/12092/bigReportOrganizer.PNG) (Harrissou Santanna)

**Comment by nyalldawson** [comment]
Umm github this is closed? stop showing it in open filters...
