### ISSUE TITLE
Layer Panel / Treeview items resize to mega and keep doing that

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25926]
Author Name: **Richard Duivenvoorde** (@rduivenvoorde)
Original Redmine Issue: [18030](https://issues.qgis.org/issues/18030)
Affected QGIS version: 3.7(master)
Redmine category:map_legend

---
While investigating some other issue #25922 this user added a gpkg with some layers (and styles in it).

When you load those layers, and zoom in at the map, the 'circles' in the Layer Panel keep growing and growing, upon every zoomin, see screenshot.

![jumbolegenditems.png](https://issues.qgis.org/attachments/download/12105/jumbolegenditems.png)

I will also add the sample gpkg.

Not sure what is happening, here. Nothing special in styles to what I can see.

---

- [orechov.gpkg](https://issues.qgis.org/attachments/download/12104/orechov.gpkg) (Richard Duivenvoorde)
- [jumbolegenditems.png](https://issues.qgis.org/attachments/download/12105/jumbolegenditems.png) (Richard Duivenvoorde)

**Comment by roya0045** [comment]
Still a thing.

**Comment by Pedro-Murteira** [comment]
I can no longer replicate this issue on QGIS 3.16.14 and 3.22.1.
