### ISSUE TITLE
Problem with No data value for raster layers

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25955]
Author Name: **Jadwiga Trojak** (@troyaqgis)
Original Redmine Issue: [18059](https://issues.qgis.org/issues/18059)
Affected QGIS version: master
Redmine category:rasters

---
Hi,
No data value (Layers Properties->Transparency) read from the geotiff file is 255 (it's 3 bands raster, why not 255,255, 255 - look at gdalinfo below) and it caused that all colours with band 1 equals 255 become transparent (e.g. 255,212,0). Problem  applies to QGIS 2.18 and QGIS master.
By the way, I've identified another proble, which applies to function "Add values from display" in Transarency section of Layer Properties: after selecting the value, the property window is minimized. 

_> GDAL execution console output
> Driver: GTiff/GeoTIFF
> Files: V:/ODBIORY/II/II_etap/styk_geotif/ergo/PL.PZGiK.283.M-34-077-B-d-2_1992.tif
> Size is 9014, 9228
> Coordinate System is:
> PROJCS["ETRS_1989_Poland_CS92",
> GEOGCS["GCS_ETRS_1989",
> DATUM["European_Terrestrial_Reference_System_1989",
> SPHEROID["GRS_1980",6378137,298.257222101,
> AUTHORITY["EPSG","7019"]],
> AUTHORITY["EPSG","6258"]],
> PRIMEM["Greenwich",0],
> UNIT["degree",0.0174532925199433]],
> PROJECTION["Transverse_Mercator"],
> PARAMETER["latitude_of_origin",0],
> PARAMETER["central_meridian",19],
> PARAMETER["scale_factor",0.9993],
> PARAMETER["false_easting",500000],
> PARAMETER["false_northing",-5300000],
> UNIT["metre",1,
> AUTHORITY["EPSG","9001"]]]
> Origin = (603166.470843223272823,228784.293993111059535)
> Pixel Size = (0.507920658126625,-0.511394638377061)
> Corner Coordinates:
> Upper Left ( 603166.471, 228784.294) ( 20d26'15.08"E, 49d55' 2.85"N)
> Lower Left ( 603166.471, 224065.144) ( 20d26'10.54"E, 49d52'30.05"N)
> Upper Right ( 607744.868, 228784.294) ( 20d30' 4.66"E, 49d54'59.94"N)
> Lower Right ( 607744.868, 224065.144) ( 20d29'59.92"E, 49d52'27.15"N)
> Center ( 605455.669, 226424.719) ( 20d28' 7.55"E, 49d53'45.01"N)
> Band 1 Block=128x128 Type=Byte, ColorInterp=Red
> Computed Min/Max=35.000,253.000
> Minimum=35.000, Maximum=253.000, Mean=188.738, StdDev=44.669
> NoData Value=255
> Band 2 Block=128x128 Type=Byte, ColorInterp=Green
> Computed Min/Max=14.000,249.000
> Minimum=14.000, Maximum=249.000, Mean=205.265, StdDev=51.967
> NoData Value=255
> Band 3 Block=128x128 Type=Byte, ColorInterp=Blue
> Computed Min/Max=0.000,252.000
> Minimum=0.000, Maximum=252.000, Mean=187.704, StdDev=49.011
> NoData Value=255
_

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary,
