### ISSUE TITLE
OSM (OGR provider) layer pointer throws a python error when checking it

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26005]
Author Name: **Mathieu Pellerin - nIRV** (Mathieu Pellerin - nIRV)
Original Redmine Issue: [18109](https://issues.qgis.org/issues/18109)
Affected QGIS version: master
Redmine category:python_bindings_/_sipify
Assignee: Nyall Dawson

---
Very odd, while dissecting a progressing error, it ended up revealing something broken with python and OGR provider layer with OSM datasets (I must assume other types also impacted).

*Steps to reproduce*
1. Create a new project
1. Add the attached test.osm dataset (add the line multipolygon layer)
1. Make sure that added layer is selected in the layers panel
1. Open the python console
1. Type the following ```(not iface.activeLayer())
```
1. Notice python throwing the following error
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
SystemError: error return without exception set

```

This triggers processing errors with vector features parameters.



---

- [test.osm.zip](https://issues.qgis.org/attachments/download/12170/test.osm.zip) (Mathieu Pellerin - nIRV)

**Comment by gioman** [comment]
@nirvn is this still a thing?

**Comment by nirvn** [comment]
No.
