### ISSUE TITLE
ImportError: QtWebEngineWidgets must be imported before a QCoreApplication instance is created 

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26048]
Author Name: **D M** (D M)
Original Redmine Issue: [18155](https://issues.qgis.org/issues/18155)
Affected QGIS version: master
Redmine category:python_plugins

---
A similar issue appears to have been reported -- see this: https://github.com/qutebrowser/qutebrowser/issues/1640.

Stack trace:
```
Couldn't load plugin 'myplugin' due to an error when calling its classFactory() method 

ImportError: QtWebEngineWidgets must be imported before a QCoreApplication instance is created 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS2~1.99/apps/qgis-dev/./python\qgis\utils.py", line 336, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/Me/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\myplugin\__init__.py", line 20, in classFactory
    from myplugin.plugin import QGISPlugin
  File "C:/PROGRA~1/QGIS2~1.99/apps/qgis-dev/./python\qgis\utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Me/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\myplugin\plugin\__init__.py", line 16, in 
    from myplugin.plugin.ui.dock import Dock
  File "C:/PROGRA~1/QGIS2~1.99/apps/qgis-dev/./python\qgis\utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Me/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\myplugin\plugin\ui\dock.py", line 6, in 
    from myplugin.plugin.ui.tab import Tab
  File "C:/PROGRA~1/QGIS2~1.99/apps/qgis-dev/./python\qgis\utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Me/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\myplugin\plugin\ui\tab_home.py", line 1, in 
    from PyQt5.QtWebEngineWidgets import QWebEngineView
  File "C:/PROGRA~1/QGIS2~1.99/apps/qgis-dev/./python\qgis\utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: QtWebEngineWidgets must be imported before a QCoreApplication instance is created


Python version: 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] 
QGIS version: 2.99.0-Master Master, 2c53630747 

Python Path:
C:/Users/Me/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\extlibs
C:/PROGRA~1/QGIS2~1.99/apps/qgis-dev/./python
C:/Users/Me/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Me/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS2~1.99/apps/qgis-dev/./python/plugins
C:\Program Files\QGIS 2.99\bin\python36.zip
C:\PROGRA~1\QGIS2~1.99\apps\Python36\DLLs
C:\PROGRA~1\QGIS2~1.99\apps\Python36\lib
C:\Program Files\QGIS 2.99\bin
C:\PROGRA~1\QGIS2~1.99\apps\Python36
C:\PROGRA~1\QGIS2~1.99\apps\Python36\lib\site-packages
C:/Users/Me/AppData/Roaming/QGIS/QGIS3\profiles\default/python

```

**Comment by bnegruimajing** [comment]
The issue is still valid on QGIS 3.6.2 running on Debian 10.
The 'QtWebEngineWidgets' module was not available at all. 
After installing the `python3-pyqt5.qtwebengine` package, I get the same error:
 `ImportError: QtWebEngineWidgets must be imported before a QCoreApplication instance is created`

**Comment by bgoesswe** [comment]
Also still valid on 3.8.2-Zanzibar Zanzibar, 4470baa1a3, Kubuntu 16.04, installed "qtwebengine5-dev-tools" package. 
The QWebEngineView works in the Qt Designer, but not in QGIS due to the same error message:
ImportError: QtWebEngineWidgets must be imported before a QCoreApplication instance is created

**Comment by elgis-frank** [comment]
I am working on a plugin for QGis Lts (3.4.16 compiled against Qt 5.9.5 on Ubuntu 18.04). I apt installed python3-pyqt5.qtwebengine and it works fine with python3, but crashed in Qgis with ImportError: QtWebEngineWidgets must be imported before a QCoreApplication instance is created.
I have an old code from Qgis 2 plugin adjusted, but QtWebKit is not really working

**Comment by nyalldawson** [comment]
There's no way this can be solved in qgis -- qgis **has** to create an application before python support is setup. There's no way around that. The fix for this would be to work with upstream and get a workaround implemented which would avoid the need to initialise before the application construction.

**Comment by neha845** [comment]
Using these lines in your code will help.

from PyQt5 import QtWidgets
app = QtWidgets.QApplication.instance()
if app is not None:
    import sip
    app.quit()
    sip.delete(app)
import sys
from PyQt5 import QtCore, QtWebEngineWidgets
QtCore.QCoreApplication.setAttribute(QtCore.Qt.AA_ShareOpenGLContexts)
app = QtWidgets.qApp = QtWidgets.QApplication(sys.argv)

**Comment by rICHi97** [comment]
> Using these lines in your code will help.
> 
> from PyQt5 import QtWidgets app = QtWidgets.QApplication.instance() if app is not None: (Press tab before this) import sip (Press tab before this) app.quit() (Press tab before this) sip.delete(app) import sys from PyQt5 import QtCore, QtWebEngineWidgets QtCore.QCoreApplication.setAttribute(QtCore.Qt.AA_ShareOpenGLContexts) app = QtWidgets.qApp = QtWidgets.QApplication(sys.argv)

it does work, but may cause unsure problem

**Comment by krzysztof-adamski** [comment]
> 

I wonder how should I use this code in QGIS, especially part as following

```
        app = QtWidgets.QApplication.instance()
        if app is not None:
            import sip
            app.quit()
            sip.delete(app)
```
When we use above the code immediately QGIS will close
