### ISSUE TITLE
Help oneliner in python console is not showing all info on Windows environment

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26065]
Author Name: **Rosa  Aguilar** (@rosaguilar)
Original Redmine Issue: [18174](https://issues.qgis.org/issues/18174)
Affected QGIS version: 3.0.0
Redmine category:pyqgis_console

---
the command help(iface.addVectorLayer) return an incomplete text when is used in the python console in Windows.

**Comment by nyalldawson** [comment]
This is related to the sip version used on the different platforms - it's not a qgis bug but requires updated sip library in osgeo4w
