### ISSUE TITLE
Define area in Nearest Neighbor analysis

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26063]
Author Name: **Matt McLean** (Matt McLean)
Original Redmine Issue: [18172](https://issues.qgis.org/issues/18172)

Redmine category:analysis_library

---
When using the Nearest neighbor analysis (Menu bar >>> Vector >>> Analysis >>> Nearest Neighbor Analysis) the current implementation does the area calculations based on the extent of the input layer (https://github.com/qgis/QGIS/blob/835cca7cae3a8bc4cdff881ec7be374eaf390f6f/python/plugins/processing/algs/qgis/NearestNeighbourAnalysis.py#L105-L106) It would be useful to have the option of manually setting the area for the purpose of being able to compare z-scores for study areas of a fixed size. This is a feature that currently exists in ArcGIS (http://pro.arcgis.com/en/pro-app/tool-reference/spatial-statistics/h-how-average-nearest-neighbor-distance-spatial-st.htm) however I would prefer to stay in an Open Source work-flow.

**Comment by alexbruy** [comment]
You can extract/clip required area and run analysis agains these clipped files.
