### ISSUE TITLE
Choose a colour for nodata values

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26087]
Author Name: **Jon Morris** (Jon Morris)
Original Redmine Issue: [18196](https://issues.qgis.org/issues/18196)

Redmine category:rasters

---
There may already be a feature request in for this, but I couldn't find one. Please could we have an option to set the colour of nodata in raster layers?

There is a workaround (see https://gis.stackexchange.com/questions/75865/how-to-display-nodata-of-a-raster-in-qgis), but it would be much easier if there was a dropdown as there is in ArcMap.

**Comment by vesnikos** [comment]
This is an on-going annoyance in my QC procedures. 
There is no way to colour the nodata with a colour of my choosing. 

I don't understand why both Arcgis and Arcgis pro now have that functionality and qgis does not :/

**Comment by gioman** [comment]
> I don't understand why both Arcgis and Arcgis pro now have that functionality and qgis does not :/

why is so strange? I could make several examples of the contrary.

**Comment by vesnikos** [comment]
if you are suggesting that the decision for this functionality was a conscious one, can you please redirect me to the relevant discussion. I am VERY much interested to see the arguments in it. 

As it stands right now, and correct me if I am wrong, the framework to support this functionality is already in place.

**Comment by gioman** [comment]
> if you are suggesting that the decision for this functionality was a conscious one, can you please redirect me to the relevant discussion. I am VERY much interested to see the arguments in it.

I'm not sure but I just think that it was just an overlooked aspect of the raster symbology. I suggest you to raise a wider discussion by writing in the developers mailing list.
