### ISSUE TITLE
Native raster calclulator in Processing does not update input layer list on layer addition/removal

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26105]
Author Name: **Alister Hood** (@AlisterH)
Original Redmine Issue: [18214](https://issues.qgis.org/issues/18214)
Affected QGIS version: 3.4.1
Redmine category:processing/qgis
Assignee: Victor Olaya

---
The list of input layers in the processing raster calculator dialog is not updated when a layer is removed (or added, although this is less annoying as it doesn't cause an error).
i.e.:
- run it once and don't close the dialog
- in the main QGIS window remove the layer that was created
- go back to the dialog and try to run it again, but you will get an error: "Unable to execute algorithm. Incorrect parameter value for LAYERS"

**Comment by AlisterH** [comment]
> Author Name: **Alister Hood** (@AlisterH)
> 
> Alister Hood wrote:
> 
> > There is also an issue with updating the "Reference layer" dialog when a layer is removed - it still shows up in the "Reference layer" dialog until another layer change is made i.e. until another layer is added or removed.
> 
> i.e. updating the list for layer removals lags by one. 

Looks like this is fixed.

>But at least in 3.4.3 it affects the list in the main dialog, not just the reference layer list.

I don't understand what I was saying here, as the main list doesn't update in the first place.  Unless I was talking about closing and reopening the dialog.

> And there is also an issue when layers are renamed. If a layer (or more than one layer) is renamed (one or more times) then that isn't reflected in either the main dialog or the reference layer list, unless you subsequently add or remove a layer.

The reference layer list is OK if you leave it and go back into it.  I think this is now consistent for all the algorithms that use this type of list.

> I guess I'll need to check these things in a nightly build as there has been some fixes to the raster calculator, and I'm not sure if they were before or after 3.4.3. But as of 3.4.3 it appears there are still more widespread issues with the layer lists in dialogs not updating correctly. e.g.:
> 
> * open the @r.patch@ dialog from processing toolbox.
> * look at the list of layers available to choose from in the dialog.  Close the list, but not the main dialog.
> * rename a layer in the layers panel.
> * remove another layer in the layers panel.
> * look again at the list of layers available to choose from in that dialog.  You will see neither renaming nor removing a layer triggered the list to be updated.  Close the list, but not the main dialog.
> * drag and drop a new layer into the main qgis window.
> * look again at the list of layers available to choose from in that dialog.  You will see that the new layer is now included, and because that triggered the list to be updated, the previous layer renaming and removal is also reflected in the list.

The main annoyance here seems to be fixed - as noted above, this widget updates when you leave and go back into it (I guess ideally it would update without leaving and reentering, but the current behaviour isn't too bad).

The other main bug I see is that after I run e.g. r.patch, in the "Raster layers to be patched together" field it increments the number of inputs that it claims are selected.  I thought this was consistent, but I just managed to run r.patch without it incrementing, so I'm not sure what was different this time.

**Comment by AlisterH** [comment]
> The list of input layers in the processing raster calculator dialog is not updated when a layer is removed (or added, although this is less annoying as it doesn't cause an error).

For the record, this main bug still occurs, but the error message I noted isn't helpful at all anymore.

> i.e.:
> 
> * run it once and don't close the dialog
> * in the main QGIS window remove the layer that was created

I'm not sure if I meant to say remove one of the layers used in the calculation, which causes an error, or if there was an additional bug that is now fixed.

> * go back to the dialog and try to run it again, but you will get an error: "Unable to execute algorithm. Incorrect parameter value for LAYERS"

error now just says:
```
An error occurred while performing the calculation
Execution failed after 0.30 seconds

**Comment by alexbruy** [comment]
Fixed in the latest master.
