### ISSUE TITLE
3D View ArcBall Camera

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26100]
Author Name: **Piero Toffanin** (Piero Toffanin)
Original Redmine Issue: [18209](https://issues.qgis.org/issues/18209)

Redmine category:3d

---
Hello! First of all congrats on the 3.0 release. :)

This is my QGIS version:

QGIS version
3.0.0-Girona
QGIS code branch
Release 3.0
Compiled against Qt
5.10.0
Running against Qt
5.10.0
Compiled against GDAL/OGR
2.1.3
Running against GDAL/OGR
2.2.3
Compiled against GEOS
3.6.2-CAPI-1.10.2
Running against GEOS
3.6.2-CAPI-1.10.2 4d2925d6
PostgreSQL Client Version
10.1
SpatiaLite Version
4.3.0a
QWT Version
6.1.3
QScintilla2 Version
2.10.2
PROJ.4 Version
493

I've experienced some difficulties navigating the 3D Map View (from a user experience perspective) so I thought to open an issue.

To reproduce:
 - Import attached dsm.tif into QGIS
 - Open 3D Map View
 - Set elevation to dsm.tif, resolution to 100px
 - Press SHIFT + Left click (or middle click) on 3D Map View and move mouse cursor downward

Result: the 3D model rotates up and away toward the top of the screen. This requires the user to zoom out, find the 3D model, pan the camera up, zoom back in. Subsequently, try to rotate around the model. The model rotates around it's corner instead of around the camera target.

Improvement: the 3D model should rotate around the current camera target (an Arcball camera implementation, see an example https://demo.webodm.org/public/task/57bde61a-43fb-4447-b47a-9896498ddfba/3d/).

Also noticed that pressing the "Zoom Full" button for this particular model does not center the scene to the model (the model disappears, with the camera being placed below it in the Z direction).

---

- [dsm.tif](https://issues.qgis.org/attachments/download/12242/dsm.tif) (Piero Toffanin)

**Comment by alexbruy** [comment]
Closing as reported issue was fixed in 3.4.
