### ISSUE TITLE
Vertex Editor dialog does not respect its last placement

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26117]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [18226](https://issues.qgis.org/issues/18226)
Affected QGIS version: 3.0.0
Redmine category:gui
Assignee: Martin Dobias

---
Open the vertex editor, the panel is placed at the bottom of the left panels.
Then move it so that it covers the height of the map canvas (shows more vertices), near the layers panel.
Do another operation so that the vertex panel is closed.
Now reopen the vertex editor: it's again at the bottom of the other panels instead of keeping its last position.

**Comment by alexbruy** [comment]
Probably the same as #25381.

**Comment by gioman** [comment]
Seems fixed in 3.16.2
