### ISSUE TITLE
Review the Subdivide algorithm help: advertised bug?

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26114]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [18223](https://issues.qgis.org/issues/18223)
Affected QGIS version: 3.0.0
Redmine category:processing/qgis
Assignee: Victor Olaya

---
The subdivide algorithm help (in app and in docs) states that 
> The returned geometry parts may not be valid and may contain self-intersections.

I'm not sure this comment adds confidence in the tool. Shouldn't creation of invalid features be considered as a bug and fixed in the tool instead?

**Comment by nyalldawson** [comment]
This is a wont-fix. It's a natural consequence of the algorithm and can be repaired in post-processing steps.
