### ISSUE TITLE
No automatic reconnection when connection lost using Oracle data sources

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26134]
Author Name: **Casper Børgesen** (Casper Børgesen)
Original Redmine Issue: [18243](https://issues.qgis.org/issues/18243)
Affected QGIS version: 3.0.0
Redmine category:db_manager

---
Problem:
* I have created a QGIS project with several layers based on Oracle data sources. 
* I am running QGIS 3.0 on a Windows machine.
* I hibernate my machine and leave work for today.
* The next morning I resume my work and when I wake my machine again QGIS doesn't draw the Oracle based layers.
* I get the following python warning/error message: @Error: ORA-03114: not connected to ORACLE@
* To try to work around the problem I then save the project and reload it hoping QGIS will reconnect. 
* When reloading the project QGIS cannot find the sources for the Oracle based layers and my only option is to press Cancel and let QGIS remove my layers.

Result:
* My project is lost or I need to revert to a previous saved copy (if I have one) where I had connection while saving the project (I ticked the _Crashes QGIS or corrupts data_ due to this).

Expected behavior:
1. I would expect QGIS to try to reconnect the layers if the connection is lost. 
1. Secondary QGIS could give me the option to click reconnect somewhere.

_P.S.: I tried just hibernating my computer and wake it immediately afterwards, and the connection persist, making it more difficult to reproduce._

**Comment by gioman** [comment]
@chau-intl is this till valid in recent QGIS releases?

**Comment by chau-intl** [comment]
I don't remember having seen this issue for a long time. But version 3.0.0 is also a very long time ago, so @gioman please close this issue. I'll come back if it re-surfaces :)
