### ISSUE TITLE
export layout output via terminal

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26131]
Author Name: **Basil Eric Rabi** (@basilrabi)
Original Redmine Issue: [18240](https://issues.qgis.org/issues/18240)

Redmine category:map_composer/printing

---
A terminal command like below, to print layouts by batches without opening the gui, would be nice.

qqis-layout -p project.qgs -l layoutName -o mymap.pdf

see https://gis.stackexchange.com/questions/167650/export-a-qgis-print-composer-file-qpt-as-pdf-from-the-command-line/167657#167657

**Comment by basilrabi** [comment]
I learned the workaround for this. You can make a python script like this:
```python3
#!/usr/bin/python3

import os

from qgis.core import QgsApplication, QgsLayoutExporter, QgsProject

gui_flag = False
app = QgsApplication([], gui_flag)

app.initQgis()

project = QgsProject.instance()
project.setFileName(os.getcwd() + '/map.qgs')
project.read()

manager = QgsProject.instance().layoutManager()
layout = manager.layoutByName('a4')

exporter = QgsLayoutExporter(layout)
exporter.exportToPdf('drillHoleLocation.pdf',
                     QgsLayoutExporter.PdfExportSettings())

app.exitQgis()
```
Then you can now print your layout by running the script via terminal.

**Comment by basilrabi** [comment]
Hi @gioman , can we close this feature request?

**Comment by gioman** [comment]
> Hi @gioman , can we close this feature request?

@basilrabi yes, but it would be better give an explanation why.

**Comment by basilrabi** [comment]
> yes, but it would be better give an explanation why.

Creating a python script similar to [this](https://github.com/qgis/QGIS/issues/26131#issuecomment-516202757) will be enough since the functionality needed is already exposed in the the python bindings.
