### ISSUE TITLE
Database configurations not carried over to QGIS 3.0

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26146]
Author Name: **rmercer -** (rmercer -)
Original Redmine Issue: [18255](https://issues.qgis.org/issues/18255)
Affected QGIS version: 3.0.0
Redmine category:unknown

---
My data is stored in a Postgres database.  I had a number of configurations stored for different usernames and databases.  These are no longer in the DB Manager in QGIS 3.0.  Some additional information is that when I upgraded to 3.0, I ended up having to completely remove my previous OSGeo4W directory because there were legacy files remaining that were causing errors with the new install.  I do not know where the configuration information is stored, so it may have been removed when I did the clean install.  One way or the other, it would be helpful to document the instances where a clean install is necessary, and include a reminder that your DB config information will be lost.

Adjunct to this is the fact that existing Postgres layers in a project have no reference to the database they came from.  If you select "Update SQL Layer" in the layer context menu, all the layers are listed as Virtual layers.  There is no reference to the database they are loaded from, or any means of modifying the source.

---

- [qgis-bin_2018-02-27_11-43-08.png](https://issues.qgis.org/attachments/download/12290/qgis-bin_2018-02-27_11-43-08.png) (rmercer -)

**Comment by alexbruy** [comment]
Should we close this?

**Comment by nyalldawson** [comment]
Yes, it won't be fixed now
