### ISSUE TITLE
Context menu items in "OWS" Browser group not working

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26150]
Author Name: **Andreas Wicht** (@andywicht)
Original Redmine Issue: [18259](https://issues.qgis.org/issues/18259)
Affected QGIS version: 3.0.0
Redmine category:browser

---
When using the context menu on a browser item in the group "OWS" the click does not do anything (e.g. edit or delete).
Items can only be edited or deleted in their native group (e.g. "WMS").

**Comment by alexbruy** [comment]
Probably related to #24841

**Comment by gioman** [comment]
Closing as the plan is to remove that OWS thing anyway.
