### ISSUE TITLE
Spatialite's views not supported in Layout Atlas

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26159]
Author Name: **Simon Falceri** (Simon Falceri)
Original Redmine Issue: [18268](https://issues.qgis.org/issues/18268)
Affected QGIS version: 3.0.0
Redmine category:map_composer/printing

---
When I set in Atlas Layout a spatialite 4.3 view as coverage vector, not work very well.

**Comment by nyalldawson** [comment]
Caused by a view which doesn't return a unique id field -- this is a requirement
