### ISSUE TITLE
XYZ tiles - add possibility to import/export saved connections

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26176]
Author Name: **Yaroslav Vasyunin** (@jarickkk)
Original Redmine Issue: [18285](https://issues.qgis.org/issues/18285)

Redmine category:browser

---
It's already here for WMS, WFS, PostreSQL and other connection types, where you can click 'Save' or 'Load' buttons in Data Source Manager. It would be convenient to have the same functionality for XYZ Tiles connections.

**Comment by roya0045** [comment]
You can export and import all XYZ connections from the browser, which is far more convenient.

**Comment by alexbruy** [comment]
Already fixed in master.
