### ISSUE TITLE
Filter expression on virtual layer is not saved

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26189]
Author Name: **Stefan Rey** (@partas1982)
Original Redmine Issue: [18298](https://issues.qgis.org/issues/18298)
Affected QGIS version: 3.0.0
Redmine category:virtual_layers

---
If I formulate a filter query on a virtual layer, the filter is lost when I save the QGIS Project, close and reopen it again.

**Comment by alexbruy** [comment]
Closed in favor of #27234 which is more general.

**Comment by elpaso** [comment]
Reopening because this seems an independent issue from #27234
