### ISSUE TITLE
QGIS3: menu is too long

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26200]
Author Name: **Tobias Wendorff** (Tobias Wendorff)
Original Redmine Issue: [18309](https://issues.qgis.org/issues/18309)
Affected QGIS version: 3.0.0
Redmine category:gui

---
The edit menu is too long for screen I'm currently working on :(
In other applications, it's possible to scroll down using the mouse-wheel. This doesn't work in QGIS 3.0.0.

---

- [offthescreen.png](https://issues.qgis.org/attachments/download/12319/offthescreen.png) (Tobias Wendorff)

**Comment by alexbruy** [comment]
Is this still an issue with latest master? For me menu expands into two columns and all items are accessible.

**Comment by alexbruy** [comment]
Closed for the lack of feedback. Please reopen if necessary.
