### ISSUE TITLE
Zooming in causes canvas to go blank

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26212]
Author Name: **Patrick Dunford** (@enzedrailmaps)
Original Redmine Issue: [18322](https://issues.qgis.org/issues/18322)
Affected QGIS version: 3.0.0
Redmine category:map_canvas

---
I just started using a project in Qgis 3 and it has some raster images loaded in the background. Quite often when I zoom in, the canvas goes completely blank and never redraws. This behaviour has never been seen in 2.18

---

- [Screenshot_2018-03-06_03-03-54.png](https://issues.qgis.org/attachments/download/12361/Screenshot_2018-03-06_03-03-54.png) (Patrick Dunford)

**Comment by roya0045** [comment]
Is still still occuring?

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
