### ISSUE TITLE
QGIS 2.18.16/3.0 Renders Multipolygon Shapefile Incorrectly

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26233]
Author Name: **Ralph Tee** (@ralphtee)
Original Redmine Issue: [18343](https://issues.qgis.org/issues/18343)
Affected QGIS version: 3.4.4
Redmine category:map_canvas

---
QGIS 2.18.16 and 3.0 incorrectly renders a multipolygon loaded from SHP. Please see screen shot below. The arrows point to locations which should be holes. A copy of the data is attached - one in SHP and one in SQLite (DB).

![image](https://i.stack.imgur.com/Zs75x.png)

The exact same multipolygon, when QGIS loaded it from SQLite (DB), was rendered correctly. Please see screen shot below.

![image](https://i.stack.imgur.com/iQ3bh.jpg)

If ArcMap 10.2 loads the SHP, the result was as in the screen shot below.

![image](https://i.stack.imgur.com/NrNy4.jpg)

---

- [sample.zip](https://issues.qgis.org/attachments/download/12362/sample.zip) (Ralph Tee)
- [Problem.png](https://issues.qgis.org/attachments/download/12363/Problem.png) (Ralph Tee)

**Comment by SrNetoChan** [comment]
Can't reproduce on QGIS 3.17 (master https://github.com/qgis/QGIS/commit/fba5093f18), nor in QGIS 3.16.3, but it was still happening on 3.10.14 (tested on linux)

I think we can close this one @gioman
