### ISSUE TITLE
DB Manager: import layer into Postgis fails with "Error 5 Creation of fields failed."

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26246]
Author Name: **Rui Pedro Henriques** (Rui Pedro Henriques)
Original Redmine Issue: [18356](https://issues.qgis.org/issues/18356)
Affected QGIS version: 3.4.4
Redmine category:db_manager

---
When trying to import a layer to Postgis I get "Error 5 Creation of fields failed."
The table and fields id and geom are created on the DB.

It was tested on QGIS 2.18.15/win 10 and QGIS 2.18.0 on MacOS.

---

- [Screen Shot 2018-03-06 at 15.59.57.png](https://issues.qgis.org/attachments/download/12366/Screen%20Shot%202018-03-06%20at%2015.59.57.png) (Rui Pedro Henriques)
- [pt_conc_grid25_4326_clip.gpkg](https://issues.qgis.org/attachments/download/12367/pt_conc_grid25_4326_clip.gpkg) (Rui Pedro Henriques)
- [bug.JPG](https://issues.qgis.org/attachments/download/14409/bug.JPG) (Federico Gianoli)

**Comment by gioman** [comment]
The error message is clearer now

`ERROR: column name "xmin" conflicts with a system column name`

as "xmin" is a reserved column name in pgsql https://www.postgresql.org/docs/12/ddl-system-columns.html
