### ISSUE TITLE
Rotate tool doesn't work for newly created points in transaction group context

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26252]
Author Name: **Regis Haubourg** (@haubourg)
Original Redmine Issue: [18362](https://issues.qgis.org/issues/18362)
Affected QGIS version: 3.3(master)
Redmine category:digitising

---
When creating new points with PostgreSQL transaction groups activated, it is impossible to select that point with the rotate tool. 
Just moving the point with node tool will restore that feature. 
So I guess there is something not wired correctly between the snapping index and the rotateTool

QGIS3, master and QGIS 2.18.17 are concerned

**Comment by lbartoletti** [comment]
@haubourg still true with latest versions?

**Comment by gioman** [comment]
@haubourg ping

**Comment by gioman** [comment]
Closing for lack of feedback.
