### ISSUE TITLE
Delete multiple connections based on selection in browser not possible

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26276]
Author Name: **lars Lingner** (@gislars)
Original Redmine Issue: [18386](https://issues.qgis.org/issues/18386)
Affected QGIS version: 3.0.0
Redmine category:data_source_manager

---
In the QGis data source browser tree I can easily see and add tables to the current project. In the context menu is the option "Add Selected Layer(s) to Canvas". There is also a entry "Delete Table" which only deletes one table regardless how many tables are actually selected.

I assumed I can also delete multiple tables in one go, but only the table with the name I clicked on gets deleted. 

I'm unsure if this qualifies as bug, but the behavior is not consistent in my opinion. I would expect all selected items are used for the action I can pick from the context menu.

Within the QGis DB Manager I can't do a multi selection, so that is more consistent to me.

QGIS version 3.0.0-Girona
QGIS code revision 0def61c

**Comment by pathmapper** [comment]
This issue exists also for `WMS` / `WFS` / `XYZ Tiles` connections:

![delete_connections](https://user-images.githubusercontent.com/20856381/97951753-85fcb680-1d9b-11eb-9478-3c84a7c2a3e9.gif)

**Comment by nyalldawson** [comment]
Deleting multiple tables is supported on current versions, but not multiple stored connections
