### ISSUE TITLE
Additional warp parameters under "Advanced parameters"

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26280]
Author Name: **Brett Hankerson** (Brett Hankerson)
Original Redmine Issue: [18390](https://issues.qgis.org/issues/18390)

Redmine category:processing/gdal
Assignee: Giovanni Manghi

---
Please make possible the input of additional warp parameters in the processing tools. Conceivably in the same way that additional creation parameters are now available

---

- [creation parameters.PNG](https://issues.qgis.org/attachments/download/12390/creation%20parameters.PNG) (Brett Hankerson)

**Comment by alexbruy** [comment]
Implemented in c224a01
