### ISSUE TITLE
Starting A new project loading osm xyz layer does not zoom to extent, but stays on 0,0 scale 1:1700

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26298]
Author Name: **Richard Duivenvoorde** (@rduivenvoorde)
Original Redmine Issue: [18409](https://issues.qgis.org/issues/18409)
Affected QGIS version: 3.1(master)
Redmine category:browser

---
Since some days with current 3.1 master if I start a fresh project and load OSM as xyz it will not zoom to 'world', but stays on 0,0 scale 1:1700. 

Meaning I'm seeing a nice blue screen and I have to either zoom out a couple of times, or use 'Zoom to Layer'.
Before I always zoomed to the world extent of osm.

To reproduce:
- remove ~/.local/share/QGIS to be sure you have a clean profile
- start QGIS (and not it starts in EPSG:4326)
- from browser open osm layer from XYZ tiles
- see bleu screen as in attached image

Note that if you then resize the screen, 
Remove the osm layer
Load the osm layer again: all is fine: you will see the world.

---

- [-Untitled Project - QGIS 30749ef80c_339.png](https://issues.qgis.org/attachments/download/12405/-Untitled%20Project%20-%20QGIS%2030749ef80c_339.png) (Richard Duivenvoorde)

**Comment by alexbruy** [comment]
Seems already fixed in 3.10/master. Please reopen if necessary.

**Comment by rduivenvoorde** [comment]
@alexbruy thanks for checking (and closing) these issues! 
You  are right, current version is ok. Probably an artifact from the upgrading of proj etc.
