### ISSUE TITLE
Error exporting layout with "." (full stop) in filename

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26308]
Author Name: **Brett Hankerson** (Brett Hankerson)
Original Redmine Issue: [18419](https://issues.qgis.org/issues/18419)
Affected QGIS version: 3.0.0
Redmine category:map_composer/printing

---
Receive the message "Cannot write to <FILE_LOCATION>. This file may be open in another application." The file is not open in another application.

**Comment by nyalldawson** [comment]
Duplicate of #26463
