### ISSUE TITLE
Advanced setting editing are reset after closing of Options GUI

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26327]
Author Name: **Luigi Pirelli** (@luipir)
Original Redmine Issue: [18439](https://issues.qgis.org/issues/18439)
Affected QGIS version: 3.0.0
Redmine category:gui

---
Any advanced setting is correctly set in the ini file during editing, but any change is lost just after the Options GUI is closed with OK button

mSettings in QgsOptions seems not be the same instance of settings of the QgsSettingsTree

**Comment by gioman** [comment]
@luipir still true?

**Comment by luipir** [comment]
I think it's still valid... as far as I remember, there is another more recent issue opened regarding this.... looking for it

**Comment by damateos** [comment]
Hi,
I just test it and still true, both  the bug and the workaround.

e.g.:
Options>Advanced>SHOW_CRS_DEF   I change value from true to false + OK button.  -> The change don't persist
Options>Advanced>SHOW_CRS_DEF   I change value from true to false + ESC key  -> The change persist

**Comment by luipir** [comment]
tnx @damateos to confirm... @gioman is it ok as feedback for this long standing issue?

**Comment by Pedro-Murteira** [comment]
Still valid on QGIS 3.22.3.

**Comment by alexbruy** [comment]
Fixed by https://github.com/qgis/QGIS/pull/51295.
