### ISSUE TITLE
ArcMap style clipping in QGIS 3.0

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26325]
Author Name: **eino jaskari** (eino jaskari)
Original Redmine Issue: [18436](https://issues.qgis.org/issues/18436)

Redmine category:editing

---
Hi,
I'd like to have ArcMap style clipping feature in QGIS 3.0. There is a plugin (https://github.com/demarcog/Clipper) for QGIS 2.xx, but it does not work for 3.xx.
Basically the clipper cuts all intersecting shapes, like overlaying polygons, with the boundaries of a selected polygon. It also DOES NOT create a new file, like the clip-processing tool currently does in QGIS, but instead it manages to modify the layer itself. So if one layer has 5 polygons that overlap, I select one of the polygons and click "clipper -button", other polygons within the same layer are cut with the boundaries of a selected polygon directly within the layer and it does not even ask you to create a new layer. There is also a merger tool build in QGIS, so this just does the opposite - kind of.
Clipper plugin ( https://github.com/demarcog/Clipper ) had some issues with PostGis functionality. It would be grate if QGIS 3.0 had build in clipper that supports all data formats that are supported by the program itself, including PostGis, Oracle, Shapefile, etc...

---

- [Selection_342.png](https://issues.qgis.org/attachments/download/12438/Selection_342.png) (Richard Duivenvoorde)
- [p1.JPG](https://issues.qgis.org/attachments/download/12449/p1.JPG) (eino jaskari)
- [p2.JPG](https://issues.qgis.org/attachments/download/12450/p2.JPG) (eino jaskari)
- [p3.JPG](https://issues.qgis.org/attachments/download/12451/p3.JPG) (eino jaskari)
- [p4.JPG](https://issues.qgis.org/attachments/download/12452/p4.JPG) (eino jaskari)
- [p5.JPG](https://issues.qgis.org/attachments/download/12453/p5.JPG) (eino jaskari)

**Comment by alexbruy** [comment]
As Processing "Clip" algorithm now supports in-place mode, can we close this?

**Comment by j-lippmann** [comment]
Im not sure for closing, because the clipping workflow of the clipping plugin is better than edit in place for often clipping actions while long digitising  sessions.
