### ISSUE TITLE
Option to add non-spatial attribute table from plain SQLite database

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26320]
Author Name: **Arjan Mossel** (Arjan Mossel)
Original Redmine Issue: [18431](https://issues.qgis.org/issues/18431)

Redmine category:data_provider/ogr

---
The docs say "QGIS allows you to load spatial and non-spatial layers. This currently includes tables supported by OGR [...]".

I see that "OGR optionally supports spatial and non-spatial tables stored in SQLite 3.x database files." (http://www.gdal.org/drv_sqlite.html)

But it doesn't work for a plain SQLite database (trying to add it from the Database manager):

```
dbname='/path/to/database.sqlite' table="attribute_table" sql= is an invalid layer - not loaded

```

Layers in the SQLite database are also not displayed in the browser panel, although a spatial table listed in geometry_columns can succesfully be added.

**Comment by roya0045** [comment]
Should be fixed by #9285 and others.
