### ISSUE TITLE
Warn when trying to save GeoJSON in SRS besides WGS84

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26338]
Author Name: **Calvin Metcalf** (Calvin Metcalf)
Original Redmine Issue: [18450](https://issues.qgis.org/issues/18450)

Redmine category:vectors

---
The other day I asked somebody for a file as GeoJSON and they gave it to me in a projected CRS since the spec is now more prescriptive about projections it might be a good idea to have some sort of warning when saving GeoJSON in a CRS as there is a good chance it could be a mistake.

**Comment by alexbruy** [comment]
Related issue #16404
