### ISSUE TITLE
Data Source Manager | PostgreSQL doesn't clear selected layers in list after you close

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26331]
Author Name: **David Mancini** (@weifageo)
Original Redmine Issue: [18443](https://issues.qgis.org/issues/18443)
Affected QGIS version: 3.0.0
Redmine category:data_source_manager

---
Hi there,

Just wanted to submit a minor issue I've noticed in the QGIS 3.0 early adopters edition.  When I go to add some layers from a PostgreSQL/PostGIS database, the layers I've selected don't clear after I click on Add and Close.  I only noticed this when I went to add in some more layers, not realizing the originals were still selected.  It adds the new selected item as well as the previously selected items if you fail to notice and deselect.

On the previous version 2.18, no selections were saved after this window closes, it started fresh each time it opens.  Just a minor thing but thought it was worth mentioning for people who use a lot of PostgreSQL/PostGIS layers.

Keep up the great work QGIS!!!

**Comment by alexbruy** [comment]
This is a consistent behaviour across all Datasource Manager tabs
