### ISSUE TITLE
Enforced constraints not working in attribute table

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26343]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [18455](https://issues.qgis.org/issues/18455)
Affected QGIS version: 3.1(master)
Redmine category:attribute_table

---
In the layer properties --> attribute form tab, select a field and add constraints + check the enforce constraint option: In my case, i checked the options for "not null" and "unique". 
When creating a feature, the constraints options work well in the form, disabling the ok button when value does not comply with constraint.
However, when editing existing field in the attribute table, i can add null value or add an existing value (hence, not unique) and i can save the changes.--> the field does not respect the constraints.

**Comment by gioman** [comment]
Closing in favor of https://github.com/qgis/QGIS/issues/29721 where there have been a lengthy discussion.
