### ISSUE TITLE
Relationship one_to_many

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26345]
Author Name: **Alessandro Della Libera** (Alessandro Della Libera)
Original Redmine Issue: [18457](https://issues.qgis.org/issues/18457)
Affected QGIS version: 3.0.0
Redmine category:relations
Assignee: Matthias Kuhn

---
QGiS3 doesn' t correctly recognize the 1_N relations between two tables without geographical characteristics, set in the project properties. The form of visualization and change data doesn't correctly visualize the data.
In version 2.8.16 this has correctly been done. Even if you save a working project version 2.18.16 in version 3, it loses the characteristics and the form doesn't display the data of the child table.
Regards
Alessandro

---

- [1_many_relations.png](https://issues.qgis.org/attachments/download/12461/1_many_relations.png) (Alessandro Della Libera)
- [1_many_form_error.png](https://issues.qgis.org/attachments/download/12462/1_many_form_error.png) (Alessandro Della Libera)
- [1_many_relations_v2-18-16.png](https://issues.qgis.org/attachments/download/12463/1_many_relations_v2-18-16.png) (Alessandro Della Libera)
- [paths.sql](https://issues.qgis.org/attachments/download/12531/paths.sql) (Etiënne Thomassen)
- [qgis2_18_17.PNG](https://issues.qgis.org/attachments/download/12532/qgis2_18_17.PNG) (Etiënne Thomassen)
- [qgis3_0_1.PNG](https://issues.qgis.org/attachments/download/12533/qgis3_0_1.PNG) (Etiënne Thomassen)

**Comment by gioman** [comment]
> ), but the form to edit the attibutes of the children within the parents window is not there.

Probably fixed a long ago, closing (as it works now).
