### ISSUE TITLE
QGIS 3.0.0 crashed while opening a PostGRES/PostGIS layer

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26348]
Author Name: **JW van Aalst** (@jwva)
Original Redmine Issue: [18460](https://issues.qgis.org/issues/18460)
Affected QGIS version: 3.0.0
Redmine category:data_provider/postgis

---
While opening a new simple PostGRES/PostGIS layer in Windows 10 / QGIS 3.0.0, the following error report was generated: 

Crash ID: 29a2e8cc4e01d216bae9a72dfd14e7f2587c1251

Stack Trace

QEventDispatcherWin32::staticMetaObject :
QgsStatisticalSummaryDockWidget::layerChanged :
QMetaObject::activate :
QgsMapLayerComboBox::layerChanged :
QMetaObject::activate :
QAbstractItemModel::endInsertRows :
QSortFilterProxyModel::insertRows :
QSortFilterProxyModel::sortRole :
QSortFilterProxyModel::`default constructor closure' :
QMetaObject::activate :
QAbstractItemModel::endInsertRows :
QgsMapLayerModel::addLayers :
QMetaObject::activate :
QgsProject::layersAdded :
QMetaObject::activate :
QgsMapLayerStore::layersAdded :
QgsMapLayerStore::addMapLayers :
QgsProject::addMapLayers :
QgisApp::addDatabaseLayers :
QMetaObject::activate :
QgsDataSourceManagerDialog::addDatabaseLayers :
QMetaObject::activate :
QgsAbstractDataSourceWidget::addDatabaseLayers :
registerGui :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
QgisApp::dataSourceManager :
QgisApp::identify :
QMetaObject::activate :
QAction::activate :
QAction::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QShortcutMap::dispatchEvent :
QShortcutMap::tryShortcut :
QWindowSystemInterface::handleShortcutEvent :
QGuiApplicationPrivate::processKeyEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.0.0-Girona
QGIS code revision: 001c80b0c3
Compiled against Qt: 5.9.2
Running against Qt: 5.9.2
Compiled against GDAL: 2.2.3
Running against GDAL: 2.2.3

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.16299

**Comment by gioman** [comment]
Support for PostGIS rasters has been rewritten for QGIS 3.16, this is likely to be not valid anymore. Reopen if necessary.
