### ISSUE TITLE
Make the Symbol Layers List resizable

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26347]
Author Name: **Michel Stuyts** (@mstuyts)
Original Redmine Issue: [18459](https://issues.qgis.org/issues/18459)

Redmine category:gui

---
When you use multiple Symbol Layers to style a layer, the Symbol Layers List area in the Layer Styling Panel and Layer Properties window is too small to have good overview of the build up structure of Symbol Layers. With the use of multiple Geometry Generators you have many Symbol Layers. It would be good to be able to resize this Symbol Layers List area.

![SymboLayersList.JPG](https://issues.qgis.org/attachments/download/12464/SymboLayersList.JPG)

---

- [SymboLayersList.JPG](https://issues.qgis.org/attachments/download/12464/SymboLayersList.JPG) (Michel Stuyts)

**Comment by BenjaminRiley** [comment]
The symbol layers area expands with the window on 3.10.8. I think this issue can be closed.
