### ISSUE TITLE
Need to close the layer properties dialog before a newly created field appears in Attribute form

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26350]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [18462](https://issues.qgis.org/issues/18462)
Affected QGIS version: 3.1(master)
Redmine category:forms

---
Create a temporary layer and add a new integer field
Apply
Check the joins tab, the new field is available (even if you did not apply)
Check the Attribute Forms tab: it's missing.
The new field will appear in the Attribute form tab only if you close the layer properties dialog in the meantime.

---

Related issue(s): #28569 (relates)
Redmine related issue(s): [20749](https://issues.qgis.org/issues/20749)

---

**Comment by Pedro-Murteira** [comment]
This seems to work fine on versions 3.16.15 e 3.22.2. The newly created field is instantly avaiable on Attribute form.

**Comment by gioman** [comment]
This is still valid.

**Comment by DelazJ** [comment]
Sorry @Pedro-Murteira I didn't reply to you.
