### ISSUE TITLE
Distorted image, but fine on thumbnail

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26368]
Author Name: **Mina Jambajantsan** (Mina Jambajantsan)
Original Redmine Issue: [18480](https://issues.qgis.org/issues/18480)
Affected QGIS version: 3.0.0
Redmine category:rasters

---
Dear QGIS,
I'm trying to make a contour map with DEM tiff files, but I have a distorted map which looks perfect on thumbnail.
How can I fix it?
As you can see, the ruins on the thumbnail are nearly cube shaped, but on the main page it's more like brick-shaped.
Thank you for your help
Warmest wishes,
Mina

---

- [Screenshot 2018-03-19 13.00.59.png](https://issues.qgis.org/attachments/download/12474/Screenshot%202018-03-19%2013.00.59.png) (Mina Jambajantsan)

**Comment by roya0045** [comment]
Just seem like a projection thing, I think this can be disregarded.
