### ISSUE TITLE
Layer style effects not supported by the legend

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26362]
Author Name: **Borys Jurgiel** (@borysiasty)
Original Redmine Issue: [18474](https://issues.qgis.org/issues/18474)
Affected QGIS version: 3.1(master)
Redmine category:map_legend

---
They are included neither to the Layers panel nor to the printed legend.
Also they cause a "Warning: Unsupported blend" debug message.

---

- [LayerEffects.png](https://issues.qgis.org/attachments/download/12471/LayerEffects.png) (Borys Jurgiel)

**Comment by nyalldawson** [comment]
Fixed since some years
