### ISSUE TITLE
Recent Projects startup screen truncates filenames containing periods

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26373]
Author Name: **Patrick Dunford** (@enzedrailmaps)
Original Redmine Issue: [18485](https://issues.qgis.org/issues/18485)
Affected QGIS version: 3.3(master)
Redmine category:project_loading/saving

---
If a project filename contains periods, the filename is truncated at the first period when displayed in the Recent Projects startup screen.

The code should truncate the filename at the last period, not the first one.

---

- [Screenshot_2018-03-20_16-24-17.png](https://issues.qgis.org/attachments/download/12492/Screenshot_2018-03-20_16-24-17.png) (Patrick Dunford)
- [Screenshot_2018-07-12_05-35-53.png](https://issues.qgis.org/attachments/download/12954/Screenshot_2018-07-12_05-35-53.png) (Patrick Dunford)
- [config.tar.gz](https://issues.qgis.org/attachments/download/12955/config.tar.gz) (Patrick Dunford)

**Comment by alexbruy** [comment]
Not reproducible on master.

**Comment by alexbruy** [comment]
Closed for the lack of feedback. Please reopen if necessary.
