### ISSUE TITLE
Label toolbar tools cannot select label when map is rotated

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26372]
Author Name: **Andrew Kovacs** (Andrew Kovacs)
Original Redmine Issue: [18484](https://issues.qgis.org/issues/18484)
Affected QGIS version: 3.0.0
Redmine category:labelling

---
The Show/Hide Labels and Diagrams and Move Labels/Diagrams tools do not function as expected when the map is rotated for at least point vector layers. When you click or highlight the label, it does not detect it. However, selecting a nearby area where the label is not located will hide it. It is apparently not transforming the coordinates on its updated location on the screen after rotation for the click listener.

It does not matter if the label has been moved first and then rotated, or if you first rotate and then try to move the label.

When changing the rotation back to 0, everything works as expected.

**Comment by nyalldawson** [comment]
Duplicate of #25384
