### ISSUE TITLE
Crash on opening a .qgs project in a second instance of QGIS 3.0

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26371]
Author Name: **Roy Nicol** (Roy Nicol)
Original Redmine Issue: [18483](https://issues.qgis.org/issues/18483)
Affected QGIS version: 3.0.0
Redmine category:project_loading/saving

---
## User Feedback

Dear QGIS Developers,

This crash happened when I opened a .qgs project in a *second* instance of QGIS 3.0.

The first instance had been operating normally. The second instance launched normally, but crashed when I actuallly opened the other project I wanted to work in.

This report is supplied for your information and there is no need to follow up with me, unless you need any further information. In that case please don't hesitate to contact me. Thank you.

Sincerely,
Roy_N

## Report Details

*Crash ID*: 234d61df91e8ad072933ab09c135d25d81b07261

*Stack Trace*
```
QString::indexOf :
QDir::fromNativeSeparators :
QFileSystemWatcher::trUtf8 :
QFileInfo::exists :
QgsStatusBarScaleWidget::userScale :
QModelIndex::flags :
QAbstractItemView::focusInEvent :
QWidget::event :
QFrame::event :
QAbstractScrollArea::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::setFocusWidget :
QWidget::setFocus :
QApplication::setActiveWindow :
QApplicationPrivate::notifyActiveWindowChange :
QGuiApplicationPrivate::processActivatedEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QCoreApplication::processEvents :
QgisApp::addProject :
QgisApp::fileOpen :
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

```

*QGIS Info*
QGIS Version: 3.0.0-Girona
QGIS code revision: 001c80b0c3
Compiled against Qt: 5.9.2
Running against Qt: 5.9.2
Compiled against GDAL: 2.2.3
Running against GDAL: 2.2.3

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.16299

**Comment by SrNetoChan** [comment]
No sample data or project. Can't reproduce on windows in any of the recent version. Can we close this one @gioman ?
