### ISSUE TITLE
Addind map layers in expression builder adds layer ID

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26400]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [18512](https://issues.qgis.org/issues/18512)
Affected QGIS version: 3.0.0
Redmine category:expressions

---
Currently, i can write in expression builder something like get_feature( 'streets', 'name','main st') to return a 'main st' from the streets layer.
To improve the UX, a "map layers" group is added and now I no longer have to remember what was the exact name of the layer; double-click is good enough.
Issue is that instead of the recognizable _streets_, i get the layer Id which is something like streets_5d217552_8e06_41de_8b23_e3e9fc27d094, very hard to identify and which imho does not ease expression review.
Could be handier to add the layer name, instead?

**Comment by alexbruy** [comment]
Can be closed?

**Comment by DelazJ** [comment]
I think there are points that could be feature request but... just close, please. Thanks.

**Comment by alexbruy** [comment]
> I think there are points that could be feature request but...

Would you mind open new tickets for these?
