### ISSUE TITLE
Crash when selecting Font after adding a label in a layout

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26416]
Author Name: **PJ Lightning** (PJ Lightning)
Original Redmine Issue: [18528](https://issues.qgis.org/issues/18528)
Affected QGIS version: 3.0.0
Redmine category:labelling

---
I created a new layout, added an image and an arrow, then added a label, went to item properties, typed in the text I wanted, then clicked on the font button, and QGIS crashed.
Win 7 pro 64 bit. QGIS 3.0.0 Girona

## User Feedback

I had added a label to print composer and clicked on the font button. Then QGIS crashed

## Report Details

*Crash ID*: dc851c90394e23a5b05dc00e2d7a1bdb6176fa75

*Stack Trace*
```
QFontDatabase::applicationFontFamilies :
QFontDatabase::font :
QFontDialog::~QFontDialog :
QFontDialog::testOption :
QMetaObject::activate :
QFontDialog::changeEvent :
QMetaObject::activate :
QItemSelectionModel::setCurrentIndex :
QAbstractItemView::setCurrentIndex :
QFontDialog::testOption :
QFontDialog::getFont :
QFontDialog::getFont :
QFontDialog::getFont :
QgsGuiUtils::getFont :
QgsFontButton::showSettingsDialog :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
TranslateMessageEx :
TranslateMessage :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

```

*QGIS Info*
QGIS Version: 3.0.0-Girona
QGIS code revision: 001c80b0c3
Compiled against Qt: 5.9.2
Running against Qt: 5.9.2
Compiled against GDAL: 2.2.3
Running against GDAL: 2.2.3

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by nyalldawson** [comment]
Cannot reproduce -- likely a local or upstream (qt) issue

**Comment by e42mercury** [comment]
I can reproduce this error; it's very consistent. QGIS 3.16.0, MacOS
