### ISSUE TITLE
[osx][layouts] "Page Setup" and "Print..." not doing anything

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26423]
Author Name: **jb Peter** (jb Peter)
Original Redmine Issue: [18535](https://issues.qgis.org/issues/18535)
Affected QGIS version: 3.6.0
Redmine category:mac_os_specific

---
I am not able to open the "Page Setup" and "Print..." windows on QGIS 3.0.0-3 layout window. Nothing happen when I click on these menu items.

**Comment by gioman** [comment]
> I am not able to open the "Page Setup" and "Print..." windows on QGIS 3.0.0-3 layout window. Nothing happen when I click on these menu items.

duplicate of https://github.com/qgis/QGIS/issues/30791
