### ISSUE TITLE
Atribute table crashes

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26424]
Author Name: **Leonardo  Nazareth** (Leonardo  Nazareth)
Original Redmine Issue: [18536](https://issues.qgis.org/issues/18536)
Affected QGIS version: 3.0.0
Redmine category:unknown

---
## User Feedback

I selected many features, opened the attribute table and click to put all features selected on top.

After that I´ve tried to unselect a few features,holding the 'ctrl' button on keyboard I clicked in 1 feature and it´s ok (unselected that one), but when I try to do that in the second feature the QGIS crashed.

I try this 2 times to be sure thats the problem.

## Report Details

*Crash ID*: 23d0c4d9b06ffb260f854488e38c3b32b38f6ab9

*Stack Trace*
```
QgsAttributeTableModel::prefetchColumnData :
QgsAttributeTableFilterModel::sort :
QgsAttributeTableFilterModel::selectionChanged :
QMetaObject::activate :
QgsVectorLayer::selectionChanged :
QgsVectorLayer::deselect :
QgsFeatureSelectionModel::enableSync :
QgsAttributeTableView::eventFilter :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

```

*QGIS Info*
QGIS Version: 3.0.0-Girona
QGIS code revision: 001c80b0c3
Compiled against Qt: 5.9.2
Running against Qt: 5.9.2
Compiled against GDAL: 2.2.3
Running against GDAL: 2.2.3

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.16299

**Comment by roya0045** [comment]
Is this still occurring?

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
