### ISSUE TITLE
Auxillary Fields - when pressing 'enter' the entered values in the auxillary field disappear, but it is stored and is shown when reopening the attributetable

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26439]
Author Name: **Mie Winstrup** (Mie Winstrup)
Original Redmine Issue: [18551](https://issues.qgis.org/issues/18551)
Affected QGIS version: 3.1(master)
Redmine category:editing

---
I like the new feature with Auxillary Fields.

However when I:
1. Add a new auxillary field
1. Enable editing on this layer
1. Enter a value in this field in the attributetable
1. Press 'Enter'

The entered value disappear. However if I close the attributetable and open it again - the values is there. This can be quite confusing.
If I enter a text in a normal field (not an auxillaryfield) and press 'enter', the value is shown and does not disappear.

I think entering text in the auxillay field should work the same way as when entering text in a non-auxillary field.

Note - It works if I enter the text in the auxillaryfield and use the mouse to click on a new row, then the entered value is kept.

I have tested that this is an issue in both QGIS 3.0.1 and QGIS 3.1.0.

**Comment by alexbruy** [comment]
Seems already fixed. Please test latest 3.10 and master.

**Comment by gioman** [comment]
Closing for lack of further feedback.
