### ISSUE TITLE
Window Title does not update if project is loaded via Python console

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26443]
Author Name: **Peter Gipper** (Peter Gipper)
Original Redmine Issue: [18555](https://issues.qgis.org/issues/18555)
Affected QGIS version: 3.0.0
Redmine category:pyqgis_console

---
If a project is loaded with PyQGIS using the command @QgsProject.instance().read("path/to/project.qgs")@ the QGIS window title doesn't update to show the current project title. It updates after open and closing the project properties though.

**Comment by stev-0** [comment]
This can be closed as this no longer occurs
