### ISSUE TITLE
Toggling Hidden Widget doesn't do anything anymore

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26442]
Author Name: **Tudor Bărăscu** (@tudorbarascu)
Original Redmine Issue: [18554](https://issues.qgis.org/issues/18554)
Affected QGIS version: 3.5(master)
Redmine category:edit_widget

---
In attributes form, selecting a Hidden widget type to hide a field in the attribute table doesn't work anymore.
Also, if you already have the Hidden type, changing it to something else also doesn't do anything.
The changes don't propagate to the attribute table.

**Comment by signedav** [comment]
@tudorbarascu In the attribute table form view it's hidden. In the table it's not. But as far as I know it's not been hidden in QGIS 2.18 neither in the table. When I organize columns and uncheck the field or I select "hide column" it's hidden. After reopening it's still hidden. Can you confirm? 
Or is there a still existing misbehavior?

**Comment by m-kuhn** [comment]
In previous versions, the "hidden" widget toggled hiding it in the form and the table. Originally that was the only possibility to hide a field.

Meanwhile, there is much more granular control over where to hide and show widgets (drag and drop editor, organizing attribute table fields). Old projects are automatically migrated to the new concept (i.e. hidden widgets from 2.8? projects are hidden in the attribute table) but new projects will be setup accordingly.

Through this granular control there can now be "conflicting" settings (i.e. setting the widget type to "hidden" and in organize table setting it to "visible"), which is the root of this issue.

In my opinion we should treat widget visualization on forms via widgets and attribute table column configuration via organize attribute table, this is a clear concept without conflicts. I am afraid that any quick fix will have intransparent effects (implicitly changing options in the table from the widget or vice versa) and reduce configuration possibilities (no longer possible to have a autogenerated form with hidden fields and a table with all fields shown).

**Comment by tudorbarascu** [comment]
Hi guys,

@m-kuhn Totally agree on "In my opinion we should treat widget visualization on forms via widgets and attribute table column configuration via organize attribute table"

@signedav Retesting things, everything reported work ok now. I found the following issue while testing, with the steps to reproduce:

1. Toggle a widget to hidden
2. Go to the attribute table and while trying to make a column hidden via  "the organize columns dialog" another one gets hidden instead of the one selected.

Step 2 works ok if you don't do step 1.
All the best!

**Comment by signedav** [comment]
Thanks @tudorbarascu 
I cannot confirm your described behavior with the "another one gets hidden" but I agree that something is not okay here. While trying to reproduce I had the issue, that I toggle a widget in the properties to "hidden" and it's still not hidden in the attribute table. Sometimes it worked sometimes not. I would need to invest more time here to have a final idea.

**Comment by SrNetoChan** [comment]
I have tested this on 3.9. And all seems to work as expected. The behaviour in forms and table are isolated. More importantly, when you hide a field in the attribute table, it gets permanently hidden even if you close and open the table again.

I think we can close this one.
