### ISSUE TITLE
scales completely wrong with custom CRS

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26440]
Author Name: **Timur Aptikeev** (Timur Aptikeev)
Original Redmine Issue: [18552](https://issues.qgis.org/issues/18552)
Affected QGIS version: 3.0.0
Redmine category:gui

---
If make new systems in units=km,  like this - "EPSG:28410 Proj4: +proj=tmerc +lat_0=0 +lon_0=57 +k=1 +x_0=10500000 +y_0=0 +ellps=krass +towgs84=23.92,-141.27,-80.9,0,0.35,0.82,-0.12 +units=km +no_defs" 
then scale in  view is very wrong! 
Necessary 1:1 000  showing 1:38 264
Necessary 1:2 500  showing 1:95 661
Necessary 1:10 000  showing 1:382 644
Necessary 1:100 000  showing 1:3 826 440

---

- [Qgis-Scale-False.PNG](https://issues.qgis.org/attachments/download/12528/Qgis-Scale-False.PNG) (Timur Aptikeev)
- [Qgis-Scale-True.PNG](https://issues.qgis.org/attachments/download/12529/Qgis-Scale-True.PNG) (Timur Aptikeev)

**Comment by alexbruy** [comment]
Is this still a valid issue? If yes, please provide test data required to reproduce it.
