### ISSUE TITLE
Export to vector file failed.

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26459]
Author Name: **mike Lewis** (mike Lewis)
Original Redmine Issue: [18571](https://issues.qgis.org/issues/18571)
Affected QGIS version: 3.0.0
Redmine category:vectors

---
When trying to create any shapefile (via layer, create layer or save as)

I get an error as below

Export to vector file failed.
Error: Creation of data source failed (OGR error: sqlite3_open(rd.gpkg) failed: unable to open database file)
 
Export to vector file failed.
Error: Creation of layer failed (OGR error: Failed to create file ml.shp: Permission denied)

**Comment by alexbruy** [comment]
Please test with latest master

**Comment by alexbruy** [comment]
Closed for the lack of feedback.

**Comment by micbru91** [comment]
Im having the same problem. I have the latest version

**Comment by fcvf-jmail** [comment]
> Im having the same problem. I have the latest version

Running app from sudo user helped for me:
Run in terminal "sudo /Applications/QGIS.app/Contents/MacOS/qgis_process.app"
