### ISSUE TITLE
Value Relation and Relation reference widget: Entries are sorted although the option "Order by value" is NOT checked

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26468]
Author Name: **Manuel K** (Manuel K)
Original Redmine Issue: [18580](https://issues.qgis.org/issues/18580)
Affected QGIS version: 3.0.0
Redmine category:forms

---
*Value Relation and Relation reference widget:*

Entries are sorted alphabetically although the option "Order by value" is NOT checked

QGIS should take the order of the entries unchanged from the database if "Order by value" is NOT checked.

Data Source: PostGIS

**Comment by SrNetoChan** [comment]
Confirmed on 3.16.3.

**Comment by signedav** [comment]
This is kind of a dead setting. The `QgsRelationReferenceWidget` receives the setting orderByValue - but does not do anything with it. It's just ordered.

Question is now - since this issue persists since almost five years - does anybody request this setting? Or could this just be removed?
