### ISSUE TITLE
QGIS Composer Export Error - File in Use

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26463]
Author Name: **Matt Warner** (Matt Warner)
Original Redmine Issue: [18575](https://issues.qgis.org/issues/18575)
Affected QGIS version: 3.4.7
Redmine category:map_composer/printing

---
When exporting images to any format from the composer I often receive an error stating that the export file is open in another application and the export cannot be completed.  This occurs even if I am not overwriting an existing image.  This started happening with QGIS 3.0 and still exist in 3.01.  There was one instance where turning off Enable Antialiasing in the Image Export Options worked, but that is not a consistent fix.  It appears that the image exports work after a fresh restart of the entire computer, but after it gets locked or goes to sleep, you cannot export images at all.  I was able to export PDFs though.  

The computer is a Surface Pro 4 running Windows 10.

**Comment by nyalldawson** [comment]
I can't reproduce -- is this still an issue with 3.8?

**Comment by gioman** [comment]
Closing for lack of feedback.
