### ISSUE TITLE
Mismatch of languages in Advanced Settings panel

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26461]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [18573](https://issues.qgis.org/issues/18573)
Affected QGIS version: 3.1(master)
Redmine category:unknown

---
My OS locale is French and I've set the QGIS language to en-US.
While browsing Settings menu --> Options --> Advanced --> UI --> paneldialog, as you can see in the attached screenshot, there are some items that are shown in French and others in English (despite the whole GUI is in English).

---

- [advancedSettings.PNG](https://issues.qgis.org/attachments/download/12541/advancedSettings.PNG) (Harrissou Santanna)

**Comment by kannes** [comment]
I don't have the "paneldialog" tree in 3.18, is this still an issue? To me any keys in there should be kept English, as I guess Windows' registry does to.

**Comment by Pedro-Murteira** [comment]
Can confirm this issue on QGIS 3.22.3.

**Comment by alexbruy** [comment]
Seems partially fixed with the new settings framework. However, descriptions of some settings are still in English.
