### ISSUE TITLE
qgis doesn't save features added to a layer when source fields are deleted for a second time

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26460]
Author Name: **A B** (A B)
Original Redmine Issue: [18572](https://issues.qgis.org/issues/18572)
Affected QGIS version: 3.0.0
Redmine category:editing

---
see the video - after creation of layer, I've added features and successfully saved them, yet when repeating the workflow, features are not saved (lost forever - no change in filesize)
why do I do it this way? I want to draw the points quickly - without being forced to enter attributes for every single feature
tested on 3.0.0 and 2.14.9

---

- [bug_qgis_nosave.gif](https://issues.qgis.org/attachments/download/12540/bug_qgis_nosave.gif) (A B)

**Comment by SrNetoChan** [comment]
I believe QGIS + Shapefile needs at least an identifier field to work correctly. when you remove the ID, you remove that.

Alternativelly you can suppress the feature form after creation on QGIS options > digitizing Feature creation.

@gioman I would close this one.
