### ISSUE TITLE
Copy/paste Layer/Group menus vs Duplicate layer(s) action: redundancy?

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26478]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [18590](https://issues.qgis.org/issues/18590)
Affected QGIS version: 3.1(master)
Redmine category:gui

---
The Layer menu provides actions to "copy layer" and "Paste layer/group". But there's also a "Duplicate layers" action which does the job in one-go. Isn't there a redundancy? And why not keep only the latter (and extend its capability to group, because it's currently grayed when a group is selected)?
Also note that the duplicate action pastes the layer above the current selection while paste action places it at the bottom of the LAyers panel, which is not nice.

In the current state, imho better keep the "duplicate" action and remove the two others. Where the two others will make sense is if instead of placing the layers/groups at the bottom of the dialog, they paste them above the currently selected layer. In that case, i think we should then get rid of the duplicate shortcuts (and make the menus less crowded)

**Comment by alexbruy** [comment]
What should we do with this?

IMHO both actions should be kept, as Copy/Paste can work between different instances of QGIS, and Duplicate saves couple of mouse clicks.

**Comment by DelazJ** [comment]
Hi @alexbruy 
> IMHO both actions should be kept,

Yep! I did not get the scope of the copy/paste feature when I reported and I think there are different issues/features reported here: 
* allow duplicate to duplicate group(s),
* make copy/paste place the new layer above the active layer instead of at the bottom of the layers panel.

We better close this report and i will try to open separate ones.

**Comment by alexbruy** [comment]
Ok, closing.
