### ISSUE TITLE
"Duplicate layers" action does not work with memory layer

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26479]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [18591](https://issues.qgis.org/issues/18591)
Affected QGIS version: 3.4.4
Redmine category:map_legend

---
create a temporary layer (i used centroids alg on a layer)
right-click on the layer: the "Duplicate layer" action is grayed.
Click on Layer menu, the "Duplicate Layer(s)" action is *NOT* grayed. (Btw, it could be nice to have the same label). Click on that menu action, nothing happens. That tool however works if you use a not memory layer.

Also, you can however use the Copy and Paste layer actions in the Layer menu to duplicate the memory layer.

**Comment by alexbruy** [comment]
Already fixed in master: memory layers can be duplicated. Please reopen if necessary.

**Comment by agiudiceandrea** [comment]
For reference: fixed with Pull Request #30486 in commit 0c6dc879bf33c0559dbbef5c58ce016bcec1e274
