### ISSUE TITLE
Attribute table icons

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26483]
Author Name: **John Norton** (John Norton)
Original Redmine Issue: [18595](https://issues.qgis.org/issues/18595)
Affected QGIS version: 3.0.0
Redmine category:attribute_table

---
In the latest version (3.0) the icons on the attribute table toolbar have shrunk in size and are now rather difficult to read and select with mouse on a high resolution monitor. They really need to be the same size as on the main application window toolbars.

**Comment by alexbruy** [comment]
Duplicates #22450.
