### ISSUE TITLE
Cannot "run as system", worked in previous versions

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26499]
Author Name: **Thomas Pemberton** (Thomas Pemberton)
Original Redmine Issue: [18611](https://issues.qgis.org/issues/18611)
Affected QGIS version: 3.0.0
Redmine category:windows_package
Assignee: Thomas Pemberton

---
I am trying to deploy QGIS 3.0.0 on our campus.  We use Microsoft SCCM to deploy the software in a scripted fashion to many computers on campus.

I can run your install fine under an admin account using /S.  Microsoft SCCM uses the "local system" (i.e. god account) to install it on the computer.  When the install runs through Microsoft SCCM using /S it does not install the product at all and exits the install almost immediately.

I am willing troubleshoot more but I have not been able to find a way to get QGIS to spit out an install log either...

**Comment by roya0045** [comment]
Still true?

**Comment by gioman** [comment]
Closing for lack of feedback.
