### ISSUE TITLE
QGIS 3.0.1 Crash - Zooming in while moving node crashes QGIS

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26509]
Author Name: **Robert Coleman** (Robert Coleman)
Original Redmine Issue: [18621](https://issues.qgis.org/issues/18621)
Affected QGIS version: 3.0.0
Redmine category:editing

---
## User Feedback

Repeatable crash; select the move node tool and zoom in to greater than 8,000:1.

## Report Details

*Crash ID*: 7100edce5428b378f44494eaf03e93b8df8b6957

*Stack Trace*
```
QColorProfile::fromSRgb :
QColorProfile::fromSRgb :
QVectorPath::convertToPainterPath :
QRasterPaintEngine::stroke :
QPaintEngineEx::draw :
QPaintEngineEx::drawPath :
QgsSimpleLineSymbolLayer::renderPolyline :
QgsLineSymbolLayer::drawPreviewIcon :
QgsSymbol::drawPreviewIcon :
QgsSymbolLayerUtils::symbolPreviewPixmap :
QgsSymbolLegendNode::minimumIconSize :
QgsLayerTreeModel::invalidateLegendMapBasedData :
QMetaObject::activate :
QTimer::timerEvent :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32Private::sendTimerEvent :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

```

*QGIS Info*
QGIS Version: 3.0.1-Girona
QGIS code revision: a86bec25eb
Compiled against Qt: 5.9.2
Running against Qt: 5.9.2
Compiled against GDAL: 2.2.4
Running against GDAL: 2.2.4

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.16299

**Comment by PeterPetrik** [comment]
unable to replicate, please reopen if still the case with LTR release and give the exact instructions/project to test

![node_zoom](https://user-images.githubusercontent.com/804608/94922987-6da72c80-04bb-11eb-938d-96b27c807bd1.gif)
