### ISSUE TITLE
Paste image/graphic in Layout Manager

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26513]
Author Name: **Matthew Bodnar** (Matthew Bodnar)
Original Redmine Issue: [18625](https://issues.qgis.org/issues/18625)

Redmine category:map_composer/printing

---
Considering adding the ability to add an image or graphic (eg,'emf' file) to the layout Manager by copy and paste from external application.

**Comment by alexbruy** [comment]
Pasting images already implemented in master.
