### ISSUE TITLE
QGIS 3.0 Crash upon closing after having open large vrt raster

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26512]
Author Name: **David Aparicio** (David Aparicio)
Original Redmine Issue: [18624](https://issues.qgis.org/issues/18624)
Affected QGIS version: 3.0.0
Redmine category:gui

---
Crashed after having open a large vrt raster that contained 97 tif files. Each tif tile covering 1x1 deg area with 10800 x 10800 pixels each. And moving around to different locations of raster

## Report Details

*Crash ID*: 910541472b33408a637523b5b1ae8cc6cdadf0d4

*Stack Trace*
```
memcpy :
VSICreateCachedFile :
GDALRegister_Terragen :
GDALRegister_Terragen :
GDALRegister_GTiff :
GDALRasterBand::GetLockedBlockRef :
GDALRasterBand::IRasterIO :
GDALRegister_GTiff :
GDALProxyRasterBand::IRasterIO :
GDALRasterBand::RasterIO :
VRTSimpleSource::RasterIO :
VRTSourcedRasterBand::IRasterIO :
GDALRasterBand::RasterIO :
GDALWarpOperation::operator= :
GDALWarpOperation::operator= :
QgsSingleBandPseudoColorRenderer::block :
QgsBrightnessContrastFilter::block :
QgsHueSaturationFilter::block :
QgsRasterResampleFilter::block :
QgsRasterProjector::block :
QgsRasterIterator::readNextRasterPart :
QgsRasterDrawer::draw :
QgsRasterLayerRenderer::render :
QgsMapRendererParallelJob::renderLayerStatic :
QgsMapRendererParallelJob::renderingFinished :
QgsArchive::zip :
QgsImageOperation::flipImage :
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

```

*QGIS Info*
QGIS Version: 3.0.0-Girona
QGIS code revision: 001c80b0c3
Compiled against Qt: 5.9.2
Running against Qt: 5.9.2
Compiled against GDAL: 2.2.3
Running against GDAL: 2.2.3

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.15063

**Comment by roya0045** [comment]
This seems to be either a system limit or a vrt issue. Is this reproducible on a recent version?

**Comment by gioman** [comment]
Closing for lack of feedback.
