### ISSUE TITLE
QGIS3: WMTS detection doesn't work

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26521]
Author Name: **Tobias Wendorff** (Tobias Wendorff)
Original Redmine Issue: [18633](https://issues.qgis.org/issues/18633)
Affected QGIS version: 3.0.0
Redmine category:web_services_clients/wms

---
When adding this WMTS to QGIS, it's not detected as WMTS and adding fails:
```http://sgx.geodatenzentrum.de/wmts_topplus_web_open
```

Having a look into the datastream using a proxy, this request is used:
```http://sgx.geodatenzentrum.de/wmts_topplus_web_open?SERVICE=WMS&REQUEST=GetCapabilities
```

Oops, so the GetCapabilities of WMS is used, not the one of WMTS. 
This one works: ```http://sgx.geodatenzentrum.de/wmts_topplus_web_open/1.0.0/WMTSCapabilities.xml
```

Since there's no switch in WMS/WMTS panel to select what kind of service it us, you should use a heuristic:
* if there's "wmts/WMTS" in the url, request @/1.0.0/WMTSCapabilities.xml@ OR
* try normal WMS GetCapabilities first, on error request WMTS capabilities.

Perhaps you could use a heuristic, which detects "WMTS" in the URL and then doe

This bug appears at least in build @d48818b492@.

**Comment by alexbruy** [comment]
Is this true with latest master?

**Comment by alexbruy** [comment]
Closed for the lack of feedback. Please reopen if necessary.
