### ISSUE TITLE
Symbol levels reset when changing style settings

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26547]
Author Name: **Klas Karlsson** (@klakar)
Original Redmine Issue: [18659](https://issues.qgis.org/issues/18659)
Affected QGIS version: 3.0.0
Redmine category:symbology

---
A line layer with a symbol layer order that is +not+ in the default order will apply properly, but when a style property for the line is changed, the symbol levels are reset to the default order.

Not sure if this is a regression...

![no_levels.png](https://issues.qgis.org/attachments/download/12578/no_levels.png)
Style with three layers, and no symbol levels.

![levels.png](https://issues.qgis.org/attachments/download/12577/levels.png)
Applying symbol levels so that drawing order change works.

But if I change for example the line width for anything in the styles, the symbol levels will revert to the starting drawing order for symbol levels. For complex rule based layers with multiple styles and symbol levels, this is a problem.

WORKAROUND:
Make sure your symbol layers are in the correct drawing order before applying symbol levels. 

It may be a small problem, but symbol level reordering feels broken...

---

- [levels.png](https://issues.qgis.org/attachments/download/12577/levels.png) (Klas Karlsson)
- [no_levels.png](https://issues.qgis.org/attachments/download/12578/no_levels.png) (Klas Karlsson)

**Comment by anitagraser** [comment]
I can confirm this in master:

Symbol levels are set up:

![image](https://user-images.githubusercontent.com/590385/63640016-664c0780-c69b-11e9-967a-38cab5af9e3c.png)

Whenever any symbol layer is changed, all symbol levels are reset to zero:

![image](https://user-images.githubusercontent.com/590385/63640020-7532ba00-c69b-11e9-9265-7bc2e0ce8b2e.png)

I've also observed this behavior when making changes to the symbol of a categorized renderer. All symbol level settings are lost when the symbol is changed.

**Comment by nirvn** [comment]
Just to add on this, the symbol levels aren't really reset to zero, they are reset to the last values upon opening the style panel / switch the style panel's layer focus.
