### ISSUE TITLE
UCS - 2000 coordinate systems - correct params towgs84

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26552]
Author Name: **Denys Dudko** (Denys Dudko)
Original Redmine Issue: [18664](https://issues.qgis.org/issues/18664)

Redmine category:projection_support

---
Some time ago, the transition parameters from the UCS2000 datum to ETRS89 were published. 
http://dgm.gki.com.ua/files/uploads/documents/Description_of_Transformation_UA_UCS_2000_to_ETRS89%20New.pdf
now parameter towgs on all UCS2000 projections family set to +towgs84=25,-141,-78.5,0,0.35,0.736,0

But in qGIs assumed that ETRS89 == WGS84. So we can use this params to set towgs84. 
It seems to me - it is good idea set (acording to published params)
+towgs84=24.376,-121.321,-75.895,0.001296,0.007840,-0.012672,0

Also in Ukraine exists 27 Local (for each oblast of Country) coordinate systems. Here is published list of them and links on theirs passports (only in urainan). If it is possible include this definitions into predefined list in qGis - i can prepare this list in proj.4 format and boundary rects

**Comment by nyalldawson** [comment]
This should be fixed in 3.8 and builds based on proj 6. If not, it's an issue in the proj library and needs reporting there.
