### ISSUE TITLE
QGIS 3 lost CRS for some QGIS 2 project

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26554]
Author Name: **Loïc BARTOLETTI** (@lbartoletti)
Original Redmine Issue: [18666](https://issues.qgis.org/issues/18666)
Affected QGIS version: 3.0.0
Redmine category:map_canvas

---
An example, using the QWAT "project":https://github.com/qwat/QWAT/tree/master/qgis-project

**Comment by nyalldawson** [comment]
This is a wontfix now -- the time for this fix to be relevant has passed
