### ISSUE TITLE
integrated document viewer not working

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26556]
Author Name: **Imaduddin Idris** (Imaduddin Idris)
Original Redmine Issue: [18668](https://issues.qgis.org/issues/18668)
Affected QGIS version: 3.0.0
Redmine category:edit_widget

---
I'm using integrated document viewer in the attachment widget, the photo doesn't show up properly only showing small images.
But when I using photo widget on qgis 2.18 version, its working well

---

- [attachment widget qgis 3.01.jpg](https://issues.qgis.org/attachments/download/12581/attachment%20widget%20qgis%203.01.jpg) (Imaduddin Idris)
- [photo widget qgis 2.18.jpg](https://issues.qgis.org/attachments/download/12582/photo%20widget%20qgis%202.18.jpg) (Imaduddin Idris)

**Comment by geomondego** [comment]
No problem in Win10 with QGIS 3.16.3

**Comment by gioman** [comment]
Closing for lack of feedback.
