### ISSUE TITLE
Value relation widget: Multiple selections, not null attribute

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26561]
Author Name: **Manuel K** (Manuel K)
Original Redmine Issue: [18673](https://issues.qgis.org/issues/18673)
Affected QGIS version: 3.0.0
Redmine category:forms

---
In case of multiple selections of a NOT NULL attribute in a value selection widget, the green tick mark is displayed (and the OK button is active) although no value is selected.

---

- [value_relation_multiple_not_null.png](https://issues.qgis.org/attachments/download/12583/value_relation_multiple_not_null.png) (Manuel K)

**Comment by gioman** [comment]
Fixed recentrly, see https://github.com/qgis/QGIS/issues/46366
