### ISSUE TITLE
Rename Map Themes directly in Map Theme Dropdown Menu

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26563]
Author Name: **Rob Willson** (Rob Willson)
Original Redmine Issue: [18675](https://issues.qgis.org/issues/18675)

Redmine category:map_tools
Assignee: Denis Rouzaud

---
Map themes (formerly presets) are one of the most valuable and useful tools in QGIS but it is hard to organize or re-organize them when you can't rename them by just right clicking them.

Request that we be able to rename them by right clicking just like you can now do in the Favorites Menu in the browser (i.e., Rename Favorite) and you can do when saving or renaming layer styles. 

a bonus would be if you could manually reorder them as it eventually becomes difficult to come up with unique starting characters to change the sort order, currently, I have to use combinations of date time stamps, exclamation points, 0.01, 0.02 etc and keep the names in a separate text editor to be able to paste into the new map themes to keep the same format when I make changes to the company startup template.

**Comment by myfriendedward** [comment]
I agree that renaming map themes directly would be a very convenient feature, as would the ability to sort themes manually.
