### ISSUE TITLE
[Layout] Attribute table: deactivating layer source dd button is reverted the next time the table is selected

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26583]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [18695](https://issues.qgis.org/issues/18695)
Affected QGIS version: 3.1(master)
Redmine category:map_composer/printing

---
In print layout, add an attribute table and use a working expression to set the layer source to use.
Then deactivate the layer DD button
Select another item, and select back the attribute table: the DD button of Layer parameter is back, in yellow.

**Comment by Pedro-Murteira** [comment]
@DelazJ I can't replicate this anymore on QGIS 3.16.14 and 3,22,1. After deactivating the DD button and selecting another item, I come back to the attribute table and the DD button is no longer yellow. Is this still an issue with you?
