### ISSUE TITLE
Virtual layer with spaces in layer name not created

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26600]
Author Name: **Nikolay Lebedev** (Nikolay Lebedev)
Original Redmine Issue: [18713](https://issues.qgis.org/issues/18713)
Affected QGIS version: 3.0.0
Redmine category:virtual_layers

---
If you try to create a virtual layer from existing project layer that has spaces in layer name (like “My layer”) you'll receive an error when pressing `Check` button in ‘Creating of Virtual layer’ dialog. Layer won't be created. Dropping spaces gives positive result.

---

- [Screenshot 2018-04-19 02.08.50.png](https://issues.qgis.org/attachments/download/12631/Screenshot%202018-04-19%2002.08.50.png) (Nikolay Lebedev)

**Comment by alexbruy** [comment]
Should be closed? There is no error if layer name is quoted and this is the same behavior as we have in other places, e.g. expressions.

**Comment by gioman** [comment]
> Should be closed?

agree
