### ISSUE TITLE
Extra line feed in table using "Wrap text"

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26605]
Author Name: **Luca Lanteri** (Luca Lanteri)
Original Redmine Issue: [18718](https://issues.qgis.org/issues/18718)
Affected QGIS version: 3.1(master)
Redmine category:map_composer/printing

---
- Insert a table in composer
- Set fixed size for a text column
- Set Oversized text properties to "Wrap text"

The last row have an extra line feed, see attached example

---

- [test.qgs](https://issues.qgis.org/attachments/download/12600/test.qgs) (Luca Lanteri)
- [test.gpkg](https://issues.qgis.org/attachments/download/12601/test.gpkg) (Luca Lanteri)

**Comment by nyalldawson** [comment]
This is fixed in 3.4 and above
