### ISSUE TITLE
QGIS crashes when opening a project having joined layers with spaces in names

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26601]
Author Name: **Nikolay Lebedev** (Nikolay Lebedev)
Original Redmine Issue: [18714](https://issues.qgis.org/issues/18714)
Affected QGIS version: 3.0.0
Redmine category:relations
Assignee: Matthias Kuhn

---
Steps to reproduce:
Add two layers to the project.
Add a space in layer name for one layer (i.e. "my layer").
Join this layer to another one, so that join has a space in it's name.
Save and close the project, open again - boom.

Should be an easy fix with using layer id's etc. instead of names with spaces.

**Comment by roya0045** [comment]
I don't recall having that issue. Is the form tag appropriate or are we talking about a normal join?

**Comment by gioman** [comment]
Closing for lack of feedback.
