### ISSUE TITLE
saving uint16 layer to netCDF crashed

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26622]
Author Name: **nuitlejour nuitlejour** (nuitlejour nuitlejour)
Original Redmine Issue: [18735](https://issues.qgis.org/issues/18735)
Affected QGIS version: 3.1(master)
Redmine category:processing/qgis

---
Import a Geotiff file as Uint16 Format, and save the layer to NetCDF, QGIS crashes everytime. 

========= crash report generated by QGIS  =========
## Report Details

*Crash ID*: fa40ef17619e0a47a3373d90434ea8cb343486b8

*Stack Trace*
```
memcpy :
GDALRasterBand::IRasterIO :
GDALRasterBand::RasterIO :
GDALWarpOperation::operator= :
QgsRasterFileWriter::writeDataRaster :
QgsRasterFileWriter::writeDataRaster :
QgsRasterFileWriter::writeRaster :
QgsRasterFileWriterTask::run :
QgsTask::start :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

```

*QGIS Info*
QGIS Version: 3.0.1-Girona
QGIS code revision: a86bec25eb
Compiled against Qt: 5.9.2
Running against Qt: 5.9.2
Compiled against GDAL: 2.2.4
Running against GDAL: 2.2.4

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.14393

---

- [MOD09GA.A2017032.h25v06.005.NRT.snow_fraction.tif](https://issues.qgis.org/attachments/download/12614/MOD09GA.A2017032.h25v06.005.NRT.snow_fraction.tif) (nuitlejour nuitlejour)

**Comment by gioman** [comment]
Not replicable anymore, reopen if necessary.
