### ISSUE TITLE
No TIFF image encoding radio button for WMS

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26628]
Author Name: **dr -** (dr -)
Original Redmine Issue: [18741](https://issues.qgis.org/issues/18741)
Affected QGIS version: 3.1(master)
Redmine category:web_services_clients/wms

---
No TIFF image encoding radio button amongst supported formats for WMS layer.

Ubuntu 16.04 (latest ubuntugis-nightly QGIS version)

---

- [photo_2018-04-17_22-53-39.jpg](https://issues.qgis.org/attachments/download/12615/photo_2018-04-17_22-53-39.jpg) (dr -)

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
