### ISSUE TITLE
Move labels on rotated view

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26632]
Author Name: **Johannes Metzler** (Johannes Metzler)
Original Redmine Issue: [18745](https://issues.qgis.org/issues/18745)
Affected QGIS version: 3.0.1
Redmine category:labelling

---
It is not possible to move or rotate labels on a rotated view because the label pin boxes are not rotated accordingly.
(see attached image)
I opened a ticket some time ago about this issue, it was set to closed but the problem remains.
thanks
Johannes

---

- [pinboxbroblem.JPG](https://issues.qgis.org/attachments/download/12622/pinboxbroblem.JPG) (Johannes Metzler)
- [pinbox no rotation.JPG](https://issues.qgis.org/attachments/download/12623/pinbox%20no%20rotation.JPG) (Johannes Metzler)

**Comment by nyalldawson** [comment]
Duplicate of #25384
