### ISSUE TITLE
QGIS3: mysteric QByteArray display in dvanced Settings Editor

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26645]
Author Name: **Tobias Wendorff** (Tobias Wendorff)
Original Redmine Issue: [18758](https://issues.qgis.org/issues/18758)
Affected QGIS version: 3.0.1
Redmine category:gui

---
Experienced on QGIS3, GIT build 6e3d879544, OSGeo4W 64-bit.

settings > options > advanced (Advanced Settings Editor) shows mysteric values in QByteArray (see image in attachment).
Maybe this is correct, since it's binary? But since the field it editable, it should be something read- or copy-able... like HEX values?!

---

- [qbytearray.png](https://issues.qgis.org/attachments/download/12630/qbytearray.png) (Tobias Wendorff)

**Comment by alexbruy** [comment]
QByteArray is a correct value, it stores for example window state (geometry, postion etc)
