### ISSUE TITLE
WFS SQL Query Composer

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26644]
Author Name: **Eric Berkowitz** (@ericwberkowitz)
Original Redmine Issue: [18757](https://issues.qgis.org/issues/18757)
Affected QGIS version: 3.0.1
Redmine category:web_services_clients/wfs

---
When I attempt to create an SQL query for a WFS layer the text in the SQL statement box is scrunched together and I can't easily edit or create a query. See attached image.

---

- [SQLQuery.PNG](https://issues.qgis.org/attachments/download/12629/SQLQuery.PNG) (Eric Berkowitz)

**Comment by pathmapper** [comment]
Can't reproduce on Windows 10 with QGIS 3.18.1

**Comment by gioman** [comment]
Closing for lack of feedback.
