### ISSUE TITLE
Nodata issue with TIN interpolation's cubic method 

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26655]
Author Name: **Mathieu Pellerin - nIRV** (Mathieu Pellerin - nIRV)
Original Redmine Issue: [18768](https://issues.qgis.org/issues/18768)
Affected QGIS version: master
Redmine category:analysis_library
Assignee: Marco Hugentobler

---
I've just spotted an interesting issue with the TIN interpolation code.

With the TIN interpolation "linear" method, the rendering is fine (tin-linear.png), but with the "cubic" method, the code inserts 0 values instead of nodata until it hits the first non-nodata value (see the black part at the top of tin-cubic.png).

Marco, you are our only hope ;) I've looked into the code, but couldn't get my way through it. 

---

- [tin-linear.png](https://issues.qgis.org/attachments/download/12637/tin-linear.png) (Mathieu Pellerin - nIRV)
- [tin-cubic.png](https://issues.qgis.org/attachments/download/12638/tin-cubic.png) (Mathieu Pellerin - nIRV)
- [test-data.zip](https://issues.qgis.org/attachments/download/12639/test-data.zip) (Mathieu Pellerin - nIRV)

**Comment by gioman** [comment]
Closing as seems to work ok with the TIN tool in processing.
