### ISSUE TITLE
Geometry generator inside Point Cluster style uses project CRS instead of layer CRS

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26660]
Author Name: **Michel Stuyts** (@mstuyts)
Original Redmine Issue: [18773](https://issues.qgis.org/issues/18773)
Affected QGIS version: 3.0.1
Redmine category:symbology

---
This problem occurs when the project CRS is different from the point layer CRS.

* If a geometry generator with only $geometry is used in a Single symbol style for a point layer, the points are generated in the CRS of the point layer.
* If a geometry generator with only $geometry (on the original points or on the Cluster points) is used in a Point cluster style for a point layer, the points or Cluster points are generated in the CRS of the project.

*Steps to reproduce with Single symbol style:*
1. Create a project with CRS EPSG:4326
1. Load a point layer with CRS EPSG:31370
1. Change the Symbol layer type from Simple Marker to Geometry Generator
1. Set the Geometry Type to Point/Multipoint
1. Set the expression to _$geometry_

+Result:+ 
The points are created on the same place as if a Simple marker style was used (this is the expected result). If the expression is changed to _geom_to_wkt($geometry)_ in the Expression Dialog box, the Output Preview shows coordinates in EPSG:31370, so the points are generated in the CRS of the original points layer.

*Steps to reproduce with Point Cluster style (geometry generator on original points):*
_PART 1_
1. Create a project with CRS EPSG:4326
1. Load a point layer with CRS EPSG:31370
1. Change the layer type from Single Symbol to Point Cluster
1. Click on Renderer settings...
1. Change the Symbol layer type from Simple Marker to Geometry Generator
1. Set the Geometry Type to Point/Multipoint
1. Set the expression to $geometry

+Result:+ 
The Cluster points are created near the place of the points where a Simple marker style would place the points, but the points created by the Geometry generator are not visible near the cluster points.  If the expression is changed to _geom_to_wkt($geometry)_ in the Expression Dialog box, the Output Preview shows coordinates in EPSG:4326, so the points are generated in the CRS of project.

_PART 2_
1. Change the expression to _transform($geometry,'EPSG:4326','EPSG:31370')_

+Result:+ 
The Cluster points and original points are created near the place of the points like when a Simple marker style was used. Inside the Point Cluster style this counterintuitive expression is needed to get the points at the correct place.

A similar problem occurs when the Geometry Generator is applied on the Cluster Markers instead of on the original points.

*Steps to reproduce with Point Cluster style (geometry generator on cluster points):*
_PART 1_
1. Create a project with CRS EPSG:4326
1. Load a point layer with CRS EPSG:31370
1. Change the layer type from Single Symbol to Point Cluster
1. Click on the cluster symbol button
1. Change the Symbol layer type of the Cluster points from Simple Marker to Geometry Generator
1. Set the Geometry Type to Point/Multipoint
1. Set the expression to $geometry

+Result:+ 
The original points are created on the same place as if a Simple marker style was used. The Cluster points are created near the place where the 0,0 coordinates in EPSG:31370 are (north of Paris), because the coordinates in EPSG:4326 are much smaller than the coordinates in EPSG:31370. 

_PART 2_
1. Change the expression to _transform($geometry,'EPSG:4326','EPSG:31370')_

+Result:+ 
The Cluster points and original points are created near the place of the points like when a Simple marker style was used. Inside the Point Cluster style this counterintuitive expression is needed to get the Cluster points at the correct place.

---

- [clustered_geometry_generator_CRS_bug.zip](https://issues.qgis.org/attachments/download/12646/clustered_geometry_generator_CRS_bug.zip) (Tom Chadwin)

**Comment by gioman** [comment]
@mstuyts @tomchadwin the original issue seems fixed to me.

In a project with CRS 4326 and a point layer in a project CRS then in the context of the cluster renderer 

`geom_to_wkt($geometry)`

returns projected coordinates.

However... while this 

`centroid(buffer($geometry,1000))`

works fine in a normal symbology, in the context of the cluster renderer the isolated points are a no show.

Can you confirm?
