### ISSUE TITLE
Hang on editing vector layer

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26667]
Author Name: **Nick Judd** (Nick Judd)
Original Redmine Issue: [18780](https://issues.qgis.org/issues/18780)
Affected QGIS version: 3.0.1
Redmine category:attribute_table

---
ENVIRONMENT:

QGIS 3.0.1 on Fedora 26

DATA:

GeoPackage or Shapefile, vector layer, ~70,000 features (US Census tracts)

TO REPLICATE:

1. Open Attribute Table.
2. Toggle editing
3. Select some nontrivial number of features (in my case ~3000)
4. Attempt to update features using a formula (in my case, updating all features where "column_name" = 'NA' to have the value NULL)

EXPECTED BEHAVIOR:

Values updated

OBSERVED BEHAVIOR:

QGIS hangs, Fedora invites the user to "Force Quit"

**Comment by roya0045** [comment]
Can anyone replicate this or see if still valid?

**Comment by gioman** [comment]
> Can anyone replicate this or see if still valid?

@roya0045 checking right now.

**Comment by gioman** [comment]
Downloades some data from here https://www.census.gov/geographies/mapping-files/time-series/geo/tiger-line-file.html and can't replicate. Please reopen if necessary.

**Comment by roya0045** [comment]
@gioman Thanks gio, I also checked the old "tracing issue" but I'm never sure if I'm doing it badly or if the tracing is just wonky.

**Comment by gioman** [comment]
> @gioman Thanks gio, I also checked the old "tracing issue" but I'm never sure if I'm doing it badly or if the tracing is just wonky.

what ticket is that?

**Comment by roya0045** [comment]
#26816
