### ISSUE TITLE
Test button in rule based styling returns wrong number of features when calculating (in shapefiles)

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26673]
Author Name: **Erik Meerburg** (Erik Meerburg)
Original Redmine Issue: [18786](https://issues.qgis.org/issues/18786)
Affected QGIS version: 3.0.1
Redmine category:expressions

---
Hi,
When making a rule based legend using a calculation, I ran into this one.

I've got two fields, both Integers. I have two rules here: Field1/field2>1 and Field1/Field2<1. The styling result comes out correct: If Field1 has the larger value, rule 1 applies, and vv.

However, when testing (pushing the Test-button), all objects fall into one of the categories. So the behaviour of the Test-button is not right. That was surprising... first I thought there was something wrong with my rules or the rule mechanism, but that behaviour is correct.

Turns out, this behaviour happens with shapefiles, but not with geopackages. Didn't test any other filetypes.

I've added a test shapefile with just two feautures, and a screenshot where you can see what I mean.

---

- [test_rulebased.zip](https://issues.qgis.org/attachments/download/12648/test_rulebased.zip) (Erik Meerburg)

**Comment by gioman** [comment]
Still true on the latest master.

**Comment by Pedro-Murteira** [comment]
@gioman Hello,  I've tested this issue and both rules return 1 feature upon hitting "Test". Isn't it the expected behaviour here?

**Comment by gioman** [comment]
> 've tested this issue and both rules return 1

@Pedro-Murteira and that is what is expected, with the attached sample data. @rduivenvoorde can we close this?

**Comment by rduivenvoorde** [comment]
@gioman Yes, I retested, and all looks fine now. Let's close it. Thanks all for checking this again.
