### ISSUE TITLE
XYZ Tile Server with custom CRS not working

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26705]
Author Name: **Bruce Steedman** (Bruce Steedman)
Original Redmine Issue: [18873](https://issues.qgis.org/issues/18873)
Affected QGIS version: 3.4.4
Redmine category:web_services_clients/xyz

---
I have added the following URL pattern as an XYZ Tile Server connection:

http://dcw7.digimap.je/arcgis/rest/services/StatesOfJersey/JerseyAerialPhotoOL2014_500/MapServer/tile/{z}/{y}/{x}.png

An example tile is at http://dcw7.digimap.je/arcgis/rest/services/StatesOfJersey/JerseyAerialPhotoOL2014_500/MapServer/tile/0/268/331

When I add the layer no tiles are rendered on my map.

I have successfully added other tile layers, which work: e.g. https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}.png

The Map Server I am trying to add uses a custom CRS: EPSG:3109 (which uses a custom map origin). I have this CRS set in my project and on the fly projection enabled.

When added, the layer does not pick up the custom CRS, but instead uses EPSG:3857. Changing to the correct CRS in the added layer does not resolve the problem.

I note that the Server specifies 9 zoom levels, with 0 scaled at 1:250,000.

Does 2.18 LTS support Tile Servers with custom CRS & scales and if not does QGIS 3 do so?

Steps to reproduce above and no known workaround.

Many thanks.

---

- [xyz.png](https://issues.qgis.org/attachments/download/14126/xyz.png) (Bruce Steedman)

**Comment by Pedro-Murteira** [comment]
This is still valid on QGIS 3.16.15 and 3.22.2.

**Comment by alexbruy** [comment]
Is this still valid issue?
