### ISSUE TITLE
"Update extents" button does not work

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26711]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [18879](https://issues.qgis.org/issues/18879)
Affected QGIS version: 3.1(master)
Redmine category:unknown

---
I have a postgreSQL layer whose extent is wrong (zoom to layer command only shows partial data, however coherent with information in the layers properties --> information dialog)
When i click the "Update extents" button in the Layers properties --> Source tab, i expect it to fix the issue but it does not: same extent (visually or checking the Info tab). I can't even tell if anything happens(if the click works): it would be nice to have some visual feedback that the command works.

**Comment by gioman** [comment]
> however coherent with information in the layers properties

@DelazJ is this still valid?

I think that your scenario is/was one where the extent is reported by the provider, and if is not right it should be fixed at the source. More or less the same that was pointed here https://github.com/qgis/QGIS/issues/26712

**Comment by DelazJ** [comment]
@gioman Sorry, i have no idea what this was about and no way I could retest. So this could probably be closed.
I just wonder in what scenario the "update extents" button is meant to be used.
