### ISSUE TITLE
[Processing] "Extract layer extent" should not blindly trust layer extent information

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26712]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [18880](https://issues.qgis.org/issues/18880)
Affected QGIS version: 3.1(master)
Redmine category:processing/qgis

---
I have a PostgreSQL layer with a wrong extent (not all the features are shown when zooming to layer - see #26711). 
Running the "Extract layer extent" on it generates a new layer covering the wrong extent. I guess it's because it uses the extent information in the layer metadata instead of generating one beforehand.
Btw, maybe we can have a new algorithm that simply updates the layer extent (which will be called in this case but can be handy for models also)

**Comment by alexbruy** [comment]
To Processing behavior looks correct. Wy we should recalculate extent if it is already provided by backend? If there is something wrong on the backend side it is no a Processing issue. Also note that recalculating extent can be extremely slow if large dataset or poor connection is used.

It can be implemented as separate algorithm or additional parameter can be added to the existing algorithm to force extent recalculation. But this is should be new feature request, not bug.

**Comment by DelazJ** [comment]
Feel free to switch/close as you want. I don't even remember what this is about: probably something I came across for documentation testing.
