### ISSUE TITLE
Clipping feature errors trying to clip raster file on Mac (QGIS 3.0.2)

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26721]
Author Name: **Robert Catherman** (Robert Catherman)
Original Redmine Issue: [18889](https://issues.qgis.org/issues/18889)
Affected QGIS version: 3.7(master)
Redmine category:unknown

---
When using feature RASTER > EXTRACTION > CLIP RASTER BY MASK LAYER

Mask is a vector file

QGIS fails with message  (tried on 2 difference Mac computers)

Processing algorithm…
AlgorithmDialog
Input parameters:
{ 'ALPHA_BAND' : False, 'CROP_TO_CUTLINE' : True, 'DATA_TYPE' : 5, 'INPUT' : '/Users/Robert/Documents/GIS Remote Sensing/Redmond/Landsat/LE07_L1TP_046027_20020611_20160929_01_T1_B3.TIF', 'KEEP_RESOLUTION' : False, 'MASK' : '/Users/Robert/Documents/GIS Remote Sensing/Redmond/StudyArea.shp', 'NODATA' : 0, 'OPTIONS' : '', 'OUTPUT' : '/var/folders/k4/fy3tzlys3t1dz08rhr9s84d80000gn/T/processing_498c80ccddac4633b4288fcd7abccdf0/be39ce251c8f45289a648384448491b7/OUTPUT.tif' }

GDAL command:
gdalwarp -ot Float32 -of GTiff -cutline "/Users/Robert/Documents/GIS Remote Sensing/Redmond/StudyArea.shp" -crop_to_cutline "/Users/Robert/Documents/GIS Remote Sensing/Redmond/Landsat/LE07_L1TP_046027_20020611_20160929_01_T1_B3.TIF" /var/folders/k4/fy3tzlys3t1dz08rhr9s84d80000gn/T/processing_498c80ccddac4633b4288fcd7abccdf0/be39ce251c8f45289a648384448491b7/OUTPUT.tif
GDAL command output:
/bin/sh: gdalwarp: command not found
Execution completed in 0.07 seconds
Results:
{'OUTPUT': <QgsProcessingOutputLayerDefinition {'sink':/var/folders/k4/fy3tzlys3t1dz08rhr9s84d80000gn/T/processing_498c80ccddac4633b4288fcd7abccdf0/be39ce251c8f45289a648384448491b7/OUTPUT.tif, 'createOptions': {'fileEncoding': 'System'}}>}

Loading resulting layers
The following layers were not correctly generated.
•	/var/folders/k4/fy3tzlys3t1dz08rhr9s84d80000gn/T/processing_498c80ccddac4633b4288fcd7abccdf0/be39ce251c8f45289a648384448491b7/OUTPUT.tif
You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.

FROM LOG MESSAGE PANEL
2018-04-30T09:22:12 INFO gdalwarp -ot Float32 -of GTiff -cutline "/Users/Robert/Documents/GIS Remote Sensing/Redmond/StudyArea.shp" -crop_to_cutline "/Users/Robert/Documents/GIS Remote Sensing/Redmond/Landsat/LE07_L1TP_046027_20020611_20160929_01_T1_B3.TIF" /var/folders/k4/fy3tzlys3t1dz08rhr9s84d80000gn/T/processing_498c80ccddac4633b4288fcd7abccdf0/d1b6edf50f804cd9abf07bdae62c8ba6/OUTPUT.tif
2018-04-30T09:22:12 INFO GDAL execution console output
/bin/sh: gdalwarp: command not found

**Comment by alexbruy** [comment]
Please test with latest master

**Comment by gioman** [comment]
Works fine on 3.10.1 on Catalina.
