### ISSUE TITLE
Geopackage converts 8 bit raster in 4 band rgb

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26742]
Author Name: **matteo ghetta** (@ghtmtt)
Original Redmine Issue: [18910](https://issues.qgis.org/issues/18910)
Affected QGIS version: 3.1(master)
Redmine category:data_provider

---
8 bit (256 greyscale) rasters are converted in 4 bands rgb images during the importing in an existing geopackage. This slows down the loading and all related properties of the layer. In attach a 8 bit image

---

- [250020.tif](https://issues.qgis.org/attachments/download/12668/250020.tif) (matteo ghetta)

**Comment by nyalldawson** [comment]
Duplicate of https://github.com/qgis/QGIS/issues/38227
