### ISSUE TITLE
Measurement tool window not visible

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26756]
Author Name: **Daniel Boyd** (Daniel Boyd)
Original Redmine Issue: [18924](https://issues.qgis.org/issues/18924)
Affected QGIS version: 3.0.2
Redmine category:gui

---
When I switch from a multiple monitor configuration to a single monitor configuration (or even a different multimonitor configuration), the measurement tool frequently opens up off-screen and there is no way (that I have seen) to get it back.

The only solution I've found is to go back to the original monitor configuration.  This is particularly troublesome for users with docked laptops where the monitor configuration changes frequently.

Steps to reproduce:
1) Using multi-monitor setup, open measurement tool and move measurement window to a second screen
2) Disconnect second screen
3) open measurement tool; measurement window is not visible

**Comment by SrNetoChan** [comment]
Using master (3.17) I Can't replicate on Linux (kde plasma). When  I change my monitor configuration to a single monitor the measurement dialog is pulled into the remaining monitor.

**Comment by jonnyforestGIS** [comment]
Using master 3.17 with Windows, this behaviour doesn't happen. When turned off the measure tool open in the correct monitor.
