### ISSUE TITLE
Qgis 3 can't properly load gml files.

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26769]
Author Name: **Jorge Almaraz** (Jorge Almaraz)
Original Redmine Issue: [18937](https://issues.qgis.org/issues/18937)
Affected QGIS version: 3.0.2
Redmine category:data_provider

---
Some gml files can't be properly loaded by the last version of qgis.The previous versión of Qgis(2.18) load them correctly.
To reproduce this bug you can try to load any gml file from the spanish cadastre web:
http://www.catastro.minhap.es/INSPIRE/CadastralParcels/10/ES.SDGC.CP.atom_10.xml

---

- [gml.png](https://issues.qgis.org/attachments/download/12695/gml.png) (Saber Razmjooei)
- [layer_properties.png](https://issues.qgis.org/attachments/download/12696/layer_properties.png) (Jorge Almaraz)

**Comment by alexbruy** [comment]
Is this still valid?

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
