### ISSUE TITLE
Service url cannot include custom query parameters

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26761]
Author Name: **Lorenzo Pini** (Lorenzo Pini)
Original Redmine Issue: [18929](https://issues.qgis.org/issues/18929)
Affected QGIS version: 3.0.1
Redmine category:web_services_clients/wcs

---
Adding new services (WCS, WMS, WFS) the url cannot contain any custom parameter.

If a custom parameter is added, QGIS will use invalid URLs to access the resources.

For example with access_token or mapId query parameters.

http://localhost/server/?access_key=123456789
will result in
http://localhost/server/?access_key=123456789?&SERVICE=WCS&....

QGIS should always generate a valid url to load the layers

**Comment by alexbruy** [comment]
Please retest wit 3.4 and master, should be already fixed.

**Comment by alexbruy** [comment]
Closed for the lack of feedback and because it seems already fixed.
