### ISSUE TITLE
Virtual layer crash when layer name not valid

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26765]
Author Name: **matteo ghetta** (@ghtmtt)
Original Redmine Issue: [18933](https://issues.qgis.org/issues/18933)
Affected QGIS version: 3.1(master)
Redmine category:db_manager

---
When the layer name is not valid the SQL query in the DB Manager makes QGIS crash

**Comment by gioman** [comment]
@ghtmtt I cannot replicate or cannot understand how to replicate. Latest master on Ubuntu 20.04.

**Comment by ghtmtt** [comment]
seems not crashing anymore. Closing the issue, thanks for the feedback
