### ISSUE TITLE
Improvement for Batch Processing

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26775]
Author Name: **Nicolas Cadieux** (@NicolasCadieux)
Original Redmine Issue: [18944](https://issues.qgis.org/issues/18944)

Redmine category:processing/gui

---
We should be able to select all or multiple layers and select a field parameter once that will apply to all selected layers.  Same thing for adding layers from the project.  We should be able to select multiple layer and then click only once for all layers to be added.

It would be nice to be able to add fields or parameters when these are missing in the GUI (like for buildVRT raster where many if not most parameters are missing making the module unusable for anything complicated).

We should be able to drag and drop layers into the Batch processing windows from the Layer Panel.

**Comment by alexbruy** [comment]
Please open separate tickets for each request/bug with proper name and description.
