### ISSUE TITLE
QGIS main application crash just after editing large gmx track file.

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26772]
Author Name: **Bryan Taylor** (Bryan Taylor)
Original Redmine Issue: [18940](https://issues.qgis.org/issues/18940)
Affected QGIS version: 3.0.2
Redmine category:editing

---
I had used the 'gps tools' plugin to import the track file from the gpx.  The track file was very complex with tracks making loops and very dense crossover/clusters.  I was mostly cutting lines (having trouble with the cut tool also) and deleting segments.  Upon saving edits and stopping the edit session, the application crashed, bringing up the crash notice and offering to reload qgis.  It did not corrupt my data and the edits were saved. 
 This happened twice while doing similar editing with about 6 files.  It was not reproducable in my opinion as I couldn't exactly repeat the editing tasks I had been doing.  The uploaded file is an exported selection from one that was involved in a crash.  I have a sent a jpg of the full track (25mb) just to show how complex it really is.  It is certainly a system taxing file to deal with, but a real world example anyway.

---

- [example_track.zip](https://issues.qgis.org/attachments/download/12686/example_track.zip) (Bryan Taylor)
- [full_track_extent.jpg](https://issues.qgis.org/attachments/download/12687/full_track_extent.jpg) (Bryan Taylor)

**Comment by lbartoletti** [comment]
I can not reproduce this issue. Please, can you try with the latest versions?

**Comment by gioman** [comment]
Closing for lack of feedback.
