### ISSUE TITLE
bug no legend display

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26787]
Author Name: **Alix Sotiaux** (Alix Sotiaux)
Original Redmine Issue: [18956](https://issues.qgis.org/issues/18956)
Affected QGIS version: 3.0.2
Redmine category:map_legend

---
Good morning,

When I want to display the legend of a vector (point) shape file with color and/or size (propriety, symbology, graduated); the symbology doesn't appearing nor in the project area nor in the layout windows. 

I try on tow distinct computers: one windows 7 professionals and a MacOS Sierra.

---

- [Capture.JPG](https://issues.qgis.org/attachments/download/12693/Capture.JPG) (Alix Sotiaux)

**Comment by roya0045** [comment]
Is this still occurring?
