### ISSUE TITLE
Styles: Load Style from File does not work when style is available in Database

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26786]
Author Name: **Luc Janssens** (Luc Janssens)
Original Redmine Issue: [18955](https://issues.qgis.org/issues/18955)
Affected QGIS version: 3.0.2
Redmine category:symbology

---
Action:
- Add a Layer with a style defined in a PG-Database
- Edit that layer and choose "Style - Load from File"
- The Style will not be adjusted.
Manual Editing of the style is still possible.

This applies to QGIS 3.02 as well as older versions.

**Comment by nyalldawson** [comment]
I can't reproduce this -- I suspect it is fixed
