### ISSUE TITLE
Data Source Manager - Filter does not consider the Name and Abstract fields when displaying ArcGIS Map Server and ArcGIS Feature Server layers

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26780]
Author Name: **Alister Hood** (@AlisterH)
Original Redmine Issue: [18949](https://issues.qgis.org/issues/18949)
Affected QGIS version: 3.0.2
Redmine category:gui

---
When adding ArcGIS Map Server or ArcGIS Feature Server layers, the Data Source Manager has a text entry field called "Filter", with this tooltip:

```
Display WFS FeatureTypes containing this word in the title, name or abstract

```

1. The tooltip says "WFS FeatureTypes", even though we are not trying to add a WFS layer.  I see this is also an issue when you go to load a Geonode layer.
2. The filter only filters based on the "Title" field, not the "Name" or "Abstract" field.  This applies also to WFS layers and so I'm guessing also Geonode layers.
In my very limited experience WFS layers actually have a useful title, so it isn't really a problem in that case.  But I have never come across an ArcGIS server that had anything useful in the "Title" field - each layer just has a number i.e. 0, 1, 2...
Perhaps there are ArcGIS servers with useful titles, and I just haven't seen them.  But the filter won't be useful on the servers I've seen unless it takes into account the "Name" and "Abstract" fields.

None of this is a regression i.e. it was the same in QGIS 2.x

**Comment by gioman** [comment]
@AlisterH seems to me that this is not more relevant/true in recent releases.

**Comment by AlisterH** [comment]
Sorry, not sure why I didn't see this before.  Yes, it seems to work OK now.
> The tooltip says "WFS FeatureTypes", even though we are not trying to add a WFS layer.

The cosmetic issue remains.
