### ISSUE TITLE
GPS information/tracker plugin : handling elevation

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26790]
Author Name: **Pierrick Allorant** (Pierrick Allorant)
Original Redmine Issue: [18959](https://issues.qgis.org/issues/18959)

Redmine category:c++_plugins/gps_plugin

---
Hi,

QGIS would be a perfect fieldprogram for surveyors who want to do some GNSS surveys. It is easy to link to low or high cost RTK-GNSS systems using NMEA0183. 

Unfortunately, at the moment we cannot use it properly because it is impossible to record the height information in the geometry (with a 3d shp for example) or just in a given attribute.

So here are my suggestions, which would be much welcome for all surveyors :

- show the altitude with 2 or 3 digits in the panel
- let the user choose between ellipsoidal height and from geoid corrected
- make it possible to record the altitude for each point in a given attribute column
- and/or (even better) : make it possible to write in 3d shapefiles so that x, y and z are directly recorded in the geometry

This is no urgent request, but a very important one for land surveyors who will be able to use  Qgis as an all-integrated on-field and office software, with growing interest from those who use low-cost RTK systems.

Thank you very much,

**Comment by nyalldawson** [comment]
These requests have all been implemented
