### ISSUE TITLE
Unpinned labels jump to wrong place when moved

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26791]
Author Name: **Nathan Perry** (Nathan Perry)
Original Redmine Issue: [18960](https://issues.qgis.org/issues/18960)
Affected QGIS version: 3.0.2
Redmine category:labelling

---
When moving an unpinned label (using auxiliary field labeling), the label jumps to a place too low on the map canvas. It does not follow the cursor location or selection box. See the attached screencast for an example: I move the first label downward and it jumps too far down; I move the second slightly upward, but it also moves down.

This issue does not occur with labels that are already pinned, or with unpinned labels using data-defined labeling.

---

- [Screencast.gif](https://issues.qgis.org/attachments/download/12694/Screencast.gif) (Nathan Perry)

**Comment by nyalldawson** [comment]
Is this still an issue? I can't reproduce.

**Comment by haubourg** [comment]
Can't reproduce either 
![Peek 21-06-2019 14-07](https://user-images.githubusercontent.com/1629853/59921472-0e401d00-942e-11e9-99d5-0c9cbdb7aa19.gif)

Let's close and reopen if necessary
