### ISSUE TITLE
No geometry operation on geopackages layers

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26805]
Author Name: **matteo ghetta** (@ghtmtt)
Original Redmine Issue: [18974](https://issues.qgis.org/issues/18974)
Affected QGIS version: 3.6.0
Redmine category:db_manager

---
In DB manager it seems that it is not possible to make any complex or even simple geometric or spatial operation with layers stored in geopackage. In attach a very simple geopackage with a single layer.

Trying to run the query:

SELECT ST_AREA(geom) AS area, geom FROM province

the area column in output contains only NULL values, while the geom column, even if it is possible to load the layer as a new layer, contains values like: `b'GP\x00\x03.........`. 

In the layer table the geom column is correctly read with, e.g. MULTIPOLYGON... type

The exact same query works on the same layer loaded in QGIS but using Virtual Layers. Output area column is correctly calculated and geometry is correctly displayed as MULTIPOLIGON type.

In attach the used geopackage with the layer

---

- [bug.gpkg](https://issues.qgis.org/attachments/download/12699/bug.gpkg) (matteo ghetta)
- [Selection_007.png](https://issues.qgis.org/attachments/download/13347/Selection_007.png) (matteo ghetta)

---

Related issue(s): #27912 (relates), #28847 (relates)
Redmine related issue(s): [20090](https://issues.qgis.org/issues/20090), [21028](https://issues.qgis.org/issues/21028)

---

**Comment by alexbruy** [comment]
Duplicates #27914
