### ISSUE TITLE
Wrong identification of feature in a View

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26804]
Author Name: **matteo ghetta** (@ghtmtt)
Original Redmine Issue: [18973](https://issues.qgis.org/issues/18973)
Affected QGIS version: 3.7(master)
Redmine category:data_provider

---
I have created a very simple view in a geopackage layer. Trying to use the selection tool AND the identify tool results in a wrong feature identification.

With the selection tool wrong features are selected while with the identify tool the form of the same feature is opened again and again.

A small video in attach to better see the error.

BTW: the original layer (from where the view comes from) works perfectly, so it really seems a view related problem

---

- [bug.mp4](https://issues.qgis.org/attachments/download/12698/bug.mp4) (matteo ghetta)
- [geo.gpkg](https://issues.qgis.org/attachments/download/13578/geo.gpkg) (matteo ghetta)

---

Related issue(s): #23523 (relates)
Redmine related issue(s): [15600](https://issues.qgis.org/issues/15600)

---

**Comment by ghtmtt** [comment]
guys, are there any WIP for making Views use more comfortable into a gpkg? I really really think that using a real database with such a *complexity* to create views is not user friendly.

**Comment by gioman** [comment]
> guys, are there any WIP for making Views use more comfortable into a gpkg? I really really think that using a real database with such a _complexity_ to create views is not user-friendly.

@ghtmtt I can't agree more... In DB manager we can run an arbitrary query on a Spatialite datasource and then with the "create view" button easily store it. With GPKGs that button is not there. Moreover, GPKGs views do NOT show in DB manager***, not even after the steps you describe in https://github.com/qgis/QGIS/issues/26804#issuecomment-495888703 (with or without the tip from Hugo here https://github.com/qgis/QGIS/issues/26804#issuecomment-495888710).

I am very interested in understanding how much work would be needed to make GPKGs fully supported in DB Manager, and eventually do my share to support such effort.

*** Also GPKG rasters do not show in DB Manager see: https://github.com/qgis/QGIS/issues/30932

**Comment by ghtmtt** [comment]
thanks @gioman for the feedback. IMHO having a real db as default (or at least suggested) file format like gpkg without having a nice method to add views is not use friendly.

Moreover: I just checked after you mentioned that also with spatialite there is the `Create View` button. It works but not for spatial layers: after creating a subset with a simple select, creating a view, the view is in the DB (also in DB Manager) but when adding the view to QGIS it is read a not spatial table. Don't know if this is the normal behavior with views. If not I can open a ticket, but just wanted to have a feedback before.

**Comment by gioman** [comment]
> Moreover: I just checked after you mentioned that also with spatialite there is the `Create View` button. It works but not for spatial layers: after creating a subset with a simple select, creating a view, the view is in the DB (also in DB Manager) but when adding the view to QGIS it is read a not spatial table. Don't know if this is the normal behavior with views. If not I can open a ticket, but just wanted to have a feedback before.

@ghtmtt this is my observation:

* add a layer (i.e. shapefile) to QGIS
* save it as SL (call it "test")
* create a connection to this new SL dataset
* in DB Manager query "test":

select * from test

* is possible to add the result as "query layer" in QGIS
* if the "create view" is pressed a message error is returned (after choosing the view name)

`insert on geometry_columns violates constraint: f_geometry_column value must be lower case`

this happens because when saving the shape to SL QGIS calls the geom column "GEOMETRY" and not "geometry". The view is created anyway, but is not spatial.

* if the user changes the query to

`SELECT ogc_fid,GEOMETRY AS geometry FROM test`

then when clicking on "create view" there are no errors a the spatial view is correctly listed in DB Manager/Browser and added to the project.

**Comment by ffierm** [comment]
In my opinion, when we use the DBManager to create VIEWS or TABLES into a GPKG, a "system help" (more friendly) should registering "on the fly" the new objects...

**Comment by gioman** [comment]
> a "system help" (more friendly)

sure, the whole discussion above is about suggesting exactly it.

**Comment by gioman** [comment]
@ghtmtt the original issue seems fixed on 3.24.0

having to do those manual steps to register a GPKG view is an horrible thing for final users, but I guess is a separate issue.


> Author Name: **matteo ghetta** (@ghtmtt)
> 
> hi guys, of course! In attach a geopackage with a single layer.
> 
> I created the view within the DB manager (a view that actually is just an exact copy of the source layer), as:
> 
> ```
> CREATE VIEW vista AS
> SELECT * FROM cities
> ```
> 
> then registered the view in the gpkg_content table:
> 
> ```
> INSERT INTO gpkg_contents (table_name, identifier, data_type, srs_id)
> VALUES ( 'vista', 'vista', 'features', 3003)
> ```
> 
> Finally registered also the geometric information in the gpkg_geometry_columns table:
> 
> ```
> INSERT INTO gpkg_geometry_columns (table_name, column_name, geometry_type_name, srs_id, z, m) 
> VALUE ('vista', 'geom', 'GEOMETRY', 3003, 0, 0)
> ```
> 
> Am I doing something wrong with the view creation?
> 
> Thanks guys
> 
>     * 13578  was configured    as geo.gpkg
> 
> 
>     * [geo.gpkg](https://issues.qgis.org/attachments/download/13578/geo.gpkg) (matteo ghetta)

**Comment by ghtmtt** [comment]
@gioman issue solved, confirmed!

> having to do those manual steps to register a GPKG view is an horrible thing for final users, but I guess is a separate issue.

definitely! IMHO having the nice button as we have for SpatiaLite would be a great improvement for Geopackage.

**Comment by ghtmtt** [comment]
@gioman should this issue converted into a feature request?

**Comment by ghtmtt** [comment]
ping @gioman just to know what to effectively do with this issue. Thanks!
