### ISSUE TITLE
Tracing issues

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26816]
Author Name: **Andreas Wicht** (@andywicht)
Original Redmine Issue: [18985](https://issues.qgis.org/issues/18985)
Affected QGIS version: 3.4.1
Redmine category:digitising

---
First Issue:
Weird snapping when choosing the first vertex to trace. In general I can often observe the behaviour that the tracing starts at one vertex, then traces 2 vertices in the wrong direction and then takes the direct straight line to the initial start, creating a "tracing triangle".

Second Issue:
Tracing does not trace the line until the last selected vertex. The closest it gets is the second to last vertex.

---

- [tracing_issue_1.gif](https://issues.qgis.org/attachments/download/12716/tracing_issue_1.gif) (Andreas Wicht)
- [tracing_issue_2.gif](https://issues.qgis.org/attachments/download/12717/tracing_issue_2.gif) (Andreas Wicht)
- [tracing_issue_1_2.gif](https://issues.qgis.org/attachments/download/12718/tracing_issue_1_2.gif) (Andreas Wicht)
- [tracing_issue_3.gif](https://issues.qgis.org/attachments/download/12886/tracing_issue_3.gif) (Andreas Wicht)
- [tracing_issue_4.gif](https://issues.qgis.org/attachments/download/13078/tracing_issue_4.gif) (Andreas Wicht)

**Comment by gioman** [comment]
@roya0045 gave it a try and can't replicate any of the described issues (on latest master here).

**Comment by roya0045** [comment]
@gioman Nice!

**Comment by gioman** [comment]
Closing for lack of feedback.
