### ISSUE TITLE
Pip in Python 3.6 under QGIS 3.0.3 doesn't work

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26828]
Author Name: **Michal Hala** (Michal Hala)
Original Redmine Issue: [18997](https://issues.qgis.org/issues/18997)
Affected QGIS version: 3.0.3
Redmine category:pyqgis_console

---
Pip in Python 3.6 under QGIS 3.0.3 doesn't work. After typing: pip install _some module_ in command prompt or in PyQGIS console pip produces this error message: Fatal error in launcher: Unable to create process using '"'

This is very bad because user cannot install third party modules (extensions) to Python 3.6.

**Comment by alexbruy** [comment]
Please test with latest master. And don't forget to setup environment before running command.

**Comment by alexbruy** [comment]
Closed for the lack of feedback. Please reopen if necessary.
