### ISSUE TITLE
click on anything in plugin manager crashes qgis

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26830]
Author Name: **luke allen** (luke allen)
Original Redmine Issue: [18999](https://issues.qgis.org/issues/18999)
Affected QGIS version: 3.0.3
Redmine category:plugin_manager
Assignee: Borys Jurgiel

---
When i click on anything inside of the plugin manager qgis crashes immediately.

qgis 3.0.3 
arch linux

running from the command line this error shows up on crashing

free(): invalid pointer [1] 29800 abort (core dumped) qgis

**Comment by alexbruy** [comment]
Closed for the lack of feedback. Please reopen if necessary.
