### ISSUE TITLE
Limits in labels for raster symbology in discrete interpolation method are not shown

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26847]
Author Name: **Mario Reyes** (@ernesto561)
Original Redmine Issue: [19016](https://issues.qgis.org/issues/19016)
Affected QGIS version: 3.6.0
Redmine category:symbology

---
In QGIS 2.18, when the discrete interpolation method was selected for a raster, the labels used to show the lower and the upper limits. This is not the case with QGIS 3.03

---

- [QGIS 2.18.17.PNG](https://issues.qgis.org/attachments/download/12732/QGIS%202.18.17.PNG) (Mario Reyes)
- [QGIS 3.03.PNG](https://issues.qgis.org/attachments/download/12733/QGIS%203.03.PNG) (Mario Reyes)

**Comment by alexbruy** [comment]
Seems already fixed. Please check with latest master

**Comment by alexbruy** [comment]
Closed for the lack of feedback and because it is seems already fixed.
