### ISSUE TITLE
Label unit suffix for rasters not working

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26846]
Author Name: **Mario Reyes** (@ernesto561)
Original Redmine Issue: [19015](https://issues.qgis.org/issues/19015)
Affected QGIS version: 3.0.3
Redmine category:rasters

---
When I try to add a text using the label unit suffix in the properties of a raster in the style tab it doesn't work.

**Comment by alexbruy** [comment]
Seems already fixed. Please check with latest master.

**Comment by gioman** [comment]
Closing for lack of feedback.

**Comment by thuettel** [comment]
I came across the same problem using QGIS 3.4.11-Madeira on Windows 10. 

When I enter a label unit suffix on a raster nothing happens. After closing the properties window and reopening it again, the former input for the label unit suffix in the symbology tab is gone.

Also I couldn't find any documentation on this feature and what maybe needs to be considered with the inputs.

**Comment by gioman** [comment]
> I came across the same problem using QGIS 3.4.11-Madeira on Windows 10.

@thuettel too old.
