### ISSUE TITLE
Toolbars reorganisation is not saved when QGIS is closed

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26850]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [19019](https://issues.qgis.org/issues/19019)
Affected QGIS version: 3.1(master)
Redmine category:gui

---
I have many toolbars enabled in QGIS and I reorganize them so that from four rows by default, I only have two rows of tools (hence, more place for map canvas). But each time i open QGIS, the toolbars are moved back to the four rows placement instead of staying where i placed them. Very annoying!

**Comment by alexbruy** [comment]
Is this still an issue? I have never seen this on my system

**Comment by alexbruy** [comment]
Closing for the lack of feedback. Please reopen if necessary.
