### ISSUE TITLE
Forms in Layer Properties - default values aren't remembered.

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26872]
Author Name: **Jadwiga Trojak** (@troyaqgis)
Original Redmine Issue: [19042](https://issues.qgis.org/issues/19042)
Affected QGIS version: 3.0.3
Redmine category:forms

---
I noticed that default values in Forms (Layer Properties) aren't remembered.
I have a field (in gpkg layer) that I want to fill with the default value, applied on update, based on the expression (variable @user_account_name).
After filling out the section 'Defaults' with an expression (Default value), and pressing 'OK' or 'Apply' button the change isn't remebered.
Default value automatically changes to 'NULL'.

**Comment by SrNetoChan** [comment]
Can't replicate on QGIS 3.17 (kubuntu 20.04) or QGIS 3.16.3 (Windows 10). 

I think we can close this one @gioman
