### ISSUE TITLE
Difference algorithm doesn't work on Windows with MultiPoints

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26879]
Author Name: **gcarrillo -** (gcarrillo -)
Original Redmine Issue: [19049](https://issues.qgis.org/issues/19049)
Affected QGIS version: 3.1(master)
Redmine category:processing/qgis

---
The Difference algorithm from QGIS Processing seems to work differently depending on the Operating System used. 

With the sample GPKG data attached (two layers, one multipoint and one simplepoint, only one point in each layer), such algorithm works as expected on GNU/Linux, but on Windows it does not. 

On Windows, using the Difference algorithm with both input parameters pointing to the MultiPoint layer, the result is the same point, whereas on GNU/Linux the result of the Difference (Multipoint-Multipoint) is an empty layer, as expected.

See QGIS and dependency versions in the image attached.

---

- [test_difference.gpkg](https://issues.qgis.org/attachments/download/12745/test_difference.gpkg) (gcarrillo -)
- [2018-05-28.png](https://issues.qgis.org/attachments/download/12746/2018-05-28.png) (gcarrillo -)

**Comment by SrNetoChan** [comment]
Can't replicate neither on Linux Master (3.17) nor on Windows 10 (3.16.3). In both cases, using the same layer as both inputs for the difference algorithm will return an empty layer, as expected.

Probably the difference back when this ticket was because of different GEOS version in each platform.

@gioman  I think we can close this one.

**Comment by agiudiceandrea** [comment]
Just for the record, the native:difference algorithm fails using QGIS 3.10.14 (GEOS 3.8.1-CAPI-1.13.3) on Windows with the provided vector layer:

> GEOS geoprocessing error: difference failed.

Anyway, it seems working fine using QGIS 3.16.3 (GEOS 3.8.1-CAPI-1.13.3).
