### ISSUE TITLE
GRASS: Error due to missing locale

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26882]
Author Name: **Garth Fletcher** (@fgfletcher)
Original Redmine Issue: [19052](https://issues.qgis.org/issues/19052)
Affected QGIS version: 3.0.3
Redmine category:grass

---
GRASS r.contour and many other GRASS processes fail with error message:

"WARNING: Default locale settings are missing. GRASS running with C locale.
  Starting GRASS GIS...
  ERROR: Path '/<UNKNOWN>/<UNKNOWN>' doesn't exist
  Default locale not found, using UTF-8
  Exiting..."

**Comment by alexbruy** [comment]
Are you using GRASS plugin or Processing?

**Comment by gioman** [comment]
Closing for lack of feedback and as is not replicable. Reopen if necessary.
