### ISSUE TITLE
Copy attribute / Copy feature attributes doesn't return value if value is URI

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26899]
Author Name: **James Passmore** (@nmtoken)
Original Redmine Issue: [19069](https://issues.qgis.org/issues/19069)
Affected QGIS version: 3.0.3
Redmine category:unknown

---
When using the identify tool, and looking at the values of a feature in the Identify Results window, I can right click and copy the attribute value when the value is plain text or a number, but not when the value is an URI.  Similarly when I right click and select Copy feature attributes, I get all attribute names, but no values that are URIs.

For example, if I do a Copy feature attributes on the following feature (image)

![copy-attributes.png](https://issues.qgis.org/attachments/download/12759/copy-attributes.png)

I only get the following text:

```
fid: 52
identifier: #M4EU.CO_264675
commodity: TREO
commodityRank: 
commodityImportance: 
mineralOccurrenceName: Aksu Diamas
commodityClassifier_uri: 
mineralOccurrence_uri: 
specification_uri: 
endusepotential: 
representativeCommodity_uri: 
mineralOccurrenceType_uri: 
inspire: GB.BGS.EURARE
country: TR

```

---

- [copy-attributes.png](https://issues.qgis.org/attachments/download/12759/copy-attributes.png) (James Passmore)

**Comment by Pedro-Murteira** [comment]
This is still valid on QGIS 3.16.15 and 3.22.2.
