### ISSUE TITLE
saving a virtual layer makes qgis crash

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26902]
Author Name: **Lee Han** (Lee Han)
Original Redmine Issue: [19072](https://issues.qgis.org/issues/19072)
Affected QGIS version: 3.0.3
Redmine category:virtual_layers

---
## User Feedback

I was trying to "save as" on my computer, a virtual layer created from 2 shp in my project.
I tried 2 times and qgis crashed 2 times.

## Report Details

*Crash ID*: b1b732ff546db928598cc22bddeb086807097248

*Stack Trace*
```
RaiseException :
_FrameUnwindFilter :
RtlRestoreContext :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

```

*QGIS Info*
QGIS Version: 3.0.3-Girona
QGIS code revision: 8a899c8758
Compiled against Qt: 5.9.2
Running against Qt: 5.9.2
Compiled against GDAL: 2.2.4
Running against GDAL: 2.2.4

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by alexbruy** [comment]
Still true with latest 3.10/master?

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
