### ISSUE TITLE
Display file names when loading multiple GPX files to project

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26905]
Author Name: **Carolyn Krause** (Carolyn Krause)
Original Redmine Issue: [19075](https://issues.qgis.org/issues/19075)

Redmine category:gui

---
When adding a GPX file to a project, a popup window asks the user to select which types of layers to add from the GPX file. When adding multiple GPX files at a time, this dialog popups up once for each file, but there's no way to tell which file the current popup is referring to. 

Is it possible to add the name of the current GPX file to the top of the popup? Like in the attached image.

---

- [add gpx layers popup.png](https://issues.qgis.org/attachments/download/12761/add%20gpx%20layers%20popup.png) (Carolyn Krause)

**Comment by darrepac** [comment]
yes would be interesting

**Comment by alexbruy** [comment]
Fixed in master.
