### ISSUE TITLE
QGIS3.0.x GRASS PATH problem: "ERROR: Path '/<UNKNOWN>/<UNKNOWN>' doesn't exist"

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26903]
Author Name: **Garth Fletcher** (@fgfletcher)
Original Redmine Issue: [19073](https://issues.qgis.org/issues/19073)
Affected QGIS version: 3.0.3
Redmine category:processing/grass

---
QGIS3.0.3 : GRASS i.segment (and many others) fail with "ERROR: Path '/<UNKNOWN>/<UNKNOWN>' doesn't exist" message.

To simplify things I tested in a new Project which contained only the one raster layer.

Sane failure occurs in all variations tested:
  output to temporary files
  output to specified files
  skipped Goodness output
No output files are created.

Example Log Messages results (formatted for legibility):
  2018-05-31T10:55:07 INFO  GRASS GIS 7 execution commands
    g.proj -c proj4="+proj=tmerc +lat_0=42.5 +lon_0=-71.66666666666667 +k=0.999966667 
      +x_0=300000.0000000001 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=us-ft +no_defs"
    r.external 
      input="/Users/garthfletcher/QGIS_TEST/DEM_Lidar/DEM_Lid_all_tiles.tif" band=1 
      output="rast_5b100ccb100772" --overwrite -o
    g.region n=116928.0 s=67410.0 e=981480.0 w=934950.0 res=6.0
    i.group group=group_5b100ccb10edd3 input=rast_5b100ccb100772
    i.segment  threshold=0.01 method="region_growing" similarity="euclidean" 
      minsize=1000 memory=300 iterations=20 group="group_5b100ccb10edd3" 
      output=output95fb91ab62bf4f47b0e06a8d8f666930 
      goodness=goodness95fb91ab62bf4f47b0e06a8d8f666930 --overwrite
    g.region raster=output95fb91ab62bf4f47b0e06a8d8f666930
    r.out.gdal -t -m input="output95fb91ab62bf4f47b0e06a8d8f666930" 
      output="/Users/garthfletcher/QGIS_TEST/DEM_Lidar/Segmented.tif" 
      format="GTiff"  createopt="TFW=YES,COMPRESS=LZW" --overwrite
    g.region raster=goodness95fb91ab62bf4f47b0e06a8d8f666930
    r.out.gdal -t -m 
      input="goodness95fb91ab62bf4f47b0e06a8d8f666930" 
      output="/Users/garthfletcher/QGIS_TEST/DEM_Lidar/Goodness.tif" 
      format="GTiff"  createopt="TFW=YES,COMPRESS=LZW" --overwrite
  2018-05-31T10:55:07 INFO  GRASS GIS 7 execution console output
      WARNING: Default locale settings are missing. GRASS running with C locale.
      Starting GRASS GIS...
      ERROR: Path '/<UNKNOWN>/<UNKNOWN>' doesn't exist
      Default locale not found, using UTF-8
      Exiting...

Marked as "Easy fix" because I think (hope) it should be.

---

- [Capture d’écran 2018-06-04 à 07.58.00.png](https://issues.qgis.org/attachments/download/12771/Capture%20d%E2%80%99%C3%A9cran%202018-06-04%20%C3%A0%2007.58.00.png) (Ronan L)

**Comment by alexbruy** [comment]
Please test with latest master and 3.4.8 using also Lutra packages.

**Comment by alexbruy** [comment]
Closed for the lack of feedback.
