### ISSUE TITLE
Ability to clear Log Messages panel, and to reload it

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26911]
Author Name: **Garth Fletcher** (@fgfletcher)
Original Redmine Issue: [19081](https://issues.qgis.org/issues/19081)

Redmine category:gui

---
The contents of the Log Messages panel grow very long, thus awkward to scroll around.  This becomes a nuisance primarily when troubleshooting some issue requires frequent inspection of the log.

It could be nice to be able to periodically clear the Log Messages so that only subsequent messages would display.

The most robust implementation might be to maintain the entire session log, but provide:
 a "Clear" button which updates a "beginning of display" pointer to the current end of the log contents
    i.e., only subsequently appended messages will display
 a "Reload" button to reset the display pointer to the beginning of the log to display the entire log.

**Comment by sggreener** [comment]
We have the same issue so we second this request.

The individual qGIS log messages windows simply keep growing with no ability to clear them except by restarting qGIS.  We use the PostGIS message log a lot to read the results of RAISE NOTICE messages from triggers.

In order to clear the message log we have to restart which is OK once or twice but not when messages are written many times.

We notice also that if one kills the PostGIS message log (click X) it also requires a qGIS restart.

We simply want the ability to clear the whole log (right mouse click>clear or a button.

**Comment by jef-n** [comment]
No, you can clear each tab by closing it - it will reopen on a new message.   You can also right click an close all except the one you clicked. Trying to close the last tab, will only clear it.

**Comment by sggreener** [comment]
Yes, I can confirm that closing and re-opening works.
Thanks
Simon

**Comment by luipir** [comment]
closing... please reopen it if you find necessary some different behaviour.

**Comment by Nitaym** [comment]
Hey, I believe a "clear" button (or a right-click->clear) is a better fit. Can we reopen this?

**Comment by rkolka** [comment]
> 
> We use the PostGIS message log a lot to read the results of RAISE NOTICE messages from triggers.
> 

Since 3.32 #53431 RAISE NOTICE does not show up in PostGIS message log anymore. 

However, for information expected by user, RAISE INFO is more suitable anyway.

Per postgres/src/include/utils/elog.h:
```
#define INFO        17          /* Messages specifically requested by user (eg
                                 * VACUUM VERBOSE output); always sent to
                                 * client regardless of client_min_messages,
                                 * but by default not sent to server log. */
```

**Comment by ArnoGW1** [comment]
It's pretty confusing that closing a tab makes it clear and disappear. It usually means "this is still somewhere and you can reopen it" in other apps. I was looking for "clear" and had to come here to learn that "close" was this.

I agree with Nitaym that a "clear" button would be better. Maybe "close" should also not clear?
