### ISSUE TITLE
Unable to save shapefile to geopackage

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26915]
Author Name: **Patrick Dunford** (@enzedrailmaps)
Original Redmine Issue: [19085](https://issues.qgis.org/issues/19085)
Affected QGIS version: 3.0.3
Redmine category:unknown

---
Appears to save and message received "Successfully saved vector layer to .gpkg" but the resulting file has a zero length, then flagged as invalid data source when it attempts to add back to the project.

---

- [osYards.xz.bz2](https://issues.qgis.org/attachments/download/12764/osYards.xz.bz2) (Patrick Dunford)

**Comment by alexbruy** [comment]
Please test with latest master, there were a lot of work on Geopackages since 3.0

**Comment by gioman** [comment]
Closing for lack of feedback.
