### ISSUE TITLE
Reading feature types from PBF files

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26916]
Author Name: **Magnus Nilsson** (Magnus Nilsson)
Original Redmine Issue: [19086](https://issues.qgis.org/issues/19086)

Redmine category:data_provider

---
When I drop a PBF file, downloaded from http://download.geofabrik.de/, on QGIS 3.0.3, I get a window where I can select feaures based on geometry type (lines, points...). Quite often, I am more interested in filtering features based on attribute data (fuel station, restaurant, road type etc.). I would  like to see this implemented in QGIS. This would especially be relevant in processing models, where I could extract desired parts of the OSM data for further processing.

**Comment by Gustry** [comment]
I'm not sure this feature request will be accepted. This is not specific to PBF files, it's for now the normal workflow for all vector layers. Should we close it?

**Comment by alexbruy** [comment]
I think this should be closed.

**Comment by saberraz** [comment]
This is related to vector tiles in general, and will be implemented.

**Comment by Gustry** [comment]
@saberraz The PBF mentioned here is about the OSM vector data format, not about vector tiles. https://docs.mapbox.com/vector-tiles/specification/#how-are-openstreetmap-pbf-files-related-to-mapbox-vector-tiles

Are you sure @saberraz ?

**Comment by saberraz** [comment]
Ahhh...you are right
