### ISSUE TITLE
QGIS3 Labelling : Copy & Paste Style misses out label rotation setting and is always pasted as "auxiliary_storage_labeling_labelrotation"

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26928]
Author Name: **sand thorn** (sand thorn)
Original Redmine Issue: [19098](https://issues.qgis.org/issues/19098)
Affected QGIS version: 3.0.3
Redmine category:labelling

---
Steps to reproduce
1. activate label rotation to a field
2. copy style
3. paste style
4. label rotation now becomes activated as auxiliary_storage instead

2.18 doesn't have this.

**Comment by DelazJ** [comment]
@haubourg should this be closed.
> If only vector layers selected, it works just fine.

I understand that there's an issue if among the target layers, you select a group item. Shouldn't QGIS skip applying the style to the group item, and NOT change the rotation for the vector layers property?
(all being said, I did not try to reproduce the issue)
