### ISSUE TITLE
v.vect.stats creates cat & cat_ then fails

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26921]
Author Name: **Simon Dedman** (@simondedman)
Original Redmine Issue: [19091](https://issues.qgis.org/issues/19091)
Affected QGIS version: 3.0.3
Redmine category:processing/grass

---
Grass processing toolbox element v.vect.stats counts point layer data within polygon areas layers & calculates statistics. If you want to calculate stats & counts for multiple fields in the points layer (e.g. you have data for various years) you have to repeat the process each time, selecting the layer and field, giving the resultant count & stats columns appropriate names, which produces a new polygon layer with the two new data fields appended, AND a field called 'cat'. If you use this new poly layer as the input for e.g. the next year's data, the output layer will already have 'cat' from the first run, so will create 'cat_'. The user likely doesn't care about these fields and there's no info presented during the process about that this is - it looks like a counter but I could very well be wrong. In any case: if you run the process a THIRD time, the code is defeated (presumably) because 'cat' is present so it tries 'cat_' which is also present, so it fails. Subsequently the user has to deduce that this is the problem with no help, then goto layer properties, source fields, edit, select cat & cat_, delete fields, unedit, save.

Proposal:
1. have an option in the dialogue box to create 'cat' field and explain what it is. Turned on by default.
2. Have cat field naming schema: cat0, cat1 etc, up to cat9999999 above which point it'll break the 10 character limit. Notwithstanding if you ran v.vect.stats 10 million times manually you'd experience the heat death of the universe before you hit the 10 character limit.

**Comment by alexbruy** [comment]
@SimonDedman please test with master and latest 3.4.8

**Comment by alexbruy** [comment]
Closed for the lack of feedback.
