### ISSUE TITLE
QGIS 3.0.3, WARNING Field rast ignored, because of unsupported type raster

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26924]
Author Name: **al piszcz** (al piszcz)
Original Redmine Issue: [19094](https://issues.qgis.org/issues/19094)
Affected QGIS version: 3.0.3
Redmine category:rasters

---
1. Import vector layer and use QGIS Browser to connect and display vector data works fine.
2. Import GeoTIF raster data to table and the table is not display in QGIS Browser, the imported raster table is in the database when viewed with psql, sql, dbeaver.

Is it possible to display and then load rasters from the QGIS Browser in QGIS 3.0.3?

All raster types are enabled in PostGIS see below, the stored image is GeoTiff

PostGIS Log Message
2018-06-01T22:54:17 WARNING Field rast ignored, because of unsupported type raster

I tried a suggestion to modify the datasource line in the .qgs project file and reloaded, same error

<datasource>PG: dbname='tdb' host=localhost port=5444 user='postgres' sslmode=disable key='rid' table="mtiscanraster"."test" column=rast sql=</datasource>

tested column="rast" 'rast' rast

tdb=# select short_name from ST_GDALDrivers();
   short_name
-----------------
 VRT
 GTiff
 NITF
 HFA
 AAIGrid
 DTED
 PNG
 JPEG
 GIF
 XPM
 ILWIS
 SRTMHGT
 ISIS3
 JP2OpenJPEG
 FIT
 WMS
 RST
 INGR
 GSAG
 GSBG
 GS7BG
 R
 KMLSUPEROVERLAY
 MBTiles
 WMTS
 MRF
 MFF
 LCP
 EHdr
 ARG
 USGSDEM
 NWT_GRD
 BLX
 SAGA
 XYZ
 HF2
 ZMap
 GPKG

**Comment by alexbruy** [comment]
Fixed in master. Please retest.

**Comment by gioman** [comment]
Closing for lack of feedback.
