### ISSUE TITLE
Incorrect colour displayed on rasters

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26923]
Author Name: **Patrick Dunford** (@enzedrailmaps)
Original Redmine Issue: [19093](https://issues.qgis.org/issues/19093)
Affected QGIS version: 3.0.3
Redmine category:map_canvas

---
The colour displayed on the rasters is yellow instead of orange.

The rasters have been altered from the original with Gimp. They display correctly in lots of image viewers, but not in Qgis.

---

- [Screenshot_2018-06-03_14-56-18.png](https://issues.qgis.org/attachments/download/12767/Screenshot_2018-06-03_14-56-18.png) (Patrick Dunford)
- [Screenshot_2018-06-06_17-03-29.png](https://issues.qgis.org/attachments/download/12787/Screenshot_2018-06-06_17-03-29.png) (Patrick Dunford)
- [Screenshot_2018-06-06_17-33-39.png](https://issues.qgis.org/attachments/download/12788/Screenshot_2018-06-06_17-33-39.png) (Patrick Dunford)

---

Related issue(s): #29280 (relates)
Redmine related issue(s): [21463](https://issues.qgis.org/issues/21463)

---

**Comment by alexbruy** [comment]
Still true in 3.10/master?

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
