### ISSUE TITLE
Inability to resize columns in 'handle bad layers' dialogue box

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26920]
Author Name: **Simon Dedman** (@simondedman)
Original Redmine Issue: [19090](https://issues.qgis.org/issues/19090)
Affected QGIS version: 3.0.3
Redmine category:gui

---
One can resize the handle bad layers box as a whole by dragging the edge, although double clicking the toolbar fills the screen vertically but not horizontally, peculiarly.
However one cannot resize the columns within the dialogue box, meaning it can be impossible to see the names of the layers. See attachment.

---

- [QGIS GUi handle bad layers bug.png](https://issues.qgis.org/attachments/download/12765/QGIS%20GUi%20handle%20bad%20layers%20bug.png) (Simon Dedman)

**Comment by roya0045** [comment]
This was fixed.
