### ISSUE TITLE
WFS request with combined filter (BBOX  + PropertyIsEqual) not working

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26930]
Author Name: **Andreas Steffens** (Andreas Steffens)
Original Redmine Issue: [19100](https://issues.qgis.org/issues/19100)
Affected QGIS version: 3.0.3
Redmine category:qgis_server

---
I'm having problems getting a WFS request using a filter with two conditions (BBOX + PropertyIsEqual) to work with QGIS Server. My goal is to get all features within a certain area that have an attribute with a certain value. Sounds simple enough.

http://localhost:8081/cgi-bin/gis.server?service=WFS&request=GetFeature&version=1.1.0&map=C:\OSGeo4W\var\qgis\gis\overview.qgs&srsname=EPSG:3857&typename=projects&outputformat=geojson&filter=<Filter><And xmlns="http://www.opengis.net/ogc"><Or><PropertyIsEqualTo><PropertyName>id</PropertyName><Literal>8</Literal></PropertyIsEqualTo><PropertyIsEqualTo><PropertyName>id</PropertyName><Literal>9</Literal></PropertyIsEqualTo></Or><BBOX><PropertyName>geometry</PropertyName><Envelope xmlns="http://www.opengis.net/gml" srsName="EPSG:3857"><lowerCorner>1501468.311742801 6893026.717014579</lowerCorner><upperCorner>1505075.184015008 6896901.1188857835</upperCorner></Envelope></BBOX></And></Filter>

QGIS Server always returns an empty feature set on the combined request. Running separate requests with only a single filter condition however returns the correct results. I'm unsure as to whether my filter syntax is somehow wrong or QGIS Server doesn't support logical operators at all. Any help or fix would be appreciated!

**Comment by gioman** [comment]
This should have been be assigned the feedback label 4 years ago. Assuming is fixed, reopen if necessary.
