### ISSUE TITLE
Qgis internal pyramiding makes GeoTIff corrupted

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26937]
Author Name: **Andrew Shanin** (Andrew Shanin)
Original Redmine Issue: [19107](https://issues.qgis.org/issues/19107)
Affected QGIS version: 3.0.3
Redmine category:rasters

---
Gauss mode for internal pyramid creation mode corrupt file.

I check it out:
WIth Moda mode it's ok... 
Hm.  With Gausse mode it's ok too...

It's very strange. It's working, but sometimes...
What's about autobackup source?

**Comment by gioman** [comment]
Can't replicate.
