### ISSUE TITLE
Scale bar in Layout always opens at height of 11.9 mm

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26931]
Author Name: **Patrick Dunford** (@enzedrailmaps)
Original Redmine Issue: [19101](https://issues.qgis.org/issues/19101)
Affected QGIS version: 3.4.6
Redmine category:map_composer/printing

---
On my print composer (Layout as it is now called) the scale bar was set at a height of 7.1 mm at the bottom of the page. This size never changed in the 2.18 print composer. Now in 3.0, each time I open this layout, the scale bar always opens to a height of 11.9 mm.

---

- [scalebar_size.qgz](https://issues.qgis.org/attachments/download/13718/scalebar_size.qgz) (Raymond Nijssen)
- [Numeric_Scale_Bar_Height_Issue2.qpt](https://issues.qgis.org/attachments/download/14048/Numeric_Scale_Bar_Height_Issue2.qpt) (Steve Lowman)

**Comment by Meibes** [comment]
This is still a bug in 3.8.2

**Comment by HaVRane** [comment]
Still a bug in 3.10.1

**Comment by ekauq** [comment]
Still in 3.12.1

**Comment by raymondnijssen** [comment]
Thank you Nyall!! <3

**Comment by HaVRane** [comment]
Good news, and thanks for your effort, nyalldawson!
