### ISSUE TITLE
Add a parameter specifying if a CRS or Ellipsoid is Earth related or not

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26944]
Author Name: **Yannick Portier** (Yannick Portier)
Original Redmine Issue: [19114](https://issues.qgis.org/issues/19114)

Redmine category:projection_support

---
It is great to have celestial bodies CRS and ellipsoids definitions in the database, but it could be helpful to easily be able to sort out non-earth related ones.

**Comment by nyalldawson** [comment]
This would need to be added in the upstream proj library first
