### ISSUE TITLE
Add an ellipsoid method to QgsCoordinateReferenceSystem

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26942]
Author Name: **Yannick Portier** (Yannick Portier)
Original Redmine Issue: [19112](https://issues.qgis.org/issues/19112)

Redmine category:projection_support

---
It would be helpful to be able to retrieve the ellipsoid definition from the CRS.
Ideally, this would return the ellipsoid acronym if it is a known ellipsoid or the (a, rf) parameters if it is a user defined one.

**Comment by m-kuhn** [comment]
There is already the `QgsCoordinateReferenceSystem::ellipsoidAcronym()` method, is there something missing still?

**Comment by nyalldawson** [comment]
Yes, we should close
