### ISSUE TITLE
Saved default style in spatialite file not available when loaded

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26950]
Author Name: **kepa ov** (kepa ov)
Original Redmine Issue: [19120](https://issues.qgis.org/issues/19120)
Affected QGIS version: 3.0.3
Redmine category:data_provider/spatialite

---
Related to #20152.

Trying to save and load a default style saved in a spatialite file. The default styles are not loaded in the spatialite file after reloading.

1. In this example spatialite file, there are three layers, one each as point, linear, and polygon. Each layer style is saved similarly.

2. Using the drop-down dialogs at the bottom of the "Layer Properties - Symbology" window: "Style --> Save Style --> Save in Database (spatialite) -->"

3. In the dialog window that pops up titled "Save Style in Database" give it a filename aka "point", skip the description, and check the checkbox for "Use as default style for this layer."

4. Start a new project. After loading the layers from the spatialite file, none of the saved default styles are applied.

5. Furthermore, when attempting to load a style from the "Database Styles Manager" under "Other styles on (sic) the database" while the two default styles for the other feature types are listed, the style for the current one is not. (It should probably read "Other styles WITHIN the database")

6. This is repeatable for each layer of different feature type in the "Database Styles Manager": The default style for the layer in question is not present but the other default styles for the different feature types are. However, none of the features open with their default styles loaded.

**Comment by gioman** [comment]
Closing as seems fixed.
