### ISSUE TITLE
Add US Survey Feet as Unit Type

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26969]
Author Name: **Bruce Helton** (Bruce Helton)
Original Redmine Issue: [19139](https://issues.qgis.org/issues/19139)

Redmine category:geometry

---
Can you add the option of re-projecting coordinates to US Survey feet ?
I'm thinking you're using international feet in your units.
There's a difference of several feet when your coordinates are in the millions of feet (actual difference is about 2 feet for every million units)

*U.S. survey foot is exactly 1,200/3937 (10 decimal places)
*International foot is exactly 12x0.0254 (4 decimal places)

*National Institute of Standards & Technology

That would help us out considerably if you could address this issue.
Love QGIS ....!!

**Comment by eshattow** [comment]
Please re-open? This is a valid issue.

**Comment by nyalldawson** [comment]
@eshattow 

Please answer the open question at https://github.com/qgis/QGIS/issues/26969#issuecomment-495889590

There's currently insufficient information to fix this request

**Comment by eshattow** [comment]
> Author Name: **Nyall Dawson** (@nyalldawson)
> 
> Is this just a matter of adding survey feet/miles as a unit choice to the measure tool? Or does it go deeper than that?
> 
> * status_id  was changed from   Open   to Feedback

It should appear on project settings as a distance and area measurement option, and not assume that Feet = US Survey Feet, such that Map Units when selected (as in the measuring tool) and numeric input (such as advanced construction mode on digitizing tools) use this unit.

**Comment by eshattow** [comment]
From https://geodesy.noaa.gov/datums/newdatums/GetPrepared.shtml
```
What about state plane coordinates?
NGS will likely define State Plane Coordinates (SPCs) through the same projections and zones associated with NAD 83. See our [FAQ](https://geodesy.noaa.gov/web/science_edu/datums/newdatums/FAQNewDatums.shtml#WILL) to learn more.

SPCs are converted from meters using the conversion factor as defined by the individual states who have requested that NGS publish SPCs in feet. The two conversion factors are:

The International Foot
1 inch = 2.54 centimeters

The U.S. Survey Foot
1 meter = 39.37 inches
```
in reference to the transition to State Plane Coordinate System of 2022 (SPCS2022).
