### ISSUE TITLE
Issues viewing, selecting and fixing polygon layer

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26982]
Author Name: **Luke Hutchison** (@lukehutch)
Original Redmine Issue: [19152](https://issues.qgis.org/issues/19152)
Affected QGIS version: 3.0.3
Redmine category:editing

---
The attached polygon layer consists of several large contour polygons with holes in them. The two largest polygons have the diagonal lines running through them -- the boundary of those polygons needs to be moved out to the clip region. Where the two diagonal lines meet at the top, 10% of the way from the left, is roughly where the two largest polygons meet.

There are several problems when viewing this polygon layer in QGIS:

(1) If the entire polygon layer is not visible in the viewport, then nothing is rendered. This means that you can't zoom in very far, because the layer disappears.

(2) In edit mode while using the Vertex Tool, the left-most large polygon (the 10% or so at the top left of the layer) cannot be selected. If you mouse over it, the red selection controls do not appear on the vertices. If you mouse over anything to the right of the leftmost 10% of the shape, then the entire shape is highlighted with red selection controls, including the leftmost 10%. Therefore there seems to be a selection bounding box around most of the layer, but not the largest polygon in the left 10%. Somehow that is excluded from selection.

(3) Sometimes without rhyme or reason, none of the polygons can be selected with the Vertex Tool, even when it is in view. Conversely, occasionally you can select vertices in the left 10%, when you are zoomed in, but it seems that you have to mouse over the polygon with the Vertex Tool to turn it red before zooming. (I don't have a reliable way to reproduce.)

---

- [5000ft-polygons.gpkg](https://issues.qgis.org/attachments/download/12800/5000ft-polygons.gpkg) (Luke Hutchison)
- [5000ft.csv.gz](https://issues.qgis.org/attachments/download/12801/5000ft.csv.gz) (Luke Hutchison)

**Comment by gioman** [comment]
@lukehutch not really sure how you were able to get this geopackage from the WKT in the CSV (I wasn't able, as the WKT is invalid, and this is the reason of all of the problems you describe). Anyway the GPKG poses an interesting case:

1) it is an invalid geometry, as reported by the "topology checker" and the "check validity" tools

2) it makes the "check geometries" tool crash QGIS

3) the "fix geometries" tool fails

4) the layer cannot be imported in PostGIS or GRASS (so for example v.clean used from the Processing toolbox produces an empty output).

5) even the good old "0 buffer" method fails to produce some result


@nyalldawson how we should threat this case?

**Comment by nyalldawson** [comment]
I think we should at least fix the crash -- that shouldn't happen

**Comment by nyalldawson** [comment]
(I'll take a look at that when I get a chance)

**Comment by Pedro-Murteira** [comment]
Still a valid issue on QGIS 3.22.3.

**Comment by lbartoletti** [comment]
> * 
> 
> * it makes the "check geometries" tool crash QGIS

Crash on QGIS 3.24 but not on master.

On master, the "fix geometries" tools produces an empty geometry, is it OK? Yes and no, it depends :)

But the geometry is unusable on the map canvas: can't edit, disapear when zooming in, etc.

**Comment by alexbruy** [comment]
Tested with latest master 2ae70ebd8aaff61af6 (QGIS 3.33):
 - original GPKG is unusable
 - Fix geometries algorithm does no crash. The results vary depending on the used repair method: "Structure" produces empty geometry, while "Linework" takes a bit more time and produces usable output which renders on map when zooming in/out and can be edited. Editing is slow as it is a single comple geometry with lots of nodes.
 
This can be closed IMHO.
