### ISSUE TITLE
[Processing] GDAL translate needs more option

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26990]
Author Name: **Dominique Lyszczarz** (@domlysz)
Original Redmine Issue: [19161](https://issues.qgis.org/issues/19161)

Redmine category:processing/gdal
Assignee: Giovanni Manghi

---
As it's no more possible to edit the command, we really need extra parameters to take full advantage of GDAL translate, especially target résolution (-tr), resampling algorithm (-r), crop extent (-projwin), band selection (-b) and nodata assignation (-a_nodata).

**Comment by alexbruy** [comment]
Implemented in c224a01
