### ISSUE TITLE
Crash when switching user profiles (too early?)

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26993]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [19164](https://issues.qgis.org/issues/19164)
Affected QGIS version: 3.1(master)
Redmine category:project_loading/saving

---
## User Feedback

I did not do any particular thing: I opened QGIS with the wrong user profile and when I realized that, I went to Settings --> User profiles and select the one I wanted. No projet was launched.
Before that new instance opens, I asked to close the first one that I did not need. And kaboom

## Report Details

*Crash ID*: 44f67b67c7d2889d544899ef088e2cf98f00d77b

*Stack Trace*
```
QWidget::actions :
QMenu::clear :
QgsMapSaveDialog::updateExtent :
QgsMapSaveDialog::updateExtent :
QgsMapSaveDialog::updateExtent :
QgsMapSaveDialog::updateExtent :
QMetaObject::activate :
QgsProcessingParameterTypeFileDestination::acceptedPythonTypes :
QgsProcessingParameterTypeFileDestination::acceptedPythonTypes :
QgsProcessingParameterTypeFileDestination::acceptedPythonTypes :
QgsProcessingParameterTypeFileDestination::acceptedPythonTypes :
QgsProcessingParameterTypeFileDestination::acceptedPythonTypes :
QMetaObject::activate :
QFileSystemWatcher::`default constructor closure' :
QMetaObject::activate :
QFileSystemWatcher::directoryChanged :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsProcessingParameterTypeFileDestination::acceptedPythonTypes :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QCoreApplication::processEvents :
QgsMapSaveDialog::updateExtent :
QgsMapSaveDialog::updateExtent :
BaseThreadInitThunk :
RtlUserThreadStart :

```

*QGIS Info*
QGIS Version: 3.1.0-Master
QGIS code revision: 2e5e20eb54
Compiled against Qt: 5.9.2
Running against Qt: 5.9.2
Compiled against GDAL: 2.2.4
Running against GDAL: 2.2.4

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by PeterPetrik** [comment]
@DelazJ I am unable to replicate on MacOS nightly build... Can you confirm it is still the issue in current releases?

![switch_profiles](https://user-images.githubusercontent.com/804608/94923570-5b79be00-04bc-11eb-9762-dd4095351e7c.gif)

**Comment by gioman** [comment]
Closing for lack of feedback and as is not replicable. Reopen if necessary.
