### ISSUE TITLE
Translate and Warp raster do not offer ER Mapper *.ers format for output

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27000]
Author Name: **Thomas Campagne** (Thomas Campagne)
Original Redmine Issue: [19171](https://issues.qgis.org/issues/19171)
Affected QGIS version: 3.0.3
Redmine category:gdal_tools

---
Translate and Warp raster do not offer ER Mapper *.ers format for output.
It is part of the GDAL supported formats but it is not available in the "Save as type" drop down menu when specifying the output file.

It would be great if all GDAL supported formats could be available.

Thanks!

**Comment by alexbruy** [comment]
Seems already fixed. Please test with latest master.

**Comment by alexbruy** [comment]
Closed for the lack of feedback.
