### ISSUE TITLE
Error after copying layer style

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27004]
Author Name: **Stefan Rey** (@partas1982)
Original Redmine Issue: [19175](https://issues.qgis.org/issues/19175)
Affected QGIS version: 3.0.3
Redmine category:symbology

---
I have a layer from a PostgreSQL DB with a specific style / classificataion in QGIS. After this, I add the same layer from another PostgreSQL DB. To have the same styling, I copy the style from the existing layer, and paste it to freshly added layer (right click to the layer, styles --> copy/paste style). So far all works fine. If I save and reopen the QGIS project, non of the layers is displayed fine, respectively the project is not opened correctly.

pic1: layer after pasting the style, before closing the project
pic2: layer after reopening the project

---

- [pic1.png](https://issues.qgis.org/attachments/download/12812/pic1.png) (Stefan Rey)
- [pic2.png](https://issues.qgis.org/attachments/download/12813/pic2.png) (Stefan Rey)

**Comment by alexbruy** [comment]
Still true with 3.10/master?

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
