### ISSUE TITLE
.MDB not opening even when adding Values on Enviroment

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27012]
Author Name: **Neil Robin Corrales Montenegro** (Neil Robin Corrales Montenegro)
Original Redmine Issue: [19183](https://issues.qgis.org/issues/19183)
Affected QGIS version: 3.0.3
Redmine category:vectors

---
I tried opening some files from a Geology Map, but the .mdb file does not open properly, i added the values:
The names and the values of the variables are:

variable name: OGR_SKIP 
value: ODBC

variable name: PGEO_DRIVER_TEMPLATE 
value: DRIVER=Microsoft Access Driver (*.mdb, *.accdb);DBQ=%s

note that there is only one percent sign in the value of PGEO_DRIVER_TEMPLATE variable

but it still is not opening, even change on qgis.bin , im using qgis 3 and 2.18, 
[Imgur](https://i.imgur.com/ZDb3mvY.png)
<a href="https://imgur.com/ZDb3mvY"><img src="https://i.imgur.com/ZDb3mvY.png" title="source: imgur.com" /></a>
[img]https://i.imgur.com/ZDb3mvY.png[/img]
[url=https://imgur.com/ZDb3mvY][img]http://i.imgur.com/ZDb3mvY.png[/img][/url]

---

- [error mdb.png](https://issues.qgis.org/attachments/download/12821/error%20mdb.png) (Neil Robin Corrales Montenegro)
- [error mdb.png](https://issues.qgis.org/attachments/download/12822/error%20mdb.png) (Neil Robin Corrales Montenegro)

**Comment by MSBack** [comment]
I am having the same issue using QGIS 3.12.2.

**Comment by gioman** [comment]
Can anyone attach a sample dataset?
