### ISSUE TITLE
Installation of QGIS-Server 3.03 on Windows 7

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27011]
Author Name: **Radim Machů** (Radim Machů)
Original Redmine Issue: [19182](https://issues.qgis.org/issues/19182)
Affected QGIS version: 3.0.3
Redmine category:qgis_server

---
I have installed QGIS-Server 3.03-1 via osgeo4w-setup-x86.exe on my machine Windows 7.
Based on existing tutorials and hints:
- I edited httpd.conf and change 
   ScriptAlias /cgi-bin/ "C:\OSGeo4W/bin/" 
to ScriptAlias /cgi-bin/ "C:\OSGeo4W/apps/qgis/bin/"

But I am stuck while trying to run it:
- when I opened the url _http://localhost/qgis/qgis_mapserv.fcgi.exe?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities_, 
I have got an error page in a browser and the following record in apache log file:
_[warn] [client 127.0.0.1] (OS 109)Přesměrování bylo ukončeno.  : mod_fcgid: get overlap result error
[error] [client 127.0.0.1] Premature end of script headers: qgis_mapserv.fcgi.exe_

What did I wrong and how to force qgis-server to run?

Regards,

Radim

**Comment by alexbruy** [comment]
Such questions should be asked in other places like mailing lists, gis.stackexchange, etc.
