### ISSUE TITLE
QgsPoint class does not store empty point geometries

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27019]
Author Name: **Philip Whitten** (Philip Whitten)
Original Redmine Issue: [19190](https://issues.qgis.org/issues/19190)
Affected QGIS version: 3.5(master)
Redmine category:geometry

---
The QgsPoint class does not properly store empty point geometries.  For example, from the python console in QGIS 3.0.3:

@> QgsPoint().isEmpty()
False@

@> print(QgsPoint().asWkt())
Point (0 0)@

@> print(QgsPoint().createEmptyWithSameType().asWkt())
Point (nan nan)@

In comparison, for a LineString:

@> QgsLineString().isEmpty()
True@

@> print(QgsLineString().asWkt())
LineString ()@

The results observed for LineString are consistent with those for QgsPolygon and QgsGeometryCollection.

**Comment by lbartoletti** [comment]
Fixed in https://github.com/qgis/QGIS/pull/9645
