### ISSUE TITLE
No transparency widget and no icons/classes in layer panel, QGIS 3.1.0-Master

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27027]
Author Name: **Yaroslav Vasyunin** (@jarickkk)
Original Redmine Issue: [19198](https://issues.qgis.org/issues/19198)
Affected QGIS version: 3.7(master)
Redmine category:unknown

---
It worked good in QGIS 3.0.3-Girona. Look at the attached screenshot (On the left QGIS 3.0.3, on the right QGIS 3.1.0): I opened the same project in both versions of QGIS. In QGIS 3.1.0-Master you can't see classes in legends for raster and vector layers.

---

- [2018-06-15 13_14_16-Greenshot image editor.png](https://issues.qgis.org/attachments/download/12841/2018-06-15%2013_14_16-Greenshot%20image%20editor.png) (Yaroslav Vasyunin)

**Comment by nyalldawson** [comment]
There's not enough detail here to reproduce
