### ISSUE TITLE
Qgis desktop 3.0 breaks Cinnamon desktop in Linux Mint

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27037]
Author Name: **Francesc Marí** (Francesc Marí)
Original Redmine Issue: [19208](https://issues.qgis.org/issues/19208)
Affected QGIS version: 3.0.3
Redmine category:forms

---
Qgis desktop 3.0 breaks Cinnamon desktop in Linux Mint. This error occurs in window "Identify results" when trying to open "object consulting form"

**Comment by alexbruy** [comment]
Please check with 3.10/master and if issue persist provide more details, inlcuding exact steps to reproduce. But most likely this is a local or DE-specific issue.

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
