### ISSUE TITLE
Opacity slider widget resets raster styles

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27031]
Author Name: **Yaroslav Vasyunin** (@jarickkk)
Original Redmine Issue: [19202](https://issues.qgis.org/issues/19202)
Affected QGIS version: 3.0.3
Redmine category:symbology

---
If I embed the "opacity slider" widget in a raster layer (Layer Properties->Legend), then after applying changes it reset the style of the raster layer to some default one.

**Comment by alexbruy** [comment]
Seems already fixed. Please test with latest master.

**Comment by gioman** [comment]
Closing for lack of feedback.
