### ISSUE TITLE
Tracing with offset produce intersections

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27036]
Author Name: **Jan Lippmann** (@j-lippmann)
Original Redmine Issue: [19207](https://issues.qgis.org/issues/19207)
Affected QGIS version: 3.3(master)
Redmine category:digitising
Assignee: Martin Dobias

---
hello,

while digitizing with offset in some cases the tool produce intersections. the gif show one case with split.

affected versions: 3.0 and actual master

a little qgis project is in the attachment.

@martin dobias

it would be very kind of you, if you can have a look at this issue.

thank you very much

!tracing_offset_geometry_error.gif!

---

- [tracing_offset_geometry_error.gif](https://issues.qgis.org/attachments/download/12847/tracing_offset_geometry_error.gif) (Jan Lippmann)
- [tracing with offset.7z](https://issues.qgis.org/attachments/download/12848/tracing%20with%20offset.7z) (Jan Lippmann)

**Comment by Pedro-Murteira** [comment]
This is still true on QGIS 3.16.14 and 3.22.1.

**Comment by lbartoletti** [comment]
I can not reproduce the error. @Pedro-Murteira how do you reproduce it?

**Comment by Pedro-Murteira** [comment]
@lbartoletti I've been trying to reproduce it again, but I'm no longer being able to. Not really sure if I am not doing it correctly, or it got fixed.
@j-lippmann Can you still replicate it?

**Comment by j-lippmann** [comment]
there is no issue anymore. tested with QGIS 3.22.7
