### ISSUE TITLE
Ctrl+C doesn't copy, despite dialog prompt

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27035]
Author Name: **Loren Amelang** (@LorenAmelang)
Original Redmine Issue: [19206](https://issues.qgis.org/issues/19206)
Affected QGIS version: 3.0.3
Redmine category:gui

---
As the Subject says, In almost every place I've tried it, Ctrl+C is ignored but using the dialog Copy command works. The screenshot shows the Python Console, but it is definitely not confined to Python. Ctrl+C doesn't work in Log Messages, but at least that dialog doesn't show the Ctrl+C hotkey. 

I'd much rather the hotkey worked everywhere, but if there is some reason why it can't, is there some way to warn us we're in one of those places before we assume it did and paste some previous buffer we don't want? Maybe a failed Ctrl+C causes an error sound? Or a successful one causes a confirmation sound? 

Right now the only practical strategy is to assume the hotkey won't work and use the dialog Copy click. 

---

- [Ctrl+C doesn_t Copy.jpg](https://issues.qgis.org/attachments/download/12846/Ctrl+C%20doesn_t%20Copy.jpg) (Loren Amelang)

**Comment by roya0045** [comment]
Seems fixed

**Comment by uclaros** [comment]
You still can't copy from the log messages. The context menu doesn't suggest you can, but intuition does! I've ended up with a wrong copy buffer from the log messages quite a few times!
