### ISSUE TITLE
Add icons to options in Algorithm dialog 

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27046]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [19217](https://issues.qgis.org/issues/19217)

Redmine category:processing/gui

---
In QGIS dialogs, when eg creating a layer, options like geometry type or Field type have an associated icon
It could be nice to have them also shown in algorithm dialog (see eg "Add field to attributes table" for field type - I unfortunately can no longer find the alg which has a drop-down parameter with option like polygon, line, point...)

**Comment by alexbruy** [comment]
@DelazJ may I ask you to check again? I just opened some random Processing tools (Buffer, Basic statistics etc) and there are icons for both layer types and field types. Or maybe I misnderstand your request?

**Comment by DelazJ** [comment]
Hi @alexbruy 
Try with the abovementioned algs:
- the field type in "Add field to attributes table" could show the icon next to its value 
![image](https://user-images.githubusercontent.com/7983394/59968155-5007bb00-9535-11e9-8b0a-4be3deca38ef.png)
to mimic the eg create shapefile dialo field type
![image](https://user-images.githubusercontent.com/7983394/59968487-ebe7f580-953a-11e9-9570-67435be39149.png)
- In the create grids alg, it'd be the grid type parameter but I don't know if we already have icons for all of them
![image](https://user-images.githubusercontent.com/7983394/59968559-d45d3c80-953b-11e9-8243-12978a6dee37.png)
* there might be a couple of other algs in the "add fields to attributes table" case

**Comment by alexbruy** [comment]
Ah I see. But these parameters are `enum` parameters, not fields/layers and they never had icons. IMHO there is no sense in adding icons support here, as in wast majority cases icons are not used.

**Comment by DelazJ** [comment]
hi @alexbruy sure. No strong request from me. It was just an idea, particularly for the add fields alg to look like the add vector layer. If it's not possible/desirable/worthy/sensible or is complex I'm OK we put energy on something else. Thanks.

**Comment by alexbruy** [comment]
Closing for now, as I really see no sence in adding icons support for enum parameters which in wast majority cases provide selection from predefined set of values of any type (e.g. data type, resampling algorithm, units, etc.). Feel free to reopen if necessary.
