### ISSUE TITLE
TIN Interpolation Issue 

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27048]
Author Name: **Eric  Andelin** (Eric  Andelin)
Original Redmine Issue: [19219](https://issues.qgis.org/issues/19219)
Affected QGIS version: 3.0.3
Redmine category:vectors
Assignee: Eric  Andelin

---
When using the Tin Interpolation tool. There is an option to identify a layer as Point, Structure Line or Break line. However, when creating a TIN comprised of a point layer and a Structure line or Break line layer the resulting TIN is inconsistent in holding the Structure or Break line. Example: Road edges (AP-Purple), Road Crown (AC-Purple), Ground Break (GBRK-White), and Ditch (DTCH-Yellow) are all break lines. AS you can see in the sample image where you can see a purple line, the TIN did not hold to the break line.  

---

- [TIN_Ex.PNG](https://issues.qgis.org/attachments/download/12853/TIN_Ex.PNG) (Eric  Andelin)

**Comment by Brent-Edwards** [comment]
Still the same at 3.8.3-Zanzibar. In my tests, the output triangle vector file is exactly the same when when performing the interpolation with or without the extra break line and/or structure line parameters. The break/structure lines are not respected during the interpolation. The documentation for this tool is quite sparse - ex. difference between break and structure lines, format requirements (polylines vs. polygons, z values necessary?).

**Comment by jescott2** [comment]
Just a thought, I learned that Breaklines are ignored in TIN if the Breaklines are not in the same Projection as the Point Layer.

**Comment by Brent-Edwards** [comment]
Just tried this with the test project/data submitted with issue [https://github.com/qgis/QGIS/issues/31970](url) [(link to zipped project)](https://github.com/qgis/QGIS/files/3702635/qgis_interp_bug_31970_v2.zip)) I get the following error **"Layer 2 is set to use a value attribute, but no attribute was set"**. The tool seems to require an attribute to be set for break/structure lines.

See the log info below and the attached screen shot.
![tin_interpolation_error_attribute_required_for_breaklines](https://user-images.githubusercontent.com/13538726/73768149-8998d980-4746-11ea-8768-c2a4399c55ad.png)


QGIS version: 3.10.2-A Coruña
QGIS code revision: d4cd3cfe5a
Qt version: 5.11.2
GDAL version: 3.0.3
GEOS version: 3.8.0-CAPI-1.13.1 
PROJ version: Rel. 6.3.0, January 1st, 2020
Processing algorithm…
Algorithm 'TIN interpolation' starting…
Input parameters:
{ 'EXTENT' : '283796.0,283845.0,5041430.0,5041470.0 [EPSG:2950]', 'INTERPOLATION_DATA' : 'C:/Users/xedwabr/Downloads/qgis_interp_bug_31970_v2/qgis_tin_interp_bug_31970_v2.gpkg|layername=qgis_tin_interp_bug_31970 pts (interp on val column)::~::0::~::2::~::0::|::C:/Users/zzzz/Downloads/qgis_interp_bug_31970_v2/qgis_tin_interp_bug_31970_v2.gpkg|layername=qgis_tin_interp_bug_31970 tri (breaklines)::~::0::~::-1::~::2', 'METHOD' : 0, 'OUTPUT' : 'TEMPORARY_OUTPUT', 'PIXEL_SIZE' : 0.1, 'TRIANGULATION' : 'TEMPORARY_OUTPUT' }

Layer 2 is set to use a value attribute, but no attribute was set
Execution failed after 0.05 seconds

Loading resulting layers
Algorithm 'TIN interpolation' finished

**Comment by ciseur68** [comment]
Same issue on 3.10.9 : "Layer 2 is set to use a value attribute, but no attribute was set"

**Comment by gioman** [comment]
> Same issue on 3.10.9

@ciseur68 try QGIS 3.16.

**Comment by ADAMKEPES** [comment]
> > Same issue on 3.10.9
> 
> @ciseur68 try QGIS 3.16.



> > Same issue on 3.10.9
> 
> @ciseur68 try QGIS 3.16.

Of course it doesn't work with 3.16. Why would it work while there wasn't a fix for it in the cangelog? Things doesn't repair themselves. 

I'm struggling with this issue since the qgis 3.0. So Qgis have been a kind of GIS software for years wich can't generate a proper elevation raster from vector measurements...

**Comment by gioman** [comment]
> Of course it doesn't work with 3.16. Why would it work while there wasn't a fix for it in the cangelog? Things doesn't repair themselves.

@ADAMKEPES the tool works in general, if you have a specific input which make the tool fail, please share it.

About the rest of the comment... no comment.

**Comment by Brent-Edwards** [comment]
> > Of course it doesn't work with 3.16. Why would it work while there wasn't a fix for it in the cangelog? Things doesn't repair themselves.
> 
> [@ADAMKEPES](https://github.com/ADAMKEPES) the tool works in general, if you have a specific input which make the tool fail, please share it.
> 
> About the rest of the comment... no comment.

Specific input which makes the tool fail - https://github.com/qgis/QGIS/issues/27048#issuecomment-582014306. I just tested again with 3.44.8-Solothurn (LTR) and the same issue persists - Layer 2 is set to use a value attribute, but no attribute was set. Why are attributes needed for the break or structure lines? At the very least, the GUI/error message should be improved. The GUI allows the user to add a layer without specifying an attribute and with the "Use Z-coordinate" unchecked making it seem as though neither are required and the the error states otherwise.

**Comment by agiudiceandrea** [comment]
@Brent-Edwards please create a new issue report, since the issue you are reporting (if it is actually an issue) seems different from the one originally reported and subsequently fixed.

**Comment by Brent-Edwards** [comment]
> [@Brent-Edwards](https://github.com/Brent-Edwards) please create a new issue report, since the issue you are reporting (if it is actually an issue) seems different from the one originally reported and subsequently fixed.

https://github.com/qgis/QGIS/issues/66429
