### ISSUE TITLE
[Raster properties] Transparency tab: Add values from display button does nothing

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27059]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [19231](https://issues.qgis.org/issues/19231)
Affected QGIS version: 3.1(master)
Redmine category:rasters

---
open a raster layer properties dialog, Transparency tab
In the custom transparency options, there's a "Add values from display" button.
Clicking on it brings to the map canvas so that you can click inside and brings you back to the dialog but nothing is added to the list.

I don't know what it's supposed to render but I'm not sure that's the expected behavior.

I'm on windows 10, in case...

**Comment by alexbruy** [comment]
Already fixed. Please reopen if necessary.
