### ISSUE TITLE
Large tile downloads fail in map export

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27055]
Author Name: **Brendan Ryan** (Brendan Ryan)
Original Redmine Issue: [19226](https://issues.qgis.org/issues/19226)
Affected QGIS version: 3.0.3
Redmine category:map_composer/printing

---
When creating a large format map, such as Arch D 24"x36", map tiles, whether from XYZ provider or from QuickMapServices, fail to fully download when map is rendering. Seems like the download times out. Changing the timeout window in QMS does not solve the problem. Due to the large number of tiles I would assume. Maps then result in half-loaded basemap layers with any shapes successfully overlaid. Screenshot attached, occurs in both 2.18.18 and 3.0.3

---

- [issues.JPG](https://issues.qgis.org/attachments/download/12858/issues.JPG) (Brendan Ryan)

**Comment by roya0045** [comment]
Seems like a local issue dependent on connection speed.

**Comment by gioman** [comment]
Closing for lack of feedback.
