### ISSUE TITLE
Grayscale is not exporting well to PDF

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27054]
Author Name: **Alexandre Neto** (@SrNetoChan)
Original Redmine Issue: [19225](https://issues.qgis.org/issues/19225)
Affected QGIS version: 3.1(master)
Redmine category:map_composer/printing

---
This is a very strange issue I found on QGIS 3.0 and also on QGIS 3.1 (master) on Linux. For some reason, certain tones of gray are not exported correctly to PDF.

They work well when converted to JPEG or PNG, but not in PDF.

Look at the top corner squares and top elements of the legend of the samples I send.

It did not happen with other color ramps, for example, a red to white ramp.

There is also a zip with project and data for trying to replicate.

---

- [test_gray_scale.zip](https://issues.qgis.org/attachments/download/12855/test_gray_scale.zip) (Alexandre Neto)
- [testing grayscale_master.pdf](https://issues.qgis.org/attachments/download/12856/testing%20grayscale_master.pdf) (Alexandre Neto)
- [testing grayscale.jpeg](https://issues.qgis.org/attachments/download/12857/testing%20grayscale.jpeg) (Alexandre Neto)

**Comment by SrNetoChan** [comment]
It seems that this could be some strange behaviour on my computer only. Currently, opening the sample files I see no difference between the PDF and the JPG. I think we can close it.
