### ISSUE TITLE
[Layer properties] dynamic form of join works only once

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27050]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [19221](https://issues.qgis.org/issues/19221)
Affected QGIS version: 3.1(master)
Redmine category:forms

---
Join a table to a layer and enable the «dynamic form» option.
Do a symbology on one the joined fieldd. 
Outside QGIS, update the symbology field of the table data. The map is repaint accordingly. 
Do another change on the table data, nothing happens until afaics you open the join properties and apply that dialog. 

After each change outside QGIS you neef to open the join item properties to get the thus not so dynamic updated data.

**Comment by gioman** [comment]
@DelazJ still does not work on 3.22.3 as you described it (but now it does not even works on the first change), anyway I'm thinking if this is how it works.

The tooltip says "....to be automatically reloaded when the **target** field changes", and a a fact it works when changing the target field, not one of the joined ones.
