### ISSUE TITLE
default value error

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27061]
Author Name: **asghar ibraheem** (asghar ibraheem)
Original Redmine Issue: [19233](https://issues.qgis.org/issues/19233)
Affected QGIS version: 3.0.3
Redmine category:unknown

---
when i split a line which have already attribute defined, default values which i assigned to a postgis layer are added to one of its segment.

**Comment by gioman** [comment]
seems fine to me on 3.16.2, reopen if necessary.
