### ISSUE TITLE
Layer Properties > Source > Provider feature filter: accept Query which includes global or project variables

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27078]
Author Name: **Garth Fletcher** (@fgfletcher)
Original Redmine Issue: [19250](https://issues.qgis.org/issues/19250)

Redmine category:expressions

---
At present the Query Builder only supports layer fields in its queries.
It would be useful to also be able to reference global or project variables, for example:
    "disp_lev" >=  @Wshed_disp_lev
where "disp_lev" is a layer variable but @Wshed_disp_lev is a global or project variable.
In the above example, the layers consisted of watersheds of which only the top (largest) watersheds should be drawn.
Wanted to draw a series of maps starting with L1 (smallest/highest watersheds), L2 (next level in which some L1 watersheds were absorbed into L2 watersheds), L3...
@Wshed_disp_lev was used to set which map was being draw, and "disp_lev" to determine whether a watershed in lower levels needed to be drawn...

**Comment by alexbruy** [comment]
Duplicates #24662.
