### ISSUE TITLE
WFS 2.0 complex features not supported

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27076]
Author Name: **Kjetil Ringen** (Kjetil Ringen)
Original Redmine Issue: [19248](https://issues.qgis.org/issues/19248)

Redmine category:web_services_clients/wfs

---
Earlier I has opened this WFS with plugin in Q-gis 2.18, but i 3.0 this plugin is not available. The WFS is included in add layer, but it work not with a degree WFS, but still it work with plugin in 2.18

"Lag er ikke ugyldig: The layer IgnoreAxisOrientation='1' restrictToRequestBBOX='1' srsname='EPSG:25833' typename='app:Sted' url='http://wfs.geonorge.no/skwms1/wfs.stedsnavn50?' version='2.0.0' table="" sql= is not a valid layer and can not be added to the map. Reason: 

Capabilities for the WFS is:  https://wfs.geonorge.no/skwms1/wfs.stedsnavn50?service=WFS&version=2.0.0&request=GetCapabilities

**Comment by pathmapper** [comment]
Here's another example of complex features provided by an INSPIRE Protected Sites WFS 2.0:

https://inspire.brandenburg.de/services/ps_schutzg_wfs?service=WFS&version=2.0.0&request=GetCapabilities

https://inspire.brandenburg.de/services/ps_schutzg_wfs?service=WFS&request=GetFeature&version=2.0.0&srsName=urn:ogc:def:crs:EPSG::25832&typeNames=ps%3AProtectedSite&namespaces=xmlns(ps,http%3A%2F%2Finspire.ec.europa.eu%2Fschemas%2Fps%2F4.0)&count=1

**Comment by rouault** [comment]
Another example from https://github.com/qgis/QGIS/issues/52227:
https://servicios.idee.es/wfs-inspire/ocupacion-suelo?request=GetCapabilities&service=WFS
