### ISSUE TITLE
GDAL crash in QGIS only when saving a new raster

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27080]
Author Name: **Andrew Blakey** (Andrew Blakey)
Original Redmine Issue: [19252](https://issues.qgis.org/issues/19252)
Affected QGIS version: 3.1(master)
Redmine category:gdal_tools

---
When I attempt to run a snippet of code in QGIS's Python window that creates a GeoTiff, it crashes QGIS. If I run the same in Python 3.5.2 from the cli with the same dependencies it completes fine and creates the GeoTiff.  Any suggestions on how to further debug this would be appreciated.

```
import gdal, numpy

print(numpy.version.version)  # 1.14.5
print(gdal.VersionInfo())  # 2020200

gdal.UseExceptions()

data = numpy.zeros((100, 100), numpy.int8)

driver = gdal.GetDriverByName('GTiff')
outRaster = driver.Create('/tmp/output.tif', 100, 100, 1, gdal.GDT_Byte)
outRaster.SetGeoTransform((0, 0.05, 0, 0, 0, 0.05))
outBand = outRaster.GetRasterBand(1)
outBand.WriteArray(data)
outRaster = None

```

One of these three things is printed when the crash occurs

```
ERROR 4: Unable to open /tmp/output.tif to obtain file list.
QGIS died on signal 11

```

or

```
*** Error in `/usr/bin/qgis.bin': malloc(): memory corruption: 0x0000562f2bcce480 ***

```

or

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/osgeo/gdal.py", line 453, in Create
    return _gdal.Driver_Create(self, *args, **kwargs)
RuntimeError: Unable to open /tmp/output.tif to obtain file list.

```

**Comment by eneiluj** [comment]
Any news about this? Any way to avoid the crash at least?

I'm facing the same kind of problem on Ubuntu 19.04, QGIS 3.4 (from ubuntu's repos) or 3.8 (from QGIS repos).

I have this code in a plugin I'm developping:

``` python
import pcraster
raster_reclass = pcraster.lookupnominal('/somewhere/legendpath', '/somewhere/mappath')
```
It runs fine when executed manually outside QGIS but in my plugin or in the Python console inside QGIS, it produces:

```
Traceback (most recent call last):
  File ".../pcraster/python/pcraster/operations.py", line 1214, in lookupnominal
    _pcraster._rte().checkAndExec(operator, 1 + len(arg2))
RuntimeError: arg#2: Number of cells is different than clone or previous argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File ".../pcraster/python/pcraster/operations.py", line 1218, in lookupnominal
    raise RuntimeError("lookupnominal: %s" % (str(exception)))
RuntimeError: lookupnominal: arg#2: Number of cells is different than clone or previous argument
```

Any idea of the difference between the two contexts? Why would a Python code behave diffently when executed in QGIS?

**Comment by alexbruy** [comment]
From the error message it looks like permissions issue.

**Comment by eneiluj** [comment]
Good you say something here. We can close this because it was completely related with the pcraster module.

Thanks for the answer.
