### ISSUE TITLE
Crash at end load base application, before show work area

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27098]
Author Name: **toponomastica ufficio** (toponomastica ufficio)
Original Redmine Issue: [19270](https://issues.qgis.org/issues/19270)
Affected QGIS version: 3.2
Redmine category:unknown

---
## Report Details

*Crash ID*: 0a093f90f9ca0528dd79bfb91b18667eb927bed7

*Stack Trace*
```
QAbstractSocket::state :
QMetaCallEvent::placeMetaCall :
QApplicationPrivate::notify_helper :

```

*QGIS Info*
QGIS Version: 3.2.0-Bonn
QGIS code revision: bc43194061
Compiled against Qt: 5.9.2
Running against Qt: 5.9.2
Compiled against GDAL: 2.2.4
Running against GDAL: 2.2.4

*System Info*
CPU Type: i386
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
