### ISSUE TITLE
Crash on open - Mac OSX High Sierra

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27093]
Author Name: **Rhenriques Henriques** (Rhenriques Henriques)
Original Redmine Issue: [19265](https://issues.qgis.org/issues/19265)
Affected QGIS version: 3.2
Redmine category:mac_os_specific

---
Latest QGIS 3.2 compilation crashes on opening - Macos High Sierra

**Comment by PeterPetrik** [comment]
can you try with LTR from https://qgis.org/downloads/macos/ ?

**Comment by gioman** [comment]
Closing for lack of feedback, no issues with the latest installers on Catalina.
