### ISSUE TITLE
fails to create shapefile layer

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27092]
Author Name: **amandeep sadhal** (amandeep sadhal)
Original Redmine Issue: [19264](https://issues.qgis.org/issues/19264)
Affected QGIS version: 3.2
Redmine category:actions

---
# hi dear, i am trying but unsuccessful creating a shapfile layer. it is showing error that **layer creation failed and see the message log***

**Comment by alexbruy** [comment]
Please test with master. If error still exists add steps to reproduce and other details (e.g. stacktrace) which can help to debug issue.

**Comment by gioman** [comment]
Closing for lack of feedback.
