### ISSUE TITLE
Only limited number of layers displayed with 3.2

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27119]
Author Name: **Patrick Dunford** (@enzedrailmaps)
Original Redmine Issue: [19291](https://issues.qgis.org/issues/19291)
Affected QGIS version: 3.2
Redmine category:map_canvas

---
When my existing 3.0x projects are opened, not all of the layers can be displayed all at the same time. This is completely contrary to experience with 3.0 and all earlier editions. 

Sample data coming.

---

- [config.bz2](https://issues.qgis.org/attachments/download/12938/config.bz2) (Patrick Dunford)

---

Related issue(s): #27186 (relates)
Redmine related issue(s): [19358](https://issues.qgis.org/issues/19358)

---

**Comment by alexbruy** [comment]
Still true with latest 3.10/master?

**Comment by nyalldawson** [comment]
Closing due to lack of feedback
