### ISSUE TITLE
Data-defined legend is broken if "map units" are used 

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27110]
Author Name: **robert kalasek** (@rkalasek)
Original Redmine Issue: [19282](https://issues.qgis.org/issues/19282)
Affected QGIS version: 3.7(master)
Redmine category:map_legend

---
symbol sizing with size assistant returns properly scaled symbols in the qgis/layer tree and the copmposer legend properties tool but doesn't show any symbols in the print composers' map legend at all. 
a workaround which was done by unsing the layer styling / advanced / data-defined size legend returned valid results on any level if units are of "Milimeter", "Points" or "Pixels" 
but if "Meters at Scale" or "Map Units" are used symbol size and symbol labelling in the legend are faulty and (!) do not match to sizes used within the map. 
for exaples pls se the corresponding question in stackexchange 
https://gis.stackexchange.com/questions/287514/qgis-composer-symbol-size/287547?noredirect=1#comment460764_287547

rk

---

- [legend_broken.PNG](https://issues.qgis.org/attachments/download/14815/legend_broken.PNG) (Anita Graser)

**Comment by nyalldawson** [comment]
This is fixed in recent versions

**Comment by chleidersdorff** [comment]
Thiis looks like an issue that have crep in again. both the latest qgis and ltr have this legend issue.
![image](https://user-images.githubusercontent.com/52182284/169943045-697e7b64-5ec4-4d7e-9326-a866dfc81b73.png)
