### ISSUE TITLE
Autocomplete algorithms in Processing Modeller

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27112]
Author Name: **Tom Chadwin** (@tomchadwin)
Original Redmine Issue: [19284](https://issues.qgis.org/issues/19284)

Redmine category:processing/modeller

---
This is a UX suggestion from an FME user:

"I use the modeler quite a lot and I must admit I find myself typing in the 
model canvas expecting to see a list of processing tools come up like they 
do in FME sometimes. GUI improvements and customisation for the modeler 
would be lovely."

**Comment by alexbruy** [comment]
Duplicates #24271.
