### ISSUE TITLE
"Attribute Table" rows open randomly ordered? 

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27127]
Author Name: **Loren Amelang** (@LorenAmelang)
Original Redmine Issue: [19299](https://issues.qgis.org/issues/19299)
Affected QGIS version: 3.4.5
Redmine category:attribute_table

---
I've pretty much concluded the "Attribute Table" rows are randomly ordered unless you intentionally sort them - even if the actual shapefile is required to be in a specific order! Can this be?

The default order is not a problem of sorting numbers stored as text in the wrong numerical order. Typically 20 or 30 rows from near the top are relocated near the bottom, and almost all rows are randomized over a distance of maybe 10, as in 257, 251, 263, 262, 259, 266...  If there is a pattern I don't see it. 

If this is not a bug, could it be a feature request? When I view a shapefile I have created in a specific order, I'd like to see it displayed in that order! 

---

- [DB Mgr, Attrib local+fresh, FreeView, Excel.JPG](https://issues.qgis.org/attachments/download/12901/DB%20Mgr,%20Attrib%20local+fresh,%20FreeView,%20Excel.JPG) (Loren Amelang)
- [1st id1, ID0, ATid3.JPG](https://issues.qgis.org/attachments/download/12902/1st%20id1,%20ID0,%20ATid3.JPG) (Loren Amelang)
- [test_19299.geojson](https://issues.qgis.org/attachments/download/14624/test_19299.geojson) (Andrea Giudiceandrea)
- [test_19299.gml](https://issues.qgis.org/attachments/download/14625/test_19299.gml) (Andrea Giudiceandrea)
- [test_19299_shp.zip](https://issues.qgis.org/attachments/download/14626/test_19299_shp.zip) (Andrea Giudiceandrea)
- [test_19299.gpkg](https://issues.qgis.org/attachments/download/14627/test_19299.gpkg) (Andrea Giudiceandrea)

**Comment by landam** [comment]
Any progress BTW? Thanks.

**Comment by sal-eros-keta-baoia** [comment]
Hi. We are a small NGO working in Mozambique and had been using with great pelasure and results qgis for several years now. we do gather field GPS measurements from various places and then copy them to a central shp. But this way of showing records in random order makes verification very dificult. So we are stuck in version 2.2 valmiera. Any forecast of solving this issue? Could we help somehow? (we do not know coding) Thanks all for your great work.

**Comment by juhele** [comment]
@sal-eros-keta-baoia while I cannot help you with the issue (also waiting for solution) I would recommend you to upgrade at least to QGIS 2.18 "Las Palmas" which does not suffer this problem - there is version 2.18.28-2 available here:
https://qgis.org/downloads/

**Comment by roya0045** [comment]
@sal-eros-keta-baoia you could use a data source that require unique fids, such as geopackage and use that ID to sort things.

**Comment by gioman** [comment]
Moreover, add "insult to injury" https://github.com/qgis/QGIS/issues/34935

**Comment by sal-eros-keta-baoia** [comment]
Thanks for the sugestions. Some months ago I checked on the geopackage
format but felt insecure about the broad adoption of the format. For now I
suspect will be staying  with 2x versions while the problem is solved.

Hau idatzi du Giovanni Manghi (notifications@github.com) erabiltzaileak
(2020 mar. 8, ig. (23:28)):

**Comment by gioman** [comment]
> but felt insecure about the broad adoption of the format.

@sal-eros-keta-baoia don't be, shapefile have finally an expire date written on them. It is much better of you really think moving on to a much better format, that is already widely adopted: https://pt.slideshare.net/jachym/switch-from-shapefile
