### ISSUE TITLE
Repeated Crash making SQL Query in DB Manager

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27125]
Author Name: **Loren Amelang** (@LorenAmelang)
Original Redmine Issue: [19297](https://issues.qgis.org/issues/19297)
Affected QGIS version: 3.2.1
Redmine category:db_manager

---
My Attribute Table views show data rows sorted randomly. Trying to understand, I tried this against a shapefile: 

Database -> DB Manager -> Virtual Layers -> QGIS Layers -> Profiles -> SQL Window ->
select * from ProfilesLinesOnly
order by id

It auto-enters only "ProfilesLinesOnly" despite showing "ProfilesLinesOnly 100-50..." in the Tree...
And it forces the column name to "id" despite showing "ID" in the Attribute Table. 

It crashed!!  And "Reload QGIS" didn't...

---
## Report Details

*Crash ID*: 7f7fe12663f1e633a0c13ed0e00e224678193a18

*Stack Trace*
```
RaiseException :
_TypeMatch :
RtlCaptureContext :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

```

*QGIS Info*
QGIS Version: 3.2.0-Bonn
QGIS code revision: bc43194061
Compiled against Qt: 5.9.2
Running against Qt: 5.9.2
Compiled against GDAL: 2.2.4
Running against GDAL: 2.2.4

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.16299
---

I tried again with the spaces removed from the shapefile name in QGIS and on disk: 

Database Error
An error occurred
(wait cursor, blank dialog)
Crashed on close:

---
## Report Details

*Crash ID*: 26a6ac7056ec4001ffdb66d4cdd268098d2a2145

*Stack Trace*
```
QBasicMutex::unlockInternal :
QgsTask::processSubTasksForTermination :
QgsTask::cancel :
PyInit__core :
PyCFunction_FastCallDict :
PyObject_GenericGetAttr :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyObject_CallFunctionObjArgs :
PyObject_Call :
PyInit_sip :
std::basic_string<char,std::char_traits<char>,std::allocator<char> >::shrink_to_fit :
PyInit__core :
QgsTask::subTaskStatusChanged :
QMetaCallEvent::placeMetaCall :
QObject::event :
PyInit__core :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

```

*QGIS Info*
QGIS Version: 3.2.0-Bonn
QGIS code revision: bc43194061
Compiled against Qt: 5.9.2
Running against Qt: 5.9.2
Compiled against GDAL: 2.2.4
Running against GDAL: 2.2.4

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.16299
---

Again, with "ID", "asc" added to sort:

---
## Report Details

*Crash ID*: 26a6ac7056ec4001ffdb66d4cdd268098d2a2145

*Stack Trace*
```
QBasicMutex::unlockInternal :
QgsTask::processSubTasksForTermination :
QgsTask::cancel :
PyInit__core :
PyCFunction_FastCallDict :
PyObject_GenericGetAttr :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyObject_CallFunctionObjArgs :
PyObject_Call :
PyInit_sip :
std::basic_string<char,std::char_traits<char>,std::allocator<char> >::shrink_to_fit :
PyInit__core :
QgsTask::subTaskStatusChanged :
QMetaCallEvent::placeMetaCall :
QObject::event :
PyInit__core :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

```

*QGIS Info*
QGIS Version: 3.2.0-Bonn
QGIS code revision: bc43194061
Compiled against Qt: 5.9.2
Running against Qt: 5.9.2
Compiled against GDAL: 2.2.4
Running against GDAL: 2.2.4

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.16299
---

I gave up. I'm far from a SQL expert, but it shouldn't crash even if my queries are stupid. 

---

- [Doc error on download page.JPG](https://issues.qgis.org/attachments/download/12991/Doc%20error%20on%20download%20page.JPG) (Loren Amelang)
- [SQL error 19297.JPG](https://issues.qgis.org/attachments/download/13119/SQL%20error%2019297.JPG) (Loren Amelang)
- [SQL error 19297 crash report.JPG](https://issues.qgis.org/attachments/download/13120/SQL%20error%2019297%20crash%20report.JPG) (Loren Amelang)
- [Mystery project (not) in OSGeo4W64 after crash.JPG](https://issues.qgis.org/attachments/download/13121/Mystery%20project%20(not)%20in%20OSGeo4W64%20after%20crash.JPG) (Loren Amelang)

**Comment by alexbruy** [comment]
Should we close this?

**Comment by LorenAmelang** [comment]
If nobody else is running into it, probably not worth chasing further.  But...  

In reading through it again, I see what is happening in the reports like:

> 2018-08-12T10:54:15     WARNING    Unable to load C:\Users\loren\Giant
> 2018-08-12T10:54:15     WARNING    Unable to load C:\OSGeo4W64\bin\Files\HEC-RAS
> 2018-08-12T10:54:15     WARNING    Unable to load C:\OSGeo4W64\bin\Dam
> 2018-08-12T10:54:15     WARNING    Unable to load C:\OSGeo4W64\bin\Break\QGIS

The project causing the problems was saved in a directory at:
C:\Users\loren\Giant Files\HEC-RAS Dam Break\QGIS Projects\FEMA808\...

Pretty obviously the query has not properly "quoted" that string, and is dividing it up, at each included space, among a series of failing queries. Someone who knows how a file path that works in QGIS gets converted into an SQL query target could probably find the problem spot and fix it quickly! 

Surprised I didn't notice that immediately! Guess I just really needed a break...

**Comment by gioman** [comment]
Not replicable here on QGIS master, please reopen if necessary (attaching sample data).
