### ISSUE TITLE
Remember input layers in a processing model

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27131]
Author Name: **Magnus Nilsson** (Magnus Nilsson)
Original Redmine Issue: [19303](https://issues.qgis.org/issues/19303)

Redmine category:processing/modeller

---
When creating a new model, I often need to run a model quite a few times to test it. Each time, I have to select input layers manually when starting the model. I would like an option to make make QGIS remember the files I picked the last time I ran the model.

**Comment by nyalldawson** [comment]
Fixed
