### ISSUE TITLE
Qgis 3.2 and Python 3.7

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27147]
Author Name: **Arthur Vignacq** (Arthur Vignacq)
Original Redmine Issue: [19319](https://issues.qgis.org/issues/19319)
Affected QGIS version: 3.2
Redmine category:build/install

---
Hello,

I've tried today to install QGIS 3.2 on mac osx with Python 3.7 new install. 
No old version of Python nor Qgis installed on this computer. 
Installation of GDAL worked but QGIS refused to install because "need Python 3" to be installed first.

I verified this twice with same error.

Then I also installed Python 3.6.6. and the it worked.

I don't know if this is related with https://github.com/qgis/QGIS/issues/26319#issuecomment-495886177, but it also affects the Python relation with QGIS on mac

**Comment by PeterPetrik** [comment]
not an issue with all-in-one installer

**Comment by alexbruy** [comment]
Should be closed?
