### ISSUE TITLE
Filter features by geometry type

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27141]
Author Name: **Magnus Nilsson** (Magnus Nilsson)
Original Redmine Issue: [19313](https://issues.qgis.org/issues/19313)

Redmine category:processing/modeller

---
It would be useful with an algorithm for filtering features by their geometry type (point, line, polygon, no geometry...) in a processing model.

**Comment by nyalldawson** [comment]
Possible in 3.14
