### ISSUE TITLE
Import data sources, no names for multiple files

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27195]
Author Name: **d quintao** (d quintao)
Original Redmine Issue: [19367](https://issues.qgis.org/issues/19367)

Redmine category:data_source_manager

---
When we import multiple files and are asked for the data source, Tracks or Waypoints or Routes, the window appears without the name of the file we are opening sources from.

Fine if we open 3 or 4 files and only want tracks from all.  But what if we want tracks from some, routes from some, waypoints from some, there is no filename at the window title so we might import the wrong sources attributes.

**Comment by alexbruy** [comment]
Already fixed in master. Please reopen if necessary.
