### ISSUE TITLE
Enable bold for layer labels is too difficult

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27198]
Author Name: **d quintao** (d quintao)
Original Redmine Issue: [19370](https://issues.qgis.org/issues/19370)

Redmine category:labelling

---
To enable Bold font I now need to go through the "Data defined override" > Field type.

Is this a good thing? I find it more cumbersome than clicking on a Bold button.

**Comment by haubourg** [comment]
Let's close this since we also closed #27357
