### ISSUE TITLE
Can't lock the map scale in canvas

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27191]
Author Name: **d quintao** (d quintao)
Original Redmine Issue: [19363](https://issues.qgis.org/issues/19363)
Affected QGIS version: 3.2
Redmine category:map_canvas

---
When I stretch the right side style panel across screen to enlarge it the map shrinks down in scale.  I want the scale to be fixed because I set it to the same scale as the Layout window map scale.

**Comment by roya0045** [comment]
I cannot replicate when changing window size.

**Comment by gioman** [comment]
Closing for lack of feedback.
