### ISSUE TITLE
hide legend classes

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27203]
Author Name: **Gavin Fleming** (@gubuntu)
Original Redmine Issue: [19375](https://issues.qgis.org/issues/19375)

Redmine category:symbology

---
I have a rule based classification where the symbol is the same but the filter and scale dependency are different across classes. 

When I do a GetLegendGraphic I get each class in the legend but I only want one (since each one is the same)

A good way to achieve this might be a 'hide class' checkbox in each rule, or even 'hide in composer' and 'hide in GetLegendGraphic'

**Comment by jgrocha** [comment]
@gubuntu If you have rules with associated filters, you will have different entries in your legend. But if the rules were created just to have different styles for different scales, you may try a different approach. You can use the Single symbol with different symbol layers. For each symbol layer, you can play with scale visibility.

Probably this is not enough for your use case, but I just want to make sure I've understood your feature request.

![just one class](https://user-images.githubusercontent.com/163681/79636103-34793b00-816d-11ea-95f1-b161c1476219.png)

**Comment by gubuntu** [comment]
thanks, I haven't tested this approach but it looks like it will do the trick. So I guess you can close this.
