### ISSUE TITLE
Keep unavailable (defect) online ressources in QGIS when opening a qgis project file

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27217]
Author Name: **Lukas Wischounig** (Lukas Wischounig)
Original Redmine Issue: [19389](https://issues.qgis.org/issues/19389)

Redmine category:actions

---
Hello together!

First i want to say thanks to all the people who are working on that great project.

I am asking myself why QGIS deletes (temporary) unavailable (in QGIS they are in my opinion somewhat misleading called "defect" layers) online ressource layers (wms, wcs etc.) when a project is opened and these sources are unavailable. I am often switching between an online and an offline machine and this behaviour is cumbersome. I propose to keep them in the layer list and mark them as (temporary) unavailable (with a red exlamation mark or something like this) and add the possibility to reload the layer in the right mouse context menu of this item. I think this would be a good benefit.

There is also no workaraound by saving these online ressources as a layer definition file because this definition is, when opened in qgis, static and has no reload option. So it is not posible to reload the layer when being online again. Perhaps i am doing something completly wrong here...??

Kind regards
lupo

**Comment by GISsymbology** [comment]
The feature is present starting from QGIS 3.6
