### ISSUE TITLE
Parssing of empty geometry values from MicroSoft SQL Server

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27225]
Author Name: **Philip Whitten** (Philip Whitten)
Original Redmine Issue: [19397](https://issues.qgis.org/issues/19397)
Affected QGIS version: 3.2
Redmine category:data_provider/mssql

---
QGIS 3.2.0 passes empty geometry values from MicroSoft SQL Server databases as being null (for example, when a geometry created within MicroSoft SQL server as geometry::STLineFromText('LINESTRING EMPTY', 4326) is passed to QGIS).

**Comment by roya0045** [comment]
Is this a bug? To me an empty geometry is a null geometry.
