### ISSUE TITLE
The python console does not run files with special characters in the filename (character encoding issue)

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27233]
Author Name: **Peter Bontinck** (@PeterBontinck)
Original Redmine Issue: [19405](https://issues.qgis.org/issues/19405)
Affected QGIS version: 3.2
Redmine category:pyqgis_console
Assignee: Salvatore Larosa

---
1) python script file  : C:\Desktop\french é ë ç\UploadScriptPy3.py

2) You can open to the file to edit in the build in editor, but when you puch "run script": 

3) FileNotFoundError: [Errno 2] No such file or directory: b'C:/Desktop/french \xc3\xa9 \xc3\xab \xc3\xa7/UploadScriptPy3.py'

Looks like some character encoding issue: u'\french é ë ç\' becomes  '/french \xc3\xa9 \xc3\xab \xc3\xa7/'

This was not a problem in QGIS2.18

---

- [screen.JPG](https://issues.qgis.org/attachments/download/12957/screen.JPG) (Peter Bontinck)
- [Capture.JPG](https://issues.qgis.org/attachments/download/12959/Capture.JPG) (Peter Bontinck)

**Comment by gioman** [comment]
Seems fixed, please reopen if necessary.
