### ISSUE TITLE
MultiPoint geometry existing in PostGIS table blocks showing Polygons-type objects  in Browser-PostGIS

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27232]
Author Name: **Arkadiusz P** (Arkadiusz P)
Original Redmine Issue: [19404](https://issues.qgis.org/issues/19404)
Affected QGIS version: 3.2
Redmine category:browser

---
If PostGIS table (with defined "geoemetry-type" column) constains at least one record storing "MultiPoint" type geometry, it causes that in Browser (Browser -> PostGIS -> database_alias -> public -> geometry_types) a polygon-type entry are not displayed, thus blocking access to this kind of objects.

Removing from database MultiPoint record and refreshing list in Browser -> PostGIS makes this geoemetry visible again.

**Comment by gioman** [comment]
Does not seems to be the case anymore, reopen if necessary.
