### ISSUE TITLE
Layer filters not being saved to .qgs file

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27234]
Author Name: **Nate Wessel** (Nate Wessel)
Original Redmine Issue: [19406](https://issues.qgis.org/issues/19406)
Affected QGIS version: 3.2
Redmine category:unknown

---
I have a QGIS project (.qgs file) that was created by an earlier version, but is now being worked with by version 3.2. As I edit the project, save it and reopen it everything seems to work normally except that the filters on a couple of my layers revert back to the state they were in when I opened the project. Things like active layers, symbols, and map extent seem to get saved and are right where I left them when I open the project anew. It's just that the layer filters don't seem to be updated. 

This is a PostGIS layer with a simple filter expression like "user_id = 'B'". I am able to change the filter with no problems and it works as expected, it just don't get saved.

**Comment by Pedro-Murteira** [comment]
I can't replicate this issue on QGIS 3.16.15 and 3.22.2.
