### ISSUE TITLE
Shapefile displayed layer name based on style

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27236]
Author Name: **Maxime RIOU** (Maxime RIOU)
Original Redmine Issue: [19408](https://issues.qgis.org/issues/19408)

Redmine category:map_legend

---
When using styles and presets in QGIS 2.18, the shapefile can change colors but the displayed name remains the same. 
I would like to have a displayed name changing when changing the style / preset. 

For example: "township", a shapefile of polygons representing townships could have "style 1: density of population : tonwship" and "style 2: number of household / township" . 

If I want two composers with these two different maps, the automatic legend will have only one title which is the displayed name.

---

Related issue(s): #25356 (relates)
Redmine related issue(s): [17459](https://issues.qgis.org/issues/17459)

---

**Comment by nyalldawson** [comment]
This is a won't fix IMO
