### ISSUE TITLE
In an Attributes Table, if you hide all columns, you can't right-click a column header to show them!

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27250]
Author Name: **Loren Amelang** (@LorenAmelang)
Original Redmine Issue: [19422](https://issues.qgis.org/issues/19422)
Affected QGIS version: 3.2
Redmine category:attribute_table

---
So obviously, don't do this...  But I accidentally did hide the columns I didn't want deleted and then delete the ones I did want gone. Now there are no column headers visible to right-click in! 

[[https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/attribute_table.html?highlight=table%20view#hiding-and-organizing-columns-and-enabling-actions]]
By right-clicking in a column header, you can choose to hide it from the attribute table. To change several columns behavior at once, unhide a column or change the order of the columns, choose Organize columns …. In the new dialog, you can:
    check/uncheck columns you want to show or hide...

I finally tried creating a new column - which let me unhide the old ones. 

Somehow I doubt this is a desirable solution, but I couldn't find any others. If it is the only one, maybe add it to the documentation?

**Comment by DelazJ** [comment]
> Somehow I doubt this is a desirable solution, but I couldn't find any others. If it is the only one, maybe add it to the documentation?

I also doubt this is desirable, likely a bug that documentation writers have also reported at #23397. So this one is likely a duplicate we can close.

**Comment by alexbruy** [comment]
Duplicates #23397
