### ISSUE TITLE
SLD import interprets specific text as decimal in scientific notation

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27262]
Author Name: **Bo Thomsen** (Bo Thomsen)
Original Redmine Issue: [19434](https://issues.qgis.org/issues/19434)
Affected QGIS version: 3.2
Redmine category:symbology

---
(Actually, I'm not sure if it's a bug or a feature...) 

When importing af SLD style layout file with filter element values and the value ex. looks like this: "4e-003" the value is mis-interpreted as a decimal (in scientific notation) instead of a string  

 ```
          <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc">
            <ogc:PropertyIsEqualTo>
              <ogc:PropertyName>underelement_kode</ogc:PropertyName>
              <ogc:Literal>11a-002</ogc:Literal>
            </ogc:PropertyIsEqualTo>
          </ogc:Filter>
```

The above SLD part is converted to a QGIS style rule like this: _underelement_kode = '11a-002'_

However this example is misinterpreted

```
          <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc">
            <ogc:PropertyIsEqualTo>
              <ogc:PropertyName>underelement_kode</ogc:PropertyName>
              <ogc:Literal>11e-002</ogc:Literal>
            </ogc:PropertyIsEqualTo>
          </ogc:Filter>
```

It's converted to a QGIS style rule like this: _underelement_kode = 0.11_

Changing the SLD style element to <ogc:PropertyIsLike> which must have a string value doesn't change the behavior. It will make a rule like this: _underelement_kode LIKE '0.11'_ instead of: _underelement_kode LIKE '11a-002'_

The example file contains a SLD created from a correct rule-based styling in QGIS with the abovementioned values and exported as a SLD file.
When re-imported into QGIS the style rules for values that can be interpreted as a decimal in scientific notation have changed ("4e-003" --> 0.004)

---

- [flade fra QGIS.sld](https://issues.qgis.org/attachments/download/12973/flade%20fra%20QGIS.sld) (Bo Thomsen)
- [flade fra QGIS.sld](https://issues.qgis.org/attachments/download/12976/flade%20fra%20QGIS.sld) (Bo Thomsen)

**Comment by rldhont** [comment]
Is the `underelement_kode` field type is String ?

**Comment by rldhont** [comment]
It seems to be fixed:
```
from qgis.PyQt.QtCore import QVariant
from qgis.PyQt.QtXml import QDomDocument
from qgis.core import QgsOgcUtils, QgsVectorLayer, QgsField

f = '''<?xml version="1.0" encoding="UTF-8"?>
    <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc">
      <ogc:PropertyIsEqualTo>
        <ogc:PropertyName>underelement_kode</ogc:PropertyName>
        <ogc:Literal>11e-002</ogc:Literal>
      </ogc:PropertyIsEqualTo>
    </ogc:Filter>
'''
d = QDomDocument('filter')
d.setContent(f, True)

vl = QgsVectorLayer('Point', 'vl', 'memory')
vl.dataProvider().addAttributes([QgsField('id', QVariant.LongLong),QgsField('underelement_kode', QVariant.String)])
vl.updateFields()
e = QgsOgcUtils.expressionFromOgcFilter(d.documentElement(),vl)
e.expression()
```
returns
```
underelement_kode = '11e-002
```
But Id' like to add some tests before closing it.

**Comment by rldhont** [comment]
I am waiting for https://github.com/qgis/QGIS/pull/30378 to propose a PR.
