### ISSUE TITLE
High memory usage with Snap geometries to layer and "exception:unknown" message

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27264]
Author Name: **Antoine Lafranchis** (@alafr)
Original Redmine Issue: [19436](https://issues.qgis.org/issues/19436)
Affected QGIS version: 3.7(master)
Redmine category:digitising

---
In some circumstances, the computer freezes with 99.9% memory usage (then task manager stops responding...) when using the algorithm 'Snap geometries to layer'.
It apparently happens only when snapping a line layer to a point reference layer, with a small tolerance (0.00001 or lower).
It happend initially on a huge shapefile with geometry errors, but then I could reproduce it with tempopary layers: a line layer with a single line and a point layer with 3 points: the 1st point was precisely on a vertex, the 2nd point close to a second vertex (within the tolerance radius) and the 3rd point quite far from the line.

Because I had to "brutally" shut down and restart the computer, I don't have any test file to attach and no crash log. The only details that were left were the processing history: ```processing.run("qgis:snapgeometries", {'INPUT':'Point?crs=EPSG:4326&uid={50146ea0-3a7a-4515-8241-e842f2ef1717}','REFERENCE_LAYER':'LineString?crs=EPSG:4326&uid={c6586332-d416-495e-868d-e34430dab439}','TOLERANCE':1e-5,'BEHAVIOR':0,'OUTPUT':'memory:'})

```

---

- [test_project.qgz](https://issues.qgis.org/attachments/download/14412/test_project.qgz) (Antoine Lafranchis)
- [test_memory_usage.png](https://issues.qgis.org/attachments/download/14413/test_memory_usage.png) (Antoine Lafranchis)
- [QGIS.zip](https://issues.qgis.org/attachments/download/14425/QGIS.zip) (Antoine Lafranchis)
- [test_snap_config.png](https://issues.qgis.org/attachments/download/14426/test_snap_config.png) (Antoine Lafranchis)
- [qgis_version.png](https://issues.qgis.org/attachments/download/14427/qgis_version.png) (Antoine Lafranchis)
- [qgis_snap_exception.png](https://issues.qgis.org/attachments/download/14428/qgis_snap_exception.png) (Antoine Lafranchis)

**Comment by gioman** [comment]
> [test_snap_config.png](https://issues.qgis.org/attachments/download/14426/test_snap_config.png) (Antoine Lafranchis)

On the latest master, using such (unnecessary?) small tolerance, it (still) leaks memory eating up all of it and causing a system freeze.

**Comment by gacarrillor** [comment]
This was solved by https://github.com/qgis/QGIS/pull/44766

Pleas reopen if necessary.
