### ISSUE TITLE
vertex editor showing incorrect data

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27260]
Author Name: **Gavin Fleming** (@gubuntu)
Original Redmine Issue: [19432](https://issues.qgis.org/issues/19432)
Affected QGIS version: 3.2
Redmine category:editing

---
I opened the vertex editor on a PostGIS LinestringZM layer which has populated M values and 0 Z values. 

It shows an 'r' field with no values instead of a populated 'm' field. Screenshot attached. 

---

- [Screen Shot 2018-07-17 at 12.56.50.png](https://issues.qgis.org/attachments/download/12972/Screen%20Shot%202018-07-17%20at%2012.56.50.png) (Gavin Fleming)

**Comment by Pedro-Murteira** [comment]
@gubuntu I can't replicate this issue, could you attach a data sample so I can test this with more detail?

**Comment by gubuntu** [comment]
It's probably been fixed in recent versions, please close.
