### ISSUE TITLE
GDAL rasterize - add support for "burn in" to existing rasters, 'add' parameter

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27298]
Author Name: **Rijk Zuurmond** (Rijk Zuurmond)
Original Redmine Issue: [19470](https://issues.qgis.org/issues/19470)

Redmine category:processing/gdal
Assignee: Giovanni Manghi

---
missing -add function in GDAL_rasterize

---

- [after-gdal-rasterize.jpg](https://issues.qgis.org/attachments/download/13012/after-gdal-rasterize.jpg) (Rijk Zuurmond)
- [polylines.jpg](https://issues.qgis.org/attachments/download/13013/polylines.jpg) (Rijk Zuurmond)
- [qgis2.18_menu_GDAL-rasterize.jpg](https://issues.qgis.org/attachments/download/13014/qgis2.18_menu_GDAL-rasterize.jpg) (Rijk Zuurmond)

**Comment by mbernasocchi** [comment]
@alexbruy is there a reason why this alg is still uncommented in the list of processing algorithms?

**Comment by gioman** [comment]
see: https://github.com/qgis/QGIS/pull/32081

**Comment by alexbruy** [comment]
Already fixed.
