### ISSUE TITLE
On save layer and close qgis

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27303]
Author Name: **Andrew Shanin** (Andrew Shanin)
Original Redmine Issue: [19475](https://issues.qgis.org/issues/19475)
Affected QGIS version: 3.2
Redmine category:unknown

---
## Report Details

*Crash ID*: ddf13c961b4087a151929505eae6dc2704baedab

*Stack Trace*
```
GDALRasterBand::TryGetLockedBlockRef :
GDALAllRegister :
GDALAllRegister :
GDALAllRegister :
GDALRasterBand::GetLockedBlockRef :
GDALRasterBand::IRasterIO :
GDALAllRegister :
GDALRasterBand::RasterIO :
GDALRasterBand::IRasterIO :
GDALAllRegister :
GDALRasterBand::RasterIO :
GDALWarpOperation::operator= :
GDALWarpOperation::operator= :
QgsMultiBandColorRenderer::block :
QgsBrightnessContrastFilter::block :
QgsHueSaturationFilter::block :
QgsRasterResampleFilter::block :
QgsRasterProjector::block :
QgsRasterIterator::readNextRasterPart :
QgsRasterDrawer::draw :
QgsRasterLayerRenderer::render :
QgsMapRendererParallelJob::renderLayerStatic :
QgsArchive::zip :
QgsImageOperation::overlayColor :
QgsImageOperation::flipImage :
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

```

*QGIS Info*
QGIS Version: 3.2.0-Bonn
QGIS code revision: bc43194061
Compiled against Qt: 5.9.2
Running against Qt: 5.9.2
Compiled against GDAL: 2.2.4
Running against GDAL: 2.2.4

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by alexbruy** [comment]
Please retest with master.

**Comment by gioman** [comment]
Closing for the lack of feedback.
