### ISSUE TITLE
Rotate point symbols when "custom expression" is active

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27325]
Author Name: **Corentin CHARLOT** (@Corentin)
Original Redmine Issue: [19497](https://issues.qgis.org/issues/19497)

Redmine category:digitising

---
Hello,

When an expression is defined as a reference for the rotation angle in style properties, the "Rotate Point Symbols" tool does not work.
Only a numeric field allows its use.

My angle field must be in grad, anti-trigonometric, 0 in the East (compliance with specifications), so I need an expression to convert these values to display it right QGIS.

Another solution would be to be able to change the type of value of the angles in the project:
- degree, grad, radian
- arithmetic or geographic system
- 0 to North or 0 to East

Thank you.

---

- [expression.png](https://issues.qgis.org/attachments/download/13024/expression.png) (Corentin CHARLOT)

**Comment by alexbruy** [comment]
Closing as wontfix.
