### ISSUE TITLE
Cannot save a layer definition file

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27329]
Author Name: **Patrick Dunford** (@enzedrailmaps)
Original Redmine Issue: [19501](https://issues.qgis.org/issues/19501)
Affected QGIS version: 3.3(master)
Redmine category:map_legend

---
When you right click a layer group in the layers list the option to save as layer definition file is missing from the shortcut menu.

If you also go to the layer menu and you can find in that menu, the option to save as a layer definition file is greyed out, although you can add from a layer definition file.

This seems to be a changed behaviour from 2.18 when you want to save a group of layers into a layer definition file and I'm not sure why I can't do it like that anymore.

**Comment by alexbruy** [comment]
Fixed in master.
