### ISSUE TITLE
Compilation on Ubuntu 16.04 fail: No module named 'PyQT5.pyqtconfig'

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27334]
Author Name: **nicolas zzzz** (nicolas zzzz)
Original Redmine Issue: [19506](https://issues.qgis.org/issues/19506)
Affected QGIS version: 3.2.1
Redmine category:build/install

---
On Ubuntu 16.04, with PyQt5 version is 5.11.2 installed, I encountered this error while compiling QGIS 3.2 from sources:

```
 Traceback (most recent call last):
   File "/opt/QGIS/cmake/FindPyQt5.py", line 34, in <module
     import PyQt5.pyqtconfig
 ImportError: No module named 'PyQt5.pyqtconfig'@

 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/opt/QGIS/cmake/FindPyQt5.py", line 37, in <module
     import PyQt5.QtCore
 ImportError: /usr/local/lib/python3.5/dist-packages/PyQt5/QtCore.so: undefined symbol: PySlice_AdjustIndices
 
 Found SIP version: 4.17
 Traceback (most recent call last):
   File "/opt/QGIS/cmake/FindQsci.py", line 45, in <module
     from PyQt5.Qsci import QSCINTILLA_VERSION_STR
 ImportError: /usr/local/lib/python3.5/dist-packages/PyQt5/QtCore.so: undefined symbol: PySlice_AdjustIndices

```

The 'pyqtconfig' module is required by the file 'FindPyQt5.py' for example:
```
cd /opt/QGIS/build3_2/
cat ../cmake/FindPyQt5.py | grep -in pyqtconfig
    34:    import PyQt5.pyqtconfig
    35:    pyqtcfg = PyQt5.pyqtconfig.Configuration()

```

When trying to import this same module directly in a python3 console, it fails as well.

This module doesn't seem to exist anymore in PyQt5: http://pyqt.sourceforge.net/Docs/PyQt5/pyqt4_differences.html

**Comment by alexbruy** [comment]
Please check with master.

**Comment by alexbruy** [comment]
Closed for the lack of feedback.
