### ISSUE TITLE
Add buttons [Stop] / [Only LineStrings] / [Only polygons] / {All} to dialog Select vector Layers to Add...

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27346]
Author Name: **Andrew Shanin** (Andrew Shanin)
Original Redmine Issue: [19519](https://issues.qgis.org/issues/19519)

Redmine category:projection_support

---
When open many layers need to stop ask that you want and tell to program it's ok -load all.

---

- [1.PNG](https://issues.qgis.org/attachments/download/13260/1.PNG) (Andrew Shanin)
- [2.PNG](https://issues.qgis.org/attachments/download/13261/2.PNG) (Andrew Shanin)
- [3.PNG](https://issues.qgis.org/attachments/download/13262/3.PNG) (Andrew Shanin)

**Comment by alexbruy** [comment]
Closing, as there is an option to set default CRS or skip CRS selection. Please reopen if necessary.
