### ISSUE TITLE
Building QGIS3 against qt-5.11.x

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27349]
Author Name: **Chris Clayton** (@chris2553)
Original Redmine Issue: [19522](https://issues.qgis.org/issues/19522)
Affected QGIS version: 3.2
Redmine category:build/install

---
In qt-5.11 there has been some tweaking of header files, which result in FTBFS when building qgis-3.2.1 (and maybe earlier qgis3 versions).

Whilst I wouldn't suggest that you simply apply the attached patch, it does show the results of the work I did to identify that places where changes are needed. That will provide a start to the "proper" solution for qgis.

---

- [qgis-3.2.0-qt-5.11.patch](https://issues.qgis.org/attachments/download/13042/qgis-3.2.0-qt-5.11.patch) (Chris Clayton)

**Comment by nyalldawson** [comment]
Not an issue anymore
