### ISSUE TITLE
button Set Italic or bold text for font is not usable for label on layer properties

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27357]
Author Name: **Jérôme Seigneuret** (Jérôme Seigneuret)
Original Redmine Issue: [19530](https://issues.qgis.org/issues/19530)
Affected QGIS version: 3.2.1
Redmine category:labelling

---
There is no possibility to set Bold or Italic text without style selection.

buttons are desactivated

This possibility is offered (and work) in composer for on text object using HTML option <i>{text}</i> and <b>{text}</b>

**Comment by nyalldawson** [comment]
This is not a bug, it's by design. Use the available font styles drop down box to set bold or italic for fonts with bold/italic variants available.
