### ISSUE TITLE
Installation Script Failure

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27378]
Author Name: **Sven Wehke** (Sven Wehke)
Original Redmine Issue: [19551](https://issues.qgis.org/issues/19551)
Affected QGIS version: 3.2.1
Redmine category:build/install

---
I received the following message after trying to install Qgis 3.2.1 from the OSGeo4W Repository

Package: qgis
	qgis.bat exit code 255
Package: Unknown package
	qgis-common.bat exit code 255
	qgis-grass-plugin7.bat exit code 255

Can anybody help?

Thanks
Sven

---

Related issue(s): #27374 (duplicates)
Redmine related issue(s): [19547](https://issues.qgis.org/issues/19547)

---

**Comment by roya0045** [comment]
Still a thing?

**Comment by alexbruy** [comment]
Instalation works fine using standalone/OSGeo4W for 3.10/3.12. Closing.
