### ISSUE TITLE
QGIS 3 slow on macOS at high resolutions

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27373]
Author Name: **Michal Jurewicz** (Michal Jurewicz)
Original Redmine Issue: [19546](https://issues.qgis.org/issues/19546)
Affected QGIS version: 3.4.2
Redmine category:mac_os_specific

---
I use QGIS installed via MacPorts. Since QGIS 3.0.0 I noticed that it's very slow and unresponsive. Additionaly all modal windows can't be resized. However in the same time official binaries works fast but has some other problems (huge and misaligned mouse cursor and some others).

Today I made some tests with QGIS 3.2.1 and I confirmed that culprint is QT5.10. When I compiled QGIS with QT5.9 it works fast but has the same problem like official binaries. When recompile it with QT 5.10 it is very slow, size of modal windows are not adjustable but some other UI glithces are fixed. 

I don't know if it is more about bugs in QT or QGIS but right now there is no option to have good user experince with QGIS 3 on MacOS.

**Comment by PeterPetrik** [comment]
we use QT 5.14.2 now and I do not experience any slow rendering on retina display. Can someone please test with QGIS 3.16 and see if this is still the issue?

**Comment by gioman** [comment]
> we use QT 5.14.2 now and I do not experience any slow rendering on retina display. Can someone please test with QGIS 3.16 and see if this is still the issue?

@PeterPetrik i have no retina or high res display I can use to test (I just have 1080p displays).
