### ISSUE TITLE
QGIS freezes when adding multiple WFS layers from a geoserver instance

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27384]
Author Name: **Jonas Grieb** (Jonas Grieb)
Original Redmine Issue: [19557](https://issues.qgis.org/issues/19557)
Affected QGIS version: 3.5(master)
Redmine category:web_services_clients/wfs

---
Hello,

I have a geoserver running on localhost. In QGIS, establishing the connection via the "Create new WFS connection" panel works, but when I then try to add a WFS layer to QGIS I observed a strange behavior. Sometimes after the first or second wfs layer added to QGIS, QGIS freezes completely and I have to restart it. Sometimes I can add more layers but at some point it will freeze again. Also object loading of large layers is very slow.

All these problems did not occur in QGIS 2.18.

Can anyone reproduce this or has similar problems with the WFS provider in QGIS 3?

---

Related issue(s): #29062 (duplicates)
Redmine related issue(s): [21244](https://issues.qgis.org/issues/21244)

---

**Comment by gioman** [comment]
Tried with a couple of remote geoserver services and do not seems to happen anymore, please reopen if necessary.
