### ISSUE TITLE
QWebPage: No such file or directory

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27402]
Author Name: **nicolas zzzz** (nicolas zzzz)
Original Redmine Issue: [19575](https://issues.qgis.org/issues/19575)
Affected QGIS version: 3.3(master)
Redmine category:build/install

---
I encountered this error during QGIS compilation on Ubuntu Xenial (4.15.0-29-generic x86_64 GNU/Linux):

```
In file included from /opt/QGIS/src/core/annotations/qgshtmlannotation.cpp:26:0:
/opt/QGIS/src/core/qgswebpage.h:26:20: fatal error: QWebPage: No such file or directory
compilation terminated.

```

**Comment by alexbruy** [comment]
Still true with master?

**Comment by alexbruy** [comment]
Closed for the lack of feedback. Please reopen if necessary.
