### ISSUE TITLE
geometry checker duplicate nodes bad results

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27403]
Author Name: **zimirrr leonid** (zimirrr leonid)
Original Redmine Issue: [19576](https://issues.qgis.org/issues/19576)
Affected QGIS version: 3.2.1
Redmine category:c++_plugins/geometry_checker

---
latest qgis 3.2.1, windows 7.

I run geometry checker for duplicate nodes with tolerance 1e-6 and it founds a lot of duplicates but when I check them there is only one node, no duplicated ones. 
If I change tolerance the number of errors changes. With 1e-10 no errors was found.

It shows duplicates for polygons and linestrings. Can somebody check it?

---

- [test_.gpkg](https://issues.qgis.org/attachments/download/13122/test_.gpkg) (zimirrr leonid)

**Comment by Pedro-Murteira** [comment]
I can still reproduce this behavior on QGIS 3.16.14 and 3.22.1.

**Comment by lbartoletti** [comment]
It works as excepted for me (except a difference point of view for the tolerance (absolute vs sqrDistance))

I tried with QGIS 3.24. 

Here the WKT of FID=7:
```
<QgsGeometry: Polygon ((87.94079499999999427 26.34483399999999875, 87.94190799999999797 26.34438499999999905, 87.94219099999999401 26.34424999999999883, 87.94239399999999307 26.34407500000000013, 87.94251800000000685 26.34397200000000083, 87.94270899999999358 26.34374499999999841, 87.9427649999999943 26.34360200000000063, 87.94285399999999697 26.34343700000000155, 87.94285200000000202 26.34322299999999828, 87.94280399999999531 26.34283399999999986, 87.94261699999999848 26.3421599999999998, 87.94259099999999307 26.34174099999999896, 87.94250499999999704 26.34156700000000129, 87.94239100000000064 26.34179900000000174, 87.94219200000000569 26.34202799999999911, 87.94225500000000295 26.34231600000000029, 87.94222299999999848 26.34267399999999881, 87.94204499999999314 26.34307499999999891, 87.94190999999999292 26.34321900000000127, 87.94164999999999566 26.34339399999999998, 87.94114899999999579 26.34388900000000078, 87.94097600000000625 26.34423900000000174, 87.94079499999999427 26.34483399999999875))>
```

First, since it's double, there is a rounding error at the 6 positions.

What is the WKT representation with a precision at the 6th digit?

```
'Polygon ((87.940795 26.344834, 87.941908 26.344385, 87.942191 26.34425, 87.942394 26.344075, 87.942518 26.343972, 87.942709 26.343745, 87.942765 26.343602, 87.942854 26.343437, 87.942852 26.343223, 87.942804 26.342834, 87.942617 26.34216, 87.942591 26.341741, 87.942505 26.341567, 87.942391 26.341799, 87.942192 26.342028, 87.942255 26.342316, 87.942223 26.342674, 87.942045 26.343075, 87.94191 26.343219, 87.94165 26.343394, 87.941149 26.343889, 87.940976 26.344239, 87.940795 26.344834))'
```
There is no duplicate node - except first and last points. 

Geometry checker is ok: no duplicated nodes has been found.

What about 1e-3?
 ```
'Polygon ((87.941 26.345, 87.942 26.344, 87.942 26.344, 87.942 26.344, 87.943 26.344, 87.943 26.344, 87.943 26.344, 87.943 26.343, 87.943 26.343, 87.943 26.343, 87.943 26.342, 87.943 26.342, 87.943 26.342, 87.942 26.342, 87.942 26.342, 87.942 26.342, 87.942 26.343, 87.942 26.343, 87.942 26.343, 87.942 26.343, 87.941 26.344, 87.941 26.344, 87.941 26.345))'
 ```
There is a lot of duplicated nodes, but your geometry will be modified:

![image](https://user-images.githubusercontent.com/7521540/169768441-408666b2-f287-4494-917a-752911054799.png)

**Comment by lindacamathias** [comment]
I guess sth goes wrong with the tolerance setting in the Check Geometries Plugin..
Here's what i observed (same in QGIS 3.22.8 and QGIS 33.26.0)

i have a polygon layer (gpkg) in which geometry precision in the properties is set to 0.001 m
when i perform a "validity check" with method either "the one selected in digitizing settings" or "QGIS"  there are 6 duplicate nodes errors. 
![image](https://user-images.githubusercontent.com/77726342/177180339-d9526749-b03f-4b43-bd5d-d5208142c5ac.png)

in the Geometry Checker when i set tolerance to 1e-3 and check for topology nodes i get 24 errors. i checked a few of the indicated errors and they're not identical at 1e-3 level.  
when i set tolerance to 1e-7 in the Geometry Checker there are 6 errors (same as "validity check" result) 
![image](https://user-images.githubusercontent.com/77726342/177179709-f8a3ab46-92a9-41ce-a75e-e31e72c69f53.png)


( further i would expect that the shown coordinate in the Geometry check result should be shown with the tolerance set for the check (it's always just one decimal) - but that may be another issue)
