### ISSUE TITLE
Single-letter shortcut doesn't work when attribute dialog is open

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27412]
Author Name: **Andreas Oxenstierna** (@AndreasOx)
Original Redmine Issue: [19585](https://issues.qgis.org/issues/19585)
Affected QGIS version: 3.2.1
Redmine category:gui

---
E.g. P for Pan is activated only if the attribute table dialog is not in focus.
All other tested shortcuts are working, eg. F11, Cmd-S
Tested on macOS 10.13.6 with QGIS 3.2.1 but seems to be the same on Windows with earlier versions.

**Comment by Pedro-Murteira** [comment]
I can still replicate this issue on QGIS 3.16.14 of qgis, but couldn't on QGIS 3.22.1. (Tested on Windows 10)
