### ISSUE TITLE
Oracle vector features not printed to pdf via standalone pyQGIS script using exporter exportToPdf

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27439]
Author Name: **C M** (C M)
Original Redmine Issue: [19612](https://issues.qgis.org/issues/19612)
Affected QGIS version: 3.2.1
Redmine category:data_provider/oracle

---
Oracle 2-dimensional line features are not being printed to pdf via exporter/exportToPdf when layout is printed via a standalone pyQGIS script.
The same features print correctly when exporting to pdf via the layout GUI.

Oracle version:
Oracle Database 11g Enterprise Edition Release 11.2.0.3.0 - 64bit Production
SDO geometry (G_TYPE 2002) features are valid, have a spatial index, primary key, etc.

**Comment by alexbruy** [comment]
Is it possible that your script does not wait for layer to be loading/rendered?
