### ISSUE TITLE
Better support for vector features crossing the internation date line with some projections

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27453]
Author Name: **克鲁 黄** (克鲁 黄)
Original Redmine Issue: [19626](https://issues.qgis.org/issues/19626)
Affected QGIS version: 3.2.1
Redmine category:map_canvas

---
When I use Natural Earth as data source and want to change projection for the project to customized Robinson, the map breaks apart (see attached file). 
I use a projection as follows: 
Proj4: +proj=robin +lon_0=150dE +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs
Hope if it's not a bug. But if it is, I'd like to know if there's a workaround. 

---

- [_未命名的项目 - QGIS 2018-08-15 15.02.14.png](https://issues.qgis.org/attachments/download/13142/_%E6%9C%AA%E5%91%BD%E5%90%8D%E7%9A%84%E9%A1%B9%E7%9B%AE%20-%20QGIS%202018-08-15%2015.02.14.png) (克鲁 黄)

---

Related issue(s): #27571 (relates)
Redmine related issue(s): [19746](https://issues.qgis.org/issues/19746)

---

**Comment by Pedro-Murteira** [comment]
Can still reproduce on QGIS 3.16.14 and 3.22.1.

**Comment by alexbruy** [comment]
Duplicates #25398.
