### ISSUE TITLE
[Expression] Allow storage of custom functions in the project they are used

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27512]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [19687](https://issues.qgis.org/issues/19687)

Redmine category:expressions

---
The "docs states":https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/expression.html#function-editor that custom functions created through the Function Editor dialog are stored in the python/expressions folder and you should remind to share them with project, otherwise it may be broken.
Could be nice to have them stored in the project when they are used (we now have models stored in project, don't we?)

**Comment by alexbruy** [comment]
Duplicates #20793.
