### ISSUE TITLE
huge (giant) font size in Extension description window

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27522]
Author Name: **Ervin Peters** (Ervin Peters)
Original Redmine Issue: [19697](https://issues.qgis.org/issues/19697)
Affected QGIS version: 3.2.2
Redmine category:gui

---
since qgis3 on gentoo i encountert a huge font size in extension description window.

I searched a place to configure something like a base size or a resolution, but unfortunately found nothing.

Is there a config option or is the font size hardcoded an therefore is a bug?

Got a 1920x1200 px display with 102dpi, xwindows and gnome knowing about it.

see screeshot attached

QGIS-Version 3.2.2-Bonn
QGIS-Codezweig Release 3.2
Kompiliert gegen Qt 5.11.1
Laufendes Qt 5.11.1
Kompiliert mit GDAL/OGR 2.3.0
Läuft mit GDAL/OGR 2.3.0
Kompiliert mit GEOS 3.6.2-CAPI-1.10.2
Läuft mit GEOS 3.6.2-CAPI-1.10.2 4d2925d6
PostgreSQL-Client-Version 10.3
SpatiaLite-Version 4.3.0a
QWT-Version 6.1.3
QScintilla2-Version 2.10.4
PROJ.4-Version 492

---

- [Bildschirmfoto von »2018-08-25 18-22-24«.png](https://issues.qgis.org/attachments/download/13198/Bildschirmfoto%20von%20%C2%BB2018-08-25%2018-22-24%C2%AB.png) (Ervin Peters)

**Comment by alexbruy** [comment]
Probably you accidentaly increased font size by scrolling in the window with pressed `Ctrl` key

**Comment by alexbruy** [comment]
Closed for the lack of feedback.
