### ISSUE TITLE
QGIS hangs after PC locks screen after timeout

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27532]
Author Name: **Keith Ross-Jones** (Keith Ross-Jones)
Original Redmine Issue: [19707](https://issues.qgis.org/issues/19707)
Affected QGIS version: 3.4.3
Redmine category:build/install

---
QGIS Desktop on windows 10 64-bit on a laptop hangs and also causes some Windows functions to hang when the laptop locks after the inactivity timeout period.  The lockup happens after unlocking the screen.  Some functions of Windows also locks, such as trying to activate other applications.

I am heavily using GEOPackages for all my layers.

---

- [One QGIS suspended and one ok.jpg](https://issues.qgis.org/attachments/download/14038/One%20QGIS%20suspended%20and%20one%20ok.jpg) (Jesper Cairo Westergaard)

**Comment by sherwoods12** [comment]
I have a user with the same problem. After a lock screen, the program becomes suspended (unresponsive) and must be restarted. We tried different versions of QGIS and they all do the same thing.

A while back Giovanni Manghi wrote:

"I am running QGIS 3.4.3-Madeira
If QGIS is the foremost/active program, and I press Win L (lock) it will be suspended when I log in again (even if after just a few sexonds of the PC being locked).
But, if I have something else as the front app, then no problem. QGIS works fine, responds, does NOT get suspended."

If the user clicks on another app before his system locks, it does not suspend the program but, if QGIS is the active app when the system is locked, the app becomes unresponsive and shows as suspended.
We have this issue with  Windows 10 Pro on a laptop. The Windows 10 version is 1903.

**Comment by gioman** [comment]
> We tried different versions

exactly what versions?

**Comment by roya0045** [comment]
On win 10 I never had such an issue, could this be caused by something other than qgis?

**Comment by sherwoods12** [comment]
We tried QGIS versions 3.4.3, 3.4.14, 3.10.1, and 3.8.
They all do the same thing.

**Comment by sherwoods12** [comment]
We are using a work around, if the app is minimized before locking the screen, it does not suspend.

**Comment by anthony-cooper** [comment]
We're also experiencing the same issues - however struggingly to find reasoning - some machines seem predisposed to it - clean installs on identical machines result in 1 machine suspending, the other not!

**Comment by roya0045** [comment]
@anthony-cooper do all the machines have the same OS and specs or is there a pattern?

**Comment by anthony-cooper** [comment]
Same OS and spec - I didn't know it was happening until one user said about it, then discovered others had the same issue! Away from my office for the next week, but on return will investigate a bit more to try and find cause, as we have about 10 users on identical/very similar hardware/os, and 3 affected!

**Comment by roya0045** [comment]
@anthony-cooper and I assume that it occurs with any project open even an empty one?

**Comment by ottadini** [comment]
I am experiencing the same problem exactly, on Windows 10 Version 10.0.18362 Build 18362, with QGIS 3.14.1 "Pi", QGIS code revision | de08d6b71d, with or without a project open. If I lock my screen while QGIS has the focus, it becomes Suspended and I have to kill it. If it doesn't have the focus then it remains responsive and doesn't get suspended.

**Comment by Pedro-Murteira** [comment]
Can't reproduce this issue on QGIS 3.22.3. (Windows 10)
