### ISSUE TITLE
Symbology option: suppress shared polygon boundaries

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27540]
Author Name: **Nathan Perry** (Nathan Perry)
Original Redmine Issue: [19715](https://issues.qgis.org/issues/19715)

Redmine category:symbology

---
It would be tremendously useful if the Symbology panel had a built-in option to style polygon features as if they were dissolved; that is, rendering them as a single united polygon with no internal boundaries visible. Currently this is only possible using the collect() function in Geometry Generator, or as a workaround with multiple symbol layers and offset outlines, but is commonly used enough to warrant a core feature.

This could be implemented as a check box in the Symbol options for fill-type symbols, perhaps: "Suppress shared polygon boundaries"

**Comment by pjshelton** [comment]
This and #17943 and #21642 are all requesting a general Merge connected objects for symbology.
