### ISSUE TITLE
Save/load style to PostgreSQL database from Layer styling panel and from layer right-click menu

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27544]
Author Name: **Tomasz Rychlicki** (@miszokienka)
Original Redmine Issue: [19719](https://issues.qgis.org/issues/19719)

Redmine category:map_canvas

---
For now layer in layer styling panel user can only load style from qml file. It will be useful if he can load style also from PostgreSQL database.
The same is applicable to the style section under the layer righ-click menu in TOC.

**Comment by alexbruy** [comment]
Duplicates #27474
