### ISSUE TITLE
Legend to reflect map theme in layouts/ reports

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27542]
Author Name: **Verity Miles** (Verity Miles)
Original Redmine Issue: [19717](https://issues.qgis.org/issues/19717)

Redmine category:map_composer/printing

---
It would be great to have a map legend reflect a map theme in the same way that the map itself does in a print layout/ report.

I am trying to set up a report in QGIS 3.2 to export a whole series of maps. At the moment, I cannot alter the style of the legend (we have different styles for the one layer depending on the map requirements) without manually changing the style/ map theme in the map viewer window. This effectively means that I have to manually export the series of maps.

Thanks.

---

Related issue(s): #24694 (duplicates)
Redmine related issue(s): [16795](https://issues.qgis.org/issues/16795)

---

**Comment by mikedufty** [comment]
I think this is the same issue I'm having.  Saving a theme works for main map display and composer maps capturing the display on or off status for categories within a layer, but this is not reflected in the legend.  Can work around by duplicating the layer so the whole layer is turned on or off for different display options, but seems to be a bug that the theme works for display but not legends.
