### ISSUE TITLE
Python error at qgis startup after changing profile folder

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27556]
Author Name: **Andreas Mueller** (Andreas Mueller)
Original Redmine Issue: [19731](https://issues.qgis.org/issues/19731)
Affected QGIS version: 3.2.2
Redmine category:build/install
Assignee: Luigi Pirelli

---
I put my osgeo4w/qgis install onto a usb stick and use the nice new profile feature. Qgis is called with a fix profile via command line (--profiles-path) which points to a directory on the same usb sick. Unfortunately, there are absolute pathes stored in the QGIS3.ini file inside the profile, so if the drive letter changes, these pathes are invalid. This is the error  message i get.

```
FileNotFoundError: [WinError 3] Das System kann den angegebenen Pfad nicht finden: 'C:\\tmp\\gp180828\\Home\\.qis3\\profiles\\default\\processing\\scripts' 
Traceback (most recent call last):
  File "C:/tmp/gp180823/osgeo4w/apps/qgis/./python/plugins\processing\script\ScriptAlgorithmProvider.py", line 106, in loadAlgorithms
    items = [f for f in os.listdir(folder) if os.path.isfile(os.path.join(folder, f))]
FileNotFoundError: [WinError 3] Das System kann den angegebenen Pfad nicht finden: 'C:\\tmp\\gp180828\\Home\\.qis3\\profiles\\default\\processing\\scripts'


Python-Version: 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 07:18:10) [MSC v.1900 32 bit (Intel)] 
QGIS-Version: 3.2.2-Bonn Bonn, 26842169e9 

Python-Pfad:
C:/tmp/gp180823/osgeo4w/apps/qgis/./python
C:\tmp\gp180823\Home\.qis3\profiles\default/python
C:\tmp\gp180823\Home\.qis3\profiles\default/python/plugins
C:/tmp/gp180823/osgeo4w/apps/qgis/./python/plugins
C:\tmp\gp180823\osgeo4w\bin\python36.zip
C:\tmp\gp180823\osgeo4w\apps\Python36\DLLs
C:\tmp\gp180823\osgeo4w\apps\Python36\lib
C:\tmp\gp180823\osgeo4w\bin
C:\tmp\gp180823\osgeo4w\apps\Python36
C:\tmp\gp180823\osgeo4w\apps\Python36\lib\site-packages
C:\tmp\gp180823\Home\.qis3\profiles\default/python

```

As you can see, the error raises inside the list comprehension in ScriptAlgorithmProvider.py.

My suggestion is, to check if the pathes exist else fall back to default values, e.g. the pathes inside the active profile.
Because the values for these pathes are stored in ini files inside the profile folder, may be qgis could use relative pathes and expand them with the profile path?
There is also a global ini file (qgis_global_settings.ini) in apps/qgis/resources which may can provide default values? 

I think the problem is not only related to my "custom portable qgis", but with cases where people have profiles or qgis installs on network drives and more.

**Comment by luipir** [comment]
I'll try to contact original author of the issue... feedback is open since time, IMHO can be closed if he does not give a feedback in a week

**Comment by amr66** [comment]
Sorry for answering so late. Unfortunately I can't test your solution, because I can't build qgis from source. It looks promising, though. Thank you for your efforts, looking forward to see it in an upcoming release!

**Comment by roya0045** [comment]
Fixed?
