### ISSUE TITLE
Copy/paste a renderer class from the contextual menu does not work

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27559]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [19734](https://issues.qgis.org/issues/19734)
Affected QGIS version: 3.3(master)
Redmine category:symbology

---
Apply a categorized or a graduated symbology to a layer
Right-click on a class and select "copy"
Then right-click and select Paste. Nothing happens.
If you do select the class then press Ctr-C, Ctrl-V, a new class is added.
Copy/paste works well in a rule-based renderer case.

Would also affect 2.18

PS: It could be nice if the focus/selection was moved to the pasted item(s) instead of the original ones (as the user may want to customize them). This is how the rule-based renderer copy-paste works.

Discussed at http://osgeo-org.1560.x6.nabble.com/how-duplicate-the-rendering-of-a-value-td5376157.html

**Comment by DelazJ** [comment]
I notice that the not working buttons that were "Copy" and "Paste" in 3.8 are in master replaced with "Copy symbol" and "Paste symbol" and do what they promise. Was removing the "copy" and "paste" actions on purpose (they are still in the rule based renderer)?

**Comment by nyalldawson** [comment]
@delazj

Yes - I deliberately removed them since
1. They were connected to absolutely nothing (IE not broken code... Just... Nothing)
2. There seemed little purpose to them, given that categories and graduated classes must be unique. I can't see why you'd need to copy a whole class.
