### ISSUE TITLE
std::bad_alloc on otf reprojection

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27574]
Author Name: **Johannes Kroeger** (Johannes Kroeger)
Original Redmine Issue: [19749](https://issues.qgis.org/issues/19749)
Affected QGIS version: 3.7(master)
Redmine category:vectors

---
* Load ne_110m_graticules_30.shp or ne_110m_graticules_20.shp (or probably any other global vector dataset)
* Set OTF projection to *EPSG:3031*
* Right-click the layer and *Zoom to layer*

You get an exception "std::bad_alloc"

Afterwards the map canvas stops updating (uses its cache). On setting a different OTF projection, the canvas is blank white. This persists opening a new project and requires a restart of QGIS.

**Comment by alexbruy** [comment]
Still true with latest 3.10/master?

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
