### ISSUE TITLE
Processing: merge vector layers produces duplicated fid

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27583]
Author Name: **Jérôme Guélat** (Jérôme Guélat)
Original Redmine Issue: [19758](https://issues.qgis.org/issues/19758)
Affected QGIS version: 3.2.2
Redmine category:processing/core

---
Here's how to reproduce the bug:

1. Add the 3 layers from the attached GeoPackage (pol.gpkg)
2. Open the merge vector layers tool in Processing, choose the 3 layers and save to a temporary layer
3. The resulting layer has features with the same fid, and hence can't be saved to a new GeoPackage without manually editing the fid values
4. Alternatively if you save directly to GeoPackage (instead of using a temporary layer), the tool produces a wrong output

A similar bug happens with other tools (see #27533). This fid problem makes Processing almost unusable with GeoPackages.

---

- [pol.gpkg](https://issues.qgis.org/attachments/download/13236/pol.gpkg) (Jérôme Guélat)

---

Related issue(s): #27533 (relates), #27820 (relates)
Redmine related issue(s): [19708](https://issues.qgis.org/issues/19708), [19998](https://issues.qgis.org/issues/19998)

---

**Comment by alexbruy** [comment]
Should be fixed in master
