### ISSUE TITLE
Path length limit on file open dialog box

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27595]
Author Name: **Patrick Dunford** (@enzedrailmaps)
Original Redmine Issue: [19770](https://issues.qgis.org/issues/19770)
Affected QGIS version: 3.2.2
Redmine category:data_source_manager

---
When opening multiple raster layers
The last filename and a few that followed it were truncated
e.g.
"/mnt/share/mainpc/maps/Non-Rail/Christchurch/1lds/94CLL-92
which should have been
"/mnt/share/mainpc/maps/Non-Rail/Christchurch/1lds/94CLL-92XDP.jpg" and about another 60 files in a set of 540 rasters. Only the first 480 were imported.
This suggests to me there is a path length limit of about 32767 characters on this dialog box.

**Comment by alexbruy** [comment]
I'm afraid this is an upstream issue.
