### ISSUE TITLE
< WFSLayers > not cleaned in project file when layer is removed

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27608]
Author Name: **Marjorie FANGAIN** (@mfangain)
Original Redmine Issue: [19783](https://issues.qgis.org/issues/19783)
Affected QGIS version: 3.2.3
Redmine category:project_loading/saving

---
The information < WFSLayers > still remains in the qgs file after layer deletion, like <layer_coordinate_transform_info> (see Bug report #22691)

**Comment by alexbruy** [comment]
Can not reproduce with master. I added WFS layer, saved project and don't see any of these tags in the XML.

**Comment by alexbruy** [comment]
Closed for the lack of feedback
