### ISSUE TITLE
macOS: QGIS 3.2.2 canvas do not scale when resizing program window

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27603]
Author Name: **Nahum Castro** (Nahum Castro)
Original Redmine Issue: [19778](https://issues.qgis.org/issues/19778)
Affected QGIS version: 3.2.2
Redmine category:osx_ui

---
The map do not scale with window when resizing

---

- [Captura de pantalla 2018-09-05 a la(s) 20.11.21.png](https://issues.qgis.org/attachments/download/13248/Captura%20de%20pantalla%202018-09-05%20a%20la(s)%2020.11.21.png) (Nahum Castro)
- [Schermata_QGIS323.jpg](https://issues.qgis.org/attachments/download/13466/Schermata_QGIS323.jpg) (amedeo fadini)

---

Related issue(s): #27351 (relates), #27607 (duplicates)
Redmine related issue(s): [19524](https://issues.qgis.org/issues/19524), [19782](https://issues.qgis.org/issues/19782)

---

**Comment by gioman** [comment]
Does not seems to be the case anymore on QGIS 3.14.0 on macOS Catalina, please reopen if necessary.
