### ISSUE TITLE
3d map in layout shows blank screen

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27616]
Author Name: **Gerhard Spieles** (Gerhard Spieles)
Original Redmine Issue: [19791](https://issues.qgis.org/issues/19791)
Affected QGIS version: 3.3(master)
Redmine category:3d

---
Steps:
1. add a 3dmap in a layout,
2. set the scensettings to the 3dmap
3. in the 3d map the message "Load" appears for a long time
4. the "Load" meesage disappears and
5. a blank screen is shown in the added 3dmap and nothing happens
6. Taskmaanager shows, that qgis needs round 40% of CPU capacity

Screenshots are attached.
Actualize the 3dmap leads mostly to a crash.

---

- [3dmap.jpg](https://issues.qgis.org/attachments/download/13258/3dmap.jpg) (Gerhard Spieles)
- [3dlayout.jpg](https://issues.qgis.org/attachments/download/13259/3dlayout.jpg) (Gerhard Spieles)

**Comment by PTod89** [comment]
Hallo! Have you fixed your problem?

**Comment by sdnxgr** [comment]
Still experiencing this issue in 3.16.1-Hannover.

**Comment by alexbruy** [comment]
Works fine with the latest QGIS 3.33 (2ae70eb)
