### ISSUE TITLE
Panning/move on QGIS using WASD/keyboard buttons

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27646]
Author Name: **Tom na** (Tom na)
Original Redmine Issue: [19822](https://issues.qgis.org/issues/19822)

Redmine category:map_canvas

---
Can we pan using WASD/other keyboard buttons, like in Google Earth?
W - Up
A - Left
S - Down
D - Right

This would allow users to split polygons with right hand and move around the QGIS map rather than have to cross arms to use arrow keys on QWERT keyboard.
I know there is a configure shortcuts options via Settings, Configure Shortcuts, but I don't think this gives me the option to set arrow keys?

WASD (,AOE on Dvorak keyboards; ZQSD on AZERTY keyboards) is a set of four keys on a QWERTY or QWERTZ computer keyboard which mimics the inverted-T configuration of the arrow keys. 
(https://en.wikipedia.org/wiki/Arrow_keys#ESDF_keys)

**Comment by Marty** [comment]
I just thought the same thing, this would be very nice. Just make it configurable.

**Comment by alexbruy** [comment]
Duplicates #21496.
