### ISSUE TITLE
QgsProcessingParameterMultipleLayers widget does not keep layer order

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27659]
Author Name: **Olivier Dalang** (@olivierdalang)
Original Redmine Issue: [19835](https://issues.qgis.org/issues/19835)
Affected QGIS version: 3.3(master)
Redmine category:processing/gui

---
Hi !

The QgsProcessingParameterMultipleLayers does not keep layer ordering when it is reopened.

This is very annoying for algorithms that are sensitive to the layer ordering and is very error prone as the difference is quite subtle. 

*Steps to reproduce*

- Open "merge vector" algorithm (or any other having a multiple layers input)
- Add at least two layers as the multiple layer input
- Change the order of the layer
- Validate (at this point, the reorderd list of layers is set as parameter)
- Reopen the multiple layer input widget
- The layer order is reset to initial state

**Comment by nyalldawson** [comment]
Fixed in 3.14
