### ISSUE TITLE
Convex hull by Field, not anymore?

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27673]
Author Name: **Cristian Páez** (Cristian Páez)
Original Redmine Issue: [19849](https://issues.qgis.org/issues/19849)

Redmine category:unknown

---
Friends. I was looking for the "by Field" option in the convex hull (QGIS 3.x), but I can not find it. Is it me and my clumsiness or do we no longer have it?

**Comment by alexbruy** [comment]
Closed for the lack of feedback and because this functionality seems available in the Minimum bounding geometry tool. Please reopen if necessary.
