### ISSUE TITLE
Data source Manager Inconsistency between the browser and left column

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27688]
Author Name: **Esbern Holmes** (@Esbern)
Original Redmine Issue: [19864](https://issues.qgis.org/issues/19864)

Redmine category:gui

---
There is a strange inconsistency between what is available in the left column /vertical tab and what is available in the brows area. Most noteworthy is that “Virtual Layer” and “Delimited Text” are available in the vertical tab area and not in the brows while “XYZ Tiles” and “OWS” are available in the brows area but not in the vertical tab.

---

- [DataSourceManager.png](https://issues.qgis.org/attachments/download/13300/DataSourceManager.png) (Esbern Holmes)

**Comment by alexbruy** [comment]
XYZ and Vector tiles now available both in browser and datasource manager. Virtual layers and CSV files does not make any sense in browser as they are project-specific entries.
