### ISSUE TITLE
Add Polygon feature: double (left click) to end the creation 

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27707]
Author Name: **Tommy Hutcheson** (@tommyhutcheson)
Original Redmine Issue: [19883](https://issues.qgis.org/issues/19883)

Redmine category:editing

---
Hi

I always seem to forget to end my polygon creation by right clicking, it just makes sense to be a double left click. I would love to not have to sit there wondering why I keep getting an error trying to do one of the most basic GIS tasks.

Thank you

Tommy

**Comment by nyalldawson** [comment]
This is by design - right click is the standard way to end digitising in qgis, and it's unlikely to be changed now
