### ISSUE TITLE
Coordinate Capture does not use datum transformation

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27712]
Author Name: **Bernhard Ströbl** (Bernhard Ströbl)
Original Redmine Issue: [19888](https://issues.qgis.org/issues/19888)
Affected QGIS version: 3.3(master)
Redmine category:c++_plugins

---
if a datum transformation is defined (with a transformation grid file) to transform from the map CRS to the coordinate capture's CRS, this transformation is not applied, nor is the user asked if or which transformation should be applied.

**Comment by nyalldawson** [comment]
No longer an issue with the merged "copy coordinates" approach
