### ISSUE TITLE
Enable Snapping in Coordinate Capture

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27713]
Author Name: **Bernhard Ströbl** (Bernhard Ströbl)
Original Redmine Issue: [19889](https://issues.qgis.org/issues/19889)

Redmine category:c++_plugins

---
Would be nice if we could snap when capturing coordinates

**Comment by nyalldawson** [comment]
The "coordinate capture" plugin is no longer present in QGIS 3.14

**Comment by nilsnolde** [comment]
Is there a native alternative instead?
