### ISSUE TITLE
print / display PostGIS Raster in QGIS map composer

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27711]
Author Name: **Holger Naumann** (Holger Naumann)
Original Redmine Issue: [19887](https://issues.qgis.org/issues/19887)
Affected QGIS version: 3.2.2
Redmine category:map_composer/printing

---
No raster are shown in map composer, if the source of the raster is a postgis database. Printing to tiff in the composer shows also just the vector data of the project. Exporting to tiff inside the map window of QGIS works.

I use the dtk100 Maps from https://www.lvermgeo.sachsen-anhalt.de/de/dtk100-grau.html
I put is into a database (PostgreSQL 10.3 with Postgis  2.4.4)

raster2pgsql -s 4647 -N 0 -I -C -M *.tif -F -t auto -l 5,10,50,100,200  dtk100.dtk100sw > dtk100sw.sql

---

- [qgis_layout.png](https://issues.qgis.org/attachments/download/13319/qgis_layout.png) (Holger Naumann)
- [qgis_kartenfenster.png](https://issues.qgis.org/attachments/download/13320/qgis_kartenfenster.png) (Holger Naumann)
- [qgis_version.png](https://issues.qgis.org/attachments/download/13321/qgis_version.png) (Holger Naumann)
- [qgis_db_verwaltung.png](https://issues.qgis.org/attachments/download/13322/qgis_db_verwaltung.png) (Holger Naumann)
- [qgis_db_verwaltung2.png](https://issues.qgis.org/attachments/download/13323/qgis_db_verwaltung2.png) (Holger Naumann)

**Comment by borysiasty** [comment]
Is it still valid? Can't confirm with QGIS 3.10

**Comment by alexbruy** [comment]
Closing for the lack of feedback. Please reopen if necessary.
