### ISSUE TITLE
VIGRA library missing in SAGA libs in QGIS3.2 on Mac OS X 10.12 (Sierra)

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27722]
Author Name: **Garth Fletcher** (@fgfletcher)
Original Redmine Issue: [19898](https://issues.qgis.org/issues/19898)
Affected QGIS version: 3.2.2
Redmine category:build/install

---
The SAGA libs in /Applications/QGIS3_3_2_2-1.app/Contents/MacOS/lib/saga/ do not include VIGRA support, e.g., libimagery_vigra.dylib
Consequently SAGA > Image analysis > Edge detection (vigra) fails with "Error: select a library" message.
I suspect the same is true of the other SAGA > Image analysis > xxx (vigra) tools such as Fourier filter (vigra), Fourier transform (vigra), etc.

Is a compatible (SAGA 2.3.1) version of libimagery_vigra.dylib available which can be installed?

**Comment by alexbruy** [comment]
Closing, as this is a SAGA packaging issue.
