### ISSUE TITLE
Relation reference widget : data is limited to the first 100 items, make it configurable in the widget options

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27727]
Author Name: **jd lom** (@lejedi76)
Original Redmine Issue: [19903](https://issues.qgis.org/issues/19903)

Redmine category:edit_widget

---
The combobox of relation reference widget displays the first 100 items.
However the autocompletion is working great.

The attached video shows the behavior on version 3.2.2 and 2.18.11.

---

- [2018-09-20_15-46-58.mp4](https://issues.qgis.org/attachments/download/13332/2018-09-20_15-46-58.mp4) (jd lom)

**Comment by alexbruy** [comment]
Fixed by #52246
