### ISSUE TITLE
Marker opacity not working on Marker Lines

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27734]
Author Name: **Alexandre Neto** (@SrNetoChan)
Original Redmine Issue: [19910](https://issues.qgis.org/issues/19910)
Affected QGIS version: 3.3(master)
Redmine category:symbology

---
When using a marker line, changing the marker's opacity has no consequences on the final symbol. In fact, if you set it to 50% and move to another setting, if you go back, it will be set to 100% again.

Color opacity works as expected.

!marker_opacity_error.gif!

---

- [marker_opacity_error.gif](https://issues.qgis.org/attachments/download/13339/marker_opacity_error.gif) (Alexandre Neto)

**Comment by SrNetoChan** [comment]
Still an issue on 3.9.

 One image = thousand words

![Peek 2019-09-27 14-03](https://user-images.githubusercontent.com/3607161/65771269-ba7d5800-e12f-11e9-82a2-6eeaa5a953cf.gif)

**Comment by jonnyforestGIS** [comment]
Tested in QGIS 3.10.1 and still persists.

**Comment by alexbruy** [comment]
Duplicates #18022
