### ISSUE TITLE
[symbology] Missing color ramp types in symbol selector dialog

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27741]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [19917](https://issues.qgis.org/issues/19917)
Affected QGIS version: 3.3(master)
Redmine category:symbology

---
Vector layer styling panel --> symbology --> categorized
Press the color ramp drop-down menu
In the All color Ramps submenu, you have ALL the color ramps created in the style manager, regardless their type
If you press the Create new color ramp button, you are prompted to select among 5 color ramp types

Now apply a gradient fill style to a symbol
Press the color ramp drop-down menu
In the All color Ramps submenu, you have *only the color ramps of the gradient or catalog:cpt-city types are displayed*
If you press the Create new color ramp button, you are prompted to select among these 2 color ramp types
The sameapplies to the Favorites color ramps shown in the widget, only gradient or cpt-cityones would be listed in the symbol selector dialog
Looks like the other types are not exposed to user and people cannot customize their symbols with them.

I do not have 2.18 to check whether it's a regression.

---

- [missing_colorramps.png](https://issues.qgis.org/attachments/download/13344/missing_colorramps.png) (Harrissou Santanna)
- [full_colorramps.png](https://issues.qgis.org/attachments/download/13345/full_colorramps.png) (Harrissou Santanna)

**Comment by alexbruy** [comment]
Can be closed?

**Comment by DelazJ** [comment]
> Can be closed?

yes, please. Thanks.
