### ISSUE TITLE
DB Manager looses target while importing more than one SHP into PostgreSQL

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27751]
Author Name: **Jörn Henrich** (Jörn Henrich)
Original Redmine Issue: [19927](https://issues.qgis.org/issues/19927)
Affected QGIS version: 3.2.3
Redmine category:db_manager

---
Hi,

I often need to import several SHP-files into my PostgreSQL DB. 
In QGIS v2.18.4 the DB Manager kept the focus on the schema I've chosen for the first file. 
In newer versions of QGIS (I tried 2.18.12, 3.0.3 and 3.2.3) I must sellect the schema again after each import.

*Way to reproduce:*
- open more than one shape file in a QGIS version >= 2.18.12 
- open the DB Manager and select the schema you want to import the SHPs into
- import the first SHP
- now you'll recognise that the selection of the schema jumps back to the superior database the previously selected schema is located in
- now you must reselect the schema you want to import the SHPs into *this is the step which was'nt necessary in QGIS v 2.18.4 and earlyer*

Greetings,
Joern

**Comment by gioman** [comment]
Still true.

**Comment by gioman** [comment]
I would say that probably is a "won't fix": DB Manager is slated to be replaced by the data source manager and there are several other ways to import data in PostGIS.
