### ISSUE TITLE
libreoffice calc integration

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27764]
Author Name: **luis marcelo dambrowski dambrowski** (luis marcelo dambrowski dambrowski)
Original Redmine Issue: [19942](https://issues.qgis.org/issues/19942)

Redmine category:forms

---
I need to insert tables made in libreoffice calc, direct in the print layout, was using the html option but n solves very well.
integration between the two programs?

---

- [Sem título.png](https://issues.qgis.org/attachments/download/13354/Sem%20t%C3%ADtulo.png) (luis marcelo dambrowski dambrowski)

**Comment by alexbruy** [comment]
Probably can be closed.
