### ISSUE TITLE
Window Position not save on Exit

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27777]
Author Name: **Sven Gruner** (Sven Gruner)
Original Redmine Issue: [19955](https://issues.qgis.org/issues/19955)
Affected QGIS version: 3.2.1
Redmine category:gui

---
Starting QGIS does not restore the original Window Size.

---

- [qgis-start.jpg](https://issues.qgis.org/attachments/download/13364/qgis-start.jpg) (Sven Gruner)

**Comment by alexbruy** [comment]
Works for me. Please test with latest master.

**Comment by alexbruy** [comment]
Closed for the lack of feedback
