### ISSUE TITLE
Cyrillic symbols in QGIS Server

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27788]
Author Name: **Alexander Novikov** (@novikov-alexander)
Original Redmine Issue: [19966](https://issues.qgis.org/issues/19966)
Affected QGIS version: 3.2.3
Redmine category:qgis_server

---
I have a project with Cyrillic attributes and label values. It works perfect in QGIS Desktop.
But it seems not working in QGIS Server. There are empty squares instead letters in labels. Rule-based labeling also doesn't work.
I've already tried what I could. I've changed system encoding, I've changed encoding in Apache config. Nothing helps me.

---

- [bad.PNG](https://issues.qgis.org/attachments/download/13375/bad.PNG) (Alexander Novikov)

**Comment by jgrocha** [comment]
Related to #29244 and #30270
