### ISSUE TITLE
Obsolete VC redist version installed

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27808]
Author Name: **Yogurt Yogurt** (Yogurt Yogurt)
Original Redmine Issue: [19986](https://issues.qgis.org/issues/19986)
Affected QGIS version: 3.3(master)
Redmine category:build/install

---
Qgis keeps on installing VC redistributable version 9.0.30729.17, regardless whether a newer version of VC++ 2008 (9.0) is already installed on the machine, like 9.0.30729.6161.

To do:
1. Update vc_redist in the installer packed to the latest one.
2. Make the installer check if a newer version is already installed.
3. Is Qgis still really built on VC2008, in 2018??? (Yeah, that's a separate issue.)

**Comment by roya0045** [comment]
Still true?

**Comment by alexbruy** [comment]
Probably should be closed.

**Comment by gioman** [comment]
Closing for lack of feedback.
