### ISSUE TITLE
Zoom from mac mousepad does not work

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27819]
Author Name: **ross bernet** (ross bernet)
Original Redmine Issue: [19997](https://issues.qgis.org/issues/19997)
Affected QGIS version: 3.2.3
Redmine category:gui

---
Zooming in does not really work from the trackpad. I have a macbook air. 

This seems like a fundamental feature that users will use with basically everything that they do.

I am guessing this issue is logged elsewhere, but there wasn't an easy way to search for it.

QGIS3 is absolutely amazing. And I am close to thinking I can ditch arcmap and never look back... but doesnt feel quite there yet. 

Glitchy zooms is part of it.

THANKS

**Comment by kannes** [comment]
Was marked fixed in other issue, can be closed.
