### ISSUE TITLE
Coordinate Capture plugin geographic coordinate issue

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27822]
Author Name: **Charles Clancy** (Charles Clancy)
Original Redmine Issue: [20000](https://issues.qgis.org/issues/20000)
Affected QGIS version: 3.2.2
Redmine category:c++_plugins

---
I've observed a couple of issues with the Coordinate Capture plugin:
1) The geographic decimal degree readout needs to be more precise - at least 7 places
2)My project CRS is Camacupa / UTM zone 33S. When I invoke the plugin the geographic CRS is set to WGS84, and the datum shift that is associated with the project CRS is used to convert from projected coordinates. I proved this using an external geodetic calculator. I have to manually set the plugin geographic CRS to Camacupa to obtain an unambiguous result.

**Comment by alexbruy** [comment]
Ca we close this as another two tickets were opened?
