### ISSUE TITLE
Print Layout missing Page Properties 

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27843]
Author Name: **Lene Fischer** (@LeneFischer)
Original Redmine Issue: [20021](https://issues.qgis.org/issues/20021)

Redmine category:map_composer/printing

---
Trying to change page properties in a layout there are no entries from a menu, tab or icon. Only solution is a right click. This is a main action in creating a layout and it has no 'normal' entry.

**Comment by roya0045** [comment]
Wat?

**Comment by gioman** [comment]
> Wat?

@roya0045 that is correct: until 2.18 (I think) in the composer there was a dedicated tab for the page properties (visible by default). Now the page properties show in the "item properties" tab, but only if you right click the page and select "page properties".

**Comment by roya0045** [comment]
I just don't get what feature is being requested here.

**Comment by gioman** [comment]
> I just don't get what feature is being requested here.

to reinstate the old behavior, the new one is baffling for many users.

**Comment by andreasneumann** [comment]
Well, the reason why this behavior was changed, was, that starting from QGIS 3.0, every single page in a layout can have a different size and orientation.

So the old way of setting the page size globally doesn't work anymore.

If we want to re-enable the old behaviour, we would have to enhance the dialogue with a new functionality that allows to select one, several, all or no page and allows to set properties for selected pages only. It is not so easy to do.

I am sure that @nyalldawson has some feedback here or an idea how to solve it?

**Comment by alexbruy** [comment]
Seems same as #26237
