### ISSUE TITLE
Server and desktop too slow with Postgis views

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27840]
Author Name: **Jesus Rodriguez Marcial** (Jesus Rodriguez Marcial)
Original Redmine Issue: [20018](https://issues.qgis.org/issues/20018)
Affected QGIS version: 3.4.5
Redmine category:data_provider/postgis

---
If a layer is defined with a view or with sql, qgis issues a select distinct count of the id, I guess that it does that to assert that the Id is unique. If I have a huge table, it takes some 60 seconds to execute (and naively enough, multiply it if several layers are based on the same exact view) It causes timeouts in qgis server, and makes the map unusable. There should be a way to tell Qgis that I'm pretty sure that the PK is valid. Adding insult to injury, I don't even want to edit the data.

**Comment by ojgenbar** [comment]
Hi, all! I'm Evgeniy Baryshkov

This trick works, but don't you think that this option should be accessible in PostGIS layer menu? And also can be defined for layers separately (not for all at once).

**Comment by haubourg** [comment]
@ojgenbar well, this option is supposed to also work with other dataproviders concerned by not having enough metadata, including some file providers, so adding the option in all connexion dialogs would not be that easy. Moreover, we started with a simple implementation, having the following server use case in mind:
If the view is big enough to be slow to describe (get metadata), then it has a lot of feature. It is very unlikely that the extent will move so much on the fly when digitizing new features. Anyway, that will not prevent users from creating features, but the "zoom to layer extent" information will just no be updated. Anyhow, it is possible to manually update layer extent; Either from layer properties in desktop use case or with a qgis server plugin for web client use cases.  
Let us know if we missed a use case for you, the trust option is only now gaining some popularity and needs some love for sure :)
