### ISSUE TITLE
Polygon not visible when selected if opacity is set to 0%

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27859]
Author Name: **Patrick Dunford** (@enzedrailmaps)
Original Redmine Issue: [20037](https://issues.qgis.org/issues/20037)
Affected QGIS version: 3.2.3
Redmine category:map_canvas

---
If a polygon layer exists and the style of that layer is set to a Fill pattern and the fill's opacity is set to 0% then a polygon will not be visible in the selection colour when it has been selected.

**Comment by alexbruy** [comment]
If I understand description correctly, works fine in 3.10/master. Please re-test.
