### ISSUE TITLE
GPKG and SQLite files containing raster layers are incorrectly added to the map

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27872]
Author Name: **Andrea Giudiceandrea** (@agiudiceandrea)
Original Redmine Issue: [20050](https://issues.qgis.org/issues/20050)
Affected QGIS version: 3.4.5
Redmine category:data_provider

---
*1)* When *a geopackage file contains only 1 raster layer* and you drag and drop the GPKG file into the map or you use the "Data Source Manager / Raster" dialog window to add the layer to the map, then:

the layer is automatically added (without the "Select Raster Layers to Add..." dialog window appearing) only like
```
filepath\filename.gpkg

```
instead of
```
GPKG:filepath/filename.gpkg:raster_layer_name

```

See Issue #27853 and PR https://github.com/qgis/QGIS/pull/8127 about the a similar issue fixed for vector layers import.

Moreover, the raster layer name is set to "filename" instead of a proper name like "raster_layer_name" or "filename raster_layer_name" (as for vector layers).

*2)* When *a geopackage file contains more then 1 raster layer* and you drag and drop the GPKG file into the map or you use the "Data Source Manager / Raster" dialog window to add the layer to the map, then:

the "Select Raster Layers to Add..." dialog window appears showing only values in the "Layers ID" column but *with the "Layer name" column blank*
![image](https://agiudiceandrea.github.io/QGIS330_6.PNG)
The selected raster layer(s) are then added with a correct source like
```
GPKG:filepath/filename.gpkg:raster_layer_name

```

but *with a blank name* instead of a proper name like "raster_layer_name" or "filename raster_layer_name" (as for vector layers).

*3)* When *a geopackage file contains both raster layer(s) and vector layer(s)* and you drag and drop the GPKG file in the map, then only raster layer(s) will be added to the map: if there is only 1 raster layer you'll fall back again in the above first case, if there are more then 1 layer you'll fall back again in the above second case.

Using the "Data Source Manager" dialog window, with the "Vector" tab you can add the contained vector layer(s) without problems, but trying to add the raster layer(s) with the "Raster" tab you will fall back again in the above first or second cases.

*4)* Using instead the *Browser panel*, raster layers in a geopackage GPKG file are always correctly added to the map with a source like:
```
GPKG:filepath/filename.gpkg:raster_layer_name

```
and with the name of "raster_layer_name".

*EDIT*:

These strange and incorrect behaviours also happen for *SQlite files containing rasterlite raster layers*.

*1), 2), 3*) are almost the same as the above ones, except that the source string for rasterlite rasters it's like
```
RASTERLITE:filepath/filename.sqlite,table=rasterlite_layer_name

```

*4)* With the Browser panel is not possible to add to the map the rasterlite rasters contained in a sqlite file, but only the related metadata tables.

---

- [1rlayer.gpkg](https://issues.qgis.org/attachments/download/13444/1rlayer.gpkg) (Andrea Giudiceandrea)
- [1vlayer+1rlayer.gpkg](https://issues.qgis.org/attachments/download/13445/1vlayer+1rlayer.gpkg) (Andrea Giudiceandrea)
- [1vlayer+2rlayer.gpkg](https://issues.qgis.org/attachments/download/13446/1vlayer+2rlayer.gpkg) (Andrea Giudiceandrea)
- [2rlayer.gpkg](https://issues.qgis.org/attachments/download/13447/2rlayer.gpkg) (Andrea Giudiceandrea)

**Comment by gioman** [comment]
@agiudiceandrea do you mind re-evaluate this? I just gave it a quick try on the latest master and  loading the layers from the browser seems ok to me. While with d&d seems there are still some issues when the gpkg contains both rasters and vectors.

**Comment by agiudiceandrea** [comment]
Hi @gioman, i can confirm almost all the incorrect behaviors with QGIS 3.16.3 on Windows.

- Dragging and dropping the layers or using the Data Source Manager / Raster:
1) still occurs for both gpkg and sqlite/rasterlite
2) still occurs for sqlite/rasterlite - no longer occurs with gpkg
3) still occurs with both gpkg and sqlite/rasterlite

- Using the Browser panel:
4) still occurs for sqlite/rasterlite


So, only the behavior 2) results now fixed only for gpkg.

Attached the corresponding sqlite/rasterlite files in compressed zip file:
1rlayer.sqlite
1vlayer+1rlayer.sqlite
1vlayer+2rlayer.sqlite
2rlayer.sqlite
[sqlite-rasterlite-layers.zip](https://github.com/qgis/QGIS/files/5903504/sqlite-rasterlite-layers.zip)

**Comment by agiudiceandrea** [comment]
Would it be better that I splitted this multiple bugs report into single ones?

**Comment by gioman** [comment]
> Would it be better if I splitted this multiple bugs report into single ones?

@agiudiceandrea yes thanks, is always preferred to have 1 issue per ticket.

**Comment by agiudiceandrea** [comment]
Splitted in various bug reports: https://github.com/qgis/QGIS/issues/41558, https://github.com/qgis/QGIS/issues/41560.

**Comment by gioman** [comment]
> Splitted in various bug reports: #41558, #41560.

@agiudiceandrea we need to keep this open too?

**Comment by agiudiceandrea** [comment]
No. Please close it.
