### ISSUE TITLE
Implement tool to load INSPIRE GML datasets

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27888]
Author Name: **Noel Suárez González** (Noel Suárez González)
Original Redmine Issue: [20066](https://issues.qgis.org/issues/20066)

Redmine category:vectors

---
some GML files can not be loaded correctly in QGIS 3.2.3 in macOS

---

- [Captura de pantalla 2018-10-10 a las 11.09.11.png](https://issues.qgis.org/attachments/download/13455/Captura%20de%20pantalla%202018-10-10%20a%20las%2011.09.11.png) (Noel Suárez González)
- [Captura de pantalla 2018-10-10 a las 11.10.35.png](https://issues.qgis.org/attachments/download/13456/Captura%20de%20pantalla%202018-10-10%20a%20las%2011.10.35.png) (Noel Suárez González)
- [Captura de pantalla 2018-10-10 a las 11.29.14.png](https://issues.qgis.org/attachments/download/13457/Captura%20de%20pantalla%202018-10-10%20a%20las%2011.29.14.png) (Noel Suárez González)
- [Captura de pantalla 2018-10-10 a las 11.30.27.png](https://issues.qgis.org/attachments/download/13458/Captura%20de%20pantalla%202018-10-10%20a%20las%2011.30.27.png) (Noel Suárez González)
- [GML_Parcelas.gml](https://issues.qgis.org/attachments/download/13461/GML_Parcelas.gml) (Noel Suárez González)
- [A.ES.SDGC.CP.33013.cadastralzoning.gml](https://issues.qgis.org/attachments/download/13462/A.ES.SDGC.CP.33013.cadastralzoning.gml) (Noel Suárez González)
- [VirtualBox_windows_7_10_10_2018_12_24_44.png](https://issues.qgis.org/attachments/download/13463/VirtualBox_windows_7_10_10_2018_12_24_44.png) (Giovanni Manghi)
- [A.ES.SDGC.CP.33013.cadastralzoning.gpkg](https://issues.qgis.org/attachments/download/13481/A.ES.SDGC.CP.33013.cadastralzoning.gpkg) (Saber Razmjooei)

**Comment by alexbruy** [comment]
See also https://github.com/qgis/QGIS/issues/27076
