### ISSUE TITLE
Field validation is not done automatically

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27894]
Author Name: **Etienne Trimaille** (@Gustry)
Original Redmine Issue: [20072](https://issues.qgis.org/issues/20072)
Affected QGIS version: 3.3(master)
Redmine category:forms

---
On my GIF,
* I set the "schema" combobox to "biocenose marine".
* My "table" combobox is updated according to the drill down expression : we can see the orange cross with the defautl value "chauvaud 1995 simplifie"
* I change the value in the "table" combobox to something else
* I change back the "table" combobox to "chauvaud 1995 simplifie", the orange cross is gone, the form is now valid.

I shouldn't change temporary the value in my "table" combobox to make it valid.

Affected 3.2 and master 3.3

---

- [expression_evaluation_trigger.gif](https://issues.qgis.org/attachments/download/13472/expression_evaluation_trigger.gif) (Etienne Trimaille)

**Comment by gioman** [comment]
@Gustry this seems fixed to me, can you confirm?
