### ISSUE TITLE
Eliminate multiple dialog levels in Layer Properties

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27905]
Author Name: **Patrick Dunford** (@enzedrailmaps)
Original Redmine Issue: [20083](https://issues.qgis.org/issues/20083)

Redmine category:gui

---
Currently in the layer properties it is divided into a number of areas. Most of the areas in this dialog are well designed without the need to bring up another dialog box to make changes to settings.

However in the Symbology section there can be rules or other entries that need a separate dialog to edit them.
This functionality should as far as practicable be integrated into the Properties dialog. 
Having the second layer of dialog increases the workload to view and change settings with extra clicks required especially when changing several rules or styles at a time and attempting to compare them.

---

- [Screenshot_2018-10-12_14-53-07.png](https://issues.qgis.org/attachments/download/13482/Screenshot_2018-10-12_14-53-07.png) (Patrick Dunford)

**Comment by alexbruy** [comment]
Can we close this?

**Comment by gioman** [comment]
Closing for lack of feedback.
