### ISSUE TITLE
Saving Memory Layer to a file misses Scaling part of the CRS

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27902]
Author Name: **Keith Johnson** (Keith Johnson)
Original Redmine Issue: [20080](https://issues.qgis.org/issues/20080)
Affected QGIS version: 3.2.3
Redmine category:projection_support

---
I created a custom CRS based on a state plane, and added a +k_0 parameter to make ground references in an image measure correctly.

I reprojected a layer of existing vectors into this new CRS in a temporary/memory layer.  The features projected correctly onto the map.

However, when I used "Layer/Save As..." to save to a file, the saved layer "jumped" to a new location (tested with both geopackage and shapefiles, same behavior).  
The CRS listed in the Source Tab for the layer properties is NOT my named custom projection, but a USER:100.... that does not include a +k_0 parameter.

When I select my custom projection to change the CRS, the feature jumps back to its proper location.

So apparently, when saving a layer to a file, not all of the PROJ4 parameters are being included in the CRS of the saved file. This may affect more parameters than just scaling, but I have not tested any others.

Keith

---

Related issue(s): #27901 (relates)
Redmine related issue(s): [20079](https://issues.qgis.org/issues/20079)

---

**Comment by nyalldawson** [comment]
Should be fixed in the newest versions -- please open a new ticket with a project attached if you still see this issue in 3.10.1
