### ISSUE TITLE
Split Tool "Bursts" linestring when used on complex linestring

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27904]
Author Name: **Simon Dellis** (@sjdellis)
Original Redmine Issue: [20082](https://issues.qgis.org/issues/20082)
Affected QGIS version: 3.4.1
Redmine category:digitising

---
When using the Split tool on a complex linestring (lots of nodes) the linestring "bursts" into many segments. Attached is a sample shapefile that causes the issue and the result after using the split to once.

Simple line strings are not a problem.

Reproduced the problem on versions from 2.18.13 to 3.2.3 on Windows 10 Pro and Enterprise. The same file in Arc splits as expected.

Using the "Split with Lines" tool generates similar problems.

---

- [test.zip](https://issues.qgis.org/attachments/download/13479/test.zip) (Simon Dellis)
- [test-split.zip](https://issues.qgis.org/attachments/download/13480/test-split.zip) (Simon Dellis)

**Comment by lbell** [comment]
Also: 3.8.1
Possible duplicate: https://github.com/qgis/QGIS/issues/14070
