### ISSUE TITLE
Axis order issue for urn:ogc:def:crs:EPSG::4326

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27909]
Author Name: **Robin Houtmeyers** (@robinhoutmeyers)
Original Redmine Issue: [20087](https://issues.qgis.org/issues/20087)
Affected QGIS version: 3.3(master)
Redmine category:web_services_clients/wcs

---
While using the WCS 1.0.0 connection capabilities in QGIS, we noticed that QGIS by default uses lon/lat axis order for CRS urn:ogc:def:crs:EPSG::4326.
This should actually be lat/lon, see also https://epsg.io/4326. Although the axis order can be inverted in the UI, I would expect that the default is the standardized axis order.

**Comment by Pedro-Murteira** [comment]
@robinhoutmeyers Hello, is this still valid on recent releases?

**Comment by robinhoutmeyers** [comment]
@Pedro-Murteira I tested this with the latest release 3.24.2 and this indeed appears to be fixed! Thanks!
