### ISSUE TITLE
"Embed Layers and Groups" only allows to embed from qgs files, not  qgz

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27910]
Author Name: **magerlin -** (magerlin -)
Original Redmine Issue: [20088](https://issues.qgis.org/issues/20088)
Affected QGIS version: 3.6.0
Redmine category:data_provider

---
More details here: http://osgeo-org.1560.x6.nabble.com/QGIS-Developer-QGIS-3-does-not-allow-to-embed-layers-from-qgz-project-files-td5377590.html

---

Related issue(s): #28398 (relates)
Redmine related issue(s): [20578](https://issues.qgis.org/issues/20578)

---

**Comment by Aus-Jono** [comment]
Also in 3.8.1

**Comment by alexbruy** [comment]
Duplicates #28280
