### ISSUE TITLE
GeoPackage SQL issues in DB Manager

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27914]
Author Name: **Antoine Fonoxo** (Antoine Fonoxo)
Original Redmine Issue: [20092](https://issues.qgis.org/issues/20092)
Affected QGIS version: 3.5(master)
Redmine category:db_manager

---
DB Manager issues with GPKG geometries on perfectly valid GeoPackage files (made by QGIS or ogr2ogr).
The following SQL queries fail in DB Manager
( but succeed in DB Browser 4 SQLite with EnableGpkgAmphibiousMode ) :

SELECT AsWKT(geom) FROM mypolygon;
--> returns NULL ; should return: MULTIPOLYGON(...

SELECT ST_Area(geom) FROM mypolygon;
--> returns NULL ; should return numeric

SELECT isvalid(geom) FROM mypolygon;
--> returns -1 (which means: UNKNOWN) ; should return 0 or 1

**Comment by roya0045** [comment]
@alexbruy GPKG doesn't even have geometric functions. this is not a QGIS issue, people are assuming that GPKG have functions that are not even implemented. I'm sure that area and lenght functions don't exist, it is possible that the other listed functions are not in the standard and thus return NULL.

**Comment by gioman** [comment]
> @alexbruy GPKG doesn't even have geometric functions. this is not a QGIS issue, people are assuming that GPKG have functions that are not even implemented. I'm sure that area and lenght functions don't exist, it is possible that the other listed functions are not in the standard and thus return NULL.

@roya0045 if this is the case then this "handled" very poorly. If in PostGIS I use in SQL a function that does not exist, the query returns an error, not a result with NULLs where the non-existing function supposedly was used.

Moreover the DB manager SQL console has auto-completion enabled for spatial operators when writing a query on a GPKG datasource. This of course makes people *assume* they can use them.

**Comment by gioman** [comment]
> @alexbruy GPKG doesn't even have geometric functions

moreover if this is true I also argue that instead of trying make this format the default one in QGIS we should have choose a different one, Spatialite.

**Comment by rouault** [comment]
This might be just an integration issue in the context of QGIS/ DBManager. The OGR GPKG driver enables Spatialite on GeoPackage databases

```
$ ogrinfo poly.gpkg -sql "SELECT ST_Area(geom) FROM poly"
INFO: Open of `poly.gpkg'
      using driver `GPKG' successful.

Layer name: SELECT
Geometry: None
Feature Count: 10
Layer SRS WKT:
(unknown)
ST_Area(geom): Real (0.0)
OGRFeature(SELECT):0
  ST_Area(geom) (Real) = 215229.265625

OGRFeature(SELECT):1
  ST_Area(geom) (Real) = 247328.171875

OGRFeature(SELECT):2
  ST_Area(geom) (Real) = 261752.78125

OGRFeature(SELECT):3
  ST_Area(geom) (Real) = 547597.2109375

OGRFeature(SELECT):4
  ST_Area(geom) (Real) = 15775.7578125

OGRFeature(SELECT):5
  ST_Area(geom) (Real) = 101429.9765625

OGRFeature(SELECT):6
  ST_Area(geom) (Real) = 268597.625

OGRFeature(SELECT):7
  ST_Area(geom) (Real) = 1634833.390625

OGRFeature(SELECT):8
  ST_Area(geom) (Real) = 596610.3359375

OGRFeature(SELECT):9
  ST_Area(geom) (Real) = 5268.8125
```

The OGR GPKG driver uses "SELECT EnableGpkgAmphibiousMode()" on spatialite >= 4.3

**Comment by roya0045** [comment]
@rouault Oh nice I wasn't aware of the OGR extension/driver. Is there a way to enable this by default in qgis? 

I wasn't aware of that but the lack of geospatial function is what turned me away from making triggers on gpkg.

**Comment by roya0045** [comment]
@gioman for reference https://gdal.org/drivers/vector/gpkg.html#sql-functions

**Comment by rouault** [comment]
>  Is there a way to enable this by default in qgis?

The OGR/GPKG driver is the way that QGIS accesses GeoPackage. But there might be something specific in DBManager. I presume it uses the sqlite3 interface directly and not OGR API, thus EnableGpkgAmphibiousMode() is probably not called.

> for reference https://gdal.org/drivers/vector/gpkg.html#sql-functions

The above lists functions are a super minimal set, that uses to be required by the GeoPackage specification, but are not that useful. The full set accessible is normally the whole Spatialite functions at http://www.gaia-gis.it/gaia-sins/spatialite-sql-4.3.0.html

**Comment by roya0045** [comment]
> > for reference https://gdal.org/drivers/vector/gpkg.html#sql-functions
> 
> The above lists functions are a super minimal set, that uses to be required by the GeoPackage specification, but are not that useful. The full set accessible is normally the whole Spatialite functions at http://www.gaia-gis.it/gaia-sins/spatialite-sql-4.3.0.html

Oh I simply wanted to show the basic/default functions of geopackage to Giovanni, I did not want to show the functions added by OGR but only those that existed and were provided by the OGC.

**Comment by roya0045** [comment]
@rouault in the DB manager the [spatialite connection method seem to be used](https://github.com/qgis/QGIS/blob/24e56a810cba9d531776af133c4f60158d9a4429/python/plugins/db_manager/db_plugins/gpkg/connector.py#L81) but I'm not sure if it enables the proper driver (I'm honestly not sure how or when to enable the driver in the code).

**Comment by alexbruy** [comment]
In fact it uses both native GDAL `ExecuteSQL` and `spatialite_connect`

**Comment by elpaso** [comment]
In master, I've recently added initial support for `QgsAbstractDatabaseProviderConnection` 
https://github.com/qgis/QGIS/blob/master/python/plugins/db_manager/db_plugins/gpkg/connector.py#L67 which uses GDAL/OGR.

See: https://qgis.org/api/classQgsAbstractDatabaseProviderConnection.html

**Comment by roya0045** [comment]
@rouault reading the spatialite docs (https://www.gaia-gis.it/stored-procs-win-test/spatialite-sql-latest.html) it mentions that the amphibious mode must always be activated as it is disabled by default ( like the geopackage mode). This mean that for each connection a call to enable the amphibious mode would be preferred (even mandatory?) before even querying the table?
