### ISSUE TITLE
QGIS save project not working properly

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27930]
Author Name: **Mario Reyes** (@ernesto561)
Original Redmine Issue: [20108](https://issues.qgis.org/issues/20108)
Affected QGIS version: 3.4.0
Redmine category:project_loading/saving

---
Steps to reproduce the error:

-Load a 3.2.3 .qgz file in QGIS Master (ae397bf24a) installed via OSGEO4W
-Save the project using the save button.  The * next to the project file name still appears.  
-Save the project in .qgs format following #26365 workaround, but the * still appears, and if the project is closed QGIS asks if I want to save the changes.

Checking the project file in the directory, it seems the changes are saved, because the time of modification corresponds to when the save button was clicked.

**Comment by alexbruy** [comment]
Fixed in master. Please reopen if necessary.
