### ISSUE TITLE
Bug with Drag and Drop Designer on QGIS 3.2

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27932]
Author Name: **didier peeters** (@dd-a)
Original Redmine Issue: [20110](https://issues.qgis.org/issues/20110)
Affected QGIS version: 3.4.2
Redmine category:forms

---
Hello,

The Drag and Drop Designer to create forms on QGIS 3.2.3 (Unbuntu Xenial) does not accept to drop items from the 'Available widgets' to the 'Form Layout'.  Sometimes it even leads to a complete freeze
This issue seems to have appeared with QGis 3.2 .

Qt version used is 5.5 (same for compilation).  

See the joined screencast.

---

- [Capture_glisser-deposer.mp4](https://issues.qgis.org/attachments/download/13500/Capture_glisser-deposer.mp4) (didier peeters)

**Comment by haubourg** [comment]
@dd-a is it still an issue in current release and ltr?

**Comment by dd-a** [comment]
Solved !
Tested with : QGIS 3.4.6 on Unbuntu 1904 and QGIS 3.4.9 on Ubuntu Mint 19
