### ISSUE TITLE
Inconsistent placement of Cancel button in Load Style window

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27943]
Author Name: **Saber Razmjooei** (@saberraz)
Original Redmine Issue: [20121](https://issues.qgis.org/issues/20121)
Affected QGIS version: 3.3(master)
Redmine category:gui

---
When loading style, the new window has two options: Cancel and Load Style
Almost everywhere in QGIS, Cancel is the most right option. For consistency, best to place Cancel to the left here too.

---

- [load_style.png](https://issues.qgis.org/attachments/download/13509/load_style.png) (Saber Razmjooei)

**Comment by alexbruy** [comment]
Seems already fixed in master.
