### ISSUE TITLE
[Processing]Last used format is not proposed by default in file selector dialog when running in batch

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27949]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [20128](https://issues.qgis.org/issues/20128)

Redmine category:processing/gui

---
Open an algorithm dialog
switch to batch mode
click the browser icon for input layer
in the select file dialog, browse to a folder and use the drop-down menu of the formats (let's say esri shapefile) to filter layer. Select any and add. 
(You may also run the alg at this step) 
Click on another row in the batch dialog to add another file; in the file selector, it would be nice to have the previously selected format (esri shapefile) instead of having to scroll down to again select the proper format. 
People will likely use the same format than the default one and this will, if i'm not wrong, align it with other file selector widgets.

**Comment by alexbruy** [comment]
Duplicates #21084.
