### ISSUE TITLE
Import to MS SQL failed due to international characters

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27945]
Author Name: **Martin Dobias** (@wonder-sk)
Original Redmine Issue: [20123](https://issues.qgis.org/issues/20123)
Affected QGIS version: 3.3(master)
Redmine category:data_provider/mssql

---
When I load the attached layer to QGIS (dbf encoding is UTF-8), I am unable to import the data to MS SQL through the browser dock. It says the export failed with this output:

```
Failed to import some layers!

Feature write errors:
Creation error for features from #0 to #0. Provider errors was: 
[FreeTDS][SQL Server]Incorrect syntax near ','. [FreeTDS][SQL Server]Error converting characters into server's character set. Some character(s) could not be converted QODBC3: Unable to execute statement
Creation error for features from #0 to #0. Provider errors was: 
[FreeTDS][SQL Server]Incorrect syntax near ','. [FreeTDS][SQL Server]Error converting characters into server's character set. Some character(s) could not be converted QODBC3: Unable to execute statement
Only 0 of 8 features written.

```

---

- [mssql-fail-kraje.zip](https://issues.qgis.org/attachments/download/13511/mssql-fail-kraje.zip) (Martin Dobias)

**Comment by Pedro-Murteira** [comment]
@wonder-sk Hello, is this still true on more recent releases?
