### ISSUE TITLE
[Processing] Esri shapefile format is listed twice in file selector dialog when running in batch

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27948]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [20127](https://issues.qgis.org/issues/20127)
Affected QGIS version: 3.3(master)
Redmine category:gui

---
Open an algorithm dialog
switch to batch mode
click the browser icon for input layer
in the select file dialog, the drop-down of the formats shows two consecutive "Esri shapefile" format. 

---

Related issue(s): #28661 (relates)
Redmine related issue(s): [20842](https://issues.qgis.org/issues/20842)

---

**Comment by alexbruy** [comment]
Duplicates #28661
