### ISSUE TITLE
Remembering the last folder when loading style

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27942]
Author Name: **Saber Razmjooei** (@saberraz)
Original Redmine Issue: [20120](https://issues.qgis.org/issues/20120)
Affected QGIS version: 3.3(master)
Redmine category:gui

---
I have all my qml files in a folder and when trying to apply style from file in the new window, it will always point to my home folder.
Like the rest of QGIS, could you set that to the last used folder (same as previous behaviour).

**Comment by alexbruy** [comment]
Seems already fixed in master.
