### ISSUE TITLE
Development version QGIS-server crashes on Win10

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27956]
Author Name: **Koen Volleberg** (Koen Volleberg)
Original Redmine Issue: [20135](https://issues.qgis.org/issues/20135)
Affected QGIS version: 3.3(master)
Redmine category:qgis_server

---
Hi all,
I wanted to do a test-drive of the 3.3 development version of QGIS-server on my Win10 laptop.
The 3.2 release runs smoothly on the same machine (Apache 2.4 x64, mod_fcgid etc). 

I installed 3.3 through OSGeo4W64 (QGIS-version 3.3.0-97, including necessary dependencies) after completely removing older versions of QGIS.
With same setting (except of pathname-changes), I sent a WMS-request, but stumbled upon a 500-error in Firefox.

This is my conf-setting in Apache (2.4 x64 with mod_fcgid, compiled with VC15):

@FcgidInitialEnv PATH "C:\OSGeo4W64\bin;C:\OSGeo4W64\apps\qgis-dev\bin;C:\OSGeo4W64\apps\Qt5\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem"
FcgidInitialEnv QGIS_AUTH_DB_DIR_PATH "C:\OSGeo4W64\apps\qgis-dev\resources"
FcgidInitialEnv PYTHONHOME "C:\OSGeo4W64\apps\Python37"
FcgidInitialEnv QGIS_PREFIX_PATH "C:\OSGeo4W64\apps\qgis-dev" 
FcgidInitialEnv QT_PLUGIN_PATH "C:\OSGeo4W64\apps\qgis-dev\qtplugins;C:\OSGeo4W64\apps\qt5\plugins"

<Directory "c:/OSGeo4W64/apps/qgis-dev/bin">
  AddHandler fcgid-script .exe
  AllowOverride None
  Options ExecCGI
  Require all granted
</Directory>@

I tried to run qgis_mapserv.fcgi.exe from the commandline, but immediately an application error without any further info (except from the number 0xc00000142) popped up.

I removed the development version from my laptop and reinstalled version 3.2 again. Did the same WMS GetCapabilities request which shows the expected result nicely.

Is this a bug or did I forget something to install/update?

**Comment by alexbruy** [comment]
Still true with 3.10/master?

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
