### ISSUE TITLE
WCS client issues

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27973]
Author Name: **Richard Duivenvoorde** (@rduivenvoorde)
Original Redmine Issue: [20152](https://issues.qgis.org/issues/20152)
Affected QGIS version: 3.3(master)
Redmine category:web_services_clients/wcs

---
The following public wcs services:

https://geodata.nationaalgeoregister.nl/ahn2/wcs?

https://geodata.nationaalgeoregister.nl/ahn3/wcs?

Fail to work in QGIS3

Trying to load these (epsg:28992) services has several problems:
(looking into debug window for fired requests)

1) QGIS always fires a request for the full extent of the dataset (whole of the Netherlands in this case) in a 10x10px raster. In this case those requests timeout.

2) QGIS sometimes seems to load a raster (showing a black mapcanvas) but min/max values in Legend then show 0/0.

3) When trying to show the properties of a layer in such case, QGIS crashes (see below for stacktrace)

4) Not sure to me if this problem is due to the slowness of the service of the 'test'- or 'legendicon -requests OR if QGIS has a problem with the data

5) QGIS really needs a nodata value sometimes eg in the ahn2_5m layer, you really have to put a nodata value of -3.4028234663852886e+38 otherwise you have slowdown of QGIS.

Crash ID: 39ea8210ccdfce385a6120ee9d1e302811bca6bf

Stack Trace

QObject::inherits :
PyInit_sip :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QMetaObject::activate :
QgsSymbolLayerMetadata::operator= :
QgsSymbolLayerMetadata::operator= :
QgsSymbolLayerMetadata::operator= :
QgsSymbolLayerMetadata::operator= :
QMetaCallEvent::placeMetaCall :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsSymbolLayerMetadata::operator= :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
TranslateMessageEx :
TranslateMessage :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
QgsMapToolAnnotation::annotationItems :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.3.0-Master
QGIS code revision: 9cae77f262
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.3.2
Running against GDAL: 2.3.2

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by Pedro-Murteira** [comment]
@rduivenvoorde Hello, is this issue still valid on recent versions?
