### ISSUE TITLE
Postgis provider dialog does not show empty schema's

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27970]
Author Name: **Richard Duivenvoorde** (@rduivenvoorde)
Original Redmine Issue: [20149](https://issues.qgis.org/issues/20149)
Affected QGIS version: 3.3(master)
Redmine category:gui

---
After creating a fresh schema, this cannot be viewed in the browser or postgis connection dialog.
(not even when you click the 'Also list tables with no geometry')

Only after adding data it will show up.

In the DB-manager the emtpy schema is at viewable, so you can import data into it.

Would it not be more helpfull if the dialog would show all schema's always?

(Added screenshots of both dbmanager and dialog, empty schema is called 'testschema')

---

- [dbmanager.png](https://issues.qgis.org/attachments/download/13524/dbmanager.png) (Richard Duivenvoorde)
- [postgresprovider.png](https://issues.qgis.org/attachments/download/13525/postgresprovider.png) (Richard Duivenvoorde)

**Comment by stev-0** [comment]
@rduivenvoorde - I checked this on master and newly created schemas do show up in the browser, but not in the Add Layer dialog. To me this makes sense - the browser shows that a schema exists even if it has no data, but it is not obvious that you should be able to see an empty schema in the Add Layer dialog, as this is just showing suitable layers for inclusion - by definition a schema with nothing in it will not have a suitable layer,

I think it would take quite a bit of code to switch the behaviour to showing empty schemas by default in the dialog, not sure if it's worth it.

**Comment by rduivenvoorde** [comment]
@stev-0 mmm, not totally agree with your reasoning, QGIS should not hide schema's (or anything else) I think. I also do not know if it is deliberate or not. 
But I do agree that if it is hard to implement (I'm not familiar with that part of the code), that it is not worth putting that time in it.

**Comment by alexbruy** [comment]
I can see empty schema in browser in master. But it still not visible in the Datasource Manager and I'm not sure if it should be shown, as Datasource Manager used only to load layers.

**Comment by gioman** [comment]
> I can see empty schema in browser in master. But it still not visible in the Datasource Manager and I'm not sure if it should be shown, as Datasource Manager used only to load layers.

I guess is ok now.
