### ISSUE TITLE
project selection combobox initially empty when trying to open project from postresql

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27986]
Author Name: **Sebastian Brocks** (@beerockxs)
Original Redmine Issue: [20165](https://issues.qgis.org/issues/20165)
Affected QGIS version: 3.2.3
Redmine category:project_loading/saving

---
When I want to open a project from PostgreSQL, the project dropdown box is initially empty. I need to switch the table scheme to another scheme and then switch back for it to contain the projects that are contained in the database schema

**Comment by beerockxs** [comment]
this does not happen anymore in 3.6.3
