### ISSUE TITLE
add interactive digiting tool to split multipart to single parts

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27989]
Author Name: **Antonio Viscomi** (@Antoviscomi)
Original Redmine Issue: [20168](https://issues.qgis.org/issues/20168)

Redmine category:editing

---
Hi all, 
I often use the "Multipart to single parts" plugin developed by Alexandre Neto. 
I think this is very useful tool that enable users to split multipart feature to single parts one.
Well I ask to developpers to merge this plugin as QGIS core editing tools. 

Thanks in advance

Antonio

**Comment by alexbruy** [comment]
Looks like duplicate of #13338.

**Comment by SrNetoChan** [comment]
You can use the multipart to single part tool in replace in place mode. There is also a split parts too (to isolate one part at a time) I still think my plugin is useful and easier to work with, when you need to explode all parts.

**Comment by Antoviscomi** [comment]
@SrNetoChan @alexbruy my request was to integrate the plugin between the native editing commands so that it is not necessary to search and install it as a plugin
