### ISSUE TITLE
[mdal] Not possible to delete extra-dataset 

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27998]
Author Name: **Michel Kuhlmann** (Michel Kuhlmann)
Original Redmine Issue: [20177](https://issues.qgis.org/issues/20177)
Affected QGIS version: 3.3(master)
Redmine category:gui

---
In the mesh properties panel, it is possible to 'Assign Extra Dataset to Mesh'. 

But it not possible to remove one of these datasets again.

**Comment by PeterPetrik** [comment]
From QGIS 3.14 in Mesh Layer Properties dialog it is possible to uncheck the quantity to now show in the menu

<img width="808" alt="Screenshot 2020-09-11 at 10 36 53" src="https://user-images.githubusercontent.com/804608/92894353-c9c9e400-f41a-11ea-8a3a-a8ac9eb878de.png">
