### ISSUE TITLE
[mdal] Open Meshes from the command-line

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28002]
Author Name: **Michel Kuhlmann** (Michel Kuhlmann)
Original Redmine Issue: [20181](https://issues.qgis.org/issues/20181)

Redmine category:gui

---
It would be great to open meshes directly from the commmand-line. E.g.

qgis mesh.2dm

Currently this only works with e.g. Shapefiles or raster datasets.

**Comment by alexbruy** [comment]
This already possible.
