### ISSUE TITLE
[Options] Missing "cap style" parameter in Options --> digitizing tab --> Curve offset tools

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28005]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [20184](https://issues.qgis.org/issues/20184)
Affected QGIS version: 3.3(master)
Redmine category:editing

---
When using the "Offset curve" tool from the advanced digitizing toolbar, you get a input dialog with options like "Join style", "Quadrant segments", "Miter limit" or "Cap style". All but the latter are from the Settings --> Options --> Digitizing --> Curve offset tools section.
For consistency, it could be nice to have that setting also there.

**Comment by Pedro-Murteira** [comment]
Still an issue on QGIS 3.16.14 and 3.22.1.
