### ISSUE TITLE
Coordinate widget on status bar doesn't display whole numbers

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28036]
Author Name: **Vedran Stojnovic** (@phidrho)
Original Redmine Issue: [20215](https://issues.qgis.org/issues/20215)
Affected QGIS version: 3.2.3
Redmine category:gui

---
Coordinate widget frame is not displaying all digits properly (first digit is partially hidden). QGIS is in fullscreen on 22" monitor (1680x1050), so there should be plenty of space for everything. Maybe some widgets should be moved to another toolbar/location (maybe magnifier and rotation) if there is no place.
I would also like to propose a feature - to add a setting for fixed number of decimal places for coordinates display, it is very important for geodesists. In attachment there is a picture how it's solved in DraftSight CAD software.

---

- [coord_bug_example2.png](https://issues.qgis.org/attachments/download/13596/coord_bug_example2.png) (Vedran Stojnovic)
- [coord_bug_example1.png](https://issues.qgis.org/attachments/download/13597/coord_bug_example1.png) (Vedran Stojnovic)
- [coord_bug_example3.png](https://issues.qgis.org/attachments/download/13598/coord_bug_example3.png) (Vedran Stojnovic)
- [coord_bug_example4.png](https://issues.qgis.org/attachments/download/13599/coord_bug_example4.png) (Vedran Stojnovic)
- [draftsight_example.png](https://issues.qgis.org/attachments/download/13600/draftsight_example.png) (Vedran Stojnovic)
- [draftsight_settings_example.png](https://issues.qgis.org/attachments/download/13601/draftsight_settings_example.png) (Vedran Stojnovic)

**Comment by nyalldawson** [comment]
This is fixed in recent versions
