### ISSUE TITLE
Drop-down menu for adding line object features

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28037]
Author Name: **Vedran Stojnovic** (@phidrho)
Original Redmine Issue: [20216](https://issues.qgis.org/issues/20216)

Redmine category:gui

---
There are many add feature options which can be found in Edit menu, but there are no buttons for them on toolbar, so they are kinda hidden.
It would be great if that options would be incorporated as drop-down button in Digitizing toolbar (or inside Advanced Digitizing toolbar).

---

- [add line feature.png](https://issues.qgis.org/attachments/download/13602/add%20line%20feature.png) (Vedran Stojnovic)
- [add_line_object.png](https://issues.qgis.org/attachments/download/13603/add_line_object.png) (Vedran Stojnovic)

**Comment by antoniolocandro** [comment]
I think these are now exposed correct?

![image](https://user-images.githubusercontent.com/4627073/146079275-a1b4d40a-63ad-4129-911e-bb56940e2c99.png)

**Comment by phidrho** [comment]
Hi @antoniolocandro, @gioman,

this seems good to me. Is it built in new version or there will be a feature request for this feature, I'm still on 3.16.3 on my home PC so I don't see this change...

If it's already implemented in the new version, we can close this feature request.

@gioman
I would like to comment one more thing related to toolbars - with installing QGIS we get "Vector Toolbar" which doesn't contain any tools, ie. an empty toolbar and it is enabled by default. I have noticed it for many versions, I would say since version 3 came out, but don't get 100% me on that.

**Comment by gioman** [comment]
> @gioman
> I would like to comment one more thing related to toolbars - with installing QGIS we get "Vector Toolbar" which doesn't contain any tools, ie. an empty toolbar and it is enabled by default. I have noticed it for many versions, I would say since version 3 came out, but don't get 100% me on that.

@phidrho it is usually a localization/translation issue. Try change QGIS language to EN.

**Comment by phidrho** [comment]
> > @gioman
> > I would like to comment one more thing related to toolbars - with installing QGIS we get "Vector Toolbar" which doesn't contain any tools, ie. an empty toolbar and it is enabled by default. I have noticed it for many versions, I would say since version 3 came out, but don't get 100% me on that.
> 
> @phidrho it is usually a localization/translation issue. Try change QGIS language to EN.

I am using English, and I tried now to override System Locale to English, but it is the same.

![image](https://user-images.githubusercontent.com/1849293/146215145-5795027c-8399-412f-bc28-5f59bf14980c.png)

**Comment by gioman** [comment]
> I am using English, and I tried now to override System Locale to English, but it is the same.

@phidrho do you have "processing" enabled in plugins manager?

**Comment by phidrho** [comment]
@gioman yes, it is enabled
![image](https://user-images.githubusercontent.com/1849293/146216624-169e75e0-4201-4167-8269-ce0cf039d41b.png)

**Comment by gioman** [comment]
> @gioman yes, it is enabled

@phidrho sorry, it seems it is really that way (empty by default). That toolbar will get populated when you install some vector/related extension.

**Comment by phidrho** [comment]
@gioman ok, thnx for checking out
But I would consider this _kind of a bug_, it doesn't make good sense to me having an empty toolbar by default which is waiting to be filled with some _possible_ tools from _possible_ plugins. 
Maybe we can comment this on developer mailing list.

**Comment by gioman** [comment]
> some _possible_ tools from _possible_ plugins.

@phidrho it is also populated with core tools, like topology checker.
