### ISSUE TITLE
QGIS does not obey saved SSL server exceptions

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28056]
Author Name: **Cory Albrecht** (@CoryAlbrecht)
Original Redmine Issue: [20235](https://issues.qgis.org/issues/20235)
Affected QGIS version: 3.2
Redmine category:authentication_system
Assignee: Larry Shaffer

---
QGIS 2.18 and 3.2 with GRASS 7, installed via the most recent OSGeo installer. Custom certificate configuration window opens each time the GeoServer WMS layer is opened or reloaded via move, zoom. Choosing "Ignore" instead of "Save & Ignore" makes the warning go away until the next time QGIS is opened, but if "Save & Ignore" is chosen it keeps getting shown.

In Settings→Options→Authentication→Manage Certificates, the exception is listed. It's a self-signed certificate with a host name mismatch.

Issue does not occur in 2.18 on Ubuntu Linux.

**Comment by alexbruy** [comment]
Still true with 3.10/master?

**Comment by alexbruy** [comment]
Closing for the lack of feedback. Please reopen if necessary.
