### ISSUE TITLE
Issue: Layer styles stored in SpatialLite Database not filtering/loading/saving correctly. 

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28055]
Author Name: **Brett Carlock** (@Saijin-Naib)
Original Redmine Issue: [20234](https://issues.qgis.org/issues/20234)
Affected QGIS version: 3.5(master)
Redmine category:symbology

---
Issue Summary:
It is very difficult to load/set a default style from a SpatialLite database, despite having created the style appropriately as the default for a layer.
The style picker seems to ignore the default style for the layer you want to load it onto, and setting a loaded style as Default to the database simply creates a copy of the already existing valid style.

Screencap of the behavior:
https://www.youtube.com/watch?v=sIZ1w3lEDLs

**Comment by alexbruy** [comment]
Not reproducible on master. Please reopen if necessary.
