### ISSUE TITLE
virtual fields can't be filtered

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28072]
Author Name: **Tobias Wendorff** (Tobias Wendorff)
Original Redmine Issue: [20251](https://issues.qgis.org/issues/20251)
Affected QGIS version: 3.5(master)
Redmine category:virtual_fields

---
After creating a virtual field with $area (float), it's not possible to filter on this variable - they don't appear on the list. It works for normal variables.

I don't know if this is a bug or a missing feature (perhaps you can select those fields by virtual layers only?).

**Comment by troopa81** [comment]
Works in master/3.14

![filter_virtualfield](https://user-images.githubusercontent.com/14358135/94011731-1fea4000-fda8-11ea-80df-628613632f26.gif)

I close the ticket, please re-open it if I didn't reproduce it correctly
