### ISSUE TITLE
Data defined override into legend items automatically

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28088]
Author Name: **Patrick Harvey** (Patrick Harvey)
Original Redmine Issue: [20267](https://issues.qgis.org/issues/20267)

Redmine category:map_legend

---
I have been using QGIS for a while now and I am trying to display 2 sets of data at a point. Manipulating size and colour are the logical choices for me and I have used data defined override. The GIS displays this fine in the main data window, and on the print layout, however, when I create my legend there is no data defined override for the colour or the size in the legened. 

Is there a way to do this or is this not yet a feature?

If it is not a feature then when will it become one? 

Kind regards,

Pat.

**Comment by DelazJ** [comment]
@gioman maybe could we close this one? I don't remember whether we got the fix in the docs but there seems to be no issue in the application, anyway.
