### ISSUE TITLE
Automatic repair source folder of 'Missing Data'

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28106]
Author Name: **Matthew Bodnar** (Matthew Bodnar)
Original Redmine Issue: [20285](https://issues.qgis.org/issues/20285)

Redmine category:project_loading/saving

---
It would be great if there was a group of broken source data links that could be automatically repaired following the manual re-linking of the first file.

**Comment by roya0045** [comment]
autofinder and other changes made to the bad layer handler should solve this.
