### ISSUE TITLE
Project which are saved with special characters in the filename and with the qgz extension are blank

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28113]
Author Name: **jd lom** (@lejedi76)
Original Redmine Issue: [20292](https://issues.qgis.org/issues/20292)
Affected QGIS version: 3.4.3
Redmine category:project_loading/saving

---
Hi,

I know it's not a best practice (no space and no special character in filename) but some user does it.

When reopening this project, the project is blank.

Whis the .qgs extension, the project is opening normally.

Only tested on windows.

---

- [test_save_project.zip](https://issues.qgis.org/attachments/download/13634/test_save_project.zip) (jd lom)

**Comment by jdlom** [comment]
Hi,
The problem seems to be resolved. I can't reproduce that bug. 
Test on windows QGIS 3.10.2
