### ISSUE TITLE
Off-Line editing should NOT ask to fill manually the PK field

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28122]
Author Name: **Giovanni Manghi** (@gioman)
Original Redmine Issue: [20301](https://issues.qgis.org/issues/20301)
Affected QGIS version: 3.4.0
Redmine category:c++_plugins/offline_editing

---
QGIS 2.18:

add a postgis layer
put it in off-line mode
edit it (add feature) > is NOT asked to fill (not mandatory) the field that represent the PK in pgsql
synchronize it back > all OK (the new feature is given a proper value for the PK field)

QGIS 3.4:

add a postgis layer
put it in off-line mode (spatialite or geopackage)
edit it (add feature) > the field that represent the PK is marked as mandatory and the user must fill it manually to be able to synchronize back. This of course can cause errors.

Also when using GPKG: #28097

---

Related issue(s): #28097 (relates)
Redmine related issue(s): [20276](https://issues.qgis.org/issues/20276)

---

**Comment by signedav** [comment]
I'll check this out.
