### ISSUE TITLE
georeferencing in EPSG:4674 creates an output with EPSG:4140

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28146]
Author Name: **JOSE SARAIVA PLACIDO JUNIOR** (JOSE SARAIVA PLACIDO JUNIOR)
Original Redmine Issue: [20325](https://issues.qgis.org/issues/20325)
Affected QGIS version: 3.4.0
Redmine category:c++_plugins/georeferencer

---
Hello, I note that when I using the EPSG 4674 (GEOGRAPHIC COORDINATE DATUM SIRGAS 2000) for georreferencing some images, the georreferencer although to transform the image to EPSG 4674, It transform to EPSG 4140. I've tested some versions of QGis 2.18, 3.2 and 3.4 all of them has the same problem, so I try the version 2.4 and It is ok.So I think that is a problem.

I hope to be clear about the problem, best regards and thank's for the great job with QGis

---

- [IMAGENS.7z](https://issues.qgis.org/attachments/download/13669/IMAGENS.7z) (JOSE SARAIVA PLACIDO JUNIOR)
- [4674.7z](https://issues.qgis.org/attachments/download/13670/4674.7z) (JOSE SARAIVA PLACIDO JUNIOR)

**Comment by roya0045** [comment]
Is this still valid with the recent changes to the goereferencer?

**Comment by gioman** [comment]
Closing for lack of feedback.
