### ISSUE TITLE
Rendering 3D Lines pseudo vertex

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28171]
Author Name: **Michael Kuerbs** (Michael Kuerbs)
Original Redmine Issue: [20350](https://issues.qgis.org/issues/20350)
Affected QGIS version: 3.4.0
Redmine category:3d

---
When I render simple 3D Lines (LineStringZ).
In the 3D View all lines of my layer do have the same additonal pseudo vertex.

sample:
LineStringZ (663921.757 5643335.050 283.746, 663926.991 5643336.589 287.855, 663920.271 5643334.612 293.445)

---

- [Screen_Linestringz_with_Pseudo_point.PNG](https://issues.qgis.org/attachments/download/13672/Screen_Linestringz_with_Pseudo_point.PNG) (Michael Kuerbs)

**Comment by wonder-sk** [comment]
This should be fixed in recent versions of QGIS (e.g. 3.6). Please reopen if not.
