### ISSUE TITLE
Python3 doctest missing in QGIS 3.4.1

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28186]
Author Name: **Jonathan Willitts** (@JonathanWillitts)
Original Redmine Issue: [20365](https://issues.qgis.org/issues/20365)
Affected QGIS version: 3.4.0
Redmine category:build/install

---
The Python3 implementation shipped with QGIS 3.4.1 Windows (64 bit) versions is missing the doctest module.

Note the below steps work fine/as expected QGIS 3.2.3

Steps to reproduce

Open OSGeo4W shell (or shell configured for QGIS Python):
```
C:\>py3_env

C:\>SET PYTHONPATH=

C:\>SET PYTHONHOME=C:\PROGRA~1\QGIS3~1.4\apps\Python37

C:\>PATH C:\PROGRA~1\QGIS3~1.4\apps\Python37;C:\PROGRA~1\QGIS3~1.4\apps\Python37\Scripts;C:\PROGRA~1\QGIS3~1.4\apps\Python27\Scripts;C:\PROGRA~1\QGIS3~1.4\bin;C:\Windows\system32;C:\Windows;C:\Windows\system32\WBem

C:\>python
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import doctest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'doctest'
>>>

```

**Comment by alexbruy** [comment]
Already fixed.
