### ISSUE TITLE
Map canvas whiteout on editing

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28196]
Author Name: **Johannes Metzler** (Johannes Metzler)
Original Redmine Issue: [20376](https://issues.qgis.org/issues/20376)
Affected QGIS version: 3.4.1
Redmine category:map_canvas

---
After a while in editing mode the map canvas whites out, if you zoom out features apper on higer zoomlevels only.
I have restart Qgis to get to normal display again.
no error messeages at all
Thanks
J

---

- [Whiteout2.JPG](https://issues.qgis.org/attachments/download/13693/Whiteout2.JPG) (Johannes Metzler)
- [Whiteout1.JPG](https://issues.qgis.org/attachments/download/13694/Whiteout1.JPG) (Johannes Metzler)

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary,
