### ISSUE TITLE
GDA94>GDA2020 OTF Transformation

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28195]
Author Name: **Tyson Hillyard** (Tyson Hillyard)
Original Redmine Issue: [20375](https://issues.qgis.org/issues/20375)

Redmine category:projection_support
Assignee: Nyall Dawson

---
Can't seem to find a way to implement GDA94(EPSG4283)>GDA2020(EPSG7844) OTF Transformation.
QGIS has support for GDA2020 now.

There are 3 options in EPSG now for this transformation and PROJ seems to support the methods, but i can't find a way to use them in QGIS.
The three EPSG codes for transformation for onshore Australia are:
8048 (Helmert Transformation)
8446 (Conformal Grid Transformation with associated GSB)
8447 (Conformal + Distrortion Grid transformation with associated GSB)

**Comment by nyalldawson** [comment]
Fixed in 3.8
