### ISSUE TITLE
Attributes Form

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28190]
Author Name: **Johannes Metzler** (Johannes Metzler)
Original Redmine Issue: [20370](https://issues.qgis.org/issues/20370)

Redmine category:edit_widget

---
Would it be possible to add "editable" option to all Widgets like it is at the unique value widget? (or turn off the attribute form data checks when editing the attribute table directly)
it would give the user more freedom to collect attributes on historical data wich are not always exactly the same. 

Thanks!

**Comment by haubourg** [comment]
This lacks a bit of details. Widget are all very different and I fail to see the point of circumventing data constraints for value relations. Closing for lack of details. Please reopen if you have more information here.
