### ISSUE TITLE
make label and ticks rotation possible in print layout

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28203]
Author Name: **Loïc Bfr** (Loïc Bfr)
Original Redmine Issue: [20383](https://issues.qgis.org/issues/20383)

Redmine category:map_composer/printing

---
It would be really nice to make possible  grid coordinate labels rotation in print layout, synchronising with map rotation factor for example.
Reading a map rotated with crosses rotated but with ticks and coordinates only vertical or horizontal could become a hard job when there is a lot of information already on the map.

**Comment by olivierdalang** [comment]
duplicates https://github.com/qgis/QGIS/issues/36904
