### ISSUE TITLE
QgsCompoundColorWidget instance crash when QgsApplication::colorSchemeRegistry() is empty

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28208]
Author Name: **Vincent Cloarec** (@vcloarec)
Original Redmine Issue: [20388](https://issues.qgis.org/issues/20388)
Affected QGIS version: 3.5(master)
Redmine category:unknown

---
When QgsApplication is not instanciate and the member mColorSchemeRegistry is empty, a crash appear when calling schemelist.at() (line 78 in qgscompoundcolorwidget.cpp). A way to avoid the crash is to add a color scheme to the registry before instantiate QgsCompoundColorWidget, but may be it would be nicer to avoid the crash even the registry is empty.

**Comment by PeterPetrik** [comment]
As mentioned in https://docs.qgis.org/3.16/en/docs/pyqgis_developer_cookbook/intro.html?using-pyqgis-in-standalone-scripts#using-pyqgis-in-standalone-scripts, using QGIS API without properly initializing (`initQgis()`) could lead to undefined behaviour and it is not a QGIS problem.
