### ISSUE TITLE
Tiny Identify Results window 

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28200]
Author Name: **Oskar Karlin** (@Oskarlin)
Original Redmine Issue: [20380](https://issues.qgis.org/issues/20380)
Affected QGIS version: 3.4.0
Redmine category:mac_os_specific
Assignee: Denis Rouzaud

---
From version 3.4 the GUI on Mac seems to have changed a lot (it now doesn't look at all like macOS gui (but that's another story)) and one of these things that have changed is that the default size of the _identify feature_ popup window is now very very tiny instead of having the size of the actual content of the attribute columns. See attached image. 

This was not an issue before 3.4.

---

- [Screen Shot 2018-11-06 at 11.15.24.png](https://issues.qgis.org/attachments/download/13687/Screen%20Shot%202018-11-06%20at%2011.15.24.png) (Oskar Karlin)
- [Screen Shot 2018-11-06 at 11.23.53.png](https://issues.qgis.org/attachments/download/13688/Screen%20Shot%202018-11-06%20at%2011.23.53.png) (Oskar Karlin)

---

Related issue(s): #29223 (relates)
Redmine related issue(s): [21406](https://issues.qgis.org/issues/21406)

---

**Comment by alexbruy** [comment]
Duplicates #28710
