### ISSUE TITLE
QGIS freezes on MacOS 10.14 (and Qt 5.11) when launched from Launch Services (works ok when launched from terminal)

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28201]
Author Name: **robert kalasek** (@rkalasek)
Original Redmine Issue: [20381](https://issues.qgis.org/issues/20381)
Affected QGIS version: 3.5(master)
Redmine category:build/install
Assignee: William Kyngesburye

---
 0
down vote
favorite

I've just installed the latest verion of QGIS (3.4.0) on a MacBook Pro 13" (3.3 GHz Core I7) MacOS 10.14. The application seemed to work fine at first. On a certain point I've tried to open a recent project via Project/Open menu and had a system freeze for 12 seconds. During that time the whole system was not at all responsive (just mouse moves did work). None of the other applications worked in any way, I couldn't even move other app's windows, the system monitor didn't show any significant increase of activity and instead of the expected functional filemanager-window a tiny little inactive shadow of the filemanager-window was displayed ... as you might identify in the added image.

I was able to reproduce this behavior for several times - even after restart of QGIS.

The whole thing might be related to stackexchange article https://gis.stackexchange.com/questions/300626/qgis-3-4-0-madeira-unresponsive but it is on a mac and it doesn't seem to affect the "rest" of QGIS.

---

- [IMG_6968_2.jpg](https://issues.qgis.org/attachments/download/13689/IMG_6968_2.jpg) (robert kalasek)
- [IMG_6970.jpg](https://issues.qgis.org/attachments/download/13701/IMG_6970.jpg) (robert kalasek)
- [Screenshot 2019-02-05 at 14.54.16.png](https://issues.qgis.org/attachments/download/14242/Screenshot%202019-02-05%20at%2014.54.16.png) (Yaroslav Vasyunin)
- [Screenshot 2019-03-30 at 20.32.54.png](https://issues.qgis.org/attachments/download/14703/Screenshot%202019-03-30%20at%2020.32.54.png) (MRick -)

---

Related issue(s): #28144 (relates), #28798 (duplicates), #28888 (duplicates)
Redmine related issue(s): [20323](https://issues.qgis.org/issues/20323), [20979](https://issues.qgis.org/issues/20979), [21070](https://issues.qgis.org/issues/21070)

---

**Comment by PeterPetrik** [comment]
the offical QGIS packages are now based on QT5.12+ so the issue should not be present any more.

@rkalasek do you still experience the issue with one-click installer?

**Comment by rkalasek** [comment]
@PeterPetrik: no issues any more ! ! ! works fine !
