### ISSUE TITLE
Add the "Select an input band for output" parameter to GDAL translate

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28210]
Author Name: **Nicolas Cadieux** (@NicolasCadieux)
Original Redmine Issue: [20390](https://issues.qgis.org/issues/20390)

Redmine category:processing/gdal
Assignee: Giovanni Manghi

---
There is no "out format field" (-of format) in Gdal Translate.  Currently, the output format is guessed from the file extension (not obvious for someone used to working at the command line) and a single format is applied by default to all output files.  
 
Additional fields like -b band would be very nice to have. Since there are many possible parameters, perhaps and open parameter field would be helpful for this and other gdal tools.    

https://www.gdal.org/gdal_translate.html

**Comment by alexbruy** [comment]
Implemented in c224a01
