### ISSUE TITLE
Advanced Digitizing Panel

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28237]
Author Name: **Nicolas Cadieux** (@NicolasCadieux)
Original Redmine Issue: [20417](https://issues.qgis.org/issues/20417)
Affected QGIS version: 3.4.1
Redmine category:gui

---
When snapping the Advanced Digitizing Panel to bottom half or the top half of another panel, it is no longer possible to resize both panels in the y plane.   You can only resize in the x plane. Limited resizing is possible only if a vector layer and only if an advanced digitizing tool are selected.

**Comment by Pedro-Murteira** [comment]
@NicolasCadieux I can no longer replicate this bug on QGIS 3.16.14 and 3.22.1.
