### ISSUE TITLE
Apply button in Field Calculator

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28239]
Author Name: **andskog -** (andskog -)
Original Redmine Issue: [20419](https://issues.qgis.org/issues/20419)

Redmine category:field_calculator

---
When working with the attribute table Field Calculator, it would be nice to have an "Apply" button in addition to the "OK" button, so that I can calculate and continue calculating, rather than repetitively having to reopen the calculator and filling in the expressions.

**Comment by alexbruy** [comment]
Duplicates #23887.
