### ISSUE TITLE
MSSQL: Layer loads but does not display (Attribute Table correct)

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28234]
Author Name: **CSW Broadband** (@crpage)
Original Redmine Issue: [20414](https://issues.qgis.org/issues/20414)
Affected QGIS version: 3.4.0
Redmine category:data_provider/mssql

---

Can't see anything special about this table (I've created a minimal copy which still has error, see below) but it does not display in v3.4 but does in v3.2.
Tried Exporting Features to a GeoPackage ( to troubleshoot the error) which shows that it adds another field called GEOM, seeing the actual geometry one as TEXT(255)

Export to vector file failed.
Error: Feature write errors:
Feature creation error (OGR error: sqlite3_exec(CREATE TABLE "Temp" ( "fid" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "geom" POLYGON, "ID" MEDIUMINT, "Postcode" TEXT(10), "Date Introduced" DATE, "Date Withdrawn" DATE, "CodePoint UPP" TEXT(255), "geom" TEXT(255))) failed: duplicate column name: geom)

In MSSQL, this is the temp file I created which has Ordnance Survey Polygon data in, all validated.

USE [BDUK 3.0]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Temp](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Postcode] [nvarchar](10) NOT NULL,
	[Date Introduced] [date] NULL,
	[Date Withdrawn] [date] NULL,
	[CodePoint UPP] [nvarchar](255) NULL,
	[geom] [geometry] NULL,
PRIMARY KEY CLUSTERED 
(
	[Postcode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

Insert INTO [dbo].[Temp]
( Postcode,[Date Introduced],[Date Withdrawn],[CodePoint UPP],[geom])
(SELECT Postcode,[Date Introduced],[Date Withdrawn],[CodePoint UPP],[geom]
   FROM [CSW3 Postcode Mapping IA]
)
--(25651 rows affected)

---

- [QGIS Bug 20414.docx](https://issues.qgis.org/attachments/download/13714/QGIS%20Bug%2020414.docx) (CSW Broadband)

**Comment by alexbruy** [comment]
Closing for the lack of feedback. Please reopen if necessary.
