### ISSUE TITLE
Allow editing of hidden layers

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28240]
Author Name: **Alex Hajnal** (@Alex-Kent)
Original Redmine Issue: [20420](https://issues.qgis.org/issues/20420)

Redmine category:digitising

---
In QGIS 2.x I frequently hide the layer I'm editing when I'm digitizing ortho imagery, LIDAR data, etc.  In 3.x this is no longer possible.  Could the ability to do this be added to 3.x?

**Comment by jef-n** [comment]
You could add a invisible style (no symbol render or setting it fully transparent) to the layer and switch styles instead enabling/disabling the layer (and use a map theme to switch more quickly).

**Comment by Alex-Kent** [comment]
@jef-n In 3.x is there any way to quickly flip between styles either with a simple mouse click or a keyboard shortcut?  The only methods I'm aware for switching styles involve selecting from a menu using the mouse.  Using the opacity slider could be a viable workaround though.  I have a python script for toggling the active layer's visibility from the keyboard; perhaps I could modify it to change its transparency instead.
