### ISSUE TITLE
Python console behaves strange

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28247]
Author Name: **Alexey T** (@Xeenych)
Original Redmine Issue: [20427](https://issues.qgis.org/issues/20427)
Affected QGIS version: 3.4.1
Redmine category:pyqgis_console

---
I wrote a function in a python script file.
Then I executed it via "Run Script" button in python console editor
Function threw an error.
Then I fixed this error, saved file and executed script again.
But console sees old function and continues to throw a nerror.

**Comment by alexbruy** [comment]
Is this still true?

**Comment by Xeenych** [comment]
Tested in 3.10.1
It is OK now.

**Comment by brittchap** [comment]
> Is this still true?

Do you know how to fix this error, or how it was fixed? I am getting this traceback error and cannot resolve it or find another thread about it anywhere.
