### ISSUE TITLE
Crash when reseting map view scale factor

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28254]
Author Name: **Alexandre Neto** (@SrNetoChan)
Original Redmine Issue: [20434](https://issues.qgis.org/issues/20434)
Affected QGIS version: 3.4.1
Redmine category:map_canvas

---
In a map view, using Syncronize Scale, if you try to reset the Scale factor by clicking the little arrow icon inside the text box, QGIS will crash.

See in attachment the animated gif on how to reproduce

!Peek2018-11-09 17-24.gif!

---

- [Peek2018-11-09 17-24.gif](https://issues.qgis.org/attachments/download/13725/Peek2018-11-09%2017-24.gif) (Alexandre Neto)

**Comment by SrNetoChan** [comment]
This is still happening on QGIS 3.9. Can we update the affected version?

**Comment by gioman** [comment]
> This is still happening on QGIS 3.9. Can we update the affected version?

there is no more tag/label for affected versions, the comment saying that is still affected is enough(?).

**Comment by nyalldawson** [comment]
This is fixed

**Comment by SrNetoChan** [comment]
Thanks!!
