### ISSUE TITLE
"Merge Selected Feature" do not works correctly with hidden fields

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28253]
Author Name: **Jan Lippmann** (@j-lippmann)
Original Redmine Issue: [20433](https://issues.qgis.org/issues/20433)
Affected QGIS version: 3.5(master)
Redmine category:digitising

---

"Take Attributes from selected feature" takes not the value from the selected feature.

!feature_merge_hidden_id_2.gif!

---

- [feature_merge_hidden_id_2.gif](https://issues.qgis.org/attachments/download/13723/feature_merge_hidden_id_2.gif) (Jan Lippmann)
- [merge_take_attributes.gif](https://issues.qgis.org/attachments/download/13758/merge_take_attributes.gif) (Jan Lippmann)

**Comment by gioman** [comment]
Still true.

**Comment by romanoe** [comment]
Still true on 3.16.10.

**Comment by leojat** [comment]
Still true on 3.22.12 and 3.28.1. Any news on this front?

**Comment by vaahtokarkki** [comment]
Still true on 3.34.3 and 3.36.0
