### ISSUE TITLE
fails to generate virtual geometry layer based on virtual wkt field

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28265]
Author Name: **Kepes Ádám** (Kepes Ádám)
Original Redmine Issue: [20445](https://issues.qgis.org/issues/20445)
Affected QGIS version: 3.4.1
Redmine category:virtual_layers

---
I would very like to generate a wkt field based on complicated expression on a delimited text layer, and auto make a geometry layer based on it! After i set the layer it is good, but reloading qgis makes a problem with it. 

I recorded it to show detailed.

please see video on:
https://www.dropbox.com/s/xhgt54q5bx922b3/qgis.mp4?dl=0

How could i do it?
thank you for your help!

**Comment by troopa81** [comment]
The video has been deleted. I try to do as you described and it works fine with the geometry by expression processing

![geomexpr](https://user-images.githubusercontent.com/14358135/94010311-0e079d80-fda6-11ea-84a5-4f78c9b64728.png)

Could please repost your video or close the ticket if it's not relevant anymore?

**Comment by gioman** [comment]
Closing for lack of further feedback.
