### ISSUE TITLE
The georeferencer dialog does not remember its size

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28268]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [20448](https://issues.qgis.org/issues/20448)
Affected QGIS version: 3.4.1
Redmine category:c++_plugins/georeferencer

---
I did a lot of georeferencing these days, using one screen for the georeferencer dialog and another one for QGIS main dialog.
When adding GCP points, i have to:
1. Click the point on the raster image
2. A dialog opens on which i have to select that i want to use the map canvas
3. The georeferencer dialog is minimized and i Click the point on the map. 
4. Once the point is added, the georeferencer dialog reopens. 

When reopening, the dialog does not take the full size i previously was using but opens in it default (too small) size, meaning that i have to resize the dialog for better visibility.

**Comment by uclaros** [comment]
@DelazJ Is this the same as #37230 ? If it is fixed with #37459 we can close this?

**Comment by gioman** [comment]
Assuming fixed by the referenced commit. Reopen if necessary.
