### ISSUE TITLE
Labeling style options reduced for default font on Windows 10

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28273]
Author Name: **Massimiliano Moraca** (Massimiliano Moraca)
Original Redmine Issue: [20453](https://issues.qgis.org/issues/20453)
Affected QGIS version: 3.7(master)
Redmine category:labelling

---
I've need to report a bug in QGIS 3.4.
As you can see from the image below, in the new version, for the labeling using Windows there isn't many option as "bold italic". This option are present if you use the last LTR on Windows or QGIS 3.4 on Ubuntu 18.04

---

- [qgis2.18-3.4.jpg](https://issues.qgis.org/attachments/download/13736/qgis2.18-3.4.jpg) (Massimiliano Moraca)

**Comment by nyalldawson** [comment]
This isn't a QGIS bug -- if it's an issue, it's an upstream Qt issue and needs fixing there.
