### ISSUE TITLE
Autogenerate fid in Geopackage doesn´t update

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28277]
Author Name: **Lene Fischer** (@LeneFischer)
Original Redmine Issue: [20457](https://issues.qgis.org/issues/20457)
Affected QGIS version: 3.4.1
Redmine category:editing

---
Having two geopackage layers from different databases. Total same tabel strucure.

Select and copy features in layer one.
Paste and save in layer two.

Some of the pasted features keeps the 'fid' and others get 'autogenerate'
Trying to save gives an error because of duplicate 'fid'

The workarround is to update the selected 'fid' to ''

See attached image

---

- [fid_autogenerate.png](https://issues.qgis.org/attachments/download/13738/fid_autogenerate.png) (Lene Fischer)

**Comment by Pedro-Murteira** [comment]
Tested this issue on QGIS 3.22.3. If the tables have the exact same structure, a dialog shows up to correct the values in order to paste them on the other table. @LeneFischer, did you come across this issue in more recent versions of QGIS?
