### ISSUE TITLE
Embedding layers does not work for projects saved as QGZ

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28280]
Author Name: **A. Egberts** (A. Egberts)
Original Redmine Issue: [20460](https://issues.qgis.org/issues/20460)
Affected QGIS version: 3.7(master)
Redmine category:project_loading/saving

---
I try to embed a layer from a QGS file made in Qgis 3.14. layer is not loading, or not shown.
When I try to embed the same layer form a QGS file made with 2.18, I get that layer well!

What is going wrong?

---

- [Knipsel.JPG](https://issues.qgis.org/attachments/download/13743/Knipsel.JPG) (A. Egberts)

**Comment by bellanz80** [comment]
I confirm in QGIS 3.10 Windows 10
