### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xac in position 211: illegal multibyte sequence

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28294]
Author Name: **law water** (law water)
Original Redmine Issue: [20474](https://issues.qgis.org/issues/20474)
Affected QGIS version: 3.0.3
Redmine category:pyqgis_console

---
I use windows OS,  this error occured when I built python script which contains chinese character. 

the python file was readly encoding by 'utf-8', It did not work when 

`exec(open('C:/Users/xxx/QGIS/scripts/test.py'.encode('utf-8')).read())` in the python console. but

`exec(open('C:/Users/xxx/QGIS/scripts/test.py'.encode('utf-8'), 'rb').read())` worked well. It maybe

an error of python but I did not sure.

---

Related issue(s): #28295 (copied_to)
Redmine related issue(s): [20475](https://issues.qgis.org/issues/20475)

---

**Comment by alexbruy** [comment]
Duplicates #27233
