### ISSUE TITLE
Text-free field names not treated correctly

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28296]
Author Name: **Samuel Wechsler** (Samuel Wechsler)
Original Redmine Issue: [20476](https://issues.qgis.org/issues/20476)
Affected QGIS version: 3.2.3
Redmine category:data_provider

---
Geopackage allows field names without text characters. It is possible to name an attribute for example "2013-2016". QGIS shows two (probably related) problems with such field/column names. I am aware that it is a bad habit to name fields without text but as it is possible, QGIS should be able to deal with it. 

Problem 1: If you want to use such a field/column with "Categorized" symbology, QGIS does not find the categories available. If I manually modify the field name in the layer properties > symbology from 2013-2016 to "2013-2016" (take not of the "") QGIS finds the available categories.

Problem 2: If such a layer is filtered and the filtered layer is then exported (via export -> save feature as) there is a misalignment of the columns/fields. If I don't filter the layer everything works fine. If I properly rename the column to yr2013-2016, then filter the layer and then export - everything works fine also. So the export is only not working properly when one uses filters in combination with non-text column/field names.

**Comment by Pedro-Murteira** [comment]
I can't replicate this issue on QGIS 3.16.15 and 3.22.1.
