### ISSUE TITLE
QGIS Server 3.4 on Windows: Error tranferring 

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28290]
Author Name: **Louis Leguan** (@hmoenk)
Original Redmine Issue: [20470](https://issues.qgis.org/issues/20470)
Affected QGIS version: 3.4.0
Redmine category:qgis_server

---
Hey,
I have just installed OsGeoaW version 3.4 and I am not able to publish WMS.
The Layer itself in QGIS show the error: 'Capabilities request failed' _(CapabilitiesError.png)_ and shows the error 'transferring http://...' _(ErrorTransferring.png)_. 

Within the properties of the QGIS Server, the initial test does not show any errors _(QGISStart.png)_.

Also the url https://localhost/cgi-bin/qgis_mapserv? show 'object not found' _(mapserv.fcgi.png)_.

Is this a problem of the new version?

---

- [CapabilitiesError.PNG](https://issues.qgis.org/attachments/download/13753/CapabilitiesError.PNG) (Louis Leguan)
- [ErrorTransferring.PNG](https://issues.qgis.org/attachments/download/13754/ErrorTransferring.PNG) (Louis Leguan)
- [mapserv.fcgi.PNG](https://issues.qgis.org/attachments/download/13755/mapserv.fcgi.PNG) (Louis Leguan)
- [QGISStart.PNG](https://issues.qgis.org/attachments/download/13757/QGISStart.PNG) (Louis Leguan)
- [error.log](https://issues.qgis.org/attachments/download/14233/error.log) (Louis Leguan)

**Comment by jonnyforestGIS** [comment]
This can be close based on last comment Louis Leguan ?

> We tested QGIS Server on Windows a couple of days ago and is ok, see: https://issues.qgis.org/issues/20873#note-7

**Comment by gioman** [comment]
> This can be close based on last comment Louis Leguan ?

it is also my observation that at the moment it works ok.
