### ISSUE TITLE
Geometry type not detected when loading query to canvas using MakePoint for geometry (DBManager)

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28307]
Author Name: **Chris York** (Chris York)
Original Redmine Issue: [20487](https://issues.qgis.org/issues/20487)
Affected QGIS version: 3.4.0
Redmine category:db_manager

---
I have a GeoPackage with a table containing coordinates as separate columns (imported from an external application, originally CSV) - there are multiple sets of coordinates in each record and I am loading a series of layers from each record using a different subset of the fields within the record.

To define the geometry of the layer my query includes:

@MakePoint( "A-Longitude" , "A-Latitude") as geometry@

When the layer is loaded to the canvas the layer styling is set to a Line so nothing is displayed. By changing the Layer styling to "No Symbols" and then back to "Single symbol", the geometry type is detected and the points appear on the canvas. However, labels can be displayed at the correct location before the layer symbology is changed.

I am guessing that the either canvas is not detecting geometry type on load or DBManager is not providing that, and the default type is a line?

Issue also occurred in 2.18, 3.0 and 3.2 

---

- [test1.gpkg](https://issues.qgis.org/attachments/download/13931/test1.gpkg) (Giovanni Manghi)

**Comment by alexbruy** [comment]
Duplicates #27914. `MakePoint()` returns `NULL` instead of valid geometry that's why layer loaded as table and geometry type is not detected.
