### ISSUE TITLE
[Digitizing] Tracing tool does not work if snapping is other than on "Active layer"

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28311]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [20491](https://issues.qgis.org/issues/20491)
Affected QGIS version: 3.5(master)
Redmine category:digitising

---
Trying to use the digitizing automatic tracing option, it turns out that it only works if the snapping is set on "Active layer".
If I switch to "All layers" or "Advanced config" with some layers checked, I can snap to the features I need to, but I can't get the tracing, even for the layer being edited. Only single straight line.

**Comment by uclaros** [comment]
@DelazJ Is this still the case for you? If it is, can you provide more feedback? I happily use tracing and very seldom have "Active Layer" snapping.

**Comment by gioman** [comment]
This seems no longer the case.
