### ISSUE TITLE
Screen Freezes when moving window associated with QGIS

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28328]
Author Name: **Kyle Somerville** (Kyle Somerville)
Original Redmine Issue: [20508](https://issues.qgis.org/issues/20508)
Affected QGIS version: 3.4.1
Redmine category:unknown

---
Version 3.4.1 (but was previously observed with 3.2), Windows 10 64 bit - frequently when moving (dragging) the QGIS main window, or an application window (process, plugin etc) within QGIS the screen freezes and computer is unresponsive.  Workaround is CTRL+ALT+DEL and cancel, which reverts the QGIS window to where it was before the freeze, and the system continues.  No data loss observed, no crash that would produce a crash report.

**Comment by gioman** [comment]
Does not seems a general issue to me, not anymore at least.
