### ISSUE TITLE
Display name in layer properties is not automatically filled

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28353]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [20533](https://issues.qgis.org/issues/20533)
Affected QGIS version: 3.4.1
Redmine category:attribute_table

---
Create a temporary layer.
Add fields to the layer using the attribute table. Yesterday I was convinced the issue resides in the firt field being of string type but further tests before I report show that integer can also raise it.
Add features with their attributes.
In the locator bar, do a search with "af ".
Instead of features the layer would return a cryptic [Please define preview text] (no clue on the meaning nor how to fix).
The same text is shown in layer properties --> Display tab until you pick a field. Next search in locator won't show that text anymore.

PS: looks like creating the field in the layer properties does fill the display name field, thus no message in search.

**Comment by Pedro-Murteira** [comment]
Still true on QGIS 3.16.14 and 3.22.1.
