### ISSUE TITLE
Testing a filter for .osm datasources shows placeholders in the message

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28357]
Author Name: **Ivan Ivanov** (@suricactus)
Original Redmine Issue: [20537](https://issues.qgis.org/issues/20537)
Affected QGIS version: 3.4.1
Redmine category:vectors

---
When applying a filter (e.g. 1 = 1) on a vector layer and pressing the Test button, sometimes I get message with placeholders unreplaced:

> The where clause returned %n row(s).

This currently happened on a .osm layer.

---

- [Screenshot from 2018-11-18 04-01-47.png](https://issues.qgis.org/attachments/download/13797/Screenshot%20from%202018-11-18%2004-01-47.png) (Ivan Ivanov)

**Comment by Pedro-Murteira** [comment]
@suricactus I can't currently replicate this on QGIS 3.16.14 and 3.22.1. Has this been fixed meanwhile? If not, can you attach the specific dataset for further testing?
