### ISSUE TITLE
GUI bug: Layer Properties -> Attributes Form

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28365]
Author Name: **Todd Baldridge** (Todd Baldridge)
Original Redmine Issue: [20545](https://issues.qgis.org/issues/20545)
Affected QGIS version: 3.4.1
Redmine category:osx_ui

---
Selecting "Attributes Form" In Layer Properties immediately collapses the pane to icons only. Click again to resize the pane, and the pane disappears completely.

Cancel and reopen Layer Properties, and the left pane shows only icons. To expand the pane to reveal the icon names again, you must enter a value into the search field, which partially opens the pane. Next, cancel and re-open Layer Properties to expand the pane as normal.

Only "Attributes Form" in Layer Properties seems to exhibit this buggy behavior. Tested in Windows 10, macOS High Sierra, and also in macOS El Capitan in a virtual machine.

**Comment by alexbruy** [comment]
Probably the same as #29765.

**Comment by alexbruy** [comment]
Please test with latest master. I can not reproduce on Linux and Windows.

**Comment by alexbruy** [comment]
Closed for the lack of feedback. Please reopen if necessary.
