### ISSUE TITLE
processing doesn't output a shapefile's encoding

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28376]
Author Name: **Tobias Wendorff** (Tobias Wendorff)
Original Redmine Issue: [20556](https://issues.qgis.org/issues/20556)
Affected QGIS version: 3.5(master)
Redmine category:processing/core

---
The tools in "processing", like "split vector layer" don't write any information about encoding of shapefiles.
Postprocessing the files is very hard because you either have to know where they come from and which charset they might be in.

---

Related issue(s): #28434 (relates)
Redmine related issue(s): [20614](https://issues.qgis.org/issues/20614)

---

**Comment by nyalldawson** [comment]
Closing due to lack of feedback
