### ISSUE TITLE
Installer/Uninstaller does not exit when done (win7)

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28380]
Author Name: **Pär Smårs** (Pär Smårs)
Original Redmine Issue: [20560](https://issues.qgis.org/issues/20560)
Affected QGIS version: 3.4.1
Redmine category:windows_package

---
Have downloaded the latest 3.4.1.
Installed to target folder B:\APS\QGIS.3.4.1 (because I don't like spaces in paths)
After everything has been installed, the installer window still stays up, with every button inactive (grayed out).
It creates a directory for the Start menu. And then it says:
"S,,tt i disketten som inneh*ller kommandofilen" = "Insert the diskette that contains the command file"
I then have to break out of the installer using black magic and a little dance around my desk, i.e., using the Task Manger.
I hope this isn't the norm, although it has been for the last couple of versions.
Nobody else installing to a different location? Is it because the system is in Swedish, although I run it in English mode?

**Comment by alexbruy** [comment]
Please test with latest master.

**Comment by alexbruy** [comment]
Closed for the lack of feedback. Please reopen if necessary.
