### ISSUE TITLE
Make Vertex Tool selection similar to Select Feature(s) tool

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28395]
Author Name: **Man Andman** (@Vitruvius21)
Original Redmine Issue: [20575](https://issues.qgis.org/issues/20575)

Redmine category:editing

---
At the moment, in QGIS, Vertex Tool can select by clicking on vertex or by rectangle area. I think it will great addition if Vertex Tool will be able to select by freehand or by polygon like in Selection Tool.

**Comment by uclaros** [comment]
This was implemented in #42250
