### ISSUE TITLE
Save SQL as file

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28396]
Author Name: **Tomasz Rychlicki** (@miszokienka)
Original Redmine Issue: [20576](https://issues.qgis.org/issues/20576)
Affected QGIS version: 3.5(master)
Redmine category:db_manager

---
While saving SQL query as a file it saves not to '.sql' file but to '.sql,.sql' file. It also adds a empty line in every even line of the created file. I think it would be better if it would not add those empty lines.

**Comment by alexbruy** [comment]
Works for me in master. Please retest.

**Comment by miszokienka** [comment]
Still saving file as *.sql,.sql

**Comment by alexbruy** [comment]
Please provide exact steps to reproduce the issue.

**Comment by miszokienka** [comment]
1. Go to DB Manager
2. Connect to PostGIS database
3. Input some SQL code
4. Click Save SQL as a file... (top right button)
5. Save the file
6. Check that the file has extension *.sql,.sql despite saving it as a *.sql file

**Comment by alexbruy** [comment]
Still not reproducible. Which QGIS version are you using and on which platform?

**Comment by miszokienka** [comment]
![image](https://user-images.githubusercontent.com/26738097/65490803-15078180-deae-11e9-8dd1-b1a43e9c2b2f.png)

**Comment by alexbruy** [comment]
I'm still unable to reproduce. Looks like local issue.

Can you retest with latest versions?

**Comment by miszokienka** [comment]
Seems like it's working properly now. It's saving *.sql files like it should.
