### ISSUE TITLE
Action Toggle Editing called from QPushButton starts looping

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28413]
Author Name: **Raul Sangonzalo** (Raul Sangonzalo)
Original Redmine Issue: [20593](https://issues.qgis.org/issues/20593)
Affected QGIS version: 3.4.1
Redmine category:editing

---
When _qgis.utils.iface.actionToggleEditing().trigger()_ is called from a QPushButton on a form to enable/disable editing it causes to loop.

1. Press QPushButton. First time it enables or disables the Editing Mode of that layer.
2. Press again, it runs it twice (as if it was pressed twice), so you get to the same point.
3. Press again, it runs 4 times. Again, 8 times, etc.

We discovered it actually does the same thing with startEditing(). It keeps looping exponentially every time you press it (checked with printing statements). You can also see it's enable/disabling on the QGIS interface!

On 3.2 it worked fine, so we think this is a glitch from this version.

**Comment by uclaros** [comment]
This can close. It is not reproducible and most probably caused by a user's code mistake in the first place.
