### ISSUE TITLE
MSSQL Invalid layer

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28427]
Author Name: **Zannis Kostalas** (Zannis Kostalas)
Original Redmine Issue: [20607](https://issues.qgis.org/issues/20607)
Affected QGIS version: 3.4.1
Redmine category:data_provider/mssql

---
The case:
On the same server, created an exact copy of a polygon table on a different db
SELECT * INTO db2.dbo.geom_table_copy FROM db1.dbo.geom_table 

While QGIS was reading the original table normally, when attempting to insert the copied table I would get
"WARNING    dbname='db2' host=www.myhost.com user='user' password='pwd' srid=4326 type=Polygon disableInvalidGeometryHandling='0' table="dbo"."geom_table_copy" (POLYGON) sql= is an invalid layer - not loaded"

The problem got solved when I populated the "sql" field on the table selection with a random, valid query, loaded the table and then deleted the query. As it seems, for some reason, when creating the connection to the 2nd db, that field, enev though appearing blank, was populated in the background with an invalid expression (that's my best guess at least)

Once you know how to fix it it's easy but this was bugging me for close to 6 months now and no solution exists on the internet

**Comment by alexbruy** [comment]
Is this still an issue with latest master?
