### ISSUE TITLE
'\n' button in function editor generates invalid code

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28426]
Author Name: **Patrick Dunford** (@enzedrailmaps)
Original Redmine Issue: [20606](https://issues.qgis.org/issues/20606)
Affected QGIS version: 3.4.1
Redmine category:field_calculator

---
In the function editor for captions you have a button clearly labelled '\n' but when you press it, it outputs '\&n'. The difference is the former is acceptable and the latter is invalid as far as the function editor is concerned.

**Comment by alexbruy** [comment]
Works for me on master. Pressing button inserts correct string `'\n'`. Preview is empty as it should be.

**Comment by alexbruy** [comment]
Closed for the lack of feedback.
