### ISSUE TITLE
Raster calculator produces empty results layer and no error message if input layer is one that has been renamed in QGIS layers panel

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28421]
Author Name: **Alister Hood** (@AlisterH)
Original Redmine Issue: [20601](https://issues.qgis.org/issues/20601)
Affected QGIS version: 3.4.1
Redmine category:processing/qgis
Assignee: Alessandro Pasotti

---
Right click on a layer in the QGIS "Layers" panel, and rename it.
Try to use it in the raster calculator (i.e. the one listed under QGIS raster analysis in processing).  It will not work, but there will be no indication there has been an error (you will just get an empty result layer).
This is bad, because it appears to run successfully, but gives the wrong results.

Maybe this is related to the limitation in the implementation that prevents the raster calculator from listing and using more than one layer with the same name.

**Comment by AlisterH** [comment]
It seems this was fixed at some point.
I can't close these tickets that came over from redmine, can someone else?
