### ISSUE TITLE
SLD load problem

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28439]
Author Name: **Eduardo Martín** (Eduardo Martín)
Original Redmine Issue: [20619](https://issues.qgis.org/issues/20619)
Affected QGIS version: 3.4.1
Redmine category:symbology

---
I use a SLD file to define styles over a polygon layer, but the results are different depending on the QGIS version: 2.18.25 and 3.4.1 don't work (missing layer cause of styling), 2.18.4 and 3.2.3 work.
Even, I tried to create a SLD on 2.18.25 and load over the same layer, the styling doesn't work. 

I attached gif example of a success and a failed cases.

Thanks for your time and help developping this great software!
Regards :)

---

- [SLD_2_18_25.zip](https://issues.qgis.org/attachments/download/13840/SLD_2_18_25.zip) (Eduardo Martín)
- [SLD_3.2.3.gif](https://issues.qgis.org/attachments/download/13841/SLD_3.2.3.gif) (Eduardo Martín)

**Comment by alexbruy** [comment]
Closed for the lack of feedback
