### ISSUE TITLE
Creating PostGIS in Browser Panel

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28436]
Author Name: **Saber Razmjooei** (@saberraz)
Original Redmine Issue: [20616](https://issues.qgis.org/issues/20616)

Redmine category:browser

---
Currently, it is possible to create file-based vectors (SHP, GPKG by right-clicking on folders in Browser panel.

But right-clicking schemas, doesn't have an option to create PostGIS layer.

**Comment by alexbruy** [comment]
Implemented in master.
