### ISSUE TITLE
Mac OS QGis installer cannot find python 3.6

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28435]
Author Name: **Vladislav Mikhailov** (Vladislav Mikhailov)
Original Redmine Issue: [20615](https://issues.qgis.org/issues/20615)
Affected QGIS version: 3.4.1
Redmine category:mac_os_specific
Assignee: Denis Rouzaud

---
When I try install QGis, see message about "QGIS requires Python 3.6.". But I already have python 3.6.5

QGis version: 3.4.1 (new LTR)
MacBook Pro (Retina, 13-inch, Early 2015)
2,7 GHz Intel Core i5
MacOS High Sierra (10.13.3)
Python version 3.6.5

---

- [Снимок экрана 2018-11-24 в 0.09.29.png](https://issues.qgis.org/attachments/download/13838/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202018-11-24%20%D0%B2%200.09.29.png) (Vladislav Mikhailov)
- [Снимок экрана 2018-11-23 в 23.58.06.png](https://issues.qgis.org/attachments/download/13839/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202018-11-23%20%D0%B2%2023.58.06.png) (Vladislav Mikhailov)

**Comment by gioman** [comment]
Closing for lack of feedback, no issues with the latest installers on Catalina.
