### ISSUE TITLE
refreshing of a layer (raster) doesn't work after georeferencing

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28437]
Author Name: **Gabriela Osaci Costache** (Gabriela Osaci Costache)
Original Redmine Issue: [20617](https://issues.qgis.org/issues/20617)
Affected QGIS version: 3.4.1
Redmine category:c++_plugins/georeferencer

---

Steps:

1. load an already geo-referenced map
2. open the georeferencer and load the map to be georeferenced and choose/set some GCP points
3. save the file with the points
4. choose the transformation settings and select "Load in QGIS when done".
5. press "Start georeferencing", result map is loaded. *Keep the georeferencer dialog open*

Up to this point everything goes smoothly, as always, up to version 2.18.25 included

7. add some new GCPs or modify existing ones
8. set the transformation settings with the option "Load in QGIS when done" NOT active, set the output name the same as the previous georeferencing operation, effectively overwriting the previous output
9. press "Start georeferencing".

At this point in QGIS 2.18 using "Refresh (F5)" will effectively show the result of the second georeferencing operation while in QGIS 3 it continues to show the first result.

File (zip): https://drive.google.com/file/d/1c4q_jP9rKS0IQ_2olAI6qPb4QJFfSnHz/view?usp=sharing

---

- [cattura_QGIS_341_bis.png](https://issues.qgis.org/attachments/download/13849/cattura_QGIS_341_bis.png) (Gabriela Osaci Costache)

**Comment by gioman** [comment]
Seems fixed in recent releases.
