### ISSUE TITLE
Vertex Tool: Please make the "Current Layer" the default

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28457]
Author Name: **Burghardt Scholle** (Burghardt Scholle)
Original Redmine Issue: [20637](https://issues.qgis.org/issues/20637)
Affected QGIS version: 3.5(master)
Redmine category:editing

---
If you toggle to the edit mode, the option "all layers" is switched on by default at the moment. With this setting, both clueless and experienced users can very quickly ruin their data. How fast did you accidentally move or delete nodes from other layers in this setting? Therefore, IMHO the default setting of "current layer" in the vertex tool is preferable.

**Comment by suricactus** [comment]
I do agree with this, it feels buggy. It is very confusing to select a "Decimal number" but to store only integers by default.

I can apply the changes, I just need an idea of sensible defaults? Personally I think having 10 digits on both sides of the decimal point makes much more sense.

**Comment by uclaros** [comment]
> I do agree with this, it feels buggy. It is very confusing to select a "Decimal number" but to store only integers by default.
> 
> I can apply the changes, I just need an idea of sensible defaults? Personally I think having 10 digits on both sides of the decimal point makes much more sense.

This probably meant to reply to another issue?

**Comment by uclaros** [comment]
The vertex tool button on the toolbar remembers the last tool used (*all layers* vs *current layer*) which is rational. So the reported issue only applies to the very first time the user selects the tool. This could probably close, or at least have *Bug* removed.

**Comment by suricactus** [comment]
Does it remember per installation, per project or per layer? If it is per installation, this can be closed for sure.

**Comment by uclaros** [comment]
It's stored in settings `"UI/defaultVertexTool"`, so it's per profile. It defaults to *active layer* initially until the user selects the *all layers*. From then on the last selected tool is used.

**Comment by suricactus** [comment]
That's good. But changing the default is would be nice for newcomers indeed.

**Comment by uclaros** [comment]
But the default *is* the active layer mode! We could skip saving the setting and have it always return the *active layer* and force the user to have to click the drop-down arrow in order to select *all layers*, but that will not be good for those that mostly use the second option. Another option would be to add separate buttons. 
IMHO all this is kind of overkill. Feature Rubber bands are highlighted when hovered with this tool. Same thing for selected vertices when dragging. It is quite clear to the user what is going to be modified! That makes me think the OP confused vertex tool - all vertices with topological editing.

**Comment by suricactus** [comment]
You are right, I just checked the code. Better to close this issue as irrelevant.

BTW, this is the commit when these two actions were added. https://github.com/qgis/QGIS/commit/c67d09c6dc296bae11e932df298fae8f5eb126da

**Comment by lbartoletti** [comment]
Active layer is already the default mode. according to @suricactus comment I close this issue.
