### ISSUE TITLE
Autosender for crash reports

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28465]
Author Name: **Andrew Shanin** (Andrew Shanin)
Original Redmine Issue: [20645](https://issues.qgis.org/issues/20645)

Redmine category:unknown

---
Add autosender please. Add more information and tracelogs.

---

Related issue(s): #29839 (duplicates)
Redmine related issue(s): [22025](https://issues.qgis.org/issues/22025)

---

**Comment by alexbruy** [comment]
Duplicates #26119.
