### ISSUE TITLE
Change of language only works partially

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28474]
Author Name: **Lars Ellebjerg** (@Ellebjerg)
Original Redmine Issue: [20654](https://issues.qgis.org/issues/20654)
Affected QGIS version: 3.4.1
Redmine category:translations_and_international
Assignee: QGIS Translation Team

---
I have changed my QGIS language settings from system locale (Danish) to American English i QGIS 3.0. This has worked fine except for the Vector menu, which has split in two. I now have 
1) a Vector menu containing 'Coordinate Capture', 'Check Geometries', 'DXF Import/Convert', 'Topology Checker' and 'Geoprocessing Tools'
2) a Vektor menu containing 'Geoprocessing-værktøjer' (Geoprocessing Tools), 'Geometri-værktøjer' (Geometry Tools), 'Analyse-værktøjer' (Analysis Tools), 'Datastyringsværktøjer' (Data Management Tools) and 'Forskningsværktøjer' (Research Tools)

The split menu has moved along to ver. 3.2, 3.4.1, 3.4.2 and is now also there in 2.18.26. Is there a way to change it to one all English menu without a complete reinstall of QGIS?

---

Related issue(s): #26093 (relates)
Redmine related issue(s): [18202](https://issues.qgis.org/issues/18202)

---

**Comment by HusseinKabbout** [comment]
I am still encountering this issue with QGIS 3.10.7-A Coruña. To reproduce you only need to click on "Reset to defaults" button in "Settings -> Options -> Processing -> Menus" and then all languages will have two different vector menus. (except the language that was active when you pressed the button or the language that has the same translation for the vector menu)
