### ISSUE TITLE
Incorrect WMS/Mapserver Extent after Upgrade

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28471]
Author Name: **Daniel McCullock** (Daniel McCullock)
Original Redmine Issue: [20651](https://issues.qgis.org/issues/20651)
Affected QGIS version: 3.4.1
Redmine category:web_services_clients/arcgis
Assignee: Sandro Mani

---
I recently Upgraded from version 3.0.1 to 3.4.1 and have noticed an issue with a WMS layer I access.
The same issue occurs when the service is added as a MapServer Layer.
Previously the extent was retrieved as per that which the service page describes but now it requests a slightly smaller extent.
I have checked other services from the same and other servers and they are functioning correctly.
The WMS can be accessed @ https://maps.six.nsw.gov.au/arcgis/services/public/NSW_Base_Map/MapServer/WMSServer?request=GetCapabilities&service=WMS

**Comment by Pedro-Murteira** [comment]
I'm not able to replicate this issue on QGIS 3.22.3.
