### ISSUE TITLE
Field calc - save and load expressions files

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28478]
Author Name: **salvatore fiandaca** (salvatore fiandaca)
Original Redmine Issue: [20658](https://issues.qgis.org/issues/20658)

Redmine category:field_calculator

---
Add the buttons to save and import the most important expressions, to save time.
The recent group stores the first 20 expressions, but they always change.

https://github.com/qgis/QGIS-Enhancement-Proposals/issues/135

---

- [Img4.png](https://issues.qgis.org/attachments/download/13859/Img4.png) (salvatore fiandaca)

**Comment by suricactus** [comment]
Saving expressions is already there in QGIS 3.12.

**Comment by suricactus** [comment]
close
