### ISSUE TITLE
Switching between selected features when they overlap

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28488]
Author Name: **Saber Razmjooei** (@saberraz)
Original Redmine Issue: [20668](https://issues.qgis.org/issues/20668)

Redmine category:map_tools

---
In some cases, there are several overlapping features, which makes selection or identifying a bit difficult.
In Mapinfo, you can hold CTRL and switch between those features (in single selection mode or identify tool).

**Comment by alexbruy** [comment]
Duplicates #24541.
