### ISSUE TITLE
Missing detached panels on hide

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28498]
Author Name: **Jesús López** (Jesús López)
Original Redmine Issue: [20678](https://issues.qgis.org/issues/20678)
Affected QGIS version: 3.4.4
Redmine category:osx_ui

---
After hide qgis (cmd+H) when you return to application any open detached panels disappear and have to reopen them manually.

**Comment by Pedro-Murteira** [comment]
I can no longer reproduce this issue on macOS. (QGIS 3.22.2.)
