### ISSUE TITLE
QGIS 3.4.2 Crash on Windows with multiple monitors

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28510]
Author Name: **al piszcz** (al piszcz)
Original Redmine Issue: [20690](https://issues.qgis.org/issues/20690)
Affected QGIS version: 3.4.2
Redmine category:gui

---
## User Feedback

Main Menu -> settngs -> OK

## Report Details

*Crash ID*: 619d9f0d20f01b8b66548edf4df2b0553bd64fbd

*Stack Trace*
```
GdiSetLastError :
TpReleaseTimer :
TpReleaseTimer :
RtlRegisterThreadWithCsrss :
TpSetWait :
RtlSetThreadWorkOnBehalfTicket :
BaseThreadInitThunk :
RtlUserThreadStart :

```

*QGIS Info*
QGIS Version: 3.4.2-Madeira
QGIS code revision: 22034aa070
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.3.2
Running against GDAL: 2.3.2

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.16299

**Comment by roya0045** [comment]
Is this still occuring?

**Comment by gioman** [comment]
Closing for lack of feedback.
