### ISSUE TITLE
3D objects (obj) eats up memory and turns computer unresponsive

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28512]
Author Name: **Klas Karlsson** (@klakar)
Original Redmine Issue: [20692](https://issues.qgis.org/issues/20692)
Affected QGIS version: 3.4.2
Redmine category:3d

---
Using "large" 3D objects to render a lot of points in 3D will start eat up memory (attached image).

When all physical RAM is consumed, it continues with virtual memory. When this also is consumed the computer becomes unresponsive.

I'm using a 6 Mb *.obj file from https://free3d.com/3d-models/ and a point layer with just 500 points. Turning textures "off" helps some, but doesn't fix the problem.

It's a bit of a "fringe" use case, but the software should not allow the computer to become unresponsive at least.

---

- [Skärmbild från 2018-12-01 14-35-57.png](https://issues.qgis.org/attachments/download/13890/Sk%C3%A4rmbild%20fr%C3%A5n%202018-12-01%2014-35-57.png) (Klas Karlsson)

**Comment by wonder-sk** [comment]
@klakar if you could post a test project that would be useful - thanks!

**Comment by klakar** [comment]
No! This problem is not as severe any longer.

**Comment by gioman** [comment]
> No! This problem is not as severe any longer.

@klakar can we close this then?

**Comment by klakar** [comment]
Close it.
