### ISSUE TITLE
Add option to filter by expression in Relation Reference widget

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28520]
Author Name: **Nikolay Lebedev** (Nikolay Lebedev)
Original Redmine Issue: [20700](https://issues.qgis.org/issues/20700)

Redmine category:forms

---
It would be nice to have an option to filter Relation Reference list by expression (like the one in Value Relation widget).
So you can filter available values by distance etc.

Currently, you can only set a chain of filtering fields, so you can narrow the list by other field values by hand, but there is no way to set a default value or expression for a filter.

**Comment by alexbruy** [comment]
Duplicates #23955.
