### ISSUE TITLE
qgis 3.4.2 crashes on Windows 8.1

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28523]
Author Name: **Giuliano Urgeghe** (Giuliano Urgeghe)
Original Redmine Issue: [20703](https://issues.qgis.org/issues/20703)
Affected QGIS version: 3.4.2
Redmine category:project_loading/saving

---
## User Feedback

I have crash when I choose the project to load!!!

## Report Details

*Crash ID*: 4db78da3a5772c90b16c535c8d0048190649cfee

*Stack Trace*
```
RtlFreeHeap :
free :
DllUnregisterServer :
DllUnregisterServer :
CoGetTreatAsClass :
CleanupTlsOleState :
CoGetTreatAsClass :
CoGetTreatAsClass :
CoGetTreatAsClass :
CoGetTreatAsClass :
CoGetTreatAsClass :
CoGetTreatAsClass :
CleanupTlsOleState :
CleanupTlsOleState :
CleanupTlsOleState :
StringFromGUID2 :
StringFromGUID2 :
SHBindToParent :
Ordinal866 :
AssocCreateForClasses :
SHCreateQueryCancelAutoPlayMoniker :
SHCreateQueryCancelAutoPlayMoniker :
SHCreateQueryCancelAutoPlayMoniker :
SHCreateQueryCancelAutoPlayMoniker :
SHAssocEnumHandlers :
Ordinal211 :
SHCreateDefaultExtractIcon :
SHGetItemFromObject :
SHEvaluateSystemCommandTemplate :
SHEvaluateSystemCommandTemplate :
ILFree :
DllCanUnloadNow :
RtlGetNtProductType :
RtlFreeUnicodeString :
BaseThreadInitThunk :
RtlUserThreadStart :

```

*QGIS Info*
QGIS Version: 3.4.2-Madeira
QGIS code revision: 22034aa070
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.3.2
Running against GDAL: 2.3.2

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.3.9600

**Comment by alexbruy** [comment]
Still true with latest versions?

**Comment by alexbruy** [comment]
Closed for the lack of feedback. Please reopen if necessary.
