### ISSUE TITLE
Crash when deleting data defined auxiliary storage configuration

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28539]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [20719](https://issues.qgis.org/issues/20719)
Affected QGIS version: 3.4.2
Redmine category:unknown

---
## User Feedback

While playing with the Data Storage capabilities of a point feature, I got a crash when I chose to delete the auxiliary storage DB. For precision, it was not the first time I opted to delete that DB; i have already deleted it in the session.

## Report Details

*Crash ID*: 8a10a9fdf261b9518e7feed3bdd25f437be4c9e9

*Stack Trace*
```
QgsFieldConstraints::QgsFieldConstraints :
QgsAttributesFormProperties::storeAttributeTypeDialog :
QgsAttributesFormProperties::apply :
QgsVectorLayerProperties::apply :
QMetaObject::activate :
QDialog::done :
QMetaObject::activate :
QDialogButtonBox::~QDialogButtonBox :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
QgisApp::showLayerProperties :
QgisApp::layerTreeViewDoubleClicked :
QMetaObject::activate :
QAbstractItemView::doubleClicked :
QTreeView::mouseDoubleClickEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

```

*QGIS Info*
QGIS Version: 3.4.2-Madeira
QGIS code revision: 22034aa070
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.3.2
Running against GDAL: 2.3.2

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by troopa81** [comment]
Do you know what you were doing before it crashes? In which parameter do you use an auxiliary storage field?

I try a few tests and fail to reproduce.

**Comment by DelazJ** [comment]
Euuhh... I'm not 100% sure but I think I was mainly playing (for docs purpose) with the label tools, trying to understand how they connect together and the fields created depending on changed properties. So creating/deleting/recreating auxiliary storage with various id fields and settings. Sorry for not being of great help, here.

**Comment by troopa81** [comment]
OK, I'll give a try with the label tool and auxiliary storage, see If I can make it crash

**Comment by roya0045** [comment]
Never had a crash whle removing auxiliary data. Maybe it was specific to 3.4?

**Comment by gioman** [comment]
@DelazJ is this still valid?

**Comment by DelazJ** [comment]
@gioman honestly I don't know, do not remember what actually triggers the crash and don't have bandwidth to check again. Unless @troopa81 still wants to give it a try, we probably should close this...

**Comment by troopa81** [comment]
I try a bit but never managed to make it crash. I think we can close this issue
