### ISSUE TITLE
Crash at QgsApplication.initQgis() on Mac

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28532]
Author Name: **Ikuo Yamaga** (Ikuo Yamaga)
Original Redmine Issue: [20712](https://issues.qgis.org/issues/20712)
Affected QGIS version: 3.5(master)
Redmine category:python_bindings_/_sipify
Assignee: Peter Petrik

---
Simple application crushed by signal 11.
I attached  crush report of Mac.

I go back to QGIS3.2.2 Bonn. It's OK, no crush.

### source:  "The PyGIS Programmer's Guide"

from PyQt5.QtWidgets import QApplication
from qgis.core import QgsApplication

from ourmainwindow_3 import OurMainWindow

app = QApplication([])
1. set up QGIS
##QgsApplication.setPrefixPath("/Users/gsherman/apps/QGIS.app/Contents/MacOS", True)
QgsApplication.setPrefixPath("/Applications/QGIS3.app/Contents/MacOS", True)
QgsApplication.initQgis()

1. set the main window and show it
mw = OurMainWindow()
mw.show()

app.exec_()

1. "delete" our main window
mw = None
1. clean up QGIS
QgsApplication.exitQgis()

### end of source

---

- [qgis362crush.txt](https://issues.qgis.org/attachments/download/13897/qgis362crush.txt) (Ikuo Yamaga)
- [Qgis344crush.txt](https://issues.qgis.org/attachments/download/14223/Qgis344crush.txt) (Ikuo Yamaga)
- [QGIS344crush.png](https://issues.qgis.org/attachments/download/14224/QGIS344crush.png) (Ikuo Yamaga)
- [QGIS322runing.png](https://issues.qgis.org/attachments/download/14225/QGIS322runing.png) (Ikuo Yamaga)
- [our_app_3.py](https://issues.qgis.org/attachments/download/14226/our_app_3.py) (Ikuo Yamaga)

**Comment by gioman** [comment]
> I can replicate the issue when I drag 'n' drop the .py file to QGIS. running individual commands is OK

@PeterPetrik I can't replicate or I don't understand the necessary steps to. What is the status of this issue?
