### ISSUE TITLE
Auxiliary storage rotation or offset fields for symbols are visible by default while labels are not

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28548]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [20728](https://issues.qgis.org/issues/20728)
Affected QGIS version: 3.4.2
Redmine category:edit_widget

---
According to "documentation":https://docs.qgis.org/3.4/en/docs/user_manual/working_with_vector/vector_properties.html#attribute-table-and-widgets, 
> Once created, auxiliary fields may be edited through the attribute table. However, there’s some subtlety about widgets of auxiliary fields.
>
> For example, auxiliary fields which may be edited through an external tool are not visible in the attribute table. This way, as the Rotation may be edited through "Change Label" or "Rotate Label", the auxiliary widget is Hidden by default (see Edit widgets).

This description applies perfectly to all the concerned label properties but not to the symbols rotation or offset that can be changed with dedicated "symbol offset" and "symbol rotation" tools: their widgets are visible in forms and attribute table by default.

**Comment by gioman** [comment]
Still true in recent releases.
