### ISSUE TITLE
Netcdf mesh aligned, or not?

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28550]
Author Name: **Richard Duivenvoorde** (@rduivenvoorde)
Original Redmine Issue: [20730](https://issues.qgis.org/issues/20730)
Affected QGIS version: 3.5(master)
Redmine category:data_provider/mdal
Assignee: Peter Petrik

---
I created a small 7x3 cell netcdf with a python script: test.nc (attached)

Loaded in QGIS3 as gdal raster you see 7x3 cells
Loaded as netcdf in Geoserver and served as wms you see 7x3 cells
If you load this small set as Mesh in QGIS3 you see 6x2 cells.
In the attached 'mesh.png' those three layers are all visible.

Note that I'm no netcdf expert! So I'm 100% sure that this IS actually a problem. 
I think all depends on the definition of a mesh: is it the middle point of grid cells or not?

When loaded in Panoply netcdf viewer: https://www.giss.nasa.gov/tools/panoply/
you also can see both situations see attached screenies:
panoply_interpolate.png zoomed in to test.png and checkbox 'interpolate' checked
panoplyNOinterpolate.png: checkbox 'interpolate' UNchecked.

So my feeling is that it depends on the interpretation of a mesh/grid and it's visualisation.

Maybe some netcdf guru's can have a say about this?

Peter Petrik asked me to create this issue to further investigate.

---

- [mesh.png](https://issues.qgis.org/attachments/download/13912/mesh.png) (Richard Duivenvoorde)
- [test.nc](https://issues.qgis.org/attachments/download/13913/test.nc) (Richard Duivenvoorde)
- [panoplyNOinterpolate.png](https://issues.qgis.org/attachments/download/13914/panoplyNOinterpolate.png) (Richard Duivenvoorde)
- [panoply_interpolate.png](https://issues.qgis.org/attachments/download/13915/panoply_interpolate.png) (Richard Duivenvoorde)

**Comment by rduivenvoorde** [comment]
@PeterPetrik there is a user question related to this on the GDAL-dev mailing list:

https://lists.osgeo.org/pipermail/gdal-dev/2019-October/051014.html

**Comment by saberraz** [comment]
@rduivenvoorde currently we use gdal driver to read those types of netcdf (and also grib file) through mdal. This is not an ideal situation:

- mdal dependency on gdal (not a big deal)
- we are missing the point about unstructured grid, as gdal transforms netcdf and grib to regular raster (i.e. re-samples the data...hence they are no longer the "raw data").

Similar to UGRID netcdf, we should try and parse the files directly. It will avoid the issue you have reported and also gives more flexibility:
https://github.com/lutraconsulting/MDAL/issues/165

**Comment by PeterPetrik** [comment]
This should be fixed upstream with lutraconsulting/MDAL#165
