### ISSUE TITLE
Show Absolute Time when viewing an Mesh in QGIS

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28551]
Author Name: **Richard Duivenvoorde** (@rduivenvoorde)
Original Redmine Issue: [20731](https://issues.qgis.org/issues/20731)

Redmine category:mesh_layers
Assignee: Peter Petrik

---
IN QGIS 2.18 when using the Crayfish plugin and loading a netcdf (which defines it time relative to some offset point) there is an option to display the "Absolute Time". (in contrast to "Relative Time") see screenshot.

In QGIS 3 there is only the relative time.

It would be nice to have the Crayfish option also in QGIS3.

Note for others: in netcdf for example you define your timeslices as "Years from 1 jan 2010" for example. 
You then see 1,2,3,4 for data 2011-2014.

---

- [absolutetime.png](https://issues.qgis.org/attachments/download/13916/absolutetime.png) (Richard Duivenvoorde)

**Comment by pcav** [comment]
Thanks for the improvement. A couple of further improvements:
* the default should be the current time rather than 2019-01-01
* the time widget only allows setup of day, not time.

**Comment by gioman** [comment]
> Thanks for the improvement. A couple of further improvements:

please file a separate ticket.
