### ISSUE TITLE
Qgis Madeira closing with Pendriveou external HD

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28555]
Author Name: **Diego Ricardo Medeiros de Lima** (Diego Ricardo Medeiros de Lima)
Original Redmine Issue: [20735](https://issues.qgis.org/issues/20735)
Affected QGIS version: 3.4.2
Redmine category:windows_package

---
My version 3.4+ Qgis (x64) every time I insert or eject a USB stick or external hard drive the program crashes and closes everything ...
Anyone else with this problem?

**Comment by gioman** [comment]
This has been solved long ago.
