### ISSUE TITLE
Saving project on start up

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28561]
Author Name: **Saber Razmjooei** (@saberraz)
Original Redmine Issue: [20741](https://issues.qgis.org/issues/20741)
Affected QGIS version: 3.6.0
Redmine category:project_loading/saving

---
All the QGIS3.5 latest betas always ask for saving a project after opening when we still are in the recent projects list:
https://www.dropbox.com/s/a39wv03sqk2amg7/QGIS8_5_OPEN_ERROR.mp4?dl=0

Fore reference seel:
https://github.com/lutraconsulting/qgis-mac-packager/issues/42

**Comment by PeterPetrik** [comment]
cannot reproduce and both dropbox link and github issue is not accessible anymore
