### ISSUE TITLE
WKT output is wrong for EMPTY geometries

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28573]
Author Name: **Johannes Kroeger** (Johannes Kroeger)
Original Redmine Issue: [20753](https://issues.qgis.org/issues/20753)
Affected QGIS version: 3.5(master)
Redmine category:geometry

---
QGIS geometries' asWkt() method returns "GeometryType ()" or simple an empty string '' instead of "GeometryType EMPTY" for empty geometries.

http://www.opengeospatial.org/standards/sfa defines for example for a POINT:

```
<empty set> ::= EMPTY

<point text> ::= <empty set> | <left paren> <point> <right
paren>

```

From my understanding this means that an empty Point would be represented as "POINT EMPTY".
QGIS however represents it as empty string ''.

```
>>> p = QgsGeometry.fromWkt('POINT EMPTY')
>>> p.isEmpty()
True
>>> p.asWkt()
''

```

**Comment by haubourg** [comment]
test ping for Loïc

**Comment by lbartoletti** [comment]
Fixed in https://github.com/qgis/QGIS/pull/9645
