### ISSUE TITLE
fromWKT should fail if neither EMPTY or coordinates are supplied

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28574]
Author Name: **Johannes Kroeger** (Johannes Kroeger)
Original Redmine Issue: [20754](https://issues.qgis.org/issues/20754)
Affected QGIS version: 3.5(master)
Redmine category:geometry

---
QGIS allows geometries to be created using a string like "GeometryType" without either specifying the coordinates or EMPTY.

http://www.opengeospatial.org/standards/sfa defines for example for a POINT:

```
<empty set> ::= EMPTY

<point text> ::= <empty set> | <left paren> <point> <right
paren>

```

So "Point" would not be ok. QGIS however, does allow and produce weird stuff...

```
>>> for type in "POINT", "LINESTRING", "POLYGON", "GEOMETRYCOLLECTION", "MULTIPOINT":
>>>   g = QgsGeometry.fromWkt(type)
>>>   print(type)
>>>   print(g)
>>>   print(g.asWkt())
POINT
<QgsGeometry: >

LINESTRING
<QgsGeometry: LineString ()>
LineString ()
POLYGON
<QgsGeometry: >

GEOMETRYCOLLECTION
<QgsGeometry: GeometryCollection ()>
GeometryCollection ()
MULTIPOINT
<QgsGeometry: MultiPoint ()>
MultiPoint ()

```

Related #22604

**Comment by lbartoletti** [comment]
Fixed in https://github.com/qgis/QGIS/pull/9645
