### ISSUE TITLE
QGIS freezes on loading message

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28593]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [20773](https://issues.qgis.org/issues/20773)
Affected QGIS version: 3.4.2
Redmine category:map_canvas

---
Now that the "identify features" freeze has gone away, it's the "loading file" report message that decides to block the project closure. Unable to close properly the project file or cancel the rendering. However afaict the tools seem to work, map canvas is responsive.
Issue occurs only when you want to close QGIS.

---

- [canvasfreeze.PNG](https://issues.qgis.org/attachments/download/13930/canvasfreeze.PNG) (Harrissou Santanna)

**Comment by gioman** [comment]
@DelazJ is this issue still a thing?

**Comment by DelazJ** [comment]
I barely used QGIS on Windows these last months so can't tell. Maybe should we close...

**Comment by gioman** [comment]
> I barely used QGIS on Windows these last months so can't tell. Maybe should we close...

@DelazJ I use Windows frequently and never seen this issue at very least recently. Reopen if you see it again.
