### ISSUE TITLE
QGIS Crash - Creating 3D Map View

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28597]
Author Name: **Eric Berkowitz** (@ericwberkowitz)
Original Redmine Issue: [20777](https://issues.qgis.org/issues/20777)
Affected QGIS version: 3.4.2
Redmine category:3d

---
Crash ID: 721c1860e106c152d28634ec7795dac22de8d6e2

Stack Trace

DumpRegistryKeyDefinitions :
DumpRegistryKeyDefinitions :
DumpRegistryKeyDefinitions :
DumpRegistryKeyDefinitions :
DrvPresentBuffers :
wglCopyContext :
DrvShareLists :
DrvSwapBuffers :
wglSwapBuffers :
SwapBuffers :
QOpenGLContext::swapBuffers :
Qt3DRender::Render::NodeManagers::environmentLightManager :
Qt3DRender::Render::Renderer::doRender :
Qt3DRender::Render::Renderer::render :
Qt3DRender::Render::AbstractRenderer::~AbstractRenderer :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.4.2-Madeira
QGIS code revision: 22034aa070
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.3.2
Running against GDAL: 2.3.2

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by wonder-sk** [comment]
@ericwberkowitz please could you add more details? What data do you use? Ideally add a test project where it is possible to reproduce the crash.

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
