### ISSUE TITLE
Symmetric classification collapsible group in symbology --> graduated renderer behaves weirdly

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28596]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [20776](https://issues.qgis.org/issues/20776)
Affected QGIS version: 3.5(master)
Redmine category:gui

---
Vector layer properties --> graduated symbology
At the bottom of the dialog, check uncheck the symmetric classification group box combined with the Mode option and you get sometimes a group with both text edit and combobox visible while they are mutually exclusive.
https://github.com/qgis/QGIS/pull/8290 should fix (though untested)

---

- [symmetric_classif.png](https://issues.qgis.org/attachments/download/13935/symmetric_classif.png) (Harrissou Santanna)

**Comment by nyalldawson** [comment]
Fixed in latest releases
