### ISSUE TITLE
QGIS crashes computer due to lack of memory when "Scan for contents in compressed files" is set to "yes"

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28610]
Author Name: **Harry Clarke** (@HarryEClarke)
Original Redmine Issue: [20790](https://issues.qgis.org/issues/20790)
Affected QGIS version: 3.5(master)
Redmine category:browser

---
Whilst browsing a local file folder which contains a number of sub-folders and zip files using the Browser widget, QGIS does not open the folder but displays a blue moving circle.

Using Microsoft Resource Monitor, QGIS was observed to start to consume all memory resources. If QGIS Desktop is not exited, this will result in a fatal crash of the computer (blue screen), due to the lack of memory.

The error is repeatable for this particular folder. There is no problem viewing the folder with Microsoft File Explorer.
However, other folders can be browsed normally.

**Comment by Pedro-Murteira** [comment]
I'm not being able to reproduce a crash here on QGIS 3.22.4 and 3.24.0. @HarryEClarke, Hello, did this issue happen again in more recent versions?
