### ISSUE TITLE
Edit line  make the project crash

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28612]
Author Name: **Marion S** (Marion S)
Original Redmine Issue: [20792](https://issues.qgis.org/issues/20792)
Affected QGIS version: 3.4.2
Redmine category:editing

---
Good afternoon 

I am doing a project for one of my class and for some reason the "edit line" ( I have the French version so I don't know the actual name) doesn't work. I am in edit mode and when I click the button it starts charging then the project doesn't answer and the only thing I can do is to close it. 
I don't really know what to do.

**Comment by roya0045** [comment]
Still valid?

**Comment by alexbruy** [comment]
Closing for the lack of feedback. Please reopen if necessary.
