### ISSUE TITLE
On the fly geometry validation doesn't work and causes QGIS to not respond

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28611]
Author Name: **Antonio Viscomi** (@Antoviscomi)
Original Redmine Issue: [20791](https://issues.qgis.org/issues/20791)
Affected QGIS version: 3.5(master)
Redmine category:geometry

---
I attached 2screencasts here, data and project are attached to #20789

---

- [Topology21.mp4](https://issues.qgis.org/attachments/download/13953/Topology21.mp4) (Antonio Viscomi)
- [Topology22.mp4](https://issues.qgis.org/attachments/download/13954/Topology22.mp4) (Antonio Viscomi)

---

Related issue(s): #28609 (duplicates)
Redmine related issue(s): [20789](https://issues.qgis.org/issues/20789)

---

**Comment by gioman** [comment]
@Antoviscomi works fine on the latest master.

**Comment by Antoviscomi** [comment]
@gioman I'm Glad to Know that, In future works I'll use It. Many thanks for your work
