### ISSUE TITLE
Field format changed when performing save features as... 

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28613]
Author Name: **KL Higgins** (KL Higgins)
Original Redmine Issue: [20793](https://issues.qgis.org/issues/20793)
Affected QGIS version: 3.4.2
Redmine category:attribute_table

---
I have recently switched from QGIS 3.0.1 to QGIS 3.4.2. I have found that field format is lost when doing export... save features as.. and letting the geometry type as automatic. However, if I specifically select the geometry type (e.g. polygon), the field formatting is conserved.  For example, a field with length of 12 and precision of 2 in the original file gets attributed a value of 23 length and precision 15 in the new file. For another field, length of a string field is increased from 5 to 80.

**Comment by nyalldawson** [comment]
There's not enough information here to do anything with this report -- e.g. it doesn't specify the original layer type or what format the layer has been saved into.
