### ISSUE TITLE
Advanced digitizing keeps position of removed vertex

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28637]
Author Name: **Antoine Lafranchis** (@alafr)
Original Redmine Issue: [20818](https://issues.qgis.org/issues/20818)
Affected QGIS version: 3.4.2
Redmine category:digitising

---
If I draw a linear feature (LineString) with advanced digitizing panel, and I undo a vertex with the Backspace key, the next vertex is still calculated relatively to the deleted one.

---

- [Qgis deleted vertex.png](https://issues.qgis.org/attachments/download/13980/Qgis%20deleted%20vertex.png) (Antoine Lafranchis)

**Comment by 3nids** [comment]
ping @olivierdalang did you solve this already?

**Comment by olivierdalang** [comment]
@3nids Yes : https://github.com/qgis/QGIS/pull/30079 (hadn't seen this issue)
