### ISSUE TITLE
Panoramic 3d maps (make field of view parametrable)

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28638]
Author Name: **Antoine Lafranchis** (@alafr)
Original Redmine Issue: [20819](https://issues.qgis.org/issues/20819)

Redmine category:3d

---
Currently the field of view in 3D maps seems fixed to 45 degrees (https://github.com/qgis/QGIS/blob/master/src/3d/qgs3dmapscene.cpp#L72).
It would be great to support changing the field of view, to allow creating panoramic views (up to 360°) around a point (in 3D Map View and in 3D Map layout item).
Thanks

**Comment by wonder-sk** [comment]
This has been added in https://github.com/qgis/QGIS/pull/9073
