### ISSUE TITLE
Representation for NULL values inconsistent use/display

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28643]
Author Name: **Björn Harrtell** (Björn Harrtell)
Original Redmine Issue: [20824](https://issues.qgis.org/issues/20824)
Affected QGIS version: 3.4.0
Redmine category:attribute_table

---
The setting for Representation for NULL values doesn't appear to be consistently respected.

In both attribute grid (unless focused on an editable cell) and identify result dialog NULL values are displayed as empty strings.

**Comment by alexbruy** [comment]
Related to #16137

**Comment by Andrey-VI** [comment]
For me this issue first appeared in version 3.10.2 (64-bit).

Sample dataset and qgis project file to reproduce the behavior: [testcase.zip](https://github.com/qgis/QGIS/files/4132468/testcase.zip)

Attribute table:
![Attribute_table](https://user-images.githubusercontent.com/1121499/73424409-c8422480-433f-11ea-9b26-c75cc1a016a8.PNG)
![Identify](https://user-images.githubusercontent.com/1121499/73424416-ced09c00-433f-11ea-86b9-74afb3ddf89d.PNG)

**QGIS and OS versions**
QGIS version 3.10.2-A Coruсa
QGIS code revision 616ad4531b
OS Version Debian GNU/Linux 10 (buster)

**Comment by Andrey-VI** [comment]
Add new feature to the testcase and open 'Edit feature form…':
![Edit_feature](https://user-images.githubusercontent.com/1121499/73433254-7a381b80-4355-11ea-95bd-a5d43177d974.PNG)

**Comment by elpaso** [comment]
Broken by https://github.com/qgis/QGIS/pull/33660

Fun facts:
```
QVariant(0.0) == QVariant(QVariant.Double)
True
```

**Comment by gioman** [comment]
@troopa81 fyi

**Comment by elpaso** [comment]
May be fixed by https://github.com/qgis/QGIS/pull/34152 but I still need to check if that's the case.
