### ISSUE TITLE
Support supplying open options for OGR in UI as an advanced setting

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28644]
Author Name: **Björn Harrtell** (Björn Harrtell)
Original Redmine Issue: [20825](https://issues.qgis.org/issues/20825)

Redmine category:data_provider/ogr

---
I've seen requests for this before (fx. http://osgeo-org.1560.x6.nabble.com/gdal-dev-GDAL-way-to-set-open-options-in-QGIS-td5354454.html)

In my case I would like to be able to control the behaviour of the GML driver.

**Comment by alexbruy** [comment]
Duplicates #18347.

**Comment by heidivanparys** [comment]
This has been fixed it seems. I don't from which version, but in 3.16.3 I get the following:

![image](https://user-images.githubusercontent.com/11427611/105365364-75bbe100-5bfe-11eb-875f-c081274e95d2.png)
