### ISSUE TITLE
Add options to draw label on the beginning or the end of a line

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28666]
Author Name: **Regis Haubourg** (@haubourg)
Original Redmine Issue: [20847](https://issues.qgis.org/issues/20847)

Redmine category:labelling

---
I encountered this need for the first time today. 
It matches this question. https://gis.stackexchange.com/questions/207736/how-to-label-the-start-end-of-the-line-in-qgis
It show a list of options that would make a lot of sense for us in QGIS. 

(note: looking for supporters to do that) 

---

- [arcgis_labelin_line_options.jpg](https://issues.qgis.org/attachments/download/13999/arcgis_labelin_line_options.jpg) (Regis Haubourg)
- [lines.png](https://issues.qgis.org/attachments/download/14011/lines.png) (Nyall Dawson)
- [example.jpg](https://issues.qgis.org/attachments/download/14533/example.jpg) (Alexey T)

**Comment by pjshelton** [comment]
This can be closed out as the North Road update to QGIS 3.16 adds this functionality.
https://north-road.com/2020/09/03/line-label-placement-our-gift-to-the-qgis-community/
