### ISSUE TITLE
Issue exporting raster layer to Geopackage

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28667]
Author Name: **Yineth Castiblanco** (Yineth Castiblanco)
Original Redmine Issue: [20848](https://issues.qgis.org/issues/20848)
Affected QGIS version: 3.4.5
Redmine category:rasters
Assignee: Alessandro Pasotti

---
I have a couple of issues when I try to export a Raster Layer into a GeoPackage format through export/Save as...

* First, the message "The layer HYP already exists ......" (attached "SaveRasterLayer.jpg")
* Second, I have this messages, the first one as CRITICAL, the second one as SUCCESSFUL (But in the Geopackage, the layer doesn´t exists)

Text of the issue in message console:

> 2018-12-19T15:06:29     CRITICAL    Fuente de datos no admitida : GPKG:C:\Users...\CapasGeopackage.gpkg:HYP no es un origen de datos ráster admitido
             Cannot find table 'HYP' in GeoPackage dataset
2018-12-19T15:06:29     SUCCESS    Capa exportada : La capa ráster se ha guardado correctamente en C:\Users\...\CapasGeopackage.gpkg

There are one way to export it or store it into a GeoPackage but + without additional options+ (the "save as" dialog has the additional options), the way to do that is just drag the layer and add it into a GeoPackage connection in "Navigator" tab.
*+But I want to add some additional options.+*

Externally I tried the next code lines through GDAL console:

> gdal_translate -co APPEND_SUBDATASET=YES -of GPKG /home/...../archivo.tif  /home/.../geopackageDB.gpkg

And I'd gotten successful export process.

+*The idea is get the export process thorugh QGIS interface.+*

My configuration information:

OS: Windows 10
QGIS: QGIS 3.4.1-Madeira
GDAL: GDAL 2.3.2
RAM: 16GB
Language: Spanish

---

- [SaveRasterLayer.jpg](https://issues.qgis.org/attachments/download/14000/SaveRasterLayer.jpg) (Yineth Castiblanco)

---

Related issue(s): #25822 (relates)
Redmine related issue(s): [17926](https://issues.qgis.org/issues/17926)

---

**Comment by kannes** [comment]
Is this fixed or not? :)

**Comment by elpaso** [comment]
Yes
