### ISSUE TITLE
Node editor as it works in 2.*

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28669]
Author Name: **Marc-André Saia** (Marc-André Saia)
Original Redmine Issue: [20850](https://issues.qgis.org/issues/20850)

Redmine category:digitising

---
Hi

Versions 3 of Qgis and beyond use a new method of editing nodes that can be confusing for anyone who is used to working with Qgis for a long time. It would be interesting to be able to choose between the new method and the classic way.

**Comment by nirvn** [comment]
I think this can be closed. If the vertex editor hasn't reached perfection yet (:wink:) please file individual issues for each problematic UI/UX point that would need addressing.
