### ISSUE TITLE
Mesh or raster layer with 0-360 extent

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28672]
Author Name: **Saber Razmjooei** (@saberraz)
Original Redmine Issue: [20853](https://issues.qgis.org/issues/20853)
Affected QGIS version: 3.5(master)
Redmine category:map_canvas

---
GRIB or netcdf files sometimes cover 0-360 degree. Most other layers cover -180 to 180.
In QGIS, there is no way of displaying them correctly. QGIS should automatically detects the coverage and uses the default one (-180 to 180).

**Comment by PeterPetrik** [comment]
This should be handled upstream , when implementing the native GRIB/NetCDF driver in MDAL https://github.com/lutraconsulting/MDAL/issues/165
