### ISSUE TITLE
Dublicating a layer with pushing the ctrl-key while dragging, results in a layer that can't be renamed individually

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28674]
Author Name: **Janne Jakob Fleischer** (@jannefleischer)
Original Redmine Issue: [20855](https://issues.qgis.org/issues/20855)
Affected QGIS version: 3.4.1
Redmine category:map_legend

---
When dublicating a layer with dragging and pushing the ctrl-key it got dublicated, though when I rename it, the source layer and the copied layer will have the new changed name. I noticed this in 2.18 and also until (my) current QGIS 3.4.1.

I think this is only relevant on Windows, while I used this function many times on mac without the doubled renaming (Sadly no Linux here at my ne workplace, so I can't test this).

**Comment by MrChebur** [comment]
I can confirm this bug in QGIS version 3.12.0-București (Windows 10):
![QGIS Copy layer bug](https://user-images.githubusercontent.com/20655102/79826371-fa01df00-83b4-11ea-9595-cff1abbcb212.gif)

**Comment by bkepl** [comment]
I can see that in some cases this could be useful, e.g. if you wanted a duplicate layer in more than one layering order in the map: in some cases I may want the layer on top of some features, and in other cases, below. If you click one such layer on, will the other turn on? If you add one of those layers to a theme, will the other also be added?

When I first noticed this behavior, I opened the map in a text editor (I love that I can do this!) and noticed that the layer was duplicated in its entirety, including the unique index given to the layer.

**Comment by gioman** [comment]
Still a thing on the latest master, still unsure if is bug or feature.

**Comment by MrChebur** [comment]
@gioman I don't think this is a feature because most users don't expect such weird behavior.

**Comment by Pedro-Murteira** [comment]
Still an issue on QGIS 3.22.3. (Windows 10)
