### ISSUE TITLE
qgis uninstalled from debian buster after routine update/upgrade due to bad dependency on libhdf5-100

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28678]
Author Name: **Gerard OpenSideFlanker** (Gerard OpenSideFlanker)
Original Redmine Issue: [20859](https://issues.qgis.org/issues/20859)
Affected QGIS version: 3.4.2
Redmine category:build/install

---
Hi all,

I am running qgis on a debian buster.
During last buster upgrade libhdf5 has been upgraded from libhdf5-100 to libhdf5-103.

Due to strict dependency of  qgis-providers on libhdf5-100, *qgis and all its dependencies* have been *removed* by the _apt-get autoremove_ command used for cleaning after upgrade. I have tried to link the new libs on the old names but with no effect, the dependency seems to be tightened to the package itself

Would it be possible to have binary builds dependencies not sticked on a given version to enable them accept newer versions of packages brought by upgrades. 

I don't know if it is possible...

As an ugly trick I have changed the dependency according to this tutorial _https://serverfault.com/questions/250224/how-do-i-get-apt-get-to-ignore-some-dependencies_ installed the modified package and recovered a normal procedure 

QGIS works properly as far as I have tested it  the link to the old name could be necessary (?)
 the modified package is attached

Thanks for your work !

---

- [qgis-providers_3.4.2+15buster_amd64.deb](https://issues.qgis.org/attachments/download/14010/qgis-providers_3.4.2+15buster_amd64.deb) (Gerard OpenSideFlanker)

**Comment by jidanni** [comment]
See also https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=929973

**Comment by nyalldawson** [comment]
Closed upstream
