### ISSUE TITLE
Easter eggs don't stack

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28671]
Author Name: **Nathan Woodrow** (@NathanW2)
Original Redmine Issue: [20852](https://issues.qgis.org/issues/20852)
Affected QGIS version: 3.5(master)
Redmine category:map_canvas
Assignee: Nyall Dawson

---
Seems we can't stack easter eggs, this is depressing.

Retro and board don't work together. 

You should fix this Nyall ASAP. Before xmas

**Comment by Pedro-Murteira** [comment]
Although it is not of the utmost importance, it is a cool feature. I can still confirm this issue. (QGIS 3.22.3.)
