### ISSUE TITLE
Qgis 3.4.2 crash when applied draw effects

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28685]
Author Name: **Branko Bass** (Branko Bass)
Original Redmine Issue: [20866](https://issues.qgis.org/issues/20866)
Affected QGIS version: 3.4.2
Redmine category:symbology

---
I tried to apply draw effects on vector layer of 1000 points. When "Outer Glow" added everything runs smoothly. But when tired to render all of them Qgis would crash.
Tried multiple times same action.
Thank you

---

- [qgisCrash.mp4](https://issues.qgis.org/attachments/download/14016/qgisCrash.mp4) (Branko Bass)

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
