### ISSUE TITLE
QGIS Server 3.4 broken on Windows

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28692]
Author Name: **Uroš Preložnik** (@uprel)
Original Redmine Issue: [20873](https://issues.qgis.org/issues/20873)
Affected QGIS version: 3.4.4
Redmine category:qgis_server

---
Latest QGIS Server from OSGeo4W doesn't work. Maybe is related to Python configuration.

This are Apache environment variables used (I checked, they are valid paths):

@SetEnv GDAL_DATA "C:\OSGeo4W64\share\gdal"
SetEnv QGIS_AUTH_DB_DIR_PATH "C:\OSGeo4W64\apps\qgis\resources"
SetEnv PYTHONHOME "C:\OSGeo4W64\apps\Python37"
SetEnv PATH "C:\OSGeo4W64\bin;C:\OSGeo4W64\apps\qgis\bin;C:\OSGeo4W64\apps\Qt5\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;"
SetEnv QGIS_PREFIX_PATH "C:\OSGeo4W64\apps\qgis"
SetEnv QT_PLUGIN_PATH "C:\OSGeo4W64\apps\qgis\qtplugins;C:\OSGeo4W64\apps\Qt5\plugins;"@

Call to GetCapabilities
http://localhost:8080/cgi-bin/qgis_mapserv.fcgi.exe?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities

Request takes over 7 seconds and generates broken response, some text on screen but not complete XML.

Attached is QGIS Server log file only for that request.

---

- [qgis-server.log](https://issues.qgis.org/attachments/download/14018/qgis-server.log) (Uroš Preložnik)
- [qgis server 3.4.4 uncomplete response.xml](https://issues.qgis.org/attachments/download/14343/qgis%20server%203.4.4%20uncomplete%20response.xml) (Uroš Preložnik)
- [qgis-server-3.4.4.log](https://issues.qgis.org/attachments/download/14344/qgis-server-3.4.4.log) (Uroš Preložnik)
- [httpd-vhosts.conf](https://issues.qgis.org/attachments/download/14548/httpd-vhosts.conf) (João Gaspar)
- [httpd.conf](https://issues.qgis.org/attachments/download/14549/httpd.conf) (João Gaspar)

**Comment by jonnyforestGIS** [comment]
@gioman This can be close? I think this isn't a problem anymore. The #28290 can be close as well see comment in #28290

**Comment by gioman** [comment]
it is also my observation that now it works ok.
