### ISSUE TITLE
Field filter in the attribute table not working for numbers as the value gets enclosed as a string

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28693]
Author Name: **Tudor Bărăscu** (@tudorbarascu)
Original Redmine Issue: [20874](https://issues.qgis.org/issues/20874)
Affected QGIS version: 3.5(master)
Redmine category:attribute_table

---
I just noticed this, having a table with a id integer column.
If I do a field filter on the attribute table and enter 1 QGIS does an id = '1' instead of id = 1 so the result is not good.
This can be seen when switching to the advanced filter.

---

- [problem.gif](https://issues.qgis.org/attachments/download/14019/problem.gif) (Tudor Bărăscu)

**Comment by Pedro-Murteira** [comment]
I'm not being able to replicate either of these issues on QGIS 3.16.15 and 3.22.2. Did you by chance came across this issues more recently? @tudorbarascu
