### ISSUE TITLE
vertex tool + topological editing

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28707]
Author Name: **Thomas Nogatz** (@TomNog)
Original Redmine Issue: [20888](https://issues.qgis.org/issues/20888)
Affected QGIS version: 3.4.3
Redmine category:digitising

---
There seems to exist a bug with the node tool when using topological editing. Some screenshots are attached.

Please follow these steps:
* create a new shapefile polygon layer 
* activate following snapping options via Advanced Configuration:
    Snapping
    Avoid intersection
    Topological Editing
* Add polygon feature: triangle, beginning with lower left corner (A1), then lower right corner (A2), finally upper corner (A3)
* Add polygon feature: square overlapping with the triangle (overlap will be deleted due to snapping options, so a second triangle will remain): set a node in A1, then make a node inside the triangle, then a node in A2, then the last node somewhere down outside the triangle (see screen_01.png, the first polygon is the upper one)
* vertex tool (current layer): try to set a node on every available edge 

Results: 
* vertices at lower left and upper right edge  are set correctly (see screen_02.png)
* setting a vertex at the common edge: a green cross appears at the vertex, but no topological error is reported (see screen_03.png)
* setting vertices at lower right and upper left edge causes topological errors (invalid geometry, see screen_04.png) 

This errors do not appear when working without topological editing. When you draw the polygons without overlapping, the error appears at the common (screen_05.png) and at the upper left edge (screen_06.png).

    

---

- [screenshots.zip](https://issues.qgis.org/attachments/download/14030/screenshots.zip) (Thomas Nogatz)

**Comment by lbartoletti** [comment]
@tomnog can you try with QGIS 3.10?

**Comment by TNogatz** [comment]
It works well, thanks a lot!
