### ISSUE TITLE
Identify results window too small by default

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28710]
Author Name: **Nathan Perry** (Nathan Perry)
Original Redmine Issue: [20891](https://issues.qgis.org/issues/20891)
Affected QGIS version: 3.4.2
Redmine category:map_tools

---
When using the identify tool, the Feature Attributes pop-up window defaults to an unusably small size, and must be resized each time (see attached screenshot).

---

- [Screen Shot 2018-12-28 at 7.35.15 AM.png](https://issues.qgis.org/attachments/download/14033/Screen%20Shot%202018-12-28%20at%207.35.15%20AM.png) (Nathan Perry)

---

Related issue(s): #28880 (duplicates)
Redmine related issue(s): [21062](https://issues.qgis.org/issues/21062)

---

**Comment by ugosantana** [comment]
Hi there!

A guy on stackoverflow find out a way to make the attribute dialog the correct size and not tiny. I tested and it's working for now. On the Layer Properties go to Form and change the Autogenerate option to Drag and drop designer. This have to be done to each layer. 

[https://stackoverflow.com/questions/54781698/qgis-3-how-to-change-size-of-attribute-window](url)

**Comment by suricactus** [comment]
Seems this is no longer the case for QGIS 3.12, please confirm.

**Comment by gioman** [comment]
Closing for lack of feedback.
