### ISSUE TITLE
[mesh] Time slider for non-temporal data should be disabled

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28761]
Author Name: **Saber Razmjooei** (@saberraz)
Original Redmine Issue: [20942](https://issues.qgis.org/issues/20942)
Affected QGIS version: 3.5(master)
Redmine category:symbology
Assignee: Peter Petrik

---
You can still move the slider if one of your quantities is not temporal.

**Comment by michelk** [comment]
When loading BASEMENT results (results.xdmf) with QGIS 3.18., the time-slider widget is not present, although the dataset is recognized as temporal data. Is the related to this PR?

**Comment by PeterPetrik** [comment]
@michelk can you show screenshot? not sure what you mean by "not present". are you sure that the toolbar is switched on?

**Comment by michelk** [comment]
Has the time-slider moved to a different panel? It used to be in 'Layer styling'

![Screenshot from 2021-03-22 16-37-24](https://user-images.githubusercontent.com/1404919/112017297-c3d16000-8b2d-11eb-867c-fab3ddae9fa6.png)

**Comment by PeterPetrik** [comment]
yes it has moved in 3.x release. see for example top-right panel in https://qgis.org/en/site/forusers/visualchangelog314/index.html?highlight=mesh#feature-use-only-specified-dataset-group

**Comment by PeterPetrik** [comment]
there are many online docs and video how to use temporal controller and new mesh layers in QGIS 3. For example you may want to watch https://www.youtube.com/watch?v=bzyB6sTNVfI

**Comment by michelk** [comment]
ok thanks, will look into it.
