### ISSUE TITLE
raster layer style shown in "Layers" panel is not updated when style is changed from the "Style Manager" tab in the Layer Styling panel

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28765]
Author Name: **Alister Hood** (@AlisterH)
Original Redmine Issue: [20946](https://issues.qgis.org/issues/20946)
Affected QGIS version: 3.4.4
Redmine category:gui

---
As per the title.  To reproduce:
- Open the "Layer Styling" panel.
- Apply a style from a qml to a layer (using the folder icon on the fourth tab down).
- The style shown for that layer in the "Layers" panel should be updated, but it is not.
- Right click on the layer in the Layers panel and choose "Properties".
- Apply the style from qml (using the style button at the bottom of the symbology tab).
- Click OK, and the style shown for the layer is correctly updated in the "Layers" panel.

In fact, any change from the "Style Manager" tab is not reflected in the "Layers" panel i.e. using the "Restore Default" button, or selecting a style from the list.

Only tested with raster layers and on Windows.

FWIW this seems like a very minor issue, but it can be very confusing - I almost filed a completely incorrect bug report because it made me think the layers panel had somehow confused some layers and was turning the wrong ones on and off.

**Comment by AlisterH** [comment]
I found some bug which might be related - errors using undo and redo in the layer styling panel.

1. e.g. testing with singleband pseudocolor rasters in 3.10.0:
- Style a raster as singleband pseudocolour.
- In the layer styling panel click on one of the colours and change it to something else.
- Undo the change.  The undo is not reflected in the Layers panel.  Neither is redo.  But this doesn't apply to undo/redo of all possible styling changes, just some particular ones.
2. Play around with undo and redo and the history list a bit, and at some point you will probably see that the original styling disappears.  My layer is saved in the project with singleband pseudocolour, so it was already styled when I opened the project, and sometimes if I undo right back to the beginning all the classes disappear and the raster becomes invisible.

**Comment by Pedro-Murteira** [comment]
@AlisterH After testing this out, this is my conclusion:
- This seems to be related to the size of the raster file
- when I applied the style on "Layer Styling" to 2 different raster files (385 KB and 196 KB) it worked without any issues
- when I applied the style on "Layer Styling" to 2 other raster files (8,360 KB and 2,736 KB) it did not work, and I could only apply the style on Layer Properties
This was the only coorelation I could find, but it can also be related to other properties.
In sum, I wasn't able to replicate it with every single test, but it still occurs sometimes. (QGIS 3.16.15 and 3.22.2.)

**Comment by AlisterH** [comment]
The workaround to update the legend in the layers panel after loading the style is to go back to the symbology tab in the layer styling panel and then click "Apply".

**Comment by AlisterH** [comment]
I think we can close this - it seems to be fixed in 3.26.3

I do note that similar to one of my previous comments, if I play around with undo and redo 
there do still seem to be some issues with that.  I managed to get it into a state where redo never did anything, and undo worked in a loop.
