### ISSUE TITLE
Define how many features to read in a processing model

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28771]
Author Name: **Magnus Nilsson** (Magnus Nilsson)
Original Redmine Issue: [20952](https://issues.qgis.org/issues/20952)

Redmine category:processing/modeller

---
In some cases, I have large data sets (millions of features or more) and when creating a processing model, I would like to be able to set a (temporary) limit of the number of features to read. That way, polishing the model will go quicker, when I don´t have to wait for QGIS to read all of the features. When the work is finished, I can remove the limit and let all of the features be processed.

**Comment by nyalldawson** [comment]
Possible in 3.14
