### ISSUE TITLE
Python error when running a Processing model

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28791]
Author Name: **Magnus Nilsson** (Magnus Nilsson)
Original Redmine Issue: [20972](https://issues.qgis.org/issues/20972)
Affected QGIS version: 3.4.3
Redmine category:processing/modeller

---
I am trying to use an online CSV file and plot its content as points using a Processing model. These steps causes a Python error:

1) Open a new model
2) Add the algorithm for downloading a file. I used https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/4.5_day.csv.
3) Add the algorithm for creating points from a table and configure it
4) Run the model
5) I now get this error message:

Traceback (most recent call last):
File "C:/PROGRA~1/GIS/QGIS/apps/qgis/./python/plugins\processing\algs\qgis\PointsLayerFromTable.py", line 91, in processAlgorithm
raise QgsProcessingException(self.invalidSourceError(parameters, self.INPUT))
_core.QgsProcessingException: Kunde inte läsa in källager för INPUT: C:/Users/Magnus/AppData/Local/Temp/processing_fa76c51163e14b998c7ffcb4867abf80/980f76d9052042cd8525137ae9ede68f/OUTPUT.file ej hittad

Ett fel uppstod vid körning av Skapa punktlager från tabell

Ett fel uppstod vid körning av Skapa punktlager från tabell

Beräkningen misslyckades efter 0.38  sekunder

I expected the data from the download algorithm to be available for other algorithms. Is this incorrect or is this a bug?

---

- [CSV from web.model3](https://issues.qgis.org/attachments/download/14083/CSV%20from%20web.model3) (Magnus Nilsson)

**Comment by alexbruy** [comment]
You need to save downloaded file with correct extension, so QGIS can recognize it as supported format. Using temporary file as destination will produce file with `OUTPUT.file` name which can not be recognized as supported format.

**Comment by nyalldawson** [comment]
Closing due to lack of feedback
