### ISSUE TITLE
NETCDF file format could not be read by QGIS

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28799]
Author Name: **Amirhossein Nikfal** (Amirhossein Nikfal)
Original Redmine Issue: [20980](https://issues.qgis.org/issues/20980)
Affected QGIS version: 3.4.4
Redmine category:data_provider/mdal

---
Dear all,

In the newest versions of QGIS (3.4.1, 3.4.2, ...), adding NETCDF files as raster layers seems to be crashed. After trying to add such file formats, the below message encounters:
Invalid Layer: Raster layer Provider is not valid (provider: gdal, URI: $path-to-netcdf-file)

Any comments would be appreciated.

thanks in advance

---

- [Sapmple-file-for-QGIS.nc](https://issues.qgis.org/attachments/download/14085/Sapmple-file-for-QGIS.nc) (Amirhossein Nikfal)
- [load mesh nc.gif](https://issues.qgis.org/attachments/download/14086/load%20mesh%20nc.gif) (Saber Razmjooei)

---

Related issue(s): #28740 (relates)
Redmine related issue(s): [20921](https://issues.qgis.org/issues/20921)

---

**Comment by wonder-sk** [comment]
Is this still an issue with the current QGIS master?

**Comment by alexbruy** [comment]
Closing for the lack of feedback. Please reopen if necessary.
