### ISSUE TITLE
Scan data for attributes to use in a Processing model

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28805]
Author Name: **Magnus Nilsson** (Magnus Nilsson)
Original Redmine Issue: [20986](https://issues.qgis.org/issues/20986)

Redmine category:processing/modeller

---
I am not too fond of the idea of manually having to enter which attributes to use in a Processing model. For example, in the tool for creating points from a table, I manually have to enter (write) which fields to use for x/y coordinates. Wouldn´t it be better to allow a model to scan the data for attributes and let the user select relevant attributes from a list?

Related: When adding a vector layer to a model, why not choose the data source directly? That way, the model knows the available attributes. Having to define this each time I run a model is time consuming.

**Comment by alexbruy** [comment]
I'm afraid this is not possible, as model does not store data itself. You can add field input to the model and connect it to the input layer/table, this way at run-time you will be able to select fields.
