### ISSUE TITLE
Add a way to pass additional parameters to GDAL commands

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28813]
Author Name: **Matthias Treitler** (@mattrei)
Original Redmine Issue: [20994](https://issues.qgis.org/issues/20994)

Redmine category:processing/gdal

---
The GDAL tool "gdaldem color-relief" https://www.gdal.org/gdaldem.html#gdaldem_color_relief allows to pass the "-alpha" argument so that the output raster also contains the alpha band. The GDAL tools dialog show a input text box for additional creation options however it is not passed to the actual command, not matter what is inserted here.

**Comment by alexbruy** [comment]
Implemented in c224a01
