### ISSUE TITLE
in SVG marker style any edits returns the styling back to green stroke with red fill

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28826]
Author Name: **Adam Fine** (@littlezaide)
Original Redmine Issue: [21007](https://issues.qgis.org/issues/21007)
Affected QGIS version: 3.4.3
Redmine category:symbology

---
When using SVG markers, it's possible to alter the SVG in QGIS to have custom colours. It defaults to green stroke, red fill when you create a new SVG style. 

The bug is that QGIS will revert back to green stroke/red fill whenever you visit the layer styling panel at any time, or go to layer properties->symbology. Making any other changes to the layer style will require you also to reset the colours you want. 

---

- [Screen Shot 2019-01-15 at 8.59.29 AM.png](https://issues.qgis.org/attachments/download/14104/Screen%20Shot%202019-01-15%20at%208.59.29%20AM.png) (Adam Fine)

**Comment by nyalldawson** [comment]
This is fixed
