### ISSUE TITLE
PostgreSQL column-restricted INSERT permissions are ignored

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28835]
Author Name: **Nikolay Lebedev** (Nikolay Lebedev)
Original Redmine Issue: [21016](https://issues.qgis.org/issues/21016)

Redmine category:data_provider/postgis

---
QGIS only allows you to create new features or modify them if you have full permissions on all columns of the table. 

I.e. you have a table:

```
CREATE TABLE foo (
  id SERIAL PRIMARY KEY,
  restricted_column TEXT,
  geom GEOMETRY(Polygon, 4326)
);

```

Feature creation is enabled only when you have permissions on all columns:

```
GRANT INSERT ON foo TO qgis_user;

```

But not in this case:

```
REVOKE INSERT ON foo FROM qgis_user;
GRANT INSERT(id, geom) ON foo TO qgis_user;

```

Same goes to updating or deleting features.

**Comment by strk** [comment]
I saw QGIS code checking for column permissions, is this still a problem with current master branch or any recent release ?

**Comment by strk** [comment]
I could reproduce with QGIS 3.22.16-Białowieża

**Comment by strk** [comment]
I could also reproduce with 
3.37.0-Master | d3ac2aef0d9

**Comment by strk** [comment]
By additionally granting UPDATE I've handled to get QGIS enter an infinite loop and crash, ouch

**Comment by strk** [comment]
So, beside the crash, which I'll file in a separate issue, I observe that by granting UPDATE the ability to edit is there.
So what's being ignored is the column-restricted INSERT while the column-restricted UPDATE is honoured.
