### ISSUE TITLE
In layout the theme of the map follows the scale dependency of default style, not the style used

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28834]
Author Name: **N Swan** (N Swan)
Original Redmine Issue: [21015](https://issues.qgis.org/issues/21015)
Affected QGIS version: 3.4.3
Redmine category:map_composer/printing

---
In Layout the map based on the Theme that has scale dependency in the  style used (not default style) will not follow this scale dependency. The map always follows the scale dependency of the default style.

**Comment by nyalldawson** [comment]
This is fixed in recent versions
