### ISSUE TITLE
[Mesh] missing arrows with Multiple blending mode when exporting to PNG 

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28846]
Author Name: **Saber Razmjooei** (@saberraz)
Original Redmine Issue: [21027](https://issues.qgis.org/issues/21027)
Affected QGIS version: 3.5(master)
Redmine category:symbology

---
https://lists.osgeo.org/pipermail/qgis-developer/2019-January/055829.html

**Comment by Pedro-Murteira** [comment]
@saberraz Hello, is this issue still valid on more recent releases?

**Comment by saberraz** [comment]
ping @pcav
