### ISSUE TITLE
Value 'default' should not be localized for style

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28848]
Author Name: **Nicolas Boisteault** (@nboisteault)
Original Redmine Issue: [21029](https://issues.qgis.org/issues/21029)
Affected QGIS version: 3.4.3
Redmine category:qgis_server
Assignee: René-Luc ReLuc

---
GetCapabilities return the localized value for 'default' in style section. In my case (french) it returns 'défaut' which is wrong.

**Comment by nboisteault** [comment]
@rldhont @dmarteau gentle ping.

**Comment by Gustry** [comment]
I think it has been fixed: https://github.com/qgis/QGIS/pull/9696 and https://github.com/qgis/QGIS/pull/9723

**Comment by nboisteault** [comment]
@Gustry OK fixed. I can't close issues. Thank you for your search.

**Comment by rldhont** [comment]
Can be closed, it has been fixed with https://github.com/qgis/QGIS/pull/9696
