### ISSUE TITLE
Export project to dxf symbol size

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28854]
Author Name: **Matjaž Mori** (Matjaž Mori)
Original Redmine Issue: [21035](https://issues.qgis.org/issues/21035)
Affected QGIS version: 3.5(master)
Redmine category:dxf_export

---
When exporting project, point symbols sizes not affected by change of symbology scale. 
Exported symbol sizes in dxf always seem to be in meters no matter what scale is set on export or what units are set for symbol size in layer properties.

**Comment by lbartoletti** [comment]
Confirmed, in master with @kandre 

If the symbol size unit is "meter" the dxf symbol is OK.

cc @kandre @jef-n
