### ISSUE TITLE
QgsAction "enabledOnlyWhenEditable" not available in Python

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28853]
Author Name: **Benjamin Jakimow** (@jakimowb)
Original Redmine Issue: [21034](https://issues.qgis.org/issues/21034)
Affected QGIS version: 3.4.3
Redmine category:python_bindings_/_sipify

---
## Problem

The @QgsAction@ keyword @enabledOnlyWhenEditable@ is unavailable Python, although
the keyword is documented in both, the C++ (https://qgis.org/api/classQgsAction.html) and Python documentation (https://qgis.org/pyqgis/master/core/QgsAction.html).

the C++ and Python documentation  describe it

## Example

```
from qgis.core import QgsAction
QgsAction(QgsAction.GenericPython, 'dummy', 'print("dummy")', 'dummy', True, notificationMessage='dummy')

1. fails
QgsAction(QgsAction.GenericPython, 'dummy', 'print("dummy")', 'dummy', True, notificationMessage='dummy', enabledOnlyWhenEditable=False)

```

## Systems

Windows 10 Education, 64-Bit
macOS 10.13.6

QGIS version 3.4.3-Madeira
QGIS code revision 2f64a3c4e7

**Comment by stev-0** [comment]
Looks like [this commit](https://github.com/qgis/QGIS/commit/555cdf0a20d926fde8708a2f70600cfcf5fccc35) changed that - unclear why it was done and therefore whether the code or just documentation should be changed.

@signedav might know as the author of the commit?

**Comment by jakimowb** [comment]
Just checked it with QGIS 3.12.2, but "enabledOnlyWhenEditable" is not available. And I still would like to have it in PyQGIS.

```
from qgis.core import QgsAction
QgsAction(QgsAction.GenericPython, 'dummy', 'print("dummy")', 'dummy', True, notificationMessage='dummy')

# fails
QgsAction(QgsAction.GenericPython, 'dummy', 'print("dummy")', 'dummy', True, notificationMessage='dummy', enabledOnlyWhenEditable=False)
```

QGIS Version

QGIS version | 3.12.2-București | QGIS code revision | 8a1fb33634
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Windows 10 (10.0)
Active python plugins | timeseriesviewerplugin; processing

**Comment by signedav** [comment]
This parameter has been removed for Python in the same PR like this parameter has been introduced. Means it's a mistake in the Python documentation.

But this does not mean, that it won't make sense to have this parameter available. As far as I remember we needed this solution on the release, but we have not been happy to have it as a bool and we planned to improve it to an enum flag instead. 
I can have another look next week and maybe integrate it...

**Comment by Gustry** [comment]
#39325 has been merged.

Still not possible to use the constructor, but at least there is a setter for it.
