### ISSUE TITLE
QGIS3, pasting a .shp source with 'gid' field presented into a postgis layer now doesn't ignore the source 'gid' like it seems do in 2.18

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28855]
Author Name: **sand thorn** (sand thorn)
Original Redmine Issue: [21036](https://issues.qgis.org/issues/21036)
Affected QGIS version: 3.4.3
Redmine category:editing

---
When pasting from .shp source with 'gid' into a postgis layer, in 2.18 it just ignore the 'gid' of the source.
As a result, you got complained when trying to save editing

Could not commit changes to layer <layername>

Errors: ERROR: 6849 feature(s) not added.
  
  Provider errors:
      PostGIS error while adding features: ERROR:  duplicate key value violates unique constraint "<layername>_pkey"
    DETAIL:  Key (gid)=(2) already exists.
    

WORKAROUND: manually delete .shp source's gid field before copying

**Comment by nyalldawson** [comment]
Much work has been done to improve this situation -- I believe we can close this now and wait for a new report to be opened if there's still issues.
