### ISSUE TITLE
WCS "always cache" not working as expected

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28869]
Author Name: **Jonathan Moules** (Jonathan Moules)
Original Redmine Issue: [21050](https://issues.qgis.org/issues/21050)
Affected QGIS version: 3.4.3
Redmine category:web_services_clients/wcs

---
This WCS:
http://opendata.meteo.be/service/wcs?

If I add a layer from there using the default "prefer network", it works fine.

But if you add a layer you have NEVER looked at before (so there's no chance of it being cached from the previous test), you get:

2019-01-20T12:59:43     CRITICAL    Invalid Layer : WCS provider Cannot get test dataset.
             Raster layer Provider is not valid (provider: wcs, URI: cache=AlwaysCache&crs=EPSG:4326&dpiMode=7&format=GeoTIFF&identifier=alaro:2_m_dewpoint_temperature&time=2019-01-20T06:00:00.000Z/2019-01-22T18:00:00.000Z/PT1H&url=http://opendata.meteo.be/service/wcs?

As far as I can tell from fiddler, it's not even trying to make a GetCoverage request to the WCS, it's simply failing.

**Comment by Pedro-Murteira** [comment]
I can no longer replicate this issue on QGIS 3.16.15 and 3.22.2.
