### ISSUE TITLE
Display layer name/title/abstract/keyword clearly for WMS

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28861]
Author Name: **Jonathan Moules** (Jonathan Moules)
Original Redmine Issue: [21042](https://issues.qgis.org/issues/21042)

Redmine category:web_services_clients/wms

---
This WMS has taken the trouble to write a long Abstract:
http://ogc.geo-ide.developpement-durable.gouv.fr/wxs?map=%2Fopt%2Fdata%2Fcarto%2Fgeoide-catalogue%2F1.4%2Forg_38102%2F2f3f11f0-91c9-479a-b748-ed1098603e91.internet.map&version=1.3.0

But there's no way to see it in QGIS. Similarly the long name and long title are also hidden, despite the fact I'm viewing this on a 1600pixel wide monitor.
Similarly, as far as I can see, layer keywords are not displayed at all (although the ones on that layer are fairly meaningless), nor is any service level info (service name, title, abstract, keywords).
Could not a dialog on the right side of the WMS panel be used to display the given information for the selected layer?

**Comment by alexbruy** [comment]
There are tooltips for abstract and title. Is this not enough?
