### ISSUE TITLE
Unable to add WCS - bad error reporting

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28865]
Author Name: **Jonathan Moules** (Jonathan Moules)
Original Redmine Issue: [21046](https://issues.qgis.org/issues/21046)
Affected QGIS version: 3.4.3
Redmine category:web_services_clients/wcs

---
Related to #28864

This WCS:
http://thredds.ucar.edu/thredds/wcs/grib/NCEP/WW3/Regional_US_West_Coast/Best

If I try and add a layer from this WCS, QGIS makes a bad request and the server response is this exception:
```
<?xml version="1.0" encoding="UTF-8"?>
<ServiceExceptionReport xmlns="http://www.opengis.net/ogc" version="1.2.0">
  <ServiceException code="InvalidParameterValue" locator="CRS">Request CRS [EPSG:0 [Latitude_Longitude]] not allowed [OGC:CRS84].</ServiceException>
</ServiceExceptionReport>

```

Except what QGIS reports is this:

```
  Invalid Layer : WCS provider Cannot get test dataset.
             Raster layer Provider is not valid (provider: wcs, URI: cache=PreferNetwork&crs&dpiMode=7&format=GeoTIFF_Float&identifier=Wind_speed_surface&time=2018-12-21T00:00:00Z&url=http://thredds.ucar.edu/thredds/wcs/grib/NCEP/WW3/Regional_US_West_Coast/Best

```

So the WCS handler doesn't seem to be correctly handling exceptions - it's passing them straight to the "Raster layer Provider" which of course barfs. Instead, the WCS error should be parsed and exposed to the user.

---

Related issue(s): #28864 (relates)
Redmine related issue(s): [21045](https://issues.qgis.org/issues/21045)

---

**Comment by gioman** [comment]
Is this still relevant on recent QGIS releases?
