### ISSUE TITLE
Requests made for features when outside of bbox

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28867]
Author Name: **Jonathan Moules** (Jonathan Moules)
Original Redmine Issue: [21048](https://issues.qgis.org/issues/21048)
Affected QGIS version: 3.4.3
Redmine category:web_services_clients/wfs

---
For WMS/WMTS, it seems that if you're viewing outside of the declared Bounding Box of the layer, then QGIS doesn't make any requests to the server. This makes sense and is a good optimisation.

But for WFS, even if you're outside of the area, if you pan-around, it still makes requests for the features.

At least, that's what I'm seeing for this (which has the data for both WMS and WFS making a good test):
http://ogc.geo-ide.developpement-durable.gouv.fr/wxs?map=%2Fopt%2Fdata%2Fcarto%2Fgeoide-catalogue%2F1.4%2Forg_38102%2F2f3f11f0-91c9-479a-b748-ed1098603e91.internet.map&version=2.0.2

The WMS requests are all simply not sent when completely outside the bbox, but the WFS requests are.

**Comment by gioman** [comment]
Is this still relevant o recent QGIS releases?
