### ISSUE TITLE
Black theme in not acivated after restart QGIS

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28884]
Author Name: **Andrew Shanin** (Andrew Shanin)
Original Redmine Issue: [21066](https://issues.qgis.org/issues/21066)
Affected QGIS version: 3.4.4
Redmine category:gui

---
Black theme in not acivated after restart QGIS.
It do not work in vista/WIndows/Fusion mode.

**Comment by Pedro-Murteira** [comment]
I can no longer reproduce this bug on versions 3.16.14 and 3.22.1.
