### ISSUE TITLE
QGIS window will not appear over any other app on a Microsoft Surface Book

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28894]
Author Name: **Loren Amelang** (@LorenAmelang)
Original Redmine Issue: [21076](https://issues.qgis.org/issues/21076)
Affected QGIS version: 3.4.3
Redmine category:gui

---
Since updating to 3.4.3 via the OSGeo4W updater, QGIS will not move to the top of my window stack over any other app window! Usually I have to manually bring new apps forward after opening them, but nothing will make QGIS appear if another app is drawn. 

I've seen this happen to Libre Office (another QT5 app) versus my mail client EverDesk, so I'm not shocked. But QGIS can't appear over _any_ app. And it can't appear over its own sub windows - I'm pretty sure I used to be able to keep those open partly behind the main window... 

Taskbar preview shows the QGIS window normally, over an empty desktop. But there is a new curiosity...  If I mouse over a tray icon, and mouse away from that icon without touching an inactive app icon, the thumbnail remains visible until I type something in whichever window is topmost. 

The QGIS icon background changes when clicked, as if it is being shown and hidden, but it does not appear unless it is the only window displayed. 

Windows 10 is out of control sometimes, and all of this may depend upon some recent Windows Update. I don't know how to dig into this window stack mess. I've included the MS Spy++ stack tree, with several groups of QGIS entries way down the stack, including at the very bottom, but I have no idea if there are useful clues there. 

---

- [Spy++ window tree (QGIS stuck behind Vivaldi).sxt](https://issues.qgis.org/attachments/download/14143/Spy++%20window%20tree%20(QGIS%20stuck%20behind%20Vivaldi).sxt) (Loren Amelang)

**Comment by Pedro-Murteira** [comment]
@LorenAmelang Hello, unfortunately I can not confirm if this issue is still valid. Did you by any chance come across this issue while  using more recent versions of QGIS?

**Comment by LorenAmelang** [comment]
@gioman @Pedro-Murteira 
Windows died and recovery deleted all my apps, and I haven't gotten to reinstalling QGIS yet. So I can't try the latest version. But after that original post and version, I only saw QGIS versions show the same random problems other apps show. Which are probably Windows issues. 

Seriously considering moving QGIS to my Linux world...  Is a full install used via VNC or RDP more competent than a server install? Wish there was a version for my new iPad 12.9 5Gen...  Same M1 chip as latest Macs...

**Comment by gioman** [comment]
> show the same random problems other apps show. Which are probably Windows issues.

@LorenAmelang so can we close this?

**Comment by LorenAmelang** [comment]
I did install the latest Standalone last night, and saw no Z-order problems at all. So yes, you can close this.
