### ISSUE TITLE
QGIS logo not displayed on taskbar for additional windows

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28899]
Author Name: **Carolyn Krause** (Carolyn Krause)
Original Redmine Issue: [21081](https://issues.qgis.org/issues/21081)
Affected QGIS version: 3.4.3
Redmine category:windows_package
Assignee: Jürgen Fischer

---
Windows other than the main QGIS project window display a blank page image on the taskbar instead of the QGIS logo. This happens for anything that opens up a separate window, including attribute tables, print layouts, and processing algorithms. The main QGIS project window correctly displays the QGIS logo.
![taskbar_logo.png](https://issues.qgis.org/attachments/download/14149/taskbar_logo.png)

---

- [taskbar_logo.png](https://issues.qgis.org/attachments/download/14149/taskbar_logo.png) (Carolyn Krause)

**Comment by gioman** [comment]
Cannot replicate on recent versions installed on Windows, reopen if necessary.
