### ISSUE TITLE
Legend content issue when using atlas and themes

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28919]
Author Name: **Alexis Roy-L** (Alexis Roy-L)
Original Redmine Issue: [21101](https://issues.qgis.org/issues/21101)
Affected QGIS version: 3.4.4
Redmine category:map_legend

---
Greetings,

Here is the behavior I noticed:

When using themes and an atlas to generate automatically maps, the current selected sub item in the map will be used rather than the setting of the theme.

IE: If I have a layer with 7 classes and I want one of them to be displayed for 2 themes and all the classes for 1 other theme.

The legend will display the classes that are currently activated in the map regardless of what is displayed by the theme on the canvas.

This mean that I must set my map to match the theme of the canvas in order to display the proper categories in the legend, otherwise only one, none or all the classes for a given layer will be displayed depending on the current map theme and regardless of the canvas theme.

Thanks and have a nice day!

**Comment by klakar** [comment]
Probably the same problem:

When creating themes with different styles and adding several map items to a layout. The legends does not follow the map theme. Even if the correct map is set as source for the legend.
![inflyttning](https://user-images.githubusercontent.com/6375959/63250339-b4ac7100-c26b-11e9-98bc-02b654af8d4a.jpg)
In the picture above is looks ok, but the interval for the colors are different between the maps.
There's no way to create a product with the correct legend from layout. It's possible to show it on screen, if you add the legend with the correct theme shown in the canvas. But as soon as you move any legend, print or make an export. All legends is reset to follow the current theme in the canvas.
