### ISSUE TITLE
Wromg definition SRS 5514 in shapefile

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28936]
Author Name: **Vladimír Hans** (Vladimír Hans)
Original Redmine Issue: [21118](https://issues.qgis.org/issues/21118)
Affected QGIS version: 3.4.4
Redmine category:projection_support

---
If I create SHP in SRS 5514 and display this layer in ArcGIS then ARcGIS display data near Barent's sea instead Central Europe. Definition in prj file of SRS 5514 is same as 5513. Same problem is on epsg.io/5514 and epsg.io/5513 in ESRI WKT.

**Comment by nyalldawson** [comment]
This should be fixed in 3.8 and builds based on proj 6. If not, it's a bug in either proj 6 or GDAL and needs reporting there.
