### ISSUE TITLE
Use relative paths in qgis-bin.env

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28945]
Author Name: **Michiel Nass** (Michiel Nass)
Original Redmine Issue: [21127](https://issues.qgis.org/issues/21127)

Redmine category:build/install

---
In file %OSGEO4W_ROOT%\bin\qgis-bin.env the drive letter of the QGIS installation is hard coded.

To allow for portable edition (changing drive letters) of QGIS using relative paths or variables like %OSGEO4W_ROOT% is preferable.

**Comment by AlisterH** [comment]
I don't think this ticket is truly awaiting feedback...
