### ISSUE TITLE
QGIS crashes whenever I try to download the map as an image

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28941]
Author Name: **Anna Kear** (Anna Kear)
Original Redmine Issue: [21123](https://issues.qgis.org/issues/21123)
Affected QGIS version: 3.4.3
Redmine category:unknown

---
Please see title, and [[https://gis.stackexchange.com/questions/310361/exporting-image-from-qgis-3-always-crashes|here]] for more details: the following link.

----BELOW IS THE CRASH REPORT----

Crash ID: 45838b8fc88db276e2db35f0f3c171b4f2c66a90

Stack Trace

QTextOption::wrapMode :
QTextOption::wrapMode :
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QRasterPaintEngine::rasterBuffer :
QRasterPaintEngine::rasterBuffer :
QRasterPaintEngine::fillPolygon :
QRasterPaintEngine::drawPolygon :
QPainter::drawPolygon :
QgsFillSymbolLayer::_renderPolygon :
QgsSimpleFillSymbolLayer::renderPolygon :
QgsFillSymbol::renderPolygonUsingLayer :
QgsFillSymbol::renderPolygon :
QgsSymbol::renderFeature :
QgsFeatureRenderer::renderFeature :
QgsVectorLayerLabelProvider::registerFeature :
QgsVectorLayerLabelProvider::registerFeature :
QgsMapRendererCustomPainterJob::doRender :
QgsMapRendererCustomPainterJob::start :
QgsMapRendererCustomPainterJob::renderSynchronously :
QgsMapRendererTask::run :
QgsTask::start :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.4.3-Madeira
QGIS code revision: 2f64a3c4e7
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.0
Running against GDAL: 2.4.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by gioman** [comment]
> Yes - send it to [nyall.dawson@gmail.com](mailto:nyall.dawson@gmail.com).

@nyalldawson did the issuer ever sent the data?

**Comment by nyalldawson** [comment]
I don't remember them doing it - in any case this looks very close to an issue identified as being in qt, and is fixed upstream
