### ISSUE TITLE
QGIS is not recognizing the AUTHORITY["Esri", part of the .qpj file

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28940]
Author Name: **Gabriel De Luca** (@gabriel-de-luca)
Original Redmine Issue: [21122](https://issues.qgis.org/issues/21122)
Affected QGIS version: 3.4.4
Redmine category:projection_support

---
Starting from a vector layer with only one point in EPSG:4326, when exporting it to a shapefile or geopackage in EPSG:102003, the saved file contains an invalid projection for QGIS.  

The same behavior is observed with any projection other than an @AUTHORITY["EPSG",@ code.

This is the content of the _.qpj_ file:

```
PROJCS["USA_Contiguous_Albers_Equal_Area_Conic",
    GEOGCS["GCS_North_American_1983",
        DATUM["North_American_Datum_1983",
        SPHEROID["GRS_1980",6378137.0,298.257222101]],
        PRIMEM["Greenwich",0.0],
        UNIT["Degree",0.0174532925199433]], 
    PROJECTION["Albers_Conic_Equal_Area"],
    PARAMETER["False_Easting",0.0],
    PARAMETER["False_Northing",0.0],
    PARAMETER["longitude_of_center",-96.0],
    PARAMETER["Standard_Parallel_1",29.5],
    PARAMETER["Standard_Parallel_2",45.5],
    PARAMETER["latitude_of_center",37.5],
    UNIT["Meter",1.0],
    AUTHORITY["Esri","102003"]]

```

I'm not sure if the mistake is made by writing it or reading it.
It may be well written and QGIS should read it like that.  

But if it is changed by @AUTHORITY["EPSG",@ QGIS reads it and assigns the corresponding CRS (EPSG:102003) to that layer.

Consequently, the projection is considered invalid (it would act in the same way if the _.qpj_ file did not exist).

Tested in OSGeo4W installations of qgis-3.4.4-2 and qgis-dev-3.5.0-76 packages.

---

- [CRS.zip](https://issues.qgis.org/attachments/download/14204/CRS.zip) (Gabriel De Luca)

**Comment by nyalldawson** [comment]
This should be resolved in 3.8 when built with the new proj 6 library. If not, it's an issue in proj/gdal, not QGIS.

**Comment by gabriel-de-luca** [comment]
QGIS 3.8 is not relased yet. All the tickets should be solved, you can close all of them if you want.

**Comment by nyalldawson** [comment]
Thats what I've been doing - we close tickets solved in master, they don't get delayed till a final release.
