### ISSUE TITLE
Retina display now shows incorrect scale in QGIS 3.4+ for macOS

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28953]
Author Name: **Jake Bramante** (Jake Bramante)
Original Redmine Issue: [21135](https://issues.qgis.org/issues/21135)
Affected QGIS version: 3.4.0
Redmine category:osx_ui

---
With support now for Retina displays, the scale needs to be changed to accommodate the increased resolution. The export to Print Composer works correctly, but the working window shows the scale at half (or double, not sure what wording would be correct). For example, if the desired scale is 1:50,000, the print composer will show 1:50,000, but the working window will need to be set to 1:100,000 for the scale to be correct for 1:50,000. 

---

- [Map 42x30.jpeg](https://issues.qgis.org/attachments/download/14214/Map%2042x30.jpeg) (Jake Bramante)
- [Screen Shot 2019-01-30 at 3.50.37 PM.png](https://issues.qgis.org/attachments/download/14215/Screen%20Shot%202019-01-30%20at%203.50.37%20PM.png) (Jake Bramante)

**Comment by migurski** [comment]
I’ve been able to confirm this behavior in both QGIS 3.4 and 3.10.

Here’s my 1:125k PDF output, generated as a layout:

<img width="1170" alt="Screen Shot 2020-02-24 at 5 55 20 PM" src="https://user-images.githubusercontent.com/58730/75207971-170c8f80-572f-11ea-9ed6-6622157c44ac.png">

For comparison, here’s a matching screenshot from QGIS on a high-res screen at 200% magnification with an incorrect 1:250k scale:

<img width="806" alt="Screen Shot 2020-02-24 at 5 54 02 PM" src="https://user-images.githubusercontent.com/58730/75208015-360b2180-572f-11ea-96da-0d26ea4e9f33.png">

**Comment by gioman** [comment]
@migurski before using the magnifier should not the scale be locked?

**Comment by migurski** [comment]
@gioman, I don’t believe so. When the scale is set to 1:125k, the text looks substantially different from the correct print version.

**Comment by 3nids** [comment]
This issue might be related to something else: https://github.com/qgis/QGIS/issues/36847#issuecomment-669069840

**Comment by Pedro-Murteira** [comment]
Still valid on QGIS 3.24.0. (macOS Monterey 12.1)

**Comment by BryanWall** [comment]
I had to buy SwitchResX to automatically change my display settings on the built-in display on my Macbook Pro to a non-HiDPI resolution whenever I open QGIS. Setting the resolution to 1900x1200 causes QGIS to work properly with no scaling issues. Using any of the default resolutions available from the OS causes different layers of the project to be displayed at different sizes. This causes features on a vector layer to not align correctly with a tile layer, for example.

**Comment by gioman** [comment]
> his causes features on a vector layer to not align correctly with a tile layer, for example.

@BryanWall this should have been fixed recently in 3.24, have you tested it?

**Comment by BryanWall** [comment]
> > his causes features on a vector layer to not align correctly with a tile layer, for example.
> 
> @BryanWall this should have been fixed recently in 3.24, have you tested it?

I had updated to 3.24 but didn't realize this had been fixed. I just texted it and it does seem to be resolved. Thanks for replying here or I might not have realized it was fixed in this version since my machine was auto-switching resolutions to compensate.

**Comment by gioman** [comment]
I guess we can close this?
