### ISSUE TITLE
Crash when reconnecting to remote desktop session

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28954]
Author Name: **Nick Vaughn** (Nick Vaughn)
Original Redmine Issue: [21136](https://issues.qgis.org/issues/21136)
Affected QGIS version: 3.4.4
Redmine category:windows_package
Assignee: Jürgen Fischer

---
## User Feedback

I run QGIS in a remote desktop session, connecting to a virtual machine running Windows Server 2016. Most times I disconnect and reconnect to this session the QGIS instance crashes like this.

I thought it was the older vesion of QGIS I was using (3.2.3), but the machine administrator just upgraded to this newer version and still a crash.

I connect with Xtralogic RDP Client (Chrome browser extension) on my Pixelbook. QGIS is the only program that experiences this, so I suspect it is just the sudden change in some resource that QGIS depends upon.

## Report Details

*Crash ID*: ad0ca5ce48ad6f9eed3256b17fadbf3c1b5f6dbb

*Stack Trace*
```
memcpy :
VSICreateCachedFile :
RawRasterBand::AccessLine :
RawRasterBand::IReadBlock :
GDALRasterBand::GetLockedBlockRef :
GDALRasterBand::IRasterIO :
RawRasterBand::IRasterIO :
GDALRasterBand::RasterIO :
dataCapabilities :
QgsMultiBandColorRenderer::block :
QgsBrightnessContrastFilter::block :
QgsHueSaturationFilter::block :
QgsRasterResampleFilter::block :
QgsRasterProjector::block :
QgsRasterIterator::readNextRasterPart :
QgsRasterDrawer::draw :
QgsRasterLayerRenderer::render :
QgsMapRendererParallelJob::renderLayerStatic :
QgsArchive::zip :
QgsImageOperation::overlayColor :
QgsArchive::zip :
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

```

*QGIS Info*
QGIS Version: 3.4.4-Madeira
QGIS code revision: f6ddc62fdb
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.0
Running against GDAL: 2.4.0

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.14393

**Comment by roya0045** [comment]
Might be a local issue or hard to replicate. Is it still valid at least?

**Comment by gioman** [comment]
Closing for lack of feedback.
