### ISSUE TITLE
scroll wheel does not respond until 3rd click

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28956]
Author Name: **garret w** (garret w)
Original Redmine Issue: [21138](https://issues.qgis.org/issues/21138)
Affected QGIS version: 3.4.4
Redmine category:map_canvas

---
When using the scroll wheel to zoom in and out of map, response is lagged. Typically it wont respond until the 3rd click. Additionally on occasion, the view will jump back to the original scale/view after having zoomed in or out.

**Comment by roya0045** [comment]
Is this just a faulting mouse?

**Comment by gioman** [comment]
Closing for lack of feedback.
