### ISSUE TITLE
Save edits button remains grayed-out when tracing is on

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28955]
Author Name: **garret w** (garret w)
Original Redmine Issue: [21137](https://issues.qgis.org/issues/21137)
Affected QGIS version: 3.6.0
Redmine category:digitising

---
When adding a new feature, using tracing the save button remains grayed-out so you can not save edits until you opt to turn off editing.

**Comment by uclaros** [comment]
This does not seem reproducible in 3.6 nor 3.10.2 on windows nor master on Linux.

**Comment by gioman** [comment]
Closing for lack of feedback.
