### ISSUE TITLE
copy layer to scratch layer

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28983]
Author Name: **Tobias Wendorff** (Tobias Wendorff)
Original Redmine Issue: [21165](https://issues.qgis.org/issues/21165)

Redmine category:unknown

---
In many cases it's useful to copy a "physical" layer into memory (a scratch layer). For exammple, when you've run a SQL query through DB manager, the created layer can't be edited. Also, memory layers can give a huge speed boost from slow sources.

Instead of using copy+paste, it would be nice to have a function "copy to scratch layer".

Right now, I'm using _Merge vector layers_ for this. It works as expected, but it adds two non-wanted columns.

**Comment by alexbruy** [comment]
You can copy features and paste them as new memory layer. Does this solve your issue?
