### ISSUE TITLE
xyz tile matrix error for zoom max levels above 22

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28987]
Author Name: **Jean Weber** (Jean Weber)
Original Redmine Issue: [21169](https://issues.qgis.org/issues/21169)
Affected QGIS version: 3.4.4
Redmine category:web_services_clients/xyz

---
xyz tiles are not rendered for zoom levels above 22. The problem is a wrong tile matrix for zoom levels above 22.
for zoom min = 20 and zoom max= 24 I have tile matrix properties as shown on the picture attached hereafter:
![tilematrix.jpg](https://issues.qgis.org/attachments/download/14239/tilematrix.jpg)

---

- [tilematrix.jpg](https://issues.qgis.org/attachments/download/14239/tilematrix.jpg) (Jean Weber)

**Comment by gioman** [comment]
Is this still true on the most recent releases?
