### ISSUE TITLE
Creating a new map set with GRASS 7.4

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28992]
Author Name: **Edward Stevenson** (Edward Stevenson)
Original Redmine Issue: [21174](https://issues.qgis.org/issues/21174)
Affected QGIS version: 3.7(master)
Redmine category:unknown

---
While trying to export my map from QGIS 3.4.4 to AutoCAD (Covadis) as a dxf with elevation data I have found an instructional video (https://www.youtube.com/watch?v=JxCxBREEqG0) which asks to create a new GRASS mapset but QGIS crashes every time I try this. Here are the details QGIS gives me

Crash ID: f3b94088ad28fd40600a5d0e06b9c43ac6243e50

Stack Trace

RtlRaiseStatus :
memset :
setjmpex :
G_fatal_error :
G_getenv :
read_datum_table :
GPJ_osr_to_grass :
GPJ_wkt_to_grass :
version :
version :
QMetaObject::activate :
QWizard::subTitleFormat :
QWizard::next :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.4.4-Madeira
QGIS code revision: f6ddc62fdb
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.0
Running against GDAL: 2.4.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by nyalldawson** [comment]
I can't reproduce on recent QGIS versions
