### ISSUE TITLE
QGIS crashes when  opening the attribute table in form view mode

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28993]
Author Name: **Stafano Baccaro** (Stafano Baccaro)
Original Redmine Issue: [21175](https://issues.qgis.org/issues/21175)
Affected QGIS version: 3.5(master)
Redmine category:attribute_table

---
*New description:*

steps to replicate:

set the default table view mode to "form view".

Open the attached project (for some reason it only opens without any bad layer only on Windows, possibly has some datasource that Linux does not like)

open the attributes table by right clicking the layer "quadri" --> Ok

open the attributes table from the toolbar --> crash

affected 3.4.4 and master

*Old description:*

## User Feedback

SYSTEM:
Windows 10 PRO 1803 Buid 17134.556

Project with Spataialite tables. Related to each other by PK-FK.
If I open the Attribute Table with the [Layer] menu [Open Attribute Table] 
or with the button in the button bar, the program stops and displays the 
following error, but in most cases the program freezes and closes without 
showing no error message (## Report Details). In the latter case, the windows event log reports 
an error of this type:
						--------------------------------------------------------------------------------------------------------
						Nome dell'applicazione che ha generato l'errore: qgis-bin.exe, versione: 0.0.0.0, timestamp: 0x5c42c0cf
						Nome del modulo che ha generato l'errore: ucrtbase.dll, versione: 10.0.17134.319, timestamp: 0x40b70dec
						Codice eccezione: 0xc0000409
						Offset errore 0x000000000006e57e
						ID processo che ha generato l'errore: 0xd40
						Ora di avvio dell'applicazione che ha generato l'errore: 0x01d4bd56c39e711b
						Percorso dell'applicazione che ha generato l'errore: C:\Program Files\QGIS 3.4\bin\qgis-bin.exe
						Percorso del modulo che ha generato l'errore: C:\WINDOWS\System32\ucrtbase.dll
						ID segnalazione: c270c3b9-b396-4ba4-aaf8-b14cba47f486
						Nome completo pacchetto che ha generato l'errore: 
						ID applicazione relativo al pacchetto che ha generato l'errore: 
						--------------------------------------------------------------------------------------------------------
Otherwise if I open the Attribute Table using the mouse context menu (right click) and choose 
the "Open Attribute Table" command, QGIS does not stop responding.

The same problem can also be found on other computers with the same QGIS installation.

## Report Details

*Crash ID*: 1ddc9933fe0b22cbad7654705f5e1bc061ef4b22

*Stack Trace*
```
QgsFeatureStore::setFields :
QgsFeatureFilterModel::displayExpression :
QgsFeatureFilterModel::updateCompleter :
QMetaCallEvent::placeMetaCall :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

```

*QGIS Info*
QGIS Version: 3.4.4-Madeira
QGIS code revision: f6ddc62fdb
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.0
Running against GDAL: 2.4.0

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

---

- [ERRORE QGIS - Apertura Tabelle Attributi.zip](https://issues.qgis.org/attachments/download/14244/ERRORE%20QGIS%20-%20Apertura%20Tabelle%20Attributi.zip) (Stafano Baccaro)
- [Video 1 - 2.zip](https://issues.qgis.org/attachments/download/14273/Video%201%20-%202.zip) (Stafano Baccaro)
- [Video 3 - 4.zip](https://issues.qgis.org/attachments/download/14274/Video%203%20-%204.zip) (Stafano Baccaro)

**Comment by Pedro-Murteira** [comment]
I can no longer reproduce this issue on QGIS 3.22.3. (Windows 10).
