### ISSUE TITLE
Layer Properties 'displayed as' value shows CamelCase Layer name, but is never used?

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29008]
Author Name: **Richard Duivenvoorde** (@rduivenvoorde)
Original Redmine Issue: [21190](https://issues.qgis.org/issues/21190)
Affected QGIS version: 3.5(master)
Redmine category:gui

---
See screenshot and Subject.

Having a raster layer loaded, and opening the Layer Properties / Source-tab, I can edit a 'Layer name', next to it there is a not-editable input with 'displayed as' next to it.

If I type 'foo dot bar' in the input, the 'display name' shows: 'Foo Dot Bar', but upon OK'ing of the dialog my layername shown in the legend is just 'foo dot bar', which is what I actually want :-) If I wanted a CamelCase name I would have given that....

I'm asking myself what the purpose is of that 'display name', as (at least for what I see) that name is not shown anywhere??

---

- [LayerName.png](https://issues.qgis.org/attachments/download/14254/LayerName.png) (Richard Duivenvoorde)

**Comment by nyalldawson** [comment]
This is removed in https://github.com/qgis/QGIS/pull/44650
