### ISSUE TITLE
GRASS 7.4.4 & QGIS 3.4.4

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29000]
Author Name: **Edward Stevenson** (Edward Stevenson)
Original Redmine Issue: [21182](https://issues.qgis.org/issues/21182)
Affected QGIS version: 3.7(master)
Redmine category:unknown

---
Futher to my report yesterday, it appears that the attributes table for my contours layer created from a USGS file 30n030w_20101117_gmted_mea075 has ID & elevation data. However, try to create a GRASS layer of the contours via the grass module (-file management-Import into GRASS-Import vector into GRASS-Import loaded Vector) the attributes table of the new grass contours layer only has cat data.

I Don't understand how I am losing this data, is it a bug or do i have the wrong proceedure?

**Comment by alexbruy** [comment]
Still an issue with 3.10/master?

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
