### ISSUE TITLE
Batch processing progress bar never completes

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29016]
Author Name: **Nigel Luckman** (Nigel Luckman)
Original Redmine Issue: [21198](https://issues.qgis.org/issues/21198)
Affected QGIS version: 3.4.5
Redmine category:processing/core

---
running batch processes for reprojections with gdalwarp
rasters are reprojected, but the batch process doesn't complete.
progress bar gets to 80 or 90% but never finishes.
progress bar continues to scroll at bottom of application even after batch processing dialog box is closed.

**Comment by alexbruy** [comment]
Is this still an issue?

**Comment by alexbruy** [comment]
Closed for the lack of feedback. Please reopen if necesary.
