### ISSUE TITLE
installation differences if you change the installation directory of QGIS (standalone version)

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29018]
Author Name: **Alain FERRATON** (@FERRATON)
Original Redmine Issue: [21200](https://issues.qgis.org/issues/21200)
Affected QGIS version: 3.4.4
Redmine category:windows_package
Assignee: Jürgen Fischer

---
If we keep the default installation directory, in the start menu we have the shortcuts: GRASS GIS 7.4.4 and QGIS desktop 3.4.4 with GRASS 7.4.4.

If we change the installation directory we have in addition:
Osgeo4w shell, QT designer, SAGA GIS (2.3.2) and setup.

Why this difference?
The additional shortcuts are very useful, in particular setup allows you to add missing libraries later on in the standalone version (like openCV).
It's not just a case of shortcuts. It seems that if you change the default installation directory there is an additional post processing.

**Comment by alexbruy** [comment]
Still true with lastest installers?

**Comment by alexbruy** [comment]
Closing for the lack of feedback. Please reopen if necessary.
