### ISSUE TITLE
']' keyboard (alt-gr + '+' ) not working on QGis 3.4.4 with Spanish or Italian keyboard - Windows

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29021]
Author Name: **Javier Becerra Elcinto** (Javier Becerra Elcinto)
Original Redmine Issue: [21203](https://issues.qgis.org/issues/21203)
Affected QGIS version: 3.4.4
Redmine category:gui

---
Running QGis 3.4.4, in a Windows 8.1 setup in Spanish, with Spanish es-es keyboard (Qwerty with '[' being alt-gr+'`' and ']' alt-gr+'+'), I can properly type '[' (alt-gr+'`') but nothing happens when I try to type ']' (alt-gr+'+').
This happens in Python Console (quite annoying actually), on Python Console's text editor or when changing a layer's name (right-click on the layer tree view on bottom left of the screen), but it works properly on dialogs shown in independent windows (i.e. open file dialog/save as...).

---

Related issue(s): #28820 (duplicates), #29800 (duplicates)
Redmine related issue(s): [21001](https://issues.qgis.org/issues/21001), [21985](https://issues.qgis.org/issues/21985)

---

**Comment by Pedro-Murteira** [comment]
I can still replicate this on QGIS 3.16.14 and 3.22.1.
