### ISSUE TITLE
no base mapping

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29023]
Author Name: **Edward Stevenson** (Edward Stevenson)
Original Redmine Issue: [21205](https://issues.qgis.org/issues/21205)
Affected QGIS version: 3.7(master)
Redmine category:unknown

---
When I 1st started with QGIS 3.4.4 I added google maps/ satellite/ relief and they worked for 2 days but now I can't see any form of mapping through the XYZ tiles.
I have reinstalled, I have deleted and redone the XYZ tiles, I have uninstalled all of my plugins and I have used EVERY single URL on  these links:
https://wiki.openstreetmap.org/wiki/Tile_servers
https://raw.githubusercontent.com/klakar/QGIS_resources/master/collections/Geosupportsystem/python/qgis_basemaps.py
And yes, switched my computer off and on again!

The latest set of instructions i am following is:
https://www.xyht.com/spatial-itgis/using-openstreetmap-basemaps-qgis-3-0/

And not a single XYZ tile loads, I have NO background mapping!

Have I somehow blocked the XYZ tiles from loading on QGIS? Has anyone else experienced a similar problem with QGIS 3.4.4?

Thanks

**Comment by kannes** [comment]
Are you still experiencing this?

Are you sure your map is in a region where tiles should appear?

Does https://plugins.qgis.org/plugins/qgisnetworklogger/ show requests happening?

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
