### ISSUE TITLE
Random marker position for marker line style

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29027]
Author Name: **Julien Monticolo** (Julien Monticolo)
Original Redmine Issue: [21209](https://issues.qgis.org/issues/21209)

Redmine category:symbology

---
For a marker style in QGIS, for the marker position, we have the choice between :
* interval
* vertex
* lastvertex
* firstvertex
* centerpoint
* curvepoint

Is-it possible to add a random position with a parameter (sort of density ?) ?

**Comment by pjshelton** [comment]
![image](https://user-images.githubusercontent.com/39154868/103430545-ff384e80-4c10-11eb-966c-3d1abbcca4db.png)
For the linear version of the dot density fill, this can be created using data defined interval,  the formula for the interval is rand(min, max),

Or is this about a single marker at a random location on the line?

**Comment by pjshelton** [comment]
On further testing, my last comment is wrong.  What I said happens does not to happen.

**Comment by pjshelton** [comment]
With even more testing I now have the code that will produce what is being asked for with this request with current (v3.16.2) functionality. 

To produce a "marker line" with one marker at a random point, you will:
 Set the 'Symbol layer type' to 'Geometry Generator'
 Set the 'Geometry type' to 'Point / MultiPoint'
 Set the expression to  'line_interpolate_point( geometry(  $currentfeature ), randf(0,1) * length( geometry( $currentfeature )))'

To create the linear version of the dot density fill, x dots randomly placed along the line, you will:
 Set the 'Symbol layer type' to 'Geometry Generator'
 Set the 'Geometry type' to 'Point / MultiPoint'
 Set the expression to  'nodes_to_points( make_line( array_foreach( generate_series( 1, x ), line_interpolate_point( geometry(  $currentfeature ), randf(0,1) * length(geometry( $currentfeature ))))))'
with the x in generate_series( 1, x ) replaced with the required number of dots.

Can we add check/radio buttons to the Marker line dialog that does the above two marker line  types?
