### ISSUE TITLE
Vector Feature Density

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29067]
Author Name: **Alejandro Pareja** (Alejandro Pareja)
Original Redmine Issue: [21249](https://issues.qgis.org/issues/21249)

Redmine category:processing/qgis

---
I suggest a tool for the density of vector features (points, lines or polygons) within a specified distance of each grid cell in a raster. Similar to ArcGIS line density and Whitebox GAT Vector Feature Density and Vector Attribute Gridding.

**Comment by alexbruy** [comment]
There is a Line Density algorithm in Processing. Does it fulfils you needs?
