### ISSUE TITLE
QGIS 3 Layer Filter error with Unicode field name

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29068]
Author Name: **Heather  Hillers** (Heather  Hillers)
Original Redmine Issue: [21250](https://issues.qgis.org/issues/21250)
Affected QGIS version: 3.5(master)
Redmine category:vectors

---

Hello,

If a user has a shape file with a field name that has an Umlaut in it ("EIGENTÜMER") and they make a Filter on that layer "EIGENTÜMER" = 'MEINFIRMA'  then the attribute table will correctly reflect the filter (with many returns) but no geometries will appear on the canvas.  Filtering by a field with a normal ASCII name results in normal behavior.  (I have warned the user that field names should never have unicode in them.)  

---

- [test.qpj](https://issues.qgis.org/attachments/download/14306/test.qpj) (Heather  Hillers)
- [test.prj](https://issues.qgis.org/attachments/download/14307/test.prj) (Heather  Hillers)
- [test.shp](https://issues.qgis.org/attachments/download/14308/test.shp) (Heather  Hillers)
- [test.dbf](https://issues.qgis.org/attachments/download/14309/test.dbf) (Heather  Hillers)
- [test.shx](https://issues.qgis.org/attachments/download/14310/test.shx) (Heather  Hillers)
- [Screenshot_20190213_152700.png](https://issues.qgis.org/attachments/download/14313/Screenshot_20190213_152700.png) (Alessandro Pasotti)

**Comment by nyalldawson** [comment]
This is no longer reproducible
