### ISSUE TITLE
Python3 error when running GRASS 7.6 tools in processing on mac OS 

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29087]
Author Name: **Alejandro Garcia** (Alejandro Garcia)
Original Redmine Issue: [21269](https://issues.qgis.org/issues/21269)
Affected QGIS version: 3.4.4
Redmine category:processing/grass
Assignee: William Kyngesburye

---
The Grass algorithm r.contour in the toolbox does not work and stop with an error message.

qgis 3.4.4 / grass 7.6 / macOS  10.14.3

---

- [Log Grass r.contours.rtf](https://issues.qgis.org/attachments/download/14331/Log%20Grass%20r.contours.rtf) (Alejandro Garcia)
- [Screen Shot 2019-02-13 at 9.11.12 AM_2.png](https://issues.qgis.org/attachments/download/14332/Screen%20Shot%202019-02-13%20at%209.11.12%20AM_2.png) (Alejandro Garcia)

**Comment by PeterPetrik** [comment]
The bug is not present in all-in-one MacOS packages @gioman

**Comment by gioman** [comment]
> The bug is not present in all-in-one MacOS packages @gioman

so we should close this?
