### ISSUE TITLE
Comments in SQL query in DB Manager breaks the query

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29089]
Author Name: **Nikolay Lebedev** (Nikolay Lebedev)
Original Redmine Issue: [21271](https://issues.qgis.org/issues/21271)
Affected QGIS version: 3.5(master)
Redmine category:db_manager

---
SQL comments are highlighted in the editor, however they break SQL execution.
Easy to replicate: add a comment after SELECT clause before selected fields.

**Comment by kannes** [comment]
The PR https://github.com/qgis/QGIS/pull/9183 was merged so I *guess* this could be closed?

**Comment by kannes** [comment]
Oh no, the fix is just a partial fix.

Example query that is still broken in 3.6.3:

```
SELECT
  *  -- a comment
FROM
  poi;
```

results in Database Error:

```
FEHLER:  SELECT * ist nicht gültig, wenn keine Tabellen angegeben sind
LINE 1: SELECT   *  -- a comment FROM   poi;
                 ^
```

**Comment by kannes** [comment]
And
```
SELECT
  *
  -- a comment
FROM
  poi;
```
gets turned into
`SELECT   * FROM   poi `
losing the comment.
