### ISSUE TITLE
return arrays with aggregate and relation_aggregate

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29092]
Author Name: **mathieu rajerison** (mathieu rajerison)
Original Redmine Issue: [21274](https://issues.qgis.org/issues/21274)

Redmine category:field_calculator

---
Hi

I hope there will not be any duplicate with this FR

I thought it would be nice that aggregate and relation_aggregate return array objects

**Comment by suricactus** [comment]
There is already a functions that returns an array and behaves like "aggregate".
```
array_agg( "fid" )
-- > [1, 2, 3]
```
What is missing an equivalent of `relation_aggregate`.

**Comment by m-kuhn** [comment]
Replaced by https://github.com/qgis/QGIS/issues/40020
