### ISSUE TITLE
SVG icon size and position on macOS

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29103]
Author Name: **Massimiliano Cannata** (Massimiliano Cannata)
Original Redmine Issue: [21285](https://issues.qgis.org/issues/21285)
Affected QGIS version: 3.4.4
Redmine category:mac_os_specific

---
Under MAC OS Sierra,
the position and dimension of SVG icons between the Desktop and the Composer, with the same fixed scale factor, is not respected. 
The same identical project, under Linux 18.08 perfectly works.
See attached images for clarification.

Additionally, when varying the SVG dimension size (width / height) in MAC it seems the setting is saved, but the input box doesn't keep the new setting and show previous values.

---

- [Screenshot from 2019-02-15 14-41-37.png](https://issues.qgis.org/attachments/download/14347/Screenshot%20from%202019-02-15%2014-41-37.png) (Massimiliano Cannata)

**Comment by gioman** [comment]
Done a quick test on 3.14.0 on Catalina and seems ok to me, can you please check again?

**Comment by PeterPetrik** [comment]
this is maybe duplicate of https://github.com/qgis/QGIS/issues/28953
