### ISSUE TITLE
QGIS flatpack crashes when opening 3d View (Ubuntu 16.04)

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29116]
Author Name: **Matthias Siewert** (@MatthiasSiewert)
Original Redmine Issue: [21298](https://issues.qgis.org/issues/21298)
Affected QGIS version: 3.4.4
Redmine category:3d

---
QGIS flatpack crashed when opening 3d View.

On Ubuntu 16.04 using NVIDIA GeForce GT 1030 PCI and 410.79 driver. 

terminal message:
Fatal: Could not initialize GLX
QGIS died on signal -1Warning: QObject::connect: invalid null parameter

**Comment by PeterPetrik** [comment]
It is impossible to replicate without project and exact steps. Please provider reproducible example data and step

**Comment by gioman** [comment]
Closing for lack of further feedback.
