### ISSUE TITLE
Buffer layer styling with geometry generator

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29119]
Author Name: **Maxime RIOU** (Maxime RIOU)
Original Redmine Issue: [21301](https://issues.qgis.org/issues/21301)
Affected QGIS version: 3.6.0
Redmine category:map_tools

---
When styling a vector file using geometry generator and buffer ( buffer( $geometry, 15) for example) , the size of the icon in the layers panel becomes very large compared with other layers' icons.
Nota: this issue does not occur for legend in composer.

**Comment by gioman** [comment]
Duplicate of https://github.com/qgis/QGIS/issues/33755
