### ISSUE TITLE
concatenator doesn't work when not in print layout mode, for instance in virtual field

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29115]
Author Name: **mathieu rajerison** (mathieu rajerison)
Original Redmine Issue: [21297](https://issues.qgis.org/issues/21297)
Affected QGIS version: 3.4.4
Redmine category:expressions

---
Hi,

I've noticed that the concatenator argument didn't work when in virtual field

It's the case for :
* concatenate
* aggregate
* relation_aggregate

So, 
```
concatenate(tostring("fid"), concatenator:=',')

``` 
doesn't work
(see attached file)

But when I type
```
concatenate('a string', concatenator:=',')

```
it's ok

In composer/print layout mode, it works well

---

- [temp field.png](https://issues.qgis.org/attachments/download/14356/temp%20field.png) (mathieu rajerison)

**Comment by gioman** [comment]
Seems to work fine to me on recent releases.
