### ISSUE TITLE
Profiles from Lines, SAGA tool, produces invalid files. 

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29112]
Author Name: **Gabriel De Luca** (@gabriel-de-luca)
Original Redmine Issue: [21294](https://issues.qgis.org/issues/21294)
Affected QGIS version: 3.4.4
Redmine category:processing/saga
Assignee: Giovanni Manghi

---
The _Profiles from Lines_ SAGA tool produces invalid files.  

In SAGA GIS, at the command line (@ta_profile 4@):  

* If you want to save _Each Line as a New Profile_, you need to use the `-SPLIT` and the `-PROFILES` options. Files will be saved as _profile_01.shp_, _profile_02.shp_, etc.  

* If not, don't use `-SPLIT` option and use `-PROFILE` option instead. File will be saved as _profile.shp_.  

In QGIS, processing toolbox:  

* Both `-PROFILE` and `-PROFILES` options are always used, so one of them always returns an error (an empty layer that can not be loaded).  

* If you tick on _Each Line as a New Profile_ (is ticked by default), `-SPLIT` option is used, and the files are saved as _PROFILE.shp1_, _PROFILE.shp2_, etc. That produced two errors (one for the `-PROFILE` empty layer and other for the invalid extensions).

**Comment by gioman** [comment]
Fixed by https://github.com/qgis/QGIS/pull/41286
