### ISSUE TITLE
Consideration of CPG files for encoding shape files

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29131]
Author Name: **Alain FERRATON** (@FERRATON)
Original Redmine Issue: [21313](https://issues.qgis.org/issues/21313)

Redmine category:gui

---
I read the different tickets on how QGIS takes into account the encoding of SHP files.
I don't feel like I'm finding a very clear position.

In my opinion, the option to ignore the internal encoding instruction of the shape file should be renamed:
Disables on-the-fly conversion of encoding to UTF-8 (which the tooltip displays).

If this option is disabled, QGIS must take into account the presence of a CPG file and propose by default the encoding corresponding to the opening of the file instead of the last encoding used. The absence of a CPG file must be reported to the user.

---

Related issue(s): #21264 (relates)
Redmine related issue(s): [13203](https://issues.qgis.org/issues/13203)

---

**Comment by nyalldawson** [comment]
This was fixed
