### ISSUE TITLE
Topology checker does not checks gaps and overlaps

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29136]
Author Name: **Vladimír Hans** (Vladimír Hans)
Original Redmine Issue: [21318](https://issues.qgis.org/issues/21318)
Affected QGIS version: 3.5(master)
Redmine category:c++_plugins/topology_checker

---
If I try check gap checker shows that gap was fixed but really nothing happen. Similar situation is in fixing overlaps. Checker tell me that overlap is obsolete. Testing data are in attachment.

---

- [test.zip](https://issues.qgis.org/attachments/download/14364/test.zip) (Vladimír Hans)

**Comment by Pedro-Murteira** [comment]
Can still reproduce this issue on QGIS 3.16.14 and 3.22.1.
