### ISSUE TITLE
Draw Effects not saved 

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29138]
Author Name: **Tim Meijer** (Tim Meijer)
Original Redmine Issue: [21320](https://issues.qgis.org/issues/21320)
Affected QGIS version: 3.4.4
Redmine category:symbology

---
When saving the Layer Properties> Symbology of an GPX track, composed of Simple Lines and some SVG markers, as a Style, the "Draw Effects" off the Simple Line are not saved.

Recalling the saved Style, under "Layer Properties"> "Symbology" shows the "Drawing effects" unchecked. And the the values set in "Draw effects" are lost.

**Comment by nyalldawson** [comment]
Can you share a screencast showing how to reproduce this issue? I'm unable to reproduce.
