### ISSUE TITLE
Source Fields returns wrong description of attribute table

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29141]
Author Name: **Tobias Wendorff** (Tobias Wendorff)
Original Redmine Issue: [21323](https://issues.qgis.org/issues/21323)
Affected QGIS version: 3.5(master)
Redmine category:vectors

---
1. Create a temporary scratch layer
2. Create a text field with unlimited length
3. Insert this text: @string	layer	path
This is a slightly longer text to check if the string processing by "Processing" works properly. Unfortunately, there are currently problems with the processing of numeric fields - hopefully not even with strings with more than 255 characters. Let's see what happens when we exceed magic limits imposed by the proprietary DBF format in the past.@
4. Check_ Layer Properties > Source Fields_: The length of the field is fixed to 255, while the text is much longer.

**Comment by gioman** [comment]
This seems not relevant anymore.
