### ISSUE TITLE
Graphical Builder - Link between Expression Paramenter and Table/Vector Field

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29155]
Author Name: **Hans-Peter Klossek** (Hans-Peter Klossek)
Original Redmine Issue: [21337](https://issues.qgis.org/issues/21337)

Redmine category:processing/modeller

---
Hello folks, 

 I have a feature request: 

It would be nice to implement a link between the input parameter 'expression' and 'table/vector field' so it is useable for a dynamic workflow with a parameter like '@field_namen' inside of a expression. I have tried this in the field calculator, it is working only for the column name but the field values go in the 'null-nirvana'.

Thanks and best regards, Hape

---

- [example.jpg](https://issues.qgis.org/attachments/download/14380/example.jpg) (Hans-Peter Klossek)

**Comment by alexbruy** [comment]
Closing as required behaviour can be implemented with expression.
