### ISSUE TITLE
Detached 3D view crash [macOS]

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29169]
Author Name: **Peter Petrik** (@PeterPetrik)
Original Redmine Issue: [21351](https://issues.qgis.org/issues/21351)
Affected QGIS version: 3.5(master)
Redmine category:3d

---
1. When new (detached) 3D view is created and closed it crashes QGIS.
2. When new (detached) 3D view is created and docked (anywhere), 3d canvas disappears. But one can identify something in gray canvas, so it is not completely off.

Workaround how to work with 3D on MacOS now is to 
1) Create detached 3D view
2) Dock it somewhere
3) Persist QGIS project to the disk
4) restart QGIS -> now docked 3D view has working 3D canvas and nothing is crashing

This is probably specific to MacOS, not able to replicate on Linux.

**Comment by PeterPetrik** [comment]
unable to replicate any more with QT 5.12.3
