### ISSUE TITLE
Assign different color ramps to selected classes

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29164]
Author Name: **Dale Jenner** (@toasthall)
Original Redmine Issue: [21346](https://issues.qgis.org/issues/21346)

Redmine category:symbology

---
It would be useful to be able to select certain classes in a layers symbology and assign different colour ramps.

**Comment by roya0045** [comment]
Pretty sure this can be done with rule-based symbology.

**Comment by gioman** [comment]
Agree, as it is described is a functionality available since long ago.
