### ISSUE TITLE
Can't visualize jpg files on Windows

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29160]
Author Name: **Mattia Fabbri** (Mattia Fabbri)
Original Redmine Issue: [21342](https://issues.qgis.org/issues/21342)
Affected QGIS version: 3.4.5
Redmine category:rasters

---
Hello everybody,

I'm running the Qgis version 3.4.4, but I had the same problem with 3.4.1, on a Core i5 with Windows 10 system.

When i try to open a .jpg file as a vector or in the georeferencer, all i got is these kind of images (depending on the zoom) you can see below:

![image](http://rabanarx.altervista.org/bug1.jpg)

![image](http://rabanarx.altervista.org/bug2.jpg)

![image](http://rabanarx.altervista.org/bug3.jpg)

---

- [Screenshot_20190307_175314.png](https://issues.qgis.org/attachments/download/14545/Screenshot_20190307_175314.png) (Giovanni Manghi)

**Comment by Charmatzis** [comment]
This issue is still exists in 3.8.1 64 bit QGIS in Win 10.

**Comment by alexbruy** [comment]
Is this  valid with latest master/3.10?

**Comment by alexbruy** [comment]
Closed for the lack of feedback. Please reopen if necessary.
