### ISSUE TITLE
Processing - Export to PostgreSQL (available connections)

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29174]
Author Name: **Rocco Pispico** (Rocco Pispico)
Original Redmine Issue: [21356](https://issues.qgis.org/issues/21356)
Affected QGIS version: 3.4.4
Redmine category:processing/gdal
Assignee: Giovanni Manghi

---
This script has several problems especially when use _iterate over..._
- doesn't create multiple layers but only a single layer, if overwrite is checked remain only the last feature;
- if the source layer is a postgres layer, the name of new one layer is a concatenation of <new schema>.<source schema>.<table name> instead of <new schema>.<table name>;
- if the source is postgres doesn't check if source layer and new layer are the same.

I think that the names of output layers could be created in a _composer_ in order to have maximum flexibility.

Finally two cosmetic wish:
-  the counter goes from 0 to number of feature instead from 1 to number of feature;
- change the iterator icon is in a checkbox widget.

**Comment by alexbruy** [comment]
As asked by Giovanni, please file separate tickets for each issue, attach sample data and describe how to reproduce it.
