### ISSUE TITLE
QGIS 3.4 is unable to locate datasources from a project created with version 2.18

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29181]
Author Name: **MRick -** (MRick -)
Original Redmine Issue: [21364](https://issues.qgis.org/issues/21364)
Affected QGIS version: 3.4.4
Redmine category:project_loading/saving
Assignee: Alessandro Pasotti

---
I have several projects created with previous version such as version 2.18.

When opening them in QGIS 3.4, QGIS will ask to finds the different files missing, while it doesn't in 2.18.
For big project with a lot of different files it can become very irritating.

But moreover, when locating the files, QGIS will ask again and again were they are. It is never ending and you will have to import manually all of them one by one losing all the settings from the project…
No problem to open any of them in 2.18, whatever the computer or the OS is. Only QGIS 3.4 will give troubles.

---

- [Capture d’écran 2019-02-23 à 22.41.56.png](https://issues.qgis.org/attachments/download/14435/Capture%20d%E2%80%99%C3%A9cran%202019-02-23%20%C3%A0%2022.41.56.png) (MRick -)
- [Capture d’écran 2019-02-23 à 22.42.05.png](https://issues.qgis.org/attachments/download/14440/Capture%20d%E2%80%99%C3%A9cran%202019-02-23%20%C3%A0%2022.42.05.png) (MRick -)
- [Capture d’écran 2019-02-23 à 22.42.09.png](https://issues.qgis.org/attachments/download/14441/Capture%20d%E2%80%99%C3%A9cran%202019-02-23%20%C3%A0%2022.42.09.png) (MRick -)
- [Capture d’écran 2019-02-23 à 22.42.15.png](https://issues.qgis.org/attachments/download/14442/Capture%20d%E2%80%99%C3%A9cran%202019-02-23%20%C3%A0%2022.42.15.png) (MRick -)
- [Capture d’écran 2019-02-23 à 22.42.22.png](https://issues.qgis.org/attachments/download/14443/Capture%20d%E2%80%99%C3%A9cran%202019-02-23%20%C3%A0%2022.42.22.png) (MRick -)
- [Test.7z](https://issues.qgis.org/attachments/download/14611/Test.7z) (MRick -)
- [Capture d’écran 2019-03-17 à 21.40.16.png](https://issues.qgis.org/attachments/download/14612/Capture%20d%E2%80%99%C3%A9cran%202019-03-17%20%C3%A0%2021.40.16.png) (MRick -)
- [Capture d’écran 2019-03-17 à 21.36.14.png](https://issues.qgis.org/attachments/download/14613/Capture%20d%E2%80%99%C3%A9cran%202019-03-17%20%C3%A0%2021.36.14.png) (MRick -)
- [Capture d’écran 2019-03-17 à 21.36.14.png](https://issues.qgis.org/attachments/download/14614/Capture%20d%E2%80%99%C3%A9cran%202019-03-17%20%C3%A0%2021.36.14.png) (MRick -)
- [readXml error.txt](https://issues.qgis.org/attachments/download/14615/readXml%20error.txt) (MRick -)
- [crash log.txt](https://issues.qgis.org/attachments/download/14616/crash%20log.txt) (MRick -)

**Comment by gioman** [comment]
Cannot confirm with the attached sample project and data: the project is looking for the datasources in subfolders, but the data is not there.
