### ISSUE TITLE
Fails to build with GUI disabled

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29185]
Author Name: **Tom Palan** (@tpalan)
Original Redmine Issue: [21368](https://issues.qgis.org/issues/21368)
Affected QGIS version: 3.4.4
Redmine category:build/install
Assignee: Alessandro Pasotti

---
For building the QGIS server without Desktop app the following cmake command works:

cmake -G Ninja \
      -DCMAKE_VERBOSE_MAKEFILE=1 \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DBINDINGS_GLOBAL_INSTALL=TRUE \
        -DPEDANTIC=TRUE \
        -DSERVER_SKIP_ECW=TRUE \
        -DQGIS_CGIBIN_SUBDIR=/usr/lib/cgi-bin \
        -DWITH_APIDOC=TRUE \
        -DGENERATE_QHP=TRUE \
        -DWITH_CUSTOM_WIDGETS=FALSE \
        -DWITH_GLOBE=FALSE \
        -DWITH_SERVER=TRUE \
        -DWITH_SERVER_PLUGINS=TRUE \
        -DWITH_QWTPOLAR=FALSE \
        -DWITH_DESKTOP=FALSE \
        -DWITH_GUI=TRUE \
        -DDOXYGEN_ON_DEMAND=TRUE ..

But when disabling the GUI (WITH_GUI=FALSE), the build fails with error message:
ninja: error:
'../python/plugins/db_manager/db_plugins/postgis/plugins/versioning/pyg
ui', needed by
'python/plugins/db_manager/db_plugins/postgis/plugins/versioning/ui_Dlg
Versioning.py', missing and no known rule to make it

**Comment by nyalldawson** [comment]
Not an issue anymore

**Comment by tpalan** [comment]
This is still an issue, when building with:
`cmake .. -DWITH_SERVER=TRUE -DWITH_GUI=FALSE -DWITH_DESKTOP=FALSE && make -j8`
the build still fails with error:

make[2]: *** No rule to make target '../python/plugins/db_manager/pygui', needed by 'python/plugins/db_manager/ui_DlgAddGeometryColumn.py'.  Stop.

I added a commit, it is references above.
