### ISSUE TITLE
Assigning a primary key in QgsDataSourceUri doesn't work

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29214]
Author Name: **Patrice V** (Patrice V)
Original Redmine Issue: [21397](https://issues.qgis.org/issues/21397)
Affected QGIS version: 3.4.5
Redmine category:python_bindings_/_sipify

---
Hi devs,

I use qgis 3.4.5 with windows 7 64bit.

I build a qgsvectorlayer like this :
uri = qgis.core.QgsDataSourceUri()
uri.setDatabase('a_sqlite_file')
uri.setDataSource('', 'SELECT * FROM MyTable', 'geom' ,'','the_pk_column_name')
vlayer = qgis.core.QgsVectorLayer(uri.uri(), tablename, 'spatialite')

When I ask the id of the features in vlayer ([fet.id() for fet in vlayer.getFeatures()]), it returns the  value of the first column of 'MyTable', and not the value of the 'the_pk_column_name' column...

it was working nicely in 2.18....

thank you in advance,

---

Related issue(s): #29486 (duplicates)
Redmine related issue(s): [21670](https://issues.qgis.org/issues/21670)

---

**Comment by patricev** [comment]
Another note : 
1 - Assigning a primary key with dbmanager is working with postgis dbase, but not with spatialite
2 - Assigning a primary key  is working with spatialite when i create a virtual layer

**Comment by gioman** [comment]
@patricev still true?

**Comment by Pedro-Murteira** [comment]
@patricev is it still valid on recent releases?

**Comment by patricev** [comment]
@Pedro-Murteira it's been a long time I haven't tested this. I suggest to no longer consider this ticket. Regards
