### ISSUE TITLE
Feature Count unavailable for geopackage layers displayed after running a processing algorithm

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29215]
Author Name: **Joseph Holler** (@josephholler)
Original Redmine Issue: [21398](https://issues.qgis.org/issues/21398)
Affected QGIS version: 3.4.4
Redmine category:processing/core

---
I'm running 3.4.4 on Windows 10. 
I am saving the output of any processing algorithm or model (for example, specifically testing with the QGIS Centroids algorithm and one of my own graphic models) to an existing geodatabase with the Save to geopackage... option for outputs. I'm using the "open file output after running algorithm" option to add the layer to the map automatically. The resulting layer always displays 0 features for the feature count with the "show feature count" option in the Layers panel.
The same table added directly from the geopackage later DOES display a correct feature count.
The same operation (Centroids) saved as a shapefile and opened after running algorithm DOES display a correct feature count. 
The issue thus seems isolated to the combination of saving a geopackage layer and having it automatically displayed after the algorithm runs.

**Comment by gioman** [comment]
Works ok on the latest master.
