### ISSUE TITLE
QGIS crashes using QSqlDatabase connecting to PostGIS

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29218]
Author Name: **Attila Peller** (@atisnz)
Original Redmine Issue: [21401](https://issues.qgis.org/issues/21401)
Affected QGIS version: 3.4.4
Redmine category:data_provider/postgis

---
We have a plugin which connects to both MSSQL and Postgis database. The plugin processes data from MSSQL and visualise them in QGis and stores results on Postgis. QGis regulary crashes with the same error blaming qsqlpsql.dll and leaves an event log behind. 

The event log says:
Faulting application name: qgis-bin.exe, version: 0.0.0.0, time stamp: 0x5c4bcf50
Faulting module name: qsqlpsql.dll, version: 5.11.2.0, time stamp: 0x5b99eaa0
Exception code: 0xc000041d
Fault offset: 0x0000000000002805
Faulting process id: 0x12f0
Faulting application start time: 0x01d4ce23e728a0b9
Faulting application path: C:\OSGEO4~2\bin\qgis-bin.exe
Faulting module path: C:\OSGEO4~2\apps\qt5\plugins\sqldrivers\qsqlpsql.dll
Report Id: 12ed419a-3a3a-11e9-8105-000c2942e70f
Faulting package full name: 
Faulting package-relative application ID: 

---

- [crash.txt](https://issues.qgis.org/attachments/download/14466/crash.txt) (Attila Peller)

**Comment by Pedro-Murteira** [comment]
@atisnz Hello, is this still valid on more recent release?
