### ISSUE TITLE
Ability to add processing tools as favorites

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29220]
Author Name: **Topi Tjukanov** (@tjukanovt)
Original Redmine Issue: [21403](https://issues.qgis.org/issues/21403)

Redmine category:processing/gui

---
The processing toolbox is becoming so massive, that it would probably be helpful for many users to be able to create some kind of "My favorite tools" section inside the Processing toolbox. Especially for less experienced users this might be helpful as 

Basic functionality could be just like with "Recently used" tools, but different tools could be added there manually (e.g. with a right-click). So a separate section on top of the processing toolbox list.

**Comment by M5610020** [comment]
I was looking for a similar one. Is it possible to create "My fav tools" collection?

**Comment by JaWue85** [comment]
Would be really nice to have! Especially for users who do not use it every day!

**Comment by gioman** [comment]
@JaWue85 @tjukanovt

You can have your favorite Processing tools added organized in a toolbar, isn't enough?


![image](https://user-images.githubusercontent.com/1951107/148386630-4f21dd70-c77a-48d3-bc7d-c2e965875594.png)

**Comment by jfbourdon** [comment]
I'm now less interested in a "My fav tools" collection than I once was, but I still see a use for occasional users forgetting the name of some tools.

> You can have your favorite Processing tools added organized in a toolbar, isn't enough?

Adding tools to the toolbar isn't quite the same, especially as it clutter the UI if you want several tools. Having a simple _Favorites_ level in the Processing Toolbox panel would be cleaner and easier to manage if it works like the _Favorites_ in the Browser panel.

![fav_processing](https://user-images.githubusercontent.com/32580398/148660525-8643cafa-4cbb-41a6-889f-fff8910d4cf3.png)

**Comment by init931** [comment]
Is there an option to increase the number of items in the "Recently used" list from 5 to greather value?
