### ISSUE TITLE
QGIS 3 dialog size to small when when adding features to shape

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29223]
Author Name: **Benjamin  Gnep ** (Benjamin  Gnep )
Original Redmine Issue: [21406](https://issues.qgis.org/issues/21406)
Affected QGIS version: 3.4.4
Redmine category:mac_os_specific

---
When I set a shape file to editing mode and click into the map to add a new features the popup dialog with the attribute tablet opens very small.  I can manually adjust the size per mouse click to see the full content of the table and type in my edits. However, when I close the dialog and want to add the next feature the dialog opens with the tiny size again and I have to adjust the window size again to be able to add edits. That soon gets quite annoying when many features need to be added. 

---

- [XYq63.png](https://issues.qgis.org/attachments/download/14472/XYq63.png) (Benjamin  Gnep )

---

Related issue(s): #28200 (relates)
Redmine related issue(s): [20380](https://issues.qgis.org/issues/20380)

---

**Comment by emonshaugen** [comment]
We are having the same problem here in my organization.  We all work on **MacBook Pros** and we recently upgraded to **QGIS 3.80**.  We create a lot of features that need feature-specific attribution, and while the **tiny Attribute Form pop-up** can be resized, it's painful to have to do this for hundreds of features a day.  Doesn't look like a solution has been developed, but has anybody found a work-around?  Any info greatly appreciated, thanks!

**Comment by gioman** [comment]
> but has anybody found a work-around?

@emonshaugen rather than a workaround you may want to consider to support the work/effort for a real fix.

**Comment by emonshaugen** [comment]
@gioman If I could, I would, I'm sorry I can't help.  However, I did find an acceptable work-around for our team.  When you create a new feature, and the Attribute Form pop-up appears, you can hit the green (+) symbol to maximize the dialogue box.  From then on (until you shut your project down) the dialogue box will pop-up full screen.  This is at least helpful for our team, sorry I'm unable to find a real solution.

**Comment by ugosantana** [comment]
I can confirm this bug is still here after 3.8.3. The attribute form window is resizable but doesn't remember the last size. This doesn't happened in old versions, like 2.18. I don't know exactly in which 3.X version it started.

I can confirm also that when maximized the window keeps showing up the same way even when closed.

**Comment by Pedro-Murteira** [comment]
I can no longer replicate this issue on macOS, the add Feature Attributes dialog rememberes the exact size of the last time it was used. (macOS Monterey 12.0.1, QGIS 3.22.2.)

**Comment by Joaquin-Urruti** [comment]
I have the same problem, small window when identifying.

**Comment by jamierob** [comment]
For people on a mac finding this and having trouble with this dialogue box size, this is the answer: https://stackoverflow.com/questions/54781698/qgis-3-how-to-change-size-of-attribute-window
