### ISSUE TITLE
For polygon editing, expose the option "avoid intersection" also in the simple snapping configuration

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29234]
Author Name: **Oliver Jeker** (Oliver Jeker)
Original Redmine Issue: [21417](https://issues.qgis.org/issues/21417)

Redmine category:digitising

---
When digitizing adjacent polygons, the "avoid intersection" option is a tremendous help.

Therefore, it would be great to have it also in the "non advanced" snapping configuration.
Could simply be added at the end after "Snapping on intersection".

---

- [avoid_intersection_advanced.jpg](https://issues.qgis.org/attachments/download/14476/avoid_intersection_advanced.jpg) (Oliver Jeker)
- [avoid_intersection_simple.jpg](https://issues.qgis.org/attachments/download/14477/avoid_intersection_simple.jpg) (Oliver Jeker)

**Comment by DelazJ** [comment]
The overlapping options are now part of both snapping "toolbars". Can be closed IMHO.
