### ISSUE TITLE
Option to clear cache for WMS/WMTS service capabilities

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29238]
Author Name: **Nikolay Lebedev** (Nikolay Lebedev)
Original Redmine Issue: [21421](https://issues.qgis.org/issues/21421)

Redmine category:web_services_clients/wms

---
When you add WMS/WMTS service to QGIS for the first time it's capabilities are fetched from the service and cached to QGIS folder. So if something changes on server side you have to clear cache manually. It'd be great to have an option to reread and re-cache capabilities response.

**Comment by alexbruy** [comment]
Duplicates #25545
