### ISSUE TITLE
Enabling acceleration crashes QGIS

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29245]
Author Name: **Roberto Uhlig** (@uhliro26)
Original Redmine Issue: [21428](https://issues.qgis.org/issues/21428)
Affected QGIS version: 3.7(master)
Redmine category:opencl
Assignee: Alessandro Pasotti

---
## User Feedback

Just enable Acceleration by hitting the check box in the Options | Acceleration Crashes QGIS ;-(.
It's done in an new empty project, fresh startet with a new createt profile.

## Report Details

*Crash ID*: dbe41a9b097feaf8e87a78ad6d3a1eadcf3b9b10

*Stack Trace*
```
cl::detail::ReferenceHandler<_cl_device_id * __ptr64>::retain cl2.hpp:1477
cl::detail::Wrapper<_cl_device_id * __ptr64>::retain cl2.hpp:1843
cl::detail::Wrapper<_cl_device_id * __ptr64>::Wrapper<_cl_device_id * __ptr64> cl2.hpp:1770
cl::Device::Device cl2.hpp:2003
cl::detail::getInfoHelper<cl::detail::GetInfoFunctor0<int (__cdecl*)(_cl_context * __ptr64,unsigned int,unsigned __int64,void * __ptr64,unsigned __int64 * __ptr64),_cl_context * __ptr64>,cl::Device> cl2.hpp:1014
cl::detail::getInfo<int (__cdecl*)(_cl_context * __ptr64,unsigned int,unsigned __int64,void * __ptr64,unsigned __int64 * __ptr64),_cl_context * __ptr64,std::vector<cl::Device,std::allocator<cl::Device> > > cl2.hpp:1445
cl::Context::getInfo<std::vector<cl::Device,std::allocator<cl::Device> > > cl2.hpp:2868
cl::Context::getInfo<4225> cl2.hpp:2880
cl::Device::makeDefault cl2.hpp:2955
std::_Invoker_functor::_Call<void (__cdecl&)(void)> type_traits:1377
std::invoke<void (__cdecl&)(void)> type_traits:1445
std::_Invoke_stored_explicit<void (__cdecl&)(void),std::exception_ptr & __ptr64,0> mutex:471
std::_Callback_once<std::tuple<void (__cdecl&)(void),std::exception_ptr & __ptr64>,std::integer_sequence<unsigned __int64,0>,1> mutex:497
RtlRunOnceExecuteOnce :
InitOnceExecuteOnce :
_crtInitOnceExecuteOnce :
std::call_once<void (__cdecl&)(void)> mutex:519
cl::Device::getDefault cl2.hpp:2013
QgsOpenClUtils::activeDevice qgsopenclutils.cpp:174
QgsOpenClUtils::activate qgsopenclutils.cpp:212
<lambda_9ec297d20451569f5bb8b1f6372c225b>::operator() qgsopenclutils.cpp:86
std::_Invoker_functor::_Call<<lambda_9ec297d20451569f5bb8b1f6372c225b> > type_traits:1377
std::invoke<<lambda_9ec297d20451569f5bb8b1f6372c225b> > type_traits:1445
std::_Invoke_stored_explicit<<lambda_9ec297d20451569f5bb8b1f6372c225b> && __ptr64,std::exception_ptr & __ptr64,0> mutex:471
std::_Callback_once<std::tuple<<lambda_9ec297d20451569f5bb8b1f6372c225b> && __ptr64,std::exception_ptr & __ptr64>,std::integer_sequence<unsigned __int64,0>,1> mutex:497
RtlRunOnceExecuteOnce :
InitOnceExecuteOnce :
_crtInitOnceExecuteOnce :
std::call_once<<lambda_9ec297d20451569f5bb8b1f6372c225b> > mutex:519
QgsOpenClUtils::init qgsopenclutils.cpp:96
QgsOpenClUtils::available qgsopenclutils.cpp:368
<lambda_922094a53c4278625000fd604db93b4a>::operator() qgsoptions.cpp:1104
QtPrivate::FunctorCall<QtPrivate::IndexesList<0>,QtPrivate::List<bool>,void,<lambda_922094a53c4278625000fd604db93b4a> >::call qobjectdefs_impl.h:128
QtPrivate::Functor<<lambda_922094a53c4278625000fd604db93b4a>,1>::call<QtPrivate::List<bool>,void> qobjectdefs_impl.h:239
QtPrivate::QFunctorSlotObject<<lambda_922094a53c4278625000fd604db93b4a>,1,QtPrivate::List<bool>,void>::impl qobjectdefs_impl.h:427
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::setChecked :
QCheckBox::nextCheckState :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:366
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:366
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
TranslateMessageEx :
TranslateMessage :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
QgisApp::showOptionsDialog qgisapp.cpp:10726
QgisApp::options qgisapp.cpp:10591
QtPrivate::FunctorCall<QtPrivate::IndexesList<>,QtPrivate::List<>,void,void (__cdecl QgisApp::*)(void) __ptr64>::call qobjectdefs_impl.h:134
QtPrivate::FunctionPointer<void (__cdecl QgisApp::*)(void) __ptr64>::call<QtPrivate::List<>,void> qobjectdefs_impl.h:168
QtPrivate::QSlotObject<void (__cdecl QgisApp::*)(void) __ptr64,QtPrivate::List<>,void>::impl qobjectdefs_impl.h:397
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:366
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:366
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
TranslateMessageEx :
TranslateMessage :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1524
WinMain mainwin.cpp:170
__scrt_common_main_seh exe_common.inl:253
BaseThreadInitThunk :
RtlUserThreadStart :

```

*QGIS Info*
QGIS Version: 3.7.0-Master
QGIS code revision: 36ca201671
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.0
Running against GDAL: 2.4.0

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

---

- [DxDiag.txt](https://issues.qgis.org/attachments/download/14484/DxDiag.txt) (Roberto Uhlig)
- [qgis3.5.0-25_4d5edb2380_dbgview.LOG](https://issues.qgis.org/attachments/download/14491/qgis3.5.0-25_4d5edb2380_dbgview.LOG) (Roberto Uhlig)
- [qgis3.7.0-04_34a0650177_dbgview.LOG](https://issues.qgis.org/attachments/download/14492/qgis3.7.0-04_34a0650177_dbgview.LOG) (Roberto Uhlig)
- [reload20190305_qgis3.5.0-25_4d5edb2380_dbgview.LOG](https://issues.qgis.org/attachments/download/14521/reload20190305_qgis3.5.0-25_4d5edb2380_dbgview.LOG) (Roberto Uhlig)

**Comment by uhliro26** [comment]
#30931

**Comment by roya0045** [comment]
Are opencl crash issues/report still common? The previous report was closed due to opencl issue.

**Comment by uhliro26** [comment]
Sorry for being late, but I awaited the new release.
Sorry, but the crash is still here for my very old card with only OpenCL 1.0 on Win7.

So I'd suggest to clear state in the GUI/Options/Acceleration, that Card's with OpenCL < 1.2 are not supported and deprecated.

**Comment by uhliro26** [comment]
## User Feedback

Same bahavior im QGIS 3.19.0-Master

## Report Details

**Crash ID**: [44472257505f4bf3bbabf09757dd31719c28578c](https://github.com/qgis/QGIS/search?q=44472257505f4bf3bbabf09757dd31719c28578c&type=Issues)


**Stack Trace**
<pre>
cl::detail::ReferenceHandler<_cl_device_id * __ptr64>::retain cl2.hpp:1477
cl::detail::Wrapper<_cl_device_id * __ptr64>::retain cl2.hpp:1843
cl::detail::Wrapper<_cl_device_id * __ptr64>::Wrapper<_cl_device_id * __ptr64> cl2.hpp:1770
cl::Device::Device cl2.hpp:2003
cl::detail::getInfoHelper<cl::detail::GetInfoFunctor0<int (__cdecl*)(_cl_context * __ptr64,unsigned int,unsigned __int64,void * __ptr64,unsigned __int64 * __ptr64),_cl_context * __ptr64>,cl::Device> cl2.hpp:1014
cl::detail::getInfo<int (__cdecl*)(_cl_context * __ptr64,unsigned int,unsigned __int64,void * __ptr64,unsigned __int64 * __ptr64),_cl_context * __ptr64,std::vector<cl::Device,std::allocator<cl::Device> > > cl2.hpp:1445
cl::Context::getInfo<std::vector<cl::Device,std::allocator<cl::Device> > > cl2.hpp:2868
cl::Context::getInfo<4225> cl2.hpp:2880
cl::Device::makeDefault cl2.hpp:2955
std::_Invoker_functor::_Call<void (__cdecl&)(void)> type_traits:1377
std::invoke<void (__cdecl&)(void)> type_traits:1445
std::_Invoke_stored_explicit<void (__cdecl&)(void),std::exception_ptr & __ptr64,0> mutex:471
std::_Callback_once<std::tuple<void (__cdecl&)(void),std::exception_ptr & __ptr64>,std::integer_sequence<unsigned __int64,0>,1> mutex:497
RtlRunOnceExecuteOnce :
InitOnceExecuteOnce :
__crtInitOnceExecuteOnce winapisupp.cpp:225
std::call_once<void (__cdecl&)(void)> mutex:519
cl::Device::getDefault cl2.hpp:2013
QgsOpenClUtils::activeDevice qgsopenclutils.cpp:276
QgsOpenClUtils::activate qgsopenclutils.cpp:314
<lambda_d196ce1642e2fe9be205786332a87f11>::operator() qgsopenclutils.cpp:188
std::_Invoker_functor::_Call<<lambda_d196ce1642e2fe9be205786332a87f11> > type_traits:1377
std::invoke<<lambda_d196ce1642e2fe9be205786332a87f11> > type_traits:1445
std::_Invoke_stored_explicit<<lambda_d196ce1642e2fe9be205786332a87f11> && __ptr64,std::exception_ptr & __ptr64,0> mutex:471
std::_Callback_once<std::tuple<<lambda_d196ce1642e2fe9be205786332a87f11> && __ptr64,std::exception_ptr & __ptr64>,std::integer_sequence<unsigned __int64,0>,1> mutex:497
RtlRunOnceExecuteOnce :
InitOnceExecuteOnce :
__crtInitOnceExecuteOnce winapisupp.cpp:225
std::call_once<<lambda_d196ce1642e2fe9be205786332a87f11> > mutex:519
QgsOpenClUtils::init qgsopenclutils.cpp:198
QgsOpenClUtils::available qgsopenclutils.cpp:470
<lambda_d3a9b9e5331d65f628dcb60613e847d4>::operator() qgsoptions.cpp:1218
QtPrivate::FunctorCall<QtPrivate::IndexesList<0>,QtPrivate::List<bool>,void,<lambda_d3a9b9e5331d65f628dcb60613e847d4> >::call qobjectdefs_impl.h:128
QtPrivate::Functor<<lambda_d3a9b9e5331d65f628dcb60613e847d4>,1>::call<QtPrivate::List<bool>,void> qobjectdefs_impl.h:239
QtPrivate::QFunctorSlotObject<<lambda_d3a9b9e5331d65f628dcb60613e847d4>,1,QtPrivate::List<bool>,void>::impl qobjectdefs_impl.h:427
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::setChecked :
QCheckBox::nextCheckState :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:478
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:478
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
TranslateMessageEx :
TranslateMessage :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
QgisApp::showOptionsDialog qgisapp.cpp:12514
QgisApp::options qgisapp.cpp:12340
QtPrivate::FunctorCall<QtPrivate::IndexesList<>,QtPrivate::List<>,void,void (__cdecl QgisApp::*)(void) __ptr64>::call qobjectdefs_impl.h:134
QtPrivate::FunctionPointer<void (__cdecl QgisApp::*)(void) __ptr64>::call<QtPrivate::List<>,void> qobjectdefs_impl.h:168
QtPrivate::QSlotObject<void (__cdecl QgisApp::*)(void) __ptr64,QtPrivate::List<>,void>::impl qobjectdefs_impl.h:397
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:478
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:478
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
TranslateMessageEx :
TranslateMessage :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1637
WinMain mainwin.cpp:197
__scrt_common_main_seh exe_common.inl:253
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>


**QGIS Info**
QGIS Version: 3.19.0-Master
QGIS code revision: a825b5af35
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.3.0dev



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by roya0045** [comment]
TBH the best option may be to disable the acceleration option for older unsupported framework. As I'm not sure keeping everything retro-compatible is worth it.

**Comment by uhliro26** [comment]
..
If you are on the same point of view, then close my ticket.
...

**Comment by uhliro26** [comment]
For reference:
[3.19.0-Master_CrashDebug.log](https://github.com/qgis/QGIS/files/6036577/3.19.0-Master_CrashDebug.log)

**Comment by uhliro26** [comment]
and the 3.5 behavior:
![grafik](https://user-images.githubusercontent.com/48444235/109014040-0ed59000-76b4-11eb-9b6d-487fd13633d3.png)
![grafik](https://user-images.githubusercontent.com/48444235/109014127-24e35080-76b4-11eb-9e8b-96d6299ad4b5.png)

**Comment by uhliro26** [comment]
Tools screens are from today:
![grafik](https://user-images.githubusercontent.com/48444235/109014663-a33ff280-76b4-11eb-9013-98e7a2f64864.png)
![grafik](https://user-images.githubusercontent.com/48444235/109014864-d4202780-76b4-11eb-8b10-5f510738ff23.png)

**Comment by roya0045** [comment]
I assume your build has https://github.com/qgis/QGIS/pull/41374 ?

**Comment by uhliro26** [comment]
Updated today via osgeo4w.

QGIS Info
QGIS Version: 3.19.0-Master
QGIS code revision: a825b5a
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.3.0dev

I think #41374 is for MAC and there sems to be at least OpenCL >= 1.2

**Comment by roya0045** [comment]
Possible, I find it strange that there is no mention of changing supported version, but I'm not familiar with opencl and its integration. Maybe someone else has a clue.

**Comment by Pedro-Murteira** [comment]
I was not able to reproduce this issue on the most recent version of QGIS (3.22.3).
