### ISSUE TITLE
QGIS Server Labels character problem

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29244]
Author Name: **Bela Kutfej** (@kutfejbela)
Original Redmine Issue: [21427](https://issues.qgis.org/issues/21427)
Affected QGIS version: 3.4.5
Redmine category:qgis_server

---
I updated QGIS Server from "http://qgis.org/debian-ltr stretch" and after that, the labels in WMS:GetMap result does not show the "ő" (hungarian) character.

---

- [qgis.server-wms.character.problem.png](https://issues.qgis.org/attachments/download/14481/qgis.server-wms.character.problem.png) (Bela Kutfej)

**Comment by kutfejbela** [comment]
2 weeks ago the QGIS server shows this message:
"QFontDatabase: Cannot find font directory /usr/lib/x86_64-linux-gnu/fonts.
Note that Qt no longer ships fonts. Deploy some (from http://dejavu-fonts.org for example) or switch to fontconfig."
After I run the "ln -s /usr/share/fonts/truetype/*/* /usr/lib/x86_64-linux-gnu/fonts" command the characters are appears correctly.

**Comment by RobiFag** [comment]
The same problem occurs with other labels style options like buffer and placement. If I set a buffer or change the label placement using an offset value, Qgis desktop shows labels correctly, but Qgis server does not show the style options applied.
We are using Qgis server 3.4.14-2 with Lizmap as web client.

**Comment by Pedro-Murteira** [comment]
@kutfejbela Hello, is this still valid on more recent releases?
