### ISSUE TITLE
Changing page size in layout editor display

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29252]
Author Name: **jb Peter** (jb Peter)
Original Redmine Issue: [21435](https://issues.qgis.org/issues/21435)
Affected QGIS version: 3.6.0
Redmine category:map_composer/printing

---
When changing the page size of the layout there seems to be a display issue if the new page size is larger than the layout view. 

To reproduce:
- create a new layout
- right click and select page properties...
- change A4 to A0

> Lead to the issue marked in red on the attached screenshot 

I had this issue on:

QGIS 3.6 - Windows 7
QGIS 3.4 - Mac OS 10.4

---

- [Sans titre-2.jpg](https://issues.qgis.org/attachments/download/14489/Sans%20titre-2.jpg) (jb Peter)

**Comment by Pedro-Murteira** [comment]
This issue is still present on QGIS 3.16.14 and 3.22.1.

**Comment by YoannQDQ** [comment]
Cannot reproduce in 3.38 (Ubuntu & Windows). Seems like it was fixed.
