### ISSUE TITLE
Apply a pre-defined style to mesh layer through the API

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29255]
Author Name: **Paolo Cavallini** (@pcav)
Original Redmine Issue: [21438](https://issues.qgis.org/issues/21438)

Redmine category:data_provider/mdal

---
Currently it does not seem possible to apply a style to a mesh layer through the API. Thus, when loading e.g. a GRIB file through a plugin layers are loaded without a style.

**Comment by saberraz** [comment]
See https://github.com/qgis/QGIS/pull/34996
