### ISSUE TITLE
Wrong result with unaryUnion in python plugin

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29254]
Author Name: **Etienne MORO** (Etienne MORO)
Original Redmine Issue: [21437](https://issues.qgis.org/issues/21437)
Affected QGIS version: 3.4.4
Redmine category:python_bindings_/_sipify

---
Writing a python plugin for QGIS, I use the function unaryUnion to obtain correct lines to be used in polygonize function. The function works correctly with some layers (layer PolygonToLineLayer0-limited1.shp), but it doesn't work with another layer (PolygonToLineLayer0-limited3.shp). And I don't find what could be the problem, just think that unaryUnion doesn't work in a specific case.
You'll find attached my 2 layers and an extract of my python code.

---

- [Pb-unaryUnion.zip](https://issues.qgis.org/attachments/download/14490/Pb-unaryUnion.zip) (Etienne MORO)

**Comment by alexbruy** [comment]
The attached code is not a self-contained snipped and does not work at all. 

Performing `unaryUnion` on the geometries from each of the provided files returns correct results in both cases.
