### ISSUE TITLE
QGIS 3.6 can't open .qgz project file created on 3.4.4

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29265]
Author Name: **Tim Makins** (Tim Makins)
Original Redmine Issue: [21448](https://issues.qgis.org/issues/21448)
Affected QGIS version: 3.6.0
Redmine category:project_loading/saving

---
I upgraded from 3.4.4.1 to 3.6.0.1.
When I clicked on an existing .qgz file, I was informed that it was from an older version, and that it might make it unusable for older versions, but there appeared to be no way to actually open it.

---

- [ITUZ 50m.qgz](https://issues.qgis.org/attachments/download/14502/ITUZ%2050m.qgz) (Tim Makins)

**Comment by alexbruy** [comment]
Works in master. Please reopen if necessary.
