### ISSUE TITLE
QGIS 3.6 plugin slow?

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29263]
Author Name: **Willem Buitendyk** (@swaxolez)
Original Redmine Issue: [21446](https://issues.qgis.org/issues/21446)
Affected QGIS version: 3.6.0
Redmine category:unknown

---
I have an in-house plugin that when a button is clicked launches a python3 subprocess.call.  After the initial 3.6 install clicking via the application icon would not allow the subprocess.call to open the helper application.  I then unchecked and checked qgis 3.6 in full disk access in security and privacy.  Now the subprocess.call works but it is painfully slow to launch.  The interesting part ...

If I launch QGIS 3.6 by launching from the terminal (inside the QGIS application package) then everything works fine and is normally snappy.  The subprocess.call launches the helper application immediately.   So, much like the maligned slow browser folder plaguing 3.4 we seem to have some MacOS security sandbox BS still happening. 

Has this been pegged to a bug in Qt?

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.

**Comment by gonsalvd** [comment]
Same problem here. Any fixes?
