### ISSUE TITLE
GDAL Complete 2.4 frameworks not available on kyngchaos.com

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29267]
Author Name: **Matt Pewsey** (Matt Pewsey)
Original Redmine Issue: [21450](https://issues.qgis.org/issues/21450)
Affected QGIS version: 3.4.5
Redmine category:mac_os_specific

---
The latest QGIS v3.4.5 LTR and 3.6.0 require the GDAL Complete 2.4 framework package to be installed per the Mac OS X readme. However, this package is not available at kyngchaos.com. A failure to import processing message appears when opening QGIS without the 2.4 frameworks installed. Could this package be added to the website?

**Comment by alexbruy** [comment]
Can we close this?

**Comment by kyngchaos** [comment]
Ah, I completely missed this bug report.  but yes, it's a non-issue because the GDAL Complete package is included on the QGS disk image (also mentioned in the readme).

**Comment by teddyward** [comment]
@kyngchaos thanks for all the great work you do. I'm curious if you know of a place to download GDAL Complete 2.4. I am not sure which readme or which image you were referring to in https://github.com/qgis/QGIS/issues/29267#issuecomment-615240433, but I could not find this package and would really benefit from it

**Comment by kyngchaos** [comment]
The disk image of the QGIS installer has Python and GDAL installers also.
