### ISSUE TITLE
Vectorlayer from spatialite missing features and inconsistent feature count

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29264]
Author Name: **Henrik Spångmyr** (@HenrikSpa)
Original Redmine Issue: [21447](https://issues.qgis.org/issues/21447)
Affected QGIS version: 3.6.0
Redmine category:data_provider/spatialite

---
QGIS show different feature count in layer list and in attribute table and some features are missing in attribute table.

I have database A with 1622 features in table obs_points.
I have a view of table obs_points, also with 1622 features.

I created a new database B and transfered all rows from A.obs_points to B.obs_points. Database B also has a view of B.obs_points.

I've attached an image which shows the issue.

There should be 1622 rows in all tables and views.

Layer obs_points_A show 1480 features in the layerlist, but 1580 in the attribute table and 1622 in spatialite_gui. << WRONG
Layer obs_points_A_view show 1565 features in the layerlist, but 1622 in the attribute table and 1622 in spatialite_gui. << WRONG
Layer obs_points_B show 1622 features in the layerlist, but 1622 in the attribute table and 1622 in spatialite_gui. << Correct
Layer obs_points_B_view show 1622 features in the layerlist, but 1622 in the attribute table and 1622 in spatialite_gui. << Correct

When I look in the attribute table for obs_points_A, the rows with rowids 1-42 (the rowid in the sqlite table) seems to be the missing rows.

Also, loading a spatialite table to QgsVectorLayer using qgis, i get vlayer.featureCount()=0 for some reason while I get lots of features from vlayer.getFeatures(). Not sure if it's related or not.

So, my transfer of rows fixed the issue, but I'm not sure why the first database isn't working well with QGIS 3.6.

---

- [featurecount_bug.png](https://issues.qgis.org/attachments/download/14497/featurecount_bug.png) (Henrik Spångmyr)
- [qgis_redmine_21447_2.sqlite](https://issues.qgis.org/attachments/download/14501/qgis_redmine_21447_2.sqlite) (Henrik Spångmyr)

**Comment by gioman** [comment]
@HenrikSpa now I see what you describe, anyway this seems to be related to the fact that your table does not have a numeric (integer) column to be used as unique id. There is one, but is text. Once you resave your layer as spatialite and allows QGIS to add a proper id/integer column then it all checks out as expected.

**Comment by HenrikSpa** [comment]
@gioman We've had this table layout from way back in QGIS version 2.x and it worked well until QGIS version 3.6. Then something changed that now requires QGIS to have a numeric id column.

The database layout we use requires the obsid column to be primary key and of type text. It might be possible to use an integer pk column and let obsid column be "unique" perhaps (note to self).

We've worked around this by using the view view_obs_points in all matters related to the original obs_points, which have worked perfectly for us.

--------------------------------------------------

Anyway, IF spatialite layers with geometries now REQUIRES an integer ID column by design, then I guess that this is intended and no longer a bug. If that is the case, this issue could be closed I guess.

**Comment by gioman** [comment]
> Anyway, IF spatialite layers with geometries now REQUIRES an integer ID column by design, then I guess that this is intended and no longer a bug. If that is the case, this issue could be closed I guess.

@HenrikSpa I'm not sure about this... maybe a developer can leave its feedback @elpaso ?

**Comment by elpaso** [comment]
No: if there is no integer PK `ROWID` is used instead.
The feature count is taken from the spatialite libraries, I'm looking at the issue now.

**Comment by elpaso** [comment]
In the linked PR I've fixed the wrong feature count: https://github.com/qgis/QGIS/pull/37277

But I'm not sure that this ticket is all about feature count, it may not be fixed entirely.
