### ISSUE TITLE
Quantile (Equal Count) on given dataset generates a lot of zero-classes

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29268]
Author Name: **Richard Duivenvoorde** (@rduivenvoorde)
Original Redmine Issue: [21451](https://issues.qgis.org/issues/21451)
Affected QGIS version: 3.7(master)
Redmine category:symbology

---
Using attached randomized dataset (with a lot of zero's AND negative values...) Graduated styling with the Quantile (Equal Count) on the 'value' column creates a lot of '0'-classes:

![QuantileEqualCount2.png](https://issues.qgis.org/attachments/download/14505/QuantileEqualCount2.png)

Adding more classes also adds more 'zero'- classes.

Maybe it has something to do with the amount of zero in the values? 
Or with the negative values in it?
Or is there some logarithmic logic in it (where there should be no negative values)?

I've also tested with QGIS 2.18 and that gave the same results.

 

---

- [random.gpkg](https://issues.qgis.org/attachments/download/14504/random.gpkg) (Richard Duivenvoorde)
- [QuantileEqualCount2.png](https://issues.qgis.org/attachments/download/14505/QuantileEqualCount2.png) (Richard Duivenvoorde)
- [random_abs_freq.ods](https://issues.qgis.org/attachments/download/14510/random_abs_freq.ods) (Pedro Venâncio)

**Comment by nyalldawson** [comment]
No issue here - closing
