### ISSUE TITLE
crop data to map extent when exporting to vector PDF

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29261]
Author Name: **Carolyn Krause** (Carolyn Krause)
Original Redmine Issue: [21444](https://issues.qgis.org/issues/21444)

Redmine category:map_composer/printing

---
When exporting to a vector pdf, the map layers are apparently not cropped to the map extent. So with a very detailed, world-wide vector layer, you can hit Adobe's 32,768 vertex limit. As a result, some features are (apparently randomly) excluded from the exported pdf.

That was the case in this question (https://gis.stackexchange.com/questions/314068/qgis-print-composer-incomplete-pdf-export) posted on GIS stackexchange, with a high-detail (10m) physical vector layer from Natural Earth. A pdf export of Northern Europe excluded certain islands, including Great Britain.

GIS SE user Juan (https://gis.stackexchange.com/users/137934/juan) commented: "When importing the "incomplete" map into Inkscape and using the path editing tool one can notice that there are many hidden vertices. Apparently what the print composer does is to add a mask to the part of the shp files that are not in the canvas. I suppose, then, that it prioritise certain polygons until it reaches the maximum allowable vertex count. Cropping the shp file seems to delete the unnecessary vertices, instead."

*Would it be possible to crop the vector data to the exported map extent, instead of just masking it?*

**Comment by haubourg** [comment]
If cropping is already done, does this mean that pdf export should somehow do a on the fly simplification to reduce the number of vertices?

**Comment by nyalldawson** [comment]
It is, as of 3.10
