### ISSUE TITLE
DB manager does not confirm anymore that the creation of a PostGIS table went ok

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29276]
Author Name: **Giovanni Manghi** (@gioman)
Original Redmine Issue: [21459](https://issues.qgis.org/issues/21459)
Affected QGIS version: 3.4.5
Redmine category:db_manager

---
Now in 3.4.5 when finalizing the creation of a PostGIS table nothing happens (in 2.18 a message like "all went ok" was returned) leaving the user wonder if the table was created or else. Not a bad bug (but a regression) and overall a bad UX.

**Comment by anitagraser** [comment]
@gioman Tested in 3.4.8: DB Manager shows "Import was successful" on completion. 

I think this can be closed.
