### ISSUE TITLE
The "avoid intersection" operation fails with NO warnings if  existing polygon has an auto intersection

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29274]
Author Name: **Giovanni Manghi** (@gioman)
Original Redmine Issue: [21457](https://issues.qgis.org/issues/21457)
Affected QGIS version: 3.4.5
Redmine category:digitising

---
When the "avoid intersection" is enabled but the existing feature has an auto-intersection, then the new polygon will NOT be clipped along the borders of the existing one.
Moreover QGIS does not show any warning, not in the message bar or even in the LOG.

This can easily led to very wrong results, unless using a semi-transparent symbolgy that allows to inspect/see how the new polygon boundaries really are.

Seen in 3.* and as well in the last release of 2.18.

tagging as "high" as it can lead to wrong results with no warning at all.

**Comment by gioman** [comment]
Still true on the latest master.

**Comment by lbartoletti** [comment]
It has been fixed here https://github.com/qgis/QGIS/pull/41424/files#diff-14d7729cdef7a27c74c96dde9009b3aee54837bc7607b2817ff952732aac21afR199
