### ISSUE TITLE
Legend issues - Differences between legend in layer's properties and legend in the layer panel/print composer

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29287]
Author Name: **Caroline Font** (Caroline Font)
Original Redmine Issue: [21470](https://issues.qgis.org/issues/21470)
Affected QGIS version: 3.6.0
Redmine category:map_legend

---
English version :
I've never seen this problem in previous version of the software.
The legend shown in the layer panel of the map canvas doesn't correspond to the one set in the layer properties (cf. capture 2019-03-04_14h14_15.jpg linked).
In the print composer, the legend correspond to the wrong version of the legend unfortunately (cf. capture 2019-03-04_14h17_20.jpg linked).
After updating the legend, no changes, still the same wrong legend. Same wrong result remaking entirely the style settings or recreating a brand new legend in the print composer.

French version/version en français :
Je n'ai jamais rencontré ce problème pour les versions antérieures de QGIS.
La légende affichée dans le panneau de couches du canevas de la carte ne correspond pas à celle configurée dans les propriétés de la couche (cf. capture 2019-03-04_14h14_15.jpg jointe).
Dans le composeur d'impression, la légende correspond à la mauvaise version de la légende malheureusement (cf. capture 2019-03-04_14h17_20.jpg jointe).
Après une mise à jour de la légende, aucun changement, toujours la même mauvaise légende. Même mauvais résultat après avoir entièrement reconfigurer les paramètres du style ou après avoir insérer une toute nouvelle légende.

---

- [2019-03-04_14h14_15.jpg](https://issues.qgis.org/attachments/download/14514/2019-03-04_14h14_15.jpg) (Caroline Font)
- [2019-03-04_14h17_20.jpg](https://issues.qgis.org/attachments/download/14515/2019-03-04_14h17_20.jpg) (Caroline Font)

**Comment by nyalldawson** [comment]
There's not enough detail here to reproduce -- we'd need a test project. My gut feeling is that this one related to map theme and legend handling, which has since been fixed.
