### ISSUE TITLE
option --profiles-path when launching QGIS and locale by default involve Qvariant error when activating plugins

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29281]
Author Name: **Alain FERRATON** (@FERRATON)
Original Redmine Issue: [21464](https://issues.qgis.org/issues/21464)
Affected QGIS version: 3.4.5
Redmine category:gui

---
I use the --profiles-path option when launching QGIS.

If you do not check the 'override system locale' settings option,
loading any plugin implies the following error:

------------
Impossible de charger l'extension 'AcATaMa' provoque une erreur lors de l'appel à sa méthode classFactory() 

TypeError: 'QVariant' object is not subscriptable 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.4J/apps/qgis-ltr/./python\qgis\utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\0_test\profiles\default/python/plugins\AcATaMa\__init__.py", line 33, in classFactory
    return AcATaMa(iface)
  File "C:\0_test\profiles\default/python/plugins\AcATaMa\acatama.py", line 57, in __init__
    *locale = QSettings().value('locale/userLocale')[0:2]*
TypeError: 'QVariant' object is not subscriptable
----------------

if you check the option and restart QGIS the error no longer occurs.

This is probably a storage problem of the default locale in the QGIS3.ini file

**Comment by haubourg** [comment]
Problem still occurs in 3.10-1 **without** the `--profiles-path` option for some plugins. 
confirmed with following plugins

- mask
- red layer
- SpreadSheet Layers

**Comment by haubourg** [comment]
More info, 
with the correct locale information in a global-settings files, the problem occurs. If we copy this global settings into the user profile QGIS3.ini, problem is solved. There might be an issue with interpreting the default settings from the global settings for these settings.

cc @mhugo

**Comment by AlisterH** [comment]
Correct me if I'm wrong, but isn't this the way to fix for plugins producing this error?: https://github.com/Kanahiro/MagicWand/pull/11/commits/77eca3d33d0e72214d811650e42faf766c05ff11

**Comment by troopa81** [comment]
> Correct me if I'm wrong, but isn't this the way to fix for plugins producing this error?: Kanahiro/MagicWand@77eca3d

I think so
