### ISSUE TITLE
Unable to display some rasters in canvas

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29280]
Author Name: **Patrick Dunford** (@enzedrailmaps)
Original Redmine Issue: [21463](https://issues.qgis.org/issues/21463)
Affected QGIS version: 3.6.0
Redmine category:rasters

---
Since upgrading to Buster there is now a situation where some rasters will not display correctly in the Canvas.

I believe this issue has been previously reported, possibly in 2.18

This only affects customised JPEG raster layers created in Gimp. All known image viewers can view these correctly.

Affecting both 3.4.5 and 3.6 on Buster

---

- [Screenshot_2019-03-04_14-55-18.png](https://issues.qgis.org/attachments/download/14509/Screenshot_2019-03-04_14-55-18.png) (Patrick Dunford)

---

Related issue(s): #26923 (relates)
Redmine related issue(s): [19093](https://issues.qgis.org/issues/19093)

---

**Comment by FelisPimeja** [comment]
> Author Name: **Patrick Dunford** (@enzedrailmaps)
> 
> It appears this issue is caused by dropping support for Progressive JPEGs in the latest version. I've tested with rasters regenerated as non progressive and everything displays properly.
> 
> Progressive Jpeg format is part of the Jpeg standard for many years and this situation could affect a lot of other users.

+1 Jpeg Progressive issue for me either.
Windows 10 x64, all Qgis versions from last 2.18 to last 3.9

**Comment by alexbruy** [comment]
Still true in 3.10/master?

**Comment by alexbruy** [comment]
Closed for the lack of feedback. Please reopen if necessary and provide sample data.
