### ISSUE TITLE
Inconsistent behaviour of digitizing toolbox and line measure tool 

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29295]
Author Name: **Anja Sen** (Anja Sen)
Original Redmine Issue: [21478](https://issues.qgis.org/issues/21478)
Affected QGIS version: 3.4.0
Redmine category:map_tools

---
I am using the digitizing toolbox to copy and move linestring feature, where I notice that the distance shown in the digitizing tool panel and the one measured by the "Measure Line" tool are very different. The line string feature layer has crs EPSG:4326.

When the project CRS is set to EPSG 3857 (Pseudo-Mercator) and I move the feature by 5m with the cad tool, the measure line tool only measures a distance of 3.3m. 

When I set the project CRS to EPSG 25832 which is optimal for the location of the features, the cad tool and the "Measure Line" Tool both measure a distance of 3.3m between the original feature and the previously moved feature. As I have re-projected, there are small errors caused by the re-projection, but it can be ignored as the distortion is not large. 

Too make things complicated, when I tried to move linestring features at another geo location (north america), I experience reversed behavior. 

When I set the projet CRS to EPSG 3857 and move the feature with the CAD tool by 5m, the "Measure Line" Tool measures a distance of only 4m. And when I set the project CRS to EPSG 54004 which is optimal for the location of the features, the "Measure Line" tool and the cad tool both measures a distane of 5m of the previously moved feature and the original feature.

As I understand, the EPSG 3857 is a projected CRS which fits the world with compromised accuracy, but an offset of 20%- 35% still seems too much.

My conclusion is, when setting the project CRS to one which is optimized to the features's geolocation, the behavior of the cad tool and the "Measure Line" tool are consistent. But when setting the project to EPSG 3857 (Pseudo-Mercator), the tools show inconsistent behavior.

**Comment by alexbruy** [comment]
Can we close this?
