### ISSUE TITLE
GRASS plugin not operating

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29307]
Author Name: **David Allison** (David Allison)
Original Redmine Issue: [21490](https://issues.qgis.org/issues/21490)
Affected QGIS version: 3.4.4
Redmine category:grass

---
Every time I try to activate a GRASS procedure I receive the error message in the attached screen capture. This seems to be an error in the configuration of the OS (WIN10) environment variables. Please reply if you have a solution or need additional info.

---

- [Grass_Error.jpg](https://issues.qgis.org/attachments/download/14528/Grass_Error.jpg) (David Allison)

**Comment by gioman** [comment]
Closing for lack of feedback (and as it works here on master on Windows 10).
