### ISSUE TITLE
python error when using the QGIS "assign projection" tool in batch mode and output format is GPKG

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29315]
Author Name: **Giovanni Manghi** (@gioman)
Original Redmine Issue: [21498](https://issues.qgis.org/issues/21498)
Affected QGIS version: 3.4.5
Redmine category:processing/qgis

---
Input layers have already a "fid" field. Does not happen not using batch mode. Possibly affects other tools?

error is like

Algorithm Assign projection starting…
Input parameters:
{'CRS': <qgis._core.QgsCoordinateReferenceSystem object at 0x0000000010CABCA8>,
'INPUT': 'input1',
'OUTPUT': <QgsProcessingOutputLayerDefinition {'sink':C:/Users/qgis/test1.gpkg, 'createOptions': {}}>}

Could not create layer C:/Users/qgis/test1.gpkg: Creation of field fid failed (OGR error: Wrong field type for fid)

**Comment by alexbruy** [comment]
Works fine in master. Can you retest?

**Comment by gioman** [comment]
> Works fine in master. Can you retest?

@alexbruy confirmed working on master, still broken in the latest LTR.

**Comment by alexbruy** [comment]
Looks like this is not a Processing issue, but related to the GPKG handling. If I'm not mistaken there were some work on GPKG support somewhere in between 3.6 and 3.10

**Comment by gioman** [comment]
Works on master.
