### ISSUE TITLE
Distance matrix does not maintain data type and precision for Input Point Layer in Linear (N*k x 3)

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29318]
Author Name: **Andy Whyte** (Andy Whyte)
Original Redmine Issue: [21501](https://issues.qgis.org/issues/21501)
Affected QGIS version: 3.7(master)
Redmine category:processing/qgis
Assignee: Victor Olaya

---
I have noticed that the distance matrix does not maintain precision or data type in InputID field created from the ID of the Input Point Layer to the tool.

This is an issue because it means I cannot join my result to an existing layer. The Target Point layer does not seem to do this.

For example the attached shapefile has an ID column (double, REAL, 20, P=0). When run through the distance matrix it inserts a decimal place. Additionally even if I use an integer ID field the output table will still not join to itself so it must be changing the type somehow to stop it from joining.

I am using QGIS 3.6

---

- [Point layer.cpg](https://issues.qgis.org/attachments/download/14537/Point%20layer.cpg) (Andy Whyte)
- [Point layer.dbf](https://issues.qgis.org/attachments/download/14538/Point%20layer.dbf) (Andy Whyte)
- [Point layer.qpj](https://issues.qgis.org/attachments/download/14539/Point%20layer.qpj) (Andy Whyte)
- [Point layer.prj](https://issues.qgis.org/attachments/download/14540/Point%20layer.prj) (Andy Whyte)
- [Point layer.shp](https://issues.qgis.org/attachments/download/14541/Point%20layer.shp) (Andy Whyte)
- [Point layer.shx](https://issues.qgis.org/attachments/download/14542/Point%20layer.shx) (Andy Whyte)
- [Clipboard01.png](https://issues.qgis.org/attachments/download/14975/Clipboard01.png) (Victor Olaya)
- [Test.PNG](https://issues.qgis.org/attachments/download/14977/Test.PNG) (Andy Whyte)

**Comment by gioman** [comment]
Works as expected on the latest master.
