### ISSUE TITLE
Network disabled after time

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29313]
Author Name: **Francesco Pirotti** (Francesco Pirotti)
Original Redmine Issue: [21496](https://issues.qgis.org/issues/21496)
Affected QGIS version: 3.4.4
Redmine category:network

---
After about one hour of using QGIS Desktop, network gets disabled: e.g. cannot download new plugins and connecting to WCS/WMS/WFS returns message "Unable to download capabilities: Network Access Disabled". New istance of QGIS works fine.

**Comment by alexbruy** [comment]
Still valid?
