### ISSUE TITLE
Mesh layers: add animation

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29326]
Author Name: **Paolo Cavallini** (@pcav)
Original Redmine Issue: [21509](https://issues.qgis.org/issues/21509)

Redmine category:mesh_layers

---
It would be useful to add a button to play the sequence of time slices in the canvas. Currently animation is only possible exporting a movie.

**Comment by pcav** [comment]
Thanks @PeterPetrik for this. Just compiled from master, I cannot see the button. Where should I see it?

**Comment by saberraz** [comment]
@pcav this is not yet merged into master. If you'd like to try it, you can compile the branch.

**Comment by pcav** [comment]
Thanks, sorry for the noise.

**Comment by pcav** [comment]
Wow, thanks @PeterPetrik
