### ISSUE TITLE
Processing "Build virtual vector" now fails in certain cases

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29336]
Author Name: **Alister Hood** (@AlisterH)
Original Redmine Issue: [21519](https://issues.qgis.org/issues/21519)
Affected QGIS version: 3.6.0
Redmine category:processing/qgis
Assignee: Victor Olaya

---
1. In 3.x, if I load shape files as directories (i.e. drag and drop the containing directory into QGIS, rather than the shapefile itself), and then try to use those layers as inputs, I get an error message:
```
Traceback (most recent call last):
File "C:/PROGRA~1/QGIS3~1.6/apps/qgis/./python/plugins\processing\algs\qgis\Datasources2Vrt.py", line 102, in processAlgorithm
feedback=feedback)
File "C:/PROGRA~1/QGIS3~1.6/apps/qgis/./python/plugins\processing\algs\qgis\Datasources2Vrt.py", line 133, in mergeDataSources2Vrt
self.tr('Invalid datasource: {}'.format(inFile)))
_core.QgsProcessingException: Invalid datasource: //path_obfuscated/Area_2/BD34_0109|layername=BD34_0109

Execution failed after 0.10 seconds

```
It succeeds without error in 2.18.x.

2. If two of the input layers have the same name and I create a "unioned" VRT using 3.x the vrt contains one of them twice and omits the other one.  2.18.x correctly creates a vrt containing both.

3. There is another buglet that isn't a regression as 2.18.x did not support loading the output file after creating it: run the algorithm with 'create "unioned" VRT' unchecked and "open output file after running algorithm" checked, and only one layer in the output VRT will be _loaded_.  However, the VRT was actually created correctly (drag and drop the VRT into QGIS and you will get the dialog to select which layers to load).

**Comment by alexbruy** [comment]
I can not reproduce with master. When I drag-n-drop directory with shapefiles into QGIS nothing happens.

**Comment by AlisterH** [comment]
Drag-n-drop directory with shapefiles still works in 3.8.3.
Either:
1. you have found a new regression in master.
2. there is something else in the directory which is confusing gdal.
3. perhaps it doesn't work on all platforms?  I am using Windows explorer; what operating system are you on and what file manager are you using?
If it isn't number 2 you should probably file a new ticket.

Can you open [the attached project](https://github.com/qgis/QGIS/files/3629164/FME_27304A19_1568861457854_30092.zip) successfully?  You should be able to test with it, even if the drag
-n-drop itself doesn't work.
