### ISSUE TITLE
Resize layout window will cause system hang if map contains ArcGIS map server layer

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29335]
Author Name: **Larry Wu** (Larry Wu)
Original Redmine Issue: [21518](https://issues.qgis.org/issues/21518)
Affected QGIS version: 3.4.5
Redmine category:network

---
Steps to repeat the bug:
1. Open a new project
2. Add an ArcGIS Map Server layer to map
3. Add a new print layout
4. Add Item -> Add Map to the layout in the layout window
5. Resize the layout window by dragging the window border, QGIS will then hang

After a long time, system recovered, and an error message prompted in QGIS window, saying network timeout, looks like: 
WARNING    Network request http://localhost:6080/arcgis/rest/services/QGIS/Basemap_Cached/MapServer?f=json timed out
WARNING    Network request http://localhost:6080/arcgis/rest/services/QGIS/Basemap_Cached/MapServer/0?f=json timed out

By using Fiddler capture network traffic, it was found when QGIS accessing the reported URL address, it received HTTP/1.1 304 Not Modified, while the URL address can be correctly opened by browser.

**Comment by nyalldawson** [comment]
Can't reproduce on master, is this still an issue?

**Comment by nyalldawson** [comment]
Closed due to lack of feedback
