### ISSUE TITLE
[node tool] nodes on the locked item remains highlighted after toggle editing

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29348]
Author Name: **Saber Razmjooei** (@saberraz)
Original Redmine Issue: [21532](https://issues.qgis.org/issues/21532)
Affected QGIS version: 3.7(master)
Redmine category:digitising

---
After toggle editing (exit edit mode), the highlighted nodes of the locked item remains highlighted.

---

- [node_tool_artifact.gif](https://issues.qgis.org/attachments/download/14559/node_tool_artifact.gif) (Saber Razmjooei)

**Comment by uclaros** [comment]
@saberraz can you still reproduce this? I think it has been fixed.

**Comment by Pedro-Murteira** [comment]
@saberraz I can no longer reproduce this situation on QGIS 3.16.14 and 3.22.1.
