### ISSUE TITLE
Add possibility to choose between seperate line and polylines in QGIS "Split lines"

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29350]
Author Name: **Lene Fischer** (@LeneFischer)
Original Redmine Issue: [21534](https://issues.qgis.org/issues/21534)

Redmine category:processing/qgis

---
I have used the two functions which initially looks the same. I miss the possibility to choose between seperate line and polylines

**Comment by nyalldawson** [comment]
I don't understand the distinction, and the SAGA help has no clues at all what the different options mean.

Can you clarify?
