### ISSUE TITLE
[Advanced Digitizing] 

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29355]
Author Name: **João Gaspar** (@jonnyforestGIS)
Original Redmine Issue: [21539](https://issues.qgis.org/issues/21539)
Affected QGIS version: 3.4.5
Redmine category:digitising

---
Tested in a shapefile format. Strange behaviour. See animated gif.
Steps:
1. Create an empty polygon shapefile.
1. Draw a polygon at least with 5 vertices.
1. Click in the simplify feature button from advanced digitizing
1. Click above the polygon double click many times. The dialogues start to appear and don't go away.

---

- [simplifygeometry.gif](https://issues.qgis.org/attachments/download/14562/simplifygeometry.gif) (João Gaspar)

**Comment by gioman** [comment]
@jonnyforestGIS still true on the latest releases?

**Comment by jonnyforestGIS** [comment]
@gioman need to check it again and then I give you the feedback.

**Comment by jonnyforestGIS** [comment]
@gioman this can be close. In 3.10 is working fine.
