### ISSUE TITLE
DB Manager cannot import anymore from GeoJSON into a Spatialite table

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29360]
Author Name: **Yannis Psomadakis** (Yannis Psomadakis)
Original Redmine Issue: [21544](https://issues.qgis.org/issues/21544)
Affected QGIS version: 3.6.0
Redmine category:db_manager

---
When importing a GeoJSON table into a Spatialite table in 3.4.2-Madeira, the name of the imported table appears in the 'Output table' field and imports as expected.
From versions 3.5 onward, the imported table defaults into one of the existing tables and imports data from that table instead of the GeoJSON file regardless of manually changing the name to the one matching the GeoJSON file.
Steps to reproduce:
a) Create a geojson file from contents below:
{
"type": "FeatureCollection",
"name": "venue-levels",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "id": 1, "level_id": 0, "floor_name": "Ground Floor", "table_name": "", "elevation_a0f": 0, "description": "ground floor plan", "floor_short_code": "F0" }, "geometry": { "type": "MultiPolygon", "coordinates": [ [ [  [ -1.2, 52.2 ], [ 0, 52.4], [ 1.2, 52.2 ],[ -1.2, 52.2 ] ] ] ] } }
]
}

b) Create a Spatialite database with 2-3 other tables 
c) Use the DB Manager "Import Layer/File"
d) Click the ellipsis, locate file you created and open it.  The 'input' field should change from a table name into the path of the selected file.
e) In versions 3.5 and beyond, the 'Output table' Table field defaults o an existing table and does not change into the name as listed in the file which in this example is "venue-levels".
f) Confirm the Primary key, geometry, choose to replace (if exists) and click OK
The imported table now shows the contents of the table that was in the 'Output table' Table field beforehand.

---

Related issue(s): #29847 (relates)
Redmine related issue(s): [22033](https://issues.qgis.org/issues/22033)

---

**Comment by alexbruy** [comment]
Duplicates #29847
