### ISSUE TITLE
QGIS crashed when use file browser

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29363]
Author Name: **Emilio Abad** (Emilio Abad)
Original Redmine Issue: [21547](https://issues.qgis.org/issues/21547)
Affected QGIS version: 3.4.5
Redmine category:browser

---
## User Feedback

QGIS crashed when use file browser. No pluggins charged.

## Report Details

*Crash ID*: 0478ce1956a3f8a7c10e47977c1089a39309c46f

*Stack Trace*
```
RtlFreeHeap :
free :
DllUnregisterServer :
DllUnregisterServer :
CoGetTreatAsClass :
CoGetTreatAsClass :
CoGetTreatAsClass :
CoGetTreatAsClass :
CoGetTreatAsClass :
CoGetTreatAsClass :
CoGetTreatAsClass :
CoGetTreatAsClass :
CoGetTreatAsClass :
CoGetTreatAsClass :
CoCreateInstance :
CoCreateInstance :
CoCreateInstance :
SHCreateItemInKnownFolder :
Ordinal61 :
Ordinal61 :
Ordinal61 :
Ordinal61 :
Ordinal61 :
SHELL32_IconOverlayManagerInit :
SHELL32_IconOverlayManagerInit :
NeverProvidedByJunction :
StateRepoVerbsCache_GetContextMenuVerbs :
StateRepoVerbsCache_GetContextMenuVerbs :
Ordinal2007 :
SHCreateItemWithParent :
SHCreateItemWithParent :
SHCreateItemWithParent :
GetScaleFactorForMonitor :
A_SHAUpdate :
RtlReleaseSRWLockExclusive :
BaseThreadInitThunk :
RtlUserThreadStart :

```

*QGIS Info*
QGIS Version: 3.4.5-Madeira
QGIS code revision: 89ee6f6e23
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.0
Running against GDAL: 2.4.0

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
