### ISSUE TITLE
Revert to old-style select method for mouse actions

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29377]
Author Name: **Cory Albrecht** (@CoryAlbrecht)
Original Redmine Issue: [21561](https://issues.qgis.org/issues/21561)
Affected QGIS version: 3.7(master)
Redmine category:map_tools

---
In 2.18.x when one wanted to select features in a layer, you clicked the primary mouse button, held it, and moves the mouse cursor over the items you wanted to select - known as "click and drag". To help, a shape was drawn on screen for the user to know what they had already dragged the mouse over top of. To add to the selection you used shift plus click and drag, to remove, ctrl plus click and drag. This is a widely used method across platforms and has been in use for more than two decades. It is a de facto standard.

In 3.x, however, instead of using that common method, it has changed to click and release and move the mouse around. This is a common UI method to set focus to an item for subsequent actions but still be able to move the mouse around without selecting or affecting any other items.

A similar change has also happened in the vertex editor where in 2.18.x single clicking on a vertex used to mean select, and you had to drag (click and hold) to move it. Now, if you click and release, it unexpectedly drags the vertex around as you move the mouse.

QGIS having it's own, non-standard mouse actions for tasks that are common (select, copy, delete, etc…) across all types of data (text in a wordprocessor, frames in a movie editor, features in a map editor, etc…) is counter-intuitive and confusing, especially if those non-standard actions are already commonly used for other common user interface actions.

It's almost like the QGIS development team has decided that Ctrl+V will now mean "Cut", Ctrl+X will mean "Copy", and to copy have to use Alt+F1 for "Paste". Extending common user interface actions for something in QGIS that has no exact parallel but is still conceptually similar to that common action, like how Ctrl+Alt+V means paste what was copied into the buffer into a brand new layer, that makes sense. But ignoring decades of common UI actions that are in the muscle memory of probably all users makes the programme frustrating and tedious to use as one has to constantly remind themselves that QGIS is different.

**Comment by alexbruy** [comment]
Should we close this as wontfix?
