### ISSUE TITLE
Can't delete vertexes without removing the ones of an adjacent feature

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29373]
Author Name: **Luca Pasqualini** (Luca Pasqualini)
Original Redmine Issue: [21557](https://issues.qgis.org/issues/21557)
Affected QGIS version: 3.6.0
Redmine category:digitising

---
*new description*

Take two adjacent polygons

Toggle editing

Select the node tool

Right click with the node tool on a polygon > its nodes become "active"

Drag the node tool to select nodes in the "active" polygon, in a place where this polygon has a nearby one

Click the "del" button to delete the nodes

Expected result: only the nodes of the "active" polygon are delete (as it happen on 2.1)

Obtained result: the nodes of both the "active" and adjacent polygons are removed

*old description*
By selecting a single polygon to delete several of its points through a selection window, also to eliminate topological errors, points of other polygons belonging to the same layer are also activated and deleted.

**Comment by wonder-sk** [comment]
Do you have topological editing enabled?

With topo editing disabled, only vertices of the current feature are removed.
With topo editing enabled, also vertices of the adjacent feature are removed.

**Comment by uclaros** [comment]
This could probably close. It's either caused by topological editing, or some old bug that is no longer reproducible.

**Comment by gioman** [comment]
Closing for lack of feedback.
