### ISSUE TITLE
opening filesystem dialogs very slow on MacOS

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29378]
Author Name: **Gavin Fleming** (@gubuntu)
Original Redmine Issue: [21562](https://issues.qgis.org/issues/21562)
Affected QGIS version: 3.4.5
Redmine category:mac_os_specific

---
For all 3.x versions to date (and in different user profiles) any action in QGIS that opens a system dialog (e.g. saving or opening any file) results in a long wait for the dialog to completely render and populate and for the cursor to become responsive again. 

Nothing else on the system is slow and it doesn't happen with 2.18 so it's definitely a 3.x phenomenon.

**Comment by gubuntu** [comment]
yes this seems to have resolved in recent builds, please close
