### ISSUE TITLE
QGIS doesn't work properly with WFS 2.0.0 combined with OGC HTTP URI srsName style (e.g. http://www.opengis.net/def/crs/EPSG/0/xxxx)

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29391]
Author Name: **Jonas Pedersen** (Jonas Pedersen)
Original Redmine Issue: [21575](https://issues.qgis.org/issues/21575)
Affected QGIS version: 3.6.0
Redmine category:web_services_clients/wfs

---
When adding a layer from a Geoserver WFS 2.0.0 serving a layer using the OGC HTTP URI srsName style I get lots and lots of errors. 
It looks as if there are more than one problem involved (e.g. QGIS doesn't recognise the CRS and has you choose one).
But after choosing the correct CRS, the problem manifests itself when checking the box "Only request features overlapping the view extent".
When this box is checked QGIS generates a "GetFeature" request containing a malformed BBOX value as can be seen below:
/am/wfs?SERVICE=WFS&REQUEST=GetFeature&VERSION=2.0.0&TYPENAMES=am:ManagementRestrictionOrRegulationZone&COUNT=1000000&BBOX=53,6,58,15,

This BBOX value end with a "," where it should end with the srsName to make it valid - like below:
/am/wfs?SERVICE=WFS&REQUEST=GetFeature&VERSION=2.0.0&TYPENAMES=am:ManagementRestrictionOrRegulationZone&COUNT=1000000&BBOX=53,6,58,15,http://www.opengis.net/def/crs/EPSG/0/3044
Apart from that it also seems that the BBOX values for the corners themselves are also a little off (although I'm not sure of this).

For reference, I have pasted the corresponding "GetFeature" request, when the layer is served with the OGC URN srsName style (e.g. urn:ogc:def:crs:EPSG::xxxx):
/am/wfs?SERVICE=WFS&REQUEST=GetFeature&VERSION=2.0.0&TYPENAMES=am:ManagementRestrictionOrRegulationZone&COUNT=1000000&SRSNAME=urn:ogc:def:crs:EPSG::3044&BBOX=6013288,254451,6430433,1035230,urn:ogc:def:crs:EPSG::3044
Here the BBOX values for the corners are looks more realistic, and this notation works perfectly in QGIS.

Unfortunately I can't provide access to our Geoserver backend, but let me know if any additional information is needed.

regards,
Jonas

---

- [choose-CRS-for-layer.PNG](https://issues.qgis.org/attachments/download/14574/choose-CRS-for-layer.PNG) (Jonas Pedersen)
- [connect.PNG](https://issues.qgis.org/attachments/download/14575/connect.PNG) (Jonas Pedersen)

**Comment by Mikel0815** [comment]
Hello everybody,
are there any news to this problem? I had recently this problem with a WFS, which announces the srs in the http-style. I'm currently working with QGIS 3.14.1 on Fedora Linux and it's not possible to load the layer in the moment.

Thanks in advance,

Michael
