### ISSUE TITLE
Crashing QGIS during adding new feature with snapping and advanced digitizing tool is enable

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29396]
Author Name: **Lukáš Hríbik** (Lukáš Hríbik)
Original Redmine Issue: [21580](https://issues.qgis.org/issues/21580)
Affected QGIS version: 3.6.0
Redmine category:digitising

---
See attached video:

http://www.icsp.sk/20190314_091645.mp4

**Comment by gioman** [comment]
Closing for lack of feedback.
