### ISSUE TITLE
The option to set "Reuse last entered attribute values" for individual form fields separately.

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29392]
Author Name: **Lukasz Sychowicz** (Lukasz Sychowicz)
Original Redmine Issue: [21576](https://issues.qgis.org/issues/21576)

Redmine category:forms

---
With some fields i need to use last entered values, but also (at the same time) i need use expression as default values for other fields. 

For now only one of the enabled options works. If I check "settings/option/digitizing/ - Reuse last entered attribute values" then my expressions work only with the first object entered, next will be as "Reuse last entered attribute values"

**Comment by alexbruy** [comment]
Duplicates #17155
