### ISSUE TITLE
QGIS 3.4.5: Link to the user manual not working when running Danish version of QGIS - might be the same for other languages where the user manual is not translated?

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29393]
Author Name: **Mie Winstrup** (Mie Winstrup)
Original Redmine Issue: [21577](https://issues.qgis.org/issues/21577)
Affected QGIS version: 3.4.5
Redmine category:translations_and_international
Assignee: QGIS Translation Team

---
When running QGIS 3.4.5 with Danish translation, the link to the user manual is to a danish version of the user manual - but this does not exists.

This might be the same for other languages where the user manual is not translated?

As a consequence, when the user wants help - the browser opens with a url pointing to a danish version of the user manual (https://docs.qgis.org/3.4/da/docs/user_manual/index.html) which does not exists.

Instead the link should be to: 
(https://docs.qgis.org/3.4/en/docs/user_manual/index.html) which does not exists.

---

- [QGOS345-help.png](https://issues.qgis.org/attachments/download/14576/QGOS345-help.png) (Mie Winstrup)
- [QGOS345-help_in_tools.png](https://issues.qgis.org/attachments/download/14577/QGOS345-help_in_tools.png) (Mie Winstrup)

**Comment by MieWinstrup** [comment]
Not a problem.
Testet with QGIS 3.4.8 on Windows.

**Comment by DelazJ** [comment]
Yes there was a redirection issue in docs that has been fixed recently. So now languages that do not exist in docs are shown the English version.
This report can be closed. @gioman ?
