### ISSUE TITLE
GetPrint doesn't accept jpg format

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29403]
Author Name: **Nicolas Boisteault** (@nboisteault)
Original Redmine Issue: [21587](https://issues.qgis.org/issues/21587)

Redmine category:qgis_server

---
Getprint request returns error message "Output format image/jpeg is not supported by the GetPrint request" when setting format to jpg, jpeg or image/jpeg.
We can see here [1] that JPEG has been forgotten in QGIS 3.X.

[1] : https://github.com/qgis/QGIS/blob/master/src/server/services/wms/qgswmsgetprint.cpp#L37

**Comment by Gustry** [comment]
@nboisteault is telling me it's ok, closing.
