### ISSUE TITLE
Windows and Processing Raster calculator pyqgis troubles

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29402]
Author Name: **matteo ghetta** (@ghtmtt)
Original Redmine Issue: [21586](https://issues.qgis.org/issues/21586)
Affected QGIS version: 3.4.5
Redmine category:python_bindings_/_sipify
Assignee: Victor Olaya

---
The bug seems to be related ONLY on Windows system. A small dataset in attach. 

Briefly: it seems that when using the Processing Raster calculator in Windows via pyqgis, it is not possible to use raster(s) entire path(s). Only raster names loaded in the TOC are available.

To reproduce the error:

* load the attached `calculated` raster in the TOC
* run this script (that uses gdal_proximity on the loaded raster and then the output of gdal_proximity is used in the raster calculator)

```
param_proximity = {
	'INPUT': QgsProject.instance().mapLayersByName('calculated')[0],
	'BAND': 1,
    'UNITS' : 0,
	'OUTPUT': os.path.join(output, 'distance.tif')
}

proximity = processing.run("gdal:proximity", param_proximity)

param_calculated = {
	'EXPRESSION':'{}@1 * {}'.format(proximity['OUTPUT'], formula),
	'LAYERS': proximity['OUTPUT'],
	'OUTPUT': os.path.join(output, 'calcolato.tif')
}

calculated = processing.run("qgis:rastercalculator", param_calculated)

iface.addRasterLayer(calculated['OUTPUT'], 'final')

```

This is working on Linux and on QGIS 3.4, 3.6 and master while is ALWAYS failing in Windows. To make it working on Windows some lines have to be added:

```
param_proximity = {
	'INPUT': QgsProject.instance().mapLayersByName('calculated')[0],
	'BAND': 1,
    'UNITS' : 0,
	'OUTPUT': os.path.join(output, 'distance.tif')
}

proximity = processing.run("gdal:proximity", param_proximity)
QgsProject.instance().addMapLayer(QgsRasterLayer(proximity['OUTPUT'], 'dummy'))
rl = QgsProject.instance().mapLayersByName('dummy')[0]

param_calculated = {
	'EXPRESSION':'{}@1 * {}'.format(rl.name(), formula),
	'LAYERS': rl.name(),
	'OUTPUT': os.path.join(output, 'calcolato.tif')
}

calculated = processing.run("qgis:rastercalculator", param_calculated)

iface.addRasterLayer(calculated['OUTPUT'], 'final')

```

Fianlly, but still **extremely** important, with the same data the result is completely different. On Windows there are some super strange values (1.79769e+308 adn -1.79769e+308): some serious trouble with NODATA values?

---

- [calculated.tif](https://issues.qgis.org/attachments/download/14589/calculated.tif) (matteo ghetta)

**Comment by MrChebur** [comment]
I confirm this bug in QGIS 3.14, Windows 10. Trying to set 'LAYERS' parameter as file path leads to error.

**Comment by Pedro-Murteira** [comment]
@ghtmtt Hello, is this issue still valid on recent releases?

**Comment by ghtmtt** [comment]
@Pedro-Murteira I don't have a Windows running right now, so I cannot verify immediately. Maybe @MrChebur can have another try with the last QGIS version on Windows?

**Comment by MrChebur** [comment]
@ghtmtt 
@Pedro-Murteira 

Still doesn't support full filenames in the 'LAYERS' and 'EXPRESSION':
```python
test_folder = r'D:\!download\!QGIS test 2'

in_file = os.path.join(test_folder, 'calculated.tif')
output = os.path.join(test_folder, 'result.tif')
expression = f'"{in_file}@1" * 150"'  # this doesn't work on Windows 10
# expression = f'"calculated@1" * 150"'  # this is ok

param_calculated = {
    'EXPRESSION': expression,
    'LAYERS': [in_file],
    'CELLSIZE': 0,
    'EXTENT': None,
    'CRS': None,
    'OUTPUT': output,
}

print(f'expression={expression}')
print(f'in_file={in_file}')
print(f'output={output}')

calculated = processing.run("qgis:rastercalculator", param_calculated)
```

**Comment by ghtmtt** [comment]
thanks @MrChebur for the test.

**Comment by alexbruy** [comment]
This should be fixed in the latest versions with the algorithm ported to C++
