### ISSUE TITLE
QGIS crashes if  unsaved edits (with attribute modifications via plugin) are discarded while closing

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29401]
Author Name: **Faiz Kidwai** (Faiz Kidwai)
Original Redmine Issue: [21585](https://issues.qgis.org/issues/21585)
Affected QGIS version: 3.6.0
Redmine category:unknown

---
## User Feedback

Close QGIS with Unsaved edits in vector layerLayer and click on discard button

## Report Details

*Crash ID*: f0d1e19b6a981d91222b8c4b7f909999c9f8888c

*Stack Trace*
```
QgsFeature::setAttribute :
QgsVectorLayerUndoCommandChangeAttribute::undo :
QUndoCommand::undo :
QUndoStack::setIndex :
QgsVectorLayer::rollBack :
QgisApp::toggleEditing :
QgisApp::checkUnsavedLayerEdits :
QgisApp::fileExit :
QWidget::event :
QgisApp::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::close_helper :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processCloseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

```

*QGIS Info*
QGIS Version: 3.6.0-Noosa
QGIS code revision: 58734527ab
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.0
Running against GDAL: 2.4.0

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.14393

**Comment by m-kuhn** [comment]
Closed for lack of feedback / reproducability and likely related to 3rd party plugin based on the title.

Please open a new issue with detailed steps to reproduce if this still applies to a currently supported version.
