### ISSUE TITLE
Union/Difference fails

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29400]
Author Name: **Massimiliano Moraca** (Massimiliano Moraca)
Original Redmine Issue: [21584](https://issues.qgis.org/issues/21584)
Affected QGIS version: 3.6.0
Redmine category:processing/qgis

---
I think I've found a bug in version 4.4. I'm trying to use Union with two vectors and QGIS show me this error:
*GEOS geoprocessing error: difference failed*

I do the same thing with 2.18.28 version and all work fine.

In the attachment there are two vectors and five screenshots

---

- [dataset.zip](https://issues.qgis.org/attachments/download/14588/dataset.zip) (Massimiliano Moraca)

**Comment by technoautotroph** [comment]
I'm faced with a similar problem. I've tried multiple times to create a union of layers and get: "GEOS geoprocessing error: difference failed" The data is available here: https://drive.google.com/file/d/15V8DMMz9e09JXkuNONt31CWLG26TbzfX/view?usp=sharing

In an effort to resolve this problem I took the two layers that I'm trying to bring together (union) and split each into two parts (P1a & P2a; P1b & P2b).  I created a successful union between P1a and P1b (= P1 P1) and, P1a and P2b (P1 P2), P2a and P1b (P2 P1), and P2a and P2b (P2 P2). I was successful in the next step as well:
P1 P1 U P1 P2 = P112
AND
P2 P1 U P2 P2 = P221

The union fails when I try to execute:

P112 U P221 = Final

I tried using QGIS 2.18, but this did not solve my problem. I'm using Windows 10 on a fast machine with QGIS 3.6.3-Noosa.

**Comment by gioman** [comment]
> Ultimately I want to finalize with the following:
> 
> P112 U P221 = Final

@technoautotroph I downloaded your data and I'm not really sure what P* means... it would be  great if you can attach the 2 layers you are trying to Union (and that subsequently give an error).

**Comment by technoautotroph** [comment]
The data is available in the link to my GoogleDrive account that I provided above.

![Layers](https://user-images.githubusercontent.com/18059003/58969449-93f47500-876c-11e9-9251-938a1b70988f.jpg)

I used "P" to represent "Part 1 or Part 2". You will see in the image of the drive directory that the data layers have larger names, but they have P1P1 and P1P2 at the end of their file name. The "U" is the logical symbol / notation for Union. Those are the two layers that give the error. Hopefully this makes sense - let me know if I have missed something here.

**Comment by gioman** [comment]
> The data is available in the link to my GoogleDrive account that I provided above.

@technoautotroph your shapes are missing the .prj files, what is the CRS?

**Comment by gioman** [comment]
> Hopefully this makes sense - let me know if I have missed something here.

I'm afraid I have difficulties following the logic, but that is not a problem, just tell us what is the operation that fails, is the union (the QGIS native tools I guess) of

Fish plus ALR plus Amphib plus Wells plus Groundwater plus SEI P1 P2
and
Fish plus ALR plus Amphib plus Wells plus Groundwater plus SEI P1 P1

**Comment by technoautotroph** [comment]
I should have caught the missing .prj files - sorry I didn't see this. It's been updated.

Yes...the union of:

Fish plus ALR plus Amphib plus Wells plus Groundwater plus SEI P1 P2
and
Fish plus ALR plus Amphib plus Wells plus Groundwater plus SEI P1 P1

fails.

**Comment by gioman** [comment]
> I should have caught the missing .prj files - sorry I didn't see this. It's been updated.
> 
> Yes...the union of:
> 
> Fish plus ALR plus Amphib plus Wells plus Groundwater plus SEI P1 P2
> and
> Fish plus ALR plus Amphib plus Wells plus Groundwater plus SEI P1 P1

@technoautotroph your data has some (a lot) of nasty geometry errors and a  bunch of zero area polygons. Said that both the Processing/SAGA/Union tool and the Processing/GRASS/v.overlay tool (the latter by specifying to clean data on import) produce a result: https://we.tl/t-7Lv6u7Ztd9

Said that the QGIS tool always fails for me, even after cleaning the inputs with the Processing "make valid" tool and/or the core "geometry checker" plugin.

**Comment by wonder-sk** [comment]
just running "make valid" may not help with the topological error caused by numerical precision issues. As mentioned in #30114, one needs to do a combination of snapping with "make valid":

1. snap geometries of layer A (to each other) with some tolerance (e.g. 0.01m)
2. fix geometries of layer A (aka MakeValid)
3. snap geometries of layer B to layer A with some tolerance (ideally the same as in step 1)
4. fix geometries of layer B (aka MakeValid)

We have reliable processing algs for steps 1,2,4, but for step 3 we don't have a good one. For step 1 we have a ported the algorithm from grass' v.clean, and I think for step 3 we should do the same. And as suggested, maybe also combine all these steps into a single algorithm for easier use...

**Comment by technoautotroph** [comment]
I've been trying to problem solve this within <a href="https://gis.stackexchange.com/questions/324798/union-merge-intersection-join-layers-logical-difference-and-clear-explanati">StackExchange</a>. It seems that the bug may be more related to running multiple iterations of the union function in QGIS without addressing topological errors. I checked the geometry in each stage and manually addressed geometric errors, but as noted by wonder-sk, "make valid" may not help with the topological error. I'm going through the process using rstats sf package with sf_combine, sf_union, and as_Spatial to convert the layers into sp compatible format to run it through the cleangeo package. I'm hoping that this process will help to explain / understand the issue.

**Comment by technoautotroph** [comment]
I found this old bug report: https://issues.qgis.org/issues/15962
Was this ever resolved?

**Comment by gioman** [comment]
> I found this old bug report: https://issues.qgis.org/issues/15962
> Was this ever resolved?

@technoautotroph it says it clearly, was closed in favor of https://issues.qgis.org/issues/17131 that was closed because the qgis native geoprocessing tools have been in general rewritten/improved. The point is that if your inputs telemetries are very unclean (as the one you posted) is always better if you fix them beforehand ir you use a tool (i.e. GRASS) that can clean/fix them on the fly.

**Comment by technoautotroph** [comment]
Sorry...I missed that info - lots going on while trying to solve this problem. I ran the data through rstats packages:
```
RQGIS
cleangeo
```
in an effort to clean the layers:

```
Unionclean <- read_sf("...layer.shp")

Unionclean_sp <- as_Spatial(Unionclean)

## Geoclean process with the report
sp.clean <- clgeo_Clean(Unionclean_sp)
report.clean <- clgeo_CollectionReport(sp.clean)
clgeo_SummaryReport(report.clean)

require(rgeos)
sapply(slot(sp.clean, "polygons"), function(x){
  gIsValid(SpatialPolygons(Srl = list(x)))
})

## Convert back to sf
Unionclean <- as(sp.clean, "sf")
st_write(Unionclean,  "layer_c.shp")

```

This did not work. However, I ran the data through Grass v.clean default functions and this worked.

**Comment by gioman** [comment]
> However, I ran the data through Grass v.clean default functions and this worked.

@technoautotroph that is "normal": GRASS is a fullly topological GIS. When we run GRASS tools in QGIS the inputs are (on the fly) translated to simple features to a fully topological ones, this means that even by default a lot of cleaning is done, then after the geoprocessing operation the result is spit out again in simple features.

**Comment by arx-it** [comment]
I have a similar problem with geopackages : With the "difference" geoprocessing 

Here are the data : [https://drive.google.com/drive/folders/1jseoFHmzw5r_yQoxSywuPBHZkYctdx63?usp=sharing](url)

Here is the log :   

Version de QGIS : 3.14.1-Pi
Révision du code : de08d6b71d
Version de Qt : 5.11.2
Version de GDAL : 3.0.4
Version de GEOS : 3.8.1-CAPI-1.13.3
Version de Proj : Rel. 6.3.2, May 1st, 2020
Traitement de l'algorithme…
Démarrage de l'algorithme 'Différence'…
Paramètres en entrée:
{ 'INPUT' : 'D:/Temp/qgis_crash/grand.gpkg|layername=grand', 'OUTPUT' : 'TEMPORARY_OUTPUT', 'OVERLAY' : 'D:/Temp/qgis_crash/petit.gpkg|layername=petit' }

Erreur de géotraitement GEOS: la différence a échoué.


Échec d'exécution au bout de 0.15 secondes

Chargement des couches de résultat
Algorithme 'Différence' terminé

**Comment by gioman** [comment]
This needs to be checked again when QGIS will ship with the new GEOS.

**Comment by Pedro-Murteira** [comment]
I've tested this on QGIS 3.22.3. and I can't replicate the issue.
