### ISSUE TITLE
vulnerability in QGIS

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29411]
Author Name: **qy li** (qy li)
Original Redmine Issue: [21595](https://issues.qgis.org/issues/21595)
Affected QGIS version: 3.6.0
Redmine category:windows_package
Assignee: Jürgen Fischer

---
In QGIS 3.4.3 our vulnerability scanner identified an very critical issue with "C:\Program Files\QGIS 3.4\bin\psql.exe" from the component PostgreSQL 9.2.4.13228. The suggested solution is to "update to version 9.6.4, 9.5.8, 9.4.13, 9.3.18, or 9.2.22".
----
Im Produkt QGIS 3.4.3 ist unter dem Pfad „C:\Program Files\QGIS 3.4\bin\psql.exe“ die Komponente PostgreSQL 9.2.4.13228 als Schwachstelle identifiziert worden. Die Sicherheitslücke wird als sehr kritisch bewertet. Die vorgeschlagene Lösung nach unserem Schwachstellenscanner lautet die Komponente PostgreSQL „Update to version 9.6.4, 9.5.8, 9.4.13, 9.3.18, or 9.2.22.“.

**Comment by jef-n** [comment]
Fixes in OSGeo4W's libpq
