### ISSUE TITLE
Gpkg: raster slowdown

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29414]
Author Name: **Paolo Cavallini** (@pcav)
Original Redmine Issue: [21598](https://issues.qgis.org/issues/21598)
Affected QGIS version: 3.6.0
Redmine category:data_provider

---
* take this raster: https://www.faunalia.eu/~paolo/250010.tif
* drag and drop it in an existing geopackage
* load it from the geopackage in QGIS
* loading takes many seconds, QGIS slows down afterwards, with CPU at 100%

gdal 2.4.0+dfsg-1

**Comment by gioman** [comment]
Unable to replicate on 3.16.2 on Ubuntu 20.04.
