### ISSUE TITLE
Select by Location: Search Distance

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29413]
Author Name: **Brett Carlock** (@Saijin-Naib)
Original Redmine Issue: [21597](https://issues.qgis.org/issues/21597)

Redmine category:processing/qgis

---
A behavior I've found quite helpful from ESRI is the "Search Distance" function while performing a Select by Location. Granted, something similar can be fudged by buffering the selection layer by whatever units prior to using it against the features layer, but having this built into the selection tool can save a number of steps.

Request:
Select by Location to have an optional Search Distance feature.
Search Distance feature to support arbitrary/defined units (not only units in layer/project CRSs).

---

- [arcdesktop.png](https://issues.qgis.org/attachments/download/14596/arcdesktop.png) (Brett Carlock)
- [arcpro.png](https://issues.qgis.org/attachments/download/14597/arcpro.png) (Brett Carlock)
- [qgis.png](https://issues.qgis.org/attachments/download/14598/qgis.png) (Brett Carlock)

**Comment by alexbruy** [comment]
IMHO overloading algorithms with additional (already available with other tools!) functionality is not good. You always can combine multiple tools into script/model and use it.

**Comment by alexbruy** [comment]
IMHO this is a wontfix, as same fucntionality can be implemented using model/script.

**Comment by alexbruy** [comment]
Closing as wontfix. Please reopen if necessary.
