### ISSUE TITLE
OGR_ORGANIZE_POLYGONS unconditionally set in OGR provider

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29425]
Author Name: **Even Rouault** (@rouault)
Original Redmine Issue: [21609](https://issues.qgis.org/issues/21609)
Affected QGIS version: 3.7(master)
Redmine category:data_provider/ogr
Assignee: Even Rouault

---
The OGR_ORGANIZE_POLYGONS configuration option is unconditionally set to ONLY_CCW in the OGR provider
I believe this is inappropriate (should honour the value the user might have defined itself),
and useless. The OGR shapefile driver uses the ONLY_CCW strategy by default.
And this setting prevent the fix for https://github.com/OSGeo/gdal/issues/1369
for non-conformant multipolygons in FileGeodatabase to be effective from QGIS.

**Comment by gioman** [comment]
@rouault is this still relevant today?

**Comment by rouault** [comment]
> @rouault is this still relevant today?

yep, this is still there: https://github.com/qgis/QGIS/blob/3ba1242990ca1ce31dbc6d55a405b69492f1d9b1/src/core/providers/ogr/qgsogrprovider.cpp#L3415.
I'm going to submit a PR to remove this
