### ISSUE TITLE
CRS not written to file

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29432]
Author Name: **Mélanie Weynants** (Mélanie Weynants)
Original Redmine Issue: [21616](https://issues.qgis.org/issues/21616)
Affected QGIS version: 3.6.0
Redmine category:python_bindings_/_sipify

---
With QGIS 3.4.2 and 3.6.0, but not with 3.2.3:
When writing a vector layer to file, the CRS is not written, depending on the driver.
It happens with GPKG and GeoJSON but not with ESRI Shapefile.

Example:
>>>error = QgsVectorFileWriter.writeAsVectorFormat({
...    layer:layer, # layer in epsg:4326
...    fileName:"layer_54009",
...    fileEncoding:"utf-8",
...    destCRS:QgsCoordinateReferenceSystem(54009),
...    driverName:"GPKG",
...    onlySeleted:True
...    })
>>>error[0] == QgsVectorFileWriter.NoError
True

File layer_54009.gpkg|layername=layer_54009 is written to disk with the correct geometries (transformation from WGS84 to Mollweide is done) but  has undefined CRS.

The same problem happens with all algorithms I've tested, including "qgis:definecurrentprojection" and "native:assignprojection", which is really annoying.

**Comment by elpaso** [comment]
Tested this on master and it works fine, the only issue is that the CRS is set to 4326 even if in the created gpkg it is correctly set as 54009.
According to @nyalldawson and @rouault it might be an issue with the "Esri" auhority in the projection, it is probably solved with the new proj6.

**Comment by nyalldawson** [comment]
Closing due to lack of feedback
