### ISSUE TITLE
QGIS Crashed Windows when close qis

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29437]
Author Name: **Martín Fernando Ortiz** (Martín Fernando Ortiz)
Original Redmine Issue: [21621](https://issues.qgis.org/issues/21621)
Affected QGIS version: 3.4.4
Redmine category:project_loading/saving

---
## User Feedback

QGIS Crashed when i closed the project. I had made updates and also put new profiles with no plugins complements.
I have this problems since some months ago but i couldnt fix it.  I attached the project. 
Thanks!!! and congratulation for the great work that you are doing with qgis ;)

## Report Details

*Crash ID*: c8d80f3b38d15cdf5d0264d4cdea93f9ce32632e

*Stack Trace*
```
RtlFreeHeap :
clGetExtensionFunctionAddress :
clGetExtensionFunctionAddress :
clGetExtensionFunctionAddress :
clGetExtensionFunctionAddress :
clGetExtensionFunctionAddress :
clGetExtensionFunctionAddress :
clGetExtensionFunctionAddress :
execute_onexit_table :
execute_onexit_table :
execute_onexit_table :
QgsQtLocationConnection::qt_metacast :
QgsQtLocationConnection::qt_metacast :
RtlActivateActivationContextUnsafeFast :
LdrShutdownProcess :
RtlExitUserProcess :
FatalExit :
exit :
exit :
BaseThreadInitThunk :
RtlUserThreadStart :

```

*QGIS Info*
QGIS Version: 3.4.4-Madeira
QGIS code revision: f6ddc62fdb
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.0
Running against GDAL: 2.4.0

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

---

- [QGIS Project.zip](https://issues.qgis.org/attachments/download/14629/QGIS%20Project.zip) (Martín Fernando Ortiz)

**Comment by gioman** [comment]
Closing for the lack of feedback.
