### ISSUE TITLE
Check geometries crashing QGIS 3.6

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29435]
Author Name: **Pedro Henrique Caldeira Caliari** (Pedro Henrique Caldeira Caliari)
Original Redmine Issue: [21619](https://issues.qgis.org/issues/21619)
Affected QGIS version: 3.6.0
Redmine category:c++_plugins/geometry_checker

---
After running Check Geometries on QGIS 3.6, even by selecting a single vector layer or some of it's features, QGIS is crashing. When it has a considerable amount of errors, a "QGIS has crashed" window appears, while with a "small" amount of errors (230 or so), the algorithm might run normally and then QGIS crashes in less than a minute. Could it be that I'm using layers and files from a QGIS 2.x material? (if I run on all the layers, about 30k errors are reported and 350k+ errors are given as fixed/processed)

If Check Geometries shouldn't be used for layers containing many errors, which tool should I use in it's place for fixing common geometry errors?

---

- [Roads.7z](https://issues.qgis.org/attachments/download/14649/Roads.7z) (Pedro Henrique Caldeira Caliari)

**Comment by lbartoletti** [comment]
I cannot reproduce with QGIS 3.16 with the data. @gioman Do you reproduce the crash?

**Comment by gioman** [comment]
> I cannot reproduce with QGIS 3.16 with the data. @gioman Do you reproduce the crash?

@lbartoletti no more crashes, please reopen if necessary.
