### ISSUE TITLE
Scalebar display is wrong when working with different geographic coordinate systems

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29441]
Author Name: **Alessandro Frigeri** (Alessandro Frigeri)
Original Redmine Issue: [21625](https://issues.qgis.org/issues/21625)
Affected QGIS version: 3.6.0
Redmine category:decorations

---
Hello,

working with latlong coordinates, I've noticed that scalebar display of QGIS (3.6.0) is wrong when changing from WGS84 ellipsoid to, for example, Mars (GCS_Mars_2000 in the CRS list).

To replicate this, find attached a 10x10 1-degree latlon grid in GML format.   Spacing between 1-degree meridians at equator and between parallels should be around 111km for WGS84. 

Changing the SRS to GCS_Mars_2000 the same 1-deg distance should be around 59km, using the QGIS distance tool the measure is correctly displayed, but the scalebar is wrong (see the screenshot attached).

It seems that scalebar display keeps using WGS84 when working with different geographic coordinate systems, while the measuring tool seems to work.

best regards,

Alessandro Frigeri

 

---

- [10x10grid.gml](https://issues.qgis.org/attachments/download/14639/10x10grid.gml) (Alessandro Frigeri)
- [qgis_scalebar.png](https://issues.qgis.org/attachments/download/14640/qgis_scalebar.png) (Alessandro Frigeri)

**Comment by nyalldawson** [comment]
This is fixed for 3.14
