### ISSUE TITLE
Identifying a WMS layer with format "feature" crashes QGIS

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29443]
Author Name: **Richard Duivenvoorde** (@rduivenvoorde)
Original Redmine Issue: [21627](https://issues.qgis.org/issues/21627)
Affected QGIS version: 3.7(master)
Redmine category:web_services_clients/wms

---
Anybody can confirm:

Having a (geoserver) WMS showing points, then using the i-tool, the Identify-Tool panel does NOT show the fields that are (in the gml) doubles/reals. Integers and text are show, but those fields are empty!
To check:

Use wms: https://geodata.nationaalgeoregister.nl/bevolkingskernen2008/ows?SERVICE=WMS&
epsg:28992
layer: bevolkingskernen2008:bevolkingskernen2008_cbsbevolkingskernen2008

Activate 
Klik on a polygon, and look in the 'Identify Results' Panel. 

With me if I use Format: Text it looks like:

![gnome-shell-screenshot-J7M9YZ.png](https://issues.qgis.org/attachments/download/14643/gnome-shell-screenshot-J7M9YZ.png)

while if I use Format: Feature

![gnome-shell-screenshot-OCI9YZ.png](https://issues.qgis.org/attachments/download/14644/gnome-shell-screenshot-OCI9YZ.png)

What is asked is:

https://geodata.nationaalgeoregister.nl/bevolkingskernen2008/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&BBOX=94754.28008294067694806,472474.20718678156845272,128178.85744312187307514,492398.68952814734075218&CRS=EPSG:28992&WIDTH=1129&HEIGHT=673&LAYERS=cbsbevolkingskernen2008&STYLES=bevolkingskernen2008:bevolkingskernen2008_cbsbevolkingskernen2008&FORMAT=image/png&QUERY_LAYERS=cbsbevolkingskernen2008&INFO_FORMAT=application/json&I=590&J=421

Uh.... &INFO_FORMAT=application/json ??

Anyway, confirmed with me both on Windows and Linux on 3.4 and 3.7

---

- [gnome-shell-screenshot-J7M9YZ.png](https://issues.qgis.org/attachments/download/14643/gnome-shell-screenshot-J7M9YZ.png) (Richard Duivenvoorde)
- [gnome-shell-screenshot-OCI9YZ.png](https://issues.qgis.org/attachments/download/14644/gnome-shell-screenshot-OCI9YZ.png) (Richard Duivenvoorde)

**Comment by gioman** [comment]
@rduivenvoorde with the provided URL now QGIS (master, 3.12) crashes when identifying with "feature" format. On QGIS 2.18 does not crash and does returns all the values as happens in text/html formats.

**Comment by rduivenvoorde** [comment]
Note that this is not a valid WMS anymore... Off course should not crash, but I'm not sure if the original issue is still valid.
I will look for a newer public url.

**Comment by rduivenvoorde** [comment]
Sorry, WMS is still valid:

https://geodata.nationaalgeoregister.nl/bevolkingskernen2008/ows?SERVICE=WMS&cbsbevolkingskernen2008&request=getcapabilities

**Comment by gioman** [comment]
> Sorry, WMS is still valid:

yes it is, I tested it before commenting :)

**Comment by rduivenvoorde** [comment]
Ah, and crash is confirmed :-)

**Comment by elpaso** [comment]
Yes, I'm on it. I've fixed the crash but not yet the root cause.

**Comment by rduivenvoorde** [comment]
Crash is fixed and not showing attribute values work now!

Thanks!
