### ISSUE TITLE
r.sun cannot be executed because it calls on two incompatible options

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29453]
Author Name: **vince -** (vince -)
Original Redmine Issue: [21637](https://issues.qgis.org/issues/21637)
Affected QGIS version: 3.6.0
Redmine category:processing/grass
Assignee: Alexander Bruy

---
Trying to run the r.sun grass7 function from the Processing toolbox gives the following output:

"ERROR: insol_time and incidout are incompatible options"

And the process exits without producing any output. As was the case with r.sunmask, would it be possible to split that function into two mutually exclusive sub-functions?

**Comment by alexbruy** [comment]
Fixed in 121a92df7d0215bcae4b2420acf2cc6c595b9b1c
