### ISSUE TITLE
QGIS crashes when editing a polygon layer

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29452]
Author Name: **Markus Weidenbach** (Markus Weidenbach)
Original Redmine Issue: [21636](https://issues.qgis.org/issues/21636)
Affected QGIS version: 3.6.0
Redmine category:digitising

---
## User Feedback

I was editing a MulitPolygon layer (*.gpkg). In the Digitizing Option of this layer I set "Geometry Correction" to "Delete duplicate Vertices" and "Is Valid". Th e "Topology Control" was not set.
As expected, when I was trying to save the layer after editing it, I got the message to check and correct the Geometrie errors before being able to save the layer.
I zoomed to the coordinates where the intersection of two line elements have been detected. I selected the vertex in question and tried to delete it. Then QGIS crashed! 

We are working for some weeks now with this automatic geometry correction, I used it in 3.4 and now also in 3.6, and it caused permanent problems (it causes crashes and when repairing the detected errors, QGIS is ignoring it, ending up in an endless loop of correcting errors ...). 
I also can find no help or documnetation on that option. I ended upt to deactivate this funtion (only the automatic correction of duplicates of vertices works).

## Report Details

*Crash ID*: ad531a5ba6bb903396b6d917663ba2cbf0d1966e

*Stack Trace*
```
QgsFirstRunDialog::tr :
QModelIndex::data :
QgsFirstRunDialog::tr :
QgsFirstRunDialog::tr :
QgsFirstRunDialog::tr :
QgsFirstRunDialog::tr :
QMetaObject::activate :
QAbstractItemModel::dataChanged :
QgsFirstRunDialog::tr :
QMetaObject::activate :
QgsFormAnnotationDialog::qt_static_metacall :
QgsFirstRunDialog::tr :
QMetaObject::activate :
QgsVectorLayer::geometryChanged :
QMetaObject::activate :
QgsVectorLayerEditBuffer::geometryChanged :
QUndoStack::push :
QgsVectorLayerEditBuffer::changeGeometry :
QgsVectorLayer::changeGeometry :
QgsVectorLayerEditUtils::deleteVertex :
QgsVectorLayer::deleteVertex :
QgsVertexTool::deleteVertex :
QgsVertexTool::keyPressEvent :
QgsMapCanvas::keyPressEvent :
QWidget::event :
QFrame::event :
QAbstractScrollArea::event :
QgsMapCanvas::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processKeyEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
TranslateMessageEx :
TranslateMessage :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

```

*QGIS Info*
QGIS Version: 3.6.0-Noosa
QGIS code revision: 58734527ab
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.0
Running against GDAL: 2.4.0

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
