### ISSUE TITLE
Python Console Panel does not respect location/status across QGIS sessions

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29460]
Author Name: **Brett Carlock** (@Saijin-Naib)
Original Redmine Issue: [21644](https://issues.qgis.org/issues/21644)
Affected QGIS version: 3.6.0
Redmine category:gui

---
If you add the Python Console panel to your QGIS layout and dock it somewhere, it will not return to the same location when you close/re-open QGIS. It defaults to being disabled/turned off.

However, when you select it from the Plugins-> Python Console menu item, it does restore to the same docked area it was before, but its tab order will not be respected/restored.

I've attached a screenshot of where/how I typically want my Python console docked.

---

- [Annotation 2019-03-21 112950.png](https://issues.qgis.org/attachments/download/14653/Annotation%202019-03-21%20112950.png) (Brett Carlock)

**Comment by Pedro-Murteira** [comment]
@Saijin-Naib After re-opening QGIS, the python console is not enabled. 
Plugins > Python Console, the console is now active and in the same tab location as before. Is this fixed or am I missing something?
