### ISSUE TITLE
unexpected error in nodetool

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29469]
Author Name: **Peter Márton** (Peter Márton)
Original Redmine Issue: [21653](https://issues.qgis.org/issues/21653)
Affected QGIS version: 3.4.5
Redmine category:digitising

---
Create New Shapefile - I started to create new point layer. I activated "Vertex Tool" Current Layer option. I started digitizing - snapping options. After clicking to my map, I receive error message - unexpected error. It was necessary restart QGIS. But after this, I received this message when again modifying point layer or other new layer. I tried to create new project - again this error. I tried to restart computer - same error.

Operation system - Windows 10, 64byte

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
