### ISSUE TITLE
Cannot open netCDF file in QGIS 3.4.5

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29464]
Author Name: **Robert Zinke** (Robert Zinke)
Original Redmine Issue: [21648](https://issues.qgis.org/issues/21648)
Affected QGIS version: 3.4.5
Redmine category:rasters

---
Hello, 
I am trying to open a netCDF file in QGIS 3.4.5 on a Mac (Mojave), but I receive the error message: 

```
Invalid Layer: GDAL provider Cannot open GDAL dataset /Users/.../S1-GUNW-A-R-041-tops-20190220_20190208-120200-45050N_43180N-PP-bac2-v2_0_1.nc: `/Users/.../S1-GUNW-A-R-041-tops-20190220_20190208-120200-45050N_43180N-PP-bac2-v2_0_1.nc' not recognized as a supported file format. Raster layer Provider is not valid (provider: gdal, URI: /Users/.../S1-GUNW-A-R-041-tops-20190220_20190208-120200-45050N_43180N-PP-bac2-v2_0_1.nc

```

Apparently, this is a similar issue to those of the closed discussions here: #28799 #28740

I cannot find the Mac installer for QGIS 3.7-master, as suggested here - #28799 - only .exe files are available on the weekly downloads page. I downloaded the most recent version of QGIS for Mac (v. 3.6.0 Noosa) but that gives the same error. 

What is the best way to read netCDF files into QGIS on Mac? 

Thanks for any assistance!
-Robert

**Comment by alexbruy** [comment]
Still true with master?

**Comment by gioman** [comment]
Works on with a few samples on QGIS 3.14.0 on macOS Catalina, please reopen if necessary.
