### ISSUE TITLE
qgis crashes when resetting map scale in  new map view

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29473]
Author Name: **luca bellani** (luca bellani)
Original Redmine Issue: [21657](https://issues.qgis.org/issues/21657)
Affected QGIS version: 3.6.0
Redmine category:map_canvas

---
I work with several map views at the same time. When I try to modify the scale factor, or any of the options of the attached canvases, QGIS goes in crash. Sometimes, it signals an error, sometimes not, and it closes without warning anything.
It happens both in 3.4.5 that 3.6
It happens in 2 computers, with the same windows 10 64 bit v 1809.
Both with the OPEN_CL activated, and deactivated.

pc1: intel I7 4280, 16 Giga RAM DDR3, SSD, GTX 850ME
pc2: intel I7 6800K, 16 Giga DDR4, SSD, GTX 1060 6 giga.

---

- [1.PNG](https://issues.qgis.org/attachments/download/14658/1.PNG) (luca bellani)
- [Anotación 2019-03-22 134724.png](https://issues.qgis.org/attachments/download/14659/Anotaci%C3%B3n%202019-03-22%20134724.png) (luca bellani)
- [error maps canvas.mp4](https://issues.qgis.org/attachments/download/14662/error%20maps%20canvas.mp4) (luca bellani)

**Comment by PeterPetrik** [comment]
Unable to replicate on MacOS (Qt 5.14.2)

**Comment by Pedro-Murteira** [comment]
I can't replicate this issue on QGIS 3.22.3. (Windows 10)
