### ISSUE TITLE
Software Crash

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29471]
Author Name: **Hassan Tariq** (Hassan Tariq)
Original Redmine Issue: [21655](https://issues.qgis.org/issues/21655)
Affected QGIS version: 3.4.5
Redmine category:unknown

---
I add the GeoReference Map in the project, then I create the new polygon shape layer and got the following error and software stop working.

Crash ID: 5c9e72de23eb99732793ab7788206f40a82565da

Stack Trace

QgsMapCanvas::setMapTool :
QgisApp::activateDeactivateLayerRelatedActions :
QMetaObject::activate :
QgisApp::activeLayerChanged :
QgisApp::onActiveLayerChanged :
QMetaObject::activate :
QgsLayerTreeView::currentLayerChanged :
QgsLayerTreeView::onCurrentChanged :
QMetaObject::activate :
QItemSelectionModel::setCurrentIndex :
QAbstractItemView::setCurrentIndex :
QgisApp::autoSelectAddedLayer :
QgisApp::identifyMapTool :
QMetaObject::activate :
QgsLayerTreeRegistryBridge::addedLayersToLayerTree :
QgsLayerTreeRegistryBridge::layersAdded :
QMetaObject::activate :
QgsProject::legendLayersAdded :
QgsProject::addMapLayers :
QgisApp::addVectorLayers :
QgisApp::newVectorLayer :
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.4.5-Madeira
QGIS code revision: 89ee6f6e23
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.0
Running against GDAL: 2.4.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
