### ISSUE TITLE
composer legend feature count not correct when datasource is in a network folder

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29484]
Author Name: **Yohan GIBERT** (Yohan GIBERT)
Original Redmine Issue: [21668](https://issues.qgis.org/issues/21668)
Affected QGIS version: 3.6.0
Redmine category:map_composer/printing

---
In english :
On export, counting entities in the legend displays [n / a] instead of the count for a categorized layer. The overall count of the layer is exported well but not at the category level.

En Français :
A l'export, le décompte des entités dans la légende affiche [n/a] au lieu du décompte pour une couche catégorisée. Le décompte général de la couche s'exporte bien mais pas au niveau des catégories.

---

- [légende décompte NOK.png](https://issues.qgis.org/attachments/download/14665/l%C3%A9gende%20d%C3%A9compte%20NOK.png) (Yohan GIBERT)
- [légende décompte OK.png](https://issues.qgis.org/attachments/download/14666/l%C3%A9gende%20d%C3%A9compte%20OK.png) (Yohan GIBERT)

**Comment by Doctor-Who** [comment]
Hello,

We still find this problem tested on QGIS 3.12 and 3.14 on Windows 10
![bugtracker](https://user-images.githubusercontent.com/5890416/91011465-9eef2b80-e5e4-11ea-96d1-5846b74d8658.jpg)

On the left : legend in composer
On the right : after export in jpg

Best,

Nicolas

**Comment by Doctor-Who** [comment]
This bug can be close, by starting from a clean blank project, everything works even with network GPKG or PostGIS layers.
