### ISSUE TITLE
crash unload plugins on exit

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29482]
Author Name: **Dimuthu Wickramasinghe** (Dimuthu Wickramasinghe)
Original Redmine Issue: [21666](https://issues.qgis.org/issues/21666)
Affected QGIS version: 3.4.0
Redmine category:unknown

---
## Report Details

*Crash ID*: 2158b01f96452b8cf079fabd6f476862ce1a56f9

*Stack Trace*
```
QDockWidget::toggleViewAction :
QgisApp::removeDockWidget :
QgsPresetSchemeColorRamp::clone :
PyCFunction_FastCallDict :
PyObject_GenericGetAttr :
PyEval_EvalFrameDefault :
PyObject_GenericGetAttr :
PyEval_EvalFrameDefault :
PyObject_GenericGetAttr :
PyEval_EvalFrameDefault :
PyErr_Occurred :
PyEval_EvalCode :
PyArena_Free :
PyRun_StringFlags :
instance :
instance :
QgsPluginRegistry::unloadAll :
QgisApp::saveWindowState :
QMetaObject::activate :
QCoreApplicationPrivate::execCleanup :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

```

*QGIS Info*
QGIS Version: 3.2.3-Bonn
QGIS code revision: 9b176802e5
Compiled against Qt: 5.9.2
Running against Qt: 5.9.2
Compiled against GDAL: 2.2.4
Running against GDAL: 2.2.4

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
