### ISSUE TITLE
Data defined grid properties in composer

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29497]
Author Name: **Giulio Fattori** (Giulio Fattori)
Original Redmine Issue: [21681](https://issues.qgis.org/issues/21681)

Redmine category:map_composer/printing

---
It would be incredibly useful to be able if grid and graticule in QGIS Print Composer can controlled from a variable like other feature (data driven) in such a way as to make them dependent on the scale of the map or a relate field from data table.
Many thanks

**Comment by nyalldawson** [comment]
Duplicate of #30246
