### ISSUE TITLE
Zonal Statistics alters zone layer, should create new layer

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29504]
Author Name: **Johannes Kroeger** (Johannes Kroeger)
Original Redmine Issue: [21688](https://issues.qgis.org/issues/21688)

Redmine category:processing/qgis

---
Zonal Statistics tries to write the statistics to the file/layer chosen in "Vector layer containing zones".

I have not tried, but I would assume that this renders the tool unusable with e.g. a read-only WFS source.

Pretty much all other tools, including Zonal Histogram, instead create a new layer or file.

Please make Zonal Statistics not try to alter the zone layer by default, instead use the same mechanism ("[Create temporary layer]"  by default) as other tools.

**Comment by alexbruy** [comment]
This should be an analysis library feature request not Processing

**Comment by alexbruy** [comment]
Fixed in #38650
