### ISSUE TITLE
Styles stored in QML files with same name as layer no longer auto loaded

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29507]
Author Name: **Andrew Robinson** (Andrew Robinson)
Original Redmine Issue: [21691](https://issues.qgis.org/issues/21691)
Affected QGIS version: 3.6.0
Redmine category:symbology
Assignee: Alexander Bruy

---
In QGIS 3.2 if I save a vector layer (GeoPackage) as My_Layer.gpkg and I save the styles in a QML file with the same e.g My_Layer.qml, in the same directory as the vector layer then the styles are automatically loaded when that vector layer is opened. In QGIS 3.6 this no longer happens. Instead the QML file must be manually loaded.

**Comment by alexbruy** [comment]
PR #14660

**Comment by nyalldawson** [comment]
Fixed in ab2d6f4f04dbb028c44b9477686f238c855c6bea
