### ISSUE TITLE
QGIS Crashed on exit

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29500]
Author Name: **Olivier Suc** (Olivier Suc)
Original Redmine Issue: [21684](https://issues.qgis.org/issues/21684)
Affected QGIS version: 3.6.0
Redmine category:unknown

---
Crash ID: 131aa1cfd3b2d4b43cc7288ec22d10a27aafca25

Stack Trace

QgsTransformEffect::readProperties :
QgsLayerTreeNode::children :
QgsLayerTreeModel::rowCount :
QAbstractItemModel::hasChildren :
QSortFilterProxyModel::hasChildren :
QTreeView::doItemsLayout :
QTreeViewPrivate::updateScrollBars :
QTreeView::updateGeometries :
QMetaObject::activate :
QHeaderView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::setStyle_helper :
QWidgetPrivate::inheritStyle :
QWidgetPrivate::setStyle_helper :
QWidgetPrivate::inheritStyle :
QWidgetPrivate::setStyle_helper :
QWidgetPrivate::inheritStyle :
QWidgetPrivate::setStyle_helper :
QWidgetPrivate::inheritStyle :
QWidgetPrivate::setStyle_helper :
QWidgetPrivate::inheritStyle :
QWidgetPrivate::setStyle_helper :
QWidgetPrivate::inheritStyle :
QWidget::setParent :
QWidget::setParent :
QWidgetAction::releaseWidget :
QToolBar::widgetForAction :
QToolBar::widgetForAction :
QWidget::~QWidget :
QgsVectorLayerProperties::`default constructor closure' :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
CPLStringList::operator[] :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.6.0-Noosa
QGIS code revision: 58734527ab
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.0
Running against GDAL: 2.4.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
