### ISSUE TITLE
QGIS crash when deleting layers

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29514]
Author Name: **Wolfgang Meinolf** (Wolfgang Meinolf)
Original Redmine Issue: [21698](https://issues.qgis.org/issues/21698)
Affected QGIS version: 3.6.1
Redmine category:unknown

---
## User Feedback

Started QGIS from Start menu. Opened recent project. Deleted layers (type shp and gpkg). Did nothing else.

## Report Details

*Crash ID*: efb36a85655a7979e6c09c4f7b09e308c5d4f797

*Stack Trace*
```
QgsVectorLayer::~QgsVectorLayer :
QgsVectorLayerUndoCommandRenameAttribute::~QgsVectorLayerUndoCommandRenameAttribute :
QgsMapLayerStore::removeMapLayers :
QgsMapLayerStore::removeMapLayers :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
TranslateMessageEx :
TranslateMessage :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

```

*QGIS Info*
QGIS Version: 3.6.1-Noosa
QGIS code revision: 2468226bc9
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

---

- [Installed Plug-ins.jpg](https://issues.qgis.org/attachments/download/14686/Installed%20Plug-ins.jpg) (Wolfgang Meinolf)
- [Installed Plug-ins necessary.jpg](https://issues.qgis.org/attachments/download/14687/Installed%20Plug-ins%20necessary.jpg) (Wolfgang Meinolf)
- [All Plugins disabled.jpg](https://issues.qgis.org/attachments/download/14690/All%20Plugins%20disabled.jpg) (Wolfgang Meinolf)
- [190329 QGIS generated Layers.jpg](https://issues.qgis.org/attachments/download/14691/190329%20QGIS%20generated%20Layers.jpg) (Wolfgang Meinolf)
- [190329 QGIS Model.jpg](https://issues.qgis.org/attachments/download/14692/190329%20QGIS%20Model.jpg) (Wolfgang Meinolf)
- [190329 QGIS Mouseover generated perm layer.jpg](https://issues.qgis.org/attachments/download/14693/190329%20QGIS%20Mouseover%20generated%20perm%20layer.jpg) (Wolfgang Meinolf)
- [190329 QGIS Mouseover generated temp layer 1.jpg](https://issues.qgis.org/attachments/download/14694/190329%20QGIS%20Mouseover%20generated%20temp%20layer%201.jpg) (Wolfgang Meinolf)
- [190329 QGIS Mouseover generated temp layer 2.jpg](https://issues.qgis.org/attachments/download/14695/190329%20QGIS%20Mouseover%20generated%20temp%20layer%202.jpg) (Wolfgang Meinolf)
- [190329 QGIS Mouseover generated temp layer 3.jpg](https://issues.qgis.org/attachments/download/14696/190329%20QGIS%20Mouseover%20generated%20temp%20layer%203.jpg) (Wolfgang Meinolf)

**Comment by AlisterH** [comment]
This ticket has a "feedback" tag, but it isn't obvious what feedback is required.
I wonder if the ticket is still valid though, since it was filed for an older version.  I see crashes in 3.10.0 when layers are closed as the project is closed, but I think they are related to CRS transformations.

**Comment by gioman** [comment]
> Let me know, if the info above and attached screenshots help.

attaching a sample project+data would help a lot.

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
