### ISSUE TITLE
Hang/Crash when attempting to drag&drop multiple layers into gpkg

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29510]
Author Name: **Brett Carlock** (@Saijin-Naib)
Original Redmine Issue: [21694](https://issues.qgis.org/issues/21694)
Affected QGIS version: 3.6.1
Redmine category:browser

---
The time it takes to import a number of layers into a geopackage seems to increase exponentially. For instance, there is no noticeable delay from time of drop to beginning of import at less than 10 layers. Somewhere between 10-20 layers there is a pause of 10s or more. Any more than 20 layers the pause becomes longer. Trying to drag/drop 105 layers results in an unresponsive QGIS GUI with 1 CPU thread pegged, no disk activity, and static (not growing) RAM usage for the QGIS process.

There should be the means to batch import data into a geopackage, especially if one is trying to migrate away from an ESRI environment where large file geodatabases are commonplace. Having to batch things a handful of layers at a time is tedious at best.

---

Related issue(s): #29511 (relates)
Redmine related issue(s): [21695](https://issues.qgis.org/issues/21695)

---

**Comment by roya0045** [comment]
Still valid un 3.14.16. Batch of 7 is fine, 40 causes hang.

**Comment by roya0045** [comment]
Might be a limitation of qgstaskmanager or qgsvectorlayerexportertask.

**Comment by SGroe** [comment]
I confirm this crash is still happening with QGIS 3.34.
Drag&drop 20 layers is working, moving more layers results in a infinite freeze.
