### ISSUE TITLE
Quit menu disabled in QGIS Mac

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29527]
Author Name: **MRick -** (MRick -)
Original Redmine Issue: [21711](https://issues.qgis.org/issues/21711)
Affected QGIS version: 3.6.1
Redmine category:mac_os_specific

---
In QGIS Mac, the Quit menu is disabled.
But the shortcut ⌘Q does work.
Plus it is not localised for non English versions.

---

- [Capture d’écran 2019-03-30 à 20.28.22.png](https://issues.qgis.org/attachments/download/14704/Capture%20d%E2%80%99%C3%A9cran%202019-03-30%20%C3%A0%2020.28.22.png) (MRick -)
- [Capture d’écran 2019-03-30 à 20.28.33.png](https://issues.qgis.org/attachments/download/14705/Capture%20d%E2%80%99%C3%A9cran%202019-03-30%20%C3%A0%2020.28.33.png) (MRick -)

**Comment by PeterPetrik** [comment]
unable to replice with https://qgis.org/downloads/macos/ releases

**Comment by gioman** [comment]
Closing for lack of feedback, no issues with the latest installers on Catalina.
