### ISSUE TITLE
Export selected Objects generated line layer not selectable in graphical modeller

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29521]
Author Name: **Wolfgang Meinolf** (Wolfgang Meinolf)
Original Redmine Issue: [21705](https://issues.qgis.org/issues/21705)
Affected QGIS version: 3.6.1
Redmine category:processing/modeller
Assignee: Victor Olaya

---
Background: 
(1) Script selects point objects, which then shall be exported to new layer for further use in v.net. 
(2) Script also selects line objects in 2 stages. Selected objects shall also be exported to new layer for further use in v.net.

Both generated layers are presented in v.net as point layers, so ist's not possible to insert v.net in script.

Manual Test in QGIS w/o script works fine, generated line and point layers be selected in v.net without problem. 

Screenshots of selection pull down menus attached

---

- [190329 QGIS Wrong Type Export selected 1.jpg](https://issues.qgis.org/attachments/download/14699/190329%20QGIS%20Wrong%20Type%20Export%20selected%201.jpg) (Wolfgang Meinolf)
- [190329 QGIS Wrong Type Export selected.jpg](https://issues.qgis.org/attachments/download/14700/190329%20QGIS%20Wrong%20Type%20Export%20selected.jpg) (Wolfgang Meinolf)
- [Debug.zip](https://issues.qgis.org/attachments/download/14701/Debug.zip) (Wolfgang Meinolf)

**Comment by alexbruy** [comment]
Selection exists only in the loaded layers. if you need to use subset of features as input in another tool it is necessary to export them instead of selecting.

**Comment by alexbruy** [comment]
I think we can close this, as for models "Extract..." algorithms should be used instead of "Select..."
