### ISSUE TITLE
algorithm "Eliminate selected polygons" works only with the result format "memory layer" 

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29520]
Author Name: **Thomas Kneissl** (Thomas Kneissl)
Original Redmine Issue: [21704](https://issues.qgis.org/issues/21704)
Affected QGIS version: 3.4.3
Redmine category:processing/qgis
Assignee: Victor Olaya

---
I try to merge a few selected polygons with their neighbors using the tool "Eliminate selected polygons" (with mode "Largest Common Boundary"). This works perfectly as long as I use a memory layer as result. If I want to write the result in a file the polygons don't get merged (the result looks exactly like the input).

**Comment by lbartoletti** [comment]
It seems to work for me. Can you try again with the latest QGIS version?

**Comment by gioman** [comment]
> It seems to work for me. Can you try again with the latest QGIS version?

@lbartoletti see also https://github.com/qgis/QGIS/issues/40407

**Comment by gioman** [comment]
> @lbartoletti see also #40407

@lbartoletti I guess that if in both cases/tickets 3.16 is ok then we can close both tickets.

**Comment by gioman** [comment]
Closing for lack of feedback.
