### ISSUE TITLE
trace/streamline visualisation 

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29534]
Author Name: **Peter Petrik** (@PeterPetrik)
Original Redmine Issue: [21719](https://issues.qgis.org/issues/21719)

Redmine category:mesh_layers
Assignee: Peter Petrik

---
Add trace/streamline visualisation of vector quantities (arrows)

https://prideout.net/blog/streamlines/
http://www.mdal.xyz
http://www.scisoftware.com/environmental_software/detailed_description/bama-2.gif

"old" implementation in 2.x in crayfish: https://github.com/lutraconsulting/qgis-crayfish-plugin/blob/release-2.7.0/corelib/crayfish_trace.cpp

estimate is a week of work

**Comment by PeterPetrik** [comment]
https://github.com/lutraconsulting/qgis-crayfish-plugin/pull/279

**Comment by saberraz** [comment]
Here is a working example:
https://www.xmswiki.com/images/0/06/Bama.gif
