### ISSUE TITLE
Disconnect between raster symbology in Layers Panel and Layer Properties

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29536]
Author Name: **Ed B** (@boesiii)
Original Redmine Issue: [21721](https://issues.qgis.org/issues/21721)
Affected QGIS version: 3.4.6
Redmine category:rasters

---
When using pyqgis to style raster layers, the layer properties symbology tab does not get updated with the information coming from python.  If you run my sample python code below you will see the problem.  The symbology is not consistent between the layers panel and the layer property symbology.

@from qgis.core import QgsRasterLayer

rlayer = QgsProject.instance().mapLayersByName('ac_filled_rvrem102')[0]
print (rlayer)
provider = rlayer.dataProvider()
stats = provider.bandStatistics(1, QgsRasterBandStats.All) 
fcn = QgsColorRampShader()
fcn.setColorRampType(QgsColorRampShader.Interpolated)
lst = [ QgsColorRampShader.ColorRampItem(stats.minimumValue, QColor(247,251,255)),
      QgsColorRampShader.ColorRampItem(stats.maximumValue, QColor(237,48,243)) ]
fcn.setColorRampItemList(lst)
shader = QgsRasterShader()
shader.setRasterShaderFunction(fcn)
renderer = QgsSingleBandPseudoColorRenderer(rlayer.dataProvider(), 1, shader)
rlayer.setRenderer(renderer)
rlayer.triggerRepaint()@

The page below also describes the issue
https://gis.stackexchange.com/questions/316450/disconnect-between-raster-symbology-in-layers-panel-and-layer-properties-qgis-3

I also updated to 3.4.6 and the same issue occurs.

**Comment by Pedro-Murteira** [comment]
Hello @boesiii, this bug seems to be fixed according to this comment on [](https://gis.stackexchange.com/questions/316450/disconnect-between-raster-symbology-in-layers-panel-and-layer-properties-qgis-3):
> The problem doesn't occur with later versions of QGIS. Not sure exactly when the bug was fixed, but I've just been using my original plugin with QGIS 3.14.0 and values/labels are consistent between the Layers Panel and Layer Properties.
Did you come across this issue in more recent versions of QGIS?

**Comment by cory-garms** [comment]
This issue has returned, it persists in version 3.32.2 and 3.38.0. See here: https://gis.stackexchange.com/questions/485597/rendering-tiff-in-classified-presentation-in-qgis-plugin/486245#486245
