### ISSUE TITLE
Reprojection not working on Mapinfo tabfiles

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29544]
Author Name: **Mie Winstrup** (Mie Winstrup)
Original Redmine Issue: [21729](https://issues.qgis.org/issues/21729)
Affected QGIS version: 3.4.5
Redmine category:vectors

---
I have a mapinfo-tab file in coordinate system EPSG:3044. I want to reproject it to EPSG:25832, and keep it as a mapinfo-file.

I have tried various ways to reproject the file to the new coordinate system, among other the 'Reproject Layer'-tool where I select Tab-files as the output format.
The tool runs without any problem, but the coordinatsystem in the new reprojected layer is the still EPSG 3044 - and not EPSG25832.

It works fine if I reproject to a shapefile.

The same happens in the export-function from the layer properties.

I have attached two screenshots and the tab-file

---

- [bug1.png](https://issues.qgis.org/attachments/download/14716/bug1.png) (Mie Winstrup)
- [bug2.png](https://issues.qgis.org/attachments/download/14717/bug2.png) (Mie Winstrup)
- [Pointdata.zip](https://issues.qgis.org/attachments/download/14718/Pointdata.zip) (Mie Winstrup)

**Comment by stev-0** [comment]
Suggest closing as GDAL bug

**Comment by nyalldawson** [comment]
Ok, closed as upstream issue
