### ISSUE TITLE
QGIS crashes on "Open project"

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29545]
Author Name: **Alistair Branagh** (Alistair Branagh)
Original Redmine Issue: [21730](https://issues.qgis.org/issues/21730)
Affected QGIS version: 3.4.6
Redmine category:project_loading/saving

---
When I try to open a project the application crashes. It happens every time. I have been trying to move up to v3 from 2.18 but it has been impossible due to these crashes. I am now having problems with 2.18 however as it is no longer supported I have no choice but to adapt to the newer version for working in. 

I don't know what the problem could be so would welcome input. 

Crash ID: 09e6674cc2ce085fa2ac5d2e6559199ef841bb85

Stack Trace

RtlFreeHeap :
HeapFree :
free :
DllUnregisterServer :
DllUnregisterServer :
CLSIDFromString :
CLSIDFromString :
CLSIDFromString :
CLSIDFromString :
IsEqualGUID :
IsEqualGUID :
CLSIDFromString :
CLSIDFromString :
CLSIDFromString :
CLSIDFromString :
CLSIDFromString :
ObjectStublessClient6 :
CoCreateInstanceEx :
ObjectStublessClient32 :
SHParseDisplayName :
Ordinal866 :
ILSaveToStream :
ShellExecuteExW :
ShellExecuteExW :
ShellExecuteExW :
Ordinal860 :
ShellExecuteExW :
ExtractIconExW :
DllCanUnloadNow :
DllCanUnloadNow :
DllCanUnloadNow :
DllCanUnloadNow :
IUnknown_SetSite :
DllGetClassObject :
DllGetClassObject :
DllCanUnloadNow :
DllCanUnloadNow :
DllCanUnloadNow :
DllCanUnloadNow :
DllCanUnloadNow :
DllCanUnloadNow :
GetMenuStringW :
CreateDialogParamW :
CreateDialogParamW :
TranslateMessageEx :
GetMenuStringW :
GetComboBoxInfo :
DialogBoxIndirectParamAorW :
DialogBoxIndirectParamW :
DllCanUnloadNow :
QDialog::exec :
QFileDialog::getOpenFileUrl :
QFileDialog::getOpenFileName :
QgisApp::fileOpen :
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
TranslateMessageEx :
TranslateMessage :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.4.6-Madeira
QGIS code revision: cc0e375a9f
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

---

Related issue(s): #26151 (relates)
Redmine related issue(s): [18260](https://issues.qgis.org/issues/18260)

---

**Comment by alexbruy** [comment]
Still true with 3.10/master?

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
