### ISSUE TITLE
Items from table do not load properly

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29547]
Author Name: **Zannis Kostalas** (Zannis Kostalas)
Original Redmine Issue: [21732](https://issues.qgis.org/issues/21732)
Affected QGIS version: 3.4.2
Redmine category:data_provider/mssql

---
I have a table with geography (SRID 4326) line items. While the majority of them show properly some of them do not show at all. Note that these lines straddle the anti-meridian but this normally does not cause any other issues than the resulting cross-globe lines.

If I try to load the table directly from the db with just the "use estimated parameters" selected in connection options and try to apply a simple filter "id IN (xxx,xxx,xxx,xxx,xxx,xxx) the "test query" function returns 0 rows. If I select to load the layer nonetheless, there is nothing in the map but the attribute table is populated with the rest of the fields

If I also select "skip invalid geometry handling", the test query returns 6 rows which is what I would expect, but still nothing shows in the map.

Casting geography to WKT using .STAsText() and extracting data in a csv results in the layer loading properly.

I am attaching a csv with the following fields:

id: Primary Key, unique non null smallint
PATH: geography, binary from MSSQL 16
wkt_geography: result of PATH.STAsText()
path_geom: casting PATH to geometry using geometry::STGeomFromWKB([PATH].STAsBinary(), 4326)
wkt_geometry: casting the above to text
validity_check: applying .STIsValid() to PATH
validity_check_geom: applying .STIsValid() to PATH after casting to geometry

in the hopes that some conclusion can be drawn as to why this happens.

---

- [lines_checks.csv](https://issues.qgis.org/attachments/download/14722/lines_checks.csv) (Zannis Kostalas)

**Comment by gioman** [comment]
Closing for lack of feedback.
