### ISSUE TITLE
selection color setting has no effect

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29549]
Author Name: **hong chen** (hong chen)
Original Redmine Issue: [21734](https://issues.qgis.org/issues/21734)
Affected QGIS version: 3.6.1
Redmine category:map_canvas

---
look the attechment picture, the objects select color and map backgroud color setting does not effact the mapcontrol.

---

- [Snap2.jpg](https://issues.qgis.org/attachments/download/14724/Snap2.jpg) (hong chen)

**Comment by alexbruy** [comment]
You need to restart QGIS to apply these settings. Works fine in master and 3.8.
