### ISSUE TITLE
Aggregate processing tool - Group by expression ($geometry) doesn't work

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29555]
Author Name: **Brent Edwards** (Brent Edwards)
Original Redmine Issue: [21740](https://issues.qgis.org/issues/21740)
Affected QGIS version: 3.6.0
Redmine category:processing/qgis

---
As the title states, when attempting to aggregate by geometry the results are inconclusive.

I tested the following expressions on a selection set of 2 identical polygons and they all produced the same result set of 2 polygons:

1) $geometry
2) geom_to_wkt($geometry)
3) centroid($geometry)

I was able to get the correct results by simply creating a virtual field with the same expression (ex. geom_to_wkt($geometry)) and the tool produced the correct result (single polygon with the agg fields).

**Comment by nyalldawson** [comment]
Closing due to lack of feedback -- for reference, I believe this was fixed during 3.6.x
