### ISSUE TITLE
Ability to choose sheets from Spreadsheet data sources

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29554]
Author Name: **Brett Carlock** (@Saijin-Naib)
Original Redmine Issue: [21739](https://issues.qgis.org/issues/21739)

Redmine category:data_provider

---
Currently, we can import a spreadsheet (spatial or non-spatial) with ease. Good stuff.

However, the import is quite limited in that it only chooses the first sheet from the object.

I'd like to see this behavior improved to have a similar UI/UX to the layer picker when opening geopackages, folders of shapefiles, File Geodatabases, etc. where the list of objects is presented, and you can choose one/some/all/none to import, along with metadata about each feature. Aside from just being consistent, this would make it far easier to work with spreadsheet data without having to constantly subset/export/import the sheets you want at any given time, making it easier to work from a single source document.

**Comment by Saijin-Naib** [comment]
I believe this to have been addressed adequately with [commits released in QGIS 3.8.0](http://changelog.qgis.org/en/qgis/version/3.8/#direct-access-sheets-from-xlsxods-files), though unfortunately, I don't know exactly which commits.

Thanks for your work on this, everyone!

( I don't see how I can close this issue, so perhaps someone else with the authority can close it now?)
