### ISSUE TITLE
convex hull by class

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29564]
Author Name: **Alain FERRATON** (@FERRATON)
Original Redmine Issue: [21749](https://issues.qgis.org/issues/21749)

Redmine category:processing/qgis

---
it would be nice to be able to create
convex hull by class (with a field)
as for concave hull (k-nearest neighbor)

**Comment by alexbruy** [comment]
Closing as this is already possible with Minimum bounding geometry algorithm.
