### ISSUE TITLE
Categorized style do not works with NULL value

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29563]
Author Name: **Roberto Marzocchi** (@rmarzocchi84)
Original Redmine Issue: [21748](https://issues.qgis.org/issues/21748)
Affected QGIS version: 3.4.6
Redmine category:symbology

---
Using categorized style the NULL value are not correctly classified as else. 

Using rule they are correctly classified.

---

- [Cattura.PNG](https://issues.qgis.org/attachments/download/14736/Cattura.PNG) (Roberto Marzocchi)

**Comment by alexbruy** [comment]
Works fine for me. Please test with latest master and if issue still present provide test datasets and instructions how to reproduce.

**Comment by alexbruy** [comment]
@rmarzocchi84 may I ask you to retest with master and latest 3.4.8?

**Comment by alexbruy** [comment]
Works fine in master/3.8
