### ISSUE TITLE
Attribute Table object cannot have arbitrary dimensions

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29577]
Author Name: **Brett Carlock** (@Saijin-Naib)
Original Redmine Issue: [21762](https://issues.qgis.org/issues/21762)
Affected QGIS version: 3.6.1
Redmine category:map_composer/printing

---
It is not possible to set arbitrary dimensions for the attribute table object directly.

However, this can almost be accomplished by setting the Attributes for the Main properties section of the Attribute table object.

However, these sizes can only be whole/integer mm values, preventing some layouts from being possible as they'd have to be fractional mm values to line up properly.

**Comment by nyalldawson** [comment]
This is by design -- tables are resized to fit their contents. You can tweak the column sizes and spacing via the "Attributes" section to change the overall size of the table.
