### ISSUE TITLE
Label Margin Clips Text

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29571]
Author Name: **Brett Carlock** (@Saijin-Naib)
Original Redmine Issue: [21756](https://issues.qgis.org/issues/21756)
Affected QGIS version: 3.6.1
Redmine category:map_composer/printing

---
The Label margin properties work by not only moving the text, but also clipping/obstructing the text potentially.

In a layout where there is ample room with my settings, the text is still slightly clipped.

We also can't set asymmetrical margins.

---

- [Annotation 2019-04-03 140608.png](https://issues.qgis.org/attachments/download/14733/Annotation%202019-04-03%20140608.png) (Brett Carlock)

**Comment by Pedro-Murteira** [comment]
Still valid on QGIS 3.22.4 and 3.24.0.

**Comment by alexbruy** [comment]
Tested with master (e8ff03b0fe) and as far as I can see there is no clipping/obstructing of the text if label item has enough room for it. However, if label item is small then text is clipped, but to me this looks like an expected behaviour.

**Comment by Saijin-Naib** [comment]
I don't think it should clip, but rather reflow.

**Comment by alexbruy** [comment]
As far as I can see it does reflow. But if label can not accomodate all the text it will be clipped.

Label is large enough to accomodate all text
![image](https://github.com/qgis/QGIS/assets/776954/97d4e994-6b18-42f9-a5cd-fa0df482e7ea)
Label is a bit smaller, reflowing text and clip 
![image](https://github.com/qgis/QGIS/assets/776954/e75bc49f-18eb-4290-ae91-cea62b11ee8c)
Label is even more smaller, reflowing text and clip
![image](https://github.com/qgis/QGIS/assets/776954/5342a9d1-b834-49be-add7-832bc5b44010)

**Comment by Saijin-Naib** [comment]
It looks like the reflow is improved of late. I guess this is better? I'm not sure what could be improved at this point.

**Comment by alexbruy** [comment]
In that case can we close this or you want to keep it open?
