### ISSUE TITLE
Zoom to feature(s)

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29582]
Author Name: **Brett Carlock** (@Saijin-Naib)
Original Redmine Issue: [21767](https://issues.qgis.org/issues/21767)

Redmine category:gui

---
I'd love to be able to zoom to the extent of a feature within a layer.

For instance, zoom to the extent of the roads that were paved within the larger road layer.

---

- [Screen Shot 2019-04-05 at 12.38.55 PM.png](https://issues.qgis.org/attachments/download/14743/Screen%20Shot%202019-04-05%20at%2012.38.55%20PM.png) (Nathan Perry)

**Comment by alexbruy** [comment]
Duplicates #29117.
