### ISSUE TITLE
map freezes after add via "Add PostGIS Layers"

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29586]
Author Name: **Navid Taheri** (Navid Taheri)
Original Redmine Issue: [21771](https://issues.qgis.org/issues/21771)
Affected QGIS version: 3.4.6
Redmine category:vectors

---
I add my ESRI shapefile layers via "Add PostGIS Layers" but when they add completely I tried zoom in and zoom out
on my add files but it seems they were locked our freeze I'd been able do any zoom after that when I did choose one layer in 
Layers Panel I could do zoom in/out normally.

---

- [freeze_zoom.png](https://issues.qgis.org/attachments/download/14737/freeze_zoom.png) (Navid Taheri)
- [pg_dump.zip](https://issues.qgis.org/attachments/download/14747/pg_dump.zip) (Navid Taheri)
- [Screenshot_20190407_113842.png](https://issues.qgis.org/attachments/download/14749/Screenshot_20190407_113842.png) (Giovanni Manghi)

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
