### ISSUE TITLE
rendering cycles forever when viewing raster at certain scales

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29591]
Author Name: **Tony Walters** (@tonywsea)
Original Redmine Issue: [21776](https://issues.qgis.org/issues/21776)
Affected QGIS version: 3.6.1
Redmine category:rasters

---
When viewing high resolution LiDAR rasters, the canvas renders continuously  and the LiDAR segments flash on and off at certain scales.
The problem exhibits when the raster has the opacity widget enabled on the label. Problem disappears when widget is removed.
Associated behaviour is that the UI hangs with the blue busy wheel for approx. a minute, then for 10 seconds will respond, then goes busy again and cycles forever. As well, the QGIS process size keeps increasing by 10MB blocks as reported by Task Manager. I eventually have to terminate the process because it will expand to more than 15GB in size.

---

- [Annotation 2019-04-05 062248.png](https://issues.qgis.org/attachments/download/14739/Annotation%202019-04-05%20062248.png) (Tony Walters)
- [Annotation 2019-04-05 062741.png](https://issues.qgis.org/attachments/download/14740/Annotation%202019-04-05%20062741.png) (Tony Walters)
- [Annotation 2019-04-05 063144.png](https://issues.qgis.org/attachments/download/14741/Annotation%202019-04-05%20063144.png) (Tony Walters)
- [Annotation 2019-04-05 062526.png](https://issues.qgis.org/attachments/download/14742/Annotation%202019-04-05%20062526.png) (Tony Walters)

**Comment by roya0045** [comment]
Still valid?

**Comment by tonywsea** [comment]
I haven’t seen this behaviour on recent QGIS releases.

Many thanks
Tony

Tony Walters
Consultant, SmartCommunity Consulting
(902)222-0646
tony@smartcommunity.ca<mailto:tony@smartcommunity.ca>
