### ISSUE TITLE
Error reading netCDF with multiple bands

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29598]
Author Name: **giu mas** (giu mas)
Original Redmine Issue: [21783](https://issues.qgis.org/issues/21783)
Affected QGIS version: 3.7(master)
Redmine category:rasters

---
I am creating some netCDF files with more than 1 band using GDAL (2.4.1).

The created files (an example file in attachment) works fine in QGIS 2.18 (and other GIS apps), but I get the following errors with QGIS 3+ (ltr, dev, etc.) on OSGEO4W64:

```
2019-04-07T16:16:16     CRITICAL    Invalid Layer : Raster layer Provider is not valid (provider: gdal, URI: C:/gdal.nc
2019-04-07T16:16:16     CRITICAL    Invalid Data Source : C:/gdal.nc is not a valid or recognized data source.

```

If I create a netCDF file with just 1 band (example attached), QGIS 3+ reads the file smoothly.

This issue may be related to #28740, #28799 and #29464 

---

- [gdal_3bands.nc](https://issues.qgis.org/attachments/download/14751/gdal_3bands.nc) (giu mas)
- [gdal_1band.nc](https://issues.qgis.org/attachments/download/14752/gdal_1band.nc) (giu mas)
- [qgis-bin_2019-04-09_00-22-03.png](https://issues.qgis.org/attachments/download/14762/qgis-bin_2019-04-09_00-22-03.png) (giu mas)
- [osgeolive12_qgis-dev.png](https://issues.qgis.org/attachments/download/14769/osgeolive12_qgis-dev.png) (giu mas)
- [osgeolive12_qgis_about.png](https://issues.qgis.org/attachments/download/14770/osgeolive12_qgis_about.png) (giu mas)
- [osgeo4w64_qgis_about.png](https://issues.qgis.org/attachments/download/14771/osgeo4w64_qgis_about.png) (giu mas)

---

Related issue(s): #29637 (relates)
Redmine related issue(s): [21822](https://issues.qgis.org/issues/21822)

---

**Comment by wonder-sk** [comment]
Tested with QGIS master on Ubuntu 18.04 - cannot replicate, everything seems to work as expected (tried to load gdal_3bands.nc).

**Comment by giumas** [comment]
The same issue is described here: https://gis.stackexchange.com/questions/312735/qgis-3-4-and-loading-raster-from-multiple-variable-netcdf-file

**Comment by giumas** [comment]
@wonder-sk You can easily replicate the issue by using OSGeo. It looks like that the issue does not show up with developer settings. Which version of GDAL are you using on your local machine?

**Comment by giumas** [comment]
Following the suggestion in https://github.com/qgis/QGIS/issues/29637, I have downloaded the latest nightly-built installer (https://qgis.org/downloads/weekly/QGIS-OSGeo4W-3.7.0-20-Setup-x86_64.exe). 

The error is still there. To replicate the issue, simply drag-and-drop the 'gdal_3bands.nc' test file:

![qgis-dev-bin-g7_2019-06-01_17-32-56](https://user-images.githubusercontent.com/2849257/58753849-a6805d00-8493-11e9-9c7f-7954a44a8d00.png)

**Comment by gioman** [comment]
> The error is still there. To replicate the issue, simply drag-and-drop the 'gdal_3bands.nc' test file:

just tried on Windows 7 with the latest nightly build installer > no issues.

**Comment by giumas** [comment]
This is a fully reproducible workflow to get the desribed error:

* Download the Evaluation Windows 10 virtual machine from Microsoft: https://developer.microsoft.com/en-us/windows/downloads/virtual-machines
* Open the VM with VMWare Workstation 15 player (I am running the VM on Windows 10, but it should not really matter)
* Download and install [QGIS 3.7.0dev](https://qgis.org/downloads/weekly/QGIS-OSGeo4W-3.7.0-20-Setup-x86_64.exe)
* Download [gdal_3bands.nc](https://issues.qgis.org/attachments/download/14751/gdal_3bands.nc)
* Drag and drop gdal_3bands.nc into QGIS 3.7.0

The expected output is:

```
2019-06-03T20:37:53     CRITICAL    Invalid Layer : Raster layer Provider is not valid (provider: gdal, URI: C:/Users/User/Downloads/gdal_3bands.nc (file: ..\..\..\src\core\raster\qgsrasterlayer.cpp row: 622function QgsRasterLayer::setDataProvider:)
2019-06-03T20:37:53     CRITICAL    Invalid Data Source : C:/Users/User/Downloads/gdal_3bands.nc is not a valid or recognized data source.
```

**Comment by gioman** [comment]
> This is a fully reproducible workflow to get the desribed error:
> 
>     * Download the Evaluation Windows 10 virtual machine from Microsoft: https://developer.microsoft.com/en-us/windows/downloads/virtual-machines
> 
>     * Open the VM with VMWare Workstation 15 player (I am running the VM on Windows 10, but it should not really matter)
> 
>     * Download and install [QGIS 3.7.0dev](https://qgis.org/downloads/weekly/QGIS-OSGeo4W-3.7.0-20-Setup-x86_64.exe)
> 
>     * Download [gdal_3bands.nc](https://issues.qgis.org/attachments/download/14751/gdal_3bands.nc)
> 
>     * Drag and drop gdal_3bands.nc into QGIS 3.7.0

@giumas yeah... I did exactly that... and it works as expected (I just use Virtualbox instead of VMware).

**Comment by rldhont** [comment]
@gioman, is the GDAL version 2.4.1 ?

Here is a python script, I have written to test the netcdf:
```py
import os.path
from qgis.core import QgsRasterLayer

# Change this line to set the NetCDF path
rpath = '/tmp/gdal_3bands.nc'

def test_netcdf(rpath):
    test = os.path.exists(rpath)
    if not test:
        print('The file does not exist')
        return test

    rlayer = QgsRasterLayer(rpath, "NetCDF")
    test = rlayer.isValid()
    if not test:
        print('The RASTER {} is not valid'.format(rlayer.name()))
        
        print('The RASTER {} data provider is {}'.format(rlayer.name(), rlayer.providerType()))
        
        rsublayers = rlayer.subLayers()
        
        test = (len(rsublayers) != 0)
        if not test:
            print('The RASTER {} has no sub-layers'.format(rlayer.name()))
            return test
        else:
            print('The RASTER {} has sub-layers'.format(rlayer.name()))
            print('The sub-layers are: {0}'.format(', '.join(rsublayers)))
    else:
        print('The RASTER {} is valid'.format(rlayer.name()))
        return test
        
    # to test a valid sub-layer
    rlayer = QgsRasterLayer('NETCDF:{0}::Band1'.format(rpath), 'NetCDF_Band1')
    test = rlayer.isValid()
    if not test:
        print('The RASTER {} is not valid'.format(rlayer.name()))
    else:
        print('The RASTER {} is valid'.format(rlayer.name()))
    return test

test_netcdf(rpath)
```
@giumas, can you test it ?

**Comment by gioman** [comment]
> @gioman, is the GDAL version 2.4.1 ?

@rldhont 


QGIS version | 3.7.0-Master | QGIS code revision | 27d687eac5
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.0 | Running against GEOS | 3.7.2-CAPI-1.11.0 b55d2125
PostgreSQL Client Version | 9.5.3 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018

**Comment by giumas** [comment]
@rldhont: this is the output:

```
exec(open('C:/Users/User/AppData/Local/Temp/tmpr0rvev_y.py'.encode('utf-8')).read())
The RASTER NetCDF is not valid
The RASTER NetCDF data provider is gdal
The RASTER NetCDF has sub-layers
The sub-layers are: NETCDF:"C:/data/gdal_3bands.nc":Band1, NETCDF:"C:/data/gdal_3bands.nc":Band2, NETCDF:"C:/data/gdal_3bands.nc":Band3
The RASTER NetCDF_Band1 is valid
```

@gioman: I am puzzled that you did not get the error by following the described steps!
Should I share the whole VM with you?

**Comment by cyrilleponcelet** [comment]
Hi everyones, 
Just a word to let you know that we encountered the same issue. With the latest QGIS Version (3.6.3-Noosa, and  3.4.8-Madeira LTS and even with the 3.7.0-master) retrieved from OSGEoW all netcdf dataset with multiple layers failed with the same kind of errors.
@giumas  is not alone having those troubles and this bug seems to be there for a long time.

**Comment by saberraz** [comment]
I am having the same issue. This could be an issue with netcdf driver version and not gdal. On Linux, where the file can be opened with no problem, netcdf is:
`netcdf library version 4.6.2 of Dec 12 2018 10:27:40 `

In Windows:
`netcdf library version 4.6.2 of Feb  5 2019 22:41:47`

Also, when I run gdalinfo on windows, I get this warning:

`Warning 1: Recode from UTF-8 to CP_ACP failed with the error: "Invalid argument".`

**Comment by rouault** [comment]
> Warning 1: Recode from UTF-8 to CP_ACP failed with the error: "Invalid argument".

There is an attempt to address this in https://github.com/OSGeo/gdal/pull/1568

**Comment by cyrilleponcelet** [comment]
I juste discover something, after reading the comment from @rouault .

- If I drag and drop @giumas  test file in the layer list it fails. 

- But if I'm using the Explorer view to access the file I can see the bands and I can display them. **It works**

**Comment by gioman** [comment]
> I juste discover something, after reading the comment from @rouault .
> 
>     * If I drag and drop @giumas  test file in the layer list it fails.
> 
>     * But if I'm using the Explorer view to access the file I can see the bands and I can display them. **It works**

@cyrilleponcelet good catch

**Comment by giumas** [comment]
I confirm @cyrilleponcelet discovery! I can open all the layers through the Browser panel:

![qgis-bin_2019-06-06_08-48-37](https://user-images.githubusercontent.com/2849257/59033975-0e3dfb80-8838-11e9-8f48-a6cfcfb84114.png)

**Comment by aaschwanden** [comment]
I used to have the same issue on several Ubuntu machines and QGIS < 3.10 and the "fix" by @cyrilleponcelet worked, but so far it never pop up on OS X.

Now, after a clean install of Catalina, I'm running into this issue, both when installing the [dmg](https://qgis.org/downloads/macos/qgis-macos-pr.dmg) from [QGIS](www.qgis.org) and compiling it with macports. Version 3.10 is working fine on a different machine with Yosemite and compiled with macports.

**Comment by BastienFR** [comment]
Adding my user case.  I'm experiencing the same bug with QGIS 3.10.2 and gdal 3.0.3 on windows 10.  @cyrilleponcelet trick seems to work, but only for the test raster.  Using NARR netCDF files (like this one: [ftp://ftp.cdc.noaa.gov/Datasets/NARR/Dailies/monolevel/snowc.2003.nc](ftp://ftp.cdc.noaa.gov/Datasets/NARR/Dailies/monolevel/snowc.2003.nc)) create an error message.  Also, looking at the file in QGIS explorer do not have the same icon, so Cyril's trick do not work.

 
![image](https://user-images.githubusercontent.com/10979480/74056442-0a0e4300-49b0-11ea-9c77-9394436fc14a.png)

My feeling is that the problem may not be with QGIS, as trying to load my netCDF file with R package `raster` made it crash and SAGA also fails reading it.  Could it be with GDAL?

note that Qgis wasn't install with the whole OSGEO4win. However, I tried it on an other machine with the whole suite and got the same bug.

**Comment by gioman** [comment]
> Also, looking at the file in QGIS explorer do not have the same icon, so Cyril's trick do not work.

The dataset shows as both raster and mesh dataset (this is the "strange" icon you see). If you expand the raster datset, you see the layers in it and they can be loaded ok.

![Screenshot_20200208_092111](https://user-images.githubusercontent.com/1951107/74082702-6a56c080-4a54-11ea-9d09-278756c204c8.png)

The problem is when add the .nc by drag and drop as noted here https://github.com/qgis/QGIS/issues/29598#issuecomment-499427066

**Comment by BastienFR** [comment]
@gioman, As you can see in the image I've uploaded, I don't get the expandable "raster" dataset for the snow file.  I get it only for test test file provided in this thread.  The fact that you see it and not me is a sign that it may be machine (?) specific.  So the problem is not limited to the drag and drop feature.

Adding more details, in the picture above, that is multiple netCDF files (not just the snow one) all from the same site from NOAA.  None of them allow for expanding in the QGIS browser.

**Comment by gioman** [comment]
> @gioman, As you can see in the image I've uploaded, I don't get the expandable "raster" dataset for the snow file. I get it only for test test file provided in this thread. The fact that you see it and not me is a sign that it may be machine (?) specific. So the problem is not limited to the drag and drop feature.
> 
> Adding more details, in the picture above, that is multiple netCDF files (not just the snow one) all from the same site from NOAA. None of them allow for expanding in the QGIS browser.

@BastienFR I tried several datasets from ftp://ftp.cdc.noaa.gov/Datasets/NARR/Dailies/monolevel/ and always got (windows, linux, QGIS 3.10.2) an expandable dataset in the QGIS browser

**Comment by Irene-GM** [comment]
I am experiencing the same situation on `Ubuntu 18.04`, with `QGIS 3.4.14 (Madeira)` compiled with `GDAL 3.0.2`. I used Python GDAL to generate a netcdf with 30 bands. At the time of opening it with QGIS I get a window with the following message:

![image](https://user-images.githubusercontent.com/8654047/76331229-2246ea00-62ef-11ea-9cf7-1d37c06f80ec.png)

And at the top of the map window I get the red error bar saying:

![image](https://user-images.githubusercontent.com/8654047/76331327-486c8a00-62ef-11ea-8605-fd748711bf28.png)

I thought my layer was corrupt, but I could open it and visualize data using `ncview`:

![image](https://user-images.githubusercontent.com/8654047/76331463-7baf1900-62ef-11ea-90f4-ae7ea0cc88ff.png)

I also tried the netcdf file from user @giumas getting the same error messages.
Any idea on how to solve this problem?
Thanks

**Comment by saberraz** [comment]
Have you tried to add it as a mesh instead of raster?

**Comment by gioman** [comment]
> Have you tried to add it as a mesh instead of raster?

@Irene-GM also attach sample data.

**Comment by Irene-GM** [comment]
@saberraz I am not really aware of the difference between adding it as a mesh or raster. Adding a file isn't just adding a file? :-) Can you please explain why using the QGIS browser opens it "as a mesh" and why doing drag and drop is a raster? Why dragging a netcdf might trigger this error but not another type of file?

Anyhow, I did use the QGIS browser to open the netcdf file and it works, I can visualize my netcdf layers and operate with them:

![image](https://user-images.githubusercontent.com/8654047/76419932-875b1800-63a1-11ea-8d16-29a30c42d364.png)

So, for me at this moment, this workaround works, but perhaps it would be good to have a more informative error message so users don't drag and drop, but use the QGIS browser :-)

Thanks for your help

**Comment by gioman** [comment]
>  I am not really aware of the difference between adding it as a mesh or raster. Adding a file isn't just adding a file?

@Irene-GM for this type of datasets? short answer: no ;)

![Screenshot_20200311_133641](https://user-images.githubusercontent.com/1951107/76422589-5a0c6b00-639d-11ea-937f-4dff2e091559.png)

try adding it as a Mesh, you'll enter a whole new world :)

**Comment by gioman** [comment]
> Anyhow, I did use the QGIS browser to open the netcdf file and it works, I can visualize my netcdf layers and operate with them:

@Irene-GM same as https://github.com/qgis/QGIS/issues/29598#issuecomment-499427066

**Comment by gioman** [comment]
Works all fine for me on QGIS 3.16.2 on Windows.
