### ISSUE TITLE
Copy/Paste fails from one layer to another when layer has NOT NULL constraints and transaction groups are enabled

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29603]
Author Name: **Andreas Neumann** (@andreasneumann)
Original Redmine Issue: [21788](https://issues.qgis.org/issues/21788)
Affected QGIS version: 3.7(master)
Redmine category:data_provider/postgis

---
In a QGIS project with the following properties:
- Automatically create transaction groups where possible is enabled
- Evaluate default values on provider side is enabled
- the layer, where features will be copy/pasted in should have some NOT NULL constraints

Steps to reproduce:
- copy and paste a compatible geometry type from another layer to a Postgis layer in the transaction group

--> you will receive an error message similar to the following:

```
2019-04-08T11:24:45     CRITICAL    Layer naturobjekt_flaeche : PostGIS error while adding features: ERROR: null value in column "referenz_nr" violates not-null constraint
DETAIL: Failing row contains (116, e16359db-c8a5-4125-90c7-1459a3ae3fda, null, null, null, null, null, null, null, null, null, null, null, null, null, 010600002008080000010000000103000000010000001C000000713D0AD76E79...)

```

The new feature is not pasted because of the NOT NULL constraint and the user has no chance to add the new attribute data. The new feature is rejected right away.

Here is the CREATE TABLE statement of the concerned table:

```
CREATE TABLE naturobjekte_kt.naturobjekt_flaeche
(
    t_id bigint NOT NULL DEFAULT nextval('naturobjekte_kt.t_ili2db_seq'::regclass),
    t_ili_tid uuid DEFAULT uuid_generate_v4(),
    referenz_nr character varying(20) COLLATE pg_catalog."default" NOT NULL,
    objekt_nr character varying(20) COLLATE pg_catalog."default" NOT NULL,
    objekt_beschreibung character varying(255) COLLATE pg_catalog."default" NOT NULL,
    zustaendigkeit character varying(255) COLLATE pg_catalog."default" NOT NULL,
    bedeutung character varying(255) COLLATE pg_catalog."default" NOT NULL,
    verbindlichkeit character varying(255) COLLATE pg_catalog."default" NOT NULL,
    festsetzungsdatum date NOT NULL,
    ortsbezeichnung character varying(255) COLLATE pg_catalog."default",
    erfassungsgrundlage character varying(255) COLLATE pg_catalog."default",
    erfassungsdatum date NOT NULL,
    dokument character varying(255) COLLATE pg_catalog."default",
    ursprung_objekt character varying(255) COLLATE pg_catalog."default",
    bemerkungen text COLLATE pg_catalog."default",
    geometrie geometry(MultiPolygon,2056),
    CONSTRAINT naturobjekt_flaeche_pkey PRIMARY KEY (t_id)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

```

**Comment by elpaso** [comment]
> Author Name: **Andreas Neumann** (@andreasneumann)
> 
> Expected behaviour would be:
> 
>     * the attribute form would open
> 
>     * In the form the user would see which values would have to be filled in
> 

@andreasneumann this is not clear to me: what if the user pasted more than one feature, do you expect that for each pasted feature the form will be opened?

I think this is a won't fix: unless we wanted to make an exception in case the user is pasting a single feature.

**Comment by andreasneumann** [comment]
Right - the above mentioned suggestions only work well for single features. However, for many workflows copying single/individual features is what people do.

Could we, if multiple features are copy/pasted open the attribute table in form mode, automatically select the new pasted features to make it obvious to the user what new features came in and need changes?

Just ignoring this problem basically means that users can't copy/paste features anymore with such a table setup. It would be a pity!

**Comment by elpaso** [comment]
:+1: for an exception for single features, I don't really know if this is more a feature or a bug, but I'll have a look.

**Comment by SebastienPeillet** [comment]
I took a look of this issue, relative to another bug. I'm not sure but it seems that this one has been resolve, isn't it ?

In master (not 3.10), #33688 resolve the issue

**Comment by elpaso** [comment]
@SebastienPeillet yes, looks like it's fixed, it's a pity it wasn't tagged from the other PR.
