### ISSUE TITLE
Crash when creating mapset

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29607]
Author Name: **Rafael Igino** (Rafael Igino)
Original Redmine Issue: [21792](https://issues.qgis.org/issues/21792)
Affected QGIS version: 3.4.6
Redmine category:grass

---
## User Feedback

EN: When I create a new mapset, qgis returns this error window.
PT: Quando vou criar um novo mapset, o qgis retorna essa janela de erro. 

## Report Details

*Crash ID*: 91a9cb64f10e82035e603c28b0be9355edc565be

*Stack Trace*
```
memset :
MITSetLastInputRecipient :
_C_specific_handler :
_chkstk :
RtlUnwindEx :
_C_specific_handler :
_chkstk :
RtlWalkFrameChain :
RtlRaiseStatus :
memset :
setjmpex :
G_fatal_error :
G_getenv :
read_datum_table :
GPJ_osr_to_grass :
GPJ_wkt_to_grass :
version :
version :
QMetaObject::activate :
QWizard::subTitleFormat :
QWizard::next :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

```

*QGIS Info*
QGIS Version: 3.4.6-Madeira
QGIS code revision: cc0e375a9f
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

---

- [mensagem_erro.PNG](https://issues.qgis.org/attachments/download/14759/mensagem_erro.PNG) (Rafael Igino)

**Comment by haubourg** [comment]
> Duplicate of #28148 ?

I think so yes
