### ISSUE TITLE
DXF-Export

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29608]
Author Name: **Adrian Beck** (Adrian Beck)
Original Redmine Issue: [21793](https://issues.qgis.org/issues/21793)
Affected QGIS version: 3.4.5
Redmine category:dxf_export

---
If i export any point-layer to DXF, the point are 3 to 5 times bigger in the DXF-Viewer then in QGIS. I tried to change the scale-dependent visibility but with no result.

Is this a common problem or am i doing something wrong?

**Comment by roya0045** [comment]
Can anyone eplicate? Are they generated baed on the symbol itself?

**Comment by nyalldawson** [comment]
Closing due to lack of feedback
