### ISSUE TITLE
Show Feature Count not updating properly

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29616]
Author Name: **Brett Carlock** (@Saijin-Naib)
Original Redmine Issue: [21801](https://issues.qgis.org/issues/21801)
Affected QGIS version: 3.6.1
Redmine category:map_legend

---
STR:
Have layer in geopackage with Number of Features X (1253, for example).

Replace layer in geopackage with another version, choose overwrite layer. New version has Number of Features 18071.

Toggle Show Feature Count On/Off. Count does not update to reflect new reality of the source data.

Correct object count is shown on Attribute Table, however.

**Comment by Pedro-Murteira** [comment]
@Saijin-Naib Hello, I've tested this issue on QGIS 3.22.4 and 3.24.0 and the feature count seems to update accordingly. Did you come across this issue more recently?

**Comment by Saijin-Naib** [comment]
Hmm... This is a still mostly an issue for me.

Project file/data:  
[TestPoints.zip](https://github.com/qgis/QGIS/files/8135391/TestPoints.zip)

STR/Screencast:  
https://youtu.be/pEmO3zeb6Yo

So, it refreshes the count eventually, but it still shows up wrong for a while. I'm also not sure what event caused it to refresh. Toggling the layers on/off? A timer? Random?

So, it still displays an improper count for a period of time, but eventually can refresh and show the right count.

**Comment by gioman** [comment]
> Please re-read the below carefully:

@Saijin-Naib 

I also think there is no bug here,
The layer has of course changed, as you replaced it, but QGIS project is not aware of it. This is why the (new) layer added after the export operation shows the correct count, but the "old" one still shows the previous feature count. This is totally expected to me. And if you hit the "refresh" button and switch off/on the feature count on the "old" layer, this now shows the correct count.  For me there is nothing to fix here.

**Comment by Saijin-Naib** [comment]
@gioman 

I disagree since my expectation is that the feature count should be kept current/correct. If not, I can't trust it, which means it should not be there 🤷

I understand what you're saying, especially since I am in fact changing the layer, but again, the expectation here is that the program will keep track of these things and ensure a consistent/correct state for things like this. It is not the user's job to do that in this case, I do not believe.

**Comment by gioman** [comment]
let's see if we can get the opinion of a QGIS core dev.

**Comment by Saijin-Naib** [comment]
Keeping alive so it doesn't get auto-closed.

**Comment by Saijin-Naib** [comment]
Still keeping open.

**Comment by Saijin-Naib** [comment]
Still think this is important

**Comment by Saijin-Naib** [comment]
I'd like to have this reopened @gioman

**Comment by ismailsunni** [comment]
Found the same issue with my own data. Hit refresh doesn't update the feature count. In my case, I updated the attribute table from a script (outside QGIS), but the count for each legend is not changing.
![image](https://user-images.githubusercontent.com/1421861/231326982-e741ec31-f534-4cf0-a29d-688add361845.png)

In my case, I expect that the count will be updated when I hit the refresh button.

**Comment by MarloesD** [comment]
Still an issue for me as well. 
I have 45 ellipses in "moeren" but it shows only als 23, At one time in the flow of work only 23 ellipses were in "moeren" but I changed the attribut so the filter shows all of them, but the count does not change. 

![image](https://github.com/qgis/QGIS/assets/159892382/d4a971ef-9610-4675-a691-c1932ec28638)
