### ISSUE TITLE
Layer Order panel: moving a layer scrolling  slows down when many layers present

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29614]
Author Name: **Garth Fletcher** (@fgfletcher)
Original Redmine Issue: [21799](https://issues.qgis.org/issues/21799)
Affected QGIS version: 3.6.1
Redmine category:gui

---
When a project contains many layers, e.g., 300+, and the Layer Order panel is being used to drag a layer to a different order, the scrolling starts fast but then slows down to a crawl.  

If the mouse is released leaving the layer in its new position, and then pressed to again select and drag the layer further, the scrolling speed resumes its normal fast rate and then gradually slows down once again.

So there is a work-around: a series of shorter drags, but each time there is a irritating delay waiting for the display to update.  It would be nice to have the fast scrolling continue throughout a long drag.

**Comment by Pedro-Murteira** [comment]
I can still replicate this behaviour on QGIS 3.16.14 and 3.22.1.

**Comment by fgfletcher** [comment]
When I originally reported the problem the scrolling quickly became painfully slow.  Several versions later the problem apparently was resolved and I haven't noticed it since then (currently testing 3.23.0 nightly release).
I considered the problem fixed, but perhaps you have found a specific case where it reappears.

**Comment by Pedro-Murteira** [comment]
@fgfletcher thank you for responding so quickly, it seems the problem was mine, after further testing, I arrived to the conclusion I didn't place the mouse correctly on the layer panel, and once I did it worked just as it is supposed to, therefore I think we can safely assume the bug is fixed.
