### ISSUE TITLE
Qgshandlebadlayers Browse button not working

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29619]
Author Name: **Alexis Roy-L** (Alexis Roy-L)
Original Redmine Issue: [21804](https://issues.qgis.org/issues/21804)
Affected QGIS version: 3.4.2
Redmine category:data_source_manager

---
Hi there, 

I don't get why but the browse button always stays greyed out even when I change my layer selection.

Tehcnically https://github.com/qgis/QGIS/blob/ca80fb6052d8e1108b9ae25b47cf1bbbfa971c55/src/app/qgshandlebadlayers.cpp#L172 should be executed but the browse button is not activated. Would it be possible that this function is actually not called.

I have noticed this in 3.4.x version but the relevant part of the code should not have changed, the PR that I made did not touch this part and I doubt Mr. Pasotti changed it with its latest PR.

So in theory the same behaviour should still be observed with master on windows, the previous updates that changed this part of the code date many years back. ( I truly broke the blame with windows changing my EOL...)

I'll update this if I get the chance to touch this with master on windows.

Thanks

**Comment by alexbruy** [comment]
Should be fixed in master. Please re-test.

**Comment by roya0045** [comment]
@alexbruy You can close this, its a local issue.
