### ISSUE TITLE
Feldrechner

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29625]
Author Name: **Stefan Zangemeister** (Stefan Zangemeister)
Original Redmine Issue: [21810](https://issues.qgis.org/issues/21810)

Redmine category:actions

---
Im Feldrechner kann unter dem Punkt Ausgabefeldtyp Dezimalzahl (real) die Ausgabefeldlänge und die Genauigkeit nicht geändert werden (Felder sind inaktiv).

Habe ein Bild angefügt aus dem ersichtlich wird, dass es in der früheren version funktioniert.

(Sorry kann kein Englisch)

MfG
Stefan

---

- [Dezimal Kopie.pdf](https://issues.qgis.org/attachments/download/14766/Dezimal%20Kopie.pdf) (Stefan Zangemeister)

**Comment by alexbruy** [comment]
Not reproducible with 3.10/3.12.
