### ISSUE TITLE
Copy & Paste of Symbol from one category to another broken

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29627]
Author Name: **Brett Carlock** (@Saijin-Naib)
Original Redmine Issue: [21812](https://issues.qgis.org/issues/21812)
Affected QGIS version: 3.6.1
Redmine category:symbology

---
STR:
Copy symbol of one category
Select another category on the same layer, in the same Layer Symbology tab, without closing/reopening Layer properties or navigating away at any point
Paste symbol to another catgegory

Expected results:
Symbol is pasted to the selected category

Actual results:
Symbol is not pasted to the selected category

Example:
Copy symbol for "C" (County Route) to "SH" (State 900 Highway)
Does not transfer symbology, must be re-built manually.

---

- [Annotation 2019-04-10 151920.png](https://issues.qgis.org/attachments/download/14776/Annotation%202019-04-10%20151920.png) (Brett Carlock)

**Comment by nyalldawson** [comment]
Fixed in master
