### ISSUE TITLE
source fields list does not update when layer is overwritten

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29629]
Author Name: **Brett Carlock** (@Saijin-Naib)
Original Redmine Issue: [21814](https://issues.qgis.org/issues/21814)
Affected QGIS version: 3.6.1
Redmine category:data_provider

---
STR:
Have a layer stored in a geopackage with N number of fields (5, for example).

Overwrite this same layer in the geopackage to a new version with 7 fields.

Actual behavior:
Right click layer, Source Fields still lists only the original 5 fields.

Entering/leaving edit mode does not expose those new fields.

Organize columns on the Attribute Table does not expose those new fields.

Expected behavior:
New fields are visible as soon as layer is overwritten.

**Comment by alexbruy** [comment]
Closing, as there is more general ticket #29617
