### ISSUE TITLE
Typo in Exporting Atlas Progress Window

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29628]
Author Name: **Julien Marchand** (Julien Marchand)
Original Redmine Issue: [21813](https://issues.qgis.org/issues/21813)
Affected QGIS version: 3.6.0
Redmine category:map_composer/printing

---
In QGIS 3.6.0, when we export an Atlas, the progress window which appears reads as *Expoering Maps* instead of the correct *Exporting Maps*. 

---

- [Screen Shot 2019-04-09 at 10.15.19 AM.png](https://issues.qgis.org/attachments/download/14767/Screen%20Shot%202019-04-09%20at%2010.15.19%20AM.png) (Julien Marchand)

**Comment by nyalldawson** [comment]
This is a translation issue, not a QGIS issue.
