### ISSUE TITLE
Cannot load multivariable netcdf files

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29637]
Author Name: **saverio vicario** (saverio vicario)
Original Redmine Issue: [21822](https://issues.qgis.org/issues/21822)
Affected QGIS version: 3.4.6
Redmine category:rasters

---
I upgraded QGis and I cannot load some netcdf anymore. All the file multivariable that I have cannot be read. 
The netcdf that I can load do not trigger the window were to choose the variable as before but directly load the single variable present in the files.
When I try to load a multivariable netcdf Qgis report on the GUI that source is not valid and on terminal I am getting only warnings relative to the naming of dimensions
"
Warning 1: dimension #2 (x) is not a Longitude/X dimension.
Warning 1: dimension #1 (y) is not a Latitude/Y dimension.
Warning 1: dimension #0 (Year) is not a Time or Vertical dimension.
" 
so no critical error.
When I am using gdalinfo is all fine.
when I am using gdal_translate to transform a single variable in geotiff is all fine and am getting a tiff file correctly read by qgis itself.

---

- [Testy.nc](https://issues.qgis.org/attachments/download/14779/Testy.nc) (saverio vicario)

---

Related issue(s): #29598 (relates)
Redmine related issue(s): [21783](https://issues.qgis.org/issues/21783)

---

**Comment by wonder-sk** [comment]
I am not sure if I understand your problem. I have tried to load your file (Testy.nc) by drag-n-drop to QGIS without issues (it opens popup asking which dataset(s) to open) and also by using browser dock widget (either as raster layer or as mesh layer). Could you please provide exact steps what steps you do? Also please make sure to test with the latest nightly builds (or at least qgis 3.6)

**Comment by milechin** [comment]
I had encountered this issue as well with QGIS 3.4.2 installed on CentOS 7.  If I delete everything in the QGIS configuration folder located in my home directory "~/.local/share/QGIS".  Then I run QGIS and try to load the multivariant netCDF file and it will throw the "Invalid Layer" error.  

Now if I go to the menu "Settings --> Options" and then just click "OK" for this window, by doing this action this adds a lot of more configuration settings to my "QGIS3.ini" file in my home directory: "~/.local/share/QGIS/QGIS3/profiles/default/QGIS".  Once this is done, I am actually able to open the multivariant NetCDF file with no errors.  This seems to suggest the default QGIS3.ini file may having some missing configuration settings that is prevent the netCDF file from loading properly.

**Comment by saberraz** [comment]
I am not able to reproduce that. Feel free to re-open if it repeats with a reproducible workflow.
