### ISSUE TITLE
Shortcut does not work when dock attribute table

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29633]
Author Name: **Maxime RIOU** (Maxime RIOU)
Original Redmine Issue: [21818](https://issues.qgis.org/issues/21818)
Affected QGIS version: 3.6.1
Redmine category:attribute_table

---
When attribute table is on the same windows as the main map (using dock attribute table), the shortcut ctrl+J is not working

**Comment by jgrocha** [comment]
I've was able to reproduce the problem, running in debug mode. I get on the console:
```
QAction::event: Ambiguous shortcut overload: Ctrl+J
```
So, it seems that more than one widget has this shortcut. I think both the map and the attribute table share this shortcut. Even ff we don't have the attribute table visible, we are able to use Crtl+J to jump to the feature.

### Workaround (not exactly!)

By going to Settings → Keyboard Shortcuts and DISABLE Ctrl+J we can get it work on the attribute table. So, by removing it from the map, the attribute table can handle it.

It is just a preliminary analysis, without looking into the code.

Tested with self compiled 3.7.0-Master on Ubuntu.

**Comment by jgrocha** [comment]
Looking at the code, I can confirm that we have the same shortcuts assigned to the main window and to the attribute table/window. When the attribute window is docked, both (the main window and the attribute window) have conflicting shortcuts. When they are separated, events goes to the selected one, and we don't have conflicts.

### Proposed solution

#### Shortcuts common to both, with the same action:

| Shortcut | 
| --- |
|Ctrl+C|
|Ctrl+V|
|Ctrl+X|
|Ctrl+J|
|Ctrl+A|
|Ctrl+Shift+A|

These can be solved by removing and recreating them on `QgsAttributeTableDialog::toggleDockMode`.

#### Shortcuts common to both, but with different actions:

| Shortcut | Attribute table | Main window | 
| --- | --- | --- |
|Ctrl+L | Delete field | Data source manager |
| Ctrl+P | Pan map | New print layout |
| Ctrl+S | Save edits | Save project |
|Ctrl+F | Select/filter features using form | Query Builder |

In this case, which shortcuts we want to keep? The Main window ones?

I'm preparing a PR disabling duplicated shortcuts on the attribute table only, preserving the Main window shortcuts.

Feedback is welcome.

**Comment by nyalldawson** [comment]
My 2c:
Ctrl +L : I don't think we need a shortcut to delete field at all -- it's not a common operation
Ctrl + S: I'd drop this shortcut from the attribute table, it's too dangerous as users may expect even with an attribute table opened and focused that it's still saving the project (I always did!)
