### ISSUE TITLE
value relation widget not saved as default style within geopackage

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29636]
Author Name: **Robin Rotsaert** (Robin Rotsaert)
Original Redmine Issue: [21821](https://issues.qgis.org/issues/21821)
Affected QGIS version: 3.6.0
Redmine category:forms

---
when using the value relation widget in the form of a layer within a geopackage and when saving these settings as default style within the geopackage, some of the settings (layer, key column, value column) are not loaded when reopening the layer directly from the geopackage. maybe there's no code for this within the geopackage-format but then it would be advisable to have this mentioned somewhere when trying to save styling for a layer where some fields have the value relation widget set up. 

(work around is to have it saved in a qgis-project, but this means a projectfile should always be added when sharing with others)

**Comment by Pedro-Murteira** [comment]
I'm not able to replicate this issue on QGIS 3.16.15 and 3.22.2.
