### ISSUE TITLE
gdal2tiles very slow compared to QGIS 2.18

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29634]
Author Name: **Karsten Tebling** (Karsten Tebling)
Original Redmine Issue: [21819](https://issues.qgis.org/issues/21819)
Affected QGIS version: 3.6.1
Redmine category:processing/gdal

---
I tried to generate tiles for zoom levels 10-11 for a roughly 2GB compressed DOP, with QGIS 3.6.1 it took about 581 minutes to finish. I also tried it with QGIS 2.18.28 and it only took around 8 seconds for the same DOP.

**Comment by alexbruy** [comment]
Closed for the lack of feedback
