### ISSUE TITLE
Double click on selected row(s) would zoom on the feature

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29632]
Author Name: **Maxime RIOU** (Maxime RIOU)
Original Redmine Issue: [21817](https://issues.qgis.org/issues/21817)

Redmine category:attribute_table

---
It would be nice to zoom on a feature when double clicking on the row number on the left of the attribute table. I know there is a shortcut (Ctrl+J) and the button on the top of the attribute table, but what about this extra shortcut?

**Comment by nyalldawson** [comment]
This is a won't fix. See the comments on the related pull request.
