### ISSUE TITLE
Crash on switching back and forth between junction and and dot-object tool

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29643]
Author Name: **Manuel du Bois** (Manuel du Bois)
Original Redmine Issue: [21828](https://issues.qgis.org/issues/21828)
Affected QGIS version: 3.6.1
Redmine category:unknown

---
QGis crashed and printed this report, when I was switching back and forth between junction and and dot-object tool.

*Crash ID*: 76a9c0a9b4b2bd92fae4372c60156ed873d1fdd5

*Stack Trace*
```
QWidget::show :
QgsVertexTool::highlightAdjacentVertex :
QTimer::timeout :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32Private::sendTimerEvent :
QEventDispatcherWin32::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

```

*QGIS Info*
QGIS Version: 3.6.1-Noosa
QGIS code revision: 2468226bc9
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

---

Related issue(s): #29320 (relates)
Redmine related issue(s): [21503](https://issues.qgis.org/issues/21503)

---

**Comment by Pedro-Murteira** [comment]
I can no longer reproduce a crash using QGIS 3.22.3.
