### ISSUE TITLE
Atlas coverage layer saved with absolute path when project is set to relative save paths

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29658]
Author Name: **Johannes Kroeger** (Johannes Kroeger)
Original Redmine Issue: [21843](https://issues.qgis.org/issues/21843)
Affected QGIS version: 3.7(master)
Redmine category:map_composer/printing

---
The setup:

- A QGIS project with a Print Layout.
- "Save paths" in the project's settings is set to "relative"

The qgz file includes the following snippet with an absolute path to a layer:

@<Atlas sortFeatures="0" enabled="1" hideCoverage="0" coverageLayer="1555062671232_cdc7c829_6e4d_4938_a006_b8882c376abf" coverageLayerSource="/tmp/some/path/1555062671232.geojson" coverageLayerProvider="ogr" filterFeatures="0" coverageLayerName="1555062671232" filenamePattern="'output_'||lpad(@atlas_featurenumber, 4, 0)" pageNameExpression=""/>@

This is a privacy issue and should not be happening.

Atlas coverage layer paths should be save relative if the project is set up that way.

**Comment by gioman** [comment]
Cannot replicate on 3.22.4
