### ISSUE TITLE
QGIS crashes on exit

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29656]
Author Name: **Karsten Tebling** (Karsten Tebling)
Original Redmine Issue: [21841](https://issues.qgis.org/issues/21841)
Affected QGIS version: 3.6.1
Redmine category:unknown

---
## User Feedback

Hello, QGIS crashes from time to time when I try to exit it via the Windows Exit Button.

I didn't find unclosed tickets with the same Stack Trace, so I hope this is not a duplicate.

## Report Details

*Crash ID*: e48fe61b279b81259140aad9ea98e4c2b936f8e5

*Stack Trace*
```
QgsTaskManager::cancelAll :
QgsTaskManager::~QgsTaskManager :
QgsTaskManager::~QgsTaskManager :
QgsValidityCheckResult::QgsValidityCheckResult :
QgsApplication::~QgsApplication :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

```

*QGIS Info*
QGIS Version: 3.6.1-Noosa
QGIS code revision: 2468226bc9
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
