### ISSUE TITLE
 Copy/Paste fails in Postgis layer null value in column "gid" violates not-null constraint

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29651]
Author Name: **CATER Normandie** (CATER Normandie)
Original Redmine Issue: [21836](https://issues.qgis.org/issues/21836)
Affected QGIS version: 3.4.5
Redmine category:data_provider/postgis

---
When copy/past features from Shapefile layer to Postgis layer, an error occure "null value in column "gid" violates not-null constraint". Creating new feature work as expected. 

Work well in QGIS 3.2 with same data.

Error occure with or without transaction group.

Don't know if something related with bug report #29603

**Comment by gioman** [comment]
> QGIS 3.6 fix it, can you bring the patch to the LTR ?

closing as should be fixed since 3.6.
