### ISSUE TITLE
PostGIS rasters do not show in the Browser and in the "add PostGIS layer" dialog in the datasource manager

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29662]
Author Name: **Giovanni Manghi** (@gioman)
Original Redmine Issue: [21847](https://issues.qgis.org/issues/21847)
Affected QGIS version: 3.6.1
Redmine category:browser

---
They only show in DB Manager.

Apparently this is a long standing issue (tried on 2.14, 2.18 and 3.4/6).

**Comment by alexbruy** [comment]
Already fixed in master. Please reopen if necessary.
