### ISSUE TITLE
QGIS crashed after abort a plugin process

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29665]
Author Name: **Torsten Hase** (Torsten Hase)
Original Redmine Issue: [21850](https://issues.qgis.org/issues/21850)
Affected QGIS version: 3.6.1
Redmine category:gui

---
## User Feedback

I was using a plugin to download some inspire data. As I aborted the process of the pluging qgis crashed.

## Report Details

*Crash ID*: f411d995c635b1ea21c06c10d9ba0978ed9832fe

*Stack Trace*
```
QEventLoop::exit :
QDialog::setVisible :
QDialog::done :
QMetaObject::activate :
QDialogButtonBox::~QDialogButtonBox :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

```

*QGIS Info*
QGIS Version: 3.6.1-Noosa
QGIS code revision: 2468226bc9
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
