### ISSUE TITLE
Crash while closing QGIS

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29661]
Author Name: **Marc Struelens** (Marc Struelens)
Original Redmine Issue: [21846](https://issues.qgis.org/issues/21846)
Affected QGIS version: 3.4.6
Redmine category:unknown

---
## User Feedback

I was closing the application after saving different layers in a geopackage (through toolbox processing > database). It also looks that I last internet connection while closing QGIS (not because of closing QGis).

## Report Details

*Crash ID*: b6e374582c08a74f0b3cd4a4b10d3e831eca662a

*Stack Trace*
```
QgsSnapIndicator::~QgsSnapIndicator :
QgsMapCanvas::~QgsMapCanvas :
QgsVectorLayerProperties::`default constructor closure' :
CPLStringList::operator char const * const * :
main :
wcspbrk :
RtlFreeAnsiString :
wcspbrk :
LdrGetDllHandleEx :
LdrGetProcedureAddressEx :
LdrGetProcedureAddressEx :

```

*QGIS Info*
QGIS Version: 3.4.6-Madeira
QGIS code revision: cc0e375a9f
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

---

- [Knipsel.PNG](https://issues.qgis.org/attachments/download/14797/Knipsel.PNG) (Marc Struelens)

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
