### ISSUE TITLE
Bad Allocation - Report Composer

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29670]
Author Name: **Tomás Carvalho** (Tomás Carvalho)
Original Redmine Issue: [21855](https://issues.qgis.org/issues/21855)
Affected QGIS version: 3.6.0
Redmine category:map_composer/printing

---
I'm trying to export a Report document in PDF and some times it works well.
But some times it causes 'Bad Allocation' and the final PDF archive get much more size and the QGIS stops working. 
I have already try to limit the number of features and pages to show but still doesn't work.
What could be? 
Please send me any kind of resolution to this problem.

---

- [archive_size_bad_alocation.PNG](https://issues.qgis.org/attachments/download/14794/archive_size_bad_alocation.PNG) (Tomás Carvalho)
- [report_bad_alocation.PNG](https://issues.qgis.org/attachments/download/14795/report_bad_alocation.PNG) (Tomás Carvalho)
- [QGIS_Project.zip](https://issues.qgis.org/attachments/download/14799/QGIS_Project.zip) (Tomás Carvalho)
- [QGIS_Data.zip](https://issues.qgis.org/attachments/download/14800/QGIS_Data.zip) (Tomás Carvalho)
- [project.qgz](https://issues.qgis.org/attachments/download/14802/project.qgz) (Tomás Carvalho)
- [Data_bugReport.zip](https://issues.qgis.org/attachments/download/14803/Data_bugReport.zip) (Tomás Carvalho)
- [Data_bugReport2.zip](https://issues.qgis.org/attachments/download/14804/Data_bugReport2.zip) (Tomás Carvalho)
- [Data_bugReport3.zip](https://issues.qgis.org/attachments/download/14805/Data_bugReport3.zip) (Tomás Carvalho)
- [metadata_bugReport.txt](https://issues.qgis.org/attachments/download/14806/metadata_bugReport.txt) (Tomás Carvalho)
- [Screenshot_20190416_215303.png](https://issues.qgis.org/attachments/download/14807/Screenshot_20190416_215303.png) (Giovanni Manghi)

**Comment by nyalldawson** [comment]
Closing due to lack of feedback
