### ISSUE TITLE
"File/folder Input" in processing won't separate input files into distinct rows in batch mode

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29674]
Author Name: **Grzegorz Sieńko** (Grzegorz Sieńko)
Original Redmine Issue: [21859](https://issues.qgis.org/issues/21859)
Affected QGIS version: 3.4.6
Redmine category:processing/gui
Assignee: Alexander Bruy

---
When creating the model in processing with file input, desire behavior in batch mode is to select multiple files where will by created many rows in model input.

Windows 10.
On 3.4.6 - I can select multiple files, but everything is in one row, separated by ;
On 3.6.1 - I can only select one file.
On 3.7 dev - I can select only one file.

**Comment by alexbruy** [comment]
Reopened, as proposed fix was reverted.

**Comment by alexbruy** [comment]
Fixed in master
