### ISSUE TITLE
Zoom to selection not always working

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29689]
Author Name: **Adam Lemire** (Adam Lemire)
Original Redmine Issue: [21874](https://issues.qgis.org/issues/21874)
Affected QGIS version: 3.6.1
Redmine category:map_tools

---
"Zoom to selection" is not always working.
Sometimes, the map doesn't move at all and the selection is still out of the view, or in a corner of the view.
After it happens, I can't pan the map until I select another element and zoom to the new selection.

Other times, it pan to the selection, without zooming in.

(not sure if I selected the right category)

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
