### ISSUE TITLE
can't change value in vertex editor if "locale" settings use commas as decimal separator

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29682]
Author Name: **Giovanni Manghi** (@gioman)
Original Redmine Issue: [21867](https://issues.qgis.org/issues/21867)
Affected QGIS version: 3.6.1
Redmine category:digitising

---
if you have a locale that uses commas as decimal separator then manually editing values in the vertex editor does not work. Workaround: set QGIS locale to English.

---

Related issue(s): #29811 (duplicates)
Redmine related issue(s): [21996](https://issues.qgis.org/issues/21996)

---

**Comment by MiiLeino** [comment]
This issue is also present in 3.4.7

**Comment by Xeenych** [comment]
This is also present in 3.10.0

**Comment by SrNetoChan** [comment]
@elpaso I am still seeing this problem both in QGIS 3.10 and master. Can we reopen this please?

**Comment by SrNetoChan** [comment]
![Peek 2020-09-17 22-21](https://user-images.githubusercontent.com/3607161/93530668-dd52de80-f935-11ea-95f8-6534834b8fae.gif)

**Comment by elpaso** [comment]
@SrNetoChan @gioman I cannot reproduce on current master, I can change and set values in vertex editor correctly using `,` as a decimal separator.

My locale is IT_it as:

![immagine](https://user-images.githubusercontent.com/142164/105033713-c265b780-5a58-11eb-9a95-5eeb4c581dfb.png)

**Comment by gioman** [comment]
> I cannot reproduce on current master, I can change and set values in vertex editor correctly using `,` as a decimal separator.

@elpaso in what language is your OS?

**Comment by elpaso** [comment]
> > I cannot reproduce on current master, I can change and set values in vertex editor correctly using `,` as a decimal separator.
> 
> @elpaso in what language is your OS?

Does it matter? Italian BTW.

**Comment by gioman** [comment]
> Does it matter?

@elpaso I'm checking, I don't want to overlook anything.

**Comment by SrNetoChan** [comment]
What decimal separator is normally used in it?

**Comment by gioman** [comment]
> What decimal separator is normally used in it?

@SrNetoChan in the vertex editor panel? the dot.

**Comment by elpaso** [comment]
> What decimal separator is normally used in it?

There is no "normality" here, you are supposed to use the decimal separator that is defined by your current locale (overridden or inherited from the os).

**Comment by SrNetoChan** [comment]
Sorry, I meant in italy. Let me recheck this with master.

**Comment by elpaso** [comment]
@SrNetoChan `,` (or the test would have been pointless).

**Comment by gioman** [comment]
> Does it matter? Italian BTW.

@elpaso works fine on master with PT_PT locale set at QGIS level on a system with the OS in EN, but let me check on a system with the OS in pt_pt

**Comment by SrNetoChan** [comment]
Does your data as Z values? I was testing on QGIS 3.10.14 and I can only replicate the problem when I try to edit the Z values
X and Y work just fine.

**Comment by SrNetoChan** [comment]
@elpaso and @gioman are you trying to edit the Z values? those are the ones problematic to me in QGIS 3.10.14 .

**Comment by gioman** [comment]
> Does it matter? Italian BTW.

@elpaso works fine on master with PT_PT locale set at QGIS level on a system with the OS in EN, but let me check on a system with the OS in pt_pt

> @elpaso and @gioman are you trying to edit the Z values? those are the ones problematic to me in QGIS 3.10.14 .

@SrNetoChan checking...

**Comment by gioman** [comment]
> @elpaso and @gioman are you trying to edit the Z values? those are the ones problematic to me in QGIS 3.10.14 .

@SrNetoChan works fine with pt_pt as QGIS locale on QGIS master and OS in EN. I'm also checking on a OS in pt_pt.

**Comment by SrNetoChan** [comment]
Ok, let me try master in here.

**Comment by elpaso** [comment]
> @elpaso and @gioman are you trying to edit the Z values? those are the ones problematic to me in QGIS 3.10.14 .

I have an `r` and no `z` , `r` cols are all empty.

Do you have a test project and data to reproduce the `z` issue?

**Comment by gioman** [comment]
> Do you have a test project and data to reproduce the `z` issue?

@elpaso testing ongoing... ;)

**Comment by SrNetoChan** [comment]
> > @elpaso and @gioman are you trying to edit the Z values? those are the ones problematic to me in QGIS 3.10.14 .
> 
> I have an `r` and no `z` , `r` cols are all empty.
> 
> Do you have a test project and data to reproduce the `z` issue?

give one sec.

**Comment by SrNetoChan** [comment]
[Temp.zip](https://github.com/qgis/QGIS/files/5836179/Temp.zip)

**Comment by SrNetoChan** [comment]
I don't think it's only the OS Language, but the locale settings. That is, if the OS Language is English, but the regional settings (time, currency, and so on) are in PT_pt, I get this problem.

**Comment by gioman** [comment]
> That is, if the OS Language is English, but the regional settings (time, currency, and so on) are in PT_pt,

@SrNetoChan in QGIS or at a OS level?

**Comment by SrNetoChan** [comment]
OS

**Comment by elpaso** [comment]
@gioman just to be clear: OS settings are just the default, when you check "[x] override ..." QGIS is in command.

**Comment by SrNetoChan** [comment]
OS

**Comment by gioman** [comment]
> [Temp.zip](https://github.com/qgis/QGIS/files/5836179/Temp.zip)

@SrNetoChan @elpaso all ok here on QGIS master on OS in pt_pt with or without the QGIS locale set to pt_pt.

**Comment by elpaso** [comment]
@SrNetoChan confirmed with `Z`

**Comment by gioman** [comment]
> confirmed with `Z`

@elpaso weird, not here.

**Comment by elpaso** [comment]
@gioman fixed, PR is on the way.
