### ISSUE TITLE
add support for "triangles" PostGIS geometry type

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29690]
Author Name: **Darafei Praliaskouski** (@Komzpa)
Original Redmine Issue: [21875](https://issues.qgis.org/issues/21875)

Redmine category:data_provider/postgis

---
I have a table of TRIANGLE's in PostGIS. QGIS shows it as Polygon layer, and when I click using Idenify tool on triangles, they show up, but they are not rendered by main map as polygons.

---

- [triangles.sqld.bz2](https://issues.qgis.org/attachments/download/14818/triangles.sqld.bz2) (Darafei Praliaskouski)
- [2019-04-18 151330.jpg](https://issues.qgis.org/attachments/download/14819/2019-04-18%20151330.jpg) (Darafei Praliaskouski)
- [Screenshot_20190418_131631.png](https://issues.qgis.org/attachments/download/14820/Screenshot_20190418_131631.png) (Giovanni Manghi)

**Comment by stev-0** [comment]
This should be closed as it's a fixed postgis bug
