### ISSUE TITLE
Crashes when loading qml style for point layer

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29691]
Author Name: **Ghassen Aouinti** (Ghassen Aouinti)
Original Redmine Issue: [21876](https://issues.qgis.org/issues/21876)
Affected QGIS version: 3.6.1
Redmine category:symbology

---
When loading a qml style file for a point layer, QGIS crashes :
This qml file was exported from a point layer which can be uploaded to it successfully.
but with this layer is Clipped to a small area and i load the same QML to the new one, QGIS crashes !

---

- [QGIS_error](https://issues.qgis.org/attachments/download/14816/QGIS_error) (Ghassen Aouinti)
- [Data_test.zip](https://issues.qgis.org/attachments/download/14830/Data_test.zip) (Ghassen Aouinti)

**Comment by alexbruy** [comment]
Seems already fixed in master.
