### ISSUE TITLE
Dragging layers too high in layers panel will reload them, potentially losing data

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29694]
Author Name: **Johannes Kroeger** (Johannes Kroeger)
Original Redmine Issue: [21879](https://issues.qgis.org/issues/21879)
Affected QGIS version: 3.7(master)
Redmine category:gui

---
Dragging layers too high in layers panel will reload(?) them, potentially losing data

1. Have at least two layers loaded and visible in the layers panel.

2. In the layers panel drag the lower layer up so high above the other layer, into the icons pane just above, so that the "insertion marker line" just disappeared and is not visible anymore.

3. Release the layer.

The layer will be reloaded. You will lose all its settings. If the layer was a memory layer, you will lose its contents!

See the attached video for an example.

---

- [layer killer.mkv](https://issues.qgis.org/attachments/download/14817/layer%20killer.mkv) (Johannes Kroeger)

**Comment by alexbruy** [comment]
Please test with latest master.

**Comment by gioman** [comment]
Closing for lack of further feedback.
