### ISSUE TITLE
Concave hull (alpha shapes) should allow creating separate hulls for each value of a user-selected field

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29693]
Author Name: **Johannes Kroeger** (Johannes Kroeger)
Original Redmine Issue: [21878](https://issues.qgis.org/issues/21878)

Redmine category:processing/qgis

---
@Concave hull (alpha shapes)@ and @Concave hull (k-nearest neighbor)@ should allow creating separate hulls for each value of a user-selected field.

The @Minimum bounding geometry@ supports this (as do many others).

See also #29564 for the same request for the @Convex hull@ tool.

**Comment by alexbruy** [comment]
Duplicates #29564
