### ISSUE TITLE
Save Layer As targeting PostGIS and scratch layers

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29704]
Author Name: **Thomas Koski** (Thomas Koski)
Original Redmine Issue: [21889](https://issues.qgis.org/issues/21889)

Redmine category:unknown

---
In the export menu there are many options for Save Layer As, but not included are a scratch layer or to a PostGIS database.  Both of these would be helpful, and their omission is puzzling.

**Comment by alexbruy** [comment]
Duplicated by #34206.
