### ISSUE TITLE
Network error on connecting to ArcGisMapServer

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29703]
Author Name: **Thomas Koski** (Thomas Koski)
Original Redmine Issue: [21888](https://issues.qgis.org/issues/21888)
Affected QGIS version: 3.4.4
Redmine category:web_services_clients/arcgis
Assignee: Sandro Mani

---
Since ESRI updated to TLS 1.2 connecting to their MapServer, e.g http://server.arcgisonline.com/arcgis/rest/services
works, but after several hours I lose connection with a "Network error: Network access is disabled." error.

Stopping and restarting QGIS reestablishes the connection for several hours.

**Comment by wonder-sk** [comment]
I can't replicate. If I use the given URL, I get no layers. I assume one needs to add username/password to log in and see something?

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary,
