### ISSUE TITLE
Crash when calling QgsRasterHistogram.histogramVector

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29700]
Author Name: **Anita Graser** (@anitagraser)
Original Redmine Issue: [21885](https://issues.qgis.org/issues/21885)
Affected QGIS version: 3.7(master)
Redmine category:rasters

---
## User Feedback

To reproduce, load a raster layer and run:

l = iface.activeLayer()
p = l.dataProvider()
p.initHistogram(QgsRasterHistogram(),1,100)
h=p.histogram(1)
h.histogramVector

## Report Details

*Crash ID*: 83fbcfe1e268fc8a14c5f21189006505dfb05fea

*Stack Trace*
```
PyObject_GenericGetAttrWithDict :
PyObject_GetAttr :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyImport_Import :
PyImport_Import :
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_sip :
PyInit_Qsci :
QWidget::event :
QFrame::event :
QAbstractScrollArea::event :
PyInit_Qsci :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processKeyEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

```

*QGIS Info*
QGIS Version: 3.6.1-Noosa
QGIS code revision: 2468226bc9
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by elpaso** [comment]
@anitagraser I think that you should keep a reference to `QgsRasterHistogram`
```python
rh = QgsRasterHistogram()
p.initHistogram(rh, 1, 100)
```
does it still crash?

**Comment by anitagraser** [comment]
Seems like even the original code doesn't crash in 3.4.6 or master anymore.

**Comment by anitagraser** [comment]
Unfortunately, that doesn't seem to help. (Tested in 3.4.8-Madeira) 

![histogram_crash](https://user-images.githubusercontent.com/590385/58632177-2ae0ad80-82e5-11e9-9f72-80ea3bf319dc.gif)

**Comment by elpaso** [comment]
@anitagraser I cannot reproduce on master, I'm going to test 3.4 now

**Comment by elpaso** [comment]
@anitagraser I *may* have found the issue.

**Comment by anitagraser** [comment]
There's still the same crash as shown in the GIF above in QGIS code revision: 4662bb9298

**Comment by elpaso** [comment]
@anitagraser thanks for checking, the a.m. revision does not contain the patch: I'm working on the forward porting to master now and adding a test for it.
