### ISSUE TITLE
Selected join isn't visually selected

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29708]
Author Name: **Jonathan Moules** (Jonathan Moules)
Original Redmine Issue: [21893](https://issues.qgis.org/issues/21893)
Affected QGIS version: 3.4.3
Redmine category:gui
Assignee: Matthias Kuhn

---
If I select a Join on the Joins page of Layer Properties, it doesn't get highlighted in any way. This makes it hard to know which join you're about to edit/remove.

**Comment by alexbruy** [comment]
Already fixed in 3.4/3.8 and master
