### ISSUE TITLE
Pip under Python 3.7 in QGIS 3.6.2 doesn't work

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29713]
Author Name: **Michal Hala** (Michal Hala)
Original Redmine Issue: [21898](https://issues.qgis.org/issues/21898)
Affected QGIS version: 3.6.2
Redmine category:pyqgis_console

---
Pip tool under Python 3.7 in QGIS 3.6.2 doesn't work. This continues in all QGIS versions since 3.0. It complicates my life very much, because third party modules are very important and absolutely must have for some types of data analysis (e. g. scikit-learn, pandas, statsmodels...). I have to export data to external Python and make analysis there. This is pretty fine mess.

**Comment by alexbruy** [comment]
Please test with latest master/3.10.
