### ISSUE TITLE
Spatialite isn't working correctly on macOS

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29714]
Author Name: **MRick -** (MRick -)
Original Redmine Issue: [21899](https://issues.qgis.org/issues/21899)
Affected QGIS version: 3.6.1
Redmine category:data_provider/spatialite

---
In QGIS 3, I have to use the Cadastre plugin.
https://github.com/3liz/QgisCadastrePlugin

When installing, it begins with a Python error. I could repaire it by removing all the accented letters in the metadata.txt file.

But when it comes to create a new Spatialite database, it fails.
I had exactly the same problem with the version 2.18 which with a buggy spatiality version. I could get it working by installing an older SQLite version SQLite3_Framework-3.8.7.3-1.dmg from http://www.kyngchaos.com/files/software/frameworks/SQLite3_Framework-3.8.7.3-1.dmg
But it doesn't work with version 3…
This plugin works out-of-the-box in both Windows and Linux versions and on QGIS 2.16 for Mac or with version 2.18 when installing SQLite3_Framework-3.8.7.3-1.dmg

It seems there is something broken in SQLite on the Mac version in all the recent versions from 2.18 and above.

---

- [Capture d’écran 2019-04-27 à 14.39.11.png](https://issues.qgis.org/attachments/download/14854/Capture%20d%E2%80%99%C3%A9cran%202019-04-27%20%C3%A0%2014.39.11.png) (MRick -)
- [Capture d’écran 2019-04-27 à 14.51.47.png](https://issues.qgis.org/attachments/download/14855/Capture%20d%E2%80%99%C3%A9cran%202019-04-27%20%C3%A0%2014.51.47.png) (MRick -)
- [Capture d’écran 2019-05-04 à 13.44.36.png](https://issues.qgis.org/attachments/download/14888/Capture%20d%E2%80%99%C3%A9cran%202019-05-04%20%C3%A0%2013.44.36.png) (MRick -)

**Comment by alexbruy** [comment]
Still true with 3.10/master?

**Comment by gioman** [comment]
> When I run this command in the Python console, I get an error.

No error on QGIS 3.14.0 on macOS Catalina, assuming this is fixed, please reopen if necessary.
