### ISSUE TITLE
Attribute Form keeping settings after column deletion

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29711]
Author Name: **Jonathan Moules** (Jonathan Moules)
Original Redmine Issue: [21896](https://issues.qgis.org/issues/21896)
Affected QGIS version: 3.4.3
Redmine category:attribute_table

---
To replicate (GeoPackage):

1) Create a field (MY_FIELD in this) of type whole integer:
2) For Layer Properties -> Attributes Form set Default value to 0; Apply on Update to MY_FIELD.
3) Delete the field (MY_FIELD)
4) Create a new field with the same name (MY_FIELD)
5) Look in Layer Properties -> Attributes Form. it will have the same setting as was set for the previous field of the same name (there should be no default on the new layer).
Worse - the values in the new field will NOT have used this default - they'll all (correctly) be NULL, not 0.

**Comment by alexbruy** [comment]
Duplicates #26350.
