### ISSUE TITLE
Suggest update only if is available for the current OS

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29719]
Author Name: **Jorge Useche** (@juusechec)
Original Redmine Issue: [21904](https://issues.qgis.org/issues/21904)

Redmine category:mac_os_specific
Assignee: Denis Rouzaud

---
I'm using QGIS Desktop in macOS, the software suggest me to update to a newest version, but It is not available for my platform.

---

- [Screen Shot 2019-04-22 at 19.11.52.png](https://issues.qgis.org/attachments/download/14825/Screen%20Shot%202019-04-22%20at%2019.11.52.png) (Jorge Useche)
- [Screen Shot 2019-04-22 at 19.17.59.png](https://issues.qgis.org/attachments/download/14826/Screen%20Shot%202019-04-22%20at%2019.17.59.png) (Jorge Useche)

**Comment by alexbruy** [comment]
Duplicates https://github.com/qgis/QGIS/issues/29216
