### ISSUE TITLE
Default values and expression calculator not working together

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29710]
Author Name: **Jonathan Moules** (Jonathan Moules)
Original Redmine Issue: [21895](https://issues.qgis.org/issues/21895)
Affected QGIS version: 3.4.3
Redmine category:vectors

---
While trying to work around #29707 I encountered the following.

To replicate (in a GeoPackage - probably not format specific):
1) Create a new field of type Integer called whatever (_MY_FIELD here)
2) Use the Layer Properties -> Attributes Form to set a default value of 0 on _MY_FIELD, and tick the "Apply default on update" (this is the bug!)
3) Now, use expression calculator to UPDATE _MY_FIELD with any numerical value (fid will do).

Result = _MY_FIELD only has values of "0".

If you uncheck the "Apply default on update" then the update of the field will work as expected.

**Comment by Pedro-Murteira** [comment]
This issue is still valid on both QGIS 3.22.4 and 3.24.0.

**Comment by alexbruy** [comment]
Not sure I understand what is wrong in this scenario. Updating fields with field calulcator count as feature update and in turn should trigger default value application.
