### ISSUE TITLE
attribute header names are not saved

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29728]
Author Name: **rawan gis** (rawan gis)
Original Redmine Issue: [21913](https://issues.qgis.org/issues/21913)
Affected QGIS version: 3.6.2
Redmine category:map_composer/printing

---
Hello
when adding attribute table to the layout,the header name for fields can be changed but it  will not be saved, so if I closed QGIS and open it again the header name will be the original name.
regards 

---

- [headercustumized.pdf](https://issues.qgis.org/attachments/download/14831/headercustumized.pdf) (rawan gis)
- [headernotsaved.pdf](https://issues.qgis.org/attachments/download/14832/headernotsaved.pdf) (rawan gis)
- [attributesheader.jpg](https://issues.qgis.org/attachments/download/14833/attributesheader.jpg) (rawan gis)
- [atlas2.rar](https://issues.qgis.org/attachments/download/14841/atlas2.rar) (rawan gis)

**Comment by nyalldawson** [comment]
This has been fixed
