### ISSUE TITLE
Invarid value for Custom Variables in "Read Me.rtf" in Mac OSX 3.4.6 dmg

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29726]
Author Name: **Shizuo Harada** (Shizuo Harada)
Original Redmine Issue: [21911](https://issues.qgis.org/issues/21911)
Affected QGIS version: 3.4.6
Redmine category:mac_os_specific

---
In the "Read Me.rtf" in QGIS-macOS-3.4.6-2.dmg

Value is invarid
Invarid
/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/GDAL.framework/Versions/2.3/Programs:

Correct
/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/GDAL.framework/Versions/2.4/Programs:

GDAL included in the installer package is updated to 2.4.
So if you use Value in the Read me.rtf, result is "command not found" error.

**Comment by nyalldawson** [comment]
@PeterPetrik can this be closed?

**Comment by kyngchaos** [comment]
Actually, that's my package.  It's been fixed for a while and is correct in my 3.4.12 and 3.8.3 (my latest for now).
