### ISSUE TITLE
QgsCollapsibleGroupBox - QtEditor - Editing of child widgets fails when box is collapsed

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29733]
Author Name: **Johannes Elstner** (@fuzzysolutions)
Original Redmine Issue: [21918](https://issues.qgis.org/issues/21918)
Affected QGIS version: 3.6.2
Redmine category:gui

---
In the Qt Editor, I add a @QgsCollapsibleGrouBox@ and then add any kind of child widget into the box. Now I set the group box on _collapsed_ state and select the child widget in the object list. When I try to edit the widget's settings (e.g. rename it), after every keyboard input the main form (dockwidget, dialog, mainwindow) gets focus and I have to re-navigate to the widget to proceed editing.

For default Qt widgets that can hide their child widgets (QTabwidget, QStackedWidget), the editor unhides the child widget when I start editing them. The behavior described above seems to affect QGIS custom widgets only, that's why I file my bug report here.

**Comment by gioman** [comment]
@fuzzysolutions is this still valid in recent QGIS releases?

**Comment by fuzzysolutions** [comment]
@gioman cannot reproduce, seems to have been solved.
