### ISSUE TITLE
QGIS crash

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29734]
Author Name: **Anne Sophie Brunin** (Anne Sophie Brunin)
Original Redmine Issue: [21919](https://issues.qgis.org/issues/21919)
Affected QGIS version: 3.4.7
Redmine category:unknown

---
## User Feedback

Hello,
I've just installed QGIS Madeira. Each time i want to save a project Qgis crashes.
Thanks for your help
AnneSo

## Report Details

*Crash ID*: 3666ff2bae6d8bd45a40e1776238359ec54c5dcb

*Stack Trace*
```
longjmp :
RtlDllShutdownInProgress :
DbgUiRemoteBreakin :
BaseThreadInitThunk :
RtlUserThreadStart :

```

*QGIS Info*
QGIS Version: 3.4.7-Madeira
QGIS code revision: 5c56989325
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
