### ISSUE TITLE
Points Geometry Become Cluster

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29735]
Author Name: **Furqan Saeed** (Furqan Saeed)
Original Redmine Issue: [21920](https://issues.qgis.org/issues/21920)
Affected QGIS version: 3.4.5
Redmine category:data_provider/mssql

---
I am connected to same sql db both in QGIS 2.18.3 and QGIS 3.4.5. As seen in the photo below, points geometries in QGIS 2.18.3 are absolutely correct but in QGIS 3.4.5, same points become cluster. 

Also "geog" column in QGIS 2.18.3 attribute table is hidden by default, I don't even find it in layer properties. However in QGIS 3.4.5, there is "geog" column in attribute table which shows special character in it. 

Another issue is when I add new point feature in QGIS 3.4.5 it only saves attribute not geometry.

---

- [QGIS 2.18.3_Identify.jpg](https://issues.qgis.org/attachments/download/14837/QGIS%202.18.3_Identify.jpg) (Furqan Saeed)
- [QGIS 2.18.3.jpg](https://issues.qgis.org/attachments/download/14838/QGIS%202.18.3.jpg) (Furqan Saeed)
- [QGIS 3.4.5_Identify.jpg](https://issues.qgis.org/attachments/download/14839/QGIS%203.4.5_Identify.jpg) (Furqan Saeed)
- [QGIS 3.4.5-Madeira.jpg](https://issues.qgis.org/attachments/download/14840/QGIS%203.4.5-Madeira.jpg) (Furqan Saeed)

**Comment by gioman** [comment]
Closing for lack of feedback.
