### ISSUE TITLE
GPS Information / Position always shows "-1.0m" for accuracy

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29748]
Author Name: **Jürgen Fredriksson** (Jürgen Fredriksson)
Original Redmine Issue: [21933](https://issues.qgis.org/issues/21933)
Affected QGIS version: 3.6.2
Redmine category:gps_live_tracking

---
I tried several versions of QGIS (2.18, 3.6, 3.4)

All of them show the same behaviour:

The H Accuracy and V Accuracy is always "-1.0m".

If you use a receiver in RTK-Mode, you really want to see the residuals..

### Vertical RMS

@VRMS = math.sqrt(math.pow(GST_Field_8, 2))
@

### Horizontal RMS

@HRMS = math.sqrt((math.pow(GST_Field_6, 2) + math.pow(GST_Field_7, 2))/2)
@

### Positional RMS

@PRMS = math.sqrt((math.pow(GST_Field_6, 2) + math.pow(GST_Field_7, 2) + math.pow(GST_Field_8, 2))/3)
@

Please make that available!
Thanks!

**Comment by alexbruy** [comment]
Seems already fixed.
