### ISSUE TITLE
Crash when opening a project with PostGIS rasters

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29745]
Author Name: **Markus Weidenbach** (Markus Weidenbach)
Original Redmine Issue: [21930](https://issues.qgis.org/issues/21930)
Affected QGIS version: 3.6.2
Redmine category:data_provider/postgis

---
## User Feedback

I am trying to open a postgis project (PSQL 10). All Layers are being loaded. I can see the complete list in the Layer Window, but before the layers are being displayed on the canvas, QGIS crashes.
I am using the passwort authentication manager, where my password is saved and the configuration is set to "SSL preferred".
I am also using different user/passwords, with diferent PostGIS/PSQL priviliges. The crash happens with my admin user login and with the read-only user login.  
I used the DB Manager to add raster data stored on PSQL to the QGIS Project. 

## Report Details

*Crash ID*: 32d075ab92c40bf51fd4bb9e96d388e778621db8

*Stack Trace*
```
BIO_ctrl :
SSLv3_client_method :
SSLv3_client_method :
PQinitSSL :
PQinitSSL :
PQenv2encoding :
PQgetResult :
PQgetResult :
PQexec :
GDALRegister_PostGISRaster :
GDALRegister_PostGISRaster :
GDALRasterBand::RasterIO :
dataCapabilities :
QgsMultiBandColorRenderer::block :
QgsBrightnessContrastFilter::block :
QgsHueSaturationFilter::block :
QgsRasterResampleFilter::block :
QgsRasterProjector::block :
QgsRasterIterator::readNextRasterPartInternal :
QgsRasterDrawer::draw :
QgsRasterLayerRenderer::render :
QgsMapRendererParallelJob::renderLayerStatic :
QgsMapRendererParallelJob::renderingFinished :
QgsMapRendererParallelJob::renderingFinished :
QgsArchive::zip :
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

```

*QGIS Info*
QGIS Version: 3.6.0-Noosa
QGIS code revision: 58734527ab
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.0
Running against GDAL: 2.4.0

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

---

Related issue(s): #29774 (duplicates)
Redmine related issue(s): [21959](https://issues.qgis.org/issues/21959)

---

**Comment by gioman** [comment]
Closing for lack of feedback.
