### ISSUE TITLE
Snapping Settings window with Night Mapping, low readability

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29751]
Author Name: **Nicklas Larsson** (Nicklas Larsson)
Original Redmine Issue: [21936](https://issues.qgis.org/issues/21936)
Affected QGIS version: 3.4.7
Redmine category:gui

---
The Snapping Settings window has an inconsistent layout and partly very difficult to read due to low contrast with Night Mapping theme (at least on macOS).

This is the present layout:
![Screenshot.png](https://issues.qgis.org/attachments/download/14850/Screenshot.png)

Suggested changes:

1. The checkboxes (Layer and Avoid intersection) should be dark grey not black
2. The checkmark in Layer should be light grey
3. The Layer name should be dark or light grey depending on checked or not

![Mockup.png](https://issues.qgis.org/attachments/download/14851/Mockup.png)

---

- [Screenshot.png](https://issues.qgis.org/attachments/download/14850/Screenshot.png) (Nicklas Larsson)
- [Mockup.png](https://issues.qgis.org/attachments/download/14851/Mockup.png) (Nicklas Larsson)

**Comment by PeterPetrik** [comment]
Looks like already fixed...

![Screenshot 2020-10-06 at 15 02 25](https://user-images.githubusercontent.com/804608/95204906-fb995500-07e4-11eb-8e7c-cfbd2f1ad74e.png)

**Comment by nirvn** [comment]
Yep, fixed this a few weeks ago.
