### ISSUE TITLE
Clear filter in Snapping Toolbar > Edit advanced configuration causes crash

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29750]
Author Name: **Nicklas Larsson** (Nicklas Larsson)
Original Redmine Issue: [21935](https://issues.qgis.org/issues/21935)
Affected QGIS version: 3.4.7
Redmine category:unknown

---
Clicking the "Clear filter"-button (see attached screenshot) in the "Edit advanced configuration" popup window in Snapping Toolbar causes crash.

Curiously, the same procedure in "Project Snapping Settings" works as expected.

---

- [crashreport.txt](https://issues.qgis.org/attachments/download/14848/crashreport.txt) (Nicklas Larsson)
- [Screenshot.png](https://issues.qgis.org/attachments/download/14849/Screenshot.png) (Nicklas Larsson)
- [crashreport_win10.txt](https://issues.qgis.org/attachments/download/14874/crashreport_win10.txt) (Nicklas Larsson)

**Comment by PeterPetrik** [comment]
unable to replicate on master from https://qgis.org/downloads/macos/nightly/qgis_nightly_master_20201005_122844.dmg
on MacOS. 

![clear_filter_crash](https://user-images.githubusercontent.com/804608/95204077-e1ab4280-07e3-11eb-8b4e-4baa22c56410.gif)
