### ISSUE TITLE
ScaleBar text needs to be able to be changed/modified for rounding/precision changes

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29756]
Author Name: **Brett Carlock** (@Saijin-Naib)
Original Redmine Issue: [21941](https://issues.qgis.org/issues/21941)

Redmine category:map_composer/printing

---
The ScaleBar object should have the ability for the precision/rounding preferences to be set, instead of using N-number of decimals with no control.

Not only does this make the ScaleBar look messy and unprofessional, it implies a level of precision that likely is not met with the data and how the map has been prepared.

There should be a user-facing option to change the precision/rounding to whatever number of digits/places desired.

I've attached a screenshot of what this ScaleBar text looks like on my layout when using miles as the unit.

---

- [Annotation 2019-04-26 105840.png](https://issues.qgis.org/attachments/download/14852/Annotation%202019-04-26%20105840.png) (Brett Carlock)

**Comment by nyalldawson** [comment]
Implemented since QGIS 3.12
