### ISSUE TITLE
Processing OGR based tools: encoding changed in outputs

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29764]
Author Name: **Bernd Vogelgesang** (Bernd Vogelgesang)
Original Redmine Issue: [21949](https://issues.qgis.org/issues/21949)
Affected QGIS version: 3.6.2
Redmine category:processing/ogr

---
When trying to buffer a point dataset with the GDAL buffer vector function, the attributes get obviously encoded to sth else than the original UTF-8.
All special characters become a ? on black rhombic background. When manually setting the resulting layer to windows1252, the special characters are visible again.
This seems to apply to other GDAL/OGR functions besides buffer as well.

Besides that I would like to second Tobias's feature request #29097 to change the output format from ESRI shapefile to GPKG, cause shape format (dbase) might cripple any GPKG-based workflow. And as GPKG is UTF-8 by default, the encoding issues would/could/should be gone as well, I hope.

QGIS 3.6.2 on Linux Mint

**Comment by alexbruy** [comment]
Just tested using shapefile with cyrillic attributes and can not confirm

**Comment by nyalldawson** [comment]
Closing due to lack of feedback
