### ISSUE TITLE
change data source and style gets overridden

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29769]
Author Name: **Gavin Fleming** (@gubuntu)
Original Redmine Issue: [21954](https://issues.qgis.org/issues/21954)
Affected QGIS version: 3.6.2
Redmine category:symbology

---
I created a project whose layers came from a locally available PostGIS connection (replication slave). 

When I opened the project on another network I had to change the PostGIS source to the replication master host. 

The layers loaded fine but with their default styles - my layer styles were overriden. 

Expected behaviour: replacing a layer's source should not affect the style. 

---

Related issue(s): #29902 (duplicates), #29906 (duplicates)
Redmine related issue(s): [22089](https://issues.qgis.org/issues/22089), [22093](https://issues.qgis.org/issues/22093)

---

**Comment by gubuntu** [comment]
Do you need more feedback? The cases described in the duplicates provide other examples of the same phenomenon.

**Comment by nyalldawson** [comment]
I can't reproduce this. Is it still an issue?

**Comment by middlepfeifer** [comment]
I am also now experiencing this in QGIS 3.14.1 using .shp and .gpkg files.  Using the handle unavailable layers interface at startup, I re-path all of the layers but the symbology / styling is lost for all the layers when map opens, to default or random styles when the map loads.

For testing purposes, I launched QGIS 3.8.0 and handled unavailable layers in the same fashion, and style / symbology is preserved.

**Comment by nyalldawson** [comment]
Is it possible to share a project and data which can be used to reproduce this? I'm still unable to reproduce.
