### ISSUE TITLE
QGIS Crashing while using Advanced Digitizing with snapping enabled

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29763]
Author Name: **James Moss** (James Moss)
Original Redmine Issue: [21948](https://issues.qgis.org/issues/21948)
Affected QGIS version: 3.4.6
Redmine category:digitising

---
I am running QGIS version 3.4.6.  It is crashing if I have the Advanced Digitzing active with snapping enabled.  When I turn off snapping, Advanced Digitizing works as it should.

**Comment by olivierdalang** [comment]
I can reproduce the crash on windows with the "show snapping tooltips" option from the digitizing options.

**Comment by ciseur68** [comment]
Same problem on 3.4.5 and 3.4.8.

**Comment by gioman** [comment]
Do not seems to be valid anymore, but please reopen if you find that is still is.
