### ISSUE TITLE
report details

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29775]
Author Name: **Piotr Pogoda** (Piotr Pogoda)
Original Redmine Issue: [21960](https://issues.qgis.org/issues/21960)
Affected QGIS version: 3.4.7
Redmine category:unknown

---
Crash ID: 7962d96f2596f89001068d78ffb584d1b19f74a6

Stack Trace

QgsSnapIndicator::~QgsSnapIndicator :
QgsAdvancedDigitizingCanvasItem::~QgsAdvancedDigitizingCanvasItem :
OGREnvelope3D::operator= :
QgsMapCanvas::~QgsMapCanvas :
QgsVectorLayerProperties::`default constructor closure' :
QgisApp::~QgisApp :
CPLStringList::List :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.4.7-Madeira
QGIS code revision: 5c56989325
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
