### ISSUE TITLE
Layer Panel display for point data  layer unusable.

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29776]
Author Name: **John Fynn** (John Fynn)
Original Redmine Issue: [21961](https://issues.qgis.org/issues/21961)
Affected QGIS version: 3.4.5
Redmine category:map_legend

---
Layers that display point data (i.e. a symbol denoting that one of our properties has been sold) display in an extremely expanded way that makes the layer unusable. These layers displayed perfectly OK in 2.18 but not in 3.45.

If I right click on the layer and select properties then just click on Apply the display reverts to normal. If I then interact with the layer in any way (i.e deselect a category) The layer immediately expands so that it is useless - please see attached file with images.

---

- [Normal layer display.png](https://issues.qgis.org/attachments/download/14866/Normal%20layer%20display.png) (Saber Razmjooei)
- [Expanded layer display.png](https://issues.qgis.org/attachments/download/14867/Expanded%20layer%20display.png) (Saber Razmjooei)
- [TreeDataCategorization.png](https://issues.qgis.org/attachments/download/14869/TreeDataCategorization.png) (John Fynn)
- [TreeDataLayerPanelAfter.png](https://issues.qgis.org/attachments/download/14871/TreeDataLayerPanelAfter.png) (John Fynn)
- [TreeDataLayerPanelBefore.png](https://issues.qgis.org/attachments/download/14872/TreeDataLayerPanelBefore.png) (John Fynn)
- [LayerTestProperties.csv](https://issues.qgis.org/attachments/download/14876/LayerTestProperties.csv) (John Fynn)
- [Housing_v3_4_5_bug_test.qgs.qgz](https://issues.qgis.org/attachments/download/14877/Housing_v3_4_5_bug_test.qgs.qgz) (John Fynn)
- [Screenshot_20190502_142735.png](https://issues.qgis.org/attachments/download/14879/Screenshot_20190502_142735.png) (Giovanni Manghi)

**Comment by alexbruy** [comment]
Closed for the lack of feedback. Please reopen if necessary.
