### ISSUE TITLE
JPG with Worldfiles shows black bounding box

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29777]
Author Name: **Roland Spielhofer** (Roland Spielhofer)
Original Redmine Issue: [21962](https://issues.qgis.org/issues/21962)
Affected QGIS version: 3.6.2
Redmine category:rasters

---
I have several JPGs together with JGW (worldfiles).
When I open them in QGIS 3.6.1 as Raster they show a black orthoganal bounding box while the image istself is shown rotated.
Comparison in ArcGIS: No black unrotated bounding box is shown.

Expected behaviour: Only rotated image is shown, no black boundingbox.

I attach a screenshot of side-by-side comparison on ArcGIS and QGis and a JPG image with according JGW worldfile to reproduce.
(The image shows road surface, do not mind that it shows only lots of shades of grey).

---

- [Worldfiles_JPG_QGis_ArcGis.jpg](https://issues.qgis.org/attachments/download/14862/Worldfiles_JPG_QGis_ArcGis.jpg) (Roland Spielhofer)
- [A01L1_km146,178_km145,830___181109_1134_CRACK_tf1,029_0.jpg](https://issues.qgis.org/attachments/download/14863/A01L1_km146,178_km145,830___181109_1134_CRACK_tf1,029_0.jpg) (Roland Spielhofer)
- [A01L1_km146,178_km145,830___181109_1134_CRACK_tf1,029_0.jgw](https://issues.qgis.org/attachments/download/14864/A01L1_km146,178_km145,830___181109_1134_CRACK_tf1,029_0.jgw) (Roland Spielhofer)

**Comment by gioman** [comment]
Closing as duplicate.
