### ISSUE TITLE
Georeferencer plugin does not work

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29772]
Author Name: **Janet Sanderson** (Janet Sanderson)
Original Redmine Issue: [21957](https://issues.qgis.org/issues/21957)
Affected QGIS version: 3.6.1
Redmine category:c++_plugins/georeferencer

---
Georeferencing features is not working and has been like this for almost 2 weeks now.  I require this features/plugin with almost all my projects and this has been rather frustrating not been able to use this.  The plugin from the python console works but not as well as the built in version.  Please could you rectify this?

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
