### ISSUE TITLE
QGIS Server SELECTION doesn't work with Postgres ids of type bigint or text

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29779]
Author Name: **Éric Lemoine** (@elemoine)
Original Redmine Issue: [21964](https://issues.qgis.org/issues/21964)
Affected QGIS version: 3.7(master)
Redmine category:qgis_server

---
The WMS GetMap SELECTION parameter allows selecting features by their ids.  But this may not work on Postgres-based layers depending on the type of the id column and the values for that column.

For example it does not work with id columns of type bigint.  This is a major problem as Postgres' row_number() function returns a bigint, and row_number() is very often used when creating views and materialized views.

The problem is related to the selection code calling selectByIds without converting the passed id to an fid.  This works correctly for ids of type int when all the ids are positive. But it doesn't work when the id column includes negative values.  Nor does it work with id columns of type bigint or text.

I think there should be an idtofid function somewhere, and the selection code calling selectByIds should call that idtofid function prior to calling selectByIds.

**Comment by elpaso** [comment]
@elemoine are you working on this one?

**Comment by rldhont** [comment]
@elemoine @elpaso I probably do the fix here, isn't it ? https://github.com/qgis/QGIS/pull/10034

**Comment by elpaso** [comment]
@rldhont yes, thank you for working on this!

**Comment by pblottiere** [comment]
I think it may be closed thank to https://github.com/qgis/QGIS/pull/10034.
