### ISSUE TITLE
"Order by expression" doesn't order anything

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29794]
Author Name: **Bernd Vogelgesang** (Bernd Vogelgesang)
Original Redmine Issue: [21979](https://issues.qgis.org/issues/21979)
Affected QGIS version: 3.6.2
Redmine category:processing/qgis

---
I tried to order a point layer by its x and y coordinates within the attribute table with "Order by expression". No matter what I try, the result is not ordered by the columns I choose.

**Comment by alexbruy** [comment]
Can not reproduce on master.

**Comment by volaya** [comment]
I can confirm, it doesn't seem to work here (3.12). It changes the order of features, but they are not ordered according to the expression. At least, when input is a shapefile and output is shapefile or memory

**Comment by nirvn** [comment]
Any chance of attaching a sample dataset here?

**Comment by volaya** [comment]
Looks like the algorithm actually works, but it's hard to see the effect it has, due to this other bug: 

https://github.com/qgis/QGIS/issues/27127

But if you programatically list the features, they seem to be in the correct order in the ouput layer

**Comment by Gustry** [comment]
In the algorithm help, it's written:

> Be careful, it might not work as expected with some providers, the order might not be kept every time.

I'm not sure about which format it's working well. I was using GeoJSON at that time.

**Comment by arnaud-morvan** [comment]
I recently has same issue, but not from sortbyexpression algorithm but default attribute table sort.
Attribute table does not seems to reflect source order.
If use sortbyexpression and add autoincrement field, this new field is correctly set.
Now I can use this field to sort attribute table.

**Comment by nirvn** [comment]
The order by expression algorithm works fine, it's the attribute table that doesn't respect default dataset/provider ordering.
