### ISSUE TITLE
python support not enabled after install

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29790]
Author Name: **Roberto Comune Boffelli Comune** (Roberto Comune Boffelli Comune)
Original Redmine Issue: [21975](https://issues.qgis.org/issues/21975)
Affected QGIS version: 3.6.1
Redmine category:build/install

---
as the subject report ... 
I have (or better the informatic service IT of my company where i'm 'employed') 
to install the all possible version of QGis installers (32 or 64 ... stand alone and web installation... and more 
various version of QGis 'last weekly version' and 'long term/stable release version')

but every time (afer the conclusion of the installation process) i have the same problem ......
at start the QGis app show me a 'strange error' concerned 'a strage import operation' of a module 

qgis._core     (is the 'underscore' that appaire to me to be strange .... because there is the qgis/core ... modules folders
                but opposite there isn't qgis/_core folders) .... 

the consequences of this .... are that QGis block every Python usage and after the 'bad start' of the application
i don't have any support to use Phyton .... (console and etc) 

why it happen with all possible installer versions? ... it strange no? am i the only one with this problem? 
are made a wrong installation? 

thank you 
have a nice day

Roberto

---

- [Error_on_QGIS_Start.Jpg](https://issues.qgis.org/attachments/download/14875/Error_on_QGIS_Start.Jpg) (Roberto Comune Boffelli Comune)

**Comment by alexbruy** [comment]
Closed for the lack of feedback and poor description. Please reopen if necessary and add clear description.
