### ISSUE TITLE
 [processing][xyz tiles] De-activate folder/file based on output type for XYZ tile generator

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29803]
Author Name: **Saber Razmjooei** (@saberraz)
Original Redmine Issue: [21988](https://issues.qgis.org/issues/21988)
Affected QGIS version: 3.7(master)
Redmine category:processing/qgis

---
Currently, if user selects director or MBTiles, both output paths are activated. Best, to deactivate the unused one.

**Comment by saberraz** [comment]
This ticket is no longer valid...but I am not able to close it.

**Comment by wonder-sk** [comment]
Already addressed by splitting the algorithm into two.
