### ISSUE TITLE
Can not save data of type "array of characters (StringList / JSONSTRINGLIST) "on a layer connected to a spatialLite base : error : Type 5 of the x attribute of the entity y is unknown

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29801]
Author Name: **Mickaël CALLAC** (Mickaël CALLAC)
Original Redmine Issue: [21986](https://issues.qgis.org/issues/21986)
Affected QGIS version: 3.4.7
Redmine category:data_provider/spatialite
Assignee: Alessandro Pasotti

---
Test environment:
QGis 3.4.7-1 (LTR)
database: spatiaLite

The error appears in the case of a layer connected to a base SpatiaLite (generated by ogr2ogr) and for an array type field characters. The field in QGis has been set as "value relational ", the option" Allow multiple selections "is checked.

The field in QGis has the following properties:

Type: QString
Identity type: StringList
This is a field of type "JSONSTRINGLIST" in the base spatiaLite
When saving this field, the following error appears: 2019-05-03T11: 39: 48
CRITICAL Layer name layer: Type 5 of the x attribute of the entity y is unknown.

---

- [base.zip](https://issues.qgis.org/attachments/download/14885/base.zip) (Mickaël CALLAC)

**Comment by elpaso** [comment]
I'm afraid this is an upstream bug then: if ogr2ogr automatically create a JSONARRAY field in the destination DB (spatialite) it should also convert values to a valid JSON.
@rouault what do you think?

**Comment by mcallac** [comment]
Hello,
I wanted to know if you had news about this bug.
Thanks for your feedback

**Comment by elpaso** [comment]
This is not a QGIS issue: I confirm https://github.com/qgis/QGIS/issues/29801#issuecomment-495907467
