### ISSUE TITLE
[processing][xyz tiles] warn user when overwriting files/folders

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29805]
Author Name: **Saber Razmjooei** (@saberraz)
Original Redmine Issue: [21990](https://issues.qgis.org/issues/21990)

Redmine category:processing/qgis

---
Warn users of overwriting data if the selected output folder is not empty.

**Comment by alexbruy** [comment]
We can't add interactive prompts to Processing tools. Will adding a new boolean parameter "Overwrite any existing files/folders"  solve the issue? Such parameter will be on by default to keep backward compatibility and when it is OFF algorithm will fail is destination folder is not empty.
