### ISSUE TITLE
DB Manager > History: current_user not written when updating

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29816]
Author Name: **Paolo Cavallini** (@pcav)
Original Redmine Issue: [22001](https://issues.qgis.org/issues/22001)
Affected QGIS version: 3.4.7
Redmine category:db_manager

---
In QGIS 3.4 the Historicization of a table works smoothly, except for the fact that the current_user is added to the table when creating or deleting a feature, but not when updating. Does anyone confirm? I had a look to the function[0] but I could not find anything obvious explaining the failure.

[0]
CREATE OR REPLACE FUNCTION "gis"."polygons_update"()
RETURNS TRIGGER AS
$$
BEGIN
  IF OLD."time_end" IS NOT NULL THEN
    RETURN NULL;
  END IF;
  IF NEW."time_end" IS NULL THEN
    INSERT INTO "gis"."polygons"
("id_0","geom","id","name","area","centroid", "time_start", "time_end")
VALUES
(OLD."id_0",OLD."geom",OLD."id",OLD."name",OLD."area",OLD."centroid",
OLD."time_start", current_timestamp);
    NEW."time_start" = current_timestamp;
    NEW."ruolo_utente" = current_user;
  END IF;
  RETURN NEW;
END;
$$
LANGUAGE 'plpgsql';

**Comment by alexbruy** [comment]
Is this still an issue? I can't reproduce on master.

**Comment by pcav** [comment]
I confirm, still true:
* create a spatial table
* digitize a polygon > username is added
* edit the same polygon > a new record is added, without username

**Comment by thbaumann** [comment]
In the insert statement of the update function the "user_role" column is not included. I would just write the OLD."user_role" into this column::

`CREATE OR REPLACE FUNCTION "gis"."polygons_update"()
RETURNS TRIGGER AS
$$
BEGIN
IF OLD."time_end" IS NOT NULL THEN
RETURN NULL;
END IF;
IF NEW."time_end" IS NULL THEN
INSERT INTO "gis"."polygons"
("id_0","geom","id","name","area","centroid", "time_start", "time_end", "ruolo_utente")
VALUES
(OLD."id_0",OLD."geom",OLD."id",OLD."name",OLD."area",OLD."centroid", OLD."time_start", current_timestamp, OLD."ruolo_utente");
NEW."time_start" = current_timestamp;
NEW."ruolo_utente" = current_user;
END IF;
RETURN NEW;
END;
$$
LANGUAGE 'plpgsql';`

Probably it would be also good to check if the OLD."user_role" is null before trying to use it in the insert statement.

**Comment by Pedro-Murteira** [comment]
@pcav Still true on recent releases?
