### ISSUE TITLE
Lock postgres/postgis on st_estimatedextent and st_makeenvelope

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29823]
Author Name: **Corentin Falcone** (Corentin Falcone)
Original Redmine Issue: [22009](https://issues.qgis.org/issues/22009)
Affected QGIS version: 3.6.2
Redmine category:data_provider/postgis

---
Hi,
We have a repetitive lock on postgres/postgis database using QGIS. 
Some times using a postgis layer in QGIS it creates a lockin the database and QGIS can no longer use the layer and freeze to death. 
Then we have two option, either kill the query on pgadmin dashboard or close and reopen QGIS to be able to work again.
This issue can appear many times in a day.

What we have managed to understand this far, is that the layer seems to lock when queries st_makeenvelope and st_estimatedextent are exectuted.
We've experienced thoses lock since the QGIS 3 version.

Hope you'll be able to solve that problem,
Thanks by advance

**Comment by gioman** [comment]
Is this still an issue?

**Comment by Doctor-Who** [comment]
Hello,

Only with PostGreSQL 9.x. 
From 10 to 12, there is no more that issue.

It can be close.
