### ISSUE TITLE
QGIS Crashed

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29828]
Author Name: **Phil K** (Phil K)
Original Redmine Issue: [22014](https://issues.qgis.org/issues/22014)
Affected QGIS version: 3.6.2
Redmine category:unknown

---
Crash on Exit, happens on all versions of 3.x that I have tried.
Same result each time.

## User Feedback

Crash on Exit, happens on all versions of 3.x that I have tried.
Same result each time.

## Report Details

*Crash ID*: 029f5c6666883dccbe82e27c6e58cc0b7b3cc412

*Stack Trace*
```
QgsMapToolExtent::~QgsMapToolExtent :
PyInit__gui :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
QgsVectorLayerProperties::`default constructor closure' :
QgisApp::~QgisApp :
CPLStringList::List :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

```

*QGIS Info*
QGIS Version: 3.6.2-Noosa
QGIS code revision: 656500e0c4
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
