### ISSUE TITLE
Batch processing error in r.mapcalc.simple

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29822]
Author Name: **Daria Svidzinska** (@darsvid)
Original Redmine Issue: [22008](https://issues.qgis.org/issues/22008)
Affected QGIS version: 3.6.2
Redmine category:processing/core

---
I'm trying to perform batch processing for multiple rasters using a conditional expression in r.mapcalc.simple, GRASS 7.6.1.

The expression is:
@if((A==322||A==386||A==834||A==898||A==1346)&&(B<=10000&&B>=-10000),(B*0.0001),null())@
where A is a qa_raster and B is a ndvi_raster.

The approach works fine for a single job, but when I try to process multiple files I constantly get an error.

For your convenience I attach the following files:

* batch_processing_error.txt - log of batch processing with error
* qgis_version_info.txt - information about QGIS version etc
* test_project.zip - a test project with a couple of layers as a data example

---

- [qgis_version_info.txt](https://issues.qgis.org/attachments/download/14893/qgis_version_info.txt) (Daria Svidzinska)
- [batch_processing_error.txt](https://issues.qgis.org/attachments/download/14894/batch_processing_error.txt) (Daria Svidzinska)
- [test_project.zip](https://issues.qgis.org/attachments/download/14895/test_project.zip) (Daria Svidzinska)

**Comment by alexbruy** [comment]
Should be fixed in master.
