### ISSUE TITLE
Add GRASS "turntable" parameters to v.net modules

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29833]
Author Name: **Sergio Antonio** (Sergio Antonio)
Original Redmine Issue: [22019](https://issues.qgis.org/issues/22019)

Redmine category:processing/grass
Assignee: Giovanni Manghi

---
The GUIs of the tools v.net.path, v.net.alloc, v.net.iso, v.net.salesman are not showing the possibility to configure the use of the turntable (parameter -t of each algorithm), according to the manual .
This parameter is indispensable for the good performance of the tools: v.net.path, v.net.alloc, v.net.iso, v.net.salesman.
The turntable is created by the v.net tool, which is not showing this function in "operation to be performed".
Please see attached texts with highlights.

---

- [GRASS GIS manual_ v.net.pdf](https://issues.qgis.org/attachments/download/14908/GRASS%20GIS%20manual_%20v.net.pdf) (Sergio Antonio)
- [GRASS GIS manual_ v.net.path.pdf](https://issues.qgis.org/attachments/download/14909/GRASS%20GIS%20manual_%20v.net.path.pdf) (Sergio Antonio)

**Comment by alexbruy** [comment]
Duplicates #25328.
