### ISSUE TITLE
progress bar never ends for some batch mode operations

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29848]
Author Name: **Giovanni Manghi** (@gioman)
Original Redmine Issue: [22034](https://issues.qgis.org/issues/22034)
Affected QGIS version: 3.6.2
Redmine category:processing/core

---
For example the OGR tool to export data in PostGIS.

Actually the operation ends correctly, but the progress bar never reaches 100%.

**Comment by alexbruy** [comment]
Duplicates #29016
