### ISSUE TITLE
Mapped Network Drives Disappear in the QGIS Browser 

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29851]
Author Name: **Tyler Veinot** (Tyler Veinot)
Original Redmine Issue: [22037](https://issues.qgis.org/issues/22037)
Affected QGIS version: 3.6.2
Redmine category:browser

---
Whenever my PC is shutdown and restarted QGIS will loose all network drives requiring me to right click in the browser favorites, add directory, where I then have to map to the missing network drives. Once remapped they all repopulate in the browser, this needs to be done every time the PC is restarted and sometimes after a complete QGIS shutdown.

**Comment by gioman** [comment]
Seems ok to me on the latest releases, please reopen if necessary.
