### ISSUE TITLE
MSSQL: Add support for v2 geometries (MSSQL2012+)

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29855]
Author Name: **Tamas Szekeres** (@szekerest)
Original Redmine Issue: [22041](https://issues.qgis.org/issues/22041)

Redmine category:data_provider/mssql
Assignee: Tamas Szekeres

---
The mssql provider should support the v2 curve geometries introduced in MSSQL2012

**Comment by nyalldawson** [comment]
Fixed in 3.8
