### ISSUE TITLE
QGIS crashes with VNC connection

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29859]
Author Name: **Daan VAN SETTEN** (Daan VAN SETTEN)
Original Redmine Issue: [22045](https://issues.qgis.org/issues/22045)
Affected QGIS version: 3.6.2
Redmine category:unknown

---
Hello

I'm running QGIS 3.6.2 on UBUNTU 18.04.2/Xfce desktop environment. The particularity is that I'm accessing the server through a secured VNC connection (tightVNC).

When I launch QGIS, everythings goes well, although I get the following 2 warnings:

   Warning: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
   Warning: Qt: XKEYBOARD extension not present on the X server.

However, when I add some data, select a tool and then move the cursor to the canvas, QGIS crashes. Apparantly because it is not able to acces the icon/image for the cursor. It crashes while giving the following warnings:

   Warning: qt_xcb_createCursorXRender: query_pict_formats failed
   Warning: The X11 connection broke (error 2). Did the X11 server die?

I did some research, and it seems that the solution can be found here with a path for QT.
https://codereview.qt-project.org/#/c/225665/

Unfortunately, I have no idea how to apply this patch.... Is that something I can do on my server or does did need a new QGIS release ???

Any help would be really appreciated. Thanks in advance, Daan

**Comment by gioman** [comment]
Is this still true on recent QGIS releases?
