### ISSUE TITLE
QGIS crashed when I use 3D View

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29854]
Author Name: **Wolfgang Figura** (Wolfgang Figura)
Original Redmine Issue: [22040](https://issues.qgis.org/issues/22040)
Affected QGIS version: 3.6.2
Redmine category:3d

---
When I use the 3D view, QGIS crashes reproducibly.
## User Feedback

When I use the 3D view, QGIS crashes reproducibly.

## Report Details

*Crash ID*: 343c12136d6018e5544d50f723e565c45088949d

*Stack Trace*
```
QgsWindow3DEngine::tr :
QgsFlatTerrainGenerator::writeXml :
QMetaObject::activate :
QgsMapLayer::repaintRequested :
QgsRasterLayer::refreshRendererIfNeeded :
QgsRasterLayerRenderer::QgsRasterLayerRenderer :
QgsRasterLayer::createMapRenderer :
QgsMapRendererJob::prepareJobs :
QgsMapRendererCustomPainterJob::start :
QgsMapRendererSequentialJob::start :
QgsTerrainGenerator::typeToString :
QgsFlatTerrainGenerator::writeXml :
QgsFlatTerrainGenerator::writeXml :
QgsCameraPose::setCenterPoint :
QgsWindow3DEngine::tr :
QgsWindow3DEngine::tr :
QMetaObject::activate :
QMetaObject::activate :
Qgs3DAlgorithms::qt_metacast :
QgsTerrainGenerator::typeToString :
QMetaObject::activate :
QMetaObject::activate :
QMetaObject::activate :
QFutureWatcherBase::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
TranslateMessageEx :
TranslateMessage :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

```

*QGIS Info*
QGIS Version: 3.6.2-Noosa
QGIS code revision: 656500e0c4
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by PeterPetrik** [comment]
unable to reproduce on MacOS

**Comment by wonder-sk** [comment]
I cannot reproduce on Ubuntu either. What are the steps you did to trigger the crash? (i.e. how did you configure the 3d view)

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
