### ISSUE TITLE
Zoom in/out and autorefreshing of raster doesn’t work after georeferencing

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29850]
Author Name: **Lukasz Olszyna** (Lukasz Olszyna)
Original Redmine Issue: [22036](https://issues.qgis.org/issues/22036)
Affected QGIS version: 3.4.4
Redmine category:map_canvas

---
Steps:
1.Load SHP files 
2. Open the georeferencer and load the map (JPG file) to be georeferenced
3. Choose the transformation and output settings
4. Add points, press ‘Start georeferencing’ georeferenced map has been added as raster (TIF file) to map canvas
5. Untick ‘Load in QGIS when done’ and add /remove/move points in georeferencer window, press ‘start georeferencing’ again

QGIS 2.18.3 result: Georeferenced map refreshed automatically in project window after zoom in/out.

QGIS 3.4.4 result:   Georeferenced map is not refreshed after zoom in/out, georeferenced raster is displayed only in one zoom level, in other zoom levels is not displaying properly (black or color stripes area):
![QGIS error.jpg](https://issues.qgis.org/attachments/download/14911/QGIS%20error.jpg)
It is possible to work around this issue by delate old raster from map canvas and load new raster, but it was not necessary in previous QGis version. 

---

- [QGIS error.jpg](https://issues.qgis.org/attachments/download/14911/QGIS%20error.jpg) (Lukasz Olszyna)

**Comment by alexbruy** [comment]
Duplicates #28437
