### ISSUE TITLE
batch mode python error on QGIS master

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29862]
Author Name: **Giovanni Manghi** (@gioman)
Original Redmine Issue: [22048](https://issues.qgis.org/issues/22048)
Affected QGIS version: 3.7(master)
Redmine category:processing/core
Assignee: Alexander Bruy

---
Traceback (most recent call last):
  File "/usr/share/qgis/python/plugins/processing/gui/wrappers.py", line 212, in widgetValue
    return self.value()
  File "/usr/share/qgis/python/plugins/processing/gui/wrappers.py", line 1348, in value
    return self.widget.value()
AttributeError: 'BatchInputSelectionPanel' object has no attribute 'value'

after that the GUI opens but is not possible to select inputs already loaded in the project, it only allows to select them from file system, but then for each layer the same error is thrown.

**Comment by jef-n** [comment]
Fixed in 943b992ed3c8d115d2aa01e0acba1655190d4fe4
