### ISSUE TITLE
Crashing and general badness on reprojection to IGNF:RGNCUTM58S

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29864]
Author Name: **Jonathan Moules** (Jonathan Moules)
Original Redmine Issue: [22050](https://issues.qgis.org/issues/22050)
Affected QGIS version: 3.7(master)
Redmine category:vectors

---
I was messing around trying to find cool projections.

1) Add this shapefile: https://www.naturalearthdata.com/downloads/10m-cultural-vectors/10m-admin-0-countries/
(attached shapefile is a slightly more processed and smaller version of the above and seems to be more broken!)

2) Go to Project Properties -> CRS

3) Change projection to: IGNF:RGNCUTM58S

4) Zoom and pan around

Problems:
a) Watch the computer slow to a crawl.
b) Get "bad allocation" error messages pop up after a few pans. Keeps kind-of-working despite these (so why are they popping up?).
c) Watch RAM usage rocket to > 6GB!
d) Once I got a crash:

Crash ID: c13f228f746140c367f1fb34c2d8934f18842180

Stack Trace

QgsCoordinateTransform::transformBoundingBox :
QgsMapRendererJob::reprojectToLayerExtent :
QgsMapRendererJob::prepareJobs :
QgsMapRendererParallelJob::start :
QgsMapCanvas::refreshMap :
QMetaObject::activate :
QTimer::timerEvent :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32Private::sendTimerEvent :
QEventDispatcherWin32::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
TranslateMessageEx :
TranslateMessage :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.4.3-Madeira
QGIS code revision: 2f64a3c4e7
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.0
Running against GDAL: 2.4.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

---

- [General Data.zip](https://issues.qgis.org/attachments/download/14922/General%20Data.zip) (Jonathan Moules)

**Comment by lbartoletti** [comment]
confirmed on QGIS 3.4.7

@nyalldawson Might your work on proj6 have corrected that? (can't test for now)

**Comment by stev-0** [comment]
This looks like it has been fixed for me on 3.7 (Linux)
