### ISSUE TITLE
Consistent layer adding for services

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29870]
Author Name: **Jonathan Moules** (Jonathan Moules)
Original Redmine Issue: [22056](https://issues.qgis.org/issues/22056)

Redmine category:gui

---
QGIS has progressed nicely and now has the Data Source Manager. This is nice, but there's still the issue of a lack of consistency in adding layers for services (WMS, WFS, WCS, ArcGIS MapServer, ArcGIS FeatureServer, GeoNode).

1) Filtering
Different data sources have different ways of searching for layers within a service. 

I.e. WFS, ArcGIS MapServer/FeatureServer, and GeoNode all have a "filter".
WMS/WMTS, and WCS have nothing.
By comparison, the databases all seem to use a "search options" field and this appears consistent across database types.

2) The ordering of the name/title columns is inconsistent between service types

3) WMS, WCS include an "ID" column which doesn't represent anything that's in the getcap

4) CRS changing is represented differently for all of them

5) WFS allows you to specify the max version, the others don't.

6) Mechanism for specifying data format is different for the different services

7) WFS has "use title for layer name", but WCS doesn't. (WMS does it differently again, but WMS allows merging multiple layers together so...)

8) WFS and ArcGIS FeatureServer have the same settings but opposite defaults.

9) WMS and GeoNode include a "referer" field, but none of the others do.

There are probably more things, this isn't meant to be exhaustive, just a good starting place.

**Comment by alexbruy** [comment]
Please file separate tickets for each request/bug.
