### ISSUE TITLE
QGis crashes due to conflicting versions of HDF5 libraries when importing h5py module from python plugin

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29878]
Author Name: **Javier Becerra Elcinto** (Javier Becerra Elcinto)
Original Redmine Issue: [22065](https://issues.qgis.org/issues/22065)
Affected QGIS version: 3.7(master)
Redmine category:build/install

---
This bug was initially reported on https://github.com/PANOimagen/profiletool/issues/23 
A workaround has been implemented on ProfileTool to avoid the crash by deactivating the offending h5py import, but the underlying conflicting libraries still exist, this bug should affect any python plugin using h5py.

This does not seem to affect to QGis standalone/Os4Geo Express Desktop installs, but rather os4geo installations with custom installation options. It has been reported on Windows installations using os4geo installer with custom installation options and Mac (QGis 3.4.7 and 3.6.2 from Homebrew/Lutraconsulting).

Some of the libraries/applications bundled by Os4Geo installer seem to be compiled/running against different versions of hdf5 library, which causes QGis to crash when module h5py is imported from a Python plugin via a ```import h5py``` statement. However, running ```import h5py``` from Python console throws an 'ImportError', but does not cause the application to crash.

To reproduce the issue on a Windows machine:
- Download os4geo installer.
- Select *all* packages for installation.
- Once installed, launch QGis and select ProfileTool (version <= 4.1.6) for installing (the crash can also be triggered installing ProfileTool version <= 4.1.6 manually on python/plugins folder.)

A stack trace quite similar to this one appears also on issues #29626, #27628 and #28988

We could pin this down to h5py was thanks to a stack trace on a similar matlab/h5py issue (https://github.com/NeurodataWithoutBorders/api-python/issues/28) where the PyInit__conv call is bound to h5py_conv.cp36-win_amd64.pyd

---

- [profiletool_crash.txt](https://issues.qgis.org/attachments/download/14927/profiletool_crash.txt) (Javier Becerra Elcinto)
- [profiletool_crash_dev_version.txt](https://issues.qgis.org/attachments/download/14928/profiletool_crash_dev_version.txt) (Javier Becerra Elcinto)

**Comment by PeterPetrik** [comment]
maybe same as https://github.com/qgis/QGIS-Mac-Packager/issues/7#issuecomment-496489291

**Comment by delhomer** [comment]
Same problem here on Ubuntu 18.04 with QGIS 3.4.9.

I tried to import tensorflow on the QGIS console, however the `import tensorflow` just crashed QGIS, with a [cryptic stacktrace](https://pastebin.com/0zDDdXHr). As it mentions h5py too (h5py is a Tensorflow dependency), I tried `import h5py` in the QGIS console and it failed in the same manner.

Following [another thread](https://github.com/nens/ThreeDiToolbox/issues/247), I've tried to reload h5py module; it kind of solves my problem (I can now import h5py and Tensorflow from the QGIS console), even if I'm still unsure of which version is used by QGIS. :)

I saw #27628 first, however I hope it may confirm the diagnosis done in the original message.

**Comment by PCdurham** [comment]
In version 3.4 LTR, win10, I am now able to import the non-gpu version of tensorflow after downgrading h5py to v2.9.  Versions 2.8 and 2.10 of h5py both bug.

**Comment by alexbruy** [comment]
Still an issue with 3.10/master?

**Comment by alexbruy** [comment]
Closing for the lack of feedback. Please reopen if necessary.
