### ISSUE TITLE
Check for update suggests wrong option

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29872]
Author Name: **Jonathan Moules** (Jonathan Moules)
Original Redmine Issue: [22058](https://issues.qgis.org/issues/22058)
Affected QGIS version: 3.4.3
Redmine category:unknown

---
I'm using QGIS 3.4.3. This is an LTR release. If I select Check for Updates, it suggests updating to 3.6.x. What it should do is suggest updating to the latest LTR. This is what FireFox does.

If I'm on non-LTR, then it's fine to suggest updating to a non-LTR version.

**Comment by Pedro-Murteira** [comment]
If I check for updates on 3.22.3, QGIS points out that there's a new version: 3.24.0, instead of poiting out the new LTR which is 3.22.4. This might be done on purpose, but this issue is still valid.

**Comment by gioman** [comment]
Closing in favor of https://github.com/qgis/QGIS/issues/47645
