### ISSUE TITLE
WMS "Add Default Servers" button removal

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29873]
Author Name: **Jonathan Moules** (Jonathan Moules)
Original Redmine Issue: [22059](https://issues.qgis.org/issues/22059)
Affected QGIS version: 3.4.3
Redmine category:web_services_clients/wms

---
Per my enquiry to the list, the Add Default Servers button adds servers that are likely useless to the end user (software Demo servers with no meaningful data).
A couple folks suggested removing it.

**Comment by alexbruy** [comment]
For reference [discussion](https://lists.osgeo.org/pipermail/qgis-user/2019-May/043028.html) in the mailing list.
