### ISSUE TITLE
[Qgis 3.6 - composer] Qgis crashed with a map type's object wich have been rotated

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29877]
Author Name: **Gladal PS** (Gladal PS)
Original Redmine Issue: [22064](https://issues.qgis.org/issues/22064)
Affected QGIS version: 3.6.2
Redmine category:map_composer/printing

---
After some tests, I think having identified the origine of the problem. I create a project with a model where there is an atlas. There is a map rotated (in "rotation" parameter which are not under the scale). There are two problems : the map is not refresh (doesn't appear) and when I try to delete the map rotated Qgis crashes.
(When there is not the rotation, the project doesn't crash)

**Comment by nyalldawson** [comment]
I can't reproduce -- please attach a sample project which demonstrates this issue.

**Comment by gioman** [comment]
Closing for lack of feedback.
