### ISSUE TITLE
QGIS crashes opening file browser window

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29880]
Author Name: **Corey Burger** (@CoreyBurger)
Original Redmine Issue: [22067](https://issues.qgis.org/issues/22067)
Affected QGIS version: 3.6.2
Redmine category:project_loading/saving

---
QGIS crashes after opening file browser window. Likely the same as #28177, which was closed for some reason. On the same computer, 2.18 works correctly and 3.2 and 3.6 both crash, so the regression is clearly in QGIS

**Comment by CoreyBurger** [comment]
Tried with a new profile, still crashed. Also updated to 3.8, still the same issue
[stack.txt](https://github.com/qgis/QGIS/files/3429281/stack.txt)
[report.txt](https://github.com/qgis/QGIS/files/3429282/report.txt)

**Comment by CoreyBurger** [comment]
Tried with new Windows user, still crashed (although no stack report), so culprit isn't mapped drives as I had thought might be

**Comment by alexbruy** [comment]
Still true with 3.10/master?

**Comment by roya0045** [comment]
There are many other tickets with this issue

**Comment by rouault** [comment]
Solution given here: https://github.com/qgis/QGIS/issues/28177#issuecomment-495897805

**Comment by CoreyBurger** [comment]
So I ended up using the ShellExView solution listed in #28177 but I assume it would still be happening

**Comment by roya0045** [comment]
I also have a home made version with a possible fix but I'm not sure if its available anymore.
