### ISSUE TITLE
Weekly snapshot issue

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29892]
Author Name: **Jerry Brand** (Jerry Brand)
Original Redmine Issue: [22079](https://issues.qgis.org/issues/22079)
Affected QGIS version: 3.7(master)
Redmine category:windows_package
Assignee: Jürgen Fischer

---
This has been an issue for the last number of weekly releases. I can go back to the first 2 weekly snapshots of the 3.7 version and install those but not since without the error message. I got around it by saving the environment file in my temp directory and just copying it into the bin folder. The environment file has been missing in the last few weekly snapshots. The problem started with the 3.7.0-12 or 3.7.0-13 versions where the environment file changed name for some reason. The next release of the weekly snapshot reverted to the previous name but the actual file has not been included with the installation file.  

```
---------------------------
Error loading QGIS
---------------------------
Oops, looks like an error loading QGIS 

 Details: 

Could not load qgis_app.dll 
 Windows Error: The specified module could not be found.


 Help: 

 Check C:\Program Files\QGIS 3.7\bin\qgis-dev-bin-g.env for correct environment paths
---------------------------
OK   
---------------------------

```

**Comment by prusswan** [comment]
Yup, had to copy (and rename) the env file from 3.6 release

**Comment by alexbruy** [comment]
You need to install grass7 package to get it generated

**Comment by jef-n** [comment]
Should have been fixed with the next weekly…
