### ISSUE TITLE
Tool Icons disappear from menu

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29897]
Author Name: **Tyler Veinot** (Tyler Veinot)
Original Redmine Issue: [22084](https://issues.qgis.org/issues/22084)
Affected QGIS version: 3.4.7
Redmine category:gui

---
When I installed go2streetview the plugin had only a blank spot on the tool bar to run it, I thought this was an issue with the plugin and didn't think much of it. After installing SwapVectorDirection the go2streetview icon appeared but the SwapVectorDirection icon does not display. If I deactivate go2streetview the SwapVectorDirection icon will appear. I can still run the tools I just need to find the blankspot on the tool bar. Not sure if any onther plugins are afflicted by this.

---

- [missing_icons.png](https://issues.qgis.org/attachments/download/14947/missing_icons.png) (Tyler Veinot)

**Comment by alexbruy** [comment]
Please try with clean profile and no plugins installed. Then add plugins one by one to see which plugin causes issue.

**Comment by alexbruy** [comment]
Closed for the lack of feedback.
