### ISSUE TITLE
Use Z and M values at vertex and/or Attribute Value at feature for 3D Rendering

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29898]
Author Name: **Tyler Veinot** (Tyler Veinot)
Original Redmine Issue: [22085](https://issues.qgis.org/issues/22085)

Redmine category:3d

---
I would like to request the ability to use the Z and M values to render 3D features. Use case would be using Z and M values on a point to display a cylinder that starts at the Z value and extends down (or up) by the M value. Or displaying 3D lines based on their Z value at vertex, much like the options available in Qgis2threejs. Similar approach could be being able to use the attributes of a feature to identify the start and end elevation to display points or lines in much the same way. 

---

- [Screenshot_20190520_161125.png](https://issues.qgis.org/attachments/download/14961/Screenshot_20190520_161125.png) (Saber Razmjooei)

**Comment by wonder-sk** [comment]
The recent versions of QGIS respect Z coordinates when drawing 3D lines - you just need to enable "Render as simple 3D lines" checkbox. It has been discussed that this should probably become the default line rendering mode...
