### ISSUE TITLE
Export as TIFF from WMS reports success but nothing happens when leaving resolution values empty

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29891]
Author Name: **James Passmore** (@nmtoken)
Original Redmine Issue: [22078](https://issues.qgis.org/issues/22078)
Affected QGIS version: 3.6.1
Redmine category:unknown

---
As documented on https://gis.stackexchange.com/questions/322228/save-tiff-from-wms-layer-qgis-for-bhuvan-lulc

Exporting a TIFF from a WMS layer results in a log message saying 'Layer Exported: Successfully saved raster to ..." but no Tiff is exported.  Exporting a GeoPackage of the same layer to the the same location works.

Affects Windows versions of QGIS (QGIS 3.4.1 as per original question, and 3.6.1-Noosa)

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary,

**Comment by nmtoken** [comment]
Not sure how can't replicate on Linux, is a test against an issue reported by two people as occurring on Windows.  Not sure what other feedback is required

**Comment by gioman** [comment]
> As documented on https://gis.stackexchange.com/questions/322228/save-tiff-from-wms-layer-qgis-for-bhuvan-lulc

@nmtoken in the screenshot in the link above you can that the user has not set any resolution (pixels size or number of rows/columns) for the output, so I guess is normal that nothing is saved. Also the service only provides WGS84 as possible projection for the layers, this is not handy when it comes to choosing a resolution, so in the dialogue you may want to choose a different (i.e. projected) CRS for the output, this allows to choose a resolution in meters rather then degrees. I just retested the process, and it works.

**Comment by nmtoken** [comment]
> so I guess is normal that nothing is saved. 

But QGIS reports that a TIFF has been saved!  Shouldn't it report that no TIFF has been saved,  due to reason X,Y,Z

**Comment by gioman** [comment]
> But QGIS reports that a TIFF has been saved! Shouldn't it report that no TIFF has been saved, due to reason X,Y,Z

I agree that is not very friendly, but it is slightly different compared saying "export does not work". I'll change the subject and description accordingly.

**Comment by gioman** [comment]
The issue has changed, see https://github.com/qgis/QGIS/issues/41284#issuecomment-770471500
