### ISSUE TITLE
QGIS crashes on closing

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29907]
Author Name: **Karsten Tebling** (Karsten Tebling)
Original Redmine Issue: [22094](https://issues.qgis.org/issues/22094)
Affected QGIS version: 3.6.2
Redmine category:unknown

---
## User Feedback

QGIS crashed when I closed it while having 4 csv-files and one WMS open

## Report Details

*Crash ID*: 03dc7fee4fc9d39a290f3c5190fb31b9fcb2ed96

*Stack Trace*
```
QgsAuthManager::createConfigTables :
QgsAuthManager::configIds :
QgsAuthManager::configIds :
QgsAuthManager::defaultCertTrustPolicy :
QgsAuthMethodRegistry::operator= :
QMetaObject::activate :
QThread::finished :
QThread::currentThreadId :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

```

*QGIS Info*
QGIS Version: 3.6.2-Noosa
QGIS code revision: 656500e0c4
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by Meibes** [comment]
happened again, I'll send a test project next week

h2. User Feedback

.

h2. Report Details

*Crash ID*: 1b5a663a8bbe4361ea39227a8113041284aeaabb


*Stack Trace*
<pre>
QgsAuthManager::createConfigTables :
QgsAuthManager::configIds :
QgsAuthManager::defaultCertTrustPolicy :
QgsAuthMethodRegistry::operator= :
QMetaObject::activate :
QThread::finished :
QThread::currentThreadId :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>


*QGIS Info*
QGIS Version: 3.6.3-Noosa
QGIS code revision: commit:0c5774c068
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1



*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by gioman** [comment]
@Meibes please try with new/clean qgis profile.

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
