### ISSUE TITLE
GRASS Region Extent not shown in Batch Mode

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29900]
Author Name: **Pedro Venâncio** (Pedro Venâncio)
Original Redmine Issue: [22087](https://issues.qgis.org/issues/22087)
Affected QGIS version: 3.4.7
Redmine category:processing/grass
Assignee: Victor Olaya

---
When using Processing GRASS algorithms in batch mode, the GRASS_REGION_EXTENT_PARAMETER is not shown.

This happens in QGIS 3.4.7 and QGIS 3.6.2, but seems ok in 3.7 (master). 

To reproduce:

1. Run a GRASS algorithm. For instance, v.to.rast. In 'Advanced parameters' you see "GRASS GIS 7 region extent (xmin, xmax, ymin, ymax) [optional]".
2. Run the same algorithm as Batch Process.
3. Toggle to advanced mode.
4. The "GRASS GIS 7 region extent (xmin, xmax, ymin, ymax)" column is not shown.

**Comment by PedroVenancio** [comment]
Hi @volaya @nyalldawson 

This fix needs to be backported to 3.4 and 3.6.

**Comment by alexbruy** [comment]
Backported to 3.4
