### ISSUE TITLE
Dialog when removing not available layers

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29903]
Author Name: **Karsten Tebling** (Karsten Tebling)
Original Redmine Issue: [22090](https://issues.qgis.org/issues/22090)
Affected QGIS version: 3.6.2
Redmine category:gui

---
Hello,

if you open an existing project with some missing files and click on "remove not available layers" (or something like that, I use the german language) an Dialog opens that says all missing layers will be deactivated until the project will be reloaded, but if you click on OK, all missing layers will be removed from the project like the button implies. It could be a translation error or the Dialog opens on the wrong button. I think this Dialog should open if you click on X/Close?

**Comment by alexbruy** [comment]
Closing for the lack of feedback. Please reopen if necessary.
