### ISSUE TITLE
Panels not docking and some invisible

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29909]
Author Name: **neil walker** (neil walker)
Original Redmine Issue: [22096](https://issues.qgis.org/issues/22096)
Affected QGIS version: 3.6.2
Redmine category:gui

---
Hello,
Refer to my image.

1. The layers toolbar will not dock. Double clicking top bar does nothing. It works ok for all other panels, just not this one. It simply will not dock.
2. Observe the small grey block below the main toolbar. This is the Vector Toolbar. It will not undock, it will not resize. It used to work, then I dragged it from the side to the top and now it will not work.

Now, I cannot actually use this application...

tbh, as an aside, relying on a double click is a bit of a UI fail because it is not obvious or intuitive. A right-click with a dock/undock like almost all other applications would be much better.

thanks.

---

- [Untitled.png](https://issues.qgis.org/attachments/download/14949/Untitled.png) (neil walker)
- [Untitled2.png](https://issues.qgis.org/attachments/download/14950/Untitled2.png) (neil walker)

**Comment by Pedro-Murteira** [comment]
I can no longer replicate this bug on QGIS 3.16.14 and 3.22.1.
