### ISSUE TITLE
function as min, max, average is not available

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29914]
Author Name: **SC SC** (SC SC)
Original Redmine Issue: [22101](https://issues.qgis.org/issues/22101)

Redmine category:raster_calculator

---
Hi but raster calculator is not able to solve function as min or max
if with 3 or more raster I want to create a new raster with matrix of min of other raster I have to use grass or gdal

and this is not coherent with powerful field calculator for vector

**Comment by alexbruy** [comment]
Duplicated by #37716.
