### ISSUE TITLE
zonal histogram wrong

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29917]
Author Name: **yonghyun kim** (yonghyun kim)
Original Redmine Issue: [22104](https://issues.qgis.org/issues/22104)
Affected QGIS version: 3.4.8
Redmine category:processing/qgis

---
The zonal histogram is not generated by the raster band setting and the raster value is listed as the field value of the output.

For example, 
the raster band type is singleband pseudocolor,
rast value range = 0 ~ 100
band is classified by 5 (20, 40, 60, 80 ,100)
 
But oustput is stragne like below

----------------------
HISTO_10          int8   -1  0
HISTO_10.0033   int8   -1  0
HISTO_10.004     int8    -1  0
HISTO_10.0041   int8    -1  0
........
HISTO_100.0      int8    -1  0
----------------------------------------

Is it normal output? 
I expect this function is same  zonal histtogram in Arcgis

**Comment by nirvn** [comment]
When you say "is classified by 5", you mean the raster layer symbology settings? If so those two don't connect. If you want to get an histogram based on ranges of values, you'd have to reclassify your raster dataset first (either via the raster classifi ation alg or the raster calculator).

I'm closing this as invalid.
