### ISSUE TITLE
GRASS module v.to.rast  -- combobox to select label field only lists numeric fields

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29916]
Author Name: **Daan VAN SETTEN** (Daan VAN SETTEN)
Original Redmine Issue: [22103](https://issues.qgis.org/issues/22103)
Affected QGIS version: 3.7(master)
Redmine category:processing/grass

---
Hello - 

In GRASS module v.to.rast, the combobox "Name of column use as raster category labels" only proposes numeric fields.

However, for this field we would typically select a string type field

Thanks in advance, 

Daan

**Comment by alexbruy** [comment]
As far as I can see labels does not used in the Processing worklfow, so this field actually does nothing.
