### ISSUE TITLE
All menus and tables are magnified :/

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29927]
Author Name: **Shiva Raissi** (Shiva Raissi)
Original Redmine Issue: [22114](https://issues.qgis.org/issues/22114)
Affected QGIS version: 3.6.2
Redmine category:unknown

---
Hi,

Since yesterday, all menus and tables are magnified in QGIS. I tried uninstalling and reinstalling the application but that didn't solve the issue. I'm using the 3.6.2 version and didn't have this issue before updating to this version.

I would appreciate if someone can help me with this.

Thanks.

---

- [QGIS Bug.PNG](https://issues.qgis.org/attachments/download/14968/QGIS%20Bug.PNG) (Shiva Raissi)

**Comment by roya0045** [comment]
The fix should be to change the font size in the general settings, maybe its a wrong default but I don't see where else the error might come from.

**Comment by alexbruy** [comment]
Closing for the lack of feedback.
