### ISSUE TITLE
Name of layout for export

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29925]
Author Name: **Andrew Shanin** (Andrew Shanin)
Original Redmine Issue: [22112](https://issues.qgis.org/issues/22112)

Redmine category:map_composer/printing

---
Need add field in page 'Property of Element' for naming exporting page.

**Comment by jgrocha** [comment]
The default name of the exported PDF is the layout name. Are you asking for an additional field to have a different default name for the export? Can you explain better or provide a screenshot of want do you want?

**Comment by alexbruy** [comment]
Closed for the lack of feedback. Please reopen if necessary.

**Comment by chleidersdorff** [comment]
If you export a multi-page layout their names are just the layout name suffixed with a 2.3.4.....  it would be goo to be able to name the pages properly in multi-page layouts.
