### ISSUE TITLE
crashed when saving a few changes

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29932]
Author Name: **Alonso Acuna** (Alonso Acuna)
Original Redmine Issue: [22119](https://issues.qgis.org/issues/22119)
Affected QGIS version: 3.6.2
Redmine category:project_loading/saving

---
## User Feedback

crashed when saving a few changes

## Report Details

*Crash ID*: e3e9dc422a6d2f320711ed5f0a10ac180d98d1ed

*Stack Trace*
```
memcmp :
VSICreateCachedFile :
SASetupDefaultHooks :
SHPReadObject :
SHPPartTypeName :
SHPPartTypeName :
wildcards :
QgsAbstractFeatureIterator::nextFeature :
QgsVectorLayerFeatureIterator::fetchFeature :
QgsAbstractFeatureIterator::nextFeature :
QgsVectorLayerLabelProvider::registerFeature :
QgsVectorLayerLabelProvider::registerFeature :
QgsMapRendererCustomPainterJob::doRender :
QgsMapRendererCustomPainterJob::staticRender :
QgsMapRendererJob::renderingTime :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

```

*QGIS Info*
QGIS Version: 3.6.2-Noosa
QGIS code revision: 656500e0c4
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.3.9600

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
