### ISSUE TITLE
QGIS crashes on close on windows

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29939]
Author Name: **Jorge Suarez** (Jorge Suarez)
Original Redmine Issue: [22128](https://issues.qgis.org/issues/22128)
Affected QGIS version: 3.6.3
Redmine category:unknown

---
## User Feedback

only, close the software and show the crash 

## Report Details

*Crash ID*: 92c4d99fcfbe624f97eac76818dd383dafab23aa

*Stack Trace*
```
QgsRubberBand::QgsRubberBand :
QgsRubberBand::asGeometry :
QgsRubberBand::reset :
version :
QMetaObject::activate :
QDockWidget::visibilityChanged :
QDockWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::hideChildren :
QWidgetPrivate::hide_helper :
QWidget::setVisible :
QWidgetPrivate::close_helper :
QWidget::~QWidget :
CPLStringList::List :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

```

*QGIS Info*
QGIS Version: 3.6.2-Noosa
QGIS code revision: 656500e0c4
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
