### ISSUE TITLE
Sort inputs parameters in QGIS modeler

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29934]
Author Name: **Maxime RIOU** (Maxime RIOU)
Original Redmine Issue: [22121](https://issues.qgis.org/issues/22121)

Redmine category:processing/modeller

---
This refers to a question on GIS Stack exchange (https://gis.stackexchange.com/questions/322831/sort-inputs-parameters-in-qgis-modeler). 
I created a model in QGIS 3.6 with three inputs parameters (two vector layer and one vector field). When I run the model, the inputs are not sorted in a correct way: the vector field is requested before the vector layer.

I searched on previous feature requests and I found this #19944 but it is closed now.

It would be nice to choose the order of the inputs parameters. For example, if the input parameters are sorted in alphabetical order, the user could name inputs "1_inputXX, 2_inputYY, etc.". 

The proposed answer on GIS stackexchange is the following workaround :

Export Model as Python Algorithm to get a translated script of your model. Here you could order the parameters however you like in the 
```
initAlgorithm() function. E.g.:
def initAlgorithm(self, config=None):
    self.addParameter(QgsProcessingParameterFeatureSource('1conduites', '1_Conduites', types=[QgsProcessing.TypeVectorLine], defaultValue=None))
    self.addParameter(QgsProcessingParameterVectorLayer('2regard', '2_Regard', types=[QgsProcessing.TypeVectorPoint], defaultValue=None))
    self.addParameter(QgsProcessingParameterFeatureSource('3idregard', '3_ID_regard', types=[QgsProcessing.TypeVector], defaultValue=None)) 
    self.addParameter(QgsProcessingParameterFeatureSink('Result', 'result', type=QgsProcessing.TypeVectorPolygon, createByDefault=True, defaultValue=None))

```

**Comment by ghtmtt** [comment]
I'm not so sure this is a feature request or a small bug. Users can be quite confused by the sorting of the final dialog. Even if the user adds all the inputs in the correct order (i.e. first the vector layer, than the radius..), the final dialog does not take all this into account:

![image](https://user-images.githubusercontent.com/2884884/58932838-92737e80-8765-11e9-9284-a397f9f2b795.png)

![image](https://user-images.githubusercontent.com/2884884/58932891-c353b380-8765-11e9-9954-9f451cff5beb.png)

**Comment by nyalldawson** [comment]
@ghtmtt I think it's a request. The only correct way to fix this is to expose a new setting allowing users to manually set the order. Any auto-ordering we do is just trading bad sort order for another...

**Comment by alexbruy** [comment]
Duplicates #27787
