### ISSUE TITLE
crashes at start

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29930]
Author Name: **stefano loddo** (stefano loddo)
Original Redmine Issue: [22117](https://issues.qgis.org/issues/22117)
Affected QGIS version: 3.4.8
Redmine category:unknown

---
as soon as I launch QGIS 3.4 Madeira, it crashes at startup, every single time.
I tried uninstall it and manually delete remaining keys containing QGis in it 

This is the log fiel:

Crash ID: 61546722bd614632fe6392e62f31b92e76e4daf9

Stack Trace

RtlFreeHeap :
free :
DllUnregisterServer :
DllUnregisterServer :
CoGetTreatAsClass :
CoInitializeEx :
CoGetTreatAsClass :
CoGetTreatAsClass :
CoGetTreatAsClass :
CoGetTreatAsClass :
CoGetTreatAsClass :
CoGetTreatAsClass :
CoInitializeEx :
CoInitializeEx :
CoInitializeEx :
CoTaskMemRealloc :
CoTaskMemRealloc :
SHBindToParent :
Ordinal866 :
AssocCreateForClasses :
SHCreateQueryCancelAutoPlayMoniker :
SHCreateQueryCancelAutoPlayMoniker :
SHCreateQueryCancelAutoPlayMoniker :
SHCreateQueryCancelAutoPlayMoniker :
SHCreateQueryCancelAutoPlayMoniker :
Ordinal893 :
Ordinal211 :
SHILCreateFromPath :
Ordinal904 :
OpenRegStream :
OpenRegStream :
ILFree :
DllCanUnloadNow :
RtlGetNtProductType :
RtlFreeUnicodeString :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.4.8-Madeira
QGIS code revision: 04ee8e0761
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.3.9600

QGis is stand-alone installed and Windows 8.1 is on my PC

Thank you

**Comment by strk** [comment]
I also experienced crash on startup, see #31350 - closing this to continue there (more recent report)

**Comment by strk** [comment]
For the record, from #31350 we found that provider registry would also load plugins, even if you pass `--noplugins` to the qgis command, the recommendation is to move plugins away until you find which one is the offending one
