### ISSUE TITLE
Plugin processing: The plugin will be disabled because it crashed QGIS during last startup. Please report an issue and re-enable the plugin when the problem has been solved.

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29936]
Author Name: **Shamsuddeen Abdullahi** (Shamsuddeen Abdullahi)
Original Redmine Issue: [22125](https://issues.qgis.org/issues/22125)
Affected QGIS version: 3.6.3
Redmine category:processing/core

---
Plugin processing: The plugin will be disabled because it crashed QGIS during last startup. Please report an issue and re-enable the plugin when the problem has been solved. *Vector* option not working as a result of this

**Comment by alexbruy** [comment]
Not reproducible on latest master, 3.4 and 3.8

**Comment by CristoFacundoP** [comment]
Hi community,
I am experiencing the same issue (QGIS V.3.4) when calculating the standard deviation by r.series application form GRASS and was warned with the same message. I already uninstalled the version 3.4 and reinstalled it along with the 3.10. But the problem continues, whenever I activate the plugin the GUI is closed. In Options/Advaced/processing indicates that the last directory is located in C:/OSGeo4W64/apps/Python37 (not so sure it has to be with the problem)

**Comment by roya0045** [comment]
Do you have any custom script or any broken thing that could cause a crash upon loading?

**Comment by CristoFacundoP** [comment]
Well, I already uninstalled and installed QGIS to fix any custom script but still, the crashes persist.

**Comment by roya0045** [comment]
Uninstall and reinstall won't change a thing if the folder with the existing scripts are still there and simply get integrated on your new install.

**Comment by gioman** [comment]
> Uninstall and reinstall won't change a thing if the folder with the existing scripts are still there and simply get integrated on your new install.

@CristoFacundoP aka = create a new QGIS profile and try with it.

**Comment by shivanip157** [comment]
I have installed QGIS 3.12 and on using dissolved feature it crashed. After opening the GUI again it crashes saying, Plugins are disabled which crashes QGIS. Report the the issue and reinstall the plugin. 
Please help.

**Comment by arkarjun** [comment]
Please try this
Open Plugin manager Plugins> Manage install plugin
Go to Installed tab
Enable the Processing Toolbar and all necessary toolbars
Ok.

**Comment by naf140230** [comment]
I am having this issue with QGIS 3.18. When I try to resolve it in the plugin manager, it crashes.

**Comment by Gustry** [comment]
You should try with a new QGIS profile.
https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles

**Comment by naf140230** [comment]
It worked. The problem is solved.

**Comment by Gatsby-2019** [comment]
I have the same issue and the problem is solved when I deleted the python script which caused the problem in the first place from the processing dir (profiles\default\processing\script).
