### ISSUE TITLE
Unable to copy selected rows from attibute table while it is docked

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29945]
Author Name: **URIIT URIIT** (URIIT URIIT)
Original Redmine Issue: [22134](https://issues.qgis.org/issues/22134)
Affected QGIS version: 3.6.1
Redmine category:attribute_table

---
While the “Dock Attribute Table” button is pressed, it is not possible to copy all selected lines in the attribute table using the “Ctrl + c” key combination.
After undocking the attribute table, everything works fine.

![1.png](https://issues.qgis.org/attachments/download/14979/1.png)

---

- [1.png](https://issues.qgis.org/attachments/download/14979/1.png) (URIIT URIIT)

**Comment by sjdqbyitr178crs813tgbr8gsdufygeuy53** [comment]
This is not the only  "Ctrl + c" problem. Other shortcuts don't work either.

**Comment by sjdqbyitr178crs813tgbr8gsdufygeuy53** [comment]
Same issue: https://github.com/qgis/QGIS/issues/29633#issue-448452162

**Comment by nyalldawson** [comment]
Closed as duplicate
