### ISSUE TITLE
Slow Vector Layer Line Rendering Speed

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29943]
Author Name: **David MacNeil** (David MacNeil)
Original Redmine Issue: [22132](https://issues.qgis.org/issues/22132)
Affected QGIS version: 3.6.3
Redmine category:vectors

---
I've had layer rendering speed issues since going from 3.2 to 3.4 which continued on up to 3.6.3. The GPS traces in an 820 MB spatialite database take many times as long to draw as they used to.

Today I stumbled across a workaround for it by accident. When I reduced the line width from the default to 0.03 in order to render a high resolution png, the old performance level was restored. I could increase the line width to 0.13 without a performance hit, but 0.14 or higher and back to molasses.

I'm unsure if there is something special in general about the transition between line thickness at those numbers, or if it maybe be the thickness in my data at which the many parallel lines become wide enough to start overlapping.

**Comment by gioman** [comment]
Closing for lack of further feedback, please reopen if necessary.
