### ISSUE TITLE
qgis crashed in the background

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29941]
Author Name: **Karsten Tebling** (Karsten Tebling)
Original Redmine Issue: [22130](https://issues.qgis.org/issues/22130)
Affected QGIS version: 3.6.3
Redmine category:unknown

---
## User Feedback

qgis crashed in the background while I was using Firefox, I had one shapefile open, one non-permanent output and one WMS. I recently made a fresh install of qgis with purging all profiles, so this should somewhat be a clean install, I only have one plugin installed by now.

## Report Details

*Crash ID*: 7d29924f4829425ab791f7ff594e8177cc850b2c

*Stack Trace*
```
QMapDataBase::freeNodeAndRebalance :
QgsAuthMethodRegistry::operator= :
QMetaObject::activate :
QThread::finished :
QThread::currentThreadId :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

```

*QGIS Info*
QGIS Version: 3.6.3-Noosa
QGIS code revision: 0c5774c068
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by Meibes** [comment]
happend again, this time it crashed on closing with several wms open and one shapefile

Crash ID: 7d29924f4829425ab791f7ff594e8177cc850b2c


Stack Trace


QMapDataBase::freeNodeAndRebalance :
QgsAuthMethodRegistry::operator= :
QMetaObject::activate :
QThread::finished :
QThread::currentThreadId :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.6.3-Noosa
QGIS code revision: 0c5774c068
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601
