### ISSUE TITLE
Qgis 3.4 x64 windows version crashed when you run options at configuration

### ISSUE THREAD

**Issue by miggoncarlos** [qgis/QGIS#29988]
**Describe the bug**

**How to Reproduce**

**Desktop environment (please complete the following information):**

 - OS and version:

**QGIS version**

*Please add information available in QGIS menu help/about*

  - QGIS Version: [e.g. 3.4.5]
  - Full library versions:

**Additional context**

**Comment by miggoncarlos** [comment]
When you need to work in a internal red. You must to configurate the proxy, server, port, users and password, but in the new version of QGIS we cant do it. Thx

**Comment by gioman** [comment]
@miggoncarlos please add a detailed description to replicate the issue.

Also try with a new/clean QGIS profile, no 3rd party plugins installed.

**Comment by miggoncarlos** [comment]
> Also try with a new/clean QGIS profile, no 3rd party plugins installed

Thank you!! now we can open **configutarion>options**

**Comment by gioman** [comment]
> Thank you!! now we can open **configutarion>options**

@miggoncarlos no more crash?

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
