### ISSUE TITLE
Buttons to adjust marker size in the digitizing tab of the general settings dialog not working

### ISSUE THREAD

**Issue by MieWinstrup** [qgis/QGIS#29987]
**Describe the bug**
The buttons to adjust marker size in the digitizing tab of the general settings dialog does not work - the size is not changed when clicking on the adjust size buttons next to the number:

![image](https://user-images.githubusercontent.com/16276034/58477052-e0c7c280-8152-11e9-8b6f-f2db17ace032.png)

The size can be adjusted by entering the desired size in the numberfield - hence, without using the buttons.

**How to Reproduce**

1. Click on the Settings menu
2. Click on 'Options'
3. Click on the 'Digitizing'-tab
4. Try to adjust the size of the vertex markers - by using the button to adjust the size.

**Desktop environment (please complete the following information):**

 - OS and version: Windows

**QGIS version**

*Please add information available in QGIS menu help/about*

  - QGIS Version: 3.4.8
  - Full library versions:
![image](https://user-images.githubusercontent.com/16276034/58477312-7ebb8d00-8153-11e9-8354-66604b20994f.png)

**Additional context**

**Comment by gioman** [comment]
also on master.
