### ISSUE TITLE
Crashed when adding field to a new non spatial scratch layer

### ISSUE THREAD

**Issue by traficus** [qgis/QGIS#29990]
h2. User Feedback

I hat a new "scratch" layer opened. Pressed "add feature". Then added one field, gave a name in (integer 7 spaces) then pressed again to add another fields (same int 7). And then it crached.

h2. Report Details

Crash ID: 96b9cf8d706a65126198f6ecf4529169527460e9

Stack Trace

memcpy :
QSequentialAnimationGroup::qt_metacast :
QSortFilterProxyModel::buddy :
QSortFilterProxyModel::removeRows :
QSortFilterProxyModel::sortRole :
QSortFilterProxyModel::`default constructor closure' :
QMetaObject::activate :
QAbstractItemModel::beginRemoveRows :
QgsAttributeTableModel::removeRows :
QgsAttributeTableModel::loadLayer :
QMetaObject::activate :
QMetaObject::activate :
QgsVectorLayer::updateFields :
QgsVectorLayerUndoCommandAddAttribute::redo :
QUndoStack::push :
QgsVectorLayerEditBuffer::addAttribute :
QgsAttributeTableDialog::mActionAddAttribute_triggered :
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
DispatchMessageW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
QGIS Info
QGIS Version: 3.6.3-Noosa
QGIS code revision: commit:0c5774c068
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by gioman** [comment]
@traficus please try with a new/clean QGIS profile, no 3rd party plugins installed.

**Comment by traficus** [comment]
Is it possible to do it with reinstalling the software? Is there any way to 'reset' the profile?

**Comment by wonder-sk** [comment]
@traficus yes you can go add a new clean profile in Settings > User Profiles > New Profile

Are you able to reproduce the crash again? If yes, it would be good to have exact steps what you did - I am unable to reproduce.

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
