### ISSUE TITLE
QGIS 3.6 win64 crashes when openning the 3D Viewer

### ISSUE THREAD

**Issue by zxmuq74** [qgis/QGIS#30009]
**Describe the bug**
I didn't make much. I have a project with a DEM and I wanted to generated a 3D model from it. I saw that I could use a 3D Viewer from QGIS as the ArcScene  from ArcGis. However when I tryto open the new 3D Map View, it crashes the system and close the project. 
One point that may be problematic, I am not sure, it is that my project is in Grauss Kruger and not in UTM. 

Crash ID: 472a7d63042ab2fd3872d8ad86730dc67b260847
Stack Trace
OpenAdapter10_2 :
OpenAdapter10_2 :
OpenAdapter10_2 :
DrvPresentBuffers :
DrvPresentBuffers :
DrvPresentBuffers :
DrvPresentBuffers :
DrvPresentBuffers :
BaseThreadInitThunk :
RtlUserThreadStart :

**How to Reproduce**
Load test data (a raster)
Start the New 3D Map View
Enable 3D renderer in the Layer Styling Panel
The crash report window will open.
QGIS Main window does not respond.

**Desktop environment (please complete the following information):**

 - OS and version:
System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**QGIS version**
QGIS Info
QGIS Version: 3.6.0-Noosa
QGIS code revision: 58734527ab
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.0
Running against GDAL: 2.4.0

I'm sorry, but I'm still a little bit confuse about which kind of infos should I add more.

**Comment by gioman** [comment]
@zxmuq74 regardless of the data used?

**Comment by wonder-sk** [comment]
Please add information about QGIS version and your OS. Also please attach a simple project that causes a crash.

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
