### ISSUE TITLE
Raster image marker doesn't work with relative paths to the file

### ISSUE THREAD

**Issue by tudorbarascu** [qgis/QGIS#30002]
**Describe the bug**

When adding a raster image marker, if I enter the full path to the gif the marker is shown, while if I enter a relative path it doesn't work. Curiously, in the QGIS project, the marker location gets saved with the relative path, e.g. ``<prop k="imageFile" v="./icons/jack0.gif"/>`` and opening the project again works. As soon as I put manually the relative path ``'./icons/jack0.gif'`` right here:
![bug1](https://user-images.githubusercontent.com/3179646/58555449-2e5f3080-8222-11e9-9b01-ec0bfccc352f.png)

 OR  in the data defined override, it doesn't work anymore.

**How to Reproduce**
I've attached a test project:
[bug_raster_image_marker.zip](https://github.com/qgis/QGIS/files/3232303/bug_raster_image_marker.zip)

To reproduce open the test project, and in the dialog where you chose the path to the marker, in the data defined part enter ``'./icons/jack0.gif'``.

Bug present

**Desktop environment (please complete the following information):**

 - OS and version:
Debian Buster
**QGIS version**
QGIS 3.7 Master, commit https://github.com/qgis/QGIS/commit/a871e90a2b
*Please add information available in QGIS menu help/about*
```

QGIS version | 3.7.0-Master | QGIS code revision | a871e90a2b
-- | -- | -- | --
Compiled against Qt | 5.11.3 | Running against Qt | 5.11.3
Compiled against GDAL/OGR | 2.4.0 | Running against GDAL/OGR | 2.4.0
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
PostgreSQL Client Version | 11.3 (Debian 11.3-1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.10.4
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
This copy of QGIS writes debugging output.
```

**Comment by wonder-sk** [comment]
I think for data-defined file path you should use something like `@project_home || '/icons/jack0.gif'` instead (tested and that works for me).

The edit box with image path is meant to have absolute path in it.

Generally speaking, relative paths are only used when saving .qgs/.qml files, but as soon as the files are loaded, relative paths are turned into absolute paths.

For convenience I can imagine that if user would type in / paste a relative path and project path is known, it could be expanded to full path - but I would classify that as a new feature :-)

**Comment by tudorbarascu** [comment]
@wonder-sk Thanks for the info! I had already found the solution you mention and it works real fine. I just had other expectations as for other markers (e.g. SVG it works). 
I'll close this.
Thanks again!
