### ISSUE TITLE
DB Manager: unable to connect to Postgresql using pg_services

### ISSUE THREAD

**Issue by jgrocha** [qgis/QGIS#30027]
**Describe the bug**

I have a shared project, so users connect to PostgreSQL using pg_services. The connection works well on all computers. Everybody is able to use the layers from PostgreSQL.

But the DB Manager is not able to connect to the database on WINDOWS. 

![image](https://user-images.githubusercontent.com/163681/58629750-3b892780-82d5-11e9-8f65-e8d75ec52f2c.png)

It works well on Ubuntu.

It seems to be Python related, since the cpp connection works well.

Running the following Python code (on the QGIS console):

```python
import psycopg2

print (psycopg2.__version__)
connection = psycopg2.connect(service='pg_trabalho')
# connection = psycopg2.connect(user = "cmb.user", password = "xxxxxxx", host = "192.168.1.24", port = "5432", database = "trabalho")
cursor = connection.cursor()
print ( connection.get_dsn_parameters(),"\n")
cursor.execute("SELECT version();")
record = cursor.fetchone()
print("Connected to - ", record,"\n")
```

works well in Ubuntu, but not on Windows. Both works well, if pg_services are not used.

Error on Windows:
```
2.7.5 (dt dec pq3 ext lo64)
Traceback (most recent call last):
  File "C:\OSGEO4~1\apps\Python37\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "<string>", line 4, in <module>
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\psycopg2\__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "192.168.1.24
" to address: Unknown host
```

The pg_services.conf file has:
```
[pg_trabalho]
host=192.168.1.24
port=5432
dbname=trabalho
```

Both `psycopg2` exists on Ubuntu and on Windows, and both report the same version:
`2.7.5 (dt dec pq3 ext lo64)`

I don't understand why QGIS native connection (cpp code) works, but not Python code. It seems related to the hostname resolution, but isn't it the same for cpp or python?

**How to Reproduce**

1. Create a connection to Postgresql using pg_services
2. Create a new connection and connect: it works!
3. Go to DB manager and try to connect: it does not work.

**Desktop environment (please complete the following information):**

 - OS and version: Windows 10 Pro

**QGIS version**

QGIS 3.6.1, without plugins installed.

![image](https://user-images.githubusercontent.com/163681/58631260-ec91c100-82d9-11e9-8ff2-0b321d212eb7.png)

**Additional context**

**Comment by Gustry** [comment]
I also got some issues with 3.4 on Windows with service file. 

First, the file must be Linux line ending, even if it's on Windows. It was not working with Windows line ending on Windows ! I could notice an extra character at the end in the error message.

Then, the file could be recognized in the browser, but I got some issues in the DB Manager too.

Everything is working fine on Linux (both browser and DB Manager)

@jgrocha I notice in your code:
```bash
psycopg2.OperationalError: could not translate host name "192.168.1.24
" to address: Unknown host
```

Maybe it's just github, but why your code goes to a new line after `24`? Is it also a Windows/Linux line ending issue?

**Comment by jgrocha** [comment]
I've [reported the bug upstream](https://github.com/psycopg/psycopg2/issues/926), at the psycopg2 repository. It seems to me that the error is upstream, not in QGIS. Let's see if we can get some feedback from psycopg2 developers to decide if this a specific DB Manager bug or upstream.

**Comment by jgrocha** [comment]
The issue on [`psycopg2`](https://github.com/psycopg/psycopg2/issues/926) was immediately closed, so I report it on the postgresql [psql-bugs](https://www.postgresql.org/message-id/15827-e6ba53a3a7ed543c%40postgresql.org) mailing list.

The issue is related to Python. On Windows, using the `psql` (from OSGeo4W) the `pg_services` works.

![psql service pg_trabalho](https://user-images.githubusercontent.com/163681/58747605-6f935280-8465-11e9-8f85-9ef4e394f565.jpg)

**Comment by jgrocha** [comment]
I've created a Windows machine running on VirtualBox. `pg_services` works fine (using `psql` or `psycopg2`)

![qgis pg_services success windows](https://user-images.githubusercontent.com/163681/58750625-c1030800-848c-11e9-8d54-d591d490d1e8.png)

I was not able to reproduce the error, using a different `psycopg2` version (2.7.3 instead of 2.7.5). I need further investigation. I'll try to run this virtual machine in the same network where the error was reported.

**Comment by jgrocha** [comment]
It is difficult to identify where the problem is.

I'm using this code to get library versions:

```python
import psycopg2
print (psycopg2.__version__)
print (psycopg2.__libpq_version__)
```

Right now I have several Windows 10 machines that crash when connect with `service=something`, some running QGIS 3.4 and a few running QGIS 3.6. All have the same `psycopg2` and `libpq` version.

```
psycopg2.__version__ =  2.7.5 (dt dec pq3 ext lo64)
psycopg2.__libpq_version__ = 100004
```

I have another Windows 10 machine (my Virtual machine), on the same network, accessing the same database, without any problem, running QGIS 3.2.3-Bonn.

```
psycopg2.__version__ = 2.7.3.2 (dt dec pq3 ext lo64)
psycopg2.__libpq_version__ = 100000
```

In both machine, the Windows name resolution has default values.

Right now, I have no clue where the problem is.

**Comment by lbartoletti** [comment]
@jgrocha Is your file have UNIX return line format (https://qgep.github.io/docs/installation-guide/workstation.html#windows-pg-service) ? AFAIK it's required even for windows.

**Comment by andreasneumann** [comment]
yes - only Unix line endings are allowed. Windows line endings just do not work (without a meaningful error message).

**Comment by jgrocha** [comment]
This problem seems to be related with DB Manager. Python code is running fine outside QGIS.

As I said before, this problem only happens on a specific organization (where all computers are Windows 10 with some security constraints).

This piece of code:
```python
import psycopg2

print (psycopg2.__version__)
connection = psycopg2.connect(service='pg_trabalho')
# connection = psycopg2.connect(user = "cmb.user", password = "xxxxxxx", host = "192.168.1.24", port = "5432", database = "trabalho")
cursor = connection.cursor()
print ( connection.get_dsn_parameters(),"\n")
cursor.execute("SELECT version();")
record = cursor.fetchone()
print("Connected to - ", record,"\n")
```

Works well on OSGeo4W shell

![ok in OSGeo4W shell](https://user-images.githubusercontent.com/163681/59433373-48337280-8de1-11e9-9765-919083db473d.JPG)

Does NOT WORK on QGIS.

![error in QGIS](https://user-images.githubusercontent.com/163681/59433382-4e295380-8de1-11e9-883a-307f126d453f.JPG)

I'll start looking at the code...

**Comment by m-kuhn** [comment]
I can't get rid of the impression that it's about the line endings. Looking at your screenshot, there's a linebreak after the ip which looks suspiciously like the source of trouble.

Since it seems to be working from outside QGIS, it might be related to some environment settings inside QGIS that makes libpq use a different pg_service.conf file?

**Comment by jgrocha** [comment]
> I can't get rid of the impression that it's about the line endings. Looking at your screenshot, there's a linebreak after the ip which looks suspiciously like the source of trouble.
> 
> Since it seems to be working from outside QGIS, it might be related to some environment settings inside QGIS that makes libpq use a different pg_service.conf file?

pg_services are working using QGIS (cpp code) and also runs fine in Python, using OSGeo4W shell. If the line endings was a problem, pg_services would fail everywhere. I think that only libpq is reading the file.

pg_services are failing just inside DB Manager (or QGIS Python console).

The DB Manager connection runs inside try .. except.

From https://github.com/qgis/QGIS/blob/3a0fb544b33581e96ab4ae5486722aeff426817e/python/plugins/db_manager/db_plugins/postgis/connector.py#L66

```python
        try:
            self.connection = psycopg2.connect(expandedConnInfo)
        except self.connection_error_types() as e:
```

I'm trying to replicate DB Manager connection procedure step by step, but I'm not able to catch the exception and handle it. QGIS crashes.

**Comment by jgrocha** [comment]
> I can't get rid of the impression that it's about the line endings. Looking at your screenshot, there's a linebreak after the ip which looks suspiciously like the source of trouble.
> 
> Since it seems to be working from outside QGIS, it might be related to some environment settings inside QGIS that makes libpq use a different pg_service.conf file?

### Line endings

As @Gustry, @lbartoletti, @andreasneumann said, line endings is a problem. I've looked at the `src/interfaces/libpq/fe-connect.c` code, and it is an easy fix. I've created and submitted a patch to `pgsql-bugs@lists.postgresql.org`. Let's see if it is possible to fix this issue upstream.

### Environment variables

@m-kuhn Nice catch! I need further debug, but by forcing the environment variable in QGIS console, I was able to get the correct `pg_service.conf` file. That was a victory! I'll need further debug to understand why user's environment variables are not available in QGIS console (in this specific Windows network).

So, this code works inside QGIS:
```python
import psycopg2
import os
os.environ['PGSERVICEFILE'] = 'c:\\Users\\ana.fernandes\\linux_pg_services.conf'
connection = psycopg2.connect(service='pg_trabalho')
cursor = connection.cursor()
print ( connection.get_dsn_parameters(),"\n")
cursor.execute("SELECT version();")
record = cursor.fetchone()
print("Connected to - ", record,"\n")
```

**Comment by jgrocha** [comment]
In the [psycopg2 issue](https://github.com/psycopg/psycopg2/issues/926) thread, @jerickso has pointed out that we are (in QGIS [main.cpp](https://github.com/qgis/QGIS/blob/master/src/app/main.cpp#L489)) changing the default behaviour of `fopen` in Windows, forcing it to use binary mode.

If `fopen` is called in binary mode, in WIndows, `\r` characters are not discarded. Probably that is why we can not read `pg_services.conf` files with `\r` in Windows.

I'll need some time to setup a virtual machine to compile QGIS using MSC.

More debug is needed!

**Comment by luipir** [comment]
> I'll need some time to setup a virtual machine to compile QGIS using MSC.

you can cross compile using MXE (@elpaso have a build chaing for that) but I think you do not have python available :/

**Comment by luipir** [comment]
sorry I closed by mistake

**Comment by jgrocha** [comment]
> > I'll need some time to setup a virtual machine to compile QGIS using MSC.
> 
> you can cross compile using MXE (@elpaso have a build chaing for that) but I think you do not have python available :/

@luipir Do you know how QGIS Windows release is compiled?

Maybe @jef-n can tell us exactly how QGIS is being compiled for Windows. If I can do the same for debug, it would be perfect.

I need to compile QGIS using MSC. The `fgets` standard function has a different behaviour if compiled with MSC. In MSC, `fgets` automatically discards `\r` characters, if the file is opened in text mode.

We also have conditional code compilation based on the compiler, like:

```c
#ifdef WIN32  // Windows
#ifdef _MSC_VER
  _set_fmode( _O_BINARY );
#else //MinGW
  _fmode = _O_BINARY;
#endif  // _MSC_VER
#endif // WIN32
```

**Comment by jef-n** [comment]
> Maybe @jef-n can tell us exactly how QGIS is being compiled for Windows. If I can do the same for debug, it would be perfect.

ms-windows/osgeo4w/package.cmd or ms-windows/osgeo4w/package-nightly.cmd

> I need to compile QGIS using MSC. The `fgets` standard function has a different behaviour if compiled with MSC. In MSC, `fgets` automatically discards `\r` characters, if the file is opened in text mode.

> We also have conditional code compilation based on the compiler, like:
> 
> ```c
> #ifdef WIN32  // Windows
> #ifdef _MSC_VER
>   _set_fmode( _O_BINARY );
> #else //MinGW
>   _fmode = _O_BINARY;
> #endif  // _MSC_VER
> #endif // WIN32
> ```

And that's causing the problem with the service file - there are probably tickets mentioning this - and the problem that we don't have a good handle on this - because not using that flag (or used to?) breaks other stuff and the reading of the service file is done from within libpq (it might be even dependent on whether QGIS and libpq use the same version of msvcrt - but using "true" line breaks in the service file works in every case).

**Comment by jgrocha** [comment]
**Good news.** No more line ending issues on `pg_service.conf` in QGIS. This issue was solved at libpq level by the following [commit](https://github.com/postgres/postgres/commit/b654714f9bcfb4443bcc531c32f059fd85f798ec). Kudos for the Postgresql team (Tom Lane and Michael Paquier).

Thank you for all comments on this issue. Without your help I would be able to isolate the problem.

We still have to see how to avoid opening all files in binary mode in Windows. _This issue was solved upstream, but the problem was only in QGIS._

**Comment by jgrocha** [comment]
Fix is already being distributed: https://www.postgresql.org/about/news/1960/

```
Make libpq ignore the \r carriage return in connection service files, which was causing connection failures in some edge cases.
```

**Comment by andreasneumann** [comment]
Nice!

**Comment by m-kuhn** [comment]
Good job @jgrocha :+1: !
