### ISSUE TITLE
Closing Vertex Edititor crashes the app.

### ISSUE THREAD

**Issue by arawakarawak** [qgis/QGIS#30028]
Closing the Vertex Editor panel cause QGIS crash.
This however happens **only when the panel is not docked** (is free floating).

**How to Reproduce**

1. Make a vector layer editable
2. Use Vertex Tool (Vertex Editor panel appears docked; IDK if this is a default behavior)
3. On Vertex Editor panel click the resize icon (in upper-right corner); the panel gets undocked.
4. Click Close icon (x) on the panel: the app crashes immediately.

Position of the panel relative to other windows and panels seems irrelevant. 

**Desktop environment:**

 - OS and version: Win 7 Home Premium SP1
**Dual screen workspace** (this may be important).

**QGIS version**
- 3.6.3

**Additional context**
I had other issues with GUI - probably related to dual screen workspace - like crashing when a panel was dragged over a map window on secondary monitor (https://github.com/qgis/QGIS/issues/29928)

**Comment by PeterPetrik** [comment]
can be reproduced on MacOS without dual screen
