### ISSUE TITLE
Expression dialog doesn't show "Fields and Values" list.

### ISSUE THREAD

**Issue by antoforest** [qgis/QGIS#30034]
Expression dialog on Attributes Forms>Default value doesn't show "Fields and Values" list. The list is empty. 
It is not so instead for expression dialog in costraints. In this case the "Fields and Values" group
shows all layers's fields correctly.
Also in Field Calculator the "Fields and Values" group is ok.
I tried with others layer and I tested also with a new clean profile but the issue remains.

**Desktop environment :** 

 - OS and version: Windows 10 Pro vers. 1803

**QGIS version**

*Please add information available in QGIS menu help/about*

  - QGIS Version: 3.6.3
  - Full library versions:

**Comment by nyalldawson** [comment]
This is not a bug - field values are not available when a feature is first created and default values are calculated. They'd all be null!

**Comment by antoforest** [comment]
Yes, I know it and I agree with you but maybe I was not so clear.
I can't compose expression to calculate **default value** because "Fields and Values" group is empty
![default](https://user-images.githubusercontent.com/47451311/58692638-4c966f00-838f-11e9-95f6-893b81d2209d.jpg)
In **costraints>expression**  the same group "Fields and Values" instead shows all fields name
![costraints](https://user-images.githubusercontent.com/47451311/58693066-3a690080-8390-11e9-83b4-ec40bf5f16dc.jpg)

I hope I have explained the issue better.
Thank in advance

**Comment by nyalldawson** [comment]
Yes, that's because constraints are evaluated after fields are created, so they have a value. Default values are evaluated **before** fields even exist, so fields have no value.

**Comment by antoforest** [comment]
ok. thank you
