### ISSUE TITLE
QGIS Server layers (WMS) do not render above zoom level 20 in leaflet or open layers

### ISSUE THREAD

**Issue by NyakudyaA** [qgis/QGIS#30031]
**Describe the bug**
I have setup qgis server using various docker images notably `camptocamp/qgis-server` and `3liz/qgis-map-server`. However when I render my wms layers from leaflet they do not show anything past zoom level 18

**How to Reproduce**

1. Run the following docker command `docker run -d -p 8080:8080 --restart=unless-stopped --name "3liz" -v `pwd`/project-qgis3:/projects -e QGSRV_SERVER_WORKERS=20 -e QGSRV_CACHE_ROOTDIR=/projects -e QGSRV_CACHE_SIZE=100 3liz/qgis-map-server:3.6`
2. In QGIS add a WMS connection pointing to `http://localhost:8080/ows/?map=project.qgs`
3. Add the layer in QGIS and use the plugin Qgis2web to export and html either leaflet or open layers with the zoom level set to be > 21
4. When you render the wms layer above zoom level 19 nothing appears there.

[project-qgis3.zip](https://github.com/qgis/QGIS/files/3237440/project-qgis3.zip)

Visible extent
![zoom](https://user-images.githubusercontent.com/2510900/58640170-ca5b6b80-82f8-11e9-8ff0-dca578c86a1d.png)

Not visible
![empty](https://user-images.githubusercontent.com/2510900/58640213-e3641c80-82f8-11e9-9beb-7dc90824386a.png)

**Desktop environment (please complete the following information):**

 - OS and version:
Ubuntu 18.04
Docker version 18.09.5, build e8ff056

**Comment by gioman** [comment]
@NyakudyaA does it happens only leaflet as client? what if you use another wms client (i.e. QGIS or other Desktop GIS) can you see the layers once you pass that specific scale?

**Comment by NyakudyaA** [comment]
@gioman It happens either using leaflet/open layers and QGIS

**Comment by gioman** [comment]
@NyakudyaA you sure that the qgis project is not set to not show the layers above that scale?

**Comment by NyakudyaA** [comment]
I have investigated this and I think there is nothing wrong with QGIS. 

`leaflet.wms.js` has the zoom levels default from 0 - 18 and even changing them does not fix this.
![leaflet](https://user-images.githubusercontent.com/2510900/69490766-c5850800-0e94-11ea-92bd-307efad70bc2.png)
