### ISSUE TITLE
[Python] Labelling for linestring are rendered after 

### ISSUE THREAD

**Issue by lbartoletti** [qgis/QGIS#30046]
**Describe the bug**

We use a python script to add labels and it works for all geometries except linestring where labels are not displayed until we modify the labeling properties.

![label_python](https://user-images.githubusercontent.com/7521540/58709329-3a7df600-83ba-11e9-9e35-6bed53c42d5c.gif)

**How to Reproduce**

1. Add a line
2. Execute this python script:

```
pal_layer = QgsPalLayerSettings()
pal_layer.fieldName = iface.activeLayer().fields()[0].name()
pal_layer.enabled = True

labeler = QgsVectorLayerSimpleLabeling(pal_layer)

iface.activeLayer().setLabeling(labeler)
iface.activeLayer().setLabelsEnabled(True)
print(iface.activeLayer().labelsEnabled())
# not necessary
iface.activeLayer().triggerRepaint()
```

**QGIS and OS versions**

All 3.X versions and OS 

**Additional context**

Initial problem reported from https://github.com/Oslandia/labelconnector/issues/13

**Comment by nyalldawson** [comment]
Check the label placement option -- the default is not applicable/usable for line layers.

e.g. 

    pal_layer.placement = QgsPalLayerSettings.Curved

**Comment by lbartoletti** [comment]
@nyalldawson Thank you. You're right, the default is not applicable for line layers. Shouldn't we propose a(n alternate) default for linestring too?

**Comment by nyalldawson** [comment]
@lbartoletti can you elaborate?

**Comment by lbartoletti** [comment]
@nyalldawson 
You said `the default is not applicable/usable for line layers` (is the default is` QgsPalLayerSettings::AroundPoint`?)

So, if it's possible - I don't know this part of QGIS code - add a conditional default something like : 
`mDefaultPlacementMember ( layer->.geometryType() == QgsWkbTypes::LineGeometry ? QgsPalLayerSettings.Curved : QgsPalLayerSettings::AroundPoint )`

But really don't know if this will change something for the python api.

Well, for my part, I consider that the problem is solved because it is a problem of using the python api.
