### ISSUE TITLE
GRASS 7 (7.6.1) is not been "detected" properly by QGIS-LTR (3.4.7-1) on [Arch Linux]

### ISSUE THREAD

**Issue by fvguilherme** [qgis/QGIS#30049]
**Describe the bug**

GRASS 7 (7.6.1, to be precise) is not been "detected" properly by QGIS-LTR (3.4.7-1) on Arch Linux. I mean, QGIS comes with a GRASS provider already installed, right? Well. Previously, the provider's algorithms simply did not work. After installing GRASS, a new provider appeared and the algorithms were provided with their proper descriptions.

Although the above mentioned provider still exists, the difference is that, now, when installing GRASS, a new GRASS provider does not appear and the provider algorithms that accompany the QGIS start working, but without the proper descriptions.

I've noticed, too, that I am not able to edit GRASS provider folder and that GRASS doesn't appear on the Plugin menu. I read #29494 and related, but that doesn't apply to me, since I am on Linux.

**How to Reproduce**

1. Install QGIS-LTR 3.4.7-1;
2. Try to use GRASS algortithms (to see that they doesn't work);
3. Install GRASS 7.6.1;
4. Try again step 3.

**QGIS and OS versions**

OS: Arch Linux x86_64 
Kernel: 5.1.5-arch1-2-ARCH 

Versão do QGIS | 3.4.7-Madeira | Código de ramificação QGIS | Release 3.4
-- | -- | -- | --
Compilado sobre Qt | 5.12.3 | Rodando sobre Qt | 5.12.3
Compilado sobre GDAL/OGR | 2.4.1 | Rodando sobre GDAL/OGR | 2.4.1
Compilado sobre GEOS | 3.7.1-CAPI-1.11.1 | Rodando sobre GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Versão do cliente PostgreSQL | 11.3 | Versão SpatiaLite | 4.3.0a
Versão do QWT | 6.1.4 | Versão QScintilla2 | 2.11.1
Compiled against PROJ | 520 | Running against PROJ | 5.2.0

**Comment by jef-n** [comment]
The grass provider requires GRASS libraries.  The GRASS algorithms in processing just call GRASS tools  - so those need GRASS too.  But we don't package for Arch, so this should be reported there.

**Comment by fvguilherme** [comment]
I think that all libraries required are installed. I've tested on Windows and I observed the same behavior. Isn't exclusive from Linux package, is it?

**Comment by fvguilherme** [comment]
I think that all libraries required are installed. I've tested on Windows and I observed the same behavior. Isn't exclusive from Linux package, is it?

**Comment by fvguilherme** [comment]
I think that all libraries required are installed. I've tested on Windows and I observed the same behavior. Isn't exclusive from Linux package, is it?

**Comment by fvguilherme** [comment]
> The grass provider requires GRASS libraries. The GRASS algorithms in processing just call GRASS tools - so those need GRASS too. But we don't package for Arch, so this should be reported there.

I think that all libraries required are installed. I've tested on Windows and I observed the same behavior. Isn't exclusive from Arch package, is it?

**Comment by neteler** [comment]
> The grass provider requires GRASS libraries. The GRASS algorithms in processing just call GRASS tools - so those need GRASS too. But we don't package for Arch, so this should be reported there.

For the record:
https://aur.archlinux.org/packages/grass/

**Comment by pmav99** [comment]
@fvguilherme AFAIK there are 3 packages providing qGIS on Arch:

- [qgis](https://www.archlinux.org/packages/community/x86_64/qgis/) which is an official package and which does not get compiled with GRASS support ([source](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/qgis)).
- [qgis-ltr](https://aur.archlinux.org/packages/qgis-ltr/) which is an AUR package and which does not get compiled with GRASS support ([source](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=qgis-ltr)). 
- [qgis-git](https://aur.archlinux.org/packages/qgis-git/) which is an AUR package and which get compiled with GRASS support ([source](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=qgis-git#n79)).

So, if you want to use GRASS from within QGIS you have two options:

1. install GRASS [from AUR](https://aur.archlinux.org/packages/grass/) and then install `qgis-git` 
2. Compile from source.

**Comment by fvguilherme** [comment]
Weird. I have always used `qgis-ltr` and GRASS from AUR without problems. On Windows I faced this problem, too. GRASS 7.6.1 has fixed the problem, but on Arch doesn't fixed. I have install both `qgis` and `qgis-ltr` packages with GRASS 7.6.1 from [here](https://github.com/czka/AUR-grass7/blob/master/PKGBUILD), but doesn't works. Maybe a PKGBUILD problem?

**Comment by fvguilherme** [comment]
yes, GRASS + `qgis-git` work properly. Thank you. 

I think that GRASS 7.6.1 will fix the problem with `qgis-ltr` package.
