### ISSUE TITLE
Problem with ParameterFile in batch mode

### ISSUE THREAD

**Issue by crocovert** [qgis/QGIS#30058]
Hello,

I use QGis 3.6.3 in windows
I've a script that use a ParameterFile to select a folder (QgsProcessingParameterFile.Folder option in the self.addParameter function)
It works well in normal mode, but crashed in batch mode.
Here is the error message displayed

AttributeError: 'NoneType' object has no attribute 'setParameterValue' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.6/apps/qgis/./python/plugins\processing\gui\BatchPanel.py", line 183, in load
    wrapper.setParameterValue(value, context)
AttributeError: 'NoneType' object has no attribute 'setParameterValue'

It worked with the previous versions of  Qgis  (3.6.2 or 3.61)

Thanks

**Comment by gioman** [comment]
@crocovert please try if the problem persist in the latest master release.

**Comment by crocovert** [comment]
Hello,

It works with the latest master release

Thanks

Best regards

Patrick PALMIER
Responsable du groupe Mobilités et Territoires
tél:+33 (0)3 20 49 60 70
mob:+33 (0)7 77 34 25 07
<cerema_html_7f500ad39ffdff4e.png>

Centre d’études et d’expertise sur les risques, l’environnement, la 
mobilité et l’aménagement - *www.cerema.fr*
Direction territoriale Nord-Picardie – 44 terrue Jean Bart -CS 20275 - 
59019 Lille Cedex
Siège social : Cité des Mobilités - 25 avenue François Mitterrand - CS 
92 803 - 69674 Bron Cedex - tél : +33 (0)4 72 14 30 30
