### ISSUE TITLE
Drag and drop geopackage from filesystem into map misses vector layers, loses names for raster layers

### ISSUE THREAD

**Issue by Llaves** [qgis/QGIS#30050]
**Describe the bug**
If you drag and drop a geopackage from the filesystem to the legend pane only the raster layers are imported. The vector layers are not imported. In addition, the raster layers lose their names in the import.

**How to Reproduce**

Save the attached geopackage (and unzip).
Drag the package *from the filesystem* to the legend pane. In the pop-up dialog note that only two layers appear and are unnamed. Select all layers and import. 

Compare this with:
Navigate to saved geopackage in the Browser. There are two raster layers (with names) and two vector layers, (also with names). Each can be dragged individually into the legend and added to the map. Each will keep it's name when dragged into the map.

**QGIS and OS versions**

QGIS version | 3.4.2-Madeira | QGIS code revision | 22034aa070
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 2.3.2 | Running against GDAL/OGR | 2.3.2
Compiled against GEOS | 3.7.0-CAPI-1.11.0 | Running against GEOS | 3.7.0-CAPI-1.11.0 673b9939
PostgreSQL Client Version | 9.2.4 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 520 | Running against PROJ | 5.2.0

[Drag_n_drop_example.zip](https://github.com/qgis/QGIS/files/3245579/Drag_n_drop_example.zip)

**Additional context**

This was first reported in this [stackexchange question](https://gis.stackexchange.com/questions/323757/geopackage-raster-layer-name-is-blank-in-qgis-layers-panel/324295#324295)
The SE question was reported on the qgis-user list by Richard Lee on April 29, 2019.

**Comment by pigreco** [comment]
I confirm QGIS 3.4.8 and MASTER ba764b0d9f
OSGeo4W64b win 10 64b
