### ISSUE TITLE
Make algorithm output dialog more user friendly

### ISSUE THREAD

**Issue by olivierdalang** [qgis/QGIS#30059]
**Feature description.**

This follows a [short discussion on the dev ML](https://lists.osgeo.org/pipermail/qgis-developer/2019-May/057489.html).

When one runs an algorithm, he's shown the algorithm log showing all algorithm output.

This dialog is very good for debugging, but not user friendly. In particular, it's very hard for a regular user to see what the actual error was, as an exception message that could be meaningful (e.g. "API limit reached") is very hard to see in a long list of debug message and stack trace.

Even when things work as excepted (no error), the log can look scary.

I'd suggest adding a new "result" tab before the "log" tab, and show this when the algorithms are run.
This tab would only show informations messages (created with `QgsProcessingFeedbackpushInfo()`) as well as exception messages without stack trace, inviting to look at the log tab if there was an error.
Maybe we could even move the progress bar to that new tab, which would save a bit of screen space on the parameters and log tabs.

**Comment by nyalldawson** [comment]
Currently the log does show things pushed using pushInfo. Isn't this issue solvable just by https://github.com/qgis/QGIS/pull/30038?

**Comment by olivierdalang** [comment]
Oh sorry I missed that (you're working too fast :-) ). The PR would of course already improve the situation.

Yes it shows things using pushInfo, but also from pushDebugInfo, which as the name tells is only relevant when debugging, and may just confuse the regular user with too much raw information.

**Comment by nyalldawson** [comment]
Right -- but pushDebugInfo is almost completely unused. I think it's only used in the grass and saga providers.

**Comment by olivierdalang** [comment]
In terms of actual usage, I think you're right, and that the PR suffices to solve the core issue (which is to make errors understandable by regular users).

But I still believe with the central role of processing in QGIS, that it would be good to think of improving the UX to something better than a log panel.

- Maybe switching to the log tab is not even useful by default (at least if there's no error) ? The progress bar is visible already, and in most case, the log is not really something you'd want to look at. Note that error messages could maybe also be printed over the progress bar ?

- Linked to this issue, there is also that "processing result" panel, that shows some non-layer outputs for algorithms such as "raster layer statistics". This would fit much better in a result tab of the algorithm itself than in the processing toolbox dock widget, supporting the idea of a new "result" tab.

But feel free to close this issue with your PR, as thanks to it, this is a bit less of a priority...

**Comment by nyalldawson** [comment]
@olivierdalang  on the topic of the results dock, https://github.com/qgis/QGIS-Enhancement-Proposals/issues/130 partially relates to this discussion

**Comment by nyalldawson** [comment]
Implemented in https://github.com/qgis/QGIS/commit/c2ce430116ac307e67ce49cdc96eb618ba85742a, further follow ups should be filed as separate issues
