### ISSUE TITLE
Probable race condition in HDF5 library use

### ISSUE THREAD

**Issue by g8sqh** [qgis/QGIS#30054]
Whilst viewing bathymetry data in HDF5 format, I experience sporadic crashes. The data set is

https://arcgispreprodent.admiralty.co.uk/BathyData/bathymetry/2015%20HI1453%20Lyme%20Bay%20Blk1%20S%201m%20CUBE.bag

from the bathymetry section of https://data.admiralty.co.uk/portal/apps/sites/#/marine-data-portal  The data is too large to post.

I attach the backtrace I obtained.  http://hdf-forum.184993.n3.nabble.com/H5SL-insert-common-can-t-insert-duplicate-key-td4026817.html  reports the same backtrace as occurring due to rare inter-thread attempts to read the same data.

As suggested, I rebuilt the HDF5 library with --enable-threadsafe, and the problem vanished. h5check and h5dump process the file successfully, so I think the data is good.

Rebuilding hdf5 threadsafe is unsupported if you want c++ or the high level library, so I suspect it's better to fix QGIS. 

I'm using a quad core i5-3470, the qgis about screen is attached
[ver.txt](https://github.com/qgis/QGIS/files/3246339/ver.txt)

HDF5 library version is 1.10.5

[back.txt](https://github.com/qgis/QGIS/files/3246329/back.txt)

Reproduction is typically by adding the raster layer to a new project, then change band rendering to single pseudocolor from band 1 (elevation), then adjust the color map, however when the crash occurs varies for exactly the same user input.

**Comment by g8sqh** [comment]
Have tried changing GDALOpen to GDALOpenShared, but this then crashes with 'double free'. Fixing will need a deep knowledge of how QGIS and GDAL operate their threading when handling raster.

For now it may be easier to build hdf5 threadsafe and statically link it into qgis - obviously only useful where gqis is distributed as a binary.

**Comment by g8sqh** [comment]
Still present in 3.14, workaround also still works in hdf5-1.12.0

In the HDF5 configure script, insert
--enable-threadsafe
--enable-unsupported

Build and install, then qgis will successfully read UKHO .bag files (the format used for all the modern bathymetry)

**Comment by rouault** [comment]
This is not a QGIS bug. This is a libhdf5 issue: the library should be thread-safe by default. Hard to believe that in 2020 it is not the case by default.
I see Ubuntu builds of libhdf5 turn --enable-threadsafe, which avoids that issue.

@jef-n Looking in http://download.osgeo.org/osgeo4w/x86_64/release/hdf5/hdf5-1.10.5-1-src.tar.bz2 , I don't see ``-D HDF5_ENABLE_THREADSAFE=ON`` in the package.sh. We likely have an issue on Windows. I've created https://trac.osgeo.org/osgeo4w/ticket/642 about that
