### ISSUE TITLE
Lines get too bold when exporting >70 dpi A1 to desktop and then to Illustrator (QGIS 3.4)

### ISSUE THREAD

**Issue by Waterlo0** [qgis/QGIS#30067]
Greetings,
when I exported my first ever A1 format map to desktop and then to Illustrator everything worked just fine. Layers maintained their size and I was able to adjust layers as well. Then, something happened and from now on I am not able to export A1 map using more than 70 dpi without getting bold layers (mainly borders and rivers, but some icons change as well).

I am pretty sure I am filling this form inappropriately, but I just see no other way of fixing this problem. I am ready to work on it and provide any data needed.

Here are some images for understanding:
https://imgur.com/a/xyayLB4

1: exporting map with 300 dpi. 
2: this is how it looks in QGIS
3: this is how it looks in Illustrator 
4: trying to export with 70 dpi
5: It looks just like in QGIS, but some details are missing. Also this DPI is bad (I think) for future printing 

Sorry for filling this form inappropriately. Reddit suggested that I turn to this website and so I did. Nevertheless, I really hope you can help me out and if this problem appears to be a bug then you can fix it.

**Comment by nyalldawson** [comment]
Is this still an issue? I can't reproduce with Illustrator CC v 23.1 

The underlying cause is likely https://illustrator.uservoice.com/forums/601447-illustrator-bugs/suggestions/34246216-incorrect-stroke-width-on-import-of-svg, but it's possibly been fixed since in Illustrator itself.

**Comment by gioman** [comment]
Closing for lack of feedback.
