### ISSUE TITLE
v.drape - no 25D export with SpatiaLite format

### ISSUE THREAD

**Issue by geoxluca** [qgis/QGIS#30066]
hello everyone
I used v.drape for add the Z value to a SpatiaLite vector file using a raster DEM. If I use a SpatiaLite OUT format the file remaine 2D and not 25D. The issue there is not if I export a shp file or dxf too. Have you the same problem?
![Schermata 2019-06-03 alle 10 03 30](https://user-images.githubusercontent.com/10447191/58822108-fba8a400-8636-11e9-80da-e69663ea1160.png)

**Comment by gioman** [comment]
@geoxluca does the same operation works as expected in native GRASS?

**Comment by nyalldawson** [comment]
If this is an issue in the underlying GRASS library, note that there's a native QGIS "drape" algorithm available as an alternative.

**Comment by alexbruy** [comment]
Works fine im master under Linux and Windows with GRASS 7.6.1. Please provider more information on how to reproduce issue.

**Comment by alexbruy** [comment]
Closed for the lack of feedback. Please reopen if necessary.
