### ISSUE TITLE
Install from zip erases plugin directory

### ISSUE THREAD

**Issue by zimirrr** [qgis/QGIS#30063]
If to try to `install from zip` badly zipped plugin it can erase whole plugin directory

1. Go to Plugins - Manage and Install Plugins -> Install from ZIP
2. Choose plugin_killer.zip
This plugin is zipped without dir, just files

QGIS 3.6.3, Windows 10, Windows 7

[plugin_killer.zip](https://github.com/qgis/QGIS/files/3247376/plugin_killer.zip)

**Comment by nyalldawson** [comment]
This is not great, but at least there **IS** a big warning given only to install trusted plugins.
