### ISSUE TITLE
In gpkg, query builder prevents autogenerate of pasted feature with same fid as hidden feature

### ISSUE THREAD

**Issue by SteveLowman** [qgis/QGIS#30062]
The first six steps show the bug problem, which is that the non-unique fid value of pasted feature with the same fid value as an already existing feature that is hidden by query builder will not be detected, and so the edit cannot be saved.

1. Apply this query builder expression to Destination_Layer: "fid" IN (109, 110)
2. Open Source_Layer attribute table, select and copy feature with fid 111, 112, or 113 (one of the fid values hidden in the destination layer).
3. With Destination_Layer in edit mode, paste the copied feature (paste successful).
4. Observe that the pasted fid value remains unchanged.
5. Attempt to save the edit.
6. Observe the error:
   Could not commit changes to layer Destination_Layer

   Errors: ERROR: 1 feature(s) not added.
  
     Provider errors:
         OGR error creating feature -2: failed to execute insert : UNIQUE    constraint failed: query_builder_copy_paste_bug_test_layer2.fid

7. Undo the edit.

The following steps show that a pasted feature with fid the same as feature visible in the destination layer gets a new autogenerated fid value with no problem.

8. In Source_Layer, select and copy feature 109 or 110 (values not hidden in the destination layer).
9. Paste the copied feature into Destination_Layer.
10. Observe that the pasted fid value is set to 'Autogenerate'.
11. Save the edit.
12. Clear the query, and observe that the pasted feature has saved with no problem, autogenerating a new fid value.

This is tested in 3.4.7 LTR, and a recent nightly build of 3.6/3.7, using Windows 10.
Possible related issues include #26960, #28277
[QueryBuilder_CopyPasteBug_test.zip](https://github.com/qgis/QGIS/files/3247310/QueryBuilder_CopyPasteBug_test.zip)

**Comment by SteveLowman** [comment]
Thanks for doing this. Will it be okay to backport to the LTR?

**Comment by elpaso** [comment]
Yes
