### ISSUE TITLE
Miniconda: Could not load qgis_app.dll

### ISSUE THREAD

**Issue by jakimowb** [qgis/QGIS#30060]
I installed QGIS from the conda-forge channel into a new miniconda installation (see https://gisunchained.wordpress.com/2019/05/29/using-qgis-from-conda/)

Starting QGIS via:
> (qgis_stable) F:\>qgis

raises a _Could not load qgis_app.dll_ error.
![qgis_app_error](https://user-images.githubusercontent.com/1404870/58792859-473a5e00-85f5-11e9-9718-e1912e1e0946.png)

However, the PATH settings seem to be correct, as _qgis_app.dll_ can be found with:
> (qgis_stable) F:\>where qgis_app.dll
> F:\miniconda3\envs\qgis_stable\Library\bin\qgis_app.dll

Checking the `qgis.env` [qgis.env.txt](https://github.com/qgis/QGIS/files/3246946/qgis.env.txt) did not reveal anything unusual.

As described by @jef-n in https://github.com/qgis/QGIS/issues/26891#issuecomment-495889169, I also created the [qgis_app.log](https://github.com/qgis/QGIS/files/3246930/qgis_app.log) in the hope that this helps to find a solution.

**Comment by gioman** [comment]
I argue that (for now at least, I think) this is an unsupported way to install QGIS.

**Comment by jakimowb** [comment]
I remember that there was an (optimistic) discussion on publishing QGIS via conda at the QGIS developers meeting in A Coruna.

The conda-installation article (https://gisunchained.wordpress.com/2019/05/29/using-qgis-from-conda/) appeared in the "Latest posts" section on https://plugins.qgis.org and might be seen as kind of semi-official description.

**Comment by gioman** [comment]
> nd might be seen as kind of semi-official description.

it is not.

**Comment by SrNetoChan** [comment]
I agree it's not an official distribution of QGIS. Maybe one day will be :-)

**Comment by SrNetoChan** [comment]
@jakimowb Sorry, I haven't tested it on windows. Please report this issue here:

https://github.com/conda-forge/qgis-feedstock/issues

**Comment by jakimowb** [comment]
Ok @SrNetoChan, my initial issue description is now on https://github.com/conda-forge/qgis-feedstock/issues/71

I think this here can be closed now.
