### ISSUE TITLE
Import online maps under Linux and win

### ISSUE THREAD

**Issue by MRwang12** [qgis/QGIS#30070]
I want to import an online map, but now I use qgis3.4 under win and Linux, and the code is the same, but the effect is different.
In Windows, everything works, but in Linux, the online map only shows half of it, may I ask why?thank you
The code is as follows:
`addOpenSourceRasterLayer("type=xyz&url=http://www.google.cn/maps/vt?lyrs%3Ds@820%26gl%3Dcn%26x%3D%7Bx%7D%26y%3D%7By%7D%26z%3D%7Bz%7D&zmax=18&zmin=0", "Google Sat", "wms");`

`void QtGuiApplication1::addOpenSourceRasterLayer(const QString& url, const QString& basename, const QString& providerKey)
{
	//        rasterLyr = QgsRasterLayer("type=xyz&url=http://c.tile.openstreetmap.org / {z} / {x} / {y}.png", "OSM", "wms") 

	QgsRasterLayer *rasterLayer = 0;

	if (providerKey.isEmpty())
	{
		rasterLayer = new QgsRasterLayer(url, basename);
	}
	else
	{
		rasterLayer = new QgsRasterLayer(url, basename, providerKey);
	}

	if (!rasterLayer->isValid())
	{
		QMessageBox::critical(this, "error", "layer is invalid");
		return;
	}

	//QgsMapLayerRegistry::instance()->addMapLayer(rasterLayer);
	//QgsProject.instance()->addMapLayer(rasterLayer);
	//qgsProject = QgsProject::instance();
	qgsProject->addMapLayer(rasterLayer);
	//mapCanvasLayerSet.append(rasterLayer);
	layers.append(rasterLayer);
	mapCanvas->setExtent(rasterLayer->extent());
	mapCanvas->setLayers(layers);
	mapCanvas->setVisible(true);
	mapCanvas->freeze(false);
	mapCanvas->refresh();
}`

linux:

![KP{` CM%L0LZW1A258SV%GA](https://user-images.githubusercontent.com/25046579/58846575-3dc2fb80-86b2-11e9-9987-379266ac1d16.png)

win:

![@ }~C`L0 4L5MF@A1F DW`E](https://user-images.githubusercontent.com/25046579/58846586-487d9080-86b2-11e9-845b-a1b7fa2251cc.png)

**Comment by gioman** [comment]
Please ask such questions in the developers mailing list.
