### ISSUE TITLE
New 3D Map View Fails on Launch (Windows)

### ISSUE THREAD

**Issue by IReese** [qgis/QGIS#30087]
Tested on QGIS 3.4.8 LTR & 3.6 
Using Window 7 Enterprise
Running Intel 4 x i7
on 64 Bit

Issue: I am running a laptop, plus an additional monitor.  When QGIS is running in the extra monitor, if I try to launch the 3D Map View nothing happens.  It looks like QGIS does refresh and the panels display shows the '3D Map 1 Panel' is running, however, the 3D window does not appear. Nothing.

If I move QGIS back to the original laptop screen and launch a 3D window.  Everything works fine and as expected.  A 3D screen launches as normal.

Not a huge issue, but some thing to note

**Comment by geomondego** [comment]
No problem where with Win10 and QGIS 3.16.3

**Comment by gioman** [comment]
Closing for lack of feedback.
