### ISSUE TITLE
The bottom layer partially covers the top layer.

### ISSUE THREAD

**Issue by beketata** [qgis/QGIS#30084]
I have a simple layer with a highway (as a MultiLineString stored in WKT file).
The next image is a part of it:

![1](https://user-images.githubusercontent.com/7413903/58893704-7397cc80-8712-11e9-8112-c4fbab8f8225.jpg)

I am trying to add a background to this layer with a same geometry with a bigger width.
When I add the same WKT file as an extra layer under existing one and increase the Stroke With everything looks fine:

![2](https://user-images.githubusercontent.com/7413903/58894226-6deeb680-8713-11e9-9f85-46f97ed80a63.jpg)

But when I add an extra line to the same layer it appears as in the next image:

![3](https://user-images.githubusercontent.com/7413903/58894621-2288d800-8714-11e9-811a-9d5ceee35ac2.jpg)

I am not sure is it a bug, but it looks like.

[Test.zip](https://github.com/qgis/QGIS/files/3253431/Test.zip)

**Comment by nyalldawson** [comment]
You can use symbol levels for this - check the qgis manual or search on gis.stackexchange.com for guides.
