### ISSUE TITLE
Temp feature should be shown after drawing new feature with maptool.

### ISSUE THREAD

**Issue by NathanW2** [qgis/QGIS#30118]
After drawing a new feature the finished feature temporarily disappears in the map so people can't see what they have just added once the feature form opens.  

A better experience for the user would be to show the feature in a rubber band color and style so the user can see what they have just drawn for context.

**Comment by nyalldawson** [comment]
you mean while the feature attribute form is open?

**Comment by NathanW2** [comment]
Yeah. When you draw a feature the attribute form comes up but the feature
vanishes after that until you press ok.

Sorry did this while training so didn't add many details

**Comment by andreasneumann** [comment]
I agree with @NathanW2 - I always found it confusing (and our users too) that the already digitized feature temporarily disappears. To me this is more a bug fix (or a fix of an annoyance)  than a new feature.

**Comment by NathanW2** [comment]
Yep, I agree. Changed it to a bug as it's really a UX style thing.

**Comment by m-kuhn** [comment]
I agree, this has been bothering me for a long time already. What's the milestone for / how should it be interpreted?

"You scheduled to work on it for 3.10" or "is on the wishlist for 3.10 but can't be added to 3.8 because too dangerous" or ...?

**Comment by gioman** [comment]
This is also a regression, because in the past it worked as expected. This also means that there is already a ticket about it that now I'm not able to find.

**Comment by NathanW2** [comment]
Ok I will check some older versions and try and find the ticket.

I was mainly using this ticket as a demo while training people.  Happy to
try and fix and backport into older versions. This happened in 3.4.8 have
not tested newer versions.

**Comment by andreasneumann** [comment]
As far as I know it was always like this in QGIS 3.x - not sure about QGIS 2.x

**Comment by gioman** [comment]
> As far as I know it was always like this in QGIS 3.x - not sure about QGIS 2.x

it broke quite some time ago, in an early 2.*

**Comment by NathanW2** [comment]
Thanks
