### ISSUE TITLE
Critical error in QGIS 3.6.3 for  WMS-services

### ISSUE THREAD

**Issue by guenter1952** [qgis/QGIS#30138]
I changed from QGIS 2.18.6 to QGIS 3.6.3 and tried to copy some simple WMS services, nearly all tries generate failures in QGIS 3.6.3, like:

2019-06-08T20:59:58     CRITICAL    Ungültiger Layer : Raster layer Datenanbieter ist ungültig (Anbieter wms, URI: 

'translated, it may mean:' void layer, Raster layer provider is void

with the services:
http://www.geodaten.bayern.de/ogc/ogc_verwaltungsatlas_verwaltungsgrenzen.cgi?
https://geoservices.bayern.de/wms/v2/ogc_dop80_oa.cgi?
http://www.geodaten.bayern.de/ogc/ogc_dtk500_oa.cgi?

...but this is working in QGIS 3.6.3:
http://www.geodaten.bayern.de/ogc/ogc_denkmal.cgi?

All are working with QGIS 2.18.6

Thank You!

**Comment by elpaso** [comment]
No issues with the first URL on master.

**Comment by gioman** [comment]
> with the services:
> http://www.geodaten.bayern.de/ogc/ogc_verwaltungsatlas_verwaltungsgrenzen.cgi?
> https://geoservices.bayern.de/wms/v2/ogc_dop80_oa.cgi?
> http://www.geodaten.bayern.de/ogc/ogc_dtk500_oa.cgi?

@guenter1952 they all works here on master too. Please try clean your QGIS network cache and see if it helps.

**Comment by gioman** [comment]
I'm the only one that finds confusing that now on GH we don't have a label saying (i.e.) "wms client" or "ogc client"?

**Comment by guenter1952** [comment]
I reset the network cache and got a failure in python.
I loaded QDIS 3.4.8 on a newly setup WIN10 machine and get installation failures (as before with 3.6.3.:
/grassplugin7.dll ---The specified module could not be found
.. and I get python warnings
The above WMS services are running now, but some produce the error info again, despite showing the correct layers.

Because of that, I will stay with QGIS 2.18.6, or drop it because i want to __USE__ a GIS system and not troubleshoot any bugs in any software for the next weeks, may it be WIn10 or QGIS or what so ever.
Thanks for your assistance and Bye

**Comment by elpaso** [comment]
You're welcome
