### ISSUE TITLE
Allow tool output and export to save a new layer/table in existing databases also for non QGIS native tools.

### ISSUE THREAD

**Issue by debaser75** [qgis/QGIS#30136]
First, it'd be nice to be able to save the output of a tool directly to a PostGIS layer/table. It seems that the only way to do this right now is to dump it out to a different format (shapefile/geojson) and then import it to PostGIS.

Second, it would be nice to save tool output as a new layer in an existing database. Many tools can save layers to a **new** geopackage or spatialite database, but it doesn't seem possible to save the output as a new layer/table in an **existing** database. I like keeping all of my layers for a project in a single database - that makes it easier to move around.  And I also use SQL in a lot of my analyses -it's fairly clunky to do joins between tables in separate databases.

Thanks to all of the QGIS developers out there! I'm more and more impressed with every release!

**Comment by gioman** [comment]
@debaser75 like:

![Screenshot_20190610_093416](https://user-images.githubusercontent.com/1951107/59182987-fb426880-8b62-11e9-96de-54071068ae6d.png)

?

**Comment by debaser75** [comment]
Yes! That's exactly what I'm talking about. I've only been using GDAL and GRASS tools that output vector layers .... and those don't seem to have that option. So I suppose this needs to be logged as a feature request in GRASS and GDAL? Or does the QGIS **interface** to those tools need to be updated to allow those output options?

**Comment by gioman** [comment]
> Yes! That's exactly what I'm talking about. I've only been using GDAL and GRASS tools that output vector layers .... and those don't seem to have that option. So I suppose this needs to be logged as a feature request in GRASS and GDAL? Or does the QGIS **interface** to those tools need to be updated to allow those output options?

@debaser75 the functionality is available on for QGIS native tools, and it makes sense. I guess that with kind a lot of work could be implemented also for SAGA/GRASS/GDAL... but that it a feature request.

**Comment by alexbruy** [comment]
I'm afraid this is a won'tfix or at least very complex as different backends will need different approaches to handle database outputs and some database which are supported by QGIS may not be supported by backends.
