### ISSUE TITLE
Adding shapefile with dialog, "layer already exists"

### ISSUE THREAD

**Issue by snow-raven** [qgis/QGIS#30157]
Adding a new shapefile today to my template project using the Add Shapefile Layer dialog and specifying the projection (#4269), I received the warning that "The layer already exists. Are you sure you want to overwrite the existing file?" I have a lot of shapefiles in this template, so I initially assumed an old version was in there and clicked yes. Doing so added the file with the correct projection, but deleted all of the features. File size went from 35 Mb to 1kb.

I thought it might be another issue, so I tested the following:
- added file (same method) to a blank project. - same error & result. (CRS is the correct one).
- added file without specifying projection. - same error & result. (CRS is the correct one).
- added a different shapefile to a blank project. - same error & result. (CRS is the correct one).
- added the file by dragging & dropping. - shapefile displays all features and is in the correct projection. 
- created a new user profile and tested adding via dialog. - same error & result. (CRS is the correct one).
- added a file to the new user profile by dragging & dropping. - shapefile displays all features and is in the correct projection. 

I don't think data source matters, but I was originally using the attached "Major Land Resource Area" shapefile from USDA. Screenshot is also attached, though is of one of my blank test files, so I'm not sure it helps, either. Adding the file with these settings resulted in a blank shapefile in CRS 4269.

I only upgraded to 3.4.7 from 2.18 a few weeks ago, having waited for a new stable build. I don't have many plugins installed yet. Specs below.

I don't know if this is a persistent bug or not, will update if I get further troubleshooting. I'm guessing it would have been reported by now if it had affected other users, but I didn't see a report. For now, I can drag & drop.

Thanks,
Brenna

QGIS version
3.4.7-Madeira
QGIS code revision
5c56989325
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
2.4.1
Running against GDAL/OGR
2.4.1
Compiled against GEOS
3.7.0-CAPI-1.11.0
Running against GEOS
3.7.2-CAPI-1.11.0 b55d2125
PostgreSQL Client Version
9.2.4
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
520
Running against PROJ
5.2.0

**Comment by jgrocha** [comment]
@snow-raven Can you share the shapefile to replicate the problem?

**Comment by snow-raven** [comment]
Sorry, thought I had. However, in trying to replicate the error, I see my mistake. I was attempting to use the "New Shapefile Layer" button in the Data Source Manager Toolbar, as it looks much like the "Add Vector Layer" button in the Manage Layers Toolbar. Forgive me while I get used to my new v3.4 layout...
