### ISSUE TITLE
PyQGIS: Error adding layer to Overview Panel

### ISSUE THREAD

**Issue by javitank** [qgis/QGIS#30154]
**Describe the bug**
I am writing a QGIS plugin and I want to have a **method that adds a layer to the map and show it in the Overview Panel**. This is working but the layer is showing "distorted" in the Overview panel until, for example you resize the overview panel and it refreshes. 

Is this a bug in QGIS?

**How to Reproduce**

1. Open QGIS (or a new project)
2. Open Python Console
3. Open the editor from the console
4. Paste the following code and press "Run Script"

    ```python
    # Open Overview automatically
    iface.mainWindow().findChild(QDockWidget, "Overview").setVisible(True)
    # Create OSM layer
    urlWithParams = 'type=xyz&url=http://a.tile.openstreetmap.org/%7Bz%7D/%7Bx%7D/%7By%7D.png&zmax=19&zmin=0&crs=EPSG3857'
    layer = QgsRasterLayer(urlWithParams, 'OpenStreetMap', 'wms')
    # Add layer to the map
    QgsProject.instance().addMapLayer(layer)
    # Show layer in Overview
    QgsProject.instance().layerTreeRoot().findLayer(layer.id()).setCustomProperty("overview", 1)
    ```
Observations:
- The layer in the Overview in showing distorted. 
- You can resize the panel, it refreshes and reloads correctly. You can also refresh it running from the Python console:
    `iface.layerTreeCanvasBridge().overviewCanvas().refresh()`
- If you remove the layer and execute the code again, it will run correctly, so you must reopen QGIS or close and open a new project.
- If you run the snippet directly from the python console, it will run ok.

**QGIS and OS versions**
I have tried in QGIS 3.6.3 and 3.4.7, both in Ubuntu 18.04 and Windows 10.

**Comment by Gustry** [comment]
What is the CRS of the new project?
What is the CRS after you added the layer? If it's not 3857, the map is distorted.

BTW, you can do a single block code with python syntax highlighted. https://help.github.com/en/articles/creating-and-highlighting-code-blocks#syntax-highlighting

**Comment by javitank** [comment]
Thank you very much!, formatting of block of code fixed.

The CRS of a new project is EPSG:4326, and is EPSG:3857 after adding the layer. 

But note that the layer i**s always loaded correctly in the main map**, the problem is in the overview panel (and it corrects automatically after resizing the panel).

**Comment by gioman** [comment]
> The layer in the Overview in showing distorted.

@javitank just tested your snippet in QGIS master on Linux: no problem whatsoever (no distortion in the overview map).

**Comment by Gustry** [comment]
Same, no problem for running the snippet and then displaying the overview panel.
3.6.3 and master, Ubuntu 19.04.

**Comment by javitank** [comment]
> @javitank just tested your snippet in QGIS master on Linux: no problem whatsoever (no distortion in the overview map).

Thank you @gioman, I'll try to test on master.

> Same, no problem for running the snippet and then displaying the overview panel.
3.6.3 and master, Ubuntu 19.04.

Thank you @Gustry.
I'm on 3.6.3 also... Have you tried opening first the overview panel and then executing the snippet?  (of course, opening a new  project, not reusing a previous one with layers loaded with the snippet)

I am going to modify the snippet to add a line to automatically open de overview panel, I would appreciate it if you can try it again.

**Comment by javitank** [comment]
[overview_panel_error.zip](https://github.com/qgis/QGIS/files/3275765/overview_panel_error.zip)

I've recorded a screencast to show exactly what happens, I hope it's helpful.

**Comment by Gustry** [comment]
Ok, confirmed if you open first the overview panel

**Comment by gioman** [comment]
> Ok, confirmed if you open first the overview panel

ok, but jeez... really a tiny annoyance rather than a bug...

**Comment by Pedro-Murteira** [comment]
I can't reproduce this issue using QGIS 3.16.15 and 3.22.2. The overview shows up without any issues. (Windows 10)

**Comment by javitank** [comment]
Hi, @Pedro-Murteira 
No longer happens in version 3.16, I have just tested again.

It was not a very important matter at the time, for me this issue can be closed. 
Thank you all very much for your time.
