### ISSUE TITLE
Move feature should live in main editing toolbar

### ISSUE THREAD

**Issue by NathanW2** [qgis/QGIS#30165]
This might just be me but Move Feature tool should really live in the main editing toolbar as it seems like it would be a common thing to do, you can move points using the vertex tool however moving polygons and lines are much easier with the move tool.

![image](https://user-images.githubusercontent.com/381660/59238458-93af1a80-8c41-11e9-9eb2-9ebe5be5fc05.png)

Not fully sold on moving it so happy for it to stay here just found it a bit odd when training people.

**Comment by nirvn** [comment]
No strong opinion on this (mainly because I have both of these toolbars always on), but as a reminder: it was moved from main editing to advanced editing a while back.

**Comment by nyalldawson** [comment]
Yeah this was discussed at length when it was originally moved out of that toolbar. I think it's a "won't fix"

**Comment by NathanW2** [comment]
Closing as won't fix for now.
