### ISSUE TITLE
Crashed on re-loading Recent

### ISSUE THREAD

**Issue by TedRodgers** [qgis/QGIS#30169]
Crash ID: cb1deb4c833d8893d428ba32e4dd5759a5bc223f

Stack Trace

QBitArray::QBitArray :
QgsCoordinateReferenceSystem::authid :
QgsCoordinateTransformContext::calculateDatumTransforms :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::QgsCoordinateTransform :
QgsMapCanvasAnnotationItem::updatePosition :
QgsMapCanvas::updateCanvasItemPositions :
QMetaObject::activate :
QgsMapCanvas::setExtent :
QgsMapCanvas::readProject :
QMetaObject::activate :
QgsProject::readProject :
QgsProject::readProjectFile :
QgsProject::unzip :
QgsProject::read :
QgisApp::addProject :
QgisApp::openProject :
QMetaObject::activate :
QMenu::~QMenu :
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.6.3-Noosa
QGIS code revision: 0c5774c068
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by elpaso** [comment]
Would you be able to share a project and data and the exact steps to reproduce the issue?

**Comment by gioman** [comment]
@TedRodgers also try with a new/clean QGIS profile, no 3rd party plugins installed.

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
