### ISSUE TITLE
Adding a north arrow is too hard

### ISSUE THREAD

**Issue by NathanW2** [qgis/QGIS#30162]
At the moment the logic to add a north arrow to a map is:

- Add picture
- Find Item Properties Tab
- Expand Search Directories
- Skip the first 30 or so icons
- Find a north arrow
- Update SVG parameters for style

I know that north arrows are just images however I think we can do something better here around this in order to make the experience better for the users.

- New North Arrow button
- Opens SVG properties
- Auto close main properties
- Auto expand Search Directories
- Filter the SVG list if we can to just show the north arrows
- Auto enable Sync with map" for rotation.

**Comment by roya0045** [comment]
This always puzzled me as to why this wasn't in QGIS in 2.x, you get used to it, but for infrequent users or newcomers this is a basic mapping feature that need to be looked up online.

**Comment by DelazJ** [comment]
For reference (a not that consensual feature request) http://osgeo-org.1560.x6.nabble.com/North-arrow-in-QGIS-td5394938.html
