### ISSUE TITLE
Label position tab is too far away. Position is a primary action so should be close to the front

### ISSUE THREAD

**Issue by NathanW2** [qgis/QGIS#30160]
The label positions label should be the second tab on the label panel as it's an important part of creating a good map.

As it stands the position label is all second last tab on the label panel meaning from a UI point of view it should have less priority in the users' workflow however this isn't the case with the position because it's one of the main things the user needs to do.

![image](https://user-images.githubusercontent.com/381660/59235444-9fe0ab00-8c34-11e9-89e3-ef20719969d7.png)

The tabs should be ordered from the highest usage and priority  to lowest use and priority

**Comment by andreasneumann** [comment]
agreed. I almost always need this tab when I create labels, while some of the background tabs are really optional.

**Comment by wonder-sk** [comment]
Yes please!

**Comment by dakcarto** [comment]
Well... that makes complete sense.

I think the current ordering of the tabs was based off of the old labelling dialog workflow.

**Comment by alexbruy** [comment]
From the discussion in #33911 ([1](https://github.com/qgis/QGIS/pull/33911#issuecomment-576133326), [2](https://github.com/qgis/QGIS/pull/33911#issuecomment-576138039)) looks like this was already discussed and voted down.
