### ISSUE TITLE
Grass7 folder cannot be entered

### ISSUE THREAD

**Issue by blackgis** [qgis/QGIS#30189]
Qgis 3.6.3 installed via osegeo4w

_Dieser Algorithmus kann nicht ausgeführt werden :-( 
The specified GRASS 7 folder "C:\BLACKP~1\OSGEO4W\Programs\bin\bin" does not contain a valid set of GRASS 7 modules. Please, go to the Processing settings dialog, and check that the GRASS 7 folder is correctly configured_

The strange thing is i cannot even set a Folder where the dataprovider are listed where you do that normally, so where to enter the grass7 path?

**Comment by blackgis** [comment]
Tried to use r.shade, then the popup showed up.

**Comment by jef-n** [comment]
Install the qgis-grass-plugin and use the "QGIS with GRASS" shortcut.

**Comment by blackgis** [comment]
damn - your are right "QGIS with GRASS" shortcut

**Comment by Arodius** [comment]
Thanks, I can use this tools
