### ISSUE TITLE
locator bar "Actions" filter is badly named

### ISSUE THREAD

**Issue by AlisterH** [qgis/QGIS#30186]
(This has been discussed in the most recent comments at #14052 and Borys suggested filing a separate ticket)

PROBLEM

The locator bar "Actions" filter searches for entries in the QGIS menu.  It is very unlikely that any user seeing "Actions" would understand what it actually means.  

I assumed it was to do with layer actions, so I didn't even try it, even though I was specifically looking for the ability to search menu entries from the locator bar.  Together with the filter being disabled by default, this meant that I was convinced it was not possible to search menu entries from the locator bar.

It is not just me that has a problem with this: when Borys did the Polish translation he found it misleading, so changed it to "Actions (menu items)" in the translation.

SUGGESTED WORDING

I'm not sure what the best wording would be, but I don't think the word "Actions" needs to be kept, as it isn't helpful to the user (I'd say there's a lot more "action" in the processing algorithms than in the menu entries!).  

My first thought was something like "_Menu entries and panels/toolbars_".  Technically that is a bit redundant because the panels and toolbars are only listed because they appear in the menu, but I think it is a good description for the user.  The main issue with that wording would be if it isn't broad enough: AFAIK this filter currently only searches menu entries; nothing stops plugins from adding toolbar buttons and not menu entries, so it should really also search for toolbar items that don't appear in the menu.  I'm guessing there is nothing else it should be searching?

**Comment by nyalldawson** [comment]
This is too late to change now - the actions locator has been present in qgis for long enough that it's now accepted wording and part of user's "muscle memory"
