### ISSUE TITLE
3D render crashing issue on 3.4.3 and 3.6.3

### ISSUE THREAD

**Issue by MatanGolan** [qgis/QGIS#30195]
Hi guys,

I'm working on a projec that demands 3D rendering, I have some performence issues.
In the 3.4.3 version I've tried to tag the 'many CPU cores' option - 

Though I'm receving the next error message 

My system is QGIS 3.4 Madeira 64bit for windows standalone. 
This might be connected to an update I had whoch forced me to reinstall numpy due to a raster merging error .

Due to that I've downloaded a few hours ago the 3.6.3 version - and once again when getting into the layout (A0 , Res 300) - with no SHP layers working - only rasters, The QGIS crashes. 

I need it urgently for work. 

Would greatly appriciate your help. 

Matan.

Crash ID: 102df5231207235751aee8a6daf57cc7bdc876c5

Stack Trace

Qt3DCore::QNode::setEnabled :
QgsWindow3DEngine::tr :
Qgs3DMapScene::onFrameTriggered :
QMetaObject::activate :
Qt3DLogic::QFrameAction::triggered :
Qt3DLogic::QFrameAction::onTriggered :
Qt3DLogic::QFrameAction::onTriggered :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.6.3-Noosa
QGIS code revision: 0c5774c068
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by MatanGolan** [comment]
This is the error message in 3.6.3 render settings tagging of multiple core rendering : 

An error has occurred while executing Python code: 

RuntimeError: wrapped C/C++ object of type ReseauTi has been deleted 
Traceback (most recent call last):
  File "C:/Users/Matan Golan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\networks\networks_provider.py", line 123, in loadAlgorithms
    self.addAlgorithm( alg )
RuntimeError: wrapped C/C++ object of type ReseauTi has been deleted


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.6.3-Noosa Noosa, 0c5774c068 

Python Path:
C:/Users/Matan Golan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\networks
C:/PROGRA~1/QGIS3~1.6/apps/qgis/./python
C:/Users/Matan Golan/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Matan Golan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.6/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.6\bin\python37.zip
C:\PROGRA~1\QGIS3~1.6\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.6\apps\Python37\lib
C:\Program Files\QGIS 3.6\bin
C:\PROGRA~1\QGIS3~1.6\apps\Python37
C:\PROGRA~1\QGIS3~1.6\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.6\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.6\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.6\apps\Python37\lib\site-packages\Pythonwin
C:/Users/Matan Golan/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Matan Golan/Documents/משרד/רשות נחל הקישון

**Comment by gioman** [comment]
> RuntimeError: wrapped C/C++ object of type ReseauTi has been deleted
> Traceback (most recent call last):
> File "C:/Users/Matan Golan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\networks\networks_provider.py", line 123, in loadAlgorithms
> self.addAlgorithm( alg )
> RuntimeError: wrapped C/C++ object of type ReseauTi has been deleted

@MatanGolan this message comes from a 3rd party python plugin, not QGIS itself. Please try your workflow with a new/clean QGIS profile (no 3d party plugins installed) and see if things get better.

**Comment by MatanGolan** [comment]
@gioman First of all thank you. I had downloaded a new version (Noosa) and it still appears. What can I do at this point?

**Comment by gioman** [comment]
> @gioman First of all thank you. I had downloaded a new version (Noosa) and it still appears. What can I do at this point?

@MatanGolan did you create a new QGIS profile and tested again? Installing or re-installing does not mean you are using a new/clean QGIS profile.

**Comment by MatanGolan** [comment]
@gioman I am sorry for the basic question, but I'm not sure what you mean. Where and how do I create a new QGIS profile?

**Comment by gioman** [comment]
@MatanGolan https://docs.qgis.org/3.4/en/docs/user_manual/introduction/qgis_configuration.html?highlight=profile#working-with-user-profiles

create a new profile, do not install any 3rd party plugin, load your project and see if it still crashes.

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
