### ISSUE TITLE
Path containing åäö fails in gdals polygonize

### ISSUE THREAD

**Issue by axelande** [qgis/QGIS#30191]
I'm writing a plugin using the proccessing alg `gdal:polygonize`, which works fine until the user of the plugin uses a special character (like å, ä, ö etc.) in the path to the file. 

Can I decode/encode the path in my plugin in order to fix this?

**Describe the bug**
GDAL command:
python3 -m gdal_polygonize "C:/Users/axa/Downloads/massaöä och hej/tmp_files123/2018-08-18, Sentinel-2B L2A, B08.tiff" "C:/Users/axa/Downloads/massaöä och hej/test.shp" -b 1 -f "ESRI Shapefile" test DN
GDAL command output:
Traceback (most recent call last):
File "C:/OSGEO4~1/apps/qgis-ltr/./python/plugins\processing\algs\gdal\GdalAlgorithm.py", line 133, in processAlgorithm
GdalUtils.runGdal(commands, feedback)
File "C:/OSGEO4~1/apps/qgis-ltr/./python/plugins\processing\algs\gdal\GdalUtils.py", line 110, in runGdal
for line in proc.stdout:
File "C:\OSGEO4~1\apps\Python37\lib\codecs.py", line 322, in decode
(result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 44: invalid start byte

Execution failed after 0.44 seconds

Loading resulting layers
Algorithm 'Polygonize (raster to vector)' finished

**How to Reproduce**
Just try to add a shapefile with a path containing some special character in `Polygonize (Raster to Vector)`

**QGIS and OS versions**
Windows 10 x64
QGIS 3.4.5
GDAL 2.4.0

**Comment by gioman** [comment]
Does it work if you just run the gdal command from the osgeo4w shell? i.e.

gdal_polygonize "C:/Users/axa/Downloads/massaöä och hej/tmp_files123/2018-08-18, Sentinel-2B L2A, B08.tiff" "C:/Users/axa/Downloads/massaöä och hej/test.shp" -b 1 -f "ESRI Shapefile" test DN

**Comment by axelande** [comment]
No,

I get `ERROR 4: C:/Users/axa/Downloads/massa och hej/tmp_files123/2018-08-18, Sentinel-2B L2A, B08.tiff: No such file or directory
Unable to open C:/Users/axa/Downloads/massa och hej/tmp_files123/2018-08-18, Sentinel-2B L2A, B08.tiff`

The `öä` just disappeared in the error message 

(I tried to rename the folder removing the `äö` and changed the path in the command and then it worked.)

**Comment by gioman** [comment]
> (I tried to rename the folder removing the `äö` and changed the path in the command and then it worked.)

if it fails from the command line, even by escaping the path that contains the spaces/etc (using double quotes) then I'm not sure if is a QGIS problem at all.

**Comment by axelande** [comment]
Alright, but what causes the problem /how can I debug it/ who should I address it to?

**Comment by gioman** [comment]
> Alright, but what causes the problem /how can I debug it/ who should I address it to?

this

gdal_polygonize "C:\Users\gio\Desktop\massaöä och hej\mdt_clipped.tif" -f "ESRI Shapefile" "C:\Users\gio\Desktop\massaöä och hej\out1.shp"


works for me on the osgeo4w shell of both the QGIS standalone installer and the osgeo4w one.

**Comment by gioman** [comment]
Closing as not replicable.
