### ISSUE TITLE
value relation widget, data is saved as Key Column values instead of Value Column values

### ISSUE THREAD

**Issue by RobinRots** [qgis/QGIS#30194]
When using the value relation widget on a column all the data is correctly visualized as Value Column values but in the background the data is actually saved as Key Column values. This becomes clear when trying to set up an expression refering to a column with a Value relation widget or trying a search by expression on such a column.

**Comment by gioman** [comment]
What QGIS Version?

Can you please attach a sample project with data and the detailed steps to follow in order to replicate?

**Comment by elpaso** [comment]
I think this is by design.

**Comment by RobinRots** [comment]
Hi,
I'm working in qgis 3.6.3

I recreated the problem in a small project (see attachment).
I set up a simple value relation (no cascades applied here) for "field1"
I set up "field2" to have a default value (when updated) based on an expression refering to "field1"
In the expression I used both Key column values and Value column values. Only in the features where the Key column is used the expression is applied.

Other simple test: do a search by expression
"field1" = 'S' gives two results
"field1" = 'sad' gives no result

I also figured this could be by design, but it's not intuitive this way (at least for me it wasn't).

Speaking of which, I also posted a feature request (back on Redmine) on the value relation widget (#29640) which hasn't produced any response so far. This one also deals with the practical useability of this widget when wanting to make a more than one step drive down cascade.

[bugreport_valuerelation.zip](https://github.com/qgis/QGIS/files/3286748/bugreport_valuerelation.zip)

**Comment by m-kuhn** [comment]
Can't you just use the same field for key and value for your use case?

**Comment by RobinRots** [comment]
@m-kuhn 
The attached project in my previous post is just a simplified recreation of the problem.
The main use of the value relation widget is for cascading dropdowns, in which case you can not use the same field for key and value.

**Comment by andreasneumann** [comment]
We need to be careful here. It is by design that QGIS stores the key and not the value. A lot of projects out there are relying on the fact that QGIS is storing the key and not the value. Also Plugins and Python form code was written against this behavior.

If one wants the value instead of the key, there is the relatively easy to use expression "represent_value()" to get the human readable value.

**Comment by m-kuhn** [comment]
Maybe for this use case of chained filters we need a special new option to have a clear separation of filters and keys or another new functionality.

As @andreasneumann and @elpaso said, this is by design and not a bug.

**Comment by damstep** [comment]
Hi all, I am not sure the behaviour is as designed as discussed above.
I get that you can display the key and value for the field and that qgis should be saving the key and not the value.
what is happening is that with the value relation, the key being saved is actually that from the original field and not the field that the value relation is set up to chose.
in the attached example the vector layer  has a value relation set up on the rank_size field which uses the target size lu table as the relation table.
the key field is the  matcode and the value column is size.
with the filter expression set up  on the matcode =currentvalue('rank_maturity')

the expected outcome is a drop down that only displays size values where matcode matches the rank_maturity value in the vector table.  this works and displays the correct value, albeit the description column (size description) values aren't displayed except in the hover text, and the selected rank size value displays fine in the atrtribute tables.
however when you export the table, or use the rank size value in a label, it actually reverts to  the matcode instead, the same beahviour can be seen when using the ndentify results  tool. the results panel shows the correct values while the feature attribute popout shows the rank size as the smae as the rank-maturity - the key field value.
![bug -identify results panel shoing different value to labels and feature attribute dropout](https://user-images.githubusercontent.com/42903068/173226952-8f678859-9cd6-4020-bf11-fea802d7b477.png)

[neighbours.zip](https://github.com/qgis/QGIS/files/8885559/neighbours.zip)
