### ISSUE TITLE
SAGA Resampling Method

### ISSUE THREAD

**Issue by PedroVenancio** [qgis/QGIS#30193]
SAGA raster algorithms are **always** using B-Spline Interpolation as Resampling Method in QGIS 3.x

https://github.com/qgis/QGIS/blob/master/python/plugins/processing/algs/saga/SagaAlgorithm.py#L434 

This leads to "strange" output values, specially when the option choosed in the algorithms interface is the Nearest Neighbour. 

QGIS documentation says that "When multiple raster layers are used as input for a SAGA algorithm, QGIS resamples them to a common grid system and then passes them to SAGA"

https://docs.qgis.org/3.4/en/docs/user_manual/processing/3rdParty.html#about-saga-grid-system-limitations

but this happen even with only one input raster.

For instance, using SAGA Raster Calculator, it do the job in two steps:

io_gdal 0 -TRANSFORM 1 **-RESAMPLING 3** -GRIDS "C:/Users/pedro.venancio/AppData/Local/Temp/processing_188d976842164f2bbb10e9f971f6ea00/0a59af8d77454142a23cd5b7ba417b82/probabilidadebruta.sgrd" -FILES "D:\Testes\duvida_e_erro\probabilidade_bruta.tif"

grid_calculus "Grid Calculator" -GRIDS "C:/Users/pedro.venancio/AppData/Local/Temp/processing_188d976842164f2bbb10e9f971f6ea00/0a59af8d77454142a23cd5b7ba417b82/probabilidadebruta.sgrd" -FORMULA "ifelse(eq(a,0),1,a)" **-RESAMPLING 0** -USE_NODATA false -TYPE 7 -RESULT "D:/Testes/duvida_e_erro/probabilidade_bruta_nn.sdat"

As you can see, the Resampling Method choosed in Raster Calculator was **[0] Nearest Neighbour**. It only uses one input raster. But the io_gdal algorithm always uses **[3] B-Spline Interpolation** Resampling Method.

This does not happened in QGIS 2.18, because it used the resampling method as a variable:

https://github.com/qgis/QGIS/blob/release-2_18/python/plugins/processing/algs/saga/SagaAlgorithm.py#L348 

Ideally, the Resampling Method of io_gdal should match the Resampling Method selected by the user in the algorithm. It is not intuitive to have the possibility to choose the Resampling Method in the algorithm window, and the B-Spline be used in background just for input one single raster.

Or in alternative, the possibility to choose the default SAGA Resampling Method in SAGA Processing Options.

Until there is a more robust solution, I think the Nearest Neighbor Resampling Method should be used by default, as in the most recent SAGA versions:

http://www.saga-gis.org/saga_tool_doc/7.2.0/io_gdal_0.html 

**QGIS and OS versions**

This affects all QGIS 3 versions in any OS.

**Comment by gioman** [comment]
@PedroVenancio the fix is here https://github.com/qgis/QGIS/pull/35726 but I can't make the updated tests to pass, so for now I have to close it.

**Comment by alexbruy** [comment]
SAGA Provider was not maintained and now remowed from QGIS (see #50834). Users are encouraged to use the 3rd-party plugins instead.
