### ISSUE TITLE
"Collect geometries" creates incomplete/empty ouput

### ISSUE THREAD

**Issue by lucamanga** [qgis/QGIS#30208]
**Describe the bug**

Trying with the attached SHP file, Collect features (on "codice" field) discards some geometries

**How to Reproduce**

1. Download this zip (shp file)
[roads.zip](https://github.com/qgis/QGIS/files/3290007/roads.zip)
2. Go to Processing then to "Collect geometries"
3. Select "codice" as a UNIQUE ID field and execute

you can see that the collected layer has lines missing

**QGIS and OS versions**

Tried with 3.4.8 LTR and 3.6.3

**Comment by gioman** [comment]
Also on master. Collecting without using the "unique id" parameter (that is optional) produces and empty output.

Note: attached shape is in 32632 epsg (is missing the prj file).

**Comment by lucamanga** [comment]
In reality, this is epsg 25832; but the problem occurs too with that projection

**Comment by lucamanga** [comment]
Can you put this fix in 3.4.9 LTR, too? Thank you :+1:

**Comment by nyalldawson** [comment]
@lucamanga already done!
