### ISSUE TITLE
Field Calculator wont save updated data, just freezing/not responding

### ISSUE THREAD

**Issue by kenjiography** [qgis/QGIS#30201]

**Comment by m-kuhn** [comment]
Thank you for reporting this.
As it currently stands it's hard to analyze the problem and eventually fix it. Please add the information suggested by the [bug report template](https://github.com/qgis/QGIS/issues/new?assignees=&labels=Bug&template=bug_report.md&title=) so this issue report gets in a good state.

**Comment by luipir** [comment]
I would close by default any bug report without description and leave to reopen it to the author after updated the issue.

**Comment by gioman** [comment]
Please add description as requested... reopen when done! Thanks
