### ISSUE TITLE
[processing] select by expression - combobox are empty

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#30218]
Starting algorithm, the comboboxes:
'**Expression**' (1) and '**Edit current selection for:**' (2) are always empty!

![image](https://user-images.githubusercontent.com/7631137/59517128-2ad6d500-8ec3-11e9-971f-8db52757fb3d.png)

OSGeo4W64 Win10 64b

```
Versione di QGIS 3.7.0-Master
Revisione codice QGIS 8fdfd7daf8
Compilato con Qt 5.11.2
Esecuzione con Qt 5.11.2
Compilato con GDAL/OGR 2.4.1
Esecuzione con GDAL/OGR 2.4.1
Compilato con GEOS 3.7.2-CAPI-1.11.0
Esecuzione con GEOS 3.7.2-CAPI-1.11.0 b55d2125
Versione client PostgreSQL 9.2.4
Versione SpatiaLite 4.3.0
Versione QWT 6.1.3
Versione QScintilla2 2.10.8
Compiled against PROJ 5.2.0
Running against PROJ Rel. 5.2.0, September 15th, 2018
Questa copia di QGIS scrive messaggi di debug. 
OS Version Windows 10 (10.0)
```

**Comment by gioman** [comment]
> Starting algorithm, the comboboxes:
> '**Expression**' (1) and '**Edit current selection for:**' (2) are always empty!

@pigreco that seems about right.

**Comment by pigreco** [comment]
@gioman 

in 3.4.8 LTR: '**Edit current selection for:**' (2) has a default value
![image](https://user-images.githubusercontent.com/7631137/59519907-28777980-8ec9-11e9-9316-1fc8ad6f428e.png)
