### ISSUE TITLE
PostGIS rasters show as geometryless tables in QGIS browser

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#30211]
**Describe the bug**
PostGIS rasters show as geometryless tables in QGIS browser, while they show ok (and are added ok) using DB Manager.

**How to Reproduce**

load a raster in your DB, then browse it in QGIS Browser and DB Manager to see the difference.

In fact if in you connection parameters you don't check the option to show geometryless tables, then the raster layer name won't even show in the browser.

QGIS master on Linux.

**Comment by nyalldawson** [comment]
This is fixed now, right?

**Comment by gioman** [comment]
> This is fixed now, right?

@nyalldawson tested master and yes, seems fixed now! thanks.
