### ISSUE TITLE
Support for cells in mesh calculator

### ISSUE THREAD

**Issue by saberraz** [qgis/QGIS#30219]
Currently, mesh calculator only supports vertex-centred meshes. But in some cases (e.g. UGRID netcdf), values are stored on the edges.

**Comment by PeterPetrik** [comment]
https://github.com/qgis/QGIS/blob/282d88b43fdc95adbaa9a92f81f4646cf4d67667/src/analysis/mesh/qgsmeshcalcutils.cpp#L109
