### ISSUE TITLE
Excessive Commit/RAM usage when drawing project

### ISSUE THREAD

**Issue by Saijin-Naib** [qgis/QGIS#30225]
**Describe the bug**
QGIS is allocating tons of RAM on and off (upwards of 6GB, then releasing and back down to about 500MB or so, and then jumping back up & back down again), with a HUGE commit size of about 18GB. This causes my entire machine to become mostly unresponsive. Screenshot of Task Manager showing QGIS and ArcGIS Desktop 10.7 rendering the (mostly) same project is attached. [I am re-creating the ArcGIS project in QGIS to begin an eventual migration away from ArcGIS, so testing side-by-side]

**How to Reproduce**
Seemingly this bug has something to do with labeling the polygons. I have the cadastral (tax parcel) layer set to draw the Address Number centered in the polygon provided the label fits. There are around 11k of these within the project. Perhaps the testing of the label collision is very intensive?
The RAM/Commit dropped significantly after QGIS finished drawing the map and placed all of two labels.

I believe a contributing factor is my QGIS project pointing at our ESRI File Geodatabase which resides on a network share. The layers all reference this location via UNC path. I also feel like the introduction of Filters on the layers exacerbates this problem, somehow. I don't recall seeing these types of issues with most of the same data copied into a local Geopackage.

**QGIS and OS versions**
QGIS version | 3.6.3-Noosa | QGIS code revision | 0c5774c068
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.0 | Running against GEOS | 3.7.2-CAPI-1.11.0 b55d2125
PostgreSQL Client Version | 9.2.4 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018

**Additional context**
I am unable to share the data at this time.

Image of RAM/Commit when QGIS is on Recent Projects screen:
![QGIS_FreshLoad](https://user-images.githubusercontent.com/19295950/59522828-aaea4400-8e9d-11e9-97bd-7b8ce57a44d0.png)

Example image of RAM/Commit when QGIS is struggling with the project:
![QGIS_High](https://user-images.githubusercontent.com/19295950/59522833-ade53480-8e9d-11e9-8ca4-3908008a6a92.png)

**Comment by Saijin-Naib** [comment]
Stabilized memory usage after Memory/Cache clean using CleanMem for project in ArcGIS Desktop 10.7.1: 20mb physical / 759mb Commit
![image](https://user-images.githubusercontent.com/19295950/69278332-199b9e00-0bb0-11ea-9d4e-a1de54c0ad54.png)

Stabilized memory usage after Memory/Cache clean using CleanMen for translated project pointed to FGDB in QGIS 3.10: 223mb physical / 2.4gb Commit
![image](https://user-images.githubusercontent.com/19295950/69279492-78621700-0bb2-11ea-8e6e-1bf09035b1c4.png)

Stabilized memory usage after Memory/Cache clean using CleanMem for translated project pointed to GPKG in QGIS 3.10: 135mb physical / 2.3gb Commit
![image](https://user-images.githubusercontent.com/19295950/69278407-4780e280-0bb0-11ea-8e88-cd51da3a5406.png)

What I believe this demonstrates is that the problem before was likely down to some data that were residing in our FGDB.

In the interim, I've worked on a data [processing/standarization Processing Model](https://github.com/Saijin-Naib/QGIS-Processing-Models/blob/master/CleanUp.model3) that I've used against every piece of vector data that had been stored in our FGDB, and then using ArcCatalog, have moved the data from my resultant GPKG back to a new/clean FGDB. I believe that there must have been corrupted or otherwise damaged data that existed prior that was causing the excessive memory consumption and commit size when I had my QGIS pointed at that version of the FGDB, as the differences now seem completely negigble between QGIS pointed at the cleaned FGDB representation of the cleaned GPKG data, and the cleaned GPKG data itself.

**Comment by nyalldawson** [comment]
> What I believe this demonstrates is that the problem before was likely down to some data that were residing in our FGDB.

Can you share the database? If it's a leak in either qgis or gdal I'd like to investigate

**Comment by Saijin-Naib** [comment]
> What I believe this demonstrates is that the problem before was likely down to some data that were residing in our FGDB.
> 
> Can you share the database? If it's a leak in either qgis or gdal I'd like to investigate

Highly unlikely... I'll have to check and see with IT what the oldest backup they have is, and I'd need to get approval to share the database outside of our organization, which I've not met with success in prior inquiries.

I'll try my best, however.

**Comment by Saijin-Naib** [comment]
@nyalldawson, would you be able to walk me through collecting what debug info you need, or possibly take a look by remote, or do you absolutely need the dataset in question?

**Comment by nyalldawson** [comment]
@Saijan-Naib I'd need the dataset-- there's specialised tools I'd need to use to diagnose the issue

**Comment by Saijin-Naib** [comment]
@nyalldawson , still no approval to share the dataset externally.

**Comment by mbalinos** [comment]
Hi @Saijin-Naib and @nyalldawson !
My name is Marygrace. Regular user of QGIS but new to Github. I am not sure if this is the right thread but seeing the issue title regarding the RAM,, this could be related. I am using QGIS 3.12 in a XUbuntu 16.04 OS on an ASUS UX303U laptop to make some maps with DEM Alos Palsar raster files and its Hillshade version (around 150MB x4 files) as base maps overlay-ed by some vector layers and I noticed that the RAM Usage is increasing as I work. While it draws, the RAM usage had reached around 10GB or more and also used the allocated swipe (the laptop has a max of 12GB RAM). I had to force kill the program and start again. (When I start the program, the RAM used is of minimum around 500MB and stayed at around 1GB if I do not move the workspace area. What can you recommend I should do? Thank you.

**Comment by gioman** [comment]
> @nyalldawson , still no approval to share the dataset externally.

@Saijin-Naib any news?

**Comment by Saijin-Naib** [comment]
> @Saijin-Naib any news?

Unfortunately not. I have left that position and they never gave me access to the backups.

**Comment by gioman** [comment]
> Unfortunately not. I have left that position and they never gave me access to the backups.

@Saijin-Naib so what we do with this ticket?
