### ISSUE TITLE
GRASS GISRC filename is hardcoded to GRASS 6

### ISSUE THREAD

**Issue by pmav99** [qgis/QGIS#30238]
**Describe the bug**

When opening a GRASS mapset, the GISRC filename is hardcoded to `grassrc6`. 

**QGIS and OS versions**

I've tested this on 

- Windows: QGIS 3.4.8 and 3.6.3
- Linux: QGIS 3.4.8, 3.7

**Additional context**

This is the line that causes the issue: https://github.com/qgis/QGIS/blame/6051c7b4b656c2b17aac0a0a103b6fe1fe4e6dde/src/providers/grass/qgsgrass.cpp#L941

Obviously this is a minor issue, but I was trying to debug a GRASS issue on Windows and it made me think that QGIS was using GRASS 6 instead of 7.

I can make a pull request, but I am not sure what the filename should be (`grass` vs `grass7` etc)

**Comment by gioman** [comment]
Here on Ubuntu 18.04/QGIS master can't find such file anywhere after opening a mapset, where should be located?

**Comment by pmav99** [comment]
GISRC is a GRASS environment variable. You can read about it [here](https://grass.osgeo.org/grass76/manuals/variables.html). 

The exact  value of the ENV variable depends on OS and configuration. The easiest way to find it is to check:
``` 
Settings -> Options -> System -> Current environment variables 
```
On linux, it should be something like:
```
/tmp/<username>/grass6-<username>-<pid>/gisrc
```

**Comment by lbartoletti** [comment]
By default, GISRC is $HOME/.grass7/rc  and $HOME/.grass6rc for grass6 on unix (grass7)

**Comment by gioman** [comment]
> By default, GISRC is $HOME/.grass7/rc for grass7 and $HOME/.grass6rc for grass6 on unix

Processing uses /tmp apparently

**Comment by pmav99** [comment]
Disclaimer: I don't have any experience with GRASS 6 (with or without QGIS)

I tried to read the code a bit more carefully. I think that [`openMapset()`](https://github.com/qgis/QGIS/blob/6051c7b4b656c2b17aac0a0a103b6fe1fe4e6dde/src/providers/grass/qgsgrass.cpp#L845-L1030):

1. Creates `gisrc` in a directory in `/tmp`. The directory name is `grass6-<PID>`. Since `pid` is there the name is going to be unique anyway. As a result, I don't see any reason to use `grass6` instead of plain `grass`. Arguable, this could lead to some confusion if both GRASS6 and GRASS7 are being used simultaneously, but I am not sure if this is still a supported usecase. 

1. QGIS is trying to read `~/.grassrc6`. if the file exists:

- it ignores lines with `GISBASE`, `LOCATION` and `MAPSET`
- if `GRASS_GUI` exists, it uses its value. If not it defaults on `wxpython`. On GRASS 7 this should not be relevant, as the only gui is using wx..
- it copies any other line.

WRT the first point, my proposal is to apply this patch [here](https://github.com/qgis/QGIS/blame/6051c7b4b656c2b17aac0a0a103b6fe1fe4e6dde/src/providers/grass/qgsgrass.cpp#L919)
``` diff
- sTmp = QDir::tempPath() + "/grass6-" + user + "-" + QString::number( pid );
+ sTmp = QDir::tempPath() + "/grass-" + user + "-" + QString::number( pid );
```

I can't really comment if reading `~/.grassrc6` is relevant any more. I guess it depends if people are still using grass6 or not.

**Comment by gioman** [comment]
> I guess it depends if people are still using grass6 or not.

not in recent versions of QGIS
