### ISSUE TITLE
Wrong default paramenter for grass r.stream.extract

### ISSUE THREAD

**Issue by mone27** [qgis/QGIS#30231]
In the r.stream.extract routine the default value of "Minimium flow accumulation for streams" (python identifier: threshold) is 0, which isn't a valid value for GRASS. ![image](https://user-images.githubusercontent.com/17617810/59550276-f4539580-8f68-11e9-8961-1d6a09b81d12.png)
So if you run the routine wit the default parameters you get this error from GRASS:
`ERROR: Threshold must be > 0 but is 0.000000`

If you change that value and run the routine everything works as expected.
My GRASS version is 7.6.0, installed from[ fedora repo](https://koji.fedoraproject.org/koji/buildinfo?buildID=1211446) .
My OS is fedora linux 30.

Here there is the full log:

Loading resulting layers
QGIS version: 3.6.3-Noosa
Qt version: 5.12.1
GDAL version: 2.3.2
GEOS version: 3.7.1-CAPI-1.11.1 27a5e771
PROJ version: 520
Processing algorithm…
Algorithm 'r.stream.extract' starting…
Input parameters:
{ 'GRASS_OUTPUT_TYPE_PARAMETER' : 0, 'GRASS_RASTER_FORMAT_META' : '', 'GRASS_RASTER_FORMAT_OPT' : '', 'GRASS_REGION_CELLSIZE_PARAMETER' : 0, 'GRASS_REGION_PARAMETER' : None, 'GRASS_VECTOR_DSCO' : '', 'GRASS_VECTOR_EXPORT_NOCAT' : False, 'GRASS_VECTOR_LCO' : '', 'accumulation' : None, 'd8cut' : None, 'depression' : None, 'direction' : 'TEMPORARY_OUTPUT', 'elevation' : '/home/simone/Documents/appunti_università/idrologia/geodati/DEM_trebbia_valsigiara.tif', 'memory' : 300, 'mexp' : 0, 'stream_length' : 0, 'stream_raster' : 'TEMPORARY_OUTPUT', 'stream_vector' : 'TEMPORARY_OUTPUT', 'threshold' : 0 }

g.proj -c proj4="+proj=utm +zone=32 +datum=WGS84 +units=m +no_defs"
r.external input="/home/simone/Documents/appunti_università/idrologia/geodati/DEM_trebbia_valsigiara.tif" band=1 output="rast_5d04c655d50847" --overwrite -o
g.region n=4945286.9231 s=4924789.4001 e=530185.1373 w=511686.7615 res=19.998244108108022
r.stream.extract elevation=rast_5d04c655d50847 threshold=0 mexp=0 stream_length=0 memory=300 stream_raster=stream_rasterb3803f7e87b24af98afa3ffe10b87212 stream_vector=stream_vectorb3803f7e87b24af98afa3ffe10b87212 direction=directionb3803f7e87b24af98afa3ffe10b87212 --overwrite
g.region raster=stream_rasterb3803f7e87b24af98afa3ffe10b87212
r.out.gdal -t -m input="stream_rasterb3803f7e87b24af98afa3ffe10b87212" output="/tmp/processing_4de7262000dd4a3b9e5eeef05253b060/ccd8d7bae727488caae9f3fe2a853eca/stream_raster.tif" format="GTiff" createopt="TFW=YES,COMPRESS=LZW" --overwrite
v.out.ogr type="auto" input="stream_vectorb3803f7e87b24af98afa3ffe10b87212" output="/tmp/processing_4de7262000dd4a3b9e5eeef05253b060/1bc59663772e4823b08c28b23a0f2e9d/stream_vector.gpkg" format="GPKG" --overwrite
g.region raster=directionb3803f7e87b24af98afa3ffe10b87212
r.out.gdal -t -m input="directionb3803f7e87b24af98afa3ffe10b87212" output="/tmp/processing_4de7262000dd4a3b9e5eeef05253b060/83dd07f2fbd24851838b10357945f479/direction.tif" format="GTiff" createopt="TFW=YES,COMPRESS=LZW" --overwrite
Starting GRASS GIS...
Executing </tmp/processing_4de7262000dd4a3b9e5eeef05253b060/grassdata/grass_batch_job.sh> ...
Default region was updated to the new projection, but if you have multiple mapsets `g.region -d` should be run in each to update the region from the default
Projection information updated
Over-riding projection check
Reading band 1 of 1...
Link to raster map <rast_5d04c655d50847> created.
ERROR: Threshold must be > 0 but is 0.000000
ERROR: Raster map <stream_rasterb3803f7e87b24af98afa3ffe10b87212> not found
ERROR: Raster map or group <stream_rasterb3803f7e87b24af98afa3ffe10b87212> not found
ERROR: Vector map <stream_vectorb3803f7e87b24af98afa3ffe10b87212> not found
ERROR: Raster map <directionb3803f7e87b24af98afa3ffe10b87212> not found
ERROR: Raster map or group <directionb3803f7e87b24af98afa3ffe10b87212> not found
Execution of </tmp/processing_4de7262000dd4a3b9e5eeef05253b060/grassdata/grass_batch_job.sh> finished.
Cleaning up default sqlite database ...
Cleaning up temporary files...
Starting GRASS GIS...
Executing </tmp/processing_4de7262000dd4a3b9e5eeef05253b060/grassdata/grass_batch_job.sh> ...
ERROR: Raster map <stream_rasterb3803f7e87b24af98afa3ffe10b87212> not found
ERROR: Raster map or group <stream_rasterb3803f7e87b24af98afa3ffe10b87212> not found
ERROR: Vector map <stream_vectorb3803f7e87b24af98afa3ffe10b87212> not found
ERROR: Raster map <directionb3803f7e87b24af98afa3ffe10b87212> not found
ERROR: Raster map or group <directionb3803f7e87b24af98afa3ffe10b87212> not found
Execution of </tmp/processing_4de7262000dd4a3b9e5eeef05253b060/grassdata/grass_batch_job.sh> finished.
Cleaning up default sqlite database ...
Cleaning up temporary files...
Execution completed in 2.42 seconds
Results:
{'direction': <QgsProcessingOutputLayerDefinition {'sink':TEMPORARY_OUTPUT, 'createOptions': {'fileEncoding': 'System'}}>,
'stream_raster': <QgsProcessingOutputLayerDefinition {'sink':TEMPORARY_OUTPUT, 'createOptions': {'fileEncoding': 'System'}}>,
'stream_vector': <QgsProcessingOutputLayerDefinition {'sink':TEMPORARY_OUTPUT, 'createOptions': {'fileEncoding': 'System'}}>}

Loading resulting layers
The following layers were not correctly generated.<ul><li>/tmp/processing_4de7262000dd4a3b9e5eeef05253b060/1bc59663772e4823b08c28b23a0f2e9d/stream_vector.gpkg</li><li>/tmp/processing_4de7262000dd4a3b9e5eeef05253b060/83dd07f2fbd24851838b10357945f479/direction.tif</li><li>/tmp/processing_4de7262000dd4a3b9e5eeef05253b060/ccd8d7bae727488caae9f3fe2a853eca/stream_raster.tif</li></ul>You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.

**Comment by alexbruy** [comment]
PR #30329
