### ISSUE TITLE
Distance to Nearest Hub make QGis 2.18.28-3 crash

### ISSUE THREAD

**Issue by cartoinddigo** [qgis/QGIS#30237]
Hi there !

After update QGis from 2.18.14-1 to 2.18.28-3 (QGIS-OSGeo4W-2.18.28-3-Setup-x86_64.exe), i can't use this processing : I get a minidump.
Idem with the DistanceMatrix processing...

**Comment by nirvn** [comment]
QGIS 2 has reached its end of life a few months ago. Time to update to the new 3.4 LTR. 

If the new LTR still crashes, please report a new issue. Thanks.
