### ISSUE TITLE
Add Ctrl+W as default shortcut for close project

### ISSUE THREAD

**Issue by dhdeangelis** [qgis/QGIS#30230]
**Feature description.**
The keystroke Ctrl+W closes the currently open project per default.

**Additional context**
The key combination Ctrl+W is usually associated with closing the current work in many packages. It is of course possible to customize this in QGIS, but I believe it can be a nice default configuration. 

This is a suggestion and not a critical issue or feature request.

**Comment by alexbruy** [comment]
See also #23910.
