### ISSUE TITLE
Execute and Load SQL Processing model should expose layer to model

### ISSUE THREAD

**Issue by timlinux** [qgis/QGIS#30240]
In QGIS 3.4.8 macOS

<img width="1054" alt="Screenshot 2019-06-16 at 19 17 38" src="https://user-images.githubusercontent.com/178003/59567247-6ad8bc00-906b-11e9-8034-1e583c97b6e6.png">

Since this algorithm loads a layer it should be possible to use the loaded layer in the next steps of the algorithm, but it does not expose the layer to the processing workflow.

I am not sure if this is a design intent, but it seems like a bug to me.

**Comment by nyalldawson** [comment]
I can't reproduce -- it works for me:
![image](https://user-images.githubusercontent.com/1829991/59570028-14a06300-90d5-11e9-9a54-e5c76d999c04.png)

**Comment by timlinux** [comment]
OK I was being an idiot (was expecting to see the rename layer option in the UI for the alg too but forgot that only dictates the layer name not the ability to pass it to the next alg! Sorry!
