### ISSUE TITLE
Allow data-defined control over grid spacing and offset

### ISSUE THREAD

**Issue by denilsonjesus** [qgis/QGIS#30246]
I'm having trouble using the "Grids" option in the QGIS 3.6.3 composer layout.
If I define the Interval units in Centimeters the coordinates on the map (text) are NOT referenced to the coordinate systems, in my case it is 4674, they are relative to the intervals and not in real coordinates.
![image](https://user-images.githubusercontent.com/28923776/59575633-a6d34780-9092-11e9-898a-39608bcc61c4.png)
If I change to MAP UNIT, the coordinate texts conform to the 4674 system, but in combination with the use of the ATLAS option, which automates several maps with different scales, I get a GRID variation on the map, which on a certain scale(1/500) is with good spacing and for smaller scales (1/3000) is very close spacing, overlapping the coordinates lines and text.
![image](https://user-images.githubusercontent.com/28923776/59575665-cf5b4180-9092-11e9-9c64-5afb3a4f038f.png)
What could it be to do to correct? It would be possible to maintain grid spacing in centimeters, but would the grid text be referenced to the coordinates system? Or, allow the use of formula so that the grid spacing varies according to the map scale controlled by ATLAS?

**Comment by nyalldawson** [comment]
This is a feature request -- the solution would be to allow data-defined overrides on the grid spacing.

**Comment by alexandreparente** [comment]
#27737
