### ISSUE TITLE
setStatusTip() ignored in Qgis3?

### ISSUE THREAD

**Issue by juanmpd** [qgis/QGIS#30249]
With Qgis 2.18 setStatusTip() could be used to show a text in the status bar when you passed the cursor over a tool icon. In Qgis3 the same method still exists but it doesn't seem to do nothing: no matter which version: we have tested it under 3.4 and 3.7Master, as shown in the images below. Is this the expected behavior? Is this function expected to be removed? Or is it a bug?

Snapshot from 2.18
![setStatusTip_2-18](https://user-images.githubusercontent.com/45386331/59606220-db85e400-9110-11e9-8d8f-cef2ff9da1d4.png)

Snapshot from 3.4.X
![setStatusTip_3-4](https://user-images.githubusercontent.com/45386331/59606543-b0e85b00-9111-11e9-9782-d2a3547a5789.png)

Snapshot from 3.7 Master
![setStatusTip_3-7Master](https://user-images.githubusercontent.com/45386331/59606225-de80d480-9110-11e9-9cc5-7fc0425e103b.png)

**Comment by m-kuhn** [comment]
Since https://github.com/qgis/QGIS/pull/4582

**Comment by juanmpd** [comment]
Thanks for a so quick fix!
