### ISSUE TITLE
Traceback when closing QGIS after installing a custom GRASS Processing Provider 

### ISSUE THREAD

**Issue by pmav99** [qgis/QGIS#30241]
Checklist before submitting

- [v] Search through existing issue reports and gis.stackexchange.com to check whether the issue already exists

**Describe the bug**

After opening a GRASS mapset, closing QGIS throws a Python Traceback in a pop-up window.

**How to Reproduce**

1. Open QGIS with GRASS 
2. Open a GRASS mapset. I used the Alaska demo dataset
3. [optionally] Close the mapset. You get the traceback even if you omit this step.
4. Close QGIS
5. The traceback pops up:

```
An error has occurred while executing Python code: 

KeyError: 'ACTIVATE_GRASS7' 
Traceback (most recent call last):
  File "/opt/qgis-git/share/qgis/python/plugins/processing/algs/grass7/Grass7AlgorithmProvider.py", line 88, in unload
    ProcessingConfig.removeSetting('ACTIVATE_GRASS7')
  File "/opt/qgis-git/share/qgis/python/plugins/processing/core/ProcessingConfig.py", line 157, in removeSetting
    del ProcessingConfig.settings[name]
KeyError: 'ACTIVATE_GRASS7'


Python version: 3.7.3 (default, Mar 26 2019, 21:43:19) [GCC 8.2.1 20181127] 
QGIS version: 3.7.0-Master Master, 52d22b8050 

Python Path:
/opt/qgis-git/share/qgis/python
/home/feanor/.local/share/QGIS/QGIS3/profiles/default/python
/home/feanor/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/opt/qgis-git/share/qgis/python/plugins
/usr/lib/python37.zip
/usr/lib/python3.7
/usr/lib/python3.7/lib-dynload
/home/feanor/.local/lib/python3.7/site-packages
/usr/lib/python3.7/site-packages
/home/feanor/.local/share/QGIS/QGIS3/profiles/default/python
```

https://i.imgur.com/vY3bqpN.png

**QGIS and OS versions**

QGIS version | 3.7.0-Master | QGIS code revision | 52d22b8050
-- | -- | -- | --
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Arch Linux |   |  

**More context**

I did debug a little bit and it seems that `Grass7AlgorithmProvider.unload()` is being called twice. The first time `ACTIVATE_GRASS7` gets deleted, but the second time a `KeyError` is being raised.

**Comment by gioman** [comment]
Can't confirm here with QGIS master on Ubuntu 18.04 and the GRASS sample dataset.

**Comment by pmav99** [comment]
OK, I think I figured it out.

The problem is that I am using a [custom Processing Provider](https://gitlab.com/natcapes/natcapes_qgis/tree/master) which subclasses `Grass7AlgorithmProvider`. You cannot trigger the issue if you don't have such a provider installed. When you do though, both providers register themselves using [the same Settings Name](https://github.com/qgis/QGIS/blob/24e56a810cba9d531776af133c4f60158d9a4429/python/plugins/processing/algs/grass7/Grass7AlgorithmProvider.py#L53) (i.e. `ACTIVATE_GRASS7`). So when you close QGIS and the providers get removed one by one, qgis tries to remove the same key twice. And that's how the `KeyError` gets thrown.

The obvious solution is to override the methods that use `ACTIVATE_GRASS7` in the custom provider and change the key to something else. Nevertheless, in order to reduce code maintenance and keep it easy to subclass `Grass7AlrorithmProvider`, I would suggest adding a class attribute named `settingName`:

``` diff
diff --git a/python/plugins/processing/algs/grass7/Grass7AlgorithmProvider.py b/python/plugins/processing/algs/grass7/Grass7AlgorithmProvider.py
index 7284cc902f..abcd2183c3 100644
--- a/python/plugins/processing/algs/grass7/Grass7AlgorithmProvider.py
+++ b/python/plugins/processing/algs/grass7/Grass7AlgorithmProvider.py
@@ -40,9 +40,13 @@ pluginPath = os.path.normpath(os.path.join(
 
 class Grass7AlgorithmProvider(QgsProcessingProvider):
 
-    # Subclasses of `Grass7AlgorithmProvider` should override `descriptionFolder`
-    # and set its value to their own description folder.
+    # Subclasses of `Grass7AlgorithmProvider` should override the following
+    # attributes:
+    #
+    # - `descriptionFolder` should be the path to their own description folder
+    # - `settingName` should be a unique capitalized key.
     descriptionFolder = Grass7Utils.grassDescriptionPath()
+    settingName = 'ACTIVATE_GRASS7'
 
     def __init__(self):
         super().__init__()
@@ -50,7 +54,7 @@ class Grass7AlgorithmProvider(QgsProcessingProvider):
 
     def load(self):
         ProcessingConfig.settingIcons[self.name()] = self.icon()
-        ProcessingConfig.addSetting(Setting(self.name(), 'ACTIVATE_GRASS7',
+        ProcessingConfig.addSetting(Setting(self.name(), self.settingName,
                                             self.tr('Activate'), True))
         if isMac():
             ProcessingConfig.addSetting(Setting(
@@ -83,7 +87,7 @@ class Grass7AlgorithmProvider(QgsProcessingProvider):
         return True
 
     def unload(self):
-        ProcessingConfig.removeSetting('ACTIVATE_GRASS7')
+        ProcessingConfig.removeSetting(self.settingName)
         if isMac():
             ProcessingConfig.removeSetting(Grass7Utils.GRASS_FOLDER)
         ProcessingConfig.removeSetting(Grass7Utils.GRASS_LOG_COMMANDS)
@@ -92,10 +96,10 @@ class Grass7AlgorithmProvider(QgsProcessingProvider):
         ProcessingConfig.removeSetting(Grass7Utils.GRASS_USE_VEXTERNAL)
 
     def isActive(self):
-        return ProcessingConfig.getSetting('ACTIVATE_GRASS7')
+        return ProcessingConfig.getSetting(self.settingName)
 
     def setActive(self, active):
-        ProcessingConfig.setSettingValue('ACTIVATE_GRASS7', active)
+        ProcessingConfig.setSettingValue(self.settingName, active)
 
     def createAlgsList(self):
         algs = []
```
