### ISSUE TITLE
Grass Shell seems to be broken on Windows 

### ISSUE THREAD

**Issue by pmav99** [qgis/QGIS#30258]
**Describe the bug**

After opening a GRASS mapset, clicking on the GRASS Shell does nothing. There is no warning and there is no traceback. Still the shell window does not open.

**How to Reproduce**
1. Create a new VM with windows 10 (Ι also tested this on windows server 2016)
2. Install QGIS. I've tried:
    - QGIS 3.4.8
    - QGIS 3.6.3
    - If memory serves I also tried this on 3.7 (master) but I don't have access to that VM now, so ignore this for now.
3. Activate the GRASS plugin from the plugins menu. 
4. Open a GRASS mapset. I used the alaska demo dataset.
4. Click on the GRASS Shell button. 

expected result: A shell should open.

**QGIS and OS versions**

https://i.imgur.com/Xn54NwX.png

Any feedback, would be appreciated.

**Comment by alexbruy** [comment]
Duplicates #28414
