### ISSUE TITLE
QGis crash after deletion of a file with the explorer of QGis (3.2.3 Bonn for PC)

### ISSUE THREAD

**Issue by LudovicCepre** [qgis/QGIS#30268]
h2. User Feedback

It was juste after the deletion of an .shp file using the file exploring interface of Qgis 3.2.3 Bonn for Windows

h2. Report Details

*Crash ID*: 3ab7493881d793117fb22e6776cee47bf3c30628

*Stack Trace*
<pre>
wildcards :
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.2.3-Bonn
QGIS code revision: commit:9b176802e5
Compiled against Qt: 5.9.2
Running against Qt: 5.9.2
Compiled against GDAL: 2.2.4
Running against GDAL: 2.2.4

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.16299

**Comment by gioman** [comment]
@LudovicCepre update to the latest 3.4.*, create a new/clean QGIS profile (no 3rd party plugins) and try again.

**Comment by LudovicCepre** [comment]
Many thanks Giovanni !
In fact i send the reporting to help (not sure it was usefull...), and i
don't have any problems using QGis, even and older version. I think it is
remarquably stable...
have a good week !
Ludovic


Le mer. 19 juin 2019 à 13:00, Giovanni Manghi <notifications@github.com> a
écrit :

**Comment by m-kuhn** [comment]
Thanks for reporting this.
Since version 3.2 is end of life and the stack trace does not give precise instructions, this is unlikely to lead to further fixes.

If you find another crash on a currently supported version, please open a new ticket.
