### ISSUE TITLE
Interpolationcomplement in QGIS 3.6.3

### ISSUE THREAD

**Issue by pquirogaARG** [qgis/QGIS#30261]
In QGIS version 3.6.3 the complement for inverse distance interpolation (IDW) is not available.
I've followed the steps of administering add-ons/all... and it doesn't seem to work.
How do I do this analysis with this version?

**Describe the bug**
In QGIS version 3.6.3 the complement for inverse distance interpolation (IDW) is not available.
I've followed the steps of administering add-ons/all... and it doesn't seem to work.
How do I do this analysis with this version?
Thankyou

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by alexbruy** [comment]
IDW and TIN interpolation were moved to the Processing
