### ISSUE TITLE
QgsOgcUtils: Parsing Literal Filter node against QLongLong field type

### ISSUE THREAD

**Issue by rldhont** [qgis/QGIS#30263]
**Describe the bug**
When building an expression based on OGC Filter Document, the Literal Node seems to be not well parsed by QgsOgcUtils when the field type is QLongLong

**How to Reproduce**
Run this code in the Python console
```py
from PyQt5.QtXml import QDomDocument
from qgis.core import QgsOgcUtils, QgsVectorLayer, QgsField

f = '''<?xml version="1.0" encoding="UTF-8"?>
    <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc">
      <ogc:And>
        <ogc:PropertyIsGreaterThan>
          <ogc:PropertyName>id</ogc:PropertyName>
          <ogc:Literal>1</ogc:Literal>
        </ogc:PropertyIsGreaterThan>
        <ogc:PropertyIsLessThan>
          <ogc:PropertyName>id</ogc:PropertyName>
          <ogc:Literal>3</ogc:Literal>
        </ogc:PropertyIsLessThan>
      </ogc:And>
    </ogc:Filter>
'''
d = QDomDocument('filter')
d.setContent(f, True)

vl = QgsVectorLayer('Point', 'vl', 'memory')
vl.dataProvider().addAttributes([QgsField('id', QVariant.LongLong)])
vl.updateFields()
e = QgsOgcUtils.expressionFromOgcFilter(d.documentElement(),vl)
e.expression()
```
The expression is:
```
id > [unsupported type: qlonglong; value: 1] AND id < [unsupported type: qlonglong; value: 3]
```
And not:
```
id > 1 AND id < 3
```
**QGIS and OS versions**

* QGIS version: 3.4.8-Madeira
* QGIS code revision: 853abe0f50
* Compiled against Qt: 5.9.5
* Running against Qt: 5.9.5

**Additional context**

I found the issue through QGIS Server tests when working on [Server] Use primary keys to build feature id #10034

**Comment by rldhont** [comment]
@pblottiere In the PR #10034 I have already done an enhancement in the Literal parser:
https://github.com/qgis/QGIS/pull/10034/commits/cdfa47d41c45afac45b1a5ad070a507f3d5e8800

I have also tested this OGC Filter:
```
    <?xml version="1.0" encoding="UTF-8"?>
    <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc">
      <ogc:And>
        <ogc:PropertyIsGreaterThan>
          <ogc:PropertyName>id</ogc:PropertyName>
          <ogc:Literal>1</ogc:Literal>
        </ogc:PropertyIsGreaterThan>
        <ogc:PropertyIsLessThan>
          <ogc:PropertyName>id</ogc:PropertyName>
          <ogc:Literal>3</ogc:Literal>
        </ogc:PropertyIsLessThan>
      </ogc:And>
    </ogc:Filter>
```
and get this expression:
```
id > NULL AND id < NULL
```

**Comment by pblottiere** [comment]
Hi @rldhont,

> The expression is:
```
id > [unsupported type: qlonglong; value: 1] AND id < [unsupported type: qlonglong; value: 3]
```

What do you think about this bugfix https://github.com/qgis/QGIS/pull/30290?

> I have also tested this OGC Filter:

```
<?xml version="1.0" encoding="UTF-8"?>
    <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc">
      <ogc:And>
        <ogc:PropertyIsGreaterThan>
          <ogc:PropertyName>id</ogc:PropertyName>
          <ogc:Literal>1</ogc:Literal>
        </ogc:PropertyIsGreaterThan>
        <ogc:PropertyIsLessThan>
          <ogc:PropertyName>id</ogc:PropertyName>
          <ogc:Literal>3</ogc:Literal>
        </ogc:PropertyIsLessThan>
      </ogc:And>
    </ogc:Filter>
```
> and get this expression:

```
id > NULL AND id < NULL
```

I'm probably not totally awaken, but I don't see any differences with the previous filter?

**Comment by rldhont** [comment]
The right filter for getting
> ```
> id > NULL AND id < NULL
> ```
is
> ```
>     <?xml version="1.0" encoding="UTF-8"?>
>     <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc">
>       <ogc:And>
>         <ogc:PropertyIsGreaterThan>
>           <ogc:PropertyName>id</ogc:PropertyName>
>           <ogc:Literal>1.0</ogc:Literal>
>         </ogc:PropertyIsGreaterThan>
>         <ogc:PropertyIsLessThan>
>           <ogc:PropertyName>id</ogc:PropertyName>
>           <ogc:Literal>3.0</ogc:Literal>
>         </ogc:PropertyIsLessThan>
>       </ogc:And>
>     </ogc:Filter>
> ```
And it's right, even if I was thinking that the code is done to test if the value can be a longlong

**Comment by rldhont** [comment]
I have wrote some PyQgsOgcUtils tests. Do you think I can propose it ?

**Comment by pblottiere** [comment]
> I have wrote some PyQgsOgcUtils tests. Do you think I can propose it ?

Yes of course, it'd be very welcome :+1:

Thanks @rldhont!

**Comment by elpaso** [comment]
@rldhont I'm sure you know that there are also C++ tests for that class but I don't see a problem in having Py tests too.

**Comment by rldhont** [comment]
@elpaso I was wondering if it will be accepted to have C++ and Python tests for the same class.

**Comment by elpaso** [comment]
I think there are some already. Is there a particular reason for doing these in Python? 
In general, the advantage of having tests in python is that you check the functionality and the bindings at the same time.

**Comment by rldhont** [comment]
It is easiest for me to write test in Python, and I would like to test the binding and the way to use this class in Python.

**Comment by pblottiere** [comment]
>  I was wondering if it will be accepted to have C++ and Python tests for the same class.

As soon as tests are not redundant between C++ and Python, I don't think that's a problem.

**Comment by rldhont** [comment]
@pblottiere @elpaso I have open a PR #30378 with the tests.
