### ISSUE TITLE
'DWG/DXF-Import' how to change the charset or encoding 

### ISSUE THREAD

**Issue by Jerry-goodboy** [qgis/QGIS#30267]
Environment:
QGIS 3.6, 
macOS 10.14.5, 
DWG from AutoCAD 2004/2005/2006 and it contains Chinese characters 

issues:
the Chinese characters are garbled, like this:
![image](https://user-images.githubusercontent.com/9030784/59749476-a82d8b80-92af-11e9-997f-2e60fa442a4b.png)

what can I do?

**Comment by Jerry-goodboy** [comment]
@misto @gvellut @spilth @epifanio

**Comment by gioman** [comment]
@Jerry-goodboy add a sample of the data

**Comment by Jerry-goodboy** [comment]
[test_dxf_2004.dxf.zip](https://github.com/qgis/QGIS/files/3305979/test_dxf_2004.dxf.zip)
[test_dwg_2004.dwg.zip](https://github.com/qgis/QGIS/files/3306025/test_dwg_2004.dwg.zip)

this dxf file is created by QCAD 3.22.1.0 (3.22.1) and saved as cad2004 dxf format on macOS, It's displayed correctly here for me when I use QGIS3.6 to import the dwg format, on the contrary, the dxf is displayed incorrectly, when I used the dxf and dwg which created by cad2004 on Windows platform, both of them are displayed incorrectly, the Chinese characters are garbled, here is my thought, the first reason is the encoding, the other one is that macOS is lack of some fonts whick the Windows has

**Comment by Jerry-goodboy** [comment]
@gioman

**Comment by Jerry-goodboy** [comment]
anyone else can help me，THX

**Comment by ldh999** [comment]
try change layer names of dwg

**Comment by Jerry-goodboy** [comment]
> try change layer names of dwg

I have no way to do that, cause the layer name with Chinese has to be shown just as it is, so I have to change the charset to import the DWG into QGIS

**Comment by ldh999** [comment]
Open the dxf file with notepad and converted the encoding to ANSI while saving，then opened the file again in QGIS，both the layer names and the text layers can display properly

今天找到解决方法了，用记事本打开DXF文件，选择ANSI编码另存后再用QGIS打开就一切正常了，包括图层名称和标注文字都可以正常显示了

**Comment by ldh999** [comment]
> > try change layer names of dwg
> 
> I have no way to do that, cause the layer name with Chinese has to be shown just as it is, so I have to change the charset to import the DWG into QGIS

今天找到解决方法了，用记事本打开DXF文件，选择ANSI编码另存后再用QGIS打开就一切正常了，包括图层名称和标注文字都可以正常显示了

**Comment by Jerry-goodboy** [comment]
> > > try change layer names of dwg
> > 
> > 
> > I have no way to do that, cause the layer name with Chinese has to be shown just as it is, so I have to change the charset to import the DWG into QGIS
> 
> 今天找到解决方法了，用记事本打开DXF文件，选择ANSI编码另存后再用QGIS打开就一切正常了，包括图层名称和标注文字都可以正常显示了

还未找机会试，先Mark一下，留着以后用

**Comment by DavidHJong** [comment]
> Open the dxf file with notepad and converted the encoding to ANSI while saving，then opened the file again in QGIS，both the layer names and the text layers can display properly
> 
> 今天找到解决方法了，用记事本打开DXF文件，选择ANSI编码另存后再用QGIS打开就一切正常了，包括图层名称和标注文字都可以正常显示了

实测有效。在QGIS中的默认编码是UTF-8，所以我另外测试了用Notepad把dxf存成UTF-8格式，但是用QGIS打开后是乱码。你知道为什么存成ANSI就可以正常显示吗？

**Comment by applefi87** [comment]
QGIS 亂碼 問號 
Hi! I SOLVE WITH DIFFERENT WAY!! My situation is all chinese word become ?????? (Question mark)
The way idh999 not effect for me.
My file is  dwg(Autocad),I output as .dxf file !!!!!! The most important part is set file type as R12/LT2 DXF (not others like 20XX/LTLT20XX)!!!!!

**Comment by IKangXu** [comment]
实测，有用。

**Comment by winchop** [comment]
导出dxf的时候让选择encoding，导入的时候却没有这个选项。

**Comment by winchop** [comment]
2023年了 这个问题可以参考这个链接（follow this link） [https://ezdxf.readthedocs.io/en/stable/dxfinternals/fileencoding.html](url)  
DXF R2004 (AC1018) 格式 默认的编码为 ANSI_1252 （by default if $DWGCODEPAGE is not set）
DXF R2007 (AC1021) 但是到2007改成默认为 utf-8 （the drawing file is UTF-8 encoded ）
QGIS的import dxf 应该是默认所有的dxf编码为1252 ，当尝试导入高版本的dxf文件时 ，导致文字编码错误。
guess the defult import dxf encode setting is ANSI 1252 ，so when someone try to import a higher file format like R2007 ，will lead to a wrong charset encoding .
可以选用这个插件 
AnotherDXFImporter Plugin 
[https://plugins.qgis.org/plugins/AnotherDXF2Shape/](url)

**Comment by aka863** [comment]
qgis 3.26.3 still has this bug.

**Comment by xiaosagua** [comment]
When exporting layers from QGIS 3.34 to the local gdb and setting the 'FEATUREDATASET' parameter to Chinese, the locally created dataset names are garbled. Is there a solution?
