### ISSUE TITLE
Union to Geopackage format returns erronious results

### ISSUE THREAD

**Issue by wburt** [qgis/QGIS#30278]
**Describe the bug**

When using the processing union tool and writing directly to Geopackage the results are incorrect.  
**How to Reproduce**

1. Create a project EPSG:3005 and add the following wkt as temporary scratch layer 
* test_layer_1
wkt_geom	fid
Polygon ((1159895 814249, 1160176 795518, 1200916 795424, 1200916 814530, 1159895 814249))	3
* test_layer_2
wkt_geom	fid
Polygon ((1167200 819774, 1167575 789430, 1192487 788868, 1188366 820898, 1167200 819774))	1
2. Use the processing tool union with these two features as inputs and set the output to an existing geopackage with a unique layer name

3. The inputs are shown below in blue and yellow.  The output is diagonally hatched.  The procedure results in correct outputs if union output is set to shape files and in-memory layer file types.

![image](https://user-images.githubusercontent.com/10637797/59797071-af46a080-9293-11e9-98a7-cdd54de7f47c.png)

**QGIS and OS versions**
Windows 10

QGIS version | 3.4.4-Madeira | QGIS code revision | f6ddc62fdb
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 2.4.0 | Running against GDAL/OGR | 2.4.0
Compiled against GEOS | 3.7.0-CAPI-1.11.0 | Running against GEOS | 3.7.0-CAPI-1.11.0 673b9939
PostgreSQL Client Version | 9.2.4 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 520 | Running against PROJ | 5.2.0

**Additional context**

**Comment by roya0045** [comment]
I did a quick test with 3.4.0 and two features in EPSG 4326. Saving to a temporary layer or a geopackage provided the same results.

Is this a matter of projection?

**Comment by wburt** [comment]
Great.  I can also confirm that the bug does not appear in 3.6.3:

QGIS version | 3.6.3-Noosa | QGIS code revision | 0c5774c068
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.0 | Running against GEOS | 3.7.2-CAPI-1.11.0 b55d2125
PostgreSQL Client Version | 9.2.4 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018

**Comment by nyalldawson** [comment]
3.4 is end of life. If this works correctly in 3.6+ it can be closed
