### ISSUE TITLE
Add Percentile Beaks to raster grid Styling Mode

### ISSUE THREAD

**Issue by Detritalgeo** [qgis/QGIS#30279]
**Feature description.**
Right now there is Continuous, Equal Interval and Quantile. It would be fantastic to be able to add a percentile based mode as well, either pre-set (my go to is 30th/60th/80th/90th/95th/98th/99th/100)  or manual percentile bins.

**Comment by gioman** [comment]
I'm pretty sure that this feature request already exist.

**Comment by Detritalgeo** [comment]
> I'm pretty sure that this feature request already exist.

Apologies, I did a search for percentile but was not able to locate a match.

**Comment by alexbruy** [comment]
Duplicates #18582.
