### ISSUE TITLE
Raster file type "SAR CEOS" is not recognized

### ISSUE THREAD

**Issue by yuvalutilis** [qgis/QGIS#30286]
When opening a raster file from ALOS-2 PALSAR-2 satellite, product level 2.1 it is supposed to be recognized as [SAR_CEOS](https://gdal.org/drivers/raster/sar_ceos.html) format type. However, QGIS turns it into virtual raster (VRT) and change the raster characteristics. 
When using GDAL INFO it recognize the raster properly as SAR_CEOS.

I suspect that the issue is related to the fact the file is projected using GCP's. When i removed the GCP's using GDAL, QGIS has recognized as SAR_CEOS, however in that case i lost the geographic location so it is not a solution. 

The bug creates an unwanted re-sampling which change the raster characteristics and add row & columns to the imagery.

**Comment by gioman** [comment]
@yuvalutilis add sample data.

**Comment by yuvalutilis** [comment]
@gioman Thanks, please find examples below.

QGIS file info - Raster shows as VRT - incorrect

![SAR_CEOS_QGIS](https://user-images.githubusercontent.com/47394659/59847218-952bc180-936a-11e9-8eb6-6b1aea82cc7d.png)

GDAL  file info - Raster shows as SAR_CEOS- correct
![SAR_CEOS_GDALINFO](https://user-images.githubusercontent.com/47394659/59847221-952bc180-936a-11e9-83e8-73120f07873d.png)

**Comment by gioman** [comment]
> @gioman Thanks, please find examples below.

@yuvalutilis we need actual *data*

**Comment by yuvalutilis** [comment]
Please download the sample data from [here](https://utiliscorp-my.sharepoint.com/:u:/p/yuval/EfLtuqxtuGZBoIUw5BAwOY0BjZ-iAmF3RevKL5H5Yqvd7g?e=omCXeq).

Thanks,

**Comment by gioman** [comment]
> @gioman Please download the sample data from [here](https://utiliscorp-my.sharepoint.com/:u:/p/yuval/EfLtuqxtuGZBoIUw5BAwOY0BjZ-iAmF3RevKL5H5Yqvd7g?e=omCXeq).
> 
> Thanks,

@yuvalutilis link is not working anymore, can you attach again the data? thanks.

**Comment by gioman** [comment]
Closing for lack of feedback.
