### ISSUE TITLE
Extent of data fetched from GEOGRAPHY PostGIS column can not be changed

### ISSUE THREAD

**Issue by majkrzak** [qgis/QGIS#30294]
**Describe the bug**
When layer data is fetched from geography postgis column extent is always -180,180,-90,90 and can not be updated. In case of geometry column extent behave correctly.

**How to Reproduce**
1. Create layer with postgis source
2. Use data from GEOGRAPHY columnt
3. Zoom to the layer /whole world appears/
4. Go to the layer settings
5. Update extent /no action/

**QGIS and OS versions**

Wersja QGIS | 3.6.3-Noosa | Gałąź kodu QGIS | Release 3.6
-- | -- | -- | --
Skompilowane z Qt | 5.12.3 | Uruchomione z Qt | 5.12.3
Skompilowane z GDAL/OGR | 2.3.2 | Uruchomione z GDAL/OGR | 2.4.1
Skompilowane z GEOS | 3.7.1-CAPI-1.11.1 | Uruchomione z GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Wersja klienta PostgreSQL | 11.2 | Wersja SpatiaLite | 4.3.0a
Wersja QWT | 6.1.4 | Wersja QScintilla2 | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018

**Comment by Pedro-Murteira** [comment]
@majkrza Hello, is this issue still valid on more recent releases?

**Comment by majkrzak** [comment]
I currently don't have QGIS set up to be able to reproduce this. I'll came back to you "soon".

**Comment by majkrzak** [comment]
not stale

**Comment by majkrzak** [comment]
not stale

**Comment by majkrzak** [comment]
no stale

**Comment by majkrzak** [comment]
not stale

**Comment by majkrzak** [comment]
not stale

**Comment by majkrzak** [comment]
I've verified the issue on 3.26.0. It still exist. FYI @Pedro-Murteira

**Comment by strk** [comment]
The extent is indeed hard-coded in `QgsPostgresProvider::extent3D()` since svn times, looks to me the hard-coding first entered codebase with aedac63127cd92e7fcdedb8cb8004771d32c8aaa referencing redmine issue https://issues.qgis.org/issues/2730

**Comment by strk** [comment]
See GH-57514 for a fix. Can you give it a go @majkrzak ?
