### ISSUE TITLE
GDAL-based algorithms should pass not only file path but also layer name

### ISSUE THREAD

**Issue by rjhale1971** [qgis/QGIS#30292]
I'm testing QGIS Master 64015a8 on Ubuntu 19.04 
1. Add a Image to QGIS
2. Add a Polygon Layer from a Geopackage to QGIS covering a portion of the Raster. 
3. Run the **Clip Raster By Mask Layer** Processing Tool 
4. Process Fails with: 
GDAL command:
gdalwarp -s_srs EPSG:2234 -t_srs EPSG:2234 -of GTiff -cutline /media/data/projects/planetzero/data/production.gpkg -crop_to_cutline /media/data/projects/planetzero/data/imagery/mosaic_2234.tif /home/rjhale/temp/randy.tif
GDAL command output:
**ERROR 1: Cutline not of polygon type**

5. Replace the Polygon from a Geopackage with a Shapefile and it runs correctly. 

![Screenshot from 2019-06-20 10-03-10](https://user-images.githubusercontent.com/389868/59855252-a6f96e80-9342-11e9-8f9b-e28060409d49.png)

I've checked the polygon layer and set "do not filter" for invalid features just in case. That didn't help or hurt. 

I wasn't sure about attaching files since image + geopackage will be about 25MB. I can though if I need to.

**Comment by gioman** [comment]
@rjhale1971 is the geopackage a MULTIpolygon? is yes that is not accepted by gdalwarp, not a QGIS issue (I think that is the source of the error message).

**Comment by rjhale1971** [comment]
You are correct - It is a Multipolygon! I didn't know those weren't acceptable....and actually I hadn't looked at the polygon type. This can be closed then.

**Comment by rjhale1971** [comment]
Actually.........I'm still getting an error. I went back and double checked with a  polygon (non-multi) and I still get the same error. Let me paste the new error message: 

GDAL command:
gdalwarp -s_srs EPSG:2234 -t_srs EPSG:2234 -of GTiff **-cutline /media/data/projects/planetzero/data/production.gpkg** -crop_to_cutline /media/data/projects/planetzero/data/imagery/mosaic_2234.tif /home/rjhale/temp/deleteme.tif
GDAL command output:
ERROR 1: Cutline not of polygon type.

No where in the error message is my cut layer mentioned

**Comment by gioman** [comment]
> production.gpkg

can you attach it? @rjhale1971

**Comment by rjhale1971** [comment]
I have attached the geopackage with a multipolygon, polygon, and a raster. 

After trying it one more time tonight it seems to be working. So I think I will stop for now. Sorry for the wrong report. I must have been doing something wrong.

[production.zip](https://github.com/qgis/QGIS/files/3312530/production.zip)

**Comment by gioman** [comment]
@rjhale1971 there is definitely a bug.

With the attached datasurce, a multi layer datasource, the GDAL command that is created by Processing is like:

`gdalwarp -of GTiff -cutline production.gpkg  -crop_to_cutline production.gpkg OUTPUT.tif`

but has there are  >1 vector layers in the source it should be

`gdalwarp -of GTiff -cutline production.gpkg **-cl park** -crop_to_cutline production.gpkg OUTPUT.tif`

The second "production.gpkg" represent the input raster layer, and in this case is ok because there is only 1 inside the GPKG, but there could be more, in this case I'm not sure what the parameter to be used on the command line... it must be checked too if Processing does the right thing or not also in this case.

**Comment by rjhale1971** [comment]
Ahhh. OK. I personally broke a bug reporting rule by changing my process and I couldn't recreate it - which is why I kept backing off thinking I had a false bug. 
It does seem to work completely fine if everything is a shapefile....which confirms what you said above. 
Thanks for sticking with me on this. I was ready to give up.
