### ISSUE TITLE
Progressive Rendering Quality

### ISSUE THREAD

**Issue by Saijin-Naib** [qgis/QGIS#30315]
**Feature description.**
I would like to see the (optional) implementation of a Progressive Rendering Quality feature into QGIS. Basically, what this rendering option would do would be to take into account the settings for feature simplification, zoom factor, anti-aliasing, et. al. that the user can tweak in the rendering options. These options will be used when first drawing the canvas, when dragging the canvas, toggling layers, etc. and as anything that would change the canvas occurs. However, there would be a watchdog that would note when the canvas was sitting idle and would begin to progressively re-render the canvas in higher quality as it sat idle/not-updated at "idle priority". I find that I have set my rendering options to be VERY coarse/simplified just to ensure panning/zoom/etc are all as snappy as possible (I work at a wide range of scales all over the extent constantly), yet I would like to be able to see things clearly when I'm maintaining a steady canvas extent.

Perhaps this could be done in tiles or by layer, or maybe per feature. I have to be quite honest that I don't actually understand how QGIS draws to the canvas, so I can't recommend what way would be most performant.

**Additional context**
I think this would be a great compromise between speed and graphical fidelity that would use idle time to improve the display. This type of progressive rendering quality is likely familiar to many from 3D rendering, games, ray-tracing, etc.

**Comment by m-kuhn** [comment]
In most cases I/O is *much* more important than rendering options. Are you sure that these options considerably improve rendering times for you?

Sidenote: We already use idle-time to pre-render neighbouring tiles for snappy panning.

**Comment by Saijin-Naib** [comment]
Matthias,

I'm not sure that my combination of settings for simplification are perfectly ideal, but I do believe they're on the right track. I've not yet done any performance profiling, but using the eyeball meter, it does seem to help a bit on more complex projects with lots of labels, buffers, transparency, etc. Significant? Hard to say, but I _feel_ like I notice it.

I like that you already have a mechanism for idle-time pre-rendering of tiles out of view. That's really slick and forward thinking.

Are your thoughts that there would be no benefit to what I proposed above?

Screenshot of my settings:
![image](https://user-images.githubusercontent.com/19295950/60033976-9b29e700-9677-11e9-9dd0-c62f80f8a0ad.png)
