### ISSUE TITLE
QGIS 3.6.3 Measure tool throws error and crashes

### ISSUE THREAD

**Issue by zeddock** [qgis/QGIS#30319]
**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by zeddock** [comment]
Trying to do very simple measure from one place on main display to another.  Change units from meters to miles. (Sometimes get an INDEXING dialog box.)
See this in terminal:
[92267.138741] ptrace attach of "/usr/bin/qgis.bin"[28007] was attempted by "gdb -q -batch -n --pid=28007 -ex thread -ex bt full /usr/bin/qgis.bin"[28532]

VERSION INFO:

QGIS version | 3.6.3-Noosa | QGIS code revision | 0c5774c
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.6.2-CAPI-1.10.2 4d2925d6
PostgreSQL Client Version | 10.8 (Ubuntu 10.8-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493

**Comment by zeddock** [comment]
Finding this is associated with a particular layer:
How do I provide information about the layer?

**Comment by zeddock** [comment]
This really seems to be a memory type of issue.  How can I get you more info that will help with this?

**Comment by stev-0** [comment]
I can load that ArcGIS Server layer and see it and measuring works fine for me, using a very similar OS, so not sure what is going on there. Could well be memory - I have quite a lot in my PC. Possibly what is happening is that your project is in one projection and that layer is in a different projection, although to be honest that would be an issue before measuring - all the reprojecting could have already been done by then. Not sure if you are able to show the whole project, or at least an isolated set of layers which crashes for you if you can create that. Possibly upgrading the Proj version might help if that is a possibility.

**Comment by zeddock** [comment]
Stephen,
Thank you for responding.  I think I need to do some OS updates before
going further because I am starting to see quite a few other oddities.  No
sense in you or others spending more time if my system is not stable and
you can show proper operations on yours.

Jim

*     Jim*Garner  *304-933-9858*
*   www.Ground*Scouts.com
