### ISSUE TITLE
Automatic screenshot tool wrongly crops the images

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#30326]
**Describe the bug**
In the console run
```
qgis --take-screenshots directory
```
This launches QGIS and adds a bunch of screenshots in the selected output folder but afaict none of the images is usable, due to wrong cropping
Eg, this image is supposed to be the Settings --> Options --> GDAL dialog
![gdal](https://user-images.githubusercontent.com/7983394/59962212-a697d980-94e2-11e9-8069-67d8577b0ddc.png)

**QGIS and OS versions**

Self build master 3.7 on bionic (but as far as I remember this feature has never worked for me - had tried on xenial and windows when it landed in the repo and there was reports, but only in list discussion).

**Comment by Pedro-Murteira** [comment]
@DelazJ Hello, is this still true on recent releases?
