### ISSUE TITLE
QGIS is parsing GRASS 6 global configuration and ignoring GRASS 7 global configuration 

### ISSUE THREAD

**Issue by pmav99** [qgis/QGIS#30332]
- GRASS 6's global configuration file is located at `~/grassrc6`
- GRASS 7's global configuration file is located at `~/.grass7/rc`

QGIS is currently parsing `~/grassrc6` and ignoring `~/.grass7/rc`.

If GRASS 6 is not supported we should remove the code that parses `~/grassrc6` and replace it with code that parses `~/.grass7/rc`.

If GRASS 6 is still supported we should parse the correct file depending on the GRASS version used. 

Question: Is it possible to use both grass 6 and grass7 simultaneously?

**Comment by neteler** [comment]
Out of curiosity: why GRASS GIS 6 at all?

**Comment by gioman** [comment]
@pmav99 as https://github.com/qgis/QGIS/pull/30330 was merged can we close this?

**Comment by pmav99** [comment]
@gioman I guess so
