### ISSUE TITLE
Cannot change single band raster color ramp while maintening current classes

### ISSUE THREAD

**Issue by domlysz** [qgis/QGIS#30345]
**Describe the bug**

Similar to this previous issue  #25001, I still encounter weird behavior when dealing with single band raster pseudocolor classification, making the widget near unusable. Actually, trying to apply a new color ramp always trigger an unwanted reclassification. 

**How to Reproduce**

Load a single band raster into qgis, in style panel and pseudocolor mode, add some classes then switch the color ramp, a new classification is automaticcaly computed

![autorreclass_issue](https://user-images.githubusercontent.com/5639024/59976230-c3efa500-95c1-11e9-8f37-6819cab57747.gif)

As I said in #25001, IMHO **automatic classification should only happen if the user explicitly want it** by clicking on the **intended classify button**.

**QGIS and OS versions**

QGIS 3.6 Linux 64

**Comment by nirvn** [comment]
I'll look into this in the coming days.
