### ISSUE TITLE
[raster] Save as does not work

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#30355]
Save as (raster) doesn't work even if you don't want to save anything, the `Cancel` button doesn't work.

how to reproduce it:

1. load a raster (I have loaded a DTM);
2. right click on the layer | Export | Save with name;
3. I have configured: file name and extension;
4. the OK and CANCEL buttons do not work

```
Versione di QGIS 3.4.9-Madeira
Revisione codice QGIS 54585165bb
Compilato con Qt 5.11.2
Esecuzione con Qt 5.11.2
Compilato con GDAL/OGR 2.4.1
Esecuzione con GDAL/OGR 2.4.1
Compilato con GEOS 3.7.2-CAPI-1.11.0
Esecuzione con GEOS 3.7.2-CAPI-1.11.0 b55d2125
Versione client PostgreSQL 9.2.4
Versione SpatiaLite 4.3.0
Versione QWT 6.1.3
Versione QScintilla2 2.10.8
Compiled against PROJ 520
Running against PROJ 5.2.0
```
use OSGeo4W Network Installer

**I did the same test on QGIS 3.9 DEV, QGIS 3.4.8 and 3.8 and it works fine!**

**Comment by bellanz80** [comment]
I confirm. In windows 10 64 bit v 19.03 QGIS 3.4.9 Standalone.
When exporting a raster file, the OK and CANCEL buttons are not activated.

**Comment by gioman** [comment]
> * load a raster (I have loaded a DTM);
> 
> * right click on the layer | Export | Save with name;
> 
> * I have configured: file name and extension;
> 
> * the OK and CANCEL buttons do not work

works as expected here on QGIS master on Ubuntu 18.04 @pigreco

**Comment by pigreco** [comment]
@gioman 
>works as expected here on QGIS master on Ubuntu 18.04

I have no doubt that it works on Ubuntu,
I point out that it does NOT work on win10
please add '**regression**' tag

thank you

![mah](https://user-images.githubusercontent.com/7631137/60126519-7d02da80-978e-11e9-8b7c-371e5112425f.gif)

**Comment by gioman** [comment]
> I have no doubt that it works on Ubuntu,

that is NOT the point of comments like mine. When testing is important to determine/check of there is a platform specific issue.

**Comment by gespiel** [comment]
can confirm this on win 7 with QGIS 3.4.9.
QGIS 3.8.0 and master work correct.
It worked also in earlier versions of 3.4.
This is regression.

**Comment by spaceof7** [comment]
I am getting this error with 3.4.9 on Linux Mint Tessa(Ubuntu Bionic based) and Windows 7.  downgrading to 3.4.8 on Windows works as expected.

**Comment by nicknn** [comment]
Confirm this issue in QGIS 3.4.9 on Ubuntu (Xubuntu) 18.04.2 LTS 64-bit
Issue not present (buttons work and file is saved) QGIS 3.4.3 on Windows 7 Pro 64 bit

**Comment by wateryhcho** [comment]
Same here with 3.4.9 on Windows 8. The earlier versions (3.4.5 and 3.4.8) are OK with this issues!

**Comment by nirvn** [comment]
Fix incoming.

**Comment by nirvn** [comment]
Fix will be included in QGIS 3.4.10, scheduled on July 19.

**Comment by pigreco** [comment]
@gioman @nirvn 
why not close it ??

**Comment by gespiel** [comment]
Tested this with 3.4.10,
Works perfect for me.
Thanks to Matthieu
