### ISSUE TITLE
"Unable to open a new empty project" message from the welcome page

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#30358]
**How to Reproduce**

1. Open QGIS
2. From the welcome page, double-click the "New empty project" entry
3. You get a small modal dialog stating "Unable to open project"
4. Pressing the OK closes it and you can work but this message should not be.

**QGIS and OS versions**

qgis master 3.9.0 94ec2dc72 on windows 10 (with osgeo4w).
Also occurred with ubuntu bionic

**Comment by nirvn** [comment]
Already fixed by our resident hero @nyalldawson

**Comment by DelazJ** [comment]
Good. Thanks!
