### ISSUE TITLE
decimal values are not saved if in a form there are multiple occurences of a decimal number field

### ISSUE THREAD

**Issue by mathgil** [qgis/QGIS#30359]
Hello

In my project, I use a drag and drop form with multiple groups and tabs.

In these multiples tabs, I created one, kind of quick data entry, wich focuses on main important data. This means that I have multiple iteration of one field in my form.

This seems do not be a problem for text data, but for decimal numbers I cannot enter my values.

Only intergers are allowed. Typing a comma reset the fied to 0. You can put a comma behind a 0, but the value is not saved.

Searching for an opened thread about it, I found this 
https://github.com/qgis/QGIS/issues/23276#issuecomment-495863669
 ... but no explanations about the fact it does not work properly.

Anyway, it does no matter where the field is implemented in the tree of group boxes and tabs.

Here's a gif with a simplified form : 
![issue1](https://user-images.githubusercontent.com/47936145/60016490-aa646100-9686-11e9-9961-64d9dd5a190d.gif)

**QGIS and OS versions**

Desktop 3.6.3

**Comment by gioman** [comment]
@mathgil seems ok to me on 3.22.4
