### ISSUE TITLE
Windows 10 crash after install

### ISSUE THREAD

**Issue by glw** [qgis/QGIS#30366]
**Describe the bug**

After Windows 10 install of QGIS 3.4, I get error "update view in private qgis.db failed. Disk I/O error."
QGIS had never been installed on this computer in the past. I tried both 3.4.8 and 3.4.9 64 bit versions with the same result

**How to Reproduce**
Default options for Install 64 bit version of QGIS 3.4.8 or .9 on Windows 10

**QGIS and OS versions**
QGIS 3.4.8 & 3.4.9 (64 bit), Windows 10 (64 bit)

**Additional context**
I checked for the existence of qgis.db, and it was placed here:
C:\Users\user\AppData\Roaming\QGIS\QGIS3\profiles\default

I also tested whether or not I have read/write/delete privileges, and I do.

Attached is the crash report
[qgis_crash.txt.txt](https://github.com/qgis/QGIS/files/3322806/qgis_crash.txt.txt)

**Comment by HeatherHillers** [comment]
We have the problem on a Windows 7 system with 32 bit QGIS 3.4.4.

**Comment by haubourg** [comment]
I raised the priority of this and marked it as a regression.

 @jef-n does this call any bell to you? I think we have seen this in the past but I fail to find it.

**Comment by glw** [comment]
We also tested the 32 bit installation, with the same result.

**Comment by nirvn** [comment]
@glw , the crasher identified through the stack trace you provided has been fixed, thanks for the report. The next public releases - LTR 3.4.10 and 3.8.1 - are scheduled for July 19 and will include this fix.

**Comment by glw** [comment]
Wonderful! Thanks to everyone!
