### ISSUE TITLE
EPSG:102631 is faulty

### ISSUE THREAD

**Issue by joshuahouston** [qgis/QGIS#30367]
EPSG:102631 [https://epsg.io/102631] doesn't load in the correct place in the world. When saving a file in EPSG:102631 it doesn't write to the file correctly. There are issues on both Windows and Mac OS using this CRS.

**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by joshuahouston** [comment]
html comments got out somehow

**Comment by joshuahouston** [comment]
added link

**Comment by nyalldawson** [comment]
Please check which proj library version your qgis build is using (from the about screen). If it's less than 6, then this won't be fixes. If it's 6 or greater, then this issue need filing at the PROJ issue tracker (which is the underlying library performing coordinate transforms)
