### ISSUE TITLE
Auxiliary storage not usable in non editable layer

### ISSUE THREAD

**Issue by bstroebl** [qgis/QGIS#30376]
**Describe the bug**

If a layer is read only (e.g. from a database where user only has SELECT rights) the auxiliary storge for e.g. the Offset of a point symbol is useless because the field cannot be edited because the layer as a whole cannot be put into editing mode.

**How to Reproduce**

1. Load a point layer from a database with a user that has only SELECT rights on this layer.
2. Goto _Symbology - Simple Marker - Offset_ and in the _Data defined override_ click _Store Data in the Project_
3. The value in the newly created field cannot be edited, neither in the form nor in the table.

**QGIS and OS versions**

QGIS 3.4.9 on Win7 and Ubuntu with PostGIS

**Additional context**

Proposed solution could be to be able to edit any field in the auxiliary storage regardless of the layer's editing status.
The described problem will be true for many settings I reckon, the tools in the _Label Toolbar_ work as expected, though.

**Comment by bstroebl** [comment]
Addition to 3) in How to reproduce:
Due to not being able to toggle editing mode, the _rotate point symbol_ and _offest point symbol_ tools are not enabled either.

**Comment by pblottiere** [comment]
I just tested on master branch and it works well.

QGIS 3.4 is EOL but I'm going to test on 3.10.

**Comment by pblottiere** [comment]
It works on QGIS 3.10 too on GNU/Linux on my side.

@bstroebl can you take a look with QGIS 3.10 please?

**Comment by pblottiere** [comment]
I think we can close this issue. What do ou think @gioman?
