### ISSUE TITLE
SemiAutomaticClassification  Plug-In Error OSX-Mojave

### ISSUE THREAD

**Issue by AntonioDEM** [qgis/QGIS#30371]
I installed on a macbook pro with OS-10.14.5 (Mojave), the SemiAutomaticClassification plugin on Qgis3.6, python 3.6.8, including all the necessary libraries (NumPy 1.9.2-1,SciPy 0.16.0-1, matplotlib 1.4.3-1).
at the start of Qgis, have this error :

AttributeError: 'Legend' object has no attribute 'draggable'
Traceback (most recent call last):
File "/Users/harlock/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin/semiautomaticclassificationplugin.py", line 1296, in newProjectLoaded
cfg.spSigPlot.refreshPlot()
File "/Users/harlock/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin/spectralsignature/spectralsignatureplot.py", line 463, in refreshPlot
self.signaturePlot()
File "/Users/harlock/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin/spectralsignature/spectralsignatureplot.py", line 711, in signaturePlot
cfg.uisp.Sig_Widget.sigCanvas.ax.legend(pL, pLN, bbox_to_anchor=(0.1, 0.0, 1.1, 1.0), loc=1, borderaxespad=0.).draggable()
AttributeError: 'Legend' object has no attribute 'draggable'

Versione Python: 3.6.8 (v3.6.8:3c6b436a57, Dec 24 2018, 02:04:31) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
Versione di QGIS: 3.6.3-Noosa Noosa, exported

Percorso Python:
/Applications/QGIS3.6.app/Contents/MacOS/../Resources/python
/Users/harlock/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/harlock/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS3.6.app/Contents/MacOS/../Resources/python/plugins
/Library/Frameworks/SQLite3.framework/Versions/E/Python/3.6
/Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
/Users/harlock/Library/Application Support/QGIS/QGIS3/profiles/default/python

Have any solution? thanks

**Comment by nyalldawson** [comment]
Plugin issue - not a QGIS issues. Please file with the plugin's author.

**Comment by semiautomaticgit** [comment]
Hello, I'm the developer of the plugin. I think it is an issue related to matplotlib compilation because it only affects MacOS.

**Comment by saberraz** [comment]
Hi @semiautomaticgit could you advise your users to use these packages for QGIS:
https://qgis.org/downloads/macos/
And report bug here:
https://github.com/qgis/QGIS-Mac-Packager

**Comment by semiautomaticgit** [comment]
Of course. Thank you very much @saberraz

**Comment by LittleWhite-tb** [comment]
Hello,

Got the same error on Linux Manjaro, with QGIS 3.80 and matplotlib 3.1.1-1.
It happens certainly only with matplotlib 3.1.1, cause they changed the draggable() function to set_dragabble() on Legend. (Source: https://matplotlib.org/api/api_changes.html#removals).
