### ISSUE TITLE
Save project to geopackage stores absolute paths

### ISSUE THREAD

**Issue by RNanclares** [qgis/QGIS#30387]
**Describe the bug**
Saving project to geopackage stores absolute paths.

**How to Reproduce**
1. Package some layers into geopackage.
2. Add layers to qgis. 
3. Save project to geopackage.
4. Move the geopackage to a different folder.
5. Open the project from the qgis browser panel.
6. All layers in the project will be unavailable. Even if you set paths to be relative in the project properties when you check the properties after re-opening the project it will be set to absolute.

**QGIS and OS versions**
QGIS Version: 3.8
OS Versions: Windows, Ubuntu 18.04

**Comment by bellanz80** [comment]
Y confirm

**QGIS and OS versions**
QGIS Version: 3.8
OS Versions: Windows 10 64 bit v. 1903

**Comment by klakar** [comment]
Confirmed, but if you re-enable relative paths and save the project again. It seems to stick.
I created a test package that you could try...
https://github.com/klakar/geosupportsystem/raw/master/hitta_hit.gpkg

**Comment by pigreco** [comment]
I confirm problem.
even using relative paths does not work.

@klakar 
![image](https://user-images.githubusercontent.com/7631137/60612937-274fb300-9dca-11e9-92e6-4a3cd5c570be.png)

**Comment by bellanz80** [comment]
I confirm the Salvatore test, with the Klas's geopack. It does not locate the layers.
![Anotación 2019-07-03 125044](https://user-images.githubusercontent.com/38449926/60613842-572e9480-9d91-11e9-8694-f634d1ff7aee.png)

**Comment by RNanclares** [comment]
Thanks!
