### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by BillCoupe** [qgis/QGIS#30398]
h2. User Feedback

I was trying to exit QGIS. the app asked if I wanted to safe the current project and I clicked 'Yes'.

h2. Report Details

*Crash ID*: e93000bd53685765b53ce547214bcdd9629abc2e

*Stack Trace*
<pre>
QObject::thread :
QgsNetworkAccessManager::instance :
selectWidget :
std::basic_string<char,std::char_traits<char>,std::allocator<char> >::crbegin :
std::basic_string<char,std::char_traits<char>,std::allocator<char> >::push_back :
QgsRasterDataProvider::block :
QgsSingleBandColorDataRenderer::block :
QgsBrightnessContrastFilter::block :
QgsHueSaturationFilter::block :
QgsRasterResampleFilter::block :
QgsRasterProjector::block :
QgsRasterIterator::readNextRasterPart :
QgsRasterDrawer::draw :
QgsRasterLayerRendererFeedback::onNewData :
std::basic_string<char,std::char_traits<char>,std::allocator<char> >::swap :
QMetaObject::activate :
QNetworkReply::url :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
QEventLoop::exec :
std::basic_string<char,std::char_traits<char>,std::allocator<char> >::crbegin :
std::basic_string<char,std::char_traits<char>,std::allocator<char> >::push_back :
QgsRasterDataProvider::block :
QgsSingleBandColorDataRenderer::block :
QgsBrightnessContrastFilter::block :
QgsHueSaturationFilter::block :
QgsRasterResampleFilter::block :
QgsRasterProjector::block :
QgsRasterIterator::readNextRasterPart :
QgsRasterDrawer::draw :
QgsRasterLayerRenderer::render :
QgsMapRendererCustomPainterJob::doRender :
QgsMapRendererCustomPainterJob::staticRender :
QgsRenderContext::segmentationToleranceType :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.2.3-Bonn
QGIS code revision: commit:9b176802e5
Compiled against Qt: 5.9.2
Running against Qt: 5.9.2
Compiled against GDAL: 2.2.4
Running against GDAL: 2.2.4

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.15063

**Comment by gioman** [comment]
@BillCoupe please try with a new/clean qgis profile, no 3rd party plugins installed.

**Comment by BillCoupe** [comment]
First and only time the product has ever crashed on me.  I only sent the report because the app asked me to do so.

Unless this becomes a regular thing I’m not removing the plugins as without them, the app doesn’t do everything I need it to do.

Thanks for the feedback though.

-bc

**Comment by gioman** [comment]
>  I’m not removing the plugins as without them

creating a new QGIS profile does not remove any of your (current profile) configs and plugins.

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
