### ISSUE TITLE
r.walk.points and r.walk.rast tools are looking for files in C: \ qgis_grass_trento

### ISSUE THREAD

**Issue by gis2015** [qgis/QGIS#30394]
**Describe the bug**
r.walk.points and r.walk.rast are looking for files in C: \ qgis_grass_trento:
ERROR:LOCATION <C:\qgis_grass_trento\nc_basic_spm\gisdemo_ncspm> not available
WARNING: Concurrent mapset locking is not supported on Windows

**How to Reproduce**
Simply fill in the fields with the requested data and accept all the optional conditions (default) and click Run.

PARAMETERS
![r walk_param](https://user-images.githubusercontent.com/33656414/60104853-a98c0780-9738-11e9-80a9-fc891106ac5b.png)

LOG:
![r walk_log](https://user-images.githubusercontent.com/33656414/60105025-f5d74780-9738-11e9-82ff-3a503b6a93ef.png)

**QGIS and OS versions**
QGIS 3.4.8
OS: Windows 10

**Additional context**

**Comment by gioman** [comment]
@gis2015 there isn't any string containing "qgis_grass_trento" in QGIS code: https://github.com/qgis/QGIS/search?q=qgis_grass_trento&unscoped_q=qgis_grass_trento

so maybe the issue is in the GRASS tool itself? Or maybe something local on your pc?

**Comment by gis2015** [comment]
Thanks. There was issue is in the GRASS tool itself.
