### ISSUE TITLE
Another crash report

### ISSUE THREAD

**Issue by NickLanzer** [qgis/QGIS#30399]
## User Feedback

I always get a ":( QGIS Crashed" message when I simply close the program. 

## Report Details

*Crash ID*: 7442373e0283e1ddab9b4be290841057a580a7ea

*Stack Trace*
<pre>
proj_lpz_dist :
proj_lpz_dist :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::~QgsCoordinateTransform :
QgsPointLocator::~QgsPointLocator :
QgsPointLocator::~QgsPointLocator :
QgsSnappingUtils::clearAllLocators :
QgsSnappingUtils::~QgsSnappingUtils :
QgsVectorLayerProperties::`default constructor closure' :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
CPLStringList::operator[] :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.8.0-Zanzibar
QGIS code revision: 11aff65f10
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by gioman** [comment]
@NickLanzer  please try with a new/clean qgis profile, no 3rd party plugins installed.
