### ISSUE TITLE
QGis 3.4-3.9 reproducible crash

### ISSUE THREAD

**Issue by juanmpd** [qgis/QGIS#30395]
We have been facing a crash in our plugin while migrating it from QGis 2.18 to Qgis 3.4, and finally we have isolated a small piece of code to reproduce the crash.
Having a plugin with the following body causes QGis to crash:

```
from qgis.PyQt.Qt import QFileInfo
class crashPlugin(object):
    def __init__(self, iface):
        mc = iface.mapCanvas()
        sc = mc.scene()       
        k=list(sc.items())
```

I have attached a zip file with a plugin demonstrating the crash:
[a_crash.zip](https://github.com/qgis/QGIS/files/3325719/a_crash.zip)

To reproduce the crash, simply uncompress the zip file into <qgis>\python\plugins, then try to enable it within QGis 3.4 / 3.9Master (you may need to force the reload of the repository, or simply restart QGis if it was already open). Just trying to enable this plugin will make QGis crash.

We have tested it on QGis 3.4.X (LTR) and QGis 3.9 (Master), under Windows 7 and Windows 10.

**Comment by juanmpd** [comment]
One more comment: the problem seams related to the QFileInfo import (thought it is not used). Changing the import so that QFileInfo is imported from qgis.PyQt.QtCore instead of qgis.PyQt.Qt avoids the crash.

**Comment by juanmpd** [comment]
Same issue is reproducible if using those imports:
```
from qgis.PyQt.Qt import QProgressDialog, QPushButton
from qgis.PyQt.Qt import QByteArray, QTime, QSettings

```
instead of:
```
from qgis.PyQt.QtWidgets import QProgressDialog, QPushButton
from qgis.PyQt.QtCore import QByteArray, QTime, QSettings

```

**Comment by nyalldawson** [comment]
> from qgis.PyQt.Qt import QProgressDialog, QPushButton

I don't think this form of input should even be supported. I had no idea it worked at all ... even in the fragile state that you've found!

I'd say this should be closed, and everyone should be using the full import instead.

**Comment by juanmpd** [comment]
I don't mind everyone should be using the full import. In fact, it is what we are trying now.
I think it would be safest if the wrong import form could be completely prevented.
If any one lets the autocompletion features of their IDEs to automatically propose where to import the classes from, and he chooses qgis.PyQt.Qt, he may later stump on crashes whose root is quite difficult to identify...
On the other way, I wonder what are the internals that make this crash happen. I'm not sure why a wrong import may manifest itself later as a crash in another point of unrelated code. What worries me, is if there may be other situations, apart from those imports, that my also manifest later as crashes due to them reaching the same underlying crash conditions...
In any case, we are proceeding as you suggest, avoiding those import forms.
Thanks!

**Comment by gioman** [comment]
> I'd say this should be closed,

I obey.
