### ISSUE TITLE
'BatchInputSelectionPanel' object has no attribute 'value'

### ISSUE THREAD

**Issue by All4Gis** [qgis/QGIS#30406]
**Describe the bug**

Based on this question from gis.stackexchange.
https://gis.stackexchange.com/q/326925/49538

![5B3Ed](https://user-images.githubusercontent.com/8123225/60157650-8f613080-97ef-11e9-9065-fb5c533397f3.png)

Related to #29862 

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by alexbruy** [comment]
Fixed in d0926f9.
