### ISSUE TITLE
QGIS 3.8.0 crash on add layer from ArcGIS MapServer

### ISSUE THREAD

**Issue by FelisPimeja** [qgis/QGIS#30409]
**QGIS 3.8.0 (Clean profile)**
Immediate crash without backtrace when trying to add any layer from the following ArcGIS Server connection:
[https://pkk5.rosreestr.ru/arcgis/rest/services/Cadastre/BordersGKN/MapServer/](https://pkk5.rosreestr.ru/arcgis/rest/services/Cadastre/BordersGKN/MapServer/)

QGIS 3.6 Added this layers to the project but could not display them writing errors to network console: 
`WARNING    Error transferring https://pkk5.rosreestr.ru/arcgis/rest/services/Cadastre/BordersGKN/MapServer//export?bbox=4451772.059913,7508399.924688,4550545.663105,7574091.208174&size=1878,1249&format=PNG32&layers=show:19&transparent=true&f=image - server replied: Bad Request`

**Comment by nirvn** [comment]
@FelisPimeja , I can't replicate the crash here (on my linux machine). 

As for the layers not working on 3.6, it appears the server is at fault, I can't get it to display on arc's online map viewer et cie.

**Comment by nyalldawson** [comment]
Definitely an issue on the server here - just trying to access the render endpoint via a browser results in an error

**Comment by FelisPimeja** [comment]
Forgot to mention - it's Windows 10.
I see it's something with the server, but strange thing it's silent on qgis 3.6 and immediate crash on 3.8 for me.

**Comment by nirvn** [comment]
OK, I can get it crashing.

**Comment by nirvn** [comment]
Trace:

#0  0x00007fff7005a890 in  ()
#1  0x00007ffff3f8de81 in QPainter::end() () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#2  0x00007ffff3f8e650 in QPainter::~QPainter() () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#3  0x00007fffd9403c70 in QgsAmsProvider::draw(QgsRectangle const&, int, int, QgsRasterBlockFeedback*) (this=
    0x5555599aaca0, viewExtent=..., pixelWidth=730, pixelHeight=338, feedback=0x5555598fede0)
    at /home/webmaster/dev/cpp/QGIS/src/providers/arcgisrest/qgsamsprovider.cpp:700
#4  0x00007fffd9406fb3 in QgsAmsProvider::readBlock(int, QgsRectangle const&, int, int, void*, QgsRasterBlockFeedback*)
    (this=0x5555599aaca0, viewExtent=..., width=730, height=338, data=0x7fff7005d790, feedback=0x5555598fede0)
    at /home/webmaster/dev/cpp/QGIS/src/providers/arcgisrest/qgsamsprovider.cpp:882
#5  0x00007ffff590f81e in QgsRasterDataProvider::block(int, QgsRectangle const&, int, int, QgsRasterBlockFeedback*)
    (this=0x5555599aaca0, bandNo=1, boundingBox=..., width=730, height=338, feedback=0x5555598fede0)
    at /home/webmaster/dev/cpp/QGIS/src/core/raster/qgsrasterdataprovider.cpp:201
#6  0x00007ffff597710f in QgsSingleBandColorDataRenderer::block(int, QgsRectangle const&, int, int, QgsRasterBlockFeedback*) (this=
    0x5555560f86b0, bandNo=1, extent=..., width=730, height=338, feedback=0x5555598fede0)
    at /home/webmaster/dev/cpp/QGIS/src/core/raster/qgssinglebandcolordatarenderer.cpp:62
#7  0x00007ffff594f0aa in QgsBrightnessContrastFilter::block(int, QgsRectangle const&, int, int, QgsRasterBlockFeedback*)
    (this=0x55555a0d8660, bandNo=1, extent=..., width=730, height=338, feedback=0x5555598fede0)
    at /home/webmaster/dev/cpp/QGIS/src/core/raster/qgsbrightnesscontrastfilter.cpp:118
#8  0x00007ffff5954385 in QgsHueSaturationFilter::block(int, QgsRectangle const&, int, int, QgsRasterBlockFeedback*)
    (this=0x55555997c1d0, bandNo=1, extent=..., width=730, height=338, feedback=0x5555598fede0)
    at /home/webmaster/dev/cpp/QGIS/src/core/raster/qgshuesaturationfilter.cpp:123
#9  0x00007ffff597582e in QgsRasterResampleFilter::block(int, QgsRectangle const&, int, int, QgsRasterBlockFeedback*)
    (this=0x55555613f380, bandNo=1, extent=..., width=730, height=338, feedback=0x5555598fede0)
    at /home/webmaster/dev/cpp/QGIS/src/core/raster/qgsrasterresamplefilter.cpp:161
#10 0x00007ffff5945ee6 in QgsRasterProjector::block(int, QgsRectangle const&, int, int, QgsRasterBlockFeedback*)
    (this=0x55555a0df7b0, bandNo=1, extent=..., width=730, height=338, feedback=0x5555598fede0) at /home/webmaster/dev/cpp/QGIS/src/core/raster/qgsrasterprojector.cpp:774
#11 0x00007ffff591b06c in QgsRasterIterator::readNextRasterPartInternal(int, int&, int&, std::unique_ptr<QgsRasterBlock, std::default_delete<QgsRasterBlock> >*, int&, int&, QgsRectangle*)
    (this=0x7fff7563b3e0, bandNumber=1, nCols=@0x7fff7563b2e0: 730, nRows=@0x7fff7563b2e4: 338, block=0x7fff7563b310, topLeftCol=@0x7fff7563b2e8: 0, topLeftRow=@0x7fff7563b2ec: 0, blockExtent=0x0) at /home/webmaster/dev/cpp/QGIS/src/core/raster/qgsrasteriterator.cpp:130
#12 0x00007ffff591a9b8 in QgsRasterIterator::readNextRasterPart(int, int&, int&, std::unique_ptr<QgsRasterBlock, std::default_delete<QgsRasterBlock> >&, int&, int&, QgsRec...

**Comment by nyalldawson** [comment]
@nirvn this is fixed, right?

**Comment by nirvn** [comment]
Yep.
