### ISSUE TITLE
classifyColorRamp() function returning a blank layer

### ISSUE THREAD

**Issue by sheyril** [qgis/QGIS#30404]
We were trying to generate singleband pseudoclor rasters from singleband greyscale height maps and ran into a problem. The classifyColorRamp() function which was used to create 5 classes in the python script is returning a blank file in QGIS. 
Here's the code:

    `   rlayer = QgsRasterLayer(inp, "pseudocolor_layer")
        fcn = QgsColorRampShader()
        fcn.setColorRampType(QgsColorRampShader.Interpolated)
        lst = [QgsColorRampShader.ColorRampItem(0, QColor(0,255,0)), QgsColorRampShader.ColorRampItem(255, QColor(255,255,0)) ]
        fcn.setColorRampItemList(lst)
        fcn.classifyColorRamp(5)
        shader = QgsRasterShader()
        shader.setRasterShaderFunction(fcn)
        renderer = QgsSingleBandPseudoColorRenderer(rlayer.dataProvider(), 1, shader)
        rlayer.setRenderer(renderer)
        rlayer.triggerRepaint()`

Run the python script along with the inp parameter in the QGIS python console. Or you can run a python standalone script with an added export function. 

**QGIS and OS versions**
Using QGIS version: 3.4.8-Madeira
Compiled against Qt: 5.11.2
Compiled against GDAL/OGR: 2.4.1
MacOS: Mojave v10.14

Here's a screenshot of what it looks like. 

![Screenshot 2019-06-21 at 1 37 13 PM](https://user-images.githubusercontent.com/40118763/60155148-fb02c800-9806-11e9-9c69-3e17747d317f.png)

**Comment by alexbruy** [comment]
There is something wrong with your code, I can apply a singleband pseudocolor renderer to my layer without any issues.

**Comment by eangius** [comment]
@alexbruy I am seeing the same 2 color classification issue when invoked on default color ramp style with quantile classifications.  if it's not a bug, what's the right way to call the styling?

```python
 def style_heatmap(layer: QgsRasterLayer, color_ramp_name: str = "Reds", opacity=0.5):
   color_ramp = QgsStyle().defaultStyle().colorRamp(color_ramp_name)
   color_ramp.setColor1(QColor("Transparent"))

   color_shader_fn = QgsColorRampShader(
      colorRamp=color_ramp,
      type=QgsColorRampShader.Interpolated,
      classificationMode=QgsColorRampShader.Quantile,
   )
   shader = QgsRasterShader()
   shader.setRasterShaderFunction(color_shader_fn)

   renderer = QgsSingleBandPseudoColorRenderer(
      layer.dataProvider(),
      layer.type(),
      shader
   )
   color_shader_fn.classifyColorRamp(5)    # <<-- PROBLEM has no effect!

   renderer.setOpacity(opacity)
   return renderer
```
