### ISSUE TITLE
crash when trying to load a postgis view with pyqgis commands

### ISSUE THREAD

**Issue by tijan49** [qgis/QGIS#30400]
h2. User Feedback

crash when trying to load a postgis layer with this commands :

        uri = QgsDataSourceUri()
        uri.setConnection("localhost", "5432", "mybdd", "postgres", "mypassword")
        uri.setDataSource ("public", "v_liste_ilots_concernes", "geom")
        vlayer=QgsVectorLayer (uri.uri(False), "tentative", "postgres")
        QgsProject.instance().addMapLayer(vlayer)

strangely, it works perfectly when it's a 'normal' layer, but it crashes when it is a view ...

h2. Report Details

*Crash ID*: 73d962e89f1fe1b92f517adc63d10afaaf16ce85

*Stack Trace*
<pre>
QMutex::lock :
sourceSelectProviders :
isProvider :
QgsVectorLayer::extent :
QgsMapSettings::fullExtent :
QgsMapCanvas::fullExtent :
QgsMapOverviewCanvas::setLayers :
QgsLayerTreeMapCanvasBridge::setCanvasLayers :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.6.2-Noosa
QGIS code revision: commit:656500e0c4
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by jgrocha** [comment]
Hi @tijan49,

Thank you for reporting this issue. Maybe the problem with views is that QGIS is unable to find the primary key. With common tables, QGIS is able to find out the primary key.

Can you try again, providing the view's primary key?

Check the [documentation](https://qgis.github.io/pyqgis/3.6/core/QgsDataSourceUri.html?highlight=setdatasource#qgis.core.QgsDataSourceUri.setDataSource).

It should be something like:

```python
uri.setDataSource ("public", "v_liste_ilots_concernes", "geom", "", "id")
```

**Comment by gioman** [comment]
Closing for the lack of feedback.
