### ISSUE TITLE
Move labels doesn't work with GPKG QGIS 3.4

### ISSUE THREAD

**Issue by lbartoletti** [qgis/QGIS#30408]
**Describe the bug**
Can't move labels on QGIS 3.4 with auxiliary storage

**How to Reproduce**

Open this gpkg https://github.com/Oslandia/labelconnector/files/3324647/COMMUNES.zip
add label and try to move it

**QGIS and OS versions**

QGIS 3.4 not reproduced in 3.6 and master

**Additional context**

Related discussion https://github.com/Oslandia/labelconnector/issues/16

**Comment by faridcher** [comment]
I still have this issue with 3.4.14

**Comment by gioman** [comment]
> I still have this issue with 3.4.14

works fine on 3.10.2

**Comment by faridcher** [comment]
> > I still have this issue with 3.4.14
> 
> works fine on 3.10.2

Thanks for the response. By the way, 3.4 is LTR and this is a serious bug!

**Comment by pblottiere** [comment]
QGIS 3.10 will become the new LTR the 21/02/2020, meaning that 3.4 is eol.

Considering that it works well on 3.10, I propose to close this issue.

Do you agree @lbartoletti?

**Comment by lbartoletti** [comment]
good for me.
