### ISSUE TITLE
Batch processing a graphical modeller model results in AttributeError: 'NoneType' object has no attribute 'parameterValue' 

### ISSUE THREAD

**Issue by bruesba** [qgis/QGIS#30410]
When a self-made model created in the graphical modeller is run in batch processing mode, it throws "Python error : An error has occurred while executing Python code: See message log (Python Error) for more details". The message log, nor the batch processing window log show anything, but when Stack Trace is clicked,  the following window pops up:

AttributeError: 'NoneType' object has no attribute 'parameterValue' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python/plugins\processing\gui\BatchAlgorithmDialog.py", line 88, in runAlgorithm
    parameters[param.name()] = wrapper.parameterValue()
AttributeError: 'NoneType' object has no attribute 'parameterValue'

When the model is run on single files, i.e. not in batch mode, it functions as expected (tested for all files which were to be included in the batch). Batch processing a simpler model (input - difference algorithm - output) throws the same error. Batch processing QGIS tools also seems to work fine, although I only tried a few.

A screetshot of the model with which I initially ran into the error: 
![batcherror](https://user-images.githubusercontent.com/47451532/60166324-3c907480-9801-11e9-92bc-53dc3a643baa.png)
Saving the output does works in neither .shp nor .gpkg.

QGIS version
3.4.8-Madeira
QGIS code revision
04ee8e0761
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
2.4.1
Running against GDAL/OGR
2.4.1
Compiled against GEOS
3.7.2-CAPI-1.11.0
Running against GEOS
3.7.2-CAPI-1.11.0 b55d2125
PostgreSQL Client Version
9.2.4
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
520
Running against PROJ
5.2.0
Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]

**Comment by gioman** [comment]
attach the model and sample data. thanks!

**Comment by bruesba** [comment]
[brokenBatchModellerExampleData.zip](https://github.com/qgis/QGIS/files/3333508/brokenBatchModellerExampleData.zip)

Right, sorry. Included are the model that's also depicted in the main post, 'GT_extent' - which should be selected as 'extent gevuld' in the model, and two other shapefiles, which should be batch processed under 'onderlingen daken'. Hope that's clear enough!

**Comment by bruesba** [comment]
Changing the code in wrappers.py as shown in #30443 doesn't do the trick for me, I run into the same issue as described in the #30410. For good measure, I also changed all four other instances of widget.value() to widget.getValue(), but to no avail.
Am I doing it wrong? If so, forgive me, GitHub first timer.

**Comment by jabiologo** [comment]
I'm having the same error, did you solve it?

**Comment by bruesba** [comment]
Nope, I'm afraid not. I ended up writing a script that did the same as my model. Batch processing does work for QGIS Python scripts aparently, it's just that scripting is quite counterintuitive in the program and documentation hasn't been updated for Python 3 IIRC. 
Have you tried this on the latest version of QGIS? If so, this issue should probably be reopened.
