### ISSUE TITLE
Unexpected moves of object with user defined rotation in atlas composer

### ISSUE THREAD

**Issue by VxTedxV** [qgis/QGIS#30419]
In composer, when image rotation is defined by an expression (rotation of object, because rotation of images cannot be custom defined), its position in the page changes when navigating through different pages of an atlas, following this pattern :

- if no rotation, image stays where it is supposed to be ![test1](https://user-images.githubusercontent.com/30288828/60190916-bb060a00-9833-11e9-8886-fe46fa774d86.jpg)
- if image rotated once through navigating between pages of atlas, then its position is moved X+width of the object ![test2](https://user-images.githubusercontent.com/30288828/60190915-ba6d7380-9833-11e9-9c44-433376104082.jpg)
- if image rotated more than once through navigating between pages of atlas, then its position is moved X+2*(width of the object) ![test3](https://user-images.githubusercontent.com/30288828/60190911-ba6d7380-9833-11e9-9eb7-2dc547bfc4aa.jpg)

Continuing navigating through pages of atlas add more space (never go back to original position of the image)
X is not defined by an expression.
Images are well rotated.

Expression used to define rotation : 
`CASE WHEN regexp_substr( attribute( get_feature( 'layer name where rotation of each photo can be found', 'attribute name of the name of each photo contening IDs', concat( right( "attribute name contening IDs from atlas coverage layer" ,2),'.jpg')), 'attribute where rotation in degrees is extracted'), '(\\d+)') >'0' THEN regexp_substr(...same expression as above...) ELSE '0' END`

QGis 3.6.0 - Windows 8.1

**Comment by VxTedxV** [comment]
With further tests : 
- When reference point is set on the middle point -> bug
- When reference point is set on the upper left point -> no bug
- Don't work only with images : when this same complex expression is used to rotate an object, simple objects (like a triangle) rotate and stay (no bug) in place whereas images rotate and move (bug).

**Comment by nyalldawson** [comment]
Can you test with 3.8.3 -- I can't reproduce this.

**Comment by VxTedxV** [comment]
I'll do it as soon as I can. Thanks you !

**Comment by VxTedxV** [comment]
Tested again under QGis 3.12.1 without bug anymore :)
