### ISSUE TITLE
QGIS Crash after changing layer projection

### ISSUE THREAD

**Issue by PauloEduardoCardoso** [qgis/QGIS#30439]
h2. User Feedback

Change layer projection.

h2. Report Details

*Crash ID*: 69f1683d149d61e4ebfa4a990193d2277d0ade0f

*Stack Trace*
<pre>
proj_lpz_dist :
proj_lpz_dist :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::~QgsCoordinateTransform :
QgsFirstRunDialog::tr :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
CPLStringList::operator char * __ptr64 * __ptr64 :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.4.4-Madeira
QGIS code revision: commit:f6ddc62fdb
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.0
Running against GDAL: 2.4.0

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by gioman** [comment]
@PauloEduardoCardoso please also try with a new/clean QGIS profile, no 3rd party plugins installed.

**Comment by roya0045** [comment]
Projections used and sample data would be nice info to have.

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
