### ISSUE TITLE
Composer Attribute Table: Wrap Heading Text

### ISSUE THREAD

**Issue by HeyMichaelRea** [qgis/QGIS#30441]
**Feature description.**
It would be appreciated if there was a way to wrap heading text to allow it to display in multiple lines in an attribute table in the composer.  

**Additional context**
At present, it seems like the wrap text function on the attribute table in the print composer will only work for attribute rows.

**Comment by samnawi** [comment]
is there any update for this stuff? I think it will be better if we can also wrap text in the heading of the attribute table at the layout.

**Comment by nyalldawson** [comment]
It's already fixed (3.12.3 includes it)

**Comment by samnawi** [comment]
OK thank you @nyalldawson.
Since I still using 3.10.3 and I still looking for it.

regards,

**Comment by domlysz** [comment]
It doesn't seem to work with QGIS 3.13 but maybe I'm missing something, I can't find the relative commit. A clue?

Regards

**Comment by nirvn** [comment]
@domlysz , proof of life:
![Screenshot from 2020-06-09 17-42-25](https://user-images.githubusercontent.com/1728657/84138541-9f156b80-aa78-11ea-89ec-acc9054a1cfa.png)

You have to set your column width to a fixed length, and make sure the oversized text combo box is set to warp text.

**Comment by domlysz** [comment]
oh yes missing the oversized text option !

Thanks Mathieu

**Comment by BilleeMc** [comment]
I am using version 3.4.13-Madeira and I still can't find how to wrap the text on the Header row. Using the function above only seems to wrap text on the content rows. Not header. Am I missing something?

**Comment by gioman** [comment]
> Am I missing something?

@BilleeMc too old version of QGIS.

**Comment by BilleeMc** [comment]
ok thanks

**Comment by BilleeMc** [comment]
I am working on a big project, if I upgrade there is not chance of loosing the work I have set up?

**Comment by gioman** [comment]
> I am working on a big project, if I upgrade there is not chance of loosing the work I have set up?

you don't need to uninstall an older version of qgis to install a new one. And I assume you have backup copies of your projects ;)

**Comment by BilleeMc** [comment]
Yes all backed up. Just upgraded and all good, and text in the headers of the table wrapping now. Thanks.
