### ISSUE TITLE
Enable snapping capabilities to select point for QgsProcessingParameterPoint

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#30463]
1. Open the Shortest path (point to point) algorithm
1. Click on the `...` button next to the "Start point" parameter. This allows you to select a point or a coordinate on the map.

It could be nice if snapping was possible so that you can select accurately a point or vertex you already have on the map.

**Comment by nyalldawson** [comment]
This is already done in 3.8

**Comment by DelazJ** [comment]
Ah great! Sorry I tested on a 3.6 release. Thanks.
