### ISSUE TITLE
Homogenize travel cost units within network analysis algorithms

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#30464]
When running shortest path algorithm (eg, point to point) with the "fastest" type of travel, the cost field in the output layer is in "hours".
When running the service area algorithms with the "fastest" travel cost, "seconds" are expected as input. Since the latter is not obviously mentioned, this may lead to errors.

It could be nice we use the same units across those algorithms and explicitly expose the units in use.

**Comment by stefancon** [comment]
Additionally the documentation on service area calculations is wrong about the cost parameter. Documentations says inputs are expected as "hours" but in fact it's "seconds".

**Comment by DelazJ** [comment]
@stefancon Please see https://github.com/qgis/QGIS-Documentation/issues/3898. Still waiting for confirmation.
