### ISSUE TITLE
Losing geometry when saving 

### ISSUE THREAD

**Issue by DOuellette1** [qgis/QGIS#30472]
I'm drawing polygon areas in a shapefile layer in QGIS Version 3.4 . Many times, when I save the attributes table, the data stays but I lose geometry. When I try to zoom in to that polygon, I get the message "Cannot zoom to selected feature(s):No extent could be determined". At the moment, I have 3 entries in that table. One has geometry so I am able to zoom in to it and you can see it in the map. But the other 2 I get the above image and I don't even see it in the map. When I draw these polygons, it's to encompass a bunch of properties together. So when I draw the polygon around the boundaries, I snap to the corners. I don't understand why for some polygons there's no problem with keeping the geometry and they show up in the map, but with others I lose geometry as soon as I save and I don't see them in the map? My shapefiles are saved on our network if that makes a difference. Can someone help please?

**Comment by DelazJ** [comment]
IS "[avoid intersections for new polygons](https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/editing_geometry_attributes.html#avoid-intersections-of-new-polygons)" from the snapping toolbar activated? 
PS: [QGIS users list](https://qgis.org/en/site/getinvolved/mailinglists.html#qgis-mailinglists) is more appropriate for this kind of questions.

**Comment by DOuellette1** [comment]
Thank you!!! It seems to be working now.
