### ISSUE TITLE
Layer Filter with more than 31 "OR" statements fails. 

### ISSUE THREAD

**Issue by maxstevenson** [qgis/QGIS#30470]
**Describe the bug**
Filter expression with 32 or more "OR" statements fails, but with 31 or less  "OR" statements the filter works correctly. 

**How to Reproduce**
1. Select the layer "Calib_wells-2-05-19"
2. Right Click on layer then select 'Filter'
3. Add this text to the filter expression box:
"WellNumber" LIKE '06N03E07M001M' or "WellNumber" LIKE '07N03E04Q001M' or "WellNumber" LIKE '08N01E07R001M' or "WellNumber" LIKE '08N01E11F001M' or "WellNumber" LIKE '08N01W03D003M' or "WellNumber" LIKE '08N01W09C001M' or "WellNumber" LIKE '08N01W12D001M' or "WellNumber" LIKE '08N01W13G003M' or "WellNumber" LIKE '08N02E01K001M' or"WellNumber" LIKE '08N02E02Q001M' or "WellNumber" LIKE '08N02E08P001M' or "WellNumber" LIKE '08N02E10F001M' or "WellNumber" LIKE '08N02E10N001M' or "WellNumber" LIKE '08N02E10P003M' or "WellNumber" LIKE '08N02E10R001M' or "WellNumber" LIKE '08N02E11A001M' or "WellNumber" LIKE '08N02E11R001M' or "WellNumber" LIKE '08N02E15A002M' or "WellNumber" LIKE '08N03E07M002M' or "WellNumber" LIKE '08N03E07N001M' or "WellNumber" LIKE '08N03E19D003M' or "WellNumber" LIKE '08N03E32L001M' or "WellNumber" LIKE '09N01E03C003M' or "WellNumber" LIKE '09N01E07D001M' or "WellNumber" LIKE '09N01E12M001M' or "WellNumber" LIKE '09N01E20E001M' or "WellNumber" LIKE '09N01E24D001M' or "WellNumber" LIKE '09N01E31D001M' or "WellNumber" LIKE '09N01W02Q002M' or "WellNumber" LIKE '09N01W07R001M' or "WellNumber" LIKE '09N01W08Q001M' or "WellNumber" LIKE '09N01W21E001M' or "WellNumber" LIKE '09N01W24G001M' or "WellNumber" LIKE '09N02E07L001M' or "WellNumber" LIKE '09N02E16N001M' or "WellNumber" LIKE '09N02E31D001M' or "WellNumber" LIKE '09N02E32M001M' or "WellNumber" LIKE '09N02E35E001M' or "WellNumber" LIKE '09N03E08C001M' or "WellNumber" LIKE '09N03E08C002M' or "WellNumber" LIKE '09N03E08C003M' or "WellNumber" LIKE '09N03E08C004M' or "WellNumber" LIKE '09N03E19R001M' or "WellNumber" LIKE '09N03E19R002M' or "WellNumber" LIKE '09N03E33B002M' or "WellNumber" LIKE '10N01E02Q002M' or "WellNumber" LIKE '10N01E14K001M' or "WellNumber" LIKE '10N01E18C001M' or "WellNumber" LIKE '10N01E23Q002M' or "WellNumber" LIKE '10N01E24E001M' or "WellNumber" LIKE '10N01E29K001M' or "WellNumber" LIKE '10N01W02Q001M' or "WellNumber" LIKE '10N01W08B001M' or "WellNumber" LIKE '10N01W09F002M' or "WellNumber" LIKE '10N01W19Q004M' or "WellNumber" LIKE '10N01W21J001M' or "WellNumber" LIKE '10N01W30K001M'
4. See error -->
![image](https://user-images.githubusercontent.com/52325246/60352331-75a12400-997c-11e9-8a8f-086bc4b60a4b.png)

5. reduce text string of filter to 31 or less "OR" statements and it works fine.
![image](https://user-images.githubusercontent.com/52325246/60352526-d92b5180-997c-11e9-96e1-6c5e484fdc2d.png)

**QGIS and OS versions**
Works fine in QGIS 2.18.6, can have hundreds of "OR" in a filter expression.
Does not work in 3.4.7 or 3.8

[Calib_wells-2-05-19.zip](https://github.com/qgis/QGIS/files/3339768/Calib_wells-2-05-19.zip)

![image](https://user-images.githubusercontent.com/52325246/60352813-83a37480-997d-11e9-9457-3aa08ff57620.png)

**Additional context**

Using QGIS 2.18.6 on an older Windows 10 machine and the filter expressions with hundreds of "OR" statements and it works fine. USing QGIS 3.4.7 and 3.8 on a newer Windows 10 machine and filter does not work if there are more than 31 "OR" statements. I tried with a fresh user profile, didn't help.

**Comment by elpaso** [comment]
Error comes from OGR: ../src/core/qgsmessagelog.cpp:29 : (logMessage) [0ms] 2019-06-28T17:37:00 OGR[1] OGR[3] error 1: Too many recursion levels in expression to evaluate

Did you try with `IN ( )` operator instead of chaining `OR`s ?

This works for me:
```
IN ('06N03E07M001M', '07N03E04Q001M', '08N01E07R001M', '08N01E11F001M', '08N01W03D003M', '08N01W09C001M', '08N01W12D001M', '08N01W13G003M', '08N02E01K001M','08N02E02Q001M', '08N02E08P001M', '08N02E10F001M', '08N02E10N001M', '08N02E10P003M', '08N02E10R001M', '08N02E11A001M', '08N02E11R001M', '08N02E15A002M', '08N03E07M002M', '08N03E07N001M', '08N03E19D003M', '08N03E32L001M', '09N01E03C003M', '09N01E07D001M', '09N01E12M001M', '09N01E20E001M', '09N01E24D001M', '09N01E31D001M', '09N01W02Q002M', '09N01W07R001M', '09N01W08Q001M', '09N01W21E001M', '09N01W24G001M', '09N02E07L001M', '09N02E16N001M', '09N02E31D001M', '09N02E32M001M', '09N02E35E001M', '09N03E08C001M', '09N03E08C002M', '09N03E08C003M', '09N03E08C004M', '09N03E19R001M', '09N03E19R002M', '09N03E33B002M', '10N01E02Q002M', '10N01E14K001M', '10N01E18C001M', '10N01E23Q002M', '10N01E24E001M', '10N01E29K001M', '10N01W02Q001M', '10N01W08B001M', '10N01W09F002M', '10N01W19Q004M', '10N01W21J001M', '10N01W30K001M')
```

**Comment by maxstevenson** [comment]
Thanks Elpaso, the IN operator works! Funny that the chained OR expression used to work in older versions of QGIS but doesn't anymore.
