### ISSUE TITLE
QGIS crashes when opening project that contains for GRASS data

### ISSUE THREAD

**Issue by jcdavids** [qgis/QGIS#30476]
h2. User Feedback

Trying to open a .qgz file that was previously used to delineate a watershed using GRASS.  The program crashes on loading if I double click the .qgz file (perhaps because it is trying to open it without GRASS).  If I launch QGIS with GRASS and then open the file through the program it works.

h2. Report Details

*Crash ID*: 6626b16d52041d320ecddeef69beb45fc8764c8f

*Stack Trace*
<pre>
QgsLayerStylingWidget::setLayer :
QMetaObject::activate :
QgsMapLayerComboBox::layerChanged :
QMetaObject::activate :
QAbstractItemModel::endInsertRows :
QSortFilterProxyModel::insertRows :
QSortFilterProxyModel::sortRole :
QSortFilterProxyModel::`default constructor closure' :
QMetaObject::activate :
QAbstractItemModel::endInsertRows :
QgsMapLayerModel::addLayers :
QMetaObject::activate :
QgsProject::layersAdded :
QMetaObject::activate :
QgsMapLayerStore::layersAdded :
QgsMapLayerStore::addMapLayers :
QgsProject::addMapLayers :
QgsProject::addLayer :
QgsProject::_getMapLayers :
QgsProject::readProjectFile :
QgsProject::unzip :
QgsProject::read :
QgisApp::addProject :
QgisApp::openProject :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.6.3-Noosa
QGIS code revision: commit:0c5774c068
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by gioman** [comment]
> Trying to open a .qgz file that was previously used to delineate a watershed using GRASS. The program crashes on loading if I double click the .qgz file (perhaps because it is trying to open it without GRASS). If I launch QGIS with GRASS and then open the file through the program it works.

@jcdavids 
so I guess you are talking about the GRASS plugin and not the Processing toolbox, correct?

**Comment by jcdavids** [comment]
> @jcdavids so I guess you are talking about the GRASS plugin and not the Processing toolbox, correct?

@gioman Yes, indeed I was using the GRASS plugin and not the Processing toolbox.  

To give a bit more context, I'm working with the UN Food and Agriculture Organization to train water managers and water researchers in Myanmar and Afghanistan on using GIS, remote sensing, and programming.  I posted another issue about QGIS 3.6.3 GRASS 7.6.1 crashing when trying to open a new map set.  I would like to follow up with the training participants with a solution once one is available.  I supposed we can use an older version, but I'm not sure when the bug started.  Thanks for your work on this and, while I'm not a programmer, I hope I can play an active role in supporting the QGIS community.

**Comment by gioman** [comment]
> To give a bit more context, I'm working with the UN Food and Agriculture Organization to train water managers and water researchers in Myanmar and Afghanistan on using GIS, remote sensing, and programming. I posted another issue about QGIS 3.6.3 GRASS 7.6.1 crashing when trying to open a new map set. I would like to follow up with the training participants with a solution once one is available. I supposed we can use an older version, but I'm not sure when the bug started. Thanks for your work on this and, while I'm not a programmer, I hope I can play an active role in supporting the QGIS community.

@jcdavids the point is simple: if you work with the GRASS plugin and load/save in a project GRASS data from a GRASS location/mapset, then to open the project you must use QGIS with GRASS support, that is why there is the "QGIS with GRASS" launcher on Windows. I agree that using QGIS without GRASS should not crash when opening project with GRASS data in them.

My suggestion for your case would be anyway to use the GRASS tools from the Procesising toolbox:  for such tools the inputs are not GRASS data, ie. shapes, geotiffs, etc., and the outputs are also shapes, geotiffs, etc. For normal users is a much easier approach (than having to understand that they have to manually import data into a GRASS mpaset, process the data with GRASS and then manually export the data to shapes, geotiffs, etc.).

**Comment by gioman** [comment]
Closing as do not seem to be the case anymore.
