### ISSUE TITLE
processing algorithm -- eliminate selected polygons: My Sliver polygons where not eliminated

### ISSUE THREAD

**Issue by Mi-Kbs-gis** [qgis/QGIS#30489]
This algorithm does not eliminate the sliver polygons in my dataset (see attachment).
A optional area tolerance or side length will be very handy.
The understanding of the algorithm name and description not simple. 
![grafik](https://user-images.githubusercontent.com/25895003/60435783-b44c0e00-9c0a-11e9-95f3-177b2049da50.png)

![grafik](https://user-images.githubusercontent.com/25895003/60435815-ccbc2880-9c0a-11e9-9810-833f85872b33.png)
[Profil_83.zip](https://github.com/qgis/QGIS/files/3345483/Profil_83.zip)

**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by gioman** [comment]
QGIS native tools in general do not clean/fix topology problems. You can fix them, for example using the "snapping" option in the GRASS v.clean tool in the QGIS Processing toolbox.

Before:

![Screenshot_20190702_100420](https://user-images.githubusercontent.com/1951107/60499770-05aed880-9cb1-11e9-8937-541ee0660b02.png)

After:

![Screenshot_20190702_100429](https://user-images.githubusercontent.com/1951107/60499780-09daf600-9cb1-11e9-8cb3-6d32c7784a3e.png)

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
