### ISSUE TITLE
PostGIS raster won't load because GDAL connection error

### ISSUE THREAD

**Issue by constant5** [qgis/QGIS#30496]
When trying to add a raster table from a PostGIS DB using the Database Manager I am prompted for a login. After three attempts the layer loads but with none of the constraint or band information.  To be clear I can add the DB data source and see the schemas and tables in the Browser. 

I checked for gdalinfo in the OSGeo shell and I was able to connect to the database and retrieve the information. 

I have experimented with various postgres configuration settings but nothing seems to work.  It seems that the server is refusing the gdal connection.  Is anyone else experiencing this and/or found a fix?

**Comment by gioman** [comment]
@constant5 duplicate/related of https://github.com/qgis/QGIS/issues/30392 ?

**Comment by constant5** [comment]
I added my comments to that page.
