### ISSUE TITLE
crash closing Qgis

### ISSUE THREAD

**Issue by limmyjw** [qgis/QGIS#30494]
**Describe the bug**
Crash when closing Qgis

**How to Reproduce**

**QGIS and OS versions**

Win10 Qgis 3.8.0

**Additional context**

Crash ID: 62f1fcd2045780cb9f127836e6b579b8665f3e63

Stack Trace

proj_lpz_dist :
proj_lpz_dist :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::QgsCoordinateTransform :
QHashData::free_helper :
QgsCoordinateTransform::addToCache :
QgsCoordinateTransform::invalidateCache :
QgsApplication::exitQgis :
QgisApp::~QgisApp :
CPLStringList::operator[] :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.8.0-Zanzibar
QGIS code revision: 11aff65f10
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by gioman** [comment]
@limmyjw please try with a new/clean QGIS profile, no 3rd party plugins installed. Thanks.

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
