### ISSUE TITLE
How to create temporary vector layer without features and then add some features to this layer Qgis 3.6?

### ISSUE THREAD

**Issue by AllahofUkrain** [qgis/QGIS#30505]
Good morning. I'm working on creating python plugins for Qgis 3.6 and my quation is: why I can't create empty temporary vector layer and then add new feature to this layer using python but can do this by standart opportunities provided by the program? Rigth now Qgis shows me massage about error when I want to add feature to this layer. If I can do this show me how.

Right now I'm creating one feature at the layer and add this layer to the project.

My code looks like this:

vl = QgsVectorLayer('Point?crs=100000', 'temporary_points', 'memory')
QgsProject.instance().addMapLayer(vl)
pr = vl.dataProvider()
vl.startEditing()
fet = QgsFeature()
fet.setGeometry(QgsGeometry.fromPointXY(QgsPointXY(10, 10)))
pr.addFeatures([fet])
vl.commitChanges()

**Comment by gioman** [comment]
@AllahofUkrain questions are better suited for the QGIS users/developers mailing list, not here.
