### ISSUE TITLE
Raster Image Marker shifting not operational with data defined

### ISSUE THREAD

**Issue by djes** [qgis/QGIS#30504]
[Tested on QGIS 3.6.3] Raster Image Markers can be shifted manually on x and y, but not when using data defined.
![image](https://user-images.githubusercontent.com/12065874/60494723-9d132c00-9caf-11e9-9c17-42a46e6e9165.png)

**Comment by nirvn** [comment]
@djes , your syntax is not valid. It's a bit counter-intuitive, but you have to use a string, with comma separated values (e.g. '10,5' would be an offset of x=10 and y=5).

**Comment by djes** [comment]
Thank you ! It works with 'value for x, value for y' eg.  `'50, 100'`. The [x ,y] is counter-intuitive, yes, hope it will be changed... 
![image](https://user-images.githubusercontent.com/12065874/60572137-3c4e2700-9d75-11e9-9e10-30f50f0de216.png)
