### ISSUE TITLE
the line_interpolate_angle() function does not return the same value if the feature is multipart or single part

### ISSUE THREAD

**Issue by FERRATON** [qgis/QGIS#30515]
see dataset.
[dataset.zip](https://github.com/qgis/QGIS/files/3350456/dataset.zip)
the difference is around 180 degrees.

**Comment by lbartoletti** [comment]
Please, can you try with the latest version? It seems to work for me, apart rounding approximation.

![line_interpolate_angle mkv](https://user-images.githubusercontent.com/7521540/107196413-e3378200-69f2-11eb-9a91-c15f873db7fa.gif)

**Comment by lbartoletti** [comment]
BTW, I wonder if we should add a part argument to compute the angle of the line in multipart geom

**Comment by FERRATON** [comment]
I confirm that the result is ok with QGIS 3.16.
Sorry, I didn't understand how the additional argument could work?
