### ISSUE TITLE
Editing column not possible if column name contains uppercase letters

### ISSUE THREAD

**Issue by IBHeberle** [qgis/QGIS#30516]
- If the column name contains only uppercase letters it's not possible to edit an element in the attribute table. 

**How to Reproduce**
-generate a new column in the attribute table as string (100) and set the name "TYP". Save the layer and create an element in the layer. Try to write something in the field "TYP". It is not possible to edit it.

QGIS Version 3.6 and 3.8

**Comment by gioman** [comment]
@IBHeberle can't confirm with shapes and postgis layer on qgis master on linux.

**Comment by IBHeberle** [comment]
I'm working with Windows 10 Professional.

**Comment by gioman** [comment]
> I'm working with Windows 10 Professional.

@IBHeberle can't confirm on win10 QGIS 3.8 too.

You may want to try on a new/clean QGIS profile, no 3rd party plugins installed.
If problem persist then add more details, like the type of data you are using, etc.

**Comment by alexbruy** [comment]
Not reproducible on Windows and Linux.
