### ISSUE TITLE
QGIS crashes when assigning a XYZ layer a different CRS

### ISSUE THREAD

**Issue by cfessler** [qgis/QGIS#30519]
As i am new to QGIS i am not so sure if this a a wanted behavior. But i did not find anything on it in the manual and also not in the web. As it also might affect others i try to do my first "bug"-report:

When connecting to a service via XYZ-Tiles, QGIS automatically chooses EPSG:3857 - WGS 84. 
![image](https://user-images.githubusercontent.com/52469130/60543274-2bba9400-9d16-11e9-92c6-45ec6202d0bc.png)

Therefore i get status 200 but no return when QGIS tries to load that tiles. And i think this is because coordinates of the request are way out of the range the remote server is expecting (it expects UTM 32U it think when looking on a valid request: "catalogNodes=11&E=**586237.08**&N=**5350634.03**&zoom=13&layers=luftbild_parz"). 
![image](https://user-images.githubusercontent.com/52469130/60543217-0463c700-9d16-11e9-80d3-bd421d7a7c49.png)

**How to Reproduce**
You can easily reproduce my problem by adding a "new connection" on "XYZ Tiles" based on that URL for example:
https://geoportal.bayern.de/bayernatlas/?lang=de&topic=ba&bgLayer=atkis&catalogNodes=11,122&layers=luftbild_parz&E=692537.11&N=5406153.53&zoom=9
by replacing (as far i understood).
lang=de&topic=ba&bgLayer=atkis&catalogNodes=11,122&layers=luftbild_parz&E={X}&N={Y}&zoom={Z}

I hope i did that report right. Thank you all for that great work!

QGIS-Version
3.8.0-Zanzibar
QGIS-Codeversion
11aff65f10
Kompiliert gegen Qt
5.11.2
Laufendes Qt
5.11.2
Kompiliert mit GDAL/OGR
2.4.1
Läuft mit GDAL/OGR
2.4.1
Kompiliert mit GEOS
3.7.2-CAPI-1.11.0
Läuft mit GEOS
3.7.2-CAPI-1.11.0 b55d2125
PostgreSQL-Client-Version
9.2.4
SpatiaLite-Version
4.3.0
QWT-Version
6.1.3
QScintilla2-Version
2.10.8
Kompiliert mit PROJ
5.2.0
Läuft mit PROJ
Rel. 5.2.0, September 15th, 2018
OS Version
Windows 10 (10.0)

**Comment by nyalldawson** [comment]
Your URL isn't correct here, it should look something more like:

https://intergeo37.bayernwolke.de/betty/satdop40_komplett/9/266/253

**Comment by cfessler** [comment]
Unfortunately I do not understand: to url you posted does not contain {X} {Y} {Z}.

Is that a real XYZ Tiles url?

**Comment by cfessler** [comment]
> Your URL isn't correct here, it should look something more like:
> 
> https://intergeo37.bayernwolke.de/betty/satdop40_komplett/9/266/253

Thank you nyalldawson
Unfortunately I do not understand: the url you posted does not contain {X} {Y} {Z}.
Is that a real XYZ Tiles url anyway?

**Comment by saberraz** [comment]
The URL to add in QGIS for https://intergeo37.bayernwolke.de/betty/satdop40_komplett/9/266/253 is going to be:
https://intergeo37.bayernwolke.de/betty/satdop40_komplett/{z}/{x}/{y}

According to XYZ tile standard (https://en.wikipedia.org/wiki/Tiled_web_map), web  marcator should be used for the CRS. But the service appears to use a different CRS

**Comment by cfessler** [comment]
> The URL to add in QGIS for https://intergeo37.bayernwolke.de/betty/satdop40_komplett/9/266/253 is going to be:
> [https://intergeo37.bayernwolke.de/betty/satdop40_komplett/{z}/{x}/{y}](https://intergeo37.bayernwolke.de/betty/satdop40_komplett/%7Bz%7D/%7Bx%7D/%7By%7D)
> 
> According to XYZ tile standard (https://en.wikipedia.org/wiki/Tiled_web_map), web marcator should be used for the CRS. But the service appears to use a different CRS

Thank you! now i understood the url thing above.
Yes it seems like the underlying CRS is EPSG 25832. Is there a way for me to get the tiles anyway (even the server has a different CRS and i have no coding abilities)?

**Comment by saberraz** [comment]
Once the layer added in QGIS, open the properties and under Source, change the CRS for your layer to 25832.

I am closing this ticket. For further help, please contact QGIS mailing list.

**Comment by cfessler** [comment]
> Once the layer added in QGIS, open the properties and under Source, change the CRS for your layer to 25832.
> 
> I am closing this ticket. For further help, please contact QGIS mailing list.
will do so, thank you
->changing the CRS (of XYZ Tiles Layer) had no effect for me, that is what i meant

**Comment by saberraz** [comment]
I see, I tested it in master and it crashed QGIS. I think the ticket can be spilt into two tickets: one is a bug with QGIS which causes crash when you assign a different CRS to . The second one is due to the fact that the XYZ layers are always set to the web Mercator (need to check that with my @wonder-sk).

**Comment by cfessler** [comment]
> I see, I tested it in master and it crashed QGIS. I think the ticket can be spilt into two tickets: one is a bug with QGIS which causes crash when you assign a different CRS to . The second one is due to the fact that the XYZ layers are always set to the web Mercator (need to check that with my @wonder-sk).

great, thanks a lot!

**Comment by gioman** [comment]
> The second one is due to the fact that the XYZ layers are always set to the web Mercator

@saberraz 
this is possibly the correct behavior. If the specifications say that such layers must be in 3857 then QGIS is right. It happens the same with GPX files: QGIS add them as 4326 without asking... but actually they can contain coordinates in a different CRS.

**Comment by saberraz** [comment]
@gioman I agree, it is a correct behaviour. But, if you change the CRS it will crash QGIS with core dump in master.

**Comment by gioman** [comment]
> But, if you change the CRS it will crash QGIS with core dump in master.

I changed the ticket title.

**Comment by cfessler** [comment]
> > The second one is due to the fact that the XYZ layers are always set to the web Mercator
> 
> @saberraz
> this is possibly the correct behavior. If the specifications say that such layers must be in 3857 then QGIS is right. It happens the same with GPX files: QGIS add them as 4326 without asking... but actually they can contain coordinates in a different CRS.

so could this be a feature for the future? the possibility to change the CRS i mean? is there anything i could assist with?

**Comment by saberraz** [comment]
It can be a feature. Also, we were thinking of having it also in XYZ tile generator algorithm.
Ping me, if you'd like to fund the feature.

**Comment by saberraz** [comment]
@cfessler by the way, the website you are trying to get the XYZ tile, might also offer WMTS. For that, the projection should work fine.

**Comment by wonder-sk** [comment]
As far as I know, xyz tiles are always in Web Mercator projection. Together with fixed CRS, there is also fixed extent so that the root tile is a square image. So for other CRS one would also need to define extent. For custom CRS I would recommend using WMTS / TMS protocols that allow all that.

**Comment by gioman** [comment]
> I see, I tested it in master and it crashed QGIS

@saberraz @cfessler no more crashes changing that layer CRS manually. Latest master on Ubuntu 20.04, closing?

**Comment by gioman** [comment]
Closing for lack of feedback.
