### ISSUE TITLE
QGIS 3.8 chenyx06etrs.gsb is missing

### ISSUE THREAD

**Issue by snoopy21** [qgis/QGIS#30513]
After installing GQIS 3.8, which replaced QGIS 3.6, the file "chenyx06etrs.gsb" for the datum transformation from CH1903 into CH1903+ is missing. 
In older releases the file was in directory share/proj.

**Comment by nyalldawson** [comment]
This is a proj issue, not qgis.

**Comment by jef-n** [comment]
Where did you install QGIS from?

**Comment by snoopy21** [comment]
@jef-n I installed QGIS via Chocolately on Windows 10.

**Comment by jef-n** [comment]
ok, AFAIK we didn't include "chenyx06etrs.gsb" anywhere in our packages (which Chocolately  isn't anyway)

**Comment by snoopy21** [comment]
@jef-n well I tested it on my laptop, where I upgraded QGIS too but in this case I downloaded QGIS from qgis.org. I received the same error. My guess is that this behaviour is linked to the new Coordinate Transform Handling. I should receive a download link for the .gsb-file. Shall I file this bug the PROJ-project?

**Comment by rouault** [comment]
The grid was added recently, as CHENYX06_etrs.gsb, conforming with the name in the EPSG dataset and as expected by PROJ 6, in the proj-datumgrid repository per https://github.com/OSGeo/proj-datumgrid/commit/fe58b5c08c4968fc774577e841dca973b3d74a0e  and will be included in proj-datumgrid-europe-1.4 package. When available, PROJ 6 should be able to automatically use it

**Comment by nyalldawson** [comment]
I think the path forward here lies in the chocolatey repo - they need to make the proj datum grid packages a dependancy of proj (or qgis)

**Comment by snoopy21** [comment]
@nyalldawson as mentioned before the problem occurs also if I do an install with a package from qgis.org.

**Comment by nyalldawson** [comment]
In that case you'd need to file a request at osgeo4w to make the Europe (and North America?) datum grids a dependency of the qgis package too. Better do it for the Lutra Macos packages also to cover all bases.

**Comment by jef-n** [comment]
> as mentioned before the problem occurs also if I do an install with a package from qgis.org.

Sure, as I said we never included it - so it's not it wasn't there in earlier releases (speaking about our packages).   We probably have many more gsb that you have to fetch manually, if you need them - maybe even some that are not freely available anyway.

**Comment by jef-n** [comment]
> In that case you'd need to file a request at osgeo4w to make the Europe (and North America?) datum grids a dependency of the qgis package too. Better do it for the Lutra Macos packages also to cover all bases.

It does.  But the the releases we use along PROJ 5 didn't include the swiss grid.

**Comment by nyalldawson** [comment]
@jef-n I think @snoopy21 is mistaken in saying we previously included this. What's actually the case is that proj <= 4 didn't FORCE use of this grid when converting between some coordinate systems, but on proj 6 the only path between these CRSs is via the grid. So in the past QGIS did... something/nothing/randomly shifted points?.. (@rouault ?) to convert between these CRSes, but it wasn't using the grid. :scream:

**Comment by jef-n** [comment]
> @jef-n I think @snoopy21 is mistaken in saying we previously included this.

If this is about our package, I know he is.   I just don't know about Chocolately.   I also depends on the definition of the CRS - grids could be optional or mandatory (depending on whether or not they were prefixed with @)

**Comment by snoopy21** [comment]
@nyalldawson you could be right 
<img width="568" alt="trafo" src="https://user-images.githubusercontent.com/9284030/60867105-58950c80-a22a-11e9-91bc-49be40e1c893.png">
I studied again the message above. It seems that I had defined an earlier ntv2 transformation between LV03<->LV95. So my apologies for the misinformation. If I understand @rouault right, the missing file will be included in a future PROJ upgrade.

**Comment by mangecoeur** [comment]
I'm experiencing this issue on macOS with QGIS 3.10
