### ISSUE TITLE
QgsJsonExporter not using JSON array for list attributes

### ISSUE THREAD

**Issue by plutoscarab** [qgis/QGIS#30521]
**Steps**
1. Import GeoJSON layer with array-typed attribute
2. Set the editor widget for that attribute to "List" so that values can be edited properly in attribute forms
3. Use `exportFeature` method of `QgsJsonExporter` to generate GeoJson representation of a feature from the layer

**Expected:** List-valued attribute represented as JSON array

**Actual:** List-value attribute represented as comma-delimited JSON string

**Comment by elpaso** [comment]
Isn't there a field for QGIS affected Version in the bug reporting template?

**Comment by nyalldawson** [comment]
@elpaso I don't think that was ever decided on. It was originally (incorrectly) mapped to github milestones, but all outdated milestones are closed now. We'll need new labels for affected version I believe.

**Comment by DelazJ** [comment]
> Isn't there a field for QGIS affected Version in the bug reporting template?

There's a dedicated section in the template (nothing we can use to filter reports but at least, it should give necessary information for each)
![image](https://user-images.githubusercontent.com/7983394/60565658-c6da5a80-9d64-11e9-87fa-d95bae33c86e.png)

**Comment by stev-0** [comment]
I have used the attached geojson as a reference implementation, and I don't even get the option to use the List attribute on master. @plutoscarab please detail which version you are using.
[example_geojson.txt](https://github.com/qgis/QGIS/files/3408826/example_geojson.txt)

**Comment by plutoscarab** [comment]
It's the Noosa version, 3.8.something, I'll have to wait until I can get back in to the office to look it up.

Setting the List widget was done in Python, not in the UI. I can post the code snippet when I get in.

**Comment by plutoscarab** [comment]
Sorry, it's 3.8.0-Zanzibar.  To associate attribute editor field with List widget, I did
`list_widget = QgsEditorWidgetSetup("List", {})` followed by `my_layer.setEditorWidgetSetup(3, list_widget)` where "3" is the field index (I set several of them).

**Comment by Pedro-Murteira** [comment]
@plutoscarab Hello, is this still valid on the recent releases?
