### ISSUE TITLE
[label] labels with rule do not refresh when expression is updated

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#30520]
labeling a vector layer using a rule does not update the labels automatically.

## reproduce the problem

1. load a polygonal vector;
2. label by rule;
3. use the filter `fieldname IN (value1, value2)`;
4. label with `nomecampox`
5. modify the filter `fieldname IN (value1, value2, value3)` using the _expression constructor_;
6. the change is not displayed even if we press on **apply** or **update map**

## operating system and version
OSGeo4W64 Network installer
```
Versione di QGIS 3.4.9-Madeira
Revisione codice QGIS 54585165bb
Compilato con Qt 5.11.2
Esecuzione con Qt 5.11.2
Compilato con GDAL/OGR 2.4.1
Esecuzione con GDAL/OGR 2.4.1
Compilato con GEOS 3.7.2-CAPI-1.11.0
Esecuzione con GEOS 3.7.2-CAPI-1.11.0 b55d2125
Versione client PostgreSQL 9.2.4
Versione SpatiaLite 4.3.0
Versione QWT 6.1.3
Versione QScintilla2 2.10.8
Compiled against PROJ 520
Running against PROJ 5.2.0
```
## gif

![mah](https://user-images.githubusercontent.com/7631137/60543207-ff9f1300-9d15-11e9-8dd0-432987fd070f.gif)

## I attach project and data

[test.zip](https://github.com/qgis/QGIS/files/3352162/test.zip)

in this example, add the value 15 to obtain  `"cod_reg"  in (1,20,15)`

**thanks and good job**

**Comment by nyalldawson** [comment]
I can't reproduce -- is this still an issue?

**Comment by pigreco** [comment]
Today I did other tests, it works in 3.10, 3.12 and master

thanks, close issue.
