### ISSUE TITLE
Al abrir un proyecto, no me deja conmutar edición. No puedo trabajar sobre ninguna capa, como podría arreglarlo? Utilizo la versión 3.6.3

### ISSUE THREAD

**Issue by jarocu** [qgis/QGIS#30523]
**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by gioman** [comment]
Tickets must be filed in English and must contain the requested infos: the following must be filled:

Describe the bug

How to Reproduce

QGIS and OS versions

Additional context
