### ISSUE TITLE
Error open MS SQL by OGR

### ISSUE THREAD

**Issue by grig27** [qgis/QGIS#30545]
Trying to open a MS SQL layer using OGR.
Use code: 
`uri = "MSSQL:server=GEOSERV;database=ZIISSAMNG;tables=ZIIS_SK63.OBJ_PAR;UID=zisadmin;PWD=aaaa)"
OBJ_PAR = QgsVectorLayer(uri, "ZEM", "ogr")`

Layer not valid.

CPL_LOG: 
`GDAL: Auto register C:\OSGeo4W\bin\gdalplugins\gdal_GEOR.dll using GDALRegister_GEOR.
GDAL: Auto register C:\OSGeo4W\bin\gdalplugins\ogr_OCI.dll using RegisterOGROCI.
GNM: GNMRegisterAllInternal
GNM: RegisterGNMFile
GNM: RegisterGNMdatabase
MSSQLSpatial: Use COPY/BCP: 0
ODBC: SQLDriverConnect(DRIVER={SQL Server Native Client 11.0};server=GEOSERV;database=ZIISSAMNG;UID=zisadmin;PWD=aaa))
ODBC: ... failed: 
ODBC: SQLDisconnect()
CPLError: Unable to initialize connection to the server for MSSQL:server=GEOSERV;database=ZIISSAMNG;tables=ZIIS_SK63.OBJ_PAR;UID=zisadmin;PWD=aaa),

Try specifying the driver in the connection string from the list of available drivers:
SQL Server
Microsoft ODBC for Oracle
Microsoft Access Driver (*.mdb)
Microsoft Access-Treiber (*.mdb)
Driver do Microsoft Access (*.mdb)
Microsoft dBase Driver (*.dbf)
Microsoft dBase-Treiber (*.dbf)
Driver do Microsoft dBase (*.dbf)
Microsoft Excel Driver (*.xls)
Microsoft Excel-Treiber (*.xls)
Driver do Microsoft Excel(*.xls)
Microsoft Paradox Driver (*.db )
Microsoft Paradox-Treiber (*.db )
Driver do Microsoft Paradox (*.db )
Microsoft Text Driver (*.txt; *.csv)
Microsoft Text-Treiber (*.txt; *.csv)
Driver da Microsoft para arquivos texto (*.txt; *.csv)
Microsoft Visual FoxPro Driver
Microsoft FoxPro VFP Driver (*.dbf)
Microsoft dBase VFP Driver (*.dbf)
Microsoft Visual FoxPro-Treiber
Driver para o Microsoft Visual FoxPro
SQL Server Native Client 11.0
Microsoft Access dBASE Driver (*.dbf, *.ndx, *.mdx)
ODBC Driver 11 for SQL Server
Oracle in oracle9
PostgreSQL ODBC Driver(ANSI)
PostgreSQL ODBC Driver(UNICODE)
ODBC Driver 13 for SQL Server
Microsoft Access Driver (*.mdb, *.accdb)
Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)
Microsoft Access Text Driver (*.txt, *.csv)

ERROR 1: Unable to initialize connection to the server for MSSQL:server=GEOSERV;database=ZIISSAMNG;tables=ZIIS_SK63.OBJ_PAR;UID=zisadmin;PWD=aaa),

Try specifying the driver in the connection string from the list of available drivers:
SQL Server
Microsoft ODBC for Oracle
Microsoft Access Driver (*.mdb)
Microsoft Access-Treiber (*.mdb)
Driver do Microsoft Access (*.mdb)
Microsoft dBase Driver (*.dbf)
Microsoft dBase-Treiber (*.dbf)
Driver do Microsoft dBase (*.dbf)
Microsoft Excel Driver (*.xls)
Microsoft Excel-Treiber (*.xls)
Driver do Microsoft Excel(*.xls)
Microsoft Paradox Driver (*.db )
Microsoft Paradox-Treiber (*.db )
Driver do Microsoft Paradox (*.db )
Microsoft Text Driver (*.txt; *.csv)
Microsoft Text-Treiber (*.txt; *.csv)
Driver da Microsoft para arquivos texto (*.txt; *.csv)
Microsoft Visual FoxPro Driver
Microsoft FoxPro VFP Driver (*.dbf)
Microsoft dBase VFP Driver (*.dbf)
Microsoft Visual FoxPro-Treiber
Driver para o Microsoft Visual FoxPro
SQL Server Native Client 11.0
Microsoft Access dBASE Driver (*.dbf, *.ndx, *.mdx)
ODBC Driver 11 for SQL Server
Oracle in oracle9
PostgreSQL ODBC Driver(ANSI)
PostgreSQL ODBC Driver(UNICODE)
ODBC Driver 13 for SQL Server
Microsoft Access Driver (*.mdb, *.accdb)
Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)
Microsoft Access Text Driver (*.txt, *.csv)`

QGIS Info
QGIS Version: 3.6.3-Noosa

QGIS code revision: 0c5774c068

Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: x86_64
Microsoft Windows [Version 6.1.7601]

**Comment by gioman** [comment]
@grig27 why trying to connect via odbc when in QGIS you have the native MSSQL provider?

**Comment by grig27** [comment]
This supplier cannot load objects of different topology (Polygons of the line and points in one layer). I try different options.

**Comment by gioman** [comment]
> This supplier cannot load objects of different topology (Polygons of the line and points in one layer). I try different options.

@grig27 do you refer to geometry collections? if yes then in QGIS are not supported (as far as I remember).

**Comment by grig27** [comment]
> do you refer to geometry collections?

No, not a collection. And the table in which different types of objects.

**Comment by gioman** [comment]
> And the table in which different types of objects.

@grig27 sorry I'm lost, I'm don't understand what you mean here. But I ask again, are you using the QGIS native MS SQL provider?

**Comment by grig27** [comment]
I'll try to explain again. The integrated MS SQL provider requires you to specify the type of geometry for the displayed layer.
Specified parameter "type". For example - "uri.setParam (" type "," MultiPolygon ")".
You cannot specify multiple types for a layer. If you do not specify a type at all, objects will not appear on the map.
I tried to use OGR. But got the above error.

**Comment by gioman** [comment]
@grig27 this would be better asked in the developers mailing list, rather than assuming it is right away a bug.
