### ISSUE TITLE
Open / cancel button

### ISSUE THREAD

**Issue by geoAndr3** [qgis/QGIS#30546]
I everybody,
I would like to suggest an improvement in the vector/raster/WMS/ ecc loading windows.
In 3.4.8 version "add" and "close" buttons are at the bottom right of the window: "close" button at right and "add" button at left. I suggest to reverse the two buttons, just to make them in the same position they have in previous versions.
Thanks a lot,

Andrea

**Comment by alexbruy** [comment]
Buttons order follow system/DE HIG.
