### ISSUE TITLE
Crash on storing json/jsonb value on PG

### ISSUE THREAD

**Issue by signedav** [qgis/QGIS#30558]
**Describe the bug**
Recognized it when trying to store value relation multi lists as JSON in a json field of Postgresql. On saving QGIS crashed.

Tried it with "key/value" widget and stored as a map. On storing an exception raises 

> [json.exception.type_error.305] cannot use operator[] with a string argument with array

and when tried with a "list" widget and stored as array, QGIS crashed again. But not always.

I need to make more investigation, but apparently sometimes it goes in an infinite loop on `QgsJsonUtils::jsonFromVariant`

**QGIS and OS versions**
Ubuntu and Master/3.6/3.8

**Additional context**
I'll have a look on it on beginning of next week.

**Comment by signedav** [comment]
Someone could assign me, please? :man_factory_worker:

**Comment by elpaso** [comment]
@signedav this may be coming from the json serialization code inside json library.
Can you check what input caused the exception? There is a decent test coverage for that method, if you find a failing test. 
See: https://github.com/nlohmann/json_docs/blob/master/docs/exceptions.md#type_error

**Comment by powersa** [comment]
I'm seeing similar errors when writing jsonb to Postgres. Here are the SQL statements that QGIS executes on my DB for 3 feature update scenarios:

JSONB Properties Edit Only:
`
LOG:  statement: BEGIN
LOG:  statement: UPDATE "public"."local_test" SET "properties"='{"Category":"Utility_hole","Color":"Orange","Composition":"Metal","HasPole":"true","ID":84,"Layer":"Roadbeds","Persistence":"Permanent","Text":null}'::jsonb WHERE "id"::text='1002'
LOG:  statement: COMMIT`

Geometry Edit Only:

`LOG:  statement: BEGIN
LOG:  execute updatefeatures: UPDATE "public"."local_test" SET "geom"=st_geomfromwkb($1::bytea,4326) WHERE "id"::text=$2
DETAIL:  parameters: $1 = '\x01eb030000010000000900000094dff5dbaf915ec050a63c80e6e5424000000080548a3cc0444329ceaf915ec020aef776e6e5424000000060008a3cc0ff5f89c8af915ec0983dee60e6e542400000000058893cc00c0660ceaf915ec03029074be6e54240000000a04d893cc0cc2e43dcaf915ec0003d1a42e6e54240000000c0048a3cc01ccb0feaaf915ec028355f4be6e5424000000080208b3cc07c7763e8af915ec05388d060e6e5424000000040878b3cc05408d9e9af915ec01fba4f77e6e54240000000601f8b3cc094dff5dbaf915ec050a63c80e6e5424000000080548a3cc0', $2 = '1002'
LOG:  statement: DEALLOCATE updatefeatures
LOG:  statement: COMMIT`

Geometry + JSONB Edit:
`LOG:  statement: BEGIN
ERROR:  column "properties" is of type jsonb but expression is of type hstore at character 47
HINT:  You will need to rewrite or cast the expression.
STATEMENT:  UPDATE "public"."local_test" SET "properties"=E'"Category"=>"Utility_hole","Color"=>"Grey","Composition"=>"Metal","HasPole"=>"true","ID"=>"84","Layer"=>"Roadbeds","Persistence"=>"Permanent","Text"=>""'::hstore,"geom"=st_geomfromwkb($1::bytea,4326) WHERE "id"::text='1002'
LOG:  statement: ROLLBACK`

@signedav, is this related to the issues you're seeing? If not, I can open a separate issue.

**Comment by signedav** [comment]
Not sure @powersa I need to do more investigation for this.
