### ISSUE TITLE
QGIS Crash

### ISSUE THREAD

**Issue by mone27** [qgis/QGIS#30556]
Today QGis hanged and then crashed two times. Sadly I was not able to figure out which operation triggered the crash. I am including the stack trace and the backtrace
this is my Installation info:

QGIS version | 3.8.0-Zanzibar | QGIS code branch | Release 3.8
-- | -- | -- | --
Compiled against Qt | 5.12.1 | Running against Qt | 5.12.1
Compiled against GDAL/OGR | 2.3.2 | Running against GDAL/OGR | 2.3.2
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Fedora 30 (Workstation Edition) |   |  

Please let me know what I can do to report better this bug and if this kind of bug report are still useful or totally pointless.

`#0  0x00007f5980abde75 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f5980aa8895 in __GI_abort () at abort.c:79
#2  0x000056108a2d3344 in qgisCrash(int) (signal=<optimized out>) at /usr/src/debug/qgis-3.8.0-1.fc30.x86_64/src/app/main.cpp:359
#3  0x00007f5980abdf00 in <signal handler called> () at /lib64/libc.so.6
#4  0x00007f5981acb344 in  () at /lib64/libQt5Widgets.so.5
#5  0x00007f5981acb467 in  () at /lib64/libQt5Widgets.so.5
#6  0x00007f5981a51b27 in QWidgetPrivate::inheritStyle() () at /lib64/libQt5Widgets.so.5
#7  0x00007f5981a62173 in QWidget::setParent(QWidget*, QFlags<Qt::WindowType>) () at /lib64/libQt5Widgets.so.5
#8  0x00007f5981a3ef03 in QLayout::addChildWidget(QWidget*) () at /lib64/libQt5Widgets.so.5
#9  0x00007f5981b41d2f in QDockWidgetLayout::setWidgetForRole(QDockWidgetLayout::Role, QWidget*) () at /lib64/libQt5Widgets.so.5
#10 0x00007f5983fa67e5 in QgsAttributeTableDialog::toggleDockMode(bool) (this=0x561097398e80, docked=<optimized out>) at /usr/src/debug/qgis-3.8.0-1.fc30.x86_64/src/app/qgsattributetabledialog.cpp:1192
#11 0x00007f59810ed6f0 in QMetaObject::activate(QObject*, int, int, void**) () at /lib64/libQt5Core.so.5
#12 0x00007f5981a184d6 in QAction::toggled(bool) () at /lib64/libQt5Widgets.so.5
#13 0x00007f5981a1a9c7 in QAction::setChecked(bool) () at /lib64/libQt5Widgets.so.5
#14 0x00007f5981a1aaea in QAction::activate(QAction::ActionEvent) () at /lib64/libQt5Widgets.so.5
#15 0x00007f5981b14090 in  () at /lib64/libQt5Widgets.so.5
#16 0x00007f5981b142b5 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () at /lib64/libQt5Widgets.so.5
#17 0x00007f5981c0727e in QToolButton::mouseReleaseEvent(QMouseEvent*) () at /lib64/libQt5Widgets.so.5
#18 0x00007f5981a60fce in QWidget::event(QEvent*) () at /lib64/libQt5Widgets.so.5
#19 0x00007f5981c07328 in QToolButton::event(QEvent*) () at /lib64/libQt5Widgets.so.5
#20 0x00007f5981a1ead6 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#21 0x00007f5981a281a3 in QApplication::notify(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#22 0x00007f59825dd14b in QgsApplication::notify(QObject*, QEvent*) (this=0x7ffc8f0d6b30, receiver=0x5610a5ae0790, event=0x7ffc8f0d5fa0) at /usr/src/debug/qgis-3.8.0-1.fc30.x86_64/src/core/qgsapplication.cpp:399
#23 0x00007f59810c32e8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib64/libQt5Core.so.5
#24 0x00007f5981a27287 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () at /lib64/libQt5Widgets.so.5
#25 0x00007f5981a7d1dd in  () at /lib64/libQt5Widgets.so.5
#26 0x00007f5981a8008c in  () at /lib64/libQt5Widgets.so.5
#27 0x00007f5981a1ead6 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#28 0x00007f5981a27f50 in QApplication::notify(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#29 0x00007f59825dd14b in QgsApplication::notify(QObject*, QEvent*) (this=0x7ffc8f0d6b30, receiver=0x5610a26194f0, event=0x7ffc8f0d6460) at /usr/src/debug/qgis-3.8.0-1.fc30.x86_64/src/core/qgsapplication.cpp:399
#30 0x00007f59810c32e8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib64/libQt5Core.so.5
#31 0x00007f5981498350 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /lib64/libQt5Gui.so.5
#32 0x00007f5981499c7b in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /lib64/libQt5Gui.so.5
#33 0x00007f598147412b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Gui.so.5
#34 0x00007f5953f3e8ce in  () at /lib64/libQt5XcbQpa.so.5
#35 0x00007f5979cb9edd in g_main_dispatch (context=0x56108c3abf10) at ../glib/gmain.c:3189
#36 0x00007f5979cb9edd in g_main_context_dispatch (context=context@entry=0x56108c3abf10) at ../glib/gmain.c:3854
#37 0x00007f5979cba270 in g_main_context_iterate (context=context@entry=0x56108c3abf10, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:3927
#38 0x00007f5979cba313 in g_main_context_iteration (context=0x56108c3abf10, may_block=1) at ../glib/gmain.c:3988
#39 0x00007f59811183f5 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#40 0x00007f59810c22bb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#41 0x00007f59810c9fd6 in QCoreApplication::exec() () at /lib64/libQt5Core.so.5
#42 0x000056108a2cfe61 in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/qgis-3.8.0-1.fc30.x86_64/src/app/main.cpp:1567
`
`           PID: 4144 (qgis)
           UID: 1000 (simone)
           GID: 1000 (simone)
        Signal: 6 (ABRT)
     Timestamp: Thu 2019-07-04 17:30:53 CEST (1h 56min ago)
  Command Line: qgis
    Executable: /usr/bin/qgis
 Control Group: /user.slice/user-1000.slice/session-2.scope
          Unit: session-2.scope
         Slice: user-1000.slice
       Session: 2
     Owner UID: 1000 (simone)
       Boot ID: c21d3042ea004896a28a0000c50b4660
    Machine ID: a932737f75c64f5ca400611a4c7f3109
      Hostname: linux
       Storage: /var/lib/systemd/coredump/core.qgis.1000.c21d3042ea004896a28a0000c50b4660.4144.1562254253000000.lz4
       Message: Process 4144 (qgis) of user 1000 dumped core.
                
                Stack trace of thread 4144:
                #0  0x00007f5980abde75 raise (libc.so.6)
                #1  0x00007f5980aa8895 abort (libc.so.6)
                #2  0x000056108a2d3344 _Z9qgisCrashi (qgis)
                #3  0x00007f5980abdf00 __restore_rt (libc.so.6)
                #4  0x00007f5981acb344 n/a (libQt5Widgets.so.5)
                #5  0x00007f5981acb467 n/a (libQt5Widgets.so.5)
                #6  0x00007f5981a51b27 _ZN14QWidgetPrivate12inheritStyleEv (libQt5Widgets.so.5)
                #7  0x00007f5981a62173 _ZN7QWidget9setParentEPS_6QFlagsIN2Qt10WindowTypeEE (libQt5Widgets.so.5)
                #8  0x00007f5981a3ef03 _ZN7QLayout14addChildWidgetEP7QWidget (libQt5Widgets.so.5)
                #9  0x00007f5981b41d2f _ZN17QDockWidgetLayout16setWidgetForRoleENS_4RoleEP7QWidget (libQt5Widgets.so.5)
                #10 0x00007f5983fa67e5 _ZN23QgsAttributeTableDialog14toggleDockModeEb (libqgis_app.so.3.8.0)
                #11 0x00007f59810ed6f0 _ZN11QMetaObject8activateEP7QObjectiiPPv (libQt5Core.so.5)
                #12 0x00007f5981a184d6 _ZN7QAction7toggledEb (libQt5Widgets.so.5)
                #13 0x00007f5981a1a9c7 _ZN7QAction10setCheckedEb (libQt5Widgets.so.5)
                #14 0x00007f5981a1aaea _ZN7QAction8activateENS_11ActionEventE (libQt5Widgets.so.5)
                #15 0x00007f5981b14090 n/a (libQt5Widgets.so.5)
                #16 0x00007f5981b142b5 _ZN15QAbstractButton17mouseReleaseEventEP11QMouseEvent (libQt5Widgets.so.5)
                #17 0x00007f5981c0727e _ZN11QToolButton17mouseReleaseEventEP11QMouseEvent (libQt5Widgets.so.5)
                #18 0x00007f5981a60fce _ZN7QWidget5eventEP6QEvent (libQt5Widgets.so.5)
                #19 0x00007f5981c07328 _ZN11QToolButton5eventEP6QEvent (libQt5Widgets.so.5)
                #20 0x00007f5981a1ead6 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
                #21 0x00007f5981a281a3 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
                #22 0x00007f59825dd14b _ZN14QgsApplication6notifyEP7QObjectP6QEvent (libqgis_core.so.3.8.0)
                #23 0x00007f59810c32e8 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
                #24 0x00007f5981a27287 _ZN19QApplicationPrivate14sendMouseEventEP7QWidgetP11QMouseEventS1_S1_PS1_R8QPointerIS0_Ebb (libQt5Widgets.so.5)
                #25 0x00007f5981a7d1dd n/a (libQt5Widgets.so.5)
                #26 0x00007f5981a8008c n/a (libQt5Widgets.so.5)
                #27 0x00007f5981a1ead6 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
                #28 0x00007f5981a27f50 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
                #29 0x00007f59825dd14b _ZN14QgsApplication6notifyEP7QObjectP6QEvent (libqgis_core.so.3.8.0)
                #30 0x00007f59810c32e8 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
                #31 0x00007f5981498350 _ZN22QGuiApplicationPrivate17processMouseEventEPN29QWindowSystemInterfacePrivate10MouseEventE (libQt5Gui.so.5)
                #32 0x00007f5981499c7b _ZN22QGuiApplicationPrivate24processWindowSystemEventEPN29QWindowSystemInterfacePrivate17WindowSystemEventE (libQt5Gui.so.5)
                #33 0x00007f598147412b _ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Gui.so.5)
                #34 0x00007f5953f3e8ce n/a (libQt5XcbQpa.so.5)
                #35 0x00007f5979cb9edd g_main_context_dispatch (libglib-2.0.so.0)
                #36 0x00007f5979cba270 n/a (libglib-2.0.so.0)
                #37 0x00007f5979cba313 g_main_context_iteration (libglib-2.0.so.0)
                #38 0x00007f59811183f5 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                #39 0x00007f59810c22bb _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                #40 0x00007f59810c9fd6 _ZN16QCoreApplication4execEv (libQt5Core.so.5)
                #41 0x000056108a2cfe61 main (qgis)
                #42 0x00007f5980aa9f33 __libc_start_main (libc.so.6)
                #43 0x000056108a2d27be _start (qgis)
                
                Stack trace of thread 4152:
                #0  0x00007f597a5764d5 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00007f5980d366d0 _ZNSt18condition_variable4waitERSt11unique_lockISt5mutexE (libstdc++.so.6)
                #2  0x00007f597e036bd1 n/a (libQt5WebKit.so.5)
                #3  0x00007f597e036d0f n/a (libQt5WebKit.so.5)
                #4  0x00007f5980d3c474 n/a (libstdc++.so.6)
                #5  0x00007f597a5705a2 start_thread (libpthread.so.0)
                #6  0x00007f5980b81303 __clone (libc.so.6)
                
                Stack trace of thread 4213:
                #0  0x00007f5980b7bfad syscall (libc.so.6)
                #1  0x00007f5980f1ecb8 n/a (libQt5Core.so.5)
                #2  0x00007f597b0d57c7 n/a (libQt53DCore.so.5)
                #3  0x00007f5980f1fdab n/a (libQt5Core.so.5)
                #4  0x00007f5980f1c7c6 n/a (libQt5Core.so.5)
                #5  0x00007f597a5705a2 start_thread (libpthread.so.0)
                #6  0x00007f5980b81303 __clone (libc.so.6)
                
                Stack trace of thread 4157:
                #0  0x00007f5980b765c7 __poll (libc.so.6)
                #1  0x00007f5979cba1de n/a (libglib-2.0.so.0)
                #2  0x00007f5979cba313 g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007f59811183f5 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                #4  0x00007f59810c22bb _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                #5  0x00007f5980f1b675 _ZN7QThread4execEv (libQt5Core.so.5)
                #6  0x00007f5974be3f4a n/a (libQt5DBus.so.5)
                #7  0x00007f5980f1c7c6 n/a (libQt5Core.so.5)
                #8  0x00007f597a5705a2 start_thread (libpthread.so.0)
                #9  0x00007f5980b81303 __clone (libc.so.6)
                
                Stack trace of thread 4154:
                #0  0x00007f5980b765c7 __poll (libc.so.6)
                #1  0x00007f5979cba1de n/a (libglib-2.0.so.0)
                #2  0x00007f5979cba313 g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007f5979cba361 n/a (libglib-2.0.so.0)
                #4  0x00007f5979ce34e2 n/a (libglib-2.0.so.0)
                #5  0x00007f597a5705a2 start_thread (libpthread.so.0)
                #6  0x00007f5980b81303 __clone (libc.so.6)
                
                Stack trace of thread 4168:
                #0  0x00007f5980b765c7 __poll (libc.so.6)
                #1  0x00007f5979cba1de n/a (libglib-2.0.so.0)
                #2  0x00007f5979cba313 g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007f59811183f5 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                #4  0x00007f59810c22bb _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                #5  0x00007f5980f1b675 _ZN7QThread4execEv (libQt5Core.so.5)
                #6  0x00007f5980f1c7c6 n/a (libQt5Core.so.5)
                #7  0x00007f597a5705a2 start_thread (libpthread.so.0)
                #8  0x00007f5980b81303 __clone (libc.so.6)
                
                Stack trace of thread 4164:
                #0  0x00007f5980b765c7 __poll (libc.so.6)
                #1  0x00007f5979cba1de n/a (libglib-2.0.so.0)
                #2  0x00007f5979cba313 g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007f59811183f5 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                #4  0x00007f59810c22bb _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                #5  0x00007f5980f1b675 _ZN7QThread4execEv (libQt5Core.so.5)
                #6  0x00007f5980f1c7c6 n/a (libQt5Core.so.5)
                #7  0x00007f597a5705a2 start_thread (libpthread.so.0)
                #8  0x00007f5980b81303 __clone (libc.so.6)
                
                Stack trace of thread 4214:
                #0  0x00007f597a5764d5 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00007f5980f222c3 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt5Core.so.5)
                #2  0x00007f5980f22351 _ZN14QWaitCondition4waitEP6QMutexm (libQt5Core.so.5)
                #3  0x00007f5980f1ffb3 n/a (libQt5Core.so.5)
                #4  0x00007f5980f1c7c6 n/a (libQt5Core.so.5)
                #5  0x00007f597a5705a2 start_thread (libpthread.so.0)
                #6  0x00007f5980b81303 __clone (libc.so.6)
                
                Stack trace of thread 4211:
                #0  0x00007f597a5764d5 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00007f5980f222c3 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt5Core.so.5)
                #2  0x00007f5980f22351 _ZN14QWaitCondition4waitEP6QMutexm (libQt5Core.so.5)
                #3  0x00007f5980f238f4 _ZN20QFutureInterfaceBase15waitForFinishedEv (libQt5Core.so.5)
                #4  0x00007f597b0d4c00 _ZN8Qt3DCore17QAspectJobManager14waitForAllJobsEv (libQt53DCore.so.5)
                #5  0x00007f597b0c13fb n/a (libQt53DCore.so.5)
                #6  0x00007f597b0d06fd _ZN8Qt3DCore14QAspectManager4execEv (libQt53DCore.so.5)
                #7  0x00007f597b0d153c n/a (libQt53DCore.so.5)
                #8  0x00007f5980f1c7c6 n/a (libQt5Core.so.5)
                #9  0x00007f597a5705a2 start_thread (libpthread.so.0)
                #10 0x00007f5980b81303 __clone (libc.so.6)
                
                Stack trace of thread 4193:
                #0  0x00007f596e6732fe n/a (libgomp.so.1)
                #1  0x00007f596e670918 n/a (libgomp.so.1)
                #2  0x00007f597a5705a2 start_thread (libpthread.so.0)
                #3  0x00007f5980b81303 __clone (libc.so.6)
                
                Stack trace of thread 4153:
                #0  0x00007f5980b765c7 __poll (libc.so.6)
                #1  0x00007f596ea9c38a n/a (libxcb.so.1)
                #2  0x00007f596ea9dffa xcb_wait_for_event (libxcb.so.1)
                #3  0x00007f5953f3d908 n/a (libQt5XcbQpa.so.5)
                #4  0x00007f5980f1c7c6 n/a (libQt5Core.so.5)
                #5  0x00007f597a5705a2 start_thread (libpthread.so.0)
                #6  0x00007f5980b81303 __clone (libc.so.6)
                
                Stack trace of thread 4218:
                #0  0x00007f5980b7bfad syscall (libc.so.6)
                #1  0x00007f5980f1ecb8 n/a (libQt5Core.so.5)
                #2  0x00007f597b2c3cc6 n/a (libQt53DRender.so.5)
                #3  0x00007f5980f1c7c6 n/a (libQt5Core.so.5)
                #4  0x00007f597a5705a2 start_thread (libpthread.so.0)
                #5  0x00007f5980b81303 __clone (libc.so.6)
                
                Stack trace of thread 4158:
                #0  0x00007f597a5764d5 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00007f593a0ee5eb n/a (i965_dri.so)
                #2  0x00007f593a0ee32b n/a (i965_dri.so)
                #3  0x00007f597a5705a2 start_thread (libpthread.so.0)
                #4  0x00007f5980b81303 __clone (libc.so.6)
                
                Stack trace of thread 4217:
                #0  0x00007f5980b7bfad syscall (libc.so.6)
                #1  0x00007f5980f1ecb8 n/a (libQt5Core.so.5)
                #2  0x00007f597b2c7480 _ZN10Qt3DRender6Render8Renderer15isReadyToSubmitEv (libQt53DRender.so.5)
                #3  0x00007f597b2cf13d _ZN10Qt3DRender6Render8Renderer8doRenderEb (libQt53DRender.so.5)
                #4  0x00007f597b2c4a4b _ZN10Qt3DRender6Render8Renderer6renderEv (libQt53DRender.so.5)
                #5  0x00007f597b19fbc3 n/a (libQt53DRender.so.5)
                #6  0x00007f5980f1c7c6 n/a (libQt5Core.so.5)
                #7  0x00007f597a5705a2 start_thread (libpthread.so.0)
                #8  0x00007f5980b81303 __clone (libc.so.6)
                
                Stack trace of thread 4216:
                #0  0x00007f597a5764d5 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00007f5980f222c3 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt5Core.so.5)
                #2  0x00007f5980f22351 _ZN14QWaitCondition4waitEP6QMutexm (libQt5Core.so.5)
                #3  0x00007f5980f1ffb3 n/a (libQt5Core.so.5)
                #4  0x00007f5980f1c7c6 n/a (libQt5Core.so.5)
                #5  0x00007f597a5705a2 start_thread (libpthread.so.0)
                #6  0x00007f5980b81303 __clone (libc.so.6)
                
                Stack trace of thread 4215:
                #0  0x00007f597a5764d5 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00007f5980f222c3 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt5Core.so.5)
                #2  0x00007f5980f22351 _ZN14QWaitCondition4waitEP6QMutexm (libQt5Core.so.5)
                #3  0x00007f5980f1ffb3 n/a (libQt5Core.so.5)
                #4  0x00007f5980f1c7c6 n/a (libQt5Core.so.5)
                #5  0x00007f597a5705a2 start_thread (libpthread.so.0)
                #6  0x00007f5980b81303 __clone (libc.so.6)
                
                Stack trace of thread 4212:
                #0  0x00007f5980b765c7 __poll (libc.so.6)
                #1  0x00007f5979cba1de n/a (libglib-2.0.so.0)
                #2  0x00007f5979cba313 g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007f59811183f5 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                #4  0x00007f59810c22bb _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                #5  0x00007f5980f1b675 _ZN7QThread4execEv (libQt5Core.so.5)
                #6  0x00007f5980f1c7c6 n/a (libQt5Core.so.5)
                #7  0x00007f597a5705a2 start_thread (libpthread.so.0)
                #8  0x00007f5980b81303 __clone (libc.so.6)
                
                Stack trace of thread 4192:
                #0  0x00007f596e6732fe n/a (libgomp.so.1)
                #1  0x00007f596e670918 n/a (libgomp.so.1)
                #2  0x00007f597a5705a2 start_thread (libpthread.so.0)
                #3  0x00007f5980b81303 __clone (libc.so.6)
                
                Stack trace of thread 4191:
                #0  0x00007f596e6732fe n/a (libgomp.so.1)
                #1  0x00007f596e670918 n/a (libgomp.so.1)
                #2  0x00007f597a5705a2 start_thread (libpthread.so.0)
                #3  0x00007f5980b81303 __clone (libc.so.6)
                
                Stack trace of thread 4163:
                #0  0x00007f5980b765c7 __poll (libc.so.6)
                #1  0x00007f5979cba1de n/a (libglib-2.0.so.0)
                #2  0x00007f5979cba313 g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007f59811183f5 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                #4  0x00007f59810c22bb _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                #5  0x00007f597ad19f81 _ZN3QCA10SyncThread3runEv (libqca-qt5.so.2)
                #6  0x00007f5980f1c7c6 n/a (libQt5Core.so.5)
                #7  0x00007f597a5705a2 start_thread (libpthread.so.0)
                #8  0x00007f5980b81303 __clone (libc.so.6)
                
                Stack trace of thread 4156:
                #0  0x00007f5980b765c7 __poll (libc.so.6)
                #1  0x00007f5979cba1de n/a (libglib-2.0.so.0)
                #2  0x00007f5979cba5a3 g_main_loop_run (libglib-2.0.so.0)
                #3  0x00007f5974300d5a n/a (libgio-2.0.so.0)
                #4  0x00007f5979ce34e2 n/a (libglib-2.0.so.0)
                #5  0x00007f597a5705a2 start_thread (libpthread.so.0)
                #6  0x00007f5980b81303 __clone (libc.so.6)
                
                Stack trace of thread 4155:
                #0  0x00007f5980b765c7 __poll (libc.so.6)
                #1  0x00007f5979cba1de n/a (libglib-2.0.so.0)
                #2  0x00007f5979cba313 g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007f596124da9d n/a (libdconfsettings.so)
                #4  0x00007f5979ce34e2 n/a (libglib-2.0.so.0)
                #5  0x00007f597a5705a2 start_thread (libpthread.so.0)
                #6  0x00007f5980b81303 __clone (libc.so.6)

`

**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by gioman** [comment]
@mone27 try with a new/clean QGIS profile, no 4rd party plugins installed.

**Comment by mone27** [comment]
I did some work with a clean profile and this issue seems that it is solved. Thanks
