### ISSUE TITLE
Extract Selected Features doesn't recognize fid when saved in memory

### ISSUE THREAD

**Issue by jsk1360** [qgis/QGIS#30555]
In Processing's 'Extract Selected Features', if the selection is saved as a file, behaviour is fine, for example, the fid is same as the original layer's fid. But if it is saved into memory, the fid field is not recognized as id and new id's are assigned to features when they are called.
QGIS version: 3.4.

**Comment by nyalldawson** [comment]
This is expected - feature IDs aren't a permanent fixed value, and will always vary from data source to data source. For some providers they may use an existing primary key field, for others they are regenerated anew on each layer load.

You'll need to create your own field and prepopulate it with static id values if you need a permanent identifier for features.

**Comment by Gustry** [comment]
I think we need some documentation and/or some warnings about this `fid` field.
Within my organization, I either saw people wondering what was this `fid` field that they didn't ask for and they tried to remove it (QGIS crashed, it was a few weeks ago). Or I saw some people saying: "we already have this primary key called `fid`, we don't need to create another primary key for our database schema." But if `fid` aren't permanent, then people are confusing why it is a primary key.

I'm just reporting feedbacks from some users I know. But I think I'm also confused.
