### ISSUE TITLE
QGIS 3 Crashed by deleting Group of Layers

### ISSUE THREAD

**Issue by FlyingEagle** [qgis/QGIS#30553]
h2. User Feedback

Delete a Group of Layers with Layers in the group.

h2. Report Details

*Crash ID*: c84bc6061242e965dc281c6447de5a8620425be0

*Stack Trace*
<pre>
QList<QItemSelectionRange>::empty :
QUndoStack::canRedo :
QgsUndoWidget::indexChanged :
QMetaObject::activate :
QUndoStack::clear :
QUndoStack::~QUndoStack :
QgsProjectFileTransform::operator= :
QObjectPrivate::deleteChildren :
QObject::~QObject :
QgsVectorLayerProperties::`default constructor closure' :
QgsMapLayerStore::removeMapLayers :
QgsMapLayerStore::removeMapLayers :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.6.3-Noosa
QGIS code revision: commit:0c5774c068
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by gioman** [comment]
> Delete a Group of Layers with Layers in the group.

regardless of the project and data? Tried a new/clean QGIS profile with no 3rd party plugins installed?

**Comment by FlyingEagle** [comment]
Not tried yet, but now my big project will not be opening as fast as usual.

**Comment by gioman** [comment]
> but now my big project will not be opening as fast as usual.

with a new profile?

**Comment by FlyingEagle** [comment]
I tried it with the same profile and project file.
I lost some Layers i added as shape files.
The main Layers are stored in a GPKG and were normal loaded.

It would be nice to have a handy tool to add or min. mark such "external shape layers" to add them to the gpkg.

**Comment by gioman** [comment]
> I tried it with the same profile and project file.
> I lost some Layers i added as shape files.
> The main Layers are stored in a GPKG and were normal loaded.
> 
> It would be nice to have a handy tool to add or min. mark such "external shape layers" to add them to the gpkg.

@FlyingEagle I'm lost, is this related to the subject/description of this ticket? Speaking about it, is the crash 100% replicable regardless of the project/data or it was more a random one?

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
