### ISSUE TITLE
Export DXF all visible layers

### ISSUE THREAD

**Issue by FlyingEagle** [qgis/QGIS#30561]
I do not know if it is a bug or i am do something wrong, but I do not the result i expected.

I have some large layers with a lot of features of a whole city, I now want to export some smaller areas to use it as a plan or something else.

I do need all visible layers in the marked area as DXF with all attributes and so on.

I tried it with exporting every single layer, yes it works (except for the attributes) but it is a hard work to export >50 layer.

after that i tried the project -> export -> dfx export. I selected there "objects that cuts the viewport" [i do not know how it is named in english, second checkbos at bottom].
i got a big DXF, but QGIS and Autodesk Trueview aren't able to load it - i let both more then some hours time to open it, without success I killed the programs by task manager.

**Comment by gioman** [comment]
any chance of sharing a project with data that can we use to replicate the problem?

**Comment by gioman** [comment]
@FlyingEagle is this still relevant? if yes, any chance to attach that can be used to replicate?

**Comment by nyalldawson** [comment]
Closing due to lack of feedback

**Comment by FlyingEagle** [comment]
sorry, no, no chance to share this data :-(
It is still relevant ...
