### ISSUE TITLE
QGIS 3.8 - Crashed

### ISSUE THREAD

**Issue by denilsonjesus** [qgis/QGIS#30571]
Crash ID: b8f27d145e302ca61f1787c1833027edf676c67f

Stack Trace

QBitArray::QBitArray :
QgsProcessingContext::defaultEncoding :
QgsLayoutItemMap::createExpressionContext :
QgsLayoutItem::refreshItemRotation :
QgsLayoutItem::rotateItem :
QgsLayoutItem::setItemRotation :
QgsLayoutItem::readXml :
QgsLayout::addItemsFromXml :
QgsLayout::readXml :
QgsPrintLayout::readXml :
QgsLayoutManager::readXml :
QgsProject::readProjectFile :
QgsProject::read :
QgisApp::addProject :
QgisApp::openProject :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.8.0-Zanzibar
QGIS code revision: 11aff65f10
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment]
@denilsonjesus doing what? is 100% replicable? have you tried with a new QGIS profile and no 3rd party plugins?

**Comment by denilsonjesus** [comment]
hi, I m using 3.4.9 without using plugings.
It crashed only some times, I don't why e not when.
I m preparing maps and I m trying  automation of layout.

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by gioman** [comment]
> It crashed only some times, I don't why e not when.

@denilsonjesus so it is random crashes and not 100% replicable when doing a specific operation eventually on a specif project with specific data?

**Comment by denilsonjesus** [comment]
I. Can t understand why, I tried discover what happened , but we're not possible for me. When this happened, I  get the old version of QGS and start again, so I'm always saving with a new name. In this project I'm using some virtual layers.

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by gioman** [comment]
@denilsonjesus reopen if/when you can provide detailed steps/instructions that demonstrate the issue.
