### ISSUE TITLE
WFS-T and special characters

### ISSUE THREAD

**Issue by zanollim** [qgis/QGIS#30575]
**Describe the bug**
WFS-T does not save (ignores) special characters in editing string attributes

**How to Reproduce**
1. load a WFS layer (in my case UTF-8 encoding)
2. try to change an attribute adding some special characters (e.g "Copiacò")
3. save the edits
4. reload the WFS layer entirely from server
5. open the attribute table and check the attibute previously modified: you will read, in my example, "Copiac"

**QGIS and OS versions**
QGIS 3.x on Linux or Windows

Thanks

**Comment by gioman** [comment]
@zanollim what is the server backend (gepserver? maspserver? qgis server?) and the the underlying datasource (postgis? else?)?

**Comment by zanollim** [comment]
the server backend is qgis server, the old version 2.14, the datasource is postgis

could the issue be maybe related to the qgis server 2.14?
at the moment I can not do a test with a newer version of qgis server

thanks

**Comment by elpaso** [comment]
@zanollim 2.14 is not supported anymore, can you make a test with QGIS Server >= 3.4 ?

**Comment by zanollim** [comment]
I did successfully a test with qgis  3.4
so the bug was related to qgis server 2.14
sorry for the mistake
