### ISSUE TITLE
Qgis crashes when triple-clicking on the Vertex Tool button

### ISSUE THREAD

**Issue by alafr** [qgis/QGIS#30577]
**Describe the bug**
Qgis crashes when triple clicking on the Vertex tool button.

**How to Reproduce**
1. Create new project
2. Add a new temporary polygon layer
3. Triple click on the Vertex tool button
4. The Qgis crashed window appears

**QGIS and OS versions**
Έκδοση QGIS
3.9.0-Master
Επανάληψη κωδικού QGIS 
accbb2d7f1
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
2.4.1
Running against GDAL/OGR
2.4.1
Compiled against GEOS
3.7.2-CAPI-1.11.0
Running against GEOS
3.7.2-CAPI-1.11.0 b55d2125
Έκδοση Πελάτη PostgreSQL 
9.2.4
Έκδοση SpatiaLite
4.3.0
Έκδοση QWT
6.1.3
Έκδοση QScintilla2
2.10.8
Compiled against PROJ
5.2.0
Running against PROJ
Rel. 5.2.0, September 15th, 2018
This copy of QGIS writes debugging output.
OS Version
Windows 10 (10.0)

**Additional context**

Crash ID: c6e2d1924decab0299b1b05113a4109bcc1d5d71

Stack Trace

QWidget::show :
QgsIdentifyResultsDialog::vectorLayer :
QgsIdentifyResultsDialog::vectorLayer :
QgsIdentifyResultsDialog::vectorLayer :
QgsIdentifyResultsDialog::vectorLayer :
QTimer::timeout :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsAuxiliaryLayer::isHiddenProperty :
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32Private::sendTimerEvent :
QEventDispatcherWin32::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsAuxiliaryLayer::isHiddenProperty :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
QgsIdentifyResultsDialog::vectorLayer :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.9.0-Master
QGIS code revision: accbb2d7f1
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.16299

Crash ID: 4629476b9e625e46d57da6dfa51d20ef94b80574

Stack Trace

QWidget::show :
QgisApp::activeLayerChanged :
QgisApp::activeLayerChanged :
QgisApp::activeLayerChanged :
QgisApp::activeLayerChanged :
QTimer::timeout :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsCentroidFillSymbolLayer::operator= :
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32Private::sendTimerEvent :
QEventDispatcherWin32::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsCentroidFillSymbolLayer::operator= :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
QgisApp::activeLayerChanged :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.7.0-Master
QGIS code revision: 840ab03808
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.16299

**Comment by gioman** [comment]
Seen also on master/linux.

**Comment by nirvn** [comment]
@alafr , thanks for your report. The crasher has been fixed and will be made available in upcoming LTR 3.4.10 as well as 3.8.1 upon release on July 19th.

**Comment by alafr** [comment]
@nirvn, thanks for fixing the bug!
