### ISSUE TITLE
Crash report: crash to desktop on closing the application (QGIS 3.8)

### ISSUE THREAD

**Issue by andreas-paul** [qgis/QGIS#30570]
## User Feedback

I closed the application 

## Report Details

*Crash ID*: 7442373e0283e1ddab9b4be290841057a580a7ea

*Stack Trace*
<pre>
proj_lpz_dist :
proj_lpz_dist :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::~QgsCoordinateTransform :
QgsPointLocator::~QgsPointLocator :
QgsPointLocator::~QgsPointLocator :
QgsSnappingUtils::clearAllLocators :
QgsSnappingUtils::~QgsSnappingUtils :
QgsVectorLayerProperties::`default constructor closure' :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
CPLStringList::operator[] :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.8.0-Zanzibar
QGIS code revision: 11aff65f10
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by nyalldawson** [comment]
This one is already fixed in 3.8.1
