### ISSUE TITLE
QGIS crash after theme change

### ISSUE THREAD

**Issue by Napoleongl** [qgis/QGIS#30579]
**Describe the bug**
QGIS crash after showing splash screen following theme change

**How to Reproduce**
Change theme to Night Mapping

**QGIS and OS versions**
QGIS 3.8
Linux Mint 19.1

**Additional context**

I think I just ran into this issue again and I'm on QGIS 3.8 on LinuxMint 19.1.
I can't guarantee it was that specific theme but I tried out the various ones and apparently I selected one that crashes QGIS after showing the splash about "QGIS ready" (don't know the english text because I run the Swedish translation).

I get the follow in in the console when starting from there:
gustav@GREED ~ $ qgis
QGIS died on signal 11Could not attach to process.  If your uid matches the uid of the target
process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
ptrace: Operation not permitted.
No thread selected
No stack.
gdb returned 0
Aborted

**Comment by Napoleongl** [comment]
Should prehaps note that renaming the folder containing the default profile under /.local/share/QGIS/QGIS3/profiles and restarting QGIS lets me get back into the program. Naturally with all settings lost, but since reinstall did not resolve the issue it's better than nothing!

**Comment by nirvn** [comment]
@Napoleongl , are you still suffering from this issue? I suspect the problem wasn't with night mapping, but with a non-Fusion _Qt_ style. If you set the style to vision and theme to night mapping, it should not crash. Can you confirm this is the case?

**Comment by Napoleongl** [comment]
@nirvn I can no longer reproduce it using QGIS 3.8.1. I don't have a style named Vision though.
