### ISSUE TITLE
grass toolbar doesn't work

### ISSUE THREAD

**Issue by salvanet76** [qgis/QGIS#30574]
Hi, I use QGIS 3.8.0 with Grass 7.6.1, but grass toolbar doesn't work properly.
In QGIS not all keys are displayed in the Grass menu bar and when I click "open grass tools", the tools are not displayed

**Comment by gioman** [comment]
@salvanet76 you first need to open a location/mapset, did you do it?

**Comment by salvanet76** [comment]
@gioman yes I did it

**Comment by gioman** [comment]
@salvanet76 please list the exact steps you are following (aka, here it works).

**Comment by salvanet76** [comment]
@gioman plugins>GRASS > open mapset  and I select a dataset downloaded from https://grass.osgeo.org/download/sample-data/

**Comment by gioman** [comment]
> @gioman plugins>GRASS > open mapset and I select a dataset downloaded from https://grass.osgeo.org/download/sample-data/

@salvanet76 still works fine here on Kubuntu 18.04 and QGIS installed from repositories.

**Comment by salvanet76** [comment]
@gioman ![2019-07-10](https://user-images.githubusercontent.com/52594004/60952431-91e97d00-a2fb-11e9-8c9b-c2219268ef64.png)

**Comment by gioman** [comment]
@salvanet76 I don't understand what you are pointing to in the screenshot. The GRASS toolbar is now as it shows since a long time. The button on the left does exactly what you have also in your screenshot, it opens the GRASS panel. The GRASS data is now accessible only using the QGIS browser.

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
