### ISSUE TITLE
Export Attribute Table by Copy&Paste with multiline

### ISSUE THREAD

**Issue by bru500** [qgis/QGIS#30580]
**Describe the bug**
If I copy a whole attribute table with multiline textfields (with linebreaks in them) by copy&paste to Libre Office Calc or MS Excel, the lines of the attribute table get messed up, because each linebreak in a multiline text field leads to a new line in the pasted table. This is especially annoying when one has to export a large attribute table with multiline fields to a spreadsheet.

attribute table in QGIS:
![qgis](https://user-images.githubusercontent.com/40229231/60760748-ef02db80-a03a-11e9-9cdf-bf08f7267677.PNG)

attribute table in calc:
![calc](https://user-images.githubusercontent.com/40229231/60760747-ee6a4500-a03a-11e9-9bd5-d34b85024546.PNG)
The seccond line "zweite Zeile" of the field "Bemerkungen" is on a new line in calc. It should be in the same cell as "eine Zeile". The "3" of the field "Nummer" is placed in the wrong column aswell .

**How to Reproduce**
Use test data or:
1. Create an attribute table with a multiline textfield and an other field
2. Enter some data, with multiline text (must contain line breaks)
3. copy whole attribute table with ctrl-a andt ctrl-c
4. open calc or excel
5. paste with ctrl-v
Test data:
[Test_issues_attribute_table.zip](https://github.com/qgis/QGIS/files/3364994/Test_issues_attribute_table.zip)

**QGIS and OS versions**
Tested with QGIS 3.6  and 3.8 on Windows 10

QGIS-Version | 3.8.0-Zanzibar | QGIS-Codeversion | 11aff65f10
-- | -- | -- | --
Kompiliert gegen Qt | 5.11.2 | Laufendes Qt | 5.11.2
Kompiliert mit GDAL/OGR | 2.4.1 | Läuft mit GDAL/OGR | 2.4.1
Kompiliert mit GEOS | 3.7.2-CAPI-1.11.0 | Läuft mit GEOS | 3.7.2-CAPI-1.11.0 b55d2125
PostgreSQL-Client-Version | 9.2.4 | SpatiaLite-Version | 4.3.0
QWT-Version | 6.1.3 | QScintilla2-Version | 2.10.8
Kompiliert mit PROJ | 5.2.0 | Läuft mit PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Windows 10 (10.0) |   |

**Comment by stev-0** [comment]
I'm not sure that the clipboard can be customised to the extent of quoting strings, but I might have a look. In the meantime, and easy workaround is to save as CSV, specifying GEOMETRY as AS_WKT and STRING_QUOTING as ALWAYS in the layer options dialog.

**Comment by nyalldawson** [comment]
@stev-0 the approach used in https://github.com/qgis/QGIS/commit/f63d5ad9acb3d6a8317a20743f937f773bbcf1b1 may work (setting clipboard html data as a table)

**Comment by bru500** [comment]
@stev-0 thank you for the workaround. I would appreciate a lot if you'd have a look at it. Copy&paste is nice and quick and the first way of a lot of folks.

**Comment by bru500** [comment]
Many thanks. You guys are great!
I wish ESRI had ever responded to a problem, at least after many years. 
Well, I don't really care now :-)
