### ISSUE TITLE
Using a gml file, only one label is shown in the canvas extent

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#30583]
Open the attached gml file in QGIS (epsg: 2964)
Enable labeling using "NAMES" field
Afaics, regardless the scale I'm at, I only get the label for one feature in the extent I have. The others don't show.

[lakes.zip](https://github.com/qgis/QGIS/files/3365172/lakes.zip)

**Comment by nirvn** [comment]
@DelazJ , this gml is probably not valid. All features have the same feature ID (i.e. F0).

**Comment by DelazJ** [comment]
OK. Thanks @nirvn I downloaded the data again and I could label the features.
