### ISSUE TITLE
The CRS selector dialog pops up twice when adding a gml file 

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#30582]
Using the Data source manager dialog > Browser, load the attached gml file (lakes.gml file from qgis sample data)
You should get the CRS dialog selector to indicate the data crs (it's in epsg: 2964)
Select the crs to use and you get the dialog a second time. Nothing seems to be different between the two dialogs and once you add the layer, you have a single layer in the layers panel so I wonder why you have to select the crs twice.
[lakes.zip](https://github.com/qgis/QGIS/files/3365165/lakes.zip)

Using master on Bionic

**Comment by alexbruy** [comment]
Not reproducible on master (probably due to recent switch to Proj 6)

**Comment by alexbruy** [comment]
Closed for the lack of feedback. Please reopen if necessary.

**Comment by DelazJ** [comment]
Sorry for the lack of feedback. I could not reproduce neither, and seems that there's no crs associated to the data I uploaded (afair, these are data from the QGIS sample dataset). generating it with a crs (4326) does prompt nothing.

**Comment by alexbruy** [comment]
At least it is gone :-). If it will come back, please reopen of file another ticket.
