### ISSUE TITLE
std::bad_alloc crash when loading raster GeoPackage

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#30590]
**Describe the bug**

If launched in the terminal with a specific GeoPackage as argument, QGIS will terminate. If launched already and the GeoPackage is added via drag and drop, QGIS will display an `Exception` `std::bad_alloc` dialog but load the layer and work fine.

Relevant part of output when launched from the terminal:
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```

**How to Reproduce**

1. Download https://www.datenatlas.de/geodata/public/hamburg/DOP20_HH_sommerbefliegung_2013.gpkg (sorry, it is 6 Gigabytes... I could not reproduce it with sample data from geopackage.org)
2. Load the file in QGIS in the GUI
3. You will get an Exception dialog but QGIS will continue working

2a. Launch QGIS and pass the filename to be loaded: `qgis DOP20_HH_sommerbefliegung_2013.gpkg`
3a. QGIS will terminate before showing its GUI.

**QGIS and OS versions**

QGIS version | 3.8.0-Zanzibar | QGIS code branch | Release 3.8
-- | -- | -- | --
Compiled against Qt | 5.13.0 | Running against Qt | 5.13.0
Compiled against GDAL/OGR | 3.0.0 | Running against GDAL/OGR | 3.0.0
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
PostgreSQL Client Version | 11.4 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 6.1.0 | Running against PROJ | Rel. 6.1.0, May 15th, 2019
OS Version | Arch Linux |   |

**Comment by elpaso** [comment]
File opens from QGIS GUI with non errors on master here.

I crashes when passing the gpkg path to the command line though, mdal is trying to open it and it crashes.

**Comment by kannes** [comment]
You guys are awesome, thanks!
