### ISSUE TITLE
Win7 with Roaming App Data and Profile Redirection - [ERROR] Can not make qgis.db private copy

### ISSUE THREAD

**Issue by Anumann** [qgis/QGIS#30619]
Starting software gives "[ERROR] Can not make qgis.db private copy" for users with redirected App Data.

I wonder if perhaps QGIS is unable to resolve a UNC path when expecting a local app data location (in this case \\servername\dfsr\Members\Redirection\franklinwaits\AppData\Roaming rather than C:\Users\franklinwaits\AppData\Roaming).

**Comment by gioman** [comment]
@Anumann what is the status of this ticket also considering that Win 7 is no more supported?
