### ISSUE TITLE
Save Textfile in DB Manager

### ISSUE THREAD

**Issue by B17DtJ** [qgis/QGIS#30616]
In the SQL Window of the DB Manager, if text is highlighted, which is often the case when executing sql queries, only the highlighted text is saved to a file. This is dangerous, as it may cause overwriting whole scripts as happened to me. I lost days of work. Please change that behavior or give me hint how I can change it.
Thanks
Brian

QGIS Version 3.6.3

**Comment by stev-0** [comment]
This isn't very helpful - please submit a proper bug report with a full description

**Comment by B17DtJ** [comment]
In the SQL Window of the DB Manager, if text is highlighted, which is often the case when executing sql queries, only the highlighted text is saved to a file. This is dangerous, as it may cause overwriting whole scripts as happened to me. I lost days of work. Please change that behavior or give me hint how I can change it.  
Thanks 
Brian

QGIS Version 3.6.3
