### ISSUE TITLE
Crash Window Remains

### ISSUE THREAD

**Issue by PlayItAll** [qgis/QGIS#30613]
Checklist before submitting

- [ x] Search through existing issue reports and gis.stackexchange.com to check whether the issue already exists
- [NA] Test with a [clean new user profile](https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html?highlight=profile#working-with-user-profiles).
- [ NA] Create a light and self-contained sample dataset and project file which demonstrates the issue

**Describe the bug**
After de-installation and re-installation of Madeira 3.4.2 and rebooting the program starts with the info-window "No data provider"
Could not find QGIs data provider:
Cannot load vector layers. Check QGIS installation.

After pressing "Close", the "QGIS Crashed" window appears. A copy of the report is below.

It is not possible to launch QGIS in any other way.

**How to Reproduce**
NA

**QGIS and OS versions**
See copy of report below.

**Additional context**

h2. User Feedback

I was building and running a python script when QGIS crashed. Even after de-installation and reboot of the OS, I cannot restart QGIS. It always routs me back to the "QGIS Crashed" window.

h2. Report Details

*Crash ID*: 2b989aab4b58061da7a6ad9661b5d20aef9c0c1b

*Stack Trace*
<pre>
QgsProjectMetadata::writeMetadataXml :
QgsAuthManager::trustedCaCertsCache :
QgsNetworkAccessManager::createRequest :
QNetworkAccessManager::get :
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyTuple_New :
PyObject_FastCallKeywords :
PyObject_FastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyEval_EvalCodeEx :
PyEval_EvalCode :
PyArena_Free :
PyRun_StringFlags :
instance :
instance :
QgisApp::rotatePointSymbols :
QgsPythonRunner::run :
QgisApp::QgisApp :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.4.2-Madeira
QGIS code revision: commit:22034aa070
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.3.2
Running against GDAL: 2.3.2

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by elpaso** [comment]
The stacktrace clearly indicates that the crash comes from Python:  start with a clean new user profile.

**Comment by PlayItAll** [comment]
Hi elpaso, I actually deleted the folder C:\Program Files\QGIS 3.4 and started over.
I still get the same QGIS Crashed window with error messages not related to Python:
h2. User Feedback

  

h2. Report Details

*Crash ID*: b181534feb234a2bc0ed6cfda5800fa7977347e3


*Stack Trace*
<pre>
QObjectPrivate::addConnection :
QObjectPrivate::connectImpl :
QObject::connectImpl :
QgisApp::setupConnections :
QgisApp::QgisApp :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>


*QGIS Info*
QGIS Version: 3.4.2-Madeira
QGIS code revision: commit:22034aa070
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.3.2
Running against GDAL: 2.3.2



*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by PlayItAll** [comment]
Since I cannot open QGIS, how can I create a clean new user profile?

**Comment by andreasneumann** [comment]
@PlayItAll - reinstalling does not help here, because the user settings (profile) is stored completely seperate from the software itself.

Please consult https://docs.qgis.org/3.4/en/docs/user_manual/introduction/qgis_configuration.html?highlight=profile#working-with-user-profiles to find out where your user profile resides and remove that configuration (make sure you don't loose existing settings). If unsure, create a backup first.

**Comment by elpaso** [comment]
> Hi elpaso, I actually deleted the folder C:\Program Files\QGIS 3.4 and started over.
> I still get the same QGIS Crashed window with error messages not related to Python:
> h2. User Feedback
> 
> h2. Report Details
> 
> _Crash ID_: b181534feb234a2bc0ed6cfda5800fa7977347e3
> 
> _Stack Trace_
> 
> QObjectPrivate::addConnection :
> QObjectPrivate::connectImpl :
> QObject::connectImpl :
> QgisApp::setupConnections :
> QgisApp::QgisApp :
> main :
> BaseThreadInitThunk :
> RtlUserThreadStart :
> 
> _QGIS Info_
> QGIS Version: 3.4.2-Madeira
> QGIS code revision: commit:22034aa070
> Compiled against Qt: 5.11.2
> Running against Qt: 5.11.2
> Compiled against GDAL: 2.3.2
> Running against GDAL: 2.3.2
> 
> _System Info_
> CPU Type: x86_64
> Kernel Type: winnt
> Kernel Version: 6.1.7601

This looks completely different, unfortunately the new stacktrace does not contain any useful information. I can only guess that there is something seriously broken in your installation.

Do you by chance have any possible conflicting Qt5 library installed or any previous QGIS installation leftover?

**Comment by PlayItAll** [comment]
> 
> 
> @PlayItAll - reinstalling does not help here, because the user settings (profile) is stored completely seperate from the software itself.
> 
> Please consult https://docs.qgis.org/3.4/en/docs/user_manual/introduction/qgis_configuration.html?highlight=profile#working-with-user-profiles to find out where your user profile resides and remove that configuration (make sure you don't loose existing settings). If unsure, create a backup first.
> 
> Removing your default profile automatically creates a new virgin profile at the next start of QGIS. No need to remove and reinstall QGIS.

Thank you Andreas, removing the default value resolved the problem :)
