### ISSUE TITLE
Strange Behavior with Layer Filter Expressions

### ISSUE THREAD

**Issue by briangmaddox** [qgis/QGIS#30623]
**Describe the bug**
I'm noticing an odd issue with the Layer Filter Expression tool in QGIS 3.8 on Ubuntu, both with the "normal" and the ubuntugis-unstable releases.  Sometimes it will work and sometimes it acts as if I didn't type anything at all even though it's a valid expression.  

So far, the only common thing I can come across is how the column is defined in Postgresql.  For example, with a geonames db in postgis defined as so:
```
     Column     |          Type          | Modifiers 
----------------+------------------------+-----------
 geonameid      | bigint                 | 
 name           | character varying(200) | 
 asciiname      | character varying(200) | 
```

a filter expression of _"name" = 'Rolla'_ works.  Test returns the correct number of rows and if I add the layer it is indeed filtered.  Note that _name_ is defined as _character varying(200)_ here.

However, for a table like this:
```
  Column  |         Type         |                            Modifiers                             
----------+----------------------+------------------------------------------------------------------
 id       | integer              | not null default nextval('osm_man_made_points_id_seq'::regclass)
 osm_id   | bigint               | 
 name     | character varying    | 
 type     | character varying    | 
 tags     | hstore               | 
```
a filter expression of _"type" = 'tower'_ does not work.  Test returns a count of all columns in the table and adding the layer does indeed have everything there without the filter.  The _type_ column here is just _character varying_ without an upper bound.  It was created using imposm3's string type.

The column types are the only thing that I've come across so far that seem consistent between various Postgis tables I've tried.

**How to Reproduce**

1. Click Add Layer -> Add PostGIS layers.
2. Connect to a data source.
3. Double click a layer name or click once and click the "Set Filter" button.
4. Add a provider specific filter expression using either using the GUI or directly typing it in.
5. Click the test button or click ok and then click add on the layer.

**QGIS and OS versions**

QGIS version | 3.8.0-Zanzibar | QGIS code revision | 11aff65
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.4.0 | Running against GDAL/OGR | 2.4.0
Compiled against GEOS | 3.7.0-CAPI-1.11.0 | Running against GEOS | 3.7.0-CAPI-1.11.0 673b9939
PostgreSQL Client Version | 10.9 (Ubuntu 10.9-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Linux Mint 19.1 |   |  

Note I have the same experience with the "normal" version of QGIS for Debian/Ubuntu.  I upgraded to ubuntugis to see if it had the same behavior in case it was something with the older gdal that comes with Ubuntu Bionic.

**Comment by elpaso** [comment]
Can you please share a DB dump and a sample project?

**Comment by briangmaddox** [comment]
Sure!  Let me create an extract and I’ll post it.

**Comment by briangmaddox** [comment]
So if I dump osm_man_made_points and restore it to a new DB, qgis works properly.  Let me see if I can generate a backup where the behavior still exists since I'd imagine the entire OSM backup would be several gigabytes.

**Comment by briangmaddox** [comment]
OK so I have an extract but it's around 25 gig.  Let me run imposm3 on a smaller area and then do an extract of it.

**Comment by briangmaddox** [comment]
OK so I've put a OSM dump where I can recreate the problem at https://drive.google.com/open?id=1XJxz2qLj_eYFPlMeRISv774-lYByX6fh.  It's an extract of Algeria that was imported using imposm3.  Here are the database stats:
```
algeria1=# select count(*) from osm_man_made_polygons;
 count
-------
  3086
(1 row)

algeria1=# select count(*) from osm_man_made_polygons where type = 'bridge';
 count
-------
    28
(1 row)
```

I also noticed this is happening as I was trying to track it down.  So here's a screenshot of me adding the filter to osm_man_made_polygons:
![Screenshot from 2019-07-11 10-45-21](https://user-images.githubusercontent.com/16601522/61060817-24a41d80-a3c9-11e9-997a-54b201b8b65f.png)

But after clicking OK, note that it's actually set on the table above the one I selected, which looks to be a duplicate except that it needs the spatial type specified.

![Screenshot from 2019-07-11 10-48-20](https://user-images.githubusercontent.com/16601522/61060973-6b921300-a3c9-11e9-9a98-31bcedd97d96.png)

I know you have the db dump, but here's also the list of tables for reference:
```
                    List of relations
 Schema |             Name              | Type  |  Owner
--------+-------------------------------+-------+---------
 public | osm_aerialway_lines           | table | bmaddox
 public | osm_aerialway_points          | table | bmaddox
 public | osm_aerialway_polygons        | table | bmaddox
 public | osm_aeroway_lines             | table | bmaddox
 public | osm_aeroway_points            | table | bmaddox
 public | osm_aeroway_polygons          | table | bmaddox
 public | osm_amenity_lines             | table | bmaddox
 public | osm_amenity_points            | table | bmaddox
 public | osm_amenity_polygons          | table | bmaddox
 public | osm_barrier_lines             | table | bmaddox
 public | osm_barrier_points            | table | bmaddox
 public | osm_barrier_polygons          | table | bmaddox
 public | osm_boundary_lines            | table | bmaddox
 public | osm_boundary_points           | table | bmaddox
 public | osm_boundary_polygons         | table | bmaddox
 public | osm_building_lines            | table | bmaddox
 public | osm_building_points           | table | bmaddox
 public | osm_building_polygons         | table | bmaddox
 public | osm_craft_lines               | table | bmaddox
 public | osm_craft_points              | table | bmaddox
 public | osm_craft_polygons            | table | bmaddox
 public | osm_emergency_lines           | table | bmaddox
 public | osm_emergency_points          | table | bmaddox
 public | osm_emergency_polygons        | table | bmaddox
 public | osm_geological_lines          | table | bmaddox
 public | osm_geological_points         | table | bmaddox
 public | osm_geological_polygons       | table | bmaddox
 public | osm_highway_lines             | table | bmaddox
 public | osm_highway_points            | table | bmaddox
 public | osm_highway_polygons          | table | bmaddox
 public | osm_historic_lines            | table | bmaddox
 public | osm_historic_points           | table | bmaddox
 public | osm_historic_polygons         | table | bmaddox
 public | osm_landuse_lines             | table | bmaddox
 public | osm_landuse_points            | table | bmaddox
 public | osm_landuse_polygons          | table | bmaddox
 public | osm_leisure_lines             | table | bmaddox
 public | osm_leisure_points            | table | bmaddox
 public | osm_leisure_polygons          | table | bmaddox
 public | osm_man_made_lines            | table | bmaddox
 public | osm_man_made_points           | table | bmaddox
 public | osm_man_made_polygons         | table | bmaddox
 public | osm_military_lines            | table | bmaddox
 public | osm_military_points           | table | bmaddox
 public | osm_military_polygons         | table | bmaddox
 public | osm_natural_lines             | table | bmaddox
 public | osm_natural_points            | table | bmaddox
 public | osm_natural_polygons          | table | bmaddox
 public | osm_office_lines              | table | bmaddox
 public | osm_office_points             | table | bmaddox
 public | osm_office_polygons           | table | bmaddox
 public | osm_place_lines               | table | bmaddox
 public | osm_place_points              | table | bmaddox
 public | osm_place_polygons            | table | bmaddox
 public | osm_power_lines               | table | bmaddox
 public | osm_power_points              | table | bmaddox
 public | osm_power_polygons            | table | bmaddox
 public | osm_public_transport_lines    | table | bmaddox
 public | osm_public_transport_points   | table | bmaddox
 public | osm_public_transport_polygons | table | bmaddox
 public | osm_railway_lines             | table | bmaddox
 public | osm_railway_points            | table | bmaddox
 public | osm_railway_polygons          | table | bmaddox
 public | osm_route_lines               | table | bmaddox
 public | osm_route_points              | table | bmaddox
 public | osm_route_polygons            | table | bmaddox
 public | osm_shop_lines                | table | bmaddox
 public | osm_shop_points               | table | bmaddox
 public | osm_shop_polygons             | table | bmaddox
 public | osm_sport_lines               | table | bmaddox
 public | osm_sport_points              | table | bmaddox
 public | osm_sport_polygons            | table | bmaddox
 public | osm_tourism_lines             | table | bmaddox
 public | osm_tourism_points            | table | bmaddox
 public | osm_tourism_polygons          | table | bmaddox
 public | osm_waterway_lines            | table | bmaddox
 public | osm_waterway_points           | table | bmaddox
 public | osm_waterway_polygons         | table | bmaddox
 public | spatial_ref_sys               | table | bmaddox
(79 rows)
```

And the table description:
```
algeria1=# \d osm_man_made_polygons;
                                  Table "public.osm_man_made_polygons"
  Column  |          Type           |                             Modifiers
----------+-------------------------+--------------------------------------------------------------------
 id       | integer                 | not null default nextval('osm_man_made_polygons_id_seq'::regclass)
 osm_id   | bigint                  | not null
 name     | character varying       |
 type     | character varying       |
 tags     | hstore                  |
 geometry | geometry(Geometry,3857) |
Indexes:
    "osm_man_made_polygons_pkey" PRIMARY KEY, btree (osm_id, id)
    "osm_man_made_polygons_geom" gist (geometry)
```

**Comment by gioman** [comment]
> OK so I've put a OSM dump where I can recreate the problem at https://drive.google.com/open?id=1XJxz2qLj_eYFPlMeRISv774-lYByX6fh. It's an extract of Algeria that was imported using imposm3.

@briangmaddox can you please re-attach/link the dump? thanks.
