### ISSUE TITLE
QGIS sends bug reports to old website

### ISSUE THREAD

**Issue by Komzpa** [qgis/QGIS#30622]
QGIS crash handler invites me to send reports to issues.qgis.org instead of github.
![image](https://user-images.githubusercontent.com/810638/60834335-2ef7c900-a1c9-11e9-84b4-da67eae571aa.png)

**Comment by gioman** [comment]
@Komzpa 3.6 is "old", try 3.8 or the latest point release of 3.4 LTR.

**Comment by nyalldawson** [comment]
This is already fixed
