### ISSUE TITLE
Not possible to toggle use selected features in the Processing layer combobox

### ISSUE THREAD

**Issue by NyakudyaA** [qgis/QGIS#30636]
**Describe the bug**
I am trying to import a selected features  into a PostgreSQL database but I am unable to toggle the selected features button.

If I reselect the layer in the processing dialog then the selected features become active

**How to Reproduce**

1. Load a vector layer (I used a spatialite layer)
2. Select a random feature or features
3. Activate processing and select the alg Export to PostgreSQL
4. Notice that the `Selected Features Only` is greyed out.
5. Click on the layer again and it becomes active and I get the following error
```
2019-07-09T11:06:20     WARNING    Traceback (most recent call last):
              File "/usr/share/qgis/python/plugins/processing/gui/wrappers.py", line 1544, in parentValueChanged
              if value in self.parent_file_based_layers:
             TypeError: unhashable type: 'QgsProcessingFeatureSourceDefinition'
```

![save](https://user-images.githubusercontent.com/2510900/60874651-a4e74900-a238-11e9-818d-c93573f2bd1e.gif)

**QGIS and OS versions**

![update](https://user-images.githubusercontent.com/2510900/60874954-335bca80-a239-11e9-83c8-4299dbd16cdd.png)

**Additional context**

**Comment by alexbruy** [comment]
Affects all algorithms with input feature sources
