### ISSUE TITLE
QGIS 3.8 "bad allocation" exception when using XYZ tile at resolution "High (512x512 / 192 DPI)"

### ISSUE THREAD

**Issue by kunthet** [qgis/QGIS#30634]
**How to Reproduce**
1. Create new XYZ connection. In Tile Resolution, select "High (512x512 / 192 DPI)". (attachment: Fig1)
2. Add the created xyz connection to QGIS
3. Try to zoom in/out to load more tiles
4. from here... QGIS loads tiles slower and slower and start freezing. 
5. wait for around 1 minute... then an exception message box appears: "bad allocation". (attachment Fig2)

**QGIS and OS versions**

QGIS version
3.8.0-Zanzibar
QGIS code revision
11aff65f10
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
2.4.1
Running against GDAL/OGR
2.4.1
Compiled against GEOS
3.7.2-CAPI-1.11.0
Running against GEOS
3.7.2-CAPI-1.11.0 b55d2125
PostgreSQL Client Version
9.2.4
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
5.2.0
Running against PROJ
Rel. 5.2.0, September 15th, 2018
OS Version
Windows 10 (10.0)

![Fig1 - TileResolution](https://user-images.githubusercontent.com/4720921/60858155-6a30e100-a237-11e9-9dd7-8f68a36d52c0.jpg)
![Fig2 - bad allocation](https://user-images.githubusercontent.com/4720921/60858158-6ac97780-a237-11e9-9cd1-60cb0df9cc05.jpg)

**Comment by gioman** [comment]
@kunthet a URL we can test? the one in the screenshot do not show anything.

**Comment by kunthet** [comment]
> @kunthet a URL we can test? the one in the screenshot do not show anything.

You may test using any available sources. or from Open Street Map: 
`http://a.tile.openstreetmap.org/{z}/{x}/{y}.png`

**Comment by nirvn** [comment]
Confirmed on linux too, if fact the tile rendering fails altogether. Gentle ping to @wonder-sk , who coded the dpi stuff.

Steps to reproduce:
1. Use the above-provided XYZ URL, save it in the browser and set the dpi to 512 x 512
2. Load the layer onto a new project, fails
3. Open the layer properties dialog for that layer, you'll get a std::malloc error
