### ISSUE TITLE
Memory issue/crash with raster GeoPackage

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#30645]
**Describe the bug**
QGIS eats memory until it freezes my whole system when loading this GeoPackage (a result of https://github.com/qgis/QGIS/issues/30644 using "Rendered image").

**How to Reproduce**

0. Save your work, sync your drives
1. Load rendered.gpkg from [rendered.gpkg.zip](https://github.com/qgis/QGIS/files/3373109/rendered.gpkg.zip)
2. QGIS will eat all memory

**QGIS and OS versions**

QGIS version | 3.8.0-Zanzibar | QGIS code branch | Release 3.8
-- | -- | -- | --
Compiled against Qt | 5.13.0 | Running against Qt | 5.13.0
Compiled against GDAL/OGR | 3.0.0 | Running against GDAL/OGR | 3.0.0
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
PostgreSQL Client Version | 11.4 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 6.1.0 | Running against PROJ | Rel. 6.1.0, May 15th, 2019
OS Version | Arch Linux |   |

**Comment by kannes** [comment]
Same issue with another GPKG (same data source) straight out of GDAL.

`gdal_translate -of GPKG NE1_50M_SR_W/NE1_50M_SR_W.tif raster.gpkg `
[raster.gpkg.zip](https://github.com/qgis/QGIS/files/3373158/raster.gpkg.zip)

**Comment by kannes** [comment]
No such issue with a GPKG that already had a vector layer inside before I added the same raster as above with GDAL:

`gdal_translate -of GPKG NE1_50M_SR_W/NE1_50M_SR_W.tif addraster.gpkg -co  APPEND_SUBDATASET=YES -co RASTER_TABLE=ne1_50m_sr_w`
[addraster.gpkg.zip](https://github.com/qgis/QGIS/files/3373163/addraster.gpkg.zip)

**Comment by rouault** [comment]
Cannot reproduce with latest QGIS and GDAL master

Version de QGIS | 3.9.0-Master | Révision du code | 738ced6
-- | -- | -- | --
Compilé avec Qt | 5.9.1 | Utilisant Qt | 5.9.1
Compilé avec GDAL/OGR | 3.1.0dev-3bc4cfb-dirty | Utilisé avec GDAL/OGR | 3.1.0dev-f4c0681-dirty
Compilé avec GEOS | 3.5.0-CAPI-1.9.0 | Utilisé avec GEOS | 3.8.0dev-CAPI-1.11.0 fd45dab
Version du client PostgreSQL | 9.5.19 | Version de SpatiaLite | 5.0.0-beta1
Version de QWT | 6.1.3 | Version de QScintilla2 | 2.10.2
Compilé avec PROJ | 6.2.0 | Fonctionne avec PROJ | Rel. 6.2.0, September 1st, 2019
Cette copie de QGIS dispose d'une sortie de débogage.
OS Version | Ubuntu 16.04.6 LTS |   |

**Comment by kannes** [comment]
Confirming fixed. Thanks!
