### ISSUE TITLE
Exporting raster as raw data to GeoPackage fails silently

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#30644]
**Describe the bug**
Exporting a raster as "Raw data" to GeoPackage fails silently. I tested with a 1 Byte, 3 bands dataset, I did *not* test other data.

Exporting as "Rendered image" works fine.

**How to Reproduce**

0. Grab https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/50m/raster/NE1_50M_SR_W.zip
1. Load NE1_50M_SR_W.tif
2. Right-click the layer -> Export as ...
3. Choose GeoPackage
4. Ensure that "Raw data" is ticked
5. Export
6. The progress bar runs, we get the message "Layer Exported: Successfully saved raster layer to /path/raw.gpkg"
7. No file is written
8. QGIS tries to load something and fails with "Unsupported Data Source: GPKG:/path/raw.gpkg:raw is not a supported raster data source"

**QGIS and OS versions**

QGIS version | 3.8.0-Zanzibar | QGIS code branch | Release 3.8
-- | -- | -- | --
Compiled against Qt | 5.13.0 | Running against Qt | 5.13.0
Compiled against GDAL/OGR | 3.0.0 | Running against GDAL/OGR | 3.0.0
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
PostgreSQL Client Version | 11.4 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 6.1.0 | Running against PROJ | Rel. 6.1.0, May 15th, 2019
OS Version | Arch Linux |   |

**Comment by gioman** [comment]
Confirmed, the file never shows up in the output folder (during the export or after).

**Comment by klakar** [comment]
While trying:
`gdal_translate -of GPKG NE1_50M_SR_W.tif NE1_50M_SR_W.gpkg`
from the terminal works fine.

(QGIS 3.8.0 / GDAL 2.2.3)

**Comment by kannes** [comment]
Thank you!
