### ISSUE TITLE
QGIS 3.6.0 confusing update window

### ISSUE THREAD

**Issue by Komzpa** [qgis/QGIS#30642]
1) sends me to issues.qgis.org
2) offers to get 3.8 release, tells you are working on 3.7 and 3.8 is getting released later
![image](https://user-images.githubusercontent.com/810638/60882341-50e85e80-a250-11e9-8223-2b926837266a.png)

**Comment by stev-0** [comment]
Not sure this in GUI / UX - looks like it's in the backend. This endpoint is called: https://version.qgis.org/version.txt and it is that which is out of date

**Comment by stev-0** [comment]
Pretty sure this can be closed as it is replaced by https://github.com/qgis/QGIS/issues/31019

**Comment by jef-n** [comment]
Duplicate of #31019
