### ISSUE TITLE
Unexpected removal of newline on Font Marker

### ISSUE THREAD

**Issue by Saijin-Naib** [qgis/QGIS#30659]
**Describe the bug**
When using a concat with the Font Marker symbol type, newline characters are seemingly stripped, resulting in output that is only a single line. This can make the utility and legibility of this marker type reduced.

**How to Reproduce**
Exact code being used:
concat(@geometry_point_num,'\n', ' X: ',format_number($x_at(@geometry_point_num),3), '\n' , ' Y: ' ,format_number($y_at(@geometry_point_num),3))
Preview of the code, and how QGIS expects it to render
![image](https://user-images.githubusercontent.com/19295950/60978886-ccedaf80-a2ff-11e9-8586-ff8b1d2c36aa.png)

Preview of the Font Marker rendered on the map.
![image](https://user-images.githubusercontent.com/19295950/60979021-ff97a800-a2ff-11e9-8c34-cfc891bf86e3.png)

**QGIS and OS versions**

QGIS version | 3.8.0-Zanzibar | QGIS code revision | 11aff65f10
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.0 | Running against GEOS | 3.7.2-CAPI-1.11.0 b55d2125
PostgreSQL Client Version | 9.2.4 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Windows 10 (10.0) |   |  

**Additional context**
Use case: Cadastral mapping. I created a style that labels each vertex with the Vertex ID, as well as the X & Y location. This can be useful for confirming and creating call-outs for new parcels, districts, etc.

**Comment by nirvn** [comment]
This is intentional behavior. I'd advice you to use two font markers for your two lines.

**Comment by ster-sjo** [comment]
I would still be interested to know why this is intentional behavior, as this seems still intended in the latest LTR. And why is intentional behavior tagged as bug? Ok, agree on using n font markers for n lines, but placing them can be a pain. Can't we leave the decision to the user?
Can we reopen this?
