### ISSUE TITLE
Open of ~/anaconda3/share/proj failed

### ISSUE THREAD

**Issue by edelbende** [qgis/QGIS#30655]
**The bug**
At trying to clip a raster by mask layer (GDALtools), the following error appears in the report :
    pj_obj_create: Open of ~/anaconda3/share/proj failed
after which, the treatment just endlessly run.

**How to Reproduce**
1. Import the two layers (raster + grid)
2. Go to Tools -> GDAL -> Extraction raster -> Clip raster by mask layer.
3. Read Journal
4. See error "proj_create_from_database: Open of /home/edelb/anaconda3/share/proj failed", and further : "pj_obj_create: Open of /home/edelb/anaconda3/share/proj failed"

Please find here the project used :
[bug_repro.zip](https://github.com/qgis/QGIS/files/3373566/bug_repro.zip)

**QGIS and OS versions**

Version de QGIS | 3.8.0-Zanzibar | Branche de code de QGIS | Release 3.8
-- | -- | -- | --
Compilé avec Qt | 5.9.7 | Utilisant Qt | 5.9.7
Compilé avec GDAL/OGR | 2.4.1 | Utilisé avec GDAL/OGR | 2.4.1
Compilé avec GEOS | 3.7.1-CAPI-1.11.1 | Utilisé avec GEOS | 3.7.1-CAPI-1.11.1 0
Version du client PostgreSQL | 11.3 | Version de SpatiaLite | 4.3.0a
Version de QWT | 6.1.4 | Version de QScintilla2 | 2.11.1
Compilé avec PROJ | 6.1.0 | Fonctionne avec PROJ | Rel. 6.1.0, May 15th, 2019
OS Version | Ubuntu 18.04.2 LTS |   |  

**Additional context**

I don't know if this may help but "conda list | grep proj " gives :
proj4                     6.1.0                he751ad9_2    conda-forge
pyproj                    2.2.1            py36hc44880f_0    conda-forge

**Comment by gioman** [comment]
Not sure but I don't think we support officially conda installs. @edelbende

**Comment by nyalldawson** [comment]
Yes, this isn't officially supported at this stage. Please file with conda instead.
