### ISSUE TITLE
QGIS 3.4.9 LTR SID and Python Error Messages on Linux!

### ISSUE THREAD

**Issue by Navid61** [qgis/QGIS#30654]
**Describe the bug**
When I Open my QGIS I got three errors before startup and get error when I am going to close program.

**How to Reproduce**

run qgis through Linux Terminal or program menu

**QGIS and OS versions**

QGIS 3.4.9 
OS: LMDE 3  X64 (LinuxMint Debian Based)

**Additional context**

These are error messages:
1. **First Error Message:**
Couldn't load SIP module.
Python support will be disabled.

Traceback (most recent call last):
  File "", line 1, in 
  File "/usr/lib/python3/dist-packages/qgis/__init__.py", line 72, in 
    from qgis.PyQt import QtCore
  File "/usr/lib/python3/dist-packages/qgis/PyQt/QtCore.py", line 26, in 
    from PyQt5.QtCore import *
ImportError: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.13' not found (required by /usr/local/lib/python3.5/dist-packages/PyQt5/QtCore.so)

Python version:
3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516]

QGIS version:
3.4.9-Madeira 'Madeira', 54585165bb

Python path:
['/usr/share/qgis/python', '/home/killercode/.local/share/QGIS/QGIS3/profiles/default/python', '/home/killercode/.local/share/QGIS/QGIS3/profiles/default/python/plugins', '/usr/share/qgis/python/plugins', '/usr/lib/python35.zip', '/usr/lib/python3.5', '/usr/lib/python3.5/plat-x86_64-linux-gnu', '/usr/lib/python3.5/lib-dynload', '/usr/local/lib/python3.5/dist-packages', '/usr/lib/python3/dist-packages']

2.**Second Error Message:**
An error occurred during execution of following code:
qgis.utils.uninstallErrorHook()

Traceback (most recent call last):
  File "", line 1, in 
NameError: name 'qgis' is not defined

Python version:
3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516]

QGIS version:
3.4.9-Madeira 'Madeira', 54585165bb

Python path:
['/usr/share/qgis/python', '/home/killercode/.local/share/QGIS/QGIS3/profiles/default/python', '/home/killercode/.local/share/QGIS/QGIS3/profiles/default/python/plugins', '/usr/share/qgis/python/plugins', '/usr/lib/python35.zip', '/usr/lib/python3.5', '/usr/lib/python3.5/plat-x86_64-linux-gnu', '/usr/lib/python3.5/lib-dynload', '/usr/local/lib/python3.5/dist-packages', '/usr/lib/python3/dist-packages']

3. **this happen when I want close QGIS**
n error occurred during execution of following code:
qgis.utils.uninstallErrorHook()

SystemError: PyEval_EvalCodeEx: NULL globals

Python version:

QGIS version:
3.4.9-Madeira 'Madeira', 54585165bb

Python path:

**Comment by jef-n** [comment]
Your PyQt5 seems to require Qt 5.13, which is apparently not the installed one.  Doesn't seem to be a QGIS problem at all.  BTW even Debian unstable still has Qt 5.11

**Comment by Navid61** [comment]
why if it's not QGIS problem, I hadn't this problem in previous version? I think this problem reason is new update from QGIS 3

**Comment by jef-n** [comment]
> why if it's not QGIS problem, I hadn't this problem in previous version? I think this problem reason is new update from QGIS 3

Did you only update QGIS or also other stuff?

This looks like a pure PyQt5 / Qt5 issue:
```
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.13' not found (required by /usr/local/lib/python3.5/dist-packages/PyQt5/QtCore.so)
```

Can you run this without an error?
```
$ python3
Python 3.7.4 (default, Jul  9 2019, 05:48:37)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from PyQt5.QtCore import *
>>>
```

**Comment by Navid61** [comment]
Yes I could run without error
![PyQt](https://user-images.githubusercontent.com/4729469/61349663-20b94500-a87a-11e9-9b2b-db43b48f7a03.png)
