### ISSUE TITLE
cannot set excluded layers in QGIS Server project properties for projects stored in a postgresql database

### ISSUE THREAD

**Issue by beerockxs** [qgis/QGIS#30668]
Using QGIS 3.8 on Windows 7 x64, I can't exlude layers from being served as WMS in the project properties - QGIS Server tab. When I check the "Exlude layers" checkbox and click on the + button to add layers, the popup window is empty and I can't add any layers, see the attached screenshot.
![grafik](https://user-images.githubusercontent.com/16764567/61035872-39cc7c80-a3c8-11e9-8b11-2f27556e8846.png)

**Comment by gioman** [comment]
@beerockxs works fine on master/linux. Can you give it a try (on master)?

**Comment by beerockxs** [comment]
This happens only for projects stored in a postgresql database

**Comment by Pedro-Murteira** [comment]
I've tested this issue on QGIS 3.22.4 and 3.24.0 and I can't reproduce it. I can exclude layers on a project loaded from postgresql and local projects. (Windows 10). @beerockxs Did you come across this issue in more recent versions of QGIS?
