### ISSUE TITLE
Convert map to Raster (Processing Toolbox) Clips Text on Output

### ISSUE THREAD

**Issue by leciphern** [qgis/QGIS#30679]
**Bug Description**
"Convert map to Raster" tool Clips all text items that intersect internal "Tile" boundaries on geotif output "Output Layer". Increasing or decreasing "Tile size" shifts the text clipping to new internal boundaries, respectfully.

The only option to produce a map free of text clipping is to specify a Tile Size that is larger than my desired map. The map area text will be clean, however, the overall geotif will be four times larger (spatially) and the map will have a large amount of data not intended to be shown.

**How to Reproduce**
1. Open a map with a fair amount of text, for example, a large state map with cities labeled.

2. Go to: Processing Toolbox > Convert Map to Raster

3. Minimum exent.. > Choose "Use Canvas Extent"

4. "Single layer to render option" > Leave blank

5. Leave all other parameters as defaults

6. Choose "Run" and carefully inspect output for tile boundary text clipping. Character strings will be masked. Resulting in partial characters and or partial words.

7. Afterward, repeat process with a smaller "Tile size" specification, i.e., change to 512 and the text clipping error of degree will increase.

8. Changing the "Tile size" to 2048 decreases text clipping, but may increase spatial coverage if the map extent exceeds the height or width of the tile size.

Thank you in advance,
Leon

![image](https://user-images.githubusercontent.com/52794957/61071252-38a24c00-a3d6-11e9-8603-ff61165f47a0.png)

QGIS version
3.8.0-Zanzibar
QGIS code revision
11aff65f10
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
2.4.1
Running against GDAL/OGR
2.4.1
Compiled against GEOS
3.7.2-CAPI-1.11.0
Running against GEOS
3.7.2-CAPI-1.11.0 b55d2125
PostgreSQL Client Version
9.2.4
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
5.2.0
Running against PROJ
Rel. 5.2.0, September 15th, 2018
OS Version
Windows 7 SP 1 (6.1)

**Comment by gioman** [comment]
@leciphern cannot replicate on the latest master.
