### ISSUE TITLE
Non-existent but registered attribute table in GPKG is added as empty table

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#30670]
**Describe the bug**
When a GPKG references a layer in its `gpkg_contents` table that does not actually exist, QGIS presents an empty table to the user instead of an fatal error.

**How to Reproduce**

1. Have a geopackage
2. Add an entry to `gpkg_contents` that registers an attribute table that does not actually exist, e.g. `INSERT INTO gpkg_contents ('table_name', 'data_type') VALUES ('non_existent_table', 'attributes');`
3. Load the file in QGIS
4. `non_existent_table` will be presented as available (correct, it should!)
5. `non_existent_table` will be "loaded" without any error, the result is an empty table with no attributes.

In the log we can find an error from OGR that QGIS turns into just a hidden warning:

`2019-07-11T11:09:31     WARNING    OGR[3] error 1: sqlite3_prepare_v2(SELECT Count(*) FROM "non_existent_table") failed: no such table: non_existent_table`

QGIS should instead throw an error message at the user that the table could not actually be found and not present a faulty, fake layer.

This does not happen for tables of `data_type` `features` or `tiles` as OGR does weeds those out silently.

**QGIS and OS versions**

QGIS version | 3.8.0-Zanzibar | QGIS code branch | Release 3.8
-- | -- | -- | --
Compiled against Qt | 5.13.0 | Running against Qt | 5.13.0
Compiled against GDAL/OGR | 3.0.0 | Running against GDAL/OGR | 3.0.0
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
PostgreSQL Client Version | 11.4 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 6.1.0 | Running against PROJ | Rel. 6.1.0, May 15th, 2019
OS Version | Arch Linux |   |

**Comment by elpaso** [comment]
The source would be a corrupted GPKG, correct?
We rely on GDAL for GPKG handling, but I suppose we could check for the existence of the table before we actually create the layer. 

Does the created layer entry appear to be broken (with the exclamation sign mark) btw?

**Comment by kannes** [comment]
Yes, the file is malfomed.

Nope, the layer is shown as normal attribute/table layer, it's just empty.

As I wrote, GDAL seems to emit an *error* but QGIS considers it just a *warning*. That seems to be the only issue :))

**Comment by gioman** [comment]
@kannes still true on recent QGIS releases?

**Comment by kannes** [comment]
I don't see the message in the log anymore but the non-existent table is still added as empty table. Here is a sample:
[asd.gpkg.zip](https://github.com/qgis/QGIS/files/8225230/asd.gpkg.zip)

**Comment by kannes** [comment]
Yay, thanks @rouault!
