### ISSUE TITLE
Band selector not working in processing batch mode dialog

### ISSUE THREAD

**Issue by SrNetoChan** [qgis/QGIS#30671]
**Describe the bug**

In processing, when working with raster as inputs, you often need to select the band to use (even if the raster only has one band). In single mode this works fine, and if only one band is available that one is selected as soon as you select the input raster.

On the other hand, in batch mode, the band selector widget does not work (It's always empty), does not use band 1 by default and does not allow you to type the band number manually. This means that it's impossible to use the tools in batch mode.

**How to Reproduce**

Zonal statistics algorithm is a good example of this.

1. Load a raster layer and a vector layer
2. Open the Zonal statistics tool in the processing Raster analysis group
3. You should be able to select the raster and the raster band to use

![image](https://user-images.githubusercontent.com/3607161/61050709-8d969000-a3df-11e9-92fa-55db991d39d6.png)

4. click the run as batch. not the band number is not possible to select or even set.

![image](https://user-images.githubusercontent.com/3607161/61050755-9e470600-a3df-11e9-8994-ca54b7dff6c5.png)

**QGIS and OS versions**

QGIS 3.4.9 LTR in  kubuntu 18.04

**Additional context**

**Comment by jonnyforestGIS** [comment]
I confirm this behaviour in Windows 7 64-bits.

**Comment by chapmanjacobd** [comment]
I'm also having this issue

AttributeError: 'BatchInputSelectionPanel' object has no attribute 'value' 
Traceback (most recent call last):
  File "/usr/share/qgis/python/plugins/processing/gui/wrappers.py", line 209, in widgetValue
    return self.value()
  File "/usr/share/qgis/python/plugins/processing/gui/wrappers.py", line 1012, in value
    return self.widget.getValue()
AttributeError: 'BatchInputSelectionPanel' object has no attribute 'value'

using https://copr.fedorainfracloud.org/coprs/dani/qgis/build/971645/

**Comment by nyalldawson** [comment]
I can't reproduce on master --is this still an issue?

**Comment by chapmanjacobd** [comment]
I learned how to use PyQGIS which was a lot easier. If someone has this problem in the future here is some code to get you started:

I think this issue can be closed if you can't reproduce it

```
import sys, csv

from qgis.core import (
     QgsApplication, 
     QgsProcessingFeedback, 
     QgsVectorLayer,
     QgsVectorFileWriter
)

# See https://gis.stackexchange.com/a/155852/4972 for details about the prefix 
QgsApplication.setPrefixPath('/usr', True)
qgs = QgsApplication([], False)
qgs.initQgis()

# Append the path where processing plugin can be found
sys.path.append('/usr/share/qgis/python/plugins')

from qgis.analysis import QgsNativeAlgorithms
import processing
from processing.core.Processing import Processing
Processing.initialize()
QgsApplication.processingRegistry().addProvider(QgsNativeAlgorithms())

zone_stats = ("id", "count", "sum", "mean","min","max") # id,0,1,2,5,6
layer = QgsVectorLayer('/home/xk/data/points/neighborhood_buffer.sqlite|layername=neighborhood_buffer1', "multipolygon", "ogr")
layer.selectAll()
clone_layer = processing.run('native:saveselectedfeatures', {'INPUT': layer, 'OUTPUT': 'memory:'})['OUTPUT']

res = processing.run('qgis:zonalstatistics',{'INPUT_RASTER': '/home/xk/data/raster/selected_hyde3.2.1/0AD_lu/conv_rangeland0AD.asc','INPUT_VECTOR': clone_layer,'RASTER_BAND':1,'STATS': [1,2,5,6]})['INPUT_VECTOR']
QgsVectorFileWriter.writeAsVectorFormat(res, '/home/xk/data/raster_processed/lu_conv_rangeland0AD.csv', "UTF-8", driverName="CSV", attributes=([res.fields().indexFromName(fields.name()) for fields in res.fields() if any(s in fields.name() for s in tuple(zone_stats))]))
print('lu_conv_rangeland0AD')
```

**Comment by SrNetoChan** [comment]
The problem still persists in QGIS 3.4.10 LTR, but not in master (tested on linux). We did not label this as a regression (although I haven't checked it), so I guess it should be ok to close it. Thanks

**Comment by gioman** [comment]
> The problem still persists in QGIS 3.4.10 LTR, but not in master (tested on linux). We did not label this as a regression (although I haven't checked it), so I guess it should be ok to close it. Thanks

@SrNetoChan @nyalldawson if there was a fix shouldn't be backported to LTR?

**Comment by nyalldawson** [comment]
I'm not aware of a specific fix which was made for this issue. I think it's been "accidentally" fixed as a result of some semi related addition or refactoring work.

**Comment by SrNetoChan** [comment]
Can we keep this open just tagging 3.4?

**Comment by gioman** [comment]
> Can we keep this open just tagging 3.4?

@SrNetoChan I guess we can, the hard part seems to pinpoint what fixed this issue.
