### ISSUE TITLE
GUI: Quicker application of styles to layer

### ISSUE THREAD

**Issue by beycpt** [qgis/QGIS#30674]
Applying a style to a layer is currently a longer process by clicking the Context menu > Properties > Style > Load Style... : Load Style : Apply.
I wonder if this can be more convenient by adding an option in the current layer's context menu where we have already the Styles category. However, this context menu item only allows to copy and paste styles but does not provide the option to load and apply a saved style. 
How about adding another menu item in the Styles category below the "Copy Styles" entry: "Load Style >". Upon hovering of over this new category, a new popup-menu will give the last five (or more?) styles used and a button at the bottom of the popup-menu will give the option to set the file path as currently done with the Style menu in the Properties window. I think this would be a huge improvement!
![CopyStyle_QGIS](https://user-images.githubusercontent.com/52786800/61054577-01d92f80-a3f0-11e9-8319-ab7ac1eae4b3.jpg)

**Comment by roya0045** [comment]
I agree that this would be nice, it's doable for sure but given the fact that the implementation of the save and loader is in the property widget. I'm not sure if simply extracting the functions, patching up dependencies and variable and then linking up the UI will be sufficient.

I have made a fork and will try to make a PR out of it at some point just to see what the ohter devs think. I'm sure they have better ideas than me.

**Comment by jgrocha** [comment]
@beycpt You can save the styles on the provider. If you save the style on the provider (GeoPackage or Postgresql) and select `Use as default style for this layer`, when you open the layer in any other project, that style will be immediately loaded.

**Comment by beycpt** [comment]
Thanks for that information. Since I'm new to QGIS it will take me while to figure out what exactly you mean by this. I still believe it would be more intuitive to have that quick loading option in the layer's context menu.
