### ISSUE TITLE
WARNING Field x ignored, because of unsupported type citext (Postgresql extension)

### ISSUE THREAD

**Issue by fernandocanizo** [qgis/QGIS#30678]
**Feature description.**
Add support for **citext** type on Postgresql. `citext` is a core extension which allows to have a case insensitive field without worrying about including specific indexes when searching to improve performance.

`citext` is nothing else but text, so it should be trivial to include its support.

**Additional context**

[`citext` extension documentation](https://www.postgresql.org/docs/current/citext.html)

Excerpt from above link:

> F.8.1. Rationale
The standard approach to doing case-insensitive matches in PostgreSQL has been to use the lower function when comparing values, for example

> SELECT * FROM tab WHERE lower(col) = LOWER(?);
This works reasonably well, but has a number of drawbacks:

> It makes your SQL statements verbose, and you always have to remember to use lower on both the column and the query value.

> It won't use an index, unless you create a functional index using lower.

> If you declare a column as UNIQUE or PRIMARY KEY, the implicitly generated index is case-sensitive. So it's useless for case-insensitive searches, and it won't enforce uniqueness case-insensitively.

> The citext data type allows you to eliminate calls to lower in SQL queries, and allows a primary key to be case-insensitive. citext is locale-aware, just like text, which means that the matching of upper case and lower case characters is dependent on the rules of the database's LC_CTYPE setting. Again, this behavior is identical to the use of lower in queries. But because it's done transparently by the data type, you don't have to remember to do anything special in your queries.

**Comment by DelazJ** [comment]
#30431?

**Comment by nyalldawson** [comment]
Yes. Already fixed

**Comment by fernandocanizo** [comment]
Sorry, I looked only in open issues. I see on referenced issue #30431 that the backport to 3.8 has been done and merged too, however I'm running version 3.8.0-Zanzibar and the problem is still there. I cannot find any minor or patch version reference in the backport, so is it my distro QGIS which is broken or this fix is coming later, say in a 3.8.1 version for example?

**Comment by nyalldawson** [comment]
It's in 3.8.1, but not 3.8.0
