### ISSUE TITLE
Control feature rendering order will crash QGIS when used on a joined field from a PostGIS table

### ISSUE THREAD

**Issue by mhabets** [qgis/QGIS#30677]
**Describe the bug**
Control feature rendering order will crash QGIS (on windows 10) when used on a joined field from a PostGIS table.

**How to Reproduce**

1. Add a point feature layer (layer A) from a PostGIS source
2. Add a CSV layer without geometry
3. Join layer A with the CSV layer.
4. Edit the symbology of the feature layer. In "Control feature rendering order" select the joined field.
5. QGIS will simply crash :-(

**QGIS and OS versions**

QGIS version | 3.8.0-Zanzibar | QGIS code revision | 11aff65f10
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.0 | Running against GEOS | 3.7.2-CAPI-1.11.0 b55d2125
PostgreSQL Client Version | 9.2.4 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Windows 10 (10.0)

**Comment by mhabets** [comment]
Also not working with the following expression: `coalesce("joined_field", 0)`.
So the reason should be not related to the NULL values.

**Comment by gioman** [comment]
Did it worked as expected on QGIS 2.18? @mhabets

**Comment by mhabets** [comment]
To be noted: with a shapefile source as a the first layer. QGIS doesn't crash but the rendering order is not working.

**Comment by mhabets** [comment]
I made some edits because I discovered that the crashing issue is related to the data source for the feature layer:
- PostGIS source => crash
- Shapefile => no crash but nothing happens

**Comment by mhabets** [comment]
> 
> 
> Did it worked as expected on QGIS 2.18? @mhabets

@gioman Sorry, I can't tell for QGIS 2.18 but same issue with QGIS 3.4.9

**Comment by gioman** [comment]
> @gioman Sorry, I can't tell for QGIS 2.18 but same issue with QGIS 3.4.9

if someone can establish it was working in the past we can add the label "regression" here.

**Comment by Pedro-Murteira** [comment]
@mhabets I've tested this issue on QGIS 3.22.3. On Windows 10 and I can't reproduce the crash. Did you come across this issue more recently?
