### ISSUE TITLE
Bump minimum proj version requirement to 4.9.3

### ISSUE THREAD

**Issue by marisn** [qgis/QGIS#30675]
It is not possible to build QGIS with PROJ <=4.9.2 (#29249; https://github.com/OSGeo/PROJ/issues/354) but during the configuration phase CMake happily will accept any proj version and will continue attempt to build with it. I managed to compile and successfully run QGIS with proj 4.9.3 thus confirming it as the minimum working version.

Changes are required to CMake magick and documentation, as documentation states "Proj >= 4.4.x" to be sufficient, although it isn't.
https://github.com/qgis/QGIS/blob/master/INSTALL#L102
https://github.com/qgis/QGIS/blob/master/doc/INSTALL.html#L208

**Comment by m-kuhn** [comment]
@marisn thanks for the details. are you able to create a pull request for that?

**Comment by marisn** [comment]
> @marisn thanks for the details. are you able to create a pull request for that?

No. My CMake knowledge is almost 0.

**Comment by m-kuhn** [comment]
Can you do the docs part?
