### ISSUE TITLE
GUI: Option for Coordinate display in format: Latitude then Longitude

### ISSUE THREAD

**Issue by beycpt** [qgis/QGIS#30672]
By default, the coordinate display in the statusbar is always Longitude then Latitude. It would be nice to have the option for the more common format: Latitude, Longitude.
![Coordinate_QGIS](https://user-images.githubusercontent.com/52786800/61053413-c6d5fc80-a3ed-11e9-8ffa-96ca9e4b01f1.jpg)

**Comment by i-s-o** [comment]
I am only a casual user of GIS, but I am guessing that the coordinate box format is specifically designed to show only "X,Y" coordinates to avoid any possible confusion. See: https://wiki.osgeo.org/wiki/Axis_Order_Confusion.

I am personally conditioned to see LatLon, and I find the [Lat Lon Tools](https://github.com/NationalSecurityAgency/qgis-latlontools-plugin) plugin very useful as a bridge between mathematically-focused X,Y and navigation-focused LatLon.

**Comment by beycpt** [comment]
Since Lan Lon Tools are mentioned here: if you use the Zoom to Lat Lon tool you will see that the sequence here is also FIRST Latitude THEN Longitude. I wonder why QGIS cannot provide the same option in the Project properties (Y,X Coordinates). Shouldn't be so hard and this way everybody could configure QGIS to his/her preferences. Everybody would be happy...  :-)

**Comment by ExcelGithub** [comment]
I'm in favor of this idea! First Latitude then Longitude should be an option in preferences, I think!

**Comment by gisn8** [comment]
Bump

**Comment by alansaviolobo** [comment]
> Bump

+ 1

**Comment by nyalldawson** [comment]
This was implemented in 3.26

**Comment by liuxsdev** [comment]
> This was implemented in 3.26

Where is this option  in  3.26
