### ISSUE TITLE
QGIS 3.4 and QGIS 3.8 GRASS initialization error: GRASS was not found in...

### ISSUE THREAD

**Issue by edurojasr** [qgis/QGIS#30680]
Hi all! thanks for the attention in advance!

**Describe the bug**

When using QGIS with GRASS, a warning occurs: 
"_GRASS initialization error: GRASS was not found in 'C: / PROGRA ~ 1 / QGIS 3.8 / apps / grass / grass76' (GISBASE), the provider and the plugin will not work_. "

this happens when GRASS plugin is enabled from the plugin manager.

The GRASS modules from the processing toolbox work, but the GRASS panel of the plugin is not working and you can not use any option from the menu Plugins > GRASS. 

as you can see in the following image: (in Spanish)
![image](https://user-images.githubusercontent.com/35645729/61079303-c7679680-a3df-11e9-95d2-934c5a4ac376.png)

the line in red the line in red says "The installation of GRASS is currently not valid" 

changing the installation path manually does not fix the problem a as you can see in the following image
![image](https://user-images.githubusercontent.com/35645729/61079644-7906c780-a3e0-11e9-98b4-784d14b4dd5c.png)

the yellow headband gives one more clue, "GISBASE" apparently is missing.

**How to Reproduce**
A) Method:
1. installation of QGIS 3.4 or 3.8 
2. open QGIS with GRASS. (the error will occur immediately)

B) Method:
1. open QGIS with GRASS, 
2. go to plugin manager 
3. activate the GRASS 7 plugin (error will appear)

**QGIS and OS versions**
QGIS 3.4.9 with GRASS 7.6.1
QGIS 3.8 with GRASS 7.6.1
Windows 10 1809

**Additional context**
Tested in 2 diferentes PC

**Comment by rjstapel** [comment]
Similar problem here on a Mac:
_WARNING    GRASS init fout : GRASS werd niet gevonden in '/usr/local/opt/osgeo-grass/grass-base' (GISBASE), provider en plug-in zullen niet werken._

QGIS 3.8.1, MacOS 10.14.6

**Comment by edurojasr** [comment]
Apparently this was a local situation, having several versions of QGIS installed at the same time.
Closing because the problem no longer appears

**Comment by IndigoWizard** [comment]
How did you solve the issue?
- Using QGIS 3.26.1-Buenos Aires
