### ISSUE TITLE
QGIS 3.80 Crashed

### ISSUE THREAD

**Issue by Cmattheou** [qgis/QGIS#30681]
## User Feedback

just open and  exit QGIS. Nothting done with in tis period

## Report Details

*Crash ID*: b11db3d431a36dd8fdf085fe4349919d50f378d8

*Stack Trace*
<pre>
QMapNodeBase::nextNode :
QgsPluginLayerRegistry::~QgsPluginLayerRegistry :
QgsValidityCheckResult::QgsValidityCheckResult :
QgsApplication::~QgsApplication :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.8.0-Zanzibar
QGIS code revision: 11aff65f10
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by nirvn** [comment]
@Cmattheou , can you list your active plugins?

**Comment by gioman** [comment]
> @Cmattheou , can you list your active plugins?

@Cmattheou or... try with a new/clean QGIS profile and don't install any 3rd party plugins.

**Comment by Cmattheou** [comment]
please see attached

I had reinstall QGIS and I had remove all plugins. It seems that the problem have been solved 

Adding  DEMto3D, OpenLayers Plugin and QGIS Cloud Plugin, it crashed
I had removed QGIS Cloud Plugin and its ok, so it seems that was the problem

**Comment by nirvn** [comment]
@Cmattheou , thanks, fix in PR #30685 .

**Comment by m-kuhn** [comment]
Just a gentle reminder that an open pull request doesn't mean issue fixed, there's still a possibility it's rejected for one reason or the other. And it's closed automatically on merge.

Fortunately the pull request here is high quality, so not a big risk for early closure :)

**Comment by nirvn** [comment]
Good reminder. Let the issues be closed through commit references, easier the manage that way.
