### ISSUE TITLE
Add record for geometryless Postgres table fails in table view

### ISSUE THREAD

**Issue by timlinux** [qgis/QGIS#30696]
# Problem:

When editing a table layer, creating a new record fails when in table view.

> Layer Plant Activity: PostGIS error while adding features: ERROR: null value in column "name" violates not-null constraint DETAIL: Failing row contains (10, null). 

Same process works fine when using the 'add record' icon on the toolbar.

![add-record-bug](https://user-images.githubusercontent.com/178003/61180929-7ee5ee00-a616-11e9-9bbf-6d34af17493c.gif)

The table has a not null constraint on the 'name' column. It appears that QGIS might be trying to do an initial commit (bad!) of the record when it is added in table view. I can see this because the sequence is being incremented with each failure.

Here is the structure of the table in question:

```sql
-- Table: public.plant_activity

-- DROP TABLE public.plant_activity;

CREATE TABLE public.plant_activity
(
    id integer NOT NULL DEFAULT nextval('plant_activity_id_seq'::regclass),
    name text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT plant_activity_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.plant_activity
    OWNER to timlinux;
```

# Version:

QGIS 3.8 (on macOS, Lutra build)

**Comment by stev-0** [comment]
Pretty sure this is fixed in 3.10
