### ISSUE TITLE
Add functionality to rename and order section in qgis reporter

### ISSUE THREAD

**Issue by severina19** [qgis/QGIS#30706]
**Feature description.**

Currently when a new section is created in the qgis reporter, it is named as "section" as default, and there is no option to rename it. This makes things a bit confusing when there are many sections. Also, there is no option to change the order of different sections.

**Additional context**
See image as example.

![4doHM](https://user-images.githubusercontent.com/29518137/61203627-377d6180-a6eb-11e9-9edb-aefde9a79abd.png)

**Comment by alexbruy** [comment]
Duplicates #29060.
