### ISSUE TITLE
The processing line to polygons don't work well

### ISSUE THREAD

**Issue by caidc** [qgis/QGIS#30708]
**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by caidc** [comment]
When I use the tool line to polygons, It can't do my job very well. The tool can only turn closed, continuous polylines into faces

**Comment by nyalldawson** [comment]
That's exactly what this tool is designed to do. Try "polygonize" instead -- that may be what you're after.

**Comment by caidc** [comment]
thank you very much. but the "polygonize" doesn't console my problem. I want to get every little polygon. just like what I descript in the email which I send to you. @

**Comment by caidc** [comment]
I want the little polygon of 1 and 2,but “polygonize” give me theCombined polygon of 1 and 2.--------------------------------


蔡德成
中国地质大学（武汉）地理与信息工程学院
国家GIS工程技术研究中心
通信地址：湖北省武汉市鲁磨路 388号  地理与信息工程学院
办公地点：中国地质大学（武汉）  工程实验大楼440#
邮编：430074
手机：17786402505
邮箱：dechengcai@sina.com
Q Q:   1982990524







----- 原始邮件 -----
发件人：Nyall Dawson <notifications@github.com>
收件人：qgis/QGIS <QGIS@noreply.github.com>
抄送人：Caidc <dechengcai@sina.com>,  Author <author@noreply.github.com>
主题：Re: [qgis/QGIS] The processing line to polygons don't work well (#30708)
日期：2019年07月15日 17点43分

That's exactly what this tool is designed to do. Try "polygonize" instead -- that may be what you're after.

**Comment by caidc** [comment]
![image](https://user-images.githubusercontent.com/26620090/61264299-9a8bf880-a7be-11e9-8636-0a1b292391fb.png)
