### ISSUE TITLE
Importing spatial bookmark with single quote does not work

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#30711]
**Describe the bug**
Single quote in spatial bookmark name breaks import.

**How to Reproduce**

1. Save this XML to a file

```
<!DOCTYPE qgis_bookmarks>
<qgis_bookmarks>
  <bookmark>
    <id>3</id>
    <name>test's</name>
    <project></project>
    <xmin>13.651571856287585</xmin>
    <ymin>43.04288807961079</ymin>
    <xmax>37.27657185628759</xmax>
    <ymax>62.329564726317386</ymax>
    <sr_id>3452</sr_id>
  </bookmark>
</qgis_bookmarks>

```

2. Try to import it as spatial bookmarks
3. QGIS will error with:

```
Unable to create the bookmark.
Driver: Unable to execute statement
Database: near "s": syntax error
```

**QGIS and OS versions**

QGIS version | 3.8.0-Zanzibar | QGIS code branch | Release 3.8
-- | -- | -- | --
Compiled against Qt | 5.13.0 | Running against Qt | 5.13.0
Compiled against GDAL/OGR | 3.0.0 | Running against GDAL/OGR | 3.0.0
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
PostgreSQL Client Version | 11.4 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 6.1.0 | Running against PROJ | Rel. 6.1.0, May 15th, 2019
OS Version | Arch Linux |   |  

**Additional context**

I saw the unsafe construction of SQL in https://github.com/qgis/QGIS/blob/861c5115ebd9533864cd4e9338ea1e35014ef0cd/src/app/qgsbookmarks.cpp#L314 and assumed the worst. :}

**Comment by nirvn** [comment]
@kannes , thanks for reporting the issue, a fix will be soon pushed into upcoming QGIS 3.4.10 and 3.8 (July 19th).
