### ISSUE TITLE
QGIS Server WMS GetFeatureInfo does not evaluate represent_value expression in maptip

### ISSUE THREAD

**Issue by mdouchin** [qgis/QGIS#30719]
**Describe the bug**

When getting HTML GetFeatureInfo response from QGIS Server, for a vector layer with a maptip configured, the `represent_value` method which replaces the field value with its represented value (for example for Value Relation edit widget) is not evaluated in the server context.

**How to Reproduce**

1. Add any vector layer with a QGIS project
2. Configure an edit widget with Value Map (or value relation, etc.) for example for a `category` field
3. Add content in the Maptip tab of the Vector layer properties, with the expression `represent_value("category")`
4. In QGIS desktop, the maptip shows the correct value
5. Publish the QGIS project with QGIS Server, and use the GetFeatureInfo request with HTML format -> the content is wrong and contains plain text containing the word `represent_value` 

**QGIS and OS versions**

Test with QGIS Server 3.4.9

**Comment by nboisteault** [comment]
Does not work with QGIS Server 3.16.3 neither.

**Comment by elpaso** [comment]
Any chance to have a test project and data?

**Comment by mdouchin** [comment]
Old issue ;) I need to re-test it and provide QGIS project with test data

**Comment by mdouchin** [comment]
@nboisteault or @Gustry do you have any test project ?

**Comment by nboisteault** [comment]
I'm currently creating a project.

**Comment by nboisteault** [comment]
[represent_value.zip](https://github.com/qgis/QGIS/files/6856095/represent_value.zip)

You'll find in this zip a QGIS project with two layers in a geopackage. Use the maptip tool on the only point of `point_layer`, you'll have `first` displayed.

Then you can execute this query (change path accordingly) : 
`QUERY_STRING="MAP=/srv/projects/tests/represent_value.qgs&SERVICE=WMS&REQUEST=GetFeatureInfo&QUERY_LAYERS=point_layer&I=645&J=345&CRS=EPSG:2154&BBOX=749647.283424,6268207.177805,798145.50542,6292178.475747&HEIGHT=906&WIDTH=1833&WITH_MAPTIP=true" /usr/lib/cgi-bin/qgis_mapserv.fcgi`
You'll have this result : 
```
GetFeatureInfo results

Layer 'point_layer'
Feature 1
fid = '1'
value = 'first'
maptip = '[%  represent_value(  "value" ) %]'
```

As you see, expression is not interpreted. I had the same bug with `relation_aggregate()` too.

Thanks @elpaso for your help.

**Comment by mdouchin** [comment]
Muchas gracias !
