### ISSUE TITLE
Spatial Bookmark with XML characters exports broken XML

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#30710]
**Describe the bug**
Special characters are not handled appropriately by the spatial bookmark (XML) export, they are written as-is, not encoded.

**How to Reproduce**

1. Create a new spatial bookmark
2. Name it <test>
3. Export the bookmarks to a file

In the exported file the bookmark name "`<test>`" was saved as `<name>&lt;test></name>`, for example

```
<!DOCTYPE qgis_bookmarks>
<qgis_bookmarks>
  <bookmark>
    <id>4</id>
    <name>&lt;asd></name>
    <project></project>
    <xmin>23.731100299401355</xmin>
    <ymin>53.051682989790436</ymin>
    <xmax>29.637350299401362</xmax>
    <ymax>57.87335215146709</ymax>
    <sr_id>3452</sr_id>
  </bookmark>
</qgis_bookmarks>
```

The closing greater than sign should be encoded as entity &gt;, https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references#Predefined_entities_in_XML

I would assume that other characters are also not handled well but have not tested further.

**QGIS and OS versions**

QGIS version | 3.8.0-Zanzibar | QGIS code branch | Release 3.8
-- | -- | -- | --
Compiled against Qt | 5.13.0 | Running against Qt | 5.13.0
Compiled against GDAL/OGR | 3.0.0 | Running against GDAL/OGR | 3.0.0
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
PostgreSQL Client Version | 11.4 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 6.1.0 | Running against PROJ | Rel. 6.1.0, May 15th, 2019
OS Version | Arch Linux |   |

**Comment by nirvn** [comment]
The > can be written as > (i.e. not replaced by its &gt; equivalent) and still produce valid XML files (you can check against online XML validators).

Qt only replaces < and & characters when creating a text node.

**Comment by kannes** [comment]
Oh, huh, I had no idea. Sorry for the noise.
