### ISSUE TITLE
Project>Export/Import>Export Map to Image: Part of exported image is replaced by background color from outside extent

### ISSUE THREAD

**Issue by andreas-paul** [qgis/QGIS#30724]
As illustrated by the attached image: when exporting a map to image from the viewport via Project>Export/Import>Export Map to Image, parts of the exported image on its left and right bounds are replaced by the background color which was present during exporting (or by whatever else was present at the time).

![QGIS-bug](https://user-images.githubusercontent.com/35452653/61246764-e5225c00-a74f-11e9-91b7-8c05e2a36f3f.jpg)

Happy to add more example images and the grid if is required to solve this issue.

**Comment by nirvn** [comment]
@andreas-paul, That's caused by rounding of extent <-> output size, which there's nothing we can do here. Your alternatives are to save your raster layer via layer right click menu, or slightly narrow down the extent so it doesn't fall at the very edge of your raster.

**Comment by andreas-paul** [comment]
That makes sense, thanks!!
