### ISSUE TITLE
dpi scale bar save image export

### ISSUE THREAD

**Issue by mankoff** [qgis/QGIS#30728]
**Describe the bug**

When selecting "Save Map As Image", the scale bar does not properly adjust to the new dpi.

**How to Reproduce**

1. Turn on Scale Bar decoration
2. Menus: Project > Import/Export / Export Map to Image
3. Change DPI from 96 to 300
4. Export Image
5. Examine exported image. Scale bar is too small.

Image on Screen:

![image](https://user-images.githubusercontent.com/145117/61254508-87731d00-a719-11e9-9bce-bc92927d85de.png)

Exported Image:

![image](https://user-images.githubusercontent.com/145117/61254580-d0c36c80-a719-11e9-96d5-70df524f8698.png)

**QGIS and OS versions**

QGIS version | 3.8.0-Zanzibar | QGIS code revision | 11aff65
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.6.2-CAPI-1.10.2 4d2925d6
PostgreSQL Client Version | 10.9 (Ubuntu 10.9-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Ubuntu 18.04.2 LTS |   |

**Comment by nirvn** [comment]
@mankoff , I can't replicate this issue (on master) using your projection:
![Screenshot from 2019-07-16 08-24-49](https://user-images.githubusercontent.com/1728657/61259185-46bfe600-a7a3-11e9-8533-52fa6c33839e.png)

Can you make a screencast of your issue?

**Comment by mankoff** [comment]
What's the best way to test things on master? Is there a nightly docker image? Some other way? Or do I need to build from source?

**Comment by gioman** [comment]
> What's the best way to test things on master? Is there a nightly docker image? Some other way? Or do I need to build from source?

there are installers for Windows (osgeo4w and as a standalone installer), for macOS and also repositories for Linux.

**Comment by mankoff** [comment]
Fixed in the version that updated on Ubuntu 18.04 a few days ago - no need for latest master/head/nightly.
