### ISSUE TITLE
"Polygonise" doesn't work well if CRS is WGS84

### ISSUE THREAD

**Issue by caidc** [qgis/QGIS#30731]
I want the little polygon of 1 and 2,but “polygonize” give me theCombined polygon of 1 and 2
![image](https://user-images.githubusercontent.com/26620090/61264379-f0f93700-a7be-11e9-8b98-fbf59a0df8ed.png)

**Comment by gioman** [comment]
@caidc please detailed steps to replicate and a sample dataset.

**Comment by caidc** [comment]
[test.zip](https://github.com/qgis/QGIS/files/3396607/test.zip)
this is my sample dataset.

**Comment by gioman** [comment]
> I want the little polygon of 1 and 2,but “polygonize” give me theCombined polygon of 1 and 2

I can't understand this description, can you try re-formulate? thanks

**Comment by caidc** [comment]
The reason is that there is no node at the intersection of the two segments. So I am trying to modify this function, first break the intersecting line segments and make one line segment into two

**Comment by caidc** [comment]
Ok, I recorded a video to illustrate the problem.
[Ubiloc-2019-07-16 18-20-10.zip](https://github.com/qgis/QGIS/files/3396624/Ubiloc-2019-07-16.18-20-10.zip)

**Comment by gioman** [comment]
if you reproject your layer to a cartographic CRS you will get the expected result.

**Comment by caidc** [comment]
Sorry，I had a try, But doen't get the expected result.

**Comment by gioman** [comment]
> Sorry，I had a try, But doen't get the expected result.

just tried with 3857 and works. What CRS have you tested?

**Comment by caidc** [comment]
I don't think you understand what I originally meant. I mean this tool can turn the line into a face, but can't get the face of the smallest unit, I marked 1 in the picture

**Comment by caidc** [comment]
I also tried the 3857 CRS, but it didn't work.

**Comment by gioman** [comment]
> I also tried the 3857 CRS, but it didn't work.

![Peek 2019-07-16 14-37](https://user-images.githubusercontent.com/1951107/61299083-5527f500-a7d7-11e9-8a08-920df576ce4e.gif)

**Comment by caidc** [comment]
Thank you very much, I followed your steps and achieved what I wanted. But I don't understand why I need to reproject the layer？

**Comment by gioman** [comment]
> Thank you very much, I followed your steps and achieved what I wanted. But I don't understand why I need to reproject the layer？

that is possibly a bug, I just gave you a workaround.

**Comment by caidc** [comment]
![image](https://user-images.githubusercontent.com/26620090/61301272-2ed57a00-a816-11e9-9e5f-84d74371910d.png)
 I think that because when the CRS is 4547 or WGS84 or others, the line vertex coordinates are too small (as shown in Figure 1), so the intersection of the line segments cannot be calculated, so this is not recognized.
![image](https://user-images.githubusercontent.com/26620090/61301524-a3101d80-a816-11e9-8086-9a91fea4f612.png)
When the CRS of the set layer is 3857, the coordinates of the line segment vertices are large(as shown in Figure 1), and the intersection of the line segments can be calculated, so that the face of the smallest unit is calculated.

**Comment by caidc** [comment]
I have an interesting thing, that is, different CRS will lead to different results with "Polygonise" @gioman

**Comment by alexbruy** [comment]
Does it work as expected if you run polygonize tool from the command line? I suppose the behavior is the same, then it should be repoted in the GDAL bugtracker, as Processing only generates command for GDAL tools.

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
