### ISSUE TITLE
QGIS crashes when exporting threeJS scenes

### ISSUE THREAD

**Issue by ecoandrewtrc** [qgis/QGIS#30752]
Crash ID: 8cc4d8bc97442d20c2cadb6bf8bd5852add9df42

Stack Trace

WTFCrash :

I don't think this is a hardware issue on my end but every time I try to export the threeJS scene I crash QGIS. 

QGIS Info
QGIS Version: 3.8.0-Zanzibar
QGIS code revision: 11aff65f10
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by nyalldawson** [comment]
this is a plugin related issue - you'll need to file it with the threeJs plugin authors, not here.
