### ISSUE TITLE
QGIS crashed when quitting

### ISSUE THREAD

**Issue by AlexGubb** [qgis/QGIS#30767]
**Describe the bug**
The program crashed when I simply quit using the X button in the top right corner

**How to Reproduce**

I don't know, as this somtimes happens and sometimes not. I don't know if it's related to my files or not

Crash ID: 7fc988d717a16711b062440b8b4f6bdc48fd2f0b

**Stack Trace**

QGraphicsItem::update :
QgsAdvancedDigitizingDockWidget::setCadEnabled :
QWidget::event :
QDockWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::hideChildren :
QWidgetPrivate::hide_helper :
QWidget::setVisible :
QWidgetPrivate::close_helper :
QWidget::~QWidget :
CPLStringList::operator char * __ptr64 * __ptr64 :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

**QGIS and OS versions**
QGIS Version: 3.4.9-Madeira
QGIS code revision: 54585165bb
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by gioman** [comment]
Please try with a new/clean QGIS profile and no 3rd party plugins installed.

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
