### ISSUE TITLE
Map view is not usable when attribute table is opened

### ISSUE THREAD

**Issue by ghtmtt** [qgis/QGIS#30763]
Freshly compiled QGIS master 3.9 on Linux.

With every layer if the option "Show Features visible on map" is chosen in the attribute table option the map view and related tools (zoom in/out, pan, move, etc) are useless. 

When trying to change the view of the map the map is "frozen". A small gif is worth 1000 words:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/2884884/61362832-2a937600-a883-11e9-85c2-d946ae83711d.gif)

**Comment by pigreco** [comment]
Confirm

## OSGeo4W 64b Network Installer

```
Versione di QGIS 3.9.0-Master
Revisione codice QGIS 63d1957d59
Compilato con Qt 5.11.2
Esecuzione con Qt 5.11.2
Compilato con GDAL/OGR 2.4.1
Esecuzione con GDAL/OGR 2.4.1
Compilato con GEOS 3.7.2-CAPI-1.11.0
Esecuzione con GEOS 3.7.2-CAPI-1.11.0 b55d2125
Versione client PostgreSQL 9.2.4
Versione SpatiaLite 4.3.0
Versione QWT 6.1.3
Versione QScintilla2 2.10.8
Compiled against PROJ 5.2.0
Running against PROJ Rel. 5.2.0, September 15th, 2018
Questa copia di QGIS scrive messaggi di debug.
OS Version Windows 10 (10.0)
Versione di QGIS 3.9.0-Master
Revisione codice QGIS 63d1957d59
Compilato con Qt 5.11.2
Esecuzione con Qt 5.11.2
Compilato con GDAL/OGR 2.4.1
Esecuzione con GDAL/OGR 2.4.1
Compilato con GEOS 3.7.2-CAPI-1.11.0
Esecuzione con GEOS 3.7.2-CAPI-1.11.0 b55d2125
Versione client PostgreSQL 9.2.4
Versione SpatiaLite 4.3.0
Versione QWT 6.1.3
Versione QScintilla2 2.10.8
Compiled against PROJ 5.2.0
Running against PROJ Rel. 5.2.0, September 15th, 2018
Questa copia di QGIS scrive messaggi di debug.
OS Version Windows 10 (10.0)
```
![bug](https://user-images.githubusercontent.com/7631137/61376423-77864500-a8a1-11e9-9870-2e408851d1c3.gif)

**Comment by gioman** [comment]
is this a regression?

**Comment by pigreco** [comment]
@gioman 
> is this a regression?

In my opinion, no, because the problem is also present in 3.8

**Comment by gioman** [comment]
> In my opinion, no, because the problem is also present in 3.8

it should be checked also on the current LTR and the old LTR (2.18).

**Comment by pigreco** [comment]
> it should be checked also on the current LTR and the old LTR (2.18).

If I am not mistaken, this flashing function when opening the attribute table was introduced after the 3.4 LTR.

I just did a test in the 3.4 LTR, everything works correctly.

**Comment by ghtmtt** [comment]
OK thanks to @DelazJ I discovered how it works.

The *problem* is due to the new `zoom/flash` to next feature introduced in 3.4. If you open the attribute table in form view, then you can click the button to flash or zoom to next feature. If you click, both buttons stay clicked, even if you switch to the normal table view.

Closing and reopening the attribute table of the same or other vectors does not reset this behavior. In my case I have the default view as table view and I didn't think it could be due to that buttons.

So not a bug, but IMHO something that can confuse the final user (at least I was confused ;) )

**Comment by pigreco** [comment]
Also for me it confuses the end user.

hank you all

**Comment by DelazJ** [comment]
Hi,
yes it's a 3.8 feature (#9992) so not a regression if that's the culprit. But it'd be an annoying bug (not simply confusing) for most users who wouldn't get the relation. I think the buttons can stay pushed while changing view or opening new table but their actions should be circumscribed to form view of the later they were enabled for, since table view does not have the concept of current feature afaik.

**Comment by gioman** [comment]
Better change the subject?

**Comment by nirvn** [comment]
Fix on the way.

**Comment by ghtmtt** [comment]
thanks @nirvn!
