### ISSUE TITLE
Regression: processing Saga "raster volume" does not work

### ISSUE THREAD

**Issue by AlisterH** [qgis/QGIS#30778]
In QGIS 3.8.0 the processing algorithm for Saga "Raster volume" produces this output, which does not include the answer we are looking for:
```
QGIS version: 3.8.0-Zanzibar
QGIS code revision: 11aff65f10
Qt version: 5.11.2
GDAL version: 2.4.1
GEOS version: 3.7.2-CAPI-1.11.0 b55d2125
PROJ version: Rel. 5.2.0, September 15th, 2018
Processing algorithm…
Algorithm 'Raster volume' starting…
Input parameters:
{ 'GRID' : 'C:/Users/alistair/AppData/Local/Temp/processing_b7ac9d44099242fba619ff8d440d41a3/402309308dd14f0da18746edf53e5def/OUTPUT.tif', 'LEVEL' : 5, 'METHOD' : 1 }

io_gdal 0 -TRANSFORM 1 -RESAMPLING 3 -GRIDS "C:/Users/alistair/AppData/Local/Temp/processing_b7ac9d44099242fba619ff8d440d41a3/093d746e514248edb56c14d6d8a2c8a7/OUTPUT.sgrd" -FILES "C:/Users/alistair/AppData/Local/Temp/processing_b7ac9d44099242fba619ff8d440d41a3/402309308dd14f0da18746edf53e5def/OUTPUT.tif"

C:\Users\alistair\Documents>set SAGA=C:/PROGRA~1/QGIS3~1.8/apps\saga-ltr

C:\Users\alistair\Documents>set SAGA_MLB=C:/PROGRA~1/QGIS3~1.8/apps\saga-ltr\modules

C:\Users\alistair\Documents>PATH=C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib\site-packages\shapely\DLLs;C:\PROGRA~1\QGIS3~1.8\apps\Python37\DLLs;C:\PROGRA~1\QGIS3~1.8\apps\qgis\bin;C:\PROGRA~1\QGIS3~1.8\apps\grass\grass76\lib;C:\PROGRA~1\QGIS3~1.8\apps\grass\grass76\bin;C:\PROGRA~1\QGIS3~1.8\apps\Python37;C:\PROGRA~1\QGIS3~1.8\apps\Python37\Scripts;C:\PROGRA~1\QGIS3~1.8\apps\qt5\bin;C:\PROGRA~1\QGIS3~1.8\apps\Python27\Scripts;C:\PROGRA~1\QGIS3~1.8\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\system32\WBem;C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib\site-packages\pywin32_system32;C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib\site-packages\numpy\.libs;;C:/PROGRA~1/QGIS3~1.8/apps\saga-ltr;C:/PROGRA~1/QGIS3~1.8/apps\saga-ltr\modules

C:\Users\alistair\Documents>call saga_cmd io_gdal 0 -TRANSFORM 1 -RESAMPLING 3 -GRIDS "C:/Users/alistair/AppData/Local/Temp/processing_b7ac9d44099242fba619ff8d440d41a3/093d746e514248edb56c14d6d8a2c8a7/OUTPUT.sgrd" -FILES "C:/Users/alistair/AppData/Local/Temp/processing_b7ac9d44099242fba619ff8d440d41a3/402309308dd14f0da18746edf53e5def/OUTPUT.tif"
____________________________

##### ## ##### ##
### ### ## ###
### # ## ## #### # ##
### ##### ## # #####
##### # ## ##### # ##
____________________________

SAGA Version: 2.3.2 (64 bit)

____________________________
library path: C:\PROGRA~1\QGIS3~1.8\apps\saga-ltr\modules\
library name: io_gdal
library : GDAL/OGR
tool : Import Raster
author : O.Conrad (c) 2007 (A.Ringeler)
processors : 8 [8]
____________________________



Parameters


Grids: No objects
Files: "C:/Users/alistair/AppData/Local/Temp/processing_b7ac9d44099242fba619ff8d440d41a3/402309308dd14f0da18746edf53e5def/OUTPUT.tif"
Select from Multiple Bands:
Alphanumeric Sorting: yes
Transformation: yes
Resampling: B-Spline Interpolation


loading: C:/Users/alistair/AppData/Local/Temp/processing_b7ac9d44099242fba619ff8d440d41a3/402309308dd14f0da18746edf53e5def/OUTPUT.tif



Driver: GTiff

Bands: 1

Rows: 61

Columns: 58


loading: OUTPUT





C:\Users\alistair\Documents>exit
Execution completed in 8.51 seconds
Results:
{}

Loading resulting layers
Algorithm 'Raster volume' finished
```

In QGIS 3.4.4 the algorithm produces this output - note the result we are looking for `Grid Volume: Volume: 1873.700044` :
````
Processing algorithm…
Algorithm 'Raster volume' starting…
Input parameters:
{ 'GRID' : 'C:/Users/alistair/AppData/Local/Temp/processing_b7ac9d44099242fba619ff8d440d41a3/402309308dd14f0da18746edf53e5def/OUTPUT.tif', 'LEVEL' : 5, 'METHOD' : 1 }

io_gdal 0 -TRANSFORM 1 -RESAMPLING 3 -GRIDS "C:/Users/alistair/AppData/Local/Temp/processing_0aaf336140bd4762b32dcbe2cf12b60b/f1b20af5fd4e4a80a8463a19435cb8e6/OUTPUT.sgrd" -FILES "C:/Users/alistair/AppData/Local/Temp/processing_b7ac9d44099242fba619ff8d440d41a3/402309308dd14f0da18746edf53e5def/OUTPUT.tif"
grid_calculus "Grid Volume" -GRID "C:/Users/alistair/AppData/Local/Temp/processing_0aaf336140bd4762b32dcbe2cf12b60b/f1b20af5fd4e4a80a8463a19435cb8e6/OUTPUT.sgrd" -METHOD 1 -LEVEL 5.0

C:\PROGRA~1\QGIS3~1.4\bin>set SAGA=C:/PROGRA~1/QGIS3~1.4/apps\saga-ltr

C:\PROGRA~1\QGIS3~1.4\bin>set SAGA_MLB=C:/PROGRA~1/QGIS3~1.4/apps\saga-ltr\modules

C:\PROGRA~1\QGIS3~1.4\bin>PATH=C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\shapely\DLLs;C:\PROGRA~1\QGIS3~1.4\apps\Python37\DLLs;C:\PROGRA~1\QGIS3~1.4\apps\qgis\bin;C:\PROGRA~1\QGIS3~1.4\apps\grass\grass-7.4.4\lib;C:\PROGRA~1\QGIS3~1.4\apps\grass\grass-7.4.4\bin;C:\PROGRA~1\QGIS3~1.4\apps\Python37;C:\PROGRA~1\QGIS3~1.4\apps\Python37\Scripts;C:\PROGRA~1\QGIS3~1.4\apps\qt5\bin;C:\PROGRA~1\QGIS3~1.4\apps\Python27\Scripts;C:\PROGRA~1\QGIS3~1.4\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\system32\WBem;C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\pywin32_system32;C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\numpy\.libs;C:/PROGRA~1/QGIS3~1.4/apps\saga-ltr;C:/PROGRA~1/QGIS3~1.4/apps\saga-ltr\modules

C:\PROGRA~1\QGIS3~1.4\bin>saga_cmd io_gdal 0 -TRANSFORM 1 -RESAMPLING 3 -GRIDS "C:/Users/alistair/AppData/Local/Temp/processing_0aaf336140bd4762b32dcbe2cf12b60b/f1b20af5fd4e4a80a8463a19435cb8e6/OUTPUT.sgrd" -FILES "C:/Users/alistair/AppData/Local/Temp/processing_b7ac9d44099242fba619ff8d440d41a3/402309308dd14f0da18746edf53e5def/OUTPUT.tif"
____________________________

##### ## ##### ##
### ### ## ###
### # ## ## #### # ##
### ##### ## # #####
##### # ## ##### # ##
____________________________

SAGA Version: 2.3.2 (64 bit)

____________________________
library path: C:\PROGRA~1\QGIS3~1.4\apps\saga-ltr\modules\
library name: io_gdal
library : GDAL/OGR
tool : Import Raster
author : O.Conrad (c) 2007 (A.Ringeler)
processors : 8 [8]
____________________________



Parameters


Grids: No objects
Files: "C:/Users/alistair/AppData/Local/Temp/processing_b7ac9d44099242fba619ff8d440d41a3/402309308dd14f0da18746edf53e5def/OUTPUT.tif"
Select from Multiple Bands:
Alphanumeric Sorting: yes
Transformation: yes
Resampling: B-Spline Interpolation


loading: C:/Users/alistair/AppData/Local/Temp/processing_b7ac9d44099242fba619ff8d440d41a3/402309308dd14f0da18746edf53e5def/OUTPUT.tif



Driver: GTiff

Bands: 1

Rows: 61

Columns: 58


loading: OUTPUT





C:\PROGRA~1\QGIS3~1.4\bin>saga_cmd grid_calculus "Grid Volume" -GRID "C:/Users/alistair/AppData/Local/Temp/processing_0aaf336140bd4762b32dcbe2cf12b60b/f1b20af5fd4e4a80a8463a19435cb8e6/OUTPUT.sgrd" -METHOD 1 -LEVEL 5.0
____________________________

##### ## ##### ##
### ### ## ###
### # ## ## #### # ##
### ##### ## # #####
##### # ## ##### # ##
____________________________

SAGA Version: 2.3.2 (64 bit)

____________________________
library path: C:\PROGRA~1\QGIS3~1.4\apps\saga-ltr\modules\
library name: grid_calculus
library : Calculus
tool : Grid Volume
author : (c) 2005 by O.Conrad
processors : 8 [8]
____________________________

Load grid: C:/Users/alistair/AppData/Local/Temp/processing_0aaf336140bd4762b32dcbe2cf12b60b/f1b20af5fd4e4a80a8463a19435cb8e6/OUTPUT.sgrd...




Parameters


Grid system: 1; 61x 58y; 1781252.5x 5872344.5y
Grid: OUTPUT
Method: Count Only Below Base Level
Base Level: 5.000000



Grid Volume: Volume: 1873.700044

C:\PROGRA~1\QGIS3~1.4\bin>exit
Execution completed in 14.23 seconds
Results:
{}

Loading resulting layers
Algorithm 'Raster volume' finished
````
I do realise QGIS now has its own raster volume algorithm (which is better because it also reports the area, as well as the volume).  But I wonder if other Saga algorithms fail in the same way as this one?

**Comment by nyalldawson** [comment]
Unfortunately SAGA algorithms are a bit of a mixed bag. I think we should tag this one with the "known issues" flag to push people away from it...

**Comment by AlisterH** [comment]
But it was working in such a recent version.  You don't think whatever change has broken it is likely to have broken other algorithms too?
Actually, it would be good to check it is still broken in master, as I saw you reworked things to fix issues with the grass algorithms.  Unfortunately I can't run the osgeo4w installer here to check.

**Comment by nyalldawson** [comment]
I don't think anything has changed here -- this algorithm has always hidden the result. It's actually still in your log:

```
Grid system: 1; 61x 58y; 1781252.5x 5872344.5y
Grid: OUTPUT
Method: Count Only Below Base Level
Base Level: 5.000000



Grid Volume: Volume: 1873.700044

C:\PROGRA~1\QGIS3~1.4\bin>exit
Execution completed in 14.23 seconds
Results:
{}

Loading resulting layers
Algorithm 'Raster volume' finished
```

It's just buried in all the noise.

**Comment by AlisterH** [comment]
I think you're looking at the wrong log.  It is in the 3.4.4 log, but not in the 3.8.0 log.

**Comment by Zatooka** [comment]
For my part, I fully agree with the point of view of AlisterH. 
Creating new versions of QGIS should not mean disregarding Saga plugins still coming with these new versions.

Having said that, I have been making some preliminaty tests with the new SAGA raster surface volume that has been ported to a native QGIS  C++algorithm.
Really good.

Moreover, if this new native QGIS algorithm could be upgraded to propose choosing another  raster or even an 3D shapefile as BASE LEVEL, would make it terribly more powerful and popular.

Does this suggestion fall within the possibilities of evolution for the next QGIS versions?
Alternatively who to adress?

Thanks to all in advance.

**Comment by AlisterH** [comment]
Why can't you subtract the base layer from the other using the raster calculator, and then calculate the volumes? Create a processing model if you need to do it frequently.

**Comment by AlisterH** [comment]
That would be nice, but can't you just subtract the base layer from the other layer using the raster calculator and then calculate the volumes from the result?  Create a processing "model" if you need to do it frequently.

**Comment by Zatooka** [comment]
Your tip is very much appreciated.
It was just a suggestion for improvement regarding they were working on it.
Such an "all-in" native algortihm in C++ would be awesome for standard maritime and bathymetrical survey reporting jobs.
Indeed, for now,  I will set up a proceesing model.

PS/ I forgot to thank you for opening this thread. 
I had been trying the SAGA algorithm the whole week-end without any sucess!
As I was using QGIS 3.4.10, i.e; the last LTR version, I was convinced the problem was coming from my side .
Hopefully the research on the web returned your thread!
That allowed me to move forward and perform the volume calculations needed.
Thank you. It has been a great relief finding it!

**Comment by AlisterH** [comment]
So the saga algorithm isn't working in 3.4.10, either?  It seems that 3.4.4 (where it does work) bundles the same version of Saga as 3.8.x, so I guess it isn't an upstream problem.

**Comment by Zatooka** [comment]
Actually I had originally 3.4.8 on my computer. 
After all the failed trials of the SAGA  algorithm, I downloaded tha last LTR version (i.e.3.4.10), but SAGA r.volume was still not working (read not delivering a volume output though the algorithm seemed to run properly).
Hopefully I found your thread mentionning 3.4.4 was working and 3.8 had its own equivalent native algorithm now.

So I also conclude  something has happened after 3.4.4 and  the problem has been copied trough at least 3.4.10.
I have not tested other SAGA algorithms yet within 3.8 but this problem raises reasonable concerns.

Thank you.

**Comment by gioman** [comment]
If it does not work and it did it (and the offending change is in QGIS) then is a regression, as such it must be fixed asap especially on LTR.

**Comment by nyalldawson** [comment]
@gioman given that this algorithm never really worked (see https://github.com/qgis/QGIS/issues/17348), can we tag this algorithm as "known issues" and leave it at that?

**Comment by AlisterH** [comment]
> @gioman given that this algorithm never really worked...

???
It works in 3.4.4

Although if it is too much bother to fix, I personally wouldn't have any problem with you removing it, even if 3.4.4 was already an LTS.

**Comment by nyalldawson** [comment]
Well, not really... it was always confusing to users (hiding the actual value in amongst a bunch of debugging cruft), and of limited use in general because the value could not be used in models and outside of the algorithm.

That's what drove the development of the native QGIS version, as a direct way of fixing all the limitations with the SAGA algorithm.

I'm honestly reluctant to spend ANY time even looking into this one, given that at best that algorithm is confusing and frustrating for users to us, and we have a tool available in QGIS which already fixes all the issues with it.

**Comment by AlisterH** [comment]
For the record I've tested some more versions and it seems the breakage was between 3.4.5 and 3.4.6.  But I agree with Nyall - removing or disabling this algorithm wouldn't remove any functionality.  The only use case for this algorithm is someone mistrusting the native QGIS version, wanting to check that something else calculates the same value.

**Comment by Zatooka** [comment]
> 
> 
> Well, not really... it was always confusing to users (hiding the actual value in amongst a bunch of debugging cruft), and of limited use in general because the value could not be used in models and outside of the algorithm.
> 
> That's what drove the development of the native QGIS version, as a direct way of fixing all the limitations with the SAGA algorithm.
> 
> I'm honestly reluctant to spend ANY time even looking into this one, given that at best that algorithm is confusing and frustrating for users to us, and we have a tool available in QGIS which already fixes all the issues with it.

Time is indeed a precious good. As mentioned earleir in the thread, for me what really makes sense would be to spend some time on this new native QGIS algorithm.
By upgrading it to allow choose another raster or even an 3D shapefile as BASE LEVEL, would make it terribly more powerful and popular.

Does this suggestion fall within the possibilities of evolution for the next QGIS versions?

Thank you.
Cheers

**Comment by roya0045** [comment]
@Zatooka I would suggest you to make a feature request in this case.

**Comment by gioman** [comment]
> Well, not really... it was always confusing to users (hiding the actual value in amongst a bunch of debugging cruft), and of limited use in general because the value could not be used in models and outside of the algorithm.

Yeah I fully understand, but still the tool produced a valid output value, that was better than nothing. What I would like to understand is if the regression was caused by a necessary underlying change in processing, that makes "impossible" to go back (but if that is the case why it affects 3.4 and not only  >3.4?).

**Comment by Zatooka** [comment]
> 
> 
> @Zatooka I would suggest you to make a feature request in this case.

Hi roya0045.
Thank you very much for tip.
I am new to Github and therefore did not knwew about the way forward.
I will proceed to make a feature request.

Cheers,

**Comment by AlisterH** [comment]
> Well, not really... it was always confusing to users (hiding the actual value in amongst a bunch of debugging cruft), and of limited use in general because the value could not be used in models and outside of the algorithm.
> 
> That's what drove the development of the native QGIS version, as a direct way of fixing all the limitations with the SAGA algorithm.

Question: if I use the QGIS raster surface volume algorithm by itself, Volume, Pixel count and Area are output to the log.  If I use it in a model they aren't.  Wouldn't it make sense for all the normal algorithm output to be shown in the log?

**Comment by AlisterH** [comment]
Zatooka's feature request is at #31122.
I am adding some additional suggestions there that could be considered if someone does look at enhancing the QGIS volume algorithm..

**Comment by gioman** [comment]
Tested on QGIS 3.16 on Windows and Linux and the "Grid Volume" value shows again in the log.
