### ISSUE TITLE
Options dialog hogs CPU

### ISSUE THREAD

**Issue by AlisterH** [qgis/QGIS#30784]
In QGIS 3.x, when the Options dialog is open QGIS' processor usage (on a fast 8 processor system) sits between 8 and 12%.  If the machine is doing something else processor hungry then the options dialog can be quite unresponsive.  Is this behaviour expected and desirable?

It is not a problem with QGIS 2.x, and I think it may be related to the new search bar in the options dialog.  I guess it is pretty insignificant, since you wouldn't often use the options dialog, but it could be considered a regression...

Testing is on Windows 10.

**Comment by Pedro-Murteira** [comment]
@AlisterH I can't replicate this issue anymore, tested with an 8 cores CPU and windows 10. (QGIS 3.16.15 and 3.22.2).

**Comment by AlisterH** [comment]
Seems to be fixed
