### ISSUE TITLE
DB manager cannot load anymore a PostGIS layer that is not registered in the geometry_columns table

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#30787]
In DB Manager run a "create table" query without doing the casting for the geometry, i.e.

CREATE TABLE test as
  SELECT 
row_number() over () as gid,
    a.gid AS id,  
    b.gid AS id2,
    ST_MakeLine(a.geom, b.geom) AS geom
  FROM points1 a, points2 b

In QGIS 2.18:

as there was no casting the table/layer is shown (just) with a "?" icon, but it *can* be loaded in the QGIS project.

![Screenshot_20190718_100819](https://user-images.githubusercontent.com/1951107/61445030-7528f700-a944-11e9-94d2-60c8c2402b6a.png)

In QGIS 3 (tested master):

the table/layer is shown multiple times: with the "?" icon as also with the icons for points, lines and polygons (but of course the real geometry is only one of them). Moreover trying to add the layer in the project it returns an error.

![Screenshot_20190718_101409](https://user-images.githubusercontent.com/1951107/61445183-cc2ecc00-a944-11e9-817a-7f494f0e8391.png)

**Comment by m-kuhn** [comment]
What happens if you load one of the entries with a geometry type icon?
Cc @olivierdalang

**Comment by gioman** [comment]
> What happens if you load one of the entries with a geometry type icon?

@m-kuhn it only works if you choose (or guess) the correct geometry type.
From a user point of view is a clear step backwards: for tables not registered in the geometry_columns table the correct  behavior is the one we had in 2.18: show the layer/table with the "?" icon and allow to add it to the project (as they layer/table has really nothing wrong other than not being created doing the geometry casting in the query).

**Comment by m-kuhn** [comment]
What geometry type was it loaded as in 2.18?
It would seem that if it's able to determine the correct layer geometry type while loading it should also be able to list it like that in db manager?

**Comment by gioman** [comment]
> What geometry type was it loaded as in 2.18?

by clicking the "?" icon? > the correct one (so yes, QGIS 2.18 understands anyway what is the geometry)

> It would seem that if it's able to determine the correct layer geometry type while loading it should also be able to list it like that in db manager?

showing the "?" for tables not registers in the geometry_columns table is the correct thing to do. It is a reminder that formally is better to "fix" them. What is not right is to show such tables listed 4 times (and not loading them when clicking on the "?" icon).

**Comment by m-kuhn** [comment]
> by clicking the "?" icon? > the correct one (so yes, QGIS 2.18 understands anyway what is the geometry)

Do you know how it did do this?

From what I can see, the type of the column is "GEOMETRY" in this case, with no definition of the (line) content.
We recently looked into this and @olivierdalang and I concluded that in such a case we should follow the logic of the add layer dialog of postgres and force the user to select the proper type himself manually.

Alternatively, there would be the possibility to inspect the table contents, but that has some hard to answer questions like what to do if multiple geometry types are found inside or no data is inside or potentially requires a full scan with a performance impact.

Do you have a good proposal how to deal with that?

**Comment by gioman** [comment]
> From what I can see, the type of the column is "GEOMETRY" in this case, with no definition of the (line) content.
> We recently looked into this and @olivierdalang and I concluded that in such a case we should follow the logic of the add layer dialog of postgres and force the user to select the proper type himself manually.
> 
> Alternatively, there would be the possibility to inspect the table contents, but that has some hard to answer questions like what to do if multiple geometry types are found inside or no data is inside or potentially requires a full scan with a performance impact.
> 
> Do you have a good proposal how to deal with that?

@m-kuhn @olivierdalang the proposal is: LEAVE AT IT WAS ON 2.18

Scenario:
Polygon layer imported from a file bases vector
Polygon layer computed by query from the first one (by buffering) WIHTOUT casting
Point layer computed by query from the first one (by centroid) WIHTOUT casting

2.18

![Screenshot_20190727_113822](https://user-images.githubusercontent.com/1951107/61993462-13633e00-b064-11e9-8887-dd328afde1e6.png)

DB manager:
the buffered layer and the centroid one are shown just ONCE with the "?" icon and are fully loadable in the project

The browser does even better as it shows those layer just ONCE and it does even show the corret icon for the proper geometry

![Screenshot_20190727_114736](https://user-images.githubusercontent.com/1951107/61993495-6937e600-b064-11e9-8ca7-8d00512225ef.png)

The "Add PostGIS" layer dialog also works in an acceptable way as it shows those layers TWICE, once with their specific geometry and another time allowing the user to manually choose a geometry type

![Screenshot_20190727_113846](https://user-images.githubusercontent.com/1951107/61993509-abf9be00-b064-11e9-877c-2f89aed8d43a.png)


For the browser and the "Add PostGIS layer" dialogs it is the same for the NEW LTR:

![Screenshot_20190727_114134](https://user-images.githubusercontent.com/1951107/61993521-c469d880-b064-11e9-9192-51f796a24200.png)


Things has got BROKEN in DB Manager:


![Screenshot_20190727_114216](https://user-images.githubusercontent.com/1951107/61993526-dea3b680-b064-11e9-9f5b-398a33698d44.png)


each layer (from a query that has not had casting) is presented 4 times. Loading the one associated to the "?" icon does not work, and a user has to GUESS what is the right geometry because RDBMS are also to be used in multi-user contexts, correct? so a user is not mandated to know what type of geometry a layer is. Regardless of this last consideration showing 4 icons for one layer is confusing and a UX regression.

The only other scenario where it MAKES sense to show icons with different geometries for the same layer is when a layer/table has >1 geometry columns. Example for 2.18:

![Screenshot_20190727_115642](https://user-images.githubusercontent.com/1951107/61993567-a6e93e80-b065-11e9-945d-f5df7e90d3a3.png)

the mess it becomes in 3.4:

![Screenshot_20190727_115854](https://user-images.githubusercontent.com/1951107/61993588-f0398e00-b065-11e9-9afb-fe23072ae318.png)


so please... reinstate QGIS 2.18 way to work for DB Manager.

**Comment by olivierdalang** [comment]
IMO the new behaviour is not that wrong. If a table has a GEOMETRY column, even if it currently only contains POINTS, it should also be loadable as a LINESTRING or POLYGON layer, to allow you to work with yet-to-be-populated tables or tables that currently have only 1 type of geometry in a generic geometry column. I don't think using heuristics to determine the geometry type like what's done by the browser is a good idea in the DB manager, as it's a more technical tool.

If you really plan to use just one particular type of geometry, you definitely should define your column with that type instead.

But I agree showing one layer multiple times is confusing amd should be improved.
Maybe we could allow to pick the geometry type to be loaded using a combobox from the layers list, like in the "add postgis" dialog.
Or even better, have QGIS show the "choose layers" dialog with feature count when a generic GEOMETRY layer is loaded (like what's done for multi-layers datasources), so that we could just stick to the '?' layer.

I'm currently in vacation, but will have another look at this when I'm back (2nd week of august).

**Comment by gioman** [comment]
> IMO the new behaviour is not that wrong. If a table has a GEOMETRY column, even if it currently only contains POINTS, it should also be loadable as a LINESTRING or POLYGON layer, to allow you to work with yet-to-be-populated tables or tables that currently have only 1 type of geometry in a generic geometry column. I don't think using heuristics to determine the geometry type like what's done by the browser is a good idea in the DB manager, as it's a more technical tool.

@olivierdalang then again leave it as it was in 2.18, it will load the proper geometry anyway! If the table contains >1 type of geom in the same geom column that is a collection and we never supported them.



> If you really plan to use just one particular type of geometry, you definitely should define your column with that type instead.

there a TON of reasons to not do the casting while you are writing a lot of SQL queries. I don't say that is 100% right, I just say that there are a lot of reason (i.e. speed) and that should not make your life harder later, as 2.18 wans't.



> But I agree showing one layer multiple times is confusing amd should be improved.

it must return as it was. This made DB manager barely usable for who used it to interact with PostGIS (it affects also other datasorces?) by writing a lot of SQL queries, sharing results, etc.

> Or even better, have QGIS show the "choose layers" dialog with feature count when a generic GEOMETRY layer is loaded (like what's done for multi-layers datasources), so that we could just stick to the '?' layer.

again... no. If I was the guy who wrote the query I should know what is the type of geometry (but maybe not after weeks/months), but if I'm working in a multi user environment then the other could not know anything about the type of geometry. QGS 2.18 did the right thing, it loaded the layer choosing automatically the geom type.

**Comment by olivierdalang** [comment]
We've understood you're unhappy with the change, now please also try to understand that the change wasn't made specifically to annoy you... Please read the original PR to have some context : #30173, and let's move past the "revert back to 2.18" stance and work together constructively on a solution that accomodates everybody's needs.

> If the table contains >1 type of geom in the same geom column that is a collection and we never supported them.

Maybe you're slightly misunderstanding the GEOMETRY column type (which may explain why we see things differently on the implementation).  A GEOMETRY column allows to store any type of geometry, and is precisely there to allow storing geometries of different types in the same column. That doesn't make it a COLLECTION, which is about storing multiple and possibly heterogeneous geometry types in ONE row (you can indeed store a COLLECTION in a GEOMETRY column, but just like POINT or any other geometry type).

These type of tables are supported by QGIS, precisely by loading the geometries as one of POINT, LINESTRING or POLYGON.

To me it seems your use case, where you seem to use GEOMETRY to store homogeneous geometry types, mainly to have a shorter table creation query, isn't really the typical use case for the GEOMETRY type. Assuming everybody does it this way would prevent using the DB manager with otherwise very valid use cases of GEOMETRY columns.

**Comment by gioman** [comment]
> We've understood you're unhappy with the change, now please also try to understand that the change wasn't made specifically to annoy you... Please read the original PR to have some context : #30173, and let's move past the "revert back to 2.18" stance and work together constructively on a solution that accomodates everybody's needs.

well it is certainly annoying me and many others who rely(ed) on DB Manager as a daily driver to interact with PostGIS and write a lot of SQL, explore results etc. As it is now it is BARELY usable.



> Maybe you're slightly misunderstanding the GEOMETRY column type (which may explain why we see things differently on the implementation). A GEOMETRY column allows to store any type of geometry, and is precisely there to allow storing geometries of different types in the same column. That doesn't make it a COLLECTION, which is about storing multiple and possibly heterogeneous geometry types in ONE row (you can indeed store a COLLECTION in a GEOMETRY column, but just like POINT or any other geometry type).
> 
> These type of tables are supported by QGIS, precisely by loading the geometries as one of POINT, LINESTRING or POLYGON.

I know perfectly what you are talking about, don't worry.

> To me it seems your use case, where you seem to use GEOMETRY to store homogeneous geometry types, mainly to have a shorter table creation query, isn't really the typical use case for the GEOMETRY type. Assuming everybody does it this way would prevent using the DB manager with otherwise very valid use cases of GEOMETRY columns.

I don't agree, the vast majority of users uses to store a specific geometry type in one specific geometry column. I challenge anyone to demonstrate de contrary. DB manager should not be broken then for the majority of users, so a better solution must be found to accommodate anyone, but in the meantime gave us back DB manager as it was in the old LTR.

Thanks for understanding users.

**Comment by pcav** [comment]
Can't we suggest users to run `SELECT PopulateGeometryColumns()`?

**Comment by m-kuhn** [comment]
> Can't we suggest users to run SELECT PopulateGeometryColumns()?

Like: when you select a table with GEOMETRY type / "?" -> open a dialog that allows the user to load this table with a configurable geometry type or to run `PopulateGeometryColumns`?

**Comment by pcav** [comment]
Yes

**Comment by gioman** [comment]
> Like: when you select a table with GEOMETRY type / "?" -> open a dialog that allows the user to load this table with a configurable geometry type or to run `PopulateGeometryColumns`?

This is if the user knows the geometry type. In a multi users environment the user that is trying to add the table could not know anything about it and could also not have the permissions to do what you suggest. 

This disrupting change had take place in 3.4.8 or 3.4.10. finalizing my check now.

For such tables, I tell it again, the right thing was/IS to > show only the "?" icon and allow to load it without having the user to take any guessing game. 

The case of a table with a geometry column not registered and containing mixed type pf geometries must be addressed in a different/better way than the patch that caused this snafu.

Moreover the aforementioned patch should have never been applied to LTR: the patch did not fixed ANY bug, on the other add tried to add a functionality, which is not allowed in LTRs.

**Comment by gioman** [comment]
The regression was introduced in 3.4.9. Will try have a look and make a PR to revert it.

**Comment by pcav** [comment]
Disrupting an LTR is obviously not good. Can't this be left for 3.6+?
My suggestion was: warn the user, in case of generic GEOMETRY columns, that this situation is not optimal, and suggest to run `PopulateGeometryColumns` straight away. If he has write permission then a simple button could help. Anyway, these are invasive changes, that should be done outside an LTR.

**Comment by m-kuhn** [comment]
I would suggest we do the following:

 - let's first wait for the finished analysis of @gioman . So far it's not clear, what caused this problem
 - if it turns out to have been https://github.com/qgis/QGIS/pull/30173 let's review what went wrong there, #30173 fixes an issue for our client, if it turns out to have unintentionally caused side effects I'm sure we can find alternatives

**Comment by m-kuhn** [comment]
@gioman #30787 should fix this odd behavior. Can you confirm?

**Comment by gioman** [comment]
> @gioman #30787 should fix this odd behavior. Can you confirm?

will check asap

**Comment by gioman** [comment]
> @gioman #30995 should fix this odd behavior. Can you confirm?

it solves just partially, let me explain:

it seems that by removing that line now the user can double click the "?" icon and the layer will be added (as it was pre 3.4.9)

BUT

the very same layer is still represented ALSO with the point, line and polygon icons, and this is VERY cumbersome for the average user (we don't want them to play a guessing game, and if they choose the wrong type they get a confusing error message).

Moreover if the table/layer has additional geometry columns, the layer will show "n" more times, one time for each additional geometry column, with no way to distinguish what represent an additional geometry column and what else.

My proposal is the following:

make DB manager behave as it was pre QGIS 3.4.9 (this is mandatory for LTR IMHO, as it was something that worked fine and that was broken) then for a geometry column containing mixed type of geometries do the following:

when the user double click the "?" icon in DB manager show a pop up asking the user what type of geometries he/she wants to load.

Also if we want to make DB manager better: beside the message "There is no entry in geometry_columns!" a link/button can be added and when clicking the table will be registered in the "geometry_columns" view (and of course this should only show case the user being used has the proper permissions to do so).

**Comment by m-kuhn** [comment]
@gioman thanks a lot for the review.

I'm currently cross checking our customer's issues again.

**Comment by olivierdalang** [comment]
> when the user double click the "?" icon in DB manager show a pop up asking the user what type of geometries he/she wants to load.

We'd also have to support drag&drop on the map canvas, which is slightly trickier. Currently, this is implemented by using mime data of the list element, so the drop is managed completely outside of the db manager's code. One way to deal with it was as per my suggestion above (showing the "select layers" dialog like what's done for multi-layers datasources).

**Comment by m-kuhn** [comment]
@gioman Here's a minimal example to reproduce the issue, a table without explicit geometry type and some line strings and circular line strings.

```
CREATE TABLE zone (
    id integer,
    the_geom public.geometry(GeometryZ,2056)
);

INSERT INTO zone (id, the_geom)
VALUES (
(1, '01020000A008080000020000008716D9DEE39D44419CC42010C8A533410000000000000000D122DBD9039E44419EEFA74600A633410000000000000000'),
(2, '01080000A00808000003000000FED478E950A044415839B4884B9A334100000000000000008B41E3474CA044416F78BEA94C9A3341000000000000000021B072B847A04441BA490CA24E9A33410000000000000000')
)
```

**Comment by m-kuhn** [comment]
@gioman can you confirm the latest patch fixes the issue?

**Comment by gioman** [comment]
> @gioman can you confirm the latest patch fixes the issue?

checking now

**Comment by gioman** [comment]
> @gioman can you confirm the latest patch fixes the issue?

@m-kuhn I'm testing against code revision https://github.com/qgis/QGIS/commit/b21b2573be I assume that this included the patch

As I said here

https://github.com/qgis/QGIS/issues/30787#issuecomment-516589419

this patch leave things not really as they should be from a user point if view.

*) when creating a spatial table without casting the resulting layer is shown 4 times(!) rather than just 1, with the "?" icon

*) in a multi user environment some person may not know anything about this layer, so he/she is left scratching the head about why the layer is shown multiple time

*) double clicking on the "?" icon and on the icon that correspond to the right geometry work, at least

*) double clicking on the icons that do NOT correspond to the right geometry will not return an error, instead they will load in the project a layer that is not functional


![Screenshot_20190806_140911](https://user-images.githubusercontent.com/1951107/62542534-dcefa500-b853-11e9-8c09-5866b04f1c78.png)


*) As it is  now things are *very* confused when multiple geometry columns are used. Example:

![Screenshot_20190806_141300](https://user-images.githubusercontent.com/1951107/62542825-8171e700-b854-11e9-95ee-7cb1e0b4dba0.png)

"aaa1" are the centroids derived from "test1", without casting. "aaa1" has also a second geometry column of type polygon for some centroid buffer.

So... what is the icon should I click to load the centroid buffers? the first one representing polygons? the second one?


Moreover it seems to me that https://github.com/qgis/QGIS/pull/31047 has not been backported to 3.4, correct? of confirmed I think that on our LTR there is still a very bad regression, and I argue that there we should revert db manager as if was on 3.4.8 and earlier.

**Comment by m-kuhn** [comment]
Please test on 3.4, an extended version has been integrated there.

**Comment by m-kuhn** [comment]
@gioman feel free to also give a positive feedback if it works :)

**Comment by gioman** [comment]
> @gioman feel free to also give a positive feedback if it works :)

Hi @m-kuhn I tried QGIS 3.4 on Ubuntu from the ltr-nightly repo, I assume that it includes your latest code. If yes then it works as I would expect (a table not registered in the geometry_columns table is only shown 1 time with the "?" icon, and can be added to the project), thanks! Will the same approach be used on > 3.4?

**Comment by m-kuhn** [comment]
It's already like this on 3.8 too.
3.10 is the first release ever to allow loading mixed content tables and empty tables with geometry type from the db manager.

**Comment by pcav** [comment]
Great news, thanks @m-kuhn
