### ISSUE TITLE
QGIS 3.8 crash during 'Check geometries'

### ISSUE THREAD

**Issue by stefanon** [qgis/QGIS#30798]
Crash of QGIS 3.8 during a long 'check geometries' on a large multipolygon shape file, with more than 300K features.
Info in the program crash dialog:

Crash ID: d57d6039df5ea6748654f3ec68c8069bf576bd45

Stack Trace

QgsGeometryCollection::vertexAt :
QgsAbstractGeometry::centroid :
QgsGeometryDuplicateCheck::collectErrors :
QgsGeometryChecker::runCheck :
QgsGeometryChecker::runCheck :
QgsGeometrySnapper::processFeature :
QgsInternalGeometrySnapper::operator= :
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.8.0-Zanzibar
QGIS code revision: 11aff65f10
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by gioman** [comment]
@stefanon any chance you can add/link the dataset?

**Comment by stefanon** [comment]
I'm sorry but I can't share the full dataset. Anyway doing again the procedure with QGIS for Linux worked without problems.

**Comment by gioman** [comment]
> I'm sorry but I can't share the full dataset

does it crash with a subset?

**Comment by m-kuhn** [comment]
Duplicate of #29470

**Comment by m-kuhn** [comment]
@stefanon can you check the fix with one of the next nightly builds?
I cannot reproduce it here, but I'm confident it has been solved.
