### ISSUE TITLE
QGIS 3.4 & 3.8 keeps crashing when saving shapefile alterations on Windows 10

### ISSUE THREAD

**Issue by lidarlady** [qgis/QGIS#30790]
**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by lidarlady** [comment]
## User Feedback

Saving a shapefile layers addition. Constantly doing this in both the "stable" Q3.4 and this one "Zanzibar". Have uninstalled and reinstalled a number of times but still a problem 

## Report Details

*Crash ID*: b790ccc28e70cdcc6522e57fdd8c304f81bffb8d


*Stack Trace*
<pre>
QgsVertexEditorModel::data :
QModelIndex::data :
QStyledItemDelegate::initStyleOption :
QStyledItemDelegate::paint :
QTableView::doItemsLayout :
QTableView::paintEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::drawWidget :
QApplication::windowIcon :
QWidget::event :
QgisApp::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::scrollRect :
QWidgetPrivate::invalidateBuffer_resizeHelper :
QWidget::repaint :
QWidget::repaint :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>


*QGIS Info*
QGIS Version: 3.8.0-Zanzibar
QGIS code revision: 11aff65f10
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1



*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by gioman** [comment]
@lidarlady please try with a new QGIS profile and no 3rd party plugins installed.

**Comment by lidarlady** [comment]
Thanks but I am not sure what you meant by 3rd parties... have only got
what was installed .also what do you mean by new profile... uninstalled and
then reinstalled on official site

**Comment by gioman** [comment]
> Thanks but I am not sure what you meant by 3rd parties

any plugin that does not comes by default in QGIS and that can be installed, for example, with the plugin manager.

Re-installing the software do not erase QGIS user profiles, you must follow settings>user profiles>new profile

**Comment by lidarlady** [comment]
Ah many thanks I will give that a try Thanks for such a speedy response

**Comment by nirvn** [comment]
@lidarlady , I *think* this will be fixed in upcoming LTR 3.4.10 and 3.8.1 releases (out in a few days). Can you give it a try upon release and report back? If it's still crashing, please provide a list of steps to reproduce the crasher (which, on the basis of the stack you provided above must involve using the vertex tool and saving new additions while the tool is still active).

**Comment by lidarlady** [comment]
Hi Mathieu  I have been working this morning on the LTR3.4.10 and am very
pleased to report that so far it has not crashed. When I downloaded it I
also logged in as new profile as you suggested. So this seems to have
worked *thank you very much*.   BUT.........I am unable to down load a
couple of plugins which I use constantly - Open Layers plugin and the
QField plugin. They both load in 3.8.0 but no luck in the 3.4.10 version
Have attached message that comes up.
Thank you for your help and all the hard work that goes into this
