### ISSUE TITLE
Unable to build QGIS due to undefined QgsLabelingGui

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#30792]
Trying to build QGIS from source (b41f8e03) on bionic it fails with the following

> FAILED: output/lib/libqgis_app.so.3.9.0 

followed by a long call of commands I don't think it's worth reporting here (is it?) that finished with
>src/app/CMakeFiles/qgis_app.dir/qgslabelingwidget.cpp.o : Dans la fonction « QgsLabelingWidget::labelModeChanged(int) » :
/media/TRAVAIL/dev/github/QGIS/build-ninja/../src/app/qgslabelingwidget.cpp:193 : référence indéfinie vers « QgsLabelingGui::QgsLabelingGui(QgsVectorLayer*, QgsMapCanvas*, QgsPalLayerSettings const&, QWidget*) »
src/app/CMakeFiles/qgis_app.dir/qgsrulebasedlabelingwidget.cpp.o : Dans la fonction « QgsLabelingRulePropsWidget::QgsLabelingRulePropsWidget(QgsRuleBasedLabeling::Rule*, QgsVectorLayer*, QWidget*, QgsMapCanvas*) » :
/media/TRAVAIL/dev/github/QGIS/build-ninja/../src/app/qgsrulebasedlabelingwidget.cpp:618 : référence indéfinie vers « QgsLabelingGui::QgsLabelingGui(QgsVectorLayer*, QgsMapCanvas*, QgsPalLayerSettings const&, QWidget*) »
collect2: error: ld returned 1 exit status
[18/1149] Building CXX object src/plugins/geometry_checker...es/geometrycheckerplugin.dir/qgsgeometrycheckfactory.cpp.o
ninja: build stopped: subcommand failed.

**Comment by nyalldawson** [comment]
Have you tried a clean build? Wipe away your previous build folder and retry

**Comment by DelazJ** [comment]
yes. Cleared and launched it right after I sent the report and unfortunately it also fails.

**Comment by stev-0** [comment]
This might not be helpful, but I can build master on bionic, albeit with compiled libs, not system ones, although not sure why that would make a difference here.

**Comment by DelazJ** [comment]
OK, found the culprit.
Because github desktop has some nice features I'm used to, I sometimes switch to Windows to do some changes/analysis on my branches. But since i not yet found the right settings to manage lf/crlf between the two platforms, I often ended with lot of files (whole repo?) being placed in an unstaged state in the branch because git detected changes on them. Removing the diff from the branch makes the build successful again.
Sorry for the noise. And thanks for suggestions.
