### ISSUE TITLE
QGIS Server - WMS Request GetPrint fails with ATLAS_PK

### ISSUE THREAD

**Issue by zeusgonzalezfernandez** [qgis/QGIS#30817]
I'm a junior developer and I'm working on a project trying to refresh an old GISWEB, to do so i chose QWC2+QGISServer.

Actual setup is:<br>
Debian 10, Apache2, QGIS-Server 3.8, using .shp as layers... the QWC2 works fine, WMS works fine, i can print some templates, print png, etc...

The issue is that I'm trying to use the &ATLAS_PK (implemented in [QGIS Server 3.6](https://github.com/qgis/QGIS/commit/21e3adfbcac4ffa339b28a4fb5fefc3a704bd2fb) and I'm getting an annoying "Internal Server Error". When I use "&ATLAS_PK=1" or "&ATLAS_PK=1, 2, 3", log says:

    "CRITICAL Server: An error occurred during the Atlas print
    WARNING: finish() called twice"

As I read in the code [here](https://github.com/qgis/QGIS/blob/master/src/server/services/wms/qgswmsrenderer.cpp) it could be caused by 2 things :

	"if ( pkIndexes.size() < 1 )
        {
          throw QgsException( QStringLiteral( "An error occurred during the Atlas print" ) );
        }"
or:

	"QString errorString;
        atlas->setFilterExpression( filterString, errorString );
        if ( !errorString.isEmpty() )
        {
          throw QgsException( QStringLiteral( "An error occurred during the Atlas print" ) );
        }"

I can't determine which one is causing it.

If I try to use "&ATLAS_PK=*" it seems to work but I get "timed out" because I have like 4k features to print (I already changed the feature limit in QGIS Server conf). I'm going to try with a layer with less features as soon as I can and post updates.

GetProjectSettings WMS request returns that I have 2 templates both with atlas enabled.

There's not much [documentation](https://docs.qgis.org/testing/en/docs/user_manual/working_with_ogc/server/services.html) to read about, as it's a new feature...

**Comment by gioman** [comment]
Better also ask in the QGIS developers mailing list.

**Comment by zeusgonzalezfernandez** [comment]
UPDATE:
I tried to use atlas_pk with postgis data instead of .shp data and it works perfectly. if I have time I'll try to check if it's a problem with the .shp data or with the implementation of the atlas_pk that doesn't allow the use of .shp data.

**Comment by TodoInTX** [comment]
Hello, 

I'm getting the exact same thing except I'm using GeoPackage for the features with the atlas_pks.

```
15:45:41 INFO Server[10244]: ******************** New request ***************
15:45:41 INFO Server[10244]: SERVER_NAME: 127.0.0.1
15:45:41 INFO Server[10244]: REQUEST_URI: /qgis/qgis_mapserv.fcgi.exe?SERVICE=WMS&REQUEST=GetPrint&SRS=EPSG:2278&TEMPLATE=PrecinctGroups&atlas_pk=1&FORMAT=pdf
15:45:41 INFO Server[10244]: REMOTE_ADDR: 127.0.0.1
15:45:41 INFO Server[10244]: HTTP_USER_AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
15:45:41 WARNING [10244]: formatString is: pdf
15:45:41 INFO Server[10244]: ATLAS_PK:1
15:45:41 INFO Server[10244]: FORMAT:pdf
15:45:41 INFO Server[10244]: REQUEST:GetPrint
15:45:41 INFO Server[10244]: SERVICE:WMS
15:45:41 INFO Server[10244]: SRS:EPSG:2278
15:45:41 INFO Server[10244]: TEMPLATE:PrecinctGroups
15:45:41 INFO Server[10244]: WMS Request parameters:
15:45:41 INFO Server[10244]:  - SRS : EPSG:2278
15:45:41 INFO Server[10244]:  - FORMAT : pdf
15:45:41 INFO Server[10244]:  - TEMPLATE : PrecinctGroups
15:45:41 INFO Server[10244]:  - ATLAS_PK : 1
15:45:41 CRITICAL Server[10244]: An error occurred during the Atlas print
15:45:41 WARNING [10244]: finish() called twice
15:45:41 INFO Server[10244]: Request finished in 222 ms

```
If I provide ATLAS_PK=*, all pages are rendered.  If I omit ATLAS_PK no features are rendered.

[map_capabilities.xml.txt](https://github.com/qgis/QGIS/files/3531892/map_capabilities.xml.txt)

**Comment by elpaso** [comment]
Can someone please attach a test project and data?

**Comment by TodoInTX** [comment]
Here is a project and data that generates the error shown above.

"15:45:41 CRITICAL Server[10244]: An error occurred during the Atlas print
15:45:41 WARNING [10244]: finish() called twice"

[PrecinctGroups30817.zip](https://github.com/qgis/QGIS/files/4123638/PrecinctGroups30817.zip)

**Comment by elpaso** [comment]
@TodoInTX thank you for the test case, I tested it with latest master and I've found no issues, these are my test calls:

PDF:
```
http://localhost:8000/?SERVICE=WMS&VERSION=1.3.0&ATLAS_PK=1,2,3&TEMPLATE=PrecinctGroups&REQUEST=GetPrint&BBOX=29.11277300000000068,-98.80763199999999813,29.76128800000000041,-98.11435000000000173&CRS=EPSG:4326&WIDTH=1754&HEIGHT=1641&LAYERS=Active%20Group&STYLES=&FORMAT=application/pdf&DPI=192&MAP_RESOLUTION=192&FORMAT_OPTIONS=dpi:192
```

JPG:
```
http://localhost:8000/?SERVICE=WMS&VERSION=1.3.0&ATLAS_PK=1&TEMPLATE=PrecinctGroups&REQUEST=GetPrint&BBOX=29.11277300000000068,-98.80763199999999813,29.76128800000000041,-98.11435000000000173&CRS=EPSG:4326&WIDTH=1754&HEIGHT=1641&LAYERS=Active%20Group&STYLES=&FORMAT=image/jpeg&DPI=192&MAP_RESOLUTION=192&FORMAT_OPTIONS=dpi:192
```

Would you be able to test the latest master builds?

**Comment by TodoInTX** [comment]
Confirmed, this error does not exist on qgis-server 3.12.0

**Comment by gioman** [comment]
> Confirmed, this error does not exist on qgis-server 3.12.0

closing? @elpaso

**Comment by elpaso** [comment]
I'm looking into this.
