### ISSUE TITLE
QGIS 3.4.9: Unable to export a raster layer through "Save As..." menu

### ISSUE THREAD

**Issue by jarickkk** [qgis/QGIS#30814]
I reproduced this bug in clean **QGIS 3.4.9**  profiles on macOS 10.14.5 (Mojave) and Windows 10 x64.

Here is a GeoTiff I work with: [19 MB](https://www.dropbox.com/s/s18pf6chif62rlp/raster_bug.tif?dl=0). The same happens for other rasters I tried.

1. Right click on a raster layer in the Layers panel: `Export --> Save As...`
2. "Raw Data" or "Rendered Image" is not important
2. Fill in file name
3. Click "OK"
4. I expect a new raster layer to be saved in the defined location, but nothing happens. The "Save As" window remains open and nothing is frozen, but it doesn't react on "OK" and "Cancel" buttons. At the same time you can edit parameters, interact with options. The only way to close this window is to click on close "x" icon at the top corner of a window.

<img width="866" alt="Screenshot 2019-07-19 at 10 27 23" src="https://user-images.githubusercontent.com/18553297/61517473-0022f380-aa10-11e9-835b-7f5adbb71991.png">

**Comment by nyalldawson** [comment]
This is already fixed for 3.4.10
