### ISSUE TITLE
Make GRS/Datum Transformation Window more like CRS Transformation Window

### ISSUE THREAD

**Issue by Saijin-Naib** [qgis/QGIS#30826]
**Feature description.**
I'd like to see the Datum Transformation window fall more in line with the CRS transformation window, where a graphical preview of the extent of the CRS/GRS would be shown.

Furthermore, I'd like to at least see the layer name somewhere in this window, as well. Hard to tell what layer is being transformed as it currently operates.

**Additional context**

See image below for current experience in QGIS 3.8.0
![Annotation 2019-07-08 094030](https://user-images.githubusercontent.com/19295950/61565098-0633c700-aa46-11e9-99c5-a86cc6039a43.png)

**Comment by DelazJ** [comment]
#30559 should fix the first part of the request
> Furthermore, I'd like to at least see the layer name somewhere in this window, as well. Hard to tell what layer is being transformed as it currently operates.

Agreed.

**Comment by nyalldawson** [comment]
The preview bounds was implemented for 3.8.1.

**Comment by DelazJ** [comment]
Thanks @nyalldawson for the fix

**Comment by Saijin-Naib** [comment]
Seriously, great boost to usability. Thanks, Nyall.
