### ISSUE TITLE
Add Specific Geopackage layer as a input to an algorithm in graphical modeler 

### ISSUE THREAD

**Issue by baswein** [qgis/QGIS#30827]
**Feature description.**

Thanks everyone for this amazing program. I found a small gap that I think would be useful as geopackage becomes the default file type. I have a geopackage layer that I want to always be used in an algorithm in the QGIS 3.8 graphical modeler. When I use the triple dots to navigate to the geopackage it doesn't give me the option to choose a layer in the geopackage. Ideally this would work like it does in other qgis situations where it asks for the layer after I choose a geopackage and then the file path would include the layer name or the graphical modeler would use the QGIS browser that allows be to choose gpkg layers.  In the example screenshot I want to use the layer AOI_Poly2 from the geopackage AOI as the mask layer. It does work but it chooses the first(?) polygon layer in the gpkg (AOI_poly). I have tried appending "|layername=AOI_poly2" to the file path but the dialog won't let me save. Allowing to manual append the layer would be a stop gap solution.  Thanks

**Additional context**

See my stack exchange question here: https://gis.stackexchange.com/questions/329294/adding-a-geopackage-layer-as-a-hardwired-input-to-an-algorithm-in-the-qgis-graph
May be related to https://github.com/qgis/QGIS/issues/28770
![image](https://user-images.githubusercontent.com/15817745/61565233-6e82a880-aa46-11e9-9a68-f0d27ce4b1e7.png)

**Comment by nyalldawson** [comment]
Not an issue in 3.14

**Comment by baswein** [comment]
Thanks!
I assume that this was part of the processing modeler crowd funding campaign. Thanks to everyone who funded that!

**Comment by dbartecchi** [comment]
I can’t find any reference to this in the changelog or QGIS documentation for 3.14. It’s also not clear how this works from within the graphic modeler in 3.14. Can kindly you explain how to select specific layers within a geopackage?

**Comment by baswein** [comment]
I believe there is now a choice when you have the input set as a value to select a file or browse for layers.  
![image](https://user-images.githubusercontent.com/15817745/92165082-7cd78380-ee04-11ea-9614-d1603d9174ff.png)
This seems to only be available for vector layers. Now that Geopackages also have rasters it might be nice to have them available as well.

**Comment by dbartecchi** [comment]
Ah yes! That must be the problem as I'm trying to select specific raster layers within a geopackage using the zonal statistics algorithm. Can this be added as a feature request?

**Comment by baswein** [comment]
Seems like it makes sense to add it as a feature request. Would you like to do that?  The workaround here might work: https://gis.stackexchange.com/questions/329294/adding-a-geopackage-layer-as-a-hardwired-input-to-an-algorithm-in-the-qgis-graph.

**Comment by dbartecchi** [comment]
Thanks for the workaround. I just submitted a request for this here https://github.com/qgis/QGIS/issues/38607
