### ISSUE TITLE
Cannot load pictures anymore in custom forms

### ISSUE THREAD

**Issue by M-Rick** [qgis/QGIS#30833]
Since QGIS version 3, when creating a custom form with QT Creator, pictures won't be shown anymore.
Until QGIS 2.18 it worked perfectly well.
A project open in QGIS 2.18 displays perfectly the pictures.
In QT Creator / QT Designer, create a new form using a QWidget using the same name of the picture field in QGIS and a QLabel to display the picture. In QGIS, this field must be set as a photo field in the fields parameters.

The QGIS project with the QT Designer project.
[Archive.zip](https://github.com/qgis/QGIS/files/3413553/Archive.zip)

**Fiels parameters - field set as a photo** 
![Capture d’écran 2019-07-20 à 13 33 46](https://user-images.githubusercontent.com/2520948/61578185-41400400-aaf3-11e9-8a0f-2ce4355f9c8e.png)

**Test 1 - QWidget and QLabel displayed in QGIS 2.18** 
![Capture d’écran 2019-07-20 à 13 31 03](https://user-images.githubusercontent.com/2520948/61578155-bbbc5400-aaf2-11e9-879a-9bfc8c3762eb.png)

**Test 2 - QWidget and QLabel from a calculation field displayed in QGIS 2.18** 
![Capture d’écran 2019-07-20 à 13 31 30](https://user-images.githubusercontent.com/2520948/61578183-3e451380-aaf3-11e9-9e0e-d942e1ffdbdd.png)

**Test 3 - QWidget and QLabel from a calculation field using a QGrid displayed in QGIS 2.18** 
![Capture d’écran 2019-07-20 à 13 31 31](https://user-images.githubusercontent.com/2520948/61578204-8a905380-aaf3-11e9-858a-38406a362ca2.png)

**Now same project open in QGIS 3 …**
The form window doesn't even respect the defined size from the field parameters.
![Capture d’écran 2019-07-20 à 13 33 46](https://user-images.githubusercontent.com/2520948/61578222-d511d000-aaf3-11e9-8605-e627746659a8.png)

![Capture d’écran 2019-07-20 à 13 39 21](https://user-images.githubusercontent.com/2520948/61578226-e35fec00-aaf3-11e9-8814-b512e561e678.png)

![Capture d’écran 2019-07-20 à 13 39 28](https://user-images.githubusercontent.com/2520948/61578230-ed81ea80-aaf3-11e9-8d6f-6acc611b2304.png)

![Capture d’écran 2019-07-20 à 13 43 13](https://user-images.githubusercontent.com/2520948/61578266-62edbb00-aaf4-11e9-8b09-94db771e591e.png)

**Comment by M-Rick** [comment]
The QGIS project with the QT Designer project.
[Archive.zip](https://github.com/qgis/QGIS/files/3413553/Archive.zip)

**Comment by m-kuhn** [comment]
Which QGIS version did you test with?

With which version is the following screenshot taken?

> ![](https://user-images.githubusercontent.com/2520948/61578222-d511d000-aaf3-11e9-8605-e627746659a8.png)

**Comment by M-Rick** [comment]
MacOS 3.8.0-Zanzibar 11aff65f10

Windows 3.6.2-Noosa 656500e0c4
![Capture d’écran 2019-07-20 à 15 53 06](https://user-images.githubusercontent.com/2520948/61579651-570bf400-ab08-11e9-944f-f5a3a8ed4677.png)

Linux 3.6.2-Noosa 656500e
![Capture d’écran 2019-07-20 à 16 04 32](https://user-images.githubusercontent.com/2520948/61579652-5a9f7b00-ab08-11e9-9483-3a5a14025c51.png)

**Comment by gioman** [comment]
While having  a look at the attached sample project I got a reminder that this https://github.com/qgis/QGIS/issues/26948 regression has not been fixed yet apparently

**Comment by m-kuhn** [comment]
@M-Rick The interesting screenshot is explicitly the one from the vector layer properties.

**Comment by M-Rick** [comment]
@m-kuhn 
If you click over the picture to zoom, you have the version on the title bar: 2.18.28 😉 

But this it with 3.8, it didn't upload or I forgot it. The settings are inherited from the project.
![Capture d’écran 2019-07-21 à 15 44 21](https://user-images.githubusercontent.com/2520948/61592071-6eadb000-abce-11e9-8f1d-27fdc398acbb.png)

**Comment by m-kuhn** [comment]
In QtDesigner, there should be a QgsExternalResourceWidget which can be used instead of QLabel, do you confirm?

**Comment by M-Rick** [comment]
No I don't. There is no QgsExternalResourceWidget but still QLabel in QtDesigner or QtCreator in Qt5.
I don't see this QgsExternalResourceWidget.

**Comment by m-kuhn** [comment]
Did you try with the QtDesigner installed from OSGEO4W on Windows?

**Comment by M-Rick** [comment]
I use the official Qt build for MacOS.

**Comment by m-kuhn** [comment]
Not sure if there are problems with custom widgets (CC @PeterPetrik / @3nids )

**Comment by 3nids** [comment]
There is no easy way currently for custom widgets on Mac as far as I know.
I am not sure if it's possible to link the custom widget library (is it even compiled?) from the standalone app to Qt Designer as there might be some different version of Qt libraries under the hood.

**Comment by M-Rick** [comment]
But this widget won't load the picture. What I am speaking about is displaying a picture. This widget is to load a file. There are many ways to store a path in a field and it can be done other ways. It won't help to display the picture in a Label field anyway.
Plus it will quite a lot of work to modify all the form already working out of the box just to upgrade to QGIS3… And this regression haven't been documented.

**Comment by 3nids** [comment]
Yes the external resource widget is able to display a picture.
Your layer doesn't seem to have that many fields, it might be a good opportunity to switch to using drag'n'drop form editor rather than custom UI form.

Regarding the issue you mentionned, photo field has indeed been dropped in favor of external resource widget. This would only affect custom forms. I *think* it would work if your widget under it was a widget and not a label (I am not sure). I believe this was a deliberated choice, but documentation is indeed lacking.

**Comment by M-Rick** [comment]
I update this post. I made a simple form just adding a QgsExternalResourceWidget from QtDesigner in Windows.

The widget isn't even loaded.

I'm made the test with QGIS 3.10.5

![Capture d’écran 2020-04-25 à 13 26 25](https://user-images.githubusercontent.com/2520948/80278660-820b2000-86f8-11ea-9f5b-ce8fff73560b.png)

![Capture d’écran 2020-04-25 à 13 26 39](https://user-images.githubusercontent.com/2520948/80278662-86373d80-86f8-11ea-9a5b-ab57efb6e8bf.png)

I didn't find a way to load pictures anymore in Qt custom forms.

**Comment by PeterPetrik** [comment]
QtDesigner is now bundled in the MacOS, fixed in 
https://github.com/qgis/QGIS-Mac-Packager/issues/3

you can test in nightly builds 
https://qgis.org/downloads/macos/nightly2/qgis_nightly2_master_20200917_044804.dmg 

and open with `open /Application/QGIS.app/Contents/MacOS/Designer.app/`
