### ISSUE TITLE
Attribute table opens as the wrong/outdated process

### ISSUE THREAD

**Issue by ghost** [qgis/QGIS#30843]
**Describe the bug**
The attribute table opens in a separate process.  The properties of the process point to the QGIS 3.4 folder/executable even though it is not installed on the system.

**How to Reproduce**
Open an attribute table
The icon appears on the taskbar (Empty Default Windows Icon)
Click on the properties of the process.
Note that it show QGIS 3.4 even when only 3.8 is installed

**QGIS and OS versions**

QGIS version
3.8.1-Zanzibar
QGIS code revision
dcd95cc648
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
2.4.1
Running against GDAL/OGR
2.4.1
Compiled against GEOS
3.7.2-CAPI-1.11.0
Running against GEOS
3.7.2-CAPI-1.11.0 b55d2125
PostgreSQL Client Version
9.2.4
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
5.2.0
Running against PROJ
Rel. 5.2.0, September 15th, 2018
OS Version
Windows 10 (10.0)

**Additional context**
![Wrong Process](https://user-images.githubusercontent.com/4864498/61600053-e7b21380-ac71-11e9-9dd7-78db2d0c34c9.png)

**Comment by Pedro-Murteira** [comment]
@ghost I'm not being able to replicate this on later versions of QGIS (3.15.16 and 3.22.2.). Are you still having this issue?
