### ISSUE TITLE
Importing networkx python package causing crash

### ISSUE THREAD

**Issue by jweckstr** [qgis/QGIS#30851]
**Describe the bug**
QGIS crashing (to desktop) when importing python package networkx (tested versions 2.1 & 2.3) in python console or as a plugin dependency. I also found the same behavior with seaborn (version 0.8.1). 

**QGIS and OS versions**

QGIS version | 3.8.1-Zanzibar | QGIS code revision | dcd95cc648
-- | -- | -- | --
Compiled against Qt | 5.11.1 | Running against Qt | 5.11.1
Compiled against GDAL/OGR | 2.3.2 | Running against GDAL/OGR | 2.3.2
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.6.2-CAPI-1.10.2 4d2925d6
PostgreSQL Client Version | 10.5 (Ubuntu 10.5-1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.4
Compiled against PROJ | 5.1.0 | Running against PROJ | Rel. 5.1.0, June 1st, 2018
OS Version | Ubuntu 18.10 |   |

**Comment by m-kuhn** [comment]
How was pythonx installed?

**Comment by jweckstr** [comment]
networkx was installed using pip in a local folder. I have checked that Qgis has access to the required pythonpaths. Other packages installed in a similar way seem to import just fine.

**Comment by m-kuhn** [comment]
Can you install from the repository and delete the custom path?

**Comment by jweckstr** [comment]
I tried the following: cloned networkx development version in a separate folder using git. Tried to run this version using a direct import using [this snippet](https://stackoverflow.com/a/50395128):

`MODULE_PATH = "/.../networkx/networkx/__init__.py"

MODULE_NAME = "networkx"
import importlib
import sys
spec = importlib.util.spec_from_file_location(MODULE_NAME, MODULE_PATH)
networkx = importlib.util.module_from_spec(spec)
sys.modules[spec.name] = networkx 
spec.loader.exec_module(networkx)`

This worked fine in the default python interpreter but resulted in the same crash in Qgis python interpreter.

**Comment by m-kuhn** [comment]
Can you carry out the abovementioned test to check if it's a local issue or a systematic issue on ubuntu 18.04 machines?

**Comment by jweckstr** [comment]
I appreciate your help but can you give more specific instructions? Installing what from repository and which custom path to delete?

**Comment by m-kuhn** [comment]
> networkx was installed using pip in a local folder. I have checked that Qgis has access to the required pythonpaths. Other packages installed in a similar way seem to import just fine.

Delete any paths you manually added here
And/or uninstall networkx using pip
Install `python3-networkx` using aptitude or your favourite software installer

**Comment by jweckstr** [comment]
Thank you, that made it clearer. 

I uninstalled networkx using pip and then installed the python3-networkx (which defaults to networkx version 2.1) using apt-get. Again import went well in default python interpreter but crash in qgis.

After this i removed the apt package and tried a few different pip installed versions. I have narrowed it down so that networkx==1.11 imports fine in qgis but not networkx==2.0.

**Comment by m-kuhn** [comment]
Can you start QGIS with a clean profile and check again?

**Comment by jweckstr** [comment]
Yes, I checked that earlier with the pip installed version. I rechecked with the apt version. Same behavior.

**Comment by m-kuhn** [comment]
Very weird, if you have any more information to add, please keep it coming. I'm out of ideas for now.

**Comment by jweckstr** [comment]
I ended up upgrading to ubuntu 19.04 and this solved the problems. I did not figure out what was causing this behavior.
