### ISSUE TITLE
unsupported SAGA version (found: 7.3.0, required: 2.3.)

### ISSUE THREAD

**Issue by dmbrmv** [qgis/QGIS#30856]
I'm running clean installation of QGIS 3.8 Zanzibar on Ununtu 18.04 and facing next problem wich you can see on the picture below:

![image](https://user-images.githubusercontent.com/47447162/61658832-810b1500-acc6-11e9-9f63-82a3733cf9ef.png)

Trying to install exact version of SAGA forcing me to next problem 
![image](https://user-images.githubusercontent.com/47447162/61658948-ba438500-acc6-11e9-9af2-862a28ebba0a.png)

What may cause all this mess and how can I solve it ?

Cheers,
Abramov Dima

**Comment by nyalldawson** [comment]
This is an upstream issue - the saga team needs to be convinced to release a new ltr supported version, which are the only versions supported by processing.

Alternatively there's a plugin available "saga next gen" which works with other versions.
