### ISSUE TITLE
Plugins not loading

### ISSUE THREAD

**Issue by lidarlady** [qgis/QGIS#30853]
Just updated to 3.4.10 and now cant down load QField or Open layers plugins. Used a new profile when updated 

**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by gioman** [comment]
> Just updated to 3.4.10 and now cant down load QField or Open layers plugins. Used a new profile when updated

@lidarlady do you mean "install"? any error message? does it happen with any other plugin too?

**Comment by lidarlady** [comment]
![Qfield](https://user-images.githubusercontent.com/53046210/61639020-8d757a80-ac92-11e9-843e-0f16c5fa701b.JPG)
Just tried these 2 plugins  so not sure if any others will have a similar problem

**Comment by lidarlady** [comment]
Problem sorted - you need to shut down Qgis if the error message comes up.
When its opened up again the plugins that it said failed are actually
loaded. Have not tried QField to see if it works yet but Open layers plugin
works

**Comment by gioman** [comment]
> Problem sorted - you need to shut down Qgis if the error message comes up. When its opened up again the plugins that it said failed are actually loaded. Have not tried QField to see if it works yet but Open layers plugin

likely a local issue.
