### ISSUE TITLE
OGR Dissolve in Processing tries to use wrong geometry column for geopackage

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#30875]
**Describe the bug**
GDAL -> Vector geoprocessing -> Dissolve (and probably others too) try to access a geometry column named "`geometry`". In GeoPackages the geometry column can have an arbitrary name. QGIS/GDAL seem to use "`geom`" by default.

Thus the algorithm fails.

Example failing ogr2ogr invocation copied out of the Processing log:

> $ ogr2ogr /tmp/processing_fa00201fd5834d59bce56248a29da60b/e757f43d33c34c7dadd7ef82099b8a38/OUTPUT.shp /tmp/criminal\ cases\ per\ bezirksregion.gpkg -nlt PROMOTE_TO_MULTI -dialect sqlite -sql "SELECT ST_Union(geometry) AS geometry FROM 'criminal cases per bezirksregion'" -f "ESRI Shapefile"
> ERROR 1: In ExecuteSQL(): sqlite3_prepare_v2(SELECT ST_Union(geometry) AS geometry FROM 'criminal cases per bezirksregion'):
>   no such column: geometry

Working invocation (I changed "`geometry`" to "`geom`"):

> $ ogr2ogr /tmp/processing_fa00201fd5834d59bce56248a29da60b/e757f43d33c34c7dadd7ef82099b8a38/OUTPUT.shp /tmp/criminal\ cases\ per\ bezirksregion.gpkg -nlt PROMOTE_TO_MULTI -dialect sqlite -sql "SELECT ST_Union(geom) AS geometry FROM 'criminal cases per bezirksregion'" -f "ESRI Shapefile"

**How to Reproduce**

1. Load a geopackage made in QGIS/GDAL (where the geometry column will be "`geom`")
2. In Processing launch GDAL -> Vector geoprocessing -> Dissolve
3. Click Run
> ERROR 1: In ExecuteSQL(): sqlite3_prepare_v2(SELECT ST_Union(geometry) AS geometry FROM 'foo'):
> 
> no such column: geometry
> 

**QGIS and OS versions**

QGIS version | 3.8.0-Zanzibar | QGIS code branch | Release 3.8
-- | -- | -- | --
Compiled against Qt | 5.13.0 | Running against Qt | 5.13.0
Compiled against GDAL/OGR | 3.0.0 | Running against GDAL/OGR | 3.0.0
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
PostgreSQL Client Version | 11.4 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 6.1.0 | Running against PROJ | Rel. 6.1.0, May 15th, 2019
OS Version | Arch Linux |   |

**Comment by kannes** [comment]
I swear the text field on top of the dialog where I can choose the geometry column did not exist 5 minutes ago!

Sorry :o)

But I would like to keep this open as feature request then. QGIS should be able to discover the name of geometry column and thus pre-fill that field automatically (in that case, why would it even be needed anymore?).

**Comment by gioman** [comment]
> But I would like to keep this open as feature request then. QGIS should be able to discover the name of geometry column and thus pre-fill that field automatically (in that case, why would it even be needed anymore?).

this was discussed a while ago on the dev mailing list and the result was that after all are not that many the (usual names), i.e. geom for postgis, geometry for shp, gpkg, etc. we could add a dropdown with the most common names... rather that adding the logic to discover the name.

**Comment by gioman** [comment]
file it again as feature request, if you feel so.
