### ISSUE TITLE
Couldn't load SIP module (Ubuntu 18.04)

### ISSUE THREAD

**Issue by wessport** [qgis/QGIS#30895]
After installing the 3.4.x Madeira LTR release, upon opening QGIS I am encountering the following error:

**Describe the bug**

```
Couldn't load SIP module.
Python support will be disabled.


Traceback (most recent call last):
  File "", line 1, in 
ModuleNotFoundError: No module named 'qgis'


Python version:
3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]

QGIS version:
3.4.10-Madeira 'Madeira', 3d97aaae88

Python path:
['/usr/share/qgis/python', '/home/wporter/.local/share/QGIS/QGIS3/profiles/default/python', '/home/wporter/.local/share/QGIS/QGIS3/profiles/default/python/plugins', '/usr/share/qgis/python/plugins', '/usr/local/lib/python36.zip', '/usr/local/lib/python3.6', '/usr/local/lib/python3.6/lib-dynload', '/home/wporter/.local/lib/python3.6/site-packages', '/usr/local/lib/python3.6/site-packages']
```

**OS Info**

Ubuntu 18.04.2 LTS 

```sudo vim /etc/apt/sources.list```
```
...
deb https://qgis.org/ubuntu-ltr bionic main
deb-src https://qgis.org/ubuntu-ltr bionic main
```

**Additional context**

I suspect the issue lies with my Python path, but I did recently upgrade from Xenial to Bionic so I suspect that may also be a factor that's contributing to the installation troubles.

Digging further, I've noticed the ```qgis``` directory and ```PyQt5``` directory seem to be missing from ```/usr/share/qgis/python```

```ls -l /usr/share/qgis/python``` returns...
```total 16
drwxr-xr-x 2 root root 4096 Jul 22 16:16 console
drwxr-xr-x 5 root root 4096 Jul 22 16:16 plugins
drwxr-xr-x 2 root root 4096 Jul 22 16:16 pyplugin_installer
drwxr-xr-x 2 root root 4096 Jul 22 16:16 qsci_apis
``` 

**Possibly Related:**
https://github.com/qgis/QGIS/issues/30654
https://github.com/qgis/QGIS/issues/28948

How can I resolve or begin to troubleshoot this error?

**Comment by gioman** [comment]
Have you tried removing all the qgis packages, then refreshing your sources and re-install? I'm on Ubuntu 18.04 too and using the official QGIS repos I can't replicate this issue.

**Comment by wessport** [comment]
@gioman I have, but perhaps I missed a lingering package?

Steps I took to try re-installing:
```
sudo apt-get purge qgis python3-qgis qgis-plugin-grass
sudo apt autoremove
sudo vim /etc/apt/sources.list
```
Removed and reinserted repositories
```
...
deb https://qgis.org/ubuntu-ltr bionic main
deb-src https://qgis.org/ubuntu-ltr bionic main
```
```
sudo apt-get update
sudo apt-get install qgis python3-qgis qgis-plugin-grass
```
Appears to install, but I encounter the same error again when opening QGIS. Perhaps interference from Anaconda I installed recently?

**Comment by wessport** [comment]
Reimaging my machine addressed the issue. 

I was able to install without the error with a fresh install of Ubuntu 18.04. In case it's helpful to anyone in the future, I suspect a recent installation of Anaconda was the culprit but I'm still not entirely sure.
