### ISSUE TITLE
QGIS crashes every time I need to open directories/folders to load or save files

### ISSUE THREAD

**Issue by camposds** [qgis/QGIS#30906]
**Describe the bug**

QGIS crashes every time I need to open directories/folders to load or save files
*QGIS Info*
QGIS Version: 3.4.10-Madeira
QGIS code revision: 3d97aaae88
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134
 -->

**How to Reproduce**

In my case, doesn't matter what function in QGIS I try to use, If it need to load or save, QGIS crashes in the step where the Explorer is open to choose folder. 

Step 1 - Load a Raster Layer
![ScreenShot_20190724111236](https://user-images.githubusercontent.com/53265594/61800848-2b3c8700-ae04-11e9-8968-eef3c40fca32.png)

Step 2 - Try to Export by clicking with the right button in the layer panel
![ScreenShot_20190724111305](https://user-images.githubusercontent.com/53265594/61800847-2b3c8700-ae04-11e9-9b8f-d36053eb4875.png)

Step 3 - When the dialogue box appears, click to find the destination folder
![ScreenShot_20190724111320](https://user-images.githubusercontent.com/53265594/61800846-2aa3f080-ae04-11e9-8c71-59b900bbcdb8.png)

Step 4 - The window of Explorer opens and in the next second...
![ScreenShot_20190724111335](https://user-images.githubusercontent.com/53265594/61800845-2aa3f080-ae04-11e9-8664-9656d54605cb.png)

Step 5 - It Crashes
![ScreenShot_20190724111352](https://user-images.githubusercontent.com/53265594/61800843-2aa3f080-ae04-11e9-8dd2-4f74f19733a9.png)

**QGIS and OS versions**

**Additional context**

**Comment by gioman** [comment]
@camposds please add *detailed* steps to follow.

**Comment by gioman** [comment]
Closing for the lack of feedback.
