### ISSUE TITLE
Installation of plugin kills QGIS

### ISSUE THREAD

**Issue by atzimler** [qgis/QGIS#30900]
I was trying to install a plugin that I'm porting from QGIS 2 to QGIS 3 when plugin installation crashed the application.

## User Feedback

Was installing a plugin that I'm trying to get up to date from QGIS 2 to QGIS 3.

## Report Details

*Crash ID*: 6cec55a9c445dd6e1f7748905538a8d7d40f84c7

*Stack Trace*
<pre>
QObject::parent :
QLayout::addChildWidget :
QTabBarPrivate::operator= :
QMainWindow::addDockWidget :
QgisApp::addDockWidget :
QgsPresetSchemeColorRamp::clone :
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyEval_EvalCodeEx :
PyEval_EvalCode :
PyArena_Free :
PyRun_StringFlags :
instance :
instance :
QgisApp::rotatePointSymbols :
QgsPythonRunner::run :
QgsAllLayersFeaturesLocatorFilter::triggerResultFromAction :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
PyInit__gui :
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyEval_EvalCodeEx :
PyEval_EvalCode :
PyArena_Free :
PyRun_StringFlags :
instance :
instance :
QgisApp::rotatePointSymbols :
QgsPythonRunner::run :
QgisApp::showPluginManager :
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.8.1-Zanzibar
QGIS code revision: dcd95cc648
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.14393

**Comment by atzimler** [comment]
This issue is most likely to be caused by a line in the python code of the plugin:
```
self.mainAction.triggered(self.run())
```
where, mainAction is of type of QAction.

**Comment by m-kuhn** [comment]
This is the bug tracker for QGIS.
Crashes with plugins are not in the scope of this issue tracker.
You might have better luck on another support channel like the mailing list, gis.stackexchange.com or by getting commercial support.

**Comment by atzimler** [comment]
This is not a crash with a plugin. It is a crash of QGIS caused by incorrect syntax in the plugin. To be clear. The plugin did not crash.

**Comment by m-kuhn** [comment]
QGIS allows plugins and python code to do pretty much whatever they want in order to allow developers to write the coolest possible plugin. The tradeoff for this is that there are also many ways to crash QGIS with python plugins. At this point the responsibility lies with the plugin author most of the time to change their use of the QGIS API.

It's possible that there is an issue with the QGIS API  too. In this case, we will need a minimum example of python code required to reproduce the problem and decide if this is "intended use of the API".

**Comment by atzimler** [comment]
Hi,

Do you need the code to be boiled down or you are just happy to go with an erroneous state? The call was a wrongly assigned QT binding accepted by the PyQT environment. The reason I’ve reported the problem was that I think it could be caught by enclosing the plugin loader to catch the error. At the moment I’m just trying to get the plugin correctly installed, the plugin is not acting yet.

If you’d like the plugin code to be boiled down to the bare minimum, I’m happy to do that as soon as I get there. The badly functioning code - in case you are happy to go with that state - is already on GitHub and I can point out the problematic commit and line - I figured how should it look correctly, so that is not why I’ve reported the bug.

Let me know which one you think would be better considering the time of wait / investigation effort involved to figure out the problem.

Regards,
Attila

**Comment by m-kuhn** [comment]
If possible, just a couple of lines to copy/paste to the python console would be the best.
