### ISSUE TITLE
Issues loading project with shapefiles on samba share

### ISSUE THREAD

**Issue by aetor** [qgis/QGIS#30924]
When I open a 3.8.1 *.qgs file, all layers are shown in first place. When I zoom out, they disapear and ar not showen anymore. When I close the *.qgs file (not saving it!!) and I open it again (I did not close Qgis)  I get a fault message that some shapefiles on a networkdrive are not there. But thay are not gone!!

see screenshot
![Knipsel](https://user-images.githubusercontent.com/18046760/61854251-fd1b7d80-aebd-11e9-95b5-76796d7932f4.JPG)

the same *.qgs file opening in 3.8.0, this problem is not there!

Today I am working for first time with 3.8.1 and this is first time i have trouble with Qgis!

**Comment by gioman** [comment]
What is the type of the share? nfs? smb? other?

**Comment by aetor** [comment]
Just at work windows share . Don't know what type.  Adding network disk \\fil1a\. Is attached to I:

**Comment by gioman** [comment]
> Just at work windows share . Don't know what type. Adding network disk \fil1a. Is attached to I:

knowing the type of share can be important. Also would allow others to test (i.e. for example I could test nfs, samba and maybe others, but not Windows shares).

**Comment by aetor** [comment]
I will look after it, tomorrow!

**Comment by aetor** [comment]
Here we use SMB.  On our pc, we have the connect it to a drive letter (I in this case)  But same files work fine in Qgis 3.8.0!

**Comment by gioman** [comment]
> Here we use SMB. On our pc, we have the connect it to a drive letter (I in this case) But same files work fine in Qgis 3.8.0!

So, trying to make things a little clear here:

you have shapes in a SMB share

you have project with shapes from this share

on 3.8.0 you can then work normally

in 3.8.1 while zooming in/out your vectors start disappear (evidently the network connection is lost).


What about if you revert to 3.8.0? It works again?

**Comment by aetor** [comment]
You tell it right, and yes, when I do not save the 3.8.1. file, I can open it in 3.8.0 without errors!  I did not try to save it. Monday I can test that.

Normally I could always use an earlier file newer qgis. But now it's gone after first zoom in and out.

**Comment by gioman** [comment]
> You tell it right, and yes, when I do not save the 3.8.1. file, I can open it in 3.8.0 without errors! I did not try to save it. Monday I can test that.

I just tested with a Samba share, and I didn't had any issue loading a project with  shapes from it (and zooming in/out, and closing re-opening the project). QGIS 3.8.1 on Windows 10 and the share created on Ubuntu.

**Comment by aetor** [comment]
Today, I tried to open the same fiel again and till now (10 minutes) there is no problem?  I think it was a network issue!  

Call can be closed!

**Comment by aetor** [comment]
today I open the file (qgs) and saved it as 3.8.1 QGZ file. the second time I open the QGZ file, I had the same issue again!

**Comment by gioman** [comment]
Does it make any difference saving as QGS ir QGZ? if you revert to 3.8.0 does it makes any difference?

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
