### ISSUE TITLE
Crash: right click on image ->export ->save as->"save raster layer as"

### ISSUE THREAD

**Issue by EvanJHamilton** [qgis/QGIS#30937]
QGIS crashes when exporting large images (12GB compressed satellite imagery).

Crash ID: de13be2a3f01cec4b12e9b0211da1bf5ded28dd7

Stack Trace

QgsRasterFileWriter::writeImageRaster :
QgsRasterFileWriter::writeRaster :
QgsRasterFileWriterTask::run :
QgsTask::start :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.8.1-Zanzibar
QGIS code revision: dcd95cc648
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by gioman** [comment]
Any chance of a download link for such raster layer?

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
