### ISSUE TITLE
[Shape Digitizing Toolbar] - add circle from three tangents does not work in the case of parallel lines

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#30933]
Add circle from three tangents does not work in the case of parallel straight lines, while for generic lines it works well

### the error: at least two segments are parallel

![due_tan_rett](https://user-images.githubusercontent.com/7631137/61889750-4b546f00-af06-11e9-88ff-3ac108eb8968.gif)

## OSGeo4W64 Network Installer - Win10 64b

```
Versione di QGIS 3.4.10-Madeira
Revisione codice QGIS 3d97aaae88
Compilato con Qt 5.11.2
Esecuzione con Qt 5.11.2
Compilato con GDAL/OGR 2.4.1
Esecuzione con GDAL/OGR 2.4.1
Compilato con GEOS 3.7.2-CAPI-1.11.0
Esecuzione con GEOS 3.7.2-CAPI-1.11.0 b55d2125
Versione client PostgreSQL 9.2.4
Versione SpatiaLite 4.3.0
Versione QWT 6.1.3
Versione QScintilla2 2.10.8
Compiled against PROJ 520
Running against PROJ 5.2.0
```

cc @lbartoletti

**Comment by tjukanovt** [comment]
This issue still seems to be in 3.12. 
Do you @lbartoletti have any ideas if there is anything that could be done for this?

**Comment by lbartoletti** [comment]
To be consistent with the maptool circle by 2 tangents, it will be a new feature since you can choice two circles wher lines are parallel. See the demo from QCAD

![circle_3tgts webm](https://user-images.githubusercontent.com/7521540/75165842-4ae1b800-5723-11ea-9ba2-31d1f5df8227.gif)

If I have some time or if it's funded, I can look for the 3.14.

**Comment by pigreco** [comment]
@lbartoletti 

Since it is not a bug then it is more correct to write like this

`Circle of 3 non-parallel tangents` ??

**Comment by lbartoletti** [comment]
@pigreco you mean, replace the error message by something like `the construction of a circle by 3 tangents, two of which are parallel, can return two circles.`?

**Comment by tjukanovt** [comment]
BTW this functionality seems to be working more or less via the QAD plugin: https://github.com/gam17/QAD

Just in case if there are some reusable pieces.

**Comment by pigreco** [comment]
> @pigreco vuoi dire, sostituire il messaggio di errore con qualcosa del genere `the construction of a circle by 3 tangents, two of which are parallel, can return two circles.`?

write in the drop-down menu,
a way to warn.

![image](https://user-images.githubusercontent.com/7631137/75622228-7985e580-5b9e-11ea-9208-0e5939865caf.png)

**Comment by lbartoletti** [comment]
@pigreco @tjukanovt 

I double-checked and there are CAD tools that propose the creation of a circle from 3 tangents even when 2 are parallel.
In this case, there are 2 possibilities (4 if you count doubles and empty circles) [1].
First I will correct the bug by using the point (click) on the first selected parallel to determine where the circle will be. [2]

Next, I'll propose an option with a key modifier to switch between: Use the first circle (*CAD soft) or let me choose my circle (QCAD philosophy) ; I will also propose this for circles by 2 tangents and a radius.

[1] QCad for example
[2] There are bugs in the qad code

**Comment by lbartoletti** [comment]
![image](https://user-images.githubusercontent.com/7521540/101735765-a585ae00-3ac2-11eb-81ba-accc5db7f345.png)

With an illustration:

if you click on the lowest point first, the circle 1 will be drawn, instead if you clik on the highest point the circle 2 will be drawn.

**Comment by lbartoletti** [comment]
Done!

Grazie totò
