### ISSUE TITLE
3D Map View blank but no crash (Windows 10)

### ISSUE THREAD

**Issue by jfbourdon** [qgis/QGIS#30934]
**Describe the bug**
When opening the 3D Map View, the window stay blank, hovewer the layer is loaded because if I save the current view with the button *Save as Image...*, the image file show the layer. I can even pan and zoom (blindfolded) and if I do again *Save as Image...*, I get a new view. It was working fine when I was on Windows 7, but it's no longer working with Windows 10. The problem was also there with QGIS 3.6.x

**How to Reproduce**
1. Load any raster into the canva
1. Go to *View*
1. Click on *New 3D Map View*

**QGIS and OS versions**
QGIS version: 3.8.1-Zanzibar
QGIS code revision: dcd95cc648
OS Version: Windows 10 (10.0)

**Comment by gioman** [comment]
Can't confirm here

![Screenshot_20190726_165108](https://user-images.githubusercontent.com/1951107/61964380-9e412b80-afc5-11e9-8fa1-55e74d741e06.png)

**Comment by jfbourdon** [comment]
I get the sense that it is related to the way our Windows environement is set up at work. I found the same kind of problem with two other software and it may be related to OpenGL. I've reported this to our IT team and I will come back here explaining the solution in case someone else experience the same thing.

**Comment by jfbourdon** [comment]
As suspected, the issue was caused by a bad graphic driver installation. It's now working fine after reinstallation.
