### ISSUE TITLE
[Shape Digitizing Toolbar] - add regular polygon always remains active

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#30948]
Adding a regular polygon, the request for the `number of sides` always remains active and the keyboard shortcut <kbd>d</kbd> (advanced digitization) does not work to enter the distance

![add](https://user-images.githubusercontent.com/7631137/61944356-ca48b680-af9d-11e9-9b4a-854b921b275b.gif)

## OSGeo4W Network Installer WIn10 64b

```
Versione di QGIS 3.4.10-Madeira
Revisione codice QGIS 3d97aaae88
Compilato con Qt 5.11.2
Esecuzione con Qt 5.11.2
Compilato con GDAL/OGR 2.4.1
Esecuzione con GDAL/OGR 2.4.1
Compilato con GEOS 3.7.2-CAPI-1.11.0
Esecuzione con GEOS 3.7.2-CAPI-1.11.0 b55d2125
Versione client PostgreSQL 9.2.4
Versione SpatiaLite 4.3.0
Versione QWT 6.1.3
Versione QScintilla2 2.10.8
Compiled against PROJ 520
Running against PROJ 5.2.0
```

cc @lbartoletti

**Comment by gioman** [comment]
@pigreco still true?

**Comment by pigreco** [comment]
@gioman 
I just did a test in QGIS 3.16.2 Hannover, everything seems ok!
thanks!
