### ISSUE TITLE
Allow inverting mouse wheel

### ISSUE THREAD

**Issue by mirouml** [qgis/QGIS#30940]
**Set wheel factor "bug"**
iface.mapCanvas().setWheelFactor(0.5)

This will revert the zoom in/ zoom out behavior. Not only wheel behavior but all zoom in / zoom out tools applied to that map canvas. For example zoom in tool will work as zoom out when clicked on map canvas.

**How to reproduce**
1. Open QGIS and load any layer you can zoom with, zoom in/out with wheel
2. Open python console - Plugins/Python console (Ctrl+Alt+p)
3. Write there this one line: iface.mapCanvas().setWheelFactor(0.5)
4. Try zoom with wheel to make sure it reverted the wheel behavior
5. Use Zoom In tool (Ctrl+Alt++) and click to zoom in, which should zoom out

QGIS 3.8, Windows

**How to sort out**
I love idea of being able to revert mouse wheel zoom in/out behavior through this (as for many ArcMap users it is desired behavior). The problem is it affects other tools too. Also it is a bit shame this can't be set up in Settings/Options/Map tools/Zooming/Zoom factor as there is minimum limit set to 100%, so you can't do 50% which is same as setWheelFactor(0.5). All these things relate to each other and should be thought through.

**Comment by m-kuhn** [comment]
Let's see if I understand this correctly:
You want to be able to invert the behaviour of the mouse wheel?
If yes, I wonder if a boolean option for this would be more user friendly.

**Comment by mirouml** [comment]
Thank you Matthias. Agreed, boolean option would be definitely more user friendly, especially taking into account user interface. From development perspective, looking at https://qgis.org/api/3.8/classQgsMapCanvas.html, setWheelFactor is actually applying setMagnificationFactor. So it is not only changing wheel zoom factor, but changing the way more general magnification factor.

There are more options to solve this, in my opinion I think there is no need to have specific zoom wheel factor, different from zoom factor:

1. setWheelFactor() = setMagnificationFactor() (setWheelFactor is only alias)
2. add setWheelOrientation() boolean
3. add it to UI: Settings/Options/Map tools/Zooming

In such case there is no need to go with setMagnificationFactor() < 1 (100%).

**Comment by mirouml** [comment]
In ArcMap UI they call it reverse:

> You can reverse the zoom in/zoom out convention used by the mouse wheel. Click Customize > ArcMap Options to open the ArcMap Options dialog box. Click the General tab and make your changes in the Mouse Wheel and Continuous Zoom/Pan Tool section.

**Comment by m-kuhn** [comment]
Are you going to work on that?
The specs sound good to me like that, although I'd seperate the method alias from the new option so they can be reviewed / accepted individually. :+1:
