### ISSUE TITLE
Crash when opening print layout

### ISSUE THREAD

**Issue by lueho** [qgis/QGIS#30951]
## User Feedback

I created a print layout from within a self made processing script and added it to the layout manager. The crash happened when i attempted to open the layout.

## Report Details

*Crash ID*: fbcc480976ee1067ea27582f307a4ca26f30cd85

*Stack Trace*
<pre>
QBitArray::QBitArray :
QgsAttributeEditorQmlElement::qmlCode :
QgsLayoutTable::render :
CPLStringList::empty :
QgsLayoutFrame::draw :
CPLStringList::PartialFindString :
QgsLayoutItem::paint :
CPLStringList::empty :
QGraphicsScene::~QGraphicsScene :
QGraphicsScene::drawForeground :
QGraphicsScene::dragMoveEvent :
QGraphicsItem::dragMoveEvent :
QGraphicsEffectSource::draw :
QgsLayoutEffect::draw :
QGraphicsScene::drawItems :
QGraphicsScene::drawItems :
QGraphicsView::paintEvent :
QgsLayoutView::paintEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QApplication::windowIcon :
QWidgetPrivate::syncBackingStore :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processExposeEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QWindowSystemInterface::flushWindowSystemEvents :
DispatchMessageW :
DispatchMessageW :
GetSystemMetrics :
KiUserCallbackDispatcher :
NtUserDispatchMessage :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.4.9-Madeira
QGIS code revision: 54585165bb
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by gioman** [comment]
@lueho can you attach a sample project+data?

**Comment by roya0045** [comment]
Can you tell us more about this:

> I created a print layout from within a **self made processing script** and added it to the layout manager. The crash happened when i attempted to open the layout.

The bug might come from your script rather than qgis itself.

**Comment by nyalldawson** [comment]
Make sure you aren't creating the layout in a background thread and then adding to a project. That's not a thread safe process and will crash.

**Comment by lueho** [comment]
Thanks for picking up on this.

Some context:

My intention is to embed a function in my script that automatically creates a report layout and ideally opens the layout designer after finishing the script. I have successfully been doing this with scripts from console. Now I wanted to integrate my scripts into the processing toolbox using the provided template ('Create new script from template...'). That lead to some behaviour that I did not expect. I have isolated the part which causes trouble below. Actually, there are three independent problems, which means, I can reproduce each problem individually. 

Problem 1: The map does not render when I initially open the layout designer. This can be fixed by duplicating the layout or restarting QGIS. 

Problem 2: See line denoted as 'crash point 1'. When I add this line to the code, the script runs and finished without error. When I try opening the layout through the layout manager, the crash of my original report occurrs. 

Problem 3: See line denoted as 'crash point 2'. When I try opening the layout designer from within the script, QGIS immediately crashes without crash report: the crash report window opens but stays blank and the cursor remains the windows waiting symbol until I close QGIS through the task manager.

I hope, this is enough information for you to decide, whether this is a bug or wrong usage of the system from my side.  If you need any more, please let me know. 

```python
project = context.project()
manager = project.layoutManager()
layout = QgsPrintLayout(project)
layout.initializeDefaults()
            
layout.setName('Layout Name')
            
pages = layout.pageCollection()
pages.beginPageSizeChange()
page = pages.page(0)
page.setPageSize('A4')
pages.endPageSizeChange()
page_center = page.pageSize().width() / 2
            
title = QgsLayoutItemLabel(layout)
title.setText('Layout Title')
title.setFont(QFont('arial', 36))
title.adjustSizeToText()
title.setReferencePoint(1)
title.attemptMove(QgsLayoutPoint(page_center, 20))
layout.addItem(title)
                     
map = QgsLayoutItemMap(layout)
map.setRect(20, 20, 20, 20)
ms = QgsMapSettings()
ms.setLayers([catchment])
rect = QgsRectangle(ms.fullExtent())
rect.scale(1.0)
ms.setExtent(rect)
map.setExtent(rect)
map.attemptResize(QgsLayoutSize(180, 90))
map.setReferencePoint(1)
map.attemptMove(QgsLayoutPoint(page_center, 50))
layout.addLayoutItem(map)
            
table = QgsLayoutItemTextTable(layout)
layout.addMultiFrame(table)
cols = [QgsLayoutTableColumn(), QgsLayoutTableColumn(), QgsLayoutTableColumn()]
cols[0].setHeading('Heading 0')
cols[1].setHeading('Heading 1')
table.setColumns(cols)
table.setContents([['Hello', 'world!']])
frame = QgsLayoutFrame(layout, table)
frame.attemptResize(QgsLayoutSize(30, 30), True)
frame.setReferencePoint(1)
frame.attemptMove(QgsLayoutPoint(page_center, 150))
table.addFrame(frame) # crash point 1
           
manager.addLayout(layout)
      
iface.openLayoutDesigner(layout) # crash point 2
```

**Comment by nyalldawson** [comment]
Yes - the script is NOT thread safe, so cannot be used from a processing algorithm I. The background thread.

This isn't a qgis issue, so I need to close this ticket. You can continue the discussion on the qgis mailing list or via gis.stackexchange.com.
