### ISSUE TITLE
QGIS Browser shows shapefiles all with the "polygon" icon (even the point and line ones)

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#30953]
Does not seems to affect other formats like GPKG and PostGIS. QGIS 3.4.10 and 3.8.1

![Screenshot_20190726_212705](https://user-images.githubusercontent.com/1951107/61979594-2f2afd80-afec-11e9-9837-c437e8f2de76.png)

**Comment by nyalldawson** [comment]
There's a setting which controls this in options - if you set to browser to scan file contents instead of just the extension. It's slower, though, so isn't the default.

**Comment by gioman** [comment]
> There's a setting which controls this in options - if you set to browser to scan file contents instead of just the extension. It's slower, though, so isn't the default.

it doesn't change even if the "fast scan this directory" option is disabled.

**Comment by nyalldawson** [comment]
It's this setting (not "fast scan"):

![image](https://user-images.githubusercontent.com/1829991/61992144-c308d200-b09d-11e9-96e9-4646505eadac.png)

**Comment by gioman** [comment]
>  It's slower

you are right, it's super slow.

**Comment by nyalldawson** [comment]
Yep, especially for network sources. (It has to open them to determine the type(

**Comment by gioman** [comment]
> Yep, especially for network sources. (It has to open them to determine the type(

I was thinking if then it would not be better to show a "neutral" icon, instead of a polygon one also for lines and points.
