### ISSUE TITLE
Update button extent doesn't work but using python console does

### ISSUE THREAD

**Issue by antoniolocandro** [qgis/QGIS#30954]
I added an XML/GML file which has defined EPSG:4326, however due to axis order things it doesn't show up where it is supposed to be. I use a custom CRS to set lat,lon however the extent doesn't get automatically update so when you zoom to the layer it will go to the initial load area. Tried the update extent but nothing happens

Similar to this question on gis stackexchange https://gis.stackexchange.com/questions/313211/qgis-3-4-layer-properties-update-extents-to-minimum-bounding-box-of-features

**Comment by gioman** [comment]
@antoniolocandro still valid? of yes please post/attach a sample (and the custom CRS definition).

**Comment by antoniolocandro** [comment]
In latest versions it seems to be working OK, I will close and will open again if it happens. I think that is a better approach for this one
