### ISSUE TITLE
Auth from qgis-auth.db only works when master password is stored in password manager

### ISSUE THREAD

**Issue by gisnederland** [qgis/QGIS#30970]
I have a few connections to postgis databases
The credentials are stored in an authentication configuration (and thus stored in qgis-auth.db).
When I use the option (in options/authentication/utilities)  _integrate master password with your password manager_ (and thus store the qgis-auh.db master password in the Windows 10 _credentials manager_ this works fine.
If I choose not to use this option QGis hangs as soon as I open the connection to the Postgis database and supply the (qgis-auth.db's) master password.

No special user profiles. 
One detail: on my PC %appdata% redirects to an UNC-path (similar as in #30619 )

QGIS version- 3.8.0-Zanzibar (64 bit)
QGIS code revision - 11aff65f10
Compiled against Qt - 5.11.2
Running against Qt - 5.11.2
Compiled against GDAL/OGR - 2.4.1
Running against GDAL/OGR - 2.4.1
Compiled against GEOS - 3.7.2-CAPI-1.11.0
Running against GEOS - 3.7.2-CAPI-1.11.0 b55d2125
PostgreSQL Client Version - 9.2.4
SpatiaLite Version - 4.3.0
QWT Version - 6.1.3
QScintilla2 Version - 2.10.8
Compiled against PROJ - 5.2.0
Running against PROJ - Rel. 5.2.0, September 15th, 2018
OS Version - Windows 10 (10.0)

**Comment by gisnederland** [comment]
Same behavior on a different PC (also Win10-64, QGIS 3.8 Zanzibar), connecting to a different database (on localhost, by the way). 
This PC has a regular %appdata% redirection (c:\users\<username>\Appdata\Roaming)

**Comment by gioman** [comment]
Did it worked correctly in a previous release?

**Comment by gisnederland** [comment]
Didn't work in 3.4 (same behavior as 3.8).
Did work properly in 2.18.15

**Comment by elpaso** [comment]
@gisnederland there were some changes in this area, would you be able to check latest master and see if this is still an issue?

**Comment by nirvn** [comment]
I've fixed this already. You'll be please to see it fixed in the next version.
