### ISSUE TITLE
Unsupported relation type 'ForeignTable'

### ISSUE THREAD

**Issue by alkra** [qgis/QGIS#30990]
**Describe the bug**

I am trying to load a PostgreSQL foreign table with the "Add a PostGIS Layer..." menu.

QGIS successfully lists the foreign table and lets me select it.

When I press the "Add" button, QGIS fails to add the layer with the following error:

    WARNING    dbname='***' host=*** port=*** authcfg=*** srid=2154 type=Polygon checkPrimaryKeyUnicity='0' table="cor_domaine_public"."28_TRONFLUV_id" (geom) sql= is an invalid layer - not loaded

and in PostGIS panel:

    WARNING    Unexpected relation type 'ForeignTable'.  
    WARNING    PostgreSQL layer has no primary key.

**How to Reproduce**

1. Set up a PostGIS foreign table on a new PostgreSQL database.
2. In a new QGIS project, use Layer > Add layer > Add PostGIS layers...
3. Configure the database, then Connect
4. See that the foreign table is listed, without warning
5. Select it
6. Click Add
7. Error

**QGIS and OS versions**

QGIS version | 3.9.0-Master | QGIS code revision | ab7106ae99
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.0 | Running against GEOS | 3.7.2-CAPI-1.11.0 b55d2125
PostgreSQL Client Version | 9.2.4 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
This copy of QGIS writes debugging output.
OS Version | Windows 10 (10.0) |   |  

I also saw this issue in QGIS 2.18, QGIS 3.4, and QGIS 3.8

**Additional context**

PostgreSQL 11.4-1 (Debian Buster) using PostGIS 2.5.1 (Debian Buster)

I am using this foreign data wrapper: [pramsey/postgresql_ogr_fdw](https://github.com/pramsey/postgresql_ogr_fdw) at version 1.0.7 (Debian Buster)

Slightly related issues (against DB Manager, mine is against PostGIS provider) : #30171 and #21727

**Comment by alkra** [comment]
I can see two ways to solve this.

1. Handle a foreign table like a normal table in [qgspostgresprovider.cpp:1366](https://github.com/qgis/QGIS/blob/master/src/providers/postgres/qgspostgresprovider.cpp).

Problem: Rows of a foreign table cannot be assigned an oid, so the ctid will be used as primary key.  I find such a layer hard to use in QGIS.

PostgreSQL >= 10 users may

    ALTER TABLE ... ALTER COLUMN fid ADD GENERATED BY DEFAULT AS IDENTITY;
   
to get this solution to work.

2. Handle a foreign table like a view, and let the user select its primary key.

I wrote [a patch](https://github.com/qgis/QGIS/files/3446769/bug30990fix2.txt) for the second solution because it should support PostgreSQL < 10. I only tested it with PostgreSQL 11.4-1 (Debian Buster).

Please let me now if you would like a pull request.

**Comment by gioman** [comment]
> Please let me now if you would like a pull request.

@alkra yes please
