### ISSUE TITLE
Obscure error message when 'Export to vector (or raster)' fails because another file with the same name is already added to the map

### ISSUE THREAD

**Issue by LBT-AiP** [qgis/QGIS#31008]
**Describe the bug**
If you try to export features (all or selected ones) of a loaded vector (or raster) file into a file with the same name as a file already loaded in qGIS, you get an obscure error message and the to-be-saved file gets corrupted.

**How to Reproduce**
1. Load a vector (or raster) file. Export some or all features into another file which you add to map.
2. Export again some or all features into a file with the same name as the one already added to map. You get a first (expected) message : 'The file already exists. Do you want to overwrite the whole file or append features to the layer?' 

3. When you answer 'yes, overwrite', you get an (obscure) error message: 
'Export to vector file failed. Error: creation of data source failed (OGR error: [path to file].sh is not a directory.)'
Also the file to be overwritten gets corrupted.

You would expect a message like 'Cannot overwrite an OGR layer in place' as you do get if you try to export the features of a loaded file under the same name as the original file - and no data corruption.

**QGIS and OS versions**
Windows 8 64 bits
QGIS version | 3.4.10-Madeira | QGIS code revision | 3d97aaae88
QGIS version | 3.8.1-Zanzibar | QGIS code revision | dcd95cc648

**Additional context**

**Comment by roya0045** [comment]
For additional information, which file format are you using to save the file? This might be provider dependent.

**Comment by LBT-AiP** [comment]
I save as an Esri shapefile (*.shp *.SHP).

Also, this problem occurred first to me while working on rasters and I easily could reproduce it with vector files. However, since then I have not been able to reproduce the issue with rasters (save as geoTiff).

**Comment by gioman** [comment]
>     3\. When you answer 'yes, overwrite', you get an (obscure) error message:
>         'Export to vector file failed. Error: creation of data source failed (OGR error: [path to file].sh is not a directory.)'
>         Also the file to be overwritten gets corrupted.

Does not happen in recent releases, please reopen if necessary.
