### ISSUE TITLE
Adding field to attribute table causes crash

### ISSUE THREAD

**Issue by rap-manager** [qgis/QGIS#31010]
**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by rap-manager** [comment]
Trying to add a field to the attribute table for a vector layer, the program crashed with the following error:

## User Feedback

Adding a field to an attribute table

## Report Details

*Crash ID*: dad62438aee5e342ba9b904a1da8f75528f08841


*Stack Trace*
<pre>
memmove :
QSortFilterProxyModel::qt_metacast :
QSortFilterProxyModel::removeRows :
QSortFilterProxyModel::sortRole :
QSortFilterProxyModel::`default constructor closure' :
QMetaObject::activate :
QAbstractItemModel::beginRemoveRows :
QgsAttributeTableModel::removeRows :
QgsAttributeTableModel::loadLayer :
QMetaObject::activate :
QMetaObject::activate :
QgsVectorLayer::updateFields :
QgsVectorLayerUndoCommandAddAttribute::redo :
QUndoStack::push :
QgsVectorLayerEditBuffer::addAttribute :
QgsAttributeTableDialog::mActionAddAttribute_triggered :
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
DispatchMessageW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>


*QGIS Info*
QGIS Version: 3.8.1-Zanzibar
QGIS code revision: dcd95cc648
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1



*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by RaySarn** [comment]
I'm having the same problem.  
## User Feedback

Editing attribute table, deleted several fields and added new one

## Report Details

*Crash ID*: 747531816264705d37ae333ddf4ef0c9eb366a9d


*Stack Trace*
<pre>
memcmp :
QSortFilterProxyModel::qt_metacast :
QSortFilterProxyModel::removeRows :
QSortFilterProxyModel::sortRole :
QSortFilterProxyModel::`default constructor closure' :
QMetaObject::activate :
QAbstractItemModel::beginRemoveRows :
QgsAttributeTableModel::removeRows :
QgsAttributeTableModel::loadLayer :
QMetaObject::activate :
QMetaObject::activate :
QgsVectorLayer::updateFields :
QgsVectorLayerUndoCommandAddAttribute::redo :
QUndoStack::push :
QgsVectorLayerEditBuffer::addAttribute :
QgsAttributeTableDialog::mActionAddAttribute_triggered :
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
DispatchMessageW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>


*QGIS Info*
QGIS Version: 3.8.1-Zanzibar
QGIS code revision: dcd95cc648
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1



*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by gioman** [comment]
> I'm having the same problem.

please try with a new/clean QGIS profile.

**Comment by roya0045** [comment]
@RaySarn does this occur with any file type/provider or only one in particular?

**Comment by RaySarn** [comment]
So far it has only occurred with a new vector layer that I added. The
problem occurs in both ver. 3.4 and 3.8.  It only started after I upgraded
to 3.8 though.  I will try a new profile as Giovanni suggested and let you
know if that clears it up.

**Comment by RaySarn** [comment]
Using a new/clean profile seems to have worked.  Thank you!
