### ISSUE TITLE
QGIS Version Information in 3.6 and 3.8 says 3.9 will be released as 3.8

### ISSUE THREAD

**Issue by mewoch** [qgis/QGIS#31019]
**Describe the bug**
Using the windows version of QGIS for 3.6 or 3.8 the QGIS Version Infromation reports that Master 3.9 will become version 3.8. It also provides a link to Redmine.

**How to Reproduce**

1. Click on Help
2. Select Check QGIS version
3. The window that opens provides incorrect information.

**QGIS and OS versions**

At least Windows standalone 64-bit versions 3.6 and 3.8

QGIS version | 3.8.1-Zanzibar | QGIS code revision | dcd95cc648
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.0 | Running against GEOS | 3.7.2-CAPI-1.11.0 b55d2125
PostgreSQL Client Version | 9.2.4 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Windows 10 (10.0) |   |  

QGIS version | 3.6.3-Noosa | QGIS code revision | 0c5774c068
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.0 | Running against GEOS | 3.7.2-CAPI-1.11.0 b55d2125
PostgreSQL Client Version | 9.2.4 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018

**Additional context**
![QGISVersionInformation](https://user-images.githubusercontent.com/6393903/62201874-cdd3a780-b3ba-11e9-9e65-9fcf578f598d.PNG)

**Comment by stev-0** [comment]
Related to https://github.com/qgis/QGIS/issues/30642

**Comment by mewoch** [comment]
Yep definitely related. At least that #30642 had sensible ordering for the version numbers.

So if one of us does a PR for the https://version.qgis.org/version.txt file this can be closed? - does that seem right?
