### ISSUE TITLE
Crash ID: aa6c01c7b97826c23bd0d3dd890f485eb0b6adc3

### ISSUE THREAD

**Issue by GISLINUX** [qgis/QGIS#31016]
Stack Trace

QgsGraduatedSymbolRenderer::graduatedMethod :
QgsMapToolTrimExtendFeature::canvasMoveEvent :
QgsMapCanvas::mouseMoveEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.8.1-Zanzibar
QGIS code revision: dcd95cc648
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by nirvn** [comment]
@GISLINUX , can you provide steps to reproduce this crash?

**Comment by GISLINUX** [comment]
Edit Polyline: cut and extend comand. (I can't write in English, sorry).

**Comment by GISLINUX** [comment]
![Cattura](https://user-images.githubusercontent.com/53510470/62203723-00b27700-b38c-11e9-9cad-647617136b30.PNG)

I hope this image is useful.

**Comment by nirvn** [comment]
@GISLINUX , thanks for your report; a crash was identified and will be fixed in time for the release of QGIS 3.8.2 in mid August. I'm pretty sure it'll fix your issue.

**Comment by GISLINUX** [comment]
Great man.
