### ISSUE TITLE
QGIS crash on attempting to print to plotter

### ISSUE THREAD

**Issue by grantboxer** [qgis/QGIS#31013]
## User Feedback

Attempting to print to a plotter (HP1055CM Designjet) and QGIS crashes on both 3.9 and 3.8 versions.

## Report Details

*Crash ID*: 1bff47426b3c703b0c7da82b1c7fc2685450e385

*Stack Trace*
<pre>
GetWindowRgnBox :
Ordinal2573 :
Ordinal2573 :
CallWindowProcW :
SendMessageW :
SendMessageW :
MITSetLastInputRecipient :
EmptyClipboard :
CallWindowProcW :
CallWindowProcW :
IsWindowVisible :
KiUserCallbackDispatcher :
NtUserSetFocus :
PropertySheetW :
PropertySheetW :
DestroyPropertySheetPage :
PropertySheetW :
GetWindowRgnBox :
Ordinal2573 :
Ordinal2573 :
CallWindowProcW :
SendMessageW :
CreateWindowInBand :
CreateDialogIndirectParamAorW :
CreateDialogIndirectParamW :
PropertySheetW :
PropertySheetW :
PropertySheetW :
CommonPropertySheetUIW :
SetCPSUIUserData :
SetCPSUIUserData :
CommonPropertySheetUIW :
DocumentPropertiesWrap :
Ordinal101 :
PrintDlgExW :
GetWindowRgnBox :
Ordinal2573 :
Ordinal2573 :
CallWindowProcW :
SendMessageW :
SendMessageW :
LoadCursorFromFileW :
MITSetLastInputRecipient :
EmptyClipboard :
CallWindowProcW :
DispatchMessageW :
IsDialogMessageW :
CreatePropertySheetPage :
CreatePropertySheetPage :
Ordinal164 :
PrintDlgExW :
PrintDlgExW :
PrintDlgExW :
QPrintDialog::metaObject :
QgisAppInterface::actionAbout :
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.8.1-Zanzibar
QGIS code revision: dcd95cc648
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by gioman** [comment]
@grantboxer please test on 3.10.3/3.12

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
