### ISSUE TITLE
Processing/GDAL does not work anymore on systems in german language

### ISSUE THREAD

**Issue by guenterhack** [qgis/QGIS#31023]
Hi
GDAL crashes reproducibly on my Windows 7 machine (German) with the following output:

---snip
 
QGIS-Version: 3.8.1-Zanzibar
QGIS-Codeversion: dcd95cc648
Qt-Version: 5.11.2
GDAL-Version: 2.4.1
GEOS-Version: 3.7.2-CAPI-1.11.0 b55d2125
PROJ-Version: Rel. 5.2.0, September 15th, 2018
Verarbeite Algorithmus…
Algorithmus Raster auf Layermaske zuschneiden startet…
Input parameters:
{ 'ALPHA_BAND' : False, 'CROP_TO_CUTLINE' : True, 'DATA_TYPE' : 0, 'INPUT' : 'path to GeoTiff file on network drive without special characters', 'KEEP_RESOLUTION' : False, 'MASK' : 'path to SHP file on network drive without special characters', 'MULTITHREADING' : False, 'NODATA' : None, 'OPTIONS' : '', 'OUTPUT' : 'TEMPORARY_OUTPUT', 'SET_RESOLUTION' : False, 'SOURCE_CRS' : None, 'TARGET_CRS' : None, 'X_RESOLUTION' : None, 'Y_RESOLUTION' : None }

GDAL command:
gdalwarp -of GTiff -cutline [path to file on network drive without special characters] -cl croplayer -crop_to_cutline [path to file on network drive without special characters] [path to temp file on local hd without special characters]
GDAL command output:
Traceback (most recent call last):
File "C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python/plugins\processing\algs\gdal\GdalAlgorithm.py", line 130, in processAlgorithm
GdalUtils.runGdal(commands, feedback)
File "C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python/plugins\processing\algs\gdal\GdalUtils.py", line 106, in runGdal
for line in proc.stdout:
File "C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib\codecs.py", line 322, in decode
(result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x81 in position 143: invalid start byte

Execution failed after 3.13 seconds

---snap

In fact, every raster operation (merge, reproject, etc.) crashes GDAL with said UnicodeDecodeError. QGIS 2.18 runs perfectly on the same machine. I've read in older error reports that this issue existed in QGIS 3.4.x but it seems to have been resolved since then. I've scrubbed my .profile and re-installed QGIS 3.8.1 several times, but to no avail, the problem persists. I even switched system language from German to English because this used to work as a workaround - still the same error. On my private machine (Win 10) everything works. Is this a Windows 7 issue? I've uninstalled all older QGIS versions apart from 2.18.

**Comment by roya0045** [comment]
Are there characters in your file path that might not be supported by utf-8?

Anything with an accent or that is not usually used in English might cause this error.

Otherwise I assume that a decoder with more characters could be used in GdalUtils to handle the string in proc.stdout.

**Comment by guenterhack** [comment]
Thanks. There are no special characters in the file paths. I guess it is an Windows 7 issue. I will stick to QGIS 2.18 in the meantime.

**Comment by roya0045** [comment]
Would you be willing to do some tests regarding this? Or maybe @volaya knows what to fix.

I assume that the issue might be fixed in the subprocess generated at line 98 of GdalUtils.py.

I'm not too familiar with the cause of the error but you could try adding a line with 'encoding = "ISO-8859-1" ' or remove the 'universal_newlines=True'.

Though I'm not sure as to only you are reporting this error...

**Comment by guenterhack** [comment]
Thanks. Tried it and it didn't work. Maybe it's my machine, then again, 2.18 works fine and the behaviour is similar to this phenomenon so I thought I'd better report it: https://gis.stackexchange.com/questions/302457/qgis-3-4-error-utf-8-codec-cant-decode-byte-0xe8-in-position-50-invalid-cont/302526

**Comment by romainbh** [comment]
I have similar issue in french language:

Version de QGIS : 3.10.1-A Coruña
Révision du code : ef24c526da
Version de Qt : 5.11.2
Version de GDAL : 3.0.2
Version de GEOS : 3.8.0-CAPI-1.13.1 
Version de Proj : Rel. 6.2.1, November 1st, 2019
Traitement de l'algorithme…
Démarrage de l'algorithme 'Contour'…
Input parameters:
{ 'BAND' : 1, 'CREATE_3D' : False, 'EXTRA' : '', 'FIELD_NAME' : 'ELEV', 'IGNORE_NODATA' : False, 'INPUT' : 'C:/Users/blancr/Desktop/test.tif', 'INTERVAL' : 1, 'NODATA' : None, 'OFFSET' : 0, 'OUTPUT' : 'C:/Users/blancr/Desktop/temp.gpkg' }

GDAL command:
gdal_contour -b 1 -a ELEV -i 1.0 -f "GPKG" C:\Users\blancr\Desktop\test.tif C:/Users/blancr/Desktop/temp.gpkg
GDAL command output:
Traceback (most recent call last):
File "C:/OSGEO4\~2/apps/qgis/./python/plugins\processing\algs\gdal\GdalAlgorithm.py", line 137, in processAlgorithm
GdalUtils.runGdal(commands, feedback)
File "C:/OSGEO4\~2/apps/qgis/./python/plugins\processing\algs\gdal\GdalUtils.py", line 106, in runGdal
for line in proc.stdout:
File "C:\OSGEO4\~2\apps\Python37\lib\codecs.py", line 322, in decode
(result, consumed) = self._buffer_decode(data, self.errors, final)
**UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 52: invalid start byte**

Execution failed after 13.06 seconds

Chargement des couches de résultat
Algorithm 'Contour' finished`

**Comment by gioman** [comment]
is this anyhow related to https://github.com/qgis/QGIS/issues/32753 ? @luipir

**Comment by luipir** [comment]
> is this anyhow related to #32753 ? @luipir

I do not think so, #32753 is related strictly to rastercalculator and related to variable mapping inside rastr calculator formula when there is a translation. This error should be more related with the move from  unicode to str in py2 to py3 => regression.

**Comment by mfestini** [comment]
I have the same problem, also with Tutorial rasters provided with Qgis training manual.

SO Windows 10 Pro release 1909 (buid 18363.720) **italian language**
QGis Installed trough OSGeo4W
I've tried with several GDAL routines as Virtual Raster, Merge, Hillshade wiht the same output error.
I've tried also changing interface language but no difference at all.
Same problem with last QGis version 3.12 (desktop installation).
 
 _________________________________________________________________________________

QGIS version: 3.10.3-A Coruña
QGIS code revision: 0e1f846438
Qt version: 5.11.2
GDAL version: 3.0.4
GEOS version: 3.8.1-CAPI-1.13.3
PROJ version: Rel. 6.3.1, February 10th, 2020
Algoritmo in esecuzione...
In avvio l'algoritmo 'Crea raster virtuale' …
Input parameters:
{ 'ADD_ALPHA' : False, 'ASSIGN_CRS' : None, 'EXTRA' : '', 'INPUT' : ['D:/GIS_DB/Cartografia/_CTR/10000_Raster/017110_Cavallino/017110.tif','D:/GIS_DB/Cartografia/_CTR/10000_Raster/017150_Longerin/017150.tif','D:/GIS_DB/Cartografia/_CTR/10000_Raster/030030_S_Stefano/030030.tif'], 'OUTPUT' : 'D:/GIS_DB/Cartografia/_Comuni/SN/CTR_10kR_V_SN.vrt', 'PROJ_DIFFERENCE' : False, 'RESAMPLING' : 0, 'RESOLUTION' : 0, 'SEPARATE' : True, 'SRC_NODATA' : '' }

GDAL command:
gdalbuildvrt -resolution average -separate -r nearest -input_file_list C:\Users\marco\AppData\Local\Temp/processing_2586372e00a84eb9967ee0ad3c76e9bf/1ccc9aeadc79478ca4e872b5ebed10e0/buildvrtInputFiles.txt D:/GIS_DB/Cartografia/_Comuni/SN/CTR_10kR_V_SN.vrt
GDAL command output:
Traceback (most recent call last):
File "C:/OSGEO4~1/apps/qgis-ltr/./python/plugins\processing\algs\gdal\GdalAlgorithm.py", line 137, in processAlgorithm
GdalUtils.runGdal(commands, feedback)
File "C:/OSGEO4~1/apps/qgis-ltr/./python/plugins\processing\algs\gdal\GdalUtils.py", line 106, in runGdal
for line in proc.stdout:
File "C:\OSGEO4~1\apps\Python37\lib\codecs.py", line 322, in decode
(result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8a in position 58: invalid start byte

Execution failed after 0.16 seconds

Caricamento layer
Algorithm 'Crea raster virtuale' finished
---------------------------------------------------------------------------------------

QGIS version: 3.10.3-A Coruña
QGIS code revision: 0e1f846438
Qt version: 5.11.2
GDAL version: 3.0.4
GEOS version: 3.8.1-CAPI-1.13.3
PROJ version: Rel. 6.3.1, February 10th, 2020
Processing algorithm…
Algorithm 'Merge' starting…
Input parameters:
{ 'DATA_TYPE' : 5, 'EXTRA' : '', 'INPUT' : ['D:/GIS/exercise_data/raster/3320C_2010_314_RGB_LATLNG.tif','D:/GIS/exercise_data/raster/3320D_2010_315_RGB_LATLNG.tif','D:/GIS/exercise_data/raster/3420B_2010_328_RGB_LATLNG.tif','D:/GIS/exercise_data/raster/3420C_2010_327_RGB_LATLNG.tif'], 'NODATA_INPUT' : None, 'NODATA_OUTPUT' : None, 'OPTIONS' : '', 'OUTPUT' : '//serverdominio/UnioneComelico/marco/Desktop/test.vrt', 'PCT' : False, 'SEPARATE' : False }

GDAL command:
python3 -m gdal_merge -ot Float32 -of VRT -o //serverdominio/UnioneComelico/marco/Desktop/test.vrt --optfile C:\Users\marco\AppData\Local\Temp/processing_9e57b2354c87459d966dc2e83969acdb/ad8647a9c1604e0cb38ee501d606236d/mergeInputFiles.txt
GDAL command output:
Traceback (most recent call last):
File "C:/OSGEO4~1/apps/qgis-ltr/./python/plugins\processing\algs\gdal\GdalAlgorithm.py", line 137, in processAlgorithm
GdalUtils.runGdal(commands, feedback)
File "C:/OSGEO4~1/apps/qgis-ltr/./python/plugins\processing\algs\gdal\GdalUtils.py", line 106, in runGdal
for line in proc.stdout:
File "C:\OSGEO4~1\apps\Python37\lib\codecs.py", line 322, in decode
(result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8a in position 58: invalid start byte

Execution failed after 4.30 seconds

Loading resulting layers
Algorithm 'Merge' finished
----------------------------------------------------------------------------------------------

**Comment by gioman** [comment]
> SO Windows 10 Pro release 1909 (buid 18363.720) **italian language**
> QGis Installed trough OSGeo4W
> I've tried with several GDAL routines as Virtual Raster, Merge, Hillshade wiht the same output error.
> I've tried also changing interface language but no difference at all.
> Same problem with last QGis version 3.12 (desktop installation).

@mfestini just tested:

downloaded Windows 10 ISO pro in Italian

installed Win 10

installed QGIS 3.10.3 with osgeo4w installer > it defaults to Italian

loaded a DEM

tried the GDAL based hillshade tool > it works

tried GDAL merge > works

**Comment by mfestini** [comment]
> 
> 
> > SO Windows 10 Pro release 1909 (buid 18363.720) **italian language**
> > QGis Installed trough OSGeo4W
> > I've tried with several GDAL routines as Virtual Raster, Merge, Hillshade wiht the same output error.
> > I've tried also changing interface language but no difference at all.
> > Same problem with last QGis version 3.12 (desktop installation).
> 
> @mfestini just tested:
> 
> downloaded Windows 10 ISO pro in Italian
> 
> installed Win 10
> 
> installed QGIS 3.10.3 with osgeo4w installer > it defaults to Italian
> 
> loaded a DEM
> 
> tried the GDAL based hillshade tool > it works
> 
> tried GDAL merge > works

Ok, maybe something gone wrong in my installation process... the question now is:
how could I completely uninstall QGis and every related packet in order to perform a new clean installation?
thanks a lot

**Comment by ClemDut** [comment]
Hi,

I think I have a similar issue using some Gdal treatments.

system : windows 8.1, french 

QGis installed  through OSgeo4w. I tried to uninstall/reinstall Qgis trhough OSGeo4w but still the same problem.

Problem persists with older version of Qgis 3.4 and 2.18 wich where on my machine before i tried to uninstall everything. 


---

```
Version de QGIS : 3.10.4-A Coruña
Révision du code : 10bc9f2ff2
Version de Qt : 5.11.2
Version de GDAL : 3.0.4
Version de GEOS : 3.8.1-CAPI-1.13.3
Version de Proj : Rel. 6.3.1, February 10th, 2020
Traitement de l'algorithme…
Démarrage de l'algorithme 'Tamiser'…
Input parameters:
{ 'EIGHT_CONNECTEDNESS' : False, 'EXTRA' : '', 'INPUT' : 'C:/Users/Admin/AppData/Local/Temp/processing_af7f93a579514ee08dfad00d7a097b7a/ecd58e731ded4fb7b556798745946def/OUTPUT.tif', 'MASK_LAYER' : None, 'NO_MASK' : False, 'OUTPUT' : 'TEMPORARY_OUTPUT', 'THRESHOLD' : 10 }

GDAL command:
python3 -m gdal_sieve -st 10 -4 -of GTiff C:/Users/Admin/AppData/Local/Temp/processing_af7f93a579514ee08dfad00d7a097b7a/ecd58e731ded4fb7b556798745946def/OUTPUT.tif C:/Users/Admin/AppData/Local/Temp/processing_af7f93a579514ee08dfad00d7a097b7a/cc0f95da581048b0815010025ed177a0/OUTPUT.tif
GDAL command output:
Traceback (most recent call last):
File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python/plugins\processing\algs\gdal\GdalAlgorithm.py", line 137, in processAlgorithm
GdalUtils.runGdal(commands, feedback)
File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python/plugins\processing\algs\gdal\GdalUtils.py", line 108, in runGdal
for line in proc.stdout:
File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\codecs.py", line 322, in decode
(result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 983: invalid continuation byte

Execution failed after 0.93 seconds

Chargement des couches de résultat
Algorithm 'Tamiser' finished
Version de QGIS : 3.10.4-A Coruña
Révision du code : 10bc9f2ff2
Version de Qt : 5.11.2
Version de GDAL : 3.0.4
Version de GEOS : 3.8.1-CAPI-1.13.3
Version de Proj : Rel. 6.3.1, February 10th, 2020
Traitement de l'algorithme…
Démarrage de l'algorithme 'Tamiser'…
Input parameters:
{ 'EIGHT_CONNECTEDNESS' : False, 'EXTRA' : '', 'INPUT' : 'D:/2020_RISQO_CD/04_TRAITEMENTS/01_MODELE_RUISSELLEMENT/01_SAGA/02_RESULT/POST_TRAITEMENT/areamod_res1_reclass4.tif', 'MASK_LAYER' : None, 'NO_MASK' : False, 'OUTPUT' : 'TEMPORARY_OUTPUT', 'THRESHOLD' : 10 }

GDAL command:
python3 -m gdal_sieve -st 10 -4 -of GTiff D:\2020_RISQO_CD\04_TRAITEMENTS\01_MODELE_RUISSELLEMENT\01_SAGA\02_RESULT\POST_TRAITEMENT\areamod_res1_reclass4.tif C:/Users/Admin/AppData/Local/Temp/processing_af7f93a579514ee08dfad00d7a097b7a/28847b804ca2488f9595c70f36530c9e/OUTPUT.tif
GDAL command output:
Traceback (most recent call last):
File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python/plugins\processing\algs\gdal\GdalAlgorithm.py", line 137, in processAlgorithm
GdalUtils.runGdal(commands, feedback)
File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python/plugins\processing\algs\gdal\GdalUtils.py", line 108, in runGdal
for line in proc.stdout:
File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\codecs.py", line 322, in decode
(result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 983: invalid continuation byte

Execution failed after 0.19 seconds
```

----


thanks a lot if someone find the solution :)

**Comment by gioman** [comment]
> system : windows 8.1, french

@ClemDut please test on a completely clean system (i.e. a VM, you can download any Windows iso in any language from MS site).

**Comment by m-kuhn** [comment]
Issue reproduced on a German windows, QGIS 3.12 with "vector to raster".

Interestingly, "raster to vector" works fine on the same system.

Running a test now if `universal_newlines=False` fixes the behavior.

**Comment by wylie2121** [comment]
I have the same problem when I try to use the GDAL Build Virtual Raster tool. I am following the QGIS Training Manual lesson 8.1.2.

I am working in QGIS 3.4.10-Madeira on a MAcBookPro running MacOS10.14.6 Mojave. 
When I select the input raster layers and hit OK, the tool crashes.

**Comment by gioman** [comment]
> Issue reproduced on a German windows, QGIS 3.12 with "vector to raster".
> 
> Interestingly, "raster to vector" works fine on the same system.
> 
> Running a test now if `universal_newlines=False` fixes the behavior.

@m-kuhn what is the status of this issue? did you tested your solution?

**Comment by m-kuhn** [comment]
It didn't fix it and right now I don't have access anymore to the affected system.

**Comment by gioman** [comment]
Just tested Processing/GDAL on a fresh Win10 machine with DE langauage and QGIS installed with the standalone installer (used data from the QGIS sample dataset). Seems all ok to me. Please reopen if necessary.

**Comment by guenterhack** [comment]
The problem persists on Windows 10/ QGIS 3.14.1. Same machine, two different profiles. One with an Umlaut in the home directory path and the other without. The first one doesn't work, the second works perfectly.

**Comment by gioman** [comment]
> One with an Umlaut in the home directory

@guenterhack do you mean that the accent is in the Windows user name (that is reflected in the user folder in c:\users)? I downloaded and installed Windows 10 in DE and tested the described scenario, without being able to replicate. Probably there is something more going on on the machine you are using.

**Comment by guenterhack** [comment]
Yes, it's an umlaut in the Windows user name. Same machine, same installation. I'm at a loss.

**Comment by m-kuhn** [comment]
@guenterhack would you be available for a remote support session so we can run some tests on your machine?

**Comment by guenterhack** [comment]
It's a machine managed by corporate IT dept., so remote control is not an option, I'm afraid. Thank you for your help, I will continue to use the working account for QGIS tasks.

**Comment by m-kuhn** [comment]
Great. In case it gains priority, you can also contact me by mail and we can setup an agreement for your IT dept.

**Comment by gioman** [comment]
@guenterhack this

gdalwarp -s_srs EPSG:3763 -t_srs EPSG:4326 -r near -of GTiff C:/Users/**jöao**/Desktop/mdt_portugal.tif C:/Users/**jöao**/AppData/Local/Temp/processing_tcySrK/8729c0686ba64c39bfa3b6b01e4f4c27/OUTPUT.tif

worked with no issues here.

**Comment by nicogodet** [comment]
I start to experience the same issue.


```
GDAL command output:
Traceback (most recent call last):
File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\algs\gdal\GdalAlgorithm.py", line 138, in processAlgorithm
GdalUtils.runGdal(commands, feedback)
File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\algs\gdal\GdalUtils.py", line 108, in runGdal
for line in proc.stdout:
File "C:\OSGEO4~1\apps\Python37\lib\codecs.py", line 322, in decode
(result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 102: invalid continuation byte

Execution failed after 0.27 seconds
```

Full reinstall of Qgis 3.16 with OsGeo4W.
Tried on clean profile.

universal_newlines=False do not fix the issue : TypeError: QgsProcessingFeedback.pushConsoleInfo(): argument 1 has unexpected type 'bytes'

**Comment by gioman** [comment]
>  Tried French and English Qgis UI without succes

@nicogodet does the input file name/path or output filename/path have special chars in it?

**Comment by nicogodet** [comment]
@gioman 
`gdalwarp -of GTiff -cutline E:/D/DONNEES_SIG/__ETUDES/16F135/DOSSIER_Modeles_hydrauliques/1_Modeles/TELEMAC2D/ISAKA/lm_isaka.shp -cl lm_isaka -crop_to_cutline E:/D/DONNEES_SIG/__ETUDES/16F135/DOSSIER_Modeles_hydrauliques/1_Modeles/TELEMAC2D/ISAKA/T2D_ISAKA_Q100_VivesEaux/IsakaQ100.tif C:/Users/godet/AppData/Local/Temp/processing_vnbUDu/8f42145ac57e4f7f9cd9a9b6d8f7a6a6/OUTPUT.tif`

No.

**Comment by gioman** [comment]
> @gioman
> `gdalwarp -of GTiff -cutline E:/D/DONNEES_SIG/__ETUDES/16F135/DOSSIER_Modeles_hydrauliques/1_Modeles/TELEMAC2D/ISAKA/lm_isaka.shp -cl lm_isaka -crop_to_cutline E:/D/DONNEES_SIG/__ETUDES/16F135/DOSSIER_Modeles_hydrauliques/1_Modeles/TELEMAC2D/ISAKA/T2D_ISAKA_Q100_VivesEaux/IsakaQ100.tif C:/Users/godet/AppData/Local/Temp/processing_vnbUDu/8f42145ac57e4f7f9cd9a9b6d8f7a6a6/OUTPUT.tif`

@nicogodet I guess that the above works fine when run from the CLI, right?

**Comment by nicogodet** [comment]
@gioman 

Qgis:
```
QGIS version: 3.16.0-Hannover
QGIS code revision: 43b64b13f3
Qt version: 5.11.2
GDAL version: 3.1.4
GEOS version: 3.8.1-CAPI-1.13.3
PROJ version: Rel. 6.3.2, May 1st, 2020
Processing algorithm…
Algorithm 'Clip raster by mask layer' starting…
Input parameters:
{ 'ALPHA_BAND' : False, 'CROP_TO_CUTLINE' : True, 'DATA_TYPE' : 0, 'EXTRA' : '', 'INPUT' : 'D:/r.tif', 'KEEP_RESOLUTION' : False, 'MASK' : 'D:/layer.shp', 'MULTITHREADING' : False, 'NODATA' : None, 'OPTIONS' : '', 'OUTPUT' : 'D:/test.tif', 'SET_RESOLUTION' : False, 'SOURCE_CRS' : None, 'TARGET_CRS' : None, 'X_RESOLUTION' : None, 'Y_RESOLUTION' : None }

GDAL command:
gdalwarp -of GTiff -cutline D:/layer.shp -cl layer -crop_to_cutline D:\r.tif D:/test.tif
GDAL command output:
Traceback (most recent call last):
File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\algs\gdal\GdalAlgorithm.py", line 138, in processAlgorithm
GdalUtils.runGdal(commands, feedback)
File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\algs\gdal\GdalUtils.py", line 108, in runGdal
for line in proc.stdout:
File "C:\OSGEO4~1\apps\Python37\lib\codecs.py", line 322, in decode
(result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 102: invalid continuation byte

Execution failed after 0.13 seconds

Loading resulting layers
Algorithm 'Clip raster by mask layer' finished
```
CLI:
```
C:\OSGeo4w64\bin>gdalwarp -of GTiff -cutline D:/layer.shp -cl layer -crop_to_cutline D:\r.tif D:\test.tif
ERROR 1: Can't load requested DLL: C:\OSGEO4~1\bin\gdalplugins\ogr_MSSQLSpatial.dll
126: Le module spÚcifiÚ est introuvable.

ERROR 1: Can't load requested DLL: C:\OSGEO4~1\bin\gdalplugins\ogr_MSSQLSpatial.dll
126: Le module spÚcifiÚ est introuvable.

ERROR 1: Can't load requested DLL: C:\OSGEO4~1\bin\gdalplugins\ogr_MSSQLSpatial.dll
126: Le module spÚcifiÚ est introuvable.

ERROR 1: Can't load requested DLL: C:\OSGEO4~1\bin\gdalplugins\ogr_MSSQLSpatial.dll
126: Le module spÚcifiÚ est introuvable.

Creating output file that is 1217P x 774L.
Processing D:\r.tif [1/1] : 0Using internal nodata values (e.g. 255) for image D:\r.tif.
Copying nodata values from source D:\r.tif to destination D:\test.tif.
...10...20...30...40...50...60...70...80...90...100 - done.
```

So we have some errors.

**Comment by stinanickel** [comment]
Dear QGIS-Family,

I use the latest Version of QGIS in German on Mac OS 10.14.6 and wanted to merge some 100 .asc files. I could load them into QGIS, but when merging with GDAL the following error occurred and no new layer was produced. I tried to install GDAL3.3 and python 3.9 externaly, but it seems QGIS doesn't makes use of them. My solution was to use an old installation of QGIS 3.10 on Mac OS 10.13, where evything worked fine. Hope this helps to improve next versions.


> 132260_2633500_1257000.asc" "/Users/dt/Desktop/PROJEKT ERGOLZ/DTM itingen bis ormalingen 5m/132260_2633500_1257500.asc" "/Users/dt/Desktop/PROJEKT ERGOLZ/DTM itingen bis ormalingen 5m/132260_2633500_1258000.asc" "/Users/dt/Desktop/PROJEKT ERGOLZ/DTM itingen bis ormalingen 5m/132260_2633500_1258500.asc"
> 2021-02-07T00:11:16     INFO    GDAL execution console output
>              Traceback (most recent call last):
>              
>               File "/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/GDAL-3.1.2-py3.7-macosx-10.13.0-x86_64.egg/osgeo/__init__.py", line 18, in swig_import_helper
>              
>               return importlib.import_module(mname)
>              
>               File "/Applications/QGIS.app/Contents/MacOS/lib/python3.7/importlib/__init__.py", line 127, in import_module
>              
>               return _bootstrap._gcd_import(name[level:], package, level)
>              
>               File "", line 1006, in _gcd_import
>              
>               File "", line 983, in _find_and_load
>              
>               File "", line 967, in _find_and_load_unlocked
>              
>               File "", line 670, in _load_unlocked
>              
>               File "", line 583, in module_from_spec
>              
>               File "", line 1043, in create_module
>              
>               File "", line 219, in _call_with_frames_removed
>              
>              ImportError: dlopen(/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/GDAL-3.1.2-py3.7-macosx-10.13.0-x86_64.egg/osgeo/_gdal.cpython-37m-darwin.so, 2): Symbol not found: _curl_mime_addpart
>              
>               Referenced from: /Applications/QGIS.app/Contents/MacOS/bin/../lib/libgdal.27.dylib
>              
>               Expected in: /usr/lib/libcurl.4.dylib
>              
>               in /Applications/QGIS.app/Contents/MacOS/bin/../lib/libgdal.27.dylib
>              
>              
>              
>              During handling of the above exception, another exception occurred:
>              
>              
>              
>              Traceback (most recent call last):
>              
>               File "/Applications/QGIS.app/Contents/MacOS/bin/gdal_retile.py", line 4, in 
>              
>               __import__('pkg_resources').run_script('GDAL==3.1.2', 'gdal_retile.py')
>              
>               File "/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/pkg_resources/__init__.py", line 667, in run_script
>              
>               self.require(requires)[0].run_script(script_name, ns)
>              
>               File "/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1464, in run_script
>              
>               exec(code, namespace, namespace)
>              
>               File "/Applications/QGIS.app/Contents/Resources/python/site-packages/GDAL-3.1.2-py3.7-macosx-10.13.0-x86_64.egg/EGG-INFO/scripts/gdal_retile.py", line 36, in 
>              
>               from osgeo import gdal
>              
>               File "/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/GDAL-3.1.2-py3.7-macosx-10.13.0-x86_64.egg/osgeo/__init__.py", line 32, in 
>              
>               _gdal = swig_import_helper()
>              
>               File "/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/GDAL-3.1.2-py3.7-macosx-10.13.0-x86_64.egg/osgeo/__init__.py", line 31, in swig_import_helper
>              
>               return importlib.import_module('_gdal')
>              
>               File "/Applications/QGIS.app/Contents/MacOS/lib/python3.7/importlib/__init__.py", line 127, in import_module
>              
>               return _bootstrap._gcd_import(name[level:], package, level)
>              
>              ModuleNotFoundError: No module named '_gdal'

**Comment by roya0045** [comment]
@stinanickel yours may be mac specific. @gioman Do you think this should be a separate issue?

**Comment by stinanickel** [comment]
@roya0045 Never tried QGIS for Windows or Linux...

**Comment by gioman** [comment]
> @roya0045 Never tried QGIS for Windows or Linux...

@stinanickel I can test on macOS, but not in German.

**Comment by stinanickel** [comment]
If merging raster layers with GDAL works well in Your QGIS 3.16 (I used
MacBook Pro 2019 and OS 10.14.6) it could be a problem of the German
Version only. German QGIS 3.10 on macMini2011 with Mac OS 10.13 worked
well. Thanks for Your help!

**Comment by gioman** [comment]
> If merging raster layers with GDAL works well in Your QGIS 3.16 (I used MacBook Pro 2019 and OS 10.14.6) it could be a problem of the German Version only. German QGIS 3.10 on macMini2011 with Mac OS 10.13 worked well.

@stinanickel I'm confused. In what circumstances that operation fails? with QGIS 3.16 in german? works ok on 3.10 in german? is your macOS in german or english?

**Comment by stinanickel** [comment]
Sorry all my Mac OS systems are German. I used a quite old Macmini (latest
Mac OS 10.13 High Sierra), still with QGIS 3.10, now I upgraded to a
MacbookPro (latest Mac OS 10.14 Mojave) with QGIS 3.16. The old setup does
GDAL merging, the new one does not. Thanks! Does it work in Your QGIS 3.16?

**Comment by PeterPetrik** [comment]
hi, @stinanickel issue is different than the problem described in this tickets. created new issue https://github.com/qgis/QGIS-Mac-Packager/issues/111 for that, please let use that ticket for further discussions.

**Comment by d-lombardi-a** [comment]
Hi, I'm experiencing the same issue described  above on a windows10 pc. Running various gdal processing tool in qgis give me the following error:
![image](https://user-images.githubusercontent.com/53909185/152119485-e9ca1d93-6f26-482d-aa57-d31eef9ff584.png)

Tried also on another windows10 workstation with QGIS freshly installed (same version as in the image above) with same result.

The same command from CLI works fine.

Any suggestion on how to solve this issue?
Thanks
Best regards

**Comment by gioman** [comment]
> Hi, I'm experiencing the same issue described above on a windows10 pc.

@d-lombardi-a you are using 3.18.5 which is too old. 3.16 is in anyway end of the line, so you must test 3.22.3, on a new QGIS profile. If the problem persist attach a sample of the data you are using.

**Comment by stinanickel** [comment]
Tested GDAL Extraction. It  seems to work fine (expoted as .xyz) on Mac Os
14.6 in QGIS 3.20 (German)...

**Comment by d-lombardi-a** [comment]
> > Hi, I'm experiencing the same issue described above on a windows10 pc.
> 
> @d-lombardi-a you are using 3.18.5 which is too old. 3.16 is in anyway end of the line, so you must test 3.22.3, on a new QGIS profile. If the problem persist attach a sample of the data you are using.

@gioman update to 3.22 is not a viable option; tried to run with new user profile on the same installed version (3.16.5) and it seems to work fine. I wonder wich profile's configuration brokes things up... do you have any idea?
Many thanks
