### ISSUE TITLE
QGIS WFS stripping of viewparam KVP from WFS Feature Requests

### ISSUE THREAD

**Issue by palmerj** [qgis/QGIS#31026]
**Describe the bug**
For our WFS service on https://data.linz.govt.nz we use the viewparams KVP request option to provide a data changesets extension over the top of WFS 1.1 and 2.0. This viewparam option is supported in Geoserver https://docs.geoserver.org/stable/en/user/data/database/sqlview.html. This support is for all of our vector layers where we have a primary key defined and can be URLs can be generated when the user is logged in. e.g https://data.linz.govt.nz/layer/50772-nz-primary-parcels/history/

An example URL is: 

https://data.linz.govt.nz/services;key=42eb71dd76a84b3d8b2e69a7b96a4d57/wfs/layer-50772-changeset?SERVICE=WFS&REQUEST=GetCapabilities&viewparams=from:2019-07-20T06:17:24.767945Z;to:2019-07-27T00:31:26.575136Z

In QGIS 2.18 the WFS provider will load this URL ok and fetch the data. However under QGIS 3.4 and 3.8 for each GetFeature request the viewparams KVP is stripped off and the query no longer work (returns 0 features). e.g:

http://data.linz.govt.nz/services;key=42eb71dd76a84b3d8b2e69a7b96a4d57/wfs/layer-50772-changeset?SERVICE=WFS&REQUEST=GetFeature&VERSION=2.0.0&TYPENAMES=data.linz.govt.nz:layer-50772-changeset&TYPENAME=data.linz.govt.nz:layer-50772-changeset&STARTINDEX=0&COUNT=12000000&SRSNAME=urn:ogc:def:crs:EPSG::4167&BBOX=-52.47523994920035761,164.42657957612391328,-27.91622356177029474,185.88148236811673542,urn:ogc:def:crs:EPSG::4167

I know the viewparams is not part of the standard, but it certainly was great that QGIS supported it. 

Is this WFS provider change intensional or a side effect of some other WFS provider changes? In any case can this functionality please be added back?

**QGIS and OS versions**

Tested to be an issue in all OS versions with QGIS 3.4.3 and 3.8.1

**Additional context**

See old closed issue #27339 and https://gis.stackexchange.com/questions/317573/request-wfs-data-using-geoservers-viewparams-with-pyqgis

**Comment by palmerj** [comment]
@rouault do you have any idea about this?

**Comment by palmerj** [comment]
Thanks so much @rouault. Tested and working for our service!

**Comment by rouault** [comment]
> Tested and working for our service!

Great. I'd be interested to know the opinion of the server developers regarding if the additional parameters should be in the DCP HTTP URLs returned in the GetCapabilities response. I guess this might be a unspecified area of OWS / WFS (didn't find anything regarding this when looking quickly at the standard documents)

**Comment by palmerj** [comment]
Our setup is pretty much geoserver viewparams out of the box. Maybe geoserver developers can comment. CC @aaime

**Comment by aaime** [comment]
Vendor parameters might be declared in the capabilities document, sure, but I don't think it's a requirement. For sure GeoServer has been using lots of vendor parameters, in many places, without ever declaring one. Even if it was required, it would take 5-10 years before most installations are updated to a version that does. It's also a matter of merely deciding of being "right" vs being practical.
