### ISSUE TITLE
GRASS v.build.polylines dosn't work in Qgis 3.4.10

### ISSUE THREAD

**Issue by Manalemart** [qgis/QGIS#31037]
In reference to issue #30680, Grass dosn't work in Qgis 3.4 to 3.8 

I'm tested various GRASS algorithms and dosn't works with Qgis 3.4.10 from the Qgis process window.

> The specified GRASS 7 folder "C:\PROGRA~1\QGIS3~1.4\bin\bin" does not contain a valid set of GRASS 7 modules. Please, go to the Processing settings dialog, and check that the GRASS 7 folder is correctly configured 

checked in 3 computers from the same office

**Comment by alexbruy** [comment]
Do you have GRASS installed?

**Comment by Manalemart** [comment]
Yes, it's the first I revised.
Grass is correctly installed, with cmd osgeo shell Grass correctly function

**Comment by gioman** [comment]
>  Grass is correctly installed, with cmd osgeo shell Grass correctly function

have you tried on a new/clean QGIS profile?

**Comment by Manalemart** [comment]
Yes, I reinstalled all the package OSGEO in differents computers, and the error repeat in all. With clear installation Qgis profile

**Comment by gioman** [comment]
Are you running QGIS using the "with GRASS" shortcut?

**Comment by Manalemart** [comment]
Yes, in all the computers we made de prove I running "QGIS with GRASS".

**Comment by alexbruy** [comment]
I can not reproduce usin 3.4, 3.8 and master both on Windows and Linux.

**Comment by gioman** [comment]
> I can not reproduce usin 3.4, 3.8 and master both on Windows and Linux.

I also think that this is probably a local issue.

**Comment by alexbruy** [comment]
Ok, closing then

**Comment by roya0045** [comment]
Did OP check the Grass integration in processing as suggested by the error message?
