### ISSUE TITLE
nextval does not work with postgres view

### ISSUE THREAD

**Issue by magnus-m** [qgis/QGIS#31038]
**Describe the bug**
QGIS will auto insert a nextval command when inserting to a PostgreSQL table containing a serial column.
This does not work for a view, pointing to the same table.

**How to Reproduce**

1. 
```
create table schema_name.table_name (
id SERIAL PRIMARY KEY,
name varchar,
geom geometry(Geometry,25832)
);
```
2.
```
create view as (
select from schema_name.table_name
where name != 'something'
);
```
3. load both tables into QGIS

4. insert new geometry in both tables

table
![image](https://user-images.githubusercontent.com/19188046/62294162-afc58000-b46a-11e9-82c6-3800e7c9e041.png)

view
![image](https://user-images.githubusercontent.com/19188046/62294214-c075f600-b46a-11e9-8380-8e4b4060a364.png)

**QGIS 3.8, Windows 10**

QGIS version | 3.8.0-Zanzibar | QGIS code revision | 11aff65f10
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.0 | Running against GEOS | 3.7.2-CAPI-1.11.0 b55d2125
PostgreSQL Client Version | 9.2.4 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Windows 10 (10.0) |   |

**Comment by magnus-m** [comment]
Issue seems to duplicate this https://github.com/qgis/QGIS/issues/26474

**Comment by AchilleAsh** [comment]
Hi,
It's related to Postgresql, not really QGIS fault.

Given your example:

```sql
create table foo (
id SERIAL PRIMARY KEY,
name varchar,
geom geometry(Geometry,25832)
);

\d foo     
                                     Table "public.foo"
 Column |           Type           | Collation | Nullable |             Default             
--------+--------------------------+-----------+----------+---------------------------------
 id     | integer                  |           | not null | nextval('foo_id_seq'::regclass)
 name   | character varying        |           |          | 
 geom   | geometry(Geometry,25832) |           |          | 
Indexes:
    "foo_pkey" PRIMARY KEY, btree (id)


create view foo_view AS (
select * from foo
WHERE name != 'bar'
);

\d foo_view
                       View "public.foo_view"
 Column |           Type           | Collation | Nullable | Default 
--------+--------------------------+-----------+----------+---------
 id     | integer                  |           |          | 
 name   | character varying        |           |          | 
 geom   | geometry(Geometry,25832) |           |          | 
```

Note that the SQL default of the view is not inherited from the underlying table: that's why QGIS does not have an automatic default, because there is none.
To add the default on the view, simply alter the view with the default from the table:

```sql 
ALTER VIEW foo_view ALTER COLUMN id SET DEFAULT nextval('foo_id_seq'::regclass);

\d foo_view
                                   View "public.foo_view"
 Column |           Type           | Collation | Nullable |             Default             
--------+--------------------------+-----------+----------+---------------------------------
 id     | integer                  |           |          | nextval('foo_id_seq'::regclass)
 name   | character varying        |           |          | 
 geom   | geometry(Geometry,25832) |           |          | 
```

This will add the same SQL default on the view and now QGIS will properly use the default (sucessfully tested on QGIS 3.4.9)

**Comment by magnus-m** [comment]
@AchilleAsh, very helpful explanation. 
Thank you very much!
