### ISSUE TITLE
WFS 1.0 request with GML3 instead of GML2

### ISSUE THREAD

**Issue by griwout** [qgis/QGIS#31034]
We have a WFS-Server that can only deliver WFS 1.0 with GML2 correctly.
In QGIS we can select WFS 1.0, but the WFS-request fo QGIS always contains GML3. The definition of WFS 1.0 specifies GML2.
Is there a possiblity to force QGIS to send the WFS-request with GML2?
Or is there a bugfix?

 ![wfs_definition](https://user-images.githubusercontent.com/33564294/62276521-25febe00-b43c-11e9-958a-769684aa3627.png)
![wfs_request](https://user-images.githubusercontent.com/33564294/62276524-272feb00-b43c-11e9-93d1-cd8d6b18103d.png)

**Comment by gioman** [comment]
@griwout Did it worked as expected in a previous version, especially on our old LTR (QGIS 2.18)?

**Comment by griwout** [comment]
We have tested with the following versions and it does not work with all of them:
QGIS 3.8 Zanzibar
QGIS3 3.4 (stable version) 
QGIS 2.18 (old stable version)

**Comment by griwout** [comment]
With the versions 2.0.1 (Dufour) and 2.8.1 (Wien) it works. But we can not tell the users to install and use these old versions ;-(

**Comment by gioman** [comment]
> With the versions 2.0.1 (Dufour) and 2.8.1 (Wien) it works. But we can not tell the users to install and use these old versions ;-(

the question is necessary just to establish if is a regression.

**Comment by rouault** [comment]
@griwout GML3 will be requested only for WFS 1.0 if the GetCapabilities response of the server advertizes it supports it. So it is probably a misconfiguration of the server

For reference support for GML3 in WFS 1.0 was added per
```
commit 852f01b0f92d79b5786ef2f63c6c329067128e88
Author: Even Rouault <even.rouault@spatialys.com>
Date:   Tue Mar 14 14:05:55 2017 +0100

    [WFS provider] Select GML3 output format for WFS 1.0 when available
    
    Some WFS servers like QGIS servers can expose GML3 output format for GetFeature
    requests, which enable to retrieve curve geometries, instead of linearized ones
    with the default GML2 output format. So use GML3 when advertized, and that
    no explicit outputFormat is passed in the URI.
```
One potential workaround if you cannot fix the server is to add `&OUTPUTFORMAT=GML2` to the connection string
