### ISSUE TITLE
Remove color scheme doesn't work

### ISSUE THREAD

**Issue by gisnederland** [qgis/QGIS#31036]
In the _settings-options-colors_ dialog  I can arrange my color palettes.
Adding and importing works fine, removing a palette howerver doesn't work. I get a confirmation dialog ("are you sure you want to remove [palette name]) , but clicking OK doesn't remove the palette.
After adding a color to the new palette, switch to a different pallette, switch back to the newly added palette I am able to remove the newly added palette,

QGis 3.8.0 / Win10 (x64)

**Comment by suricactus** [comment]
This is true still valid I will fix that.
