### ISSUE TITLE
Geopackage date of modification changes without any changes

### ISSUE THREAD

**Issue by saberraz** [qgis/QGIS#31044]
I have a geopackage database (osm.gpkg) in my project. It is set to read-only under Project Properties.

When I open the project and close the project, the time stamp for data of modification changes, even if I don't make any edits. I can see that QGIS adds shm and wal files to all my gpkg databases, as soon as I open the project.

**Comment by roya0045** [comment]
Is this issue only within qgis or does it occur when opening any gpkg with a provider?

Also is the geopackage in the DB manager?

**Comment by saberraz** [comment]
I have not tried it in other software packages.

No, I opened it directly as a file.

**Comment by gioman** [comment]
You can try disabling WAL, in the python console:

QSettings().setValue("/qgis/walForSqlite3", False)

**Comment by kannes** [comment]
Dupe of https://github.com/qgis/QGIS/issues/23991

It's seriously annoying if you synchronize and/or backup your stuff.

**Comment by saberraz** [comment]
@gioman this can have some unintended consequences if your file is on a network drive with multiple users accessing the same file. I can close this in favour of #23991
