### ISSUE TITLE
How to build QGIS from source with spatialite configured with --disable-proj?

### ISSUE THREAD

**Issue by rsbivand** [qgis/QGIS#31040]
I am not installing binary because I need to run with full control of source provenance of the geospatial stack for R development. I do not use QGIS, but need to know how sensitive it is to PROJ 6 migration.

I'm struggling to build QGIS from source (3.8.1) on Fedora 29. I have PROJ 6.1.1, GDAL 3.0.1, GEOS 3.7.2 all built from source, they are all found by cmake. Problems start with spatialite, because neither 4.3.0 nor 5.0.0beta support PROJ 6 (they do not add the environment variable needed to continue using proj_api.h). I built spatialite 4.3.0 from source with --disable-proj --disable-examples apparently successfully. Both QGIS cmake and spatialite::make check fail on `/usr/bin/ld: /usr/local/lib/libspatialite.so: undefined reference to `gaiaTransform'`, for QGIS at step: `Linking CXX executable ../../output/bin/crssync`. 

Can I disable `crssync` and any other modules affected by spatialite's missing support for PROJ migration when building QGIS? Can I build QGIS without spatialite, even though it is given as a required dependency? I already build GDAL without spatialite for similar reasons.

**Comment by gioman** [comment]
@rsbivand please ask questions on the users or developers mailing list, thanks!

**Comment by roya0045** [comment]
@rsbivand have you checked https://www.gaia-gis.it/fossil/libspatialite/wiki?name=PROJ.6 ?

**Comment by rsbivand** [comment]
@roya0045 thanks! I'd started fossil cloning the libspatialite master source already, and find that it builds successfully against PROJ 6. I'm building QGIS now, and will report back when the make process terminates.

**Comment by rsbivand** [comment]
Got past libspatialite; failed on `Generating ui_DlgAddGeometryColumn.py` - more debugging later ...

**Comment by rsbivand** [comment]
After installing sip-devel, removing build-master and initializing it again, QGIS is built and does what I need with regard to the PROJ changes. So thanks for your patience!

**Comment by roya0045** [comment]
@rsbivand I'm glad you solved it!
