### ISSUE TITLE
r.grow.distance in the QGIS 3.8.1 with GRASS 7.6.1

### ISSUE THREAD

**Issue by dimitrisal** [qgis/QGIS#31048]
Hello

There is the following bug in the r.grow.distance in the QGIS 3.8.1 with GRASS 7.6.1

If i try to use the r.grow.distance with the setting "Output distances in meters instead of map units" I get the error "ERROR: Output distance in meters for lat/lon is only possible with 'metric=geodesic'"

There are only 4 options for metrics euclidean,manhattan,squared,maximum.

**TO FIX IT**

Find the r.grow.distance.txt in the pc and add the geodesic like the following line

QgsProcessingParameterEnum|metric|Metric|euclidean;squared;maximum;manhattan;geodesic|False|0|True

**Comment by roya0045** [comment]
Do you want to submit the PR with the fix or do you want someone else to do this.

If you want to submit it simply go to https://github.com/qgis/QGIS/blob/master/python/plugins/processing/algs/grass7/description/r.grow.distance.txt 
click the pencil icon
 make the changes 
save the changes and then I don't recall if it automatically make a PR for you or you have to make it.

**Comment by dimitrisal** [comment]
Hello I didn't know I could do that , i made the change!

**Comment by roya0045** [comment]
Don't forget to push the PR to the master branch of Qgis, otherwise the changes will only be done in your repository and not in the main project.

If you go on the code page there should now be a yellow box with a green button to compare the fork and make a pull request.

See 'Step 4' of this guide https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/ for how to contribute

**Comment by dimitrisal** [comment]
So , there is a big chance that I have no idea what I am doing , I may or may not made the change that may require your approval. If i didn't can you make the change? thanks in advance.....

**Comment by roya0045** [comment]
@dimitrisal PR seems good, I'll let the official devs do their work. Thanks for the PR!
