### ISSUE TITLE
RuntimeError: wrapped C/C++ object of type ReseauTi has been deleted 

### ISSUE THREAD

**Issue by someone191** [qgis/QGIS#31060]
I changed the selection color and this error occured and closed my QGIS. Since then it is occuring every time i try to change the color. See screencast for details:

https://1drv.ms/v/s!ApqpX_j-iQ9CgUxcTqWaaWdFd2HV

An error has occurred while executing Python code: 

RuntimeError: wrapped C/C++ object of type ReseauTi has been deleted 
Traceback (most recent call last):
  File "C:/Users/asiddiqui/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\networks\networks_provider.py", line 135, in loadAlgorithms
    self.addAlgorithm( alg )
RuntimeError: wrapped C/C++ object of type ReseauTi has been deleted

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.6.3-Noosa Noosa, 0c5774c068 

Python Path:
C:/Users/asiddiqui/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\networks
C:/OSGEO4~1/apps/qgis/./python
C:/Users/asiddiqui/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/asiddiqui/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGEO4~1/apps/qgis/./python/plugins
C:\OSGeo4W64\bin\python37.zip
C:\OSGEO4~1\apps\Python37\DLLs
C:\OSGEO4~1\apps\Python37\lib
C:\OSGeo4W64\bin
C:\OSGEO4~1\apps\Python37
C:\OSGEO4~1\apps\Python37\lib\site-packages
C:/Users/asiddiqui/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Backups/Area1/Area1_Combined

**Comment by nyalldawson** [comment]
This is an issue with the "networks" plugin, not qgis
