### ISSUE TITLE
Getting 3.4 from qgis.org/ubuntu instead of 3.8

### ISSUE THREAD

**Issue by gubuntu** [qgis/QGIS#31074]
**Describe the bug**
I expect 3.8 to be available from qgis.org/ubuntu and 3.4 from qgis.org/ubuntu-ltr but instead I get 3.4 from the ubuntu repo. 

**How to Reproduce**

Configure software sources for ubuntu according to qgis.org and install qgis with apt. 

QGIS 3.4 gets installed instead of 3.8

**QGIS and OS versions**

Ubuntu 19.04 disco

**Comment by jef-n** [comment]
With
```
deb     http://qgis.org/ubuntu          disco   main
deb     http://qgis.org/ubuntu-ltr      disco   main
```

in `sources.list`  `apt-cache policy qgis` produces

```
# apt-cache policy qgis
qgis:
  Installed: (none)
  Candidate: 1:3.8.1+30disco
  Version table:
     1:3.8.1+30disco 500
        500 http://qgis.org/ubuntu disco/main amd64 Packages
     1:3.4.10+30disco 500
        500 http://qgis.org/ubuntu-ltr disco/main amd64 Packages
```

LGTM

**Comment by gubuntu** [comment]
oops, apologies

I used https and only now see I had an expired key. All sorted now thanks.
