### ISSUE TITLE
jpeg not shown

### ISSUE THREAD

**Issue by Funfurik111** [qgis/QGIS#31075]
When exporting a layout with vectors to a Jpeg file, the ESRI Satellite is not displayed.

![село Урхучи зонирование Урхучи123123](https://user-images.githubusercontent.com/53703948/62425036-41d5be80-b6df-11e9-9941-9c55cfa14688.jpeg)

**Comment by gioman** [comment]
>  the ESRI Satellite is not displayed

how did you added this baselayer?

**Comment by alexbruy** [comment]
Closed for the lack of feedback. Please reopen if necessary.
