### ISSUE TITLE
Multiband raster not appearing in legend when "Filter Legend by Map Content"

### ISSUE THREAD

**Issue by AdvisianADB** [qgis/QGIS#31082]
QGIS Version 3.6.1

(Multiband) rasters (satellite image geo-referenced TIF files) do not appear in the legend when "Filter Legend by Map Content" is selected.
Singleband (classified) rasters do appear.

Different to #22196, #19894 which applied to previous versions (<3.0)

**Comment by gioman** [comment]
@AdvisianADB Please try with the latest 3.4 and 3.8, 3.6 is end of life and not getting any fix.

**Comment by AdvisianADB** [comment]
Tried with 3.8.1 and had same issue

**Comment by gioman** [comment]
Seems ok to me on 3.16.1. Reopen if necessary.
