### ISSUE TITLE
When scrolling down long legend graphic of a WMS, QGIS skips to next entry in the TOC so that complete legend graphic is never visible

### ISSUE THREAD

**Issue by AndreSchmiedel** [qgis/QGIS#31093]
Dear Ladies and Gentlemen,

long legend graphics in QGIS desktop are not fully displayed as the bottom end of the graphic is not reached by scrolling down. Also, when other layers are present in the table of contents below the entry for the WMS layer, QGIS skips to that other layer.  

**How to Reproduce:**

1. Load http://sgx.geodatenzentrum.de/wms_topplus_open? into QGIS.

2. Legend graphic gets displayed but not fully: even though the scroll bar is in its bottommost position only some upper portion of the legend is displayed. 

3. The complete legend graphic looks like this: http://sgx.geodatenzentrum.de/wms_topplus_open?styles=&layer=web&service=WMS&format=image%2Fpng&sld_version=1.1.0&request=GetLegendGraphic&version=1.1.1

3. In those cases where there is another item present in the table of content below the WMS entry, scrolling down results in skipping to that other item.  

**QGIS and OS versions:**

This behaviour has been observed in QGIS desktop versions 2.18, 3.0.3 and 3.8.0.

**Additional context:**

This is the exact same issue as stated in bug ticket https://github.com/qgis/QGIS/issues/28050 but unlike stated in the title of https://github.com/qgis/QGIS/pull/30227, issue 28050 **is not** fixed by 30227.

**Comment by nyalldawson** [comment]
Works fine for me:

![Peek 2019-08-06 14-05](https://user-images.githubusercontent.com/1829991/62510662-428f6180-b853-11e9-9abc-aab0f3f80185.gif)

**Comment by gioman** [comment]
Work also fine here on 3.4 on Linux.

**Comment by AndreSchmiedel** [comment]
Doesn't work in QGIS 3.8.0-Zanzibar on Windows 7. See here:

![legend](https://user-images.githubusercontent.com/53781127/62539453-85eacf80-b855-11e9-9f55-5367b91aa269.gif)

**Comment by gioman** [comment]
Windows only issue?

**Comment by Saijin-Naib** [comment]
Cannot confirm behavior under Win10.
![image](https://user-images.githubusercontent.com/19295950/62554462-2aade280-b83f-11e9-8104-af6d56ba11f6.png)

QGIS version | 3.8.1-Zanzibar | QGIS code revision | dcd95cc648
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.0 | Running against GEOS | 3.7.2-CAPI-1.11.0 b55d2125
PostgreSQL Client Version | 9.2.4 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Windows 10 (10.0) |   |

**Comment by nyalldawson** [comment]
Please upgrade to 3.8.1 - 3.8.0 doesn't include the fix.
