### ISSUE TITLE
Change date format aren't reflected in attribute table

### ISSUE THREAD

**Issue by FranklinJS** [qgis/QGIS#31097]
**Describe the bug**
After changing the date format in the Attribute Forms panel, the new format has no effect on the target field.

**How to Reproduce**

1. Go to layer properties
2. Click on Attributes Forms
3. Select a date or datetime field
4. Change date format from 'yyyy-MM-dd' to 'dd-MM-yyyy'
5. Change not reflected in attribute table

**QGIS and OS versions**

Versão do QGIS
3.4.8-Madeira
Código da versão do QGIS
04ee8e0761
Compilado sobre Qt
5.11.2
Rodando sobre Qt
5.11.2
Compilado sobre GDAL/OGR
2.4.1
Rodando sobre GDAL/OGR
2.4.1
Compilado sobre GEOS
3.7.2-CAPI-1.11.0
Rodando sobre GEOS
3.7.2-CAPI-1.11.0 b55d2125
Versão do cliente PostgreSQL
9.2.4
Versão SpatiaLite
4.3.0
Versão do QWT
6.1.3
Versão QScintilla2
2.10.8
Compiled against PROJ
520
Running against PROJ
5.2.0

**Additional context**

qgis global date format setting should be assumed by the local system

**Comment by gioman** [comment]
@FranklinJS a lot of necessary details are missing:

what type is the datasource?
have you checked if you have write permissions in the folder where the data source is?
have yo checked if you have write permissions in the table/layer case is in a DB (i.e. PostGIS)?
do you make use of any widget/custom form? if yes, have you tried if the same happen without them?

**Comment by FranklinJS** [comment]
Hi @gioman 

what type is the datasource? Shapefiles and Oracle BD
have you checked if you have write permissions in the folder where the data source is? Yes, I have.
have yo checked if you have write permissions in the table/layer case is in a DB (i.e. PostGIS)? Yes, I have.
do you make use of any widget/custom form? if yes, have you tried if the same happen without them? No, nothing custom or widget.

Note that nowhere in the software is the local date system format being assumed. Is this the correct behavior? Shouldn't QGIS use the host system format as its own?

**Comment by gioman** [comment]
>     5\. Change not reflected in attribute table

I don't think so, the change of date format in the widget applies only to new records, I guess.

**Comment by FranklinJS** [comment]
> > ```
> > 5\. Change not reflected in attribute table
> > ```
> 
> I don't think so, the change of date format in the widget applies only to new records, I guess.



In version 2.14 changing the format is reflected over the entire attribute table. However, I think you should think about the whole QGIS system for all new features created or loaded based on the host system configuration.

**Comment by DelazJ** [comment]
@FranklinJS Have you played with the option in Settings --> Options --> General --> Override system locale?

**Comment by FranklinJS** [comment]
> @FranklinJS Have you played with the option in Settings --> Options --> General --> Override system locale?

Yes, but no effect

**Comment by tudorbarascu** [comment]
I can easily replicate this with latest LTR and Master and just wanted to make a bug report when I saw this one. I'm trying to attach a test project but the page freezes so I'll attach later although it's super easy replicable.

- add a custom format for a date field e.g. ``dd-MM-yyyy``
- It never gets propagated to the attribute table (only to the form)
- all QGIS versions

It's an annoying bug as the other widgets do propagate the settings tot the attribute table.

**Comment by andrew-glos** [comment]
This is resolved in QGIS 3.16

**Comment by gioman** [comment]
> This is resolved in QGIS 3.16

@andrew-glos thanks for checking.
