### ISSUE TITLE
osgeo4w: on a clean install of qgis-dev (only ), QGIS does not start

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS#31090]
Having a Windows10 machine here, I tried to install ONLY qgis-dev via osgeo4w64, but could not start it due to:

![image](https://user-images.githubusercontent.com/731673/62450800-4f398a00-b76d-11e9-81ff-17ce756f8e12.png)

That msg tells you to check the qgis-dev-bin.env file, but that one is apparently not installed?

After that I installed qgis latest in the same osgeo4w64 dir, and that one indeed installed qgis-bin-g7.env  and qgis-bin.env in the bin dir.  I am able to start QGIS then by double clicking those exe files.
A second try to install only dev version in another dir had the same result.

As in this local setup there is no creation of Windows menu items, I cannot start qgis via the Start button, so either use the osgeo command window to start it: qgis-dev-bin, or I click the qgis-dev-bin.exe or bat file if available.

Anybody can confirm?

**Comment by jguelat** [comment]
I'm having the same problem on Windows 7.

**Comment by jef-n** [comment]
Not a qgis issue - still grass was added to the dependencies - reinstalling qgis-dev will bring it in.

**Comment by rduivenvoorde** [comment]
@jef-n Ah thanks!

So with 'not a qgis issue' you mean osgeo4w related issues should be reported here:
https://trac.osgeo.org/osgeo4w/report  (also for others) ?

Not clear to me what you mean with the grass comment above.

Just tried to do a clean install, is that too early?

If I *only* install 'qgis-dev'  then I end up with qgis-dev-bin.exe en *.vars NOT an *.env file. 
I do see a qgis-dev-bin-g7 versions though of all 3 files.
I will use that one (as it is working fine) in future.

**Comment by jef-n** [comment]
> So with 'not a qgis issue' you mean osgeo4w related issues should be reported here:
> https://trac.osgeo.org/osgeo4w/report (also for others) ?

Yes.  Not sure what you mean with "also for others".   Depends whether you report a problem about osgeo4w packages or QGIS itself.

> Not clear to me what you mean with the grass comment above.

The shortcut (and .env) creation is only done for the GRASS enabled version (see `etc/postinstall/qgis-dev.bat`) - and doesn't work without GRASS - but that wasn't a explicit dependency earlier.  So reinstalling `qgis-dev` should also fetch GRASS and create a working shortcut.
