### ISSUE TITLE
Ability to set "z" in "advanced digiticer" 

### ISSUE THREAD

**Issue by APOS80** [qgis/QGIS#31105]
**Feature description.**
I would like to be abel to set "z" value when using "advanced digiticer", it would way better than assigning "z" values afterwords.

**Additional context**
Name your price.

**Comment by m-kuhn** [comment]
Contact info@opengis.ch we've just estimated that for a part of a (not yet public) crowdfunding.

**Comment by DelazJ** [comment]
Duplicate of #29415

**Comment by alexbruy** [comment]
Duplicates #25865.
