### ISSUE TITLE
Processing select file button wrong text

### ISSUE THREAD

**Issue by arno974** [qgis/QGIS#31115]
In QGIS 3.8 (French language) on Windows when using geoprocessing tools from the vector/raster menu, the button to select a file appears with a weird text inside instead of the usual three dots '...' (see image below).

![Capture](https://user-images.githubusercontent.com/425243/62538837-d3bb0400-b864-11e9-837d-1f5a2e56bc75.PNG)

**Comment by Saijin-Naib** [comment]
![image](https://user-images.githubusercontent.com/19295950/62552933-714e0d80-b83c-11e9-8609-d9565149134c.png)
Can confirm the same behavior here in English, as well.


QGIS version | 3.8.1-Zanzibar | QGIS code revision | dcd95cc648
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.0 | Running against GEOS | 3.7.2-CAPI-1.11.0 b55d2125
PostgreSQL Client Version | 9.2.4 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Windows 10 (10.0) |   |
