### ISSUE TITLE
QGIS app does not show on top of other apps when is clicked

### ISSUE THREAD

**Issue by Charmatzis** [qgis/QGIS#31136]
QGIS app is not show on top of other apps when is clicked in the taskbar.

1. Start QGIS
2. Start another application (i.e. Chrome)
3. click on the QGIS application in the task bar.
4. QGIS does not show on top of the other app.

QGIS 3.8.1 Win 10 64-bit

**Comment by Pedro-Murteira** [comment]
@Charmatzis I can no longer reproduce this bug on QGIS 3.16.14 and 3.22.1.
