### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Peterh12** [qgis/QGIS#31165]
h2. User Feedback  QGIS first crashed when I was running the check geometries routine.  Then when I tried to re-open the project, it crashed each time.  h2.

Report Details  *Crash ID*: 4ed94ffc0125ffa462be11073b0178b031b3cd04   *Stack Trace* <pre> memcpy : VSICreateCachedFile : SASetupDefaultHooks : SHPReadObject : SHPPartTypeName : SHPPartTypeName : handlesDirectoryPath : QgsAbstractFeatureIterator::nextFeature : QgsVectorLayerFeatureIterator::fetchFeature : QgsAbstractFeatureIterator::nextFeature : QgsVectorLayerLabelProvider::registerFeature : QgsVectorLayerLabelProvider::registerFeature : QgsMapRendererParallelJob::renderLayerStatic : QgsArchive::zip : QgsImageOperation::overlayColor : QgsMapRendererParallelJob::cancelWithoutBlocking : QtConcurrent::ThreadEngineBase::run : QThreadPoolPrivate::reset : QThread::start : BaseThreadInitThunk : RtlUserThreadStart : </pre>   *QGIS Info* QGIS Version: 3.2.3-Bonn QGIS code revision: commit:9b176802e5 Compiled against Qt: 5.9.2 Running against Qt: 5.9.2 Compiled against GDAL: 2.2.4 Running against GDAL: 2.2.4    *System Info* CPU Type: x86_64 Kernel Type: winnt Kernel Version: 10.0.15063

**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by JMi31** [comment]
Same random crash issues with QGIS 3.8.0 occuring when selecting objects or clicking right on them.
Did not appear with my previous version 3.6.

Hope it helps to get more stable version !


Crash ID: f0d1e2bdf786f3eca76ac9b19f3b7172fa82c5fa

Stack Trace

QList::size :
QTableView::paintEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::drawWidget :
QApplication::windowIcon :
QWidget::event :
QgisApp::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::scrollRect :
QWidgetPrivate::invalidateBuffer_resizeHelper :
QWidget::repaint :
QWidget::repaint :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
TranslateMessageEx :
TranslateMessage :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.8.0-Zanzibar
QGIS code revision: 11aff65f10
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by gioman** [comment]
> Same random crash issues with QGIS 3.8.

try 3.8.1, try using a new/clean QGIS profile.

**Comment by roya0045** [comment]
@JMi31 A standalone request might be better if the crash is reproducible.
@Peterh12 Try the latest version

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
