### ISSUE TITLE
 PyQt5.QtCore module failed to register with the sip module

### ISSUE THREAD

**Issue by marcel-bariou** [qgis/QGIS#31166]
**QGIS and OS versions concerned with the trouble**
QGIS 3.8.1 from *.tar.gz
Qt version: 5.9.5
SIP version: 4.19.7
PyQt version: 5.10.1
QScintilla version: 2.10.2
On Ubuntu 18.04 LTS

**Describe the bug**

During QGIS 3.8.1 Compile I met the following error :[ 81%] Generating ui_console_compile_apis.py
Traceback (most recent call last):   File "../../../scripts/pyuic-wrapper.py", line 24, in <module>
    import qgis.PyQt.uic.pyuic
  File "/home/mbariou/WKSCOMPILE/QGIS/QGIS-final-3_8_1/build/output/python/qgis/__init__.py", line 78, in <module>
    import qgis.gui
  File "/home/mbariou/WKSCOMPILE/QGIS/QGIS-final-3_8_1/build/output/python/qgis/gui/__init__.py", line 25, in <module>
    from qgis._gui import *
**RuntimeError:** the PyQt5.QtCore module failed to register with the sip module
python/console/CMakeFiles/pyconsole.dir/build.make:62: recipe for target 'python/console/ui_console_compile_apis.py' failed
make[2]: *** [python/console/ui_console_compile_apis.py] Error 1
CMakeFiles/Makefile2:8450: recipe for target 'python/console/CMakeFiles/pyconsole.dir/all' failed
make[1]: *** [python/console/CMakeFiles/pyconsole.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

**How to Reproduce**
Complete compilation with respect to QGIS and OS version

**Additional context**
QGIS 3.6.1 is already installed ans it works correctly !
I met the problem with QGIS 3.6.1, i solved it [as follow](https://gis.stackexchange.com/questions/316263/qgis-compiling-3-6-0-troubleshooting-about-pyqt5-sip-qscintilla-on-ubuntu-18-0/316810#316810) . But it was not really  completed as indicated, some question was pending, I met them again in the same way with 3.8.1 release, but the remedy does not work today.

Today, Some hints or help will be welcome

thanks 
Marcel Bariou

**Comment by gioman** [comment]
is this a question or a bug report? if is a question please ask it on the developers mailing list, thanks.

**Comment by marcel-bariou** [comment]
Thanks, it is a question! I will take an other way,Sorry.

**Comment by Yunting-Zhao** [comment]
> Thanks, it is a question! I will take an other way,Sorry.
Have you solved this problem now? I had the same problem today and it was bugging me.
