### ISSUE TITLE
QGIS 3.4.6 startup crash on Ubuntu  19.04

### ISSUE THREAD

**Issue by maellevd** [qgis/QGIS#31179]
Hello,
We recently have crash problem with 3.4.6-Madeira on Ubuntu 19.04. Every time QGIS fails to open.
When we try to start it from the Menu, it doesn’t open.
When we try to open it from the terminal it dosen’t open and we get the following error message:
« QGIS died on signal 11Could not attach to process.  If your uid matches the uid of the target process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try again as the root user.  
For more details, see /etc/sysctl.d/10-ptrace.conf ptrace: Opération non permise. No thread selected No stack. gdb returned 256 Abandon (core dumped) »

But when we tried starting qgis as root in the terminal,  it works (and in the treminal we just have a warning message:
'Warning: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root').

We already tried to remove the configurations/profiles (/home/yourusername/.local/share/QGIS/QGIS3)  as I found it in some other thread and reinstall, but it did not make any difference (sometimes we had one first success but after the crash reappears).

**Comment by roya0045** [comment]
The first I would suggest is to update to 3.4.10 to validate if the same issue is still present in the current LTR.

Otherwise did the previous versions work properly on that machine?

**Comment by maellevd** [comment]
Thank you for answering !
      I updated to 3.4.10 with the release LT for Ubuntu. (FYI using synaptic GUI and add :
      deb https://qgis.org/ubuntu-ltr disco main
deb-src https://qgis.org/ubuntu-ltr disco main)
      But same issues ! 
These crashes appeared this Wednesday, July 17th. There has been no crashe since July 17th.

**Comment by maellevd** [comment]
Thank you for answering !
      I updated to 3.4.10 with the release LT for Ubuntu. 
(FYI using synaptic GUI and add :
      deb https://qgis.org/ubuntu-ltr disco main
deb-src https://qgis.org/ubuntu-ltr disco main)
      But same issues ! This is what I'm getting at startup. The splash screen loads, then the whole program quits.
These crashes appeared this Wednesday, August 7th. There has been no crashe since July 17th.

**Comment by roya0045** [comment]
Could this simply by an authorization issue (since you mentionned that running in admin mode was ok)?

It is possible that something on your end is blocking a step during the startup.

Otherwise without any log or trace its hard to say.

**Comment by maellevd** [comment]
Hello,
FYI, we found  the origin of the problem.
It came  from an incompatibility of coexistence between QuickOSM (https://plugins.qgis.org/plugins/QuickOSM/) and Qdraw (https://plugins.qgis.org/plugins/qdraw/) extensions. Indeed, QGIS opens correctly if one of them is installed but not both.
