### ISSUE TITLE
Project>Export/Import>Export Map To Image

### ISSUE THREAD

**Issue by MoabGeoff** [qgis/QGIS#31187]
Export Map to Image

This feature would be so much more useful if it would actually export a .geotiff file that has the spatial information embedded instead of exporting just a tiff file and a world file. The Avenza map app prefers that mappers download .geotiff files because they are already rasterized and do not need more processing before being posted to the app store. Avenza app developers say that if we who create the maps could include a .prj file and/or a .wkt file along with the .tiff and .tfw files, they might work with Avenza app; but I have not discovered how to create these addition files for a entire map canvas.

Would it be possible for QGIS developers to change this export feature to simply create a .geotiff file?

**Comment by nirvn** [comment]
I'll look into this, overlapping a current focus of mine.

**Comment by nirvn** [comment]
@MoabGeoff , this is being implemented in PR #31188 , will be available in QGIS 3.10.

**Comment by nirvn** [comment]
Implemented, closing.

**Comment by marjemetsast** [comment]
I'm disappointed. The tif/tfw file was essential for my work and now its gone from Project Import/Export Export Map to Image. How can I choose program to make tfw file with tif?
