### ISSUE TITLE
 Error saving layer after editing

### ISSUE THREAD

**Issue by woolyx** [qgis/QGIS#31180]
*Crash ID*: 346977bcd8b4ab804213e98e8e26b9cca23dba1d

*Stack Trace*
<pre>
RtlFreeHeap :
HeapFree :
free :
DllUnregisterServer :
DllUnregisterServer :
CLSIDFromString :
CLSIDFromString :
CLSIDFromString :
CLSIDFromString :
DllGetClassObjectWOW :
DllGetClassObjectWOW :
CLSIDFromString :
CLSIDFromString :
CLSIDFromString :
CLSIDFromString :
CLSIDFromString :
ObjectStublessClient6 :
CoCreateInstanceEx :
ObjectStublessClient32 :
SHParseDisplayName :
Ordinal866 :
ILSaveToStream :
ShellExecuteExW :
ShellExecuteExW :
ShellExecuteExW :
Ordinal860 :
ShellExecuteExW :
ExtractIconExW :
DllCanUnloadNow :
DllCanUnloadNow :
DllCanUnloadNow :
DllCanUnloadNow :
IUnknown_SetSite :
DllGetClassObject :
DllGetClassObject :
DllCanUnloadNow :
DllCanUnloadNow :
DllCanUnloadNow :
DllCanUnloadNow :
DllCanUnloadNow :
DllCanUnloadNow :
GetMenuStringW :
CreateDialogParamW :
CreateDialogParamW :
TranslateMessageEx :
GetMenuStringW :
GetComboBoxInfo :
DialogBoxIndirectParamAorW :
DialogBoxIndirectParamW :
DllCanUnloadNow :
QDialog::exec :
QFileDialog::getSaveFileUrl :
QFileDialog::getSaveFileName :
QgsFileWidget::openFileDialog :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
TranslateMessageEx :
TranslateMessage :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
QgisApp::saveAsVectorFileGeneral :
QgisApp::saveAsVectorFileGeneral :
QgisApp::saveAsFile :
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
TranslateMessageEx :
TranslateMessage :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QMenu::exec :
QgsLayerTreeView::contextMenuEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
TranslateMessageEx :
TranslateMessage :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.4.10-Madeira
QGIS code revision: 3d97aaae88
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by roya0045** [comment]
Could you provide more information on the layer that was edited and if there were concurrent edits or read/write being done?

**Comment by woolyx** [comment]
Good Morning,
This error has been constantly occurring after installation on this machine, and at the time of the error, there are no concurrent processes from other systems or other layers being edited as it still occurs in the "validation" version 3.4.10 installation.
In version 2.18.28, the same project works without any kind of error. In the same environment there is another machine that works perfectly .... the only difference is owning like S.O Win 10.

**Comment by gioman** [comment]
> Good Morning,
> This error has been constantly occurring after installation on this machine, and at the time of the error, there are no concurrent processes from other systems or other layers being edited as it still occurs in the "validation" version 3.4.10 installation.
> In version 2.18.28, the same project works without any kind of error. In the same environment there is another machine that works perfectly .... the only difference is owning like S.O Win 10.

please attach a screencast showing your problem, also first try on a new/clean QGIS profile.

**Comment by woolyx** [comment]
The layer in question is a line, which is on a server with Postgres 9.6 and Postgis 2.2.3, in the network we can access the project and make all access but this local station has this problem, in another allows functionality without the error but does not enable layer saving after editing.
We are doing local evaluations but still unsuccessful.

![image](https://user-images.githubusercontent.com/18752261/63022020-4edd7500-be78-11e9-847f-9cf4cd5f7906.png)

**Comment by roya0045** [comment]
And these issues are only occuring with a single PostGis layer or with all the layers of this database?

**Comment by gioman** [comment]
also have you tried on a new/clean QGIS profile (no 3rd party plugins installed)?

**Comment by gioman** [comment]
Closing for the lack of feedback.
