### ISSUE TITLE
Dragging layers sometimes disappear on drop

### ISSUE THREAD

**Issue by lbell** [qgis/QGIS#31182]
**Describe the bug**
Often when dragging a layer (to re-order or add to a new group) the layer simply disappears on drop.

**How to Reproduce**

- Drag and drop a layer. 
- Seems (possibly) to happen most when the layer is trying to be inserted between layers (rather than dropped into a group).

**QGIS and OS versions**

QGIS version | 3.8.1-Zanzibar | QGIS code revision | dcd95cc648
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.4.2 | Running against GDAL/OGR | 2.4.2
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
PostgreSQL Client Version | 10.9 (Ubuntu 10.9-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Ubuntu 18.04.3 LTS |   |  

**Additional context**
Possibly related to: https://github.com/qgis/QGIS/issues/29694 but my layers are actually disappearing.

**Comment by Pedro-Murteira** [comment]
@lbell I can't replicate on QGIS versions 3.16.14 and 3.22.1. (Tested on both Linux UBUNTU 20.04 and windows 10).

**Comment by lbell** [comment]
@Pedro-Murteira Howdy! To be fair, haven't noticed the behavior in recent usage, and couldn't replicate on the current version (3.22.1) so looks like an updated must have fixed this.

Thanks!
