### ISSUE TITLE
Raster - Miscellaneous - Merge : /usr/bin/env: ‘python’: No such file or directory

### ISSUE THREAD

**Issue by AndrewAkinson** [qgis/QGIS#31194]
Using the current version in flatpak on Debian

QGIS version | 3.6.2-Noosa | QGIS code revision | 656500e0
-- | -- | -- | --
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.4
Compiled against GDAL/OGR | 2.3.1 | Running against GDAL/OGR | 2.3.1
Compiled against GEOS | 3.6.0-CAPI-1.10.0 | Running against GEOS | 3.6.0-CAPI-1.10.0 r0
PostgreSQL Client Version | 10.5 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.4
Compiled against PROJ | 5.1.0 | Running against PROJ | Rel. 5.1.0, June 1st, 2018

Following the tutoral and data set from

https://www.qgistutorials.com/en/docs/3/raster_mosaicing_and_clipping.html

On step 5 hitting Run does not produce the new layer and the possessing log message is

2019-08-11T20:01:48     INFO    gdal_merge.py -ot Int16 -of GTiff -o /tmp/processing_57f244aa6d724438857db637dc11ad63/e020a0f71aae4ee3a64e7f54e6195f34/OUTPUT.tif --optfile /tmp/processing_57f244aa6d724438857db637dc11ad63/520735abb91b48669463e810fb020d46/mergeInputFiles.txt
2019-08-11T20:01:48     INFO    GDAL execution console output
             /usr/bin/env: ‘python’: No such file or directory

Running /usr/bin/env 'python' from the terminal works (although it runs python 2 not python 3)

Andrew

**Comment by nyalldawson** [comment]
Not a qgis issue - please file with the Flatpak package maintainers.
