### ISSUE TITLE
apparent regression in raster calculator multiplying conditionals

### ISSUE THREAD

**Issue by AlisterH** [qgis/QGIS#31193]
Load the attached layer and calculate this expression:
` ( "demo@1" > 0 )  * "demo@1" `
In QGIS 3.4 the result is a raster with values 3 and nodata.  The 3 is correct; I'm not certain whether the nodata is correct or it should be 0.
In QGIS 3.8.1 the result is a raster with values 1 and 0.  The 1 is incorrect; not sure about the 0.

[Desktop.zip](https://github.com/qgis/QGIS/files/3490336/Desktop.zip)

**Comment by AlisterH** [comment]
It doesn't look like it is a simple issue with order of operations.  This gives the same result:
`( 5 *  "demo@1") > 0  ` 

> The 3 is correct; I'm not certain whether the nodata is correct or it should be 0.

I note that the saga raster calculator has a "use nodata" option which allows either behaviour i.e. 0 or nodata, which might be a good idea.

**Comment by BC-Consulting** [comment]
Confirmed as regression.
Similar to above but Raster Calculator throwing "clBuildProgram" Exception when trying "ch_B02@1" < -3.0, on a one-band raster in QGIS 3.8.x (x=1 or 2). This works fine in QGIS 3.4.x.
OS is win10.

**Comment by AlisterH** [comment]
In case it helps anyone reading this - it looks like the problem was only triggered by enabling the "experimental" OpenCL acceleration, so until you have a fixed version, just disable it to workaround.
