### ISSUE TITLE
crash in discover relations for postgresql layers

### ISSUE THREAD

**Issue by beerockxs** [qgis/QGIS#31213]
## User Feedback

clicked "discover relations" in relations tab of project properties

## Report Details

*Crash ID*: 73667ad2d480d253f0d002f41b7ef114a92d7222

*Stack Trace*
<pre>
QMutex::lock :
sourceSelectProviders :
QgsRelationManager::discoverRelations :
QgsDiscoverRelationsDlg::QgsDiscoverRelationsDlg :
QgsRelationManagerDialog::mBtnDiscoverRelations_clicked :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
TranslateMessageEx :
TranslateMessage :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
QgisApp::projectProperties :
QgisApp::identifyMapTool :
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
TranslateMessageEx :
TranslateMessage :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.8.1-Zanzibar
QGIS code revision: dcd95cc648
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by beerockxs** [comment]
This happened because I had a layer based on an a stored function on the server, and the function had an error. Once I fixed the function, it worked again.

**Comment by roya0045** [comment]
@beerockxs does this mean that the crash was your fault or is it QGIS that is at fault for the crash?

**Comment by beerockxs** [comment]
Well, should QGIS crash when there's an SQL layer that does not work? I think it shouldn't, in other places, an error message pops up.
