### ISSUE TITLE
HeatMap (kernel density estimation) not working with point data having 8 million records.

### ISSUE THREAD

**Issue by GISConsortium** [qgis/QGIS#31229]
I am working on QGIS (3.8.0-Zanzibar) to generate a heat map with point data having 8  million records, but the process keeps on going for many days. I am processing it on 64-bit system with 32 GB RAM and 1TB hard drive. It works on small data but fails on a large dataset.

**Comment by Pedro-Murteira** [comment]
@GISConsortium Hello, I've tried to reproduce this issue but I'm not being able to. The datasets I used where not that large, but I didn't notice any unusual loading times. Did this happen to you more recently? And if it did, could you share the problematic dataset?
