### ISSUE TITLE
QGIS 3.6 Crashes upon file hyperlink within attribute table

### ISSUE THREAD

**Issue by karavindan2020** [qgis/QGIS#31233]
**Describe the bug**
<QGIS version 3.6 crashes upon selecting a hyperlink location from the attribute table. Attached error snapshot>
![QGIS 3 6 Hyperlink Crash](https://user-images.githubusercontent.com/54068457/62944203-15532e00-bdd4-11e9-951b-32176ff2c3f5.PNG)

**Comment by gioman** [comment]
Duplicate and long standing 3.* issue that has not solutions in QGIS, it must be fixed upstream in QT.
