### ISSUE TITLE
WFS freezes QGIS, while working in QGIS 2.18

### ISSUE THREAD

**Issue by beerockxs** [qgis/QGIS#31230]
When I add a layer from this public WFS http://inspire.brandenburg.de/services/strassennetz_wfs, QGIS 3.8.1 freezes, while it works just fine in QGIS 2.18

**Comment by nirvn** [comment]
@beerockxs , works fine here:
![Screenshot from 2019-08-13 16-36-40](https://user-images.githubusercontent.com/1728657/62931437-94526180-bde8-11e9-9dec-4d9d32a3ac28.png)

**Comment by beerockxs** [comment]
Possibly a problem only on Windows?

**Comment by beerockxs** [comment]
Hmm. In an empty project, it works, albeit very slowly. 2.18 is a lot faster. In a project with a lot of other layers, it freezes QGIS.

**Comment by nirvn** [comment]
@beerockxs , if you want to increase the chances of having this issue looked at, try to attach a test project which shows the symptoms you are suffering from.

Also, attaching GIFs could help (for e.g. demonstrating speed issue).

**Comment by beerockxs** [comment]
Here's a gif of the slowness in an empty project, it's practically unusable.
![slow_wfs](https://user-images.githubusercontent.com/16764567/62932696-f0a18b00-bdc0-11e9-9cc2-8d299a970294.gif)

**Comment by gioman** [comment]
> Here's a gif of the slowness in an empty project, it's practically unusable.

I added this and many other layers from your WFS service, and is snappy here. QGIS 3.4 on Linux.

**Comment by beerockxs** [comment]
Initially, it works fine here, but after a bit of zooming and changing of the extent, QGIS slows down to a crawl and I have to force-close it. Is there any way I can get meaningful logfiles for this?

**Comment by gioman** [comment]
> Initially, it works fine here, but after a bit of zooming and changing of the extent, QGIS slows down to a crawl and I have to force-close it. Is there any way I can get meaningful logfiles for this?

have you tried if it makes any difference on a new/clean QGIS profile?

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
