### ISSUE TITLE
QGIS Crashes when deleting a map in a layout

### ISSUE THREAD

**Issue by maltaesousa** [qgis/QGIS#31232]
Steps to reproduce:

1. Download this [QGIS project](https://sitn.ne.ch/web/qgis/TestCrashLayout.qgz) and open it
2. Open "Atlas" Layout
3. Delete the Map 1 object
4. Save Layout > Crash

Bug occurs in 3.9, 3.8.1, 3.6

Map 1 object has uuid `b1501156-b5af-4aef-9a3b-e7096050e640`
Editing the qgs file and deleting all the `<LayoutMultiFrame>` tags that have `mapUuid="{b1501156-b5af-4aef-9a3b-e7096050e640}"` attribute solves the issue.

```
Crash ID: 729143510354b98179f61ccfc688c8156fd82ddc

Stack Trace

QgsImageLegendNode::exportSymbolToJson :
QgsImageLegendNode::exportSymbolToJson :
QgsImageLegendNode::exportSymbolToJson :
QgsImageLegendNode::exportSymbolToJson :
QgsImageLegendNode::exportSymbolToJson :
QgsImageLegendNode::exportSymbolToJson :
QgsImageLegendNode::exportSymbolToJson :
QgsImageLegendNode::exportSymbolToJson :
QgsVectorLayerProperties::onAuxiliaryLayerDeleteField :
QgsVectorLayerProperties::onAuxiliaryLayerDeleteField :
QgsVectorLayerProperties::onAuxiliaryLayerDeleteField :
QgsVectorLayerProperties::onAuxiliaryLayerDeleteField :
QMetaObject::activate :
QAction::activate :
QgsVectorLayerProperties::onAuxiliaryLayerDeleteField :
QgsVectorLayerProperties::onAuxiliaryLayerDeleteField :
QgsVectorLayerProperties::onAuxiliaryLayerDeleteField :
QgsVectorLayerProperties::onAuxiliaryLayerDeleteField :
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsImageLegendNode::exportSymbolToJson :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsImageLegendNode::exportSymbolToJson :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
QgsVectorLayerProperties::onAuxiliaryLayerDeleteField :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.9.0-Master
QGIS code revision: bf31ce1d8c
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.0dev
Running against GDAL: 3.1.0dev

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

```

**Comment by nirvn** [comment]
Confirmed. 

Steps to reproduce:
# Create a new project, add a new layout
# In the layout, add a map item, then a scalebar item, legend item, or basically any item that has a referenced map.
# Save the new project
# In the layout, remove the map item
# Save the project again
# *boom* QGIS dies

**Comment by nirvn** [comment]
This crash has been addressed; QGIS' next point releases (3.4.11 and 3.8.2 coming Aug. 16-17) will include the fix. Thanks for the reporting.

**Comment by maltaesousa** [comment]
Thanks a lot!

**Comment by PauloEduardoCardoso** [comment]
Crash when deleting elements from map Layout in QGIS 3.10.1

## Report Details

**Crash ID**: [da89b5c62a47b099b636daa0e1ed91ebcbe4364e]('https://github.com/qgis/QGIS/search?q=da89b5c62a47b099b636daa0e1ed91ebcbe4364e&type=Issues')


**Stack Trace**
<pre>
QgsLayoutItem::writeXml :
QgsLayoutItemUndoCommand::saveState :
QgsLayoutUndoStack::beginCommand :
QgsLayoutItem::beginCommand :
QgsMapThemes::menu :
QMetaObject::activate :
QgsLayoutItemComboBox::itemChanged :
QMetaObject::activate :
QWidgetLineControl::`default constructor closure' :
QWidgetLineControl::`default constructor closure' :
QMetaObject::activate :
QAbstractItemModel::endRemoveRows :
QSortFilterProxyModel::removeRows :
QSortFilterProxyModel::sortRole :
QSortFilterProxyModel::`default constructor closure' :
QMetaObject::activate :
QAbstractItemModel::beginRemoveRows :
QgsLayoutModel::setItemRemoved :
QgsLayout::removeLayoutItem :
QgsLayoutView::deleteItems :
QgsLayoutView::deleteSelectedItems :
QMetaObject::activate :
QAction::activate :
QAction::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QShortcutMap::dispatchEvent :
QShortcutMap::tryShortcut :
QWindowSystemInterface::handleShortcutEvent :
QGuiApplicationPrivate::processKeyEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>


**QGIS Info**
QGIS Version: 3.10.1-A Coruna
QGIS code revision: ef24c526da
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by gioman** [comment]
>  QGIS Version: 3.10.1-A Coruna

@maltaesousa please try again with 3.10.2, possibly also with a new QGIS profile (no 3rd party plugins installed).

**Comment by gioman** [comment]
> @maltaesousa please try again with 3.10.2, possibly also with a new QGIS profile (no 3rd party plugins installed).

sorry I meant @PauloEduardoCardoso
