### ISSUE TITLE
Project macros fail to start on macOS

### ISSUE THREAD

**Issue by timlinux** [qgis/QGIS#31235]
Using QGIS 3.8 I am trying to use python macros on project start up:

<img width="857" alt="image" src="https://user-images.githubusercontent.com/178003/62970520-98da4280-be07-11e9-8285-3c4f46929178.png">

Code:

```
def openProject():
    layers = QgsProject.instance().mapLayersByName('plant_activity')
    layer = layers[0]
    iface.showAttributeTable(layer)
    

def saveProject():
    pass

def closeProject():
    pass

```

After starting QGIS 3.8 on macOS and opening my project I get this message:

<img width="1321" alt="image" src="https://user-images.githubusercontent.com/178003/62970593-bf987900-be07-11e9-9b89-74ee3b5ae3a5.png">

Clicking on enable macros then raises this error:

<img width="899" alt="image" src="https://user-images.githubusercontent.com/178003/62970616-d0e18580-be07-11e9-9d49-a1109877ae89.png">

```python
An error occurred during execution of following code:
qgis.utils.reloadProjectMacros()


traceback.print_exception() failed

Python version:


QGIS version:
3.8.1-Zanzibar 'Zanzibar', dcd95cc648

Python path:

```

CC @PeterPetrik  - not sure if this is macOS specific?

**Comment by PeterPetrik** [comment]
it is not, can be replicated on (mario@opengis.ch replicated on Archlinux)

**Comment by bvthomsen** [comment]
On Windows 8.1 64 bit, QGIS 3.8.1 64 bit it works as expected (printing a traceback):

 
```
Der opstod en fejl ved udførelse af følgende kode:

qgis.utils.reloadProjectMacros()


Traceback (most recent call last):
  File "", line 1, in 
  File "C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python\qgis\utils.py", line 557, in reloadProjectMacros
    openProjectMacro()
  File "C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python\qgis\utils.py", line 574, in openProjectMacro
    mod.openProject()
  File "", line 3, in openProject
NameError: name 'QgsProject' is not defined


Python-version:
3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]

QGIS-version:
3.8.0-Zanzibar 'Zanzibar', 11aff65f10

Python-sti:
['C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python', 'C:/Users/Bo Victor/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python', 'C:/Users/Bo Victor/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python/plugins', 'C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python/plugins', 'C:\\Program Files\\QGIS 3.8\\bin\\python37.zip', 'C:\\PROGRA~1\\QGIS3~1.8\\apps\\Python37\\DLLs', 'C:\\PROGRA~1\\QGIS3~1.8\\apps\\Python37\\lib', 'C:\\Program Files\\QGIS 3.8\\bin', 'C:\\PROGRA~1\\QGIS3~1.8\\apps\\Python37', 'C:\\PROGRA~1\\QGIS3~1.8\\apps\\Python37\\lib\\site-packages', 'C:\\PROGRA~1\\QGIS3~1.8\\apps\\Python37\\lib\\site-packages\\win32', 'C:\\PROGRA~1\\QGIS3~1.8\\apps\\Python37\\lib\\site-packages\\win32\\lib', 'C:\\PROGRA~1\\QGIS3~1.8\\apps\\Python37\\lib\\site-packages\\Pythonwin', 'C:/Users/Bo Victor/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python', 'D:/Projekter/groenreg']
`````
And *if* you modify the python code to include relevant imports like this:

```
from qgis.core import QgsProject
from qgis.utils import iface

def openProject():
    layers = QgsProject.instance().mapLayersByName('kommune')
    layer = layers[0]
    iface.showAttributeTable(layer)
   

def saveProject():
    pass

def closeProject():
    pass
```
The "openProject " function works as expected without triggering an error (and show an attribute window after loading the layers)

**Comment by timlinux** [comment]
Ah thanks @bvthomsen - waiting for confirmation from Mario to see if he replicated the failing traceback or the issue with my broken code.

**Comment by timlinux** [comment]
I also confirm that the macros run properly with properly formulated code as @bvthomsen provided - without getting a proper traceback though it is hard for users to understand why their code is not working.

**Comment by marioba** [comment]
@bvthomsen's code works as expected. 
But if there is an error in the code, `print_exception()` fails as it happens to @timlinux.
![image](https://user-images.githubusercontent.com/24844357/63079085-c1fcef00-bf3d-11e9-997f-66faab0a4421.png)

**Comment by MrChebur** [comment]
The same error in 3.10.1 when macros fail:

```
An error occurred during execution of following code:
qgis.utils.reloadProjectMacros()


traceback.print_exception() failed

Python version:


QGIS version:
3.10.1-A Coruña 'A Coruña', ef24c526da

Python path:

```

**Comment by espinafre** [comment]
I also get this with current QGIS on Gentoo Linux. I'm trying to update some old custom actions over from QGIS 2/Python 2 to the latest versions, but this leaves me blind. It seems this bug existed since 2.x, and was only closed because of EOL of that version: https://issues.qgis.org/issues/16923

Maybe the failure to display the Python version/python path is related to this issue. My system, after our rather long, convoluted, hopelessly outdated python2 code, displays:

`traceback.print_exception() failed

Python version:


QGIS version:
3.11.0-Master 'Master', 51f4f032f6

Python path:
`
I'm running Python-3.8.1 BTW.
