### ISSUE TITLE
Displaying and editing negative integers using Range Widget when "Allow NULL" is selected

### ISSUE THREAD

**Issue by heidivanparys** [qgis/QGIS#31245]
**Describe the bug**
Negative integers are not displayed correctly in the Feature Form (at least for GML files).

**How to Reproduce**
1. Download [test.txt](https://github.com/qgis/QGIS/files/3500706/test.txt) and rename extension to .gml
2. Add Vector Layer, select test.gml
3. Identify feature
4. Right-click on the info of an identified feature, choose "View Feature Form"
5. The value of a negative integer is displayed as `<null>` instead of the actual value.

![image](https://user-images.githubusercontent.com/11427611/63010550-e053e380-be86-11e9-8cc9-9adf9c43a07e.png)

![image](https://user-images.githubusercontent.com/11427611/63010720-2dd05080-be87-11e9-91a4-d5063fbccff6.png)

**QGIS and OS versions**
QGIS version | 3.8.1-Zanzibar | QGIS code revision | dcd95cc648
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.0 | Running against GEOS | 3.7.2-CAPI-1.11.0 b55d2125
PostgreSQL Client Version | 9.2.4 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Windows 10 (10.0) |   |

**Comment by gioman** [comment]
@heidivanparys for some reason when I add you gml in a clean project that attribute is automatically given the "range" widget. With that widget there is the issue you report, but if you change it to "text edit" then it works as expected. it may not be a datasource problem at all, it can be a widget problem, to test someone should try with different datasources.

**Comment by gioman** [comment]
It does not seems to affect PostGIS, anyway I also noticed this: https://github.com/qgis/QGIS/issues/31247

**Comment by heidivanparys** [comment]
I tested with a scratch layer, where I added an integer field, and the same issue occurs.

Apart from the other workaround, described in #31247 (@gioman  thanks for testing!), I noticed that another workaround is to deselect the checkbox "Allow NULL" in the settings of the Range widget (for the record: right-click on layer -> Attributes Form -> click on the field).

![image](https://user-images.githubusercontent.com/11427611/63078493-f2438e00-bf3b-11e9-8e46-fd5b6132b60d.png)

So, another way to reproduce this issue:

1. Create a new temporary scratch layer
2. Add a feature
3. Add a field with type integer (Layer Properties -> Source Fields). 
![image](https://user-images.githubusercontent.com/11427611/63078848-1bb0e980-bf3d-11e9-82bf-a1f6c7ffa3b0.png)
4. Try to edit the field, which currently has no contents, by clicking on the "arrow down", this doesn't work, negative values cannot be set. The "arrow up" does work. 
![image](https://user-images.githubusercontent.com/11427611/63079028-9417aa80-bf3d-11e9-9a6d-acf660fb5395.png)

Again, after deselecting the checkbox "Allow NULL", negative values can be chosen using the "arrow down". When entering a value, and selecting "Allow NULL" again, negative values can be entered for those features where a value was present already in the field. For features that have no value, the same issue as described above occurs.

**Comment by gioman** [comment]
Related to https://github.com/qgis/QGIS/issues/31247 ?

**Comment by alexbruy** [comment]
Seems already fixed. Tested with attached GML and in master form shows correct field value.

**Comment by heidivanparys** [comment]
I just tested with 3.10.5-A Coruña and this indeed seems to be fixed now. Thanks for the feedback, @alexbruy .
