### ISSUE TITLE
Crash with 3.8.1 version when clicking on "select icon"

### ISSUE THREAD

**Issue by JMi31** [qgis/QGIS#31246]
Hi,

I experienced some random crashes with QGIS 3.8 version, when digitalizing networks.
It occured essentially when right-clicking on object or clicking on some buttons. 
In order to limit loss of data, I installed the "autosaver" extension, which slows down and disrupt a bit the digitalization, but does not crash.

Following Giovanni Manghi's advice, I upgraded to 3.8.1 version, with same extensions.
After some days, it seems that when crashes occurs, it is often linked with clicking on "Select Icone" (arrow on yellow square), but not systematically...

Hope it helps,

Jean-Michel

## User Feedback

Frequent crashes when clicking on "select icon"

## Report Details

*Crash ID*: f0d1e2bdf786f3eca76ac9b19f3b7172fa82c5fa

*Stack Trace*
<pre>
QList<QItemSelectionRange>::size :
QTableView::paintEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::drawWidget :
QApplication::windowIcon :
QWidget::event :
QgisApp::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::scrollRect :
QWidgetPrivate::invalidateBuffer_resizeHelper :
QWidget::repaint :
QWidget::repaint :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
TranslateMessageEx :
TranslateMessage :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.8.1-Zanzibar
QGIS code revision: dcd95cc648
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by gioman** [comment]
> with same extensions

have you tried with no 3rd party extensions? to do that create a new/clean QGIS profile, and don't install any.

**Comment by nyalldawson** [comment]
Closing due to lack of feedback
