### ISSUE TITLE
Attribute table is not respecting cell margins in layout

### ISSUE THREAD

**Issue by Isaacson33** [qgis/QGIS#31259]
Text in an attribute table added to a print layout does not seem to respect cell margin settings when alignment is set to any of the 'Top...' options in the 'Alignment' setting of the 'Attributes...' dialog.

No matter how large the margins are set, only left and right margins are increased. The top of the text remains resolutely attached to the top of the cell. If the cell margin is set to 5mm, I would expect top-aligned text to start 5mm from the top of the cell.

When alignment is set to 'Middle...', the cell margins are respected both top/bottom and left/right.

I'm hesitant to mark this as a regression because I don't have an old version of Qgis to test on, but I have been using it to make print layouts for several years and I don't think I've encountered this problem before.

**Comment by gioman** [comment]
> I'm hesitant to mark this as a regression because I don't have an old version of Qgis to test on, but I have been using it to make print layouts for several years and I don't think I've encountered this problem before.

I also think it was working as expected, but also not 100%. I will try to check on an older release asap.

**Comment by Isaacson33** [comment]
> I also think it was working as expected, but also not 100%. I will try to check on an older release asap.

Thanks. I'm having real trouble testing things at the moment as I've made a few adjustments to my proj files to workaround a previous problem. I'm on Linux and the upshot is I can't easily revert to previous versions, I'm pretty much stuck with whatever is in the Arch repository (currently 3.8.0). I can upgrade to master, but can't easily downgrade again afterwards, so am reluctant to do so. Another person testing would be really helpful.

**Comment by nyalldawson** [comment]
> I also think it was working as expected, but also not 100%. I will try to check on an older release asap.

I've tested on 2.18 -- it's not a regression, this never worked.
