### ISSUE TITLE
QGIS silently loads last-loaded project in the background at launch

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#31260]
**Describe the bug**
I notice QGIS load a project that was loaded on the previous instance of QGIS when I launch a fresh instance. This can slow down the launch a lot and will show the toast notification about it, but apart from that the user won't notice it.

**How to Reproduce**
Unfortunately I have not found a way to regularly reproduce it. I encourage you to keep an eye out for it.

I *think* it happens when I launch QGIS with a file or project as argument. I don't think I ever noticed it happening when launching a clean QGIS. I have not tried this on a clean QGIS profile (please tell me what to look for in my profile if you think this might be an issue).

Suggestions for what to try and recommendations what to log/monitor are welcome!

**QGIS and OS versions**

QGIS version | 3.8.0-Zanzibar | QGIS code branch | Release 3.8
-- | -- | -- | --
Compiled against Qt | 5.13.0 | Running against Qt | 5.13.0
Compiled against GDAL/OGR | 3.0.0 | Running against GDAL/OGR | 3.0.0
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
PostgreSQL Client Version | 11.4 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 6.1.0 | Running against PROJ | Rel. 6.1.0, May 15th, 2019
OS Version | Arch Linux |   |

**Comment by elpaso** [comment]
Settings -> Options -> General -> Project files -> Open project on launch -> ... ?

**Comment by kannes** [comment]
Nope, it does not actually visibly or usably *open* it, it just *load*s it hidden in the background.

**Comment by kannes** [comment]
Can't reproduce this anymore.
