### ISSUE TITLE
Add warnings for "stupid", non-spatial GEOS-based functions like length and area

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#31275]
**Feature description.**
Please add notes or warnings to the docs of all the not-spatially-aware GEOS-based functions used for calculating things like lengths and areas.

For example https://qgis.org/pyqgis/master/core/QgsGeometry.html#qgis.core.QgsGeometry.area and https://qgis.org/pyqgis/master/core/QgsGeometry.html#qgis.core.QgsGeometry.length will treat all coordinates as if they were on a flat cartesian plane. This is confusing to users who assume their GIS abstracts these issues for them.

This extends to expression functions like `area()` and `length()`, though these two already have appropriate warnings in their help texts:

> Calculations are always planimetric in the Spatial Reference System (SRS) of this geometry, and the units of the returned area will match the units for the SRS. This differs from the calculations performed by the $area function, which will perform ellipsoidal calculations based on the project's ellipsoid and area unit settings.

I don't know which functions and methods all might be affected.

**Additional context**
Motivated by https://gis.stackexchange.com/questions/332179/qgsgeometry-length-gives-wrong-result/332180 . It is a very common problem.

**Comment by nyalldawson** [comment]
Sounds like a great contribution you could make via a Pull Request?

**Comment by kannes** [comment]
I knew someone would say that ;) Unfortunately I am too unexperienced with the QGIS internals to identify those functions correctly.

**Comment by roya0045** [comment]
I would assume that [the only two elements using the](https://github.com/qgis/QGIS/blob/e7389db5c7cc81369a33c31e35c1cac42c90747b/src/core/expression/qgsexpression.h#L375) QgsDistanceArea class are the lenght and area functions as far as ExpressionFunctions go.

It might be possible to improve it.

Otherwise simply adding a warning in the json files for those two should be enough I assume.

**Comment by nyalldawson** [comment]
The changes would need to be made right here: https://github.com/qgis/QGIS/blob/master/src/core/geometry/qgsgeometry.h#L378

**Comment by kannes** [comment]
Thanks, I am on it right now :)

**Comment by kannes** [comment]
A first scan through https://qgis.org/pyqgis/master/core/QgsGeometry.html for "area", "length", "distance", "radius" gave me

# returns
- area
- length
- distance
- distanceToVertex
- closestVertex?
- closestVertexWithContext?
- hausdorffDistance?
- hausdorffDistanceDensify?
- lineLocatePoint
- sqrDistToVertexAt
- translate

# parameters
- buffer x2
- createWedgeBuffer
- densifyByDistance
- extendLine
- extrude? (needs parameter descriptions, might be coordinates not offsets)
- interpolate
- interpolateAngle
- offsetCurve
- removeInteriorRings
- singleSidedBuffer
- smooth
- snappedToGrid
- taperedBuffer
- ~variableWidthBufferByM

As usual, this is more complex than I expected...
I also need to look for "tolerance", "epsilon" and similar terms.

My idea would be to add a shortest possible "in layer units" where it *should* be obvious and the long "Calculations are always planimetric in the Spatial Reference System (SRS) of this geometry, and the units of the returned FUNCTION will match the units for the SRS." text from https://github.com/qgis/QGIS/commit/c23e3096fe1ebc048e00f940c02e6f22954f59fa for the main functions.

TBC!

**Comment by nyalldawson** [comment]
@kannes I've made a start in https://github.com/qgis/QGIS/pull/31330  - this should give a good model of what's required for further follow ups. It would be good to see your expanded explanations included here too regarding the CRS, etc.

**Comment by nyalldawson** [comment]
(and it's quite likely I missed a few too !)

**Comment by kannes** [comment]
Wow, thank you so much!
