### ISSUE TITLE
Problems with Warp (Reproject) and user-defined output extent

### ISSUE THREAD

**Issue by gkimbell** [qgis/QGIS#31276]
**Description**

A problem occurs when using Warp (Reproject) from the Processing Toolbox or  gdal:warpreproject in Python when the CRS of a user-defined output extent is implicit or is specified in a user-defined coordinate system. In the former case the GDAL/OGR console call contains the ‘-te_srs’ string but no CRS definition.  In the latter case the -te_srs parameter is specified as an authid rather than being translated into a Proj4 string and this presumably causes the GDAL routine to crash. The error message in both cases is 'Translating source or target SRS failed'. If the Source CRS and Target CRS are explicitly specified as user-defined, these are translated to Proj4 in the console call.

**How to reproduce (implicit projection)**

Run Warp (Reproject) from the Processing Toolbox on any suitable raster and a define a georeferenced extent for the output in Advanced Parameters (e.g. the canvas extent) while leaving the CRS of the target raster extent blank.

**How to reproduce (user-defined projection)**

1.  Load a raster with a user-defined CRS into QGIS (example provided).
2.  Run Warp (Reproject) and select the user-defined CRS in the Source, Target and Extent drop-down lists. Define an extent for the output.
3.  Note the difference in the way the GDAL/OGR console call defines the -s_srs, -t_srs and -te_srs parameters.
4.  The routine crashes if -te_srs is a USER: rather than EPSG: system. 
[test_uklidar.zip](https://github.com/qgis/QGIS/files/3509481/test_uklidar.zip)

**QGIS and OS versions**

QGIS version
3.8.1-Zanzibar
QGIS code revision
dcd95cc648
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
2.4.1
Running against GDAL/OGR
2.4.1
Compiled against GEOS
3.7.2-CAPI-1.11.0
Running against GEOS
3.7.2-CAPI-1.11.0 b55d2125
PostgreSQL Client Version
9.2.4
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
5.2.0
Running against PROJ
Rel. 5.2.0, September 15th, 2018
OS Version
Windows 10 (10.0)

**Additional context**

Problem also occurs with the 'processing.run('gdal:warpreproject', parameters)' Python command  (TARGET_EXTENT_CRS parameter)

**Comment by gioman** [comment]
There is a problem with GDAL Warp:

https://github.com/qgis/QGIS/issues/31301

the log/run always ends with an error even when the output is correctly created.

> Run Warp (Reproject) from the Processing Toolbox on any suitable raster and a define a georeferenced extent for the output in Advanced Parameters (e.g. the canvas extent) while leaving the CRS of the target raster extent blank.

you can't leave the "CRS of the target raster extent" blank, despite the filed says it is "optional". If you leave that blank you'll get the 'Translating source or target SRS failed' error from GDAL and eventually the annoying https://github.com/qgis/QGIS/issues/31301





> **How to reproduce (user-defined projection)**

this is the real issue, the  "CRS of the target raster extent"  do not translate to a proj4 string as it happens for the s_srs and t_srs parameters. 

The title and description of this ticket should be changed accordingly if you agree.

**Comment by gkimbell** [comment]
Hi Giovanni,

Thanks for the feedback. I think the problem with leaving the CRS of the target extent blank is slightly different to #31301 in that it causes a crash rather than just a spurious error message. If lines 217-220 of QGIS/python/plugins/processing/algs/gdal/warp.py are changed as follows I think that both the problems I identify are fixed, but #31301 still occurs.

            extentCrs = self.parameterAsCrs(parameters, self.TARGET_EXTENT_CRS, context)
            #if extentCrs:
            if extentCrs.isValid():
                arguments.append('-te_srs')
                #arguments.append(extentCrs.authid())
                arguments.append(GdalUtils.gdal_crs_string(extentCrs))

Cheers,

Geoff Kimbell

**Comment by gioman** [comment]
> leaving the CRS of the target extent blank is slightly different to #31301

it is indeed, I didn't meant to say it was the same.




>  If lines 217-220 of QGIS/python/plugins/processing/algs/gdal/warp.py are changed as follows I think that both the problems I identify are fixed

can you make it a Pull Request? thanks!
