### ISSUE TITLE
QGIS weekly windows build seems to be corrupted

### ISSUE THREAD

**Issue by FelisPimeja** [qgis/QGIS#31274]
QGIS-OSGeo4W-3.9.0-32-Setup-x86_64.exe from https://qgis.org/downloads/weekly/QGIS-OSGeo4W-3.9.0-32-Setup-x86_64.exe  does not run after install. Running Qgis shortcut gives this error message:

```
---------------------------
Error loading QGIS
---------------------------
Oops, looks like an error loading QGIS 

 Details: 

Could not load qgis_app.dll 
 Windows Error: The specified module could not be found.


 Help: 

 Check C:\Program Files\QGIS 3.9\bin\qgis-dev-bin.env for correct environment paths
---------------------------
OK   
---------------------------

```
As I can see there's no qgis-dev-bin-g7.exe in \QGIS 3.9\bin either

**Comment by ponceta** [comment]
Same here :
![image](https://user-images.githubusercontent.com/8614223/63243636-71e29d00-c25b-11e9-8bbc-03862c2eee3b.png)

**Comment by roya0045** [comment]
Is this still a thing?

**Comment by gioman** [comment]
> Is this still a thing?

yes it is. Even on clean Windows machines (no DLL hell) both qgis-dev installed with OSGeo4W and the standalone master weeklies do not start with the error reported above. Both "qgis" and "qgis-ltr" work as expected on the same OSGeo4W installation.

**Comment by jef-n** [comment]
There haven't been no new weeklies for x86_64 for a while - as they currently exceed NSIS's 2GB limit (GRASS on python3 will probably cure that)..

This has nothing to do with the problem in OSGeo4W - this has been broken for two or three days when proj master switched from 6.2 to 7.0 in short succession - should be fixed with the latest build.

**Comment by gioman** [comment]
> There haven't been any new weeklies for x86_64 for a while - as they currently exceed NSIS's 2GB limit (GRASS on python3 will probably cure that)..

ok

> This has nothing to do with the problem in OSGeo4W - this has been broken for two or three days when proj master switched from 6.2 to 7.0 in short succession - should be fixed with the latest build.

nice to know, but actually i have not been able to start qgis-dev from osgeo4w for much longer than 2/3 days (weeks, maybe months), before the issue was different?

cheers

**Comment by jef-n** [comment]
Um, news to me.  This ticket is about the weekly standalone.

**Comment by gioman** [comment]
> This ticket is about the weekly standalone.

yes I know, I just hijacked a little bit this ticket to let know about the qgis-dev issue in osgeo4w (which I personally haven't reported... yet).

**Comment by jef-n** [comment]
> yes I know, I just hijacked a little bit this ticket to let know about the qgis-dev issue in osgeo4w (which I personally haven't reported... yet).

Please try again

**Comment by gioman** [comment]
> Please try again

yeah I know...again... but as the error message is exactly the same you must admit that commenting here about osgeo4w was pretty natural :)

**Comment by roya0045** [comment]
> > Please try again
> 
> yeah I know...again... but as the error message is exactly the same you must admit that commenting here about osgeo4w was pretty natural :)

I think he meant that you should try the qgis-dev to validate and not about creating a new ticket.

**Comment by gioman** [comment]
> I think he meant that you should try the qgis-dev to validate and not about creating a new ticket.

apparently I don't need to to do, I tried again on a fresh Windows VM and now it works. Compared to my last tries I see that now in the bin folder there is the qgis-dev.bat file (when it didn't worked I noticed that this file wasn't there). Not sure it was a local issue or some recent fix, but it doesn't matter anymore. Thanks Jurgen.

**Comment by jef-n** [comment]
> Not sure it was a local issue or some recent fix, but it doesn't matter anymore. Thanks Jurgen.

3354a8cceee002fc3335da242d506c4070ea2770 was the fix - and the grass variant should have worked all along

**Comment by denevers** [comment]
Same problem with 3.14 (and I had the same issue with 3.13, which i fixed by using OSGeo4W, but this time, it does not work)

**Comment by narrowtux** [comment]
I have a similar issue with 3.14.16-2 as well. On the 5th try, I was able to install. 

Check if there is really enough space on your disk, I suspect that this was the problem for me, the installer just gives you a weird error message because it doesn't check for disk space errors when writing the file, but it will try to read the files later. (my assumption).
