### ISSUE TITLE
Memory leak and qgis crash

### ISSUE THREAD

**Issue by Adviser-ua** [qgis/QGIS#31278]
**Describe the bug**

Increasing using RAM when add raster in particular way.

In case add raster layer via panel "browser" or just drag and drop the bug is not reproduced

**How to Reproduce**

1) add raster layer:
 open menu Layer -> Add Layer -> Add Raster Layer -> Choose file *.tiff  about 30MB

2) change extent multiple times

3) In Task manager I can view increase memory using by QGIS

4) QGIS Crashed aproximetly on 1300MB RAM

**QGIS and OS versions**

QGIS Info
QGIS Version: 3.4.2-Madeira
QGIS code branch: Release 3.4
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.3.2
Running against GDAL: 2.3.2

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

Windows 7 Ultimate
Windows 10 also bug reproduced

**Additional context**
Stack Trace

QgsMultiBandColorRenderer::block :
QgsBrightnessContrastFilter::block :
QgsHueSaturationFilter::block :
QgsRasterResampleFilter::block :
QgsRasterProjector::block :
free :
QgsRasterIterator::readNextRasterPart :
QgsRasterIterator::readNextRasterPart :
QgsRasterDrawer::draw :
QgsRasterLayerRenderer::render :
QgsMapRendererParallelJob::renderLayerStatic :
QgsMapRendererParallelJob::renderingFinished :
QgsCredentialsNone::request :
QgsMapRendererParallelJob::cancelWithoutBlocking :

**Comment by nyalldawson** [comment]
Can you attach/link to your raster and a qml of the style used?

**Comment by nyalldawson** [comment]
Also please test with 3.4.11

**Comment by gioman** [comment]
Closing for the lack of feedback.
