### ISSUE TITLE
rasters in gpkg are not saved as relative path in project file (.qgs)

### ISSUE THREAD

**Issue by meyerlor** [qgis/QGIS#31296]
**Description**
when raster files saved in a gpkg are added to a QGIS project, the paths saved in the .qgs file to the rasters are not relative, but absolute. This breaks the ability to transfer projects

**How to Reproduce**
Drag & Drop gpkg containing rasters as well as adding a new datasource from inside QGIS results in the same behavior

QGIS 3.8.2

**Comment by elpaso** [comment]
I cannot reproduce this issue on master.
If you refer to the source attribute in `<layer-tree-layer source="GPKG:/absolute_path" />` that is irrelevant, the real datasource is in `<datasource>GPKG:../relative_path:250010</datasource>`.

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
