### ISSUE TITLE
CRS details are not readable in the CRS selector dialog

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#31297]
The details of the selected CRS in a "CRS selector dialog" is barely readable (the following screenshot actually displays it better than what I get in QGIS). Might have to do with font and font size (too small?).
![image](https://user-images.githubusercontent.com/7983394/63270299-374b2580-c298-11e9-8a60-8b0fff421d8b.png)

QGIS version | 3.9.0-Master | QGIS code revision | 19220b9e06
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.0dev | Running against GDAL/OGR | 3.1.0dev
Compiled against GEOS | 3.7.2-CAPI-1.11.0 | Running against GEOS | 3.7.2-CAPI-1.11.0 b55d2125
PostgreSQL Client Version | 10.8 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.1.0 | Running against PROJ | Rel. 6.1.0, May 15th, 2019
This copy of QGIS writes debugging output.
OS Version | Windows 10 (10.0) |   |  

PS: it was already the case in recent nightlies with proj<6.1 and gdal<3

**Comment by roya0045** [comment]
If you want to change it, it should be straighfoward enough, QT seems to use font 8 when the font is not specified, see https://github.com/qgis/QGIS/blob/037bdef53e917ef4e0652d45aa5deca5ddcce0f3/src/ui/qgsprojectionselectorbase.ui#L232 for the section where to add the font size.

**Comment by alexbruy** [comment]
Not sure if this is a bug, from the commits history it looks like intentional thing.

**Comment by DelazJ** [comment]
Need to check the dialog when i'm on Windows but as shown above it's pretty unreadable, so something is buggy imho. Here, the same dialog with ubuntu
![image](https://user-images.githubusercontent.com/7983394/65287874-05520b00-db45-11e9-90cc-04e16a7fe356.png)
