### ISSUE TITLE
how to create a shape file

### ISSUE THREAD

**Issue by Jesummg** [qgis/QGIS#31294]
**problems by creating a new layer**
<when I try to create a new layer (shape) it produces next error message: "2019-08-19T13:15:10     WARNING    Falló la creación de la fuente de datos OGR sala1.shp: Failed to create file sala1.shp: Permission denied" Which could be the problem?>

**Comment by roya0045** [comment]
If you do not specify a folder the shapefile will be created in something like system32, and you probably don't have write access to that folder, simply specify the full  path and not the name only.

**Comment by Gustry** [comment]
Use the 3 dots to specify your path.

**Comment by Jesummg** [comment]
> If you do not specify a folder the shapefile will be created in something like system32, and you probably don't have write access to that folder, simply specify the full  path and not the name only.

Many thanks, I did not remember that and got failed!

**Comment by Jesummg** [comment]
> Use the 3 dots to specify your path.

OK! thanks
