### ISSUE TITLE
QGIS disabled plugins error

### ISSUE THREAD

**Issue by Scunnymatt** [qgis/QGIS#31307]
Describe the bug
On opening QGIS the following error message appears:
Plugin processing: The plugin will be disabled because it crashed QGIS during last startup. Please report an issue and re-enable the plugin when the problem has been solved.

Could someone please send steps as to how to fix the issue? We have tried reinstalling.

QGIS and OS versions 
Windows 8 64 bits
QGIS 3.6 Noosa

**Comment by roya0045** [comment]
Simply deactivate and reactivate the plugin, it happens from time to time on my end too.

**Comment by Scunnymatt** [comment]
Thank you, all sorted
