### ISSUE TITLE
crash when creating a new page after deleting section/field group

### ISSUE THREAD

**Issue by imaginaryearthnotes** [qgis/QGIS#31302]
## User Feedback

crashed when trying to create a new page in a new report. There was no page before trying to insert one. Also in the background of this crash screen there is no page, so it crashed before inserting one I guess. Hope this helps.

## Report Details

*Crash ID*: 524be25758eaaee4c1bb67eb68e90bc0dcb49bfb

*Stack Trace*
<pre>
QgsRasterCalcDialog::numberOfColumns :
QgsVertexEntry::point :
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
DispatchMessageW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.4.10-Madeira
QGIS code revision: 3d97aaae88
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by nyalldawson** [comment]
Can you please post more steps on how to reproduce? How did you get a report with no pages in the first place?

**Comment by imaginaryearthnotes** [comment]
thanks, simplest reproducible example (3.4.10, win64):
- new project
- new report
- add field group (note "new page" ist greyed out)
- delete field group
- add page (now "new page" is not greyed out)
- crash

**Comment by gioman** [comment]
> add page (now "new page" is not greyed out)

if you mean "add page" then I can't confirm it becomes active, at least on 3.8.1 on Linux.

**Comment by imaginaryearthnotes** [comment]
yes, I mean "add page" and consistently reproducible on 3.4.10 LTR on Win10(x86_64). It just does not goes inactive **after deleting a field group or static section**.

**Comment by gioman** [comment]
> yes, I mean "add page" and consistently reproducible on 3.4.10 LTR on Win10(x86_64). It just does not goes inactive **after deleting a field group or static section**.

I just tested on 3.4.10 on Windows and still can't see "add page" turning on after deleting the field group.

**Comment by gioman** [comment]
Confirmed also on 3.8
