### ISSUE TITLE
QGIS 3.8.1 crashes when exiting

### ISSUE THREAD

**Issue by rap-manager** [qgis/QGIS#31306]
## User Feedback

Closing out of QGIS, it always crashes rather than exiting 'nicely'. 

## Report Details

*Crash ID*: 62f1fcd2045780cb9f127836e6b579b8665f3e63

*Stack Trace*
<pre>
proj_lpz_dist :
proj_lpz_dist :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::QgsCoordinateTransform :
QHashData::free_helper :
QgsCoordinateTransform::addToCache :
QgsCoordinateTransform::invalidateCache :
QgsApplication::exitQgis :
QgisApp::~QgisApp :
CPLStringList::operator[] :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.8.1-Zanzibar
QGIS code revision: dcd95cc648
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by roya0045** [comment]
Have you tried with a clean profile and no plugins?

**Comment by gioman** [comment]
This is duplicate of a ton of other identical reports with the same stack trace.

**Comment by jef-n** [comment]
Duplicate of #28104
