### ISSUE TITLE
Ubuntu cosmic repository signed with expired gpg key

### ISSUE THREAD

**Issue by benelsen** [qgis/QGIS#31317]
**Describe the bug**

The qgis apt repos for `cosmic` (18.10) are still signed with the expired 2017 key.
Judging by the mtimes `stretch` and `xenial` might be affected too.

**How to Reproduce**

```
sudo apt update
(…)
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://qgis.org/debian cosmic InRelease: The following signatures were invalid: EXPKEYSIG CAEB3DC3BDF7FB45 QGIS Archive Automatic Signing Key (2017) <qgis-developer@lists.osgeo.org>
W: Failed to fetch https://qgis.org/debian/dists/cosmic/InRelease  The following signatures were invalid: EXPKEYSIG CAEB3DC3BDF7FB45 QGIS Archive Automatic Signing Key (2017) <qgis-developer@lists.osgeo.org>
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**QGIS and OS versions**
Ubuntu 18.10 cosmic

**Additional context**

**Comment by CoryAlbrecht** [comment]
I see this too:

`root@RedBarchetta:/home/cory# apt update
Hit:1 http://archive.canonical.com/ubuntu cosmic InRelease
Hit:2 http://security.ubuntu.com/ubuntu cosmic-security InRelease                                                                  
Hit:3 http://apt.postgresql.org/pub/repos/apt cosmic-pgdg InRelease                                                                
Hit:4 http://repo.steampowered.com/steam precise InRelease                                                                         
Hit:5 https://dl.yarnpkg.com/debian stable InRelease                                                                               
Hit:6 http://repository.spotify.com stable InRelease                                                                               
Hit:7 http://ca.archive.ubuntu.com/ubuntu cosmic InRelease                                                                         
Hit:8 http://ppa.launchpad.net/dreibh/ppa/ubuntu cosmic InRelease                                                    
Hit:9 http://qgis.org/ubuntu-nightly-release cosmic InRelease                                                                      
Ign:10 http://dl.google.com/linux/chrome/deb stable InRelease                                                                      
Hit:11 http://ca.archive.ubuntu.com/ubuntu cosmic-updates InRelease                                                       
Hit:12 http://dl.google.com/linux/chrome/deb stable Release                                         
Hit:13 http://ca.archive.ubuntu.com/ubuntu cosmic-backports InRelease                               
Hit:14 http://ppa.launchpad.net/inkscape.dev/stable-daily/ubuntu cosmic InRelease                   
Hit:15 http://ca.archive.ubuntu.com/ubuntu cosmic-proposed InRelease                                
Hit:16 http://ppa.launchpad.net/nextcloud-devs/client/ubuntu cosmic InRelease                       
Hit:17 http://ppa.launchpad.net/rodsmith/refind/ubuntu cosmic InRelease       
Hit:18 http://ppa.launchpad.net/ubuntuhandbook1/shutter/ubuntu cosmic InRelease
Err:9 http://qgis.org/ubuntu-nightly-release cosmic InRelease
  The following signatures were invalid: EXPKEYSIG CAEB3DC3BDF7FB45 QGIS Archive Automatic Signing Key (2017) <qgis-developer@lists.osgeo.org>
Reading package lists... Done 
Building dependency tree       
Reading state information... Done
20 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://qgis.org/ubuntu-nightly-release cosmic InRelease: The following signatures were invalid: EXPKEYSIG CAEB3DC3BDF7FB45 QGIS Archive Automatic Signing Key (2017) <qgis-developer@lists.osgeo.org>
W: Failed to fetch http://qgis.org/ubuntu-nightly-release/dists/cosmic/InRelease  The following signatures were invalid: EXPKEYSIG CAEB3DC3BDF7FB45 QGIS Archive Automatic Signing Key (2017) <qgis-developer@lists.osgeo.org>
W: Some index files failed to download. They have been ignored, or old ones used instead.
root@RedBarchetta:/home/cory# 
`

**Comment by jef-n** [comment]
cosmic is not build anymore. It's EOL.

**Comment by greathector7** [comment]
saludos. a mi igual me sale este error aunque con debian stretch y eso de ayer!!!
W: Error de GPG: https://qgis.org/debian stretch InRelease: Las siguientes firmas no fueron válidas: EXPKEYSIG CAEB3DC3BDF7FB45 QGIS Archive Automatic Signing Key (2017) <qgis-developer@lists.osgeo.org>
instale la key 2019 pero aun continua saliendome este error

**Comment by jef-n** [comment]
> Greetings. I still get this error although with debian stretch and yesterday!
> W: GPG error: https://qgis.org/debian stretch InRelease: The following signatures were invalid: EXPKEYSIG CAEB3DC3BDF7FB45 QGIS Archive Automatic Signing Key (2017) [qgis-developer@lists.osgeo.org](mailto:qgis-developer@lists.osgeo.org)
> install the 2019 key but this error still continues

stretch is unsupported too - see  https://www.qgis.org/en/site/forusers/alldownloads.html#id12, ie. only up to 3.4 (3.6 requires Qt 5.9 and above)
