### ISSUE TITLE
PostGIS Authentication Failure - QGIS Crash

### ISSUE THREAD

**Issue by andy-harney** [qgis/QGIS#31314]
## User Feedback

I've created a new QGIS user profile and imported in all my previous `default` profile PostGIS connections from the XML generated by saving PostGIS connections. Upon clicking the `Test Connection` button, I'm met with a `Enter Credentials` popup as the authentication details have legitimately changed. Clicking `Cancel` with cause QGIS to crash.

I can replicate this on both the new profile and the `default`.

QGIS is installed via OSGeo4W.

## Report Details

*Crash ID*: 1f2cca9ddef4026bfc7babe2759fb5a3f92ddb3c

*Stack Trace*
<pre>
registerGui :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
registerGui :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
QgisApp::dataSourceManager :
QgisApp::identifyMapTool :
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.8.2-Zanzibar
QGIS code revision: 4470baa1a3
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment]
> I can replicate this on both the new profile and the `default`.

what I did to test was:

* saved my connections
* changed the password of the user for one of those connections
* created a new QGIS profile
* using this new profile imported the connections
* tested the connection with that uses the users that had the password changed > connections fails as expected > no crash on clicking "cancel"

I did it right?

**Comment by andy-harney** [comment]
From the sounds of it yes.  
I'm testing the connection from within the `Edit` window within `Data Source Manager` if that makes any difference.
I can get it to crash on demand 😄 
![q_crash](https://user-images.githubusercontent.com/47160505/63506025-95f8e500-c4cc-11e9-8890-b505c30d9479.png)

**Comment by gioman** [comment]
>  I can get it to crash on demand smile

can you please try on a new/clean QGIS profile?

**Comment by nirvn** [comment]
This has been fixed, the next point release (released around the 19th of September) will contain the fix. Thanks for reporting this.
