### ISSUE TITLE
Block method of raster's layer DataProvider causes memory leak

### ISSUE THREAD

**Issue by matheusfillipe** [qgis/QGIS#31343]
This was tested in both windows 10 and ubuntu 18.04.3 with qgis 3.8.1

**Describe the bug**
Calling the block method of QgsRasterDataProvider causes a memory leak. The memory taken by the qgis process isn't freed after this variable is deleted by python's del. I am working on a plugin that calls this in a loop that can have like 1000 iterations.
Loop:
https://github.com/matheusfillipe/Topografia/blob/1488e1ab788089091147fb23b6316c82fea1e018/app/controller/estacas.py#L954

Function:
https://github.com/matheusfillipe/Topografia/blob/1488e1ab788089091147fb23b6316c82fea1e018/app/model/utils.py#L439

**How to Reproduce**
```
def memory_leaker(layer):
    B=[]
    for i in range(10):
	b=layer.dataProvider().block(1,dp.extent(), l.width(), l.height())
	B.append(b)
```

You can check out each time you run that loop an extra amount of ram memory is taken and is not freed by del B, and even though this is reassigning B each time it only makes the parent qgis threat takes more ram, whitch is unexpected.

Looks like someone forgot to call some deletes.... :)

**Comment by elpaso** [comment]
Maybe missing a `SIP_FACTORY` annotation since a new instance is returned.

**Comment by elpaso** [comment]
Forget about it, it already has the SIP_FACTORY decorator

**Comment by nyalldawson** [comment]
@elpaso looks like it's missing from the QgsRasterDataProvider subclass. But not sure if sip "inherits" this setting from the base class or not...

**Comment by elpaso** [comment]
@nyalldawson I'm testing it right now
