### ISSUE TITLE
Number inputs as raster calculator variables in QGIS Processing Modeler

### ISSUE THREAD

**Issue by fgianoli** [qgis/QGIS#31344]
**Add number as input variables to Raster Calculator**
The raster calculator does not allow other inputs than raster. It would be interesting to have the option to pass variables coming from numbers or vector fields

![image](https://user-images.githubusercontent.com/28388726/63498956-2fbd9380-c4c7-11e9-9535-f3b01e26f33c.png)

**Comment by roya0045** [comment]
A simpler approach would be to have the ability to import/use an expression (as expressions are already available in the modeler), no need to make a new type of input.

But the raster calculator is a strange beast.

**Comment by raymondnijssen** [comment]
As a (silly) workaround I'm using the 'Create constant raster layer' algorithm to generate a raster from my input value, which can function as the input for my raster calculator :/

**Comment by alexbruy** [comment]
In master raster calculator accepts expression which in turn can contain other modeler inputs.
