### ISSUE TITLE
Virtual Layer SQLite Natural Join - Instant Crash

### ISSUE THREAD

**Issue by Saijin-Naib** [qgis/QGIS#31356]
**Describe the bug**
My understanding is that QGIS is SQLite3 compliant, and as such, should be compatible with SQLite3 syntax and functions.

**How to Reproduce**
![image](https://user-images.githubusercontent.com/19295950/63547312-de7ac780-c4f9-11e9-941a-991ed764fa3a.png)
Create new Virtual Layer
Import needed layers (One MultiLineString, one Table)
Write SQLite Code:
SELECT * FROM "CAMP-RS_JobsList_XLS"
NATURAL JOIN "Reconciled"

Test & get valid SQLite code confirmation
Click Add and QGIS crashes instantly to desktop

**QGIS and OS versions**

QGIS version | 3.8.2-Zanzibar | QGIS code revision | 4470baa1a3
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.0 | Running against GEOS | 3.7.2-CAPI-1.11.0 b55d2125
PostgreSQL Client Version | 10.8 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Windows 10 (10.0) |   |

**Comment by gioman** [comment]
Can you add a sample dataset?

**Comment by roya0045** [comment]
Can you get a stack trace/core dump/debug or anything that might be of use to target the faulty function?

**Comment by Saijin-Naib** [comment]
@gioman,
I'll have to see if I can create a sanitized dataset for sharing.

@roya0045,
I'll see what I can get. Currently, nothing gets logged at all by QGIS, nor does QGIS make a dump file. I think there might be a MS/SysInternals tool I can try to see if it'll capture anything.

**Comment by roya0045** [comment]
Maybe the event manager has some nice info but as far as I recall it only shows the faulty dll/exe.
Otherwise this might be of use if you want to fiddle with it https://www.microsoft.com/en-ca/download/details.aspx?id=26798

**Comment by gioman** [comment]
>  Exception captured with DebugDiag v2u3:

I would still like to try a sample project+data and see if it crashes also on other machines.

**Comment by Saijin-Naib** [comment]
@gioman,
Here's a sanitized dataset based upon the actual data I used above. Same behavior.
[QGIS_NaturalJoin.zip](https://github.com/qgis/QGIS/files/3535310/QGIS_NaturalJoin.zip)

**Comment by gioman** [comment]
Crash confirmed on 3.8.2/Ubuntu.

**Comment by haubourg** [comment]
cc @mhugo

**Comment by pigreco** [comment]
CONFIRM

OSGeo4W64b - 3.4.13, 3.10 e master

**Comment by aborruso** [comment]
Me too using OSGeo4W64, 3.4.13 and 3.10

cc @mhugo

**Comment by pigreco** [comment]
cc @mhugo 
If you need a fundraiser, please give us a quote.

**Comment by agiudiceandrea** [comment]
It seems that `NATURAL JOIN` is missing in the parser
https://github.com/qgis/QGIS/blob/8836429b250cf26bd6e354556895c1333036924e/src/core/qgssqlstatementparser.yy#L458-L491

but `NATURAL` is listed among the operator tokens
https://github.com/qgis/QGIS/blob/8836429b250cf26bd6e354556895c1333036924e/src/core/qgssqlstatementparser.yy#L127


Probably, just adding it in qgssqlstatementparser.yy and here
https://github.com/qgis/QGIS/blob/8836429b250cf26bd6e354556895c1333036924e/src/core/qgssqlstatement.cpp#L45-L49
and here
https://github.com/qgis/QGIS/blob/8836429b250cf26bd6e354556895c1333036924e/src/core/qgssqlstatement.h#L168-L178
could solve the problem.

**Comment by mhugo** [comment]
Identified, working on a fix
