### ISSUE TITLE
Couldn't load SIP module (from qgis.PyQt import QtCore, from PyQt5.QtCore import *; DLL load failed) 

### ISSUE THREAD

**Issue by lalver1** [qgis/QGIS#31367]
**Describe the bug**
When loading QGIS 3.8.2 Zanzibar desktop in Windows 10 I get the following error:
`Couldn't load SIP module.`
`Python support will be disabled.`
`Traceback (most recent call last):`
  `File "", line 1, in` 
  `File "C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python\qgis\__init__.py", line 70, in` 
    `from qgis.PyQt import QtCore`
  `File "C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python\qgis\PyQt\QtCore.py", line 24, in` 
    `from PyQt5.QtCore import *`
`ImportError: DLL load failed: The specified procedure could not be found.`

`Python version:`
`3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]`

`QGIS version:`
`3.8.2-Zanzibar 'Zanzibar', 4470baa1a3`

If I try
`from PyQt5.QtCore import *`
from a Python interactive session I get no error. 
But trying 
`from qgis.PyQt import QtCore`
from an interactive session gives me the error: `ModuleNotFoundError: No module named 'qgis'`.

**How to Reproduce**

N/A

**QGIS and OS versions**

QGIS version
3.8.2-Zanzibar
QGIS code revision
4470baa1a3
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
2.4.1
Running against GDAL/OGR
2.4.1
Compiled against GEOS
3.7.2-CAPI-1.11.0
Running against GEOS
3.7.2-CAPI-1.11.0 b55d2125
PostgreSQL Client Version
10.8
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
5.2.0
Running against PROJ
Rel. 5.2.0, September 15th, 2018
OS Version
Windows 10 (10.0)

**Additional context**

I installed Anaconda. Then QGIS Madeira. I had no problems. The I uninstalled Anaconda and installed Python from python.org. I uninstalled QGIS Madeira and installed Zanzibar, then I got the error.

**Comment by nyalldawson** [comment]
The anaconda build isn't officially supported.

**Comment by lalver1** [comment]
I reinstalled Windows 10 to start fresh and I did not install Anaconda. I am still getting the same error:

```
Couldn't load SIP module.
Python support will be disabled.


Traceback (most recent call last):
  File "", line 1, in 
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\__init__.py", line 72, in 
    from qgis.PyQt import QtCore
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\PyQt\QtCore.py", line 26, in 
    from PyQt5.QtCore import *
ImportError: DLL load failed: The specified procedure could not be found.


Python version:
3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]

QGIS version:
3.4.11-Madeira 'Madeira', 9a8a6d4687

Python path:
['C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python', 'C:/Users/l_alv/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python', 'C:/Users/l_alv/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python/plugins', 'C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python/plugins', 'C:\\Program Files\\QGIS 3.4\\bin\\python37.zip', 'C:\\PROGRA~1\\QGIS3~1.4\\apps\\Python37\\DLLs', 'C:\\PROGRA~1\\QGIS3~1.4\\apps\\Python37\\lib', 'C:\\Program Files\\QGIS 3.4\\bin', 'C:\\Users\\l_alv\\AppData\\Roaming\\Python\\Python37\\site-packages', 'C:\\PROGRA~1\\QGIS3~1.4\\apps\\Python37', 'C:\\PROGRA~1\\QGIS3~1.4\\apps\\Python37\\lib\\site-packages', 'C:\\PROGRA~1\\QGIS3~1.4\\apps\\Python37\\lib\\site-packages\\win32', 'C:\\PROGRA~1\\QGIS3~1.4\\apps\\Python37\\lib\\site-packages\\win32\\lib', 'C:\\PROGRA~1\\QGIS3~1.4\\apps\\Python37\\lib\\site-packages\\Pythonwin']
```

**Comment by moisessalvino** [comment]
Aqui, para resolver o problema apaguei a pasta 

X:\Users\usuario\AppData\Roaming\QGIS

E, ao abrir o QGIS ele restabeleceu os arquivos python e entrou novamente. Espero ter ajudado.
