### ISSUE TITLE
is it possible to refresh the specific area of map in QgsMapCanvas? 

### ISSUE THREAD

**Issue by xee425** [qgis/QGIS#31373]
i am developing a map navigation application, using QGis (2.14) API and Qt C++,while moving the map on mapCanvas, i am having a problem on mapCanvas->refresh() call, when i call it the map ( raster map ) contract/expand a bit. is there any way to optimize the maprefresh() call? or just refresh the region of map which is not visible?

**Comment by roya0045** [comment]
You are aware that 2.14 is outdated and that even if something was changed in the core you would never benefit from it.

This seems more like a question, for that you should use the developer mailing list or other platforms such as gitter,etc.

**Comment by gioman** [comment]
> for that you should use the developer mailing list

yes, questions must be asked first in the users/developers mailing lists or other official channels.
