### ISSUE TITLE
error with returned angle by orientedMinimumBoundingBox()

### ISSUE THREAD

**Issue by 300000kms** [qgis/QGIS#31371]
in qgis3.4  and ubuntu16
with geometries projected in 25831
the angle obtained by the function **orientedMinimumBoundingBox** is not the same as the obtained using the function angleBetweenThreePoints 
And this second is the correct

### oriented minimum bounding box
geom, area, angle, width, height = z.geometry().orientedMinimumBoundingBox()

### angle manually calculated
a = math.degrees(QgsGeometryUtils.angleBetweenThreePoints(
    geom.vertexAt(0).x(),geom.vertexAt(0).y(),
    geom.vertexAt(1).x(),geom.vertexAt(1).y(),
    geom.vertexAt(1).x(),geom.vertexAt(1).y()+1000000,
))

a != angle
a != angle-180

**Comment by lbartoletti** [comment]
@300000kms QgsGeometryUtils.angleBetweenThreePoints return an angle in radians. You converted it in degrees, but orientedMinimumBoundingBox() returns an angle in degrees converted from angle in radians clockwise from the north direction.

You can take a look at our test files:
https://github.com/qgis/QGIS/blob/master/python/plugins/processing/tests/testdata/custom/oriented_bbox.gml
https://github.com/qgis/QGIS/blob/master/python/plugins/processing/tests/testdata/expected/oriented_bounds.gml
