### ISSUE TITLE
not show spatial tables  from conection  mssql

### ISSUE THREAD

**Issue by Gus12345tavo** [qgis/QGIS#31379]
In administrator source data
qgis version 3.6 y 3.8
database mssql

not shoe table spatial ( only not spatial )

**Comment by gioman** [comment]
Isn't there a "show geometryless tables" as we have for the PostGIS connections?

**Comment by gioman** [comment]
> Isn't there a "show geometryless tables" as we have for the PostGIS connections?

yes there is. Closing for lack of feedback, please reopen if necessary.
