### ISSUE TITLE
GeoNode provider continually tries to connect in the background

### ISSUE THREAD

**Issue by gubuntu** [qgis/QGIS#31375]
**Describe the bug**
I have some geonode instances that are not always available, for which I have created connections in the QGIS GeoNode provider. 

Every few seconds in a normal QGIS session, I get notifications of network issues, such as `Network request http://geonode.kartoza.com//api/layers/ timed out`, even though I have not gone anywhere near the connection in Browser. 

***Expected behaviour***
- Do not try to establish a connection unless the user attempts to open it in the browser
- When the user does try to open it, attempt it once and if there is an error, leave it there unless the user tries again. 

**How to Reproduce**

1. Set up a GeoNode to a valid instance (e.g. http://bims.ledet.gov.za/, which is on a VPN)
2. Re-open QGIS
3. You will see the connection trying to connect in the browser and eventually giving a yellow error message

**QGIS and OS versions**

QGIS 3
Mac OSX 10.14

**Comment by gioman** [comment]
@gubuntu seems ok to me on 3,22 > it fails to connect at QGIS start (as can be seen in logs) but then do not bother anymore.

**Comment by gubuntu** [comment]
I think we can close, the provider has also changed since then, thanks
