### ISSUE TITLE
qgis 3.8.2 symbol selector window crash

### ISSUE THREAD

**Issue by Matavelhas** [qgis/QGIS#31378]
**Describe the bug**

Each time I try to change the horizontal distance of the stock "pattern dot black texture (check attached print screen) the program completely freezes

**How to Reproduce**
Select a vectorial layer, select the pattern dot black and try to alter the horizontal distance of the dots and it will freeze on my machine

**QGIS and OS versions**

Versão do QGIS
3.8.2-Zanzibar
Revisão do código do QGIS
4470baa1a3
Compilado com Qt
5.11.2
Em execução com Qt
5.11.2
Compilado com GDAL/OGR
2.4.1
Em execução com GDAL/OGR
2.4.1
Compilado com GEOS
3.7.2-CAPI-1.11.0
Em execução com GEOS
3.7.2-CAPI-1.11.0 b55d2125
Versão de cliente PostgreSQL
10.8
Versão SpatiaLite
4.3.0
Versão QWT
6.1.3
Versão QScintilla2
2.10.8
Compilado com PROJ
5.2.0
Em execução com PROJ
Rel. 5.2.0, September 15th, 2018
OS Version
Windows 10 (10.0)

Nome do SO	Microsoft Windows 10 Pro
Versão	10.0.17134 Compilação 17134
Outra descrição do SO 	Indisponível
Fabricante do SO	Microsoft Corporation
Nome do sistema	PYN_Y_PON
Fabricante do sistema	To Be Filled By O.E.M.
Modelo do sistema	To Be Filled By O.E.M.
Tipo do sistema	x64-based PC
Sistema SKU	To Be Filled By O.E.M.
Processador	Intel(R) Celeron(R) CPU  J1800  @ 2.41GHz, 2408 Mhz, 2 Núcleo(s), 2 Processador(es) Lógico(s)
Data/versão de BIOS	American Megatrends Inc. P1.90, 01-03-2018
Versão SMBIOS	2.8
Versão do Controlador Incorporado	255.255
Modo de BIOS	Legado
Fabricante da Placa Base	ASRock
Modelo da Placa Base	Indisponível
Nome da Placa Base	Placa Base
Função da Plataforma	Ambiente de Trabalho
Estado de Arranque Seguro	Não suportado
Configuração PCR7	Enlace Não Possível
Diretório do Windows	C:\WINDOWS
Diretório do sistema	C:\WINDOWS\system32
Dispositivo de arranque	\Device\HarddiskVolume1
Região	Portugal
Camada de abstração de hardware (HAL)	Versão = "10.0.17134.858"
Nome de utilizador	Pyn_y_Pon\Aninhas
Fuso horário	Hora de Verão de GMT
Memória Física (RAM) Instalada	8,00 GB
Memória física total	7,71 GB
Memória física disponível	1,72 GB
Memória virtual total	15,5 GB
Memória virtual disponível	8,64 GB
Espaço de ficheiro de página	7,75 GB
Ficheiro de paginação	C:\pagefile.sys
Proteção DMA de Kernel	Desativado
Segurança baseada em virtualização	Não ativado
Suporte de Encriptação de Dispositivo	Razões para a falha na encriptação automática do dispositivo: O TPM não é utilizável, O enlace PCR7 não é suportado, Falha de Interface de Teste de Segurança de Hardware e dispositivo não compatível com InstantGo, Detetado barramento/dispositivo(s) compatíveis com DMA não permitidos, O TPM não é utilizável
Hyper-V - Extensões de Modo de Monitor VM	Sim
Hyper-V - Extensões de Tradução de Endereços de Segundo Nível	Sim
Hyper-V - Virtualização Ativada em Firmware	Sim
Hyper-V - Proteção de Execução de Dados	Sim

![Qgis2](https://user-images.githubusercontent.com/54453565/63619172-ced8ad00-c5e5-11e9-8e46-5e521bf63790.png)

**Additional context**

**Comment by gioman** [comment]
Please try using a new/clean QGIS profile.

**Comment by haubourg** [comment]
Agreed with @gioman . I cant' reproduce here.

**Comment by Matavelhas** [comment]
Thank you. Will try that.

Regards

Hugo

A sábado, 24 de ago de 2019, 17:12, Régis Haubourg <notifications@github.com>
escreveu:

**Comment by febex2008** [comment]
Same crash with symbol fill when trying to change the symbol spacing on QGIS 3.10, OSGeo 4W Installer, Windows 10 Professional V. 10.0.18362. I deleted the QGIS Folder in C:\Users\user\AppData\Roaming. This did not fix the issue. I did not experience this with earlier versions.

Is there a fix?

Cheers, 
Pirmin

**Comment by febex2008** [comment]
Here the crash report if this can help.

Crash ID: 8853bd784b0a8b859e10549cd4d251d57a90c399


Stack Trace


proj_context_delete_cpp_context :
proj_context_delete_cpp_context :
proj_context_delete_cpp_context :
OGRSpatialReference::~OGRSpatialReference :
OGRSpatialReference::operator= :
OGRSpatialReference::Release :
OGR_DS_TestCapability :
QgsConnectionPoolGroup::onConnectionExpired qgsconnectionpool.h:227
QMetaObject::activate :
QMetaObject::activate :
QApplicationPrivate::notify_helper :




QGIS Info
QGIS Version: 3.10.0-A Coru�a
QGIS code revision: 6ffa89eb3e
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by roya0045** [comment]
@febex2008 
It might be an issue with proj6, is the layer's projection fine, can you change it to another projection and then test?

**Comment by nyalldawson** [comment]
This was fixed upstream in the gdal library
