### ISSUE TITLE
Command-C in About dialog copies canvas geometries instead of dialog content

### ISSUE THREAD

**Issue by gubuntu** [qgis/QGIS#31392]
**Describe the bug**

Command-C to copy About dialog content copies canvas geometries instead. Command-A selects the geometries instead of the About content. Only right-click->Select right-click->Copy work

**How to Reproduce**

1. Open About dialog and click in it to focus
2. Command-A to select (nothing highlights)
3. Command-C to copy
4. Paste somewhere and records from the active layer in the canvas are pasted 

**QGIS and OS versions**

QGIS version | 3.4.11-Madeira | QGIS code revision | 9a8a6d4687
-- | -- | -- | --
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 520 | Running against PROJ | 5.2.0

**Comment by gubuntu** [comment]
fixed in 3.8 but needs to be backported to 3.4

**Comment by nyalldawson** [comment]
I don't think the severity of the issue warrants the risk associated with backporting to LTR.
