### ISSUE TITLE
GRASS plugin using wrong locale

### ISSUE THREAD

**Issue by gubuntu** [qgis/QGIS#31404]
**Describe the bug**

The plugin appears to be picking the wrong default locale. I have en_ZA, en_GB and es available on my Mac, in that order. Yet the module panel uses a combination of en and es. And the es isn't using the proper UTF accented characters either. 

<img width="540" alt="Screenshot 2019-08-25 at 11 55 39" src="https://user-images.githubusercontent.com/496911/63647814-f4210480-c726-11e9-883a-9c8b66c40293.png">

**How to Reproduce**
Run the plugin with various locales available?

**QGIS and OS versions**

QGIS version | 3.8.2-Zanzibar | QGIS code revision | 4470baa1a3
-- | -- | -- | --
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS Mojave (10.14) |   |

**Comment by gioman** [comment]
@gubuntu there are similar tickets already filed about this issue, have you had a look at them?

**Comment by gubuntu** [comment]
yes I did look at other issues related to locale and this seems different enough to warrant its own issue

**Comment by neteler** [comment]
Could you try with the new GRASS GIS 7.8.1 (https://github.com/OSGeo/grass/releases/tag/7.8.1)? Also locale related issues where fixed and Python 3 is supported since 7.8.0.
