### ISSUE TITLE
pgdump is no longer a recognized format for the GDAL/OGR convert format algorithm

### ISSUE THREAD

**Issue by FERRATON** [qgis/QGIS#31421]
The option to define the output format is normally given by the extension of the output file.
It is no longer possible to specify 'PgDump' as the output format (-f PGDump).

**Comment by gioman** [comment]
@FERRATON when this was last working?

**Comment by FERRATON** [comment]
at least in QGIS 2.16

**Comment by alexbruy** [comment]
I don't think this is regression and worth high priotiry tag. Now we rely on the supported output formats reported by QgsVectorFileWriter and detect output format by file extension. In old versions of GDALTools completely different mechanism was used.

This should be a feature request to add pgdump as supported output format to QgsVectorFileWriter.

**Comment by FERRATON** [comment]
I understand your point of view as a developer. However, for the user this is a regression since a feature that existed is no longer available. An important consequence from your point of view is that the functionality will not be restored in the LTR version that is the one we use.

**Comment by rouault** [comment]
Fixed in 3.10
