### ISSUE TITLE
Dynamic grid support in layout view.

### ISSUE THREAD

**Issue by MrChebur** [qgis/QGIS#31439]
**Feature description.**

A dynamic grid is a coordinate grid that does not change the distance between the lines of longitude and latitude when zooming in the layout view. Instead of changing the distance between the grid lines, it changes the grid labels. 

Alternatively dynamic grid algorithm can adjust the distance a little to keep the integer values of the distance between the grid lines.

Currently QGIS only supports static grids in layout view and user must manually change or select the appropriate grid for the current scale.

**Additional context**

Here is static grid example: [https://i.imgur.com/4ZyaG8i.gif](https://i.imgur.com/4ZyaG8i.gif)

Here is dynamic grid example (invalid labels): [https://i.imgur.com/kkjIsMe.gif](https://i.imgur.com/kkjIsMe.gif)

**Comment by nyalldawson** [comment]
See https://github.com/qgis/QGIS/pull/31435

**Comment by nirvn** [comment]
Dynamic grid implemented, woupidou.
