### ISSUE TITLE
GEOJSON suffering serious performance issues in QGIS 3.4.4 (windows)

### ISSUE THREAD

**Issue by unwitten** [qgis/QGIS#31433]
**Describe the bug**
I am encountering a number of performance issues using GeoJSON compared to SHP files. The easiest one to explain and reproduce is:
- Significant speed difference using 'Statistics' tool with 'Selected features only' checked for GeoJSON compared to SHP.

However, worth noting that I am noticing similar issues with:
- Significant speed difference using 'Save Selected Features As...' for GeoJSON compared to SHP.
- Significant speed difference with the canvas rendering larger GeoJSON layers as you pan around, compared to SHP files.

**How to Reproduce**
Data attached: 
[test_data.zip](https://github.com/qgis/QGIS/files/3543318/test_data.zip)

From the attached data above;
1. Start a new QGIS project
2. Open the SHP and GeoJSON layers in the data attached
3. Open the Statistics tool 
4. Select the 'line_shp' layer from the drop down menu
5. Select the 'length' field from the next drop down layer
6. Check the 'Selected features only' box
7. Using the 'Select features by area' tool, select roughly half of the features in the line_shp layer. Statistic tool should almost instantly calculate the 'length' statistics for the selected features.
8. Repeat the process, but this time with the 'line_geojson' layer, it should take significantly longer (around 3 seconds for me) for the Statistic tool to calculate the 'length' statistics for the GeoJSON layer.

Made a gif demonstrating:
![test_gif](https://user-images.githubusercontent.com/30657229/63728240-58b69d80-c8a6-11e9-97b5-7d350d301500.gif)

**QGIS and OS versions**
Using Windows 10

QGIS version
3.4.4-Madeira
QGIS code revision
f6ddc62fdb
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
2.4.0
Running against GDAL/OGR
2.4.0
Compiled against GEOS
3.7.0-CAPI-1.11.0
Running against GEOS
3.7.0-CAPI-1.11.0 673b9939
PostgreSQL Client Version
9.2.4
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
520
Running against PROJ
5.2.0

**Comment by nyalldawson** [comment]
Why do you expect the same performance as shapefile? GeoJSON is NOT an optimised format -- it's a plain text format designed for ease of use in Javascript only, with dramatically larger file sizes and which requires MUCH more work to parse and create.

Use Geopackage or shapefile if you want maximum speed.

**Comment by unwitten** [comment]
@nyalldawson  Thanks for the response.

Before closing this for good, could you please consider that:
- I cannot replicate this using QGIS 2.14.3 on Ubuntu (no noticeable difference between SHP and GeoJSON performance).
- The issue only presents when running the statistics on selected features - it is almost instant when running on the whole layer.
- On slightly larger layers (15,000 features), getting statistics for 7,500 selected features takes around **10 minutes** (As opposed to < 0.5 second for SHP). In this case, the GeoJSON is taking at least 1000 times as long as the SHP.

This seems to be more than an optimisation problem?

**Comment by nirvn** [comment]
Re 10 minutes, as Nyall mentioned it's pointless to throw GeoJSON vs SHP comparisons. If you are reporting a speed regression, it has to be confined to the same singular format. Eg, on 2.18 it took 3sec while on 3.8 it takes 10min.

**Comment by nyalldawson** [comment]
Well - it's possibly something which could be improved in GDAL, but not QGIS.

Basically the difference here is that when you run the operation over a set of selected features, QGIS uses gdal to seek to particular features in the layer. When you run over a whole layer, QGIS is just stepping through feature by feature. So the slowdown is caused by seeking to a particular feature in the layer many times. 

Shapefiles (and other binary formats) are optimised for this -- they use internal indexes so that readers can jump directly to the desired feature. GeoJSON doesn't have any of these smarts -- there's no indexing support in the format. Possibly GDAL could build an internal temporary index while reading, but that's something which would have to be done by the GDAL project, not QGIS.

**Comment by unwitten** [comment]
@nirvn , sure I understand, thanks!

This is actually what I tried to say in the first dot point of my previous comment.

Using this QGIS version on Ubuntu:
QGIS version
2.14.3-Essen
QGIS code branch
Release 2.14
Compiled against Qt
4.8.6
Running against Qt
4.8.6
Compiled against GDAL/OGR
2.2.2
Running against GDAL/OGR
2.1.0
Compiled against GEOS
3.5.0-CAPI-1.9.0
Running against GEOS
3.5.0-CAPI-1.9.0 r4084
PostgreSQL Client Version
9.3.20
SpatiaLite Version
4.1.1
QWT Version
6.0.0-svn
PROJ.4 Version
480
QScintilla2 Version
2.8.1

It takes **less than a second** to calculate the statistics for 7424 selected features.

Using the QGIS 3.4.4 version on Windows (as per the issue description), selecting the same 7424 features, it takes at least **10 minutes** to calculate the statistics.

Here is the geojson I used: 
[line_geojson.zip](https://github.com/qgis/QGIS/files/3543959/line_geojson.zip)


So there is a clear and significant difference between 2.14 and 3.4.4

**Comment by nyalldawson** [comment]
In that case you'll need to raise this with the GDAL authors.

**Comment by unwitten** [comment]
So, if I run the following code in the QGIS Python console, it runs in < 1 second, while the Statistic tool sits there taking its 10 minutes.

```python
from statistics import mean, median, stdev
layer = iface.activeLayer()
selected_feature_ids = set(layer.selectedFeatureIds())
selected_features = [feat for feat in layer.getFeatures() if feat.id() in selected_feature_ids]
lengths = [feat['length'] for feat in selected_features]
_count = len(lengths)
_sum = sum(lengths)
_mean = mean(lengths)
_median = median(lengths)
_st_dev = stdev(lengths)
_min = min(lengths)
_max = max(lengths)
_range = _max - _min
print(f"Count: {_count}")
print(f"Sum: {_sum}")
print(f"Mean: {_mean}")
print(f"Median: {_median}")
print(f"St. Dev.: {_st_dev}")
print(f"Min: {_min}")
print(f"Max: {_max}")
print(f"Range: {_range}")
```

Here's an example of me selecting the features, pasting my code into the console and waiting for the Statistic tool to crawl to 10% complete:
![test_gif](https://user-images.githubusercontent.com/30657229/63741512-be238200-c8d8-11e9-8357-561fb2630cb2.gif)


The interesting key here is that, in the Python console, the function `layer.getSelectedFeatures()` takes a long time to run for geoJSON, but the function `layer.selectedFeatureIds()` runs extremely quickly, as does `layer.getFeatures()`

Is the Statistic tool in QGIS implemented in such a way, that `layer.getSelectedFeatures` could be replaced with this approach (or something neater)?

**Comment by nyalldawson** [comment]
Your code is iterating through all features -- i.e.,an optimized case ONLY for geojson, but super-slow for all other data types. Try:

    layer = iface.activeLayer()
    selected_features = [feat for feat in layer.getFeatures(QgsFeatureRequest().setFilterFids(layer.selectedFeatureIds()))]

**Comment by unwitten** [comment]
Hmm, that code is running quite slowly for the GeoJSON- similar to `layer.getSelectedFeatures()`

**Comment by unwitten** [comment]
I will stop bothering you now, but as a final comment, I feel as though I have demonstrated a clear deficiency in the tool. I'm not asking someone to fix it today, and perhaps the best fix _is_ in GDAL itself; but I think the issue is valid and should remain open.

And to finish up my python console exercise, this is perhaps inelegant, but works.
```python
layer = iface.activeLayer()
if layer.storageType() == 'GeoJSON':
    selected_feature_ids = set(layer.selectedFeatureIds())
    selected_features = [feat for feat in layer.getFeatures() if feat.id() in selected_feature_ids]
else:
    selected_features = list(layer.getSelectedFeatures())
```

Thanks for responding all day!

**Comment by coreydexter** [comment]
@unwitten in the 3.4.12 version of QGIS this doesn't appear as an issue with your dataset. 
3.4.12 is using gdal 2.4.1, which has [fixed ](https://github.com/OSGeo/gdal/blob/v2.4.1/gdal/NEWS#L87) the issue  you've described (see [this related issue](https://issues.qgis.org/issues/21085))

**Comment by unwitten** [comment]
Nice to know! Thanks @coreydexter
