### ISSUE TITLE
Display the QGIS version of the project when opening it in a newer release

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#31430]
When opening a project in a newer release of QGIS, there's a message indicating that I'm opening from an old version and I could not reuse the project in that version.
It could be nice to know from which version I come.

I find the information later in the message log (it was necessary to reproduce and report a bug while upgrading)

**Comment by jgrocha** [comment]
Is this ok for you @DelazJ ?

![old project warning - display QGIS version](https://user-images.githubusercontent.com/163681/63769973-08523680-c8cc-11e9-84f3-8b2ae242b32e.png)

It will have impact (minimal) on the translation. I have to split the message into two different strings.

```c
    QString smalltext = tr( "This project file was saved by an older version of QGIS (%1)." ).arg( oldVersion ) +
                            tr ( " When saving this project file, QGIS will update it to the latest version, "
                            "possibly rendering it useless for older versions of QGIS." );
```

**Comment by DelazJ** [comment]
Yes @jgrocha. Thanks for looking into it.

**Comment by NathanW2** [comment]
Nice work.  That kind of tweak is super handy for users.
