### ISSUE TITLE
Labels position through formulas is uneffective

### ISSUE THREAD

**Issue by rbonnefoi** [qgis/QGIS#31444]
Dear all,

I just tried to use the label position formulas but it seems to be effectless. I never used this feature before. I am using the 3.8.2 QGIS version, and the problem was there with the 3.8.0 one, but I don't know whether it occured in a former version.

As I use a French version, I am not sure about the correct translation of the different fields. I'll use screenshots to be more explicit.

Here is my labelling option windows of my point layer :
![labelling options](https://user-images.githubusercontent.com/12908619/63761439-72b1a980-c8c1-11e9-966b-edf5fdc9932f.jpg)
You can notice with the yellow background right the X,Y shifting fields that the formula is really activated, and the set up formula is : 
`array( -10 * cos(radians(180 -  "angle" )), 10 * sin(radians("angle")))`
where angle is a layer field holding a integer value (an angle in degrees).
The preview of the formula result shown is (for a 60° value of angle) : 
`[ 4.999999999999998, 8.660254037844386 ]`

But whatever the value is, the label doesn't move. It looks like the formula is not taken into account at all, only the value input in the X,Y fields.

Any help would be greatly appreciated.

Many thanks,

Remi.

**Comment by nyalldawson** [comment]
It's not intuitive, but the expression result has to be a string. E.g.

    coalesce( -10 * cos(radians(180 - "angle" )), ',', 10 * sin(radians("angle")))

**Comment by gioman** [comment]
Should we make this a ticket against the documentation?

**Comment by rbonnefoi** [comment]
Ok, many thanks for your fast help. I just replaced the `coalesce ` function with `concatenate `(I think nyalldawson, you made a lapsus), and it works now.

The inline help is indeed ambiguous, as the expected format shown in the formula window of the shifting fields is `double [x,y]`, while the field description correctly states the valid input type as `string`.

**Comment by nyalldawson** [comment]
Thanks! I did make a mistake, and all day I've been trying to remember where i'd incorrectly written this 😛
