### ISSUE TITLE
Symbology tab widget does not horizontally expand in the layer properties dialog extent

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#31449]
Open the layer properties dialog
Go to the symbology tab and resize the dialog: it behaves correctly
Enable another tab and enlarge the dialog again: widgets should follow
Now go back to the symbology tab: they did not follow there and you get something like 

![midfilleddialog](https://user-images.githubusercontent.com/7983394/63775864-87516a00-c8e0-11e9-82d6-790c94f5bb7e.PNG)

Observed on Windows 10, 4470baa1a3 (3.8.2) and a3f411acce (3.9)

**Comment by elpaso** [comment]
I cannot reproduce on Linux/Master, I guess it's windows only

**Comment by DelazJ** [comment]
No, I also get it on bionic (older than a week). But in today's windows nigthly build, the issue is still there (and for some reason, the dialog becomes even smaller than it was/should be). And as soon as I begin to resize the main dialog, the resizing is done for the symbol selector.
![midfilleddialog2](https://user-images.githubusercontent.com/7983394/64534138-2c266b00-d315-11e9-9f45-19d066f2f2f7.PNG)

**Comment by elpaso** [comment]
I cannot reproduce this exact issue on Linux but I see some similar issues in the same dialog but different tabs.

**Comment by elpaso** [comment]
@DelazJ waiting for your feed-back if you have a chance to test this patch, or we can just merge and you will find it in the nightly builds.

**Comment by DelazJ** [comment]
Thanks @elpaso but sorry I'm not sure I can find a slot for building and testing. If it solves an issue on your side, let's merge and when available I'll check my issues on nightly

**Comment by elpaso** [comment]
ok, np, I tested on windows and it also fixes your issue.
