### ISSUE TITLE
QGIS crashes while moving labels

### ISSUE THREAD

**Issue by michapo** [qgis/QGIS#31442]
## User Feedback

Changed the field's "id"-attributes that is used to identify the custom label properties (recalculated all rows using row_number in the field calculator). 

It instantly crashed and won't load the project anymore.

It used to crash before, while moving a label of an object with an empty identifier-attribute-field.

"auxiliary_storage_labeling_positiony"
"auxiliary_storage_labeling_positionx"

## Report Details

*Crash ID*: 6c4bfaf77b3de258692b19507266a8dcc82f5b86

*Stack Trace*
<pre>
GEOSEquals_r :
GEOSEquals_r :
QgsGeos::closestPoint :
QgsGeometry::nearestPoint :
QgsRegularPolygon::center :
QgsRegularPolygon::firstVertex :
QgsExpressionFunction::run :
QgsExpressionNodeFunction::evalNode :
QgsExpressionNode::eval :
QgsExpressionFunction::run :
QgsExpressionNodeFunction::evalNode :
QgsExpressionNode::eval :
QgsRegularPolygon::center :
QgsRegularPolygon::firstVertex :
QgsExpressionFunction::run :
QgsExpressionNodeFunction::evalNode :
QgsExpressionNode::eval :
QgsRegularPolygon::center :
QgsRegularPolygon::firstVertex :
QgsExpressionFunction::run :
QgsExpressionNodeFunction::evalNode :
QgsExpressionNode::eval :
QgsRegularPolygon::center :
QgsRegularPolygon::firstVertex :
QgsExpressionFunction::run :
QgsExpressionNodeFunction::evalNode :
QgsExpressionNode::eval :
QgsExpression::evaluate :
QgsGeometryGeneratorSymbolLayer::render :
QgsSymbol::renderUsingLayer :
QgsFillSymbol::renderPolygon :
QgsSymbol::renderFeature :
QgsFeatureRenderer::renderFeature :
QgsVectorLayerLabelProvider::registerFeature :
QgsVectorLayerLabelProvider::registerFeature :
QgsMapRendererParallelJob::renderLayerStatic :
QgsMapRendererParallelJob::renderingFinished :
QgsImageOperation::overlayColor :
QgsMapRendererParallelJob::cancelWithoutBlocking :
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.8.2-Zanzibar
QGIS code revision: 4470baa1a3
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by roya0045** [comment]
Couldn't there be an alternate uid for each feature based on the row number or any other non-redundant information and use that all the time instead of forcing the user to specify a UID that can break the process? Then some safety checks would need to be performed when a feature is added/removed to generate an id that was not used previously.

**Comment by gioman** [comment]
Closing for the lack of feedback.
