### ISSUE TITLE
Syntax error new label geometry generator widget on macOS

### ISSUE THREAD

**Issue by timlinux** [qgis/QGIS#31456]
Trying out the new geometry generator for labels, I see there is an error shown in the panel:

<img width="390" alt="image" src="https://user-images.githubusercontent.com/178003/63806742-ed5fe080-c924-11e9-83d2-708c88893dba.png">

QGIS Details:

QGIS version | 3.9.0-Master | QGIS code revision | 6af029d52e
-- | -- | -- | --
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS Mojave (10.14) |

**Comment by m-kuhn** [comment]
What would you expect to be shown for an empty expression?

**Comment by gioman** [comment]
Seen also on Linux, removing the "macOS" tag.

**Comment by m-kuhn** [comment]
Sorry to break the relabeling party here ;-)

Shall we go for this instead?

> Syntax error: empty expression
