### ISSUE TITLE
Download of feature type failed: SSL handshake failed in 3.4 and 3.8 but not in 2.18

### ISSUE THREAD

**Issue by Bastiaandupon** [qgis/QGIS#31450]
**Describe the bug**

When I try to add WFS layer (described below) It connects to the mapserver, but it failed to add a layer and gives a error: _Download of feature type failed: SSL handshake failed_

However! It **works** in qgis version **2.18.28** (windows)

Help is greatly appreciated.

Best Regards,
Bastiaan

**How to Reproduce**

1. Add wfs layer: 'https://acc.dsr.maps.amsterdam.nl/mapserver/wfs' or 'https://dsr.maps.amsterdam.nl/mapserver/wfs'
2. Connect to wfs and select e.g:  'Invloedsgebied_Metro'
3. See error Log message panel:

        2019-08-27T15:18:00     WARNING    DescribeFeatureType network request failed for url pageSize='0' pagingEnabled='true' srsname='EPSG:28992' typename='ms:Invloedsgebied_Metro' url='<https://acc.dsr.maps.amsterdam.nl/mapserver/wfs'> version='2.0.0' table="" sql=: Download of feature type failed: SSL handshake failed 2019-08-27T15:18:00     WARNING    Download of feature type failed: SSL handshake failed

**QGIS and OS versions**

current version of this machine:

    QGIS version 3.8.2-Zanzibar
    QGIS code revision 4470baa1a3
    Compiled against Qt 5.9.5
    Running against Qt 5.9.5
    Compiled against GDAL/OGR 2.2.3
    Running against GDAL/OGR 2.4.0
    Compiled against GEOS 3.6.2-CAPI-1.10.2
    Running against GEOS 3.7.0-CAPI-1.11.0 
    PostgreSQL Client Version 10.10 (Ubuntu 10.10-0ubuntu0.18.04.1)
    SpatiaLite Version 4.3.0a
    QWT Version 6.1.3
    QScintilla2 Version 2.10.2
    PROJ.4 Version 493
    OS Version Ubuntu 18.04.3 LTS

**Additional context**

- tested with clean profiles

- tested on windows: 2.18/3.4/3.8

- tested for ubuntu: 3.8 only

N.B.
current server which on mapserver is configured is running **TLS 1.2** for authentication protocols.

**Comment by nirvn** [comment]
@Bastiaandupon , the network request fails due to a SSL error on the server-side of things. You can check by yourself, type the DescribeFeatureType request URL in your browser:

`https://dsr.maps.amsterdam.nl:80/mapserver?SERVICE=WFS&REQUEST=DescribeFeatureType&VERSION=2.0.0&TYPENAMES=ms:Vergunningsgebieden_NZL&TYPENAME=ms:Vergunningsgebieden_NZL`

You'll get an error page.

**Comment by rmarzocchi84** [comment]
https://github.com/qgis/QGIS/issues/26014 I think there is also a regression ( I have the same problem)

**Comment by elpaso** [comment]
@rmarzocchi84 if the WFS works on QGIS Desktop but not in QGIS Server, please file a separate ticket.

**Comment by nirvn** [comment]
As far as I understand, the handshake failure is warranted. As I said, firefox chrome et cie also fail to connect to the address. If anything, Qt4 (used in 2.18) was not properly failing and permitted an unsafe connection to happen.

**Comment by elpaso** [comment]
@nirvn of course, but I believe @rmarzocchi84 was referring to a valid endpoint that works in a browser and in QGIS Desktop but does not in QGIS server, but better not to mix things up here, that's why I asked to file a separate ticket for the server issue.

**Comment by rmarzocchi84** [comment]
Yes the object of my issue is Qgis server.


It is now possible to divide issues between server and desktop?

**Comment by elpaso** [comment]
It's always been possible (and recommended), it's mandatory if an issue is server-specific.

**Comment by rmarzocchi84** [comment]
Ok, sorry. I have done just now https://github.com/qgis/QGIS/issues/31675
