### ISSUE TITLE
Watch file not adding new columns

### ISSUE THREAD

**Issue by ghtmtt** [qgis/QGIS#31452]
Actually I'm not sure if this is a bug or a feature request.

If you load a csv file (also without coordinates to stay simple) and check the `watch file` check box it works nice if other **rows** are added. But if new columns are added then QGIS is not watching the file anymore. 

Is this the normal behavior?

QGIS 3.9 on debian

**Comment by elpaso** [comment]
Sounds like a bug to me.

**Comment by elpaso** [comment]
Not sure if there is an easy fix though.

**Comment by elpaso** [comment]
@ghtmtt  Can you share a project and test file?

**Comment by ghtmtt** [comment]
here it is 
[test.zip](https://github.com/qgis/QGIS/files/3590840/test.zip)

**Comment by elpaso** [comment]
I'm checking this one, I must say that on current master it does not even work when new rows are added (the attribute table is not updates until you refresh it). Does it work for you?

For the column change I think it's a feature request, because it was never implemented and I couldn't find a way to do it using the current API.

**Comment by ghtmtt** [comment]
thanks for checking. 

> I'm checking this one, I must say that on current master it does not even work when new rows are added (the attribute table is not updates until you refresh it). Does it work for you?

only with refreshing yes. It seems it is not refreshing it automatically

> For the column change I think it's a feature request, because it was never implemented and I couldn't find a way to do it using the current API.

I was suspecting it ;) would be a good enhancement. Should I open a specific feature request for this?

**Comment by elpaso** [comment]
Yes please, but beware that it's not an easy fix, it requires a core change by adding a signal from the dataprovider that is connected to the vector layer and that would update the fields when they have changed externally, currently there is no implementation for this in any data provider.

**Comment by Saijin-Naib** [comment]
Related?:
#29617
#29629
#29616

Possibly fixing row not updating?
#33259
