### ISSUE TITLE
QGIS Desktop 3.4.4 continues to Crash

### ISSUE THREAD

**Issue by kamillepreto** [qgis/QGIS#31472]
Error message in a .txt is attached & screenshot image is attached

We upgraded to QGIS Desktop 3.4.4 and it continues crashing and will not open up. The only steps I am completing is selecting "Import settings from QGIS 2" and I've also selected "I want a clean start. Don't import my QGIS 2 settings" to see if that option would work instead. Click continue. QGIS 3.4 continues to open up, and then the "Private qgis.db" error pops up stating "
![errorqgis](https://user-images.githubusercontent.com/54640349/63879464-c7285800-c999-11e9-938e-b37fa6df4993.JPG)
[ERROR] Can not make qgis.db private copy". When I select "ok", QGIS crashes with the attached .txt.

[QGIS.txt](https://github.com/qgis/QGIS/files/3552171/QGIS.txt)

**Comment by nirvn** [comment]
The crasher has already been fixed, update to the latest LTR and you'll be crash free.

**Comment by NathanW2** [comment]
People still seem to be having it in 3.8.2 where it should be fixed as well
so I'm not sure.  Hopefully, it is at least fixed in the LTR...

**Comment by nirvn** [comment]
@NathanW2 , that's not the exit crash; on the basis of the provided stack trace, this is a crash that I fixed whereas messages were sent to the message bar prior to its creation (auth-related).

**Comment by NathanW2** [comment]
ahh opps should have read the first message better :P Sorry got my issues
mixed up.

**Comment by kamillepreto** [comment]
So is the issue resolved, or does this ticket need to be re-opened? I have a project due for the Census Bureau and can't move forward until it's functioning correctly. Thanks for the help.

**Comment by nirvn** [comment]
The specific crash you reported is indeed fix. Happy mapping!

**Comment by kamillepreto** [comment]
Thank you. Is there anything that I need to do on my end?

**Comment by nirvn** [comment]
You mean besides downloading the latest version on qgis.org ? Nothing
