### ISSUE TITLE
Export Attribute Table by Copy&Paste with multiline still not working properly in 3.8.2

### ISSUE THREAD

**Issue by Meibes** [qgis/QGIS#31484]
this is a follow up of #30580, because #30620 doesn't seem to fix the issue on my machine, at least not in LibreOffice or Excel, see attached screenshots. I'm using 3.8.2 which should already have the mentioned fixes? At least I can clearly see the quotes on the multiline field

![qgis_multiline_data](https://user-images.githubusercontent.com/26258451/63916632-1a051c80-ca39-11e9-8e3e-82ad2b4a4375.png)

![qgis_multiline_data_libreoffice](https://user-images.githubusercontent.com/26258451/63916642-1ec9d080-ca39-11e9-8a59-58687361c698.png)

![qgis_multiline_data_excel](https://user-images.githubusercontent.com/26258451/63916645-225d5780-ca39-11e9-84b0-f564f6d9de75.png)

**Comment by nirvn** [comment]
Fixed, grab a weekly build or wait for the next point release around the 19th of September. Thanks for reporting this issue (twice! ;) )
