### ISSUE TITLE
TestQgsFileDownloader has a too strict expenctance on SSL error message

### ISSUE THREAD

**Issue by strk** [qgis/QGIS#31497]
On my system (Ubuntu 18.04) it fail with:

> expected:
SSL Errors: ;The root certificate of the certificate chain is self-signed, and untrusted
actual:
No certificates could be verified;SSL Errors: ;The issuer certificate of a locally looked up certificate could not be found

I guess the test could be made more tollerant ?

**Comment by gioman** [comment]
@strk Is this still valid?
