### ISSUE TITLE
Filepath misunderstood when loading a CSV file with addVectorLayer 

### ISSUE THREAD

**Issue by etienne67** [qgis/QGIS#31505]
**Describe the bug**
I try to load a CSV file using this code:
url = "file:///C:/Sigmoé/l_adresse_etat.csv?delimiter=;"
iface.addVectorLayer(url, "l_adresse_etat", "delimitedtext")
And the file is not correctly loaded because of the path that contains an accented character.
If I use a path with 'Sigmoe' instead of 'Sigmoé', the csv file is correctly loaded. This a problem of accented characterm misunderstood (unicode problem ?!)

**How to Reproduce**

1. Put a CSV file in a directory with a name containing accented character
2. Try to load that file with python code using addVectorLayer or QgsVectorLayer (same problem)

**QGIS and OS versions**

Version de QGIS
3.4.8-Madeira
Révision du code
04ee8e0761
Compilé avec Qt
5.11.2
Utilisant Qt
5.11.2
Compilé avec GDAL/OGR
2.4.1
Utilisé avec GDAL/OGR
2.4.1
Compilé avec GEOS
3.7.2-CAPI-1.11.0
Utilisé avec GEOS
3.7.2-CAPI-1.11.0 b55d2125
Version du client PostgreSQL
9.2.4
Version de SpatiaLite
4.3.0
Version de QWT
6.1.3
Version de QScintilla2
2.10.8
Compilé avec PROJ
520
Fonctionne avec PROJ
5.2.0

**Additional context**

**Comment by roya0045** [comment]
This is related to python and not qgis.

**Comment by nirvn** [comment]
I suspect it might actually be a real issue. I'll look into it, have a gut feeling as to what might be wrong.

**Comment by nirvn** [comment]
@etienne67 , actually, this isn't a bug; the text delimiter provider is expecting an _encoded_ URL to be passed on. For eg your file path in encoded form looks like this: `file:///home/webmaster/Desktop/Sigmo%C3%A9/test.txt`.

You can use QUrl.fromLocalFile( filepath ) to get the proper encoded string.

Enjoy coding!

**Comment by etienne67** [comment]
@nirvn 
Thank you for your answer. Thanks to that, I've found the complete process to create the correct string to pass:
`uri =  QUrl.fromLocalFile(file_path).toString(QUrl.EncodeUnicode)`
`nw_lyr = QgsVectorLayer(uri, lyr_name, 'delimitedtext')` 
Perhaps it should be explained like that in the QGIS doc `(https://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/loadlayer.html).`
Nevertheless, I think there's a strange handling of the filepath in QgsVectorLayer. Because if you use 'ogr' provider instead of 'delimitedtext' provider, you have to use the direct file_path and not the encoded file_path:
`nw_lyr = QgsVectorLayer(file_path, lyr_name, 'ogr')`
So it's a little bit disturbing and not very logical, to my mind ;-)
It's just a little remark to meditate, but thank you for your nice job on QGIS.

**Comment by DelazJ** [comment]
> Perhaps it should be explained like that in the QGIS doc (https://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/loadlayer.html).

May I suggest you open an issue report in [QGIS-Documentation](https://github.con/qgis/QGIS-Documentation/issues) repository or even better, provide a fix (source file is accessible from the footer of the link you provided https://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/loadlayer.html)? Thanks.
