### ISSUE TITLE
Not editable csv layer when added with addVectorLayer or QgsVectorLayer

### ISSUE THREAD

**Issue by etienne67** [qgis/QGIS#31506]
**Describe the bug**
When you add a CSV file with a Python code using addVectorLayer or QgsVectorLayer, the layer can't be edited in QGIS.

**How to Reproduce**
1. Add a csv layer using this type of Python code:
url = "file:///C:/TEST/l_adresse_etat.csv?delimiter=;"
iface.addVectorLayer(url, "l_adresse_etat", "delimitedtext")
2. See in QGIS that the edit icon is not enabled on this layer.

**QGIS and OS versions**
Version de QGIS
3.4.8-Madeira
Révision du code
04ee8e0761
Compilé avec Qt
5.11.2
Utilisant Qt
5.11.2
Compilé avec GDAL/OGR
2.4.1
Utilisé avec GDAL/OGR
2.4.1
Compilé avec GEOS
3.7.2-CAPI-1.11.0
Utilisé avec GEOS
3.7.2-CAPI-1.11.0 b55d2125
Version du client PostgreSQL
9.2.4
Version de SpatiaLite
4.3.0
Version de QWT
6.1.3
Version de QScintilla2
2.10.8
Compilé avec PROJ
520
Fonctionne avec PROJ
5.2.0

**Additional context**

**Comment by nirvn** [comment]
You are loading the CSV through the delimited text provider, which doesn't support writing. If you open the CSV through the ogr provider, you'll be able to add and edit features.

**Comment by roya0045** [comment]
I'm pretty sure this is intended behaviour otherwise this would have been changed a long time ago. Simply export the shapefile and then you can edit it.
