### ISSUE TITLE
Allow defined data control over crs properties in the map composer.

### ISSUE THREAD

**Issue by alexandreparente** [qgis/QGIS#31518]
**Feature description.**
QGIS would rock even more if allow defined data control over src properties in the map composer.

**Additional context**
I could generate an atlas of all features using the UTM coordinate system even when the cover layer crossed more than one UTM zone.

![output_1](https://user-images.githubusercontent.com/5301826/64080747-44bbd300-ccce-11e9-95d6-676284320298.jpg)

![Captura de tela de 2019-09-01 16-34-54](https://user-images.githubusercontent.com/5301826/64081421-f8c15c00-ccd6-11e9-8297-f0a079318a04.png)

![Captura de tela de 2019-09-01 16-35-36](https://user-images.githubusercontent.com/5301826/64081422-0676e180-ccd7-11e9-8b94-248153cd4d10.png)

**Comment by nyalldawson** [comment]
You could use data defined visibility with a set of multiple overlapping maps in different crs as a workaround

**Comment by alexandreparente** [comment]
Brazil has eight utm zones like Australia 😁

**Comment by roya0045** [comment]
Didn't notice that this one existed before making mine... Welp I guess you can close this one @alexandreparente
