### ISSUE TITLE
Union algorithm with a single layer

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#31528]
Using this shapefile (I checked geometry and has no problems) as an input layer in the [Union algorithm](http://changelog.qgis.org/en/qgis/version/3.2.0/#union-algorithm-with-single-layer) I get this error:

EDIT:
![image](https://user-images.githubusercontent.com/7631137/64165157-c59cdb00-ce44-11e9-933a-403dee9faf31.png)

![image](https://user-images.githubusercontent.com/7631137/64100959-09bcac80-cd6d-11e9-9d2b-226ecff168f1.png)

I have the same mistake in 3.4.11 LTR and 3.8.2 Zanzibar

## shapefile: [aaaa.zip](https://github.com/qgis/QGIS/files/3565128/aaaa.zip)

```
Versione di QGIS 3.4.11-Madeira
Revisione codice QGIS 9a8a6d4687
Compilato con Qt 5.11.2
Esecuzione con Qt 5.11.2
Compilato con GDAL/OGR 2.4.1
Esecuzione con GDAL/OGR 2.4.1
Compilato con GEOS 3.7.2-CAPI-1.11.0
Esecuzione con GEOS 3.7.2-CAPI-1.11.0 b55d2125
Versione client PostgreSQL 10.8
Versione SpatiaLite 4.3.0
Versione QWT 6.1.3
Versione QScintilla2 2.10.8
Compiled against PROJ 520
Running against PROJ 5.2.0
```

**Comment by gioman** [comment]
works fine here on 3.8.2 on Ubuntu 18.04.

**Comment by pigreco** [comment]
In 3.8.2 OSGeo4W64 Win10 does not work

![image](https://user-images.githubusercontent.com/7631137/64109557-1c8cac80-cd80-11e9-96e9-500368639071.png)

**Comment by gioman** [comment]
Just tried on 3.8.2 on OSGeo4W, still works here:

```
QGIS version: 3.8.2-Zanzibar
QGIS code revision: 4470baa1a3
Qt version: 5.11.2
GDAL version: 2.4.1
GEOS version: 3.7.2-CAPI-1.11.0 b55d2125
PROJ version: Rel. 5.2.0, September 15th, 2018
Processing algorithm…
Algorithm 'Union' starting…
Input parameters:
{ 'INPUT' : '//vboxsvr/giovanni/Downloads/aaaa/iso300.shp', 'OUTPUT' : 'TEMPORARY_OUTPUT', 'OVERLAY' : '//vboxsvr/giovanni/Downloads/aaaa/iso300.shp', 'OVERLAY_FIELDS_PREFIX' : '' }

Execution completed in 0.38 seconds
Results:
{'OUTPUT': 'Union_aee9a507_d44b_4c5a_accf_a7da55dc46d8'}

Loading resulting layers
Algorithm 'Union' finished
```

**Comment by aborruso** [comment]
@gioman please try with [this one](https://github.com/qgis/QGIS/files/3565793/tmp_dbg.zip).

Thank you

**Comment by gioman** [comment]
> @gioman please try with [this one](https://github.com/qgis/QGIS/files/3565793/tmp_dbg.zip).

no error here on Win/OSGeo4W/3.8.2

**Comment by pigreco** [comment]
does not work in the master :-(

![image](https://user-images.githubusercontent.com/7631137/64113519-d4bf5280-cd8a-11e9-9c19-8f0a58bf511c.png)

**Comment by roya0045** [comment]
Tried in 3.4.4 windows 10 with a square temporary layer over the provided layer and with the same crs. All good

**Comment by aborruso** [comment]
> no error here on Win/OSGeo4W/3.8.2

Please note that I use a temp layer (the settings below) and then I click on run.
@gioman Did you have used temp output?

Thank you

![image](https://user-images.githubusercontent.com/30607/64152945-fde4ef00-ce2d-11e9-920d-af284c3b3011.png)

**Comment by aborruso** [comment]
Moreover in Union output the polygon 1 disappears.

This is my [input file](https://github.com/qgis/QGIS/files/3568339/output.zip)

![image](https://user-images.githubusercontent.com/30607/64153400-186b9800-ce2f-11e9-9a94-35881f371142.png)

**Comment by Korto19** [comment]
![immagine](https://user-images.githubusercontent.com/36882050/64163613-e283df00-ce41-11e9-9676-a4ae6dbaa280.png)

**Comment by Korto19** [comment]
anyway me too

**Comment by roya0045** [comment]
@aborruso does it work properly with an overlay layer specified?

**Comment by aborruso** [comment]
@roya0045 does it work for you without an overlay layer and a temporary output?

I will do the test you have asked me to do.

Thank you

**Comment by roya0045** [comment]
@aborruso I have tested 3.4.4 with an overlay and a temporary output and it was fine, I have tested 3.4.0 with no overlay and a temp output it was fine. (I don't have access to a more recent version for the moment). This might be a regression.

**Comment by aborruso** [comment]
> @aborruso does it work properly with an overlay layer specified?

@roya0045 no error, but it's not my goal. I need to do an Overlay Union only to one layer.

**Comment by aborruso** [comment]
In this video you can see all:

- what I do;
- the message error;
- the wrong geometric output.

https://youtu.be/Qzo0gR0-yNk

**Comment by gioman** [comment]
> I have the same mistake in 3.4.11 LTR and 3.8.2 Zanzibar

@pigreco how this differs from https://github.com/qgis/QGIS/issues/31541 ?

**Comment by gioman** [comment]
> shapefile: [aaaa.zip](https://github.com/qgis/QGIS/files/3565128/aaaa.zip)

just to try clarify, this sample works fine for me as it is (so with the 4326 crs) on 3.8.2, no errors or data loss.

**Comment by gioman** [comment]
> This is my [input file](https://github.com/qgis/QGIS/files/3568339/output.zip)

@aborruso about this sample data I can make the same comment as here https://github.com/qgis/QGIS/issues/31541#issuecomment-527881871

**Comment by pigreco** [comment]
@gioman 

>@pigreco in che modo differisce da # 31541 ?

- the #31528 returns an error
- the #31541  does not return error but data loss

**Comment by pigreco** [comment]
@gioman 

>just to try clarify, this sample works fine for me as it is (so with the 4326 crs) on 3.8.2, no errors or data loss.

I tried with the 3.8.2 and the dataset aaaa.zip: I get an error !!!! (also in the master - temporary file and 4326)

**Comment by gioman** [comment]
> the #31541 does not return error but data loss

@pigreco @aborruso I retested on 3.8.2 the sample dataset https://github.com/qgis/QGIS/files/3568314/shape.zip attached in #31541 and I get the error AND the incomplete result. So here in my case this is the same case as #31528

```
QGIS version: 3.8.2-Zanzibar
QGIS code revision: 4470baa1a3
Qt version: 5.9.5
GDAL version: 2.2.3
GEOS version: 3.6.2-CAPI-1.10.2 4d2925d6
PROJ version: 493
Processing algorithm…
Algorithm 'Union' starting…
Input parameters:
{ 'INPUT' : '/home/giovanni/Downloads/shape/tmp_tp_300.shp', 'OUTPUT' : 'TEMPORARY_OUTPUT', 'OVERLAY' : None, 'OVERLAY_FIELDS_PREFIX' : '' }

Feature could not be written to Union_80ed7baa_c41c_419b_b48a_330902823d7a
Execution completed in 0.04 seconds
Results:
{'OUTPUT': 'Union_80ed7baa_c41c_419b_b48a_330902823d7a'}

Loading resulting layers
Algorithm 'Union' finished
```

and as said, if I save the sample dataset to a projected CRS it all works as expected.

**Comment by gioman** [comment]
> I tried with the 3.8.2 and the dataset aaaa.zip: I get an error !!!! (also in the master - temporary file and 4326)

still no issues here on 3.8.2/linux.

**Comment by pigreco** [comment]
Honestly, I got tired.
For me it's a bug, I've reported it and if any developer wants to fix it I'm available for other tests.

thanks for your patience @giohappy

**Comment by aborruso** [comment]
@gioman Now I have 3.8.2-Zanzibar:

- using EPSG:4326 I have error and data loss;
- using EPSG:3004 it seems all OK.

**Comment by gioman** [comment]
> Honestly, I got tired.
> For me it's a bug

is just a matter to determine if is a bug, and in what circumstances it appears. From what I see there is clearly an issue when the submitted datasets are in WGS84, while are ok if in a projected CRS. This does not seems to match your experience, so this needs further investigations.

**Comment by gioman** [comment]
> @gioman Now I have 3.8.2-Zanzibar:
> 
>     * using EPSG:4326 I have error and data loss;
> 
>     * using EPSG:3004 it seems all OK.

@aborruso so this matches my observations.

**Comment by pigreco** [comment]
close issue
to clarify it we will open a summary
with two typical cases
