### ISSUE TITLE
Union algorithm with a single layer returns incomplete geometry

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#31541]
I have a shapefile on which I apply the [Union ](http://changelog.qgis.org/en/qgis/version/3.2.0/#union-algorithm-with-single-layer)algorithm using only this layer (no overlapping layers):

1. startup algorithm union
2. select the layer
3. save as GeoPackage

![image](https://user-images.githubusercontent.com/7631137/64166064-9e470d80-ce46-11e9-8627-a1900d2026f0.png)

at the end of the process I DO NOT receive errors in the log but the geometry is clearly not complete, a piece is missing.

![image](https://user-images.githubusercontent.com/7631137/64153396-1570a780-ce2f-11e9-8cf4-f00f030bceee.png)

PS1: if I left as a temporary file I get an error (issue  [#31528](https://github.com/qgis/QGIS/issues/31528))
PS2: if I save in shp I get an error and the geometry is incomplete

## shapefile: [shape.zip](https://github.com/qgis/QGIS/files/3568314/shape.zip)

```
Versione di QGIS 3.4.11-Madeira
Revisione codice QGIS 9a8a6d4687
Compilato con Qt 5.11.2
Esecuzione con Qt 5.11.2
Compilato con GDAL/OGR 2.4.1
Esecuzione con GDAL/OGR 2.4.1
Compilato con GEOS 3.7.2-CAPI-1.11.0
Esecuzione con GEOS 3.7.2-CAPI-1.11.0 b55d2125
Versione client PostgreSQL 10.8
Versione SpatiaLite 4.3.0
Versione QWT 6.1.3
Versione QScintilla2 2.10.8
Compiled against PROJ 520
Running against PROJ 5.2.0
```

**Comment by pigreco** [comment]
from further evidence I note that the problem is related to the function $ id = 0
changing the order from $id = 0 to $id = 7 (cut and paste the function) the problem no longer exists

**Comment by gioman** [comment]
@pigreco this seems to be a rounding issue as the layer is in WGS84, is you save it in a projected CRS (i.e. 3003) the operation works as expected. Can you confirm?

If this is the case (we need a dev confirmation) this could affect also other tools.

**Comment by pigreco** [comment]
@gioman 
Unfortunately I cannot confirm, other errors remain.

![image](https://user-images.githubusercontent.com/7631137/64201168-4e8c3480-ce8e-11e9-8e7b-3e9f1aaa47be.png)

![image](https://user-images.githubusercontent.com/7631137/64201233-7bd8e280-ce8e-11e9-8819-856fad5d96b4.png)


You get an error in the EPSG 4326 case ??

**Comment by gioman** [comment]
> You get an error in the EPSG 4326 case ??

yes, as I wrote https://github.com/qgis/QGIS/issues/31541#issuecomment-527579757

But I'm NOT getting any error if your sample layer is reprojected to a projected CRS like 3003 or 3004. in this case it all works fine here (also regardless of the type of input, I tried gpkg, shape and temp layer).

I'm on 3.8.2 would you mind trying on the same version?

**Comment by pigreco** [comment]
@gioman 

>I'm on 3.8.2 would you mind trying on the same version?

with the 3.8.2 I have no errors (temporary - 4326)

![image](https://user-images.githubusercontent.com/7631137/64262626-a7aba500-cf2e-11e9-9819-d13f69bdbd14.png)

**Comment by pigreco** [comment]
also works in the master,
does not work in 3.4.11 LTR

![image](https://user-images.githubusercontent.com/7631137/64265289-f0655d00-cf32-11e9-9ed6-d0481bb10ec1.png)

**Comment by gioman** [comment]
>  does not work in 3.4.11 LTR

even if the input has a projected CRS?

**Comment by pigreco** [comment]
close issue
to clarify it we will open a summary
with two typical cases
