### ISSUE TITLE
Crash when deleting print layout items

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#31549]
## User Feedback

Since deleting a page does not remove its items (see #26618), I had to select all the items (map, label, legend, scale bar) that are on the page and delete them first. Pressing the DEL button with that selection results in a crash.

## Report Details

*Crash ID*: 49d40d2abbd7434db890cc41631ce23549141083

*Stack Trace*
<pre>
QgsLayoutItem::writeXml :
QgsLayoutItemUndoCommand::saveState :
QgsLayoutUndoStack::beginCommand :
QgsLayoutItem::beginCommand :
QgsAttributeActionDialog::showWidgetInAttributeTable :
QMetaObject::activate :
QgsLayoutItemComboBox::itemChanged :
QMetaObject::activate :
QWidgetLineControl::`default constructor closure' :
QComboBox::setCurrentIndex :
QComboBox::setCurrentIndex :
QWidgetLineControl::`default constructor closure' :
QMetaObject::activate :
QAbstractItemModel::endRemoveRows :
QSortFilterProxyModel::removeRows :
QSortFilterProxyModel::sortRole :
QSortFilterProxyModel::`default constructor closure' :
QMetaObject::activate :
QAbstractItemModel::beginRemoveRows :
QgsLayoutModel::setItemRemoved :
QgsLayout::removeLayoutItem :
QgsLayoutView::deleteItems :
QgsLayoutView::deleteSelectedItems :
QMetaObject::activate :
QAction::activate :
QAction::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QShortcutMap::dispatchEvent :
QShortcutMap::tryShortcut :
QWindowSystemInterface::handleShortcutEvent :
QGuiApplicationPrivate::processKeyEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.8.2-Zanzibar
QGIS code revision: 4470baa1a3
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by elpaso** [comment]
@DelazJ can you share a project to reproduce the issue? I cannot reproduce it locally with a test template.

**Comment by elpaso** [comment]
Just spoke to @nyalldawson, he has some good ideas for a deeper rework of the undo stack for layouts.

**Comment by DelazJ** [comment]
@elpaso Do you need a project with data (they are in PG and some are sensible) or would a qgs file be enough, since the "bug" seems to be in layout?

**Comment by elpaso** [comment]
Any project that shows the bug will do.
And please, step-by-step workflow to reproduce (since I couldn't reproduce with my workflow)

**Comment by DelazJ** [comment]
Will do. Thanks

**Comment by gioman** [comment]
Closing for lack of feedback.
