### ISSUE TITLE
Crash in categorized symbology dialog

### ISSUE THREAD

**Issue by gbyrom** [qgis/QGIS#31546]
## User Feedback

Creating a symbol categorization using layer properties > symbology > Categorized

## Report Details

*Crash ID*: 41a8c9d81e6beec97349c603af141574ac9038e3

*Stack Trace*
<pre>
QAbstractItemModelPrivate::removePersistentIndexData :
QPersistentModelIndex::~QPersistentModelIndex :
QList<QItemSelectionRange>::dealloc :
QItemSelectionModel::~QItemSelectionModel :
QItemSelectionModel::`default constructor closure' :
QObject::~QObject :
QAbstractItemView::~QAbstractItemView :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
QgsPalettedRendererWidget::~QgsPalettedRendererWidget :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
QgsRasterBandComboBox::`default constructor closure' :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
QStackedWidget::~QStackedWidget :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
QgsDialog::`default constructor closure' :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
QgsGraduatedSymbolRendererWidget::~QgsGraduatedSymbolRendererWidget :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
QgsRasterHistogramWidget::~QgsRasterHistogramWidget :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
QgsRasterBandComboBox::`default constructor closure' :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
QgsRasterHistogramWidget::~QgsRasterHistogramWidget :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
QgsMeshRendererVectorSettingsWidget::`default constructor closure' :
QgsVectorLayerProperties::updateSymbologyPage :
QgsVectorLayerProperties::syncToLayer :
QgsVectorLayerProperties::onCancel :
QMetaObject::activate :
QDialog::done :
QMetaObject::activate :
QDialogButtonBox::~QDialogButtonBox :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
QgisApp::showLayerProperties :
QgisApp::layerTreeViewDoubleClicked :
QMetaObject::activate :
QAbstractItemView::doubleClicked :
QTreeView::mouseDoubleClickEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.4.11-Madeira
QGIS code revision: 9a8a6d4687
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment]
Please try with a new/clean QGIS profile. If the crash persist then attach sample data and exact steps to replicate.

**Comment by gioman** [comment]
Closing for the lack of feedback.
