### ISSUE TITLE
Translate (Convert Format) produces a blank image

### ISSUE THREAD

**Issue by jorgepsantos2002** [qgis/QGIS#31544]
When I trying to convert a Landsat-8 imagery from UInt16 (Unsigned Integer 16 Bit) to Byte (Unsigned Integer 8 Bit), the algorithm produces a blank image.

This video shows the issue: 
https://drive.google.com/file/d/1MnEaYDVF4b4363RTN05ZLsNb4UyHj-aT/view?usp=sharing

**Another question:** I was unable to include the parameter **-scale** to stretch data correcty as I do via GDAL command prompt

QGIS version 3.4.11 64 Bit, Operational System Windows 10 Pro.

**Comment by gioman** [comment]
@jorgepsantos2002 regarding GDAL/OGR tools QGIS is "just" an interface for those command line tools. So you must try from the command line (use the OSGeo shell that comes with any QGIS installation) the command that QGIS buillds (in your video at 00:39, in the "chamada da consola gdal/ogr" at the bottom of the dialog. If you get the same results then is NOT a QGIS issue. 

If the "scale" parameter is not available in the QGIS GUI, then we could add it. Please file a feature request.

**Comment by jorgepsantos2002** [comment]
Hi Giovanni, thanks for your response. This algorithm works in QGIS 2.18, GDAL, OSGeo4W Shell and yes, the -scale parameter must be used to stretch data correctly. We cannot edit GDAL commands anymore, so the user will not able to do this step in QGIS 3 interface.

Sorry, but in my opinion, the process resulting a blank image is a bug. I follow your advise and ran this process in command line interface:

https://drive.google.com/file/d/1WUB1tqvMfrPbyCYmLGTVymVzZfU0uJns/view?usp=sharing

Thank you for the help!

**Comment by gioman** [comment]
> This algorithm works in QGIS 2.18

QGIS 2.18 shipped with a completely different version of GDAL, it is something we cannot rule out.



> and yes, the -scale parameter must be used to stretch data correctly

file a feature request asking to add this parameter.



> Sorry, but in my opinion, the process resulting a blank image is a bug. I follow your advise and ran this process in command line interface:
> 
> https://drive.google.com/file/d/1WUB1tqvMfrPbyCYmLGTVymVzZfU0uJns/view?usp=sharing

it is very unlikely (not impossible) to be a QGIS problem. QGIS/Processing "just" builds a (GDAL) command and runs it.

In the OSGeo Shell (the one shipped with your QGIS 3.4.11 installation, not one from another installation) you must run the same command QGIS builds in your first screencast. In the secondo screencast the command you write in the shell is not identical.

Also it would be much more better if you could attach a sample input.

cheers!

**Comment by jorgepsantos2002** [comment]
Sorry Giovanni, but the error persists if I copy/paste QGIS command in OSGeo4W Shell and run it.

Landsat imagery that I used:
https://drive.google.com/file/d/1mGJltIPkwiik1Kwh-NAXa4p4mV7mPN33/view?usp=sharing

Screencast:
https://drive.google.com/file/d/1jjWTvLfdfKySlCAMbpXAFTUewWcrESaj/view?usp=sharing

Jorge Santos

**Comment by gioman** [comment]
> Sorry Giovanni, but the error persists if I copy/paste QGIS command in OSGeo4W Shell and run it.


Olá Jorge,
actually you just confirmed my point: you took one gdal command as built with the QGIS gui and run it in the CLI, and you got the same identical result (as expected), there is no issue here in QGIS. For you specific operation you really need the "-scale" parameter, without it GDAL (not QGIS) will give the pixels all the same value.

For that: https://github.com/qgis/QGIS/pull/31602

**Comment by jorgepsantos2002** [comment]
Thanks Giovanni for you time! My goal is transform 16bit to 8bit via QGIS GUI but I can run this process via CLI with pure GDAL or OSGeo4W application. Now I understand that this is a GDAL mandatory parameter to rescale data, not a QGIS issue.

**Comment by alexbruy** [comment]
There is an optional "Additional command-line parameters" parameter in all GDAL algorithms, you can enter any and all missed parameters here. I suggest to close this ticket (and similar tickets in future)

**Comment by gioman** [comment]
> There is an optional "Additional command-line parameters" parameter in all GDAL algorithms, you can enter any and all missed parameters here. I suggest to close this ticket (and similar tickets in future)

@alexbruy Hi Alex, isn't that only for "layer creation options" (-lco)?

**Comment by alexbruy** [comment]
No. I have added parameter to all GDAL tools exactly for passing options not exposed in the UI (like this one and in #31692). There is "Additional creation options" parameter for `-lco` and "Additional command-line parameters" for passing command line arguments.

**Comment by jorgepsantos2002** [comment]
> There is "Additional creation options" parameter for -lco

Unfortunately, in Translate window, I cannot find this option, but If I run another algorithm such gdal_contour, this option is there.

**Comment by alexbruy** [comment]
> > There is "Additional creation options" parameter for -lco
> 
> Unfortunately, in Translate window, I cannot find this option, but If I run another algorithm such gdal_contour, this option is there.

I clearly see it on your video.

**Comment by roya0045** [comment]
> > > There is "Additional creation options" parameter for -lco
> > 
> > 
> > Unfortunately, in Translate window, I cannot find this option, but If I run another algorithm such gdal_contour, this option is there.
> 
> I clearly see it on your video.

I think this is why it can be better to have dedicated parameters for such things.

**Comment by jorgepsantos2002** [comment]
> I clearly see it on your video.

Yes you're right!  I can see the **"Additional creation options"**

but I need of  **"Additional command-line parameters"** in Translate (Convert Format) to insert a plain text **-scale** that work with Byte Data Type.

Without this, it's not possible to convert Data Type via QGIS GUI.

**Comment by alexbruy** [comment]
"Additional command-line parameters" were introduced in QGIS 3.8 and as this was a new feature it was not backported to 3.4. Upgrade to 3.8 or wait for 3.10 LTR.

**Comment by gioman** [comment]
@alexbruy I think we can close this an https://github.com/qgis/QGIS/pull/31602 agree?

**Comment by alexbruy** [comment]
@gioman my reference would be to close, but if you (and others) think it is better to have a separate parameter, then let me know and I will add test to your PR and merge it

**Comment by gioman** [comment]
I don't have a strong opinion, I was just really stuck in the past (thinking that it was only possible to add gdal layer creation options).

**Comment by roya0045** [comment]
I still think that for less technical users having some options explicitly exposed is a good thing while that additional commands should mostly be used to tweak some thing that are less frequently used. Or for users that don't want or can't look up the doc of the command to check all possible parameters.

And also the work is already done, this shouldn't clutter the UI or degrade UX in my opinion.

**Comment by alexbruy** [comment]
Closed as there is an "Additional command-line parameters" for this
