### ISSUE TITLE
Map grid properties X and Y look disaligned

### ISSUE THREAD

**Issue by SrNetoChan** [qgis/QGIS#31555]
**Describe the bug**

In the map grids properties, the X and Y interval fields are not aligned with the rest.

![image](https://user-images.githubusercontent.com/3607161/64298856-dba6ba80-cf6e-11e9-9dee-cb39a7ef5ab1.png)

**How to Reproduce**

**QGIS and OS versions**

QGIS version | 3.9.0-Master | QGIS code revision | e21ff39ea5
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.6.2-CAPI-1.10.2 4d2925d6
PostgreSQL Client Version | 11.5 (Ubuntu 11.5-1.pgdg18.04+1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Ubuntu 18.04.3 LTS |   |  

**Additional context**

**Comment by nyalldawson** [comment]
This is by design - it's following the pattern used elsewhere to reflect that these values apply to the "interval" setting above them

**Comment by SrNetoChan** [comment]
IMHO, it looks weird.

**Comment by nyalldawson** [comment]
Maybe we should increase the padding to make it more obvious?
