### ISSUE TITLE
Running processing script with an external import crashes QGIS on macOS 

### ISSUE THREAD

**Issue by lcoandrade** [qgis/QGIS#31557]
I've made a processing script to perform K-Means classification using sklearn. I've installed it normally using `pip install scikit-learn`.

When I run the script on my MacBook Pro, QGIS crashes. After the crash, when I restart QGIS, the processing plugin is disabled. When I activate it, several instances of QGIS start to pop up one after other no stop.

When I use the scrip on my Kubuntu at work it works perfectly.

**Steps to reproduce:**
1 - run the script
2 - restart QGIS
3 - re-activate the processing plugin

**Info:**
OS: macOS 10.14.6
Python: 3.6.8
QGIS version | 3.4.7-Madeira | QGIS code branch | Release 3.4
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.1-CAPI-1.11.0 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
PostgreSQL Client Version | 9.6.10 | SpatiaLite Version | 4.4.0-RC1
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 5.2.0 | Running against PROJ | 5.2.0

**Script and test image to reproduce the steps:**
(https://github.com/qgis/QGIS/files/3576981/script.and.test.image.zip)

**Comment by gioman** [comment]
I don't have a mac to test this, hopefully someone else will step in.

**Comment by lcoandrade** [comment]
Here is the detailed problem:
`Thread 14 Crashed:: Thread (pooled)
0   libopenblasp-r0.3.5.dev.dylib 	0x000000014f2f77d0 dgemm_thread_tt + 1728
1   libopenblasp-r0.3.5.dev.dylib 	0x000000014f1c3bff cblas_dgemm + 783
2   _multiarray_umath.cpython-36m-darwin.so	0x000000014f02d1d7 cblas_matrixproduct + 4567
3   _multiarray_umath.cpython-36m-darwin.so	0x000000014ef36e55 PyArray_MatrixProduct2 + 229
4   _multiarray_umath.cpython-36m-darwin.so	0x000000014ef4210f array_matrixproduct + 191
5   org.python.python             	0x0000000148456697 _PyCFunction_FastCallDict + 183
6   org.python.python             	0x00000001484d8747 call_function + 439
7   org.python.python             	0x00000001484d4eb7 _PyEval_EvalFrameDefault + 27559
8   org.python.python             	0x00000001484d91af _PyEval_EvalCodeWithName + 2447
9   org.python.python             	0x00000001484d9ae1 fast_function + 545
10  org.python.python             	0x00000001484d8721 call_function + 401
11  org.python.python             	0x00000001484d4f56 _PyEval_EvalFrameDefault + 27718
12  org.python.python             	0x00000001484d91af _PyEval_EvalCodeWithName + 2447
13  org.python.python             	0x00000001484d9ae1 fast_function + 545
14  org.python.python             	0x00000001484d8721 call_function + 401
15  org.python.python             	0x00000001484d4f56 _PyEval_EvalFrameDefault + 27718
16  org.python.python             	0x00000001484d91af _PyEval_EvalCodeWithName + 2447
17  org.python.python             	0x00000001484d9ae1 fast_function + 545
18  org.python.python             	0x00000001484d8721 call_function + 401
19  org.python.python             	0x00000001484d4f56 _PyEval_EvalFrameDefault + 27718
20  org.python.python             	0x00000001484d91af _PyEval_EvalCodeWithName + 2447
21  org.python.python             	0x00000001484d9ae1 fast_function + 545
22  org.python.python             	0x00000001484d8721 call_function + 401
23  org.python.python             	0x00000001484d4f56 _PyEval_EvalFrameDefault + 27718
24  org.python.python             	0x00000001484d91af _PyEval_EvalCodeWithName + 2447
25  org.python.python             	0x00000001484d9ae1 fast_function + 545
26  org.python.python             	0x00000001484d8721 call_function + 401
27  org.python.python             	0x00000001484d4f56 _PyEval_EvalFrameDefault + 27718
28  org.python.python             	0x00000001484d91af _PyEval_EvalCodeWithName + 2447
29  org.python.python             	0x00000001484d9ae1 fast_function + 545
30  org.python.python             	0x00000001484d8721 call_function + 401
31  org.python.python             	0x00000001484d4f56 _PyEval_EvalFrameDefault + 27718
32  org.python.python             	0x00000001484d91af _PyEval_EvalCodeWithName + 2447
33  org.python.python             	0x00000001484d9ae1 fast_function + 545
34  org.python.python             	0x00000001484d8721 call_function + 401
35  org.python.python             	0x00000001484d4eb7 _PyEval_EvalFrameDefault + 27559
36  org.python.python             	0x00000001484d9a3d fast_function + 381
37  org.python.python             	0x00000001484d8721 call_function + 401
38  org.python.python             	0x00000001484d4eb7 _PyEval_EvalFrameDefault + 27559
39  org.python.python             	0x00000001484d9c5c _PyFunction_FastCallDict + 348
40  org.python.python             	0x000000014840d6b7 _PyObject_FastCallDict + 247
41  org.python.python             	0x000000014840d7d5 _PyObject_Call_Prepend + 149
42  org.python.python             	0x000000014840d4f0 PyObject_Call + 96
43  sip.so                        	0x0000000148c222ad call_method + 85
44  sip.so                        	0x0000000148c1e166 sip_api_call_method + 148
45  _core.so                      	0x000000014b079105 sipVH__core_287(PyGILState_STATE, void (*)(_sipSimpleWrapper*, PyGILState_STATE), _sipSimpleWrapper*, _object*, QMap<QString, QVariant> const&, QgsProcessingContext&, QgsProcessingFeedback*) + 170
46  _core.so                      	0x000000014b545340 sipQgsProcessingAlgorithm::processAlgorithm(QMap<QString, QVariant> const&, QgsProcessingContext&, QgsProcessingFeedback*) + 126
47  org.qgis.qgis3_core           	0x000000010db6de36 QgsProcessingAlgorithm::runPrepared(QMap<QString, QVariant> const&, QgsProcessingContext&, QgsProcessingFeedback*) + 170
48  org.qgis.qgis3_core           	0x000000010db70fee QgsProcessingAlgRunnerTask::run() + 198
49  _core.so                      	0x000000014b25788b sipQgsProcessingAlgRunnerTask::run() + 101
50  org.qgis.qgis3_core           	0x000000010de1e434 QgsTask::start() + 100
51  org.qt-project.QtCore         	0x000000011516168e 0x11513c000 + 153230
52  org.qt-project.QtCore         	0x0000000115169e87 0x11513c000 + 188039
53  libsystem_pthread.dylib       	0x00007fff6d3932eb _pthread_body + 126
54  libsystem_pthread.dylib       	0x00007fff6d396249 _pthread_start + 66
55  libsystem_pthread.dylib       	0x00007fff6d39240d thread_start + 13`

This problem is related to QgsTask::start() created by  QgsProcessingAlgRunnerTask::run()

Summary:
`Logical CPU:     0
Error Code:      0x00000006
Trap Number:     14
`

**Comment by alexbruy** [comment]
Still true with 3.10/master?

**Comment by gioman** [comment]
> Still true with 3.10/master?

@lcoandrade closing for lack of feedback please reopen if necessary.
