### ISSUE TITLE
QgsSingleBandPseudoColorRenderer.setBand() crashed QGIS

### ISSUE THREAD

**Issue by jakimowb** [qgis/QGIS#31568]
**Problem**

The QgsSingleBandPseudoColorRenderer.setBand() crashes QGIS.

**How to get the error**

![image](https://user-images.githubusercontent.com/1404870/64318378-3285b180-cfba-11e9-8ef6-f147d2eb2036.png)

Let `layer` be a QgsRasterLayer with 3 bands and a QgsSingleBandPseudoColorRenderer on the first band. The following python lines crashed QGIS, at least on my windows plattform (all plugins disabled, new user profile):

```
assert isinstance(layer, QgsRasterLayer)
assert layer.bandCount() > 1
renderer = layer.renderer()
assert renderer.band() == 1
assert isinstance(renderer, QgsSingleBandPseudoColorRenderer)

# clone the render
newRenderer = renderer.clone()
newRenderer.setBand(2)
layer.setRenderer(newRenderer)
```

A QGIS Project file + python script is appended
[QgsSingleBandPseudoColorRendererCrash.zip](https://github.com/qgis/QGIS/files/3577830/QgsSingleBandPseudoColorRendererCrash.zip)

**Stack Trace**

```
QgsSingleBandPseudoColorRenderer::setBand :
PyInit__core :
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyImport_Import :
PyImport_Import :
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_sip :
PyInit_Qsci :
QWidget::event :
QFrame::event :
QAbstractScrollArea::event :
PyInit_Qsci :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processKeyEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.8.2-Zanzibar
QGIS code revision: 4470baa1a3
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by nirvn** [comment]
@jakimowb , when cloning raster renderers, you still need to manually set a raster interface input for the renderer to use via clonedRenderer.setInput(...)

That said, QGIS shouldn't crash. That'll be fixed in the next point release.
