### ISSUE TITLE
UI: Symbol editor window too small for graduated layers

### ISSUE THREAD

**Issue by Komzpa** [qgis/QGIS#31578]
I created graduated layer, and now want to remove outline. I have to click on Symbol. It opens a window. Window is too small to show all the contents:

![image](https://user-images.githubusercontent.com/810638/64351260-aba8f700-d002-11e9-943c-29a911e6908b.png)

I'd like to see "no outline" option right away. 

However, I remember that I can click "Simple fill" and it will let me select "no outline". I click it and it does not show it.

![image](https://user-images.githubusercontent.com/810638/64351040-510f9b00-d002-11e9-8193-b78a032c7a71.png)

I am frightened, but somehow remember that I can scroll. I scroll past the useless color selector (it's reset via graduated color setter) and finally set "no pen".

![image](https://user-images.githubusercontent.com/810638/64351515-1e19d700-d003-11e9-8ec1-b98c78f0b0f5.png)

I press ok, move mouse, press ok.

**Comment by NathanW2** [comment]
OK so we can adjust the dialog here to be a better height however the generally preferred method to style layers is via the style dock (F7 - maybe this is still not clear to users it exists). Which will embed the selector in the panel and allow for better workflows:

![image](https://user-images.githubusercontent.com/381660/64391439-08042900-d08c-11e9-849f-cf06ed4e3e65.png)


![image](https://user-images.githubusercontent.com/381660/64391443-0c304680-d08c-11e9-98c9-2368d4543fad.png)

I tend to push people away from styling layers using the old layer properties dialog as the experience is not as streamlined as the style dock.

**Comment by Komzpa** [comment]
I am afraid the Layer Styling panel is really unusable on laptop screen.
![image](https://user-images.githubusercontent.com/810638/64420904-06952980-d0a9-11e9-9710-ccf016ffce23.png)

What can be done about it is that properties can open this panel in floating non-blocking mode, with right size, and pretend it's properties window:

![image](https://user-images.githubusercontent.com/810638/64421029-4825d480-d0a9-11e9-9ca8-53e3291ea442.png)

Another thing is that however large I make this window the "symmetric classification" text is clipped.

**Comment by nirvn** [comment]
@Komzpa , embed your panels into a group of panels with tabs to switch from one panel to the other, that'll give you plenty of vertical space.

**Comment by DelazJ** [comment]
> I am frightened, but somehow remember that I can scroll. I scroll past the useless color selector (it's reset via graduated color setter) and finally set "no pen".

@Komzpa Why don't use instead enlarge the dialog, taking it from the corners? Also this dialog remembers the last geometry, so if not resized, you'll get the same inappropriate size at each opening. And can you indicate the version you are using, please?

**Comment by Komzpa** [comment]
@nirvn I don't do very non-default setups because I have to show people in my team how to do something.

@DelazJ I don't enlarge dialog as it requires precise aiming of the mouse. I also don't really want to resize it on every machine I come across.

**Comment by nirvn** [comment]
@Komzpa , a better default size for the symbol selector dialog has been committed and will be available in the next point releases in less than 10 days (LTR 3.4.12, and latest 3.8.3).

**Comment by Komzpa** [comment]
@nirvn Thank you!
