### ISSUE TITLE
UI: Filter is not part of properties?

### ISSUE THREAD

**Issue by Komzpa** [qgis/QGIS#31580]
I added my layer to QGIS. I am changing everything about its styles and how to colorize and label what in right-click - properties. 
![image](https://user-images.githubusercontent.com/810638/64360981-4a8a1f00-d014-11e9-911b-dad04d79ff0c.png)

![image](https://user-images.githubusercontent.com/810638/64361038-67265700-d014-11e9-8bcb-fed696ebdb8f.png)

At some point I decide I don't need some of the features. I'd like to filter them out. I can go to first tab and see the filter:

![image](https://user-images.githubusercontent.com/810638/64361068-773e3680-d014-11e9-8277-9590a633c0a0.png)

But I can't right click the layer again - the window is modal - and open the filter window.

![image](https://user-images.githubusercontent.com/810638/64361470-4ad6ea00-d015-11e9-9a22-25412d2c5f3e.png)

(note the yellow-on-yellow column names that are not really readable)

What if that window was just one of the tabs of Properties? Then I can switch there right away.

**Comment by suricactus** [comment]
This is possible by going to the source tab and clicking on the "Query Builder" button on the bottom right.
![image](https://user-images.githubusercontent.com/2820439/77786887-4f252c00-7067-11ea-9b97-84d6fc3e7880.png)

**Comment by pathmapper** [comment]
> This is possible by going to the source tab and clicking on the "Query Builder" button on the bottom right.

Yep, looks like this issue can be closed.
