### ISSUE TITLE
Expressions: LIKE operator is slow

### ISSUE THREAD

**Issue by wonder-sk** [qgis/QGIS#31594]
QGIS rendering may get quite slow with the use of expressions using LIKE. 

Internally expressions use QRegExp when evaluating LIKE - this class has now a replacement in Qt5 - QRegularExpression. The new class has better API (easier to cache the engine for the regexp) and also a faster engine (based on PCRE library instead of custom one implemented within Qt). It looks like we need to switch to the new class + add caching of the regexp instance where possible (when the right side is a literal string).

Some platforms seem to be more prone to the slowness - e.g. iOS - see https://github.com/lutraconsulting/input/issues/433

**Comment by roya0045** [comment]
Is this on anyone's radar? I can try to cook up something.

**Comment by nyalldawson** [comment]
This is fixed now -- everything in core is migrated to QRegularExpression
