### ISSUE TITLE
deselect features of the active layer

### ISSUE THREAD

**Issue by j-lippmann** [qgis/QGIS#31598]
hello,

it would be useful, if i could deselect features of the active layer (with an new button in the select menu?). at the moment i can do this only if i open the attributetable and click the deselect button. this is not a short way and for large tables painful.

and additional it would be cool if the select menu (from edit menu) also available in the layer contextmenu (right mouseclick). this is little bit inspired from A**GIS ;-)

i hope someone can implement this !? :-)

thank you very much

**Comment by alexbruy** [comment]
Closing as #31563 was merged

**Comment by j-lippmann** [comment]
Hi @alexbruy Why you closed this issue? The Pull Request #31563 is for reselect Not for deselect! Or i' m wrong?

**Comment by andreasneumann** [comment]
@j-lippmann - do you really need this on a "per layer" base?

There is a "Deselect in all layers" button as shown below.
![image](https://user-images.githubusercontent.com/884476/64730169-fe8d1d80-d4de-11e9-978e-8a22fa446805.png)

Would this not work in your scenario?

**Comment by j-lippmann** [comment]
Hi @andreasneumann i know the deselect of all Layers...heavy in use... but often i destroy the Selection of Layers which  needed for processing algs.  And Why we Cam have a deselect for Active  Layer without Open the Attribute table? Large Tables can be painful!

**Comment by andreasneumann** [comment]
@j-lippmann no problem. I agree that it might be useful to have this "deselect" on the active layer only. Just wanted to double check if the already existing functionality of deselect in all layers doesn't work for you.

It is probably easy to implement. But for 3.10, this feature request is too late. We are already in feature freeze mode. For 3.12 it should be possible. I reopen this feature request as I think that @alexbruy closed this by accident.

**Comment by j-lippmann** [comment]
@andreasneumann thanks for reopen!

**Comment by alexbruy** [comment]
@j-lippmann sorry, I was confused with a PR with similar title and the fact that is linked to this issue.
