### ISSUE TITLE
cannot make qgis.db a private copy-error msg

### ISSUE THREAD

**Issue by GeorgeJones92** [qgis/QGIS#31596]
Hi all, 
I keep running across the same issue when trying to open QGIS 3.4.4. It says ' cannot make qgis.db  private copy' then crashes. Any advice? I've copied this QGIS instance from a DVD into a local file where I can open it up. 

thanks George

**Comment by roya0045** [comment]
> I've copied this QGIS instance from a DVD into a local file where I can open it up.

What version are you using and what do you mean by this?

**Comment by nirvn** [comment]
> I've copied this QGIS instance from a DVD into a local file...

I'm not sure what that means, but it sounds like a recipe for disaster :wink: you should definitively add QGIS onto your local system via a proper installation procedure (standalone installer or osgeo4win installer).

That said, this specific crash has been addressed, grab the latest LTS point release (3.4.11), you'll be crash free.
