### ISSUE TITLE
QGIS Server issue under WIndows

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#31606]
I'm really not sure how to tackle this report, the issues are probably more than one and so this would need to be split, I kindly ask you to help me pinpoint them.

1) the installation instructions in the manual https://docs.qgis.org/3.4/en/docs/user_manual/working_with_ogc/server/getting_started.html#installation-on-windows maybe used to work, but they don't do anymore. If you follow them (use the xampp installer for Apache) you get a not working installation of QGIS Server. The returned error is like

 `end of script output before headers `

which is the same you get when you install QGIS Server on linux and you don't have the fcgi Apache module installed. In fact the xampp installer do not have such module in its installation of Apache.

2) There are alternative installation paths, like for example:

https://opengislab.com/blog/2018/7/7/updated-installing-apache-qgis-server-and-lizmap-on-windows-os

this tutorial was written for QGIS Server 2.18, and if you install this version with OSGeo4W it all works ok (more or less, because QGIS Server 2.18 on Windows had its own share of issues).

On the other end, if the tutorial is adapted for QGIS Server 3.4 the result is dead end.

Firstly when trying to check if QGIS Server works testing

`http://localhost/qgis/qgis_mapserv.fcgi.exe`

it starts to spit out errors about missing **qt5*** libraries.

So I went to check were the equivalent qt4 libraries are in a OSGeo4W installations, and t turns are in **C:\OSGeo4W64\bin** while the qt5 ones are only in **C:\OSGeo4W64\apps\Qt5\bin**. So I copied them into "C:\OSGeo4W64\bin" (without knowing exactly what I was doing, of course) and the errors went away.

But then the roadblock: trying a real GetCapabilities request:

`<ServerException>Layer(s) not valid</ServerException>`

in the log messages like:

```
17:01:55 INFO Server[2860]: ******************** New request ***************
17:01:55 INFO Server[2860]: SERVER_NAMElocalhost
17:01:55 INFO Server[2860]: REQUEST_URI/qgis/qgis_mapserv.fcgi.exe?map=C:/Users/qgis/Desktop/test/test_proj.qgs&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities
17:01:55 INFO Server[2860]: REMOTE_ADDR::1
17:01:55 INFO Server[2860]: HTTP_USER_AGENTMozilla/5.0 (Windows NT 6.1; WOW64; rv:56.0) Gecko/20100101 Firefox/56.0
17:01:55 INFO Server[2860]: MAP:C:/Users/qgis/Desktop/test/test_proj.qgs
17:01:55 INFO Server[2860]: REQUEST:GetCapabilities
17:01:55 INFO Server[2860]: SERVICE:WMS
17:01:55 INFO Server[2860]: VERSION:1.3.0
17:01:55 WARNING [2860]: Invalid data provider ogr
17:01:55 CRITICAL Server[2860]: Layer(s) test_46969f5c_959b_4867_b820_10ae141699ec not valid
17:01:55 INFO Server[2860]: Request finished in 31 ms
```

I'm doing something wrong? there are real issues? thanks for any hint and feel free to close if this completely wrong @jef-n @rldhont

**Comment by gioman** [comment]
There seems to be a recipe to get QGIS Server going on Windows after all. I will try to document it.

**Comment by sweco-dkjesh** [comment]
I have experienced the same issue (<ServerException>Layer(s) not valid</ServerException> from getCapabilities). 
Can you please link to where you placed the recipe to fix it?
