### ISSUE TITLE
Trim/Extend tool isn't working on macOS

### ISSUE THREAD

**Issue by M-Rick** [qgis/QGIS#31604]
The Trim/Extend tool isn't working at all. It has never worked in MacOS X version.

When activated, the cursor should highlight the line to be trimed, but nothing happens.
No problem under Windows or Linux.
In this video the behaviour it should have is shown and nothing of this can be  #done.
https://vimeo.com/306907902

**Comment by lbartoletti** [comment]
@M-Rick I tested on macOS Mojave with QGIS 3.6 and it works.

Maybe, you forgot to activate segment snapping? https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/editing_geometry_attributes.html#trim-extend-feature

**Comment by gioman** [comment]
Closing for lack of feedback.
