### ISSUE TITLE
WFS URL causes QGIS to crash

### ISSUE THREAD

**Issue by palmerj** [qgis/QGIS#31607]
- [x] Search through existing issue reports and gis.stackexchange.com to check whether the issue already exists
- [x] Test with a [clean new user profile](https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html?highlight=profile#working-with-user-profiles).
- [ ] Create a light and self-contained sample dataset and project file which demonstrates the issue

**Describe the bug**
When adding this URL http://opendata.ccc.govt.nz/CCCSearch/ogc/SuggestAddress/wfsg via the WFS new connection within the Browser causes QGIS crashes. 

**How to Reproduce**

When adding this URL http://opendata.ccc.govt.nz/CCCSearch/ogc/SuggestAddress/wfsg via the WFS new connection within the Browser causes QGIS crashes. . When I load QGIS again the WFS endpoint node still exists, but when I expand the node QGIS crashes again.

**QGIS and OS versions**

QGIS version | 3.8.2-Zanzibar | QGIS code revision | 4470baa1a3
-- | -- | -- | --
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS Mojave (10.14) |   |

**Comment by palmerj** [comment]
This service is the same https://opendata.ccc.govt.nz/Address/service.svc/get?request=GetCapabilities&SERVICE=WFS

**Comment by gioman** [comment]
Confirmed also on master/ubuntu.

**Comment by palmerj** [comment]
wow thanks!
