### ISSUE TITLE
Crash ID hyperlink is not clickable by default

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#31629]
because instead of `[b2e8752cd39468b3be83e51f1c34e92bfdd48cc3](https://github.com/qgis/QGIS/search?q=b2e8752cd39468b3be83e51f1c34e92bfdd48cc3&type=Issues)` it returns `[b2e8752cd39468b3be83e51f1c34e92bfdd48cc3]('https://github.com/qgis/QGIS/search?q=b2e8752cd39468b3be83e51f1c34e92bfdd48cc3&type=Issues')` (note the quote around the link)

**Comment by DelazJ** [comment]
@Gustry The issue here does not seem to be fixed afaict. Pasting crash report to github still keeps the single quote.

**Comment by Gustry** [comment]
I'm sorry, I couldn't try as I'm not using Windows and I don't know how to trigger the crash dialog. I just tried to improve this blindly ;-) I will try again later.

Maybe @NathanW2 might have a look?
