### ISSUE TITLE
UI: Spurios "method" in colorization options

### ISSUE THREAD

**Issue by Komzpa** [qgis/QGIS#31638]
There is a multi-select called "method". It only selects "Color". It shouldn't even be.

![image](https://user-images.githubusercontent.com/810638/64533327-e28d4e80-d31b-11e9-81a5-00681cd8653d.png)

**Comment by DelazJ** [comment]
When you are using a point/line layer, it also shows "Size". Maybe should the widgets be grayed...

**Comment by Komzpa** [comment]
There is no way to simply change a layer from polygon to point/line. A thing that you can't do anything with shouldn't be there.

**Comment by Komzpa** [comment]
@nyalldawson I see https://github.com/qgis/QGIS/pull/31700 merged - this one can be closed, or something else left?

**Comment by nirvn** [comment]
All good, this can be closed.
