### ISSUE TITLE
Galician language missing from 3.8.2 GUI

### ISSUE THREAD

**Issue by gallaecia** [qgis/QGIS#31632]
Hi,
after updating to 3.8.2, galician language has disappeared from GUI. This behaviour does not occurs on 3.4 or master. Tested on Ubuntu. 
Thanks.

**Comment by jef-n** [comment]
fixed in df73de2bb82a998f476edb613e74a280f51bddfb

**Comment by gallaecia** [comment]
Thanks.

O 14:14, Ven., 13 de set. de 2019, Jürgen Fischer <notifications@github.com>
escribiu:
