### ISSUE TITLE
UI: any click on number of classes updown triggers twice

### ISSUE THREAD

**Issue by Komzpa** [qgis/QGIS#31635]
In layer properties, whenever I click on the number of classes updown, it gets changed (slowly recalculates), and repeats the action after first recalculation gets finished. Very annoying on slow coloring modes like Quantiles.

![image](https://user-images.githubusercontent.com/810638/64531868-0ac77e00-d319-11e9-967a-4828ae1f4f5b.png)

**Comment by elpaso** [comment]
How do you know that the action is actually triggered twice?
My debugger stopped only once in the renderer.

**Comment by Komzpa** [comment]
Here's video:
https://youtu.be/FGNnkFOt9qg

I click once, it adds one, redoes classes, adds one, redoes classes. Same with decrement.

**Comment by elpaso** [comment]
Oh, I see, So you clicked once and it got decremented twice (from 5 to 3), I cannot reproduce it on Linux, I'll check on windows.

**Comment by Komzpa** [comment]
I have also seen this on Linux. This seems to be happening to me mostly on Quantile graduated ramps. I suspect it may be connected somehow with time it takes to recalculate it, but have no proofs.

**Comment by elpaso** [comment]
Does it happen all the times with a particular project? 
If yes, may I ask you to share a project where I can reproduce the issue?

**Comment by Komzpa** [comment]
It happens all the time on large datasets, which I store in PostGIS. They're large and I'm not immediately sure how to share them to reproduce all of environment, in principle I can.

**Comment by elpaso** [comment]
you can probably just drag and drop the layer into a geopackage and share it (with the associated style).

**Comment by Komzpa** [comment]
No, I exported trimmed down excerpt into geopackage and issue won't reproduce there. Seems it's connected to PostGIS, either being slower or in implementation.

**Comment by elpaso** [comment]
`pg_dump` then. If I cannot reproduce it I cannot even try to fix it, and this issue seems dependent on the project + the style.

**Comment by Komzpa** [comment]
@elpaso I was trying to build a datasource for testing but it failed in another way: https://github.com/qgis/QGIS/issues/31799

**Comment by Komzpa** [comment]
It reproduces on this slow view. Try creating it and classifying on "g" field - double updown trigger reproduces will on my side.
```
create table test_table as (select (ST_DumpPoints(ST_GeneratePoints(ST_Expand('SRID=4326;POINT(0 0)'::geometry,90),10))).geom, random());  
create view test_view as (select geom, random+coalesce((0||pg_sleep(0.1)::text)::int,0)  g,0 as id from test_table);
```

**Comment by elpaso** [comment]
I can reproduce this with your last SQL, thank you for providing all required details to reproduce the issue.

**Comment by Komzpa** [comment]
Thanks a lot!
