### ISSUE TITLE
UI: Fast close hotkey from SQL Filter

### ISSUE THREAD

**Issue by Komzpa** [qgis/QGIS#31644]
I open the filter. I want to quickly change a number and be gone. I change it, try Enter, try Ctrl+Enter, nothing works, I go grab my mouse. 
![image](https://user-images.githubusercontent.com/810638/64537024-c3de8600-d322-11e9-8347-104990f68b95.png)

Ctrl+Enter can apply+save.

**Comment by nirvn** [comment]
It's indeed the case that there's no way to use this dialog only with the keyboard as TABing away from the sql edit widget doesn't work (it instead inserts a tab).

**Comment by nirvn** [comment]
Well, well, well, TIL: Alt+O (i.e. the letter O) is the dialog shortcut to apply the filter. Enjoy.

**Comment by Komzpa** [comment]
Thank you!
