### ISSUE TITLE
UI: Invert Ramp does not have tick but Random Ramp has

### ISSUE THREAD

**Issue by Komzpa** [qgis/QGIS#31646]
I keep clicking "Random Ramp" as I expect the option with checkbox to be "Invert ramp". 
![image](https://user-images.githubusercontent.com/810638/64537975-7c58f980-d324-11e9-8f21-6501c0d9cbe7.png)

**Comment by nirvn** [comment]
Invert color ramp isn't a state, it's an action that modifies your ramp. 

Random color ramp is a state, hence the checkbox.

Keep those UI/UX issues coming, just make sure you keep an open mind and be receptive to the idea of understanding why things are the way they are for a reason. :)

**Comment by Komzpa** [comment]
If "invert ramp" is an action, can it be made into a button next to the dropdown? Dropdown will be comprised mostly of preset selection list, and invert will be a distinct action - the mix-up will not happen this way.
