### ISSUE TITLE
A question: where can I submit a ticket for a build issue?

### ISSUE THREAD

**Issue by Sinan81** [qgis/QGIS#31652]
Experiencing problems in building QGIS from source in Linux. I am wondering where I can submit a ticket for this and get help? Thanks.

**Comment by NathanW2** [comment]
The best bet to start is to email the developer mailing list and see if we
can resolve it there.

If it's a bug in the build process then we can open a ticket. A lot of the
times it's a config or environment issue so we should resolve on the
mailing list first if we can.

**Comment by Sinan81** [comment]
ok. thanks.
