### ISSUE TITLE
Attribute Table - Move Selection Top does not work each time

### ISSUE THREAD

**Issue by EmreHepgunes** [qgis/QGIS#31658]
Attribute Table - Move Selection Top does not work each time when pressed the button. Sometimes it works and sometimes it is not. It was working properly in version 2 but in version 3 still the same problem occurs in every new update i have tried.

**Comment by Gustry** [comment]
Duplicate of https://github.com/qgis/QGIS/issues/28914 ?

**Comment by alexbruy** [comment]
Should be fixed in master. Please reopen if necessary.
