### ISSUE TITLE
Unable to add WMS service in QGIS, same URL works in other clients.

### ISSUE THREAD

**Issue by Skiffen** [qgis/QGIS#31661]
**Describe the bug**
Failing to add a WMS service that is accepted in other clients like browsers and ArcGIS software. It seems like a bug with the header as request parameters are kept identical along all clients.
The returned warning shows Service Unavailable, but the same URL is openable in a web browser (Chrome).

**How to Reproduce**
Add the WMS from [1] as a source to the browser in QGIS. From the Images subfolder add meest_recent. Error is shown. 100% reproduction rate.

**QGIS and OS versions**
QGIS 3.4.3.
Windows 7

**Additional context**
[1]: https://luchtfoto.prorail.nl/erdas-iws/ogc/wms/Luchtfoto

**Comment by elpaso** [comment]
The WMS endpoint is defective/misconfigured:

GetCapabilities returns correctly:
https://luchtfoto.prorail.nl/erdas-iws/ogc/wms/Luchtfoto?REQUEST=GetCapabilities&SERVICE=WMS
But the getMap address and all others do not:

```
GET 'https://luchtfoto.prorail.nl:443/erdas-iws/erdas/imagex/Luchtfoto?request=image&type=jpg&layers=/meest_recent/&style=default&sizex=100&sizey=100&SERVICE=WMS&VERSION=1.3.0&SLD_VERSION=1.1.0&FORMAT=image/jpeg&LAYER=meest_recent&TRANSPARENT=true'                                                                                                                                                                                               
<html><body><b>Http/1.1 Service Unavailable</b></body> </html>
```

Notice that the getcapabilities  response adds the (standard) port 443 for HTTPS which is very strange, but event if it's removed, it still fails but with a different error (also strange):

```
GET 'https://luchtfoto.prorail.nl/erdas-iws/erdas/imagex/Luchtfoto?request=image&type=jpg&layers=/meest_recent/&style=default&sizex=100&sizey=100&SERVICE=WMS&VERSION=1.3.0&SLD_VERSION=1.1.0&FORMAT=image/jpeg&LAYER=meest_recent&TRANSPARENT=true'                                                                                                                                                                                               
<?xml version="1.0" encoding="UTF-8" ?>                                                                                                                                                                                                      
<ImageXError version="16.5">                                                                                                                                                                                                                 
 <Error code="InternalError">An error has occurred: Error 2&quot;File open failed&quot;  location &quot;NCS::IWS::ServerDatastore::CServerDatastore::ReparentPath&quot; Unable to open dataset /meest_recent/. Reason: unable to obtain service WMS due to An error has occurred: Error 22&quot;404 Not found&quot;  location &quot;NCS::IWS::ServerDatastore::CServerDatastore::GetService&quot; Service &apos;WMS&apos; is not available</Error>                                        
</ImageXError>
```

Btw, the a.m. calls do also fail in a browser.

**Comment by jef-n** [comment]
You can check "Ignore GetMap/GetTile URI reported in capabilities" in the WMS connection to work around this.

**Comment by ccalvocm** [comment]
Thank you @jef-n this solution works for me
