### ISSUE TITLE
Model Builder- How to refer a "vector field parameter" in "field calculator formula"

### ISSUE THREAD

**Issue by EmreHepgunes** [qgis/QGIS#31660]
In the model builder, i want to link or refer a vector field parameter into the field calculator formula. However, it seems not to be working. Even the "parameter('parameter_name') function does not work. Although searching for the answer for more than 2 years still the problem exists (also for version 2 and version 3).

**Comment by nyalldawson** [comment]
Use the "attribute" function along with parameter.

This isn't a user support site, so if you still hit issues please open a ticket on gis.stackexchange.com.
