### ISSUE TITLE
QGIS Crashed

### ISSUE THREAD

**Issue by Nicko05** [qgis/QGIS#31667]
Regularly crashes after using angle measurement tool !!

**Comment by gioman** [comment]
> Regularly crashes after using angle measurement tool !!

regardless of the project/data? have you tried with a new/clean QGIS profile?
what OS? what QGIS version?

**Comment by Nicko05** [comment]
Hello,

thank's for fast response :)

OS -> win 7
QGIS version -> latest Zanzibar 3.8.2

So I double checked after your questions.
After I open my saved project, it crashes after just one angle measurement!
When I open new clean project without any surface, it crashes again after
just one measurement.


uto, 10. ruj 2019. u 13:03 Giovanni Manghi <notifications@github.com>
napisao je:

**Comment by gioman** [comment]
> So I double checked after your questions. After I open my saved project, it crashes after just one angle measurement! When I open new clean project without any surface, it crashes again after just one measurement.

try again with a new QGIS profile (and do not install any 3rd party plugin).

**Comment by Nicko05** [comment]
I have tried with new clean user profile (with out plugins), and it crashed
again after several attempts of angle measurements !!

It's no big problem for me, I'm still going to use QGIS program, just very
careful :)



uto, 10. ruj 2019. u 13:16 Nikola Pavić <05nikola.pavic@gmail.com> napisao
je:

**Comment by gioman** [comment]
> I have tried with new clean user profile (with out plugins), and it crashed again after several attempts of angle measurements !!

please attach the crash stack trace.

**Comment by Nicko05** [comment]
My computer system is working okay for me (photoshop, power diretor ...
program like that and even gaming like witcher 3).

But definitely QGIS is a bit unstable experience for me, because this is
not only example for crash situation.

Crash ID: 6a074c491858b138cc4e1cb834ca89b91445862c


Stack Trace


QWindow::destroy :
QWindow::event :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processCloseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
TranslateMessageEx :
TranslateMessage :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.8.2-Zanzibar
QGIS code revision: 4470baa1a3
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

uto, 10. ruj 2019. u 13:31 Nikola Pavić <05nikola.pavic@gmail.com> napisao
je:

**Comment by gioman** [comment]
Not enough details to try replicate.
