### ISSUE TITLE
Editing symbology in realtime using the histogram

### ISSUE THREAD

**Issue by UnkzF** [qgis/QGIS#31670]
h2. User Feedback

When doing realtime editing of classes in graduated symbol using the histogram, QGIS crashed.

h2. Report Details

*Crash ID*: 36940ae209be73f72900662a7706848e03c95091

*Stack Trace*
<pre>
QgsGraduatedSymbolRenderer::addBreak :
QgsGraduatedHistogramWidget::mouseRelease :
QMetaObject::activate :
QgsGraduatedHistogramEventFilter::mouseRelease :
QgsGraduatedHistogramEventFilter::eventFilter :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
DispatchMessageW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.4.5-Madeira
QGIS code revision: commit:89ee6f6e23
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.0
Running against GDAL: 2.4.0

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by gioman** [comment]
> When doing realtime editing of classes in graduated symbol using the histogram, QGIS crashed.

does it happens always? regardless of the data? have you tried on a new/clean QGIS profile?

**Comment by alexbruy** [comment]
Closed for the lack of feedback. Please reopen if necessary.
