### ISSUE TITLE
Problem with projection OTF

### ISSUE THREAD

**Issue by saberraz** [qgis/QGIS#31674]
I am trying to set my canvas to EPSG:102038. My shapefile is the world boundaries in EPSG:4326:
https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/50m/cultural/ne_50m_admin_0_countries.zip

This is how it looks like when zoomed out:
![image](https://user-images.githubusercontent.com/2649047/64631742-9c092400-d3ef-11e9-95a9-0d9ed6d3bcc8.png)

It looks fine when zoomed in:
![image](https://user-images.githubusercontent.com/2649047/64631796-bf33d380-d3ef-11e9-8409-b35e9986f824.png)

**Comment by gioman** [comment]
@saberraz duplicate/related to https://github.com/qgis/QGIS/issues/30686 ?

**Comment by saberraz** [comment]
It is indeed.
