### ISSUE TITLE
Map Tip Position / Follow the Hyperlink

### ISSUE THREAD

**Issue by Amphibitus** [qgis/QGIS#31672]
In earlier times (before QGIS 3.8.?) the pop up window position was equal wit the cursor position. So it was possible, to move in the "Pop up Window from the Map Tip" and klick on any Link , to follow the Link.

Now the Left Top Corner Positiop of the Map Tip has been changed. When the User move the Mouspoition,  the Map Tip Popup Window close, an is it not possible to follow the LINK. 

![grafik](https://user-images.githubusercontent.com/7237786/64628259-5baaa580-d3f1-11e9-9adc-c3d4d698a8f2.png)

**Comment by DelazJ** [comment]
See #31311 and #31515
