### ISSUE TITLE
QGIS 3.8.2 Zanibar TIN/IDW Interpolation in Processing Toolbox Crashed QGIS

### ISSUE THREAD

**Issue by lstullwv** [qgis/QGIS#31695]
**Describe the bug**
QGIS crashes when attempting to generate a surface using the TIN Interpolation method as structure lines on contours found within a shapefile. 

**How to Reproduce**
1. Go to Interpolation plugin found within processing toolbox, Select TIN interpolation method
2. Select shapefile having vector contours-->select structure lines, 
3. Establish Extent by shapefile layer extent.
4. Select 200 foot grid spacing
5. Default to temporary output of grid

Crash report:
## User Feedback

I was attempting to create a surface from shapefile contours using the TIN interpolation method for structure lines. QGIS crashed.

## Report Details

*Crash ID*: 185de4a9a11eb29f05672d8b176e731c0d36ee2f

*Stack Trace*
<pre>
MathUtils::lineIntersection :
DualEdgeTriangulation::insertForcedSegment :
DualEdgeTriangulation::addLine :
QgsTinInterpolator::insertData :
QgsTinInterpolator::initialize :
QgsTinInterpolator::interpolatePoint :
PyInit__analysis :
QgsGridFileWriter::writeFile :
PyInit__analysis :
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_sip :
CPLStringList::empty :
PyInit__core :
QgsProcessingAlgorithm::runPrepared :
QgsProcessingAlgRunnerTask::run :
PyInit__core :
QgsTask::start :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS and OS versions**
*QGIS Info*
QGIS Version: 3.8.2-Zanzibar
QGIS code revision: 4470baa1a3
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.16299

**Additional context**

**Comment by alexbruy** [comment]
Duplicates #30549.
