### ISSUE TITLE
3D map in composer crashes QGIS

### ISSUE THREAD

**Issue by WillTaig** [qgis/QGIS#31707]
## User Feedback

When I try to reset 3D maps via the 'Copy settings from a 3D view' button in the print composer Qgis crashes

## Report Details

*Crash ID*: 7a8ff76f6331aaa19304d366766562f4b1ffb938

*Stack Trace*
<pre>
Qt3DRender::Render::NodeManagers::environmentLightManager :
Qt3DRender::Render::QRenderPluginFactoryIf::create :
Qt3DRender::Render::Renderer::submitRenderViews :
Qt3DRender::Render::Renderer::doRender :
Qt3DRender::Render::Renderer::render :
Qt3DRender::Render::AbstractRenderer::~AbstractRenderer :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.8.2-Zanzibar
QGIS code revision: 4470baa1a3
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by nirvn** [comment]
Could you provide more detailed steps to reproduce, alongside a test project that replicates the crash reliably?

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
