### ISSUE TITLE
Rendered Image Algorithm for Processing

### ISSUE THREAD

**Issue by PedroVenancio** [qgis/QGIS#31715]
**Feature description.**

It would be nice to have a Processing Algorithm to export a raster layer as rendered image, just like the Export -> Save As.. -> Rendered Image option.

![rendered_image](https://user-images.githubusercontent.com/1331581/64779501-1f448a00-d556-11e9-88b7-b8214fd8489b.jpg)

Besides the flexibility to run it as batch process, with it in Processing, it would be possible integrate in Models or Scripts.

Thank you very much!

**Comment by root676** [comment]
Isn't this functionality already exposed through the `Convert map to raster` algorithm?

**Comment by PedroVenancio** [comment]
Hi @root676 

Yes, I think `Convert map to raster` can be used to mimetize the export as rendered image! Thanks for pointing it! 

It can be used in conjunction with gdal_translate and gdaladdo to get compression and overviews, and so cover all aspects of save as.

**Comment by AlisterH** [comment]
For the record, if you're trying to actually match the original size and extent you need to:
- select to calculate "minimum extent to render" from the layer
- find out the pixel size of the layer and specify it in "map units per pixel
- select the layer to render
- don't select a map theme to render
