### ISSUE TITLE
Crash deleting vertex, just after deleting a polygon

### ISSUE THREAD

**Issue by noronig** [qgis/QGIS#31714]
Crash ID: 30bbfca863185b3aa8a9a4dd48853ecba50bc799

Stack Trace

QgsVertexTool::~QgsVertexTool :
QgsPointLocator::verticesInRect :
Index::~Index :
Index::~Index :
QgsPointLocator::nearestVertex :
QgsVertexTool::layerVerticesSnappedToPoint :
QgsVertexTool::findCoincidentVertices :
QgsVertexTool::startDraggingMoveVertex :
QgsVertexTool::startDragging :
QgsVertexTool::cadCanvasReleaseEvent :
QgsMapToolAdvancedDigitizing::canvasReleaseEvent :
QgsMapCanvas::mouseReleaseEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
DispatchMessageW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.4.11-Madeira
QGIS code revision: 9a8a6d4687
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by gioman** [comment]
Closing for the lack of feedback.
