### ISSUE TITLE
Legend issue: Subgroup heading does not work

### ISSUE THREAD

**Issue by fjgh77** [qgis/QGIS#31722]
**Describe the bug**
Trying to change the format letter but nothing happens

**How to Reproduce**

**QGIS and OS versions**
3.4 and 3.8

**Additional context**

**Comment by fjgh77** [comment]
Sorry for being unclear. It seems that the option to change the format of the Subgroup heading does not work properly. I have a typical structure of layers in my qgis project (group, subgroup and elements). Here an example: 
Country (Group)
  Region (Subgroup)
      Town1 (element 1)
      Town 2 (element 2)
In the leyend of the map I would like to have different type of letters for the Country, Region and Town. So I am using the available options to change the format: group heading, subgroup heading and element heading. The problem is that when I select a type of format for the Group heading, not only change the Group heading but also the Subgroup heading with that format. When I try to change the format for the Subgroup heading, let me say, bold and cursive, the leyend does not change. It seems that the Group heading option is affecting to the Group and Subgroup heading at the same time, while the option for the Subgroup heading does not work. I have the same problem in both versions QGIS 3.4 and 3.8.
Hope to be  clear enough and thank you in advance for any help.

**Comment by roya0045** [comment]
Yeah  that's because subgroup are not a thing in qgis, there are layers and groups. They are entities and not hierarchies.
To have code that distinguish nesting level would be hard to implement and I doubt there is much demand for such features. 
I understand your need but in this case wouldn't it be simpler to have the layer be the legion label and simply use classification to display the towns. This way all your information would be in a single layer and you could have your tree tiers.

**Comment by fjgh77** [comment]
Thank you for this clarification and the alternative to solve the issue. According to your explanation, what is the sense of the option _Subgroup Headings_ offered to edit the Leyend format?
![image](https://user-images.githubusercontent.com/55246700/64953823-cb9aaf00-d87b-11e9-9d79-2d5bd0c846b4.JPG)

**Comment by roya0045** [comment]
> Thank you for this clarification and the alternative to solve the issue. According to your explanation, what is the sense of the option _Subgroup Headings_ offered to edit the Leyend format?
> ![image](https://user-images.githubusercontent.com/55246700/64953823-cb9aaf00-d87b-11e9-9d79-2d5bd0c846b4.JPG)

Item label should be the symbol label and the subgroup heading is possibly the layer label.
If you have a layer with a classification that has categories, The subgroup heading would become the layer title as it englobe a number of symbology.

I agree that the naming scheme is confusing, maybe @nirvn has a better alternative than "subgroup".

**Comment by nyalldawson** [comment]
Are you aware you can right click entries in the legend item list to promote them to groups or Subgroups?

**Comment by fjgh77** [comment]
Thank you. I was not aware about this option. It works fine and seems to solve the issue.
