### ISSUE TITLE
qgis crashed on close in QSortFilterProxyModel

### ISSUE THREAD

**Issue by Andrea-Zep** [qgis/QGIS#31721]
## User Feedback

Crash

## Report Details

*Crash ID*: 022e9e1e51446f73e4c778e8b0a8199e576d1e48

*Stack Trace*
<pre>
memcpy :
QSortFilterProxyModel::qt_metacast :
QSortFilterProxyModel::removeRows :
QSortFilterProxyModel::sortRole :
QSortFilterProxyModel::`default constructor closure' :
QMetaObject::activate :
QAbstractItemModel::beginRemoveRows :
QgsAttributeTableModel::removeRows :
QgsAttributeTableModel::loadLayer :
QMetaObject::activate :
QMetaObject::activate :
QgsVectorLayer::updateFields :
QgsVectorLayer::deleteAttribute :
QgsVectorLayer::deleteAttributes :
QgsAttributeTableDialog::mActionRemoveAttribute_triggered :
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
DispatchMessageW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.8.1-Zanzibar
QGIS code revision: dcd95cc648
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by Andrea-Zep** [comment]
> Hi, you must add a minimal set of steps to allow us replicate the issue. If you can add a sample project with data even better.

hi, thanks for the reply, i made a simple file
[simple file.zip](https://github.com/qgis/QGIS/files/3608843/simple.file.zip)

**Comment by gioman** [comment]
> hi, thanks for the reply, i made a simple file
> [simple file.zip](https://github.com/qgis/QGIS/files/3608843/simple.file.zip)

what are the steps to follow to replicate?

**Comment by ntgis** [comment]
## User Feedback

FIX YOUR GODDAM ISSUE, MONTHS AND MONTHS THIS HAS BEEN GOING ON

## Report Details

*Crash ID*: 62f1fcd2045780cb9f127836e6b579b8665f3e63


*Stack Trace*
<pre>
proj_lpz_dist :
proj_lpz_dist :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::QgsCoordinateTransform :
QHashData::free_helper :
QgsCoordinateTransform::addToCache :
QgsCoordinateTransform::invalidateCache :
QgsApplication::exitQgis :
QgisApp::~QgisApp :
CPLStringList::operator[] :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>


*QGIS Info*
QGIS Version: 3.8.2-Zanzibar
QGIS code revision: 4470baa1a3
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1



*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by nyalldawson** [comment]
No thanks. Take your whining, self entitled attitude elsewhere.

**Comment by roya0045** [comment]
@ntgis plugins

**Comment by Andrea-Zep** [comment]
> > hi, thanks for the reply, i made a simple file
> > [simple file.zip](https://github.com/qgis/QGIS/files/3608843/simple.file.zip)
> 
> what are the steps to follow to replicate?

the crash happens when the software is closing.

**Comment by roya0045** [comment]
If find it strange that you got a memcopy call when closing the software.

**Comment by gioman** [comment]
Crash confirmed on close after having loaded the provided project (even if the project does not have data).

**Comment by Andrea-Zep** [comment]
Another crash opening extend/trim button 🥺

**Comment by PeterPetrik** [comment]
@Andrea-Zep the zip is missing the file D:/GIS/RETINO TERRENO_REV00-01.shp

also I am not able to replicate it on MacOS QGIS 3.8

**Comment by Andrea-Zep** [comment]
[file RETINO.zip](https://github.com/qgis/QGIS/files/3646735/file.RETINO.zip)

**Comment by Andrea-Zep** [comment]
i downloaded the ver 3.8.3, i didn't recognize crashes.

**Comment by gioman** [comment]
>  i didn't recognize crashes.

@Andrea-Zep 
does it means that you are not getting crashes anymore?
