### ISSUE TITLE
graduated renderer widget doesn't properly sync with the layer's renderer

### ISSUE THREAD

**Issue by nirvn** [qgis/QGIS#31736]
**Describe the bug**

Following @3nids 's excellent work on the graduated renderer, a regression has slipped in whereas hitting the [ delete all ] button in the renderer's widget doesn't delete the class from the layer's renderer. There seems to be a syncing problem there.

**How to Reproduce**

<!-- Steps, sample datasets and qgis project file to reproduce the behavior. Screencasts or screenshots welcome

1. add two layers to a new project, including one which you will use to do a graduated classification
2. pick one layer, switch to graduated renderer (via style dock), classify a given field / value using the default classification mode (any will do really)
2. hit delete all button
3. notice the layer still renders features using the deleted classes
4. switch to your other layer, then switching back to the layer you had classified earlier & had hit delete all
5. notice the deleted classes are back.

**Comment by 3nids** [comment]
from @nirvn 

La premiere (qui est fort probablement la cause des autres regressions):
1. add two layers to a new project, including one which you will use to do a graduated classification
2. pick one layer, switch to graduated renderer (via style dock), classify a given field / value using the default classification mode (any will do really)
2. hit delete all button
3. notice the layer still renders features using the deleted classes
4. switch to your other layer, then switching back to the layer you had classified earlier & had hit delete all
5. notice the deleted classes are back.

Par la suite, quand je switch d'un type de classification a une autre, ca ne marche plus, les nouvelles classes sont ignores.
Je pense que le probleme est le meme, il y a un probleme de synchronisation entre le renderer associer au widget, et le renderer de la couche.

**Comment by 3nids** [comment]
other issue:

double minimum = mLayer->minimumValue( attrNum ).toDouble();
this isn't working for expression-based values
also, connecting the model to the dataChanged signal does _not_ deal with added / removed rows, hence why the delete all doesn't sync up.

**Comment by 3nids** [comment]
We need to save minimum size and maximum size values as members of the graduated renderer class, otherwise the values get lost when the classification only has one step

**Comment by 3nids** [comment]
> double minimum = mLayer->minimumValue( attrNum ).toDouble();
this isn't working for expression-based values
also, connecting the model to the dataChanged signal does not deal with added / removed rows, hence why the delete all doesn't sync up.

was this working in 3.8 ?

**Comment by nirvn** [comment]
@3nids , dunno, I suspect probably broken on 3.8 too.

**Comment by 3nids** [comment]
> double minimum = mLayer->minimumValue( attrNum ).toDouble();
this isn't working for expression-based values

where did you get that from? I just tested min and max values for expression, and it's correctly using the expression. 

see https://github.com/qgis/QGIS/blob/db7f8c3/src/core/classification/qgsclassificationmethod.cpp#L181-L187

![image](https://user-images.githubusercontent.com/127259/64970308-c8b4b400-d8a5-11e9-929d-14eb357fbc55.png)

**Comment by nirvn** [comment]
Ok, I might have tried against a failing expression.

**Comment by nirvn** [comment]
What about this line: https://github.com/qgis/QGIS/blob/master/src/gui/symbology/qgsgraduatedsymbolrendererwidget.cpp#L917 ?

**Comment by 3nids** [comment]
> What about this line:https://github.com/qgis/QGIS/blob/master/src/gui/symbology/qgsgraduatedsymbolrendererwidget.cpp#L917 ?

That's for setting the min/max of the spin box for the symmetry center. That would still be more correct to fix it too.
