### ISSUE TITLE
QGIS 3.4: Shapefile lost thousands of geometries after saving

### ISSUE THREAD

**Issue by Pippo87** [qgis/QGIS#31738]
I worked on my shapefile with like 2.217 polygons. Sometimes I delete or change something in the attribute table. 
After saving my edits, thousands (the mjority btw) of polygons just disappeared. 
Restarted QGIS, opened and even openened the project in older version (2.18) - nothing changed. All the entries are still in the attribute table, but their geometry is lost all of a sudden. The error message 'Zoom failed, feature has no geometry' appaears. 
I did not change the CRS or anything else.

Never happened before. Did enyone faced the same issue?

I read about at least in this post from GIS Stackexchange:

https://gis.stackexchange.com/questions/304596/polygon-geometry-suddenly-disappeared-deleted-from-shapefile-in-qgis#_=_

Seems unsolved.

Anyone at least any ideas how I could retrieve the lost geometries?

**QGIS and OS versions**

QGIS-Version | 3.4.8-Madeira | QGIS-Codeversion | 04ee8e0761
-- | -- | -- | --
Kompiliert gegen Qt | 5.11.2 | Laufendes Qt | 5.11.2
Kompiliert mit GDAL/OGR | 2.4.1 | Läuft mit GDAL/OGR | 2.4.1
Kompiliert mit GEOS | 3.7.2-CAPI-1.11.0 | Läuft mit GEOS | 3.7.2-CAPI-1.11.0 b55d2125
PostgreSQL-Client-Version | 9.2.4 | SpatiaLite-Version | 4.3.0
QWT-Version | 6.1.3 | QScintilla2-Version | 2.10.8
Kompiliert mit PROJ | 520 | Läuft mit PROJ | 5.2.0

**Comment by gioman** [comment]
Your shapefile has a spatial index? if yes delete it.

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
