### ISSUE TITLE
CRS selector not working

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#31753]
This is in the GDAL tool "Export to PostgreSQL" (the dialog to choose a CRS is all greyed out).

As the parameters is mandatory (I believe it should not be) then the user cannot use the tool at all unless the needed CRS is among the list/dropdown of the latest used.

This affects 3.4 but not master (and I can't spot any important difference in the code in the the two versions, but of course I'm probably wrong).

**Comment by gioman** [comment]
This affects also QGIS's "define layer projection".

**Comment by jagodki** [comment]
I can reproduce the problem with the CRS selector in QGIS 3.4.9 on Windows 10. The CRS selector of the plugin Offline-MapMatching (opened from the vector menu, toolbar and the toolbox) is also completely gray. I cannot reproduce the problem in QGIS 3.4 on macOS.

**Comment by gioman** [comment]
Yeah, I have also seen this in plugins.

**Comment by Gustry** [comment]
I can confirm on QGIS 3.4.12 too.
The CRS selector is totally disabled with this code:

```python
        self.addParameter(
            QgsProcessingParameterCrs(
                self.CRS,
                self.tr('Coordinate Reference System'),
            )
        )
```
and makes it impossible to use the Processing algorithm.

It's working well with a default CRS value such as:
```python
        self.addParameter(
            QgsProcessingParameterCrs(
                self.CRS,
                self.tr('Coordinate Reference System'),
                defaultValue='EPSG:2154',
            )
        )
```

**Comment by gioman** [comment]
> I can confirm on QGIS 3.4.12 too.

@Gustry 
so this mean that there was an underlying change that make necessary now to always specify a default CRS?

**Comment by Gustry** [comment]
@gioman I don't know, I'm just working on a new Processing provider and I notice I needed to define a default projection to make it work.

**Comment by gioman** [comment]
@Gustry thanks!

anyone has idea about what is going on here?

**Comment by nyalldawson** [comment]
The fix might be: https://github.com/qgis/QGIS/commit/63370d90dbf046218a2d7abed64f93c1b1d0c150

**Comment by gioman** [comment]
I have seen this on a number of 3.4.12 installations at a training, in this case in the CRS dialog of the "add delimited text layer" core tool.

**Comment by sigmoe** [comment]
For me, the CRS selector doesn't work only in the "Add delimited text layer".
It works correctly in:
- CRS Settings, 
- CRS Project properties,
- CRS Layer property,
...
In QGIS v3.4.13.

**Comment by Location-Artistry** [comment]
Does this fix the issue with not being able to set the CRS in QGIS 3.4?
