### ISSUE TITLE
"New 3D map view" button not available

### ISSUE THREAD

**Issue by juanmanuelrq** [qgis/QGIS#31755]
I have installed qgis in anaconda with: 
` conda install -c conda-forge qgis`

QGIS version | 3.8.2-Zanzibar | QGIS code branch | Release 3.8
-- | -- | -- | --
Compiled against Qt | 5.9.7 | Running against Qt | 5.9.7
Compiled against GDAL/OGR | 2.4.2 | Running against GDAL/OGR | 2.4.2
Compiled against GEOS | 3.7.2dev-CAPI-1.11.2 | Running against GEOS | 3.7.2dev-CAPI-1.11.2 0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.1.0 | Running against PROJ | Rel. 6.1.0, May 15th, 2019
OS Version | Linux Mint 19 |   |  

when I have to create a 3D view, I don't have the button VIEW/NEW 3D MAP VIEW

![0sI8K](https://user-images.githubusercontent.com/29231800/64894303-f21fd680-d63e-11e9-8bea-532655ea095f.png)
![3D-Map-View-en-QGIS-3](https://user-images.githubusercontent.com/29231800/64894304-f21fd680-d63e-11e9-89be-e1a79ee33353.png)

**Comment by roya0045** [comment]
Does the conda version has 3D disabled?

**Comment by juanmanuelrq** [comment]
conda info

     active environment : arpex_acim
    active env location : /home/inn/anaconda3/envs/arpex_acim
            shell level : 2
       user config file : /home/inn/.condarc
 populated config files : 
          conda version : 4.7.11
    conda-build version : 3.17.8
         python version : 3.7.3.final.0
       virtual packages : __cuda=10.2
       base environment : /home/inn/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/inn/anaconda3/pkgs
                          /home/inn/.conda/pkgs
       envs directories : /home/inn/anaconda3/envs
                          /home/inn/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.11 requests/2.21.0 CPython/3.7.3 Linux/4.15.0-20-generic linuxmint/19 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

**Comment by juanmanuelrq** [comment]
> Does the conda version has 3D disabled?

Hi, thanks for your answer, my conda version is 4.7.11

conda info

     active environment : arpex_acim
    active env location : /home/inn/anaconda3/envs/arpex_acim
            shell level : 2
       user config file : /home/inn/.condarc
 populated config files : 
          conda version : 4.7.11
    conda-build version : 3.17.8
         python version : 3.7.3.final.0
       virtual packages : __cuda=10.2
       base environment : /home/inn/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/inn/anaconda3/pkgs
                          /home/inn/.conda/pkgs
       envs directories : /home/inn/anaconda3/envs
                          /home/inn/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.11 requests/2.21.0 CPython/3.7.3 Linux/4.15.0-20-generic linuxmint/19 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

**Comment by roya0045** [comment]
@juanmanuelrq sorry this was a question to the official devs, it may be possible that the version on conda does not have 3D enabled, if you use the official way to install qgis you should have 3D enabled. I'm not sure if the missing 3D in conda is deliberate or not.

**Comment by juanmanuelrq** [comment]
> @juanmanuelrq sorry this was a question to the official devs, it may be possible that the version on conda does not have 3D enabled, if you use the official way to install qgis you should have 3D enabled. I'm not sure if the missing 3D in conda is deliberate or not.

Thank you, I am going to install the official version, best regards

**Comment by nyalldawson** [comment]
The conda build is not official supported

**Comment by roya0045** [comment]
Thanks Nyall, @juanmanuelrq If you encounter any bug with the official version do not hesitate. The newest version should be released today (if it wasn't already).

Happy mapping!
