### ISSUE TITLE
[layouts] @symbol_label variable is not listed in the expression dialog, no help

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#31756]
Add a legend item to a map layout
In the 'Legend items' section, select a layer and click the "Add an expression to the vector layer and each child symbol's label"
The expression dialog opens with a symbol `@symbol_label` already entered
What that variable represents is not available anywhere. I think it should be listed next to the other variables.

master 3.9 cdd3a55e9e

**Comment by roya0045** [comment]
I thought I added that in the docs, my bad.

**Comment by roya0045** [comment]
Oh right, the doc is there but since the variable is not in the scope that is generated in the GUI the variable and the doc don't show up, hence the fix from Matthias.
