### ISSUE TITLE
Data Privacy Compliance Information

### ISSUE THREAD

**Issue by SSGoveia** [qgis/QGIS#31767]
Please, I am a member of the QGIS Brazil User Group coordination. I don't know if this is the best channel for this kind of question.
A User is questioning about the data privacy information collected by the software, other than those sent by the bug report.
Not only the Privacy Policy (which is not on the QGIS.org website) but also the privacy of project data that is developed using QGIS.
Unfortunately I also did not find this information available on the website or software license, which refers only to the program code.

**Comment by rouault** [comment]
Questions should not be asked in QGIS issues. Please use the qgis-user mailing list https://lists.osgeo.org/mailman/listinfo/qgis-user or other support channels
