### ISSUE TITLE
QGIS master crash upon exit @ QgsCoordinateTransformPrivate::freeProj on Windows platform

### ISSUE THREAD

**Issue by nirvn** [qgis/QGIS#31762]
**Describe the bug**

While we have a fair number ( :cry: ) of "QGIS crash upon exit" for 3.4 and 3.8 (both running proj < 6), this issue covers a crash upon exit for the master builds (i.e. 3.9) on windows, where it also dies with proj >= 6.

My system is now able to duplicate the crasher every time I exit QGIS with a project loaded, and I've been able to install the debug symbol needed for a proper stack to be outputted. 

Without further due:

```
osgeo::proj::datum::Datum::conventionalRS :
osgeo::proj::datum::Datum::conventionalRS :
osgeo::proj::datum::Datum::conventionalRS :
QgsCoordinateTransformPrivate::freeProj qgscoordinatetransform_p.cpp:664
QgsCoordinateTransformPrivate::~QgsCoordinateTransformPrivate qgscoordinatetransform_p.cpp:120
QgsCoordinateTransformPrivate::`scalar deleting destructor' :
QExplicitlySharedDataPointer::~QExplicitlySharedDataPointer qshareddata.h:169
QgsCoordinateTransform::~QgsCoordinateTransform qgscoordinatetransform.cpp:148
QHashNode,QgsCoordinateTransform>::~QHashNode,QgsCoordinateTransform> :
QHashNode,QgsCoordinateTransform>::`scalar deleting destructor' :
QHash,QgsCoordinateTransform>::deleteNode2 qhash.h:547
QHashData::free_helper :
QHash,QgsCoordinateTransform>::freeData qhash.h:586
QHash,QgsCoordinateTransform>::~QHash,QgsCoordinateTransform> qhash.h:254
QHash,QgsCoordinateTransform>::operator= qhash.h:260
QHash,QgsCoordinateTransform>::clear qhash.h:591
QgsCoordinateTransform::invalidateCache qgscoordinatetransform.cpp:958
QgsApplication::exitQgis qgsapplication.cpp:1274
QgisApp::~QgisApp qgisapp.cpp:1662
QgisApp::`vector deleting destructor' :
main main.cpp:1579
WinMain mainwin.cpp:170
__scrt_common_main_seh exe_common.inl:253
BaseThreadInitThunk :
RtlUserThreadStart :
```

@rouault , this looks a lot like a crash you fixed a while back (https://github.com/qgis/QGIS/pull/7151/commits/6b7504d6cc9fb3868e2cb5f0e6396d901624fffc) , and also seems to link to @m-kuhn 's own look at this here (https://github.com/qgis/QGIS/pull/8693).

**How to Reproduce**

1. Launch QGIS, open a project
2. Exit QGIS, wait and notice the crash

**QGIS and OS versions**

QGIS master, Windows 7

**Additional context**

**Comment by nirvn** [comment]
@rouault , I've just installed a QGIS nightly on windows with your related commit included.

Unfortunately, the crash on exit remains (you had indeed mentioned that the likelihood of your commit addressing this specific crash was low).

The updated stack trace is as follow:

```
osgeo::proj::datum::Datum::conventionalRS :
osgeo::proj::datum::Datum::conventionalRS :
osgeo::proj::datum::Datum::conventionalRS :
QgsCoordinateTransformPrivate::freeProj qgscoordinatetransform_p.cpp:664
QgsCoordinateTransformPrivate::~QgsCoordinateTransformPrivate qgscoordinatetransform_p.cpp:120
QgsCoordinateTransformPrivate::`scalar deleting destructor' :
QExplicitlySharedDataPointer::~QExplicitlySharedDataPointer qshareddata.h:169
QgsCoordinateTransform::~QgsCoordinateTransform qgscoordinatetransform.cpp:148
QHashNode,QgsCoordinateTransform>::~QHashNode,QgsCoordinateTransform> :
QHashNode,QgsCoordinateTransform>::`scalar deleting destructor' :
QHash,QgsCoordinateTransform>::deleteNode2 qhash.h:547
QHashData::free_helper :
QHash,QgsCoordinateTransform>::freeData qhash.h:586
QHash,QgsCoordinateTransform>::~QHash,QgsCoordinateTransform> qhash.h:254
QHash,QgsCoordinateTransform>::operator= qhash.h:260
QHash,QgsCoordinateTransform>::clear qhash.h:591
QgsCoordinateTransform::invalidateCache qgscoordinatetransform.cpp:958
QgsApplication::invalidateCaches qgsapplication.cpp:366
QgsApplication::exitQgis qgsapplication.cpp:1277
QgisApp::~QgisApp qgisapp.cpp:1662
QgisApp::`vector deleting destructor' :
main main.cpp:1579
WinMain mainwin.cpp:170
__scrt_common_main_seh exe_common.inl:253
BaseThreadInitThunk :
RtlUserThreadStart :
```

**Comment by nirvn** [comment]
I think I found a way to reliablty reproduce the crash using this zipped project:
[crash.zip](https://github.com/qgis/QGIS/files/3620451/crash.zip)

1. Load the crash.qgz project
2. When the project is loaded, pan the canvas with your mouse
3. After panning, close QGIS via the [ x ] close windows button
4. *boom*

There are three projection transformation registered in this test project, which appears to be part of what triggers the crash.

**Comment by nirvn** [comment]
I *think* I can replicate the crash on linux too:

```
src/core/qgsapplication.cpp:365 : (invalidateCaches) [0ms] BEFORE: QgsCoordinateTransform::invalidateCache( true );
corrupted double-linked list
Aborted (core dumped)
```

**Comment by rouault** [comment]
> How does one debug a corrupted double-linked list crash?

Valgrind is your friend `valgrind --num-callers=40 output/bin/qgis crash.qgz` . I'm on it
