### ISSUE TITLE
Dissolve tool dialog box closes prematurely after choosing dissolve fields version 3.8.2

### ISSUE THREAD

**Issue by Esbern** [qgis/QGIS#31776]
QGIS version: 3.8.2 os: Mac 10.14.6

When using the vector geometry dissolve tool the dialog box closes prematurely after choosing dissolve fields (independent of the number of fields selected) . This behavior is independent of how I access the tool (use the menu vector menu or the processing tools) The error occurred on both shp and geopackages files. The GDAL dissolve works fine.

**Comment by roya0045** [comment]
Does it closes or simply goes behind other windows, as it occurred with other mac users?

**Comment by Esbern** [comment]
Solved (sort of) it is the same issue as other mac users it the dialog box simply disappears behind thee other windows.

**Comment by alexbruy** [comment]
Duplicates #31577
