### ISSUE TITLE
Boolean virtual field unusable in virtual layers.

### ISSUE THREAD

**Issue by GeoJGH** [qgis/QGIS#31798]
There is an issue with virtual field of type boolean that are then used in a virtual layer. The value of such field is not null but is empty (ie. not true, not false, not null).

I have tested this using a memory layer, a Postgres table and a simple Shapefile, using QGIS 3.4.5.

Step to reproduce:
Open QGIS
Create a new in memory layer named "a". Create 2 entries.
Add a virtual field of type Boolean named "test_bl", set the value to TRUE.
Create a new virtual layer with the expression SELECT * FROM a WHERE test_bl = true
Open attribute table, see that it is empty.
Update the virtual layer expression  SELECT * FROM a WHERE test_bl IS NOT NULL
Open attribute table, see all records are there but the column "test_bl" is empty.

Note that doing the same test using an integer field works fine.

Related post on GIS StackExchange: https://gis.stackexchange.com/questions/336017/creating-a-virtual-layer-based-on-a-virtual-field-for-dynamic-selection-in-qgis/336038#336038

**Comment by troopa81** [comment]
> Update the virtual layer expression SELECT * FROM a WHERE test_bl IS NOT NULL
Open attribute table, see all records are there but the column "test_bl" is empty.

This one was an issue. The PR #38957 fixes it

> Create a new virtual layer with the expression SELECT * FROM a WHERE test_bl = true

Be aware that virtual layer is based on SQLITE SQL syntax, and there is not [real boolean type in SQLITE](https://www.sqlite.org/datatype3.html) and type is in fact an integer. So when the fix will be merged, you will have to write this query to filter on boolean attribute.

```sql
SELECT * FROM a WHERE test_bl
```
or
```sql
SELECT * FROM a WHERE not test_bl
```
