### ISSUE TITLE
UI: PostGIS layer error message not helpful, disappears and shouldn't happen

### ISSUE THREAD

**Issue by Komzpa** [qgis/QGIS#31799]
Trying to generate a slow postgis layer to reproduce #31635.

In PostGIS-enabled DB:
```
create table test_table as (select (ST_DumpPoints(ST_GeneratePoints(ST_Expand('SRID=4326;POINT(0 0)'::geometry,90),10))).geom, random());  
create view test_view as (select geom, random+coalesce(pg_sleep(0.1)::int,0)  g from test_table);  

15:13:11 [gis] > select * from test_view ;
┌────────────────────────────────────────────────────┬─────────────────────┐
│                        geom                        │          g          │
├────────────────────────────────────────────────────┼─────────────────────┤
│ 0101000020E610000000E474FFFFA941C05DE2B4AF24D142C0 │  0.6291001356093986 │
│ 0101000020E610000026BD30DC220734C04F03C2ADB6B141C0 │  0.5626557368133867 │
│ 0101000020E61000003766CF73210846C080D87D9EDF1A34C0 │ 0.09838422078965436 │
│ 0101000020E61000000ECC1C6F5AA8534070661A75CD331440 │ 0.16004865906309007 │
│ 0101000020E610000000DFEFDF588A0240CB3D3A67B7DA5240 │  0.3205073746002043 │
│ 0101000020E6100000A077D1AD2CF9FEBF382B10F522E22D40 │ 0.23407737790354943 │
│ 0101000020E6100000F20B3DABC02E40C08FC8DF2C55A84F40 │  0.9812978427793695 │
│ 0101000020E6100000C91FCDD123744140DE96041BCEEB4340 │  0.6411738976976515 │
│ 0101000020E6100000CA5754AEFFFB524000FAFBCCCC5556C0 │  0.5346711048059873 │
│ 0101000020E610000056C4D34ACA234FC0F800CA54E0DE4AC0 │  0.8792077187687006 │
└────────────────────────────────────────────────────┴─────────────────────┘
(10 rows)

Time: 1012,931 ms (00:01,013)
```
Geometry looks good, accessing the value sleeps 0.1s per row.

I try to add the layer in QGIS. It's seen well in PostGIS tree:
![image](https://user-images.githubusercontent.com/810638/64957400-8be0c100-d895-11e9-829e-70ba040331fd.png)

Try to drag it into map. Wait expected 1s. Get unhelpful error message:
![image](https://user-images.githubusercontent.com/810638/64957464-b468bb00-d895-11e9-80ec-9769021d4993.png)

 - Reason is empty.
 - Message disappears before I finish reading it. A layer that loads more time than it and then fails will be lost, as I won't be at the computer in case it loads 1minute+.
 - It should just work. Adding test_table of same structure works.

**Comment by elpaso** [comment]
@Komzpa I think that you need to specify a valid column (or a set of columns) that can uniquely identify a feature in order to add it to QGIS, if you use the data source manager dialog a warning sign besides the view row will tell you that.

You can click on the small icon on the top left of the error message to make it permanent.

While for a real table we can use `tid`, for views that is not possible.

**Comment by Komzpa** [comment]
How do I specify them not leaving this drag and drop UI?

It also does not show me any indication there's an issue with this relation, and message does not lead me to the idea on what to do.

I added column `ctid` from upstream table and tried adding this using DB manager. The triangle went away, but the issue is now different:
![image](https://user-images.githubusercontent.com/810638/64972890-bd1bba00-d8b2-11e9-8b8f-3b36cc5ef9c0.png)

Suggested log is not helpful either:
![image](https://user-images.githubusercontent.com/810638/64972958-dae91f00-d8b2-11e9-9d9f-f5cf7b3992e6.png)

**Comment by elpaso** [comment]
what is the new view definition you are testing?

**Comment by Komzpa** [comment]
```
create view test_view as (select geom, random+coalesce(pg_sleep(0.1)::int,0)  g, ctid from test_table);  
```

**Comment by elpaso** [comment]
`ctid` returns a tuple that cannot be used as a feature key, try this:

```sql
create view test_view as (select row_number() OVER (ORDER BY ctid) , geom, random()  from test_table, pg_sleep(0.1));
```

**Comment by elpaso** [comment]
The message log actually contains some more information:
```
2019-09-17T12:17:08     WARNING    Field ctid ignored, because of unsupported type tid
2019-09-17T12:17:08     WARNING    Key field 'ctid' for view/query not found.
2019-09-17T12:17:08     WARNING    Keys for view/query undefined.
2019-09-17T12:17:08     WARNING    PostgreSQL layer has no primary key.
```

**Comment by Komzpa** [comment]
True, ticketed that.

In https://github.com/qgis/QGIS/issues/31799#issuecomment-531830225 you said you use tid for tables, why it can't be for views then?

**Comment by elpaso** [comment]
Honestly I'm not sure we have a bug here. 
I agree that the error message could be better, but the thing is that the provider tries hard to find a suitable key and it fails.

The final message that is shown to the user in the message bar comes from the application that cannot get a valid layer from the provider, there is currently no API to retrieve the error message from the provider (I agree that it would be nice to have), so we can only point the user to the log messages for more information about the failure.

**Comment by Komzpa** [comment]
What is the key needed for?
I see that there's a checkbox saying "select by id". When I uncheck that, message about the "no primary key" disappears, but layer still says that it is invalid, without any other messages:

![image](https://user-images.githubusercontent.com/810638/65034769-577e0b00-d950-11e9-912f-236cea513711.png)

I expect that configuration to work. In fact I expect it to just work for layers without PK, losing the tick about "select at id".

**Comment by elpaso** [comment]
If you place your mouse over the column header "Select at id", you'll find the answer to your question: that checkbox is not for what you think.

For the `tid` type in views: the `tid` type fields are not supported by the current provider implementation but it can automatically make use of `ctid` as a fallback PK for real tables (because all  tables have that field), in case of a view the view does not have a `ctid` so we cannot use it and we need to rely on other field(s) to specify the PK.

What happens here is that since `ctid` is of type `tid` and that type is not a supported  QGIS field type it gets removed from the fields and even if you specify it in the view row settings the provider cannot find it and fails to create a valid layer.

I guess this is a bug even if it's probably a corner case.

**Comment by Komzpa** [comment]
ok, it now works with this definition:
```
create view test_view as (select geom, random+coalesce((0||pg_sleep(0.1)::text)::int,0)  g,0 as id from test_table);
```

Identify, Rendering works in this configuration. I'm not sure what doesn't - perhaps editing, but it's not supposed to work for views anyway. Can feature ID default to 0 if not found and just let these parts work?

**Comment by elpaso** [comment]
no: we need a pk (or something pretending to be a pk) to identify a row.

**Comment by Komzpa** [comment]
Indeed table view breaks. Identify doesn't though.

Note `ctid` may be duplicate in partitioned tables.

A way to blindly generate stable surrogate id from content is something like:
`select md5(row(a.*)::text)::uuid as id, * from test_view a;`
 - that can be applied to any relation, including views.
