### ISSUE TITLE
Composer doesn't update map_layer_ids after changeing Data Defined Override for a map object

### ISSUE THREAD

**Issue by vince-ice** [qgis/QGIS#31808]
**Describe the bug**
I am trying to do the following: Duplicate an existing layout, and then change the underlying layer af a layout map object. However, the old referenced layer still displays, and updating the layout doesn't help.

**How to Reproduce**
1. Open the Layout Manager via Project->Layout Manager...
2. Create a layout "layout1" with a map object and, under the "Item Properties" tab, toggle "Lock layers" on.
3. Click on the "Data defined override" button, just next to the eye icon, and select "Edit..."
4. Now, input a couple of layer names with "|" as delimiting character. Enclose with double quotes, e.g.:
`"003-CT-02_poi|Limiti comunali"` 
where the two layers we want to use are "003-CT-02_poi" and "Limiti comunali".
5. click Ok, then close the layout.
6. Now make a duplicate under the layout Manager window by clicking on the "Duplicate..." button. Let's call our new layout "layout2".
7. Open "layout2", click on the map object and, under "Item Properties", scroll to "Layers". The Data Defined Override button should be yellow. Click on it, and select Edit...
8. Now, change the string, to e.g.:
`"003-CT-03_poi|Limiti comunali"` 
as to replace the previous layer, "003-CT-02_poi" with the new one, "003-CT-03_poi", we want to show on the layout.
9. Click Ok to accept, and then View->Refresh.
4. Unfortunately the old map composition still holds, and the new inputed values are not taken into account.

**QGIS and OS versions**
QGIS version | 3.4.7-Madeira 
QGIS code branch | Release 3.4
Compiled against Qt | 5.12.3 
Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1
Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.0-CAPI-1.11.0 
Running against GEOS | 3.7.0-CAPI-1.11.0 673b9939
PostgreSQL Client Version | No support 
SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3
QScintilla2 Version | 2.11.1
Compiled against PROJ | 520
Running against PROJ | 5.2.0

**Additional context**
I noticed that, under the "Variables" section of the layout map object, the variabile Map Settings->map_layers_ids still references the old layer id "003_CT_02__poi_223cdf24_d490_4b84_a04e_7d5b8fd55acf" instead of the new layer "003_CT_03__poi_1297aec5_58fd_4ffb_9914_dd275400b759".
I thus opened the QGIS file with a text editor, and navigated to the `<Layout>` tag with the attribute _name_ equal to "layout2", in my case:
`<Layout units="mm" worldFileMap="{7aef77f9-bc08-416e-b2d6-303aa26bd6ca}" printResolution="300" name="layout2">`.
Under that `<Layout>` tag, there's a `<LayoutItem>` that describes the map, with the expected  reference to the updated Data Defined Override (see step 8 above):
`          <dataDefinedProperties>
            <Option type="Map">
              <Option type="QString" name="name" value=""/>
              <Option type="Map" name="properties">
                <Option type="Map" name="dataDefinedMapLayers">
                  <Option type="bool" name="active" value="true"/>
                  <Option type="QString" name="expression" value="&quot;003-CT-03_poi|Limiti comunali&quot;"/>
                  <Option type="int" name="type" value="2"/>
                </Option>
              </Option>
              <Option type="QString" name="type" value="collection"/>
            </Option>
          </dataDefinedProperties>`
However, under the same `<LayoutItem>` tag, there's a `<LayerSet>` which wrongly references the old values, i.e. those we inputed in step 4 above:
`        <LayerSet>
          <Layer source="/home/vince/path/003-CT-02_poi.shp|layername=003-CT-02_poi" provider="ogr" name="003-CT-02_poi">003_CT_02__poi_223cdf24_d490_4b84_a04e_7d5b8fd55acf</Layer>
          <Layer source="/home/vince/path/LimitiComuni.shp" provider="ogr" name="Limiti comunali">LimitiComuni_0920150313135256522</Layer>
        </LayerSet>
`
By manually replacing that `<LayerSet>` with:
`        <LayerSet>
          <Layer source="/home/vince/path/003-CT-03_poi.shp|layername=003-CT-03_poi" provider="ogr" name="003-CT-03_poi">003_CT_03__poi_1297aec5_58fd_4ffb_9914_dd275400b759</Layer>
          <Layer source="/home/vince/path/LimitiComuni.shp" provider="ogr" name="Limiti comunali">LimitiComuni_0920150313135256522</Layer>
        </LayerSet>
`
we fix the problem. 
(layer ID can be easily found by searching among the `<layer-tree-layer>` tags)

**Comment by nyalldawson** [comment]
I can't reproduce. I suspect your issue is coming from:

    Enclose with double quotes, e.g.: "003-CT-02_poi|Limiti comunali"

Enclosing with double quotes means you're refering to a field value, i.e. the value in the `003-CT-02_poi|Limiti comunali` field. I suspect if you change these to single quotes then things will work as expected.

**Comment by vince-ice** [comment]
Ops!!!
How bad of me. Thanks @nyalldawson and sorry all for wasting your time!
