### ISSUE TITLE
inital GetCapabilities request takes very long when millions of rows in layer

### ISSUE THREAD

**Issue by cfsgarcia** [qgis/QGIS#31803]
**Describe the bug**
The inital GetCapabilities request takes very long because my tables contain millions of records. Tracing the database I see for every layer a (or more) "SELECT count(*) FROM "mytable" is issued (postgis layer, indexed etc.). 
As this is a costly query on my large tables: where does it come from and is it configurable?
To be notified: the layers based on large tables are only visible from 1:5,000 on wards. This way no more than a few hundred features are ever loaded up in the map extent.
Works flawlessly in QGIS Desktop. Opening qgs project is fast. Panning, zooming is fast. Loading up data at requested scale is fast.

The workaround I found in QGIS Server consists in:
-wait for 8-9 minute to generating the GetCapabilities (time for select count (*) [...] to be run)
-export generated GetCapabilities.xm to the web server
-create a qgs project consuming this GetCapabilities as wms. This new qgs project will load up instantaneously.  
Works but it's not ideal at all.

**How to Reproduce**
-Have a layer in Postgres/Postgis  11.4/2.4.5 with over 30 millions of rows,
-Add it to qgs project,
-"publish" this qgs project with QGIS Server as WMS (standard config).
-Access this map service in a web browser
-Trace queries in Postgres, see this SELECT count(*) [...]
-Will take potentially long for the WMS to load.

**QGIS and OS versions**
QGIS 3.4.9 Madeira with QGIS SERVER

**Additional context**

**Comment by elpaso** [comment]
Did you check "Use estimated table metadata" in the postgres connection settings for the layers?
If not, can you try that and see if it makes a difference?

**Comment by cfsgarcia** [comment]
Thank you very much Elapso! That's the trick. It does help a lot indeed.
