### ISSUE TITLE
is_selected() not working as filter in print composer

### ISSUE THREAD

**Issue by brusspi** [qgis/QGIS#31807]
**Describe the bug**

Using QGIS 3.8.2 adding `is_selected()` as filter in the print composer returns an error 

**How to Reproduce**

1. select some features
2. add a print composer
3. enable atlas function
4. set the map-item-properties as to be controlled by the atlas
5. define the filter `is_selected()`

message: > no matching atlas features found

When trying to use the same expression in the attribute table, using the 'Advanced Filter' with the same expression `is_selected()`, it works fine.  Idem dito with the rule based styling of the layer only

In QGIS 2.18 you could use an expression (provided by a plugin): `isselected('layername')` which worked fine.

**Comment by nyalldawson** [comment]
Confirmed.
