### ISSUE TITLE
SAGA RGB Composite not working - "*.tif" files not accepted

### ISSUE THREAD

**Issue by AuSpotter** [qgis/QGIS#31816]
Using the SAGA Raster Visualisation tool under the Processing toolbox, an error is generated: 

“.tif” files are not supported as outputs for this algorithm

However, only the tif format is available under the Save File dialogue.
QGIS 3.8.2-Zanzibar
Windows 10 (10.0)

**Comment by gioman** [comment]
Ummm... that SAGA tool is one of the few that *must* ouput a tif and not the SAGA native format.

This was addressed here: https://github.com/qgis/QGIS/pull/8597

so the fact that Processing blocks the operation with that message does not make sense, @nyalldawson  any idea?

**Comment by alexbruy** [comment]
Should be fixed with #35820. Please re-test.

**Comment by nyalldawson** [comment]
Closing due to lack of feedback
