### ISSUE TITLE
QGIS crashes by clicking on a html Link in getFeatueInfo of WMS Service

### ISSUE THREAD

**Issue by netgis** [qgis/QGIS#31830]
-> I have a WMS Service an loading it in QGIS 3.8.1, no problem.
-> With the info button I make a getFeature Request on a polygon and get back an valid HTML Document with links inside.
-> Qgis crashes when clicking on this links.

## Report Details

*Crash ID*: acd4d5b4a58a8988e82a0ae10d6f9f561df9e131

*Stack Trace*
<pre>
QWebFrame::baseUrl :
QWebPage::acceptNavigationRequest :
QWebPage::userAgentForUrl :
WebCore::FrameSelection::`default constructor closure' :
WebCore::ArchiveResourceCollection::archiveResourceForURL :
WebCore::FrameLoader::clearTestingOverrides :
WebCore::FrameLoader::loadFrameRequest :
WebCore::FrameLoader::clearTestingOverrides :
WebCore::FrameLoader::urlSelected :
WebCore::HTMLPlugInElement::getNPObject :
WebCore::UserGestureIndicator::~UserGestureIndicator :
WebCore::ScriptedAnimationController::isThrottled :
WebCore::Element::containsFullScreenElement :
WebCore::EventHandler::handleMouseReleaseEvent :
WebCore::EventHandler::handleMouseReleaseEvent :
QWebPageAdapter::mouseReleaseEvent :
QWebPage::event :
QWebView::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
DispatchMessageW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.8.1-Zanzibar
QGIS code revision: dcd95cc648
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by andreasneumann** [comment]
Hi @netgis - I believe this has been fixed in https://github.com/qgis/QGIS/commit/fc73f7bec1b8cb0e9156bc1c60c53929545b172c - can you retry with QGIS 3.8.3?

See also https://github.com/qgis/QGIS/issues/31226

**Comment by netgis** [comment]
Just installed 3.8.3, yes it is fixed and now works perfectly, thank you.
