### ISSUE TITLE
QgsDateTimeEdit doesn't behave correctly for NULL values

### ISSUE THREAD

**Issue by Gustry** [qgis/QGIS#31849]
**Describe the bug**

Given this Python code:
```python
dialog = QDialog()
layout = QHBoxLayout()
dialog.setLayout(layout)

edit = QgsDateTimeEdit()
edit.clear()  # Should display NULL
layout.addWidget(edit)
dialog.exec_()
```
that we can run from the Python console, the widget is displaying the current date as a placeholder. `NULL` should be displayed instead.

Documentation of `clear`:
https://qgis.org/api/classQgsDateTimeEdit.html#ac764f28b1ceaa092de8df0e2bf24e18b

Another example:
```python
dialog = QDialog()
layout = QHBoxLayout()
dialog.setLayout(layout)
edit = QgsDateTimeEdit()
layout.addWidget(edit)
dialog.exec_()
```

Simple click on the "clear" button will indeed set `NULL`.
But a double click on the "clear "button" will set the current date as a placeholder instead of `NULL`.

**QGIS and OS versions**

QGIS version | 3.9.0-Master | QGIS code revision | 99a525c513
-- | -- | -- | --
Compiled against Qt | 5.12.2 | Running against Qt | 5.12.2
Compiled against GDAL/OGR | 2.4.0 | Running against GDAL/OGR | 2.4.0
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
PostgreSQL Client Version | 11.5 (Ubuntu 11.5-1.pgdg19.04+1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.10.4
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Ubuntu 19.04 |   |

**Comment by signedav** [comment]
Hi @Gustry 

With the implementation done on PR #32158 this would look like this:
```
dialog = QDialog()
layout = QHBoxLayout()
dialog.setLayout(layout)

edit = QgsDateTimeEdit()
edit.clear()  # Should display NULL
layout.addWidget(edit)
edit = QgsDateTimeEdit()
layout.addWidget(edit)
dialog.exec_()
```
![python](https://user-images.githubusercontent.com/28384354/66399028-1d4bda80-e9df-11e9-82e3-ee68083e80f0.gif)

Before it has been an inconsistent behavior (like you mention here) but with this fix it's consistent. Just not like you describe, like it should be. IMHO when pressing the clear button the value of the widget should be NULL but the text displayed should _not_ be the null representation. In the range widget it's empty and here it's the current date as kind of template...

**Comment by Gustry** [comment]
Ok thanks for your inputs.
So your PR will close this ticket, right?

**Comment by signedav** [comment]
Yes.
