### ISSUE TITLE
BBOX in GetLegendGraphic is not taken into account

### ISSUE THREAD

**Issue by Livava1** [qgis/QGIS#31840]
**Describe the bug**
QGIS3 is ignoring BBOX in GetLegendGraphic-requests.

`../qgis/qgis_mapserv.fcgi.exe?SERVICE=WMS&VERSION=1.3.0&CRS=EPSG:32632&REQUEST=GetLegendGraphic&FORMAT=image/png&map=<mapname>.qgs&BBOX=601393,6637900,601670,6638230&ITEMFONTSIZE=10&ITEMFONTFAMILY=Arial&SYMBOLWIDTH=20&HEIGHT=30&WIDTH=30&DPI=300&LAYERS=<layername>`

This request on a server with 2.14 is returning only items within BBOX
This request on a server with 3.8 is returning the full legend

**QGIS and OS versions**
QGIS 3.8 (also in 3.6), windows

**Comment by elpaso** [comment]
I've verified this in master and it works correctly, there are also some tests in place that confirm that it is working as expected, can you please check if this issue has been solved in current master?
3.8 is end of life anyway there won't be any bugfixes on that branch.

**Comment by Livava1** [comment]
I have just been doing some more testing and can confirm that it is working as it should. It turns out that my problem is connected to inherited project files and layers from QGIS2 - I probably need to add them all again. Sorry for the confusion.
