### ISSUE TITLE
Server GetLegendGraphics contextual (BBOX) fails if no WIDTH and HEIGHT are supplied

### ISSUE THREAD

**Issue by elpaso** [qgis/QGIS#31846]
For instance, using the projects and layers used in our CI tests:
```
?MAP=/dev/QGIS/tests/testdata/qgis_server/test_project_wms_grouped_nested_layers.qgs&SERVICE=WMS&VERSION=1.3&REQUEST=GetLegendGraphic&LAYER=areas%20and%20symbols&FORMAT=image/png&CRS=EPSG:4326&BBOX=52.4124,10.6727,52.4649,10.7794&SLD_VERSION=1.1
```

fails with 
```xml
<ServiceException code="InvalidParameterValue">The requested map size is too large</ServiceException>
</ServiceExceptionReport>
```

**Comment by elpaso** [comment]
Some more context.

I discovered this while testing contextual WMS legend from QGIS client. 

QGIS client adds a BBOX but does not add WIDTH or HEIGHT (which is actually good, because they would probably be much larger than what's required server side for an hit test), so my proposed solution will be to add some default values for WIDTH and HEIGHT (800x600 looks good) in case of GetLegendGraphics calls with BBOX set.

**Comment by elpaso** [comment]
@pblottiere am I missing anything here? 
Are `SRCHEIGHT` and `SRCWIDTH` supposed to be used in this case?

**Comment by daniviga** [comment]
I guess it's related to this: https://github.com/qgis/QGIS/pull/9236

**Comment by elpaso** [comment]
@daniviga thanks for the link!
@signedav do you agree with my proposed solution in #31865 ? 
It is basically using a default fallback value to 800x600 for the hit test in case BBOX is specified but WIDTH/HEIGHT are not.

**Comment by pblottiere** [comment]
> @pblottiere am I missing anything here?
> Are SRCHEIGHT and SRCWIDTH supposed to be used in this case?

Yes it will be more explicit for future reading I think.

**Comment by rldhont** [comment]
@elpaso does the issue exist in version 3.4 ? Has the fix have to be backported ?

**Comment by elpaso** [comment]
@rldhont I didn't check yet.

**Comment by signedav** [comment]
Sorry @elpaso for not replying. I've overseen this discussion while my vacation.
The PR looks good. 

For information: On the PR I made back then #9545 I introduced SRCWIDTH -> if empty I kept the fallback to use WIDTH and now if this is empty too you introduced the fallback to a static value. That's IMO a good solution.

Thanks a lot :+1:
