### ISSUE TITLE
Crash of QGIS

### ISSUE THREAD

**Issue by FlyingEagle** [qgis/QGIS#31869]
## User Feedback

Open Polygon Shape File in a new empty Project, click Edit to edit this Layer and then click on Move-Points (the second to the right from the layers save-disc).

## Report Details

*Crash ID*: 3a49922535deed301e5a889590f5e468cbdb0094

*Stack Trace*
<pre>
QWidget::show :
QgsVertexEditor::updateVertexSelection :
QTimer::timeout :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32Private::sendTimerEvent :
QEventDispatcherWin32::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.8.0-Zanzibar
QGIS code revision: 11aff65f10
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by nirvn** [comment]
Fixed a while back. Update to latest 3.8.3 version.
