### ISSUE TITLE
Processing's Package Layers will create empty GPKG if no input layers are selected

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#31888]
**Describe the bug**
Processing's Package Layers will create empty GPKG if no input layers are selected instead of erroring and telling the user that they should select one or more layers. The GPKG will contain a `ogr_empty_table` dataset which is exactly what it says it is.

**How to Reproduce**

1. Launch `Package Layers`
2. Click on 'Run'
3. `Package Layers` writes an empty GPKG to the temporary path

Instead it should error and tell the user to select at least one layer.

**QGIS and OS versions**

QGIS version | 3.9.0-Master | QGIS code revision | 738ced6488
-- | -- | -- | --
Compiled against Qt | 5.13.0 | Running against Qt | 5.13.1
Compiled against GDAL/OGR | 3.0.1 | Running against GDAL/OGR | 3.0.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.1.0 | Running against PROJ | Rel. 6.2.0, September 1st, 2019
OS Version | Arch Linux |   |

**Comment by nyalldawson** [comment]
I don't think this is an issue - if we make it always abort in this case then we lose flexibility in models, where an empty result may be valid...

**Comment by kannes** [comment]
But it is meant to package layers. :D
Shouldn't a model realise there is nothing to package first or accept the "no"?

**Comment by nyalldawson** [comment]
It should raise a warning, but not abort...
