### ISSUE TITLE
Features randomly dissappeared from shapefiles, while attributes remain in attribute table.

### ISSUE THREAD

**Issue by ryanwoodsmith** [qgis/QGIS#31886]
In two of my shapefiles, the polygons I had previously saved disappeared while leaving their attributes in the attribute tables intact.  In one shapefile, all 109 polygons dissapeared, while in the other, about 10 of 70 dissappeared.  When I right click on the polygon in the attribute table > Zoom to feature, the message "Zoom to feature id failed: feature does not have a geometry" appears.  I dont know exactly how to reproduce the problem or why it happened.  Has anyone seen this before?  Any idea why this might happen? Is it possible to recover the data?  

I am using QGis 3.6.3.

**Comment by nirvn** [comment]
Can you share a problematic dataset? If you cant provide a way to replicate your issue, it's unlikely devs can look into it.

**Comment by nirvn** [comment]
Oh and please update your QGIS to 3.8.3 and try again. There have been literally hundreds of fixes applied since 3.6.3.

**Comment by alexbruy** [comment]
Probably duplicates #31738

**Comment by gioman** [comment]
> Probably duplicates #31738

Hi Alex, not sure is duplicate. I have seen exactly the same thing on a Windows (with the latest 3.4) machine a few days ago, and it didn't happened after any editing operation, and the shapefiles had no spatial indexes.

**Comment by Pedro-Murteira** [comment]
I've not been able to reproduce this issue in any of the recent releases. (3.16, 3.22 or the newly released 3.24). @ryanwoodsmith Did you come across this issue more recently?
