### ISSUE TITLE
Layers with rules-based legend failing to draw

### ISSUE THREAD

**Issue by JordanPinder** [qgis/QGIS#31884]
Hello!

I have layer with a _somewhat_ complex layer, ~40 total individual classes which is based on a simple rules (i.e. LIKE, = etc.). However the layer fails to draw if it has any more than 31 classes activated. I've mixed it with different classes but it always seems to be anything more than 31 when it fails. 

Any ideas what the issue might be?

**Comment by roya0045** [comment]
Could you share a project with the layer if its not sensitive information?

**Comment by nirvn** [comment]
Just tested on QGIS master, 300-something simple "ID" = X rules works perfectly fine:
![Screenshot from 2019-09-20 10-51-03](https://user-images.githubusercontent.com/1728657/65298164-a1573300-db94-11e9-8010-b5a44ac2cded.png)

If there is an issue with QGIS here, it's  not merely about the number of rules. As @roya0045 suggested, you'll have to provide a test case project that shows the issue for devs to start looking into it.

**Comment by basilrabi** [comment]
A similar issue #27269 has been fixed before.

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
