### ISSUE TITLE
Arabic characters labeling

### ISSUE THREAD

**Issue by moawiakhadish1983** [qgis/QGIS#31907]
when i am trying to label my local network roads and choosing the curved manner for labeling the letters  Separating from each other and this is contrary to the Arabic text and The order of the words is reflected. how can i fix that?
![true](https://user-images.githubusercontent.com/55588127/65328434-fd36b180-dbbe-11e9-907c-7324c561ae1d.png)
![fales](https://user-images.githubusercontent.com/55588127/65328441-032c9280-dbbf-11e9-93f2-98013ab4b437.png)

**Comment by saberraz** [comment]
This is a duplicate #21940

**Comment by erizk** [comment]
please is there any clear solution for the above-reported problem because it is still persisting with QGIS version 3.12.3

**Comment by moawiakhadish1983** [comment]
Unfortunately, the problem was not solved. Someone sent a report of the error , but the report was closed, i was sent again, but also the report was closed without solution ):

**Comment by gioman** [comment]
> Unfortunately, the problem was not solved. Someone sent a report of the error , but the report was closed, i was sent again, but also the report was closed without solution ):

@moawiakhadish1983 this is open https://github.com/qgis/QGIS/issues/21940
