### ISSUE TITLE
auto-extend string and integer fields of shapefiles

### ISSUE THREAD

**Issue by rmarzocchi84** [qgis/QGIS#31903]
I do not like so much shapefile, but a lot of basic user of QGIS use this format. 

I read today that starting from GDAL 1.10 it is possible to  "auto-extend string and integer fields up to 255 bytes" https://gdal.org/drivers/vector/shapefile.html#field-sizes

I do not really know what it is mean? But in your opinion it is possible for QGIS to manage this behaviour?

**Comment by DelazJ** [comment]
I think it's already the case (reminds me of an old issue report): if you add a 7 characters string in a field you define with 5 characters, it'll be adjusted and the text inserted instead of throwing an error. *Didn't try myself over the years but this is what I understood.*

**Comment by rmarzocchi84** [comment]
We have tried on QGIS 3.4 but it do not works

**Comment by DelazJ** [comment]
Actually, from what i can see, it does not happen if you type the value in the field; it happens if you copy a feature from another layer (same field name of course but different length), the original field gets extended to the new value size. Tested with 3.6.
