### ISSUE TITLE
Unable to copy message - copies attribute table instead

### ISSUE THREAD

**Issue by jonathan-geoseer** [qgis/QGIS#31918]
3.4.12 - windows
(Similar to but different from https://github.com/qgis/QGIS/issues/31914)

I'm trying to copy an error from the top error bar to paste it here for a ticket. I have selected the text and ctrl-c (copy).

Rather than the error text, QGIS is adding 345 lines of stuff from the attribute take of the WFS layer I have added (but not enabled) in the view (345 = all the features).

I've cleared by copy buffer and done it again and I get the same thing.

I've never even opened the attribute table of the WFS except after this to confirm the data was coming from it. Nor have I selected any of the WFS features. In fact the WFS didn't even connect properly (due to a bug in the WFS) and no WFS features have been rendered.

This is the WFS I added first:
http://si.icnf.pt:80/geoserver/BDG/atlas_bivalves_2007/wfs - and this was the error it came up with: https://github.com/qgis/QGIS/issues/31917

**Comment by gioman** [comment]
The pointed service works here, please provide another example. Regardless: the right place where to look/copy error messages is the log.

**Comment by jonathan-geoseer** [comment]
> Regardless: the right place where to look/copy error messages is the log.
I must humbly but strongly disagree that there is a "right" way. If the functionality is there then it should work. If you don't want folks copying those messages they shouldn't be selectable.

**Comment by gioman** [comment]
> I must humbly but strongly disagree that there is a "right" way. If the functionality is there then it should work. If you don't want folks copying those messages they shouldn't be selectable.

I don't think that the message bar was ever planned to be the proper place where to study in detail the error messages, but I can be wrong (at least to me does not seems so, as frequently the messages are too long to be displayed in the message bar, and moreover they do not stick).
