### ISSUE TITLE
QGIS browser fails to add WMS layers groups

### ISSUE THREAD

**Issue by jonathan-geoseer** [qgis/QGIS#31913]
3.4.12

This WMS:
http://atlas.marine.ie/arcgis/services/Fisheries/MapServer/WmsServer?

In the Browser panel:
* Double click WMS/WMTS. It opens with the list of WMS connections
* Double click whatever you named the service. It opens a list of layer groups
* Double click on "fisheries" (the only layer group). I **expect** it to open the group, which it does. But it also raises a CRITICAL error: "Invalid Layer: Raster layer provider is not valid". It shouldn't do this. I'm guessing this is a category layer, not a named layer.

(probably also true for other provider types in the Browser panel, not tested)

**Comment by gioman** [comment]
Adding WMS layers groups raises no error from the normal "Add WMS layers" dialog.

**Comment by Pedro-Murteira** [comment]
@jonathan-geoseer I can no longer replicate this bug on versions QGIS 3.16.14 and 3.22.1.
