### ISSUE TITLE
Coying messages in logs throws python error if python console is open

### ISSUE THREAD

**Issue by jonathan-geoseer** [qgis/QGIS#31914]
3.4.12
While reporting https://github.com/qgis/QGIS/issues/31913 - I selected the text of the error from the top error bar. This worked, But when I pressed `Ctrl-C` (copy), this raised a different error (and the content was *not* added to the copy buffer!).

`Python error: An error has occured while executing Python code. See log`.
It appears that QGIS is considering my `Ctrl-C` to try and copy the error as a `KeyboardInterrupt` for a Python script.

This makes it impossible to copy bugs/exceptions for issue reports.

**Edit**: This may have been because the Python Console was open but it doesn't have focus - the focus is on the selected error text.

**Comment by gioman** [comment]
> I pressed `Ctrl-C` (copy), this raised a different error (and the content was _not_ added to the copy buffer!).
> 
> `Python error: An error has occured while executing Python code. See log`.
> It appears that QGIS is considering my `Ctrl-C` to try and copy the error as a `KeyboardInterrupt` for a Python script.
> 
> This makes it impossible to copy bugs/exceptions for issue reports.

cannot confirm here on 3.4.12 on Linux.

> This makes it impossible to copy bugs/exceptions for issue reports.

the log seems to me the right place where to look/copy those messages.

**Comment by jonathan-geoseer** [comment]
> the log seems to me the right place where to look/copy those messages.
It also fails (same way) copying from the message log, hence "impossible". Sorry, I wasn't clear on that.

**Comment by gioman** [comment]
> It also fails (same way) copying from the message log, hence "impossible". Sorry, I wasn't clear on that.

@jonathan-geoseer I can copy without issues here in the log... it really seems a local issue... but I can check on Windows in the upcoming days...

**Comment by jonathan-geoseer** [comment]
@gioman - Just tested it on a different computer with Windows, and 3.4.3

To reproduce:
* Open Python console.
* Open message view
* Select any message on the message tab (I was using General this time), and Ctrl-C.

**Comment by gioman** [comment]
> To reproduce:

@jonathan-geoseer I edited the title to reflect exactly when the error shows

**Comment by DelazJ** [comment]
Confirmed here. I got in the message bar (hence also in the "log messages"
> Critical  Qt: QAction::event: Ambiguous shortcut overload: Ctrl+C

But afaict, this happens only when I select more than one row in the messages panel

**Comment by jonathan-geoseer** [comment]
I've not seen that text before. A different error? Maybe you're using a debug build? I see:

> 
> Traceback (most recent call last):
>   File "E:/__INST~1/QGIS3~1.4/apps/qgis/./python\console\console_output.py", line 306, in copy
>     raise KeyboardInterrupt
> KeyboardInterrupt

> this happens only when I select more than one row in the messages panel

For me this happens even if I try and copy a single character.

**Comment by DelazJ** [comment]
> Maybe you're using a debug build? 

Yes, I do
> For me this happens even if I try and copy a single character.

Actually it happens every other time. Trying two times the Ctrl+C throws the error (regardless what I select)

**Comment by alexbruy** [comment]
Duplicates #31955

**Comment by DelazJ** [comment]
@alexbruy is #31955 really a duplicate? From my understanding, that one is about the "message log" panel not being accessible when opened next to the "python console" while this report is about some keyboard shortcuts of the "message logs" not working as expected, in the same condition.

**Comment by alexbruy** [comment]
Hmm, my understanding was that when both message log and console are open, then pressing `Ctrl+C` in the message log does not copy selected message, but instead intercepted by console and considered and break signal.

But maybe I'm wrong.
