### ISSUE TITLE
"Refresh" on Browser

### ISSUE THREAD

**Issue by jonathan-geoseer** [qgis/QGIS#31912]
3.4.12

It would be nice if the Browser window had a "refresh" option when you right-click on a dataset (for example, a WMS connection). Currently it's necessary to "edit" the connection to get it to refresh.

**Comment by gioman** [comment]
Like this one?

![Screenshot_20190922_093249](https://user-images.githubusercontent.com/1951107/65384606-11dc8c00-dd1c-11e9-854e-d535477d748b.png)

**Comment by jonathan-geoseer** [comment]
Exactly like that, but on the right-click menu. In fact, thinking about it more, it would be good if the right click menu and the top menu were more consistent. Currently functionality is split between the two. On top of that current functionality on the top bar is mixed. Some buttons affect the select item (add, refresh), some affect everything (filter, collapse all).

**Comment by nyalldawson** [comment]
Most of the items DO have a refresh option. Can you please file individual requests for any you find which don't so that we can action them individually?
