### ISSUE TITLE
Label: text-buffer disappears with opacity less then 100%

### ISSUE THREAD

**Issue by tecbabel** [qgis/QGIS#31915]
Windows 10 64bit, tested with QGIS 3.8.2, 3.8.3. and 3.9.0

When applying a text-label to a polygon (might be any other geometry) an setting a text-buffer, the buffer shows as long as opacity is set to 100%. It disappear completely when slightly reducing opacity, say to 99.9% or 99%. See screenshots - 99% opacity (above) and 100% (below):
![Text_Buffer](https://user-images.githubusercontent.com/55049648/65373104-113ee980-dc79-11e9-949b-f11a6750bebd.jpg)

**Comment by gioman** [comment]
Cannot confirm here on the latest 3.4/ltr.

**Comment by tecbabel** [comment]
Problem still persists with QGIS 3.10.0 on Win. 10, tried on different computers and with different projects. So I guess it should be reproducable, at least under Windows. Can anyone confirm?
Text-Buffer only shows when opacity = 100%, but disappears completely for any other value (99.9%, 99%, 50%, 2% etc.). See screenshot:

![TextBuffer](https://user-images.githubusercontent.com/55049648/68545098-f3187e80-03c9-11ea-99b2-39462eefb85f.png)

**Comment by nyalldawson** [comment]
I can't reproduce. Can you share a project demonstrating this?

**Comment by tecbabel** [comment]
I tried to prepare the project above (screenshot) to share it - but surprisingly, now, reducing opacity works perfect. I know I had this problem before, thus it must be somehow reproducable, but only under certain conditions. Don't know yet what causes this problem - will come back when I find out more.

**Comment by nyalldawson** [comment]
Thanks! I played around a lot and couldn't find anyway to trigger this, so if you do work out the steps to reproduce please share!

**Comment by gioman** [comment]
> so if you do work out the steps to reproduce please share!

@tecbabel reopen if/when you find the way to replicate. Thanks.
