### ISSUE TITLE
WCS with bad certificate not handled correctly

### ISSUE THREAD

**Issue by jonathan-geoseer** [qgis/QGIS#31922]
3.4.12

Add this WCS:
https://ide.caceres.es/geoserver/Carto_Historica/1900/wcs

Try and connect to it. You'll get a "custom certificate configuration" dialog.

Click "Custom SSL  configuration" and tick every single box, then click the save button.

Now try and add the layer. Up pops the dialog again. This is **bug 1**. I've saved an exception for this certificate but it keeps popping this up every time. Shouldn't it remember my exception? I've also had this when connecting for to this service again after restarting QGIS.

Now press `Abort`. The dialog disappears and then reappears again. This is **bug 2**. I've had this happen a dozen plus times where it just keeps trying to load the layer and popping up the dialog. "Ignore" seems to work as expected, but "abort" does not.

**Comment by elpaso** [comment]
Can you disclose the operating system you were using?

**Comment by elpaso** [comment]
Cannot reproduce on master/linux

**Comment by gioman** [comment]
> Cannot reproduce on master/linux

I think it refers to this:

![Screenshot_20191007_095954](https://user-images.githubusercontent.com/1951107/66298578-ee077180-e8e9-11e9-8b23-96958311a254.png)

that shows up always on Windows (even when starting the program), now also on Windows 10. The only way to get rid of it is by selecting "save SSL exception" and then clicking "save and ignore". This happens on any QGIS installation on Windows, also on clean machines and it is very puzzling for normal users.

**Comment by elpaso** [comment]
That's what also happens on Linux. By clicking on "save SSL exception" and then clicking "save and ignore" it does not open again (which I suppose was the reported issue).

**Comment by gioman** [comment]
Beside the fact that I don't clealy understand why this happens (and if it  has a solution, especially when that dialog pop up on QGIS start) I think that "save and ignore" is a reasonable solution @jonathan-geoseer

**Comment by alexbruy** [comment]
Closed for the lack of feedback. Please reopen if necessary.
