### ISSUE TITLE
Icon for adding a WMTS is a database

### ISSUE THREAD

**Issue by jonathan-geoseer** [qgis/QGIS#31923]
3.4.12
Add a WMTS connection and connect to it.:
http://geoportal.eberswalde.de:8080/geoserver/gwc/service/wmts

Double click it to open a list of layers.
These layers all use the "database" icon. they should be showing something rastery.

**Comment by timlinux** [comment]
![image](https://user-images.githubusercontent.com/178003/70611962-f76ccd00-1bfd-11ea-8caa-a86efba0f15f.png)

Maybe we can show it is a folder with rasters in it like this:

![image](https://user-images.githubusercontent.com/178003/70612259-8843a880-1bfe-11ea-976f-d4b63de64772.png)

**Comment by timlinux** [comment]
Here is the svg of the icon above:
[wms-folder-icon.svg.zip](https://github.com/qgis/QGIS/files/3949762/wms-folder-icon.svg.zip)

**Comment by alexbruy** [comment]
Probably we can use existing WMS icon?

**Comment by Samweli** [comment]
@timlinux what do you think? is https://github.com/qgis/QGIS/blob/2dbc0d726f534167b24b74484ec07930cb1a3667/images/themes/default/mIconWms.svg ok?

**Comment by roya0045** [comment]
> @timlinux what do you think? is https://github.com/qgis/QGIS/blob/2dbc0d726f534167b24b74484ec07930cb1a3667/images/themes/default/mIconWms.svg ok?

I think something like that but with a clock or a fancy 't' in a bock or circle in the bottom corner.

**Comment by timlinux** [comment]
@roya0045 Maybe you are mixing up WMS-T (Time based WMS) with WMTS (Web Map Tile Service)? Damn OGC for such confusing acronyms :-P In this case we are talking about WMST and yes @alexbruy and @Samweli  existing WMS icon would be good.

@roya0045 BTW we should be bringing in support for WMS-T soon...

**Comment by roya0045** [comment]
@timlinux Ah you are right... why isn't it called TWMS (Tiled Web Map Service) instead?

In that case could we use the grid pattern symbol that we have, make it 4x4 and either 'detach' the lower 2*2 quarter or the four quarter in order to show subdivision/separations?
