### ISSUE TITLE
Crash on adding WMS

### ISSUE THREAD

**Issue by jonathan-geoseer** [qgis/QGIS#31927]
3.4.12 - Windows

1) Add this WMTS to your connections:
http://geoportal.eberswalde.de:8080/geoserver/gwc/service/wmts

2) (optional) restart qgis.

3) Double click the WMTS connection in the browser so that it connects. (this is the important part)

4) Add this WMS connection:
http://apps.siba.geosphere.fr/cgi-bin/mapserv.exe?map=C:/ms4w/geosphere/client1/Carte3_IA.map&amp;

5) now double click your new WMS connection. QGIS crashes 100% of the time repeatably for me when doing this (about 6 times so far to write this).

If you don't do step 3, then step 5 works absolutely fine. It's only when they're together it crashes.

**Comment by gioman** [comment]
Confirmed here on the same QGIS version on Linux.

**Comment by elpaso** [comment]
Confirmed on master too

**Comment by elpaso** [comment]
The root cause it a misconfiguration on the first server:

http://geoportal.eberswalde.de:8080/geoserver/gwc/service/wmts?REQUEST=GetCapabilities&SERVICE=WMS

all addresses pointing to localhost

It should not crash btw, working on it

**Comment by elpaso** [comment]
It seems like that the server is also broken because it has some layers with null style identifiers, according to the specifications: http://schemas.opengis.net/wmts/1.0/wmtsGetCapabilities_response.xsd this is not allowed.

It should not crash btw, still working on it

**Comment by elpaso** [comment]
For the record, to reprouce the issue was sufficient to:
- add the broken WMTS endpoint:
http://geoportal.eberswalde.de:8080/geoserver/gwc/service/wmts
- click on the item in the browser (to connect and download capabilities)
- click the browser refresh icon **twice**
