### ISSUE TITLE
warnings on start about missing grass plugin

### ISSUE THREAD

**Issue by jonathan-geoseer** [qgis/QGIS#31924]
I'm using a fresh install of 3.4.12 from qgis.org on Windows. I have absolutely zero plugins installed apart from whatever the default comes with.

I am running the "QGIS Desktop 3.4.12" link to start it, not the one with GRASS.

When i start it an error pops up at the top, which appear in the logs as:

> 
>      2019-09-21T15:56:26     WARNING    Failed to load E:/Software/QGIS3~1.4/apps/qgis-ltr/plugins/grassplugin7.dll (Reason: Cannot load library E:\Software\QGIS3~1.4\apps\qgis-ltr\plugins\grassplugin7.dll: The specified module could not be found.)
> 2019-09-21T15:56:26     WARNING    Failed to load E:/Software/QGIS3~1.4/apps/qgis-ltr/plugins/grassprovider7.dll (Reason: Cannot load library E:\Software\QGIS3~1.4\apps\qgis-ltr\plugins\grassprovider7.dll: The specified module could not be found.)
> 2019-09-21T15:56:26     WARNING    Failed to load E:/Software/QGIS3~1.4/apps/qgis-ltr/plugins/grassrasterprovider7.dll (Reason: Cannot load library E:\Software\QGIS3~1.4\apps\qgis-ltr\plugins\grassrasterprovider7.dll: The specified module could not be found.)

I'm assuming this is because I didn't use the GRASS link. However from an end user perspective this shouldn't be raising Warnings - I don't want the GRASS stuff or I'd have asked for it. The links should load with zero errors or warnings.

**Comment by alexbruy** [comment]
This is by design. If QGIS started without GRASS support, no GRASS libraries will be loaded.

**Comment by jonathan-geoseer** [comment]
And that's fine. But I'd suggest this is still a bug because:
I did not run the QGIS with GRASS, and therefore I should NOT be getting a big scary user-interface message suggesting my installation is broken (which it's not). 
Given that I put it to you that this is a UI bug.

**Comment by roya0045** [comment]
If the plugin was active then this seems fine to show that the plugin cannot be activated and is adequate.

**Comment by alexbruy** [comment]
> I should NOT be getting a big scary user-interface message suggesting my installation is broken.

And you don't get such message. The only user-visible feedback is a warning in the message log.
