### ISSUE TITLE
[mesh] Add time selection widget to Absolute time selector

### ISSUE THREAD

**Issue by pcav** [qgis/QGIS#31934]
In the Mesh Absolute time panel, the time widget only allows setup of day, not time.

**Comment by PeterPetrik** [comment]
@pcav what do you mean by "setup of time"?

**Comment by pcav** [comment]
The user should be able to set up the time of start of the temporal sequence.

**Comment by saberraz** [comment]
The **Reference date/time** should do this. I am closing this ticket, feel free to open with some example data and description of what needs to be achieved.
![Uploading image.png…]()
