### ISSUE TITLE
Color problem in the legend

### ISSUE THREAD

**Issue by SunJian31** [qgis/QGIS#31949]
Hi, 

sorry for my bad english.
I have a problem in the map. The blue color in the properties are good but it doesn't appear correctly on the legend in the final map (the blue color called "scénario moyen"). I don't know how to solve it.

I join a copy of my screen.

Thanks for helping me.

![bug](https://user-images.githubusercontent.com/55685844/65408817-97c50980-dde6-11e9-9795-9642452df721.JPG)

**Comment by gioman** [comment]
>  The blue color in the properties are good but it doesn't appear correctly on the legend in the final map (the blue color called "scénario moyen").

@SunJian31 
how so? can you explain better?

**Comment by SunJian31** [comment]
I'll try.
I mean, it is not the same blue on the legend and on the properties for the same object. It doesnt' match. 
I surrounded in red the problem :
![bug](https://user-images.githubusercontent.com/55685844/65409325-ba0b5700-dde7-11e9-8b62-0ee52f83b5c7.JPG)

**Comment by gioman** [comment]
>  I mean, it is not the same blue on the legend and on the properties for the same object. It doesnt' match.

can you attach a sample project (with sample data)?

**Comment by SunJian31** [comment]
I just solved the problem.
It was because the layer was not 100% opacity, not in the general opacity but in a sub menu.... so I didn't see it before a meticulous research.
So sorry to waste your time guys.
Have a good day !

**Comment by kannes** [comment]
Thanks for coming back and describing what the problem was. While I am not a developer, I would say that excuses you from all "sorry"s :)

**Comment by DelazJ** [comment]
Thanks @SunJian31 
This makes me wonder if the legend should not reflect also the opacity applied to the class symbol. Should I open a feature request or does it not make sense?

**Comment by nyalldawson** [comment]
@Delazj it already does

**Comment by DelazJ** [comment]
@nyalldawson Good to know. In 3.10 or earlier (@SunJian31 did not mention the version he's using)?

**Comment by nyalldawson** [comment]
In 2.2 or earlier I think :p

**Comment by SunJian31** [comment]
I use 3.4 !

**Comment by DelazJ** [comment]
> In 2.2 or earlier I think :p

Ouch! Indeed!

> I use 3.4 !

Weird. Tried on 3.4.12 and 3.9 and could not reproduce. Likely some local and temporary issue?

**Comment by SunJian31** [comment]
You mean it is supposed to appear in light blue also in the properties (in right red box on y screen) instead of being normal ?

**Comment by DelazJ** [comment]
All the colors should display as configured in the layer's properties dialog. So yes, light blue if you played with the opacity property.

**Comment by SunJian31** [comment]
Ah ok. I don't know why it doesn't apply.
I tried on my old version 2.14 and it is exactly the same. Maybe it is local issue as you said.

**Comment by jmonticolo** [comment]
Following [this post](https://gis.stackexchange.com/questions/424864/qgis-legend-patches-do-not-honor-opacity) on GIS SE I tried to repoduce this bug on QGIS 3.22.3 on Windows 10, here is a GIF to show how :

![qgis_issue_31949](https://user-images.githubusercontent.com/20857031/156234077-5d4324f4-6d73-4a30-843c-1bfe872fd085.gif)

**Comment by jmonticolo** [comment]
@DelazJ, @gioman : can we re-open this one ?

**Comment by gioman** [comment]
> @DelazJ, @gioman : can we re-open this one ?

@jmonticolo it seems to be still true but only for rasters, I think is better to file a new ticket.
