### ISSUE TITLE
"Log Messages" shortcut is broken if "Python console" is enabled

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#31955]
While trying to replicate https://github.com/qgis/QGIS/issues/31914#issuecomment-534017343 I came across an issue that was previously reported but closed during 2 to 3 migration (#22127)
1. Open the "Log messages" panel. Do not anchor it in the dialog (keep it floating)
1. Open the Python Console. It will likely be added to the same tab as the Message log. So far so good
1. Go to the "Python Console". It comes foreground and you no longer see the tabs title. So no way to click on the other tab to reactivate it.
1. Try also to enable the "log messages" panel using the tooltip button on the status bar. Nothing!
If you however go the "View --> Panels -->" route then the "log messages" tab is back.

3.9 766db97 on Windows 10 but it is also the case in 3.4.12

**Comment by BergWerkGIS** [comment]
Just came across this issue as well. 
`QGIS@3.12.0` on Linux and Windows.

* `Plugins -> Python Console`
* `View -> Panels -> Log Messages`
  ![image](https://user-images.githubusercontent.com/4549888/75777728-c57b8a80-5d56-11ea-8363-b1b736dbf816.png)
* click on `Log Messages` tab, still good
  ![image](https://user-images.githubusercontent.com/4549888/75777943-358a1080-5d57-11ea-8f2d-9ed68bd7b8fc.png)
* click on `Python Console` tab, both tabs are gone and Python console has taken over
  ![image](https://user-images.githubusercontent.com/4549888/75778014-5488a280-5d57-11ea-95e8-54da3c8b72f2.png)
  * only way to get `Log Messages` panel back is via `View -> Panels -> Log Messages`
  * `Messages` button ![image](https://user-images.githubusercontent.com/4549888/75778475-2c4d7380-5d58-11ea-929b-9af1eb49a534.png) does not work
