### ISSUE TITLE
Features and vertices can't be deleted with "del" key when Rule-based styling or Rule-based labelling panels are active

### ISSUE THREAD

**Issue by mstuyts** [qgis/QGIS#31958]
I noticed something very similar to this older, closed bug report (#23888), but now in QGIS 3.8.3 and QGIS 3.9.0.  I have tested it on Windows 10 (installed using OSGeo4W) and on Ubuntu 18.04.3 and both give the same results.

---

**How to reproduce**

1. Create a new QGIS project
2. Create a polygon layer (I tested it with both Geopackage and PostGIS: same results)
3. Create some test polygons inside that layer
4. Create a Rule-based styling in the Layer Styling panel.
5. Make sure the Symbology tab is active in the Layer Styling Panel
6. Click in the Layer Styling Panel somewhere below the rules to make sure none of the rules is selected.
7. Make sure your layer is editable and select a vertex
8. Press the delete button on your keyboard =>**result: the selected vertex is not deleted**
9. In the Layer Styling Panel select any of the none Rule-Based tabs, like 3D View for example.
10. Select a vertex
11. Press the delete button on your keyboard  =>**result: the selected vertex is deleted**
12. In the Layer Styling Panel go back to the Symbology tab.
13. Select one of the polygons in your layer.
14. Press the delete button on your keyboard  =>**result: the selected polygon is not deleted**
15. In the Layer Styling Panel select any of the none Rule-Based tabs, like 3D View for example.
16. Select a polygon
17. Press the delete button on your keyboard  =>**result: the selected polygon is deleted**

The same happens when Rule-based labeling is used and the Rule-based labeling tab is active when pressing the delete button.

If in step 6 one of the rules is selected, pressing the delete button, will delete the rule instead of the selected vertex, even if a vertex or polygon was selected last.

When in step 14 the Toolbar button 'Delete Selected' is used instead of the keyboard delete button, the polygon is deleted, even if a vertex or polygon was selected last.

I get similar results with point and polyline layers.

---

**Actual behavior**

* When the Symbology tab is active in the Layer Styling Panel with Rule-based styling and a vertex or a polygon is selected in the map and the keyboard Delete button is pressed, QGIS tries to delete a symbol rule, no matter what was selected last (a symbol rule, a label rule, a vertex or a polygon).
* When the Labels tab is active in the Layer Styling Panel with Rule-based labeling and a vertex or a polygon is selected in the map and the keyboard Delete button is pressed, QGIS tries to delete a label rule, no matter what was selected last (a symbol rule, a label rule, a vertex or a polygon).

**Expected behavior**

* The last selected (a symbol rule, a label rule, a vertex or a polygon) item is deleted when the keyboard Delete button is pressed.

---

**Sample project and data**

[rulebased-delete.zip](https://github.com/qgis/QGIS/files/3642054/rulebased-delete.zip)

**Comment by nyalldawson** [comment]
Fixed in recent versions
