### ISSUE TITLE
label backgound transparency is not saved in the project file

### ISSUE THREAD

**Issue by Amphibitus** [qgis/QGIS#31953]
if I save my project and open it again the Text Background opacity (Deckkraft)  is 0 

QGIS 3.8.3 Geman Version Windows 10

![grafik](https://user-images.githubusercontent.com/7237786/65415062-42dcbf80-ddf5-11e9-8b1a-c706dd2877e5.png)

**Comment by gioman** [comment]
@Amphibitus works as expected here, please attach a sample project+data.

**Comment by alexbruy** [comment]
Closed for the lack of feedback. Please reopen if necessary.
