### ISSUE TITLE
"Point" input not working in Processing Modeller?

### ISSUE THREAD

**Issue by josephholler** [qgis/QGIS#31969]
the 'point' input type for Graphic Models / Processing Modeler is not functioning.  The button for the point field appears with the symbol: â€| and when clicked, minimizes the algorithm dialogue to allow the user to interactively click a point on the map canvas, but nothing happens when I do so. The algorithm will not run unless I type in a coordinate pair.
I'm fairly certain older versions of QGIS allowed a point to be entered with a click on the map canvas?
QGIS version 3.8.2 in Windows 10

**Comment by gioman** [comment]
@josephholler please try on QGIS master.

**Comment by josephholler** [comment]
Just tried on the latest nightly build and found the same result. The QGIS version details are below:

QGIS version | 3.9.0-Master | QGIS code revision | ea7b27ef3e
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.0dev | Running against GDAL/OGR | 3.1.0dev
Compiled against GEOS | 3.7.2-CAPI-1.11.0 | Running against GEOS | 3.7.2-CAPI-1.11.0 b55d2125
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 10.8 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 7.0.0 | Running against PROJ | Rel. 7.0.0, March 1st, 2020
OS Version | Windows 10 (10.0) | This copy of QGIS writes debugging output.

**Comment by gioman** [comment]
> Just tried on the latest nightly build and found the same result. The QGIS version details are below:

can you please attach a sample project/model/data?

**Comment by josephholler** [comment]
The sample is sad... just trying to get any functionality out of the point input type. The point input also does not appear as a parameter in expression builder, so I attempted to write in `@singlepoint` or `parameter('singlepoint')`, with `null` results. All other geometry input types I have been experimenting with create a variable names available in the formula editor/expression builder.

Attached a qgz, model3, and geopackage with polygons for testing. 

I wish I could provide more information, but I've had no success using the point input in the model or selecting the point on the map canvas. I'm fairly certain I that I used the point input in earlier QGIS versions for finding distances from features in one layer to a dynamically clicked point on the map.

[testPointInput.zip](https://github.com/qgis/QGIS/files/3649027/testPointInput.zip)

**Comment by nyalldawson** [comment]
Just to clarify -- it's only in the modeler where the clicking on canvas behavior doesn't work, right? It works ok when you actually run the model from the toolbox?

**Comment by gioman** [comment]
@josephholler please leave feedback.

**Comment by nyalldawson** [comment]
Closing due to lack of feedback

**Comment by josephholler** [comment]
Just had a chance to get back to this, now with QGIS version 3.10.1.
I can confirm that the point input DOES work if the model is added to the Toolbox and run from the toolbox.
The point input DOES NOT work if the model is run from the graphic modeller editing GUI using the Run Model (F5) green play button.

**Comment by kannes** [comment]
There was feedback here after the issue was closed, is this still happening @josephholler?

**Comment by josephholler** [comment]
Thanks for following up.  I do not know and since writing this bug report, I have moved away from teaching QGIS graphic modeller in favor of python & R.

**Comment by karsonkevin2** [comment]
> There was feedback here after the issue was closed, is this still happening @josephholler?

Issue still occurs in QGIS v 3.20.2.

When running a model using a point input from the Model Designer, the dialog box is minimized, but attempting to click on the map does nothing.

Running a model with point input from the Processing Toolbox works as intended.

**Comment by gioman** [comment]
> Issue still occurs in QGIS v 3.20.2.

@karsonkevin2 which is unsupported, can you test 3.22.2? thanks.

**Comment by karsonkevin2** [comment]
> > Issue still occurs in QGIS v 3.20.2.
> 
> @karsonkevin2 which is unsupported, can you test 3.22.2? thanks.

Issue is still there in 3.22.2

**Comment by gioman** [comment]
@nyalldawson @alexbruy  should we reopen this?

**Comment by kannes** [comment]
I admit I did not test this again but I looked at the commits for "point" and saw nothing that suggests that it was fixed. So I assume it is still not working. If it was fixed I own cookies or a beer to the developer.

**Comment by kannes** [comment]
I can confirm it being like this in dd6e83b2fa6 (recent master).

When clicking the [...] button of the model GUI launched from the model builder, the dialog flashes off and on again briefly (I think, sometimes it does not do anything noticable) and that's it.
