### ISSUE TITLE
Snapping map units always show "meters even when the project is in different units

### ISSUE THREAD

**Issue by SrNetoChan** [qgis/QGIS#31961]
**Describe the bug**

On the snapping toolbar, you have to ways of setting the snapping tolerance "pixels" and map units. The "map units" option should show the actual units, but it seems to always show the units as "meters" even if the project units are, for example "degrees". Moreover, the actual snapping accurs using the project units and not meters.

**How to Reproduce**

1. Open a new project and set the projection to 4326
2. Add a new temporary layer in 4326
3. Enable snapping and you will see that besides pixels the other option is meters.
4. keep the tolerance as 12
4. Try digiting something and you will see the snapping accurs at 12 degrees, and not 12 meters.

![image](https://user-images.githubusercontent.com/3607161/65432057-7548e580-de12-11e9-9eed-6fec6b1c54eb.png)

**QGIS and OS versions**

QGIS version | 3.9.0-Master | QGIS code revision | cebdc8dded
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.6.2-CAPI-1.10.2 4d2925d6
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 11.5 (Ubuntu 11.5-1.pgdg18.04+1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Ubuntu 18.04.3 LTS

**Additional context**

**Comment by elpaso** [comment]
@SrNetoChan looking to the implementation, what is shown as map unit is actually the `mProject->distanceUnits()` which is defined in the project settings and not the map canvas CRS units.

I feel this is a real bug.

**Comment by SrNetoChan** [comment]
@elpaso in that case, there are more bugs involved.

Changing the distance units (for example to feet) in the project only changes tolerance combobox in the advanced mode. For "current layer" and "All layers" mode it always shows meters.

![Peek 2019-09-26 09-52](https://user-images.githubusercontent.com/3607161/65673879-917f9900-e043-11e9-83bd-a8394894c496.gif)

Nevertheless, the snapping in all modes occur at the project units and not at the defined measurement units, which makes sense to me. So, unless there was lots of code to make the snapping work with the measuring units already, simply making sure that the project units is show would be enough. (Or go back to just showing the string "Map units").

**Comment by elpaso** [comment]
I think the issue here is just at the GUI level: the dialog is constructed when QGIS starts and the map canvas units are unknown, for this reason (maybe) the units are read from the project settings (but those are not the units used in the canvas), I think that what we need to do here is synchronize the combo item text with the actual canvas units as soon as they change.

**Comment by SrNetoChan** [comment]
I fully agree! Thanks for looking into this.

**Comment by elpaso** [comment]
@3nids can you confirm that it is just a matter of updating the GUI of the snapping dialog when the canvas CRS (project CRS) changes? 

I see that currently the code gets the units from project's setting "Units for distance measurement" and ignores any following CRS change, I can fix it but I'd like to be sure that I am not missing something here.

**Comment by elpaso** [comment]
@SrNetoChan what about this?

![snapping-units](https://user-images.githubusercontent.com/142164/65680346-0d371100-e057-11e9-89be-96cccbcf7095.gif)

**Comment by SrNetoChan** [comment]
@elpaso SOLD! For me, assuming that @3nids has no other comment, it's all that is needed.

**Comment by 3nids** [comment]
this makes sense to me, I don't recall for sure, but this looks correct.

**Comment by SrNetoChan** [comment]
I have tested it and it seems to be working well. Thanks @elpaso

**Comment by elpaso** [comment]
Thank you both for reviewing this!

**Comment by elpaso** [comment]
@SrNetoChan do you have a chance to check if this is also an issue for 3.4?

**Comment by SrNetoChan** [comment]
@elpaso it was. I found it there. Forgot to mention on the Ticket. So backporting will be appreciated.
