### ISSUE TITLE
QGIS 3.8.2 QgsTask based object crash qgis when running

### ISSUE THREAD

**Issue by jdejesus517** [qgis/QGIS#31964]
## User Feedback

I subclassed QgsTask in order to process jobs that make class to a postgres database outputs the data as a kmz or shapefile. When I execute the run method directly, everything works fine albeit it blocks the main thread.

~~~
         task = CbydTask(job_queue, context, output_dir)
         task.run()
~~~
If I kick off a bunch of them and send them to the task manager for processing, many of them will finish but eventually and very randomly QGIS will crash. It will crash either two or three jobs in. Or almost at the end of all the jobs. It is not consistent on which jobs it fails on and all jobs will process correctly when just doing `task.run()`.
~~~
        manager = QgsApplication.taskManager()
        for job in job_queue:
            manager.addTask(CbydJobTask(job, context, output_dir))
~~~
When I opened visual studio to try and get deeper debug info, I saw messages like

`Unhandled exception at 0x00007FFBE9DCB049 (ntdll.dll) in qgis-bin.exe: 0xC0000374: A heap has been corrupted (parameters: 0x00007FFBE9E327F0).`

and

`0x00007FFB959DF1F6 (QtCore.pyd) in qgis-bin.exe: 0xC0000005: Access violation reading location 0x0000000000000000.`

None of the objects referenced in the QgsTask class references the UI in any way nor attempts to communicate with the main thread other than the normal signals between the task and the task manager.

The class definition is below:

~~~
class CbydJobTask(QgsTask):

    def __init__(self, job, context, output_dir):
        QgsTask.__init__(self, '811 Export Job ' + str(job.get_id()))
        """Constructor."""
        
        self.job = job
        self.context = context
        self.output_dir = output_dir

    def run(self):
        """Start the job-building/validation routine."""
        
        self.setProgress(0)
        if self.isCanceled():
            return False
        if self.context['kmz']:
            self.job.set_strategy(CbydKmzStrategy())
            self.job.process(self.output_dir)
            
        if self.isCanceled():
            return False
            
        if self.context['shp']:
            if self.job.is_buffered():
                self.job.set_strategy(CbydBufferedShpStrategy())
            else:
                self.job.set_strategy(CbydShpStrategy())
            self.job.process(self.output_dir)
            
        if self.isCanceled():
            return False

        if self.context['utilisphere']:
            self.job.set_strategy(CbydBufferedShpUtilisphereStrategy())
            self.job.process(self.output_dir)
            
        self.setProgress(1)
                
        return True
~~~

## Report Details

*Crash ID*: f0a1510016bda7570a611a9552d7d04e8a7599b5

*Stack Trace*
<pre>
PyInit_QtCore :
PyInit_QtCore :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
DispatchMessageW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.8.2-Zanzibar
QGIS code revision: 4470baa1a3
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by elpaso** [comment]
Did you try to keep a reference to `CbydJobTask(job, context, output_dir)` ?
Try storing them into a python array right before passing them to the task manager.

**Comment by nyalldawson** [comment]
Without seeing the definition of "job" it's impossible to assist.

My suspicion is that somewhere in your code you are calling a method which is not thread safe.

Best to open a thread about this on gis.stackexchange.com, as it's not an issue in qgis itself.

**Comment by jdejesus517** [comment]
job.process() just delegates to the strategy class's build() function. If there is one that may not have something thread safe in it, I guess it could be this one. I will open up a thread on stack exchange. But if where I messed up is glaringly obvious, please let me know.

~~~
class CbydShpStrategy(CbydAbstractStrategy):
                
    SPATIAL_QUERY = #QUERY REMOVED FOR EXAMPLE
    DATA_QUERY = #QUERY REMOVED FOR EXAMPLE
                    
    def _prepare_output_path(self, output_dir, company, state, code):
        
        output_path = os.path.join(output_dir, company, state, code, 'SHAPE')
        if not os.path.isdir(output_path):
            os.makedirs(output_path)
            
        return output_path

    def build(self, id, output_dir):

        data = None
        with psycopg2.connect(DSN_ODW_RW, cursor_factory=RealDictCursor) as connection:
            with connection.cursor() as cursor:
                cursor.execute(self.DATA_QUERY, (id,))
                data = cursor.fetchone()
                
        output_path = self._prepare_output_path(output_dir, data['company'], data['state'], data['code'])
        
        layer = QgsVectorLayer('MultiLineString?crs=epsg:'+
                               data['output_coord_system']+
                               '&field=ductbankid:integer',data['code_type'],'memory')
        provider = layer.dataProvider()
        fields = layer.fields()
            
        spatial_data = None
        with psycopg2.connect(DSN_ODW_RW, cursor_factory=RealDictCursor) as connection:
            with connection.cursor() as cursor:
                cursor.execute(self.SPATIAL_QUERY, (data['output_coord_system'], data['state'], data['code']))
                spatial_data = cursor.fetchall()
        
        features = []      
        for conduit in spatial_data:
            q = QgsFeature(fields)
            q['ductbankid'] = conduit['ductbankid']
            q.setGeometry(QgsGeometry.fromWkt(conduit['wkt_text']))
            features.append(q)
            
        provider.addFeatures(features)
        QgsVectorFileWriter.writeAsVectorFormat(
            layer,
            os.path.join(output_path, data['file_name_shp']),
            'utf-8',
            driverName='ESRI Shapefile'
        )
~~~

**Comment by nyalldawson** [comment]
I can't see anything obvious. Is this only an issue when you run the task multiple times?

**Comment by jdejesus517** [comment]
If I am using any of the shapefile based output strategies, then it fails randomly. Some of them succeed, eventually one of them kills everything. The KMZ output strategy just uses a custom library I made that builds a kml document with QtXml libraries and then zips them.

I have a version of the task that took in a list of jobs and iterated through the list and processed them. Sometime it would fail early, sometimes it would almost be done and fail. The version here up top is one task per job on which occasionally one of the shapefile based jobs fails and crashed QGIS.

I was able to capture this error only once when the program didn't quite completely crash or at least crashed after a logging mechanism I have was able to capture this.

~~~
Traceback (most recent call last):                                                                                                                       
   File "C:/Users/jdejesus/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\CrownCastleFiberPlugin\functions\cbyd\cbyd.py", line 48, in run     
     self.job.process(self.output_dir)                                                                                                                    
   File "C:/Users/jdejesus/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\CrownCastleFiberPlugin\functions\cbyd\cbyd.py", line 562, in process
     self._strategy.build(self._id, output_dir)                                                                                                           
   File "C:/Users/jdejesus/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\CrownCastleFiberPlugin\functions\cbyd\cbyd.py", line 822, in build  
     provider.addFeatures(features)                                                                                                                       
 RuntimeError: wrapped C/C++ object of type QgsVectorDataProvider has been deleted
~~~

I'm not sure how it is possible for the data provider object to get deleted before the end of the function. I hold a proper reference to it and the layer. And each job gets its own strategy object so the strategies aren't shared at all and they ran sequentially in the old version of the task. I even implemented using QThread and still crash on the ones involving layers and shapefiles.

~~~
class WorkerThread(QThread):
    
    def __init__(self, job, context, output_dir, parent=None):
        super().__init__(parent)
        """Constructor."""
        
        self.job = job
        self.context = context
        self.output_dir = output_dir

    def run(self):
        """Start the job-building/validation routine."""
        
        if self.context['kmz']:
            self.job.set_strategy(CbydKmzStrategy())
            self.job.process(self.output_dir)
            
        if self.context['shp']:
            if self.job.is_buffered():
                self.job.set_strategy(CbydBufferedShpStrategy())
            else:
                self.job.set_strategy(CbydShpStrategy())
            self.job.process(self.output_dir)

        if self.context['utilisphere']:
            self.job.set_strategy(CbydBufferedShpUtilisphereStrategy())
            self.job.process(self.output_dir)


class ThreadManager(QObject):
    
    worker_finished = pyqtSignal()
    
    def __init__(self, progress_bar, parent=None):
        super().__init__()
        """Constructor."""
    
        self.threads = []
        self.current_worker = None
        self.workers_added = 0
        self.workers_finished = 0
        self.progress_bar = progress_bar
    
    def on_worker_finished(self):
        
        if len(self.threads) == 0:
            self.current_worker = None
        else:
            self.activate_worker()
            
        self.workers_finished += 1
        
        self.progress_bar.setRange(0, self.workers_added)
        self.progress_bar.setValue(self.workers_finished)
            
    def activate_worker(self):
        
        self.current_worker = self.threads.pop(0)
        self.current_worker.finished.connect(self.current_worker.deleteLater)
        self.current_worker.finished.connect(self.on_worker_finished)
        self.current_worker.start()
    
    def add_worker(self, worker):
        
        self.threads.append(worker)
        self.workers_added += 1
        
        if self.current_worker is None:
            self.activate_worker()
~~~

The above is invoked using:

~~~
        for job in job_queue:
            self.thread_manager.add_worker(WorkerThread(job, context, output_dir))
~~~
