### ISSUE TITLE
Please update to EPSG Dataset ver 9.8 (2019-09-17 ) #150

### ISSUE THREAD

**Issue by thangqd** [qgis/QGIS#31976]
Could epsg.io team please update the latest EPSG Dataset ver 9.8 (2019 - 09 - 17) in the next QGIS version?Thanks
http://www.epsg.org/EPSGDataset/Whatisnew.aspx

**Comment by nyalldawson** [comment]
That's done in the PROJ library, not QGIS.

See https://github.com/OSGeo/PROJ/pull/1633
