### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by basilis29** [qgis/QGIS#31985]
This problem began when i had version 2.18 and was working perfectly, until some day the program did not start. Then i  uninstalled it and install new versions such us Madeira and Zanzibar.
I install Qgis Madeira or Zanzibar  and there is not desktop icon neither in program file folder to run it.

**Comment by roya0045** [comment]
More information is required. OS? Installation method? etc.

**Comment by basilis29** [comment]
I download this setup (QGIS-OSGeo4W-3.4.12-1-Setup-x86_64). I run the setup normaly and when is finished there is not dekstop icon neither in the program files folder.

**Comment by basilis29** [comment]
![Χωρίς τίτλο](https://user-images.githubusercontent.com/55754132/65531633-01d2d100-df03-11e9-9487-d30473146b64.png)

**Comment by gioman** [comment]
binaries are in "apps", shortcuts are in "bin".

**Comment by basilis29** [comment]
Error message :Could not load qgis_app.dll

**Comment by jef-n** [comment]
Check `postinstall.log`

**Comment by SIGISLV** [comment]
I have the same problem and as @jef-n suggest I couldn't find the `postinstall.log` I searched in the `etc/postinstall` there is no `postinstall.log` file. 
To describe my context : I Install the last version of Qgis (3.10) and it get the error on start up of qgis (windows 7). The error message said it couldn't find the `qgis_app.dll`. I checked in the `c:/osgeo4w/apps/qgis/bin` the `qgis_app.dll` is here.

**Comment by jef-n** [comment]
@SIGSLV the `postinstall.log` is in the top directory (see screenshot above) - unless you are not using the standalone installer.  With `osgeo4w-setup` it's in `var/log/setup.log` or `var/log/setup.log.full`.    https://github.com/qgis/QGIS/issues/26891#issuecomment-495889169 might also help with diagnosing the `qgis_app.dll` problem.

**Comment by roya0045** [comment]
I might recall wrongly but the qgis_app.dll error does not only occur when qgis cannot find this dependencies but also any other dependency during startup.
Some environment variable might be missing and prevent the program from finding things in general.

**Comment by SIGISLV** [comment]
I solve my problem since I have update the driver for my graphic card (in the properties of the graphic card update driver). Also I noticed that the osgeo4w has a package to update the OpenCL.dll. Some of my collegue who has the same problem was fix with this osgeo4w update.

**Comment by aborruso** [comment]
I have solved using the last OSGeo installer

**Comment by gioman** [comment]
@basilis29 closing for lack of feedback.
