### ISSUE TITLE
QGIS Crashed

### ISSUE THREAD

**Issue by glmodica** [qgis/QGIS#31987]
h2. User Feedback

Been trying to launch QGIS and it constantly crashes

h2. Report Details

*Crash ID*: 9dd447e8923a898061d2ea6718b134d43fc7e2b3

*Stack Trace*
<pre>
QList<QItemSelectionRange>::size :
QgsMessageBar::pushMessage :
QgsMessageBar::pushInfo :
QgisApp::showSystemNotification :
QgisApp::authMessageOut :
QMetaObject::activate :
QgsAuthManager::messageOut :
QgsAuthManager::authDatabaseConnection :
QgsAuthManager::sslCertCustomConfigByHost :
QgsNetworkAccessManager::createRequest :
QNetworkAccessManager::get :
QgsVectorLayerLoadStyleDialog::updateLoadButtonState :
QgsVectorLayerLoadStyleDialog::updateLoadButtonState :
QgisApp::QgisApp :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.4.4-Madeira
QGIS code revision: commit:73c31df831
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.0
Running against GDAL: 2.4.0

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by nyalldawson** [comment]
This issue has already been fixed - please upgrade to a newer qgis release
