### ISSUE TITLE
Umpteenth crash of Qgis 3.X

### ISSUE THREAD

**Issue by HerrBatz** [qgis/QGIS#31989]
## User Feedback

I was pissed off

## Report Details

*Crash ID*: 87026061338cf3642d5384d839eec65b4bd34835

*Stack Trace*
<pre>
QgsMapCanvas::setMapTool qgsmapcanvas.cpp:1722
QgisApp::activateDeactivateLayerRelatedActions qgisapp.cpp:12746
QgisApp::layerEditStateChanged qgisapp.cpp:12547
QMetaObject::activate :
QgsVectorLayer::commitChanges qgsvectorlayer.cpp:3024
QgisApp::toggleEditing qgisapp.cpp:9536
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:403
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:403
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QMenu::exec :
QgsLayerTreeView::contextMenuEvent qgslayertreeview.cpp:136
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:403
QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:403
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1567
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.8.2-Zanzibar
QGIS code revision: 4470baa1a3
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by roya0045** [comment]
What were you doing when the crash occurred?

**Comment by HerrBatz** [comment]
This time: setting transparancies to a georeferenced raster layer.

[X]

Mit freundlichen Grüßen

i. A. Stefan Grallert





MTR Main-Taunus-Recycling GmbH

Stefan Grallert

Baumaßnahmen Liegenschaften EDV

Rhein-Main-Deponiepark 1

65439 Flörsheim-Wicker



Telefon: 06145 9260-1014

Telefax: 06145 9260-2014

E-Mail: projekte@deponiepark.de

Internet: www.deponiepark.de



Aufsichtsratvorsitzende: Kreisbeigeordnete Madlen Overdick

Geschäftsführer: Heino von Winning und Dr. Mathias Bausback

Gesellschafter: RMD Rhein-Main Deponie GmbH, Stadt Flörsheim am Main, Stadt Hochheim am Main

Eingetragen im Handelsregister Wiesbaden HRB 18219 Steuernummer: 043 225 71946 USt-Id-Nr. DE 113 866 770



Sofern nicht anders angegeben, ist diese E-Mail und alle Anlagen vertraulich und nur für den Empfänger bestimmt.

Falls Sie diese E-Mail irrtümlich empfangen haben, bitten wir Sie uns den Empfang mitzuteilen und die E-Mail zu löschen.

Die Internet-Kommunikation ist nicht sicher, die MTR Main-Taunus-Recycling GmbH, Angestellte oder

Geschäftspartner können nicht für den Missbrauch von Dritten verantwortlich gemacht werden.

Meinungen, die in dieser E-Mail ausgedrückt werden, reflektieren nicht notwendigerweise die Ansicht der

MTR Main-Taunus-Recycling GmbH.
________________________________
Von: Alex [notifications@github.com]
Gesendet: Dienstag, 24. September 2019 21:45
An: qgis/QGIS
Cc: Grallert, Stefan; Author
Betreff: Re: [qgis/QGIS] Umpteenth crash of Qgis 3.X (#31989)


What were you doing when the crash occurred?

**Comment by gioman** [comment]
Things to try:

try QGIS master, as it contains all the latest and greatest bug fixes

try with a new/clean QGIS profile (no 3rd party plugins installed)

**Comment by gioman** [comment]
Closing for the lack of feedback.
