### ISSUE TITLE
raster_values vs Point sampling tool

### ISSUE THREAD

**Issue by cesarcorreo** [qgis/QGIS#31997]
**Describe the bug**
I'm using raster_values from field calculator to assign height values from a  Tiff (3Gb) to a point (1.000.000 points). It takes more than 2 hours to perform only 25 % of the work and I stopped it.
Using the plugin point sampling tool with the same files only takes around 5 minutes for the full operation. 

**How to Reproduce**

Point file is from OSM but I cannot share the tiff file. 

**QGIS and OS versions**
QGIS 3.8.3 (last version)

**Comment by roya0045** [comment]
What about "Sample raster values" in Raster analysis?

**Comment by nyalldawson** [comment]
I'd be keen to see sample data -- are you able to email?

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
