### ISSUE TITLE
Decrease the number of round-trips to postgres servers when connecting using the Data source manager

### ISSUE THREAD

**Issue by palmerj** [qgis/QGIS#32002]
**Feature description.**
We are testing if it's feasible for desktop clients to connect to large PostgreSQL database over the WAN. Our current database has over 2000 tables, of which 1100 have a PostGIS column. The average WAN response time from the QGIS desktop client to the PostgreSQL server is 35ms. Bandwidth is not a major issue in this case.

When connecting via PostgreSQL connections in the Data source manager (using the "Also list tables with no geometry", "User estimated table metadata" options) it takes about 1.5mins to fully populate the dialog. We have tested multiple configurations but have not found any of the options any faster for our use cases. This 1.5min process runs over 5000 SQL queries, and with the 35ms latency that's why the process takes so long. The top queries by volume are:

| calls | rows  | query                                                                                                                                                                                               |
|-------|-------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 3089  | 496  | select description from pg_catalog.pg_description where objoid = $1 and objsubid = ?                                                                                                                |
| 2009  | 21597 | SELECT attname, CASE WHEN typname = ANY(ARRAY[?,?,?]) THEN ? ELSE ? END AS isSpatial FROM pg_attribute JOIN pg_type ON atttypid=pg_type.oid WHERE attrelid=regclass(?) AND attnum>? ORDER BY attnum |
| 20    | 20    | SELECT proj4text FROM spatial_ref_sys WHERE srid = ? LIMIT ?                                                                                                                                        |

In this situation we also have we also have 380 queries to try and determine the geometry type for columns that don't have a specific geometry typemod set. e.g `SELECT DISTINCT upper(geometrytype) xxx`

It looks like most of queries are coming from determining the column type information https://github.com/qgis/QGIS/blob/3be3984e8edd980a8cf36a1c59bf1f0595e0860b/src/providers/postgres/qgspostgresprovider.cpp#L744 and https://github.com/qgis/QGIS/blob/b837e65662d5328863dc1048e180c8b28752c23b/src/providers/postgres/qgspostgresconn.cpp#L402

I think the process could be quickly improved using lazy loading of the column info. The info is not needed immediately in the dialog (only schema, tablename, comment, spatial column, geometry type, srid, relation type, primary key seem to be needed). Surely the other information could be populated if required (e.g double click to set SQL, or additional potential key information if it's a view).

It's noted the workaround for this issue to to just use the QGIS connection browser, but some of our users prefer this method of adding layers.

**Comment by strk** [comment]
What version of QGIS are you using @palmerj ? Do  you also have timing info for those queries ?

**Comment by palmerj** [comment]
I've tested on 3.8, 3.4 and 2.18

**Comment by palmerj** [comment]
Total times was about 90secs

**Comment by strk** [comment]
I meant the timing for each of the queries you reported number of calls and number of returned rows for.

Testing connection to big databases locally I noticed that while it takes time to _fully_ populate the dialog, the UI is still responsive and you can still load layers that are already loaded, do you confirm this behavior on your side ?

Lazy loading per-schema would be a good idea. Another one could be reducing number of round-trips by grouping togheter queries for multiple tables, or at least reducing number of queries to ONE per table (your report indicates there are more than 2 queries per table)

**Comment by strk** [comment]
> In the testing I did it took 70 secs before the first table loaded
> into the UI. So not good there either.

is the UI blocked during those 70 secs ?

Reading the code in qgspgsourceselect.cpp it looks like a single
thread is spanwed in the background to detect "layer type" (I think
this is the one checking for geometry type).

Maybe we should have more threads for other kind of expensive
retrivals

**Comment by palmerj** [comment]
> is the UI blocked during those 70 secs ?

No it's not, because I think the whole process is run as a background QgsTask

Parallel queries is one options. but I wonder if there is simpler solution..

**Comment by strk** [comment]
Here are some timings from my own testing, with a connection having an average of 500ms latency for each query:

```
src/providers/postgres/qgspostgresconn.cpp:552 : (getTableInfo) [524ms] [thread:0x55d2086695e0] getting table info: SELECT l.f_table_name,l.f_table_schema,l.f_geometry_column,upper(l.type),l.srid,l.coord_dimension,c.relkind,obj_description(c.oid) FROM geometry_columns l,pg_class c,pg_namespace n WHERE c.relname=l.f_table_name AND l.f_table_schema=n.nspname AND n.oid=c.relnamespace AND has_schema_privilege(n.nspname,'usage') AND has_table_privilege('"'||n.nspname||'"."'||c.relname||'"','select') ORDER BY n.nspname,c.relname,l.f_geometry_column
src/providers/postgres/qgspostgresconn.cpp:552 : (getTableInfo) [606205ms] [thread:0x55d2086695e0] getting table info: SELECT l.f_table_name,l.f_table_schema,l.f_geography_column,upper(l.type),l.srid,2,c.relkind,obj_description(c.oid) FROM geography_columns l,pg_class c,pg_namespace n WHERE c.relname=l.f_table_name AND l.f_table_schema=n.nspname AND n.oid=c.relnamespace AND has_schema_privilege(n.nspname,'usage') AND has_table_privilege('"'||n.nspname||'"."'||c.relname||'"','select') ORDER BY n.nspname,c.relname,l.f_geography_column
src/providers/postgres/qgspostgresconn.cpp:552 : (getTableInfo) [614ms] [thread:0x55d2086695e0] getting table info: SELECT l.table_name,l.schema_name,l.feature_column,CASE WHEN l.feature_type = 1 THEN 'MULTIPOINT' WHEN l.feature_type = 2 THEN 'MULTILINESTRING' WHEN l.feature_type = 3 THEN 'MULTIPOLYGON' WHEN l.feature_type = 4 THEN 'GEOMETRYCOLLECTION' END AS type,(SELECT srid FROM topology.topology t WHERE l.topology_id=t.id),2,c.relkind,obj_description(c.oid) FROM topology.layer l,pg_class c,pg_namespace n WHERE c.relname=l.table_name AND l.schema_name=n.nspname AND n.oid=c.relnamespace AND has_schema_privilege(n.nspname,'usage') AND has_table_privilege('"'||n.nspname||'"."'||c.relname||'"','select') ORDER BY n.nspname,c.relname,l.feature_column
src/providers/postgres/qgspostgresconn.cpp:552 : (getTableInfo) [518ms] [thread:0x55d2086695e0] getting table info: SELECT l."r_table_name",l."r_table_schema",l."r_raster_column",'RASTER',l.srid,2,c.relkind,obj_description(c.oid) FROM raster_columns l,pg_class c,pg_namespace n WHERE c.relname=l."r_table_name" AND l."r_table_schema"=n.nspname AND n.oid=c.relnamespace AND has_schema_privilege(n.nspname,'usage') AND has_table_privilege('"'||n.nspname||'"."'||c.relname||'"','select') ORDER BY n.nspname,c.relname,l."r_raster_column"
```

Basically it tells us that it took 1h40m to fetch information about tables with geometry columns, and about half a second to figure out there were no tables with _geography_ or _topogeometry_ or _raster_ columns....

What QGIS was doing in that 1h40m is not logged by QGIS itself, I think it would be useful to add more debugging lines to see that, but reading the code I'd bet on the calls to `addColumnInfo`

**Comment by strk** [comment]
With further tests I confirm it is the many calls to `addColumnInfo` that take all that time. The calls are made for _each_ table in each set of tables (those from geometry_columns, those from raster_columns, those from topology and those from geography_columns) prior to return control to the UI controller. This means no UI activity is made until each set is fully retrieved.

Locally I've been trying a patch that further splits the workload so to have a set for each _schema_ (in addition to each geometry/geography/raster/topogeometry logical subdivision). While this actually _increases_ the number of round-trips to server, it shows _some_ information earlier in the UI (tables start showing up in UI as soon as each smaller set is fully retrieved). This could be the first step toward doing the on-demand schema retrieval.

This can be tested in #32091

**Comment by strk** [comment]
A new commit in #32091 merges the 'addColumnInfo' SQL query with the outer query performed to retrieve layer info. This drastically reduces the number of queries to database.
