### ISSUE TITLE
GPSInformation Add point fails on 3D-Shapes

### ISSUE THREAD

**Issue by jiargei** [qgis/QGIS#32016]
**Describe the bug**
It is not possible add a Point to a 3D-Vector-Layer using GPSInformation.

**How to Reproduce**

1. Right Click on Panel and add "GPS Information Panel"
2. Connect to GNSS-Receiver
3. Wait until connected to GNSS-Receiver
3. Create Vector Layer with Z-Values
4. Set Vector Layer on edit mode "Toggle Editing"
5. Click "Add Point"
4. See error --> "Cannot add feature. Unknown WKB type. Choose a different layer and try again."

**Additional context**

It works fine on 2D-Vector Layers

**Comment by jiargei** [comment]
Hej @gioman !
Just want to know, if this issue will be reviewed?

https://github.com/qgis/QGIS/blob/master/src/app/gps/qgsgpsinformationwidget.cpp Line 912 shall be a QgsPoint instead of a QgsPointXY... 

But..
https://github.com/qgis/QGIS/blob/cdd3a55e9e9c3b1d95f17a47920b51673a4e4099/src/gui/qgsrubberband.cpp Line 110 accepts a QgsPointXY ..

Would be cool changing this to QgsPoint respectively adding addPoint (QgsPoint & p, ...)

Can somebody please check that?

**Comment by gioman** [comment]
> Can somebody please check that?

can you submit a patch/pull request?
Also there have been some fixes recently in the GPS panel, have you tested QGIS master?

**Comment by jiargei** [comment]
Hej... i tested it on the master... The Problem lies within the rubberband, accepting QgsPointXY only...
I have no pull request for that.. It will take a lot of changement in the source code... I guess
