### ISSUE TITLE
Add option to embed in projects images added in print layouts

### ISSUE THREAD

**Issue by gomerso** [qgis/QGIS#32028]
Hi there. I love the new-ish feature which allows SVGs and images to be embeded into a map document. It would be awesome to have the same option with photos in the layout view (logos, north arrows, etc.).

Keep up the good work!

**Comment by gioman** [comment]
@gomerso you can do it since... as far as I can remember, please check the manual.

**Comment by gomerso** [comment]
@gioman I wonder if we're talking about two different things. I am often sharing map documents with clients who obviously don't have the same file structure and icons that I have locally. In 3.0 an option was added to allow SVGs for point symbols or picture-fills to be embedded into the QGZ to avoid the file-structure problem. The same feature is not available for image items in the layout. You can place pictures, but they are referencing a filepath instead of being saved in the map. Am I missing something?

**Comment by jdugge** [comment]
This is possible in QGIS 3.14 (and probably earlier) using the "Embed file..." option:

![embed_image_in_layout](https://user-images.githubusercontent.com/2399255/94373822-3970ec00-0108-11eb-82ec-a86496f111f7.png)
