### ISSUE TITLE
QGIS Raster Calculator outputs nodata only rasters

### ISSUE THREAD

**Issue by raymondnijssen** [qgis/QGIS#32025]
**Describe the bug**
When native qgis raster calculators are used in a model, they (sometimes) generate output rasters containing only nodata values. This does not happen when doing the same calculation using a processing toolbox raster calculator (outside the model).

**How to Reproduce**
Has already been reproduced by Alessandro. :)

**QGIS and OS versions**
3.9 master

**Comment by elpaso** [comment]
@raymondnijssen I'm not 100% sure that it is the exact same issue (but there is a good chance that it is), what I've been able to reproduce is that if you set a formula to a numeric value (with no input rasters as part of the formula) only the first column is changed, this means that you get no-data values for all other cells.

**Comment by raymondnijssen** [comment]
@elpaso I'm not sure. My rasters seemed to be completely nodata, looking like this [-1.79769e+308 to 1.79769e+308] in the mapLayer classification and showing no min and max values with gdalinfo. The extent and cellsize were alright though.
Will try to reproduce it and also to test your possible fix.

**Comment by RNanclares** [comment]
I've had similar issues with some model that use not only the raster calculator (also clipping tool) and if I take the model from my laptop (Ubuntu/Debian) english language to other laptop with Spanish language the model doesn't produce valid rasters anymore. Some of the things I have noticed, the model is referencing an input raster band and can't understand this parameter when I use the model Ina different computer (linux to windows and English to Spanish , both OS and QGIS language and some tool names get translated. I have a model that calculates ndbr and has this issue I will share it later.
