### ISSUE TITLE
GetLegendGraphic shows all identical symbols for content based legend 

### ISSUE THREAD

**Issue by Livava1** [qgis/QGIS#32020]
If I add BBOX to a GetLegendGraphic request, it returns all symbols for objects within the area AND all symbols that are identical. So, if you have two classes with legend labels "A" and "B" but with the identical fill and border, the returned legend will include both "A" and "B" even if only objects of type B is in the area.

This is not the case with QGIS 2.14.

**QGIS and OS versions**

QGIS 3.8.3, Windows

**Comment by elpaso** [comment]
Works fine for me here on master.
QGIS 3.8 is end of life, can you please confirm that the bug is also present on current master?
If it is, can you please attach a small project and data that we can use to reproduce this issue?

**Comment by Livava1** [comment]
I have attached a small project.
A request like
`/qgis_mapserv.fcgi.exe?SERVICE=WMS&VERSION=1.3.0&CRS=EPSG:4326&REQUEST=GetLegendGraphic&FORMAT=image/png&map=test_project.qgs&HEIGHT=30&WIDTH=30&LAYERS=test_layer&BBOX=-0.7,0.2,0,0.4`
gives you a legend with three items. This is wrong. 
If you change the color or of Type C (to any color but those of Type A and B) only A and B will be returned. 

[test_project.zip](https://github.com/qgis/QGIS/files/3686578/test_project.zip)

**Comment by gioman** [comment]
>  If you change the color or of Type C (to any color but those of Type A and B) only A and B will be returned.

on master or still 3.8?

**Comment by elpaso** [comment]
Thank you @Livava1 I can now reproduce the issue on master using your test project.

**Comment by elpaso** [comment]
This is certainly a bug but I'm curious: what's the use case for having two classes with the same style if you cannot tell them apart in the map?

**Comment by Livava1** [comment]
It's not ideal, but necessary because we have too many different values. Then we have to settle with "green is green" instead of 15 different shades of green that no one can tell apart. We use the content based legend combined with labels on the map.
