### ISSUE TITLE
layers panel shows strange artifact

### ISSUE THREAD

**Issue by SrNetoChan** [qgis/QGIS#32029]
**Describe the bug**

There's a strange grey artifact on the Layers panel.

![image](https://user-images.githubusercontent.com/3607161/65729327-c9272900-e0b5-11e9-801a-45cd40639349.png)

First I thought it might be some new feature but it kinda shows also mixed with other layer symbols.

**How to Reproduce**

Just open some layer on QGIS.

**QGIS and OS versions**

QGIS version | 3.9.0-Master | QGIS code revision | 880de7f364
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.6.2-CAPI-1.10.2 4d2925d6
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 11.5 (Ubuntu 11.5-1.pgdg18.04+1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Ubuntu 18.04.3 LTS

**Additional context**

**Comment by DelazJ** [comment]
not the only place eg
![image](https://user-images.githubusercontent.com/7983394/65741786-aa448900-e0ed-11e9-8a24-4e609367dff0.png)

**Comment by nirvn** [comment]
It's not a bug nor a glitch, this is a visual queue added by @dakcarto following his (welcomed) layer tree change enabling horizontal scrollbar to be able to see all legend content vs. clipping it.

**Comment by DelazJ** [comment]
> It's not a bug nor a glitch

Sorry but I'm not really sold on this. In the screenshots above, these "artifacts" look ugly, they are puzzling, and since scrollbar is not needed, they should not be there. Isn't that possible to display that on rows that actually have texts wider than the panel?

**Comment by SrNetoChan** [comment]
@nirvn I agree with @DelazJ on this. It's not clear to me how it works as a visual queue, after all that grey symbol is always visible. Besides does not look very polished. Wouldn't the horizontal scrollbar work just fine without it? The browser has a horizontal scrollbar without any other icons in it.

![Peek 2019-09-27 09-38](https://user-images.githubusercontent.com/3607161/65755338-d589a100-e10a-11e9-87b5-5ca1894d853a.gif)

Sorry if I missed the PR, but can we please reopen this to allow some discussion?

**Comment by gioman** [comment]
agree with @SrNetoChan  and @DelazJ , should have been discussed more widely.

**Comment by SrNetoChan** [comment]
The original PR and discussion was here:

https://github.com/qgis/QGIS/pull/30227

For what I read, the work was merged under the assumption that it would need more testing and because it was early in the development cycle:

https://github.com/qgis/QGIS/pull/30227#issuecomment-505701668

**Comment by gacarrillor** [comment]
Hi all, 
I would acknowledge if you can test PR #35461, where I address suggestions stated here, still preserving the layer mark as a visual clue when using the horizontal scroll.
