### ISSUE TITLE
Qgis 3.8.2 zanzibar unexpectedly ended

### ISSUE THREAD

**Issue by gernigon** [qgis/QGIS#32024]
It takes 10 mn to load my project, then it is slow to work with and it crashes when I close Qgis. Here is the report details.
Any ideas how to solve the issue ?

Crash ID: b4417c17e4e0afd551fca11b93f09b0325592b2f

Stack Trace

proj_lpz_dist :
proj_lpz_dist :
QgsCoordinateTransformPrivate::freeProj qgscoordinatetransform_p.cpp:659
QgsCoordinateTransformPrivate::~QgsCoordinateTransformPrivate qgscoordinatetransform_p.cpp:120
QHashNode,QgsCoordinateTransform>::~QHashNode,QgsCoordinateTransform> :
QHashData::free_helper :
QHash,QgsCoordinateTransform>::clear qhash.h:591
QgsCoordinateTransform::invalidateCache qgscoordinatetransform.cpp:958
QgsApplication::exitQgis qgsapplication.cpp:1263
QgisApp::~QgisApp qgisapp.cpp:1646
QgisApp::`vector deleting destructor' :
main main.cpp:1568
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.8.3-Zanzibar
QGIS code revision: 685d8b15d2
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by nyalldawson** [comment]
This one is already solved - just wait for the next round of releases
