### ISSUE TITLE
Windows QGIS build can't connect to postgres database with scram-sha-256 password

### ISSUE THREAD

**Issue by nextstopsun** [qgis/QGIS#32037]
This has been an issue since 2.18 or earlier. 

Windows builds still use older version of client library `libpq.dll` so it can't connect with 
scram-sha-256 password.

There is a [workaround](https://gis.stackexchange.com/questions/284280/authentication-using-pg-10-scram-sha-256-password-encryption) which just changes `dll` files to newer versions, but it'd be great to have this working out of the box in 3.10.

**Comment by gioman** [comment]
@nextstopsun related to https://github.com/qgis/QGIS/issues/30027 ?

**Comment by nextstopsun** [comment]
@gioman Not sure it's related. 
This one could be easily fixed by just switching to newer library versions.

**Comment by gioman** [comment]
solution for https://github.com/qgis/QGIS/issues/30027 was an update of the same library.

**Comment by alexbruy** [comment]
Seems duplicates #25174
