### ISSUE TITLE
calculating geometries

### ISSUE THREAD

**Issue by Geogeo572** [qgis/QGIS#32035]
I have a problem calculating geometries. The same gemetria has slightly different values using ARGIS and QGIS.
**Arcgis**: 204175,79213200000 sqm
**QGIS**: 204152,093083449261030 sqm
Area officially indicated in the table of the shape file in ha: 20.420000000000002 ha

The most correct color appears to be that of Arcgis.

Best regards
Giorgio Cologni

**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by DelazJ** [comment]
Since QGIS has different means to calculate areas (ie, with or without ellipsoid - see functions help), we'd first need more details on what function you use to calculate, and what is used to calculate the "Area officially indicated in the table".

**Comment by gioman** [comment]
@Geogeo572 

attach the geometry

tell us how are you computing the area (field calculator? derived in the identify panel? other?) and how is your project configured in regard to the ellipsoid being used.

**Comment by Geogeo572** [comment]
The calculation in both programs uses the same reference system (CRS EPSG 3003). The calculation was done using the fileld calculetor with the variable $ Area. I checked the elissid area, while arcgis and the official data use the Cartesian area. How can I insert the Cartesian area in the table.

**Comment by gioman** [comment]
> The calculation in both programs uses the same reference system (CRS EPSG 3003). The calculation was done using the fileld calculetor with the variable $ Area. I checked the elissid area, while arcgis and the official data use the Cartesian area. How can I insert the Cartesian area in the table.

please attach a sample

**Comment by Geogeo572** [comment]
![Area](https://user-images.githubusercontent.com/55874349/65769510-ff0af280-e133-11e9-95c5-ceb0d7d6431c.JPG)

**Comment by Geogeo572** [comment]
All I have to do is to understand what variable I can use to fill in the table field with Cartesian values. Does anyone know it?

**Comment by SrNetoChan** [comment]
You need to go to the project properties and in the General > Measurementts set the Ellipsoid to 

![image](https://user-images.githubusercontent.com/3607161/65769941-d3d0d500-e12c-11e9-90dd-c7c6815783c8.png)

**Comment by Geogeo572** [comment]
Thanks!
