### ISSUE TITLE
Model only runs with QGIS in english

### ISSUE THREAD

**Issue by rnanclares** [qgis/QGIS#32044]
**Describe the bug**
I have a model to calculate dnbr using sentinel 2 images that only works using QGIS in english (which is the language setting used in QGIS when the model was created). If i change the language to something different the model stops working, and the resulting rasters are emtpy.

I used both the native and the gdal raster calculator. The step in which the nbr is calculated for each date doesn't get the correct input parameters because the results from the clipping tool have its name translated to whatever language you have selected in your QGIS settings which doesn't match the input parameter name of the nbr calculation step.

![dnbr_sentinel2](https://user-images.githubusercontent.com/11431207/65788913-ce21c200-e121-11e9-8bdb-398bf6ce1b2f.png)

**How to Reproduce**
I've created this github rebo in case anyone wanted to try to reproduce the issue:
https://github.com/RNanclares/modeler_bug_testing

**QGIS and OS versions**
Only tested with 3.6.x, 3.8.x
Ubuntu 18.04 - 19.04, Windows 10

**Comment by gioman** [comment]
> **How to Reproduce**
> I've created this github rebo in case anyone wanted to try to reproduce the issue:
> https://github.com/RNanclares/modeler_bug_testing

@rnanclares is this still true? the link is not working anymore.

**Comment by rnanclares** [comment]
No, i'm sorry i removed it a month ago. If you still need it i can rebuild it.

**Comment by rnanclares** [comment]
@gioman i just tried changing the language from english to spanish and back, run the model that was having issues previously and it worked without any issue. I think we can close this issue.
