### ISSUE TITLE
Crash on Exit

### ISSUE THREAD

**Issue by FlyingEagle** [qgis/QGIS#32042]
## User Feedback

Simply closing the Programm with open Project file.

## Report Details

*Crash ID*: b4417c17e4e0afd551fca11b93f09b0325592b2f

*Stack Trace*
<pre>
proj_lpz_dist :
proj_lpz_dist :
QgsCoordinateTransformPrivate::freeProj qgscoordinatetransform_p.cpp:659
QgsCoordinateTransformPrivate::~QgsCoordinateTransformPrivate qgscoordinatetransform_p.cpp:120
QHashNode<QPair<QString,QString>,QgsCoordinateTransform>::~QHashNode<QPair<QString,QString>,QgsCoordinateTransform> :
QHashData::free_helper :
QHash<QPair<QString,QString>,QgsCoordinateTransform>::clear qhash.h:591
QgsCoordinateTransform::invalidateCache qgscoordinatetransform.cpp:958
QgsApplication::exitQgis qgsapplication.cpp:1263
QgisApp::~QgisApp qgisapp.cpp:1646
QgisApp::`vector deleting destructor' :
main main.cpp:1568
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.8.3-Zanzibar
QGIS code revision: 685d8b15d2
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment]
already fixed, wait the next point release.
