### ISSUE TITLE
GEOREFERENCER PROBLEM QGIS

### ISSUE THREAD

**Issue by JCSanchezC** [qgis/QGIS#32049]
Greetings I am having problems with the Qgis Georeferencer, pressing it gives no signs of running and I cannot reinstall add-on to solve problem. I have already removed and reinstalled the complete program and the problem is not resolved.

**Comment by SrNetoChan** [comment]
What QGIS version and Operating system are you using?

Can you try running QGIS with a new profile? (Settings > user profiles > new profile)

**Comment by JCSanchezC** [comment]
> What QGIS version and Operating system are you using?
> 
> Can you try running QGIS with a new profile? (Settings > user profiles > new profile)

**thanks for your help. It worked perfect.**
