### ISSUE TITLE
QGIS 3.8.3 Crashes while saving 

### ISSUE THREAD

**Issue by LandList** [qgis/QGIS#32047]
Description
QGIS 3.8.3 will crash and give me the error below when I try to save. I do not have to have a project open for QGIS to crash. 

Crash ID: d3aa618b88abd4005d2f6cc4ab4d08997b7c738d

Stack Trace

RtlFreeHeap :
HeapFree :
free :
DllUnregisterServer :
DllUnregisterServer :
CServerContextActivator::CreateInstance actvator.cxx:1000
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1918
CApartmentActivator::CreateInstance actvator.cxx:2251
CProcessActivator::CCICallback actvator.cxx:1716
CProcessActivator::AttemptActivation actvator.cxx:1630
CProcessActivator::ActivateByContext actvator.cxx:1488
CProcessActivator::CreateInstance actvator.cxx:1389
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1918
CClientContextActivator::CreateInstance actvator.cxx:685
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1918
ICoCreateInstanceEx objact.cxx:1397
CComActivator::DoCreateInstance immact.hxx:343
CoCreateInstanceEx actapi.cxx:175
CoCreateInstance actapi.cxx:120
_SHCoCreateInstance :
SHExtCoCreateInstance :
DCA_SHExtCoCreateInstance :
CFSIconOverlayManager::_s_LoadIconOverlayIdentifiers :
CFSIconOverlayManager::CreateInstance :
IconOverlayManagerInit :
GetIconOverlayManager :
FileIconInit :
SHGetImageList :
CBreadcrumbBar::InitBreadcrumbBar :
CAddressBand::_EnsureBreadcrumbBar :
CAddressBand::_CreateAddressBand :
CAddressBand::SetSite :
IUnknown_SetSite :
CBandSite::_AddBandByID :
CBandSite::AddBand :
CNavBar::_CreateBands :
CNavBar::_CreateBar :
CNavBar::ShowDW :
CFileOpenSave::_CreateNavigationBar :
CFileOpenSave::_InitOpenSaveDialog :
CFileOpenSave::s_OpenSaveDlgProc :
UserCallDlgProcCheckWow :
DefDlgProcWorker :
DefDlgProcW :
UserCallWinProcCheckWow :
InternalCreateDialog :
InternalDialogBox :
DialogBoxIndirectParamAorW :
DialogBoxIndirectParamW :
CFileOpenSave::Show :
QDialog::exec :
QFileDialog::getSaveFileUrl :
QFileDialog::getSaveFileName :
QgisApp::fileSave qgisapp.cpp:6179
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:403
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:403
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1567
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.8.3-Zanzibar
QGIS code revision: 685d8b15d2
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by SrNetoChan** [comment]
Can you try to create a new profile (settings > users profile > new profile) and try again?

Thanks

**Comment by LandList** [comment]
Thank you for the help! That is the first thing I did when I started having this issue.

**Comment by SrNetoChan** [comment]
Can you try QGIS master? There were some recent fixes that may have fixed it.

**Comment by gioman** [comment]
Closing for the lack of feedback.
