### ISSUE TITLE
QGIS crashes on exiting

### ISSUE THREAD

**Issue by IrishEyesAreSmiling** [qgis/QGIS#32056]
QGIS crashes every time I close/exit it. 

Report as below:

Crash ID: b4417c17e4e0afd551fca11b93f09b0325592b2f

Stack Trace

proj_lpz_dist :
proj_lpz_dist :
QgsCoordinateTransformPrivate::freeProj qgscoordinatetransform_p.cpp:340
QgsCoordinateTransformPrivate::~QgsCoordinateTransformPrivate qgscoordinatetransform_p.cpp:91
QHashNode,QgsCoordinateTransform>::~QHashNode,QgsCoordinateTransform> :
QHashData::free_helper :
QHash,QgsCoordinateTransform>::clear qhash.h:591
QgsCoordinateTransform::invalidateCache qgscoordinatetransform.cpp:831
QgsApplication::exitQgis qgsapplication.cpp:1211
QgisApp::~QgisApp qgisapp.cpp:1600
QgisApp::`vector deleting destructor' :
main main.cpp:1543
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.4.12-Madeira
QGIS code revision: 625767347a
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by nyalldawson** [comment]
Already fixed for the next set of releases
