### ISSUE TITLE
Point Simple Marker is clipped when rotated

### ISSUE THREAD

**Issue by davekimble2** [qgis/QGIS#32059]
Ubuntu-18.04, QGIS-2.18.17 .
I am trying to create a vector layer, a new point shapefile.
The Simple Marker is a "half square", but when its Rotation is 45, the corners of the rectangle are truncated, I think by the boundaries of the unrotated marker.

Open your base layer.
Layer > Create Layer > New Shapefile Layer ...
Point > Name: xxx > Add to fields list > OK
In Layer Panel right-click the new layer, click Properties, click Simple Marker.
Select "square", Rotation: 0.00000
image1 attached
Rotation: 45.00000
image2 attached
![Screenshot from 2019-09-30 10-54-51](https://user-images.githubusercontent.com/6146050/65843898-53ea7b00-e377-11e9-9f1b-2193672399ed.png)
![Screenshot from 2019-09-30 10-55-16](https://user-images.githubusercontent.com/6146050/65843931-711f4980-e377-11e9-810c-c1469d49bc95.png)

**Comment by gioman** [comment]
> Ubuntu-18.04, QGIS-2.18.17 .

@davekimble2 too old, you must try with 3.4 or above.

**Comment by SrNetoChan** [comment]
Still valid in master 3.9:

![image](https://user-images.githubusercontent.com/3607161/65866758-49c37f00-e36d-11e9-9f42-e69570fb5117.png)

**Comment by SrNetoChan** [comment]
Does not happen with Filled marker, SVG and Font Marker.

**Comment by davekimble2** [comment]
> too old, you must try with 3.4 or above.''

My script to reproduce the effect on any version is so short that it would be simpler to test it on 3.4 than to dismiss as "too old" the latest LTS version on the most popular Linux distro.

**Comment by nirvn** [comment]
I'm on this one.

**Comment by DelazJ** [comment]
> My script to reproduce the effect on any version is so short that it would be simpler to test it on 3.4 than to dismiss as "too old" the latest LTS version on the most popular Linux distro.

@davekimble2 are you sure that 2.18 is the latest version on ubuntu 18.04? According to https://qgis.org/en/site/forusers/alldownloads.html#debian-ubuntu 3.4 (QGIS latest LTR) is available on 1**6**.04

**Comment by davekimble2** [comment]
$ sudo apt install qgis
qgis is already the newest version (2.18.17+dfsg-1).

**Comment by nirvn** [comment]
@DelazJ , FYI: 

    xenial (16.04LTS) (science): Geographic Information System (GIS) [universe]
    2.8.6+dfsg-1build1: amd64 arm64 armhf i386 powerpc ppc64el s390x
    xenial-updates (science): Geographic Information System (GIS) [universe]
    2.8.6+dfsg-1ubuntu1: amd64 arm64 armhf i386 powerpc ppc64el s390x
    bionic (18.04LTS) (science): Geographic Information System (GIS) [universe]
    2.18.17+dfsg-1: amd64 arm64 armhf i386 ppc64el s390x
    cosmic (18.10) (science): Geographic Information System (GIS) [universe]
    2.18.22+dfsg-1: amd64 arm64 armhf i386 ppc64el s390x
    disco (19.04) (science): Geographic Information System (GIS) [universe]
    3.4.6+dfsg-1build1: amd64 arm64 armhf i386 ppc64el s390x
    eoan (science): Geographic Information System (GIS) [universe]
    3.4.10+dfsg-1build1: amd64 arm64 armhf i386 ppc64el s390x

**Comment by nirvn** [comment]
@davekimble2 , it'll be fixed in the next scheduled QGIS release (Oct 25). That said, you'll have to move away from the ubuntu-distributed version of QGIS onto the version provided by the QGIS project itself via one of the repositories listed here: https://qgis.org/en/site/forusers/alldownloads.html#debian-ubuntu

**Comment by davekimble2** [comment]
Thank you.
I would add a repository if I could only find one from that link.
https://qgis.org/ubuntu and https://qgis.org/ubuntugis give me an index list of some other files, but I don't know what they are.
I was expecting something like:
// qgis-3.8 for ubuntu-18.04
$ sudo add-apt-repository ... ?
$ sudo apt update
$ sudo apt upgrade

**Comment by gioman** [comment]
>  I would add a repository if I could only find one from that link.

there are plenty of links here https://qgis.org/en/site/forusers/alldownloads.html#debian-ubuntu

QGIS repos (from qgis.org) are not PPAs, do don't expect a "sudo add-apt-repository..."

In your sources.list you must add the proper repo, depending on what version of QGIS you want to install (3.4, 3.8 or master) and if you are using ubuntugis dependencies or not.

Anyway I think there is a PR that fixes this issue (not sure if it has already been merged),
closing?

**Comment by nirvn** [comment]
Fix already merged, issue already closed :)

**Comment by davekimble2** [comment]
> QGIS repos (from qgis.org) are not PPAs

Huh?  This must be my basic misunderstanding.
Can someone please explain this to me.

I have Ubuntu-18.04 and I want the latest stable version of QGIS, so any minor errors I find can be reported without being told "its too old". 
I also want the software to get updated automatically.
So what do I do?
Perhaps then I'll understand, but  https://qgis.org/en/site/forusers/alldownloads.html#debian-ubuntu
doesn't explain it.

**Comment by gioman** [comment]
>  Perhaps then I'll understand, but https://qgis.org/en/site/forusers/alldownloads.html#debian-ubuntu

it does very clearly:

at some point

_"Add the lines for one of the repositories to your /etc/apt/sources.list:"_


that means that you must edit your sources.list file and add a line  containing the proper address depending on what ubuntu version you have and what qgis release you want to install. If you want to install QGIS LTR on Ubuntu 18.04 and you use also the Ubuntugis repository than you must add

deb https://qgis.org/ubuntugis-ltr bionic main

the you do apt-get update

do not forget to authenticate the qgis.org repos

sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key 51F523511C7028C3

**Comment by davekimble2** [comment]
> very clearly
> "Add the lines for one of the repositories to your /etc/apt/sources.list:"

But WHAT are "the lines for"? 
Does it mean add a line to /etc/apt/sources.list: 
deb <_repository_> <_your Ubuntu version_> main 
(where <_repository_> is any URL from the Repository column.)

Assuming that is the case, I will add to /etc/apt/sources.list :
deb https://qgis.org/ubuntu bionic main
followed by: 
$ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key 51F523511C7028C3
$ sudo apt update
$ sudo apt upgrade

**Comment by davekimble2** [comment]
It works.  3.8.3 installed.
The repo server is painfully slow.
