### ISSUE TITLE
WFS doesn't recognize advertised GeoJSON outputFormat string

### ISSUE THREAD

**Issue by MattiasSp** [qgis/QGIS#32065]
Using QGIS Server 3.8.2, the WFS Capabilities for version 1.1.0 advertise possible outputFormats as such:

```xml
<ows:Operation name="GetFeature">
    <ows:DCP>
        <ows:HTTP>...</ows:HTTP>
    </ows:DCP>
    <ows:Parameter name="outputFormat">
        <ows:Value>text/xml; subtype=gml/2.1.2</ows:Value>
        <ows:Value>text/xml; subtype=gml/3.1.1</ows:Value>
        <ows:Value>application/vnd.geo+json</ows:Value>
    </ows:Parameter>
    <ows:Parameter name="resultType">...</ows:Parameter>
</ows:Operation>
```

But the WFS only recognizes `outputFormat=GeoJSON`, not `outputFormat=application/vnd.geo+json`. Using the latter, or any other variant, results in the WFS default GML format.

The WFS should at least recognize the Media Type advertised in its own Capabilities document, but for making QGIS Server compatible with more clients, it would be great if it could accept multiple variants, e.g;

- GeoJSON (current Media Type)
- application/vnd.geo+json (advertised Media Type)
- application/geo+json ([Media Type specified in the GeoJSON standard](https://tools.ietf.org/html/rfc7946#section-12))
- application/json ([Media Type used by GeoServer](https://docs.geoserver.org/latest/en/user/services/wfs/outputformats.html))

**QGIS and OS versions**
> QGIS version 3.8.2-Zanzibar
QGIS code revision 4470baa1a3
Compiled against Qt 5.11.2
Running against Qt 5.11.2
Compiled against GDAL/OGR 2.4.1
Running against GDAL/OGR 2.4.1
Compiled against GEOS 3.7.2-CAPI-1.11.0
Running against GEOS 3.7.2-CAPI-1.11.0 b55d2125
PostgreSQL Client Version 10.8
SpatiaLite Version 4.3.0
QWT Version 6.1.3
QScintilla2 Version 2.10.8
Compiled against PROJ 5.2.0
Running against PROJ Rel. 5.2.0, September 15th, 2018
OS Version Windows Server 2016 (10.0)

**Comment by MattiasSp** [comment]
Thank you @elpaso, great work! I see the fix required more edits than I expected, especially for WFS3. I look forward to trying it out :)

**Comment by elpaso** [comment]
No problem, thanks to all QGIS donors and sponsors! 
Let me know if I missed anything.
