### ISSUE TITLE
Display current layers CRS in project's properties.

### ISSUE THREAD

**Issue by MrChebur** [qgis/QGIS#32066]
**Feature description.**

I want to see the new information box `Current CRS Layers` on the tab` Project Properties` => `CRS`.

The `Current CRS Layers` box should contain all CRS of the currently added layers.

This will allow you to quickly change your project CRS to the one of the current layer CRS without having to check the properties of the layers.

**Additional context**

![1](https://user-images.githubusercontent.com/20655102/65868966-d2a0e180-e392-11e9-9d6f-6e279227ba89.jpg)

**Comment by DelazJ** [comment]
> This will allow you to quickly change your project CRS to the one of the current layer CRS without having to check the properties of the layers.

In the ["Layer" menu](https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_gui.html#layer) as well as from the [context menu of a layer](https://docs.qgis.org/testing/en/docs/user_manual/introduction/general_tools.html#overview-of-the-context-menu-of-the-layers-panel), there's a button to "set Project CRS from Layer". No need to open the project properties tab.

**Comment by MrChebur** [comment]
Live and learn. Closed.
