### ISSUE TITLE
Broken SVG export when metadata is enabled

### ISSUE THREAD

**Issue by vog** [qgis/QGIS#32077]
**Describe the bug**

When exporting to SVG **and** enabling metadata, the resulting SVG file is severely broken: It is not only invalid SVG, it is not-well-formed XML.

**How to Reproduce**

1. Use any test dataset (doesn't matter)
2. Export to SVG with metadata enabled
3. Open SVG file in Firefox (or use xmllint, or any other strict XML processing tool)

**QGIS and OS versions**

3.4.12

**Additional context**

The XML is only ill-formed because of missing namespace declarations. The standard SVG namespaces are all set, but the metadata namespaces such as `xmlns:rdf=...` missing. Adding those to the SVG export (or just the metadata part) will fix the issue.

**Comment by nyalldawson** [comment]
This is fixed for QGIS 3.10

**Comment by vog** [comment]
I see! For future readers, the relevant issue is #28130 and the relevant PR is #31890
