### ISSUE TITLE
QGIS 3.4 closes when I open the settings and go to options

### ISSUE THREAD

**Issue by samueldelaguila** [qgis/QGIS#32071]
Error
1. Go to 'Setting'
2. Click on 'Options'
3. See error -->
Crash ID: c383df7530c930f2dd512e56afc9d70a11a78b7c

Stack Trace

QgsQtLocationConnection::startSatelliteMonitor :
QgsQtLocationConnection::startSatelliteMonitor :
QgsQtLocationConnection::startSatelliteMonitor :
QgsOpenClUtils::init :
QgsQtLocationConnection::startSatelliteMonitor :
RtlRunOnceComplete :
InitOnceExecuteOnce :
_crtInitOnceExecuteOnce :
QgsOpenClUtils::errorText :
QgsOpenClUtils::activeDevice :
QgsOpenClUtils::activate :
QgsQtLocationConnection::startSatelliteMonitor :
QgsQtLocationConnection::startSatelliteMonitor :
RtlRunOnceComplete :
InitOnceExecuteOnce :
_crtInitOnceExecuteOnce :
QgsOpenClUtils::init :
QgsOpenClUtils::available :
QgsOptions::~QgsOptions :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::setChecked :
QgsOptions::QgsOptions :
QgisApp::createOptionsDialog :
QgisApp::showOptionsDialog :
QgisApp::options :
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
TranslateMessageEx :
TranslateMessage :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.4.3-Madeira
QGIS code revision: 2f64a3c4e7
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.0
Running against GDAL: 2.4.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**QGIS 3.4 and Windows 7 versions**

**Additional context**

**Comment by nyalldawson** [comment]
Please upgrade to 3.4.12 - this is already fixed
