### ISSUE TITLE
dbmanager: various oracle plugin issues

### ISSUE THREAD

**Issue by Mi-Kbs-gis** [qgis/QGIS#32086]
While using Oracle Spatial Layers, there are some problems.

*** Geometry type detection in Browser and DB-Manager is not the same**
![grafik](https://user-images.githubusercontent.com/25895003/66021445-160e6380-e4eb-11e9-9944-60e121c5604a.png)
![grafik](https://user-images.githubusercontent.com/25895003/66021514-448c3e80-e4eb-11e9-8fb9-9ec8502e019f.png)

*** SQL-Querys works, but they can't load as a new Layer (included tables with metadata, spatialindex and primary key)**
![grafik](https://user-images.githubusercontent.com/25895003/66021721-d136fc80-e4eb-11e9-859e-799115f48322.png)
![grafik](https://user-images.githubusercontent.com/25895003/66021773-ff1c4100-e4eb-11e9-965d-0e5e5eea46d2.png)

* Layer Import into Oracle is not possible with the existing import-dialog (DB-Manager) 
->schema name in sql statment must not have double quotation mark
![grafik](https://user-images.githubusercontent.com/25895003/66021818-28d56800-e4ec-11e9-8f1d-55ad16a1f308.png)
![grafik](https://user-images.githubusercontent.com/25895003/66021835-3c80ce80-e4ec-11e9-941c-d246368d28c1.png)

*** Creating of new tables in oracle is not possible**
->schema name in sql statment must not have double quotation mark
![grafik](https://user-images.githubusercontent.com/25895003/66022013-dba5c600-e4ec-11e9-9f3a-9b254bdd60b8.png)
![grafik](https://user-images.githubusercontent.com/25895003/66022032-ea8c7880-e4ec-11e9-9c97-62c396094544.png)

Operarting System Windows 7
QGIS Version 3.4 - 3.8

**Comment by jef-n** [comment]
For inserting the query you have to pick the key column (ie. check the box in front of `PROFIL_ID` if that's the key).
So the schema name is actually "KUERBS" (ie. uppercase)?

**Comment by Mi-Kbs-gis** [comment]
Thanks, inserting the query works now. Just with primary key?

Yes the scheme name is actually "KUERBS"

**Comment by haubourg** [comment]
According to the last comment from @Mi-Kbs-gis , I close. please reopen and provide details if the issue still occurs
