### ISSUE TITLE
DB manager import option "Create single-part geometries instead of multi-part" is broken

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#32089]
Despite its name, that has been always confusing (PR to change the name here https://github.com/qgis/QGIS/pull/32088 ), this option in DB Manager never transformed geometries to SINGLE from MULTI along the import process.

What the option means is that if I have a layer that is declared as MULTI but actually has no multipart geometries in it, then it can be imported as a non-MULTI table.

In past QGIS releases (i.e. 2.18 LTR)  if you had a layer with a multi-geometry and checked
that option then DB manager returned an error like

```
Error 7
Feature write errors:
Creation error for features from #0 to #0. Provider errors was:
Geometry type MultiLineString not compatible with provider type LineString.
PostGIS error while adding features: ERROR: Geometry type (MultiLineString)
does not match column type (LineString)
```

now it does **not** and imports to MULTI anyway and silently. And it does also if you don't have any multi-geometry, which of course are both bugs and regressions.

QGIS 3.4 and master.

**Comment by elpaso** [comment]
@gioman I don't feel it's a regression because it basically never worked, but that's not the important point.

I've checked the implementation (from 2012!) and there is no way to make it work except for scanning the whole layer upfront and check all geometries if is there any multi and switch to single-part it there aren't any. Another option would be to re-open the file with GDAL and ask GDAL the actual type (`ogrinfo` does, so I'm pretty sure it will work for us too).

The fact is that around 2017 a change was introduced https://github.com/qgis/QGIS/commit/1aa0091e7a368dedf716b80c25b376e3251848a0#diff-63b6a1d9be718d66b05c5f314071c51eR1182 that always returns multi type for shapefiles in OGR provider.

This change was at the provider level, so since that moment all POLYGON and LINESTRING shapefiles have multi-part type (but not the POINTS, don't ask me why because I really cannot guess).

**Comment by nirvn** [comment]
Shapefile's linestring and polygon datasets are actually always multi-part, whereas for points, the format supports single point & multipoint. 

The commit in 2017 was applied to fix the false promise that shapefile POLYGON layers would only return singlepart polygons.

As to why ESRI only separated single and multi types for points, that's a mystery.

**Comment by elpaso** [comment]
> Shapefile's linestring and polygon datasets are actually always multi-part, whereas for points, the format supports single point & multipoint.
> 
> The commit in 2017 was applied to fix the false promise that shapefile POLYGON layers would only return singlepart polygons.
> 

Thanks for clarifying: I knew about the multi-part for shapefiles but I didn't know about this special case for points.

**Comment by gioman** [comment]
> @gioman I don't feel it's a regression because it basically never worked, but that's not the important point.

@elpaso Hi Alessandro, I respectfully disagree here. From a user point of view is certainly a regression that does not leave options in QGIS.



> I've checked the implementation (from 2012!) and there is no way to make it work except for scanning the whole layer upfront and check all geometries if is there any multi and switch to single-part it there aren't any. Another option would be to re-open the file with GDAL and ask GDAL the actual type (`ogrinfo` does, so I'm pretty sure it will work for us too).

reading this I'm not sure if the problem is clear.

The problem is not about shapefiles and how they are treated and how this changed since past QGIS versions, it affects any type of datasource it can be used as input for this db manager tool.

Despite the name (now changed) the option was *never* about importing a layer in (i.e.) PostGIS and along the process have MULTI geometries transformed in SINGLE, so it is *not* the equivalent of doing a "multipart to singlepart" operation followed by the import one.

The option was always about the possibility to import a layer *without* any MULTI geometry in it (but declared as MULTI) as a NON-MULTI table in (i.e.) PostGIS.

Up to 2.18 if I had a layer with MULTI geometries and tried to import them with that option activated at some point the operation failed (I guess it failed when the first MULTI geometry was encountered), and that was good.

Now the operation *does* not fail, QGIS imports silently in a MULTI table which is exactly the opposite of what the user asked by activating that checkbox, and it does silently, which is very bad.

So actually there are 2 issues, and both are regressions:

* QGIS/DB manager does silently an operation that is not what the user asked
* QGIS/DB manager does not allow anymore to import a layer/table (declared as MULTI but without actually any MULTI features) into a SINGLE layer/table

**Comment by elpaso** [comment]
@gioman I don't really care if it's a regression or not, it's a bug and for me it's enough :) 
But, can you give me a reproducible example on 2.x where I can import a MULTI into POSTGIS and get it imported as SINGLE? (let's stick to polygons if possible)? 

I don't see any implementation for this conversion in the current code, but it's possible that something else changed under the hood.

Besides, I think that the new label "Do not promote to multi-part" is still unclear: let's say that I have a MULTI layer (QGIS reports it as MULTI) with only single-part features in it and I want it imported into PG.

There would be no promotion of the layer if I leave unchecked the option, I have a MULTI in and a MULTI out (no change: no promotion), the promotion would possibly be on (some or all of) the features.

On the other hand, if I check the option I get a MULTI in and a SINGLE out (would you call it a demotion?) and the features would be untouched. Perhaps we can make it clearer that the promotion would be on single-part features and the option would only have an effect on layer that do not have any MULTI feature in them.
 
Just to muddy the waters, guess how it is called internally that option? "forceSinglePartGeometryType"

**Comment by gioman** [comment]
@elpaso thanks for tackling this. I was preparing a simple demo, but I have seen a PR for this issue, is still necessary?

**Comment by gioman** [comment]
> I'd really like you to test it.

ok

> Note that in case of failure we could have a partial import and the table will be already created, in an ideal (DB) world we could have transactions and rollbacks but this is all to be developed.

yes, this is how worked until 2.18. Is of course far from ideal, but still a little better than how it works now (a user has the impression to have a non-MULTI table, a table where is supposed that MULTI geometries cannot be created (i.e. it can be used as a constraint is some context), and instead gets a MULTI table).
