### ISSUE TITLE
creating indexes on geopackage failes (QGIS 3.8.3)

### ISSUE THREAD

**Issue by brusspi** [qgis/QGIS#32094]
**Describe the bug**

I trie to add an index on a field of a layer that belongs to a geopackage via Databasemanager, but nothing happens.

**How to Reproduce**
I downloaded an exctract of OSM and packaged the layers.

Via DBmanager I want to add an index on the field highway by 'edit table' > tab indexes, > add index
Choosing the right field I clicked on 'create index'.  It runs some time and then stops suddenly without any result.

When I do the same procedure on a spatialiteDB with the same data, the index is created fine.

**QGIS and OS versions**
windows 10, QGIS 3.8.3

**Additional context**

**Comment by elpaso** [comment]
I checked on Linux/master and I could not reproduce this issue.
Since 3.8 is end of life, could you please check if this is still an issue on master?
If it is, please attach a small sample project and data to reproduce the issue.

**Comment by brusspi** [comment]
I tried it on QGIS 3.9 and it worked fine.  This question can be closed.  Thx!
