### ISSUE TITLE
Layout --> Show maps inside irregular polygons, triangular polygons, circles, ellypse or rectangle polygons like a Tetris

### ISSUE THREAD

**Issue by miquidesitio** [qgis/QGIS#32092]
_**Layout --> Show maps inside irregular polygons, triangular polygons, circles, ellypse or rectangle polygons like a Tetris**_

_**Additional context**_
In layout, you can insert many maps (Add map), but only can be regular polygon (square or rectangular), but when you want create a special presentation like a Tetris, you can't do it. The figures circle, triangular, add polygon,... can't show maps inside them.
Someone know how can do this?
Would be nice that QGIS has this options in layouts...

![WkUh4](https://user-images.githubusercontent.com/56071452/66038261-f0488500-e511-11e9-97d1-cdbba4e38241.jpg)

Thanks,
Miquel

**Comment by gioman** [comment]
@miquidesitio inverted polygons? https://oslandia.com/2014/06/14/masking-features-in-qgis-2-4/

**Comment by miquidesitio** [comment]
Thanks @gioman for your idea but I can't work with inverted polygons in layouts. I need that the irregular polygon call the map from inside and outside be transparent for fit another irregular polygon with other map. It's a little bit difficult....  Thanks again !!!!

**Comment by gioman** [comment]
@miquidesitio would not this better suited for a question in the users/developers mailing list?

**Comment by nyalldawson** [comment]
It's a valid feature request. ArcGIS has this functionality, and there's no way to reproduce it in current qgis versions.

**Comment by miquidesitio** [comment]
> @miquidesitio would not this better suited for a question in the users/developers mailing list?

@gioman, what is the users/developers list? Where is?

**Comment by miquidesitio** [comment]
> It's a valid feature request. ArcGIS has this functionality, and there's no way to reproduce it in current qgis versions.

Good to know @nyalldawson that ArcGIS has this functionallity. Maybe QGIS will can incorporate it in layouts. Thanks !!!!

**Comment by nyalldawson** [comment]
@miquidesitio I've previously specced this out, but it's not a trivial change and would likely require sponsorship to make it a reality. Let me know if you're interested!

**Comment by miquidesitio** [comment]
Sure. It isn't a easy change...
When you talk about sponsorship, what mean to be sponsorship? How much would can cost to do this change in QGIS?

**Comment by nyalldawson** [comment]
@miquidesitio 

There's a few parts involved here:

1. Adding support for setting "clipping paths" to layout items. This would allow an existing layout shape item (either rect/oval/triangle/or polygon shape) to be used to clip out the rendered portion of another item. This part would be around 2-3 days to implement.

2. For clipped map items, pushing the clipping shape into the rendering engine to avoid placing labels inside clipped areas, and avoiding rendering things like centroid markers in these areas too. That's another 2-3 days to do.

So you'd be looking at about a week of developer time to implement. Send me an email at nyall@north-road.com if you'd like a formal proposal and costing covering this!

**Comment by andreasneumann** [comment]
> @gioman, what is the users/developers list? Where is?

https://www.qgis.org/en/site/forusers/support.html#mailing-lists

**Comment by nyalldawson** [comment]
This was already implemented

**Comment by miquidesitio** [comment]
Thanks @NyallDawson !!!
Sorry for my delayed answer....
*------------------------------------------------------*
*Miquel Pujol Garcia*

*AdverbiodeLugar**.International™*
https://sitio.earth
https://frmp.racing



Missatge de Nyall Dawson ***@***.***> del dia dc., 7 de set.
2022 a les 7:26:
