### ISSUE TITLE
Performance drawing of 1 million points on a part of the screen

### ISSUE THREAD

**Issue by mooiman** [qgis/QGIS#32099]
**Feature description.**
Performance drawing of 1 million points on a part of the screen from a shapefile-layer

**Additional context**
I am developing a plugin in QGIS 3.8 Zanzibar. When I draw a layer with 1 million points it takes some time  (ie too much time). The 1 million points are loaded from a shape-file. Using the overlay option does not improve the drawing speed, and I think the spatial indexing does not help because all the 1 million points are in view. 
When I am using my plugin implementation the 1 million points are drawn very fast (nearly no time), but these points are drawn above the mapcanvas of QGIS when the rendering of the layers is complete, after the renderComplete signal is given.
I do have a mp4-file to show the difference between drawing 1 million points, but that file is not excepted.

Is there a way to get the same perfomance drawing the 1 million points from a layer? 
For my application it is initially not needed to combine some layers, only shifting the drawing order of layers is of interest for my application.
Thanks in advance

**Comment by roya0045** [comment]
This doesn't seem to be a feature request. What you want is probably the developer mailing list.

All the mailing lists are listed here: https://qgis.org/en/site/getinvolved/mailinglists.html

**Comment by gioman** [comment]
@mooiman I also do not clearly understand what is the request. If you have a screencast you can link it here rather than attaching it.

**Comment by mooiman** [comment]
I added a picture. At the left side of the picture the points from the Maasvlakte layer are drawn, at the right side the points are drawn by the plugin I had writte.
![note_on_performance](https://user-images.githubusercontent.com/13199595/66155318-a51c9800-e61f-11e9-9e0f-b842f70a5398.png)
Link to [animation](d:\mooiman\home\screencaptures\mp4\qgis_drawing_performance.mp4)
My question is: How could I get the same  performance in QGIS with the layers as I have with the plugin?

**Comment by mooiman** [comment]
Sorry for closing the issue.

**Comment by mooiman** [comment]
Unzip the file to get a mp4-file. The movie will first the drawing spped of my plugin, including zooming into the canvas and moving the canvas. Than I disable drawing the points via the plugin and start viewing the points by the enabe the layer 'maasvlakte' . A major difference in performance is seen.

[qgis_drawing_performance.zip](https://github.com/qgis/QGIS/files/3692069/qgis_drawing_performance.zip)

**Comment by gioman** [comment]
> The movie will first the drawing spped of my plugin, including zooming into the canvas and moving the canvas. Than I disable drawing the points via the plugin and start viewing the points by the enabe the layer 'maasvlakte' . A major difference in performance is seen.

is the underlying datasource the same? Can you post/link the data? Is your plugin a python or a C++ one? Can you share it?

**Comment by roya0045** [comment]
I agree that with the source code core devs could explain the performance difference.

**Comment by mooiman** [comment]
As Gioman and Roya0045 asked about the underlying data source, the data source is the same (see attached file maasvlakte_for_qgis.xyz; EPSG=28992). But in the movie qgis_drawing_performance the visualized data is not the same. The data drawn from the qgis-layer does also render the labels of the depth, where my plugin does not. Therefor a new movie is attached, there is still a performance issue, see zip file qgis_drawing_performance_2.zip.  When I also render the labels (in QGIS and my PLUGIN) the performance difference is increasing, see qgis_drawing_performance_2_labels.zip. In the last movie, after some time I disabled the drawing of the layer which increase the drawing preformance.

My plugin is written in FORTRAN (ie the quickin.dll) but there is a c++ wrapper around this dll, so for QGIS it is a C++ plugin.

The most important source code file which does the drawing is also attached: MyCanvas.cpp (MyCanvas.zip). A short description:
After QGIS has finished rendering the signal renderCompletePlugin is given, this signal is catched in MyCanvas.cpp. Than the plugin start the drawing by MyCanvas:StartDrawing, after that, the dots are drawn by the function MyCanvas::drawMultiDot(...), when the plugin is finished with drawing, the function MyCanvas::finishDrawing is called. This function draw the caches on the MapCanvas of QGIS. I think the magic is done in the function MyCanvas::drawMultiDot(...) because a pixel on the screen is just once drawn (mask array pixelArray, line 714).
[MyCanvas.zip](https://github.com/qgis/QGIS/files/3698866/MyCanvas.zip)
[qgis_drawing_performance_2.zip](https://github.com/qgis/QGIS/files/3698868/qgis_drawing_performance_2.zip)
[qgis_drawing_performance_2_labels.zip](https://github.com/qgis/QGIS/files/3698869/qgis_drawing_performance_2_labels.zip)

**Comment by gioman** [comment]
> My plugin is written in FORTRAN (ie the quickin.dll) but there is a c++ wrapper around this dll, so for QGIS it is a C++ plugin.
> 
> The most important source code file which does the drawing is also attached: MyCanvas.cpp (MyCanvas.zip). A short description:
> After QGIS has finished rendering the signal renderCompletePlugin is given, this signal is catched in MyCanvas.cpp. Than the plugin start the drawing by MyCanvas:StartDrawing, after that, the dots are drawn by the function MyCanvas::drawMultiDot(...), when the plugin is finished with drawing, the function MyCanvas::finishDrawing is called. This function draw the caches on the MapCanvas of QGIS. I think the magic is done in the function MyCanvas::drawMultiDot(...) because a pixel on the screen is just once drawn (mask array pixelArray, line 714).

@mooiman you should (also) raise this interesting case to the QGIS developers mailing list with all the necessary technical details. I think that is you find a way to significalle improve rendering speeds in QGIS then many devs will be interested to discuss it.

**Comment by roya0045** [comment]
I would assume @nyalldawson  would be interested. Though I'm not sure integrating Fortran is something that devs would approve rapidly.

**Comment by nyalldawson** [comment]
It's really quite a different approach, and I'm doubtful there's anything we can use here. The fundamental differences are:
1. No support for vector based drawing, which we require for map exports in PDF/SVG/EPS etc
2. No support for complex symbology options like data defined settings, drawing selected features, etc
3. (most limiting) No support for transparency or antialiased rendering of markers

Number 3 is the big one, which prevents any use of the "don't draw overlapping markers" shortcut in the core marker renderer. 

So it's a nice shortcut, but since it only can be used in very limited circumstances I don't think there's anyway we can adapt this approach to the core symbol renderer.

**Comment by mooiman** [comment]
OK, thanks for the explanation.
I never thought about 'complex symbology', 'transparancy' and 'anti-aliasing'.
