### ISSUE TITLE
Install for Linux says 3.8.3 released, but only 3.8.2 is coming up.

### ISSUE THREAD

**Issue by zeddock** [qgis/QGIS#32109]
As a new user, I installed QGIS and got 3.8.2-2 on my Manjaro installation 18.1
I keep getting a little indicator at the bottom when I start the application that says New Version Available 3.8.3

I go to the link but cannot see a way to download/install.

Sorry if this is a newbee issue.  I did look for answers but found none so thought I had better report it since Arch is listed in the Available Linux downloads.

**Comment by jef-n** [comment]
This is a known distribution issue - QGIS is already flagged outdated [there](https://www.archlinux.org/packages/community/x86_64/qgis/)
