### ISSUE TITLE
Warning when changing CRS in layer properties

### ISSUE THREAD

**Issue by baswein** [qgis/QGIS#32101]
**Warning when changing CRS in layer properties**

For those new to GIS it is too easy to change the CRS of the layer in the layers properties dialog when trying to troubleshoot data. If there was a warning dialog (that could be turned off for experienced users) explaining that this only changes how QGIS reads the layer and does not reproject the data could save a lot of confusion and provide some education.

**Comment by roya0045** [comment]
Maybe adding a tooltip or simply adding to the description that this does not changes the coordinate of the vertices but how they are projected should be sufficient instead of a warning.

**Comment by alexbruy** [comment]
Related issue #24852.

**Comment by baswein** [comment]
A couple of mockups of language change based on this [twitter thread](https://twitter.com/Geo__Don/status/1316129706962550786?s=20). Both of these seem like simple fixes to me (non-coder) is  the long one better than the short one? . 
![image](https://user-images.githubusercontent.com/15817745/96004594-98717900-0e09-11eb-91ad-716a7122702f.png)
![image](https://user-images.githubusercontent.com/15817745/96005289-4da43100-0e0a-11eb-9cb5-54555c8d5306.png)
If this seems like a good idea It would be fun to try to figure out how to do a pull request and find the relevant place in the code to make the change but I am sure it would be better for someone who actually knows how to code.

**Comment by baswein** [comment]
Here is an updated proposal:
1. Remove the "Set" word to be consistent with the style of other dialog boxes.
2. Change "source" to "Layer" because as far as I can tell it does not read from the data source or change the data source CRS.
3. Add: "(changing does not reproject data)" to help inexperienced GIS users understand what is happening. 
Final proposaed text is: 
**Layer coordinate reference system (changing does not reproject data)**
![image](https://user-images.githubusercontent.com/15817745/96184533-9e994f80-0f06-11eb-9bf9-3ffe2de7e796.png)
I am sure there will still be many confused people but hopefully less.

**Comment by nyalldawson** [comment]
Sounds good -- I'll implement your wording in a similar appearance as the very descriptive explanations we've added for some of the recent labelling settings.

**Comment by baswein** [comment]
@nyalldawson Because you seem to be fixing a lot of these CRS UI things right now (Thanks!!!) another place that could use a warning is in the layer right click> Set layer CRS selector dialog. There is a big text box on the top that could use something. It currently is telling me that my layer has no reference system even though it is set to 26986 as shown on the bottom in this image. 
![image](https://user-images.githubusercontent.com/15817745/96198310-74558b00-0f22-11eb-9008-c3b133bc9f17.png)

**Comment by nyalldawson** [comment]
@baswein that one is already fixed on updated nightlies. Can you confirm?

**Comment by baswein** [comment]
Yes I can confirm that in  3.15 ad3f0a8f1e there is no longer that warning about the CRS not being set. However the right click choose a CRS is going to cause so many of my student to end up with their geometry in the middle of the Atlantic ocean because unless you know what you are doing you should not be changing the layer's CRS and now it is even easier. A warning in the CRS dialog will help. Which if I am reading the pull request correctly you set as:  
> "Changing this option does not modify the original data source or perform any reprojection of features. Rather, it can be used to override the layer's CRS within this project if it could not be detected or has been incorrectly detected. The Processing tool should be used to reproject features and permanently change a data source's CRS"   

Which looks great! Thanks again for making that change!
Unfortunately as it is now they will probably just choose one of the CRS's shown here and never get to the dialog. We will see if there are enough warnings in the CRS dialog it might sink in.   
![image](https://user-images.githubusercontent.com/15817745/96207686-ca81f880-0f39-11eb-8252-424dfeb9eeb2.png)
