### ISSUE TITLE
Distance matrix error for Standard (N x T) in QGIS 3.4.10

### ISSUE THREAD

**Issue by ChalktyGeo** [qgis/QGIS#32107]
### **Summary**
When running the distance matrix in QGIS 3.4.10 with the Standard (N x T) matrix I am receiving the following error message after 0.33 seconds in the algorithm log panel.

I have tested the same data in a QGIS 2 build, specifically 2.18.28, and it ran successfully with the desired result. 

**Error**

`Input parameters:
{ 'INPUT' : 'C:\\Users\\myname\\Desktop\\Test data\\Input point data.shp', 'INPUT_FIELD' : 'postcode', 'MATRIX_TYPE' : 1, 'NEAREST_POINTS' : 0, 'OUTPUT' : 'C:/Users/myname/Desktop/Test data/Test.csv', 'TARGET' : 'C:\\Users\\myname\\Desktop\\Test data\\Target point layer.shp', 'TARGET_FIELD' : 'Name' `}`

`Traceback (most recent call last):
File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python/plugins\processing\algs\qgis\PointDistance.py", line 145, in processAlgorithm
nPoints, feedback)
File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python/plugins\processing\algs\qgis\PointDistance.py", line 270, in regularMatrix
fields, source.wkbType(), source.sourceCrs())
Exception: unknown`

`Execution failed after 0.33 seconds`

### **Data and algorithm parameters used**
I have attached both SHP files used and the QGIS project file to this post for testing if needed. Below I have listed the ID fields used for each SHP file and included an image for ease.

- The input unique ID was set to "postcode"

- The target unique ID was set to "Name"

![image](https://user-images.githubusercontent.com/48433421/66119974-b63eb800-e5d1-11e9-8f6a-73ea0138f0b0.png)

### **Other observations that may be useful**

1. I receive the same error no matter what the output format is.
2. If I run the tool with a temporary layer output then the algorithm runs and a layer is created in the layers panel. However, when I go to view the attribute table QGIS crashes.
3. I have tried re-saving and converting them to single-point (even though they already are) to no avail.
4. They are both projected to ESPG: 27700 BNG. 
4. I have noticed two similar issues on GIS Stack Exchange and no definitive answers have been given for the cause. These can be found here:
[https://gis.stackexchange.com/questions/337410/error-when-running-distance-matrix-in-qgis-3-4-10?noredirect=1#comment550490_337410](url)
[https://gis.stackexchange.com/questions/278609/qgis-distance-matrix-execution-fails](url)

**Link to data**
[https://www.dropbox.com/sh/33v4dtbl6nk98j8/AADDbSo_x5EChM34-B0aWT4Ma?dl=0](url)

**Comment by gioman** [comment]
>  [https://www.dropbox.com/sh/33v4dtbl6nk98j8/AADDbSo_x5EChM34-B0aWT4Ma?dl=0](url)

@ChalktyGeo can you re-upload the data?
