### ISSUE TITLE
QGIS 3.4.12:  attribute table: Move selected to top does not work

### ISSUE THREAD

**Issue by bertramrabe** [qgis/QGIS#32115]
**Describe the bug**
in the attribute table the function <Move selected to top> does not work always. 

**How to Reproduce**
Especially when I insert a new dataset and I select it, then I save it (the selection keeps). When I use the function "Move selected to top" the dataset does not go to top. It is still selected, but it is not possible to get it to the top.
Sometimes the same happens, when I did not insert new datasets. Just select datasets, and in the attribute table the selected datasets do not move to the top.

**QGIS and OS versions**
QGIS 3.4.12
OS: ubuntu 18.04

**Comment by gioman** [comment]
duplicate

https://github.com/qgis/QGIS/issues/28914

https://github.com/qgis/QGIS/issues/31658
