### ISSUE TITLE
IAG GRS 1980 ou IAG GRS 1967 cannot be chosen as ellipsoid for measurements

### ISSUE THREAD

**Issue by FERRATON** [qgis/QGIS#32116]
If one of these ellipsoids is chosen, when reopening the project properties, the indicated ellipsoid becomes Clarke 1866

Another question: what is the difference between 
IAG GRS 1980 and GRS 1980(IUGG, 1980)?
(the latter ellipsoid does not reproduce the bug).

**Comment by nyalldawson** [comment]
Can you please confirm your proj version? (Available from the about dialog)

**Comment by FERRATON** [comment]
Version 5.2.0 (QGIS 3.4.5 et 3.8.3)

**Comment by nyalldawson** [comment]
This should be fixed already in proj 6 based builds

**Comment by FERRATON** [comment]
Thank Nyall

**Comment by gioman** [comment]
closing?

**Comment by FERRATON** [comment]
OK for me
