### ISSUE TITLE
Holes in polygon infill automatically when dissolve and save new file

### ISSUE THREAD

**Issue by dalyk85** [qgis/QGIS#32113]
hi, 

I have a polygon representing a flood extent and I wish to clean it by dissolving (to remove lines within the polygon). I use the QGIS vector geometry tool "fix geometries" firstly, followed by the dissolve tool. An example portion of the input polygon is shown below. 

![Input file](https://user-images.githubusercontent.com/53575300/66199913-bb663a80-e697-11e9-9602-169eda98d90e.jpg)

Whilst the output temporary file looks just fine (see below).

![Temporary file result](https://user-images.githubusercontent.com/53575300/66199926-c325df00-e697-11e9-865f-bd5773690875.jpg)

When  I save via exporting to shapefile, many of the holes infill, as shown below. 

![Saved shapefile result](https://user-images.githubusercontent.com/53575300/66199960-d042ce00-e697-11e9-8230-084b86e575da.jpg)
 
I have tested with GRASS dissolve and SAGA dissolve and they don't even remove all of the internal lines in the first place (the whole objective of "dissolving" I thought).

I have experienced this many times where the temporary file looks ok, but the exported shapefile form changes to show holes infilled and can't figure it out.  

Any help on how to successfully save a dissolved polygon without any internal lines appreciated. 
I am using QGIS version 3.6.0-Noosa  from the user interface and want to avoid having to do it via python scripting as I'm not accustomed to that way. Hoping there is a way to get the tools to function as described. 

Thanks

**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by dalyk85** [comment]
[Input and output files.zip](https://github.com/qgis/QGIS/files/3690069/Input.and.output.files.zip)

The input layer and output layer are attached now.

**Comment by DelazJ** [comment]
Hi @dalyk85 
Confirmed on master e47d55f: disolving the fixed geometries layer to temporary layer or gpkg works well. Using shp result in a single item with weird geometry

**Comment by dalyk85** [comment]
Further testing shows that if I export the temporary file to 'Mapinfo tab or Geopackage format the output file is ok, and the holes are not infilled. If I try Mapinfo MIF the holes are infilled. So the issue seems to be dependent upon what output file type is selected.

**Comment by dalyk85** [comment]
If I export to gpkg, I then need to convert that to shp, and when I do that the same problem arises.

**Comment by dalyk85** [comment]
So it seems there is no way to get it to shp without this odd infilling of holes bug occurring

**Comment by dalyk85** [comment]
I am struggling to understand how a temporary output layer looks ok but can become corrupted in a mere saving to shp exercise.

**Comment by gioman** [comment]
@dalyk85 how this differs from https://github.com/qgis/QGIS/issues/31041 ?

**Comment by dalyk85** [comment]
It is the same problem I guess. It was never resolved then either.

**Comment by gioman** [comment]
> It is the same problem I guess. It was never resolved then either.

so closing this as duplicate. If there are new infos please add them to the old ticket, thanks!

**Comment by dalyk85** [comment]
Previously you stated you resolved on Linux 3.4: QGIS, GDAL and SAGA tools

This problem is occurring for me using windows 10

**Comment by dalyk85** [comment]
So is this error still down as unresolved or have you stated is is resolved?

**Comment by gioman** [comment]
> Previously you stated you resolved on Linux 3.4: QGIS, GDAL and SAGA tools

I didn't said it was solved, I just said that I wasn't getting the same results on a different platform.

**Comment by dalyk85** [comment]
Ok...so it has been left untested in windows so.  Will there be any support who can test on windows or will it just lay idle?

**Comment by gioman** [comment]
>  or have you stated is is resolved

I didn't, I have stated that I wasn't getting the same results on a different platform, that is part of the troubleshooting effort that can lead a developer understand where is the underlying problem.

**Comment by dalyk85** [comment]
Well it seems to be falling on deaf ears as there has been no support with regards testing on windows. Not much hope for it every being resolved so.

**Comment by gioman** [comment]
> Well it seems to be falling on deaf ears as there has been no support with regards testing on windows. Not much hope for it every being resolved so.

it does not work like that. There is no guarantee that a particular issue will be fixed sooner than later (but in general if they are bad they usually are fixed pretty quickly). If the issue is a blocker for you or your organization you can look for having it fixed by one of the many developers/companies that offer commercial support.

**Comment by dalyk85** [comment]
Ok...thanks for clarifying the process. I guess I was at least hoping for someone to test it on the same setup (windows) to confirm that the issue occurs for others.

I will refrain from bringing up the issue on this again and hopefully it gets attention down the line. 
One interesting aspect is the output shapefile appears fine on ArcMap...so seems to be a display issue in QGIS perhaps. 
Thanks for your help...

**Comment by DelazJ** [comment]
>  I guess I was at least hoping for someone to test it on the same setup (windows) to confirm that the issue occurs for others.

This is what I did [above](https://github.com/qgis/QGIS/issues/32113#issuecomment-538345272), isn't it?

**Comment by dalyk85** [comment]
Yes it is...I meant the previous thread with gioman had never confirmed a test in windows, hence my reason for reposting. 
Thank you for testing and validating the issue.
