### ISSUE TITLE
Why would .qgz files need a temporary (T) attribute (Windows)

### ISSUE THREAD

**Issue by RudiU** [qgis/QGIS#32118]
**Describe the bug**

I just discovered that project files (.qgz) on our Win Server are not backed up by our Synology backup application. The reason for this behaviour is the T attribute which is added to the file in the moment it is saved. It occurs both on the windows server and on my local windows computer. Only if I save the project file as .qgs it doesn't get that T attribute. Since project files are not truely temporary files, and I'm not aware of a configuration option I suspect it to be a bug.
(The phenomenon was described earlier on gis.stackexchange, but there was no answer whatsoever:
https://gis.stackexchange.com/questions/306458/qgz-files-and-replication-thereof)
**How to Reproduce**

**QGIS and OS versions**
OS: Win 10 Pro, Win Server 2019
QGIS: At least all versions since April 2019 including 3.8.3

**Additional context**

**Comment by m-kuhn** [comment]
The qgz file is first written as a file in the standard temporary file location and later moved to the final location.
I could imagine that windows flags any file written in the temporay location as `T` and when it's later renamed (moved) to the final destination, this flag remains with the file.

**Comment by RudiU** [comment]
Hello Alessandro,

I just wrote a comment on github, but since I am not sure, if and to 
whom it is sent after the issue is closed I just repeat it here:

/Thank you for that fix! However, it might well be that removing the T 
attribute comes too late for automatic backups. On our system I need an 
additional rename operation to 'inform' the NAS backup about the newly 
saved file.//
//So I'd suggest to move the attribute removal up, operating on the 
tmpfile before it is renamed. I suppose, rename should delete the 
tmpfile anyway, so there would be no need for it keeping the T attribute(?)/

Thank you very much for your help - I'd wish to be able to contribute 
myself, but so far I didn't see how I could get a working development 
system running on my win computer within the limited time span I have 
left for GIS work...

Best wishes Rudi


Dipl.-Biol. Rudolf Uhl
FÖA Landschaftsplanung GmbH

Auf der Redoute 12
D-54296 Trier

Telefon ++49 +651 91048-20 (Durchwahl), -0 (Zentrale)
Email rudi.uhl@foea.de
Web www.foea.de


--------------------------------------------------
Geschäftsführung:
    Dipl.-Ing. Ute Jahns-Lüttmann
    Dr. Jochen Lüttmann
    Dipl.-Ing. Werner Zachay
Sitz der Gesellschaft:
    Trier, AG Wittlich, HRB 40305

Am 08.10.2019 um 21:35 schrieb Alessandro Pasotti:
