### ISSUE TITLE
rotate feature is frozen

### ISSUE THREAD

**Issue by klaus120566** [qgis/QGIS#32123]
**Describe the bug**

It is not possible to finish the rotate feautre
**How to Reproduce**
In Edit-Mode, select featrue and rotate it. The result is shown in the gut but not finished

**QGIS and OS versions**
3.9 and ubuntu 18.4.3

**Additional context**

**Comment by DelazJ** [comment]
Confirmed here. same version and platform. Serious bug imho. You can not end the action and QGIS somehow freezes. I had to force quit, making me lose what i was doing before i came across this report and wanted to give it a quick try.
_Repeat after me: "I will always save my work before I test anybody else bug report"_

**Comment by daveh2019** [comment]
3.10 Rotate feature (polygons) on Windows 10 freezes and eventually causes QGIS to have to be restarted.

**Comment by richardewaters** [comment]
I can confirm this issue on 3.10 Windows 10. Rotate freezes as soon as you try to complete the action. Only way out is to terminate QGIS.

**Comment by bellanz80** [comment]
> I can confirm this issue on 3.10 Windows 10. Rotate freezes as soon as you try to complete the action. Only way out is to terminate QGIS.

I Confirm

**Comment by pigreco** [comment]
confirm

OSGeo4W64b QGIS 3.10

**Comment by lbell** [comment]
Also happening on 3.10 Ubuntu. Was not an issue on 3.8.


QGIS version | 3.10.0-A Coruña | QGIS code revision | 6c816b4204
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.4.2 | Running against GDAL/OGR | 2.4.2
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 10.10 (Ubuntu 10.10-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Ubuntu 18.04.3 LTS
Active python plugins | mmqgis; profiletool; joinmultiplelines; SwapVectorDirection; NNJoin; LAStools; qgis_resources_sharing-master; CalculateGeometry; Climb; db_manager; processing; MetaSearch; CustomToolBar
