### ISSUE TITLE
Unable to Install Plugins - No Python Support Detected

### ISSUE THREAD

**Issue by iliebentritt** [qgis/QGIS#32135]
Hello, I am getting back on QGIS after a few years of not using it at my previous job.  In order to continue using QGIS, I downloaded QGIS 3.8 for Mac OS X a few days ago.

However, I am having issues utilizing basic functions of QGIS with the new version.  I looked up my plugins window, but was only greeted with eight available plugins in the entire repository.  When I opened up my plugins window to find out how I could install new plugins, I was greeted with this message:

<img width="875" alt="Screen Shot 2019-10-06 at 6 39 08 PM" src="https://user-images.githubusercontent.com/25887056/66277181-befceb80-e868-11e9-9f66-26cfb78368a1.png">

Adding to that, I looked on my Plugins menu from my options at the top of the screen and it does not give me a Python console.  This is confusing because I have Python 3.7 installed on my computer. 

How do I fix this problem?

**Comment by nyalldawson** [comment]
Which QGIS mac installer did you use? It's highly recommended that you use the "all-in-one" signed installers, which don't require any messing around with system python libraries.

**Comment by iliebentritt** [comment]
If I remember correctly, it was the all in one version, for QGIS 3.8.  I never had QGIS 3.4, so I don't know if that caused a problem.

Should I try reinstalling with the all-in-one installer?

**Comment by nyalldawson** [comment]
@iliebentritt 
I'd suggest that's a good starting move - remove all previous versions and reinstall the latest from the qgis site.

**Comment by iliebentritt** [comment]
I tried reinstalling qgis and it didn't work.  Any suggestions for next steps?

**Comment by gioman** [comment]
> I tried reinstalling qgis and it didn't work

probably here the problem is with some previous (or lack of ) python installation.

**Comment by QuantumNovice** [comment]
Which version of python do you have? If any?

**Comment by DelazJ** [comment]
> If I remember correctly, it was the all in one version, for QGIS 3.8. I never had QGIS 3.4, so I don't know if that caused a problem.

Which version of macos do you have? All in one installer is for >10.12 (see #31906)

**Comment by QuantumNovice** [comment]
I have mac OS 10.15 RN. I'll try to install it there to see if it cause any errors.

**Comment by felipem775** [comment]
same problem here. using linux mint 19.2

**Comment by BlissVictor** [comment]
Same problem here mac OS 10.12.6 (16G1710)

**Comment by Limsande** [comment]
Same issue here on Fedora 31. 

With QGIS 3.10.0 I got
```
ImportError: /lib64/libQt5Core.so.5: version 'Qt_5_PRIVATE_API' not found
```
on QGIS startup, and no Python support. After upgrading QGIS to 3.10.1 (tried both from Fedora package source, and the [Copr repo](https://copr.fedorainfracloud.org/coprs/dani/qgis/)) the error is gone but still no Python support.

I have Python 3.7.5 installed.

![about_qgis](https://user-images.githubusercontent.com/45884056/72248151-c285d880-35f6-11ea-8a4b-e44202c1c583.png)

**Comment by Limsande** [comment]
> Same issue here on Fedora 31.
> 
> With QGIS 3.10.0 I got
> 
> ```
> ImportError: /lib64/libQt5Core.so.5: version 'Qt_5_PRIVATE_API' not found
> ```
> 
> on QGIS startup, and no Python support. After upgrading QGIS to 3.10.1 (tried both from Fedora package source, and the [Copr repo](https://copr.fedorainfracloud.org/coprs/dani/qgis/)) the error is gone but still no Python support.
> 
> I have Python 3.7.5 installed.
> 
> ![about_qgis](https://user-images.githubusercontent.com/45884056/72248151-c285d880-35f6-11ea-8a4b-e44202c1c583.png)

Now the ImportError appears again. Somehow python3-qgis went missing, so I reinstalled it. The full error message is
```
Couldn't load SIP module.
Python support will be disabled.


Traceback (most recent call last):
  File "", line 1, in 
  File "/usr/lib64/python3.7/site-packages/qgis/__init__.py", line 70, in 
    from qgis.PyQt import QtCore
  File "/usr/lib64/python3.7/site-packages/qgis/PyQt/QtCore.py", line 24, in 
    from PyQt5.QtCore import *
ImportError: /lib64/libQt5Core.so.5: version `Qt_5_PRIVATE_API' not found (required by /usr/local/lib64/python3.7/site-packages/PyQt5/QtCore.so)


Python version:
3.7.6 (default, Dec 19 2019, 22:52:49) 
[GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]

QGIS version:
3.10.1-A Coruña 'A Coruña', exported
```
pip lists both PyQt4-sip and PyQt5-sip as installed.

**Comment by almereyda** [comment]
Same here on Fedora 30. Installing the QGIS package does not by itself install `python3-qgis`. Eventually this is rather a packaging issue with the distribution upstream, than an issue in QGIS?

**Comment by gioman** [comment]
> Eventually this is rather a packaging issue with the distribution upstream, than an issue in QGIS?

yes, if this is the problem then this ticket should be closed.

**Comment by almereyda** [comment]
As of https://fedoraproject.org/wiki/GIS, I am getting in touch with `#fedora-gis` on Freenode and am seeking to report there. Once we have the upstream ticket, it will be linked here and this can be closed.

**Comment by almereyda** [comment]
Okay, so it seems in Fedora this is, for now, intentionally not a dependency. The installation instructions for QGIS clearly state to install that package alongside.

- https://qgis.org/en/site/forusers/alldownloads.html#fedora

I cannot make informed comments on how this is intended to work with macOS or Linux Mint.

**Comment by ajesteves** [comment]
Hi. i also have this same problem in CentOS. After compiling qgis, when i run it, there is no python support, no plugins, no processing facilities.
Any help to overcome this issue, it will be welcome.

**Comment by yassineMrabet** [comment]
Same problem issue in Ubuntu 20.04. 

```
Couldn't load SIP module.
Python support will be disabled.


Traceback (most recent call last):
  File "", line 1, in 
  File "/usr/lib/python3/dist-packages/qgis/__init__.py", line 70, in 
    from qgis.PyQt import QtCore
  File "/usr/lib/python3/dist-packages/qgis/PyQt/QtCore.py", line 24, in 
    from PyQt5.QtCore import *
ImportError: /lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.14' not found (required by /home/nesrine/.local/lib/python3.8/site-packages/PyQt5/QtCore.abi3.so)


Python version:
3.8.2 (default, Apr 27 2020, 15:53:34) 
[GCC 9.3.0]

QGIS version:
3.10.4-A Coruña 'A Coruña', exported

Python path:
['/usr/share/qgis/python', '/home/nesrine/.local/share/QGIS/QGIS3/profiles/default/python', '/home/nesrine/.local/share/QGIS/QGIS3/profiles/default/python/plugins', '/usr/share/qgis/python/plugins', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/home/nesrine/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/dist-packages', '/usr/local/lib/python3.8/dist-packages/Mentalist-1.0-py3.8.egg', '/usr/lib/python3/dist-packages']
```

I tried to set the Qt environment to Qt_5.14 as the default installed is version in 5.12, with these [instructions](http://www.programmersought.com/article/5503486993/). However it doesn't work.
I there any config files to fix this problem ?

**Comment by gioman** [comment]
> Which QGIS mac installer did you use? It's highly recommended that you use the "all-in-one" signed installers, which don't require any messing around with system python libraries.

@iliebentritt correct, no issues whatsoever under macOS Catalina with the all in one installers.

**Comment by hob814** [comment]
i'm having the same problem on fedora 32

> Hello, I am getting back on QGIS after a few years of not using it at my previous job. In order to continue using QGIS, I downloaded QGIS 3.8 for Mac OS X a few days ago.
> 
> However, I am having issues utilizing basic functions of QGIS with the new version. I looked up my plugins window, but was only greeted with eight available plugins in the entire repository. When I opened up my plugins window to find out how I could install new plugins, I was greeted with this message:
> 
> <img alt="Screen Shot 2019-10-06 at 6 39 08 PM" width="875" src="https://user-images.githubusercontent.com/25887056/66277181-befceb80-e868-11e9-9f66-26cfb78368a1.png">
> 
> Adding to that, I looked on my Plugins menu from my options at the top of the screen and it does not give me a Python console. This is confusing because I have Python 3.7 installed on my computer.
> 
> How do I fix this problem?

**Comment by benjaminforest** [comment]
Hi, 
Same problem here. Anyone has any success in solving it ? I can import it from python fine, so I suppose it's a matter of PATH but I do not have more.
Running up to date Fedora 33

**Comment by muety** [comment]
I'm having the same problem as @Limsande and don't know to fix it. Any ideas?

**Comment by jorgeortizamos** [comment]
I had the same problem with Qgis, I tried many versions, I installed and uninstalled them, there was no way, it didn't allow me to install plugins, finally what I did was take the DLL files from another computer with the same windows and compile and paste in the system 32 and Syswow64 folders (in my case), all the DLLs. And it finally worked for me.

**Comment by jorgeortizamos** [comment]
> I had the same problem with Qgis, I tried many versions, I installed and uninstalled them, there was no way, it didn't allow me to install plugins, finally what I did was take the DLL files from another computer with the same windows and compile and paste in the system 32 and Syswow64 folders (in my case), all the DLLs. And it finally worked for me.



> Which QGIS mac installer did you use? It's highly recommended that you use the "all-in-one" signed installers, which don't require any messing around with system python libraries.

I had the same problem with Qgis, I tried many versions, I installed and uninstalled them, there was no way, it didn't allow me to install plugins, finally what I did was take the DLL files from another computer with the same windows and compile and paste in the system 32 and Syswow64 folders (in my case), all the DLLs. And it finally worked for me.

**Comment by nmonnerat** [comment]
I have the same problem with Linux Mint Uma
![Captura de tela em 2022-01-19 16-50-41](https://user-images.githubusercontent.com/23378665/150203663-46e79708-393b-4e0f-b7eb-624a5e0b9ec4.png)

**Comment by jesuspolo** [comment]
Same problem in Windows. In version 3.16 I have many plugins bit as I've been installing newer versions, the plugins disappear.

**Comment by syanenko** [comment]
Hi,
Has anyoune found a solution for this issue ? I have it on:

![image](https://user-images.githubusercontent.com/6688301/227772662-e5f51f3b-bb64-4681-82a9-50a9461c410b.png)

![image](https://user-images.githubusercontent.com/6688301/227772693-01f2b8c6-eb30-4d6a-ad65-5d42e8696e8a.png)

Thanks on advance.

**Comment by syanenko** [comment]
Running:
"C:\Program Files\QGIS 3.28.0\bin\setup.bat" 
solves the problem.

**Comment by eric66-fr** [comment]
I have Windows 8, all 64 bits libraries and programs, python 3.8 (x64), and installed QGIS 3.34. I have the same problem : python not active, though python 3.12.8 is displayed in "About...". QGIS came along with python 3.12, but when running that python.exe (in QGIS folder), it says "PssQuerySnapshot not found in python312.dll". Installing QGIS 3.14 detects python ok (and I can install extensions). With 3.34 I tried to modify the PATH to my python 3.8, but same result : python not active (I only have python.exe, not python3.exe nor pythonw.exe in my python 3.8 bin directory).
