### ISSUE TITLE
TestSagaAlgorithms: line 139, in check_algorithm: 'NoneType' object has no attribute 'checkParameterValues'

### ISSUE THREAD

**Issue by strk** [qgis/QGIS#32143]
I'm guessing lack of some dependency is not disabling Saga test ?
```
======================================================================
ERROR: test_algorithms:1
'Raster tools - Invert grid', {'algorithm': 'saga:invertgrid', 'name': 'Raster  (__main__.TestSagaAlgorithms)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/qgis/qgis-no-override-testdata/python/plugins/processing/tests/AlgorithmsTestBase.py", line 139, in check_algorithm
    ok, msg = alg.checkParameterValues(parameters, context)
AttributeError: 'NoneType' object has no attribute 'checkParameterValues'
```

**Comment by strk** [comment]
@m-kuhn you are documented to be author of processing/tests/AlgorithmsTestBase.py so asking you: should we _skip_ the test if an algorithm is not found ? (this is the case for me). Or is that a real error to deal with ?

In my case the missing algorithm is:
Running alg: "saga:multipleregressionanalysispointsandpredictorgrids"

**Comment by nyalldawson** [comment]
@strk it should probably be togglable via a cmake switch

**Comment by strk** [comment]
I confirm my local problem being there's no SAGA installed on my system

src/core/qgsmessagelog.cpp:29 : (logMessage) [177ms] 2019-10-07T10:23:22 Processing[2] 
Problem with SAGA installation: SAGA was not found or is not correctly installed

My question is: do we want tests to fail if SAGA is missing or just to skip the tests ?
As we dont' install SAGA ourselves I think we should just skip the test. Not sure if we should do it at CMake level though, as you may install SAGA _after_ you built QGIS ?

**Comment by nyalldawson** [comment]
> My question is: do we want tests to fail if SAGA is missing or just to skip the tests ?

I think we want to test to fail. Otherwise the test no longer checks for correct operation of the saga detection code itself. 

That's why I think this test should only be enabled via a cmake option (defaulting to off, but on for Travis).

**Comment by strk** [comment]
@nyalldawson I'm testing this in #32199 can we continue discussion there ?
