### ISSUE TITLE
PostGIS/geojson: Cannot input negative numbers in int fields

### ISSUE THREAD

**Issue by Gunganis** [qgis/QGIS#32149]
While working with PostGIS or geojson or WFS layers, when adding a new feature or editing the attribute table, a negative number (e.g. -10) is added in a field with datatype `int` it is automatically changed to `NULL`. 

In more detail:
When creating a new feature, in the dialog that appears when finished drawing, only values >0 are accepted. If negative values are entered they are automatically changed to `NULL`.
When editing the attribute table it's the same, only values >0 are accepted and negative values are changed to `NULL`.
But in the attribute table, while in edit mode, if the column is selected and in the expression panel a negative number is added and then the Update All or Update Selected or Update Filtered button is clicked then the values are changes correctly.

So, the issue is of course not with storing the negative numbers but with the way inserting them.

The column is `int` in postgresql which corresponds to the int32 of QGIS. When altering the column to `bigint` it corresponds to the int64 of QGIS and the problem is fixed. But it seems pointless to convert everything to `bigint`.

Note: This is not an issue when working with shp.

**Comment by elpaso** [comment]
I cannot reproduce on master.

Can you attach a sample project and related SQL data to reproduce this issue?

Also, you don't say which version and which operating system you are using (even if that information is required in the issue template).

**Comment by Gunganis** [comment]
Thank you for the response.

The version I am currently using is the 3.8.1-Zanzibar in Ubuntu 18.04.3. I had the same issue with the 3.4 and I ended up using the 2.18.17 which works fine. 

I am uploading a geojson exported from the database with two columns for integers, the `col_int` is integer (32bit) and the `col_bigint` is big integer (64bit). 

[test_data.zip](https://github.com/qgis/QGIS/files/3701418/test_data.zip)

Let me know if you need anything else
