### ISSUE TITLE
Grid cross and text orientation on rotated maps and unwanted shortcut generation

### ISSUE THREAD

**Issue by John-Grubb** [qgis/QGIS#32142]
When making a non-north up map in Print Layout the grid/geographical labels for a projection grid remain either perpendicular or horizontal (dependant on setting) relative to the map window. Would very much like an option added to have them rotate to be in line with the grid lines. Also, when using grid crosses these should rotate so that the cross is oriented north/south and east/west relative to the projection. Also, the Admiralty-style ("zebra") geographical grid border doesn't plot properly for non-north up maps, either.

I can't see any options anywhere and extensive Googling with various QGIS-specific search terms hasn't returned any user forum solutions.

Screenshot attached to illustrate how crap it looks without labels and crosses oriented relative to north.

Also I would really like for QGIS to stop creating a shortcut in the root of the Start menu each time I launch it. I don't like this tiles/task launcher thing and use Classic Shell to give me my tried, trusted and damn well used to it Start menu with all my application shortcuts grouped in category folders. I don't want a shortcut I don't want forced on me every time I use an application and I'm fed up with deleting the damn thing all the time. Again, extensive Googling - when I have the time - gives no solution. 

And finally! Please, please, please stop V3.8 from crashing every time I exit the program. Ta everso.

Running 3.8.3 on Win10 build 1903. Issues above existed before the Windows update to 1903.

![07-10-2019 06-46-16](https://user-images.githubusercontent.com/56247575/66291506-5ce0cc80-e8e2-11e9-91fb-b3c2f0bf22b5.jpg)

![07-10-2019 06-45-32](https://user-images.githubusercontent.com/56247575/66291106-3f5f3300-e8e1-11e9-9bcb-f303f3bb4f2b.jpg)

**Comment by elpaso** [comment]
please file separate tickets for separate issues

**Comment by nirvn** [comment]
@John-Grubb , as was just said a minute ago, please file one feature request or issue at a time. Keep those screenshots and details attached to requests and issues, that's helpful. Try not to use words like 'crap' or 'damn', that'll probably avoid pissing off benevolent developers who might otherwise be interested in looking into your issues :wink: 

Regarding the crash-on-exit, it's been fixed, meaning the next round of releases (Oct. 25th) will be crash-free on exit. :tada:

**Comment by gioman** [comment]
>  Try not to use words like 'crap' or 'damn', that'll probably avoid pissing off benevolent developers who might otherwise be interested in looking into your issues

agree, closing this, please open separate tickets (do not open one for the crash on exit, is already fixed in the upcoming new releases).
