### ISSUE TITLE
Entries disappearing in QGIS Browser

### ISSUE THREAD

**Issue by Meibes** [qgis/QGIS#32159]
Hello,

I noticed that some of my QGIS Browser-Entries disappeared on their own. A few weeks back it was one WMS and today it was my PostGIS-connection.

Yesterday I was working with some of the PostGIS-layers and when I started QGIS today my whole PostGIS-Connection was gone. I was using the "db manager" yesterday quite a lot and I played with virtual layers. I was using some queries and added them as layers. I did not query the PostGIS-layers but they were loaded as layers. If I remember correctly I was also playing with virtual layers when the WMS disappeared and the WMS was also loaded as a layer.

My guess would be that there is an issue when query-layer are loaded/removed from the project?

e1:I am using QGIS 3.8.3
e2:There is no problem with PostGIS - I entered all neccessary information and could access all my layers again

**Comment by roya0045** [comment]
Could you provide a way to replicate this reliably?

**Comment by jgrocha** [comment]
If you create a new profile, all connections are lost (the connections are stored on the profile). Have you changed the profile?

@Meibes These connections are stored under the profile folder. If you go to Settings → User Profiles → Open Active Profile Folder, you can see all profile related files. There is a folder called QGIS, with QGIS3.ini, where these connections are stored. It is a text file. You can inspect that file.

**Comment by Meibes** [comment]
I tried a couple of things but I couldn't replicate it by now.

I did not create a new profile and my other WMS are still there (but I'm not sure if all are still there, I have like 30 of them and use only some of them regularly, so if one goes missing it might take a while for me to notice if I don't use it often).

I've looked into the qgis3.ini and it's a huge file, my new postgis connection is the last entry - I guess this is normal?

I'm also working with 2-3 instances of QGIS 3.8.3 and 3.4.12 open at the same time, perhaps this could be a reason too.

**Comment by andreasneumann** [comment]
If you are on Windows and in a company LAN - I would just add that all the QGIS settings are residing in the roaming profile of Windows.

It is widely known that roaming profiles on Windows are sometimes problematic. The profiles are loaded from a central network server when you log in and copied back to that server if you log out. In case the network connection is broken during logout (e.g. when you disconnect your network during logout), you might end up with an old version from the central profile server.

Could this be the case in your situation?

**Comment by Meibes** [comment]
I am on Windows and in a company LAN but my profile is local because we don't have a server. We do have a NAS though.

**Comment by Meibes** [comment]
happend again.

I opened a qgis project, added a wms from my browser (http://sgx.geodatenzentrum.de/wms_topplus_open) and on closing qgis, qgis crashed, after that the wms was missing from my list. here the crash:

Crash ID: 8ca1aab4e8acf1a14067830db51cd86a1bc2e775


Stack Trace


osgeo::proj::datum::Datum::conventionalRS :
osgeo::proj::datum::Datum::conventionalRS :
osgeo::proj::datum::Datum::conventionalRS :
QgsCoordinateReferenceSystemPrivate::~QgsCoordinateReferenceSystemPrivate qgscoordinatereferencesystem_p.h:98
QgsCoordinateReferenceSystem::~QgsCoordinateReferenceSystem qshareddata.h:169
QMapNode::destroySubTree qmap.h:129
QMapData::destroy qmap.h:249
`QgsPostgresProvider::crs'::`5'::`dynamic atexit destructor for 'sCrsCache'' :
::operator() :
__crt_seh_guarded_call::operator(), & __ptr64, > :
execute_onexit_table :
dllmain_crt_process_detach dll_dllmain.cpp:109
dllmain_dispatch dll_dllmain.cpp:207
LdrShutdownProcess :
RtlExitUserProcess :
exit_or_terminate_process :
common_exit :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.10.1-A Coru�a
QGIS code revision: ef24c526da
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by gioman** [comment]
@Meibes not sure how much sense makes keep this open as this seems really a local issue.

**Comment by Meibes** [comment]
@gioman i'm rarely using qgis at the moment so I can't say if this still happens but because no one other reported this too it seems like a local issue - I'm ok with closing it
