### ISSUE TITLE
Crash / hang when saving a layer - numerous times

### ISSUE THREAD

**Issue by DCucchiaro** [qgis/QGIS#32160]
## User Feedback

I was saving a layer

## Report Details

*Crash ID*: 1193b9724c8c516ed15d8d7521f2d5f6a7b37057

*Stack Trace*
<pre>
QList<QItemSelectionRange>::size :
QTableView::paintEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:403
QCoreApplication::notifyInternal2 :
QWidgetPrivate::drawWidget :
QApplication::windowIcon :
QWidget::event :
QgisApp::event qgisapp.cpp:1870
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:403
QCoreApplication::notifyInternal2 :
QWidgetPrivate::scrollRect :
QWidgetPrivate::invalidateBuffer_resizeHelper :
QWidget::repaint :
QWidget::repaint :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:403
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:403
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1567
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.8.3-Zanzibar
QGIS code revision: 685d8b15d2
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by gioman** [comment]
@DCucchiaro the report is largely incomplete, you should tell us what type of layer (raster? vector?) what format (shape? gpkg? other?) and the exact, detailed steps that lead to the crash.

Also you should try a new/clean QGIS profile, without installing any 3rd party plugins.

Attaching a sample project+sample data is also highly suggested.

**Comment by DCucchiaro** [comment]
Ok ok - next time I'll be more detailed and respond with the details -
please cancel my issue #32160

**Comment by gioman** [comment]
> Ok ok - next time I'll be more detailed and respond with the details - please cancel my issue #32160

did a new profile worked for you?

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
