### ISSUE TITLE
Renaming macOS app causes authentication error

### ISSUE THREAD

**Issue by 71vl17** [qgis/QGIS#32163]
**Describe the bug**
If I rename the QGIS .app-file in my applications folder to any other, for example - "QGIS.app", I'll get an error "Authentication System: DISABLED. Resources authenticating via the system can not be accessed".
Renaming it back to "QGIS3.8.app" makes everything fine.
No plugins installed, I have fresh, just downloaded version of QGIS, no previous installations.

**How to Reproduce**
1. Rename "QGIS3.8.app" in your applications folder to "QGIS" or something
2. Open renamed app
3. See the error

**QGIS and OS versions**
macOS Mojave 10.14.6 (18G87)
QGIS 3.8.3

**Additional context**
It's cool that name of the app shows it's version, but it's not cool that I can't hide to stop seeing damn digits.
Thank you.

**Comment by PeterPetrik** [comment]
@71vl17 Hi, the renaming of the QGIS application is not possible since the libraries are resolved by absolute paths on MacOS in the installation. Frankly I am surprised that the application starts at all after renaming. 

Can you please expand on what is the use-case for renaming of the Application in the MacOS? Since to allow renaming of the QGIS would be significant work (>~ week at least)...

**Comment by kyngchaos** [comment]
Odd.  The QGIS app should be using relative paths for all libraries.  My build has always done that.  I can run it with any name and from any folder.

-----
William Kyngesburye
<kyngchaos@kyngchaos.com>
<http://www.kyngchaos.com>

Don't Panic

**Comment by PeterPetrik** [comment]
@kyngchaos you are right, technically it is possible. But since the qgis-mac-packager is written in a way it uses absolute paths, it would need quite refactoring to allow relative paths.

**Comment by kyngchaos** [comment]
Don't you use the QGIS_MACAPP_BUNDLE option?  It's made to change all library paths for bundled items to use relative paths.  This should be expanded for the Mac packager.  It's something that's been there waiting for expanding to a more inclusive bundling.  It can even be customized with a QGIS_MACAPP_BUNDLE_USER script (I do that for GRASS and SAGA bundling).

It could get messy to include everything possible.  Maybe an option to bundle a whole "support" folder is needed.

-----
William Kyngesburye
<kyngchaos@kyngchaos.com>
<http://www.kyngchaos.com>

Don't Panic

**Comment by 71vl17** [comment]
@PeterPetrik Well, it’s no special purposes, I just want it to look sleek. I don’t have «1Password 7.5.3» installed, it’s just «1Password»

**Comment by 71vl17** [comment]
@PeterPetrik So... just fix it some day please

**Comment by PeterPetrik** [comment]
@kyngchaos we do not use `QGIS_MACAPP_BUNDLE` since when designing the packager I felt that writing such stuff in CMAKE script language is a bit over-stretching of the capabilities of the tool. The functionality is replicated in python scripts inside QGIS-Mac-Packager.

**Comment by kyngchaos** [comment]
You can run a python script from cmake.

This is something I mentioned way back when you were asking about packaging - I think bundling functions should stay part of the build/install process since it's essentially an installation process.  The "packaging" is a different process.

-----
William Kyngesburye
<kyngchaos@kyngchaos.com>
<http://www.kyngchaos.com>

Don't Panic

**Comment by andyanderson** [comment]
By moving QGIS3.4 into a subfolder, for example, /Applications/QGIS/QGIS3.4, this bug also appears.

I routinely place my personally installed applications into subfolders within /Applications, to organize them by type (e.g. “Analysis” or “Programming”), group them with related files (e.g. QGIS 2.x and QGIS 3.x), and find them more easily amongst dozens of apps.

I think every application should avoid using absolute paths whenever possible, and that certainly includes items that are within the same package.

**Comment by NetworkNed** [comment]
It's not a great first impression to see this error message the first time one opens a program.

**Comment by OzDetect** [comment]
Hi, Im. a beginner with all this, and I'm having the same problem, Tried renaming it, Still has the same error

Any solutions so I can get using on QGIS?

**Comment by PeterPetrik** [comment]
For now, you need to keep the original installation directory `/Application/QGIS<ver>/`. We work on the new bundling method that will allow rename of the application, probably landing with release of QGIS 3.14

**Comment by NetworkNed** [comment]
>  For now, you need to keep the original installation directory /Application/QGIS<ver>/

I hope you'll forgive me for butting in @PeterPetrik, but I think a newcomer would find it easier to understand it's explained that for the moment *QGIS mustn't be renamed and must be kept in the top level /Applications folder.*

`QGIS<ver>.app` may be a directory, but on a Mac it just shows as an icon in the Applications folder. Clicking on it doesn't open the folder and show the contents, it just starts the app.

**Comment by iod-ine** [comment]
I have the same problem with a freshly installed QGIS 3.14. I tried to install it for my user only, in `/Users/<user>/Applications`, and it caused an authentication error. Reinstalling to `/Applications` helped, however it would be very nice to be able to install only for myself.

**Comment by PeterPetrik** [comment]
Thanks to the QGIS 2020 Grants, we manage to replace absolute paths with the relative paths so the application can be moved around. So far it is only implemented in the nightly2 builds https://qgis.org/downloads/macos/nightly2/

**Comment by andyanderson** [comment]
Thanks, Peter!
