### ISSUE TITLE
Can not edit edit vertex coordinates if "Local (currency format, number and dates)" is not English US

### ISSUE THREAD

**Issue by xsaiama** [qgis/QGIS#32195]
Hello.
Whenever I want to edit the value of a vertex (for Z, usually) I have to choose "English US" for "Local (currency format, numbers and dates)" for it to work. If this setting is set to "French Canada" and probably for many other languages, it does not work.

**Comment by gioman** [comment]
@xsaiama duplicate of https://github.com/qgis/QGIS/issues/29682 ?

**Comment by xsaiama** [comment]
Sorry.

I did some research but I did not find. The interface of GitHub is less familiar to me and I probably did not do the research in the right way.
