### ISSUE TITLE
Error during program shutdown

### ISSUE THREAD

**Issue by gibuja** [qgis/QGIS#32190]
**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

## User Feedback

This error occurred during program shutdown

## Report Details

*Crash ID*: 41bd556bfb4cb3857ad8b303df49560eb10217ac

*Stack Trace*
<pre>
proj_lpz_dist :
proj_lpz_dist :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::QgsCoordinateTransform :
QHashData::free_helper :
QgsCoordinateTransform::addToCache :
QgsCoordinateTransform::invalidateCache :
QgsApplication::exitQgis :
QgisApp::~QgisApp :
CPLStringList::operator char const * __ptr64 const * __ptr64 :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.4.11-Madeira
QGIS code revision: 9a8a6d4687
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by NathanW2** [comment]
Upgrade to 3.4.12 as this has already been fixed.

**Comment by nirvn** [comment]
It's already fixed, but not part of 3.4.12. It'll be the next release at the end of this month.

Until then, rest assured this inconvenient crasher is in no way harmful to your data or projects.

**Comment by gibuja** [comment]
Ok, Tks!
I verified that my QGIS version checker don't identified the 3.4.12 version.

**Comment by NathanW2** [comment]
@nirvn Oh I thought it made it into 4.12 but I didn't check the release.
