### ISSUE TITLE
Missing SOL format in mesh list

### ISSUE THREAD

**Issue by saberraz** [qgis/QGIS#32191]
When I try to attach a mesh quantity SOL file (BASEMENT) is not listed. The format is supported, so it is just a missing extension in the list:
![image](https://user-images.githubusercontent.com/2649047/66579560-e9a2b900-eb74-11e9-9c9d-1f6863e09be6.png)

**Comment by PeterPetrik** [comment]
This is MDAL upstream issue, raised the issue in the tracker
