### ISSUE TITLE
"Merge features" and "merge feature attributes" have broken numerical functions

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#32208]
See what is reported as count in the following screenshot (master 3.9 a3ef3899 but also occurs on 3.8 (and maybe 3.4?))![image](https://user-images.githubusercontent.com/7983394/66642509-304bee00-ec1d-11e9-8a4e-ce332f68820a.png). The other functions also return wrong values

**Comment by roya0045** [comment]
Is it only the preview that is wrong or is it the output itself?

**Comment by DelazJ** [comment]
Yep, sorry, I forgot to mention it, the wrong value is added to the feature(s). The issue is more critical.
