### ISSUE TITLE
Please Include Pandas Package in PyQGIS

### ISSUE THREAD

**Issue by slalomchip** [qgis/QGIS#32212]
Please add the `pandas` package in the PyQGIS distribution.  Without administrator privileges at work, I am unable to `python -m pip install pandas`.  `pandas` is an extremely convenient way to work with some feature layers.  Adding `panda` to PyQGIS will help users like me that cannot add packages, but will alleviate the need for many other users to do a pip install.

**Comment by Saijin-Naib** [comment]
Can you use the --user flag (python -m pip install pandas --user) to put it into the user packages directory to get around the need for admin?

**Comment by slalomchip** [comment]
I did the pip install at home.  At work, QGIS is virtualized (with Citrix).  The cmd.exe is not available to us, but Powershell is.  Regardless, the network does not have an internet connection.  I would have to get a whl package, but I don’t have the privileges to move the whl to the network.

 

To me, adding Pandas or GeoPandas to the PyQGIS distribution is a “no-brainer”.  Basically, a feature attribute table is DataFrame.  Using pandas (or GeoPandas) will make scripts a lot easier to write and more efficient to run.  Pandas is a standard across the Python community for sorting, pivoting, performing numeric operations, etc. on dataframes.

 

Please consider adding Pandas (or GeoPandas) to an upcoming release.

 

Thank you,

Chip Shand

**Comment by SrNetoChan** [comment]
Unfortunately, AFAIK it's not that simple. I believe there are some
dependencies incompatibilities between geopandas and QGIS. If I recall,
they rely on different versions of GDAL or GEOS.

So the reason why it's not available is more of a technical problem, not a
question of no one being interested in that.

Alexandre Neto

A quarta, 16/10/2019, 00:20, slalomchip <notifications@github.com> escreveu:

**Comment by slalomchip** [comment]
Thank you.  I read that there are some compatibility issues between QGIS and GeoPandas.  But the “out-of-the-box” Pandas seems to work without issue (at least it did for my script using QGIS 3.8.3).  Are there known issues with between QGIS and the regular version of Pandas?  Could Pandas be included in a future release?

 

Thanks!

Chip Shand

**Comment by stev-0** [comment]
I just updated OSGeo4W and I was prompted to download python3-pandas, so I think potentially your wish may have been granted, depending on how you install QGIS.

**Comment by slalomchip** [comment]
Thank you!

**Comment by jef-n** [comment]
> Thank you! 

No problem.

**Comment by stev-0** [comment]
Can someone close this as it's done
