### ISSUE TITLE
Crashed QGIS Zanzibar while trying to add a vector file

### ISSUE THREAD

**Issue by ColinPSweeney** [qgis/QGIS#32214]
QGIS crashed as I tried to upload a vector file. No layers were active at the time. I tried multiple times in a row. QGIS crashes once I click the button to try to navigate to the file directory.

**Comment by gioman** [comment]
@ColinPSweeney try with a new/clean QGIS profile, no 3rd party plugins installed.

**Comment by stev-0** [comment]
I suggest closing due to insufficient information and age
