### ISSUE TITLE
Unable to install QGIS

### ISSUE THREAD

**Issue by kitkat517** [qgis/QGIS#32217]
trying to launch app on my windows 10 desktop, after admin installed QGIS and it keeps crashing. here is the output:
FYI

Crash ID: 9dd447e8923a898061d2ea6718b134d43fc7e2b3

Stack Trace

QList::size :
QgsMessageBar::pushMessage :
QgsMessageBar::pushInfo :
QgisApp::showSystemNotification :
QgisApp::authMessageOut :
QMetaObject::activate :
QgsAuthManager::messageOut :
QgsAuthManager::authDatabaseConnection :
QgsAuthManager::sslCertCustomConfigByHost :
QgsNetworkAccessManager::createRequest :
QNetworkAccessManager::get :
QgsVectorLayerLoadStyleDialog::updateLoadButtonState :
QgsVectorLayerLoadStyleDialog::updateLoadButtonState :
QgisApp::QgisApp :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.4.4-Madeira
QGIS code revision: 73c31df831
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.0
Running against GDAL: 2.4.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by roya0045** [comment]
I'm not sure what is causing a crash but is your app blocked by the firewall out of curiosity?

**Comment by nyalldawson** [comment]
Update to a later version (either 3.8.3 or a later 3.4 release). This is already fixed

**Comment by kitkat517** [comment]
Yes most likely it is
