### ISSUE TITLE
Change in how feature posting works when using Time Manager plugin

### ISSUE THREAD

**Issue by CoryAlbrecht** [qgis/QGIS#32228]
3.8.3 0b21735e28 on Ubuntu 19.04

I create timeline maps and I use the awesome Time Manager plugin. My PostGIS layers have Start_date and end_date fields that Time Manager uses to show features or not based on what timestamp it is set to.

It used to be that if I had a feature that was changing, I would use the following procedure:

1. set start_date and end_date of original feature, e.g. 2001-01-01, 2001-01-10, and save layer
2. copy original object
3. move Time Manager to a time point after the original feature's end_date, e.g. 2001-01-11
4. see the original feature disappear on canvas redraw
5. paste in a new feature, it would get drawn on the canvas even though the start_date and end_date fields copied from the original feature would mean it should not be showing
6. feature attributes form would open
7. edit the start_date and end_date fields to something appropriate, e.g. 2002-01-11, 2001-01-20
8. save the layer back to the PostGIS DB just in case QGIS crashes while editing
9. edit the shape of copied feature

That way if I use Time Managers forward and backward buttons to walk through the timeline, and when the original feature disappears because it no longer fits the date constraint from Time Manager the modified new feature would appear, and so on.

But now when I get to step 5 to paste the copied feature, it does not appear and the feature attributes form does not get shown. If I use Time Manager to go backward to 2001-01-10 I see two identical features (except for a unique field). The copied feature is a new feature, so why isn't the feature attributes form opening any more?

**Comment by gioman** [comment]
@CoryAlbrecht is this a QGIS problem or a Time Manager plugin one? If is the latter this must be reported to the plugin author, not here.

**Comment by CoryAlbrecht** [comment]
Hi @gioman,

Please tell me hat was unclear, especially that last paragraph, and I will expand.

Since the problem occurs on pasting the feature and the attributes form is not opening like it used to, that doesn't sound like a TimeManager problem to me.

**Comment by gioman** [comment]
> Please tell me hat was unclear, especially that last paragraph, and I will expand.

Hi @CoryAlbrecht I'm sorry, it is still unclear to me. I'm not familiarized with the Time Manager plugin and in general I would appreciate a description of the issue that would allow us to replicate/test without the use of 3rd party plugins.

**Comment by CoryAlbrecht** [comment]
@gioman All TimeManager does is add a provider feature filter to the layer of the form

"start_date" < '1880/09/01' AND "end_date" >= '1880/08/31'

I replicated the issue by removing TimeManger plugin and setting that filter manually.

**Comment by gioman** [comment]
> I replicated the issue by removing TimeManger plugin and setting that filter manually.

please attach a dump of your table with sample data in it. Also please detail steps to replicate without using the TM plugin. Thanks.

**Comment by CoryAlbrecht** [comment]
1. Create a PostGIS layer with columns start_date and end_date as DATE and add the layer to your project
2. In Layer Properties→Source, add a provider feature filter of "start_date" < '1880/09/01' AND "end_date" >= '1880/08/31'
3. toggle layer editing to on
4. add a feature with start _date='1870-07-15', end_date='1880-08-31'
5. toggle layer editing to off
6. Select that new feature and copy it.
7. In Layer Properties→Source, change the provider feature filter of "start_date" < '1880/09/01' AND "end_date" >= '1880/08/31'
8. See the feature disappear fro view
9. toggle feature editing to on
10. Paste the copied feature
11. See how pasted feature does not appear on map canvas and the feature attributes dialog window does not pop up for you to edit the attributes

**Comment by gioman** [comment]
> See the feature disappear fro view

it does not disappear, please note that the filter clauses in 2) and 7) are identical. Is this correct?

**Comment by CoryAlbrecht** [comment]
@gioman  My bad, that was a typo on my part. Fixed.

**Comment by gioman** [comment]
>     11\. See how pasted feature does not appear on map canvas

@CoryAlbrecht the fact it does not show is totally expected: you have a filter that it does *not* includes the feature you copied, so it does not includes the feature you pasted as it has identical attributes.

>     the feature attributes dialog window does not pop up for you to edit the attributes

pasting feature never triggered the attributes dialog/form to pop up.

**Comment by CoryAlbrecht** [comment]
Except until recently that copied feature used to show on the  canvas after pasting so you could edit it and do things like change those dates. Even though the dates might be wrong for that filter, it would still be visible until you saved the layer.

**Comment by gioman** [comment]
> t would still be visible until you saved the layer.

correct, that is what I see here.

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
