### ISSUE TITLE
Something strange with "Generate XYZ tiles (Directory)"

### ISSUE THREAD

**Issue by IMMSPgisgroup** [qgis/QGIS#32220]
After using "Generate XYZ tiles (Directory)" tool some tiles have one pixel transparent column, like this. 
![25](https://user-images.githubusercontent.com/33963849/66692989-9d5a9480-ecac-11e9-99dc-7e91e6d8f7aa.png)
![image](https://user-images.githubusercontent.com/33963849/66693150-71d8a980-ecae-11e9-9899-2dc3648c3fa6.png)

**How to Reproduce**
I used tile layer from Stamen.Toner (http://tile.stamen.com/toner/{z}/{x}/{y}.png).
![image](https://user-images.githubusercontent.com/33963849/66693555-ce3dc800-ecb2-11e9-9084-d391e62d3c8e.png)
On next step I used "Generate XYZ tiles (Directory)" tool with input options
![image](https://user-images.githubusercontent.com/33963849/66693498-08f33080-ecb2-11e9-9427-6fee98700b2e.png)
{ 'DPI' : 96, 'EXTENT' : '1259055.1894920156,8678167.484272065,1058234.4169979505,6221787.4462795425 [EPSG:3857]', 'OUTPUT_DIRECTORY' : 'TEMPORARY_OUTPUT', 'OUTPUT_HTML' : 'TEMPORARY_OUTPUT', 'QUALITY' : 75, 'TILE_FORMAT' : 0, 'TILE_HEIGHT' : 256, 'TILE_WIDTH' : 256, 'TMS_CONVENTION' : False, 'ZOOM_MAX' : 11, 'ZOOM_MIN' : 0 }

**QGIS and OS versions**

QGIS version | 3.8.3-Zanzibar
-- | --
Compiled against Qt | 5.11.2
Compiled against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.0
PostgreSQL Client Version | 10.8
QWT Version | 6.1.3
Compiled against PROJ | 5.2.0
OS Version | Windows 10 Pro 1903 (64-bit)
QGIS code revision | 685d8b1
Running against Qt | 5.11.2
Running against GDAL/OGR | 2.4.1
Running against GEOS | 3.7.2-CAPI-1.11.0 b55d2125
SpatiaLite Version | 4.3.0
QScintilla2 Version | 2.10.8
Running against PROJ | Rel. 5.2.0, September 15th, 2018

__________________________________________________________________
With best regards, IMMSPgisgroup

**Comment by Kazcade** [comment]
So far I have been unable to reproduce the bug - at what zoom level and/or tile number does this become apparent? Tiles look fine for me even at zoom level 11.

**Comment by IMMSPgisgroup** [comment]
Sample tile is 6/39/25.png (zoom 6) but tiles, like this, exists more than one. I think, if in LeafletJS map set in style 
```css
background-color: red 
```
same bugs become more visible.
________________________________________________________________________________________________________
With best regards, IMMSPgisgroup

**Comment by Kazcade** [comment]
Yeah, I'm seeing this as well. Looking at the extracted alpha channels this seems to happen at the right and lower boundaries on some images at zoom levels 6 and at some lower boundaries on zoom level 7.

Examples:

tile 6\39\29 
<img src="https://abload.de/img/296fjav.png" /> 

tile 7\71\57 
<img src="https://abload.de/img/30rhke1.png" />

**Comment by mash-graz** [comment]
this issue could be very likely related to issue #32471 resp. the already suggested fix in PR #32499, because the symptoms look rather similar.

**Comment by gioman** [comment]
@IMMSPgisgroup is this still true? I don't think I'm replicating it, and the tool has a new(?) option (METATILESIZE) that maybe is helping(?).

**Comment by IMMSPgisgroup** [comment]
This was true for QGIS 3.8.3-Zanzibar. In QGIS 3.12 this bug wasn't exist, but I saw something another.

I used tile layer from Stamen.Toner (http://tile.stamen.com/toner/{z}/{x}/{y}.png).

QGIS version: 3.12.0-București
QGIS code revision: cd141490ec
Qt version: 5.11.2
GDAL version: 3.0.4
GEOS version: 3.8.0-CAPI-1.13.1 
PROJ version: Rel. 6.3.1, February 10th, 2020 

{ 'BACKGROUND_COLOR' : QColor(0, 0, 0, 0), 'DPI' : 96, 'EXTENT' : '1259055.1894920156,8678167.484272065,1058234.4169979505,6221787.4462795425', 'METATILESIZE' : 4, 'OUTPUT_DIRECTORY' : 'TEMPORARY_OUTPUT', 'OUTPUT_HTML' : 'TEMPORARY_OUTPUT', 'QUALITY' : 75, 'TILE_FORMAT' : 0, 'TILE_HEIGHT' : 256, 'TILE_WIDTH' : 256, 'TMS_CONVENTION' : False, 'ZOOM_MAX' : 10, 'ZOOM_MIN' : 4 }

Downloaded tiles.
![image27026](https://user-images.githubusercontent.com/33963849/123550708-80fbd580-d777-11eb-89bd-6e4f04576dbf.png)
We see white line on Jordan border.

In original tiles
![image10027](https://user-images.githubusercontent.com/33963849/123550778-d801aa80-d777-11eb-8185-c049cad6fac3.png)

If I change tile 6/38/25 to original tile [http://tile.stamen.com/toner/6/38/25.png](url)
![image27471](https://user-images.githubusercontent.com/33963849/123550959-5b230080-d778-11eb-8c20-541f2ffeebe7.png)
I used default "METATILESIZE" value. 

I haven't experiment with version newer than this (3.12.0-București). 

P.S. What is METATILESIZE mean? I have read about this in QGIS 3.16 documentation, but I don`t understand his description.

**Comment by gioman** [comment]
> In QGIS 3.12 this bug wasn't exist, but I saw something another.

@IMMSPgisgroup please report the new issue in a separate ticket, thanks!

**Comment by gioman** [comment]
@IMMSPgisgroup also you must test on 3.16 or 3.20, as 3.12 is discontinued.
