### ISSUE TITLE
Don't snap to features that are moved

### ISSUE THREAD

**Issue by loctt86** [qgis/QGIS#32237]
**Describe the bug**
After moving a feature TT from position A to new position B, I still snap to feature from position A like gif file attachment. All is ok only I restart project. 
![snap-to-new-pos](https://user-images.githubusercontent.com/56423382/66731430-8ae58400-ee81-11e9-87a9-567ca756a0cf.gif)
**QGIS and OS versions**

QGIS version | 3.8.1-Zanzibar | QGIS code revision | dcd95cc648
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.0 | Running against GEOS | 3.7.2-CAPI-1.11.0 b55d2125
PostgreSQL Client Version | 9.2.4 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Windows 10 (10.0) |   |

**Comment by haubourg** [comment]
Hi, 
do you have triggers on the database side altering the geometry after commit? 
Or someone editing your data in the meantime?

If this is the case, we will offer a solution with https://github.com/qgis/QGIS/pull/30947 in future 3.10
You will need to configure data dependencies in layer properties so that any edit of the layer triggers a snapping cache refresh

**Comment by loctt86** [comment]
Hi haubourg,
This layer is based a shape local file.

**Comment by loctt86** [comment]
Sorry,
It's based a sqlite local file.

**Comment by haubourg** [comment]
Oh, then it's a totally new issue. 
Can you share a project file with data that reproduces this error?

**Comment by loctt86** [comment]
Hi haubourg,
After checking your "someone editing your data in the meantime" recommend again. I found the cause that I have duplicated layer to two layer, then my setting snap is only refer the first layer, while i move the feature on second layer. That's why the nap like gif file attachment. That's so embarrassed!
Thanks for spend your time to reply me!

**Comment by haubourg** [comment]
@loctt86 no worries. Thanks!
