### ISSUE TITLE
When downloading QGIS and starting program I am unable to access any features. I get an error message that readsAuthentication System: DISABLED. Resources authenticating via the system can not be accessed. I am new to this program and not a very technical person. Any help is appreciated as I need this program for a school project

### ISSUE THREAD

**Issue by CChaggy** [qgis/QGIS#32244]
**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by roya0045** [comment]
This is not how you fill an issue, also are you on Mac?

**Comment by CChaggy** [comment]
Hello,

Yes, I am on a MAc. I am not very tech savvy and new to QGIS. I need to create a MAP using this program for school, and spent numerous hours and days trying to get it to work. If you have any insight or assistance, it would be welcomed

**Comment by gioman** [comment]
@CChaggy how did you installed qgis? what macos version to you use? does the error on startup blocks the use of the program?

**Comment by CChaggy** [comment]
HI,
I am on Mac 10.14.6

Yes the error on the start up blocks the use of the program

**Comment by gioman** [comment]
How did you installed QGIS (link to installer you used)?

**Comment by CChaggy** [comment]
This is a screen shot of the error message blocking the use of the application:

**Comment by gioman** [comment]
> This is a screen shot of the error message blocking the use of the application:

no image attached.

**Comment by gioman** [comment]
Closing for lack of feedback. also no issues whatsoever installing QGIS 3.4/3.10 on macOS 10.15.
