### ISSUE TITLE
Not possible to load multiband raster in geopackage

### ISSUE THREAD

**Issue by ghtmtt** [qgis/QGIS#32245]
Don't know if this a provider limit or a QGIS one. Drag&drop a multiband raster (more than 3 bands) within an existing geopackage is not possible: not errors are shown, nothing happens.

Bug or feature request?

**Comment by elpaso** [comment]
See: https://gdal.org/drivers/raster/gpkg.html
RGB and RGBA should be supported. Bytes only.

**Comment by gioman** [comment]
> Drag&drop a multiband raster (more than 3 bands)

@ghtmtt sample data?

**Comment by ghtmtt** [comment]
Cannot load it here (github does not support the file type). Direct link [here](1_CLIP_LC08_L1TP_188032_20140522_20180527_01_T1_sr_bandstack_raster)

**Comment by elpaso** [comment]
@ghtmtt you can just zip it and upload the zip

**Comment by gioman** [comment]
> Direct link [here](1_CLIP_LC08_L1TP_188032_20140522_20180527_01_T1_sr_bandstack_raster)

The link does not point to a dataset nor a page where the dataset is downloadable.

**Comment by ghtmtt** [comment]
done, link updated with a zipped file

**Comment by elpaso** [comment]
@ghtmtt this kind of raster is not supported by GPKG, only RGB and RGBA with Bytes type are supported.
```
Various kind of input datasets can be converted to GeoPackage raster :

    Single band grey level

    Single band with R,G,B or R,G,B,A color table

    Two bands: first band with grey level, second band with alpha channel

    Three bands: Red, Green, Blue

    Four band: Red, Green, Blue, Alpha

GeoPackage rasters only support Byte data type.
```

**Comment by rouault** [comment]
> but a feature request for gdal?

This is more a limitation of the GeoPackage specification itself. One potential workaround on GDAL side would be to split the bands into separate rasters inside the GeoPackage and have GDAL handle this transparently. A bit involved...

**Comment by alexbruy** [comment]
Should we close this?

**Comment by ghtmtt** [comment]
Given that it is a limit of the geopackage itself, then yes. Thanks
