### ISSUE TITLE
Data Source UI - PostgreSQL Spatial Type Drop Down Box has Offset icons on MacOS

### ISSUE THREAD

**Issue by palmerj** [qgis/QGIS#32248]
Checklist before submitting

- [x] Search through existing issue reports and gis.stackexchange.com to check whether the issue already exists
- [x] Test with a [clean new user profile](https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html?highlight=profile#working-with-user-profiles).
- [x] Create a light and self-contained sample dataset and project file which demonstrates the issue

**Describe the bug**
When a table with a geometry column doesn't have defined geometry type you can set the type by selecting the spatial type drop down box from within the row. On MacOS the spatial type drop down box has offset icons. See:

<img width="149" alt="offset_spatial_icons" src="https://user-images.githubusercontent.com/580022/66802867-9ca25680-ef69-11e9-8cb6-fe41e9b32dc4.png">

Seems ok on Ubuntu.

**QGIS and OS versions**

QGIS version | 3.9.0-Master | QGIS code revision | 5f24a0b214
-- | -- | -- | --
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.28.0 | Running against SQLite | 3.28.0
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS 10.15
Active python plugins | QuickWKT; qgisnetworklogger; Mergin; processing; db_manager; MetaSearch

**Comment by nirvn** [comment]
@palmerj , this is a Qt issue (across all platforms) that has been fixed, as of Qt 5.12.5. You'll have to wait for the OS X installer to come bundled with this new Qt version.

**Comment by palmerj** [comment]
Ok thanks. Sorry for the noise

**Comment by roya0045** [comment]
@nirvn Do we know when the new Qt version will be implemented?

**Comment by jaakla** [comment]
Btw for me It was fixed for me with theme change to "default". If OS theme is dark, then it looks just the same as Night Mapping.
