### ISSUE TITLE
Spatial Bookmarks should be Project Specific

### ISSUE THREAD

**Issue by WA-Hui** [qgis/QGIS#32243]
I love Spatial Bookmarks but shouldn't Spatial Bookmarks be Project Specific?

At present they show up in all projects and even appear if there are no open projects

Thanx in anticipation

IH

**Comment by nirvn** [comment]
@WA-Hui , bookmarks can be project-specific already. In upcoming QGIS 3.10, the UI/UX was revamped, and that option is now (hopefully) better exposed.
