### ISSUE TITLE
Cannot restore virtual layer that uses delimited text layer at project load

### ISSUE THREAD

**Issue by SGroe** [qgis/QGIS#32259]
**Describe the bug**

A virtual layer that uses a delimited text layer has a bad source after the project is loaded.

Bad virtual layer source after project load

`?layer=delimitedtext:D%3A%2Fdaten%2Fdigi%2Faccuracy%2Fmatched_trackpoints_773.csv%3Ftype%3Dcsv%26delimiter%3D%3B%26detectTypes%3Dyes%26xField%3Dlon%26yField%3Dlat%26crs%3DEPSG%3A4326%26spatialIndex%3Dno%26subsetIndex%3Dno%26watchFile%3Dno:matched_trackpoints:UTF-8&query=SELECT%20DISTINCT%20t.track_id%0D%0AFROM%20matched_trackpoints%20t&nogeometry`

Correct virtual layer source

`?layer=delimitedtext:file%3A%2F%2F%2FD%3A%2Fdaten%2Fdigibus%2Faccuracy%2Fmatched_trackpoints_773.csv%3Ftype%3Dcsv%26delimiter%3D%3B%26detectTypes%3Dyes%26xField%3Dlon%26yField%3Dlat%26crs%3DEPSG%3A4326%26spatialIndex%3Dno%26subsetIndex%3Dno%26watchFile%3Dno:matched_trackpoints:UTF-8&query=SELECT%20DISTINCT%20t.track_id%0D%0AFROM%20matched_trackpoints%20t&nogeometry`

Difference is following string after 'delimitedtext:'
`file%3A%2F%2F%2F`

**How to Reproduce**

1. Add a delimited text layer to the map
2. Create a virtual layer that uses this delimited text layer
3. Close project
4. Open project
5. Layer is bad

**QGIS and OS versions**

3.8.3 and Win10

**Additional context**

**Comment by sigeal** [comment]
Same problem here.
I noticed the problem occured because "file:///" string at the beginning of the source uri is not saved.

When I had the source using the Import button I get :
`file:///path_to_csv`

When I open the project, the source has become : 
`path_to_csv`

**QGIS and OS versions**
3.10.6 - Windows 10

**Comment by suricactus** [comment]
@sigeal I wish I have found your comment before I lost a few hours looking for this :)
