### ISSUE TITLE
CCON - The coordinate system is not saved

### ISSUE THREAD

**Issue by marekverey** [qgis/QGIS#32253]
Applies to version 3.4.12 - Madeira. Maybe also other versions.
When I define my own coordinate system:
+proj=ccon +lat_1=52 +lon_0=19 +axis=esu +a=6390000 +x_0=330000 +y_0=-350000
test calculates valid coordinate values
For example: 52N , 19E count  330000 , 350000 OK
The same is true for other values.
The same is true for a slightly different definition:
+proj=ccon +lat_1=52 +lon_0=19 +R=6390000 +x_0=330000 +y_0=-350000
+step +proj=axisswap +order=1,-2

Unfortunately, none of these coordinate systems can be saved - write error without comment

**Comment by gioman** [comment]
> write error without comment

here it clearly says "The proj4 definition of '***' is not valid"

**Comment by marekverey** [comment]
OK, but why?
This definition is given on the Proj4 website:
https://proj.org/operations/projections/ccon.html?highlight=ccon
+proj=ccon +lat_1=52 +lon_0=19 +axis=esu +a=6390000 +x_0=330000 +y_0=-350000
And it correctly counts coordinate values in QGIS!

**Comment by roya0045** [comment]
> OK, but why?
> This definition is given on the Proj4 website:
> https://proj.org/operations/projections/ccon.html?highlight=ccon
> +proj=ccon +lat_1=52 +lon_0=19 +axis=esu +a=6390000 +x_0=330000 +y_0=-350000
> And it correctly counts coordinate values in QGIS!

Yes and just above it says "New in Version 5.0.0", you have version 4 in your build.

**Comment by marekverey** [comment]
![image](https://user-images.githubusercontent.com/56582372/66833845-d4ef6800-ef5c-11e9-8a47-8cb1b25b6fb0.png)
I don't think you're right, This is version Proj 5.2
I am sorry in Polish, but you can see the version number :-)

**Comment by marekverey** [comment]
"Works for me on 3.4.0" ....
Of course QGIS 3.4, PROJ 5.2.0   .... as above
ccon is a function for Poland - the ATPOL grid:
from 24E, to 48.7N  and 13.8E to 55N
for example precisely 19E, 52N it is 350000, 330000
![image](https://user-images.githubusercontent.com/56582372/66868895-89f64480-ef9e-11e9-8d2f-3af09bddcdf3.png)

**Comment by marekverey** [comment]
![image](https://user-images.githubusercontent.com/56582372/66869653-1ce3ae80-efa0-11e9-80f6-83f085b9078a.png)

**Comment by roya0045** [comment]
Well the projections are added to your custom list of projections. I'm not sure how you are obtaining your error that you mentioned.

**Comment by marekverey** [comment]
They are just not added!
I just can't save this definition in QGIS 3.4.12 (PROJ 5.2.0). Pressing OK triggers the error message.
