### ISSUE TITLE
Value map: Sort order & CSV import

### ISSUE THREAD

**Issue by saemiw** [qgis/QGIS#32250]
**Keep sort order of original CSV File**
Under "Layer properties" > "Attributes Form" there is the "value map" widget. It is possible to load value-description data from CSV. Currently the original ordering (as it is in the csv) is not kept but changed upon import. Imported data are sorted by value. It would be nice if the original ordering (as it is in the csv) would be kept. The following picture shows the current (not ideal situation):
![grafik](https://user-images.githubusercontent.com/20398621/66811085-c68b5700-ef30-11e9-8699-34579c92bec9.png)

**Comment by DelazJ** [comment]
@saemiw Can you create a new feature request and move the second one there. It's better to have a report/request addressing one issue at a time.

**Comment by DelazJ** [comment]
Btw, Can you provide information on your QGIS version? Your first issue is supposed to be fixed in 3.x according to #23000. So it'd be a bugfix/regression if you are running a 3.x version (what you should be doing in order to report valid issues)

**Comment by saemiw** [comment]
I ise QGIS 3.4.12.

@DelazJ no I think its not the same as https://github.com/qgis/QGIS/issues/23000. This issue solved sorting when you enter the value manually (which is indeed solved). My issue concenrs entry via csv. I would also like to keept the two issues together as I will ask/pay a developer to fix this issue.

**Comment by domhag** [comment]
I just tested the sort order in the value map-widget by import csv-files with QGIS 3.10.4.
The order is not sorted alphabetically any more but in inverse way.

**Comment by m-kuhn** [comment]
@domhag confirmed. I'm working on it.
I also noticed that it skips the first line (probably assuming that it's a header, but that cannot be taken for granted, so I'd rather import it. It's easy to delete it manually from the user interface).
