### ISSUE TITLE
plugin manager python error 

### ISSUE THREAD

**Issue by glw** [qgis/QGIS#32263]
Checklist before submitting

- [X] Search through existing issue reports and gis.stackexchange.com to check whether the issue already exists
- [X] Test with a [clean new user profile](https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html?highlight=profile#working-with-user-profiles).
- [ ] Create a light and self-contained sample dataset and project file which demonstrates the issue

**Describe the bug**
Error when attempting to access plugin manager.

**How to Reproduce**
Plugins > Manage and Install Plugins

**QGIS and OS versions**
QGIS 3.4.12-Madeira
Ubuntu Xenial

**Additional context**
Error Message:

An error occurred during execution of following code:
pyplugin_installer.instance().showPluginManagerWhenReady()

Traceback (most recent call last):
  File "", line 1, in 
  File "/usr/share/qgis/python/pyplugin_installer/installer.py", line 252, in showPluginManagerWhenReady
    self.fetchAvailablePlugins(reloadMode=False)
  File "/usr/share/qgis/python/pyplugin_installer/installer.py", line 120, in fetchAvailablePlugins
    repositories.requestFetching(key)
  File "/usr/share/qgis/python/pyplugin_installer/installer_data.py", line 325, in requestFetching
    self.mRepositories[key]["QRequest"].setAttribute(QNetworkRequest.FollowRedirectsAttribute, True)
AttributeError: type object 'QNetworkRequest' has no attribute 'FollowRedirectsAttribute'

Python version:
3.5.2 (default, Oct  8 2019, 13:06:37) 
[GCC 5.4.0 20160609]

QGIS version:
3.4.12-Madeira 'Madeira', 625767347a

Python path:
['/usr/share/qgis/python', '/home/garret/.local/share/QGIS/QGIS3/profiles/test/python', '/home/garret/.local/share/QGIS/QGIS3/profiles/test/python/plugins', '/usr/share/qgis/python/plugins', '/usr/lib/python35.zip', '/usr/lib/python3.5', '/usr/lib/python3.5/plat-x86_64-linux-gnu', '/usr/lib/python3.5/lib-dynload', '/home/garret/.local/lib/python3.5/site-packages', '/usr/local/lib/python3.5/dist-packages', '/usr/lib/python3/dist-packages', '/home/garret/.local/share/QGIS/QGIS3/profiles/test/python']

**Comment by DelazJ** [comment]
I think this is fixed (https://github.com/qgis/QGIS/pull/32046/) and would be available in next point release

**Comment by glw** [comment]
This is fixed now. Thank you!

QGIS version 3.4.13-Madeira
Compiled against Qt 5.5.1
Running against Qt 5.5.1
Compiled against GDAL/OGR 2.2.2
Running against GDAL/OGR 2.2.2
Compiled against GEOS 3.5.1-CAPI-1.9.1
Running against GEOS 3.7.1-CAPI-1.11.1 27a5e771
PostgreSQL Client Version 9.5.2
SpatiaLite Version 4.3.0a
QWT Version 6.1.2
QScintilla2 Version 2.9.1
PROJ.4 Version 492
