### ISSUE TITLE
GDAL raster calculator fails when using compression

### ISSUE THREAD

**Issue by ernstste** [qgis/QGIS#32266]
QGIS 3.8.3 on Windows 10, GDAL v2.4.1

Using any compression options in the additional creation options leads to a syntax error in the GDAL raster calculator:
`gdal_calc.py: error: no such option: -c`

The problem is in the syntax created by the tool. Instead of --co COMPRESS=..., it will use -co COMPRESS=...

The issue was reproduced running the GDAL command created by the tool in the command line. After changing -co to --co it runs successfully.

I remember being able to change the GDAL/OGR console call (at least on some tools) in prior QGIS versions. This does not seem to be possible anymore.

**Comment by gioman** [comment]
Confirmed.

**Comment by alexbruy** [comment]
I'd say this is a GDAL bug: inconsistent format of the command-line switches. Most of the GDAL tools use `-co` while gdal_calc uses `--co`.

**Comment by ernstste** [comment]
It may be inconsistent syntax in GDAL, but the bug is in QGIS if the GDAL API isn't being used correctly.

**Comment by alexbruy** [comment]
Fixed.

**Comment by ernstste** [comment]
Thanks Alex
