### ISSUE TITLE
[oracle] Wrong extent computation when no estimatemetadata=false

### ISSUE THREAD

**Issue by mhugo** [qgis/QGIS#32261]
The Oracle provider is currently using [sdo_tune.extent_of](https://docs.oracle.com/database/121/SPATL/sdo_tune-extent_of.htm) to estimate the extent of a layer, which could be used as a speedup to sdo_aggr_mbr when an estimate of the extent is ok.

However, this estimate is also used even when estimatemetadata=false. See https://github.com/qgis/QGIS/blob/master/src/providers/oracle/qgsoracleprovider.cpp#L2293
It may result in a "wrong" extent (the result may also depends on the version of Oracle), when the actual extent is requested.

The fix should be easy, but I am a bit scared to touch this behavior, since returning a fast estimate even when it is not asked for may have been turned into a feature with time ...

**Comment by troopa81** [comment]
Fixed in https://github.com/qgis/QGIS/pull/32337 
I choose to not use extent_of when estimatedata is false, seems quite normal to me.
