### ISSUE TITLE
Crash when double clicking on a layer that has been kept on project load with "“keep unvailable layer”

### ISSUE THREAD

**Issue by qptwer** [qgis/QGIS#32273]
## User Feedback

When I double clicked the node which has been kept by badLayerHandler,it crashed.
I opened a project which contains a wmts layer without network, and kept the node by cliked Button “keep unvailable layer”. Then a double clicked the node in the layer tree, it crashed

## Report Details

*Crash ID*: 857665ab692106a077f9ff9b1dc8f980738702ef

*Stack Trace*
<pre>
QtPrivate::QStringList_join :
CPLStringList::empty :
QgsRasterLayer::htmlMetadata :
QgsRasterLayerProperties::sync :
QgsRasterLayerProperties::QgsRasterLayerProperties :
QgisApp::showLayerProperties :
QgisApp::layerTreeViewDoubleClicked :
QMetaObject::activate :
QAbstractItemView::doubleClicked :
QTreeView::mouseDoubleClickEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.8.3-Zanzibar
QGIS code revision: 685d8b15d2
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by gioman** [comment]
I believe that the reported means "layer" instead of "node".

**Comment by elpaso** [comment]
I think this was fixed already.

**Comment by gioman** [comment]
> I think this was fixed already.

Hi @elpaso , so closing this?

**Comment by qptwer** [comment]
I do the same operations on Debug version I compiled , thers's nothing wrong. However, I do the opertions on Release version I compiled and the official Release version "QGis.exe" , it crashed

**Comment by qptwer** [comment]
> I think this was fixed already.

I do the same operations on Debug version I compiled , thers's nothing wrong. However, I do the opertions on Release version I compiled and the official Release version "QGis.exe" , it crashed

**Comment by elpaso** [comment]
Can you share the crashing project? I've just re-tested master and it is not crashing.

**Comment by qptwer** [comment]
> Can you share the crashing project? I've just re-tested master and it is not crashing.

Sorry,I'm afraid not.The wmts server published by ArcGIS only can be accessed by our internal network.The project only contains a wmts server,which was saved when it can be accessed.And crashed by double clicked after opening without network. Thanks for your test and reply, maybe I'll going to find some other ways to solve it~
