### ISSUE TITLE
Rasterize (gdal_rasterize) interface doesn't create a gdal_rasterize instruction in a proper way (cell size trouble)

### ISSUE THREAD

**Issue by gasato** [qgis/QGIS#32279]
**Describe the bug**
QGIS Rasterize (gdal_rasterize) interface doesn't create a gdal_rasterize instruction in a proper way because it doesn't fill the cell size instruction part completely.

This is the error message I have:

GDAL command:
gdal_rasterize -l AreaGeoquimica -burn 0.0 -tr 1000.0 0.0 -te 3002799.9735100204 5332875.350869383 3599119.220332247 5556105.008465713 -ot Float32 -of HDF4 Au.hdf
GDAL command output:
ERROR 1: Wrong value for -tr parameter.

Usage: gdal_rasterize [-b band]* [-i] [-at]

{[-burn value]* | [-a attribute_name] | [-3d]} [-add]

[-l layername]* [-where expression] [-sql select_statement]

[-dialect dialect] [-of format] [-a_srs srs_def] [-to "NAME=VALUE"]*

[-co "NAME=VALUE"]* [-a_nodata value] [-init value]*

[-te xmin ymin xmax ymax] [-tr xres yres] [-tap] [-ts width height]

[-ot {Byte/Int16/UInt16/UInt32/Int32/Float32/Float64/

CInt16/CInt32/CFloat32/CFloat64}] [-optim {[AUTO]/VECTOR/RASTER}] [-q]

**

**How to Reproduce**

Versión de QGIS | 3.8.3-Zanzibar | Revisión del código de QGIS | 685d8b15d2
-- | -- | -- | --
Compilado contra Qt | 5.11.2 | Ejecutándose contra Qt | 5.11.2
Compilado contra GDAL/OGR | 2.4.1 | Ejecutándose contra GDAL/OGR | 2.4.1
Compilado contra GEOS | 3.7.2-CAPI-1.11.0 | Ejecutándose contra GEOS | 3.7.2-CAPI-1.11.0 b55d2125
Versión del cliente PostgreSQL | 10.8 | Versión de SpatiaLite | 4.3.0
Versión de QWT | 6.1.3 | Versión de QScintilla2 | 2.10.8
Compilado contra PROJ | 5.2.0 | Ejecutándose contra PROJ | Rel. 5.2.0, September 15th, 2018
Versión del SO | Windows 10 (10.0) |   |  

**Additional context**
I have also tried to fill the Size parameter by other differents ways like including two separated values like 1000 1000 or 1000/1000 and it doesnt work too. I have remembered in a previous versions of QGIS I only put only one value and gdal_rasterize interface worked.

When I do the same process from the command tool adding the corresponding -tr values gdal_rasterize works well

**Comment by gioman** [comment]
@gasato you have specified only the width of the pixel not the height, so GDAL answer

Wrong value for -tr parameter  because you have

 -tr 1000.0 0.0

and not 

 -tr 1000.0 1000.0

**Comment by gasato** [comment]
Yes, but the interface do not put that parameter on Gdal

**Comment by gasato** [comment]
> 
> 
> @gasato you have specified only the width of the pixel not the height, so GDAL answer
> 
> Wrong value for -tr parameter because you have
> 
> -tr 1000.0 0.0
> 
> and not
> 
> -tr 1000.0 1000.0

Yes, but what I found is the QGIS graphical interface do not put that parameterm correctly on gdal_rasterize.

**Comment by gasato** [comment]
> 
> 
> > Yes, but what I found is the QGIS graphical interface do not put that parameter correctly on gdal_rasterize.
> 
> you have to fill the values for width and height manually. It works, I just tested.

Yes I did, but the question is the QGIS rasterize interface must work well.

**Comment by gioman** [comment]
> but the question is the QGIS rasterize interface must work well.

it does. Can you attach a screencast of how you are using the tool?

**Comment by gasato** [comment]
> 
> 
> > but the question is the QGIS rasterize interface must work well.
> 
> it does. Can you attach a screencast of how you are using the tool?

Sorry @gioman , I have found the error. I will close the issue. Thanks for the help and sorry for the time I have got from you.
