### ISSUE TITLE
SVG fills with clipPath tag are rendered as all-black

### ISSUE THREAD

**Issue by afrigeri** [qgis/QGIS#32270]
**Describe the bug**
When assigning an SVG pattern to a QGIS fill, if the SVG has a ``<clipPath>`` tag, QGIS renders it as all-black.

**How to Reproduce**

Fill __A__ (SVG source is [here](https://raw.githubusercontent.com/afrigeri/geologic-symbols-qgis/master/src/svg/patterns/fgdc/434-DO.svg)) renders correctly in QGIS.

ImageMagick render is this: 
![A](https://user-images.githubusercontent.com/158104/66905476-37e90980-f006-11e9-8f62-5bbb090a866d.png)

fill __B__ (SVG source is [here](https://raw.githubusercontent.com/afrigeri/geologic-symbols-qgis/master/src/svg/patterns/fgdc/434-K.svg)), which uses __clipPath__ and renders as all black in QGIS:

ImageMagick render is this: 
![B](https://user-images.githubusercontent.com/158104/66905475-37507300-f006-11e9-9b39-eec2422ffa32.png).

QGIS renders this as all-black fill: 
![Style Manager](https://user-images.githubusercontent.com/158104/66906498-1c7efe00-f008-11e9-910e-31ccf5eee0e9.png)

This behavior shows up with all the fills with a __clipPath__ svg tag.

Since all the graphics software tested (IM, inkscape, EOG) are rendering the pattern __B__ correctly, maybe there is an issue with rendering this specific fill type within QGIS?  

**QGIS and OS versions**

QGIS version | 3.8.3-Zanzibar | QGIS code revision | 0b21735e28
-- | -- | -- | --
Compiled against Qt | 5.12.2 | Running against Qt | 5.12.2
Compiled against GDAL/OGR | 2.4.0 | Running against GDAL/OGR | 2.4.0
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
PostgreSQL Client Version | 11.5 (Ubuntu 11.5-0ubuntu0.19.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.10.4
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
This copy of QGIS writes debugging output.
OS Version | Ubuntu 19.04 |   |

**Comment by andreasneumann** [comment]
Most likely, this issue is in qt, not in QGIS. qt doesn't support the full SVG standard, just a subset of it, more like the fomer SVG tiny profile.

You need to remove the clip-path from your SVG and use Inkscape or Illustrator to actually do the clip on the geometry rather than just setting a clip-path.

You can't expect that QGIS will fix this. It needs to be fixed in qt upstream.

**Comment by andreasneumann** [comment]
see also https://doc.qt.io/qt-5/svgrendering.html - only the static portion of the SVG Tiny 1.2 profile is supported. This doesn't include clip-path.

**Comment by afrigeri** [comment]
Thanks, @andreasneumann!  That's now clear that it is not a bug but the limit is the Qt-5 support of SVG  to version 1.2 while clippath tag is proper of SVG 2.0.
I've tried to work this out in Inkscape, but there is no easy way of obtaining the same result without the 'clipping' function.   

I did not find any tool/library taking care of saving SVG 2.0 data into SVG 1.2, is there something out I 
 did no find?    That would be a useful option when loading SVG patterns into QGIS.

On the QGIS/symbology side, I would suggest specifying the SVG 1.2 in the documentation/manual and surely we can close this, as does no represent a QGIS bug.

**Comment by gioman** [comment]
> I would suggest specifying the SVG 1.2 in the documentation/manual and surely we can close this issue, as does not represent a QGIS bug.

file a ticket here https://github.com/qgis/QGIS-Documentation/issues ?

**Comment by afrigeri** [comment]
Good idea @gioman see [#4318](https://github.com/qgis/QGIS-Documentation/issues/4318)

**Comment by andreasneumann** [comment]
@afrigeri 

In Inkscape you need to use the "Path" operations, like Intersect:

![image](https://user-images.githubusercontent.com/884476/67202317-a106bd80-f408-11e9-9779-e38d89192208.png)

Unfortunately, this doesn't work with groups, so you'd have to work object by object and clip them, as far as I know.

It would be good, if you could file an enhancement request on qt or Inkscape to improve the situation.
