### ISSUE TITLE
QGIS Browser Layer Property dialog is slow to load for large PostgreSQL layers

### ISSUE THREAD

**Issue by palmerj** [qgis/QGIS#32277]
Checklist before submitting

- [x] Search through existing issue reports and gis.stackexchange.com to check whether the issue already exists
- [x] Test with a [clean new user profile](https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html?highlight=profile#working-with-user-profiles).
- [ ] Create a light and self-contained sample dataset and project file which demonstrates the issue

If the issue concerns a **third party plugin**, then it **cannot** be fixed by the QGIS team. Please raise your issue in the dedicated bug tracker for that specific plugin (as listed in the plugin's description). -->

**Describe the bug**
When right-clicking on very large PostgreSQL tables/layers (e.g millions of rows) in the QGIS browser to show the layer properties dialog, it's very slow to load. It is slow even if the Estimated Metadata connection option is used. This is because queries like the following are run:

```
"SELECT count(*) FROM "foo"."bar"
 WHERE st_srid("the_geom")=4326 AND
 upper(geometrytype("shape")) IN ....

"SELECT st_extent("the_geom") FROM "foo"."bar"
 WHERE st_srid("the_geom")=4326 AND
 upper(geometrytype("shape")) IN ....
```

I think if the Estimated Metadata connection option is used, then the queries should apply the same logic as other estimated metadata queries in the main PG provider. Also, in this case, the count and extent attribute text in the layer properties dialog should state they are estimated. 

**QGIS and OS versions**

QGIS version | 3.9.0-Master | QGIS code revision | 5f24a0b214
-- | -- | -- | --
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.28.0 | Running against SQLite | 3.28.0
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS 10.15
Active python plugins | QuickWKT; qgisnetworklogger; Mergin; processing; db_manager; MetaSearch

**Comment by strk** [comment]
Can you please check if #32292 fixes this case as well ?

**Comment by palmerj** [comment]
It's still slow. Both the count(*) and extents queries are still being run. See comments in https://github.com/qgis/QGIS/issues/32276#issuecomment-544015193

**Comment by strk** [comment]
I've pushed a new commit in #32292 can you please try again ?
