### ISSUE TITLE
Info bubble text no readable under Dark Theme

### ISSUE THREAD

**Issue by Pieha** [qgis/QGIS#32288]
**Bug description**
In Dark Theme QGIS the text of info bubbles is not visible enough.

**How to Reproduce**
1. Enable Dark Theme
2. Set up info bubbles
3. Point a feature on the canvas to display the info bubble text 
4. The text appear in black

**Cange proposed**
Modifiication of info bubble color.

**QGIS and OS versions**

Version of QGIS | 3.4.10-Madeira | Code revision | 3d97aaae88
-- | -- | -- | --
Compilated with Qt | 5.11.2 | Using Qt | 5.11.2
Compilated with GDAL/OGR | 2.4.1 | Used with GDAL/OGR | 2.4.1
Compilated with GEOS | 3.7.2-CAPI-1.11.0 | Used with GEOS | 3.7.2-CAPI-1.11.0 b55d2125
Version for PostgreSQL client | 9.2.4 | SpatiaLite Version | 4.3.0
Version for  QWT | 6.1.3 | Version of QScintilla2 | 2.10.8
Compilated with PROJ | 520 | Work with PROJ | 5.2.0

**Comment by nirvn** [comment]
Confirmed; taking this one.
