### ISSUE TITLE
Interface freezes whenever turning on Log Messages panel on QGIS 3.8 flatpak image

### ISSUE THREAD

**Issue by suricactus** [qgis/QGIS#32286]
**Describe the bug**
The title says it all. Enabling the Log Messages panel completely freezes the UI, nothing inside the window is clickable. However, the menu is still responsive and turning off the panel works fine, the panel disappears. However, the interface remains frozen until restart. It appears that only Log Messages panel cause this. This is what is observed from the command line log:
> Warning: QXcbConnection: XCB error: 8 (BadMatch), sequence: 9238, resource id: 60817545, major code: 42 (SetInputFocus), minor code: 0

**How to Reproduce**
1. Install the flatpak image.
2. Run using `flatpak run org.qgis.qgis`
3. Either right click on the menu section and enable the Log Messages panel, or do it through (Top Menu -> ) Settings -> Panels -> Log Messages

**QGIS and OS versions**
OS -> KDE Neon, but I also experienced it before on other Ubuntu based distros under flatpak
QGIS:
```
QGIS version | 3.8.3-Zanzibar | QGIS code revision | 685d8b15
-- | -- | -- | --
Compiled against Qt | 5.12.4 | Running against Qt | 5.12.5
Compiled against GDAL/OGR | 2.4.2 | Running against GDAL/OGR | 2.4.2
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Linux 5.0.0-31-generic |   |  


```

**Additional context**
Opening/closing the plugins windows works fine. However, closing the About windows is impossible. I didn't manage to select the text either. Turning off all plugins didn't help too.

**Comment by nyalldawson** [comment]
The flatpak install isn't supported here - you need to file this bug against the flatpak package instead.

**Comment by suricactus** [comment]
It's not very fruitful to play the issue ping-pong game. It affects the combination of the product itself (qgis) and the platform (flatpak). I know flatpak is marked experimental, but would be nice to have it fully production ready at some point. For some users it's the only way to install recent or any version of QGIS. I'm not good with cpp, flatpak or qt to be able to solve this issue myself.

**Comment by haubourg** [comment]
> It's not very fruitful to play the issue ping-pong game

Did you create an issue upstream before. It is more likely to be an issue there. If investigations reveal it is QGIS fault, then we'll reopen here. It's probably faster this way. We do the same for osgeo4w or any other packages, don't take it as a closed door :)

**Comment by aleixpol** [comment]
Hi, I'm responsible for the flatpak. I have not much of an idea how this could be the packaging's fault.
I would appreciate it if we could collaborate instead of push people back. :(

**Comment by rduivenvoorde** [comment]
Hi, just testing here, I can not reproduce this.
With me I can just open the panel and it is work fine.
Could it be an KDE / Flatpak issue?

I'm on Debian Testing, Gnome 3.34.1

QGIS version | 3.8.3-Zanzibar | QGIS code revision | 685d8b15
-- | -- | -- | --
Compiled against Qt | 5.12.4 | Running against Qt | 5.12.6
Compiled against GDAL/OGR | 2.4.2 | Running against GDAL/OGR | 2.4.2
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Linux 5.3.0-2-amd64 |   |  



QGIS version | 3.8.3-Zanzibar | QGIS code revision | 685d8b15
-- | -- | -- | --
Compiled against Qt | 5.12.4 | Running against Qt | 5.12.6
Compiled against GDAL/OGR | 2.4.2 | Running against GDAL/OGR | 2.4.2
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Linux 5.3.0-2-amd64 |   |
