### ISSUE TITLE
Bug when converting to Permanent layer after extraction by localisation

### ISSUE THREAD

**Issue by simogeo** [qgis/QGIS#32280]
**Describe the bug**

When performing Extract by localisation from Processings tools THEN converting to permanent layer tin _geopackage_ format   I get an error related to `fid` field .... which already exists !

Here is the error message : 
> Impossible de rendre permanente la couche temporaire.
> Erreur : Erreurs d'écriture d'entité :
> Erreur lors la création de l'entité (Erreur OGR : failed to execute insert : UNIQUE constraint failed: equipements-insee-2018-torcy.fid)
> Erreur lors la création de l'entité (Erreur OGR : failed to execute insert : UNIQUE constraint failed: equipements-insee-2018-torcy.fid)
> Erreur lors la création de l'entité (Erreur OGR : failed to execute insert : UNIQUE constraint failed: equipements-insee-2018-torcy.fid)
> Erreur lors la création de l'entité (Erreur OGR : failed to execute insert : UNIQUE constraint failed: equipements-insee-2018-torcy.fid)
> Erreur lors la création de l'entité (Erreur OGR : failed to execute insert : UNIQUE constraint failed: equipements-insee-2018-torcy.fid)
> ...

**How to Reproduce**

1. Use Extract by localisation from Processings tools 
2. Right click on resulting layer
3. Click 'Convert to permanent layer'
4. It will fail ...

**QGIS and OS versions**

Version de QGIS | 3.8.1-Zanzibar | Révision du code | dcd95cc648
Compilé avec Qt | 5.9.5 | Utilisant Qt | 5.9.5
Compilé avec GDAL/OGR | 2.2.3 | Utilisé avec GDAL/OGR | 2.2.3
Compilé avec GEOS | 3.6.2-CAPI-1.10.2 | Utilisé avec GEOS | 3.6.2-CAPI-1.10.2 4d2925d6
Version du client PostgreSQL | 10.9 (Ubuntu 10.9-0ubuntu0.18.04.1) | Version de SpatiaLite | 4.3.0a
Version de QWT | 6.1.3 | Version de QScintilla2 | 2.10.2
Version de PROJ.4 : | 493
OS Version | Ubuntu 18.04.3 LTS

**Comment by alexbruy** [comment]
Please test with latest master and 3.10. Seems fixed.

**Comment by simogeo** [comment]
Workin with 3.10.1 (ef24c526da). It now works ! Thanks
