### ISSUE TITLE
astyle doesn't format properly C++11 initizalier-list in function calls

### ISSUE THREAD

**Issue by rouault** [qgis/QGIS#32285]
See https://github.com/qgis/QGIS/pull/32262/commits/887a60f615fd5bbf7bbff4aa01acc5e5ea25a109#diff-ce5bd99b9c150c4fe78e6f84b4d914f0R154

```
    mNextUrl = QgsOAPIFJson::findLink( links,
                                       QStringLiteral( "next" ),
    {  QStringLiteral( "application/geo+json" ) } );
```

It looks like it confuses them with new blocks

**Comment by nyalldawson** [comment]
This isn't a qgis issue though - it's an astyle issue 🤔

**Comment by rouault** [comment]
> This isn't a qgis issue though - it's an astyle issue thinking

as astyle code is in QGIS code base, it is sort of of a QGIS issue :-) At least it is affecting our code base. I was going to write "perhaps more recent versions of astyle would fix this" but seems we are using the most recent one from January 2018

**Comment by nyalldawson** [comment]
> as astyle code is in QGIS code base

Do we even still need that? I haven't built with the style flag for 3 or more years. I think we could probably drop it now that it's a direct copy of upstream with no tweaks...

@jef-n?

**Comment by m-kuhn** [comment]
Or switch to clang-format, there is just one nasty difference that [it's not possible to handle class indentation the way we have it now](https://bugs.llvm.org/show_bug.cgi?id=19056).

**Comment by jef-n** [comment]
well, astyle was into our code base to avoid the reformatting by a newer version, that couldn't be configured to match the formatting of the old.  Not sure why it was updated - because that voids the original point of having it in the first place.

**Comment by m-kuhn** [comment]
It was updated because some developers (or was it the ci?) use distros that ship older versions of astyle, anyone with a recent distro doesn't need to build with astyle nowadays.

If everyone is using a distro with a recent astyle version out of the box, there's indeed no reason to keep astyle in the code.

**Comment by Pedro-Murteira** [comment]
@rouault Hello, is this issue still valid on the recent builds?

**Comment by rouault** [comment]
> Hello, is this issue still valid on the recent builds?

yes

**Comment by uclaros** [comment]
This gets fixed with the new clang-format approach, however it is converted to a single line.
Sometimes it really helps in readability to explicitly have parameters in separate lines. Is that an option in clang-format? (ping @3nids)
