### ISSUE TITLE
Integer field when creating field in Graphical Modeler not trimming decimals

### ISSUE THREAD

**Issue by baswein** [qgis/QGIS#32298]
**Field Calculator in Graphic Modeler not respecting integer field type**

When creating a new field in the graphical modeler using the field calculator and setting the field type to integer the resulting field displays as integer but values are kept as float until the layer is saved as a geopackage. This results in errors when running another field calculator directly off of the first when an integer is expected. In the field calculator that is run from the processing toolbox or directly in the attribute table the precision is greyed out and the expected integer results. 
A work around is to add to_int to the field calculator formula.    
**How to Reproduce**

1. Create a model in the graphical modeler that has a vector file with table as an input with a field ("field_A") with the value of 100. 
2. Add a field calculator with "Field_A"/3 and set the type to integer. 
3. The resulting field (Calc_int) will display as 33 but if you create another field that is Float from "Calc_int" you will get 33.33333333.

**QGIS and OS versions**

QGIS version | 3.8.3-Zanzibar | QGIS code revision | 685d8b15d2
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.0 | Running against GEOS | 3.7.2-CAPI-1.11.0 b55d2125
PostgreSQL Client Version | 10.8 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Windows 10 (10.0) |   |  

**Additional context**
See stack exchange question here. https://gis.stackexchange.com/questions/338944/multiple-and-operators-in-case-function-in-qgis-field-calculator-not-returning-r

**Comment by gioman** [comment]
@baswein seems to work fine on the latest master.

**Comment by baswein** [comment]
Just checked it on my end with 3.20 and it does seem fixed. Thanks for following up on this!
