### ISSUE TITLE
Rule based styles limited to 31 rules

### ISSUE THREAD

**Issue by sebzips** [qgis/QGIS#32293]
Hello,
when styling vector features with rule based styles, there seems to be a limitation to 31 rules. When doing a 32th the content is not visible anymore. The (in my case) polygons dissappear. 

This bug seems to be active for 2.18.28 (but not older Versions of 2.8) and > 3.4. 
Qgis 3.2 and 3.3 seem to work normally.

Sebastian

**Comment by sebzips** [comment]
[Exampel.zip](https://github.com/qgis/QGIS/files/3739047/Exampel.zip)

**Comment by haubourg** [comment]
why close? Is it solved somehow?

**Comment by sebzips** [comment]
clicked the wrong button, sorry

**Comment by gioman** [comment]
@sebzips duplicate of https://github.com/qgis/QGIS/issues/31884 ?

**Comment by sebzips** [comment]
Yes it is the same thing. I close this one.
