### ISSUE TITLE
QGIS crashes upon opening Google Satellite URL under XYZ tile or any web based mapping services

### ISSUE THREAD

**Issue by dhanushya-kannan** [qgis/QGIS#32290]
Hi, i've been using Google Satellite imagery in QGIS for a while now, suddenly it started crashing upon opening it. Initially it crashed upon zooming, then right after opening the satellite image view it crashes without any warning. i'm using QGIS 3.4.1, i reinstalled the whole setup as well as tried with new 3.8 version still it crashes. I've tried few solutions provided online still it doesn't work.  Should i look into some system settings or anything within QGIS environment?. Kindly help me out here. Thanks all.

This is the error log i got.

Faulting application name: qgis-ltr-bin-g7.exe, version: 0.0.0.0, time stamp: 0x5d577c2e
Faulting module name: DbgHelp.dll_unloaded, version: 10.0.17763.1, time stamp: 0x05f0e9a4
Exception code: 0xc0000005
Fault offset: 0x0000000000012b81
Faulting process id: 0x3fd8
Faulting application start time: 0x01d584b50c6ec507
Faulting application path: C:\Program Files\QGIS 3.4\bin\qgis-ltr-bin-g7.exe
Faulting module path: DbgHelp.dll
Report Id: a7bdb54e-663c-4061-a03c-f8315162c00e

**Comment by gioman** [comment]
@dhanushya-kannan reinstalling and cleaning the windows registry does not clean/remove QGIS user profiles. 

settings > user profiles > new profile

**Comment by dhanushya-kannan** [comment]
@gioman tried what you said still crashing

**Comment by dhanushya-kannan** [comment]
Thanks guys, had to reset the system because of some issues. QGIS is working fine now after fresh reinstall. But still didn't find what was causing the problem. Will update if something comes up.
