### ISSUE TITLE
GRASS v.voronoi.skeleton is not recognized (patch supplied)

### ISSUE THREAD

**Issue by PedroVenancio** [qgis/QGIS#32296]
v.voronoi.skeleton algorithm in QGIS 3.8 and master is not recognized as an internal or external command, operable program or batch file, because it is calling a v.voronoi.skeleton algorithm that does not exist in GRASS.

```
v.voronoi.skeleton input=vector_5da861993e5712 smoothness=0.25 thin=-1 -s output=output78b49c22a0f64f71a5663422874d9284 --overwrite
'v.voronoi.skeleton' is not recognized as an internal or external command, operable program or batch file.
```

The solution is very simple and I'm uploading a patch for that.

This needs to be applied in master to 3.10 ASAP. 

[v.voronoi.skeleton.txt](https://github.com/qgis/QGIS/files/3739325/v.voronoi.skeleton.txt)

**Comment by gioman** [comment]
Thanks @PedroVenancio I had this already on my list, but I forgot about it.

**Comment by gioman** [comment]
@PedroVenancio PR done https://github.com/qgis/QGIS/pull/32312 not sure how it works now with the backport.
