### ISSUE TITLE
Allow rasterization of specific vector layers on SVG/PDF export

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#32300]
**Feature description.**
It would be great if one could specify specific layers to be rasterized when exporting a PDF or SVG file. The use-case would be highly detailed vector layers that would lead to problems otherwise, e.g. millions of features.

**Additional context**
https://twitter.com/Timmeko/status/1184879513294913537

**Comment by haubourg** [comment]
Hi, It's already possible. In layer option / rendering, you can force a specific layer to be rendered as raster.

**Comment by kannes** [comment]
Oh how did I miss that. Thanks!
