### ISSUE TITLE
Lable position from fields in MapInfo tab files

### ISSUE THREAD

**Issue by chleidersdorff** [qgis/QGIS#32304]
## User Feedback

defining label position based on fields in a MapInfo Tab file causes QGIS to crash

## Report Details

*Crash ID*: 1058694c08e99ff3dcbebd3ffd8204d7fd5048ea

*Stack Trace*
<pre>
geos::noding::snapround::MCIndexSnapRounder::computeVertexSnaps :
geos::noding::snapround::MCIndexSnapRounder::computeVertexSnaps :
GEOSEquals_r :
pal::LabelPosition::intersects labelposition.cpp:206
pal::FeaturePart::createCandidates feature.cpp:1601
extractFeatCallback pal.cpp:151
pal::RTree<QgsLabelPosition * __ptr64,double,2,double,8,4>::Search rtree.hpp:1577
pal::Pal::extract pal.cpp:293
pal::Pal::extractProblem pal.cpp:455
QgsLabelingEngine::run qgslabelingengine.cpp:296
QgsMapRendererJob::drawLabeling qgsmaprenderercustompainterjob.cpp:339
QgsMapRendererParallelJob::renderLabelsStatic qgsmaprendererparalleljob.cpp:311
QtConcurrent::RunFunctionTask<void>::run qtconcurrentrunbase.h:136
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.8.3-Zanzibar
QGIS code revision: 685d8b15d2
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by nirvn** [comment]
@chleidersdorff , can you provide a sample dataset to reproduce the crash?

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
