### ISSUE TITLE
Disable layer option which can also be used on project load

### ISSUE THREAD

**Issue by paulwittle** [qgis/QGIS#32314]
**Feature description.**
It can be annoying that QGIS removes layers when loading a project due to temporary network issues. Examples might include web layers or even local network layers and in such circumstances I would rather the project maintained the reference but simply disabled the layer. 

I'm assuming you could then right click the layer and hit 'Enable Layer' and it would recheck if the layer is valid and load it if it is. 

I think this functionality might have general use anyway as in my experience there can be benefit in being able to temporarily disable a layer in a project. This might be due to planned maintenance of the dataset for example.

To summarise the proposal:
 - Allow layers to be Enabled/Disabled^
 - Switch from removing bad layers at load to disabling 

^ Disabled layers would be maintained in the project file and shown greyed out in the layers panel but they would not be validated in the project load or seen as available anywhere but the layers panel. It would also not be possible to click the tick until the layer is enabled. Enabling the layer would be similar in effect to loading the layer again; in reality the disabled layer would sort of be a saved set of instructions on how to reload the layer again with all the previous settings. 

Sorry I've added so many requests; I thought I'd share my ideas as hopefully I might be able to implement them myself if I get going with development. This one might be a bit more radical though in terms of the way QGIS handles layers.

**Comment by nyalldawson** [comment]
This is already available in qgis 3.6+

**Comment by andreasneumann** [comment]
@paulwittle - what version of QGIS are you using?

Because what you describe should already be possible (I don't remember since which version). ON the loading of QGIS you get a list of broken layers which allows you to either correct the data source, or keep them anyway. QGIS allows to keep such layers in the project. Not sure about the enabling part though. That probably still requires a reload of the project. But at least you don't loose layers that temporarily can't be accessed.

**Comment by paulwittle** [comment]
Ah, that's great! Sorry, we are using the LTR so we are on 3.4.7 and that's why I hadn't noticed. I'll close the ticket...good resolution :-)
