### ISSUE TITLE
qgis crashes after panning the map canvas

### ISSUE THREAD

**Issue by angelablancovogt79** [qgis/QGIS#32313]
Working with ALKIS-Data and trying to georeference an images, qgis 3.6 and qgis 2.8 crash and unexpected close.

**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by gioman** [comment]
@angelablancovogt79 please share a project with data or described the detailed steps to replicate. Is also always worth test with a new QGIS profile, and no 3rd party plugins installed.

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
