### ISSUE TITLE
Join attributes by nearest ignoring "Maximum Nearest Neighbors" setting (Multilinestring)

### ISSUE THREAD

**Issue by lbell** [qgis/QGIS#32317]
**Bug description.**
Using the "Join Attributes by Nearest" feature with two multiline string layers, even when I select "1" for "Maximum nearest neighbors" I get a table output with several repeated rows of the original feature from the input layer joined with different features from input layer 2.

**Additional info**
Two things of note:

1) Both are multilinestring layers
2) One feature in original input layer may overlap multiple features in input layer 2 (ie, distance 0)

I'm guessing it's happening because every intersecting line has a 0 distance score... so which is closest? Looks related to possible bug: https://github.com/qgis/QGIS/issues/32318 which favors intersecting lines as more "nearest" than parallel lines.

**Comment by nyalldawson** [comment]
I don't think this is a bug. If there multiple matching features with identical distances, then only returning one is giving misleading results.

**Comment by lbell** [comment]
I'm coming from it in terms of, say, a SQL query: `SELECT * FROM a LIMIT 1` returns one result only, regardless of number of matching records. Perhaps something in the docs / mouseover to the effect of: "If multiple nearest neighbors of identical distance are found, all will be returned."

Might also be useful to have a "Limit" setting, but maybe mine is an edge case.
