### ISSUE TITLE
Join attributes by nearest gives unexpected results with line features

### ISSUE THREAD

**Issue by lbell** [qgis/QGIS#32318]
**Describe the bug**
When using "join attribute by nearest" feature on two multiline layers, a line that intersects will be selected over a line that runs parallel (but does not intersect). While technically, the intersecting line is "closer" at the intersecting point, it seems to miss the "spirit" of which two lines are nearest... 

**How to Reproduce**

![image](https://user-images.githubusercontent.com/1029014/67096774-1018b380-f176-11e9-8e1e-9dba1d14acc1.png)

**QGIS and OS versions**

QGIS version | 3.8.3-Zanzibar | QGIS code revision | 685d8b15d2
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.4.2 | Running against GDAL/OGR | 2.4.2
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
PostgreSQL Client Version | 10.10 (Ubuntu 10.10-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Ubuntu 18.04.3 LTS |   |  

I realize this may not be a "bug" and I'd be happy if someone could point me to how to achieve the desired results... I don't see a "Join attribute by most similar" tool.

**Comment by haubourg** [comment]
This is the behavior of GEOS algorithm if I don't mistake. Matching Lines is not an easy task and is not a simple intersection. In postGIS I use to project one line to the other using linear referencing tools, and then I compute the shared segment proportion to keep or discard my relating candidates

**Comment by nyalldawson** [comment]
Not an issue - it's working as intended. If anything, this is a feature request for a new "match lines by similarity" algorithm.
