### ISSUE TITLE
Temporary raster isn't calculated in Raster calculator

### ISSUE THREAD

**Issue by nicco17** [qgis/QGIS#32310]
Procedure:
     -  use of the model graphic builder
     -  use rasterize  algoritm to rasterize a vector line (it's work well)
     -  gdal raster calculator use the rasterize vector how calculation element, but the result is a NODATA output (it'nt work)
     - if use a save rasterize vector line ingdal raster calculator it's work well!

WELL the issue, for me, is that gdal raster calculator doesn't recognized the temporary raster because have a too long filename  in temp folder. I GIVE THIS IDEA

I need to use the model graphic builder in may raster model work

I'm sorry if  i mistake where post the issue

[prova.txt](https://github.com/qgis/QGIS/files/3743415/prova.txt)

**Comment by gioman** [comment]
@nicco17 works fine on the latest master.

**Comment by nicco17** [comment]
please close the problem. I believe it involves a piece of third party
software that I am unable to find and replicate. anyway thanks for this
fundamental and very important qgis project
-----‐----------‐------------------------------

Il Mer 14 Lug 2021, 16:38 github-actions[bot] ***@***.***> ha
scritto:
