### ISSUE TITLE
Postgresql unstoppable style_list

### ISSUE THREAD

**Issue by DocOC86** [qgis/QGIS#32320]
**Describe the bug**
If i load a layer out of a postgresql database via python, it get automatically the style of the layer_style table. If I want to change the style immediatly after loading it into the legend via "loadNamedStyle(qml_path)" it stays on the old style of the layer_style table. If i change the style in the qgis menu it is changing the style with no problems. 

**How to Reproduce**
#load layer out of postgresql database
layer_mark = QgsVectorLayer(uri.uri, "tree_mark", "postgres")
#add layer to legend
QgsProject.instance().addMapLayer(layer_mark, True)
#change style with qml
layer_mark.loadNamedStyle(qml_path)

**QGIS and OS versions**

OS-Version: Windows 7 Professional

QGIS-Version
3.4.11-Madeira
QGIS-Codeversion
9a8a6d4687
Kompiliert gegen Qt
5.11.2
Laufendes Qt
5.11.2
Kompiliert mit GDAL/OGR
2.4.1
Läuft mit GDAL/OGR
2.4.1
Kompiliert mit GEOS
3.7.2-CAPI-1.11.0
Läuft mit GEOS
3.7.2-CAPI-1.11.0 b55d2125
PostgreSQL-Client-Version
10.8
SpatiaLite-Version
4.3.0
QWT-Version
6.1.3
QScintilla2-Version
2.10.8
Kompiliert mit PROJ
520
Läuft mit PROJ
5.2.0

**Additional context**

**Comment by Gustry** [comment]
You might need to call a layer refresh from python on your layer.

**Comment by DocOC86** [comment]
I have done the refresh but with the same result as before. All Layerstyles are from postgresql database and not from my qml. For avoid the problem, i have add a new style.

```
style_memory = QgsMapLayerStyle()
style_memory.readFromLayer(layer_mark)
layer.styleManager().addStyle("new_style", style_memory)
layer.styleManager().setCurrentStyle("new_style")
```

**Comment by Gustry** [comment]
@DocOC86 `loadNamedStyle` is returning a string with status message. https://qgis.org/api/classQgsMapLayer.html#a8b271b8bf3074e84808cff26f722b26f
You could check it.

Just for curiosity, did you install the plugin "DB Style manager"? If yes, disable it.

**Comment by DocOC86** [comment]
I had disabled the db style manager and get a True out of loadNamedStyle but the style is the same as before.

**Comment by gioman** [comment]
@DocOC86 is this still valid?
