### ISSUE TITLE
`Clip raster by extension` batch mode: no path for output choosable 

### ISSUE THREAD

**Issue by ghtmtt** [qgis/QGIS#32328]
In the ``Clip raster by extent`` of gdal, in the **batch mode** it is not possible to choose an output for the raster files (and having the nice *Fill automatically with... (parameter, numbers..)* options. It seems to be just an empty string. With the ``Clip raster by mask`` always gdal, all seems working fine:
1. Clip raster by extent (not working)

![immagine](https://user-images.githubusercontent.com/2884884/67203763-40797f80-f40c-11e9-9dad-ce6cca1d8b62.png)

2. Clip raster by mask (working)

![immagine](https://user-images.githubusercontent.com/2884884/67203818-57b86d00-f40c-11e9-8698-54a9863b2641.png)

QGIS 3.9 on Linux Debian Sid

**Comment by gioman** [comment]
@ghtmtt QGIS version? OS?

**Comment by ghtmtt** [comment]
> @ghtmtt QGIS version? OS?

was too fast to add the ticket, Issue edited

**Comment by gioman** [comment]
@ghtmtt works on 3.14.12 on Ubuntu, could be a regression on master, kindly try also on 3.4.12 to confirm.

**Comment by ghtmtt** [comment]
Yep and regression is. 3.14.12 (from package) is working nice (I see the output of raster as a path and not as a string)

**Comment by alexbruy** [comment]
Can not reproduce with master and 3.10.

**Comment by ghtmtt** [comment]
Tried with master and this problem is solved. But another problem is here. Even if there are rasters loaded in the legend (temporary and existing) the loading dialog of the batch interface is empty:

![immagine](https://user-images.githubusercontent.com/2884884/71716300-87c0bb00-2e14-11ea-8552-d665be713aa6.png)

should I close this and open another issue?

**Comment by gioman** [comment]
> should I close this and open another issue?

@ghtmtt yes please, and also please check if a regression. Thanks.
