### ISSUE TITLE
QGIS crashes with almost everything

### ISSUE THREAD

**Issue by ShahlaYadollahi** [qgis/QGIS#32327]
## User Feedback

I just loaded a basin shapefile and as I tried to identify one part, it crashed with this ID. It also can't find some plugins (like qswat).  This is as far as I can go with it. It just doesn't work.

## Report Details

*Crash ID*: a1d45e46e8d1c06d923e1f837d5d9bf7bc9dd1b5

*Stack Trace*
<pre>
QgsField::QgsField qgsfield.cpp:55
QgsFields::at qgsfields.cpp:186
QgsFieldFormatter::representValue qgsfieldformatter.cpp:35
QgsIdentifyResultsDialog::representValue qgsidentifyresultsdialog.cpp:769
QgsIdentifyResultsDialog::addFeature qgsidentifyresultsdialog.cpp:597
QgsMapToolIdentifyAction::identifyFromGeometry qgsmaptoolidentifyaction.cpp:148
QMetaObject::activate :
QgsMapToolSelectionHandler::geometryChanged moc_qgsmaptoolselectionhandler.cpp:314
QgsMapToolSelectionHandler::selectFeaturesReleaseEvent qgsmaptoolselectionhandler.cpp:219
QgsMapToolIdentifyAction::canvasReleaseEvent qgsmaptoolidentifyaction.cpp:175
QgsMapCanvas::mouseReleaseEvent qgsmapcanvas.cpp:1528
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:368
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:368
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1542
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.4.12-Madeira
QGIS code revision: 625767347a
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment]
> It just doesn't work.

likely you have local issues.
As a start try a new QGIS profile and do not install any 3rd party plugins.

**Comment by ntgis** [comment]
That's not a fix! Part of the enjoyment of QGIS is 3rd party plugins!

**Comment by gioman** [comment]
>  Part of the enjoyment of QGIS is 3rd party plugins!

it is indeed, but we have no control on the 3rd party plugins code. You must complaint with the plugins authors.

**Comment by kannes** [comment]
@ShahlaYadollahi does it crash if you disable all plugins temporarily?

**Comment by gioman** [comment]
Closing for lack of feedback.
