### ISSUE TITLE
qgis.exe can't start and crashed!

### ISSUE THREAD

**Issue by xairwolfcn** [qgis/QGIS#32335]
**Describe the bug**

compile the QGIS library with:
-VS2017 
-osgeo4w-setup-x86_64 for 3rdparty
-QT5.13.0x64 for vs2017
-X64
cmake with basic option，：gui core desktop..
**### qgis.exe crash ：**
Application path not initialized
Debug Assertion Failed!

Program: ...ryCompile\QGIS\QGIS-final-3_4_12B\output\bin\Release\qgis.exe
File: minkernel\crts\ucrt\src\appcrt\heap\debug_heap.cpp
Line: 908

Expression: is_block_type_valid(header->_block_use)

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts.

(Press Retry to debug the application)
Crash ID: 599bbf09eb9a825c352c2af1a3661d868930890a

Stack Trace

strnicoll_l :
strnicoll_l :
strnicoll_l :
strnlen :
_p__commode :
_p__commode :
_p__commode :
_p__commode :
_p__commode :
_p__commode :
_stdio_common_vsnprintf_s :
VCrtDbgReportW :
VCrtDbgReportW :
VCrtDbgReportA :
CrtDbgReport :
calloc_base :
free_dbg :
free :
QLockFile::error :
QLockFile::error :
QLockFile::error :
main :
BaseThreadInitThunk :
RtlUserThreadStart 

QGIS Info
QGIS Version: 3.4.12-Madeira
QGIS code branch: Release 3.4
Compiled against Qt: 5.13.0
Running against Qt: 5.13.0
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**How to Reproduce**

**QGIS and OS versions**

I try QGIS3_4_0 QGIS3_4_12 QGIS3_8_2 QGIS ltr-3_4 ,the same error!
Win10 X64

**Comment by jef-n** [comment]
Did you roll you own Qt?  Qt in OSGeo4W is for VS2015 and won't work with VS2017.

**Comment by xairwolfcn** [comment]
yes，I install myself with qt5.13.0!

**Comment by gioman** [comment]
@xairwolfcn is this still relevant?
