### ISSUE TITLE
batch mode: cannot autofill "column" if is a raster input

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#32332]
QGIS 3.4.12 on Ubuntu:

Open a Processing tool (native or else) that uses an input raster layer.

Fill the first input with a raster taken from the project or file system

Add new lines to the batch mode.

Try to fill the new lines by double clicking the input parameter name/column > do not work. 

Does not happen with vector inputs.

**Comment by alexbruy** [comment]
This was changed to use "Autofill" button. Works fine on master and 3.10.

**Comment by gioman** [comment]
> This was changed to use "Autofill" button. Works fine on master and 3.10.

is there such button on 3.4?

**Comment by alexbruy** [comment]
Not sure, probably no. But 3.4 is EOL isn't it?

**Comment by gioman** [comment]
> But 3.4 is EOL isn't it?

is it? I'm confused, it was then decided that there are no longer bug fixes in 3.4?

**Comment by alexbruy** [comment]
Maybe I'm wrong. I was sure that after 3.10.1 new LTR is 3.10 and 3.4 is EOL'ed.

Also there were a discussion in the developers ML about backporting only critical bugfixes (like fixes for crashes) at the end on the LTR cycle and don't backport other fixes to avoid breaks in the end of cycle.

**Comment by gioman** [comment]
ok thanks for clarifying!
