### ISSUE TITLE
Can not use grass on 3.8.3-Zanzibar

### ISSUE THREAD

**Issue by sandrolemosmachado** [qgis/QGIS#32341]
**Describe the bug**
<I can not use any grass tool. It seems system variable is not set correctly-->

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by gioman** [comment]
@sandrolemosmachado this is missing *all* the necessary information.

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
