### ISSUE TITLE
Crashes on exit

### ISSUE THREAD

**Issue by geomdev** [qgis/QGIS#32349]
QGIS crashes on exit consistently. Doesn’t matter what I load (orthos, shp file, etc), it crashes. No data loss though. I will re-install and try again in case it is plugin related, then report again if I get the same behaviour.

***Crash report below.***

## User Feedback

I only had large orhtos loaded, but even when I just load small shapefiles, QGIS crashes on exit. I don't lose any data, it just crashes when I try to close the program. I will re-install and try again then report again if I get the same behaviour.

## Report Details

*Crash ID*: 62f1fcd2045780cb9f127836e6b579b8665f3e63

*Stack Trace*
<pre>
proj_lpz_dist :
proj_lpz_dist :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::QgsCoordinateTransform :
QHashData::free_helper :
QgsCoordinateTransform::addToCache :
QgsCoordinateTransform::invalidateCache :
QgsApplication::exitQgis :
QgisApp::~QgisApp :
CPLStringList::operator[] :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.8.0-Zanzibar
QGIS code revision: 11aff65f10
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by nirvn** [comment]
@geomdev , good news, this specific crash has been addressed, and will be available in QGIS' next release before the end of this month.

**Comment by geomdev** [comment]
Very good to hear. Thank you.
