### ISSUE TITLE
QGIS 3D advanced: Linking 2D and 3D map view

### ISSUE THREAD

**Issue by GokulGeo** [qgis/QGIS#32356]
QGIS advanced 3D

Qgis 3D will be more useful if there is a link view button between 3d and 3d option. I would like to work on a synced view so that I wouldn't get lost the region I am working on.

**Comment by Saijin-Naib** [comment]
I too would love to see this optional facility. I think this could go a long way towards making the navigation of the 2D/3D Maps a bit more intuitive, and would allow for a direct comparison of the same scene between the two views.

**Comment by GokulGeo** [comment]
Also if possible adding capability for editing shapefile in 3d view itself

**Comment by TANK2003** [comment]
Hello, any update of this ?
