### ISSUE TITLE
QGIS 3D advanced feature request

### ISSUE THREAD

**Issue by GokulGeo** [qgis/QGIS#32355]
**QGIS advanced 3D.**
Qgis 3d is good to use but if it is built with some more additional features it would be useful for GIS work.

Such as,
1. Linking 2D and 3D map view while paning
2. Editor option in 3D for vector formats
3. Visible timescale with keyframes in qgis 3D animation

**Comment by saberraz** [comment]
Could you open new feature request for each of those. Also, I think there are tickets for 1 and 2.

**Comment by GokulGeo** [comment]
Could you tell me why it is required? I am new to this forum.

**Comment by saberraz** [comment]
Hi @GokulGeo and welcome. Thanks for your contribution so far.

Because, no one will probably is going to solve all the these feature requests in one go. Also, it is easier to discuss each feature in its own thread, future PR to reference the relevant ticket......etc.

**Comment by GokulGeo** [comment]
ok..! got it now. I will put those individually.

**Comment by saberraz** [comment]
Thanks!
