### ISSUE TITLE
QGIS Server understands only UpperCamelCase for URL parameters

### ISSUE THREAD

**Issue by Gustry** [qgis/QGIS#32354]
**Describe the bug**

QGIS Server understands only UpperCamelCase for parameters.

`http://qgis.server/ltr?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities` is working.

`http://qgis.server/ltr?SERVICE=WMS&VERSION=1.3.0&REQUEST=GETCAPABILITIES` is not working.

```
<ServiceExceptionReport version="1.3.0"><ServiceException code="OperationNotSupported">Request GETCAPABILITIES is not supported</ServiceException></ServiceExceptionReport>
```

**QGIS and OS versions**

It's compiled version of 3.4.12 that I'm using, this is the version from the Desktop app

Version de QGIS | 3.4.12-Madeira | Révision du code | Révision du code
-- | -- | -- | --
Compilé avec Qt | 5.12.2 | Utilisant Qt | 5.12.2
Compilé avec GDAL/OGR | 2.4.0 | Utilisé avec GDAL/OGR | 2.4.0
Compilé avec GEOS | 3.7.1-CAPI-1.11.1 | Utilisé avec GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Version du client PostgreSQL | 12.0 (Ubuntu 12.0-1.pgdg19.04+1) | SpatiaLite Version | 4.3.0a
Version de QWT | 6.1.4 | Version de QScintilla2 | 2.10.4
Compilé avec PROJ | 5.2.0 | Fonctionne avec PROJ | Rel. 5.2.0, September 15th, 2018
Active python plugins | qgis-analyse-itv-rerau-plugin; raepa; go2mapillary; plugin_reloader; french_locator_filter; firstaid; Qgis-Plugin-Builder; lizmap; QgisLayerBoardPlugin; qgis_drain_sewer_visual_inspection; QuickOSM; processing; db_manager

**Comment by rldhont** [comment]
@elpaso @sbrunner @dmarteau some knowledge about this issue ?

**Comment by elpaso** [comment]
mmm no, I'm surprised.

**Comment by sbrunner** [comment]
Me neither, for me the case is important...
