### ISSUE TITLE
Importing using D&D in QGIS browser does not work anymore if input is multipart

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#32362]
On master

Try to D&D a MULTI layer from GPKG/PostGIS to GPKG/PostGIS, it will fail with an error like
`
Failed to import some vector layers!Feature write errors:Failed to transform a feature with ID '1' to single part. Writing stopped.`

Does not happen on 3.4

related to https://github.com/qgis/QGIS/pull/32108 ?

**Comment by elpaso** [comment]
maybe related, I'll check

**Comment by gioman** [comment]
> maybe related, I'll check

Thanks Ale.

**Comment by elpaso** [comment]
@gioman it's related but apparently the root cause is upstream:
```
62d615c2cd1 (Peter Petrik       2019-06-04 15:52:50 +0200)             options.insert( QStringLiteral( "forceSinglePartGeometryType" ), true );
```
@PeterPetrik  do you remeber why you added that option? It does not look required to me.

**Comment by elpaso** [comment]
the one for PG is mine though: 
```772adec552a (Alessandro Pasotti 2018-02-25 16:22:16 +0000)       options.insert( QStringLiteral( "forceSinglePartGeometryType" ), true );
```

**Comment by elpaso** [comment]
Ok, I know what happened, when I fixed https://issues.qgis.org/issues/15875 the behavior of the exporter was different and the forceSinglePartGeometryType did not fail when it could not transform the geometry to single part: it was just passing the geometry unchanged, since #32108  it fails.
