### ISSUE TITLE
Crashing on Load of Census new Construction program saved file

### ISSUE THREAD

**Issue by rleibowitz** [qgis/QGIS#32365]
Here's what I get in the crash report 
----------------------------------------------

Crash ID: 7b6beaea49dc0c87b90ff67d1b523d32120b698c

Stack Trace

QgsArrowSymbolLayer::usedAttributes :
QgsRasterDataProvider::copyBaseSettings :
QgsRasterPipe::QgsRasterPipe :
QgsRasterLayerRenderer::QgsRasterLayerRenderer :
QgsRasterLayer::createMapRenderer :
QgsMapRendererJob::prepareJobs :
QgsMapRendererParallelJob::start :
QgsMapCanvas::refreshMap :
QMetaObject::activate :
QTimer::timerEvent :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32Private::sendTimerEvent :
QEventDispatcherWin32::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
TranslateMessageEx :
TranslateMessage :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QCoreApplication::processEvents :
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_sip :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::close_helper :
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QMetaObject::activate :
QActionGroup::~QActionGroup :
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
TranslateMessageEx :
TranslateMessage :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QMenu::exec :
QDialogPrivate::operator= :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::mousePressEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
TranslateMessageEx :
TranslateMessage :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QMetaObject::activate :
QMetaObject::activate :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.4.4-Madeira
QGIS code revision: 73c31df831
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.0
Running against GDAL: 2.4.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by gioman** [comment]
@rleibowitz try with a new QGIS profile and no 3rd party plugins installed.

**Comment by rleibowitz** [comment]
How do I do that?

**Comment by gioman** [comment]
settings > user profiles > new profile

**Comment by Gustry** [comment]
@gioman I think the message in the crash dialog should be improved with these steps and asking for a new QGIS profile before submitting the crash report, what do you think?

**Comment by gioman** [comment]
> @gioman I think the message in the crash dialog should be improved with these steps and asking for a new QGIS profile before submitting the crash report, what do you think?

@Gustry it would be indeed be a lot better for the users and also for who do bug triage.

**Comment by gioman** [comment]
> Well the program loads, but then not sure what I do from here to get the plugin operating again in conjunction with the project.

well, if it loads it means that the crash was likely caused by a bad 3rd party plugin, and we cannot do anything about it. I would suggest to start installing your usual 3rd party plugins under the new profile, and see what is the one that is causing you issues. After that report the problem to the plugin authors.

**Comment by rleibowitz** [comment]
FWIW - talked to Census Bureau regarding GUPS 3rd party install. The issue relates to their digital imagery. If you save the project with the imagery still on it will corrupt the file. So be sure to turn it off prior to saving or closing QGIS if you are using GUPS.

If you go through what I just had to go through - you'll need to find your dbf file and save it as a CSV. (c:\Users\username\GUPSGIS\gupsdata\NC20\shape\useaddr.dbf. (open it in excel and save as csv).

Then open QGIS without opening a project, go to the GUPS menu--->GUPS DAta Settings and then select --->Clean by project.  (select that and then hit "ok". 

You'll have to start by scratch and redownload the data, but you'll immediately be able to import your CSV right in and match the fields and you'll be right back where you were as if nothing happened.
