### ISSUE TITLE
Report : Predefined scale (best fit) doesnt' work

### ISSUE THREAD

**Issue by REIMSMetropole** [qgis/QGIS#32366]
Aloha,

**Describe the bug**
In a report, if you set the Controlled by atlas property to Predefined scale (best fit), the map item will be transformed (in my case, its height and length were augmented and the map weren't contained anymore in the layout). 
The property works properly in a simple atlas made with composer.

**How to Reproduce**
Create a report,
add a group attribute section
create a map
set the Controlled by atlas property to Predefined scale (best fit)
![image](https://user-images.githubusercontent.com/5716587/67407244-84f54e80-f5b7-11e9-8704-1898d2b4a82e.png)
![image](https://user-images.githubusercontent.com/5716587/67407322-9b9ba580-f5b7-11e9-8e27-9f56833d006d.png)
![image](https://user-images.githubusercontent.com/5716587/67407367-ac4c1b80-f5b7-11e9-9124-b45180499b77.png)

**Comment by roya0045** [comment]
What version of QGIs are you using ?

**Comment by nyalldawson** [comment]
This is fixed in 3.10

**Comment by REIMSMetropole** [comment]
> 
> 
> This is fixed in 3.10

Thanks. We're actually in 3.4.7.
