### ISSUE TITLE
Change location of temporary executables for geoprocessing tools

### ISSUE THREAD

**Issue by stragu** [qgis/QGIS#32375]
**Feature description.**

I am not sure if I missed something somewhere, but it would be amazing to add the option to decide where the intermediate geoprocessing executables are stored and executed.

We would like to use QGIS (with SAGA + GRASS + GDAL) at a university, and the fact that some intermediate executables are created inside the user's temporary folder means that we can't whitelist them.

We end up having this type of error message:

> "This program is blocked by group policy. For more information, contact your system administrator."

In a GRASS example, the offending executable would be:

> C:\Users\<username>\AppData\Local\Temp\processing_670dd4b4fc494c41a3761314d2eb317a\grassdata\grass_batch_job.cmd

In the case of SAGA, it seems it tries to run a .bat file.

We can't whitelist every user's entire `AppData\Local\Temp` folder, and the unpredictable naming of the folders does not allow to whitelist a more precise path.

Could there be an option to define where all those intermediate executables will be going and executed from? For example, an extra option in Options > Processing > General

**Additional context**

Tested with QGIS 3.6.3 and 3.8.3 on Windows 10.

**Comment by roya0045** [comment]
I would assume that this is simply the matter of adding a variable in the settings, UI for the settings and [referencing it here](https://github.com/qgis/QGIS/blob/dadb90312f0f3b71ef55ae2056d522f0ad703787/src/core/processing/qgsprocessingutils.cpp#L686). The default var would be the one in the function.

**Comment by NathanW2** [comment]
I caught up with @stragu at Linux Conf Au today (2020) and will look at pointing him in the right direction to fix this.  He is quite keen to spend some time on doing this fix him self.    @stragu  I will get in touch and give you a hand.

**Comment by stragu** [comment]
Hi @NathanW2 ! Lovely meeting you and learning more about the history and nitty gritty of QGIS!
Yes please, pointers would be very appreciated :)

**Comment by nyalldawson** [comment]
This is fixed in recent releases

**Comment by stragu** [comment]
Hi @nyalldawson ! Could you please point me to the right commit / feature description / bug report that describes the fix? Much appreciated :)

**Comment by nyalldawson** [comment]
https://github.com/qgis/QGIS/pull/33086
