### ISSUE TITLE
Scale bar size is not saved properly in print composition

### ISSUE THREAD

**Issue by miron-t** [qgis/QGIS#32379]
When a scale bar is added to a print composition and the size of the scale bat is changed, for example the height, after reopening the composition, the scalebar height is back to a default value or something.

**Comment by gioman** [comment]
@miron-t duplicate of https://github.com/qgis/QGIS/issues/26931 ?

**Comment by HaVRane** [comment]
Still a bug in 3.10.1

**Comment by ekauq** [comment]
Still in 3.12.1

**Comment by HaVRane** [comment]
Thanks, nyalldawson! Looking forward to next release!

**Comment by fiddlersfan** [comment]
Unfortunately still available in version 3.10.12 LTR. Its possible to push this in the LTR branch?
