### ISSUE TITLE
estimatedmetadata parameter not set for layer when using browser

### ISSUE THREAD

**Issue by nboisteault** [qgis/QGIS#32378]
**Describe the bug**
When using browser to add a PostGIS layer, the "estimatedmetadata" parameter is not set for the layer while the connection has it set.

**How to Reproduce**

1. Create a PostGIS connection checking "Use estimated table metadata"
2. Add a layer from this connection using the browser
3. Go to Properties -> Information for the layer
4. Watch "estimatedmetadata" parameter is not set

**QGIS and OS versions**

QGIS version | 3.4.12-Madeira | QGIS code revision | 625767347a
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
PostgreSQL Client Version | 10.10 (Ubuntu 10.10-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493

**Issue saw in Windows 10 too.**

**Comment by strk** [comment]
@nboisteault this should be fixed by #32292 -- can you check that please ?

**Comment by strk** [comment]
Why can't you compile QGIS ? All tools to do so are free to download :)

**Comment by strk** [comment]
Fixed via #32292
