### ISSUE TITLE
labels "formatted numbers" option does not work anymore on QGIS master

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#32393]
Trying to reduce the numbers of decimals of a label (of a decimal field of a postgis layer as also of a gpkg) and the "formatted numbers" option doesn't work anymore, as also the nearby one "show plus sign".

QGIS master on Ubuntu 18.04.

**Comment by pigreco** [comment]
confirm

**Comment by nyalldawson** [comment]
i'm on this one
