### ISSUE TITLE
Deleting features from GeoJSON causing misalignment between map and attribute table features

### ISSUE THREAD

**Issue by thismakessand** [qgis/QGIS#32396]
**Describe the bug**

Myself and several co-workers have been seeing some weird behavior when editing geojson (specifically when deleting rows) with QGIS (we are seeing it in both 3.4 and 3.8).  After deleting a row and saving, the features on the map appear to be misaligned with the features in the attribute table and zooming to a row selected in the attribute table takes you do a different/seemingly random feature on the map.  Some rows zoom to correct feature, some zoom to other features and some give a warning "Cannot zoom to selected feature(s) : No extent could be determined".

The edits are saved correctly though.  Stopping the edit session, and removing/re-adding the geojson layer fixes the issue (although stopping/starting the edit session does not).  It also appears to only happen when editing GeoJSON files.  I attached some sample data below.

It happens regardless of whether or not the attribute table is docked so I don't think it's the same as https://github.com/qgis/QGIS/issues/26310 

**How to Reproduce**

1. Add a GeoJSON layer
2. Open Attribute Table
3. Start editing session
4. Delete a row
5. Select a row in the attribute table
6. Use "Zoom map to the selected rows" button
Map should now zoom to the correct features on the map for each row
7. Save Edits
8. Use "Zoom map to the selected rows" button
Map now zooms to features that do not match the selected row

**QGIS and OS versions**
Having this issue on both Ubuntu 16.04 with gdal 2.2.2 and MacOS 10.13.6 with gdal 2.3 and MacOS with gdal 2.4

![image](https://user-images.githubusercontent.com/2924736/67526104-b20a3580-f679-11e9-91ea-6d77c17de114.png)
![image](https://user-images.githubusercontent.com/2924736/67527139-e979e180-f67b-11e9-9faf-c654aa8e6ff7.png)

**Additional context**

sample data:
```qgis_sample.geojson```:
```
{
"type": "FeatureCollection",
"name": "qgis_sample",
"features": [
{ "type": "Feature", "id": "wguynrhMG2e2bmYvtTon6BlxWL8=", "properties": { "addr:full": "1450 Ala Moana Blvd. STE 1272", "addr:city": "Honolulu", "addr:state": "HI", "addr:postcode": "96814" }, "geometry": { "type": "Point", "coordinates": [ -157.843756223636689, 21.289745250687552 ] } },
{ "type": "Feature", "id": "hbYLqCK3ZrtZyZQ2r24FYi2aRyA=", "properties": { "addr:full": "200 East Northern Lights Blvd", "addr:city": "Anchorage", "addr:state": "AK", "addr:postcode": "99503" }, "geometry": { "type": "Point", "coordinates": [ -149.880708, 61.195104 ] } },
{ "type": "Feature", "id": "g8wEfVB5AVA51wqv2KZhT0cr3XA=", "properties": { "addr:full": "1321 N. Columbia Center Blvd.", "addr:city": "Kennewick", "addr:state": "WA", "addr:postcode": "99336" }, "geometry": { "type": "Point", "coordinates": [ -119.225241, 46.208503 ] } },
{ "type": "Feature", "id": "yfLADTt1njgBaVpVHnpmoR8B74c=", "properties": { "addr:full": "1720 East Red Cliffs Drive", "addr:city": "St. George", "addr:state": "UT", "addr:postcode": "84790" }, "geometry": { "type": "Point", "coordinates": [ -113.533007744409502, 37.123757218658731 ] } },
{ "type": "Feature", "id": "CvhZM61O2vU1d4CmEb-O7XL9dSg=", "properties": { "addr:full": "8251 Flying Cloud Dr. #3000", "addr:city": "Eden Prairie", "addr:state": "MN", "addr:postcode": "55344" }, "geometry": { "type": "Point", "coordinates": [ -93.4306, 44.8634 ] } },
{ "type": "Feature", "id": "P_0Ta1sQ7f2m4cRyILuBzYwct-Q=", "properties": { "addr:full": "769 Iyannough Road", "addr:city": "Hyannis", "addr:state": "MA", "addr:postcode": "02601" }, "geometry": { "type": "Point", "coordinates": [ -70.292656, 41.667365 ] } }
]
}
```

**Comment by gioman** [comment]
>     8\. Use "Zoom map to the selected rows" button
>         Map now zooms to features that do not match the selected row

works as expected here on qgis master/linux.

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
