### ISSUE TITLE
Some few code spelling errors in QGIS-final-3_10_0.tar.gz

### ISSUE THREAD

**Issue by jschleus** [qgis/QGIS#32408]
As administrator of a FOSS server I have just added a new feature: Source code misspelling error checks for the supported software packages (using the command line program `codespell`).

A first check for a really big  project was just done as a trial for QGIS-final-3_10_0.tar.gz. The analysis report can be found here: https://fossies.org/linux/misc/QGIS-final-3_10_0.tar.gz/codespell.html

A hint: Clicking on a red colored spelling error in the "top" list jumps to the first match in the sortable actual spelling error occurrence list. Clicking on a matching member file let you browse that file while jumping to the according red marked line (in some cases the matching line may lie in the neighborhood).                      

I know it's not an important issue (especially since "surprisingly" few errors were found) so you may ignore it. But if you found wrong matches (false positives) please let me know it so that I can force a new improved check.

**Comment by roya0045** [comment]
Does your function provide a way to fix the spelling? If so you could make a PR to fix those typos.

**Comment by jschleus** [comment]
That is a reasonable and meaningful question but the answer is unfortunately "no".

I thought about such a function to create by using the `diff` command one or multiple patch files but the risk is too high that something is wrongly done. Maybe an option to let users (experts) select single spelling errors via a Web form for creating one or multiple  patch files would be acceptable so that they could use it for a PR. But that isn't trivial and not yet available.

By the way the used program [codespell](https://github.com/codespell-project/codespell) has such a - not yet tried by me - function (see for e.g. the options `--write-changes ` and `--interactive`).

**Comment by jschleus** [comment]
Although the issue is closed the small information that for the current releases two new analysis runs were done (using a slightly improved configuration):

https://fossies.org/linux/misc/QGIS-final-3_10_3.tar.gz/codespell.html
https://fossies.org/linux/misc/QGIS-final-3_12_0.tar.gz/codespell.html

**Comment by jef-n** [comment]
> Although the issue is closed the small information that for the current releases two new analysis runs were done (using a slightly improved configuration):
> https://fossies.org/linux/misc/QGIS-final-3_10_3.tar.gz/codespell.html
> https://fossies.org/linux/misc/QGIS-final-3_12_0.tar.gz/codespell.html

Following directories contain third party code and are therefore exclude from our spellchecking:
* src/plugins/grass/qtermwidget
* src/core/pal

**Comment by jschleus** [comment]
Thanks, that was overseen, so accordingly two new analysis runs were done.
