### ISSUE TITLE
QGIS Server Font Directory

### ISSUE THREAD

**Issue by StefanNiemeier** [qgis/QGIS#32404]
QGIS / QGIS Server 3.8.3  on Apache on Windows2012.

Theres a difference between displaying fonts in QGIS and displaying fonts from WMS by QGIS Server.
For example ARIAL in QGIS is not ARIAL by QGIS Server.

Even setting the environment variable QT_QPA_FONTDIR in httpd_qgis.conf doesn't work. The qgis-server-font-loader Plugin (https://github.com/avinet/qgis-server-font-loader) has also no effect.

Seems to be a bug.

Regards,
Stefan Niemeier

**Comment by StefanNiemeier** [comment]
Update:
Also in the new 3.10.0 QGIS/QGIS Server on Windows10 there is no effect by setting the QT_QPA_FONTDIR in the httpd_qgis.conf. 
I had thougth that the solution by #31743 solved the problem but it's still the same.

**My httpd_qgis.conf:**
![httpd_qgis conf](https://user-images.githubusercontent.com/18546726/67631705-f247fe80-f899-11e9-90e7-8eed8ad05893.PNG)

**The qgis_server.log:**
[qgis_server.log](https://github.com/qgis/QGIS/files/3775625/qgis_server.log)

**The Screenshots:**
Text in QGIS Project: (ARIAL):
![QGIS_Beschriftung](https://user-images.githubusercontent.com/18546726/67631743-8dd96f00-f89a-11e9-8602-4dae4ecf5f6d.PNG)

Text by QGIS Server WMS:
![QGIS_Server_WMS_Beschriftung](https://user-images.githubusercontent.com/18546726/67631783-f3c5f680-f89a-11e9-91ac-950f6efe9609.PNG)

Text combined:
![zusammen](https://user-images.githubusercontent.com/18546726/67631791-15bf7900-f89b-11e9-9ed8-5d9be4e03ac0.PNG)

**Comment by Livava1** [comment]
Same problem here: 3.10.2 QGIS/QGIS Server on Windows Server 2016 / Apache24 uses only default font in WMS. When project files from earlier versions have points symbolised with Font marker this is a show-stopper. The correct fonts are displayed in QGIS Desktop on the same server.

Another example: Setting _ITEMFONTFAMILY=Courier_ in GetLegendGraphic-requests has no effect.

**Comment by Livava1** [comment]
I upgraded from QGIS server 3.10.0? with correct fonts to 3.10.2-2 and the fonts are now default. It doesn't seem like QT_QPA_FONTDIR is used. Fonts are also ok if I use qgis-ltr-server 3.4.15-1, but this lack other fixes so I can't use it either.

**Comment by tobias-brunner** [comment]
I can confirm that on Windows QT_QPA_FONTDIR was respected in earlier 3.10 versions but not anymore in 3.10.2.

**Comment by Livava1** [comment]
This issue still exists in qgis-server 3.12.0-1.

**Comment by tobias-brunner** [comment]
Works in 3.10.3 though!

**Comment by Livava1** [comment]
I have tried qgis-ltr-server 3.10.3-1, but I can't get it to work.

**Comment by elpaso** [comment]
This is the only change I can think of: https://github.com/qgis/QGIS/commit/bd8a7164cb6efea8faad728447c63c76086af9ed#diff-d9cd4c7230f45da2c7db939ce9db2f88

**Comment by tobias-brunner** [comment]
> I have tried qgis-ltr-server 3.10.3-1, but I can't get it to work.

We don't use FCGIDInitialenv, but DefaultinitEnv instead - don't know if that helps...

like this:
DefaultInitEnv QT_QPA_FONTDIR "C:\Windows\Fonts"

**Comment by Livava1** [comment]
DefaultInitEnv solved the problem for me in qgis-ltr-server 3.10.3-1 - thank you! (But did not help for qgis-server 3.12.0-1)

**Comment by gioman** [comment]
> DefaultInitEnv solved the problem for me ~in qgis-ltr-server 3.10.3-1~ - thank you! ~(But did not help for qgis-server 3.12.0-1)~

@StefanNiemeier what is the status of this issue?

**Comment by do4sch** [comment]
Still a problem for me in 3.28.3.
See https://github.com/qgis/QGIS/issues/51688
