### ISSUE TITLE
Attribute table looses filter results

### ISSUE THREAD

**Issue by chiffr** [qgis/QGIS#32457]
**Describe the bug**
When a user have been working with an attribute table for a while with the filter "Show Selected Features" the selected features are lost in the listing. Changing the filter back and forth returns the selected features.
The text is greyed when the the selected features are missing. Attaching a screenshot of a complete attribute table with selected features and a screenshot where the selected feature is missing.

**How to Reproduce**
Re-open the attribute table and work for a few hours.

**QGIS and OS versions**
QGIS Info
QGIS Version: 3.4.12-Madeira
QGIS code revision: 625767347a
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Additional context**
[svar.zip](https://github.com/qgis/QGIS/files/3778658/svar.zip)
![qgis2-attribute_table](https://user-images.githubusercontent.com/7722309/67678888-0bc77400-f988-11e9-946c-6c56cf00fb63.jpg)
![qgis1-attribute_table](https://user-images.githubusercontent.com/7722309/67678889-0c600a80-f988-11e9-8825-955ed4b1421d.jpg)

**Comment by Pedro-Murteira** [comment]
@chiffr Is this still an issue in your case? I'm not able to replicate this behaviour on QGIS 3.16.15 and 3.22.2.
