### ISSUE TITLE
"Enum" input in a model is not listed in "Model input" in an algorithm

### ISSUE THREAD

**Issue by Gustry** [qgis/QGIS#32452]
**Describe the bug**

I have an "Enum" input in my model, with some predefined strings. The user can select only one:

![Capture d’écran de 2019-10-28 08-53-47](https://user-images.githubusercontent.com/1609292/67661053-7ebcf480-f960-11e9-8177-e7c58cefdd4a.png)

In an algorithm, I can't use this input, the combobox is empty:

![Capture d’écran de 2019-10-28 08-52-20](https://user-images.githubusercontent.com/1609292/67660986-559c6400-f960-11e9-83ee-61adfbc6f60e.png)

**QGIS and OS versions**

QGIS version | 3.11.0-Master | QGIS code revision | 776ed72c05
-- | -- | -- | --
Compiled against Qt | 5.12.4 | Running against Qt | 5.12.4
Compiled against GDAL/OGR | 2.4.2 | Running against GDAL/OGR | 2.4.2
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 12.0 (Ubuntu 12.0-2.pgdg19.04+1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.10.4
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Ubuntu 19.10
Active python plugins | processing; db_manager; MetaSearch

**Comment by nyalldawson** [comment]
It's easy enough to expose this setting to string inputs, BUT.... it will be a numeric value only, and probably not what you are after, right?

I think your particular use case would be addressed by using an expression based input for the parameter, where you check the model enum input numeric value with a case statement and return the desired matching string.

**Comment by Gustry** [comment]
> It's easy enough to expose this setting to string inputs, BUT.... it will be a numeric value only, and probably not what you are after, right?

Ah yes, I have been told indeed.  This would be a nice feature to have, enum as strings, to build some predefined combobox.

> I think your particular use case would be addressed by using an expression based input for the parameter, where you check the model enum input numeric value with a case statement and return the desired matching string.

Are you talking about having one **enum input** (called `Layer`) and another one **expression input** with the given expression : `CASE WHEN parameter('Layer') = '0' THEN 'point' ELSE 'multipolygons' END` ?

First issue, the `parameter()` is not shown in the expression dialog context.
And second issue, it seems the expression is not evaluated after that. I tried a quick example., sorry I have updated with dummy website example.
The expression is not evaluated when it's given to the next algorithm in a specific situation.

[expression_enum.txt](https://github.com/qgis/QGIS/files/3787348/expression_enum.txt)

**Comment by nyalldawson** [comment]
With the above PR this model will work correctly:

[expression_enum2.txt](https://github.com/qgis/QGIS/files/3796876/expression_enum2.txt)

**Comment by rduivenvoorde** [comment]
@nyalldawson  see 
https://lists.osgeo.org/pipermail/qgis-developer/2019-December/059677.html

Would it be difficult to expose the values in the enum?

I think this would be usefull... but no idea if complex or not

**Comment by invincible1215** [comment]
Still facing the same problem in 2022. Is there any example to resolve this problem?

**Comment by spatialthoughts** [comment]
+1 to this. Currently (QGIs 3.40) there is no way to get the text associated with an enum input - just the index. That means any algorithm that wants to use the enum input - has to rely on a hard-coded value with each index. If the order of the Enum inputs change or new values get added - it breaks the model. Would be nice to have a way to get an array of index and array of values from an input input
