### ISSUE TITLE
QGIS Crashes When Deleting Layout From Its Own Window

### ISSUE THREAD

**Issue by gisn8** [qgis/QGIS#32465]
**Describe the bug**

QGIS crashes when deleting layout from within the layout's own window

**How to Reproduce**

Open QGIS. Project -> New Print Layout. Tried with and without naming; no difference. Tried adding items, tried without adding items; makes no difference. In the layout window Layout -> Delete layout... Confirm. QGIS immediately closes.
Tested with no plugins on new profile on new empty project. When deleting a layout through the Layout Manager, does not occur.

**QGIS and OS versions**

QGIS version | 3.10.0-A Coruña | QGIS code revision | 6c816b4204
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 10.10 (Ubuntu 10.10-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Linux Mint 19.2
Active python plugins |  

I also tried on 3.8 on another Linux Mint. Same result.
And 3.4 on Windows 10 on VirtualBox. Same result.

**Additional context**

**Comment by nyalldawson** [comment]
Confirmed
