### ISSUE TITLE
Dashed lines surround the corners

### ISSUE THREAD

**Issue by osm-chenshi** [qgis/QGIS#32468]
**Feature description.**
i have a usefull idea. please create a button to "close" the cornes by dashed lines. see the links below.

https://downloads.psd-tutorials.de/Download/_userimages/Image/Stefan/workshops/Illustrator/Grundlagen/26_Breitenwerkzeug/12.gif
https://www.illustrator-tutorials.de/2012/02/01/adobe-illustrator-grundlagen-breitenwerkzeug-konturen/

**Comment by nyalldawson** [comment]
Can you describe (in English) exactly what this feature does?

**Comment by andreasneumann** [comment]
I guess what he asks for, is that the dashing patterns shouldn't be "strict" (as they are now) but allow some flexibility, analyze the geometries for corners and sharp angles and make sure there are no dashes, but always stroked part at such corners and sharp angles.

That would be something desirable for cartographers or graphic specialists, but probably not trivial to implement (though I think it might be possible, others have done it as well). I am pretty sure there are papers from Cartographers out there. Definitely, in the pre-digital analog age, cartographers had been taught to never use dashes at corners and sharp angles. If you are interested, I can dig up articles about that.

**Comment by andreasneumann** [comment]
The other illustration might be something totally different. @osm-chenshi - if you ask for two separate things, please open two separate issues.

**Comment by osm-chenshi** [comment]
only that what you can see in the first link is what i would like to use in qgis. a dashed line around a polygon, that has never a gap at the corners. the second link is only where i had it from.

**Comment by nyalldawson** [comment]
This was fixed in 3.18
