### ISSUE TITLE
Current CRS label (right corner) not updated after change through Python script

### ISSUE THREAD

**Issue by Vroei** [qgis/QGIS#32476]
Changing the current CRS through the python console or a plugin script will change the actual used CRS but the label at the right hand corner will not change to the new CRS.

can be tested from python console using:

```
target_crs = QgsCoordinateReferenceSystem(28992)
iface.mapCanvas().setDestinationCrs(target_crs)
```

**Comment by nyalldawson** [comment]
Use

    QgsProject.instance().setCrs(target_crs)

instead. That works correctly on 3.10.1

**Comment by Vroei** [comment]
Hi Nyall,




Thanks. That works!




Outlook voor Android downloaden







On Tue, Nov 26, 2019 at 1:46 AM +0100, "Nyall Dawson" <notifications@github.com> wrote:












Use
QgsProject.instance().setCrs(target_crs)



instead. That works correctly on 3.10.1
