### ISSUE TITLE
Change Log link error in Welcome screen on QGIS 3.10 

### ISSUE THREAD

**Issue by mcecchinato** [qgis/QGIS#32484]
After a clean intallation of QGIS 3.10 on windows 10 (italian Language) a "welcome screen" with a wrong link (to changelog page) and the version name have a letter error:
![immagine](https://user-images.githubusercontent.com/9415281/67766160-15b3aa80-fa4e-11e9-97f6-b72442422468.png)
- Link to CHANGELOg page is to 3.4 version and not to 3.10
- The name is not "Coruña" 

I use Standalone installer 64bit.

**Comment by jef-n** [comment]
should be also fixes in bd1b27087d94095318fbe8c9f17720b599007a42

**Comment by mcecchinato** [comment]
Thank you
