### ISSUE TITLE
Polygon Still Overlapping despite Avoid Overlap being checked

### ISSUE THREAD

**Issue by ar-siddiqui** [qgis/QGIS#32488]
I am creating polygons and I have topological editing on and have checked the avoid overlap options for the layer I am editing. Still, it works some time and sometimes does not. See the attached video.
[2019-10-29 11-08-59.zip](https://github.com/qgis/QGIS/files/3784278/2019-10-29.11-08-59.zip)

**Comment by lbartoletti** [comment]
@ar-siddiqui The overlap function can fail silently if the geometry it is supposed to avoid contains a geometry error. Can you check if this is the case for you?

![overlap mkv](https://user-images.githubusercontent.com/7521540/107198029-eaf82600-69f4-11eb-930f-94b7c8466056.gif)

**Comment by gioman** [comment]
>  The overlap function can fail silently if the geometry it is supposed to avoid contains a geometry error

@lbartoletti it should really not fail silently. Or even better it should also work when encountering a geom with errors, if possible (and if not really possible then throw an error).

**Comment by gioman** [comment]
@lbartoletti I think that the priority of this ticket should be raised: failing silently means that could cause serious mistakes for whi digitize and may  not realize that the features can have even tiny geometry errors (which are *very* common).

**Comment by lbartoletti** [comment]
@gioman You're right, I'll will add message to inform if there is a problem.

**Comment by ar-siddiqui** [comment]
@lbartoletti I don't have the same geometry to check if it has geometrical errors ... but I have encountered this issue multiple times ... so I would assume @gioman is write, ideally it should work if it can with geometrical errors but if not then error message is fine too.
