### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by jps2016** [qgis/QGIS#32482]
h2. User Feedback

h2. Report Details

*Crash ID*: 5868342a6d6148dd9044d538e3d9b89dd8f507a4

*Stack Trace*
<pre>
QEventDispatcherWin32::staticMetaObject :
QgsStatisticalSummaryDockWidget::~QgsStatisticalSummaryDockWidget :
QgsStatisticalSummaryDockWidget::~QgsStatisticalSummaryDockWidget :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
std::basic_string<char,std::char_traits<char>,std::allocator<char> >::operator+= :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.0.1-Girona
QGIS code revision: commit:a86bec25eb
Compiled against Qt: 5.9.2
Running against Qt: 5.9.2
Compiled against GDAL: 2.2.4
Running against GDAL: 2.2.4

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by nirvn** [comment]
Here's your problem: version 3.0.1. Update to the latest version, you'll find yourself in a much better situation.

**Comment by gioman** [comment]
> and don't say its the Plugins and to stop using them

you got it WRONG. We don't ask to stop using 3rd party plugins, when crashes happen we ask you to TRY if QGIS crashes with no 3rd party plugins, just as a way to determine where the issue is, QGIS or the plugin.
