### ISSUE TITLE
Crash when zooming in

### ISSUE THREAD

**Issue by Saijin-Naib** [qgis/QGIS#32489]
**Describe the bug**
QGIS appears to hang/crash when zoomed in much beyond 1:1 (seemingly when the dot grid appears on the background of the QGIS project).

**How to Reproduce**
1) Zoom in past 1:1 until dot grid appears, or until CPU usage jumps to 100%
2) Stop editing, zoom back to regular extent, CPU will not go down

**QGIS and OS versions**

QGIS version | 3.10.0-A CoruÃ±a | QGIS code revision | 6c816b4204
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Windows 10 (10.0)
Active python plugins | BoundaryDelineation; BufferByPercentage; changeDataSource; DEMto3D; FeatureGridCreator; GeoCoding; GeodesicDensifier; geomovetools; getools; GroupPointsWithinDistance; joinmultiplelines; kmltools; LAStools; latlontools; LineDirectionHistogram; lrs; MemoryLayerSaver; minimum_spanning_tree; mmqgis; networks; openeo-qgis-plugin-master; ORStools; oscars-georaster-qgis-plugin; ParallelLineConstruction; pdaltools; photo2shape; Polygons_Pile; polystrip; processing_circuitscape; processing_fusion; processing_gnm; processing_js; processing_prepair; processing_r; processing_saga; processing_taudem; processing_whitebox; project_colors_dock; qchainage; qconsolidate; qdraw; qgiscloud; QgisModelBaker; QGISRed; QGISSortAndNumber-master; qgis_resource_sharing; qgSurf; QRectangleCreator; QuickOSM; quick_map_services; realcentroid; refFunctions; SelectWithin; sen2cor_adapter; Serval; shapetools; snail; spatial_query_with_values; SplitPolygonShowingAreas; SpreadsheetLayers; statist; ThToolBox; toggle_labels_widget; trail_elevation_stats; vector_tiles_reader; wnt; db_manager; MetaSearch; processing

**Additional context**
https://www.youtube.com/watch?v=rruN8OOwPy8

**Comment by Saijin-Naib** [comment]
Can confirm same behavior with new/clean profile:


QGIS version | 3.10.0-A CoruÃ±a | QGIS code revision | 6c816b4204
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Windows 10 (10.0)
Active python plugins | db_manager; MetaSearch; processing



![image](https://user-images.githubusercontent.com/19295950/67783521-bc914a00-fa40-11e9-9624-b84c21cf1177.png)

**Comment by nyalldawson** [comment]
I can't reproduce -- can you share a project?

**Comment by Saijin-Naib** [comment]
Scrubbed project attached, still exhibits the noted behavior above despite being scrubbed and run under a newer build of QGIS 3.10 with much newer dependency libraries:


QGIS version | 3.10.0-A Coruña | QGIS code revision | 6ffa89eb3e
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.2 | Running against GDAL/OGR | 3.0.2
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.2.1 | Running against PROJ | Rel. 6.2.1, November 1st, 2019
OS Version | Windows 10 (10.0)
Active python plugins | CalculateGeometry; cartogram3; changeDataSource; DataPlotly; DEMto3D; dzetsaka; GeoCoding; GeodesicDensifier; geomovetools; getools; GroupPointsWithinDistance; guided_offline_editing; htpgeoprocessor; joinmultiplelines; karika; kmltools; kml_style_importer; LandSurveyCodesImport; LAStools; latlontools; LineDirectionHistogram; lrs; maps2winbugs; MemoryLayerSaver; minimum_spanning_tree; mmqgis; networks; openlayers_plugin; oscars-georaster-qgis-plugin; ParallelLineConstruction; pdaltools; photo2shape; PluginLoadTimes; Polygons_Pile; polystrip; processing_circuitscape; processing_fusion; processing_gnm; processing_js; processing_pktools; processing_prepair; processing_r; processing_saga_nextgen; processing_taudem; processing_trajectory; processing_whitebox; project_colors_dock; qchainage; qconsolidate; qdraw; qgiscloud; QGISSortAndNumber-master; QRectangleCreator; QuickOSM; realcentroid; refFunctions; SelectWithin; sen2cor_adapter; Serval; shapetools; snail; spatial_query_with_values; SplitPolygonShowingAreas; SpreadsheetLayers; statist; ThToolBox; toggle_labels_widget; trail_elevation_stats; wnt; db_manager; processing



[Debris_Overview_2.zip](https://github.com/qgis/QGIS/files/3892367/Debris_Overview_2.zip)
