### ISSUE TITLE
Crash using the field calculator

### ISSUE THREAD

**Issue by martinfernandoortiz** [qgis/QGIS#32490]
QGIS Crashed when i was working with field calculator in layer of a geopackage. The layer has another layer join.
The profile is clean with no plugins.
Report Details

Crash ID: 3d27613a2f0cbd155104b686fa38b0df83c50fd1

Stack Trace

QVariant::operator= :
QgsAttributeForm::onUpdatedFields qgsattributeform.cpp:979
QMetaObject::activate :
QgsVectorLayer::updateFields qgsvectorlayer.cpp:3449
QgsVectorLayerUndoCommandAddAttribute::redo qgsvectorlayerundocommand.cpp:317
QUndoStack::push :
QgsVectorLayerEditBuffer::addAttribute qgsvectorlayereditbuffer.cpp:273
QgsFieldCalculator::accept qgsfieldcalculator.cpp:227
QMetaObject::activate :
QDialogButtonBox::~QDialogButtonBox :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:373
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:373
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
QgisApp::fieldCalculator qgisapp.cpp:7241
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:373
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:373
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyFunction_FastCallDict :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:373
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:373
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1542
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.4.13-Madeira
QGIS code revision: 64ad560274
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by martinfernandoortiz** [comment]
Yes. I had this problems like 3 times. I tried again to replicate but it worked.
How was the problem:
First i made an intersect between centroides and barrios.shp. (it was a temp file)
After that i made the join between centroides and the intersection (using for both files co_frac_rad)
Then i tried to make the field calculator creating a new string file and it crashed.

Regards, and thank you for the great   job!

[Proyectos.zip](https://github.com/qgis/QGIS/files/3784504/Proyectos.zip)

**Comment by haubourg** [comment]
@martinfernandoortiz can you be more explicit on what steps we need to do to reproduce? A screencast would be perfect

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
