### ISSUE TITLE
qgis icon on taskbar disappears in windows 10

### ISSUE THREAD

**Issue by mikecusi** [qgis/QGIS#32500]
**Describe the bug**

The QGIS icon in the taskbar appears properly after starting QGIS. After some time, while working on the open project, the icon in the taskbar gets replaced by a generic icon.

**How to Reproduce**

**QGIS and OS versions**

QGIS version 3.8.3-Zanzibar
QGIS code revision 685d8b15d2
Compiled against Qt 5.11.2
Running against Qt 5.11.2
Compiled against GDAL/OGR 2.4.1
Running against GDAL/OGR 2.4.1
Compiled against GEOS 3.7.2-CAPI-1.11.0
Running against GEOS 3.7.2-CAPI-1.11.0 b55d2125
PostgreSQL Client Version 10.8
SpatiaLite Version 4.3.0
QWT Version 6.1.3
QScintilla2 Version 2.10.8
Compiled against PROJ 5.2.0
Running against PROJ Rel. 5.2.0, September 15th, 2018
OS Version Windows 10 (10.0)

**Comment by mikecusi** [comment]
![image](https://user-images.githubusercontent.com/49886264/67819700-04c47100-fb02-11e9-859c-5ba4e9514941.png)

**Comment by mikecusi** [comment]
![image](https://user-images.githubusercontent.com/49886264/67820292-68e83480-fb04-11e9-8f54-a21c4ec3d7cd.png)


![image](https://user-images.githubusercontent.com/49886264/67820284-61c12680-fb04-11e9-9178-009499bba518.png)

**Comment by junkchandu** [comment]
Problem occurs even with just one instance of QGIS being open. This problem seems peculiar to Windows 10 and after QGIS version 3.8 (not sure)

**Comment by haubourg** [comment]
We have three similar issues #32368 / #33692

**Comment by Pedro-Murteira** [comment]
@mikecusi I've been keeping an eye out for this one while working on a few projects and I never managed to replicate it. (QGIS 3.16.15 and 3.22.2). Is this still an issue with you?
