### ISSUE TITLE
QWebView issues

### ISSUE THREAD

**Issue by enricofer** [qgis/QGIS#32507]
After QGIS 3.10 upgrade I'm having a big problem with QWebView that throws exceptions and does not run javascript libraries like googlemaps threejs or mapillaryjs anymore.The affected platform is Windows, surely with osgeo installer, I have not tested standalone version yet. Linux platform seems not affected.
You can simply reproduce the issues running go2streetview go2mapillary or Qgis2threejs plugins and inspecting the QWebView window. you will get something like this: https://user-images.githubusercontent.com/7544963/67840103-67634000-faf5-11e9-8d96-6170bf312169.png Where it appears there is a problem with webgl.Go2streetview can be fixed manually downgrading QtWebKit from 5.221-1 (?) to 5.9 from osgeo4w installer: https://user-images.githubusercontent.com/7544963/67840590-81515280-faf6-11e9-85a6-14f0c547c237.pngFor the other plugins the issues still persist and I can' found any fix.

**Comment by gioman** [comment]
If you haven't done it already I suggest to post this also on the developers mailing list.

**Comment by fgianoli** [comment]
I have this issue in Windows and QGIS 3.10 using the plugin go2mapillary.
The error is  QtNetwork Error 5 and the plugin GUI is not loaded.

**Comment by inedecubber** [comment]
I'm still using Qgis 3.0 on a windows machine and have the same problem with the go2mapillary-plugin, which I just installed. No images visible in the GUI, error on WEBGLrenderer and weakmap error in the mapillary.min.js

**Comment by denchat** [comment]
@inedecubber  Would you mind looking up the version of this .dll?
C:\Program Files\QGIS 3.0\apps\qt5\bin\Qt5WebKit.dll
( goto the folder / right click on the file / properties / details )

In my use case of go2streetview, as enricofer [_suggests_](https://user-images.githubusercontent.com/7544963/67840590-81515280-faf6-11e9-85a6-14f0c547c237.png), I download [_OSGEO4W_](https://trac.osgeo.org/osgeo4w/#QuickStartforOSGeo4WUsers)'s `qtwebkit-qt5-lib` 5.9 then put them in `apps\qt5\bin`, the plugin works again.

Qt5WebKit.dll (In the package, there are other two files also)
Version: 5.9.1.0
SHA256: 1B61D648986C9E90054F5723B7C2E8A5A1A3AD1BB145BC8FF848CB672A1F8CBC

I'm on Qgis 3.10.0 though.

**Comment by gioman** [comment]
Is this a QGIS issue or a upstream library one?

**Comment by enricofer** [comment]
I verified that qtwebview loads local files without any issue, Recent DataPlotly  Qgis2Threejs plugins are not affected. go2streetview and go2mapillary have problem to load remote pages and resources (javascript libs) and QT log reports: WARNING    stream 3 finished with error: "Server is unable to maintain the header compression context for the connection"
As stated above downgrading qtwebkit to 5.9 partially solves the issue for go2streetview. QtWebView can load external resources again but remains an issue with webgl that prevent go2mapillary to view images in QwebView.
I'm working on a compiled version of QGIS running under Linux that seems to be immune. so I tend to exclude QGIS issue. Maybe a Upsteam or a packaging  issue, I don't know. In this case I would ask your help to open a ticket on qtwebkit, but in the meanwhile would be great if we could rollback to the previous running release of webkit, if possible.

**Comment by enricofer** [comment]
I downloaded and installed standalone QGIS 3.8.3 and QGIS 3.10.0 to verify issue persistence and I confirmed that QGIS 3.8.3 is immune.
Then I compared the installation directories and I found that Qt5 and QtWebKit related files between the two installation are unchanged so I'm thinking to something inside QGIS implementation, maybe qgsapplication or qgsnetworkmanager?

**Comment by enricofer** [comment]
I'm doing some test on QWebView connection.
I'm actually able to load local html pages and http page but https connections failed so I suppose this issue is related to this one: https://github.com/qgis/QGIS/issues/32920

**Comment by enricofer** [comment]
I tested QGIS nightly build f9f00d3388 and issue is fixed!

**Comment by denchat** [comment]
Just tried `3.10.0-30` from `OSGeo4W-x86_64`. Instead of white screen, it turns black and issues a warning on the log window:

> `WARNING    stream 5 finished with error: "Server is unable to maintain the header compression context for the connection"`

Perhaps, having to downgrade `QtWebKit` to `5.9.1` until #32920 is fixed then.

**Comment by enricofer** [comment]
The issue is fixed in master 3.11 but the fix have not been backported to release 3.10.1
Will Qgis 3,10 ever fixed?
![Screenshot 2020-01-16 08 50 43](https://user-images.githubusercontent.com/7544963/72504465-26e6a900-383e-11ea-8bde-95647f93e944.png)

**Comment by elpaso** [comment]
@enricofer out of curiosity, what was exactly the fix? Downgrade webkit?

**Comment by enricofer** [comment]
I can't point you to the fix. I don't know what have been done in master to solve the issue. I only suppose the fix is related to the the issue mentioned above by @jef-n.
Downgrading the webkit to 5.9 is a solution only for go2streetview plugin. Go2mapillary fails probably executing webgl related javascript code.
Anyway either the plugins run without errors in nightly QGIS:
![Screenshot 2020-01-16 11 18 21](https://user-images.githubusercontent.com/7544963/72516999-e6455a80-3852-11ea-8315-a6365d1489f2.png)

**Comment by denchat** [comment]
[QGIS 3.10.2 Release] In my machine now works fine with go2streetview.

[QGIS 3.11.0-61 4a7ea580e9 ] Plugin go2streetview somehow triggers a critical message here

> `CRITICAL    Qt : Qt WebEngine seems to be initialized from a plugin. Please set Qt::AA_ShareOpenGLContexts using QCoreApplication::setAttribute before constructing QGuiApplication.`

**Comment by nyalldawson** [comment]
That's a plugin bug, in the go2streetview plugin. You **can't** use Qt webengine from qgis python plugins, it's just not possible.

**Comment by enricofer** [comment]
Reviewing the code I can't find any reference to QtWebEngine (the plugin widget works on QWebView)
and I can't figure where and how the reported critical message raises.
Please @nyalldawson can you point me where investigate to correct the issue?

**Comment by denchat** [comment]
From this [**answer**](https://stackoverflow.com/q/56159475/6370128) from stackoverflow

> ```
>   if __name__ == '__main__':
>       QtCore.QCoreApplication.setAttribute(QtCore.Qt.AA_ShareOpenGLContexts)
>       qt_app = QtWidgets.QApplication(sys.argv)
>       ...
> ```

I guess this is because the `Qt::AA_ShareOpenGLContexts` is suppose to be set before launching a Qt app as shown in this [**answer**](https://bugreports.qt.io/browse/QTBUG-51379?focusedCommentId=309052&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-309052) from qt dev website

> ```
> QGuiApplication::setAttribute(Qt::AA_ShareOpenGLContexts);
> QGuiApplication app(argc, argv);
> QQmlApplicationEngine engine;
> engine.load(QUrl(QStringLiteral("qrc:/main.qml")));
> return app.exec();
> ```
