### ISSUE TITLE
Layer Styling only partial on WFS-sources

### ISSUE THREAD

**Issue by Ellebjerg** [qgis/QGIS#32509]
I have a problem with fill color on WFS-source polygons in QGIS 3.10. I can change the Simple fill color, but not the Fill color. This results in a change of color in the map, but in the legend the correct color is only displayed when the layer is inactive. When I mark the layer as my active layer, the layer is shown with the original automatically applied color. I have attached a screen clipping to examplify.
There is also a problem with the Feature count only being correct sometimes, but this is of less importance.
Thanks for a great product!
Best regards
Lars Ellebjerg
![qgis_wfs_style](https://user-images.githubusercontent.com/10741426/67845342-a1d1da80-faff-11e9-8571-7d95d9eeffbe.JPG)

**Comment by gioman** [comment]
@Ellebjerg Did it worked in previous releases? any public URL?

**Comment by Ellebjerg** [comment]
I have just tried with the same wfs-layer in 3.4.10. Here it works just fine.

The layer is from https://services.kortforsyningen.dk/service?servicename=fot2007_gml212&version=2.0.0&token=XXXXXXXXXXX

The service is public, but you have to sign up for a user and use a token to access it. If you do not want to do this yourself, you may talk to someone at Septima P/S (septima.dk). I believe they contribute to QGIS development.

**Comment by gioman** [comment]
> The layer is from https://services.kortforsyningen.dk/service?servicename=fot2007_gml212&version=2.0.0&token=XXXXXXXXXXX
> 
> The service is public, but you have to sign up for a user and use a token to access it. If you do not want to do this yourself, you may talk to someone at Septima P/S (septima.dk). I believe they contribute to QGIS development.

can you check if this 

> The layer is from https://services.kortforsyningen.dk/service?servicename=fot2007_gml212&version=2.0.0&token=XXXXXXXXXXX
> 
> The service is public, but you have to sign up for a user and use a token to access it. If you do not want to do this yourself, you may talk to someone at Septima P/S (septima.dk). I believe they contribute to QGIS development.

I cannot replicate using an open service like

https://demo.mapserver.org/cgi-bin/wfs

**Comment by Ellebjerg** [comment]
I can reproduce it, but I have also discovered that it is not a change in color. It is because the gray marker color indicating the selected layer masks and thereby changes the appearance of the color in the layers menu. 
It happens with all colors, but it is clearest with the yellow color from my example, which turns green when masked.
So it is not an actual error, but it is a point for improvement.
Thanks!
Lars

**Comment by gioman** [comment]
>  So it is not an actual error, but it is a point for improvement.

feel free to file a feature request.
