### ISSUE TITLE
Settings menu misleadingly shows most recently launched user profile as active

### ISSUE THREAD

**Issue by AlisterH** [qgis/QGIS#32506]
In recent versions of QGIS under "Settings>User Profiles" the user profiles are listed.  Clicking on one of the entries does not switch to that profile; it launches a new instance of QGIS using that profile.  This is handy.
The icon for one of the entries in the list is shown as "active".  But this is misleading, because it is not the profile that is in use.  If you click one of the entries then that entry will be highlighted i.e. the _most recently launched_ profile is highlighted, not the profile that is actually in use.
Note that QGIS does also display the profile name in the title bar in brackets [], but for some reason not for the "default" profile.
![image](https://user-images.githubusercontent.com/714600/67829173-19712b00-fb3b-11e9-9fb9-8697e903d44a.png)

**Comment by haubourg** [comment]
Confirmed on QGIS 3.8.2.

**Comment by AlisterH** [comment]
> If you click one of the entries then that entry will be highlighted i.e. the most recently launched profile is highlighted, not the profile that is actually in use.

I noticed the behaviour is slightly more complicated than this.

1. After clicking another profile you can click back on the original one, and it will highlight (it won't launch another instance).
2. If you don't do (1) and you close the window that you opened in the new profile, the original window will go back to highlighting the correct profile.

(2) might make you think that what this is supposed to be indicating is the profile that will be active next time you start QGIS from the start menu or wherever.  But it isn't, because the next time you start QGIS from the start menu it always starts in whatever profile was started most recently.

**Comment by Pedro-Murteira** [comment]
This is still true on QGIS 3.16.14 and 3.22.1.
