### ISSUE TITLE
QGIS 3.10.0 fails to launch on Windows 10

### ISSUE THREAD

**Issue by charinator** [qgis/QGIS#32501]
Hi there, I have downloaded the OSGeo4W and installed QGIS 3.10.0 but it fails to launch (no error messages received). I have been trying to install it for the past 3 weeks now and none of the versions have worked. 
Please help!
Thanks
Charlotte

**Comment by gioman** [comment]
Have you ruled out being a local issue by trying on a different computer?

**Comment by charinator** [comment]
Hey - Yes, I am in an office with 10 others who can all run it on the same computer. Must be something specific to my computer...
