### ISSUE TITLE
python3 inspect.getargspec() error

### ISSUE THREAD

**Issue by Djedouas** [qgis/QGIS#32516]
Hi !

From [inspect.getargspec doc](https://docs.python.org/3.8/library/inspect.html#inspect.getargspec) we can see the following :

`Deprecated since version 3.0: Use getfullargspec() for an updated API that is usually a drop-in replacement, but also correctly handles function annotations and keyword-only parameters.`

I want to add annotations to my QGIS forms, but I can't because [qgsattributeform.cpp](https://github.com/qgis/QGIS/blob/b2e712149312390b483cfb3c9be4c63e875694f0/src/gui/qgsattributeform.cpp#L1767) still uses `getargspec()` instead of `getfullargspec()`.

The error I run into:
`ValueError: Function has keyword-only parameters or annotations, use getfullargspec() API which can support them`

**Comment by m-kuhn** [comment]
Hi

Can you

- add steps to reproduce this error
- if you are confident that simply replacing this inside qgsattributeform.cpp is sufficient, you could open a pull request. Navigate to https://github.com/qgis/QGIS/blob/master/src/gui/qgsattributeform.cpp and click the pencil on top to start a change proposal (pull request).

**Comment by Djedouas** [comment]
Hi,

Steps to reproduce the error:

Run this script into QGis Python console
```
vl = QgsVectorLayer("point?crs=epsg:4326&field=id:integer", "test layer", "memory")
c = vl.editFormConfig()

c.setInitCode("""
from qgis.PyQt.QtWidgets import QDialog
from qgis.core import QgsFeature, QgsVectorLayer

def formOpen(dialog: QDialog, layer: QgsVectorLayer, feature: QgsFeature) -> None:
    pass
""")

c.setInitFunction("formOpen")
c.setInitCodeSource(QgsEditFormConfig.CodeSourceDialog)
vl.setEditFormConfig(c)
dlg = QgsAttributeDialog(vl, QgsFeature(), False)
```

And the outputs are:
- the ValueError in the Python console and in the log panel "Python Errors"
- an error popup telling that `formOpen` couldn't be found (consequence of the python error)

```ValueError: Function has keyword-only parameters or annotations, use getfullargspec() API which can support them```
