### ISSUE TITLE
Unable to run GRASS plugin on MacOS 

### ISSUE THREAD

**Issue by PeterPetrik** [qgis/QGIS#32511]
```
File "/Applications/QGIS3.10.app/Contents/Resources/grass7/bin/_grass76", line 2207, in <module>
main()
File "/Applications/QGIS3.10.app/Contents/Resources/grass7/bin/_grass76", line 2143, in main
grass_gui=grass_gui)
File "/Applications/QGIS3.10.app/Contents/Resources/grass7/bin/_grass76", line 1390, in lock_mapset
ret = call([gpath("etc", "lock"), lockfile, "%d" % os.getpid()])
File "/Applications/QGIS3.10.app/Contents/Resources/grass7/bin/_grass76", line 247, in call
return subprocess.call(cmd, **kwargs)
File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/subprocess.py", line 323, in call
with Popen(*popenargs, **kwargs) as p:
File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/subprocess.py", line 775, in __init__
restore_signals, start_new_session)
File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/subprocess.py", line 1522, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/Cellar/osgeo-grass/7.6.1_5/grass76/etc/lock': '/usr/local/Cellar/osgeo-grass/7.6.1_5/grass76/etc/lock'
/Applications/QGIS3.10.app/Contents/Resources/grass7/grass76.sh: line 20: /private/var/folders/9_/1ntz1sgx1qgflk2pyshntrmr0000gn/T/processing_8f307747f31d49f5b7353446df4f17cb/grassdata/temp_location/PERMANENT: is a directory
```

**Comment by PeterPetrik** [comment]
workaround (replace with your QGIS version)

in file: /Applications/QGIS3.10.app/Contents/Resources/grass7/bin/_grass76
replace /usr/local/Cellar/osgeo-grass/7.6.1_5/grass76 with /Applications/QGIS3.10.app/Contents/Resources/grass7

**Comment by PeterPetrik** [comment]
fixed in qgis-mac-packager. 
TODO: test nighlty from 31Aug and check if GRASS works 
https://qgis.org/downloads/macos/

**Comment by dkav** [comment]
I get the following error on 3.10 (downloaded Nov 5) with the Grass plugin enabled:

_GRASS init error : GRASS was not found in '/usr/local/opt/osgeo-grass/grass-base' (GISBASE), provider and plugin will not work._

I was also unable to get v.voronoi.skeleton to work from the processing toolbox (Grass plugin disabled). Here is the error:

_FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/Cellar/osgeo-grass/7.6.1_5/grass76/etc/lock': '/usr/local/Cellar/osgeo-grass/7.6.1_5/grass76/etc/lock'
/Applications/QGIS3.10.app/Contents/Resources/grass7/grass76.sh: line 20_

**Comment by dkav** [comment]
When I apply your workaround the plugin issue remains. The v.voronoi.skeleton does proceed further along only to fail with the following: 

_/private/var/folders/zn/l8w7w5pj55z3nqxjmg8zd3j40000gn/T/processing_e94583737c764df0be271f2caa57bfc3/grassdata/grass_batch_job.sh: line 5: v.voronoi.skeleton: command not found_

**Comment by neteler** [comment]
Update: GRASS GIS 7.8.1 with support for Python 3, PROJ 6 and GDAL 3 has been released:

- https://github.com/OSGeo/grass/releases/tag/7.8.1
- https://trac.osgeo.org/grass/wiki/Release/7.8.1-News

**Comment by spatialthoughts** [comment]
> workaround (replace with your QGIS version)
> 
> in file: /Applications/QGIS3.10.app/Contents/Resources/grass7/bin/_grass76
> replace /usr/local/Cellar/osgeo-grass/7.6.1_5/grass76 with /Applications/QGIS3.10.app/Contents/Resources/grass7

The workaround works for me on  3.10 downloaded on 7Nov.

**Comment by PeterPetrik** [comment]
can someone confirm that nightly builds with grass now works ok? if yes we can trigger rebuild of LTR and PR qgis to have this fixed

**Comment by dkav** [comment]
v.voronoi.skeleton from the Processing Toolbox worked on the nightly build. Grass Plugin did not.

**Comment by leonmvd** [comment]
I came across this Interesting solution. Toggle editing mode on the layer you are processing and the tool will work https://gis.stackexchange.com/questions/63000/how-to-resize-shapefile-features-proportionally-in-qgis

**Comment by davidafuller01** [comment]
I get the same error as @dkav (`**GRASS init error:** GRASS was not found in '/usr/local/opt/osgeo-grass/grass-base' (GISBASE), provider and plugin will not work.`) simply trying to toggle on GRASS7 via the Plugins manager.

The workaround suggested above isn't applicable as I installed from the QGIS.org download page (not Homebrew). Here's what the applicable portion of `/Applications/QGIS3.10.app/Contents/Resources/grass7/bin/_grass76` looks like on my CLEAN install (i.e., prior 3.4 version fully uninstalled):

```
# ----+- Python 3 compatibility end -+----

# Variables substituted during build process
if 'GISBASE' in os.environ:
    # TODO: should this be something like GRASS_PATH?
    # GISBASE marks complete runtime, so no need to get it here when
    # setting it up, possible scenario: existing runtime and starting
    # GRASS in that, we want to overwrite the settings, not to take it
    # possibly same for GRASS_PROJSHARE and others but maybe not
    gisbase = os.environ['GISBASE']
else:
    gisbase = "/Applications/QGIS3.10.app/Contents/Resources/grass7"
cmd_name = "grass76"
grass_version = "7.6.1"
ld_library_path_var = 'DYLD_LIBRARY_PATH'
if 'GRASS_PROJSHARE' in os.environ:
    config_projshare = os.environ['GRASS_PROJSHARE']
else:
    config_projshare = "/Applications/QGIS3.10.app/Contents/Resources/proj/proj"

gisbase = os.path.normpath(gisbase)
```

**Comment by dkav** [comment]
@gioman if the GRASS plugin is abandoned per your [comment](https://github.com/qgis/QGIS/issues/34721#issuecomment-592090316) elsewhere would it not be helpful to remove the plugin altogether and eliminate confusion?

**Comment by gioman** [comment]
> @gioman if the GRASS plugin is abandoned per your [comment](https://github.com/qgis/QGIS/issues/34721#issuecomment-592090316) elsewhere would it not be helpful to remove the plugin altogether and eliminate confusion?

@dkav it is a good question. I would have discussed it in the upcoming dev meeting but it has been canceled, so I will do it in the next, but feel free to raise the issue in the developers mailing list.

**Comment by gioman** [comment]
> @gioman if the GRASS plugin is abandoned per your [comment](https://github.com/qgis/QGIS/issues/34721#issuecomment-592090316) elsewhere would it not be helpful to remove the plugin altogether and eliminate confusion?

@dkav but also note that despite being "abandoned" is also still working on Linux and Windows.

**Comment by neteler** [comment]
Let me recommend to switch to GRASS GIS 7.8 which supports Python 3 (since 7.6 is really old...).

**Comment by dkav** [comment]
@gioman did you ever get a chance to bring this issue up? I haven't followed up myself.

**Comment by christro** [comment]
Is there already a solution? I can not find a workaround to fix this problem on Mac OS.

**Comment by christro** [comment]
At a first glance the following workaround was successful

```
sudo mkdir -p /usr/local/opt/osgeo-grass
sudo ln -s /Applications/QGIS3.10.app/Contents/Resources/grass7 /usr/local/opt/osgeo-grass/grass-base

```

But If I load a GRASS layer, I get the following errors
```
GRASS provider Cannot get projection: Cannot find module /Applications/QGIS3.10.app/Contents/MacOS/lib/qgis/grass/modules/qgis.g.info7
GRASS provider Cannot get raster extent : Cannot find module /Applications/QGIS3.10.app/Contents/MacOS/lib/qgis/grass/modules/qgis.g.info7
GRASS provider Cannot get map info Cannot find module /Applications/QGIS3.10.app/Contents/MacOS/lib/qgis/grass/modules/qgis.g.info7
```
There is no file with the name "qgis.g.info7" in the folder "/Applications/QGIS3.10.app" and even the whole folder qgis is missing in "/Applications/QGIS3.10.app/Contents/MacOS/lib/". So my question: should I give up any attempts to fix this by myself, because the GRASS Plugin is completely broken in QGIS 3.10 LTR?

**Comment by gioman** [comment]
> because the GRASS Plugin is completely broken in QGIS 3.10 LTR

@christro it seems broken at least on macOS.

**Comment by christro** [comment]
Status GRASS Plugin for QGIS 3.12.2

Grass Plugin can be loaded, but raster layer can not be added. Adding raster layer results in the following error
```
2020-05-09T17:20:49 CRITICAL Invalid Layer :

GRASS provider Cannot get projection: Cannot find module /Applications/QGIS3.12.app/Contents/MacOS/lib/qgis/grass/modules/qgis.g.info7
GRASS provider Cannot get raster extent : Cannot find module /Applications/QGIS3.12.app/Contents/MacOS/lib/qgis/grass/modules/qgis.g.info7
GRASS provider Cannot get map info: Cannot find module /Applications/QGIS3.12.app/Contents/MacOS/lib/qgis/grass/modules/qgis.g.info7

Raster layer Provider is not valid (provider: grassraster, URI: /Users/xxx/shared/data/spearfish60_grass7/PERMANENT/cellhd/elevation.dem
```

**Comment by christro** [comment]
Status GRASS Plugin for QGIS 3.13.0-Master (Nightly Build 09/05/20)

The same as for QGIS 3.12.2, no improvements

**Comment by gioman** [comment]
@christro I think is clear that the GRASS plugin is not working on QGIS 3 on macOS. If there will be any development on this you will get a notification.

**Comment by christro** [comment]
Thanks for this clarification. 
The last version was QGIS 3.8 for which the GRASS Plugin was really working on Mac OS. This was also the last version, which was installed with the old installer. I thought, it would be maybe useful to document this, also for people which have the same problem.
The GRASS Plugin is according to the Plugin Manager a so called Core Plugin and I am relying on this. I am using this Plugin also for teaching and this for years and now I am a little bit worried that it is broken since 3.10. Therefore I wanted to document the status of the GRASS Plugin here.

**Comment by PeterPetrik** [comment]
I am working on it. Unfortunately it is not that easy as it looks. Hopefully should be ready with QGIS 3.14 (along with GDAL3 and PROJ6 and other updates)

**Comment by christro** [comment]
@PeterPetrik and @gioman: Thank you very much for your help and your fast reply

**Comment by gioman** [comment]
Tested on 3.14.0 and 3.10.7 on macOS Catalina:

`GRASS init error: GRASS was not found in '/usr/local/osgeo-grass/grass-base' (GISBASE), provider and plugin will not work.`

**Comment by ydeznutz** [comment]
i got this eror today, any solution?

**Comment by gioman** [comment]
> any solution

@ydeznutz if you don't really need to use the GRASS plugin then you can run GRASS tools in the Processing toolbox.

**Comment by ronenschmitz** [comment]
Hi all, now I hope this is good news for everybody:
In QGIS 3.10.8, when I ran it for the first time, it showed me this error 
`GRASS init error: GRASS was not found in '/usr/local/osgeo-grass/grass-base' (GISBASE), provider and plugin will not work.` – like mentioned above. 

The solution that worked was:
I anyways went to Plugins/GRASS/ and everything was greyed out except for `GRASS Options`, which I selected.
In the `General`-Tab there is an option to manually browse for `Applications/QGIS3.10.app/Contents/Resources/grass7`. Make sure to hit the radio button `Custom`.

and finally the `GRASS init error` is gone.

Do test to see if it's working for you.

**Comment by dkav** [comment]
@ronenschmitz's solution worked for me on QGIS 3.14.1.

**Comment by PeterPetrik** [comment]
Can you try with the nightly2 with the clean user profile? 
https://qgis.org/downloads/macos/nightly2/qgis_nightly2_master_20200915_134924.dmg

**Comment by mapninja** [comment]
I seem to be having the same issue, an issue I've seen many times in the past. My routine for testing a new installation of QGIS is to add the QuickMapPlugin, Create random points and then use v.voronoi on those points to  test the historically finicky GRASS processing tools. 

1. Deleted user profile for all QGIS users and uninstalled previous apps
2. Download Latest Release: qgis-macos-pr.dmg and install
3. Open QGIS with new empty doc
_FYI, I don't think the next 2 steps have anything to do with the issue, but adding them full acccounting:_
4. Install QuickMapServices Plugin, add contrib services
5. Add Stamen Toner Lite
6. Run "Random points in extent" from Processing Panel
    a. Use Canvas Extent
    b. 10 Points
    c. Target CRS: 3857 (also tried outputing to 4326, same results)
    d. [Create temporary layer]
7. Runs fine, produces expected random points
8. Run v.voronoi tool on resulting random points
    a. Use Map Canvas Extent
    b. All else=default
    c. Save to temp
9. Fails with the error, below
10. ReRun with option to  save to point.shp produces the  same error.  
11. Identical results for 40+ students,using LTR
12. Repeat exact steps with fresh LTR, including deleting the User Profile
13. same results, exactly.



## Log WIndow:  
`QGIS version: 3.14.16-Pi
QGIS code revision: a235a149f0
Qt version: 5.12.3
GDAL version: 2.4.1
GEOS version: 3.7.2-CAPI-1.11.2 b55d2125
PROJ version: Rel. 5.2.0, September 15th, 2018
Processing algorithm…
Algorithm 'v.voronoi' starting…
Input parameters:
{ '-l' : False, '-t' : False, 'GRASS_MIN_AREA_PARAMETER' : 0.0001, 'GRASS_OUTPUT_TYPE_PARAMETER' : 0, 'GRASS_REGION_PARAMETER' : '-13670428.191800000,-13586035.687300000,4532539.747800000,4571278.579000000 [EPSG:3857]', 'GRASS_SNAP_TOLERANCE_PARAMETER' : -1, 'GRASS_VECTOR_DSCO' : '', 'GRASS_VECTOR_EXPORT_NOCAT' : False, 'GRASS_VECTOR_LCO' : '', 'input' : '/Users/maples/Downloads/points.shp|layername=points', 'output' : 'TEMPORARY_OUTPUT' }

g.proj -c proj4="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs"
v.in.ogr min_area=0.0001 snap=-1.0 input="/Users/maples/Downloads/points.shp" layer="points" output="vector_5f627ae75a6d96" --overwrite -o
g.region n=4571278.579 s=4532539.7478 e=-13586035.6873 w=-13670428.1918
v.voronoi input=vector_5f627ae75a6d96 output=output0fc09ffb9e94472baedcf2a353550eca --overwrite
v.out.ogr type="auto" input="output0fc09ffb9e94472baedcf2a353550eca" output="/private/var/folders/f3/0prmkq7962795yfpwsmvh2100000gq/T/processing_xxaYqK/a0d0a2d2844c493babe4c52273dc5a59/output.gpkg" format="GPKG" --overwrite
Starting GRASS GIS...
Executing </private/var/folders/f3/0prmkq7962795yfpwsmvh2100000gq/T/processing_xxaYqK/grassdata/grass_batch_job.sh> ...
dyld: Symbol not found: _iconv
Referenced from: /usr/lib/libarchive.2.dylib
Expected in: /Applications/QGIS3.14.app/Contents/Resources/grass7/lib/libiconv.2.dylib
in /usr/lib/libarchive.2.dylib
/private/var/folders/f3/0prmkq7962795yfpwsmvh2100000gq/T/processing_xxaYqK/grassdata/grass_batch_job.sh: line 2: 3039 Abort trap: 6 g.proj -c proj4="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs"
dyld: Symbol not found: _iconv
Referenced from: /usr/lib/libarchive.2.dylib
Expected in: /Applications/QGIS3.14.app/Contents/Resources/grass7/lib/libiconv.2.dylib
in /usr/lib/libarchive.2.dylib
/private/var/folders/f3/0prmkq7962795yfpwsmvh2100000gq/T/processing_xxaYqK/grassdata/grass_batch_job.sh: line 3: 3040 Abort trap: 6 v.in.ogr min_area=0.0001 snap=-1.0 input="/Users/maples/Downloads/points.shp" layer="points" output="vector_5f627ae75a6d96" --overwrite -o
dyld: Symbol not found: _iconv
Referenced from: /usr/lib/libarchive.2.dylib
Expected in: /Applications/QGIS3.14.app/Contents/Resources/grass7/lib/libiconv.2.dylib
in /usr/lib/libarchive.2.dylib
/private/var/folders/f3/0prmkq7962795yfpwsmvh2100000gq/T/processing_xxaYqK/grassdata/grass_batch_job.sh: line 4: 3041 Abort trap: 6 g.region n=4571278.579 s=4532539.7478 e=-13586035.6873 w=-13670428.1918
dyld: Symbol not found: _iconv
Referenced from: /usr/lib/libarchive.2.dylib
Expected in: /Applications/QGIS3.14.app/Contents/Resources/grass7/lib/libiconv.2.dylib
in /usr/lib/libarchive.2.dylib
/private/var/folders/f3/0prmkq7962795yfpwsmvh2100000gq/T/processing_xxaYqK/grassdata/grass_batch_job.sh: line 5: 3042 Abort trap: 6 v.voronoi input=vector_5f627ae75a6d96 output=output0fc09ffb9e94472baedcf2a353550eca --overwrite
dyld: Symbol not found: _iconv
Referenced from: /usr/lib/libarchive.2.dylib
Expected in: /Applications/QGIS3.14.app/Contents/Resources/grass7/lib/libiconv.2.dylib
in /usr/lib/libarchive.2.dylib
/private/var/folders/f3/0prmkq7962795yfpwsmvh2100000gq/T/processing_xxaYqK/grassdata/grass_batch_job.sh: line 6: 3043 Abort trap: 6 v.out.ogr type="auto" input="output0fc09ffb9e94472baedcf2a353550eca" output="/private/var/folders/f3/0prmkq7962795yfpwsmvh2100000gq/T/processing_xxaYqK/a0d0a2d2844c493babe4c52273dc5a59/output.gpkg" format="GPKG" --overwrite
Execution of </private/var/folders/f3/0prmkq7962795yfpwsmvh2100000gq/T/processing_xxaYqK/grassdata/grass_batch_job.sh> finished.
Traceback (most recent call last):
File "/Applications/QGIS3.14.app/Contents/Resources/grass7/bin/_grass76", line 2207, in <module>
main()
File "/Applications/QGIS3.14.app/Contents/Resources/grass7/bin/_grass76", line 2155, in main
clean_all()
File "/Applications/QGIS3.14.app/Contents/Resources/grass7/bin/_grass76", line 1789, in clean_all
gsetup.clean_default_db()
File "/Applications/QGIS3.14.app/Contents/Resources/grass7/etc/python/grass/script/setup.py", line 220, in clean_default_db
conn = gdb.db_connection()
File "/Applications/QGIS3.14.app/Contents/Resources/grass7/etc/python/grass/script/db.py", line 108, in db_connection
nuldev = file(os.devnull, 'w')
NameError: name 'file' is not defined
/Applications/QGIS3.14.app/Contents/Resources/grass7/grass76.sh: line 20: /private/var/folders/f3/0prmkq7962795yfpwsmvh2100000gq/T/processing_xxaYqK/grassdata/temp_location/PERMANENT: is a directory
Execution completed in 1.06 seconds
Results:
{'output': <QgsProcessingOutputLayerDefinition {'sink':TEMPORARY_OUTPUT, 'createOptions': {'fileEncoding': 'System'}}>}

Loading resulting layers
The following layers were not correctly generated.
• /private/var/folders/f3/0prmkq7962795yfpwsmvh2100000gq/T/processing_xxaYqK/a0d0a2d2844c493babe4c52273dc5a59/output.gpkg
You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.`

Grass7 Messages:  

`2020-09-16T13:36:32     INFO    processInputs end. Commands: ['g.proj -c proj4="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs"', 'v.in.ogr min_area=0.0001 snap=-1.0 input="/private/var/folders/f3/0prmkq7962795yfpwsmvh2100000gq/T/processing_xxaYqK/08af800894524bfab7d0246fa9cfa686/input.shp" output="vector_5f627750a89682" --overwrite -o', 'g.region n=4571278.579 s=4532539.7478 e=-13603929.6588 w=-13652534.2203']
2020-09-16T13:36:32     INFO    processCommands end. Commands: ['g.proj -c proj4="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs"', 'v.in.ogr min_area=0.0001 snap=-1.0 input="/private/var/folders/f3/0prmkq7962795yfpwsmvh2100000gq/T/processing_xxaYqK/08af800894524bfab7d0246fa9cfa686/input.shp" output="vector_5f627750a89682" --overwrite -o', 'g.region n=4571278.579 s=4532539.7478 e=-13603929.6588 w=-13652534.2203', 'v.voronoi input=vector_5f627750a89682 output=output0a0d63c243fe4fe7ba108fc071fb92e3 --overwrite']
2020-09-16T13:37:14     INFO    processInputs end. Commands: ['g.proj -c proj4="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs"', 'v.in.ogr min_area=0.0001 snap=-1.0 input="/private/var/folders/f3/0prmkq7962795yfpwsmvh2100000gq/T/processing_xxaYqK/3e6d8b4161c148319a28b77258238e5f/input.shp" output="vector_5f62777a579b03" --overwrite -o', 'g.region n=4571278.579 s=4532539.7478 e=-13603929.6588 w=-13652534.2203']
2020-09-16T13:37:14     INFO    processCommands end. Commands: ['g.proj -c proj4="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs"', 'v.in.ogr min_area=0.0001 snap=-1.0 input="/private/var/folders/f3/0prmkq7962795yfpwsmvh2100000gq/T/processing_xxaYqK/3e6d8b4161c148319a28b77258238e5f/input.shp" output="vector_5f62777a579b03" --overwrite -o', 'g.region n=4571278.579 s=4532539.7478 e=-13603929.6588 w=-13652534.2203', 'v.voronoi input=vector_5f62777a579b03 output=outpute794dfeeeea144df98a90b7a07128ca0 --overwrite']
2020-09-16T13:38:55     INFO    processInputs end. Commands: ['g.proj -c proj4="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs"', 'v.in.ogr min_area=0.0001 snap=-1.0 input="/private/var/folders/f3/0prmkq7962795yfpwsmvh2100000gq/T/processing_xxaYqK/2c92d7fff8934dc0b3e37199fe83a09c/input.shp" output="vector_5f6277dfbe5304" --overwrite -o', 'g.region n=4570531.891981606 s=4534907.978609399 e=-13613607.067557963 w=-13651848.786443522']
2020-09-16T13:38:55     INFO    processCommands end. Commands: ['g.proj -c proj4="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs"', 'v.in.ogr min_area=0.0001 snap=-1.0 input="/private/var/folders/f3/0prmkq7962795yfpwsmvh2100000gq/T/processing_xxaYqK/2c92d7fff8934dc0b3e37199fe83a09c/input.shp" output="vector_5f6277dfbe5304" --overwrite -o', 'g.region n=4570531.891981606 s=4534907.978609399 e=-13613607.067557963 w=-13651848.786443522', 'v.voronoi input=vector_5f6277dfbe5304 output=output9a09588a79b54d9ea768c6f2b689c702 --overwrite']
2020-09-16T13:39:58     INFO    processInputs end. Commands: ['g.proj -c proj4="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs"', 'v.in.ogr min_area=0.0001 snap=-1.0 input="/private/var/folders/f3/0prmkq7962795yfpwsmvh2100000gq/T/processing_xxaYqK/5b575cc50fc849a1bb97003b5f78f42b/input.shp" output="vector_5f62781edb4255" --overwrite -o', 'g.region n=4571278.579 s=4532539.7478 e=-13586035.6873 w=-13670428.1918']
2020-09-16T13:39:58     INFO    processCommands end. Commands: ['g.proj -c proj4="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs"', 'v.in.ogr min_area=0.0001 snap=-1.0 input="/private/var/folders/f3/0prmkq7962795yfpwsmvh2100000gq/T/processing_xxaYqK/5b575cc50fc849a1bb97003b5f78f42b/input.shp" output="vector_5f62781edb4255" --overwrite -o', 'g.region n=4571278.579 s=4532539.7478 e=-13586035.6873 w=-13670428.1918', 'v.voronoi input=vector_5f62781edb4255 output=output03206a43e4b742dbbfd883da361be4bc --overwrite']
2020-09-16T13:51:51     INFO    processInputs end. Commands: ['g.proj -c proj4="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs"', 'v.in.ogr min_area=0.0001 snap=-1.0 input="/Users/maples/Downloads/points.shp" layer="points" output="vector_5f627ae75a6d96" --overwrite -o', 'g.region n=4571278.579 s=4532539.7478 e=-13586035.6873 w=-13670428.1918']
2020-09-16T13:51:51     INFO    processCommands end. Commands: ['g.proj -c proj4="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs"', 'v.in.ogr min_area=0.0001 snap=-1.0 input="/Users/maples/Downloads/points.shp" layer="points" output="vector_5f627ae75a6d96" --overwrite -o', 'g.region n=4571278.579 s=4532539.7478 e=-13586035.6873 w=-13670428.1918', 'v.voronoi input=vector_5f627ae75a6d96 output=output0fc09ffb9e94472baedcf2a353550eca --overwrite']
2020-09-16T13:53:25     INFO    processInputs end. Commands: ['g.proj -c proj4="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs"', 'v.in.ogr min_area=0.0001 snap=-1.0 input="/Users/maples/Downloads/points.shp" layer="points" output="vector_5f627b452c9c37" --overwrite -o', 'g.region n=4571278.579 s=4532539.7478 e=-13586035.6873 w=-13670428.1918']
2020-09-16T13:53:25     INFO    processCommands end. Commands: ['g.proj -c proj4="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs"', 'v.in.ogr min_area=0.0001 snap=-1.0 input="/Users/maples/Downloads/points.shp" layer="points" output="vector_5f627b452c9c37" --overwrite -o', 'g.region n=4571278.579 s=4532539.7478 e=-13586035.6873 w=-13670428.1918', 'v.voronoi input=vector_5f627b452c9c37 output=outpute37f6908fba34e188ad9ccedb42a9b3a --overwrite']`

**Comment by mapninja** [comment]
Just tried the Nightly Build, which doesn't load the GRASS Provider, at all.

**Comment by dkav** [comment]
@PeterPetrik the GRASS installation directory is still not correct - 
<img width="728" alt="Screen Shot 2020-09-16 at 14 39 42" src="https://user-images.githubusercontent.com/3822086/93395712-3aae3900-f82b-11ea-94d4-73f05f88fbf6.png">

When I corrected the GRASS path and tried to run a tool I got the following error - 
<img width="532" alt="Screen Shot 2020-09-16 at 14 55 42" src="https://user-images.githubusercontent.com/3822086/93396830-2b2fef80-f82d-11ea-8cff-cc961e701d0e.png">

Also, this build is unstable. It complained about the Processing plugin and crashed both when it was enabled or disabled.

**Comment by PeterPetrik** [comment]
@dkav the default grass PATH problem is reported in https://github.com/qgis/QGIS/issues/38595, can we discuss it there?

**Comment by PeterPetrik** [comment]
@mapninja until https://github.com/qgis/QGIS/issues/38595 is solved, you need to go to Menu->Settings->Options->Processing(left)->Providers->Grass->set GRASS7 folder to `/Application/QGIS.app/Contents/MacOS/grass78` or where you installation points to

**Comment by PeterPetrik** [comment]
@dkav @mapninja 

The reported issue should be fixed by commit https://github.com/qgis/QGIS-Mac-Packager/commit/218a571f6f268dcc4490ebe1a00068bfe363b2ae.
Can you please re-test if the issue persists with build: https://qgis.org/downloads/macos/nightly2/qgis_nightly2_master_20200917_044804.dmg

Note: Problems with GRASS processing provider in QGIS 3.10 and 3.14 were caused by complicated settings of PATHS, linker paths and other settings in various GRASS and QGIS scripts/binaries (partially coming from homebrew builds). The GRASS (reliable) deployment was one of the drivers for complete refactoring of QGIS dependencies used for MacOS builds
(see https://github.com/qgis/QGIS-Enhancement-Proposals/issues/177). Now we have full control of building and patching GRASS as needed. QGIS 3.16 release will be first using the new system, you can test it in "nighlty2" builds (nightly are still based on "old" homebrew deps and QGIS 3.10 LTR will be released with them). You can grab your nighly build in https://qgis.org/downloads/macos/nightly2/.

**Comment by PeterPetrik** [comment]
screencast of the mentioned build on my laptop: 

![grass_voronoi](https://user-images.githubusercontent.com/804608/93458738-fc735100-f8e0-11ea-83e9-889f415fe6c6.gif)

**Comment by dkav** [comment]
The GRASS plugin, on a clean profile and using the qgis_nightly2_master_20200917_044804.dmg build, still does work without providing the location of the GRASS installation.

 > 2020-09-18T14:27:24     WARNING    GRASS init error : GRASS was not found in 'INVALID/S/qgis-deps-0.5.4/stage/grass78' (GISBASE), provider and plugin will not work.

Below is screencast of the steps I took to enable the GRASS plugin:
![sc](https://user-images.githubusercontent.com/3822086/93659205-bbba2b80-f9f7-11ea-841f-375dfeae5d43.gif)

Once enabled, I tested three GRASS modules/commands via the GRASS Tools panel. One failed, one worked and one crashed QGIS.

Also, @PeterPetrik your screencast shows you using GRASS via the Processing plugin, which I am unable to replicate as the Processing plugin is still causing QGIS to crash so I cannot replicate your steps.

**Comment by PeterPetrik** [comment]
@dkav thanks for testing. The location of the GRASS should be already on nighlty2 builds from the weekend, please retest and if that does not work report to issue https://github.com/qgis/QGIS/issues/38595 that is about that problem/ 

For the QGIS crash, please create a new issue. Also for failed algorithm, create a separate issue. Thanks

**Comment by dkav** [comment]
> @dkav thanks for testing. The location of the GRASS should be already on nighlty2 builds from the weekend, please retest and if that does not work report to issue #38595 that is about that problem/
> 
> For the QGIS crash, please create a new issue. Also for failed algorithm, create a separate issue. Thanks

See https://github.com/qgis/QGIS/issues/38595#issuecomment-696910832 for retest and #38960 for crash issue. GRASS algorithms seem to be working (I chose randomly last time so I am not sure if I reran the same tools). I did notice an issue with the GRASS console - see #38961.
