### ISSUE TITLE
Qgis crash when composer try to export PDF 600dpi as a raster

### ISSUE THREAD

**Issue by yodaanneaux** [qgis/QGIS#32514]
1. Go to Composer
2. Click on "Print as raster", then "export as PDF"

## User Feedback

exporting a pdf with the checked option : "Print as raster"
two times tested with same results

## Report Details

**Crash ID**: [2794cfcc8730893780453cc5a83788c02d06174d]('https://github.com/qgis/QGIS/search?q=2794cfcc8730893780453cc5a83788c02d06174d&type=Issues')

**Stack Trace**
<pre>
memcpy_repmovs memcpy.asm:115
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QRasterPaintEngine::rasterBuffer :
QRasterPaintEngine::rasterBuffer :
QRasterPaintEngine::fill :
QPaintEngineEx::draw :
QPaintEngineEx::drawPath :
QgsFillSymbolLayer::_renderPolygon qgssymbollayer.cpp:740
QgsSimpleFillSymbolLayer::renderPolygon qgsfillsymbollayer.cpp:286
QgsFillSymbol::renderPolygonUsingLayer qgssymbol.cpp:2039
QgsFillSymbol::renderPolygon qgssymbol.cpp:1994
QgsLayoutItemPage::draw qgslayoutitempage.cpp:286
QgsLayoutItem::paint qgslayoutitem.cpp:411
QGraphicsScene::dragMoveEvent :
QGraphicsItem::dragMoveEvent :
QGraphicsEffectSource::draw :
QgsLayoutEffect::draw qgslayouteffect.cpp:33
QGraphicsScene::drawItems :
QGraphicsScene::drawItems :
QGraphicsScene::render :
QgsLayoutExporter::renderRegion qgslayoutexporter.cpp:261
QgsLayoutExporter::renderRegionToImage qgslayoutexporter.cpp:300
QgsLayoutExporter::renderPageToImage qgslayoutexporter.cpp:207
QgsLayoutExporter::printPrivate qgslayoutexporter.cpp:1228
QgsLayoutExporter::exportToPdf qgslayoutexporter.cpp:663
QgsLayoutDesignerDialog::exportToPdf qgslayoutdesignerdialog.cpp:2183
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1583
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.0-A Coruña
QGIS code revision: 6c816b4204
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by nyalldawson** [comment]
This is an upstream issue, fixed in qt 5.13
