### ISSUE TITLE
Critical error messages in Nightly builds

### ISSUE THREAD

**Issue by nicolasmcfadden** [qgis/QGIS#32515]
**Describe the bug**
Error messages for Nightly builds: see screenshot below

**How to Reproduce**
Install Nightly build and start QGIS

![image](https://user-images.githubusercontent.com/27243743/67851050-e2ceec80-fb09-11e9-88ae-c7a26f01a202.png)
**QGIS and OS versions**

Had same behaviour with QGIS 3.8 and 3.9: QGIS 3.8 main installation (release versions) had no problems but the 3.8 nightly and the 3.9 had these error messages.
The problem is the same with 3.10 and 3.11. 3.10 "Express installe" works without erros but the 3.10 nightly and 3.11 have the error messages.

**Additional context**

**Comment by jef-n** [comment]
These messages probably have been there for long - just shown more prominent in debug builds (since a4dea7d8b4)

**Comment by nyalldawson** [comment]
As @jef-n has said, these are ONLY shown in the nightly builds as a way of getting developers to see and investigate them. Some are harmless, but some give hints to potential issues in the code.

Just ignore them if they don't mean anything to you :wink:
