### ISSUE TITLE
Multi-layer export from GML

### ISSUE THREAD

**Issue by Ellebjerg** [qgis/QGIS#32510]
I have just had to export 50 layers from a GML to a geopackage. It would have been nice to be able to export all layers in one go instead of one at a time. This improvement would be nice not only to a geopackage but also to other formats, for instance to separate shape-files in a common folder.

Best regards
Lars Ellebjerg

**Comment by gioman** [comment]
@Ellebjerg have you tried Processing "package layers"?

**Comment by Ellebjerg** [comment]
No, I missed that one. I tried googling the subject, but since this did not pop up, I have clearly used the wrong search terms.

It would be nice to have the functionality directly in the layer export, but for now this is great.

Thanks a lot for your help!
