### ISSUE TITLE
Adding tables (and views) from PostGIS database do not record Postgres User

### ISSUE THREAD

**Issue by immoblecher** [qgis/QGIS#32526]
**Describe the bug**

When adding tables from a PostGIS database with a connection with plain text username and password, which are supposed to be saved in the project file, the user name is not saved in the project. This is not really a problem for Desktop, but QGIS Server returns an invalid layer, as the Server cannot make a connection with the user name and password.

**How to Reproduce**

1. Go to Layer Browser
2. Double-Click on any PostGIS table or drag into the map canvas
3. Hover with mouse over added layer (or just table without geometry)
4. Watch connection settings with database, host, port etc. but no "user='blahblah'"

This was not a problem before 3.10.

**QGIS and OS versions**

QGIS version | 3.10.0-A Coruña | QGIS code revision | 6c816b4204
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.6.2-CAPI-1.10.2 4d2925d6
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 10.10 (Ubuntu 10.10-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Ubuntu 18.04.3 LTS

**Additional context**

A workaround is to edit the project file with a text editor and add the user. (Careful!). I fortunately had a few tables added with earlier QGIS versions, which I just duplicate and change the SQL.

**Comment by gioman** [comment]
> When adding tables from a PostGIS database with a connection with plain text username and password, which are supposed to be saved in the project file, the user name is not saved in the project

@immoblecher I just tested on 3.10 on Windows and cannot confirm.

**Comment by immoblecher** [comment]
Thanks, 

So this must be something in the Linux version? Not using Windows at the moment so can't confirm. 

⁣--
Immo F. Blecher 

Street: 36 Saffraan Ave., Die Boord, Stellenbosch, 7613, South Africa 

Postal: PO Box 74, Lynedoch, 7603, South Africa 

Cell: +27 83 272 6791 | Fax: +27 86 736 3302 

Email:  immo@blecher.co.za  | immob19@gmail.com  | immob@mymtnmail.co.za 

Internet:  https://www.blecher.co.za / 

Please consider your environmental responsibility. Before printing this e-mail message, ask yourself whether you really need a hard copy.

Get BlueMail for Android ​

**Comment by gioman** [comment]
> So this must be something in the Linux version? Not using Windows at the moment so can't confirm.

I also can't confirm on Ubuntu.

**Comment by immoblecher** [comment]
Will take a screen shot tomorrow and maybe logs etc. Maybe it's also a project file that came along over a couple of versions and has got some "baggage". Not sure what's happening. 

⁣--
Immo F. Blecher
Street: 36 Saffraan Ave., Die Boord, Stellenbosch, 7613, South Africa
Postal: PO Box 74, Lynedoch, 7603, South Africa
Cell: +27 83 272 6791 | Fax: +27 86 736 3302

Email: immo@blecher.co.za | immob19@gmail.com | immob@mymtnmail.co.za
Internet: https://www.blecher.co.za/

Please consider your environmental responsibility. Before printing this e-mail message, ask yourself whether you really need a hard copy.

Get BlueMail for Android ​

**Comment by immoblecher** [comment]
Here is a screenshot of the hint box which shows the connection details, but not the user='blahblah". So the user name is not saved in the project file and qgis server will give an error message that the layer is not valid. I also added the project file.
![IMG_20191031_080757](https://user-images.githubusercontent.com/25684536/67923542-d48ada00-fbb6-11e9-8d46-c5d991966d02.jpg)
[TestProject.qgs.zip](https://github.com/qgis/QGIS/files/3792401/TestProject.qgs.zip)

**Comment by gioman** [comment]
> Here is a screenshot of the hint box which shows the connection details, but not the user='blahblah".

@immoblecher have you checked the "store" checkbox beside the username when you set up the connection?

![Screenshot_20191031_094057](https://user-images.githubusercontent.com/1951107/67935843-985d7680-fbc2-11e9-92bf-24318a8ee391.png)

**Comment by immoblecher** [comment]
Yes, checked! It works for QGIS Desktop, but not when using the Project for a QGIS Server instance.
So what I do to resolve this are the following steps:
1.) I add the table or view from a Data Source where the user name and password are stored in plain text in the project. (No questions asked when opening the project)
2.) Then I close the project and edit the project file with a text editor, specifically where it says:
 <datasource>dbname='western-cape' host=192.168.1.2 port=5432 **user='qgis'** sslmode=disable key='site_id_nr' checkPrimaryKeyUnicity='1' table="(SELECT * FROM \"qgis_view_ec\" etc..... where I add the **user='qgis'**
3.) Then I reopen the project in QGIS Desktop and now it will ask for the password, which I enter.
4.) Then I save the project and when reopening it does not ask for the password any longer. But then the layer is valid for QGIS Server.

**Comment by gioman** [comment]
> Then I reopen the project in QGIS Desktop and now it will ask for the password, which I enter.

I just tested here, and it clearly saves (in plain text) both username and password in the project file. I'm on 3.10 on Ubuntu.

**Comment by immoblecher** [comment]
That is very weird. Just look into the TestProject.qgs I posted this morning. It's not there! Maybe a difference in QGIS installations? I install from the normal Debian/Ubuntu repository, not the UbuntuGIS.

**Comment by gioman** [comment]
> I install from the normal Debian/Ubuntu repository

me too.

**Comment by immoblecher** [comment]
Or a way the PostGIS user is set up? I have created the user 'qgis' with read-only permissions, which the QGIS Server then uses to open the layers and served to qwc2.
And: even if I add the user='qgis' to the project the password is not saved in the project file at all.

**Comment by Gustry** [comment]
> > Here is a screenshot of the hint box which shows the connection details, but not the user='blahblah".
> 
> @immoblecher have you checked the "store" checkbox beside the username when you set up the connection?
> 
> ![Screenshot_20191031_094057](https://user-images.githubusercontent.com/1951107/67935843-985d7680-fbc2-11e9-92bf-24318a8ee391.png)

@immoblecher Was it checked before?
I guess it works only for newly added layers.

**Comment by immoblecher** [comment]
Yes, I always store the un and pw when creating the connection.

**Comment by immoblecher** [comment]
OK, I have nothing better to do, so playing around with some settings:
It has something to do with the read-only user: If I don't check the boxes then the connection opens and I can see all layers. If I then go back and store the password in plain text (check the boxes) then the connection does not work and under public it shows 'Failed to get layers'. But if I test the connection it is successful. I think I read something about this in another bug report here.

**Comment by immoblecher** [comment]
But in DB Manager, and only in DB Manager, it can see all layers and rightly so also shows that it is a read-only user. This makes no sense. The other two methods of opening PostGIS tables should also work.

**Comment by gioman** [comment]
> The other two methods of opening PostGIS tables should also work.

I think that

you have some type of local issues

or

you found a bug, but this is not clear (at least to me) how to replicate it. If you find the problem please add the detailed steps to replicate (the ones already described here are evidently not enough).

**Comment by gioman** [comment]
Closing for lack of feedback and also as is not possible to clearly understand what the local issue is. Please reopen if necessary.
