### ISSUE TITLE
Export from gml to dxf skips layer

### ISSUE THREAD

**Issue by Gert-JanMaarten** [qgis/QGIS#32520]
I use QGIS 3.6.3-Noosa on a Windows10 system for reading GML-files en export them to DXF (DWG)

Importing GML-layers works great!
Exporting the GGZ-project to DXF (multilayer) also works great! 
Except for one thing;

**One of the layers stays empty when exporting to DXF!**

To investigate what goes wrong I've tried to;
- export this single layer but every time it results in an empty DXF!
- I've tried different outlines and fillings but the DXF-export stays empty
- exporting the one layer to PDF works fine!!

How do I export the 'bgt_pand'-layer correctly to a DXF?

I've attached my GGZ, GML, PDF and DXF 
[GJM_GMLlayer-t-DXFfail.zip](https://github.com/qgis/QGIS/files/3789226/GJM_GMLlayer-t-DXFfail.zip)
[GJM_GMLlayer-to-DXFfail.pdf](https://github.com/qgis/QGIS/files/3789229/GJM_GMLlayer-to-DXFfail.pdf)

**Comment by gioman** [comment]
> I use QGIS 3.6.3-Noosa

Hi @Gert-JanMaarten you must test also the latest 3.4 or 3.10, because 3.6 is obsolete.

**Comment by roya0045** [comment]
These elements were worked on recently by two core devs. Though the changes might take some time to get into the next official release, I would suggest trying out the nightly build (if it works) next week.

**Comment by gioman** [comment]
@Gert-JanMaarten please leave further feedback.

**Comment by gioman** [comment]
I tested "export project to DXF" and the results seems ok to me. Reopen if necessary.
