### ISSUE TITLE
MultiLineString from OpenFileGDB Disappears on Zoom

### ISSUE THREAD

**Issue by markegge** [qgis/QGIS#32534]
**Describe the bug**

When a FileGeodatabase contains a multi-linestring, if the entire multi-linestring cannot be displayed within the current view extent, none of the multi-linestring displays on screen. 

**How to Reproduce**

[MultiStringRoads.zip](https://github.com/qgis/QGIS/files/3790837/MultiStringRoads.zip)

1. Extract and add the attached "MultiStringRoads" FileGeodatabase to QGIS (Add Vector Layer --> Source Type: Directory --> Source Type: OpenFileGDB --> Add)
2. Right click on the newly added layer and choose "Zoom to Layer." Observe the two correctly displayed multi-linestrings.
3. Zoom in. Observe the multi-linestrings disappear.

<img width="840" alt="screenshot_1" src="https://user-images.githubusercontent.com/5603735/67892757-02badc00-fb1b-11e9-96ae-f20df4d00534.png">

<img width="840" alt="screenshot_2" src="https://user-images.githubusercontent.com/5603735/67892756-02badc00-fb1b-11e9-83a6-bbfa2961ca6d.png">

**QGIS and OS versions**

* QGIS version 3.4.11-Madeira
* macOS 10.14.6

**Additional context**

I'm not sure if this issue is FileGeodatabase specific, but I do *not* have this issue if I convert the GDB to a GeoPackage with the "Force Multi" option.

**Comment by Pedro-Murteira** [comment]
@markegge I'm not being able to replicate this issue, are you still having problems with this? (tested on QGIS 3.16.15 and 3.22.2.)

**Comment by LisaSSL** [comment]
We have the same issue with 3.22.7-Białowieża - also with MultiStringZM and MultiStringZ.

**Comment by jguelat** [comment]
I'm having a similar problem with a MultiPolygonZ layer in a file geodatabase using the OpenFileGDB driver. I have the feeling this is caused by a corrupted index.

QGIS 3.22.12 (GDAL 3.6.0) on Windows 10

**Comment by rouault** [comment]
I can't reproduce any issue with GDAL and QGIS master on the [MultiStringRoads.zip](https://github.com/qgis/QGIS/files/3790837/MultiStringRoads.zip) file
@jguelat Can you attach a dataset reproducing the issue you have ?

**Comment by jguelat** [comment]
Thanks a lot for having a look at it. The problematic dataset is part of the official swiss topographic landscape model (swissTLM3D) which can be freely downloaded using the following URL: https://data.geo.admin.ch/ch.swisstopo.swisstlm3d/swisstlm3d_2022-03/swisstlm3d_2022-03_2056_5728.gdb.zip

I'm having troubles with the layer "TLM_NUTZUNGSAREAL" contained in the file geodatabase. I tried with QGIS 3.22 and 3.28, both using GDAL 3.6.0. To be fair I also tried with an "old" version of ArcMap and experienced the same problem.

If I export the problematic layer as a GeoPackage, all is fine with the exported dataset.

**Comment by rouault** [comment]
@jguelat
I concur the .spx file is broken. The Esri FileGDB SDK is also confused by it. I've added in GDAL in https://github.com/OSGeo/gdal/pull/7137 a heuristic to detect that situation and disable the use of the .spx file. This should be reported to the data producer so they regenerate the .spx file.

**Comment by jguelat** [comment]
Thanks a lot! I will inform them.

**Comment by rouault** [comment]
By the way, the attribute indices on GUID fields seem to have the same kind of corruption. Smells like a bug in Esri software...
