### ISSUE TITLE
dxf export qgis 3.10

### ISSUE THREAD

**Issue by ro1990Uy** [qgis/QGIS#32548]
in version 3.10, when i export a dxf file, the autocad 2017 cant open the file, it request a "enter to continue". and nothing shows.

**Comment by gioman** [comment]
@ro1990Uy did the same process worked in a previous release?

**Comment by jef-n** [comment]
Likely already fixed with #32548

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.

**Comment by SergeyChern** [comment]
I know 2 critical issues leads to file open error with Autodesk TrueViewer. QGIS version is 3.4.14.
1. CR LF symbols in text labels. Kind of fixed in 3.10? Didn't check it.
2. Transparensy group code 440.

**Comment by gioman** [comment]
> I know 2 critical issues leads to file open error with Autodesk TrueViewer. QGIS version is 3.4.14.
> 
>     1. CR LF symbols in text labels. Kind of fixed in 3.10? Didn't check it.
> 
>     2. Transparensy group code 440.

@SergeyChern please file a new ticket, if this issues are not already reported.
