### ISSUE TITLE
QGIS crash after startup - Win10

### ISSUE THREAD

**Issue by hugonbg** [qgis/QGIS#32557]
**Describe the bug**

The QGIS crash right after starting.

**How to Reproduce**

Start QGIS 3.11 

**QGIS and OS versions**

QGIS Info
QGIS Version: 3.11.0-Master
QGIS code revision: 6e03a97f63
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.0dev
Running against GDAL: 3.1.0dev

**Additional context**

## User Feedback

aaa

## Report Details

**Crash ID**: [5eca77f15c8e3b0b2ba93bfb4b5d5b41db0e1192]('https://github.com/qgis/QGIS/search?q=5eca77f15c8e3b0b2ba93bfb4b5d5b41db0e1192&type=Issues')

**Stack Trace**
<pre>
QBasicMutex::unlockInternal :
QgsTask::~QgsTask qgstaskmanager.cpp:45
QgsNetworkContentFetcherTask::~QgsNetworkContentFetcherTask qgsnetworkcontentfetchertask.cpp:38
QgsNetworkContentFetcherTask::`vector deleting destructor' :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QCoreApplication::processEvents :
QgisApp::QgisApp qgisapp.cpp:1311
main main.cpp:1344
WinMain mainwin.cpp:170
__scrt_common_main_seh exe_common.inl:253
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.11.0-Master
QGIS code revision: 6e03a97f63
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.0dev
Running against GDAL: 3.1.0dev

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

------------------------------------------------------
DebugView

## User Feedback

aaa

## Report Details

**Crash ID**: [5eca77f15c8e3b0b2ba93bfb4b5d5b41db0e1192]('https://github.com/qgis/QGIS/search?q=5eca77f15c8e3b0b2ba93bfb4b5d5b41db0e1192&type=Issues')

**Stack Trace**
<pre>
QBasicMutex::unlockInternal :
QgsTask::~QgsTask qgstaskmanager.cpp:45
QgsNetworkContentFetcherTask::~QgsNetworkContentFetcherTask qgsnetworkcontentfetchertask.cpp:38
QgsNetworkContentFetcherTask::`vector deleting destructor' :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QCoreApplication::processEvents :
QgisApp::QgisApp qgisapp.cpp:1311
main main.cpp:1344
WinMain mainwin.cpp:170
__scrt_common_main_seh exe_common.inl:253
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.11.0-Master
QGIS code revision: 6e03a97f63
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.0dev
Running against GDAL: 3.1.0dev

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

-------------------------------------------------------
[qgis.LOG](https://github.com/qgis/QGIS/files/3795332/qgis.LOG)

**Comment by gioman** [comment]
Duplicate https://github.com/qgis/QGIS/issues/32545 ?

**Comment by roya0045** [comment]
> Duplicate #32545 ?

Yep.
