### ISSUE TITLE
Bad Allocation Error

### ISSUE THREAD

**Issue by aflaurio** [qgis/QGIS#32564]
QGIS A Cortuna 3.10
OS windows 10

Opening a project created QGIS 3.8.3 will result a Bad allocation error.
It will open but the Print Composer layout is gone.

**Comment by gioman** [comment]
@aflaurio can you attach the project?

**Comment by andregeorisk** [comment]
I have a similar problem.
When I try to load a specific layout model (created in 3.8.3), even in a new 3.10.0 project, my computer just runs out of memory and gets useless, demanding a windows hard reset.
Opening a project created in 3.8.3 that has already this same layout loaded, is possible to open the Print-Composer and change some configurations, but it gets the same issue when the projection is changed.
Follows the layout template in question

[localizacao_geral_qgis3.zip](https://github.com/qgis/QGIS/files/3816405/localizacao_geral_qgis3.zip)

**Comment by nyalldawson** [comment]
I can't reproduce with the attached qpt alone. Can you share the whole project?

**Comment by strozzascotte** [comment]
I have the same problem. Opening a 3.8.2 project with QGIS 3.10.0 results in std::bad_alloc error.
Also the print layouts are not imported in 3.10.0.
I noticed that QGIS 3.10.0 uses an enormous amount of memory (up to 8 GB) when opening the project and before throwing the error, while 3.8.2 don't.

Observed this in MacOS 10.14 and 10.15.

**Comment by roya0045** [comment]
Can someone share the full stack trace at least?

**Comment by strozzascotte** [comment]
> Can someone share the full stack trace at least?
How can I get the full stack trace on MacOS?

Here's a [screen recording](https://drive.google.com/open?id=1-JamY06tjgCY7QG6l9OggVN0lKhFUvZE) while opening the same project in QGIS 3.8.2 and 3.10. I hope it helps.

**Comment by aflaurio** [comment]
no more bad allocation error after upgrading to a new version of QGIS 3.10
but the customizing projection is not working and deletes the +towgs84 parameters
<img width="642" alt="cust_proj" src="https://user-images.githubusercontent.com/7996232/70400255-ed639680-1a64-11ea-874e-a019b0a4ae2a.png">

**Comment by gioman** [comment]
>  but the customizing projection is not working and deletes the +towgs84 parameters

this is a separate issue. Closing this one?

**Comment by strozzascotte** [comment]
> no more bad allocation error after upgrading to a new version of QGIS 3.10

There are no newer version of QGIS 3.10 for MacOS available for me to try, but I can confirm that in QGIS 3.11 nightly build code revision 60c401a8d2 the bad allocation error is gone AND print layouts are correctly loaded.
