### ISSUE TITLE
Qgis crashed

### ISSUE THREAD

**Issue by abocianowski** [qgis/QGIS#32567]
## User Feedback

Its happend when I use run button in plugin 'https://plugins.qgis.org/plugins/ObliczWysokosc/'

## Report Details

*Crash ID*: 936de020e6f56a9b089632184439e56b47dcdd39

*Stack Trace*
<pre>
QgsDefaultVectorLayerLegend::createLayerTreeModelLegendNodes :
QgsLayerTreeModel::addLegendToLayer :
QgsLayerTreeModel::connectToLayer :
QgsLayerTreeModel::nodeAddedChildren :
QMetaCallEvent::placeMetaCall :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.8.0-Zanzibar
QGIS code revision: 11aff65f10
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by nyalldawson** [comment]
Please file this bug with the plugin authors, not the qgis project
