### ISSUE TITLE
QGIS crash on exit when OpenCL acceleration enabled

### ISSUE THREAD

**Issue by Minichaz** [qgis/QGIS#32563]
## User Feedback

After enabling OpenCL acceleration QGIS produces this crash after exit.

## Report Details

**Crash ID**: [e5434d02bb34af06cd725310bf82b3a13eaf22bb]('https://github.com/qgis/QGIS/search?q=e5434d02bb34af06cd725310bf82b3a13eaf22bb&type=Issues')

**Stack Trace**
<pre>
RtlFreeHeap :
clGetExtensionFunctionAddress :
clGetExtensionFunctionAddress :
clGetExtensionFunctionAddress :
clGetExtensionFunctionAddress :
clGetExtensionFunctionAddress :
clGetExtensionFunctionAddress :
clGetExtensionFunctionAddress :
<lambda_f03950bc5685219e0bcd2087efbe011e>::operator() :
__crt_seh_guarded_call<int>::operator()<<lambda_7777bce6b2f8c936911f934f8298dc43>,<lambda_f03950bc5685219e0bcd2087efbe011e> &,<lambda_3883c3dff614d5e0c5f61bb1ac94921c> > :
execute_onexit_table :
dllmain_crt_process_detach dll_dllmain.cpp:109
dllmain_dispatch dll_dllmain.cpp:207
LdrpCallInitRoutine :
LdrShutdownProcess :
RtlExitUserProcess :
ExitProcessImplementation :
exit_or_terminate_process :
common_exit :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.0-A Coruña
QGIS code revision: 6c816b4204
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by elpaso** [comment]
I'm afraid there is not much we can do, it looks like a bug in the underlying OpenCL library.
