### ISSUE TITLE
warn if there are "temporary" raster files on project/app close

### ISSUE THREAD

**Issue by sanzoghenzo** [qgis/QGIS#32582]
**Describe the bug**

Raster layers computed by Processing algorithms don't have the "memory" icon at the right of the layer item in the layers panel, and there's no warning about losing them on QGIS exit.

**How to Reproduce**

- add a raster layer;
- use a processing algorithm (in my example I used clip) - no "memory" icon at the right of the layer:

    ![Schermata da 2019-11-02 09-59-56](https://user-images.githubusercontent.com/977953/68068734-89103180-fd58-11e9-8af0-20c2fdfd1fc5.png)

- Close QGIS - the program doesn't warn about temporary layers that will get lost;
- Reopen QGIS and the project - the program complains about missing layers:

    ![Schermata da 2019-11-02 10-01-09](https://user-images.githubusercontent.com/977953/68068743-9decc500-fd58-11e9-8f6d-7c3266dc7617.png)

**QGIS and OS versions**

Versione di QGIS | 3.8.3-Zanzibar | branch codice QGIS | Release 3.8
-- | -- | -- | --
Compilato con Qt | 5.13.1 | Esecuzione con Qt | 5.13.1
Compilato con GDAL/OGR | 3.0.1 | Esecuzione con GDAL/OGR | 3.0.1
Compilato con GEOS | 3.7.2-CAPI-1.11.2 | Esecuzione con GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Versione client PostgreSQL | 11.5 | Versione SpatiaLite | 4.3.0a
Versione QWT | 6.1.4 | Versione QScintilla2 | 2.11.2
Compiled against PROJ | 6.2.0 | Running against PROJ | Rel. 6.2.0, September 1st, 2019
OS Version | Manjaro Linux |   |  

I (and my colleagues) also experienced this on 3.8.2 and 3.8.3 on Windows.

**Comment by alexbruy** [comment]
These layers are not memory layers, they are normal, file-based rasters, and should not have such icon.

**Comment by sanzoghenzo** [comment]
It makes sense, but something has to be done to handle rasters in temporary directories.

- use a icon (something other than the memory icon) to signal that they are in a temp dir;
- provide a shortcut to permanently "save" the layer (that is, moving the layer in a specified directory);
- warn if there are "temporary" raster files on project/app close.

**Comment by alexbruy** [comment]
> * provide a shortcut to permanently "save" the layer (that is, moving the layer in a specified directory);

You already have such option. Just select desired location before running algorithm

> * warn if there are "temporary" raster files on project/app close.

Docs clearly states that if no file path specified then Processing created rasters in the temporary directory.

I don't think this is a bug. It is more like a feature request.

**Comment by sanzoghenzo** [comment]
Ok, it's not a bug, but to my eyes it's a UX/usability flaw.

- in case of trials with various options, specifying the path every time and then having to delete all the unneeded files is tedious (usually I overwrite files, but some of my colleagues are used to make multiple files for every test they do);
- if there's a bunch of rasters, without the option to quickly detect what are the rasters that need to be made permanent, one might overlook them and lose hours of work, or has to lose time to go through all the layers.
- I agree that one should read the docs, but the behavior is not consistent from a user perspective: memory or tempfile, if someone is working with temporary data, he/she expects a warning for both kind of layers.

**Comment by baswein** [comment]
I agree and I really like the warning and the ability to "make permanent" temporary memory layers. Layers disappearing after close is one of the first frustrations my students express with QGIS this behavior is very different than the behavior they are used to in software. I would expand this feature request to include the warning and make permanent feature for all temporary layers regardless of type (vector and raster).
