### ISSUE TITLE
Wrong layer name after processing procedures

### ISSUE THREAD

**Issue by ewirth** [qgis/QGIS#32591]
In older QGIS versions (2.x), if I saved a layer to a file (Save to file) and I gave a name to that e.g. "airports", by running the algorithm (Add saved layer to project - option ticked) the created and loaded  layer's name was the same like the given filename. 

In newer versions this behavior disappeared, the resulted layer's name will be "Clipped", "Added geom info", "Intersected", instead of the given one.

I suppose the old solution was better. 
Please up vote this issue, if you feel the same.

**Comment by roya0045** [comment]
That's not a bug, the only improvement that I see would be to combine the original name and the procedure that was applied. But if badly implemented you would have a name that keep growing, I assume this is why it was never implemented.

**Comment by ewirth** [comment]
If the user creates memory layers, I think that the naming logic is fine (Clipped, Intersected ...). 

But in the case when the user would like to Save the layer to file, and gives a name for that, then the layer's name should be stem from the given filename.

I set it as a bug, since it worked well in previous versions like QGIS Wien.

**Comment by Gustry** [comment]
@ewirth It's a setting: `Settings`, `Options`, `Processing`, `Use filename as layer name`.

**Comment by ewirth** [comment]
@Gustry Ohh, thank you so much :)

**Comment by nyalldawson** [comment]
We need to revisit the default value of this setting. It's universally reviled....
