### ISSUE TITLE
grass plugin doesn't work on qgis 3.8 (mac)

### ISSUE THREAD

**Issue by hatsepsutana** [qgis/QGIS#32599]
It's been a few months that i started using Qgis and the need for the GRASS plugin came up in order to work with raster data.

when i try to open a new mapset it doesnt allow me!
<img width="1055" alt="Screenshot 2019-11-03 at 12 27 31" src="https://user-images.githubusercontent.com/57315603/68083757-6dc72400-fe35-11e9-8009-783a981605ef.png">

the problem as it seems is that the path is not correct or the installation doesnt exist?
<img width="520" alt="Screenshot 2019-11-03 at 12 27 40" src="https://user-images.githubusercontent.com/57315603/68083773-a0711c80-fe35-11e9-86cd-bf0cb58790eb.png">

I tried different pathways assigning it to where i found the word grass on a folder in the contents of the app but nothing seems to be working!

<img width="611" alt="Screenshot 2019-11-03 at 12 28 00" src="https://user-images.githubusercontent.com/57315603/68083797-e332f480-fe35-11e9-92c6-6ef9f108b182.png">

I even installed the latest stable grass software in order to create a path for qgis but it doesn't work . 
 
I would really like some help please!!

**Comment by roya0045** [comment]
see #32584, simply use the algs in processing instead.

**Comment by gioman** [comment]
Closing as duplicate as there are several other tickets on this matter.
