### ISSUE TITLE
Qgis 3.10.0-6 crashes at start

### ISSUE THREAD

**Issue by nCVJTK** [qgis/QGIS#32603]
## User Feedback

Qgis rel-dev version 3.10.0-6 crashes upon starting the application. Installed via osgeo4w-setup-x86_64 installer. The 3.10.0 version installed via the same installer successfully starts. I have tried deleting every possible file from previous installations (OSGeo4W64 folder, Appdata folder, registry values) but nothing helped. The same problems exist with 3.11.0-6 dev version (I can't seem to start any version compiled against new GDAL for some reason). No plugins installed whatsoever. 

## Report Details

**Crash ID**: [5eca77f15c8e3b0b2ba93bfb4b5d5b41db0e1192]('https://github.com/qgis/QGIS/search?q=5eca77f15c8e3b0b2ba93bfb4b5d5b41db0e1192&type=Issues')

**Stack Trace**
<pre>
QBasicMutex::unlockInternal :
QgsTask::~QgsTask qgstaskmanager.cpp:45
QgsNetworkContentFetcherTask::~QgsNetworkContentFetcherTask qgsnetworkcontentfetchertask.cpp:38
QgsNetworkContentFetcherTask::`vector deleting destructor' :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QCoreApplication::processEvents :
QgisApp::QgisApp qgisapp.cpp:1202
main main.cpp:1344
WinMain mainwin.cpp:170
__scrt_common_main_seh exe_common.inl:253
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.0-A Coruna
QGIS code revision: 7769983896
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.0dev
Running against GDAL: 3.1.0dev

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by Gustry** [comment]
You should check the crash ID, it's a duplicate https://github.com/qgis/QGIS/search?q=5eca77f15c8e3b0b2ba93bfb4b5d5b41db0e1192&type=Issues

https://github.com/qgis/QGIS/issues/32592
