### ISSUE TITLE
dxf export

### ISSUE THREAD

**Issue by tsterop** [qgis/QGIS#32604]
**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

when i am exporting qpx files( with wptpoints) to dxf, always missing 2 points.!

**Comment by nyalldawson** [comment]
Please provide detail - this report has no content!

**Comment by tsterop** [comment]
when i am exporting qpx files( with wptpoints) to dxf, always missing 2  points.!

**Comment by nyalldawson** [comment]
Can you provide a sample test data? There still isn't enough here to meaningfully debug.

**Comment by tsterop** [comment]
![qgis_points](https://user-images.githubusercontent.com/57331286/68092628-e78efa00-fe95-11e9-9863-fce1be5d6a61.png)
![dxf_points](https://user-images.githubusercontent.com/57331286/68092663-1f963d00-fe96-11e9-9281-d4ae865fe51d.png)

**Comment by tsterop** [comment]
[dxf_export.zip](https://github.com/qgis/QGIS/files/3802196/dxf_export.zip)

**Comment by tsterop** [comment]
[export_3_gps.pdf](https://github.com/qgis/QGIS/files/3802206/export_3_gps.pdf)
[dxf_exporting.pdf](https://github.com/qgis/QGIS/files/3802208/dxf_exporting.pdf)

**Comment by tsterop** [comment]
with
QGIS version
2.14.10-Essen
issue does not exist, gpx points and dxf points are the same.

**Comment by tsterop** [comment]
with qgis 2.14 there is no issue

**Comment by m-kuhn** [comment]
> dxf_export.zip

Can you add the gpx file as well?

**Comment by tsterop** [comment]
with all of this files qgis do the same (2.14.10 works fine)
[kanabia2_steno_makri.zip](https://github.com/qgis/QGIS/files/3802444/kanabia2_steno_makri.zip)

**Comment by tsterop** [comment]
[kanabia2_steno_makri.zip](https://github.com/qgis/QGIS/files/3802446/kanabia2_steno_makri.zip)

with this type of file new versions og qgis do the same.!

**Comment by gioman** [comment]
> with all of this files qgis do the same (2.14.10 works fine)

tried your gpx on QGIS 3.10, export > save features as > dxf

8 points in, 8 points out.

**Comment by tsterop** [comment]
[qgis_issue.zip](https://github.com/qgis/QGIS/files/3803546/qgis_issue.zip)
No in my setup
(acer aspire i3, win 10, desktop qgis3.10 and desktop qgis2.14,)
 qgis3.10 8 point in 6 point out,!!!
 ggis2.14 8 point in 8 point out (works fine)!!!

**Comment by tsterop** [comment]
in my QGIS 3.10
There is not "export>save features as>dxf"
,  but
project>import/export>export project to dxf

**Comment by tsterop** [comment]
in my QGIS 3.10
i wasnt using 
"export>save features as>dxf"
where i checked it and it works fine
, but
project>import/export>export project to dxf
that does not working 8 p in 6 p out

**Comment by gioman** [comment]
> where i checked it and it works fine
> , but
> project>import/export>export project to dxf
> that does not working 8 p in 6 p out

just tested here on 3.10/Linux, 8 in 8 out.

**Comment by tsterop** [comment]
> > where i checked it and it works fine
> > , but
> > project>import/export>export project to dxf
> > that does not working 8 p in 6 p out
> 
> just tested here on 3.10/Linux, 8 in 8 out.

probaply works on linux not on win10

**Comment by tsterop** [comment]
> > where i checked it and it works fine
> > , but
> > project>import/export>export project to dxf
> > that does not working 8 p in 6 p out
> 
> just tested here on 3.10/Linux, 8 in 8 out.

thank you
probably, works on linux not on win10. !!!
Anybody with win10 QGIS 3.10 desktop to test it?

**Comment by gioman** [comment]
>  Anybody with win10 QGIS 3.10 desktop to test it?

just tested on 3.10 on Win7, 8 in 8 out.

**Comment by tsterop** [comment]
> > dxf_export.zip
> 
> Can you add the gpx file as well?
I have post it the files.
In my setup (acer aspire i3, **win 10**, desktop qgis3.10 and desktop qgis2.14,)
qgis3.10 8 point in 6 point out,!!!
ggis2.14 8 point in 8 point out (works fine)!!!
Gioman just tested here on 3.10/Linux, 8 in 8 out.
_Probably, works on linux not on win10. !!!
Anybody with win10 QGIS 3.10 desktop to test it?

**Comment by gioman** [comment]
>  Anybody with win10 QGIS 3.10 desktop to test it?

yes me (it really should not matter that I used Win7). I still get 8 points out.

**Comment by tsterop** [comment]
i am sorry, i closed the issue, by mistake.
gioman
you get 8 points with:
 project>import/export>export project to dxf  or  "export>save features as>dxf"

**Comment by tsterop** [comment]
i am sorry, i closed the issue, by mistake.
gioman
you get 8 points with:
 project>import/export>export project to dxf  or  "export>save features as>dxf"

**Comment by gioman** [comment]
both

**Comment by tsterop** [comment]
maybe its win10?

**Comment by gioman** [comment]
unlikely. Please try: with a new QGIS profile and/or on another machine.

**Comment by tsterop** [comment]
in my laptop win10 works o.k. only with "export > save features as > dxf,"
or with QGIS 2.14 (8 point in 8 point out)
not working with project>import/export>export project to dxf

**Comment by gioman** [comment]
> not working

so it is a draw, I think we must understand how it works on other machines/environments. Please give it a try.

**Comment by tsterop** [comment]
o.k. thanks

**Comment by baswein** [comment]
I tried it on 3.14.13 with win 10 using the **project>import/export>export project to dxf** 
 method and 8in/8out.

**Comment by tsterop** [comment]
"baswein
I tried it on 3.14.13 with win 10 using the project>import/export>export project to dxf
method and 8in/8out."
Do you mean 2.14.13? in QGIS 2.14 works o.k.
The current version is QGIS 3.10.0 'A Coruña' and was released on 25.10.2019, where is the problem.

**Comment by baswein** [comment]
Whoops I meant the LTR 3.4.13.
I just tried it in 3.10.0 and it worked as well.

**Comment by tsterop** [comment]
> Whoops I meant the LTR 3.4.13.
> I just tried it in 3.10.0 and it worked as well.

no 
just download ltr 3.4 and works fine, 4 points in 4 points out.
3.10: 4 points in 2 ponts out

**Comment by gioman** [comment]
>  3.10: 4 points in 2 ponts out

new dataset? please post a screencast showing the steps you are following.

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
