### ISSUE TITLE
Plugin failure

### ISSUE THREAD

**Issue by ColinN14** [qgis/QGIS#32605]
Crash ID: 188e441b487e48d0ebd7d07fe63c7c16edf44e05

Stack Trace

QWidget::actions :
QMenu::clear :
QgisApp::refreshProfileMenu :
QMetaObject::activate :
QMetaObject::activate :
QFileSystemWatcher::`default constructor closure' :
QMetaObject::activate :
QFileSystemWatcher::directoryChanged :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
QMessageBox::showEvent :
QMessageBox::critical :
QgisApp::QgisApp :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.10.0-A Coruña
QGIS code revision: 6c816b4204
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by nyalldawson** [comment]
There's no detail here to do anything with. Was this caused by a 3rd party plugin? Please provide steps leading up to the crash

**Comment by ColinN14** [comment]
The Plugins causing the problem are either by 'OSMDownloader' or Lat Lon Tools. The problem is created when QGIS loads.

________________________________

**Comment by roya0045** [comment]
I had similar issues with 3.4, this occurred when I typed something in the processing search bar, QGIS simply froze and I forced the termination after 20 mins of no response. I found that some map caused this issue and disabling rendering helped prevent the freeze.

**Comment by gioman** [comment]
> The Plugins causing the problem are either by 'OSMDownloader' or Lat Lon Tools. The problem is created when QGIS loads.

please report the issue to the plugins authors.
