### ISSUE TITLE
Profile tool plugin to select a Line feature crash QGIS 3.10

### ISSUE THREAD

**Issue by mlbraga82** [qgis/QGIS#32606]
## User Feedback

Some time my QGIS crash, when I use profile tool plugin to select a Line feature. This time crash when I create a new field in a new temporaly point vector.

## Report Details

**Crash ID**: [fa36b40844ca401947a0ae5aa3e850f91bb130c3]('https://github.com/qgis/QGIS/search?q=fa36b40844ca401947a0ae5aa3e850f91bb130c3&type=Issues')

**Stack Trace**
<pre>
QSortFilterProxyModel::parent :
QModelIndex::parent :
QTableView::visualRect :
QAbstractItemView::update :
QAbstractItemView::currentChanged :
QMetaObject::activate :
QItemSelectionModel::`default constructor closure' :
QItemSelectionModel::qt_static_metacall :
QMetaObject::activate :
QAbstractItemModel::beginRemoveRows :
QSortFilterProxyModel::removeRows :
QSortFilterProxyModel::sortRole :
QSortFilterProxyModel::`default constructor closure' :
QMetaObject::activate :
QAbstractItemModel::beginRemoveRows :
QgsAttributeTableModel::removeRows qgsattributetablemodel.cpp:177
QgsAttributeTableModel::loadLayer qgsattributetablemodel.cpp:449
QMetaObject::activate :
QMetaObject::activate :
QgsVectorLayer::updateFields qgsvectorlayer.cpp:3610
QgsVectorLayerUndoCommandAddAttribute::redo qgsvectorlayerundocommand.cpp:317
QUndoStack::push :
QgsVectorLayerEditBuffer::addAttribute qgsvectorlayereditbuffer.cpp:274
QgsAttributeTableDialog::mActionAddAttribute_triggered qgsattributetabledialog.cpp:1032
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1583
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.0-A Coruña
QGIS code revision: 6c816b4204
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by nyalldawson** [comment]
Please file this bug with the Profile tool plugin authors
