### ISSUE TITLE
Broken UI when loading layers through the Datasource Manager

### ISSUE THREAD

**Issue by NyakudyaA** [qgis/QGIS#32615]
# Problem

I am just trying to load a layer using the Datasource manager and I experience a weird behavior with the UI.

Broken UI
![broken-ui](https://user-images.githubusercontent.com/2510900/68102262-8d645800-feda-11e9-9e25-1e7180b2712d.png)

![broken_ui](https://user-images.githubusercontent.com/2510900/68102275-99501a00-feda-11e9-829c-6049dc927f76.png)

![save-1](https://user-images.githubusercontent.com/2510900/68102612-39f30980-fedc-11e9-8500-91a7c4dfc896.gif)

![os](https://user-images.githubusercontent.com/2510900/68102645-5727d800-fedc-11e9-909a-82e155aa60a6.png)

**Comment by elpaso** [comment]
May be we need the same solution I applied here? https://github.com/qgis/QGIS/pull/31665
Does it look a similar issue?

**Comment by NyakudyaA** [comment]
yes @elpaso it looks like similar issue

**Comment by elpaso** [comment]
This is odd: the same patch was moved to the base class and it should work for this dialog too :/

**Comment by elpaso** [comment]
@NyakudyaA please test the patch and let me know how it goes.

**Comment by NyakudyaA** [comment]
> @NyakudyaA please test the patch and let me know how it goes.

Thanks , let me get to it

**Comment by NyakudyaA** [comment]
@elpaso I have tested this and it looks good in master now

**Comment by elpaso** [comment]
@NyakudyaA thank you for the feedback!
