### ISSUE TITLE
QGIS crashed on start

### ISSUE THREAD

**Issue by torecki** [qgis/QGIS#32616]
## User Feedback

Just try to start.

## Report Details

**Crash ID**: [5eca77f15c8e3b0b2ba93bfb4b5d5b41db0e1192]('https://github.com/qgis/QGIS/search?q=5eca77f15c8e3b0b2ba93bfb4b5d5b41db0e1192&type=Issues')

**Stack Trace**
<pre>
QBasicMutex::unlockInternal :
QgsTask::~QgsTask qgstaskmanager.cpp:45
QgsNetworkContentFetcherTask::~QgsNetworkContentFetcherTask qgsnetworkcontentfetchertask.cpp:38
QgsNetworkContentFetcherTask::`vector deleting destructor' :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QCoreApplication::processEvents :
QgisApp::QgisApp qgisapp.cpp:1202
main main.cpp:1344
WinMain mainwin.cpp:170
__scrt_common_main_seh exe_common.inl:253
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.11.0-Master
QGIS code revision: 6e03a97f63
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.0dev
Running against GDAL: 3.1.0dev

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Describe the bug**

Start QGIS on Windows
**How to Reproduce**
Start QGIS on Windows

**QGIS and OS versions**
3.11

**Additional context**

**Comment by Gustry** [comment]
You should check the crash ID, there is already 3 existing tickets: https://github.com/qgis/QGIS/search?q=5eca77f15c8e3b0b2ba93bfb4b5d5b41db0e1192&type=Issues

It has already been fixed. It should be in the new nightly https://github.com/qgis/QGIS/issues/32592

**Comment by johansanders** [comment]
not fixed 
still getting crash

## User Feedback

crash on start

## Report Details

**Crash ID**: [0c52f94213ffd2c5b0d3c9573822a2705e892fd8]('https://github.com/qgis/QGIS/search?q=0c52f94213ffd2c5b0d3c9573822a2705e892fd8&type=Issues')


**Stack Trace**
<pre>
QBasicMutex::unlockInternal :
QgsNetworkContentFetcherTask::~QgsNetworkContentFetcherTask qgsnetworkcontentfetchertask.cpp:38
QgsNetworkContentFetcherTask::`vector deleting destructor' :
QObject::event :
QApplicationPrivate::notify_helper :
</pre>


**QGIS Info**
QGIS Version: 3.11.0-Master
QGIS code revision: 213df8df23
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.0dev
Running against GDAL: 3.1.0dev



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by gioman** [comment]
You should check the crash ID, there is already 3 existing tickets: https://github.com/qgis/QGIS/search?q=5eca77f15c8e3b0b2ba93bfb4b5d5b41db0e1192&type=Issues

It has already been fixed. It should be in the new nightly #32592

**Comment by gioman** [comment]
> not fixed
> still getting crash

I think you need to test using a  nightly-build, or wait 3.11.1 or compile the master code.

**Comment by johansanders** [comment]
Ok
I’ll be patiient
Thanks fort he reaction

Vriendelijke groeten
________________________________
Johan Sanders
Dienstverlening
Consulent Dienstbetoon
E johan.sanders@boerenbond.be<mailto:johan.sanders@boerenbond.be>
T (092) 43 88 31<tel:+3292438831>
M (0472) 81 03 36<tel:+32472810336>
Boerenbond & Landelijke Gilden
Kortrijksesteenweg 1144 J, 9051 Sint-Denijs-Westrem
http://www.boerenbond.be<http://www.boerenbond.be/>
http://www.landelijkegilden.be<http://www.landelijkegilden.be/>


Van: Giovanni Manghi <notifications@github.com>
Verzonden: maandag 4 november 2019 10:51
Aan: qgis/QGIS <QGIS@noreply.github.com>
CC: Johan Sanders <johan.sanders@boerenbond.be>; Comment <comment@noreply.github.com>
Onderwerp: Re: [qgis/QGIS] QGIS crashed on start (#32616)


not fixed
still getting crash

I think you need to test using a nightly-build, or wait 3.11.1 or compile the master code.
