### ISSUE TITLE
Geopackage not rendered correctly

### ISSUE THREAD

**Issue by Ellebjerg** [qgis/QGIS#32622]
My colleague and I have both experienced that data from a geopackage are not rendered correctly. It is a 90 MB file, so fairly large but not extreme. The package is an export from QGIS 3.10, so the format should be ok.

The error seems to occur in connection with panning. Refresh does not help, but a change in zoom brings back the missing features. The error only occurs every now and then, so it is not directly reproducable.

We have experienced it in 3.10, but as we have not worked a great deal with geopackage-data previously, we do not know whether the error has been there previously. I do not have time to test in earlier versions at present, but I may find the time in 1-2 weeks.

Best regards
Lars

**Comment by gioman** [comment]
Please attach/link the file (or a sample that shows the issue).

**Comment by Ellebjerg** [comment]
The data are for QA of the annual update of national geodata. The released data are publicly available at kortforsyningen.dk, copyright Danish Agency for Data Supply and Efficiency.

[geodk_data_t_ks_2019.zip](https://github.com/qgis/QGIS/files/3803492/geodk_data_t_ks_2019.zip)

**Comment by Pedro-Murteira** [comment]
@Ellebjerg I can't replicate this using QGIS 3.22.2. and 3.16.15. Is this still an issue with you?

**Comment by Ellebjerg** [comment]
I haven't experienced it recently, but I haven't worked with large geopackages so I can't say for sure that it is not an issue. 
I have tested in 3.16.15 with the data which I uploaded for the issue without experiencing any problems. But as I wrote originally, the problem only occurred every now and then.
As neither of us can reproduce, I will close the issue.
