### ISSUE TITLE
Issue installing qgis -debian unix

### ISSUE THREAD

**Issue by QGISUpslope** [qgis/QGIS#32625]
WHen trying to install qgis on my chromebook, uses the debian install instructions - https://qgis.org/en/site/forusers/alldownloads.html#debian-ubuntu

With the text  added to my /etc/apt/source file
deb https://qgis.org/debian-ltr stretch main

deb-src  https://qgis.org/debian-ltr stretch main

it is installing qgis 2.14 instead of 3.4.13

thoughts?

**Comment by gioman** [comment]
apt-cache policy qgis

says to you what is the available/installed version and from what repo comes from. If in your case you added the QGIS repo and it still says 2.14 it means that there is no candidate for installation of qgis 3 on your platform... unless you have just missed to do apt-get update...

**Comment by QGISUpslope** [comment]
Thanks
