### ISSUE TITLE
QGIS 3.10 and MASTER crash on startup on Windows 7

### ISSUE THREAD

**Issue by Antoviscomi** [qgis/QGIS#32623]
It happens both with a totally clean profile and with the default profile

below I have attached the crashes files

[0b3c32b7-0e55-4922-8fc1-09596ff9567f.zip](https://github.com/qgis/QGIS/files/3803682/0b3c32b7-0e55-4922-8fc1-09596ff9567f.zip)

**Comment by Antoviscomi** [comment]
![image](https://user-images.githubusercontent.com/12639444/68117648-38d2d400-fefe-11e9-81c0-6e0f32dbc136.png)

![image](https://user-images.githubusercontent.com/12639444/68117726-6881dc00-fefe-11e9-8d9f-1fbc3cf8a8e4.png)

**Comment by gioman** [comment]
You should check the crash ID, it's a duplicate https://github.com/qgis/QGIS/search?q=5eca77f15c8e3b0b2ba93bfb4b5d5b41db0e1192&type=Issues

#32592

**Comment by Antoviscomi** [comment]
Ok @gioman I'll wait for for fixed update
