### ISSUE TITLE
Bug when trying to select features from large Oracle datasets

### ISSUE THREAD

**Issue by paulwittle** [qgis/QGIS#32648]
**Describe the bug**
We believe the Oracle ROWID is not 100% reliable as a primary key as previous ROWID values can be reused if data is deleted and re-imported. It can also change dynamically if you have a partitioned table.

The result is that we are finding the basic select tool in QGIS 3.4.7 results in the wrong features being selected. I have tried configuring the layer with a primary key but it still seems to be using ROWID. We have also run the SQL in FME and checked the result and it comes back as a rectangle of data so we have concluded that QGIS must be incorrectly applying the results. 

[Please see this screenshot](http://static.geowessex.com/191105-screenshot.png)

**How to Reproduce**

We simple load a layer directly from Oracle and then use the standard selection tools to drag a rectangle on the map. The features within the area turn yellow but so do random features outside the area. When we then copy and paste the features to another layer some of the features inside are missing so it doesn't appear that the results can be used consistently. 

**QGIS and OS versions**

QGIS 3.4.7 on a Windows 10 operating system using Oracle 12c

**Comment by jef-n** [comment]
The provider should use the actual primary key.   How is the above table defined?

**Comment by paulwittle** [comment]
The table has a number of constraints in Oracle including a primary key. The name of the primary key is not the same as the field name on which it is based of course. I've managed to tell QGIS there is a key and the source line looks like this:

port=1521 user='qgis' key='UPRN' estimatedmetadata=true srid=27700 table="ADDRESS_TABLE" (GEOM) sql=

**Comment by paulwittle** [comment]
On inspection, you can't set a primary key for a table the select option only appears for views. I am adding my layers via Python so I've been able to add the key= to the definition but if you look at the information tab the table doesn't have a primary key listed under Fields but the view does. 

Short and long, I'm not sure it respects a primary key being set unless the source is a view.

Does that sound right?

**Comment by jef-n** [comment]
> On inspection, you can't set a primary key for a table the select option only appears for views. I am adding my layers via Python so I've been able to add the key= to the definition but if you look at the information tab the table doesn't have a primary key listed under Fields but the view does.

Yes.  The primary keys are detected automatically for tables.   Do you also have the problem when load the layer through the UI?

**Comment by paulwittle** [comment]
Yes, the primary keys are not being picked up so I suspect we don't have the expected metadata that QGIS is looking for. Can you point me in the right direction to find out how QGIS picks up the primary key automatically (I assume it is an SQL statement to pull from the metadata tables). 

I should be able to quickly identify if we have done something unexpected with our database and share the result here to help others if they run into the same issue.

**Comment by jef-n** [comment]
> Yes, the primary keys are not being picked up so I suspect we don't have the expected metadata that QGIS is looking for. Can you point me in the right direction to find out how QGIS picks up the primary key automatically (I assume it is an SQL statement to pull from the metadata tables).

[QgsOracleProvider::determinePrimaryKey](https://github.com/qgis/QGIS/blob/5910a7b9f14a951714226767ccb9bc3d3347dc7a/src/providers/oracle/qgsoracleprovider.cpp#L872)

**Comment by paulwittle** [comment]
Okay, thank you for that. Turns out that one of our tables didn't have a primary key constraint it was only an index. We will get that updated. 
I note that it will not let you add a view without specifying a primary key; would it not be wise for it to notify the user if they try to add a table and there is no primary key found? 
In this context QGIS knows that the table doesn't have a primary key but it still lets you add it to your map. This is then confusing because everything seems fine till you start selecting so I think it might be easier if it just enforces, or at least warns, that a primary key is a requirement.

**Comment by paulwittle** [comment]
I've proposed a quick change to the documentation for your consideration. A warning in the application may still be wise but I think something like my proposal should be enough in the first instance to close off this bug report.

Thanks again for your help!
