### ISSUE TITLE
QGIS Server WFS3 items page link issues

### ISSUE THREAD

**Issue by tudorbarascu** [qgis/QGIS#32641]
ping @elpaso 

How to reproduce:

- Go to WFS3 items page for a layer, e.g. ``world`` layer in the qgis server vagrant machine

- On the ``http://localhost:8080/project/helloworld/wfs3/collections/world/items`` page.. the links for every item are not correctly generated

Meaning:
* Wrong: ``http://localhost:8080/project/helloworld/wfs3/collections/world/item/0?`` it should be ``items`` in the link

* Correct: ``http://localhost:8080/project/helloworld/wfs3/collections/world/items/0?``

Tried fixing it myself but the fix eluded me.

**Comment by elpaso** [comment]
@tudorbarascu I cannot reproduce on current master:
![immagine](https://user-images.githubusercontent.com/142164/68191667-519bc200-ffb0-11e9-9928-9d618373fc53.png)

**Comment by elpaso** [comment]
Can you add a failing test case somewhere near https://github.com/qgis/QGIS/blob/master/tests/src/python/test_qgsserver_api.py#L422 ?

**Comment by tudorbarascu** [comment]
@elpaso Will try and thanks for looking into this!

You can reproduce it if you replace in your url ``items.html`` with ``items``.
If I add the ``.html`` part it works for me also.

**Comment by elpaso** [comment]
Thank **you** for testing WFS3 and finding my bugs :)
