### ISSUE TITLE
"Extract by location"  atributes bug when two predicates are selected

### ISSUE THREAD

**Issue by simogeo** [qgis/QGIS#32653]
**Describe the bug**

When using "Extract by location" from _Processings_,  choosing two predicates as seen below causes duplicates rows ... when object intersects and is within. 

Geometries are unique but I get duplicates rows in attributes.

**How to Reproduce**

1. Open Processings toolbox
2. Click on "Extract by location" 
3. Choose any input layer : here "polygons-2"
4. Check predicates : 'intersects' and 'are within'
5. Choose second layer `By comparing features from` "polygon"

![image](https://user-images.githubusercontent.com/154323/68209241-355d4c80-ffd3-11e9-82d1-646ef4af075d.png)

6. Open attributes table from created layer
7. Observe duplicated rows in  attributes when object match both  'intersects' and 'within' conditions !

![image](https://user-images.githubusercontent.com/154323/68212517-f67ec500-ffd9-11e9-8689-c16cf8022fe1.png)

**QGIS and OS versions**

Version de QGIS | 3.10.0-A Coruña | Révision du code | 6c816b4204
-- | -- | -- | --
Compilé avec Qt | 5.9.5 | Utilisant Qt | 5.9.5
Compilé avec GDAL/OGR | 2.2.3 | Utilisé avec GDAL/OGR | 2.2.3
Compilé avec GEOS | 3.6.2-CAPI-1.10.2 | Utilisé avec GEOS | 3.6.2-CAPI-1.10.2 4d2925d6
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
Version du client PostgreSQL | 10.10 (Ubuntu 10.10-0ubuntu0.18.04.1) | Version de SpatiaLite | 4.3.0a
Version de QWT | 6.1.3 | Version de QScintilla2 | 2.10.2
Version de PROJ.4 : | 493
OS Version | Ubuntu 18.04.3 LTS
Extensions Python actives | VectorBender; AnotherDXF2Shape; mask; Qgis2threejs; GeoCoding; vector_tiles_reader; qconsolidate3; shapetools; Hqgis; DataPlotly; french_locator_filter; SRTM-Downloader; Beeline; OSMtools; QNEAT3; loadthemall; db_manager; MetaSearch; processing

**Additional context**

**Comment by gioman** [comment]
@alexbruy should we use a radio button instead or is supposed to work with multiple predicates?

**Comment by simogeo** [comment]
according to me, by default, should be OR condition. But actually, it would be nice to have the ability to choose with radio buttons OR / AND conditions. 

(my 2 cents)

**Comment by nyalldawson** [comment]
I can't reproduce. Can you post sample data and step-by-step instructions?

**Comment by simogeo** [comment]
@nyalldawson : I'll try it again in latest QGIS version and let you know

**Comment by simogeo** [comment]
Bug still there in version. Here comes a [sample dataset](https://github.com/qgis/QGIS/files/4423364/qgis-buggy.zip) and a screenshot 


1. Open Processings toolbox
2. Click on "Extract by location" 
3. Choose any input layer : here "polygons-2"
4. Check predicates : 'intersects' and 'are within'
5. Choose second layer `By comparing features from` "polygon"
6. Open attributes table from created layer
7. Observe duplicated rows in  attributes when object match both  'intersect

' and 'are within' conditions - following screenshot : 

![image](https://user-images.githubusercontent.com/154323/78296381-f3a6e280-752d-11ea-9d5e-5b47a6049246.png)

**Comment by simogeo** [comment]
:+1:  thanks you !
