### ISSUE TITLE
QGIS 3.10 crashes when trying to rotate a polygon object

### ISSUE THREAD

**Issue by tclaassen** [qgis/QGIS#32657]
QGIS 3.10 crashes each time when I start to rotate a polygon, no matter if it's from a shape file, from a newly created temporary layer or from a PostGIS layer.
By using the rotation tool, it's possible to select the polygon and to rotate the mask but when fixing the desired position by left mouse click QGIS does not respond any more an uses full CPU capacity.
I waited once for >10 min for any program response without success.
It's only possible to get out by closing the program by the windows cross. QGIS then quits without error message or crash report under C:\Users\thomas.claassen\AppData\Local\QGIS\QGIS3\crashes\
resectively

This bug occures since I have upated from 3.8 to 3.10 on 1st Nov 2019.

##############
QGIS-Version | 3.10.0-A CoruÃ±a | QGIS-Codeversion | 6c816b4204
-- | -- | -- | --
Kompiliert gegen Qt | 5.11.2 | Laufendes Qt | 5.11.2
Kompiliert mit GDAL/OGR | 2.4.1 | Läuft mit GDAL/OGR | 2.4.1
Kompiliert mit GEOS | 3.8.0-CAPI-1.13.1 | Läuft mit GEOS | 3.8.0-CAPI-1.13.1
Kompiliert mit SQLite | 3.29.0 | Läuft mit SQLite | 3.29.0
PostgreSQL-Client-Version | 11.5 | SpatiaLite-Version | 4.3.0
QWT-Version | 6.1.3 | QScintilla2-Version | 2.10.8
Kompiliert mit PROJ | 5.2.0 | Läuft mit PROJ | Rel. 5.2.0, September 15th, 2018
BS-Version | Windows 10 (10.0)
Aktive Python-Erweiterungen | alkisplugin; AnotherDXF2Shape; arrayplus; autoSaver; cadastre; DB_Werkzeug; DigitizingTools; french_locator_filter; geometric_attributes; gisquick-qgis-plugin; ImportPhotos; joinmultiplelines; kml_style_importer; latlontools; layer2kmz; LocatePoints; MemoryLayerSaver; mmqgis; openlayers_plugin; PostNAS_Search; refFunctions; SpreadsheetLayers; xplanung; db_manager; processing.

**Comment by Gustry** [comment]
Duplicate https://github.com/qgis/QGIS/issues/32123 ?
Which is already closed because fixed.

**Comment by nyalldawson** [comment]
Yes, duplicate

**Comment by tclaassen** [comment]
Hi,
I disagree. The issue is not fixed because it still occurs.
The #32123 refers to QGIS 3.9 but I reported a new bug on version 3.10 including all latest updates.
So, please let #32657 open.

Von: Étienne Trimaille [mailto:notifications@github.com]
Gesendet: Dienstag, 5. November 2019 17:32
An: qgis/QGIS <QGIS@noreply.github.com>
Cc: Thomas Claassen <Thomas.Claassen@deangruppe.de>; Author <author@noreply.github.com>
Betreff: Re: [qgis/QGIS] QGIS 3.10 crashes when trying to rotate a polygon object (#32657)


Duplicate #32123<https://github.com/qgis/QGIS/issues/32123> ?
Which is already closed because fixed.

**Comment by Gustry** [comment]
Reported since QGIS 3.9, fixed in 3.10.1 so wait end of november.

**Comment by leonmvd** [comment]
Same issue here on Mac in 3.10.

**Comment by leonmvd** [comment]
In the nightly version 3.11 of 2019-12-09 the issue is resolved indeed

**Comment by JohnRLang** [comment]
Look forward to update 3.11 as Version 3.10.1 also crashed rotating point feature classes

**Comment by elpaso** [comment]
Don't forget that if you are on windows there are simplified (no python) builds available for testing on every commit, just click on https://github.com/qgis/QGIS/actions, select a build and download the artifact (top right link).

Actually, testing is strongly encouraged because it gives quick feedback to the developers.

**Comment by JohnRLang** [comment]
Thanks Alessandro
Unfortunately I'm a newbe so whilst able to download the artifact I can't
understand how to make the qgis exec

**Comment by elpaso** [comment]
@JohnRLang the artifact is a zip that contains another zip. Inside the second zip there is a qgis.exe binary.
So, the procedure is to download the artifact, unzip it (twice) to a temporary folder and run qgis.exe.

**Comment by JohnRLang** [comment]
Thank you for your reply. Unfortunately overseas until 13th. Will try and
respond when I am back. John
