### ISSUE TITLE
ECW support disabled/does not works in QGIS 3.10 in Windows 7

### ISSUE THREAD

**Issue by Antoviscomi** [qgis/QGIS#32681]
Hi All,
After today update, I've noticed that ECW support is no longer avaible/working in 6ffa89eb3e (today nightly of 3.10) and when I try to open an ECW, QGIS come out with this log message:

_2019-11-06T10:38:51     CRITICAL    Layer non valido : GDAL provider Cannot open GDAL dataset G:\Dati\Cartografia\Ortofoto\ProvRC1\583030.ecw:
             `G:\Dati\Cartografia\Ortofoto\ProvRC1\583030.ecw' not recognized as a supported file format. (file: ..\..\..\src\core\providers\gdal\qgsgdalprovider.cpp row: 2619function QgsGdalProvider::initIfNeeded:)
             Raster layer Sorgente dati non valida (sorgente dati: gdal, URI: G:\Dati\Cartografia\Ortofoto\ProvRC1\583030.ecw (file: ..\..\..\src\core\raster\qgsrasterlayer.cpp row: 614function QgsRasterLayer::setDataProvider:)_

**Comment by Antoviscomi** [comment]
for some reason the gdal-dev-ecw library (nigthly-master by osgeow) hadn't been updated, now I have reinstalled it and the ECW support works again

**Comment by Mishelm2** [comment]
> for some reason the gdal-dev-ecw library (nigthly-master by osgeow) hadn't been updated, now I have reinstalled it and the ECW support works again

Hi ANtoviscomi:
Would you like to let me know how did you solve the issue? I mean, which command did you use for update gdal-dev-ecw library? Thanks in advance.
MIshel

**Comment by Juncus** [comment]
Ah so helpful is github. Still not included and no way to install.
