### ISSUE TITLE
Crash when using vertex editor

### ISSUE THREAD

**Issue by SrNetoChan** [qgis/QGIS#32685]
**Describe the bug**

Getting a QGIS Crash when using the Vextex Editor Panel. My layer has Z values.

After the crash the command line shows the following:

```
Warning: QObject::connect: invalid null parameter
Warning: QObject::connect: invalid null parameter
Warning: QObject::connect: invalid null parameter
Warning: QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
need for update
need for update
need for update
need for update
need for update
Xlib: sequence lost (0x1160c > 0x160e) in reply type 0x23!
QGIS died on signal 11Could not attach to process.  If your uid matches the uid of the target
process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
ptrace: Operation not permitted.
No thread selected
No stack.
gdb returned 0
Aborted (core dumped)
```

**How to Reproduce**

1. Turn editing mode for a vector layer
2 . Using the vertex tool, select a couple of vertices
3. Right-click the vertices to open the Vertex Editor
4. Click the Select Features by area tool (I think any other tool will result in the same problem)
5. Bum!

![Peek 2019-11-06 12-05](https://user-images.githubusercontent.com/3607161/68297390-b6c5e500-008e-11ea-931b-ffebae0a4a25.gif)

**QGIS and OS versions**

QGIS version | 3.10.0-A Coruña | QGIS code revision | 6c816b4204
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.6.2-CAPI-1.10.2 4d2925d6
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 10.10 (Ubuntu 10.10-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Ubuntu 18.04.3 LTS
Active python plugins | MetaSearch; db_manager; processing

**Additional context**

Tested with a clean profile

**Comment by jef-n** [comment]
See [Creating a backtrace](https://www.qgis.org/en/site/getinvolved/development/bugreporting.html#creating-a-backtrace) to produce a backtrace from the core dump.

**Comment by saberraz** [comment]
It is also happening in master (87a8a16bbd)
[core_dumped.zip](https://github.com/qgis/QGIS/files/3814481/core_dumped.zip)

**Comment by SrNetoChan** [comment]
And confirmed in Windows 10

**Comment by nirvn** [comment]
@SrNetoChan , can you confirm the crash is gone as of commit e6a932b ? Thanks.

**Comment by SrNetoChan** [comment]
@nirvn I have confirmed in master and it seems fixed. thanks!

**Comment by nirvn** [comment]
Good. Your GIF was useful, I had tried (and failed) to dissect that one before and couldn't reproduce a crash until today.
