### ISSUE TITLE
Grass Progressing Alg's won't run 3.10.0 OSGeo Win 10

### ISSUE THREAD

**Issue by baswein** [qgis/QGIS#32687]
**Describe the bug**

After update to 3.10.0 and 3.14.13 using OSGeo4w Grass processing algorithms give the warning and do not run. "The specified GRASS 7 folder "C:\OSGeo4W64\bin\bin" does not contain a valid set of GRASS 7 modules. Please, go to the Processing settings dialog, and check that the GRASS 7 folder is correctly configured"
In the past I have been able to fix this by changing the path in the processing settings but the path is not available to change there. 
![image](https://user-images.githubusercontent.com/15817745/68302970-f7af0100-0070-11ea-8c5e-7b479cba87f8.png)
Or I have found that the grass version installed by [OSGeo is different than the version QGIS expects](https://issues.qgis.org/issues/19692). 
![image](https://user-images.githubusercontent.com/15817745/68303166-4d83a900-0071-11ea-9bf3-207e06e58797.png)
This did appear to be the case and I reverted grass from 7.8 to 7.6.1 but that did not fix the issue. 
If I copy the grass bin folder to the path the error is describing I can run the processes. 
The path in Option>System>Environment appears to be correct. 
![image](https://user-images.githubusercontent.com/15817745/68304123-2037fa80-0073-11ea-918a-f1e745ef6d13.png)
I am running the QGIS version with grass. 
![image](https://user-images.githubusercontent.com/15817745/68304324-86248200-0073-11ea-9d8d-ec830cf8469f.png)

**How to Reproduce**
Update QGIS to 3.10.0 using the OSGeo setup processes. Run QGIS with Grass. Try to start a Grass processes such as r.buffer.  

**QGIS and OS versions**

QGIS version | 3.10.0-A CoruÃ±a | QGIS code revision | 6c816b4204
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Windows 10 (10.0)
Active python plugins | inkscape2symbol-master; processing_r; Qgis2threejs; qgsAzimuth; QuickOSM; quick_map_services; toolbargenerator; workbench; db_manager; MetaSearch; processing

**Additional context**
I know this is a known and persistent issue and I may be missing something simple but after churning through all of the documentation on this It appears there is a lot of confusion about grass and it's connection to QGIS and are a number of improvements and clarifications that would help and I feel it should be addressed as these are the kinds of frustrations that turn off new users. 
1. The distinction between the grass 7 plugin and the grass algorithms. A more comprehensive description in the plugin may help this.
![image](https://user-images.githubusercontent.com/15817745/68305036-f4b60f80-0074-11ea-81c5-8e25a059cc8e.png)
2. Running QGIS with and without GRASS. This is very confusing for those new to QGIS, such as my students and I do not understand why there are two shortcuts. After fixing the grass file path if I start either one I am able to run grass processes..
3. OSGeo updates Grass when a new version comes out and this breaks the Grass QGIS connection. 
4. The warning dialog doesn't describe a valid fix.

**Comment by jef-n** [comment]
Did you start using the "QGIS with GRASS" shortcut?

**Comment by neteler** [comment]
Update: GRASS GIS 7.8.1 with support for Python 3, PROJ 6 and GDAL 3 has been released:

- https://github.com/OSGeo/grass/releases/tag/7.8.1
- https://trac.osgeo.org/grass/wiki/Release/7.8.1-News

**Comment by roya0045** [comment]
@neteler this might be more useful on the dev mailing list, if you haven't spread the word there already.

**Comment by gioman** [comment]
> After update to 3.10.0 and 3.14.13 using OSGeo4w Grass processing algorithms give the warning and do not run. "The specified GRASS 7 folder "C:\OSGeo4W64\bin\bin" does not contain a valid set of GRASS 7 modules. Please, go to the Processing settings dialog, and check that the GRASS 7 folder is correctly configured"

I also see this on OSGeo4W installations, but is ok on QGIS master. Maybe is just a matter to wait a round of updates(?) @jef-n

**Comment by jef-n** [comment]
> I also see this on OSGeo4W installations, but is ok on QGIS master

Using the "with GRASS" shortcut?

**Comment by gioman** [comment]
> Using the "with GRASS" shortcut?

yes.

**Comment by baswein** [comment]
Waiting is fine because I have a work around: I revert the grass version back to 7.6.1 and I copy the grass bin folder to C:\OSGeo4W64\bin where the error says it is looking for it. I'm not sure if that is breaking anything about grass. 
In the spirit of "it shouldn't be that way" I do think my points in Additional context should be addressed. Should I do them as feature requests? Thanks for all of this!

**Comment by baswein** [comment]
With the updates it's working now. Thanks!

**Comment by micha-silver** [comment]
I can confirm this problem. Fresh install of QGIS 3.14 on Win10, there is no menu shortcut to "QGIS with GRASS", the provider does not work (GRASS folders in the browser window do no show the GRASS maps), and under Processing, the GRASS modules do not work.
(GRASS itself works)
BTW, the error that shows when trying to run GRASS modules is bogus.  It says:

"This algorithm cannot be run :-( 
The specified GRASS 7 folder "C:\OSGEO4~1\bin\bin" does not contain a valid set of GRASS 7 modules. Please, go to the Processing settings dialog, and check that the GRASS 7 folder is correctly configured"

but there is no place to configure the GRASS 7 folder in Processing->Settings (it was removed, I believe, many versions ago). Perhaps this error message should be updated?

Thanks, Micha

**Comment by gioman** [comment]
> there is no menu shortcut to "QGIS with GRASS"

@micha-silver have you installed with the standalone installer or with osgeo4w?

**Comment by micha-silver** [comment]
I use the OSGeo4W installer.

**Comment by gioman** [comment]
> I use the OSGeo4W installer.

@micha-silver have you installed the "qgis-grass-plugin*" packages? You get GRASS (also in Processing) and the the "with GRASS" shortcut  only if you install those.

**Comment by micha-silver** [comment]
That was it. Thanks for reminding me.

**Comment by Rafael-Vinicius-Rodrigues** [comment]
I was with the same problem: when I tried to run any GRASS algorithm, it showed me that error message. Then I just copy the whole folder named "**bin**" in this path "**C:\Program Files\QGIS 3.10\apps\grass\grass78\bin**" into the "**C:\Program Files\QGIS 3.10\bin**". Afterwards, my problem was solved.

I am using versions: 
QGIS 3.10.7 A Coruña
Compilado sobre GDAL/OGR 3.0.4
Compilado sobre GEOS 3.8.1-CAPI-1.13.3

I hope I have helped someone.
Greetings!!!

**Comment by HeatherHillers** [comment]
You can also fix the problem in apps\qgis-ltr\python\plugins\processing\algs\grass7\Grass7Utils.py.  In the function GrassBin(), right before the return, add the line
Grass7Utils.path = r"C:\OSGeo4W64\apps\grass\grass78"

**Comment by rkalasek** [comment]
same here - installed a fresh QGIS on a new machine a few days ago. used OSGeo4W installer and activated anything which seemed to be necessary for GRASS to work (GRASS as well as GRASS plugins)

unsing QGIS_ 3.14.16, GRASS 7.8.3. 
asked for help in the following stackexchange post: https://gis.stackexchange.com/questions/374457/grass-doesnt-run-on-qgis

and there is definitely nothing like qgis-bin-g7.exe and qgis-bin-g7.env in the C:\OSGeo4W64\bin folder. just to be shure i've tried my QGIS 3.12. version on a virtual machine - which worked fine and did have all necessary files in \bin - then updated with OSGeo4W + setup / avanced options. after update nothing worked anymore.

**Comment by jef-n** [comment]
Did you install qgis-grass-plugin7 (or qgis-full)?

**Comment by rkalasek** [comment]
i did install both. strange enough ... just did an update via OSGeo4W and could find the qgis-bin-g7.exe right now. just nuw i am starting to recheck that on the virtual machine too ...

**Comment by d-lombardi-a** [comment]
I've encountered the same issue described by @baswein.
Found a workaround by changing, from the qgis python console, the qgis search path for grass7 bin folder :
`from processing.algs.grass7.Grass7Utils import Grass7Utils`
`Grass7Utils.path=r'C:\Program Files\QGIS 3.10\apps\grass\grass78'`

**Comment by baswein** [comment]
@d-lombardi-a  I'm glad you were able to find some sort of workaround. The specific problem that I encountered should be fixed at this point (although this does seem to be a problem that reappears in different versions from time to time). What version of QGIS are you using and was it the standalone installer or OSGeo?

**Comment by d-lombardi-a** [comment]
I’m running QGIS 3.10.7 A Coruña installed trough OSGEO on Windows.
Thanks.

Da: baswein ***@***.***>
Inviato: martedì 4 maggio 2021 23:07
A: qgis/QGIS ***@***.***>
Cc: LOMBARDI DARIO ***@***.***>; Mention ***@***.***>
Oggetto: Re: [qgis/QGIS] Grass Progressing Alg's won't run 3.10.0 OSGeo Win 10 (#32687)


@d-lombardi-a<https://github.com/d-lombardi-a> I'm glad you were able to find some sort of workaround. The specific problem that I encountered should be fixed at this point (although this does seem to be a problem that reappears in different versions from time to time). What version of QGIS are you using and was it the standalone installer or OSGeo?
