### ISSUE TITLE
Disable the CRS combobox in the "Save Vector Layer as..." dialog when not relevant

### ISSUE THREAD

**Issue by dericke** [qgis/QGIS#32698]
**Feature description.**
Some vector data types only support one projection, typically WGS84. Two examples would be KML and GeoJSON saved with the RFC7946 option. When the user's selections make CRS selection irrelevant, this could be communicated to the user by disabling the CRS combobox until user selections make it relevant again. Something similar is already done with the Encoding combobox.

**Additional context**
A full list of applicable data types should be compiled before anyone starts work on this. To begin:

* KML
* RFC7946-flavor GeoJSON
* Any data type when "Geometry type" is set to "No geometry"

**Comment by alexbruy** [comment]
Duplicates #16404
