### ISSUE TITLE
Windows 64-bit Install Failure

### ISSUE THREAD

**Issue by wbpaley** [qgis/QGIS#32697]
**Describe the bug**

I tried to do a noob (me!) install and got this:
![QGIS_installFail](https://user-images.githubusercontent.com/60867/68325154-dd881980-0096-11ea-8631-f6f4780026e8.jpg)
It said to report (but not to whom), so I'm trying to comply.
(And would love to try out this remarkable-looking app.)

**How to Reproduce**
Try to install.

**QGIS and OS versions**
QGIS: Whatever's linked from the (current) page in the image above.
OS: Windows 10 Pro, Version 1709, OS Build 16299.125

 

**Additional context**

**Comment by roya0045** [comment]
This is a GRASS error, I would assume that you have installed QGIS properly beforehand.

**Comment by wbpaley** [comment]
Thanks for the instant reply!

I’d hoped that just clicking the link on the shown page would install whatever was necessary, since there was no install procedure document. (Or did I miss that?)

No, I’ve never installed QGIS before—maybe oops? Should I have started somewhere else?

**Comment by roya0045** [comment]
Did you click on the standalone 3.10 64bit link? 

I find it curious that it gave you a grass popup but that might be possible if you used the network installer and are not too sure what to do.

**Comment by wbpaley** [comment]
Oh I see: newbie misreading; didn't mentally parse the red on the page 
in that first link:
QGIS in OSGeo4W

Bet installing with the standalone does it. Thanks!

**Comment by wbpaley** [comment]
To follow up:
I'm running, using that standalone like--issue closed for me; thanks!
But if the intent was to have the net-install link do the same as the 
standalone,
maybe the issue should stay open?
Happy to uninstall and reinstall over the net as a guinea pig if needed.

Separate question:
I'm running and downloaded the Alaska demo data set.
And the interface assumes a lot of things I don't know.
(Didn't really expect it to be as neophyte-friendly as Google Maps...   ;)
Guess I'll start here https://docs.qgis.org/3.4/en/docs/user_manual 
<https://docs.qgis.org/3.4/en/docs/user_manual/>
unless you have a better quickstart/on-ramp for me?

**Comment by roya0045** [comment]
The network installer is often for users that are more familiar with QGIS and desire more or less components.

Though for a starting point the main page of the doc should cover most things https://docs.qgis.org/3.4/en/docs/

Otherwise if you have questions you can use the user mailing list : https://lists.osgeo.org/mailman/listinfo/qgis-user the email address is in the page. 

In the meantime I would suggest closing this ticket and happy mapping!

**Comment by wbpaley** [comment]
Closed--thanks!

(Though I might suggest putting the standalone links above the net installers, 
for those of us so new we're just looking for the first that looks like it'll work...   ;)
