### ISSUE TITLE
Swatch in color selector does not always save colours

### ISSUE THREAD

**Issue by AlisterH** [qgis/QGIS#32704]
If you change the colours in the swatch in the layer colour selector (see [https://docs.qgis.org/testing/en/docs/user_manual/introduction/general_tools.html#color-selector](https://docs.qgis.org/testing/en/docs/user_manual/introduction/general_tools.html#color-selector)) it may or may not save the change, depending on how you got to the colour selector.
e.g. it does not save if I get to the colour selector from the styling tab of the layer properties dialog for a singleband pseudocolor, clicking on one of the colours in table.
It does save it if I do the same thing but from the layer styling panel instead of the layer properties dialog.
It does save it if I get to the colour selector from the styling tab of the layer properties dialog, editing the colour of a simple fill for a polygon layer.

Perhaps the problems are only to do with the layer properties dialog; I don't know.  At one point it was suggested that issues like this could be expected when styling through the layer properties dialog, because it was essentially obsolete.  Is it going to be removed at some point?

Testing in 3.10.0 and 3.8.3 on Windows.

**Comment by gioman** [comment]
Fixed by https://github.com/qgis/QGIS/pull/37866 see https://github.com/qgis/QGIS/issues/37749
