### ISSUE TITLE
QGIS crashes on getting items of mapCanvas' scene.

### ISSUE THREAD

**Issue by kadirsahbaz** [qgis/QGIS#32700]
**Describe the bug**
If I try to get items of mapCanvas' scene using `iface.mapCanvas().scene().items()`, QGIS crashes without warning or crash report. I encountered that issue after updating from version 3.4.12 to version 3.4.13 LTR, 3.10.0-A Coruña. and 3.11.0-Master. In Windows, QGIS freezes.

No crashing on version 3.4.12 LTR.

**How to Reproduce**
Just run `iface.mapCanvas().scene().items()`  in the Python Console.
`
**QGIS and OS versions**
QGIS:  3.4.13 LTR  /  3.10.0-A Coruña  /  3.11.0-Master
OS: Ubuntu 18.04.3 LTS / Windows 10, version 1903

**Comment by gioman** [comment]
>  Just run `iface.mapCanvas().scene().items()` in the Python Console.

does not crash here on 3.4.13 on Ubuntu 18.04.

**Comment by gioman** [comment]
never mind, it crashes.
