### ISSUE TITLE
expression function "relation_aggregate" does not accept "filter" parameter even though docs show it does.

### ISSUE THREAD

**Issue by starlandcounty** [qgis/QGIS#32702]
When using the relation_aggregate() function in the expression editor (of field calculator), according to the popup help one of the parameters is "filter". However, if I try using the filter parameter it gives an error that "filter" is not an acceptable parameter name.

I've created a clean project with dummy relational data to verify it wasn't my project.

The "Show Help" feature of the Expression Editor inside the Field Calculator shows "filter" is an optional parameter:

>filter
>optional filter expression to order the features used for calculating the aggregate. Fields and geometry are from the features on the joined layer.

In the expression builder to make sure I'm entering parameters syntax correctly the following works:
`relation_aggregate( relation:='road_dustc_gid_road_dustc_gid', aggregate:='sum', expression:="total")`

Yet if I add the "filter" parameter described:
`relation_aggregate( relation:='road_dustc_gid_road_dustc_gid', aggregate:='sum', expression:="total",filter:="year"=2019)`

It gives me an expression is invalid with this description:
`Invalid QgsExpressionFunction::Parameter name 'filter' for relation_aggregate`

If I go into the code I do not see a "filter" parameter for that function. There is an "order_by" parameter but it isn't listed in the show help feature.

**Comment by roya0045** [comment]
You are right, the filter parameter are wrongly named and order by is missing documentation.

[Here its called concatenator](https://github.com/qgis/QGIS/blob/81e645902f4d2001f6f49985f503daf8c5ea24ef/src/core/expression/qgsexpressionfunction.cpp#L676) and order by is just below.
[Here the variable is also called concatenaror](https://github.com/qgis/QGIS/blob/81e645902f4d2001f6f49985f503daf8c5ea24ef/src/core/expression/qgsexpressionfunction.cpp#L5260)

In the PR where I made changes to the expression [I used concatenator as a filter](https://github.com/qgis/QGIS/blob/5a3acf69c4a937e173dfaacf8faf2a491d3b02ea/python/plugins/processing/algs/qgis/Aggregate.py#L158) and everything is ok.

So I would assume that the documentation from filter should go to concatenator and filter removed [in this file](https://github.com/qgis/QGIS/blob/master/resources/function_help/json/aggregate)

**Comment by gioman** [comment]
Fixed by https://github.com/qgis/QGIS/pull/36849
