### ISSUE TITLE
QGIS 10 still missing chenyx06etrs.gsb

### ISSUE THREAD

**Issue by tgdbepe4** [qgis/QGIS#32713]
Still have the problem in QGIS 10 when opening an older project which runs well with QGIS 3.4.
<img width="321" alt="ScreenShot_20191107115354" src="https://user-images.githubusercontent.com/46052442/68383200-7bdab480-0155-11ea-9065-6b0050e0e7f2.png">

Any idea what could be the reason?

Peter

**Comment by gioman** [comment]
On Linux that grid has a slightly different name

/usr/share/proj/CHENYX06_etrs.gsb

**Comment by nyalldawson** [comment]
This will be fixed in 3.10.1

**Comment by mlechner** [comment]
please reopen this issue Still seems not be fixed:

QGIS 3.10.8 on Debian or QGIS 3.14.15 on Ubuntu:

$ ls -hal /usr/share/proj | grep -i chen
-rw-r--r--   1 root root 3,2M Feb 13  2020 CHENYX06a.gsb
-rw-r--r--   1 root root 3,2M Feb 13  2020 CHENYX06_etrs.gsb
-rw-r--r--   1 root root 3,2M Feb 13  2020 CHENYX06.gsb

But QGIS is searching for chenyx06etrs.gsb!
