### ISSUE TITLE
In 3.10 - bad allocation for 3.8 qgs - "loading" mouse cursor remains

### ISSUE THREAD

**Issue by hbgcn** [qgis/QGIS#32717]
**Describe the bug**

I described in #32661 an error:
 when opening 3.8 qgs projects with 3.10, I get a bad allocation error message.
after the bad allocation error, the mouse cursor remains a blue "loading" circle instead of the regular white triangular pointer... leading me to believe it had crashed, then exiting QGIS by closing the window bringing the crash report message seemingly confirmed it had crashed
I just found out that QGIS is still usable even after the "bad allocation" error, although the blue circle mouse pointer makes clicking on things very confusing.

The closing qgis crash erroneously led me to believe it had already crashed, but it hat not, only the loading cursor was still present. (I found out that saving the project, the closing the project only through the project menu, then exiting qgis through the project menu prevented the crash)

The circle cursor remains even when using the select tool and the information tool.

I don't know how to further assist.
I only tried doing a buffer and exporting a layer in a different CRS
Thank you

**How to Reproduce**

open 3.8 qgs project with 3.10
get bad allocation error message
mouse cursor is "loading"
message bar below still shows "loading layer xxxxxx"
qgis is usable but the mouse cursor will not change back to the regular triangular pointer

**edit** I have to add that saving the v3.8 qgs project with 3.10 corrects this issue. Also using themes also work.

**QGIS and OS versions**

QGIS version
3.10.0-A CoruÃ±a
QGIS code revision
6c816b4204
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
2.4.1
Running against GDAL/OGR
2.4.1
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
5.2.0
Running against PROJ
Rel. 5.2.0, September 15th, 2018
OS Version
Windows 10 (10.0)
Active python plugins
db_manager; 
MetaSearch; 
processing

**Additional context**

**Comment by hbgcn** [comment]
I have to add that saving the v3.8 qgs project with 3.10 corrects this issue. Also using themes also work.

**Comment by gioman** [comment]
how this differ from https://github.com/qgis/QGIS/issues/32661 ?

**Comment by hbgcn** [comment]
It doesn't really, but the other one was closed... I think there was more than one issue addressed in that one and one of them was fixed, althouth I don't exactly understand what was fixed.

**Comment by gioman** [comment]
> It doesn't really, but the other one was closed...

it was closed because ti was fixed with this patch: https://github.com/qgis/QGIS/pull/32670

wait for the next round of releases or use QGIS master.
