### ISSUE TITLE
Unable to load layers from PostgreSQL 9.6 / PostGIS using the browser

### ISSUE THREAD

**Issue by raynerhoward** [qgis/QGIS#32726]
After upgrading from QGIS 3.8.2 to 3.10.0, I am no longer able to see my tables in the QGIS Browser under PostGIS:

public --> failed to get layers
topology --> failed to get layers

I am connecting to a PostgreSQL/PostGIS database hosted via a2hosting.com and am currently unable to change schema privileges using the postgres user.

qgis.log file shows the following:

PostGIS(1): Erroneous query: SELECT l.f_table_name,l.f_table_schema,l.f_geometry_column,upper(l.type),l.srid,l.coord_dimension,c.relkind,obj_description(c.oid),array_agg(a.attname), count(CASE WHEN t.typname IN ('geometry','geography','topogeometry','raster') THEN 1 ELSE NULL END) , 1  FROM geometry_columns l,pg_class c,pg_namespace n,pg_attribute a,pg_type t WHERE c.relname=l.f_table_name AND l.f_table_schema=n.nspname AND NOT a.attisdropped AND a.attrelid=c.oid AND a.atttypid=t.oid AND a.attnum>0 AND n.oid=c.relnamespace AND has_schema_privilege(n.nspname,'usage') AND has_table_privilege('"'||n.nspname||'"."'||c.relname||'"','select') AND l.f_table_schema='public' GROUP BY 1,2,3,4,5,6,7,c.oid,11 UNION SELECT l.f_table_name,l.f_table_schema,l.f_geography_column,upper(l.type),l.srid,2,c.relkind,obj_description(c.oid),array_agg(a.attname), count(CASE WHEN t.typname IN ('geometry','geography','topogeometry','raster') THEN 1 ELSE NULL END) , 1  FROM geography_columns l,pg_class c,pg_namespace n,pg_attribute a,pg_type t WHERE c.relname=l.f_table_name AND l.f_table_schema=n.nspname AND NOT a.attisdropped AND a.attrelid=c.oid AND a.atttypid=t.oid AND a.attnum>0 AND n.oid=c.relnamespace AND has_schema_privilege(n.nspname,'usage') AND has_table_privilege('"'||n.nspname||'"."'||c.relname||'"','select') AND l.f_table_schema='public' GROUP BY 1,2,3,4,5,6,7,c.oid,11 UNION SELECT l.table_name,l.schema_name,l.feature_column,CASE WHEN l.feature_type = 1 THEN 'MULTIPOINT' WHEN l.feature_type = 2 THEN 'MULTILINESTRING' WHEN l.feature_type = 3 THEN 'MULTIPOLYGON' WHEN l.feature_type = 4 THEN 'GEOMETRYCOLLECTION' END AS type,(SELECT srid FROM topology.topology t WHERE l.topology_id=t.id),2,c.relkind,obj_description(c.oid),array_agg(a.attname), count(CASE WHEN t.typname IN ('geometry','geography','topogeometry','raster') THEN 1 ELSE NULL END) , 1  FROM topology.layer l,pg_class c,pg_namespace n,pg_attribute a,pg_type t WHERE c.relname=l.table_name AND l.schema_name=n.nspname AND NOT a.attisdropped AND a.attrelid=c.oid AND a.atttypid=t.oid AND a.attnum>0 AND n.oid=c.relnamespace AND has_schema_privilege(n.nspname,'usage') AND has_table_privilege('"'||n.nspname||'"."'||c.relname||'"','select') AND l.schema_name='public' GROUP BY 1,2,3,4,5,6,7,c.oid,11 UNION SELECT l."r_table_name",l."r_table_schema",l."r_raster_column",'RASTER',l.srid,2,c.relkind,obj_description(c.oid),array_agg(a.attname), count(CASE WHEN t.typname IN ('geometry','geography','topogeometry','raster') THEN 1 ELSE NULL END) , 1  FROM raster_columns l,pg_class c,pg_namespace n,pg_attribute a,pg_type t WHERE c.relname=l."r_table_name" AND l."r_table_schema"=n.nspname AND NOT a.attisdropped AND a.attrelid=c.oid AND a.atttypid=t.oid AND a.attnum>0 AND n.oid=c.relnamespace AND has_schema_privilege(n.nspname,'usage') AND has_table_privilege('"'||n.nspname||'"."'||c.relname||'"','select') AND l."r_table_schema"='public' GROUP BY 1,2,3,4,5,6,7,c.oid,11 ORDER BY 2,1,3 returned 7 [ERROR:  permission denied for schema topology
LINE 1: ...ometry','raster') THEN 1 ELSE NULL END) , 1  FROM topology.l...
                                                             ^
]PostGIS(1): NOTICE: WARNING:  there is no transaction in progressPostGIS(1): Unable to get list of spatially enabled tables from the databasePostGIS(1): Erroneous query: SELECT l.f_table_name,l.f_table_schema,l.f_geometry_column,upper(l.type),l.srid,l.coord_dimension,c.relkind,obj_description(c.oid),array_agg(a.attname), count(CASE WHEN t.typname IN ('geometry','geography','topogeometry','raster') THEN 1 ELSE NULL END) , 1  FROM geometry_columns l,pg_class c,pg_namespace n,pg_attribute a,pg_type t WHERE c.relname=l.f_table_name AND l.f_table_schema=n.nspname AND NOT a.attisdropped AND a.attrelid=c.oid AND a.atttypid=t.oid AND a.attnum>0 AND n.oid=c.relnamespace AND has_schema_privilege(n.nspname,'usage') AND has_table_privilege('"'||n.nspname||'"."'||c.relname||'"','select') AND l.f_table_schema='topology' GROUP BY 1,2,3,4,5,6,7,c.oid,11 UNION SELECT l.f_table_name,l.f_table_schema,l.f_geography_column,upper(l.type),l.srid,2,c.relkind,obj_description(c.oid),array_agg(a.attname), count(CASE WHEN t.typname IN ('geometry','geography','topogeometry','raster') THEN 1 ELSE NULL END) , 1  FROM geography_columns l,pg_class c,pg_namespace n,pg_attribute a,pg_type t WHERE c.relname=l.f_table_name AND l.f_table_schema=n.nspname AND NOT a.attisdropped AND a.attrelid=c.oid AND a.atttypid=t.oid AND a.attnum>0 AND n.oid=c.relnamespace AND has_schema_privilege(n.nspname,'usage') AND has_table_privilege('"'||n.nspname||'"."'||c.relname||'"','select') AND l.f_table_schema='topology' GROUP BY 1,2,3,4,5,6,7,c.oid,11 UNION SELECT l.table_name,l.schema_name,l.feature_column,CASE WHEN l.feature_type = 1 THEN 'MULTIPOINT' WHEN l.feature_type = 2 THEN 'MULTILINESTRING' WHEN l.feature_type = 3 THEN 'MULTIPOLYGON' WHEN l.feature_type = 4 THEN 'GEOMETRYCOLLECTION' END AS type,(SELECT srid FROM topology.topology t WHERE l.topology_id=t.id),2,c.relkind,obj_description(c.oid),array_agg(a.attname), count(CASE WHEN t.typname IN ('geometry','geography','topogeometry','raster') THEN 1 ELSE NULL END) , 1  FROM topology.layer l,pg_class c,pg_namespace n,pg_attribute a,pg_type t WHERE c.relname=l.table_name AND l.schema_name=n.nspname AND NOT a.attisdropped AND a.attrelid=c.oid AND a.atttypid=t.oid AND a.attnum>0 AND n.oid=c.relnamespace AND has_schema_privilege(n.nspname,'usage') AND has_table_privilege('"'||n.nspname||'"."'||c.relname||'"','select') AND l.schema_name='topology' GROUP BY 1,2,3,4,5,6,7,c.oid,11 UNION SELECT l."r_table_name",l."r_table_schema",l."r_raster_column",'RASTER',l.srid,2,c.relkind,obj_description(c.oid),array_agg(a.attname), count(CASE WHEN t.typname IN ('geometry','geography','topogeometry','raster') THEN 1 ELSE NULL END) , 1  FROM raster_columns l,pg_class c,pg_namespace n,pg_attribute a,pg_type t WHERE c.relname=l."r_table_name" AND l."r_table_schema"=n.nspname AND NOT a.attisdropped AND a.attrelid=c.oid AND a.atttypid=t.oid AND a.attnum>0 AND n.oid=c.relnamespace AND has_schema_privilege(n.nspname,'usage') AND has_table_privilege('"'||n.nspname||'"."'||c.relname||'"','select') AND l."r_table_schema"='topology' GROUP BY 1,2,3,4,5,6,7,c.oid,11 ORDER BY 2,1,3 returned 7 [ERROR:  permission denied for schema topology
LINE 1: ...ometry','raster') THEN 1 ELSE NULL END) , 1  FROM topology.l...
                                                             ^
]PostGIS(1): NOTICE: WARNING:  there is no transaction in progressPostGIS(1): Unable to get list of spatially enabled tables from the database

**Comment by gioman** [comment]
@raynerhoward  Check your permissions for the public and topology schemas (in public for example your user must have at least read permission on spatial_ref_sys and geometry_columns).

**Comment by raynerhoward** [comment]
@gioman The user has read permissions on public.spatial_ref_sys and public.geometry_columns but no permissions in the topology schema (cannot access topology.layers or topology.topology).

I have since downgraded from QGIS 3.10.0 to 3.8.3 and can now see all my tables in public and nothing (no tables) in topology (which is fine with me, not using the topology schema for anything).

Previously, I wasn't able to see any of my tables in the public schema with QGIS 3.10.0 due to the permission issue with the topology schema.  Shouldn't have prevented me though from viewing my tables in the public schema.

As you can see in the qgis.log, it wasn't letting me view tables in the public schema due to the ERROR: permission denied for schema topology.

**Comment by gioman** [comment]
I confirm the issue. Is a regression, it affects 3.10 and master and affects also the "add postgis layer" dialog.

**Comment by elpaso** [comment]
@strk CC

**Comment by strk** [comment]
I guess we'd need to have QGIS check for permissions at connection time. I'll look at it

**Comment by gioman** [comment]
it works as expected on 3.4 (and 3.8), something changed in between releases.

**Comment by strk** [comment]
Shall topology support considered as "unavailable" for those without read permissions in topology.topolgy table ? I'm thinking YES, or can anyone think of a reason why it should be considered available ?

**Comment by strk** [comment]
@raynerhoward are you able to test #32822 ?

**Comment by strk** [comment]
For the record: I filed a PostGIS ticket to grant topology metadata tables read permissions to public, which I think makes sense:
https://trac.osgeo.org/postgis/ticket/4575

**Comment by raynerhoward** [comment]
> @raynerhoward are you able to test #32822 ?

@strk Not sure, do you want me to run this python script?  https://github.com/qgis/QGIS/blob/master/tests/src/python/test_qgsproviderconnection_postgres.py

Happy to help in any way I can, but not exactly sure how to set up this python script to run the test.  I have a support ticket open with a2hosting to create a new database for testing purposes.  Or should I test against the existing database in which I received the original error message? Run the test from within QGIS 3.8.3?

**Comment by gioman** [comment]
> @strk Not sure, do you want me to run this python script? https://github.com/qgis/QGIS/blob/master/tests/src/python/test_qgsproviderconnection_postgres.py

@raynerhoward as the patch includes changes to the C++ code, it means that to the test the fix you should compile QGIS code.

**Comment by cayetanobv** [comment]
I think this issue is related and the fix applied in the same way to solve the problem: https://github.com/qgis/QGIS/issues/32483
