### ISSUE TITLE
QGIS Georeferencer issue when trying to georeference an already georeferenced image

### ISSUE THREAD

**Issue by OlivierCristol** [qgis/QGIS#32722]
In QGIS, when georeferencing an already georeferenced file, the raster is listed in the Layer panel, no error message or warning is prompted but the raster is not visible in the map.

Step 1: open georeferencer
Step 2: opn raster you want to georeference. Use a geospatial pdf
Step 3: set your transformation settings (polynomial 1, Nearest Neighbour, CRS...)
Step 4: add your reference point in the file and in the map canvas
Step 5: Start georeferencing
**Expected result**: the georeferenced file should open as a layer and be visible in the Map OR, if already georeferenced, user should be warned there's no need to georeference the file and it should be open "as is" as a raster
**Actual result:** georeference steps go as usual but when the raster is loaded in the map, it is invisible. It shows as an available layer in the layer panel but there's nothing visible in the map.
**More context:** see https://gis.stackexchange.com/questions/340857/using-qgis-georeferencer

**Comment by gioman** [comment]
@OlivierCristol arguably this is a feature request to remove the projection first, maybe with https://gdal.org/programs/gdal_edit.html

**Comment by OlivierCristol** [comment]
@gioman I don't have a strong opinion on what is the best way to address this (I am not a developer). All I can say on a end user stand point is the behavior described is very confusing. Most of the time, pdf or image files users want to overlay on their map don't come with georeference or metadata so when users follow same steps as usual and receive no error/warning or guidance, they expect a certain result. Maybe wiping out geo data from the file when a user load it in the georeferencer is a good way to do it. Detecting and informing the user that the file is already georefrenced and can be loaded "as is" as raster seems easier to me.

**Comment by roya0045** [comment]
@OlivierCristol but sometimes you have georeferenced data that might be badly georeferenced and need some tweaking. Since the georeferencer aims to simply 'correct' the projection I'm not too sure what is wrong.
From what I recall when loaded images are projetected using their size and then the data is corrected. It should still be the same procedure.

Though what you are describing with an invisible layer is possibly a projection issue, the georeferencer is finnicky and everything that is used must be in the same projection, and even then it might fail.

**Comment by gioman** [comment]
> In QGIS, when georeferencing an already georeferenced file, the raster is listed in the Layer panel, no error message or warning is prompted but the raster is not visible in the map.
> 
> Step 1: open georeferencer
> Step 2: opn raster you want to georeference. Use a geospatial pdf
> Step 3: set your transformation settings (polynomial 1, Nearest Neighbour, CRS...)
> Step 4: add your reference point in the file and in the map canvas
> Step 5: Start georeferencing


@OlivierCristol 

I tried to replicate, but I can't really replicate the issue. 

My starting point is a geotiff as I don't have a geospatial pdf at hand.

What I see is the following:

the georef tool always outputs a geotiff, regardless of the input

the georef tool do *not* allow to overwrite an already existing geotiff, so a new output is always generated.

so for me the result is always correct.

**Comment by OlivierCristol** [comment]
@roya0045 by layer invisible I meant it is there but not displaying anything. I thought it might be a projection issue but when right clicking on the layer and zoom to layer, it shows the correct map extent and location. There's just nothing on the map regardless in which order the layers are arranged.
@gioman I can't speak for geotiff. I have experienced this issue with geo referenced pdf

**Comment by gioman** [comment]
>  @gioman I can't speak for geotiff. I have experienced this issue with geo referenced pdf

so maybe the issue is just with geopdf, and maybe the issue is in GDAL and not QGIS (the QGIS georef is a GUI for GDAL). You should export your georef configs as a script and try run it from the command line. If it fails there, then is not a QGIS issue.

**Comment by nyalldawson** [comment]
Closed due to lack of feedback
