### ISSUE TITLE
Auto-zoom to selection

### ISSUE THREAD

**Issue by Ellebjerg** [qgis/QGIS#32731]
I am currently quality assuring changes to map data. In this proces the zoom to selection is a vital tool. However, it does involve a large number of mouse operations to select a feature, click zoom to selection and then often also zooming out to get a broader view of the area, where a change has been made.
It would be a great help with a tool which allows the user to use the down- and up-arrows to select the next feature in the attribute table and then have the map automatically pan to the selected feature at a preset zoom level.
I post the request here, but I will also raise it in the Danish QGIS Community to see whether other users are interesting in participating in finansing the development.

Thank you to the many developers for a great product.

Best regards
Lars Ellebjerg

**Comment by haubourg** [comment]
I think your wish has been realised since 3.8 :

https://qgis.org/en/site/forusers/visualchangelog38/#feature-browse-through-features-in-the-attribute-table-form-view

**Comment by haubourg** [comment]
Feel free to close if this is OK for you.

**Comment by Ellebjerg** [comment]
This doen not quite do it. I still need the function where the map pans to the selected feature and shows it at a fixed zoom level.

**Comment by Ellebjerg** [comment]
Sorry, now I found the automatic zoom to selected function. But I still need it to keep at a zoom level, which is not too close to the selected feature

**Comment by haubourg** [comment]
@Ellebjerg Well it seems to have landed in master :)

![image](https://user-images.githubusercontent.com/1629853/68484430-883a3c80-023d-11ea-98a3-44e8f6a4c83b.png)

**Comment by Ellebjerg** [comment]
Great!
