### ISSUE TITLE
QGIS Server WMS 'SELECTION' parameter doesn't seem to work on polylines

### ISSUE THREAD

**Issue by cfsgarcia** [qgis/QGIS#32738]
**Describe the bug**
In QGIS Server, attempting to retrieve selections from WMS using SELECTION parameter. It works on polygons and points. It doesn't work on polylines (standard ST_LineString).

**How to Reproduce**
1) Make a .qgs project in which there are point, polygon and polyline layers coming from a Postgres/Postgis database. 
2) Publish this .qgs project to QGIS server
3) Test out a selection on a polygon -> OK:
http://qgis-server/qgis_mapserv.fcgi?map=qgis/test.qgs&LAYERS=my_polygon&STYLES=default&VERSION=1.3.0&SERVICE=WMS&REQUEST=GetMap&CRS=EPSG%3A27700&SELECTION=my_polygon:21&BBOX=406746.9454984575,94159.8261255787,406998.3001678336,94275.18468962915&WIDTH=1900&HEIGHT=872
4) Test out a selection on a point -> OK: 
http://qgis-server/qgis_mapserv.fcgi?map=qgis/test.qgs&LAYERS=my_point&STYLES=default&VERSION=1.3.0&SERVICE=WMS&REQUEST=GetMap&CRS=EPSG%3A27700&SELECTION=my_point:321&BBOX=406746.9454984575,94159.8261255787,406998.3001678336,94275.18468962915&WIDTH=1900&HEIGHT=872
5) Test out a selection on a polyline-> NOK: nothing selected! : 
http://qgis-server/qgis_mapserv.fcgi?map=qgis/test.qgs&LAYERS=my_polyline&STYLES=default&VERSION=1.3.0&SERVICE=WMS&REQUEST=GetMap&CRS=EPSG%3A27700&SELECTION=my_polyline:666&BBOX=406746.9454984575,94159.8261255787,406998.3001678336,94275.18468962915&WIDTH=1900&HEIGHT=872
6) In summary: test out 3 selections-> NOK: 2 selections (polygon, point) out of 3 work! : 
http://qgis-server/qgis_mapserv.fcgi?map=qgis/test.qgs&LAYERS=my_polygon,my_point,my_polyline&STYLES=default&VERSION=1.3.0&SERVICE=WMS&REQUEST=GetMap&CRS=EPSG%3A27700&SELECTION=my_polygon:321&SELECTION=my_point:321&SELECTION=my_polyline:666&BBOX=406746.9454984575,94159.8261255787,406998.3001678336,94275.18468962915&WIDTH=1900&HEIGHT=872

**QGIS and OS versions**
QGIS LTR 3.4.9 with QGIS SERVER
POSTGRES 11.4 POSTGIS 2.4

**Comment by cfsgarcia** [comment]
Looks like it works. It's not very clear in what circumstances. 
It looks like creating a new auto-incremented column 'id' (postgis type serial), set as PK with index make it work.

**Comment by gioman** [comment]
>  It looks like creating a new auto-incremented column 'id' (postgis type serial), set as PK with index make it work.

@cfsgarcia closing?
