### ISSUE TITLE
GeoPDF - OSGeo4w setup installs wrong version of GDAL (2.4.1-1) to support GeoPDF

### ISSUE THREAD

**Issue by CharlieGIS** [qgis/QGIS#32742]
OSGeo4w installs GDAL version 2.4.1-1 but to function GeoPDF requires GDAL version 3.0 or greater. For advanced QGIS users this probably does not represent a problem as they can manually install GDAL 3.0 but for the majority of users this may be a barrier to using GeoPDF (very exciting new addition!). 
Suggest either GDAL 3.0 is added to OSGeo4w install or simple work around instructions are provided.

**Comment by SrNetoChan** [comment]
This is known. The reason is that GRASS won't work with gdal 3, yet.

**Comment by CharlieGIS** [comment]
Ok - what to do? You want to post more info here? i.e. suggested workarounds and an indication of when GDAL 3 will be compatible with GRASS?

Or I can just close the comment.

**Comment by jef-n** [comment]
https://lists.osgeo.org/pipermail/osgeo4w-dev/2019-November/003818.html ff

**Comment by roya0045** [comment]
With the release of 7.8.1 I would assume that things should be fixed in the coming weeks.
