### ISSUE TITLE
QGIS 3.10 - WMS issue

### ISSUE THREAD

**Issue by nhopton-pixel** [qgis/QGIS#32740]
When QGIS makes a WMS request it adds the current version to the User-Agent string, so in version QGIS 3.10.0 this results in "Mozilla/5.0 QGIS/3.10.0-A Coruña". This in turn causes some servers to reject requests, probably because of the "ñ" character.

In the main my WMS requests are made to the UK Environment Agency's WMS server and in QGIS 3.10 these are always rejected.

Test WMS URL: 
https://environment.data.gov.uk/spatialdata/lidar-composite-digital-surface-model-dtm-1m/wms

**Comment by elpaso** [comment]
I can confirm that is the UTF8 User-Agent causing the issue, I would say that QGIS should not send UTF8 chars in the User-Agent header, see https://tools.ietf.org/html/rfc7230#section-3.2.4

**Comment by nhopton-pixel** [comment]
Thanks for this, I wonder if there is a work-around? So far as I can see it's only possible to edit the first part of the string in network settings.

**Comment by elpaso** [comment]
No: there is no workaround.

**Comment by matself** [comment]
We had this problem when Nødebo came out. So it was anticipated.
