### ISSUE TITLE
QGIS 3.10 Cannot connect wms

### ISSUE THREAD

**Issue by granddad1** [qgis/QGIS#32746]
In version 3.10, cannot connect wms from adress: "http://services.cuzk.cz/wms/wms.asp" in the same way as in version 3.8.
Projects with wms-service from "http://services.cuzk.cz/wms/wms.asp" created in version 3.8, in version 3.10 with the same wms-linked services are not working.

**Comment by agiudiceandrea** [comment]
This is probably related to #32740

**Comment by gioman** [comment]
closing as duplicate.
