### ISSUE TITLE
Geojson Layer 'feature count' does not take into account filters 

### ISSUE THREAD

**Issue by tastrax** [qgis/QGIS#32750]
**Describe the bug**
Geojson layer with filters shows incorrect feature count in layer panel

**How to Reproduce**

http://www.rfs.nsw.gov.au/feeds/majorIncidents.json

1. Point layer above appears to be filtered by date
2. Categorise by category
3. Turn on 'show feature count'

![image](https://user-images.githubusercontent.com/8775395/68525288-2dc7db80-0324-11ea-800d-fc9f16f50e3b.png)

**QGIS and OS versions**

QGIS3.10

**Comment by roya0045** [comment]
Not a bug, the filters is applied to the symbols, but the layer still has 40 features in total.

**Comment by tastrax** [comment]
OK

**Comment by roya0045** [comment]
For more information, counting is done based on rendered features, in the case of multiple symbols( everything except the basic symbology) the base layer itself has no symbology and the symbology becomes subset. The filter is applied to those subset but the main layer 'non symbol' is applied to all features. 

This is how I understand the code, let me know if this is clearer.
