### ISSUE TITLE
Maps zooms out on editing vertex by vertex tool

### ISSUE THREAD

**Issue by Xeenych** [qgis/QGIS#32759]
Canvas magnifier is set to other than 100%. I use vertex tool to manually editing coordinates, filling values in the coordinate table. On every coordinate update canvas zooms out.

Qgis 3.10
Win 7 x64 pro

**Comment by gioman** [comment]
@Xeenych I can't confirm or I didn't understand how to replicate. A screencast would be very useful.

**Comment by Xeenych** [comment]
See this.
![1](https://user-images.githubusercontent.com/11345848/68577381-09cddc80-0481-11ea-81d2-c56a4181739e.gif)

**Comment by gioman** [comment]
> See this.

@Xeenych now I see. Magnification must be less than 50%.
