### ISSUE TITLE
Layout export generates lines in raster dem

### ISSUE THREAD

**Issue by bellanz80** [qgis/QGIS#32761]
**Describe the bug**
Hi. Given a DEM raster, and displayed as shaded on the fly, the print layout generates a line in the exported image.

**How to Reproduce**

1. Import raster DEM'
2. change the style to shading
3. open the print layout and append the hillshade map
4. export as image, (I use 300 dpi)
5. notice the lines in the exported image

**QGIS and OS versions**
QGIS 3.10 Windows 10 64 bit

**Additional context**

the problem appears with all resample (nearest, bilinear etc)
NEAR
![Uploading 3-10_near_clip.png…]()

BILINEAL
![3-10_bilineal](https://user-images.githubusercontent.com/38449926/68536893-d889cb00-031f-11ea-9962-d2f0082422e9.png)

In QGIS 2.18 it works perfectly, there is no lines.
![2-18_bilinea](https://user-images.githubusercontent.com/38449926/68536881-a0828800-031f-11ea-8bd5-db13f895f600.png)

DEM annex for tests
https://drive.google.com/file/d/1z4sQu7jEZ_2UrXcAf-8_XbA5bwv6mwQ4/view?usp=sharing

Thank's

**Comment by nyalldawson** [comment]
Please try the "Disable tiled raster export" option:

![image](https://user-images.githubusercontent.com/1829991/68566701-d56b1800-04a2-11ea-93b6-43577510b875.png)

**Comment by nyalldawson** [comment]
This is fixed in 3.10.1
