### ISSUE TITLE
QGIS3.10 - Overview frames are missing in svg export

### ISSUE THREAD

**Issue by mhabets** [qgis/QGIS#32763]
**How to Reproduce**

1. In a map layout, add 2 map frames: Map 1 (higher scale) and Map 2 (lower scale)
2. In Map 2 properties, add an Overview and select Map 1. Make sure you can see Map 1 frame inside Map 2 frame.
3. Export as svg
4. Issue: The overview frame in Map 2 frame is missing in the svg file. Note: the pdf export is fine.

**QGIS and OS versions**

QGIS version | 3.10.0-A CoruÃ±a | QGIS code revision | 6c816b4204
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Windows 10 (10.0)
Active python plugins | db_manager; MetaSearch

**Comment by gioman** [comment]
@mhabets just tested here on 3.10 on Linux, and the result is the expected one.

**Comment by mhabets** [comment]
@gioman thank you a lot for your feedback. So, may be it is a Windows only issue.
Could you please let me know the name of the layer containing the Overview frame (with Inkscape for example)?

**Comment by gioman** [comment]
works as expected also on Windows here.

**Comment by gioman** [comment]
results tested in Inkscape.

**Comment by mhabets** [comment]
@gioman Can you please *definitively* confirm that we are on the same page.
I am talking about the rectangle (or frame) showing geographic coverage of a higher scale map inside an lower scale map (called "Overview" feature in map layout).
See the red rectangle in the upper left map in this example: https://issues.qgis.org/attachments/download/8275/GISCarto_map3_JMJ45.jpg
To be 100% sure, could you please provide (from Inkscape) the name of the layer containing that rectangle in the svg file?

**Comment by gioman** [comment]
> @gioman Can you please _definitively_ confirm that we are on the same page.
> I am talking about the rectangle (or frame) showing geographic coverage of a higher scale map inside an lower scale map (called "Overview" feature in map layout).
> See the red rectangle in the upper left map in th

@mhabets yes



> To be 100% sure, could you please provide (from Inkscape) the name of the layer containing that rectangle in the svg file?

attached

[test.zip](https://github.com/qgis/QGIS/files/3837149/test.zip)

**Comment by nyalldawson** [comment]
This is only triggered when the "export as layers" option is used
