### ISSUE TITLE
missing build dependency on qgswmssourceselectbase generated header ?

### ISSUE THREAD

**Issue by landryb** [qgis/QGIS#32764]
(extracted from https://github.com/qgis/QGIS/pull/31800#issuecomment-550200854)

I'm still seeing a semi-random build failure as reported in the first comment, building 3.10 release on OpenBSD. 
```
In file included from /usr/obj/ports/qgis-3.10.0/qgis-3.10.0/src/providers/wms/qgswmsdataitems.cpp:26:
/usr/obj/ports/qgis-3.10.0/qgis-3.10.0/src/providers/wms/qgswmssourceselect.h:20:10: fatal error: 'ui_qgswmssourceselectbase.h' file not found
#include "ui_qgswmssourceselectbase.h"

```
Could this be some fallout/side-effect from https://github.com/qgis/qgis/commit/635c1b54d8025ef2c02e5fecf1537ad5ac77f4d7#diff-17c63f5441b19b50cf0d99055932fb4c ? It's as if a dependency wasnt correctly declared somewhere... but only on the wms provider. I tried fiddling with the CMakeLists.txt file to no avail, and it seems the failure is random due to some random build ordering with ninja. Help appreciated.

**Comment by landryb** [comment]
will try https://github.com/qgis/QGIS/commit/277a848300a5dba1aa36e1fad8c1f3dd2cb4bbc5 chunk for the wms provider in the meantime.

**Comment by landryb** [comment]
bits of 277a848 didnt help, automoc doesnt seem to find that src/providers/wms/qgswmsdataitems.cpp depends on the generated ui_qgswmssourceselectbase.h from ./src/ui/qgswmssourceselectbase.ui. And my cmake-fu is weak. @lbartoletti ?

**Comment by lpechacek** [comment]
I've hit the issue as well and I'm just testing the below fix. Once the build finishes, I'll drop a note here whether it it helped.

```
Fix WMS provide build failure

Heavily multithreaded QGIS build fails due to missing dependency between WMS
code and the Qt form code. This patch makes the dependency explicit.

Signed-off: Libor Pechacek <lpechacek@gmx.com>
---
 src/providers/wms/CMakeLists.txt |    6 +++++-
 1 file changed, 5 insertions(+), 1 deletion(-)

--- a/src/providers/wms/CMakeLists.txt
+++ b/src/providers/wms/CMakeLists.txt
@@ -12,6 +12,9 @@ SET (WMS_MOC_HDRS
 )
 
 IF (WITH_GUI)
+  SET(WMS_GUI_UIS
+    ../../ui/qgswmssourceselectbase.ui
+  )
   SET(WMS_GUI_SRCS
     qgswmsprovidergui.cpp
     qgswmssourceselect.cpp
@@ -29,6 +32,7 @@ IF (WITH_GUI)
   )
 ENDIF ()
 
+QT5_WRAP_UI (WMS_GUI_UIS_H  ${WMS_GUI_UIS})
 QT5_WRAP_CPP (WMS_MOC_SRCS ${WMS_MOC_HDRS})
 QT5_WRAP_CPP (WMS_GUI_MOC_SRCS ${WMS_GUI_MOC_HDRS})
 
@@ -57,7 +61,7 @@ INCLUDE_DIRECTORIES(SYSTEM
 )
 
 # static library
-ADD_LIBRARY(wmsprovider_a STATIC ${WMS_SRCS} ${WMS_MOC_SRCS})
+ADD_LIBRARY(wmsprovider_a STATIC ${WMS_GUI_UIS_H} ${WMS_SRCS} ${WMS_MOC_SRCS})
 TARGET_LINK_LIBRARIES(wmsprovider_a
   ${Qt5Xml_LIBRARIES}
   ${Qt5Core_LIBRARIES}
```
Build is running at https://build.opensuse.org/package/show/home:LPechacek:branches:Application:Geo/qgis

**Comment by lpechacek** [comment]
No luck. Builds with eight parallel jobs failed. Builds with three parallel jobs passed. Looks like the proposed change has no effect.

**Comment by lpechacek** [comment]
Excerpt from build log:
```
[  143s] + /usr/bin/make -j8 VERBOSE=1
[...]
[  147s] In file included from /home/abuild/rpmbuild/BUILD/qgis-3.10.0/src/providers/wms/qgswmsdataitems.cpp:26:0:
[  147s] /home/abuild/rpmbuild/BUILD/qgis-3.10.0/src/providers/wms/qgswmssourceselect.h:20:10: fatal error: ui_qgswmssourceselectbase.h: No such file or directory
[  147s]  #include "ui_qgswmssourceselectbase.h"
[  147s]           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[  147s] compilation terminated.
[  147s] make[2]: *** [src/providers/wms/CMakeFiles/wmsprovider_a.dir/build.make:154: src/providers/wms/CMakeFiles/wmsprovider_a.dir/qgswmsdataitems.cpp.o] Error 1
[  147s] make[2]: *** Waiting for unfinished jobs....
[...]
[  155s] [  4%] Generating ui_qgswmssourceselectbase.h
[  155s] cd /home/abuild/rpmbuild/BUILD/qgis-3.10.0/build/src/ui && /usr/lib64/qt5/bin/uic -o /home/abuild/rpmbuild/BUILD/qgis-3.10.0/build/src/ui/ui_qgswmssourceselectbase.h /home/abuild/rpmbuild/BUILD/qgis-3.10.0/src/ui/qgswmssourceselectbase.ui
[...]

[  739s] make[1]: Leaving directory '/home/abuild/rpmbuild/BUILD/qgis-3.10.0/build'
[  739s] make: *** [Makefile:166: all] Error 2
[  739s] error: Bad exit status from /var/tmp/rpm-tmp.EBDDFl (%build)
[  739s] 
[  739s] 
[  739s] RPM build errors:
[  739s]     Bad exit status from /var/tmp/rpm-tmp.EBDDFl (%build)
[  739s] 
[  739s] lamb72 failed "build qgis.spec" at Tue Nov 12 07:12:16 UTC 2019.
[  739s] 
[  739s] ### VM INTERACTION START ###
[  743s] [  730.218883] sysrq: SysRq : Power Off
[  743s] [  730.225283] reboot: Power down
[  743s] ### VM INTERACTION END ###
[  743s] 
[  743s] lamb72 failed "build qgis.spec" at Tue Nov 12 07:12:20 UTC 2019.
[  743s] 
```

**Comment by lbartoletti** [comment]
> I'm still seeing a semi-random build failure

I confirm the problem for OpenBSD.
@rhurlin Do we have the same problem on FreeBSD? ; I've always been able to built it, but since it's a random problem...

@m-kuhn We think it's a problem with the order of moc generation by ninja (@lpechacek you use ninja too?) if. Do you have any idea how to force the order of file generation?

Just for information. QT version are 5.9 for OpenBSD and OpenSuse Leap (@lpechacek  right ?)

**Comment by lpechacek** [comment]
@lbartoletti, there are no traces of ninja in the build system. The package is built with make. Regarding Qt5 versions, all details can be found at [Repology](https://repology.org/project/qt5/versions). It confirms that there is Qt 5.9 in OpenBSD, oS Leap 15.0 and Leap 15.1. HTH

**Comment by rhurlin** [comment]
@lbartoletti Until now, I am not aware of any 'ui_qgswmssourceselectbase.h file not found' error on FreeBSD. 
From time to time, there is a build stop, which does not happen again, if the build on same sources is repeated. But that is another story ...

Am I wrong on the assumption that ninja is not used by the gmake based build process on FreeBSD?

**Comment by lbartoletti** [comment]
> Am I wrong on the assumption that ninja is not used by the gmake based build process on FreeBSD?

CMake use Ninja by default except for some ports with cmake:noninja (for fortran if i'm right)

**Comment by m-kuhn** [comment]
You can specify `-GMakefile`. But if this helps it's pure luck, Makefiles also need to resolve dependencies and if there are some unspecified dependencies it might as well run things in the "wrong" order, especially if run in multiple processes (`-j` with a param >1).

**Comment by m-kuhn** [comment]
It's also unrelated to automoc. Automoc has been introduced on master only (not on 3.10).

**Comment by lbartoletti** [comment]
So maybe Qt version (>= 5.11)?

@lpechacek Do you have the possibility to try with openSUSE Leap 15.2 or Tumbleweed which have Qt 5.12.5 and Qt 5.13.1?

**Comment by m-kuhn** [comment]
I think it's this:

> Could this be some fallout/side-effect from 635c1b5#diff-17c63f5441b19b50cf0d99055932fb4c ?

The target `wmsprovider_a` is added unconditionally and without the ui dependency, it compiles qgswmsdataitem.cpp which fails if the ui part is missing.

https://github.com/qgis/QGIS/blob/master/src/providers/wms/CMakeLists.txt#L46

Can you check this pull request:

https://github.com/qgis/QGIS/pull/32824

@PeterPetrik should this library only be built if compiled with static linking?
