### ISSUE TITLE
When I saved field record, and QGIS crashed

### ISSUE THREAD

**Issue by juni1978200** [qgis/QGIS#32775]
## User Feedback

When I saved field record, and QGIS crashed

## Report Details

*Crash ID*: d7ca0d2eebb472b15590da5c965d34f63c41c7fe

*Stack Trace*
<pre>
MoveSmall memcpy.asm:511
QSortFilterProxyModel::qt_metacast :
QSortFilterProxyModel::removeRows :
QSortFilterProxyModel::sortRole :
QSortFilterProxyModel::`default constructor closure' :
QMetaObject::activate :
QAbstractItemModel::beginRemoveRows :
QgsAttributeTableModel::removeRows qgsattributetablemodel.cpp:173
QgsAttributeTableModel::featuresDeleted qgsattributetablemodel.cpp:155
QMetaObject::activate :
QgsVectorLayer::featuresDeleted moc_qgsvectorlayer.cpp:945
QgsVectorLayer::onFeatureDeleted qgsvectorlayer.cpp:4443
QMetaObject::activate :
QgsVectorLayerEditBuffer::featureDeleted moc_qgsvectorlayereditbuffer.cpp:361
QgsVectorLayerEditBuffer::commitChanges qgsvectorlayereditbuffer.cpp:637
QgsVectorLayer::commitChanges qgsvectorlayer.cpp:2940
QgisApp::saveEdits qgisapp.cpp:9378
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:373
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:373
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1542
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.4.13-Madeira
QGIS code revision: 64ad560274
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment]
> When I saved field record, and QGIS crashed

@juni1978200 there aren't enough details: please add detailed steps that lead to the crash. Also try with a new QGIS profile (and do not install any 3rd party plugins).

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
