### ISSUE TITLE
GeoJson Export Always exports MultiGeomerty types

### ISSUE THREAD

**Issue by Melegy90** [qgis/QGIS#32782]
**Bug Description**
When exporting from Shapefile to Geojson, no matter what the options in the export selected are. The result is always a Multi-geometry even tho the input is a single geometry type without any multi parts.

**How to Reproduce**
1. Add any shapefile to a an empty project
2. Right click and "save feature as"
3. Choose GeoJson type without modifying any export options

**QGIS and OS versions**

Windows 7
QGIS version 3.4.4 Madeira

**Comment by gioman** [comment]
@Melegy90 shapefiles are always opened as "multi".

**Comment by Melegy90** [comment]
> @Melegy90 shapefiles are always opened as "multi".

So this behavior is new to QGIS 3.x because this isn't the case with QGIS 2.x 
Also if this is the case then the checkbox "Enforce Multi-type" under the Geometry tab in the "Save Feature As" Dialog is invalid since it is enforced anyway.

**Comment by gioman** [comment]
> > 
> 
> So this behavior is new to QGIS 3.x because this isn't the case with QGIS 2.x

yes it is.
