### ISSUE TITLE
QGIS crash when rotate one poligon in edition the active layer.

### ISSUE THREAD

**Issue by caleto** [qgis/QGIS#32781]
**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

==============================================

Versión de QGIS | 3.8.3-Zanzibar | Revisión del código de QGIS | 685d8b15d2
-- | -- | -- | --
Compilado contra Qt | 5.11.2 | Ejecutándose contra Qt | 5.11.2
Compilado contra GDAL/OGR | 2.4.1 | Ejecutándose contra GDAL/OGR | 2.4.1
Compilado contra GEOS | 3.7.2-CAPI-1.11.0 | Ejecutándose contra GEOS | 3.7.2-CAPI-1.11.0 b55d2125
Versión del cliente PostgreSQL | 10.8 | Versión de SpatiaLite | 4.3.0
Versión de QWT | 6.1.3 | Versión de QScintilla2 | 2.10.8
Compilado contra PROJ | 5.2.0 | Ejecutándose contra PROJ | Rel. 5.2.0, September 15th, 2018
Versión del SO | Windows 10 (10.0) |   |

**Comment by gioman** [comment]
already fixed, please wait the next round of releases.
