### ISSUE TITLE
qgis_local_server.ServerProcessError: Could not locate server binaries

### ISSUE THREAD

**Issue by strk** [qgis/QGIS#32785]
Running `make check` after a successful build I get:
```
Traceback (most recent call last):
  File "/usr/src/qgis/qgis-do-not-override-source-files/tests/src/python/test_qgis_local_server.py", line 44, in <module>
    MAPSERV = getLocalServer()
  File "/usr/src/qgis/qgis-do-not-override-source-files/tests/src/python/qgis_local_server.py", line 693, in getLocalServer
    srv = QgisLocalServer(FCGIBIN)
  File "/usr/src/qgis/qgis-do-not-override-source-files/tests/src/python/qgis_local_server.py", line 290, in __init__
    'Make sure one of the sets of servers is available on PATH'
qgis_local_server.ServerProcessError:
#----------------------------------------------------------------#
Could not locate server binaries
Find 'spawn-fcgi':
Find 'lighttpd':



Make sure one of the sets of servers is available on PATH

#----------------------------------------------------------------#

CMake Error at PyQgsLocalServer.cmake:15 (MESSAGE):
  Test failed: 1
```

I think testsuite should skip tests that cannot be run and WARN about the fact, so that user can improve test coverage following warning instructions.

Also, if server was NOT built (I'm not sure this was the case) there should not even be a warning but just skipping of tests for components that were not built.

\cc @m-kuhn

**Comment by m-kuhn** [comment]
Yes, sounds good to me.
Since I never run `make check` and always only targetted individual tests on for everything else trust the CI this hasn't been a priority here.

**Comment by elpaso** [comment]
@strk yeah, please keep in mind that you probably the first one to run `make check`, AFAIK we all use `ctest` on individual tests or run C++ tests from QtCreator or run python tests manually.

**Comment by strk** [comment]
> keep in mind that you probably the first one to run `make check`

This is scary, to me, as it means completely outsourcing quality assurance of codebase to external infrastructure which cannot be replicated locally.

PS: `make check` is just a wrapper to `ctest`, just running all tests, at the moment. By GNU standards it's meant to be what developers run to verify their changes didn't break functionality covered by tests..

**Comment by m-kuhn** [comment]
It's not that scary. It's all dockerized.
And it's hard to get `make check` to run fine because of all the external infrastructure tests like postgres etc.

**Comment by elpaso** [comment]
> > keep in mind that you probably the first one to run `make check`
> 
> This is scary, to me, as it means completely outsourcing quality assurance of codebase to external infrastructure which cannot be replicated locally.

That's not correct: we do regularly run tests locally, just in another way.

But I agree that it is important to be able to run **all** the tests  locally, the problem with some provider tests (postgres for example) is that the development environment can be very different, we have used env vars to set paths to executable and other things in the tests, have a look to tests/src/python/test_provider_postgres.py for an example.

For providers like oracle of mssql it's even worse because they require dockers or VMs to be installed  to run.


> 
> PS: `make check` is just a wrapper to `ctest`, just running all tests, at the moment. By GNU standards it's meant to be what developers run to verify their changes didn't break functionality covered by tests..

**Comment by strk** [comment]
Hard doesn't mean impossible. We had Gnash testsuite also using
external assets like streaming servers and external testsuites,
the testsuite runner used env variables to enable/disable tests
and configure external assets.

**Comment by m-kuhn** [comment]
Yes. Hard doesn't mean impossible.
But hard with limited direct benefit often triggers a "better work on easier things with higher impact first" reaction for me.

If you a developer or a client of someone is willing to put the required effort into it, I don't have a problem with that at all.

**Comment by gioman** [comment]
@strk still relevant?
