### ISSUE TITLE
QGIS crash when closing the application

### ISSUE THREAD

**Issue by MaxDragonheart** [qgis/QGIS#32780]
Every time I quit QGIS the software give me back a crash. This is the traceback:

Crash ID: 56776c067d5c4c396ceb7d9652ae10f294434880

Stack Trace

QGraphicsItem::update :
QgsAdvancedDigitizingDockWidget::setCadEnabled qgsadvanceddigitizingdockwidget.cpp:169
QWidget::event :
QDockWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:373
QCoreApplication::notifyInternal2 :
QWidgetPrivate::hideChildren :
QWidgetPrivate::hide_helper :
QWidget::setVisible :
QWidgetPrivate::close_helper :
QWidget::~QWidget :
QgisApp::`vector deleting destructor' :
main main.cpp:1543
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.4.13-Madeira
QGIS code revision: 64ad560274
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment]
> Every time I quit QGIS the software give me back a crash

@MaxDragonheart please try with a new QGIS profile (and do not install any 3rd party plugins).

**Comment by m-kuhn** [comment]
I think this has already been fixed a couple of days ago.
Would you have the possibility to install a nightly build of 3.4 with osgeo4w and check if the issue is fixed? https://github.com/qgis/QGIS/pull/32715

**Comment by MaxDragonheart** [comment]
@gioman I've installed saturday a clean copy of QGIS using OSGeo and nothing is changed.

@m-kuhn ok, I try it

**Comment by m-kuhn** [comment]
> @gioman I've installed saturday a clean copy of QGIS using OSGeo and nothing is changed.

You will still need to create a new profile folder, reinstalling the application does not clear the profile folder as far as I know, does it?

**Comment by MaxDragonheart** [comment]
@gioman Yes, it's right. I've deleted manually all folders of the previous installation before start a new installation.

**Comment by gioman** [comment]
> Yes, it's right. I've deleted manually all folders of the previous installation before start a new installation.

@MaxDragonheart including "C:\Users\yourusername\AppData\Roaming\QGIS\QGIS3\profiles"?

**Comment by MaxDragonheart** [comment]
Yes @gioman 
I've the same version on Ubuntu 18.04 and with it I've no problems

**Comment by nirvn** [comment]
@MaxDragonheart , can you make a screencast (GIF) demonstrating the crash you see on your machine? I can't replicate here either, you'll need to provide more details.

**Comment by MaxDragonheart** [comment]
@nirvn unfortunately I can't. I've uninstalled QGIS via OSGeo and reinstalled it with a deep clean of all previous installation files. I don't know why, but now, I can't install OSGeo "Adavanced install" but only "Express Desktop Install". On Ubuntu 18.04 I have zero problems. Maybe something is corrupted on WIndows 10 after yet another update of Windows.

**Comment by gioman** [comment]
> @nirvn unfortunately I can't. 

@MaxDragonheart can't do a screencast of QGIS crashing?

>I've uninstalled QGIS via OSGeo and reinstalled it with a deep clean of all previous installation files. 

if there is a bug, a "deep clean" of installation files would not help. Is it more frequent for issues to be caused by bad/legacy configs and 3rd party plugins that are *not* stored in the install tree and are not removed when uninstalling.

>I don't know why, but now, I can't install OSGeo "Adavanced install" but only "Express Desktop Install"

just remove manually the osgeo4w installation folder.

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
