### ISSUE TITLE
Slow network drive listing on windows blocking QGIS loading

### ISSUE THREAD

**Issue by NathanW2** [qgis/QGIS#32797]
If you are not connected to a network but have network drives attached Windows has a massive long timeout on network drives and will slow QGIS loading right now.

We need to load any network drives in the browser using a background thread.

**Comment by gomyhr** [comment]
This issue seems to be the same as #33164 (which is newer, but has more activity).

**Comment by scottshambaugh** [comment]
I believe this was fixed in PR https://github.com/qgis/QGIS/pull/43416, and can now be closed.
