### ISSUE TITLE
Problem for choosing a CRS when importing a delimited text file

### ISSUE THREAD

**Issue by sigmoe** [qgis/QGIS#32792]
**Describe the bug**

The widget for choosing a CRS when importing a delimited text file is not enabled.

**How to Reproduce**

1. Use the Data source manager, enable the Delimited Text tab.
2. Choose a file (with geometry columns), set the right configuration
3. In the Geometry Definition, try to choose the Geometry CRS, using the CRS icon. 
-> The Select CRS widget appears, but you can't select anything in this widget. The widget is not enabled.

**QGIS and OS versions**

Version de QGIS
3.4.13-Madeira
Révision du code
Révision du code
Compilé avec Qt
5.11.2
Utilisant Qt
5.11.2
Compilé avec GDAL/OGR
2.4.1
Utilisé avec GDAL/OGR
2.4.1
Compilé avec GEOS
3.8.0-CAPI-1.13.1
Utilisé avec GEOS
3.8.0-CAPI-1.13.1 
Version du client PostgreSQL
11.5
Version de SpatiaLite
4.3.0
Version de QWT
6.1.3
Version de QScintilla2
2.10.8
Compilé avec PROJ
5.2.0
Fonctionne avec PROJ
Rel. 5.2.0, September 15th, 2018

**Additional context**

The problem wasn't there in QGIS v3.4.8

**Comment by gioman** [comment]
duplicate of https://github.com/qgis/QGIS/issues/31753
