### ISSUE TITLE
Layout broken in Searching in form

### ISSUE THREAD

**Issue by 3nids** [qgis/QGIS#32796]
In attribute table, searching in form.
The layout seems broken
![image](https://user-images.githubusercontent.com/127259/68612964-ff7e0380-04bd-11ea-86eb-eb0644a12d99.png)
The last row should be expanded

affects at least 3.4.13

**Comment by gioman** [comment]
> affects at least 3.4.13

@3nids regression?

**Comment by 3nids** [comment]
Also in a 1 month old 3.9.
Hard to say regression or not, I'd say so but not sure

**Comment by geomondego** [comment]
@gioman @3nids in 3.4.12 it is working

![Screenshot from 2019-11-11 19-37-04](https://user-images.githubusercontent.com/4389239/68615389-e162d400-04ba-11ea-8402-279b093868f0.png)

**Comment by 3nids** [comment]
@geomondego thanks for the feedback. I had a very quick look at the code, and I suspect it works well with tabs since the tabs are in embed in one column, while probably when you don't have tabs it takes 3.

**Comment by gioman** [comment]
@3nids status of this one?
