### ISSUE TITLE
Server GetMap response missing labels in latest master on no GUI server

### ISSUE THREAD

**Issue by tudorbarascu** [qgis/QGIS#32791]
On Debian Testing Server (no GUI) the labels are gone for GetMap WMS requests. I've bisected the culprit to 845894b31318ff8bb5eb094cd4a4785b7440fb24 .

What's interesting is that the same project works on my Debian Testing Laptop that includes X-Server (Desktop).

I can reproduce this on another debian testing server.

**Comment by gioman** [comment]
> I've bisected the culprit to [845894b](https://github.com/qgis/QGIS/commit/845894b31318ff8bb5eb094cd4a4785b7440fb24)

@mhugo

**Comment by tudorbarascu** [comment]
Linked to https://github.com/qgis/QGIS/pull/30747

**Comment by mhugo** [comment]
@tudorbarascu Can you reproduce the problem for whatever the project is ? Or is it limited to some symbology options enabled ?

**Comment by mhugo** [comment]
@tudorbarascu Did you notice something special in the logs ? Any "QPainter not active" error messages  or similar ?

**Comment by tudorbarascu** [comment]
@mhugo will try and see now.. and debug as properly as I can..

**Comment by tudorbarascu** [comment]
@mhugo Just noticed it can only be replicated when parallel rendering in Server is activated. Everything works ok if it's deactivated. Rebuilding in debug mode currently and I'll post any findings right away.

**Comment by tudorbarascu** [comment]
No errors show up in the logs.. although I'm in Debug mode.. The image gets rendered without errors but the output is missing the label.

**Comment by tudorbarascu** [comment]
@mhugo It can be replicated on different projects and on different systems but you need to enable server parallel rendering. For instance, if you use https://github.com/elpaso/qgis3-server-vagrant, update packages and add the ```"Environment="QGIS_SERVER_PARALLEL_RENDERING=true"``` line in the ```/etc/systemd/system/qgis-server-fcgi\@.service``` and restart the labels will be missing from the helloworld project at ```http://localhost:8080/cgi-bin/qgis_mapserv.fcgi?MAP=/qgis-server/projects/helloworld.qgs```. 

@elpaso @pblottiere FYI  Maybe it would be wise to enable parallel rendering on the server testing framework as there are were some bugs introduced in the past that passed the CI because the parallel rendering is disabled there.

**Comment by tudorbarascu** [comment]
@mhugo It's fixed! Thanks!

**Comment by mhugo** [comment]
@tudorbarascu Very good to read, and thanks for your tests
