### ISSUE TITLE
Default labels setting as MS Shell Dlg looks gross

### ISSUE THREAD

**Issue by NathanW2** [qgis/QGIS#32798]
What is with the default label settings using MS Shell Dlg.  Looks gross, maybe we should make it smarter and set it to something to nicer!

**Comment by roya0045** [comment]
Its not just label, all default fonts are MS Shell Dlg 2, though I think this should be a feature request to add a variable to change all default fonts (unless this is what the variable in application font does and not only change the display font).

**Comment by NathanW2** [comment]
Yeah. I am creating tickets based on feedback from Nyall workshop he is
running so I will come back and flesh this out more after we are done

**Comment by Llaves** [comment]
Any updates on this?
Thanks
