### ISSUE TITLE
Hide "File properties" from right click menu for PostGIS raster tables in browser

### ISSUE THREAD

**Issue by FelisPimeja** [qgis/QGIS#32806]
![image](https://user-images.githubusercontent.com/874261/68678383-e5e8c480-056e-11ea-97ed-9e1f9d51bb1f.png)

It makes no sense for database table and leads to _System properties_ dialog on Windows 10.
QGIS 3.10 - 3.11 Win10 x64

By the way, thanks for all your great work and especially for improved PostGIS Raster support!

**Comment by alexbruy** [comment]
Still true in latest 3.10/master?

**Comment by jgrocha** [comment]
![Screenshot from 2020-07-26 17-47-35](https://user-images.githubusercontent.com/163681/88484689-4fc3c580-cf68-11ea-95dd-5c40cde1100a.png)

Unable to reproduce with current version.
