### ISSUE TITLE
WMS Download of capabitilies failed: Error transferring getCapabilities document

### ISSUE THREAD

**Issue by zimmicz** [qgis/QGIS#32804]
**WMS capabilities transfer fails**

When I try to connect to the WMS service located at http://services.cuzk.cz/wms/local-KM-wms.asp?service=WMS&request=getCapabilities, I get the error below and no layers are retrieved from that service. Yet `curl` downloads the underlying xml document just fine. 

```
WARNING    Download of capabilities failed: Error transferring http://services.cuzk.cz/wms/local-KM-wms.asp?SERVICE=WMS&REQUEST=GetCapabilities - server replied: Bad Gateway
```

**How to Reproduce**

Add new WMS/WMTS connection, use http://services.cuzk.cz/wms/local-KM-wms.asp?service=WMS&request=getCapabilities for URL. Try to expand the layer list of the newly added connection, you get "Failed to download capabilities".

**QGIS and OS versions**

QGIS version | 3.10.0-A Coruña | QGIS code revision | 6c816b4204
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 10.10 (Ubuntu 10.10-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Linux Mint 19.2
Active python plugins | qgis2web; db_manager; processing

**Comment by gioman** [comment]
Does it work on 3.4? Duplicate of https://github.com/qgis/QGIS/issues/32740 ?

**Comment by zimmicz** [comment]
It does work on 3.4. Seems to be the duplicate of above mentioned #32740.
