### ISSUE TITLE
Treat IntegerList, Integer64List, RealList as QVariantList

### ISSUE THREAD

**Issue by Meibes** [qgis/QGIS#32805]
At the moment QGIS does treat StringLists as QVariantLists, which means that you can edit a real list in the attribute table and query items with array_get(). IntegerLists, Integer64Lists, RealLists are not dealt as QVariantLists but as simple QString in the form of '(itemCount:item1,item2,item3,...)'. This makes querying affected columns not easy and may cause data corruption if the layer is exported or edited and saved.

here is an example in geojson:

```
{
  "type": "FeatureCollection",
  "features": [
    {
      "geometry": {
        "type": "Point",
        "coordinates": [
          12,
          52
        ]
      },
      "properties": {
        "integer_list": [
          1,
          3,
          5,
          7
        ],
        "string_list": [
          "another",
          "one",
          "bites",
          "the",
          "dust"
        ],
        "real_list": [
          1.1,
          1.2,
          1.3
        ],
        "object_list": [
          {
            "attr1": true,
            "attr2": "obejct1"
          },
          {
            "attr1": false,
            "attr2": "object2"
          }
        ]
      },
      "type": "Feature"
    }
  ]
}
```

I also attached some screenshots

![properties](https://user-images.githubusercontent.com/26258451/68656313-da2add00-0531-11ea-9a95-5ff080189b94.png)
![attribute_table](https://user-images.githubusercontent.com/26258451/68656315-da2add00-0531-11ea-99a4-1fbb0b1f2b63.png)

**Comment by nirvn** [comment]
@Meibes , send your thanks to @nyalldawson , he implemented this a while back.
