### ISSUE TITLE
Delete PostGIS Raster table not working in Browser panel 

### ISSUE THREAD

**Issue by FelisPimeja** [qgis/QGIS#32809]
![image](https://user-images.githubusercontent.com/874261/68681188-05362080-0574-11ea-9290-583fd7ba381c.png)

Trying to delete PostGIS raster from Browser panel through right click menu.
Getting error in Messages console:
`CRITICAL    Qt : QFile::remove: Empty or null file name`
And table is not deleted.
No problems deleting raster table from DB Manager at the same time.
QGIS 3.10 - 3.11 Win10 x64

**Comment by gioman** [comment]
@FelisPimeja did it worked in a previous release?

**Comment by FelisPimeja** [comment]
@gioman:
QGIS 3.9.0 - same issue as described
QGIS 3.6.3, 3.8.1 - no PostGIS raster functionality, but deleting raster table works without problems.
