### ISSUE TITLE
slow network connectivity timeouts when loading a project

### ISSUE THREAD

**Issue by littlezaide** [qgis/QGIS#32816]
If there is no network connectivity (e.g. no available PostGIS connection) it takes ages to load a QGIS project—the timeouts are very long, and each layer has to be cancelled manually. Is there any way to get QGIS to load a project with shorter timeouts when it's known that network layers are missing/unavailable?

**How to Reproduce**

Say we're loading a project with many Postgres connections. 

1. load the project
2. wait for timeouts on each missing layer
3. cancel each manually with a mouse click

Seems to be a problem on recent 3.10 OSX and Linux versions, and has been an issue since at least 2.12.

**Comment by gioman** [comment]
> and each layer has to be cancelled manually

I had the impression that this has been addressed recently, but now I'm not 100% sure. @nyalldawson

**Comment by gioman** [comment]
@littlezaide I think this is ok now with the new missing layers dialog.
