### ISSUE TITLE
QGIS (3.x) Freeze after use input() method on python terminal

### ISSUE THREAD

**Issue by kylefelipe** [qgis/QGIS#32815]
in a python script if used input() method qgis just freeze!

S.O Debian Buster
Qgis Version: 3.4.13 AND 3.10.0
Python Version: 3.7

**Comment by roya0045** [comment]
I believe this should be normal as input would stall the main thread. This doesn't seem like a bug but more of a question for the mailing list.

**Comment by nyalldawson** [comment]
This isn't a bug -- if you want users to enter strings, you'll need to use a graphical approach such as  QInputDialog. The simple python input() function is only designed for use in console based applications.

**Comment by kylefelipe** [comment]
Thx @nyalldawson !
