### ISSUE TITLE
Add option to Settings to not prompt to save scratch layers on exit

### ISSUE THREAD

**Issue by g-sherman** [qgis/QGIS#32814]
**Feature description.**
The prompt/warning about saving scratch layers can get in the way when developing plugins that must close and reopen QGIS.

**Additional context**
![image](https://user-images.githubusercontent.com/494282/68699475-9df67d00-052f-11ea-8339-479f11b41e2e.png)

An option to disable this prompt we be great :)

**Comment by roya0045** [comment]
I would assume that the best option would be to have a project specific variable to disable that in the cases when people have 'processing' projects.

Otherwise having such a global setting would be a bad idea IMO.

**Comment by nyalldawson** [comment]
@g-sherman 

This is already possible -- you just need to set the "skipMemoryLayersCheck" custom property on the layer to true

**Comment by g-sherman** [comment]
@nyalldawson That works for me---didn't see that in the api; was looking for a specific method in QgsProject. Now if you could solve my QGIS crash on exit, that would be great :)

Thanks.

**Comment by nyalldawson** [comment]
The crash on exit issue should be fixed in the latest round of releases... Do you still see it?

**Comment by g-sherman** [comment]
@nyalldawson Yes, I'm setting snapping config on a couple of layers and on exit it crashes during reset of the snapping config during a call to QgsProject.mapLayers inside the reset method. Was planning to file a bug on it...
![image](https://user-images.githubusercontent.com/494282/68710570-41ea2380-0544-11ea-85c4-0196fc0138a5.png)
