### ISSUE TITLE
QGIS Crashing when adding fields to an existing shp file

### ISSUE THREAD

**Issue by TonyShep** [qgis/QGIS#32819]
## User Feedback

Adding more than one new field to a SHP file.  I have managed to get this to replicate.  Add one field, save. OK. Add a second field QGIS crash.  Have closed, rebooted and get the same behavioue.

## Report Details

**Crash ID**: [fe1921e12f4432d0751980f7cd89aee94750f14c]('https://github.com/qgis/QGIS/search?q=fe1921e12f4432d0751980f7cd89aee94750f14c&type=Issues')

**Stack Trace**
<pre>
memcpy_repmovs memcpy.asm:115
QSortFilterProxyModel::qt_metacast :
QSortFilterProxyModel::removeRows :
QSortFilterProxyModel::sortRole :
QSortFilterProxyModel::`default constructor closure' :
QMetaObject::activate :
QAbstractItemModel::beginRemoveRows :
QgsAttributeTableModel::removeRows qgsattributetablemodel.cpp:177
QgsAttributeTableModel::loadLayer qgsattributetablemodel.cpp:449
QMetaObject::activate :
QMetaObject::activate :
QgsVectorLayer::updateFields qgsvectorlayer.cpp:3610
QgsVectorLayerUndoCommandAddAttribute::redo qgsvectorlayerundocommand.cpp:317
QUndoStack::push :
QgsVectorLayerEditBuffer::addAttribute qgsvectorlayereditbuffer.cpp:274
</pre>

**QGIS Info**
QGIS Version: 3.10.0-A Coruña
QGIS code revision: 6c816b4204
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment]
@TonyShep Please try with a new QGIS profile (don't install any 3rd party plugins).

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
