### ISSUE TITLE
Drop multiple fields with the drop field(s) tool from Graphical Modeler

### ISSUE THREAD

**Issue by noenandre** [qgis/QGIS#32818]
**Describe the bug**

It's possible to select multiple field(s) too drop if you run the Drop field(s) algorithm from the Processing Toolbox. It's only possible to drop a field at a time if you use the same algorithm from Graphical Modeler.

**How to Reproduce**
Open a new Graphical Modeler, and add a layer with the columns "layer" and "path" (leftover after a "Merge vector layers" algorithm). Add the drop field(s) algorithm. Write a list off columns to drop. The result will be something like this:

`{ COLUMN: '[\'layer\',\'path\']', INPUT: '(...)', OUTPUT: 'TEMPORARY_OUTPUT' }  
Field “['layer','path']” does not exist in input layer`

**QGIS version**
3.10.0

**Comment by nyalldawson** [comment]
Seperate the field names with a ";" character

**Comment by noenandre** [comment]
Really thought I had tried every combinations of delimiters, brackets, and quotation marks. Thanks anyway!   
Let me start over again...  can i ask for a Feature Request for a graphical way to add multiple fields?

**Comment by alexbruy** [comment]
It is not possible to add fields in a way other than manual, as at desing-time we don't know which fields layer has.

**Comment by noenandre** [comment]
Yes of course, you are right. 
But just a tooltip would have helped immensely. The output field already has a placeholder - "[enter name if final result"].  Would it be possible to add a placeholder that states "[separate multiple fields with a semicolon]"?

**Comment by AlisterH** [comment]
> Yes of course, you are right. But just a tooltip would have helped immensely. The output field already has a placeholder - "[enter name if final result"]. Would it be possible to add a placeholder that states "[separate multiple fields with a semicolon]"?

Yes - when not using the modeller, the gui shows the selected fields to drop with a comma separator, so naturally that is what users try to use.  
I thought I'd tried everything to get it to work, adding quotes in various ways, then I came here to file a bug report, before finding this ticket...
