### ISSUE TITLE
Composer grid displayed on map canvas

### ISSUE THREAD

**Issue by Jean-Roc** [qgis/QGIS#32821]
**Describe the bug**

When editing a layer in some projects with 3.10, a composer grid is automatically displayed on the canvas at a fixed scale (1:13) :

* it acts as a snapping grid
* it is displayed whether snapping is enabled or not
* it is superseding any snap options

I have not been able to found any parameters in the projects or the user profile that can be link to this behavior.

**How to Reproduce**

I have not been able to reproduce it on purpose on a new project, it appears on several computers/profiles (even a brand new). Due the scale condition delaying the discovery, I can't pinpoint any particular user action.

**QGIS and OS versions**

Discovered after a trial with 3.10, these projects now display the same on 3.4

**Additional context**

![canvas_grid](https://user-images.githubusercontent.com/736212/68742582-d0b47a00-05f0-11ea-850a-8ce09b42871b.PNG)

**Comment by andreasneumann** [comment]
Hi,
This is not a bug. It is a feature. One of your layers has a geometry precision defined:

Layer Properties --> Last Tab "Digitizing" --> "Geometry Precision"

As soon as one layer in your project has the geometry precision defined, QGIS will display this grid and in the concerned layer, it will snap to this grid when you edit data in this layer.

Note that this grid is purely on screen and won't be exported or printed.

**Comment by andreasneumann** [comment]
However, I have to say, I have troubles on my machine to get the grid displaying. I don't get the grid once I set the geometry precision setting.

@m-kuhn  - maybe you can help?

**Comment by m-kuhn** [comment]
You have

- to zoom in close enough
- have an edit tool (node tool, add feature tool, ...) enable

**Comment by andreasneumann** [comment]
Ah - right.

I see crosses, and not circles like @Jean-Roc - is this version dependent or configurable?

**Comment by Jean-Roc** [comment]
thanks andreas, this is it !  A precision has been set on one common layer, setting it back to default and closing/reopening the edition session brings back the default behavior.

**Comment by m-kuhn** [comment]
I think it's also crosses for @Jean-Roc , that's just a screenshot "issue".

**Comment by andreasneumann** [comment]
Thanks for your explanations @m-kuhn !
