### ISSUE TITLE
[FEATURE] Add "justify" label alignment on line features

### ISSUE THREAD

**Issue by Xeenych** [qgis/QGIS#32826]
**Feature description.**
I want to add a line with automatic justified letter spacing as described here:
https://gis.stackexchange.com/questions/283996/create-line-label-with-automatic-justified-letter-spacing-in-qgis

![1](https://user-images.githubusercontent.com/11345848/68755793-12a5e600-061a-11ea-9027-903c14f366aa.png)

**Comment by pjshelton** [comment]
Duplicate of #13541

**Comment by gioman** [comment]
Closing as duplicate.
