### ISSUE TITLE
Label letter and word spacing broken in QGIS 3.10

### ISSUE THREAD

**Issue by Xeenych** [qgis/QGIS#32825]
Looks like introduction of kerning in 3.10 has broken letter and word spacing in labels.

In QGIS 3.10 if letter rspacing is set to something other than 0, then letter's interval shrinks or expands depending on zoom level.
Label size is set to map units.
Map projection is EPSG;3857
Layer projection id EPSG:3857

The attached gif-video shows difference in v3.4 and v3.10
https://yadi.sk/d/A4GRvsg6AJgG8A

Also notice, that in 3.4 the label is shown even if it is partially visible, but in 3.10 it disappears.
"Allow truncated labels" option is enabled in both projects

**Comment by gioman** [comment]
> Also notice, that in 3.4 the label is shown even if it is partially visible, but in 3.10 it disappears.
> "Allow truncted labels" option is enabled in both projects

@Xeenych Please file a separate ticket for this.

**Comment by gioman** [comment]
> Looks like introduction of kerning in 3.10 has broken letter and word spacing in labels.

@nyalldawson is this confirmed/already reported?

**Comment by nyalldawson** [comment]
No, I can't confirm -- all working correctly here and in the (many) unit tests. We'll need a project which demonstrates this issue to reproduce.

**Comment by Xeenych** [comment]
Here is the project
[test.zip](https://github.com/qgis/QGIS/files/3849885/test.zip)

**Comment by andreasneumann** [comment]
Ok - the question is:
what units are the letter and word spacing in?

I don't have a unit choice for those properties.

@nyalldawson : can we really assume that letter and word spacing inherits the units from the label size property? If yes, then I agree that this is broken. If not, then it would be useful being able to set units for these properties.

**Comment by Xeenych** [comment]
In QGIS 3.4 it was assumed that letter spacing an font size units are the same. Both settings were in the same section.

**Comment by Xeenych** [comment]
What version number this fix will be available at?
