### ISSUE TITLE
QGIS 3.10 "A Coruña" displays as "A CoruÃ±a" on Windows 10

### ISSUE THREAD

**Issue by scottshambaugh** [qgis/QGIS#32820]
**Describe the bug**
The ene (ñ) in A Coruna (A Coruña) does not display correctly on my machine, showing up as "Ã±". [Stackoverflow suggests](https://stackoverflow.com/questions/23922562/%c3%91-characters-showing-as-%c3%83%c2%b1) that this is because the characters are being rendered with Latin-1 encoding rather than UTF-8 encoding.

**How to Reproduce**

This manifests immediately on startup, after the splash screen closes and the main window opens:
![image](https://user-images.githubusercontent.com/14363975/68727360-703a2400-0581-11ea-8330-78bc30ede1f8.png)

**QGIS and OS versions**

QGIS version
3.10.0-A CoruÃ±a
QGIS code revision
6c816b4204
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
2.4.1
Running against GDAL/OGR
2.4.1
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
5.2.0
Running against PROJ
Rel. 5.2.0, September 15th, 2018
OS Version
Windows 10 (10.0)
Active python plugins
db_manager; 
MetaSearch

**Additional context**

None.

**Comment by jef-n** [comment]
Fixed in f8eeaabe6
