### ISSUE TITLE
Scrape GIS data to find sites that match certain criteria

### ISSUE THREAD

**Issue by theoryshaw** [qgis/QGIS#32837]
Hi I'm an architect (the building kind) that has been practicing open source architecture for a number of years.

All our 'blueprints' are open source and hosted on github: 
https://github.com/OpeningDesign

Visual Gallery: http://openingdesign.com/gallery/

We have a number of projects we've done in the past, residences, multiple family, etc.

Since we spent so much time developing these projects, it would be awesome if we could redevelopment them again, on another similar site.

The problem is, however, to manually find a site with the same (or similar) criteria (size of lot, setbacks, topography changes, etc.) as the original site would be near impossible.

Would be awesome if we could search/scrape GIS data to narrow down a list of candidate sites that matched the characteristics/criteria of the original site.

Relatively doable?

**Comment by m-kuhn** [comment]
Hi, QGIS is a tool that offers a wide variety of tools for different purposes - you probably know already as an architect.

It offers a wide variety of tools that can be used to perform an analysis like the one you are describing here. I think what you are currently looking for is but how to leverage existing functionality in QGIS for your use case.

I would recommend to raise this question on https://gis.stackexchange.com/ or on the [QGIS user mailing list](https://www.qgis.org/en/site/getinvolved/mailinglists.html), where you have a higher chance of finding some people to discuss this idea and the requirements than on this (rather technical) issue tracker here.

**Comment by gioman** [comment]
Or maybe what is needed/asked is a custom made plugin that facilitates some specific tasks for the specific use case.

**Comment by theoryshaw** [comment]
Thanks Guys for the replies!  Will check these other channels out as well.  Basically wanted to ask here to gauge how doable this was.  Would like to potentially drum up some development funding, if such an approach was relatively attainable.

**Comment by roya0045** [comment]
@theoryshaw I'm a simple contributor, but I feel like this is too specific to be in QGIS. This is dependent on far too many things (source of data,, attribute management, processing, etc) that are too specific. For a plugin this would be fine, but for integration in the program as a core element this is too much, I feel (I may be wrong). 

I feel like this would be the equivalent of someone going to see you just to ask for an extremely intricate furniture piece since you can do plans.

**Comment by gioman** [comment]
>  Basically wanted to ask here to gauge how doable this was. Would like to potentially drum up some development funding, if such an approach was relatively attainable.

it is certainly doable, the point is that it seems too specific to be added to core QGIS (also because in QGIS you have all the geoprocessing tools that would allow you to create a workflow/model to get the result you need). This seems more likely to fit a custom QGIS plugin. Closing?

**Comment by theoryshaw** [comment]
Sounds great.  Will do. 
If anyone's interested in such a project, ping me at ryan@openingdesign.com

Peace!

**Comment by theoryshaw** [comment]
Will plan on making it open source as well.  Is there a repo dedicated to QGIS scripts, or should we just start our own specific to this project?
Cheers.

**Comment by gioman** [comment]
>  If anyone's interested in such a project, ping me at [ryan@openingdesign.com](mailto:ryan@openingdesign.com)

have a look also to the commercial support page you find in qgis.org site.
