### ISSUE TITLE
Make build more reproducible

### ISSUE THREAD

**Issue by stoecker** [qgis/QGIS#32836]
For many reasons in modern packaging it's important to get a build reproducible, i.e. always produce the same result.

In openSUSE we have thus a patch for qgis to reach that:
```
diff --git a/scripts/ts2appinfo.py b/scripts/ts2appinfo.py
index 5fadd30e30..a9018a26c3 100644
--- a/scripts/ts2appinfo.py
+++ b/scripts/ts2appinfo.py
@@ -57,7 +57,7 @@ except AttributeError:
 
 app = QCoreApplication(argvb)
 
-for qm in glob(sys.argv[1] + "/output/i18n/qgis_*.qm"):
+for qm in sorted(glob(sys.argv[1] + "/output/i18n/qgis_*.qm")):
     translator = QTranslator()
     translator.load(qm)

```
Please apply this (i.e. add sorted()), so we can drop the patch.

See also https://build.opensuse.org/package/show/Application:Geo/qgis

**Comment by jef-n** [comment]
Already fixed in 33d0c3d6542f9
