### ISSUE TITLE
Cannot specify options in QgsDataSourceURI

### ISSUE THREAD

**Issue by strk** [qgis/QGIS#32832]
The `options` parameter to QgsDatasourceURI is ignored, by code.
See https://github.com/qgis/QGIS/pull/32822#issuecomment-553437143

This issue is to add support for it, or discuss why it should be discarded
(I tried to use it to set current user)

\cc @jef-n

**Comment by jef-n** [comment]
see https://github.com/qgis/QGIS/pull/32822#issuecomment-553447843

**Comment by strk** [comment]
Closing as "ignored by design", due to:
`QgsDebugMsg( QStringLiteral( "backend debug options ignored" ) );` being found in code
