### ISSUE TITLE
QGIS Server: GetFeatureInfo unable to retrieve feature's properties if key is int8

### ISSUE THREAD

**Issue by jgrocha** [qgis/QGIS#32844]
**Describe the bug**

Two Postgresql tables, with the same contents, but one as key `int4` and another `int8`. With first table, `GetFeatureInfo` request works. With the later `GetFeatureInfo` works, but does not include the feature's properties on the result.

First table:

```
CREATE TABLE infraestruturas.infra_agere2018_linha_rede_agua (
	id int4 NOT NULL,
	geom geometry(MULTILINESTRING, 3763) NULL,
        (...)
	material varchar(40) NULL,
	CONSTRAINT infra_agere2018_linha_rede_agua_pk PRIMARY KEY (id)
);
```

Request with int4 key: properties are included.

```json
{
  "features": [
    {
      "bbox": [
        -24196.728,
        209637.607,
        -24149.961,
        209698.801
      ],
      "geometry": {
        "coordinates": [
          [
            [
              -24196.728,
              209698.801
            ],
            [
              -24149.961,
              209637.607
            ]
          ]
        ],
        "type": "MultiLineString"
      },
      "id": "Rede de Água Agere (2018).10437",
      "properties": {
        "Comprimento": 77.0,
        "Diâmetro": 90.0,
        "Estado operacional": "ABERTA",
        "Freguesia": "BRAGA S VICENTE",
        "Função": "DISTRIBUICAO",
        "Material": "PVC",
        "Sistema": "PRINCIPAL",
        "Subsistema": "RA_GUADALUPE",
        "Zmc": "RA_STAMARGARIDA",
        "ano_de_ins": "1987",
        "estado_de_": "_ng_",
        "id": 10437,
        "ipid": 82947.0,
        "observacoe": "RA"
      },
      "type": "Feature"
    }
  ],
  "type": "FeatureCollection"
}
```

Second table:

```
CREATE TABLE infraestruturas.infra_agere2018_linha_rede_agua_int8 (
	id int8 NOT NULL,
	geom geometry(MULTILINESTRING, 3763) NULL,
        (...)
	material varchar(40) NULL,
	CONSTRAINT infra_agere2018_linha_distribuicao_agua_pkey PRIMARY KEY (id)
);
```

Response with int8 key (properties are not included)

```json
{
  "features": [
    {
      "bbox": [
        -24196.728,
        209637.607,
        -24149.961,
        209698.801
      ],
      "geometry": {
        "coordinates": [
          [
            [
              -24196.728,
              209698.801
            ],
            [
              -24149.961,
              209637.607
            ]
          ]
        ],
        "type": "MultiLineString"
      },
      "id": "Rede de Água Agere int8 (2018).0",
      "properties": null,
      "type": "Feature"
    }
  ],
  "type": "FeatureCollection"
}
```

**How to Reproduce**

Just create or use an Postgresql table with an int8 primary key, and try a `GetFeatureRequest` using that table.

**QGIS and OS versions**

Running QGis version 3.11.0-Master

**Additional context**

The error in [qgspostgresprovider.cpp](https://github.com/qgis/QGIS/blob/59292b47c7768a954dbe1a5734be44be5317fefe/src/providers/postgres/qgspostgresprovider.cpp#L584) is reported in debug mode:
```
src/providers/postgres/qgspostgresprovider.cpp:584 : (whereClause) [0ms] FAILURE: Key values for feature 10437 not found.
```

The key is not of type `PktInt`. It is treated as `PktFidMap`.

**Comment by elpaso** [comment]
I wonder if this is really a server issue, I suspect that the bug is in the provider.

**Comment by jef-n** [comment]
Does server cover that PktFidMap feature ids are temporary only (ie. only persist during the life time of the provider)?

**Comment by elpaso** [comment]
> Does server cover that PktFidMap feature ids are temporary only (ie. only persist during the life time of the provider)?

Is that used in this case? `id` is a valid PK on a single field.

**Comment by jef-n** [comment]
> Is that used in this case? `id` is a valid PK on a single field.

see jgrocha's comment above:

> The key is not of type PktInt. It is treated as PktFidMap.

**Comment by jgrocha** [comment]
The key, in the Postgresql provider, is a single column. The problem is that it is mapped to `PktFidMap`, but it isn't a `PktFidMap` key.

It works well in QGIS Desktop. The primary key is well detected and everything works. It only fails with `GetFeatureInfo` requests to QGIS Server. That's when the key is mapped to `PktFidMap`. But it is a normal `int8` key.

**Comment by elpaso** [comment]
> > Is that used in this case? `id` is a valid PK on a single field.
> 
> see jgrocha's comment above:
> 
> > The key is not of type PktInt. It is treated as PktFidMap.

Yeah, I saw that but quickly looking at the code (maybe too quickly) I had the impression that it was used for multi-column PKs and `id` looks a pretty standard PK to me (but there is probably a type check somewhere).

**Comment by jef-n** [comment]
> Yeah, I saw that but quickly looking at the code (maybe too quickly) I had the impression that it was used for multi-column PKs and `id` looks a pretty standard PK to me (but there is probably a type check somewhere).

We use negative feature ids for uncommited new features - so while feature ids of `qint64` are enough for `int4` keys, it's not enough for `int8`.   But this issue also applies to any other int4+ key (strings, multi-column, etc).

**Comment by jgrocha** [comment]
On QGIS Desktop, the key is identified and it is just one field.

```python
>>> layer_int8 = QgsProject.instance().mapLayersByName("Rede de Água Agere int8 (2018)")[0]
>>> provider = layer_int8.dataProvider()
>>> provider.storageType()
'PostgreSQL database with PostGIS extension'
>>> layer_int8.primaryKeyAttributes()
[0]
```

**Comment by jgrocha** [comment]
> We use negative feature ids for uncommited new features - so while feature ids of `qint64` are enough for `int4` keys, it's not enough for `int8`. But this issue also applies to any other int4+ key (strings, multi-column, etc).

Hum... now I understand the behaviour...

**Comment by jgrocha** [comment]
> > Yeah, I saw that but quickly looking at the code (maybe too quickly) I had the impression that it was used for multi-column PKs and `id` looks a pretty standard PK to me (but there is probably a type check somewhere).
> 
> We use negative feature ids for uncommited new features - so while feature ids of `qint64` are enough for `int4` keys, it's not enough for `int8`. But this issue also applies to any other int4+ key (strings, multi-column, etc).

An alternative would be the usage of a phantom column, of the exactly same type, for uncommitted new features (instead of using the same column, with negative numbers). But I'm just thinking out loud. I'll have to read the code carefully. I don't fell comfortable to change such an important part of the provider.

**Comment by jef-n** [comment]
> An alternative would be the usage of a phantom column, of the exactly same type, for uncommitted new features (instead of using the same column, with negative numbers). But I'm just thinking out loud. I'll have to read the code carefully. I don't fell comfortable to change such an important part of the provider.

The feature id is not necessarily tied to attributes (eg. for shape files).

**Comment by jgrocha** [comment]
> > An alternative would be the usage of a phantom column, of the exactly same type, for uncommitted new features (instead of using the same column, with negative numbers). But I'm just thinking out loud. I'll have to read the code carefully. I don't fell comfortable to change such an important part of the provider.
> 
> The feature id is not necessarily tied to attributes (eg. for shape files).

That's true for some providers. But for Postgresql, the feature id is the primary key. Do we need to keep the same logic in the Postgresql provider?

**Comment by jef-n** [comment]
> That's true for some providers. But for Postgresql, the feature id is the primary key. Do we need to keep the same logic in the Postgresql provider?

But it's true for all features - outside of the provider everything revolves around feature ids.  That said, GetFeatureInfo does not - so all this shouldn't matter.  I was thinking we were trying to get a feature with an id we previously got from another incarnation of the layer and hence with a different fid map (maybe from a different server process).

**Comment by espinafre** [comment]
@jgrocha , can you still reproduce the problem? I've tested this with master at 909dd311080678b43669b593f70642ec2978f378 and didn't see any issues. Here is what I did:

1. Create two new PostgreSQL tables (PostgreSQL 12) and populate them:

```sql
CREATE TABLE public.tb_int4 (
    id integer NOT NULL PRIMARY KEY,
    attr character varying(32),
    geom geometry(Point,4674)
);

INSERT INTO tb_int4 VALUES (1, 'campo int4, id 1', '0101000020421200002D56B304E6AA50C07DCFE7EC68AC12C0');
INSERT INTO tb_int4 VALUES (2, 'campo int4, id 2', '0101000020421200009D84DED8B6A750C0F99C7688F12F0DC0');
INSERT INTO tb_int4 VALUES (-1, 'campo int4, id -1', '010100002042120000FCEA7EAA406350C045EE3145E0E110C0');

CREATE TABLE public.tb_int8 (
    id bigint NOT NULL PRIMARY KEY,
    attr character varying(32),
    geom geometry(Point,4674)
);
INSERT INTO tb_int8 VALUES (1, 'campo int8, id 1', '010100002042120000D3BE82BC60804BC04B077F02D31411C0');
INSERT INTO tb_int8 VALUES (2, 'campo int8, id 2', '010100002042120000CC92A1AC9DC94BC0A97E031A0C1114C0');
INSERT INTO tb_int8 VALUES (-1, 'campo int8, id -1', '010100002042120000ED48DF56CC534BC09D4C699F26AB13C0');
```
2. Create a new project, add those two tables (on my local system, I can access the database without any authentication), and save it as, say, teste_qgis_server.qgz , remembering to mark those two layers as published in the Project Properties -> QGIS Server -> WFS Capabilites before saving.
3. Run `qgis_mapserver -p teste_qgis_server.qgz`

On another computer, open a QGIS Desktop, create a new project, add a new WFS layer pointing to the computer hosting the qgis_mapserver we've just lauched. This way, I can query and see the attributes of both layers (tb_int8 and tb_int4), with positive and negative PKs, bigint and ordinary integer, so I cannot reproduce your issue.

**Comment by jgrocha** [comment]
Obrigado @espinafre for your recent contributions related to Postgresql.

I need to test this issue carefully, because it is non deterministic (as far as I've noticed). Sometimes the feature's details associated with a non int primary keys are successful retrieved, but sometimes it fails.

For very small datasets, like the one you used, you will not notice the problem. I noticed this problem on a production QGIS Server, with a few hundred layers and large tables (more than 100k, but less than 1M rows). It happens less frequently on smaller tables.

But hopefully, this might have already been solved. I'll test this on the May 1st holiday and I'll report back. 

Thank you for looking into this.

**Comment by jgrocha** [comment]
Confirmed with current master (3.15.0-Master) with a table with a 'numeric' type id. The GetFeatueInfo does not retrieve the features' attributes, as expected.

**Comment by elpaso** [comment]
@jgrocha is this related with (and maybe fixed by) https://github.com/qgis/QGIS/pull/41137 ?

**Comment by jgrocha** [comment]
Thanks for updating the issue.
Seems related. I'll recover my test environment for this and test it. It was not failing always, so it is not so easy to check. But looks quite promising!

**Comment by jgrocha** [comment]
Unable to reproduced the issue with current master.  Cool! Thanks @elpaso 🏆
