### ISSUE TITLE
The coordinate bound preview map widget's countries layer isn't styled anymore

### ISSUE THREAD

**Issue by nirvn** [qgis/QGIS#32853]
**Describe the bug**

For some time now, the coordinate bound preview map widget's countries layer isn't styled anymore. Every time a CRS selection dialog pops up, the polygons are styled with a different color.

**How to Reproduce**

1. Launch QGIS
2. Open the project properties dialog's CRS panel (by clicking on the status bar's CRS button)
3. Notice the countries polygons' color in the preview map widget
4. Close the project  properties dialog
5. Re-open the dialog's CRS panel (via status bar gain)
6. Notice the countries polygons' color has changed
7. Repeat ad vitam æternam

**QGIS and OS versions**

Affecting at least QGIS 3.10 and master.

**Additional context**

**Comment by alexbruy** [comment]
Seems was fixed in a059c367d956fab80a0c8590c379da58afaec16c
