### ISSUE TITLE
Crash on new project/exit when setting snapping in python code

### ISSUE THREAD

**Issue by g-sherman** [qgis/QGIS#32867]
## User Feedback

Clicking on New Project or exiting QGIS causes crash.

I'm setting snapping config on a couple of layers and it crashes during reset of the snapping config during a call to QgsProject.mapLayers inside the reset method.

Here is my code:

        snap_config = QgsSnappingConfig()
        snap_config.setEnabled(True)
        snap_config.setType(QgsSnappingConfig.VertexAndSegment)
        snap_config.setUnits(QgsTolerance.Pixels)
        snap_config.setTolerance(tolerance)
        snap_config.setIntersectionSnapping(True)
        snap_config.setMode(QgsSnappingConfig.SnappingMode.AdvancedConfiguration)
        lyr_settings = QgsSnappingConfig.IndividualLayerSettings(
            True,
            QgsSnappingConfig.SnappingType.Segment,
            tolerance,
            QgsTolerance.Pixels)
        snap_config.setIndividualLayerSettings(self.lyr, lyr_settings)
        QgsProject.instance().setSnappingConfig(snap_config)

If I remove the snapping code, all is fine.

## Report Details

*Crash ID*: 22b690f3fc4a1e2af64fb7c25bbbfa93fbb1ee32

*Stack Trace*
<pre>
QgsProject::mapLayers :
QgsSnappingConfig::reset :
QgsProject::clear :
QgisApp::closeProject :
QgisApp::fileNew :
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.4.2-Madeira
QGIS code revision: commit:22034aa070
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.3.2
Running against GDAL: 2.3.2

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by g-sherman** [comment]
Also happens with QGIS 3.10

**Comment by nirvn** [comment]
I think passing on the project instance in the snapping config constructor should prevent your crash.

That being said, the snapping config code could do with a few null pointer checks.

Also, it might make sense to attach project to snapping config when calling QgsProject::setSnappingConfig(...).

**Comment by g-sherman** [comment]
@nirvn Good catch---I should have realized that was the cause, but another set of eyes is good!  Thanks!

**Comment by nirvn** [comment]
Your welcome.
