### ISSUE TITLE
QGIS 3.10 Win64 GeoJSON from URL error 

### ISSUE THREAD

**Issue by floju** [qgis/QGIS#32861]
QGIS 3.10 Win64 reports an error while opening the GeoJSON from this URL:
https://data-tiris.opendata.arcgis.com/datasets/almzentren-1
(in QGIS 3.10 Linux/64 Deb/Ubuntu it works!) 

2019-11-13T13:30:04     INFO    Ferner Layer : Lade https://opendata.arcgis.com/datasets/cd1b86196f2e4f14aeae79269433a499_0.geojson, bitte warten …

2019-11-13T13:30:04     CRITICAL    Ungültige Datenquelle : https://opendata.arcgis.com/datasets/cd1b86196f2e4f14aeae79269433a499_0.geojson ist keine gültige Datenquelle oder wird nicht erkannt 

2019-11-13T13:30:04     WARNING    Kann https://opendata.arcgis.com/datasets/cd1b86196f2e4f14aeae79269433a499_0.geojson nicht öffnen.(SSL certificate problem: unable to get local issuer certificate)

**Comment by nirvn** [comment]
@floju , your error has to do with the fact that your Windows system has no certificate authority bundle file (i.e. curl-ca-bundle.crt), which is needed by curl (and in turn gdal) to open HTTPS connections.

You can add such a file by following the instructions here: https://curl.haxx.se/docs/sslcerts.html

@jef-n , this actually raises a valid issue with the QGIS osgeo4w (and I assume the derived standalone installer) whereas the curl library doesn't ship with a certificate authority bundle. This means that any libraries relying on libcurl to connect to HTTPS sites will error out.

**Comment by gioman** [comment]
> this actually raises a valid issue with the QGIS osgeo4w (and I assume the derived standalone installer) whereas the curl library doesn't ship with a certificate authority bundle.

so this is the reason  why on every installation on Windows the users get SSL certificates errors on start, when connecting to services, etc?

**Comment by nirvn** [comment]
Could well be.

**Comment by nirvn** [comment]
I'm not using windows much. If you have those errors, try the steps linked to above to add a ca bundle onto your system and see if the errors are gone.

**Comment by jef-n** [comment]
> @jef-n , this actually raises a valid issue with the QGIS osgeo4w (and I assume the derived standalone installer) whereas the curl library doesn't ship with a certificate authority bundle. This means that any libraries relying on libcurl to connect to HTTPS sites will error out.

updated to curl 7.67.0 (built with OpenSSL 1.1 and WinSSL)

**Comment by nirvn** [comment]
@jef-n , that was fast, thanks. 

Closing this issue.
