### ISSUE TITLE
QGis Crashes When Using the Search feature on "Layer Properties" window

### ISSUE THREAD

**Issue by jeffloun** [qgis/QGIS#32869]
h2. User Feedback

Tried to use the search bar on the layer properties dialog. Seems to happen every time I type more than 2 letters in the search bar:
![image](https://user-images.githubusercontent.com/16547710/68879191-d6c45c80-06bd-11ea-9953-532395d87d2c.png)

h2. Report Details

*Crash ID*: 851f40cbaa72d7e49963d30443f362cbeffbd432

*Stack Trace*
<pre>
QgsOptionsDialogHighlightTree::searchText :
QgsOptionsDialogHighlightWidget::searchHighlight :
QgsMapUnitScaleDialog::getMapUnitScale :
QMetaObject::activate :
QMetaObject::activate :
QWidgetLineControl::finishChange :
QWidgetLineControl::insert :
</pre>

*QGIS Info*
QGIS Version: 3.6.0-Noosa
QGIS code revision: commit:58734527ab
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.0
Running against GDAL: 2.4.0

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by gioman** [comment]
@jeffloun 3.6.0 is *very* old and is old end of life (no updates for such release). Please try again wit the latest 3.4 or 3.10.

**Comment by nirvn** [comment]
Already fixed, please upgrade.
