### ISSUE TITLE
Instalacion de Qgis 3.10 en RedHat

### ISSUE THREAD

**Issue by FabianJimenezEsparza** [qgis/QGIS#32875]
**Upgrade Qgis 2.14.1 to 3.10.x**

Actualmente cuento con Qgis 2.14.1 en un servidor Linux RedHat 7.3, sin embargo, no he podido hacer el upgrade por medio de rpm o hacer la instalacion inicial por este mismo medio, ya que marca dependencias infinitas que aun teniendolos en un repositorio local, me sigue marcando el error.

Tendra algun repositorio para la version Qgis 3.10 o alguna documentacion donde me pueda basar para hacer dicha instalacion.?

Por otro lado, es posible instalar la version 3.10 en un servidor RedHat 7.??

De antemano muchas gracias.

**Additional context**

**Comment by gioman** [comment]
@FabianJimenezEsparza Hi. can I ask kindly to make this question in the users or developers mailing list? thanks.
