### ISSUE TITLE
QGIS 3.10 hangs with Exception/Bad Allocation when using plot layout with 2nd Cross type Grid

### ISSUE THREAD

**Issue by Palatkik** [qgis/QGIS#32889]
If using a plot Layout with map added that uses TWO grids then the 2nd grid type cannot be changed from Solid to Cross type on the drop down menu of QGIS 3.10. The program hangs with 
Exception/Bad Allocation error . 

Also if opening old projects made in earlier versions of QGIS that have plot Layout using TWO grids where both grids use Cross type grids, then QGIS 3.10 cannot open the project and hangs with same Exception/Bad Allocation error . 

Only fix in 3.10 is to have second grid in Plot Layout using Solid type grid. This error has only been noticed since update to 3.10.

**QGIS 3.10 and Win10 64 versions**

**Comment by gioman** [comment]
@Palatkik can you please attach a sample project that shows the issue?

**Comment by Palatkik** [comment]
@gioman I have attached a sample project I just made with this error. Hope this helps.

[TEST3.1_2ndGridCross_FAIL.zip](https://github.com/qgis/QGIS/files/3851834/TEST3.1_2ndGridCross_FAIL.zip)

**Comment by nyalldawson** [comment]
This should be already fixed in master and for 3.10.1
