### ISSUE TITLE
QGIS 3.10 crash when closed

### ISSUE THREAD

**Issue by atsyplenkov** [qgis/QGIS#32885]
Hi!

QGIS 3.10 always crashes on exit. Don't know what to do with it.

Best,
Anatoly

## Report Details

**Crash ID**: [881fde7e6ba24e2202b36b2ef5e94068333c6a3a]('https://github.com/qgis/QGIS/search?q=881fde7e6ba24e2202b36b2ef5e94068333c6a3a&type=Issues')

**Stack Trace**
<pre>
osgeo::proj::datum::Datum::conventionalRS :
osgeo::proj::datum::Datum::conventionalRS :
osgeo::proj::datum::Datum::conventionalRS :
OGRSpatialReference::~OGRSpatialReference :
OGRSpatialReference::~OGRSpatialReference :
GDALRegister_GenBin :
GDALRegister_GenBin :
QgsGdalProvider::closeCachedGdalHandlesFor qgsgdalprovider.cpp:436
QgsGdalProvider::~QgsGdalProvider qgsgdalprovider.cpp:489
QgsGdalProvider::`scalar deleting destructor' :
QgsRasterPipe::~QgsRasterPipe qgsrasterpipe.cpp:58
QgsRasterLayer::~QgsRasterLayer qgsrasterlayer.cpp:137
QgsRasterLayer::`vector deleting destructor' :
QgsMapLayerStore::removeMapLayers qgsmaplayerstore.cpp:160
QgsMapLayerStore::removeMapLayers qgsmaplayerstore.cpp:121
QgsMapLayerStore::removeAllMapLayers qgsmaplayerstore.cpp:203
QgsProject::clear qgsproject.cpp:793
QgisApp::closeProject qgisapp.cpp:11881
QgisApp::fileExit qgisapp.cpp:5676
QWidget::event :
QgisApp::event qgisapp.cpp:1928
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QWidgetPrivate::close_helper :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processCloseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1598
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.0-A Coruna
QGIS code revision: 6ffa89eb3e
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
@atsyplenkov please try with a new QGIS profile (do not install any 3rd party plugin after creating the new profile).

**Comment by roya0045** [comment]
Is the plugin autosave activated?

**Comment by atsyplenkov** [comment]
> @atsyplenkov please try with a new QGIS profile (do not install any 3rd party plugin after creating the new profile).

@gioman Thanks a lot. This is really solves the problem.
