### ISSUE TITLE
Repeated popup dialog during lost db connections makes QGIS unusable

### ISSUE THREAD

**Issue by planemad** [qgis/QGIS#32899]
**Describe the bug**

When a connection to a postgres database becomes unavailable, QGIS repeatedly attempts to connect with a popup dialog asking for credentials for the unavailable connection. The repeated dialogs blocks any other interface action and essentially makes  QGIS unusable till the connection is restored.

Possibly same as https://github.com/qgis/QGIS/issues/17128 which was closed for lack of feedback

**How to Reproduce**

1. Open a postgres datasource running locally and and load a layer from it
2. Terminate the local postgres server
3. In QGIS attempt to pan or interact with the map canvas

![new3](https://user-images.githubusercontent.com/126868/68977518-6ce3aa00-07c6-11ea-9008-f03e62b6c24b.gif)

**QGIS and OS versions**

QGIS version | 3.10.0-A Coruña | QGIS code revision | 6c816b4204
-- | -- | -- | --
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3

**Additional context**

This is a scenario i encounter often in my development environment where postgres is running inside a docker container and QGIS is loading data from it. Whenever the container is restarted to test updates, i can no longer use QGIS till postgres on docker is running again which could take 10-15 minutes.

I can see how in most cases it would be pretty rare to frequently lose a connection to a database, but for those that use postgres in docker development environment or anyone remotely connected to a database on a bad network, this dialog can be pretty frustrating. Sometime the easiest workaround is to restart QGIS to make it usable again.

An expected behaviour would be an option to suppress the popup dialog for the rest of the session.

**Comment by roya0045** [comment]
I would guess that the optimal UX thing would be to have a warning, and a symbol beside the layer, if its a credential issue this would be solved by this popup and if its a connection issue qgis could ping the url from time to time or the use could force a ping. This is just an idea.

**Comment by planemad** [comment]
> if its a credential issue this would be solved by this popup and if its a connection issue qgis could ping the url from time to time or the use could force a ping.

If theres a an easy way to distinguish between a credential and connection issue, this does sound like the ideal behaviour 👍

**Comment by elpaso** [comment]
Like this? https://github.com/qgis/QGIS/pull/32546

**Comment by Komzpa** [comment]
It should not be asking for password for refused connection at all.

**Comment by planemad** [comment]
This is amazing, looks like https://github.com/qgis/QGIS/pull/32546 definitely addresses the bug of qgis being unusable.

> It should not be asking for password for refused connection at all.

To me it seems like this behavior might require some more discussion and could be scoped as a new enhancement ticket.

**Comment by gioman** [comment]
> This is amazing, looks like #32546 definitely addresses the bug of qgis being unusable.

@planemad so closing?

**Comment by Komzpa** [comment]
Yes, I've spinned up #32909 to address the credentials-are-not-unavailable-server issue.
