### ISSUE TITLE
Save fails on PostGIS tables containing a generated ("GENERATED AS") column

### ISSUE THREAD

**Issue by AEMPhil** [qgis/QGIS#32898]
**Describe the bug**
When a PostGIS layer contains a generated column, on a PostgreSQL 12 server, saving edits to the table fails.

**How to Reproduce**
1. In a clean PostGIS database on PostgreSQL 12 ( I use a docker container with [PostgreSQL12.0 and PostGIS 3.0](https://hub.docker.com/layers/kartoza/postgis/12.0/images/sha256-3e7a5c46a1b496eab21d0867df6ac92d0d5c542f94e4505dcf729fa6ea9aa539) ), create a new spatial table with a generated column:
```SQL
CREATE TABLE test_gen_col (
  id SERIAL PRIMARY KEY,
  geom GEOMETRY('Polygon', 4326) NOT NULL,
  cent GEOMETRY('Point') GENERATED AS ( ST_Centroid(geom) ) STORED
);
```
2. In QGIS Desktop, add the new table as a PostGIS layer
3. toggle editing
4. create a new polygon
5. save edits
6. see "Commit error"

![image](https://user-images.githubusercontent.com/1293613/68976379-4409e780-07bb-11ea-8b58-098bc101a1d0.png)

**QGIS and OS versions**
QGIS 3.10 on Windows 10

**Additional context**
In the example provided, the generated column uses a spatial function, but this problem also exists for generated functions that refer to any other column in the table.

**Comment by masp** [comment]
Hi @AEMPhil, while investigating this, I was able to reproduce it with a slightly different query:
```
CREATE TABLE test_gen_col (
  id SERIAL PRIMARY KEY,
  geom GEOMETRY('Polygon', 4326) NOT NULL,
  cent GEOMETRY('Point') GENERATED ALWAYS AS ( st_centroid(geom) ) STORED
);
```

Is this the correct statement you're trying to use?

**Comment by AEMPhil** [comment]
Yes, that is correct; sorry for the mis-report. 
Note that the same issue exists with Identity columns as well (`GENERATED AS IDENTITY`)

**Comment by espinafre** [comment]
The following doesn't error out with the latest master commit (81911c1 at this time); I believe it is true for 3.12 as well (but I didn't check):

```sql
CREATE TABLE test_identity_pk (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  geom GEOMETRY('Polygon', 4326) NOT NULL 
);
```
