### ISSUE TITLE
Crash on closing

### ISSUE THREAD

**Issue by brunolemke** [qgis/QGIS#32895]
## User Feedback

When closing down

## Report Details

**Crash ID**: [881fde7e6ba24e2202b36b2ef5e94068333c6a3a]('https://github.com/qgis/QGIS/search?q=881fde7e6ba24e2202b36b2ef5e94068333c6a3a&type=Issues')

**Stack Trace**
<pre>
osgeo::proj::datum::Datum::conventionalRS :
osgeo::proj::datum::Datum::conventionalRS :
osgeo::proj::datum::Datum::conventionalRS :
OGRSpatialReference::~OGRSpatialReference :
OGRSpatialReference::~OGRSpatialReference :
GDALRegister_GenBin :
GDALRegister_GenBin :
QgsGdalProvider::closeCachedGdalHandlesFor qgsgdalprovider.cpp:436
QgsGdalProvider::~QgsGdalProvider qgsgdalprovider.cpp:489
QgsGdalProvider::`scalar deleting destructor' :
QgsRasterPipe::~QgsRasterPipe qgsrasterpipe.cpp:58
QgsRasterLayer::~QgsRasterLayer qgsrasterlayer.cpp:137
QgsRasterLayer::`vector deleting destructor' :
QgsMapLayerStore::removeMapLayers qgsmaplayerstore.cpp:160
QgsMapLayerStore::removeMapLayers qgsmaplayerstore.cpp:121
QgsMapLayerStore::removeAllMapLayers qgsmaplayerstore.cpp:203
QgsProject::clear qgsproject.cpp:793
QgisApp::closeProject qgisapp.cpp:11881
QgisApp::fileExit qgisapp.cpp:5676
QWidget::event :
QgisApp::event qgisapp.cpp:1928
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QWidgetPrivate::close_helper :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processCloseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1598
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.0-A Coru�a
QGIS code revision: 6ffa89eb3e
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by roya0045** [comment]
Do you have the autosave plugin active?

**Comment by gioman** [comment]
> Do you have the autosave plugin active?

@brunolemke 
In other words also try with a new QGIS profile and no 3rd party plugins installed.

**Comment by brunolemke** [comment]
I don’t ever remember an auto save plugin.
The QGIS file saved OK but crashed on closing.
I will check for a plug-in.
Bruno

Sent  by Bruno

On 18 Nov 2019, at 9:28 pm, Giovanni Manghi <notifications@github.com> wrote:

Do you have the autosave plugin active?

@brunolemke
In other words also try with a new QGIS profile and no 3rd party plugins installed.

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
