### ISSUE TITLE
qgis Corunna version not loading with qgis_app.dll error

### ISSUE THREAD

**Issue by ColinN14** [qgis/QGIS#32893]
When the Corunna version loads it cretates a 'could not load qgis_app.dll could not be found' error message.
I have startewd it with the Dependency walker and uploaded the log file. Qgis did work for a short period until I ran a windows update. I am running Windows 10 home version 10.0.18362

[qgis_app.log](https://github.com/qgis/QGIS/files/3852510/qgis_app.log)

**Comment by gioman** [comment]
local issue?

**Comment by ColinN14** [comment]
I believe so


________________________________

**Comment by roya0045** [comment]
Usual dependency issues, though any missing dependency seem to cause this. It can be tricky to fix.

**Comment by jef-n** [comment]
> Usual dependency issues, though any missing dependency seem to cause this. It can be tricky to fix.

Not there there is an odd circular dependency - triggered by `opencl.dll` - between `c:\windows\system32\API-MS-WIN-CORE-SYNCH-L1-2-0.DLL` and `c:\windows\system32\KERNEL32.DLL`.  And it's not even the `opencl.dll` we ship.
