### ISSUE TITLE
mapCanvas().scene().items() causes crash in Qgis 3.10

### ISSUE THREAD

**Issue by dgreenewalt** [qgis/QGIS#32894]
the line:
`gList = self.iface.mapCanvas().scene().items()`
Causes Qgis 3.10 to freeze and crash.  This line of code is fine in version 3.8

Adding VertexMarkers is still working properly, but it is no longer possible to generate a list of graphics on the scene using the above line.  From the list I want to delete certain graphics (vertex markers or rubber bands).

**Comment by nyalldawson** [comment]
This is already fixed in master and for 3.10.1

**Comment by Gustry** [comment]
Duplicate of https://github.com/qgis/QGIS/issues/32700

**Comment by dgreenewalt** [comment]
Thank you!  I can wait for 3.10.1    : )
