### ISSUE TITLE
UX: shut down database reported as credential mismatch

### ISSUE THREAD

**Issue by Komzpa** [qgis/QGIS#32909]
Spin-off #32899.

1. Create layers from DB table.
2. Disconnect laptop from network with database.
3. Get tons of "invalid credentials" boxes all over the screen.
4. This happens for layers:
![image](https://user-images.githubusercontent.com/810638/69007976-28871400-0956-11ea-893b-971f2b3cc6d5.png)

5. This happens for non-created databases even if you just click them in Browser:
![image](https://user-images.githubusercontent.com/810638/69007989-68e69200-0956-11ea-8053-5744eb60ea7e.png)

Expected:
 Connections that are temporarily unavailable should not present a blocking pop up asking for credentials.
In browser, such connection should present a triangle /!\ icon and that's it. 
In added layers, absent database shouldn't be different from absent table - just render nothing.

**Comment by gioman** [comment]
@Komzpa isn't this also addressed by https://github.com/qgis/QGIS/pull/32546 ?

**Comment by roya0045** [comment]
@gioman The ignore button seem to be present, but as reported in another issue, the loss of connection should not be associated to a logout/credential issue. I think this is the main issue presented.

**Comment by gioman** [comment]
> The ignore button seem to be present, but as reported in another issue, the loss of connection should not be associated to a logout/credential issue. I think this is the main issue presented.

I understad, my question/point is if the cited patch also takes into account this scenario.

**Comment by Komzpa** [comment]
@gioman no. Second screenshot in first post features the ignore button from that ticket but still asks for password for server that's down.

**Comment by elpaso** [comment]
@Komzpa but you get only one dialog for each broken server connections instead of one per each layer (if you press the ignore button) or is it not working?
