### ISSUE TITLE
QGIS (2.18) crashes on zooming

### ISSUE THREAD

**Issue by AkhilJPatil** [qgis/QGIS#32911]
**Describe the bug**
I am working of creating a vector layer (polygon) manually. this polygon is supposed to match 2 sentinel-2 products whose extents are not overlapping. The 2 sentinel products overlap partially. I am trying to create a polygon for this overlapping region. QGIS completely terminates and shutdowns itself if I zoom down quickly. 
I tried to lookup other bugs reported, and tried to connect with my approach. But could not connect with my issue here. 

**How to Reproduce**
1. Open 2 sentinel-2 [A/B] products, that may be overlapping partially or completely [Projection-3857]
2. GoTo : Layer > create layer > New Shapefile Layer
3. To this new shape file, add the polygon points
4. Zoom-in using mouse wheel from scale 1:6,000,00 to 1:1000
5. QGIS shuts down

**QGIS and OS versions**
QGIS: 2.18
Windows: 10

**Comment by nyalldawson** [comment]
2.18 is no longer supported

**Comment by AkhilJPatil** [comment]
okay. thanks for the response. I will try working around it or may be switch to later version.
