### ISSUE TITLE
crashing with export pdf

### ISSUE THREAD

**Issue by court25** [qgis/QGIS#32912]
Crash ID: e47ea778f81d5f29f49c88e0a812a6efd94cf8c4

Stack Trace

QgsLayoutExporter::updatePrinterPageSize :
QgsLayoutExporter::exportToPdf :
QgsVertexEditorModel::flags :
QMetaObject::activate :
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :

QGIS Info
QGIS Version: 3.8.2-Zanzibar
QGIS code revision: 4470baa1a3
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by nyalldawson** [comment]
Please retest with 3.10.0 (or at least 3.8.3)

**Comment by court25** [comment]
I did that and it is still not working.

**Comment by nyalldawson** [comment]
Ok, thanks! In that case, can you attach a sample project which demonstrates this issue?

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
