### ISSUE TITLE
Problems loading, displaying and saving JSON fields in PostGIS layers

### ISSUE THREAD

**Issue by CoryAlbrecht** [qgis/QGIS#32914]
1. Create a PostGIS layer with one or more JSON columns (see below for example)
2. Add layer to project in QGIS, toggle editing for the layer, and add feature to layer
3. Use identify features tool to open the feature attributes dialog
4. In the JSON field enter some syntactically valid JSON like  `[{"en":"Province of New Caledonia"}]`, and click the OK button
5. Save the layer
6. Open the feature attributes form again
7. See that the input box for the JSON field  has "NULL" in it. (see image 1)
8. Check database directly and see the column is null
9. In Layer Properties→Attributes Form, set the JSOn field to be a Key/Value widget
10. Open the feature attributes form and enter some key/value pairs that will hopefull get save as JSON back to the database
11. Click OK, then save the layer
12. Open up Feature attributes form, see the widget is empty
13. Go look at raw database, see that JSON field has been set to `[{}]`

So, two things.

Data is not saved properly. Key/Value widget let's you input arrays of simple JSON objects, but any attempt at multilevel objects get's parse badly and escaped. At the very least in a simple text widget you should be able to type in syntactically valid JSON and expect that it get properly saved as JSON into the column just like how you can do with an UPDATE statement in psql or pgAdmin. Instead the text widget just saves a null value to PostGIS

Data is not preserved when updating other fields. Even if you only needs simple JSON arrays that the Key/Value widget can produce properly, when you load the layer the values do not appear in the widget, and updating other attributes of the feature and saving replaces the good value with `[{}]`.

```sql
CREATE TABLE "Balance of Power".timeline_level1
(
    geom geometry(MultiPolygon,4326) NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    feature_uuid uuid NOT NULL DEFAULT uuid_generate_v4(),
    level1_uuid uuid NOT NULL DEFAULT uuid_generate_v4(),
    full_name json DEFAULT '{}'::json,
    alternate_name json DEFAULT '{}'::json,
    start_date date,
    end_date date,
    main_rgb character varying(9) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    stripe_rgb character varying(9) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    border_rgb character varying(9) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    type text COLLATE pg_catalog."default",
    info_url json DEFAULT '[]'::json,
    flag_url json DEFAULT '[]'::json,
    predecessors json DEFAULT '[]'::json,
    successors json DEFAULT '[]'::json,
    visible boolean DEFAULT true,
    level0_parent uuid,
    CONSTRAINT timeline_level1_pkey PRIMARY KEY (feature_uuid)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;
```

Before Text Saving:
![image](https://user-images.githubusercontent.com/8172909/69022400-31dda400-0989-11ea-825c-42457e7f1d2d.png)

After Text Saving: 
![image](https://user-images.githubusercontent.com/8172909/69022477-64879c80-0989-11ea-9082-2a02e0ffef34.png)

Before Key/Value Saving: 
![image](https://user-images.githubusercontent.com/8172909/69022672-0909de80-098a-11ea-8089-84fc4330fdd3.png)

After Key/Value Saving: 
![image](https://user-images.githubusercontent.com/8172909/69022785-6ef66600-098a-11ea-9751-49061461370e.png)

Raw Database after Key/Value Saving: 
![image](https://user-images.githubusercontent.com/8172909/69023137-b7625380-098b-11ea-872c-2df51827e891.png)

Step 13: 
![image](https://user-images.githubusercontent.com/8172909/69023248-2049cb80-098c-11ea-8677-fed8ad1c727e.png)

**Comment by CoryAlbrecht** [comment]
Even worse, it does this silently with no errors displayed.

**Comment by CoryAlbrecht** [comment]
Trying with the List Widget

Entry: 
![image](https://user-images.githubusercontent.com/8172909/69154114-68144400-0aad-11ea-9ac0-14242966d462.png)

Pre-save DB ([] is default value): 
![image](https://user-images.githubusercontent.com/8172909/69154188-88440300-0aad-11ea-8e8f-e89fe9fc8975.png)

Post-save check attributes form: 
![image](https://user-images.githubusercontent.com/8172909/69154241-a447a480-0aad-11ea-9d69-37c6eb454ed9.png)

Post-save check DB: 
![image](https://user-images.githubusercontent.com/8172909/69154358-dbb65100-0aad-11ea-8b0d-cc22e0d9a333.png)

So, yeah, not working.

The first field, info_url which had two list items got converted to a JSON object with a key/value pair. It should have been converted to a JSON array containing two strings. 

Second field, which should have been a JSON array with one string is instead an array with one element that is an array with one string element.

And, again, the list element post save displays as empty even though there was stuff in it to be saved.

If I make a change to a different field, like say I had spelled the name attribute incorrectly, this is what happens: 
![image](https://user-images.githubusercontent.com/8172909/69154967-ea513800-0aae-11ea-9a0b-d2d9974cef8e.png)

The fields get written over even though their values did not change, an dit was over with `[[]]` an empty JSON array inside another array.

**Comment by CoryAlbrecht** [comment]
Given QGIS's historically bad handling of PostgreSQL array fields, this isn't terribly surprising. Though one wonders why fields that were not updated in QGIS get placed in the  SQL `UPDATE` statement for that feature. That was a disaster waiting to happen for something like this where a bug destroys your data.

**Comment by CoryAlbrecht** [comment]
As text widgets:

Form entry pre close, pre save: 
![image](https://user-images.githubusercontent.com/8172909/69155669-2638cd00-0ab0-11ea-9b53-df2136e75cb2.png)

Form re-open pre-save:  Why are info_url and flag_url empty?!?
![image](https://user-images.githubusercontent.com/8172909/69155759-4f595d80-0ab0-11ea-8801-41cd5e20b3f2.png)

Check database post-save: 
![image](https://user-images.githubusercontent.com/8172909/69156091-e45c5680-0ab0-11ea-88dd-2a2481ce1fa2.png)

Show form after save: Why are those values set to null? 
![image](https://user-images.githubusercontent.com/8172909/69156241-1f5e8a00-0ab1-11ea-9525-89a86488c074.png)

**Comment by CoryAlbrecht** [comment]
You'd think that with plain old text widgets that QGIS would know enough to do something like

```sql
UPDATE table_name_here SET a_json_field='["a", "json", "array"]'::json
```

**Comment by CoryAlbrecht** [comment]
Turned on PostgreSQL statment logging, got this
```sql
UPDATE "Balance of Power"."timeline_level1" SET "full_name"=null::json,"alternate_name"=null::json,"info_url"=null::json,"flag_url"=null::json,"predecessors"=null::json,"successors"=null::json WHERE "feature_uuid"::text='ff31c209-7f9f-44f7-9aaa-5b2e9de65b6f'
```
The fields info_url and flag_url were the values shown above

**Comment by CoryAlbrecht** [comment]
When using List widgets:

```sql
UPDATE 
  "Balance of Power"."timeline_level1" 
SET 
  "full_name" = null :: json, 
  "alternate_name" = null :: json, 
  "info_url" = '{"https://test/2":"https://test/1"}' :: json, 
  "flag_url" = '[["https://test/3"]]' :: json, 
  "predecessors" = null :: json, 
  "successors" = null :: json 
WHERE 
  "feature_uuid" :: text = 'ff31c209-7f9f-44f7-9aaa-5b2e9de65b6f'
```

Let's try with 3 items instead of 2:

```sql
UPDATE 
  "Balance of Power"."timeline_level1" 
SET 
  "full_name" = null :: json, 
  "alternate_name" = null :: json, 
  "info_url" = '[["https://test/3","https://test/2","https://test/1"]]' :: json, 
  "flag_url" = '[[]]' :: json, 
  "predecessors" = null :: json, 
  "successors" = null :: json 
WHERE 
  "feature_uuid" :: text = 'ff31c209-7f9f-44f7-9aaa-5b2e9de65b6f'
```

4?

```sql
UPDATE 
  "Balance of Power"."timeline_level1" 
SET 
  "full_name" = null :: json, 
  "alternate_name" = null :: json, 
  "info_url" = '[["https://test/4","https://test/3","https://test/2","https://test/1"]]' :: json, 
  "flag_url" = '[[]]' :: json, 
  "predecessors" = null :: json, 
  "successors" = null :: json 
WHERE 
  "feature_uuid" :: text = 'ff31c209-7f9f-44f7-9aaa-5b2e9de65b6f'
```

**Comment by stev-0** [comment]
There is a pull request #30758 that should fix the edit text part of this when it is merged, but I can't speak for the list widget and key value widget as I didn't directly look at those, although I did notice some issues if I remember. Maybe something I could take a look at subsequently.

**Comment by CoryAlbrecht** [comment]
@stev-0 Will it at least fix the overwriting of attribute values, and let me edit the raw JSON in the multi-line text widget?

**Comment by stev-0** [comment]
@CoryAlbrecht yes it should fix overwriting of attributes, but only when using the EditTextWidget

**Comment by stev-0** [comment]
@CoryAlbrecht - can you check if this is fixed now, and close it if so, thanks

**Comment by stev-0** [comment]
This one has been open for months now - assuming no one else speaks up maybe you could close it @gioman?
