### ISSUE TITLE
Extens Boundary (Limit zooming in basemap area)

### ISSUE THREAD

**Issue by EsmH** [qgis/QGIS#32923]
I have put OpenStreetMap service in QGIS and I want to limit the area of zooming in and out. I want to let users to be focused just in one city and I don't want to permit them to pan all over the world (in the base map).

**Comment by gioman** [comment]
@EsmH use scale based visibility?

**Comment by EsmH** [comment]
No. I want to limit the boundaries. If the project area is in Germany and if users will pan to France (for example), I don't want to permit them to go there.

**Comment by gioman** [comment]
> No. I want to limit the boundaries. If the project area is in Germany and if users will pan to France (for example), I don't want to permit them to go there.

then you can create your own service with just the extent you want/need.

**Comment by EsmH** [comment]
Can you please help me how to do it? (by sending any link where I can see an example? 
I am a new user in QGIS and I don't have enough experience unfortunately.

**Comment by gioman** [comment]
@EsmH a simple solution is to save (as a file, like a geotiff) only the area you need. 

export > save as

**Comment by EsmH** [comment]
By saving geotiff the map will lose the resolution and users can pan again outside the raster.

**Comment by gioman** [comment]
> By saving geotiff the map will lose the resolution

save at a higher resolution?

> and users can pan again outside the raster.

this is not how desktop gis works, as far as I know. There are webgis applications that limit the extent that can be panned.

**Comment by NathanW2** [comment]
In fact Nyall and I talked about this last week at FOSS4G in NZ :P

**Comment by EsmH** [comment]
@NathanW2 and which was the result? Something we can not realise yet? :S

**Comment by NathanW2** [comment]
Just chats between the house and breakfast so nothing yet ;) I can't see it
being hard would just need someone to work on it

**Comment by EsmH** [comment]
Haha, neither I can't see it being hard, but I'm not able to do it xD

**Comment by Saijin-Naib** [comment]
> this is not how desktop gis works, as far as I know. There are webgis applications that limit the extent that can be panned.

There is a similar behavior in ArcGIS where you can set the "zoom to full/zoom to world" button to any particular given extent, though you can't prevent the map from panning/zooming outside of this extent.

However, you can "clip" the canvas to a given extent, which hides all the data beyond that extent, but again, you can navigate further if you wish (even if ESRI pretends you can't by making the scroll bars appear to be at their full maximum values):
![image](https://user-images.githubusercontent.com/19295950/69070768-c16d6c00-09f6-11ea-98d9-499599786364.png)

They lie:
![image](https://user-images.githubusercontent.com/19295950/69070797-cdf1c480-09f6-11ea-9d0f-40b0954ac74d.png)

**Comment by EsmH** [comment]
Thank you @Saijin-Naib. I used to clip dataframe in ArcMap, but I need something different in Qgis :/

**Comment by Saijin-Naib** [comment]
> Thank you @Saijin-Naib. I used to clip dataframe in ArcMap, but I need something different in Qgis :/

I too would like to see something similar to both Clip to dataframe as well as a "locked" max extent function in QGIS. It could keep some of my users out of trouble, haha.

**Comment by gioman** [comment]
@EsmH seems the basis to implement this has already been added: https://github.com/qgis/QGIS/pull/40233
