### ISSUE TITLE
Random crashing

### ISSUE THREAD

**Issue by mrnapop** [qgis/QGIS#32924]
Hello,

QGIS 3.10 crashed upon editing a layer's table manually, and the map got stuck when i tried to zoom to selected features, that is the software worked but the map display itself got stuck.

**Comment by gioman** [comment]
@mrnapop please try with a new QGIS profile and no 3rd party plugins installed. Also send the full set of infos requested by the ticket template.

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
