### ISSUE TITLE
When exporting to GeoPDf, the page size is set incorrectly.

### ISSUE THREAD

**Issue by schorsch2** [qgis/QGIS#32931]
**Describe the bug**
When exporting to GeoPDf, the page size is set incorrectly.
The export to a normal pdf file works as expected: A4 remains A4. The output as Geo-PDF leads to a page size of 876.1 x 1237.7 mm.

**How to Reproduce**
export to pdf
export to geopdf and compare the page size

<!-- Steps, sample datasets and qgis project file to reproduce the behavior. Screencasts or screenshots welcome

**Additional context**

**Comment by schorsch2** [comment]
![Pagesize](https://user-images.githubusercontent.com/13661057/69327457-e0b20680-0c4d-11ea-89a6-45c25d66f8ad.png)

**Comment by schorsch2** [comment]
**QGIS and OS versions**

QGIS-Version | 3.10.0-A Coruña | QGIS-Codeversion | 6ffa89eb3e
-- | -- | -- | --
Kompiliert gegen Qt | 5.11.2 | Laufendes Qt | 5.11.2
Kompiliert mit GDAL/OGR | 3.0.2 | Läuft mit GDAL/OGR | 3.0.2
Kompiliert mit GEOS | 3.8.0-CAPI-1.13.1 | Läuft mit GEOS | 3.8.0-CAPI-1.13.1
Kompiliert mit SQLite | 3.29.0 | Läuft mit SQLite | 3.29.0
PostgreSQL-Client-Version | 11.5 | SpatiaLite-Version | 4.3.0
QWT-Version | 6.1.3 | QScintilla2-Version | 2.10.8
Kompiliert mit PROJ | 6.2.1 | Läuft mit PROJ | Rel. 6.2.1, November 1st, 2019
BS-Version | Windows 10 (10.0)
Aktive Python-Erweiterungen | alkisplugin; giswater; Hqgis; ImportPhotos; postgis_geoprocessing; processing_whitebox; qkan; QuickOSM; SaxonyCadastralParcels; db_manager; MetaSearch; processing

**Comment by nyalldawson** [comment]
Duplicate of #33465
