### ISSUE TITLE
In form view wrong features/records are deleted

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#32933]
Latest QGIS 3.4 on Linux

An image is worth a 1000 words:

![Peek 2019-11-18 16-08](https://user-images.githubusercontent.com/1951107/69069683-d0681480-0a1e-11ea-8350-59afd16b7f1c.gif)

**Comment by elpaso** [comment]
with all layers and all providers?

**Comment by gioman** [comment]
> with all layers and all providers?

tested gpkg, postgis and shp.

**Comment by gioman** [comment]
and a few different layers.

**Comment by elpaso** [comment]
Confirmed.
