### ISSUE TITLE
GRASS Problems when installing parallel QGIS versions at Windows

### ISSUE THREAD

**Issue by miron-t** [qgis/QGIS#32930]
I have problems when trying to run more versions (3.4 ltr and 3.10) at the same time. I’m using the osgeo4w-setup, but there are several things I cannot explain:

- First, the “QGIS desktop with grass” doesn’t exist anymore (for 3.4 ltr as well as for 3.10). So I can’t get to run QGIS with grass anymore.

- I cannot configure the two versions separately: when I go into the setup of the 3.4 ltr version and configure the grass path to the 6.4 Version (grass-6.4.3), the same configuration is set automatically in the QGIS 3.10 version! So, I cannot configure different grass paths for different versions of QGS anymore.

Any Ideas?
Thanks

**Comment by roya0045** [comment]
Grass is in the processing toolbox. For point two you could try to setup two distinct osgeo environment otherwise you will always manage one environment.

Though I have no clue why you would need to have both 3.4 and 3.10.

**Comment by miron-t** [comment]
Thanks for the reply. I know that GRASS algorithms can be found in the processing toolbox. Unfortunately, after installing QGIS with the osgeo4w-setup, the GRASS algorithms are shown, but an error page comes up when trying to start an algorithm. 

Regarding point two: I had the impression that the hole setup with the osgeo4w-setup was fitted to run more QGIS versions independently? I run different versions for Plugin development.

Anyways, I wanted to point out in this bug report that there the is something wrong with the osgeo4w-setup, had lots of errors before.

**Comment by gioman** [comment]
> but an error page comes up when trying to start an algorithm.

what error? something similar has been addressed recently, please be sure you have installed all the latest updates from osgeo4w-

**Comment by miron-t** [comment]
Mostly missing .dll. I could not start QGIS at all but I could fix this with uninstalling all versions and deleting the OSGEO folder, but the above-mentioned errors maintain. Did everything with the latest download.

**Comment by gioman** [comment]
> Mostly missing .dll.

this is likely a local/temporary issue. Recently they pushed GRASS 7.8,1 in osgeo4w that until a few days ago was messed up.

**Comment by miron-t** [comment]
Sorry, I didn’t got your question. The error that comes up is the missing GRASS folder:

![grafik](https://user-images.githubusercontent.com/38276891/69068857-cbf32a00-0a25-11ea-813b-ce8ce45cd976.png)

Its not the same path as in the picture but the same error.

**Comment by gioman** [comment]
> Its not the same path as in the picture but the same error.

try doing a clean osgeo4w install

**Comment by jef-n** [comment]
@miron-t There should be a "with GRASS" shortcut and you need to use it.   And hint in `setup.log` or `setup.log.full` on why there isn't a shortcut?

**Comment by miron-t** [comment]
I just did a clean Install of 3.4 and 3.10 with the osgeo4w and no success. There are no “with GRASS” exe for both versions. And GRASS is also not working from the Processing Toolbox. Same error as mentioned above. Where can I find `setup.log` and `setup.log.full`? I deleted the OSGEO folder on C: for the clean install, is there something else I have to delete?

**Comment by jef-n** [comment]
@miron-t ``%OSGEO4W_ROOT%/var/log``

**Comment by miron-t** [comment]
If I change the folder name for GRASS in "C:\OSGeo4W64\apps\grass\grass78" from "grass78" to "grass-7.8.1", I can at least run GRASS processes for QGIS 3.10, but not for 3.4

**Comment by miron-t** [comment]
I noticed in the setup.log.full that sometimes the path for GRASS is “grass-78” instead of “grass78” witch results in an error: `Failed to open source file 'C:\OSGeo4W64\apps\grass\grass-78\etc\fontcap' No such file or directory`. Does this help?

**Comment by miron-t** [comment]
I found out that this error also occurs when I try to install any version of QGIS using the OSGeo4W Installer. So, the error is not limited to the installation of parallel versions. 
When I try installing QGIS version 3.10.14 or 3.4.14 singular on a Windows 10 machine with the OSGeo4W Installer, there is no qgis-grass7.exe or qgis-ltr-bin-g7.exe. Hence, I cannot use GRASS processes in QGIS.

**Comment by gioman** [comment]
> When I try installing QGIS version 3.10.14 or 3.4.14 singular on a Windows 10 machine with the OSGeo4W Installer, there is no qgis-grass7.exe or qgis-ltr-bin-g7.exe. Hence, I cannot use GRASS processes in QGIS.

if you are using the osgeo4w installer then GRASS must be installed/selected manually along with the necessary "qgis-grass-plugin" package.

**Comment by miron-t** [comment]
Ok, I was not aware of that change! I’m using the osgeo4w installer since years and it must have changed recently. Thanks so much @gioman for pointing this out, I literally spend hours trying to solve this.

**Comment by jef-n** [comment]
> Ok, I was not aware of that change! I’m using the osgeo4w installer since years and it must have changed recently. Thanks so much @gioman for pointing this out, I literally spend hours trying to solve this.

Which change?

**Comment by miron-t** [comment]
The change that in the OSGeo4W Installer you have to manually select the "qgis-grass-plugin7" package under “Libs”. I guess it is a change, I always used the OSGeo4W Installer and I never had to select the GRASS plugin manually.
![grafik](https://user-images.githubusercontent.com/38276891/70996886-078c1d00-20d4-11ea-901c-52b016cc3f58.png)

**Comment by gioman** [comment]
> The change that in the OSGeo4W Installer you have to manually select the "qgis-grass-plugin7" package under “Libs”. I guess it is a change, I always used the OSGeo4W Installer and I never had to select the GRASS plugin manually.

I also have the feeling that in the past (2.*) to run GRASS tools in Processing was not needed to run QGIS using the "with GRASS" shortcut. But not 100% sure.

**Comment by jef-n** [comment]
> I also have the feeling that in the past (2.*) to run GRASS tools in Processing was not needed to run QGIS using the "with GRASS" shortcut. But not 100% sure.

Correct - but before you also had to update the GRASS path in processing's settings after GRASS updates (back then for every GRASS point release), which is now set by the "with GRASS" shortcut - causing problems if you didn't.  The GRASS plugin itself should always have been optional and hence GRASS.      processing doesn't have a hard dependency on GRASS and should detect whether it's there or not - but that's a bit flaky - as w/o "with GRASS" it there, but not operational.  And we still have stuff to support version 6 and 7 although GRASS6 is probably not used anymore anywhere…

**Comment by gioman** [comment]
> Correct - but before you also had to update the GRASS path in processing's settings after GRASS updates (back then for every GRASS point release - causing problems if you didn't), which is now set by the "with GRASS" shortcut. The GRASS plugin itself should always have been optional and hence GRASS. processing doesn't have a hard dependency on GRASS and should detect whether it's there or not - but that's a bit flaky - as w/o "with GRASS" it there, but not operational. And we still have stuff to support version 6 and 7 although GRASS6 is probably not used anymore anywhere…

thanks for the explanation.
