### ISSUE TITLE
Wrong label in UI for "Create point for each part" on "Centroids" processing algorithm

### ISSUE THREAD

**Issue by phidrho** [qgis/QGIS#32940]
**Describe the bug**
Current misleading label says "Create point on surface for each part" which is probably copied from Point on surface algorithm. This assumes if checked, point on surface algorithm should be used, which is not correct. Should be corrected to "Create a centroid for each part".

OLD VERSION OF THIS BUG REPORT (IGNORE, HERE ONLY FOR REFERENCE):
> When option "Create point on surface for each part" is checked, all created 'centroid' points should be inside polygon, but for some reason they don't. See [video demo](https://www.youtube.com/watch?v=Cz_LPBfjtz0).
> If I am understanding it correctly it shoud behave as [ST_PointOnSurface](https://postgis.net/docs/ST_PointOnSurface.html).
> 

[bug_qgis_centroids.zip](https://github.com/qgis/QGIS/files/3862314/bug_qgis_centroids.zip)

**QGIS and OS versions**

QGIS version
3.10.0-A Coruña
QGIS code revision
6ffa89eb3e
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.2
Running against GDAL/OGR
3.0.2
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.2.1
Running against PROJ
Rel. 6.2.1, November 1st, 2019
OS Version
Windows 10 (10.0)
Active python plugins
gml_application_schema_toolbox; 
LAStools; 
mmqgis; 
db_manager; 
MetaSearch; 
processing

**Comment by nirvn** [comment]
This label is misleading, it should read "create a centroid for each part". What you want to use is the point on surface algorithm.

**Comment by phidrho** [comment]
Oh, I didn't know that they are separate algorithms, I've found it now in Processing Toolbox. So It's only a bug in UI, it should be easy fix.

**Comment by gioman** [comment]
> So It's only a bug in UI, it should be easy fix.

please update accordingly the subject and description of this ticket, thanks.

**Comment by havatv** [comment]
Shouldn't this be backported to the current LTR (3.4)?
