### ISSUE TITLE
Mouse pointer keeps switching type

### ISSUE THREAD

**Issue by oskarlin** [qgis/QGIS#32947]
**Describe the bug**
When using different tools in QGIS 3.10 the mouse pointer on my Mac keeps on flickering between the native pointer to the crosshair of QGIS which is annoying. This didn't happen on the previous versions of QGIS.

**How to Reproduce**
<img width="496" alt="Screenshot 2019-11-19 at 10 11 31" src="https://user-images.githubusercontent.com/2736990/69132780-01932400-0ab5-11ea-82fb-be5c6184b471.png">
<img width="496" alt="Screenshot 2019-11-19 at 10 13 10" src="https://user-images.githubusercontent.com/2736990/69132881-343d1c80-0ab5-11ea-8b6c-04d9580d0df8.png">

**QGIS and OS versions**
QGIS version | 3.10.0-A Coruña
MacOS 10.14.6

**Comment by PeterPetrik** [comment]
@oskarlin can you please give me exact how to reproduce steps for the problem (or better screencast)? In QGIS, various tools have different cursors associated, so the users know that they have different tools active (e.g. cursor with "i" for identify, cross cursor for digitizing, ...), so I think it could be well the feature and not the bug.

**Comment by oskarlin** [comment]
I made a recording and put it on YT:
https://www.youtube.com/watch?v=rp50OkVS70A

**Comment by PeterPetrik** [comment]
i cannot watch the YT video, it is private

**Comment by oskarlin** [comment]
Sorry @PeterPetrik, now it's public.

**Comment by PeterPetrik** [comment]
do you press any keys, or just mouse clicks? 
can you try with https://qgis.org/downloads/macos/nightly/qgis_nightly_master_20201005_122844.dmg ?

**Comment by oskarlin** [comment]
No keys pressed. And yes, it's gone in that build! Thanks!

**Comment by PeterPetrik** [comment]
If you do not mind, i close it in that case, the 3.10,3.14 are packaged completely differently, so I am not able to fix it there

**Comment by oskarlin** [comment]
@PeterPetrik ok but the problem still exists in my 3.14 version.
