### ISSUE TITLE
QGIS marks my layer as a memory layer...

### ISSUE THREAD

**Issue by saberraz** [qgis/QGIS#32943]
when I save my project in /tmp/ folder.

To replicate the issue:
- Move the attached project to your /tmp/ folder
- Open the project
- You will see this in the Layers Panel:
![image](https://user-images.githubusercontent.com/2649047/69127055-6e9cbe80-0aa1-11ea-99e5-3ba54891d3f6.png)

If I open the same project anywhere else on my file system, the memory layer sign disappears.

It appears to me that QGIS marks any layer sourced from /tmp/ as a temporary/memory layer. 

[example.zip](https://github.com/qgis/QGIS/files/3862531/example.zip)

**Comment by alexbruy** [comment]
Looks like this is caused by fix for #32582.

**Comment by nyalldawson** [comment]
> It appears to me that QGIS marks any layer sourced from /tmp/ as a temporary/memory layer.

That's because it IS a temporary layer!!

**Comment by saberraz** [comment]
I understand it is a temporary location...but that's where I do all my work :)
 
I have changed my TMP environment variable to something other than /tmp/ and QGIS treats the layer not as a memory layer...
