### ISSUE TITLE
Crash on importing KMZ without geometry

### ISSUE THREAD

**Issue by frprieto** [qgis/QGIS#32948]
**Describe the bug**
When importing a KMZ from Google Earth without geometry, QGIS gets blocked. The problem is only with KMZ files, not KML.

**How to reproduce**
- On Google Earth Pro, create a new route or poligon without defining a geometry.
- Save site as KMZ
- Import the KMZ file into QGIS file by drag and drop

**QGIS and OS versions**
3.10.0, 64 bits on Windows 10

**Comment by gioman** [comment]
Can you attach here an offending kmz? thanks.

**Comment by frprieto** [comment]
The KMZ and KML files have the same information (a polygon without geometry). In both of them the coordinates field is empty,
```
<coordinates></coordinates>
```
but the crash only happens with the KMZ file.

[KMZ and KML.zip](https://github.com/qgis/QGIS/files/3863203/KMZ.and.KML.zip)

**Comment by gioman** [comment]
No crash on 3.4 on Linux.

**Comment by alexbruy** [comment]
Works fine on 3.10/3.12 both on Windows and Linux.
