### ISSUE TITLE
Polygon with Map Units width shows up in the corner of the canvas when zoomed in

### ISSUE THREAD

**Issue by oskarlin** [qgis/QGIS#32951]
**Describe the bug**
I have a rectangular polygon which has a border width using Map units (in this case 1000 m wide) and when I zoom in to a certain scale, the polygon shows up in the border of my map canvas all of a sudden, and the more you zoom in, the more space it takes. See images. This only happens when using _Map units_ or _Meters at Scale_ .

**How to Reproduce**

<img width="1484" alt="Screenshot 2019-11-19 at 10 53 05" src="https://user-images.githubusercontent.com/2736990/69136632-808b5b00-0abb-11ea-8d6c-1760f3ee7fd4.png">
<img width="1503" alt="Screenshot 2019-11-19 at 10 53 32" src="https://user-images.githubusercontent.com/2736990/69136654-8b45f000-0abb-11ea-9280-12b5b5fadb4c.png">
<img width="1498" alt="Screenshot 2019-11-19 at 10 53 40" src="https://user-images.githubusercontent.com/2736990/69136676-91d46780-0abb-11ea-9c5f-3390f0a4877a.png">

**QGIS and OS versions**
QGIS version | 3.10.0-A Coruña
MacOS 10.14.6

**Comment by nyalldawson** [comment]
You need to uncheck the "Clip Features to Canvas Extent" option under the "advanced" button. The polygon is being clipped at render time to an area just outside the map canvas, so as the border width grows when you zoom in this eventually becomes visible.

**Comment by oskarlin** [comment]
I'm sorry but where do I look? In the general settings? Can't find any "Clip Features to Canvas Extent" there under Advanced.

**Comment by nyalldawson** [comment]
@oskarlin it's here:

https://user-images.githubusercontent.com/1829991/134610923-f6b2ef7a-a83c-4975-b65d-9d8fc4d358c0.mp4
