### ISSUE TITLE
SAGA Fill sinks (Wang & Liu) gives error in 3.4.13

### ISSUE THREAD

**Issue by jvdkwast** [qgis/QGIS#32953]
**Describe the bug**
In QGIS 3.4.13 the SAGA Fill sink (Wang & Liu) processing tool is not working. It gives an error. See screenshot. We tested it against QGIS 3.4.10 where it was still working with the same procedure and files.
![error_fill_sinks](https://user-images.githubusercontent.com/1172662/69155490-189c3b00-0ae2-11ea-9a0c-0ea4498273c9.jpg)

**How to Reproduce**
I used the "catchment delineation procedure" as explained in the book QGIS for Hydrological Applications and this video (https://youtu.be/Ro-RRzMMw-c). Here I'll only put the summary:
1. In the Processing Tools go to SAGA -> Terrain Analysis - Hydrology -> Fill sinks (Wang & Liu)
2. Select an DEM tif file (we use SRTM 1 arc second, reprojected to UTM/WGS-84)
3. Keep defaults and Save output to dem_fill.tif. You can uncheck the boxes for Flow Direction and Watershed Basins. Click Run.
4. See error --> screenshot above

**QGIS and OS versions**

3.4.13 for Windows 64 bit

**Additional context**

It was working in 3.4.10 and older versions

**Comment by jvdkwast** [comment]
In 3.10 it also doesn't work.

From the log it seems that there's a problem loading the grid.

Load grid: C:/Users/hansa/AppData/Local/Temp/processing_2c504eea0fde4c46a62e2d5abe7d54cd/4aa35cfe7612459696b5b0b57bf4077b/dem36nclip10.sgrd...
failed

Usage: saga_cmd ta_preprocessor 4 [-ELEV <str>] [-FILLED <str>] [-FDIR <str>] [-WSHED <str>] [-MINSLOPE <double>]
-ELEV:<str> DEM
Grid (input)
-FILLED:<str> Filled DEM
Grid (output)
-FDIR:<str> Flow Directions
Grid (output)
-WSHED:<str> Watershed Basins
Grid (output)
-MINSLOPE:<double> Minimum Slope [Degree]
Floating point
Minimum: 0.000000
Default: 0.100000

**Comment by gioman** [comment]
oddly enough it works ok on Linux with basically the same SAGA version (2.3.1 linux VS 2.3.2 windows).

**Comment by gioman** [comment]
@jvdkwast so... on Windows you must install manually also the "gdal204dll" package (if you are using the osgeo4w installer) otherwise SAGA will not come with the "io_gdal" library and so any SAGA command will fail (to import data in its own data format/model). @jef-n should this be added as a dependency?

**Comment by gioman** [comment]
closing?

**Comment by jvdkwast** [comment]
I use the standalone installer and it always worked. At least it should keep working in the current LTR version. Otherwise it will have consequences for many users.

**Comment by gioman** [comment]
> I use the standalone installer and it always worked.

yes but there was a major GDAL upgrade recentely, and SAGA version supported in QGIS still uses an old GDAL release.

**Comment by TimotheeMichon** [comment]
Doesn't work for me too... Same bug !

**Comment by JahAirforce** [comment]
Hi,
I got the same problem and I would like to try your solution gioman but I don't know how to install manually the "gdal204dll" package.... I tried by downloading the dll and copy/replace in the directory, but it didn't solve anything. Is there any tips/tutorials plz ?
Thanks !

**Comment by frgis** [comment]
Hello,
in version 3.10.1 SAGA does not appear in the processing tool. Log attached to QGIS 3.10.1
Thanks
![saga_fonctionne_pas](https://user-images.githubusercontent.com/56657014/72339535-b9fcd300-36c6-11ea-93f1-a686f288a55c.PNG)

**Comment by gioman** [comment]
> Hello,
> in version 3.10.1 SAGA does not appear in the processing tool. Log attached to QGIS 3.10.1
> Thanks

@frgis have you installed QGIS with osgeo4w or the standalone installer? With the formers ypu must install manually the saga-ltr package.

**Comment by gioman** [comment]
> Hi,
> I got the same problem and I would like to try your solution gioman but I don't know how to install manually the "gdal204dll" package.... I tried by downloading the dll and copy/replace in the directory, but it didn't solve anything. Is there any tips/tutorials plz ?
> Thanks !

I just tested a clean install with osgeo4w, and the gdal204 package is now an automatic dependency, this means that SAGA works ok out of the box (at the end of the process an error message is returned, but the ouputs are generated and added to the project. This is another issue that has already been reported).

**Comment by frgis** [comment]
Hi,

I install QGIS with standalone installer.


it is not advisable ?

**Comment by gioman** [comment]
> it is not advisable ?

I don't know if the standalone packages have the library/dependency needed by SAGA. As this dependency is respected now with OSGeo4w it means that the next standalone installers will be ok fir sure.

**Comment by gioman** [comment]
I suggest to close this issue.

**Comment by frgis** [comment]
Ok for me
