### ISSUE TITLE
Layer label based on success

### ISSUE THREAD

**Issue by j66FME** [qgis/QGIS#32958]
Is there a way to fix the save file name format when using a analytical tool?

I.E, I used the the raster calculator to look at the aspect layer of the srtm_41_19.tif layer from the QGIS training data 2.0 by these conditions "aspect@1" <= 90 OR "aspect@1" >= 270

I am able to save the file as aspect_north.tiff but when it when it is brought over to the layers, it is only labelled as Output. Obviously you can change the name manually but that can be tedious at best and really time consuming at worst. 

![QGIS](https://user-images.githubusercontent.com/57955062/69175576-fbf80700-0ad1-11ea-81ee-a0c3b88d4e40.PNG)

**Comment by gioman** [comment]
settings > options > processing > general > use file names as layer names
