### ISSUE TITLE
crash when deleting a column in the attribute table window

### ISSUE THREAD

**Issue by ZMcCarrey** [qgis/QGIS#32964]
## User Feedback

I was deleting a column in the attribute table window

## Report Details

*Crash ID*: a89a1f09837ca15a7d33a52321407dced8b213de

*Stack Trace*
<pre>
memcpy :
QgsVectorLayerFeatureIterator::updateChangedAttributes :
QgsVectorLayerFeatureIterator::fetchFeature :
QgsAbstractFeatureIterator::nextFeature :
QgsVectorLayerLabelProvider::registerFeature :
QgsVectorLayerLabelProvider::registerFeature :
QgsMapRendererParallelJob::renderLayerStatic :
QgsMapRendererParallelJob::renderingFinished :
QgsArchive::zip :
QgsArchive::zip :
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.8.1-Zanzibar
QGIS code revision: dcd95cc648
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment]
@ZMcCarrey please upgrade to the latest 3.10 or 3.4 LTR, then test again. If it persist then try with a new QGIS profile and no 3rd party plugins installed.

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
