### ISSUE TITLE
georeferencer: decimal values for "dest Y" not retained 

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#32960]
As shown in the below cast, the "dest y" values are always rounded to the nearest integer. The "dest X" is rounded only to 1 decimal. In both cases at least a couple of decimal values could be kept. Please notice that if you double click in the dest x/y values in the GPC table you will be presented will all the original decimals, but when exporting to GDAL script the decimals are lost.

![Peek 2019-11-19 22-07](https://user-images.githubusercontent.com/1951107/69190847-32a54000-0b19-11ea-80bd-c4f158446019.gif)

**Comment by nyalldawson** [comment]
This looks like a locale-specific issue -- can you confirm it works correctly with a locale with "." as decimal place?

**Comment by gioman** [comment]
> This looks like a locale-specific issue -- can you confirm it works correctly with a locale with "." as decimal place?

@nyalldawson my OS is in English and I use QGIS in English, but for some reasons I see commas as separator for decimals. I then tried on a VM, all in EN, where the dots are used as separators, and I still see the same issue. Oddly enough if the project CRS is WGS84 then in the GCP table the dest x/y coordinates show with 3 decimals (that in degrees are arguably still too few).

**Comment by gioman** [comment]
@nyalldawson on the most recent master the situation has slightly changed, but not completely for the best.

Now values (for both dest X and dest Y) are shown in scientific notation (that in my opinion should be avoided). What is worst os that double clicking on dest X or dest Y cell makes the values change(!) after leaving the focus on that cell. @roya0045 it wasn't you that had worked on the georef recently?

**Comment by roya0045** [comment]
Gio do you think this is still valid?

**Comment by gioman** [comment]
From the last tests I think this can be safely closed.
