### ISSUE TITLE
Layer Sorting in Toolbox Multiple Selection

### ISSUE THREAD

**Issue by ZMcCarrey** [qgis/QGIS#32963]
When you go into a tool in the tool box, say Merge Vector Layers for example, it is difficult to find which input layers to select. It would be great if the input layers could sort by alphabetical order or give the same file structure as the layers list in the main QGIS window.

Usually i have to rename files i want to merge so it has lots of xxxxx in front of it, to be able to see it easier in the list. I have over 200 layers within a project. Image shows how poorly sorted the list is.

![image](https://user-images.githubusercontent.com/56584917/69215180-ea7f2f80-0ba3-11ea-9919-5f78d66f3da0.png)

**Comment by roya0045** [comment]
This makes me wonder if that type of input could check selected layers in the project layer tree, either as a button or by default. This would allow the user to select the items that he wants in the project, open the tool and use all those layers directly.

**Comment by ZMcCarrey** [comment]
That would be helpful too. Any form of sorting will be great

**Comment by roya0045** [comment]
Though the main issue that I can see are duplicate name. And the fact that elements are passed strangely to the code, they go through a convoluted path to end up in the list, this makes things hard to  compare things.

**Comment by nyalldawson** [comment]
Fixed in 3.14
