### ISSUE TITLE
PyQgis: Qgis crashes when changing the labeling of an already styled layer

### ISSUE THREAD

**Issue by Magnati** [qgis/QGIS#32970]
When programming your own plugin and loading a layer, which you are styling with a `.qml` file and later try to change the style programmatically, QGIS has a hard crash:

```bash
GIS died on signal 11Could not attach to process. If your uid matches the uid of the target
process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
again as the root user. For more details, see /etc/sysctl.d/10-ptrace.conf
ptrace: Operation not permitted.
No thread selected
No stack.
gdb returned 256
```

**How to Reproduce**

I created a reproduction plugin in [my github](https://github.com/Magnati/QGISLabelingCrash).

The most interesting code part however is:
```python
        root = qgis.core.QgsProject().instance().layerTreeRoot()
        shape_file = "matching.qml"
        layer = self._add_layer_by_uri(
            f"LineString?crs=EPSG:4326",
            "matching",
            "memory",
            root,
            0,
            shape_file,
        )
        color = PyQt5.QtGui.QColor(255, 0, 0)
        # changing the renderer works !
        layer.renderer().symbol().setColor(color)
        # But here it crashes
        layer.labeling().settings().format().background().setFillColor(color)
        self.registry.addMapLayer(layer, False)
        self.iface.layerTreeView().refreshLayerSymbology(layer.id())
```

**QGIS and OS versions**

This behaviour was only apparent on Ubuntu 19.04

The crash occured on Ubuntu 19.04 with QGIS 3.4/3.10:
The labeling change worked on Ubuntu 18.04 with QGIS 3.4/3.10

**Comment by roya0045** [comment]
That is possibly because labeling is not enabled/setup and you are assigning a parameter to it anyway.

I highly doubt this is a bug, I guess that some failsafe could be put in place but otherwise the issue 
 seems comes from your code. There are to many ways to crash qgis in python to patch them all.

**Comment by Magnati** [comment]
Labeling (especially the background-color) is setup in the `.qml` file. (in Ubuntu 18.04 it works)

Is there a special enable step, that I maybe missed?

**Comment by roya0045** [comment]
if you do layer.labeling().labelsEnabled() you should know if labeling is enabled. Otherwise I guess that you would need to make a PalsSetting or xml/sld document.
From the doc it would seem that layer.labeling().setSetting( QgsPalLayerSettings) is the way to set things up.
Once you are done use layers.setLabelEnabled(True)

I would assume that the settings need to be set one by one, [ here is the pals settings](https://qgis.org/pyqgis/3.4/core/QgsPalLayerSettings.html).

I have never done such but I feel like this would be the way.

**Comment by Magnati** [comment]
**Note:** The method to check is `layer.labelsEnabled()`.  
`QgsPalLayerSettings` has no `enabled` member anymore according to [https://qgis.org/api/api_break.html](https://qgis.org/api/api_break.html).

It is `true` on both Ubuntu 19.04 and 18.04.

I found a way to get it working but it feels very uncanny (`master` in [my repo](https://github.com/Magnati/QGISLabelingCrash) is updated ).
I clone the labeling object of my layer but only if I unpack each element of the labeling object one by one it works in both Ubuntu versions.

```python
    # alternative approach
    labeling = layer.labeling().clone()

    # crashes in 18.04 crashes in 19.04
    # labeling.settings().format().background().setFillColor(color)  

    # crashes in 18.04 crashes in 19.04
    # b = labeling.settings().format().background()
    # b.setFillColor(color)
            
    # works in 18.04 crashes in 19.04
    # settings = labeling.settings()
    # settings.format().background().setFillColor(color) 

    # works in 18.04 works in 19.04
    settings = labeling.settings()
    my_format = settings.format()
    my_background = my_format.background()
    my_background.setFillColor(color)
            
    layer.setLabeling(labeling)
```

esspecially that 
```python
    # crashes in 18.04 crashes in 19.04
    # b = labeling.settings().format().background()
    # b.setFillColor(color)
```
does not work, seems pretty disturbing.

**Comment by gioman** [comment]
@Magnati is this relevant in recent QGIS releases? Have you asked in the dev mailing list if your code is correct?
