### ISSUE TITLE
3D View Skybox

### ISSUE THREAD

**Issue by Saijin-Naib** [qgis/QGIS#32981]
**Feature description.**
3D game engines oftentimes feature support for a Skybox, which is a 3D cube with inverted normals rendered at a sufficiently large size as to encompass the entire scene. Each face of the cube has an image applied to it so that when the camera points in any direction, the image is rendered onto the screen, giving the impression of a fully realized sky/horizon.

Having a skybox in QGIS's 3D View would allow for more photorealistic rendering, as well as possibly more stylized rendering if wanted/needed.

**Additional context**
The implementation I am most familiar with comes from the iDTech family of 3D game engines. In this implementation, six images of the same format are put into a directory, and the engine applies them to the face of the cube by reading a suffix on the filename.

The suffixes are:  
bk [back]
ft [front]
lf [left face]
rt [right face]
up [up]
dn [down]

The engine is expected to find the images either with or without a prepended underscore before the suffix, for instance:  
sky_bk.png
sky_ft.png
skylf.png
sky_rt.png
skyup.png
skydn.png

Documentation from the QuakeWiki:
https://quakewiki.org/wiki/Skybox_Support

This format for skyboxes is very mature and has seen adoption as a de-facto standard in many games/engines due to the adoption of the iDTech engines, so there are numerous pre-made skyboxes that could be dropped in as-is, which is a big benefit.

**Comment by alexbruy** [comment]
Seems implemented in #38087.

**Comment by Saijin-Naib** [comment]
Yes and no. His implementation doesn't work with the huge library of existing sky boxes from game engines, so would this still be able to be kept open as an expansion of the current implementation?

**Comment by kannes** [comment]
Just ran into this when I tried to set a skybox using this good-old format. Would be a great feature!

Re-open please.

**Comment by Saijin-Naib** [comment]
Yeah, that was my thinking when I asked for this format. We have something like 30 years of skyboxes created in this format to pick through... Should be pretty awesome for end-users.

**Comment by kannes** [comment]
To be honest I did not get any panoramic sky to work either, nothing ever shows up for me. Are you getting anything displayed at all when using the bk, ft, lf, rt, up, dn format?

**Comment by Saijin-Naib** [comment]
I've not tried in a long while, but last I tried, it didn't work for me either. It has been quite a few versions, though. Something to check this week!

I'll pull a skybox from Quake2 :D

**Comment by Saijin-Naib** [comment]
![image](https://user-images.githubusercontent.com/19295950/105738557-267af680-5f05-11eb-86d1-f3bdeeb3e2da.png)
It doesn't tile right, but it does load in the faces.

![image](https://user-images.githubusercontent.com/19295950/105738875-82457f80-5f05-11eb-9842-911ddf2637e0.png)

@NEDJIMAbelgacem , any idea why the skybox didn't tile properly?
[quake2_skybox.zip](https://github.com/qgis/QGIS/files/5868160/quake2_skybox.zip)

**Comment by Saijin-Naib** [comment]
I've created a debug skybox, and it looks like some of the faces/normals are flipped.
![image](https://user-images.githubusercontent.com/19295950/105744791-942a2100-5f0b-11eb-953a-9d84bdded71b.png)
[debug_skybox.zip](https://github.com/qgis/QGIS/files/5868484/debug_skybox.zip)

**Comment by Saijin-Naib** [comment]
https://user-images.githubusercontent.com/19295950/105747107-55e23100-5f0e-11eb-97ed-74301403aa47.mp4

Another interesting behavior I'm observing is that applying the skybox seems to:  
1) Change the "home" viewport
2) Flip/rotate the origin of the viewport
  A) You are no longer looking "down" from the top at your model/surface, but rather from Back to Front.
3) Zoom To Full Extent seems to not function as expected once a Skybox is applied

**Comment by Saijin-Naib** [comment]
https://user-images.githubusercontent.com/19295950/105896232-8ac0b780-5fe4-11eb-8145-e9cc2eea7dd9.mp4

So, it would appear that the "home" gets broken IF you do not set the 3D View up using a Type (DEM Raster Layer) BEFORE you set up the skybox.

If you set that up first, then set the skybox, then the zoom to extent, home, and navigation are all as they have been.

Faces stll seem to be flipped inside-out, though.

Updated debug skybox here:  
![debug_skybox_ft](https://user-images.githubusercontent.com/19295950/105896387-b8a5fc00-5fe4-11eb-957d-707ab96692d9.png)
![debug_skybox_bk](https://user-images.githubusercontent.com/19295950/105896389-b93e9280-5fe4-11eb-98e0-417721904190.png)
![debug_skybox_up](https://user-images.githubusercontent.com/19295950/105896391-b93e9280-5fe4-11eb-967a-07da6f5f7969.png)
![debug_skybox_dn](https://user-images.githubusercontent.com/19295950/105896393-b93e9280-5fe4-11eb-88a0-506aa8e353a1.png)
![debug_skybox_rt](https://user-images.githubusercontent.com/19295950/105896394-b9d72900-5fe4-11eb-8b13-bf31a9922ff7.png)
![debug_skybox_lf](https://user-images.githubusercontent.com/19295950/105896395-b9d72900-5fe4-11eb-9796-624e40d9e8df.png)
[debug_skybox_265px.zip](https://github.com/qgis/QGIS/files/5875669/debug_skybox_265px.zip)

**Comment by NEDJIMAbelgacem** [comment]
>  3dview_test.mp4 
> So, it would appear that the "home" gets broken IF you do not set the 3D View up using a Type (DEM Raster Layer) BEFORE you set up the skybox.
> 
> If you set that up first, then set the skybox, then the zoom to extent, home, and navigation are all as they have been.
> 
> Faces stll seem to be flipped inside-out, though.
> 
> Updated debug skybox here:
> ![debug_skybox_ft](https://user-images.githubusercontent.com/19295950/105896387-b8a5fc00-5fe4-11eb-957d-707ab96692d9.png)
> ![debug_skybox_bk](https://user-images.githubusercontent.com/19295950/105896389-b93e9280-5fe4-11eb-98e0-417721904190.png)
> ![debug_skybox_up](https://user-images.githubusercontent.com/19295950/105896391-b93e9280-5fe4-11eb-967a-07da6f5f7969.png)
> ![debug_skybox_dn](https://user-images.githubusercontent.com/19295950/105896393-b93e9280-5fe4-11eb-88a0-506aa8e353a1.png)
> ![debug_skybox_rt](https://user-images.githubusercontent.com/19295950/105896394-b9d72900-5fe4-11eb-8b13-bf31a9922ff7.png)
> ![debug_skybox_lf](https://user-images.githubusercontent.com/19295950/105896395-b9d72900-5fe4-11eb-9796-624e40d9e8df.png)
> [debug_skybox_265px.zip](https://github.com/qgis/QGIS/files/5875669/debug_skybox_265px.zip)

Hi @Saijin-Naib 
The skybox should be seen from inside so the orientation is a bit tricky, when developing I just used this online tool to convert to 6 faced cube maps: https://matheowis.github.io/HDRI-to-CubeMap/
The orientations of these faces looks incorrect for me : (

**Comment by Saijin-Naib** [comment]
I guess I'll have to re-test when the changes in #41303 get merged to see if the existing skyboxes from iDTech and other games work properly, as well as the debug skybox.

Thanks!

**Comment by NEDJIMAbelgacem** [comment]
> The orientation of the faces I created for the debug skybox? The X/Y are in image coordinate space, not skybox coordinate space.
> 
> I guess I'll have to re-test when the changes in #41303 get merged to see if the existing skyboxes from iDTech and other games work properly, as well as the debug skybox.
> 
> Thanks!

Ah yes I thought the axis were for debugging as well. Also I need to mention that opengl uses Y as the vertical axis as opposed to the common Z convention

**Comment by Saijin-Naib** [comment]
> Ah yes I thought the axis were for debugging as well. 

They will/would be once I get them into an engine to test. I no longer have my mapping tools for iDTech games, so once I get setup there, I'll remake the set to be in Skybox coordinate space instead of Image coordinate space.

> Also I need to mention that opengl uses Y as the vertical axis as opposed to the common Z convention

Of course, why make anything consistent or simple? Too easy 🤣

**Comment by kannes** [comment]
@Saijin-Naib you can use the [Quake shareware](https://www.quaddicted.com/files/idgames2/idstuff/quake/quake106.zip) with the [Quakespasm engine](http://quakespasm.sourceforge.net/download.htm). Then load the start map, enter noclip mode ("noclip" in the console) and load the skybox (should be "loadsky $prefix"). The [spawnpoint has an angle of 90](https://github.com/fzwoch/quake_map_source/blob/master/start.map#L9185) (should be East/Left I guess).

**Comment by Saijin-Naib** [comment]
Feels good to get back into this after like... 15 years, haha.
![image](https://user-images.githubusercontent.com/19295950/107285370-0d0d9a80-6a2d-11eb-8271-3fef0cc87fe0.png)
Now in TrenchBroom, I can see that the images for LF/DN are kind of weird still. So now I'm completely lost.

**Comment by kannes** [comment]
I think this might need to be reopened, maybe with a bit of clarification in the top post for the format that is wanted?

**Comment by Saijin-Naib** [comment]
This might fit well with new Lutra/NR funding for Digital Twins

**Comment by kannes** [comment]
Just tried again but for me the sky goes black if I enable and setup a skybox. I did try with MSAA on and off.

Is it working for you in 4.2 @Saijin-Naib?

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta charset="utf-8" /></head><body>

QGIS version | 4.2.0-Belém do Pará
-- | --
QGIS code branch | Release 4.2
 
Libraries
Qt version | 6.11.1
Python version | 3.14.6
GDAL version | 3.13.1 — Iowa City
PROJ version | 9.8.1
EPSG Registry database version | v12.029 (2025-10-02)
GEOS version | 3.14.1-CAPI-1.20.5
SFCGAL version | No support
GeographicLib version | No support
SQLite version | 3.53.3
PDAL version | 2.10.1
PostgreSQL client version | 18.4
SpatiaLite version | 5.1.0
QWT version | 6.3.0
QScintilla2 version | 2.14.1
OS version | Manjaro Linux
 
Active Python plugins
MetaSearch | 0.3.6
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99

</body></html>

**Comment by Saijin-Naib** [comment]
<img width="1344" height="751" alt="Image" src="https://github.com/user-attachments/assets/243e1b9c-4d2d-48ea-9a39-fe37df1d7f68" />

It renders, though I may have made my test skybox images incorrectly way back, it seems.

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta charset="utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
hr { height: 1px; border-width: 0; }
li.unchecked::marker { content: "\2610"; }
li.checked::marker { content: "\2612"; }
</style></head><body>

QGIS version | 3.44.10-Solothurn
-- | --
QGIS code branch | Release 3.44
 
Libraries
Qt version | 6.11.0 (Compiled)6.11.1 (Running)
Python version | 3.14.3 (Compiled)3.14.5 (Running)
GDAL version | 3.13.0 (Compiled)3.13.2 (Running) — Iowa City
PROJ version | 9.8.1
EPSG Registry database version | v12.029 (2025-10-02)
GEOS version | 3.14.1-CAPI-1.20.5
SQLite version | 3.53.1 (Compiled)3.53.4 (Running)
PDAL version | 2.10.0 (Compiled)2.10.1 (Running)
PostgreSQL client version | 18.4
SpatiaLite version | 5.1.0
QWT version | 6.3.0
QScintilla2 version | 2.14.1
OS version | Alpine Linux v3.24
 
Active Python plugins
MetaSearch | 0.3.6
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99

</body></html>QGIS version
3.44.10-Solothurn
QGIS code branch
[Release 3.44](https://github.com/qgis/QGIS/tree/release-3_44)
 
Libraries
Qt version
6.11.0 (Compiled)
6.11.1 (Running)
Python version
3.14.3 (Compiled)
3.14.5 (Running)
GDAL version
3.13.0 (Compiled)
3.13.2 (Running) — Iowa City
PROJ version
9.8.1
EPSG Registry database version
v12.029 (2025-10-02)
GEOS version
3.14.1-CAPI-1.20.5
SQLite version
3.53.1 (Compiled)
3.53.4 (Running)
PDAL version
2.10.0 (Compiled)
2.10.1 (Running)
PostgreSQL client version
18.4
SpatiaLite version
5.1.0
QWT version
6.3.0
QScintilla2 version
2.14.1
OS version
Alpine Linux v3.24
 
Active Python plugins
MetaSearch
0.3.6
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99
```
