### ISSUE TITLE
Default style with action does load on layer open from Postgres

### ISSUE THREAD

**Issue by Jakob-Lanstorp** [qgis/QGIS#32994]
When saving a default style with an action included to postgres, it does appear in the qgis ui when the layer is loaded from postgres to qgis. If you open the layer properties the action is present. When clicking ok to the property dialog the action is now available from the qgis ui - without changing anything.

**Comment by gioman** [comment]
Really not clear to me what this is about and how to replicate, would you mind adding specific detailed steps or a screencast? thanks.

**Comment by Jakob-Lanstorp** [comment]
1. Open a layer from postgres that has a default style where an action is included.

QGIS does not recognize that the layer has an action (in the default style), i.e. the Action button is disabled:

![Capture](https://user-images.githubusercontent.com/8887576/69334133-5a4ff180-0c5a-11ea-953a-0db2755e7547.PNG)

2. Open the layer properties dialog and then just close it again - doing nothing. Now the Action button is enabled - and not before.

![Capture1](https://user-images.githubusercontent.com/8887576/69334731-b0716480-0c5b-11ea-9f07-0850969c3ef7.PNG)

**Comment by Jakob-Lanstorp** [comment]
Using Microsoft Windows 10 Enterprise 2016 LFSB and OSGEO QGIS 3.10.0

**Comment by elpaso** [comment]
I cannot reproduce on Linux/Master.

**Comment by Jakob-Lanstorp** [comment]
After installing QGIS 3.10 I can no longer reproduce this issue. Seems to be fixed in 3.10.
