### ISSUE TITLE
QGIS crash while closing

### ISSUE THREAD

**Issue by tilmanb** [qgis/QGIS#32998]
## User Feedback

after closing QGIS, having clicked "discard" ("verwerfen" in geman translation) on the dialog asking whether i wanted to save changes to the project.

## Report Details

*Crash ID*: 60c0093ac9d5b8f56929417062eebec43d94ece2

*Stack Trace*
<pre>
QWidget::actions :
QMenu::clear :
QgisApp::refreshProfileMenu :
QMetaObject::activate :
QMetaObject::activate :
QFileSystemWatcher::`default constructor closure' :
QMetaObject::activate :
QFileSystemWatcher::directoryChanged :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
QMessageBox::showEvent :
QMessageBox::critical :
QgisApp::QgisApp :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.8.2-Zanzibar
QGIS code revision: 4470baa1a3
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by roya0045** [comment]
Please update to the latest verison.

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
