### ISSUE TITLE
No colour when you select a feature

### ISSUE THREAD

**Issue by solisgb** [qgis/QGIS#32993]
Qgis 10.0 (QGIS-OSGeo4W-3.10.0-2-Setup-x86_64.exe installer) OS version Windows 10 18362.418  

Add a shapefile to map
Click the button Select feature(s)
Click on one feature or more
The selected feature(s) don't show(s) the yellow colour for selected features (default); this is the bug 
In the attribute table the clicked feature is selected ok

Thanks

**Comment by gioman** [comment]
Can't confirm here, have you tried with a new QGIS profile or even on a different machine?

**Comment by alexbruy** [comment]
Not reproducible.
