### ISSUE TITLE
Date field values are shown as NULL in attribute table form view

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#33000]
I have a layer with a time field
![image](https://user-images.githubusercontent.com/7983394/69363723-4a9fcf80-0c91-11ea-82bd-9ecb4abc1bc9.png)
The values display in attribute table, in table view
![image](https://user-images.githubusercontent.com/7983394/69363815-6efbac00-0c91-11ea-9bf2-7920e7d4991f.png)
not in form view
![image](https://user-images.githubusercontent.com/7983394/69363911-a10d0e00-0c91-11ea-9ddb-bd463fc802b8.png)

Version de QGIS | 3.10.0-A Coruña | Révision du code | 07378a71cb
-- | -- | -- | --
Compilé avec Qt | 5.11.2 | Utilisant Qt | 5.11.2
Compilé avec GDAL/OGR | 3.1.0dev | Utilisé avec GDAL/OGR | 3.1.0dev
Compilé avec GEOS | 3.8.0-CAPI-1.13.1 | Utilisé avec GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
Version du client PostgreSQL | 11.5 | Version de SpatiaLite | 4.3.0
Version de QWT | 6.1.3 | Version de QScintilla2 | 2.10.8
Compilé avec PROJ | 7.0.0 | Fonctionne avec PROJ | Rel. 7.0.0, March 1st, 2020
OS Version | Windows 10 (10.0) | Cette copie de QGIS dispose d'une sortie de débogage.
Extensions Python actives | arrayplus; DissolveWithStats; firstaid; GroupStats; MapsPrinter; MapsPrinter-add_batch_export; pluginbuilder3; PluginLoadTimes; plugin_reloader; Qgis2threejs; db_manager; MetaSearch; processing

**Comment by gioman** [comment]
>  not in form view

the horror. @DelazJ can you establish if is a regression, of example it is ok in the current and old ltr?
