### ISSUE TITLE
QGIS can't identify GDA2020 tab file v17

### ISSUE THREAD

**Issue by bzzzggz** [qgis/QGIS#33007]
**Describe the bug**

**How to Reproduce**
Type1:
1. The data are download from VIC state government official database. data.vic.gov.au
2. The format is GDA2020 Zone 55 in tab file Mapinfo v17 and after. 
3, After loading into QGIS, the CRS are identified as user-defined CRS, not EPSG:7855.
Type2:
1. Export sample data into GDA2020 datum (EPSG:7855) in QGIS. 
2. Load the new GDA2020 data into QGIS.
3. QGIS wrongly identify the datum as EPSG:32755

**QGIS and OS versions**

<

QGIS version | 3.8.1-Zanzibar | QGIS code revision | dcd95cc648
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.0 | Running against GEOS | 3.7.2-CAPI-1.11.0 b55d2125
PostgreSQL Client Version | 9.2.4 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Windows 10 (10.0) |   |  

>

**Additional context**

**Comment by nyalldawson** [comment]
If you upgrade to 3.10 this should be resolved now

**Comment by bzzzggz** [comment]
> If you upgrade to 3.10 this should be resolved now

Thanks for your reply, I tested these steps on 3.10.
For Type1: QGIS wrongly identify EPSG 7855 as EPSG 5551.
      Type2: Still goes to EPSG: 32755

**Comment by nyalldawson** [comment]
Ok, looking into this, it's not a QGIS issue, rather it's an issue in the GDAL library.

**Comment by nyalldawson** [comment]
(and will need to be reported at https://github.com/OSGeo/gdal)

**Comment by nyalldawson** [comment]
Fixed by https://github.com/OSGeo/gdal/commit/e14c9aedfcb8943411e6498c719cbf2db63d8684

**Comment by nyalldawson** [comment]
Reopening -- following the GDAL fix, there's some work still required on QGIS' side to correctly handle this...
