### ISSUE TITLE
Basemaps Don't Load on Project Open

### ISSUE THREAD

**Issue by happydeb** [qgis/QGIS#33009]
I solved this problem by going through the steps to reproduce and explain it for this ticket. I post here for the benefit of others like me who know how to drive QGIS but don't know anything about what's under the hood (or bonnet If your British ;-)

So I upgrade to Corsuna from Madiera with a project in progress. No basemaps appear when I open my project but I get a popup giving me suggestions for the correct  geographic CRS and the transformation to the "destination" CRS.  I choose the destination CRS that I recall my "projected" project is in for each of several layers that the pop up indicates are problematic.

I click "ok" and nothing happens, no base map! ( I spend several hours trying different things, give up, cry, go back try again).

Then it occurs to me to change the project CRS from my projected setting (which matches my projected CAD file overlays and undefined digitizing layers) to a geographic CRS. A new popup window appears and give suggestions for the transformation and I pick the geographic one.
TA DA! Base maps appear.... in southern California as they're supposed to.

It seems like a simple "fix" as far as bugs go. Add more instructions on what to do in the pop-up box. So, if I'm not alone, maybe this will help you too!

**Comment by gioman** [comment]
@happydeb this is likely duplicated of https://github.com/qgis/QGIS/issues/3297

Please try/stay on QGIS stable release (3.4) and leave feedback if it "solves" the issue or not. Thanks.

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
