### ISSUE TITLE
Add a smoothing motion zoom, something similar to a web map viewer

### ISSUE THREAD

**Issue by juanca5195** [qgis/QGIS#33017]
I would like to know how I can modify the movement of the view to make the movement smoother, can this be modified with a plugin?

**Comment by gioman** [comment]
Hi, please ask questions on the users or developers mailing lists, gis stackexchange or the IRC channel. Thanks.

**Comment by juanca5195** [comment]
But this is a Feature Request

**Comment by gioman** [comment]
> I would like to know how I can modify the movement of the view to make the movement smoother, can this be modified with a plugin?

sounds a question to me. You may want to rephrase it and also add more details, the title and description seems vague (to me).

**Comment by juanca5195** [comment]
Thanks for the recommendation, I imagined that the short message would be a problem but I didn't want you to get tired reading, I'll try again if you let me.
