### ISSUE TITLE
Python API QgsField.constraints().setConstraint does not work

### ISSUE THREAD

**Issue by szppaks** [qgis/QGIS#33015]
I can't set field constraint by python API.

I've tried three ways:

>>>
al=iface.activeLayer()
mezo=al.fields().indexFromName('azonosito')

'''1.'''
mezo.constraints().ConstraintNotNull
>>>1
mezo.constraints().ConstraintNotNull=0
mezo.constraints().ConstraintNotNull
>>>1

'''2.'''
>>>
fico=mezo.constraints()
fico
>>><qgis._core.QgsFieldConstraints object at 0x000001750D45ECA8>
fico.ConstraintNotNull
>>>1
fico.ConstraintNotNull=0
fico.ConstraintNotNull
>>>0
mezo.constraints().setConstraint(fico.ConstraintNotNull,mezo.constraints().ConstraintOriginLayer)
mezo.constraints().ConstraintNotNull
>>>1
fico.ConstraintNotNull
>>>0
'''3.'''
>>>
mezo.constraints().setConstraint(fico.ConstraintNotNull)
mezo.constraints().ConstraintNotNull
>>>1
fico.ConstraintNotNull
>>>0

**QGIS and OS versions**
QGIS 3.8.0
Windows10

**Comment by nyalldawson** [comment]
You need to use QgsVectorLayer.setFieldConstraint instead.
