### ISSUE TITLE
ALL Function Help strings missing from Field Calculator

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS#33016]
Currently in my self compiled version of QGIS, ALL help strings for functions in the Field Calculator are missing. 
I asked on the mailing list and Andreas has a version from https://github.com/qgis/QGIS/commit/f1e6745fe7 which also misses them?

See screenshot, note that it is not only for format_date but for all functions:

![Screenshot-20191122144234-854x714](https://user-images.githubusercontent.com/731673/69430810-b720da00-0d36-11ea-8536-d70fe5cee04d.png)

**Comment by rduivenvoorde** [comment]
Self-confirmed here on a Windows nightly (Osgeo4W64)  of 8 days ago too:
https://github.com/qgis/QGIS/commit/6180c59fa8b5aca776a5776792a3f20843b17946

**Comment by pigreco** [comment]
confirm

`OSGeo4W`

**Comment by Korto19** [comment]
confirm

**Comment by rduivenvoorde** [comment]
Thanks @nyalldawson , tested and working again!!

![Screenshot-20191125203318-1188x661](https://user-images.githubusercontent.com/731673/69571686-ea779900-0fc2-11ea-9020-9f422231f262.png)
