### ISSUE TITLE
KML Export transposes Lat and Lon values

### ISSUE THREAD

**Issue by aharfoot** [qgis/QGIS#33014]
**OSGeo4W QGIS 3.10.0 x64 running on Win10**

If I export points, lines or polygons to KML the order of the coordinates are transposed in the resulting KML. Steps to reproduce:

1. Create a 'New Temporary Scratch Layer', type Point
2. Digitise a point
3. Stop editing, save changes, and export the layer, saving it as a KML file.
4. Load the KML back into QGIS if it isn't automatically and observe the transposed data.

**Comment by aharfoot** [comment]
Replicated on OSGeo4W QGIS 3.4.13 x64 running on Win10

**Comment by elpaso** [comment]
Works for me on Linux/master.

**Comment by aharfoot** [comment]
Works as expected on Standalone QGIS 3.10.0 x64 running on Win10. I suspect that this install is a slightly older version of 3.10 as it is using Proj 5.2, whereas the installs experiencing the bug are using Proj 6.2.1

**Comment by elpaso** [comment]
That might be the case, I tested proj 5.
