### ISSUE TITLE
SAGA Gradient vectors from surface fails in QGIS 3.10

### ISSUE THREAD

**Issue by mudomau** [qgis/QGIS#33020]
Not sure if this is QGIS related, but as SAGA is integrated in the release I got, I figured it might be of interest.

**Describe the bug**

The "Gradient vectors from surface" SAGA processing tool fails to generate an output.
The same tool works as expected in QGIS 3.8.

**How to Reproduce**
Input TIF DEM, 
check CRS, 
use tool (nearest neighbor, arrow centered on cell, step 1, size range 0 to 100, save to temp file)

**QGIS and OS versions**
Windows 10, QGIS 3.10

**Additional context**
Works fine in QGIS 3.8

**Comment by roya0045** [comment]
related to #35953 ?

**Comment by gioman** [comment]
> related to #35953 ?

it is duplicated, the correct reference is https://github.com/qgis/QGIS/issues/32953
