### ISSUE TITLE
[Value Relation widget] does not work if I use a default value

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#33046]
The widget in question works fine but if I write a value or an expression within the `default value`, the form does not display any value.

![image](https://user-images.githubusercontent.com/7631137/69496238-55947300-0ed0-11ea-9bd8-4f32c1ef4c14.png)

## how to replicate it:

I imported two layers:
1. `province_siciliane` (polygon)
2. `comuni_siciliani` (polygon)
and I created a new `PUNTO` layer (point)
on the latter I used the Value Relation widget to dynamically filter, after setting a province, the municipalities.
As soon as I enter a default value in the province field, nothing appears on the form.
![image](https://user-images.githubusercontent.com/7631137/69496486-ebc99880-0ed2-11ea-8507-5b43c9909713.png)

the default value is present in the attributes table

---

I attach a `gpkg` with data and project.

[drilldown_form_multiple.zip](https://github.com/qgis/QGIS/files/3883695/drilldown_form_multiple.zip)

---

## OS and Version QGIS

```
Versione di QGIS 3.10.0-A Coruña
Revisione codice QGIS 6ffa89eb3e
Compilato con Qt 5.11.2
Esecuzione con Qt 5.11.2
Compilato con GDAL/OGR 3.0.2
Esecuzione con GDAL/OGR 3.0.2
Compilato con GEOS 3.8.0-CAPI-1.13.1
Esecuzione con GEOS 3.8.0-CAPI-1.13.1 
Compiled against SQLite 3.29.0
Running against SQLite 3.29.0
Versione client PostgreSQL 11.5
Versione SpatiaLite 4.3.0
Versione QWT 6.1.3
Versione QScintilla2 2.10.8
Compiled against PROJ 6.2.1
Running against PROJ Rel. 6.2.1, November 1st, 2019
OS Version Windows 10 (10.0)
```

**EDIT:**

Video: https://youtu.be/Rg2IUuRtIqI

**Comment by Korto19** [comment]
I confirm

**Comment by bellanz80** [comment]
I confirm

**Comment by gioman** [comment]
> I attach a `gpkg` with data and project.

seems is only the data.

**Comment by bellanz80** [comment]
the QGZ project is contained in the Geopack

**Comment by gioman** [comment]
> the QGZ project is contained in the Geopack

nope.

**Comment by Korto19** [comment]
I want to clarify that the project in in the gpkg file and that is required almost Qgis 3.8 for read it

**Comment by gioman** [comment]
> I want to clarify that the project in in the gpkg file and that is required almost Qgis 3.8 for read it

I tried with 3.10 and master.

**Comment by pigreco** [comment]
The project is inside the gpkg and to read it you need to make a connection via the QGIS browser
![image](https://user-images.githubusercontent.com/7631137/69526481-89bc7200-0f6a-11ea-83ce-f6e7ac35ab56.png)

**Comment by gioman** [comment]
> The project is inside the gpkg and to read it you need to make a connection via the QGIS browser

3.10 on Windows here:

![Screenshot_20191125_090340](https://user-images.githubusercontent.com/1951107/69526650-989f2680-0f62-11ea-8c9c-2bd7e986fa68.png)

**Comment by pigreco** [comment]
@gioman 

I made a video demonstrating the opening of the issue (attached at the end of the text issue)

**Comment by Korto19** [comment]
I load the project from gpgk file in Browser like this screenshot
![immagine](https://user-images.githubusercontent.com/36882050/69532927-1f5dfe80-0f77-11ea-91c4-710d223a00fb.png)

**Comment by gioman** [comment]
> I load the project from gpgk file in Browser like this screenshot

here it does not show the project inside the gpkg. Have you uploaded the right file? Can't you just attach the project as a separate file? Thanks.

**Comment by elpaso** [comment]
@gioman I can open the project from the GPKG just fine.

**Comment by gioman** [comment]
> @gioman I can open the project from the GPKG just fine.

@elpaso just saying what I see here. Anyway I think i found the reason: if the gpkg is in "c" I see the project saved in it, if is in a network drive mapped with a drive letter then it does not (but layers do show, and load).

**Comment by elpaso** [comment]
@pigreco there is an error in the relation definition for the field "comune" on layer PUNTO: the "Key column" must point to `fid` instead of `cod_prov` or the relation would not work correctly.

**Comment by elpaso** [comment]
> > @gioman I can open the project from the GPKG just fine.
> 
> @elpaso just saying what I see here. Anyway I think i found the reason: if the gpkg is in "c" I see the project saved in it, if is in a network drive mapped with a drive letter then it does not (but layers do show, and load).

Another bug I suppose...

**Comment by elpaso** [comment]
Works for me, you just have to use the correct column for default values, the value-relation for "provincia" uses `COD_PROV` for "key column" and `DEN_PCM` for value, the "key column" is the "foreign key" of the related model and `'Enna'` is **not** a value from the `COD_PROV` column, you must use the correct value (`86`) in this case.

**Comment by pigreco** [comment]
@elpaso 
Thanks, now work well
