### ISSUE TITLE
Node tool (snapping tool) not work for new features in  Postgis View

### ISSUE THREAD

**Issue by XmaziaX** [qgis/QGIS#33047]
**Node tool (snapping tool) not working for new features in  Postgis View's layers (after save).**

Same issues was in version 2.18.17 and was fixed in 2.18.18.
I just checked in 2.18.19 and it works fine there as well.

**How to Reproduce**
1. Create Postgis view, triggers for etc. and add to QGis.
2. Start editing
3. Add features (do not save) - snapping for this new features working correctly.
4. Save layer.
5. Now, snapping for this features not working - objects are not tracked.

After move this features (and ctrl + z) feature becomes snappable.
Same if you split this features.

**QGIS**:  3.4.13 , 3.10.0, 3.11.0      
**POSTGIS**: 2.3    
**OS**:  WIN10

**Comment by XmaziaX** [comment]
Code to reproduce the situation, but with a polygon geometry.
[view_bug.txt](https://github.com/qgis/QGIS/files/3883996/view_bug.txt)

I found old similar problem, but with Oracle tables.
[https://issues.qgis.org/issues/12690]

**Comment by lbartoletti** [comment]
Ping @haubourg and @troopa81

**Comment by XmaziaX** [comment]
Just readed changelog for 3.10 and found new feature:   Add circular data dependencies
**"We improved the dependencies support in QGIS by allowing refreshing the modified layer itself"** - This is solution to the problem. Unfortunately - these settings cannot be saved to the default style and must be set manually each time...

**Comment by troopa81** [comment]
> Unfortunately - these settings cannot be saved to the default style and must be set manually each time...

@XmaziaX Just tested with 3.10 and data dependencies are well saved in the QGIS project. In 3.4 you can also save them (but you can define the modified layer as a dependecy, it's a 3.10 nex feature)

**Comment by XmaziaX** [comment]
> 
> @XmaziaX Just tested with 3.10 and data dependencies are well saved in the QGIS project. In 3.4 you can also save them (but you can define the modified layer as a dependecy, it's a 3.10 new feature)
>
Ok, it works.
I thought it was written in style (relationship is set in layer properties).
I have the impression that the solution from 2.18.19 (after inserting the object in view, using the trigger with insert clause, the object was snapable) worked more efficiently.
But of course I can be wrong :)
Thanks for the answer
