### ISSUE TITLE
Rotating vector features causes QGIS-crash

### ISSUE THREAD

**Issue by georik124** [qgis/QGIS#33059]
Rotating a vector-feature (point / line / polygon) with the "Rotate Feature"-function causes a crash (Tested with geometries from shp-files and postgis).

 QGIS 3.10.0
 Windows 10, 64 bit

**Comment by gioman** [comment]
Already fixed.

**Comment by georik124** [comment]
I am new to github. Now i can find the closed issues. Thank you very much!
