### ISSUE TITLE
Online C++ API for 3.4 landing page has no way to navigate to the actual docs

### ISSUE THREAD

**Issue by ricardogsilva** [qgis/QGIS#33058]
When visiting the [C++ API landing page for version 3.4](https://qgis.org/api/3.4/) there is no way to navigate the actual API docs.

This happens because the docs landing page is missing the navigation area.

To be clear, what is missing is the stuff highlighted in red here (showing the same page but for version 3.2):

![qgis_api_3_2_annotated](https://user-images.githubusercontent.com/732010/69537564-4d900e00-0f78-11ea-852f-20893dea786e.png)

in 3.4 I get:

![qgis_api_3_4](https://user-images.githubusercontent.com/732010/69537604-5da7ed80-0f78-11ea-9b24-1cc7b4f603a6.png)

The docs for QGIS testing (currently 3.11) do not have this problem.

**Comment by Gustry** [comment]
I think this ticket should go in the QGIS-Documentation https://github.com/qgis/QGIS-Documentation/issues

**Comment by ricardogsilva** [comment]
From glancing at the QGIS-Documentation repo, it seems the QGIS C++ API docs are not under its scope.

Seems to me that the C++ API docs are built from the code that is in main QGIS repo. So I guess the issue is in the right place. Should I take your answer @Gustry, as a definitive request to move this over to QGIS-Documentation? Or are you not certain?

**Comment by SrNetoChan** [comment]
That is definitely not in the QGIS-Documentation repo scope. I am not sure where that is managed, but it may attract more attention here than the docs repo.

**Comment by ricardogsilva** [comment]
This seems to be fixed now
