### ISSUE TITLE
Mask properties are displayed in text settings background panel

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#33056]
In Style manager, add a new text format
in the text settings dialog, enable the background panel: you get Mask properties instead. The background's are offset under "Shadow" panel and shadow properties are no longer available.
![image](https://user-images.githubusercontent.com/7983394/69534695-98ab2080-0f7a-11ea-81ec-9cc58c4d9b23.png)
@mhugo?

QGIS code revision : f9f00d3388

**Comment by mhugo** [comment]
@alexbruy Thanks for the fix !
