### ISSUE TITLE
Add the possibility to change font of label in rules renderer (symbology)

### ISSUE THREAD

**Issue by aurorehertout** [qgis/QGIS#33062]
I work in geology and we have some strange notations for geological formations. I need to write a symbology in rules definition. 
I define a label like "¥GP, Dépôts de pente consolidés ferruginés (formations périglaciaires) - 33" where "¥GP" is notation. But we have our font to display this and it's not true to keep this in the interface (layers dock widget). So, my labels can have personal fonts. My legend in composer too. But I have a contradiction in my layers window.

Thank you in advance to upgrade the rules renderer! :)

**Comment by gioman** [comment]
>  But we have our font to display this and it's not true to keep this in the interface (layers dock widget). So, my labels can have personal fonts. My legend in composer too. But I have a contradiction in my layers window.

I'm lost here. Maybe a screenshot/cast could help.

**Comment by nyalldawson** [comment]
Closed due to lack of feedback
