### ISSUE TITLE
Universal Polar Stereographic Projections (UPSS & UPSN) are flipped in QGIS 3.10

### ISSUE THREAD

**Issue by simondreutter** [qgis/QGIS#33077]
**Describe the bug**
Since QGIS version 3.10 the map view is flipped/mirrored and rotated, when changing the Project CRS to either UPSS (EPSG:32761) or UPSN (EPSG:32661). Other polar stereographic projections like the IBCAO projection (EPSG:3996) are looking normal.

**How to Reproduce**
Change the Project CRS to UPSS or UPSN.

**QGIS and OS versions**
QGIS version | 3.10.0-A Coruña | QGIS code revision | 6ffa89eb3e
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.2 | Running against GDAL/OGR | 3.0.2
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.2.1 | Running against PROJ | Rel. 6.2.1, November 1st, 2019
OS Version | Windows 10 (10.0)
Active python plugins | autoSaver; cruisetools; latlontools; NNJoin; pluginbuilder3; plugin_reloader; pointsamplingtool; PosiView; profiletool; quick_map_services; shapetools; valuetool; db_manager; MetaSearch; processing

**Comment by nyalldawson** [comment]
@rouault got any clues on this particular one? Anything unusual about these particular projections in proj6?

**Comment by rouault** [comment]
> Anything unusual about these particular projections in proj6?

Yes... Should be fixed by PROJ https://github.com/OSGeo/PROJ/commit/a2b2663d2a35c9ff6ff56e9348f166a99cc618a4

**Comment by rouault** [comment]
As a workaround use EPSG:5041 instead of EPSG:32661 and EPSG:5042 instead of EPSG:32761

**Comment by nyalldawson** [comment]
Thanks @rouault !
