### ISSUE TITLE
Crash ID: 8bed21098f22d18766e0d226e76e4375e19d2e52   

### ISSUE THREAD

**Issue by eyalosbalos** [qgis/QGIS#33081]
Stack Trace   proj_context_delete_cpp_context : proj_context_delete_cpp_context : proj_context_delete_cpp_context : OGRSpatialReference::~OGRSpatialReference : OGRSpatialReference::operator= : OGRSpatialReference::Release : SHPWriteObject : OGRFeatureDefn::Release : DBFWriteTuple : QgsConnectionPoolGroup::onConnectionExpired qgsconnectionpool.h:227 QMetaObject::activate : QMetaObject::activate : QApplicationPrivate::notify_helper :     QGIS Info QGIS Version: 3.4.13-Madeira QGIS code revision: 567300ccf1 Compiled against Qt: 5.11.2 Running against Qt: 5.11.2 Compiled against GDAL: 3.0.2 Running against GDAL: 3.0.2    System Info CPU Type: x86_64 Kernel Type: winnt Kernel Version: 10.0.17763

**Comment by roya0045** [comment]
That's not how you fill a ticket :/

**Comment by gioman** [comment]
> Stack Trace proj_context_delete_cpp_context

@eyalosbalos please add all the requires details. Also try with a new QGIS Profile.

**Comment by nyalldawson** [comment]
This was an upstream gdal issue (fixed now)
