### ISSUE TITLE
Crash while Copying settings from 3d view to 3d layout.

### ISSUE THREAD

**Issue by ReghardNell** [qgis/QGIS#33098]
## User Feedback

Layout manager

I have existing 3D 

Crash while Copying settings from 3d view to 3d layout.

Kind regards

skrap.nell@gmail.com

## Report Details

**Crash ID**: [f85ba097835d240b07f20ee79d8f1de40fc0007e]('https://github.com/qgis/QGIS/search?q=f85ba097835d240b07f20ee79d8f1de40fc0007e&type=Issues')

**Stack Trace**
<pre>
Qt3DRender::Render::Renderer::updateVAOWithAttributes :
Qt3DRender::Render::Renderer::requiresVAOAttributeUpdate :
Qt3DRender::Render::Renderer::prepareCommandsSubmission :
Qt3DRender::Render::Renderer::doRender :
Qt3DRender::Render::Renderer::render :
Qt3DRender::Render::AbstractRenderer::~AbstractRenderer :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.0-A Coru�a
QGIS code revision: 6ffa89eb3e
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by ReghardNell** [comment]
![image](https://user-images.githubusercontent.com/19644684/69727008-56284600-112a-11ea-9158-2a3c9b9e383c.png)

**Comment by Pedro-Murteira** [comment]
@ReghardNell Hello, I've tested this issue in QGIS 3.22.4 and 3.24.0 and I couldn't reproduce a crash. Did you come across this issue in more recent versions?

**Comment by ReghardNell** [comment]
Hi. We can close this issue. It is very old 👍
