### ISSUE TITLE
Can't use edit tools

### ISSUE THREAD

**Issue by Hristina-R** [qgis/QGIS#33102]
Software was working last night, today neither myself or my colleagues are able to edit anything. Please can you advise asap?

**Comment by gioman** [comment]
@Hristina-R Questions are supposed to be made on other channels, like the users/developers mailing lists, gis.stackexchange and the QGIS IRC channel. Anyway this could be a bug, but to help you we need much more details: QGIS version, platform, what exact operations you are doing, on what type of datasources, etc.

**Comment by Hristina-R** [comment]
[QGIS.docx](https://github.com/qgis/QGIS/files/3897220/QGIS.docx)

please see a screenshot it's the edit tool that seems to be disabled?

**Comment by Hristina-R** [comment]
It's QGIS 3.4.2

**Comment by stev-0** [comment]
Probably quite likely to be a network issue or something related to your organisational setup if a lot of people have been affected, and the nature of the issue - "it just happened".

**Comment by gioman** [comment]
@Hristina-R I agree, the most likely is to have lost write permissions in the folders where you store the data.

**Comment by Hristina-R** [comment]
@gioman what could've caused the loss of write access please?

**Comment by gioman** [comment]
> @gioman what could've caused the loss of write access please?

first you should verify this hypothesis (can you write file/folders in the same place where your data come from?). If it is verified then you should contact your IT guys as it is not a QGIS issue.

**Comment by Hristina-R** [comment]
> @gioman what could've caused the loss of write access please?
> 
> first you should verify this hypothesis (can you write file/folders in the same place where your data come from?). If it is verified then you should contact your IT guys as it is not a QGIS issue.

I just amended an excel file which already existed in the same folder and saved it.

**Comment by gioman** [comment]
> I just amended an excel file which already existed in the same folder and saved it.

try make a copy of one of your datasources and see if you can edit it in a new clean qgis project and also in an already existing project.

**Comment by bonesdad** [comment]
This topic was laid to rest long ago, but I'm experiencing the same issue on standalone 3.12.  I edited tables just the other day, now I can't edit anything.  Simple edit on a vector point layer.

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
