### ISSUE TITLE
QGIS 3.10: Broken clustering method selection in GRASS v.cluster processing algorithm?

### ISSUE THREAD

**Issue by apiszcz** [qgis/QGIS#33100]
1. QGIS DBSCAN works properly.

2. GRASS v.cluster methods do not.

3. When the user selects the Clustering method it would be helpful if the dialog entry displayed the entry. DBSCAN for example, currently it displays how many options are selected. ( 1 options selected). If the goal is to run all algorithms than perhaps a comma separate list should appear.

4. When I use the same input data and parameters with GRASS v.cluster there is no labeled cluster even though the Log output states there are clusters. The 'cat' column appears in the output with the same value as the 'fid' **_instead of the label value for the cluster_**.

DBSCAN
Registering primitives...
12 clusters found
6 outliers found

When testing Optics and 'density' methods the same result and both state clusters are found.

Optics
Registering primitives...
3 clusters found
95 outliers found

density
Registering primitives...
39 clusters found
22 outliers found

**Comment by gioman** [comment]
@apiszcz GRASS plugin or Processing toolbox?

**Comment by apiszcz** [comment]
Processing Toolbox

**Comment by apiszcz** [comment]
I just loaded the Grass 7 Tools, and it states I need a mapset context
setup. Perhaps this is my problem.

**Comment by gioman** [comment]
> I just loaded the Grass 7 Tools, and it states I need a mapset context setup.

@apiszcz now are you speaking of the GRASS plugin?

**Comment by apiszcz** [comment]
This is the startup error follows when launching 'QGIS 3.10.0 with GRASS 7.6.1' (on windows)

GRASS was not found in 'C:/PROGRA~1/QGIS 3.10/apps/grass/grass76' (GISBASE), provider and plugin will not work.

The folder with grass76 exists at 
C:\Program Files\QGIS 3.10\apps\grass\grass76

**Comment by apiszcz** [comment]
Same test with 3.8.3 installed, GRASS is detected and active. No warnings in log messages.
Same behavior from running v.cluster as 3.10.0

**Comment by i-s-o** [comment]
Is it possible your QGIS got updated, and the proper GRASS is now somewhere else? On my computer, QGIS 3.10 link reads "QGIS Desktop 3.10.0 with GRASS 7.8.0", and GISBASE points to ".../grass78". How about re-downloading and reinstalling the latest 3.10? In the about box, the "Code Revision" reads 6ffa89eb3e on mine.

**Comment by alexbruy** [comment]
Please provide clear description and test dataset.

**Comment by alexbruy** [comment]
Closed for the lack of feedback.

**Comment by cefect** [comment]
I'm having the same problem w/ v.cluster on 3.16.14. From the GRASS docs:

[By default, cluster IDs are stored as category values of the points in layer 2.](https://grass.osgeo.org/grass80/manuals/v.cluster.html)

It doesn't look like the processing tool is collecting properly .
