### ISSUE TITLE
QvariantList Field , nothing in attribute table when a single value is in the list

### ISSUE THREAD

**Issue by Loctudy** [qgis/QGIS#33108]
Using Qgis 3.10.0 on Windows and PostgeSQL 9.6
I'm connected to a table with field as an array integer
field_name integer[]

This field may have 0 or many values.

If there is a single value in this field the attribute table (in Qgis)  is empty for this field.

Also, in the Query Builder if I want to list existing values (in that field) , this return empty cells.

**Comment by dragonxtek** [comment]
I'm using Qgis 3.16.3 and PostgreSQL 12 on Linux.
I have the same issue. For fields as integer[], the query builder shows them as empty cells.
![Selection_056](https://user-images.githubusercontent.com/10552658/107243039-5fd65a80-6a0b-11eb-96ce-bcdcd7425e57.png)

**Comment by gioman** [comment]
>  I have the same issue. For fields as integer[], the query builder shows them as empty cells.

@dragonxtek cannot replicate, can you attach a dump of your table (or a sample of).

**Comment by dragonxtek** [comment]
Sure, here it is
![Selection_049](https://user-images.githubusercontent.com/10552658/107261571-396dea80-6a1e-11eb-826e-b05f14874009.png)

**Comment by gioman** [comment]
> Sure, here it is

@dragonxtek attach (as zip) a dump created with pg_dump, thanks.

**Comment by dragonxtek** [comment]
ok, I created [backup.zip](https://github.com/qgis/QGIS/files/5946016/backup.zip) as follows:

pg_dump --column-inserts --table=table_name database_name > backup.sql

**Comment by troopa81** [comment]
> If there is a single value in this field the attribute table (in Qgis) is empty for this field.

Failed to reproduce this one, it looks like it works

> For fields as integer[], the query builder shows them as empty cells.

Fixed by #43508
