### ISSUE TITLE
Python Console window not movable and eventually freezes QGIS

### ISSUE THREAD

**Issue by woodtore** [qgis/QGIS#33112]
Ubuntu 18.04
QGIS version | 3.4.13-Madeira

When I open the python console through the plugins dropbox, the python console panel covers the QGIS window. Normally I would move this python panel to another monitor and do work. When I attempt to drag the panel it wont move. If I try to close the panel nothing happens then QGIS will freeze. If I use Ctrl+Alt+P I can hide the python panel and close QGIS.
I tried purging qgis qgis-common python3-qgis python3-qgis-common and then reinstalling. No change.

**Comment by gioman** [comment]
I'm on KDE here and cannot confirm this.

**Comment by woodtore** [comment]
Solution found. I have three monitors on the machine. Altering the location of the displays through the Displays tool allowed for the Python panel to become unstuck.
