### ISSUE TITLE
Default value won't get set for uneditable field

### ISSUE THREAD

**Issue by Jean-Zombie** [qgis/QGIS#33122]
**Describe the bug**

My observation is in regard to feature addition via the attributes form.

I calculate a default value for a Boolean field with a `CASE` expression which successfully applies on update in the attribute form and is also written correctly to my postgis db layer on save. But **only**  

- if the widget is set to "editable". 

Otherwise, i.e. the Boolean field is "not editable", the `CASE` expression successfully applies on update in the attribute form **BUT** it always writes the first return value to the DB and never reaches the `ELSE` statement.

The fact that the `CASE` expression successfully applies on update in the attribute form even when "editable" is unchecked, leads me to believe this is a bug and not the intended behavior. 

**How to Reproduce**

1. Set up a Boolean field, two text fields ("field1, "field2) and define a `CASE` expression for the default value of the Boolean field:
```
CASE
WHEN (COALESCE("field1", '') = '') AND (COALESCE("field2", '') = '')
THEN FALSE
ELSE TRUE
END
```
2. Add all three fields to the form layout and set the Boolean field to "editable" and choose a checkbox widget.
3. Add a feature a watch the checkbox getting checked when you enter text in one or both text fields. Save the feature and inspect your db: It will be `TRUE` if there is input for at least one of the text fields or `FALSE` if there is no input in both text field.
4. **Uncheck "editable" for the Boolean field in the form layout.**
5. Add a feature and watch the checkbox getting checked when you enter text in one or both text fields. Save the feature and inspect your db: It will always be `FALSE`, no matter which case.
6. Flip the return values in the `CASE`expression, i.e.:
```
CASE
WHEN (COALESCE("field1", '') = '') AND (COALESCE("field2", '') = '')
THEN TRUE
ELSE FALSE
END
```
7. Repeat step 5. Now the checkbox is initially checked and gets unchecked for text input. Save the feature and inspect your db: It will always be `TRUE`, no matter which case. 

**Conclusion: When a Boolean field is set to "not editable" it's default value calculated by a `CASE` expression will never reach past the first return value and hence not be written correctly to the database, albeit being correctly visualized in the attributes form.**

**Additional context**
- I don't want the Boolean field to be editable since it will only be used by an external app. Therefore I also don't want to expose it to the attributes form. My workaround for now is to leave the field editable and set the widget type to "hidden". But for this to work I still have to add the field to the form which I'd like avoid for usability reasons.
- I observed the same behavior with reduced complexity and an if statement instead of `CASE`:
``` 
if (COALESCE("field1", '') = '',  FALSE, TRUE)
```
- I also tested everything on a text fields default value instead of a Boolean field. Same thing.

**QGIS and OS versions**
macOs Catalina 10.15.1
QGIS version | 3.10.0-A Coruña

**Comment by gioman** [comment]
> 5\. Add a feature and watch the checkbox getting checked when you enter text in one or both text fields. Save the feature and inspect your db: It will always be `FALSE`, no matter which case.

@Jean-Zombie cannot replicate anymore on 3.22.4
