### ISSUE TITLE
QGIS 3.10 Projected CRS do not display properly

### ISSUE THREAD

**Issue by CharlesPetersen** [qgis/QGIS#33129]
In QGIS 3.10, projected CRSs do not display properly. For example, the attached project file shows how the popular Gall Stereographic proj
[Projected CRS Bug.zip](https://github.com/qgis/QGIS/files/3902235/Projected.CRS.Bug.zip)
ection is mangled in version 3.10.

**Comment by gioman** [comment]
@CharlesPetersen duplicate of https://github.com/qgis/QGIS/issues/30569 ?

**Comment by CharlesPetersen** [comment]
Looks like the same problem reported in #30569 and #33121 .
My OS: Windows 10 Enterprise N Version 1809
