### ISSUE TITLE
server wfs3 strange behaviour of coordinates

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS#33127]
First steps using QGIS-server wfs3. QGIS-3.10 server in Apache on Windows10server.
This zip contains a shapefile of zip codes of one city in The Netherlands. 
When 'browsing' the wfs3 interface, sometimes the coordinates are wrong.

[testdata.zip](https://github.com/qgis/QGIS/files/3901365/testdata.zip)

Originally it was in a Oracle db when I observed the behaviour, but also if I use this shapefile I see it.
To reproduce:
- load the shp file (EPSG:28992) in a project, save the project, but do not forget to set the server properties in the projectfile (so add pc6 to the wfs etc)
- configure QGISserver for example using the httpd_qgis.conf example file from the osgeo4w64/httpd directory, BUT adding the path to the project file using for example:
 `DefaultInitEnv QGIS_PROJECT_FILE "d:\tmp\pc6test2.qgz"`
I used 'wfs3' as endpoint:
 `Alias /wfs3 C:\OSGeo4W64/apps/qgis/bin/qgis_mapserv.fcgi.exe` 

Now:

/wfs3/collections/pc6.json shows the right (lat lon coordinates of the extent are the right ones for this city in NL)

![afbeelding](https://user-images.githubusercontent.com/731673/69806550-6fd99400-11e3-11ea-8aad-eb76e46c9c75.png)

But if I receive all tems, I see all the same coordinate (somewhere in France):

![afbeelding](https://user-images.githubusercontent.com/731673/69806742-e5456480-11e3-11ea-9090-4e070792744f.png)

/wfs3/collections/pc6/items.json

As json you will see all the same coordinates: `{"features":[{"bbox":[3.313777,47.97573,3.313777,47.97573],"geometry":{"coordinates":[[[[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],`

If I query one item all looks fine in the html version:

/wfs3/collections/pc6/items/21.html

![afbeelding](https://user-images.githubusercontent.com/731673/69807274-2ab66180-11e5-11ea-8ac9-0668cb00eedd.png)

als json looks good (as in the right coordinates):

http://geodev.nieuwegein.nl/wfs3/collections/pc6/items/21.json

But if I use the query interface:

http://geodev.nieuwegein.nl/wfs3/collections/pc6/items.json?POSTCODE=3431BG

I'm back in france again:

`{"features":[{"bbox":[3.313777,47.97573,3.313777,47.97573],"geometry":{"coordinates":[[[[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573],[3.313777,47.97573]]]],"type":"MultiPolygon"},"id":950,"properties":{"ADRESLOCAT":24,"ID":162599,"MULTIPARTS":1,"POSTCODE":"3431BG"},"type":"Feature"}],"links":`

/wfs3/collections/pc6/items.html?POSTCODE=3431BG

![afbeelding](https://user-images.githubusercontent.com/731673/69807448-9c8eab00-11e5-11ea-873f-3efdeb18eee0.png)

As said, this is QGIS 3.10, I will see if I can test master later tonight.

**Comment by tudorbarascu** [comment]
@rduivenvoorde There was a bug for this.. and it was fixed about 2 weeks ago (master at least).

**Comment by rduivenvoorde** [comment]
@tudorbarascu yes, Thanks. Working! Just compiled and tested Master. Will close this one.

One question: I run mapserver in /usr/lib/cgi-bin and put my data in  dir pc6 in that dir.
Then creating a fresh qgis project pointing to the shp in that dir, qgisserver failed. Looking into the log it showed: 
../src/core/qgsvectorlayer.cpp:1460 : (readXml) [7ms] Datasource in QgsVectorLayer::readXml: /pc6/pc6.shp
which is NOT ok, as it was a relative path...
After changing (in the project properties) to save the path as a absolute path, server was able to find my shp. Note that this is only if you put the shp in a separate dir. If you put the data (file) next to the project file it is ok. Does this ring a bell? Should I create an issue for it?

**Comment by tudorbarascu** [comment]
Great to hear it works! You can thank Alessandro for the fix.

Well.. it rings a bell.. but I think these issues were fixed long ago.

When you saved with relative path, it would be good to do check/post what's the line with ``datasource`` and ``name_of_file.shp`` in your ``qgs`` project.

**Comment by tudorbarascu** [comment]
@rduivenvoorde Maybe you should close this? :)

**Comment by rduivenvoorde** [comment]
Wanted to check the foo.shp in a foo dir (because I think that was the clue...) 
But closing this one
