### ISSUE TITLE
open attribute table in qgis 3.11 master is very slow,  QGIS-Codeversion c52a6e711a

### ISSUE THREAD

**Issue by gespiel** [qgis/QGIS#33133]
Shapefile, 70000 features, Open the attribute table in 3.4 or 3.10 needs 2-3 seconds.
Same shapefile needs near half an hour in QGIS-Codeversion c52a6e711a.

**Comment by gioman** [comment]
@gespiel can you attach the data?

**Comment by gespiel** [comment]
File is attached
[test.zip](https://github.com/qgis/QGIS/files/3903121/test.zip)
