### ISSUE TITLE
Processing dialog goes behind the main QGIS window

### ISSUE THREAD

**Issue by benjaminFaguer** [qgis/QGIS#33143]
Hi,
I just updated to QGIS 3.10 on OSX 10.14 and kept working on a project created under 3.8.

**Describe the bug and how to reproduce**

I have tried merging two raster layers (geotiff files with elevation data, as my area of interest is on the border of the two files). Here is what I did:
* Go to Raster > Miscellaneous > Merge
* Clicked on the button on the right of the field to select input layers
* When the `Multiple selection` window appears, I select my two files and click `OK`.
* The window closes, along with the `Merge` menu. No new layer is created and no error appears in the log panel.

I have tried selecting only one layer, two other layer or no layer at all; clicking the `OK` button on using my `Enter` key, the same behaviour each time.

The exact same thing happened when I tired to merge the two vector layers derived from these two geotiffs, when using the `Merge verctor layers` dialog box.
This also happens with a new user profile, a new project and the two geotiff files.

**QGIS and OS versions**

QGIS version | 3.10.0-A Coruña | QGIS code revision | 6c816b4204
-- | -- | -- | --
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.28.0 | Running against SQLite | 3.28.0
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS Mojave (10.14)
Active python plugins | QuickOSM; quick_map_services; nominatim; openlayers_plugin; processing; db_manager; MetaSearch

**Additional context**

Nothing to add.

**Comment by gioman** [comment]
>     * The window closes, along with the `Merge` menu. No new layer is created and no error appears in the log panel.

I think someone already reported something similar... are you sure that the dialog isn't just behind de QGIS main window?

**Comment by benjaminFaguer** [comment]
>are you sure that the dialog isn't just behind de QGIS main window

Well, thank you, that was it! The dialog disappeared and reappeared behind the main window and I had no idea that was a possibility.
Should I edit the title to say "New dialog to merge layers appears appears behind the main window"?

**Comment by alexbruy** [comment]
Duplicates #31577
