### ISSUE TITLE
Wizard fails to copy the grid transformation from file

### ISSUE THREAD

**Issue by vesnikos** [qgis/QGIS#33149]
- [x ] Test with a [clean new user profile] 

**Describe the bug**

WINDOWS 10, clean computer, part of Enterprise/Domain
 
QGis happily informed that could not transform from EPSG:4326->EPSG:27700 because of missing grid tranformation file. Furthermore informed me that I could download the zip containing that file and if wanted to install it. When pointed to correct file, the wizzard failed, as the destination folder wasn't existing. 

I assume i should make that folder manually?

**How to Reproduce**

![qgis_bug_copy_grid_file](https://user-images.githubusercontent.com/6684178/69868997-7c252600-12a3-11ea-817c-9d3789d111f0.PNG)

**QGIS and OS versions**

QGIS version
3.10.0-A Coruña
QGIS code revision
6ffa89eb3e
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.2
Running against GDAL/OGR
3.0.2
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.2.1
Running against PROJ
Rel. 6.2.1, November 1st, 2019
OS Version
Windows 10 (10.0)
Active python plugins
db_manager; 
MetaSearch; 
processing

**Additional context**

Installed qgis through osgeo4w, select ONLY QGIS package to install

**Comment by nyalldawson** [comment]
Fixed for 3.10.1
