### ISSUE TITLE
GDA2020 proj4: transform error

### ISSUE THREAD

**Issue by GGummow** [qgis/QGIS#33144]
I am currently running QGIS Ver 3.4.8-Madeira Code Revision 04ee8e0761 and GDA2020 seems to be "off the planet".

For GDA2020 (EPSG:7842):-
The identified projection Proj4 transform is: +proj=geocent +ellps=GRS80 +units=m +no_defs
I believe that is wrong and perhaps should be: +proj=longlat +ellps=GRS80 +units=m +no_defs

I have tested the recommended change with a custom CRS and it seems to be correct.

**Comment by nyalldawson** [comment]
You'll need 3.10.1 for proper GDA 2020 support - 3.4 doesn't have all the necessary pieces.

**Comment by GGummow** [comment]
Hi Nyall

Thanks for your prompt response and many thanks for the awesome work you guys do, I’m in awe and have huge gratitude.

You wrote:
You'll need 3.10.1 for proper GDA 2020 support - 3.4 doesn't have all the necessary pieces.

Same problem exist and same solution seems to apply ALSO for (latest stable) QGIS version: 3.10.0-A Coruña; QGIS code revision: 6ffa89eb3e<https://github.com/qgis/QGIS/commit/6ffa89eb3e>

My initial submission stated:
For GDA2020 (EPSG:7842):-
The identified projection Proj4 transform is: +proj=geocent +ellps=GRS80 +units=m +no_defs
I believe that is wrong and perhaps should be: +proj=longlat +ellps=GRS80 +units=m +no_defs

Also, as such if I’m correct then the fix should equally apply to LTR 3.4 as well as Stable 3.10.0

Acknowledgement: There does not appear to be a readily available build (as nominated in your response) for Windows Version 3.10.1


Cheers G²

**Comment by nyalldawson** [comment]
You're correct - 3.10.0 has a known issue which affects this, and 3.10.1 is due out in a week.

**Comment by nyalldawson** [comment]
Oh, and the required changes can't be backported to 3.4 -- they are just far too intrusive and risky. 3.4 will NEVER have proper gda2020 support.

**Comment by GGummow** [comment]
Thanks, I eventually worked out what I think you are saying: That the fix I proposed simply allows some kind of mimic of GDA94 or WGS84, but does not in fact provide real GDA2020 because the 3.4 engine does not have the working parts (I assume for plate drift).

Cheers, and once again, thanks for all the awesome work you guys do.

No reply required

**Comment by nyalldawson** [comment]
Correct - gda2020 is a tricky beast. If you're not careful, and the software doesn't have support for it, you'll likely get a so called "null transform" which can be up to 2m off the correct transform.
