### ISSUE TITLE
Points on a line segment are not excluded from the difference algorithm result

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#33155]
1. Let's take a line layer
1. Use the "extract vertices" algorithm to generate a point layer from it
1. Add some more points: some snapped to the line segment, others away from the line
1. Run the difference algorithm with point layer as input and line one as overlay
1. Points that I add away from the lines are reported (good!) as well as those that are placed on the segment (bug imho). It will exclude only the points that are at the vertices of the lines. 

It's not imho a matter of snapping because:
* i zoomed in to 10000:1 (in m) and the point and line features were still shown aligned
* If I add a new point and I edit the line to snap to it, that point is not reported anymore in the "difference" layer since it's now a vertex
* If I extend a line using the "trim/extend" tool, the point that was previously at the vertex I extend is now reported in the "difference" layer (considered as not on the line anymore).

So is a point considered as a line only if it's at the line vertex position?

master c52a6e711a on Win10

**Comment by lbartoletti** [comment]
@DelazJ Can you add some data and pictures please?

**Comment by nyalldawson** [comment]
It's very likely a precision issue. These algorithms are **exact**, and have absolutely no tolerance. So even a 0.0000000000000001 difference will prevent the match.

**Comment by DelazJ** [comment]
Then how do we explain 
> If I add a new point and I edit the line to snap to it, that point is not reported anymore in the "difference" layer since it's now a vertex
If I extend a line using the "trim/extend" tool, the point that was previously at the vertex I extend is now reported in the "difference" layer (considered as not on the line anymore).

**Comment by lbartoletti** [comment]
> Then how do we explain
> 
> > If I add a new point and I edit the line to snap to it, that point is not reported anymore in the "difference" layer since it's now a vertex
> > If I extend a line using the "trim/extend" tool, the point that was previously at the vertex I extend is now reported in the "difference" layer (considered as not on the line anymore).

Seems related to a difference between algorithm/library used.
For trim/extend, we use QGIS. For some other algorithms it's GEOS.
We found a similar problem with reshape tool.

**Comment by gioman** [comment]
@DelazJ what it the status of this report? Can we close?

**Comment by DelazJ** [comment]
@gioman I had a [pending question](https://github.com/qgis/QGIS/issues/33155#issuecomment-560034155). I'm not directly impacted, came across this while testing for docs. Give me a moment and I'll give it another shot and add a record as Loïc requested.
