### ISSUE TITLE
Incorrect short help for "Random points along line" algorithm

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#33160]
The "Random points along line" algorithm help panel states:
> This algorithm creates a new point layer, with points placed in the lines of another layer.
For each line in the input layer, a given number of points is added to the resulting layer. A minimum distance can be specified to avoid point being too close to each other.

I thereby understand that the input number is placed on **each** line but actually that number represents the total of points that would be generated in the output. ie, if you enter 5, you'll get 5 points in the output layer and not 5 points placed on each line.
Is it a bug or am I misunderstanding?

**Comment by alexbruy** [comment]
This is a bug in the documentation, seems it was written without testing and undertanding how algorithm works.

Algorithm generates requested number of points along input lines, but not for each line individually. It picks a random line segment and tries to add a point taking in account min distance, existing line vertices and already generated points.

Hope this helps.

**Comment by DelazJ** [comment]
> This is a bug in the documentation, seems it was written without testing and undertanding how algorithm works.

Hmmmm... Writers try to do their best, including the time-consuming features testing (and that includes processing hundreds of algs) otherwise there would not be more details in the docs than in the GUI. And there are things they don't know/understand and they ping devs; sometimes they get feedback, sometimes it's the "silence radio" So they try "something"...

But I think they have to trust developers description. And what I'm referring to in this case comes from the GUI (https://github.com/qgis/QGIS/blame/0219d0019ed3158ef662a7a322fdd3a073fdd541/python/plugins/processing/algs/help/qgis.yaml#L298), hence from the developer and not from an ignorant writer
![image](https://user-images.githubusercontent.com/7983394/71000479-b08a4600-20db-11ea-849a-7d7b60ccbb81.png)
> Hope this helps.

Yes it does: there's likely a bug in the alg or alg shortHelp, so this report is still worth it imho.

**Comment by alexbruy** [comment]
As I said, I don't know who wrote it. From git history I see that this file mostly edited by a non-developers.

Personally I contributed to docs a lot some time ago, but at some point gave up because couple of years ago getting PR merged became almost impossible.

**Comment by DelazJ** [comment]
> As I said, I don't know who wrote it. From git history I see that this file mostly edited by a non-developers.

I wouldn't have said that looking at the history but I was hoping that the git blame url would have avoided that statement. I failed obviously...
> Personally I contributed to docs a lot some time ago, but at some point gave up because couple of years ago getting PR merged became almost impossible.

_Personally_ I've been told that I was too demanding on writers and that it would scare off contributors but from what i can see in the repo history, you are a doc committer (so you could bypass reviewers though not always nice, I know) and you were already leaving when I began to contribute to the docs so obviously not my fault in this case. 😌 

And just to be clear, FWIW, I don't blame you (nor anybody else) to not write nor answer when you are questioned. It's your freedom despite it does not look nice for writers but it's not a big deal. I assume it's a matter of priorities and time. And OTOH there are some devs that help us somehow compensate.

Anyways, all these personal feelings are off-topic: what matters here is whether the algorithm is doing what the user is expected it to do. And if it doesn't, how could we fix it?
