### ISSUE TITLE
Wrong marker interval calculation in map units

### ISSUE THREAD

**Issue by Xeenych** [qgis/QGIS#33169]
I draw a line.
I add a markers to a line with interval of 60 map units.
I add a text do display $length of a line

Length of a line is 211, so I expect to have 3 intervals and 4 markers, but I get 4 intervals and 5 markers. See attached picture
![123](https://user-images.githubusercontent.com/11345848/69903412-f0e28800-13a9-11ea-9ff0-858cddbf25f7.jpg)

The line layer is in EPSG:4326.

If I save the layer to EPSG:3395 (metric) and then take length($geometry) then it displays 280 which is more adequate.

QGIS 3.4.13
QGIS 3.10.0

**Comment by gioman** [comment]
Can you please attach a sample project with sample data? thanks.

**Comment by Xeenych** [comment]
Here it is.
[temp.zip](https://github.com/qgis/QGIS/files/3907474/temp.zip)
There is a line, which $length is 368 meters.
Marker interval is set to 100 map units (meters).
But the line contains 5 markers instea of 4

**Comment by gioman** [comment]
> Here it is.
> [temp.zip](https://github.com/qgis/QGIS/files/3907474/temp.zip)
> There is a line, which $length is 368 meters.
> Marker interval is set to 100 map units (meters).
> But the line contains 5 markers instead of 4

your layer/project is a geographic CRS, if you make a copy of the layer to a projected CRS and use it for the project too you get 4 markers, and a distance between markers of exactly 100 map units (meters).

**Comment by Xeenych** [comment]
The layer "1" is in EPSG:3395 and this is a projected CRS. The project is also in 3395. Am, I wrong?

**Comment by gioman** [comment]
> and this is a projected CRS

@Xeenych you are right, sorry, but as a global CRS it probably suffers the same measurements problems as 3857 (you cannot use 3857 for reliable measurements).

**Comment by Xeenych** [comment]
In the attached example I have a topographic map as a raster layer in the project. It has a grid of 1000x1000 meters. Then I draw a line 1000 meters long and set marker interval to 100 meters. Then I expect to have 10-11 markers. This is expected behaviour. But I get 14-15 markers. This is unexpected and very strange.

**Comment by gioman** [comment]
> In the attached example I have a topographic map as a raster layer in the project. It has a grid of 1000x1000 meters. Then I draw a line 1000 meters long and set marker interval to 100 meters. Then I expect to have 10-11 markers. This is expected behaviour. But I get 14-15 markers. This is unexpected and very strange.

@Xeenych have you read my previous comment? The CRS you are using is not reliable for measurements. Try use the UTM for that area, and you'll see is ok.

**Comment by Xeenych** [comment]
The problem is not in reliable mweasurements but in the method used to calculate marker interval.

**Comment by i-s-o** [comment]
@Xeenych, another way of stating what @gioman said is that *CRS does matter*. This is true for many (maybe most or all?) of the UI graphical elements (e.g. try the new Grid Decoration feature: it is only useful to me if I zoom all the way in to a small area, in a correct local projection). To see this, as an alternative to what gioman is suggesting, you can use the `length` function instead of `$length` function:
![image](https://user-images.githubusercontent.com/1661549/69917708-ee7a3f80-1436-11ea-8346-f458d1bc35bd.png)

I think your expectation of
> ... I should get 10 markers on my map. No matter what CRS is.

can be better addressed as a feature request.

As for
> this should be obvious in user's interface.

From the Coordinate box in the status bar, hovering over the ends of the line:
X @ left ~ 8627695
X @ right ~ 8629045
=> 8629045 - 8627695 = 1350 (i.e. this is the distance in "Map Units")
Then, setting the marker distance to 100 of the same units, you get 13.5 markers.

**Comment by Xeenych** [comment]
I see and agree with you.
To write a feature request I have to understand one moment.
length($geometry) gives a rprojected length of 1.345 meters and 13.5 markers.
But if the layer is in geographic projection, length($geometry) gives length in arcdegrees or seconds regardless of project's CRS.

Looks like I may need something like projected_length($geometry) to give projected length in project's CRS.

**Comment by gioman** [comment]
>  To write a feature request I have to understand one moment.

please open a feature request when you feel ready.
