### ISSUE TITLE
Clipping Raster using a polygon

### ISSUE THREAD

**Issue by hammao** [qgis/QGIS#33179]
Clipping a raster using a polygon generate unusable data.

**Comment by gioman** [comment]
> Clipping a raster using a polygon generate unusable data.

@hammao 

very uncomplete report. You really must make a better effort: qgis version? platform? tool used? Add detailed steps to replicate and sample data and obtained results vs expected results.

**Comment by hammao** [comment]
Sorry about that ... i'm using QGIS version 3.8.1-Zanzibar... I downloaded GEBCO bathymetric dataset over the Arabian/Persian Gulf. I used a shape file for the water body to clip the raster. It generated values within this range -1.79769e+308 to  1.79769e+308. The initial values of my dataset were -1331.73 to 3567.45. 

I also have QGIS 2.8.9-Wien installed on my system and it worked fine... it clipped the data without issues. I'm using same settings. Let me know if you need more information.

**Comment by gioman** [comment]
> 3.8.1-Zanzibar

@hammao too old. Use the latest 3.4 (the LTR version) or the latest 3.10. Attach or link your data. also we have different tools that can do the operation you describe, you must tell use exactly what you are using.

**Comment by alexbruy** [comment]
Closing for the lack of feedback. Please reopen if necessary.
