### ISSUE TITLE
Crash every time I want to export Map in map layout

### ISSUE THREAD

**Issue by vmf3184** [qgis/QGIS#33184]
## User Feedback

Crash ID: 253881be096adbd9b68764249ad531d0fea539e8

Stack Trace

RtlFreeHeap :
HeapFree :
free :
DllUnregisterServer :
DllUnregisterServer :
CServerContextActivator::CreateInstance actvator.cxx:1000
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1917
CApartmentActivator::CreateInstance actvator.cxx:2251
CProcessActivator::CCICallback actvator.cxx:1716
CProcessActivator::AttemptActivation actvator.cxx:1630
CProcessActivator::ActivateByContext actvator.cxx:1488
CProcessActivator::CreateInstance actvator.cxx:1389
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1917
CClientContextActivator::CreateInstance actvator.cxx:685
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1917
ICoCreateInstanceEx objact.cxx:1334
CoCreateInstance actapi.cxx:108
_SHCoCreateInstance :
SHExtCoCreateInstance :
DCA_SHExtCoCreateInstance :
CFSIconOverlayManager::_s_LoadIconOverlayIdentifiers :
CFSIconOverlayManager::CreateInstance :
IconOverlayManagerInit :
GetIconOverlayManager :
FileIconInit :
SHGetImageList :
CBreadcrumbBar::InitBreadcrumbBar :
CAddressBand::_EnsureBreadcrumbBar :
CAddressBand::_CreateAddressBand :
CAddressBand::SetSite :
IUnknown_SetSite :
CBandSite::_AddBandByID :
CBandSite::AddBand :
CNavBar::_CreateBands :
CNavBar::_CreateBar :
CNavBar::ShowDW :
CFileOpenSave::_CreateNavigationBar :
CFileOpenSave::_InitOpenSaveDialog :
CFileOpenSave::s_OpenSaveDlgProc :
UserCallDlgProcCheckWow :
DefDlgProcWorker :
DefDlgProcW :
UserCallWinProcCheckWow :
InternalCreateDialog :
InternalDialogBox :
DialogBoxIndirectParamAorW :
DialogBoxIndirectParamW :
CFileOpenSave::Show :
QDialog::exec :
QFileDialog::getSaveFileUrl :
QFileDialog::getSaveFileName :
QgsLayoutDesignerDialog::saveAsTemplate qgslayoutdesignerdialog.cpp:1674
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:373
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:373
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1542
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.4.13-Madeira
QGIS code revision: 567300ccf1
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

## Report Details

*Crash ID*: 253881be096adbd9b68764249ad531d0fea539e8

*Stack Trace*
<pre>
RtlFreeHeap :
HeapFree :
free :
DllUnregisterServer :
DllUnregisterServer :
CServerContextActivator::CreateInstance actvator.cxx:1000
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1917
CApartmentActivator::CreateInstance actvator.cxx:2251
CProcessActivator::CCICallback actvator.cxx:1716
CProcessActivator::AttemptActivation actvator.cxx:1630
CProcessActivator::ActivateByContext actvator.cxx:1488
CProcessActivator::CreateInstance actvator.cxx:1389
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1917
CClientContextActivator::CreateInstance actvator.cxx:685
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1917
ICoCreateInstanceEx objact.cxx:1334
CoCreateInstance actapi.cxx:108
_SHCoCreateInstance :
SHExtCoCreateInstance :
DCA_SHExtCoCreateInstance :
CFSIconOverlayManager::_s_LoadIconOverlayIdentifiers :
CFSIconOverlayManager::CreateInstance :
IconOverlayManagerInit :
GetIconOverlayManager :
FileIconInit :
SHGetImageList :
CBreadcrumbBar::InitBreadcrumbBar :
CAddressBand::_EnsureBreadcrumbBar :
CAddressBand::_CreateAddressBand :
CAddressBand::SetSite :
IUnknown_SetSite :
CBandSite::_AddBandByID :
CBandSite::AddBand :
CNavBar::_CreateBands :
CNavBar::_CreateBar :
CNavBar::ShowDW :
CFileOpenSave::_CreateNavigationBar :
CFileOpenSave::_InitOpenSaveDialog :
CFileOpenSave::s_OpenSaveDlgProc :
UserCallDlgProcCheckWow :
DefDlgProcWorker :
DefDlgProcW :
UserCallWinProcCheckWow :
InternalCreateDialog :
InternalDialogBox :
DialogBoxIndirectParamAorW :
DialogBoxIndirectParamW :
CFileOpenSave::Show :
QDialog::exec :
QFileDialog::getSaveFileUrl :
QFileDialog::getSaveFileName :
QgsLayoutDesignerDialog::saveAsTemplate qgslayoutdesignerdialog.cpp:1674
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:373
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:373
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1542
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.4.13-Madeira
QGIS code revision: 567300ccf1
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by gioman** [comment]
@vmf3184 does it makes any difference if you try using a new QGIS profile (do not install any 3rd party plugins)?

**Comment by vmf3184** [comment]
Hi,

Let me try and get back to you.

Regards,

V

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by vmf3184** [comment]
Hi, I just tried the same 3rd party plugin on a different computer, this time a laptop. And it works fine. I think it is a problem of the computer. Should I remove the ticket?

Thanks,

V


________________________________
