### ISSUE TITLE
I want to copy an attribute of selected feature to .csv file using Python in QGIS

### ISSUE THREAD

**Issue by EsmH** [qgis/QGIS#33188]
I am going to save one attribute of the selected feature from QGIS to a .CSV file using this code :

```
# Append a list with the values of your field
values_field = []
for feature in layer.getFeatures():
    values_field.append(feature['gml_id']) # gml_id is the name of my field

# Open your csv file 
with open('C:/Users/v.bre/Desktop/export_csv/test.csv', 'w') as file:
    # Write in your file
    for feature in values_field:
        file.write(feature)
        file.write('\n') # line break 

# Close your csv file
file.close()
```
------------------------

but I'm getting this error: 

![Feature_Get](https://user-images.githubusercontent.com/32569479/69961724-c0ffc580-150c-11ea-9954-49c268eeb21f.PNG)

**Comment by roya0045** [comment]
Not a bug, just bad code.

I would redirect you to stack exchange or the user mailing list.
