### ISSUE TITLE
3D uses band 1 even when another band is selected

### ISSUE THREAD

**Issue by andrewcooke** [qgis/QGIS#33180]
**How to Reproduce**

1. Grab http://acooke.org/route.tiff which is an image with 4 bands - R, G, B and elevation.
2. Add the image as a layer and display RGB.  Should look like Santiago, Chile, with a red line overplotted.
3. Add the image again, as a second layer (with a new name), and display the 4th band from the file as grayscale.  Compare the two layers - the grayscale shows elevation.
4. Open the 3D window and set elevation from the second layer added to qgis.  Elevation will be set from the first band (R) in the image rather than the 4th band (elevation).

**QGIS and OS versions**

QGIS version | 3.10.0-A Coruña | QGIS code branch | Release QGIS code branch.3
-- | -- | -- | --
Compiled against Qt | 5.9.7 | Running against Qt | 5.9.7
Compiled against GDAL/OGR | 2.4.2 | Running against GDAL/OGR | 2.4.3
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.28.0 | Running against SQLite | 3.28.0
PostgreSQL Client Version | 10.10 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.10.4
Compiled against PROJ | 6.2.1 | Running against PROJ | Rel. 6.2.1, November 1st, 2019
OS Version | openSUSE Leap 15.1 | This copy of QGIS writes debugging output.
Active python plugins | MetaSearch; processing; db_manager

**Additional context**

It's possible this is me not understanding something, or generating the file in correctly (sorry).  If I come to understand more I will delete this issue.

**Comment by gioman** [comment]
> It's possible this is me not understanding something, or generating the file in correctly (sorry). If I come to understand more I will delete this issue.

@andrewcooke 
I'm not sure if I understand the steps to replicate (when you say "layer" you mean "band"?), but if I so then I can't replicate. A screencast would help.

**Comment by andrewcooke** [comment]
i edited the description above.  i was using 'layer' in two different ways; i have changed one to 'band'.

if this is still not clear, or it works for you, i can try making a video.

**Comment by gioman** [comment]
@andrewcooke still true on latest releases?
