### ISSUE TITLE
QGIS crashes when rotating a feature

### ISSUE THREAD

**Issue by reginaldc** [qgis/QGIS#33186]
**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

Hi,

I am using qgis 3.10 on windows 7 (installation osgeo4w64).
I am using a clean profile.
Every time I try to rotate a feature (be it a point, line or polygon) qgis freezes and crashes.
I remember in previous versions I was able to rotate polygons. It looks like a regression.
I am using the advanced digitalizing toolbar for rotating the feature.

Regards,

**Comment by gioman** [comment]
Already reported and already fixed.
