### ISSUE TITLE
Some functions lost

### ISSUE THREAD

**Issue by housepig83** [qgis/QGIS#33181]
Hi, 

I am using QGIS3.6 on my Mac IOS. The software was freeze while I was converting raster to polygon. When I reopened the software, many of the functions gone, such as raster to pixel points, clip raster etc. I tried uninstall and reinstall (both 3.6 and 3.10 version ) again but still can't find these functions. My tool search window also can't be open anymore... How can I fix this? thanks

**Comment by gioman** [comment]
@housepig83 what happens if you try a new QGIS profile?

**Comment by housepig83** [comment]
Hi thanks for your reply. I have just sort it out . Turns out I just need to reinstall the Processing toolbox plugin again . No idea why it was removed.
