### ISSUE TITLE
QGIS plugin import DBSCAN RecursionError issue: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by Ariel505** [qgis/QGIS#33191]
I am developing a QGIS plugin that use DBSCAN method in sklearn.
In my Linux QGIS test environment, the import failed. QGIS plugin can not be opened.
However I test the plugin in windows 7 but it works.

Python version: 3.6.8 (default, Oct  7 2019, 12:59:55) [GCC 8.3.0] 
QGIS version: 3.6.1-Noosa Noosa, 93e761d 

Could not load plugin 'aChor' due to an error when calling its classFactory() method.
RecursionError: maximum recursion depth exceeded 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/hcuadmin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/aChor/__init__.py", line 35, in classFactory
    from .aChor import aChor
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/hcuadmin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/aChor/aChor.py", line 53, in 
    from sklearn.cluster import DBSCAN
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/hcuadmin/.local/lib/python3.6/site-packages/sklearn/cluster/__init__.py", line 6, in 
    from .spectral import spectral_clustering, SpectralClustering
...

Please refer to the attached text document for complete error report.

Any suggestion would be appreciated, thanks.
[bug.txt](https://github.com/qgis/QGIS/files/3912140/bug.txt)

**Comment by gioman** [comment]
@Ariel505 is this a question or a bug report?

**Comment by Ariel505** [comment]
Hello gioman,
I believe this is a bug report for QGIS desktop. 
For the windows QGIS do not have this import DBSCAN issue.
Cheers,
Ariel

**Comment by gioman** [comment]
Maybe that python library is not correctly installed in your linux machine?

**Comment by Ariel505** [comment]
Hi thanks for the comment. I suppose the same in the beginning.
However when I use the python console to import the sklearn there's no error appears.
I can use the library correctly.
Cheers,
Ariel

**Comment by roya0045** [comment]
It might be dangerous but I recall that you can increase the recursion limit, you could increase it be a few just to see if that solves it.

**Comment by Ariel505** [comment]
Thanks. I tried the solution from this post but it didn't work.
https://stackoverflow.com/questions/33757661/how-could-you-increase-the-maximum-recursion-depth-in-python
May I know how to increase? Is this in the QGIS advanced setting?

**Comment by Ariel505** [comment]
Upgrade to QGIS 3.10 Coruña didn't solve the issue.

**Comment by roya0045** [comment]
I think max recursion depth is a system setting only. If changing this variable did not solve your issue I'm not sure what else will. I might be a local issue or a bad build somehow.

**Comment by Ariel505** [comment]
Hi,
So this issue was solved by removing all pytest and py associated folders under /usr/lib/python3.6/dist-packages/
So I think this can be closed.
Thanks for your help.
