### ISSUE TITLE
Rotate feature hangs QGIS 3.10.0

### ISSUE THREAD

**Issue by Jean-Roc** [qgis/QGIS#33199]
Using the rotate feature tool causes the application to hang with QGIS 3.10.0, the UI becomes unresponsive and nothing is displayed in the logs.

I have tested against QGIS 3.4.13 and 3.8.3 and was not able to reproduce this behaviour.

**How to Reproduce**

1. Start a new project
2. Create a memory layer (any type/srid)
3. Create a new feature
4. Use the rotate tool on an object
5. End the rotation -> QGIS hangs

**QGIS and OS versions**

Version de QGIS 3.10.0-A Coruña
Révision du code 6ffa89eb3e
Compilé avec Qt 5.11.2
Utilisant Qt  5.11.2
Compilé avec GDAL/OGR 3.0.2
Utilisé avec GDAL/OGR 3.0.2
Compilé avec GEOS 3.8.0-CAPI-1.13.1
Utilisé avec GEOS 3.8.0-CAPI-1.13.1 
Compiled against SQLite 3.29.0
Running against SQLite  3.29.0
Version du client PostgreSQL  11.5
Version de SpatiaLite 4.3.0
Version de QWT  6.1.3
Version de QScintilla2  2.10.8
Compilé avec PROJ 6.2.1
Fonctionne avec PROJ  Rel. 6.2.1, November 1st, 2019
OS Version  Windows 10 (10.0)
Extensions Python actives quick_map_services; db_manager; processing

**Additional context**

Happens whatever the geometry type or source.

**Comment by gioman** [comment]
Already fixed.
