### ISSUE TITLE
Error while adding WMS layer: raster layer Provider is not valid

### ISSUE THREAD

**Issue by arbakker** [qgis/QGIS#33190]
**Describe the bug**
Error occurs while trying to add a specific WMS layer `gmw` (title: *BRO Grondwater Monitoringput*) from service `https://geodata.nationaalgeoregister.nl/brogmw/wms?`. Error message:

```
Invalid Layer: Raster layer Provider is not valid (provider: wms, URI: crs=EPSG:4326&dpiMode=7&format=image/png&layers=gmw&styles&url=https://geodata.nationaalgeoregister.nl/brogmw/wms?
```
![Screenshot from 2019-12-02 16-40-54](https://user-images.githubusercontent.com/3216462/69972776-89037d00-1522-11ea-8bfa-fbaa4f512467.png)

In the log panel I only see the following:

```
2019-12-02T16:40:53     CRITICAL    Invalid Layer : Raster layer Provider is not valid (provider: wms, URI: crs=EPSG:4326&dpiMode=7&format=image/png&layers=gmw&styles&url=https://geodata.nationaalgeoregister.nl/brogmw/wms?
```

Above tested with running QGIS in a new profile.

**How to Reproduce**

Follow steps below to reproduce the error:

- Add WMS connection through the browser panel, set name to *bro-gmw* and url to `https://geodata.nationaalgeoregister.nl/brogmw/wms?`, leave other options as is. 
- Restart QGIS (important since state in QGIS project seem to affect outcome)
- Create new project
- Add  layer `gmw` (title: *BRO Grondwater Monitoringput*) from the newly created connection *bro-gmw* (this should cause the error to occur)

Strange thing is that the WMS layer does work when I have a WMTS background loaded prior to adding the `gmw` layer. Follow steps below to reproduce the working WMS layer:

- Install the PDOK services [plugin](https://plugins.qgis.org/plugins/pdokservicesplugin/)
- Restart QGIS
- Create new project 
- Add the "brtachtergrondkaart" WMTS layer (through the PDOK services plugin)
- Add  layer `gmw` (title: *BRO Grondwater Monitoringput*) from the newly created connection *bro-gmw* 

Note that this WMS service has MaxScaleDenominator set on the layers, maybe this has something to do with the error message?

**QGIS and OS versions**

QGIS version | 3.10.0-A Coruña | QGIS code revision | 6c816b4204
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.4.2 | Running against GDAL/OGR | 2.4.0
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.0-CAPI-1.11.0 673b9939
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 10.10 (Ubuntu 10.10-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Ubuntu 18.04.3 LTS
Active python plugins | pdokservicesplugin; qgisnetworklogger; db_manager; MetaSearch; processing

**Comment by gioman** [comment]
> Note that this WMS service has MaxScaleDenominator set on the layers, maybe this has something to do with the error message?

I cannot replicate on QGIS LTR on Ubuntu 18.04. The layer loads with no error and is visible in from scale  ~20000. Anyway I can't say I haven't seen that error before. Try cleaning your QGIS (network) cache, in the past this error was triggered by QGIS caching of requests,

**Comment by arbakker** [comment]
Thanks for the quick response! I tried enabling and disabling the network cache and that did the trick. I previously did not attempt to clean the network cache because I had set the size of the cache to 0. I assumed that cleaning the network cache would not do anything...
