### ISSUE TITLE
 when using  QGIS in chinese it can't connect to *.mdb files

### ISSUE THREAD

**Issue by bouyeijiang** [qgis/QGIS#33194]
when i change chinese encoding and than it can't connect *.mdb file

**Comment by gioman** [comment]
@bouyeijiang this report is largely incomplete. QGIS version? Platform? Detailed steps to replicate? sample data?

**Comment by bouyeijiang** [comment]
QGIS newest version,windows 10 workstation,user interface transactoin select chinese.
when i select user interface transaction is American english item is ok

**Comment by Pedro-Murteira** [comment]
@bouyeijiang I can't seem to reproduce this issue, can you still replicate this in the current version?
