### ISSUE TITLE
Buttons shows up as â€¦

### ISSUE THREAD

**Issue by isamsonWL** [qgis/QGIS#33209]
I installed QGIS 3.10, and have noticed that in many processing window interfaces that … shows up as â€¦

For example, grass tool r.watershed, I see â€¦ instead of … on all the select file buttons.

Install was done both using OSGeo4W Network Installer, and also QGIS standalone, issue happens in both.

This has happened on 3 different machines, one of which was brand new and had nothing besides windows 10 Pro on it. The only other software installed was visual studio code, notepad++, lenovo vantage and drivers, openvpn, timecard software, git, and 7zip.

I have set up the following environmental variables so things actually work:
GISBASE = 'C:\OSGeo4W64\apps\grass\grass78'
PYTHONPATH = 'path to company codebase that has currently been emptied'
![QGIS_Issue_ellipse_display](https://user-images.githubusercontent.com/58479297/70067469-8e58da00-15ab-11ea-9af1-0711438e5363.PNG)

**Comment by i-s-o** [comment]
I noticed this in both 3.10 and 3.11, but not in 3.4. In case this helps: it appears to be affecting only some of the button (maybe an encoding issue in the source code?). This is from the nightly master in Windows 10:
![image](https://user-images.githubusercontent.com/1661549/70087709-cd565200-15e2-11ea-8cf4-0f53a6bc29a2.png)

**Comment by gioman** [comment]
Confirmed on clean Win7 3.10.1 installation.

**Comment by i-s-o** [comment]
FYI: this is also an issue in the Select Transformation dialog where an m-dash (—, U+2014) shows up as â€”:
![image](https://user-images.githubusercontent.com/1661549/70398270-8bb11700-19e7-11ea-9006-c5daa4cd3f9b.png)

On a separate note: I think an n-dash (–, U+2013) for this specific situation is a more appropriate typographic symbol and it would look better.

**Comment by i-s-o** [comment]
I took a quick look at the affected forms: this seems to happen when QStringLiteral() used in setText() methods of those buttons. If I change them from `setText(QStringLiteral('…'))` to `setText('…')` the correct character shows on the buttons. This could be due to a setting in VS2015, as this problem doesn't show up in QGIS 3.4.

**Comment by i-s-o** [comment]
This was introduced by #9339 and then by #31124 to fix the problem with ellipsis.

re: `QStringLiteral()`, the following talks about the limitations of it (I am not a programmer so I'm not sure whether it is relevant here):
https://www.mail-archive.com/development@qt-project.org/msg35932.html

There is also this [discussion](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/1142) about requiring BOM for UTF-8 source code in MSVS2015: haven't tested whether it makes a difference.
