### ISSUE TITLE
QGISserver wfs3 dead link in breadcrumbs path

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS#33203]
Setting up a small QGISserver demo here:

http://qgis.zuidt.nl/cgi-bin/qgis_mapserv.fcgi/wfs3/

If I 'browse' to 'cbsgemeenten2018 items as HTML' (dutch municipalities 2018 stats):

http://qgis.zuidt.nl/cgi-bin/qgis_mapserv.fcgi/wfs3/collections/cbsgemeenten2018/items.html?

And then click on the 'cbsgemeenten2018' link in the breadcrumbs in the top of that page, I end up here:

http://qgis.zuidt.nl/cgi-bin/qgis_mapserv.fcgi/wfs3/collections/cbsgemeenten2018/

telling me: 

`[{"code":"API not found error","description":"Collection was not found"}]`

I think it should go to 

http://qgis.zuidt.nl/cgi-bin/qgis_mapserv.fcgi/wfs3/collections/cbsgemeenten2018.html?

as I'm browsing html?

**Comment by elpaso** [comment]
No, `.html` is optional and content negotiation will define the content-type if it's not explicitly set. What's wrong here is the extra `/`, if you remove it it will all work correctly, but it's definitely a but (probably in the template helper function that builds the breadcrumbs), I'll have a look.
