### ISSUE TITLE
QGIS freeze after rotating feature numerical

### ISSUE THREAD

**Issue by oskarlin** [qgis/QGIS#33208]
**Describe the bug**
When rotating a feature using the rotate tool in Advanced Digitizing Toolbar freehand rotating or  typing in an angle QGIS freezes. This never happened in version 3.8.

**How to Reproduce**

1. Select a feature
2. Click on rotate tool
3. Rotate a feature
4. Freeeeeze

**QGIS and OS versions**
QGIS 3.10 
MacOS 10.14.6

**Additional context**

**Comment by roya0045** [comment]
Should be fixed in the next release.

**Comment by gioman** [comment]
it is already fixed.
