### ISSUE TITLE
Digitizing: LineStringZ does not inherit Z-coordinates from points if line starts by snapping to a point with no Z coordinate

### ISSUE THREAD

**Issue by CarstenRC** [qgis/QGIS#33201]
**Describe the bug**

When digitizing 3D linestrings (LineStringZ) using snap functions the linestring does not inherit __any__ Z-coordinates from points if the first vertex of the linestring snaps to a 2D point even though subsequent vertices snap to 3D points that do have a Z-coordinate.

**How to Reproduce**
1. Edit a linestring layer with LineStringZ geometry.
2. Click to add a line feature.
3. Start adding the line feature by snapping to a point feature that has no Z-coordinate, i.e. Point or MultiPoint geometry.
4. Continue to create the next vertex by snapping to a point feature that has a Z-coordinate, i.e. PointZ or MultiPointZ geometry.
5. Finish the line feature.
6. Activate the vertex tool and right-click on the line feature.
7. The Z-coordinate is 'nan' on all vertices.

QGIS version
3.10.0-A Coruña
QGIS code revision
6ffa89eb3e
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.2
Running against GDAL/OGR
3.0.2
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.2.1
Running against PROJ
Rel. 6.2.1, November 1st, 2019
OS Version
Windows 10 (10.0)
Active python plugins
changeDataSource; 
featureattachments; 
geosearch_dk; 
Kortforsyningen; 
latlontools; 
mask; 
pointsamplingtool; 
profiletool; 
Qgis2threejs; 
scriptrunner3; 
db_manager; 
MetaSearch; 
processing

**Additional context**
Features are based on data from a PostgreSQL/PostGIS database and data from a shape file (PointZ)

**Comment by lbartoletti** [comment]
Can you try with the nightly version?

**Comment by CarstenRC** [comment]
I just tried with the latest build and the problem remains. Here's the version info:


QGIS version
3.11.0-Master
QGIS code revision
af1c087919
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.0dev
Running against GDAL/OGR
3.1.0dev
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
7.0.0
Running against PROJ
Rel. 7.0.0, March 1st, 2020
OS Version
Windows 10 (10.0)
This copy of QGIS writes debugging output.
Active python plugins
changeDataSource; 
featureattachments; 
geosearch_dk; 
Kortforsyningen; 
latlontools; 
mask; 
pointsamplingtool; 
profiletool; 
Qgis2threejs; 
scriptrunner3; 
db_manager; 
MetaSearch; 
processing

**Comment by lbartoletti** [comment]
@CarstenRC Thanks. I'll take a look.

**Comment by lbartoletti** [comment]
@CarstenRC Fixed in https://github.com/qgis/QGIS/pull/33642
Let me know
