### ISSUE TITLE
Crash when closing application

### ISSUE THREAD

**Issue by AlwynB** [qgis/QGIS#33207]
## User Feedback

Crash occurs when closing QGIS desktop application

## Report Details

**Crash ID**: [533376728e5523b2835d2f7e33464e1f304dd042]('https://github.com/qgis/QGIS/search?q=533376728e5523b2835d2f7e33464e1f304dd042&type=Issues')

**Stack Trace**
<pre>
QDockWidget::toggleViewAction :
QgisApp::removeDockWidget qgisapp.cpp:3957
meth_QgisInterface_removeDockWidget sip_guipart3.cpp:243774
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyEval_EvalCodeEx :
PyEval_EvalCode :
PyArena_Free :
PyRun_StringFlags :
QgsPythonUtilsImpl::evalString qgspythonutilsimpl.cpp:529
QgsPythonUtilsImpl::unloadPlugin qgspythonutilsimpl.cpp:648
QgsPluginRegistry::unloadAll qgspluginregistry.cpp:191
QgisApp::saveWindowState qgisapp.cpp:4650
QMetaObject::activate :
QCoreApplicationPrivate::execCleanup :
QCoreApplication::exec :
main main.cpp:1598
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.0-A Coru�a
QGIS code revision: 6ffa89eb3e
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment]
> Crash occurs when closing QGIS desktop application

try with a new QGIS profile (no 3rd party plugins installed).

> My first report, pls let me know if I am missing anything that could help you out

use a meaningful subject :)

**Comment by AlwynB** [comment]
Hi @gioman , I deleted the SCP plugin and QGIS 3.10 seems to close without error again. :)

Thx for you help before!

**Comment by banananana-ananaa** [comment]
is it possible to use the SCP plugin and not have the application crash?
