### ISSUE TITLE
Lots of CRS missing from nigthlies with ubuntugis-unstable

### ISSUE THREAD

**Issue by Bernd-Vogelgesang** [qgis/QGIS#33211]
Updated QGIS nigthly with ubuntugis-unstable dependencies today. Now lots of CRS are missing, as it seems e.g. all WGS 84 / UTM zone xy z
Furthermore at start-up, the "default" CRS 4326 is not set (missing from the list as well), but in the project properties, there is the checkbox checked with "No projection".
In the terminal, this error shows up:

> ERROR 4: Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.

QGIS-Version | 3.11.0-Master | QGIS-Codeversion | fe9dcf1f33
-- | -- | -- | --
Kompiliert gegen Qt | 5.9.5 | Laufendes Qt | 5.9.5
Kompiliert mit GDAL/OGR | 2.4.2 | Läuft mit GDAL/OGR | 2.4.2
Kompiliert mit GEOS | 3.7.1-CAPI-1.11.1 | Läuft mit GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL-Client-Version | 10.10 (Ubuntu 10.10-0ubuntu0.18.04.1) | SpatiaLite-Version | 4.3.0a
QWT-Version | 6.1.3 | QScintilla2-Version | 2.10.2
Kompiliert mit PROJ | 5.2.0 | Läuft mit PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Linux Mint 19.2 | Diese QGIS-Kopie schreibt Debugausgaben.
Active python plugins | MetaSearch; db_manager; processing

**Comment by gioman** [comment]
@Bernd-Vogelgesang and if you don't use ubuntugis?

**Comment by Bernd-Vogelgesang** [comment]
> @Bernd-Vogelgesang and if you don't use ubuntugis?

Well, I did ... and the situation got even worse, cause QGIS refused to install at all (https://qgis.org/ubuntu). Seems I now have the choice between no QGIS or no CRS.
```
Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 qgis : Hängt ab von: gdal-abi-2-2-3
        Hängt ab von: libqgis-analysis3.10.0 soll aber nicht installiert werden
        Hängt ab von: libqgis-app3.10.0 soll aber nicht installiert werden
        Hängt ab von: libqgis-core3.10.0 soll aber nicht installiert werden
        Hängt ab von: libqgis-gui3.10.0 soll aber nicht installiert werden
        Hängt ab von: python3-qgis (= 1:3.10.0+28bionic) soll aber nicht installiert werden
        Hängt ab von: qgis-providers (= 1:3.10.0+28bionic) soll aber nicht installiert werden
E: Probleme können nicht korrigiert werden, Sie haben zurückgehaltene defekte Pakete.
```
next try will be nightlies without ubuntugis

**Comment by gioman** [comment]
I'm on yours same system and version and I don't have such issues. Maybe is a local issue one?

**Comment by Bernd-Vogelgesang** [comment]
Presumably gdal hickups. Throwing it away and try to install new without ubuntugis. Actually I did nothing special but switch to nightlies some weeks ago and updated yesterday.

**Comment by Bernd-Vogelgesang** [comment]
@gioman Not possible to revert to 3.10 ubuntugis. GRASS 780 is expected, but 781 is there. Darn!
Why does it always have to be hard wired to point release numbers ? Anyway, original problem somehow solved itself, now facing other problems.
