### ISSUE TITLE
Confusing use of "container" and "categories" in drag and drop form design

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#33221]
When configuring a drag and drop form, you get fields with either "categories" or "containers" and it's hard to document since nothing obvious helps to identify the difference (if any)
Here I assume the category "MyGroup" is part of a container which is "first tab"
![image](https://user-images.githubusercontent.com/7983394/70117224-2cf54180-1665-11ea-90f9-874b44a69bca.png)
But here "MyGroup" is identified as a container (double-click on the group - also applies to tabs)
![image](https://user-images.githubusercontent.com/7983394/70117288-5dd57680-1665-11ea-89e6-51bc767df507.png)

Suggestion: move everything to container, ie in the first image above:
- "Add tab or group for ..." --> "Add Container for ..."
- "Create category ... as" --> "Create Container ... as"

@m-kuhn @signedav ?

**Comment by DelazJ** [comment]
Btw, "number of columns" vs "column count" ?

**Comment by signedav** [comment]
First I completely agree that it's a bad naming.

As far I understand it (without going deep into code) "Category" is another word for "Container"

A top level container is a tab and all lower level containers are groups.

I summarize (mainly for myself :-)):

Tabs are these:
![image](https://user-images.githubusercontent.com/28384354/70120186-2ddda180-166c-11ea-9785-cfadc9fbafaf.png)

Groups are these:
![image](https://user-images.githubusercontent.com/28384354/70120265-65e4e480-166c-11ea-9f26-1a2b5a796b5d.png)
![image](https://user-images.githubusercontent.com/28384354/70120529-1a7f0600-166d-11ea-9617-b5d2f95ddd26.png)

Configurated like this:
![image](https://user-images.githubusercontent.com/28384354/70120319-96c51980-166c-11ea-8b9b-2c02663939fc.png)

Containers can be nested. In groups and subgroups:

**Comment by signedav** [comment]
And I prefer to use only "number of columns". "column count" is IMO not really correct.

**Comment by DelazJ** [comment]
Thanks @signedav PR done
