### ISSUE TITLE
defective presentation from *.xml files

### ISSUE THREAD

**Issue by MalteEBA** [qgis/QGIS#33222]
**Describe the bug**
If I load xml files out of this zip file (see below) in QGIS, the buildings aren't displayed correct. There are a lot of buldings missing or corrupt.
I know, that this file contains all informations, cause with other programms I can extract them.

**How to Reproduce**
https://fbinter.stadt-berlin.de/fb/berlin/service_intern.jsp?id=a_lod1@senstadt&type=FEED
http://fbarc.stadt-berlin.de/FIS_Broker_Atom/lod1/LoD1.zip

**QGIS and OS versions**
3.10 and
3.4.5-Madeira

I am not the only one, who has problems with xml files.

**Comment by gioman** [comment]
@MalteEBA that zip contains a lot of xml files, which one we should test? and can you add an image that shows expected vs obtained?

**Comment by MalteEBA** [comment]
Wow, that was a fast answer!! Thanks alot!

Exemplary I toke 391_5820 and 5821 + 390_5820 and 5821 -this are displayed in red. In turquoise u can the the informations, which should be displayed.

![2019-12-04 10_18_01-_Unbenanntes Projekt - QGIS](https://user-images.githubusercontent.com/58505266/70129658-7783b780-167f-11ea-844d-157535d041d7.png)

**Comment by gioman** [comment]
@MalteEBA converting to GPKG (or another format) using ogr2ogr and you'll get the same result you see in QGIS, so if there is an issue this is likely to be in a upstream library.

`ogr2ogr -f "GPKG" LoD1_391_5821.gpkg LoD1_391_5821.xml`

[LoD1_391_5821.gpkg.zip](https://github.com/qgis/QGIS/files/3921141/LoD1_391_5821.gpkg.zip)

**Comment by MalteEBA** [comment]
(my english isnt the best)
So if I get u right, u see the problem not in QGIS but in the file itself.

The turquoise building u can see in the screenshot are created out of the xml files by using FME. So, there is the correct information in the file.

Or did I get u wrong?

**Comment by andreasneumann** [comment]
@MalteEBA - QGIS is using external libraries for reading the XML file. In this case, OGR. @gioman is saying that the issue might be in the OGR library and not in QGIS. You can find more info about OGR at https://gdal.org/

Note that GDAL is the raster library and OGR the vector library.

You can raise your issue in the gdal/ogr project at https://github.com/OSGeo/GDAL or discuss it in the gdal-dev mailing list: see https://gdal.org/community.html

**Comment by MalteEBA** [comment]
Ah, got it -thank you!
Okay, then I need to put the issue there. Or is it possible to relocated it from here?

**Comment by andreasneumann** [comment]
No, we can't move this issue to GDAL from here. But you can copy/paste stuff of course.

And then you can either close this ticket here or cross-reference the GDAL issue and close both tickets together once it is fixed in GDAL/OGR.

Note that some OGR devs are also QGIS devs, so there is some overlap ;-)

**Comment by MalteEBA** [comment]
Okay, I opend a new ticket in the gdal/ogr project at https://github.com/OSGeo/GDAL.
I'll close the issue in this forum.
