### ISSUE TITLE
XYZTiles (mbtiles) exports in TMS Scheme not XYZ Scheme

### ISSUE THREAD

**Issue by CaptainInler** [qgis/QGIS#33228]
**Describe the bug**
When exporting tiles from a Map there are two processing-tools to do so:
- Generate XYZ tiles (Directory)
- Generate XYZ tiles (MBTiles)

Assuming of the names of this tools, they would export Tiles according to the XYZ-Scheme (Slippy map tilenames) used by osm, google, bing, ...
But this is only true for "Generate XYZ tiles (Directory)". While this Tool uses by default the XYZ-Scheme it also provides an Option to choose between the XYZ and TMS-Scheme, "Generate XYZ tiles (MBTiles)" does only allow to export tiles in the TMS-Scheme..

So I guess "Generate XYZ tiles (MBTiles)" has to be renamed to "Generate **TMS** tiles (MBTiles)"

**How to Reproduce**
For this test I used the tool provided by #32499 

***Generate XYZ tiles (Directory)***
Generate an Export with this options:
![grafik](https://user-images.githubusercontent.com/16583617/70149904-533cd080-16a9-11ea-8c0d-89db6a1cdb6a.png)

Result: this file will be generated: "C:\test\6\33\22.png"
where 22 is the row used by XYZ-scheme for the given coordinate

***Generate XYZ tiles (MBTiles)***
Generate an Export with this options:
![grafik](https://user-images.githubusercontent.com/16583617/70149781-1bce2400-16a9-11ea-9f45-9113fb336714.png)

edit this mbtiles with a Database-utility an execute this query `select * from tiles`

zoom_level | tile_column | tile_row | tile_data
-- | -- | -- | --
6 | 33 | 41 | 137,80,78,71,13,...

41 is the row used by TMS-scheme for the given coordinate

see also here: [https://www.maptiler.com/google-maps-coordinates-tile-bounds-projection/](https://www.maptiler.com/google-maps-coordinates-tile-bounds-projection/)

**QGIS and OS versions**

QGIS version | 3.10.0-A CoruÃ±a | QGIS code revision | 6c816b4204
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Windows 10 (10.0)
Active python plugins | db_manager; MetaSearch; processing

**Comment by wonder-sk** [comment]
I would say that it is just a technical detail of the MBTiles format that it uses TMS convention. I would rather keep it as it is. Or maybe rename the algorithms to "Generate Raster Tiles" to make it independent from the actual tiling scheme.

**Comment by madhums** [comment]
So then how can I convert this mbtiles which is in TMS format to XYZ? 

I am having the same issue here ([post on gist.stackexchange](https://gis.stackexchange.com/questions/348254/qgis-mbtiles-vs-xyz-tiles-export-inconsistency))

**Comment by madhums** [comment]
Ok so I followed this [gist](https://gist.github.com/tmcw/4954720) and simply converted the y value to `pow(2, z) - y - 1` and it seems to convert properly! 

I think xyz is a very standard approach, so I guess QGIS should export it in xyz scheme by default instead of tms. OR an option must be provided for the user to choose which scheme they prefer.

**Comment by wonder-sk** [comment]
> I think xyz is a very standard approach, so I guess QGIS should export it in xyz scheme by default instead of tms. OR an option must be provided for the user to choose which scheme they prefer.

MBTiles requires the TMS convention. So if we exported MBTiles file using XYZ convention, all client software supporting MBTiles would display the tiles incorrectly. I am not sure if that would be really helpful...?

**Comment by madhums** [comment]
Ah ok makes sense. May be we can provide a note in the UI to the user that the tiles exported won't be in xyz and that they would have to make the conversion if intended to be used in xyz scheme. 

For GIS people this might be a no-brainer but might help beginners / web developers.

**Comment by Pedro-Murteira** [comment]
@CaptainInler Hello, is this issue still valid on recent versions?
