### ISSUE TITLE
Drag and Drop form designer does not respect hidden widget type

### ISSUE THREAD

**Issue by tastrax** [qgis/QGIS#33238]
**Describe the bug**
Drag and drop designer appears not to respect hidden widget. Field values are not displayed but labels are.

**How to Reproduce**

in this example the first field 'fid' is hidden

- In autogenerate form designer make a field hidden, apply, OK and then check an object to ensure field is actually hidden 

![Autogenerate](https://user-images.githubusercontent.com/8775395/70196511-0581a000-175d-11ea-86ce-e1bc0c9d76b2.JPG)

- Return to form designer and switch to 'drag and drop designer', apply, OK then check an object. Field with hidden widget will continue to **show label** but no field value

![DragDrop](https://user-images.githubusercontent.com/8775395/70196515-087c9080-175d-11ea-894c-303b68d6c3e8.JPG)

**QGIS and OS versions**

3.10.0, Windows 10(10.0)

**Comment by DelazJ** [comment]
And what happens if in the Form attributes --> drag and drop designer settings frame, you double-click the fid entry and uncheck "show label"?

**Comment by tastrax** [comment]
I then get a blank space

![blankspace](https://user-images.githubusercontent.com/8775395/70208886-d2ea9e00-1782-11ea-9a9a-bc047b65ad58.JPG)

**Comment by andreasneumann** [comment]
Then I would suggest you simply don't add the field, if you don't need it. The "hidden" widget is mainly for the purpose of the autogenerated list.

It also has no influence on the attribute table, as this has separate mechanisms to show/hide columns, independent of the form mode.

**Comment by saberraz** [comment]
Here is the original ticket: https://github.com/lutraconsulting/input/issues/549

**Comment by tastrax** [comment]
Alas, I do need them in the form (for things like last updated date and time when the form is used in mobile application Input/Mergin)

**Comment by tastrax** [comment]
Ok, so my understanding now is that calculated fields (ie last updated, create date and time, virtual fields etc) do not need to be in the form to still operate correctly?

**Comment by andreasneumann** [comment]
I would assume that as well.

**Comment by tastrax** [comment]
Many thanks - will close the issue

**Comment by janbur** [comment]
@tastrax and @andreasneumann - can you confirm that calculated fields (i.e. fields that use expressions for default values) do not need to be in the form (drag and drop designer) to still operate correctly?
Oddly, in my case this is true only for some simple expressions (e.g. calculating uuid(), geometry $x etc) but not for complex expressions (e.g. using `if` or `case` statements) that depend on other fields.
I want to hide some fields frm the form (eventually used in QField) but still calculate their values when other field is modified. When they are added to the form - all works well. When I hide them (change widget type to Hidden) they are still visible in the form. But when I remove them from the form, the don't get calculated anymore.
I'm testing directly in QGIS (3.14), on Win10. Same behavior is in QField (10 Nov 2020 version).

**Comment by janbur** [comment]
After some tests I can confirm that calculated fields that use expressions referencing other fields will not work when creating a new feature if they are not added to the form (drag & drop designer). However, they will get updated once the feature is modified.
Tested on QGIS (3.14) Win10 using shapefiles.

**Comment by gioman** [comment]
> 3.14

@janbur please test on 3.16 as 3.14 is outdated, if the problem persist please file a new ticket.
