### ISSUE TITLE
Crash on clik in "Enable Snapping on Intersection" from Snapping  Toolbar

### ISSUE THREAD

**Issue by andhersonpeter** [qgis/QGIS#33234]
Crash ID: ff48eba451388ba43cf68cb2852b6171adc14573

Stack Trace

_geometrySegmentsInRect qgspointlocator.cpp:355
QgsPointLocator_VisitorEdgesInRect::visitData qgspointlocator.cpp:403
Index::~Index :
Index::~Index :
QgsPointLocator::edgesInRect qgspointlocator.cpp:918
QgsPointLocator::edgesInRect qgspointlocator.cpp:927
QgsSnappingUtils::snapToMap qgssnappingutils.cpp:263
QgsMapMouseEvent::snapPoint qgsmapmouseevent.cpp:52
QgsMapToolAdvancedDigitizing::canvasMoveEvent qgsmaptooladvanceddigitizing.cpp:110
QgsMapCanvas::mouseMoveEvent qgsmapcanvas.cpp:1726
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1598
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.10.0-A Coru�a
QGIS code revision: 6ffa89eb3e
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.14393

**Comment by lbartoletti** [comment]
Please, can you add detail and some data?

**Comment by gioman** [comment]
@andhersonpeter also try with a new QGIS profile.

**Comment by PeterZamudio** [comment]
The same thing is happening with me. If I click on the intersection icon of the snapping tool qgis blocks up and then crashes.

## User Feedback

on the snapping tool, the line intersection causes a crash.

## Report Details

**Crash ID**: [ff48eba451388ba43cf68cb2852b6171adc14573]('https://github.com/qgis/QGIS/search?q=ff48eba451388ba43cf68cb2852b6171adc14573&type=Issues')


**Stack Trace**
<pre>
_geometrySegmentsInRect qgspointlocator.cpp:355
QgsPointLocator_VisitorEdgesInRect::visitData qgspointlocator.cpp:403
Index::~Index :
Index::~Index :
QgsPointLocator::edgesInRect qgspointlocator.cpp:918
QgsPointLocator::edgesInRect qgspointlocator.cpp:927
QgsSnappingUtils::snapToMap qgssnappingutils.cpp:328
QgsMapMouseEvent::snapPoint qgsmapmouseevent.cpp:52
QgsMapToolAdvancedDigitizing::canvasMoveEvent qgsmaptooladvanceddigitizing.cpp:110
QgsMapCanvas::mouseMoveEvent qgsmapcanvas.cpp:1727
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1598
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>


**QGIS Info**
QGIS Version: 3.10.2-A Coru�a
QGIS code revision: d4cd3cfe5a
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.3
Running against GDAL: 3.0.3



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
> The same thing is happening with me. If I click on the intersection icon of the snapping tool qgis blocks up and then crashes.

@andhersonpeter 
please try with a new QGIS profile, no 3rd party plugins installed.

If the problem persist please attach a sample project+data and detailed steps that lead to the crash.

**Comment by PeterZamudio** [comment]
Hello again

Thank you for the answer.

I did as you said, new profile with no plugins other than those that come with the installation.
Sadly still with a crash.

I work with a cloud based postgresql db that works fine with all other projects including qgep.
sadly nearly all fail on the intersection snap and then crash.

I know with simple geopackage-layers and all the plugins I have installed that the intersection snap works OK. Maybe I just have to much data for the indexing.

It is a bit difficult to send you data as it's in a password protected DB.
So I will keep trying to narrow it down at the moment and find out when the crash starts.

I will report back what I find or come back for help.

thank you again

**Comment by PeterZamudio** [comment]
Hi again

I may have solved it. I reduced the number of layers for the intersection down to Properties(Liegenschften), hlinien and support-lines. and it worked as it should. :-)
See the picture.
![Projekteinrasteinstellungen](https://user-images.githubusercontent.com/32352291/74165049-d720b500-4c24-11ea-856d-35ae087908a2.jpg)

I think the problem must be to many layers or to much data, not certain which it is.
In the test I had 2 cloud Postgres layers and 1 Geodatabase(Hilflinien).

I hope this helps to make it better and it will work better soon.

Best regards and thank you for a great program.
Peter Zamudio
Swizerland

**Comment by gioman** [comment]
> I hope this helps to make it better and it will work better soon.

@andhersonpeter can you provide a sample project+data that shows the problem?

**Comment by m-kuhn** [comment]
Seems to be related to curved layers

**Comment by m-kuhn** [comment]
More precisely, if a geometry is of a type that supports curves but does not contain curves.

**Comment by imkeines** [comment]
QGIS 3.28.3 on Windows 10
Each time I try to split on intersection it crashes, which makes this function unusable. This is the error message:
Python Stack Trace
Windows fatal exception: access violation

Current thread 0x00002438 (most recent call first):



Stack Trace


QgsGeos::linePointDifference :
QgsGeos::splitGeometry :
QgsGeometry::splitGeometry :
QgsGeometry::splitGeometry :
QgsVectorLayerEditUtils::splitFeatures :
QgsVectorLayer::splitFeatures :
QgsMapToolSplitFeatures::cadCanvasReleaseEvent :
QgsMapToolAdvancedDigitizing::canvasReleaseEvent :
QgsMapCanvas::mouseReleaseEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.28.3-Firenze
QGIS code revision: c12bcb2f76c
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.2
Running against GDAL: 3.6.2



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045
