### ISSUE TITLE
Bug in Vertex Edit

### ISSUE THREAD

**Issue by andhersonpeter** [qgis/QGIS#33231]
Crash ID: ff48eba451388ba43cf68cb2852b6171adc14573

Stack Trace

_geometrySegmentsInRect qgspointlocator.cpp:355
QgsPointLocator_VisitorEdgesInRect::visitData qgspointlocator.cpp:403
Index::~Index :
Index::~Index :
QgsPointLocator::edgesInRect qgspointlocator.cpp:918
QgsPointLocator::edgesInRect qgspointlocator.cpp:927
QgsSnappingUtils::snapToMap qgssnappingutils.cpp:263
QgsMapMouseEvent::snapPoint qgsmapmouseevent.cpp:52
QgsMapToolAdvancedDigitizing::canvasMoveEvent qgsmaptooladvanceddigitizing.cpp:110
QgsMapCanvas::mouseMoveEvent qgsmapcanvas.cpp:1726
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1598
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.10.0-A Coru�a
QGIS code revision: 6ffa89eb3e
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.14393

**Comment by gioman** [comment]
@andhersonpeter please add detailed steps about how replicate the issue. Also please check if you can confirm the problem using a new QGIS profile (no 3rd party plugins installed).

**Comment by lbartoletti** [comment]
And, please, try with the nightly version. I think that this bug is maybe already resolved.

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
