### ISSUE TITLE
'project home' not showing up in browser directly

### ISSUE THREAD

**Issue by MartinMap** [qgis/QGIS#33230]
After creating/saving a new project somewhere in a folder, the 'project home' in browser-panel should pop up, but it don't. Just after restarting the project (close and open), the 'project home' is displayed.

To reproduce:
1. Open QGIS
2. Save a empty Project (Save as / Save)
3. Look at the browser (no 'project home')
4. close the project
5. restart the project
6. look at the browser ('project home' is there!)

QGIS Version:

> 
> QGIS version | 3.10.0-A Coruña | QGIS code revision | 6c816b4204
> -- | -- | -- | --
> Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
> Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
> Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.6.2-CAPI-1.10.2 4d2925d6
> Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
> PostgreSQL Client Version | 10.10 (Ubuntu 10.10-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
> QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
> PROJ.4 Version | 493
> OS Version | Linux Mint 19.2
> Active python plugins | nominatim; quick_map_services; FreehandRasterGeoreferencer; searchlayers; SaxonyCadastralParcels; ArcheoCAD; QuickOSM; db_manager; MetaSearch; processing

**Comment by pigreco** [comment]
I confirm, also happens in 3.10.1

win 10 OSGeo4W
