### ISSUE TITLE
Server is unable to maintain the header compression context for the connection

### ISSUE THREAD

**Issue by NizhiSaeba** [qgis/QGIS#33255]
I have a couple of years working something with a plugin (yes, i know you are not responsible for plugins, but please read) called go2streetview. Always was working well. but after upgrade to 3.10 don't worked again, i tried to go back to versions 3.8 and 3.4 and works fine, exactly the same plugin (8.1)

I know that plugins are responsible by his autors, but i'm sure this is not an issue with the plugin, because it works fine since version 3.0 till 3.8. exactly the same plugin.

This plugin uses a webkit browser i guess from qtweb or something, a friend told me that maybe something in the last build has been different.

The error is that, this plugin tried to connect to googleapis.com server, which uses HTTP/2 protocol, and seems that it uses some kind of compression standard not so very standard. it seems like google is changing his stuff to use brotli instead of gzip. 

When i look at the debug window for web connection i can see this error:

(Failed to load resource: Server is unable to maintain the header compression context for the connection)

![imagen](https://user-images.githubusercontent.com/6070970/70287366-434deb00-1794-11ea-9401-882b8802d2e9.png)

So, my report is to ask you how webkit of the webclient bundled with qgis was built. it supports brotli? or only gzip? or can you tell me if something changed in the build enviroment? because it seems like an issue with the webkit qt client support of compression standards, and not an issue with the plugin. But this issue affects this specific plugin.

**Comment by jef-n** [comment]
See also #32507

**Comment by gioman** [comment]
> I have a couple of years working something with a plugin (yes, i know you are not responsible for plugins, but please read) called go2streetview

please add your notes here #32507
