### ISSUE TITLE
Data-defined buttons have raised styling when symbol properties opened from the point displacement renderer settings

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#33258]
When opening symbols properties dialog or the rendering settings dialog from the symbology --> point displacement option, the data-defined widgets in most of the dialogs show an ugly background
![image](https://user-images.githubusercontent.com/7983394/70300164-154dc280-17f7-11ea-91aa-29045fd13951.png)
If I open the same dialog from eg, the single symbol or style manager, I don't have them.
![image](https://user-images.githubusercontent.com/7983394/70300347-8f7e4700-17f7-11ea-8734-7136dab5c801.png)

**Comment by nyalldawson** [comment]
Fixed in master
