### ISSUE TITLE
Clicking expression button in symbology tab crashes qgis

### ISSUE THREAD

**Issue by andrewharvey** [qgis/QGIS#33256]
> Bug fixing and feature development is a community responsibility, and not the responsibility of the QGIS project alone.
> If this bug report or feature request is high-priority for you, we suggest engaging a QGIS developer or support organisation and financially sponsoring a fix

Absolutely, I have no expectations that someone will give up their free time to fix my issue.

- [x] Search through existing issue reports and gis.stackexchange.com to check whether the issue already exists
- [ ] Test with a [clean new user profile](https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html?highlight=profile#working-with-user-profiles).
- [x] Create a light and self-contained sample dataset and project file which demonstrates the issue

**Describe the bug**
QGIS crash

**How to Reproduce**

1. Open the attached shp file in QGIS.
[VNP14IMGTDL_NRT_Australia_and_New_Zealand_7d.zip](https://github.com/qgis/QGIS/files/3930449/VNP14IMGTDL_NRT_Australia_and_New_Zealand_7d.zip)
2. Right click layer > Properties > Control Feature Symbology tab > Graduated > expression button right of Value.
3. QGIS crashes with:

```
> qgis
proj_create_from_database: crs not found
proj_create_from_database: crs not found
Warning: Logged warning: Duplicate provider otb registered
Fatal: Assertion [endStyled < Length()] failed at ../src/Document.cpp 2053

QGIS died on signal -1[New LWP 163326]
[New LWP 163327]
[New LWP 163332]
[New LWP 163333]
[New LWP 163336]
[New LWP 163370]
[New LWP 163371]
[New LWP 163375]
[New LWP 163376]
[New LWP 163377]
[New LWP 163378]
[New LWP 163379]
[New LWP 163380]
[New LWP 163381]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007ff3b28068ee in __GI___waitpid (pid=163391, stat_loc=stat_loc@entry=0x7ffff55d978c, options=options@entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
30	../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.
[Current thread is 1 (Thread 0x7ff3aaf69e80 (LWP 163323))]
#0  0x00007ff3b28068ee in __GI___waitpid (pid=163391, stat_loc=stat_loc@entry=0x7ffff55d978c, options=options@entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
        resultvar = 18446744073709551104
        sc_cancel_oldtype = 0
#1  0x0000562f353da540 in qgisCrash(int) (signal=signal@entry=-1) at ../../src/app/main.cpp:349
        status = 32755
        pidstr = "--pid=163323\000\177\000\000\240\233]\365\377\177\000\000\005\b\000\000\000\000\000"
        gdbpid = <optimized out>
        exename = "/usr/bin/qgis.bin", '\000' <repeats 15 times>, "\005\000\000\000\000\000\000\000\b\000\000\000\000\000\000\000\360\231]\365\377\177\000\000!\374ϲ\363\177\000\000\004\000\000\000\000\000\000\000\000V\302\"\342\035:\017\b\000\000\000\000\000\000\000\221\000\000\000\000\000\000\000\220\000\000\000\000\000\000\000\240\031\367>/V\000\000@\214\217\262\363\177\000\000\220\032\367>/V\000\000\000\000\000\000\000\000\000\000\002R|\262\363\177\000\000\a\000\000\000\000\000\000\000\360\000\000\000\000\000\000\000\345\000\000\000\000\000\000\000\360\000\000\000\000\000\000\000\260\031\367>/V\000\000\200\000\000\000\000\000\000\000?\000\000\000\000\000\000\000\240"...
        len = <optimized out>
#2  0x0000562f353da71a in myMessageOutput(QtMsgType, char const*) (type=<optimized out>, msg=0x562f3ef719c8 "Assertion [endStyled < Length()] failed at ../src/Document.cpp 2053\n") at ../../src/app/main.cpp:436
#3  0x00007ff3b2cec45c in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007ff3b2cec5e9 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007ff3b2cbca44 in QMessageLogger::fatal(char const*, ...) const () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007ff3bbb2f0ce in QMessageLogContext::QMessageLogContext(char const*, int, char const*, char const*) () at /usr/lib/libqscintilla2_qt5.so.13
#7  0x00007ff3bbc11f5f in Document::SetStyles(int, char const*) () at /usr/lib/libqscintilla2_qt5.so.13
#8  0x00007ff39430ede1 in Scintilla::LexAccessor::Flush() () at /usr/lib/libqscintilla2_qt5.so.15
#9  0x00007ff39430ef32 in Scintilla::LexAccessor::ColourTo(unsigned long, int) () at /usr/lib/libqscintilla2_qt5.so.15
#10 0x00007ff39438e884 in  () at /usr/lib/libqscintilla2_qt5.so.15
#11 0x00007ff3943e7662 in Scintilla::LexerModule::Lex(unsigned long, long, int, Scintilla::WordList**, Scintilla::Accessor&) const () at /usr/lib/libqscintilla2_qt5.so.15
#12 0x00007ff3bbbf7a5d in LexerSimple::Lex(unsigned int, int, int, IDocument*) () at /usr/lib/libqscintilla2_qt5.so.13
#13 0x00007ff3bbc0b15f in LexInterface::Colourise(int, int) () at /usr/lib/libqscintilla2_qt5.so.13
[Inferior 1 (process 163323) detached]
gdb returned 0
fish: “qgis” terminated by signal SIGABRT (Abort)
```

**QGIS and OS versions**
```
> qgis --version
QGIS 3.10.0-A Coruña 'A Coruña' (6c816b4204)
```

QGIS version | 3.10.0-A Coruña | QGIS code revision | 6c816b4204
-- | -- | -- | --
Compiled against Qt | 5.12.5 | Running against Qt | 5.12.5
Compiled against GDAL/OGR | 2.4.2 | Running against GDAL/OGR | 2.4.3
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.30.1 | Running against SQLite | 3.30.1
PostgreSQL Client Version | 12.0 (Debian 12.0-1+b1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.10.4
Compiled against PROJ | 6.2.0 | Running against PROJ | Rel. 6.2.1, November 1st, 2019
OS Version | Debian GNU/Linux bullseye/sid
Active python plugins | nominatim_locator_filter; chinesepostman; otb; db_manager; processing

**Comment by nyalldawson** [comment]
I can't reproduce this -- what platform is it?

**Comment by andrewharvey** [comment]
That's strang. Debian using the packages from https://qgis.org/debian.

**Comment by andrewharvey** [comment]
So further testing, it doesn't matter what source data I use, as same issue with a scratch layer.

**Comment by gioman** [comment]
> So further testing, it doesn't matter what source data I use, as same issue with a scratch layer.

@andrewharvey please try with a new QGIS profile, no 3rd party plugins installed.

**Comment by andrewharvey** [comment]
The qgis.org/debian repos were just updated with 3.10.1 :smile:, and now it works :tada:.

**Comment by andrewharvey** [comment]
I suspect this issue was related to Qt somehow possibly a missmatch of library versions between the qgis.org/debian repo and debian's own repo.
