### ISSUE TITLE
Unexpectedly Ended error

### ISSUE THREAD

**Issue by Keith842803** [qgis/QGIS#33264]
## Report Details

*Crash ID*: 62f1fcd2045780cb9f127836e6b579b8665f3e63

*Stack Trace*
<pre>
proj_lpz_dist :
proj_lpz_dist :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::QgsCoordinateTransform :
QHashData::free_helper :
QgsCoordinateTransform::addToCache :
QgsCoordinateTransform::invalidateCache :
QgsApplication::exitQgis :
QgisApp::~QgisApp :
CPLStringList::operator[] :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.8.3-Zanzibar
QGIS code revision: 685d8b15d2
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.3.9600

**Describe the bug**
Running on Windows 8.1 on Dell desktop computer. 
QGIS ver 3.8.3
Unexpectedly ended crash on shutdown and sometimes during running. Not predictable. 
3.10 is worse as it can give same crash as soon as OS map is loaded. Reverted back to a clean install of 3.8.3 still crashes. 
No other programs on my computer have this problem. Checks run on computer systems show no system errors.

**How to Reproduce**
Not predictable

**QGIS and OS versions**

QGIS version
3.8.3-Zanzibar
QGIS code revision
685d8b15d2
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
2.4.1
Running against GDAL/OGR
2.4.1
Compiled against GEOS
3.7.2-CAPI-1.11.0
Running against GEOS
3.7.2-CAPI-1.11.0 b55d2125
PostgreSQL Client Version
10.8
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
5.2.0
Running against PROJ
Rel. 5.2.0, September 15th, 2018
OS Version
Windows 8.1 (6.3)

**Additional context**
Earlier versions have run ok

**Comment by jef-n** [comment]
3.8.3 is EOL.

**Comment by Keith842803** [comment]
Unfortunately I do not know what EOL means. If it is something to do with it not been the current version I stated that I have had the same problem with 3.10 If not could someone advise me of the meaning.

**Comment by haubourg** [comment]
EOL means End of Life

We provide support for the release and LTR version

**Comment by jef-n** [comment]
More over duplicate of #33177
