### ISSUE TITLE
QGis 3.10 crash (freeze) while rotating an item

### ISSUE THREAD

**Issue by Cantalou15** [qgis/QGIS#33260]
**Describe the bug**
QGis 3.10 crash (freeze) while rotating an item with the standard tool.

**How to Reproduce**

In "Edit" mode:

Select the "rotate" tool.
Click one item (shape) of the layer
Move the mouse to rotate to the proper angle
Click to validate ... QGIS freeze...

**QGIS and OS versions**

Bug with 3.10 but not with 3.8

**Additional context**
Windows 7 and 10 64 bits
![Rotate item bug](https://user-images.githubusercontent.com/12166686/70312802-a0898100-1814-11ea-9215-5c62ae638820.png)

**Comment by lbartoletti** [comment]
Hello,

It's already fixed in the nightly version.
