### ISSUE TITLE
Symbol masking for labels seems quite broken

### ISSUE THREAD

**Issue by nyalldawson** [qgis/QGIS#33277]
Possibly I'm totally misusing this feature, but I can't get it to actually DO anything!

The settings are lost just by closing dialogs, and regardless of which combination of checkboxes I tick there's no visible impact on the map...

![Peek 2019-12-07 19-59](https://user-images.githubusercontent.com/1829991/70372547-22200280-192c-11ea-8f25-c3bc3e5bb46a.gif)

**Comment by tomass** [comment]
My observation on latest master is that masking only works when layer style dialogue is **docked**.
If styling is done in normal/undocked layer properties dialogue, settings have no impact upon pressing „Apply“ and settings are lost after layer property dialogue is closed (regardless if _Cancel_ or _OK_ was pressed).

**Comment by smnorris** [comment]
Can confirm - applying the masked symbol layers check box in the docked layer styling dialogue makes the mask actually happen. This was driving me nuts.
