### ISSUE TITLE
ModuleNotFoundError: No module named 'shapely.vectorized._vectorized'

### ISSUE THREAD

**Issue by matheusfillipe** [qgis/QGIS#33275]
I am trying to use trimesh https://github.com/mikedh/trimesh. Seems like this module has problems. Not sure what it is. It worked just fine on the linux version but is not working on windows:

`
from shapely import vectorized
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\shapely\vectorized\__init__.py", line 3, in <module>
    from ._vectorized import (contains, touches)
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
`

I tested on qgis 3.6 and 3.10.

**Comment by gioman** [comment]
@matheusfillipe is that a QGIS plugin? if not how this is a QGIS issue?

**Comment by matheusfillipe** [comment]
Doing that from the Qgis shell or either from a plugin leads to that error. (Windows only).

For my plugin a temporary fix i found is unzipping the windows shapelly wheel build and using it locally.

**Comment by gioman** [comment]
> Doing that from the Qgis shell or either from a plugin leads to that error. (Windows only).

seems it is likely an issue with the installation of that library on Win rather than a QGIS bug.

**Comment by matheusfillipe** [comment]
Doesn't Qgis use its own python environment? I didn't even and don't have that library installed on my system. It comes with Qgis.

**Comment by matheusfillipe** [comment]
What I mean is that maybe Qgis should use a more recent version of that library or is building it wrongly, but I have no idea.

**Comment by gioman** [comment]
@matheusfillipe is the library shapely?

**Comment by matheusfillipe** [comment]
Yes shapely.

**Comment by gioman** [comment]
> Yes shapely.

@matheusfillipe but your link does not point to shapely but rather to a "trimesh" one, that I don't think is part of the ones that are shipped with QGIS on Windows.

**Comment by matheusfillipe** [comment]
Ignore that link.... It is a library I am using inside my plugin that has shapely as a requirement that i just expected to work with the qgis shapely. Just run "from shapely import vectorized" on qgis on Windows. That is the bug. If Qgis had shapely properly that should work?

**Comment by roya0045** [comment]
@matheusfillipe did you execute the code within qgis or in a python interpreter elsewhere ?

I might be possible that it is a PATH issue if its the latter.

**Comment by matheusfillipe** [comment]
> @matheusfillipe did you execute the code within qgis or in a python interpreter elsewhere ?
> 
> I might be possible that it is a PATH issue if its the latter.
Fresh install of Qgis 3.10 on a fresh windows VM Install without python on the OS.

**Comment by roya0045** [comment]
That's not quite what I wanted to know, if you open qgis and in the python console within qgis import shapely, it should be fine.

I am assuming that you are testing python from outside of QGIS and your environment variables are not properly set up.

**Comment by matheusfillipe** [comment]
@roya0045 I ran that on the Qgis Shell.

**Comment by matheusfillipe** [comment]
just import shapely works fine. Most shapely functions work fine too. But "from shapely import vectorized" causes that error. All tested from Qgis python Shell. Someone really tested this on Windows and works? I would like to know since it is for a plugin.

**Comment by roya0045** [comment]
By looking at https://pypi.org/project/Shapely/ it seems that vectorized might be an extra library/module. 

Otherwise importing specifically does not work either on the old 3.4.0, so this is not a regression.

**Comment by matheusfillipe** [comment]
@roya0045  So why it works on linux? Does qgis uses the OS python on ubuntu, this was never clear to me? 
Any chance this extra would ever be added? I am having a hard time trying to do 3D  mesh stuff inside Qgis.

**Comment by gioman** [comment]
> Does qgis uses the OS python on ubuntu? this was never clear to me...

@matheusfillipe yes

**Comment by gioman** [comment]
>  "from shapely import vectorized"

@matheusfillipe 
just tested: with the osgeo4w installer manually install "python3-shapely" and the above import will work.

**Comment by roya0045** [comment]
> > "from shapely import vectorized"
> 
> @matheusfillipe
> just tested: with the osgeo4w installer manually install "python3-shapely" and the above import will work.

This means that the plugin will not work out of the box for standalone install. I think the best otpion would be to have a try except to check if vectorized is available else use the normal library.

**Comment by matheusfillipe** [comment]
@roya0045 
Yes thanks! I am doing a try to import shapely.vectorized and if it fails i use my own shapely module inside the plugin folder.

**Comment by jef-n** [comment]
Fixed in OSGeo4W
