### ISSUE TITLE
No support for MrSid on linux

### ISSUE THREAD

**Issue by stopyaks** [qgis/QGIS#33273]
In windows, upon install you can elect to agree to the terms for MrSid support. There's no support for MrSid at all in the linux version?

**Comment by jef-n** [comment]
Please direct questions to the [user mailing list](https://qgis.org/en/site/forusers/support.html#mailing-lists).     MrSID support is provided by GDAL.  You need to have a GDAL build that supports [MrSID](https://trac.osgeo.org/gdal/wiki/MrSID).  If your GDAL supports MrSID you'll also be able to use it in QGIS.
