### ISSUE TITLE
QGIS crash windows 10

### ISSUE THREAD

**Issue by dzimmerle** [qgis/QGIS#33272]
Seems to happen when closing, or after Windows has been suspended .

Crash ID: f4475de87e6a815390b3363a83d3fb7ae10fc9c9

Stack Trace

proj_lpz_dist :
proj_lpz_dist :
proj_lpz_dist :
proj_lpz_dist :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::QgsCoordinateTransform :
QHashData::free_helper :
QgsCoordinateTransform::addToCache :
QgsCoordinateTransform::invalidateCache :
QgsApplication::exitQgis :
QgisApp::~QgisApp :
CPLStringList::operator[] :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.8.3-Zanzibar
QGIS code revision: 685d8b15d2
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by roya0045** [comment]
Please update this has been fixed.
