### ISSUE TITLE
 ImportError: No module named site

### ISSUE THREAD

**Issue by yportier** [qgis/QGIS#33281]
`GDAL Raster Calculator Processing Algorithm` complains about a module named `site` that couldn't be loaded.

QGIS version: 3.10.1-A Coruña
QGIS code revision: ef24c526da
Qt version: 5.11.2
GDAL version: 3.0.2
GEOS version: 3.8.0-CAPI-1.13.1
PROJ version: Rel. 6.2.1, November 1st, 2019

running on

Win 7 Enterprise (64bits), Service Pack 1
16GB RAM / Intel Core i5-4300U @ 1.90GHz

**Comment by gioman** [comment]
@yportier just tested on a clean QGIS 3.10.1 on Win 7 and cannot confirm.

**Comment by gioman** [comment]
@yportier sorry ignore my previous comment, it overlooked you were speaking about the GDAL one.

In my case the error is:

"gdal_calc is not a recognized command..."

**Comment by gioman** [comment]
I had to install the gdal-python package on osgeo4w, then the command works but it throws another error, which is still different from yours.

"none type" object has no attribute "data type"

**Comment by roya0045** [comment]
The error of the OP seems like a bad installation as import site is a basic python thing.

**Comment by gioman** [comment]
> seems like a bad installation

I tested on an immaculate system, if a bad installation is then is a osgeo4w problem.

**Comment by roya0045** [comment]
@gioman I was referring to the error reported by @yportier .

**Comment by gioman** [comment]
> I was referring to the error reported by

@roya0045 ah ok, sorry

**Comment by yportier** [comment]
> @gioman I was referring to the error reported by @yportier .

Indeed it does, but I've installed with osgeo4w so basic python things should be working properly I assume

**Comment by yportier** [comment]
Just to add a few details:  
The `algorithm` itself gives the following error:  

> The following layers were not correctly generated. C:/Users/yportier/AppData/Local/Temp/processing_42669ca868e84145bcf5e0be76f26092/57e61466304a4301ad1b29d49309033a/OUTPUT.tif You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.

The `Processing` Tab in the `Log messages` window gives the following:  

> 2019-12-10T12:04:38     INFO    GDAL execution console output
>              ImportError: No module named site

**Comment by gioman** [comment]
Sorry for having hijacked this ticket. In my case it works as expected. The error I was seeing was because of the optional input layers being filled automatically, and they cause some trouble in GDAL raster calc even if they are not used in the formula. This has been addressed by a PR by @alexbruy

**Comment by alexbruy** [comment]
Looks like there are some issues with your OSGeo4W installation. Try to remove it completele and reinstall.

**Comment by yportier** [comment]
> Looks like there are some issues with your OSGeo4W installation. Try to remove it completele and reinstall.

I just did, now it's not complaining about `site` anymore but fails with this message:

> 'gdal_calc' is not recognized as an internal or external command, operable program or batch file.

**Comment by jef-n** [comment]
> > 'gdal_calc' is not recognized as an internal or external command, operable program or batch file.

Should be already fixed in OSGeo4W - the standalone will be update on the next point release.
