### ISSUE TITLE
Snapping and Vertex tool not working with memory layers without any fields, if snapping was enabled during layer creation and entering the edit mode

### ISSUE THREAD

**Issue by borysiasty** [qgis/QGIS#33285]
In Master (3.11), if I try to edit a memory layer with no attributes, the node tool is dead - it can't highlight any feature. As soon as I add any field the issue is fixed. Note it's enough to add and remove the field immediately, so the problem is not in missing fields - rather in the missing step of field creation.

It's clearly 3.11 regression, as there is no such problem with the freshly compiled 3.10 branch.

See also #33449.

**How to Reproduce**

0. Ensure snapping is enabled during steps 1 and 2.
1. Create a new memory layer of any geometry type
2. Add a feature
3. Try to use the vertex tool -> doesn't work
4. Add any field (it's enough to add it and remove immediately)
5. Try to use the vertex tool -> it works!

**Comment by haubourg** [comment]
Hi, how do you expect editing to work without any PK field?

**Comment by haubourg** [comment]
Is there a FID displayed in 3.10?

**Comment by roya0045** [comment]
Is this also the case with shapefiles? They usually don't have an explicit PK field.

**Comment by borysiasty** [comment]
> Hi, how do you expect editing to work without any PK field?

Normally - memory layers don't use PK. Please note also in 3.11, if I add any field (e. g. boolean) and even remove it immediately, the vertex tool starts to work. 

So it has nothing to do with PK. Actually QgsFeature.id() don't reflect any field in most providers/formats.  

But after your question I checked PostGIS layers with oids (instead of PK) and it turned out they are also not editable anymore!

> Is there a FID displayed in 3.10?

No, and feat.fields().toList() returns []. 

> Is this also the case with shapefiles? They usually don't have an explicit PK field.

QGIS create Shapefiles with at least one field, so there is no issue. If I remove that field and load the layer again, the vertex tool works, however adding new features and saving changes is grayed out (although I can save changes when exiting the edit mode). So it seems Shapefiles are not affected, and the two actions are unnecessarily grayed out, but it's another story.

**Comment by borysiasty** [comment]
Now I see also snapping doesn't work, so the vertex tool malfunction is derived I guess.

**Comment by borysiasty** [comment]
A bunch of more detailed tests: it's exactly the same situation as described in https://github.com/qgis/QGIS/issues/33449#issuecomment-573310241

**Comment by gioman** [comment]
> A bunch of more detailed tests: it's exactly the same situation as described in [#33449 (comment)](https://github.com/qgis/QGIS/issues/33449#issuecomment-573310241)

@borysiasty closing as duplicate?

**Comment by borysiasty** [comment]
Ok, merged
