### ISSUE TITLE
Rubberband not working correctly with "Shapes" digtizing in rotated map window 

### ISSUE THREAD

**Issue by bvthomsen** [qgis/QGIS#33287]
If you try to digitize a polygon (and other types of objects) using the "Shapes" ditizing tool in a **rotated** map-window the rubberband shows strange geometries. The ordinary digtizing tool works as expected.

Affected version (at least) QGIS v. 3.10 64 bit on windows 8.1

**Comment by gioman** [comment]
> using the "Shapes" ditizing tool

@bvthomsen 
is that a 3rd party plugin?

**Comment by bvthomsen** [comment]
Not AFAIK. I'm referring to the digitizing tools in a toolbar called "Shape Digitizing toolbar". 

I don't have any plugins installed that contains these functions, so it must be core functionality or a system plugin

**Comment by bvthomsen** [comment]
Further examination reveals that the resulting object seem to be geometrically correct even if the rubberbard is screwed up during the digitizing.

**Comment by lbartoletti** [comment]
Duplicate of https://github.com/qgis/QGIS/issues/25095
Still present in master
