### ISSUE TITLE
Crash on adding layers from SHP files.

### ISSUE THREAD

**Issue by l-nick** [qgis/QGIS#33299]
QGIS 3.10.0 running on Windows 7 64-bit crashes on adding a second layer from SHP file.

Steps to reproduce:

1. Creating new project
2. Adding a shapefile by double-clicking it in the 'browser' pane
3. Adding another shapefile using the same procedure
4. Getting 'QGIS unexpectedly ended' window

Making the layer of the shp added in the second step invisible by unticking its visibility checkbox in the 'layers' pane allows to add another layer without a crash. Making it visible again after adding another shp-file doesn't induce crash too.

Report details:
Crash ID: 795c5c9bccb9f4a984c02874fa2f41d6caecafb3

Stack Trace

QBasicMutex::unlockInternal :
QgsTask::processSubTasksForCompletion :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.10.0-A Coru�a
QGIS code revision: 6ffa89eb3e
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

UPD: The same behavior occurs when trying to perform the described steps using QGIS 3.8.3.
Adding the same files using Layer > Add Layer > Vector Layer > same shp files with () File radiobutton selected works without crashing.

**Comment by gioman** [comment]
@l-nick 
Can't replicate please try with a new QGIS profile.

**Comment by l-nick** [comment]
All the actions described were performed with a freshly created profile from the start.

**Comment by gioman** [comment]
> All the actions described were performed with a freshly created profile from the start.

please test 3.10.1 and master if possible. Thanks.

**Comment by l-nick** [comment]
Ok, I'll download 3.10.1 and test it asap. The OS in question works on an offline computer, so would weekly snapshot be ok for testing instead of dev-master installed via OSGeo4W?

**Comment by l-nick** [comment]
3.10.1 crashes performing the same sequence, but not every time, something like 1 crash of 5-10 tries.
Crash report is:

Crash ID: be168d9a9e75f6ed6759e76bc7a8a06239a44887


Stack Trace


QCoreApplication::postEvent :
qt_qFindChildren_helper :
QMetaObject::activate :
QgsTask::statusChanged :
QgsTask::processSubTasksForCompletion :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.10.1-A Coru�a
QGIS code revision: ef24c526da
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by l-nick** [comment]
dev-master weekly snapshot crashes too.
Report:

Crash ID: 956212f0fe728478554e3cb2309e447dc6312466


Stack Trace


QBasicMutex::unlockInternal :
QgsRecentColorScheme::~QgsRecentColorScheme :
QgsRecentColorScheme::~QgsRecentColorScheme :
QgsRecentColorScheme::~QgsRecentColorScheme :
QgsRecentColorScheme::~QgsRecentColorScheme :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.11.0-Master
QGIS code revision: 358e466517
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.0dev
Running against GDAL: 3.1.0dev



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by gioman** [comment]
> dev-master weekly snapshot crashes too.

clean Windows testing environment here, no crash with 3.10.1 and master.

**Comment by roya0045** [comment]
@l-nick does it occurs with the same shapefiles or any shapefiles?

**Comment by l-nick** [comment]
@roya0045 I can't speak about _all_ shapefiles, but I tried different shp from different sources, and the crash reproduced with different ones. As the latest try, I tried files from this example: http://www.spatialquerylab.com/FOSS4GAcademy/GST101-Module4Lab-QGIS2.8.zip

Adding Sage_grouse_current_distribution.shp just after adding Land_ownership.shp (with the steps described in the first message in the thread) in the new empty project caused 3.11.0-Master (code revision: 358e466517) to crash.

Crash ID: e33f4015dbc4904379a1cd047f8e5c13cc72c43f


Stack Trace


QMutex::tryLock :
QMutex::lock :
QgsRecentColorScheme::~QgsRecentColorScheme :
QgsRecentColorScheme::~QgsRecentColorScheme :
QgsRecentColorScheme::~QgsRecentColorScheme :
QgsRecentColorScheme::~QgsRecentColorScheme :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.11.0-Master
QGIS code revision: 358e466517
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.0dev
Running against GDAL: 3.1.0dev



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by gioman** [comment]
> As the latest try, I tried files from this example: http://www.spatialquerylab.com/FOSS4GAcademy/GST101-Module4Lab-QGIS2.8.zip

no crahs here on 3.10.1 on Windows

**Comment by l-nick** [comment]
Got it, thanks. Maybe it just something wrong with my OS/computer then. Sorry for the disturbance here.

**Comment by gioman** [comment]
Closing as is not replicable on other machines and/or operating systems.
