### ISSUE TITLE
Bring the remaining Array functions from ArrayPlus into Core

### ISSUE THREAD

**Issue by PedroVenancio** [qgis/QGIS#33302]
It would be a good improvement to bring the remaining array functions from ArrayPlus into Core

https://framagit.org/jbdesbas/arrayPlus

It seems that this was already tried, but it does not went to the end/merge:

https://github.com/qgis/QGIS/pull/7645

**Comment by pigreco** [comment]
https://github.com/qgis/QGIS/pull/40364

**Comment by m-kuhn** [comment]
this shortens the list to the following ones:

- array_avg
- array_count
- array_lambda
- array_minority
- array_prioritize 
- array_replace

**Comment by nyalldawson** [comment]
Some of these already exist, just with different names:
- array_lambda: array_foreach
- array_count: array_length
- array_avg: array_mean

**Comment by m-kuhn** [comment]
Well then, we are left with

-  array_minority
-  array_prioritize
-  array_replace

**Comment by jbdesbas** [comment]
> Some of these already exist, just with different names:
> 
>     * array_lambda: array_foreach
> 
>     * array_count: array_length
> 
>     * array_avg: array_mean

Hi,

_array_coun_t give the count of a **specific** value, so is not the same as _array_lenght_.

**Comment by DelazJ** [comment]
I think "le compte est bon" now, and this report can be closed.

**Comment by PedroVenancio** [comment]
Thanks!
