### ISSUE TITLE
Now() function stores time incorrectly

### ISSUE THREAD

**Issue by bakkerss** [qgis/QGIS#33303]
When I use the function now() for a time field the current time is proposed correctly in the entry form. However, once the data has been saved the time is stored as a date.
I have tried several options to store time using the 'format_date' expression and the 'to_time' expression . But all with the same result.
When I use the 'to_time' expression a tekst box appears stating the datetime can't be converted to type time. 

**How to Reproduce**

In the attachment the details of the expressions can be found.

[Now function stores time incorrectly.pdf](https://github.com/qgis/QGIS/files/3940157/Now.function.stores.time.incorrectly.pdf)

QGIS version data

QGIS-versie | 3.10.0-A Coruña | QGIS code revisie | 6ffa89eb3e
-- | -- | -- | --
Gecompileerd tegen Qt | 5.11.2 | Gebruikt nu Qt | 5.11.2
Gecompileerd tegen GDAL/OGR | 3.0.2 | Gebruikt nu GDAL/OGR | 3.0.2
Gecompileerd tegen GEOS | 3.8.0-CAPI-1.13.1 | Gebruikt nu GEOS | 3.8.0-CAPI-1.13.1
Gecompileerd tegen SQLite | 3.29.0 | Uitgevoerd met SQLite | 3.29.0
PostgreSQL Client Versie | 11.5 | SpatiaLite-versie | 4.3.0
QWT versie | 6.1.3 | QScintilla2 Versie | 2.10.8
Gecompileerd tegen PROJ | 6.2.1 | Gebruikt nu PROJ | Rel. 6.2.1, November 1st, 2019
Versie OS | Windows 10 (10.0)
Actieve plug-ins van Python | OSMDownloader; pdokservicesplugin; pdok_locatieserver_locator_filter; qfieldsync; QuickOSM; quick_map_services; db_manager; MetaSearch; processing

Windows 10 home

**Comment by elpaso** [comment]
Can you share a project and data to reproduce the issue?

**Comment by bakkerss** [comment]
Apparently I don't have to use the expression now() at all to default the current time in QGIS. By default the current date and time are proposed in QGIS without this expression. However, when syncing the project to Qfield, the date and time fields in Qfield are empty and I must use the now() expression to have the date/time field filled. 

In Qfield there is also a bug around time fields so perhaps these problems are related. Here you can find the related issue:

https://github.com/opengisch/QField/issues/728#issuecomment-561700916.

I tried attaching my project (a .qgz file zipped) but it fails to upload. Is there any other way I can share my project?

In the project I added 6 time fields, all with different types (String, date and datetime). I also noticed the following strange behavior. If I add a point QGIS will initially store the time in the attribute table. As soon as I touch the field QGIS converts the time into a date (the bug). But then also the field type changes from Qdatetime to Date.

**Comment by gioman** [comment]
> However, when syncing the project to Qfield, the date and time fields in Qfield are empty and I must use the now() expression to have the date/time field filled.

This is a QField issue not QGIS's.



> I tried attaching my project (a .qgz file zipped) but it fails to upload. Is there any other way I can share my project?

zip it.

**Comment by bakkerss** [comment]
I already zipped it but somehow failed to load yesterday.  Attached you can find the project.

[Example project issue 33303.zip](https://github.com/qgis/QGIS/files/3944852/Example.project.issue.33303.zip)

Within this project the example can be found under 'Vleermuizen - waarnemingen'. 

As indicated in the previous comment a seperate issue has been raised for QField. I received a confirmation that this is indeed a bug which needs to be solved.

**Comment by bakkerss** [comment]
I am closing this issue as QGIS and Qfield behave differently in the current version. I will raise a new issue

**Comment by danass** [comment]
i have two fields 
var_one with default expression now()
and var_two with default expression now() and box update on change checked;

but when both are created, var_one is always the same datetime (probably the moment when i created the first feature). but i never updates.
