### ISSUE TITLE
Export, Geopdf, Layertransparency and Layer Rendering, Blendig mode, multiply are not respected

### ISSUE THREAD

**Issue by gespiel** [qgis/QGIS#33305]
Export, Geopdf, Layertransparency and Layer Rendering, Blendig mode, multiply are not respected in the exported pdf.
QGIS 3.10.1 and master
jpg is attached.

![export_geopdf_layer_transparency_not_respected](https://user-images.githubusercontent.com/51882943/70459596-cd5bc380-1ab4-11ea-9932-83815c519ff8.jpg)

**Comment by haubourg** [comment]
Can you check what is the pdf standard version that QGIS produces ?  I think you can have it in the document properties from within Adobe Reader. 

From what I get, blending modes are supported by PDF >= 1.6. If you have a version 1.4 or 1.5, then it is probably a feature request, and maybe a feature request for GDAL

**Comment by gespiel** [comment]
- pdf version ist 1.6
- blending and transparency in section simple fill is not repected
- transparency in section fill is respected.
jpgs with settings are attatched.
![33305_fill_transparency_is respected](https://user-images.githubusercontent.com/51882943/71370399-1c722000-25ae-11ea-8e29-642b0da7e3af.jpg)
![33305_pdf_version](https://user-images.githubusercontent.com/51882943/71370400-1c722000-25ae-11ea-9a63-7a3475279bf5.jpg)
![33305_simplefill_transparency_blending not respected](https://user-images.githubusercontent.com/51882943/71370401-1c722000-25ae-11ea-80df-687ca358b8ab.jpg)
