### ISSUE TITLE
Export, Geopdf, Layernames are replaced through layer 1, layer2... in the exported pdf

### ISSUE THREAD

**Issue by gespiel** [qgis/QGIS#33306]
Export, Geopdf, Layernames are replaced through layer 1, layer2... in the exported pdf.

![export_geopdf_layer_transparency_not_respected](https://user-images.githubusercontent.com/51882943/70459833-507d1980-1ab5-11ea-8e4e-464d829c680b.jpg)

**Comment by jagodki** [comment]
Using QGIS 3.10.2 on Windows 10, I can confirm this bug with Raster layers and with vector layers without features. If a vector layer contains at least one feature, the layer name will be shown correctly in the GeoPDF.

**Comment by sigmoe** [comment]
I confirm to have the same problem using QGIS 3.10.3
