### ISSUE TITLE
Merge Vector Layers - Wrong or missing parameter value:Input layers

### ISSUE THREAD

**Issue by Saijin-Naib** [qgis/QGIS#33307]
**Describe the bug**
When attempting to merge vector layers using this processing algorithm, it will fail when layers are being added from the current QGIS layer list, but will work fine when loaded from disk directly. However, if you then close/reopen the Merge tool and re-attempt the merge with layers from the layer list, it will run correctly.
```
An error has occurred while executing Python code: 

IndexError: list index out of range 
Traceback (most recent call last):
  File "C:/OSGeo4W64/apps/qgis/./python/plugins\processing\gui\wrappers.py", line 209, in widgetValue
    return self.value()
  File "C:/OSGeo4W64/apps/qgis/./python/plugins\processing\gui\wrappers.py", line 804, in value
    return [options[i] if isinstance(i, int) else i for i in self.widget.selectedoptions]
  File "C:/OSGeo4W64/apps/qgis/./python/plugins\processing\gui\wrappers.py", line 804, in 
    return [options[i] if isinstance(i, int) else i for i in self.widget.selectedoptions]
IndexError: list index out of range


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.10.1-A Coruña A Coruña, ef24c526da 

Python Path:
C:/Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\networks
C:/OSGeo4W64/apps/qgis/./python
C:/Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGeo4W64/apps/qgis/./python/plugins
C:\OSGeo4W64\bin\python37.zip
C:\OSGeo4W64\apps\Python37\DLLs
C:\OSGeo4W64\apps\Python37\lib
C:\OSGeo4W64\bin
C:\Users\username\AppData\Roaming\Python\Python37\site-packages
C:\OSGeo4W64\apps\Python37
C:\OSGeo4W64\apps\Python37\lib\site-packages
C:\OSGeo4W64\apps\Python37\lib\site-packages\win32
C:\OSGeo4W64\apps\Python37\lib\site-packages\win32\lib
C:\OSGeo4W64\apps\Python37\lib\site-packages\Pythonwin
C:/Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\joinmultiplelines
C:/Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Polygons_Pile
```

**How to Reproduce**
1) Have layers loaded in the layer list
2) Attempt to merge layers
3) See that merge fails with above noted error
4) Load same layers from disk by browsing
5) Verify that merge is successful
6) Close tool, re-open tool
7) Add layers from layer list
8) Verify merge is successful

**QGIS and OS versions**

QGIS version | 3.10.1-A Coruña | QGIS code revision | ef24c526da
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.2 | Running against GDAL/OGR | 3.0.2
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.2.1 | Running against PROJ | Rel. 6.2.1, November 1st, 2019
OS Version | Windows 10 (10.0)
Active python plugins | CalculateGeometry; DataPlotly; joinmultiplelines; latlontools; MemoryLayerSaver; networks; openlayers_plugin; PluginLoadTimes; Polygons_Pile; processing_gnm; qchainage; qconsolidate; QGISSortAndNumber-master; realcentroid; refFunctions; SelectWithin; SplitPolygonShowingAreas; statist; db_manager; processing

**Additional context**
Tipped off by a GIS.stackexchange question:
https://gis.stackexchange.com/questions/344470/wrong-or-missing-parameter-value-input-layers

**Comment by roya0045** [comment]
Are you using the network provider? Isn't that a 3rd party plugin?

I might be misinterpreting.

**Comment by Saijin-Naib** [comment]
I'm confused as to what you're asking.

The layers are stored on a mapped windows network drive, if that's what you mean.

**Comment by roya0045** [comment]
I saw `C:/Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\networks` and thought you were using that plugin, forgot that the path vars are printed also.

**Comment by alexbruy** [comment]
I can not reproduce on master.

1. Added two layers to project
2. In "Merge Vector Layers" algorithm selected them as inputs
3. Output generated without errors

**Comment by Saijin-Naib** [comment]
Can't reproduce on weekly master:

QGIS version | 3.11.0-Master | QGIS code revision | 2b195e9450
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.0dev | Running against GDAL/OGR | 3.1.0dev
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.0 | Running against PROJ | Rel. 6.3.0, January 1st, 2020
OS Version | Windows 10 (10.0) | This copy of QGIS writes debugging output.
Active python plugins | CalculateGeometry; DataPlotly; joinmultiplelines; latlontools; MemoryLayerSaver; networks; openlayers_plugin; PluginLoadTimes; Polygons_Pile; processing_gnm; qchainage; qconsolidate; QGISSortAndNumber-master; realcentroid; refFunctions; SelectWithin; SplitPolygonShowingAreas; statist; db_manager; processing

**Comment by alexbruy** [comment]
Closing?

**Comment by Saijin-Naib** [comment]
The original poster still has the issue as far as I know, but I can't reproduce anymore. I guess it sorted itself out in master?
