### ISSUE TITLE
No more French in QGIS 3.10.1 on macOS

### ISSUE THREAD

**Issue by dd-a** [qgis/QGIS#33315]
In QGis 3.10.1 the user interface on a Mac (10.13.x and also 10.14.x, downloaded from [https://qgis.org/downloads/macos/pr/qgis_pr_final-3_10_1_20191206_142356.dmg]) has switched back to English although the Os is in French (Detected active locale is fr_BE). No User Interface Translation available for French in the list to override the system locale.

**Comment by PeterPetrik** [comment]
related: https://github.com/qgis/QGIS-Mac-Packager/issues/30

**Comment by lbartoletti** [comment]
Same issue on FreeBSD ( cc @rhurlin )

**Comment by gioman** [comment]
Seems ok to me on 3.14.0 on macOS Catalina. Reopen if necessary.
