### ISSUE TITLE
gdal2xyz (QGIS 3.4.13; Yesterday downloaded and installed; Windows)- The csv. file is not saved to the PC.

### ISSUE THREAD

**Issue by UHULBR** [qgis/QGIS#33337]
Gdal2xyz does not save and create csv. file to selected location on PC. On the console, however, the whole process is going well.

**Comment by gioman** [comment]
Can't confirm here on both 3.4 and 3.10.1 (on Windows).

**Comment by UHULBR** [comment]
Do you use QGIS version 3.4.14?

**Comment by gioman** [comment]
> Do you use QGIS version 3.4.14?

yes

**Comment by alexbruy** [comment]
Not reproducible on master, 3.4 and 3.10

**Comment by alexbruy** [comment]
Closed for the lack of feedback.
