### ISSUE TITLE
GRASS: replace liblas commands with pdal ones

### ISSUE THREAD

**Issue by pcav** [qgis/QGIS#33335]
Current ``*lidar*`` GRASS modules do not work. Upstream they have been replaced by ``pdal`` ones. Modules should be updated in Processing and in GRASS plugin.

**Comment by gioman** [comment]
Link/reference?
In the GRASS 7.8 manual I still see the v.lidar/r.lidar modules. While r.in.pdal is listed as a GRASS addon.

**Comment by pcav** [comment]
Thanks for investigating. So lidar commends are working for you?
See the thread: https://lists.debian.org/debian-gis/2019/12/threads.html

**Comment by gioman** [comment]
> So lidar commends are working for you?

yes on both GRASS 7.8.1 on Windows and 7.4.0 on Linux.

**Comment by pcav** [comment]
OK, not clarified: on Debian Sid `liblas` has been dropped because of serious bugs, unlikely to be fixed AFAIK. As a result I do not have the commands on my box. In a way it's a local issue, but in the longer term a proper solution will have to be found.
Thanks for the help, and sorry for the noise.
