### ISSUE TITLE
Showing wrong feature info after publishing in 3.4 and 3.10 ( in 2.18 good )

### ISSUE THREAD

**Issue by EDGIS2018** [qgis/QGIS#33357]
<Good afternoon,

Last years I used QGIS 2.18 to publish maps in QGISCLOUD. The user of the maps could read the street and housenumber while clicking on the feature. Publishing in QGIS 3.4 shows the wrong values. In stead of showing the street and housenumber the customer sees the qc_id. 

I'm posting this question here because I think it's a bug in QGIS 3.4 / 3.10, and publishing in QGIS 2.18 gives the good result.

I added 6 printscreens, the first 3 are in QGIS 3.4, the other 3 in qgis 2.18.  See the results on printscreen 3 and printtscreen 6. I'm hoping this can be fixed in the QGIS 3 versions.
Thanks from the Netherlands !

![1  command in QGIS 3 4 Madeira](https://user-images.githubusercontent.com/35311044/70722118-02575880-1cf7-11ea-9d2c-74359d7ed2ad.PNG)
![2  QGIS 3 4 - in the desktop the right value is shown ( in this case zoeknaam which is MIDDENAKKER 16 )](https://user-images.githubusercontent.com/35311044/70722120-02575880-1cf7-11ea-89ab-44b9294945c4.PNG)
![3  Shown Feature info in QGISCLOUD (after publishing in QGIS 3 4 ) is the qc_id 15630 instead of zoeknaam MIDDENAKKER 16 which is NOT what we want to be shown_LI](https://user-images.githubusercontent.com/35311044/70722122-02575880-1cf7-11ea-9511-2b83c41ab0da.jpg)
![4  command in QGIS 2 18 Las Palmas](https://user-images.githubusercontent.com/35311044/70722123-02efef00-1cf7-11ea-9a25-faa95172bba3.PNG)
![5  QGIS 2 18 - in the desktop the right value is shown ( in this case zoeknaam which is MIDDENAKKER 16 )](https://user-images.githubusercontent.com/35311044/70722124-02efef00-1cf7-11ea-81b3-5485e5dfac79.PNG)
![6  Shown Feature info in QGISCLOUD (after publishing in QGIS 2 18 ) is the zoeknaam MIDDENAKKER 16 which is what we want to be shown_LI](https://user-images.githubusercontent.com/35311044/70722125-02efef00-1cf7-11ea-9cee-9d024a6386f4.jpg)

**Comment by gioman** [comment]
@EDGIS2018 to me seems that is QGIS cloud that needs to catch up with the changes in QGIS 3. Can you please ask the authors?

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
