### ISSUE TITLE
GDAL Unable to Access Postgres Raster 

### ISSUE THREAD

**Issue by crabel99** [qgis/QGIS#33354]
Not sure if this is a bug or an installation problem, based on how I can reproduce the issue I think that it is more on the bug side (however I'm usually wrong), specifically with how the Windows version communicates SSL credentials to GDAL to import tiled rasters. With the same user credentials and configuration on the MAC version, there is no issue.

From clean installs of 3.10.0 and then 3.10.1 (thanks for the bug fix with DB Manager) on multiple Windows platforms, including using the *.exe installer and the OSGeo installer the final installed version is not capable of being able to access raster tables.

When attempting to add a layer the following error is returned:
```bash
Invalid Layer: GDAL provider Cannot open GDAL dataset PG: dbname='my_gis' host=my.host.com sslmode=verify-ca authcfg=keypairfingerprint mode=2 schema='my_schema' column='rast' table='my_table' Couldn't establish a database connection Raster layer Provider is not valid (provider: goal, URI: PG: dbname='my_gis' host=my.host.com sslmode=verify-ca authcfg=keypairfingerprint mode=2 schema='my_schema' column='rast' table='my_table'
```
There are no issues in how vector/non-vector tables are accessed either by adding them as layers or when accessing them directly through the DB Manager. The issue is not present on a Mac (10.14.6), but is present on 3 different windows machines (Windows 10) I've tested.

When accessed through DB Manager by selecting the appropriate table and then Preview, the program responds as if I had provided the incorrect SSL credentials. It returns a field asking for credentials with the same error when adding layer is attempted.

**Comment by gioman** [comment]
@crabel99 duplicate of https://github.com/qgis/QGIS/issues/30392 ?

**Comment by crabel99** [comment]
looks like it will close this and add my comment into that thread. Thanks!
