### ISSUE TITLE
crash on update z on postgres db

### ISSUE THREAD

**Issue by seur2000** [qgis/QGIS#33351]
Crash ID: cd240faef663603de24a8089d32bb225f5d5dfaf

Stack Trace

QMetaObject::disconnect :
QObject::disconnectImpl :
QgsVertexTool::setHighlightedVertices qgsvertextool.cpp:2388
QgsVertexTool::deactivate qgsvertextool.cpp:334
QgsMapCanvas::setMapTool qgsmapcanvas.cpp:1750
QMetaObject::activate :
QAction::triggered :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1598
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.10.0-A Coru�a
QGIS code revision: 6ffa89eb3e
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by elpaso** [comment]
Steps to reproduce?

**Comment by gioman** [comment]
Also (along with the datailed steps as asked by Alessandro, update to most recent version and/or try with a new QGIS profile, no 3rd party plugins installed.

**Comment by seur2000** [comment]
I'm working with Postgres12 and modifying nodes and lines by positioning
the vertices at the same height .. but often everything gets stuck and this
makes work useless.
I read about incompatibility with pg12 quind I installed pg11 but the
situation does not change.
maybe I behave badly
modifies more elements and punctual lines and then saves, maybe once saved
but then stops abnormally.

where can I find errors? thank you and forgive me if you can use my
translation

Il giorno gio 12 dic 2019 alle ore 12:21 Giovanni Manghi <
notifications@github.com> ha scritto:

**Comment by gioman** [comment]
> where can I find errors? thank you and forgive me if you can use my

have you tried what as been asked here https://github.com/qgis/QGIS/issues/33351#issuecomment-564966019 ?

what are the detailed steps to replicate?

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
