### ISSUE TITLE
Unable to add a feature even if editing is toggled on

### ISSUE THREAD

**Issue by arspragu** [qgis/QGIS#33362]
When i toggle editting on a layer on and go to add a feature, the feature does not show up. Nor does it bring up the feature form when i right click it to commit the added feature. The attribute table of all the data in the layer functions normally. QGIS 3.10.1

**Comment by roya0045** [comment]
What is the type/source of the layer?

**Comment by arspragu** [comment]
It affects Vector/Line/ and Polygon layers.The layer source is from a postgres database. I know I have not had issues in the past with prior releases.

**Comment by arspragu** [comment]
I confirmed that this issue is not specific to one version of QGIS 3. Still have feature form issues and am not able to add layers.

**Comment by gioman** [comment]
> When i toggle editting on a layer on and go to add a feature, the feature does not show up. Nor does it bring up the feature form when i right click it to commit the added feature.

@arspragu I cannot cofirm here on 3.10.1/Windows. Please try with a new QGIS profile on a clean project.

**Comment by haubourg** [comment]
@arspragu did you test with a clean profile?

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
