### ISSUE TITLE
Unable to open the feature form for any feature that i identify -BUG

### ISSUE THREAD

**Issue by arspragu** [qgis/QGIS#33361]
When identifying a feature on a layer using the identify feature tool I am unable to get the feature form to open regardless of if I make sure that the Auto Open Form radio button in checked and that I am only trying to identify a single feature. I am using QGIS 3.10.1 currently 
![image](https://user-images.githubusercontent.com/19801458/70725783-0077a000-1ccb-11ea-9f61-6ed88a589ec3.png)

**Comment by gioman** [comment]
@arspragu can't confirm here on 3.10.1 on Windows. Please try with a new QGIS profile.

**Comment by alexbruy** [comment]
Closed for the lack of feedback. Please reopen if necessary.
