### ISSUE TITLE
QGis crash again

### ISSUE THREAD

**Issue by GeoMon55** [qgis/QGIS#33364]
Crash ID: db8768b901c5e2e3a0dfd51d059d8384b14c65b6

Stack Trace

memcpy memcpy.asm:137
QSortFilterProxyModel::qt_metacast :
QSortFilterProxyModel::removeRows :
QSortFilterProxyModel::sortRole :
QSortFilterProxyModel::`default constructor closure' :
QMetaObject::activate :
QAbstractItemModel::beginRemoveRows :
QgsAttributeTableModel::removeRows qgsattributetablemodel.cpp:177
QgsAttributeTableModel::featuresDeleted qgsattributetablemodel.cpp:158
QMetaObject::activate :
QgsVectorLayer::featuresDeleted moc_qgsvectorlayer.cpp:960
QgsVectorLayer::onFeatureDeleted qgsvectorlayer.cpp:4539
QMetaObject::activate :
QgsVectorLayerEditBuffer::featureDeleted moc_qgsvectorlayereditbuffer.cpp:361
QgsVectorLayerEditBuffer::commitChanges qgsvectorlayereditbuffer.cpp:644
QgsVectorLayer::commitChanges qgsvectorlayer.cpp:3090
QgisApp::saveEdits qgisapp.cpp:9838
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1598
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.10.0-A Coru�a
QGIS code revision: 6ffa89eb3e
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment]
@GeoMon55 please update to 3.10.1 Also try with new QGIS profile and if nothing works add *detailed* steps to replicate and attach a sample project with data.

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
