### ISSUE TITLE
Errors/warnings reprojecting EPSG:2951 with 26918, 3857, 4326

### ISSUE THREAD

**Issue by Houska1** [qgis/QGIS#33367]
I appreciate the efforts in QGIS 3.10.0-3 and 3.10.1 to make QGIS and proj6 play nice, but I'm still having reprojection problems. Here is simplified example. 

My project CRS is EPSG:2951. Layers are natively in 2951, 3857, and 26918. I'm using QGIS 3.10.1, OSGEO4Win, running against proj 6.2.1. I have manually also installed proj-datumgrid-north-america. 

1.  As the screenshot shows, by default my map displays OK, but there are critical "cannot normalize transform" errors silently logged (they reoccur anytime there is a canvas redraw). In addition, every time I restart I get the "cannot use preferred transform between EPSG:26918 and EPSG:2951" message bar alert. This persists regardless of which of the top 2 choices I make for datum transformations between these 2 CRSes when asked to choose, or subsequently in Project Properties / CRS / Datum transformations.

2. If I click through the "Details" button in the message bar, I am invited to install grid shift file NAD83-98.gsb. At [proj-datumgrid/blob/master/north-america/README.NORTHAMERICA](https://github.com/OSGeo/proj-datumgrid/blob/master/north-america/README.NORTHAMERICA), I learn this is the same as [NA83SCRS.GSB](https://github.com/OSGeo/proj-datumgrid/blob/master/north-america/NA83SCRS.GSB). If I download this file and rename it to NAD83-98.GSB, then the QGIS dialog from the message bar is willing to install it. When I then restart, the message bar error goes away. However the EPSG:26918 layer is (silently) not displayed (ie the closed purple contour line does not appear). The message log critical errors continue.  If I manually delete the NAD83-98.GSB file that has been installed in my profile in the proj directory, I revert to the (preferable, since the layer displays) behaviour of 1.

The simplified test project, and its underlying data as a gpkg, attached as a zip.
All this worked normally through QGIS 3.8 (with proj < 6) and also QGIS 3.10.0-1 (as opposed to -3). 

![ScreenClip](https://user-images.githubusercontent.com/48919900/70735634-9cf66e00-1cdc-11ea-86cc-1fdeab6b3095.png)
[testproj.zip](https://github.com/qgis/QGIS/files/3957110/testproj.zip)

**Comment by Houska1** [comment]
Relevant links - [gis.stackexchange query by me](https://gis.stackexchange.com/questions/344705/qgis-proj-errors-with-epsg2951) and #32936 (by me, similar problem but while bigger problems between QGIS 3.10.0-3 and proj6 were at play).

**Comment by nyalldawson** [comment]
I can't reproduce under when running with https://github.com/qgis/QGIS/pull/33370

**Comment by nyalldawson** [comment]
I'll test with current master under proj 6, but this has potentially already been fixed in either qgis or proj

**Comment by nyalldawson** [comment]
Ok - I can confirm the "cannot normalize projection" issue under current master, but not when running with #33370. Looks like #33370 fixes this one too.

**Comment by nyalldawson** [comment]
I'll leave this ticket open as feedback for you to test with a nightly release after #33370 is merged

**Comment by Houska1** [comment]
Just checked and I confirm it is fixed (at least on the test project) on a clean install of the nightly dev release.  Thanks!
