### ISSUE TITLE
GeoPDF not working after export (version 3.10.1)

### ISSUE THREAD

**Issue by szaszszabolcs1** [qgis/QGIS#33363]
Hello!

I found a bug in the version 3.10.0.  I have a polygon layer that contains some features, In my case some circles. The circles are hatched on my map. Here comes the problem, when my PDF is exported it says : Theres an error in this file, ...please contact the creator of the PDF. I tried to export that polygon layer with simple filled symbology, that way it worked. So I guess the problem is with the hatched fill somehow. The strange thing is, when I delete some features from that poly layer the exported PDF works fine, without error.

**Comment by gioman** [comment]
@szaszszabolcs1 please attach a sample project/data.

**Comment by szaszszabolcs1** [comment]
Unfortunately I cant do that because the data im working with is classified, but its a normal polygon shapefile. Thank you for your answer.

**Comment by nyalldawson** [comment]
Without a test case this is impossible to diagnose unfortunately...

**Comment by szaszszabolcs1** [comment]
@nyalldawson , @gioman I attached the shapefile and project file that I created. I put the PDF in the zip file as well. The strange thing is, its working in Foxit PDF reader, but not in Acrobat Reader.
[map_export.zip](https://github.com/qgis/QGIS/files/3960713/map_export.zip)
Thank you for your help!

**Comment by gioman** [comment]
> The strange thing is, its working in Foxit PDF reader, but not in Acrobat Reader.

@szaszszabolcs1 so does not seems a QGIS issue after all.

**Comment by szaszszabolcs1** [comment]
@gioman It seems not , but i think its related with the GeoPDF feature. I tried many versions of Acrobat Reader , none of them is able to read the file.

**Comment by roya0045** [comment]
@szaszszabolcs1 out of curiosity can you try another pdf reader such as sumatra? I find it strange that only foxit can handle them.

**Comment by szaszszabolcs1** [comment]
@roya0045 Thank you for your response. I tried sumatra but I think it cannot handle layered PDF-s.

**Comment by roya0045** [comment]
@szaszszabolcs1 ah right, forgot about that, I couldn't think of an other program that can handle layered pdfs :/

**Comment by andreasneumann** [comment]
Layered PDFs are supported by many viewers. On Linux I can use them with "okular" (KDE) or "evince" from Gnome.

But for the other GeoPDF features (measuring, coordinate display and display of attributes), there is almost only Acrobat. This means, that there is no full-featured GeoPDF capable viewer on Linux.

**Comment by nyalldawson** [comment]
Not sure what can be done here - I think we should close this ticket

**Comment by Sile96** [comment]
I ran into this issue the other day. This [post](https://community.adobe.com/t5/acrobat-reader/an-error-exists-on-this-page-acrobat-may-not-display-the-page-correctly-please-contact-the-person/td-p/10469080?page=1) was helpful for me.
