### ISSUE TITLE
Exporting SLD doesnt include fill-opacity

### ISSUE THREAD

**Issue by dersteppenwolf** [qgis/QGIS#33376]
**Describe the bug**
Exporting symbology to SLD doesn't include the opacity (fill-opacity in sld) defined using "Layer rendering"

**How to Reproduce**

1. Go to symbology / layer rendering / opacity
2. Click on apply.  The GUI shows the simbology with opacity
3. Export symbology to SLD. The generated SLD doesn`t include the fill-opacity parameter
`        <se:SvgParameter name="fill-opacity">0.25</se:SvgParameter>`

**QGIS and OS versions**
Mac . 3.4.13

**Additional context**

**Comment by Pedro-Murteira** [comment]
I can still reproduce this on QGIS 3.16.15 and 3.22.2.

**Comment by 9ls1** [comment]
Hm, is this fixed in ver. 3.28.0 (released 2022-10-21)? I can't see opacity (<se:SvgParameter name="fill-opacity">0.25</se:SvgParameter>) included in my SLD-file?

**Comment by 9ls1** [comment]
Thanks for this fix. Works like a charm i ver. 3.28.
