### ISSUE TITLE
Relation Reference misbehaviour

### ISSUE THREAD

**Issue by pcav** [qgis/QGIS#33372]
Following the example from
https://docs.qgis.org/3.4/en/docs/user_manual/working_with_vector/attribute_table.html#introducing-many-to-many-n-m-relations
I noticed that it does not work, at least with 3.10.
The default Relation Reference, automatically selected, displays the
value column, and tries to insert the same (which obviously fails, being
a string) instead of the key, which would work.
Changing the widget type, by hand, with a Value relation, makes it work.

**Comment by m-kuhn** [comment]
Which steps exactly did you try to reproduce, what are the expected outcomes and what do you see?

I am a bit at loss because the section linked above does not talk about relation reference (and should not, since for N:M relations, a relation reference widget is not the right tool to show).

**Comment by pcav** [comment]
I followed exactly what is described in the link:
* creating the three tables
* loading all three in an empty project
* Project ‣ Properties ‣ Relations ‣ Discover Relations
* Layer Properties ‣ Attributes Form for the airports and airlines layers. For the first one I choose the airlines (id) option and for the second one the airports (id) option
* I link existing child feature in the subforms. A record will automatically be inserted in the airports_airlines table
* when saving, I get the error described above.

**Comment by m-kuhn** [comment]
Thanks for the detailed report.

I assume the misbehavior is related to the "relation editor" widget (which shows a list of multiple children / related features) and not to the "relation reference" widget (which is a dropdown to link to one specific feature in 1:N relations, like the "value relation" widget mentioned in the report as well).

Does this make sense to you?

**Comment by pcav** [comment]
Unclear to me, the type of widget is apparently not displayed in Layer Properties ‣ Attributes Form

**Comment by m-kuhn** [comment]
It's not a field widget, but a relation widget. For the drag and drop editor listed next to the fields, qml and html widget.
It's for the parent side of the relation, where there is no field available to configure it on.

**Comment by billjwilliamson** [comment]
Getting similar experience in QGIS version | 3.10.2-A Coruña | QGIS code revision | 616ad4531b
Running against GDAL/OGR | 2.2.3  OS Version | Ubuntu 18.04.4 LTS

Have tried it as a Geopackage and on Postgresql. 
Only variation is that tables do not have geometry. 
Discussion, https://gis.stackexchange.com/questions/351649/many-to-many-relationship-in-a-qgis-geopackage-fail  

Related bug? https://github.com/qgis/QGIS/issues/30171
