### ISSUE TITLE
Qgis 3.10 - Copy entity from shp to sqlite

### ISSUE THREAD

**Issue by Kazkan** [qgis/QGIS#33377]
When i copy entities from a shapefile layer to a Sqlite layer in a qgz project, Qgis always crash. 
This used to work in Qgis 3.8.

1 - I select and copy the entities from the shapefile layer (using ctrl+c)
2 - I paste the entites in the Sqlite layer (and it takes an unusually long time but it still works)
3 - I try to save my Sqlite layer after leaving the edition mode
4 - Qgis doesn't respond anymore and finally crash
5 - I reopen my Qgis project and I see my Sqlite layer didn't save the pasted entities

**Comment by gioman** [comment]
@Kazkan please add sample project with sample data.

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
