### ISSUE TITLE
Composer paper size reverts to letter

### ISSUE THREAD

**Issue by ghost** [qgis/QGIS#33381]
Composer paper size reverts to letter-portrait when A4 landscape is selected.

System Linux Fedora30, HP laserjet 1160

To reproduce:
New layout, right click in page, select page properties and set to A4 landscape.
Add a map.
In Menu->Layout->Page setup check page size, this defaults to Letter-portrait, change this to A4-landscape.
Print to printer containing A4 paper. Printer blinks because paper size is wrong for loaded paper, press override (or cancel) button on printer.  Map is printed landscape (or cancelled).
Back to Menu->Layout->Page setup check page size, and see it has reverted to Letter-portrait again.

**Comment by alexbruy** [comment]
Still true in 3.10/master?

**Comment by EvansMike** [comment]
Just tried this in 3.13.0-Master, same results.

**Comment by Pedro-Murteira** [comment]
Still true on QGIS 3.16.15 and 3.22.2.

**Comment by alexbruy** [comment]
Can't reproduce with the latest master (e5e6a13671) on Linux. Page size remain the same.
