### ISSUE TITLE
XYZ Tile Generator crashes due to memory leak?

### ISSUE THREAD

**Issue by DanielNLD** [qgis/QGIS#33393]
I have created a QGIS project and imported a CSV data set. I have added conditional labels. In total there are about 160.000 points with labels.

I try to export image tiles using the Processing Toolbox: generate XYZ tiles (Directory).
![tiles](https://user-images.githubusercontent.com/58861978/70826012-26de2e00-1de6-11ea-83eb-adfd7053e43c.PNG)

QGIS starts processing until the system runs out of memory after which QGIS crashes.

I found when only the Base layer from Wikimedia is selected the CPU and memory usage remains stable.

When selecting the layer with the data points with or without labels CPU goes up and eventually it crashes due to being out of memory. No crash window is shown.

Also tried to create a new project and just add the data points from the csv file and start the XYZ tool but after a short while the CPU and memory goes up again until the point of crashing.

QGIS version | 3.10.1-A Coruña
QGIS code revision | ef24c526da
OS Version | Windows 10 (10.0)
Active python plugins | pdokservicesplugin; qgis2web; quick_map_services; db_manager; MetaSearch; processing

**QGIS Processing Log:**
QGIS version: 3.10.1-A Coruña
QGIS code revision: ef24c526da
Qt version: 5.11.2
GDAL version: 3.0.2
GEOS version: 3.8.0-CAPI-1.13.1 
PROJ version: Rel. 6.2.1, November 1st, 2019
Processing algorithm…
Algorithm 'Generate XYZ tiles (Directory)' starting…
Input parameters:
{ 'BACKGROUND_COLOR' : QColor(0, 0, 0, 0), 'DPI' : 96, 'EXTENT' : '370105.1538221377,807162.0713756337,6572997.527245209,7083899.032047429 [EPSG:3857]', 'METATILESIZE' : 4, 'OUTPUT_DIRECTORY' : 'D:\\hmp\\test', 'OUTPUT_HTML' : 'TEMPORARY_OUTPUT', 'QUALITY' : 75, 'TILE_FORMAT' : 0, 'TILE_HEIGHT' : 256, 'TILE_WIDTH' : 256, 'TMS_CONVENTION' : False, 'ZOOM_MAX' : 17, 'ZOOM_MIN' : 17 }

Using 6 CPU Threads:
Pushing all tiles at once: 149644 tiles.

**Crash Report:**
Crash ID: b2759a90df4ab42e27e623527d2de72137aa53d2

Stack Trace

QIODevice::channelReadyRead :
QIODevice::write :
QLocalSocket::isSequential :
QHttpMultiPart::qt_metacast :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
QEventLoop::exec :
QgsWmsProvider::draw qgswmsprovider.cpp:882
QgsWmsProvider::readBlock qgswmsprovider.cpp:904
QgsRasterDataProvider::block qgsrasterdataprovider.cpp:201
QgsSingleBandColorDataRenderer::block qgssinglebandcolordatarenderer.cpp:62
QgsBrightnessContrastFilter::block qgsbrightnesscontrastfilter.cpp:118
QgsHueSaturationFilter::block qgshuesaturationfilter.cpp:123
QgsRasterResampleFilter::block qgsrasterresamplefilter.cpp:162
QgsRasterProjector::block qgsrasterprojector.cpp:878
QgsRasterIterator::readNextRasterPartInternal qgsrasteriterator.cpp:130
QgsRasterDrawer::draw qgsrasterdrawer.cpp:60
QgsRasterLayerRenderer::render qgsrasterlayerrenderer.cpp:266
QgsMapRendererCustomPainterJob::doRender qgsmaprenderercustompainterjob.cpp:312
QgsMapRendererCustomPainterJob::start qgsmaprenderercustompainterjob.cpp:115
sipQgsMapRendererCustomPainterJob::start sip_corepart1.cpp:189964
QgsMapRendererCustomPainterJob::renderSynchronously qgsmaprenderercustompainterjob.cpp:215
meth_QgsMapRendererCustomPainterJob_renderSynchronously sip_corepart1.cpp:190947
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyException_SetTraceback :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyException_SetTraceback :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PySignal_AfterFork :
PyThread_tss_is_created :
thread_start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.10.1-A Coru�a
QGIS code revision: ef24c526da
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by elpaso** [comment]
Can you please share a test project to reproduce the issue?

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
