### ISSUE TITLE
Dynamic libraries loading erros in PyQGIS on macOS

### ISSUE THREAD

**Issue by sadads1337** [qgis/QGIS#33397]
Hello!
I was trying to develop simple python application via this guide [link](https://docs.qgis.org/3.4/en/docs/pyqgis_developer_cookbook/intro.html#using-pyqgis-in-custom-applications).
And I met some problems while trying to run an example code.

```
from qgis.core import *

# Supply the path to the qgis install location
QgsApplication.setPrefixPath("/path/to/qgis/installation", True)

# Create a reference to the QgsApplication.
# Setting the second argument to True enables the GUI.  We need
# this since this is a custom application.

qgs = QgsApplication([], True)

# load providers
qgs.initQgis()

# Write your code here to load some layers, use processing
# algorithms, etc.

# Finally, exitQgis() is called to remove the
# provider and layer registries from memory
qgs.exitQgis()
```

The first issue I've ran into was `ImportError: No module named qgis.core` as described in cookbook, its' easy to solve it, by providing `PYTHONPATH=/<qgispath>/Contents/Resources/python`.

Then I met the error:
```
Traceback (most recent call last):
  File "/Users/i.o.makarov/develop/local/PyQGISViewer/main.py", line 15, in <module>
    from qgis.core import *
  File "/Applications/QGIS3.10.app/Contents/Resources/python/qgis/core/__init__.py", line 25, in <module>
    from qgis._core import *
ImportError: dlopen(/Applications/QGIS3.10.app/Contents/Resources/python/qgis/_core.so, 2): Library not loaded: @executable_path/../Frameworks/qgis_core.framework/qgis_core
  Referenced from: /Applications/QGIS3.10.app/Contents/Resources/python/qgis/_core.so
  Reason: image not found
```
Okey, it's described too, adding `DYLD_LIBRARY_PATH=/Applications/QGIS3.10.app/Contents/MacOS/lib` works, and it finds `_core.so`

But then, something strange happens:
It can't load PyQt library
```
ImportError: dlopen(/Applications/QGIS3.10.app/Contents/Resources/python/PyQt5/QtCore.so, 2): Library not loaded: @executable_path/../Frameworks/QtCore.framework/QtCore
  Referenced from: /Applications/QGIS3.10.app/Contents/MacOS/lib/QtCore.so
  Reason: image not found
```

All the things work fine in QGIS python console.

I guess the problem is on my environment, but I haven't find any related topics. So the question, what is the proper way to use PyQt on macOS, and how should I setup my environment?

**Comment by gioman** [comment]
> So the question, what is the proper way to use PyQt on macOS, and how should I setup my environment?

@sadads1337 please ask questions in the users or developers mailing lists, on gis.stackexchange or the QGIS IRC/Gitter channel. Thanks!

**Comment by christianurich** [comment]
I run into the same issues and it took me quite a while to work out a solution. 

Here are my steps that worked:

1. The above error originated for me from not using the QGIS python environment. if you use /Applications/QGIS13.12.app/Contents/MacOS/bin/python3 it will probably work 

2. The next error I faced was 

```
qt.qpa.plugin: Could not find the Qt platform plugin "cocoa" in ""
```

Defining the plugin path resolved this issue for me

```
 os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = '/Applications/QGIS3.12.app/Contents/PlugIns'
```
