### ISSUE TITLE
Projections seem to be completely broken with proj 5.2 / gdal 2.4 ?

### ISSUE THREAD

**Issue by borysiasty** [qgis/QGIS#33402]
Since 187b8f3325, projections seem to not work at all on Debian Buster / PROJ 5.2 / GDAL 2.4:

- The CRS selector dialog is partially broken (empty CRS definition text area, empty CRS extent map widget)
- Setting the project CRS takes no result (always falls back to 'No projection')
- Setting the layer CRS takes no result
- Layers added from the Browser or the DataManager have undefined CRS (tested with OGR, Postgis, GDAL) and some of them crash QGIS
- Opening some old projects crash QGIS
- With an old ("dirty") user profile, also opening the Datasource manager or the Settings dialog crash QGIS. Other problems occur also with a clear user profile.

All the problems start from 187b8f3325 and still persist in yesterday's 40b198cf90c520d14.

@nyalldawson let me know if I can do any more detailed tests.

**Comment by nyalldawson** [comment]
I can't reproduce (and all the tests on Travis pass on proj 5). Maybe try a completely clean build?

**Comment by borysiasty** [comment]
Ok, my fault. It was a little less obvious - only system restart helped.
