### ISSUE TITLE
Split feature makes QGIS 3.4.6 crash

### ISSUE THREAD

**Issue by stage7** [qgis/QGIS#33408]
Hi,

I am getting QGIS crashed trying to perform the following actions:

1. Switch the only layer in the project to edit mode.
2. Select the spatial object comprising most of continental Europe (Portugal to Ukraine).
3. In the advanced digitizing toolbar choose the split features option.
4. Start tracing where the southern and eastern boundaries of Latvia would be until you have passed the limit with Lithuania (accuracy is not really a factor).

Expected output: the polygon is divided between Latvia and the rest of Europe.
Actual output: the program crashes and closes.

CLI output:
```
QGIS died on signal 11Could not attach to process.  If your uid matches the uid of the target
process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
ptrace: Operación no permitida.
No se seleccionó hilo
No stack.
gdb returned 0
Abortado (`core' generado)
```

QGIS version: 3.4.6
OS version: Ubuntu 16.04 LTS

It seems that the layer format is not relevant (tested with SHP and GeoJSON).

![qgis](https://user-images.githubusercontent.com/2507471/70865373-2caa4f80-1f5d-11ea-8b52-39607c3151c5.png)

[crash.zip](https://github.com/qgis/QGIS/files/3965125/crash.zip)

**Comment by gioman** [comment]
> I am getting QGIS crashed trying to perform the following actions:

@stage7 3.4.6 is too old. Please update to the latest 3.4 release and try again. Also try with a new QGIS profile, no 3rd party plugins installed.

**Comment by lbartoletti** [comment]
Already fixed.
