### ISSUE TITLE
QGIS crashed when trying to peudocolor raster data

### ISSUE THREAD

**Issue by jduval41** [qgis/QGIS#33415]
h2. User Feedback

I imported raster layers from GXF grid files using the Layers->Add Layer->From Raster. I was then changing the symbology to color the data when QGIS crashed. I did not use GDAL conversion directly although I had used that approach earlier but was having problems getting the layers to display when I had more than one layer. When importing using GDAL conversion I could specify the dummy value (1e+38). Asidq from crashing the grids seemed to display until I tried using pseudocolor. Perhaps it has to do with the dummy value which displayed black in the grey scale when I set min/max?

h2. Report Details

*Crash ID*: b3c6329c742d46f8f87a7e89adcacbe203d8dd85

*Stack Trace*
<pre>
QgsColorRampShader::shade :
QgsSingleBandPseudoColorRenderer::block :
QgsBrightnessContrastFilter::block :
QgsHueSaturationFilter::block :
QgsRasterResampleFilter::block :
QgsRasterProjector::block :
QgsRasterIterator::readNextRasterPart :
QgsRasterDrawer::draw :
QgsRasterLayer::draw :
QgsRasterLayer::previewAsImage :
QgsRasterLayerProperties::apply :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.0.3-Girona
QGIS code revision: commit:8a899c8758
Compiled against Qt: 5.9.2
Running against Qt: 5.9.2
Compiled against GDAL: 2.2.4
Running against GDAL: 2.2.4

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by gioman** [comment]
> I imported raster layers from GXF grid files

@jduval41 can you attach sample data?

**Comment by nirvn** [comment]
Here's your problem, your using QGIS 3.0.3. Update to the latest version, this is likely fixed already.

**Comment by nyalldawson** [comment]
Let's close - 3.0.3 is not supported at all.
