### ISSUE TITLE
QGIS 3.10.1 ImportError: DLL load failed

### ISSUE THREAD

**Issue by Infiziert90** [qgis/QGIS#33421]
**Describe the bug**
With 3.10.1 i can't import qgis.core without getting an import error. 
The same script runs fine under 3.10.0.

**How to Reproduce**
```
$python3
>>>import qgis.core 
3.10.1:
crash with the ImportError
3.10.0:
no problem
```

**QGIS and OS versions**

3.10.1 and 3.10.0 tested
Windows10 Build 17763

**Comment by Infiziert90** [comment]
Tested it with 3.10.2 and the issue is still there.

i used the "python-qgis.bat" in the /bin folder from qgis for the latest test. 
In 3.10.0 it works fine ... with .1 and .2 it drops the import error

**Comment by gioman** [comment]
@Infiziert90 no error on qgis master installed from osgeo4w.

**Comment by roya0045** [comment]
Multiple installs and dependencies issues ?

**Comment by Infiziert90** [comment]
> Multiple installs and dependencies issues ?
yeah, i uninstalled 3.4 and removed all files from 3.10 and now it works
