### ISSUE TITLE
Copy cell contents copies wrong cell contents

### ISSUE THREAD

**Issue by uclaros** [qgis/QGIS#33439]
**Describe the bug**

On a fresh 3.10.1 build (7d1eacc0bf) on debian, new clean profile, I have problems copying values from the attribute table.
When right clicking on a value and selecting "copy cell contents" the contents of another cell from the same row are copied. Using ctrl+c with no selected features works correctly and copies the value of the active cell, no problem.

**How to Reproduce**
1. Load a vector layer (geometry does not matter) with at least two fields.
2. Open attribute table.
3. Right click on a cell value other than the first column.
4. Select "copy cell contents"
5. Check the clipboard contents, it's not the expected value.

**QGIS and OS versions**

QGIS version | 3.10.1-A Coruña | QGIS code revision | 7d1eacc0bf
-- | -- | -- | --
Compiled against Qt | 5.11.3 | Running against Qt | 5.11.3
Compiled against GDAL/OGR | 2.4.0 | Running against GDAL/OGR | 2.4.0
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.27.2 | Running against SQLite | 3.27.2
PostgreSQL Client Version | 11.5 (Debian 11.5-1+deb10u1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.10.4
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Debian GNU/Linux 10 (buster)
Active python plugins | processing; MetaSearch; db_manager

**Additional context**
It works as expected on linux build final_3.8.3
I think it works as expected on windows even on 3.10.1 but I can't test right now.

**Comment by pigreco** [comment]
I confirm,
does not work in QGIS 3.10.1 OSGeo4W

```
Compilato con Qt
5.11.2
Esecuzione con Qt
5.11.2
Compilato con GDAL/OGR
3.0.2
Esecuzione con GDAL/OGR
3.0.2
Compilato con GEOS
3.8.0-CAPI-1.13.1
Esecuzione con GEOS 3.8.0-CAPI-1.13.1 
Compiled against SQLite 3.29.0
Running against SQLite 3.29.0
Versione client PostgreSQL 11.5
Versione SpatiaLite 4.3.0
Versione QWT 6.1.3
Versione QScintilla2 2.10.8
Compiled against PROJ 6.2.1
Running against PROJ Rel. 6.2.1, November 1st, 2019
OS Version Windows 10 (10.0)
```

**Comment by roya0045** [comment]
Question: is the value provided from one of the cells below the dialog where you are clicking the button? I'm curious to know if the sender is truly anchored where the right click happen or only where the last left click occur.

**Comment by pigreco** [comment]
@roya0045 

>Question: is the value provided from one of the cells below the dialog where you are clicking the button? I'm curious to know if the sender is truly anchored where the right click happen or only where the last left click occur.

Always copy the value of the first column

**Comment by roya0045** [comment]
I had the chance to do a test on 3.4.0 and it works fine also. The function itself doesn't seem to have changes in the last 3 years, This is weird.

**Comment by pigreco** [comment]
## QGIS 3.10.1
![copia_ta](https://user-images.githubusercontent.com/7631137/71899228-8b797800-315b-11ea-8549-10bb08712156.gif)

**Comment by roya0045** [comment]
This might be related to the changes made in this commit. https://github.com/qgis/QGIS/commit/39082474e79b6146d7b268332e5c574ff18d379e

Maybe @elpaso or @nyalldawson  could confirm if those changes could have inadvertently changed this.

**Comment by uclaros** [comment]
I confirm it broke with commit [3908247](https://github.com/qgis/QGIS/commit/39082474e79b6146d7b268332e5c574ff18d379e)

In [qgsdualview.cpp](https://github.com/qgis/QGIS/pull/32952/files#diff-21fe1ea6560d0888920c58c9e51e5bc1L667-R667) the source index is no longer aware of the column that was clicked, only the row.
`mFilterModel->mapToSource( atIndex );` allowed the retrieval of the column through the modelIndex passed.
`mFilterModel->fidToIndex( featureId );` does not

Copy Cell Contents is the only context menu entry that is column specific and affected by this, but  custom actions could also be affected by not passing the modelindex.

**Comment by roya0045** [comment]
@elpaso do you think that it would be possible to separate the current flow in two? A first step that would use the old approach to only set up the copy signal and the rest that would only rely of the feature id to constrain the other operation on a row basis?

**Comment by roya0045** [comment]
@uclaros if you still have a way to test qgis before the offending commit could you also see if that affected the issue reported in #33665 , I suspect they are related.

**Comment by uclaros** [comment]
You're right, I just tested my build without commit 3908247. Both *copy cell values* and *duplicate feature* work as expected. On the other hand, I can't reproduce #32933, the bug that commit 3908247 fixes!

As for #33439 and #33665, the row returned depends on the table's sorting, so at first the correct row might be returned. The cell copied seems to always be the first column.

**Comment by roya0045** [comment]
@uclaros Thank you for the help!

**Comment by roya0045** [comment]
@uclaros I made a bugfix, if you have some free time could you also validate that the fixes work for you also. It was fine for me but validation would be appreciated.

**Comment by uclaros** [comment]
I see you reverted commit 3908247, so copy and duplicate should work, but I don't seem to understand the other change you made in qgsdualview.cpp
What's the `idx` in 
`  QModelIndex rowSourceIndex = mFilterModel->fidToIndex( mFilterModel->rowToId( idx ) );` ?

**Comment by roya0045** [comment]
@uclaros I could not reproduce #32933 either even by simply reverting the commit but I didn't want to take a chance and went for a hybrid approach to be safe. The idx line was a git error, I tend to switch between prs on two environments and sometimes git break or I forgot to save one file.

 Should be fine now.

**Comment by uclaros** [comment]
@roya0045 ok, that explains it :)
So if I understand correctly, (apart from undoing commit 3908247) you change from cell modelIndex to row modelIndex with `  QModelIndex rowSourceIndex = mFilterModel->fidToIndex( mFilterModel->rowToId( atIndex ) );`
and use that for standard actions (duplicate feature - dup and digitize, is it also delete feature in form view?)  and open form.
I think we need someone who can replicate #32933 for validation, the other two bugs will be fixed with this.
Also tests. Can't this functionality be built on tests?

**Comment by roya0045** [comment]
@uclaros yes I am hoping that actions that are cell dependent are at the top of the code while actions that are only row dependent use the second index. That way things should be flexible enough.

As far as the bug test itself, I couldn't find a way to reproduce it in my environment anyway so it might be gone at this point somehow or intermittent. And making tests on intermittent things is bad and will bite you back. :/
