### ISSUE TITLE
Topological editing - changes revert when saving the layer

### ISSUE THREAD

**Issue by jfmoyen** [qgis/QGIS#33438]
**Describe the bug**

When editing a layer using topological editing, a new polygon overlapping a previously existing one is indeed clipped upon creation, as expected. However, when the layer is saved, the new poly reverts to the way it was drawn.

**How to Reproduce**

Use the attached shp as an example. 
[test_layer.zip](https://github.com/qgis/QGIS/files/3972247/test_layer.zip)

1. Open the shp file, project CRS 4326, layer CRS 4326.
2. Topological editing activated.
3. Zoom to the 5 stripes (not the northernmost zone, the ones just below). 
4. Edit the layer, add a polygon overlapping one of the existing stripes:
![bug1](https://user-images.githubusercontent.com/22688234/70980397-87ee5600-20b3-11ea-8cbf-69a2790b15a3.jpg)
5. Finish the poly. Topological editing, as expected, crops it so that it does not overlap the previous entities:
![bug2](https://user-images.githubusercontent.com/22688234/70980442-a0f70700-20b3-11ea-8d09-9ebe800b6d5b.jpg)
6. Save the layer. The new polygon is now reverted to the way it was drawn (i.e. not clipped, and overlapping the previous ones):
![bug3](https://user-images.githubusercontent.com/22688234/70980509-ba984e80-20b3-11ea-83a4-9e80b20b2dea.jpg)

**QGIS and OS versions**
Windows 7 professional, SP1, 64b

Initially spotted on 3.6.0 and, sadly, confirmed on 3.10.1 freshly minted (ef24c526da)

**Additional context**

This is an issue I recall facing long ago, with one of the 2.x versions probably. Was never really solved, and at that time I was editing a complex shapefile, with many potential errors, it was harder to isolate the issue.

**Comment by lbartoletti** [comment]
If I'm right, you can't overlap an invalid geometry. Maybe your base geometry is not clean. Can you confirm with a clean geometry please?

**Comment by jfmoyen** [comment]
The topology checker does not report any invalid geometry. Anything else I could check ?

**Comment by jfmoyen** [comment]
And another bit: if I now create a new poly, poly1, anywhere else in the canvas;
And another poly, poly2, overlapping...
![bug4](https://user-images.githubusercontent.com/22688234/70985412-5b8b0780-20bc-11ea-9084-b1c368f17ead.jpg)

poly2 is NOT clipped, as I'd expect :
![bug5](https://user-images.githubusercontent.com/22688234/70985468-7a899980-20bc-11ea-9033-078d7c6436b2.jpg)

(with, or without saving. Here saving does not make a difference).

**Comment by jfmoyen** [comment]
And, one more. This seem somehow related to the "phantom feature" shapefile bug that is reported occasionally. Here my file shows 10 features on map but 11 in the attribute table. Unfortunately deleting the offending line from the attribute table (the one with no geometry) does not make a difference...

**Comment by lbartoletti** [comment]
> poly2 is NOT clipped, as I'd expect :
> ![bug5](https://user-images.githubusercontent.com/22688234/70985468-7a899980-20bc-11ea-9033-078d7c6436b2.jpg)
> 
> (with, or without saving. Here saving does not make a difference).

Can you try with the advanced configuration and activate "Avoid overlap". This is a mandatory.
![image](https://user-images.githubusercontent.com/7521540/70995704-7451e800-20d1-11ea-9d9a-ed6c4434c071.png)

**Comment by jfmoyen** [comment]
> Can you try with the advanced configuration and activate "Avoid overlap". This is a mandatory.

Well this seems to work, so functionally my problem is solved (including the original one). I have no further complain. However the reported behaviour is a bit strange still, no ?

**Comment by lbartoletti** [comment]
> However the reported behaviour is a bit strange still, no ?

This https://github.com/qgis/QGIS/issues/33438#issuecomment-566487313 ? Please open a new ticket for this issue Thanks.
