### ISSUE TITLE
Snapping and vertex tool not working with some layers if snapping was enabled when loaded

### ISSUE THREAD

**Issue by borysiasty** [qgis/QGIS#33449]
It's a regression between 3.10 and 3.11/master.

With snapping enabled, if I open either:
 - an empty PostGIS layer
 - a memory layer without any attributes 

and add any features, snapping doesn't work, what makes also the vertex tool unable to find and highlight any feature.

**Steps to reproduce**

0. Ensure the snapping is ON during steps 1 and 2.
1. Either open an empty PostGIS layer, or a new memory layer without any fields
2. Add any feature
3. Try to edit vertices - doesn't work
4. Try to save changes, re-enter the edit mode etc - nothing helps
5. Load the layer again (now it's not empty during loading)
6. Try to edit vertices - now it works!
7. Add more features - still the vertex tool works fine, also on new features
8. Remove all features and GO TO 0. It doesn't work again

**Comment by troopa81** [comment]
I failed to reproduce the issue on both Linux and Windows with master (updated yesterday)

Here is what I am doing, to be sure I don't misunderstand the process

![bugsnap](https://user-images.githubusercontent.com/14358135/72163639-7e12f680-33c4-11ea-9008-7e215c8854d1.gif)

**Comment by borysiasty** [comment]
Do you have snapping enabled? I made hundreds additional tests and realized it's dependent on the snapping state during layer loading and then entering the edit mode:

1. If snapping is OFF all the time when loading the layer and entering the edit mode: everything works.

2. If snapping is ON all the time when loading the layer and entering the edit mode: the bug occurs.

If I toggle snapping between loading the layer and entering the edit mode:

3. Snapping is OFF during layer loading and then switched ON before entering the edit mode - the bug occurs.

4. Snapping is ON during layer loading and then switched OFF before entering the edit mode - the results are mixed (random or rather dependant on something else).

All the four cases above refers to the first edit session after the layer is loaded. Then, if you rollback the edit mode and enter it again with snapping ON or OFF, the results seem to be persistent (I mean the same as in the first edit session) until the layer is removed from the project.

If you remove the layer and load it again, all symptoms seem to be reset, so you can start another test without any need of using multiple layers nor restarting QGIS in order to get replicable results.

**Comment by borysiasty** [comment]
@troopa81 :
Do you have snapping enabled? I made hundreds additional tests and realized it's dependent on the snapping state during layer loading and then entering the edit mode:

1. If snapping is OFF all the time when loading the layer and entering the edit mode: everything works.

2. If snapping is ON all the time when loading the layer and entering the edit mode: the bug occurs.

If I toggle snapping between loading the layer and entering the edit mode:

3. Snapping is OFF during layer loading and then switched ON before entering the edit mode - the bug occurs.

4. Snapping is ON during layer loading and then switched OFF before entering the edit mode - the results are mixed (random or rather dependant on something else).

All the four cases above refers to the first edit session after the layer is loaded. Then, if you rollback the edit mode and enter it again with snapping ON or OFF, the results seem to be persistent (I mean the same as in the first edit session) until the layer is removed from the project.

If you remove the layer and load it again, all symptoms seem to be reset, so you can start another test without any need of using multiple layers nor restarting QGIS in order to get replicable results.

**Comment by borysiasty** [comment]
In case 1) above, you can safely turn snapping on not earlier than after adding the first feature to the editing buffer.

**Comment by troopa81** [comment]
> If snapping is ON all the time when loading the layer and entering the edit mode: the bug occurs

That was it, I manage to reproduce now. Thanks for the details, I'll fix it.

**Comment by troopa81** [comment]
@Luckless1167 I'll take a look next bug fix session
