### ISSUE TITLE
python-qgis.bat does not set environment correctly on Windows for OSGEO4W install

### ISSUE THREAD

**Issue by ottadini** [qgis/QGIS#33440]
**Describe the bug**

Using the code examples for the processing module found in the [cheatsheet](https://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/cheat_sheet.html#processing-algorithms), **in the qgis python console** I can print a list of the algorithms available. I want to do the same from a "standalone" python script for my Windows box. I run `python-qgis.bat` and in the python shell that opens I run the same script as in the [cheatsheet](https://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/cheat_sheet.html#processing-algorithms), but no output is produced. 

**How to Reproduce**

1. Run `python-qgis.bat`.
2. In the python shell that opens, run [the code for creating a list of the processing algorithms](https://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/cheat_sheet.html#processing-algorithms).
3. In my case, no output is produced. 

**QGIS and OS versions**

item|value|item|value
-- | -- | -- | --
QGIS version | 3.8.0-Zanzibar | QGIS code revision | 11aff65f10
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.0 | Running against GEOS | 3.7.2-CAPI-1.11.0 b55d2125
PostgreSQL Client Version | 9.2.4 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Windows 10 (10.0) |   |  

**Additional context**

Running the code from the in-built python console does work.

**Comment by alexbruy** [comment]
This is correct behavior. You need to initialize QGIS application before accessing any registry.

**Comment by ottadini** [comment]
Even doing the following fails to return any output:

```
from qgis.core import *
import qgis.utils

# create qgis app object, no gui
qgs = QgsApplication([], False)

# Supply path to qgis install location
QgsApplication.setPrefixPath("C:\\OSGeo4W64\\bin", True)

# init Qgis
qgs.initQgis()

for alg in QgsApplication.processingRegistry().algorithms():
    print("{}:{} --> {}".format(alg.provider().name(), alg.name(), alg.displayName()))


```

**Comment by alexbruy** [comment]
You still have not registered providers in the registry.

**Comment by ottadini** [comment]
Hi, thanks for the response. I have no idea what I need to do to achieve that though.
Can you point me to docs that can tell me how to do this please? Or comment with your own knowledge?

**Comment by alexbruy** [comment]
After setting up QGIS environment you need to call `Processing.initialize()` or alternatively registed all required providers manually in the `QgsProcessingRegistry`.

**Comment by jgrocha** [comment]
Just an example:
```python
from qgis import processing
from processing.core.Processing import Processing
Processing.initialize()
QgsApplication.processingRegistry().addProvider(QgsNativeAlgorithms())
```
