### ISSUE TITLE
Grid in UTM and Geographical coordinates

### ISSUE THREAD

**Issue by fjgh77** [qgis/QGIS#33441]
Hello,
I have a project including a significant set of layers in WGS84/UTM28N. 
I would like to create and configurate two different grids with coordinates in the layout map.  One grid showing the coordinates in UTM format and the other one showing the coordinates in Geographical format.  I will use one or another depending of the end user. I don't need to show both of them at the same time. I am able to create the grids but I cannot configurate the geographical format labels. Any suggestion?
Thank you in advance.

**Comment by roya0045** [comment]
This is not a feature request, for such enquiries I would suggest you to post on the gis stackexchange and/or on the qgis user mailing list.

**Comment by fjgh77** [comment]
ok. Thank you.
