### ISSUE TITLE
Layout very slow with PostGIS point layer created from DB Manger

### ISSUE THREAD

**Issue by HarryEClarke** [qgis/QGIS#33450]
Opening a project containg 14 layers in QGIS 3.10.1 running under Windows 8 64-bit opens in about 8 seconds, containing a mixture of raster, line and point layers.
Open an existing layout without the point layer opens in a few seconds. However, if the point layer is added in, which consists of 49,293 records, mostly outside the map area, QGIS then takes a very very long time before the map is shown. Resource Manager shows that there is a lot of disk activity and PostgreSQL activity. Significantly reducing the number of records reduces the times, but still takes minutes to display.
The main point is that the Point Layer was created by a simple SQL command using DB Manager.

Opening a different project with several point layers, but this time created from the Browser panel, and then the Query Builder used to select the records required. Opened without problems within seconds, including displaying the Layout, which displayed in seconds.

The difference in the commands sent to the database server are
1) table = "(SELECT * FROM table1 WHERE name = 'abc')"
2) table = table1, sql = "name = 'abc'"

**Comment by gioman** [comment]
@HarryEClarke so If I understand correctly: the layer added via DB Manager is a query layer, while the one added by the browser is not a new layer, but rather a filter on an existing one, correct?

**Comment by HarryEClarke** [comment]
Yes that is correct

**Comment by gioman** [comment]
> Yes that is correct

then I think a difference in speed is expected. The query layer is basically a view.

**Comment by HarryEClarke** [comment]
I disagree. They are actually both views, and execution of the view is milli-seconds, and they both result in the same thing. There shouldn’t be any difference between displaying the query layer in QGIS in layer mode (or whatever the correct term is) – which is quick and layout mode – which is extremely slow. It as though in Layout mode, QGIS is repeatedly calling query for every point.

**Comment by elpaso** [comment]
@HarryEClarke is the query layer just slow in layouts or is it also slow when loading/rendering in the map canvas?

**Comment by HarryEClarke** [comment]
In Layout mode, the Query layer is painfully slow to load, but the other layers which are raster layers and boundary line layers load quickly.

The query layer is a point layer, with each point rendered as a solid circle

Any slight change to the Layout is very painful in the long wait whilst it refreshes

 

In the Map Canvas, all layers load/render fast

**Comment by gioman** [comment]
> I disagree. They are actually both views, and execution of the view is milli-seconds, and they both result in the same thing. There shouldn’t be any difference between displaying the query layer in QGIS in layer mode (or whatever the correct term is) – which is quick and layout mode – which is extremely slow. It as though in Layout mode, QGIS is repeatedly calling query for every point.

@HarryEClarke can't replicate on the latest releases, would you mind test again?
