### ISSUE TITLE
Organize Columns button in Attribute Table toolbar

### ISSUE THREAD

**Issue by Saijin-Naib** [qgis/QGIS#33466]
**Feature description.**
I would like to see the Organize Columns tool accessible from the Attribute Table toolbar, in part to further expose this functionality, as well as to provide a solution to some long-standing UX quirks as referenced below. It would also make it easier to expose via keyboard navigation.

**Additional context**
As referenced by other bugs (#27250 , #23397 ), if you hide all the columns, you can't easily un-hide them as there is no column header available to right-click upon to access the Organize Columns tool.

**Proposed Location**
I think a natural fit for this icon would be in the cluster which currently contains New Field, Delete Field, and Field calculator. Perhaps after all three of these to not interfere with muscle-memory or existing docs/screenshots, as well as to provide a logical flow (add, remove, update, organize).  
![image](https://user-images.githubusercontent.com/19295950/71105528-b93a5500-218b-11ea-9031-13a857301b56.png)

**Proposed Icon**
I think the deisgn language of the Fields icon from the Layer Properties dialog fits quite nicely. Minor tweaks, if any.
![image](https://user-images.githubusercontent.com/19295950/71105743-1209ed80-218c-11ea-9c4c-8c52c5ae16a6.png)

**Comment by alexbruy** [comment]
Duplicates #23397
