### ISSUE TITLE
PDF Export Size / Resolution Inconsistency

### ISSUE THREAD

**Issue by Saijin-Naib** [qgis/QGIS#33465]
**Describe the bug**
GeoPDF export products (both ISO3200 and OGC styles) export at a page size that is scaled by a factor above the determined Page Size set in the Layout Manager.

For instance:  
Project settings: GeoPDF ISO3200 - ANSI D (34 x 22 inches)  

Export @ 150dpi: 70.83 x 45.83 inches
![image](https://user-images.githubusercontent.com/19295950/71100125-71630000-2182-11ea-9420-bb67e527b077.png)
    - 2.08 scale factor

Export @ 300dpi: 141.67 x 91.67 inches
![image](https://user-images.githubusercontent.com/19295950/71100162-82ac0c80-2182-11ea-8460-24b3ad756780.png)
    - 4.16 scale factor

Project Settings: Legacy PDF - ANSI D (34 x 22 inches)
Export @ 300dpi: 34 x 22 inches  
![image](https://user-images.githubusercontent.com/19295950/71117324-eeeb3800-21a3-11ea-98c3-2c30a9cc8127.png)
    - 1.00 scale factor

**How to Reproduce**
1) Set a known page size and export resolution (ANSI D @ 150/300dpi for this example)
2) Export PDF using GeoPDF variant (ISO3200 or OGC)
3) Inpsect document properties in PDF viewer
4) Note that actual page dimensions are scaled above what export was set to
5) Re-export same document using "Legacy" PDF
6) Inspect document properties in PDF viewer
7) Note that actual page dimensions match export settings

**QGIS and OS versions**

QGIS version | 3.10.1-A Coruña | QGIS code revision | ef24c526da
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.2 | Running against GDAL/OGR | 3.0.2
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.2.1 | Running against PROJ | Rel. 6.2.1, November 1st, 2019
OS Version | Windows 10 (10.0)
Active python plugins | CalculateGeometry; DataPlotly; joinmultiplelines; latlontools; MemoryLayerSaver; networks; openlayers_plugin; PluginLoadTimes; processing_gnm; qconsolidate; QGISSortAndNumber-master; realcentroid; refFunctions; SelectWithin; SplitPolygonShowingAreas; SpreadsheetLayers; statist; db_manager; processing

**Additional context**
Seems to be the same issue as Issue #32931

**Attachment**
This attachment contains a sample QGIS project, as well as sample export PDFs, and screenshots for the settings used to generate each set of export PDFs.  
[PDF_TEST.7z.zip](https://github.com/qgis/QGIS/files/3979107/PDF_TEST.7z.zip)

**Comment by nyalldawson** [comment]
I can't reproduce this -- using the attached project the generated PDFs are all correctly sized...

**Comment by Saijin-Naib** [comment]
I've not tried again on recent versions. Maybe this has been fixed in testing? I'll try on latest stable and report back.

**Comment by nyalldawson** [comment]
I suspect the difference here is in how Adobe Reader interprets the page size vs the PDF reader I'm using...

**Comment by Saijin-Naib** [comment]
> I suspect the difference here is in how Adobe Reader interprets the page size vs the PDF reader I'm using...

Hm, locally these files show the same (wrong) size in GSView, Foxit, and Adobe.

**Comment by agiudiceandrea** [comment]
If it can help, inspecting the provided pdf files you will find:
Legacy_150DPI.pdf
`<< /Annots 14 0 R /Contents 11 0 R /MediaBox [ 0 0 2448 1584 ] /Parent 3 0 R /Resources 13 0 R /Type /Page /VP [ 27 0 R ] >>`

Legacy_300DPI.pdf
`<< /Annots 14 0 R /Contents 11 0 R /MediaBox [ 0 0 2448 1584 ] /Parent 3 0 R /Resources 13 0 R /Type /Page /VP [ 27 0 R ] >>`

ISO3200_150DPI.pdf
`<< /Contents 3213 0 R /Group << /CS /DeviceRGB /S /Transparency /Type /Group >> /MediaBox [ 0 0 2448 1584 ] /Parent 1 0 R /Resources 3214 0 R /StructParents 0 /Type /Page /UserUnit 2.083333333333333 /VP [ 12 0 R 15 0 R ] >>`

ISO3200_300DPI.pdf
`<< /Contents 3213 0 R /Group << /CS /DeviceRGB /S /Transparency /Type /Group >> /MediaBox [ 0 0 2448 1584 ] /Parent 1 0 R /Resources 3214 0 R /StructParents 0 /Type /Page /UserUnit 4.1666666666666661 /VP [ 12 0 R 15 0 R ] >>`

As you can see, the `MediaBox` values (in default user space units) are the same (2448 1584), but for ISO3200_150DPI.pdf and ISO3200_300DPI.pdf a `UserUnit` value is also present.
This value (_A positive number that shall give the size of default user space units, in multiples of 1⁄72 inch_ _Default value: 1.0, user space unit is 1⁄72 inch_ ) represents a scale factor for the real page size: 2.0833 for ISO3200_150DPI.pdf and 4.1667 for ISO3200_300DPI.pdf.

So, the page size for Legacy_150DPI.pdf and Legacy_300DPI.pdf is 34 x 22 inches (2448*1/72=34 x 1584*1/72=22), while for ISO3200_150DPI.pdf is 70.83 x 45.83 inches (2448*2.0833/72=70.83 x 1584*2.0833/72=45.83) and for ISO3200_300DPI.pdf is 141.67 x 91.67 inches (2448*4.1667/72=141.67 x 1584*4.1667/72=91.67)

**Comment by agiudiceandrea** [comment]
Moreover, I cannot see any geospatial information for the provided pdf (OGC or ISO3200 ones) using the Geospatial Location Tool in Adobe Reader XI.

**Comment by agiudiceandrea** [comment]
See also ["[Qgis-user] Exporting a GeoPDF through Map Layout outputs a larger page size format"](https://lists.osgeo.org/pipermail/qgis-user/2020-June/046021.html)

**Comment by Saijin-Naib** [comment]
Is the over-scale output expected and part of the GeoPDF spec?

**Comment by agiudiceandrea** [comment]
I don't think so.  For example, ArcMap 9.3.1 exports a correct size GeoPDF for whatever resolution the user wants.

**Comment by nyalldawson** [comment]
I've attempted to fix this, but am blocked by https://lists.osgeo.org/pipermail/gdal-dev/2020-September/052681.html  -- it's possible there's an underlying GDAL bug at play here. Will report back any updates...

**Comment by Saijin-Naib** [comment]
Thanks for looking into this!
