### ISSUE TITLE
Sorting an attribute table with actions enabled hides the values in the ID column with the action's combo box

### ISSUE THREAD

**Issue by marioba** [qgis/QGIS#33464]
**Describe the bug**

This bug seems to be the same as the already closed #26731 that is still present in QGIS 3.10.1 on Linux. 

If the actions are visible in the attribute table, sorting a column causes the action combo box to be displayed above the values of the id column.

**How to Reproduce**
![actions_attribute_table](https://user-images.githubusercontent.com/24844357/71098011-493ec580-21b1-11ea-884c-ec616b5d658b.gif)

**QGIS and OS versions**

QGIS version | 3.10.1-A Coruña | QGIS code branch | Release QGIS code branch.3
-- | -- | -- | --
Compiled against Qt | 5.13.2 | Running against Qt | 5.13.2
Compiled against GDAL/OGR | 3.0.2 | Running against GDAL/OGR | 3.0.2
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.30.1 | Running against SQLite | 3.30.1
PostgreSQL Client Version | 12.1 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.3
Compiled against PROJ | 6.2.1 | Running against PROJ | Rel. 6.2.1, November 1st, 2019
OS Version | Arch Linux
Active python plugins | processing; db_manager; MetaSearch

**Additional context**

**Comment by Saijin-Naib** [comment]
Can confirm on Win10


QGIS version | 3.10.1-A Coruña | QGIS code revision | ef24c526da
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.2 | Running against GDAL/OGR | 3.0.2
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.2.1 | Running against PROJ | Rel. 6.2.1, November 1st, 2019
OS Version | Windows 10 (10.0)
Active python plugins | CalculateGeometry; DataPlotly; joinmultiplelines; latlontools; MemoryLayerSaver; networks; openlayers_plugin; PluginLoadTimes; processing_gnm; qconsolidate; QGISSortAndNumber-master; realcentroid; refFunctions; SelectWithin; SplitPolygonShowingAreas; SpreadsheetLayers; statist; db_manager; processing


For me, it also would appear that the furthest-left column next to FID will also get this behavior, if FID has been hidden using the Organize Columns feature.  
Original table:  
![image](https://user-images.githubusercontent.com/19295950/71104897-8fccf980-218a-11ea-9e51-c5d50f2dce3d.png)  

Hidden FID:  
![image](https://user-images.githubusercontent.com/19295950/71104934-a07d6f80-218a-11ea-8df4-26897def5717.png)

Hidden FID + Status:  
![image](https://user-images.githubusercontent.com/19295950/71104946-ab380480-218a-11ea-995d-f3914c24b77f.png)  

Hidden FID + Status + Town:  
![image](https://user-images.githubusercontent.com/19295950/71104967-b9862080-218a-11ea-9985-a9179d46a36b.png)

etc....

**Comment by bkepl** [comment]
I, to,o have been experiencing this odd table behavior, for several versions of QGIS. I created two custom actions to zoom or pan to a feature without having to first select a feature and click the icon at the top of the table or right-click the feature and choose the action from the context menu. I works well to rapidly move through a lot of features, until I sort on any field or edit a feature in any way, similar to what's described above. Here’s what happens:

1 – After adding Actions:
![1 – After adding Actions](https://user-images.githubusercontent.com/54165328/79889265-c2eaf800-83cb-11ea-8924-75cb9028a175.png)

2 – After sorting any column:
![2 – After sorting any column](https://user-images.githubusercontent.com/54165328/79889054-7bfd0280-83cb-11ea-9ef8-bfc5cafe102a.png)

3 – After editing any feature in any way:
![3 – After editing any feature in any way](https://user-images.githubusercontent.com/54165328/79887565-190a6c00-83c9-11ea-8cc1-be81b9586b73.png)

4 – This behavior occurs even when only the default actions show, as described in the post I'm commenting on; this is what happens after sorting any field:
![4 – This behavior occurs even when the default actions show](https://user-images.githubusercontent.com/54165328/79887611-29bae200-83c9-11ea-9eb4-c7ba4ac5429b.png)

**Comment by Pedro-Murteira** [comment]
@marioba I've tested this on windows 10 using QGIS 3.22.3 and I can't reproduce this anymore. Did you come across this issue more recently?

**Comment by marioba** [comment]
@Pedro-Murteira I just tried on QGIS 3.22.2 on Linux and the issue still happens.

**Comment by Ludwig-K** [comment]
The annoying behaviour still exists under QGis 3.30.1, Linux (Mint) and Windows.

The Id isn't hidden but overlapped by the duplicated QToolButtons.
![grafik](https://github.com/qgis/QGIS/assets/5821720/1631f11b-70da-432c-8f20-32eda3649496)

The buttons disappear, when table is refreshed.

Additional two "unwanted" buttons "Duplicate Feature" and "Duplicate Feature and Digitize" in actions and first column, remaining *in first column* after ending edit-mode and then leading to error-message "Cannot duplicate feature in not editable mode in layer...". Also funny, to offer "...and Digitize" for a geometry-less layer...

see https://issues.qgis.org/issues/17852
and the conversation under
https://marc.info/?l=qgis-developer&m=151857927809496&w=2

Btw: 
One of the tips in the above discussion was setting an option tools/showDuplicateFeatureActions with value false, but no success.

**Comment by bkepl** [comment]
This is still an issue in 3.30.3.
