### ISSUE TITLE
Scientific notation in attribute table for double type value

### ISSUE THREAD

**Issue by SebastienPeillet** [qgis/QGIS#33475]
**Describe the bug**

The scientific notation is not used in the attribute table for double type display. I'm aware that the use of scientific notation has already been discussed in some issues (like for labelling [here](https://github.com/qgis/QGIS/pull/32398), and [here](https://github.com/qgis/QGIS/pull/32398)).

The use of scientific notation for int or longlong type doesn't seem wished, which I agree, but at the moment it is also not used for double type. It can be annoying, especially for double number between 1 and -1, like 4.5e-09 for example that is displayed as '0.0000000' in attribute table

**How to Reproduce**

[test_decimal.zip](https://github.com/qgis/QGIS/files/3978270/test_decimal.zip)

the data test contains a gpkg file with a layer, that have a decimal field named `decimal_f`

1. Open the gpkg file in Qgis
2. Open the attribute table, `decimal_f` field displays 0,00000

![image](https://user-images.githubusercontent.com/18545440/71160939-c36e5900-2248-11ea-8984-afffc5c50ea7.png)

**QGIS and OS versions**

QGIS version | 3.11.0-Master | QGIS code revision | d0348127bf
-- | -- | -- | --
Compiled against Qt | 5.12.2 | Running against Qt | 5.12.2
Compiled against GDAL/OGR | 2.4.0 | Running against GDAL/OGR | 2.4.0
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.27.2 | Running against SQLite | 3.27.2
PostgreSQL Client Version | 11.5 (Ubuntu 11.5-0ubuntu0.19.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.10.4
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Ubuntu 19.04
Active python plugins | MetaSearch; processing; db_manager

**Additional context**

Can be fix by using 'g' mode [here](https://github.com/qgis/QGIS/blob/master/src/core/qgsfield.cpp#L255) and [here](https://github.com/qgis/QGIS/blob/master/src/core/qgsfield.cpp#L261)

![image](https://user-images.githubusercontent.com/18545440/71161184-2c55d100-2249-11ea-924d-5b27d88f8e44.png)

**Comment by elpaso** [comment]
Are you going to make a PR?

**Comment by SebastienPeillet** [comment]
Yes, just need the time to think about the test to add
