### ISSUE TITLE
processing polygonize broken in 3.4.14

### ISSUE THREAD

**Issue by ChrisWGeorge** [qgis/QGIS#33478]
**Describe the bug**
Running polygonize in the processing toolbox in QGIS 3.4.14 produces the error 
'C:\PROGRA~1\QGIS3~1.4\bin\python3.exe: No module named gdal_polygonize'

**How to Reproduce**
To reproduce the error, load a raster, open the processing toolbox, select GDAL -> Raster conversion -> Polygonize, select the raster as the input layer, and click Run.

**QGIS and OS versions**
QGIS 3.4.14
Windows 10

**Additional context**

The error is not present in 3.4.13.

**Comment by alexbruy** [comment]
This already fixed in OSGeo4W and standalone installer will be updated on the next point release, see [comment](https://github.com/qgis/QGIS/issues/33281#issuecomment-567010525).
