### ISSUE TITLE
QGIS crashes with spacific relations/widget settings

### ISSUE THREAD

**Issue by montarob** [qgis/QGIS#33487]
My Qgis project was crashing in continuous.
The project has been created with the version 3.4.2 Madeira.
In this project I am working uploading data from a spatialite database.
data into the database are:
1. Vector (point) representing the location of the site where I am working. This vector point is called "site" (see project attached)
2. A set of tables (tables without geometry) representing normal sheet registers. These tables are "permatrace_register" and "site_staff" (see the project attached).
Specifically, the table "permatrace_register" contains records of site surveys taken and the table "site_staff" contains the list of people involved in the survey.
I set some relationships in the project properties and some widgets in order to speed up the data entry.
In particolar, the setting was the following:
1. relation between "site" and "permatrace_register" (association), referenced layer = site, referenced field = site_name, referencing layer = permatrace_register, referencing field = site_name; this relation aims to get the "site_name" of the new "permatrace_register" records from the "site" vector.
2. I set up a widget to the attribute "taken_by" (see project) as a "Value Relation" aimed to get the name of the people that have been making the various surveys taken registered into the table "permatrace_register". More in depth, the original set of the widget has been done like this: Layer = site_staff, Key column = "signature", Value column = "signature".

With this kind of setting my project was crashing in continuous.
However, setting up the widget in this way: Layer = site_staff, Key column = "id", Value column = "signature", it seems like Qgis doesn't crash anymore.

So, at the end, the issue seemed to be caused by a wrong setting of the widget.

[ticket.zip](https://github.com/qgis/QGIS/files/3988021/ticket.zip)

**Comment by roya0045** [comment]
Why is the word 'Fixed' in the title?

**Comment by montarob** [comment]
Because in the Italian qgis user list there
Was an issue regarding to "qgis crash" opened by myself.
After some comparisons we realized where the mistake was.
Therefore, as other people have got the same problem, the moderator of the
Italian qgis user list invited me to open an issue even here explaining how
I have been able to fix the problem.
That's it.

Il ven 20 dic 2019, 12:43 Alex <notifications@github.com> ha scritto:

**Comment by gioman** [comment]
> So, at the end, the issue seemed to be caused by a wrong setting of the widget.

@montarob ok, but QGIS should not crash anyway. Can you please test with the latest 3.4 and 3.10 releases (3.4.2 is too old). Also use a new/clean QGIS profile.

**Comment by montarob** [comment]
Buonasera Giovanni,
sì farò questi test. L'unica cosa non ho capito cosa si intende con usare
un "New/clean qgis profile"...perdona la mia ignoranza.

Roberto Montagnetti

Il ven 20 dic 2019, 19:36 Giovanni Manghi <notifications@github.com> ha
scritto:

**Comment by gioman** [comment]
> osa si intende con usare un "New/clean qgis profile"

@montarob 
settings > user profiles > new profile 

(and do not install any 3rd party plugin while testing).

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
