### ISSUE TITLE
North Arrow - bug when rotating Map in composer

### ISSUE THREAD

**Issue by simogeo** [qgis/QGIS#33482]
**Describe the bug**
Working with 3.10.1 (ef24c52), Nort arrow does not rotate anymore when rotating map ...

**How to Reproduce**

1. Add map
2. Add arrow
3. Rotate map (here 15°)
4. See error, as below 

![image](https://user-images.githubusercontent.com/154323/71188867-0dbffc00-2282-11ea-85dd-6a1bc5c96768.png)

**QGIS and OS versions**

Version de QGIS | 3.10.1-A Coruña | Révision du code | ef24c526da
-- | -- | -- | --
Compilé avec Qt | 5.12.4 | Utilisant Qt | 5.12.4
Compilé avec GDAL/OGR | 2.4.2 | Utilisé avec GDAL/OGR | 2.4.2
Compilé avec GEOS | 3.7.2-CAPI-1.11.2 | Utilisé avec GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
Version du client PostgreSQL | 11.5 (Ubuntu 11.5-1) | Version de SpatiaLite | 4.3.0a
Version de QWT | 6.1.4 | Version de QScintilla2 | 2.10.4
Compilé avec PROJ | 5.2.0 | Fonctionne avec PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Ubuntu 19.10
Extensions Python actives | VectorBender; AnotherDXF2Shape; mask; Qgis2threejs; GeoCoding; vector_tiles_reader; ORStools; qconsolidate3; shapetools; Hqgis; DataPlotly; french_locator_filter; SRTM-Downloader; Beeline; OSMtools; QNEAT3; loadthemall; db_manager; MetaSearch; processing

**Comment by nyalldawson** [comment]
I can't reproduce -- can you post steps to show this issue?

**Comment by nyalldawson** [comment]
(or a sample project)

**Comment by simogeo** [comment]
Hi Nyall, 

Please find attached archive : https://framadrop.org/r/Sa4_9F1XID#AOODs7d+WATvcqDJIQ02n/Uusj8zmOd9iTmpouNKTAQ=

**Comment by gioman** [comment]
I also cannot replicate.

**Comment by simogeo** [comment]
Do you mean North arrow has correct rotation on given sample ?

**Comment by gioman** [comment]
> Do you mean North arrow has correct rotation on given sample ?

in the sample you linked (that do not include any data) there is an object in the layout which looks rotated but does not actually have any rotation angle in the layout properties. If you change the angle then the arrow will also rotate.

**Comment by simogeo** [comment]
sorry, here is the right archive : https://framadrop.org/r/YkjVcW_9ra#HERxfHAq9Oo5s5XlJB/6gNYRn9TFKFVLLAc+4fY0Hj8=

**Comment by gioman** [comment]
> sorry, here is the right archive : https://framadrop.org/r/YkjVcW_9ra#HERxfHAq9Oo5s5XlJB/6gNYRn9TFKFVLLAc+4fY0Hj8=

here is the point: in your layout there is a map object that *looks* rotated, but that actually has "0" has rotation angle. The moment you change the angle, the arrow rotates. Now the question is... how you got to add a map object that looks rotated but that actually has no rotation (as property in the layout composer)?

**Comment by simogeo** [comment]
hi @gioman, the point is .... there is rotation - see below : 

![image](https://user-images.githubusercontent.com/154323/71542229-ef35c100-2963-11ea-9a6f-39dc1aa986c4.png)

**Comment by roya0045** [comment]
Yeah the arrow seem to only care about the rotation of the data and not the layout object. I might be able to come up with a fix. Should be easy in theory.

**Comment by roya0045** [comment]
PR is made, I'll try to test it when I get back to work, otherwise if someone else can test it before my vacations are over, that would be welcome.

**Comment by simogeo** [comment]
thanks @roya0045 for your PR, I'm not synchronised with master version so I can't test, but thanks for fixing it.

**Comment by gioman** [comment]
> hi @gioman, the point is .... there is rotation - see below :+1: 

@simogeo the rotation property you are looking at is a different one:

![Screenshot_20191228_162848](https://user-images.githubusercontent.com/1951107/71546498-47ce8380-298f-11ea-8003-494652cc078f.png)

**Comment by gioman** [comment]
> Yeah the arrow seem to only care about the rotation of the data and not the layout object.

what is the point of making the arrow point in a direction that is not the map north?

**Comment by roya0045** [comment]
> > Yeah the arrow seem to only care about the rotation of the data and not the layout object.
> 
> what is the point of making the arrow point in a direction that is not the map north?

Exactly. If you want to have a layout item that is rotated to 45 degree, the north arrow will not care. It only cares about the content and not the object itself. My proposed fix also add the items rotation to the angle, this way the arrow will always point north even if the object itself is rotated and not its content.

**Comment by simogeo** [comment]
> @simogeo the rotation property you are looking at is a different one:

@gioman : indeed, I never realized there was two way for rotation ! was it the case before ? Anyway, this is very confusing for the final user. I think North arrow should also be linked to the object itself or the object rotation has to me removed ...What do you think ?
