### ISSUE TITLE
QGIS Crashing frequently

### ISSUE THREAD

**Issue by someone191** [qgis/QGIS#33483]
My QGIS is crashing every few hours. All my plugins are closed.

> ## User Feedback
> 
> Selecting Features and zooming out.
> 
> ## Report Details
> 
> **Crash ID**: [6b1db71cead6191726849d9ef7e26af683a56e4e]('https://github.com/qgis/QGIS/search?q=6b1db71cead6191726849d9ef7e26af683a56e4e&type=Issues')
> 
> 
> **Stack Trace**
> <pre>
> QgsFeatureSelectionModel::isSelected qgsfeatureselectionmodel.cpp:69
> QgsAttributeTableView::selectRow qgsattributetableview.cpp:412
> QMetaObject::activate :
> QHeaderView::sectionPressed :
> QHeaderView::mousePressEvent :
> QWidget::event :
> QFrame::event :
> QAbstractItemView::viewportEvent :
> QHeaderView::viewportEvent :
> QCoreApplicationPrivate::sendThroughObjectEventFilters :
> QApplicationPrivate::notify_helper :
> QApplication::notify :
> QgsApplication::notify qgsapplication.cpp:418
> QCoreApplication::notifyInternal2 :
> QApplicationPrivate::sendMouseEvent :
> QSizePolicy::QSizePolicy :
> QSizePolicy::QSizePolicy :
> QApplicationPrivate::notify_helper :
> QApplication::notify :
> QgsApplication::notify qgsapplication.cpp:418
> QCoreApplication::notifyInternal2 :
> QGuiApplicationPrivate::processMouseEvent :
> QWindowSystemInterface::sendWindowSystemEvents :
> QEventDispatcherWin32::processEvents :
> UserCallWinProcCheckWow :
> DispatchMessageWorker :
> QEventDispatcherWin32::processEvents :
> qt_plugin_query_metadata :
> QEventLoop::exec :
> QCoreApplication::exec :
> main main.cpp:1598
> BaseThreadInitThunk :
> RtlUserThreadStart :
> </pre>
> 
> 
> **QGIS Info**
> QGIS Version: 3.10.0-A Coru�a
> QGIS code revision: 6ffa89eb3e
> Compiled against Qt: 5.11.2
> Running against Qt: 5.11.2
> Compiled against GDAL: 3.0.2
> Running against GDAL: 3.0.2
> 
> 
> 
> **System Info**
> CPU Type: x86_64
> Kernel Type: winnt
> Kernel Version: 10.0.18362
>

**Comment by gioman** [comment]
> My QGIS is crashing every few hours. All my plugins are closed.

@someone191 not enough details to understand what is going on. First try with a new QGIS profile, and no 3rd party plugins installed (note that there are 3rd party plugins that are bad for QGIS even if not in use, and not even enabled, so you must test with a immaculate QGIS profile).

**Comment by someone191** [comment]
@gioman I uninstalled all my plugins. I am trying now and will update here. Is there a way to figure out which plugin is causing issues?

**Comment by roya0045** [comment]
For the stack trace that you posted its going to be hard to guess the source without steps to replicate it. The crash occured when something checked if an element was selected. This could be caused by many thing. If you have distinct crash traces, they might be related to something else that is causing instability in your setup.

**Comment by gioman** [comment]
> I uninstalled all my plugins

a quicker and better way is to create a new QGIS profile.

**Comment by someone191** [comment]
Can you explain what do you mean by creating a new QGIS profile? Do you mean uninstall, if yes how can I save my symbols, color ramps, keyboard shortkeys etc before uninstalling. 

Also, QGIS isn't showing under Add/Remove Program, should I just delete the OSGeo folder?

**Comment by roya0045** [comment]
@gioman you're going to need a special webpage with how to make a clean profile and how to remove plugins since you get asked so often.

@someone191 In the settings menu - User profile - New Profie.

**Comment by gioman** [comment]
> Can you explain what do you mean by creating a new QGIS profile? Do you mean uninstall, if yes how can I save my symbols, color ramps, keyboard shortkeys etc before uninstalling.
> 
> Also, QGIS isn't showing under Add/Remove Program, should I just delete the OSGeo folder?

@someone191 
you do not need to re-install and creating a new QGIS profile does not imply losing anything in the current profile you are using

settings > user profiles > new profile

**Comment by someone191** [comment]
I was able to do this. Let me try the new profile for some time, I will update here.
Thanks for all the help.

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
