### ISSUE TITLE
? Graphical Model, Spatialite Execute SQL, how does one select a table within the spatialite file database?

### ISSUE THREAD

**Issue by apiszcz** [qgis/QGIS#33484]
Version 3.10 (Windows), I also tested 3.8.3 same error.

How does one specify the table to select for a SQL query that exists in a spatialite.sqlite3 data base file on disk? Using in the Execute SQL query Database->algorithm tool panel in graphic modeler.

I set additional input datasources (input1....) value by selecting the three dots on the right, then in the next panel i select Add Files... and add data base file which has multiple tables.

spatialite.sqlite3 file has the following tables
events
xyztable

I would like to query xyztable
select * from xyztable; (FAIL)
select * from input1; (FAIL)
select * from input2; (FAIL

Running the model an error is produced related to the SQL query
<p><b>virtual:</b> Referenced table xyztable in query not found!

**Comment by gioman** [comment]
@apiszcz is this a question or a bug report?

**Comment by roya0045** [comment]
Seems to be a question regarding how to use an external SQL table.

**Comment by apiszcz** [comment]
Perhaps however there were related bugs in 3.4.x and 3.6 using Execute SQL, so I am not sure what the issue is. I hope it is user error.

**Comment by apiszcz** [comment]
If it is possible to select a table in a spatialite table than it is a question. If is not possible then it is a bug.

**Comment by gioman** [comment]
> If is not possible then it is a bug

please add a sample dataset and detailed steps to replicate.

**Comment by apiszcz** [comment]
In creating the steps I discovered my error in naming.
Will close this and continue with the model.
Thank you.
