### ISSUE TITLE
Project default symbology

### ISSUE THREAD

**Issue by StephPeriquet** [qgis/QGIS#33492]
After setting up the default symbology for a given project, the new settings for the marker (it works fine for lins and gradients fros instance) are lost after quitting QGIS. Every time I start it up again, I need to set the default again. I'm under Mac OS 10.14.6 and QGIS 3.10.0-A Coruña.

The current fix is to open the QGIS project as a text file and modify the default marker there, it seems to hold for now.

**Comment by suricactus** [comment]
Seems that 3.12 and current `master` are affected too.

**Comment by Pedro-Murteira** [comment]
This issue seems fixed on versions 3.16.15 and 3.22.2.

**Comment by StephPeriquet** [comment]
Hi guys, thanks for following up on this.
the issue is sorted indeed!
