### ISSUE TITLE
Adding grid - crash

### ISSUE THREAD

**Issue by PeterB-UK** [qgis/QGIS#33508]
## User Feedback

Adding a grid.

## Report Details

**Crash ID**: [1aff05dc87b94e91cd85505b8e47c4eb3b5b1b51]('https://github.com/qgis/QGIS/search?q=1aff05dc87b94e91cd85505b8e47c4eb3b5b1b51&type=Issues')

**Stack Trace**
<pre>
QWidget::mapTo :
QWidgetPrivate::moveRect :
QApplication::windowIcon :
QApplication::windowIcon :
QWidget::event :
QDockWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1598
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.1-A Coru�a
QGIS code revision: ef24c526da
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment]
@PeterB-UK please try with a new QGIS profile (no 3rd party plugins installed). If the problem persiste please attach a sample of the data is causing the crash.

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
