### ISSUE TITLE
Legend Title in Composer when Pulled from Map Cannot be Empty

### ISSUE THREAD

**Issue by PeroDejic** [qgis/QGIS#33501]
I use fairly long names of SHP files in a map and when I pull the legend for that in the composer I'd like to change / adjust the names. It doesn't allow me to have an empty title of the legend to see the legend items only and reverts back to the full name in the title. A workaround now is to have an empty space in the title field to remove it / make it not visible.
In previous version I was able to do so. 
Using QGIS 3.10.1 on MacOS Mojave 10.14.6.

**Comment by gioman** [comment]
@PeroDejic is this a feature request or a bug report?

**Comment by PeroDejic** [comment]
I'd say it is a bug as it was working in previous versions and reverts now to the full name used in the SHP file in the map when trying to delete the legend title in the properties.

**Comment by iona5** [comment]
just stumbled upon this bug and i would like to add that since the whole labeling of a layer in the print layout legend has changed in 3.14 it is now possible to set the layer label to an empty string.

**Comment by gioman** [comment]
> it is now possible to set the layer label to an empty string.

then this if fixed.
