### ISSUE TITLE
MISSING gdal204.dll

### ISSUE THREAD

**Issue by FRANCOSIBILLINI** [qgis/QGIS#33505]
Using OSGeo4W64 (last version) WINDOWS installer, 
QGIS SERVER show error 500
The problem is: "missing gdal204.dll".

I had put it directly into windows\system 32 to work properly.

**Comment by gioman** [comment]
@FRANCOSIBILLINI "gdal204.dll" is available in osgeo4w, where is the issue?

**Comment by FRANCOSIBILLINI** [comment]
Yes it is into apps/gdal2/bin but the system can't find... I don't know why.
Copying it into windows/system32 works.

I've installed into windows server 2016, windows 7, windows 10.
Always the same problem.

**Comment by gioman** [comment]
> Yes it is into apps/gdal2/bin but the system can't find... I don't know why.

@FRANCOSIBILLINI that's not my experience, I just install from osgeo4w, leave where the installer places it, and it works.

**Comment by m-kuhn** [comment]
@FRANCOSIBILLINI the QGIS server requires your webserver (apache/nginx) to be correctly configured. It's likely that some environment variables are not correctly set up (in particular the `PATH` variable, but there are a couple of others that need to be set up as well)

**Comment by FRANCOSIBILLINI** [comment]
Hi Matthias,
thanks for your replay. Do you mean that I have to add the Gdal2 bin path to DefaultInitEnv PATH (for fast cgi)?

after installed OSGeo4W64, inside the directory http.d there is the configuration file httpd_qgis-ltr.conf:

LoadModule fcgid_module modules/mod_fcgid.so

DefaultInitEnv O4W_QT_PREFIX "C:\OSGeo4W64/apps/Qt5"
DefaultInitEnv O4W_QT_BINARIES "C:\OSGeo4W64/apps/Qt5/bin"
DefaultInitEnv O4W_QT_PLUGINS "C:\OSGeo4W64/apps/Qt5/plugins"
DefaultInitEnv O4W_QT_LIBRARIES "C:\OSGeo4W64/apps/Qt5/lib"
DefaultInitEnv O4W_QT_TRANSLATIONS "C:\OSGeo4W64/apps/Qt5/translations"
DefaultInitEnv O4W_QT_HEADERS "C:\OSGeo4W64/apps/Qt5/include"
DefaultInitEnv O4W_QT_DOC "C:\OSGeo4W64/apps/Qt5/doc"

DefaultInitEnv GDAL_DATA "C:\OSGeo4W64\share\gdal"
DefaultInitEnv QGIS_AUTH_DB_DIR_PATH "C:\OSGeo4W64\apps\qgis-ltr\resources"

DefaultInitEnv PATH "C:\OSGeo4W64\apps\qt5\bin;C:\OSGeo4W64\bin;C:\OSGeo4W64\apps\qgis-ltr\bin;C:\OSGeo4W64\apps\grass\@grasspath@\bin;C:\OSGeo4W64\apps\grass\@grasspath@\lib;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem"
DefaultInitEnv QGIS_PREFIX_PATH "C:\OSGeo4W64\apps\qgis-ltr"
DefaultInitEnv QT_PLUGIN_PATH "C:\OSGeo4W64\apps\qgis-ltr\qtplugins;C:\OSGeo4W64\apps\qt5\plugins"
DefaultInitEnv TEMP "C:\Users\ADMINI~1\AppData\Local\Temp\1"
DefaultInitEnv PYTHONHOME "C:\OSGeo4W64\apps\Python37"
DefaultInitEnv PYTHONPATH "C:\OSGeo4W64\apps\Python37;C:\OSGeo4W64\apps\Python37\Scripts"

Alias /qgis-ltr/ C:\OSGeo4W64/apps/qgis-ltr/bin/

<Directory "C:\OSGeo4W64/apps/qgis-ltr/bin/">
    SetHandler fcgid-script
    Options ExecCGI
    Require all granted 
    #Order allow,deny
    #Allow from all
</Directory>


I copied  it into apache24\conf and added to import conf/httpd_qgis-ltr.conf
The system show missing gdal204.dll 
But it work copy it from C:\OSGeo4W64\apps\gdal2\bin top windows\system32

**Comment by m-kuhn** [comment]
Is your issue solved?

**Comment by FRANCOSIBILLINI** [comment]
Yes It works if I put  in 
DefaultInitEnv  PATH C:\OSGeo4W64\apps\gdal2\bin; BLA; BLA; BLA;
Many thanks

**Comment by jef-n** [comment]
Fxied in d21aa90a76e

**Comment by FRANCOSIBILLINI** [comment]
thanks!
