### ISSUE TITLE
QGIS Crash v.3.10.1

### ISSUE THREAD

**Issue by grantboxer** [qgis/QGIS#33500]
## User Feedback

QGIS Crash when opening large project

## Report Details

**Crash ID**: [72246f34bad335dfb38cbfc0ea183155711a17cb]('https://github.com/qgis/QGIS/search?q=72246f34bad335dfb38cbfc0ea183155711a17cb&type=Issues')

**Stack Trace**
<pre>
osgeo::proj::datum::Datum::conventionalRS :
osgeo::proj::datum::Datum::conventionalRS :
osgeo::proj::datum::Datum::conventionalRS :
OGRSpatialReference::~OGRSpatialReference :
OGRSpatialReference::operator= :
OGRGeomFieldDefn::~OGRGeomFieldDefn :
OGRPGCommonLayerSetType :
OGRFeatureDefn::~OGRFeatureDefn :
OGRPGCommonLayerSetType :
OGRPGCommonLayerSetType :
VRTDataset::GetSpatialRef :
VRTDataset::GetSpatialRef :
RegisterOGRSXF :
QgsOgrProviderUtils::GDALCloseWrapper qgsogrprovider.cpp:4129
QgsConnectionPoolGroup<QgsOgrConn * __ptr64>::onConnectionExpired qgsconnectionpool.h:227
QMetaObject::activate :
QTimer::timerEvent :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32Private::sendTimerEvent :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1598
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.0-A Coru�a
QGIS code revision: 6ffa89eb3e
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by nyalldawson** [comment]
This is a gdal issue, already fixed upstream
