### ISSUE TITLE
QgsCoordinateReferenceSystem.saveAsUserCrs broken (returns -1)

### ISSUE THREAD

**Issue by letmaik** [qgis/QGIS#33519]
**Describe the bug**
User-defined CRSs  cannot be created programmatically anymore from proj4 strings.

**How to Reproduce**
 Open the Python console an run:
```py
>>> from qgis.core import QgsCoordinateReferenceSystem
>>> proj4 = '+proj=stere +lat_ts=1.0 +lat_0=90 +lon_0=1.0 +x_0=0 +y_0=0 +datum=WGS84 +no_defs'
>>> crs = QgsCoordinateReferenceSystem.fromProj4(proj4)
>>> crs.isValid()
True
>>> crs.authid()
''
>>> srs_id = crs.saveAsUserCrs('test crs')
>>> srs_id
-1
```

**QGIS and OS versions**

QGIS version | 3.10.0-A Coruña | QGIS code revision | 6ffa89eb3e
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.2 | Running against GDAL/OGR | 3.0.2
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.2.1 | Running against PROJ | Rel. 6.2.1, November 1st, 2019
OS Version | Windows 10 (10.0)
Active python plugins | gis4wrf; db_manager; MetaSearch; processing

**Additional context**

This worked in the past, see https://github.com/qgis/QGIS/issues/25677.

**Comment by letmaik** [comment]
Possible duplicate of https://github.com/qgis/QGIS/issues/32866.

**Comment by alexbruy** [comment]
Already fixed in master.
