### ISSUE TITLE
raster merge  error in qgis 3.10

### ISSUE THREAD

**Issue by dufl07** [qgis/QGIS#33515]
It seems an error when I tried merge raster using 'Raster-Miscellaneous-Merge'.

**Comment by roya0045** [comment]
Too generic, provide more details on the error, and anything else that could be needed to reproduce that error.

**Comment by alexbruy** [comment]
There were similar tickets recently, this should be already fixed. Please try latest master or nightly build.

**Comment by agiudiceandrea** [comment]
It seems a duplicate of https://github.com/qgis/QGIS/issues/33386

**Comment by gioman** [comment]
Closed as duplicate.
