### ISSUE TITLE
PostGIS raster: estimated table metadata reads all table

### ISSUE THREAD

**Issue by Komzpa** [qgis/QGIS#33524]
I connect to PostGIS database that has raster in it. I do not intend to look at raster. Loading table list takes forever. "Use estimated table metadata" is checked.

I see qgis performing this query:

```SELECT 0, array_agg(DISTINCT 'RASTER:' || ST_SRID( "rast" )) FROM "public"."fb_population_raster"```

It looks like it should have a "LIMIT 100" clause or something like it. Otherwise it's a full scan over several gigs of data, not something I expect opening list of tables.

```
QGIS version | 3.10.1-A Coruña | QGIS code revision | ef24c526da
-- | -- | -- | --
Compiled against Qt | 5.12.4 | Running against Qt | 5.12.4
Compiled against GDAL/OGR | 2.4.2 | Running against GDAL/OGR | 2.4.2
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 (Ubuntu 11.5-1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.10.4
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Ubuntu 19.10
Active python plugins | db_manager; MetaSearch; processing

```

**Comment by elpaso** [comment]
duplicated by #33885
