### ISSUE TITLE
QGIS 3.10 : bug when forcing label to be displayed ?

### ISSUE THREAD

**Issue by simogeo** [qgis/QGIS#33527]
**Describe the bug**
Since v 3.10, it seems forcing label to be displayed is not working correctly 

![image](https://user-images.githubusercontent.com/154323/71477940-3fd6de00-27ed-11ea-8062-f554bbaafee5.png)

Enabling it does not change much ... all labels are not displayed in my map.

**How to Reproduce**

1. Add layer
2. Display labels - check the box to force labels displaying - even with conflict
3. It does not display as expected ... some labels are still missing

**QGIS and OS versions**

Version de QGIS | 3.10.1-A Coruña | Révision du code | ef24c526da
-- | -- | -- | --
Compilé avec Qt | 5.12.4 | Utilisant Qt | 5.12.4
Compilé avec GDAL/OGR | 2.4.2 | Utilisé avec GDAL/OGR | 2.4.2
Compilé avec GEOS | 3.7.2-CAPI-1.11.2 | Utilisé avec GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
Version du client PostgreSQL | 11.5 (Ubuntu 11.5-1) | Version de SpatiaLite | 4.3.0a
Version de QWT | 6.1.4 | Version de QScintilla2 | 2.10.4
Compilé avec PROJ | 5.2.0 | Fonctionne avec PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Ubuntu 19.10
Extensions Python actives | VectorBender; AnotherDXF2Shape; mask; Qgis2threejs; GeoCoding; vector_tiles_reader; ORStools; qconsolidate3; shapetools; Hqgis; DataPlotly; french_locator_filter; SRTM-Downloader; Beeline; OSMtools; QNEAT3; loadthemall; db_manager; MetaSearch; processing

**Comment by gioman** [comment]
@simogeo same project and data works ok on 3.4?

**Comment by simogeo** [comment]
this is a new project I just created the day I reported the bug (with QGIS 3.10.1). 
I can't tell about 3.4 or 3.8 behaviour, but till now I never observed (on others prpjects) strange behaviours when forcing label display.

**Comment by gioman** [comment]
> but till now I never observed (on others prpjects)

@simogeo 
so this problem is data/project dependent? if yes please attach a project+data that shows the issue.

**Comment by simogeo** [comment]
> but till now I never observed (on others projects) strange behaviours when forcing label display.

I mean using 3.4 or 3.8 version ... I will have some tries working with 3.10 coming weeks and let you know

**Comment by yodaanneaux** [comment]
Same behaviour noticed with Qgis 3.10.2 running on Windows 10 for the "MultilineString/Multicurve" geometry type. It works with points though.

**Comment by gioman** [comment]
> Same behaviour noticed with Qgis 3.10.2 running on Windows 10 for the "MultilineString/Multicurve" geometry type. It works with points though.

can you attach a minimal sample project (with data) that shows the issue?

**Comment by yodaanneaux** [comment]
[test.zip](https://github.com/qgis/QGIS/files/4180169/test.zip)
Although the problem occurs only with lines in this example, this problem takes place in professional projects I am working on (cannot share).

**Comment by gioman** [comment]
@yodaanneaux 

this is what I see

with that option enabled:

![Screenshot_20200210_120900](https://user-images.githubusercontent.com/1951107/74148808-36b79a00-4bfe-11ea-9f4d-d0aa8fc23e0a.png)


without:


![Screenshot_20200210_120914](https://user-images.githubusercontent.com/1951107/74148816-3ae3b780-4bfe-11ea-8aa5-542e0d5db5db.png)

**Comment by yodaanneaux** [comment]
What if you zoom more out? If i understand this option "Show all labels for this layer" well, then it should not be able to get red labels when I click on the "Toogles Display of Unplaced Labels". This is however what I get when try that out: 
![image](https://user-images.githubusercontent.com/50982709/74149880-bc3c4980-4c00-11ea-9752-e3f4a306b493.png)

**Comment by gioman** [comment]
> What if you zoom more out?

@yodaanneaux 

![Screenshot_20200210_124606](https://user-images.githubusercontent.com/1951107/74151102-54d3c900-4c03-11ea-8e61-215b8d65844b.png)

**Comment by yodaanneaux** [comment]
> 
> 
> > What if you zoom more out?
> 
> @yodaanneaux
> 
> ![Screenshot_20200210_124606](https://user-images.githubusercontent.com/1951107/74151102-54d3c900-4c03-11ea-8e61-215b8d65844b.png)

What if you click on "Toogles Display of Unplaced Labels" then?

**Comment by gioman** [comment]
> What if you click on "Toogles Display of Unplaced Labels" then? It seems ok for you, meaning that it could be a configuration problem.

it does what I would expect, it toggle on/off the labels that are not shown when the option "show all labels..." is not active.

**Comment by yodaanneaux** [comment]
> 
> 
> > What if you click on "Toogles Display of Unplaced Labels" then? It seems ok for you, meaning that it could be a configuration problem.
> 
> it does what I would expect, it toggle on/off the labels that are not shown when the option "show all labels..." is not active.

Ok here lies the difference then. When "Show all labels for this layer" and "Toogles Display of Unplaced Labels" are switched on, it nevertheless shows red labels (meaning unplaced labels) to me, which normally does not occur.

It appears that I am not the only one in this case (cf. @simogeo), where does it come from? Even if it is a small configuration thing, this is very annoying...

**Comment by simogeo** [comment]
indeed ! Same happened to me ... don't understand how / why ....

**Comment by gioman** [comment]
> Ok here lies the difference then. When "Show all labels for this layer" and "Toogles Display of Unplaced Labels" are switched on, it nevertheless shows red labels (meaning unplaced labels) to me, which normally does not occur.

@simogeo @yodaanneaux I'm on 3.10.2 on Linux, with a new QGIS profile.

**Comment by yodaanneaux** [comment]
> 
> 
> > Ok here lies the difference then. When "Show all labels for this layer" and "Toogles Display of Unplaced Labels" are switched on, it nevertheless shows red labels (meaning unplaced labels) to me, which normally does not occur.
> 
> @simogeo @yodaanneaux I'm on 3.10.2 on Linux, with a new QGIS profile.

As @simogeo is running Qgis on a Linux system, the problem does not seem to come from that. It would be good if more people report the problem.

**Comment by nyalldawson** [comment]
Just to clarify:

>  check the box to force labels displaying - even with conflict
> It does not display as expected ... some labels are still missing

This option does not force display of all labels (and never has). Rather it permits display of **overlapping** labels. There's still cases where labels will be missing, e.g. due to other constraints such as the "only display labels which fit in polygon" option OR if a line label is too long for the line feature and the "overrun distance" option isn't set to a sufficiently large value to permit this.

That's not a bug though. The option only applies to overlapping labels.

**Comment by gioman** [comment]
> That's not a bug though. The option only applies to overlapping labels.

@nyalldawson so this should be closed?

**Comment by nyalldawson** [comment]
I think so. But maybe the option needs to be renamed for clarity, or a tooltip added to assist?

**Comment by gioman** [comment]
@simogeo please file a new ticket (possibly as a feature request, not sure) asking to improve the name of the option or add a tooltip to add a short description of the same option.
