### ISSUE TITLE
QGIS3 ZoomToSelected() not working in Editor Script - works in Python Console but not the Python Editor

### ISSUE THREAD

**Issue by dza6549** [qgis/QGIS#33533]
Using 3.10.1-A Coruña on Windows 10

I am writing a Python Script in the Editor but iface.mapCanvas().zoomToSelected() does not appear to be working at all in the Editor.

iface.mapCanvas().zoomToSelected() - works fine in the Python Console

**Editor code - apparently does nothing**
```
selectid = [2]
poalayer.select(selectid)
iface.mapCanvas().zoomToSelected() # does nothing
iface.mapCanvas().refresh();
```
**Console - works as expected**
`iface.mapCanvas().zoomToSelected()`

Let me know if I can provide any further info or do a test.

**Comment by alexbruy** [comment]
Not reproducible both Windows and Linux.

**Comment by alexbruy** [comment]
Looks like local issue, probably data-related.
