### ISSUE TITLE
3.10.1 . issues with new group

### ISSUE THREAD

**Issue by MPN-stack** [qgis/QGIS#33545]
I have been adding layers to 3.10 and discovered the new feature of group to group layers together. This when pressed seems to pop up an empty menu before adding a paperclip group to the list which you can name . Creating several of these stops and you cannot create any more without saving project and closing QGIS. I then found that QGIS reported a dll error and would not restart without it being removed and installed in its entirety.

It is easy to reproduce just start a big project with more than 300 layers and try and add a group. You will come across this very quickly . It is annoying but can be solved by restarting QGIS
**How to Reproduce**

**QGIS and OS versions**
Windows 10 

The current released version of QGIS is 3.10.1. 
We are working on 3.11-Master. It will go into feature freeze on 2020-01-17 12:00:00 UTC and be released as 3.12 on 2020-02-21 12:00:00 UTC. 
Details on changes can be found on github at https://github.com/qgis/QGIS/commits/master. 
**Additional context**

**Comment by MPN-stack** [comment]
I think this issue could be because the upgrade did not remove all the 3.10 code when it installed 3.10.1 . The dll error is below. I have found 3.10 references under C:\Program Files deleted them and reinstalled this morning as i met this same error  I am hoping things will sort themselves out now. This is fabulous software thank you. 

![9b11d91a3564ea08d241402dc1fc37d8](https://user-images.githubusercontent.com/54211372/71555188-69a72500-29e6-11ea-8ef0-672c2e8bed54.png)

**Comment by gioman** [comment]
@MPN-stack would you mind add a screencast to show the issue? the description is not clear to me. Thanks.

**Comment by MPN-stack** [comment]
hi Gioman its above your post . I think it was the installation software not clearing 3.10 . I don't have the problem with groups anymore so it must be because it did not clear out the previous installation 3.10 when i installed 3.10.1 . I hope this helps. Its great software thanks for your reply.

**Comment by roya0045** [comment]
If the issue resolved itself please close this issue.
