### ISSUE TITLE
QGIS 3.10.1: all layers appear as temporary layers

### ISSUE THREAD

**Issue by redneb** [qgis/QGIS#33546]
After upgrading to 3.10.1 (from 3.10.0), all (geopackage) layers in my old projects are shown by qgis as being tempory/scratch layers, i.e. there is a "chip" icon next to them and there is an item in their context menu that says "Make permanent...". Also, when I close the project, I get the standard prompt "This project includes one or more temporary layers..." even though there are no temporary layers in the project. Despite that, when I edit or otherwise work with these layers, everything works exactly as if the layers were permanent.

**Comment by alexbruy** [comment]
Probably your layers are located in the user or system temporary folder.

**Comment by redneb** [comment]
Wow, you are right! I would have never guessed that.

**Comment by nyalldawson** [comment]
Woohoo! The new warning has saved the day at least once :smile:
