### ISSUE TITLE
Regular problem - update to Ubuntu fails, demands partial upgrade - and insists on deleting Qgis

### ISSUE THREAD

**Issue by Redheart64** [qgis/QGIS#33549]
OS: Ubuntu 18.04LTS
QGis 3.4

Problem: Ubuntu stops updating and insists on a partial upgrade when I try to manually update the OS.  When you try the partial upgrade, the software insists on removing QGis.  I USE QGis a lot in my schoolwork, fieldwork, and dissertation project!  This problem happens at least once a year, if not more often - and it's been a problem off and on for years.  I've had to live without updates for months at a time until something changes and I either upgrade QGis (and that fixes the problem with updates), or when Ubuntu makes a change.

I searched for anything similar, but without luck.  I may have not used the right keywords in the search.  I'm good at research, but terrible at googling.

I live in a hacker-dangerous environment and don't like going without security updates (we were once hacked by someone who came in via our cable internet - physical access or wireless access is blocked), and I don't want to drop QGis - especially while in the middle of a project!

I don't know what else I can add to help diagnose this problem.

BTW: QGis often crashes when I shut it down (properly) - close the project, and then quit the software.  "X"ing out also usually crashes.  I don't know if this is a symptom or not.

**Comment by gioman** [comment]
@Redheart64 I don't think that this is a general issue or that relevant anymore, anyway.
