### ISSUE TITLE
Coordinate capture: update coordinates when CRS to use for coordinate display is changed

### ISSUE THREAD

**Issue by JBosm** [qgis/QGIS#33555]
Hello,
when changing the CRS to use for coordinate display, the coordinates in the display box are not corrected. It would seem better if they were updated to the new CRS.
![image](https://user-images.githubusercontent.com/5849171/71579829-8d5d8e80-2afe-11ea-900d-bf1485c9e703.png)

**Comment by gioman** [comment]
@JBosm how this is different from https://github.com/qgis/QGIS/issues/33554 ?

**Comment by JBosm** [comment]
@gioman The two tickets are different, I'm sorry if I was not clear enough (english is not my mother tongue, feel free to ask again if still not clear). 
This one, 33555 is that when changing CRS for coordinate capture, the coordinates in the display are not immediately updated, so you have to click once again (on the map) to get new coordinates, this time with the right CRS. But when clicking, the coordinates will never be exactly the same, so updating when changing the CRS would seem cleaner and more logical to me. 
#33554  is about loosing the chosen CRS when quitting QGIS. On opening QGIS, the CRS for coordinate capture will always be 4326, even if changed earlier. Not sure if the CRS for coordinate capture should be saved in the project or in QGIS preferences.

**Comment by nyalldawson** [comment]
No longer an issue with the merged "copy coordinates" approach
