### ISSUE TITLE
Coordinate capture: save CRS to use for coordinate display

### ISSUE THREAD

**Issue by JBosm** [qgis/QGIS#33554]
Hello,
when closing and re-opening QGIS, the CRS of the first coordinates is always 4326, even when changed. Would it be possible/desirable to save the last CRS used for coordinates display?
![image](https://user-images.githubusercontent.com/5849171/71579719-20e28f80-2afe-11ea-8232-9faf4821c17d.png)

**Comment by nyalldawson** [comment]
No longer an issue with the merged "copy coordinates" approach
