### ISSUE TITLE
QGIS is crashing frequently.

### ISSUE THREAD

**Issue by rishieco** [qgis/QGIS#33558]
## User Feedback

I was creating a map layout and had done the job. The crash happened after I pressed the save project button, followed by close. 

## Report Details

*Crash ID*: 1087041d7e6e99f1cf513cf6fae2c163b049f9b8

*Stack Trace*
<pre>
osgeo::proj::datum::Datum::conventionalRS :
osgeo::proj::datum::Datum::conventionalRS :
osgeo::proj::datum::Datum::conventionalRS :
OGRSpatialReference::~OGRSpatialReference :
OGRSpatialReference::operator= :
OGRGeomFieldDefn::~OGRGeomFieldDefn :
SHPWriteObject :
OGRFeatureDefn::~OGRFeatureDefn :
OGRFeatureDefn::~OGRFeatureDefn :
SHPWriteObject :
DBFWriteTuple :
OGREditableLayer::Translate :
CPLStringList::FindString :
OGREnvelope::OGREnvelope :
CPLStringList::operator char const * __ptr64 const * __ptr64 :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.4.13-Madeira
QGIS code revision: 567300ccf1
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
@rishieco please update to 3.4.14 and try again.

**Comment by nyalldawson** [comment]
This was a gdal issue. It's fixed now
