### ISSUE TITLE
#BUG , Scale resize from toolbox, not affine

### ISSUE THREAD

**Issue by MPN-stack** [qgis/QGIS#33550]
Hi I wonder if we can have a new feature that allows you to select the layer or feature  or more importantly group and use a tool box button to drag its size like in other paint programs ? The Affine (rotation , Scale ) is good but practically difficult to use could this not be implement into the tool box. It would make things much more easier to do by dragging to position  extending one side?

Is it also possible to be able to select all your features and set the ownership publisher details please even by group to set everything?

Thanks for looking

**Comment by MPN-stack** [comment]
**#BUG**
I think this might be a bug request now . i tried to use the v.transformation  under  GRASS to change scale y to .5 and height to 1.5 it ran the transformation creating a transformed layer above the original . However no visable item was created  as detailed here https://gis.stackexchange.com/questions/63000/how-to-resize-shapefile-features-proportionally-in-qgis

This seems a ridiculous of amount of effort to do what can be done n a paint program like GIMP 2

**This is the log**
QGIS version: 3.10.1-A Coruña
QGIS code revision: ef24c526da
Qt version: 5.11.2
GDAL version: 3.0.2
GEOS version: 3.8.0-CAPI-1.13.1 
PROJ version: Rel. 6.2.1, November 1st, 2019
Processing algorithm…
Algorithm 'v.transform' starting…
Input parameters:
{ 'GRASS_MIN_AREA_PARAMETER' : 0.0001, 'GRASS_OUTPUT_TYPE_PARAMETER' : 0, 'GRASS_REGION_PARAMETER' : None, 'GRASS_SNAP_TOLERANCE_PARAMETER' : -1, 'GRASS_VECTOR_DSCO' : '', 'GRASS_VECTOR_EXPORT_NOCAT' : False, 'GRASS_VECTOR_LCO' : '', 'columns' : '', 'input' : 'C:/Users/BLAGMOSWHAT/Documents/Json TPO Shapes/TPO_013-W01.geojson', 'output' : 'TEMPORARY_OUTPUT', 'xscale' : 1, 'xshift' : 0, 'yscale' : 0.5, 'yshift' : 0, 'zrotation' : 0, 'zscale' : 1.5, 'zshift' : 0 }

g.proj -c proj4="+proj=longlat +datum=WGS84 +no_defs"
v.in.ogr min_area=0.0001 snap=-1.0 input="C:\Users\BLAGMOSWHAT\Documents\Json TPO Shapes\TPO_013-W01.geojson" output="vector_5e0920eb8dee64" --overwrite -o
g.region n=50.87505345 s=50.86802493 e=0.53917454 w=0.52936614
v.transform input=vector_5e0920eb8dee64 xshift=0 yshift=0 zshift=0 xscale=1 yscale=0.5 zscale=1.5 zrotation=0 output=output717e0f3a30434137898fbef92508f546 --overwrite
v.out.ogr type="auto" input="output717e0f3a30434137898fbef92508f546" output="C:\Users\BLAGMOSWHAT\AppData\Local\Temp\processing_0f66a0a3f873467293bbacd609f7505c\ac65695a58da4e4abc0e3bf702da565b\output.gpkg" format="GPKG" --overwrite
Starting GRASS GIS...
WARNING: Concurrent mapset locking is not supported on Windows
Cleaning up temporary files...
Executing <C:\Users\BLAGMOSWHAT\AppData\Local\Temp\processing_0f66a0a3f873467293bbacd609f7505c\grassdata\grass_batch_job.cmd> ...
C:\Users\BLAGMOSWHAT\Documents>chcp 1252 1>NUL
C:\Users\BLAGMOSWHAT\Documents>g.proj -c proj4="+proj=longlat +datum=WGS84 +no_defs"
Default region was updated to the new projection, but if you have multiple mapsets `g.region -d` should be run in each to update the region from the default
Projection information updated
C:\Users\BLAGMOSWHAT\Documents>v.in.ogr min_area=0.0001 snap=-1.0 input="C:\Users\BLAGMOSWHAT\Documents\Json TPO Shapes\TPO_013-W01.geojson" output="vector_5e0920eb8dee64" --overwrite -o
Over-riding projection check
Check if OGR layer <TPO_013-W01> contains polygons...
0..100
Creating attribute table for layer <TPO_013-W01>...
Importing 1 features (OGR layer <TPO_013-W01>)...
0..100
-----------------------------------------------------
Registering primitives...
-----------------------------------------------------
Cleaning polygons
-----------------------------------------------------
Breaking polygons...
Breaking polygons (pass 1: select break points)...
100
Breaking polygons (pass 2: break at selected points)...
100
-----------------------------------------------------
Removing duplicates...
100
-----------------------------------------------------
Breaking boundaries...
0..100
-----------------------------------------------------
Removing duplicates...
100
-----------------------------------------------------
Cleaning boundaries at nodes...
100
-----------------------------------------------------
Merging boundaries...
100
-----------------------------------------------------
Removing dangles...
100
-----------------------------------------------------
Building areas...
0..100
-----------------------------------------------------
Removing bridges...
100
-----------------------------------------------------
Registering primitives...
Building areas...
0..100
Attaching islands...
0..100
-----------------------------------------------------
Finding centroids for OGR layer <TPO_013-W01>...
0..100
-----------------------------------------------------
Writing centroids...
100
-----------------------------------------------------
1 input polygons
Total area: 157129 (1 areas)
-----------------------------------------------------
Copying features...
50..100
Building topology for vector map <vector_5e0920eb8dee64@PERMANENT>...
Registering primitives...
Building areas...
0..100
Attaching islands...
0..100
Attaching centroids...
0..100
C:\Users\BLAGMOSWHAT\Documents>g.region n=50.87505345 s=50.86802493 e=0.53917454 w=0.52936614
C:\Users\BLAGMOSWHAT\Documents>v.transform input=vector_5e0920eb8dee64 xshift=0 yshift=0 zshift=0 xscale=1 yscale=0.5 zscale=1.5 zrotation=0 output=output717e0f3a30434137898fbef92508f546 --overwrite
Transforming features...
0..Copying attributes...
Building topology for vector map <output717e0f3a30434137898fbef92508f546@PERMANENT>...
Registering primitives...
Building areas...
0..100
Attaching islands...
0..100
Attaching centroids...
0..100
v.transform complete.
C:\Users\BLAGMOSWHAT\Documents>v.out.ogr type="auto" input="output717e0f3a30434137898fbef92508f546" output="C:\Users\BLAGMOSWHAT\AppData\Local\Temp\processing_0f66a0a3f873467293bbacd609f7505c\ac65695a58da4e4abc0e3bf702da565b\output.gpkg" format="GPKG" --overwrite
Exporting 1 area (may take some time)...
100
v.out.ogr complete. 1 feature (Polygon type) written to <output717e0f3a30434137898fbef92508f546> (GPKG format).
C:\Users\BLAGMOSWHAT\Documents>exit
Execution of <C:\Users\BLAGMOSWHAT\AppData\Local\Temp\processing_0f66a0a3f873467293bbacd609f7505c\grassdata\grass_batch_job.cmd> finished.
Cleaning up default sqlite database ...
Cleaning up temporary files...
Execution completed in 7.68 seconds
Results:
{'output': <QgsProcessingOutputLayerDefinition {'sink':TEMPORARY_OUTPUT, 'createOptions': {'fileEncoding': 'System'}}>}

Loading resulting layers
Algorithm 'v.transform' finished


**Output**
![c397af3414a8d687461d6c7be26402a2](https://user-images.githubusercontent.com/54211372/71563423-6ba3cf00-2a4c-11ea-8d90-b4c57ae1a903.jpg)

**software**

The current released version of QGIS is 3.10.1. 
We are working on 3.11-Master. It will go into feature freeze on 2020-01-17 12:00:00 UTC and be released as 3.12 on 2020-02-21 12:00:00 UTC. 
Details on changes can be found on github at https://github.com/qgis/QGIS/commits/master.

**Comment by gioman** [comment]
> his is very unhelpful and i can quite understand why you would re-invent the wheel

@MPN-stack actually we integrare GRASS and SAGA and GDAL, etc. in QGIS exactly because we don't want to re-invent the wheel. If this GRASS tool does not produce the expected results it can be for several reasons. I suggest to check directly in GRASS, then we can compare results.

**Comment by MPN-stack** [comment]
As you saw the item above {image] was moved off world to nowhere a really unhelpful transformation sorry but its a great product and being brought down in flames. I am now expecting to go back to the drawing board with this feature as i do not know why it imported out of proportion. I am told this is just something QGIS does! I am importing from GEO Referencer which is great producing GEOJSON text files but the shape shown in QGIS 3.10.1 seems out of proportion . I expected GRASS v.transform  to transform and overlay onto of existing item so i could see the difference . Am i doing something wrong ? Please see my image above  I added it while you was commenting thank you for your response. I can overlay the image it was taken from and clearly see it is not representing the co-ordinates . I am not sure why.

Thanks for looking

**Comment by gioman** [comment]
See my previous comment: if there are any doubts about how a GRASS tool is implemented in QGIS it must be first checked directly in GRASS. It may be a GRASS issue, or it may be a QGIS issue about how we expose and process the GRASS tool parameters. Once you have clarified if in GRASS you get the expected results or not leave a comment here.

**Comment by MPN-stack** [comment]
Oh sorry that is not very helpful. I would have thought you would have tested it before IMPLEMENTATION is that not normal in SOFTWARE DEVELOPMENT? 

Or do you just bolt something on to brilliant software untested? 

I only tried this option as i could not find a way to do this in QGIS can you explain how to change the scale of an item feature in QGIS please or direct me to a reading resource to do this . Thank you.

**Comment by gioman** [comment]
Also have a look at 3rd party plugins like https://github.com/olivierdalang/VectorBender

> Oh sorry that is not very helpful. I would have thought you would have tested it before IMPLEMENTATION is that not normal in SOFTWARE DEVELOPMENT?

you are speaking about code (the GRASS tool code) that is not part of QGIS's code. Anyway as I said it can be merely a problem on how we expose or process the GRASS tools parameters, for this reason you must test the tool in its original software.

**Comment by MPN-stack** [comment]
Thanks, I have that loaded but it needs two pairs of points  which I presume are an outline unlike my GEOJSON( below) which are polyon based on co-ordinates. I'm really to busy to test GRASS for you I am just trying to find a workaround

**i.e**
{"type":"FeatureCollection","features":[{"type":"Feature","id":"9b6823bc-26b5-4cbc-b247-7a881cb70136","geometry":{"type":"Polygon","coordinates":[[[0.53385245,50.87505345],[0.53394556,50.87497737],[0.53394098,50.87496388],[0.53401272,50.87492343],[0.53396082,50.8749215],[0.5339593,50.87490032],[0.53401882,50.87487238],[0.5341043,50.87477896],[0.53423251,50.8746865],[0.53438972,50.87458537],[0.53442765,50.87454295],[0.53447733,50.87448222],[0.53445249,50.87447438],[0.53445559,50.87444989],[0.53444472,50.87442539],[0.53447422,50.87437151],[0.53455961,50.87434898],[0.53455185,50.87431469],[0.53451459,50.87430685],[0.53454719,50.87426571],[0.5345503,50.87419909],[0.53454775,50.87400989],[0.53464442,50.87393965],[0.53461512,50.87384353],[0.53460066,50.87379711],[0.5346746,50.8737693],[0.53467175,50.87372085],[0.53464474,50.87371546],[0.53463621,50.87369124],[0.53467175,50.87366432],[0.53456227,50.87363919],[0.5346618,50.87356472],[0.53453525,50.87352345],[0.53459071,50.87347589],[0.53459569,50.87345727],[0.53453708,50.87343736],[0.53454008,50.87341459],[0.53456263,50.87338993],[0.53456413,50.87336338],[0.53446644,50.87333777],[0.53443037,50.87331027],[0.53442736,50.87328466],[0.53438227,50.87326],[0.53438377,50.87321447],[0.53437948,50.87315589],[0.53431779,50.87316943],[0.5343245,50.87312796],[0.53428829,50.87309834],[0.53419307,50.8730865],[0.53407103,50.87308903],[0.53408176,50.87304672],[0.53399593,50.87304587],[0.53397715,50.87299002],[0.53390742,50.87298833],[0.53387255,50.87297055],[0.53388864,50.8729257],[0.53383514,50.87291208],[0.53376272,50.87295101],[0.53365812,50.87294931],[0.53361252,50.87291715],[0.5335106,50.872929],[0.53347841,50.87288669],[0.53337112,50.87289177],[0.53319946,50.87284437],[0.53319141,50.87279698],[0.53290442,50.8727936],[0.53278908,50.87275974],[0.53269252,50.87277159],[0.53261206,50.87277159],[0.53255305,50.87273097],[0.53249619,50.87271506],[0.53250533,50.87265972],[0.53242129,50.87264127],[0.53239388,50.87259516],[0.53234638,50.87257902],[0.53229157,50.87257902],[0.532243,50.87258233],[0.53221268,50.87254258],[0.53223134,50.87248371],[0.53230132,50.87235859],[0.53201675,50.87241305],[0.53199809,50.87237625],[0.53187679,50.87237037],[0.53182781,50.87236889],[0.53184181,50.87232915],[0.53182315,50.87228646],[0.53185347,50.87223789],[0.53174151,50.87221581],[0.53173068,50.87217504],[0.53176367,50.87211779],[0.53157123,50.87211606],[0.53161247,50.87207442],[0.53163171,50.87202932],[0.53158223,50.87198074],[0.53154374,50.87196339],[0.53160697,50.87189573],[0.53145302,50.87191135],[0.53154099,50.8718246],[0.53142003,50.87184022],[0.53144752,50.87178817],[0.53141865,50.87178644],[0.53146264,50.87172745],[0.53137604,50.87175087],[0.5313623,50.87173179],[0.53136745,50.87169956],[0.53135067,50.87166357],[0.53143119,50.87160534],[0.53126009,50.87162334],[0.53124331,50.8716064],[0.53115944,50.87160429],[0.53113699,50.87158626],[0.53113699,50.87152672],[0.53091128,50.87157225],[0.53097233,50.87153022],[0.53090573,50.87152439],[0.53092793,50.8715022],[0.53090203,50.87148819],[0.53093718,50.87145784],[0.53080397,50.87148819],[0.53073552,50.87145784],[0.53063931,50.87144266],[0.53059676,50.87147301],[0.5305061,50.87147535],[0.53051535,50.87144733],[0.53036549,50.87144266],[0.53042655,50.87140646],[0.53036179,50.8714053],[0.53031554,50.87139829],[0.53027299,50.87140296],[0.53023784,50.87137961],[0.53005456,50.87142717],[0.52986868,50.8714402],[0.52969657,50.87143369],[0.52959675,50.87145106],[0.52962429,50.87140979],[0.52957954,50.87138264],[0.52956921,50.87135114],[0.52952963,50.87133811],[0.52940055,50.87135766],[0.52943325,50.87132073],[0.52943325,50.87128597],[0.52940915,50.87126425],[0.52941604,50.87123058],[0.52936614,50.87116693],[0.52937404,50.87107674],[0.52964174,50.87082116],[0.530279,50.87002694],[0.53044741,50.86998519],[0.53059176,50.86989788],[0.53072408,50.86986752],[0.53084438,50.86986372],[0.53082032,50.86997759],[0.53085458,50.86999756],[0.53045198,50.8704171],[0.53031859,50.87058654],[0.53040576,50.87058654],[0.53053049,50.87056962],[0.53067667,50.87055523],[0.53079334,50.87056792],[0.53088588,50.87057977],[0.53102267,50.87055777],[0.53118763,50.87052222],[0.53133917,50.87049429],[0.53147295,50.87049356],[0.53155394,50.8705036],[0.53165228,50.87049539],[0.53180414,50.87047531],[0.53190104,50.87044793],[0.53200372,50.87044427],[0.53220765,50.87040138],[0.5323812,50.87039408],[0.53255908,50.8703886],[0.53272974,50.87039955],[0.53281808,50.87040902],[0.53291022,50.87039739],[0.53321276,50.87041386],[0.53340165,50.87040902],[0.53356444,50.87040514],[0.53366886,50.87040902],[0.53376869,50.87038963],[0.53414531,50.8702745],[0.53464755,50.87005884],[0.53548635,50.86961445],[0.53586433,50.86942492],[0.53619007,50.8692377],[0.5363836,50.86907369],[0.53654948,50.86891317],[0.53669878,50.86883291],[0.53743972,50.86853629],[0.5378102,50.86838624],[0.53844024,50.86802493],[0.53873764,50.86830993],[0.5384072,50.86847677],[0.53847328,50.86866445],[0.53842324,50.86872706],[0.53838895,50.86876313],[0.53841467,50.86882446],[0.53840895,50.86893449],[0.53840324,50.8690355],[0.53853757,50.86912929],[0.53808884,50.86926097],[0.5380374,50.86932229],[0.53799488,50.8693637],[0.53804414,50.86936919],[0.53804559,50.86942588],[0.53812093,50.86943776],[0.53804414,50.86949994],[0.53799923,50.8695484],[0.53799527,50.8696017],[0.537897,50.86968273],[0.53806025,50.86968681],[0.53801197,50.86975452],[0.53816619,50.86974351],[0.5381854,50.8697664],[0.53824039,50.86977655],[0.53828062,50.86979179],[0.53839596,50.86980025],[0.53844558,50.8698231],[0.5384952,50.86986881],[0.53854252,50.86988271],[0.53857202,50.86989625],[0.53857739,50.86991656],[0.53856264,50.86993941],[0.53860957,50.86994787],[0.53876112,50.8699301],[0.53904141,50.86989032],[0.5391326,50.8698734],[0.53917454,50.86995147],[0.53866052,50.87025783],[0.53857485,50.87018575],[0.53849489,50.87011727],[0.53840922,50.87003076],[0.53834068,50.86993705],[0.53824359,50.86990461],[0.53805511,50.86986857],[0.53780953,50.86981811],[0.53762676,50.86983973],[0.53738688,50.86991542],[0.53720412,50.87000193],[0.5369414,50.87005239],[0.53667296,50.87011727],[0.53660443,50.87019296],[0.53661109,50.8702473],[0.53662316,50.87030316],[0.53671435,50.87033786],[0.53685785,50.87037425],[0.53700537,50.87044619],[0.53710193,50.87049697],[0.53714753,50.87058753],[0.53717301,50.87066031],[0.53725974,50.87076362],[0.53730747,50.87084395],[0.536325,50.87136104],[0.53621761,50.87131334],[0.53618977,50.87125059],[0.53614203,50.8711778],[0.53605453,50.87111002],[0.53579201,50.87097197],[0.53446761,50.87169156],[0.53469913,50.87177922],[0.53487111,50.87187106],[0.53656451,50.87263913],[0.53652973,50.87267313],[0.53650961,50.87271883],[0.5364667,50.87275945],[0.53640501,50.8728043],[0.53632724,50.8728689],[0.53631828,50.87295374],[0.53625778,50.87305554],[0.53617936,50.87317856],[0.53610093,50.87324643],[0.53600458,50.87330299],[0.53587461,50.87346277],[0.53576079,50.87364879],[0.53571161,50.87376258],[0.53570459,50.8738808],[0.53575377,50.87395026],[0.53582636,50.87395912],[0.53585915,50.87398277],[0.53597624,50.8740005],[0.53601605,50.87406552],[0.5360261,50.87411385],[0.53600598,50.874146],[0.53600732,50.87424163],[0.53591076,50.87437534],[0.53587589,50.87439311],[0.53588126,50.8744312],[0.53582505,50.87448186],[0.53552517,50.87466541],[0.53537224,50.87469664],[0.53531976,50.87470515],[0.53517282,50.87474867],[0.53494424,50.87482567],[0.53413292,50.87499602],[0.53406073,50.87502699],[0.53396545,50.87504339],[0.53385245,50.87505345]]]},"properties":{"name":"W1"}}]}

**Comment by SrNetoChan** [comment]
@MPN-stack I think you are seeing the wrong picture. And you are being a bit impolite. @gioman is trying to help you to solve the problem. If you are too busy for trying something out, you shouldn't be asking others to spend time working for you.

**Comment by nyalldawson** [comment]
Yeah, I was pretty close to donating some time today to make an optimised qgis native version of this tool, but now my motivation has been killed by the ungrateful nature of this thread.

I'll probably still do it for myself, but I'm reluctant to reward such uncooperative behaviour...

**Comment by MPN-stack** [comment]
Well I was told by one of my colleagues that I could create and edit in QGIS it seems you can only change points, move items and rotate NOT re-scale. This is clearly not a full editing sweet . 

I don't think I am being a bit impolite or unfair. I have more than eight  weeks invested in QGIS which is a great product as I said earlier and does some amazing things. 

@gioman told me it was GRASS problems  not QGIS  which I understood . 

 @nyalldawson I am just frustrated that I have to go back and forth between two products as QGIS is currently only  a storage map solution for me then as I will have to go back and forth do my editing of features elsewhere. Sorry its just an opinion from using your product and I hoped valuable feedback from a user. which you now seem to think is impolite even though I credited to you you that it was a great product . This means more work. I asked if there was a solution or if this was fixed in beta I don't think I had an answer. I don't currently have beta installed as I had trouble installing second release candidate as the installer did not remove all of 3.10 creating odd errors which are noted on here to help others. I am reluctant to beta test as need this report written attached to these maps and don't know if beta will have same problem.

When I searched for an answer the only option that came up was GRASS which didn't seem to work on this feature . sending it off world.  I tested it providing you both screen images and code . You seem to want more time from me to solve this for you  . I am sorry I don't have enough to do what I am currently doing . I am not an expert of QGIS but am learning as its a huge program .

I note you are pulling this thread without answer have a great day.

**Comment by gioman** [comment]
> I note you are pulling this thread without answer have a great day.

@MPN-stack maybe you haven't noticed but @nyalldawson just implemented the feature you requested.

**Comment by MPN-stack** [comment]
@geoman, Sorry no I had not noticed sorry thanks for pointing this out  :) That is totally brilliant thanks   @nyalldawson I like the new groups they are much easier to keep track of everything. I hope you can add the edit moved tasks to these groups  too it would be great . Have a great day.

**Comment by SrNetoChan** [comment]
@MPN-stack it's not OUR product, it's YOURS too! Since QGIS is open source we are all responsible for its improvement.

I am still intrigued by what you want to achieve. Can you please provide some sample data? Is the data not aligned with the basemap and you are trying to force it there?

**Comment by gabriel-de-luca** [comment]
@MPN-stack v.transform works fine. It performs an affine transformation from the layer origin of coordinates.  
If a polygon vertex has _y_ coordinate = 50  and you scale it by 0.5, it will be in _y_ coordinate = 25.  
If the layer is defined in a geodetic coordinate reference system in which _y_ coordinates are latitude degrees, the polygon will go to latitude 25 degrees.  
If you want it scaled from a custom point, probably the centroid of the polygon geometry, you need to include a translation in the affine transformation, from the scaled to the original centroid coordinates.  

Also, the implementation of native algorithm with full support for Z and M coordinates, with per feature transformation proposed by @nyalldawson is welcomed.
