### ISSUE TITLE
no such function: InitSpatialMetadata

### ISSUE THREAD

**Issue by gdefilippis** [qgis/QGIS#33568]
Hi! I am porting a QGIS plugin to QGIS3.

I get a problem when I try to create a new SpatiaLite DB, in particular when I initialize spatial metadata (GEOMETRY_COLUMNS and SPATIAL_REF_SYS).

My code is:

import sqlite3
con = sqlite3.connect(dbname)
con.enable_load_extension(True)
cur = con.cursor()
cur.execute("PRAGMA foreign_keys = ON")
cur.execute("SELECT InitSpatialMetaData(1);")

Here I get the error "no such function: InitSpatialMetadata"

My sqlite3 version is 3.29.0

Any idea about that?

Thank you for your support!

Giovanna

**Comment by gioman** [comment]
@gdefilippis if is question rather than a bug report you should ask in the users/developers mailing list or the QGIS irc channel or gis.stackexchange
