### ISSUE TITLE
Processing parameter filename needs quoting: Sieve

### ISSUE THREAD

**Issue by Houska1** [qgis/QGIS#33562]
QGIS 3.10.1, OSGeo4W Windows install.

In the Sieve processing algorithm, QGIS needs to quote (" " and likely Windows path \ to \\ ) the mask parameter in the GDAL/OGR console call. Without it, leads to a processing error if the pathname of the mask layer has spaces, etc.  The input and output filenames are quoted properly. See problematic console call line generated in the attached picture. Thanks!

![image](https://user-images.githubusercontent.com/48919900/71603957-5d79af80-2b2d-11ea-92c7-a7e768b4e19c.png)

**Comment by Houska1** [comment]
Molto grazie, @agiudiceandrea !

**Comment by agiudiceandrea** [comment]
Hi @Houska1, you can test and use the patch right away, manually modifying the file sieve.py (usually in \python\plugins\processing\algs\gdal\\) as in https://github.com/qgis/QGIS/pull/33567/files.
