### ISSUE TITLE
QGIS 3.10.1 crashes when exporting raster to MBTiles on too many cores

### ISSUE THREAD

**Issue by supraopticus** [qgis/QGIS#33573]
QGIS version | 3.10.1-A Coruña | QGIS code revision | 1e6b1a3eda
-- | -- | -- | --
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.28.0 | Running against SQLite | 3.28.0
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS 10.15
Active python plugins | processing; db_manager; MetaSearch

Toolbox -> Raster Tools -> Generate XYZ Tiles (MBTiles) will crash if using too many threads.  I'm running an 8 physical core i9.  It works fine with 7 threads (I didn't try all 8) but 12 or 16 crashes very quickly.

Log File: 
QGIS version: 3.10.1-A Coruña
QGIS code revision: 1e6b1a3eda
Qt version: 5.12.3
GDAL version: 2.4.1
GEOS version: 3.7.2-CAPI-1.11.2 b55d2125
PROJ version: Rel. 5.2.0, September 15th, 2018
Processing algorithm…
Algorithm 'Generate XYZ tiles (MBTiles)' starting…
Input parameters:
{ 'BACKGROUND_COLOR' : QColor(0, 0, 0, 0), 'DPI' : 96, 'EXTENT' : '-14010569.60360237,-12342599.60360237,4574283.589267357,6439083.589267357 [USER:100000]', 'METATILESIZE' : 4, 'OUTPUT_FILE' : '/Downloads/DEM/srtm1SlopeNWTiles.mbtiles', 'QUALITY' : 75, 'TILE_FORMAT' : 0, 'ZOOM_MAX' : 15, 'ZOOM_MIN' : 13 }

Using 7 CPU Threads:
Pushing all tiles at once: 171561 tiles.

**Comment by roya0045** [comment]
possibly related to #32471 , please wait for next release or pleas test master to see if the fix solves your issue.

**Comment by gioman** [comment]
I would day duplicate, closing?
