### ISSUE TITLE
Cannot open new install on Mac (Catalina 10.15)

### ISSUE THREAD

**Issue by christinamc** [qgis/QGIS#33577]
Hello

I am a student (Enviro Sci and Geography) and I want to learn QGIS to be able to use it independently for projects and some contract work. 
I have just downloaded it today (using Mac OS Catalina 10.15) and neither the long term stable, or newer versions will allow me to open the software. The attached screenshot appears (after downloading, and installing to Applications). 

I look forward to any advice or assistance.
Thank you
Christina

<img width="416" alt="Screen Shot 2020-01-02 at 3 54 36 PM" src="https://user-images.githubusercontent.com/59427352/71650436-b4c08f80-2d7a-11ea-9cf8-179a01a6f7bc.png">

**Comment by christinamc** [comment]
Oops - managed to figure out a work around!

**Comment by joehumpert** [comment]
can you explain the workaround to me? i'm experiencing the same issue.

**Comment by roya0045** [comment]
@joehumpert  see if https://github.com/qgis/QGIS/issues/34018#issuecomment-578186707 helps

**Comment by joehumpert** [comment]
@roya0045 that did it, thank you!
