### ISSUE TITLE
Random Marker Fill crashes on multipolygons

### ISSUE THREAD

**Issue by raymondnijssen** [qgis/QGIS#33584]
**Describe the bug**
When a Random Marker fill is applied to a polygon layer containing multi polygons, QGIS crashes on zooming in.

**How to Reproduce**

1. Create a projected multipolygon memory layer (I used epsg 28992)
2. Draw a multipolygon
3. Set symbology to Random Marker (10 red dots appear)
4. Zoom in out with mouse wheel and qgis crashes

If you do the same with a single polygon, it just works.

**QGIS and OS versions**

QGIS version | 3.11.0-Master | QGIS code revision | 75ba9b394d
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.6.2-CAPI-1.10.2 4d2925d6
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 10.10 (Ubuntu 10.10-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Ubuntu 18.04.3 LTS
Active python plugins | quick_map_services; pdokservicesplugin; DEMto3D; QCopycanvas; catalogpl_plugin; firstaid; processing

**Additional context**

**Comment by nyalldawson** [comment]
Can you provide a test project please?

**Comment by raymondnijssen** [comment]
[randommarker.zip](https://github.com/qgis/QGIS/files/4018552/randommarker.zip)

**Comment by raymondnijssen** [comment]
If you turn on the "multis" layer in the test project (containing 2 mutli polygons) en zoom in some steps, QGIS will crash. At least mine does.

Yesterday it crashed instantly but today I need to zoom in a few steps. I guess I was at a higher scale already yesterday, which could mean that the bug only happens at higher scales.

**Comment by roya0045** [comment]
The polygon gpkg only contains singles for me.

**Comment by gioman** [comment]
> The polygon gpkg only contains singles for me.

true, also the provided project does not seems to have the necessary symbology.

**Comment by raymondnijssen** [comment]
[randommarker2.zip](https://github.com/qgis/QGIS/files/4421100/randommarker2.zip)

**Comment by gioman** [comment]
> [randommarker2.zip](https://github.com/qgis/QGIS/files/4421100/randommarker2.zip)

thanks @raymondnijssen no crash here on 3.12.1

**Comment by nyalldawson** [comment]
Closing due to lack of feedback
