### ISSUE TITLE
browser: does not load SpatiaLite views correctly from "project home"

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#33586]
The project home - in the browser panel - is a very useful folder,
it contains and displays the project file and other files inside.

This folder is displayed in the browser panel immediately after having
saved the project.

I notice that spatialite views loaded from this folder don't
they are well managed, that is, load only the first line despite the
view properties the correct number of rows appears.

For verification I uploaded the same view, same SL db from the SPatialite group
always present in the browser panel, and they work well, I read all the lines.

how to reproduce it:
1. create a spatialite database, I used spatialite_gui 2.0 (spatialite
4.3a);
2. import of any carriers;
3. create a simple view, without geometry, using geo-tables
present in the db;
4. start QGIS, connect the db using a browser panel
5. add a geo-tables to the project;
6. save the project, close QGIS and restart it; open the project;
7. in the browser panel at the top you will find the project Home, inside the
database;
8. try to load the view from the home page;
9. open the attribute table and you will notice:
to. start with rowid, even if it is not a field of the view;
b. only the first row is visible.

I attach a spatialite db and test project.
https://mega.nz/#!wMhRQCAA!lsO71upZGWfbYVLUV8NdpR-3cwX0OjX-Wuux5H0eZ-g

```
Versione di QGIS 3.10.1-A Coruña
Revisione codice QGIS ef24c526da
Compilato con Qt 5.11.2
Esecuzione con Qt 5.11.2
Compilato con GDAL/OGR 3.0.2
Esecuzione con GDAL/OGR 3.0.2
Compilato con GEOS 3.8.0-CAPI-1.13.1
Esecuzione con GEOS 3.8.0-CAPI-1.13.1 
Compiled against SQLite 3.29.0
Running against SQLite 3.29.0
Versione client PostgreSQL 11.5
Versione SpatiaLite 4.3.0
Versione QWT 6.1.3
Versione QScintilla2 2.10.8
Compiled against PROJ 6.2.1
Running against PROJ Rel. 6.2.1, November 1st, 2019
OS Version Windows 10 (10.0)
```

**Comment by elpaso** [comment]
>     3\. geotabels

what is it?

... and what is a "geotab" ?

**Comment by gioman** [comment]
> what is it?
> 
> ... and what is a "geotab" ?

@elpaso he means a table with geometries, a layer. I followed the described steps and replicated the issue here.

**Comment by pigreco** [comment]
@elpaso 
I corrected,
geo-table = table with geometry field

@gioman 
thanks for the help and confirmation of the bug

**Comment by pigreco** [comment]
Please, if you need to make a fundraiser say it explicitly. thanks

**Comment by gioman** [comment]
> Please, if you need to make a fundraiser say it explicitly. thanks

@pigreco see https://github.com/qgis/QGIS/issues/35016#issuecomment-641176040

**Comment by Pedro-Murteira** [comment]
@pigreco I followed these steps but I wasn't able to reproduce it on QGIS 3.22.2. I might be missing something here, not entirely sure. Did you come across this issue more recently?

**Comment by pigreco** [comment]
> @pigreco I followed these steps but I wasn't able to reproduce it on QGIS 3.22.2. I might be missing something here, not entirely sure. Did you come across this issue more recently?

in 3.22.2 and 3.22.3 everything seems to be solved, it works
but in 3.16.16-1 no

**Comment by gioman** [comment]
> but in 3.16.16-1 no

@pigreco considering that is 3.16 is becoming EOL soon, I guess is probable there will not be any special effort in fixing this.

**Comment by nyalldawson** [comment]
The final 3.16 release has already occurred -- no more bugs will be fixed in this release.

@gioman I think we can close this

**Comment by gioman** [comment]
Done.
