### ISSUE TITLE
SSL handshake failed

### ISSUE THREAD

**Issue by bernardflach** [qgis/QGIS#33582]
version  : QGIS 3.10.1
Host OS : Debian 10
No proxy

taken steps : 
add WMS :  http://ows.gis.rotterdam.nl/cgi-bin/mapserv.exe?map=d:\gwr\webdata\mapserver\map\BBDWH_pub.map
Add a layer to workspace

What i end up with:
-> I see the capabilities See screenshot)
-> but my adding a layer to the workspace, i get the error "SSL handshake failed" (see screenshot)
![Schermafdruk van 2020-01-02 13-44-47](https://user-images.githubusercontent.com/49860071/71667596-1f1b0500-2d66-11ea-9168-1c531fa4af48.png)
![Schermafdruk van 2020-01-02 13-44-03](https://user-images.githubusercontent.com/49860071/71667597-1f1b0500-2d66-11ea-91fb-0b6b65d43e76.png)

Note : some other public mapservices worklike a charm however this one is not. 
Tested on :
-> Has been tested by a facebook user (qgis community) on QGIS 3.10 on windows witch works
-> tested by me on QGIS 3.4 witch works.
-> tested by me on QGIS 3.10.0 witch works

It looks like a update (QGIS 3,10.0 -> QGIS 3.10.1) caused this.  
can you confirm this ?

**Comment by gioman** [comment]
works here on 3.10.1 on Windows

![Screenshot_20200102_160947](https://user-images.githubusercontent.com/1951107/71677354-8d69c280-2d7a-11ea-9f8a-3cb8d3b14812.png)

Please try by cleaning the QGIS's network cache.

**Comment by bernardflach** [comment]
Did a clean cache and then a complete reinstall of application. Not working. Did a reinstall of the workstation, installed QGIS 3.10.1 via flatpak (linux) and strange enough ..... it works. 
I cant explain but it happened after upgrade 3.10 -> 3.10.1. So this issue can be closed.
