### ISSUE TITLE
Some NTv2 grids are incorrectly not recognized as NTv2

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/QGIS#33590]
NTv2 grid files that contain the string "towgs84" in the file name are incorrectly not recognized as NTv2 datum transformations in the "Select Datum Transformations" dialog window.

The bug affects QGIS 3.4, 3.10 using PROJ < 6.

![image](https://user-images.githubusercontent.com/16253859/71714893-d1f36d80-2e0f-11ea-911d-fe5d0a879bce.png)

For example, the NadRoma40.gsb is correctly labelled as NTv2, while ItalyMonteMarioToWGS84_NTV2.gsb is incorrectly not labelled as NTv2.

This is caused by QgsDatumTransformDialog::gridShiftTransformation in 3.10 and QgsCoordinateOperationWidget::gridShiftTransformation in current master which check for the string "towgs84" in the source or destination datum transform proj string.

https://github.com/qgis/QGIS/blob/4f307cf03edd5a3d5dd429ee6176ee697a424916/src/gui/qgsdatumtransformdialog.cpp#L728-L731
https://github.com/qgis/QGIS/blob/c367e770de510e61d10870c7ba995b4ec9c3ced2/src/gui/qgscoordinateoperationwidget.cpp#L638-L641

I think it could be less problematic to check for the string "+towgs84=" or for "+nadgrids=" which are less likely to be present in the NTv2 grid file name.

It should be better to let [QgsDatumTransform::datumTransformInfo](https://github.com/qgis/QGIS/blob/master/src/core/qgsdatumtransform.cpp#L273) retrieve also the transformation method code in the coord_op_method_code field from tbl_datum_transform table of srs.db and test against it (9615 for NTv2 method).

**Comment by nyalldawson** [comment]
This is unlikely to be fixed -- on proj 6+ builds the logic is completely different, and use of earlier proj versions is not recommended.
