### ISSUE TITLE
unexpected crash after loading project with just shapefiles

### ISSUE THREAD

**Issue by janhec** [qgis/QGIS#33591]
## User Feedback

Using large (but <2GB) shapefiles with arcgis spatial index (and project file).
After loading the project, I inquired a large shape, got the are from actions, did a bit of excel and when I returned to QGis, it had stopped.
System: 64 bit W10, up to date, AMD Ryzen 2700X, 32 GB ram, machine functions fine. Qgis v 3.10 etc. See below.
Nothing extraordinary, therefore.
Have regular crashes which did not happen in previous versions and perhaps only recently with v3.10. The program goes into non-response and only a minute or so later reports the crash.
The stacktrace contains writes of dbf and shp, which should not have occurred, since I did not edit anything. The writes are not reflected in the time stamps of the files (presumably) in question.

## Report Details

**Crash ID**: [029bc1a9b819dfb49a1342291172e44f3c1f8e53]('https://github.com/qgis/QGIS/search?q=029bc1a9b819dfb49a1342291172e44f3c1f8e53&type=Issues')

**Stack Trace**
<pre>
osgeo::proj::datum::Datum::conventionalRS :
osgeo::proj::datum::Datum::conventionalRS :
osgeo::proj::datum::Datum::conventionalRS :
OGRSpatialReference::~OGRSpatialReference :
OGRSpatialReference::operator= :
OGRGeomFieldDefn::~OGRGeomFieldDefn :
SHPWriteObject :
OGRFeatureDefn::~OGRFeatureDefn :
OGRFeatureDefn::~OGRFeatureDefn :
SHPWriteObject :
DBFWriteTuple :
OGREditableLayer::Translate :
QgsOgrProviderUtils::GDALCloseWrapper qgsogrprovider.cpp:4129
QgsConnectionPoolGroup<QgsOgrConn * __ptr64>::onConnectionExpired qgsconnectionpool.h:227
QMetaObject::activate :
QTimer::timerEvent :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32Private::sendTimerEvent :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1598
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.0-A Coru�a
QGIS code revision: 6ffa89eb3e
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
>  QGIS Version: 3.10.0-A Coru�a

@janhec please update to the latest release (3.10.1 at this time).

**Comment by nyalldawson** [comment]
This is a gdal issue, fixed upstream

**Comment by janhec** [comment]
Thanks, so far it's ok again!
Jan
