### ISSUE TITLE
Unable to Remove Vertex in QGIS 3.4.14 LTR

### ISSUE THREAD

**Issue by asgharibraheembaloch** [qgis/QGIS#33592]
Unable to remove vertex in QGIS 3.4.14 LTR when "Layer Styling Dock" is open

![QGIS_3 4 14](https://user-images.githubusercontent.com/46741864/71720779-ad65b880-2e44-11ea-9173-4f6d7ea5cb99.PNG)

**Comment by roya0045** [comment]
Out of curiosity, does it still occur with the live update disabled?

**Comment by gioman** [comment]
FYI it only happens if the active tab is "rule based labelling".

**Comment by gioman** [comment]
> Out of curiosity, does it still occur with the live update disabled?

yes.

**Comment by nyalldawson** [comment]
Thanks for the extra clarification @gioman -- I've been trying to track this one down for some time and never realised it was linked to the rule-based renderer panel visibility!
