### ISSUE TITLE
Draw effects dialog does not display the actual symbol but uses an abstract red circle

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#33600]
On the road to update the screenshots [in the docs](https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/vector_properties.html#draw-effects), I realize that it's not possible to display the current symbol in the effects dialog. I think this was possible in earlier versions as shown in this screenshot
![image](https://user-images.githubusercontent.com/7983394/71763766-f6b71600-2edf-11ea-9b9b-a913c4c91aed.png)
which imho is more helpful to visualize the changes on my symbol than the abstract symbol below
![image](https://user-images.githubusercontent.com/7983394/71763818-aab8a100-2ee0-11ea-9f63-4107b835cc5d.png)

Btw, isn't there an issue with the drop shadow preview in the second screenshot?

Using QGIS 3.10.1

**Comment by nyalldawson** [comment]
What's the drop shadow issue? Also, I don't recall there ever being support for showing the actual marker symbol here. I'm not sure how that screenshot would have been generated...

**Comment by nyalldawson** [comment]
Ah no, there IS code here for that. Strange, I don't recall adding that at all...

**Comment by nyalldawson** [comment]
Ah - got it. It only shows if you're setting the effect for a symbol layer, not if you're setting the effect for the whole layer.

I think this is a "wont fix". A layer could have many different symbols, so if you're setting an effect on a layer-wide level then its not possible to use a single symbol to show the effect's results.

**Comment by DelazJ** [comment]
> What's the drop shadow issue?

It looks like there's a halo around the source while I'd expect a shift in the 135° direction, like shown in the orange screenshot.
Here's the drop shadow with 100% opacity
![image](https://user-images.githubusercontent.com/7983394/71763934-65956e80-2ee2-11ea-950d-2dd7330d9530.png)

**Comment by DelazJ** [comment]
> Ah - got it. It only shows if you're setting the effect for a symbol layer, not if you're setting the effect for the whole layer.

I can't confirm. Trying from the symbol manager and whatever symbol I take, i also get that circle. In the previous example I thought layer level was the issue hence I was testing it from the symbol properties (using a single symbol rendering for the layer) and not from the layer features section.

**Comment by DelazJ** [comment]
Testing further: you get a display in the layer styling panel but not when using the layer properties nor from the symbol manager.

**Comment by nyalldawson** [comment]
> It looks like there's a halo around the source while I'd expect a shift in the 135° direction, like shown in the orange screenshot.
Here's the drop shadow with 100% opacity

No, it's correct. You've got an offset distance of only 2mm while the shadow blur is 10mm, which is why it appears more like a glow. Try increasing the offset or decreasing the blur

**Comment by DelazJ** [comment]
Ok I see. it works. I was using same values as in the docs but earlier versions did not expose units selection for the blur radius (hence pixel-based).
