### ISSUE TITLE
GeoReferencer GCPtbale does not appear to act the same as it does in 3.10 to 3.10.1

### ISSUE THREAD

**Issue by MPN-stack** [qgis/QGIS#33607]
I have been experiencing some problems with  Geo tagging an image and a friend send me a working points file from 3.10 on his computer as follows:

mapX,mapY,pixelX,pixelY,enable,dX,dY,residual
0.53799722222222224,50.87444444444444258,1543.36274509803934052,-1680.3137254901957931,1,0.00000000000045475,0.00000000000181899,0.00000000000187497
0.53805555555555551,50.86722222222222456,1409.71568627451074462,-3495.21568627450915301,1,-0.00000000000181899,0.00000000000181899,0.00000000000257244
0.54083333333333328,50.87916666666666998,1975.67647058823581574,-478.43137254901921551,1,-0.00000000000022737,0.00000000000318323,0.00000000000319134
0.54138888888888892,50.87222222222222001,2116.22549019607868104,-2303.05882352941080171,1,-0.00000000000090949,-0.00000000000090949,0.00000000000128622
0.53250000000000008,50.86749999999999972,563.91176470588311531,-3527.8431372549016487,1,-0.00000000000250111,0.00000000000636646,0.00000000000684013

When I place this in my points file t sends the map out to sea. Now I note difference in the file as there is differences in  dx(pixels), dy(pixels), Residual(pixels) being created in 3.10.1 but are created in 3.10. with the same imported points set above.
![table from qgis 3 10](https://user-images.githubusercontent.com/54211372/71771844-8370cc80-2efe-11ea-8e2a-e94968a3eaa3.png)

Created in 3.10.1
![table with imported data from points file in 3 10 1](https://user-images.githubusercontent.com/54211372/71771891-1f9ad380-2eff-11ea-98a9-f7ba3612bb99.png)

I am wondering if 3.10.1 is very buggy and have not seen any version or information saying that going out to google maps no longer works

  used  points .

1. 50 52 50 0 32 16
2. 50 52 02 03 17
3. 50 52 45 0 32 27
4. 50 52 20 0 32 29
5. 50 52 03 0 31 57

All on the ESPG 3857- WGS 84 Psudo Mercataor

I converted these to map coordinates in Google Maps just in case there was any error
Eastings, Northings

1. 0.537997, 50.874444
2. 0.538056, 50.867222
3. 0.540833, 50.879167
4. 0.541389, 50.872222
5. 0.532500, 50.867500

![5014f51d5d0e35e80b41db2d5409e5e7](https://user-images.githubusercontent.com/54211372/71771855-9d121400-2efe-11ea-8bab-d52ec856dfcc.png)

Now if I click get co-ordinates from map point on other maps this works fine. I am wondering if there is something odd going on with grid references from google maps in 3.10.1 as this same shape file points places the image on land in 3.10(image below) but in the seanin 3.10.1(image above)
![map in 3 10](https://user-images.githubusercontent.com/54211372/71771860-ab603000-2efe-11ea-9214-cca8ff52305c.png)

Thanks for looking and any help would be gratefully received. 

It should be noted I tried this on my laptop version of QGIS which just placed the image in the sea again with same data using a 3.10.1 version of QGIS 
![58f5b5b1ea39694fac290b498914d13e](https://user-images.githubusercontent.com/54211372/71772227-e82f2580-2f04-11ea-9cbc-ded0b1e31cfb.png)

**Comment by gioman** [comment]
@MPN-stack I'm having an hard time in understanding how to try replicate. I would appreciate if you can:

* add step by step instructions

* add the necessary files (in this case the image to be georeferenced and the GPC table *file*) and parameters used in the georeferencer

* describe expected results vs obtained

**Comment by MPN-stack** [comment]
[SOLVED] Havig been to a friends today it was noted The CRS was different between the two images being created on 3.10 and 3.10.1 . It seems that installing 3.10.1 lost the default layer settings all is good now with this excellent software.
