### ISSUE TITLE
QgsCoordinateReferenceSystem.fromWkt fails with e.g. GLanCE data record WKTs

### ISSUE THREAD

**Issue by jakimowb** [qgis/QGIS#33614]
**Problem**

`QgsCoordinateReferenceSystem.fromWkt() ` fails to import some CRS WKTs which otherwise are recognized correctly by GDAL and can be imported via `QgsCoordinateReferenceSystem.fromProj4(gdalSRS.ExportToProj4())`.

In consequence, QGIS shows a "Layer has not coordinate reference system set" error, e.g. for raster data sets that are projected in one of the 7 continental NASA GLANCE (see background below) projection systems.

**How to reproduct**

This example shows how `QgsCoordinateReferenceSystem.fromWkt()` fails to import the GLANCE LAEA projection WKT for South America. A unit test (`test_glance_wkts.py`), WKT definitions of the mentioned GLANCE CRS and a raster quality flag image projected in GLANCE_GRIDS_V01_SA_CRS (`20140803_LEVEL2_LND07_QAI.tif`) are appended [crs_glance.zip](https://github.com/qgis/QGIS/files/4023839/crs_glance.zip):

```python
wkt = r'PROJCS["BU MEaSUREs Lambert Azimuthal Equal Area - SA - V01",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["degree",0.0174532925199433]],PROJECTION["Lambert_Azimuthal_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["longitude_of_center",-60],PARAMETER["latitude_of_center",-15],UNIT["meter",1.0]]'

from osgeo import gdal, osr, ogr
srs = osr.SpatialReference()
srs.ImportFromWkt(wkt)
assert srs.Validate() == ogr.OGRERR_NONE

from qgis.core import QgsCoordinateReferenceSystem
# this works fine
crs = QgsCoordinateReferenceSystem.fromProj4(srs.ExportToProj4())
assert crs.isValid()

# this fails
crs = QgsCoordinateReferenceSystem.fromWkt(wkt)
assert crs.isValid()
```

**Background**

The NASA Global Land Cover mapping and Estimation (GLanCE) project defines 7 continental coordinate reference systems that are used for raster data records of global land cover, land use and land cover change at 30m resolution. 

Project details can be found at http://sites.bu.edu/measures/

The following CRS WKTs are take from https://github.com/measures-glance/glance-grids/tree/master/data/crs_wkt

Name | WKT
------|---- 
GLANCE_GRIDS_V01_AF_CRS.wkt | PROJCS["BU MEaSUREs Lambert Azimuthal Equal Area - AF - V01",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["degree",0.0174532925199433]],PROJECTION["Lambert_Azimuthal_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["longitude_of_center",20],PARAMETER["latitude_of_center",5],UNIT["meter",1.0]]
GLANCE_GRIDS_V01_AN_CRS.wkt | PROJCS["BU MEaSUREs Lambert Azimuthal Equal Area - AN - V01",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["degree",0.0174532925199433]],PROJECTION["Lambert_Azimuthal_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["longitude_of_center",0],PARAMETER["latitude_of_center",-90],UNIT["meter",1.0]]
GLANCE_GRIDS_V01_AS_CRS.wkt | PROJCS["BU MEaSUREs Lambert Azimuthal Equal Area - AS - V01",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["degree",0.0174532925199433]],PROJECTION["Lambert_Azimuthal_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["longitude_of_center",100],PARAMETER["latitude_of_center",45],UNIT["meter",1.0]]
GLANCE_GRIDS_V01_EU_CRS.wkt | PROJCS["BU MEaSUREs Lambert Azimuthal Equal Area - EU - V01",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["degree",0.0174532925199433]],PROJECTION["Lambert_Azimuthal_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["longitude_of_center",20],PARAMETER["latitude_of_center",55],UNIT["meter",1.0]]
GLANCE_GRIDS_V01_NA_CRS.wkt | PROJCS["BU MEaSUREs Lambert Azimuthal Equal Area - NA - V01",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["degree",0.0174532925199433]],PROJECTION["Lambert_Azimuthal_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["longitude_of_center",-100],PARAMETER["latitude_of_center",50],UNIT["meter",1.0]]
GLANCE_GRIDS_V01_OC_CRS.wkt | PROJCS["BU MEaSUREs Lambert Azimuthal Equal Area - OC - V01",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["degree",0.0174532925199433]],PROJECTION["Lambert_Azimuthal_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["longitude_of_center",135],PARAMETER["latitude_of_center",-15],UNIT["meter",1.0]]
GLANCE_GRIDS_V01_SA_CRS.wkt | PROJCS["BU MEaSUREs Lambert Azimuthal Equal Area - SA - V01",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["degree",0.0174532925199433]],PROJECTION["Lambert_Azimuthal_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["longitude_of_center",-60],PARAMETER["latitude_of_center",-15],UNIT["meter",1.0]]

**Comment by nyalldawson** [comment]
Which proj library version are you using? (Check from the about screen)

**Comment by nyalldawson** [comment]
I can't reproduce under QGIS 3.10 with either proj 5 or 6 based build

**Comment by jakimowb** [comment]
Maybe it's a Windows problem? 

Component | Version
------------|-------------
QGIS version | 3.10.1-A Coruña
QGIS code revision | ef24c526da
Compiled against Qt | 5.11.2
Running against Qt |5.11.2
Compiled against GDAL/OGR | 3.0.2
Running against GDAL/OGR | 3.0.2
Compiled against GEOS | 3.8.0-CAPI-1.13.1
Running against GEOS | 3.8.0-CAPI-1.13.1 
Compiled against SQLite | 3.29.0
Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5
SpatiaLite Version | 4.3.0
QWT Version | 6.1.3
QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.2.1
Running against PROJ | Rel. 6.2.1, November 1st, 2019
OS Version | Windows 10 (10.0)
Active python plugins | db_manager;  processing

**Comment by jakimowb** [comment]
I reproduces the error on Ununtu 18.04.03 with GDAL 3.0.2. and Proj4 6.2.1.
![grafik](https://user-images.githubusercontent.com/1404870/71878716-9ec11f00-312c-11ea-9e9a-8c2e1b075156.png)

![grafik](https://user-images.githubusercontent.com/1404870/71879080-7e459480-312d-11ea-8a00-3d26a2f8763d.png)

**Comment by nyalldawson** [comment]
Hmmmm, maybe it's been fixed as part of the 3.10.2 changes...

**Comment by nyalldawson** [comment]
Can you reproduce on 3.10.2?

**Comment by jakimowb** [comment]
Thanks, since 3.10.2 it works fine on Windows.  I think this issue can be closed.
