### ISSUE TITLE
QGIS Browser Panel item refresh cause crash

### ISSUE THREAD

**Issue by Samweli** [qgis/QGIS#33621]
Compiling QGIS master and doing a refresh on postgres data provider connection item while a 
WMS connection item is open and there are changes ( from WMS Server ) in WMS 
layer items will cause a QGIS crash. 

This also occurs in  QGIS 3.4 and QGIS 3.10. 

Steps to reproduce

1. Add Postgres connection
2. Add WMS/WMTS connection
3. Make changes in any of the WMS/WMTS connection layers (eg. change value of the layer title), this should be done from the WMS server.
4. Expand the WMS/WMTS connection to show the layers with the expected changes.
5. Go to the Postgres connection, right click and click "Refresh".

Below is the traceback from QGIS 3.10. 

```
QgsBrowserModel::data qgsbrowsermodel.cpp:251 
QSortFilterProxyModel::data : 
QModelIndex::data : 
QStyledItemDelegate::initStyleOption : 
QStyledItemDelegate::sizeHint : 
QTreeViewPrivate::widthHintForIndex : 
QTreeView::sizeHintForColumn : 
QHeaderView::resizeSections : 
QHeaderView::sectionSize : 
QTreeViewPrivate::updateScrollBars : 
QTreeView::updateGeometries : 
QTreeView::timerEvent : 
QObject::event : 
QWidget::event : 
QFrame::event : 
QAbstractScrollArea::event : 
QApplicationPrivate::notify_helper : 
QApplication::notify : 
QgsApplication::notify qgsapplication.cpp:418 
QCoreApplication::notifyInternal2 : 
QEventDispatcherWin32::event : 
QApplicationPrivate::notify_helper : 
QApplication::notify : 
QgsApplication::notify qgsapplication.cpp:418 
QCoreApplication::notifyInternal2 : 
QCoreApplicationPrivate::sendPostedEvents : 
qt_plugin_query_metadata : 
QEventDispatcherWin32::processEvents : 
UserCallWinProcCheckWow : 
DispatchMessageWorker : 
QEventDispatcherWin32::processEvents : 
qt_plugin_query_metadata : 
QEventLoop::exec : 
QCoreApplication::exec : 
main main.cpp:1598 
BaseThreadInitThunk : 
RtlUserThreadStart : 
```

**Comment by Samweli** [comment]
I'm currently exploring a fix for this, I'll appreciate any input!

**Comment by roya0045** [comment]
Just had a glance at the code and it would appear that the item is returning an invalid icon.  If this is the case I assume that an error handling method to find the icon in some other way or by setting a default icon would do the trick.

**Comment by Samweli** [comment]
> Just had a glance at the code and it would appear that the item is returning an invalid icon

@roya0045 I'm not sure if it even return invalid icon.
Evaluating the code on the line where execution stops / crash occurs with `item->icon()` returns `<no such value>`. I suspect that it is try to access a QgsDataItem which has already been deleted.

**Comment by roya0045** [comment]
> > Just had a glance at the code and it would appear that the item is returning an invalid icon
> 
> @roya0045 I'm not sure if it even return an invalid icon.
> Evaluating the code on the line where execution stops / crash occurs with `item->icon()` returns `<no such value>`. I suspect that it is try to access a QgsDataItem which has already been deleted.

The validity of the pointer is evaluated on line 233, a QgsDataItem should exist ? Though you could try to debug [the icon method](https://github.com/qgis/QGIS/blob/c3f98ebfce51537688aa3d10bb88ad85502b41a9/src/core/qgsdataitem.cpp#L226) just to see if it even gets there.

**Comment by Samweli** [comment]
> The validity of the pointer is evaluated on line 233, a QgsDataItem should exist ? Though you could try to debug [the icon method](https://github.com/qgis/QGIS/blob/c3f98ebfce51537688aa3d10bb88ad85502b41a9/src/core/qgsdataitem.cpp#L226) just to see if it even gets there.

Debugging again causes the crash to happen at a different point. This is why I feel there is access of an already deleted item.

```
4   QgsBrowserModel::flags                                  qgsbrowsermodel.cpp    217 
5   QgsBrowserGuiModel::flags                               qgsbrowserguimodel.cpp 39  
6   QSortFilterProxyModel::flags(QModelIndex const&) const                            
7   QTreeViewPrivate::layout(int, bool, bool)                                        
8   QTreeViewPrivate::layout(int, bool, bool)                                          
9   QTreeViewPrivate::layout(int, bool, bool)                                          
10  QTreeViewPrivate::layout(int, bool, bool)                                          
11  QTreeView::doItemsLayout()                                                        
12  QAbstractItemView::timerEvent(QTimerEvent *)                                       
13  QTreeView::timerEvent(QTimerEvent *)                                               
14  QObject::event(QEvent *)                                                           
15  QWidget::event(QEvent *)                                                          
16  QFrame::event(QEvent *)                                                            
17  QAbstractScrollArea::event(QEvent *)                                               
18  QAbstractItemView::event(QEvent *)                                                 
19  QApplicationPrivate::notify_helper(QObject *, QEvent *)                           
20  QApplication::notify(QObject *, QEvent *)                                          
... <More>       

```

**Comment by roya0045** [comment]
That might be possible, though I'm not too sure what might cause this to be released during refresh. :/

**Comment by Samweli** [comment]
I think it happen during refresh because of this line https://github.com/qgis/QGIS/blob/3f9b53ea73e6e3c596fcf5dbd5ac856291232f70/src/providers/postgres/qgspostgresdataitemguiprovider.cpp#L214
It cause the root node of the browser items to refresh which in turn also refreshs its children, but fails to refresh the WMS items which have been updated in their server leading to crash.
@wonder-sk do you think this might be the cause?
