### ISSUE TITLE
Add DB schema to Favorites in Browser Panel

### ISSUE THREAD

**Issue by Jakob-Lanstorp** [qgis/QGIS#33639]
**Feature description.**
As you can add a folder to Favorites in QGIS Browser Panel, it could be fancy if you also could add things like a database schema to Favorites.

![Capture](https://user-images.githubusercontent.com/8887576/71885320-6c1e2300-313a-11ea-8f6d-60e00d7f998c.PNG)

**Comment by haubourg** [comment]
I like the idea! +1

**Comment by alexbruy** [comment]
Duplicates #18825.
