### ISSUE TITLE
wrapped C/C++ object of type QgsVectorLayer has been deleted

### ISSUE THREAD

**Issue by FlyingEagle** [qgis/QGIS#33646]
advanced_line_editor.py", line 299, in currentLayerChanged
              self.currentlayer.editingStarted.disconnect(self.curLayerIsEditable)
             RuntimeError: wrapped C/C++ object of type QgsVectorLayer has been deleted

What does this mean and how can I fix it?

QGIS-Version
3.10.1-A Coruña

**Comment by nyalldawson** [comment]
Looks like an issue caused by a plugin you have installed. Try disabling plugins one by one to identify the culprit...

**Comment by alexbruy** [comment]
Closed for the lack of feedback. Please reopen if necessary.
