### ISSUE TITLE
Temporary files (processing output) are not discarded after closing QGIS.

### ISSUE THREAD

**Issue by pathmapper** [qgis/QGIS#33641]
**Describe the bug**
On Windows, temporary files (processing outputs when using tools from the processing toolbox in QGIS) are not discarded after closing QGIS.

**How to Reproduce**

1. Use the GDAL tool _Clip Vector by Extent_ from the processing toolbox on a vector layer and save the output to a temporary file like on the following screenshot:

![Unbenannt](https://user-images.githubusercontent.com/20856381/71899626-6cc7b100-315c-11ea-9b51-aa4d201499b9.PNG)

2. Copy the specified output path

3. Close QGIS

4. Browse to the specified output path -> the temp files are still there

**QGIS and OS versions**

QGIS version | 3.10.1-A Coruña | QGIS code revision | ef24c526da
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.2 | Running against GDAL/OGR | 3.0.2
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.2.1 | Running against PROJ | Rel. 6.2.1, November 1st, 2019
OS Version | Windows 10 (10.0)
Active python plugins | canvas_clipper; db_manager; MetaSearch; processing

**Additional context**

On Linux this issue doesn't exist.
Please note, that on Linux there is only one directory prefixed with `processing_` created while on Windows there is a `processing_` directory in another `processing_` directory created.

For comparision here the output path on Linux:
![3](https://user-images.githubusercontent.com/20856381/71901658-b3b7a580-3160-11ea-9442-2d9422ed9ff4.PNG)

Maybe https://github.com/qgis/QGIS/issues/28222 is related.

Edit:
This issue exists also when using `QgsProcessing.TEMPORARY_OUTPUT` in PyQGIS ([context](https://gis.stackexchange.com/questions/346646/pyqgis-save-processing-output-to-temporary-file-which-is-discarded-when-qgis-i#comment566786_346688)).

**Comment by alexbruy** [comment]
Partially related to changes from #33086.

**Comment by alexbruy** [comment]
Issue with duplicating folders should be fixed by #33686. Also you can fix it manually by setting "Temporary output folder path" to user temp directory in the Processing settings.

Regarding clearing temporary files Linux (and probably other UNIX-like systems) allows to delete files which are used by another process, but Windows does not. As workaround you can remove all temporary files before closing QGIS (for example, by creating a new empty project). In this case all used files will be unlocked and removed on close.

Probably we should clear temporary directore not from Processing, but as part of QGIS cleanup routine. I will try to look into it.

**Comment by nyalldawson** [comment]
Should be fixed in recent versions

**Comment by pathmapper** [comment]
Yep, this is is fixed in `3.12.1`, thanks!

**Comment by PedroVenancio** [comment]
Hi @nyalldawson @alexbruy 

I'm with a related issue and I don't know if this can be solved somehow.

I've a processing model with 4 algorithms that run sequencialy:
1. Calculate Viewshed;
2. r.null to change 0 to null;
3. Assign Projection;
4. Polygonize.

I'm running this model iterating from a vector layer with about 1700 points. 

The first step gives a temporary output of about 1GB, which multiplied by 1700 is a huge amount of hard drive space, that I don't have! 

So, I've set a job/task to delete files created 15 minutes before, to try to delete the temporary files from the first step, but they are always blocked and "used by another process - QGIS", until I stop the running model. 

The workaround I'm following is reducing the input raster resolution. 

But is there any chance to QGIS leave old temporary files free, when using iterate option on Windows machines?

Thanks!

Best regards,
Pedro

**Comment by driansmith** [comment]
I use ccleaner as a regular tool to cleanup a wide range of debris from the hard drive. The free version works perfectly well - I've used it for many years.
https://www.ccleaner.com/ccleaner

**Comment by nicogodet** [comment]
@PedroVenancio I hit this issue today while writing an iterating script.

A workaround if to transform your faulty huge raster to a tiny one if you don't need it in further iterations.

```python
    def suppressionFichier(self, fichier, outputs, context, feedback):
        alg_params = {
            "EXTENT": "-1.0000,1.0000,-1.0000,1.0000 [EPSG:2154]",
            "LOWER_BOUND": 0.01,
            "OUTPUT_TYPE": 5,
            "PIXEL_SIZE": 1,
            "TARGET_CRS": "ProjectCrs",
            "UPPER_BOUND": 0.01,
            "OUTPUT": fichier,
        }
        outputs["aleatoire"] = processing.run(
            "native:createrandomuniformrasterlayer",
            alg_params,
            context=context,
            feedback=feedback,
            is_child_algorithm=False,
        )
```
and from my loop in `processAlgorithm()` I call:
```python
    if supprFichiersIntermed:
        self.suppressionFichier(raster_A, outputs, context, feedback)
        self.suppressionFichier(raster_B, outputs, context, feedback)
        self.suppressionFichier(raster_C, outputs, context, feedback)
```

If Qgis don't want you to use os.remove(), it allows you to re-use the file in another algorithm.
Above function take your file as an input and it designates this file as output from the alg that generates a random raster of 4 pixels of 1 meter each.

**Comment by rjavierch** [comment]
Hello!

Currently I am using QGIS version 3.22.5-Białowieża and I am facing this problem. Almost all my disk space is gone after a few days of working with raster images.

Is there any "For dummies" way to manually delete the files?

**Comment by kannes** [comment]
> Hello!
> 
> Currently I am using QGIS version 3.22.5-Białowieża and I am facing this problem. Almost all my disk space is gone after a few days of working with raster images.
> 
> Is there any "For dummies" way to manually delete the files?

Find your temporary directory (maybe `C:\Users\user\AppData\Local\Temp`?) and while QGIS is closed, delete all `processing_*` directories. Warning: If you have projects referencing those temporary files, they will be broken afterwards of course!

**Comment by kannes** [comment]
Thanks for your great idea @nicogodet, unfortunately this does not seem to truncate the "file" in shared buffers. At least on Linux I end up with nice small files in `/tmp/` but my shared buffers still referencing the huge intermediate files (`lsof -nP +L0 /tmp | grep processing`). Dang, this looked so good! :]
