### ISSUE TITLE
Custom CRS info lost when new layer generated

### ISSUE THREAD

**Issue by Houska1** [qgis/QGIS#33640]
Project CRS is a custom CRS (USER:100000).

**Instance 1.** When raster calculator creates new layer, CRS info is missing even though specified (as USER:...) in the dialog box. Since I have settings to put layers with unknown CRS into project CRS, I get warning message "CRS was undefined : defaulting to project CRS USER:100000 - AAFC" and it fixes itself. But it should have picked up the specified CRS from the dialog.

**Instance 2.** Doing `Raster / Conversion / Polygonize` on a raster in this CRS, the newly created polygon layer is missing its CRS. Appears with ? in layer list, and "invalid projection" when attempting to export. See picture attached. I have to set CRS manually.

![ScreenClip](https://user-images.githubusercontent.com/48919900/71898384-2a37b180-3127-11ea-921d-79fa786432fc.png)

The above 2 instances do not happen when project and layer is in a EPSG: projection. (I have not tried with project and layer in different CRSes). 

**Instance 3.** Various occasions CRS info is not added to output layers when doing vector or raster processing with grass plugins from QGIS processing toolbox. Have only done this with this USER: projection, and blamed grass<>QGIS interaction. But in view of the above, may be related. 

In case relevant, my custom CRS definition is `+proj=aea +lat_0=40 +lon_0=-96 +lat_1=44.75 +lat_2=55.75 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs`.

QGIS 3.10.1, OSGeo4W.

**Comment by nyalldawson** [comment]
Please test with 3.10.2 -- this was likely fixed as a result of changes in that version

**Comment by nyalldawson** [comment]
Closing due to lack of feedback
