### ISSUE TITLE
Snapping with newly created line segment of postgis layer

### ISSUE THREAD

**Issue by asgharibraheembaloch** [qgis/QGIS#33664]
we have postgis database layers in our production environment, problem here is when ever i insert new segment for postgis layer, snapping doesn't work for this newly created segment or segments processed from processing toolbar for postgis line layer, i resolve this issue by uncheck and then check layer, for further clarification video is attached in zip file
qgis version is 3.4.14

[qgis_issue.zip](https://github.com/qgis/QGIS/files/4035342/qgis_issue.zip)

**Comment by gioman** [comment]
@asgharibraheembaloch I cannot replicate on 3.10.1 Would you mind give it a try, also testing using on a new QGIS profile (no 3rd party plugins installed).

**Comment by asgharibraheembaloch** [comment]
> @asgharibraheembaloch I cannot replicate on 3.10.1 Would you mind give it a try, also testing using on a new QGIS profile (no 3rd party plugins installed).

ok @gioman i will try but i have tried it on QGIS 3.8.2-Zanzibar the error is same and found that after saving edits the rubber band snapping doesn't work for newly created segment

**Comment by gioman** [comment]
> ok @gioman i will try but i have tried it on QGIS 3.8.2-Zanzibar the error is same and found that after saving edits the rubber band snapping doesn't work for newly created segment

it maybe data dependent or project dependent, whith sample data of my own I can't replicate.

**Comment by asgharibraheembaloch** [comment]
> can't replicate

unable to understand the meaning here?

**Comment by asgharibraheembaloch** [comment]
> can't replicate.

i think you are saying that on my data it's work fine

**Comment by gioman** [comment]
> i think you are saying that on my data it's work fine

you didn't provided any project or data, so on *my* data it works as expected.

**Comment by asgharibraheembaloch** [comment]
@gioman this error comes only when our data (postgis road data in my example) is on remote server, it's work fine for local data whether it is shape file or local postgis database

**Comment by gioman** [comment]
> @gioman this error comes only when our data (postgis road data in my example) is on remote server, it's work fine for local data whether it is shape file or local postgis database

@asgharibraheembaloch I tested a remote server. Please try with a new QGIS profile, no 3rd party plugins installed.

**Comment by asgharibraheembaloch** [comment]
ok i will try

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
