### ISSUE TITLE
Error with plugin 'rastertool' 

### ISSUE THREAD

**Issue by Labros89** [qgis/QGIS#33662]
Hi Guys.

I am a new user of QGIS. In the past I used ArcGis. 

I download QGIS, I install it but I am facing a problem with python. Actually when I start the programm I get the following message "Python error: Couldn't load plugin 'rastertool' due to an error when calling its classFactory() method See message log (Python Error) for more details." 

I have tried a lot to fix it but I cannot find a way. I have observed that because of it I cannot use or execute raster tools/processes.

I really need your help how to fix it.

Thanks in advance

**Comment by luipir** [comment]
seems issue already open in the plugin traker https://github.com/aishwaryahegde29/RasterTool_Qgis/issues

please follow adding your comments there because is a third party plugin and not strictly a QGIS bug

regards

**Comment by Labros89** [comment]
Hi luipir, 

Thanks for the answer. However still it cannot be fixed. It might not be strictly a QGIS bug but it is part of QGIS for this reason I texted here.

Do you know better how can I fix it because I am still facing the problem.

Thanks

**Comment by Labros89** [comment]
I checked the link but the suggested code doesn't work

**Comment by gioman** [comment]
> Thanks for the answer. However still it cannot be fixed. It might not be strictly a QGIS bug but it is part of QGIS for this reason I texted here.

@Labros89 this is the bug tracker for QGIS as you get it after installing it. The tool you need is a 3rd party plugin and the QGIS developers have no control or responsibility whatsoever over it. In this cases you must get in touch with the authors of the extension.
