### ISSUE TITLE
 QGIS UNEXPECTEDLY ENDED 

### ISSUE THREAD

**Issue by Camille-34** [qgis/QGIS#33661]
## User Feedback

QGIS UNEXPECTEDLY ENDED 

Crash ID: 860ac4671a7fe68a8d188afd252d1cfc53852288 

QGIS crashes unexpectedly and almost systematically without being able to identify the reason.
 
Where does the problem come from ? 
What is the solution ? 

Thanks

Stack Trace

osgeo::proj::datum::Datum::conventionalRS :
osgeo::proj::datum::Datum::conventionalRS :
osgeo::proj::datum::Datum::conventionalRS :
OGRSpatialReference::~OGRSpatialReference :
OGRSpatialReference::operator= :
OGRGeomFieldDefn::~OGRGeomFieldDefn :
SHPWriteObject :
OGRFeatureDefn::~OGRFeatureDefn :
OGRFeatureDefn::~OGRFeatureDefn :
SHPWriteObject :
DBFWriteTuple :
OGREditableLayer::Translate :
CPLStringList::FindString :
selectWidget :
QMetaObject::activate :
QTimer::timerEvent :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32Private::sendTimerEvent :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.4.13-Madeira
QGIS code revision: 567300ccf1
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

## Report Details

*Crash ID*: 860ac4671a7fe68a8d188afd252d1cfc53852288

*Stack Trace*
<pre>
osgeo::proj::datum::Datum::conventionalRS :
osgeo::proj::datum::Datum::conventionalRS :
osgeo::proj::datum::Datum::conventionalRS :
OGRSpatialReference::~OGRSpatialReference :
OGRSpatialReference::operator= :
OGRGeomFieldDefn::~OGRGeomFieldDefn :
SHPWriteObject :
OGRFeatureDefn::~OGRFeatureDefn :
OGRFeatureDefn::~OGRFeatureDefn :
SHPWriteObject :
DBFWriteTuple :
OGREditableLayer::Translate :
CPLStringList::FindString :
selectWidget :
QMetaObject::activate :
QTimer::timerEvent :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32Private::sendTimerEvent :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.4.13-Madeira
QGIS code revision: 567300ccf1
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by Camille-34** [comment]
<img width="173" alt="QGis UNEXPECTEDLY ENDED" src="https://user-images.githubusercontent.com/59648024/71974267-60e9f680-3211-11ea-85a3-831c5db6ec54.PNG">

**Comment by luipir** [comment]
are you able to test with latest 3.10 "A Coruña" version?

**Comment by Camille-34** [comment]
I use the version : 3.4.13-Madeira. I will download and try with the latest version. 
I keep you informed. Thanks!

**Comment by gioman** [comment]
> I use the version : 3.4.13-Madeira

he meant update to the latest point release, 3.4.14 or 3.10.1

**Comment by nyalldawson** [comment]
Already fixed upstream in the gdal project

**Comment by Leoned** [comment]
I need help with the QGIS error, help me. My version of QGIS is 3.12, this situation is the same as the previous version 3.10
![Screenshot_1](https://user-images.githubusercontent.com/17074687/76255052-81d3c580-621b-11ea-8389-c9c92e02c9b4.png)

**Comment by roya0045** [comment]
> I need help with the QGIS error, help me. My version of QGIS is 3.12, this situation is the same as the previous version 3.10
> ![Screenshot_1](https://user-images.githubusercontent.com/17074687/76255052-81d3c580-621b-11ea-8389-c9c92e02c9b4.png)

This is probably related to the 300 views that you have open. You just hit the qt/qgis limit I guess.

**Comment by Leoned** [comment]
> > I use the version : 3.4.13-Madeira
> 
> he meant update to the latest point release, 3.4.14 or 3.10.1
it´is same in both version

**Comment by Leoned** [comment]
> > I need help with the QGIS error, help me. My version of QGIS is 3.12, this situation is the same as the previous version 3.10
> > ![Screenshot_1](https://user-images.githubusercontent.com/17074687/76255052-81d3c580-621b-11ea-8389-c9c92e02c9b4.png)
> 
> This is probably related to the 300 views that you have open. You just hit the qt/qgis limit I guess.

the images are google earth engine joined with qgis

**Comment by gioman** [comment]
> the images are google earth engine joined with qgis

@Leoned the problem is the **several** additional map canvases: it is very unusual to have that many open, and possibly you may have it a platform limitation.
