### ISSUE TITLE
qGIS 3.10 on macOs Catalina can't open Shapefiles anymore

### ISSUE THREAD

**Issue by vomc** [qgis/QGIS#33666]
**Describe the bug**
I have a folder that contains a SHP file (along with SHX, PRJ and DBF) (see image) and I would like to open the SHP file. This is something that I have done almost every other week using qGIS (before updating my mac to Catalina). It seems that now I can't open the files anymore because they are greyed out.

<img width="534" alt="Screenshot 2020-01-08 at 15 52 27" src="https://user-images.githubusercontent.com/78635/71987872-4292f380-322f-11ea-9fc3-2d40bd243663.png">

**How to Reproduce**

Install qGIS 3.10 on macOs catalina and download the ZIP file from here: https://www.dropbox.com/s/rfy2u3kne8k6td3/stenon-map.zip?dl=0 -- note that this ZIP contains the SHP, PRJ, DBF and SHX files. I was able to open these fine prior to updating last week

**QGIS and OS versions**

QGIS version | 3.10.1-A Coruña | QGIS code revision | 1e6b1a3eda
-- | -- | -- | --
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.28.0 | Running against SQLite | 3.28.0
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS 10.15
Active python plugins | LayerMetadataSearch; processing; db_manager; MetaSearch

macOs Catalina 10.15.2 (19C57)

**Comment by gioman** [comment]
@vomc 

clean QGIS 3.10.1 installation on Catalina:

![Screenshot 2020-01-08 at 15 10 59](https://user-images.githubusercontent.com/1951107/71992120-dadba900-322c-11ea-8979-2cb32f26d709.png)

**Comment by gioman** [comment]
![Screenshot 2020-01-08 at 15 47 59](https://user-images.githubusercontent.com/1951107/71993070-61dd5100-322e-11ea-8b51-4253618acfed.png)

**Comment by vomc** [comment]
interesting. going to try this again, will delete qGIS and do a clean installation now

**Comment by vomc** [comment]
@gioman any suggestions on what could be wrong? I just did a clean re-install and it is still not working. Is there something wrong with my computer?

re-downloaded it and verified

<img width="484" alt="Screenshot 2020-01-09 at 10 49 11" src="https://user-images.githubusercontent.com/78635/72057017-fc40a180-32cd-11ea-89ab-56a94ec713ba.png">

then got a few warnings but was able to open it

<img width="453" alt="Screenshot 2020-01-09 at 10 49 56" src="https://user-images.githubusercontent.com/78635/72057035-0498dc80-32ce-11ea-8077-eaca13af1488.png">

<img width="522" alt="Screenshot 2020-01-09 at 10 50 07" src="https://user-images.githubusercontent.com/78635/72057040-06fb3680-32ce-11ea-8fe7-4c1a726e8e38.png">

and then -- same thing -- the files are still greyed out:

<img width="537" alt="Screenshot 2020-01-09 at 10 50 37" src="https://user-images.githubusercontent.com/78635/72057058-0f537180-32ce-11ea-8193-b90059744674.png">

**Comment by vomc** [comment]
... going to try 3.4 to see if the LTS version works

**Comment by vomc** [comment]
hmm same issue even with 3.4 -- how do i get this to work? the only thing I can think of is that I have HD encryption running on my mac but other than that everything is standard

install
<img width="425" alt="Screenshot 2020-01-09 at 10 58 44" src="https://user-images.githubusercontent.com/78635/72058551-91449a00-32d0-11ea-963b-c715df42b2ce.png">

usual notices about verification

<img width="518" alt="Screenshot 2020-01-09 at 11 08 00" src="https://user-images.githubusercontent.com/78635/72058599-a91c1e00-32d0-11ea-9434-d4237081bd8a.png">

<img width="561" alt="Screenshot 2020-01-09 at 11 08 10" src="https://user-images.githubusercontent.com/78635/72058605-ab7e7800-32d0-11ea-9617-f95f45e61e72.png">

<img width="489" alt="Screenshot 2020-01-09 at 11 08 20" src="https://user-images.githubusercontent.com/78635/72058623-b33e1c80-32d0-11ea-88c2-9b188797abeb.png">

then i get asked about 'access' -- which i allow:

<img width="465" alt="Screenshot 2020-01-09 at 11 08 40" src="https://user-images.githubusercontent.com/78635/72058649-bd601b00-32d0-11ea-9ddd-351a7ac1de2c.png">

but still not working:

<img width="552" alt="Screenshot 2020-01-09 at 11 08 53" src="https://user-images.githubusercontent.com/78635/72058664-c2bd6580-32d0-11ea-8765-09d31036418f.png">

**Comment by vomc** [comment]
i was able to find a workaround which is to open them from the finder using a right-click. oddly for the very same files that open ok in qGIS this way if I do file > open from within the app they are still greyed out. 

also just double checked permissions and set to `read & write` for everyone....

works
<img width="626" alt="Screenshot 2020-01-09 at 11 39 09" src="https://user-images.githubusercontent.com/78635/72060937-35304480-32d5-11ea-9ce4-5e83c0f28c52.png">

in qGIS file > open they are still greyed out after permissions reset
<img width="511" alt="Screenshot 2020-01-09 at 11 39 21" src="https://user-images.githubusercontent.com/78635/72060958-3d887f80-32d5-11ea-8889-7fe5d023c192.png">

**Comment by vomc** [comment]
anyway, feel free to close this as I suppose it is pretty difficult to reproduce... i have found a workaround that is ok for the time being...

**Comment by gioman** [comment]
![Screenshot 2020-01-09 at 16 23 30](https://user-images.githubusercontent.com/1951107/72085142-b8b15c00-32fc-11ea-84a1-f61cd851e546.png)

on an encrypted disk.
