### ISSUE TITLE
QGIS 3.8.1 : Recurrent when actionning the "modification nodes" button

### ISSUE THREAD

**Issue by JMi31** [qgis/QGIS#33663]
## User Feedback

Hi,
For your information :
Recurrent crashes (but not systematic) when actioning the "modification nodes" button. Usually the "index calculation" pop up appears, here in this case it doesn't launch.
Did'nt happened with previous QGIS 3.6.0 version.

Cordially,

JMi31

## Report Details

*Crash ID*: 4f949b2cd7387c8641ddd602a877515b0d7683d1

*Stack Trace*
<pre>
QList<QItemSelectionRange>::size :
QTableView::paintEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::drawWidget :
QApplication::windowIcon :
QWidget::event :
QgisApp::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
QGraphicsScene::~QGraphicsScene :
QObject::event :
QGraphicsScene::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
TranslateMessageEx :
TranslateMessage :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.8.1-Zanzibar
QGIS code revision: dcd95cc648
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by gioman** [comment]
>  QGIS Version: 3.8.1-Zanzibar

@JMi31 please update to 3.10.1 and try again

**Comment by JMi31** [comment]
Thanks Gioman, it works, and the digitalization is stable since 2 days !
Happy new year to GitHub Team and contributors !
