### ISSUE TITLE
Duplicate and digitize record from table returns random record copied

### ISSUE THREAD

**Issue by jahpio** [qgis/QGIS#33665]
**Describe the bug**

duplicate and digitize returns wrong copy
![knipsel](https://user-images.githubusercontent.com/59652202/71981271-57b55580-3222-11ea-942a-68c5fe586cbc.JPG)

**How to Reproduce**
select shape file, open attributetable, right mouse on record -> duplicate and digitize -> point on map and see a different reccord is copied

**QGIS and OS versions**
qgis 3.10.1 on win10home

**Additional context**

**Comment by roya0045** [comment]
Could be also related to the changes made in https://github.com/qgis/QGIS/commit/39082474e79b6146d7b268332e5c574ff18d379e ?

**Comment by roya0045** [comment]
I confirm that its not fixed again in master, not sure if something changed in the meantime.

**Comment by roya0045** [comment]
@gioman could you reopen this. I'll try to refix this but I can't provide any guaranty.

**Comment by gioman** [comment]
> @gioman could you reopen this. I'll try to refix this but I can't provide any guaranty.

@roya0045 done
