### ISSUE TITLE
Merge Raster Layers Not Working

### ISSUE THREAD

**Issue by housepig83** [qgis/QGIS#33677]
Hi, 
I tried to merge a few raster layers (.tiff)using the "GDAL>Raster miscellaneous>Merge" function
 in QGIS3.10 but it shows me the below error messages. It used to work fine but now it doesn't. Some of the error messages say "No module named gdal_merge"

I have uninstalled and reinstalled the software but still got me the same problem. 

can someone help? thanks!

**Error Messages:**
QGIS version: 3.10.1-A Coruña
QGIS code revision: ef24c526da
Qt version: 5.11.2
GDAL version: 3.0.2
GEOS version: 3.8.0-CAPI-1.13.1 
PROJ version: Rel. 6.2.1, November 1st, 2019
Processing algorithm…
Algorithm 'Merge' starting…
Input parameters:
{ 'DATA_TYPE' : 5, 'EXTRA' : '', 'INPUT' : ['G:/My Drive/CWR - Shared/GIS/2019 Cap Threat/Singapore/n01_e103_1arc_v3.tif','G:/My Drive/CWR - Shared/GIS/2019 Cap Threat/Singapore/n01_e104_1arc_v3.tif'], 'NODATA_INPUT' : None, 'NODATA_OUTPUT' : None, 'OPTIONS' : '', 'OUTPUT' : 'TEMPORARY_OUTPUT', 'PCT' : False, 'SEPARATE' : False }

GDAL command:
python3 -m gdal_merge -ot Float32 -of GTiff -o C:/Users/ctl/AppData/Local/Temp/processing_e39c4d5bce7c4fa1a94c9959d9b93a82/processing_fc89f93751fa4b358818b4336347446c/9ba8cc375add404782484a2f22c0193c/OUTPUT.tif --optfile C:/Users/ctl/AppData/Local/Temp/processing_e39c4d5bce7c4fa1a94c9959d9b93a82/processing_fc89f93751fa4b358818b4336347446c/f645098a993c499f992b9e2901e01897/mergeInputFiles.txt
GDAL command output:
D:\QGIS\bin\python3.exe: No module named gdal_merge

Execution completed in 0.15 seconds
Results:
{'OUTPUT': 'C:/Users/ctl/AppData/Local/Temp/processing_e39c4d5bce7c4fa1a94c9959d9b93a82/processing_fc89f93751fa4b358818b4336347446c/9ba8cc375add404782484a2f22c0193c/OUTPUT.tif'}

Loading resulting layers
The following layers were not correctly generated.<ul><li>C:/Users/ctl/AppData/Local/Temp/processing_e39c4d5bce7c4fa1a94c9959d9b93a82/processing_fc89f93751fa4b358818b4336347446c/9ba8cc375add404782484a2f22c0193c/OUTPUT.tif</li></ul>You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.

**Comment by alexbruy** [comment]
This should be already fixed in master and nightly builds. Try to reinstall QGIS using nightly build or "dev" package from OSGeo4W

**Comment by agiudiceandrea** [comment]
It's a dupicate of https://github.com/qgis/QGIS/issues/33386 and other similar recent bug reprts.

@housepig83 to fix the issue on Windows, you could update python3-core package to 3.7.0-4 version via OSGeo4W setup, or you could try to workaround the bug: see https://github.com/qgis/QGIS/issues/33386#issuecomment-569140502

**Comment by housepig83** [comment]
> It's a dupicate of #33386 and other similar recent bug reports.
> 
> @housepig83 to fix the issue on Windows, you could update python3-core package to 3.7.0-4 version via OSGeo4W setup, or you could try to workaround the bug: see [#33386 (comment)](https://github.com/qgis/QGIS/issues/33386#issuecomment-569140502)



> This should be already fixed in master and nightly builds. Try to reinstall QGIS using nightly build or "dev" package from OSGeo4W

Thanks! Solved !
