### ISSUE TITLE
WFS Switching BBOX X & Y and sending bad request

### ISSUE THREAD

**Issue by someone191** [qgis/QGIS#33673]
**Describe the bug**

QGIS is sending a bad request to WFS server. I am getting the following error message:

2020-01-08T15:06:00     CRITICAL    Layer Soil Mapunit Polygon : Download of features for layer mapunitpoly failed or partially failed: Download of features failed: Error transferring https://sdmdataaccess.sc.egov.usda.gov/Spatial/SDMWGS84GEOGRAPHIC.wfs?SERVICE=WFS&REQUEST=GetFeature&VERSION=1.1.0&TYPENAME=mapunitpoly&SRSNAME=urn:ogc:def:crs:EPSG::4326&BBOX=35.52551273180824154,-120.17369005225681633,35.70981609974859339,-119.82296349386254519,urn:ogc:def:crs:EPSG::4326 - server replied: Bad Request. You may attempt reloading the layer with F5

I contacted the sdmdataaccess.sc.egov.usda.gov and according to them, the request is bad because:
it is switching X&Y parameters, SRS should have been defined for both the bounding box and for the output, and coordinate pairs are separated by a space instead of another comma

**How to Reproduce**

1. Add following WFS https://sdmdataaccess.sc.egov.usda.gov/Spatial/SDMWGS84Geographic.wfs

**QGIS and OS versions**

QGIS version
3.4.13-Madeira
QGIS code revision
QGIS code revision
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.2
Running against GDAL/OGR
3.0.2
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.2.1
Running against PROJ
Rel. 6.2.1, November 1st, 2019
Active python plugins
profiletool; 
StreetView; 
valuetool; 
db_manager; 
MetaSearch; 
processing

**Additional context**

Email Discussion with sdmdataaccess.sc.egov.usda.gov

"BBOX should be minX, minY, maxX, maxY. The Y coordinates must fall between -90 and 90 degrees and cannot exceed a certain number of square kilometers or they will exceed the limits set on the database server.

For example, a location in California.
-122.5,37.3,-122.0,38.6"

**Comment by roya0045** [comment]
> **Describe the bug**
> 
> QGIS is sending a bad request to WFS server. I am getting the following error message:
> 
> 2020-01-08T15:06:00 CRITICAL Layer Soil Mapunit Polygon : Download of features for layer mapunitpoly failed or partially failed: Download of features failed: Error transferring https://sdmdataaccess.sc.egov.usda.gov/Spatial/SDMWGS84GEOGRAPHIC.wfs?SERVICE=WFS&REQUEST=GetFeature&VERSION=1.1.0&TYPENAME=mapunitpoly&SRSNAME=urn:ogc:def:crs:EPSG::4326&BBOX=35.52551273180824154,-120.17369005225681633,35.70981609974859339,-119.82296349386254519,urn:ogc:def:crs:EPSG::4326 - server replied: Bad Request. You may attempt reloading the layer with F5
> 
> I contacted the sdmdataaccess.sc.egov.usda.gov and according to them, the request is bad because:
> it is switching X&Y parameters, SRS should have been defined for both the bounding box and for the output, and coordinate pairs are separated by a space instead of another comma
> 
> **How to Reproduce**
> 
> 1. Add following WFS https://sdmdataaccess.sc.egov.usda.gov/Spatial/SDMWGS84Geographic.wfs
> 
> **QGIS and OS versions**
> 
> **Additional context**
> 
> Email Discussion with sdmdataaccess.sc.egov.usda.gov
> 
> "BBOX should be minX, minY, maxX, maxY. The Y coordinates must fall between -90 and 90 degrees and cannot exceed a certain number of square kilometers or they will exceed the limits set on the database server.
> 
> For example, a location in California.
> -122.5,37.3,-122.0,38.6"

So their server is not truly in EPSG::4326 ?

**Comment by someone191** [comment]
Yes it is valid with 3.10.0 as well.

2020-01-08T18:01:06     CRITICAL    Layer Soil Mapunit Polygon With Extended Attributes : Download of features for layer mapunitpolyextended failed or partially failed: Download of features failed: Error transferring https://sdmdataaccess.sc.egov.usda.gov/Spatial/SDMWGS84GEOGRAPHIC.wfs?SERVICE=WFS&REQUEST=GetFeature&VERSION=1.1.0&TYPENAME=mapunitpolyextended&SRSNAME=urn:ogc:def:crs:EPSG::4326&BBOX=-0.01672381010087618,-0.00098539847715968,0.01044122899920138,0.01328956324601833,urn:ogc:def:crs:EPSG::4326 - server replied: Bad Request. You may attempt reloading the layer with F5

**Comment by nyalldawson** [comment]
Can you access this server using the ogr command line tools? My gut feeling is that this is a still a server misconfiguration issue...

**Comment by someone191** [comment]
@nyalldawson I am not knowledgable on using OGR command line.

**Comment by rduivenvoorde** [comment]
I played a little with this server (by using a QGIS (master, GDAL 2.4.3), compiled in debug mode, so I could see the WFS requests fired, and then firing the requests in a browser window or curl).

My conclusions: standards are difficult, all parties (QGIS, GDAL, usda, OGC) are messing up :-)

To start: the way a bbox is supposed to be used in WFS requests is VERY wfs-version dependent. For example: look what Geoserver is trying to conclude:
https://docs.geoserver.org/latest/en/user/services/wfs/axis_order.html
But in the end that does NOT be the problem though..

QGIS: (or gdal? @rouault ) is nowadays apparently always using the urn-notation for crs's: 
urn:ogc:def:crs:EPSG::4326 
but BOTH in the SRSNAME-parameter and in the BBO parameter

https://sdmdataaccess.sc.egov.usda.gov/Spatial/SDMWGS84GEOGRAPHIC.wfs?SERVICE=WFS&REQUEST=GetFeature&VERSION=1.1.0&TYPENAME=mapunitpoly&SRSNAME=urn:ogc:def:crs:EPSG::4326&BBOX=-140.21129999999999427,-189,133.8387000000000171,189,urn:ogc:def:crs:EPSG::4326

Apparently, USDA wfs server is an older instance, for instance can only do WFS 1.1.0 and NOT handle the urn notation, nor as SRSNAME, nor in the BBOX parameter: 

Error: parameter "srsname" requires a value from the list ("EPSG:4326","EPSG:3857","EPSG:42659").

Error getting BBOX and extent area from WFS request string (shorthand BBOX filter)  - invalid Bounding Box coordinate format (shorthand BBOX).

Then another observation: QGIS loading  a world map zooming out so you see the whole world, then firing a getfeature request to the wfs server:
As you see in the request above (taken from debug info of QGIS): QGIS is requesting a bbox:
-140.21129999999999427,-189,133.8387000000000171,189,urn:ogc:def:crs:EPSG::4326
so in short: -140, -189, 133, 189 

Server rightfully returns: "Error getting BBOX extent area from WFS request string 24201: Latitude values must be between -90 and 90 degrees." I think?

But for example (all in browser) trying:

https://sdmdataaccess.sc.egov.usda.gov/Spatial/SDMWGS84GEOGRAPHIC.wfs?SERVICE=WFS&REQUEST=GetFeature&VERSION=1.1.0&TYPENAME=mapunitpoly&SRSNAME=EPSG:4326&BBOX=-122.72548527115587547,35.93863911088143226,-120.07577775884060145,37.85967705731000166

BBOX area (50344843114.6714 square meters) exceeds the limit of 10100000000 square meters

Fixing epsg notation:

https://sdmdataaccess.sc.egov.usda.gov/Spatial/SDMWGS84GEOGRAPHIC.wfs?SERVICE=WFS&REQUEST=GetFeature&VERSION=1.1.0&TYPENAME=mapunitpoly&SRSNAME=EPSG:4326&BBOX=-122.72548527115587547,35.93863911088143226,-120.07577775884060145,37.85967705731000166

Finally OK:

https://sdmdataaccess.sc.egov.usda.gov/Spatial/SDMWGS84GEOGRAPHIC.wfs?SERVICE=WFS&REQUEST=GetFeature&VERSION=1.1.0&TYPENAME=mapunitpoly&SRSNAME=EPSG:4326&BBOX=-121.9246584917641627,36.86446939088204289,-121.60054248356131268,37.09945349682910631

So either the USDA service needs to be ok with the urn notation in de srsparameter AND QGIS should not append it to the bbox
OR QGIS should not add it to the bbox and have a checkbox to choose between urn and EPSG:xxxx notation for crs's

Conclusion: while both are 'standard'-compliant, this server and client cannot talk to each other, unless both work together to fix. Best would be if USDA uses a newer WFS-server implementation: Geoserver, QGIS, Mapserver? So we all can speak WFS 1.3.0 (which has paging).

Or even better: do WFS3 (aka OGC API - Features, see https://github.com/opengeospatial/ogcapi-features).

**Comment by roya0045** [comment]
@rduivenvoorde Could there be some way to first test the request format and then save the format for a given source?

The request can have a lot of formatting and I'm wondering if invalid requests could iterate through a list of permutations until a good one is found and save that formatting information. If we have formatting flags/qmap like "alternate dims", "bbox arg", etc. I assumed that there was already something to that effect.

Otherwise it seems like we are hoping that all servers will only be up to date and use the same standard while we see an explosion of 'outdated' or alternate standards used.

**Comment by someone191** [comment]
If I use @rduivenvoorde link to download file from QGIS download file tool, the downloaded file will be at wrong spatial location, I have to run swap X and Y tool to get it to correct spatial location

https://sdmdataaccess.sc.egov.usda.gov/Spatial/SDMWGS84GEOGRAPHIC.wfs?SERVICE=WFS&REQUEST=GetFeature&VERSION=1.1.0&TYPENAME=mapunitpoly&SRSNAME=EPSG:4326&BBOX=-121.9246584917641627,36.86446939088204289,-121.60054248356131268,37.09945349682910631

**Comment by gioman** [comment]
```
giovanni@sibirica:~$ ogrinfo -so WFS:https://sdmdataaccess.sc.egov.usda.gov/Spatial/SDMWGS84Geographic.wfs
ERROR 1: Server is read-only WFS; no WFS-T feature advertized
Had to open data source read-only.
INFO: Open of `WFS:https://sdmdataaccess.sc.egov.usda.gov/Spatial/SDMWGS84Geographic.wfs'
      using driver `WFS' successful.
Metadata:
  ABSTRACT=NRCS SSURGO Soils web feature service in WGS84 geographic. This is an Open GIS Consortium standard Web Feature Service (WFS).
  PROVIDER_NAME=National Soil Survey Center, NRCS, USDA
  TITLE=NRCS Soil Data Mart Data Access Web Feature Service WGS84
1: mapunitpoly (Multi Polygon)
2: mapunitline (Multi Line String)
3: mapunitpoint (Multi Point)
4: mapunitpolyextended (Multi Polygon)
5: mapunitlineextended (Multi Line String)
6: mapunitpointextended (Multi Point)
7: mapunitpolythematic (Multi Polygon)
ERROR 1: HTTP error code : 400
ERROR 1: Error returned by server : HTTP error code : 400 (0)
8: mapunitlinethematic
ERROR 1: HTTP error code : 400
ERROR 1: Error returned by server : HTTP error code : 400 (0)
9: mapunitpointthematic
10: surveyareapoly (Multi Polygon)
11: surveyareapolytransparent (Multi Polygon)
12: surveyareapolyoutline (Multi Polygon)
ERROR 1: HTTP error code : 400
ERROR 1: Error returned by server : HTTP error code : 400 (0)
13: featline
ERROR 1: HTTP error code : 400
ERROR 1: Error returned by server : HTTP error code : 400 (0)
14: featpoint
15: aoi (Multi Polygon)
16: aoihatched (Multi Polygon)
17: aoilabeled (Multi Polygon)
```

```
giovanni@sibirica:~$ ogr2ogr -progress -f GPKG test.gpkg WFS:https://sdmdataaccess.sc.egov.usda.gov/Spatial/SDMWGS84Geographic.wfs
Warning 6: Progress turned off as fast feature count is not available.
ERROR 1: HTTP error code : 400
ERROR 1: Error returned by server : HTTP error code : 400 (0)
ERROR 1: HTTP error code : 400
ERROR 1: Error returned by server : HTTP error code : 400 (0)
ERROR 1: HTTP error code : 400
ERROR 1: Error returned by server : HTTP error code : 400 (0)
ERROR 1: HTTP error code : 400
ERROR 1: Error returned by server : HTTP error code : 400 (0)
ERROR 1: HTTP error code : 400
ERROR 1: Error returned by server : HTTP error code : 400 (0)
ERROR 1: HTTP error code : 400
ERROR 1: Error returned by server : HTTP error code : 400 (0)
ERROR 1: HTTP error code : 400
ERROR 1: Error returned by server : HTTP error code : 400 (0)
ERROR 1: HTTP error code : 400
ERROR 1: Error returned by server : HTTP error code : 400 (0)
ERROR 1: HTTP error code : 400
ERROR 1: Error returned by server : HTTP error code : 400 (0)
ERROR 1: HTTP error code : 400
ERROR 1: Error returned by server : HTTP error code : 400 (0)
ERROR 1: HTTP error code : 400
ERROR 1: Error returned by server : HTTP error code : 400 (0)
ERROR 1: HTTP error code : 400
ERROR 1: Error returned by server : HTTP error code : 400 (0)
ERROR 1: HTTP error code : 400
ERROR 1: Error returned by server : HTTP error code : 400 (0)
ERROR 1: HTTP error code : 400
ERROR 1: Error returned by server : HTTP error code : 400 (0)
ERROR 1: HTTP error code : 400
ERROR 1: Error returned by server : HTTP error code : 400 (0)
ERROR 1: HTTP error code : 400
ERROR 1: Error returned by server : HTTP error code : 400 (0)
ERROR 1: HTTP error code : 400
ERROR 1: Error returned by server : HTTP error code : 400 (0)
ERROR 1: HTTP error code : 400
ERROR 1: Error returned by server : HTTP error code : 400 (0)
ERROR 1: HTTP error code : 400
ERROR 1: Error returned by server : HTTP error code : 400 (0)
ERROR 1: HTTP error code : 400
ERROR 1: Error returned by server : HTTP error code : 400 (0)
ERROR 1: HTTP error code : 400
ERROR 1: Error returned by server : HTTP error code : 400 (0)
```

**Comment by gioman** [comment]
Is this really a QGIS issue? the server seems to have several issues...

**Comment by roya0045** [comment]
@gioman The 400 error are possibly due to 'bad' requests, I don't think those are distinct issues.

**Comment by someone191** [comment]
Do we have any final conclusion on this?

**Comment by roya0045** [comment]
> So either the USDA service needs to be ok with the urn notation in de srsparameter AND QGIS should not append it to the bbox
> OR QGIS should not add it to the bbox and have a checkbox to choose between urn and EPSG:xxxx notation for crs's
> 
> Conclusion: while both are 'standard'-compliant, this server and client cannot talk to each other, unless both work together to fix. Best would be if USDA uses a newer WFS-server implementation: Geoserver, QGIS, Mapserver? So we all can speak WFS 1.3.0 (which has paging).
> 
> Or even better: do WFS3 (aka OGC API - Features, see https://github.com/opengeospatial/ogcapi-features).

@someone191 pretty much that.

**Comment by roya0045** [comment]
@someone191 you could make a feature request regarding the things mentioned by @rduivenvoorde

**Comment by rouault** [comment]
The server is definitely not compliant, and their analysis is wrong ("the request is bad because:
it is switching X&Y parameters"). In WFS 1.1.0, EPSG axis order must be honoured and for geographic CRS, this order is X=lat, Y=long, how arguable it is. But it has been decided that it would be like that more than 10 years ago. It should also support the urn: syntax, especially as it does advertize <DefaultSRS>urn:ogc:def:crs:EPSG::4326</DefaultSRS> in its response to https://sdmdataaccess.sc.egov.usda.gov/Spatial/SDMWGS84GEOGRAPHIC.wfs?SERVICE=WFS&REQUEST=GetCapabilities
