### ISSUE TITLE
WFS inputs are not supported in OGR based tools on WIndows

### ISSUE THREAD

**Issue by pathmapper** [qgis/QGIS#33684]
**Describe the bug**
On Windows, the processing tool from the processing toolbox `Clip Vector by Extent` is not working with a WFS vector layer as input layer. It fails with: _ERROR 1: No schema information loaded_

**How to Reproduce**

1. Open [sample_project.zip](https://github.com/qgis/QGIS/files/4039714/sample_project.zip)
2. Use the tool "Clip vector by extent" from the processing toolbox with _ave_GebaeudeBauwerk_ as input layer, Canvas Extent as clipping extent and save to tempory file:

![settings](https://user-images.githubusercontent.com/20856381/72057462-c05a0c00-32ce-11ea-88c7-2b49e27e4810.PNG)

3. See error: _ERROR 1: No schema information loaded_

![error](https://user-images.githubusercontent.com/20856381/72057237-593c5780-32ce-11ea-9250-057cf04ded2e.png)

**QGIS and OS versions**

QGIS version | 3.10.1-A Coruña | QGIS code revision | ef24c526da
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.2 | Running against GDAL/OGR | 3.0.2
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.2.1 | Running against PROJ | Rel. 6.2.1, November 1st, 2019
OS Version | Windows 10 (10.0)
Active python plugins | canvas_clipper; db_manager; MetaSearch; processing

**Additional context**

On Linux this is working fine.

With a vector layer which is having a Shapefile source this is working also fine.

**Comment by nirvn** [comment]
@pathmapper , use QGIS' native 'Extract/clip by extent' algorithm.

**Comment by pathmapper** [comment]
@nirvn thanks a lot, this is indeed a good replacement.

**Comment by gioman** [comment]
> @nirvn thanks a lot, this is indeed a good replacement.

@pathmapper open a feature request to ask improve support of WFS inputs in OGR based tools.

**Comment by pathmapper** [comment]
@gioman as mentioned, on Linux it is supported. So I assumed this is a bug specific to the Windows platform.

Do you still think this is a feature request instead of a bug? If yes, should I open the request here on the same issue tracker?

**Comment by gioman** [comment]
> @gioman as mentioned, on Linux it is supported. So I assumed this is a bug specific to the Windows platform.

Oh I see...

**Comment by alexbruy** [comment]
Does it works from the command-line?

**Comment by pathmapper** [comment]
@alexbruy yes, from the OSgeo4W Shell it is working on Windows. 
Used the same command as shown in the `Clip Vector by Extent` tool settings dialogue:

`ogr2ogr -spat 315896.592291821 5690818.948608233 316825.6439050988 5690129.2845272105 -clipsrc spat_extent C:/Users/user/AppData/Local/Temp/processing_7b50816dd8e2496bae77dc615a537822/processing_1ae9b03bf1ce44798bd7ba3c2c8ee0e1/406c4f161b514c3999353b2a34d2490e/OUTPUT.gpkg WFS:https://www.wfs.nrw.de/geobasis/wfs_nw_alkis_vereinfacht ave:GebaeudeBauwerk -f "GPKG"`

![grafik](https://user-images.githubusercontent.com/20856381/72202576-663d8000-3461-11ea-9fe7-6cc73c818f28.png)

![grafik](https://user-images.githubusercontent.com/20856381/72202613-dea44100-3461-11ea-8e6e-b58878dce5fc.png)

**Comment by rouault** [comment]
It seems that for some reason the OGR NAS driver kicks in (through the use of the OGR WFS driver) instead of the GML one

**Comment by pathmapper** [comment]
This issue is not reproducible anymore with `3.16.0` :tada:
