### ISSUE TITLE
Missing Recent Projects on Start up v3.10

### ISSUE THREAD

**Issue by david-laverty** [qgis/QGIS#33718]
Since QGIS 3.10 the recent projects tab on the start up screen has disappeared for me. 

![image](https://user-images.githubusercontent.com/48278498/72144150-f27f7280-338f-11ea-8fe6-dd87c832dd5c.png)

I have experienced this on all versions of 3.10 I have tried. including the latest nightly builds. 

The start screen now has a Project Templates tab instead. Is this intentional or do I have to check a box somewhere to get recent projects to return?

Version 3.8 still has the recent project tab on my machine. 

Running QGIS 3.10 on Windows 10

**Comment by gioman** [comment]
@david-laverty check if you have

Settings -> Options -> General -> welcome page

**Comment by david-laverty** [comment]
It is there and set to welcome page, but no recent projects tab. 
![image](https://user-images.githubusercontent.com/48278498/72241085-c8bb8b00-35dd-11ea-9d34-d5c1315b78ce.png)
If changed to most recent it does open the most recent workspace I have accessed so it does know of recent jobs. It just isnt displaying them on the welcome page at start up.

**Comment by cesarcorreo** [comment]
Same problem as me. On my QGIS 3.4 works fine but not in 3.10. 
Settings -> Options -> General -> welcome page Are the same in the two versions

**Comment by roya0045** [comment]
@david-laverty  @cesarcorreo what are your screen resolution by hazard?

**Comment by nyalldawson** [comment]
Try this:

![Peek 2020-01-14 08-39](https://user-images.githubusercontent.com/1829991/72298294-734cb000-36a9-11ea-87e0-fa885c996649.gif)

**Comment by david-laverty** [comment]
what do u mean? would that affect the recent jobs tab being missing? I can check for you in the morning when I'm in the office. does screen resolution affect that? even it works on older 3.8 version without problem?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by roya0045** [comment]
@david-laverty if the news tab has a minimum size it could overlap on the recent project tab, as demonstrated by Nyall's gif. Otherwise I'm not too sure what could have caused one to overlap the other randomly otherwise.

**Comment by david-laverty** [comment]
will check this out in the morning. Hopefully it's as simple as this. Cant believe I didnt notice the arrows to pull over like that. will let u guys know soon as I try it



Sent from my Samsung Galaxy smartphone.



-------- Original message --------

**Comment by david-laverty** [comment]
This was my problem. the recent projects tab was hidden behind the news tab. Dragging it over revealed the recent projects tab hidden below it. Thanks very much for showing me this. Much appreciated Nyall

**Comment by cesarcorreo** [comment]
Thats carzy :DDDD

It was also my problem.
Thanks a lot
*________________*


*César Herrera Lindo <http://www.cesarpagina.com>*

**Comment by chucklepie** [comment]
I raised a bug (as I never saw this), and this was my solution. But this is a brand new install and I've never touched anything, so 'out of the box' it was like this.

I think this should be added to the list of bug/feature requests as from a UI/UX point of view there is no indication a pane is completely hidden and from a bug point of view recent projects shouldn't be a hidden pane on installation.

**Comment by Jakob-Lanstorp** [comment]
This issue is still the case in QGIS 3.14.16-Pi after a new clean install. When you first time (after an install) drag and drop the border QGIS remembers setting until you make a clean (delete QGIS and related user folders) install QGIS install where you have to due it once again. Also perhaps the Setting > Options > General will be better off letting you pick for the checklist what you want on the welcome page of the three choices: Recent Projects, News, Project Templates.

**Comment by tomtor** [comment]
@david-laverty You closed this issue, but current QGIS master still has this issue.

It effects every clean QGIS installation, so I suggest reopening it.

**Comment by roya0045** [comment]
@tomtor see Nyall's answer

**Comment by tomtor** [comment]
> see Nyall's answer

@roya0045 I did, but that describes a manual recover action, not a source fix.

A new QGIS user might never discover the hidden recent projects list.

**Comment by roya0045** [comment]
I agree and have raised this issue previously also. I feel like a fix shouldn't be too hard.

**Comment by tomtor** [comment]
The current implementation is surprising in other ways:

After opening your first project:

![image](https://user-images.githubusercontent.com/1104260/102712741-a210d480-42c3-11eb-9b72-0be895a3b4ce.png)

after restart we have to manually resize one time to make it visible again, like explained in https://github.com/qgis/QGIS/issues/33718#issuecomment-573907204

But when we delete the project from the list with the right mouse button the interface is shown as:

![image](https://user-images.githubusercontent.com/1104260/102712865-64607b80-42c4-11eb-81e1-db0eb4bddcab.png)

which is not very elegant.

Removing `void QgsWelcomePage::updateRecentProjectsVisibility()` completely fixes these issues.

I will create a PR.

**Comment by roya0045** [comment]
@tomtor if you plan on doing a PR I would also suggest adding some logic to move the news feed to half the screen if there are now recent projects. @nyalldawson any objection to exposing the recent projects once there are some?

**Comment by tomtor** [comment]
> if you plan on doing a PR I would also suggest adding some logic to move the news feed to half the screen if there are now recent projects.

The PR will default to half the screen for both News and Projects, until a user manually resizes (or hides) either of them.
