### ISSUE TITLE
PyQGIS gdal:gdal2xyz processing tool produces incomplete output for sdat grid files

### ISSUE THREAD

**Issue by ottadini** [qgis/QGIS#33714]
**Describe the bug**

Using PyQGIS to automate QGIS version 3.8.0 from OSGEO4W64, running the gdal:gdal2xyz tool on a temporary file produced by another processing tool (for example saga:lsfactor) results in incomplete output, whereas grass7:r.out.xyz works as expected. (Temporary grid files created by SAGA tools are in the .sdat file format).

**How to Reproduce**

See gist for scripts and screenshots of the problem: https://gist.github.com/ottadini/4c7450051ae4895866c3d7c5ba69f28c

**QGIS and OS versions**

QGIS version | 3.8.0-Zanzibar | QGIS code revision | 11aff65f10
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.0 | Running against GEOS | 3.7.2-CAPI-1.11.0 b55d2125
PostgreSQL Client Version | 9.2.4 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Windows 10 (10.0) |   |  

**Additional context**

**Comment by alexbruy** [comment]
Does running gdal2xyz directly from the command-line produce same results? Also please share test data

**Comment by alexbruy** [comment]
Closed for the lack of feedback. Please reopen if necessary.
