### ISSUE TITLE
Ability to shoose rotation basepoint(Advanced digiticing toolbar)

### ISSUE THREAD

**Issue by APOS80** [qgis/QGIS#33712]
**Feature description.**
The ability to shoose rotation basepoint(Advanced digiticing toolbar).
As of now its seems to be object center always.

**Comment by DelazJ** [comment]
@APOS80 This is already possible, I think: https://docs.qgis.org/3.4/en/docs/user_manual/working_with_vector/editing_geometry_attributes.html#rotate-feature-s

**Comment by uclaros** [comment]
Yes, it is there, you can ctrl+click to set the rotation center, but what is missing is the ability to snap and use the advanced digitizing tools for both setting the center and the angle of rotation. This would make perfectly aligning two geometries possible!

**Comment by DelazJ** [comment]
@uclaros see #33353 or #26936?

**Comment by gioman** [comment]
> Yes, it is there, you can ctrl+click to set the rotation center, but what is missing is the ability to snap and use the advanced digitizing tools for both setting the center and the angle of rotation. This would make perfectly aligning two geometries possible!

Closing as the functionality is already implemented. About the snapping there are already other tickets.
