### ISSUE TITLE
GEORSS doesn't work on windows

### ISSUE THREAD

**Issue by rpispico** [qgis/QGIS#33713]
Hi all, 
I tried to open a GEORSS file as explained in [0] on QGIS 3.4.3 and 3.10.1 on window 10 but it doesn't work.

The same test on Ubuntu 18.04 e QGIS 3.10.1 works fine.

[0] https://gis.stackexchange.com/questions/318725/use-of-usgs-georss-in-qgis/318735#318735

**Comment by gioman** [comment]
> I tried to open a GEORSS file as explained in [0] on QGIS 3.4.3 and 3.10.1 on window 10 but it doesn't work.

@rpispico this https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_hour.geojson works just fine here on the latest 3.4 and 3.10 on Windows.

**Comment by gioman** [comment]
@rpispico if the above is not the URL/Dataset to test please add/link it here.

**Comment by Pedro-Murteira** [comment]
This seems to work alright with this dataset >https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_hour.geojson
(Tested on Windows 10/QGIS 3.22.3.)
