### ISSUE TITLE
Trouble with closing qgis

### ISSUE THREAD

**Issue by vincentdulout** [qgis/QGIS#33724]
## User Feedback

I have a large amount of composer with heavy satelite photo.

Moreover the project did not save all the modification trough the unexpectedly ending.

## Report Details

*Crash ID*: cf0ee4dcc0c4b8820068b444e3b74d192b0d94e6

*Stack Trace*
<pre>
osgeo::proj::datum::Datum::conventionalRS :
osgeo::proj::datum::Datum::conventionalRS :
osgeo::proj::datum::Datum::conventionalRS :
OGRSpatialReference::~OGRSpatialReference :
OGRSpatialReference::operator= :
GDALDataset::~GDALDataset :
ECWDataset::~ECWDataset :
NCS::SDK::CStats::CRaw64Value::operator-= :
QgsRasterPipe::~QgsRasterPipe :
QgsRasterLayer::~QgsRasterLayer :
QgsMeshDatasetIndex::operator= :
QgsMapLayerStore::removeMapLayers :
QgsMapLayerStore::removeMapLayers :
QgsMapLayerStore::removeAllMapLayers :
QgsProject::clear :
QgisApp::closeProject :
QgisApp::fileExit :
QWidget::event :
QgisApp::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::close_helper :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processCloseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.4.13-Madeira
QGIS code revision: 567300ccf1
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by roya0045** [comment]
There are many duplicates ticket about this and this issue should be fixed. Either in the current or next point release.

**Comment by vincentdulout** [comment]
So great !

**Comment by gioman** [comment]
> So great !

@vincentdulout please update to 3.4.14 and test if it still happens.

**Comment by vincentdulout** [comment]
@gioman, yes it is.

**Comment by gioman** [comment]
> @gioman, yes it is.

@vincentdulout have you tried with a new QGIS profile (no 3rd party plugins installed)?

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
