### ISSUE TITLE
Editing non-spatial tables is broken

### ISSUE THREAD

**Issue by saberraz** [qgis/QGIS#33723]
I am trying to add a record to a non-spatial table (geopackage). But it is completely broken. Every time I apply changes, it resets the values.
![non-spatial-table](https://user-images.githubusercontent.com/2649047/72146565-a97ded00-3394-11ea-91b5-d571a1564757.gif)

**Comment by m-kuhn** [comment]
Which QGIS version(s) is/are affected?

**Comment by DelazJ** [comment]
@saberraz any reason you are trying to do multi edit while there's no (selected) features in your layer. should you  not hit the "add feature" button, instead?

**Comment by saberraz** [comment]
Ahhhh...thanks @DelazJ ...my bad. I seem to remember to button for a single feature was there!
