### ISSUE TITLE
QGIS crashes when opening layout, after PYQGIS script

### ISSUE THREAD

**Issue by davidlgalt** [qgis/QGIS#33738]
I created a script to automate map creation in QGIS. It works, but after it runs it causes the project to become unstable crashing during various types of operations, but especially when attempting to open a layout. I have resisted posting a bug for this before, because there are so many moving parts, but maybe someone can spot something in the stack trace?

## User Feedback

Opening a layout, after modifying multiple layouts in the project with PYQGIS.

Operations:

- Performed varous operations on the layers inclding dissolve, merge, extract and spatial joins
- Removed layers from the project
- Looped through layout elements and modified them to match the elements in a specified layout
- Created and modified raster layers using Rasterize (GDAL) processing tool and Gaussian filter
- Turned on and off multiple layers visibility
- Modified Legend title and added layer to legend
- Used setMapLayers to specify differnt set of layers for each layout
- Exported multiple PDFs 

Also, if I save the project and then reopen it, then I can open layouts or perform other operations without causing a crash.

Is there some resources that I need to flush after running PYQGIS scripts?

## Report Details

**Crash ID**: [4bd91351603b1b7f6a5fe76faf3841e357933017]('https://github.com/qgis/QGIS/search?q=4bd91351603b1b7f6a5fe76faf3841e357933017&type=Issues')

**Stack Trace**
<pre>
QList<QgsLayerTreeNode * __ptr64>::QList<QgsLayerTreeNode * __ptr64> qlist.h:809
QgsLayerTreeNode::children qgslayertreenode.h:110
QgsLegendRenderer::createComponentGroupList qgslegendrenderer.cpp:266
QgsLegendRenderer::paintAndDetermineSizeInternal qgslegendrenderer.cpp:139
QgsLegendRenderer::paintAndDetermineSize qgslegendrenderer.cpp:41
QgsLayoutItemLegend::paint qgslayoutitemlegend.cpp:122
QGraphicsScene::~QGraphicsScene :
QGraphicsScene::drawForeground :
QGraphicsScene::dragMoveEvent :
QGraphicsItem::dragMoveEvent :
QGraphicsEffectSource::draw :
QgsLayoutEffect::draw qgslayouteffect.cpp:33
QGraphicsScene::drawItems :
QGraphicsScene::drawItems :
QGraphicsView::paintEvent :
QgsLayoutView::paintEvent qgslayoutview.cpp:1147
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QApplication::windowIcon :
QWidgetPrivate::syncBackingStore :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processExposeEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QWindowSystemInterface::flushWindowSystemEvents :
UserCallWinProcCheckWow :
DispatchClientMessage :
_fnDWORD :
KiUserCallbackDispatcherContinue :
NtUserDispatchMessage :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1598
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.1-A Coru�a
QGIS code revision: ef24c526da
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by nyalldawson** [comment]
Are you running on a background thread?

**Comment by davidlgalt** [comment]
No. I'm self taught programmer, and I still have a lot of self-teaching to do. Can you give me an example of a background thread with PYQGIS?

**Comment by roya0045** [comment]
@davidlgalt share the script if you can, or parts of it, otherwise you can send the full thing to Nyall if you want your script to be private.

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
