### ISSUE TITLE
The "Measure Polygon" feature calculates about double the actual acreage (USA) of the actual polygon.  I noticed the issue when I measured the polygons in the field using a GPS unit. 

### ISSUE THREAD

**Issue by ForwardLandManagement** [qgis/QGIS#33737]
**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by gioman** [comment]
@ForwardLandManagement thanks for the report, but is largely incomplete.

Please add:

QGIS version used

Platform used

Attach a sample project + sample data

Add step by step list of operations that you are doing that lead to the wrong result

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
