### ISSUE TITLE
SVG point markers move at certain zoom levels when using  'metres at scale' as units

### ISSUE THREAD

**Issue by Isaacson33** [qgis/QGIS#33731]
The first screenshot is of a point marker (made up of a simple dot and a symbol (flying spaghetti monster!). The symbol is centred on the point feature.
![image](https://user-images.githubusercontent.com/37577337/72172804-00ec7f00-33ce-11ea-85d8-cb6af2213199.png)
Zoom in one step and I get the second screenshot. The SVG is way off the point feature, though the simple dot is unaffected. 
![image](https://user-images.githubusercontent.com/37577337/72172841-224d6b00-33ce-11ea-9989-9cd032dace35.png)
This only happens when the symbol size is set to metres at scale.
The actual zoom level seems to be irrelevant, it seems to happen whenever one part of the SVG is off-canvas, so a really large SVG would become displaced sooner than a small SVG.
I've tried various combinations of projected and co-ordinate CRSs, they don't seem to have any effect. I've also tried various ellipsoid methods (in case it was using them to measure the symbol) These don't seem to have any effect either.
As far as I can tell, the symbol is actually scaled correctly, so the 'metres at scale' bit is working properly, it just displaces it.

QGIS version | 3.10.1-A Coruña | QGIS code branch | Release QGIS code branch.3
-- | -- | -- | --
Compiled against Qt | 5.13.2 | Running against Qt | 5.14.0
Compiled against GDAL/OGR | 3.0.2 | Running against GDAL/OGR | 3.0.2
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.30.1 | Running against SQLite | 3.30.1
PostgreSQL Client Version | 12.1 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.3
Compiled against PROJ | 6.2.1 | Running against PROJ | Rel. 6.2.1, November 1st, 2019
OS Version | Manjaro Linux
Active python plugins | clipper; refFunctions; quick_map_services; TomBio; MetaSearch; db_manager; processing

**Comment by Saijin-Naib** [comment]
May his noodly appendages ever be in the geographically correct location.

**Comment by elpaso** [comment]
Please share a test project.

**Comment by Isaacson33** [comment]
[qgis test.zip](https://github.com/qgis/QGIS/files/4107711/qgis.test.zip)

**Comment by Pedro-Murteira** [comment]
@Isaacson33 I can no longer reproduce this issue using QGIS 3.16.15 and 3.22.2. Did you come across this issue more recently?
