### ISSUE TITLE
Polygonize Tool doesn't work with big data

### ISSUE THREAD

**Issue by kk-qgis** [qgis/QGIS#33736]
**Describe the bug**

Using the Polygonize Tool to create Polygons from a line layer
**How to Reproduce**

1 I loud a gpkg-layer with more than 50.000 features
![Screenshot_20200111_165350](https://user-images.githubusercontent.com/59770558/72206908-8dad4080-3493-11ea-8e91-711bb6269582.png)

2. then I run the Polygonize Tool
3. after 40 % the process stops
![Screenshot_20200111_165629](https://user-images.githubusercontent.com/59770558/72206891-563e9400-3493-11ea-9153-b6c2e042d9c9.png)
4. I wonder if the tool uses only one core instead more

**QGIS and OS versions**

QGIS 3.10-1 with Kubuntu
**Additional context**

**Comment by gioman** [comment]
@kk-qgis please attach/link the problematic dataset.

**Comment by kk-qgis** [comment]
@gioman here is gkpg-file with linelayer
[data.zip](https://github.com/qgis/QGIS/files/4051427/data.zip)

**Comment by nyalldawson** [comment]
It's not a freeze - it's just a very complex set of geometry to process. This is all being done in the geos library, and has been optimised considerably in newer GEOS versions. Closing as an upstream issue.
