### ISSUE TITLE
Copy & Paste of Cell Values broken

### ISSUE THREAD

**Issue by Saijin-Naib** [qgis/QGIS#33733]
**Describe the bug**
Cell values copy & pasted from the attributes table appear to be picking values from other rows/columns at random, and seemingly only the rowID or meaybe FID?.

**How to Reproduce**
Have an existing QGZ project with attribute tables attached to vector features (or even just stand-alone tabular data). Select a record, right click a cell, Copy Cell Content. Paste into another window/text editor, and observe a different value chosen than the one you expect.

**QGIS and OS versions**

QGIS version | 3.10.1-A Coruña | QGIS code revision | ef24c526da
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.2 | Running against GDAL/OGR | 3.0.2
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.2.1 | Running against PROJ | Rel. 6.2.1, November 1st, 2019
OS Version | Windows 10 (10.0)
Active python plugins | CalculateGeometry; MemoryLayerSaver; networks; openlayers_plugin; realcentroid; refFunctions; snail; SpreadsheetLayers; db_manager; MetaSearch; processing

**Additional context**
https://youtu.be/1Q6IvTwjGvM

**Comment by roya0045** [comment]
possibly related to #33439

**Comment by uclaros** [comment]
Yes, same as #33439 
You can use ctrl+c on the cell (with no features selected) until it's fixed.
