### ISSUE TITLE
SVG position inconsistencies in latest QGIS and Qt 5.14.0 on Arch Linux

### ISSUE THREAD

**Issue by betrio61** [qgis/QGIS#33745]
**Describe the bug**

SVG Symbol Selector interface shows correct symbol in preview window, but both in the all symbols thumbnails of that interface as well as in the main map canvas the composite symbol is incorrectly shown. More specifically, some of the individual SVGs that make up the composite symbol are displaced. This happens inconsistently accross various SVGs with no obvious reason.

This started only recently in the new version but still works properly with this version on Windows, thus I suspect that the different Qt version may be involved.

Screenshot:
- Of SVG Symbol Selector interface: ![Screenshot_2020-01-12_17-39-26](https://user-images.githubusercontent.com/59808482/72226965-35467380-3565-11ea-80c5-521af42f8697.png)
- Of Qt Version: 
![Screenshot_2020-01-12_17-40-41](https://user-images.githubusercontent.com/59808482/72226970-514a1500-3565-11ea-924a-959c17ee05f5.png)

I'm including the SVG file that is being displaced as well: https://gist.github.com/betrio61/c5c33cccbcfb18273cefebb3deddc5fe

**Comment by Isaacson33** [comment]
Possibly related to [#33731](https://github.com/qgis/QGIS/issues/33731)?

**Comment by betrio61** [comment]
It seems this was **not** a qgis specific issue since it resolved itself after updating my system. I believe it is from Qt 15.14.0 and resolved in Qt 15.14.1. Perhaps this also fixes poor mr. flying spaghetti monster in #33731 as well.

![image](https://user-images.githubusercontent.com/59808482/73601287-b376b400-452c-11ea-88a5-14d2bd27e268.png)
