### ISSUE TITLE
When i run this script on QGIS 3.6 with large database, QGIS got crashed

### ISSUE THREAD

**Issue by kapildevadk** [qgis/QGIS#33744]
[Qgis crashed.txt](https://github.com/qgis/QGIS/files/4051102/Qgis.crashed.txt)

**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by gioman** [comment]
@kapildevadk please update to 3.10.1 or use the latest LTR release, 3.14.4. Also if don't add the script/detail what you are trying to achieve (with snippets of code) this report is likely to not drive any attention.

**Comment by kapildevadk** [comment]
@gioman I've used 'Delete by Attribute' tool which is not found in QGIS 3.4 version, so i can not it on 3.4 version.

**Comment by gioman** [comment]
@kapildevadk 


so... are you running a custom script (as the title suggest) or are you using a standard QGIS tool? Do you mean the "delete duplicates by attribute"?

If is the latter please add detailed steps to replicate, if you can also attach the problematic layer (if is in a database attach the dump).

Also try with a new QGIS profile, no 3rd party plugins installed.


> so i can not it on 3.4 version.

update to the 3.10.1

**Comment by kapildevadk** [comment]
@gioman Yes, i'm running a custom script in which i've called up 'delete duplicates by attribute' algorithm from processing toolbox. All things gone as i want but when this script should save its final result output, it got crashed.

**Comment by gioman** [comment]
> @gioman Yes, i'm running a custom script in which i've called up 'delete duplicates by attribute' algorithm from processing toolbox. All things gone as i want but when this script should save its final result output, it got crashed.

@kapildevadk seem my previous comment, add your code.

**Comment by kapildevadk** [comment]
[select and alalyzed MT.txt](https://github.com/qgis/QGIS/files/4051193/select.and.alalyzed.MT.txt)

**Comment by gioman** [comment]
@kapildevadk is a model created with the QGIS modeller?

**Comment by kapildevadk** [comment]
@gioman Yes

**Comment by roya0045** [comment]
This might not be a qgis issue but a user issue, by looking at the code its impossible to run without the dataset.

**Comment by gioman** [comment]
@kapildevadk please attach the necessary sample data.

**Comment by alexbruy** [comment]
Closed for the lack of feedback. Please reopen if necessary.
