### ISSUE TITLE
QGIS WFS / OGC API – Features not showing list typed attributes correctly

### ISSUE THREAD

**Issue by giyona** [qgis/QGIS#33758]
**Describe the bug**

QGIS WFS / OGC API – Features are not showing list typed attributes (in Identify Results) correctly. Instead of a list it returns NULL.

**How to Reproduce**

1. Add a WFS / OGC API – Features: `https://pta.spatineo-devops.com/sofp/?f=json`
2. Add Administrative units 4500k (sea area excluded) (2019) -layer
3. Use filter `"levelName" = 'maakunta'`
4. Select any polygon with Identify Features tool
5. Notice how upperLevelUnit and/or lowerLevelUnit are NULL
6. To verify the data is there add the same data as Vector Layer using Layer --> Add Layer --> Add Vector Layer... (file) with Vector Dataset(s) as `https://pta.spatineo-devops.com/sofp/collections/au_kansallinen_meri_4500k_wgs84/2019/items?f=json&levelName=maakunta&limit=100` --> Add
8. Select any polygon with Identify Features tool
9. Notice how upperLevelUnit and/or lowerLevelUnit has list data

(Any other API Features data will do if there is a list typed attributes.)

**QGIS and OS versions**

QGIS version
3.11.0-Master
QGIS code revision
12c410c3f4
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.0dev
Running against GDAL/OGR
3.1.0dev
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
7.0.0
Running against PROJ
Rel. 7.0.0, March 1st, 2020
OS Version
Windows 10 (10.0)
This copy of QGIS writes debugging output.
Active python plugins
buffer_clip; 
MetaSearch; 
pluginbuilder3; 
plugin_reloader; 
db_manager; 
processing

**Comment by gioman** [comment]
> Use filter `"levelName" = 'maakunta'`

@giyona QGIS master always crashes for me at this step, works for you?

**Comment by giyona** [comment]
It hasn't crashed for me but you can skip the filter (it would just make it easier to find polygons which has data in upperLevelUnit and/or lowerLevelUnit). So you can just click polygons and see which has data in them and you will see the NULL instead of a list.

**Comment by giyona** [comment]
@gioman It hasn't crashed for me but you can skip the filter (it would just make it easier to find polygons which has data in upperLevelUnit and/or lowerLevelUnit). So you can just click polygons and see which has data in them and you will see the NULL instead of a list.

**Comment by gioman** [comment]
@giyona I was able to follow your steps and see what you say, anyway there are attributes that have different values, so I'm guessing if the difference for "upperLevelUnit" and "lowerLevelUnit" are just because the two datasources are just publishing different data...

![Screenshot_20200117_113148](https://user-images.githubusercontent.com/1951107/72609487-f4f84400-391c-11ea-84c8-790aaa51e251.png)

**Comment by gioman** [comment]
> different data...
> 
> ![Screenshot_20200117_113148](https://user-images.githubusercontent.com/1951107/72609487-f4f84400-391c-11ea-84c8-790aaa51e251.png)

forget about it, I think that what I'm seeing in the above image is because of another bug.

**Comment by gioman** [comment]
> forget about it, I think that what I'm seeing in the above image is because of another bug.

this one https://github.com/qgis/QGIS/issues/33880

**Comment by giyona** [comment]
> > forget about it, I think that what I'm seeing in the above image is because of another bug.
> 
> this one #33880

@gioman That is not the bug I am refering to here. If you see the original data of that particular feature with kmtkId = maakunta_01_20190101_01 (direct link here to the data: https://pta.spatineo-devops.com/sofp/collections/au_kansallinen_meri_4500k_wgs84/2019/items?levelName=maakunta&kmtkId=maakunta_1_20190101_01&f=json) you can see after you scroll almost to the end of that json file that the upperLevelUnit and lowerLevelUnit has values as follows:
```
"upperLevelUnit": ["avi_1_20190101_1", "valtio_1_20190101"],
"lowerLevelUnit": ["kunta_1_20190101_018", "kunta_1_20190101_049", "kunta_1_20190101_078"...]
```
In your picture above (the left one maakunta_01_20190101_01) it says that those two parameters are empty / null even they aren't. The bug is that the WFS / OGC API – Features does not show correctly the attributes which are lists in the original data.
