### ISSUE TITLE
QGIS crash on initiating print to plotter

### ISSUE THREAD

**Issue by grantboxer** [qgis/QGIS#33752]
## User Feedback

Sending print layout to plotter

## Report Details

**Crash ID**: [9165f34931d5344df87a0dc9432677a7e542667d]('https://github.com/qgis/QGIS/search?q=9165f34931d5344df87a0dc9432677a7e542667d&type=Issues')

**Stack Trace**
<pre>
UserCallDlgProcCheckWow :
DefDlgProcWorker :
DefDlgProcW :
UserCallWinProcCheckWow :
DispatchClientMessage :
_fnDWORD :
KiUserCallbackDispatcherContinue :
NtUserMessageCall :
SendMessageWorker :
SendMessageW :
ECResetTextInfo :
ECSetText :
EditWndProc :
EditWndProcWorker :
EditWndProcW :
UserCallWinProcCheckWow :
DispatchClientMessage :
_fnINSTRINGNULL :
KiUserCallbackDispatcherContinue :
NtUserMessageCall :
SendMessageWorker :
SendMessageW :
CPSUIPageDlgProc :
UserCallDlgProcCheckWow :
DefDlgProcWorker :
DefDlgProcW :
UserCallWinProcCheckWow :
DispatchClientMessage :
_fnDWORD :
KiUserCallbackDispatcherContinue :
NtUserMessageCall :
SendMessageWorker :
InternalCreateDialog :
CreateDialogIndirectParamAorW :
CreateDialogIndirectParamW :
_CreatePageDialog :
_CreatePage :
PageChange :
InitPropSheetDlg :
PropSheetDlgProc :
UserCallDlgProcCheckWow :
DefDlgProcWorker :
DefDlgProcW :
UserCallWinProcCheckWow :
DispatchClientMessage :
_fnDWORD :
KiUserCallbackDispatcherContinue :
NtUserMessageCall :
SendMessageWorker :
InternalCreateDialog :
CreateDialogIndirectParamAorW :
CreateDialogIndirectParamW :
SHFusionCreateDialogIndirectParam :
_RealPropertySheet :
_PropertySheet :
PropertySheetW :
DoComPropSheet :
DoCommonPropertySheetUI :
CommonPropertySheetUIW :
DocumentPropertiesWrap :
CPrintDialog::OnCommandMessage :
Print_GeneralDlgProc :
UserCallDlgProcCheckWow :
DefDlgProcWorker :
DefDlgProcW :
UserCallWinProcCheckWow :
DispatchClientMessage :
_fnDWORD :
KiUserCallbackDispatcherContinue :
NtUserMessageCall :
SendMessageWorker :
SendMessageW :
xxxBNReleaseCapture :
ButtonWndProcWorker :
ButtonWndProcW :
UserCallWinProcCheckWow :
DispatchMessageWorker :
IsDialogMessageW :
Prop_IsDialogMessage :
RealPropertySheet :
PropertySheet :
Print_InvokePropertySheets :
PrintDlgExX :
PrintDlgExW :
QPrintDialog::metaObject :
QgsLayoutDesignerDialog::print qgslayoutdesignerdialog.cpp:1938
QtPrivate::FunctorCall<QtPrivate::IndexesList<>,QtPrivate::List<>,void,void (__cdecl QgsLayoutDesignerDialog::*)(void) __ptr64>::call qobjectdefs_impl.h:134
QtPrivate::FunctionPointer<void (__cdecl QgsLayoutDesignerDialog::*)(void) __ptr64>::call<QtPrivate::List<>,void> qobjectdefs_impl.h:168
QtPrivate::QSlotObject<void (__cdecl QgsLayoutDesignerDialog::*)(void) __ptr64,QtPrivate::List<>,void>::impl qobjectdefs_impl.h:397
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
</pre>

**QGIS Info**
QGIS Version: 3.11.0-Master
QGIS code revision: 12c410c3f4
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.0dev
Running against GDAL: 3.1.0dev

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by gioman** [comment]
>  QGIS Version: 3.11.0-Master

@grantboxer 
does it makes any difference if you use QGIS 3.4 or 3.10? and using a new QGIS profile (no 3rd party plugins installed)?

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
