### ISSUE TITLE
[Processing][Database]Package layer takes only the first layer

### ISSUE THREAD

**Issue by saberraz** [qgis/QGIS#33767]
I am trying to use Package layer algorithm to package 4 layers. It only writes to first layer to the output database.

To elaborate a bit more, I am creating a model and there are 4 processes creating 4 OUTPUT.gpkg. There is only one layer in each geopackage. When I package all the OUTPUT.gpkgs, only the first one is written to the final output.

**Comment by m-kuhn** [comment]
This is likely linked to all the layers having the same name "OUTPUT". It should work if you rename layers first.
It's annoying - but rather a feature request to integrate layer renaming into package layers than a bug.

**Comment by nyalldawson** [comment]
There's a "Rename layer" algorithm available in the modeler designed for just this purpose...

**Comment by saberraz** [comment]
Yayyy! Renaming works.

**Comment by Gustry** [comment]
@saberraz Is-there an error message if you don't rename? (saying that the layer was already existing)

**Comment by saberraz** [comment]
No, no message. It shows merging layers has completed successfully.
