### ISSUE TITLE
QGIS 3.11 Crash

### ISSUE THREAD

**Issue by grantboxer** [qgis/QGIS#33777]
## User Feedback

Added SRTM DTM layer and panned map window, then crash.

## Report Details

**Crash ID**: [4396abf1a926888bf7246df90e042998452fdcc0]('https://github.com/qgis/QGIS/search?q=4396abf1a926888bf7246df90e042998452fdcc0&type=Issues')

**Stack Trace**
<pre>
RtlpFreeHeapInternal :
RtlFreeHeap :
_free_base :
osgeo::proj::datum::Datum::conventionalRS :
osgeo::proj::datum::Datum::conventionalRS :
OGRSpatialReference::exportToWkt :
QgsVectorLayer::labeling :
QgsVectorLayer::labeling :
QgsVectorLayer::labeling :
QgsVectorLayer::labeling :
QgsVectorLayer::labeling :
QgsVectorLayer::labeling :
QgsVectorLayer::labeling :
QgsVectorLayer::labeling :
QgsVectorLayer::labeling :
QgsVectorLayer::labeling :
QgsVectorLayer::labeling :
QgsGroupBoxCollapseButton::metaObject :
QgsGroupBoxCollapseButton::metaObject :
QgsGroupBoxCollapseButton::metaObject :
QgsGroupBoxCollapseButton::metaObject :
QgsGroupBoxCollapseButton::metaObject :
QMetaObject::activate :
QTimer::timerEvent :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsVectorLayer::labeling :
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32Private::sendTimerEvent :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
QgsVectorLayerProperties::aboutToShowStyleMenu :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.11.0-Master
QGIS code revision: 664ba234da
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.0dev
Running against GDAL: 3.1.0dev

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment]
@grantboxer please attach/link the problematic data.

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
