### ISSUE TITLE
Identify feature ID value off by 1 or more values

### ISSUE THREAD

**Issue by lindseyhannah** [qgis/QGIS#33770]
Windows 64 OS, data loaded in GeoJSON format. 

Issue occurs in the following release versions:

3.6.2
3.6.3
3.8.1
3.8.3
3.10

When using the Identify tool in an area with multiple layers (right click), the ID for the selected elements is off by 1 or more.  For instance, there is a feature at the location below in layer "Feature_A".  The initial Identify window says that the feature ID is "4", however, when clicking "identify" for this feature, the pop-up box states that this feature is ID "6". 

![image](https://user-images.githubusercontent.com/44279695/72303531-6df85280-3622-11ea-8303-ae8e31adb3b9.png)

![image](https://user-images.githubusercontent.com/44279695/72303333-caa73d80-3621-11ea-8649-b6011eb8f4e7.png)

This occurs for lines, polygons and point features. Usually, ID value are off by 1 but sometimes they are off by 2 or every 3.  

This bug is not present in v3.2.2

**Comment by m-kuhn** [comment]
Can you go to the attribute table and hover the row header and check the feature id there?

<img width="130" alt="image" src="https://user-images.githubusercontent.com/178003/70797451-77c93480-1d9c-11ea-9fe5-fbe32e138b58.png">

Note that feature id is not (necessarily) equal to your field ID. You can set the [display expression (sorry, google brought up the qfield docs earlier than the QGIS docs, it applies as well)](https://qfield.org/docs/et/project-management/vector-layers.html#display-expression) to tell QGIS which field you want to use to identify your features.

**Comment by lindseyhannah** [comment]
That fixed it!  We have a template where somehow the Display Option was set to "COALESCE ("ID/", <NULL>')”.  I reset this to "ID" for all our vector layers.  I didnt know this was an option we could change.  Thank you!!
