### ISSUE TITLE
[Processing][Cartography]Set layer style

### ISSUE THREAD

**Issue by saberraz** [qgis/QGIS#33784]
I am trying to apply a QML file from a web link (https://raw.githubusercontent.com/anitagraser/QGIS-resources/master/qgis2/osm_spatialite/osm_spatialite_googlemaps_multipolygon.qml) to my model. But **Set layer style** only accepts links from local resources.

**Comment by alexbruy** [comment]
@saberraz you can do this by creating very simple model with "Download file" and "Set layer style" algorithms.

**Comment by saberraz** [comment]
Indeed...that will work!
