### ISSUE TITLE
Incorrect repository settings for Debian install?

### ISSUE THREAD

**Issue by Robinlovelace** [qgis/QGIS#33786]
Related to https://github.com/qgis/QGIS/issues/32625, install instructions from https://qgis.org/en/site/forusers/alldownloads.html#debian-ubuntu on Debian stretch seem to fail.

I'm using the following stretch base image: https://hub.docker.com/r/rocker/r-ver/dockerfile

When the following is used the install fails:

```bash
'echo "deb http://qgis.org/debian-ltr stretch main" >> /etc/apt/sources.list'
'echo "deb-src http://qgis.org/debian-ltr stretch main" >> /etc/apt/sources.list'


  wget -O - https://qgis.org/downloads/qgis-2019.gpg.key | gpg --no-tty --import
  gpg --export --armor --no-tty --yes 51F523511C7028C3 | apt-key add - 
  apt-get update && apt-get install -qqy --no-install-recommends --fix-missing 
  python3-pip 
  python3-setuptools 
  python3-qgis 
  qgis 
  qgis-plugin-grass
```

With the following error message:

```
Unable to correct problems, you have held broken packages.
```

After some trial and error I found the install works when changing to a non-recommded mirror, is this intentional?:

```
  'echo "deb http://ftp.debian.org/debian sid main" >> /etc/apt/sources.list' 
  'echo "deb-src http://ftp.debian.org/debian sid main" >> /etc/apt/sources.list' 
```

As can be see here: https://hub.docker.com/r/robinlovelace/geocompr/builds

Is this deliberate? The only reason I tried sid was this thread which essentially reports the same issue: https://gis.stackexchange.com/questions/318738/raspbian-qgis-3-x-install which says:

> Issue: with the QGIS install instructions (assuming I followed them correctly) - it was unable to find the python3-qgis package.

> Solution: basically use a different mirror than what the install recommends.

**Comment by gioman** [comment]
@Robinlovelace can you ask this in the developers mailing list? thanks.

**Comment by Robinlovelace** [comment]
Trying to reproduce on a fresh Debian install, starting with:

```
docker run --rm -it debian:stretch bash
```

But cannot get anything working at present, apologies.

**Comment by Robinlovelace** [comment]
I still think this is an issue but closing for now as I cannot provide a reprex. Will re-open if I can.
