### ISSUE TITLE
QGIS as WFS client doesn't respect bounding boxes of layers

### ISSUE THREAD

**Issue by NyakudyaA** [qgis/QGIS#33787]
# Problem

I have an OSM layer I have published in Geoserver. The layer is coming from a PostgreSQL DB.
In the DB the layer covers the whole world but in GeoServer, I have restricted the extent as following

![layer-setting](https://user-images.githubusercontent.com/2510900/72332918-92583b80-36c3-11ea-8614-382b960c6fed.png)

If I request a WMS in QGIS I get the correct extent

![osm](https://user-images.githubusercontent.com/2510900/72333082-e7944d00-36c3-11ea-841a-dfc07bcb13b7.png)

WMS layer extent
![wms](https://user-images.githubusercontent.com/2510900/72334109-7d7ca780-36c5-11ea-8e27-5a563c3dfcd4.png)

A corresponding WFS layer shows the full layer as it is depicted in the DB

![wfs](https://user-images.githubusercontent.com/2510900/72333444-7608ce80-36c4-11ea-99f3-fb2a4d69661c.png)

WFS layer extent
![lry-ext](https://user-images.githubusercontent.com/2510900/72334140-88cfd300-36c5-11ea-85e1-d544f6e6242d.png)

I am using the following QGIS
![qgis](https://user-images.githubusercontent.com/2510900/72333577-b0726b80-36c4-11ea-95d5-c0f2394c8161.png)

**Comment by gioman** [comment]
@NyakudyaA I don't have a Geoserver installation right now I can use to test, but I have a Mapserver one > if you want to limit the published extent of a WFS layer the extent must be defined at a layer level and not at a service one.  I just tested it and works as expected (in QGIS as WFS client).

**Comment by NyakudyaA** [comment]
> @NyakudyaA I don't have a Geoserver installation right now I can use to test, but I have a Mapserver one > if you want to limit the published extent of a WFS layer the extent must be defined at a layer level and not at a service one. I just tested it and works as expected (in QGIS as WFS client).

Thanks, @gioman for testing but from my setup I have definitely setup per layer level not per service level. Maybe my QGIS is buggy so will test with master and revert back

**Comment by gioman** [comment]
> Maybe my QGIS is buggy so will test with master and revert back

@NyakudyaA I have tested with QGIS 3.10.1 on Linux.

**Comment by rouault** [comment]
The behaviour you see is "by design". There are too many servers buggy or misconfigured in the wild, so the provider doesn't (entirely) rely on the extent advertized in the Capabilities. If the returned feature go beyond it then it will extend the extent to the actual extent of the features. If you really want to truncate your layer, then you will have to clip it on the server side

**Comment by gioman** [comment]
> The behaviour you see is "by design". There are too many servers buggy or misconfigured in the wild, so the provider doesn't (entirely) rely on the extent advertized in the Capabilities. If the returned feature go beyond it then it will extend the extent to the actual extent of the features. If you really want to truncate your layer, then you will have to clip it on the server side

case closed then :)
