### ISSUE TITLE
Control Feature Renderin order not working with atlas

### ISSUE THREAD

**Issue by kylefelipe** [qgis/QGIS#33795]
**Describe the bug**
I set a layer "Control Feature Rendering Order" to render "@atlas_feature" first but its not working

**How to Reproduce**

1. make a point layer, some points must be near each other.
2. Right click on layer > Symbology check control rendering order and set to @atlas_feature and nulls handling as "Nulls Last"
3. Create a print layout and set the layer as coverage layer
4. activate the preview and navigate between the features.

**QGIS and OS versions**

QGIS version | 3.10.1-A Coruña
S.O.: Debian Buster

**Additional context**

![image](https://user-images.githubusercontent.com/24795382/72369775-9003da80-36df-11ea-8062-d12d1f08a8f8.png)

**Comment by roya0045** [comment]
Don't you want to render it last so it overlap the others instead of first where it will be buried?

**Comment by kylefelipe** [comment]
Yess....

Em ter, 14 de jan de 2020 19:46, Alex <notifications@github.com> escreveu:

**Comment by roya0045** [comment]
@kylefelipe if you render it last, does it work as intended?

**Comment by kylefelipe** [comment]
@roya0045, it does not work.

**Comment by gioman** [comment]
Maybe I'm missing something obvious, but as "@atlas_feature" is not available in the expression builder in the context of the layer order rendering, is that expected to work anyway while rendering an atlas?

**Comment by roya0045** [comment]
@gioman you're right, I assumed that it was available for rendering as I was using that to control the symbology but it appears the context is not added. This should be a feature request I guess.

**Comment by kylefelipe** [comment]
I found a way, using @atlas_pagename = "name" ("name" is a column that i used to page name)

**Comment by gioman** [comment]
> I found a way, using @atlas_pagename = "name" ("name" is a column that i used to page name)

can we close this?

**Comment by kylefelipe** [comment]
Yes, master...
