### ISSUE TITLE
Crash when exporting rendered raster to EPSG:3857

### ISSUE THREAD

**Issue by HenrikJanPersson** [qgis/QGIS#33801]
## User Feedback

Loaded a GeoTIFF which I colorized using pseudo-colors.
Wanted to export the rendered image, but in the web projection epsg:3857, which appears to cause QGIS to crash. Exporting in for example epsg:3006 works perfect.
Have Qgis installed through osgeo4w64.

## Report Details

**Crash ID**: [785baf5e21cce063fdd499b2efd77b76cbf0ad7e]('https://github.com/qgis/QGIS/search?q=785baf5e21cce063fdd499b2efd77b76cbf0ad7e&type=Issues')

**Stack Trace**
<pre>
QgsRasterBlock::color qgsrasterblock.h:271
QgsRasterFileWriter::writeImageRaster qgsrasterfilewriter.cpp:664
QgsRasterFileWriter::writeRaster qgsrasterfilewriter.cpp:151
QgsRasterFileWriterTask::run qgsrasterfilewritertask.cpp:59
QgsTask::start qgstaskmanager.cpp:77
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.1-A Coru�a
QGIS code revision: ef24c526da
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment]
@HenrikJanPersson please attach/link a sample of a raster we can use to replicate this issue.

**Comment by HenrikJanPersson** [comment]
the file limit size was 10 mb, and when I cut only a very small part of the raster, qgis does not crash. I have therefore cut a reasonably small part of the raster, which is ~70mb, which still causes qgis to crash.
It is available here until 22 jan 2020: https://transfernow.net/70863911sy7j

**Comment by gioman** [comment]
@HenrikJanPersson Crash confirmed on Windows, not on Linux. QGIS 3.10.1 in both cases.

**Comment by gioman** [comment]
[test.zip](https://github.com/qgis/QGIS/files/4073097/test.zip)
