### ISSUE TITLE
Not possible to change layer order by dragging (Fedora 31)

### ISSUE THREAD

**Issue by pathmapper** [qgis/QGIS#33817]
**Describe the bug**
On Fedora 31 it's not possible to change layer order by dragging.

**How to Reproduce**

1. Load at least two layers
2. Try to change the layer order by dragging in the layers panel
3. See error --> At the beginning it looks like it is working (see screenshot) but the order is not changeable

![layer_order](https://user-images.githubusercontent.com/20856381/72433865-93a86780-379a-11ea-8730-144ab7402d4d.png)

**QGIS and OS versions**

QGIS version | 3.10.1-A Coruña | QGIS code branch | Release QGIS code branch.3
-- | -- | -- | --
Compiled against Qt | 5.13.2 | Running against Qt | 5.13.2
Compiled against GDAL/OGR | 2.3.2 | Running against GDAL/OGR | 2.3.2
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.30.0 | Running against SQLite | 3.30.0
PostgreSQL Client Version | 11.6 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Fedora 31 (Workstation Edition)
Active python plugins | MetaSearch; db_manager; processing

**Additional context**

Similar issue in the past: https://github.com/qgis/QGIS/issues/24760

**Comment by pathmapper** [comment]
Just reproduced this issue two times with 

1. a fresh installation of Fedora 31 (with `sudo dnf upgrade` / reboot) and QGIS installed from the Fedora repositories: 
https://qgis.org/en/site/forusers/alldownloads.html#fedora

and also 

2. a fresh installation of Fedora 31 (with `sudo dnf upgrade` / reboot) and installed QGIS from `dani/qgis` as described here: https://qgis.org/en/site/forusers/alldownloads.html#qgis-stable

Fedora 31 iso from here: https://getfedora.org/de/workstation/download/

**Comment by manisandro** [comment]
Are you on gnome+wayland? If so, this is likely the same issue affecting many other Qt applications, see [1].

[1] https://lists.fedoraproject.org/archives/list/kde@lists.fedoraproject.org/thread/NHTCN2KKCC44T2FKBYG7QYCMFEECS25R/

**Comment by pathmapper** [comment]
@manisandro thanks a lot.

Yes, this is the source of the issue, GNOME / Wayland is the default in Fedora 31.

After setting `WaylandEnable=false` in `/etc/gdm/custom.conf` and a reboot, the drag and drop in the legend works as expected. 


![grafik](https://user-images.githubusercontent.com/20856381/72612172-4825c300-392c-11ea-90b6-d6cad097a69f.png)

Seems like this is the upstream issue which needs to be fixed:
https://gitlab.gnome.org/GNOME/mutter/issues/965 (Drag but no drop under Wayland)

Maybe add a hint to https://qgis.org/en/site/forusers/alldownloads.html#fedora?

Please feel free to close the issue.
