### ISSUE TITLE
QGIS 3.10 repeatedly crashing when left unattended

### ISSUE THREAD

**Issue by DavidJ2020** [qgis/QGIS#33812]
Hi - QGIS 3.10 A Coruna will not stop crashing whenever I leave my workstation! It's as though it cannot handle idleness. I'm running on a brand new Acer Nitro 5 using Windows 10. Any advice please? Many thanks. ****Discovered only happens when laptop on battery*****

**Comment by gioman** [comment]
@DavidJ2020 are you running 3.10.**1** ?

**Comment by gioman** [comment]
Does it makes any difference if you use a new QGIS profile (no 3rd party plugins installed)?

**Comment by roya0045** [comment]
@DavidJ2020 when you wrote "only happens when laptop on battery", could it be because your system is limiting performance when using the battery and this causes the crash? I doubt there is anything that can be done if that's the case as this is system specific.

**Comment by DavidJ2020** [comment]
Thank you both. I'm inclined to agree with @roya0045 but I'm such a novice I can well believe @gioman has it right too. I'll try running on a new profile. I'm running 3.10.0-A Coruña. Thanks again, appreciate it.

**Comment by gioman** [comment]
> 3.10.0-A Coruña

@DavidJ2020 also please update to 3.10.1 and try if is better.

**Comment by nyalldawson** [comment]
This is an upstream gdal issue - fixed in the gdal project already
