### ISSUE TITLE
qgis secondary development missing some header files

### ISSUE THREAD

**Issue by longhuan2018** [qgis/QGIS#33810]
When using QGIS for secondary development, it will prompt that some header files are missing. 

- [ ] Missing ui _ ***. h file
       The reason for this is that some of the ui _ ***. h files in the CMakeLists.txt of the gui are not included.
- [ ] Missing *** / ***. h file
      The reason for this is that some header files include their directories when including other header files, for example: #include "diagram / qgsdiagram.h", but when QGIS INSTALL, all header files will be placed in the same folder
- [x] ~~Missing header file used in qgis_app
      The reason for this is that the app's CMakeLists.txt does not contain a header file that requires INSTALL~~

**Comment by nyalldawson** [comment]
qgis_app headers are deliberately not exposed -- these aren't part of the public api

**Comment by longhuan2018** [comment]
> qgis_app headers are deliberately not exposed -- these aren't part of the public api

ok,  i will delete the third part

**Comment by longhuan2018** [comment]
I submitted a PR #33815 for this issue

**Comment by alexbruy** [comment]
Fixed by #51741.
