### ISSUE TITLE
Atlas check output filename expression validity

### ISSUE THREAD

**Issue by rpispico** [qgis/QGIS#33824]
When exporting an atlas  is necessary test if the expression set as specific "output filename expression " is correct. Otherwise no output file must be allowed. 
Try with a wrong expression using the "expression builder", in this case the validity check is performed and the Ok button is not active until the expression is not correct. 
Write the same wrong expression directly in the "output filename expression", you can go further to create the atlas. 
In this case no file will be created because even though the expression is not valid.

I tried with this wrong expression 'output_'||@atlas_featurenumber 'Hello world'

QGIS 3.10.1 on Windows 10 64bit

**Comment by roya0045** [comment]
I'm not sure its a bug if someone go out of their way to bypass the validation on an expression. This is up to the users. Otherwise there would be too many things to 'baby-proof' . Maybe someone will think otherwise.

**Comment by gioman** [comment]
> I'm not sure its a bug

@rpispico @roya0045 regardless sounds like more e feature request to me.

**Comment by rpispico** [comment]
I think it's a bug.  First, why let produce some output if QGIS knows that no map will be realized? Second, a feature is something new, but in this case, we have a different behavior (with error) for the same function. It's not a problem, now we know where to check before produce an atlas.

**Comment by roya0045** [comment]
Only the expression builder has validation mechanism, I doubt anyone wants to add scopes and expression validation to an input box. It could be done, but this is more stuff and that stuff is a feature.

**Comment by elpaso** [comment]
The missing validation may be a feature request but the fact that the atlas printing process proceeds until the end producing **no output at all** and with a green flagged success message is a bug for sure.
