### ISSUE TITLE
Recent Project List missing

### ISSUE THREAD

**Issue by chucklepie** [qgis/QGIS#33822]
I have installed V3.10.1-A and all that shows in the welcome page is 'Project Templates'. There are no recent projects, despite having created and opened some, and no obvious setting to show/hide this list.

I have observed similar problems raised by others, e.g.
https://gis.stackexchange.com/questions/342903/qgis-3-10-recent-projects-list-missing

If I visit Settings/options/advanced/UI/recentProjects I can see I have two items.

![image](https://user-images.githubusercontent.com/12863685/72446017-a0cd5280-37aa-11ea-98d9-b870f0167272.png)

All that is visible on the homepage is this:
![image](https://user-images.githubusercontent.com/12863685/72446091-c65a5c00-37aa-11ea-8a2f-c2dbc077c9fe.png)

**Comment by Gustry** [comment]
Can you try https://github.com/qgis/QGIS/issues/33718#issuecomment-573907204 ?
#33718

**Comment by chucklepie** [comment]
First, sorry, I did search for this bug but nothing came up.

Second, seriously! Sorryb, but this seems like a bit of UI and UX fail. The pane has no indication it is collapsed and no indication it can be expanded.

Any chance of a fix?

**Comment by gioman** [comment]
> Any chance of a fix?

yes sure, please file a feature request with the suggestion to improve this aspect of the UI/UX.
