### ISSUE TITLE
3D Map canvas does not follow the assigned map theme

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#33839]
1. In a 3D map view settings dialog, select a map theme to follow
1. Apply
1. In the main canvas, update that map theme
1. Look at the 3D map canvas, nothing changed: it still renders the old layers combination. Refreshing, moving doesn't seem to change anything.
1. Open the settings, it's however still bound to the map theme you selected
1. Apply that dialog, your map is now rendered with the map theme.

I think the update should be done automatically, without any action from the user.
3.10.1

**Comment by ismailsunni** [comment]
Hi @DelazJ 
I miss a little bit reading your description. So, I want to confirm, is it like this:

1. Set 3D map theme to map theme `MT1`
2. Update the map theme `MT1` (from the layer panel) by `replace theme` menu
3. The 3D map theme is using the old version of  `MT1`  not the new version of `MT1`

Is it correct?

**Comment by DelazJ** [comment]
Hi @ismailsunni 
Yes, that is the issue I'm reporting

**Comment by Pedro-Murteira** [comment]
@DelazJ using QGIS 3.16.15 and 3.22.2. and it seems I can no longer reproduce this.
