### ISSUE TITLE
QgsRendererPropertiesDialog crashes python application using PyQGis

### ISSUE THREAD

**Issue by mrludens** [qgis/QGIS#33830]
I have an external windows standalone python application that uses pyqgis. When I display a QgsRendererPropertiesDialog, python sometimes crashes when the user clicks on any color button (screenshot: http://psr.me/1903oq2). The problem is intermitent and seems to be in displaying the color dialog. In previous QGis versions I could avoid this problem by using:

        settings = QgsSettings()
        settings.setValue('qgis/native_color_dialogs', True)

QGis then used another color dialog that did not crash my application. However, since I updated to QGis 3.8.3 (OSGEO4W) this option no longer works.

I wrote a very small PyQt5 application (below, at the end) that reproduces the problem. 

Operating system: Windows 10 Home
Python version: 3.7.0 (OSGEO4W)
QGis version: 3.8.3 (OSGEO4W)

# Sample PyQt5 application that reproduces the problem

    from qgis.core import QgsVectorLayer, QgsStyle
    from qgis.gui import QgsRendererPropertiesDialog
    from PyQt5 import QtCore, QtWidgets

    def editStyle():
        layer = QgsVectorLayer('LineString?field=level:integer', 'contour_lines', 'memory')
        dialog = QtWidgets.QDialog()
        layout = QtWidgets.QVBoxLayout(dialog)

        # Add symbology panel
        symbPanel = QgsRendererPropertiesDialog(layer, QgsStyle.defaultStyle(), True)
        layout.addWidget(symbPanel)

        # Add Ok Cancel button box
        buttonBox = QtWidgets.QDialogButtonBox(QtWidgets.QDialogButtonBox.Ok | QtWidgets.QDialogButtonBox.Cancel, QtCore.Qt.Horizontal, dialog)
        buttonBox.button(QtWidgets.QDialogButtonBox.Ok).setText('Ok')
        buttonBox.button(QtWidgets.QDialogButtonBox.Cancel).setText('Cancel')
        buttonBox.accepted.connect(dialog.accept)
        buttonBox.rejected.connect(dialog.reject)
        layout.addWidget(buttonBox)

        dialog.setLayout(layout)
        dialog.adjustSize()

        if (dialog.exec_() == QtWidgets.QDialog.Accepted):
            symbPanel.apply()

    # Create simple application with only one button
    app = QtWidgets.QApplication([])

    window = QtWidgets.QWidget()
    layout = QtWidgets.QVBoxLayout()
    editBtn = QtWidgets.QPushButton('Edit Style')
    editBtn.clicked.connect(editStyle)
    layout.addWidget(editBtn)
    window.setLayout(layout)
    window.show()
    app.exec_()

    app.exit()

**Comment by gioman** [comment]
>  QGis version: 3.8.3 (OSGEO4W)

this is old. Does it happens if you use 3.10.1 (or QGIS LTR, in this case 3.4.14)?

**Comment by mrludens** [comment]
Yes, it still crashes with 3.10.1, only it crashes in the QgsRendererPropertiesDialog constructor (instead of when I click at color buttons). I can't even display the dialog.
In versions prior to 3.8.3 it still crashed but I could bypass it with QgsSettings().setValue('qgis/native_color_dialogs', True)

**Comment by Pedro-Murteira** [comment]
@mrludens Hello, is this still the case on recent versions of QGIS?

**Comment by mrludens** [comment]
No, it does not crash anymore
