### ISSUE TITLE
Highlight selected feature with a color even if its stroke and fill is set to none

### ISSUE THREAD

**Issue by HugoP27** [qgis/QGIS#33841]
I have point features with label values that I extracted from a CAD annotation file. As I only want to show the text and not the points, I set the symbology of the points so that they are not visible. The problem now is when I want to edit (move) the vertex of one of the 'invisible' points, it does not highlight the point on the map once it's selected (probably because the symbol is 'invisible'). It would be great if the outline of a shape is highlighted when selected even though the symbol is not visible.
Thanks for all the great work

**Comment by bkepl** [comment]
Maybe I’m not fully understanding your issue, but I am able to select a feature and see that it is selected (with the selection color set for the project), even if No Symbology is selected for the layer. Maybe I’m missing something in your comment.

**Comment by HugoP27** [comment]
Hi, I updated to the new version of QGIS and am able to see the selected feature now even if the symbology is not set, so maybe it was updated or just an oversight from my side. Thank you anyway and apologies for time wasted.
