### ISSUE TITLE
Python Script from graphic modeler doesn't run

### ISSUE THREAD

**Issue by kk-qgis** [qgis/QGIS#33845]
**Describe the bug**

I have maked a model with an if-statement/boolean. This model runs in well, but when I export to python, I will get an error
**How to Reproduce**

1. Create a model to add and calculate a field, which depends on the check of a boolean-input
![Screenshot_20200116_100602](https://user-images.githubusercontent.com/59770558/72509430-d83e0c80-3847-11ea-8c89-1d9a15b82cd1.png)

2. run the model in the graphic modeler and get the expected result
3. export to python and get an error
![Screenshot_20200116_095633](https://user-images.githubusercontent.com/59770558/72509517-0a4f6e80-3848-11ea-9316-657289481034.png)

4. See error -->
Unable to execute algorithm
Field name is not set. Please enter a field name
![Screenshot_20200116_095546](https://user-images.githubusercontent.com/59770558/72509596-28b56a00-3848-11ea-8f4b-a5ea8c8856ab.png)

**QGIS and OS versions**

QGIS version | 3.10.1-A Coruña | QGIS code revision | ef24c526da
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.6.2-CAPI-1.10.2 4d2925d6
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 10.10 (Ubuntu 10.10-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Ubuntu 18.04.3 LTS
Active python plugins | QuickMultiAttributeEdit3; polystrip; ViewshedAnalysis; LocatePoints; contour; DigitizingTools; IPyConsole; quick_map_services; AnotherDXF2Shape; MetaSearch; db_manager; processing

**Additional context**

**Comment by gioman** [comment]
@kk-qgis please attach the script.

**Comment by alexbruy** [comment]
Closed for the lack of feedback. Please reopen if necessary.
