### ISSUE TITLE
eVis Database Connection  error

### ISSUE THREAD

**Issue by the3rdParty** [qgis/QGIS#33848]
**Describe the bug**
eVis Database connection to an ODBC data source returns an error

**How to Reproduce**
1. Use the "eVis Database Connection" to set up a connection to an ODBC data source. 
![image](https://user-images.githubusercontent.com/6815649/72520588-6de69580-3862-11ea-9eb5-ace52f25c78c.png)

3. Set up the basic SQL query to return the fields with Lat / Long data from the appropriate table.  Run the query. 

2.  Configure the "Database File Selection" window.
![image](https://user-images.githubusercontent.com/6815649/72520929-28769800-3863-11ea-883d-22a363583092.png)

3. Click OK and this message appears:

"Layer is not valid : The layer file:///C:/Users/ABCDE/AppData/Local/Temp/QGIS3.HJlEUi?delimiter=%09&delimiterType=regexp&xField=WP_Lat&yField=WP_Long is not a valid layer and can not be added to the map. Reason:"

No layer is created.

**Additional context**
Looking at the QGIS Log Messages, under the "Delimited Text" tab I can see:

"2020-01-15T18:39:48 WARNING Errors in file C:/Users/ABCDE/AppData/Local/Temp/QGIS3.HJlEUi 2020-01-15T18:39:48 WARNING X field is not defined in delimited text file 2020-01-15T18:39:48 WARNING Y field is not defined in delimited text file"

The temporary file QGIS3.HJlEUi it appears to be a delimited text file in exactly the correct format:

WP_Lat	WP_Long
-15.765315	40.515876
-15.779443	40.534107
-15.816472	40.628185
-15.816369	40.611462
-15.816465	40.628178
-15.816469	40.628175

**QGIS and OS versions**
QGIS version
3.8.3-Zanzibar
QGIS code revision
685d8b15d2
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
2.4.1
Running against GDAL/OGR
2.4.1
Compiled against GEOS
3.7.2-CAPI-1.11.0
Running against GEOS
3.7.2-CAPI-1.11.0 b55d2125
PostgreSQL Client Version
10.8
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
5.2.0
Running against PROJ
Rel. 5.2.0, September 15th, 2018
OS Version
Windows 10 (10.0)

eVis 1.1.0 (core plugin)

Windows 10

Many thanks

**Comment by gioman** [comment]
>  3.8.3-Zanzibar

@the3rdParty is too old, you must test on 3.10(.1) but I don't think it will do much difference (given it is really a bug) as the eVIS tool is kind in a abandoned state.

**Comment by gioman** [comment]
> The temporary file QGIS3.HJlEUi it appears to be a delimited text file in exactly the correct format:
> 
> WP_Lat WP_Long
> -15.765315 40.515876
> -15.779443 40.534107
> -15.816472 40.628185
> -15.816369 40.611462
> -15.816465 40.628178
> -15.816469 40.628175

@the3rdParty unless it expects the comma as separator(?).

**Comment by gioman** [comment]
@the3rdParty attaching a sample dataset would also help try understand where the problem is.

**Comment by the3rdParty** [comment]
> @the3rdParty attaching a sample dataset would also help try understand where the problem is.

Here is the temporary file that eVis created from the ODBC link
[QGIS3.zip](https://github.com/qgis/QGIS/files/4071429/QGIS3.zip)

I am not able to send you the source database for various reasons including the fact that you would need an installation of Filemaker to make it work.

**Comment by the3rdParty** [comment]
> @the3rdParty unless it expects the comma as separator(?).

"Layer is not valid : The layer file:///C:/Users/ABCDE/AppData/Local/Temp/QGIS3.HJlEUi?delimiter=**%09**&delimiterType=regexp&xField=WP_Lat&yField=WP_Long is not a valid layer and can not be added to the map. Reason:"

The error message seems to recognise that it is Tab delimited (%09 is Horizontal Tab)..... but I am not sure whether this is in fact what it was expecting.

**Comment by the3rdParty** [comment]
> > @the3rdParty attaching a sample dataset would also help try understand where the problem is.
> 
> Here is the temporary file that eVis created from the ODBC link
> [QGIS3.zip](https://github.com/qgis/QGIS/files/4071429/QGIS3.zip)
> 
> I am not able to send you the source database for various reasons including the fact that you would need an installation of Filemaker to make it work.

I just put some test point data into Excel, configured an ODBC connection, linked from QGIS to Excel using eVis and got exactly the same result.  The problem does not appear to be how the data is served via ODBC, but how eVis is reading the temporary file that eVis has created

**Comment by DLList** [comment]
I have same Problem ...

**Comment by the3rdParty** [comment]
Unfortunately I have not, at least not via eVis.

At the moment I am having to use an alternative method which unfortunately can only be made to read 1 geometry per record (apparently its a limit of the ODBC driver).

More details [here](https://gis.stackexchange.com/questions/130172/filemaker-interface-with-qgis/336358#336358)

**Comment by nyalldawson** [comment]
The evis plugin has been removed for qgis 3.14 and is no longer supported
