### ISSUE TITLE
to_date function not working into layer filter

### ISSUE THREAD

**Issue by respeso** [qgis/QGIS#33842]
Qgis 3.4 documentation indicates that:  "to_date()" function can be used in expressions filtering, but when it is used, qgis throws error "no exist to_date(unknown) function"
![image](https://user-images.githubusercontent.com/16921604/72503665-90fe4e80-383c-11ea-8f70-3e9da8917cf5.png)

Filter used:    "date">to_date( '2014-03-28') about layer with a field called "date" and type QDate.  Result return all features, but it is not real.

I'm working with QGIS 3.10.1 in Windows 7 Professional (regional configuration Spain ES)

**Additional context**

**Comment by DelazJ** [comment]
Hi @respeso 
Can you point to the doc section you are referring to and explain where in QGIS you are using your expression filter? Also the whole expression might be helpful.
Thanks.

**Comment by DelazJ** [comment]
This section is about the programming way to filter so has nothing to do with your need. I think you better try https://docs.qgis.org/3.4/en/docs/user_manual/working_with_vector/vector_properties.html#query-builder which relates to the place you are doing your filter, ie casting your field. And right, to_date is not available there.
Nonetheless, I think these functions should not be listed in the pyqgis.

**Comment by DelazJ** [comment]
Ps: most of the dialogs in QGIS have a help button that leads to the most appropriate and related section. Better use it when looking for details on a dialog

**Comment by respeso** [comment]
Thank's @DelazJ
It is working now!!!. 
Excuse me for the inconvenience.
Best regards
