### ISSUE TITLE
bsb format not projected in 3.10.1

### ISSUE THREAD

**Issue by alaybourn** [qgis/QGIS#33853]
bsb format nautical charts are not projected on the fly in version 3.10.1 as they were in 3.10.0. These files from NOAA (https://www.charts.noaa.gov/InteractiveCatalog/nrnc.shtml?rnc=16528) contain CRS info in the header, which must have been how earlier versions projected them, but don't seem to be utilized in 3.10.1.

**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by i-s-o** [comment]
I see that is fixed in the current development branches. I would expect that the next point release, 3.10.2, which will be out in a few days will work correctly.

**Comment by gioman** [comment]
@alaybourn works ok here on 3.10.1 On Linux with GDAL 2.2.3 and proj4 v.493, also works ok on QGIS-rel-dev (next 3.10.2) on Windows with GDAL 3.1.0dev and Proj 7.0.0, while is not ok on Windows on QGIS 3.10.1 with GDAL 3.0.2 and Proj 6.2.1. Seems like an upstream library issue, already fixed at some point, and anyway not a QGIS issue.

**Comment by alaybourn** [comment]
Thank you for looking into this. I should have included that I'm running
Windows 10, QGIS 3.10.1 against GDAL 3.0.2, which makes sense why it's not
working. I'll wait for the 3.10.2 release.

Many thanks,
Adam
