### ISSUE TITLE
Not possible to uncheck layers in Order Panel

### ISSUE THREAD

**Issue by ghtmtt** [qgis/QGIS#33854]
In the Order Layer Panel it is possible to check a layer not active in the legend to activate it, but it is not possible to uncheck it to deactivate it. It is the correct behavior?

**Comment by gioman** [comment]
@ghtmtt no, is not right, this is a regression.

**Comment by gioman** [comment]
> @ghtmtt no, is not right, this is a regression.

well... at least I think so... I can't recall this work this way in the past.

**Comment by ghtmtt** [comment]
BTW: same behavior on Linux and Windows on QGIS 3.10.1 (compiled and also installed from package)
