### ISSUE TITLE
Custom select tool invisible features

### ISSUE THREAD

**Issue by berkayoruc** [qgis/QGIS#33869]
**Describe the bug**
I'm a QGIS plugin developer. For my plugin, I need to write custom select tool. Custom select tool(QgsMapTool) is selecting invisible features which are in categorized layer and unchecked category. At QGIS 3.6.0, custom select tool doesn't select invisible features.

**How to Reproduce**
```
layer=iface.activeLayer()
startPoint=QgsPoint(419497,4182641)
endPoint=QgsPoint(419538,4182662)
rect=QgsRectangle(419497,4182641,419538,4182662)
layer.selectByRect(rect)
selection = layer.selectedFeatures()
# iterate over selected features
for feat in selection:
    print(feat.isValid())
```
Here is my sample code.

**QGIS and OS versions**
Bug version: 3.10.0
Working version: 3.6.0
OS versions: Windows 10

**Additional context**
I don't know it is bug or not, but I didn't see any changes of API about QgsMapTool or QgsMapToolEmitPoint.

**Comment by gioman** [comment]
>  Working version: 3.6.0

@berkayoruc this is too old and unsupported, anyway if this is a question rather than a bug report it should be asked in the developers mailing list, not here.

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
