### ISSUE TITLE
 Crash when applying wrong filter to OAFeat layer

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#33878]
QGIS master on Windows.

Create a WFS / OGC API  connection to https://pta.spatineo-devops.com/sofp/?f=json

Connect to the service

Choose a layer and double click to open a dialog that allows to create a filter with an expression

Enter a filter/expression that is based on a column name that does not actually exist in the layer, i.e. "test"=1

Click "test" or "ok" > crash

**Comment by rouault** [comment]
@giohappy Side remark: my proposed modified title for the issue was more specific I think that "WFS". The layer pointed is a OAFeat (OGC API Feature) one, not a WFS one.

**Comment by rouault** [comment]
oops above remark was meant for @gioman

**Comment by gioman** [comment]
> The layer pointed is a OAFeat (OGC API Feature) one, not a WFS one.

@rouault correct, thanks!
