### ISSUE TITLE
"auto open form" does not show on Windows

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#33879]
QGIS 3.10.1 Linux:

![Screenshot_20200117_114905](https://user-images.githubusercontent.com/1951107/72610518-823c9800-391f-11ea-8c7f-15d82a1e62ee.png)

QGIS 3.10.1/master Windows:

![Screenshot_20200117_114924](https://user-images.githubusercontent.com/1951107/72610536-8e285a00-391f-11ea-8600-90d7a719858a.png)

**Comment by alexbruy** [comment]
In master it was moved to the settings menu, see #33704. Also fix was backported to 3.10 branch. Probably you have different revisions on Linux and Windows

**Comment by gioman** [comment]
@alexbruy thanks Alex I missed that.
