### ISSUE TITLE
Crashes whenever you try to open or save a project

### ISSUE THREAD

**Issue by Griffonaus** [qgis/QGIS#33881]
## User Feedback

Crashes everytime you try to open or save a project.

## Report Details

**Crash ID**: [3df8060b40e0410b694a9b87b4a9d955be2b0399]('https://github.com/qgis/QGIS/search?q=3df8060b40e0410b694a9b87b4a9d955be2b0399&type=Issues')

**Stack Trace**
<pre>
RtlpFreeHeapInternal :
RtlFreeHeap :
free :
DllUnregisterServer :
DllUnregisterServer :
CServerContextActivator::CreateInstance actvator.cxx:877
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1970
CApartmentActivator::CreateInstance actvator.cxx:2185
CProcessActivator::CCICallback actvator.cxx:1636
CProcessActivator::AttemptActivation actvator.cxx:1523
CProcessActivator::ActivateByContext actvator.cxx:1367
CProcessActivator::CreateInstance actvator.cxx:1267
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1970
CClientContextActivator::CreateInstance actvator.cxx:566
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1970
ICoCreateInstanceEx objact.cxx:2044
CComActivator::DoCreateInstance immact.hxx:386
CoCreateInstance actapi.cxx:121
_SHCoCreateInstance :
DCA_SHExtCoCreateInstance :
CreateAndCacheIconOverlay :
CFSIconOverlayManager::GetOverlayIconInformation :
CFSIconOverlayManager::LoadIconOverlayIdentifiers :
CFSIconOverlayManager::_s_LoadIconOverlayIdentifiers :
CFSIconOverlayManager::LoadNonloadedOverlayIdentifiers :
EnableExternalOverlayIdentifiers :
CFSIconOverlayManager::RefreshOverlayImages :
GetIconOverlayManagerImpl :
CFSFolder::_GetOverlayInfo :
CDesktopFolder::GetOverlayIndex :
CRegFolder::GetOverlayIndex :
CNscOverlayTask::_Extract :
CNscOverlayTask::InternalResumeRT :
CRunnableTask::Run :
CShellTask::TT_Run :
CShellTaskThread::ThreadProc :
CShellTaskThread::s_ThreadProc :
ExecuteWorkItemThreadProc :
RtlpTpWorkCallback :
TppWorkerThread :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.1-A Coru�a
QGIS code revision: ef24c526da
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
@Griffonaus please try with a new QGIS profile, no 3rd party plugins installed.

**Comment by Griffonaus** [comment]
How do  you start with a new QGIS profile? Kind regards,Andrew Wilkinson From: Giovanni ManghiSent: 17 January 2020 22:57To: qgis/QGISCc: Griffonaus; MentionSubject: Re: [qgis/QGIS] Crashes whenever you try to open or save a project (#33881) @Griffonaus please try with a new QGIS profile, no 3rd party plugins installed.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by gioman** [comment]
> >How do  you start with a new QGIS profile?

settings > user profiles > new profile

**Comment by Griffonaus** [comment]
Still crashes. When Save As or Open  it “stops responding” From: Giovanni ManghiSent: 17 January 2020 23:08To: qgis/QGISCc: Griffonaus; MentionSubject: Re: [qgis/QGIS] Crashes whenever you try to open or save a project (#33881) How do you start with a new QGIS profile?settings > user profiles > new profile—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by gioman** [comment]
> Still crashes

@Griffonaus does it happens on a different machine?

**Comment by Griffonaus** [comment]
I only have the laptop. It crashes every time QGIS opens explorer to import a file or open or save a project. It is really frustrating as It has been working well until V 3.4.  I have tried uninstalling and re-installing numerous times, rolled back graphic card updates etc.    From: Giovanni ManghiSent: 17 January 2020 23:19To: qgis/QGISCc: Griffonaus; MentionSubject: Re: [qgis/QGIS] Crashes whenever you try to open or save a project (#33881) Still crashes@Griffonaus does it happens on a different machine?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by roya0045** [comment]
How much memory do you have?

**Comment by gioman** [comment]
> I only have the laptop. It crashes every time QGIS opens explorer to import a file or open or save a project. It is really frustrating as It has been working well until V 3.4

@Griffonaus I understand but this seems really a local issue and not a general one.

**Comment by Griffonaus** [comment]
Agreed. Apart from Windows 10 updates , nothing else has really changed.

**Comment by Griffonaus** [comment]
16Gb RAM
3TB SSD/HDD

**Comment by Griffonaus** [comment]
I have re-installed V2.18 and that runs really well.

It is version 3.4 and 3.10.1 thatare not working (I haven’t re-installed V3.0) yet.

Kind regards,
Andrew Wilkinson
+61 400 778 098
Andrew.wilkinson@flinders.edu.au

**Comment by gioman** [comment]
> It is version 3.4 and 3.10.1 thatare not working (I haven’t re-installed V3.0) yet.

@Griffonaus it really seems a local issue, not a general one. You should try on a different machine (even a virtual machine) and check it.

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
