### ISSUE TITLE
QGIS crashes when loading geotiff

### ISSUE THREAD

**Issue by woody23** [qgis/QGIS#33892]
## User Feedback

When loading a Lidar til (geotiff), QGIS suddenly crashes all the time. I tried to reinstall QGIS with OSGEO4W, but no difference, even after uninstalling all traces of plugins from QGIS. 

## Report Details

**Crash ID**: [ebdeeea817cbd53583c8b87f4bef3fbaf385ef44]('https://github.com/qgis/QGIS/search?q=ebdeeea817cbd53583c8b87f4bef3fbaf385ef44&type=Issues')

**Stack Trace**
<pre>
MoveSmall memcpy.asm:266
QgsRasterIdentifyResult::params :
QgsAbstractDatabaseProviderConnection::TableProperty::GeometryColumnType::operator== :
QgsSingleBandGrayRenderer::block :
QgsBrightnessContrastFilter::block :
QgsHueSaturationFilter::block :
QgsRasterResampleFilter::block :
QgsRasterProjector::block :
QgsRasterIterator::readNextRasterPartInternal :
QgsRasterDrawer::draw :
QgsRasterLayerRenderer::render :
QgsMapRendererParallelJob::renderLayerStatic :
QgsArchive::zip :
QgsImageOperation::overlayColor :
QgsMapRendererParallelJob::cancelWithoutBlocking :
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.1-A Coru�a
QGIS code revision: ef24c526da
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment]
> When loading a Lidar til (geotiff), QGIS suddenly crashes all the time. I tried to reinstall QGIS with OSGEO4W, but no difference, even after uninstalling all traces of plugins from QGIS.

@woody23 please try with a new QGIS profile, no 3rd party plugins installed. If it continues please attach/link the problematic raster.

**Comment by woody23** [comment]
Many thanks for this, works very well! Problems resolved!
