### ISSUE TITLE
Error of tool Fill Sink (wang & liu).

### ISSUE THREAD

**Issue by Labros89** [qgis/QGIS#33890]
Hi I am trying to use the tool Fill Sink (wang & liu) and all the time I got the following error:
The following layers were not correctly generated.<ul><li>C:/AGMEE/Workspace Saga/DEM2_FillSink.sdat</li><li>C:/AGMEE/Workspace Saga/DEM2_FlowDirection.sdat</li></ul>You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.

Please, do you know how to fix it? It is important for my work.

**Comment by Labros89** [comment]
The Log Message Panel gives me this:
2020-01-17T17:47:05     INFO    SAGA execution commands
             io_gdal 0 -TRANSFORM 1 -RESAMPLING 3 -GRIDS "C:/Users/lambr/AppData/Local/Temp/processing_7f1878665ee14c129c2d9c0735fa6bba/processing_ed3715a382f041deb51e39ddeb794320/c4031f8760524688a9c7214a35b3bb8e/DEM2Proj3.sgrd" -FILES "C:/AGMEE/Workspace/DEM_2_Proj3.tif"
             ta_preprocessor "Fill Sinks (Wang & Liu)" -ELEV "C:/Users/lambr/AppData/Local/Temp/processing_7f1878665ee14c129c2d9c0735fa6bba/processing_ed3715a382f041deb51e39ddeb794320/c4031f8760524688a9c7214a35b3bb8e/DEM2Proj3.sgrd" -MINSLOPE 0.01 -FILLED "C:/AGMEE/Workspace Saga/DEM_2_FillSinks.sdat"
             ta_preprocessor "Fill Sinks (Wang & Liu)" -ELEV "C:/Users/lambr/AppData/Local/Temp/processing_7f1878665ee14c129c2d9c0735fa6bba/processing_ed3715a382f041deb51e39ddeb794320/c4031f8760524688a9c7214a35b3bb8e/DEM2Proj3.sgrd" -MINSLOPE 0.01 -FILLED "C:/AGMEE/Workspace Saga/DEM_2_FillSinks.sdat" -FDIR "C:/AGMEE/Workspace Saga/DEM_2_FlowDirection.sdat"
             ta_preprocessor "Fill Sinks (Wang & Liu)" -ELEV "C:/Users/lambr/AppData/Local/Temp/processing_7f1878665ee14c129c2d9c0735fa6bba/processing_ed3715a382f041deb51e39ddeb794320/c4031f8760524688a9c7214a35b3bb8e/DEM2Proj3.sgrd" -MINSLOPE 0.01 -FILLED "C:/AGMEE/Workspace Saga/DEM_2_FillSinks.sdat" -FDIR "C:/AGMEE/Workspace Saga/DEM_2_FlowDirection.sdat" -WSHED "C:/Users/lambr/AppData/Local/Temp/processing_7f1878665ee14c129c2d9c0735fa6bba/processing_ed3715a382f041deb51e39ddeb794320/6429dcdd7d1c408c836e7a0bdac214b6/WSHED.sdat"
2020-01-17T17:47:09     INFO    SAGA execution console output
             
2020-01-17T17:47:12     INFO    SAGA execution commands
             ta_preprocessor "Fill Sinks (Wang & Liu)" -ELEV "C:/Users/lambr/AppData/Local/Temp/processing_7f1878665ee14c129c2d9c0735fa6bba/processing_ed3715a382f041deb51e39ddeb794320/c4031f8760524688a9c7214a35b3bb8e/DEM2Proj3.sgrd" -MINSLOPE 0.01 -FILLED "C:/AGMEE/Workspace Saga/DEM_2_FillSinks.sdat"
             ta_preprocessor "Fill Sinks (Wang & Liu)" -ELEV "C:/Users/lambr/AppData/Local/Temp/processing_7f1878665ee14c129c2d9c0735fa6bba/processing_ed3715a382f041deb51e39ddeb794320/c4031f8760524688a9c7214a35b3bb8e/DEM2Proj3.sgrd" -MINSLOPE 0.01 -FILLED "C:/AGMEE/Workspace Saga/DEM_2_FillSinks.sdat" -FDIR "C:/AGMEE/Workspace Saga/DEM_2_FlowDirection.sdat"
             ta_preprocessor "Fill Sinks (Wang & Liu)" -ELEV "C:/Users/lambr/AppData/Local/Temp/processing_7f1878665ee14c129c2d9c0735fa6bba/processing_ed3715a382f041deb51e39ddeb794320/c4031f8760524688a9c7214a35b3bb8e/DEM2Proj3.sgrd" -MINSLOPE 0.01 -FILLED "C:/AGMEE/Workspace Saga/DEM_2_FillSinks.sdat" -FDIR "C:/AGMEE/Workspace Saga/DEM_2_FlowDirection.sdat" -WSHED "C:/Users/lambr/AppData/Local/Temp/processing_7f1878665ee14c129c2d9c0735fa6bba/processing_ed3715a382f041deb51e39ddeb794320/73c0b610e2534f26b49c335f7774a017/WSHED.sdat"
2020-01-17T17:47:35     INFO    SAGA execution console output
             
2020-01-17T17:53:24     INFO    SAGA execution commands
             io_gdal 0 -TRANSFORM 1 -RESAMPLING 3 -GRIDS "C:/Users/lambr/AppData/Local/Temp/processing_7f1878665ee14c129c2d9c0735fa6bba/processing_ed3715a382f041deb51e39ddeb794320/30e4c3392bb74a84944b8a38a4e7392c/DEM2FillSinks.sgrd" -FILES "C:/AGMEE/Workspace Saga/DEM_2_FillSinks.sdat"
             ta_preprocessor "Fill Sinks (Wang & Liu)" -ELEV "C:/Users/lambr/AppData/Local/Temp/processing_7f1878665ee14c129c2d9c0735fa6bba/processing_ed3715a382f041deb51e39ddeb794320/30e4c3392bb74a84944b8a38a4e7392c/DEM2FillSinks.sgrd" -MINSLOPE 0.01 -FILLED "C:/AGMEE/Workspace Saga/DEM2_FillSink.sdat"
             ta_preprocessor "Fill Sinks (Wang & Liu)" -ELEV "C:/Users/lambr/AppData/Local/Temp/processing_7f1878665ee14c129c2d9c0735fa6bba/processing_ed3715a382f041deb51e39ddeb794320/30e4c3392bb74a84944b8a38a4e7392c/DEM2FillSinks.sgrd" -MINSLOPE 0.01 -FILLED "C:/AGMEE/Workspace Saga/DEM2_FillSink.sdat" -FDIR "C:/AGMEE/Workspace Saga/DEM2_FlowDirection.sdat"
             ta_preprocessor "Fill Sinks (Wang & Liu)" -ELEV "C:/Users/lambr/AppData/Local/Temp/processing_7f1878665ee14c129c2d9c0735fa6bba/processing_ed3715a382f041deb51e39ddeb794320/30e4c3392bb74a84944b8a38a4e7392c/DEM2FillSinks.sgrd" -MINSLOPE 0.01 -FILLED "C:/AGMEE/Workspace Saga/DEM2_FillSink.sdat" -FDIR "C:/AGMEE/Workspace Saga/DEM2_FlowDirection.sdat" -WSHED "C:/Users/lambr/AppData/Local/Temp/processing_7f1878665ee14c129c2d9c0735fa6bba/processing_ed3715a382f041deb51e39ddeb794320/cf15814a38d34082954f7d0149ac550e/WSHED.sdat"
2020-01-17T17:53:27     INFO    SAGA execution console output

**Comment by gioman** [comment]
@Labros89 are you on Windows? is yes did you installed QGIS with the standalone installer or OSGeo4w? what version are you using?

**Comment by gioman** [comment]
@Labros89 also there are several other tickets on the same matter, open and closed.

**Comment by gioman** [comment]
@Labros89 also attach/link the DEM you are using.

**Comment by gioman** [comment]
@Labros89 how this differs from https://github.com/qgis/QGIS/issues/33821 ?

**Comment by Labros89** [comment]
I installed OSGeo4W the last version and I use this one, not the standalone QGIS

**Comment by gioman** [comment]
> last version

@Labros89 be specific, 3.10.1? 3.4.14? 

check (using the advanced install in OSGEO4w)  if the gdal204 package is installed.

please attach your DEM.

**Comment by Labros89** [comment]
The DEM that I downloaded is from ASTER GDEM 2

**Comment by gioman** [comment]
> The DEM that I downloaded is from ASTER GDEM 2

please post a link.

**Comment by Labros89** [comment]
The version that I download is the 3.10.1

**Comment by gioman** [comment]
> The version that I download is the 3.10.1

post a link to the DEM.

**Comment by Labros89** [comment]
Do you mean this? ASTGTM2_N57E058_dem?

**Comment by gioman** [comment]
> Do you mean this? ASTGTM2_N57E058_dem?

is not a link where I can download the DEM and test locally if the tool works as expected or not.

**Comment by Labros89** [comment]
https://gdex.cr.usgs.gov/gdex/ this is the link from which I downloaded my DEM

**Comment by gioman** [comment]
> https://gdex.cr.usgs.gov/gdex/ this is the link from which I downloaded my DEM

the link is dead here.

**Comment by gioman** [comment]
> https://gdex.cr.usgs.gov/gdex/ this is the link from which I downloaded my DEM

http://sendimage.whu.edu.cn/res/DEM_share/ASTER%20GDEM%20v2/N30,E30/ASTGTM2_N57E058_dem.tif

**Comment by gioman** [comment]
@Labros89 works as expected here, on a testing Windows VM.

Results attached. You have probably a local installation issue, or maybe a memory one.

[results.zip](https://github.com/qgis/QGIS/files/4077949/results.zip)
