### ISSUE TITLE
Labels along perimeters or lines

### ISSUE THREAD

**Issue by Forna73** [qgis/QGIS#33915]
I'm using Qgis since 1.8 and I've noticed the improvements in labels engine.
I usually work with maps very label crowded and I always have to get mad sorting and positioning them. One Thing often happens to me is that when I have a region with a lot of labels and in the same region I have a polygon or a line that pass through, when I select a label positioning system with the perimeter (both curved or not) the label quite always appear where there are already other labels!!! even if the main geometry portion stays out of them.
It should be very useful having the possibility to scroll the label along the line, or at least to decide where the label should stay along the perimeter.

**Comment by roya0045** [comment]
In the meantime if the label is still straight and the feature is a line, you could use the orientation of the line set the orientation of the label as move it. This is what I tend to do.

**Comment by pjshelton** [comment]
This can be closed out now as North Road have implemented this in their addition to 3.16.
https://north-road.com/2020/09/03/line-label-placement-our-gift-to-the-qgis-community/

To control the position along the perimeter of a polygon, you will need to use geometry generator and use the function exterior_ring(  $geometry ) to get a Linestring that mimics the perimeter of the polygon.
