### ISSUE TITLE
[QGIS 3.11-Master] Qt keeps complaining "WARNING    GEOS exception: UnsupportedOperationException: getX called on empty Point"

### ISSUE THREAD

**Issue by denchat** [qgis/QGIS#33914]
After open a project from 3.10, Qt keeps complaining as below everytime the map gets rendered.

>     WARNING    GEOS exception: UnsupportedOperationException: getX called on empty Point
>     WARNING    GEOS exception: UnsupportedOperationException: getY called on empty Point

Any ideas where those are thrown from?

**Comment by gioman** [comment]
@denchat please ask questions in the users or developers mailing lists.

**Comment by denchat** [comment]
@gioman After further investigation. I'm certained that this is probably some kind of mild regression of label renderer.

I just filed some details about it with a sample project at #33931 . Please re-consider keep that open.
