### ISSUE TITLE
crash using proxy connection (proxy.pac)

### ISSUE THREAD

**Issue by fgianoli** [qgis/QGIS#33919]
**the  plugin manager causes the crash of QGIS under proxy connection**

QGIS crash when I open the plugin manager under proxy (using proxy.pac).
Once configured the proxy under the tab QGIS option, if I try to install a plugin,  QGIS crash.
This error appears only on QGIS 3.10.x.  Versions 3.4.x and 3.8.x are not affected.

**Stack Trace**
```
QMetaObject::activate :
QHttpMultiPart::qt_metacast :
QSslKey::operator!= :
QSslKey::operator!= :
QMetaObject::activate :
QAbstractSocket::proxyAuthenticationRequired :
QMetaObject::activate :
QAbstractSocket::proxyAuthenticationRequired :
QNetworkProxyQuery::networkConfiguration :
QMetaObject::activate :
QAbstractSocket::disconnected :
QAbstractSocket::canReadLine :
QNetworkProxyQuery::networkConfiguration :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
QEventLoop::exec :
QThread::exec :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.10.1-A Coruña
QGIS code revision: ef24c526da
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.14393
**Additional context**
```

**Comment by zanzi77** [comment]
Dear All,
I'm experiencing the same issue as reported above when we try to install plugins. (just selecting the name of the plugin)

![crash](https://user-images.githubusercontent.com/37799124/73170061-c426c480-40fd-11ea-8304-4b2680ab7d7d.JPG)

with QGIS 3.10.2.2 on Windows. No issue with 3.8 or 3.4.x versions

**Comment by aroche** [comment]
Same problem. It happens only when connected to a proxy (with authentication) on Windows. Version 3.10.4. It happens when you click on the name of a plugin in the plugin list.

**Comment by wonder-sk** [comment]
I have just seen this in a training session with QGIS 3.10.10 (at least on windows) - users with proxy set up (and with proxy credentials saved) were getting a crash in plugin manager when just clicking a plugin name in the list of plugins that could be installed - it crashes before users even can try to install a plugin.

**Comment by PeterPetrik** [comment]
cannot replicate on MacOS

**Comment by fgianoli** [comment]
Dear all, I'm still having this issue  with QGIS 3.14.16 under windows.
there is any workaround to avoid this? 
Which kind of test can I do in order to help to figure out the issue?

**Comment by fgianoli** [comment]
Hi! 
We are experiencing this issues since the 3.4 version. 
It's impossible to download any plugin via repository and we have to do it manually via ZIP.
How can we help to solve the problem? Can we do some tests?

**Comment by fgianoli** [comment]
Problem solved by setting the Windows environment variables for the proxy HTTP_PROXY and HTTPS_PROXY
