### ISSUE TITLE
WMS doesn't render layer with duplicate names

### ISSUE THREAD

**Issue by m-kuhn** [qgis/QGIS#33928]
When several layers with equal names are added in a project, only one of them is rendered, the other ones are silently discarded by QGIS Server.

This often happens when adding the same layer multiple times with different geometries because the underlying table is of type GeometryCollection.

**Comment by gioman** [comment]
@m-kuhn a long standing issue as far as I remember.

**Comment by m-kuhn** [comment]
@gioman any duplicate issue reports I didn't discover?

**Comment by Gustry** [comment]
You need to use the last section in Project Properties -> QGIS Server tab. It's checking for duplicated names.

**Comment by m-kuhn** [comment]
@Gustry are you referring to "use layer ids as names"?
Is this a workaround or are you saying it's a "wontfix"?

**Comment by rldhont** [comment]
@m-kuhn it's a wontfix, the OGC services do not have to provide multiple layer with the same name.

In the GetCapabilities, each layer has to have a different name because the name are the identifier. Layers can have the same title. To avoid duplicate name you can use: layer ids or shortname.

@Gustry mentionned the tools in Project Properties -> QGIS Server tab that help you to check your project to avoid duplicate layer name in OGC servcies.

**Comment by m-kuhn** [comment]
I still think something needs to be done. The current situation doesn't seem very helpful, it's very puzzling to just get a partial output with no control over which layer.

I think the most understandable one for users would be exposing 1 layer in GetCapabilities (as done now) but rendering n layers in GetMap requests. GetFeatureInfo and GetLegend requests could also visit all layers transparently. I think that would still be OGC compliant (since it's only an internal implementation detail that there are n layers behind the scene, with possibly some edge cases like colliding feature ids of multiple layers, but that's in the project admins responsibility).

For what I want (my main concern right now): GetDxf are now also proxied through WMS, and layers that are GeometryCollection in the DB that should be merged on the final result again are lost because of this filtering. I'm open to alternative ideas to fix that.

**Comment by elpaso** [comment]
I agree that the current situation is not ideal, perhaps the most user friendly solution would be to issue a warning when there are duplicated names and also automatically/transparently make them unique by appending an incremental suffix.

**Comment by elpaso** [comment]
@jef-n I'm not proposing another naming option, I'm proposing a transparent and automatic way to generate unique names for WMS/WFS typenames just in case there are name clashes.

About using layer ids, I think it's not ideal either: they are supposed to be internal identifiers, they are not user friendly at all, hard to type and hard to remember, and they are not stable: they can change if you recreate the layer in another project.

**Comment by m-kuhn** [comment]
Did you read the second and third paragraphs here https://github.com/qgis/QGIS/issues/33928#issuecomment-576584578 ?

**Comment by elpaso** [comment]
> Did you read the second and third paragraphs here [#33928 (comment)](https://github.com/qgis/QGIS/issues/33928#issuecomment-576584578) ?

Yes, I did. But I'm not sure it's always good idea, it is in in case of multiple wkb types from a single source, but in case of different sources it might lead to unexpected results.

**Comment by m-kuhn** [comment]
That is true, but is this a reason to dismiss the concept as a whole?
What I can see as issues are:
 - colliding feature ids (project admin responsibility)
 - different CRS (reproject or raise exception)
 - anything else that is a showstopper?

**Comment by jef-n** [comment]
> * anything else that is a showstopper?

Different sets of attributes for GetFeatureInfo.

**Comment by m-kuhn** [comment]
Good point, return attributes found, merged attributes or raise exception?
