### ISSUE TITLE
Issue with creating features within new layers in QGIS 3.4.4

### ISSUE THREAD

**Issue by Beckinboots** [qgis/QGIS#33923]
I am having sporadic issues when creating features within new layers in QGIS 3.4.4.  Sometimes they save properly and are editable, other times they vanish and don't show in the attribute table.  Files are usually saved to a server which is when I'm having the issue but they seem to work properly if they're saved to my desktop.  This has never been a problem with previous issues of QGIS and has only started in the last couple of months.  I've been using 3.4.4 since it became the LTR.  Please let me know if you need any more info.  Thanks

**Comment by gioman** [comment]
>  I've been using 3.4.4 since it became the LTR. Please let me know if you need any more info. Thanks

@Beckinboots give a try to a much more recent release as 3.4.15 or 3.10.2 then report back if you still hit the same. If yes we would need detailed steps/data to allow us try replicate. Thanks!

**Comment by Beckinboots** [comment]
@gioman  - a couple of us have updated to version 3.4.15 but the issue persists.  When saving the new layer it seems to go well but then, when trying to edit we get a "commit error" stating that it "cannot reopen datasource XXXXXX.shp layername=New boundary test in update mode".  We are saving to a server and when I look in the folder where the shapefiles are being saved there are still tmp. files there that we can't delete as it says they're still in use even when nothing is open.  When we save to our individual desk tops we have no issues at all.  Could there be a conflict between QGIS and the servers?

**Comment by gioman** [comment]
@Beckinboots my guess is that you just don't have full write permissions where your data/files are. If your data is on a local disk or a server folder, where you have full write permissions, it works as expected?

**Comment by Beckinboots** [comment]
Yes, if it's on a local disk it's absolutely fine.

**Comment by gioman** [comment]
> Yes, if it's on a local disk it's absolutely fine.

@Beckinboots there it is, check the write permissions on your network share.

**Comment by Beckinboots** [comment]
> > Yes, if it's on a local disk it's absolutely fine.
> 
> @Beckinboots there it is, check the write permissions on your network share.

@gioman - thank you.  You've confirmed what I suspected but it's not necessarily the answer I wanted.  I'll go bother IT now.  Thanks again for your help.

**Comment by gioman** [comment]
Reopen of necessary.
