### ISSUE TITLE
Errors for DEM terrain analysis

### ISSUE THREAD

**Issue by Labros89** [qgis/QGIS#33920]
Hi I am trying to do some pre-processing operations. However I use some tools and usually I cannot execute the commands. For example, I use Fill nodata from GDAL and I got the following error:
 INFO    GDAL execution console output
             
             
             gdal_fillnodata [-q] [-md max_distance] [-si smooth_iterations]
             
              [-o name=value] [-b band]
             
              srcfile [-nomask] [-mask filename] [-of format] [-co name=value]* [dstfile]
             
Moreover, I use Fill Sinks (Wang & Liu) and again I cannot run the tool having again error.

I use the last version of QGIS 3.10.1 'A Coruna', actually I downloaded the OSGeo4W Network.

I downloaded a DEM from: https://earthexplorer.usgs.gov/
My DEM is n39_e021_1arc_v3

Please can you tell me what is happening and how can I fix the tools because I cannot work.

**Comment by gioman** [comment]
@Labros89 this sounds familiar :)

>  For example, I use Fill nodata from GDAL and I got the following error:
> INFO GDAL execution console output

![Peek 2020-01-20 14-59](https://user-images.githubusercontent.com/1951107/72736550-d486ee80-3b95-11ea-84f6-b11f183635cc.gif)


> Moreover, I use Fill Sinks (Wang & Liu) and again I cannot run the tool having again error.

![Peek 2020-01-20 15-01](https://user-images.githubusercontent.com/1951107/72736574-dd77c000-3b95-11ea-890a-0dabb581406e.gif)


The above is on 3.10.2, installed using the OSGeo4W installer.

**Comment by Labros89** [comment]
I am having the same problems.

Do you know how can I solve it?

**Comment by gioman** [comment]
> I am having the same problems.

@Labros89 you may have misunderstand my answer with the screencasts: there are no problems. The outputs are created, ignore the message at the end of the SAGA processing.

**Comment by Labros89** [comment]
You are right, however I would like ask you, In the parameter "validity mask" you do not use a layer. However when I run the tool the parameter has as a default the DEM and I cannot remove it. Do you know how can I do remove? and do you believe that this is the problem?

**Comment by gioman** [comment]
> Do you know how can I do remove?

please update to 3.10.2 with the osgeo4w installer and check if it makes any difference.

**Comment by Labros89** [comment]
How can I update to 3.10.2? Sorry about this but I am a new user of QGIS and in general of GIS

**Comment by gioman** [comment]
Run the osgeo4w (network) installer, follow the "advanced" option, choose the "qgis" and "saga-ltr" packages, next next finish.

**Comment by Labros89** [comment]
Dear gioman, I updated and it works. 
Thanks a lot really!!
