### ISSUE TITLE
No funciona el terrain profile con ruta de GPS en 3.10.1 ni 3.10.2

### ISSUE THREAD

**Issue by corx28** [qgis/QGIS#33932]
Lo he probado en varios ordenadores. Estamos dando un curso y nos ha pasado a todos los que usamos estas versiones y he venido a casa y pasaba lo mismo.
Cuando voy a hacer un perfil de terreno de una ruta gpx al seleccionar la ruta se queda "en espera" hasta que se cuelga.

Gracias

**Comment by luipir** [comment]
ES: Titulo y descripcion hay que hacerla en ingles ya que la comunidad es internacional.
EN: title and description have to be in english due the fact that this is a international community

please provide a test procedure and eventually test data set and much more details about platform, OS version and qgis about snapshot. Please before to report, test with a clean qgis profile.

I'm closing the issue iviting you to open a new one in English. Thank you.
ES: Porfa reabre una nueva issue en ingles y con mas detalles
