### ISSUE TITLE
Flash the Feature When it is Found through Search Menu in the Status Bar

### ISSUE THREAD

**Issue by ar-siddiqui** [qgis/QGIS#33934]
**Feature description.**
QGIS would rock even more if it would Flash the Feature When it is Found through Search Menu in the Status Bar. It gets difficult to figure out which feature was found if there are multiple features in the canvas extent.

**Additional context**
See here it is difficult to figure out which pipe it found.
![image](https://user-images.githubusercontent.com/53625184/72759919-1bc8ab80-3ba5-11ea-8064-edcf974aaf5c.png)

**Comment by ismailsunni** [comment]
Already implemented in QGIS 3.24
