### ISSUE TITLE
Vertex Tool cache not refreshing after changes to line features

### ISSUE THREAD

**Issue by NealKrautz** [qgis/QGIS#33947]
**Vertex Tool cache not refreshing after changes to line features**

The environment for this bug is editing line features in a (PostGIS) database layer.  The Vertex Tool initially shows all the vertices on hover, and allows editing for all line features existing when the QGIS session was started, or when the layer is opened.  The Vertex Tool also correctly shows vertices on hover for line features added prior to the Vertex Tool being opened for the first time in the session.  This is expected behaviour.

The bug is activated because a necessary and reasonable trigger function in the database modifies the line feature before commit.  Once the Vertex tool has been used initially in that session, subsequent new lines produced by the database are no longer editable.  Even though all these new lines are correctly displayed on the canvas, they are not refreshed in the Vertex Tool, and cannot be edited.

The workaround is to close QGIS and restart, or remove and re-add the layer.  The Vertex tool then once again sees all vertices.  But, after opening the tool, again no subsequently added or edited lines can be edited.  This means close and reopen, again, and again, and again...

The problem has been observed in versions 3.4 and 3.10, and on both Linux and Windows hosts.

It seems Vertex Tool persistence cache is not refreshing along with the current state of the layer.

This bug can be replicated easily without needing a database with triggers.  Create a file vector layer such as a .shp file.  Start two separate instances of QGIS and open the same vector layer in both.  Add some line features using both instances.  Anything created in one instance will be visible in the other instance (after refreshing).

When opening the Vertex tool for the first time, every feature created by either instance will be editable.  However, once the Vertex Tool has been opened, any new line features subsequently created by the other instance are no longer editable using the Vertex Tool.  Thereafter, each instance can only edit the features that it created, or the features that existed before the Vertex Tool was initially opened.  This is despite the fact that all features are correctly visible in both instances.  (For this demonstration, the second instance would represent the database trigger function.)

![Pre-existing is editable](https://user-images.githubusercontent.com/60124954/72780886-b68bbd80-3c6b-11ea-893e-1cfb323b47e2.jpg)
Hovering shows the pre-existing lines are editable

![Line added by this instance is editable](https://user-images.githubusercontent.com/60124954/72780939-d327f580-3c6b-11ea-9e54-38d26c1fc404.jpg)
Hovering shows lines added by this instance are editable.

![Line added by other instance not editable](https://user-images.githubusercontent.com/60124954/72781022-010d3a00-3c6c-11ea-94e5-04f6d910f78a.jpg)
Hovering on the line created by the other QGIS instance (or a database) does not allow editing.

**Possible solution:**  Have an option to refresh the vertex cache whenever the layer is refreshed on the canvas.  This way the Vertex Tool and the display will always stay synchronized.

**Comment by lbartoletti** [comment]
I think it's already fixed in the latest version.
Ping @troopa81

**Comment by troopa81** [comment]
@NealKrautz You have to set up data dependencies so QGIS will be aware of the database trigger modifications and will refresh the cache. In your scenario, you have to setup your layer as a dependency of itself.

More informations [here](https://oslandia.com/en/2020/01/10/en-qgis-snapping-improvements/)  (circular dependencies)

**Comment by NealKrautz** [comment]
Thanks. This solves the problem.  I never realized that dependencies does what we were looking for.  Searching the web didn't reveal this.  Thanks again.

**Comment by NealKrautz** [comment]
Most appreciated.  Thanks


Neal Krautz
