### ISSUE TITLE
Harmonize 3D map view widget with 2D ones to display the map theme drop-down menu

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#33954]
Afaict, the map theme selection in a 3D map view settings has no effects on the other settings so, maybe for consistency with other map views and allow quick interaction, the map theme selection menu can be placed over the 3D map canvas dock widget instead of within the settings dialog
Current state in 3.10
 ![image](https://user-images.githubusercontent.com/7983394/72801952-f4c4b500-3c4a-11ea-872a-d0325a0a51ab.png)

**Comment by ismailsunni** [comment]
Hi @DelazJ 
While working on it, I found out that there is a relationship between the mesh configuration. If the terrain generation is a mesh, it will be hidden (looking at the code).

Another alternative solution would disable the map theme selection in the toolbar if the terrain is a mesh. I am not sure what is best. Perhaps @wonder-sk has an opinion here.

In the meantime, I have added the map theme switcher:
![image](https://user-images.githubusercontent.com/1421861/73854518-f7baca80-4832-11ea-9c97-760c5e119930.png)

The code is in here: https://github.com/ismailsunni/QGIS/tree/harmonize_3d_map_view
