### ISSUE TITLE
QGIS crashes when closing or creating new project

### ISSUE THREAD

**Issue by nrimbeau** [qgis/QGIS#33964]
h2. User Feedback

Crashed when clicking on New Project. This also happens when closing the software after saving a project, using the cross button at the top right of the window. I think the software is trying to clear layers from the project I'm working on, and it just fails to and crashes.

I have point layers and rasters, mostly, nothing too exotic.

h2. Report Details

*Crash ID*: 2a6c51fed359546871b16499ddcf9df8ecb584ca

*Stack Trace*
<pre>
QSortFilterProxyModel::buddy :
QSortFilterProxyModel::sortRole :
QSortFilterProxyModel::`default constructor closure' :
QMetaObject::activate :
QAbstractItemModel::endRemoveRows :
QMetaObject::activate :
QgsLayerTreeNode::removedChildren :
QMetaObject::activate :
QgsLayerTreeNode::removedChildren :
QMetaObject::activate :
QgsLayerTreeNode::removedChildren :
QMetaObject::activate :
QgsLayerTreeNode::removedChildren :
QMetaObject::activate :
QgsLayerTreeNode::removedChildren :
QgsLayerTreeNode::removeChildrenPrivate :
QgsLayerTreeGroup::removeChildren :
QgsLayerTreeGroup::removeChildNode :
QgsLayerTreeRegistryBridge::layersWillBeRemoved :
QMetaObject::activate :
QgsProject::layersWillBeRemoved :
QMetaObject::activate :
QgsMapLayerStore::layersWillBeRemoved :
QgsMapLayerStore::removeMapLayers :
QgsMapLayerStore::removeMapLayers :
QgsMapLayerStore::removeAllMapLayers :
QgsProject::clear :
QgisApp::closeProject :
QgisApp::fileNew :
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.6.0-Noosa
QGIS code revision: commit:58734527ab
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.0
Running against GDAL: 2.4.0

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by roya0045** [comment]
Please update to the latest version to see if this error still occurs.

**Comment by nrimbeau** [comment]
Hi Alex,

Updated to the latest version. It doesn't crash like before, but I'm still
getting the following:



## User Feedback

Happened after having saved the project, and when trying to close.

## Report Details

**Crash ID**: [c2a7b6a256a8cd7a30b6d3b55b07a618c4808f60]('
https://github.com/qgis/QGIS/search?q=c2a7b6a256a8cd7a30b6d3b55b07a618c4808f60&type=Issues
')


**Stack Trace**

QSortFilterProxyModel::buddy :
QSortFilterProxyModel::sortRole :
QSortFilterProxyModel::`default constructor closure' :
QMetaObject::activate :
QAbstractItemModel::endRemoveRows :
QMetaObject::activate :
QgsLayerTreeNode::removedChildren moc_qgslayertreenode.cpp:297
QMetaObject::activate :
QgsLayerTreeNode::removedChildren moc_qgslayertreenode.cpp:297
QMetaObject::activate :
QgsLayerTreeNode::removedChildren moc_qgslayertreenode.cpp:297
QMetaObject::activate :
QgsLayerTreeNode::removedChildren moc_qgslayertreenode.cpp:297
QMetaObject::activate :
QgsLayerTreeNode::removedChildren moc_qgslayertreenode.cpp:297
QgsLayerTreeNode::removeChildrenPrivate qgslayertreenode.cpp:252
QgsLayerTreeGroup::removeChildren qgslayertreegroup.cpp:161
QgsLayerTreeGroup::removeChildNode qgslayertreegroup.cpp:136
QgsLayerTreeRegistryBridge::layersWillBeRemoved
qgslayertreeregistrybridge.cpp:92
QMetaObject::activate :
QgsProject::layersWillBeRemoved moc_qgsproject.cpp:1085
QMetaObject::activate :
QgsMapLayerStore::layersWillBeRemoved moc_qgsmaplayerstore.cpp:266
QgsMapLayerStore::removeMapLayers qgsmaplayerstore.cpp:147
QgsMapLayerStore::removeMapLayers qgsmaplayerstore.cpp:121
QgsMapLayerStore::removeAllMapLayers qgsmaplayerstore.cpp:203
QgsProject::clear qgsproject.cpp:793
QgisApp::closeProject qgisapp.cpp:11902
QgisApp::fileExit qgisapp.cpp:5676
QWidget::event :
QgisApp::event qgisapp.cpp:1928
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QWidgetPrivate::close_helper :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processCloseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1598
BaseThreadInitThunk :
RtlUserThreadStart :


**QGIS Info**
QGIS Version: 3.10.1-A Coruna
QGIS code revision: ef24c526da
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134


The application wasn't responding for a while, then that happened.

**Comment by gioman** [comment]
> Updated to the latest version. It doesn't crash like before, but I'm still

@nrimbeau plesae try with a new QGIS profile, no 3rd party plugins installed.

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
