### ISSUE TITLE
Grass tools do not work

### ISSUE THREAD

**Issue by Labros89** [qgis/QGIS#33986]
Hi, I am trying to use some Grass tools. Actually I tried to use r.reclass and r.flow but both cannot execute the command. They give the same error:

Traceback (most recent call last):
File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\algs\grass7\Grass7Algorithm.py", line 431, in processAlgorithm
Grass7Utils.executeGrass(self.commands, feedback, self.outputCommands)
File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\algs\grass7\Grass7Utils.py", line 389, in executeGrass
for line in iter(proc.stdout.readline, ''):
File "C:\OSGEO4~1\apps\Python37\lib\encodings\cp1253.py", line 23, in decode
return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9a in position 25: character maps to <undefined>

Probably I have not done something correct with the Python and it is not problem of the software. However, I have tried a lot to solve it but I cannot find a solution.

Can you help me?

I am using the last version of QGIS 'A Coruna' 3.10.2

Thanks in advance

**Comment by alexbruy** [comment]
Duplicates #29845

**Comment by Labros89** [comment]
I so that the solution is to change from Grass to Processing/grass, right? But how can I do it?

**Comment by gioman** [comment]
> But how can I do it?

GRASS support in QGIS/Processing comes out of the box. Just open the Processing toolbox and use any of the provided GRASS tools (no need to know anything about  GRASS locations/mapsets, but you'll get always simple features vectors as outputs).

**Comment by Labros89** [comment]
> > But how can I do it?
> 
> GRASS support in QGIS/Processing comes out of the box. Just open the Processing toolbox and use any of the provided GRASS tools (no need to know anything about GRASS locations/mapsets, but you'll get always simple features vectors as outputs).

I did it but I cannot run any tool...Again I got the same message:
Traceback (most recent call last):
File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\algs\grass7\Grass7Algorithm.py", line 431, in processAlgorithm
Grass7Utils.executeGrass(self.commands, feedback, self.outputCommands)
File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\algs\grass7\Grass7Utils.py", line 389, in executeGrass
for line in iter(proc.stdout.readline, ''):
File "C:\OSGEO4~1\apps\Python37\lib\encodings\cp1253.py", line 23, in decode
return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9a in position 27: character maps to <undefined>

**Comment by Labros89** [comment]
> > But how can I do it?
> 
> GRASS support in QGIS/Processing comes out of the box. Just open the Processing toolbox and use any of the provided GRASS tools (no need to know anything about GRASS locations/mapsets, but you'll get always simple features vectors as outputs).

Still does not work, can you give me more details please?

**Comment by gioman** [comment]
> Still does not work, can you give me more details please?

[Recording #1.zip](https://github.com/qgis/QGIS/files/4098726/Recording.1.zip)

**Comment by alexbruy** [comment]
@Labros89 they does work. In your case there are non-ASCII characters in the path, I already pointed you to the exactly the same issue.
