### ISSUE TITLE
Geotiff Issue on 3.10.1 on Windows

### ISSUE THREAD

**Issue by rjhale1971** [qgis/QGIS#33988]
This was mentioned first on https://lists.osgeo.org/pipermail/qgis-user/2020-January/044693.html

The data is located  ftp://rockyftp.cr.usgs.gov/vdelivery/Datasets/Staged/Maps/HistoricalTopo/GeoTIFF/GA/ and is the GA_Hightower Bald_245924_1988_24000_geo.tif

If you do a gdalinfo on the tiff the first thing you will notice is: 
Files: GA_Hightower Bald_245924_1988_24000_geo.tif
Size is 6600, 8050
Coordinate System is:
PROJCS[**"unnamed",**

If this file is added (by drag and drop or using data source manager) to QGIS 3.10.1 on windows the projection of the canvas window defaults to unknown and it never picks up the coordinate information when changing the canvas projection. 

If this file is added to QGIS 3.10.1 on Ubuntu the canvas will default to unknown BUT if you change the canvas to 4326 or anything else you get a transformation dialogue and the file moves to the correct location. 

The big difference between the two is proj 6 vs 5.2 I believe. 

The user had reported everything was fine in 3.8. 

I have noticed this behaviour when adding GeoPDFs to QGIS on windows and linux but didn't really think much of it as those were generated out on an ESRI Environment. I have attached a Geopdf that mimics this behavior (canvas default to unknown and has to be changed). The Geopdf has a projection readable in GDALINFO though).

I was for a bit running 3.11 Master and everything seemed fine there. I don't think this is a huge bug - but it's something inconsistent. 

Thanks much
Randy

[_ags_5cfcdf8bfa224793bdd31b2c67b70660.pdf](https://github.com/qgis/QGIS/files/4098276/_ags_5cfcdf8bfa224793bdd31b2c67b70660.pdf)

**Comment by gioman** [comment]
> I was for a bit running 3.11 Master and everything seemed fine there. I don't think this is a huge bug - but it's something inconsistent.

@rjhale1971 I just tried it on my Windows VM with QGIS master (so the latest and greatest GDAL and PROJ) and I think is ok. I don't think that at this point is worth of testing with anything less than that.

**Comment by rjhale1971** [comment]
Excellent - I wasn't sure if I should have worried since it worked in master - but - I appreciate your time looking at it.

**Comment by gioman** [comment]
> Excellent - I wasn't sure if I should have worried since it worked in master - but - I appreciate your time looking at it.

Anyway better leave the last word to a developer.

**Comment by nyalldawson** [comment]
This isn't a QGIS issue. It's either a dataset issue or something in GDAL.

Using gdalinfo to identify the CRS for the dataset gives:

```
Coordinate System is:
PROJCRS["unnamed",
    BASEGEOGCRS["NAD27",
        DATUM["North American Datum 1927",
            ELLIPSOID["Clarke 1866",6378206.4,294.978698213898,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4267]],
    CONVERSION["Transverse Mercator",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",-83.5629999999992,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",1,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["easting",east,
            ORDER[1],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]],
        AXIS["northing",north,
            ORDER[2],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]]]
```

Plugging this CRS info `projinfo --identify` does not match any known EPSG codes. Do you know what the expected CRS for these layers is?

**Comment by rjhale1971** [comment]
Should be UTM Zone 17 North NAD27 which is EPSG:26717

**Comment by nyalldawson** [comment]
Thanks.

projinfo reports EPSG:26717 as:

```
PROJCS["NAD_1927_UTM_Zone_17N",GEOGCS["GCS_North_American_1927",DATUM["D_North_American_1927",SPHEROID["Clarke_1866",6378206.4,294.978698213898]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Transverse_Mercator"],PARAMETER["False_Easting",500000.0],PARAMETER["False_Northing",0.0],PARAMETER["Central_Meridian",-81.0],PARAMETER["Scale_Factor",0.9996],PARAMETER["Latitude_Of_Origin",0.0],UNIT["Meter",1.0]]
```

whereas the included dataset uses:

```
PROJCS["Transverse_Mercator",GEOGCS["GCS_North_American_1927",DATUM["D_North_American_1927",SPHEROID["Clarke_1866",6378206.4,294.9786982]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",-83.56299999999918],PARAMETER["scale_factor",1],PARAMETER["false_easting",0],PARAMETER["false_northing",0],UNIT["Meter",1]]
```

The definition is quite different (e.g. central meridian is -81 officially, -83.56299999999918 in the dataset)

**Comment by rjhale1971** [comment]
Welp - let me do some digging and see. It may be NAD27 Georgia West - I'll report back with the correct projection.

**Comment by nyalldawson** [comment]
Great, thanks Randal! if this is a bug it's in either GDAL or PROJ, but I'm happy to coordinate between the projects...

**Comment by rjhale1971** [comment]
No Problem - someone just popped up on the users list with the same problem. These files are so old (I worked for the original map agency unit these came from) which in part makes me old. Sigh. I feel compelled to get it fixed.

**Comment by rjhale1971** [comment]
Contacted the USGS. Nothing currently makes sense with the projection of this file. The tfw is wrong in my opinion. The Definition of the file looks to be a very old ESRI WKT definition.

**Comment by gioman** [comment]
so what to do with this ticket?

**Comment by rjhale1971** [comment]
I'll close it - I'm working back through the QGZ file and I can't figure out an exact cause of it crashing. If I figure it out I'll re-open and provide a better report.

**Comment by gioman** [comment]
Maybe you can attach the TIF+TFW?

**Comment by rjhale1971** [comment]
I don't know. I'm not sure if QGIS reads the tfw file first or the Tiff. Right now it appears to be reading the tfw file - of course I'm assuming the tfw file is wrong based off looks. I'm going to plot the corner as a point and see where it falls. The Tiff itself is still "undefined" but whatever has happened from 3.6 to now has some users complaining QGIS (proj/gdal) is wrong - which I'm starting to think isn't the case.

**Comment by nyalldawson** [comment]
Closing this for now -- all signs point to it being an error with the data source, not a QGIS/PROJ issue.
