### ISSUE TITLE
Coordinate transformation is broken for non EPSG CRSs

### ISSUE THREAD

**Issue by Dkrav-UA** [qgis/QGIS#33994]
**Describe the bug**
QgsCoordinateTransform doesn't work with non-standard (non-EPSG) coordinate systems.
Everything was working on qgis 3.10.1. The problem occurred after an upgrade to 3.10.2.
**How to Reproduce**
src = QgsCoordinateReferenceSystem()
            src.createFromProj4('+proj=tmerc +lat_0=0 +lon_0=25.875 '
                                '+k=1.00003628 +x_0=39903.694 '
                                '+y_0=-5331008.193 +ellps=krass '
                                '+towgs84=23.92,-141.27,-80.9,-0,0.35,0.82,-0.12 '
                                '+units=m +no_defs')
dest.createFromProj4('+proj=merc +a=6378137 +b=6378137 '
                                 '+lat_ts=0.0 +lon_0=0.0 '
                                 '+x_0=-7.0 +y_0=-10.0 +k=1.0 '
                                 '+units=m +nadgrids=@null +wktext  +no_defs')
xform = QgsCoordinateTransform(src, dest, QgsProject.instance())
x = 39388.1
y = 18656.3
pt1 = xform.transform(QgsPointXY(x, y))

pt1 returns the same coordinates.
------------------------------------------------------------
 xform = QgsCoordinateTransform(QgsCoordinateReferenceSystem("EPSG:4326"),
                                   QgsCoordinateReferenceSystem("EPSG:3857"), QgsProject.instance())
x = 25.866182
y = 48.277826
pt1 = xform.transform(QgsPointXY(x, y))
pt1 returns the transformed coordinates.

**QGIS and OS versions**

OS: Ubuntu 18.04
QGIS: 3.10.2 and 3.4.15-Madeira

**Comment by nyalldawson** [comment]
I can't reproduce -- 

On a proj 6.3 based build I get `2879611.57913811970502138 6153274.99715435784310102` for pt1, which is identical to the results given by the proj cct utility when converting between these two proj strings.

On a proj 5.2 based build I get `2879425.3780604531057179 6153228.46810947172343731`, which is slightly different but likely a result of the less accurate transformations applied in proj < 6.

**Comment by Dkrav-UA** [comment]
> I can't reproduce --
> 
> On a proj 6.3 based build I get `2879611.57913811970502138 6153274.99715435784310102` for pt1, which is identical to the results given by the proj cct utility when converting between these two proj strings.
> 
> On a proj 5.2 based build I get `2879425.3780604531057179 6153228.46810947172343731`, which is slightly different but likely a result of the less accurate transformations applied in proj < 6.

Which version of QGIS?

**Comment by nyalldawson** [comment]
Master

**Comment by Dkrav-UA** [comment]
> Master

This is strange. But it works in plain 3.10.2. 
I don't know why. I corrected the projections in my qgis.db. Maybe it somehow connected?

**Comment by nyalldawson** [comment]
I'm unsure -- I'll need more detailed steps to reproduce to take this further.

**Comment by Dkrav-UA** [comment]
> I'm unsure -- I'll need more detailed steps to reproduce to take this further.

Strange, but it's a fact! qgis.db affects coordinate transformation.
Following "qgis.db" leads to bad transformation.
[qgis.db.zip](https://github.com/qgis/QGIS/files/4158394/qgis.db.zip)



> src = QgsCoordinateReferenceSystem()
> src.createFromProj4('+proj=tmerc +lat_0=0 +lon_0=25.875 ''+k=1.00003628 +x_0=39903.694 ''+y_0=-5331008.193 +ellps=krass ''+towgs84=23.92,-141.27,-80.9,-0,0.35,0.82,-0.12 ''+units=m +no_defs')
> True
> dest = QgsCoordinateReferenceSystem()
> dest.createFromProj4('+proj=merc +a=6378137 +b=6378137 ''+lat_ts=0.0 +lon_0=0.0 ''+x_0=-7.0 +y_0=-10.0 +k=1.0 ''+units=m +nadgrids=@null +wktext +no_defs')
> True
> xform = QgsCoordinateTransform(src, dest, QgsProject.instance())
> x = 39388.1
> y = 18656.3
> pt1 = xform.transform(QgsPointXY(x, y))
> pt1
> <QgsPointXY: POINT(39388.09999999999854481 18656.2999999999992724)>
> 



With this "qgis.db" everything is ok.
[qgis.db.ok.zip](https://github.com/qgis/QGIS/files/4158420/qgis.db.ok.zip)

> 
> src = QgsCoordinateReferenceSystem()
> src.createFromProj4('+proj=tmerc +lat_0=0 +lon_0=25.875 ''+k=1.00003628 +x_0=39903.694 ''+y_0=-5331008.193 +ellps=krass ''+towgs84=23.92,-141.27,-80.9,-0,0.35,0.82,-0.12 ''+units=m +no_defs')
> True
> dest = QgsCoordinateReferenceSystem()
> dest.createFromProj4('+proj=merc +a=6378137 +b=6378137 ''+lat_ts=0.0 +lon_0=0.0 ''+x_0=-7.0 +y_0=-10.0 +k=1.0 ''+units=m +nadgrids=@null +wktext +no_defs')
> True
> xform = QgsCoordinateTransform(src, dest, QgsProject.instance())
> x = 39388.1
> y = 18656.3
> pt1 = xform.transform(QgsPointXY(x, y))
> pt1
> <QgsPointXY: POINT(2879425.3780604531057179 6153228.46810947172343731)>

**Comment by roya0045** [comment]
@Dkrav-UA  Still valid in more recent versions?

**Comment by Dkrav-UA** [comment]
> 
> 
> @Dkrav-UA Still valid in more recent versions?

No. 3.12.1 works fine.
