### ISSUE TITLE
Change in CRS format in .prj for the same projection

### ISSUE THREAD

**Issue by si-kov** [qgis/QGIS#34007]
The format of the text describing the geographic project as output in the .prj file associated with shapefiles appears to have changed since version 3.10.0. I noticed this issue in v3.10.1 and have just checked with v3.10.2 and the problem persists.

I've not tested for other projections, but here are the contents of the .prj file before and after for GDA94 / MGA Zone 55:

Before:
PROJCS["GDA94_MGA_zone_55",GEOGCS["GCS_GDA_1994",DATUM["D_GDA_1994",SPHEROID["GRS_1980",6378137,298.257222101]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",147],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",500000],PARAMETER["false_northing",10000000],UNIT["Meter",1]]

After:
PROJCS["GDA_1994_MGA_Zone_55",GEOGCS["GCS_GDA_1994",DATUM["D_GDA_1994",SPHEROID["GRS_1980",6378137.0,298.257222101]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Transverse_Mercator"],PARAMETER["False_Easting",500000.0],PARAMETER["False_Northing",10000000.0],PARAMETER["Central_Meridian",147.0],PARAMETER["Scale_Factor",0.9996],PARAMETER["Latitude_Of_Origin",0.0],UNIT["Meter",1.0]]

The changes might look subtle, but they are there. Problematic for me as this affects external hydraulic modelling software (TUFLOW) which uses shapefiles as input layers, and TUFLOW detects that the geographic projection is different.

I searched to see if there was any "agreed" change in relation to GDA2020 coming online but that turned up nothing. Is this format change correct?

Cheers,
Simon

QGIS version 3.10.2
OS Windows 10

**Comment by nyalldawson** [comment]
This would be coming from the gdal library, not qgis

**Comment by si-kov** [comment]
Hi Nyall

Thanks for the reply - I'll admit I'm not fully across all elements and components being used in the background but your reply enabled me to do some digging... from what I can tell, I think ESRI have created a new WKT for GDA94 Zone XX which differs from the EPSG WKT. Appears that ESRI adopted a new projection engine database v10.8.0 a couple of months back which probably coincided with the QGIS release when I first encountered this issue (albeit I didn't install that version of QGIS until late December).

I have a couple of workarounds at my end for dealing with this, but is it feasible to have an option in QGIS to use non-ESRI WKT when writing out the .prj file?

Cheers,
Simon

**Comment by nyalldawson** [comment]
What I mean is that QGIS uses GDAL to write outputs like this, and it's the GDAL library itself which is creating the prj output file. You'll need to open a bug with the gdal project: https://github.com/OSGeo/gdal

**Comment by si-kov** [comment]
Got it. Thanks again

**Comment by rouault** [comment]
I don't see this is as a GDAL (or in that instance a PROJ) bug. 
What GDAL/PROJ writes is the official WKT representation for EPSG:28355 from ESRI.
From https://raw.githubusercontent.com/Esri/projection-engine-db-doc/master/csv/pe_list_projcs.csv :
```
28355,28355,"PE_PCS_GDA_1994_MGA_55","GDA_1994_MGA_Zone_55","PROJCS[""GDA_1994_MGA_Zone_55"",GEOGCS[""GCS_GDA_1994"",DATUM[""D_GDA_1994"",SPHEROID[""GRS_1980"",6378137.0,298.257222101]],PRIMEM[""Greenwich"",0.0],UNIT[""Degree"",0.0174532925199433]],PROJECTION[""Transverse_Mercator""],PARAMETER[""False_Easting"",500000.0],PARAMETER[""False_Northing"",10000000.0],PARAMETER[""Central_Meridian"",147.0],PARAMETER[""Scale_Factor"",0.9996],PARAMETER[""Latitude_Of_Origin"",0.0],UNIT[""Meter"",1.0]]","GDA 1994 MGA Zone 55","EPSG","2.1(3.0.1)","no","Australia - 144~E to 150~E",-50.89,-9.23,144.0,150.01
```

**Comment by si-kov** [comment]
> I don't see this is as a GDAL (or in that instance a PROJ) bug.
> What GDAL/PROJ writes is the official WKT representation for EPSG:28355 from ESRI.
> From https://raw.githubusercontent.com/Esri/projection-engine-db-doc/master/csv/pe_list_projcs.csv :
> 
> ```
> 28355,28355,"PE_PCS_GDA_1994_MGA_55","GDA_1994_MGA_Zone_55","PROJCS[""GDA_1994_MGA_Zone_55"",GEOGCS[""GCS_GDA_1994"",DATUM[""D_GDA_1994"",SPHEROID[""GRS_1980"",6378137.0,298.257222101]],PRIMEM[""Greenwich"",0.0],UNIT[""Degree"",0.0174532925199433]],PROJECTION[""Transverse_Mercator""],PARAMETER[""False_Easting"",500000.0],PARAMETER[""False_Northing"",10000000.0],PARAMETER[""Central_Meridian"",147.0],PARAMETER[""Scale_Factor"",0.9996],PARAMETER[""Latitude_Of_Origin"",0.0],UNIT[""Meter"",1.0]]","GDA 1994 MGA Zone 55","EPSG","2.1(3.0.1)","no","Australia - 144~E to 150~E",-50.89,-9.23,144.0,150.01
> ```

Yes, and from what I can tell this is from ESRI's recently updated projection database, which is being used to create the .prj file when creating a new shapefile from within QGIS.

I should add that late yesterday I discovered that I get a different result (i.e. different content in the .prj file) if using the "Define layer projection" routine (algorithm ID 'qgis.definecurrentprojection') to create the .prj file, and the result via this routine is more consistent with the EPSG WKT.

So it would appear that some QGIS routines use the ESRI database and other routines don't. As a user, I don't seem to have any control over which projection database or format is being used. Seems rather crazy that I can have 3 different WKT formats in my .prj file for the same projection, and all three are valid.

Wouldn't it be nice if we could just have one system???!!

**Comment by rouault** [comment]
> So it would appear that some QGIS routines use the ESRI database and other routines don't.

Yes, when QGIS itself writes a .prj, it must uses the WKT1(-OGC/-GDAL) style.
When GDAL/OGR writes a .prj for a Shapefile, it uses the WKT1-ESRI style (which is what is supposed to be written for Shapefiles)

> Wouldn't it be nice if we could just have one system???!!

Ah ah, there are at least 4 different standards/variants: WKT1-ESRI, WKT1(-OGC/-GDAL), WKT2:2015, WKT2:2019 . Each with different variations how software understand & implement them :-). For example, PROJ 6 has updated the way it writes WKT1-ESRI compared to previous GDAL 2.X versions used different dictionaries. Confusing, isn't it :-) ?
