### ISSUE TITLE
Strange crash

### ISSUE THREAD

**Issue by EricMcKeen** [qgis/QGIS#34005]
Hi all.

I'm fairly new to QGIS but have been experiencing a strange repeated crash today.

Basically, everything seems to run fine, but occasionally when I attempt to save a layer/output, as I'm typing the name in the windows explorer window QGIS will instantly close. Then, all shortcuts to reopen QGIS will produce the error "The item 'qgis-bin.exe' that this shortcut refers to has been changed or moved, so this shortcut will no longer work properly.

I tried uninstalling and reinstalling twice but it keeps happening. The weird thing is, it isn't happening every time I try to save something, 90% of the time everything works fine.

Any ideas?

Cheers

**Comment by luipir** [comment]
Hi @EricMcKeen do you have WFS layers? are you able to test master version (e.g. qgis-dev)? if so, please wait one or two days waiting for merge of latest fixes that would face these "strange" issues.

**Comment by NathanW2** [comment]
@EricMcKeen Can you also include the QGIS version inside any bug reports as the issue might have been fixed in a new version.

**Comment by gioman** [comment]
@EricMcKeen also try is using a new QGIS profile helps (do not install any 3rd party plugin).

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
