### ISSUE TITLE
QGIS 3.10.1 gdal_merge module missing

### ISSUE THREAD

**Issue by MrZombie69232** [qgis/QGIS#34001]
I tried merging two shapefiles but I got error as following

**GDAL command output:
C:\PROGRA~1\QGIS3~1.10\bin\python3.exe: No module named gdal_merge
**
Earlier it was working fine but as I upgraded to 3.10.1 the problem started 

_I re-installed it twice but still facing this issue_

**Comment by gioman** [comment]
@MrZombie69232 upgrade to 3.10.2

**Comment by Gustry** [comment]
It has already been fixed according to the number of closed tickets given by a search : 
https://github.com/qgis/QGIS/search?q=gdal_merge&type=Issues
