### ISSUE TITLE
[Label] Capitalize first letter not working properly

### ISSUE THREAD

**Issue by ghtmtt** [qgis/QGIS#34008]
The "Capitalize first letter" in the "Formatting" tab is not working when the cell content is already all capitalized:

![immagine](https://user-images.githubusercontent.com/2884884/73053928-65591500-3e89-11ea-83b7-a565b302489f.png)

No problems if the cell contain mixed lower can upper strings

**QGIS and OS versions**

QGIS 3.10 and QGIS 3.11 on Linux Debian

**Comment by elpaso** [comment]
Sometimes they are back https://github.com/qgis/QGIS/issues/29889

**Comment by pigreco** [comment]
CONFIRM

OSGeo4W64  3.10.2-2 e master -  WIN 10

![image](https://user-images.githubusercontent.com/7631137/73065836-d1954200-3ea4-11ea-933d-3eb885f0cc1e.png)

**Comment by ghtmtt** [comment]
@elpaso I totally forgot the discussion,. By searching for similar issues I forget to uncheck the "is open" option. Thanks

**Comment by pigreco** [comment]
IMHO anything confusing the user is bug.

m2c
