### ISSUE TITLE
QGIS Plugin Repository - Improper Parsing of 0 after period

### ISSUE THREAD

**Issue by Saijin-Naib** [qgis/QGIS#34019]
**Describe the bug**
Currently two plugins show a mis-match between installed/available versions, despite actually being the latest available versions.

**How to Reproduce**
Hard to reproduce, but currently visible in the Plugin Manager. There have been other plugins hit by this same parsing issue, but I can't recall what ones, nor do I have screenshots at current.

It seems to be a parsing issue with the digit "0" following a delimiter "."

I vaguely remember seeing a PR about delimter parsing for Plugins being adjusted, but I can't find it at the moment.

**QGIS and OS versions**

QGIS version | 3.10.2-A Coruña | QGIS code revision | d4cd3cfe5a
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.3 | Running against GDAL/OGR | 3.0.3
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.0 | Running against PROJ | Rel. 6.3.0, January 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | CalculateGeometry; guided_offline_editing; MemoryLayerSaver; networks; openlayers_plugin; ORStools; PeliasGeocoding; PluginLoadTimes; realcentroid; snail; SpreadsheetLayers; db_manager; MetaSearch; processing

**Additional context**
HCMCGIS: Installed (20.01.20) | Available (20.1.20)  
![image](https://user-images.githubusercontent.com/19295950/73079168-be2cab80-3e91-11ea-9562-ffcd4a1a0ce3.png)

MergeIn: Installed (2020.01) | Available (2020.1)
![image](https://user-images.githubusercontent.com/19295950/73079249-dc92a700-3e91-11ea-9451-34a76a8a650d.png)

**Comment by Pedro-Murteira** [comment]
@Saijin-Naib The plugins mentioned don't appear on the "upgradeable" tab after installing the latest version, at least for me. are you still having this issue? (QGIS 3.16.15 and 3.22.2)
Mergin Installed version	2021.5.1
HCMGIS Installed version 21.8.28
