### ISSUE TITLE
Crashing when changing layers

### ISSUE THREAD

**Issue by plovett** [qgis/QGIS#34016]
## User Feedback

I was trying to move between layers via the panel on the left of the screen, when it froze then crashed. It is quite common. The layer i was moving from was open for edits and i had right clicked on it to look at node data. I then clicked on to a different layer that was not open for edits, and it crashed. 

## Report Details

*Crash ID*: 31cacd143ad750aedcb433e6f1bc4a692e8a72e0

*Stack Trace*
<pre>
QgsVertexEditorModel::data :
QModelIndex::data :
QWidget::event :
QFrame::event :
QFrame::event :
QAbstractScrollArea::viewportEvent :
QAbstractItemView::viewportEvent :
QFrame::event :
QAbstractScrollArea::viewportEvent :
QAbstractItemView::viewportEvent :
QTranslator::translate :
</pre>

*QGIS Info*
QGIS Version: 3.4.12-Madeira
QGIS code revision: 625767347a
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by gioman** [comment]
@plovett please try with 3.4.15 or 3.10.2

also try with a new QGIS profile (no 3rd party plugins installed)

if problem continue add/attach/link a project with data we can use to replicate.

**Comment by nirvn** [comment]
I'm pretty sure this is fixed already.

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
