### ISSUE TITLE
freezecrash when zooming out rasterlayers 

### ISSUE THREAD

**Issue by davwis** [qgis/QGIS#34013]
## User Feedback

zooming rasterlayers with quadro card activated..

## Report Details

**Crash ID**: [8f5d13fa3efd1d2720c7edf15577a64b3e660500]('https://github.com/qgis/QGIS/search?q=8f5d13fa3efd1d2720c7edf15577a64b3e660500&type=Issues')

**Stack Trace**
<pre>
MoveSmall memcpy.asm:235
QgsGdalProvider::readBlock qgsgdalprovider.cpp:944
QgsGdalProvider::block qgsgdalprovider.cpp:672
QgsSingleBandPseudoColorRenderer::block qgssinglebandpseudocolorrenderer.cpp:213
QgsBrightnessContrastFilter::block qgsbrightnesscontrastfilter.cpp:118
QgsHueSaturationFilter::block qgshuesaturationfilter.cpp:123
QgsRasterResampleFilter::block qgsrasterresamplefilter.cpp:193
QgsRasterProjector::block qgsrasterprojector.cpp:878
QgsRasterIterator::readNextRasterPartInternal qgsrasteriterator.cpp:130
QgsRasterDrawer::draw qgsrasterdrawer.cpp:60
QgsRasterLayerRenderer::render qgsrasterlayerrenderer.cpp:266
QgsMapRendererParallelJob::renderLayerStatic qgsmaprendererparalleljob.cpp:265
QtConcurrent::MapKernel<QList<LayerRenderJob>::iterator,QtConcurrent::FunctionWrapper1<void,LayerRenderJob & __ptr64> >::runIteration qtconcurrentmapkernel.h:69
QtConcurrent::MapKernel<QList<QgsImageOperation::ImageBlock>::iterator,QgsImageOperation::ProcessBlockUsingPixelOperation<QgsImageOperation::ShadeFromArrayOperation> >::runIterations qtconcurrentmapkernel.h:78
QtConcurrent::IterateKernel<QList<QgsImageOperation::ImageBlock>::iterator,void>::forThreadFunction qtconcurrentiteratekernel.h:256
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.2-A Coru�a
QGIS code revision: d4cd3cfe5a
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.3
Running against GDAL: 3.0.3

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by luipir** [comment]
do you have installed latest 3.10.2 build? e.g. 3.10.2-2?

**Comment by davwis** [comment]
yes 3.10.2 but it started in 3.10.1 so its the same problem

**Comment by davwis** [comment]
its the version found here: https://qgis.org/downloads/QGIS-OSGeo4W-3.10.2-2-Setup-x86_64.exe

**Comment by davwis** [comment]
one wms-service and one geotiff.. maybe it has to do with overlay feature of the wms service.. but im guessing..

**Comment by luipir** [comment]
> its the version found here

ok, sorry mine was a unuseful question I can deduce from "QGIS code revision: d4cd3cf"

**Comment by luipir** [comment]
as usual... try before with:
clean install and/or clean qgis profile

then prepare a test project to replicate (do not send your cuadro card ;) )

**Comment by gioman** [comment]
> then prepare a test project to replicate (do not send your cuadro card ;) )

but actually I have a quadro graphic card (although I am on Linux and will not install windows on this machine), so I would be keen to receive all the details and data to try replicate.

**Comment by davwis** [comment]
still does not work. removed profile and reinstalled. want the .qgz file?

**Comment by davwis** [comment]
i cant send the data im working on.. not open source

**Comment by roya0045** [comment]
@davwis is it the combination that make things crash or only one of the two?

**Comment by davwis** [comment]
its a combination. they work fine alone in empty project. but in the project im working on there are also a hillshade of the geotiff and some shapefiles with gradiant coloring.. so there is quite alot going on.

**Comment by davwis** [comment]
![image](https://user-images.githubusercontent.com/60259053/73070869-b7159580-3eb1-11ea-87bc-0a6499280874.png)

**Comment by elpaso** [comment]
Maybe related to #33711 , how are your resampling settings?

**Comment by davwis** [comment]
biliniar and cubic.. so yes maybe i will try to change and see

**Comment by davwis** [comment]
nope. still crashed.

**Comment by gioman** [comment]
>  not open source

@davwis yeah ok... can't you just clip your data to an extent that is enough to replicate the problem? or even prepare/use fake data.

**Comment by elpaso** [comment]
@davwis the options are in redering settings, there is no bilinear or cubic, just average and nearest-neighbours.

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
