### ISSUE TITLE
Support for comments in filter expressions

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#34011]
**Feature description.**
Please add support for comments in filter expressions.

Filtering features on a layer is useful for many things. For documenting the reason why or to document a complex expression it would be great if we could add comments (like in other expressions, e.g. for field calculations or overrides) to the filter expressions.

Status quo:
`"field" = 'value'`

Filter expression with comment:
`"field" = 'value'  -- value means foo because of bar`

Currently this leads to 0 rows being returned.

**Comment by roya0045** [comment]
This seems like a minefield as this could break parsing in so many ways.

**Comment by alexbruy** [comment]
Seems duplicates #19277.

**Comment by kannes** [comment]
Indeed!
