### ISSUE TITLE
DB Manager using deprecated signature ST_Estimated_Extent for PostGIS 2.1+

### ISSUE THREAD

**Issue by wrass** [qgis/QGIS#34014]
**Describe the bug**

Deprecation warnings are logged by PostGIS whenever users select tables in the QGIS DB Manager.

**How to Reproduce**

1. Open DB Manager
2. Select a PostGIS database and schema
3. Select a database table to view info
4. See warnings in PostgreSQL log: ```"ST_Estimated_Extent signature was deprecated in 2.1.0. Please use ST_EstimatedExtent"```

**QGIS and OS versions**

QGIS 3.10.2-A Coruña
PostGIS 2.1 or above

**Additional context**

The source of the issue seems to be:
https://github.com/qgis/QGIS/blob/d39b6ac77d0abf89dcd50fb6b07d6c47321971c4/python/plugins/db_manager/db_plugins/postgis/connector.py#L730

This could do with a PostGIS version check similar to the one included in qgspostgresprovider.cpp (https://github.com/qgis/QGIS/commit/99cee10cf96314ae911a6d8b99d6a43015a3cf83).

**Comment by alexbruy** [comment]
Already fixed.
