### ISSUE TITLE
CRASH 

### ISSUE THREAD

**Issue by ashish4ll** [qgis/QGIS#34010]
Crash ID: cd240faef663603de24a8089d32bb225f5d5dfaf

Stack Trace

QMetaObject::disconnect :
QObject::disconnectImpl :
QgsVertexTool::setHighlightedVertices :
QgsVertexTool::deactivate :
QgsMapCanvas::setMapTool :
QMetaObject::activate :
QAction::triggered :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.10.1-A Coru�a
QGIS code revision: ef24c526da
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by luipir** [comment]
Thank you @ashish4ll for you help. Please test with latest qgis 3.10.2-2 and if carsh is still there, then also with master.
If it persists, please try to setup a procedure and data to replicate the crash.

**Comment by gioman** [comment]
@ashish4ll also try with a new QGIS profile (no 3rd party plugins installed). Also a more meaningful subject helps.
