### ISSUE TITLE
Strange symbols in field calculator

### ISSUE THREAD

**Issue by krvrd** [qgis/QGIS#34023]
QGIS 3.10.1
MacOS 10.15.2
There is strange symbols when I input some expression in field calculator. Strange symbols is too small and underline brackets, too small quotation marks and others.
![image](https://user-images.githubusercontent.com/36080079/73121242-4f327e00-3f89-11ea-958b-187f6ea13f69.png)

QGIS 2
![image](https://user-images.githubusercontent.com/36080079/73121399-b43aa380-3f8a-11ea-8710-a08b0edf1a1e.png)
The symbols are normal.

**Comment by roya0045** [comment]
I feel like this is just something in your (customized?) display parameters that affects QT.

**Comment by krvrd** [comment]
Where I can reset it to default?

**Comment by roya0045** [comment]
I don't think there is an explicit reset button, but you could take a screenshot of your settings-general-application setup to see if those settings alone can replicate this.

**Comment by gioman** [comment]
> Where I can reset it to default?

@krvrd try a new QGIS profile 

settings > users profiles > new profile

**Comment by krvrd** [comment]
> > Where I can reset it to default?
> 
> @krvrd try a new QGIS profile
> 
> settings > users profiles > new profile

Just try create and change profile.

![image](https://user-images.githubusercontent.com/36080079/73135425-c253f700-4052-11ea-8474-632532b4d0ac.png)

**Comment by krvrd** [comment]
> I don't think there is an explicit reset button, but you could take a screenshot of your settings-general-application setup to see if those settings alone can replicate this.

![image](https://user-images.githubusercontent.com/36080079/73135449-30002300-4053-11ea-8a4b-af63b5b2d272.png)

**Comment by gioman** [comment]
@krvrd this is QGIS 3.10.1 on Catalina here:

![Screenshot 2020-01-27 at 13 49 18](https://user-images.githubusercontent.com/1951107/73180636-9f3a4d80-410d-11ea-9bc5-09ecb3d1ac5a.png)

Also it does not crash when creating new QGIS profiles.

**Comment by gioman** [comment]
Closing as probable local issue, please reopen if necessary.
