### ISSUE TITLE
QGIS 3.102 Full Release

### ISSUE THREAD

**Issue by MPN-stack** [qgis/QGIS#34028]
**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

I am providing this for helpul advice on installing 3.10.2
Has 3.10.2 running now  I had to delete my root directory  c:/OSGeo4W64 again before I got an install. The first couple of install attempts did not provide the text for licence agreements I found that this was from the first server i chose.  I am guessing this was not populated with 3..10.2 and switching to another server worked to bring these in. The installer did not create my icons so I had to go into directories to create short cuts which was not a problem  to do.  The project required conversion which took a while longer to open but opened up with a message to save in the new format.. The icons are fixed and it seems to currently be working well. I wanted to say thanks to the team at QGIS who have put up with understanding our difficulties and again met them in a friendly manor and produced an even better version. :)  Thank you again QGIS Development team

**Comment by gioman** [comment]
@MPN-stack Is this a bug report?

**Comment by roya0045** [comment]
@gioman from the last line I would say no.
