### ISSUE TITLE
QGIS unexpectedly ended  v3.10

### ISSUE THREAD

**Issue by Normko** [qgis/QGIS#34020]
Everytime I quite the application I get this message.

## User Feedback

everytime i X out of QGIS

## Report Details

**Crash ID**: [b7976a07d3a82072753bf9b772d69ee3a5e24f16]('https://github.com/qgis/QGIS/search?q=b7976a07d3a82072753bf9b772d69ee3a5e24f16&type=Issues')

**Stack Trace**
<pre>
RtlFreeHeap :
clGetExtensionFunctionAddress :
clGetExtensionFunctionAddress :
clGetExtensionFunctionAddress :
clGetExtensionFunctionAddress :
clGetExtensionFunctionAddress :
clGetExtensionFunctionAddress :
clGetExtensionFunctionAddress :
<lambda_f03950bc5685219e0bcd2087efbe011e>::operator() :
__crt_seh_guarded_call<int>::operator()<<lambda_7777bce6b2f8c936911f934f8298dc43>,<lambda_f03950bc5685219e0bcd2087efbe011e> & __ptr64,<lambda_3883c3dff614d5e0c5f61bb1ac94921c> > :
execute_onexit_table :
QgsQtLocationConnection::qt_metacast :
QgsQtLocationConnection::qt_metacast :
LdrpCallInitRoutine :
LdrShutdownProcess :
RtlExitUserProcess :
ExitProcessImplementation :
exit_or_terminate_process :
common_exit :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.1-A Coru�a
QGIS code revision: ef24c526da
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by NathanW2** [comment]
Can you install the latest 3.10.2 and see if you have the same issue there.

**Comment by gioman** [comment]
@Normko Also try with a new QGIS profile, no 3rd party plugins installed.

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
