### ISSUE TITLE
DB Manager no longer works with pqlib services

### ISSUE THREAD

**Issue by jgrocha** [qgis/QGIS#34025]
**Describe the bug**

**How to Reproduce**

1. Go to DB Manager
2. Click on PostGIS connections
3. Scroll down to one connection defined using services
4. Open it
5. You will be prompted with a dialogue to enter credentials

![Screenshot from 2020-01-25 16-42-23](https://user-images.githubusercontent.com/163681/73124298-bfdd9880-3f91-11ea-9afc-536df7659ee5.png)

**QGIS and OS versions**

This happens on master only. I suspect that it is related with #33225, but I'm not sure. Can someone else confirm this on master?

Compiling with a version prior to #33225 it works.

**Comment by luipir** [comment]
ping @strk

**Comment by strk** [comment]
I just tested opening, with DBManager, the connection called "qgis_test". The connection was made only filing the "service" field. DBManager opens it fine.

Does your problem also show up outside of DBManager @jgrocha ?

**Comment by strk** [comment]
My test was with commit 5b4e581d03538b6f97d2fab41d28ef81aaf218ba (top commit from PR #33225)

**Comment by jgrocha** [comment]
Thanks @strk for looking into this.

If I try to open a service based connection, I get this error:

![error connecting using db manager](https://user-images.githubusercontent.com/163681/73547181-57316880-4436-11ea-9571-561e3bc9805b.png)

The error makes sense. **I don't have any connection named `qgis_test`.**

The DB Manager is not using the service name I have configured. This is my list of connections:

![connections](https://user-images.githubusercontent.com/163681/73547439-d9ba2800-4436-11ea-84f1-b55dc8fd124b.png)

If I try to connect to any of these, the error is always the same.

**Comment by jgrocha** [comment]
@strk If I add a service called `qgis_test`, everything works fine. I mean, the other services starts to work again.

My .pg_services.conf now has:

```
[qgis_test]
host=192.168.1.24
port=5432
dbname=ortos
user=postgres
password=xxx

[ortos]
host=192.168.1.24
port=5432
dbname=ortos
user=postgres
password=xxx

[websig]
host=192.168.1.24
port=5432
dbname=websig
user=postgres
password=xxx

[pdm2015]
host=192.168.1.24
port=5432
dbname=pdm2015
user=postgres
password=xxx
```

With this dummy `qgis_test` service, the DB Manager is working.

**Comment by strk** [comment]
Wow, puzzling. The only hard-coded "qgis_test" I find in the QGIS codebase (outside of testsuite) is in python/plugins/db_manager/db_plugins/postgis/plugin_test.py -- could it be python loads all files in a dir rather than just the given one ? (just shooting in the dark here)

**Comment by strk** [comment]
@jgrocha besides, the error you show now is different from the one you showed in your original report, I even tried removing the `[qgis_test]` block from my `.pg_services.conf` and things still worked for me (other than connecting to the `qgis_test` named connection of course).

Do you build QGIS yourself ? If so, could you bisect ?

**Comment by elpaso** [comment]
@jgrocha also, test latest master: I've done a couple of PG/DB-manager fixes a few hours ago.

**Comment by jgrocha** [comment]
Thanks @elpaso and @strk 
Everything is working perfectly right now on latest master.
