### ISSUE TITLE
"Save as..." for raster layer gives different result compared to canvas rendering

### ISSUE THREAD

**Issue by pathmapper** [qgis/QGIS#34031]
**Describe the bug**

"Save as..." for raster layer gives different result compared to canvas rendering.

**How to Reproduce**

1. Start QGIS and load `SR_50M_alaska_nad.tif` from "Alaska dataset":
http://qgis.org/downloads/data/qgis_sample_data.zip
2. Make sure the Canvas CRS is set to EPSG:2964 (same as the raster layer from the tif file)
3. Zoom in to custom area
4. From layer context menu choose "Export" -> "Save as..." and save raster in GeoTiff format with the following settings:
- Output mode: Rendered image
- Format: GeoTIFF
- CRS: EPSG:2964
- Extent: Map Canvas Extent
- Resolution: Horizontal, leave the values as they are
- Add saved file to map
![grafik](https://user-images.githubusercontent.com/20856381/73131742-d7a83180-4010-11ea-84ca-0ccd76161363.png)

4. If you compare the created TIF with the source raster Layer rendered on the canvas you'll see a difference like in the following GIF:

![difference_canvas_savedTIF](https://user-images.githubusercontent.com/20856381/73131797-d297b200-4011-11ea-82ef-f4e388ecbefa.gif)

**QGIS and OS versions**

QGIS version | 3.10.2-A Coruña | QGIS code revision | 616ad4531b
-- | -- | -- | --
Compiled against Qt | 5.11.3 | Running against Qt | 5.11.3
Compiled against GDAL/OGR | 2.4.0 | Running against GDAL/OGR | 2.4.0
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.27.2 | Running against SQLite | 3.27.2
PostgreSQL Client Version | 11.5 (Debian 11.5-1+deb10u1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.10.4
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Debian GNU/Linux 10 (buster)
Active python plugins | ClipMultipleLayers; quick_map_services; scriptrunner3; LAStools; canvas_clipper; savedialog; loadthemall; kmltools; MapsPrinter; mmqgis; pluginbuilder3; vector_tiles_reader; layerGroupFilter; plugin_reloader; realcentroid; mask; MetaSearch; db_manager; processing

**Additional context**

- Searching existing issues, I came across https://github.com/qgis/QGIS/issues/23609 which is similar (however in my test case above there is no reprojection taking place) and was closed without a fix as far as I can see.

- When exporting the map to an image from the main menu ("Project" -> "Import/Export" -> "Export Map to Image ...") there is no difference compared to the source raster Layer.

**Comment by gioman** [comment]
>     * Extent: Map Canvas Extent

@pathmapper by choosing an extent that is different from the input (and a slightly different pixel size, the original is 7181.354110795283304) you are asking QGIS to do a resampling, so is normal you get a slightly different result compared to the original. If you use the layer extent and the same exactly pixel size you get an identical copy.

**Comment by pathmapper** [comment]
> If you use the layer extent and the same exactly pixel size you get an identical copy.

@gioman thanks, but I don't want to save the whole extent as image (because I want to do this also for WMS layers, where I would like to save what I'm seeing on the canvas as an image). 

I think the main problem is that the resolution in the setting window doesn't fit to the canvas extent so that resampling happens.

Is there a way to use "Map Canvas Extent" as Extent in the settings window for "Save Layer as ..." without resampling the data? A little more extent than the canvas extent would be also be OK.

A solution doing this with PyQGIS would also be fine. I tried to achieve this with `QgsRasterFileWriter` but the following results in the same resampling.

```
canvas = iface.mapCanvas()
canvasExtent = canvas.extent()
canvasCRS = QgsCoordinateReferenceSystem(iface.mapCanvas().mapSettings().destinationCrs().authid())

# Transform canvas CRS to layer CRS if needed
layerCRS = QgsCoordinateReferenceSystem(layer.crs().authid())
if canvasCRS is not layerCRS:
    transform = QgsCoordinateTransform(canvasCRS, layerCRS, QgsProject.instance())
    clipExtent = transform.transformBoundingBox(canvasExtent)
else:
    clipExtent = canvasExtent


temporaryFile = QgsProcessing.TEMPORARY_OUTPUT

canvasSize = iface.mapCanvas().size()
width, height = canvasSize.width(), canvasSize.height()
renderer = layer.renderer()
provider=layer.dataProvider()

pipe = QgsRasterPipe()
pipe.set(provider.clone())
pipe.set(renderer.clone())

file_writer = QgsRasterFileWriter(temporaryFile)

file_writer.writeRaster(pipe,
                        width,
                        height,
                        clipExtent,
                        layerCRS)


newLayer = QgsRasterLayer(temporaryFile, 'NewLayer')

QgsProject.instance().addMapLayer(newLayer)



```

**Comment by gioman** [comment]
> I think the main problem is that the resolution in the setting window doesn't fit to the canvas extent so that resampling happens.

yeah it seems that make some rounding, but that is not the main issue (as you can manually change that). The main point is that by choosing manually an extent is very unlikely you are setting one that fill perfectly fit the pixels in the original raster > as you cannot have fractions of pixels in a raster you are asking for a resampling...

I would say that there is really no issue here...


> Is there a way to use "Map Canvas Extent" as Extent in the settings window for "Save Layer as ..." without resampling the data? A little more extent than the canvas extent would be also be OK.

Please ask questions in the users/developers mailing lists.

**Comment by pathmapper** [comment]
> I would say that there is really no issue here...

Well, I expected it would be possible to save the area which is visible on the canvas without resampling because what is shown on the canvas is also not resampled. 

But sure, on the other hand there is a need for resampling if you don't allow the saved image to be up to one pixel in x and y dimension overlapping the canvas extent.

Closing here because it seems that the current behavior of _"Save as ..."_ for raster layers with `extent` = _Map Canvas Extent_ is like it should be. Feel free to reopen if this is not the case.

> Please ask questions in the users/developers mailing lists.

Will do, thanks.

**Comment by AlisterH** [comment]
In case it helps others searching the tracker, to avoid issues like this I often find (not just using "save as", but when transforming rasters with various tools) that I need to manually set the CRS on the input file and/or the output file, and/or change the "zoomed in" and "zoomed out" resampling settings in the layer styling.
