### ISSUE TITLE
Error on FreeBSD 'use of undeclared identifier proj_assign_context' since #e60d0ac

### ISSUE THREAD

**Issue by rhurlin** [qgis/QGIS#34036]
**Describe the bug**

On FreeBSD 13.0-CURRENT with clang-9.0.1 I get the following breakage since [#e60d0ac](https://github.com/qgis/QGIS/commit/e60d0ac2687417fedcced9cb6b98235b3ef662a5)

`[..snip..] Building CXX object src/core/CMakeFiles/qgis_core.dir/qgscoordinatereferencesystem.cpp.o
cd /usr/ports/graphics/qgis-devel/work/.build/src/core && /usr/bin/c++  -DPROJ_VERSION_MAJOR=6 -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_DISABLE_DEPRECATED_BEFORE=0 -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_NO_FOREACH -DQT_POSITIONING_LIB -DQT_PRINTSUPPORT_LIB -DQT_SERIALPORT_LIB -DQT_SQL_LIB -DQT_SVG_LIB -DQT_WEBKITWIDGETS_LIB -DQT_WEBKIT_LIB -DQT_WIDGETS_LIB -DQT_XML_LIB -DSIP_VERSION=0x041313 -DTEST_DATA_DIR=\"/usr/ports/graphics/qgis-devel/work/QGIS-e60d0ac/tests/testdata\" -DWITH_BINDINGS -DWITH_QTWEBKIT -D_HAVE_PTHREAD_ -Dqgis_core_EXPORTS -I/usr/ports/graphics/qgis-devel/work/.build/src/core/qgis_core_autogen/include -I/usr/ports/graphics/qgis-devel/work/.build -I/usr/ports/graphics/qgis-devel/work/QGIS-e60d0ac/src/core -I/usr/ports/graphics/qgis-devel/work/.build/src/core -I/usr/ports/graphics/qgis-devel/work/QGIS-e60d0ac/src/core/3d -I/usr/ports/graphics/qgis-devel/work/QGIS-e60d0ac/src/core/annotations -I/usr/ports/graphics/qgis-devel/work/QGIS-e60d0ac/src/core/auth -I/usr/ports/graphics/qgis-devel/work/QGIS-e60d0ac/src/core/classification -I/usr/ports/graphics/qgis-devel/work/QGIS-e60d0ac/src/core/dxf -I/usr/ports/graphics/qgis-devel/work/QGIS-e60d0ac/src/core/effects -I/usr/ports/graphics/qgis-devel/work/QGIS-e60d0ac/src/core/expression -I/usr/ports/graphics/qgis-devel/work/QGIS-e60d0ac/src/core/fieldformatter -I/usr/ports/graphics/qgis-devel/work/QGIS-e60d0ac/src/core/geometry -I/usr/ports/graphics/qgis-devel/work/QGIS-e60d0ac/src/core/geocms -I/usr/ports/graphics/qgis-devel/work/QGIS-e60d0ac/src/core/geocms/geonode -I/usr/ports/graphics/qgis-devel/work/QGIS-e60d0ac/src/core/labeling -I/usr/ports/graphics/qgis-devel/work/QGIS-e60d0ac/src/core/layertree -I/usr/ports/graphics/qgis-devel/work/QGIS-e60d0ac/src/core/layout -I/usr/ports/graphics/qgis-devel/work/QGIS-e60d0ac/src/core/locator -I/usr/ports/graphics/qgis-devel/work/QGIS-e60d0ac/src/core/metadata -I/usr/ports/graphics/qgis-devel/work/QGIS-e60d0ac/src/core/numericformats -I/usr/ports/graphics/qgis-devel/work/QGIS-e60d0ac/src/core/pal -I/usr/ports/graphics/qgis-devel/work/QGIS-e60d0ac/src/core/processing -I/usr/ports/graphics/qgis-devel/work/QGIS-e60d0ac/src/core/processing/models -I/usr/ports/graphics/qgis-devel/work/QGIS-e60d0ac/src/core/providers -I/usr/ports/graphics/qgis-devel/work/QGIS-e60d0ac/src/core/providers/memory -I/usr/ports/graphics/qgis-devel/work/QGIS-e60d0ac/src/core/providers/gdal -I/usr/ports/graphics/qgis-devel/work/QGIS-e60d0ac/src/core/providers/ogr -I/usr/ports/graphics/qgis-devel/work/QGIS-e60d0ac/src/core/providers/meshmemory -I/usr/ports/graphics/qgis-devel/work/QGIS-e60d0ac/src/core/raster -I/usr/ports/graphics/qgis-devel/work/QGIS-e60d0ac/src/core/renderer -I/usr/ports/graphics/qgis-devel/work/QGIS-e60d0ac/src/core/scalebar -I/usr/ports/graphics/qgis-devel/work/QGIS-e60d0ac/src/core/symbology -I/usr/ports/graphics/qgis-devel/work/QGIS-e60d0ac/src/core/mesh -I/usr/ports/graphics/qgis-devel/work/QGIS-e60d0ac/src/core/validity -I/usr/ports/graphics/qgis-devel/work/QGIS-e60d0ac/external -I/usr/ports/graphics/qgis-devel/work/QGIS-e60d0ac/external/nlohmann -I/usr/ports/graphics/qgis-devel/work/QGIS-e60d0ac/external/kdbush/include -I/usr/ports/graphics/qgis-devel/work/QGIS-e60d0ac/external/nmea -I/usr/ports/graphics/qgis-devel/work/QGIS-e60d0ac/external/poly2tri -I/usr/ports/graphics/qgis-devel/work/QGIS-e60d0ac/external/rtree/include -isystem /usr/local/include -isystem /usr/local/include/Qca-qt5/QtCrypto -isystem /usr/local/include/qt5keychain -isystem /usr/local/include/qt5 -isystem /usr/local/include/qt5/QtSerialPort -isystem /usr/local/include/qt5/QtCore -isystem /usr/local/lib/qt5/mkspecs/freebsd-clang -isystem /usr/local/include/qt5/QtXml -isystem /usr/local/include/qt5/QtGui -isystem /usr/local/include/qt5/QtWidgets -isystem /usr/local/include/qt5/QtSvg -isystem /usr/local/include/qt5/QtPrintSupport -isystem /usr/local/include/qt5/QtNetwork -isystem /usr/local/include/qt5/QtWebKitWidgets -isystem /usr/local/include/qt5/QtWebKit -isystem /usr/local/include/qt5/QtSql -isystem /usr/local/include/qt5/QtConcurrent -isystem /usr/local/include/qt5/QtPositioning  -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -Wall -Wextra -Wno-long-long -Wformat-security -Wno-strict-aliasing -Wno-redundant-move -Wno-return-type-c-linkage -Wno-overloaded-virtual -Wimplicit-fallthrough -Qunused-arguments -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -fPIC -fvisibility=hidden   -fPIC -std=gnu++11 -mllvm -inline-threshold=128 -o CMakeFiles/qgis_core.dir/qgscoordinatereferencesystem.cpp.o -c /usr/ports/graphics/qgis-devel/work/QGIS-e60d0ac/src/core/qgscoordinatereferencesystem.cpp

In file included from /usr/ports/graphics/qgis-devel/work/QGIS-e60d0ac/src/core/qgscoordinatereferencesystem.cpp:19:
/usr/ports/graphics/qgis-devel/work/QGIS-e60d0ac/src/core/qgscoordinatereferencesystem_p.h:109:9: error: use of
      undeclared identifier 'proj_assign_context'
        proj_assign_context( it.value(), tmpContext );
        ^
/usr/ports/graphics/qgis-devel/work/QGIS-e60d0ac/src/core/qgscoordinatereferencesystem_p.h:115:9: error: use of
      undeclared identifier 'proj_assign_context'
        proj_assign_context( mPj.get(), tmpContext );
        ^
2 errors generated.
gmake[4]: *** [src/core/CMakeFiles/qgis_core.dir/build.make:2977: src/core/CMakeFiles/qgis_core.dir/qgscoordinatereferencesystem.cpp.o] Error 1
gmake[4]: Leaving directory '/usr/ports/graphics/qgis-devel/work/.build'
gmake[3]: *** [CMakeFiles/Makefile2:4729: src/core/CMakeFiles/qgis_core.dir/all] Error 2
gmake[3]: Leaving directory '/usr/ports/graphics/qgis-devel/work/.build'
gmake[2]: *** [Makefile:166: all] Error 2`

One commit before (#2bf0e9f, 'Use PJ_CONTEXT* instead of void*') builds and installs just fine. Obviously, there is something incomplete with creating a temporary PJ_CONTEXT?

**How to Reproduce**

Build QGIS commit equal or newer than #e60d0ac with clang (don't know, if this is FreeBSD specific).

**QGIS and OS versions**

- FreeBSD 13.0-CURRENT (amd64, r356917)
- clang-9.0.1
- QGIS master #e60d0ac
- gdal-3.0.3
- proj-6.1.1

**Additional context**

**Comment by rouault** [comment]
Updating to proj 6.3.0 will fix it, and will fix other runtime issues

**Comment by rhurlin** [comment]
I just updated PROJ from 6.1.1 to 6.3.0 and now QGIS builds again :)
Fortunately, the official update of the FreeBSD port of PROJ 6.3.0 is coming soon.

Many thanks for the fast and helpful response.
