### ISSUE TITLE
Crash on saving actual layers data

### ISSUE THREAD

**Issue by FlyingEagle** [qgis/QGIS#34039]
## User Feedback

I wanted to save the actual Layer - it is not reproduceable all the time but it happens from time to time.

## Report Details

**Crash ID**: [608547bebf1f28febe6672b3c64e642ee6c24562]('https://github.com/qgis/QGIS/search?q=608547bebf1f28febe6672b3c64e642ee6c24562&type=Issues')

**Stack Trace**
<pre>
RtlpFreeHeapInternal :
RtlFreeHeap :
_free_base :
QgsLabelFeature::~QgsLabelFeature qgslabelfeature.cpp:47
QgsLabelFeature::`vector deleting destructor' :
QMetaObject::cast :
QgsAttributeForm::updateDefaultValues qgsattributeform.cpp:491
QgsAttributeForm::onAttributeChanged qgsattributeform.cpp:878
QMetaObject::activate :
QgsEditorWidgetWrapper::valuesChanged moc_qgseditorwidgetwrapper.cpp:260
QgsEditorWidgetWrapper::emitValueChanged qgseditorwidgetwrapper.cpp:96
QgsEditorWidgetWrapper::qt_static_metacall moc_qgseditorwidgetwrapper.cpp:141
QMetaObject::activate :
QDoubleSpinBox::decimals :
QAbstractSpinBox::setSpecialValueText :
QSpinBox::setValue :
QgsRangeWidgetWrapper::updateValues qgsrangewidgetwrapper.cpp:272
QgsEditorWidgetWrapper::setFeature qgseditorwidgetwrapper.cpp:76
QgsAttributeForm::resetValues qgsattributeform.cpp:762
QgsAttributeForm::setFeature qgsattributeform.cpp:278
QMetaObject::activate :
QgsVectorLayer::updateFields qgsvectorlayer.cpp:3614
QgsVectorLayerEditBuffer::commitChanges qgsvectorlayereditbuffer.cpp:476
QgsVectorLayer::commitChanges qgsvectorlayer.cpp:3096
QgisApp::saveActiveLayerEdits qgisapp.cpp:9833
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1598
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.1-A Coru�a
QGIS code revision: ef24c526da
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by Gustry** [comment]
> QGIS Version: 3.10.1-A Coru�a

Upgrade to 3.10.2
http://blog.qgis.org/2020/01/24/public-service-announcement-update-to-the-latest-point-release-now/

**Comment by gioman** [comment]
> Upgrade to 3.10.2

@FlyingEagle and if the problem persist plesae try with a new QGIS profile, no 3rd party plugins installed.

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
