### ISSUE TITLE
Menu icons in wrong position due to checked - not checked status

### ISSUE THREAD

**Issue by kosnick** [qgis/QGIS#34032]
Some of the menu icons are not positioned correctly. I believe it has to do with the 'checked' / 'not checked' status of them. 
For example, in the 'View' menu the 3rd option is 'Pan Map'. The icon (the hand) is on top of the letter P and on the left is the usual icon for checked (tick or V). When i deselect the 'Pan Map' , actually select some other option, let's say 'Zoom In' , the tick symbol moves from the 'Pan Map' selection in the 'View' menu down to the 'Zoom In' selection, to the left of it. The 'Pan Map' icon remains on top of the letter P and as expected the 'checked' symbol is removed. Same thing happens to the 'Zoom In' selection but in reverse - no tick symbol at the beginning, icon on top of letter Z and then the tick symbol appears on the left of it.
I'm including some screenshots of the menus I believe this is happening (also two extra to describe the check thing)

![QGIS - Edit menu](https://user-images.githubusercontent.com/6617863/73132223-b6e7d800-4020-11ea-8bb8-fd2c4ef5e512.png)
![QGIS - Layer menu](https://user-images.githubusercontent.com/6617863/73132224-b7806e80-4020-11ea-917a-c0af250adc18.png)
![QGIS - Processing menu](https://user-images.githubusercontent.com/6617863/73132225-b7806e80-4020-11ea-950f-cbeea8833392.png)
![QGIS - View menu - Pan Map checked](https://user-images.githubusercontent.com/6617863/73132226-b8190500-4020-11ea-8333-5dff2e572636.png)
![QGIS - View menu - Zoom in checked](https://user-images.githubusercontent.com/6617863/73132227-b8190500-4020-11ea-8f6c-88ca0f51b1b9.png)

These are the menus that this is happening (to the best of my knowledge)

--View
   ++Add Line Feature
   ++Add Circular String
   ++Add Circular String by Radius
   ++Rotate Feature(s)
   ++Simplify Feature
   ++Add Ring
   ++Add Part
   ++Delete Ring
   ++Delete Part
   ++Reshape Features
   ++Offset Curve
   ++Split Features
   ++Reshape Features
   ++Split Parts
   ++Vertex Tool (All Layers)
   ++Rotate Point Symbols
   ++Offset Point Symbol
   ++Reverse Line

--Layer
   ++Toggle Editing
   
--Processing
   ++Toolbox
   ++Results Viewer
   ++Edit Features In-Place

QGIS version | 3.4.10-Madeira | QGIS code branch | Release 3.4
-- | -- | -- | --
Compiled against Qt | 5.12.4 | Running against Qt | 5.12.4
Compiled against GDAL/OGR | 2.4.2 | Running against GDAL/OGR | 2.4.2
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
PostgreSQL Client Version | 11.5 (Ubuntu 11.5-1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.10.4
Compiled against PROJ | 520 | Running against PROJ | 5.2.0

**Comment by kosnick** [comment]
Also in the Layer Styling panel, here are some screenshots:

![QGIS - Layer Styling panel](https://user-images.githubusercontent.com/6617863/73132366-d08a1f00-4022-11ea-8a8c-9aafa9bf4688.png)
![QGIS - Layer Styling panel - Syngle symbol](https://user-images.githubusercontent.com/6617863/73132367-d122b580-4022-11ea-9975-9add908dbb9a.png)

**Comment by Gustry** [comment]
> Running against Qt | 5.12.4

It looks like a duplicate of https://github.com/qgis/QGIS/issues/32248 ?

Upgrade or wait for Qt 5.12.5.

**Comment by kosnick** [comment]
Ok, thanks for the update.
