### ISSUE TITLE
Expression for previous value in a child layer

### ISSUE THREAD

**Issue by baumsicht** [qgis/QGIS#34035]
Is it possible to show not the newest but the previous value in a child layer with an expression? (Many child layers are joined to one parent.)

![example](https://user-images.githubusercontent.com/54360394/73135121-1c4ac180-403f-11ea-8e53-3df7643445c4.png)
)

**Comment by gioman** [comment]
@baumsicht is this a question or a bug report?

**Comment by roya0045** [comment]
For questions please use stack exchange or the qgis mailing lists.

**Comment by baumsicht** [comment]
Sorry, is a question.
