### ISSUE TITLE
Window turns blue when moving another window over it

### ISSUE THREAD

**Issue by GeoEugeneK** [qgis/QGIS#34042]
The problem occured when Python console window was being moved over Layer Styling Panel and persist if I switch the panel back and forth. 

More specifically, I moved undocked Python console over the panel but did not finally dock it. For some reason, QGIS produced this kind of bug because of how I moved Python console, as when I tried to reproduce the bug, it did not work out.

Image 1: QGIS screen shot
![image](https://user-images.githubusercontent.com/60332001/73145403-7e96d700-40be-11ea-8c45-eeacce99ade9.png)

Image 2: Essential QGIS info (note: I have been using this version for less than a week)
![image](https://user-images.githubusercontent.com/60332001/73145469-cf0e3480-40be-11ea-9934-9968d60c58c0.png)

**Comment by gioman** [comment]
@GeoEugeneK not sure if I really understand what the issue is. A screencast would be better than a still image.

**Comment by roya0045** [comment]
I feel like this would be on the QT side if it shows the possibility of docking but is then unable to do it due to size constrains or something else. I may be wrong though.

**Comment by gioman** [comment]
> as when I tried to reproduce the bug, it did not work out.

@GeoEugeneK can we assume that this was a glitch and then we can close this?
