### ISSUE TITLE
Environment variables are overwritten rather than appended

### ISSUE THREAD

**Issue by simonwright-jbarisk** [qgis/QGIS#34054]
**Describe the bug**

In QGIS 3.4.15 it is possible to update current environment variables using different options including overwrite, append, prepend, etc.

However, in both QGIS 3.10.1 and 3.10.2, the different options don't work - the selected environment variable is just overwritten.

**How to Reproduce**

QGIS version
3.10.2-A Coruña
QGIS code revision
d4cd3cfe5a
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.3
Running against GDAL/OGR
3.0.3
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.0
Running against PROJ
Rel. 6.3.0, January 1st, 2020
OS Version
Windows 10 (10.0)

**Additional context**

**Comment by agiudiceandrea** [comment]
I cannot replicate on Windows 7 64 bit with QGIS 3.10.1 and Windows 10 64 bit with QGIS 3.10.3, 3.12.1 (via standalone installer), nor  master 3.13.0 (via OSGeo4W setup).

**Comment by alexbruy** [comment]
Not reproducible.

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
