### ISSUE TITLE
QGIS casts bigint Primary key field to a text field

### ISSUE THREAD

**Issue by lennertdefeyter** [qgis/QGIS#34077]
Using version of QGIS:
3.10.2-A Coruña
Postgres version 9.6

Although also tested on QGIS 3.4, Qgis 2.18 and postgresql 11

Steps to reproduce:
1) Engage the detailed logging on your postgres instance
2) create a table using a bigint as primary key:
```
create table if not exists
test.test_4
(id bigint primary key,
geometry geometry(POINT, 4326));
```
3) Load this table into QGIS
4) Create some points in the table
5) Identify a point using the identify tool
6) Check your postgresql logging and see:

> 2020-01-28 09:15:40 CET LOG:  statement: DECLARE qgis_350 BINARY CURSOR FOR SELECT st_asbinary("geometry",'NDR'),"id"::text FROM "test"."test_4" WHERE "id"::text='1'

The id field is cast to a text field which causes the index on the primary key to be skipped. For larger tables, this causes a huge slowdown.

This does not happen with primary keys of the type:
- int
- serial
- bigserial

**Comment by Saijin-Naib** [comment]
Please see GIS.SE issue here:  
https://gis.stackexchange.com/questions/348536/qgis-form-performance

**Comment by espinafre** [comment]
I've also seen this issue with PostgreSQL 12, QGIS master (3.13) and a table with 10e6+ entries, in which the primary key is a bigserial (and not an ordinary bigint).
