### ISSUE TITLE
'Count' field not shown when using 'Show statistical summary' button

### ISSUE THREAD

**Issue by Henrik-P** [qgis/QGIS#34086]
I am following the QGIS Training manual - thanks a lot for this excellent resource.

In the [QGIS Training manual 7.4.2. basic Follow Along: Basic Statistics](https://docs.qgis.org/3.4/en/docs/training_manual/vector_analysis/spatial_statistics.html#basic-fa-basic-statistics), the first field in the Statistics Panel is 'Count' (see pt. 4). However, when try exactly the same procedure, the 'Count' field does not appear. All other fields are there though.

QGIS 3.10.2

-----

If I use the menus instead (Vector - Analysis Tools - Basis Statistics for Fields), the 'Count' field appears in the resulting HTML.

**Comment by roya0045** [comment]
Strange, its fine on master for me.

**Comment by pigreco** [comment]
I took a test and can't confirm

## OSGeo4W64 win 10 QGIS 3.10.2-2

![image](https://user-images.githubusercontent.com/7631137/73279568-a59ff680-41ed-11ea-87b4-c70288822dd1.png)


try a new profile

**Comment by roya0045** [comment]
@Henrik-P  Can you restest if this is still valid?

**Comment by alexbruy** [comment]
Closing due the lack of feedback
