### ISSUE TITLE
QGIS 3.10.2 Error 'QgsMultiLineString' object has no attribute 'xAt' 

### ISSUE THREAD

**Issue by Hutch07** [qgis/QGIS#34094]
Python code is attempting to get the "X" value of the first node in a QgsMultiLineString feature.  This works fine from 3.4 to 3.10.1.   I have loaded 3.10.2 on 3 separate machines and all fail with the same error.   I made a slim dataset with just a few lines and it also errored out.

It is coming from my plugin so I will also try just a short chunk of code.

An error has occurred while executing Python code: 
AttributeError: 'QgsMultiLineString' object has no attribute 'xAt' 
Traceback (most recent call last):
  File "C:/Users/S M/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\invert_builder\invert_builder.py", line 618, in editPipe
    x0 = line.xAt(0) # x value of first vertex
AttributeError: 'QgsMultiLineString' object has no attribute 'xAt'

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.10.2-A Coruña A Coruña, d4cd3cfe5a 
Python Path:
    • C:/PROGRA~1/QGIS3~1.10/apps/qgis/./python
    • C:/Users/S M/AppData/Roaming/QGIS/QGIS3\profiles\default/python
    • C:/Users/S M/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
    • C:/PROGRA~1/QGIS3~1.10/apps/qgis/./python/plugins
    • C:\PROGRA~1\QGIS3~1.10\apps\Python37
    • C:\PROGRA~1\QGIS3~1.10\apps\Python37\Scripts
    • C:\Program Files\QGIS 3.10\bin\python37.zip
    • C:\PROGRA~1\QGIS3~1.10\apps\Python37\DLLs
    • C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib
    • C:\Program Files\QGIS 3.10\bin
    • C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages
    • C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32
    • C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32\lib
    • C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\Pythonwin
    • C:/Users/S M/AppData/Roaming/QGIS/QGIS3\profiles\default/python
Data attached.
When I uninstalled 3.10.2 and reinstalled 3.10.1 the issue goes away.    Thank you for any help.   
[lite_data.zip](https://github.com/qgis/QGIS/files/4124196/lite_data.zip)
UPDATE:
    `layer = iface.activeLayer()
    print(layer.name())
    all_features = layer.getFeatures()
    layer.startEditing()
    for linep in all_features:
        geom = linep.geometry()
        line = geom.constGet()
        print(geom)
        x0 = line.xAt(0)
        print(str(x0))`

**Comment by Hutch07** [comment]
[line_getX.zip](https://github.com/qgis/QGIS/files/4124273/line_getX.zip)
This small bit of code also will recreate the error inside the python console.

**Comment by nyalldawson** [comment]
QgsMultiLineString has never had an xAt method. Can you double check the geometry type you receive when you run the script on the earlier version?

**Comment by Hutch07** [comment]
Thanks nyalldawson.  The data type is QgsLinestring the error is _'QgsMultiLineString'_.  The minimal code is .
`layer = iface.activeLayer()
print(layer.name())
all_features = layer.getFeatures()
layer.startEditing()
for linep in all_features:
    geom = linep.geometry()
    line = geom.constGet()
    print(geom)
    x0 = line.xAt(0)
    print(str(x0))`

**Comment by nyalldawson** [comment]
> The data type is QgsLinestring

Can you share the data source?

**Comment by Hutch07** [comment]
[lite_data.zip](https://github.com/qgis/QGIS/files/4331533/lite_data.zip)

**Comment by Hutch07** [comment]
QGIS 3.10.3 Error 'QgsMultiLineString' object has no attribute 'xAt' #34094.   Attached is the minimum code.  When I uninstalled 3.10.2 and reinstalled 3.10.1 the issue goes away. Thank you for any help.   I have tried this on several data sets.   I create 2 QgsPoints with x,y,z coordinates.   Use these 2 points to create a QgsLinestring.  Then try to get the x value on either one of the nodes.  x0 = line.xAt(0)
[line_getX.zip](https://github.com/qgis/QGIS/files/4331542/line_getX.zip)

**Comment by Hutch07** [comment]
**UPDATE:**
When I look at the same file created in 3.10.1.  The Layer Properties shows _Geometry_  Line(LineString25D) in 3.10.1 **BUT** when opened in 3.10.3 it shows 
_Geometry_ Line (MultiLineStringZ).
![QGIS3_10_3_MLSZ](https://user-images.githubusercontent.com/11570521/76658598-dbedc700-654a-11ea-9445-615dba3cbec6.jpg)

**Comment by nyalldawson** [comment]
This is as expected - shp now always open as multi* geometry types
