### ISSUE TITLE
Minimize/Maximize/Close buttons do not appear on top menu bar - QGIS3.10.2/Win10Enterprise

### ISSUE THREAD

**Issue by paddleman** [qgis/QGIS#34097]
Minimize/Maximize/Close buttons do not appear. No ability to move the QGIS window around the desktop.

QGIS 3.10.2; Windows 10 enterprise.

**Comment by nyalldawson** [comment]
This is almost certainly a local issue.

**Comment by gioman** [comment]
@paddleman I also cannot replicate on any Windows (7,10) installation.

**Comment by alexbruy** [comment]
Also can not reproduce. Should be a local issue.

**Comment by Eckfeldt** [comment]
I have this issue in QGIS 3.12.1
Windows 10 Home edition

I did recently install ioGAS pluggin otherwise no changes since it was last working.

**Comment by The-Gig** [comment]
_For whoever reaches this page while searching for this problem:_
probably it's just you enabled "Fullscreen mode" by mistake. Try pressing F11 or disabling it from View menu.
