### ISSUE TITLE
Dependencies cannot be applied to non-spatial data

### ISSUE THREAD

**Issue by Saijin-Naib** [qgis/QGIS#34092]
**Describe the bug**
Dependencies do not seem to allow for the selection of tabular (non-spatial) data, even if the data is inside of an OGR format (table in a GPKG, as pictured below).

My database does not have triggers (yet), but I was hoping that by setting dependencies on the tables joined to my spatial data (Inventory Segments), that updates would propoagate across the tables/geometries when I edit, especially since I have dynamic join/upsert/delete options enabled for each table joined to my geometries.

**How to Reproduce**
Have a spatial dataset with non-spatial data joined.  
Try to set dependencies on the "child" non-spatial data to update when spatial data updates (OK)
Try to set dependencies on the "parent" spatial data to update when non-spatial data updates (NO)

**QGIS and OS versions**

QGIS version | 3.10.2-A Coruña | QGIS code revision | d4cd3cfe5a
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.3 | Running against GDAL/OGR | 3.0.3
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.0 | Running against PROJ | Rel. 6.3.0, January 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | CalculateGeometry; guided_offline_editing; MemoryLayerSaver; networks; openlayers_plugin; ORStools; PeliasGeocoding; PluginLoadTimes; realcentroid; snail; SpreadsheetLayers; zoom_level; db_manager; MetaSearch; processing

**Additional context**
![image](https://user-images.githubusercontent.com/19295950/73282508-bf2a4980-41bf-11ea-9850-3c9c4bc5febd.png)

**Comment by alexbruy** [comment]
Seems fixed in master
![image](https://github.com/qgis/QGIS/assets/776954/34f1dcd3-07b3-444a-af2c-866da2a9fd57)

**Comment by Saijin-Naib** [comment]
Still need to test/repro

**Comment by alexbruy** [comment]
@Saijin-Naib were you able to check?

**Comment by Saijin-Naib** [comment]
Not yet 😬
