### ISSUE TITLE
3D Map view and Add MSSQL layer both mapped to shift-command-M keyboard shortcut (macOS)

### ISSUE THREAD

**Issue by Ylannl** [qgis/QGIS#34100]
**Describe the bug**
The functions `View > 3D Map View` and `Layer > Add Layer > Add MSSQL Spatial Layer` are **both** mapped to the *shift-command-M keyboard* shortcut. Now I always get the Add MSSQL layer dialog instead of the 3D Map View that I want when I use this shortcut.

I suggest changing one of them.

**QGIS and OS versions**
QGIS version | 3.6.0-Noosa | QGIS code revision | 58734527ab
macOS Catalina 10.3

**Comment by nyalldawson** [comment]
This is fixed in newer releases - please upgrade

**Comment by Ylannl** [comment]
Right! Sorry, I had forgotten to remove 3.6 when I installed to 3.10 last week. And now I was accidentally running the old QGIS, while thinking I had just upgraded... Thanks for the quick response!
