### ISSUE TITLE
Wrong results when executing r.patch on ms-windows

### ISSUE THREAD

**Issue by lluisvicens** [qgis/QGIS#34111]
**Describe the bug**
The algorithm **r.patch** offers wrong results when using r.patch in an MS Windows environment. While r.patch operates as is expected in a GNU/Linux environment, in windows does not. The algorithm does not preserve the original minimum value (0) of the first input layer (A), in the output layer (patched).

**How to Reproduce**

1. Load raster layers ([layers_2_patch.zip](https://github.com/qgis/QGIS/files/4127830/layers_2_patch.zip)) on QGIS (EPSG:25831).
2. Open the r.patch window and select both layers taking into account that layer A with nulls values is the layer to update the null values with the values stored in layer B
3. Here it is the **wrong** result/behavior on Windows:
![patch_on_windows](https://user-images.githubusercontent.com/1196051/73356300-4ea42b00-429a-11ea-8500-cc69a33bb813.jpg)

Note that the original **0** value in layer A has been converted to **1** into the patched file.

4. And here it is the **correct** result/behavior on Linux:
![patch_on_linux](https://user-images.githubusercontent.com/1196051/73356384-857a4100-429a-11ea-82d1-198a141abd12.jpg)

Note that the original **0** value in layer A has been kept as **0** into the patched file, while the null values has been updated properly

**QGIS and OS versions**

QGIS version | 3.10.0-A Coruña | QGIS code revision | 6c816b4204
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Windows 10 (10.0)
Active python plugins | leastcostpath; db_manager; MetaSearch; processing

**Comment by gioman** [comment]
@lluisvicens do you get the same results if you use directly GRASS (not through QGIS)?

**Comment by lluisvicens** [comment]
If I execute r.patch directly on GRASS GIS (Windows environment), the result is **completely correct**, as in Linux. The problem is in executing r.patch from QGIS on Windows. Thanks for your quick reply @gioman !

**Comment by gioman** [comment]
@lluisvicens 

linux:

```
g.proj -c proj4="+proj=utm +zone=31 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"
r.in.gdal input="/home/giovanni/Downloads/layers_2_patch/layerA_withnulls.tif" band=1 output="rast_5e31953b618162" --overwrite -o
r.in.gdal input="/home/giovanni/Downloads/layers_2_patch/layerB_withnonulls.tif" band=1 output="rast_5e31953b619373" --overwrite -o
g.region n=4651869.4591 s=4647739.4983 e=489965.8205 w=485835.8596 res=2.000950048449587
r.patch input=rast_5e31953b618162,rast_5e31953b619373 output=output173e568f77584f17b031a2d195ed697b --overwrite
g.region raster=output173e568f77584f17b031a2d195ed697b
r.out.gdal -t -m input="output173e568f77584f17b031a2d195ed697b" output="/tmp/processing_18008c2c8b8943dab2b94121ed7d27f1/processing_999f687b31e74c8f85817000e9c31858/9d2d235e7ba84413aacf6b1d14683bb9/output.tif" format="GTiff" createopt="TFW=YES,COMPRESS=LZW" --overwrite
```

Windows:

```
g.proj -c proj4="+proj=utm +zone=31 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"
r.external input="C:\Users\qgis\Desktop\layers_2_patch\layerA_withnulls.tif" band=1 output="rast_5e3195706ea564" --overwrite -o
r.external input="C:\Users\qgis\Desktop\layers_2_patch\layerB_withnonulls.tif" band=1 output="rast_5e3195706ea565" --overwrite -o
g.region n=4651869.4591 s=4647739.4983 e=489965.8205 w=485835.8596 res=2.000950048449587
r.patch input=rast_5e3195706ea564,rast_5e3195706ea565 output=output5bc409a41f75456b84d5a6a2708373ab --overwrite
g.region raster=output5bc409a41f75456b84d5a6a2708373ab
r.out.gdal -t -m input="output5bc409a41f75456b84d5a6a2708373ab" output="C:\Users\qgis\AppData\Local\Temp\processing_9dc2996092cf4c058731b21ae46a647e\e998ede9d9924630b78aabe730addc7e\output.tif" format="GTiff" createopt="TFW=YES,COMPRESS=LZW" --overwrite
```



The difference being how the raster is imported, r.external on Windows here (3.10) and with r.in.gdal on Linux (master).

if you test master on Windows you get also the option to use or not r.external, if you don't use you get the expected results.

So if there is an issue it is in how GRASS imports rasters with r.external (or eventually in how we use r.external in QGIS/Processing).

**Comment by lluisvicens** [comment]
Excellent @gioman . Thanks for your explanation and clarification. Then, should I proceed to close this issue?

**Comment by gioman** [comment]
> Then, should I proceed to close this issue?

@lluisvicens it depends, do you get the same results if you use r.external in native GRASS? it may be  bug in GRASS (unlikely I would say) or it is just a matter of a flag/parameter in r.external that we use (or not) in QGIS.

**Comment by lluisvicens** [comment]
> do you get the same results if you use r.external in native GRASS?

Yes, if I run r.patch in windows native GRASS, using **_r.external_** instead of **_r.in.gdal_**, I get the same result as in QGIS: **Wrong**, because I miss all the original zero values as the minimum values in layer A.

Otherwise, If I do exactly the same operation in linux using **_r.external_**, the result is **correct**. The output layer keeps all the zeros.

So, I guess that the problem is how QGIS is using r.external.

**Comment by gioman** [comment]
> Yes, if I run r.patch in windows native GRASS, using **_r.external_** instead of **_r.in.gdal_**, I get the same result as in QGIS: **Wrong**, because I miss all the original zero values as the minimum values in layer A.
> 
> Otherwise, If I do exactly the same operation in linux using **_r.external_**, the result is **correct**. The output layer keeps all the zeros.
> 
> So, I guess that the problem is how QGIS is using r.external.

ummm... from what you say it seems to me that there is a difference on how r.external runs  on Windows and Linux (no QGIS involved). It a flag used/not used? or the commands are identical on both platforms?

**Comment by lluisvicens** [comment]
> ummm... from what you say it seems to me that there is a difference on how r.external runs on Windows and Linux (no QGIS involved). It a flag used/not used? or the commands are identical on both platforms?

Yes! That's what I wanted to say. Sorry. The problem is on how Windows and Linux are running r.external. The commands for r.external are identical in both platforms.

**Comment by gioman** [comment]
> The commands for r.external are identical in both platforms.

so it is a GRASS issue on Windows, not a QGIS one...

**Comment by lluisvicens** [comment]
Yes, sorry. I'm going to open an issue on the GRASS project side. Thanks for your kindness and sorry for bothering you with this issue.

**Comment by gioman** [comment]
> Yes, sorry. I'm going to open an issue on the GRASS project side. Thanks for your kindness and sorry for bothering you with this issue.

@lluisvicens no problem!
