### ISSUE TITLE
QGIS 3.10.x Bug with QuickMapservices

### ISSUE THREAD

**Issue by moebi74** [qgis/QGIS#34112]
Since QGis 3.10.1 (including actual release 3.10.2) the online images, added with quickmapservices, of saved projects are not shown in the view - one has to add the images again to be able to view them

Since QGis 3.10.1 (including actual release 3.10.2) the added online images (with quickmapservices) are not shown in the layouts and therefor not printable - no matter what you do

**Comment by nirvn** [comment]
@moebi74 , you've already identified the right plugin repository to report this issue a few days ago https://github.com/nextgis/quickmapservices/issues/203 , please wait for feedback from the plugin author there.

Thanks.
