### ISSUE TITLE
Server W*S getCapabilites (and getProjectSettings) do not return layer metadata keywords

### ISSUE THREAD

**Issue by elpaso** [qgis/QGIS#34113]
**How to Reproduce**

1. Create a project with at least one layer
2. Set keywords in project metadata
3. Set keywords in layer metadata
4. Publish as WMS
5. getCapabilites or/and getProjectSettings from WMS
4. the keywords in the layer entry are taken from the project's keyword and not from the layer's keywords

**QGIS and OS versions**

Master

**Comment by elpaso** [comment]
ok, closing, because there is no bridge between the new metadata system and the server metadata. It would be nice to have though.

**Comment by nmtoken** [comment]
Note that 'getCapabilites' should **NOT** strictly return a response.  

ref for example: https://github.com/qgis/QGIS/issues/34148

The  required spelling is 'GetCapabilities`

**Comment by elpaso** [comment]
Typos.
