### ISSUE TITLE
PostGIS layer cannot enable toggle editing

### ISSUE THREAD

**Issue by vitorcsm** [qgis/QGIS#34115]
Sometimes, when I open a project, and click on a layer, the toggle editing buton is 
disabled (grey).
I have tried to run the script below:

```
from qgis.core import QgsProject
LayerName =QgsProject.instance().mapLayersByName('example_of_layer')[0]
print(LayerName.name())
qgis.utils.iface.setActiveLayer(LayerName)
qgis.utils.iface.actionToggleEditing().trigger()
```

But I received this message in : `Failed to start editing: Provider cannot be opened for editing`

The solution I found was reconnecting to the PostGIS and adding the layer again.
1. Go to Menu bar 
2. Click Layer > Add layer > Add PostGIS layer
3. In PostgreSQL Data Source Manager window
4. Select the layer> click Add and Close

Nevertheless I would be happy if the ggis community could solve the problem, or if I learn the solution.

**QGIS and OS versions**

QGIS version
3.10.1-A Coruña
QGIS code revision
ef24c526da
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.2
Running against GDAL/OGR
3.0.2
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.2.1
Running against PROJ
Rel. 6.2.1, November 1st, 2019
OS Version
Windows 10 (10.0)
Active python plugins
searchlayers; 
db_manager; 
MetaSearch; 
processing

**Additional context**

Just to emphasize, it happens sometimes.

**Comment by gioman** [comment]
> Just to emphasize, it happens sometimes.

if it does not happen always it is hard to say where the issue could be, does not seems a general QGIS issue.

**Comment by vitorcsm** [comment]
@gioman  
In this case, what is your recommendation?

**Comment by gioman** [comment]
@vitorcsm have you tried a different endpoint?

**Comment by vitorcsm** [comment]
@gioman  what do you mean with "endpoint"? if endpoint==workstation, yes I have tried differents workstations and the problem persist

**Comment by gioman** [comment]
@vitorcsm no, the endpoint is the other end, the PostGIS server.

**Comment by vitorcsm** [comment]
@gioman  ok, I am going to verify, thanks :)

**Comment by vitorcsm** [comment]
@gioman I downloaded QGIS 3.8, and so far i didn't had any issue related to the toggle editing button.
And I didn't try a different endpoint, because I depend to a bureaucratic request to another department in my job (public service).

**Comment by gioman** [comment]
> @gioman I downloaded QGIS 3.8, and so far i didn't had any issue related to the toggle editing button.
> And I didn't try a different endpoint, because I depend to a bureaucratic request to another department in my job (public service).

@vitorcsm hard to say where the issue can be without further tests on your side (as I don't think this is a general issue). To try a different endpoint you could just make a local installation of postgresql/postgis and import some data in it...

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
