### ISSUE TITLE
"SCR" window bug on Mageia

### ISSUE THREAD

**Issue by bertrand44** [qgis/QGIS#34121]
Bonjour,

Ma distribution est Linux Mageia.
Depuis la récente mise à jour de Mageia 6 en Mageia 7,
La version proposée de QGIS n'est plus 2.14.7.Essen mais Madera 3.4.15.

Hors, si l'ancienne version de QGIS fonctionnait très bien,
Il y a un bug dans la version Madera :
Lorsque je veux "définir le SCR de cette couche", 
la fenêtre qui s'ouvre ne se ferme plus, même si je clique sur "ok" ou "annuler",
et je suis alors obligé de "tuer" le programme en perdant toutes les modifications...

Je ne sais pas si ce bug provient de QGIS Madera ou de Mageia 7...
Peut-être aurez-vous une idée concernant la résolution de ce problème...

Je vous remercie d'avance,
Cordialement,
Bertrand.

**Comment by gioman** [comment]
@bertrand44 hi, can you please edit the title and description in order to be in English? Thanks!

**Comment by bertrand44** [comment]
TITLE : "SCR" window bug

Hello,

My distribution is Linux Mageia.
Since the recent update from Mageia 6 to Mageia 7,
The proposed version of QGIS is no longer 2.14.7.Essen but Madera 3.4.15.

Except, if the old version of QGIS worked very well,
There is a bug in the Madera version:
When I want to "define the SCR for this layer",
the window that opens no longer closes, even if I click on "ok" or "cancel" buttons,
and I am then obliged to "kill" the program by losing all the modifications ...

I do not know if this bug comes from QGIS Madera or Mageia 7 ...
Perhaps you will have an idea concerning the resolution of this problem ...

I thank you in advance,
Regards,
Bertrand.

**Comment by gioman** [comment]
> I do not know if this bug comes from QGIS Madera

It is not a general QGIS bug.

**Comment by bertrand44** [comment]
Thank you for that answer,
I will post a message on the mageia forum ...

Thank you

**Comment by alexbruy** [comment]
Seems local issue. Please reopen if necessary.
