### ISSUE TITLE
Save QML to overwrite existing qml does not do anything

### ISSUE THREAD

**Issue by gubuntu** [qgis/QGIS#34136]
**Describe the bug**
Saving a QML style (from the layer properties dialogue of a vector layer) over an existing one does not actually write anything. Choose 'replace file', OK etc. No errors but the original file remains. 

Saving the same style somewhere else works, then I used the file manager to copy the style over the previous one. 

**How to Reproduce**

**QGIS and OS versions**

3.4.14
Mac OSX

**Comment by DelazJ** [comment]
@gubuntu can you check on 3.10 because 3.4.15 was the last release of that version?

**Comment by gioman** [comment]
@gubuntu just tried on QGIS 3.10.1 on macOS Catalina, works as expected.

**Comment by gubuntu** [comment]
thanks, seems to be working on 3.4.15 too
