### ISSUE TITLE
QGIS Master Crashing on editing PostGIS 

### ISSUE THREAD

**Issue by rjhale1971** [qgis/QGIS#34131]
postgresql -> 12 
PostGIS -> 3 
QGIS -> 3.11 Rev: 50514b9577
Ubuntu Linux 19.10

I connect to a database - edit the table. I draw any size polygon and on right clicking one of two things happen: 
*Attribute form pop-up opens and is blank (as in no canvas) and then QGIS Crashes 
*QGIS Crashes upon right clicking. 

I captured this output from the last crash (crashed on right click) after starting QGIS in a terminal window: 
Fatal: ASSERT: "f.geometry().constGet()->vertexCount() == sm.size()" in file ../../src/app/qgsmaptooladdfeature.cpp, line 94
QGIS died on signal -1Aborted (core dumped)

I was able to successfully edit a Geopackage Created in 3.11 Master though.

**Comment by gioman** [comment]
I can't confirm this (QGIS master on Ubuntu 18.04) with an older PostgreSQL endpoint (not sure if it matters).

**Comment by rjhale1971** [comment]
Thanks for the comment - if I connect outside of my QGZ file (start a new project) it doesn't crash. So I'm going to work my way through that project file and start a new profile and see it's a plugin. Thanks much for the help. I'll let you know what I find out.

**Comment by rjhale1971** [comment]
I think the problem is the QGZ on my end file - I can't figure out what is wrong so I'll close this for now.
