### ISSUE TITLE
Duplicating a scratch layer ignores added fields

### ISSUE THREAD

**Issue by uclaros** [qgis/QGIS#34134]
**Describe the bug**
When duplicating a temporary scratch layer the copy does not have any fields that have been added manually to the original.

**How to Reproduce**
1. Create a temporary scratch layer, either by create layer menu or as a geoprocessing result.
2. Start editing, add a field, save edits, stop editing.
3. Right click on the layer and select duplicate layer
The copy layer that's created does not have the added field.

**QGIS and OS versions**
Tested on Linux master branch

**Comment by elpaso** [comment]
It's almost impossible to implement without a major rewrite of QGIS core classes given the current design of the vector layer and data provider classes.

**Comment by uclaros** [comment]
@elpaso maybe I'm missing something, but I have a pretty simple solution.
On memory layers, `QgsMemoryProvider.uri()` returns a uri with the fields that the layer had when created, ignoring any fields added later. On the other hand, `QgsMemoryProvider.dataSourceUri()` rebuilds the uri string upon request by iterating through fields, layer type, crs etc.

When duplicating a vector layer via `QgsVectorLayer.clone()`, the new layer is defined by:
https://github.com/qgis/QGIS/blob/73f707e02d8a634a91bfdb577b43733044bd1fe8/src/core/qgsvectorlayer.cpp#L228
`source()` is `QgsMapLayer.source()`:
https://github.com/qgis/QGIS/blob/73f707e02d8a634a91bfdb577b43733044bd1fe8/src/core/qgsmaplayer.cpp#L191-L194
and is the same value as `QgsMemoryProvider.uri().uri()`, which is outdated.

Simply changing `QgsVectorLayer *layer = new QgsVectorLayer( source(), name(), mProviderKey, options );` to `QgsVectorLayer *layer = new QgsVectorLayer( mDataProvider->dataSourceUri(), name(), mProviderKey, options );` in the layer creation seems to fix the problem and the resulting duplicated layer is correctly up to date.

I haven't checked yet why `layer.dataProvider().uri().uri() != layer.dataProvider().dataSourceUri()` though which is the root cause.

**Comment by elpaso** [comment]
Ok, thank you for the idea, let me have another look if your solution is safe.

**Comment by uclaros** [comment]
Some more things I noticed:
- The clone layer has 2 `uid=` on it's `dataProvider().uri().uri()`. Further cloning the clone, appends more `uid=`
- Cloning a layer with added fields results in a layer without the extra fields. Manually adding the field to the clone also brings the data it had on the original layer!
- Changing the crs has no effect on either Uris and subsequently no effect on the clones

**Comment by elpaso** [comment]
@uclaros please have a look to my PR if that address your issues. 

There is still an issue with the original vector layer source string not being updated, and that was my initial concern when I said "we need to rewrite half of qgis to get id done", because there is currently no way for the provider to access the vector layer datasource string.

**Comment by uclaros** [comment]
@elpaso That fixes it but as you said does not address the real issue, its a workaround. I'll try to check if there's an easy way to keep the memory provider up to date with the layer changes. It would be better if this was handled by QgsMemoryProvider rather than as an exception in QgsVectorLayer.

+1 for adding tests!
