### ISSUE TITLE
QGIS crashed using old workspace (3.10 suitable)

### ISSUE THREAD

**Issue by Mickeler** [qgis/QGIS#34149]
Error message below

Crash ID: 74c7a85cf14cd725655f9ce1d194f0c476f34f7a

Stack Trace

memcpy_repmovs memcpy.asm:115
VSICreateCachedFile :
OGRPGCommonAppendFieldValue :
OGRPGCommonAppendFieldValue :
OGRPGCommonAppendFieldValue :
QgsOgrProviderUtils::expandAuthConfig :
QgsVectorLayer::extent :
QgsMapSettings::fullExtent :
QgsMapCanvas::fullExtent :
QgsMapOverviewCanvas::setLayers :
QgsLayerTreeMapCanvasBridge::setCanvasLayers :
QgisApp::readProject :
QMetaObject::activate :
QgsProject::readProject :
QgsProject::readProjectFile :
QgsProject::unzip :
QgsProject::read :
QgsProject::read :
QgisApp::addProject :
QgisApp::openProject :
QgsVectorLayerLoadStyleDialog::updateLoadButtonState :
QMetaObject::activate :
QAbstractItemView::activated :
QAbstractItemView::mouseDoubleClickEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.10.0-A Coruña
QGIS code revision: 6c816b4204
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by gioman** [comment]
>  QGIS Version: 3.10.0-A Coruña

@Mickeler please update to 3.10.2

Also please add detailed steps to replicate and a sample project with data if necessary.

**Comment by Mickeler** [comment]
I got Python error message, when using 3.10.2

Ei voida ladata PyQGISia.
Python-tuki ei ole käytettävissä.


Traceback (most recent call last):
  File "", line 1, in 
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis/./python\qgis\core\__init__.py", line 84, in 
    QgsDxfExport.ExportResult.Success.__doc__ = "Successful export"
AttributeError: type object 'QgsDxfExport' has no attribute 'ExportResult'


Python-versio:
3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]

QGISin versio:
3.10.0-A CoruÃ±a 'A CoruÃ±a', 6c816b4204

Python-polku:
['C:/PROGRA~1/QGIS3~1.10/apps/qgis/./python', 'C:/Users/mikko.hamalainen/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python', 'C:/Users/mikko.hamalainen/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python/plugins', 'C:/PROGRA~1/QGIS3~1.10/apps/qgis/./python/plugins', 'C:\\PROGRA~1\\QGIS3~1.10\\apps\\Python37', 'C:\\PROGRA~1\\QGIS3~1.10\\apps\\Python37\\Scripts', 'C:\\Program Files\\QGIS 3.10\\bin\\python37.zip', 'C:\\PROGRA~1\\QGIS3~1.10\\apps\\Python37\\DLLs', 'C:\\PROGRA~1\\QGIS3~1.10\\apps\\Python37\\lib', 'C:\\Program Files\\QGIS 3.10\\bin', 'C:\\PROGRA~1\\QGIS3~1.10\\apps\\Python37\\lib\\site-packages', 'C:\\PROGRA~1\\QGIS3~1.10\\apps\\Python37\\lib\\site-packages\\win32', 'C:\\PROGRA~1\\QGIS3~1.10\\apps\\Python37\\lib\\site-packages\\win32\\lib', 'C:\\PROGRA~1\\QGIS3~1.10\\apps\\Python37\\lib\\site-packages\\Pythonwin']

**Comment by gioman** [comment]
> I got Python error message, when using 3.10.2

@Mickeler doing what?

> Python-versio:
> 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]
> 
> QGISin versio:
> **3.10.0**-A CoruÃ±a 'A CoruÃ±a', [6c816b4](https://github.com/qgis/QGIS/commit/6c816b4204162945336c18ccf44ffce7be2bf1b5)

seems it is still 3.10.0

**Comment by Mickeler** [comment]
OK, I try to reinstall 3.10.2

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
