### ISSUE TITLE
QGIS doesn't respect OGC guidelines for KVP parameters

### ISSUE THREAD

**Issue by lifa-lin** [qgis/QGIS#34148]
**Describe the bug**

QGIS makes unwarranted case sensitive comparisons of KVP keys

**How to Reproduce**

In the latest WFS 2.0 specification (and all previous specifications):
"09-025r1_OGC_Web_Feature_Service_WFS_2.0_ISOFDIS_19142_Geographic_information_-_Web_Feature_Service.pdf"

it clearly states in section "6.2.5.2 Parameter ordering and case" (my emphasis of NOT):

"Parameter names shall NOT be case sensitive, but parameter values shall be case sensitive. In this International Standard, parameter names used in KVP encoding are typically shown in uppercase for typographical clarity, NOT as a requirement."

**QGIS and OS versions**

Any version including 3.4.15, Windows 10

**Additional context**

I provide two non-standard "Login=" and "Password=" parameters in a WFS stub url, which some software of ours changed to lowercase, which prompted QGIS to re-insert the two parameters again (because clearly "login" was deemed different than "Login"), yielding an error. A case-insensitive comparision would have prevented this, which should have been performed re: the standard.

Please fix this.

**Comment by elpaso** [comment]
Sorry, but I don't understand: is this an issue on QGIS Desktop WFS provider or in QGIS Server?

Can you please explain step-by-step how to reproduce the issue? (I understand that the server might not be public)

**Comment by lifa-lin** [comment]
Hi elpaso.

When I open a WFS connection in QGIS, it looks something like this:

https://myserver/myhandler?Login=MyCustomer&Password=123456789&

The "Login" and "Password" parameters are needed to validate my requests thru "myhandler", but because they're non-standard, I provide them in the stub url (no other way).

The application "myhandler" recognizes and processes the non-standard parameters, but inserts them in the Capabilities document as "login" and "password", i.e. in lower case.

QGIS also handles and remembers the non-standard parameters in the stub url, and inserts them (I assume) if they're not present. Unfortunately this check for existence is case sensitive, so both "login" and "Login" ends up in the final url that's used to issue requests for DescribeFeatureLayer and GetFeature etc.

The server isn't case sensitive, so it sees two logins, yielding a "LOGIN" value of "MyCustomer,MyCustomer" (and the same for password), which is clearly errornous.

But QGIS should test for existence of these non-standard parameters in a case IN-sensitive manner as per the documentation. If it did, the "login" would only appear once in the urls, and things would work. This is the crux of this bug issue.

It's unfortunate that "myhandler" lowercases the parameter keys, but this is perfectly legal, as keys are to be considered case-INsensitive as per the documentation.

The only other possibility is that QGIS insert the non-standard parameters regardless of whether they are present or not in the Capabilities url's, which I think would also constitute a bug.

Cheers.
