### ISSUE TITLE
Issue with datum when exporting SHP EPSG:2260

### ISSUE THREAD

**Issue by brendan35** [qgis/QGIS#34155]
**QGIS and OS versions**
3.10 and prior versions

**Additional context**

Exporting SHPs to EPSG:2260 exports successfully. When importing SHPs into autocad, autocad recognizes the SHP as EPSG:3432, but when imported into an EPSG:2260 drawing appears to be geolocated correctly.

**Comment by gioman** [comment]
Can you attach a sample of your exported SHP in EPSG 2260?

**Comment by nyalldawson** [comment]
This sounds like an autocad issue, not qgis...
