### ISSUE TITLE
In-consistence between legend in map layout and legend item

### ISSUE THREAD

**Issue by lochkalyan** [qgis/QGIS#34166]
**In-consistence between legend in map layout and legend item**
I am curious why it was difference between legend item and legend in map layout. Anyone can help to fix this issue (QGIS version 3.10)? Thank in advance.
![image](https://user-images.githubusercontent.com/7929651/73519583-0fa9dd00-4434-11ea-9b17-4a9bc7cc0d3d.png)

**Comment by elpaso** [comment]
Please share a test project and data where a developer can reproduce the issue.

**Comment by MrXsquared** [comment]
I have noticed the same bug, so I will provide the steps to repoduce it and an example project with data. I have only tested in Windows 64bit Version of QGIS 3.10.0, but as I have heard the same issue exists in 3.10.1 and 3.10.2. I can not reproduce it in 3.8 or 3.4.

**Steps to see the issue in attached project:**
[Test.zip](https://github.com/qgis/QGIS/files/4149450/Test.zip)
1. Open the attached project with QGIS 3.10.x
2. Go to Project -> Layouts -> Test
3. See the legend in this print-layout

**Steps to reproduce yourself:**
1. Create a point layer and place some points (file format does not matter)
2. Add a double or integer field and fill it with random values
3. Create a diagram (via diagrams) or symbol (via size assistant) with varying size 
4. Create a collapsed legend for the diagram (via diagrams -> legend) or symbol (via data defined size legend)
5. Create a print layout and add a legend to it
6. The legend in print layout is now corrupted

**Comment by jgrocha** [comment]
I notice this inconsistence for rasters and wms/wmts layers.

The ![mIconRaster](https://user-images.githubusercontent.com/163681/74158390-e64a3780-4c11-11ea-91ca-c13beeeb8129.png) is missing in the layout, although it appears in the legend and in the legend item form.

In this case, QGIS Server also does not provide the legend icon. An empty image is return.

To reproduce:
1. Create project with raster or wms/wmts layer.
1. Create layout
1. The layout does not include the icon
1. Get the legend using QGIS Server: an empty image is returned.

**Comment by sjpark1989** [comment]
Hi is this still an issue with the latest version?

**Comment by nyalldawson** [comment]
No, this one is fixed
