### ISSUE TITLE
Can't add layer to 2nd project opened in session

### ISSUE THREAD

**Issue by Houska1** [qgis/QGIS#34160]
3.10.2-2 (OSGeo4W), code revision `d4cd3cfe5a`

Work on project A, then in same session (without shutting down QGIS) open different project B.
Attempt to add a layer. Does not appear in canvas or layer tree (legend), no error message given; seems just not to have been added at all.

This is regardless of whether I drag'n'drop from browser, right click in browser and say Add to project.., or go through the `Layer / Add layer ..` menu and dialog. I can add the same layer in project A, or project B if I restart QGIS and B becomes the first project I work on.

I've tried this on several layers, and several different projects (in the project A and B roles) though as I write this up I realize I've always been adding vector layers from inside a gpkg. Not sure if that matters.

I think I encountered this once a few weeks ago with 3.10.1, but I didn't have time to isolate at that time. It definitely worked fine with 3.8.

Haven't tried on a fully clean profile, but have duplicated on a different machine (also Windows) which I rarely use, and its default profile, so unlikely to be profile corruption I think.

**Comment by gioman** [comment]
> Work on project A, then in same session (without shutting down QGIS) open different project B.
> Attempt to add a layer. Does not appear in canvas or layer tree (legend), no error message given; seems just not to have been added at all.
> 
> This is regardless of whether I drag'n'drop from browser, right click in browser and say Add to project.., or go through the `Layer / Add layer ..` menu and dialog. I can add the same layer in project A, or project B if I restart QGIS and B becomes the first project I work on.

@Houska1 just to be sure about the steps to follow:

1) open project A (already existing? blank?)

2) add a layer in the project

3) save(?)

4) open project B (already existing? blank?)

5) add the same layer added in step 2

correct?

**Comment by Houska1** [comment]
@gioman 
1. Launch QGIS which opens existing project A. Optionally do anything in project A, but not required.
2. Project / Open recent... another existing project B
3. Attempt to add layer to project B by dragging from browser, right clicking in browser, or Layer / Add layer.... Nothing happens.

In contrast, if try to add the same layer to Project A, as "step 1.5" in the above list, it works at that point.

If after step 3:
4. Close QGIS
5. Restart QGIS, which opens Project B
6. Add the same layer <--- this works.

**Comment by Houska1** [comment]
I did write above I had only tried adding a vector layer from a gpkg. I have now verified that I can't add *any* layer to Project B (if it was opened as above). Have just checked that I can't add a tif raster or a ArcGisFeatureServer browser tree entry either.

**Comment by Houska1** [comment]
I'm going to close this for now, and reopen after some more exploration if needed.

It turns out the projects I've tried this on have openProject() and closeProject() macros. This problem isn't happening if I run in a profile *in which I've disabled macros*. It's still weird it worked in 3.8 and not 3.10 but I'll do a bit more exploration myself to figure out if (and how) in the macros are related.
