### ISSUE TITLE
Local  drive root path can not be opened in browser panel on Windows in qgis-dev

### ISSUE THREAD

**Issue by FelisPimeja** [qgis/QGIS#34169]
This happens with the current qgis-dev version on Windows with new clean profile and no third plugins installed. In browser panel I can not expand any local drive to see it's root folders. Instead, I get an error in Messages tab of log panel:

`2020-01-31T12:04:08     CRITICAL    Qt : QFileSystemWatcher::addPath: path is empty`

And the folders listed in browser panel located not in the root folder of drive C:\ (for example) but in C:\Users\%User profile%\Documents\

This happened a couple of revisions ago, not sure when exactly.
![image](https://user-images.githubusercontent.com/874261/73526505-72927880-4422-11ea-9f28-0e014564c3ca.png)

System info:
Windows 10 x64
QGIS 3.11.0-68 x64 OSGEO

QGIS version
3.11.0-Master
QGIS code revision
ee323eb5c1
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.0dev
Running against GDAL/OGR
3.1.0dev
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
7.0.0
Running against PROJ
Rel. 7.0.0, March 1st, 2020
OS Version
Windows 10 (10.0)
This copy of QGIS writes debugging output.
Active python plugins
db_manager; 
MetaSearch; 
processing

**Comment by saberraz** [comment]
Also confirmed in Linux on master.

**Comment by Saijin-Naib** [comment]
The same behavior applies for mapped network drives under Windows, as well.

**Comment by rjhale1971** [comment]
On Master Revision 6bffe18af3 on Ubuntu 19.10 I also get the same error as shown above. 

2020-02-07T09:46:10     CRITICAL    Qt : QFileSystemWatcher::addPath: path is empty

**Comment by rduivenvoorde** [comment]
Yess! Checked: Works! Thanks (also for the docs :-) )!
