### ISSUE TITLE
QGIS 3.102 crashing repeatedly this morning

### ISSUE THREAD

**Issue by ghost** [qgis/QGIS#34176]
**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**
## User Feedback

i was moving a layer in the window . It has been locking up all morning on the full time release with a cursor spinning the crashes

## Report Details

**Crash ID**: [019e7c4b02c464431071767a7a3f1b0e15e2b96a]('https://github.com/qgis/QGIS/search?q=019e7c4b02c464431071767a7a3f1b0e15e2b96a&type=Issues')

**Stack Trace**
<pre>
QgsGeometry::closestVertex qgsgeometry.cpp:385
QgsPointLocator_VisitorNearestVertex::visitData qgspointlocator.cpp:113
Index::~Index :
Index::~Index :
QgsPointLocator::nearestVertex qgspointlocator.cpp:841
_updateBestMatch qgssnappingutils.cpp:190
QgsSnappingUtils::snapToMap qgssnappingutils.cpp:327
QgsSnappingUtils::snapToMap qgssnappingutils.cpp:226
meth_QgsSnappingUtils_snapToMap sip_corepart3.cpp:53442
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_sip :
sipVH__gui_250 sip_guipart0.cpp:6003
sipQgsMapToolEmitPoint::canvasMoveEvent sip_guipart2.cpp:182856
QgsMapCanvas::mouseMoveEvent qgsmapcanvas.cpp:1727
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1598
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.2-A Coru�a
QGIS code revision: d4cd3cfe5a
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.3
Running against GDAL: 3.0.3

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

I was moving a layer in the window . It has been locking up all morning on the full time release with a cursor spinning the crashes

**Comment by gioman** [comment]
> i was moving a layer in the window . It has been locking up all morning on the full time release with a cursor spinning the crashes

@MPN-stack the drill is always the same:

1) try if a new QGIS profile helps (do not install any 3rd party plugin)

2) if 1) does not help then attach a sample project with data that can help us find the source of the issue

**Comment by NathanW2** [comment]
This looks like a possible plugin issue due to the Py** stack frames and
sip lines. Which plugins do you have installed currently

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
