### ISSUE TITLE
WMS on QGIS Server 3.10.2 ignoring layers with scaledenominator

### ISSUE THREAD

**Issue by geoang** [qgis/QGIS#34174]
publishing a wms containing layers with scale dependent visibility in qgis server 3.10.2 (on windows server!) does not work as expected. the getmap returns an image without the layer even tough the image has been requested within the visibility range of the layer.

getcapabilities lists the layer correctly.

bug?

**Comment by gioman** [comment]
> bug?

seems so but right now I can't check, will do it asap.

**Comment by tobias-brunner** [comment]
Same here (windows 2016 server). Works on Linux though.

**Comment by Abelon38** [comment]
Hi ! I have the same problem with QGIS server 3.12 on Windows 2016. Have you guys tried with QGIS 3.4 ?
/Abel

**Comment by Abelon38** [comment]
Hi again!

It seams to work with .qgz instead for .qgs.

Good luck!

**Comment by elpaso** [comment]
Please try with QGIS 3.16 and if the problem persists we can reopen the issue.
