### ISSUE TITLE
CityGML-Import LoD1 (official source) - objects are missing (QGIS 3.10.2)

### ISSUE THREAD

**Issue by RolfBerlin** [qgis/QGIS#34173]
**Describe the bug**
Result of importing  LoD1-files (and of the corresponding LoD2-files as well) is that several buildings are missing. In the jpg attached you can see - 3 of them signed with a circle. 
The missing buildings are included in "LoD1_419915-5737900_geb.gml" as a friend saw in  Sketchup ! 
The corresponding file "LoD1_419915-5737900_geb.txt" says 321 buildings. 
The Attribute table in QGIS says 321 objects, all of them appear on the map. Because, when I mark all objects in the map the result is also 321 Objects, but more than 3 are not in the map ... !!
The source of the official files is a state-office "LGB - Landesvermessung und Geobasisinformation Brandenburg". LGB said, that the 3 buildings should appear and they couldn't find any errors in the provided files. 
They gave mit the IDs of the 3 missing buildings, but in QGIS other buildings have these  IDs ... (see jpg)
left: DEBBAL66000274Xr
top: DEBBAL66000274Yr
right: DEBBAL66000274YZ
May be its a problem that LGB uses UTF-16LE ? When importing GML the result is always UTF-8 and can't be converted to UTF-16LE.   UTF-8 is what I normally use.

**How to Reproduce**
CityGML Dataset is attached:
[LoD1_419915-5737900_geb.zip](https://github.com/qgis/QGIS/files/4138821/LoD1_419915-5737900_geb.zip)    (3 files)

EPSG:25833 - ETRS89 / UTM zone 33N

(For reproducing the download:  https://geobroker.geobasis-bb.de/basiskarte.php?mode=startup&aProductId=0414a37a-a749-4ee6-9f59-a41226919c58.  Zinnitz you can find with the magnifying glass, 2. icon from right).

**QGIS and OS versions**
3.10.2

**Additional context**

![CityGML LoD1 (also LoD2) - Bug Report QGIS](https://user-images.githubusercontent.com/47972999/73531867-aae28880-441b-11ea-8ede-34508035d386.jpg)

**Comment by gioman** [comment]
> CityGML Dataset is attached:
> LoD1_419915-5737900_geb.zip (3 files)
> (Download-site: https://geobroker.geobasis-bb.de/basiskarte.php?mode=startup&aProductId=0414a37a-a749-4ee6-9f59-a41226919c58. Zinnitz you can find with the magnifying glass, 2. icon from right).
> EPSG:25833 - ETRS89 / UTM zone 33N

@RolfBerlin sorry I can't figure how to download the dataset from that web viewer in german, can you just attach the zip file? thanks.

**Comment by RolfBerlin** [comment]
Hi, you can find the ZIP at the end of my report.
Thx in advance!
Rolf

**Comment by gioman** [comment]
> Hi, you can find the ZIP at the end of my report.

sorry I missed it.

**Comment by RolfBerlin** [comment]
I pushed the ZIP a bit higher ...

**Comment by gioman** [comment]
>  [LoD1_419915-5737900_geb.zip](https://github.com/qgis/QGIS/files/4138821/LoD1_419915-5737900_geb.zip) (3 files)

@RolfBerlin here is the problem... it's complicated :)

Disclaimer: I personally do not grap/understand fully the whole matter, so consider the following just as vague explanation.

There are GML datasources that encode inside a complex data model (i.e. Inspire, citygml), to read this data correctly a specific driver was added to GDAL/OGR, is called GMLAS:

https://gdal.org/drivers/vector/gmlas.html

If you do ogrinfo on this datasources without using the GMLAS driver the result seems simple:

```
ogrinfo -so LoD1_419915-5737900_geb.gml
Warning 1: Unrecognized geometry type : 1015
Had to open data source read-only.
INFO: Open of `LoD1_419915-5737900_geb.gml'
      using driver `GML' successful.
Metadata:
  NAME=LoD1_420_5738_2_BB
1: Building
```
it seems there is only 1 layer/table (Building)

ogrinfo -so LoD1_419915-5737900_geb.gml Building
Warning 1: Unrecognized geometry type : 1015
Had to open data source read-only.
INFO: Open of `LoD1_419915-5737900_geb.gml'
      using driver `GML' successful.
Metadata:
  NAME=LoD1_420_5738_2_BB

```
Layer name: Building
Geometry: Unknown (any)
Feature Count: 321
Extent: (420234.162000, 5738292.900000) - (421295.202000, 5739203.480000)
Layer SRS WKT:
(unknown)
gml_id: String (0.0) NOT NULL
creationDate: String (10.0)
informationSystem: String (66.0)
name: String (16.0)
DatenquelleDachhoehe: IntegerList (0.0)
DatenquelleLage: IntegerList (0.0)
DatenquelleBodenhoehe: IntegerList (0.0)
Gemeindeschluessel: Integer (0.0)
BezugspunktDach: IntegerList (0.0)
function: String (10.0)
measuredHeight: Real (0.0)
measuredHeight_uom: String (13.0)
name_: String (12.0)
consistsOfBuildingPart|BuildingPart|creationDate: StringList (0.0)
consistsOfBuildingPart|BuildingPart|measuredHeight: RealList (0.0)
consistsOfBuildingPart|BuildingPart|measuredHeight_uom: StringList (0.0)
```

But if you use the GMLAS driver you see that there is much more going on...


```
ogrinfo -so GMLAS:LoD1_419915-5737900_geb.gml
Had to open data source read-only.
INFO: Open of `GMLAS:LoD1_419915-5737900_geb.gml'
      using driver `GMLAS' successful.
1: buildingpart (Multi Curve)
2: buildingpart_metadataproperty (None)
3: buildingpart_name (None)
4: building (Multi Curve)
5: building_metadataproperty (None)
6: building_name (None)
7: address1 (Multi Point)
8: address_metadataproperty (None)
9: address_name (None)
10: addre_xaladdre_addredetai_postaservicelemen_addresidentifier (None)
11: addr_xaladdre_addredetai_postaservieleme_supplpostaservidata (None)
12: address_xaladdress_addressdetails_country_countrynamecode (None)
13: address_xaladdress_addressdetails_country_countryname (None)
14: location (None)
15: stringattribute (None)
16: externalreference (None)
17: consistsofbuildingpart (Multi Curve)
18: consistsofbuildingpart_buildingpart_metadataproperty (None)
19: consistsofbuildingpart_buildingpart_name (None)
20: address2 (None)
21: addressline (None)
22: mailstopname (None)
23: mailstopnumber (None)
24: postalcode (None)
25: postalcode_postalcodenumber (None)
26: postalcode_postalcodenumberextension (None)
27: postalcode_posttown_posttownname (None)
28: department (None)
29: department_departmentname (None)
30: postbox (None)
31: thoroughfarenumber (None)
32: thoroughfarenumberprefix (None)
33: thoroughfarenumbersuffix (None)
34: largemailusername (None)
35: largemailuseridentifier (None)
36: buildingname (None)
37: thoroughfare (None)
38: premisenumber (None)
39: premisenumbersuffix (None)
40: firmname (None)
41: mailstop (None)
42: subpremisename (None)
43: subpremiselocation (None)
44: subpremisenumber (None)
45: subpremisenumberprefix (None)
46: subpremisenumbersuffix (None)
47: firm (None)
48: subpremise (None)
49: subpremise_buildingname (None)
50: premise (None)
51: premise_premisename (None)
52: premi_preminumberange_preminumberangefrom_premisnumberprefix (None)
53: premi_preminumberange_premisnumberrangeto_premisnumberprefix (None)
54: premise_premisenumberprefix (None)
55: premise_buildingname (None)
56: premise_subpremise (None)
57: premise_subpremise_buildingname (None)
58: dependentlocalityname (None)
59: dependentlocalitynumber (None)
60: largemailuser (None)
61: postoffice (None)
62: postoffice_postofficename (None)
63: postoffice_postalroute_postalroutename (None)
64: postalroute (None)
65: postalroute_postalroutename (None)
66: dependentlocality (None)
67: locality (None)
68: locality_localityname (None)
69: locality_postalroute_postalroutename (None)
70: administrativearea (None)
71: administrativearea_administrativeareaname (None)
72: administratiarea_subadministratiarea_subadministratiareaname (None)
73: buildingpart_externalreference_externalreference (None)
74: buildipart__generiapplicapropertofcityobject_stringattribute (None)
75: buildingpart_consistsofbuildingpart_consistsofbuildingpart (None)
76: buildingpart_address_address (None)
77: building_externalreference_externalreference (None)
78: buildin__genericapplicatpropertyofcityobject_stringattribute (None)
79: building_consistsofbuildingpart_consistsofbuildingpart (None)
80: building_address_address (None)
81: addre_xaladdre_addredetail_addreslines_addresline_addresline (None)
82: addres_xaladdres_addresdetail_countr_addressline_addressline (None)
83: consisofbuildipart_buildipart_externreferen_externareference (None)
84: consofbuilpart_builpart__geneapplpropofcityobje_striattribut (None)
85: consiofbuildpart_buildpart_consiofbuildpart_consiofbuildpart (None)
86: consistsofbuildingpart_buildingpart_address_address (None)
87: postalcode_addressline_addressline (None)
88: postalcode_posttown_addressline_addressline (None)
89: department_addressline_addressline (None)
90: department_mailstop_addressline_addressline (None)
91: postbox_addressline_addressline (None)
92: postbox_firm_addressline_addressline (None)
93: postbox_firm_firmname_firmname (None)
94: postbox_firm_department_department (None)
95: thoroughfare_addressline_addressline (None)
96: thoroughfare_thoroughfarenumberrange_addressline_addressline (None)
97: thoro_thoronumberange_thorounumberfrom_addresline_addresline (None)
98: thor_thornumbrang_thornumbfrom_thornumbpref_thoronumbeprefix (None)
99: thoro_thoronumberange_thoronumbefrom_thoronumbe_thorounumber (None)
100: thor_thornumbrang_thornumbfrom_thornumbsuff_thoronumbesuffix (None)
101: thoro_thorounumberrange_thorounumberto_addresline_addresline (None)
102: thor_thornumbrang_thornumbto_thornumbeprefi_thoronumbeprefix (None)
103: thoro_thoronumberange_thoronumbeto_thorounumber_thorounumber (None)
104: thor_thornumbrang_thornumbto_thornumbesuffi_thoronumbesuffix (None)
105: mailstop_addressline_addressline (None)
106: firm_addressline_addressline (None)
107: firm_firmname_firmname (None)
108: firm_department_department (None)
109: subpremise_addressline_addressline (None)
110: subpremise_subpremisename_subpremisename (None)
111: subpremise_subpremisenumber_subpremisenumber (None)
112: subpremise_subpremisenumberprefix_subpremisenumberprefix (None)
113: subpremise_subpremisenumbersuffix_subpremisenumbersuffix (None)
114: subpremise_mailstop_addressline_addressline (None)
115: premise_addressline_addressline (None)
116: premise_premisenumber_premisenumber (None)
117: prem_preminumberange_preminumberangefrom_addreline_addreline (None)
118: prem_premnumbrang_preminumberangefrom_preminumbe_preminumber (None)
119: pre_prenumbrang_premnumbrangfrom_premnumbsuff_premnumbsuffix (None)
120: premi_preminumberange_preminumberangeto_addreline_addresline (None)
121: prem_premnumberange_preminumberangeto_preminumbe_preminumber (None)
122: prem_premnumbrang_premnumbrangto_premnumbsuff_premnumbsuffix (None)
123: premise_premisenumbersuffix_premisenumbersuffix (None)
124: premise_subpremise_addressline_addressline (None)
125: premise_subpremise_subpremisename_subpremisename (None)
126: premise_subpremise_subpremisenumber_subpremisenumber (None)
127: premis_subpremis_subpremisnumberprefix_subpremisnumberprefix (None)
128: premis_subpremis_subpremisnumbersuffix_subpremisnumbersuffix (None)
129: premise_subpremise_mailstop_addressline_addressline (None)
130: premise_firm_addressline_addressline (None)
131: premise_firm_firmname_firmname (None)
132: premise_firm_department_department (None)
133: premise_mailstop_addressline_addressline (None)
134: largemailuser_addressline_addressline (None)
135: largemailuser_largemailusername_largemailusername (None)
136: largemailuser_buildingname_buildingname (None)
137: postoffice_addressline_addressline (None)
138: postoffice_postalroute_addressline_addressline (None)
139: postalroute_addressline_addressline (None)
140: dependentlocality_addressline_addressline (None)
141: dependenlocality_dependentlocalityname_dependentlocalityname (None)
142: locality_addressline_addressline (None)
143: locality_largemailuser_addressline_addressline (None)
144: locality_largemailuser_largemailusername_largemailusername (None)
145: locality_largemailuser_buildingname_buildingname (None)
146: locality_postalroute_addressline_addressline (None)
147: locality_dependentlocality_addressline_addressline (None)
148: localit_dependelocalit_dependelocalitname_dependelocalitname (None)
149: administrativearea_addressline_addressline (None)
150: administratiarea_subadministratiarea_addressline_addressline (None)
```


You can use GDAL/OGR (a recent version like 3.0) to translate this GML into another format like GPKG and along the way "resolve" the relations within this complex data model:

`ogr2ogr -f GPKG test.gpkg GMLAS:LoD1_419915-5737900_geb.gml -oo REMOVE_UNUSED_FIELDS=YES`


This will give you a GPKG with several tables/layers in, in this specifi case you will have 2 that seems to represent the footprints of the buildings you are looking for:

![Screenshot_20200131_150702](https://user-images.githubusercontent.com/1951107/73549863-5ea74080-443b-11ea-951e-b27b8995b939.png)

[test.gpkg.zip](https://github.com/qgis/QGIS/files/4140035/test.gpkg.zip)


As far as I know there isn't yet a mechanism/tool in core QGIS that allows to handle this datasets, I think there are 3rd party plugins.

**Comment by gioman** [comment]
There should not be any issue here, it is at best a feature request (in order to allow QGIS handle this datasets via GDAL/OGR, but I think there are other tickets about it).

**Comment by RolfBerlin** [comment]
Thanks a lot Giovanni for your analytics!!! 
Many things you explain I haven't heard of before, e.g. "GMLAS driver" or "GDAL/OGR". I have no idea how to translate my GML like you did ... 
The screenshot looks great! The best would be a plugin that functions this way ... So far I couldn't find one ... Does anybody know ?

**Comment by rouault** [comment]
> The best would be a plugin that functions this way ... So far I couldn't find one ... Does anybody know ?

--> https://plugins.qgis.org/plugins/gml_application_schema_toolbox/

**Comment by RolfBerlin** [comment]
@roualt: Thanks for the link. I found this plugin some days ago but it seems for specialists !? To try all options as a non-expert on GML I need one week of try and error.
What I need is Import -> convert -> export, Or a step by step explanation for "GML Application Schema toolbox QGIS" plugin. Then i would give it a try.

**Comment by RolfBerlin** [comment]
I found a workflow here:
https://github.com/INSPIRE-MIF/caniuse/issues/3
But although I am a little bit firm with DOS-commands I can't find a way to change in OSGeo4W from C: to my folder on D:  as explained in Step 2.
Sorry, but isn't there an easier way ?

**Comment by gioman** [comment]
> I found a workflow here:

@RolfBerlin you don't need much workflow, it is just one command (example):

ogr2ogr -f GPKG c:\path\to\your\ouput.gpkg GMLAS:c:\path\to\your\input.gml -oo REMOVE_UNUSED_FIELDS=YES

just use the OSGeo4W command line shell you get with any QGIS installation.


> But although I am a little bit firm with DOS-commands I can't find a way to change in OSGeo4W from C: to my folder on D: as explained in Step 2.

the command to change drive/directory is "cd", i.e.

cd d:\myfolder

but if you use the command as above  you won't need it.

Anyway, having ogr2ogr a a weapon in your arsenal in priceless, is the swiss army knife for vector data, and some more...


>  Sorry, but isn't there an easier way ?

personal opinion here:
"easy" is not the word that "they" had in mind when they created this complex data models/formats ("complex" refers the way the data is encoded/structured within the datasource, not the data itself). Bottom line, for the final users consuming this type of data is a pain in the b**t. And this has nothing to do with QGIS in first place.

There was a plugin for QGIS 2.* that used to yield some results (https://github.com/JuergenWeichand/qgis-gml-loader) but this wasn't ported to QGIS 3, that indicates that really there is not that big interest. The https://plugins.qgis.org/plugins/gml_application_schema_toolbox/ plugin seems like a much more advanced/complete tool, but I have never made really to make it work.

**Comment by RolfBerlin** [comment]
**PERFECT !! I got all the missing buildings !!** 
Thank you !!!

To summarize:
In the screenshot you can see the command I used.
![command](https://user-images.githubusercontent.com/47972999/73591444-bd79c200-44ee-11ea-895c-066e5d4ac3be.jpg)
As result I got a gpkg-file that I imported in QGIS. I had to choose between dozends of layers.
I chosed Layer-ID Nr. 0 "building" (all the buildings I had before)
and Nr. 1 "consistsofbuildingpart" (all the buildings I missed !!)
So now I combine these to one.  Done!

I am in contact with the Official Provider of the CityGML-Files. Is there anything they should change in the provided GML-Files I could tell them to make the import easier, in a direct way without using OSGeo4W shell ? How to explain ?  Do have a proposal for me that I can send the provider? 
Many thanks in advance.
Rolf

**Comment by gioman** [comment]
@RolfBerlin there can be bureaucratic (i.e. INSPIRE) or technical reasons to ship data in this complex data models, after all citygml is standard format from OGC. In general I don't understand why in some cases the underlying data is not shipped also in a more user/gis friendly format.

**Comment by rouault** [comment]
You may also add ``-oo REMOVE_UNUSED_LAYERS=YES``

**Comment by RolfBerlin** [comment]
@rouault  Many thanks for your addition.

@gioman  Many thanks for your explaining. I'll try to get in contact with the official provider (state). Not so easy for me via mail (maybe phone) without any experience in CityGML. It's a big topic for me now cause in Brandenburg state of Germany its now opendata since 2 weeks !!!  

There is a new problem! Thats why the issue isn't really closed for me, I'm sorry:
With the new gpkg-file (I received with your help) I can now see all buildings in the right place! But when saving this Layer in a new Shapefile-Layer the buildings are missing as in the beginning. Different is: some are filled with colour, some are missing, some just have frames which I can't fill with colour. I need the layer as shp because I have to categorize the buildings together with many other information in ready prepared Layers ......

Very special: The often I save the gpkg-file in different GCS (WGS84, Pseudo-Mercator, 3044, 3045 etc.) the more buildings appear filled with colours (and perfect useable in shp) instead of just having a frame before (s. jpg). I have no idea what this has to do with GCS ... it was just a try. This workflow makes nearly every building useable in shp when I merge the layers, but the workflow costs too much time, cause I have to do this steps for nearly 100 villages ...

![CityGML Zinnitz - LoD1 (also LoD2) - Bug Report QGIS 2](https://user-images.githubusercontent.com/47972999/73608661-005a9900-45c6-11ea-9ba0-f56d69164365.jpg)

**Comment by gioman** [comment]
> But when saving this Layer in a new Shapefile-Layer the buildings are missing as in the beginning.

@RolfBerlin 

well it seems that the buildings are in separate layers in the GPKG generated from the GML. did you merged them?

**Comment by RolfBerlin** [comment]
From the GPKG-layer (here "...nur building (25833) ...") I saved the 6 above individually as shp, all with different GCS/CRS as you can find in the layer-names.

Yes, in one layer (the bottom one, not activated) I copied all objects from all 6 layers, but as result there were 2528 objects in this layer instead of 528 in the GPKG-layer. It is theoretically possible to work with this one, but, as I wrote, not the workflow I can follow.

**Comment by moet1972** [comment]
I had the same problem with LOD1 data from Marburg. After converting the GML into a GPKG-File I tried as well to convert the GPKG-layers into Shapefiles with Save as... A lot of buildings were not displayed but in the attribute table. These ones had a corrupt geometry in the exported Shapefile.
I solved the Problem with Vector geometry => Fix geometries: One GPKG-layer as Input layer and a Shapefile as Output layer. I don't know if this works for your files as well. My QGIS is 3.10.2

**Comment by gioman** [comment]
> I had the same problem with LOD1 data from Marburg. After converting the GML into a GPKG-File I tried as well to convert the GPKG-layers into Shapefiles with Save as... A lot of buildings were not displayed but in the attribute table. These ones had a corrupt geometry in the exported Shapefile.
> I solved the Problem with Vector geometry => Fix geometries: One GPKG-layer as Input layer and a Shapefile as Output layer. I don't know if this works for your files as well. My QGIS is 3.10.2

so complex data model + geometry errors = not easy for users

**Comment by RolfBerlin** [comment]
@moet1972 Thanks for the advice. Unfortunately I had to many errors at the end ...

**Comment by RolfBerlin** [comment]
@gioman Hi Giovanni, can you please reopen the issue, cause I have no solution for getting a useable Shape-File so far.
Thanks in advance! Rolf

**Comment by gioman** [comment]
> @gioman Hi Giovanni, can you please reopen the issue, cause I have no solution for getting a useable Shape-File so far.
> Thanks in advance! Rolf

@RolfBerlin I can, but what is actually the QGIS issue?
As far I understand there are two issues that are not QGIS's ones:

the original data is encoded in a "unfortunate" format that must be "flattened" using OGR before consuming it in QGIS. This results in a datasource that has a lot of tables/layers, if in this tables there are missing features this is not a QGIS issue, eventually it could be in the OGR driver used to extract this data.

also if the resulting features have geometry errors this is likely a problem in the original dataset.


This is the result of the merge of the (polygon) layers from the original datatset

[merged.gpkg.zip](https://github.com/qgis/QGIS/files/4158728/merged.gpkg.zip)

Can you point to the issues in it?

**Comment by RolfBerlin** [comment]
@gioman Sorry, that I call it an "issue" without a prove. I'm not an expert. The provider says the import works with other software ... Why not with QGIS ? A friend opened the GML in Sketchup (I know it's not GIS) and everything looked great, also with the roofs in LoD2-GML.
Maybe the problem is in the provided GML, as you assume,  how to explain this to the provider instead of the data should be "flattened"?
Do you see a problem in the fact that the data is stored with UTF-16LE, which I never use ?

**Comment by gioman** [comment]
@RolfBerlin is https://github.com/qgis/QGIS/files/4158728/merged.gpkg.zip correct or not?

**Comment by gioman** [comment]
> Sketchup

I cannot test it, it is required to create an account to download the trial, something I don't want to do.



> also with the roofs in LoD2-GML

what is this?

**Comment by RolfBerlin** [comment]
The GPKG-Merge is correct, like the GPKG-Merge some days before. But saved as Shape there are the same problems as in the beginning.
The provider provides different GML on his website:
LoD1 = without roofs
LoD2 = with roofs

**Comment by gioman** [comment]
> The GPKG-Merge is correct, like the GPKG-Merge some days before. But saved as Shape there are the same problems as in the beginning.

can you point me (maybe with screenshots) at the issues you see after having saved the GPKG as SHP?

**Comment by RolfBerlin** [comment]
![merged](https://user-images.githubusercontent.com/47972999/73837324-84ed2780-4811-11ea-8f4b-00dcc3f231eb.JPG)
![merge to shp](https://user-images.githubusercontent.com/47972999/73837326-8585be00-4811-11ea-8d28-b5e81f501223.JPG)

The objects with just a frame in the new shp-Layer cannot be marked as an object on the map. 
In the attribute table there are many objects with no data in the column "ID". But these are not all objects that are just framed. When all objects with no "ID" are marked in the attribute table than I can see on the map some of them have just a frame, some are colour-filled ...

**Comment by RolfBerlin** [comment]
here a screenshot from Sketchup with GML as LoD2 (with roofs)
![GML LoD2 in Sketchup](https://user-images.githubusercontent.com/47972999/73838546-35f4c180-4814-11ea-8ba5-8fecfa5b7fb0.JPG)

**Comment by gioman** [comment]
@RolfBerlin this dataset is nasty on several levels.



> ![merge to shp](https://user-images.githubusercontent.com/47972999/73837326-8585be00-4811-11ea-8d28-b5e81f501223.JPG)


I see the above now, after exporting the GPKG to SHP. The polygons you see just outlined are still polygons (it could not be different in a polygon layer), but for some strange reason during the conversion GPKG > SHP they get mangled.

If you use the "fix geometries" tool (from the Processing toolbox) on the GPKG layer and then export to SHP you get the expected result.

Anyway there is really something fishy in the data, as QGIS/OGR reports 528 features (in the merged layer) but actually there are only 438 features in the table.



> In the attribute table there are many objects with no data in the column "ID"

You merged polygons from 2 different layers, that evidently had different table of attributes. In fact can see that the polygons that have the "id" filled they have not a "buildingpart_id" and vice versa.


[as_shape.zip](https://github.com/qgis/QGIS/files/4159910/as_shape.zip)

**Comment by RolfBerlin** [comment]
@gioman 
 
> You merged polygons from 2 different layers, that evidently had different table of attributes. In fact can see that the polygons that have the "id" filled they have not a "buildingpart_id" and vice versa.

I didn't merge polygons from 2 different layers. What you see above was just taking your "merged"(GPKG)-file and saved it as shp.

I checked your "as_shape.zip" - the result is fine now, except of "438 features vs. 528 features" as you mentioned.  
With your help I found the "fix geometries" tool (@moet1972: Sorry I took the wrong tool "Geometrien prüfen" yesterday). After this fix I can work with this shape-file now.

And I think there must be something wrong (or could be better) with the provided GML-files. With all that information after analysing the data together I feel prepared to inform the german state-provider.

Many thanks Giovanni for your patience, knowledge and help!
Rolf

**Comment by saberraz** [comment]
In an ideal world, we should offer better tools in QGIS to support 3D vector data. There is a guide here:
https://3d.bk.tudelft.nl/svitalis/citygml/gdal/2017/07/25/messing-around-with-citygml-on-gdal-2.2.html

And various tools and scripts. But having a native tool in QGIS to handle CityGML would be great.

**Comment by gioman** [comment]
> But having a native tool in QGIS to handle CityGML would be great.

amen, but add "INSPIRE" to it too, is the same confusing stuff.

**Comment by gioman** [comment]
https://opengeospatialdata.springeropen.com/articles/10.1186/s40965-020-0074-y

there is a part of the article about citygml.

**Comment by StefanCiesilski** [comment]
@RolfBerlin 
I converting LoD1 to GPKG with ogr2ogr, but I can't see any geometry.

**Comment by imkeines** [comment]
2024 now, with QGIS Firenze. I used ogr2ogr and can also not see the geometry (even though the feature count is correct).
