### ISSUE TITLE
Possible bug: QgsProject.instance() not re-initialized when 2nd project opened?

### ISSUE THREAD

**Issue by Houska1** [qgis/QGIS#34180]
(Pardon any cluelessness - I used to be a developer decades ago, but now merely dabble.)

I have Project A with macros:
```python
from qgis.core import QgsProject
from qgis.utils import iface

def openProject():
    def layersToTopHandler( layers ):
        pass 
        # There's code here to move added layers to top of custom layer order. Removed, not germane to issue.
    QgsProject.instance().legendLayersAdded.connect( layersToTopHandler )

def saveProject():
    pass

def closeProject():
    QgsProject.instance().legendLayersAdded.disconnect()
 ```

Up to 3.8, this worked. Now, in 3.10.2, if I open *another* project (e.g. existing Project B) after this one, without restarting QGIS in between, I am unable to add any layers (https://github.com/qgis/QGIS/issues/34160 - closed in favour of this one). The cause seems to be that the `disconnect()` in my `closeProject()` clobbers not only my own signal handler but also another slot QGIS is (now?) using. And it stays clobbered even after Project B is loaded.

Now it's crappy coding on my part to `disconnect()` *all* slots on the signal, not just my own. But, on further consideration, shouldn't QGIS re-initialize `QgsProject.instance()` completely whenever it opens a project, so that it would all be moot? Are there other, potentially more damaging elements of Project A's `QgsProject.instance()` that Project B is inheriting, if QGIS is not shut down and restarted in between?

Just rap my knuckles and close this issue if I should just fix my macro. I'm raising this here more so someone checks there's not some bigger bug that has been introduced into project opening.

**Comment by gioman** [comment]
@Houska1 if this is a question you should make it in the users or developers mailing lists. If it turns out to be a bug then file a ticket here.

**Comment by Houska1** [comment]
@gioman, OK will do. On another project I'm in, the attitude is "if it's a potential bug, open an issue and it will be evaluated, closed if determined not to be one, or once fixed. Don't clutter up the mailing list, which is for news and discussions, with specific issues which will just scroll by". But I see your point, esp. in a pre-3.12 bug sprint, and will do so next week.

**Comment by roya0045** [comment]
Do you even need to disconnect when closing the project? I assume that if you do nothing it should be fine?

**Comment by m-kuhn** [comment]
Calling `disconnect()` on a core signal is dangerous. It will disconnect everything and is almost guaranteed to break core stuff and other plugins.

Keep a copy of the connection that is returned by the call to `connect()` and use it as parameter when disconnecting.
