### ISSUE TITLE
XYZ tiles do not load in certain CRS's 

### ISSUE THREAD

**Issue by baswein** [qgis/QGIS#34183]
**Description**

In QGIS 3.10.2 XYZ maps from the Quickmap Services and Open Street Maps XYZ tiles are not visible when working with certain CRS's. These CRS's loaded fine in 3.8. I am not sure if they where also not loading in QGIS 3.10.1. I have tried this on multiple computers with a clean profile. 
**How to Reproduce**
Open up QGIS and load Open Street Map from the XYZ tiles section of the browser. Zoom to Massachusetts USA and change the project CRS to 102686 (NAD_1983_StatePlane_Massachusetts_Mainland_FIPS_2001_Feet). The base-map disappears. 
This will also happen with 102716 (NAD_1983_StatePlane_New_York_Central_FIPS_3102_Feet) but not 103070 (NAD_1983_2011_StatePlane_Massachusetts_Mainland_FIPS_2001) or 3586 (NAD83(NSRS2007) / Massachusetts Mainland (ftUS))

**QGIS and OS versions**

QGIS version
3.10.2-A Coruña
QGIS code revision
d4cd3cfe5a
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.3
Running against GDAL/OGR
3.0.3
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.0
Running against PROJ
Rel. 6.3.0, January 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
db_manager; 
MetaSearch; 
processing

**Additional context**

**Comment by gioman** [comment]
@baswein cannot confirm here

![Peek 2020-02-01 10-47](https://user-images.githubusercontent.com/1951107/73590936-6ff65880-44e0-11ea-972a-7afb8f1532c2.gif)

**Comment by baswein** [comment]
Thanks for testing it out. Can always count you to triage these things!  The only difference I see is that you choose a transformation other then the top one. Here is a GIF of me doing the same thing using the first transformation. 
![qgi_xyz_switch-back](https://user-images.githubusercontent.com/15817745/73592812-3b78a180-44cc-11ea-9b94-6d018f4e8a60.gif)

But if I use the second transformation option the first time it doesn't show however if I switch back to 3857 and then back to 102686 it does show. 
![qgis_xyz_1](https://user-images.githubusercontent.com/15817745/73592802-11bf7a80-44cc-11ea-9603-750782a348d4.gif)

Because I do not fully understand the transformation process I always go with the first one.

**Comment by gioman** [comment]
@baswein seems to me is the very same case as described here: https://github.com/qgis/QGIS/issues/33929#issuecomment-576516324

**Comment by baswein** [comment]
Thanks- It does seem to be a transformation issue. Here is some more evidence using the "world" map. With the world map it leaves weird shapes. 
![QGIS_transform_world](https://user-images.githubusercontent.com/15817745/73610046-74cf1100-45a1-11ea-98ef-ed65e9613294.gif)

**Comment by baswein** [comment]
I just tried exporting a clipped 3857 geotif of the ma OSM (stylized in gray-scale to show the difference) and adding that and it did not have the same issues. 
![qgis_clip_xyz](https://user-images.githubusercontent.com/15817745/73610291-b5c82500-45a3-11ea-94f7-08ef1aa9034b.gif)

**Comment by gioman** [comment]
@baswein 

> I just tried exporting a clipped 3857 geotif of the ma OSM (stylized in gray-scale to show the difference) and adding that and it did not have the same issues.

if you read https://github.com/qgis/QGIS/issues/33929 you will see that this was already reported an already got an explanation:

transformations with NTV2 grids have a very strict geographic area/extent where they work. If the layer you want to reproject has a much larger extent then the grid will fail to do so. This was always the case but now is more evident because the new implementation for BTV2 grids makes much easier to use them, so more users hit this problem. The real issue (actually a feature request) here is that QGIS should be able to catch this scenarios and revert to a fallback transformation that do not rely on methods/parameters that are not able to reproject some layer. Closing as duplicate.
