### ISSUE TITLE
dbmanager python error when trying import a layer from a project containing embedded layers

### ISSUE THREAD

**Issue by cxc61cxc** [qgis/QGIS#34198]
i have a project with embedded layers, some of these layers are in postgis others in gpkg.
When I try to load a shp file in db manager the error occurs.
if I delete the links to the embedded layers coming from postgis the error is not there. While the links from gpkg seem not to affect. thank you

2020-02-02T17:25:12     WARNING    Traceback (most recent call last):
              File "/usr/share/qgis/python/plugins/db_manager/db_manager.py", line 169, in importActionSlot
              dlg = DlgImportVector(None, db, outUri, self)
              File "/usr/share/qgis/python/plugins/db_manager/dlg_import_vector.py", line 69, in __init__
              self.populateLayers()
              File "/usr/share/qgis/python/plugins/db_manager/dlg_import_vector.py", line 136, in populateLayers
              if layer.type() == QgsMapLayerType.VectorLayer:
             AttributeError: 'NoneType' object has no attribute 'type'

video :https://drive.google.com/open?id=1CmN3u-Bku3y5JPg3X9njxLAPt5MyjY92

**Comment by gioman** [comment]
@cxc61cxc I cannot confirm on QGIS master, can you please give it a try?

Also remember to add QGIS versoin you are using, and platform. Thanks.

**Comment by cxc61cxc** [comment]
Versione di QGIS | 3.10.2-A Coruña | Revisione codice QGIS | 616ad4531b
-- | -- | -- | --
Compilato con Qt | 5.9.5 | Esecuzione con Qt | 5.9.5
Compilato con GDAL/OGR | 2.2.3 | Esecuzione con GDAL/OGR | 2.2.3
Compilato con GEOS | 3.6.2-CAPI-1.10.2 | Esecuzione con GEOS | 3.6.2-CAPI-1.10.2 4d2925d6
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
Versione client PostgreSQL | 10.10 (Ubuntu 10.10-0ubuntu0.18.04.1) | Versione SpatiaLite | 4.3.0a
Versione QWT | 6.1.3 | Versione QScintilla2 | 2.10.2
Versione PROJ.4 | 493
OS Version | Ubuntu 18.04.4 LTS
Active python plugins | qconsolidate3; mmqgis; changeDataSource; AnimateOsm; searchlayers; QuickOSM; timemanager; QPackage; quick_map_services; go2mapillary; Cxf_in; Qgis2threejs; GroupStats; MetaSearch; processing; db_manager; ImportPhotos

**Comment by gioman** [comment]
> Active python plugins 	qconsolidate3; mmqgis; changeDataSource; AnimateOsm; searchlayers; QuickOSM; timemanager; QPackage; quick_map_services; go2mapillary; Cxf_in; Qgis2threejs; GroupStats; MetaSearch; processing; db_manager; ImportPhotos

@cxc61cxc if problems persist also on master, please also try with a new QGIS profile, no 3rd party plugins installed.

**Comment by gioman** [comment]
@cxc61cxc still can't replicate on the latest master/3.13. Please reopen if necessary.
