### ISSUE TITLE
qgis crash

### ISSUE THREAD

**Issue by Elia1959** [qgis/QGIS#34197]
Crash ID: f53c022538b98c179981f3efb9b4894a728a297a

Stack Trace

QCoreApplication::postEvent :
::operator() qgsgeonoderequest.cpp:68
QMetaObject::activate :
QgsGeoNodeRequest::replyFinished qgsgeonoderequest.cpp:258
QMetaObject::activate :
QSslKey::operator!= :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
QEventLoop::exec :
QgsGeoNodeRequest::fetchLayersBlocking qgsgeonoderequest.cpp:85
QgsGeoNodeRequest::fetchServiceUrlsBlocking qgsgeonoderequest.cpp:430
QgsGeoNodeConnectionItem::createChildren qgsgeonodedataitems.cpp:39
QgsDataItem::runCreateChildren qgsdataitem.cpp:284
QtConcurrent::StoredFunctorCall1,QVector (__cdecl*)(QgsDataItem * __ptr64),QgsDataItem * __ptr64>::runFunctor qtconcurrentstoredfunctioncall.h:422
QtConcurrent::RunFunctionTask >::run qtconcurrentrunbase.h:108
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.10.2-A Coru�a
QGIS code revision: d4cd3cfe5a
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.3
Running against GDAL: 3.0.3

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7600

**Comment by gioman** [comment]
@Elia1959 please add detailed steps to replicate.

Try a new QGIS profile (no 3rd party plugins installed). if the problem persist attach a sample project + data.

**Comment by Elia1959** [comment]
ok ... very good ...

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.

**Comment by ohmh** [comment]
This happens to me too, it is a matter of time even if no project is running.
I noticed the crash id is different
"fba877d9ec130ea2641944befd14f2f6f996da0c"

It started with me when I installed a new version 3.14, then when I downgraded to 3.10.10 it did not fix it

**Comment by ohmh** [comment]
And Yeah starting a new clean profile fixes it; at least for me
