### ISSUE TITLE
DB Manager: "is an invalid layer - not loaded" when double clicking on virtual layer

### ISSUE THREAD

**Issue by AndrewAnnex** [qgis/QGIS#34191]
Checklist before submitting

- [✔️] Search through existing issue reports and gis.stackexchange.com to check whether the issue already exists
- [✔️] Test with a [clean new user profile](https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html?highlight=profile#working-with-user-profiles).
- [✔️] Create a light and self-contained sample dataset and project file which demonstrates the issue

**Describe the bug**

db_manager does not seem to want to import any project layers via the interface and does not give a clear explanation. eventualy I found this error after clicking a few things I forget that could explain the issue:
```
Error 9
Provider virtual has no createEmptyLayer method
```
**How to Reproduce**
example file page: https://hub.arcgis.com/datasets/a21fdb46d23e4ef896f31475217cbb08_1
1. download https://opendata.arcgis.com/datasets/a21fdb46d23e4ef896f31475217cbb08_1.zip
2. load file into new qgis project
3. open DB Manager 
4. double click the layer from the project layers

**QGIS and OS versions**

QGIS version | 3.10.0-A Coruña | QGIS code revision | 6c816b4204
-- | -- | -- | --
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.28.0 | Running against SQLite | 3.28.0
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS 10.15
Active python plugins | profiletool; contour; Discovery; qgSurf; qgis3marstools; QuickWKT; searchlayers; autoSaver; processing; db_manager; catalogpl_plugin; mmqgis; pointsamplingtool; Qgis2threejs; shapetools

**Additional context**

eventually I figured out I could import the layer using the db_manager new connection option, but it should work this other way as well

**Comment by gioman** [comment]
Confirmed also on 3.10.2 and 3.4.15.

**Comment by i-s-o** [comment]
Also confirmed on QGIS 2.18! :)

I guess this action was *not in the feature set* because the virtual layers were designed to be used in queries, and not simply added back as new layers (for that we have *Duplicate Layer* right-click action in the Layers Panel).

For UX consistency, I think it is better to link the double-click action on the layer name in Virtual Layers tree to the Duplicate Layer right-click action of the Layers Panel.

**Comment by AndrewAnnex** [comment]
Okay good to know,

This might be a feature request but is there a way to have a sql REPL panel in QGIS? I want to quickly iterate with developing sql queries and see the results on the main canvas (provided the geometry is included in the result I suppose). I think this is the intended use of the DB manager but I recall that the map preview is another panel in the manager and the sql command panel is not simultaneously visible. Also there was some flag I had to enable to use the spatial queries on geopackage files that was hard to find documentation for (I am away from my computer so I am not linking it here). Are there cases for users who would not want that feature enabled by default?

-Andrew Annex

**Comment by gioman** [comment]
> This might be a feature request but is there a way to have a sql REPL panel in QGIS? I want to quickly iterate with developing sql queries and see the results on the main canvas (provided the geometry is included in the result I suppose).

@AndrewAnnex 

just open the SQL panel in DB Manager, then run an arbitrary SQL query. You have an option (a checkbox) to load the (SELECT) result as layer  > you will be asked to select a column with a unique ID and the geometry column.
