### ISSUE TITLE
QGis Crash

### ISSUE THREAD

**Issue by rafaaaltamiranda** [qgis/QGIS#34195]
Crash ID: f74f6418021ce0696dbcc0141a62af7efdbf27a7

Stack Trace

QGraphicsScene::wheelEvent :
QGraphicsScene::wheelEvent :
QGraphicsScene::wheelEvent :
QGraphicsScene::wheelEvent :
QGraphicsScene::wheelEvent :
QGraphicsScene::wheelEvent :
QGraphicsScene::wheelEvent :
QGraphicsScene::drawItems :
QGraphicsView::paintEvent :
QgsLayoutView::paintEvent qgslayoutview.cpp:1147
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:373
QCoreApplication::notifyInternal2 :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QApplication::windowIcon :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:373
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1542
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.4.14-Madeira
QGIS code revision: c92881c294
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.3
Running against GDAL: 2.4.3

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by gioman** [comment]
@rafaaaltamiranda 



>  QGIS Version: 3.4.14-Madeira

upgrade to 3.4.15 or 3.10.2

test with a new QGIS profile (no 3rd party plugins installed)

if the problem persist please add detailed steps (and sample project + data) about how replicate the problem.

**Comment by gioman** [comment]
@rafaaaltamiranda also please edit the title with a more descriptive one.

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
