### ISSUE TITLE
EPSG code of CRS not recognized

### ISSUE THREAD

**Issue by kerkovits** [qgis/QGIS#34213]
**Describe the bug**
QGIS does not recognize the EPSG code of coordinate systems.

**How to Reproduce**

1. Reproject any vector layer to EPSG:23700
2. Save it to a GeoPackage
3. Create a new, empty project
4. Load the layer from the GeoPackage
5. Open Layer properties -> Source

**What should happen?**

The layer properties should show that the CRS is EPSG:23700

**What happens instead?**

A generated CRS is shown with the WKT string. The unit of the CRS is also unknown e. g. in the Buffer geoprocessing tool.

**QGIS and OS versions**

QGIS verzió | 3.10.2-A Coruña | QGIS kód változat | 616ad4531b
-- | -- | -- | --
Qt-val fordítva | 5.11.2 | Qt-val futtatva | 5.11.2
GDAL/OGR-rel fordítva | 3.0.2 | GDAL/OGR-rel futtatva | 3.0.2
GEOS-szal fordítva | 3.8.0-CAPI-1.13.1 | GEOS-szal futtatva | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL kliens verzió | 11.5 | SpatiaLite verzió | 4.3.0
OWT verzió | 6.1.3 | QScintilla2 Verzió | 2.10.8
PROJ-al fordítva | 6.2.1 | PROJ-al futtatva | Rel. 6.2.1, November 1st, 2019
OS verzió | Windows 10 (10.0)
Active python plugins | db_manager; MetaSearch; processing

**Comment by gioman** [comment]
@kerkovits I cannot confirm here (3.10.2 on Windows)



> Reproject any vector layer to EPSG:23700

how you did this step? what CRS had your original data?

**Comment by kerkovits** [comment]
WGS84 (EPSG:4326)

**Comment by kerkovits** [comment]
Reprojection was done at the Change CRS geoprocessing tool and the result was stored as a temp layer. It was saves using right click->Export->Save features as…

**Comment by gioman** [comment]
> Reprojection was done at the Change CRS geoprocessing tool and the result was stored as a temp layer. It was saved using right click->Export->Save features as…

 @kerkovits cannot replicate here.

**Comment by nyalldawson** [comment]
I can't reproduce -- can you clarify exactly which processing tool was used?

**Comment by nirvn** [comment]
@kerkovits , looking at your QGIS and OS versions details, I noticed you were running the flawed initial 3.10.2 release. QGIS re-released that version with updated gdal and proj packages. 

Step 0: re-download 3.10.2's installation package to make sure you are running against gdal 3.0.3 and proj 6.3.0
Step 1: check if your issue is gone :)

**Comment by kerkovits** [comment]
I redownloaded QGIS. It became even worse.

1. I opened the attached termved.shp. It is in webMercator.
2. Right-click -> Export -> Save features as: I set the CRS to EPSG:23700
3. I save it to a new geopackage (this is attached, too)
4. New, empty project
5. Open the layer from the GeoPackage
6. QGIS assumes that the CRS is EPSG:4326

[a.zip](https://github.com/qgis/QGIS/files/4151923/a.zip)

**Comment by kerkovits** [comment]
P.S.
I analyzed the geopackage saved by QGIS. In gpkg_geometry_columns the srs_id is 0. In gpkg_spatial_ref_sys there is no mention of EPSG:23700. Nevertheless, the older build with proj 6.2.1 saved the geopackage well, and the old geopackages created with that build open correctly…

**Comment by nirvn** [comment]
@kerkovits , I can't reproduce here. See the spatial ref table of the geopackage file:
![Screenshot from 2020-02-04 14-54-57](https://user-images.githubusercontent.com/1728657/73724645-5f531600-475e-11ea-821f-45294f28c07b.png)

Can you try to re-do the steps above with a new QGIS user profile? Use the settings -> user profiles -> new profile... menu item to create a new profile. It might have to do with the pre-existing srs.db in your current user profile directory.

**Comment by kerkovits** [comment]
Thank you it solved. I have already tried to use a new profile with the old build, but that did not help, therefore I reverted. Now it works as expected.
