### ISSUE TITLE
Unable to run GDAL python scripts from OSGeo4W Shell

### ISSUE THREAD

**Issue by miet-t** [qgis/QGIS#34214]
**Describe the bug**

I'm unable to run GDAL python scripts (i.e. gdal_calc or gdal_edit) from OSGeo4W Shell just by typing script name (like other commands from Shell, i.e. gdal_translate). That was standard behaviour for QGIS with GDAL versions lower than 3.
Now need to enter full path to pyhon.exe followed by script path and file name, i.e.:
"%OSGEO4W_ROOT%\apps\Python37\python.exe" "%OSGEO4W_ROOT%\apps\Python37\Scripts\gdal_calc.py"
There are missing *.bat files that existed in QGIS 3.x\bin folder in versions with GDAL 2.x:
gdal2tiles.bat
gdal2xyz.bat
gdalchksum.bat
gdalcompare.bat
gdalident.bat
gdalimport.bat
gdalmove.bat
gdal_auth.bat
gdal_calc.bat
gdal_edit.bat
gdal_fillnodata.bat
gdal_merge.bat
gdal_pansharpen.bat
gdal_polygonize.bat
gdal_proximity.bat
gdal_retile.bat
gdal_sieve.bat

**How to Reproduce**

**QGIS and OS versions**

 QGIS 3.10.2 64 bit
 QGIS 3.4.15 64 bit
Windows 10, 64 bit

**Additional context**

**Comment by alexbruy** [comment]
This should be reported in the OSGeo4W bugtracker at https://trac.osgeo.org/osgeo4w

**Comment by gioman** [comment]
> This should be reported in the OSGeo4W bugtracker at https://trac.osgeo.org/osgeo4w

correct. By the way, the problem seems to be that "gdal-python" does not seems to be set as a dependency for "qgis" on osgeo4w.
