### ISSUE TITLE
QgsHighlight not clearing

### ISSUE THREAD

**Issue by oznerol2** [qgis/QGIS#34228]
QgsHighlight  cant be cleared even after disconected layer or empty layer referenced.

**Comment by gioman** [comment]
@oznerol2 is this a question or a bug report?

**Comment by grasdackel0815** [comment]
This happens to me on Win10 when I use setColor and setFillColor on the QgsHighlight. 
I can remove when I only use setFillColor with workaround:
my_highlight.setFillColor(QColor(0, 0, 0, 0))
my_highlight = None

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
