### ISSUE TITLE
Qgis issues a error incomplete when run a python function

### ISSUE THREAD

**Issue by kylefelipe** [qgis/QGIS#34229]
**Describe the bug**

My intent is upload some pictures to a table, and then, use project relations to join the image to some vectors.
I made a custom form and a table (without geometry) with a BLOB Field to upload some images.
Then i made a python function that will show the image in a QLabel to 
 
When i open the attribute table, qgis issues the error as follow:

![image](https://user-images.githubusercontent.com/24795382/73676848-de2f4c80-4693-11ea-9a64-4dcb923cc281.png)

**How to Reproduce**

Steps

    Make a table with fiels "fid" - integer , "foto" - BLOB and "id_especie".
    Insert 2 images to the layer.
    Make a custom form with a Text Edit and a label ('exfoto')
    Load this to the layer as a custom form.
    Create a python function that will show the image in the label.
    Open attribute table

**QGIS and OS versions**
3.10.2 A Coruña
Debian Buster

**Additional context**

Code:

```Python 
# -*- coding: utf-8 -*-
from qgis.PyQt.QtCore import Qt
from qgis.PyQt.QtWidgets import QLabel, QTextEdit
from qgis.PyQt.QtGui import QPixmap, QImage

myDialog = None

def my_form_open(dialog, layer, feature):
    label = dialog.findChild(QLabel, "exfoto")
    h = label.height()
    w = label.width()
    qmg = QImage.fromData(feature['foto'])
    img = QPixmap.fromImage(qmg)
    label.setPixmap(img.scaled(w, h, Qt.KeepAspectRatio))
```
A zip with a project and samples to test
[example.zip](https://github.com/qgis/QGIS/files/4149444/example.zip)

**Comment by 3nids** [comment]
the project you provided cannot be open.
more generally, this doesn't like a bug but rather a Python error or mismatch configuration with your UI file.

**Comment by espinafre** [comment]
Looks like the same symptom as in #34370 and #31235 ; your function might have an error, but QGIS is unable to show it. Hopefully PR #34380 will fix this.
