### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by FlyingEagle** [qgis/QGIS#34235]
## User Feedback

Add or Edit Points on a Point-Layer by Dialog, closing the dialog or saving directly after closing the dialog.
It happens very often.

## Report Details

**Crash ID**: [abd09e333ec25c9005349e301c404f602702b43d]('https://github.com/qgis/QGIS/search?q=abd09e333ec25c9005349e301c404f602702b43d&type=Issues')

**Stack Trace**
<pre>
QMetaObject::cast :
QgsAttributeForm::updateDefaultValues qgsattributeform.cpp:494
QgsAttributeForm::onAttributeChanged qgsattributeform.cpp:881
QMetaObject::activate :
QgsEditorWidgetWrapper::valuesChanged moc_qgseditorwidgetwrapper.cpp:260
QgsDateTimeEditWrapper::dateTimeChanged qgsdatetimeeditwrapper.cpp:130
QMetaObject::activate :
QgsDateTimeEdit::valueChanged moc_qgsdatetimeedit.cpp:179
QMetaObject::activate :
QDateTimeEdit::displayedSections :
QAbstractSpinBox::setSpecialValueText :
QDateTimeEdit::setDateTime :
QgsDateTimeEdit::setDateTime qgsdatetimeedit.cpp:282
QgsDateTimeEditWrapper::updateValues qgsdatetimeeditwrapper.cpp:247
QgsEditorWidgetWrapper::setFeature qgseditorwidgetwrapper.cpp:76
QgsAttributeForm::resetValues qgsattributeform.cpp:765
QMetaObject::activate :
QgsVectorLayer::commitChanges qgsvectorlayer.cpp:3111
QgisApp::saveActiveLayerEdits qgisapp.cpp:9845
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1598
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.2-A Coru�a
QGIS code revision: d4cd3cfe5a
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.3
Running against GDAL: 3.0.3

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment]
@FlyingEagle please try with a new QGIS profile, no 3rd party plugins installed.

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
