### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by FlyingEagle** [qgis/QGIS#34236]
Konnte Erweiterung 'QRectangleCreator' nicht laden aufgrund eines Fehlers beim Aufruf der classFactory() Methode 

ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden. 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/%USERNAME%/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QRectangleCreator\__init__.py", line 27, in classFactory
    from .QRectangleCreator import QRectangleCreator
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/%USERNAME%/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QRectangleCreator\QRectangleCreator.py", line 37, in 
    from pyproj import Proj, transform
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\pyproj\__init__.py", line 70, in 
    from pyproj import _datadir
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.

Python-Version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS-Version: 3.10.2-A Coruña A Coruña, d4cd3cfe5a 

Python-Pfad:
C:/OSGEO4~1/apps/qgis/./python
C:/Users/%USERNAME%/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/%USERNAME%/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGEO4~1/apps/qgis/./python/plugins
C:\OSGEO4~1\apps\Python37
C:\OSGEO4~1\apps\Python37\Scripts
C:\OSGeo4W64\bin\python37.zip
C:\OSGEO4~1\apps\Python37\DLLs
C:\OSGEO4~1\apps\Python37\lib
C:\OSGeo4W64\bin
C:\OSGEO4~1\apps\Python37\lib\site-packages
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32\lib
C:\OSGEO4~1\apps\Python37\lib\site-packages\Pythonwin
C:/Users/%USERNAME%/AppData/Roaming/QGIS/QGIS3\profiles\default/python
D:\eclipse\plugins\org.python.pydev.core_7.0.3.201811082356\pysrc
C:\Users\%USERNAME%\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms
.
C:/Users/%USERNAME%/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web
C:\Users\%USERNAME%\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
C:\Users\%USERNAME%\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\shapetools\ext-libs

**Comment by gioman** [comment]
> File "C:/Users/%USERNAME%/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QRectangleCreator\QRectangleCreator.py", line 37, in

this error comes from a 3rd party plugins, you must report it to the plugin autor/s.
