### ISSUE TITLE
Crash when changing datasource

### ISSUE THREAD

**Issue by jmacura** [qgis/QGIS#34231]
## User Feedback

I was changing a datasource for one layer for which I moved the source (GeoTIFF file) into another directory.
It took some time loading it, so I left QGIS running but switched my focus to a browser window for some time. After several minutes I wanted to check if the layer already reloaded the datasource, but instead I have seen this pretty crash window...

## Report Details

**Crash ID**: [b895f2e972085ce69e79887e6109a2117e415761]('https://github.com/qgis/QGIS/search?q=b895f2e972085ce69e79887e6109a2117e415761&type=Issues')

**Stack Trace**
<pre>
<lambda_955db2f13493070010946a286f1d09a1>::operator() qgisapp.cpp:7393
QgisApp::changeDataSource qgisapp.cpp:7451
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QMenu::exec :
QgsLayerTreeView::contextMenuEvent qgslayertreeview.cpp:152
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1598
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.2-A Coruna
QGIS code revision: d4cd3cfe5a
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.3
Running against GDAL: 3.0.3

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by jmacura** [comment]
Just tested the same with empty user profile. Crashed again (I didn't even left QGIS as previously, just let it running in the front) after some 20 seconds.

## User Feedback
--

## Report Details

**Crash ID**: [b895f2e972085ce69e79887e6109a2117e415761]('https://github.com/qgis/QGIS/search?q=b895f2e972085ce69e79887e6109a2117e415761&type=Issues')


**Stack Trace**
<pre>
<lambda_955db2f13493070010946a286f1d09a1>::operator() qgisapp.cpp:7393
QgisApp::changeDataSource qgisapp.cpp:7451
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QMenu::exec :
QgsLayerTreeView::contextMenuEvent qgslayertreeview.cpp:152
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1598
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>


**QGIS Info**
QGIS Version: 3.10.2-A Coruna
QGIS code revision: d4cd3cfe5a
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.3
Running against GDAL: 3.0.3



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment]
> I was changing a datasource for one layer for which I moved the source (GeoTIFF file) into another directory.

@jmacura can you describe in detail the steps to replicate? thanks.

**Comment by jmacura** [comment]
@gioman sure!

# Steps to reproduce
1. Open new project
2. Load GeoTIFF as a new raster layer
3. Save project
4. Quit QGIS
5. Go to your file system, move the .tiff file somewhere else
6. Open QGIS and reopen the project
7. The .tiff file won't be found (logically), hence the prompt dialog appears
![image](https://user-images.githubusercontent.com/5598693/73692287-5453a380-46d4-11ea-9326-2e13907ed1cd.png)
8. In the prompt select option "Keep Unavailable Layers"
9. Right click on the layer, choose "Change Data Source...." (it's in Czech in the image as it's a default language in an empty profile)
![image](https://user-images.githubusercontent.com/5598693/73692464-a98fb500-46d4-11ea-93a0-7ee12f1f1d47.png)
10. Find the new location of the file, click "OK", wait for the crash to happen


Is this sufficient? I can attach testing .qgz and testing .tiff files if needed.

**Comment by jmacura** [comment]
And one more comment:
In step no. 7, if I choose "Browse" in the prompt dialog and relink the file from there, it works just fine.

**Comment by gioman** [comment]
Confirmed also here.
