### ISSUE TITLE
layer with a CRS without EPSG code not shown 

### ISSUE THREAD

**Issue by metzm** [qgis/QGIS#34240]
**Describe the bug**
This is with QGIS 3.10.2, GDAL 3.0.4, PROJ 6.3.0. The QGIS project uses EPSG:4326. Trying to insert a layer with a CRS without EPSG code
```
PROJCRS["NW Africa Grid",
    BASEGEOGCRS["NTF",
        DATUM["Nouvelle Triangulation Francaise",
            ELLIPSOID["Clarke 1880 (IGN)",6378249.2,293.466021293627,
                LENGTHUNIT["metre",1]],
            ID["EPSG",6275]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["Degree",0.0174532925199433]]],
    CONVERSION["unnamed",
        METHOD["Lambert Conic Conformal (1SP)",
            ID["EPSG",9801]],
        PARAMETER["Latitude of natural origin",34,
            ANGLEUNIT["Degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",0,
            ANGLEUNIT["Degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9994,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",1000000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",500000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]]]
```
this layer is not displayed. In Project -> Properties -> CRS, enabling or disabling the button "No projection (...)" has no effect. GDAL 3.0.4 and PROJ 6.3.0 readily recognize this CRS.

Adding this CRS to QGIS as custom projection via Settings -> Custom Projections works in the test, the CRS is considered valid and the test is passed, but it is not possible because, despite a new name for this custom CRS, QGIS 3.10.2 attempts to overwrite the first entry in the list of custom properties:
```
Cannot save ' * Generated CRS (+proj=longlat +ellps=andrae +no_defs)' — this Proj string definition is identical to :.

Try changing the CRS definition to a WKT format instead.
```
The new CRS definition is indeed in WKT format.

There are also lots of (27) Exceptions coming from PROJ: `proj_create_from_database: crs not found`. I would be surprised if this or any other CRS without a spatial reference id can be found in the database of PROJ. 

**How to Reproduce**
Use any datasource located in Algeria, Tunisia, Libya, use GDAL/OGR to reproject it to the above CRS, try to display it in a QGIS project using EPSG:4326 as default.

**QGIS and OS versions**

QGIS version | 3.10.2-A Coruña | QGIS code branch | Release QGIS code branch.3
-- | -- | -- | --
Compiled against Qt | 5.12.5 | Running against Qt | 5.12.5
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.26.0 | Running against SQLite | 3.26.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.0 | Running against PROJ | Rel. 6.3.0, January 1st, 2020
OS Version | Fedora 30 (Thirty)
Active python plugins | plugin_reloader; pluginbuilder3; db_manager; processing; MetaSearch

**Comment by gioman** [comment]
@metzm please attach sample data.

**Comment by metzm** [comment]
Sample data: a simple rectangular polygon with extents in WGS 84
west=4.6859299999999999
south=32.3472999999999971
east=13.1209000000000007
north=37.6679999999999993

which needs to the reprojected to the mentioned CRS with ogr2ogr 

or in the mentioned CRS:
west=1413905.66991158 
south=326879.21817598
east=2231574.35163749
north=981138.89659334

as attached

[nw_africa_grid.gpkg.zip](https://github.com/qgis/QGIS/files/4150662/nw_africa_grid.gpkg.zip)

**Comment by nyalldawson** [comment]
My findings:

>  GDAL 3.0.4 and PROJ 6.3.0 readily recognize this CRS.

They accept it, but they don't recognise it as standard CRS (just like how QGIS displays it as a custom CRS)

> nw_africa_grid.gpkg.zip

(on a master build) the attached data displays ok for me with a project in either the same CRS as the layer, or EPSG:4326. Could you re-test on a nightly build and see if this has been fixed since the 3.10.2 release?


> Adding this CRS to QGIS as custom projection via Settings -> Custom Projections works in the test, the CRS is considered valid and the test is passed, but it is not possible because, despite a new name for this custom CRS, QGIS 3.10.2 attempts to overwrite the first entry in the list of custom properties:

I can't reproduce this -- can you post steps to reproduce?

**Comment by metzm** [comment]
> > Adding this CRS to QGIS as custom projection via Settings -> Custom Projections works in the test, the CRS is considered valid and the test is passed, but it is not possible because, despite a new name for this custom CRS, QGIS 3.10.2 attempts to overwrite the first entry in the list of custom properties:
> 
> I can't reproduce this -- can you post steps to reproduce?

Go to Settings -> Custom Projections...
To the right top of the list with custom CRS's, there is a button with a plus sign "Add new CRS", click it.
Change the name from "New CRS" to something else, e.g. "NW Africa Grid".
Select "WKT (Recommended)" as format.
Insert WKT in the parameters field, click "Validate": "This WKT projection definition is valid", click ok.
Test with e.g. North = 33, East = 13, test is passed.
The new custom CRS appears as last entry in the list of custom CRS's. Looks all fine, but clicking ok gives me
```
Cannot save ' * Generated CRS (+proj=longlat +ellps=andrae +no_defs)' — this Proj string definition is identical to :.

Try changing the CRS definition to a WKT format instead.
```

**Comment by nirvn** [comment]
@metzm , PR #34258 will fix your issue.

**Comment by metzm** [comment]
@nirvn Great, thanks for the quick fix!

**Comment by metzm** [comment]
> My findings:
> 
> > GDAL 3.0.4 and PROJ 6.3.0 readily recognize this CRS.
> 
> They accept it, but they don't recognise it as standard CRS (just like how QGIS displays it as a custom CRS)

What exactly do you mean with "standard CRS"? A CRS in the PROJ database? Otherwise, a Lambert Conic Conformal projection with NTF datum and Clarke 1880 ellipsoid seems pretty much standard to me.
> 
> > nw_africa_grid.gpkg.zip
> 
> (on a master build) the attached data displays ok for me with a project in either the same CRS as the layer, or EPSG:4326. Could you re-test on a nightly build and see if this has been fixed since the 3.10.2 release?

I tested with QGÍS master, latest commit 0815ad487aac44a9cd506f6f470521005f27c347 (nirvn: Fix user projection not identified as such), but still can't display data with this CRS.

**Comment by nyalldawson** [comment]
> What exactly do you mean with "standard CRS"? A CRS in the PROJ database? Otherwise, a Lambert Conic Conformal projection with NTF datum and Clarke 1880 ellipsoid seems pretty much standard to me.

Just that it doesn't match any registered EPSG/ESRI/... entries from the database. You're 100% correct in that it's a valid CRS.

> I tested with QGÍS master, latest commit 0815ad4 (nirvn: Fix user projection not identified as such), but still can't display data with this CRS.

I can't explain that -- it works fine for me here.

**Comment by nirvn** [comment]
OK, let's break this down into parts.

1/ I can successfully save the WKT attached to this issue now

2/ I can successfully see the saved user projection used when inserting the nw_africa_grid.gpkg dataset (and the project set to that CRS)
![Screenshot from 2020-02-05 10-39-00](https://user-images.githubusercontent.com/1728657/73808793-bc54d780-4803-11ea-99c6-463cedf60bb2.png)

3/ now, if I choose the recommended transform (with an accuracy of 1 meter), I can't get the dataset to reproject properly onto a wgs84 or pseudomercator project CRS; I see the following warning in my log messages panel:
`2020-02-05T10:33:32     WARNING    Transform error caught: Could not transform bounding box to target CRS`

4/ however, if I pick the second transformation (with an accuracy of 2 meter), the dataset projects / reprojects just fine:
![Screenshot from 2020-02-05 10-42-44](https://user-images.githubusercontent.com/1728657/73808977-43a24b00-4804-11ea-9738-80663fa45905.png)

Proof of life:
![Screenshot from 2020-02-05 10-42-59](https://user-images.githubusercontent.com/1728657/73808984-4ac95900-4804-11ea-9639-2cad93121248.png)

**Comment by nirvn** [comment]
OK, so the 1-meter accuracy transformation relies on a grid file (ntf_r93.gsb) which, on Ubuntu, is shipped as part of the proj-data package. 

The issue is therefore very likely to fall within what @nyalldawson is trying to address in PR #34273 .

1-meter grid-based transform against a WGS84 world countries vector dataset:
![Screenshot from 2020-02-05 11-10-47](https://user-images.githubusercontent.com/1728657/73810356-de048d80-4808-11ea-93ab-e02026df8646.png)

vs 2-meter transform against the same world countries dataset:
![Screenshot from 2020-02-05 11-11-39](https://user-images.githubusercontent.com/1728657/73810385-ef4d9a00-4808-11ea-9bc7-45e2377711bf.png)

**Comment by metzm** [comment]
Thanks for digging into this problem, I got it working now. The problem was apparently that the grid file did not cover my area of interest.
When adding the vector to my QGIS project, I get a dialogue "Select Transformation for ...". QGIS could use the bbox of the layer to select suitable PROJ operations (proj_get_area_of_use()).
Works for me now, closing the issue.
