### ISSUE TITLE
Turned off layer is displayed in the composer

### ISSUE THREAD

**Issue by timondriy** [qgis/QGIS#34257]
I have theme where some layers are enabled, but group where it is 
situated is disabled. In composer if i use this theme thats layers are showing anyway.

On screenshot below disabeled layer in yellow cirkle and on map it isn't showing, but on composer its showing. Theme on map and on composer is same

![image](https://user-images.githubusercontent.com/41323447/73729166-9832c100-4745-11ea-9e76-ddadd80c9a58.png)

Версия QGIS
3.10.2-A Coruña
Ревизия
d4cd3cfe5a
Версия Qt при сборке
5.11.2
Текущая версия Qt
5.11.2
Версия GDAL/OGR при сборке
3.0.3
Текущая версия GDAL/OGR
3.0.3
Версия GEOS при сборке
3.8.0-CAPI-1.13.1
Текущая версия GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
Версия PostgreSQL
11.5
Версия SpatiaLite
4.3.0
Версия QWT
6.1.3
Версия QScintilla2
2.10.8
Compiled against PROJ
6.3.0
Running against PROJ
Rel. 6.3.0, January 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
Add_a_point_road_sign; 
autoSaver; 
FreehandRasterGeoreferencer; 
GeoCoding; 
mmqgis; 
nominatim; 
openlayers_plugin; 
ORStools; 
pdok_locatieserver_locator_filter; 
PeliasGeocoding; 
qconsolidate3; 
qtiles3; 
quick_map_services; 
raster_tracer; 
db_manager; 
MetaSearch; 
processing

**Comment by roya0045** [comment]
Composer uses active elements and does not care about groups or even single symbols. There are probably already bug reports that report similar issues.

**Comment by nyalldawson** [comment]
Confirmed issue

**Comment by nyalldawson** [comment]
Caused by https://github.com/qgis/QGIS/pull/33099
