### ISSUE TITLE
Digitization problems

### ISSUE THREAD

**Issue by kohlibri** [qgis/QGIS#34265]
We use a PostGIS database.
There we have a table with two different geometries, a point geometry and a geometry column in which polygons or multipolygons are stored.
In the next step, we also have a georeferenced raster layer and the area in the raster layer is to be digitized as a polygon or multipolygon.
Now I open the attribute table of the point layer, I look for the suitable data set and zoom in on the selected row. In the next step I toggle edining die Polygonlayer and I will add a part. I now digitize the georeferenced area and then I want to save the changes. 
But I can't save the changes because of this error message

Layer xxx: PostGIS error while changing geometry values: FEHLER: Unknown geometry type: 12 - MultiSurface.

In version 3.6.x, the digitized areas are still saved as polygons or multipolygons.

QGIS version | 3.10.1-A Coruña | QGIS code revision | ef24c526da
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.2 | Running against GDAL/OGR | 3.0.2
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.2.1 | Running against PROJ | Rel. 6.2.1, November 1st, 2019
OS Version | Windows 10 (10.0)
Active python plugins | DigitizingTools; qgisnetworklogger; vrtbuilderplugin; db_manager; MetaSearch; processing

**Comment by gioman** [comment]
@kohlibri can you add a dump of the table that gives you that error?

**Comment by kohlibri** [comment]
If I use a normal Postgres / PostGIS table and then digitize a geometry, the geometry is a multipolygon. But if I use a inherited table, the geometry type is a MultiSurface.

**Comment by gioman** [comment]
> If I use a normal Postgres / PostGIS table and then digitize a geometry, the geometry is a multipolygon.

@kohlibri this does not answer the previous request of attaching a dump of your table




> But if I use a inherited table, the geometry type is a MultiSurface.

what do you mean?

**Comment by kohlibri** [comment]
I can give you a dump of the table, the data is not for the public.
 have created two CREATE commands for you around the table structure so that you can understand the table structure.

CREATE TABLE mother
(
	id integer not null Default nextval(...),
	the_geom_point geometry,
	the_geom geometry,
	site integer,
	constraint mother_pkey PRIMARY KEY (id)
)

CREATE TABLE child
(
    -- Inherited from table mother: id integer NOT NULL DEFAULT nextval(...),
    -- Inherited from table mother: the_geom_point geometry,
    -- Inherited from table mother: the_geom geometry,
    -- Inherited from table mother: site integer,
    -- Inherited from table baulasten.all_baulastenarchiv: verpflichtungserklaerung_vom date,
	constraint child_pkey PRIMARY KEY (id)
	CONSTRAINT the_geom_point_valid CHECK (st_isvalid(the_geom_point)),
    CONSTRAINT the_geom_valid CHECK (st_isvalid(the_geom))
)
INHERITS (mother)

**Comment by gioman** [comment]
@kohlibri if I do this

CREATE TABLE mother
(
id serial not null,
the_geom_point geometry(MultiPoint,4326),
the_geom geometry(MultiPolygon,4326),
site integer,
constraint mother_pkey PRIMARY KEY (id)
)

CREATE TABLE child
(
-- Inherited from table mother: id integer NOT NULL DEFAULT nextval(...),
-- Inherited from table mother: the_geom_point geometry,
-- Inherited from table mother: the_geom geometry,
-- Inherited from table mother: site integer,
-- Inherited from table baulasten.all_baulastenarchiv: verpflichtungserklaerung_vom date,
constraint child_pkey PRIMARY KEY (id),
CONSTRAINT the_geom_point_valid CHECK (st_isvalid(the_geom_point)),
CONSTRAINT the_geom_valid CHECK (st_isvalid(the_geom))
)
INHERITS (mother)



I can edit the (point and polygon) child table without issues (also adding parts).

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
