### ISSUE TITLE
Is qbrowser gone?  ubuntu 18.04 on stable ppa

### ISSUE THREAD

**Issue by dazza-codes** [qgis/QGIS#34267]
Is qbrowser gone?  After adding ppa-stable, it went missing.

```
sudo add-apt-repository ppa:ubuntugis/ppa
sudo apt-get update
sudo apt-get upgrade
```

Installs QGIS 3.4 LTS.  Previously there was the QBrowser available for easy one-click navigation and view of data in the file system.  That's the easiest way to quickly view data without all the bells-n-whistles of using layers and projects.  After searching for more about it, there's no information and no app installed.

**Comment by Gustry** [comment]
Yes, it has been removed for QGIS 3 : https://gis.stackexchange.com/questions/312236/qgis-browser-for-version-3

**Comment by roya0045** [comment]
How is this a feature request or even a bug report? We should add a link to the mailing lists for other type of 'issues'/tickets.

**Comment by dazza-codes** [comment]
It's a request to bring it back.  The feature is gone.

**Comment by gioman** [comment]
> Yes, it has been removed for QGIS 3 : https://gis.stackexchange.com/questions/312236/qgis-browser-for-version-3

removed as standalone and integrated in main QGIS application.

**Comment by gioman** [comment]
> It's a request to bring it back. The feature is gone.

unlikely to aver happen, the goal is to integrate the old standalone browser (and db manager) functionalities in the new data source manager.

**Comment by gioman** [comment]
but if you want I can reopen.

**Comment by dazza-codes** [comment]
IMO it could help for this issue to be open so that users missing the browser functionality can vote somehow for that feature and developers can get that feedback (or create a specific issue for voting on this qbrowser feature).  I can certainly understand the dev-perspective to reduce maintenance overhead.  *The one-click find and view functionality is just perfect for nearly 90% of my use-cases when working with GeoTIFFs and other formats that QGIS supports.*  If that functionality were so easily available from a panel or something in the QGIS 3.x app, please point me in the right direction, since most of my use cases doesn't require managing a project or layers.  I did try the QGIS 3.x browser but it can't do the one-click find and view that the qbrowser could, it demands that everything is dragged into layers in a project.

**Comment by dazza-codes** [comment]
Maybe there is some way to isolate the 2.x release package for just the qbrowser component and split it out of the main qgis debian/ubuntu package, thereby leaving it behind as an archive of the 2.x release that doesn't need to be maintained for an LTS system (or only update a branch for it for security patches and deprecate it).

One solution is to try to purge the gis-ppa and rollback to the 2.x release.  It's going to lose other benefits of the gis-ppa, but might recover the older qgis app (not highly recommended), i.e.
```
sudo apt-get install ppa-purge
sudo purge-ppa ppa:ubuntugis/ppa  # rolls back installed packages
sudo apt autoremove
sudo apt install qgis
qbrowser  # is back!
```

**Comment by DelazJ** [comment]
@dazza-codes At the top of the Browser panel, you have an "Enable/disable properties widget" button. click on it, you get a panel at the bottom of the browser. One of the tab is "Preview" and would help you view your data. A right-click over the layer, Layer properties would also display the information in a new dialog.
Honestly, I'm not sure that the request of getting back the separate browser will ever get a yes.

**Comment by dazza-codes** [comment]
It could really help the transition if updates to documentation could include the instructions ^^ about how to enable a simple file-system browser with a preview in the latest app versions.  If that takes care of this, it could be resolved/closed with doc-PR.

**Comment by NathanW2** [comment]
There are currently no plans to being back the browser in future releases.
Not at the moment anyway.  I'm not sure including notes on how to mix
installs to get back the old browser is a good idea as it will confuse
users.
