### ISSUE TITLE
Field calculator bug with loooong integers

### ISSUE THREAD

**Issue by Luuffen** [qgis/QGIS#34262]
tested with QGIS 3.4.15 and 3.10.1 on Windows 10 64bit
Filed calculator puts wrong values into integer field, for Shape also manually editing in table after saving results in wrong values. Tested for Shapefile and GeoPackage (with newly created and already existing files).
Example:
1. create new layerfile (gpkg or shape)
2. add some objects
3. open field calculator, create new column int 64 bit, 21 length -> write value 1234567890123456789 (field calculator preview already showed wrong value 1234567890123456800)
--> result in attribute table: 1234567890123456768
4. write value manually by hand into table cell works (before saving)
5. for Shape: saving file --> manually inserting 1234567890123456789 into cell produces 1234567890123456768 (wrong)
for gpkg: saving file --> manually inserting 1234567890123456789 into cell stays 1234567890123456789 (correct)

Difference between gpkg and Shape: gpkg sourcefield datatype stays qlonglong (type) Integer64 (typename), for Shape it is automatically changed into double (type) Real (typename).

Problem occurs also with other integer fieldtype.

![grafik](https://user-images.githubusercontent.com/49310583/73742696-48f08e80-474d-11ea-8e18-92a0ed543b50.png)
![grafik](https://user-images.githubusercontent.com/49310583/73742768-6d4c6b00-474d-11ea-9a22-845d4a6e210c.png)

**Comment by gioman** [comment]
@Luuffen QGIS version? Platform?

**Comment by Luuffen** [comment]
Oh sorry, of course: 3.4.15 and 3.10.1 Windows

**Comment by agiudiceandrea** [comment]
@gioman I've made some test and I can confirm there's a problem in Field Calculator when handling integers and particularly 64 bit integers that may silently cause calculation errors.

It seems there are also some more general incorrect behaviour handling field types for shapefile layers.

The strange reported Field Calculator / Expression builder behaviours are present in both 3.4 an 3.10 branch regardless of the layer source.

I've made some tests with QGIS 3.10.1 using the Field Calculator whose dialog window can be opened from the Attribute Table or from Layer properties / Fields. There is also a slightly different Field Calculator (qgis:fieldcalculator) in the Processing Toolbox that behave like the former for some aspects of this issue.

1) Wrong "Output preview"
a) inserting e.g. the number `1234567890123456789` (which is in the range of a 64 bit integer) in the Expression box, "Output preview" displays the **wrong** number 1234567890123456800
b) the same occurs with the expression `137174210013717421*9`, which equals to 1234567890123456789:  "Output preview" **wrongly** displays 1234567890123456800
c) it happens differently with the expression `1290011087*957021147` or `357641*13717421*251649`, which both equal to 1234567890123456789, "Output preview" **correctly** displays 1234567890123456789
d) with:
  d1) `1290011087*106335683*9` -> 1234567890123456789 (**correct**)
  d2) `1290011087*106335683*3*3` -> 1234567890123456789 (**correct**)
  d3) `1290011087*106335683*(3^2)` -> 1234567890123456800 (**wrong**)

2) using a memory layer with a field created as "Whole number - (integer - 64bit)" (type: qlonglong, type name: int8) and just one record
a) the number 1234567890123456789 is correctly stored and showed in the field if manually inserted; it results that is possible to manually insert in such type of filed values in the range -9223372036854775808 to 9223372036854775807 (which is the total 64 bit integers range)
b) updating the field, or creating a new "Whole number - (integer - 64bit)" filed using the Field Calculator, with the above expressions, the following values are stored in the field:
  (1a). 1234567890123456768 (**wrong**)
  (1b). 1234567890123456768 (**wrong**)
  (1c). 1234567890123456789 (**correct**)
  (1d1). 1234567890123456789 (**correct**)
  (1d2). 1234567890123456789 (**correct**)
  (1d3). 1234567890123456768 (**wrong**)
c) if a field, say "wn64_1", contains the value 1234567890123456789, then using `wn64_1` in the expression box results in a **correct** display of the Output preview and such correct value will be stored in another updated or newly create "Whole number - (integer - 64bit)" field
d) it will be **correct** also if wn64_1 = 137174210013717421 and wn64_2 = 9, using `wn64_1*wn64_2` in the expression box. As previously said (see 1b and 2b), on the contrary `137174210013717421*9` produce **wrong** results instead

**Comment by agiudiceandrea** [comment]
The problem is most likely at
https://github.com/qgis/QGIS/blob/58f1206748fa29b0018a68e1279832b77ab9d1e5/src/core/qgsexpressionlexer.ll#L206-L217

When cLocale()->toInt() fails to properly convert a literal to a 32 bit int, then a conversion to a double is performed.

I think it is necessary to also add an attempt to or directly try to convert to a 64 bit integer using cLocale()->toLongLong(), instead.

**Comment by agiudiceandrea** [comment]
qgssqlstatementlexer.ll is yet capable to correctly handle int64 numbers:
https://github.com/qgis/QGIS/blob/ef108f3538e96d1edbba987c4b4a04f762a05b31/src/core/qgssqlstatementlexer.ll#L168-L183

**Comment by agiudiceandrea** [comment]
Hi @Luuffen,
if you want, you could test a patched version of QGIS downloading a self-contained portale version 
 from https://github.com/qgis/QGIS/suites/627782765/artifacts/5049452

Let me know if the patch proposed with PR #35996 solves for you the issue about int64 literals in expressions.
