### ISSUE TITLE
[postgres] Performance issue: Fields are converted to text

### ISSUE THREAD

**Issue by mhugo** [qgis/QGIS#34264]
**Describe the bug**

It appears that values read from a PostgreSQL source are first converted to text when the SQL query is crafted. This results in unneeded extra space allocated and transferred on the network.

Sources:

- https://github.com/qgis/QGIS/blob/master/src/providers/postgres/qgspostgresfeatureiterator.cpp#L639
- https://github.com/qgis/QGIS/blob/master/src/providers/postgres/qgspostgresconn.cpp#L1622

It seems the conversion to text is here on purpose but I cannot find the rationale behind it. Maybe to ease some other parts of code ? Could anyone shed some light ?

**How to Reproduce**

You can reproduce easily by looking at queries that QGIS generates on the PostgreSQL server (like with a call to `pg_stat_statements`). The query looks like `select "field1"::text, "field2"::text from ...` whatever the types of `field1`, `field2`are ...

**QGIS and OS versions**

https://github.com/qgis/QGIS/commit/e64a6acd38

**Comment by Saijin-Naib** [comment]
Related: https://github.com/qgis/QGIS/issues/34077

GIS.SE Question: https://gis.stackexchange.com/questions/348536/qgis-form-performance

**Comment by nyalldawson** [comment]
I can't explain this choice either. But it also breaks server-side request ordering for the postgres provider (it's currently disabled as a result).

**Comment by mhugo** [comment]
@espinafre @m-kuhn Thank you very much !
