### ISSUE TITLE
Can't merge raster layers

### ISSUE THREAD

**Issue by housepig83** [qgis/QGIS#34284]
I can't merge these raster layers. I wonder is it because of the data or software error because i used to be able to merge other raster layers. This set of raster layers are overlapping each other wonder it could cause an issue or not. I have tried the mosaic raster function as well, it worked fine but missed out some tiles so i have to mosaic those missing parts individually. 

Below is the error message when I run merge raster function.

QGIS version: 3.10.1-A Coruña
QGIS code revision: ef24c526da
Qt version: 5.11.2
GDAL version: 3.0.2
GEOS version: 3.8.0-CAPI-1.13.1 
PROJ version: Rel. 6.2.1, November 1st, 2019
Processing algorithm…
Algorithm 'Merge' starting…
Input parameters:
{ 'DATA_TYPE' : 5, 'EXTRA' : '', 'INPUT' : ['G:/My Drive/CWR - Shared/GIS/2019 Cap Threat/Taipei/Taiwan DTM20m/KEELUNG20MDEM/97232022dem.grd','G:/My Drive/CWR - Shared/GIS/2019 Cap Threat/Taipei/Taiwan DTM20m/KEELUNG20MDEM/97232031dem.grd','G:/My Drive/CWR - Shared/GIS/2019 Cap Threat/Taipei/Taiwan DTM20m/KEELUNG20MDEM/97232032dem.grd','G:/My Drive/CWR - Shared/GIS/2019 Cap Threat/Taipei/Taiwan DTM20m/KEELUNG20MDEM/97232041dem.grd','G:/My Drive/CWR - Shared/GIS/2019 Cap Threat/Taipei/Taiwan DTM20m/KEELUNG20MDEM/97232042dem.grd','G:/My Drive/CWR - Shared/GIS/2019 Cap Threat/Taipei/Taiwan DTM20m/KEELUNG20MDEM/97232043dem.grd','G:/My Drive/CWR - Shared/GIS/2019 Cap Threat/Taipei/Taiwan DTM20m/KEELUNG20MDEM/97232051dem.grd','G:/My Drive/CWR - Shared/GIS/2019 Cap Threat/Taipei/Taiwan DTM20m/KEELUNG20MDEM/97232052dem.grd','G:/My Drive/CWR - Shared/GIS/2019 Cap Threat/Taipei/Taiwan DTM20m/KEELUNG20MDEM/97232061dem.grd','G:/My Drive/CWR - Shared/GIS/2019 Cap Threat/Taipei/Taiwan DTM20m/KEELUNG20MDEM/97232071dem.grd','G:/My Drive/CWR - Shared/GIS/2019 Cap Threat/Taipei/Taiwan DTM20m/KEELUNG20MDEM/97233028dem.grd','G:/My Drive/CWR - Shared/GIS/2019 Cap Threat/Taipei/Taiwan DTM20m/KEELUNG20MDEM/97233029dem.grd','G:/My Drive/CWR - Shared/GIS/2019 Cap Threat/Taipei/Taiwan DTM20m/KEELUNG20MDEM/97233036dem.grd','G:/My Drive/CWR - Shared/GIS/2019 Cap Threat/Taipei/Taiwan DTM20m/KEELUNG20MDEM/97233037dem.grd','G:/My Drive/CWR - Shared/GIS/2019 Cap Threat/Taipei/Taiwan DTM20m/KEELUNG20MDEM/97233038dem.grd','G:/My Drive/CWR - Shared/GIS/2019 Cap Threat/Taipei/Taiwan DTM20m/KEELUNG20MDEM/97233039dem.grd','G:/My Drive/CWR - Shared/GIS/2019 Cap Threat/Taipei/Taiwan DTM20m/KEELUNG20MDEM/97233040dem.grd','G:/My Drive/CWR - Shared/GIS/2019 Cap Threat/Taipei/Taiwan DTM20m/KEELUNG20MDEM/97233045dem.grd','G:/My Drive/CWR - Shared/GIS/2019 Cap Threat/Taipei/Taiwan DTM20m/KEELUNG20MDEM/97233046dem.grd','G:/My Drive/CWR - Shared/GIS/2019 Cap Threat/Taipei/Taiwan DTM20m/KEELUNG20MDEM/97233047dem.grd','G:/My Drive/CWR - Shared/GIS/2019 Cap Threat/Taipei/Taiwan DTM20m/KEELUNG20MDEM/97233048dem.grd','G:/My Drive/CWR - Shared/GIS/2019 Cap Threat/Taipei/Taiwan DTM20m/KEELUNG20MDEM/97233049dem.grd','G:/My Drive/CWR - Shared/GIS/2019 Cap Threat/Taipei/Taiwan DTM20m/KEELUNG20MDEM/97233050dem.grd','G:/My Drive/CWR - Shared/GIS/2019 Cap Threat/Taipei/Taiwan DTM20m/KEELUNG20MDEM/97233056dem.grd','G:/My Drive/CWR - Shared/GIS/2019 Cap Threat/Taipei/Taiwan DTM20m/KEELUNG20MDEM/97233057dem.grd','G:/My Drive/CWR - Shared/GIS/2019 Cap Threat/Taipei/Taiwan DTM20m/KEELUNG20MDEM/97233058dem.grd','G:/My Drive/CWR - Shared/GIS/2019 Cap Threat/Taipei/Taiwan DTM20m/KEELUNG20MDEM/97233059dem.grd','G:/My Drive/CWR - Shared/GIS/2019 Cap Threat/Taipei/Taiwan DTM20m/KEELUNG20MDEM/97233060dem.grd','G:/My Drive/CWR - Shared/GIS/2019 Cap Threat/Taipei/Taiwan DTM20m/KEELUNG20MDEM/97233066dem.grd','G:/My Drive/CWR - Shared/GIS/2019 Cap Threat/Taipei/Taiwan DTM20m/KEELUNG20MDEM/97233067dem.grd','G:/My Drive/CWR - Shared/GIS/2019 Cap Threat/Taipei/Taiwan DTM20m/KEELUNG20MDEM/97233068dem.grd','G:/My Drive/CWR - Shared/GIS/2019 Cap Threat/Taipei/Taiwan DTM20m/KEELUNG20MDEM/97233069dem.grd','G:/My Drive/CWR - Shared/GIS/2019 Cap Threat/Taipei/Taiwan DTM20m/KEELUNG20MDEM/97233070dem.grd','G:/My Drive/CWR - Shared/GIS/2019 Cap Threat/Taipei/Taiwan DTM20m/KEELUNG20MDEM/97233078dem.grd','G:/My Drive/CWR - Shared/GIS/2019 Cap Threat/Taipei/Taiwan DTM20m/KEELUNG20MDEM/97233079dem.grd','G:/My Drive/CWR - Shared/GIS/2019 Cap Threat/Taipei/Taiwan DTM20m/KEELUNG20MDEM/97233080dem.grd'], 'NODATA_INPUT' : None, 'NODATA_OUTPUT' : None, 'OPTIONS' : '', 'OUTPUT' : 'TEMPORARY_OUTPUT', 'PCT' : False, 'SEPARATE' : False }

GDAL command:
python3 -m gdal_merge -ot Float32 -of GTiff -o C:/Users/ctl/AppData/Local/Temp/processing_e39c4d5bce7c4fa1a94c9959d9b93a82/processing_df500df4c3a3448e891c18384a65f79f/7d02fbd926654b8f9127fbdd3cfe9ea7/OUTPUT.tif --optfile C:/Users/ctl/AppData/Local/Temp/processing_e39c4d5bce7c4fa1a94c9959d9b93a82/processing_df500df4c3a3448e891c18384a65f79f/560e7cc5a9b1416e8ae4484379dbfb14/mergeInputFiles.txt
GDAL command output:
ERROR 1: Attempt to create 1139x-551 dataset is illegal,sizes must be larger than zero.

Creation failed, terminating gdal_merge.

Execution completed in 2.31 seconds
Results:
{'OUTPUT': 'C:/Users/ctl/AppData/Local/Temp/processing_e39c4d5bce7c4fa1a94c9959d9b93a82/processing_df500df4c3a3448e891c18384a65f79f/7d02fbd926654b8f9127fbdd3cfe9ea7/OUTPUT.tif'}

Loading resulting layers
The following layers were not correctly generated.<ul><li>C:/Users/ctl/AppData/Local/Temp/processing_e39c4d5bce7c4fa1a94c9959d9b93a82/processing_df500df4c3a3448e891c18384a65f79f/7d02fbd926654b8f9127fbdd3cfe9ea7/OUTPUT.tif</li></ul>You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.

**Comment by gioman** [comment]
> QGIS version: 3.10.1-A Coruña

@housepig83 already fixed, upgrade tp 3.10.2

**Comment by GGDRriedel** [comment]
I have the exact same error , I am on 3.10.2



Error Protocol: 


> QGIS-Version: 3.10.2-A Coruña
QGIS-Codeversion: 616ad4531b
Qt-Version: 5.11.2
GDAL-Version: 3.0.2
GEOS-Version: 3.8.0-CAPI-1.13.1 
PROJ-Version: Rel. 6.2.1, November 1st, 2019
Verarbeite Algorithmus…
Algorithmus Verschmelzen startet…
Input parameters:
{ 'DATA_TYPE' : 5, 'EXTRA' : '', 'INPUT' : ['C:/Users/Riedel/Projekte/fun/wandern/334445638_dgm1.xyz','C:/Users/Riedel/Projekte/fun/wandern/334445640_dgm1.xyz','C:/Users/Riedel/Projekte/fun/wandern/334465636_dgm1.xyz','C:/Users/Riedel/Projekte/fun/wandern/334465638_dgm1.xyz','C:/Users/Riedel/Projekte/fun/wandern/334465640_dgm1.xyz','C:/Users/Riedel/Projekte/fun/wandern/334485638_dgm1.xyz'], 'NODATA_INPUT' : None, 'NODATA_OUTPUT' : None, 'OPTIONS' : '', 'OUTPUT' : 'C:/Users/Riedel/Projekte/fun/wandern/test.tif', 'PCT' : False, 'SEPARATE' : False }

GDAL command:
python3 -m gdal_merge -ot Float32 -of GTiff -o C:/Users/Riedel/Projekte/fun/wandern/test.tif --optfile C:\Users\Riedel\AppData\Local\Temp/processing_7c6cecac1d6744d6a5c2bb3a8d321471/4ee4855bf4a845aa9964efafe07f5beb/mergeInputFiles.txt
GDAL command output:
ERROR 1: Attempt to create 6000x-1999 dataset is illegal,sizes must be larger than zero.

Creation failed, terminating gdal_merge.

Execution completed in 18.71 seconds
Results:
{'OUTPUT': 'C:/Users/Riedel/Projekte/fun/wandern/test.tif'}

Lade Ergebnis Layer
Die folgenden Layer wurden nicht erzeugt.<ul><li>C:/Users/Riedel/Projekte/fun/wandern/test.tif</li></ul>Im 'Protokoll-Fenster' im QGIS-Hauptfenster sind mehr Informationen zur Ausführung des Algorithmus zu finden.
