### ISSUE TITLE
After QGIS 3.10.1 & 3.10.2 updates the Greek CRS is erroneously projected

### ISSUE THREAD

**Issue by AnestisPan** [qgis/QGIS#34299]
After updating from the 3.10.0 version to 3.10.1 and recently to 3.10.2 the existing layers with CRS "GGRS87 / Greek Grid EPSG:2100" are erroneously projected somewhere to Saudi Arabia. Uninstalled and reinstalled version 3.10.0 to solve the problem.

**Comment by gioman** [comment]
@AnestisPan can you attach sample data?

**Comment by uclaros** [comment]
Do you re-project? or just loading the layer it appears on wrong coordinates?
I'm using 2100 daily here without any issues with either 2100, 4326 or web mercator

**Comment by AnestisPan** [comment]
Thank you for the replies, after a more thorough research we make the problem is narrowed to the oziexplorer map files. I include the example below. This file when opened with QGIS 3.10.0 and of course all the previous versions, it is displayed in the right coordinates somewhere in W. Crete - Greece. With the latest versions 3.10.1 & 3.10.2 it is displayed in Egypt and cannot correct the position after setting any other CRS. The project CRS is EPSG:2100 - GGRS87 /Greek Grid.
[tp.zip](https://github.com/qgis/QGIS/files/4159516/tp.zip)

**Comment by gioman** [comment]
@AnestisPan on 3.10.2 with old GDAL/PROJ dependencies it shows in the right place, so this may be an issue in a new version of a underlying library rather than QGIS



QGIS version | 3.10.2-A Coruña | QGIS code revision | 616ad4531b
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 10.10 (Ubuntu 10.10-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493

![Screenshot_20200205_130652](https://user-images.githubusercontent.com/1951107/73844385-63436e80-4818-11ea-8bbd-52fb703c76cf.png)

**Comment by AnestisPan** [comment]
Probably but the problem is that after updating to 3.10.1 and 3.10.2 I open the same project and one of the layers is offset and I cannot restore it in any way. I do not understand what you mean by "old GDAL/PROJ dependencies". If I convert the ozfx file to geotiff probably there will be no problem as already checked in other projects. But what can I do for the older projects?

**Comment by gioman** [comment]
> I do not understand what you mean by "old GDAL/PROJ dependencies"

QGIS 3.10.2 on Windows uses much more recent versions of GDAL and PROJ compared to the test I made with 3.10.2 on Ubuntu.

So, in both cases 3.10.2, but the underlying libraries (among the others the one involved in projection management) are different, this apparently points to a problem but not in QGIS.

**Comment by AnestisPan** [comment]
OK I believe that the new versions (this is not the case for 3.4.15) do not translate the projection described in oziexplorer .map file correctly as in the previous versions. By the way thank very much for the replies.

**Comment by gioman** [comment]
@AnestisPan QGIS 3.4.15 on Windows uses slightly older dependencies than 3.10.2. You see the correct thing on 3.4.15?

**Comment by AnestisPan** [comment]
Yes there is no problem with 3.4.15. OK I will search to learn more about old GDAL/PROJ dependencies if this can correct the issue. To be honest I am not a GIS expert, I just use QGIS after using oziexplorer for field geological mapping wit a tablet. Again thank you very much.

**Comment by gioman** [comment]
> Yes there is no problem with 3.4.15

don't get me wrong, of there is an issue in 3.10.2 that wasn't in previous releases than it must be fixed, regardless if the bug is in QGIS code or not.

**Comment by uclaros** [comment]
I haven't used oziexplorer files again, but `gdalinfo tp_all.map` says it's in WGS84, not GGRS87, and so does opening `tp_all.map` in a text editor.

**Comment by AnestisPan** [comment]
Correct I was mistaken the project is in GGRS87. But the fact is that from the beginning after opening the same project, the two versions display the map differently. In the second (erroneous) case I also used the WGS84 CRS and many others, with no results.

**Comment by gioman** [comment]
@AnestisPan @uclaros gdalinfo returns pretty different things depending is using GDAL 3.0.4 or 2.4.3

3.0.4

```
C:\Users\qgis\Desktop\tp>gdalinfo tp_all.map
Driver: MAP/OziExplorer .MAP
Files: tp_all.map
       tp_all.ozfx3
Size is 5364, 10570
Coordinate System is:
PROJCRS["unnamed",
    BASEGEOGCRS["WGS 84",
        DATUM["World Geodetic System 1984",
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4326]],
    CONVERSION["unnamed",
        METHOD["Mercator (variant A)",
            ID["EPSG",9804]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",1,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",0,
            LENGTHUNIT["Meter",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["Meter",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["easting",east,
            ORDER[1],
            LENGTHUNIT["Meter",1]],
        AXIS["northing",north,
            ORDER[2],
            LENGTHUNIT["Meter",1]]]
Data axis to CRS axis mapping: 1,2
GeoTransform =
  3945249.397383949, 0, -0.502219058747572
  2695047.226405261, 0.6661887092701261, 0
Corner Coordinates:
Upper Left  ( 3945249.397, 2695047.226) ( 35d26'26.80"E, 23d39'40.66"N)
Lower Left  ( 3939940.942, 2695047.226) ( 35d23'35.13"E, 23d39'40.66"N)
Upper Right ( 3945249.397, 2698620.663) ( 35d26'26.80"E, 23d41'27.09"N)
Lower Right ( 3939940.942, 2698620.663) ( 35d23'35.13"E, 23d41'27.09"N)
Center      ( 3942595.170, 2696833.945) ( 35d25' 0.97"E, 23d40'33.88"N)
Band 1 Block=64x64 Type=Byte, ColorInterp=Palette
  Overviews: 1341x2642, 536x1057, 268x528, 134x264, 54x106
```

2.4.3

```
giovanni@sibirica:~/Downloads/tp$ gdalinfo tp_all.map
Driver: MAP/OziExplorer .MAP
Files: tp_all.map
       tp_all.ozfx3
Size is 5364, 10570
Coordinate System is:
PROJCS["unnamed",
    GEOGCS["WGS 84",
        DATUM["WGS_1984",
            SPHEROID["WGS 84",6378137,298.257223563,
                AUTHORITY["EPSG","7030"]],
            AUTHORITY["EPSG","6326"]],
        PRIMEM["Greenwich",0,
            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.0174532925199433,
            AUTHORITY["EPSG","9122"]],
        AUTHORITY["EPSG","4326"]],
    PROJECTION["Mercator_1SP"],
    PARAMETER["central_meridian",0],
    PARAMETER["scale_factor",1],
    PARAMETER["false_easting",0],
    PARAMETER["false_northing",0],
    UNIT["Meter",1]]
Origin = (2633963.125376945827156,4199166.343846347182989)
Pixel Size = (0.613564643046821,-0.613506506028512)
Corner Coordinates:
Upper Left  ( 2633963.125, 4199166.344) ( 23d39'40.66"E, 35d26'26.80"N)
Lower Left  ( 2633963.125, 4192681.580) ( 23d39'40.66"E, 35d23'35.13"N)
Upper Right ( 2637254.286, 4199166.344) ( 23d41'27.09"E, 35d26'26.80"N)
Lower Right ( 2637254.286, 4192681.580) ( 23d41'27.09"E, 35d23'35.13"N)
Center      ( 2635608.706, 4195923.962) ( 23d40'33.87"E, 35d25' 0.98"N)
Band 1 Block=64x64 Type=Byte, ColorInterp=Palette
  Overviews: 1341x2642, 536x1057, 268x528, 134x264, 54x106
```


see for example the coordinates of the corners. This is likely a bug in GDAL or a change in GDAL that must trigger also a change in QGIS.

**Comment by uclaros** [comment]
Easting and northing are switched in those results!

**Comment by AndrewAnnex** [comment]
I think I am running into this issue currently, what is odd is that it did not start until I install 3.10.2 from https://github.com/qgis/QGIS-Mac-Packager and what is very strange is that it has modified behavior in older versions of qgis I have installed including 3.4. I thought the packages would be isolated from each other, they don't interact with any system level packages no? @gioman

**Comment by rouault** [comment]
I've confirmed this to be a GDAL 3.0 regression. Fixed per https://github.com/OSGeo/gdal/commit/7bedf61bbb8d8c331642b44f30c083abb43f4085
