### ISSUE TITLE
WFS Transaction operation using GetCapabilities URI

### ISSUE THREAD

**Issue by Rastopapola** [qgis/QGIS#34307]
**Describe the bug**

Transaction operation is not performed on the <ows:Operation name="Transaction"> referred uri. Instead the capabilities uri is used.

**How to Reproduce**
1. Add a WFS of your choice to QGIS, which is able to perform transaction operations. 
1. Draw some polygons, try to save them.
1. The response depends on the implementation of the server, which provides the data. 

If the request fails providing a non-200 code, QGIS informs in the WFS message tab about the used uri. You can see the capabilities uri with added `?SERVICE=WFS` parameter.

**QGIS and OS versions**
Sry, it's german:

QGIS-Version | 3.4.4-Madeira | QGIS-Codeversion | f6ddc62
Kompiliert gegen Qt | 5.7.1 | Laufendes Qt | 5.7.1
Kompiliert mit GDAL/OGR | 2.1.2 | Läuft mit GDAL/OGR | 2.1.2
Kompiliert mit GEOS | 3.5.1-CAPI-1.9.1 | Läuft mit GEOS | 3.5.1-CAPI-1.9.1 r4246
PostgreSQL-Client-Version | 9.6.10 | SpatiaLite-Version | 4.3.0a
QWT-Version | 6.1.2 | QScintilla2-Version | 2.9.3
PROJ.4-Version | 493

installed from  trusty packages, used by Debian 10.

**Additional context**
No further information.

**Comment by gioman** [comment]
> QGIS-Version | 3.4.4-Madeira | QGIS-Codeversion | [f6ddc62](https://github.com/qgis/QGIS/commit/f6ddc62fdb8ae589d3827e84d0c25bf669931040)

@Rastopapola maybe it won't change much, but you must test against a recent release, 3.4.15 and 3.10.2 (3.10 is about to become LTR).

**Comment by Rastopapola** [comment]
Thanks for the hint, I will install one of the recent releases tomorrow and give you feedback.

**Comment by Rastopapola** [comment]
@gioman 
A little thing before I continue:
I checked the [QGIS documentation](https://www.qgis.org/en/site/forusers/alldownloads.html#linux) and it's stated there, that the version 3.10.x would be available using `https://qgis.org/debian` as source in my `/etc/apt/sources.list`. Using this source, I only had the chance of installing qgis in version 3.4.14, as stated in my opening post. When I add the suffix `-ltr`, I'm able to get the version 3.4.**15.**

**Yet, the bug exists in there as well**. I try to figure out how to retrieve the 3.10.x from the trusty packages.

**Comment by Rastopapola** [comment]
@gioman 
Alright, I realized I had Debian 9 installed, despite the fact I wrote Debian 10 in my opening post. However - after a dist upgrade, I was able to install QGIS 3.10.x and the bug is still there :/ 

The error message isn't shown in the message tab on the bottom now, as it was in 3.4.x, so I was only able to determine whether it worked or not by checking my proxy log and the request is still targeting the capabilities URI. 

Could you please check if the uri from 
```xml
<ows:OperationsMetadata>
  <ows:Operation name="GetCapabilities">
    <ows:DCP>
      <ows:HTTP>
        <ows:Get xlink:type="simple" xlink:href="http://xys.com?>
        <ows:Post xlink:type="simple" xlink:href="http://xys.com?>
      </ows:HTTP>
    </ows:DCP>
  <ows:Operation name="GetCapabilities">
</ows:OperationsMetadata>
```
is used instead of 
```xml
<ows:OperationsMetadata>
  <ows:Operation name="Transaction">
    <ows:DCP>
      <ows:HTTP>
        <ows:Get xlink:type="simple" xlink:href="http://xys.com?>
        <ows:Post xlink:type="simple" xlink:href="http://xys.com?>
      </ows:HTTP>
    </ows:DCP>
  <ows:Operation name="GetCapabilities">
</ows:OperationsMetadata>
```

**Comment by Rastopapola** [comment]
@gioman 

An update to my now current version:


QGIS version | 3.10.2-A Coruña | QGIS code revision | 616ad4531b
-- | -- | -- | --
Compiled against Qt | 5.11.3 | Running against Qt | 5.11.3
Compiled against GDAL/OGR | 2.4.0 | Running against GDAL/OGR | 2.4.0
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.27.2 | Running against SQLite | 3.27.2
PostgreSQL Client Version | 11.5 (Debian 11.5-1+deb10u1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.10.4
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Debian GNU/Linux 10 (buster)
Active python plugins | MetaSearch; processing; db_manager

**Comment by rouault** [comment]
@rastopapola In https://github.com/qgis/QGIS/pull/36746 , I've enhanced an existing unit test demonstrating that the Transaction endpoints are used for transaction operations.

Do you force your service version to be WFS 1.0.0 ? Because that's the only version supported by QGIS currently for the transactional part.

**Comment by Rastopapola** [comment]
@rouault I stumbled over this behaviour while working on another project, so it was just some test service I used. I would need to readd the service in my system and check again if I forced 1.0.0 on the WFS. 

When this is covered in your tests now and everything runs as expected, there must be something else fishy in there.

Thanks for your reply!

**Comment by rouault** [comment]
@Rastopapola Could you re-test with latest QGIS version ? It has now WFS-T 1.1 support by the way

**Comment by Rastopapola** [comment]
@rouault Thanks for this update but I'm not working any longer on the project, where I detected that behaviour. Maybe someone else might be able to check on this?

**Comment by gioman** [comment]
Closing for lack of feedback.
