### ISSUE TITLE
Incorrect results when running Query Builder to filter features for a layer

### ISSUE THREAD

**Issue by saberraz** [qgis/QGIS#34303]
To replicate the issue in QGIS master:
- Add a vector layer
- Go to Properties > Source
- Select Query Builder
- Write a valid query and click on Test
- The result is not shown correctly:

![image](https://user-images.githubusercontent.com/2649047/73835704-c546a880-4805-11ea-8957-840e5e9c902c.png)

**Comment by saberraz** [comment]
Well, it seems the whole feature filtering is broken

**Comment by elpaso** [comment]
@saberraz works for me on master. Can you attach a sample project? 
Why did you close this btw?

**Comment by saberraz** [comment]
Ale, after filing the ticket and reloading the layer, all started working again! Magic of ![Alt Text](https://media.giphy.com/media/F7yLXA5fJ5sLC/giphy.gif)

**Comment by Gustry** [comment]
It looks a duplicate with https://github.com/qgis/QGIS/issues/34259
