### ISSUE TITLE
Coordinate display stuck in degrees with IRENET95 CRS

### ISSUE THREAD

**Issue by smckech** [qgis/QGIS#34306]
Using QGIS version 3.6.2-Noosa on Windows 10 Pro 64-bit OS. I imported kmz in WGS84, reprojected to IRENET95 but the displayed coordinates are stuck in angular units. Switching to UTM results in the expected metric units. Guessing this is some bug with IRENET95 CRS?

**Comment by gioman** [comment]
> Using QGIS version 3.6.2-Noosa

@smckech upgrade to 3.4.15 or 3.10.2 and check if the problem persist.

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
