### ISSUE TITLE
CRITICAL message (Qt : QWinJumpList failed) & (Qt : QVariant::save: unable to save type 'QgsAttributeTableConfig::ColumnConfig')

### ISSUE THREAD

**Issue by JMi31** [qgis/QGIS#34310]
Hello,

I found some CRITICAL issues working on a qgz workfile used with QGIS (3.10.2-A Coruña) during workfile saving.

Here are QGIS MESSAGES :
"_2020-02-05T09:46:02     CRITICAL    Qt : QWinJumpList: CommitList() failed: 0x80070497_"
"_2020-02-05T12:10:42     CRITICAL    Qt : QVariant::save: unable to save type 'QgsAttributeTableConfig::ColumnConfig' (type id: 1130)_"

This could be linked with QT MESSAGE : 
"_2020-02-03T09:05:38     WARNING    GEOS exception: TopologyException: Input geom 0 is invalid: Nested shells at or near point 1565658.449 2264147.6644000001 at 1565658.449 2264147.6644000001"

The only new features I used in this workfile is "Organise" functionality for some attribute tables...

Thanks in advance for your help to solve the matter.

JMi31
-----------------------------
Version de QGIS
3.10.2-A Coruña
Révision du code
e28feaf5fd
Compilé avec Qt
5.11.2
Utilisant Qt
5.11.2
Compilé avec GDAL/OGR
3.1.0dev
Utilisé avec GDAL/OGR
3.1.0dev
Compilé avec GEOS
3.8.0-CAPI-1.13.1
Utilisé avec GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
Version du client PostgreSQL
11.5
Version de SpatiaLite
4.3.0
Version de QWT
6.1.3
Version de QScintilla2
2.10.8
Compilé avec PROJ
7.0.0
Fonctionne avec PROJ
Rel. 7.0.0, March 1st, 2020
OS Version
Windows 7 SP 1 (6.1)
Cette copie de QGIS dispose d'une sortie de débogage.
Extensions Python actives
db_manager; 
MetaSearch; 
processing

**Comment by gioman** [comment]
@JMi31 is this a question?

**Comment by JMi31** [comment]
Hi gioman,

Just information for your bug recordings, and...
possibly an answer to solve the problem ?

**Comment by gioman** [comment]
@JMi31 


> "_2020-02-03T09:05:38 WARNING GEOS exception: TopologyException: Input geom 0 is invalid: Nested shells at or near point 1565658.449 2264147.6644000001 at 1565658.449 2264147.6644000001"

what problem, this one?

**Comment by JMi31** [comment]
The point does not correspond to any object on the map.
"Nested Shells" shoud correspond to "polygone layer" encapsulation... 
However, I did'nt work on any layer of this type since a long time, so I don't understand why this error comes now. 
I did'nt find what layer was involved in the generation of this error.

**Comment by gioman** [comment]
@JMi31 without access to the project (and data) hard to say what can be wrong. Anyway this does not seems much a bug report, and neither a feature request.

**Comment by JMi31** [comment]
However, when saving the workfile, this message is still persistant (not the second one "QTVariant"...)  : 

2020-02-05T09:46:02 CRITICAL Qt : QWinJumpList: CommitList() failed: 0x80070497"

**Comment by Pedro-Murteira** [comment]
I'm unable to reproduce this issue. @JMi31 did you come across this bug in more recent versions?
