### ISSUE TITLE
"Save as..." GPKG/SHP a FileGDB creates wrong geometries

### ISSUE THREAD

**Issue by Fi156** [qgis/QGIS#34327]
**Describe the bug**

FileGDB "Save as..." dialog creates wrong geometries
Geometry Type:
Polygon ZM in ESRI File Geodatabase

![ErrorAsFig](https://user-images.githubusercontent.com/2189169/73922690-df49bf00-48c9-11ea-8c89-93bac6e7a877.png)

**How to Reproduce**

Create a FileGDB with ArcMap (included in the sample Data)
Create Feature Layer with Polygon Geometries, icnluding Z and M - Measures. (included in the sample Data)

Open Qgis
Import Layer directly from GDB.
Export via "Save as..." dialog as GPKG or SHP (doesnt matter).
Get wrong geometry. (see picture above and GPKG "ZMPolyTest_GPKG")

Using ogr2ogr like:

ogr2ogr -append  -f GPKG  "\ZMPolyTest_GPKG_fromOGR2OGR_withoutNLT.gpkg" "\ZMPolyTest_FileGDB.gdb"

Will lead to a correctly exported dataset. See: ZMPolyTest_GPKG_fromOGR2OGR and ZMPolyTest_GPKG_fromOGR2OGR_withoutNLT

**QGIS and OS versions**
![QgisAndOGR_Versions](https://user-images.githubusercontent.com/2189169/73923005-757de500-48ca-11ea-8c07-00ef560ca7f1.png)

ogr2ogr was used from the same OSGeo install and has therefore the same version as in QGis.

**Example data:**
https://we.tl/t-uMgCOmiZxj

**Comment by gioman** [comment]
Confirmed also on Ubuntu with an older GDAL/OGR version (2.2.4) and using the open source driver to open the FileGDB thing.

**Comment by stev-0** [comment]
@Fi156 Can you repost the link or put it somewhere that doesn't expire please

**Comment by Fi156** [comment]
Had the issue today on 3.10.5 again.
Switched to 3.14.0 used the same steps and did not get the error.

From my point of view: This should be fixed somehow...

@stev-0 do you want to have a look at it regardlessly?

**Comment by gioman** [comment]
>  Switched to 3.14.0 used the same steps and did not get the error.

likely fixed in GDAL 3.*.
