### ISSUE TITLE
'__MACOSX'  not found in _plugin_modules | module '__MACOSX' has no attribute class factory

### ISSUE THREAD

**Issue by carlosbabativa** [qgis/QGIS#34323]
**Describe the bug**

Unhandled error or missing key when pyplugin_installer.instance().installFromZipFile(r'/path/to/zip.zip')

Error:
Traceback (most recent call last):
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
AttributeError: module '__MACOSX' has no attribute 'classFactory'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "", line 1, in 
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/pyplugin_installer/installer.py", line 612, in installFromZipFile
    if startPlugin(pluginName):
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 337, in startPlugin
    _unloadPluginModules(packageName)
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 404, in _unloadPluginModules
    mods = _plugin_modules[packageName]
KeyError: '__MACOSX'
Python version:
3.6.8 (v3.6.8:3c6b436a57, Dec 24 2018, 02:04:31) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]

QGIS version:
3.4.12-Madeira 'Madeira', exported

**How to Reproduce**

**Additional context**

**Comment by gioman** [comment]
@carlosbabativa what installer have you used? what is triggering the error?

**Comment by gioman** [comment]
Also, what macOS version are you using?

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.

**Comment by rneppi** [comment]
After opening "plugin manager/installed" I see at first position a plugin called "__MACOSX" in red letter wich is deactivatet. I can set it activ, but after reopening plugin manager it is deactivatet again. In description area appears
```
This plugin is broken
Missing metadata file
__MACOSX

Installed version	?
```
I can uninstall it successfully (qgis says).

After installing and activating the plugin "OSMDownloader" the plugin "__MACOSX" is back as discribed above. One working toolbar bottom for "OSMdownloader" apperas but no entree in Menus. (I don't know if that's normal.)

Anyway, what's the plugin "__MACOSX" and its issue all about?


Here some environment data:
System: OSX 10.15.5

QGIS version | 3.10.6-A Coruña | 
QGIS code revision | ec80021f49
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.28.0 | Running against SQLite | 3.28.0
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS 10.15
Active python plugins | QuickOSM; quick_map_services; latlontools; batch_hillshader-master; processing; db_manager; MetaSearch; OSMDownloader

**Comment by rejusam** [comment]
> After opening "plugin manager/installed" I see at first position a plugin called "__MACOSX" in red letter wich is deactivatet. I can set it activ, but after reopening plugin manager it is deactivatet again. In description area appears
> 
> ```
> This plugin is broken
> Missing metadata file
> __MACOSX
> 
> Installed version	?
> ```
> 
> I can uninstall it successfully (qgis says).
> 
> After installing and activating the plugin "OSMDownloader" the plugin "__MACOSX" is back as discribed above. One working toolbar bottom for "OSMdownloader" apperas but no entree in Menus. (I don't know if that's normal.)
> 
> Anyway, what's the plugin "__MACOSX" and its issue all about?
> 
> Here some environment data:
> System: OSX 10.15.5
> 
> QGIS version | 3.10.6-A Coruña |
> QGIS code revision | [ec80021](https://github.com/qgis/QGIS/commit/ec80021f49ea23306eea2bccfc771f567fe87787)
> Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
> Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
> Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
> Compiled against SQLite | 3.28.0 | Running against SQLite | 3.28.0
> PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
> QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
> Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
> OS Version | macOS 10.15
> Active python plugins | QuickOSM; quick_map_services; latlontools; batch_hillshader-master; processing; db_manager; MetaSearch; OSMDownloader

@rneppi did you solved this issue? If yes, please let me know how you have done this. 
Tankyou

**Comment by Gustry** [comment]
Open your QGIS profile folder, go to `python/plugins` and remove any folder named like `__MACOSX`.

**Comment by rejusam** [comment]
thanks @Gustry :-)

**Comment by rneppi** [comment]
@rejusam 
No I didn't.
After updating qgis the error did not appear any more.
Searching for "__MACOSX" inside QGIS-LTR 3.16.7 - package has no results.
