### ISSUE TITLE
Fields are shifted when importing a layer with an FID attribute into GeoPackage

### ISSUE THREAD

**Issue by havatv** [qgis/QGIS#34333]
**Describe the bug**
When importing a layer containing a field with the name "FID" (case sensitive) into a GeoPackage, the field values of original "FID" column and the following fields are shifted to the next field. The original values of the last field are gone. A field with the name "fid" will not cause any trouble, but "FID", "Fid", ... result in this erroneous behaviour.

**How to Reproduce**

1. Create a new temporary scratch layer (Layer-> Create Layer-> New Temporary Scratch Layer)
2. Open the attribute table of this layer and add the following fields: `FID` (Number, 0), `Text` (Text, 10), `Number` (Number, 0)
3. Add a new feature to the layer with the following values: `99` (FID), `111` (Text), `555` (Number).
4. Stop editing and save changes. This is what the table looks like:
![temptable](https://user-images.githubusercontent.com/1598812/73937417-47f26500-48e5-11ea-8d53-8209db3df461.png)

5. Create a new Geopackage
6. Find the new Geopackage in the Browser, and drag the new layer into it.
7. Right-click on the layer in the geopackage (in the Browser), and open Layer Properties
8. Look at the result:
![gpkg_attr](https://user-images.githubusercontent.com/1598812/73937461-5e98bc00-48e5-11ea-8a55-f54930c6fcd1.png)

An `fid` column has been added as the leftmost column in the table, and the original `FID` column is gone. The `fid` column has been populated with a generated (unique) value. The original values in the `FID` column have been moved to the next column, and the original values in that column have then been moved to the next one, and so on.  The original values in the rightmost column are gone.

If the original `FID` field is not the first (leftmost) field, only the columns to the right of the `FID` column in the table are affected (the `fid` field is still added as the leftmost column).

**QGIS and OS versions**
Recent nightly on Ubuntu 18.04 (but I discovered it with 3.10.2 - have not tried with 3.4):

QGIS version
3.11.0-Master
QGIS code revision
b7980f009c
Compiled against Qt
5.9.5
Running against Qt
5.9.5
Compiled against GDAL/OGR
2.2.3
Running against GDAL/OGR
2.2.3
Compiled against GEOS
3.6.2-CAPI-1.10.2
Running against GEOS
3.6.2-CAPI-1.10.2 4d2925d6
Compiled against SQLite
3.22.0
Running against SQLite
3.22.0
PostgreSQL Client Version
10.10 (Ubuntu 10.10-0ubuntu0.18.04.1)
SpatiaLite Version
4.3.0a
QWT Version
6.1.3
QScintilla2 Version
2.10.2
PROJ.4 Version
493
OS Version
Ubuntu 18.04.3 LTS
This copy of QGIS writes debugging output.
Active python plugins
ThinGreyscale; 
NNJoin; 
SDEllipse; 
LineDirectionHistogram; 
processing_r; 
Climb; 
MultiDistanceBuffer; 
processing; 
db_manager; 
MetaSearch

**Additional context**

Issues I found that may be related: #28097, #30697.

**Comment by Saijin-Naib** [comment]
@gioman , this seems severe. Potential loss of data!

**Comment by havatv** [comment]
Thanks!
Tested on today's nightly (code revision a0723939fa), and the behaviour is now as expected.
A column with name ``FID``/``Fid``/``FiD``/... is treated as a unique id and "translated" into the GeoPackage ``fid`` column. If there are duplicates in that column, the import will fail, as expected.
