### ISSUE TITLE
inverted polygons on gradient filliing crashed qgis

### ISSUE THREAD

**Issue by johansanders** [qgis/QGIS#34330]
inverted polygons on gradient filliing crashed qgis

Crash ID: 63c2d17bf4e9aa97d36ec3a2dfa3992c4a741bc6

Stack Trace

QPaintEngineExPrivate::hasClipOperations :
QRegion::xored :

QGIS Info
QGIS Version: 3.10.2-A Coru�a
QGIS code revision: d4cd3cfe5a
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.3
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by gioman** [comment]
@johansanders please add detailed steps (and sample data) that lead to the crash.

**Comment by johansanders** [comment]
It seems to be dependent of the number of polygons and the applied gradient  "plasma"

I select layer polygons - transparant  single symbol
Apply gradient plasma
Change single symbol to inverted polygon => crash

When i apply gradient gray then no problem
f.i.
Polygon for 9  provincies  no problem ; 14  also ok
300 communities  crash
266 flow areas crash

[cid:image002.jpg@01D5DCEF.C9FEEF80]
Vriendelijke groeten
________________________________
Johan Sanders
Dienstverlening
Consulent Dienstbetoon
E johan.sanders@boerenbond.be<mailto:johan.sanders@boerenbond.be>
T (092) 43 88 31<tel:+3292438831>
M (0472) 81 03 36<tel:+32472810336>
Boerenbond & Landelijke Gilden
Kortrijksesteenweg 1144 J, 9051 Sint-Denijs-Westrem
http://www.boerenbond.be<http://www.boerenbond.be/>
http://www.landelijkegilden.be<http://www.landelijkegilden.be/>


Van: Giovanni Manghi <notifications@github.com>
Verzonden: donderdag 6 februari 2020 12:52
Aan: qgis/QGIS <QGIS@noreply.github.com>
CC: Johan Sanders <johan.sanders@boerenbond.be>; Mention <mention@noreply.github.com>
Onderwerp: Re: [qgis/QGIS] inverted polygons on gradient filliing crashed qgis (#34330)


@johansanders<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjohansanders&data=02%7C01%7Cjohan.sanders%40boerenbond.be%7Cdcbb7f161aad4ba8127308d7aafaeee4%7Ccce5156d7a794845927c07fc674c3e2b%7C0%7C0%7C637165867040246640&sdata=o1Z1oJIegIiNAWRrxTRfuYIigCzD%2B0G9U7sb7kG6wT8%3D&reserved=0> please add detailed steps (and sample data) that lead to the crash.

-

**Comment by gioman** [comment]
> Polygon for 9 provincies no problem ; 14 also ok

@johansanders please attach the data and the style.

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.

**Comment by johansanders** [comment]
Sorry

Problem was solved  in most recent version

Thank you very much

Vriendelijke groeten
________________________________
Johan Sanders
Dienstverlening
Consulent Dienstbetoon
E johan.sanders@boerenbond.be<mailto:johan.sanders@boerenbond.be>
T (092) 43 88 31<tel:+3292438831>
M (0472) 81 03 36<tel:+32472810336>
Boerenbond & Landelijke Gilden
Kortrijksesteenweg 1144 J, 9051 Sint-Denijs-Westrem
http://www.boerenbond.be<http://www.boerenbond.be/>
http://www.landelijkegilden.be<http://www.landelijkegilden.be/>


Van: Giovanni Manghi <notifications@github.com>
Verzonden: maandag 2 maart 2020 17:33
Aan: qgis/QGIS <QGIS@noreply.github.com>
CC: Johan Sanders <johan.sanders@boerenbond.be>; Mention <mention@noreply.github.com>
Onderwerp: Re: [qgis/QGIS] inverted polygons on gradient filliing crashed qgis (#34330)


Closed #34330<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fqgis%2FQGIS%2Fissues%2F34330&data=02%7C01%7Cjohan.sanders%40boerenbond.be%7Caf6468ebb1b7450b028b08d7bec75114%7Ccce5156d7a794845927c07fc674c3e2b%7C0%7C0%7C637187635577846491&sdata=At0hF2OhujC520YUwjhNMv2pbl7EqXV6P6IxkHOZGwQ%3D&reserved=0>.
