### ISSUE TITLE
Plugin Manager 'Reload all Repositories' Doesn't Reload Private Repository

### ISSUE THREAD

**Issue by jlayt** [qgis/QGIS#34351]
**Describe the bug**

Reloading a private plugin repository does not make new updates available, and continues to cache old versions of the installed plugins. New profiles for the existing users also get the old versions, but new users are able to install the latest versions. If 'Check for updates on startup' is set the manifest does eventually update after an as yet undetermined interval of time.

It appears QGIS3 or Qt is too aggressively caching both the repo manifest and any already installed plugins at the Mac user level and doesn't actually refresh them when requested. This makes it very hard to fix issues in our private plugins and distribute them to our staff.

This worked correctly in QGIS2.

**How to Reproduce**

1. Upload updated plugin to our private repo, edit our repo .xml file with the new version number and zip filename, delete old version zip file.
2. Run QGIS3 for user with the old version already installed, choose Plugins > Manage and Install Plugins > Settings > Reload all Repositories.
3. No 'Updated' tab shows in the sidebar.
4. Check plugin and 'Available Version' is still the old version.
5. Delete plugin, do 'Reload all Repositories', and 'Available Version' is still the old version.
6. Install plugin, old version is installed despite zip file no longer being on the server.
7. Create new QGIS user profile for same Mac login user, add repo, shows old version, installs old version.
8. Create new Mac test login on same computer, run QGIS, add repo, shows new version, installs new version.

**QGIS and OS versions**

QGIS version | 3.10.2-A Coruña | QGIS code revision | 616ad4531b
-- | -- | -- | --
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.28.0 | Running against SQLite | 3.28.0
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS 10.15
Active python plugins | LPGetLibraryInfo; LPMaps; ArkSpatial; MemoryLayerSaver; LPFigureBuilder; plugin_reloader; processing; db_manager; MetaSearch

**Additional context**

If access is required to our private repository, please contact me directly.

**Comment by jlayt** [comment]
I should also note that deleting and re-adding the private repo with a restart in-between also does not make the updates appear.

**Comment by saberraz** [comment]
See this https://issues.qgis.org/issues/17411

**Comment by jlayt** [comment]
We don't have this issue with our still maintained QGIS2 plugins served from the same repo.

The response headers for the plugins.xml request (per Firefox dev tools) are:

HTTP/1.1 200 OK
Date: Fri, 07 Feb 2020 10:45:03 GMT
Server: Apache/2.4.38 (Debian)
Last-Modified: Thu, 06 Feb 2020 16:01:08 GMT
ETag: "1731-59dea61953648-gzip"
Accept-Ranges: bytes
Vary: Accept-Encoding
Content-Encoding: gzip
Content-Length: 907
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: application/xml

**Comment by jlayt** [comment]
Adding 'Cache-Control: no-store' works around the issue for us, but it seems wrong that QGIS should be using the cached copies when no control is set at all. It also seems wrong that if I explicitly click 'Reload' it doesn't force a reload, surely that is what the option is supposed to do?

**Comment by miroHema** [comment]
I do confirm we face the same issue in our company. Even after removing repository, restarting QGIS, adding repository again, it shows old versions of plugins available. If you click on old version number link it downloads the new version though. Which seems to me as if plugin.xml is cached by QGIS and does not get truly reloaded. Not after hitting "Reload all Repositories" and after even deleting and adding private repository.
