### ISSUE TITLE
QGIS v3.4.15 LTS Crashes while adding columns to attributes table

### ISSUE THREAD

**Issue by dathinc** [qgis/QGIS#34353]
Crash ID: b89dd818f9aa4f5a02e09c26e6e3cd1e79137d0c

Stack Trace

QSortFilterProxyModel::parent :
QModelIndex::parent :
QTableView::visualRect :
QAbstractItemView::update :
QAbstractItemView::currentChanged :
QMetaObject::activate :
QItemSelectionModel::`default constructor closure' :
QItemSelectionModel::qt_static_metacall :
QMetaObject::activate :
QAbstractItemModel::beginRemoveRows :
QSortFilterProxyModel::removeRows :
QSortFilterProxyModel::sortRole :
QSortFilterProxyModel::`default constructor closure' :
QMetaObject::activate :
QAbstractItemModel::beginRemoveRows :
QgsAttributeTableModel::removeRows qgsattributetablemodel.cpp:173
QgsAttributeTableModel::loadLayer qgsattributetablemodel.cpp:445
QMetaObject::activate :
QMetaObject::activate :
QgsVectorLayer::updateFields qgsvectorlayer.cpp:3449
QgsVectorLayerEditBuffer::commitChanges qgsvectorlayereditbuffer.cpp:473
QgsVectorLayer::commitChanges qgsvectorlayer.cpp:2940
QgisApp::toggleEditing qgisapp.cpp:9309
QgsAttributeTableDialog::mActionToggleEditing_toggled qgsattributetabledialog.cpp:881
QMetaObject::activate :
QAction::setChecked :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:373
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:373
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1542
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.4.15-Madeira
QGIS code revision: e83d02e274
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.3
Running against GDAL: 2.4.3

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment]
@dathinc Please try with a new QGIS profile (no 3rd party plugins installed).

If the problem persist please add detailed steps to replicate and sample data.

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
