### ISSUE TITLE
Label masking doesn't work with line pattern symbol sub layers

### ISSUE THREAD

**Issue by nirvn** [qgis/QGIS#34352]
While testing out the label masking feature some more today, I stumble on an implementation issue, whereas line pattern symbol's sub layer aren't masked.

Test project here:
[mask.zip](https://github.com/qgis/QGIS/files/4170252/mask.zip)

You can see here the hashed lines are checked to be masked but
![Screenshot from 2020-02-07 17-35-47](https://user-images.githubusercontent.com/1728657/74022527-4d78a980-49d0-11ea-94c1-aa92c3f60129.png)

**Comment by nirvn** [comment]
@mhugo , gentle ping. It'd be great if you could look into this issue before masking is officially released as part of 3.12. Cheers

**Comment by mhugo** [comment]
@nirvn Thanks for your feedback. However, I am struggling to find some available time to work on it before 3.12 ...

**Comment by nirvn** [comment]
@mhugo , OK, it's a shame though, it means QGIS will ship masking without sub-symbol support (hashed lines, point pattern, geometry generator, etc.). Nobody can force you to find that hour before now and release date to insure the implementation is complete, but I'll keep hoping you find time until then.

**Comment by mhugo** [comment]
After some time spent on a debugging session, it seems to come from `QgsLinePatternFillSymbolLayer::applyPattern`
https://github.com/qgis/QGIS/blob/master/src/core/symbology/qgsfillsymbollayer.cpp#L2517
where the fill line sub symbol is cloned for some reasons.

The symbol layer pointers that have to be disabled in the second pass and are stored in the rendering context do not correspond anymore ...
So I have to find a more robust way to disable symbol layers during the second pass ...

Not easy :-(

**Comment by Pedro-Murteira** [comment]
Still valid on QGIS 3.22.3.

**Comment by thymaro** [comment]
I don't understand _how_, but I understand _that_ it is complicated to fix. So, this is not a rant, just another sitrep:

I can confirm this is still valid for QGIS 3.22.6. Line pattern fills don't respect masks.
![grafik](https://user-images.githubusercontent.com/24420636/165026816-863f040f-02c6-44d4-8fd5-f87e57b80598.png)
