### ISSUE TITLE
QGIS unexpectedly ended

### ISSUE THREAD

**Issue by chuerta805** [qgis/QGIS#34360]
QGIS window froze as I was scrolling up. I had the node/segment database loaded with tile layers and features loaded as well.

Not sure how to reproduce besides loading those layers and scrolling. 

QGIS 3.4 and OS is Windows 10 Business

It has been freezing up frequently. It freezes up at different times. Sometimes within 5 minutes of using QGIS other times after an hour or longer.

Below is a copy of the report as well.

## User Feedback

I was scrolling, with features and tile layers loaded, and it froze. 

## Report Details

*Crash ID*: 262c3ca0538bface1674559813eb628df070d42e

*Stack Trace*
<pre>
QIODevice::channelReadyRead :
QIODevice::write :
QLocalSocket::isSequential :
QHttpMultiPart::qt_metacast :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:373
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
QEventLoop::exec :
QgsWmsProvider::draw qgswmsprovider.cpp:873
QgsWmsProvider::readBlock qgswmsprovider.cpp:895
QgsRasterDataProvider::block qgsrasterdataprovider.cpp:200
QgsSingleBandColorDataRenderer::block qgssinglebandcolordatarenderer.cpp:62
QgsBrightnessContrastFilter::block qgsbrightnesscontrastfilter.cpp:118
QgsHueSaturationFilter::block qgshuesaturationfilter.cpp:123
QgsRasterResampleFilter::block qgsrasterresamplefilter.cpp:161
QgsRasterProjector::block qgsrasterprojector.cpp:770
QgsRasterIterator::readNextRasterPart qgsrasteriterator.cpp:118
QgsRasterDrawer::draw qgsrasterdrawer.cpp:58
QgsRasterLayerRenderer::render qgsrasterlayerrenderer.cpp:274
QgsMapRendererParallelJob::renderLayerStatic qgsmaprendererparalleljob.cpp:256
QtConcurrent::MapKernel<QList<QPair<QgsVectorDataProvider * __ptr64,QgsFeatureRequest> >::iterator,QtConcurrent::FunctionWrapper1<void,QPair<QgsVectorDataProvider * __ptr64,QgsFeatureRequest> const & __ptr64> >::runIteration qtconcurrentmapkernel.h:69
QtConcurrent::MapKernel<QList<QgsImageOperation::ImageBlock>::iterator,QgsImageOperation::ProcessBlockUsingPixelOperation<QgsImageOperation::GrayscalePixelOperation> >::runIterations qtconcurrentmapkernel.h:78
QtConcurrent::IterateKernel<QList<QgsImageOperation::ImageBlock>::iterator,void>::forThreadFunction qtconcurrentiteratekernel.h:256
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.4.15-Madeira
QGIS code revision: e83d02e274
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.3
Running against GDAL: 2.4.3

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by gioman** [comment]
@chuerta805 Please try with a new QGIS profile, no 3rd party plugins installed.

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
