### ISSUE TITLE
Expanding menus going past screen boundaries do not follow active selection

### ISSUE THREAD

**Issue by anto-1** [qgis/QGIS#34364]
![Screenshot from 2020-02-07 23-37-35](https://user-images.githubusercontent.com/46658878/74079264-da3c5b00-4a02-11ea-9548-e1a560979b5b.png)

Therefore by continuing the selection towards the bottom we cannot see further available options.

**Comment by gioman** [comment]
QGIS version? Platform?

**Comment by anto-1** [comment]
QGIS version | 3.10.1-A Coruña | QGIS code branch | Release QGIS code branch.3
-- | -- | -- | --
Compiled against Qt | 5.13.2 | Running against Qt | 5.13.2
Compiled against GDAL/OGR | 2.3.2 | Running against GDAL/OGR | 2.3.2
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.30.0 | Running against SQLite | 3.30.0
PostgreSQL Client Version | 11.6 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Fedora 31 (Workstation Edition)
Active python plugins | quick_map_services; MetaSearch; processing; db_manager

**Comment by alexbruy** [comment]
Probably this is  DE-related, I can not reproduce on Windows and Linux. Are you using Gnome?

**Comment by anto-1** [comment]
Yes, Gnome Version 3.34.6. The problem is likely caused by Qt.

**Comment by alexbruy** [comment]
Actually in Qt environment and on Windows everything is ok. We have some other tickets with UI issues which only exists on Gnome and not reproducible on other platforms/environments.

**Comment by alexbruy** [comment]
Seems DE-specific. Closing.
