### ISSUE TITLE
QGIS DB Manager fails to escape quotes in comment field when importing a shapefile into PostGIS

### ISSUE THREAD

**Issue by Nitrodist** [qgis/QGIS#34362]
**Describe the bug**

User input is not escaped when using the 'comment' option in using QGIS's DB Manager to import a shapefile to a postgis instance. Having a quote in the optional comment value causes the import to crash/fail:

```
An error has occurred while executing Python code: 

db_manager.db_plugins.plugin.DbError: syntax error at or near "s" LINE 1: ...ourhoods" IS E'Imported from the City of Winnipeg's ODP http...                                                             ^ 
Traceback (most recent call last):
  File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/plugins/db_manager/db_plugins/connector.py", line 89, in _execute
    cursor.execute(sql)
psycopg2.errors.SyntaxError: syntax error at or near "s"
LINE 1: ...ourhoods" IS E'Imported from the City of Winnipeg's ODP http...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/plugins/db_manager/dlg_import_vector.py", line 382, in accept
    self.db.connector.commentTable(schema, table, com)
  File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/plugins/db_manager/db_plugins/postgis/connector.py", line 756, in commentTable
    self._execute(None, 'COMMENT ON TABLE "{0}"."{1}" IS E\'{2}\';'.format(schema, tablename, comment))
  File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/plugins/db_manager/db_plugins/connector.py", line 97, in _execute
    raise DbError(e, sql)
db_manager.db_plugins.plugin.DbError: syntax error at or near "s"
LINE 1: ...ourhoods" IS E'Imported from the City of Winnipeg's ODP http...
                                                             ^



Python version: 3.7.3 (default, Mar 27 2019, 09:23:15) [Clang 10.0.1 (clang-1001.0.46.3)] 
QGIS version: 3.10.2-A Coruña A Coruña, 616ad4531b 

Python Path:
/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python
/Users/markcampbell/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/markcampbell/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/plugins
/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7
/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/lib-dynload
/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/site-packages/geos
/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python37.zip
/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/site-packages
/Applications/QGIS3.10.app/Contents/Resources/python
/Users/markcampbell/Library/Application Support/QGIS/QGIS3/profiles/default/python
```

This is what it looks like to the user:

![image](https://user-images.githubusercontent.com/385448/74065316-33cc6780-49ba-11ea-80d9-c4f127dd51d2.png)

This is the comment value:

```
Imported from the City of Winnipeg's ODP https://data.winnipeg.ca/City-Planning/Neighbourhood/fen6-iygi
``` 

The quote in `Winnipeg's` causes a [sql injection bug](https://en.wikipedia.org/wiki/SQL_injection).

**How to Reproduce**

1. From the file menu, go to Database > DB Manager
1. Select PostGIS from the providers pane (left side) and navigate to a schema in a postgres database you have access to ([like this - screenshot](https://user-images.githubusercontent.com/385448/74065932-9e31d780-49bb-11ea-8302-0000236351cb.png))
1. Select the `Import Layer/File...` option from the top nav bar
1. Select any shape file as input, give it a table name 
1. Check off the 'Comment' checkbox and set the input box to its right to `'`
1. [See an error like this](https://user-images.githubusercontent.com/385448/74065316-33cc6780-49ba-11ea-80d9-c4f127dd51d2.png)

**QGIS and OS versions**

QGIS version | 3.10.2-A Coruña | QGIS code revision | 616ad4531b
-- | -- | -- | --
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.28.0 | Running against SQLite | 3.28.0
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS 10.15
Active python plugins | processing; db_manager; MetaSearch

**Additional context**

None

**Additional bugs**

The instruction to copy paste the QGIS version information from the 'About' dialog on Mac OS does not work as expected. The main program in the background is still selected, so Command-A selects all of the features and then Command-C copies all of their data resulting in a lot of coordinate data entering your clipboard, potentially megabytes.  On Mac OS you have to manually click-drag to select all of the text and then right click on the selected text to then select the 'copy text' button for this to work.

Secondly, after the import failed due to this bug the `odp_neighbourhoods` table was created but empty. Running the import again resulted in an error saying that the table already exists.

**Comment by DelazJ** [comment]
Can be closed, fixed by #34525
