### ISSUE TITLE
Minimize title bar height

### ISSUE THREAD

**Issue by anto-1** [qgis/QGIS#34373]
The title bar seems unnecessarily thick for small screens. However, this could concern only systems running Gnome desktops. Haven’t tried on other platforms. 
From the fresh install
![thick_titlebar](https://user-images.githubusercontent.com/46658878/74093308-2dafb700-4a9e-11ea-9416-02e498aa94a7.png)
A comparison to something more acceptable.
![example](https://user-images.githubusercontent.com/46658878/74093311-31dbd480-4a9e-11ea-8d55-4cc4cbc29ab6.png)

**Comment by nirvn** [comment]
This is controlled by your OS, not QGIS. Change your gnome shell GTK theme. Google is your friend :)
