### ISSUE TITLE
Cannot add/save more than 1 record/feature in a Spatialite layer/table

### ISSUE THREAD

**Issue by kaptainkory** [qgis/QGIS#34379]
To reproduce...

1. Add or create a Spatialite layer with autoincrementing primary key.
2. **Add more than 1 record.**
3. On Save, there is a provider error.

![Screenshot from 2020-02-09 10-38-28](https://user-images.githubusercontent.com/59102670/74106061-ff2aee00-4b28-11ea-9a9a-de8c971e372e.png)

QGIS version | 3.11.0-Master | QGIS code revision | a0723939fa
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.6.2-CAPI-1.10.2 4d2925d6
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 10.10 (Ubuntu 10.10-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Linux Mint 19.3 | This copy of QGIS writes debugging output.
Active python plugins | MetaSearch; processing; db_manager

**Comment by gioman** [comment]
> Add or create a Spatialite layer with autoincrementing primary key.

no error here on master/windows. Please attach a sample dataset.

**Comment by kaptainkory** [comment]
[temp.sqlite.zip](https://github.com/qgis/QGIS/files/4177174/temp.sqlite.zip)

**Comment by gioman** [comment]
> [temp.sqlite.zip](https://github.com/qgis/QGIS/files/4177174/temp.sqlite.zip)

@kaptainkory 

_Invalid Data Source: /home/giovanni/Downloads/temp.sqlite is not a valid or recognized data source._

**Comment by gioman** [comment]
> [temp.sqlite.zip](https://github.com/qgis/QGIS/files/4177174/temp.sqlite.zip)

@kaptainkory tried again with the geometryless table, no errors on master on both Windows and Linux.

**Comment by kaptainkory** [comment]
![Screenshot from 2020-02-09 11-20-15](https://user-images.githubusercontent.com/59102670/74106645-2f28c000-4b2e-11ea-975a-b545441415df.png)

[temp2.sqlite.zip](https://github.com/qgis/QGIS/files/4177207/temp2.sqlite.zip)

**Comment by gioman** [comment]
> [temp2.sqlite.zip](https://github.com/qgis/QGIS/files/4177207/temp2.sqlite.zip)

@kaptainkory ok, with this sample I can see the issue, weird.
