### ISSUE TITLE
Error in SQL statement for Virtual layers may lock layers in map canvas

### ISSUE THREAD

**Issue by klakar** [qgis/QGIS#34378]
### Issue:
Sometimes when I do something "wrong" in a virtual layer, the test can be "No error", but the result after "Add" is an error and any visible layers in the canvas will be "locked". No matter what layers are turned on or off, added or deleted, the canvas stays the same. QGIS does not crash, but will need a restart to work.

### Repeat:
Add "world" layer to canvas (world in coordinate field), rename to "world".
Add "contributors" layer to canvas (contributors in coordinate field), rename "contributors"

Create virtual layer:

`select * from contributors where st_intersects(contributors.geometry, (select geometry from world where iso_a2='FR'))`

This should generate a layer with points only inside the France country polygon.

Now, edit the virtual layer expression to something that is wrong, like:

`select * from contributors where st_intersects(contributors.geometry, (select * from world where iso_a2='FR'))`

(Note the * where previously geometry was)

A "Test" will not throw any errors, but when updating the layer, there will be an error...

**After this the canvas is locked!**

The only solution I've found to "un-freeze" the canvas is to restart QGIS.

### System

QGIS version | 3.10.2-A Coruña | QGIS code revision | 616ad4531b
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.6.2-CAPI-1.10.2 4d2925d6
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 10.10 (Ubuntu 10.10-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Ubuntu 18.04.4 LTS
Active python plugins | qfieldsync; LmOpenData; qgis2web; layout_loader; plugin_reloader; DataPlotly; Qgis2threejs; latlontools; pluginbuilder3; MetaSearch; db_manager; processing

**Comment by roya0045** [comment]
I guess the fault detection need to be fixed to prevent bad sql from being evaluated.
