### ISSUE TITLE
While not in focus, the floating menu open his action dialog behind itself when right-clicking on his items.

### ISSUE THREAD

**Issue by anto-1** [qgis/QGIS#34371]
![menu](https://user-images.githubusercontent.com/46658878/74092669-44054500-4a95-11ea-9b4f-2270710dcf2f.gif)

QGIS version | 3.10.1-A Coruña | QGIS code branch | Release QGIS code branch.3
-- | -- | -- | --
Compiled against Qt | 5.13.2 | Running against Qt | 5.13.2
Compiled against GDAL/OGR | 2.3.2 | Running against GDAL/OGR | 2.3.2
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.30.0 | Running against SQLite | 3.30.0
PostgreSQL Client Version | 11.6 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Fedora 31 (Workstation Edition)
Active python plugins | quick_map_services; MetaSearch; processing; db_manager

**Comment by nyalldawson** [comment]
Unfortunately this is an upstream (qt) issue - not something we can fix in qgis itself

**Comment by anto-1** [comment]
Cool, than you for the feeback.
