### ISSUE TITLE
QGIS crashes adding new field to geometryless Spatialite tbale

### ISSUE THREAD

**Issue by kaptainkory** [qgis/QGIS#34375]
Reproduce bug by...

1. Start new QGIS project.
2. Add or create new Spatialite layer.
3. Open attribute table.
4. Toggle editing.
5. Add new field.  (NOT add new feature, but field.)
6. Upon clicking "OK", QGIS crashes.

Bug even present when table has no existing features/records.

QGIS version | 3.11.0-Master | QGIS code revision | a0723939fa
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.6.2-CAPI-1.10.2 4d2925d6
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 10.10 (Ubuntu 10.10-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Linux Mint 19.3 | This copy of QGIS writes debugging output.
Active python plugins | latlontools; joinmultiplelines; qdraw; DataPlotly; mmqgis; DigitizingTools; openlayers_plugin; processing; db_manager

**Comment by pigreco** [comment]
I confirm on OSGeo4W64 win 10

**Comment by nirvn** [comment]
I can't confirm here, adding field (via the field calculator and the add a new field dialog) works fine here.

You'll need to provide a more specific steps to reproduce (e.g. "add a new field" is not precise enough as this can be done in many different ways).

I also see a few plugins in your profile active that could interfere. Try to confirm the crash under a new user profile.

**Comment by kaptainkory** [comment]
> I can't confirm here, adding field (via the field calculator and the add a new field dialog) works fine here.

Exactly as pigreco shows produces the crash for me.

**Comment by gioman** [comment]
> Exactly as pigreco shows produces the crash for me.

@kaptainkory @pigreco 

Also cannot replicate here (master on Windows), so it may be data dependent > please attach sample data.

Also note that the "add field" dialog that you posted is not the same as the one I see on master/windows here

![Screenshot_20200209_163554](https://user-images.githubusercontent.com/1951107/74105964-4c738380-4b5a-11ea-9833-b7d802f0a034.png)

**Comment by kaptainkory** [comment]
> Also note that the "add field" dialog that you posted is not the same as the one I see on master/windows here

Are you sure you are working with a Spatialite layer?  SQLite does not have hard type lengths.  (The dialog you show is exactly what I see from a Shapefile, however.)

[temp.sqlite.zip](https://github.com/qgis/QGIS/files/4177171/temp.sqlite.zip)

**Comment by gioman** [comment]
> Are you sure you are working with a Spatialite layer?

yes



> temp.sqlite.zip

_"Invalid Data Source: /home/giovanni/Downloads/temp.sqlite/temp.sqlite is not a valid or recognized data source."_

on both Windows and Linux

**Comment by gioman** [comment]
> SQLite does not have hard type lengths. (The dialog you show is exactly what I see from a Shapefile, however.)

ummm let me check again.

**Comment by kaptainkory** [comment]
The temp.sqlite does not include geometries (which are not needed to demonstrate the error).  It was created from scratch in QGIS itself.

**Comment by kaptainkory** [comment]
Here's a fresh one and all settings:

![Screenshot from 2020-02-09 11-04-38](https://user-images.githubusercontent.com/59102670/74106360-00a9e580-4b2c-11ea-832a-c399070b2a21.png)

[temp2.sqlite.zip](https://github.com/qgis/QGIS/files/4177189/temp2.sqlite.zip)

**Comment by gioman** [comment]
> The temp.sqlite does not include geometries (which are not needed to demonstrate the error). It was created from scratch in QGIS itself.

@kaptainkory crash replicated but ONLY for geometryless spatialite tables. So to prove the issue the lack of geometries is not optional.

**Comment by kaptainkory** [comment]
Fresh one...

![Screenshot from 2020-02-09 11-04-38](https://user-images.githubusercontent.com/59102670/74106466-e0c6f180-4b2c-11ea-9b6b-fdac210f1335.png)

[temp2.sqlite.zip](https://github.com/qgis/QGIS/files/4177195/temp2.sqlite.zip)

**Comment by gioman** [comment]
> Are you sure you are working with a Spatialite layer?

@kaptainkory also the "add field" dialog is different if the table is geometryless, an important detail about the understanding of this issue.

**Comment by nirvn** [comment]
I can confirm the crash too with the additional details provided.
