### ISSUE TITLE
Crash when joining a layer/table to a Spatialite layer

### ISSUE THREAD

**Issue by kaptainkory** [qgis/QGIS#34374]
Bug seems to have appeared within the last couple of days.  It showed up when I was running 3.10.x A Coruña from repository https://qgis.org/ubuntu-nightly-release, but in trying to troubleshoot I switched to 3.11 master with the same bug.

To reproduce...
1. Start new QGIS project.
2. Add new Spatialite layer, with a table and a couple of fields.
3. Add a couple of features.
4. Add another layer, such as duplicate existing layer.
5. From Properties... -> manage joins to other layers, set up a join.
6. Open attribute table for layer.
7. QGIS crashes.

I've tried some variations, such as Spatialite tables with and without geometries, joining with separate (not duplicated) Spatialite layers and with non-Spatialite layers (Shapefiles, Temp Scratch Layers), etc. all to the same effect.  Joining 2 Shapefiles by similar steps did not crash, but involving Spatialite layers for any part did.

QGIS version | 3.11.0-Master | QGIS code revision | a0723939fa
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.6.2-CAPI-1.10.2 4d2925d6
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 10.10 (Ubuntu 10.10-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Linux Mint 19.3 | This copy of QGIS writes debugging output.
Active python plugins | latlontools; joinmultiplelines; qdraw; DataPlotly; mmqgis; DigitizingTools; openlayers_plugin; processing; db_manager

**Comment by kaptainkory** [comment]
Just tested with all plugins disabled.  Same result.

**Comment by gioman** [comment]
> * Start new QGIS project.
> 
> * Add new Spatialite layer, with a table and a couple of fields.
> 
> * Add a couple of features.
> 
> * Add another layer, such as duplicate existing layer.
> 
> * From Properties... -> manage joins to other layers, set up a join.
> 
> * Open attribute table for layer.
> 
> * QGIS crashes.

@kaptainkory 
cannot replicate here on master/windows. Please attach sample data as also a screenshot of the join options.

**Comment by kaptainkory** [comment]
![Screenshot from 2020-02-09 11-27-43](https://user-images.githubusercontent.com/59102670/74106829-84b19c80-4b2f-11ea-97ab-5ba7b1f22b3c.png)

[temp2.sqlite.zip](https://github.com/qgis/QGIS/files/4177234/temp2.sqlite.zip)

Tested table with geometry + nongeometry AND geometry + geometry...both crash.  Test with no records in table(s) and then with a couple of records added...still crashes.

**Comment by kaptainkory** [comment]
[temp.shp.zip](https://github.com/qgis/QGIS/files/4177277/temp.shp.zip)

* shapefile + spatialite => NO CRASH
* spatialite + shapefile => CRASH

**Comment by gioman** [comment]
> spatialite + shapefile => CRASH

@kaptainkory replicated (on master/Windows).

**Comment by kaptainkory** [comment]
Are you not confirming crashes with spatialite to spatialite from provided "temp2.sqlite"?

**Comment by gioman** [comment]
> Are you not confirming crashes with spatialite to spatialite from provided "temp2.sqlite"?

@kaptainkory right

**Comment by kaptainkory** [comment]
Not thoroughly tested, but appears to be working now (at least Spatialite to Spatialite) in latest master:

QGIS version | 3.11.0-Master | QGIS code revision | fc6e453385
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.6.2-CAPI-1.10.2 4d2925d6
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 10.10 (Ubuntu 10.10-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Linux Mint 19.3 | This copy of QGIS writes debugging output.
Active python plugins | latlontools; joinmultiplelines; processing
