### ISSUE TITLE
[SAGA][MACOSX] Error in 'Add raster values to points'

### ISSUE THREAD

**Issue by amllerjacobsen** [qgis/QGIS#34385]
Environment:
Mac OS 
QGIS LTR 3.4.15
64 bit

Getting an error when using the SAGA function 'Add raster values to points'. Has worked for me previously some month ago so not sure what has happened. Tried to follow various threads here in Github and Google but nothing has worked so far - of course also full reinstall of the QGIS package but LTR and 3.10 versions.

Only error I can notice in below is "Error: Points" 

Any solutions out there?

Error message: 

` ____________________________
             
             ##### ## ##### ##
             ### ### ## ###
             ### # ## ## #### # ##
             ### ##### ## # #####
             ##### # ## ##### # ##
             ____________________________
             
             SAGA Version: 2.3.2
             
             ____________________________
             library path: /Applications/QGIS3.4.app/Contents/Resources/aaaa/
             library name: libio_gdal
             library : GDAL/OGR
             tool : Import Raster
             author : O.Conrad (c) 2007 (A.Ringeler)
             ____________________________
             
             
             
             Parameters
             
             
             Grids: No objects
             Files: "/Users/AMJ/temp/EGS_2018_bathymetry_1x1m.tif"
             Select from Multiple Bands:
             Alphanumeric Sorting: yes
             Transformation: yes
             Resampling: B-Spline Interpolation
             
             
             loading: /Users/AMJ/temp/EGS_2018_bathymetry_1x1m.tif
             
             
             
             Driver: GTiff
             
             Bands: 1
             
             Rows: 33260
             
             Columns: 17825
             
             
             loading: EGS_2018_bathymetry_1x1m
             
             
             
             
             Error: Points
             ____________________________
             
             ##### ## ##### ##
             ### ### ## ###
             ### # ## ## #### # ##
             ### ##### ## # #####
             ##### # ## ##### # ##
             ____________________________
             
             SAGA Version: 2.3.2
             
             ____________________________
             library path: /Applications/QGIS3.4.app/Contents/Resources/aaaa/
             library name: libshapes_grid
             library : Grid Tools
             tool : Add Grid Values to Points
             author : O.Conrad (c) 2003
             ____________________________
             
             Load shapes: /Users/AMJ/temp/wtg_cf_64x_point_20181011.shp...
             
             
             
             Usage: saga_cmd shapes_grid 0 [-SHAPES ] [-GRIDS ] [-RESULT ] [-RESAMPLING ]
             -SHAPES: Points
             Shapes (input)
             -GRIDS: Grids
             Grid list (input)
             -RESULT: Result
             Shapes (optional output)
             -RESAMPLING: Resampling
             Choice
             Available Choices:
             [0] Nearest Neighbour
             [1] Bilinear Interpolation
             [2] Bicubic Spline Interpolation
             [3] B-Spline Interpolation
             Default: 3`

**Comment by gioman** [comment]
@amllerjacobsen I just tested on Catalina with QGIS installed with the installer from the qgis.org download page > it works ok (I used sample data from the QGIS sample dataset).

**Comment by amllerjacobsen** [comment]
Ok thanks for the feedback. I've tried this as well but without luck, unfortunately.

**Comment by gioman** [comment]
>  I've tried this as well but without luck, unfortunately.

@amllerjacobsen mine is a completely clean systeam, clean Catalina install > QGIS installed using the installer in the qgis.org download page

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
