### ISSUE TITLE
Import homography crash QGIS

### ISSUE THREAD

**Issue by luipir** [qgis/QGIS#34393]
**Describe the bug**
Crash due to import homography python module installed with:

pi3 install homography

**How to Reproduce**

1. Go to QGIS python console
2. type: import homography
3. type: return => CRASH

**QGIS and OS versions**

Linux Ubuntu 18.04
python module: homography-0.1.5

QGIS version | 3.11.0-Master | QGIS code revision | c9fa1ab73c
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 12.1 (Ubuntu 12.1-1.pgdg18.04+1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Ubuntu 18.04.4 LTS | This copy of QGIS writes debugging output.
Active python plugins | plugin_reloader; processing_taudem; quick_map_services; qgisnetworklogger; qgis_resource_sharing; SpreadsheetLayers; firstaid; IPyConsole; LAStools; remotedebug; mapswipetool_plugin; db_manager

**Additional context**

None

**Comment by luipir** [comment]
Not yet confirmed, but seems the problem is not present in Win env

**Comment by luipir** [comment]
confirmed... no crash under Windows

**Comment by roya0045** [comment]
Is qgis to blame for crash when importing python libraries?

**Comment by nyalldawson** [comment]
Closing due to lack of feedback (also likely not a qgis issue)
