### ISSUE TITLE
[Data Source Manager][ArcGIS Feature Server] Column Cache Feature disappear

### ISSUE THREAD

**Issue by jonnyforestGIS** [qgis/QGIS#34397]
**Previous Steps**
- [X] Search through existing issue reports and gis.stackexchange.com to check whether the issue already exists. Can be related to: #27635 , #26780 , #23040
- [X] Test with a [clean new user profile](https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html?highlight=profile#working-with-user-profiles).
- [ ] Create a light and self-contained sample dataset and project file which demonstrates the issue. _Don't need it, because is a link to a feature map service._

**Describe the bug**
After connecting to an ArcGIS Feature Service the column of cache feature don't appear.
Link sample: http://sampleserver6.arcgisonline.com/arcgis/rest/services/Military/FeatureServer

Link with a youtube video that have the missing column (perhaps a version before 3.4 not sure): https://www.youtube.com/watch?v=Mo1hHy9rMjc
[![Correct Behavior](http://img.youtube.com/vi/Mo1hHy9rMjc/0.jpg)](http://www.youtube.com/watch?v=Mo1hHy9rMjc)

**How to Reproduce**
![missing_column](https://user-images.githubusercontent.com/4480601/74173108-69c35300-4c29-11ea-9495-f5e9f3768352.gif)

1. Go to Data Source Manager.
2. Click on ArcGIS Feature Server Tab
3. Add A new Connection With random name and the url http://sampleserver6.arcgisonline.com/arcgis/rest/services/Military/FeatureServer
4. Connect and see the missing column. Compare the same dialogue with the Youtube video.

**QGIS and OS versions**

QGIS version | 3.10.1-A Coruña | QGIS code revision | ef24c526da
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.2 | Running against GDAL/OGR | 3.0.2
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.2.1 | Running against PROJ | Rel. 6.2.1, November 1st, 2019
OS Version | Windows 7 SP 1 (6.1)
Active python plugins | crayfish; DataPlotly; disconnected-islands; export_to_sql_server; gerashapefile; gis4wrf; gribdownloader; GroupStats; ImportPhotos; LAStools; LayerBoard; pgRoutingLayer; Qgis2threejs; quick_map_services; raster_tracer; timemanager; db_manager; MetaSearch; processing

**Comment by nyalldawson** [comment]
Showing that setting was a bug, as it never had an actual effect -- the features were (and still are) **always** cached!

**Comment by jonnyforestGIS** [comment]
@nyalldawson thank you for your feedback. This was a collegue that reported to me and I posted as bug. Sorry for the "noise" Regards.
