### ISSUE TITLE
GeoPackage output format from QGIS Server WFS

### ISSUE THREAD

**Issue by MattiasSp** [qgis/QGIS#34391]
**Feature description.**
GeoPackage as output format from QGIS Server WFS Services would be sweet and would further improve the QGIS-GeoPackage compatibility.

**Additional context**
Seeing as QGIS already reads and writes GeoPackages natively, it would make sense to plan for its inclusion as a QGIS Server output format. GeoServer already offers this as an extension: https://docs.geoserver.org/latest/en/user/community/geopkg/

**Comment by rldhont** [comment]
A plugin already exists https://github.com/3liz/qgis-wfsOutputExtension

**Comment by MattiasSp** [comment]
> A plugin already exists https://github.com/3liz/qgis-wfsOutputExtension

Awesome plugin, wasn't aware of that! It doesn't seem to support GeoPackage yet though. Also, putting GeoPackage support in the main QGIS Server would be even better in my opinion.

**Comment by elpaso** [comment]
I'm -1 on adding this functionality into server library. 
I think that a plugin is a good way to implement extra formats.

**Comment by Gustry** [comment]
> It doesn't seem to support GeoPackage yet though. 

No, it was supporting Geopackage. Just the README file wasn't updated. I just fixed that.

**Comment by luipir** [comment]
should be tagged with won't fix?
