### ISSUE TITLE
Loading raster image ends with QGIS crash

### ISSUE THREAD

**Issue by uwerder** [qgis/QGIS#34398]
## User Feedback

I worked in the session for about 1 hour - everything worked well without issues. Tried to load another historic raster image when the system crashed. I hope this helps. Thanks for all your work and support!

## Report Details

**Crash ID**: [4b8aaf3599c0f5f32a5274ea89571df493d8a3a4]('https://github.com/qgis/QGIS/search?q=4b8aaf3599c0f5f32a5274ea89571df493d8a3a4&type=Issues')

**Stack Trace**
<pre>
MoveSmall memcpy.asm:441
GMLFeatureClass::IsSchemaLocked :
GDALRegister_Terragen :
VSIFilesystemHandler::IsCaseSensitive :
VSIFilesystemHandler::IsCaseSensitive :
VSIFilesystemHandler::IsCaseSensitive :
GDALRegister_GenBin :
GDALRasterBand::GetLockedBlockRef :
GDALRasterBand::IRasterIO :
GDALRegister_GenBin :
GDALRasterBand::RasterIO :
QgsProcessingModelOutput::toVariant :
QgsRasterIdentifyResult::params :
QgsAbstractDatabaseProviderConnection::TableProperty::GeometryColumnType::operator== :
QgsSingleBandGrayRenderer::block :
QgsBrightnessContrastFilter::block :
QgsHueSaturationFilter::block :
QgsRasterResampleFilter::block :
QgsRasterProjector::block :
QgsRasterIterator::readNextRasterPartInternal :
QgsRasterDrawer::draw :
QgsRasterLayerRenderer::render :
QgsMapRendererParallelJob::renderLayerStatic :
QgsArchive::zip :
QgsImageOperation::overlayColor :
QgsMapRendererParallelJob::cancelWithoutBlocking :
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.1-A Coru�a
QGIS code revision: ef24c526da
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by Saijin-Naib** [comment]
Can you re-try your work with the current/latest QGIS 3.10.2-1?

**Comment by gioman** [comment]
> Tried to load another historic raster image when the system crashed

@uwerder also 

1) try with a new QGIS profile (there are 3rd party plugins that are causing issues even if disabled, so better use a QGIS profile with no 3rd party plugins installed at all)

2) attach/link the offending raster

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
