### ISSUE TITLE
15km Radius from the Co-ordinates provided

### ISSUE THREAD

**Issue by irin-upgrad** [qgis/QGIS#34390]
**Feature description.**
Trying to upload a map shape file/ kmz file, need to find the provided coordinates checks 15km in and around of the coordinates. Will be highlighting the pin available which we have as a latitude and longitude. 

**Additional context**

**Comment by gioman** [comment]
> Trying to upload a map shape file/ kmz file, need to find the provided coordinates checks 15km in and around of the coordinates. Will be highlighting the pin available which we have as a latitude and longitude.

@irin-upgrad 
is this a feature request or a question about how to get some kind of results from your data?

**Comment by roya0045** [comment]
Is that even a question?

**Comment by alexbruy** [comment]
Closed for the lack of feedback.
