### ISSUE TITLE
PROBLEMS WITH QGIS 3.10 AND PGROUTING

### ISSUE THREAD

**Issue by FranciscoMoralesMartinez** [qgis/QGIS#34400]
Hello, I have a problem using QGIS and PGROUTING
Rather I connect a database, Pgrouting Layer is unable to detect that database.
Then, when I reboot QGIS, an error appears as it is in the attached file,

I hope you can help me with this problem,

Thank you,
[ERROR CON PGROUTING.txt](https://github.com/qgis/QGIS/files/4183414/ERROR.CON.PGROUTING.txt)

Bug fixing and feature development is a community responsibility, and not the responsibility of the QGIS project alone.
If this bug report or feature request is high-priority for you, we suggest engaging a QGIS developer or support organisation and financially sponsoring a fix

Checklist before submitting

- [ ] Search through existing issue reports and gis.stackexchange.com to check whether the issue already exists
- [ ] Test with a [clean new user profile](https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html?highlight=profile#working-with-user-profiles).
- [ ] Create a light and self-contained sample dataset and project file which demonstrates the issue

If the issue concerns a **third party plugin**, then it **cannot** be fixed by the QGIS team. Please raise your issue in the dedicated bug tracker for that specific plugin (as listed in the plugin's description). -->

**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by roya0045** [comment]
Error seems to lie with the plugin. As the issue template said, qgis cannot fix the plugin.
