### ISSUE TITLE
QGIS crashes when changing "default value" in layer property on a point scratch layer, after editing feature

### ISSUE THREAD

**Issue by danpejobo** [qgis/QGIS#34404]
**Additional context**

Bug experianced on a fresh userprofile, with no plugins installed

**Describe the bug**
Qgis crashes when applying changes (activating/deactivating) "default value" in layer properties on a point scratch layer, AFTER editing feature on the layer. Below is a picture showing info on the layer.
![image](https://user-images.githubusercontent.com/36916831/74216932-3541ac80-4ca6-11ea-825d-19fbfeb3ec23.png)

**How to Reproduce**
1. Enter edit mode
2. Add feature to a point scratch layer
3. Save and exit edit mode
4. Enter edit mode again and edit some attribute, save and exit editing
5. Enter layer properties and change "default value" on one of the fields.
5.  Apply change
6. QGIS crashes
![image](https://user-images.githubusercontent.com/36916831/74217819-d2054980-4ca8-11ea-957d-26d7867c3da3.png)

**QGIS and OS versions**

## Report Details

**Crash ID**: [630ba2dde6d626c9d75f75078859b3606d9abca2]('https://github.com/qgis/QGIS/search?q=630ba2dde6d626c9d75f75078859b3606d9abca2&type=Issues')

**Stack Trace**
<pre>
QObject::metaObject :
QMetaObject::cast :
QgsAttributeForm::updateDefaultValues qgsattributeform.cpp:494
QgsAttributeForm::onAttributeChanged qgsattributeform.cpp:881
QMetaObject::activate :
QgsEditorWidgetWrapper::valuesChanged moc_qgseditorwidgetwrapper.cpp:260
<lambda_40855d1aa2ea430dc6d1606b9acc29cf>::operator() qgstexteditwrapper.cpp:141
QMetaObject::activate :
QLineEdit::qt_static_metacall :
QMetaObject::activate :
QWidgetLineControl::finishChange :
QWidgetLineControl::internalSetText :
QgsTextEditWrapper::setWidgetValue qgstexteditwrapper.cpp:275
QgsEditorWidgetWrapper::setFeature qgseditorwidgetwrapper.cpp:76
QgsAttributeForm::resetValues qgsattributeform.cpp:765
QgsAttributeForm::setFeature qgsattributeform.cpp:281
QMetaObject::activate :
QgsVectorLayer::updateFields qgsvectorlayer.cpp:3620
QgsVectorLayer::setDefaultValueDefinition qgsvectorlayer.cpp:3685
QgsAttributesFormProperties::storeAttributeTypeDialog qgsattributesformproperties.cpp:335
QgsAttributesFormProperties::apply qgsattributesformproperties.cpp:731
QgsVectorLayerProperties::apply qgsvectorlayerproperties.cpp:747
QMetaObject::activate :
QDialog::done :
QMetaObject::activate :
QDialogButtonBox::~QDialogButtonBox :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
QgisApp::showLayerProperties qgisapp.cpp:14293
QgisApp::layerTreeViewDoubleClicked qgisapp.cpp:621
QMetaObject::activate :
QAbstractItemView::doubleClicked :
QTreeView::mouseDoubleClickEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1598
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.2-A Coru�a
QGIS code revision: d4cd3cfe5a
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.3
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by elpaso** [comment]
I tried hard but I couldn't make it crash on master.

**Comment by danpejobo** [comment]
@elpaso i had the layer "set up" with the default value in layer properties (as shown in the picture) before adding the feature. Then start from point 1. Maybe you needed to have it set up before adding the feature.

The idea was to "edit" the default value of the attribute (for testing purposes) of the field "Bornavn", so after adding the feature i turned off "apply default value", and then qgis crashes. On the version above, it does so all the time and i don't know how to debug any further

**Comment by gioman** [comment]
>     7\. ![image](https://user-images.githubusercontent.com/36916831/74217819-d2054980-4ca8-11ea-957d-26d7867c3da3.png)

 @danpejobo can you paste here that expression? Also table structure could be important.

**Comment by m-kuhn** [comment]
I guess it's important to have an attribute form open.
The docked attribute table currently hidden form view in the screenshot could be enough.

**Comment by danpejobo** [comment]
@gioman I dont think it is directly related to the expression shown in the picture, since it crashes every time i deactivate the "apply default value", even if it is for another field, then the one i edited.
##### Expression in picture above
```
CASE WHEN "Borserie" IS NULL THEN lpad(to_string("BorID"),3,'0') 
ELSE"BORSERIE"||'_'|| lpad(to_string("BorID"),3,'0')
END
```
@m-kuhn I think you are onto something!

It seems to ONLY crash when you have the attribute table open! Crashes both docked and not docked.

**Comment by danpejobo** [comment]
**How to Reproduce**
1. add a feature to a point scratch layer
2. leave the attribute table open
3 enter layer properties
4. apply/deactivate "apply default value"
5. Crash

Didn't need to edit the feature.

**Comment by danpejobo** [comment]
I think the important detail is to have the attribute table open.

It crashes for me as long as i have the attribute table open and change something in the layer properties.
1. tried to add "not null" under constraints to the "Dato" field. Crashed.
2. tried to add "not null" under constraints to the "x" field. Crashed.

**Comment by danpejobo** [comment]
I tried with a new project, and could not make it crash.... i guess then there is something with the project?

**Comment by gioman** [comment]
> i guess then there is something wrong with the project?

@danpejobo unless you can share the full project is hard to say.

**Comment by elpaso** [comment]
That's why it's always recommended to share a project together with the data to reproduce an issue. There might be subtle differences in the project options.

**Comment by danpejobo** [comment]
@gioman @elpaso I can share the project

[Borplan_V1.0.qgs.zip](https://github.com/qgis/QGIS/files/4191153/Borplan_V1.0.qgs.zip)

**Comment by gioman** [comment]
> @gioman @elpaso I can share the project

@danpejobo thanks, no crashes here following the same exact steps in your initial report.

**Comment by danpejobo** [comment]
> > @gioman @elpaso I can share the project
> 
> @danpejobo thanks, no crashes here following the same exact steps in your initial report.

can you try with this approach?

> **How to Reproduce**
> 
> 1. add a feature to a point scratch layer
> 2. leave the attribute table open
> 3. enter layer properties
> 4. apply/deactivate "apply default value"
> 5. Crash
> 
> Didn't need to edit the feature.

**Comment by gioman** [comment]
> **How to Reproduce**
> 
>     1. add a feature to a point scratch layer
> 
>     2. leave the attribute table open
> 
>     3. enter layer properties
> 
>     4. apply/deactivate "apply default value"
> 
>     5. Crash

@danpejobo that's it, confirmed.

**Comment by danpejobo** [comment]
**detail**
> I think the important detail is to have the attribute table open.
> 
> It crashes for me as long as i have the attribute table open and change something in the layer properties.
> 
> 1. tried to add "not null" under constraints to the "Dato" field. Crashed.
> 2. tried to add "not null" under constraints to the "x" field. Crashed.
