### ISSUE TITLE
"No default style was found" when using some languages

### ISSUE THREAD

**Issue by matjash** [qgis/QGIS#34405]
When trying to Restore default style:
Layer properties -> Style -> Restore dfault style
I get the error: "No default style was found for this layer"

This seems to be connected to language settings. When i change to "override system locale" and select english, default style gets restored correctly.

I get same issue for PostGIS layers as well as Geopackage layers. 
Tested in QGIS 3.10.2 and 3.4.12

**Comment by gioman** [comment]
> This seems to be connected to language settings. When i change to "override system locale" and select english, default style gets restored correctly.

@matjash cannot confirm using for example Portuguese. What is your QGIS language? And what is your OS?

**Comment by matjash** [comment]
Windows 7 and 10. 
It seems to be connected to some languages only. I tried French, Portuguese, Italian which works. With  German, Slovene, Dansk i get "No default style was found for this layer" message..

**Comment by Pedro-Murteira** [comment]
@matjash I can't replicate this issue, are you still having this problem? (Tested on QGIS 3.16.15 and 3.22.2.)

**Comment by matjash** [comment]
QGIS versions 3.16.15 and 3.22.2 seem to be without this problem.
