### ISSUE TITLE
Add drag & drop raster file function to Georeferencer GDAL plugin.

### ISSUE THREAD

**Issue by MrChebur** [qgis/QGIS#34418]
**Feature description.**
It would be convenient to add raster files to the Georeferencer GDAL plugin using the drag & drop
 function. At the moment, there is no such possibility.

**Additional context**
![drag   drop does not work](https://user-images.githubusercontent.com/20655102/74304409-ba989000-4d7e-11ea-9b4b-f074b3fee63c.gif)

**Comment by roya0045** [comment]
@nirvn it didn't link the PR as a fix, will need to be closed manually.

**Comment by MrChebur** [comment]
@nirvn Thanks a lot for your work! Closed.
