### ISSUE TITLE
Error when trying to save FGDB - (The user does not have permission to execute the operation.)

### ISSUE THREAD

**Issue by diego-teixeira** [qgis/QGIS#34412]
**Describe the bug**

Hello, I did the advanced installation of QGIS by OSGEO4W, in order to be able to edit Arcgis feature classes (File Geodatabase -FGDB), but when trying to save changes to the table, the following message appears: "Failed updating row (The user does not have permission to execute the operation.) "or if you try to save edits (in the case of dividing) in the geometry this message appears:" Failed at writing Row to Table in CreateFeature. (The user does not have permission to execute the operation.) ".
Does anyone know how I can fix this problem?

Note: I'm sorry for any mistakes, but I don't speak English.

**How to Reproduce**

- >Import FileGDB
1. Go to Layer/add Layer
2. Click on Add Vector Layer (CRTL+SHIFT+V)
3. Choose Directory format
4. Choose ESRI FileGDB type
5. Search for FileGDB
6. Click the add button
7. Select Layers
8. Click the OK button
9. Click the Close button

- >To edit table
1. Open the Talhoes table
2. Click toggle editing (pencil)
3. Change the attribute of any field
4. Save the edit (floppy)

**QGIS and OS versions**

QGIS: 10.10.2
GDAL/OGR: 3.0.3/3.0.4
SO: Windows 10.0

FileGDB:
[J12__04_11_2013.gdb.zip](https://github.com/qgis/QGIS/files/4187336/J12__04_11_2013.gdb.zip)

**Comment by gioman** [comment]
@diego-teixeira can you attach/link the FGDB?

**Comment by diego-teixeira** [comment]
> @diego-teixeira can you attach/link the FGDB?

@gioman add the FileGDB, thanks

**Comment by gioman** [comment]
> @gioman add the FileGDB, thanks

@diego-teixeira no file attached/linked.

**Comment by diego-teixeira** [comment]
> > @gioman add the FileGDB, thanks
> 
> @diego-teixeira no file attached/linked.


I attached it to the main message so as not to get lost, does it appear to you?

**Comment by gioman** [comment]
> I attached it to the main message so as not to get lost, does it appear to you?

@diego-teixeira this seems to be very specific to the sample you attached. If I download a random sample dataset in FCDB i.e. https://www.arcgis.com/home/item.html?id=7a2631a5dff54bf3af77b6a7d223632a this does not happen.

It would be important/interesting know how your FGDB was created (for instance the ArcGIS version): hopefully ESRI didn't changed something in their format breaking compatibility with their own "free" FCGB API.

**Comment by diego-teixeira** [comment]
> > Anexei-o à mensagem principal para não se perder, parece-lhe?
> 
> @ diego-teixeira, isso parece ser muito específico para a amostra que você anexou. Se eu baixar um conjunto de dados de amostra aleatória no FCDB, por exemplo, [https://www.arcgis.com/home/item.html?id=7a2631a5dff54bf3af77b6a7d223632a,](https://www.arcgis.com/home/item.html?id=7a2631a5dff54bf3af77b6a7d223632a) isso não acontece.
> 
> Seria importante / interessante saber como o seu FGDB foi criado (por exemplo, a versão ArcGIS): espero que a ESRI não tenha mudado algo em seu formato, quebrando a compatibilidade com sua própria API FCGB "gratuita".



> > I attached it to the main message so as not to get lost, does it appear to you?
> 
> @diego-teixeira this seems to be very specific to the sample you attached. If I download a random sample dataset in FCDB i.e. https://www.arcgis.com/home/item.html?id=7a2631a5dff54bf3af77b6a7d223632a this does not happen.
> 
> It would be important/interesting know how your FGDB was created (for instance the ArcGIS version): hopefully ESRI didn't changed something in their format breaking compatibility with their own "free" FCGB API.

@gioman, it was created in Arcmap 10.5. I don't know if I'm right, but it seems to me that the problem occurs when there is a relationship in the feature class (in this case: Talhões -> TalhõesAnno)

**Comment by gioman** [comment]
> @gioman, it was created in Arcmap 10.5. I don't know if I'm right, but it seems to me that the problem occurs when there is a relationship in the feature class (in this case: Talhões -> TalhõesAnno)

@diego-teixeira try save the fdgb without relations and try again. I don't think anyway that there is a QGIS issue here. QGIS uses GDAL/OGR to read/write this format (with an open source driver or with a driver based on ESRI api) and if there is an issue in writing this type of FGDB this should be reported to GDAL/OGR.

**Comment by nyalldawson** [comment]
> QGIS uses GDAL/OGR to read/write this format (with an open source driver or with a driver based on ESRI api) and if there is an issue in writing this type of FGDB this should be reported to GDAL/OGR.

In this case it **must*8 be using the ESRI SDK based driver, because the open-source one doesn't support editing. So it's likely a bug in the (closed-source) SDK itself...

**Comment by gioman** [comment]
@diego-teixeira so as Nyall said, closing as this seems to be an upstream issue (or limit) in https://github.com/Esri/file-geodatabase-api 

@rouault please step in and correct me if I said something stupid.

**Comment by diego-teixeira** [comment]
Thanks to everyone, sorry to answer just now, but yesterday I had no access.
I will do as @gioman suggested, and I will report to GDAL / OGR. When I have an answer, I will update that message to help those who visit the topic. God bless them.

**Comment by SavelevGeo** [comment]
In my case the problem occured after I had added a topology to the database and the Feautre class I was trying to edit participated it it. After deleting the topology from Feature Dataset, everything came back to normal
