### ISSUE TITLE
'creating a relation sets wrong expression in "display expression" and breaks the "select features by value" functionality

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#34410]
I created a `1:m` relationship between two polygonal vector layers (_I attach data and project_), 

![image](https://user-images.githubusercontent.com/7631137/74253090-e9ffbc00-4cee-11ea-82db-64aa14af8914.png)

doing a search by value using the **F3** function key (selection by value / select feature) on the parent layer, I get a red error message.

```
The relationship is invalid. Check that the relationship definitions are correct
```

![image](https://user-images.githubusercontent.com/7631137/74253674-ab1e3600-4cef-11ea-935c-1e892e1f33ff.png)

and strange, because the **COD_REG** field is `NULL`

In reality, the relationship is correct because by opening the attribute table (parent layer) in module mode, everything works well:

![image](https://user-images.githubusercontent.com/7631137/74253340-3d720a00-4cef-11ea-9a22-184b4610f312.png)

---

## DATA AND PROJECT

[BUG_selectbyrelationship.zip](https://github.com/qgis/QGIS/files/4186674/BUG_selectbyrelationship.zip)

---

## the problem occurs in QGIS 3.4.15, 3.10.2-2 and master ` with clean profile !!!`

---

```
Versione di QGIS 3.10.2-A Coruña
Revisione codice QGIS d4cd3cfe5a
Compilato con Qt 5.11.2 
Esecuzione con Qt 5.11.2
Compilato con GDAL/OGR 3.0.3
Esecuzione con GDAL/OGR 3.0.4
Compilato con GEOS 3.8.0-CAPI-1.13.1
Esecuzione con GEOS 3.8.0-CAPI-1.13.1 
Compiled against SQLite 3.29.0
Running against SQLite 3.29.0
Versione client PostgreSQL 11.5
Versione SpatiaLite 4.3.0
Versione QWT 6.1.3
Versione QScintilla2 2.10.8
Compiled against PROJ 6.3.0
Running against PROJ Rel. 6.3.0, January 1st, 2020
OS Version Windows 10 (10.0)
```

### OSGeo4W64

**Comment by gioman** [comment]
@pigreco just a guess, but your expression

COALESCE( "DEN_REG", '<NULL>' )

in the "COD_REG" field of the child layer breaks the relation (you gets the region name where is the code). Then I'm not sure if the error is expected or not.

**Comment by pigreco** [comment]
@gioman 

> COALESCE ("DEN_REG", '')

it is not an expression written by me, it is the result of the creation of the relationship.

**Comment by gioman** [comment]
> it is not an expression written by me, it is the result of the creation of the relationship.

@pigreco 

funny thing, if I open your layers in clean project and create the relation using "COD_REG", then in the child layer properties the "display expression" for "COD_REG" is automatically set to

COD_RIP

which is of course different from

COALESCE ("DEN_REG", '')

I found in your project, but still wrong as has nothing to do with the fields used to create the relation (and breaks the "select features by value" dialog that is accessible by the F3 shortcut).


The subject of this ticket should be changed to something along the lines 'creating a relation sets wrong expression in "display expression" and breaks the  "select features by value" functionality'

**Comment by pigreco** [comment]
At this point I ask myself: is this something foreseen or not?

that is, the selection of features is foreseen starting from a one to many relationship, as described above ??

I remember that in the 2.x series it worked.

**Comment by gioman** [comment]
> At this point I ask myself: is this something foreseen or not?

@pigreco we should ask some relation guru, maybe @m-kuhn or @3nids can tell us what they think?

**Comment by ghtmtt** [comment]
Yep, same here. Setting up a standard 1:N relation (BTW: I always used these 2 layers for this kind of operation) caused some weird behavior:

1. Select Features By Value (F3) of the ``1`` part of the relation:

   ![immagine](https://user-images.githubusercontent.com/2884884/74350527-21856b80-4db6-11ea-8cc2-a436bb761004.png)

2. Standard form when the identification button is used (again, ``1`` side), works fine (also in the attribute table):
  
   ![immagine](https://user-images.githubusercontent.com/2884884/74350710-5f828f80-4db6-11ea-984d-06321426798a.png)

**Comment by pigreco** [comment]
IMHO it is important that the `M` side of the relationship works when using `F3`.
Put the case of having a table without geometry as a child layer, the selection of the father starting from the child is important

**Comment by pigreco** [comment]
@gioman 

>@pigreco we should ask some relation guru, maybe @m-kuhn or @3nids can tell us what they think?

no one knows this behavior well and therefore it is a bug for me, please is it possible to remove the `Feedback` label and put `high priority`?

**Comment by pigreco** [comment]
Is anyone willing to fix it ?? if yes, can you make a quote ??

**Comment by m-kuhn** [comment]
@3nids is this something on your todo list?

**Comment by 3nids** [comment]
I believe it was fixed here: https://github.com/qgis/QGIS/pull/35272
While quickly reading here, I am not 100% this is the correct approach but I think it's fixed by this.
I plan to work on relation reference next week, I can give it a deeper look by then.

**Comment by pigreco** [comment]
> I believe it was fixed here: #35272
> While quickly reading here, I am not 100% this is the correct approach but I think it's fixed by this.
> I plan to work on relation reference next week, I can give it a deeper look by then.

Using the data and project attached to this issue, the problem is always there.

**Comment by agiudiceandrea** [comment]
I've made the following test using the provided layers with QGIS 3.10.3-3 (standalone) on Windows:

- add the two layers in a new blank projet
- add the relationship (name: rel1; parent layer: Reg2011_WGS84; parent field: COD_REG; child layer: Prov2011_WGS84; child field: COD_REG; id: rel1; strength: Association)

then

- in the "Attribute Form" window of the Prov2011_WGS84 layer properties, selecting the COD_REG field in the Available Widgets tab I see the followng properties automatically set:
Widget Type: Relation Reference
Display Expression: COD_RIP
Relation: rel1 (...)
- the Select by value window for both layers show the error "The relation is not valid. Please make sure your relation definitions are OK."
![image](https://user-images.githubusercontent.com/16253859/77844799-cb278d00-71a9-11ea-94d7-4e66427a1f8b.png)

**Now, if I open the  the "Attribute Form" window of the Prov2011_WGS84 layer properties and I select the COD_REG field in the Available Widgets tab and than clicking the OK button without changing any property, then the error is not yet shown in the Select by value window for both layers**:
![image](https://user-images.githubusercontent.com/16253859/77844894-a253c780-71aa-11ea-8e23-2a4088d39b60.png)

Afteward, I can open the attribute table in form view of the Reg2011_WGS84 layer and change the column preview of both parent and child layers to DEN_REG and DEN_PROV respectively
![image](https://user-images.githubusercontent.com/16253859/77845473-8bfc3a80-71af-11ea-9ee5-f1da0fb60ef4.png)

Now the Display Expression property of the COD_REG field n the Prov2011_WGS84 layer attirbute form proerties windows results automatically set to the value `COALESCE( "DEN_REG", '<NULL>' )`
![image](https://user-images.githubusercontent.com/16253859/77845573-3a07e480-71b0-11ea-9d7e-7af8438b41e6.png)

**Comment by agiudiceandrea** [comment]
So, using the provided project, **if I open the the "Attribute Form" window of the Prov2011_WGS84 layer properties and I select the COD_REG field in the Available Widgets tab and than clicking the OK button without changing any property, then the error is not yet shown in the Select by value window for both layers**
![image](https://user-images.githubusercontent.com/16253859/77845645-cf0add80-71b0-11ea-9acd-2c6889b6b40a.png)

**Comment by pigreco** [comment]
@agiudiceandrea 

> but **if I subsequently open the "Attribute Form" window of the Prov2011_WGS84 layer properties and I select the COD_REG field in the Available Widgets tab and than clicking the OK button without changing any property, then the error is not anymore shown in the Select by value window for both layers**

confirm

**Comment by agiudiceandrea** [comment]
Another test:
- in a new black project add the two provided layer
- open the Prov2011_WGS84 layer properties windows and then (whatever tab is selected, e.g. the Information tab) click the OK button without changing anything
- add the relationship as previously specified (name: rel1; parent layer: Reg2011_WGS84; parent field: COD_REG; child layer: Prov2011_WGS84; child field: COD_REG; id: rel1; strength: Association)

No error is shown in the Select by value window for both layers.

Moreover, now in the "Attribute Form" window of the Prov2011_WGS84 layer properties, selecting the COD_REG field in the Available Widgets tab I see that the Widget Type property is Text Edit (unlike the previous test, when the Widget Type property was automatically set to "Relation Reference" after the relationship was added).

The same strange behaviours happen in both 3.10.3 and 3.4.5 on my Windows system.

**Comment by pigreco** [comment]
> Moreover, now in the "Attribute Form" window of the Prov2011_WGS84 layer properties, selecting the COD_REG field in the Available Widgets tab I see that the Widget Type property is Text Edit (unlike the previous test, when the Widget Type property was automatically set to "Relation Reference" after the relationship was added).
> 
> The same strange behaviours happen in both 3.10.4

confirm 

OSGeo4W64 Win 10

**Comment by pigreco** [comment]
Please, if you need to make a fundraiser say it explicitly. thanks

**Comment by gioman** [comment]
> Please, if you need to make a fundraiser say it explicitly. thanks

@pigreco see https://github.com/qgis/QGIS/issues/35016#issuecomment-641176040

**Comment by 3nids** [comment]
see https://github.com/qgis/QGIS/pull/37137
