### ISSUE TITLE
QGIS 3.4 crashes when using the Plugin dialog

### ISSUE THREAD

**Issue by lifa-lin** [qgis/QGIS#34421]
I had both the 64 and 32 bit versions of 3.4.9 installed. And the 64 bit worked almost flawlessly.

I then installed the 32 bit version of 3.4.15, and now both versions crash whenever I open the plugin admin dialog, and click on any (!) plugin to see its description. No plugins are loaded, and it crashes every single time.

I also have 3.10.2 64 bit installed, and it doesn't crash like the 3.4's.

Here's a screen dump of the crash in the 3.4.15 32 bit showing a very minimal stack trace:
![2020-02-12 07_59_55-Start](https://user-images.githubusercontent.com/37143389/74312141-62a75c80-4d71-11ea-9f88-472744d0aec5.png)

Running it all on Windows 10 version 1903.

**Comment by gioman** [comment]
@lifa-lin you seems to have a lot of QGIS installation in your machine, does it happens if you install 3.4.15 32 bit on a clean pc?

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
