### ISSUE TITLE
QGIS 3.10 crashes when I try to export images of resolution more than 1200 dpi

### ISSUE THREAD

**Issue by kk54321** [qgis/QGIS#34429]
This is the problem report: 
Crash ID: 99c2e47bff5c445dac61245978f40408db8a87df

Stack Trace

memcpy memcpy.asm:135
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QRasterPaintEngine::rasterBuffer :
QRasterPaintEngine::rasterBuffer :
QRasterPaintEngine::fill :
QPaintEngineEx::draw :
QPaintEngineEx::drawPath :
QgsFillSymbolLayer::_renderPolygon :
QgsSimpleFillSymbolLayer::renderPolygon :
QgsFillSymbol::renderPolygonUsingLayer :
QgsFillSymbol::renderPolygon :
QgsLayoutItemPage::draw :
QgsLayoutItem::paint :
QGraphicsScene::dragMoveEvent :
QGraphicsItem::dragMoveEvent :
QGraphicsEffectSource::draw :
QgsLayoutEffect::draw :
QGraphicsScene::drawItems :
QGraphicsScene::drawItems :
QGraphicsScene::render :
QgsLayoutExporter::renderRegion :
QgsLayoutExporter::renderRegionToImage :
QgsLayoutExporter::renderPageToImage :
QgsLayoutExporter::createImage :
QgsLayoutExporter::exportToImage :
QgisAppInterface::actionFeatureAction :
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.10.0-A Coru�a
QGIS code revision: 6ffa89eb3e
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.10586

**Comment by gioman** [comment]
>  QGIS Version: 3.10.0-A Coru�a

just to be sure please try after upgrading to 3.10.2

If the problem persist try a new QGIS profile. 

If still persist you may want to watch memory consumption on your machine while you are attempting export that image.

**Comment by nyalldawson** [comment]
This is an upstream qt issue, fixed in qt 5.13

**Comment by kk54321** [comment]
> > QGIS Version: 3.10.0-A Coru�a
> 
> just to be sure please try after upgrading to 3.10.2
> 
> If the problem persist try a new QGIS profile.
> 
> If still persist you may want to watch memory consumption on your machine while you are attempting export that image.

My Memory is it 68% and GIS is using 1.5GB (Have 8Gb Ram)
See This:
Crash ID: 7b6def937167ccc1e9bbaf099dae4d8d0ffa8ac3


Stack Trace


memcpy memcpy.asm:135
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QRasterPaintEngine::rasterBuffer :
QRasterPaintEngine::rasterBuffer :
QRasterPaintEngine::fill :
QPaintEngineEx::draw :
QPaintEngineEx::drawPath :
QgsFillSymbolLayer::_renderPolygon qgssymbollayer.cpp:740
QgsSimpleFillSymbolLayer::renderPolygon qgsfillsymbollayer.cpp:286
QgsFillSymbol::renderPolygonUsingLayer qgssymbol.cpp:2038
QgsFillSymbol::renderPolygon qgssymbol.cpp:1993
QgsLayoutItemPage::draw qgslayoutitempage.cpp:286
QgsLayoutItem::paint qgslayoutitem.cpp:411
QGraphicsScene::dragMoveEvent :
QGraphicsItem::dragMoveEvent :
QGraphicsEffectSource::draw :
QgsLayoutEffect::draw qgslayouteffect.cpp:33
QGraphicsScene::drawItems :
QGraphicsScene::drawItems :
QGraphicsScene::render :
QgsLayoutExporter::renderRegion qgslayoutexporter.cpp:261
QgsLayoutExporter::renderRegionToImage qgslayoutexporter.cpp:300
QgsLayoutExporter::renderPageToImage qgslayoutexporter.cpp:207
QgsLayoutExporter::createImage qgslayoutexporter.cpp:1922
QgsLayoutExporter::exportToImage qgslayoutexporter.cpp:411
QgsLayoutDesignerDialog::exportToRaster qgslayoutdesignerdialog.cpp:2070
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1598
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.10.2-A Coru�a
QGIS code revision: d4cd3cfe5a
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.3
Running against GDAL: 3.0.3



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.10586

**Comment by kk54321** [comment]
I'm Sorry. RAM was maxed out so it was having issues.
