### ISSUE TITLE
Vector Menu bar inactive

### ISSUE THREAD

**Issue by GinaWS7** [qgis/QGIS#34427]
**Describe the bug**

I have installed an uninstalled QGIS 3.4 Madeira on my computer, but the Vector function on the Menu bar remains dysfunctional. If I click on it, there is no dropdown menu. There is however a dropdown menu for all other functions on the Menu bar. I have seen this on one other computer as well.
In QGIS 2.14 Essen this function is active on my computer.

**How to Reproduce**

**QGIS and OS versions**
Version 3.4 Madeira long term release

**Additional context**

My computer is a Dell laptop and I am using Windows 10 and my machine is 64bit.

**Comment by DelazJ** [comment]
Hi @GinaWS7 
Do you have the Processing plugin enabled (in Plugins --> Manage and Install plugins)?
If you are using a locale different from English, isn't there a translated "vector" menu at the end of the menus bar?

**Comment by alexbruy** [comment]
Closing for the lack of feedback. Please reopen if necessary.
