### ISSUE TITLE
Don't works command "Copy Cell Content" (3.10.2-A Coruña)

### ISSUE THREAD

**Issue by dm-korottsev** [qgis/QGIS#34422]
Nothing happens when you click.

QGIS version
3.10.2-A Coruña
QGIS code revision
d4cd3cfe5a
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.3
Running against GDAL/OGR
3.0.3
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.0
Running against PROJ
Rel. 6.3.0, January 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
BoundingBox; 
d3datavis; 
EasyCustomLabeling; 
geocoder; 
GeoCoding; 
Hqgis; 
isolines; 
maplibrary; 
NNJoin; 
nominatim_locator_filter; 
pluginbuilder3; 
plugin_reloader; 
pst; 
QuickOSM; 
quick_map_services; 
realcentroid; 
SpreadsheetLayers; 
db_manager; 
MetaSearch; 
processing

**Comment by gioman** [comment]
@dm-korottsev actuallu what I see here (3.10.2 on Linux) is that it always copy the content of the first column, can you confirm?

**Comment by dm-korottsev** [comment]
Yes, I have the same thing. The data is copied not from the cell I click on, but from the first column (the same row). I recorded a video
https://yadi.sk/i/Urdurp-_jVOI6g

**Comment by elpaso** [comment]
Duplicate, already fixed: https://github.com/qgis/QGIS/pull/33797
