### ISSUE TITLE
Raster calculator turns one row of pixels into nodata

### ISSUE THREAD

**Issue by jratike80** [qgis/QGIS#34435]
Discussion with code examples and screenshots in https://gis.stackexchange.com/questions/349531/qgis-zonal-statistics-and-no-data/349559

Steps to re-produce with QGIS 3.11 Master on Windows 10.

1. Download https://s3.us-east-2.amazonaws.com/earthstatdata/FertilizerBalance_Geotiff.zip
2. Use file NitrogenBalanceOnLandscape_140Crops.tif (later "source")
3. Create a new GeoTIFF by applying the following raster calculator formula
`("source@1"<0) * "source@1"`
4. Open the result into QGIS. The southmost pixel row gets, in my environment, a nodata value of -3.40282347e+38. In the source image all those pixels are zeroes.
Clicked coordinate may be for example -27.239, -89.987

The issue happens for me when using the default, non-accelerated path. If I activate the OpenCL acceleration then the lowest pixel row is not changed into nodata.

**Comment by jratike80** [comment]
Discussion with code examples and screenshots in https://gis.stackexchange.com/questions/349531/qgis-zonal-statistics-and-no-data/349559

Steps to re-produce with QGIS 3.11 Master on Windows 10.

1. Download https://s3.us-east-2.amazonaws.com/earthstatdata/FertilizerBalance_Geotiff.zip
2. Use file NitrogenBalanceOnLandscape_140Crops.tif (later "source")
3. Create a new GeoTIFF by applying the following raster calculator formula
`("source@1"<0) * "source@1"`
4. Open the result into QGIS. The southmost pixel row gets, in my environment, a nodata value of -3.40282347e+38. In the source image all those pixels zeroes.
Clicked coordinate may be for example -27.239, -89.987

The issue happens for me when using the default, non-accelerated path. If I activate the OpenCL acceleration then the lowest pixel row is not changed into nodata.

**Comment by elpaso** [comment]
@jratike80 just to be sure, you are saying that when OpenCL acceleration is enabled everything works as expected and when OpenCL acceleration is **disabled** the bug appears?

It's usually the other way round :smile_cat:

**Comment by jratike80** [comment]
Yes, I am sure about that. Before the suggestion to test with OpenCL accelaration I did not even know that such thing exists so I was playing with all the defaults of vanilla QGIS-dev installation from OSGeo4W.

**Comment by elpaso** [comment]
This is very very tricky: there is a double precision rounding issue that calculates the wrong number of rows near the edges.

**Comment by t-oker** [comment]
Hi,

I have the same problem when I run the code below:

(("SAVI-trial@1" > 0.6875) *6.004)+(("SAVI-trial@1" <= 0.6875) * (ln((0.69-"SAVI-trial@1")/0.59)/-0.91))

Instead of accepting the value 6.004 where the pixel value is greater than 0.6875, the raster calculator instead returns no-data cells.

What is the work around this problem? I am using QGIS version 3.20.1-Odense.

Thank you,

Tobias
