### ISSUE TITLE
Have a home project directory in preferences

### ISSUE THREAD

**Issue by MPN-stack** [qgis/QGIS#34454]
**Feature description.**

The new implementation of these three dots menus in creation of shapes is very frustrating . With no home directory in preferences, the data can be inserted in all fields and an attempt to save without using the menu to set directory fails loosing data this is now taking me twice or three times as long to enter shapes into QGIS . making it a backward step in QGIS design. Please rethink your development although this is nice to be able to set the path . When creating 30 or morre shapes this becomes tiresome and if i could go back to previous version i would that didn't have this! Feature added.

The QGIS systembefore tehes updated seem to default to the systems home director this has now been changed on windows to C:/windows/system32 which gives an error of insufficient privaliges.

**Additional context**

![71f0f37e53bb211deb9124c4fc93be3a](https://user-images.githubusercontent.com/54211372/74439770-0f451500-4e2a-11ea-9178-f969319bf078.png)

There has been lots of cases of this error #34430 and #32801

I hope QGIS team recognises this is causing frustration and more operation to get same result as before.

**Comment by gioman** [comment]
@MPN-stack I know you won't like it, but if there is https://github.com/qgis/QGIS/issues/32801 already open this should be closed as duplicate.

**Comment by MPN-stack** [comment]
Not sure its a duplicate as if you already had this why has this provision not been put in place in the last update  the item you gave is not a feature request so is not similar the one you pointed to is a BUG.

**Comment by alexbruy** [comment]
I fail to see how this is different from #32801.

Also may I ask you to be more precise in you tickets (e.g. provide exact steps to reproduce, full names of the tools/menus, etc), probably it is only me, but I find all your tickets very cryptic and need to spend some time to guess what you are trying to say.

**Comment by gioman** [comment]
> I fail to see how this is different from #32801.

I agree. It does not matter if the other ticket is a bug report and this a feature request, it is borderline so I guess that both would fit anyway.

> Also may I ask you to be more precise in you tickets (e.g. provide exact steps to reproduce, full names of the tools/menus, etc), probably it is only me, but I find all your tickets very cryptic and need to spend some time to guess what you are trying to say.

I agree again. Please keep reporting what you think are valid bug reports and feature requests (but please first search the tracker for possible similar tickets) but I kindly ask to make them more readable and understandable (use the report template as much as you can). Thanks.
