### ISSUE TITLE
Critical error: "OpenType support missing"

### ISSUE THREAD

**Issue by kadarivan** [qgis/QGIS#34455]
**Describe the bug**
Open the Settings/Options window generates these error messages:
2020-02-13T16:04:42     CRITICAL    Qt : OpenType support missing for "MS Shell Dlg 2", script 11
2020-02-13T16:04:42     CRITICAL    Qt : OpenType support missing for "Arial", script 11
2020-02-13T16:04:42     CRITICAL    Qt : OpenType support missing for "MS UI Gothic", script 11
2020-02-13T16:04:42     CRITICAL    Qt : OpenType support missing for "SimSun", script 11

**How to Reproduce**
Open Settings->Options...

**QGIS and OS versions**
QGIS 3.10.2-15 new, clean profile:
QGIS version | 3.10.2-A Coruña | QGIS code revision | eb19089184
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.0dev | Running against GDAL/OGR | 3.1.0dev
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 7.0.0 | Running against PROJ | Rel. 7.0.0, March 1st, 2020
OS Version | Windows 10 (10.0) | This copy of QGIS writes debugging output.
Active python plugins | db_manager; MetaSearch; processing

QGIS 3.10.2-16 new, clean profile:
QGIS version | 3.10.2-A Coruña | QGIS code revision | a4c55fb0bb
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.0dev | Running against GDAL/OGR | 3.1.0dev
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 7.0.0 | Running against PROJ | Rel. 7.0.0, March 1st, 2020
OS Version | Windows 10 (10.0) | This copy of QGIS writes debugging output.
Active python plugins | db_manager; MetaSearch; processing

**Comment by kadarivan** [comment]
fixed in 3.10.2-20 


QGIS version | 3.10.2-A Coruña | QGIS code revision | cd85f38786
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.0dev | Running against GDAL/OGR | 3.1.0dev
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 7.0.0 | Running against PROJ | Rel. 7.0.0, March 1st, 2020
OS Version | Windows 10 (10.0) | This copy of QGIS writes debugging output.
Active python plugins | db_manager; MetaSearch; processing

**Comment by nitinpeshwani** [comment]
Can anyone give the solution regarding this issue.
