### ISSUE TITLE
Refactor fields algorithm - allow configuring a source layer

### ISSUE THREAD

**Issue by m-kuhn** [qgis/QGIS#34459]
When configuring a refactor fields algorithm, there is an expression builder available to help configuring the expression.
Within the expression builder, there are currently no fields available. In a perfect world, the available fields would be determined from the connected input. Introducing such a system might be nice but is quite complex and even then might not be able to be 100% completely reliable in every situation.

I would therefore propose a second layer combo box next to the current possibility to set the "target layer" where a "source layer" can be specified which is used in the expression builders. This helps not only to have the names of the fields available but also to get available values like code lists etc. from the source layer.

**Comment by nyalldawson** [comment]
Are you referring to models where the refactor fields config is exposed as an input?

**Comment by m-kuhn** [comment]
No. But directly applied on an input layer.

The situation in this case here is a change from an old model version to a new one.
A lot changed in field names, domains (before integer, now strings - or reclassification).

So the algorithm is:

Old vector features (input/source) -> refactor field -> New vector features (output/destination)

**Comment by nyalldawson** [comment]
So it's a modeler widget mode only change, right?

**Comment by m-kuhn** [comment]
I assume so

**Comment by alexbruy** [comment]
Same as #26493?

**Comment by m-kuhn** [comment]
Yes
