### ISSUE TITLE
relations bug: zoom to child button disappears

### ISSUE THREAD

**Issue by Luuffen** [qgis/QGIS#34477]
Windows 10 64 bit, QGIS 3.4.15
Testfile: testtest.zip (zipped geopackage)
Zooming to child does not work if parent table has no geometry(?). maybe bug because button dissapears.

**works** fine with two polygon files:

- polygon-shapefile, polygon-shapefile

- gpkg polygon-table, gpkg polygon-table

does **not work** for relation between table without geometry and table with geometry:

- geopackage (see attached file)

- spatialite

- polygon-shape and csv-table

Add relation in project properties. table with geometry is bound as a child to table without geometry:
![grafik](https://user-images.githubusercontent.com/49310583/74537885-3b9c8680-4f3b-11ea-9ae4-8ea8cba55da7.png)

Open attributetable of geometryless table in form-mode, all buttons are present, also for zooming in to child-features:
![grafik](https://user-images.githubusercontent.com/49310583/74537937-5a028200-4f3b-11ea-93c6-1dab72a9f3d5.png)

as soon as i try to select a child the button for zooming disappears:
![grafik](https://user-images.githubusercontent.com/49310583/74537993-72729c80-4f3b-11ea-8a8b-611a160ce64f.png)

[testtest.zip](https://github.com/qgis/QGIS/files/4204777/testtest.zip)

**Comment by Saijin-Naib** [comment]
Can confirm locally with a different dataset setup similarly.

**Comment by gioman** [comment]
I also happen on 3.10.2 when toggling editing for a child.

**Comment by 3nids** [comment]
I cannot reproduce on master.
Can you test again?

**Comment by gioman** [comment]
> I cannot reproduce on master.

@3nids the button does not disappear anymore, but should not be active too (it stays inactive)?

**Comment by 3nids** [comment]
it is active and working for me

**Comment by gioman** [comment]
> it is active and working for me

@3nids tested on the latest master using qgis.org's repos for Ubuntu 20.04.

**Comment by 3nids** [comment]
![ezgif-6-4726b3bc03c7](https://user-images.githubusercontent.com/127259/120799039-7ebea680-c53e-11eb-8e5d-e7c6db64df68.gif)

**Comment by 3nids** [comment]
am I missing something?

**Comment by gioman** [comment]
> am I missing something?

@3nids using the provided dataset:

![Peek 2021-06-04 13-24](https://user-images.githubusercontent.com/1951107/120800798-44eaa180-c538-11eb-979d-074792393d3e.gif)

**Comment by 3nids** [comment]
you need to select the items first with the yellow square.
but this could be well discussed that you shouldn't need to select (highlighting the feature should be enough)

**Comment by gioman** [comment]
> highlighting the feature should be enough

as user I would say yes, it should be enough.

**Comment by 3nids** [comment]
After looking a bit more:
While swithcing from selection to current feature would make sense, it does make less for the unlink and delete buttons, all of them working with the selection.
More over, there are other buttons at the end of the list to highlight/pan/zoom to currently edited feature:
![image](https://user-images.githubusercontent.com/127259/120969215-308deb00-c76a-11eb-91a0-4d01d7802ace.png)

I agree that they are far less visible and know (even me as creator forgot about them at start).
But I think it make sense to keep the coherence of using the selection in the toolbar.

As a minimal thing, we could rename the tooltips to emphase the fact that it works on selection.

What do you think?

**Comment by gioman** [comment]
> As a minimal thing, we could rename the tooltips to emphase the fact that it works on selection.

@3nids +1 for me.
