### ISSUE TITLE
was "update preview (cache, rectangle, renderer)" removed from QGIS 3?

### ISSUE THREAD

**Issue by Forna73** [qgis/QGIS#34473]
In old 2.xx series when in map composer You made a map window, there was the possibility to view the actual map, or leave a simple rectangle to mark where the windows was and procede with other editing without waiting for the rendering in the window.

In the new layout I can't find this option and every map window I create it renders it and it takes quite a lot to let me procede with editing cause all is stacked!!!!

Is there a chance to leave the window without rendering? A sort of composer in "structure view".

**Comment by kadarivan** [comment]
You can create an empty Map Theme on the Layers Panel, and use it in the composer
![theme](https://user-images.githubusercontent.com/18245793/74531667-9a5b0380-4f2d-11ea-8e24-dd3abb6d2bad.png)

**Comment by Forna73** [comment]
Done, but doesn't work... it continues in rendering....

**Comment by roya0045** [comment]
You could simply add a shape or add a picture instead. I doubt this will be implemented.

**Comment by Forna73** [comment]
Sorry?!?
This feature was in Qgis 2.xx...
So there is any option to not view the content in window map... every time I zoom in or out or shift an object I must wait 2-3 minutes the render!!!! OMG
I think this is a regression in layout composer.

**Comment by kadarivan** [comment]
> Done, but doesn't work... it continues in rendering....
> I'm trying in Qgis 3.8.3...
> 
> is it a bug?

It's working for me (3.10) Did you disabled every layer before created the theme?

**Comment by Forna73** [comment]
You mean I Must disable all layer from the canvas to create an empty theme to work at the layout? ...and then to enable all them back to print? mhmm....

**Comment by gioman** [comment]
>  I think this is a regression in layout composer.

@Forna73 https://gis.stackexchange.com/a/305631

**Comment by gioman** [comment]
It should have been removed from the manual...  https://docs.qgis.org/3.4/en/docs/user_manual/print_composer/composer_items/composer_map.html

**Comment by Forna73** [comment]
That's just what I was looking for...
However, even if it's written about a background thread, I'm having a lot of time waiting for render before I can do anything...
I know it's old but I've an i7 4790K @4.4Ghz with 32Gb ram in an SSD...
Forgive me, but I thnk that removing these options has not been a good idea.

**Comment by gioman** [comment]
> That's just what I was looking for...
>  I know it's old but I've an i7 4790K @4.4Ghz with 32Gb ram in an SSD...

I'm try to make the composer choke here on a 8 years old laptop, and I'm not able to (not saying that you are not hitting a use case that really causes troubles to QGIS).

Not sure but this is maybe related too the 

![Screenshot_20200215_225358](https://user-images.githubusercontent.com/1951107/74596352-0fb9f780-5046-11ea-927d-de785db2733c.png)

QGIS general config.

**Comment by gioman** [comment]
Anyway this must be closed. If you really have a use case that renders the composer barely usable please file a new bug ticket attaching the necessary project/data.

**Comment by Forna73** [comment]
Ok.... Understood... sorry for this post.

Il sab 15 feb 2020, 23:55 Giovanni Manghi <notifications@github.com> ha
scritto:
