### ISSUE TITLE
QGIS crashes when removing columns from a vector

### ISSUE THREAD

**Issue by verdicos-gcomstock** [qgis/QGIS#34478]
Crash ID: de8d4a69ab50a24dbef78411a70cd10dd1643da3

Stack Trace

memcpy_repmovs memcpy.asm:114
QgsVectorLayerFeatureIterator::updateChangedAttributes qgsvectorlayerfeatureiterator.cpp:1146
QgsVectorLayerFeatureIterator::fetchFeature qgsvectorlayerfeatureiterator.cpp:428
QgsAbstractFeatureIterator::nextFeature qgsfeatureiterator.cpp:63
QgsCachedFeatureWriterIterator::fetchFeature qgscachedfeatureiterator.cpp:141
QgsAbstractFeatureIterator::nextFeature qgsfeatureiterator.cpp:63
QgsAttributeTableModel::loadLayer qgsattributetablemodel.cpp:462
QMetaObject::activate :
QMetaObject::activate :
QgsVectorLayer::updateFields qgsvectorlayer.cpp:3620
QgsVectorLayerUndoCommandDeleteAttribute::redo qgsvectorlayerundocommand.cpp:416
QUndoStack::push :
QgsVectorLayerEditBuffer::deleteAttribute qgsvectorlayereditbuffer.cpp:302
QgsVectorLayer::deleteAttribute qgsvectorlayer.cpp:2971
QgsVectorLayer::deleteAttributes qgsvectorlayer.cpp:2985
QgsAttributeTableDialog::mActionRemoveAttribute_triggered qgsattributetabledialog.cpp:1068
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1598
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.10.2-A Coru�a
QGIS code revision: d4cd3cfe5a
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.3
Running against GDAL: 3.0.3

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
@verdicos-gcomstock please try with a new QGIS profile, no 3rd party plugins installed.

If the problem persist add detailed steps and a sample project + data.

**Comment by m-kuhn** [comment]
@verdicos-gcomstock which data provider is involved? Are you using spatialite data?
I.e. @elpaso a couple of hours ago solved a similar issue.

**Comment by verdicos-gcomstock** [comment]
I had a layer from MSSQL and a layer from an ESRI shapefile.

**Comment by gioman** [comment]
> I had a layer from MSSQL and a layer from an ESRI shapefile.

@verdicos-gcomstock what are the operations that lead to the crash > detailed steps please.

**Comment by verdicos-gcomstock** [comment]
1.  Imported MSSQL as Layer 1
  2.  Imported ESRI Shapefile as Layer 2
  3.  Fixed geometries from Layer 1
  4.  Used tool “Join Attributes by Location” to add attributes from Layer 2 to Layer 1
  5.  Edited joined layer to remove unwanted attribute columns.  I deleted about 4 attributes but when I tried to delete the 5th attribute it hung for about 10 minutes then received this exception.  Not sure if it matters but the attribute I was trying to remove that caused the hanging and ultimate exception was ogr_fid.

**Comment by roya0045** [comment]
@gioman its not even a join, its an output layer. Without knowing the output type its hard to know what is the issue and if this is reproducible.

**Comment by gioman** [comment]
> @gioman its not even a join, its an output layer. Without knowing the output type its hard to know what is the issue and if this is reproducible

@roya0045 agree @verdicos-gcomstock  can you leave further feedback? thanks.

**Comment by verdicos-gcomstock** [comment]
Sorry @gioman<https://github.com/gioman> and @roya0045<https://github.com/roya0045>, I cannot give additional information, this happened once and it was quite some time ago so I don’t recall.

G

**Comment by gioman** [comment]
> Sorry @gioman<https://github.com/gioman> and @roya0045<https://github.com/roya0045>, I cannot give additional information, this happened once and it was quite some time ago so I don’t recall. G

@verdicos-gcomstock reopen if you find a consistent way to replicate.
