### ISSUE TITLE
QGIS crash on opening geopackage image

### ISSUE THREAD

**Issue by grantboxer** [qgis/QGIS#34483]
## User Feedback

QGIS crashes on opening an image from a GeoPackage file into a blank project window

## Report Details

**Crash ID**: [3db21e41567a4fc788fa14670e61ec6fcf096af1]('https://github.com/qgis/QGIS/search?q=3db21e41567a4fc788fa14670e61ec6fcf096af1&type=Issues')

**Stack Trace**
<pre>
memcpy :
QgsRasterIdentifyResult::params :
QgsAbstractDatabaseProviderConnection::TableProperty::GeometryColumnType::operator== :
QgsSingleBandGrayRenderer::block :
QgsBrightnessContrastFilter::block :
QgsHueSaturationFilter::block :
QgsRasterResampleFilter::block :
QgsRasterProjector::block :
QgsRasterIterator::readNextRasterPartInternal :
QgsRasterDrawer::draw :
QgsRasterLayerRenderer::render :
QgsMapRendererParallelJob::renderLayerStatic :
QgsMapRendererParallelJob::renderingFinished :
QgsImageOperation::overlayColor :
QgsImageOperation::flipImage :
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.2-A Coru�a
QGIS code revision: d4cd3cfe5a
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.3
Running against GDAL: 3.0.3

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment]
@grantboxer please attach/link the dataset.

**Comment by grantboxer** [comment]
Hi Giovanni,

 

Please see attached link https://www.dropbox.com/s/5y7bx98z5btf88u/Argyle_Data.gpkg?dl=0 to download the Geopackage file. It is about 450 Mb and contains vector and raster satellite data from over the Argyle diamond mine area in northern Western Australia. Please let me know if you would like any further info!

 

Cheers Grant

 

Grant Boxer

Consultant Geologist (FAIG R.P. Geo)

Perth, Western Australia

Email: boxerg@iinet.net.au <mailto:boxerg@iinet.net.au> 

Mobile: 0418 954 059

Skype: grantboxer

Website: www.iinet.net.au/~gboxer <http://www.iinet.net.au/~gboxer>

**Comment by gioman** [comment]
> Please let me know if you would like any further info!

@grantboxer thanks! what is the name of the layer that causes troubles?

**Comment by grantboxer** [comment]
All I did was make a new project to clear the map, then I dragged the B02 image into the map window and QGIS crashed.

 

I seem to be having problems with 3.10.2 with regards to projections and files produced in older versions of QGIS. When I bring them in they cannot see the old original projection information. The prj files are the same but the qpj files are slightly different. Not sure if this is causing a problem.

 

Cheers Grant

**Comment by gioman** [comment]
> All I did was make a new project to clear the map, then I dragged the B02 image into the map window and QGIS crashed.

@grantboxer I just tested on

3.10.2 on Linux

3.10.2/master on windows

loading all the vector and raster data in the gpkg, no crashes.

**Comment by grantboxer** [comment]
It loads no problem using version 3.4 and 3.8, so it seems to be a problem with 3.10.2?

 

Cheers Grant

**Comment by gioman** [comment]
> so it seems to be a problem with 3.10.2?

maybe, but no crashes here on 3.10.2 on Linux and Windows.

**Comment by grantboxer** [comment]
Of course! Some of these problems seem to be machine dependant, and I would say probably difficult to track down. I also tried the OSGeo4W version and this also crashed.

 

Any other suggestions – try a new profile perhaps?

 

Cheers Grant

**Comment by gioman** [comment]
> Any other suggestions – try a new profile perhaps?

@grantboxer that is always a good start.

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
