### ISSUE TITLE
QGIS crash just by starting

### ISSUE THREAD

**Issue by juan-masson** [qgis/QGIS#34481]
Hello,

it is my first time reporting an issue. I have just created an account in Github for this.

I tried to load an Open Street Map layer in a just created empty project in QGIS under the application of GISWATER.
QGIS did not respond for a long time and i have closed the programm. After 2 minutes i have tried to start it again but i receive the following message.

Crash ID: 7c8e619fd720186396d695bd0a01590b46444c3e

Stack Trace

operatoroperatorQMetaType::save :
QVariant::save :
operatorQSettings::value :
QSettings::value :
QSettings::sync :
QThreadPool::maxThreadCount :
QSettings::~QSettings :
QSettings::`scalar deleting destructor' :
QgsSettings::~QgsSettings qgssettings.cpp:83
QgsNewsFeedParser::onFetch qgsnewsfeedparser.cpp:169
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QCoreApplication::processEvents :
QgisApp::QgisApp qgisapp.cpp:1202
main main.cpp:1344
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.10.2-A Coru�a
QGIS code revision: d4cd3cfe5a
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.3
Running against GDAL: 3.0.3

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

Could you please give me some advice where the problem may be?

Thanks in advance.
Best regards
Juan Masson

**Comment by gioman** [comment]
>  under the application of GISWATER

@juan-masson what is this? a QGIS plugin? a standalone application based on QGIS?

**Comment by juan-masson** [comment]
GISWATER ist a programm based on QGIS. An open source related to water supply and wastewater networks for hydraulic calculation wich use QGIS as standar interface.
You can load it as an extension.

**Comment by gioman** [comment]
@juan-masson if the problem is caused by this extension you must report it to the extension author/s. Please try again using QGIS after having removed (not just disabled) this extension.

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.

**Comment by junior128** [comment]
Hola me pasa lo mismo, lograste solucionarlo, incluso reinstale el Qgis y me sale el mismo error
