### ISSUE TITLE
Usability: Avoid running a Processing algorithm twice by accident

### ISSUE THREAD

**Issue by gacarrillor** [qgis/QGIS#34484]
**Feature description.**
After you run a Processing algorithm, the `Log` tab is visible and the `Run` button is enabled, so you can run the algorithm again with a single click. From a user perspective, it shouldn't be the case. If you want to run the algorithm again, you could at least have a look at the `Parameters` tab once more.

**1st proposal**
1. Run the algorithm.
2. Disable `Run` button.
3. Enable `Run` button as soon as the user activates the `Parameters` tab.

![1st_proposal](https://user-images.githubusercontent.com/652785/74596277-fea7c100-501a-11ea-9473-23bf5d4e099a.gif)

**2nd proposal**

Only run if `Parameters` tab is active. That is, avoid running the algorithm if `Log` tab is active.

![2nd_proposal](https://user-images.githubusercontent.com/652785/74596540-bd191500-501e-11ea-805a-e59a927f393e.gif)

**3rd proposal**
1. Run the algorithm.
2. Change `Run` button by `Prepare next run` button.
3. A click on `Prepare next run` button activates `Parameters` tab, which changes `Prepare next run` button by `Run` button. 

![3rd_proposal](https://user-images.githubusercontent.com/652785/74597089-e2118600-5026-11ea-96dd-140071385212.gif)

----------------------------------------
Let me know which one you all prefer, then I'll create a PR. I prefer the 2nd proposal. 
If you have another idea, please comment it.

*Note: I didn't write a QEP because this is a minor change in UI.*

**Comment by m-kuhn** [comment]
I like the proposals.
I like the last proposal best but I'm not completely convinced of the label. Maybe just "Change parameters" but also not completely convincing.

**Comment by roya0045** [comment]
Wouldn't it be simpler to add a timer of a few seconds before enabling again?
 No need to fiddle and to find the magic combination to enable the run again.

**Comment by gacarrillor** [comment]
> Wouldn't it be simpler to add a timer of a few seconds before enabling again?
> No need to fiddle and to find the magic combination to enable the run again.

In that sense, the 3rd proposal is better. There is no magic and a click on the button is required (but clear enough) for running an algorithm twice.

**Comment by roya0045** [comment]
@gacarrillor you could say so, though I don't think activating the parameter tab is needed in this case.

**Comment by gacarrillor** [comment]
Let's wait for other opinions.

**Comment by nyalldawson** [comment]
+1 for option 1 or 2. @nirvn?

**Comment by j-lippmann** [comment]
+1 for 2

**Comment by j-lippmann** [comment]
Additional: sometimes i wish i could minimize or Dock the algorithm window 😀

**Comment by roya0045** [comment]
This might just be me but if 1 or 2 is implemented, some people will think that the algorithm break after one run and will close and open it again as having to check the param to re enable something seem to be unintuitive and obscure to guess.

**Comment by gacarrillor** [comment]
Votes so far:

Option 1:    **1** (ND)
Option 2:    **3** (ND, JL, GC)
Option 3:    **1** (MK)

**Comment by m-kuhn** [comment]
My vote goes to "Run again with different parameters" in Option 3.
I think this is more explicit and visible than as a side effect of reactivating the parameters tab. But I can live with any of the proposals.

**Comment by roya0045** [comment]
I think it would be a good idea to ask @nirvn and on the user mailing list.

**Comment by jgrocha** [comment]
+1 for option 2

**Comment by gacarrillor** [comment]
Votes so far:

Option 1: **1** (ND)
Option 2: **4** (ND, JL, JGR, GC)
Option 3: **1** (MK)

----------------
@m-kuhn, would adding an explanatory tooltip to the disabled button help?

**Comment by 3nids** [comment]
I'd vote for 3 also, for the same reasons than Matthias, being it's the most explicit behavior to me.

**Comment by andreasneumann** [comment]
+1 for Option 3

**Comment by m-kuhn** [comment]
@gacarrillor if option 2, is the one which wins, a tooltip button would be appreciated. (for the record, I can very well live with option 2 too)

**Comment by roya0045** [comment]
@gacarrillor to be explicit, option 3 gets my vote as its the one that is more clear and will generate less bug reports due to a new hidden behaviour.

**Comment by gacarrillor** [comment]
We've got a tie! 
Votes so far: 

Option 1: **1** (ND)
Option 2: **4** (ND, JL, JGR, GC)
Option 3: **4** (MK, DR, AN, R45)

**Comment by nyalldawson** [comment]
Happy to change my vote to 4, my only concern is that the button label needs to be sufficiently concise . I.e. "Change Parameters" would be ok, "Rerun with Different Parameters" is too long.

**Comment by gacarrillor** [comment]
You mean to 3. Yes, I'm fine with any option. Option 3 is more appropriate for guiding users, so, let's declare it as the winner!

Now, I'd ask you and people who voted for option 3, to help me find the best button text:

Option A: **Prepare Next Run**
Option B: **Change Parameters**
Option C: **Rerun with Different Parameters**
Option D: ?

-----------------
@m-kuhn, @3nids, @andreasneumann, @roya0045 and @nyalldawson: please vote again, and if you have another suggestion for the button text, just let me know.

**Comment by nyalldawson** [comment]
Option B

**Comment by nyalldawson** [comment]
(with a nice tooltip)

**Comment by m-kuhn** [comment]
Agreed, B with tooltoip :+1:

**Comment by roya0045** [comment]
Maybe not change but "Validate Parameters", I would assume that using change directly would be akin to asking the user to change or fix his parameters, whereas it might not be needed.

**Comment by gacarrillor** [comment]
Implemented in PR #34928.

For consistency and to make things simple, I ended up mixing options 3 (the winner) and 2 (good amount of votes). That means, the Change Parameters button is shown after an algorithm execution, but also, you cannot run an algorithm from the Log tab, it should be done from the Parameters tab. 

Let me know if you think the tooltip is still necessary, and if so, which could be its text.

**Comment by alexbruy** [comment]
I'm -1 with disabling "Parameters" tab during algorithm execution. Why I can't take a look at the parameters while algorithm executes? What if I have multiple dialogs open and running and want to cancel some specific instance?

Also probably I'm late here, but from my point of view adding "Change parameters" button makes very little sense and clutter dialog. It is enough just to hide "Run" button when "Log" tab is active.

**Comment by m-kuhn** [comment]
@alexbruy good points.

Can you specify for which approach you would like to vote?
It would be good to continue the structured approach started by @gacarrillor to eventually find a solution.

**Comment by alexbruy** [comment]
There is no option for my vote :-). Personally I don't think that ability to run algorithm from the Log tab is bad. And if I will be forced to vote, I'll be definitely against option 3 and will choose between 1 and 2, but will preffer to leave current implementation. As already mentioned when button disabled users might think that algorithm dialog now need to be closed and reopened to perform next run. I have always believed and continue to believe that users should *read* docs and labels on the contrlos and not clicking everywhere in hasle.

**Comment by m-kuhn** [comment]
In this case I'd like to ask you to vote for 1 or 2.
Or convince 4 others that the current situation is better ;)

**Comment by alexbruy** [comment]
Let's not create yet another stalemate here. I only shared my humble opinion and can live with currently adopted approach (especially as I'm probably only one who does not see any issues with current implementation). And if it will bug me a lot I always can apply a patch.

But if you want a bit more lengthy discussion, my vote goes for option 2.

**Comment by m-kuhn** [comment]
Thanks @alexbruy !!

**Comment by gacarrillor** [comment]
For the record, final count (Nyall changed vote to option 3): 

Option 1 --> 0 votes 
Option 2 --> 4 votes (JL, JGR, GC, AB)
Option 3 --> 5 votes (MK, DR, AN, R45, ND)
