### ISSUE TITLE
QGIS unexpectedly ended

### ISSUE THREAD

**Issue by Piturnah** [qgis/QGIS#34485]
Crashed on startup and received a dialog with this info

QGIS Info
QGIS Version: 3.10.2-A Coru�a
QGIS code revision: d4cd3cfe5a
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

Crash ID: 761572ff52cc37427ef3dc86dcd25a465b3ecd97

Stack Trace

RtlSizeHeap :
sqlite3_blob_bytes :
sqlite3_blob_bytes :
sqlite3_blob_bytes :
sqlite3_database_unique_ptr::open qgssqliteutils.cpp:67
QgsUserProfile::alias qgsuserprofile.cpp:73
QgisApp::refreshProfileMenu qgisapp.cpp:2696
QgisApp::QgisApp qgisapp.cpp:974
main main.cpp:1344
BaseThreadInitThunk :
RtlUserThreadStart :

**Comment by gioman** [comment]
@Piturnah try removing (make a backup first if you have important stuff in there) manually the QGIS folder in your Windows user profile, then start QGIS again.

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
