### ISSUE TITLE
"automatically pan/zoom to the current feature" is broken

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#34486]
QGIS 3.10.2/master on Windows and Linux.

Open a attribute table in form view, then enable the "automatically pan to the current feature" or "automatically zoom to the current feature" and navigate the feature with the provided arrows.

No pan or zoom whatsoever.

![Peek 2020-02-16 19-46](https://user-images.githubusercontent.com/1951107/74611622-5f0b3100-50f5-11ea-8742-59c75c07c1ff.gif)

**Comment by 3nids** [comment]
I could not replicate with line or polygon layers, even with different CRSs between layer and canvas.
Can you share the project?

**Comment by gioman** [comment]
> I could not replicate with line or polygon layers, even with different CRSs between layer and canvas.
> Can you share the project?


@3nids found the culprit, is happens when 

![Screenshot_20200216_203237](https://user-images.githubusercontent.com/1951107/74612252-7e0cc180-50fb-11ea-890c-dbce4a96eb2b.png)

is selected rather than

![Screenshot_20200216_203306](https://user-images.githubusercontent.com/1951107/74612257-8bc24700-50fb-11ea-96f2-da98d4c8622e.png)

**Comment by 3nids** [comment]
Well this makes sense then, no? otherwise the list would be reduced to a single item on first change. What shall we do? I'd suggest to disable the pan/scale buttons.

**Comment by gioman** [comment]
> Well this makes sense then, no? otherwise the list would be reduced to a single item on first change. What shall we do? I'd suggest to disable the pan/scale buttons.

@3nids I see your point, but I don't think is a general one. I.e. in a (continuous) land use map, if I zoom to a feature I still very well get a map with quite a few surrounding polygons (around the zoomed one), polygons that user may very well to explore/zoom with the arrows. Same applies to pan/center. My opinion is to fix the functionality regardless of the option used in "attribute table behavior" in QGIS general options.

**Comment by nyalldawson** [comment]
@gioman but that would give essentially random behaviour - the first panned neighbour could be to the east, causing all the neighbours on the right to leave the map and disappear from the list. Then the next pan might take you north, south, or even back to the first polygon! I personally think these two options are logically mutually exclusive...

**Comment by gioman** [comment]
> @gioman but that would give essentially random behaviour - the first panned neighbour could be to the east, causing all the neighbours on the west to leave the map and disappear from the list. Then the next pan might take you north, south, or even back to the first polygon! I personally think these two options are logically mutually exclusive...

@nyalldawson if the user have labels on and/or a proper expression to show something significant,

![Screenshot_20200216_224054](https://user-images.githubusercontent.com/1951107/74614171-7f46ea00-510d-11ea-82a4-aab695ae488e.png)

than clicking on a specific item in the list of the form view can very well lead to focus/center exactly where is needed.

That said this is my opinion, at very least as Denis said this should be disabled in this specific case, but as user I'm -1 (of course it cannot stay as it is now).

**Comment by nyalldawson** [comment]
>than clicking on a specific item in the list of the form view can very well lead to focus/center exactly where is needed.

Right -- at which stage the list is refresh to only show the features NOW visible. So clicking next-next-next will lead you on a merry quasi-random path through potentially ALL the features in the layer, with no regard to the initially visible selection at all. That's why I think this combination of settings would be misleading/meaningless

**Comment by 3nids** [comment]
I'm with Nyall here.
I will disable the buttons and add a typehint to say why it's disabled.

**Comment by gioman** [comment]
@nyalldawson @3nids I was willingly to add here this morning an example where it made clearly sense, but I see you have already patched and maybe also merged. So be it (as you want).

**Comment by 3nids** [comment]
sorry the timing makes me want to decide quickly.
feel free to add any valuable info to the topic!

**Comment by uclaros** [comment]
Indeed it does not make much sense when navigating to the next - previous feature since it's kind of random. But it does make sense when navigating with the mouse. When moving to the clicked feature you have a full list of it's neighbors on witch you can click, move and repeat.

**Comment by gioman** [comment]
>  But it does make sense when navigating with the mouse. When moving to the clicked feature you have a full list of it's neighbors on witch you can click, move and repeat.

yes! my use case would be: what about if I have to inspect parcels visible on map (in a continuous land use map) not in any particular order but by letting me "guide" by the parcel is centered/zoomed and then by clicking on the "id/whataver" of a neighbor one (so NOT by clicking the navigation arrows).

**Comment by 3nids** [comment]
in such scenario I'd be in favor that the filter is switched from the visible items to a list of feature fid (by doing it in the code). But that sounds a bit too much like a black box to me.

Anyway, it's more likely you are already at large scale, and the flashing will highlight the feature.
If not, there is still the approach select -> pan/scale to selected.

I will merge the PR as it's a first fix (and I have another one following which depends on this). I'm open to suggestions.

**Comment by uclaros** [comment]
Double click to pan / ctrl + double click to zoom to feature would be a handy solution to the 'rolling window' use case.
