### ISSUE TITLE
impossible to open QGIS (3.4 and 3.10): missing dependencies

### ISSUE THREAD

**Issue by smavd** [qgis/QGIS#34499]
## User Feedback

impossible to open Qgis 

## Report Details

**Crash ID**: [6919c7f2870d7e5daee3df68cd629847de045ccb]('https://github.com/qgis/QGIS/search?q=6919c7f2870d7e5daee3df68cd629847de045ccb&type=Issues')

**Stack Trace**
<pre>
RaiseException :
_CxxThrowException throw.cpp:133
qBadAlloc :
QString::QString :
QTextDecoder::toUnicode :
QString::fromUtf16 :
QString::fromWCharArray :
QInternalMimeData::retrieveData :
QMimeData::retrieveData :
QMimeData::text :
QClipboard::text :
QgsClipboard::isEmpty qgsclipboard.cpp:350
QgisApp::activateDeactivateLayerRelatedActions qgisapp.cpp:12855
QgisApp::QgisApp qgisapp.cpp:1175
main main.cpp:1344
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.2-A Coru�a
QGIS code revision: d4cd3cfe5a
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.3
Running against GDAL: 3.0.3

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
> impossible to open Qgis

@smavd really...not enough details. Any error message? How did you installed QGIS, osgeo4w or standalone?

**Comment by reyemtm** [comment]
Same issue. Cannot open QGIS after attempt to upgrade from OSGEO network installer. Mine is the qgis_app.dll not found. Windows. What information is needed?

**Comment by roya0045** [comment]
@reyemtm that error might be caused by many things, I would suggest you to clean your install and use the standalone installer to see if the error persist.

**Comment by reyemtm** [comment]
Standalone install worked. 3.10.2-A Coruña. My guess is there is some issues with PATH variables in the OSGeo-installed version.

**Comment by roya0045** [comment]
@reyemtm This is usually the case as those system variable are easy to break. :/

**Comment by gioman** [comment]
@roya0045 yes and no... it also not easy to break them unless playing around without knowing exactly what is being done. I do *a lot* of osgeo4w installations on *clean* Windows machines and it *just works* in the vast majority of cases.

**Comment by kadarivan** [comment]
qgis-ltr package in OSGeo4W installer not install EXIV2, but qgis_app.dll required it.
Install exiv2 resolve the problem for me.

**Comment by gioman** [comment]
> qgis-ltr package in OSGeo4W installer not install EXIV2, but qgis_app.dll required it.
> Install exiv2 resolve the problem for me.
> 
> update:
> python3-gdal package missing too, qgis-ltr install python3-gdal2, but not working with it.

@kadarivan please report it also in the osgeo4w bug tracker. Thanks!

**Comment by kadarivan** [comment]
> @kadarivan please report it also in the osgeo4w bug tracker. Thanks!
I don't have account there, and as I see, the registration is ridiculously overcomplicated.

**Comment by jef-n** [comment]
> I don't have account there, and as I see, the registration is ridiculously overcomplicated.

the problem is already fixed there.

**Comment by kadarivan** [comment]
> 
> 
> > I don't have account there, and as I see, the registration is ridiculously overcomplicated.
> 
> the problem is already fixed there.

@jef-n 
QGIS-ltr 3.10 is working fine with a fresh install, but 3.4 needs gdal2 package
(old and new LTR not compatible, should be separated in the installer)

**Comment by jef-n** [comment]
3.4 is EOL.
