### ISSUE TITLE
WKT parser error

### ISSUE THREAD

**Issue by lbartoletti** [qgis/QGIS#34496]
**Describe the bug**

There is an error with the WKT parser from QgsGeometry.fromWkt. When there are extra open parentheses, are parsed as a 0 and not a null geometry.

**How to Reproduce**

PyQGIS example:

```
g = QgsGeometry.fromWkt('MULTILINESTRING( ((1 2, 2 4, 4 5))')
g
<QgsGeometry: MultiLineString ((0 2, 2 4, 4 5))>
g = QgsGeometry.fromWkt('MULTILINESTRING((1 2, 2 4, 4 5))')
g
<QgsGeometry: MultiLineString ((1 2, 2 4, 4 5))>
g = QgsGeometry.fromWkt('MULTILINESTRING((((1 2, 2 4, 4 5))')
g
<QgsGeometry: MultiLineString ((0 2, 2 4, 4 5))>
g = QgsGeometry.fromWkt('MULTILINESTRING( {1 2, 2 4, 4 5))')
g
<QgsGeometry: null>
```

**QGIS and OS versions**

**Additional context**

**Comment by stev-0** [comment]
I think this has now been fixed, so assume can be closed
