### ISSUE TITLE
Extension processing desactivated

### ISSUE THREAD

**Issue by Kazkan** [qgis/QGIS#34498]
Every time I open Qgis I get this error message : 
_"Extension processing: Cette extension sera désactivée car elle a entraîné un plantage de QGIS lors du dernier démarrage. Merci de faire remonter le problème et de réactiver l'extension lorsque ce dernier aura été réglé."_
Something like : Extension processing : this extension will be desactivated because it resulted Qgis crash during the last start. Please advise and then reactivate the extension when the problem will be solved.

I have no processing tools available. I tried to restart and reinstal Qgis, on different version (3.8, 3.10, 3.10.2), I also tried to reboot my computer etc. It does still not work.

**Comment by gioman** [comment]
> I have no processing tools available. I tried to restart and reinstal Qgis, on different version (3.8, 3.10, 3.10.2), I also tried to reboot my computer etc. It does still not work.

@Kazkan please try a new QGIS profile.

**Comment by Kazkan** [comment]
Problem solved by reactivating "Processing" in the plug-in manager
