### ISSUE TITLE
"Draw map's objects" option in layout composer Qgis 3.8.3

### ISSUE THREAD

**Issue by Forna73** [qgis/QGIS#34507]
Even if the "Draw map's objects" option is unchecked in the Object's properties TAB under "main properties", the map window still render the content.

**Comment by gioman** [comment]
@Forna73 "draw objects" do not refer to the map object, but rather to other things like for example the map annotations.

**Comment by gioman** [comment]
@Forna73 Also 3.8 is EOL.

**Comment by Forna73** [comment]
You mean Other objects created directly inside the layout composer?

**Comment by gioman** [comment]
no, objects added in the main map canvas, i.e. annotations

**Comment by DelazJ** [comment]
@Forna73 explained in docs https://docs.qgis.org/3.4/en/docs/user_manual/print_composer/composer_items/composer_map.html#main-properties

**Comment by Forna73** [comment]
thx
