### ISSUE TITLE
Raster layer misaligns when bbox bigger than projected raster layer

### ISSUE THREAD

**Issue by anneb** [qgis/QGIS#34518]
**Projected raster layer misaligns in QGIS**
![qgis-wms-landuse](https://user-images.githubusercontent.com/839432/74689895-39595700-51dd-11ea-9935-3b14bbed0b89.png)
A raster layer (source srs EPSG:4326) misaligns with a vector layer when projected AND zooming out beyond the bounding box of the raster layer.

**How to Reproduce**
1. download the 267MB zipped project and data from [my cloud drive](https://drive.google.com/file/d/1D9X8twzOSLrDW7cd-1L_el9S4Duq0QWC/view?usp=sharing). The raster is a TIFF file, EPSG:4326. I do not know how to reproduce a world covering raster with less data.
2. unzip the project and data (directory 'rastervector', project 'project.qgs') and open in  QGIS. 
3. load the project into QGIS. The raster and vector layers align nicely. 
4. change the OTF projection to EPSG:3857 and zoom to layer 'landcover2'

This should produce the image showing the misaligned raster layer. If you zoom in on the map, the raster and vector suddenly align properly.

**QGIS and OS versions**
I got exactly the same results with QGIS versions 2.18.20 and 3.03 and 3.2

**Comment by nyalldawson** [comment]
This looks a lot like https://github.com/qgis/QGIS/issues/32180. Maybe the same underlying issue.

**Comment by anneb** [comment]
I found that the problem also occurs in QGIS Desktop, it is NOT specific to QGIS-server (original issue name). It happens when the raster is projected AND the user zooms out beyond the extents of the raster layer.
