### ISSUE TITLE
Manual layout needs its own icon

### ISSUE THREAD

**Issue by timlinux** [qgis/QGIS#34517]
Help......two icons the same, I am a poor user trying to figure out which to click:

![image](https://user-images.githubusercontent.com/178003/74689213-3efd6f80-51d2-11ea-9a65-648510f2d870.png)

Could we please have a different icon for the new manual layout feature?

cc @nyalldawson

**Comment by timlinux** [comment]
PS yes I know there are tooltips but I am not smart enough to know there are tooltips...

**Comment by nyalldawson** [comment]
Tim - update to a newer build, this is fixed
