### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by mythirdeye** [qgis/QGIS#34516]
## User Feedback

The program crashed after I tried closing after saving the Alaska sample map.

## Report Details

**Crash ID**: [ce907c6a97722a18420f3bcae47b0ff9b07ba6fb]('https://github.com/qgis/QGIS/search?q=ce907c6a97722a18420f3bcae47b0ff9b07ba6fb&type=Issues')

**Stack Trace**
<pre>
PyInit_sip :
PyInit_sip :
sipQgsDataItemProvider::capabilities sip_corepart3.cpp:177640
QgsDirectoryItem::createChildren qgsdataitem.cpp:933
QgsDataItem::runCreateChildren qgsdataitem.cpp:284
QtConcurrent::StoredFunctorCall1<QVector<QgsDataItem * __ptr64>,QVector<QgsDataItem * __ptr64> (__cdecl*)(QgsDataItem * __ptr64),QgsDataItem * __ptr64>::runFunctor qtconcurrentstoredfunctioncall.h:422
QtConcurrent::RunFunctionTask<QVector<QgsDataItem * __ptr64> >::run qtconcurrentrunbase.h:108
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.2-A Coru�a
QGIS code revision: d4cd3cfe5a
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.3
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by gioman** [comment]
@mythirdeye does it happens in a replicable way?

**Comment by mythirdeye** [comment]
Thanks for your reply. I only just got qGIS and it happened the first time I used it, so I sent the crash report as the program suggested to do it.  I will let you know if it is a persistent problem or not. Thanks for your help!

**Comment by roya0045** [comment]
I guess this can be closed?

**Comment by gioman** [comment]
Closing for lack of further feedback.

**Comment by mythirdeye** [comment]
Thank you, yes I never had the issue since
