### ISSUE TITLE
Missing drop-down option for layer visibility in Layers panel

### ISSUE THREAD

**Issue by saberraz** [qgis/QGIS#34524]
I have noticed the layer visibility icon no long has the drop-down option in master:
![image](https://user-images.githubusercontent.com/2649047/74723116-f2498100-5231-11ea-86ab-787274a0845a.png)

The arrow indicating there are more options is useful for (new) users. Maybe something like this:
![proposed](https://user-images.githubusercontent.com/2649047/74723188-12794000-5232-11ea-92e3-bf8f7ce9ac6e.png)

Can we have it back please? :)

**Comment by pigreco** [comment]
## OSGeo4W64 win 10 - all right!

![image](https://user-images.githubusercontent.com/7631137/74727962-43fa0780-5242-11ea-9158-1ec7ad300f7d.png)

![image](https://user-images.githubusercontent.com/7631137/74727885-1f9e2b00-5242-11ea-9311-5738f1833c52.png)

**Comment by saberraz** [comment]
I am using master (self compiled) under Kubuntu:
![image](https://user-images.githubusercontent.com/2649047/74732247-bf0eee00-5241-11ea-9087-94829993c2e2.png)

**Comment by basilrabi** [comment]
It's all right for me too.
![Layers](https://user-images.githubusercontent.com/29010952/74798773-a833ce80-5309-11ea-8b2c-a7ec7ad88fc9.png)

QGIS version | 3.11.0-Master | QGIS code revision | a3c08ad667b
-- | -- | -- | --
Compiled against Qt | 5.13.2 | Running against Qt | 5.13.2
Compiled against GDAL/OGR | 2.3.2 | Running against GDAL/OGR | 2.3.2
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.30.0 | Running against SQLite | 3.30.0
PostgreSQL Client Version | 12.2 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Fedora 31 (Workstation Edition)
Active python plugins | db_manager; processing

**Comment by nirvn** [comment]
@saberraz , that looks a lot like a Qt (Breeze?) style issue. Nothing we can do on our end. If you change the application style to Fusion, you should see the arrows again.

**Comment by saberraz** [comment]
Thanks folks. @nirvn confirmed, changing the style worked.
