### ISSUE TITLE
Crash When Start editing

### ISSUE THREAD

**Issue by fiqih131** [qgis/QGIS#34533]
Crash ID: 5f62a21d6a203e22e70424ade9153cbdd6cb45e2

Stack Trace

QSortFilterProxyModel::parent :
QModelIndex::parent :
QTableView::visualRect :
QAbstractItemView::update :
QAbstractItemView::currentChanged :
QMetaObject::activate :
QItemSelectionModel::`default constructor closure' :
QItemSelectionModel::qt_static_metacall :
QMetaObject::activate :
QAbstractItemModel::beginRemoveRows :
QSortFilterProxyModel::removeRows :
QSortFilterProxyModel::sortRole :
QSortFilterProxyModel::`default constructor closure' :
QMetaObject::activate :
QAbstractItemModel::beginRemoveRows :

QGIS Info
QGIS Version: 3.4.15-Madeira
QGIS code revision: e83d02e274
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.3
Running against GDAL: 2.4.3

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
@fiqih131 please try with a new QGIS profile, no 3rd party plugins installed.

**Comment by gioman** [comment]
Closing for lack of feedback.
