### ISSUE TITLE
"Allow NULL value" in Relation Reference Widget is not respected in attributes form 

### ISSUE THREAD

**Issue by basilrabi** [qgis/QGIS#34537]
**Describe the bug**

When ticking `Allow NULL value` in Relation Reference (many-to-one in postgis) widget and editing the feature (combobox), selecting NULL or entering NULL or empty text in the combo box is not treated as a **change** in the feature.

In order to successful set the foreign key field to `NULL` in QGIS 3.10.2, you need to tick `Use a read-only line edit instead of a combobox` then press the red `X` mark in the form.
However in master (a3c08ad667b), this work around does not work and is clearly a regression from 3.10.x.

**How to Reproduce**

To reproduce, see [screencast](https://github.com/qgis/QGIS/files/4222866/Screencast.from.Wednesday.19.February.2020.10.17.37.AM.PST.zip).

**QGIS and OS versions**

1. QGIS 3.10.2 Flatpak (OS: Fedora 31)
1. QGIS master (a3c08ad667b) (OS: Fedora 31)

**Additional context**

Although I did not test, this could also be a regression from QGIS 3.4 and might be related to [this issue](https://issues.qgis.org/issues/17505).

**Comment by gioman** [comment]
> Although I did not test, this could also be a regression from QGIS 3.4 and might be related to [this issue](https://issues.qgis.org/issues/17505).

@basilrabi it would be very important to find out if is a regression.

**Comment by basilrabi** [comment]
@gioman I tested in Windows using QGIS 3.4.15. It works fine there, choosing NULL in the combobox is recorded as a change and can be saved successfully. This is a regression in 3.10 and master.

**Comment by basilrabi** [comment]
The fix works for me in master. I hope this fix also reaches 3.10.x and 3.12.x
