### ISSUE TITLE
Processing settings dialog cleared after a search is done in Settings dialog

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#34543]
1. Open Settings --> Options --> Processing tab
2. In the top left corner of the dialog do a search, eg 'set'
3. You get a list of algorithms and properties
4. Erase now the search text: you get an empty Processing dialog, with no options.
5. Reopening the dialog of course brings them back
6. Doing more tests, I realize that if you have enabled another tab at point 1 above, did the search and cleared the search text, Processing dialog display is bound to the results of your test, instead of going back to its default rendering.

 3.10 and master are concerned

**Comment by Pedro-Murteira** [comment]
This bug is still present on versions 3.16.14 and 3.22.1. Aswell as, after clearing the search, the settings: "General","Menus","Models","Providers","Scripts" are no longer there. The only way to interact with these options is to restart the process: Open Settings --> Options --> Processing tab.
