### ISSUE TITLE
Crash when querying from DB Manager - QGIS 3.10.1-A Coruna

### ISSUE THREAD

**Issue by PauloEduardoCardoso** [qgis/QGIS#34542]
## User Feedback

Crash when querying from DB Manager

## Report Details

**Crash ID**: [2534f3b8363b8981175252d91d77c1a4d4078567]('https://github.com/qgis/QGIS/search?q=2534f3b8363b8981175252d91d77c1a4d4078567&type=Issues')

**Stack Trace**
<pre>
QMutex::tryLock :
QgsTask::processSubTasksForTermination :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.1-A Coruna
QGIS code revision: ef24c526da
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by gioman** [comment]
>  QGIS Version: 3.10.1-A Coruna

@PauloEduardoCardoso please update to 3.10.2 and try again.

**Comment by roya0045** [comment]
More details would also be needed to reproduce

**Comment by gioman** [comment]
Closing for lack of feedback.
