### ISSUE TITLE
0 is replaced with NULL in the attribute table

### ISSUE THREAD

**Issue by m-kuhn** [qgis/QGIS#34541]
I have a geopackage with values 0.
When I click a cell in the attribute table, the value is automatically replaced with a NULL value.
![Peek 2020-02-19 11-07](https://user-images.githubusercontent.com/588407/74824132-21cabd00-5308-11ea-8338-b53fa8ab1ab9.gif)

QGIS 3.10.2

**Comment by elpaso** [comment]
Pretty bad, it may have something to do with my recent changes in the default values for OGR provider. Do you want me to have a look or are you onto it?

**Comment by elpaso** [comment]
@m-kuhn I cannot reproduce in current master (with an integer field and all defaults).

**Comment by m-kuhn** [comment]
@elpaso if you have time to look into it, here's the dataset I loaded (On Fedora and Windows, QGIS 3.10.2 both):

https://cloud.opengis.ch/index.php/s/Y9pJFxGmsiXmwX3

**Comment by elpaso** [comment]
@m-kuhn I tested you qgep data on master and I still cannot reproduce (but you mentioned 3.10, does it work on master for you?).

**Comment by m-kuhn** [comment]
I will check when I have a working build again (not sure when exactly).

**Comment by pigreco** [comment]
## OSGeo4W64 WIN 10 QGIS 3.10.2-2 all right

![zeronull](https://user-images.githubusercontent.com/7631137/74837906-cc4fd980-5322-11ea-8909-6197d252bfb5.gif)

**Comment by m-kuhn** [comment]
Seems to happen only on "Text Edit Widgets" (e.g. Haltungen->rp_from_level)

**Comment by gioman** [comment]
@m-kuhn confirmed here on 3.10.2 on Windows with your data

![Peek 2020-02-19 20-26](https://user-images.githubusercontent.com/1951107/74872987-303fc580-5356-11ea-8f1f-fbff5eabd802.gif)

**Comment by elpaso** [comment]
Looks like 3.10 only, current master is ok.

![zero](https://user-images.githubusercontent.com/142164/74916956-0a063e00-53c7-11ea-9eef-f9ffd7192514.gif)

**Comment by gioman** [comment]
> Looks like 3.10 only, current master is ok.

@m-kuhn @elpaso I confirm also on Windows, ok on master.

**Comment by elpaso** [comment]
I'm not so sure it's related to my recent fixes, I think I've backported to 3.10 almost everything.

**Comment by pigreco** [comment]
## All right → OSGeo4W64 win 10 `QGIS 3.10.3` <--
![ipo](https://user-images.githubusercontent.com/7631137/75119797-7e223980-5686-11ea-81ea-3a60e1d93cc0.gif)

**Comment by m-kuhn** [comment]
Thank you @pigreco !
