### ISSUE TITLE
Crush at clear project while trying loading any data QGIS 3.4.15 (happened also with QGIS 3.10.2)

### ISSUE THREAD

**Issue by martaksx** [qgis/QGIS#34555]
## User Feedback

I wanted to load a new vector file, same happend with trying to load csv via Data Source Manager.
I also created a new profile (settings > user profiles > new profile), to check if this bug will appear, but it strikes again, 
It happens in a  replicable way, first it started at QGIS 3.10.2, then I uninstalled and went to 3.4.15, but problem didn't disappear.

I can't use QGIS :(

## Report Details

*Crash ID*: 2b5b8847e4fda81698b56c97b7805166938c74fd

*Stack Trace*
<pre>
RtlpFreeHeapInternal :
RtlFreeHeap :
free :
DllUnregisterServer :
DllUnregisterServer :
CServerContextActivator::CreateInstance actvator.cxx:877
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1970
CApartmentActivator::CreateInstance actvator.cxx:2185
CProcessActivator::CCICallback actvator.cxx:1636
CProcessActivator::AttemptActivation actvator.cxx:1523
CProcessActivator::ActivateByContext actvator.cxx:1367
CProcessActivator::CreateInstance actvator.cxx:1267
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1970
CClientContextActivator::CreateInstance actvator.cxx:566
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1970
ICoCreateInstanceEx objact.cxx:2211
CComActivator::DoCreateInstance immact.hxx:386
CoCreateInstance actapi.cxx:121
_SHCoCreateInstance :
DCA_SHExtCoCreateInstance :
CreateAndCacheIconOverlay :
CFSIconOverlayManager::GetOverlayIconInformation :
CFSIconOverlayManager::LoadIconOverlayIdentifiers :
CFSIconOverlayManager::_s_LoadIconOverlayIdentifiers :
CFSIconOverlayManager::LoadNonloadedOverlayIdentifiers :
EnableExternalOverlayIdentifiers :
CFSIconOverlayManager::RefreshOverlayImages :
GetIconOverlayManagerImpl :
CFSFolder::_GetOverlayInfo :
CRegFolder::_GetOverlayInfo :
CRegFolder::GetOverlayIndex :
CAutoDestItemsFolder::GetOverlayIndex :
CRegFolder::_GetOverlayInfo :
CRegFolder::GetOverlayIndex :
CNscOverlayTask::_Extract :
CNscOverlayTask::InternalResumeRT :
CRunnableTask::Run :
CShellTask::TT_Run :
CShellTaskThread::ThreadProc :
CShellTaskThread::s_ThreadProc :
ExecuteWorkItemThreadProc :
RtlpTpWorkCallback :
TppWorkerThread :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.4.15-Madeira
QGIS code revision: e83d02e274
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.3
Running against GDAL: 2.4.3

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by roya0045** [comment]
Could you provide more detailed steps to reproduce this?

**Comment by gioman** [comment]
> I can't use QGIS :( 

@martaksx please try with a new QGIS profile, no 3rd party plugins installed.

**Comment by martaksx** [comment]
@gioman 
Hi, so I was installing this QGIS on a computer, which had before 2.18 version, so there are no extra plugins installed and everytime I make a new, clear profile (I already have few), it doesn't help, it crashes again and again.

@roya0045 
Well, it's not so complicated, I thought I described it well in the report, but here you are.
1. Run QGIS (never mind if it is GRASS or without GRASS version)
2. Open New Project.
3. Click "Open Data Source Manager"
4. Choose "Delimited Text" option
5. Click "Browse" (...) in the "File name" field.
6. I can't even choose the file load, because at this moment QGIS crashes.

What is interesting, at my old PC I load the same files (csv, vectors) and nothing is crushing (there I installed QGIS 3.10.2, but also with 3.4.x it worked), so I think there may be problem with python version or some registry stuff. Do you think this is possible?
I inherited this second PC at Uni from ex PhD student, so it's hard for me to say what was done before and maybe this is the reason for this bug to appear?

**Comment by roya0045** [comment]
@martaksx In the data manager does it only occurs with the delimited text or any other source?

**Comment by gioman** [comment]
> What is interesting, at my old PC I load the same files (csv, vectors) and nothing is crushing (there I installed QGIS 3.10.2, but also with 3.4.x it worked), so I think there may be problem with python version or some registry stuff. Do you think this is possible?
> I inherited this second PC at Uni from ex PhD student, so it's hard for me to say what was done before and maybe this is the reason for this bug to appear?

@martaksx I'm keen to close this ticket as it is clearly a local issue and not a general one (as you demonstrated by your own). I suggest you (regardless of this problem of QGIS) of re-installing from scratch the operating system on your inherited computer.

**Comment by martaksx** [comment]
@roya0045 happens with any type of data.
@gioman well, I actually started re-installation of the OS, however I hoped it's just a different problem, cause I hate to install all programs which I use again. I think you can close this topic as you suggested. Anyway, thanks to both of you for your time and attention.
