### ISSUE TITLE
PATH customization doesn't work with Qgis 3.10.2

### ISSUE THREAD

**Issue by EmmaAEAG** [qgis/QGIS#34550]
Hi,

I'm working on Windows-NT OS, with 3.10.2-A Coruña.
I need to add a path to use an external program wich is located in : c:\\mypath (this path is not always the same so I need to custom it depending on the PC).

With Qgis 2.*, I used in the qgis-ltr.bat script the line : 
path %OSGEO4W_ROOT%\apps\qgis-ltr\bin;%OSGEO4W_ROOT%\apps\grass\grass-6.4.3\lib;%PATH%;c:\mypath
And it works

With Qgis 3.4, such a line has no effect. As I could see in the Settings>Options>System>Environment, PATH is always 
C:\OSGEO4~1\apps\qgis\bin;C:\OSGEO4~1\apps\Python37;C:\OSGEO4~1\apps\Python37\Scripts;C:\OSGEO4~1\apps\qt5\bin;{app};C:\OSGEO4~1\bin;C:\Windows\system32;C:\Windows;C:\Windows\system32\WBem;C:\Program Files\R\R-3.2.2\bin\i386;C:\OSGEO4~1\apps\Python37\lib\site-packages\pywin32_system32;C:\OSGEO4~1\apps\Python37\lib\site-packages\numpy\.libs
any path.... line I put in the bat.
So I used custom variables : 
Apply = Append / Variable = PATH / Value = ;C:\mypath
that results in the QGIS3.ini file in :
[qgis]...
customEnvVarsUse=true
customEnvVars="append|PATH=;C:\\mypath"
And it works : PATH variable become 
C:\OSGEO4~1\apps\qgis\bin;C:\OSGEO4~1\apps\Python37;C:\OSGEO4~1\apps\Python37\Scripts;C:\OSGEO4~1\apps\qt5\bin;{app};C:\OSGEO4~1\bin;C:\Windows\system32;C:\Windows;C:\Windows\system32\WBem;C:\Program Files\R\R-3.2.2\bin\i386;C:\mypath;C:\OSGEO4~1\apps\Python37\lib\site-packages\pywin32_system32;C:\OSGEO4~1\apps\Python37\lib\site-packages\numpy\.libs
(as seen in Settings>Options>System>Environment)

But with Qgis 3.10.2, such a customization 
customEnvVarsUse=true
customEnvVars="append|PATH=;C:\\mypath"
results in a PATH=;C:\\mypath
and a lot of plugins don't work anymore...

Is it a bug ? 
Or is there any other way to add a path ?
Thanks

**Comment by roya0045** [comment]
This doesn't seem to be a bug, bug you can add a path in your system variables and it should be fine.

**Comment by jef-n** [comment]
The system PATH gets overridden.   QGIS starts from a clean PATH.
Certain variables - including PATH - are read from the .env next to the .exe (see .vars), which is written on install (by calling the .bat with --postinstall).  So changing the .bat after that doesn't take effect (unless you rerun it with --postinstall).

**Comment by EmmaAEAG** [comment]
Thanks roya0045. 
But in my company I can't modify the PATH in the OS of all my colleagues (we don't have administrator rights). So customization was a solution.
My question is : that worked but doesn't work anymore. Why Append in Custom Variable Option overwrites the variable ?

**Comment by EmmaAEAG** [comment]
Thanks Jef.
That doesn't explain why Append Apply-option overwrites a variable in the Settings>Options>System>Environment> Use Custom variables panel.
But modify the .env file to add mypath to the PATH is a way that works.
