### ISSUE TITLE
crash when adding a new child feature from a relation reference widget parent form

### ISSUE THREAD

**Issue by elpaso** [qgis/QGIS#34552]
because QgsAttributeEditorContext::setCadDockWidget is never called in that code path and QgsMapToolAdvancedDigitizing precondition is that mCadDockWidget is not nullptr.

@troopa81 any idea?

**Comment by elpaso** [comment]
besides, I think it would be a good idea if we started adding precondition asserts in constructors.

**Comment by elpaso** [comment]
@troopa81 nevermind, I've found the solution

**Comment by troopa81** [comment]
@elpaso Just for the record, there is other issues coming from a not well initialized context. I try to fix it in this [PR](https://github.com/qgis/QGIS/pull/33990) (which need to be updated)
