### ISSUE TITLE
GeoJson datasources - unlink to file when checkout git branches

### ISSUE THREAD

**Issue by lmdc45** [qgis/QGIS#34560]
I had issue before saving geojson files, fixed now thanks to #28580. Here is one small issue I still have with QGIS and I could not find any answers yet. This might still be related to that issue.

I have small geojson datasets, version managed with git. If I modify a geosjon with QGIS I can push it to a repo just fine.
However once I have modified a file, it will stay linked to QGIS. This means when I checkout another branch, git will block it with a message : 
` cannot unlink file xxx.geojson, do you want to retry (y/n)?`

Then at this stage I have to close QGIS to unlink the file, checkout a branch, and open QGIS again.
Is there a quick way to 'unlink' a file, and so checkout branches easily?

Thanks

**Comment by gioman** [comment]
@lmdc45 is this a question or a bug report?

**Comment by lmdc45** [comment]
Thank you for the reply. It might be in between a question and a bug... is it normal that the file is still linked even when not being edited?
I am not sure.
If it is normal then it is a question

**Comment by gioman** [comment]
> Thank you for the reply. It might be in between a question and a bug... is it normal that the file is still linked even when not being edited?
> I am not sure.
> If it is normal then it is a question

@lmdc45 please ask it in the users/developers mailing list. If it turns out is a bug then ask to reopen this ticket, thanks.
