### ISSUE TITLE
Phantom windows - unable to regain focus of open windows

### ISSUE THREAD

**Issue by Brent-Edwards** [qgis/QGIS#34587]
**Describe the bug**
This is a tough one to describe... I did my best with the title.

**How to Reproduce**
I can't specifically nail down the sequence of events that lead to the described behavior. The best I can do is to state that the problem seems to arise when I have several projects open with several windows (ex. attribute table windows, processing tool windows). When attempting to return to a specific project in the Windows task bar, the focus (mouse over of the open project) displays the project and all open windows. I am able to change the focus to the project, but not the open windows and therefore it is impossible to close them.

1. Open multiple QGIS projects
2. Open a window within a certain project - ex. Help>About
3. Minimize all windows
4. Attempt to return to a specific window within an open project and close it (ex. the window opened in step 2)

Example - I am unable to regain focus on the "About" window and close it:
![2020-02-20_QGIS_unable_to_close_certain_windows](https://user-images.githubusercontent.com/13538726/74961280-cf5ad080-53db-11ea-95e9-3b4b3fa8d36e.png)

**QGIS and OS versions**

QGIS version
3.10.2-A Coruña
QGIS code revision
d4cd3cfe5a
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.3
Running against GDAL/OGR
3.0.3
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.0
Running against PROJ
Rel. 6.3.0, January 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
changeDataSource; 
crayfish; 
gmsh; 
latlontools; 
Mergin; 
mmqgis; 
profiletool; 
QMetaTiles; 
quick_map_services; 
shapetools; 
splitmultipart; 
SVG2ColoR; 
timemanager; 
valuetool; 
VectorMCDA; 
VoGisProfilTool; 
db_manager; 
MetaSearch; 
processing

**Additional context**

Dual monitors.

**Comment by roya0045** [comment]
If you are on a dual screen setup, sometimes changing the screen disposition will make it appear. This is often needed with the georeferencer window on my setup.

**Comment by Brent-Edwards** [comment]
> If you are on a dual screen setup, sometimes changing the screen disposition will make it appear. This is often needed with the georeferencer window on my setup.

What do you mean by "changing the screen disposition"? Simply swapping applications/windows across screens, or actually changing a screen from portrait to landscape?

I definitely do the first (swapping applications/windows across screens), but not the latter.

**Comment by roya0045** [comment]
In your windows display settings, in 'Select and rearrange displays'. Fiddle with that and it should force the window to render.

**Comment by gioman** [comment]
Closing for lack of feedback.
