### ISSUE TITLE
Null z value when exporting layer with points to GeoJSON

### ISSUE THREAD

**Issue by benjaminh** [qgis/QGIS#34582]
**Issue**
When trying to export a layer of points in GeoJSON while specifying exporting z value, the features in the GeoJSON file have a point geometry property with x,y and z values, but the z coordinate is always 0 whereas the "z" property outside of the geometry is correctly set.

I guess that "z-dimension" mentioned in the export wizard is not bound to "z" property as nothing is asked about "z" value when importing a new delimited layer.

How can I specify which field corresponds to that "z-dimension" ?

Here is an extract of the created GeoJSON file.
```JSON
{
"type": "FeatureCollection",
"name": "test-fusion",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:EPSG::2154" } },
"features": [
{
  "type": "Feature",
  "properties": { "profile_index": 50, "point_index": 1, "z": -0.038558173924699998, "x": 307983.48476900003, "y": 6653456.4515699996 },
  "geometry": { "type": "Point", "coordinates": [ 307983.484769, 6653456.4515699995682, 0.0 ] } },
...
]
}
```
**How to Reproduce**

1. Select a layer
2. Click on 'Export' > 'Save features as'
3. Choose GeoJSON as Export format
4. In Geometry section, choose "Point" or "GeometryCollection" and tick "include z-dimension"
5. Save file

**QGIS and OS versions**

QGIS version | 3.4.15-Madeira
-- | --
Compiled against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2
PostgreSQL Client Version | 10.10 (Ubuntu 10.10-0ubuntu0.18.04.1)
QWT Version | 6.1.3

**Comment by basilrabi** [comment]
This is not a bug. Exporting to GeoJSON in QGIS 3.4.15 works as expected.

Most probably, your data is only 2-dimensional (*e.g.* Points with only X and Y as coordinates that define the geometry). When you export a 2D data to GeoJSON while ticking `include z-dimension`, it is expected that the exported `z-dimension` to be zero.

What  you can do is convert your 2D data into 3D first before exporting to GeoJSON. This can be done by using `Processing Toolbox` > `Set Z value`. In your case, you can use the `z` field as the `Z value`.

**Comment by benjaminh** [comment]
@basilrabi I suspected to be missing something like that but wasn't sure about it, thank you !
