### ISSUE TITLE
Raster File size is too large

### ISSUE THREAD

**Issue by Dhanesh-shirsat** [qgis/QGIS#34583]
**Regarding Raster file**

**We are doing slope analysis, but while we perform raster interpolation then after interpolation there are "Bad allocation error"  as well when it works properly then raster file size is about 9 gb so because of it we are not able to perform further. and at the same time time PC gets hang due to it we are not able to move forward**

**QGIS version - 2.18.13 and OS versions- Windows 7 (64bit), 8gb Ram, i5-3330@ 3.00GHz**

**Please give us a solution how can we able to reduced the size of raster file or else another way to solve this issue**

**Comment by basilrabi** [comment]
@Dhanesh-shirsat , you need to use the latest versions of QGIS before you try to report any issues. In the [website](https://qgis.org/en/site/), the versions shown are 3.10.2 and 3.4.15. The version you mentioned (2.18.13) is almost 3 years old.

**Comment by Dhanesh-shirsat** [comment]
we are also using latest version of QGIS 3.10.2, but in that we are unable to find the interpolation plugin. so can you tell me where we can find that interpolation plugin in QGIS 3.10.2?

**Comment by basilrabi** [comment]
Not sure what you want to do but most probably it is already in the `Processing Toolbox`. I can see a `Slope` tool in the `Raster Terrain Analysis`.

**Comment by gioman** [comment]
@Dhanesh-shirsat the plugin was migrated into the Procesing toolbox. Please try the latest version of QGIS and report back. If the issue persist please add a link to your data and post the exact parameters used for the operations your are trying to do.

**Comment by roya0045** [comment]
@Dhanesh-shirsat I'm pretty sure this might be a local issue. The best option if they want to keep the definition would be to split their data in tiles and perform separate interpolation as they seem to be running our of resource.

**Comment by roya0045** [comment]
@gioman think this can be closed?

**Comment by gioman** [comment]
Closing for lack of feedback.
