### ISSUE TITLE
MultiLineString(Z) with an empty LineString(Z) component is not handled properly with $length calculation and also not caught by "Check Validity" or "Fix Geometries""

### ISSUE THREAD

**Issue by iboates** [qgis/QGIS#34596]
**Describe the bug**

When running "Check Validity" or "Fix Geometries", it does not seem to catch the case where a MultiLineString(Z) has a component with an empty LineString(Z) component.

I discovered this when a feature in my dataset kept returning `nan` when I calculated `$length` into a field. Curiously, however, it is able to calculate the length when I use the formula `length($geometry)` instead. I understand that the former takes into account ellipsoidal distances, and the latter is purely planimetric, but it seems odd that one is able to transparently handle this broken geometry and the other is not.

I tried exporting the geometry to WKT and found this (EPSG is 2154):

```
MultiLineStringZ (
	(
		998038.7 6493206.69999999 0,
		998072.9 6493193.29999999 0,
		998203.09999999 6493266.49999999 0,
		998219.4 6493301.69999999 0,
		998306.2 6493334.19999999 0,
		998360.5 6493312.49999999 0,
		998525.3 6493422.59999998 0,
		998474.4 6493480.39999999 0,
		998525.2 6493532.59999998 0,
		998607.3 6493583.39999999 0,
		998707.7 6493745.89999999 0,
		998798.5 6493819.49999999 0,
		998838.5 6493824.09999998 0,
		998918.4 6493823.39999999 0,
		998938.6 6493843.19999999 0,
		998948.8 6493868.09999998 0,
		999019.3 6493932.49999999 0,
		999034.3 6493942.29999999 0,
		999074.59999999 6493981.89999999 0,
		999119.7 6493996.49999999 0,
		999149.7 6494001.29999999 0,
		999234.59999999 6494000.49999999 0,
		999274.3 6493960.19999999 0,
		999304.09999999 6493949.99999999 0,
		999364 6493939.49999999 0,
		999394 6493939.19999999 0,
		999404 6493944.09999998 0,
		999444.4 6493988.69999999 0,
		999469.4 6493993.49999999 0,
		999504.5 6494008.19999999 0,
		999549.5 6494012.79999999 0,
		999699.8 6494061.39999999 0,
		999708.65802306 6494072.49247933 0
	),
	(
		999708.65802306 6494072.49247933 0,
		999708.65802306 6494072.49247933 0
	)
)
```

A second LineStringZ component with 0 length is hanging around.

Running "Check Validity" and "Fix Geometries" did not catch this empty LineStringZ component, even when setting the Check Validity method to "QGIS" and "GEOS".

I suppose I could have assigned each feature a uniqe ID, exploded all features to Singlepart, tried to fix the geometries, then re-assembled them into multipart features again, but this seems rather cumbersome when this kind of invalid geometry could probably be fixed properly using an official tool.

**How to Reproduce**

Create a feature with the above WKT geometry and try to calculate a field with `$length`. You will get `nan`. Try again with `length($geometry)`. You will get the actual length. Run "Check Validity" and "Fix Geometries" on it. Nothing will happen.

**QGIS and OS versions**

QGIS version | 3.8.3-Zanzibar | QGIS code revision | 685d8b15d2
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.0 | Running against GEOS | 3.7.2-CAPI-1.11.0 b55d2125
PostgreSQL Client Version | 10.8 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Windows Server 2016 (10.0) |   |

**Comment by gioman** [comment]
> 3.8.3-Zanzibar

@iboates Hi,  this version is really too old, you must test the same scenario/case on the latest version, 3.10.2 and/or master, thanks!

**Comment by CoosForest** [comment]
Same issue here. Spent many hours until I found the workaround mentioned here. length($geometry) works while $length returns nan for all records.
QGIS version
3.22.13-Białowieża

QGIS version
3.22.13-Białowieża
