### ISSUE TITLE
Street View plugin not opening within the correct region

### ISSUE THREAD

**Issue by panda1967** [qgis/QGIS#34598]
My colleague is having a function issue
 after activation, the street view result is within a different region ( Paris in France) when looking at Broxburn, West Lothian, Scotland.

Any idea on what is happening?

Kind regards,

Ken.

**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by Gustry** [comment]
@panda1967 As mentioned in the ticket template:

> If the issue concerns a **third party plugin**, then it **cannot** be fixed by the QGIS team. Please raise your issue in the dedicated bug tracker for that specific plugin (as listed in the plugin's description).

Report to plugin code repository, not QGIS.
