### ISSUE TITLE
Selection with Vertex Tool does not work with layers in different reference system than the project

### ISSUE THREAD

**Issue by PedroVenancio** [qgis/QGIS#34591]
**Describe the bug**
Selection with Vertex Tool does not work with layers in different reference system than the project.

This does not happen in QGIS 3.4.15, where everything works as expected, regardless the OTF being used or not.

**How to Reproduce**

Please see the screencast:

![vertex_tool_qgis3102](https://user-images.githubusercontent.com/1331581/74989993-e8926a00-5439-11ea-91d5-de3dad48929c.gif)

**QGIS and OS versions**

QGIS version | 3.10.2-A Coruña | QGIS code revision | c932794154
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.0dev | Running against GDAL/OGR | 3.1.0dev
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 7.0.0 | Running against PROJ | Rel. 7.0.0, March 1st, 2020
OS Version | Windows 10 (10.0) | This copy of QGIS writes debugging output.
Active python plugins | BackupLayer; DataPlotly; export_to_sql_server; geoprocAlgos; getools; gml_application_schema_toolbox; go2streetview; GroupStats; HCMGIS; lrs; mmqgis; MultiDistanceBuffer; ntv2_transformations; photo2shape; pointsamplingtool; postgis_geoprocessing; PotentialSlopeFailure; processing_circuitscape; processing_gnm; processing_js; processing_prepair; processing_saga; profiletool; qchainage; Qgis2threejs; qgis2web; QNEAT3; quick_map_services; refFunctions; SemiAutomaticClassificationPlugin; SentinelHub; statist; SwapVectorDirection; timemanager; valuetool; verifica_lotesrp; VoGisProfilTool; db_manager; MetaSearch; processing

**Comment by gioman** [comment]
@PedroVenancio Hi Pedro, I tried hard on Windows/3.10.2 without being able to replicate. I see that you use a lot of 3rd party plugins, would you mind do a quick test and see if you see the same with a new QGIS profile? Thanks!

**Comment by PedroVenancio** [comment]
Hi @gioman 
Tested here in a clean profile, and it still happen.

Versão do QGIS | 3.10.2-A Coruña | Revisão do código do QGIS | c932794154
-- | -- | -- | --
Compilado com Qt | 5.11.2 | Em execução com Qt | 5.11.2
Compilado com GDAL/OGR | 3.1.0dev | Em execução com GDAL/OGR | 3.1.0dev
Compilado com GEOS | 3.8.0-CAPI-1.13.1 | Em execução com GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
Versão de cliente PostgreSQL | 11.5 | Versão SpatiaLite | 4.3.0
Versão QWT | 6.1.3 | Versão QScintilla2 | 2.10.8
Compilado com PROJ | 7.0.0 | Em execução com PROJ | Rel. 7.0.0, March 1st, 2020
OS Version | Windows 10 (10.0) | Esta cópia do QGIS escreve a saída de depuração.
Active python plugins | db_manager; MetaSearch; processing

**Comment by nyalldawson** [comment]
Confirmed
