### ISSUE TITLE
`$area` function returns different results for QGIS 2 and 3

### ISSUE THREAD

**Issue by kadirsahbaz** [qgis/QGIS#34597]
`$area` function in Field Calculator returns different values for QGIS 2 and 3 for the same polygon.

Please look at: [Area calculation in QGIS](https://gis.stackexchange.com/questions/351464/area-calculation-in-qgis)

QGIS 2.18.20 / QGIS 3.8.0

**Comment by nyalldawson** [comment]
Trust the qgis 3 results. They are much more accurate and reliable vs 2 (which had some known bugs in area calculation)
