### ISSUE TITLE
QgsRendererRasterPropertiesWidget().syncToLayer bug

### ISSUE THREAD

**Issue by jakimowb** [qgis/QGIS#34602]
**Bug Description**

The QgsRendererRasterPropertiesWidget() allows to modify a raster layers QgsRasterRenderer.
However, changes of renderer bands are not taken up when calling the QgsRendererRasterPropertiesWidget's ['syncToLayer(rasterLayer)'](https://qgis.org/api/classQgsRendererRasterPropertiesWidget.html#a928b84eed069a09147ef6054d9d5b77e) function. Instead, the renderer bands are set back to default settings, at least in case of QgsMultiBandColorRenderer and QgsSingleBandGrayRenderer.

I assume this is caused in [`qgsrendererrasterpropertieswidget.cpp`](https://github.com/qgis/QGIS/blob/master/src/gui/raster/qgsrendererrasterpropertieswidget.cpp) by lines 343 - 356, which overwrite existing single-band-gray or multibandcolor renderers.

```cpp
      if ( oldWidget )
      {
        if ( rendererName == QLatin1String( "singlebandgray" ) )
        {
          whileBlocking( mRasterLayer )->setRenderer( QgsApplication::rasterRendererRegistry()->defaultRendererForDrawingStyle( QgsRaster::SingleBandGray, mRasterLayer->dataProvider() ) );
          whileBlocking( mRasterLayer )->setDefaultContrastEnhancement();
        }
        else if ( rendererName == QLatin1String( "multibandcolor" ) )
        {
          whileBlocking( mRasterLayer )->setRenderer( QgsApplication::rasterRendererRegistry()->defaultRendererForDrawingStyle( QgsRaster::MultiBandColor, mRasterLayer->dataProvider() ) );
          whileBlocking( mRasterLayer )->setDefaultContrastEnhancement();
        }
      }

```

**How to Reproduce**

Let `lyr` be a multiband raster layer, then the following example fails in the last line:

```python
lyr = QgsRasterLayer('path to layer')
lyr.setRenderer(QgsSingleBandGrayRenderer(lyr.dataProvider(), 1))
c = QgsMapCanvas()
w = QgsRendererRasterPropertiesWidget(lyr, c)
w.show()
assert isinstance(w.currentRenderWidget().renderer(), QgsSingleBandGrayRenderer)
assert w.currentRenderWidget().renderer().grayBand() == 1
lyr.renderer().setGrayBand(2)
w.syncToLayer(lyr)
assert w.currentRenderWidget().renderer().grayBand() == 2
```

A python unit test for this problem is available in
[QgsRendererRasterPropertiesWidget_bug.zip](https://github.com/qgis/QGIS/files/4237469/QgsRendererRasterPropertiesWidget_bug.zip) and could be pulled [from this fork](https://github.com/jakimowb/QGIS/blob/feature/rasterrendererprops_test/tests/src/python/test_qgsrendererrasterpropertieswidget.py)

https://github.com/jakimowb/QGIS/tree/feature/rasterrendererprops_test

**QGIS and OS versions**

Windows 10 and Ubuntu 18.04.4 LTS

Part | Version
-- | -- 
QGIS version | 3.10.2-A Coruña 
QGIS code revision | d4cd3cfe5a

**Comment by gioman** [comment]
@jakimowb has a patch/pull request been submitted?

**Comment by jakimowb** [comment]
@gioman so far no patch/PR has been submitted. I can try to create a patch. (Unfortunatelly, I am just a python programmer who, so it might take some time to get it run in C++)
