### ISSUE TITLE
QGIS does not completely start up with roaming profiles

### ISSUE THREAD

**Issue by starfury65** [qgis/QGIS#34603]
## User Feedback

This crash occurs on a user that does not have admin rights. Unplugining the PC from the network will allow the program to start for the unprivileged users. 

## Report Details

**Crash ID**: [987de2fa39cbcfe6367dcba9768a51f1f7140689]('https://github.com/qgis/QGIS/search?q=987de2fa39cbcfe6367dcba9768a51f1f7140689&type=Issues')

**Stack Trace**
<pre>
QWidget::actions :
QMenu::clear :
QgisApp::refreshProfileMenu :
QMetaObject::activate :
QMetaObject::activate :
QFileSystemWatcher::`default constructor closure' :
QMetaObject::activate :
QFileSystemWatcher::directoryChanged :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QCoreApplication::processEvents :
QgisApp::QgisApp :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.2-A Coru�a
QGIS code revision: d4cd3cfe5a
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.3
Running against GDAL: 3.0.3

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
> This crash occurs on a user that does not have admin rights. Unplugining the PC from the network will allow the program to start for the unprivileged users.

@starfury65 really not sure about this description, but regardless seems a local issue.

**Comment by starfury65** [comment]
We have been able to run past versions of QGIS without issue. QGIS here is running on a network with roaming profiles. Again previous QGIS ran fine, but now it will only start if the user is an admin. Last thing I see in the startup screen is Loading Database and then the crash menu appears?  So we currently cannot run the latest QGIS.

**Comment by gioman** [comment]
> We have been able to run past versions of QGIS without issue. QGIS here is running on a network with roaming profiles. Again previous QGIS ran fine, but now it will only start if the user is an admin. Last thing I see in the startup screen is Loading Database and then the crash menu appears? So we currently cannot run the latest QGIS.

@starfury65 ok, unfortunately I cannot test such scenario, se let's see if someone else can confirm the same problem.

**Comment by roya0045** [comment]
Are there scripts or other things in your setups that would occur at boot time?
