### ISSUE TITLE
First feature FID differs for data providers

### ISSUE THREAD

**Issue by nilsnolde** [qgis/QGIS#34606]
**Describe the bug**

In pyqgis I get the first feature of a vector layer via QgsVectorLayer.getFeature(0), but that fails for certain providers, for which it instead works with QgsVectorLayer.getFeature(**1**). Suggesting that these providers have a 1-based internal FID.

I didn't try all data providers:
- shapefile: QgsVectorLayer.getFeature(0) returns the first feature
- memory layer: QgsVectorLayer.getFeature(1) returns the first feature
- geopackage: QgsVectorLayer.getFeature(1) returns the first feature

Also:
- if one exports a shapefile to a new Geopackage and a new layer, the first feature in that Geopackage layer is at index 0 as well. If it's a new Geopackage from scratch and one inserts a new layer and draws a feature, that feature will have an index of 1.
- if a memory layer is made permanent (at least to a shapefile), the resulting layer's first feature will also have an index of 0.

**How to Reproduce**

Load layers for different providers in QGIS, go to Python console and do:

- `l = QgsProject.instance().mapLayersByName('<layer_name>')[0]`
- `print(l.getFeature(0).geometry())` and try `print(l.getFeature(1).geometry())` if the first results in  `<QgsGeometry: null>`

**Workaround**

It's easy to work around it by just doing

```
feat = l.getFeature(0) or l.getFeature(1)
```

However, I'd be curious as to what causes it or if it's known behavior as it feels like that should've come up before somewhere, being a fairly standard pyqgis operation.

Any comment appreciated:)

**QGIS and OS versions**

```
QGIS version | 3.10.1-A Coruña | QGIS code branch | Release QGIS code branch.3
-- | -- | -- | --
Compiled against Qt | 5.13.2 | Running against Qt | 5.14.1
Compiled against GDAL/OGR | 3.0.2 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.30.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.1 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.3
Compiled against PROJ | 6.2.1 | Running against PROJ | Rel. 6.3.0, January 1st, 2020
OS Version | Manjaro Linux
```

**Comment by nyalldawson** [comment]
It's expected. The feature id is usually taken from the underlying backend, and eg may be a primary key from a database table.

The correct approach to get the first feature is:

    f= next(layer.getFeatures())
