### ISSUE TITLE
recreating vector layer style within same project on different computers

### ISSUE THREAD

**Issue by petroleum1997** [qgis/QGIS#34600]
**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

Hi QGIS,

I have created a QGIS Project and setup all the required layer styles by copy/pasting the same symbology between similiar layers and then saved the project to disk. 

I can open the project on PC1 and see all the style/symbology I had added to the required feature layers (vectors) but when  I copy across to the network and open in another PC2 I cannot see the correct symbology/style? On both PC's the same version is beng used 3.4.15 Madeira.

Is anything saved within the setup of PC1 that would need to be copied to the 2nd PC so that the Style/symbology is created on PC2 when oening the same project?

Regards and Thanks

Neil

**Comment by gioman** [comment]
@petroleum1997 is this a question or  a bug report?

**Comment by petroleum1997** [comment]
Hi gioman, this is a question? txs

**Comment by roya0045** [comment]
Without seeing the symbology it is hard to tell. But the ticketing system is not made for question, please use the mailing lists ( dev or user) for such enquiries..

**Comment by alexbruy** [comment]
Clsoing due the lack of feedback.
