### ISSUE TITLE
Strange Projection Behavior

### ISSUE THREAD

**Issue by MicheleTobias** [qgis/QGIS#34604]
Apologies up front - this is difficult to describe in a reproducible way.

QGIS 3.10.2-2 on Windows 10

Rasters that have a custom projection are behaving in strange ways.  I'm working with USGS Topo maps, and each of the files has it's own unique custom (non-EPSG) projection.  When I load one file into either a new or existing QGIS project, I immediately get an error at the top of the map canvas that says "Cannot use preferred transform between Unknown CRS and EPSG: 4326" at the same time as the "Select Transformation" dialog appears.  The first map often goes to the correct spot regardless of which transformation I select, but adding additional maps, the maps seem to be using the projection from the first file I load, and they all stack up on top of each other even though their bounding boxes should be different.  Changing the project's projection from EPSG:4326 to a projected coordinate system (I did EPSG:3310) sometimes fixes the problem, but sometimes makes some of the maps move to a completely different place, not aligned with any data at all.  

Data to reproduce the problem: download a few of the 24K topo maps from [TopoView](https://ngmdb.usgs.gov/topoview/viewer) - each map has a custom projection.

**Comment by MicheleTobias** [comment]
At Anita Graser's suggestion, I just tried it with 3.10.2-22 and it has the same behavior.

**Comment by nyalldawson** [comment]
Can you test with 3.10.3/3.12?

**Comment by MicheleTobias** [comment]
I tried it in 3.12 and it has the same behavior as the other versions I tried.

**Comment by gioman** [comment]
I can confirm the report (tested also on 3.12 on Windows).


[CA_RedBluff_299843_1890_250000_geo_tif.zip](https://github.com/qgis/QGIS/files/4257163/CA_RedBluff_299843_1890_250000_geo_tif.zip)


[SD_RidgeviewNW_344126_1951_24000_geo_tif.zip](https://github.com/qgis/QGIS/files/4257159/SD_RidgeviewNW_344126_1951_24000_geo_tif.zip)


[WI_Blaine_20100715_TM_geo_tif.zip](https://github.com/qgis/QGIS/files/4257158/WI_Blaine_20100715_TM_geo_tif.zip)

**Comment by Pedro-Murteira** [comment]
@MicheleTobias I can no longer replicate this issue using QGIS 3.16.15 and 3.22.2. Did you come across this problem more recently?

**Comment by MicheleTobias** [comment]
I haven't seen it happen lately myself and I checked with my intern who works with this workflow quite a bit and he said he hasn't encountered it in the newer versions of QGIS either, so maybe it's not a problem any more?
