### ISSUE TITLE
Let user drag to change the size of each dialogue

### ISSUE THREAD

**Issue by husi253** [qgis/QGIS#34616]
**Feature description.**
QGIS lets users drag to change the size of each dialogue.

**Additional context**
I use the Linux version. Some dialogue window is too small to show all the contents. I would like to drag the border of the window to change its size.

**Comment by uclaros** [comment]
Which dialog is too small to fit contents and can't be resized?

**Comment by husi253** [comment]
I find the window actually could be dragged and resized. However, when I place the mouse near the boundary of a window, the mouse's style does not change to indicate the possibility of dragging and resize the window. So I mistakenly thought that I could not drag the window.

OS: Ubuntu 18.04 + i3wm

**Comment by roya0045** [comment]
So this can be closed?

**Comment by husi253** [comment]
Of course. I think this mouse's style not changing thing is an issue of the X server that i3wm uses. Since the same thing happens in gimp too.

> So this can be closed?
