### ISSUE TITLE
FID data type error saving from GPKG to SHP and back to GPKG

### ISSUE THREAD

**Issue by josephholler** [qgis/QGIS#34613]
Running QGIS 3.10.2 64-bit or 3.11 weekly (code revision 7c7c2d775b) on Windows 10:

If you save a layer from a geopackage as a shapefile, the FID from the geopackage layer is created as data type 'double' in the shapefile. If your workflow then requires saving back into a geopackage layer, the operation fails because of "wrong field type for FID". I assume that the geopackage is expecting a 64-bit long integer data type.

**Comment by elpaso** [comment]
@josephholler can you add detailed steps to reproduce? There are many ways you can convert a shp to GPKG and vice-versa in QGIS.

**Comment by josephholler** [comment]
Every way that I have been converting shp to gpkg and vis-versa reproduces the error. For example, using a layer's context menu to export features or running an algorithm like Centroids both reproduce the problem on the LTR 3.10.3
The FID becomes *double* data type in shapefile format every time, and saving back into gpkg throws an error every time.
I could potentially spend a bit more time debugging this stuff in a few weeks, but for now we are scrambling to put all of our GIS courses online after colleges in the U.S. closed down.

**Comment by gioman** [comment]
> can you add detailed steps to reproduce?

open a polygon GPKG

create centroids outputting as shapefile > the FID field becomes decimal (was integer in the input layer(

try save the centroids as GPKG > 

```
Export to vector file failed.
Error: Creation of field fid failed (OGR error: Wrong field type for fid)
```

see also https://lists.osgeo.org/pipermail/qgis-developer/2020-March/060584.html
