### ISSUE TITLE
exiv2.dll not is the last qgis-ltr (3.10.3-1) package from OSGeo4W Setup

### ISSUE THREAD

**Issue by EmmaAEAG** [qgis/QGIS#34623]
Hello,
Just to inform that the exiv2.dll library is missing from the really new package from OSGeo4W Setup tool : qgis-ltr Desktop (3.10.3-1).
Starting this Qgis-ltr results in an error message "Error system...exiv2.dll is missing".
Adding the DLL from anywhere (another installation or internet) in the bin directory solves the problem.

**Comment by gioman** [comment]
duplicte of https://github.com/qgis/QGIS/issues/34499

**Comment by EmmaAEAG** [comment]
This problem had been corrected in 3.10.2 package (#34499) , but re-appear in 3.10.3-1, available this morning.
