### ISSUE TITLE
Attribute table highlight missing / misplaced actions column in attributestableconfig

### ISSUE THREAD

**Issue by Houska1** [qgis/QGIS#34628]
A bit of a weird one. 
Some time ago, the highlight identifying the current record stopped being displayed on the left hand panel of the attribute table (with form) on two of my complex layers. See pic, there should be a highlight immediately to the left of the `LongLabel` label.

![ScreenClip2](https://user-images.githubusercontent.com/48919900/75163397-266ae900-56ed-11ea-894b-acd5236d86c0.png)

I've solved the problem by rebuilding the layer, gradually copying over the style parts bit by bit. It turns out the problem is in the attribute table column list, which (when style as saved as qml) appears as:

```
  <attributetableconfig sortExpression="&quot;LongLabel&quot;" actionWidgetStyle="dropDown" sortOrder="1">
    <columns>
      <column type="field" hidden="0" width="-1" name="Photo"/>
      <column type="field" hidden="0" width="-1" name="Category"/>
      <column type="field" hidden="0" width="-1" name="Comment"/>
      <column type="field" hidden="0" width="-1" name="Longitude"/>
      <column type="field" hidden="0" width="-1" name="Latitude"/>
      <column type="field" hidden="0" width="-1" name="Altitude"/>
      <column type="field" hidden="0" width="-1" name="Azimuth"/>
      <column type="field" hidden="0" width="-1" name="SourceFile"/>
      <column type="actions" hidden="1" width="-1"/>
      <column type="field" hidden="0" width="-1" name="Age"/>
      <column type="field" hidden="0" width="-1" name="fid"/>
      <column type="field" hidden="0" width="-1" name="PhotoDate"/>
      <column type="field" hidden="0" width="-1" name="UpdateDate"/>
      <column type="field" hidden="0" width="-1" name="GeomState"/>
      <column type="field" hidden="0" width="-1" name="ShortLabel"/>
      <column type="field" hidden="0" width="-1" name="LongLabel"/>
      <column type="field" hidden="0" width="-1" name="InvalidGeom"/>
      <column type="field" hidden="0" width="-1" name="PhotoBlob"/>
    </columns>
  </attributetableconfig>
```
The problem gets solved when the `actions` entry gets moved to be last in the list (in a saved qml style file, and reloaded).

I don't know why/where the order got munged. I've been fiddling with this layer for some time; this specific problem has been ongoing for several months until I've put my head down to fix it. If it's a weird one-off corruption, who cares, but I'd suggest someone with more coding ability than me check some combo of:

1. Making sure new fields added to a layer, including virtual fields, end up added before not after `actions` in the data that maps into `<attributetableconfig>`

2. Whatever logic adds the highlight in the attribute table left panel should not give up when it meets the `actions` entry (however it is encoded internally) but continue to the end.

I'm using 3.12 on Windows, but this first broke sometime when I was using 3.6 or 3.8.

**Comment by Pedro-Murteira** [comment]
I'm not being able to reproduce this issue on QGIS 3.22.4 and 3.24.0. @Houska1, did you come across this bug since you submitted the issue?

**Comment by Houska1** [comment]
@Pedro-Murteira, it has unfortunately come back, on the same layer, recently, using 3.23-Master. 
I'll dig a bit deeper next week to try to isolate it better. Let's leave this open with the Feedback label (as added by gioman) until then.

**Comment by gioman** [comment]
> using 3.23-Master

@Houska1 master is now 3.25. 3.23 is outdated.
