### ISSUE TITLE
No longer possible to edit a project-saved model

### ISSUE THREAD

**Issue by marcusyoung** [qgis/QGIS#34627]
**Describe the bug**

It no longer seems to be possible to edit an existing model that is saved in a project. If you right click on a model the option to edit is no longer there.

![image](https://user-images.githubusercontent.com/10391966/75158945-0ea45c80-570f-11ea-9d06-e4af84cd179a.png)

The only workaround it to open the project in an earlier version of QGIS, save the model to an external file and then open it in the Graphical Modeller within QGIS 3.12.  

**QGIS and OS versions**

```

QGIS version | 3.12.0-București | QGIS code revision | cd141490ec
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Windows 10 (10.0)
Active python plugins | lrs; quick_map_services; travel_time_platform_plugin; db_manager; MetaSearch; processing

```

**Comment by nyalldawson** [comment]
@marcusyoung 
https://github.com/qgis/QGIS/pull/34637 fixes this -- you could copy the .py files from that pull request over your local copy in order to restore this functionality prior to the next round of releases...

**Comment by j-lippmann** [comment]
Thanks for the fix @nyalldawson . Is there a backport for 3.10 ?

**Comment by nyalldawson** [comment]
Yes, it was already done
