### ISSUE TITLE
QGIS reading wrong projection

### ISSUE THREAD

**Issue by PhilipWhitten** [qgis/QGIS#34633]
When we load rasters (.asc file extensions) QGIS is allocating the wrong projection.  I have attached a projection file to this report.  For the projection file attached, QGIS is allocating the projection EPSG 7856 (GDA 2020), but, the correct projection is EPSG 28356 (GDA 1994).  We are using QGIS 3.4.12.  I added a file extension of .txt to the attached file so that it would load to this forum.
[Burragorang-DEM-AHD_56_5m.prj.txt](https://github.com/qgis/QGIS/files/4247646/Burragorang-DEM-AHD_56_5m.prj.txt)

**Comment by NathanW2** [comment]
It might be best to use 3.10.3 as there have been a lot of fixes in proj,
GDAL, and QGIS for this stuff.

**Comment by nyalldawson** [comment]
Yes - try QGIS 3.4.15 if you have to stick with 3.4, but be aware that it's EOLed and any bugs in it won't be fixed.

3.10.3 has MUCH MUCH improved projection handling.

**Comment by nyalldawson** [comment]
Confirmed not an issue on proj 6 based builds
