### ISSUE TITLE
No rubber band using 3D measurement tool

### ISSUE THREAD

**Issue by kadirsahbaz** [qgis/QGIS#34630]
**Describe the bug**
When using 3D measurement tool, rubber band which represents a path from the last point you snapped to the current position doesn't appear. 

**How to Reproduce**

![3d](https://user-images.githubusercontent.com/15310223/75205650-6382ba00-5785-11ea-9e18-c3f997519b80.gif)

**QGIS and OS versions**

QGIS version
3.12.0-București
QGIS code revision
cd141490ec
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.1
Running against PROJ
Rel. 6.3.1, February 10th, 2020
OS Version
Windows 10 (10.0)
Active python plugins
openlayers_plugin; 
pluginbuilder3; 
QuickOSM; 
QuickWKT; 
db_manager; 
MetaSearch; 
processing

**Comment by ismailsunni** [comment]
Confirmed on 3.12 on Ubuntu 18.04, I think we need a regression label @gioman
