### ISSUE TITLE
Crashing when closing 3D measurement tool window

### ISSUE THREAD

**Issue by kadirsahbaz** [qgis/QGIS#34632]
**Describe the bug**
When trying to close 3d Measurement Tool window after closing 3D Map Viewer, QGIS crashes

**How to Reproduce**
- Open 3D Map Viewer
- Click 3D measurement tool button
- Close 3D Map Viewer window
- Try to close 3D measurement tool window

![3d2](https://user-images.githubusercontent.com/15310223/75206035-83ff4400-5786-11ea-9be2-ae4c33b1849d.gif)

**QGIS and OS versions**

QGIS version
3.12.0-București
QGIS code revision
cd141490ec
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.1
Running against PROJ
Rel. 6.3.1, February 10th, 2020
OS Version
Windows 10 (10.0)
Active python plugins
openlayers_plugin; 
pluginbuilder3; 
QuickOSM; 
QuickWKT; 
db_manager; 
MetaSearch; 
processing

**Comment by roya0045** [comment]
@ismailsunni I've checked the code and noticed that the chain of reseting occur around here https://github.com/qgis/QGIS/blob/85caa70e76bc6d9b29245c21906a969c85692d7c/src/app/3d/qgs3dmeasuredialog.cpp#L167 when the dialog is closed. Though I'm not too familiar with the 3d stuff, I couldn't find a simple way to check if the 3d canvas was still active/open before performing that action. Any idea?

**Comment by roya0045** [comment]
@ismailsunni I made a PR to address this, though I still need to test it. Just to let know you in case you were about to start something.

**Comment by ismailsunni** [comment]
Hi, @roya0045 thanks for the incoming PR. I am not so sure I will have time to check and fix it, so please go ahead :)
