### ISSUE TITLE
Processing : Dynamic dropdown list depending on selected layer

### ISSUE THREAD

**Issue by Ailurupoda** [qgis/QGIS#34643]
Hi, i'm not sure if it's a new feature to add or if it already exists and i didn't managed to find out.
**Feature description.**
Creating a processing algorithm, i would like to have a field that can feel depending to the layer selected. Like when using a ParameterField, but with custom data inside that would be different depending on the layer (Not like a ParameterEnum that has always the same list).

**Additional context**
In my case for example, i would like to have the list of the schema contained on the database where the layer come from.
I have a layer: **Layer1**, from a database : **Database1** and a layer : **LayerA** from a database : **DatabaseA**.
My **Database1** got the schemas **[schema1, schema2, schema3]** and my **DatabaseA** got the schemas **[schemaA, schemaB, schemaC].**

In my processing interface, i want to have a field that display the list of schema when i select a layer.
If **Layer1** is selected, then my field displays the values **[schema1, schema2, schema3]**
If i switch to **LayerA**, then it displays **[schemaA, schemaB, schemaC]**

Thanks

**Comment by nyalldawson** [comment]
This is possible with the new dedicated Database Schema parameters coming in QGIS 3.14
