### ISSUE TITLE
Topology checker: add a "line intersection" rule

### ISSUE THREAD

**Issue by ovillama** [qgis/QGIS#34657]
Solicito que en las reglas de topología se incluya  la "intersección" entre capas con geometría tipo linea, lo que  puede ocurrir entre la misma capa o entre capas diferentes. también lineas intersectadas con polígonos

Por ejemplo para curvas de nivel de cartografía se requiere verificar esta regla topológica ya que no puede cruzarse ente si mismas,  en el segundo caso vías no interctan cuerpos de agua (lagunas)

**Comment by roya0045** [comment]
English pls.

**Comment by gioman** [comment]
> I request that the "intersection" between layers with line type geometry be included in the topology rules, which may occur between the same layer or between different layers. also intersected lines with polygons. For example, for mapping level curves it is necessary to verify this topological rule since it cannot cross between themselves, in the second case roads do not interfere with bodies of water (lagoons) and as there are more cases.

@ovillama can you specify exactly in what tool you would like this option added?


> , I would need it since I am testing in tests to see if the change of production to this free software is good.

great, but with Open Source is not just a matter of what the software can do for you, but also of what you can do for the software. If the lack of this option is what separates you from choosing QGIS and a proprietary GIS then remember that probably you can get the missing functionality for a fraction of the cost of the proprietary software licenses.

**Comment by ovillama** [comment]
It is to complete the topology tool, adding within the rules, the
intersection between lines, with itself or with other elements that
can be lines or polygons.

It is to complete the topology tool



Thanks for your interest



*Olga Cecilia Villamarín Mesa*
*Profesional Especializado*
*Subdirección de Geografía y Cartografía*
*GIT Modernización **, Evaluación y Seguimiento** de Productos Geodésicos,
Geográficos ** y **Cartográficos*

3694000 Extensión 91175
Carrera 30 No. 48-51, Bogotá
Sede Central Bogotá
*www.igac.gov.co <http://www.igac.gov.co>*


[image: Redes_IGAC]
<https://www.google.com/url?q=https%3A%2F%2Fwww.facebook.com%2FIgacColombia%2F&sa=D&sntz=1&usg=AFQjCNFJPekPJXNBKeoMA-gvHMYNSeubAw>

**Comment by gioman** [comment]
> It is to complete the topology tool

do you mean the "topology checker" tool?
https://docs.qgis.org/testing/en/docs/user_manual/plugins/core_plugins/plugins_topology_checker.html

**Comment by ovillama** [comment]
Yes, it is for the topology verification, which is missing the intersection





*Olga Cecilia Villamarín Mesa*
*Profesional Especializado*
*Subdirección de Geografía y Cartografía*
*GIT Modernización **, Evaluación y Seguimiento** de Productos Geodésicos,
Geográficos ** y **Cartográficos*

3694000 Extensión 91175
Carrera 30 No. 48-51, Bogotá
Sede Central Bogotá
*www.igac.gov.co <http://www.igac.gov.co>*


[image: Redes_IGAC]
<https://www.google.com/url?q=https%3A%2F%2Fwww.facebook.com%2FIgacColombia%2F&sa=D&sntz=1&usg=AFQjCNFJPekPJXNBKeoMA-gvHMYNSeubAw>

**Comment by uclaros** [comment]
You can also do topological checking, including checking for intersecting lines, with the *Check Geometries* tool.
