### ISSUE TITLE
flatpak install doesn't work

### ISSUE THREAD

**Issue by rustygreen** [qgis/QGIS#34669]
**Describe the bug**
Can't install QGIS using Flatpak (using latest Clear Linux release)

**How to Reproduce**
1. Install QGIS using flatpack instructions here: https://clearlinux.org/software/flathub/qgis-desktop

NOTE: Issue also occurs if following instructions from here: https://www.qgis.org/en/site/forusers/alldownloads.html#flatpak

![qgis-error](https://user-images.githubusercontent.com/1774477/75295656-3243d180-57f9-11ea-9c20-95cdd88a0631.png)

**System**
* Dell XPS 13 (9370)
* Clear Linux

**Comment by roya0045** [comment]
Still occurs?

**Comment by alexbruy** [comment]
Closing for the lack of feedback.

**Comment by rustygreen** [comment]
> Still occurs?

This issue is fixed now. Thanks.
