### ISSUE TITLE
Merge features in a postgis layer fails to assign primary key

### ISSUE THREAD

**Issue by GISsymbology** [qgis/QGIS#34666]
When two records is merged in a  postGIS layer, QGIS try to assign the primary key of one object to the new object but it fails, so the old geometries are deleted but the new one is not saved. 
The result is that geometry is lost.

to reproduce:
1. Edit a postGIS layer
2. Select two geometries
3. Merge geometries
4. Save
5. See error:

2020-02-25T21:52:31     CRITICAL    Layer prova : PostGIS error while adding features: ERRORE: valori null nella colonna "vald_id" violano il vincolo non-null
             DETTAGLI: La riga in errore contiene (null, 0106000020787F000001000000010300000001000000080000008C53153F7EE0).
             
2020-02-25T21:52:31     WARNING    Commit errors : Could not commit changes to layer Valanghe documentate

QGIS version | 3.12.0-București | QGIS code branch | Release QGIS code branch.3
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 12.2 (Ubuntu 12.2-2.pgdg18.04+1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Linux Mint 19.3
Active python plugins | lizmap; qgis_resource_sharing; quick_map_services; db_manager; processing; MetaSearch

On QGIS 3.10 the error is slight different:

2020-02-25T21:43:51     WARNING    Commit errors : Could not commit changes to layer prova 
2020-02-25T21:44:44     WARNING    Invalid result : Could not store value 'Skipped' in field of type int4.
2020-02-25T21:45:13     CRITICAL    Layer prova : PostGIS error while adding features: ERRORE: valori null nella colonna "gid" violano il vincolo non-null
             DETTAGLI: La riga in errore contiene (null, 2020-02-25 21:45:37.993019, 0106000020787F0000010000000103000000010000000A000000769CD04B470B).

QGIS version | 3.10.3-A Coruña | QGIS code revision | 0e1f846438
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 10.12 (Ubuntu 10.12-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Linux Mint 19.3
Active python plugins | lizmap; qgis_resource_sharing; quick_map_services; db_manager; MetaSearch; processing

**Comment by elpaso** [comment]
Please attach a SQL DB dump to reproduce the issue.

**Comment by GISsymbology** [comment]
[test.zip](https://github.com/qgis/QGIS/files/4252490/test.zip)

**Comment by GISsymbology** [comment]
Activate the flag:  "evaluate value on server side"  in project properties
