### ISSUE TITLE
prj files not being read correctly 

### ISSUE THREAD

**Issue by geomenke** [qgis/QGIS#34660]
When adding a shapefile to a new QGIS project, even with a new profile, QGIS does not read the PRJ correctly. In the attached example, the shapefile is in EPSG: 4269. When added to QGIS via the Browser panel, the Select Transformation window opens which correctly reads the datum.

![SelectTransformation](https://user-images.githubusercontent.com/4527589/75270862-7fec1a00-57b8-11ea-8e99-210c03cf53a5.jpg)

After taking the default transformation QGIS reads it as having an unknown CRS, but the description that follows is correct.

![LayerProperties](https://user-images.githubusercontent.com/4527589/75270593-0a804980-57b8-11ea-9c2f-2eb8ef9bfae5.jpg)

This happens with other CRSs as well. Below are the details of the QGIS version.

QGIS version 3.12.0-București
QGIS code revision cd141490ec
Compiled against Qt 5.11.2
Running against Qt 5.11.2
Compiled against GDAL/OGR 3.0.4
Running against GDAL/OGR 3.0.4
Compiled against GEOS 3.8.0-CAPI-1.13.1
Running against GEOS 3.8.0-CAPI-1.13.1 
Compiled against SQLite 3.29.0
Running against SQLite 3.29.0
PostgreSQL Client Version 11.5
SpatiaLite Version 4.3.0
QWT Version 6.1.3
QScintilla2 Version 2.10.8
Compiled against PROJ 6.3.1
Running against PROJ Rel. 6.3.1, February 10th, 2020
OS Version Windows 10 (10.0)
Active python plugins
db_manager; 
MetaSearch; 
processing

[prj_issue_example_project_and_data.zip](https://github.com/qgis/QGIS/files/4251171/prj_issue_example_project_and_data.zip)

**Comment by nyalldawson** [comment]
This is a gdal issue:


Running ogrinfo on the attached file gives a projection definition

Layer SRS WKT:
```
GEOGCRS["GCS_Assumed_Geographic_1",
    DATUM["North American Datum 1983",
        ELLIPSOID["GRS 1980",6378137,298.257222101,
            LENGTHUNIT["metre",1]],
        ID["EPSG",6269]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["Degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["longitude",east,
            ORDER[1],
            ANGLEUNIT["Degree",0.0174532925199433]],
        AXIS["latitude",north,
            ORDER[2],
            ANGLEUNIT["Degree",0.0174532925199433]]]
```

Plugging ogr's detected CRS into projinfo --identify reports:
```
Identification match count: 1
ESRI:104000: 25 %
```
(QGIS requires a 70% match).

In constrast, plugging the .prj contents directly into projinfo reports:

```
Identification match count: 2
EPSG:4269: 70 %
ESRI:104000: 25 %
```

**Comment by nyalldawson** [comment]
Filed upstream: https://github.com/OSGeo/gdal/issues/2270

**Comment by nyalldawson** [comment]
Not a bug -- this shapefile DOES have a custom CRS. See upstream ticket.

**Comment by geomenke** [comment]
Thanks for checking this out and filing a gdal ticket, much appreciated! It's a layer provided by a client created in some off the shelf GPS hiking program.
