### ISSUE TITLE
WMS renders partially in full screen

### ISSUE THREAD

**Issue by pshf** [qgis/QGIS#34663]
When loading an non-public WMS raster image layer rendering fails when QGIS window is maxed to 2560x1440 px on Windows 7.
Layer is received correctly, shows up for 0.2 seconds and display only partially on the right side.

When QGIS window is "restored" e.g. to full heigth and width about 2300px the layer renders normally.

This behaviour started with v 3.10 and persists with 3.12. Other WMS layers render fine. So I assume it has something to do with the wms data type. What else can I contribute to narrow down the cause? It's a pity the wms source is intranet only. This particular layer is rendered fine in ArcGIS.
[screencast_WMS_render_bug.zip](https://github.com/qgis/QGIS/files/4251930/screencast_WMS_render_bug.zip)

**QGIS and OS versions**

QGIS-Version | 3.12.0-București | QGIS-Codeversion | cd141490ec
-- | -- | -- | --
Kompiliert gegen Qt | 5.11.2 | Laufendes Qt | 5.11.2
Kompiliert mit GDAL/OGR | 3.0.4 | Läuft mit GDAL/OGR | 3.0.4
Kompiliert mit GEOS | 3.8.0-CAPI-1.13.1 | Läuft mit GEOS | 3.8.0-CAPI-1.13.1
Kompiliert mit SQLite | 3.29.0 | Läuft mit SQLite | 3.29.0
PostgreSQL-Client-Version | 11.5 | SpatiaLite-Version | 4.3.0
QWT-Version | 6.1.3 | QScintilla2-Version | 2.10.8
Kompiliert mit PROJ | 6.3.1 | Läuft mit PROJ | Rel. 6.3.1, February 10th, 2020
BS-Version | Windows 7 SP 1 (6.1)
Aktive Python-Erweiterungen | db_manager; MetaSearch; processing

**Comment by gioman** [comment]
@pshf what the QGIS log says (in english)? are you sure that the server has not a limitation in terms of possible max WxH of the served images?

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
