### ISSUE TITLE
Dark mode problem

### ISSUE THREAD

**Issue by urbayo** [qgis/QGIS#34687]
**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by urbayo** [comment]
when open the color pallet window, the first time it is always just half window, so one need to close it and open/click it once again to be fully visualized. It is not a big issue but it a little bit annoying sometimes :)

**Comment by Saijin-Naib** [comment]
Same but for regular theme:
Issue #33324

**Comment by gioman** [comment]
Closing as duplicate.
