### ISSUE TITLE
Traiiling "?" is removed from a WMS URL so the QGIS browser does not show anymore the content of groups

### ISSUE THREAD

**Issue by Thsi0815** [qgis/QGIS#34692]
New description: https://github.com/qgis/QGIS/issues/34692#issuecomment-591878120

##############

Old description:

![Annotation 2020-02-26 133422](https://user-images.githubusercontent.com/61503307/75345348-da5ea680-589c-11ea-9d3c-77f49abbb12c.png)

The new qgis version: 3.1.2 does not accept any special characters like "?" in the URL-address of a WMS-Source. After a refresh of the working wms-source the url and the source does no more work.

**Comment by gioman** [comment]
@Thsi0815 works ok here, can you provide an URL?

**Comment by Thsi0815** [comment]
http://www.geoportal.rlp.de/mapbender/php/wms.php?layer_id=61680&VERSION=1.1.1&withChilds=1Am 26.02.20, 18:33 schrieb Giovanni Manghi <notifications@github.com>:

  @Thsi0815 works ok here, can you provide an URL?

**Comment by gioman** [comment]
> http://www.geoportal.rlp.de/mapbender/php/wms.php?layer_id=61680&VERSION=1.1.1&withChilds=1Am 26.02.20, 18:33 schrieb Giovanni Manghi <notifications@github.com>:

@Thsi0815 works fine here (3.10.3 on Windows as also 3.12.0)

![Screenshot_20200226_190614](https://user-images.githubusercontent.com/1951107/75378151-1ad51900-58cb-11ea-9778-fc6502f0f348.png)

**Comment by Thsi0815** [comment]
Sorry, but on my installation I could not insert any kind of special character in the URL field.Tomorrow I will setup and test the new version once again.I will send you the result tomorrowThank you...  :-)Am 26.02.20, 20:07 schrieb Giovanni Manghi <notifications@github.com>:

   
   http://www.geoportal.rlp.de/mapbender/php/wms.php?layer_id=61680&VERSION=1.1.1&withChilds=1Am 26.02.20, 18:33 schrieb Giovanni Manghi notifications@github.com: 
   
  @Thsi0815 works fine here (3.10.3 on Windows as also 3.12.0)

**Comment by gioman** [comment]
> Sorry, but on my installation I could not insert any kind of special character in the URL field.Tomorrow I will setup and test the new version once again.I will send you the result tomorrowThank you..

I copy/pasted your URL, are you writing it manually?

**Comment by Thsi0815** [comment]
Good morning

sorry I have to substantiate my issue:

If there is a special character "on the end" of an URL, it will be delete in the 3.12 version.

You can try the URL: http://wmts1.geoportal.lu/opendata/service?

and you see on the screenshots the difference.

Sorry

      Matthias

 

 

Sorry, but on my installation I could not insert any kind of special character in the URL field.
Tomorrow I will setup and test the new version once again.
I will send you the result tomorrow
Thank you... :-)

Am 26.02.20, 20:07 schrieb Giovanni Manghi <notifications@github.com>:


http://www.geoportal.rlp.de/mapbender/php/wms.php?layer_id=61680&VERSION=1.1.1&withChilds=1Am 26.02.20, 18:33 schrieb Giovanni Manghi notifications@github.com:


@Thsi0815 works fine here (3.10.3 on Windows as also 3.12.0)

**Comment by gioman** [comment]
> If there is a special character "on the end" of an URL, it will be delete in the 3.12 version.

Yes I see, but the "?" at the end of that URL is also useless as it is used to attach the address other service parameters.... but the are none (after the final "?"), so it is useless and does not harm removing it.

**Comment by Thsi0815** [comment]
The goal with the "?" on the end is, that you will get the list of all the sub WMS-sources.

Without you have to setup every single WMS-source and you have to know the url-details.

In the 3.10 version I can setup the URL with the "?" on the end and I get all sub wms-source automatically.

 
 

Gesendet: Donnerstag, 27. Februar 2020 um 10:21 Uhr
Von: "Giovanni Manghi" <notifications@github.com>
An: qgis/QGIS <QGIS@noreply.github.com>
Cc: Thsi0815 <computer@online.ms>, Mention <mention@noreply.github.com>
Betreff: Re: [qgis/QGIS] QGIS 3.12.0 - URL issue in WMS Sources (No "?" allowed in URL) (#34692)



If there is a special character "on the end" of an URL, it will be delete in the 3.12 version.


Yes I see, but the "?" at the end of that URL is also useless as it is used to attach the address other service parameters.... but the are none (after the final "?"), so it is useless and does not harm removing it.

**Comment by gioman** [comment]
@Thsi0815 I can't see any difference. 

3.10.3

![Screenshot_20200227_094733](https://user-images.githubusercontent.com/1951107/75432414-49440a00-5946-11ea-819d-c445c835f0eb.png)


3.12.0

![Screenshot_20200227_094757](https://user-images.githubusercontent.com/1951107/75432431-4ea15480-5946-11ea-86ff-8c907d0fd42e.png)

**Comment by gioman** [comment]
@Thsi0815 ah sorry, I see the difference in the browser....

**Comment by gioman** [comment]
@Thsi0815 tagging as regression

**Comment by pathmapper** [comment]
I'm running in a similar issue which might be related:

After adding a WMS with the following URL to the browser with QGIS 3.12.0 the available WMS layers are not displayed in the browser:
https://www.wms.nrw.de/geobasis/wms_nw_dop 

With QGIS 3.10.1 they are displayed in the browser.

**Comment by Samweli** [comment]
Related to https://github.com/qgis/QGIS/issues/34798, currently working on a fix..

**Comment by pathmapper** [comment]
I think this is fixed in `3.12.1` and could be closed.
