### ISSUE TITLE
DEM parameter error in Directional slope

### ISSUE THREAD

**Issue by Dhanesh-shirsat** [qgis/QGIS#34693]
Tin interpolation, i choose interpolation attribute as ELEVATION, Interpolated method as Linear, And use layer extent, after that for output raster size i have entered pixel size X & Y as 1 and run the Tin interpolation by saving it as raster file.

after that, In Direction slope i choose Zevenbergen and Thorne (1987) method with slope along direction is 90/180/90 and run. then DEM parameter error occurs. which says pixel sizes in X & Y direction are different in raster.

**What step should be taken to avoid that error**

**QGIS- 3.10.2and  OS versions- Windows 7,**

****

**Comment by alexbruy** [comment]
This is known issue. Until it is fixed, as workaround you can resample DEM to desired resolution using GDAL.

**Comment by Dhanesh-shirsat** [comment]
Will you please elaborate more about it. so that i can get idea what to do?

**Comment by gioman** [comment]
> Will you please elaborate more about it. so that i can get idea what to do?

@Dhanesh-shirsat he means that out of the TIn tool you may not get perfectly square pixels (must be fixed at some point), so just resample your DEM using one of the many options in QGIS, like the tool based GDAL.

**Comment by gioman** [comment]
> This is known issue

@alexbruy is there already a ticket for it?

**Comment by alexbruy** [comment]
@gioman can't find ticket right now, but I remember there were some reports about this.

**Comment by Dhanesh-shirsat** [comment]
@alexbruy we also tried it by using GDAL tool. we are facing same problem with this tool.
will you able to elaborate what step should i follow to incorporate that DEM parameter error by using GDAL tool?

**Comment by alexbruy** [comment]
Can you provider sample data and detailed steps to reproduce issue?

**Comment by alexbruy** [comment]
Closing due the lack of feedback.
