### ISSUE TITLE
Problem creating GeoPDF with layers. 

### ISSUE THREAD

**Issue by urbayo** [qgis/QGIS#34694]
When trying to export layered PDF via this new feature it simply does not work. Both "create geospatial PDF" and "include vector feature information" are checked. When press save, it shows the yellow line on the top saying "could not save the map to PDF", without any further info/explanation about the error. However a PDF file is created, where everything is blank, but the layer function is active and the structure of the layers with the titles is there as well. 
Windows 10 64, QGIS 3.10.3

![image](https://user-images.githubusercontent.com/61496472/75346689-ef8d0280-58a7-11ea-8c8f-8a0ff1a5c405.png)

![image](https://user-images.githubusercontent.com/61496472/75346811-29f69f80-58a8-11ea-93ed-d471a2475bf4.png)

**Comment by gioman** [comment]
@urbayo works fine here on 3.12.0 and 3.10.3. Can you attach a sample project?

**Comment by urbayo** [comment]
Hi @gioman. After several hours of trying different options it did not work. I have tried to set just one file, or several files, or only in Latin (since I have several in Cyrillic) or some other options and it did give an error, so finally i did it in Arcmap where it was without any problem. However, today before responding to you and attaching a file you have requested, i have tried once again and it did work with even several files. I have restarted the computer yesterday, and til now it was hibernating, nothing has been changed, so it is still quite mysterious. 10x anyway :)

**Comment by gioman** [comment]
@urbayo closing?

**Comment by nirvn** [comment]
This sounds a lot like some user access issue to the temporary directory (needed to export Geo PDF), possibly upon resuming an hybernated system with QGIS open or something.

Wouhou to reboot fixing things magically ;)

**Comment by evans-otis** [comment]
Hello I am trying to create a geospartial PDF but it does not work, anybody with the same problem? How did you solve it?

**Comment by mconsidine** [comment]
I have the same problem with 3.16 on Linux.  It will export to an image with "append georeferenced information" checked.  But it will throw an error if I try to create a geospatial PDF *unless* I *uncheck* "append georeferenced information".  Which I think makes the resulting PDF not georeferenced, because the info is not embedded.

**Comment by agiudiceandrea** [comment]
> have the same problem with 3.16 on Linux. It will export to an image with "append georeferenced information" checked. But it will throw an error if I try to create a geospatial PDF _unless_ I _uncheck_ "append georeferenced information". Which I think makes the resulting PDF not georeferenced, because the info is not embedded.

@mconsidine was the map rotated?

**Comment by mconsidine** [comment]
It's been awhile.  I'd need to try to recreate.
Mconsidine

**Comment by aloboa** [comment]
Why is this closed? I am experiencing the same problem.
