### ISSUE TITLE
Composer Exports Text as Image in SVG or PDF

### ISSUE THREAD

**Issue by MicheleTobias** [qgis/QGIS#34709]
QGIS Version 3.12
Windows 10

When exporting a map from the print composer, the SVG and PDF both do not have selectable text.  The text appears to be a part of a raster image.

To re-create the issue:
1. Compose a map in the print composer.  Include a raster layer, and a vector layer with text labels.
2. Export either a .svg or .pdf file - it doesn't matter if you select the option to have text exported as text or a path or if you have it group the layers or not - all the options produce the same results.
3. Open the .svg or .pdf in a vector illustration software like Inkscape, ungroup layers, try to select a text object, but find it's a part of the image that was the raster data.

**Comment by nyalldawson** [comment]
Michele -- can you check if your labels use settings like blend modes? This will force rasterisation of them. Also try checking the "always export as vectors" option in the pdf export options dialog.

**Comment by MicheleTobias** [comment]
Checking "always export as vectors" fixed it.  I wasn't using a blending mode.  Thanks for this! I'm glad it's not a real bug.

**Comment by nyalldawson** [comment]
Could you share your project?

**Comment by MicheleTobias** [comment]
Sadly, I cannot share it because it's for a paper that will be published.

**Comment by nyalldawson** [comment]
What about just the qml from the layer?

**Comment by gioman** [comment]
@nyalldawson closing?

**Comment by nyalldawson** [comment]
Closing as not reproducible
