### ISSUE TITLE
Qgis crashes after closing.

### ISSUE THREAD

**Issue by Heryx** [qgis/QGIS#34708]
## User Feedback

I closed Qgis and it crashed.

## Report Details

*Crash ID*: 41bd556bfb4cb3857ad8b303df49560eb10217ac

*Stack Trace*
<pre>
proj_lpz_dist :
proj_lpz_dist :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::QgsCoordinateTransform :
QHashData::free_helper :
QgsCoordinateTransform::addToCache :
QgsCoordinateTransform::invalidateCache :
QgsApplication::exitQgis :
QgisApp::~QgisApp :
CPLStringList::operator char const * __ptr64 const * __ptr64 :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.4.10-Madeira
QGIS code revision: 3d97aaae88
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by nyalldawson** [comment]
Please update to a newer patch release -- this bug was already fixed.
