### ISSUE TITLE
Foreign key constraints checks are ignored on GPKG 

### ISSUE THREAD

**Issue by elpaso** [qgis/QGIS#34728]
see: https://github.com/qgis/QGIS/pull/9939#issuecomment-591909825

I added the "Data corruption" flag because that's what a disabled foreign key check does.

**Comment by m-kuhn** [comment]
@elpaso I think we need more information here.

Short summary of #9939 objectives. Before it QGIS was not able to open GeoPackages with broken forigen keys (disaster recovery) at all. Now it allows opening these files.
Already before #9939 QGIS did not enforce foreign keys, so you could create broken GeoPackages. Making it very easy to produce broken gpkgs, but almost impossible to repair them.

**Comment by elpaso** [comment]
> @elpaso I think we need more information here.
> 

What kind of information? If you have a GPKG with foreign key constraints QGIS OGR provider sets PRAGMA to ignore foreign key constraints, this makes it possible to edit the layer in QGIS and enter values that violate the constraint(s).

> Short summary of #9939 objectives. Before it QGIS was not able to open GeoPackages with broken forigen keys (disaster recovery) at all. Now it allows opening these files.

Which is good, of course.

> Already before #9939 QGIS did not enforce foreign keys, so you could create broken GeoPackages. Making it very easy to produce broken gpkgs, but almost impossible to repair them.

AFAIK it's not QGIS to enforce the FK constraints but sqlite itself (when the PRAGMA foreign_key_check is set and it's a per-connection flag), I don't know if QGIS was producing corrupted files before that commit (but since the PRAGMA was not altered I don't see how) and honestly I don't care.

Let's agree that a sqlite (or GPKG) DB with broken FOREIGN KEY constraints is a "corrupted file".

That said, being able to open (recover/repair is another story) a corrupted file is not a good reason to allow QGIS to turn an **healthy** file into a **corrupted** file.

If we want to be able to "open" a corrupted file we should probably follow an approach that:

1. try to open the file in strict mode with all checks enabled
2. if that fails, retry with a more permissive mode, open the file in RO mode and issue a BIG WARNING to the user

The current situation is that QGIS is able to open an healthy file and produce a corrupted one that is not IMO a good thing at all.

**Comment by rouault** [comment]
#9939 didn't change anything regarding foreign key enforcement. It just disabled a check at open time that checks if there are violations of foreign keys in existing records.

According to https://www.sqlite.org/foreignkeys.html , "foreign key constraints are disabled by default (for backwards compatibility), so must be enabled separately for each database connection". So if we want to enforce them after database opening, one should issue a ExecuteSQL("PRAGMA foreign_keys = ON")

**Comment by elpaso** [comment]
@rouault ok, I misunderstood your comment then.

Anyway, this doesn't change the situation: I believe we should enable FK constraints by default and only fall back to RO mode and checks disabled if the datasource is "corrupted".

I see that is is overrideable with env var OGR_GPKG_FOREIGN_KEY_CHECK but that's not very user friendly.

**Comment by rouault** [comment]
> I see that is is overrideable with env var OGR_GPKG_FOREIGN_KEY_CHECK but that's not very user friendly.

Just to clarify: the effect of this env variable/config option, when set to YES, is to issue a "PRAGMA foreign_key_check" (one shot verification of the database). Not a "PRAGMA foreign_keys = ON" (verification "on-the-fly", while changes are done).

Otherwise there's a OGR_SQLITE_PRAGMA env variable/config option that applies to both OGR SQLite and GPKG drivers, and you could do CPLSetConfigOption("OGR_SQLITE_PRAGMA", "foreign_keys = ON") to turn on "on-the-fly" foreign key checking
