### ISSUE TITLE
Small API break on QGIS 3.10 QgsPoint(), QgsGeometry::atVertex api docs should be updated

### ISSUE THREAD

**Issue by JaviBecerra** [qgis/QGIS#34729]
(Found this while fixing ProfileTool plugin issue https://github.com/PANOimagen/profiletool/issues/35 )

(Not sure if this is to be reported as a break on the API or just that the documentation for both C++ and PyQgis apis should be updated)

QgsPoint() shows different behaviour on QGIS < 3.10 and QGIS >= 3.10

On QGIS Python console for QGIS 3.8:
```
>>> QgsPoint()
<QgsPoint: Point (0 0)>
```
On QGIS Python console for QGIS 3.10:
```
>>> QgsPoint()
<QgsPoint: Point EMPTY>
```

**Describe the bug**
Now QgsGeometry.vertexAt returns QgsPoint() on error (Point(0,0) prior to QGIS 3.10, Point: EMPTY afterwards), but the documentation (both C++ https://qgis.org/api/classQgsGeometry.html#a4de6615ad51648577d66983c6efd5203 and PyQgis  https://qgis.org/pyqgis/master/core/QgsGeometry.html#qgis.core.QgsGeometry.vertexAt ) states that QgsGeometry.vertexAt returns QgsPoint(0, 0) on error.

**How to Reproduce**
According to the API documentation, the following snippet run on QGIS Python console should return True: 
```
line = QgsGeometry.fromPolyline([QgsPoint(1,2),QgsPoint(3,4)])
line.vertexAt(2) == QgsPoint(0,0)
```
However it returns False instead of True for QGIS >= 3.10

The following code works (returns True) both on QGIS 3.8 and QGIS 3.10
```
line = QgsGeometry.fromPolyline([QgsPoint(1,2),QgsPoint(3,4)])
line.vertexAt(2) == QgsPoint()
```

**QGIS and OS versions**
Tested on Windows 8.1 with QGIS 3.6.0-Noosa (x64), QGIS 3.8.3-Zanzibar (x64) and QGIS 3.10.3-A Coruña (x64)

**Comment by lbartoletti** [comment]
@JaviBecerra According to the OGC standard, QgsPoint() should returns an Empty Point. Before Qgis 3.10, it returns QgsPoint(0,0) which was a bug.

Sees https://github.com/qgis/QGIS/pull/9645 and (all) PRs/issues related.

BTW, the documentation must be updated.

**Comment by lbartoletti** [comment]
![image](https://user-images.githubusercontent.com/7521540/95753873-87f2be80-0ca2-11eb-9806-84f1b3a4812d.png)
It's "fixed"

**Comment by JaviBecerra** [comment]
Thanks @lbartoletti!
