### ISSUE TITLE
Project with 3D View and certain symbology on 2D vector crashes with QGIS > 3.4.15-1

### ISSUE THREAD

**Issue by Saijin-Naib** [qgis/QGIS#34735]
**Describe the bug**
Project will open under 3.4.15-1.  
Project will hang/crash under 3.12.0.
Project will hang/crash under 3.13.0.
Project was initially created/worked with under 3.10.x

**How to Reproduce**
Project files: [34735.7z.zip](https://github.com/qgis/QGIS/files/4262918/34735.7z.zip)  
Open attached project (Town_3D_Terrain) and attempt to load.
Open attached project (Town_3D_Terrain_novector), and see that the same raster/extent loads fine.
Open attached project (Town_3D_Terrain_buildingsoff), and see that the data loads fine. Toggle on the Simplified layer, and see it hang/crash.

**QGIS and OS versions**

QGIS version | 3.4.15-Madeira | QGIS code revision | e83d02e274
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 2.4.3 | Running against GDAL/OGR | 2.4.3
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
Active python plugins | gupsapp; db_manager; MetaSearch; processing

QGIS version | 3.12.0-București | QGIS code revision | cd141490ec
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Windows 10 (10.0)
Active python plugins | db_manager; MetaSearch; processing

QGIS version | 3.13.0-Master | QGIS code revision | 39a9ae9dfd
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.0dev | Running against GDAL/OGR | 3.1.0dev
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 7.0.0 | Running against PROJ | Rel. 7.0.0, March 1st, 2020
OS Version | Windows 10 (10.0) | This copy of QGIS writes debugging output.
Active python plugins | db_manager; MetaSearch; processing

**Additional context**
3.4.15-1  
![image](https://user-images.githubusercontent.com/19295950/75465215-4d782380-5956-11ea-823b-965cb2aef150.png)

3.12.0  
![image](https://user-images.githubusercontent.com/19295950/75463297-9aa6c600-5953-11ea-8dbb-fa517378735e.png)

3.13  
![image](https://user-images.githubusercontent.com/19295950/75464941-eeb2aa00-5955-11ea-9fc8-609c0a3ba9d8.png)

**Comment by saberraz** [comment]
Could you share the project?

**Comment by Saijin-Naib** [comment]
> Could you share the project?

Yeah, sorry, I was just compressing it to add it into my issue above.

**Comment by saberraz** [comment]
data? :)

**Comment by nirvn** [comment]
Stick to LTR for upmost stability, and use newer release to make sure regressions are spotted and properly reported (with as much information as possible and test projects/data).

Merely sticking to LTR risks having your own workflow regressions never found.

**Comment by Saijin-Naib** [comment]
@saberraz 
> data? :)

In the my first post.

> Project files: 34735.7z.zip

https://github.com/qgis/QGIS/files/4262918/34735.7z.zip

**Comment by Saijin-Naib** [comment]
> Stick to LTR for upmost stability, and use newer release to make sure regressions are spotted and properly reported (with as much information as possible and test projects/data).
> Merely sticking to LTR risks having your own workflow regressions never found.

I'm not sure I understand what you're saying, but I'll explain what I have posted above.

I run three independent QGIS installs/environments in parallel:
LTS (Census GeoBAS/GUPS)
Stable (Production)
Nightly (Testing)

I created the project starting with 3.10 when 3.10 was stable. I have not touched it since due to other tasks taking precedent.

Discovered that my project that worked just fine under 3.10 will not work under 3.12 stable nor 3.13 nightly, but rather only 3.14.15-1 LTS.

I have included all salient details I know to include, as well as the requested test data and project. What else am I missing?

**Comment by nirvn** [comment]
You're doing it right :)

**Comment by Saijin-Naib** [comment]
> You're doing it right :)

Oh okay, haha. I didn't know if I was missing something you guys needed and I was confused about what I could have missed aside from possibly crash logs/traces (which are normally by request, right?)

Thanks for your help!

**Comment by saberraz** [comment]
Works fine for me:
![image](https://user-images.githubusercontent.com/2649047/75752783-4cae0b80-5d21-11ea-869c-a72c384fdee1.png)

**Comment by Saijin-Naib** [comment]
... 😑
Do you not have an AMD GPU?

Let me test on my home NVIDIA as well

**Comment by saberraz** [comment]
hmmmm...I can replicate the issue, if I run QGIS by clicking on the shortcut I have created on my panel.

But if I run it from my output/bin/ folder (where I have compiled it) in terminal, it works!! 

Makes me this should be some environment settings set up correctly in the shell but not in the DE????

**Comment by Saijin-Naib** [comment]
Oh, that's super strange... Is there a QT version mis-match between the QGIS from the repository and the QGIS you compiled?

**Comment by saberraz** [comment]
nope, it is just a shortcut to the same executable!

**Comment by Saijin-Naib** [comment]
Behavior still the same:  

QGIS version | 3.14.15-Pi | QGIS code revision | d5114d2cfa
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | bettereditor; CalculateGeometry; MemoryLayerSaver; quick_map_services; slyr; SpreadsheetLayers; zoom_level; db_manager; MetaSearch; processing

**Comment by Saijin-Naib** [comment]
> hmmmm...I can replicate the issue, if I run QGIS by clicking on the shortcut I have created on my panel.
> But if I run it from my output/bin/ folder (where I have compiled it) in terminal, it works!!
> Makes me this should be some environment settings set up correctly in the shell but not in the DE????

**Comment by Saijin-Naib** [comment]
Behavior still present, even with OpenCL Disabled:  

QGIS version | 3.14.16-Pi | QGIS code revision | df27394552
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | bettereditor; CalculateGeometry; MemoryLayerSaver; ORStools; slyr; SpreadsheetLayers; zoom_level; db_manager; MetaSearch; processing

**Comment by Pedro-Murteira** [comment]
@Saijin-Naib Hello, is this still valid on recent versions?

**Comment by Saijin-Naib** [comment]
Seems to be worse, even. Can't get any of the projects to load with latest stable Flatpak release. They all just endlessly load with CPU pegged on all cores.

**Comment by alexbruy** [comment]
No crashes with the latest master (e5e6a13671) on Linux.

**Comment by Saijin-Naib** [comment]
Still need to test/repro
