### ISSUE TITLE
DB Manager - semicolon does not get stripped from meta query

### ISSUE THREAD

**Issue by geozelot** [qgis/QGIS#34731]
**Describe the bug**
The automated `__rid__`  meta query wrapping doesn't strip the trailing `;` from the passed in query text.

**How to Reproduce**
Run any query in DB Manager, having a trailing `;`, e.g.:
```
SELECT *
FROM   <table>
;
```

**QGIS and OS versions**

QGIS version | 3.12.0-București | QGIS code revision | 409bcf8eaa
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 10.12 (Ubuntu 10.12-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Linux Mint 19.1
Active python plugins | Qgis2threejs; FreehandRasterGeoreferencer; refFunctions; processing; MetaSearch; db_manager

**Additional context**

Example Log output:
```
2020-02-27T14:06:16   WARNING    Unable to execute the query.
        The error message from the database was:
        ERROR: syntax error at or near ";"
        LINE 1: ... () AS __rid__, * FROM (SELECT * FROM issue_test ;) as foo)...
         ^
        .
        SQL: SELECT * FROM (SELECT row_number() OVER () AS __rid__, * FROM (SELECT * FROM issue_test ;) as foo) AS "subQuery_0" LIMIT 1
```

**Comment by gioman** [comment]
Confirmed, regression.

**Comment by roya0045** [comment]
For future reader here is some info https://github.com/qgis/QGIS/issues/35426#issuecomment-605627406

**Comment by gioman** [comment]
This seems fixed.
