### ISSUE TITLE
Toolbar buttons gets highlighted instead of active

### ISSUE THREAD

**Issue by oskarlin** [qgis/QGIS#34733]
**Describe the bug**
Sometimes when I click on a button in the Toolbar, the button gets highlighted but not activated. It gets darker grey but not "active". 

**How to Reproduce**

**QGIS and OS versions**
QGIS 3.10 and 3.12 has the same problem. Not QGIS 3.8
Running MacOS Catalina

**Additional context**
<img width="150" alt="Screenshot 2020-02-27 at 15 13 29" src="https://user-images.githubusercontent.com/2736990/75453387-23cdf500-5974-11ea-99b0-bbc90a4ae69e.png">

**Comment by Pedro-Murteira** [comment]
@oskarlin I've tested this but I couldn't reproduce it. Is this still an issue with you? (Tested on macOS Monterey 12.0.1, QGIS 3.22.2.)
