### ISSUE TITLE
Bad performance of Oracle provider when reloading a project

### ISSUE THREAD

**Issue by tomass** [qgis/QGIS#34737]
**Bug description**

When QGIS project uses data from a large (several million rows) oracle view it is very slow to re-query geometry type each time QGIS project is opened. Each time while opening a project (including when creating a new QGIS Server instance in apache on high server load) geometry type of a layer is re-checked which is probably unnecessary and could be skipped.

While on Desktop there could theoretically be situations when geometry type changes on existing layer, I'm not sure the rest of layer settings would work correctly (for example styling settings if geometry type changes from polygon to say line). Such re-checking of geometry type is not wanted on server, where database should be stable and represent 1:1 development/testing environments.

**How to Reproduce**

1. Create a project with layers getting data from Oracle view which has say 10-20 millions of rows.
2. Close project.
3. Open project.
4. QGIS takes a lot of time (depends on a database, but could be 20-30s per layer)

**QGIS and OS versions**

3.10, 3.12, Linux

**Additional context**

I've been running a QGIS Desktop/Server with a modification given below for 3 months now (including QGIS Server in production) and have project speed loading imporoved a lot and not noticed any problems.

This is a code I've added in _/src/providers/oracle/qgsoracleprovider.cpp_ function _getGeometryDetails()_:

 <pre>    return true;
   }
 
+  // Added if block below
+  if ( mRequestedGeomType != QgsWkbTypes::Unknown && mSrid > 0 ) {
+    mHasSpatialIndex = true; // default value is false
+    mDetectedGeomType = mRequestedGeomType;
+    mValid = true;
+    return mValid;
+  }
+
   QString ownerName = mOwnerName;
   QString tableName = mTableName;
   QString geomCol = mGeometryColumn;
</pre>

In my live test a load time of a project with ~80 Oracle layers went down from 3-4 minutes to 10-15 seconds.

**Comment by gioman** [comment]
@tomass can you please submit a patch via pull request? thanks!

**Comment by troopa81** [comment]
> Each time while opening a project (including when creating a new QGIS Server instance in apache on high server load) geometry type of a layer is re-checked which is probably unnecessary and could be skipped.

Like I say in the PR, I do'nt think the check is unnecessary. 

You can use the `estimate meta data` option in your layer if you want to speed up the geometry details function.

Can you confirm that this is this [line](https://github.com/qgis/QGIS/blob/master/src/providers/oracle/qgsoracleprovider.cpp#L2675) which slow down the whole process. I would have said that sdo_gtype is indexed and this kind of request should be costless but I'm no oracle expert.

**Comment by tomass** [comment]
Estimate meta data is switched on. Yes, it is the line you're pointing which is slow. The reason is that "table" is actually a view (with meta data entered) on multiple tables with tens of millions of rows. Even getting one value is slow (and queries in a view are tuned for usage in WMS - with spatial filter).
View itself is not (and cannot be) indexed (making it a materialized will require too much additional space). Oracle manages to find all needed indexes of the tables which make up this view (WMS request works perfectly), but it is impossible for QGIS to find the spatial index out without parsing the view itself.
By "slow" I mean 1-10 seconds, but when we have a project with ~100 oracle layers this adds up to a considerable amount of time which is used on a high load of QGIS Server when apache adds a new QGIS process.

**Comment by troopa81** [comment]
> Even getting one value is slow (and queries in a view are tuned for usage in WMS - with spatial filter)

If you estimate metadata, the request to detect type take only the first 100 rows and make a distinct over it. It should not be slow even if there is millions of rows

Could you try this request on your database (with the good table and field names) after enabling timing (set timing on) and give me the result?

```sql
SELECT DISTINCT gtype FROM (SELECT t.%1.sdo_gtype AS gtype FROM %2 t WHERE t.%1 IS NOT NULL AND rownum<100) WHERE rownum<=2
```

And this one (just curious)
```sql
SELECT DISTINCT gtype FROM (SELECT t.%1.sdo_gtype AS gtype FROM %2 t WHERE t.%1 IS NOT NULL GROUP BY t.%1.sdo_gtype )
```

**Comment by tomass** [comment]
`SELECT DISTINCT gtype FROM (SELECT t.geom.sdo_gtype AS gtype FROM l_dkl t WHERE t.geom IS NOT NULL AND rownum<100) WHERE rownum<=2`

returns 2003 in 360 seconds.

`SELECT DISTINCT gtype FROM (SELECT t.geom.sdo_gtype AS gtype FROM l_dkl t WHERE t.geom IS NOT NULL GROUP BY t.geom.sdo_gtype )`

cancelled after one hour. Explain plan gives a cost of 32 million :-)

WMS queries (with spatial filter) return in 50-150ms.

What is a role/purpose/use case of RE-querying geometry type of a layer?

**Comment by troopa81** [comment]
> returns 2003 in 360 seconds.

Ouch!

And If you just request the 100 first sdo_gtype with this, how long it last?
```
SELECT t.geom.sdo_gtype AS gtype FROM l_dkl t WHERE t.geom IS NOT NULL AND rownum<100
```
I suspect something messy regarding the way we use distinct and rownum.

> What is a role/purpose/use case of RE-querying geometry type of a layer?

It's not re-querying, it queries only once at layer creation to be able to filter only the requested geom if needed.

**Comment by tomass** [comment]
> And If you just request the 100 first sdo_gtype with this, how long it last?

  120 seconds. I assume because now it has some data in cache.
  Repeating initial full query it now finishes in 70 seconds - for sure - data cached.

> I suspect something messy regarding the way we use distinct and rownum.

  There is not too much which could be done here. Data is held in the way to be fetched quickly with geometry table as a leading one (there are long and wide branches of data from each geometry). That is why WMS queries are very fast. But when you fetch even some rows without spatial filter all this usage schema breaks and oracle has to go through all tables giving this terrible result.

>> What is a role/purpose/use case of RE-querying geometry type of a layer?
> It's not re-querying, it queries only once at layer creation to be
> able to filter only the requested geom if needed.

  We add a layer to the project, get geometry type and save it in the project.
  We close project.
  We re-open the project again, the layer (provider) is created again. What is the reason to get geometry type from database again instead of using saved geometry type data from the project file?

  My change tries to identify situation when layer is not being created (menu add layer), but rather "opened" again (open project with previously created layer) using data in the project file and then skip geometry checking from database but use data saved in the project file.

  Also notable: we choose geometry type in the add vector layer dialog, why is it checked again?

**Comment by troopa81** [comment]
> 120 seconds. I assume because now it has some data in cache.

Again, I'm not an Oracle expert, but I can't see a good reason why getting the geomtype for the 100 first features should take more than few milliseconds. Is this not a database issue? Or am I missing a point here?

> What is the reason to get geometry type from database again instead of using saved geometry type data from the project file?

filtering on geom type, see my comment in the PR

**Comment by tomass** [comment]
> Again, I'm not an Oracle expert, but I can't see a good reason
> why getting the geomtype for the 100 first features should take
> more than few milliseconds. Is this not a database issue? Or
> am I missing a point here?

  I have OCP and I admin of the database in question has OCM certificate (the highest possible one, living Master Yoda). Database is tuned and producing hundreds of WMS requests per second.
  The reason why it is hard (slow) to get geometry type is because geometry table is "hidden" in the **view** and view query cannot be written to cater for both WMS and geometry type checking use cases.

**Comment by tomass** [comment]
Does this issue still needs any feedback from me?

**Comment by tomass** [comment]
The corresponding patches/fixes have already been applied a year ago.
