### ISSUE TITLE
Does the free version of Qgis has limitations?

### ISSUE THREAD

**Issue by Cezario2020** [qgis/QGIS#34740]
Good day, I'm new here, I want to ask questions about qgis. Thank you for letting me in to Github.

My question is, Qgis madeira free has limitations? o Qgis madeira has all the functions enabled when it is free? (because Combar does not perform the reprojection gives an error)

Thanks a lot

**Comment by kylefelipe** [comment]
Qgis is free... there is no paid version...

**Comment by rouault** [comment]
This is a bug tracker. Not meant for questions
