### ISSUE TITLE
Y value in XYZ Tiles seem to be wrong

### ISSUE THREAD

**Issue by coderzbx** [qgis/QGIS#34756]
**Describe the bug**

The x/y values in XYZ Tiles seem to be calculated wrong.
There're three values for one tile:zoom/x/y, while zoom and x are right and y is wrong value.
QGIS version:v3.10.3- A Coruna
OS version: Ubuntu 18.04-LTS (Mac dosen't have this problem)
**How to Reproduce**

1. Go to 'XYZ Tiles'
2. Click on 'New Connection'
3. Add URL for tiles and named this layer
4. Set level from 21-23 and set tile as 256 * 256
5. Drag new connection just made into layer control
6. Locate a coordinte for display tiles
7. Check the requests of tiles, value of y are wrong, so no tile can be rended.

**QGIS and OS versions**

QGIS version | 3.10.3-A Coruña | QGIS code revision | 0e1f846438
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.6.2-CAPI-1.10.2 4d2925d6
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 10.12 (Ubuntu 10.12-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Ubuntu 18.04 LTS
Active python plugins | processing; db_manager; MetaSearch

**Additional context**

**Comment by CaptainInler** [comment]
this might be a duplicate of #33228

**Comment by gioman** [comment]
@coderzbx is this still true on recent releases?
