### ISSUE TITLE
opening wms gives error

### ISSUE THREAD

**Issue by deRightDirection** [qgis/QGIS#34769]
I opened QGIS and add a wms-service with the following url: https://geo2.flevoland.nl/geoserver/Extern/wms?

It can show me the list of available layers but when i open for example: geothermiekansen, QGIS shows me the error "connection refused".

I tried to open the same url in ArcGIS Pro and I doesn't give me any issues.

QGIS: 3.8 Zanzibar
Windows: 10 Pro, 10.0.18362 build 18362

![afbeelding](https://user-images.githubusercontent.com/3999790/75557765-ef743a80-5a40-11ea-8f3e-2511a2c9ef53.png)

![afbeelding](https://user-images.githubusercontent.com/3999790/75557900-35310300-5a41-11ea-9963-2a3b09ebd70f.png)

**Comment by roya0045** [comment]
Please update to a current version beforehand.

**Comment by gioman** [comment]
@deRightDirection on 3.10 the connection can be established, the layer list show and they can be added, but the on the canvas they do not appear. The QGIS log shows:

`2020-02-28T15:25:55     WARNING    Map request failed [error: **Connection closed** url: https://geo2.flevoland.nl:80/geoserver/Extern/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=6.323571749673839726,52.34086760705616115,7.393717256254119796,52.59709962975848185&CRS=CRS:84&WIDTH=994&HEIGHT=238&LAYERS=Bodemdalingskaart Flevoland 2011-2042&STYLES=&FORMAT=image/png&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96&TRANSPARENT=TRUE]`


are you sure that this server does not need any authentication?

**Comment by gioman** [comment]
@deRightDirection it works if in the connection parameters you check the "ignore getmap/gettile uri..." option. This is probably needed because of some server configuration (for that for some layers you will still get an error when it comes to download the legend).

**Comment by elpaso** [comment]
what? https://geo2.flevoland.nl:80 HTTPS on port 80? Really?

**Comment by deRightDirection** [comment]
yeah we fixed it, issue gone :-)
