### ISSUE TITLE
Calculation of wrong areas and lengths

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#34768]
## Area

Incorrect ellipsoidal area calculation,
using this expression in the labels:

```
'Ellipsoidal area ($area):' || format_number ($area /1000000,2) || 'km²'
|| '\n' ||
'Planimetric area (area ($geometry)):' || format_number (area ($geometry) /1000000,2) || 'km²'
```
![image](https://user-images.githubusercontent.com/7631137/75555086-d917b000-5a3b-11ea-93c1-958ebca9dbb6.png)

## Length

```
'Ellipsoidal length ($length):' || format_number ($length/1000,2) || 'km'
|| '\n' ||
'Planimetric length (length ($geometry)):' || format_number (length ($geometry) /1000,2) || 'km'
```

![image](https://user-images.githubusercontent.com/7631137/75556074-cf8f4780-5a3d-11ea-9964-c7d83f0d65c0.png)

## OSGeo4W64  win 10 - QGIS 3.12

![image](https://user-images.githubusercontent.com/7631137/75555171-04020400-5a3c-11ea-906a-e38a1f8a8189.png)

**Comment by roya0045** [comment]
If you set the projection of the project to be the projection of the layer, does it changes anything?

**Comment by pigreco** [comment]
> If you set the projection of the project to be the projection of the layer, does it changes anything?

project and layer: EPSG 32632

**Comment by gioman** [comment]
> project and layer: EPSG 32632

@pigreco attach sample data, thanks!

**Comment by DelazJ** [comment]
> project and layer: EPSG 32632

And the identify tool mentions epsg:7030. The same?

**Comment by roya0045** [comment]
> > project and layer: EPSG 32632
> 
> And the identify tool mentions epsg:7030. The same?

This is what confused me also.

**Comment by pigreco** [comment]
sorry, but I closed the old project and now I can't reproduce it anymore.
As soon as I can I will be more precise.

**Comment by pigreco** [comment]
Sorry for the false alarm.
after other tests I can no longer reproduce it, so I close the issue.

sorry
