### ISSUE TITLE
Crash on form opening with N-M relations (Postgres & Windows)

### ISSUE THREAD

**Issue by ygversil** [qgis/QGIS#34776]
**Describe the bug**
When trying to add a feature in a layer which is referenced by a pivot table, once the geometry has been digitized, the form dialog shows up, but the dialog is unusable, then QGIS crash after a while.

**How to Reproduce**

1. In PostgreSQL, create two tables and a pivot table between them :

```sql
create table public.event (fid serial primary key, title text not null, geometry geometry(POINT, 2154) not null);
create table public.person (fid serial primary key, name text not null);
create table public.event_person ( 
   fid serial primary key, 
   event_id integer not null references public.event (fid) on update cascade deferrable initially deferred, 
   person_id integer not null references public.person (fid) on update cascade deferrable initially deferred 
 );
insert into public.person (name) values ('Alice');
```

2. In QGIS, add all three Postgres tables as layers into a new project.

3. In Project --> Properties menu, Data Sources tab, check both "Automatically create transaction groups where possible" and "Evaluate default values on provider side" checkboxes.

4. Still in project properties, Relations tab, click the Discover Relations button and add the two found relations.

5. Close the project properties dialog. Now try to add a new feature in the event layer : switch to editing mode, click the add point button, and add a point somewhere. The form dialog popups but is unusable and the QGIS crash after a while.

**QGIS and OS versions**

Version de QGIS
3.10.3-A Coruña
Révision du code
0e1f846438
Compilé avec Qt
5.11.2
Utilisant Qt
5.11.2
Compilé avec GDAL/OGR
3.0.4
Utilisé avec GDAL/OGR
3.0.4
Compilé avec GEOS
3.8.0-CAPI-1.13.1
Utilisé avec GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
Version du client PostgreSQL
11.5
Version de SpatiaLite
4.3.0
Version de QWT
6.1.3
Version de QScintilla2
2.10.8
Compilé avec PROJ
6.3.1
Fonctionne avec PROJ
Rel. 6.3.1, February 10th, 2020
OS Version
Windows 10 (10.0)
Extensions Python actives
db_manager; 
MetaSearch; 
processing

**Additional context**

In PostgreSQL audit log, the following line shows up when the point is added :

`2020-02-28 17:40:23.349 CET,"ygversil","ana",17358,"192.168.1.204:59008",5e594270.43ce,1,"CLOSE CURSOR",2020-02-28 17:40:16 CET,17/51428,1479929,ERREUR,34000,"le curseur « qgis_7 » n'existe pas",,,,,,,,,"QGIS"`

I've only seen this bug with PostgreSQL layers and QGIS 3.10.3 under Windows 10. On Arch Linux/QGIS 3.10.2, it works fine (form shows up and can be filled up ; the above error message is not to be seen). On Windows 10/QGIS 3.10.3 using a GeoPackage instead of Postgres, it works fine too.

**Comment by ygversil** [comment]
A little more feedback.

Just tried with QGIS 3.12, same crash.

If "Evaluate default values on provider side" is unchecked, same crash but error message is PG audit is `"DECLARE CURSOR",2020-02-28 18:58:58 CET,23/3009,0,ERREUR,22P02,"syntaxe en entrée invalide pour le type integer : « nextval('event_fid_seq'::regclass) »"`.

If "Automatically create transaction groups where possible" is unchecked, same crash but PG audit error if `"FETCH",2020-02-28 19:00:32 CET,26/911,0,ERREUR,34000,"le curseur « qgis_3 » n'existe pas",,,,,,,,,"QGIS"`.

If form is Drag'n'Drop and the reference relation widget is omitted it works.

If form is generated automatically and cardinality for the relation is set to "person (fid)", it works. But this is not a true workaround since the join table may have attributes to to qualify the relationship.

**Comment by gioman** [comment]
>     1. In PostgreSQL, create two tables and a pivot table between them :
> 
> 
> ```sql
> create table public.event (fid serial primary key, title text not null, geometry geometry(POINT, 2154) not null);
> create table public.person (fid serial primary key, name text not null);
> create table public.event_person ( 
>    fid serial primary key, 
>    event_id integer not null references public.event (fid) on update cascade deferrable initially deferred, 
>    person_id integer not null references public.person (fid) on update cascade deferrable initially deferred 
>  );
> insert into public.person (name) values ('Alice');
> ```
> 
>     1. In QGIS, add all three Postgres tables as layers into a new project.
> 
>     2. In Project --> Properties menu, Data Sources tab, check both "Automatically create transaction groups where possible" and "Evaluate default values on provider side" checkboxes.
> 
>     3. Still in project properties, Relations tab, click the Discover Relations button and add the two found relations.
> 
>     4. Close the project properties dialog. Now try to add a new feature in the event layer : switch to editing mode, click the add point button, and add a point somewhere. The form dialog popups but is unusable and the QGIS crash after a while.

@ygversil I followed your steps on 3.10.3 on Windows/Postgresql 12  > no crash

**Comment by ygversil** [comment]
On the same Windows computer, with a clean profile, no crash occurs with QGIS 3.12.2 which seems to have fixed the problem.
