### ISSUE TITLE
Crash in RelationReference test

### ISSUE THREAD

**Issue by m-kuhn** [qgis/QGIS#34779]
Reported in https://github.com/qgis/QGIS/pull/34778
(Does not always happen, likely a race condition)

Trace here https://cdash.orfeo-toolbox.org/testDetails.php?test=16814015&build=32644

@troopa81 since I haven't seen crashes before on these tests I assume this is related to your recent work.

**Comment by troopa81** [comment]
@m-kuhn not (directly) related to my work I think, but anyway I proposed a fix for the cdash related issue

**Comment by m-kuhn** [comment]
Thanks!
