### ISSUE TITLE
Available WMS layers are not displayed in QGIS Browser

### ISSUE THREAD

**Issue by pathmapper** [qgis/QGIS#34798]
**Describe the bug**
Available WMS layers are not displayed in the QGIS Browser.

**How to Reproduce**
After adding a WMS with the following URL to the browser with QGIS 3.12.0 the available WMS layers are not displayed in the browser (there is only 1 layer displayed but there are more):
https://www.wms.nrw.de/geobasis/wms_nw_dop

![grafik](https://user-images.githubusercontent.com/20856381/75623020-6414b980-5ba6-11ea-965c-a20230d2b5db.png)

![grafik](https://user-images.githubusercontent.com/20856381/75622898-72aea100-5ba5-11ea-8da0-5c66b4629d68.png)

**QGIS and OS versions**

QGIS version | 3.12.0-București | QGIS code revision | 409bcf8eaa
-- | -- | -- | --
Compiled against Qt | 5.11.3 | Running against Qt | 5.11.3
Compiled against GDAL/OGR | 2.4.0 | Running against GDAL/OGR | 2.4.0
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.27.2 | Running against SQLite | 3.27.2
PostgreSQL Client Version | 11.6 (Debian 11.6-0+deb10u1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.10.4
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Debian GNU/Linux 10 (buster)
Active python plugins | ClipMultipleLayers; quick_map_services; scriptrunner3; LAStools; canvas_clipper; savedialog; loadthemall; kmltools; MapsPrinter; mmqgis; pluginbuilder3; vector_tiles_reader; layerGroupFilter; plugin_reloader; realcentroid; mask; MetaSearch; db_manager; processing

**Additional context**

- With QGIS 3.10.1 the WMS layers are displayed. 

- With QGIS 3.12.0 it is possible to add the WMS layers via the "Data Source Manager":
![grafik](https://user-images.githubusercontent.com/20856381/75622864-2e230580-5ba5-11ea-8c5b-247f1b6b3d80.png)

- https://github.com/qgis/QGIS/issues/34692 could be related.

**Comment by gioman** [comment]
Confirmed regression.

**Comment by Samweli** [comment]
Confirmed on master, working on a fix!

**Comment by pathmapper** [comment]
This is fixed in `3.12.1`, thanks!
