### ISSUE TITLE
Problem importing a DWG drawing

### ISSUE THREAD

**Issue by mahmoud2728** [qgis/QGIS#34805]
I suffer from this problem when importing a dwg file

![Screenshot 2020-03-01 22 55 45](https://user-images.githubusercontent.com/61476338/75633728-2c425c00-5c10-11ea-89ff-45238591c1ec.png)
![Screenshot 2020-03-01 22 55 05](https://user-images.githubusercontent.com/61476338/75633731-2ea4b600-5c10-11ea-9240-800cefe638b3.png)

**Comment by gioman** [comment]
> I suffer from this problem when importing a dwg file

@mahmoud2728 please describe in **words** your issue (detailed steps to replicate and obtained results VS expected, thanks). Also attach the problematic dataset.

**Comment by mahmoud2728** [comment]
The problem is when I import a DWG file, I am having trouble not closing captors,
Although in AutoCAD it is closed !!
![Screenshot 2020-03-01 23 05 34](https://user-images.githubusercontent.com/61476338/75633833-3d3f9d00-5c11-11ea-8fb3-a8028894b5e8.png)

**Comment by gioman** [comment]
> The problem is when I import a DWG file, I am having trouble not closing the vectors
> Although in AutoCAD it is closed !!

@mahmoud2728 attach the data.

**Comment by mahmoud2728** [comment]
https://www.gulf-up.com/k9fz5dxvs8ap

**Comment by mahmoud2728** [comment]
Is there a solution to the problem?

**Comment by gioman** [comment]
> Is there a solution to the problem?

@mahmoud2728 seems to work fine here on Linux:

![Screenshot_20200302_121347](https://user-images.githubusercontent.com/1951107/75675576-4ff0bb00-5c7f-11ea-994f-ab46ed15586d.png)

**Comment by mahmoud2728** [comment]
I work on a Windows machine!
Can you explain to me all the steps that I took to import the file,
Because all your LAYER are correct and even the colors are the same AutoCAD!
Even the text

**Comment by andreasneumann** [comment]
@mahmoud2728 - there are 2 ways of importing DXF/DWG into QGIS:
1. drag and drop or with load vector. This runs through OGR and is usually not as good as the second option
2. Go to menu "Project" --> "Import" --> "Import/Export" --> "Import Layers from DWG/DXF".

If you tried the first option, please try the second option to see if this fixes your problem.

**Comment by gioman** [comment]
> Go to menu "Project" --> "Import" --> "Import/Export" --> "Import Layers from DWG/DXF".

@mahmoud2728 following this same results on Windows.

**Comment by roya0045** [comment]
Is this solved?

**Comment by gioman** [comment]
Closing for lack of feedback.
