### ISSUE TITLE
Stuck at Recent Project window when opening blank file in 3.10.3

### ISSUE THREAD

**Issue by IZ404** [qgis/QGIS#34809]
**Describe the bug**

I have recently upgraded to the new long term release of 3.10 from 3.4. Now, every now and then, when I try to open an existing blank QGIS file through any method, e.g. double-clicking, open from QGIS through 'Open Project', I get stuck on the Recent Projects window. The only way to fix it is to do something, such as adding a layer, and the actual window would appear.

**How to Reproduce**

Open a blank existing file, i.e a file with no layers but projection setup.

**QGIS and OS versions**

QGIS latest long term release of 3.10.3. Windows 10

**Additional context**

It is not a crash or freeze. It is probably when nothing is displaying, QGIS decide to display the recent projects window.

**Comment by troopa81** [comment]
Cannot reproduce on Debian. Could you provide a *blank* project

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.

**Comment by neogeomat** [comment]
It's not just on blank project. opening qgis took 48 seconds on "updating recent project paths".  This is on fresh start as well as opening saved projects.
![image](https://github.com/user-attachments/assets/3a56e6e2-e297-42d3-b179-8773c50e54cb)

**Comment by troopa81** [comment]
3.10 version is no longer supported, Can you give a try to current LTR 3.34.10

Do you have some project on a network share or database stored in your recent projects?

If you create a new profile, do you have the same issue?

**Comment by neogeomat** [comment]
I am using version 3.36.3.

I cleared the recent projects and it is opening fast now. Is there a way to clear it from explorer without opening qgis first?

**Comment by troopa81** [comment]
You can edit QGIS ini file to remove all the entries starting with `recentProjects` string
