### ISSUE TITLE
QGIS loads too many XYZ tiles on first view

### ISSUE THREAD

**Issue by pnorman** [qgis/QGIS#34813]
**How to Reproduce**

1. Load a shapefile with a small area (e.g. buildings from geofabrik's prince-edward-island-latest-free.shp)
2. Turn on a network debugger or install QGIS network logger
3. Add OpenStreetMap XYZ tiles

242 tile requests are made on my display, but only 25-50 or so are needed to cover the screen at my resolution

![image](https://user-images.githubusercontent.com/1190866/75645849-69045800-5bfc-11ea-9bf9-f90f69a1f3ba.png)

**QGIS and OS versions**
3.12 on Windows 10

```
QGIS version
3.12.0-București
QGIS code revision
cd141490ec
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.1
Running against PROJ
Rel. 6.3.1, February 10th, 2020
OS Version
Windows 10 (10.0)
Active python plugins
qgisnetworklogger; 
db_manager; 
MetaSearch; 
processing
```

Loading 10x the tiles required is putting heavy load on the OSMF tile servers

cc @firefishy

**Comment by Firefishy** [comment]
QGIS now accounts for over 5% (>330 req per second reaching our backend, 245GB / day) of our daily tile.openstreetmap.org traffic.

**Comment by elpaso** [comment]
@wonder-sk do you have any clue if we can reduce the number of downloaded tiles or at least control it through settings ?

**Comment by alexbruy** [comment]
Probably not all of these requests are from native QGIS provider, there are also some plugins which allow to load XYZ tiles.

**Comment by systemed** [comment]
Any further thoughts on this? It would be a real shame if QGIS was blocked from loading OSM tiles.

**Comment by saberraz** [comment]
Could you disable your plugins (ideally a clean profile) and see if the bug still appears. As @alexbruy mentioned, it could be other plugins trying to fetch xyz files.

**Comment by pnorman** [comment]
I interpreted @alexbruy's comment to be about the 5% of osm.org traffic, not about the excess tiles.

The only plugin I installed was qgisnetworklogger, which was required to see the requests.

**Comment by mhugent** [comment]
QGIS renders the surrounding areas in a background job to make subsequent pan actions faster. Therefore it sends more tile requests than necessary for the current map extent. It is discussible if this behaviour is desirable here or if it should be switched off for xyz-layers.

**Comment by pnorman** [comment]
> QGIS renders the surrounding areas in a background job to make subsequent pan actions faster. Therefore it sends more tile requests than necessary for the current map extent. It is discussible if this behaviour is desirable here or if it should be switched off for xyz-layers.

It's doing this too far out if it's loading 10x tiles. 

I think in general this is undesirable for xyz layers

**Comment by andreasneumann** [comment]
We discussed this yesterday in our PSC meeting and would like to come up with either a hard-coded fix or a configuration with it, with a default that fetches a smaller amount of tiles.

Please be patient. Will be probably be shipped with QGIS 3.14 and maybe bugfix releases of older versions. But it will be a while until the old QGIS versions will disappear.

**Comment by elpaso** [comment]
@andreasneumann I'm on it. I have a quick and dirty patch but I'm looking to a more elegant solution, if it takes too long I'll probably go with the "quick" patch.

**Comment by Nakaner** [comment]
If a tile service responds quickly (and not as slowly as a WMS), preloading should not be necessary. If services do not respond quickly, preloading might improve the situation for one user but it reduces the quality of the service for all other users. Caching tiles on client side is suggested or requested by usage guidelines and policies of popular tile service providers. A proper solution should focus on caching (better cache longer than necessary to reduce the load on the source).

**Comment by elpaso** [comment]
QGIS has a cache for tiles but it lasts for the session only. Btw, we now have the code in place to fine-tune prefetching behavior for all raster layers on a per-layer basis, for now I just blacklisted osm tiles.

**Comment by pnorman** [comment]
Just to follow up on this, the changes have had a noticeable reduction in load from qgis users on OSM servers.
