### ISSUE TITLE
MS-SQL server lines and polygons not showing in QGIS, throwing Compound curve error

### ISSUE THREAD

**Issue by Shrijana1** [qgis/QGIS#34810]
Our environment is:
•	MS SQL server 2012 using the Geometry data type
•	QGIS version 2.18 and 3.0
We are trying to load MS SQL server data into QGIS but its throwing error message related to compound curve. Looks like SQL sever data provider only support linear geometry types and the presence of curves geometry type are the problem.

**Comment by gioman** [comment]
@Shrijana1 what ogrinfo says about the layers (geometries) you are trying to load?

**Comment by roya0045** [comment]
Even if this is a bug in qgis and not your provider I would suggest testing on an updated version.

**Comment by gioman** [comment]
> r I would suggest testing on an updated version

actually is not a suggestion, it must be really tested on the latest available LTR > 3.10.3
