### ISSUE TITLE
 Cannot instantiate the 'postgresraster' data provider when load raster from postGIS

### ISSUE THREAD

**Issue by lucalanteri** [qgis/QGIS#34823]
When I try to load a raster from postGIS QGIS raises this error:
 CRITICAL    Invalid Layer : Raster layer Cannot instantiate the 'postgresraster' data provider

To reproduce
1. restore test.sql
2. load raster 

The issue is on QGIS 3.12.0. It works fine on QGIS 3.10
Tested on windows 10
[test.zip](https://github.com/qgis/QGIS/files/4276046/test.zip)

**Comment by elpaso** [comment]
@jef-n does the windows package include the new data PG raster data provider dll?

**Comment by elpaso** [comment]
@jef-n nvermind, there is an issue with the schema, I'll fix it.

**Comment by elpaso** [comment]
@jef-n I've found the problem in QgsDataSourceUri: the URI string that is passed to the provider is in GDAL format:

```
PG:  dbname='qgis_tests' host=localhost port=5432 user='ale' password='ale' sslmode=disable mode=2 schema='idro' column='rast' table='cosmo_i5_snow'
```
the `schema` is explicit, how do you feel about patching QgsDataSourceUri to handle an explicit schema in addition to the dotted notation in the `table`?
