### ISSUE TITLE
3D view does not visualize polygons in EPSG:4326 coord. sys. after 3.12 version

### ISSUE THREAD

**Issue by muratkendir** [qgis/QGIS#34824]
I was using a workplace since QGIS 3.x, in which projected coordinate system is defined as <Project Coordinate System> and my layer data are composed from EPSG:4326 data in PolygonZ geometry type. Layer data served by PostGIS.

Since i upgraded to 3.12 version of QGIS, i can not visualize these  polygons anymore by using <New 3D Map View> function in View menu.

I noticed that, i can visualize other data in projected coordinate systems without any problem. 
Also another observation is that, when i install Qgis2threejs plugin and use this plugin with EPSG:4326 defined data, it also works without any problem.

By the way, i tried to catch some related errors in log messages, but couldn't.
[212_bug_report_qgis_3d.zip](https://github.com/qgis/QGIS/files/4276015/212_bug_report_qgis_3d.zip)

![2020-03-02 18_03_04-_bug_report_in_4326 - QGIS  test1](https://user-images.githubusercontent.com/3502531/75688195-1be1be00-5cb0-11ea-983d-42e55caf203f.png)

![2020-03-02 18_02_40-bug_report_in_4326 - QGIS  test1](https://user-images.githubusercontent.com/3502531/75688196-1c7a5480-5cb0-11ea-9d92-804b1eca2bf2.png)

**Comment by gioman** [comment]
@muratkendir thanks for the report. In general try stick with LTR releases, now is 3.10.

**Comment by muratkendir** [comment]
Thanks for advise, i already use both LTS 3.10 and 3.12.

**Comment by DelazJ** [comment]
> In general try stick with LTR releases,

@gioman may I ask why?

**Comment by muratkendir** [comment]
Of course, i generally prepare data for CesiumJS, thats why i use data generally in EPSG:4326 coord. sys. and need to visualize in 3D environment. So, i can check objects before converting it to 3D tiles.

**Comment by saberraz** [comment]
I can confirm the issue. The link to the zip file is broken. @muratkendir could you edit your OP to have the correct link?

**Comment by gioman** [comment]
> @gioman may I ask why?

@DelazJ honestly I'm a bit surprised/confused by this question. Aren't we (QGIS) always suggesting users to stay on the release we declare to be the most stable? And at the same time aren't we that say that is likely the brand new .0 releases to have undetected issue?

Mine was a general suggestion for the general user (not the ones we know we can ask to be testers): stick to ltr to get the smoothest possible qgis experience.

**Comment by nirvn** [comment]
@gioman , I think it'd be a disservice to our project to incite _everybody_ to stay on LTR. We need users using latest releases, that's the only way we have to stress test newer version. 

For enterprises that require stability above all else -> LTR. For GIS enthusiasts (professional or otherwise) that are interested in the latest and greatest -> newest non-LTR release.

**Comment by gioman** [comment]
> I think it'd be a disservice to our project to incite _everybody_ to stay on LTR

@nirvn that's NOT what I suggest to all users, but certainly most of them should stick to LTR.

**Comment by muratkendir** [comment]
@saberraz broken link edited.

**Comment by DelazJ** [comment]
> honestly I'm a bit surprised/confused by this question.

@gioman You should not! 3.10.3 and 3.12.0 are the latest releases so imho good candidates for use, for everybody. I don't know @muratkendir profile but maybe the advice misses some contextualization/explanation for anyone else that would read it (though I personally do not agree with that as a general advisable behavior). 
> We need users using latest releases, that's the only way we have to stress test newer version.

Agreed. And unfortunately having more "testers" for .0 is currently easier than during feature freeze.

But let's not hijack this issue report with such a discussion.

**Comment by antoniolocandro** [comment]
I want to confirm this is still the case. Also I notice the interface between the symbology and the 3D map and pan/zoom in the 3D map a lot slower compared to previous versions 3.10 which seems to work smoother.

**Comment by muratkendir** [comment]
Sorry for late response. This issue still continue. Data sources with EPSG:4326 CRS, still not appears in 3D View. If you want to view your data as 3D extruded objects, you should reproject them to any projected CRS.

**Comment by jukos** [comment]
I have posted this on gis. stackexchange:
https://gis.stackexchange.com/questions/363299/qgis-3d-no-terrain-altitude-binding-for-polygons-buildings

Can anybode here me give answers to this questions:
1. is there any connection to this issue here?
2. if not: do you know a suitable isssue here on github qgis for my problem?

Background: I want to create an issue here in github, if my problem has not yet been described.

Thanks
