### ISSUE TITLE
geometry generator precision problem when making a difference between geometry and a buffer around the same geometry

### ISSUE THREAD

**Issue by danduk82** [qgis/QGIS#34828]
**Describe the bug**
When generating an `aggregate` difference between a `geometry` and a `buffer`, some precision problems might appear, that leaves the ghost geometry behind.

In the following example, we want to display 2 polygons, with a 6m gap between them. The geometries are touching each-other. 

In the following 2 screenshots, you can notice that in the wrong one, in the red-circle we notice an artifact between the 2 polygons in the center, which is one of the poligons edges, which has not been cought by the geometry generator script.

![problem](https://user-images.githubusercontent.com/2493436/75699011-ffde1c80-5caf-11ea-9190-667c1c1d0ee8.png)

If we add a small buffer of 0.0001 to the `$geometry` instead of using it directly, this artifact disappears.

![correct](https://user-images.githubusercontent.com/2493436/75699041-08ceee00-5cb0-11ea-994b-60be95513610.png)

**How to Reproduce**
To reproduce the bug, just download  [the attached zip file](https://github.com/qgis/QGIS/files/4276758/exemple_polygones.zip), it contains:
- a qgis project
- a geopackage with the data

Open the project and the bug should be visible. To see how it should be instead, just go in the `Ziel A` legend class and change the geometry generator with the following:

```
CASE
  WHEN  "Parent"  = -1 
	THEN $geometry 
  WHEN  "Parent"  IS NULL
	THEN $geometry
  ELSE
	intersection( 
		buffer(geometry(get_feature(@layer_id, 'Erfassungsnummer',  "Parent" )), -6,-2),
		difference(
			$geometry,
			buffer(aggregate(@layer,'collect',difference(buffer($geometry,3,-2),buffer($geometry,-000001,-2)),"Parent" != -1),0)
			)
		)
END
```

Note the `buffer($geometry,-000001,-2)` which removes the precision-related artifact. In fact you simply change:

```
	intersection( 
		buffer(geometry(get_feature(@layer_id, 'Erfassungsnummer',  "Parent" )), -6,-2),
		difference(
			$geometry,
			buffer(aggregate(@layer,'collect',difference(buffer($geometry,3,-2),$geometry),"Parent" != -1),0)
			)
		)
```

with this:

```
	intersection( 
		buffer(geometry(get_feature(@layer_id, 'Erfassungsnummer',  "Parent" )), -6,-2),
		difference(
			$geometry,
			buffer(aggregate(@layer,'collect',difference(buffer($geometry,3,-2),buffer($geometry,-000001,-2)),"Parent" != -1),0)
			)
		)
```

**QGIS and OS versions**
QGIS version: 3.10
OS: Ubuntu 18.04 and Windows10

**Comment by nyalldawson** [comment]
This should be re-tested with a newer version based on GEOS 3.9 (with the new precision model)
