### ISSUE TITLE
Missing or faulty lxml-library in QGIS 3.10.3 ltr?

### ISSUE THREAD

**Issue by gitDimg** [qgis/QGIS#34838]
Trying to install GeoCat Bridge plugin but failing.
Reported this error on bug tracker for GeoCat and some helpful souls pointed out that there might be some
problems with lxml and current QGIS ltr version. 

Is lxml-library possibly missing or faulty in QGIS 3.10.3? No problem installing on 3.10.1 or 3.12.0.
Already tested to wipe profile.

How to reproduce the error:
1: Plugins
2: Manage and install plugins
3: Search for GeocatBridge
4: Install

**Error message when trying to install GeoCat Bridge plugin:**
Couldn't load plugin 'geocatbridge' due to an error when calling its classFactory() method 
ModuleNotFoundError: No module named 'lxml.etree' 
Traceback (most recent call last):
File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 334, in _startPlugin
plugins[packageName] = package.classFactory(iface)
File "C:/Users/KlanteVolante/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geocatbridge\__init__.py", line 11, in classFactory
from .plugin import GeocatBridge
File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 744, in _import
mod = _builtin_import(name, globals, locals, fromlist, level)
File "C:/Users/KlanteVolante/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geocatbridge\plugin.py", line 13, in 
from .ui.bridgedialog import BridgeDialog
File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 744, in _import
mod = _builtin_import(name, globals, locals, fromlist, level)
File "C:/Users/KlanteVolante/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geocatbridge\ui\bridgedialog.py", line 8, in 
from .publishwidget import PublishWidget
File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 744, in _import
mod = _builtin_import(name, globals, locals, fromlist, level)
File "C:/Users/KlanteVolante/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geocatbridge\ui\publishwidget.py", line 48, in 
from geocatbridge.publish.geonetwork import GeonetworkServer
File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 744, in _import
mod = _builtin_import(name, globals, locals, fromlist, level)
File "C:/Users/KlanteVolante/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geocatbridge\publish\geonetwork.py", line 9, in 
import lxml.etree as ET
File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 744, in _import
mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'lxml.etree'

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.10.3-A Coruña A Coruña, 0e1f846438 

Python Path: C:/Users/KlanteVolante/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\BoundaryDelineation/lib
C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python
C:/Users/KlanteVolante/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/KlanteVolante/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3~1.10\apps\Python37
C:\PROGRA~1\QGIS3~1.10\apps\Python37\Scripts
C:\Program Files\QGIS 3.10\bin\python37.zip
C:\PROGRA~1\QGIS3~1.10\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib
C:\Program Files\QGIS 3.10\bin
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\Pythonwin
C:/Users/KlanteVolante/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\KlanteVolante\AppData\Local\acatama\python37
C:\Users\KlanteVolante\AppData\Local\acatama\python37\lib\site-packages
.
C:/Users/KlanteVolante/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\BitFlagRenderer
C:/Users/KlanteVolante/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\BitFlagRenderer\bitflagrenderer
C:/Users/KlanteVolante/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web
C:\Users\KlanteVolante\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
C:\Users\KlanteVolante\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\geocatbridge\libs
C:\Users\KlanteVolante\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\geocatbridge\libs\bridgestyle

**QGIS version**
3.10.3-A Coruña
QGIS code revision
0e1f846438
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.1
Running against PROJ
Rel. 6.3.1, February 10th, 2020
OS Version
Windows 10 (10.0)
Active python plugins
AcATaMa; 
active_fire; 
Add_a_point_road_sign; 
AppendFeaturesToLayer; 
attributeBasedClustering; 
AustrianElevation; 
beePen; 
BitFlagRenderer; 
BoundaryDelineation; 
BoundingBox; 
BufferByPercentage; 
buienradar_plugin; 
BulkVectorExport; 
Climb; 
qgis2web; 
db_manager; 
MetaSearch; 
processing

**Comment by jef-n** [comment]
python3-lxml is no actual dependency of QGIS and was not included in the ltr packages.  Added to qgis-ltr-full in osgeo4w.

**Comment by gitDimg** [comment]
OK, thank you for the quick reply!
