### ISSUE TITLE
ID column for temporary layer is not detected when creating virtual layers using data source manager

### ISSUE THREAD

**Issue by NyakudyaA** [qgis/QGIS#34830]
# Problem

I have created a temporary scratch layer with the following columns

![scrtac](https://user-images.githubusercontent.com/2510900/75704206-9c5cea80-5cc1-11ea-9dcd-a185870a0167.png)

However, when I try to use the ID column in creating a virtual layer I get the following error.
![no-such-column](https://user-images.githubusercontent.com/2510900/75704306-ce6e4c80-5cc1-11ea-95d1-19cd3c096cb1.png)

The same SQL statement works in DB manager
Tested on MAC, Windows using QGIS 3.12, QGIS 3.10.2

**Comment by troopa81** [comment]
Just tested in 3.14 and master and it works if you don't import the memory scratch layer in embedded layers before.

The widget tooltip says

> Embedded layers can be added to have SQL queries with layers that are independent from layers loaded by the current QGIS project. In particular, saving a virtual layer with embedded layers to a QLR file can be done to reuse its definition in another project.

So, you need embedded layers if you want to connect to layers outside your project, on a physical file. So it doesn't apply to memory scratch layer which lives only in the project.
