### ISSUE TITLE
db manager give SRID error by vector file import

### ISSUE THREAD

**Issue by dig360** [qgis/QGIS#34839]
**Describe the bug**
By using db manager to import a layer to Postgresql (file or layer) the operation fails every time. With many differents files or layers. Error messages : 
"Error 2
Creation of data source "public"."abords" failed: 
ERROR:  AddGeometryColumn() - invalid SRID
CONTEXT:  PL/pgSQL function addgeometrycolumn(character varying,character varying,character varying,character varying,integer,character varying,integer,boolean) line 50 at RAISE
SQL statement "SELECT public.AddGeometryColumn('',$1,$2,$3,$4,$5,$6,$7)"
PL/pgSQL function addgeometrycolumn(character varying,character varying,character varying,integer,character varying,integer,boolean) line 5 at SQL statement"

**How to Reproduce**
1 Launch DB manager
2 Select database 
3 Select shapefile or layer in project
4 Fill the options in import vector layer popup menu
5 Validate 
Then error message appear.

**QGIS and OS versions**
QGIS version | 3.12.0-București | QGIS code revision | 409bcf8eaa
-- | -- | -- | --
Compiled against Qt | 5.12.4 | Running against Qt | 5.12.4
Compiled against GDAL/OGR | 2.4.2 | Running against GDAL/OGR | 2.4.2
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.7 (Ubuntu 11.7-0ubuntu0.19.10.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.10.4
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Ubuntu 19.10
Active python plugins | MetaSearch; db_manager; processing

Best Regards
Didier Genier

**Comment by gioman** [comment]
@dig360 please attach sample data.

**Comment by dig360** [comment]
For example this I downloaded last week, SRID 4326
[World_Countries.zip](https://github.com/qgis/QGIS/files/4280435/World_Countries.zip)
Or this other in SRID 2056 (Swirtzerland) very small one
[nocturne.zip](https://github.com/qgis/QGIS/files/4280454/nocturne.zip)

**Comment by gioman** [comment]
@dig360 works fine here on 3.12 (on Linux) with this backend:

```

Server version: | PostgreSQL 10.12 (Ubuntu 10.12-2.pgdg18.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0, 64-bit
PostGIS
Library: | 2.4.4
GEOS: | 3.7.1-CAPI-1.11.1 27a5e771
Proj: | Rel. 4.9.3, 15 August 2016

```

**Comment by dig360** [comment]
Thank you Giovanni, 
But I wonder what I can check... 
Sometime locals are in cause, I tried to change it to english, same error...
An idea ? Needs a missing library on my system ? Where to search ?
It's an operation I need really often...

**Comment by gioman** [comment]
>  But I wonder what I can check...

@dig360 have you checked if your backend/target database is ok?

**Comment by dig360** [comment]
Tested shp2pgsql on console : same error ! Qgis is not at issue !
I close this ticket.

**Comment by dig360** [comment]
I come back for a moment to complete this ticket. The problem came from the spatial_ref_sys table which was empty. Incredible, on a remote server used for several years!?! Check if you encounter the same error message.
Best regards.
Didier
