### ISSUE TITLE
Layer's point with CSV don't display on QGIS 3.10 and 3.12

### ISSUE THREAD

**Issue by cherifmad** [qgis/QGIS#34833]
**Describe the bug**
Description

[QGIS 3.10 and QGIS 3.12  Windows 10 64 b]

Good morning,

I cannot add delimited text layers. ( this is my file [staffff1.txt](https://github.com/qgis/QGIS/files/4278656/staffff1.txt) )

Specifically (using the attached example):
1) click on "add delimited text layer"
2) dialog opens, browse to file, fill in the infos 

![qgis proc1](https://user-images.githubusercontent.com/10108717/75731050-831a6500-5ce6-11ea-97ef-1d599f2c3673.JPG)

3) the layer does appear in the layer list but no points are created.

![qgis proc2](https://user-images.githubusercontent.com/10108717/75731075-94637180-5ce6-11ea-803b-477909cca0db.JPG)

Please Can I help me to solve this bug ?

**How to Reproduce**

**QGIS and OS versions**
QGIS 3.10 and QGIS 3.12 my OS is Windows 10

**Additional context**

**Comment by stev-0** [comment]
You need to check the `decimal seperator is comma` checkbox, or in French `Virgule en seperator decimal` in order for this to work, as a point to represent decimals is the default

**Comment by cherifmad** [comment]
Thanks 
I use comma like separator, but nothing Appear in my layer.
[staffff1.txt](https://github.com/qgis/QGIS/files/4280131/staffff1.txt)

**Comment by stev-0** [comment]
That is odd, I get this, which I presume is expected?

Possibly a locale thing, what is your locale (Settings -> Options -> General Tab)?

![image](https://user-images.githubusercontent.com/1316871/75758176-8d128700-5d2b-11ea-816a-d2d4b12fb614.png)

**Comment by gioman** [comment]
>  I use comma like separator, but nothing Appear in my layer.

@cherifmad have you checked the "decimal separator is comma" in the "add delimited text layer" tool GUI? Have you choose the right CRS (4326)?

**Comment by cherifmad** [comment]
@gioman I have use on of the good CRS (4326).
When I use QGIS 2.18 with this setting, the points Appear in my layer, but nothing in QGIS 3.10 and QGIS 3.12

**Comment by cherifmad** [comment]
@stev-0 Please, Do you have used QGIS 3.10 to display my CSV's Points?

**Comment by gioman** [comment]
@cherifmad 

![Peek 2020-03-03 13-25](https://user-images.githubusercontent.com/1951107/75779954-83504a00-5d52-11ea-9e11-2c86adc1da77.gif)

**Comment by stev-0** [comment]
No, QGIS 3.12. Since we can both do it, and I am on WIndows, I think you must be doing something wrong or have a strange setup.

**Comment by cherifmad** [comment]
@gioman May be this problem is the fact of windows 10 ... I suppose that you use QGIS on Linux

**Comment by gioman** [comment]
@cherifmad Windows:

![Screenshot_20200303_140028](https://user-images.githubusercontent.com/1951107/75782774-5ce0dd80-5d57-11ea-8280-a7d391e5d871.png)

**Comment by cherifmad** [comment]
@gioman this is the step that I follow
![QGIS demo points1](https://user-images.githubusercontent.com/10108717/75783349-59018b00-5d58-11ea-8554-df0c63a6e937.gif)
I am very Sad

**Comment by cherifmad** [comment]
what is your QGIS version please @gioman ?

**Comment by gioman** [comment]
> @gioman this is the step that I follow

@cherifmad don't you see that you are missing to say QGIS that your decimal separator is the comma? Compare the checked options in my cast and yours...

**Comment by stev-0** [comment]
Hi @cherifmad if you can't follow instructions we can't help you - there are 3 seperate messages / videos on here telling you to check that box, and in the video you sent you didn't, so presume you are not doing it correctly.

**Comment by cherifmad** [comment]
@gioman thanks for your support , but even I use the comma , that is the same result, nothing in my layer
![QGIS demo points2](https://user-images.githubusercontent.com/10108717/75784504-307a9080-5d5a-11ea-8eb4-87f77191ffe3.gif)

**Comment by cherifmad** [comment]
I have use all options in QGIS 3.10 but when I use my old QGIS 2.18 the points appears very easily
@gioman I don't jump one step in my list GIF. Thanks for all

**Comment by gioman** [comment]
>  @gioman I don't jump one step in my list GIF. Thanks for all

@cherifmad have you been able to add the data?

**Comment by cherifmad** [comment]
@stev-0 thanks
I follow completly the step in my list gift. May be i will download the last version of qgis 3.10.3 and try it

**Comment by cherifmad** [comment]
> > @gioman Je ne saute pas d'une étape dans ma liste GIF. Merci pour tout
> 
> @cherifmad avez-vous pu ajouter les données?

Unfortunately I could not add the data

**Comment by gioman** [comment]
> Unfortunately I could not add the data

@cherifmad I tried with everything in French, it still works here.

**Comment by cherifmad** [comment]
Dear All, Finally, I have Download the last version of QGIS 3.10 ( QGIS 3.10.3)  and this problem is solved. Perrhaps the version of Qgis is the problem. Thanks a lot for your support and Lord Keep all members of Coronavirus.
