### ISSUE TITLE
Oauth authorization flows for WFS3

### ISSUE THREAD

**Issue by woodsyb** [qgis/QGIS#34836]
**Feature description.**
The WFS3 functionality looks really cool but it doesn't seem to support any authentication schemes like the other services(such as oauth). It would be really nice if we were able to authenticate a WFS3 service in the same way you can with a WMTS.

**Comment by elpaso** [comment]
Hi, Interesting proposal, I myself thought about adding auth backends in the core several times in the past but for now you need to delegate that functionality to another application tier or use a QGIS Server Python Plugin.

Note that auth is not WFS3 specific, but WFS/WMS etc. are also unprotected.

In any event, you can implement your auth scheme today using QGIS Server python plugins, you can have a look to https://github.com/qgis/QGIS/blob/master/tests/src/python/qgis_wrapped_server.py (it was developed for integration testing and it is **not production ready**) auth provider examples, it provides PKI, HTTP Basic, OAuth resource owner.

I'll leave this request open, just in case there are more people interested and willing to fund such a (probably big) development.

**Comment by elpaso** [comment]
re-reading your text I'm not so sure you were talking about the server though. But I think that OAuth (and all other QGIS auth plugins) are already implemented for the client, aren't they?
