### ISSUE TITLE
3.10.3 - Web maps (ie open street map) not appearing correctly after installing missing transformation

### ISSUE THREAD

**Issue by mattenvsys** [qgis/QGIS#34842]
Hi,

Just upgraded from QGIS 3.4.15 to 3.10.3 

Opened a previous project file, created in 3.4.15, which contains data in EPSG 27700 and 4326. Then I was greeted with this window:

![missing_transformation](https://user-images.githubusercontent.com/15214610/75765717-d79a0080-5d37-11ea-94be-782b6fe86b2a.png)

The 27700 layers are vector datasets in the UK, the 4326 data is the xyz tile service for open street map and bing imagery.

As the unavailable preferred option is stated to be more accurate, our IT manager installed the missing file from the link provided in the message.

After opening the project again, selecting the preferred transformation option, the web layers were not displaying correctly:

![qgis_screenshot](https://user-images.githubusercontent.com/15214610/75766431-0b295a80-5d39-11ea-906f-9ab7cdf997e6.png)

Here's the about QGIS window about my installation:

![qgis_about](https://user-images.githubusercontent.com/15214610/75766907-cd790180-5d39-11ea-89e2-95f9b4af9664.png)

QGIS version
3.10.3-A Coruña
QGIS code revision
0e1f846438
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.1
Running against PROJ
Rel. 6.3.1, February 10th, 2020
OS Version
Windows 10 (10.0)
Active python plugins
envsysCoastal3; 
envsysSend2google_earth; 
GroupStats; 
mapswipetool_plugin; 
OSTranslatorII; 
pointsamplingtool; 
qdraw; 
qfieldsync; 
Qgis2threejs; 
SemiAutomaticClassificationPlugin; 
splitmultipart; 
db_manager; 
MetaSearch; 
processing

I'm running Windows 10 Pro
Version: 1903
OS Build 18362.657

I am able to reproduce this bug using Ordnance Survey open data, which I have attached. This layer was added to a fresh QGIS canvas. Selecting the preferred transformation:

![qgis_preferred](https://user-images.githubusercontent.com/15214610/75767240-627bfa80-5d3a-11ea-81a1-fc5f890ed6dd.png)

Then using this xyz tile layer: 

https://tile.openstreetmap.org/{z}/{x}/{y}.png

Creates this result:

![qgis_screenshot02](https://user-images.githubusercontent.com/15214610/75769047-60676b00-5d3d-11ea-8dbb-348f5d102954.png)

[junction_font_point.zip](https://github.com/qgis/QGIS/files/4280742/junction_font_point.zip)

**Comment by nirvn** [comment]
@mattenvsys , this has been addressed in QGIS 3.12 (out now) and upcoming 3.10.4 (to be released on March 20th). 

In the meantime, you can either install QGIS 3.12, or pick the 2-meter accuracy transformation (the second choice in the transformation dialog).

**Comment by mattenvsys** [comment]
Hi @nirvn would the 1 metre accuracy transformation also be included in 3.10.4 or would we need to manually install it again?

**Comment by nirvn** [comment]
If you manually installed it into your user folder, that'll be there when you update to 3.10.4.
