### ISSUE TITLE
Crashing when trying to open up options 

### ISSUE THREAD

**Issue by azstumbler** [qgis/QGIS#34849]
## User Feedback

trying to open up the option menu under settings.

## Report Details

**Crash ID**: [9dba32b287f8d89304cee6e3b94abb40dc0658a1]('https://github.com/qgis/QGIS/search?q=9dba32b287f8d89304cee6e3b94abb40dc0658a1&type=Issues')

**Stack Trace**
<pre>
cl::detail::getInfoHelper<cl::detail::GetInfoFunctor0<int (__cdecl*)(_cl_context * __ptr64,unsigned int,unsigned __int64,void * __ptr64,unsigned __int64 * __ptr64),_cl_context * __ptr64>,cl::Device> cl2.hpp:1014
cl::Context::getInfo<std::vector<cl::Device,std::allocator<cl::Device> > > cl2.hpp:2868
cl::Context::getInfo<4225> cl2.hpp:2881
cl::Device::makeDefault cl2.hpp:2955
std::_Callback_once<std::tuple<void (__cdecl&)(void),std::exception_ptr & __ptr64>,std::integer_sequence<unsigned __int64,0>,1> mutex:497
RtlRunOnceExecuteOnce :
InitOnceExecuteOnce :
__crtInitOnceExecuteOnce winapisupp.cpp:295
cl::Device::getDefault cl2.hpp:2012
QgsOpenClUtils::activeDevice qgsopenclutils.cpp:272
QgsOpenClUtils::activate qgsopenclutils.cpp:310
<lambda_e52bae7ef377df945b84291a90b55216>::operator() qgsopenclutils.cpp:184
std::_Callback_once<std::tuple<<lambda_e52bae7ef377df945b84291a90b55216> && __ptr64,std::exception_ptr & __ptr64>,std::integer_sequence<unsigned __int64,0>,1> mutex:497
RtlRunOnceExecuteOnce :
InitOnceExecuteOnce :
__crtInitOnceExecuteOnce winapisupp.cpp:295
QgsOpenClUtils::init qgsopenclutils.cpp:84
QgsOpenClUtils::available qgsopenclutils.cpp:466
<lambda_922094a53c4278625000fd604db93b4a>::operator() qgsoptions.cpp:1155
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::setChecked :
QgsOptions::QgsOptions qgsoptions.cpp:1201
QgisApp::createOptionsDialog qgisapp.cpp:11416
QgisApp::showOptionsDialog qgisapp.cpp:11422
QgisApp::options qgisapp.cpp:11301
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1609
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.12.0-Bucure?ti
QGIS code revision: cd141490ec
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by gioman** [comment]
@azstumbler try with a new QGIS profile, no 3rd party plugins installed.

**Comment by roya0045** [comment]
It seems the function is having issues with some of your device, could you provide info if there is anything unusual with your setup?

**Comment by gioman** [comment]
Closing for lack of feedback.
