### ISSUE TITLE
Polygonize misses intersections (ESPG:28426)

### ISSUE THREAD

**Issue by GSavelev-VSEGEI** [qgis/QGIS#34840]
The problem is very much similar to https://github.com/qgis/QGIS/issues/30731, but it is not really solved.

So, I have a line shape file containing the boundaries of polygons I need ([lines.zip](https://github.com/qgis/QGIS/files/4280392/lines.zip), pic.1). It is projected, the projection is ESPG:28426.
 ![Pic 1](https://user-images.githubusercontent.com/57714410/75761913-efc74b00-5d4a-11ea-80a6-e9d47a8b3a35.png)
Pic.1. Shape file with boundary features.
When I construct polygons with Polygonize (‘qgis:polygonize’) (pic.2), the program does not recognize some line intersections (pic.3).
![Pic 2](https://user-images.githubusercontent.com/57714410/75764900-a2011180-5d4f-11ea-8385-bf019710a29a.png)
Pic.2. Polygonize tool used.

![Pic 3](https://user-images.githubusercontent.com/57714410/75764935-af1e0080-5d4f-11ea-96bb-0a6c06969428.png)
Pic.3. Resulting polygons.
I understand, there must be a topology issue, but I do not seem to find an elegant solution to it, furthermore, ArcMap makes polygons from the same line shape file without any problem (pic.4-5-6).

![Pic 4](https://user-images.githubusercontent.com/57714410/75766573-6d428980-5d52-11ea-9b7e-08062ea8f4b9.png)
Pic.4. Shape file with boundary features.

![Pic 5](https://user-images.githubusercontent.com/57714410/75766615-7e8b9600-5d52-11ea-924d-6d4be6ae17a5.png)
Pic.5. Polygonize tool used. Target layer – polygons shape file with the same projection

![Pic 6](https://user-images.githubusercontent.com/57714410/75766631-85b2a400-5d52-11ea-9f49-50d7d537553f.png)
Pic.6. Resulting polygons

Should I try another projection and/or another data format? But really changing the projection musn't be a solution, because reprojecting before every polygonizing would be an argument for a GIS changing. Anyway it would be possible to make reprojection to a "good" CRS a part of polygonize tool.
P.S. All the projects and files 
[CONSTRUCTPOLYGONSISSUE.zip](https://github.com/qgis/QGIS/files/4280740/CONSTRUCTPOLYGONSISSUE.zip)

**Comment by gioman** [comment]
@GSavelev-VSEGEI 

right, the tool should output the expected results. Anyway you sample seems to be really a nasty one: I tried to snap/clean in any way I know (among the other GRASS) and to polygonize with different tool and the result is always not the expected obvious one. Really not sure where the underlying issue is.

**Comment by uclaros** [comment]
The inside lines are not snapped to the perimetric nodes in your layer. They are really close, like 1E-10 close, but not snapped. If you first run *Snap geometries to layer* , select the same layer twice and pick *Snap to anchor nodes (single layer only)* with a tolerance bigger than your gaps (1E-9 in your case) it will be fixed.
You can also run *Snap points to grid* with a tolerance that fits the precision of your data. This is what I believe arcmap does implicitly with most it's geoprocessing tools, snap to grid to the dataset's XY resolution.
With the tool you used, *construct polygons*, you picked a cluster tolerance of 0.001m so it's the equivalent to running *snap points to grid* with a grid of 0.001m prior to using *Polygonize*

**Comment by gioman** [comment]
> The inside lines are not snapped to the perimetric nodes in your layer. They are really close, like 1E-10 close, but not snapped. If you first run _Snap geometries to layer_ , select the same layer twice and pick _Snap to anchor nodes (single layer only)_ with a tolerance bigger than your gaps (1E-9 in your case) it will be fixed.

@uclaros good catch. After all I was also able to snap with GRASS using v.clean (tool "snap"), when I first tried I was not setting correctly the tolerance.



>This is what I believe arcmap does implicitly with most it's geoprocessing tools, snap to grid to the dataset's XY resolution.

that's correct, at least I also have been told so.

**Comment by GSavelev-VSEGEI** [comment]
Cheers @uclaros, @gioman, snapping to layer really sovles this problem. I think, it originates from shapefile xy tolerance is not always the same 
[ESRI FAQ Why is the XY tolerance calculated differently depending on data type](https://support.esri.com/en/technical-article/000012626)
