### ISSUE TITLE
DB Browser not show PostgreSQL/PostGIS tables

### ISSUE THREAD

**Issue by rmarzocchi84** [qgis/QGIS#34844]
Using QGIS 3.10.3 (or 3.12) on windows not all the PostGIS connections are correctly viewed. 

See the example in the follwing image:

![image](https://user-images.githubusercontent.com/4061154/75784056-e9909900-5d61-11ea-8449-91d289568283.png)

S.O. Windows 10
QGIS 3.10.1 and QGIS 3.12.1
Qt 5.11.2
GDAL/OGR 3.0.4
GEOS 3.8.0-CAPI-1.13.1 
SQLite  3.29.0
Client PostgreSQL v. 11.5
SpatiaLite v.  4.3.0
QWT v- 6.1.3
QScintilla2 v 2.10.8
Compiled against PROJ 6.3.1
Rel. 6.3.1, February 10th, 2020

**Comment by elpaso** [comment]
You need to attach a SQL that we can use to reproduce the issue.

**Comment by gioman** [comment]
@elpaso is not related to a specific table/layer.

I have seen this a few days ago too and I was waiting to gather more infos before reporting it.

In my case I "solved" by giving the user permission to read the raster_columns and raster_overviews views, after that the layer list started to show again in the browser. Anyway this was not necessary in past QGIS releases. @rmarzocchi84 can you check if is also your case?

**Comment by elpaso** [comment]
@gioman this issue doesn't seems related to rasters, anyway there is actually a check for read permissions in the new API and it makes sense to me at least for rasters, because without being able to read raster_columns and raster_overviews we cannot correctly instanciate the data provider, in theory we could still read the raster data but with a great deal of inefficiency, for this reason it is not supported.

**Comment by gioman** [comment]
> @gioman this issue doesn't seems related to rasters, anyway there is actually a check for read permissions in the new API and it makes sense to me at least for rasters, because without being able to read raster_columns and raster_overviews we cannot correctly instanciate the data provider, in theory we could still read the raster data but with a great deal of inefficiency, for this reason it is not supported.

@elpaso yeah... I made some more tests and cannot replicate from scratch what I described here https://github.com/qgis/QGIS/issues/34844#issuecomment-594046579 

So at this point I'm not anymore sure about what causes the issue described in this ticket (despite having seen the same thing and having solved by granting permissions on that default views).

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
