### ISSUE TITLE
QGIS 3.12 on Ubuntu Crashes by adding a table with no Geometry from PostGIS 

### ISSUE THREAD

**Issue by rjhale1971** [qgis/QGIS#34851]
I'm running: 
QGIS -> 3.12 409bcf8eaa on Ubuntu 19.10 
QGIS -> 3.12 cd141490ec on Windows 10 Pro 

I've test this with Postgresql/PostGIS 12/3 and Postgresql 11.6/2.5 

If you add a table without geometry to the Ubuntu version it results in a crash with:
 QGIS died on signal 11Aborted (core dumped)

On windows 10 it's fine - everything works and no crashing. 

I at least think this is a bug - I've tried a few things and it's consistent and doesn't seem to be a bad install on this linux box and doesn't seemed to be confined to my install of PostgreSQL/PostGIS.

**Comment by gioman** [comment]
> If you add a table

@rjhale1971 Hi. Regardless of the way the table is added (db manager, browser, etc.)?

regardless of the table or just with some specific one?

**Comment by rjhale1971** [comment]
Good point. If I use the Data Source Manager to add the tables it crashes. I cannot see the tables using the QGIS Browser. 

I tested with DB Manager and adding the table from there (right clicking and add) caused it to crash also.

**Comment by gioman** [comment]
> If you add a table without geometry to the Ubuntu version it results in a crash with:
> QGIS died on signal 11Aborted (core dumped)

@rjhale1971 I can't confirm here on Ubuntu 18.04 and QGIS 3.12. Can you attach the dump of one of your tables?

**Comment by rjhale1971** [comment]
Will do - Give me just a bit and I'll dump the schema with all the tables. Thanks for your help on this.

**Comment by rjhale1971** [comment]
Update. I just built a VM (finished the one I started yesterday)  and it loaded the table without problem. So it seems this is a local problem to this machine. Which is more troubling as I don't know what it could be as it's not tossing an error.

**Comment by rjhale1971** [comment]
Update - So I made a new profile and it's not crashing. So that leaves me with a plugin I guess? Lemme investigate more.

**Comment by rjhale1971** [comment]
AHA - it's the GeocatBridge Plugin. I will close this and move over and hassle them. @gioman - I thank you for the help and your patience.
