### ISSUE TITLE
DB Manager - 'geometry_dump' not supported (ignored due to unsupported field type)

### ISSUE THREAD

**Issue by geozelot** [qgis/QGIS#34866]
**Describe the bug**
PostGIS `geometry_dump` type as QGIS field type (c) is not supported.

**How to Reproduce**
Run any query that returns a `geometry_dump` type, e.g.
```
SELECT ST_Dump('MULTIPOINT((0 0), (1 1))'::GEOMETRY)
```

**QGIS and OS versions**

QGIS version | 3.12.0-București | QGIS code revision | 409bcf8eaa
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 10.12 (Ubuntu 10.12-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Linux Mint 19.1
Active python plugins | Qgis2threejs; FreehandRasterGeoreferencer; refFunctions; processing; MetaSearch; db_manager

**Additional context**
Example Log output:
```
2020-03-04T13:40:29  WARNING  Field st_dump ignored, because of unsupported type c
```

**Comment by geozelot** [comment]
@gioman sorry for the BUG flag, but I was under the impression I never had that issue in any prior versions...

**Comment by gioman** [comment]
> sorry for the BUG flag, but I was under the impression I never had that issue in any prior versions. May be wrong though.

@geozelot can you check? Happy to tag as bug if it worked properly in the past.

**Comment by elpaso** [comment]
maybe fixed by https://github.com/qgis/QGIS/pull/34815 can you please check latest master?

**Comment by geozelot** [comment]
@gioman @elpaso sure, will set up a test env later today, can't do it right away...

**Comment by gioman** [comment]
Assuming fixed.
