### ISSUE TITLE
PostGIS connection parameters in DB manager are updated only after a QGIS restart

### ISSUE THREAD

**Issue by NyakudyaA** [qgis/QGIS#34862]
# Problem

I previously defined a DB connection using the following parameters:
IP Address: `10.0.0.115` etc and I could connect successfully to the DB. 

I then changed my connection parameters from using the IP address to the localhost and can connect to the same database using Datasource manager. But when I use DB Manager it still references the old connection details.

New connection DB

![Screenshot 2020-03-04 at 13 43 01](https://user-images.githubusercontent.com/2510900/75876656-c7108580-5e1e-11ea-975c-a6f687aaaa5e.png)

In DB Manager It still uses the old credentials

![Screenshot 2020-03-04 at 13 42 24](https://user-images.githubusercontent.com/2510900/75876773-00e18c00-5e1f-11ea-92e0-8356c477cd81.png)

![Screenshot 2020-03-04 at 13 52 07](https://user-images.githubusercontent.com/2510900/75876997-603f9c00-5e1f-11ea-92ee-882e0a090d11.png)

OS System: Mac 

NB: I do not need to restart QGIS to activate these settings. I tried to open and close DB manager thinking it would help but it didn't. 

Update I then changed the connection name in Data Source Manager but it still doesn't refresh in DB manager.

**Comment by gioman** [comment]
> But when I use DB Manager it still references the old connection details.

@NyakudyaA even after restating QGIS?

**Comment by NyakudyaA** [comment]
> > But when I use DB Manager it still references the old connection details.
> 
> @NyakudyaA even after restating QGIS?

I haven't restarted my QGIS, currently doing training and will test that out but I should not be restarting QGIS for a small change like this.

**Comment by gioman** [comment]
> but I should not be restarting QGIS for a small change like this.

@NyakudyaA I have not said  that is ok, just trying to help developers with some additional detail.

**Comment by NyakudyaA** [comment]
> > but I should not be restarting QGIS for a small change like this.
> 
> @NyakudyaA I have not said that is ok, just trying to help developers with some additional detail.

@gioman If I restart QGIS it fixes the issue. So it seems the main issues happen when you are in the same session that parameters persist. Probably because the machine IP had changed from the previous one that's why I needed to change the IP to localhost

**Comment by gioman** [comment]
Very minor issue I would say.

**Comment by NyakudyaA** [comment]
> Very minor issue I would say.

@gioman I wouldn't classify this as a minor issue. I think it is a serious bug. I just defined a new connection and then went to DB manager. I can refresh my connection but nothing happens
![save](https://user-images.githubusercontent.com/2510900/75989582-31e3be80-5efc-11ea-97ce-3a902d9a12bc.gif)

**Comment by gioman** [comment]
>  wouldn't classify this as a minor issue. I think it is a serious bug. I just defined a new connection and then went to DB manager. I can refresh my connection but nothing happens

@NyakudyaA probably two consequences of the same bug. Can you test please if this is a regression (i.e. test on the past LTR releases, 3.4 and 2.18), thanks.

**Comment by gioman** [comment]
Both issues confirmed on 3.10.3 and 3.12, now testing master and old LTRs too.

**Comment by gioman** [comment]
Both issues are regressions, all ok on 3.4.

**Comment by elpaso** [comment]
Can someone please test if changing:
QGIS/python/plugins/db_manager/db_plugins/plugin.py:207
from 
```
for name in md.dbConnections().keys():
```
to
```
for name in md.dbConnections(False).keys():
```
helps?

**Comment by gioman** [comment]
> Can someone please test if changing:

@elpaso it does fixes the problems indeed. Thanks!
