### ISSUE TITLE
Map canvas draws weird drawings when map is rotated

### ISSUE THREAD

**Issue by kadirsahbaz** [qgis/QGIS#34860]
When I pan the map canvas content, strange drawings appear on it. The same thing happens when zooming but I couldn't capture that.

![model3](https://user-images.githubusercontent.com/15310223/75867074-1488f480-5e17-11ea-873e-cd20bd6cf05e.gif)

**QGIS and OS versions**
3.12.0-București
QGIS code revision
cd141490ec
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.1
Running against PROJ
Rel. 6.3.1, February 10th, 2020
OS Version
Windows 10 (10.0)
Active python plugins
IPyConsole; 
quick_map_services; 
db_manager; 
MetaSearch; 
processing

**Comment by gioman** [comment]
@kadirsahbaz not enough info. If possible attach a sample project + data.

**Comment by kadirsahbaz** [comment]
I forgot to mention that it occurred after changing map rotation from statusbar.

**Comment by roya0045** [comment]
Its just rendering artifacts. It doesn't affect the final output, I doubt this is even worth keeping open.
