### ISSUE TITLE
QGIS 3.4.15 crashes while working in layouts

### ISSUE THREAD

**Issue by pizzobarone** [qgis/QGIS#34863]
## User Feedback

I wanted to save the project in the layout. At the moment every project crashes after approximately 10 minutes. I also started to work in a new profile (without any plugins). The same...

## Report Details

*Crash ID*: 3068ef16e97b0ef734d39ec6783690990807c54b

*Stack Trace*
<pre>
qt_addBitmapToPath :
QFontEngineMulti::alphaRGBMapForGlyph :
QFontEngine::loadKerningPairs :
qt_plugin_query_metadata :
qt_plugin_query_metadata :
vDeleteLOCALFONT :
QFontInfo::family :
QFontDatabase::load :
QFontDatabase::applicationFontFamilies :
QFontDatabase::load :
_malloc_base :
</pre>

*QGIS Info*
QGIS Version: 3.4.15-Madeira
QGIS code revision: e83d02e274
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.3
Running against GDAL: 2.4.3

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
>  QGIS Version: 3.4.15-Madeira

@pizzobarone Thanks for the report. QGIS 3.4 is EOL so anyway you should test with 3.10.3 (the new LTR).

**Comment by roya0045** [comment]
@pizzobarone still occuring in more recent versions?

**Comment by gioman** [comment]
Closing for lack of feedback.
