### ISSUE TITLE
QGIS crashes when trying to identify a GRASS layer

### ISSUE THREAD

**Issue by malapradej** [qgis/QGIS#34864]
I imported an existing shapefile points layer into GRASS using v.in.ogr without errors. When I identify click on a point in this GRASS layer QGIS crashes. I'm running version 3.12.0-București on Ubuntu 18.04 LTS. The same crash happens when I try to open the table view for the GRASS layer, but it doesn't crash when selecting the view the layers properties.

**Comment by gioman** [comment]
Confirmed here too.

**Comment by gioman** [comment]
@malapradej it does not happen on Windows, that ships with much more recent dependencies (GDAL, PROJ) than Ubuntu 18.04.

**Comment by gioman** [comment]
This must be checked again on Ubuntu 20.04.

**Comment by malapradej** [comment]
Is there a temporary solution? Is it a GRASS or QGIS issue? Should I try and update GRASS to a later version?

**Comment by jradinger** [comment]
I can also confirm this issue when querying a line segment of a GRASS layer in QGIS 3.12.0-București on Ubuntu 19.10. QGIS also crashes when I want to open the attribute table. 

Potentially related: QGIS also crashes when the I want use a different symbology for my lines, e.g. to colorize the lines based on an attribute.

_Additional note: The GRASS layer was initially created with the latest (selfcompiled) GRASS version_

**System**

```
QGIS version | 3.12.0-București | QGIS code revision | 117da6e0f4
Compiled against Qt | 5.12.4 | Running against Qt | 5.12.4
Compiled against GDAL/OGR | 2.4.2 | Running against GDAL/OGR | 2.4.2
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.7 (Ubuntu 11.7-0ubuntu0.19.10.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.10.4
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Ubuntu 19.10 | This copy of QGIS writes debugging output.
Active python plugins | openlayers_plugin; processing; db_manager; MetaSearch
```

**Comment by gioman** [comment]
> I can also confirm this issue when querying a line segment of a GRASS layer in QGIS 3.12.0-București on Ubuntu 19.10. QGIS also crashes when I want to open the attribute table.

@jradinger as I wrote above this must be checked on 20.04 that has the necessary recent dependencies (GDAL 3, Proj6, etc).

At the moment testing anything in QGIS >= 3.10 that has not such recent dependencies is not very useful.
