### ISSUE TITLE
[MSSQL] Snapping for new features does not work

### ISSUE THREAD

**Issue by j-lippmann** [qgis/QGIS#34879]
hi,

there is an issue with snapping for new features **after** save the new features. the problem occur only with MSSQL provider. Affected QGIS versions:

QGIS 3.4.15
QGIS 3.10.3
QGIS 3.12.0

steps:
1.  digitize a new feature
2. save the feature
3. try to snap the new feature

![mssql_snapping](https://user-images.githubusercontent.com/32189541/75922047-8e929b00-5e62-11ea-829b-c5871749c73f.gif)

`
QGIS version
3.10.3-A Coruña
QGIS code revision
a1a5ed3f6c
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.0dev
Running against GDAL/OGR
3.1.0dev
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
7.1.0
Running against PROJ
Rel. 7.1.0, August 1st, 2020
OS Version
Windows 7 SP 1 (6.1)
This copy of QGIS writes debugging output.
Active python plugins
alkisplugin; 
DbgGruen; 
plugin_reloader; 
db_manager; 
MetaSearch; 
processing
`

**Comment by j-lippmann** [comment]
Update:
the issue is still present in qgis 3.10.6 LTR
but with qgis 3.12 and master snapping works **after** press canvas refresh button

can anybody reproduce this problem? please contact me, if testdata needed.

thanks

**Comment by gioman** [comment]
> can anybody reproduce this problem? please contact me, if testdata needed.

@j-lippmann can you provide a mssql server endpoint for tests?

**Comment by j-lippmann** [comment]
> > can anybody reproduce this problem? please contact me, if testdata needed.
> 
> @j-lippmann can you provide a mssql server endpoint for tests?

@gioman a mssql server is little bit difficult, but a database dumpfile is easy for me.

**Comment by gioman** [comment]
> @gioman a mssql server is little bit difficult, but a database dumpfile is easy for me.

@j-lippmann can we install locally an instance of mssql server + spatial (without requiring any registration to MS or any MS account) as easily as we can do with PostgreSQL/PostGIS? And what about restoring a dump file, is as easy as with pgsql/postgis?

**Comment by j-lippmann** [comment]
@gioman  install mssql on local win is easy. Some requirements like .NET Framework...install on Linux is possibile too...but i have no expirience. I will Upload a dumpfile tomorrow. Restore is easy like with postgres. Thanks so far.

**Comment by gioman** [comment]
> install mssql on local win is easy. Some requirements like .NET Framework.. Restore is easy like with postgres. Thanks so far.

I will need some guidance anyway.

**Comment by j-lippmann** [comment]
hi @gioman 
after more test i figure out that a trigger was the reason for snapping issue. 
**I rewrote the trigger and solved the problem.** 
The old trigger worked without problems for 5 years. but with an early qgis 3.4.X? version the behavior of qgis has changed.

thanks

**Comment by w0pr** [comment]
Hi @j-lippmann 

> hi [@gioman](https://github.com/gioman) after more test i figure out that a trigger was the reason for snapping issue. **I rewrote the trigger and solved the problem.** The old trigger worked without problems for 5 years. but with an early qgis 3.4.X? version the behavior of qgis has changed.

I seem to have the same problem with QGIS 3.40.7 and a postgresql layer based on a view that is handled by an instead of UPDATE, INSERT, DELETE trigger. Can you give me any input on what you did to fix it?

Nevermind. After discovering another similar issue from 2015 regarding oracle provider https://github.com/qgis/QGIS/issues/20796 that was fixed in https://github.com/qgis/QGIS/commit/d3df4edaedc9542830dba1a99ce1b20d2bdc5773, I checked my trigger and discovered that I did not return newly inserted fid column.
