### ISSUE TITLE
QGIS 3.10.3 crashes at open

### ISSUE THREAD

**Issue by XavierCalatrava** [qgis/QGIS#34870]
## Report Details

**Crash ID**: [70507434ed785a113cdb249200d2a9737eb8e5fe]('https://github.com/qgis/QGIS/search?q=70507434ed785a113cdb249200d2a9737eb8e5fe&type=Issues')

**Stack Trace**
<pre>
operator<< :
operator<< :
QMetaType::save :
QVariant::save :
operator<< :
QSettings::value :
QSettings::value :
QSettings::sync :
QThreadPool::maxThreadCount :
QUrlQuery::setQueryItems :
QXmlStreamStringRef::~QXmlStreamStringRef :
QSettings::QSettings :
QgsSettings::QgsSettings qgssettings.cpp:76
QgsPluginRegistry::loadPythonPlugin qgspluginregistry.cpp:292
QgsPluginRegistry::restoreSessionPlugins qgspluginregistry.cpp:573
QgisApp::QgisApp qgisapp.cpp:1249
main main.cpp:1353
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.3-A Coru�a
QGIS code revision: 0e1f846438
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
@XavierCalatrava does it make any difference if you manually wipe (maybe do a backup first) the QGIS folder in your Windows user profile?

**Comment by XavierCalatrava** [comment]
Is this folder?

**Comment by gioman** [comment]
C:\Users\username\AppData\Roaming\QGIS

**Comment by XavierCalatrava** [comment]
Thanks. It works now.
