### ISSUE TITLE
[DB-Manager] postgresql views are not recognized on the Info tab

### ISSUE THREAD

**Issue by SamyFR** [qgis/QGIS#34886]
In QGis 3.12, the Info tab returns incorrect information about postgresql views (and materialized views too), and these views can't be  added to canvas because "_PostgreSQL layer has no primary key_".
Example : 
### General info
Relation type: Table
Owner: samyfr
Pages: 0
Rows (estimation): 0
Rows (counted): 3716
Privileges: select, insert, update, delete
There's a significant difference between estimated and real row count. Consider running VACUUM ANALYZE.
No primary key defined for this table!
### Fields
[...]
.

In QGis 3.10, it's ok with the same view that can be added in canvas :
### General info
Relation type: View
Owner: samyfr
Pages: 0
Rows (estimation): 0
Rows (counted): 3716
Privileges: select, insert, update, delete

**Comment by elpaso** [comment]
Can you please attach a SQL dump to reproduce the issue?

**Comment by SamyFR** [comment]
Here is a dump of the source table and an another dump of the view.
https://framabin.org/p/?92be4c92b69cf460#Px1pM/9P0nZXIqgB7E8gNo0vrBhcALKNZdA5IMkKir4=
https://framabin.org/p/?8714fcaef3a76976#baIque4o6MG/X9D1z+Fio61Fjc9ZTplwHkT+13gZ2iA=

**Comment by gioman** [comment]
Confirmed also here, only on 3.12 (3.10.3 is ok).

**Comment by gioman** [comment]
> Can you please attach a SQL dump to reproduce the issue?

as far as I can see it does not depend on the data, I tested several DBs with several Views and MT created in many different ways.
