### ISSUE TITLE
Toolbox features: Grid, GDAL and SAGA Raster clipping not working

### ISSUE THREAD

**Issue by eddjharrison** [qgis/QGIS#34881]
Randomly encountered "Create Grid" function not working in the QGIS toolbox, think its since installing 3.12, however I've tried on both 3.10 and 3.12 and come across the same issues. The drop down with units for horizontal and vertical spacing is now gone and stuck on degrees, with an error symbol that is unclickable or provides no errors when hovering over.

![image](https://user-images.githubusercontent.com/61405769/75958112-d98ccc80-5ebb-11ea-861f-3ce5d9d1a525.png)

Similarly when using both the GDAL "Clip raster by mask layer" on a standard, small Geotiff I receive an error: 

![image](https://user-images.githubusercontent.com/61405769/75960438-5ae65e00-5ec0-11ea-85b0-f81d9b5570f2.png)

**Comment by DelazJ** [comment]
> The drop down with units for horizontal and vertical spacing is now gone and stuck on degrees,

What is the CRS of your project file? I guess epsg:4326. Try with a non geographic one.

**Comment by gioman** [comment]
> The drop down with units for horizontal and vertical spacing is now gone and stuck on degrees

@eddjharrison as @DelazJ noted this is likely because your project CRS is in degrees, just change it to a projected one.

> Similarly when using both the GDAL "Clip raster by mask layer" on a standard, small Geotiff I receive an error:

can you see the "Error 3" in the log you posted? it is saying to you that you don't have enough disk space to perform the operation (the output file size just under the error message is very suspicious...).

**Comment by gioman** [comment]
Also please 1 issue each ticket.

**Comment by alexbruy** [comment]
As @gioman said, please file separate tickets for each issue.
