### ISSUE TITLE
QGIS Crashes after selecting CRS EPSG:27700 and adding KMZ file into project

### ISSUE THREAD

**Issue by AsifMehmood690** [qgis/QGIS#34889]
**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

QGIS version
3.12.0-București
QGIS code revision
cd141490ec
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.1
Running against PROJ
Rel. 6.3.1, February 10th, 2020
OS Version
Windows 10 (10.0)
Active python plugins
contour; 
OSMDownloader; 
planet_explorer; 
qgis2web; 
QuickOSM; 
quick_map_services; 
db_manager; 
MetaSearch; 
processing

**Additional context**

I am trying to add CRS from Ordinance Survey UK OSTN15_NTv2. It has added but everytime I try to use it for transforming from WGS84 (e.g. Google KMZ file), it gives me multiple options and when I select the option with 1m accuracy it gives some kind of warning telling data may not be accurately transformed. and after that if I add KMZ file it crashes. report is as below.

Crash ID: 3753eb214710ce027f603800df5bb3ad43f22232

Stack Trace

QTextOption::wrapMode :
QTextOption::wrapMode :
QRasterPaintEngine::drawImage :
QRasterPaintEngine::drawImage :
QPainter::drawImage :
QPainter::drawImage :
QgsMapCanvasMap::paint qgsmapcanvasmap.cpp:96
QGraphicsScene::dragMoveEvent :
QGraphicsScene::drawItems :
QGraphicsScene::drawItems :
QGraphicsView::paintEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QApplication::windowIcon :
QWidget::event :
QgisApp::event qgisapp.cpp:2017
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1609
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.12.0-Bucure?ti
QGIS code revision: cd141490ec
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by gioman** [comment]
@AsifMehmood690 attach sample project+data, thanks.

**Comment by yuhui-maker** [comment]
the same question,when i  open the projection properties|crs dialog,but you can't do anything(select or browe the crs), click on....it crash...i have tried the version  3.4

**Comment by gioman** [comment]
> the same question,when i open the projection properties|crs dialog,but you can't do anything(select or browe the crs), click on....it crash...i have tried the version 3.4

@yuhui-maker it is not a general QGIS issue, of course. Try the same suggestion that was given here: https://github.com/qgis/QGIS/issues/34891#issuecomment-595368095

**Comment by nirvn** [comment]
Additional steps to reproduce (in the form of a numbered list of steps) and test data would be useful here.

**Comment by gioman** [comment]
Closing for lack of feedback.
