### ISSUE TITLE
Implement a layer icon indicating a join

### ISSUE THREAD

**Issue by bkepl** [qgis/QGIS#34899]
If a layer has a join, it would be useful to indicate this in the layers panel just as there are icons for a filter being applied to the layer or for the layer being a memory layer.

**Comment by 3nids** [comment]
I don't think this is an information that should be visible in the legend.
There were already several propositions about adding icons in the legend. I wonder if we should not provide something to handle this? Either in the tool tip or a toggle to show/hide extra icons.

**Comment by bkepl** [comment]
While I avoid adding several instances of the same layer, there are times when I will, and some of those may have one or more joins that others don’t. I don’t always remember which is which, so having an icon indicating the presence of a join would be useful to me.

**Comment by 3nids** [comment]
I would propose to either rename the layers according to what they are in your project.
Otherwise, a plugin could be the way to go here.

**Comment by bkepl** [comment]
Actually, this is normally my practice, although sometimes I forget to do it. Still, I think the icon would be nice to have.

**Comment by alexbruy** [comment]
Duplicates #18614.
