### ISSUE TITLE
Embed layers and groups - layer styling not supportet or not layer

### ISSUE THREAD

**Issue by tm261700** [qgis/QGIS#34903]
Options "open the layer styling panel (F7)" not working for layer/projekt (*.qgs) added from Layer->Embed layers and groups.

QGIS 64bits  version 3.10.0-A CoruÃ±a QGIS code revision 6c816b4204

![Embed layers and groups](https://user-images.githubusercontent.com/45361214/76067274-63f23080-5f8f-11ea-8bd4-8d75f80b52cf.jpg)

**Comment by haubourg** [comment]
Hi, it's not a bug. Embedded layers can't be styled from the child project, because they inherit from another project.
