### ISSUE TITLE
Plugin with thread

### ISSUE THREAD

**Issue by Pilou59** [qgis/QGIS#34916]
Hello every one,

I've got a problem trying to make a plugin with a thread inside.

I've got a QDockWidget class and a QThread ("Controleur") class.

The dockWidget class instanciate a thread("self.Ctrl1 = Controleur(self)") and launch it.

I have connected the run method to the started signal "self.thread.started.connect(self.Ctrl1.run)"

QGis crashes anytime on "self.thread.start()" command.

Her is a part of my code :

self.Ctrl1 = Controleur(self)
self.thread = QThread(self)
self.Ctrl1.moveToThread(self.thread)
self.thread.started.connect(self.Ctrl1.run)
self.thread.start()

Could someone say me where I'm wrong ?

## User Feedback

trying to work with à thread...

## Report Details

*Crash ID*: d1c326b82fbf119367f83b674415b90f23a366de

*Stack Trace*
<pre>
QWindowPrivate::create :
QWidgetPrivate::create_sys :
QWidget::create :
QWidget::setVisible :
QDialog::setVisible :
QDialog::exec :
QMessageBox::showEvent :
QMessageBox::information :
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QMetaObject::activate :
QThread::started :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.8.2-Zanzibar
QGIS code revision: 4470baa1a3
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by roya0045** [comment]
Not a bug,of QGIS, possibly bad code or a QT limit. Please use the dev mailing list instead.
