### ISSUE TITLE
Display the User expression itself in the help panel

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#34919]
Having an expression saved as user expression, when you select it under the "User expression" group, only the help text is displayed in the right panel. I think that other than the help, the expression itself should be shown, otherwise, it's not obvious to guess whether the expression you select is really the one you want, when you have a big collection.
IOW, what is shown in the expression editor (left) should also be displayed in the help panel (right)
![image](https://user-images.githubusercontent.com/7983394/76102706-abe57780-5fd0-11ea-8cb7-f501acd7db31.png)
For information, "Recent" expressions show their expression in the help panel

**Comment by elpaso** [comment]
:+1: Agreed, good idea.
