### ISSUE TITLE
[Diagrams] Stacked bars do not display the "Axis line symbol"

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#34915]
In layer properties > Diagrams, > stacked bars, the "show axis" under the rendering tab does not seem to render the axis line symbol in the map canvas
![image](https://user-images.githubusercontent.com/7983394/76087013-9878e300-5fb5-11ea-87fc-30d36fc9784a.png)
Note that it renders if I set the diagram type to "histogram".
I wonder if the setting is broken or should be hidden when in "stacked bars" mode...

QGIS 3.12.0 on Windows 10

**Comment by alexbruy** [comment]
I think it is not redered (probably was not implemented/overlooked). We need axis as without it sctacked bars with negative values can not be identified.
