### ISSUE TITLE
OGR error Setting object

### ISSUE THREAD

**Issue by JoseLuisAza** [qgis/QGIS#34923]
when I try to add a field to a kmz map layer and edit that field and save the OGR error setting object 51 Invalid Index 11

**Comment by gioman** [comment]
@JoseLuisAza please attach sample data.

**Comment by gioman** [comment]
@JoseLuisAza also you miss completely to tell us what version of QGIS do you use and what operating system too.

**Comment by DogmaT2** [comment]
I have the same issue (QGIS version 3.16.0). Attaching shapefile.

STEPS
1 add vector layer GAR-1
2 open attributes table
3 open field calculator
4 add Geometry feature: $area (decimal valued feature)
5 confirm Preview area shows a numerical value
6 click OK

Here one of two things happens. Either I get the following message box:
ERROR: Could not add the new field to the provider.

Or the Field Calculator window closes. When I turn off editing (click on pencil), I am prompted to save. When I click yes, I get the error which says:
Layer GAR-1: OGR error setting feature 1: Invalid index : 11

[GAR-1.zip](https://github.com/qgis/QGIS/files/6288827/GAR-1.zip)

**Comment by gioman** [comment]
Closing for lack of feedback.



> I have the same issue (QGIS version 3.16.0). Attaching shapefile.

@DogmaT2 too old, update to the latest 3.16 or 3.18. 

Not replicable on the latest 3.16 or 3.18  on both Linux and Windows.

**Comment by DogmaT2** [comment]
I upgraded QGIS to 3.18.1-Zürich.
Still getting this error when attempting to add area value to a layer using the attribute table.
