### ISSUE TITLE
Network drives not showing in data source manager and QGIS browser

### ISSUE THREAD

**Issue by tveinot** [qgis/QGIS#34921]
**Describe the bug**
When my PC is rebooted all the network drives dropp in QGIS Browser and the File Browser. Windows shows the the network drives as normal in the File Explorer.

**How to Reproduce**

Turn PC off and back on, run QGIS

**QGIS and OS versions**

Issue is not present in 2.18.28
Issue is present in both 3.X versions

**Additional context**

This has been an on going issue and I am not sure why QGIS 3.X seems to refuse to read my network drives without me re-adding them through the QGIS File Browser window.

**Comment by gioman** [comment]
@tveinot what type is the share? samba? nfs? other?

**Comment by tveinot** [comment]
It is a netowrk drived mapped through Windows on a Windows Server. It is a file Server over a local network. Does that help?

**Comment by tveinot** [comment]
I don't understand your question sorry, but here is a screen grab of what I am experiencing;
![image](https://user-images.githubusercontent.com/26797978/77657263-d08b9a00-6f53-11ea-8770-a2cd82bad4e0.png)
As you can see on the left the File Explorer shows all my mapped network drive, simultaniously though QGIS browser and the add data explorer do not show any network drives. I really don't understand how the 2 can be different. To get them back I have to map the network drives from within the QGIS file explorer window.

**Comment by roya0045** [comment]
This seems strange, anyone else in your workplace with this issue?

**Comment by tveinot** [comment]
No, but I am th only one using 3.x

**Comment by gioman** [comment]
> No, but I am th only one using 3.x

@tveinot so no such issue on 2.*?

**Comment by Pedro-Murteira** [comment]
@tveinot Hello, is this still valid on more recent versions of QGIS? (3.22.4 or 3.24.0.)

**Comment by tveinot** [comment]
Hello,
You know it isn't and I don't know what or how it stopped being one lol.
Sorry I didn't take this down I forgot about it.
Tyler
