### ISSUE TITLE
Recently suffering from crash

### ISSUE THREAD

**Issue by cucumberwine** [qgis/QGIS#34927]
**Feature description.**
Crash ID: 6eb336e1707c696dc5f05710ca034d834befa383

Stack Trace

memcpy_repmovs memcpy.asm:114
VSICreateCachedFile :
SASetupDefaultHooks :
SHPReadObject :
SHPPartTypeName :
SHPPartTypeName :
QgsOgrFeatureIterator::fetchFeature qgsogrfeatureiterator.cpp:364
QgsAbstractFeatureIterator::nextFeature qgsfeatureiterator.cpp:63
QgsVectorLayerFeatureIterator::fetchFeature qgsvectorlayerfeatureiterator.cpp:416
QgsAbstractFeatureIterator::nextFeature qgsfeatureiterator.cpp:63
QgsVectorLayerRenderer::drawRenderer qgsvectorlayerrenderer.cpp:306
QgsVectorLayerRenderer::render qgsvectorlayerrenderer.cpp:284
QgsMapRendererCustomPainterJob::doRender qgsmaprenderercustompainterjob.cpp:312
QgsMapRendererCustomPainterJob::staticRender qgsmaprenderercustompainterjob.cpp:261
QtConcurrent::RunFunctionTask::run qtconcurrentrunbase.h:136
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.10.3-A Coruna
QGIS code revision: 0e1f846438
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

Who help this problem?

**Additional context**

**Comment by roya0045** [comment]
This seems like a  bug and not a feature request. context of the crash would be appreciated. Alo try with a new profile.

**Comment by gioman** [comment]
@cucumberwine please try with a new QGIS profile, no 3rd party plugins installed. If the problem persist please add the detailed (step by step) infos (and sample data) that are lading to the crash.

**Comment by gioman** [comment]
Closing for lack of feedback.
