### ISSUE TITLE
QGIS does not reproject properly

### ISSUE THREAD

**Issue by CoryAlbrecht** [qgis/QGIS#34933]
QGIS 3.13

With data entered in 4326, when I change the projection to 3573 to prepare for a print manager layout and export SVG, some lines are not drawn as expected.

It's not uncommon with long lines made up of only two widely separated points that look fine in a 4326/Mercator type projection to do this on projections that would show curves in the lines of latitude and longitude. The lines on my layers, however, are made up of multiple points and the intermediate one are not getting placed properly.
 
4326
![image](https://user-images.githubusercontent.com/8172909/76166778-7effa480-6137-11ea-9501-159c6d1d78be.png)

3573
![image](https://user-images.githubusercontent.com/8172909/76166634-604cde00-6136-11ea-9f08-0c844c40c29a.png)

Oddly, when I make the layer active, toggle edit mode to on, and then select the wrongly drawn lines, they get redrawn correctly. Ocasionally, but not always, they will redraw correctly after moving the canvas in edit mode, but not always. Selecting first guarantees the correct redraw.

![image](https://user-images.githubusercontent.com/8172909/76166646-7ce91600-6136-11ea-8f91-3419af277790.png)

They stay redrawn correctly even after deselecting and moving the canvas around, zooming,, as long as I do not toggle edit mode off.

![image](https://user-images.githubusercontent.com/8172909/76166694-d9e4cc00-6136-11ea-93e7-cc5e8140431a.png)

The revert to the badly drawn lines immediately after toggling off edit mode.

![image](https://user-images.githubusercontent.com/8172909/76166711-03055c80-6137-11ea-808d-7fef1aa9a4ef.png)

Note that the solid line at the bottom, which is in a different layer, also suffers froim this same problem

QGIS version | 3.13.0-Master | QGIS code revision | 13337b20cd
-- | -- | -- | --
Compiled against Qt | 5.12.2 | Running against Qt | 5.12.2
Compiled against GDAL/OGR | 2.4.0 | Running against GDAL/OGR | 2.4.0
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.27.2 | Running against SQLite | 3.27.2
PostgreSQL Client Version | 11.5 (Ubuntu 11.5-0ubuntu0.19.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.10.4
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Ubuntu 19.04 | This copy of QGIS writes debugging output.
Active python plugins | ClipMultipleLayers; postgisQueryBuilder; arrayplus; quick_map_services; qgis_hats; BoundingBox; Qgis2threejs; splitmultipart; postgis_geoprocessing; clipper; timemanager; db-style-manager; qgis2web; MetaSearch; db_manager; processing

The layer used for the example screencaps:

Name | timeline_level2_borders
-- | --
Source | dbname='Alternate History' host=pg1.db.cory.albrecht.name port=5432 sslmode=require authcfg=y3j5ksn key='id' srid=4326 type=MultiLineString checkPrimaryKeyUnicity='1' table="Balance of Power"."timeline_level2_borders" (geom) sql="start_date" = '1886/12/31'
Storage | PostgreSQL database with PostGIS extension
Comment |  
Encoding |  
Geometry | Line (MultiLineString)
CRS | EPSG:4326 - WGS 84 - Geographic
Extent | -135.4769919305130088,49.0000000000000000 : -100.0000000000000000,62.0000000000000000
Unit | degrees
Feature count | 10

The two feature lines used as example for selecting
[out.geojson.gz](https://github.com/qgis/QGIS/files/4303511/out.geojson.gz)

**Comment by uclaros** [comment]
Could be because of GDAL 2.4 / PROJ 5.2.0?
The lines you attached seem to display fine on 8addbde0a5 with GDAL 3.0.4 and PROJ 6.3.1

**Comment by gioman** [comment]
@CoryAlbrecht as far as I know/understand you cannot expect correct reprojections if using QGIS >= 3.10 and such old dependencies (GDAL and PROJ). If you upgrade to 20.04 the necessary recent dependencies are part of the official Ubuntu repos. @nyalldawson

**Comment by nirvn** [comment]
Did this *ever* work for you in the past with earlier versions of QGIS or have you just tried for the first time and witnessed it failing?

If this isn't a straightforward regression, I doubt it'll be addressed as there's little to no incentive to spend time working on obsolete gdal/proj.

Also, for that straight line at the bottom, if the original dataset only has two nodes to form the line, it'll only reproject those two nodes. You can use the density algorithm to add more points along lines.

**Comment by CoryAlbrecht** [comment]
@nirvn Yes, it has worked before. I reproject to something that will have have curved lines before I output to SVG to continue working on the artistic portion map. Just not with these new layers. as you can see, the graticules for longitude and latitude still worked OK.

**Comment by CoryAlbrecht** [comment]
@gioman I fetched from

```
# 3.13.x
deb http://qgis.org/ubuntu-nightly disco main
deb-src http://qgis.org/ubuntu-nightly disco main
```
Are the packages like
```
…
http://qgis.org/ubuntu-nightly/pool/main/q/qgis/qgis_3.13.0+git20200318+3a32b18289+28bionic_amd64.deb
http://qgis.org/ubuntu-nightly/pool/main/q/qgis/qgis_3.9.0+git20190809+7e16b6c9db+29cosmic_amd64.deb
http://qgis.org/ubuntu-nightly/pool/main/q/qgis/qgis_3.13.0+git20200223+13337b20cd+30disco_amd64.deb
http://qgis.org/ubuntu-nightly/pool/main/q/qgis/qgis_3.13.0+git20200315+a93db7d7c5+31eoan_amd64.deb
…
```
not built with the dependencies found on that particular version as one might reasonably expect since the apt line can contain that version tage? E.g. with the gdal and proj available on Disco Dingo (19.04) rather than on Eoan Ermine (19.10)?

Based on @nirvin's comment about "obsolete" versions of dependencies,  would I be having this problem if I were running 18.04 LTS Bionic Beaver because QGIS isn't built for gdal 2.2.3?

**Comment by CoryAlbrecht** [comment]
> Also, for that straight line at the bottom, if the original dataset only has two nodes to form the line, it'll only reproject those two nodes. You can use the density algorithm to add more points along lines.

@nirvn I know that, and it is addressed in the second paragraph of my original bug report where I mentions lines with only two points. I just didn't happen to use that particular line for the example screencaps.

**Comment by uclaros** [comment]
Each one of the packages is built with the dependencies found on the repositories for the particular version. I am not familiar with Ubuntu versions, but it seems that the only version that has gdal 3 and proj 6 is *focal*. That means that eoan, disco, bionic and older will *probably* have the same problem (if the problem is indeed caused by gdal 2 / proj 5).

**Comment by gioman** [comment]
@CoryAlbrecht there is no point at the moment to test/file a ticket about projections if you are using QGIS >= 3.10 and not using recent versions on GDAL (3) and Proj (6 and above). The "necessary" dependencies are available on Ubuntu 20.04 (and derivatives).

**Comment by uclaros** [comment]
Ubuntu 20.04 is marked as *future* release (I guess like Debian testing?).
Ubuntu should put gdal 3 and proj 6 on the *current* release, since it's what most casual users probably install thinking they have the latest version.

**Comment by gioman** [comment]
> Ubuntu 20.04 is marked as _future_ release

it is due in April, and you can already install the RC.

**Comment by gioman** [comment]
@CoryAlbrecht have you tested with recent gdal/proj dependencies?

**Comment by gioman** [comment]
It look fine with recent gdal/proj dependencies, closing.

**Comment by CoryAlbrecht** [comment]
> @CoryAlbrecht there is no point at the moment to test/file a ticket about projections if you are using QGIS >= 3.10 and not using recent versions on GDAL (3) and Proj (6 and above). The "necessary" dependencies are available on Ubuntu 20.04 (and derivatives).

So I rechecked this and it still happens on Ubuntu 20.04 with an updated QGIS, unlike what you say.

![image](https://user-images.githubusercontent.com/8172909/95608415-0f35fd00-0a2b-11eb-8d72-76bea8450d2b.png)


QGIS version | 3.15.0-Master | QGIS code revision | 9efa05b1e2
-- | -- | -- | --
Compiled against Qt | 5.12.8 | Running against Qt | 5.12.8
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.4 (Ubuntu 12.4-0ubuntu0.20.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Ubuntu 20.04.1 LTS | This copy of QGIS writes debugging output.
Active python plugins | CanadianWebServices; qgis2web; quick_map_services; Qgis2threejs; qgiscloud; postgisQueryBuilder; QuickOSM; OSMDownloader; OnlineRoutingMapper; processing; db_manager; MetaSearch

**Comment by gioman** [comment]
> unlike what you say

@CoryAlbrecht if you still see it is fine. I just meant that it didn't made sense to report it using a qgis build that didn't made use of recent dependencies.

**Comment by gioman** [comment]
@CoryAlbrecht can you attach a sample project + sample data?

**Comment by Pedro-Murteira** [comment]
@CoryAlbrecht Hello, I've tried to reproduce this but i'm being unable to, I'm not sure if I'm doing the exact steps tho. Is this still valid on more recent releases?
