### ISSUE TITLE
canvas shapes editing

### ISSUE THREAD

**Issue by dbmedina** [qgis/QGIS#34948]
Can no longer edit canvas arrow shape directly on the canvas in ver.3.10.3 for Windows (i.e., select and drag). Having to play with X, Y, width, and height in the properties box is very cumbersome.

**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by gioman** [comment]
@dbmedina is not of course a general issue. Please try with a new QGIS profile, no 3rd party plugins installed.

**Comment by dbmedina** [comment]
The only active plugins are the ones that came with it. The only difference is that I updated from version 3.4 to the latest long-term release of 3.10.

**Comment by gioman** [comment]
> The only active plugins are the ones that came with it. The only difference is that I updated from version 3.4 to the latest long-term release of 3.10.

@dbmedina regardless please try with a new QGIS profile.

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
