### ISSUE TITLE
Crash adding multi panel for view

### ISSUE THREAD

**Issue by Leoned** [qgis/QGIS#34949]
Crash ID: 4023bb83e927ddf71856046ec67e186ae1ede6bc

Stack Trace

QXmlStreamStringRef::~QXmlStreamStringRef :
QgsCoordinateReferenceSystem::~QgsCoordinateReferenceSystem qgscoordinatereferencesystem.cpp:249
QMetaType::destroy :
QTranslator::translate :
QVariant::~QVariant :
QHash::deleteNode2 qhash.h:541
QHashData::free_helper :
QgsExpressionContextScope::~QgsExpressionContextScope qgsexpressioncontext.cpp:76
qDeleteAll > qalgorithms.h:328
QgsExpressionContext::~QgsExpressionContext qgsexpressioncontext.cpp:283
QgsRenderContext::~QgsRenderContext :
QList::operator= qlist.h:159
QList::clear qlist.h:874
QgsMapRendererParallelJob::renderingFinished qgsmaprendererparalleljob.cpp:299
QMetaObject::activate :
QFutureWatcherBase::event :
![2020-03-09_16h39_01](https://user-images.githubusercontent.com/17074687/76259855-881a6f80-6224-11ea-915d-18b8965edd51.png)

QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QMenu::exec :
QToolButton::paintEvent :
QToolButton::showMenu :
QToolButton::~QToolButton :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::mousePressEvent :
QToolButton::mousePressEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :

QGIS Info
QGIS Version: 3.12.0-Bucure?ti
QGIS code revision: cd141490ec
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by Leoned** [comment]
ahother error.

Crash ID: f9d9d6b4d504a4a1df6528eef9b8b36e9806efa4


Stack Trace


QWidget::window :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
RtlAllocateHeap :
RtlAllocateHeap :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplicationPrivate::notify_helper :
QApplication::notify :
QMetaObject::activate :




QGIS Info
QGIS Version: 3.12.0-Bucure?ti
QGIS code revision: cd141490ec
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362
![2020-03-09_18h18_06](https://user-images.githubusercontent.com/17074687/76265375-5dcfae80-6232-11ea-94f1-55cb4604de7a.png)

**Comment by DelazJ** [comment]
@Leoned crash report is not enough. You'd need to provide also what you were doing when it happened, to help others replicate. And you should open different tickets if the issues are different. Thanks.

**Comment by Leoned** [comment]
I added multi panel for view independent imagen satelital with google earth engine.

**Comment by gioman** [comment]
> I added multi panel for view independent imagen satelital with google earth engine.

@Leoned add sample data/project and detailed steps to replicate, also try with a new QGIS profile, no 3rd party plugins installed.

**Comment by gioman** [comment]
@Leoned 

https://github.com/qgis/QGIS/issues/33661#issuecomment-596767442

**Comment by roya0045** [comment]
As stated, I'm sure this is a QT limit and nothing QGIS itself can fix.

**Comment by Leoned** [comment]
> As stated, I'm sure this is a QT limit and nothing QGIS itself can fix.

I think so
