### ISSUE TITLE
Heatmap not correct

### ISSUE THREAD

**Issue by Elithraldor** [qgis/QGIS#34958]
Noticed that the heatmap tool gives very different results from 3.10 to 3.12 - is it supposed to do that?

**Comment by gioman** [comment]
@Elithraldor please attach sample data (input and obtained results) and detailed infos about the parameters used in the operation. Also explain why the result obtained in 3.12 is wrong.

**Comment by Elithraldor** [comment]
Settings are radius 1500 and pixel size 100 - epsg25832.
QGIS 12:
![qgis12](https://user-images.githubusercontent.com/59510793/76398911-00487880-637e-11ea-88b2-d955bf895316.PNG)

QGIS10:
![qgis10](https://user-images.githubusercontent.com/59510793/76398924-050d2c80-637e-11ea-98fa-0182f8fabe8e.PNG)

V12 gives weird square-kinda result vs. 10 which gives the expected.

**Comment by gioman** [comment]
@Elithraldor please attach the point layer.

**Comment by kerkovits** [comment]
I confirm the bug. Please see the data attached.
[rendor.zip](https://github.com/qgis/QGIS/files/4437440/rendor.zip)
I used 500 m for distance and 5 m for pixel size.

**Comment by gioman** [comment]
Confirmed, the heatmap in 3.12 looks completely weird/wrong.

**Comment by roya0045** [comment]
I did the test, I don't get as much squaring but I got some high values in empty spot and still some arefacting 
![image](https://user-images.githubusercontent.com/12854129/79026638-785db600-7b57-11ea-978c-23321cb5753c.png)

I also tried three kernel settings:  quartic, uniform and epanechnikov. They yielded the same results

@alexbruy  @nyalldawson could the code tweaks in nov 2019 have broken the alg?

**Comment by gioman** [comment]
> I did the test, I don't get as much squaring but I got some high values in empty spot and still some arefacting

@roya0045 still if you compare with the results from the old LTR they are completely different/wrong.

**Comment by roya0045** [comment]
@gioman I fully agree that the values are wrong, just that they are not similar to the screenshot posted.

**Comment by nyalldawson** [comment]
@alexbruy I think we need to revert your change here -- I spent some time trying to fix this, and can't work out what's wrong. I suspect it's an issue in QgsRasterDataProvider::writeBlock, but I can't locate it. It seems like after writing a block to the data provider, any subsequent attempts to read back this data will return incorrect results.

**Comment by alexbruy** [comment]
@nyalldawson agree. I also spend some time looking into this and failed. Strange enough it works fine on some datasets and fail with others but I can't find pattern or what is causing this issue.
