### ISSUE TITLE
WFS connection requires authentication in QGIS 3.x

### ISSUE THREAD

**Issue by saberraz** [qgis/QGIS#34957]
A WFS connection I have, works fine in QGIS 2.18 without asking for authentication and connects anonymously.

But in QGIS 3.x it asks for username and password and fails to connect:

https://www.nottinghamshire.gov.uk/roadsearch/geoserver/wfsproxy?service=wfs&request=GetCapabilities

**Comment by gioman** [comment]
@saberraz if you force the WFS version to 1.0 it works.

**Comment by saberraz** [comment]
Indeed. It does not complain about username and password. But it shows a blank geometry for map and a NULL attribute table:
![image](https://user-images.githubusercontent.com/2649047/76326663-e73dba00-62e0-11ea-9815-a9e292b13366.png)

**Comment by gioman** [comment]
@saberraz here seems ok

![Screenshot_20200310_150932](https://user-images.githubusercontent.com/1951107/76326883-2d931900-62e1-11ea-9682-34adc07092c9.png)

![Screenshot_20200310_151016](https://user-images.githubusercontent.com/1951107/76326945-43084300-62e1-11ea-9648-03bbb11d19e0.png)

**Comment by saberraz** [comment]
OK then, it must be a local issue with my build. Thanks a lot for the hint!

**Comment by gioman** [comment]
@saberraz before closing you may want to double check, I was not on master here.

**Comment by gioman** [comment]
using 3.12

**Comment by saberraz** [comment]
Let me try on a nightly build on Windows

**Comment by saberraz** [comment]
OK, it looks like a local issue. Happy to close it.
