### ISSUE TITLE
error al iniciar la aplicacion despues de primera instalacion

### ISSUE THREAD

**Issue by macarrete** [qgis/QGIS#34967]
## User Feedback

Al iniciar la aplicacion despues de la primera instalacion muestra un error de carga del complemento MetaSearch y a continuación devuelve este error.

## Report Details

**Crash ID**: [67d946f7e16887bfd939dfe454d37ea8d66bc49c]('https://github.com/qgis/QGIS/search?q=67d946f7e16887bfd939dfe454d37ea8d66bc49c&type=Issues')

**Stack Trace**
<pre>
QSslKey::operator!= :
QSslKey::operator!= :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
QEventLoop::exec :
QThread::exec :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.3-A Coru�a
QGIS code revision: 0e1f846438
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by Saijin-Naib** [comment]
> Al iniciar la aplicacion despues de la primera instalacion muestra un error de carga del complemento MetaSearch y a continuación devuelve este error.

When starting the application after the first installation, a loading error is shown from the MetaSearch plugin, and then this error is returned.

**Comment by gioman** [comment]
@macarrete please re-file the ticket with subject and description in English, thanks for understanding.
