### ISSUE TITLE
Project crashes while exporting

### ISSUE THREAD

**Issue by pizzobarone** [qgis/QGIS#34965]
## User Feedback

The project crashed while exporting a temporary layer. The project crashes quite often. Maybe it has to do with too many atlas layouts?

## Report Details

**Crash ID**: [97857071bf2e7b39c88356c5432194df6fab79d5]('https://github.com/qgis/QGIS/search?q=97857071bf2e7b39c88356c5432194df6fab79d5&type=Issues')

**Stack Trace**
<pre>
QgsSingleBandColorDataRenderer::block qgssinglebandcolordatarenderer.cpp:90
QgsBrightnessContrastFilter::block qgsbrightnesscontrastfilter.cpp:118
QgsHueSaturationFilter::block qgshuesaturationfilter.cpp:123
QgsRasterResampleFilter::block qgsrasterresamplefilter.cpp:162
QgsRasterProjector::block qgsrasterprojector.cpp:810
QgsRasterIterator::readNextRasterPartInternal qgsrasteriterator.cpp:130
QgsRasterDrawer::draw qgsrasterdrawer.cpp:60
QgsRasterLayerRenderer::render qgsrasterlayerrenderer.cpp:266
QgsMapRendererCustomPainterJob::doRender qgsmaprenderercustompainterjob.cpp:312
QgsMapRendererCustomPainterJob::staticRender qgsmaprenderercustompainterjob.cpp:277
QtConcurrent::StoredFunctorCall1<void,void (__cdecl*)(QgsMapRendererParallelJob *),QgsMapRendererParallelJob *>::runFunctor qtconcurrentstoredfunctioncall.h:432
QtConcurrent::RunFunctionTask<void>::run qtconcurrentrunbase.h:144
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
__RtlUserThreadStart :
_RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.3-A Coru�a
QGIS code revision: 0e1f846438
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
@pizzobarone please try with a new QGIS profile, no 3rd party plugins installed, If the issue persist add the detailed steps, and data to allow us try replicate locally.

**Comment by roya0045** [comment]
Does it occur with specific data type? Here it seems that the raster renderer caused the crash.

**Comment by gioman** [comment]
Closing for lack of feedback.
