### ISSUE TITLE
Opening forms in a project with several relations causes core dumped

### ISSUE THREAD

**Issue by saberraz** [qgis/QGIS#34972]
Both using identify tool and opening attribute table causes core dumped.

See debugging info.
[open_attrib.log](https://github.com/qgis/QGIS/files/4313039/open_attrib.log)
[identify_tool_core_dump.txt](https://github.com/qgis/QGIS/files/4313040/identify_tool_core_dump.txt)

**Comment by gioman** [comment]
@saberraz QGIS version and OS?

**Comment by saberraz** [comment]
Sorry Gio! :) 
QGIS project was created in 3.12. I am trying to open the forms in master under Linux.

**Comment by gioman** [comment]
> Sorry Gio!

;)

**Comment by elpaso** [comment]
Hard to test without a project. Can you attach one?
