### ISSUE TITLE
Field Calculator causes crash

### ISSUE THREAD

**Issue by yourvick** [qgis/QGIS#34979]
## User Feedback

Whenever I try to open the field calculator, regardless of the project (new or different saved ones), the version (tried 3.10 and 3.12), OSGeo/local install, or whether I go through the main menu or the attribute table, QGIS crashes. I have tried restarting, uninstalling and reinstalling, as well as the different combinations outlined above.

## Report Details

**Crash ID**: [45de3b07fa848dc59218a0daffdbf46ef1580280]('https://github.com/qgis/QGIS/search?q=45de3b07fa848dc59218a0daffdbf46ef1580280&type=Issues')

**Stack Trace**
<pre>
QgsExpressionBuilderWidget::updateFunctionTree qgsexpressionbuilderwidget.cpp:666
QgsExpressionBuilderWidget::QgsExpressionBuilderWidget qgsexpressionbuilderwidget.cpp:127
Ui_QgsFieldCalculatorBase::setupUi ui_qgsfieldcalculatorbase.h:110
QgsFieldCalculator::QgsFieldCalculator qgsfieldcalculator.cpp:51
QgisApp::fieldCalculator qgisapp.cpp:7704
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1607
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.3-A Coru�a
QGIS code revision: 0e1f846438
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

QGIS version | 3.10.3-A Coruña | QGIS code revision | 0e1f846438
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Windows 10 (10.0)
Active python plugins | processing

**Comment by roya0045** [comment]
Did you try with a new profile?

**Comment by gioman** [comment]
> Did you try with a new profile?

@yourvick specifically a new QGIS profile (and leave it clean, no 3rd party plugins installed).

**Comment by yourvick** [comment]
A new, clean profile solved the problem - many thanks, I was pulling my hair out!
