### ISSUE TITLE
QGIS 3.10.3 Some GDAL functions not working. Example gdal_merge

### ISSUE THREAD

**Issue by mattenvsys** [qgis/QGIS#34976]
GDAL tools are not working via QGIS Desktop 3.10.3 on Windows 10 using the Python Module syntax.

This is similar to issues [33386](https://github.com/qgis/QGIS/issues/33386) and [34001](https://github.com/qgis/QGIS/issues/34001). That issue has been closed but it seems to have returned.

For instance GDAL edit and GDAL merge do not work:

```
C:\PROGRA~1\QGIS3~1.10\bin\python3.exe: No module named gdal_merge
C:\PROGRA~1\QGIS3~1.10\bin\python3.exe: No module named gdal_edit
```

The command syntax is as follows:
```
python3 -m gdal_edit -a_srs EPSG:27700 D:/qgis/test.tif
```

These tools work correctly on Linux but not on Windows (they are called in a different way)

Steps to reproduce:
Example 1) Attempt to use the Merge command under Raster > Miscellaneous, on any input raster

![Merge](https://user-images.githubusercontent.com/15214610/76329151-1c97d700-62e4-11ea-90bc-ab59a49174fd.PNG)

Example 2) Attempt to use the Assign Projection command under Raster > Projections, on any input raster

![Edit](https://user-images.githubusercontent.com/15214610/76329451-80220480-62e4-11ea-882d-971071c69eac.PNG)

Installation executable used:
QGIS-OSGeo4W-3.10.3-2-Setup-x86_64.exe

OS Info:
Windows 10 Pro
Version 1903
OS Build 18362.693

QGIS About Info:

QGIS version
3.10.3-A Coruña
QGIS code revision
0e1f846438
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.1
Running against PROJ
Rel. 6.3.1, February 10th, 2020
OS Version
Windows 10 (10.0)
Active python plugins
envsysCoastal3; 
envsysSend2google_earth; 
GroupStats; 
mapswipetool_plugin; 
mmqgis; 
OSTranslatorII; 
pointsamplingtool; 
qdraw; 
qfieldsync; 
Qgis2threejs; 
SemiAutomaticClassificationPlugin; 
splitmultipart; 
db_manager; 
MetaSearch; 
processing

**Comment by roya0045** [comment]
Are you using the plugin or the processing algs?

**Comment by gioman** [comment]
> GDAL tools are not working via QGIS Desktop 3.10.3 on Windows 10 using the Python Module syntax.

@mattenvsys cannot confirm here on 3.10.3 installed with osgeo4w. Check if it makes any difference compared to the standalone installer.

**Comment by mattenvsys** [comment]
@roya0045 The projections are the same for the two rasters. Just selecting a single raster gives the same error message that the module can't be found

We are running a Windows domain in the office. The [standalone installer](https://qgis.org/downloads/QGIS-OSGeo4W-3.10.3-3-Setup-x86_64.exe) was pushed silently via the command line by our IT manager (this was all the detail I was able to extract from him)

Command line string used:

QGIS-OSGeo4W-3.10.3-2-Setup-x86_64.exe /S

@gioman those two operations work using 3.10.3 via osgeo installer.

**Comment by gioman** [comment]
> @gioman those two operations work using 3.10.3 via osgeo installer.

@mattenvsys just download and tested 3.10.3 with the standalone installer: GDAL tools that are python scripts do work as expected. There is probably something wrong with your installations.

**Comment by mattenvsys** [comment]
hi @gioman ,

Just noticed the standalone installer has been replaced with QGIS-OSGeo4W-3.10.3-**3**-Setup-x86_64.exe

Initially used installer QGIS-OSGeo4W-3.10.3-**2**-Setup-x86_64.exe 

However, the gdal tools listed above still don't work using the version 3 installer on my system

**Comment by gioman** [comment]
> However, the gdal tools listed above still don't work using the version 3 installer on my system

@mattenvsys please try on a completely clean system, like a virtual machine (you can download the Windows ISO from MS site).

**Comment by mattenvsys** [comment]
hi @gioman the tools work in a completely fresh Windows environment

**Comment by gioman** [comment]
> hi @gioman the tools work in a completely fresh Windows environment

@mattenvsys this suggest a local issue on the other machine, and this should be closed.
