### ISSUE TITLE
Exporting labels as dxf

### ISSUE THREAD

**Issue by zippy84** [qgis/QGIS#34973]
I think this a general question about the Python API.

I want to export labels as dxf. This is my code:

```Python
dxf = QgsDxfExport()
dxf.addLayers([dxf.DxfLayer(iface.activeLayer())])
dxf.setLayerTitleAsName(True)
dxf.setFlags(QgsDxfExport.Flag.FlagNoMText)
f = QFile('/home/rr/labels.dxf')
f.open(QIODevice.ReadWrite)
dxf.writeToFile(f, 'ansi_1252')
f.close()
```
The labels are visible in the GUI, but not in the dxf. What I'm doing wrong?

Is `dxf.setFlags(QgsDxfExport.Flag.FlagNoMText)` right?

**Comment by gioman** [comment]
Please ask questions in the developers/users mailing lists, the QGIS IRC channel or gis.stackexchange. Thanks!

**Comment by zippy84** [comment]
Please delete this issue/question.
