### ISSUE TITLE
Rectangles, ovals, diamonds (variable) tool missing in QGIS 3.12

### ISSUE THREAD

**Issue by joeyfranck56** [qgis/QGIS#34981]
In previous versions of QGIS there were 2 tools, "Rectangles, ovals, diamonds(fixed)" and "Rectangles, ovals, diamonds(variable)".  In QGIS 3.12 there is only 1 tool, "Rectangles, ovals, diamonds" which is the same tool as the fixed tool.  Was this tool re-named or removed?  

For now I can install an older version of QGIS, but I hope this tool comes back in future releases.

**Comment by nyalldawson** [comment]
They have been combined into a single tool. Use the "data defined" value buttons to the right of the different parameters in order to take them from fields or expressions.
