### ISSUE TITLE
Uninstalling the standalone installer leaves cmake directory 

### ISSUE THREAD

**Issue by haubourg** [qgis/QGIS#34980]
**Describe the bug**

When uninstalling QGIS on Windows (10 here), the `cmake` directories are left unremoved.

**How to Reproduce**

<!-- Steps, sample datasets and qgis project file to reproduce the behavior. Screencasts or screenshots welcome

1.Install a standalone installer (tested with 3.10 and 3.12)
2. uninstall
3. check the QGIS install directory. It is still there, with cmake dir into it

On one install, I also found a `apps/Python37/lib/site-package` left next to the Cmake dir. 

@jef-n does that ring any bell to you ?

**Comment by AlisterH** [comment]
The cmake directory doesn't seem to be left by 3.20.x and 3.22.x, but was for 3.16.x

There is other stuff that the newer versions fail to remove though:
![image](https://user-images.githubusercontent.com/714600/151072144-9d7913d5-44fd-4a4e-b7d5-94d9057529b5.png)

**Comment by alexbruy** [comment]
Is this an issue with the new installers?

**Comment by AlisterH** [comment]
Please define "new".
This is what's left behind after uninstalling 3.24.0:
![image](https://user-images.githubusercontent.com/714600/168178063-3c6035c5-c9de-44d5-8cef-b80a43f90d33.png)
