### ISSUE TITLE
[Mesh] Disabling the "enable 3D renderer" should not reset the user settings in the dialog

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#34986]
1. Add a mesh layer
2. Open layer properties dialog
3. Enable the 3d view dialog
4. Check the "Enable 3d renderer" button and modify some settings, eg set the vertical scale from 1 to 2
5. Apply (or OK, reopen the layer properties to do it the hard way)
6. Disable the "Enable 3D renderer" setting, OK.
7. Reopen: you get #34985 but you'll notice that settings you made in the dialog are wiped, reset to initial values of the dialog (ie, our vertical scale displays 1 and not 2).

Disabling the box can be a temporary action and we shouldn't reset the configuration the user made; these are supposed to be disabled anyways so shouldn't harm anything if left customized (and resetting is not consistent with the other parts of the properties dialog)

**Comment by saberraz** [comment]
Thanks a lot @DelazJ for your review, much appreciated.
