### ISSUE TITLE
Cannot choose Vn-2000 Projected CRS from CRS Selector in QGIS

### ISSUE THREAD

**Issue by thangqd** [qgis/QGIS#34984]
Dear QGIS Developers!
Recently, based on my sugguession, EPSG has updated the database which adding dozens of Local Projected CRS for provinces in Vietnam

In QGIS (3.10, 3.12), I noticed that QGIS has updeated Proj library so that it could detect Local Projected CRS of Vietnam with EPSG code (screenshot attached) 
![a](https://user-images.githubusercontent.com/1776420/76375777-37685b00-6379-11ea-8ecf-05262728e1e8.PNG)

Unfortunately, in CRS Selector, Vietnamese users cannot choose appropriate local Projected CRS, and we also cannot add custom projection due to some syntax erros (Proj, WKT) - which worked fine before! 
![image](https://user-images.githubusercontent.com/1776420/76376023-d5f4bc00-6379-11ea-8457-9542429a412a.png)

This is a headache of Vietnamese users for years. So, on behalf of QGIS community in Vietnam, I would like to sugguest that users can choose all VN-2000 CRS in QGIS CRS Selector
Thanks and best regards!

**Comment by gioman** [comment]
> Unfortunately, in CRS Selector, Vietnamese users cannot choose appropriate local Projected CRS, and we also cannot add custom projection due to some syntax erros (Proj, WKT) - which worked fine before!
> ![image](https://user-images.githubusercontent.com/1776420/76376023-d5f4bc00-6379-11ea-8457-9542429a412a.png)

@thangqd it this the "before" or "after" screenshot? if is the "after" then the CRSs are right there in the bottom part of that dialog. I just tested on 3.10.3 and above on Windows, they show up.

**Comment by DelazJ** [comment]
@gioman probably because the epsg:9210 (from the first screenshot) is not in the filter results.
However, this is what I get from my osgeo4w install of 3.10.3 (gdal 3.0.4, proj 6.3.1)
![image](https://user-images.githubusercontent.com/7983394/76412196-802d0d80-6393-11ea-979f-0334a6001d38.png)

**Comment by gioman** [comment]
> this is what I get from my osgeo4w install of 3.10.3 (gdal 3.0.4, proj 6.3.1) - a bit more projections than you have

same here.

**Comment by thangqd** [comment]
Thanks all! It works fine on QGIS 3.12 (OSGeo4W Network Installer)
