### ISSUE TITLE
QGIS Composer crash when exporting image

### ISSUE THREAD

**Issue by Mickeler** [qgis/QGIS#34991]
QGIS Composer will crash when try to export image (tif, resolution 508 dpi). Is that memory issue?

Crash ID: bfc811e107b3e0e9c6ed5974d83fcebc51e299d2

Stack Trace

memcpy_repmovs memcpy.asm:115
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QRasterPaintEngine::rasterBuffer :
QRasterPaintEngine::rasterBuffer :
QRasterPaintEngine::fill :
QPaintEngineEx::draw :
QPaintEngineEx::drawPath :
QgsFillSymbolLayer::_renderPolygon qgssymbollayer.cpp:753
QgsSimpleFillSymbolLayer::renderPolygon qgsfillsymbollayer.cpp:289
QgsFillSymbol::renderPolygonUsingLayer qgssymbol.cpp:2097
QgsFillSymbol::renderPolygon qgssymbol.cpp:2052
QgsLayoutItemPage::draw qgslayoutitempage.cpp:286
QgsLayoutItem::paint qgslayoutitem.cpp:411
QGraphicsScene::dragMoveEvent :
QGraphicsItem::dragMoveEvent :
QGraphicsEffectSource::draw :
QgsLayoutEffect::draw qgslayouteffect.cpp:33
QGraphicsScene::drawItems :
QGraphicsScene::drawItems :
QGraphicsScene::render :
QgsLayoutExporter::renderRegion qgslayoutexporter.cpp:261
QgsLayoutExporter::renderRegionToImage qgslayoutexporter.cpp:300
QgsLayoutExporter::renderPageToImage qgslayoutexporter.cpp:207
QgsLayoutExporter::createImage qgslayoutexporter.cpp:1922
QgsLayoutExporter::exportToImage qgslayoutexporter.cpp:411
QgsLayoutDesignerDialog::exportToRaster qgslayoutdesignerdialog.cpp:2078
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1609
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.12.0-Bucure?ti
QGIS code revision: cd141490ec
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by gioman** [comment]
@Mickeler can you attach a project+layout+data we can test?

**Comment by nyalldawson** [comment]
This is a bug in qt -- already fixed upstream
