### ISSUE TITLE
Processing - the result component forgets its location

### ISSUE THREAD

**Issue by magnusnil** [qgis/QGIS#34994]
Describe the bug
In a processing model, the green model component for output forgets its location when hitting OK in the algorithm that creates it.

How to Reproduce
1. Add input data in a processing model
2. Add an algorithm and configure it. Pick a name for the result.
3. Click OK
4. Move the green result box to a new location.
5. Go back to the algorithm and hit OK.
6. The green result box now moves back to its default location, which is a bit annoying if I already have positioned it.

QGIS and OS versions
Tested in QGIS 3.4.11 and 3.12.0 on Windows 10, 64 bit.

**Comment by gioman** [comment]
@magnusnil there have been a lot of work lately in the modeller. Please try again on master.

**Comment by magnusnil** [comment]
OK, I´ll do that.

**Comment by nyalldawson** [comment]
This is already fixed on master -- I fixed it a couple of days ago

**Comment by magnusnil** [comment]
Something tells me that the next release of QGIS is going to be great.
