### ISSUE TITLE
Support for opening processing model files using drag and drop

### ISSUE THREAD

**Issue by magnusnil** [qgis/QGIS#34990]
Feature description
When a user drops a processing model (.model3) in QGIS (the main window or a processing model window), the model should open. That would improve usability a bit.

**Comment by DelazJ** [comment]
Is it not what https://github.com/qgis/QGIS/pull/5200 does? Or do I misunderstand?

**Comment by magnusnil** [comment]
Ah, that sounds very similar, I didn´t find that one when searching. Is the intention to execute or just open the model in #5200? I would prefer to just open it.

**Comment by DelazJ** [comment]
#5200 is implemented (3.0) so if you drag and drop a model, you should get some behavior (no model around to test right now)

**Comment by MrChebur** [comment]
@magnusnil Perhaps this topic can be closed?

**Comment by MrChebur** [comment]
@DelazJ @magnusnil Tested it - this feature is available. You can close the question.
