### ISSUE TITLE
Buffering closed line produces wrong results

### ISSUE THREAD

**Issue by uclaros** [qgis/QGIS#34998]
**Describe the bug**
Buffering a closed line, under circumstances, produces a filled polygon and not a donut with a hole.
I am not sure what the circumstances are, but I noticed it while buffering a large dataset of closed lines, produced by clean polygons via *polygons to lines*. A few of my polygons appeared without a hole, so I picked one and simplified it vertices and I came to the following simple fail case:

**How to Reproduce**
Running the following on python console produces a polygon without a hole while it should produce a polygon with a hole.
```QgsGeometry().fromWkt('LineString (278601.0234000000054948 4295292.71929999999701977, 278598.71919999999227002 4295290.49340000003576279, 278589.06283691781572998 4295303.48101469129323959, 278605.49300000001676381 4295297.03689999971538782, 278601.0234000000054948 4295292.71929999999701977)').buffer(1,0).asWkt()```

**QGIS and OS versions**
8addbde0a5 on Debian
GEOS 3.8.0-CAPI-1.13.1

**Additional context**
This could be a GEOS bug? Could someone test it on other GEOS versions?

**Comment by gioman** [comment]
@uclaros just a hunch, nothing more: maybe the CRS is not set so it defaults to 4326 and then you are doing a 1 degree buffer (that is probably enough to fill all the area inside your closed line).

**Comment by uclaros** [comment]
There's something about the three nodes that are almost aligned. Moving any of the three causes the buffer to give correct results...

**Comment by jgrocha** [comment]
@uclaros I was not able to reproduce on current master.

The code I used to test:
```python
pointlayer = QgsVectorLayer("LineString?crs=EPSG:3857", "line", "memory")
line = QgsFeature()
line.setGeometry(QgsGeometry().fromWkt('LineString (278601.0234000000054948 4295292.71929999999701977, 278598.71919999999227002 4295290.49340000003576279, 278589.06283691781572998 4295303.48101469129323959, 278605.49300000001676381 4295297.03689999971538782, 278601.0234000000054948 4295292.71929999999701977)'))
pointlayer.dataProvider().addFeatures([line])
QgsProject.instance().addMapLayer(pointlayer, True)

polygonlayer = QgsVectorLayer("Polygon?crs=EPSG:3857", "buffer", "memory")
buffer = QgsFeature()
buffer.setGeometry(line.geometry().buffer(1, 0))
polygonlayer.dataProvider().addFeatures([buffer])
QgsProject.instance().addMapLayer(polygonlayer, True)
```
![Buffer from geometry](https://user-images.githubusercontent.com/163681/76692053-f5753880-6648-11ea-96ee-960d25a7a457.png)

Can you check this minimal example? Or can you share the code not working as expected?

**Comment by jgrocha** [comment]
> There's something about the three nodes that are almost aligned. Moving any of the three causes the buffer to give correct results...

Same here.

**Comment by jgrocha** [comment]
### Same result using Postgis

```sql
CREATE TABLE public.tpoly (
	id serial NOT NULL,
	geom geometry(POLYGON, 3857) not null,
	CONSTRAINT tpoly_pkey PRIMARY KEY (id)
);

CREATE TABLE public.tline (
	id serial NOT NULL,
	geom geometry(LINESTRING, 3857) not null,
	CONSTRAINT tline_pkey PRIMARY KEY (id)
);

insert into public.tline (geom)
values (ST_GeomFromText('LineString (278601.0234000000054948 4295292.71929999999701977, 278598.71919999999227002 4295290.49340000003576279, 278589.06283691781572998 4295303.48101469129323959, 278605.49300000001676381 4295297.03689999971538782, 278601.0234000000054948 4295292.71929999999701977)',3857));

insert into public.tpoly (geom)
select st_buffer(geom,1, 'quad_segs=0') from public.tline where id = 1;
```
 
![Buffer from geometry postgis](https://user-images.githubusercontent.com/163681/76692570-64a25b00-6650-11ea-82d4-e550af96ec3c.png)

```sql
select postgis_full_version();
POSTGIS="2.5.1 r17027" [EXTENSION] PGSQL="100" GEOS="3.7.1-CAPI-1.11.1 27a5e771" PROJ="Rel. 5.2.0, September 15th, 2018" GDAL="GDAL 2.4.2, released 2019/06/28" LIBXML="2.9.4" LIBJSON="0.12.1" LIBPROTOBUF="1.2.1" RASTER
```

**Comment by nyalldawson** [comment]
Could you file this on the geos issue tracker? That's where the bug lies

**Comment by uclaros** [comment]
Reported to geos issue tracker https://trac.osgeo.org/geos/ticket/1022

**Comment by jgrocha** [comment]
### Same problem on Postgis 3.1

```
POSTGIS="3.1.0dev 3e1ea07" [EXTENSION] PGSQL="120" GEOS="3.8.0-CAPI-1.13.1 " PROJ="7.0.0" LIBXML="2.9.4" LIBJSON="0.13.1"
```

![Buffer from geometry postgis 3 1](https://user-images.githubusercontent.com/163681/76693225-8227f280-6659-11ea-8f70-851db16f9062.png)

**Comment by nyalldawson** [comment]
Thanks!

**Comment by uclaros** [comment]
FYI it's twice upstream, it's in JTS 1.14 too!
