### ISSUE TITLE
[Mesh] Scrolling on styling panel becomes unresponsive

### ISSUE THREAD

**Issue by saberraz** [qgis/QGIS#35001]
Finally I managed to reproduce it persistently:
Open a mesh layer with lots of quantities
Go to the general settings (where quantities are listed)
Scroll to the very bottom of the list using the mouse wheel
Now, try to scroll UP using the mouse...it is blocked and you have to use the scroll bar by dragging it

**Comment by MrChebur** [comment]
Confirming this bug in QGIS version 3.14.1-Pi, when scrolling with the mouse wheel, when the scrollbar reaches the top or bottom position, it is disabled. Here is the video:
![Mouse wheel do not work](https://user-images.githubusercontent.com/20655102/89643177-a6b58d00-d8ce-11ea-8127-36f1eb44146a.gif)

**Comment by alexbruy** [comment]
No sure this is Processing issue.

**Comment by DelazJ** [comment]
@nyalldawson would #46958 (or any recent tweaks you did to scrolling) fix this?

**Comment by nyalldawson** [comment]
Yes this is fixed now
