### ISSUE TITLE
Improved Create Options when creating GTIFF using GDAL Translate and JPEG Compression

### ISSUE THREAD

**Issue by angusmcb** [qgis/QGIS#35002]
**Feature description.**

When creating a GTiff using GDAL Translate from processing or 'Export as...'   there is the option to select JPEG Compression. This sets create create options COMPRESS = JPEG and QUALITY = 75. 

According to the below link (which seems to work well for me) it would be worth also including the create options PHOTOMETRIC=YCBCR  and TILED=YES when jpeg compression is selected.

[http://blog.cleverelephant.ca/2015/02/geotiff-compression-for-dummies.html](http://blog.cleverelephant.ca/2015/02/geotiff-compression-for-dummies.html)

If this is a good idea, then it looks like it would be a very easy change in:
GIS/src/gui/qgsrasterformatsaveoptionswidget.cpp

**Comment by angusmcb** [comment]
Strangely enough, the YCBCR option is already used if JPEG compression is selected when creating pyramids.

**Comment by rouault** [comment]
Tiling is completely orthogonal to JPEG compression. But PHOTOMETRIC=YCBCR indeed makes sense

**Comment by angusmcb** [comment]
I am not an expert on this but have done a bit more research. From what I can see tiling is at least somewhat related (in theory at least)

Form the [Tiff specificaition](https://www.itu.int/itudoc/itu-t/com16/tiff-fx/docs/tiff6.pdf):

Section 15:

> For low-resolution to medium-resolution images, the standard TIFF method of breaking the image into strips is adequate. However high-resolution images can be accessed more efficiently—and compression tends to work better—if the image is broken into roughly square tiles instead of horizontally-wide but vertically-narrow strips.

and

> The advantages of padding an image to the tile boundaries are that implementations can be simpler and faster and that it is more compatible with tile-oriented compression schemes such as JPEG. See Section 22

Section 22:

> Although JPEG codes consecutive image blocks in a single contiguousbitstream, it is extremely useful to employ the concept of tiles in an image. TheTIFF Tiles section defines some new fields for tiles. These fields should be stored in place of the older fields for strips. The concept of tiling an image in both dimensions is important because JPEG hardware may be limited in the size of each block that is handled

**Comment by angusmcb** [comment]
@rouault  I just tried it in practice with some random satellite imagery. You are right - it makes no difference whatsoever whether or not it is tiled.

**Comment by rouault** [comment]
What you quote from the TIFF spec is not false: the recommendation of tiling is generally good for sufficiently big images, especially when compression is used
