### ISSUE TITLE
3D tab in vector properties now appears at the bottom of the list

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#35010]
and is filled with properties, even if set to "no symbols" - I'm not sure this tab deserves to be at the end of the properties dialog.
![image](https://user-images.githubusercontent.com/7983394/76492063-8cff3f00-642f-11ea-999a-7e7d55c0964e.png)
master

**Comment by 3nids** [comment]
@manisandro is this related to the recent changes from #33833
