### ISSUE TITLE
3D tab in vector properties dialog "resets" settings

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#35012]
Open the vector layer properties --> 3D
select single symbol and do some changes
Press OK 
Reopen the dialog, move to the 3D tab: the menu is reset to "no symbols". Afaics the values previously entered are kept if you switch to "single symbol" so probably a matter of the drop down menu not synced

**Comment by nyalldawson** [comment]
Ping @manisandro

**Comment by alexbruy** [comment]
Seems already fixed.

**Comment by DelazJ** [comment]
I can not reproduce indeed.
