### ISSUE TITLE
Subgroups Legend

### ISSUE THREAD

**Issue by RemyBouillaguet** [qgis/QGIS#35024]
Describe the bug
In QGIS 3.10, it is no longer possible to delete the text of a subgroup in the legend and see this empty text

QGIS and OS versions
3.10

**Comment by gioman** [comment]
@RemyBouillaguet can you post a screencast to allow understand better what do you mean? Thanks.

**Comment by RemyBouillaguet** [comment]
![bug_legend_qgis](https://user-images.githubusercontent.com/62098334/76523739-33b40180-6469-11ea-976d-f79d86925495.png)

In this example, I want no text for the layer "prescription_surf", so I delete the text. Result, the text is still in the legend?

**Comment by roya0045** [comment]
Just right click on it and select hidden.

**Comment by roya0045** [comment]
Or use a space..

**Comment by RemyBouillaguet** [comment]
Thank you!
