### ISSUE TITLE
2 vector menus

### ISSUE THREAD

**Issue by sigmoe** [qgis/QGIS#35028]
**Describe the bug**

In the MenuBar, there are 2 menus 'Vector'. The first one, placed after 'Extension' menu (correct place) contains only two functions. The second 'Vector' menu placed at the end of the menus, contains all the processing functions.

**How to Reproduce**    

**QGIS and OS versions**

Version de QGIS
3.10.3-A Coruña
Révision du code
0e1f846438
Compilé avec Qt
5.11.2
Utilisant Qt
5.11.2
Compilé avec GDAL/OGR
3.0.4
Utilisé avec GDAL/OGR
3.0.4
Compilé avec GEOS
3.8.0-CAPI-1.13.1
Utilisé avec GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
Version du client PostgreSQL
11.5
Version de SpatiaLite
4.3.0
Version de QWT
6.1.3
Version de QScintilla2
2.10.8
Compilé avec PROJ
6.3.1
Fonctionne avec PROJ
Rel. 6.3.1, February 10th, 2020
OS Version
Windows 10 (10.0)
Extensions Python actives
ClipMultipleLayers; 
gban; 
GeofoncierEditeurRFU; 
gml_application_schema_toolbox; 
loadthemall; 
localiserparcelle; 
mmqgis; 
OSMDownloader; 
qgis2web; 
QgisLayerBoardPlugin-master; 
qProf; 
quick_map_services; 
refFunctions; 
SgmCdmTransfo; 
SgmComparePmAvvApv; 
SgmDxfImportPro; 
SgmExpressFunctions; 
SgmLinesToPoints; 
SgmVertex2NodeByAtt; 
StreetView; 
db_manager; 
MetaSearch; 
processing

**Additional context**

French version

**Comment by DelazJ** [comment]
@sigmoe can you go to Settings --> Options --> Processing, press the "reset to default" button (on menus) and restart QGIS?

**Comment by sigmoe** [comment]
@gioman ok, the resetting works, but then if I open a QGIS 3.4, the problem appears in QGIS 3.4. I think there's a kind of settings incompatibilty concerning the menus between QGIS 3.4 and QGIS 3.10.
