### ISSUE TITLE
Raster 

### ISSUE THREAD

**Issue by ssomani10** [qgis/QGIS#35036]
I am having difficulty in trying to merge raster files in QGIS.  I have tried the processing toolbox and the dropdown menu where after I select the files, the

I tried a clean install of QGIS 3.12 and when I try and click on raster-->Miscellaneous --> Merge or Build Virtual Raster, and the text box opens.    I added the files, via directory, add file button, or toggle the selection.  Once I hit okay, the box completely closes and I am back in the main screen.  I added a GIF to clarify any questions.

![Virtual-Raster](https://user-images.githubusercontent.com/8172915/76543686-3f99c680-645d-11ea-9676-cd8333be2adb.gif)

**Comment by gioman** [comment]
@ssomani10 subject not meaningful and description completely missing.

**Comment by ssomani10** [comment]
Sorry, I clicked on okay by accident and it got posted.  Updated the text, title and added a GIF to demonstrate the issue I was facing.

**Comment by gioman** [comment]
>  Once I hit okay, the box completely closes and I am back in the main screen

@ssomani10 it does not close, it goes behind the main QGIS window. Is a known macOS versoin issue, that has been already reported in other tickets.

**Comment by ssomani10** [comment]
Thanks.  I thought it was a Catlina issue and when I searched that it was not showing up.

Shaffiq

________________________________
