### ISSUE TITLE
ArcGisMapServer problem !!

### ISSUE THREAD

**Issue by mahmoud2728** [qgis/QGIS#35041]
I'm having this problem when I zoom in,
The map is disappearing !!
Note that on the Google Satellite link it does not disappear when zoomed in and the map remains visible!

![Screenshot 2020-03-12 22 26 31](https://user-images.githubusercontent.com/61476338/76564403-1440c700-64b1-11ea-81e2-a1711db4d895.png)
![Screenshot 2020-03-12 22 26 19](https://user-images.githubusercontent.com/61476338/76564408-16a32100-64b1-11ea-961a-b4448522b718.png)

**Comment by roya0045** [comment]
Probably a limitation set by the source itself rather than a qgis issue, if I were to guess.

**Comment by gioman** [comment]
> Probably a limitation set by the source itself rather than a qgis issue, if I were to guess.

@mahmoud2728 I agree with @roya0045 not all such services serve maps at all scales. Several time they serve maps only within some range of scales.

I think this should be closed.

**Comment by nyalldawson** [comment]
Definitely not a qgis issue - the server doesn't have that information available
