### ISSUE TITLE
crash when opening filters in attribute table

### ISSUE THREAD

**Issue by beerockxs** [qgis/QGIS#35054]
## User Feedback

i tried to see what kind of filters where set in the attribute  table of a feature class

## Report Details

**Crash ID**: [0aa7edb6c7853dab339ec97637da83faf315ddb2]('https://github.com/qgis/QGIS/search?q=0aa7edb6c7853dab339ec97637da83faf315ddb2&type=Issues')

**Stack Trace**
<pre>
QgsExpressionPrivate::QgsExpressionPrivate qgsexpressionprivate.h:44
QgsExpression::prepare qgsexpression.cpp:377
QgsFieldExpressionValuesGatherer::run qgsfeaturefiltermodel_p.h:58
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.2-A Coru�a
QGIS code revision: d4cd3cfe5a
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.3
Running against GDAL: 3.0.3

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by gioman** [comment]
@beerockxs please try with a new QGIS profile, no 3rd party plugins installed.

**Comment by gioman** [comment]
Closing for lack of feedback.
