### ISSUE TITLE
QGIS 3.12  Error ?    when working with a duplicated layer

### ISSUE THREAD

**Issue by vfzaitsev54** [qgis/QGIS#35057]
I am writing from Ukraine. Error ?   . In version 3.12, I duplicate the "father" layer to the "son" layer and start working in the "son" layer. But all changes to the attribute table in the "son" layer are repeated in the "fathe" layer.  Maybe I’m doing something wrong?

**Comment by roya0045** [comment]
@vfzaitsev54 not a bug, duplicating only make a new layer in the legend, the data source is the same.
