### ISSUE TITLE
Spatialite column with AUTOINCREMENT block with forms

### ISSUE THREAD

**Issue by EnFiore** [qgis/QGIS#35062]
the issue is the same as decribed in [Spatialite column with AUTOINCREMENT block with forms #27762](https://github.com/qgis/QGIS/issues/27762).  
I have noticed the same issue in QGIS 3.10.3.
If Spatialite is created by a geojson or by command 'new spatialite' the issue is the same as described in #27762. 
If Spatialite DB is created starting by shapefile the issue not happens.

**Comment by gioman** [comment]
@EnFiore please post step by step operations to follow to replicate, and/or attach a sample project with data. Thanks!

**Comment by EnFiore** [comment]
You can reproduce the issue by this steps:
1. Creating a new spatialite file by QGIS tool denominate 'New Layer Spatialite' and set layer name and geometry type, I have choose polygon. 
2. Setting a new text field, naming it as code, it is allowed to create a autoincrement field. 
3. Click ok.
4. Starting editing and drawing a new geometry and set a code.
5. To save new geometry. 

QGIS writes a message that notices you that is not possible modify layer.
But if you add a value in pkuid field the geometry will be save.

the same issue occurs if you try to generate spatialite starting from a Json.

I Attache db example with the issue.
[db_prova.zip](https://github.com/qgis/QGIS/files/4337326/db_prova.zip)

**Comment by gioman** [comment]
> I Attache db example with the issue.
> [db_prova.zip](https://github.com/qgis/QGIS/files/4337326/db_prova.zip)

@EnFiore zip file is empty.

**Comment by gioman** [comment]
@EnFiore I have tested on master and it works ok. I think that there may have some recent fix that will be available in the next round of point releases. Please test it.

**Comment by EnFiore** [comment]
I am working in windows 10 and 7. 
I have noticed that the issue occures only when the db is created or if I reload layer from QGIS browser by Spatialite connections.
The issue doesn't occure if I navigate in file system, always by QGIS browser, and load layer from the complete path. In this case I can add new features.

Can be that the problem is related to system permissions?


Complete error is:
> Errori: ERROR: 1 feature(s) not added.
> Errori della sorgente dati:
>       Errore di SQLite: causa sconosciuta
>     SQL: INSERT INTO "zone"("geometry",,"codice") VALUES (GeomFromWKB(?, 4326),,?)

[db_prova.zip](https://github.com/qgis/QGIS/files/4347855/db_prova.zip)

**Comment by elpaso** [comment]
This error was fixed a few weeks ago.

**Comment by mcrevato** [comment]
I have some problem on 3.12.0 Bucuresti. 
This issue is new and old geometries of some layer are OK (I forgot how many QGis upgrades occurs from last correct geometry insert).
But why the column name (ID before TIP field in my case), is empty ?
(ID is autoincrement)
  Errori della sorgente dati:
      Errore di SQLite: causa sconosciuta
    SQL: INSERT INTO "poti"("geom",,"TIP","STANJE","ZADNIPOSEG","DATUMZADJIPOSEG","OPOMBE","OPIS","LAST") VALUES (GeomFromWKB(?, 32633),,?,?,?,?,?,?,?).
Is possible convert entire sqlite db in geopackage without collateral issues ?
regards
Mario
