### ISSUE TITLE
QGIS Server GetPrint does not respect position reference point for legend item.

### ISSUE THREAD

**Issue by rldhont** [qgis/QGIS#35063]
**Describe the bug**
In a layout, if the legend item has a position reference point at the bottom right and _Filter Legend by Map Content_ is checked: the position is not respected in the QGIS Server GetPrint request output.

**How to Reproduce**

1. Go to Layout Manager
2. Create an Empty Layout
3. Add a Map Item
4. Add a Legend item
5. Configure the Legend item with _Position > Reference point > bottom right_ and check _Filter Legend by Map Content_
6. Do a GetPrint request with not all layers
7. The Legend is drawn at the upper left position refrence point and not at the bottom right

**QGIS and OS versions**

QGIS Server: 3.4 and upper
OS: linux

**Additional context**

PR: [[Tests][Server] WMS GetPrint a layout with legend anchored bottom right](https://github.com/qgis/QGIS/pull/35060)

Expected
![WMS_GetPrint_Legend_Bottomright_expected](https://user-images.githubusercontent.com/1575538/76946284-1a490480-6904-11ea-9fc9-8375bb00e1e5.png)

Rendered 
![WMS_GetPrint_Legend_Bottomright_rendered](https://user-images.githubusercontent.com/1575538/76946334-292fb700-6904-11ea-9a65-af800b9abff8.png)

**Comment by Pedro-Murteira** [comment]
@rldhont Hello, is this issue still valid on more recent releases?
