### ISSUE TITLE
3D map and critical Qt warnings

### ISSUE THREAD

**Issue by saberraz** [qgis/QGIS#35078]
When I try to open a 3D map, I get the following critical warnings:

```
CRITICAL    Qt : QObject::connect(Qgs3DMapScene, Qgs3DMapToolIdentify): invalid null parameter
CRITICAL    Qt : QObject::connect(Qgs3DMapScene, Qgs3DMapToolMeasureLine): invalid null parameter
CRITICAL    Qt : QObject::connect(Qgs3DMapSettings, Qgs3DMapToolMeasureLine): invalid null parameter
```

**Comment by ismailsunni** [comment]
@saberraz in which version did you get these messages?

**Comment by saberraz** [comment]
QGIS version | 3.13.0-Master | QGIS code revision | 55d37614cb
-- | -- | -- | --
Compiled against Qt | 5.12.4 | Running against Qt | 5.12.4
Compiled against GDAL/OGR | 3.1.0dev-e6bd967e0d | Running against GDAL/OGR | 3.1.0dev-e6bd967e0d
Compiled against GEOS | 3.9.0dev-CAPI-1.14.0 | Running against GEOS | 3.9.0dev-CAPI-1.14.0
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 12.0 (Ubuntu 12.0-2.pgdg19.04+1) | SpatiaLite Version | 5.0.0-beta0
QWT Version | 6.1.4 | QScintilla2 Version | 2.10.4
Compiled against PROJ | 7.1.0 | Running against PROJ | Rel. 7.1.0, August 1st, 2020
OS Version | Ubuntu 19.10 | This copy of QGIS writes debugging output.
Active python plugins | valuetool; crayfish; cawdor_forestry_db; cartogram3; CityJSON-loader; Mergin; DataPlotly; MetaSearch; processing; db_manager

**Comment by ismailsunni** [comment]
Hi, @saberraz I made a PR #35096  for this issue. I got different warning messages though initially (i.e. only `null parameter`), but my PR removes the critical warning message.
Please try and let me know if it works also for you.

**Comment by saberraz** [comment]
Nice one @ismailsunni 

I tested your PR and the warning went away! Thanks a lot.
