### ISSUE TITLE
Vertex tool Edit not accuracy

### ISSUE THREAD

**Issue by wanghai1988** [qgis/QGIS#35079]
When I use “vertex tool edit” and enable “topologyedit” to move a polygon vertex, sometimes this vertex is the common vertex of three polygons, but when I move this vetex, only two polygons change the geometry。version：3.12.0

![image](https://user-images.githubusercontent.com/13306286/76683915-a3311900-6642-11ea-9b76-3af8991b039e.png)
![image](https://user-images.githubusercontent.com/13306286/76683927-be9c2400-6642-11ea-8cb8-aa98a8b87270.png)
[testdata.zip](https://github.com/qgis/QGIS/files/4332880/testdata.zip)

**Comment by uclaros** [comment]
The polygons in the testdata are not snapped to each other. Some nodes coincide, but some others are very close but do not coincide, you can find those with *Check geometries* and a very small tolerance (E-16).
If you first run *Snap geometries to layer* , select the same layer twice and pick *Snap to anchor nodes (single layer only)* with a tolerance bigger than your gaps (1E-9 in your case) it will be fixed.
You can also run *Snap points to grid* with a tolerance that fits the precision of your data.

**Comment by gioman** [comment]
> The polygons in the testdata are not snapped to each other. Some nodes coincide, but some others are very close but do not coincide, you can find those with _Check geometries_ and a very small tolerance (E-16).
> If you first run _Snap geometries to layer_ , select the same layer twice and pick _Snap to anchor nodes (single layer only)_ with a tolerance bigger than your gaps (1E-9 in your case) it will be fixed.
> You can also run _Snap points to grid_ with a tolerance that fits the precision of your data.

@uclaros good catch, but now the million dollar question is: how the layer was created. If it was created with QGIS using snapping then we have really an issue.

**Comment by wanghai1988** [comment]
thank you,

> > The polygons in the testdata are not snapped to each other. Some nodes coincide, but some others are very close but do not coincide, you can find those with _Check geometries_ and a very small tolerance (E-16).
> > If you first run _Snap geometries to layer_ , select the same layer twice and pick _Snap to anchor nodes (single layer only)_ with a tolerance bigger than your gaps (1E-9 in your case) it will be fixed.
> > You can also run _Snap points to grid_ with a tolerance that fits the precision of your data.
> 
> @uclaros good catch, but now the million dollar question is: how the layer was created. If it was created with QGIS using snapping then we have really an issue.

@uclaros @gioman Thank you for your answer ,this layer is create by my own algorithm，Now it seems to be my algorithm‘s bug
