### ISSUE TITLE
Reduce the head size when the line geometry is short in arrow symbol

### ISSUE THREAD

**Issue by fangzhegeo** [qgis/QGIS#35089]
**Feature description.**
In QgsArrowSymbolLayer, When the length of the line geometry is small,  the body of the arrow  will be covered by its head, only left the trianglular head.  I want a feature that the size of the arrow width, the arrow width at start, the head length and the head thickness will be reduced automatically when the line geometry is short.  

**Example**
The following is a expected symbology, which is realized by writing expresions.
![image](https://user-images.githubusercontent.com/29173894/76674681-20ca3a00-65ed-11ea-9461-6a11e26bc1be.png)

**Comment by roya0045** [comment]
Not a bug, just use the lenght of the line and a formula to control the size of the symbol.

**Comment by gioman** [comment]
@fangzhegeo  Closing?

**Comment by fangzhegeo** [comment]
> Not a bug, just use the lenght of the line and a formula to control the size of the symbol.

Sorry but I didn't get it. Is the "formula" you mentioned expression? I did realize it by writing expressions, which is very tedious. I wonder that whether it could resize automatically without writing expressions manually. A checkbox can be added in the user interface to control whether resize it when the line geometry is short.

**Comment by fangzhegeo** [comment]
> @fangzhegeo Closing?

Sorry I haven't get the answer. If it is not a expected feature, is it feasible to relize it by a pyqgis script or plugin?  If yes, please give me some suggestions. It would reduce my workload greatly.

**Comment by roya0045** [comment]
![image](https://user-images.githubusercontent.com/12854129/76755458-46c11d00-675a-11ea-8913-4874b84b4015.png)
