### ISSUE TITLE
QGIS crash

### ISSUE THREAD

**Issue by uwerder** [qgis/QGIS#35115]
while adjusting shape file boundaries in multiple layers QGIS just crashed. 
No specific heavy operation done shortly before. Traceback below.

Thanks developers for your support of QGIS. I really appreciate your efforts.
Ulrich

Crash ID: c0ab8a07ecc79b08768a9e06d71571f8d3992163

Stack Trace

MoveSmall memcpy.asm:442
VSICreateCachedFile :
GDALRegister_Terragen :
GDALRegister_Terragen :
GDALRegister_Terragen :
GDALRegister_Terragen :
GDALRegister_GTiff :
GDALRasterBand::GetLockedBlockRef :
GDALRasterBand::IRasterIO :
GDALRegister_GTiff :
GDALRasterBand::RasterIO :
QgsGdalProviderBase::gdalRasterIO qgsgdalproviderbase.cpp:299
QgsGdalProvider::readBlock qgsgdalprovider.cpp:905
QgsGdalProvider::block qgsgdalprovider.cpp:672
QgsSingleBandGrayRenderer::block qgssinglebandgrayrenderer.cpp:91
QgsBrightnessContrastFilter::block qgsbrightnesscontrastfilter.cpp:118
QgsHueSaturationFilter::block qgshuesaturationfilter.cpp:123
QgsRasterResampleFilter::block qgsrasterresamplefilter.cpp:162
QgsRasterProjector::block qgsrasterprojector.cpp:878
QgsRasterIterator::readNextRasterPartInternal qgsrasteriterator.cpp:130
QgsRasterDrawer::draw qgsrasterdrawer.cpp:60
QgsRasterLayerRenderer::render qgsrasterlayerrenderer.cpp:266
QgsMapRendererCustomPainterJob::doRender qgsmaprenderercustompainterjob.cpp:312
QgsMapRendererCustomPainterJob::staticRender qgsmaprenderercustompainterjob.cpp:261
QtConcurrent::RunFunctionTask::run qtconcurrentrunbase.h:136
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.10.2-A Coru�a
QGIS code revision: d4cd3cfe5a
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.3
Running against GDAL: 3.0.3

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment]
>  QGIS Version: 3.10.2-A Coru�a

@uwerder please update to 3.10.3, if the problem persist please try with a new QGIS profile, no 3rd party plugins installed.

**Comment by gioman** [comment]
Closing for lack of feedback.
