### ISSUE TITLE
project_crs_name variable

### ISSUE THREAD

**Issue by Saijin-Naib** [qgis/QGIS#35113]
**Feature description.**
A variable to expose the "name" or text of the project's CRS instead of just the authority ID and definition string would be quite valuable, as not everyone recognizes CRSs by their EPSG ID, and having "friendly" names visible, on a map layout for instance, is quite helpful.

**Additional context**
GIS.SE Question:  garth-cooper
https://gis.stackexchange.com/questions/354053/getting-text-name-of-current-project-crs-in-qgis-layout

> 
> I'm want to display the current project projection in a QGIS layout.
> 
> Right now I can get QGIS to display the current EPSG number like below:
> 
> [![Current Solution][1]][1]
> 
> But what I want to do is get QGIS layout to print the ESPG name as well like below with an expression:
> 
>  [![What I want][2]][2]
> 
>   [1]: https://i.stack.imgur.com/AgikV.png
>   [2]: https://i.stack.imgur.com/cR6Cm.png

Solution:  ian-turnton

> I think you will need a custom function to do this, the following seems to work though I haven't tested it extensively.
> 
```
>     from qgis.core import *
>     from qgis.gui import *
>     from qgis.utils import iface
>     
>     @qgsfunction(args='auto', group='Custom')
>     def getCrsDescription(feature, parent):
>         """
>         Returns the description text of the project CRS
>         <h2>Example usage:</h2>
>         <ul>
>           <li>getCrsDescription() -> WGS 84</li>
>           <li>getCrsDescription() -> OSGB 1936 / British National Grid</li>
>         </ul>
>         """
>         return iface.mapCanvas().mapSettings().destinationCrs().description()
```

**Comment by roya0045** [comment]
Agreed.

**Comment by roya0045** [comment]
@Saijin-Naib what about map_crs_description, this seems to be the one you want.

**Comment by Saijin-Naib** [comment]
> @Saijin-Naib what about map_crs_description, this seems to be the one you want.

Does not seem to be available in 3.12.0. Is that master only?

**Comment by roya0045** [comment]
Should be, if other map crs are there, I forgot I added that. https://github.com/qgis/QGIS/blob/f514516d0771d2163b0f42801dc3eb23c88e20c4/tests/src/core/testqgslayoutmap.cpp#L609

Maybe that's because its a map thing and the layout textbox is not linked to a specific map, hence why that context was not added for that.

**Comment by Saijin-Naib** [comment]
Thanks so much, guys!

**Comment by opfcl** [comment]
HI... 
I had the same problem.
I founded the most simple and wonderfull solution in https://gis.stackexchange.com/questions/352035/adding-crs-definition-details-to-layout-in-print-composer

The solution is the Following:
Put in the label panel this code...

[% map_get( item_variables('Mapa 1'),'map_crs_description')%]

You can use any vartiable from each map present in your layout,
For example:
- Change the name of map = [% map_get( item_variables('Mapa Regional'),'map_crs_description')%]
- Print the mapunits =  [% map_get( item_variables('Mapa 1'),'map_units')%]

Be Happy.
J. C jerez Torres
Chile

![image](https://user-images.githubusercontent.com/99933879/155194645-43ce9380-345a-4d09-a880-e84a45a1de9e.png)

![image](https://user-images.githubusercontent.com/99933879/155194468-ed633a8d-7129-49b0-b5b6-c41ce7da571d.png)

![image](https://user-images.githubusercontent.com/99933879/155196453-64b5cde1-828b-4534-a85c-8d86cbc15a54.png)
