### ISSUE TITLE
ESRI projections not correctly handled by GDAL algorithms

### ISSUE THREAD

**Issue by SrNetoChan** [qgis/QGIS#35123]
**Describe the bug**

Since the latest versions of GDAL and PROJ, QGIS now has CRSs from ESRI authority, which is nice. Nevertheless, when you, for example, reproject a WGS84 raster layer into ESRI:102003, when the output is loaded it comes with and invalid CRS.

The user can set the CRS manually to make it back to normal, but that is not possible in models, which fail to use the raster properly for the next steps (for example getting some spatial statistics using a vector layer with the same CRS)

**How to Reproduce**

#. Load a raster layer (you can use this [one](https://cloud.naturalgis.pt/index.php/s/cW3y37YQKmYNAbx))
#. Reproject the raster layer to ESRI:102003 using GDAL warp
#. Confirm that the loaded layer CRS is set to invalid

**QGIS and OS versions**

QGIS version | 3.10.3-A Coruña | QGIS code revision | 0e1f846438
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Windows 10 (10.0)
Active python plugins | qfieldsync; db_manager; MetaSearch; processing

**Additional context**

**Comment by nyalldawson** [comment]
Only affects gdal algorithms -- if you use the built in "save as" for rasters, it'll work fine

**Comment by SrNetoChan** [comment]
The problem is that you can't use save as in the processing modeler.

**Comment by nyalldawson** [comment]
@SrNetoChan I agree it's a bug, I'm just providing a workaround and explaining the actual scope of the bug.

**Comment by SrNetoChan** [comment]
Ah sorry. Let me know if you want me to do some testing.

Seems that at least warp is using the CRS parameters instead of the ESRI code

gdalwarp -t_srs "+proj=aea +lat_0=37.5 +lon_0=-96 +lat_1=29.5 +lat_2=45.5 +x_0=0 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs" -r near -of GTiff Z:/Trabalho/ARSI/data/Crooks/DEM_Crooks_SD_epsg4326.tif C:\Users\BOUNDL~1\AppData\Local\Temp/processing_cb195a274bb04200a9ba03d46c3d54ae/792d6c73818045aabeefe7c58fa625a9/OUTPUT.tif

While if you choose a EPSG code, it just uses it directly

gdalwarp -t_srs EPSG:3763 -r near -of GTiff Z:/Trabalho/ARSI/data/Crooks/DEM_Crooks_SD_epsg4326.tif C:\Users\BOUNDL~1\AppData\Local\Temp/processing_cb195a274bb04200a9ba03d46c3d54ae/9a04889b73a6419ab2c8ed781a2f7f4f/OUTPUT.tif

Using this on the command line works fine

gdalwarp -t_srs ESRI:102003 -r near -of GTiff Z:/Trabalho/ARSI/data/Crooks/DEM_Crooks_SD_epsg4326.tif C:\Users\BOUNDL~1\AppData\Local\Temp/processing_cb195a274bb04200a9ba03d46c3d54ae/9a04889b73a6419ab2c8ed781a2f7f4f/OUTPUT.tif

**Comment by SrNetoChan** [comment]
There's where it's failing:

https://github.com/qgis/QGIS/blob/fcdf1f6e7873497b36159bcee772a22637a61304/python/plugins/processing/algs/gdal/GdalUtils.py#L435

**Comment by nyalldawson** [comment]
@SrNetoChan see #35125
