### ISSUE TITLE
3.12.0 crashes in logicalDotsperinchX

### ISSUE THREAD

**Issue by g8sqh** [qgis/QGIS#35137]
On artix linux, qgis 3.12.0 crashes when attempting to double click on properties for a bathymetry geotiff file

Checking the gdb backtrace, and reading the assembler, the problem is line 448 in gui/raster/qgsrasterlayerproperties.cpp. `screenAt()` can return null (and is doing on my multi-monitor setup)

Quick and dirty fix - change line 449 to read

`const int horizontalDpi = (screen ?  screen->logicalDotsPerInchX() : 96);`
`
so that weird screen layouts guess 96dpi, rather than crashing

**Comment by gioman** [comment]
@g8sqh can you please attach one of your offending geotiffs so we can check if it happens also on more mainstream distributions and others OSes? Thanks.

**Comment by g8sqh** [comment]
[1994 HI594 South Eastern Approaches to Plymouth Blk4.tif.gz](https://github.com/qgis/QGIS/files/4343779/1994.HI594.South.Eastern.Approaches.to.Plymouth.Blk4.tif.gz)

**Comment by gioman** [comment]
@g8sqh it is ok on Ubuntu 18.04 and Windows.

**Comment by g8sqh** [comment]
Doesn't surprise me - I run two different sized monitors (same GPU) with enlightment as the window manager,  neither KDE nor GNome installed, no systemd - so definitely an unusual system :-)  However it's run QGIS successfully for 3 years, and I'd like to keep it working. I have no problem just patching and rebuilding if the fix isn't suitable for mainstream use.

**Comment by gioman** [comment]
@g8sqh submit a patch as a pull request and wait to see what the devs will say about that.

**Comment by nyalldawson** [comment]
I think this is already fixed on master - can you test?

**Comment by g8sqh** [comment]
I downloaded commit daaeeb40 from master
I had to make one change to get it to compile with Qt 5.14 - line 26 in src/3d/mesh/qgsmesh3dmaterial_p.cpp

`#include <QVector2D>`

Happy to report the previous problem has been fixed
