### ISSUE TITLE
Crash when selecting polygon from KML/KMZ datasource

### ISSUE THREAD

**Issue by angelos87** [qgis/QGIS#35149]
## User Feedback

I imported a KMZ file in my project and tried to select a polygon.

## Report Details

**Crash ID**: [8c6741d06a0c02db92ccaac6af8740a6dcb4c8b5]('https://github.com/qgis/QGIS/search?q=8c6741d06a0c02db92ccaac6af8740a6dcb4c8b5&type=Issues')

**Stack Trace**
<pre>
geos::noding::snapround::MCIndexSnapRounder::computeVertexSnaps :
geos::noding::snapround::MCIndexSnapRounder::computeVertexSnaps :
geos::noding::snapround::MCIndexSnapRounder::computeVertexSnaps :
geos::noding::snapround::MCIndexSnapRounder::computeVertexSnaps :
geos::noding::snapround::MCIndexSnapRounder::computeVertexSnaps :
geos::noding::snapround::MCIndexSnapRounder::computeVertexSnaps :
geos::noding::snapround::MCIndexSnapRounder::computeVertexSnaps :
geos::noding::snapround::MCIndexSnapRounder::computeVertexSnaps :
GEOSEquals_r :
</pre>

**QGIS Info**
QGIS Version: 3.10.3-A Coru�a
QGIS code revision: 0e1f846438
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by roya0045** [comment]
If the data is not sensitive you could upload it here for people to validate. Otherwise a dev might ask you to send the data directly to him to ensure privacy and still test the data.

Though right off the bat it seems like a corrupted geometry since geos is acting up.

**Comment by angelos87** [comment]
Unfortunately the data is confidential, but I can send it to a developer if
necessary.

**Comment by gioman** [comment]
> Unfortunately the data is confidential, but I can send it to a developer if necessary.

@angelos87 does it happens really only with that specific KMZ?

**Comment by angelos87** [comment]
@gioman Yes, it seems to be related to that file. Try importing the attached KML and selecting the polygon.

[test_polygon.zip](https://github.com/qgis/QGIS/files/4349213/test_polygon.zip)

**Comment by gioman** [comment]
Confirmed on both Windows and Linux.

**Comment by roya0045** [comment]
Since the error comes from geos I would thing that the issue is upstream in geos or in the data itself. :/

**Comment by gioman** [comment]
> Since the error comes from geos I would thing that the issue is upstream in geos or in the data itself. :/

yes, but QGIS should not crash anyway.

**Comment by nyalldawson** [comment]
The crash is happening in the geos library - this needs moving upstream.

**Comment by nyalldawson** [comment]
https://github.com/libgeos/geos/issues/295
