### ISSUE TITLE
QGIS Crashes Upon Launch

### ISSUE THREAD

**Issue by user1180** [qgis/QGIS#35159]
This is my first time posting.

Running Linux Mint 19.3 (MATE)

Did a fresh install of QGIS 3.12 from the Mint repos. Launching the application brings up the loading screen, then crashes after about 10-20 seconds.

Launching from the terminal spits out the following [error](https://pastebin.com/xmxscm30)

And this is the [backtrace](https://pastebin.com/D3gTmC5R) created by Mint.

Prior to the reports just pasted, I had to install qgis-dbg to get a backtrace.

**Comment by gioman** [comment]
> Did a fresh install of QGIS 3.12 from the Mint repos

@user1180 weird,19.3 is based on Ubuntu 18.04 and there you don't have QGIS 3.12 in the repos:

https://packages.ubuntu.com/search?keywords=qgis&searchon=names&suite=bionic&section=all

plesae try again by adding the qgis.org repository.

**Comment by user1180** [comment]
I already had qgis repos added from a previous installation attempt. I discovered that the version in the Mint repos isn't the LTR release. So I  purged qgis and all related packages I could find, removed all existing qgis repos, added the Ubuntu-ltr repo for bionic, and then reinstalled qgis according to the official site instructions. I've got A Coruna now, which is what I wanted anyway, but I'm still facing the same problem. Terminal output and backtrace have been updated.

**Comment by gioman** [comment]
Weird, I have a number of computers with Mint 19.3 and no issues here.

**Comment by user1180** [comment]
Must have misread, the Mint repos now read as 3.10.4+28bionic. In any case, I noticed a discrepancy in the sources list. The etc/apt/sources.list file is labelled as the sources list for Mint 19.2. Idk if that would make a difference or not. Also, when I ran the morning update, the manager reported an error about the sources list having double/repeat entries or something. Here's a screencap of the sources file.
![discrepancy](https://user-images.githubusercontent.com/60323465/77344726-96c35500-6d01-11ea-8042-97dff39d4b64.png)

**Comment by gioman** [comment]
> The etc/apt/sources.list file is labelled as the sources list for Mint 19.2. Idk if that would make a difference or not. Also, when I ran the morning update, the manager repor

that is a comment, a leftover from an update

> Also, when I ran the morning update, the manager reported an error about the sources list having double/repeat entries or something (unfortunately, I neglected to take a screencap. Will do next time).

fix your issues with the sources then try again.

I suggest you to remove everything that is QGIS, of GDAL or PROJ OR GEOS related, then update sources and install again.

**Comment by gioman** [comment]
Closing for lack of feedback.
