### ISSUE TITLE
[Atlas] unprinted and inconsistent graphics with coverage vector

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#35173]
I created a simple project and an atlas.

I notice some problems:

1. randomly the graphs are not printed when exported to PDF;

![image](https://user-images.githubusercontent.com/7631137/76709172-d0420200-66fc-11ea-9d46-2f2eacb1b1aa.png)

2. the printed graphics do not respect the coverage vector;
 
![image](https://user-images.githubusercontent.com/7631137/76709180-e64fc280-66fc-11ea-82a9-23f54c797142.png)

Leafing through the atlas, I notice that the creation of the charts is rather slow.

I attach a PDF exported from the attached project.

---
## OSGeo4W64 Win 10 - QGIS 3.12 București
---

![image](https://user-images.githubusercontent.com/7631137/76709264-d684ae00-66fd-11ea-9595-500872ff7e2b.png)

data and project:
[test_dataplotly35.zip](https://github.com/ghtmtt/DataPlotly/files/4334968/test_dataplotly35.zip)

---
**I suspect it's a QGIS issue and not the DataPlotly plugin**

https://github.com/ghtmtt/DataPlotly/issues/207

**Comment by gioman** [comment]
> the printed graphics do not respect the coverage vector;

@pigreco I can't uderstand the problem from the image, can you be more precise?

anyway it seems a different issue from

> randomly the graphs are not printed when exported to PDF;

so it should be filed in a different ticket.

**Comment by gioman** [comment]
> randomly the graphs are not printed when exported to PDF;

Can't replicate this on 3.12 on linux.

**Comment by pigreco** [comment]
Some graphs do not respect the coverage vector, ie if the current vector is x the data of the vector x-1 is reported in the graph; in other cases the chart is not printed.
The attached project has been tested in win, mac and linux environments and all have similar problems.

**Comment by pigreco** [comment]
the column in green (2) has values 2,0,0,0 and the graph instead displays too large values
![image](https://user-images.githubusercontent.com/7631137/77000775-2f9c4e00-6959-11ea-997e-7e3a7a70641d.png)

**Comment by pigreco** [comment]
@gioman 
being a problem related to the print composer, it is appropriate to tag nyall ??

**Comment by roya0045** [comment]
> the column in green (2) has values 3,0,0,0 and the graph instead displays too large values
> ![image](https://user-images.githubusercontent.com/7631137/77000775-2f9c4e00-6959-11ea-997e-7e3a7a70641d.png)

That's 100% a plugin issue. It is also possible that the plugin doesn't ensure that all images are rendered before exporting. I doubt QGIS is to blame for this.

**Comment by gioman** [comment]
@pigreco have you contacted the plugin author?

**Comment by pigreco** [comment]
> @pigreco have you contacted the plugin author?

yes, I also opened issue in the plugin author's repository.
We await response from nyall

https://github.com/ghtmtt/DataPlotly/issues/207

**Comment by roya0045** [comment]
From what I gathered quickly the figure are made and rendered in a web view, it might be lighter to have them as fixed image that get replaced but the risk is still that when the layout is being painted/drawn the plugin will probably not finish before everything else is done and exported.

**Comment by ludovico85** [comment]
I agree with @pigreco. I have made two tests with two different machines, both with Windows10:
- PC Desktop with i7-7700 @3.60 GHz and 16 GB of RAM - GeForce GTX 1050Ti (**no issue**)
- Notebook with i5-3210M @2.50 GHz and 8 GB of RAM - AMD Radeon HD 7600M (**issue**)

[atlas_3.12.1.pdf](https://github.com/qgis/QGIS/files/4443843/atlas_3.12.1.pdf)
[atlas_3.12.1_notebook.pdf](https://github.com/qgis/QGIS/files/4443844/atlas_3.12.1_notebook.pdf)

**Comment by pigreco** [comment]
Problem solved.

I close issue.

thank you all
