### ISSUE TITLE
Wrong interpretation of url with accented characters using GetLegendGraphic

### ISSUE THREAD

**Issue by sigmoe** [qgis/QGIS#35176]
**Describe the bug**
In QGIS Server, I use a project with a layer which name has an accented character (layername = Département GE Nord-Est). When I try to obtain the legend of that layer, I use an URL replacing the accented character by the HTML code (é replaced by %E9):  
`.../qgisserver?&SERVICE=WMS&REQUEST=GetLegendGraphic&VERSION=1.3.0&FORMAT=image/png&LAYER=D%E9partements%20GE%20Nord-Est`
And it doesn't work. I have the message:
`<ServiceException code="LayerNotDefined">
The layer 'D�partements GE Nord-Est' does not exist.
</ServiceException>`
It works with this URL:
`.../qgisserver?&SERVICE=WMS&REQUEST=GetLegendGraphic&VERSION=1.3.0&FORMAT=image/png&LAYER=Départements%20GE%20Nord-Est`
where I didn't replace the accented character in the URL.

**How to Reproduce**

1) In QGIS Server, use a project with an accented character in a layername
2) Try to obtain the legend of that layer using an URL with no accented character

**QGIS and OS versions**

QGIS Server 3.10
Ubuntu 18.04

**Additional context**

**Comment by elpaso** [comment]
QGIS Server 3.10 is not supported. Please retry with >= 3.16 and if the issue is till there we can re-open the issue.
