### ISSUE TITLE
crash when copying features between gpkg layers

### ISSUE THREAD

**Issue by RobinRots** [qgis/QGIS#35171]
## User Feedback

For some reason I'm not able to copy polygons between two of my layers in QGIS 3.12. Both layers are contained in the same geopackage. Each time i do this, I get a crash. I tried doing the same operation in an new empty project, but even then this crash happens. I also tried copying to a temporary scratch layer and then to the target layer, but it still crashes. I did a validity check (Vector>Geometry tools>Check Validity...) on both layers which returns 0 errors. Finally, I reïnstalled version 3.10 and tried the same operation, which this time gave no problem at all! So the problem seems to be related to the latest version...

In attachment a trimmed down version of the mentioned gpkg, I tried copying the two polygons from the layer 'GK_NPHK_2' to the layer 'Gebieden'.
[database_beheer_copy_for_bugreport.zip](https://github.com/qgis/QGIS/files/4348913/database_beheer_copy_for_bugreport.zip)

Cheers,

Robin

## Report Details

**Crash ID**: [1ef5167970854de4c0075232d4a1ea2e1734a1b5]('https://github.com/qgis/QGIS/search?q=1ef5167970854de4c0075232d4a1ea2e1734a1b5&type=Issues')

**Stack Trace**
<pre>
QgsMapCanvas::currentLayer qgsmapcanvas.cpp:483
QgsMapToolCapture::QgsMapToolCapture qgsmaptoolcapture.cpp:55
QgsMapToolDigitizeFeature::QgsMapToolDigitizeFeature qgsmaptooldigitizefeature.cpp:38
QgsRelationEditorWidget::setEditorContext qgsrelationeditorwidget.cpp:368
QgsRelationWidgetWrapper::initWidget qgsrelationwidgetwrapper.cpp:126
QgsWidgetWrapper::widget qgswidgetwrapper.cpp:55
QgsAttributeFormWidget::QgsAttributeFormWidget qgsattributeformwidget.cpp:65
QgsAttributeFormRelationEditorWidget::QgsAttributeFormRelationEditorWidget qgsattributeformrelationeditorwidget.cpp:23
QgsAttributeForm::createWidgetFromDef qgsattributeform.cpp:1858
QgsAttributeForm::createWidgetFromDef qgsattributeform.cpp:1930
QgsAttributeForm::init qgsattributeform.cpp:1369
QgsAttributeForm::QgsAttributeForm qgsattributeform.cpp:78
QgsFixAttributeDialog::init qgsfixattributedialog.cpp:54
QgsFixAttributeDialog::QgsFixAttributeDialog qgsfixattributedialog.cpp:26
QgisApp::pasteFromClipboard qgisapp.cpp:9705
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1609
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.12.0-Bucure?ti
QGIS code revision: cd141490ec
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.14393

**Comment by gioman** [comment]
Confirmed, it works fine on LTR 3.10.3.
