### ISSUE TITLE
hyperlink doesn't work in PDF printing

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#35172]
I made a project and a print layout, I added an HTML frame:

![image](https://user-images.githubusercontent.com/7631137/76970096-a91d4780-692b-11ea-8fac-80e90cb8cbae.png)

```
<a href="https://qgis.org/it/site/"> QGIS </a>
```
but after printing to PDF, the link does not work, it is not clickable.

---

OSGeo4W64 QGIS 3.12 București  win 10

![image](https://user-images.githubusercontent.com/7631137/76970581-65770d80-692c-11ea-930d-b3473712351f.png)

PDF:
[6-PA.pdf](https://github.com/qgis/QGIS/files/4349456/6-PA.pdf)

**Comment by gioman** [comment]
> but after printing to PDF, the link does not work, it is not clickable.

@pigreco  https://github.com/qgis/QGIS/issues/29888 ?

**Comment by pigreco** [comment]
> @pigreco #29888 ?
 
right, there is no news ??

**Comment by ivn951** [comment]
Correctly the syntax should be:

`<a href="url"> link_text /a>`

In the QGIS layout, this syntax is ignored as there is no distinction between the `url` part and the `link_text` part.  In fact if you type :

`<a href> www.qgis.org/a>`

it's the same thing.

**Comment by pigreco** [comment]
If I'm not mistaken, it's a limit of the Qt library

**Comment by gioman** [comment]
> If I'm not mistaken, it's a limit of the Qt library

yes it's an upstream issue. Did you tried of exporting as geopdf it makes any difference?

**Comment by ivn951** [comment]
> yes it's an upstream issue. Did you tried of exporting as geopdf it makes any difference?

no difference...

**Comment by pigreco** [comment]
@giohappy 

Why did you close??
Can't solve the problem ??

IMHO is a key feature!

**Comment by gioman** [comment]
> Why did you close??

@pigreco have you seen the comment from a core developer here? https://github.com/qgis/QGIS/issues/29888 is an **upstream** issue, not an issue in QGIS code.

**Comment by f0lg0** [comment]
Same thing happening in GQGIS 3.34, has this been solved somehow?

**Comment by agiudiceandrea** [comment]
@f0lg0, this issue has been fixed since QGIS 3.32: see https://github.com/qgis/QGIS/pull/53192.
You need to use a Label item with the Render as HTML option set, instead of an HTML item.
