### ISSUE TITLE
QGIS crash calling originalSymbolsForFeature or originalSymbolForFeature or symbolForFeature

### ISSUE THREAD

**Issue by asfixia** [qgis/QGIS#35199]
## User Feedback

Using any point Layer crashes. Using any of the functions like originalSymbolForFeature causes the QGIS to crash.

layer = iface.mapCanvas().layers()[0]

#renderContext = QgsRenderContext()
clonedLayer = layer.clone()
#layerRenderer = clonedLayer.createMapRenderer(renderContext)
layerRenderer = clonedLayer.renderer()
layerSymbols = layerRenderer.legendSymbolItems()
renderContext = layerRenderer.renderContext()
imageList = list()
iconField = QgsField('icon_url', QVariant.String, 'text')
clonedLayer.startEditing()
res = clonedLayer.addAttribute(iconField)
clonedLayer.commitChanges()
#layerRenderer.startRender(renderContext, clonedLayer.fields())
clonedLayer.startEditing()
for feature in clonedLayer.getFeatures():
    symbol = layerRenderer.originalSymbolsForFeature(feature, renderContext)  # originalSymbolForFeature(f, teste)
    break

## Report Details

**Crash ID**: [3420333691f8f32c2b9345894ec11bb1b284d264]('https://github.com/qgis/QGIS/search?q=3420333691f8f32c2b9345894ec11bb1b284d264&type=Issues')

**Stack Trace**
<pre>
QgsExpression::evaluate qgsexpression.cpp:412
QgsGraduatedSymbolRenderer::valueForFeature qgsgraduatedsymbolrenderer.cpp:138
QgsGraduatedSymbolRenderer::originalSymbolForFeature qgsgraduatedsymbolrenderer.cpp:150
QgsFeatureRenderer::originalSymbolsForFeature qgsrenderer.cpp:419
meth_QgsFeatureRenderer_originalSymbolsForFeature sip_corepart2.cpp:61758
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyImport_Import :
PyImport_Import :
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_sip :
PyInit_Qsci :
QWidget::event :
QFrame::event :
QAbstractScrollArea::event :
PyInit_Qsci :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processKeyEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1598
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.2-A Coru�a
QGIS code revision: d4cd3cfe5a
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.3
Running against GDAL: 3.0.3

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by gioman** [comment]
@asfixia are you sure is a bug and not just a misuse of the API?

**Comment by asfixia** [comment]
Like another thread i added
layerRenderer.startRender(renderContext, clonedLayer.fields())
But instead of crash the symbol has no content.
And even this code, it was working when using a simple symbology.

**Comment by asfixia** [comment]
Well i got it working so not sure if it is a API issue or missing some documentation information, there is nothing about the startRender in the originalSymbolsForFeature function.

If someone with the same problem my working code is as follow:

```
import time;
layer = iface.mapCanvas().layers()[0]


clonedLayer = layer.clone()
layerRenderer = clonedLayer.renderer()
renderContext = QgsRenderContext()
renderContext.setUseAdvancedEffects(True)
renderContext.setFlags(QgsRenderContext.Flag.RenderBlocking | QgsRenderContext.Flag.Antialiasing)
imageList = list()
iconField = QgsField('icon_url', QVariant.String, 'text')
clonedLayer.startEditing()
res = clonedLayer.addAttribute(iconField)
clonedLayer.commitChanges()
clonedLayer.startEditing()
for feature in clonedLayer.getFeatures():
    layerRenderer.startRender(renderContext, clonedLayer.fields())
    symbol = layerRenderer.originalSymbolForFeature(feature, renderContext)
    layerRenderer.stopRender(renderContext)
    curImage = symbol.asImage(QSize(32, 32))
    try:
        imgIndex = imageList.index(curImage)
    except Exception as e:
        imageList.append(curImage)
        imgIndex = len(imageList) - 1
    break
    #feature.setAttribute("icon_url", './' + str(imgIndex) + ".png")
    #clonedLayer.updateFeature(feature)
    #print(len(imageList))
    # break

clonedLayer.commitChanges()
wgs_crs = QgsCoordinateReferenceSystem('EPSG:4326')
QgsVectorFileWriter.writeAsVectorFormat(clonedLayer, 'C:/Users/danilo/Downloads/symbol/myjson_danilo_.json',
                                                  'utf-8', wgs_crs, 'CSV', layerOptions=['GEOMETRY=AS_XY'])
for index in range(len(imageList)):
    imageList[index].save('C:/Users/danilo/Downloads/symbol/' + str(index) + '.png')

```
