### ISSUE TITLE
Print composer - bug when using theme and undisplayed group

### ISSUE THREAD

**Issue by simogeo** [qgis/QGIS#35203]
Having layers in group (unchecked so invisible) and using Theme in Print composer cause unwated displayed layers.

**See example below (invisible group) :**

![image](https://user-images.githubusercontent.com/154323/77095513-4d77ba80-6a0e-11ea-8846-2a57dbd88a4b.png)

**But layers are visible on print composer when map is set to specified Theme - see result :** 

![image](https://user-images.githubusercontent.com/154323/77095568-62ece480-6a0e-11ea-9678-6ec810f48fba.png)

**How to Reproduce**

1. Create a Group in layers manager
2. Add layers in group
3. Make group unckeched
4. Add theme
5. Create print composer 
6. Add map set content based on created Theme
7. See bug 

**QGIS and OS versions**

QGIS version | 3.12.0-București | QGIS code revision | 409bcf8eaa
-- | -- | -- | --
Compiled against Qt | 5.12.4 | Running against Qt | 5.12.4
Compiled against GDAL/OGR | 2.4.2 | Running against GDAL/OGR | 2.4.2
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.7 (Ubuntu 11.7-0ubuntu0.19.10.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.10.4
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Ubuntu 19.10
Active python plugins | VectorBender; AnotherDXF2Shape; mask; Qgis2threejs; GeoCoding; vector_tiles_reader; ORStools; qconsolidate3; shapetools; Hqgis; DataPlotly; french_locator_filter; SRTM-Downloader; Beeline; OSMtools; QNEAT3; loadthemall; db_manager; MetaSearch; processing

**Comment by roya0045** [comment]
pretty sure there were similar tickets regarding themes and group or complex symbology. I might be wrong.

**Comment by nyalldawson** [comment]
This is fixed already

**Comment by simogeo** [comment]
Sorry for duplicate ! And thanks for the good work
