### ISSUE TITLE
relations not working in duplicated layers

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#35204]
Starting from a layey with 1: m relations with another layer, if I duplicate this layer the relations are not recognized.

Is it a desired behavior or is it a bug ??

If it were a bug I will attach a mini-project.

## OSGeo4W QGIS 3.12

**Comment by gioman** [comment]
>  the relations are not recognized.

@pigreco it means that the relation is visible in the layer properties but does not work or that in the duplicated layer the relation is not duplicated too?

**Comment by pigreco** [comment]
> @pigreco it means that the relation is visible in the layer properties but does not work or that in the duplicated layer the relation is not duplicated too?


@gioman 
exactly, the relationships are visible but not recognized.
Relationship ID error appears

**Comment by elpaso** [comment]
Just a wild guess here, but I think that because the relations are based on layer IDs, when a layer is duplicated the new layer has a different ID and the relation is "broken".

**Comment by andreasneumann** [comment]
To me it is unclear if duplicating a layer should also duplicate the corresponding relations. Do we really want that?

Relations are something that should be either derived from the database sources, or if set manually (e.g. in case of shapefile) it should be really made consciously.

But I have not a clear opinion here.

**Comment by elpaso** [comment]
@andreasneumann I agree, I'm not sure this is what we want to happen automatically, my comment was just a possible explanation about what is probably happening.

**Comment by gioman** [comment]
> Do we really want that?

I agree, I would suggest to **not** transpose relations or joins when duplicating layers.

**Comment by haubourg** [comment]
> To me it is unclear if duplicating a layer should also duplicate the corresponding relations. Do we really want that?

Agreed, we don't want relations to duplicate themselves automagically. 
This is a bit tricky for the user. The only think I could think of is a gentle messageBar information warning that relations are not duplicated. But even this appears a bit intrusive, UX wise.

**Comment by gioman** [comment]
Closing?
