### ISSUE TITLE
error message in export to image

### ISSUE THREAD

**Issue by greenmansinger** [qgis/QGIS#35202]
Cannot write to /home/xxxx/xxxx/xxxx.bmp

This file may be open in another application.

Note this does *not* crash the program, it just brings up the above error message, regardless of what sort of output file I choose, or what I choose to call the file. No such file previously exists.

This happens both in layout and in the main screen.

**Comment by gioman** [comment]
@greenmansinger please add detailed steps to replicate. Also version if QGIS used and OS.

**Comment by roya0045** [comment]
Also does it only occur with bmp or a specific location that you are trying to write to?

**Comment by nyalldawson** [comment]
Closing due to lack of feedback
