### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 32293: ordinal not in range(128)

### ISSUE THREAD

**Issue by Selena-Kimball** [qgis/QGIS#35223]
I am getting this error when trying to create a geopackage file using Flo2d plugin:

Traceback (most recent call last):
  File "/Users/goddamnit/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/flo2d/gui/dlg_settings.py", line 156, in create_db
    con = database_create(gpkg_path)
  File "/Users/goddamnit/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/flo2d/geopackage_utils.py", line 80, in database_create
    qry = open(script, 'r').read()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 32293: ordinal not in range(128)

Python version: 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 05:52:31) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] 
QGIS version: 3.4.2-Madeira Madeira, exported 

Python Path:
/Applications/QGIS3.app/Contents/MacOS/../Resources/python
/Users/goddamnit/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/goddamnit/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS3.app/Contents/MacOS/../Resources/python/plugins
/Library/Frameworks/SQLite3.framework/Versions/D/Python/3.6
/Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
/Users/goddamnit/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/goddamnit/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/flo2d/deps/pyqtgraph-0.10.0-py3.6.egg

I'm using MacOS Catalina with QGIS 3.4.2. Any help would be appreciated!

**Comment by roya0045** [comment]
1) Contact plugin author instead. 2) Update qgis just in case.

**Comment by saberraz** [comment]
I have opened a ticket in the plugin repo (private repo). Please contact the plugin maintainer.

**Comment by FLO-2DKaren** [comment]
Selena-Kimball,  I think you may have a the experimental plugin.  Contact me via my website contact form and we'll get this sorted out. www.flo-2d.com

**Comment by Selena-Kimball** [comment]
FLO-2DKaren, I submitted a contact form on www.flo-2d.com on Friday afternoon. Is there an email I can reach you that is quicker?
