### ISSUE TITLE
Fill NODATA  does not fill all NODATA 

### ISSUE THREAD

**Issue by bacloud14** [qgis/QGIS#35232]
* Version de QGIS  3.12.0-București
* Révision du code  cd141490ec
* Compilé avec GDAL/OGR  3.0.4
* Utilisé avec GDAL/OGR  3.0.4

* Windows 10

I am trying to fill NODATA although I do not know how what values they are represented with.
So running: 
gdal_fillnodata.py on a raster file, did not give the desirable results, as not all NODATA cells are filled.
The command I picked from QGis then tried to run in Windows bash like:

`FOR %i IN (C:\Users\UBU\Dowloads\NODATA\*.tif) DO "C:/Program Files/QGIS 3.12/bin/python3.exe" "C:/Program Files/QGIS 3.12/apps/Python37/Scripts/gdal_fillnodata.py" -md 10 -b 4 -of GTiff "%i" "%i.tiff"` 

But this does not change anything I guess.

Result:

Using Raster object from acrpy provided by Esri, I am testing nan values in the file in input and in output:

np.count_nonzero(np.isnan(RasterToNumPyArray(Raster('s5p_no2_20180917T164548_20180923T182508.tif'))))
600
np.count_nonzero(np.isnan(RasterToNumPyArray(Raster('20180917T164548_20180923T182508.tif.tiff')))) 
50

So I still have some NODATA cells. 
Is this normal behavior ? and why if yes.

**Comment by gioman** [comment]
>  Is this normal behavior ? and why if yes.

@bacloud14 is this a question or a bug report?

**Comment by bacloud14** [comment]
I guess this is a bug, from what I read in documentation. also I am sorry to annoy here, I guess this belongs to gdal, I just payed attention.
