### ISSUE TITLE
load raster failed

### ISSUE THREAD

**Issue by jovahe** [qgis/QGIS#35231]
I used the following code to load a raster image, why the rlayer is invalid?

reg=QgsProject.instance()
fileInfo = QFileInfo(file)
baseName = fileInfo.baseName()
rlayer = QgsRasterLayer(file, baseName)
if not rlayer.isValid():
print("图层加载失败！")

**Comment by gioman** [comment]
@jovahe please ask questions on the users or developers mailing lists. Thanks!
