### ISSUE TITLE
Export GeoPDF "Could not create print device"

### ISSUE THREAD

**Issue by morrow5991** [qgis/QGIS#35242]
Trying Export to a Geo Spartial PDF  throws error "Export to PDF" "Could not create print device".  The Export to PDF works with Create Geospartial PDF unchecked,   I have not rotated the map (see #34438) The base map is GeoPDF created in a prior version of  QGIS with a couple of layers added.

Error Reproduction:  
    <project> < layout manager>
    select a layout click show
   <layout) <Export to PDF> perform save as dialog
   Check "Create Geospartial PDF" 
   click save

project with throws error and System info from machine with issue
[qgis_error.zip](https://github.com/qgis/QGIS/files/4366244/qgis_error.zip)

OS: Window 10 Home 64 bit
QGIS version 3.12.0-București QGIS code revision cd141490ec

**Comment by gioman** [comment]
> The base map is GeoPDF created in a prior version of QGIS with a couple of layers added.

@morrow5991 the project seems to have a **geotiff** layer in it, not a geopdf.
Anyway is not inside here

>  [qgis_error.zip](https://github.com/qgis/QGIS/files/4366244/qgis_error.zip)


it would be much better of you can attach a sample project with **all** the necessary layers. Thanks.

**Comment by morrow5991** [comment]
Embarrassing!  My bad! I missed the “tif” sorry.  I should have caught that, after all in a few months it will be half a century since I created my first application not done for a class assignment. 
I have been doing some testing, I believe this is really a backwards compatibility issue, or fallout too many changes to QGIS project.  
I have been updating and revising this project thru several QGIS upgrades.  This is a project for the trails on new town park, which has been ongoing for several years, with many many revisions (add and remove layers).  When I build a new project containing the pieces, the print works without an issue. 
My recommendation is to close the issue as backwards compatibility from very old versions. 
Thank You
[qgis_#35242.zip](https://github.com/qgis/QGIS/files/4375807/qgis_.35242.zip)
