### ISSUE TITLE
The interpolate function/method of QgsGeometry fails for some line geometries

### ISSUE THREAD

**Issue by havatv** [qgis/QGIS#35249]
**Describe the bug**
For some line geometries, the interpolate function fails to find a point on the line.
I stumbled upon this when @nyalldawson asked me to use this function for the RandomPointsOnLine algorithm (#34631).
I may have a look at this bug myself, but can't promise anything in the near future.

**How to Reproduce**
I attach a GML file with only one feature / line (origin: Norwegian official road dataset, run through the *Fix geometries* algorithm to make sure the geometry is valid (same problem before running *Fix geometries*), MultiLineStringZ, EPSG:32632).
The interpolate function is not able to interpolate any point at distances longer than 550 meters along this line in my environment.
This is the GML file: [difficult_line.zip](https://github.com/qgis/QGIS/files/4366690/difficult_line.zip)
The bug also manifests itself when you try to run the *Interpolate point on line* and *Points along geometry* algorithms with this dataset as input. For distances of 551 meters and more, no points are generated. The first part of the multi-line is around 550 meters long, and located at the south end of the geometry. It goes "backward" (from north to south), and another part is "attached" close to the start of the line (I have not checked if this is the second part).

**QGIS and OS versions**

QGIS version | 3.11.0-Master | QGIS code revision | 2672c74393
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.6.2-CAPI-1.10.2 4d2925d6
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 10.12 (Ubuntu 10.12-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Ubuntu 18.04.4 LTS
Active python plugins | pluginbuilder3; plugin_reloader; SDEllipse; BOS; QGIS-ResourceSharing-master; LineDirectionHistogram; processing_taudem; processing_r; MetaSearch; processing; db_manager

**Additional context**

**Comment by nyalldawson** [comment]
Why are you running 3.11? That's an odd choice :laughing: 

Anyway, this was fixed a while back -- see https://github.com/qgis/QGIS/issues/34022

**Comment by havatv** [comment]
> Why are you running 3.11? That's an odd choice laughing
> 
> Anyway, this was fixed a while back -- see #34022

I thought I was running against master, but my "fork" had apparently not been updated for a while...  Sorry about that.

**Comment by nyalldawson** [comment]
No problem! Was just curious if there was a particular reason you were sticking to that version
