### ISSUE TITLE
WMS 1.0.0 not working on GetMap

### ISSUE THREAD

**Issue by Rastopapola** [qgis/QGIS#35263]
# Bug 
## Bug related resource
1. https://komserv4gdi.service24.rlp.de/ows/wms/07137068_Mayen?REQUEST=GetCapabilities&VERSION=1.0.0&SERVICE=WMS
1. https://geo4.service24.rlp.de/wms/rp_dop40.fcgi?REQUEST=GetCapabilities&VERSION=1.0.0&SERVICE=WMS

## To 1)
Running a GetMap operation results in a gray image, containing the exception message "msWMSLoadGetMapParams(): WMS server error. Missing required parameter FORMAT"

## To 2)
Running a GetMap operation results in a white image, containing the exception message "msWMSLoadGetMapParams(): Image handling error. Unsupported output format {}."

## Why do I think this is a QGIS bug?
Adding both services in a version > 1.0.0, e.g. 1.1.1 runs like a charm.

# Image for 1)
![image](https://user-images.githubusercontent.com/35961376/77316246-4d770380-6d09-11ea-8e22-c0cd3a82ba41.png)

# Image for 2)
![image](https://user-images.githubusercontent.com/35961376/77316831-6633e900-6d0a-11ea-9dbb-e2effaaaf21c.png)

**Comment by gioman** [comment]
@Rastopapola they work ok here on QGIS master on Linux:

![Screenshot_20200323_133654](https://user-images.githubusercontent.com/1951107/77322255-5ec10f80-6d0b-11ea-8546-a45992263012.png)

**Comment by Rastopapola** [comment]
Thanks for the quick feedback! 
Your response made me think again and I think I have an idea what this problem might cause in my case. I close this issue for now. If you won't here anything further, it worked ;)
