### ISSUE TITLE
multiprocessing module not woking

### ISSUE THREAD

**Issue by lidong74** [qgis/QGIS#35266]
I found that the python multiprocessing module does not wok in pyqgis :

from multiprocessing import Process
import qgis.core 
import qgis.gui 
def fun():
   print ('Hello world')
def main():
   p = Process(target=fun)       
   p.start()
   p.join()    
if __name__ == "__main__":
 main()

=====================
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00000b20 (most recent call first):

**Comment by gioman** [comment]
@lidong74 are you sure you are using the QGIS api the right way? Have you asked in the developers mailing list?

**Comment by lidong74** [comment]
I'm a beginner of qgis.  I'm writing a standalone python program using pyqgis and pyqt. Everything goes well except when I use the multiprocessing module. I haven't asked in the developers mailing list yet.

**Comment by lidong74** [comment]
> @lidong74 are you sure you are using the QGIS api the right way? Have you asked in the developers mailing list?
Hi,gioman. I'm a beginner of qgis. I'm writing a standalone python program using pyqgis and pyqt. Everything goes well except when I use the multiprocessing module. I haven't asked in the developers mailing list yet.

**Comment by gioman** [comment]
> I haven't asked in the developers mailing list yet.

@lidong74 please do it.

**Comment by Flgado** [comment]
@lidong74 hey. do you fine the solution for this problem? i have the same issue.
thanks
