### ISSUE TITLE
Is pandas package inside QGIS ?

### ISSUE THREAD

**Issue by jhemmi** [qgis/QGIS#35261]
On Windows installation from standalone installer 64bits,
pandas disappeared in QGIS version **3.10.3 LTR**
but was present in 3.10.0 (pandas version 0.25.1) and is present in 3.12.0. (pandas version 1.0.1)

from Python console inside QGIS:

`import pandas`
`pandas.__version__`

Is there a reason for this inconsistency  ? 
Is pandas package inside QGIS standalone installer ?

_to be link to # 32212 which is closed but defends the usefulness of pandas inside QGIS_

**Comment by gioman** [comment]
@jhemmi Please ask questions in the users or developers mailing lists, thanks.
