### ISSUE TITLE
"Delete geopackage" not working in Browser

### ISSUE THREAD

**Issue by ghtmtt** [qgis/QGIS#35262]
**Describe the bug**

Right click on a geopackge layer in the browser -> Delete geopackge layers.gpkg. Nothing happens

Deleting layers **within** a geopackage works perfectly.

QGIS master 3.13 compiled on linux debian sid

**Comment by gioman** [comment]
@ghtmtt missing QGIS version and Operating System.

**Comment by ghtmtt** [comment]
> @ghtmtt missing QGIS version and Operating System.

both are in the issue text

**Comment by gioman** [comment]
@ghtmtt original notification didn't included the necessary info:

![Screenshot_20200323_115527](https://user-images.githubusercontent.com/1951107/77314272-3cc09080-6cfd-11ea-80e6-e0f13d17076f.png)

**Comment by ghtmtt** [comment]
@gioman I was too fast to hit Enter. Then I edited the text, that's the reason ;)
