### ISSUE TITLE
Processing ignore file extension when exporting results

### ISSUE THREAD

**Issue by ghtmtt** [qgis/QGIS#35269]
**Describe the bug**
When saving the output to a file (no temporary), Processing is ignoring the file extension picked and put `gpkg`. Happens with all the algorithms.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/2884884/77329309-1eb75800-6d1e-11ea-900e-365c60bdf667.gif)

**QGIS and OS versions**

QGIS master 3.13 compiled on Linux Sid.

**Comment by gioman** [comment]
@ghtmtt is a regression?

**Comment by ghtmtt** [comment]
> @ghtmtt is a regression?

tested the same algorithm in QGIS 3.10 installed from package and **yes**, it is a regression.
