### ISSUE TITLE
the field calculator panel in the default Macintosh style has white font on a white background that does not allow you to see the functions.

### ISSUE THREAD

**Issue by aldo10362** [qgis/QGIS#35299]
the field calculator panel in the default Macintosh style has white font on a white background that does not allow you to see the functions.

**QGIS 3.12/3.10 and OSx Mojave**

**Additional context**

<img width="1446" alt="Schermata 2020-03-24 alle 11 22 40" src="https://user-images.githubusercontent.com/62595899/77414762-cf2a6800-6dc1-11ea-9808-884f473c18d3.png">

**Comment by gioman** [comment]
@aldo10362 default mac style is the dark one? Not here.

**Comment by aldo10362** [comment]
what do you mean?

**Comment by gioman** [comment]
> what do you mean?

that the QGIS dark theme is not the default QGIS one regardless of the platform. Have you tried the real default theme? Also see https://github.com/qgis/QGIS/pull/35300

**Comment by aldo10362** [comment]
with fusion default is fine, but not with macintosch default
