### ISSUE TITLE
Incoherence betwwen data-defined and color picker Hexadecimal color notation with alpha

### ISSUE THREAD

**Issue by SrNetoChan** [qgis/QGIS#35308]
**Describe the bug**

IMHO, there's an incoherence between the  Hexadecimal color notation between data-defined properties and the color picker when alpha is included.

Color data-defined properties expects a #AARRGGBB notation:

![image](https://user-images.githubusercontent.com/3607161/77458912-d455da00-6df6-11ea-8d13-4a770ef2a265.png)

While the Style panel shows colors as #RRGGBBAA

![image](https://user-images.githubusercontent.com/3607161/77460178-aa9db280-6df8-11ea-91ed-ad98a47cb14d.png)

Although this is not a blocker of any kind, users may find it confusing.

Related to this, looks like most browsers use the HTML #RRGGBBAA notation:

https://stackoverflow.com/a/31029864/1918685

**How to Reproduce**

**QGIS and OS versions**

QGIS 3.10.4

**Additional context**

**Comment by nyalldawson** [comment]
I agree that this is an issue, but it's also completely impossible for us to fix without major breakage to user's projects (because their data defined color expressions will suddenly change behavior). Closing as "wontfix" as a result.

**Comment by NathanW2** [comment]
Wow I have never noticed this before. Is that something we did or a Qt
thing.q

**Comment by nyalldawson** [comment]
We did it, but it's from ever since data defined symbology was introduced decades ago
