### ISSUE TITLE
fixgeometries does not run well in files

### ISSUE THREAD

**Issue by kozka** [qgis/QGIS#35306]
3.6.2-Noosa

native: fixgeometries
does not execute correctly if the destination is a file, but in memory if it works

**Comment by roya0045** [comment]
3.6.2 is quite outdated, please update and validate if the issue is still present.

**Comment by kozka** [comment]
if I have tried it with 3.12.1-București, it behaves the same, it works with a memory layer but not if I save it as a shapefile file

**Comment by kozka** [comment]
if I save a corrected geometry file in memory and it works fine as a shapefile it has the geometry error again

**Comment by gioman** [comment]
> if I save a corrected geometry file in memory and it works fine as a shapefile it has the geometry error again

@kozka please add sample data (specifying what/where the errors are)  as also precise/detailed steps (and options) you are using.

**Comment by kozka** [comment]
[capa_shp_con_error.zip](https://github.com/qgis/QGIS/files/4380048/capa_shp_con_error.zip)
This file comes from a plugin process that I created, and I may have to rethink and simplify it.
The file has the wrong geometry.
I apply native: fixgeometries if I save it in a shp it is still wrong.
but if I keep it in memory I can continue working with it.

**Comment by gioman** [comment]
>  The file has the wrong geometry.

@kozka this is very unclear. There are several errors that classify as "wrong geometry" (auto-intersections, duplicate nodes, etc.). Also I guess that you only a few features are affected. What has been asked was to specify what errors and where (what features) are affected.

Also what tool are you using?

vector > check geometries? (if you are using this tool what parameters are you using?)

processing  > fix geometries?

other?

**Comment by gioman** [comment]
@kozka according to PostGIS ST_IsValid all the geometries in your layer are ok.

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
