### ISSUE TITLE
Form tabs randomly becoming group boxes

### ISSUE THREAD

**Issue by dd-a** [qgis/QGIS#35304]
Hi, 
I'm working on a project stored in PostGIS with an attribute form made of more than 20 tabs and sub-groups, and since my recent upgrade to QGis 3.12.1 (on Mac OS), some tabs randomly become group boxes.  Then the 'show as group box' appears checked and when I uncheck it, it comes stubbornly back to 'checked'.   The only solution I found to make them become regular tabs again is to change the groupBox="1" to groupBox="0" in the project file directly.  This happens after modifying something (else) in the tab properties but so far I haven't been able to find what specifically triggers this change.

Opening the project in QGis 3.10.3 didn't solve the issue.

Version de QGIS | 3.12.1-București | Révision du code | 121cc00ff0
-- | -- | -- | --
Compilé avec Qt | 5.12.3 | Utilisant Qt | 5.12.3
Compilé avec GDAL/OGR | 2.4.1 | Utilisé avec GDAL/OGR | 2.4.1
Compilé avec GEOS | 3.7.2-CAPI-1.11.2 | Utilisé avec GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.28.0 | Running against SQLite | 3.28.0
Version du client PostgreSQL | 11.3 | Version de SpatiaLite | 4.3.0a
Version de QWT | 6.1.4 | Version de QScintilla2 | 2.11.1
Compilé avec PROJ | 5.2.0 | Fonctionne avec PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS 10.15

**Comment by Saijin-Naib** [comment]
Experiencing the same here with 3.12.1 on Win10
