### ISSUE TITLE
No PRJ written to shp

### ISSUE THREAD

**Issue by kerkovits** [qgis/QGIS#35301]
**How to Reproduce**

1. I open a geopackage file with layers in EPSG:23700. (The bug is reproducible with all my geopackeges).
2. Export->Save features as -> set to shapefile, all other settings default.
3. The shapefile is created, but no PRJ file is written, thus, the coordinate system is undefined.

**QGIS and OS versions**

QGIS verzió | 3.12.0-București | QGIS kód változat | cd141490ec
-- | -- | -- | --
Qt-val fordítva | 5.11.2 | Qt-val futtatva | 5.11.2
GDAL/OGR-rel fordítva | 3.0.4 | GDAL/OGR-rel futtatva | 3.0.4
GEOS-szal fordítva | 3.8.0-CAPI-1.13.1 | GEOS-szal futtatva | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL kliens verzió | 11.5 | SpatiaLite verzió | 4.3.0
OWT verzió | 6.1.3 | QScintilla2 Verzió | 2.10.8
PROJ-al fordítva | 6.3.1 | PROJ-al futtatva | Rel. 6.3.1, February 10th, 2020
OS verzió | Windows 10 (10.0)
Active python plugins | db_manager; MetaSearch; processing

**Additional context**

Lately QGIS does some strange transformation issues, when the project crs is EPSG:23700. Sometimes layers in the WebMercator appear 1000 km away from the correct location, but it jumps to the correct location if the layer properties dialog is opened. Results of geoprocessing tools sometimes not having crs information at all, etc. These are not reproducible, random errors, I tried to use a new profile, but these issues are coming back with ca. 25% probability. The bug reported here is the only one, I can always reproduce.

**Comment by gioman** [comment]
@kerkovits please attach sample data.

**Comment by kerkovits** [comment]
[temp.zip](https://github.com/qgis/QGIS/files/4375297/temp.zip)

**Comment by gioman** [comment]
> [temp.zip](https://github.com/qgis/QGIS/files/4375297/temp.zip)

@kerkovits cannot confirm on 3.12.1 and master on Windows.

**Comment by kerkovits** [comment]
It is still happening to me with the new version, however, I found a certain circumstance that can help finding the reason. QGIS is installed on the C:\ drive. When I save the shapefile to the C:\ drive, it usually works as expected, the prj is **rarely** missing (still not never). If i try to save it to the other disk (D:\), the prj is **always** missing.

**Comment by gioman** [comment]
> If i try to save it to the other disk (D:), the prj is **always** missing.

@kerkovits is D a local drive? or a network one? does it happen just on one specific machine? have  you tried a different machine and/or a new QGIS profile?

**Comment by kerkovits** [comment]
D: is a local drive. I tried it using a new profile. I am not able to try it on a different machine.

**Comment by gioman** [comment]
> . I am not able to try it on a different machine.

yes you can, is enough to test on a virtual machine (you can download the Windows ISO from Microsoft we site).

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
