### ISSUE TITLE
Random order of attributes in oracle feature query

### ISSUE THREAD

**Issue by tomass** [qgis/QGIS#35309]
**Description**
Say we have an Oracle layer with attributes A, B and C.
When querying features QGIS server randomly(?) orders A, B and C, f.e. these could be actual queries executed to fetch features:
SELECT geom, id, A, B, C...
SELECT geom, id, B, C, A...
SELECT geom, id, C, B, A...
This might look like a nuisance, but such randomness of queries does not allow to optimise large queries (use pre-generated plan) as Oracle expects the query to be stable.

**How to Reproduce**

1. Create a project with Oracle layer and some attributes
2. Execute WMS query (should also work with any query, even in Desktop) and write down the feature request query (order of attributes)
3. Execute the same WMS query again and note that the order of attributes in the query has changed.
4. Execute again - different (randomly) order again.

**QGIS and OS versions**

3.10-3.12 linux.

**Additional context**

I was able to temporarily fix this by changing _src/providers/oracle/qgsoraclefeatureiterator.cpp_
In function _openQuery_ i've added ordering of _mAttributeList_ (lines marked with plus sign) :

```
         return false;
     }
 
+#include <algorithm>
+std::sort(mAttributeList.begin(), mAttributeList.end());
     const auto constMAttributeList = mAttributeList;
     for ( int idx : constMAttributeList )
     {

```
  This is of course a bad solution, but should show the reason and principle of possible solution.

**Comment by elpaso** [comment]
I had a quick look to the code and I couldn't find any possible reason for the random order of the attributes, I'm not saying it doesn't happen of course.

**Comment by elpaso** [comment]
Ok, I might have found the randomness source ...
