### ISSUE TITLE
QGIS unexpectedly ended 

### ISSUE THREAD

**Issue by palexaraujo** [qgis/QGIS#35318]
Crash ID: c82cbf60cf9025798dcfa35edbc935944b70a596

Stack Trace

operatorQgsProcessingParameterTypeVectorLayer::description :
QgsArrowSymbolLayer::usedAttributes :
QgsGeos::isValid :
QgsSurface::isValid :
QgsGeometry::isGeosValid :
QgsPalLabeling::prepareGeometry :
QgsPalLayerSettings::registerFeature :
QgsVectorLayerLabelProvider::registerFeature :
QgsVectorLayerLabelProvider::stopRender :
QgsVectorLayerLabelProvider::stopRender :
QgsMapRendererParallelJob::renderLayerStatic :
QgsMapRendererParallelJob::renderingFinished :
QgsImageOperation::overlayColor :
QgsArchive::zip :
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.10.4-A Coru�a
QGIS code revision: 10bc9f2ff2
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.15063

**Comment by roya0045** [comment]
Any more details? scrennshot, data, steps, etc?

**Comment by gioman** [comment]
> Any more details? scrennshot, data, steps, etc?

@palexaraujo basically you **must** add all the information it is asked to you when you open the page/form to report an issue. Thanks.

**Comment by gioman** [comment]
Closing for lack of feedback.
