### ISSUE TITLE
QGIS unexpectedly ended

### ISSUE THREAD

**Issue by Shirleyzh** [qgis/QGIS#35320]
My system: Windows 10

Crash ID: 472ea3512682a3798d2cecc71f612973b1cc7185

Stack Trace

QMetaObject::activate :
QHttpMultiPart::qt_metacast :
QSslKey::operator!= :
QSslKey::operator!= :
QMetaObject::activate :
QAbstractSocket::proxyAuthenticationRequired :
QMetaObject::activate :
QAbstractSocket::proxyAuthenticationRequired :
QNetworkProxyQuery::networkConfiguration :
QMetaObject::activate :
QAbstractSocket::disconnected :
QAbstractSocket::canReadLine :
QNetworkProxyQuery::networkConfiguration :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
QEventLoop::exec :
QThread::exec :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.10.4-A Coru�a
QGIS code revision: 10bc9f2ff2
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment]
@Shirleyzh not enough informations: please detail what are the steps that lead to the crash, and also attach sample data/project if necessary. Also test using a new QGIS profile, no 3rd party plugins installed.

**Comment by Shirleyzh** [comment]
Hi Gioman,

Thanks for your reply. I uninstalled the older version of the QGIS and installed the newest OSGeo4W. The crash happens whenever I try to install new plugins.

**Comment by gioman** [comment]
> The crash happens whenever I try to install new plugins.

@Shirleyzh any plugin? from the QGIS public repo or from another one?

Have you tried with a new QGIS profile?

**Comment by Shirleyzh** [comment]
Hi Gioman,

Sorry I am at home now and it was my computer at work.  The plugin installation is from QGIS public repo.  I tried 2 to 3 plugins and they all caused the crash. 

I will try with a new QGIS profile tomorrow after I go back into the office.

Thanks for your time. I will let you know. 

Cheers, Shirley

**Comment by Shirleyzh** [comment]
Hi Gioman,
Thanks. I removed all the QGIS and OSGeo4W related files and folders and then started everything from scratch. This time it works. I think you are right. It was caused by the QGIS profile. 

Thanks, Shirley
