### ISSUE TITLE
Cannot use tiffile package in QGIS 3.10 but QGIS 3.4.5 working normally.

### ISSUE THREAD

**Issue by takhyun** [qgis/QGIS#35336]
Occured crash when starting QGIS after install tifffile package.
but QGIS 3.4.5 working.
How can I use tifffile package in QGIS 3.10.
please help.
thanks

## User Feedback

Occured crash after install tifffile package.
but QGIS 3.4.5 working.
How can I use tifffile package in QGIS 3.10.
please help.
thanks

## Report Details

**Crash ID**: [6f1c484cc77af1d32e01885ecd6f69e18d8d5d73]('https://github.com/qgis/QGIS/search?q=6f1c484cc77af1d32e01885ecd6f69e18d8d5d73&type=Issues')

**Stack Trace**
<pre>
QWidget::actions :
QgsCustomization::createTreeItemToolbars qgscustomization.cpp:630
QgsCustomization::updateMainWindow qgscustomization.cpp:714
QgisApp::QgisApp qgisapp.cpp:1341
main main.cpp:1353
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.3-A Coruna
QGIS code revision: 0e1f846438
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
@takhyun please add detailed steps that is needed to follow and that lead to the crash. Also attach sample data. Also try with a new QGIS profile.

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
