### ISSUE TITLE
Spatial Bookmark Manager Bad Behavior and Crashing App (3.10.4-A Coruña)

### ISSUE THREAD

**Issue by davidafuller01** [qgis/QGIS#35348]
**Describe the bug**
1. QGIS crashes after adding between 2 and 3 bookmarks (seems to vary).
2. Highlighting a single bookmark and hitting the trashcan will sometimes delete more than the selected bookmark.
3. Added bookmarks do not always appear in the list.
4. Saving a bookmark with a name identical to an existing bookmark that IS NOT SHOWING THE LIST (see 3.) sometimes crashes QGIS.
5. After a bookmark panel caused crash, when QGIS is restarted the panel isn't active. Have to toggle it back on again.

**How to Reproduce**
This is a pretty simple feature. See the various bad behaviors listed above.

**QGIS and OS versions**
QGIS version | 3.10.4-A Coruña | QGIS code revision | 10bc9f2ff2
-- | -- | -- | --
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.28.0 | Running against SQLite | 3.28.0
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS 10.15
Active python plugins | OnlineRoutingMapper; kmltools; quick_map_services; qgis_resource_sharing; autoSaver; LocatePoints; processing; db_manager; MetaSearch

**Comment by gioman** [comment]
@davidafuller01 I can't test on macOS in these days... have you tested on a different OS? It seems I can't replicate here on Linux.

**Comment by davidafuller01** [comment]
@gioman - I have not tried on another OS and do not have ready access to another machine.

**Comment by roya0045** [comment]
Windows 3.12 is fine

**Comment by saberraz** [comment]
"Retro" rendering was designed specifically for Windows 3.1x.

@roya0045 to set your rendering to retro to match your OS, simply type retro in the coordinate section in the status bar

**Comment by roya0045** [comment]
@saberraz I think you commented in the wrong issue.

**Comment by PeterPetrik** [comment]
Tried with nightly build https://qgis.org/downloads/macos/nightly2/qgis_nightly2_master_20200917_044804.dmg and all works as expected
![Screenshot 2020-09-17 at 15 49 46](https://user-images.githubusercontent.com/804608/93480228-7fa2a000-f8fd-11ea-8d68-1a6c7a8c3e56.png)

Please retest with nightl2 build and attach the detailed crash report from Apple if the problem still persists
