### ISSUE TITLE
Masking doesn't work for Merged Categories

### ISSUE THREAD

**Issue by oskarlin** [qgis/QGIS#35374]
**Describe the bug**

When merging several catagories in Layer styling, these merged layers will not be masked when activating masking layers.

**How to Reproduce**
1. Mege Categories
2. Try add masking

**Additional context**

**Comment by nyalldawson** [comment]
Can you clarify the steps required here? A sample project would help

**Comment by gioman** [comment]
Closing for lack of further feedback.
