### ISSUE TITLE
Method bounds() not invoked in custom QgsMarkerSymbolLayer

### ISSUE THREAD

**Issue by Christophe-FR-31** [qgis/QGIS#35377]
**Describe the bug**

In a custom QgsMarkerSymbolLayer for drawing large symbol, the override method bounds() is never call. Other override methods are called : clone(), hasDataDefinedProperties(), startRender(), renderPoint(), stopRender() and usedAttributes().

If I comment the bound() method, qgis doesn't complain but in C++ include, the method is declared as pure virtual.

**How to Reproduce**

Install the experimental plugin (provided with __init__.py, qmsl_bug.py and metadata.txt)
Create a shape with 2 points
Add a symbol layer "Marker Debug"
No trace of a call of bounds() in the log (qgis-log.txt)

**QGIS and OS versions**

Version de QGIS | 3.12.1-București | Branche de code de QGIS | Release Branche de code de QGIS.3
-- | -- | -- | --
Compilé avec Qt | 5.9.9 | Utilisant Qt | 5.9.9
Compilé avec GDAL/OGR | 3.0.4 | Utilisé avec GDAL/OGR | 3.0.4
Compilé avec GEOS | 3.8.0-CAPI-1.13.1 | Utilisé avec GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.13.0 | Running against SQLite | 3.13.0
Version du client PostgreSQL | 10.10 | Version de SpatiaLite | 4.3.0
Version de QWT | 6.1.4 | Version de QScintilla2 | 2.11.4
Compilé avec PROJ | 7.0.0 | Fonctionne avec PROJ | Rel. 7.0.0, March 1st, 2020
OS Version | Slackware 14.2
Extensions Python actives | plugin_reloader; marker-sympol-layer-bug; db_manager; processing; MetaSearch

**Additional context**
[metadata.txt](https://github.com/qgis/QGIS/files/4387501/metadata.txt)
[__init__.py.txt](https://github.com/qgis/QGIS/files/4387506/__init__.py.txt)
[qmsl_bug.py.txt](https://github.com/qgis/QGIS/files/4387508/qmsl_bug.py.txt)
[qgis-log.txt](https://github.com/qgis/QGIS/files/4387512/qgis-log.txt)

**Comment by nyalldawson** [comment]
This method is only called during labelling - try turning on labels for your layer, switching them to the "cartographic" placement mode and "from symbol bounds".

**Comment by Christophe-FR-31** [comment]
Ok, I believe this method is called in function like "Zoom to layer" or to know if a symbol should be drawn after a movement or zoom action.

**Comment by nyalldawson** [comment]
No, it's not. It's currently used **only** during labelling
