### ISSUE TITLE
Group statements when deleting from PostgreSQL

### ISSUE THREAD

**Issue by uclaros** [qgis/QGIS#35381]
**Feature description.**

Deleting 40000 features from a PostgreSQL layer results in 40000 different `delete from ... where id = ...` statements. On remote connections this causes 40000 times the overhead and connection latency.
A single `delete from ... where id in (... ...)` would probably be much faster for remote and slow connections.
**Additional context**

**Comment by gioman** [comment]
@uclaros I would say that this is bug.

**Comment by elpaso** [comment]
Well, technically it is not. An enhancement yes.

**Comment by uclaros** [comment]
> Well, technically it is not. An enhancement yes.

The code works as intended, the intention is bugged though!!!
