### ISSUE TITLE
QGIS can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by benmadin** [qgis/QGIS#35389]
**Checklist before submitting**

- [ X ] Search through existing issue reports and gis.stackexchange.com to check whether the issue already exists

**Describe the bug**

Warning message on attempting to open newly downloaded version QIS 3.12:
“QGIS3.12” can’t be opened because Apple cannot check it for malicious software.

**Steps, sample datasets and qgis project file to reproduce the behavior. Screencasts or screenshots welcome**

1. Download and install QGIS 3.12 on Apple running macOS Catalina Version 10.15.4
2. Double click to open
3. Receive error message

![Screen Shot 2020-03-27 at 05 29 08](https://user-images.githubusercontent.com/2987068/77698647-ee0c4280-6feb-11ea-8bf0-4bbe009152d2.png)

3. be surprised, having been installing MacOS versions for 10 years (thanks William)
4. Google and find solution
5. Knowing that there is a solution, and that the problem is partly I suspect a change in behaviour with by Apple, decide to report action as this would be a roadblock to many potential users.

**QGIS and OS versions**

QGIS version | 3.12.1-București | QGIS code revision | 121cc00ff0
-- | -- | -- | --
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.28.0 | Running against SQLite | 3.28.0
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS 10.15
Active python plugins | d3datavis; BoundingBox; timemanager; processing; db_manager; MetaSearch

**Additional context**

I realise that there is a work around, but I suspect for many people this would be more of a blocker than the old requirement to install multiple packages.

**Comment by benmadin** [comment]
And after submitting, I see that this is similar to four open issues :)

**Comment by gioman** [comment]
> And after submitting, I see that this is similar to four open issues :) 

@benmadin that were closed :) https://github.com/qgis/QGIS/issues/34018#issuecomment-578186707
