### ISSUE TITLE
Mean Coordinates algorithm does not recognize grouping field in graphical modeler

### ISSUE THREAD

**Issue by MrXsquared** [qgis/QGIS#35385]
**Describe the bug**
When running the Mean Coordinates algorithm through graphical modeler and using a Vector Field input as Unique ID field, the Unique ID is being ignored which results in a wrong output. The mean coordinate of all points is beeing built.

When running Mean Coordinates algorithm through processing toolbox as "standalone" and setting the same field as Unique ID, the output is correct. The mean coordinate of each group is beeing built.

**How to Reproduce**
[meanbug.zip](https://github.com/qgis/QGIS/files/4388404/meanbug.zip)
1. Create some points or use the one provided in attached zip file (CRS does not matter)
2. Create a field where these points shall be grouped by (field type does not matter)
3. Create a graphical model with two inputs:
Vector layer and Vector field
4. Add Mean Coordinates algorithm to this graphical model and set the Vector layer as input layer and the Vector field as Unique ID field
5. Run the model

**QGIS and OS versions**

QGIS 3.4.3 and 3.12.0 on Windows 10 64bit

**Additional context**
The model setup:
![grafik](https://user-images.githubusercontent.com/44526431/77668708-0ea0b200-6f84-11ea-8ae9-9e4e874ca279.png)

Running the model:
![grafik](https://user-images.githubusercontent.com/44526431/77668789-2a0bbd00-6f84-11ea-807c-cac0cda01da6.png)

Incorrect output:
![grafik](https://user-images.githubusercontent.com/44526431/77668873-47408b80-6f84-11ea-87ff-6115d01c2a62.png)

**Comment by nyalldawson** [comment]
Your model has the input field type parameter accepting a list of multiple fields:

![image](https://user-images.githubusercontent.com/1829991/77718580-ffc30980-702e-11ea-9ac3-4f82beed03e0.png)

The list of selected fields can't be handled by the mean coordinates algorithm, which expects a single field value only.

Solutions are:
1. Uncheck "accept multiple fields" for the field parameter if you don't actually require a selection of multiple fields

or 

2. Change the "Unique ID field" parameter value in the "Mean coordinate(s)" algorithm in your model to a "Pre-calculated value", and use an expression like `@field2[0]` to just get the first field name from the list

![image](https://user-images.githubusercontent.com/1829991/77718745-5c262900-702f-11ea-98d3-9f7e1771ec06.png)


Both solutions are confirmed working
