### ISSUE TITLE
QGIS rejects a custom CRS (which works fine in Postgis/Proj)

### ISSUE THREAD

**Issue by Brent-Wood** [qgis/QGIS#35392]
I have a new CRS ratified by EPSG in late 2019 as  EPSG::9191

It has not yet percolated into QGIS.

I have been using this as a custom CRS with QGIS 2.18 OK, and it works with R & Postgis (also proj libraries), but it fails with QGIS 3.10

The proj definition is:
 +proj=aea +lat_1=-30 +lat_2=-50 +lat_0=-40 +lon_0=175 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs

I have installed QGIS 3.10 and it rejects this definition - "This proj projection definition is not valid" and just says ERROR when testing it with 175/-40 (which should give the 0,0 coords that both QGIS v2.18 & Postgis v2.4 return - I have inserted it into Postgis spatial_ref_sys table as 27201)

select ST_ASText(ST_Transform(ST_SetSRID(ST_MakePoint(175,-40),4326),27201));
(returns)
POINT(0 0)

I can't see why it is rejected by QGIS, but works with Proj, so I'm assuming there is some filter in QGIS which is broken. I have tried teh list for help, but got no replies so am filing it as a bug.

**Comment by nyalldawson** [comment]
Which exact QGIS version is this? Which PROJ version?

**Comment by Brent-Wood** [comment]
resolved in 3.5+
This CRS =EPSG: 9191 not yet in the QGIS database, but proj parameters are:
+proj=aea +lat_1=-30 +lat_2=-50 +lat_0=-40 +lon_0=175 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs
