### ISSUE TITLE
CRS problems: EPSG code not correctly applied in QGIS 3.4 

### ISSUE THREAD

**Issue by zaw-shinoto** [qgis/QGIS#35395]
**Description**

I am working on a project in QGIS 3.4, the CRS is `JGD2011 / Japan Plane Rectangular CS II`; the correct EPSG code for my area is 6670. 

But on import into QGIS I get EPSG:102611, which seems not to exist. The projection is OK though. 

**When I just import the shapefile, I get the following information:**

```
epsg:102611
JGD_2011_Japan_Zone_2
領域：範囲が不明です
Proj4：+proj=tmerc +lat_0=33 +lon_0=131 +k=0.9999 +x_0=0 +y_0=0 +ellps=GRS80 +units=m +no_defs
```

The Japanese text that the extension is not known. 

**When I set the EPSG on import to EPSG:6670, I get the following information:**

```
epsg:6670
JGD2011 / Japan Plane Rectangular CS II
領域：129.76, 30.18, 132.05, 33.99
Proj4：+proj=tmerc +lat_0=33 +lon_0=131 +k=0.9999 +x_0=0 +y_0=0 +ellps=GRS80 +units=m +no_defs
```

The Japanese text sets the extension of the zone; this is correct. This EPSG code can be found in the EPSG code database; it is the code to use. 

**About the files I submit**

The shapefiles with buildings, groundpoints etc. are created from 4 tiles of .xml data. I submit the shapefile of the coastline, there are only two tiles in .xml concerend. The folders with the .xml data hold an additional .xml file that I add as well, both start with ".fmdid10-". 

Using the Japanese Windows software that the Japanese government provides, I can create the shapefile that I can import into QGIS. 

Best, 
Maria

[20190101-海岸線.zip](https://github.com/qgis/QGIS/files/4390841/20190101-.zip)
[xml-files.zip](https://github.com/qgis/QGIS/files/4390842/xml-files.zip)

**Comment by nyalldawson** [comment]
Please test with QGIS 3.10.4 -- 3.4 is no longer supported.

**Comment by zaw-shinoto** [comment]
I thought 3.4 is a long term release valid until autumn?

It needs some time and change for me to set up 3.10; there were some critical issues for our project that need testing first. 

In the meantime, could you not just import into your version and have a look at the layer info? It is a matter of less than a minute.

**Comment by nyalldawson** [comment]
> I thought 3.4 is a long term release valid until autumn?

No, it's EOLed - see https://www.qgis.org/en/site/getinvolved/development/roadmap.html

I've had a look at this data file.

The projection (.prj) file contains the definition:

```
PROJCS["JGD2011_Japan_Zone_2",GEOGCS["GCS_JGD_2011",DATUM["D_JGD_2011",SPHEROID["GRS_1980",6378137.0,298.257222101]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Transverse_Mercator"],PARAMETER["False_Easting",0.0],PARAMETER["False_Northing",0.0],PARAMETER["Central_Meridian",131],PARAMETER["Scale_Factor",0.9999],PARAMETER["Latitude_Of_Origin",33],UNIT["Meter",1.0]]
```

plugging this into `projinfo --identify` gives:

```
Identification match count: 25
EPSG:6669: 25 %
EPSG:6670: 25 %
EPSG:6671: 25 %
EPSG:6672: 25 %
EPSG:6677: 25 %
EPSG:6673: 25 %
EPSG:6674: 25 %
EPSG:6675: 25 %
EPSG:6676: 25 %
EPSG:6678: 25 %
EPSG:6679: 25 %
EPSG:6680: 25 %
EPSG:6681: 25 %
EPSG:6682: 25 %
EPSG:6687: 25 %
EPSG:6683: 25 %
EPSG:6684: 25 %
EPSG:6685: 25 %
EPSG:6686: 25 %
EPSG:6688: 25 %
EPSG:6689: 25 %
EPSG:6690: 25 %
EPSG:6691: 25 %
EPSG:6692: 25 %
ESRI:102598: 25 %
```

I.e. it's not an exact match for any known CRSes (25% is a very low confidence result - the threshold used by QGIS is 70%)

Let's have a look now at the definition of EPSG:6670: `projinfo EPSG:6670 -o WKT1:ESRI` gives:

```
PROJCS["JGD_2011_Japan_Zone_2",GEOGCS["GCS_JGD_2011",DATUM["D_JGD_2011",SPHEROID["GRS_1980",6378137.0,298.257222101]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Transverse_Mercator"],PARAMETER["False_Easting",0.0],PARAMETER["False_Northing",0.0],PARAMETER["Central_Meridian",131.0],PARAMETER["Scale_Factor",0.9999],PARAMETER["Latitude_Of_Origin",33.0],UNIT["Meter",1.0]]
```

The difference in the definitions stems from the PROJCS term. In your file you have "JGD2011_Japan_Zone_2", vs proj libraries definition of "JGD_2011_Japan_Zone_2" (an extra underscore)

If there's an issue, it's in the proj library. I've filed this as https://github.com/OSGeo/PROJ/issues/2099

**Comment by zaw-shinoto** [comment]
I see, I will change to 3.10 asap.

As for the problem with the CRS, thanks for filing this problem. I will comment and follow the case over there.

**Comment by nyalldawson** [comment]
Fixed upstream, thanks for reporting!
