### ISSUE TITLE
New user, installation issue

### ISSUE THREAD

**Issue by gibram10** [qgis/QGIS#35397]
Hi Guys,

I'm trying to install the program but is not working for me Im using MAc Catalina 10.15.4.
Thank you hope to hear from you soon.

<img width="453" alt="Screen Shot 2020-03-26 at 9 14 32 PM" src="https://user-images.githubusercontent.com/62735287/77721437-21c57900-6fa8-11ea-8584-dfb4ebb91fcc.png">
<img width="453" alt="Screen Shot 2020-03-26 at 9 14 32 PM" src="https://user-images.githubusercontent.com/62735287/77721455-2db13b00-6fa8-11ea-84c5-7c859a211dc0.png">

**Comment by agiudiceandrea** [comment]
@gibram10 try to Ctrl or right-click on it in Finder and select Open
See http://osgeo-org.1560.x6.nabble.com/QGIS-3-10-can-t-be-opened-on-Mac-td5432283.html

**Comment by roya0045** [comment]
https://github.com/qgis/QGIS/issues/34018#issuecomment-578186707

@Gustry should an option be added for this specific issue and point to the comment, this is occurring quite frequently

**Comment by Gustry** [comment]
I think a note should added on the QGIS website when they download the package.

**Comment by gioman** [comment]
> I think a note should added on the QGIS website when they download the package.

@gibram10 please add a ticket against the QGIS web site/documentation bug trackers.

**Comment by gibram10** [comment]
Nice, it works thanks guys!
