### ISSUE TITLE
Adding custom projection to have NEU doesn't work in versions after 3.8

### ISSUE THREAD

**Issue by antoniolocandro** [qgis/QGIS#35394]
**Describe the bug**

Custom projection worked in QGIS 3.8, I can't add it in newer versions included dev it doesn't matter what I do
**How to Reproduce**

![QGIS_PROJ_3 8](https://user-images.githubusercontent.com/4627073/77706819-08610480-6f89-11ea-8b91-f6dc14ae43b8.png)
![QGIS_PROJ_dev](https://user-images.githubusercontent.com/4627073/77706818-072fd780-6f89-11ea-9f20-2a49605c3412.png)

![QGIS_PROJ_dev2](https://user-images.githubusercontent.com/4627073/77706820-08610480-6f89-11ea-90aa-b73ae8930a69.png)

**Additional context**

**Comment by nyalldawson** [comment]
Try doing what the error suggests, and changing the format combo box from "proj" to "WKT".

**Comment by antoniolocandro** [comment]
Tried to WKT also get the same issue, tells me something about EPSG 4326 exists, actually I only need this as a workaround because a GML i am loading is written in lat,lon but apparently QGIS doesn't honor axis order

**Comment by antoniolocandro** [comment]
Error message trying WKT, only thing is that it worked before in 3.8 which I downloaded for the time being

![equivalent_wgs84](https://user-images.githubusercontent.com/4627073/77710477-b8d40600-6f93-11ea-8a32-3b29217b9c59.png)

**Comment by nyalldawson** [comment]
Yep - follow the suggestion from the error message again.

it's there for a reason!!
:wink:

**Comment by antoniolocandro** [comment]
My problem is related to this issue https://github.com/qgis/QGIS/issues/35393

As a workaround in QGIS 3.8 I used to be able to save this custom projection to swap coordinates of layers that were not correct, what would be the option in latest version, I would want to add +axis=neu for this layer while I can see what the issue is for the swap in the first place

I tried the suggestion

GEOGCRS["unknown",
    DATUM["unnamed",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]],
        ID["EPSG",6326]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433],
        ID["EPSG",8901]],
    CS[ellipsoidal,2],
        AXIS["latitude",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]],
        AXIS["longitude",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]]]

test works I want to invert 2,3 to 3,2
![test](https://user-images.githubusercontent.com/4627073/77770731-5ae30500-700b-11ea-9ef4-6a15a91623c0.png)

I am able to save it

But when I apply it to the layer, nothing happens to it (east and north should switch for visualization and this worked in QGIS 3.8) my data is in EPSG:4326 BTW. When I did this in QGIS 3.8 the features axis would swap
![viz](https://user-images.githubusercontent.com/4627073/77771526-697dec00-700c-11ea-8f79-21c3755ca92a.png)

Thanks for any ideas

**Comment by gioman** [comment]
> QGIS 3.8

QGIS 3.8 shipped with GDAL 2, QGIS 3 LTR and above ship with GDAL 3. It is a major change, you should first check if the issue lies in this underlying library.

**Comment by antoniolocandro** [comment]
Ok so reporting in the GDAL tracker would be the way to go I guess. Anyway this is happening at that level to be visualized in QGIS correct?

**Comment by gioman** [comment]
> Ok so reporting in the GDAL tracker would be the way to go I guess

if is confirmed the issue is there.

**Comment by antoniolocandro** [comment]
My use case is no longer needed as it was fixed upstream on the rendering part Just for general knowledge fixed upstream OSGeo/gdal#2356
