### ISSUE TITLE
QGIS server postgresql datasource getting error "invalid layer(s)"

### ISSUE THREAD

**Issue by aneer-anwar** [qgis/QGIS#35409]
Steps I followed for QGIS server Postgres integration are as follows:

1)I created a .qgs project using Postgres Datasource in QGIS desktop client. 
2)I edited .qgs file and added user and password for the Postgres in Datasource tag.
3)installed QGIS server and tested the same using another Spatialite .qgs which was working as expected.
4)installed postgresql-client
4)Added  properties in Apache conf file(sites-available)
         SetEnv PGSERVICEFILE /home/qgis/.pg_service.conf
	  FcgidInitialEnv PGPASSFILE "/home/qgis/.pgpass"
5)Reloaded and restarted Apache server
6)Still same result : invalid layer(s)
7)Converted the same project to spatialite and deployed again. Surprisingly was working as expected.
Is there anything i am missing for connecting QGIS server to a remote postgresql DB. Please help.

**Comment by gioman** [comment]
@aneer-anwar is this a question or a bug report?

**Comment by NyakudyaA** [comment]
Just try to connect to the database using 
psql service=name of connection.

These kind of questions are more suited to gis.stackexchange.com . In future state how you deployed QGIS etc(additional info) If it really is a bug

**Comment by aneer-anwar** [comment]
@gioman @NyakudyaA  Thank you for the quick response. yes this is a question not sure if its a bug. I followed all the steps given in official QGIS Server documentation to add Postgres Datasource to QGIS Server (Apache server). The steps I followed are given above. 
Unfortunately, nothing seems to be working. Don't know if I missed out anything.

**Comment by gioman** [comment]
> Unfortunately, nothing seems to be working.

@aneer-anwar does it work if for your postgis layers you use the basic authentication (username and password stored in the QGIS project)?

**Comment by aneer-anwar** [comment]
@gioman As @NyakudyaA suggested, connecting to Postgres as service worked as expected. but the other method using basic authentication didn't work showing error "Invalid layer(s)" even after having .pg_service and .pgpass. Please have a look at that. I am closing the issue as I got resolution from you.

**Comment by Gustry** [comment]
@aneer-anwar Your settings looks wrong:
```
SetEnv PGSERVICEFILE /home/qgis/.pg_service.conf
FcgidInitialEnv PGPASSFILE "/home/qgis/.pgpass"
```
https://docs.qgis.org/2.18/en/docs/user_manual/working_with_ogc/server/config.html#environment-variables  I can't find this note in the 3.10 version

**Comment by riccardoklinger** [comment]
Hi folks,
unfortunately I am facing the same issues here on my side. followed the [newest docs](https://docs.qgis.org/3.10/en/docs/training_manual/qgis_server/wms.html), added a layer to the world project that was originating from a postgis table. WMS was only repsonding with "Invalid Layers" maybe docs should be adjusted?! @aneer-anwar can you elaborate more on how you fixed it?
if I call `psql service=airports` in terminal it works fine.
all folders and files in /home/qgis are granted to www-data as the doc described.
my .pg_services.conf is:
```
[airports]
host=localhost
port=5432
dbname=gisdb
user=XX
password=YY
```
do I need to adjust the qgs file as well with only service definition?

**Comment by Gustry** [comment]
> do I need to adjust the qgs file as well with only service definition?

What do you mean? A Service definition file is useful only if you use it in your project.
How are your postgresql layers configured? With service? With login&password in the project?

**Comment by riccardoklinger** [comment]
tried both: service and basic authentication. I also tried to add the basic authentication params in the datasource tag of the layer in the saved .qgs project file. No luck for now. will try again with a fresh install
