### ISSUE TITLE
Search for short feature identifiers in the locator bar

### ISSUE THREAD

**Issue by m-kuhn** [qgis/QGIS#35418]
Currently, the locator feature filter only shows results once 3 or more characters have been typed.
This makes it impossible to find ids like 1, 20, 45, ab, etc.
By using a prefix, these are included but can be hidden because of the maximum result count of 6. (ie. 100, 1000, 2100, 111, 110, 3310 shown instead of 1).

Ideas:
 - order by relevance (ideally provider side for performance reasons)
 - for < 3 characters search for exact match only
 - introduce double quotes for exact match search `"1"` (not that intuitive)

**Comment by nyalldawson** [comment]
> for < 3 characters search for exact match only

+1

**Comment by uclaros** [comment]
> Currently, the locator feature filter only shows results once 3 or more characters have been typed.

For the record, this is not how it currently works. Results are fetched from the first typed character but are limited to 6 results with the *af* prefix and to 30 with the *f* prefix.

**Comment by m-kuhn** [comment]
... which hides away some results which are not retrievable.

![](https://user-images.githubusercontent.com/588407/77821916-33189d80-70ee-11ea-813a-98d09ccc11bb.gif)
