### ISSUE TITLE
DBManager return nothing when query ends with a semicolon

### ISSUE THREAD

**Issue by letoff** [qgis/QGIS#35426]
In version 3.12 and maybe others, in DBManager executing any SQL request that ends with a semicolon (like every sql statement in psql)  returns 0 line and no error message. This is very disturbing for someone learning QGis like me.

Expected behavior would be either an error message or silently removing the ';'

Tia.

**Comment by gioman** [comment]
Confirmed.

> This is very disturbing for someone learning QGis like me.

@letoff stick to LTR releases in this case 3.10.*.

**Comment by roya0045** [comment]
This should be done already as by  https://github.com/qgis/QGIS/blame/master/python/plugins/db_manager/dlg_sql_window.py#L436 Though I suspect that the changes related to comments might be altering something that prevent the ; from being removed.

**Comment by alexbruy** [comment]
Duplicates #34731
