### ISSUE TITLE
[Layer panel] - mysterious objects

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#35425]
Since **QGIS 3.12** I notice these strange objects in the layer panel, what are they? what are they for?? it's normal??

![image](https://user-images.githubusercontent.com/7631137/77825183-f6f23680-7107-11ea-8265-f0863c38ef3b.png)

**Comment by roya0045** [comment]
I'm pretty sure (99%) that this was already reported.

**Comment by pigreco** [comment]
> I'm pretty sure (99%) that this was already reported.

I can't find anything, also because I don't know what to look for. :-(

**Comment by gioman** [comment]
Duplicate of https://github.com/qgis/QGIS/issues/32029

**Comment by roya0045** [comment]
@gioman Thanks gio! I've looked yesterday and couldn't find it back.

**Comment by gioman** [comment]
> @gioman Thanks gio! I've looked yesterday and couldn't find it back.

no problem!

**Comment by Gustry** [comment]
Thanks. I also tried to find this ticket yesterday. Lesson learned again, screenshots are
not searchable ;-)
It's also in qgis 3.10

**Comment by gioman** [comment]
>  It's also in qgis 3.10

@Gustry there was not much discussion (in the mailing lists) about this change: https://github.com/qgis/QGIS/issues/32029#issuecomment-535854462
