### ISSUE TITLE
Can't save new line layer as SpatiaLite

### ISSUE THREAD

**Issue by vicpaine** [qgis/QGIS#35435]
Updated desktop to Coruna but when I tried to save a new line layer I got an error message (attached).  I tried redoing the layer as a shapefile which saved with no problem.  I still have Madeira on the Surface Book and this saves as SpatiaLite with no problem.

QGIS version | 3.10.3-A Coruña | QGIS code revision | 0e1f846438
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Windows 10 (10.0)
Active python plugins | AreaAlongVector; ImportPhotos; db_manager; MetaSearch; processing

![Qgis error message](https://user-images.githubusercontent.com/62830712/77844983-eb078280-71a2-11ea-9471-940c24c8f9c9.jpg)

**Comment by gioman** [comment]
@vicpaine please attach the problematic datasouce.

**Comment by vicpaine** [comment]
There is no data source file, I make new SpatiaLite layer, toggle editing, draw the wind farm boundary, click to finish, toggle editing.  This brings up save dialog which is where I get the error message.  If I follow the same procedure with a shapefile it saves with no errors.  As I said before Madeira saves Spatialite files, same procedure with no problem.

**Comment by vicpaine** [comment]
Hi
There is no data source, I start new spatialite layer (BrenigWindFarm), toggle editing, draw wind farm boundary, rt click when finished, toggle editing off, dialogue box to save, when I click save I get the error.  If I follow the same procedure but with shapefile it saves correctly.
Regards
Vic
V.J.Paine

On 29 Mar 2020, at 10:29 am, Giovanni Manghi <notifications@github.com> wrote:

﻿

@vicpaine<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvicpaine&data=02%7C01%7C%7C87d9e5b7ea5d4eeb2fbe08d7d3c3b6b8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637210709837434492&sdata=hq5gD1H3aEUrlJJniUwKnmYi%2BIXdQsSpnH0x1jBZPpU%3D&reserved=0> please attach the problematic datasouce.

**Comment by gioman** [comment]
> There is no data source file, I make new SpatiaLite layer, toggle editing, draw the wind farm boundary, click to finish, toggle editing. This brings up save dialog which is where I get the error message. If I follow the same procedure with a shapefile it saves with no errors. As I said before Madeira saves Spatialite files, same procedure with no problem.

@vicpaine I cannot replicate. A screencast showing all the steps you are following would help a lot. Thanks.

**Comment by vicpaine** [comment]
Sorry never done screencast. It sounds possible there is a corrupt file in my download.  I’m away from PC for a while will try deleting and downloading again when I return and let you know the result
Vic
V.J.Paine

On 29 Mar 2020, at 11:46 am, Giovanni Manghi <notifications@github.com> wrote:

﻿

There is no data source file, I make new SpatiaLite layer, toggle editing, draw the wind farm boundary, click to finish, toggle editing. This brings up save dialog which is where I get the error message. If I follow the same procedure with a shapefile it saves with no errors. As I said before Madeira saves Spatialite files, same procedure with no problem.

@vicpaine<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvicpaine&data=02%7C01%7C%7C8105886a650c40c00daa08d7d3ce76aa%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637210756008582669&sdata=3oTiUygcdO2VJIxdvRw5exWY8rv4%2BEAFwlThccMg1og%3D&reserved=0> I cannot replicate. A screencast showing all the steps you are following would help a lot. Thanks.

**Comment by gioman** [comment]
> Sorry never done screencast

google for:
screencastOmatic

**Comment by vicpaine** [comment]
Vic Paine has shared a OneDrive file with you. To view it, click the link below.
<https://1drv.ms/u/s!Ap9tfttWLwAF6jrTDrLkEwxWcH5U>
[https://r1.res.office365.com/owa/prem/images/dc-mpg_20.png]<https://1drv.ms/u/s!Ap9tfttWLwAF6jrTDrLkEwxWcH5U>
Recording #1.mp4<https://1drv.ms/u/s!Ap9tfttWLwAF6jrTDrLkEwxWcH5U>

Link as too big for github


________________________________

**Comment by gioman** [comment]
> Recording #1.mp4<https://1drv.ms/u/s!Ap9tfttWLwAF6jrTDrLkEwxWcH5U>

@vicpaine I can't replicate on my testing machine (same OS as yours) following your exact steps. Please try with a new QGIS profile, no 3rd party plugins installed.

**Comment by vicpaine** [comment]
New profile didn't make any difference.  Deleted from PC and downloaded again.  Now working correctly.   Only difference I can see is that new one is 3.10.4-A Coruña whereas problem one was 3.10.3-A Coruña, unless it was just one or more corrupted files.

Vic

________________________________

**Comment by vicpaine** [comment]
Deleted from PC and downloaded again.  Now working correctly.   Only difference I can see is that new one is 3.10.4-A Coruña whereas problem one was 3.10.3-A Coruña, unless it was just one or more corrupted files.
