### ISSUE TITLE
"Identify features" tool does not return more than a single feature in 3D map view

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#35436]
I have a 3d map view that I zoomed out enough to get more than one feature clicked when I use the identify tool. But it seems to return nothing (when more than one feature should be caught) or a single feature.

3.10-3 on ubuntu 18.04

**Comment by Pedro-Murteira** [comment]
@DelazJ I can no longer replicate this on QGIS 3.16.14 and 3.22.1. Can you attach a data sample so I can investigate further?
