### ISSUE TITLE
Select by expression returns erroneous results with integer field division for shapefiles

### ISSUE THREAD

**Issue by she-weeds** [qgis/QGIS#35449]
As raised in [this GIS.SE post](https://gis.stackexchange.com/questions/356528/problem-with-select-by-expression-in-qgis/356529), Select by Expression does not seem to work properly when a division expression includes an integer field, unless `to_real()` or `eval()` is wrapped around the division. 
It cannot find any matching features if using the greater than (`>`) or equal operator and returns all features if using the less than (`<`) operator.

Field calculator works normally; this mainly seems to be an issue with Select by Expression.

Curiously, this seems to be a file-specific isssue. I have only encountered this with shapefiles and not had the same issue with spatialite, geopackage or csv with the exact same dataset. This is despite QGIS showing all the integer fields as Integer64 in each data format (except CSV where it is String).

---
See the following very simple test on the attached shapefile to reproduce the bug in QGIS 3. 

I should get two results for "int1"/"int2" = 1. No results.
![division_int](https://user-images.githubusercontent.com/41975056/77865697-6f2d3900-727b-11ea-8e7d-8adc0feafcb4.JPG)

I should get two results for "int1"/"real2" = 1. No results.
![division_int_real](https://user-images.githubusercontent.com/41975056/77865702-76ecdd80-727b-11ea-8a72-f80a21aa999e.JPG)

However I do get the one result for "real1"/"real2" = 1, which is correct.
![division_real](https://user-images.githubusercontent.com/41975056/77865705-79e7ce00-727b-11ea-95c6-51b464995e85.JPG)

I have also attached gpkg, csv, and spatialite versions of the exact same dataset (exported from shapefile) which, if you run these tests, will return the desired results.

[division.zip](https://github.com/qgis/QGIS/files/4400253/division.zip)

**QGIS and OS versions**
QGIS version
3.12.1-București
QGIS code revision
121cc00ff0
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.1
Running against PROJ
Rel. 6.3.1, February 10th, 2020
OS Version
Windows 10 (10.0)

**Comment by troopa81** [comment]
There is an issue in Shapefile ogr driver. I proposed a [PR](https://github.com/OSGeo/gdal/pull/2531) to fix this.

For the record: 
- Gpkg use sqlite expression evaluation system, so it works
- Csv file try to use the ogr expression evaluation system and fails, so it fallback on QGIS one and works
- Shapefile (and potentially other ogr supported format) use the ogr evaluation expression and fails.
