### ISSUE TITLE
6e9735d1beaecc91fcd9344212f0b6daeb33aeae

### ISSUE THREAD

**Issue by lippemartinsm** [qgis/QGIS#35441]
Bug appeared when trying to export to dxf.

Stack Trace

QgsMapLayer::type qgsmaplayer.cpp:129
QgsDxfExportDialog::cleanGroup qgsdxfexportdialog.cpp:526
QgsDxfExportDialog::cleanGroup qgsdxfexportdialog.cpp:534
QgsDxfExportDialog::cleanGroup qgsdxfexportdialog.cpp:534
QgsDxfExportDialog::QgsDxfExportDialog qgsdxfexportdialog.cpp:441
QgisApp::dxfExport qgisapp.cpp:6511
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1607
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.10.4-A Coru�a
QGIS code revision: 10bc9f2ff2
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
@lippemartinsm please use  a meaningful title and add the **detailed** steps that lead to the problem, attaching sample data if necessary, thanks.

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
