### ISSUE TITLE
[print layouts] table, datetime field not correctly evaluated

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#35443]
I loaded a table (CSV) into the print layout,
known that the data field (datetime) is not correctly evaluated in the expression constructor.
Although an error appears, the expression works.

![image](https://user-images.githubusercontent.com/7631137/77856431-7d397600-71f7-11ea-9b3a-d3d6427a4c38.png)

I attach project with data

https://github.com/qgis/QGIS/files/4397674/dpc-covid19-ita-province.zip

**Comment by agiudiceandrea** [comment]
@pigreco, with QGIS 3.12.0 (standalone installer 3.12.0-2) on Windows 10 64 bit the error is not diplayed
![image](https://user-images.githubusercontent.com/16253859/77894875-350d6880-7276-11ea-9a27-2f11d15ff91f.png)

**Comment by gioman** [comment]
Also no error on 3.12 on OSGeo4W.

![Screenshot_20200330_124934](https://user-images.githubusercontent.com/1951107/77909232-eb784a00-7284-11ea-80f2-5dea460f2b2c.png)

**Comment by pigreco** [comment]
## OSGeo4W64 WIn10 QGIS 3.12 New profile

in the composer the data field (datetime) looks like this:

![image](https://user-images.githubusercontent.com/7631137/77910436-66def900-728f-11ea-9bbc-55eec45ceba7.png)

**Comment by gioman** [comment]
> in the composer the data field (datetime) looks like this:

and?

**Comment by pigreco** [comment]
@gioman 

from the screenshot
`Output preview: 99`

**Comment by gioman** [comment]
> Output preview: 99

![Screenshot_20200330_131820](https://user-images.githubusercontent.com/1951107/77911572-f0d79380-7288-11ea-981d-3feb31227f3d.png)


please try with a clean/new QGIS profile.

**Comment by pigreco** [comment]
> ## OSGeo4W64 WIn10 QGIS 3.12 New profile
> in the composer the data field (datetime) looks like this:
> 
> ![image](https://user-images.githubusercontent.com/7631137/77910436-66def900-728f-11ea-9bbc-55eec45ceba7.png)

as written here, I used new profile,

Then, the test must be done in the layout area

**Comment by gioman** [comment]
> Then, the test must be done in the layout area

I did it, but you didn't attached a full project, just the table. Plase attach a full sample project as it may be relevant.

**Comment by pigreco** [comment]
In a simple project it works.

Sorry for the lost time.
