### ISSUE TITLE
PostGIS Connection synchronization between DBManager & Browser 

### ISSUE THREAD

**Issue by onsummer** [qgis/QGIS#35451]
When I add a postgis connection in browser panel, if I do not restart QGIS, postgis connection list would not refresh in DBManager.

QGIS version: 3.12.0
OS: Windows 10 64bit 1903

I'm sorry that I cannot show you screenshot because, when I restart QGIS, they have synchronized...
This is not a big problem, but it has an impact on the operation, such as when I need to add a new PostGIS connection and perform an import operation.
tks.

**Comment by Gustry** [comment]
> QGIS version: 3.12.0

Update, it has already been fixed.
Duplicate of https://github.com/qgis/QGIS/issues/34862
