### ISSUE TITLE
Crash when closing QGIS

### ISSUE THREAD

**Issue by stragu** [qgis/QGIS#35457]
## User Feedback

I only tried to close QGIS, without saving changes I made to a project.
I did not use a plugin.
The edits I did to the project were adding an OSM basemap from the XZ Tiles dropdown, and import a vector layer from a umap file (which did not work, which was to be expected, and ended up showing one empty node). However, the crash only occurred when I closed QGIS, so I don't think it is linked to what modifications I mad to the project.

## Report Details

**Crash ID**: [188e441b487e48d0ebd7d07fe63c7c16edf44e05]('https://github.com/qgis/QGIS/search?q=188e441b487e48d0ebd7d07fe63c7c16edf44e05&type=Issues')

**Stack Trace**
<pre>
QWidget::actions :
QMenu::clear :
QgisApp::refreshProfileMenu qgisapp.cpp:2682
QMetaObject::activate :
QMetaObject::activate :
QFileSystemWatcher::`default constructor closure' :
QMetaObject::activate :
QFileSystemWatcher::directoryChanged :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
QMessageBox::showEvent :
QMessageBox::critical :
QgisApp::QgisApp qgisapp.cpp:788
main main.cpp:1353
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.3-A Coru�a
QGIS code revision: 0e1f846438
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
@stragu please try with a new QGIS profile, no 3rd party plugins installed.

**Comment by gioman** [comment]
>  QGIS Version: 3.10.3-A Coru�a

also update to the latest point release.

**Comment by stragu** [comment]
Oh I didn't realise 3.10.4 was out. I will install that, and if I run into it again, I will provide more details, but closing it for now before I forget and it lingers. The issue has only happened once and I'm not sure I will be able to reproduce.
