### ISSUE TITLE
Standalone installer for QGIS 3.12 incorrectly displays the release name as Bucure?ti

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/QGIS#35453]
**Describe the bug**

Standalone installer for QGIS 3.12 'București' incorrectly displays the release name as Bucure?ti instead of București, at least on Windows 10 64 bit localized in Italian
![image](https://user-images.githubusercontent.com/16253859/77886387-10f75a80-7269-11ea-94fe-56bd1cf51558.png)

The same doesn't occur with the standalone installer for QGIS 3.10 'A Coruña'.

This is probably caused by the fact that while the `ñ` char (U+00F1 Latin Small Letter N with tilde) is mapped in the Latin-1 Supplement and Windows-1252 codepage, whereas the `ș` char (U+0219 Latin Small Letter S with Comma Below) is not.

**Comment by Gustry** [comment]
Side note @agiudiceandrea as you are reporting a few bugs on QGIS, better to install 3.12.1. You are installing 3.12.0 on your screenshot.
As always, a lot of bugs are fixed in the first bug fix releases.

**Comment by agiudiceandrea** [comment]
Additional information:
the standalone installer for QGIS 3.12 incorrectly sets the following Values in the Windows Registry:

- VersionName = "Bucure?ti" in HKLM\SOFTWARE\QGIS 3.12

- DisplayName = "QGIS 3.12.0 'Bucure?ti'" in HKLM\Software\Microsoft\Windows\CurrentVersion\Uninstall\QGIS 3.12

It seems no commits have been merged before the release of 3.12.1 to address this issue https://github.com/qgis/QGIS/compare/final-3_12_0...final-3_12_1

**Comment by agiudiceandrea** [comment]
The same occurs with QGIS 3.12.1 standalone installer
![image](https://user-images.githubusercontent.com/16253859/78079587-b5ce8080-73ac-11ea-8027-18e98b34b0bb.png)

**Comment by agiudiceandrea** [comment]
@jef-n, I have done some tests, and it seems that it is possible to solve the problem in the following way (building the installer on Windows):
- 1
a. use NSIS version 2.50.0-Unicode (https://github.com/jimpark/unsis/releases)
or
b. use NSIS version 3.05 and add the option `Unicode true` in QGIS-Installer.nsi

- 2
and in the creatensis.pl perl script, use the modules `Win32::Unicode::Process` and `Encode qw(decode)` and change the system calls to makensis as:
```
$cmd = decode( "UTF-8", "makensis -DINNER=1 -DUNINSTALLERDEST='$instdest' -DINSTALLER_NAME='makeuinst.exe' $args" );
systemW($cmd);
```
```
my $cmd = decode( "UTF-8", "makensis -DINSTALLER_NAME=$installerbase.exe $args" );
systemW($cmd);
```

![image](https://user-images.githubusercontent.com/16253859/78218396-01248400-74be-11ea-9a47-7d40ee792901.png)
![image](https://user-images.githubusercontent.com/16253859/78218647-6d9f8300-74be-11ea-81f4-16d3c0f3a46b.png)

**Comment by agiudiceandrea** [comment]
Hi @jef-n, did you find a fix for this bug as the new release QGIS 3.12.2 'București'  is approaching?

**Comment by agiudiceandrea** [comment]
@jef-n, the same issue occurs with QGIS 3.12.2-1 standalone installer on Windows 10 localized in Italian
![image](https://user-images.githubusercontent.com/16253859/79701095-8ec3ea00-829a-11ea-9e4c-01f7fc149042.png)

**Comment by jef-n** [comment]
if it had been used - 3.12.2-1 was created with master's creatensis.pl.  Fixed in 3.12.2-2

**Comment by agiudiceandrea** [comment]
Thanks @jef-n. With 3.12.2-2 installer the "?" is gone, but now there is a normal `s` instead of `ș` or `ş`.

![image](https://user-images.githubusercontent.com/16253859/79977675-f21e6980-849e-11ea-8723-0db0c59b529c.png)

**Comment by agiudiceandrea** [comment]
Same behavior with QGIS-OSGeo4W-3.12.3-1-Setup-x86_64.exe: there is a normal `s` instead of `ș` or `ş`.
![image](https://user-images.githubusercontent.com/16253859/82152132-9c4f9e00-985f-11ea-83d8-b92f5977506b.png)
