### ISSUE TITLE
[WMS] Upper level layer not selectable with newest version

### ISSUE THREAD

**Issue by Rastopapola** [qgis/QGIS#35460]
# Bug behaviour
In the previous versions of QGIS I was able to load the top-level layer of a WMS. It looks like all existing layers of a WMS are now shown to the user - which is of course nice - but the upper level layers can not be added to the current view. The double click just opens the list of subelements. There is no right-click context menu and selecting the upper level layer and clicking on the button "Add selected layer" does not do anything.

# Preview
A gif of the behaviour can be seen [here](https://i.ibb.co/6FBqzJL/Peek-2020-03-30-16-10.gif)

# Resource
The used WMS in the gif is [this one](http://geo5.service24.rlp.de/wms/karte_rp.fcgi?REQUEST=GetCapabilities&VERSION=1.1.1&SERVICE=WMS)

# My QGIS version
Updated today, 30th March 2020

QGIS-Version | 3.12.1-București | QGIS-Codeversion | 121cc00ff0
-- | -- | -- | --
Kompiliert gegen Qt | 5.11.3 | Laufendes Qt | 5.11.3
Kompiliert mit GDAL/OGR | 2.4.0 | Läuft mit GDAL/OGR | 2.4.0
Kompiliert mit GEOS | 3.7.1-CAPI-1.11.1 | Läuft mit GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Kompiliert mit SQLite | 3.27.2 | Läuft mit SQLite | 3.27.2
PostgreSQL-Client-Version | 11.6 (Debian 11.6-0+deb10u1) | SpatiaLite-Version | 4.3.0a
QWT-Version | 6.1.4 | QScintilla2-Version | 2.10.4
Kompiliert mit PROJ | 5.2.0 | Läuft mit PROJ | Rel. 5.2.0, September 15th, 2018
BS-Version | Debian GNU/Linux 10 (buster)
Aktive Python-Erweiterungen | db_manager; processing; MetaSearch

# Thanks!

**Comment by nyalldawson** [comment]
See https://github.com/qgis/QGIS/pull/35148
