### ISSUE TITLE
Temporary output folder path does not exist

### ISSUE THREAD

**Issue by gubuntu** [qgis/QGIS#35477]
**Describe the bug**

After closing the Options dialog I get this error:

Wrong value for parameter "Temporary output folder path":

Specified path does not exist:
/private/var/folders/8b/12slfx955yj25xt6x1_zjz8m0000gn/T/processing_45159720cf0043389031aaf549b4979e

**QGIS and OS versions**

QGIS version | 3.10.3-A Coruña | QGIS code revision | 0e1f846438
-- | -- | -- | --
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.28.0 | Running against SQLite | 3.28.0
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS 10.15
Active python plugins | QgisModelBaker; SpreadsheetLayers; lrs; QuickOSM; VectorBender; quick_map_services; stac_browser; Discovery; qfieldsync; qchainage; OSMDownloader; parcel_plugin; lizmap; openlayers_plugin; Projestions; mmqgis; processing_circuitscape; mapswipetool_plugin; Mergin; travel_time_platform_plugin; nominatim_locator_filter; timemanager; processing; db_manager; MetaSearch

**Comment by alexbruy** [comment]
Please check with latest 3.10/master, this should be fixed.

**Comment by gubuntu** [comment]
It's not fixed in 3.10.5

**Comment by alexbruy** [comment]
Did you try with clean profile?

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
