### ISSUE TITLE
Option to also duplicate the data when duplicating scratch layer

### ISSUE THREAD

**Issue by uclaros** [qgis/QGIS#35487]
**Feature description.**
I find quite often myself, when working on a temporary scratch layer, the need to modify data in a layer, but also keep the original. I don't want to have it stored in a file since it's only temporary, so I do select all -> copy -> paste as temporary scratch layer.
I think it would be quite useful if *duplicate layer* on a temporary scratch layer would spawn a dialog asking if I want to get a deep copy including data.
This would also help with people who might still misunderstand that it normally points to the same data.

**Additional context**
On second thought, this could also be applied to other layers too: duplicate into a new temporary scratch layer.

**Comment by elpaso** [comment]
I think it's a nice feature but I'm not a big fan of the popups that stand in my way. I would probably prefer a context menu option.

**Comment by nyalldawson** [comment]
Since a few versions we already deep copy the features on duplicating a scratch layer. I think this report is redundant....

**Comment by uclaros** [comment]
@nyalldawson  You're right, I guess I missed that!
The message still says *Layer duplication complete : Note that it's using the same data source.* though...
But even if the message is corrected, the fact that doing the same action (duplicate layer) to different types of layers (file vs memory) has different results (keep vs copy data source) is IMHO not the best UX wise and can lead to user confusion.

**Comment by roya0045** [comment]
@uclaros so you're suggesting to have duplicate behave on temp/scratch as it does for any layer and to add something like "Copy in memory" to create a temp/scratch layer from the selected layer?

**Comment by nyalldawson** [comment]
> The message still says Layer duplication complete : Note that it's using the same data source. though...

That's fixed in master now too
