### ISSUE TITLE
add r.basin to the QGIS Processing toolbox

### ISSUE THREAD

**Issue by valterhydrodynamics** [qgis/QGIS#35481]
r.basin
GRASS GIS plugin would be better if we can compute "r.basin" from the GRASS plugin console or from the QGIS Processing toolbox

![imagem](https://user-images.githubusercontent.com/43525314/78019146-0dd29c00-7347-11ea-9984-cc30347c50b9.png)

**Comment by PedroVenancio** [comment]
Valter,

r.basin is a GRASS addon/extension, and so, does not make sense to include the description file of this module in Processing, as it needs to be manually installed in GRASS. That is, it will not work in QGIS, unless the user install it in GRASS. 

So, first you would ask GRASS dev team to include r.basin in GRASS as a default module, if it makes sense to them, and only then include the description file in QGIS, to call it.

**Comment by valterhydrodynamics** [comment]
Thanks for the answer Pedro

Cumprimentos,
*Valter Albino -* Geógrafo Físico, M.Sc.
Modelação H&H / Riscos ambientais / OT&U
www.valteralbino.wixsite.com/hydrodynamics


Pedro Venancio <notifications@github.com> escreveu no dia terça, 31/03/2020
à(s) 14:30:
