### ISSUE TITLE
[Already fixed - reapeared bug] SQL syntax error while saving project in PostgreSQL version 9.4 (and older)

### ISSUE THREAD

**Issue by phidrho** [qgis/QGIS#35485]
I'm using latest version QGIS 3.12.1 on Linux and Windows.

While trying to save project file in PosgreSQL, I tried both from Ubuntu and Windows and got following error:
```
Unable to save project to storage posgresql://localhost:5432?authcfg…
Unable to insert or update project (project=my_project) in the destination table on the database. Maybe this is due to table permissions (user=). Please contact your database admin.
```

In PostGIS log there is a following message:
```
2020-03-31T16:13:32     WARNING    Erroneous query: INSERT INTO "zgrade".qgis_projects VALUES ('moj_projekt', ('{ "last_modified_time": "' || (now() at time zone 'utc')::text || '", "last_modified_user": "' || current_user || '" }')::jsonb, E'\\x504b0304140...0') ON CONFLICT (name) DO UPDATE SET content = EXCLUDED.content, metadata = EXCLUDED.metadata; returned 7 [ERROR: syntax error at or near "ON"
             LINE 1: ...764504b05060000000002000200b0000000eb1500000000') ON CONFLIC...
              ^
             ]
```

I did a reasearch and seems that problem is in PostgreSQL version ([I'm using 9.4.1](https://www.postgresql.org/docs/9.4/sql-insert.html)) which doesn't support `ON CONFLICT` SQL syntax which is implemented since [PostgreSQL ver. 9.5](https://www.postgresql.org/docs/9.5/sql-insert.html).

So for connections to older versions of PostgreSQL project saving should have different approach, or at least we should have a limitation/warning in GUI that it's not possible because of database version.

This seems to be fixed already in #28966 but the bug is still here.

**Comment by gioman** [comment]
> This seems to be fixed already in #28966 but the bug is still here.

@phidrho not sure if I got it right, but that patch goal seems was to block/disable to save the project in the DB if the detected version was lower than 9.5

**Comment by phidrho** [comment]
Yes, I also understood it shoud work that way, but nothing was disabled.

**Comment by phidrho** [comment]
I already uninstalled database and installed new version... fortunately, DB was empty so I didn't have to migrate anything.

My PostgreSQL 9.4.1 was installed on Windows server 2008, not on Linux, don't know if that fact has anything with detecting DB version.

**Comment by gioman** [comment]
> My PostgreSQL 9.4.1 was installed on Windows server 2008, not on Linux, don't know if that fact has anything with detecting DB version.

I got the same using QGIS LTR (3.10) and PostgreSQL 9.3 on a Linux server.
