### ISSUE TITLE
Docker image qgis:final-3_10_4_disco: Couldn't load plugin 'MetaSearch' (various python modules missing)

### ISSUE THREAD

**Issue by strk** [qgis/QGIS#35480]
The docker image for qgis:final-3_10_4_disco, when started, fails to load MetaSearch plugin due to lack of `jinja2` python module on the system. Sounds like something the official image should include ?

**Comment by strk** [comment]
@3nids I see your name as maintainer of the dockerfile. What do you think can be done about this ? Shall I send a PR against the 3.10 branch to fix that, to see it fixed in final-3_10_5_something ?

**Comment by strk** [comment]
Sorry for the typo: it was the `jinja2`, not `ninja2` package being missed

**Comment by strk** [comment]
Also `pygments` is missing, and I guess a number of other ones. Shall the docker image either NOT include (or enable) the plugin or provide those modules too ?

**Comment by 3nids** [comment]
> Shall I send a PR against the 3.10 branch to fix that, to see it fixed in final-3_10_5_something ?

yes please do

**Comment by strk** [comment]
It looks like there are other errors in the dockerfile, but maybe I'm not supposed to build it via `docker build -f qgis.dockerfile  .` from under the `.docker` directory ? How else ?


This is what I get with the above:
```
 ---> Running in 55e2dc71dda0
CMake Error: The source directory "/QGIS" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
Removing intermediate container 55e2dc71dda0
 ---> b11f62584070
Step 17/24 : ARG DELETE_CACHE=FALSE
 ---> Running in fd78d07cce64
Removing intermediate container fd78d07cce64
 ---> 069046911195
Step 18/24 : RUN if [[ ${DELETE_CACHE} == TRUE ]]; then rm /QGIS; fi
 ---> Running in f9242e114558
/bin/sh: 1: [[: not found
```

**Comment by 3nids** [comment]
indeed
have a look at https://github.com/qgis/QGIS/blob/master/.ci/travis/docker_image/script.sh#L37-L43

**Comment by strk** [comment]
How about turning that into a Makefile target, rather than keep it buried inside .travis ? Or is it available already ?

**Comment by 3nids** [comment]
> How about turning that into a Makefile target, rather than keep it buried inside .travis ? Or is it available already ?

I am not sure if a Makefile is worth 2 lines in the script above.
But as said before, I'm quite open to improving the situation of these docker images.

But, as discussed they might be more suited into a dedicated repo where they are builds on some CI.
The question of the branching still makes sense though, but I guess everything would be much clearer.

**Comment by strk** [comment]
Ok, running it from the proper "context dir" still shows the `/bin/sh: 1: [[: not found` error, but anyway I filed PR #35486 to add the jinja and pygments modules (but did not test, as every single test seems to require having to build qgis again from scratch, which takes an hour or so)

**Comment by strk** [comment]
The PR was merged so I'm closing this. Is a new docker image tag planned for upload ? Latest tag is 3_10_5
