### ISSUE TITLE
MODIS_NITK not getting installed properly

### ISSUE THREAD

**Issue by civilianmanyu** [qgis/QGIS#35501]
Couldn't load plugin 'modis_nitk' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'pyhdf' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.12/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/abhib/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\modis_nitk\__init__.py", line 35, in classFactory
    from .modis_nitk import MODISNITK
  File "C:/PROGRA~1/QGIS3~1.12/apps/qgis/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/abhib/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\modis_nitk\modis_nitk.py", line 35, in 
    from pyhdf.SD import SD, SDC
  File "C:/PROGRA~1/QGIS3~1.12/apps/qgis/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'pyhdf'

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.12.1-București București, 121cc00ff0 

Python Path:
C:/Users/abhib/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\wnt
C:/Users/abhib/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\WaterNetAnalyzer-master
C:/Users/abhib/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\contour
C:/PROGRA~1/QGIS3~1.12/apps/qgis/./python
C:/Users/abhib/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/abhib/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.12/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS3~1.12\apps\Python37
C:\PROGRA~1\QGIS3~1.12\apps\Python37\Scripts
C:\Program Files\QGIS 3.12\bin\python37.zip
C:\PROGRA~1\QGIS3~1.12\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.12\apps\Python37\lib
C:\Program Files\QGIS 3.12\bin
C:\PROGRA~1\QGIS3~1.12\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.12\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.12\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.12\apps\Python37\lib\site-packages\Pythonwin
C:/Users/abhib/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/abhib/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\go2streetview
C:\Users\abhib\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\go2streetview\res
.

**Comment by nyalldawson** [comment]
This needs reporting to the plugin author, not qgis
