### ISSUE TITLE
Problem reprojecting rasters in 54019 and 54042 CRSs

### ISSUE THREAD

**Issue by murialex** [qgis/QGIS#35512]
In QGIS 3.12, the Winkel Tripel projection working on the fly but Winkel II is not working.
The Winkel II on the fly coordinate transformation is not implemented yet or there is a bug?

**Comment by gioman** [comment]
@murialex please add detailed steps, and sample data.

**Comment by murialex** [comment]
Steps: 
1. Add data in QGIS in EPSG:3857 or EPSG :4326 coordinate systems (any data);
2. Change project CRS to ESRI: 54019;
3. The loaded data will disappear, and won't show on zoom in. For vector data is possible to show some polygons and give an error: Exception ”forward transform of (inf, inf) Error: Fallback transform failed” ;
Same steps for ESRI: 54042...and everything is fine.

**Comment by gioman** [comment]
@murialex 

![Screenshot_20200401_181720](https://user-images.githubusercontent.com/1951107/78166711-1e693c00-7445-11ea-8400-bb531a47af4b.png)


this is why we ask to add sample data. Thanks.

**Comment by murialex** [comment]
This is what happening with Natural Earth na_110m_land.shp data:
![image](https://user-images.githubusercontent.com/8098983/78168653-f84d9700-7458-11ea-95ae-f5e11350d61e.png)

**Comment by murialex** [comment]
And try to visualize Google Hybrid layer with project CRS set to ESRI: 54019.

**Comment by gioman** [comment]
> This is what happening with Natural Earth na_110m_land.shp data:

@murialex please attach data or add  link for a direct download. thanks.

**Comment by murialex** [comment]
[ne_110m_land.zip](https://github.com/qgis/QGIS/files/4416806/ne_110m_land.zip)

**Comment by gioman** [comment]
> This is what happening with Natural Earth na_110m_land.shp data:

@murialex 

![Screenshot_20200401_185924](https://user-images.githubusercontent.com/1951107/78170480-ed8c0580-744a-11ea-8708-70ce64731831.png)

in the layer options, under "rendering" you have enable layer simplification, disable it.

**Comment by gioman** [comment]
@murialex I see that it seems that there are issues reprojecting rasters in the CRSs you say, but not vectors. I also your observation?

**Comment by murialex** [comment]
After disable layer simplification, Natural Earth na_110m_land.shp, it show up fine! Thank You!
Layers from QuickMapServices plugin don't show. This raster SRTM data don't show also.
[n43_e019_1arc_v3_bil.zip](https://github.com/qgis/QGIS/files/4416935/n43_e019_1arc_v3_bil.zip)

**Comment by rouault** [comment]
Failure to use EPSG:54019 (Winkel II) with raster was due to the lack in PROJ of implementation of the inverse projection for Winkel II. Now added for PROJ 7.1 in https://github.com/OSGeo/PROJ/pull/2243

**Comment by Golok** [comment]
Hello,

Despite being listed in the [changelog for QGIS 3.14](https://www.qgis.org/en/site/forusers/visualchangelog314/index.html), I still can't output rasters with the Winkel Tripel projection.

I updated to 3.16, but the bug persists… I have no problem to output vector layers, but rasters disappear as soon as the preview reaches the end of longitudes (see screenshots below).

![Screenshot 2020-11-25 at 18 34 45](https://user-images.githubusercontent.com/278053/100263206-7e20d400-2f4d-11eb-8cbc-cf5c13290e91.png)
![Screenshot 2020-11-25 at 18 34 57](https://user-images.githubusercontent.com/278053/100263215-80832e00-2f4d-11eb-9d4e-4bc010e6c8a0.png)

My working environment is the following:

Mac OS Mojave 10.14.6
QGIS 3.14

Thank you in advance for any help.

**Comment by murialex** [comment]
I confirm the issue that has not been resolved and persists in my case too. I suppose that the origin of the problem is in the PROJ library.
Environment:
Wondows 10, QGIS 3.16

**Comment by kannes** [comment]
The inverse projection as Winkel Tripel (ESRI:54042) is not supported in PROJ yet: https://proj.org/operations/projections/wintri.html

ESRI:54019 is supported since Proj 7.1 as mentioned above: https://github.com/qgis/QGIS/issues/35512#issuecomment-634052334

I too would love to be able to use rasters in Winkel Tripel. @rouault would you mind if I opened a feature request at Proj for it or is there something that would not make it possible?

**Comment by rouault** [comment]
> @rouault would you mind if I opened a feature request at Proj for it or is there something that would not make it possible?

I haven't looked at if there would be theoretical impossibiliies. Feel free to open a feature request

**Comment by kannes** [comment]
Hm, above issue turned out to be a documentation issue. Proj does support the necessary inverse projection for ESRI:54042.

But it does not seem to work in QGIS as people have shown above. Maybe this issue should be reopened as being only half fixed?
