### ISSUE TITLE
QGIS crashes when synchronizing data from QField back to QGIS

### ISSUE THREAD

**Issue by BoswachterMarc** [qgis/QGIS#35513]
## User Feedback

QGIS crashes each time when I use QFieldSync, trying to synchronize from QField back to QGIS...
I will try re-installing the plugin QField and eventually try a new, clean profile.
It worked previously...

## Report Details

**Crash ID**: [f0c4c96a23232118b74e84e91452753115b2bf99]('https://github.com/qgis/QGIS/search?q=f0c4c96a23232118b74e84e91452753115b2bf99&type=Issues')

**Stack Trace**
<pre>
QgsSymbolLayerUtils::estimateMaxSymbolBleed :
QgsMapCanvasAnnotationItem::updateBoundingRect :
QgsMapCanvasAnnotationItem::updatePosition :
QgsMapCanvas::updateCanvasItemPositions :
QMetaObject::activate :
QgsMapCanvas::setExtent :
QgsMapCanvas::readProject :
QMetaObject::activate :
QgsProject::readProject :
QgsProject::readProjectFile :
QgsProject::read :
PyInit__core :
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.2-A Coru�a
QGIS code revision: d4cd3cfe5a
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.3
Running against GDAL: 3.0.3

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by BoswachterMarc** [comment]
![Knipsel3](https://user-images.githubusercontent.com/57868975/78176628-161cfb00-745d-11ea-9f56-68dd80473ed4.PNG)
![Knipsel2](https://user-images.githubusercontent.com/57868975/78176632-16b59180-745d-11ea-8254-7c8936fd646f.PNG)
![Knipsel](https://user-images.githubusercontent.com/57868975/78176634-174e2800-745d-11ea-8a87-16fb39d1d4a3.PNG)

**Comment by roya0045** [comment]
Pretty sure this should be files in QFIELD rather than QGIS

**Comment by BoswachterMarc** [comment]
Ok, I will post it in that section. Thank you.

**Comment by roya0045** [comment]
But its always when importing data from QFIELD?

**Comment by gioman** [comment]
> QFieldSync

@BoswachterMarc file the ticket in the qfieldsync tracker, if the qfield devs say that is a qgis issue we can reopen this one.

**Comment by rouault** [comment]
Reopening. If it crashes QGIS, it is a QGIS bug

**Comment by rouault** [comment]
Ah sorry, this is likely a bug in the plugin qgfieldsync. Closing again. Sorry for the noise
