### ISSUE TITLE
Options dialog wrong title

### ISSUE THREAD

**Issue by elpaso** [qgis/QGIS#35510]
See `| QGIS Server |` in raster properties dialog title, actually it takes the title of the first selected tab and carries it around.

![Update_on_match_modes](https://user-images.githubusercontent.com/2663775/78025121-21d7c700-7362-11ea-993b-cc5ededa0121.png)

**Comment by Samweli** [comment]
I confirm this issue is on master and QGIS 3.10.

**Comment by Samweli** [comment]
Hi @elpaso, I have look at this issue and commenting lines https://github.com/qgis/QGIS/blob/75ddf3c7a6a7cb77b962dcb84abef9d36dbc2832/src/gui/raster/qgsrasterlayerproperties.cpp#L504 and https://github.com/qgis/QGIS/blob/75ddf3c7a6a7cb77b962dcb84abef9d36dbc2832/src/gui/raster/qgsrasterlayerproperties.cpp#L735 seems to fix this issue, not quite sure about the regressions though.

**Comment by Samweli** [comment]
Hi @Gustry, can you happen to know the cause of this issue?
