### ISSUE TITLE
Wrong page size when exporting layout as Geospatial PDF (no issue when exporting as normal PDF)

### ISSUE THREAD

**Issue by molig** [qgis/QGIS#35522]
In the layout manager I set a custom page dimension 1209x861mm but when I export as pdf I get a page 6718 x 4784mm
![Screenshot 2020-04-02 16 10 26](https://user-images.githubusercontent.com/63057226/78259283-c1c95800-74fc-11ea-8196-cdf872a6b8b7.png)
QGIS version 3.12.1

**Comment by gioman** [comment]
@molig please attach a sample project + sample data.

**Comment by molig** [comment]
@gioman thanks for your reply. What should I attach? I can't attach th qgz file here

**Comment by gioman** [comment]
> @gioman thanks for your reply. What should I attach? I can't attach th qgz file here

@molig you can attach zip file. Please attach a zip containing the project -with the layout- and also the necessary sample data.

**Comment by molig** [comment]
@gioman here the zip folder. thank you!
[TEST.zip](https://github.com/qgis/QGIS/files/4425930/TEST.zip)

**Comment by gioman** [comment]
> @gioman here the zip folder. thank you! 

@molig can't confirm

![Screenshot_20200403_120039](https://user-images.githubusercontent.com/1951107/78353875-bf213e00-75a2-11ea-8321-08f0c4ecc204.png)

**Comment by molig** [comment]
@gioman at thi link https://www.dropbox.com/s/t3xcpfqmnanlbvm/Layout%20prova.flv?dl=0 you can find the screen record of pdf exporting operations I have just done.  Can you please give a look? May you contact me by email  noalponte @gmail. com? thanks

**Comment by gioman** [comment]
> t thi link https://www.dropbox.com/s/t3xcpfqmnanlbvm/Layout%20prova.flv?dl=0 you can find the screen record of pdf exporting operations I have just done

you are exporting with the option "export as Geospatial PDF" enabled, in this case I confirm your observation. If you uncheck that option you get the expected page size.

**Comment by BenjaminRiley** [comment]
It seems like this has been fixed as of v3.16.4. I'd been using a DPI of 72 and forcing vector exports to work around this issue, but I can raise the DPI and still get the expected A4/A3 page size on the PDF now.
