### ISSUE TITLE
Projects with custom CRS on Windows

### ISSUE THREAD

**Issue by Dkrav-UA** [qgis/QGIS#35527]
**Describe the bug**
Opening a project with custom CRS on Windows displays "Unknown CRS" or empty.
**How to Reproduce**

1. Create an empty project.
2. Set custom CRS for the project.
3. Reopen the project.
![UnknownCRS](https://user-images.githubusercontent.com/16414895/78291471-1e913680-752e-11ea-8dd4-8836e70619e2.jpg)
![UnknownCRS2](https://user-images.githubusercontent.com/16414895/78292054-1e456b00-752f-11ea-9f1b-737d84525203.jpg)

**QGIS and OS versions**

QGIS version | 3.12.1-București | QGIS code revision | 121cc00ff0
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Windows 7 SP 1 (6.1)
Active python plugins | changeDataSource; ClusterPoints; concavehull; FreehandRasterGeoreferencer; gml_application_schema_toolbox; Go2NextFeature3; in4; open-cadastre-qgis3; open_500_qgis3_xyz; plugin_reloader; qgis2web; qtiles3; SRTM-Downloader; SuperLabeling; topomap; db_manager; MetaSearch; processing

**Additional context**

On Ubuntu 18.04 everything is OK.

**Comment by gioman** [comment]
> Set custom CRS for the project.

@Dkrav-UA do you mean that you have created a custom CRS and then used it as project CRS?

if yes, can add the details of your custom CRS?



> On Ubuntu 18.04 everything is OK.

same identical QGIS  version and steps followed?

**Comment by Dkrav-UA** [comment]
> 
> 
> > Set custom CRS for the project.
> 
> @Dkrav-UA do you mean that you have created a custom CRS and then used it as project CRS?
> 
> if yes, can add the details of your custom CRS?
> 
> > On Ubuntu 18.04 everything is OK.
> 
> same identical QGIS version and steps followed?
QGIS on Ubuntu:  QGIS version: 3.12.1-București, QGIS code revision: 121cc00ff0

Custom projection: +proj=tmerc +lat_0=0 +lon_0=25.875 +k=1.00003628 +x_0=39905.02 +y_0=-5331005.956 +ellps=krass +towgs84=23.92,-141.27,-80.9,-0,0.35,0.82,-0.12 +units=m +no_defs

**Comment by gioman** [comment]
Confirmed.

**Comment by nyalldawson** [comment]
You need to change your custom CRS definition from being a "proj" definition to a "wkt" type definition. Proj definitions are effectively deprecated as they are lossy and are no longer recommended.

I've confirmed that this all works as expected if you change the drop down for "format" for your custom crs to "wkt":

![image](https://user-images.githubusercontent.com/1829991/82314845-c050e200-9a0d-11ea-92be-e5713c364087.png)
