### ISSUE TITLE
QGIS Application Crash

### ISSUE THREAD

**Issue by NicolasStephney** [qgis/QGIS#35521]
After running the following code:
    QgsApplication.setPrefixPath('D:\Programs\QGIS 3.12', True)
    qgs = QgsApplication([], False)
    qgs.initQgis()

    window = CrimeMap()
    window.show()
    window.raise_()
    window.setupMapLayers()
    window.setupMapTools()

    exitcode = qgs.exec_()
    QgsApplication.exitQgis()

My program crashes if I remove the QgsApplication lines it runs no problem. The unexpected end is as follows.

Crash ID: 2235b0dc7e9dc6836e7162e65b0f968b8dac6609

Stack Trace

QgsStyleProxyModel::QgsStyleProxyModel qgsstylemodel.cpp:872
QgsStyleItemsListWidget::setStyle qgsstyleitemslistwidget.cpp:143
QgsSymbolsListWidget::QgsSymbolsListWidget qgssymbolslistwidget.cpp:42
QgsSymbolSelectorWidget::layerChanged qgssymbolselectordialog.cpp:533
QMetaObject::activate :
QItemSelectionModel::setCurrentIndex :
QAbstractItemView::setCurrentIndex :
QgsSymbolSelectorWidget::QgsSymbolSelectorWidget qgssymbolselectordialog.cpp:306
QgsSingleSymbolRendererWidget::QgsSingleSymbolRendererWidget qgssinglesymbolrendererwidget.cpp:59
QgsSingleSymbolRendererWidget::create qgssinglesymbolrendererwidget.cpp:32
QgsRendererPropertiesDialog::rendererChanged qgsrendererpropertiesdialog.cpp:251
QMetaObject::activate :
QWidgetLineControl::`default constructor closure' :
QComboBox::setCurrentIndex :
QComboBox::setCurrentIndex :
QgsRendererPropertiesDialog::syncToLayer qgsrendererpropertiesdialog.cpp:384
QgsRendererPropertiesDialog::QgsRendererPropertiesDialog qgsrendererpropertiesdialog.cpp:122
QgsLayerStylingWidget::updateCurrentWidgetLayer qgslayerstylingwidget.cpp:434
QMetaObject::activate :
QListWidgetItem::`default constructor closure' :
QMetaObject::activate :
QItemSelectionModel::setCurrentIndex :
QListWidget::setCurrentRow :
QgsLayerStylingWidget::setLayer qgslayerstylingwidget.cpp:259
QMetaObject::activate :
QgsMapLayerComboBox::layerChanged moc_qgsmaplayercombobox.cpp:209
QMetaObject::activate :
QAbstractItemModel::endInsertRows :
QSortFilterProxyModel::insertRows :
QSortFilterProxyModel::sortRole :
QSortFilterProxyModel::`default constructor closure' :
QMetaObject::activate :
QAbstractItemModel::endInsertRows :
QgsMapLayerModel::addLayers qgsmaplayermodel.cpp:172
QMetaObject::activate :
QgsProject::layersAdded moc_qgsproject.cpp:1142
QMetaObject::activate :
QgsMapLayerStore::layersAdded moc_qgsmaplayerstore.cpp:314
QgsMapLayerStore::addMapLayers qgsmaplayerstore.cpp:99
QgsProject::addMapLayers qgsproject.cpp:3127
QgsProject::addMapLayer qgsproject.cpp:3165
meth_QgsProject_addMapLayer sip_corepart3.cpp:35134
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyEval_EvalCodeEx :
PyEval_EvalCode :
PyArena_Free :
PyRun_StringFlags :
PyImport_Import :
PyImport_Import :
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyImport_Import :
PyImport_Import :
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1609
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.12.0-Bucure?ti
QGIS code revision: cd141490ec
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

Can anyone help me solve this?

**Comment by gioman** [comment]
@NicolasStephney please edit the subject/title to a more meaningful one, thanks.

**Comment by gioman** [comment]
@NicolasStephney you also should ask in the developers mailing list if you are making a correct use of the api.

**Comment by roya0045** [comment]
I get this stack trace:

QEventDispatcherWin32::processEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1609
BaseThreadInitThunk :
RtlUserThreadStart :

**Comment by nyalldawson** [comment]
There's insufficient information to diagnose this -- we'd need a self-contained script which we can test with.

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
