### ISSUE TITLE
QGIS compile problem in Ubuntu 16.04

### ISSUE THREAD

**Issue by forest21000** [qgis/QGIS#35534]
Hello,every!I am compiling QGIS-3.10 in Ubuntu 16.04 ,Qt 5.9.6,python 3.7.1,PyQt5 5.14.1,SIP 4.19.14.

I get an error:
sip: Unable to find file "QtCore/QtCoremod.sip"
python/CMakeFiles/python_module_qgisanalysis.dir/build.make:616: recipe for target 'python/analysis/sip_analysispart0.cpp' failed
make[2]: [python/analysis/sip_analysispart0.cpp] Error 1
make[2]: Deleting file 'python/analysis/sip_analysispart0.cpp'
CMakeFiles/Makefile2:4056: recipe for target 'python/CMakeFiles/python_module_qgisanalysis.dir/all' failed
make[1]: * [python/CMakeFiles/python_module_qgis__analysis.dir/all] Error 2
Makefile:160: recipe for target 'all' failed

![image](https://user-images.githubusercontent.com/2012752/78308558-5a9eb880-757b-11ea-97ff-eea8f6f8b6f8.png)

I don't know how to solve the problem,Tks for your help!

**Comment by forest21000** [comment]
my compile evn is this:
![image](https://user-images.githubusercontent.com/2012752/78308890-45765980-757c-11ea-842d-ce4deded9935.png)

**Comment by gioman** [comment]
@forest21000 please ask questions on the users or developers mailing lists. Thanks!
