### ISSUE TITLE
A new way to build QGIS and all its dependencies from scratch

### ISSUE THREAD

**Issue by Sinan81** [qgis/QGIS#35545]
Hi. I am a volunteer contributor for the software project [Spack](https://github.com/spack), an HPC package manager. Using this tool, it is possible to build QGIS and all of its direct and indirect dependencies from scratch using a single line of command. I thought this might be useful to some, especially to QGIS developers, and wanted to let you guys know so that you might consider adding it to the list of QGIS build/installation methods.

Once Spack is setup like:
```
git clone https://github.com/spack/spack.git
source spack/share/spack/setup-env.sh
```
One can build QGIS and all its dependencies via a single line of command like
```
spack install qgis
```
In practice, one might need to issue a command involving some hints for dependency resolution:
```
spack install qgis ^gdal@2.4.2 ^libgeotiff@1.4.3 ^py-pyproj@1.9.6 ^netcdf-c+mpi ^mesa~llvm
```
This will not be necessary in the upcoming releases of Spack.

Once it is built, one can use the package like
```
$ spack find qgis
==> 7 installed packages
-- linux-centos7-skylake / gcc@7.4.0 ----------------------------
qgis@3.8.1  qgis@3.10.3  qgis@3.10.3  qgis@3.10.3  qgis@3.10.4

-- linux-centos7-x86_64 / gcc@8.2.0 -----------------------------
qgis@3.8.1  qgis@3.8.1

$ spack load qgis@3.10.4

$ which qgis
/mnt/local/spack/opt/spack/linux-centos7-skylake/gcc-7.4.0/qgis-3.10.4-hc7uhdochwjmx4v2dzy2zzewit2vr2ov/bin/qgis
```

**Feature description.**

List an alternative build method in documentation.

**Comment by m-kuhn** [comment]
Interesting.
Does this also work for windows/macOS (etc)?

**Comment by gioman** [comment]
Isn't this better suited for a discussion on the developers mailing list?

**Comment by roya0045** [comment]
From the docs it seems that spack doesn't support windows at the moment.

And I agree with gioman that this should be moved, unless a PR is made to add this to the docs as a followup.

**Comment by gioman** [comment]
> And I agree with gioman that this should be move

@Sinan81 feel free to open a PR against QGIS docs. Thanks!

**Comment by serdarkocerr** [comment]
Hi,
I have been trying install QGIS so I decided to use spack. As you mentioned, spack was cloned and set environment(setup-env.sh).
Then run 'spack install qgis'  command
While build llvm-12.0.1 I have faced below issue:
FAILED: tools/clang/lib/ASTMatchers/Dynamic/CMakeFiles/obj.clangDynamicASTMatchers.dir/Registry.cpp.o

So do you have any suggestion?

stack version : 0.19.0.dev0
gcc: 7.3.1

**Comment by Sinan81** [comment]
You might want to use a release version of spack as opposed to cloning the development branch. Also, I encourage you to create an issue on Spack repo.
