### ISSUE TITLE
Map names get swapped when duplicating a layout

### ISSUE THREAD

**Issue by vvmalbre** [qgis/QGIS#35543]
I created a layout using two map windows. To each map I attached a scale bar and a legend.

When duplicating the layout window, map 1 became map 2 and map 2 became map 1. Scale bar and legend automatically switched to the new name (which is correct). Nevertheless the change of the map names is confusing.

**Comment by gioman** [comment]
> When duplicating the layout window, map 1 became map 2 and map 2 became map 1.

@vvmalbre I can't replicate on 3.12.1, please attach a sample project that shows the issue.

**Comment by vvmalbre** [comment]
Find attached a sample workspace as well as a PDF with some screenshots. Layout_2 is a duplicate of Layout_1. You will find them identically since after closing and reopening a workspace the same thing happens (map 1 will be map 2). In the screenshot you can see how it was originally.

Hope you can replicate it. Thanks!

By the way: I'm working with QGIS 3.10.4 LTR

[Layout.zip](https://github.com/qgis/QGIS/files/4437007/Layout.zip)

**Comment by iona5** [comment]
i can reproduce both behaviors (renumber on duplicate layout, renumber on reload of project) in 3.14.1 and latest master (acc750c7e3).

During addition of map layers these are naturally numbered in ascending order (oldest to newest). But when a layout is created (through duplication of an existing layout or loading from the project) the map layers with no ID are numbered from the latest addition to the oldest, so in reverse.

**Comment by Pedro-Murteira** [comment]
@vvmalbre Hello, I've tested this on QGIS 3.22.3. and I can't reproduce it. The maps/legends/scale bars stay exactly the same on the duplicated layout. Did you come across this issue more recently?
