### ISSUE TITLE
QGIS crashed using raster calculator

### ISSUE THREAD

**Issue by paulajonsson** [qgis/QGIS#35546]
Each time when I try to use raster calculator when trying to merge two raster layers, QGIS crashed with following "Crash ID" 7bcc30951f3e00b6a6328b8dd535558e56b39d47. In the proccess I try to sum to raster layers using layer + layer and uses one of the layers as reference. I then try to save the output file as an own and when clicking run I get the "QGIS crashed".

**Comment by paulajonsson** [comment]
Tried to do another raster calculation, but QGIS still crashes. 

This is the report detalis: 
Crash ID: 7bcc30951f3e00b6a6328b8dd535558e56b39d47


Stack Trace


memcmp :
GDALRasterBand::IRasterIO :
GDALRegister_GTiff :
GDALRasterBand::RasterIO :
QgsRasterCalculator::processCalculation :
PyInit__analysis :
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_sip :
CPLStringList::empty :
PyInit__core :
QgsProcessingAlgorithm::runPrepared :
QgsProcessingAlgRunnerTask::run :
PyInit__core :
QgsTask::start :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.4.0-Madeira
QGIS code revision: 4a4b62ed19
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.3.2
Running against GDAL: 2.3.2



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by nyalldawson** [comment]
3.4 is too old, and is no longer supported

**Comment by gioman** [comment]
> 3.4 is too old, and is no longer supported

@paulajonsson if the issue persist after upgrading to the latest 3.10 or 3.12 then please attach sample data and the formula you are using.

**Comment by paulajonsson** [comment]
I have now downloaded 3.10 and the crashing problem stoped :), but I still cannot calculate. Each time I try (using this modul, Iam at step 11, https://www.qgistutorials.com/en/docs/3/multi_criteria_overlay.html) to merge these two layers, i get this message 

"The following layers were not correctly generated.<ul><li>C:/Users/paula/Documents/Paula/Ex-jobb/Kartor/raster_water_merged.tif</li></ul>You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm."

I have changed the CRS to the same as the layers, so they dont differ at all. Iam new to QGIS and dont understand why this doesnt work. Everything up to this have worked just fine.

**Comment by roya0045** [comment]
@paulajonsson are the layers even overlapping?

**Comment by gioman** [comment]
> I try (using this modul, Iam at step 11, https://www.qgistutorials.com/en/docs/3/multi_criteria_overlay.html) to merge these two layers, i get this message

@paulajonsson please attach the raster inputs. Thanks.

**Comment by paulajonsson** [comment]
> 
> 
> @paulajonsson are the layers even overlapping?

It seems like it. I rasterized them from a vector and used the same layer as "reference" and both of the both layers have the same CRS (All this according to this module, https://www.qgistutorials.com/en/docs/3/multi_criteria_overlay.html ).

**Comment by paulajonsson** [comment]
@gioman 
[Kartor.zip](https://github.com/qgis/QGIS/files/4427168/Kartor.zip)

I hope i got it right! Let me know overwise!

**Comment by gioman** [comment]
> I hope i got it right! Let me know overwise! "Kartor" is maps on swedish :) 

@paulajonsson the formula?

**Comment by gioman** [comment]
@paulajonsson if the forumula is raster1 + raster2 then no issues here on 3.12.1 and 3.10.4 on Windows 10.

**Comment by paulajonsson** [comment]
@gioman yes it is! I tried with raster1 + raster2 again and this time it worked. Didnt do anything different from before. BUT, as soon as i was trying to do the second step (replace all 2 to 0,, since I only want 0 and 1 in my raster, non water and water) same thing happend. Just got a error again. Dont understand why it worked sometimes and sometimes it doesnt.

**Comment by gioman** [comment]
> BUT, as soon as i was trying to do the second step (replace all 2 to 0,, since I only want 0 and 1 in my raster, non water and water) same thing happend

@paulajonsson formula used?

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
