### ISSUE TITLE
Crash report: Export to DXF

### ISSUE THREAD

**Issue by heis2201** [qgis/QGIS#35553]
## User Feedback

I was trying to use the Export to DXF function...

## Report Details

**Crash ID**: [413b506d46e7e26e6694b461f7b2ffe9a8d3e33d]('https://github.com/qgis/QGIS/search?q=413b506d46e7e26e6694b461f7b2ffe9a8d3e33d&type=Issues')

**Stack Trace**
<pre>
QgsMarkerSymbolLayer::scaleMethod qgsarrowsymbollayer.h:57
QgsDxfExportDialog::cleanGroup qgsdxfexportdialog.cpp:526
QgsDxfExportDialog::QgsDxfExportDialog qgsdxfexportdialog.cpp:441
QgisApp::dxfExport qgisapp.cpp:6510
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1607
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.3-A Coru�a
QGIS code revision: 0e1f846438
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
> I was trying to use the Export to DXF function...

@heis2201 regardless of the input data? if no, then attach sample data. Also try with a new QGIS profile.

**Comment by heis2201** [comment]
Hi @gioman, no it's not regardless of the input data. I had another project that I could sucesfully export to DXF. My feeling is that as soon as the project exceeds a certain size (map extent, number of layers, ...) QGIS crashes. I am going to update to the latest LTR now (not sure there have been changes on the DXF export function from .3 to .4) and report back.

I am pasting here another trace (just in case that helps). 
## User Feedback

Again...

## Report Details

**Crash ID**: [60ee04db54041eeafcdf425091b32eec5c4e3a5c]('https://github.com/qgis/QGIS/search?q=60ee04db54041eeafcdf425091b32eec5c4e3a5c&type=Issues')


**Stack Trace**
<pre>
QgsDxfExport::addFeature qgsdxfexport.cpp:4087
QgsDxfExport::writeEntities qgsdxfexport.cpp:1138
QgsDxfExport::writeToFile qgsdxfexport.cpp:563
QgisApp::dxfExport qgisapp.cpp:6545
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1607
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>


**QGIS Info**
QGIS Version: 3.10.3-A Coru�a
QGIS code revision: 0e1f846438
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by heis2201** [comment]
I just tried the export the exact same project on another PC that is still running 3.4.12 (Madeira) and the export was sucessful.

**Comment by heis2201** [comment]
## User Feedback

Still crashing under the latest 3.10.4 release...

## Report Details

**Crash ID**: [60ee04db54041eeafcdf425091b32eec5c4e3a5c]('https://github.com/qgis/QGIS/search?q=60ee04db54041eeafcdf425091b32eec5c4e3a5c&type=Issues')


**Stack Trace**
<pre>
QgsDxfExport::addFeature qgsdxfexport.cpp:4087
QgsDxfExport::writeEntities qgsdxfexport.cpp:1103
QgsDxfExport::writeToFile qgsdxfexport.cpp:563
QgisApp::dxfExport qgisapp.cpp:6546
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1607
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>


**QGIS Info**
QGIS Version: 3.10.4-A Coru�a
QGIS code revision: 10bc9f2ff2
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
>  no it's not regardless of the input data

@heis2201 please attach the data.

**Comment by gioman** [comment]
> Maybe a regression?

@heis2201 maybe, you still need to allow us to replicate, so please attach a sample dataset.

**Comment by m-kuhn** [comment]
A sample data set would be useful.
Also, could you install the current nightly build and pdb from OSGEO4W and try again (qgis-dev qgis-dev-pdb) and post the stack trace of that one?

**Comment by gioman** [comment]
Closing for lack of feedback.
