### ISSUE TITLE
Problem with qgis_version_no qgis_short_version and qgis_version expressions controling forms visibility

### ISSUE THREAD

**Issue by PedroVenancio** [qgis/QGIS#35558]
There is an issue with @qgis_version_no, @qgis_short_version and @qgis_version expressions, when used in "Control visibility by expression", in Attributes Form (Drag and drop designer).

To reproduce:

1. Please open the sample shapefile provided here in any QGIS version (3.10.4, 3.12.1 or master 3.13):
https://cld.pt/dl/download/8ac48104-0d45-41fb-9dbd-85bd1d7d39e1/qgis_version_sample.zip

2. Identify any feature. You will see something like the following image, with 2 tabs:

![imagem](https://user-images.githubusercontent.com/1331581/78386600-c7df3780-75d5-11ea-9323-0a8aa60c8bca.png)

3. However, the form has 3 tabs, as you can see if you open the Layer Properties -> Attributes Form:

![imagem](https://user-images.githubusercontent.com/1331581/78386657-e1807f00-75d5-11ea-855c-7c21ff08a641.png)

Tab 'ID' visibility is controlled by this expression (using QGIS 3.10.4).

```
CASE 
  WHEN ( @qgis_version_no = 31004 ) THEN 1
  ELSE 0
END
```

If you are using another QGIS version, change @qgis_version_no value accordingly.

If you look at the Output preview, it is correct, as it shows 1. But it is not followed by the result in the form.

4. Changing the expression to always drop in the first condition of Case When, it works as expected:

![imagem](https://user-images.githubusercontent.com/1331581/78386755-0d036980-75d6-11ea-928d-2ac4857647a7.png)

![imagem](https://user-images.githubusercontent.com/1331581/78386765-142a7780-75d6-11ea-8d99-083223d09407.png)

The issue is only with @qgis_version_no, @qgis_short_version and @qgis_version expressions. 
And it happens the same way in 3.10.4, 3.12.1 and master. Tested in Windows.

**Comment by stev-0** [comment]
I'm not sure it's only the qgis_* variables - I tested with `CASE WHEN ( @project_crs = 'EPSG:3763' ) THEN 1 ELSE 0
END`

and that doesn't work either despite reporting a 1 result, similarly with `project_area_units`.

But `CASE  WHEN (  day_of_week(  now() ) = 1 ) THEN 1 ELSE 0
END` does work (on a Monday)

Which suggests it's an issue with variables more generally.
