### ISSUE TITLE
WFS filter query fails as soon as wkb_geometry is involved

### ISSUE THREAD

**Issue by andreasneumann** [qgis/QGIS#35556]
**Describe the bug**
WFS filter query works if only attributes are involved, but as soon as wkb_geometry is involved, it fails to load.

**How to Reproduce**
1. Connect the following WFS: https://wfs.geodienste.ch/lwb_bewirtschaftungseinheit_0 and then the layer "Bewirtschaftungseinheit"
2. Use "SELECT * FROM bewirtschaftungseinheit WHERE kanton='SO'" as the query --> works fine
3. Use "SELECT * FROM bewirtschaftungseinheit WHERE kanton='SO' AND ST_Intersects(wkb_geometry,ST_MakeEnvelope(2612000,1245500,2613500,1246500,2056))" as the query --> fails
4. Use "SELECT * FROM bewirtschaftungseinheit WHERE ST_Intersects(wkb_geometry, ST_GeometryFromText('POLYGON((2612000 1245500,2612000 1246500,2613500 1246500,2613500 1245500,2612000 1245500))'))" --> fails

![image](https://user-images.githubusercontent.com/884476/78371076-c73fa480-75c7-11ea-9681-812b5d91c66d.png)

**QGIS and OS versions**
Tested in version 3.4, 3.10 and master, on Windows and Linux.

**Comment by rouault** [comment]
Seems to be a server issue. In a debug build, I see the following trace
```
src/core/qgsmessagelog.cpp:29 : (logMessage) [2ms] 2020-04-03T17:23:54 WFS[1] Server generated an exception in GetFeature response: msWFSGetFeature(): WFS server error. Invalid or Unsupported FILTER in GetFeature : <fes:Filter xmlns:fes="http://www.opengis.net/fes/2.0" xmlns:gml="http://www.opengis.net/gml/3.2">
 <fes:And>
  <fes:PropertyIsEqualTo>
   <fes:ValueReference>kanton</fes:ValueReference>
   <fes:Literal>SO</fes:Literal>
  </fes:PropertyIsEqualTo>
  <fes:Intersects>
   <fes:ValueReference>wkb_geometry</fes:ValueReference>
   <gml:Envelope srsName="urn:ogc:def:crs:EPSG::2056">
    <gml:lowerCorner>2612000 1245500</gml:lowerCorner>
    <gml:upperCorner>2613500 1246500</gml:upperCorner>
   </gml:Envelope>
  </fes:Intersects>
 </fes:And>
</fes:Filter>
```

**Comment by andreasneumann** [comment]
Thanks for your quick look, @rouault 

So the above XML snippet would be a syntactically correct filter, but the server doesn't send anything useful back?

**Comment by andreasneumann** [comment]
Ok, so then we can close this issue.

Thank you for having a look at it!
