### ISSUE TITLE
Wrong label size for SLD export/import

### ISSUE THREAD

**Issue by bdhaegar** [qgis/QGIS#35561]
**Describe the bug**
When saving a feature layer with a label style as an SLD file, the SLD file has the wrong label size if the label size in QGIS was stated in points. 

**How to Reproduce**

<!-- Steps, sample datasets and qgis project file to reproduce the behavior. Screencasts or screenshots welcome

1. Create a point layer
2. Open the style dialog and create a single layer
3. set the size of the label to 10 Points
4. Export the layer style to an SLD file
5. Open the SLD file with an editor
6. The font-size has the value 13 instead of 10

**QGIS version 3.10.0 and Windows 10.0.18362**

**Additional context**

If the label size of the label in QGIS is stated as 10 pixels, then the font-size in the SLD file is 10, which is correct.

**Comment by Pedro-Murteira** [comment]
I was able to replicate this on QGIS 3.16.15 and 3.22.2.

**Comment by elpaso** [comment]
Looks like it was already fixed, see test in the linked PR
