### ISSUE TITLE
QGIS crash on exit

### ISSUE THREAD

**Issue by j-lippmann** [qgis/QGIS#35562]
## User Feedback

Hello,

QGIS crash on exit. May be the crash is related to a virtual field in an geometryless table...

`CASE
WHEN   length( array_get( string_to_array(  replace ("strshl",'   ','#'),'#'),1)) >8  THEN 'too long'
ELSE   array_get( string_to_array(  replace ("strshl",'   ','#'),'#'),1)
END`

## Report Details

**Crash ID**: [8f7c7a3b14547938858049da3bf5b1bc7a122d84]('https://github.com/qgis/QGIS/search?q=8f7c7a3b14547938858049da3bf5b1bc7a122d84&type=Issues')

**Stack Trace**
<pre>
QBitArray::QBitArray :
QgsAggregateCalculator::delimiter qgsaggregatecalculator.h:165
QgisApp::fileExit qgisapp.cpp:5661
QWidget::event :
QgisApp::event qgisapp.cpp:1929
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QWidgetPrivate::close_helper :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processCloseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1607
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.4-A Coru�a
QGIS code revision: 10bc9f2ff2
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by gioman** [comment]
@j-lippmann can you please attach a sample project (with data) that shows the issue? Thanks.

**Comment by j-lippmann** [comment]
The issue it's no more reproduceable. Sorry for the noise.
