### ISSUE TITLE
QGIS 3.12 - Date Field does not go earlier than 1/1/100 AD in geopackage or shape file

### ISSUE THREAD

**Issue by microcebus** [qgis/QGIS#35574]
QGIS3.12.0 (Mac Mojave 10.14.6, iMac - QGIS Website Download) - I am mapping radiometric dates from archaeological sites that date from 60000BC to 1950AD, but it appears that I can not set a date using the date field type in a geopackage or shapefile earlier than 1/1/100 AD.

I have searched the previous bugs, but did not find a similar issue. Note attached image shows the 'click earlier year' triangle button as being greyed out.

![image](https://user-images.githubusercontent.com/1481348/78417010-1b529380-7671-11ea-80d4-89f33c1bb5c4.png)

**Comment by rouault** [comment]
There might be a limitation of QGIS for dates between 1/1/1 AD and 1/1/100 AD, but what I'm sure is that there is definitely a limitation of the formats themselves to support any date in the BC era. For GeoPackage, see table 1 of http://www.geopackage.org/spec/ "DATE | ISO-8601 date string in the form YYYY-MM-DD". For shapefiles, this comes from the DBF format itself whose date formatting is YYYYMMDD.

You'd better working with a floating point type and using decimal year convention.

**Comment by nyalldawson** [comment]
QDateTime docs state:

"No Year 0
There is no year 0. Dates in that year are considered invalid. The year -1 is the year "1 before Christ" or "1 before current era." The day before 1 January 1 CE is 31 December 1 BCE.

Range of Valid Dates
The range of values that QDateTime can represent is dependent on the internal storage implementation. QDateTime is currently stored in a qint64 as a serial msecs value encoding the date and time. This restricts the date range to about +/- 292 million years, compared to the QDate range of +/- 2 billion years. Care must be taken when creating a QDateTime with extreme values that you do not overflow the storage. The exact range of supported values varies depending on the Qt::TimeSpec and time zone."

It's possibly a limitation with the date time widget itself, not the QDateTime class. (and of course, @rouault's note on the support within the actual data formats themselves...)

**Comment by agiudiceandrea** [comment]
The issue affects also memory layers.
The minimum datetime was set to 100-01-01 with PR https://github.com/qgis/QGIS/pull/4842. Previously was 1752-09-14.
See https://github.com/qgis/QGIS/blob/6358baafcd8253f5944d2ea87b8bfea8b8b3289f/src/gui/editorwidgets/qgsdatetimeedit.h#L190-L204

It seems a limitation of Qt https://doc.qt.io/qt-5/qdatetimeedit.html#minimumDateTime-prop:

> This property can only be set to a valid QDateTime value. The earliest date-time that setMinimumDateTime() accepts is the start of 100 CE. The property's default is the start of September 14, 1752 CE.

**Comment by agiudiceandrea** [comment]
It's possible avoid the limitation of QDateTimeEdit::setMinimumDateTime() using QDateTimeEdit::setDateTimeRange(), instead.
E.g. to 0001-01-01
`setDateTimeRange( QDateTime::fromString( QStringLiteral( "0001-01-01" ), Qt::ISODate ), maximumDateTime() );`

**Comment by microcebus** [comment]
Cool, thanks for all this helpful advice!

**Comment by agiudiceandrea** [comment]
Hi @microcebus, it'is also possible to set the minimum datetime to BC (negative) years :
`setDateTimeRange( QDateTime( QDate( -100, 1, 1) ), maximumDateTime() );`
but then, entering a BC date, the value is not displayed in the attribute table, although it is correctly stored, at least in a memory layer.
There is also a bug in the calendar widget, which incorrectly displays also a nonexistent year 0.

**Comment by Voghera** [comment]
I am using Qgis for an archaeological project and I find that the such limitation in date management is a serious drawback.

**Comment by agiudiceandrea** [comment]
@voghera, see https://github.com/qgis/QGIS/issues/38209.

**Comment by Voghera** [comment]
Many thanks, but I am not so expert to take advantage of your suggestion:

   - Allow QgsDateTimeEdit to support dates since Jan 1st 1 CE (instead of
   100 CE) and avoid QDate and QDateTime field value triple conversion
   #36683 <https://github.com/qgis/QGIS/pull/36683>

I have no idea how to do it and, however, I need dates from 3000 bc... it
is not so crazy: with dendrochronology, archaeoastronomy and from ancient
documents sometimes we get precise dates of thousands years ago.
