### ISSUE TITLE
DB manager does not display query results from PG 12

### ISSUE THREAD

**Issue by jurafejfar** [qgis/QGIS#35577]
**Describe the bug**

DB manager does not display query results from PostgresSQL 12.

**How to Reproduce**

1. Go to DB Manager.
2. Click on SQL Window
3. Run any query like 
```sql
select * from version();
select * from pg_stat_activity;
select * from spatial_ref_sys;
```
4. No results displayed

Queries are being executed (exec. time is reported) but no results displayed (0 rows).

![image](https://user-images.githubusercontent.com/15230644/78419804-999b3f80-7649-11ea-871c-528971768a43.png)

the same query run on the same DB with psql client:

```
psql postgres 
Pager is used for long output.
Line style is unicode.
Border style is 2.
Timing is on.
psql (12.2 (Debian 12.2-2.pgdg100+1))
Type "help" for help.

(jura@[local]:5432) [postgres] > select * from version();
┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                     version                                                      │
├──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ PostgreSQL 12.2 (Debian 12.2-2.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
(1 row)

Time: 2.519 ms
```

**QGIS and OS versions**

QGIS version | 3.12.1-București | QGIS code revision | 121cc00ff0
-- | -- | -- | --
Compiled against Qt | 5.11.3 | Running against Qt | 5.11.3
Compiled against GDAL/OGR | 2.4.0 | Running against GDAL/OGR | 2.4.0
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.27.2 | Running against SQLite | 3.27.2
PostgreSQL Client Version | 11.6 (Debian 11.6-0+deb10u1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.10.4
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Debian GNU/Linux 10 (buster)
Active python plugins | qgis2web; quick_map_services; MetaSearch; processing; db_manager

**Comment by Gustry** [comment]
Duplicate https://github.com/qgis/QGIS/issues/34731
Remove the `;` to make it work.
