### ISSUE TITLE
Des extensions empechent Qgis de les utiliser et d'ouvrir qgis correctement.

### ISSUE THREAD

**Issue by anais-boucher** [qgis/QGIS#35581]
Je suis sur qgis 3.4 et je reçoit ce message à l'ouverture de QGIS qui m'empeche d'utiliser l'extension 2threesqgis entre autre 

![Capture d’écran 2020-04-04 à 12 19 12](https://user-images.githubusercontent.com/63146844/78424569-d594cb80-766e-11ea-95ee-2beda57bb673.png)

**Comment by gioman** [comment]
@anais-boucher go in the plugin manager and disable/enable the Processing toolbox.

**Comment by anais-boucher** [comment]
Merci !
Seulement même en ayant fait ça, je ne peux pas utiliser mon extension, il y a ce message qui s'affiche :

![Capture d’écran 2020-04-05 à 10 14 46](https://user-images.githubusercontent.com/63146844/78470032-6da1bc00-7726-11ea-8bfe-564d2f94fc57.png)

**Comment by gioman** [comment]
@anais-boucher it seems the message comes from the qgis2threejs plugin, you must report it to the plugin author.

**Comment by Gustry** [comment]
Well, it might also be Processing issue too not handling the custom menu correctly when the key is not there anymore.
@anais-boucher So you got the plugin Qgis2ThreeJS and you tried to set a custom menu entry? Tu avais essayé de faire un menu pour QGIS2ThreeJS?  Je pense qu'il faut que tu essaies un nouveau profil, le tiens semble corrompu avec un menu.

**Comment by anais-boucher** [comment]
Tres bien je vais le signaler à l'auteur merci,
Il y a un moment que j'avais téléchargé QgisThreeJS , je me suis contentée de m'en servir pour de la visualisation 3D , ça marchait tres bien et d'un coup ça a planté, je vais essayer un nouveau profil .... Merci beaucoup !
