### ISSUE TITLE
vector editing not active after loading a project

### ISSUE THREAD

**Issue by BC-Consulting** [qgis/QGIS#35596]
First layer in project is a line vector shapefile and is the selected layer. Other layers in project are all raster files.
When project opens, the first layer is selected as it should but it is not editable (greyed icon). I have to select another layer and then select the first layer back in order to enable editing.

Behaviour noticed from dev distro from 3 weeks ago and today latest dev distro.
Environment: Win10Pro, OSGeoW64, latest dev distro (eef586664f)

Cheers,
Benoit

**Comment by gioman** [comment]
@BC-Consulting can you attach a sample project? I cannot replicate on 3.16.2
