### ISSUE TITLE
Set the correct temporal extent

### ISSUE THREAD

**Issue by saberraz** [qgis/QGIS#35594]
I have seen that in the mesh provider, but I think it might be applicable to other dataset with temporal extent:

When loading a layer spanning over a time period, the logical thing is:

- If it is the first data with the time component, set the project/canvas time to the first time step of the newly added dataset
- If there are other datasets already loaded with time component, show the time step set in the time manager widget, if available.

The above logic follows similar one for spatial extent: QGIS zooms to the extent of the first spatial layer. The subsequent layers only shown within the current map extent (if available).

**Comment by saberraz** [comment]
Could an admin please add a new label for Time Manager....now that we have the feature, there will be bugs with it too :)

**Comment by gioman** [comment]
> Could an admin please add a new label for Time Manager....now that we have the feature, there will be bugs with it too :) 

@saberraz 

done

**Comment by saberraz** [comment]
Thanks Gio!
