### ISSUE TITLE
multiline symbology classes names do not work in print layouts legends

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#35597]
I have a legend with very long text and to create a multiline I use the expression:

``` 
 wordwrap ("DESCRIZIONE", 50)
```

it is correctly displayed in the Panel layer but not in the legend of the print composer.

![image](https://user-images.githubusercontent.com/7631137/78502423-719eff80-7761-11ea-8fe7-a047b6237c19.png)

---

## I attach gpkg with data and project

[test_legend.zip](https://github.com/qgis/QGIS/files/4434191/test_legend.zip)

**Comment by nyalldawson** [comment]
Your expression should be ` wordwrap(@symbol_label ,20)`, not ` wordwrap("field name" ,20)`. In any case, this is working correctly on 3.14

**Comment by pigreco** [comment]
@nyalldawson 
Thanks for the reply,
but where should the expression `wordwrap(@symbol_label ,20)` be used ??

I don't understand how to use it, thanks.

**Comment by pigreco** [comment]
here's where to use it!
![image](https://user-images.githubusercontent.com/7631137/142762901-40dc5059-3c8e-432c-baf9-c7a2b604c6f3.png)
