### ISSUE TITLE
QGIS not importing .map files correctly in 3.12

### ISSUE THREAD

**Issue by rossoe** [qgis/QGIS#35600]
**Describe the bug:**

I use a programe that generates OziExplorer **.map** files along with associated **.jpg** files, in order to break up a large ROI of flown imagery into tiled downloads.

usually I just select all the **.map** files and drag into QGIS, and it works perfectly. But recently it seems unable to order them correctly, I can't recollect the most recent version of QGIS where this last worked, however I know it definately worked in 3.4.3

Someone on stackexchange suggested it may be something related to axis order, following switch to proj 6 in latest QGIS?

**How to Reproduce:**

https://1drv.ms/u/s!AjCedBZJ5Eh4nXzbmNk_EX7ReQE4?e=07OUgH

1. See linked zip file above with 2 example tile images inlcuding .map files
2. unzip and select only the 2 .map files
3. Drag into open QGIS 3.12 workspace

This is what it looks like in QGIS 3.12:
![image](https://user-images.githubusercontent.com/28996048/78510827-04569300-7790-11ea-8569-07fbb0891569.png)

If I do the same with QGIS 2.18 it orientates the tiles correctly:
![image](https://user-images.githubusercontent.com/28996048/78510859-37008b80-7790-11ea-9460-8f5b510e9ec8.png)

**QGIS and OS versions:**
3.12
Windows 10

QGIS version
3.12.1-București
QGIS code revision
121cc00ff0
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.1
Running against PROJ
Rel. 6.3.1, February 10th, 2020
OS Version
Windows 10 (10.0)
Active python plugins
CSMapMaker; 
LAStools; 
OSMDownloader; 
otb; 
Qgis2threejs; 
quick_map_services; 
SRTM-Downloader; 
tiss; 
db_manager; 
MetaSearch; 
processing

**Comment by gioman** [comment]
> Someone on stackexchange suggested it may be something related to axis order, following switch to proj 6 in latest QGIS?

@rossoe yes. 

gdal 2.4

```
gdalinfo google_025c_0_0_1_0.map 
Driver: MAP/OziExplorer .MAP
Files: google_025c_0_0_1_0.map
       google_025c_0_0_1_0.Jpg
Size is 8448, 11776
Coordinate System is:
PROJCS["unnamed",
    GEOGCS["WGS 84",
        DATUM["WGS_1984",
            SPHEROID["WGS 84",6378137,298.257223563,
                AUTHORITY["EPSG","7030"]],
            AUTHORITY["EPSG","6326"]],
        PRIMEM["Greenwich",0,
            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.0174532925199433,
            AUTHORITY["EPSG","9122"]],
        AUTHORITY["EPSG","4326"]],
    PROJECTION["Mercator_1SP"],
    PARAMETER["central_meridian",0],
    PARAMETER["scale_factor",1],
    PARAMETER["false_easting",0],
    PARAMETER["false_northing",0],
    UNIT["Meter",1]]
Origin = (-459463.034819911932573,6478129.145325681194663)
Pixel Size = (0.298582762685717,-0.297750621436524)
Corner Coordinates:
**Upper Left  ( -459463.035, 6478129.145) (  4d 7'38.74"W, 50d22'21.43"N)
Lower Left  ( -459463.035, 6474622.834) (  4d 7'38.74"W, 50d21' 8.90"N)
Upper Right ( -456940.608, 6478129.145) (  4d 6'17.16"W, 50d22'21.43"N)
Lower Right ( -456940.608, 6474622.834) (  4d 6'17.16"W, 50d21' 8.90"N)
Center      ( -458201.821, 6476375.990) (  4d 6'57.95"W, 50d21'45.17"N)**
Band 1 Block=8448x1 Type=Byte, ColorInterp=Red
  Overviews: 4224x5888, 2112x2944, 1056x1472
  Image Structure Metadata:
    COMPRESSION=JPEG
Band 2 Block=8448x1 Type=Byte, ColorInterp=Green
  Overviews: 4224x5888, 2112x2944, 1056x1472
  Image Structure Metadata:
    COMPRESSION=JPEG
Band 3 Block=8448x1 Type=Byte, ColorInterp=Blue
  Overviews: 4224x5888, 2112x2944, 1056x1472
  Image Structure Metadata:
    COMPRESSION=JPEG
```

GDAL 3

```
gdalinfo google_025c_0_0_1_0.map
Driver: MAP/OziExplorer .MAP
Files: google_025c_0_0_1_0.map
       google_025c_0_0_1_0.Jpg
Size is 8448, 11776
Coordinate System is:
PROJCRS["unnamed",
    BASEGEOGCRS["WGS 84",
        DATUM["World Geodetic System 1984",
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4326]],
    CONVERSION["unnamed",
        METHOD["Mercator (variant A)",
            ID["EPSG",9804]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",1,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",0,
            LENGTHUNIT["Meter",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["Meter",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["easting",east,
            ORDER[1],
            LENGTHUNIT["Meter",1]],
        AXIS["northing",north,
            ORDER[2],
            LENGTHUNIT["Meter",1]]]
Data axis to CRS axis mapping: 1,2
Origin = (5607454.408323068171740,-456787.741245437238831)
Pixel Size = (-0.265504519298573,0.213317176895073)
Corner Coordinates:
**Upper Left  ( 5607454.408, -456787.741) ( 50d22'21.43"E,  4d 7'38.74"S)
Lower Left  ( 5607454.408, -454275.718) ( 50d22'21.43"E,  4d 6'17.17"S)
Upper Right ( 5605211.426, -456787.741) ( 50d21' 8.90"E,  4d 7'38.74"S)
Lower Right ( 5605211.426, -454275.718) ( 50d21' 8.90"E,  4d 6'17.17"S)
Center      ( 5606332.917, -455531.730) ( 50d21'45.16"E,  4d 6'57.95"S)**
Band 1 Block=8448x1 Type=Byte, ColorInterp=Red
  Overviews: 4224x5888, 2112x2944, 1056x1472
  Image Structure Metadata:
    COMPRESSION=JPEG
Band 2 Block=8448x1 Type=Byte, ColorInterp=Green
  Overviews: 4224x5888, 2112x2944, 1056x1472
  Image Structure Metadata:
    COMPRESSION=JPEG
Band 3 Block=8448x1 Type=Byte, ColorInterp=Blue
  Overviews: 4224x5888, 2112x2944, 1056x1472
  Image Structure Metadata:
    COMPRESSION=JPEG
```

This should be closed as an upstream issue.

**Comment by rouault** [comment]
Duplicated of https://github.com/qgis/QGIS/issues/34299 . Will be fixed in future GDAL versions: see https://github.com/qgis/QGIS/issues/34299#issuecomment-582646747
