### ISSUE TITLE
Big difference in values between cartesian and ellipsoidal areas

### ISSUE THREAD

**Issue by AlexJew** [qgis/QGIS#35629]
Hello,

When looking at area values of polygons in vector layers. I've noticed that depending on the chosen CRS, there could be big differences between the cartesian and the ellipsoidal areas. In my case, I have two exact same layers. Via the *Identify Feature* tool, I am showing the derived area of the same polygon in each layer ( <=> with different CRS).

1. Its CRS is `EPSG:3857 - WGS 84 / Pseudo-Mercator - Projected`. The areas are : 
- Cartesian : 357.91 m2
- Ellipsoidal : 217.55 m2

![image](https://user-images.githubusercontent.com/32110882/78566466-2810ec00-7817-11ea-8a68-97b28aaae075.png)

2. Its CRS is `EPSG:32729 - WGS 84 / UTM zone 29S - Projected`. The areas are:
- Cartesian : 217.37 m2
- Ellipsoidal : 217.54 m2

![Screen Shot 2020-04-06 at 14 55 22 (2)](https://user-images.githubusercontent.com/32110882/78566588-58588a80-7817-11ea-8fb3-3e764d3ad168.png)

Is this a bug in the computation of the cartesian area?

**Comment by gioman** [comment]
@AlexJew 3857 is not reliable for any kind of measurement.

**Comment by AlexJew** [comment]
Ok, thanks! I was just wondering ^^

**Comment by roya0045** [comment]
@gioman I guess this can be closed then?
