### ISSUE TITLE
QGIS variables used on symbology rules do not appear on 3D map (but features are returned)

### ISSUE THREAD

**Issue by bmscmoreira** [qgis/QGIS#35627]
**Describe the bug**
When adding a QGIS variable in a symbology rule features are returned but are not displayed on the 3D Map, only on the 2D Map.

**How to Reproduce**
1. define a custom variable in config / options / variables: for ex. "var" = 1
2. add that variable as a rule in symbology: for ex. "variable = @var"
3. click "test" and confirm that the filter returns the features (ex. "filter returned 38 elements"; @var evaluated to '1';
4. click ok; the features are displayed on the 2D map but not in the 3D map.

Note that if I use the rule "variable = 1" instead of "variable = @var" the filter will return the same elements, but they will be displayed both in the 2D and 3D map.

**QGIS and OS versions**

Versão do QGIS | 3.12.0-București | Revisão do código do QGIS | 409bcf8eaa
Compilado com Qt | 5.12.3 | Em execução com Qt | 5.12.3
Compilado com GDAL/OGR | 2.4.1 | Em execução com GDAL/OGR | 2.4.1
Compilado com GEOS | 3.7.2-CAPI-1.11.2 | Em execução com GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.28.0 | Running against SQLite | 3.28.0
Versão de cliente PostgreSQL | 11.3 | Versão SpatiaLite | 4.3.0a
Versão QWT | 6.1.4 | Versão QScintilla2 | 2.11.1
Compilado com PROJ | 5.2.0 | Em execução com PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS 10.15

**Additional context**
Steps to reproduce are based on my actual content. To reproduce one must have entities matching the filter.

**Comment by nyalldawson** [comment]
I can't reproduce -- is this still an issue?

**Comment by bmscmoreira** [comment]
Sorry for late reply. Just upgraded Qgis to latest version (details below) and problem is still present.
Versão do QGIS | 3.14.0-Pi | Revisão do código do QGIS | 9f7028fd23
-- | -- | -- | --
Compilado com Qt | 5.12.3 | Em execução com Qt | 5.12.3
Compilado com GDAL/OGR | 2.4.1 | Em execução com GDAL/OGR | 2.4.1
Compilado com GEOS | 3.7.2-CAPI-1.11.2 | Em execução com GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.28.0 | Running against SQLite | 3.28.0
Versão de cliente PostgreSQL | 11.3 | Versão SpatiaLite | 4.3.0a
Versão QWT | 6.1.4 | Versão QScintilla2 | 2.11.1
Compilado com PROJ | 5.2.0 | Em execução com PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS 10.15
Active python plugins | profiletool; layerGroupFilter; Qgis2threejs; pointsamplingtool; valuetool; processing; db_manager; MetaSearch

**Comment by nyalldawson** [comment]
Any chance of a sample test project? I still can't reproduce

**Comment by lbartoletti** [comment]
I have the same problem.

![image](https://user-images.githubusercontent.com/7521540/97537902-d650ce80-19bf-11eb-8773-3e4e2bd00594.png)

![image](https://user-images.githubusercontent.com/7521540/97538053-131cc580-19c0-11eb-9af3-cec55fcb057d.png)


[3D_filter.zip](https://github.com/qgis/QGIS/files/5456711/3D_filter.zip)


I notice, that at the open of the project polygons are extruded but with grey colors. But if you change settings in 3D view the extrusion is no more rendered -- you have to quit and reopen qgis.


But by doing several tests, it seems to work on this layer... On another project, the polygons are not extruded at all... very strange

**Comment by nyalldawson** [comment]
I still can't reproduce this, using either report
