### ISSUE TITLE
Wrong preview values for $area and $perimeter in the "Select By Expression"

### ISSUE THREAD

**Issue by jmonticolo** [qgis/QGIS#35628]
**Describe the bug**
Very similar issue to [issue #17334](https://github.com/qgis/QGIS/issues/17334), I noticed in the Select By Expression dialog there is strange values for `$area` and `$perimeter`.

**How to Reproduce**

1. Create a new QGIS project and select the 2154 CRS (I think it's not the source of the bug but it's a projected system I'm used too (french reference CRS))
2. Create a 100 m square grid with the extent `400000,400200,7000000,7000200 [EPSG:2154]` but the bug appears for all polygon layers I tested, just it's easier with squares.
3. You have 4 square features with a logical projected perimeter of 400 m and area of 10 000 m2
4. Open the Calculate Field Dialog and verify :
  - OK: `perimeter($geometry)` : 400
  - OK: `area($geometry)` : 10000
  - OK: `$perimeter` : 399.6146268034432 (around 400, ellipsoidal distance)
  - OK: `$area` : 9980.74059100748 (around 10000, ellipsoidal area)
5. Same but with the Select By Expression Dialog :
  - OK: `perimeter($geometry)` : 400
  - OK: `area($geometry)` : 10000
  - KO: `$perimeter` : **44527796.31730943**
  - KO: `$area` : **123920290305000**

**QGIS and OS versions**

Version de QGIS | 3.12.1-București | Révision du code | 121cc00ff0
-- | -- | -- | --
Compilé avec Qt | 5.12.4 | Utilisant Qt | 5.12.4
Compilé avec GDAL/OGR | 2.4.2 | Utilisé avec GDAL/OGR | 2.4.2
Compilé avec GEOS | 3.7.2-CAPI-1.11.2 | Utilisé avec GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
Version du client PostgreSQL | 11.7 (Ubuntu 11.7-0ubuntu0.19.10.1) | Version de SpatiaLite | 4.3.0a
Version de QWT | 6.1.4 | Version de QScintilla2 | 2.10.4
Compilé avec PROJ | 5.2.0 | Fonctionne avec PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Ubuntu 19.10
Extensions Python actives | french_locator_filter; plugin_reloader; pluginbuilder3; firstaid; quick_map_services; processing; db_manager; MetaSearch

**Comment by gioman** [comment]
@jmonticolo as far as I can see is just the preview that is wrong (the selection by expression works as expected), correct?

**Comment by jmonticolo** [comment]
Yes. With the following Select expressions `390 < $perimeter < 400` and `9990 < $area < 10010` with the 100 m side squares, all the 4 features are selected, which means the algorithm behind works.
The bug is just the value displayed in the bottom left of the Select By Expression Dialog.
