### ISSUE TITLE
QGIS unexpectedly ended - DEL key while entering circular string arc

### ISSUE THREAD

**Issue by TMcManus2018** [qgis/QGIS#35637]
## User Feedback

Was ortho tracing using circular arc. Missed switching to a line segment and then tried to go back by hitting delete, hoping that QGIS would simply go back to the last vertex, let me switch to line segment and proceed from there. Instead, it stopped responding.

## Report Details

**Crash ID**: [e4162199c3be8e973894328e593f88979dd1bfbf]('https://github.com/qgis/QGIS/search?q=e4162199c3be8e973894328e593f88979dd1bfbf&type=Issues')

**Stack Trace**
<pre>
QListData::begin :
QgsRubberBand::numberOfVertices qgsrubberband.cpp:608
QgsMapToolCapture::undo qgsmaptoolcapture.cpp:583
QgsMapToolCapture::keyPressEvent qgsmaptoolcapture.cpp:625
QgsMapToolAddCircularString::keyPressEvent qgsmaptooladdcircularstring.cpp:93
QgsMapCanvas::keyPressEvent qgsmapcanvas.cpp:1376
QWidget::event :
QFrame::event :
QAbstractScrollArea::event :
QgsMapCanvas::event qgsmapcanvas.cpp:2359
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processKeyEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1609
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.12.1-Bucure?ti
QGIS code revision: 121cc00ff0
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by TMcManus2018** [comment]
On restarting QGIS, the layer I was working in disappeared completely, even though I had completed 6 or more features and having saved the features and the project prior to this crash!! Oh no!

**Comment by gioman** [comment]
@TMcManus2018 please try with a new QGIS profile, no 3rd party plugins installed.

If the issue persist:

is the crash data dependent? if yes please attach sample data.

**Comment by TMcManus2018** [comment]
Tried to reproduce this error in a new QGIS profile. Was not able to reproduce. Did find that I could back out of an erroneous circular arc using backspace. I had been trying escape and delete when the crash occurred. If the crash trace back doesn't lead to any obvious error, probably best to just close this report and ignore this crash unless and until other reported crashes with related characteristics occur.
