### ISSUE TITLE
Crashed when I tryed to 'add layers to map' after defining a new ODBC connection to Presto DB

### ISSUE THREAD

**Issue by rherasm** [qgis/QGIS#35634]
Related with the closed issue: https://github.com/qgis/QGIS/issues/20807

I was trying a ODBC connection with AWS Presto DB through Simba-Presto x64 driver.
QGIS 3.12 x64 
Windows 10 x64 1809
Presto: AWS cluster

After successfully test the new defined connection I pushes the button 'Add the selected layers to the map'

Simba ODBC driver reference: https://www.simba.com/drivers/presto-odbc-jdbc/?gclid=CjwKCAjwvZv0BRA8EiwAD9T2VUTjxLQYrgQOsI8YT6bduxVaDel2AV9Av8gtExNIIPTZW4gQyf8lQBoCkDMQAvD_BwE

After one minute QGIS crashed (QGIS unexpectedly ended)
--------
Crash ID: c4598b936d09b7f052a37d8c67c1922646c03994

Stack Trace

memcpy memcpy.asm:135
CPLODBCStatement::Fetch :
DDFRecordIndex::SetClientInfoByIndex :
DDFRecordIndex::SetClientInfoByIndex :
QgsOgrProvider::getOgrGeomType qgsogrprovider.cpp:1045
QgsOgrProvider::loadFields qgsogrprovider.cpp:1091
QgsOgrProvider::setEncoding qgsogrprovider.cpp:1018
QgsOgrProvider::open qgsogrprovider.cpp:4550
QgsOgrProvider::QgsOgrProvider qgsogrprovider.cpp:512
QgsOgrProviderMetadata::createProvider qgsogrprovider.cpp:3462
QgsProviderRegistry::createProvider qgsproviderregistry.cpp:385
QgsVectorLayer::setDataProvider qgsvectorlayer.cpp:1695
QgsVectorLayer::setDataSource qgsvectorlayer.cpp:1602
QgsVectorLayer::QgsVectorLayer qgsvectorlayer.cpp:178
QgisApp::addVectorLayersPrivate qgisapp.cpp:5269
QgisApp::addVectorLayers qgisapp.cpp:5202
QgisApp::qt_static_metacall moc_qgisapp.cpp:1652
QMetaObject::activate :
QgsDataSourceManagerDialog::addVectorLayers moc_qgsdatasourcemanagerdialog.cpp:367
QMetaObject::activate :
QgsAbstractDataSourceWidget::addVectorLayers moc_qgsabstractdatasourcewidget.cpp:304
QgsOgrSourceSelect::addButtonClicked qgsogrsourceselect.cpp:430
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
QgisApp::dataSourceManager qgisapp.cpp:2286
QtPrivate::QFunctorSlotObject,0,QtPrivate::List,void>::impl qobjectdefs_impl.h:421
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1609
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.12.1-Bucure?ti
QGIS code revision: 121cc00ff0
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

------------------------------------------------------------------------------------------------------------

**Comment by rherasm** [comment]
Additional information, ODBC driver traces:

gis-bin        3e80-40d8	EXIT  SQLAllocStmt  with return code 0 (SQL_SUCCESS)
		HDBC                0x000001ACE80A2BB0
		HSTMT *             0x00000047E1FEDFB8 ( 0x000001ACE25849E0)

qgis-bin        3e80-40d8	ENTER SQLExecDirect 
		HSTMT               0x000001ACE25849E0
		UCHAR *             0x000001ACFB320CB0 [      -3] "SELECT f_table_name, f_geometry_column, geometry_type FROM geometry_columns\ 0"
		SDWORD                    -3

qgis-bin        3e80-40d8	EXIT  SQLExecDirect  with return code -1 (SQL_ERROR)
		HSTMT               0x000001ACE25849E0
		UCHAR *             0x000001ACFB320CB0 [      -3] "SELECT f_table_name, f_geometry_column, geometry_type FROM geometry_columns\ 0"
		SDWORD                    -3

		DIAG [S1000] [Simba][Presto] (1060) Presto Query Error: line 1:60: Table hive.schemaName.geometry_columns does not exist (1) (1060) 

qgis-bin        3e80-40d8	ENTER SQLGetDiagRecW 
		SQLSMALLINT                  3 <SQL_HANDLE_STMT>
		SQLHANDLE           0x000001ACE25849E0
		SQLSMALLINT                  1 
		SQLWCHAR *          0x00000047E1FEDDD0
		SQLINTEGER *        0x00000047E1FEDE88
		SQLWCHAR *          0x000001ACE254B5E0 
		SQLSMALLINT                512 
		SQLSMALLINT *       0x00000047E1FEDE80

qgis-bin        3e80-40d8	EXIT  SQLGetDiagRecW  with return code 0 (SQL_SUCCESS)
		SQLSMALLINT                  3 <SQL_HANDLE_STMT>
		SQLHANDLE           0x000001ACE25849E0
		SQLSMALLINT                  1 
		SQLWCHAR *          0x00000047E1FEDDD0 [       5] "S1000"
		SQLINTEGER *        0x00000047E1FEDE88 (1060)
		SQLWCHAR *          0x000001ACE254B5E0 [     107] "[Simba][Presto] (1060) Presto Query Error: line 1:60: Table hive.schemaName.geometry_columns does not exist (1)"
		SQLSMALLINT                512 
		SQLSMALLINT *       0x00000047E1FEDE80 (107)

qgis-bin        3e80-40d8	ENTER SQLGetDiagRecW 
		SQLSMALLINT                  3 <SQL_HANDLE_STMT>

DIAG [01004] [Simba][ODBC] (10160) Output string data right truncation: string data is too big for the output data buffer and has been truncated. (10160)

**Comment by gioman** [comment]
> Additional information, ODBC driver traces:

@rherasm thanks for the detailed report, anyway consider that there is little interest around ODBC datasources, so not sure if a fix will come anytime soon (unless supporting the work or patching the code yourself).

**Comment by Pedro-Murteira** [comment]
@rherasm Hello, did you come across this crash in recent versions?
