### ISSUE TITLE
Auto-update QGIS Legend based on map theme defined in "Follow Map Theme" in Print Composer

### ISSUE THREAD

**Issue by bmscmoreira** [qgis/QGIS#35639]
**Feature description.**
Print composer has a handy feature that allows a map to use a saved theme (set of layers) by selecting the map and, inside its properties, activating "follow map theme" and selecting a saved theme.
A legend can be tied to a map and show only relevant items (visible on the map) but does not respect the theme selected in "follow map theme" - i.e., I have to go back to QGIS main window and switch the theme there, and then return to Print Composer to have the legend updated. It would be handy if the legend followed the theme defined in the print composer, saving these extra steps.

**Comment by nyalldawson** [comment]
This was fixed a couple of days ago
