### ISSUE TITLE
WFS, ArcGIS Map/Feature Server dialog filter works only on titles (not names or abstracts)

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS#35642]
All in current master (3.13)

A mailing list user asked a question about the following public ArcGIS Mapserver:

https://hazards.fema.gov/gis/nfhl/rest/services/public/NFHL/MapServer

After adding the url in the ArcGIS Map Server dialog(! not in browser), I retrieved all layers:

![Screenshot-20200407071004-877x678](https://user-images.githubusercontent.com/731673/78632719-090a6c80-78a0-11ea-977e-5aae551c255f.png)

Then tried to use the filter (question was about FIRM Panels) in the dialog, but as soon as you type, ALL layers are gone:

![Screenshot-20200407071025-877x678](https://user-images.githubusercontent.com/731673/78632521-7c5fae80-789f-11ea-92be-904b8d24ecbf.png)

Same functionality in Browser is working fine: ALL layers:

![Screenshot-20200407070944-877x678](https://user-images.githubusercontent.com/731673/78632817-4c64db00-78a0-11ea-950b-c3c908adfd31.png)

But here the filter is working fine?

![Screenshot-20200407070926-877x678](https://user-images.githubusercontent.com/731673/78632859-61416e80-78a0-11ea-969f-28050671e7af.png)

Not sure about filters in ArcGIS Feature Server, as I do not have a public url

**Comment by alexbruy** [comment]
See also #27635

**Comment by gioman** [comment]
@rduivenvoorde Ĩ modified the title: the filter option works on title, name and abstract only for WMS connections. For WFS and Arc* ones works only for titles (didn't checked WCS).

**Comment by rduivenvoorde** [comment]
Yes, you are right (I normally never use arc* services).

Apparently the dialog now (re)uses the same treeview:

![Screenshot-20220316084214-716x396](https://user-images.githubusercontent.com/731673/158540567-08bc00e8-6d80-4fae-ac8e-4b269d654c05.png)
