### ISSUE TITLE
Broken Transformations. 3.12.1

### ISSUE THREAD

**Issue by andy-harney** [qgis/QGIS#35665]
**Describe the bug**

Upgrading from 3.12.0 to 3.12.1 has broken transformations. Specifically in my case EPSG:4326 - EPSG:27700

I previously had installed the file `OSTN15_NTv2_OSGBtoETRS.gsb` to facilitate the transformations. 
Now when I open QGIS 3.12.1 I am presented with an info banner
![image](https://user-images.githubusercontent.com/47160505/78768253-95da2680-7983-11ea-868c-37754e314535.png)

I go to reinstall the required `OSTN15_NTv2_OSGBtoETRS.gsb` file. Then get this error message,
![image](https://user-images.githubusercontent.com/47160505/78768446-d8036800-7983-11ea-9ef2-39d9fc1f8aac.png)

Navigating to the path displayed, I can see the file is actually there.
![image](https://user-images.githubusercontent.com/47160505/78768772-4c3e0b80-7984-11ea-8191-0bd658ac770a.png)

So I delete the file, and reinstall from folder.
![image](https://user-images.githubusercontent.com/47160505/78768818-61b33580-7984-11ea-9846-71eb6d8069a8.png)

Restart QGIS, and I still have the info banner telling me it can't used the preferred transform. The file is present in the proj folder in my QGIS profile folder.
This issue is also present on the default QGIS profile without any plugins.

Uninstalling QGIS 3.12.1, and reinstalling 3.12.0 I don't get the info banner.

**QGIS and OS versions**

Windows 10 Pro x64
1903. Build 18364.145

QGIS 3.12.1 from https://qgis.org/downloads/QGIS-OSGeo4W-3.12.1-1-Setup-x86_64.exe

QGIS 3.12.0 installed;
QGIS version
3.12.0-București
QGIS code revision
cd141490ec
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.1
Running against PROJ
Rel. 6.3.1, February 10th, 2020
OS Version
Windows 10 (10.0)
Active python plugins
db_manager; 
MetaSearch; 
processing

**Additional context**

Many thanks.

**Comment by nyalldawson** [comment]
This is fixed for 3.12.2

**Comment by andy-harney** [comment]
That was fast! Thanks.
