### ISSUE TITLE
Grib file makes QGIS unexpectedly ended

### ISSUE THREAD

**Issue by lolo762I3** [qgis/QGIS#35673]
I begin with QGIS and GitHub, so please be kind.
I add the plugin Crayfish in order to open grib file (I downloaded a gribfile using ECMWF API). When I want to open it in QGIS (DB manager>add a mesh), I obtain the following error message :  Sorry :( It looks something unexpected happened that we didn't handle and QGIS ended unexpectedly.

![2](https://user-images.githubusercontent.com/47398882/78813792-d8285580-79cd-11ea-8a00-9e7dfe99c2a6.PNG)

**Comment by saberraz** [comment]
Hi @lolo762I3 and welcome!

Do you have an example file?

**Comment by lolo762I3** [comment]
Thank you for your answer. It seems that GitHub does not support grib format, so I cannot show you an example file. (But grib file could be downloaded for instance on ECMWF website). 

Actually I achieve to open data in QGIS using a netCDF file. 

I found help on this subject on this page : https://www.lutraconsulting.co.uk/blog/2017/11/02/working-with-climate-data-in-qgis/

**Comment by saberraz** [comment]
You can zip and upload the file.

There is an updated version of that blog here:
https://www.lutraconsulting.co.uk/blog/2019/08/26/foss4g-workshop/

**Comment by gioman** [comment]
@lolo762I3 please attach (zipped) sample data.

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
