### ISSUE TITLE
Split with lines - unexpected behaviour 

### ISSUE THREAD

**Issue by jecogeo** [qgis/QGIS#35670]
**Describe the bug**
Split with Lines: when lines from input layer intersect lines from split layer at the exact same point, the operation is not performed.

**How to Reproduce**

1. Take [sample_data.zip](https://github.com/qgis/QGIS/files/4450964/sample_data.zip)
1. Add input_features.shp and split_feature.shp. input_features contains 3 lines, two of them intersects each other at the exact same point they intersec the split_feature  (FID= 0 and 2)
2. Click on Processing Toolbox > Vector Overlay > Split with lines
3. See unexpected behaviour --> input_features FID= 0 and 2 are not splitted by split_feature.

**QGIS and OS versions**
OS: Arch Linux x86_64
Kernel: 5.6.2-arch1-2
DE: GNOME (Wayland)

QGIS version | 3.12.0-București | QGIS code branch | Release QGIS code branch.3
Compiled against Qt | 5.14.1 | Running against Qt | 5.14.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.2 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.4
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Arch Linux
Active python plugins | QNEAT3; networks; SentinelHub; timeseriesviewerplugin; db_manager; MetaSearch; processing

**Comment by spatialthoughts** [comment]
I can reproduce on MacOS with QGIS 3.10.7

**Comment by gioman** [comment]
@jecogeo @gioman isn't this related to https://github.com/qgis/QGIS/issues/37484 ?

**Comment by jecogeo** [comment]
> @jecogeo @gioman isn't this related to #37484 ?

It could be, in the core functioning, maybe. But at the user end, it seems slightly different. #37848 is reporting some kind of precision-related issue, where after splitting the road by line no vertices of the split road are found intersecting the line with the vertices, although it is expected that a vertice is created just intersecting the line (split feature).

My issue, on the other hand, is that when two lines of the input features share a vertice in the exact same point where the split feature crosses, those lines are not split. 
As I said, could be related, but it doesn't seem such apparently.

I tested with QGIS version 3.20.0-Odense and the issue is still present for both tickets.

**Comment by gioman** [comment]
> is that when two lines of the input features share a vertice in the exact same point where the split feature crosses, those lines are not split.

@jecogeo does it happens after a "snap to layer" or "snap points to grid"?

**Comment by jecogeo** [comment]
> > is that when two lines of the input features share a vertice in the exact same point where the split feature crosses, those lines are not split.
> 
> @jecogeo does it happens after a "snap to layer" or "snap points to grid"?

You mean in the issue I reported? I don't see how snapping would be necessary for a split. In fact, it appears to me that in most cases the user doesn't want to displace their features before splitting. The split tool should split the features as given, right?

**Comment by gioman** [comment]
> You mean in the issue I reported? I don't see how snapping would be necessary for a split. In fact, it appears to me that in most cases users don't want to displace their features before splitting. The split tool should split the features as given, right?

@jecogeo sorry, I was thinking to another ticket/dataset.

I don't think that the problem is having lines crossing the split layer in the same spot, the following scenario also produces a line that is not split (the rightmost one):

![image](https://user-images.githubusercontent.com/1951107/123849579-dd462d00-d910-11eb-87b2-a66883f70a1a.png)

**Comment by jecogeo** [comment]
> > You mean in the issue I reported? I don't see how snapping would be necessary for a split. In fact, it appears to me that in most cases users don't want to displace their features before splitting. The split tool should split the features as given, right?
> 
> @jecogeo sorry, I was thinking to another ticket/dataset.
> 
> I don't think that the problem is having lines crossing the split layer in the same spot, the following scenario also produces a line that is not split (the rightmost one):
> 
> ![image](https://user-images.githubusercontent.com/1951107/123849579-dd462d00-d910-11eb-87b2-a66883f70a1a.png)

interesting... I haven't thought of testing displacing the split line. So the problem might be on a different rationale. Anyway, worthwhile checking.

**Comment by jecogeo** [comment]
The issue certainly needs to remains open. I gave the feedback needed, so I think the feedback tag must be removed.
