### ISSUE TITLE
Borders in 3D Map not displaying in the right height (z-coordinate) with value from expression

### ISSUE THREAD

**Issue by bmscmoreira** [qgis/QGIS#35672]
**Describe the bug**
Borders in 3D Map not displaying in the right height (z-coordinate) when height and extrusion values are based on an expression which retrieves a value from a table

**How to Reproduce**
1. Create a 3D View and features that display on it with a given height and extrusion as direct numeric input inside the respective input boxes in the layer properties / 3D View, and activate the borders;
2. Check that both volumes and borders are displayed correctly;
3. Change the values of height and extrusion to be fetched from a table by name;
4. Now the volume should be on the right height but the borders do not assume the right height parameter, but the extrusion is taken into account.

**QGIS and OS versions**
Versão do QGIS | 3.12.1-București | Revisão do código do QGIS | 121cc00ff0
Compilado com Qt | 5.12.3 | Em execução com Qt | 5.12.3
Compilado com GDAL/OGR | 2.4.1 | Em execução com GDAL/OGR | 2.4.1
Compilado com GEOS | 3.7.2-CAPI-1.11.2 | Em execução com GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.28.0 | Running against SQLite | 3.28.0
Versão de cliente PostgreSQL | 11.3 | Versão SpatiaLite | 4.3.0a
Versão QWT | 6.1.4 | Versão QScintilla2 | 2.11.1
Compilado com PROJ | 5.2.0 | Em execução com PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS 10.15
Active python plugins | FreehandRasterGeoreferencer; DigitizingTools; layerGroupFilter; QPackage; MapsPrinter; pointsamplingtool; openlayers_plugin; valuetool; processing; db_manager; MetaSearch

**Additional context**
Using rule-based symbol in layer properties / 3d view; the rule is displaying features by filter; height and extrusion are being given by expressions, fetching a numeric value from a table; fixation height = absolute, connection altitude = centroid, culling mode = no culling

![borders-3d-map](https://user-images.githubusercontent.com/3017910/78806935-47487e80-79bb-11ea-90cb-ebb7ee8b7d25.jpg)

**Comment by nyalldawson** [comment]
Fixed in master

**Comment by MauroDallapina** [comment]
Is it possible to fix the same problem in QGIS 3.10 (LTR)?

**Comment by MauroDallapina** [comment]
![QGIS_3D_Edges_Bug](https://user-images.githubusercontent.com/73581448/97425158-02157b00-1912-11eb-86b9-8e5aa6e1ad10.png)
