### ISSUE TITLE
Shape Digitizing 3-Point Rectangle Tool always creates 3D Polygon

### ISSUE THREAD

**Issue by ScottWerkema** [qgis/QGIS#35671]
**Describe the bug**

When using the Shape Digitizing toolbar to create a 3-Point Rectangle (distance and projected), the resultant polygon is always 3D even on a 2D layer. 

**How to Reproduce**

1. Add a layer to a QGIS where the geometry type is a 2D polygon. In my case, this is a PostGIS layer. `geom geometry(Polygon,3857) NOT NULL`
Created using `SELECT AddGeometryColumn ('my_schema','my_spatial_table','geom',3857,'POLYGON',2);`
2. Use the "Add rectangle from 3 points" (either variant) to digitize a rectangle. 
3. Note the resultant rectangle is a 3D polygon and you are unable to save edits to this layer now.

Using other shape tools on the toolbar behave as expected. 

**Expected Result**
The 3-Point rectangle tool should create a 2D polygon for a 2D layer and a 3D polygon for a 3D layer.

**QGIS and OS versions**
macOS 10.15.4
QGIS
3.12.0
3.13 nightly (2020-04-07)

**Additional context**

This appears to be a regression in 3.12 as 3.10 and lower behave as expected.

**Comment by gioman** [comment]
> This appears to be a regression in 3.12 as 3.10 and lower behave as expected.

I confirm the issue but I see the same problem on 3.10.4 I have not tested 3.4

**Comment by gioman** [comment]
Working ok on 3.8, confirmed regression.

**Comment by haubourg** [comment]
Cc @lbartoletti
