### ISSUE TITLE
Value relation widget in attribute form very slow, with hundreds of records

### ISSUE THREAD

**Issue by dd-a** [qgis/QGIS#35693]
I'm trying to make a cascading selection tool in an attribute form, so that the user would select successively a country, then a region then a sub-region, and so on. For this I'm using postgresql tables containing the data coming from [gadm.org](https://gadm.org/download_world.html) and I set filters like ` "name_1"  =  current_value( 'name_1')` in the widget for selecting name_2, and so on.  It works but the problem is that it takes several minutes for each dropdown list to appear, depending on the number of records in the table.  This limits that great functionality to very simple and short relation tables.
I wonder if this is a bug or some technical limitation, but I wish it was faster.
I've used this cascading value relation system often but it is the first time I try it with a somewhat bigger table - always with primary keys - and even with tables limited to two columns (i.e. name_1, name_2).   

On Mac OS 10.15.4, with QGis 3.12.1 and 3.10.4 .

Version de QGIS | 3.12.1-București | Révision du code | 121cc00ff0
-- | -- | -- | --
Compilé avec Qt | 5.12.3 | Utilisant Qt | 5.12.3
Compilé avec GDAL/OGR | 2.4.1 | Utilisé avec GDAL/OGR | 2.4.1
Compilé avec GEOS | 3.7.2-CAPI-1.11.2 | Utilisé avec GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.28.0 | Running against SQLite | 3.28.0
Version du client PostgreSQL | 11.3 | Version de SpatiaLite | 4.3.0a
Version de QWT | 6.1.4 | Version de QScintilla2 | 2.11.1
Compilé avec PROJ | 5.2.0 | Fonctionne avec PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS 10.15

**Comment by gioman** [comment]
@dd-a please attach/link a sample project+data.

**Comment by dd-a** [comment]
@gioman I attach projects and data in 4 different configurations.  
Trying to create this sample I found that the cascading filters are not involved here. It's the total number of records in the tables involved in the relations that determines how long it takes to open the form or do anything (I have a strong linear correlation (R2 = 0.99) with the time it takes to open the form with this total number).  Since I don't have a postgresql server to which I can give an access I put my data in a geopackage and csv files, and I made 4 different projects with different relation settings, i.e. 'no relation', 'one relation to the level 2 data (46700 records)', 'one relation to the level 3 data (170912 records)', 'two relations to the levels 2 and 3 data + cascading'.  
With postgresql I expected to accelerate everything by making all these cascading relations (name_0 > name_1 > name_2 > name_3) but if QGis indexes all the tables involved beforehand, it does not help.  Isn't that counter-productive ? 
[RelationWidgetTest.zip](https://github.com/qgis/QGIS/files/4462654/RelationWidgetTest.zip)

**Comment by elpaso** [comment]
The problem is that if you have dynamic filtering (drill-down) we cannot cache the values, this makes everything slow when you have many rows. You may want to try to setup relations instead.

**Comment by elpaso** [comment]
I checked your project, you don't even set a filter for the second level... You are always loading all features. I don't see a chance to make it faster.
Btw, the filtering happens in the client (in QGIS) and not in the server, this is how it is designed because we use QGIS expressions for the filtering, hence all features are loaded.
