### ISSUE TITLE
3D Map View with fixed map theme applied regenerating tiles on switching themes

### ISSUE THREAD

**Issue by bmscmoreira** [qgis/QGIS#35690]
**Describe the bug**
When a 3D Map view has a theme applied in its 3D configuration window (other than none) and one triggers a theme change in the 2D View, the 3D Map view tiles are regenerated (as if it was expecting a theme change). Since the theme is fixed for the 3D View, a tiles regeneration should not be triggered.
Also noticed a moderate slowdown with a map theme other than "none" on the 3D Configuration and sometimes problems with panning on the 2D view ("sticky pan" as if the left mouse button was always down).

**How to Reproduce**
1. Define some map themes;
2. Create a 3d view with a specific map theme;
3. Switch theme on the layer's panel: the 3D View will be regenerated even if it should be displaying the same theme.

**QGIS and OS versions**
Versão do QGIS | 3.12.1-București | Revisão do código do QGIS | 121cc00ff0
-- | -- | -- | --
Compilado com Qt | 5.12.3 | Em execução com Qt | 5.12.3
Compilado com GDAL/OGR | 2.4.1 | Em execução com GDAL/OGR | 2.4.1
Compilado com GEOS | 3.7.2-CAPI-1.11.2 | Em execução com GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.28.0 | Running against SQLite | 3.28.0
Versão de cliente PostgreSQL | 11.3 | Versão SpatiaLite | 4.3.0a
Versão QWT | 6.1.4 | Versão QScintilla2 | 2.11.1
Compilado com PROJ | 5.2.0 | Em execução com PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS 10.15
Active python plugins | FreehandRasterGeoreferencer; DigitizingTools; layerGroupFilter; QPackage; MapsPrinter; pointsamplingtool; openlayers_plugin; valuetool; processing; db_manager; MetaSearch

**Comment by NEDJIMAbelgacem** [comment]
Hi,
I looked into this issue and for me it didn't happen unless the current 3D view theme is "none" which is normal I think.
I am using ubuntu 18 and compiled using the latest build.

**Comment by Pedro-Murteira** [comment]
@bmscmoreira Hello, is this issue still valid on more recent releases?
