### ISSUE TITLE
herramientas

### ISSUE THREAD

**Issue by franklinllionel** [qgis/QGIS#35697]
hola...tengo un problema con respecto a las herramientas vectoriales y raster, no me aparecen, el error dice que: WARNING    Complemento processing : Este complemento estará deshabilitado porque petó QGIS durante el último arranque. Por favor, envíe un informe y rehabilite el complemento cuando el problema se haya resuelto.
2020-04-09T19:29:09     INFO    Executing

**Comment by gioman** [comment]
@franklinllionel go to plugin manager, re-enable the Processing plugin. Questions must be asked in the users/developers mailing lists.

**Comment by franklinllionel** [comment]
pero como se hace la habilitación?, ese es el problema, por que cuando entro ahi esta todo normal, que complemento se debe instalar? cuando quiero instalar el complemento "processing" se cierra todo el programa. me faltan los compelmentos mas utilizados como todas las herramientas vectoriales y analisis de terreno de raster.
el problema es algo mas tecnico, si se como instalar complementos.

**Comment by roya0045** [comment]
English pls

**Comment by franklinllionel** [comment]
But how is the enablement done ?, That is the problem, why when I go in there is everything normal, what plugin should be installed? When I want to install the "process" plugin, the whole program closes. I am missing the most used components as all the tools used and raster terrain analysis.

the problem is something more technical, if I know how to install plugins.

**Comment by franklinllionel** [comment]
How can I delete the qgis files after uninstalling? because they are left as garbage.

**Comment by roya0045** [comment]
Do you have custom functions ? I assume this might be what is causing the processing crashes.

**Comment by gioman** [comment]
> But how is the enablement done ?

@franklinllionel the QGIS plugin manager



>  When I want to install the "process" plugin

you don't have to install it, it comes by default with any QGIS installation

**Comment by franklinllionel** [comment]
pero cuando lo activo se cierra el programa.

**Comment by gioman** [comment]
> How can I delete the qgis files after uninstalling? because they are left as garbage.

just create a new QGIS profile.

**Comment by franklinllionel** [comment]
ya esta solucionado, muchas gracias.

**Comment by franklinllionel** [comment]
sus graficos estan como en la version antigua (grandes iconos, diferentes colores, etc) pero todo funciona con normalidad..gracias

**Comment by ingridolanda** [comment]
@franklinllionel como solucionaste ese problema en QGIS

**Comment by franklinllionel** [comment]
E creado un nuevo perfil de usuario.

**Comment by franklinllionel** [comment]
ya no me sucede lo mismo cuando cambié de perfil. puedes intentar
desinstalar todos los drivers y carpetas del programa y volver a instalar
todo.
