### ISSUE TITLE
openSUSE 15.1 - nothing provides libgdal.so.20()(64bit)

### ISSUE THREAD

**Issue by arcanelove** [qgis/QGIS#35691]
I'm not convinced this is the right place for this issue but I can't really find anywhere more suitable to submit so please accept my apologies if I should be posting this elsewhere.

I'm trying to install QGIS version 3.12.0-lp151.32.3 onto openSUSE Leap 15.1 using the recommended repository at  https://download.opensuse.org/repositories/Application:/Geo/openSUSE_Leap_15.1/. When examining the package the package manager returns the message 'Nothing provides libgdal.so.20()(64bit)'. I installed libgdal20 version 2.4.3-lp151.3.3.1 and proceeded with breaking QGIS which of course won't run because of the broken dependency. I downgraded libgdal20 to 2.4.2 but receive the same error.

My question then is which version of the GDAL library do I need, or is it in the wrong path? I've been using QGIS on Windows and Mac for 6 years now without much of a hitch, so I was surprised to fall at the first hurdle when installing it on Linux. I suspect I can get around the problem in the short term by using Flatpak but I would prefer a 'native' installation if possible.

Many thanks,

Justin.

**Comment by roya0045** [comment]
This might be better suited for the user and or dev mailing lists. https://qgis.org/en/site/getinvolved/mailinglists.html

**Comment by gioman** [comment]
> This might be better suited for the user and or dev mailing lists. https://qgis.org/en/site/getinvolved/mailinglists.html

agree, questions are to be directed in the official mailing lists, gis stackexchange or the QGIS irc channel.
