### ISSUE TITLE
Probleme pour consulter données littérales base spacialite

### ISSUE THREAD

**Issue by AQUAFONTEDIT** [qgis/QGIS#35707]
IMPORTANT:
## User Feedback

Impossible de consulter la base cadastre intégrée en spatialite 

## Report Details

*Crash ID*: e7652970d1bbdb4e684970c3e4e9c82c66549f1f

*Stack Trace*
<pre>
QgsGeometryCollection::vertexAt :
QgsMapToolIdentify::closestVertexAttributes :
QgsMapToolIdentify::featureDerivedAttributes :
QgsMapToolIdentify::identifyVectorLayer :
QgsMapToolIdentify::identifyLayer :
QgsMapToolIdentify::identify :
QgsMapToolIdentify::identify :
QgsMapToolIdentifyAction::identifyFromGeometry :
QMetaObject::activate :
QgsMapToolSelect::qt_static_metacall :
QgsMapToolSelect::setSelectionMode :
QgsMapToolIdentifyAction::canvasReleaseEvent :
QgsMapCanvas::mouseReleaseEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.8.3-Zanzibar
QGIS code revision: 685d8b15d2
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

Do NOT use GitHub to post any questions or support requests!
They will be closed immediately and ignored.
Questions should go to the qgis-user mailing list at https://lists.osgeo.org/mailman/listinfo/qgis-user
or other support forums such as https://gis.stackexchange.com/.

GitHub issues are for bug reports and suggestions for new features.

**Comment by roya0045** [comment]
Try with a more recent version to see if the problem persists. It also looks like it failed when you used identify instead of loading the data, is this the case?

**Comment by AQUAFONTEDIT** [comment]
Thnaks for answer
I tried to install QGIS Version: 3.12.1 , i cannot open extensions : cadastre 
I have a warning about authentification...
Sorry, it's my first time I use QGIS...

**Comment by roya0045** [comment]
Are you talking about a plugin or base QGIS? If its related to a plugin we cannot do anything and suggest you to contact the author instead.

**Comment by AQUAFONTEDIT** [comment]
The problem is not with extension. All is OK wiy=th extension, I can read data from Spatialite base. When I clic on an item with "Identifier les entités" ( Ctrl maj i ), qgis is blocked...

**Comment by roya0045** [comment]
And if you update your qgis to something more recent and try?

**Comment by AQUAFONTEDIT** [comment]
I update in 3.10.4 A Coruna, il seems to work.
Thanks

**Comment by roya0045** [comment]
If the issue is now solve you can solve this ticket and reopen it if the issue arise again.
