### ISSUE TITLE
Failed to modify items

### ISSUE THREAD

**Issue by AQUAFONTEDIT** [qgis/QGIS#35716]
Hello,
I just install 3.10.4 version
When I try to modify any item, I have a message like this:
Couche Commentaires sur proposition réseau: Erreur OGR lors du paramétrage de l'entité 13 : Failed to open C:/PROGRA1/QGIS31.10/apps/qgis-ltr/./resources/data/world_map.gpkg: Permission denied.
tHe good directory is : C:\Program Files\QGIS 3.10\apps\qgis-ltr\resources\data and not C:/PROGRA1/QGIS31.10/apps/qgis-ltr/./resources/data/
How to change? Thanks>

**Comment by gioman** [comment]
@AQUAFONTEDIT you don't have write permissions for files in

C:/PROGRA1...

copy that datasource in another place, i.e. on your Desktop.

**Comment by AQUAFONTEDIT** [comment]
Sorry There is no data source in this directory...

**Comment by gioman** [comment]
> Couche Commentaires sur proposition réseau: Erreur OGR lors du paramétrage de l'entité 13 : Failed to open C:/PROGRA1/QGIS31.10/apps/qgis-ltr/./resources/data/world_map.gpkg: Permission denied.

"world_map.gpkg" is the datasource, is a Geopackage.

**Comment by Gustry** [comment]
@AQUAFONTEDIT Are you trying to edit `world_map.gpkg` ? This file belongs to QGIS application. You should indeed copy it because it seems you on't have write permissions on that file on your installation.

**Comment by AQUAFONTEDIT** [comment]
No, I try to modify text data in a simple imported KML point layer...

**Comment by gioman** [comment]
> No, I try to modify text data in a simple imported KML point layer...

@AQUAFONTEDIT it is really unclear what you are trying to do and what the problem is. Maybe recording a screencast of the whole process would help up help you.
