### ISSUE TITLE
Impossible enregistrer modifications

### ISSUE THREAD

**Issue by AQUAFONTEDIT** [qgis/QGIS#35715]
Bonjour
Je viens d'installer la version 3.10.4 , 
Quand je veux enregistrer une modification , j'ai le message d'erreur:
Couche Commentaires sur proposition réseau: Erreur OGR lors du paramétrage de l'entité 13 : Failed to open C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./resources/data/world_map.gpkg: Permission denied.
Le  bon repertoire est : C:\Program Files\QGIS 3.10\apps\qgis-ltr\resources\data
Comment modifier?
Merci

**Comment by gioman** [comment]
@AQUAFONTEDIT please file tickets in English, thanks for understanding.

**Comment by AQUAFONTEDIT** [comment]
Hello,
I just install 3.10.4 version
When I try to modify any item, I have a message like this:
Couche Commentaires sur proposition réseau: Erreur OGR lors du paramétrage de l'entité 13 : Failed to open C:/PROGRA1/QGIS31.10/apps/qgis-ltr/./resources/data/world_map.gpkg: Permission denied.
tHe good directory is  : C:\Program Files\QGIS 3.10\apps\qgis-ltr\resources\data and not C:/PROGRA1/QGIS31.10/apps/qgis-ltr/./resources/data/
How to change? Thanks

**Comment by gioman** [comment]
@AQUAFONTEDIT you don't have write permissions for files in

C:/PROGRA1...

copy that datasource in another place, i.e. on your Desktop.
