### ISSUE TITLE
Les extensions son bloquées

### ISSUE THREAD

**Issue by Brassellea** [qgis/QGIS#35723]
Bonjour,
A l'ouverture de qgis 3.10, les 2 messages d'erreur suivants apparaissent, QGIS se lance cependant il n'y a pas d'accès aux extensions. Il n'y a pas de problème avec la version 3.4. 
Tous les chemins d'accès propres à ma machine sont floutés

Le premier 

> Une erreur est survenue lors de l'exécution du code suivant:
> import pyplugin_installer
> 
> Traceback (most recent call last):
>   File ".../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pgRoutingLayer\connectors\postgis.py", line 162, in __init__
>     self.con = psycopg2.connect(self.connection_info(), connect_timeout=5)
>   File "...\apps\Python37\lib\site-packages\psycopg2\__init__.py", line 126, in connect
>     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
> psycopg2.OperationalError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File ".../apps/qgis-ltr/./python\qgis\utils.py", line 359, in startPlugin
>     plugins[packageName].initGui()
>   File ".../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pgRoutingLayer\pgRoutingLayer.py", line 240, in initGui
>     self.reloadConnections()
>   File ".../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pgRoutingLayer\pgRoutingLayer.py", line 272, in reloadConnections
>     db = self.actionsDb[dbname].connect()
>   File ".../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pgRoutingLayer\dbConnection.py", line 152, in connect
>     conn = ConnectionManager.getConnection(self.type).connect(selected, self.parent())
>   File ".../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pgRoutingLayer\connectors\postgis.py", line 149, in connect
>     return Connection(uri)
>   File ".../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pgRoutingLayer\connectors\postgis.py", line 164, in __init__
>     raise DbError(e)
>   File ".../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pgRoutingLayer\connectors\postgis.py", line 87, in __init__
>     msg = str(error.args[0])
> IndexError: tuple index out of range
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "", line 1, in 
>   File ".../apps/qgis-ltr/./python\qgis\utils.py", line 362, in startPlugin
>     _unloadPluginModules(packageName)
>   File ".../apps/qgis-ltr/./python\qgis\utils.py", line 466, in _unloadPluginModules
>     for path in sys.modules[mod].__path__:
>   File "", line 1115, in __iter__
>   File "", line 1103, in _recalculate
>   File "", line 1099, in _get_parent_path
> KeyError: 'pgRoutingLayer'
> 
> 
> Version de Python :
> 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]
> 
> Version de QGIS :
> 3.10.4-A Coruña 'A Coruña', 10bc9f2ff2
> 
> Chemin vers Python : []

Puis le second

> Une erreur est survenue lors de l'exécution du code suivant:
> pyplugin_installer.initPluginInstaller()
> 
> Traceback (most recent call last):
>   File "", line 1, in 
> NameError: name 'pyplugin_installer' is not defined
> 
> Version de Python :
> 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]
> 
> Version de QGIS :
> 3.10.4-A Coruña 'A Coruña', 10bc9f2ff2
> 
> Chemin vers Python : []

**Comment by Gustry** [comment]
```
File ".../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pgRoutingLayer\connectors\postgis.py", line 87, in init
```

Ton problème vient de `pgRoutingLayer`, QGIS ne peut rien faire et ce bug doit être remonté à l'auteur du plugin.
Supprime le plugin et cela marchera.

The issue is the plugin `pgRoutingLayer`. You should disable it and report to plugin author.
