### ISSUE TITLE
Q GIS Quick Map Services Plugin

### ISSUE THREAD

**Issue by mdnafil** [qgis/QGIS#35729]
Hello,

While working on QGIS, I accessed the settings of quick map services plugin and tried getting more services. The QGIS stopped respong after displaying error. After closing QGIS it displayed QGIS- ltr bin.exe is not responding. I missed on the error which was reported while getting more services. If it is required, you can email me on md.nafil@live.in.

**Comment by roya0045** [comment]
Not responsible for plugins.

**Comment by m-kuhn** [comment]
Please fill a bug in the Quick Map Services Plugin.

See https://plugins.qgis.org/plugins/quick_map_services/ -> Details -> Tracker.

**Comment by mdnafil** [comment]
> Please fill a bug in the Quick Map Services Plugin.
> 
> See https://plugins.qgis.org/plugins/quick_map_services/ -> Details -> Tracker.

Thank you.
