### ISSUE TITLE
Crash when using line editing

### ISSUE THREAD

**Issue by mylesmcd** [qgis/QGIS#35728]
## User Feedback

Was using the 'extend line' feature in the advanced editing toolbar (dataset held in Postgres online DB)

## Report Details

**Crash ID**: [7653cef84568c75930d883a0d31abcc9fc8179dc]('https://github.com/qgis/QGIS/search?q=7653cef84568c75930d883a0d31abcc9fc8179dc&type=Issues')

**Stack Trace**
<pre>
pal::LabelPosition::getProblemFeatureId labelposition.h:181
QgsMapToolTrimExtendFeature::canvasMoveEvent qgsmaptooltrimextendfeature.cpp:92
QgsMapCanvas::mouseMoveEvent qgsmapcanvas.cpp:1727
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1607
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.3-A Coru�a
QGIS code revision: 0e1f846438
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by roya0045** [comment]
Seem to be related to labelling possibly.

**Comment by gioman** [comment]
@mylesmcd please attach a sample project (with sample data) and detail the exact steps to follow to replicate the crash, thanks.

**Comment by gioman** [comment]
Closing for lack of feedback.
