### ISSUE TITLE
crash entering Qgis 3.12

### ISSUE THREAD

**Issue by davidmanuelmoronta** [qgis/QGIS#35746]
Crash ID: 7c8e619fd720186396d695bd0a01590b46444c3e

Stack Trace

operatoroperatorQMetaType::save :
QVariant::save :
operatorQSettings::value :
QSettings::value :
QSettings::sync :
QThreadPool::maxThreadCount :
QSettings::~QSettings :
QSettings::`scalar deleting destructor' :
QgsSettings::~QgsSettings qgssettings.cpp:83
QgsNewsFeedParser::onFetch qgsnewsfeedparser.cpp:169
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QCoreApplication::processEvents :
QgisApp::QgisApp qgisapp.cpp:1271
main main.cpp:1355
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.12.1-Bucure?ti
QGIS code revision: 121cc00ff0
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment]
@davidmanuelmoronta please try with a new QGIS profile, no 3rd party plugins installed. If the problem persist please add the **extact** steps to follow that lead to the crash. Thanks.

**Comment by gioman** [comment]
Closing for lack of feedback.
