### ISSUE TITLE
Heatmap Kernel Density Estimation giving strange results

### ISSUE THREAD

**Issue by alanterra** [qgis/QGIS#35747]
**Description**

In QGIS 3.12.1, the heatmap tutorial titled "Creating Heatmaps (QGIS3)" at QGIS Tutorials and Tips, v 1.0, at step 23, gives different results than shown in the tutorial, and results that are clearly incorrect. Doing the tutorial with QGIS 3.10.2 gives the same results as shown in the tutorial.

This appears to be a bug in the "Heatmap (Kernel Density Estimation)" tool in the Processing Toolbox.

**How to Reproduce**

Install QGIS 3.12.1 (I re-installed this on my Macintosh running MacOS Mojave 10.14.6) and go through the tutorial at https://www.qgistutorials.com/en/docs/3/creating_heatmaps.html.

When I do step 23 in QGIS 3.12.1, I get the following:

<img width="1198" alt="Screen Shot 2020-04-13 at 12 41 13" src="https://user-images.githubusercontent.com/6795475/79154254-18982280-7d84-11ea-988f-63ca2a65f625.png">

If I do the same exercise with QGIS 3.10.2, I get the following, which is very similar to the image shown in the tutorial.

<img width="1194" alt="Screen Shot 2020-04-13 at 12 41 45" src="https://user-images.githubusercontent.com/6795475/79154307-2baaf280-7d84-11ea-8949-85c7faf2b89d.png">

While this grayscale image is hard to interpret, if you change the style of the layer, you will see that the first heatmap shown above shows broad areas of "heat" (high density) about 10 km NW of the actual areas of high density of the point cloud.

I am very much a noobie with QGIS (hence that is why I am doing these tutorials), but I am pretty sure that this is a bug and not user error. I don't think it is worthwhile for me to give a precise recipe for reproducing this bug, as I get it when I follow the tutorial exactly.

I downloaded a fresh copy of QGIS 3.12.1 and replicated the bug. If others cannot replicate it, I will give a complete step-by-step, including a project file and layers.

**QGIS and OS versions**
Bug found in this QGIS version:

QGIS version | 3.12.1-București | QGIS code revision | 121cc00ff0
-- | -- | -- | --
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.28.0 | Running against SQLite | 3.28.0
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS Mojave (10.14)
Active python plugins | QuickOSM; quick_map_services; nominatim; processing; db_manager; MetaSearch

Bug not seen in this version:

QGIS version | 3.10.2-A Coruña | QGIS code revision | 616ad4531b
-- | -- | -- | --
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.28.0 | Running against SQLite | 3.28.0
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS Mojave (10.14)
Active python plugins | QuickOSM; quick_map_services; nominatim; processing; db_manager; MetaSearch

MacOS Mojave 10.14.6

**Additional context**

None

**Comment by roya0045** [comment]
Duplicate of #39458 which should now be solved.

**Comment by alanterra** [comment]
Thank you
