### ISSUE TITLE
GDAL build virtual raster/vector broken

### ISSUE THREAD

**Issue by kaptainkory** [qgis/QGIS#35755]
Throwing a python error:

An error has occurred while executing Python code: 

AttributeError: 'NoneType' object has no attribute 'setWidgetContext' 
Traceback (most recent call last):
  File "/usr/share/qgis/python/plugins/processing/gui/ProcessingToolbox.py", line 262, in executeAlgorithm
    dlg = AlgorithmDialog(alg, self.in_place_mode, iface.mainWindow())
  File "/usr/share/qgis/python/plugins/processing/gui/AlgorithmDialog.py", line 67, in __init__
    self.setMainWidget(self.getParametersPanel(alg, self))
  File "/usr/share/qgis/python/plugins/processing/gui/AlgorithmDialog.py", line 88, in getParametersPanel
    panel = ParametersPanel(parent, alg, self.in_place)
  File "/usr/share/qgis/python/plugins/processing/gui/ParametersPanel.py", line 67, in __init__
    self.initWidgets()
  File "/usr/share/qgis/python/plugins/processing/gui/ParametersPanel.py", line 154, in initWidgets
    wrapper.setWidgetContext(widget_context)
AttributeError: 'NoneType' object has no attribute 'setWidgetContext'

Python version: 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0] 
QGIS version: 3.13.0-Master Master, 2022848492 

Python Path:
/usr/share/qgis/python
/home/kaptainkory/.local/share/QGIS/QGIS3/profiles/default/python
/home/kaptainkory/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/home/kaptainkory/.local/lib/python3.6/site-packages
/usr/local/lib/python3.6/dist-packages
/usr/lib/python3/dist-packages
/usr/lib/python3.6/dist-packages
/home/kaptainkory/.local/share/QGIS/QGIS3/profiles/default/python
/media/files/Home Files/Documents/Herpetology/AR Herp Atlas

**How to Reproduce**

Attempt to open GDAL "build virtual raster" or "build virtual vector" from Processing Toolbox.

**QGIS and OS versions**

QGIS version | 3.13.0-Master | QGIS code revision | 2022848492
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.6.2-CAPI-1.10.2 4d2925d6
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 10.12 (Ubuntu 10.12-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Linux Mint 19.3 | This copy of QGIS writes debugging output.
Active python plugins | latlontools; processing; db_manager; DataPlotly

**Additional context**

Other GDAL algorithms seem to open input windows correctly, but I didn't check every single one.

**Comment by gioman** [comment]
Confirmed on both Linux and Windows.

**Comment by gioman** [comment]
It affects master and 3.12 but not 3.10 ltr.

**Comment by agiudiceandrea** [comment]
@gioman, I cannot reproduce with QGIS 3.12.0 (cd141490ec) on Windows.

**Comment by gioman** [comment]
> @gioman, I cannot reproduce the issue with QGIS 3.12.0 ([cd14149](https://github.com/qgis/QGIS/commit/cd141490eccf4340b658eab7fab1e7fb80c06214)) on Windows.

@agiudiceandrea I tried on 3.12.1 from OSGeo4W, not standalone and on master on Ubuntu Linux 18.04.

**Comment by agiudiceandrea** [comment]
So... it could be some change between 3.12.0 and 3.12.1 https://github.com/qgis/QGIS/compare/final-3_12_0...final-3_12_1

**Comment by agiudiceandrea** [comment]
I cannot reproduce the issue also with QGIS 3.12.1 (121cc00ff0), standalone installer QGIS-OSGeo4W-3.12.1-1-Setup-x86_64.exe, on Windows 10 64 bit 

![Annotazione 2020-04-15 222359](https://user-images.githubusercontent.com/16253859/79384839-e515ed80-7f67-11ea-892e-80fc75a5d915.png)

**Comment by gioman** [comment]
@agiudiceandrea it does not happen here on QGIS in EN on Windows in EN butit happens happens on a localized QGIS on a localized Windows (tested Italian and Portuguese). But also happens on Linux (ubuntu 18.04) all in EN.

**Comment by agiudiceandrea** [comment]
It's really strange...

I did the previous tests with <ins>QGIS localized in English</ins> (User Interface Translation: American English, Locale: Italian Italy it_IT or Locale: English UnitedStates en_US) on <ins>Windows localized in Italian</ins>.

I did the test again with <ins>QGIS localized in Italian</ins> (User Interface Translation: Italiano, Locale: Italian Italy it_IT) on <ins>Windows localized in Italian</ins>, but I can open both the GDAL "Build virtual raster" / "Crea raster virtuale" and "Build virtual vector" / "Crea vettore virtuale" from Processing Toolbox...

![Annotazione 2020-04-16 194806](https://user-images.githubusercontent.com/16253859/79491160-52845580-801e-11ea-96cf-9b73984221a5.png)

Python version 3.7.0 (python3-core-3.7.0-4)
pyqt5 5.11.3 (pyqt5-5.11.3-2)
Qt 5.11.2 (qt5-libs-5.11.2-1)

**Comment by nyalldawson** [comment]
I think any issues in 3.12 must be a different cause -- the code wasn't touched recently in 3.12
