### ISSUE TITLE
Removing layout page does not delete map contents

### ISSUE THREAD

**Issue by NyakudyaA** [qgis/QGIS#35768]
# Problem

When you have a multi-page layout and you try to delete a page. All the map contents are shifted to the page above. This should not be the case. A user who chooses to delete a page should know that all the map contents on that page are also going to be deleted.

![save](https://user-images.githubusercontent.com/2510900/79234555-b82fe080-7e6a-11ea-9c85-fd2b62d602e6.gif)

**Comment by gioman** [comment]
@NyakudyaA I think this is arguable: I personally prefer as it is because is safer. If I want to delete a page an all of its objects then select first all the objects, delete them pressing "del" and then delete the page.

**Comment by NyakudyaA** [comment]
> @NyakudyaA I think this is arguable: I personally prefer as it is because is safer. If I want to delete a page an all of its objects then select first all the objects, delete them pressing "del" and then delete the page.

Fair point @gioman. Maybe a message to tell users that deleting the page will shift the map contents because I think in most software deleting the page will just assume everything on the page will be deleted.

**Comment by DelazJ** [comment]
Duplicates #26618 imho. Also see outcome of #30000

**Comment by gioman** [comment]
> Duplicates #26618 imho

@DelazJ thanks, you are right.
