### ISSUE TITLE
Problemas en la calculadora raster

### ISSUE THREAD

**Issue by Fertuesta25** [qgis/QGIS#35769]
Cuando ejecuto la siguiente expresión: "Imagen" = 5463 debería clasificar la imagen resultante en dos valores es decir 0 y 1, esto es algo que en la versión 3.4 si resultaba. Sin embargo en la versión 3.12 todo se clasifica con el valor 0.

**Comment by gioman** [comment]
@Fertuesta25 please re-file the ticket with subject and description in English. Thanks for understanding.

**Comment by gioman** [comment]
@Fertuesta25 also add **all** the requested informations like: QGIS version, Operating System and attach a sample of data.
