### ISSUE TITLE
CRS Projections not working...

### ISSUE THREAD

**Issue by oroboropia** [qgis/QGIS#35772]
whenever I try to change the CRS, the projection doesn't load... 

possible issues? possible fixes?

**Comment by oroboropia** [comment]
Error message:

forward transform of
(inf, inf)
Error: Fallback transform failed

**Comment by gioman** [comment]
@oroboropia Please add all the **requested** informations:

1) QGIS version

2) Operatying System

3) full list of steps you are following (in detail)

4) obtained VS expected results

5) attach (as zip) a sample project with data

**Comment by nyalldawson** [comment]
Closing due to lack of feedback
