### ISSUE TITLE
Scale dependent snapping has min and max inverted

### ISSUE THREAD

**Issue by uclaros** [qgis/QGIS#35786]
**Describe the bug**
Since scale is a fraction `1:500 > 1:1000000`, min scale should be the most zoomed out scale, max scale should be the most zoomed in scale, just like scale dependent layer visibility does it.

Also the tooltip should state "zoomed-in" and "zoomed-out" as in scale dependent visibility to avoid any further confusion.

**Comment by roya0045** [comment]
Sometime people don't think of the '1:' part and just focus on the number. Bigger number = max smaller number = min. So this can also be understood, especially when only the divider is provided by the user.

**Comment by lbartoletti** [comment]
cc @obrix @troopa81

**Comment by obrix** [comment]
Hello and thank you @uclaros. Yep you are right, in the code only the denominator is handled, this is where the error comes from. The behavior should be coherent with the other qgis features so I will change it.
Labeling should also be like the one from the scale dependent layer visibility feature to avoid any confusion for the user.

**Comment by uclaros** [comment]
This is fixed in #35798 so I guess it can close.

**Comment by roya0045** [comment]
@uclaros you have the power to close this if you want.

**Comment by uclaros** [comment]
Doh!
