### ISSUE TITLE
Accept boolean type when loading CSV file

### ISSUE THREAD

**Issue by ygversil** [qgis/QGIS#35784]
**Feature description.**

QGIS would be greater if it recognizes boolean typed columns in CSV files, and/or accept `Integer(Boolean)` header in CSVT companion file.

**Additional context**

I acknowledge that it may be tricky to automatically assign boolean type to a column. What would be the values?

* `1` and `0`? But these can be integers,
* `true` and `false`, or even `t` and `f` as in PostgreSQL COPY ? But these can be just comments and thus strings.

But at least, it would be great to recognize `Integer(Boolean)` in a companion CSVT file (as does GDAL/OGR) and then convert associated columns to boolean. Just like it already does for date/time columns by the way.

**Comment by alexbruy** [comment]
Implemented in #46236.
