### ISSUE TITLE
Scale dependent snapping disabled drop downs

### ISSUE THREAD

**Issue by uclaros** [qgis/QGIS#35789]
**Describe the bug**
When switching *Scale dependent snapping* from *per layer* to *disabled* while the min or max drop down is focused, the widget is not disabled and its values can be be changed.
Additionally, when switching to *per layer* sometimes the min and max drop down widgets are not enabled and can't be clicked.

See the following screencast for both (clicking is not visible, but you can presume when I clicked)
![Peek 2020-04-15 13-24](https://user-images.githubusercontent.com/11358178/79328171-49ac5a80-7f1e-11ea-8694-b7927b545e28.gif)

**Comment by obrix** [comment]
I can reproduce the first bug but cannot reproduce the second one yet.
Anyway I rewrote the way the view is refreshed by resetting the tree view when the snapping scale mode is changed. This fix the first one for sure, it may fix the second one also. I will open a pull request.

**Comment by uclaros** [comment]
The second one appeared while recording the screencast for the first, I hadn't seen it till then. I can't reproduce it either!
