### ISSUE TITLE
Hello. I am using qgis 3.12 in ubuntu 18.4. My problem is in qgis .ecw file can not show. i find solution in many places but that is not satisfied me so what shoud i do now. i am a begenner user of qgis and ubuntu also. so please save me from this problem. Thank You so much in advance.

### ISSUE THREAD

**Issue by anikshaikh** [qgis/QGIS#35791]
IMPORTANT:

Do NOT use GitHub to post any questions or support requests!
They will be closed immediately and ignored.
Questions should go to the qgis-user mailing list at https://lists.osgeo.org/mailman/listinfo/qgis-user
or other support forums such as https://gis.stackexchange.com/.

GitHub issues are for bug reports and suggestions for new features.

**Comment by gioman** [comment]
@anikshaikh please post questions in the users/developers mailing lists.

Anyway about your problem: ECW is a closed format, to allow QGIS read it the support must be added to the GDAL library, that QGIS uses to read/write many data formats. This support is added through proprietary (closed) libraries that come with their own specific license and terms of use. A version of the library to just read ECW files  is available in QGIS installers for Windows. For Linux  it more difficult. In the past it was available an SDK that could be used to add ECW support to GDAL. Not sure if it is still available or if the company that hold the copyrights on the format distributes pre-compiled binaries for Linux. In other words... stay away from ECW if you can, or just use a Windows installation of QGIS to read your ECWs and make copies of them in more friendly formats (i.e. GeoTiffs with compression).

**Comment by eusoubrasileiro** [comment]
From here.  This seams to work. I think GDAL needs to put more effort on Linux as well on Windows.

https://www.reddit.com/r/QGIS/comments/icw98f/problem_loading_ecw_file_in_ubuntu_linux/

```
# First download zip file bellow from https://download.hexagongeospatial.com/downloads/ecw/erdas-ecw-jp2-sdk-v5-4-linux

unzip [erdas-ecw-sdk-5.4.0-linux.zip](https://erdas-ecw-sdk-5.4.0-linux.zip/)

chmod +x ERDAS_ECWJP2_SDK-5.4.0.bin

# Run bin - Choose Option 1. Desktop_Read-Only

./ERDAS_ECWJP2_SDK-5.4.0.bin

# Copy installed files to /usr/local

cp -r hexagon/ERDAS-ECW_JPEG_2000_SDK-5.4.0/Desktop_Read-Only/ /usr/local

# Make symbolic link to libNCSEcw.so.5.4.0

ln -s /usr/local/Desktop_Read-Only/lib/newabi/x64/release/libNCSEcw.so.5.4.0 /usr/local/lib/libNCSEcw.so.5.4.0

# Download GDAL- QGIS 3.4 uses gdal 2.2.3 but I downloaded 2.2.4

wget -c http://download.osgeo.org/gdal/2.2.4/gdal-2.2.4.tar.gz

tar -xvzf gdal-2.2.4.tar.gz

cd gdal-2.2.4

#Find option ECW = yes after configure

./configure --with-ecw=/usr/local/Desktop_Read-Only

# Compile- takes about 1 hour

make

make install

# Set variables

echo 'export LD_LIBRARY_PATH=/usr/local/lib' >> ~/.profile

echo 'export LD_LIBRARY_PATH=/usr/local/lib' >> ~/.bashrc

GDAL_DATA="/usr/local/share/gdal"

ldconfig

# Check if ECW is installed

gdalinfo -formats | grep ECW
```

**Comment by nyalldawson** [comment]
@eusoubrasileiro 

It's not gdal's fault -- it's hexagon's fault, and the fact that ECW is a secret, proprietary format. You should pressure them to open the specifications and then this could work out of the box

**Comment by eusoubrasileiro** [comment]
@nyalldawson yeah you are right. I was confused by the fact that windows has support for ecw. 
Although some formats will never be open. It's not profitable. For then we must accept the fact. Don't know if this is the case for ecw. 
But thanks anyway.
