### ISSUE TITLE
QGis Extension QField : changing type numeric

### ISSUE THREAD

**Issue by gsollberger** [qgis/QGIS#35792]
Hi,
A QGis project is connected to 2 postgres/postgis layers : eu_grille_pg09 and eu_chambre_pg10. 
This layers contain char attributes and numeric attributes, for exmple 'alt_couv' defined with double precision in postgres.
Extension QField "transform" this QGis project in QField project with gpkg data ... *et là c'est le drame" ... the numeric attributes are not decimal : 
![Annotation 2020-04-15 133805](https://user-images.githubusercontent.com/4537306/79333178-5af56700-7f1e-11ea-868e-062af9bf3121.png)
Impossible to enter an altitude without decimal numbers.

Any one for a solution ?

Thank's a lot and best regards.

Gérard Sollberger
HKD Géomatique Vaud SA

My environnement : 
- QGis 3.12.1
- QField Sync extension : 3.1.6
- postgres 9 et 10
- QField on dive Mobile : 1.4.4
- Device mobile : Samsung Galaxy Tab Active 2
[tmp-qfield.zip](https://github.com/qgis/QGIS/files/4480974/tmp-qfield.zip)

**Comment by gioman** [comment]
> Extension QField

@gsollberger do you mean QField sync?

**Comment by gsollberger** [comment]
Yes i do, sorry for the imprecision.

**Comment by gioman** [comment]
> Yes i do, sorry for the imprecision.

@gsollberger no problem, but then you must submit this ticket in the QField/QField sync bug tracker, not QGIS's one.
