### ISSUE TITLE
CRS customization

### ISSUE THREAD

**Issue by EmirCaldeira** [qgis/QGIS#35817]
I found a bug when i tried to customize CRS. I tried putting the parameters to create a new CRS to  Albers Projection with instructions for Instituto Brasileiro de Geografia e Estatística (IBGE), organization responsible for cartographic brazilian policies. QGIS returned me the following bug:

**"Custom Coordinate Reference System
Cannot save '*SRC gerado (+proj=merc+lon_0=0 +lat_ts=0 +x_0=0 +y_0=0 +ellps=WGS84 +units=m _no_defs)' - this Proj string definition is equivalente to ESRI:54004.
Try changing the CRS definition to a WKT format instead"**

I'm using QGIS 3.10.4 and win10 64 bits
The parameters i tried to use were:
**"+proj=aea +lat_1=10 +lat_2=-40 +lat_0=-25 +lon_0=-50 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"**

**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by gioman** [comment]
@EmirCaldeira works fine here on the latest 3.10, 3.12 and master on Windows 10.

**Comment by nyalldawson** [comment]
Follow the instructions in the warning and change the format drop down to "wkt"
