### ISSUE TITLE
[Modeler] Make input variable available in the model expression scope

### ISSUE THREAD

**Issue by roya0045** [qgis/QGIS#35818]
@nyalldawson Maybe this is done already and not in the version that I am using, if so please close this.

I would like to have inputs and other elements to be available throughout a model by adding them to the model scope. The name should be the name of the parameter itself.

This would help to use those elements in expressions and use elements from more than one layer and more complex expression.

In this sense a new item/function could also be made to explicitly add a variable to the model scope.

**Comment by nyalldawson** [comment]
This is already done. They are available directly as variables and also through the 'parameter' function

**Comment by roya0045** [comment]
@nyalldawson Ah I must have missed it when checking the code. Could you tell me when it was done? I'm still running 3.4 at work and waiting until the legend can do aggregate before upgrading and in the other version that I use ( my custom branch from MXE), I don't have the processing plugin to validate.

**Comment by nyalldawson** [comment]
I think 3.0?

**Comment by roya0045** [comment]
@nyalldawson are they listed in the expression dialog or only accessible somehow in the model without clear guidance of the available variables? I'll need to have a look again in this case.

Thanks.
