### ISSUE TITLE
Problems whit encoding in processing "native:saveselectedfeatures "

### ISSUE THREAD

**Issue by diezrabanos** [qgis/QGIS#35816]
When I export the selected elements of a layer that contains a Ñ in the attribute table the encoding is wrong when I do it with the processing "native: saveselectedfeatures" and well if I do it from "Export"> "Save Selected Feature .." Save only selected features ".

I work whit Windows 10 and QGIS 3.10

**Comment by gioman** [comment]
@diezrabanos can you please attach sample data? Thanks.

**Comment by diezrabanos** [comment]
[example.zip](https://github.com/qgis/QGIS/files/4488957/example.zip)

**Comment by gioman** [comment]
@diezrabanos works as expected here. Operatying system in EN and QGIS in EN.

**Comment by diezrabanos** [comment]
Thanks
