### ISSUE TITLE
Table field names are truncated to 10 chars

### ISSUE THREAD

**Issue by AlexanderGrigoryev** [qgis/QGIS#35823]
**Describe the bug**

I am trying to fix defects with encoding of field names in Russian.
In the loop, I replace the name of the table field with the original one. For Mapinfo files, field names are replaced and updated correctly. For shape-files, the field names are replaced correctly, but are truncated to 10 characters after updating. 

This is code which reproduced the bug.

`new_layer` - shape-file layer
`layer` - database table layer

![image](https://user-images.githubusercontent.com/30285620/79535209-faddfc80-80a6-11ea-91dc-7d85701d4899.png)

and as text:
            try:
                new_layer.dataProvider().setEncoding(layer.dataProvider().encoding())
                print(10*'-'+layer.name()+70*'-')
                for new_field, field in list(zip(new_layer.fields(), layer.fields())):
                    print('было: %s, стало: %s' % (new_field.name(), field.name()))
                    new_field.setName(field.name())
                    print('стало факт: %s' % new_field.name())
                new_layer.updateFields()
                for new_field in new_layer.fields():
                    print('стало после апдейта: %s' % new_field.name())
            except AttributeError:
                pass

**How to Reproduce**

1. create table with long (more then 10 symbols) field names
2. create layer and set table as data source
3. export layer to shape-file (`QgsVectorFileWriter.writeAsVectorFormat(table_layer, file_layer, export_options)`)
4. apply code example from "describe bug" in console
5. analyze log

![image](https://user-images.githubusercontent.com/30285620/79538235-2dd7be80-80ae-11ea-97d2-1627f2da0fd1.png)

Red line is `new_layer.updateFields()`

**QGIS and OS versions**

Версия QGIS
3.4.4-Madeira
Ревизия
f6ddc62fdb
Версия Qt при сборке
5.11.2
Текущая версия Qt
5.11.2
Версия GDAL/OGR при сборке
2.4.0
Текущая версия GDAL/OGR
2.4.0
Версия GEOS при сборке
3.7.0-CAPI-1.11.0
Текущая версия GEOS
3.7.0-CAPI-1.11.0 673b9939
Версия PostgreSQL
9.2.4
Версия SpatiaLite
4.3.0
Версия QWT
6.1.3
Версия QScintilla2
2.10.8
Compiled against PROJ
520
Running against PROJ
5.2.0

**Comment by m-kuhn** [comment]
Shapefile has a 10 character limit by definition (http://switchfromshapefile.org/)
You can configure an alias inside qgis to work around this limitation in the gui.

**Comment by AlexanderGrigoryev** [comment]
Can You give me correct aliases filling example? I'm trying this, but has no aliases filled.

**Comment by m-kuhn** [comment]
Please ask on one of the support channels (https://www.qgis.org/en/site/forusers/support.html).

**Comment by AlexanderGrigoryev** [comment]
thanks
