### ISSUE TITLE
QgsProcessingParameterFolderDestination is not visible as input for other algs in modeler

### ISSUE THREAD

**Issue by luipir** [qgis/QGIS#35829]
**Describe the bug**
processing parameter using QgsProcessingParameterFolderDestination is nott available as input in following algorithms used in a modeler.
Despite others derived from QgsProcessingDestinationParameter as QgsProcessingParameterFileDestination, this parameter is not available as input.

**How to Reproduce**
1. Create a pyqgis alg using:
`param = QgsProcessingParameterFolderDestination('OUTPUT', 'Output')
self.addParameter(param)`
2. Create a model il graphical modeler that use the als as in 1)
3. Create a new alg having a parameter that have to be initialize as "Algorithm output"
4. Scroll th elist of available Algorithm output => the output of algorithm added in 2 is not available

**QGIS and OS versions**

!!!The same happen in master  https://github.com/qgis/QGIS/commit/8addbde0a5  !!!

QGIS version | 3.10.4-A Coruña | QGIS code revision | 961b3eee10
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 12.2 (Ubuntu 12.2-2.pgdg18.04+1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Ubuntu 18.04.4 LTS | This copy of QGIS writes debugging output.
Active python plugins | plugin_reloader; IPyConsole; pluginbuilder3; copernicushub; firstaid; epyris; db_manager; processing; MetaSearch

**Comment by alexbruy** [comment]
Fixed by #35862.

**Comment by luipir** [comment]
First of all, thanks for the fix @nyalldawson :)

Then some considerations... would make sense to have compatibile roles?
From the maintenence point of view, finding all the classes that have to be touched to add compatibleOutputTypes would increase adding new widget or parameter definitions.
A possibile simplification is that any widget wrapper would belong to one of multiple compatible roles. Then a parameter definition can be registered to one os multiple roles.
The complexity would be reduced to a good role abstraction (if possibile).
