### ISSUE TITLE
Can't remove an expression at  'Control feature rendering order'

### ISSUE THREAD

**Issue by jeroenrijsdijk** [qgis/QGIS#35845]
**Describe the bug**
If you add an expression in the expression list, you caný remove it anymore. 

**How to Reproduce**
1. goto layer properties
2. check the box 'Control feature rendering order'
3. Add an expression in [1], and a second one in [2]. 
4. press OK
5. now go back to Control feature rendering order, and try to delete the second expression

**Comment by gioman** [comment]
>     5\. and try to delete the second expression

@jeroenrijsdijk clean the text in the column "expression" and press enter.

**Comment by jeroenrijsdijk** [comment]
if I press Enter, it copies the value in the first expression 
![image](https://user-images.githubusercontent.com/23061463/79720399-c8b7df00-82e0-11ea-97db-83da82ab9a2d.png)

**Comment by gioman** [comment]
> if I press Enter, it copies the value from the first expression

@jeroenrijsdijk you are not doing what I suggested: first you must **clean** the expression (select the expression text and remove it) then you press enter.

**Comment by jeroenrijsdijk** [comment]
I _was_ doing what you asked.  Anyway I found an bypass: after opening the expression Dialog you can remove it there.

**Comment by andrewharvey** [comment]
I think this should be reopened as it's still an issue, yes the workaround of selecting the expression and deleting the content works, but this is not obvious for new users. I got stuck on this myself and a simple right click delete or trash icon on the right side would be a better UX.
