### ISSUE TITLE
Empty frames exported from 3D View animation

### ISSUE THREAD

**Issue by adamsss92** [qgis/QGIS#35847]
**Describe the bug**
I prepare animation with orthophotomap as basemap in the 3D View window. I tried to export this animation as frame images. Unfortunetaly, exported frames are empty images. File weight of all of these images is the same - 9KB (it's weight of empty image in 800x600pix resolution). I change some parameters of 3D View and exported frames but with no result. There is no any error during exporting. 
I wanted to rule out the influence of the type of displayed data, which is why I repeated the steps for a simple vector layer. The effect is the same.

**How to Reproduce**

1. Go to 'View'
2. Click on '3D View'
3. Prepare animation
3. Click on 'Export image frames'

![qgis](https://user-images.githubusercontent.com/38074065/79684562-b4b5a400-8232-11ea-8f14-72ac8c2fffd1.png)

**QGIS and OS versions**

The current released version of QGIS is 3.12.1. 
We are working on 3.13-Master. It will go into feature freeze on 2020-05-15 12:00:00 UTC and be released as 3.14 on 2020-06-19 12:00:00 UTC. 
Details on changes can be found on github at https://github.com/qgis/QGIS/commits/master. 

**Additional context**

**Comment by gioman** [comment]
@adamsss92 since this was filed there have been a lot of development and fixes in QGIS 3d, can you check if this is still valid? Thanks.
