### ISSUE TITLE
Build failure: invalid application of 'sizeof' to an incomplete type 'QgsDevToolWidgetFactory'

### ISSUE THREAD

**Issue by Chaz6** [qgis/QGIS#35851]
When compiling QGIS on CentOS 7 using Clang 10 with devtoolset7 and Qt 5.14.2 (installed from qt.io), the build fails with the following output:-

```
In file included from ../src/app/qgisappinterface.cpp:21:
In file included from /home/chaz/.local/local/qt5/include/QtWidgets/QMenu:1:
In file included from /home/chaz/.local/local/qt5/include/QtWidgets/qmenu.h:44:
In file included from /home/chaz/.local/local/qt5/include/QtWidgets/qwidget.h:48:
In file included from /home/chaz/.local/local/qt5/include/QtGui/qpalette.h:46:
In file included from /home/chaz/.local/local/qt5/include/QtGui/qbrush.h:52:
In file included from /home/chaz/.local/local/qt5/include/QtGui/qpixmap.h:48:
In file included from /home/chaz/.local/local/qt5/include/QtCore/qsharedpointer.h:48:
In file included from /home/chaz/.local/local/qt5/include/QtCore/qsharedpointer_impl.h:70:
In file included from /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/memory:80:
/opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/bits/unique_ptr.h:76:16: error: invalid application of 'sizeof' to an incomplete type 'QgsDevToolWidgetFactory'
        static_assert(sizeof(_Tp)>0,
                      ^~~~~~~~~~~
```

**Comment by gioman** [comment]
@Chaz6 you should ask for support in the developers mailing list rather than filing a bug ticket here.

**Comment by Chaz6** [comment]
@gioman the build was working until recently, so I believe that a bug has been introduced.

**Comment by gioman** [comment]
> @gioman the build was working until recently, so I believe that a bug has been introduced.

@Chaz6 still this should be asked (to be sure is a bug) in the dev mailing list, not here.

**Comment by Chaz6** [comment]
Maybe you should update README.md because it says "Please submit bug reports using the QGIS bug tracker."; it does not say anything about a mailing list (which I have no desire to subscribe to - if it was available as an nntp group I would be more inclined).

**Comment by Chaz6** [comment]
Closing this issue until it is confirmed as a bug.
