### ISSUE TITLE
Layer property panel can't be resized when focus is on labels/info-bubbles tab

### ISSUE THREAD

**Issue by ponceta** [qgis/QGIS#35868]
**Describe the bug**

![qgis_layer_properties_resize_bug](https://user-images.githubusercontent.com/8614223/79748050-04689e00-830d-11ea-87f2-df00e73c206a.gif)

**How to Reproduce**

1. Right Click on a layer -> `Properties`
2. Labels or info-bubbles
3. **Left panel goes reduced**
4. **Resizing is impossible**
5. click on another section (General / Symbology / ...)
6. Resizing is possible

**QGIS and OS versions**

QGIS 3.10.4 / 3.12.1 Win 10 x 64

**Additional context**

None

**Comment by haubourg** [comment]
@ponceta can you reword the issue title by "Layer property panel can't be resized when focus is on labels/info-bubbles tab" ? 
thx!

**Comment by ponceta** [comment]
Still a bug on 3.16.X, but seems to be fixed on QGIS 3.18.X, no need for backport on my side. (small GUI bug)
