### ISSUE TITLE
Create New Layer - Access Denied

### ISSUE THREAD

**Issue by isreilly** [qgis/QGIS#35865]
I've been creating "new Shapefile Layers" without issues until today. Even today I have g=created several but this afternoon it's now giving me a warning saying "Access Denied".

Please, any ideas why?

**Comment by gioman** [comment]
@isreilly Please ask questions on the users or developers mailing lists. Anyway your problem is probably that you are not setting the path were the shapefile has to be created, so QGIS defaults to a folder where you don't have write permissions.
