### ISSUE TITLE
Exporting WFS connections list will not include WFS version

### ISSUE THREAD

**Issue by olebrask** [qgis/QGIS#35866]
The seting of WFS version in not exported when you export to xml-file

**Comment by gioman** [comment]
@olebrask this ticket misses most of the necessary informations.

Are you speaking of QGIS Server of the QGIS Desktop WFS client?

What are the steps necessary to replicate? what are the expected results VS the obtained ones?

**Comment by alexbruy** [comment]
@gioman I think he is talking about exporting WFS connections into XML exchange file to be shared with someone else.

**Comment by gioman** [comment]
@alexbruy oh I see.

**Comment by alexbruy** [comment]
Actually much more information is missed including paging settings, axis orientation etc.
