### ISSUE TITLE
QGIS Server GetPrint: EXTERNAL_WMS layer on top of QGIS layer

### ISSUE THREAD

**Issue by uprel** [qgis/QGIS#35873]
**Describe the bug**
In QGIS 3.4 when using EXTERNAL_WMS parameter to print base layer it was below QGIS project layer. In QGIS 3.10 and master EXTERNAL_WMS is above QGIS layer meaning if base layer is solid, like orthophoto... user does not see QGIS content in GetPrint request

**How to Reproduce**
Project to reproduce issue is available here: [project3.zip](https://github.com/qgis/QGIS/files/4504806/project3.zip).
Should be copied in
/tests/tesdata/qgis_server_project/project3.qgs

Run this [request ](http://localhost:8000/?map=%2Fhome%2Furos%2Fdev%2Fcpp%2FQGIS%2Ftests%2Ftestdata%2Fqgis_server_project%2Fproject3.qgs&SERVICE=WMS&VERSION=1.3&REQUEST=GetPrint&FORMAT=png&EXCEPTIONS=application%2Fvnd.ogc.se_inimage&TRANSPARENT=true&SRS=EPSG%3A3857&DPI=150&TEMPLATE=a4%20test&map0%3Aextent=-11624780.5%2C3430129.8%2C-9074719.1%2C4700160.3&map0%3Ascale=10000000&map0%3Arotation=0&LAYERS=EXTERNAL_WMS%3AOpenLayers_Layer_WMS_20%2Cpolys_with_id_b2dbe530_e0ab_46d2_b070_b1220011f016&STYLES=&description=&title=&OpenLayers_Layer_WMS_20%3Aurl=http%3A%2F%2Fwww.gebco.net%2Fdata_and_products%2Fgebco_web_services%2Fweb_map_service%2Fmapserv%3F&OpenLayers_Layer_WMS_20%3Aformat=image%2Fpng&OpenLayers_Layer_WMS_20%3Acrs=EPSG%3A3857&OpenLayers_Layer_WMS_20%3Alayers=GEBCO_LATEST_2&OpenLayers_Layer_WMS_20%3Astyles
) with server (adjust how you acces server and path in map parameter)

You get WMS layer above QGIS data
![VirtualBox_LinuxMint 19 Xfce_20_04_2020_16_24_08](https://user-images.githubusercontent.com/7328417/79762836-88c61b80-8323-11ea-9fa8-6be6b6c741ba.png)

But should be QGIS data over WMS
![VirtualBox_LinuxMint 19 Xfce_20_04_2020_16_21_41](https://user-images.githubusercontent.com/7328417/79762951-b4490600-8323-11ea-9abe-7f7f41620905.png)

**QGIS and OS versions**
Problem is in QGIS master 3.13 and in QGIS 3.10, working fine in QGIS 3.4

**Additional context**
GetMap should also be tested for this same issue

**Comment by uprel** [comment]
Here is the [test request](http://localhost:8000/?map=/home/uros/dev/cpp/QGIS/tests/testdata/qgis_server_project/project3.qgs&LAYERS=EXTERNAL_WMS%3AOpenLayers_Layer_WMS_20%2Cpolys_with_id_b2dbe530_e0ab_46d2_b070_b1220011f016&FORMAT=image%2Fpng&TRANSPARENT=TRUE&DPI=96&VERSION=1.3.0&EXCEPTIONS=XML&SERVICE=WMS&REQUEST=GetMap&STYLES=&CRS=EPSG%3A3857&BBOX=-12800626.67562,3248186.0973439,-7698302.164238,5116918.5645997&WIDTH=1043&HEIGHT=382&OpenLayers_Layer_WMS_20%3Aurl=http%3A%2F%2Fwww.gebco.net%2Fdata_and_products%2Fgebco_web_services%2Fweb_map_service%2Fmapserv%3F&OpenLayers_Layer_WMS_20%3Aformat=image%2Fpng&OpenLayers_Layer_WMS_20%3Acrs=EPSG%3A3857&OpenLayers_Layer_WMS_20%3Alayers=GEBCO_LATEST_2&OpenLayers_Layer_WMS_20%3Astyles=) also for GetMap

Also important to note is that with 3.4 you can control position of external wms to be below (first in layers) or top (last of layers). Problem with master is that regarding of the order external WMS is always on top.

**Comment by elpaso** [comment]
All I can get from your attached project is 
```
<ServiceExceptionReport version="1.3.0">
<ServiceException code="LayerNotDefined">
The layer 'polys_with_id_b2dbe530_e0ab_46d2_b070_b1220011f016' does not exist.
</ServiceException>
</ServiceExceptionReport>
```

maybe you forgot to attach the data?

**Comment by uprel** [comment]
No it's only project, because first I wanted to commit it, but then we remove that PR. Project has relative path to this layer already in testdata: 
`.../QGIS/tests/testdata/polys_with_id.shp`

**Comment by elpaso** [comment]
project without data won't work. You should add the data inside the zip.

**Comment by uprel** [comment]
OK, new project now with only that referenced layer
[ext_wms_issue.zip](https://github.com/qgis/QGIS/files/4521159/ext_wms_issue.zip)
