### ISSUE TITLE
QGIS Browser - gpkg "refresh" 

### ISSUE THREAD

**Issue by wburt** [qgis/QGIS#35879]
**Feature description.**
Functionality for right click on a Geopackage in QGIS browser is:
- Remove Connection
- Create a New Layer or Table
- Delete
- Compact

When additional layers are added to the prepackage via QGIS processing tools or saving data from the layer panel the need to refresh the Geopackage contents may arise. This isn't currently obvious but can be achieved via removing your gpkg connection and adding it again.  I propose a **Refresh** option be added to the gpkg provider (perhaps consider other similar providers fgdb,spatialite, etc).

**Comment by stev-0** [comment]
I have been bitten by this before, good idea

**Comment by elpaso** [comment]
What are the UX "visible" issues involved here? 
Are you thinking at the layers shown in the browser tree? 
Any other part of the GUI involved?

I'm asking because at least for the browser we do already have refresh functionality implemented, perhaps it's just not triggered in your workflow.

In any event one or more step-by-step procedures to reproduce the issues would be very useful.

**Comment by wburt** [comment]
Slightly annoying that when you remove your geopackage connection and add it again my database connection refreshes its contents catalogue.

**Comment by BenGunnewijk** [comment]
I would also like to see a refresh option. 

In my case I have QGIS and another application open, the other application adds a layer to or removes a layer from the geopackage and the QGIS browser panel does not show the change nor does it allow me to manually refresh the package or individual layers.

Indeed the browser does refresh the geopackage when either adding or removing the geopackage database connection.

**Comment by maphew** [comment]
Yes please. Removing and re-adding a database connection in order see the new gpkg contents is error prone at worst and tedious at best when there are a number folders to navigate.
