### ISSUE TITLE
Build on macOS fails with Postgres test

### ISSUE THREAD

**Issue by timlinux** [qgis/QGIS#35883]
Building on macOS using @PeterPetrik 's dependency bundle I get:

```
[ 52%] Built target qgis_geometryimporttest_autogen
[ 53%] Built target qgis_wmsprovidertest
tests/src/providers/CMakeFiles/qgis_postgresconntest.dir/build.make:128: *** target pattern contains no `%'.  Stop.
make[1]: *** [tests/src/providers/CMakeFiles/qgis_postgresconntest.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 53%] Automatic MOC for target qgis_mdalprovidertest
[ 53%] Built target qgis_mdalprovidertest_autogen
make: *** [all] Error 2
```

and with tests disabled:

```
[ 43%] Automatic MOC for target postgresrasterprovider
[ 43%] Built target postgresrasterprovider_autogen
src/providers/postgres/CMakeFiles/postgresrasterprovider.dir/build.make:177: *** target pattern contains no `%'.  Stop.
make[1]: *** [src/providers/postgres/CMakeFiles/postgresrasterprovider.dir/all] Error 2
make: *** [all] Error 2
```

Looking at https://qgis.org/downloads/macos/nightly/?C=M;O=D it seems like the nightly builds are failing too (unsure if the two are related).

Verified against ea9613e096a98e7cb60454453fe4bd413caad4c2

**Comment by timlinux** [comment]
This turned out to be my build environment.

**Comment by franciscojavierrojas** [comment]
> This turned out to be my build environment.

How do you fix it at your  build environment? , it also happens to me. Trying to compile on MacOS 11 BigSur
![image](https://user-images.githubusercontent.com/42790815/101559870-ac5bd600-3987-11eb-8534-233d193d7285.png)
