### ISSUE TITLE
Potential memory leak?

### ISSUE THREAD

**Issue by PeterDrexel** [qgis/QGIS#35894]
Hi,
I use a Python-Script to load all shapefiles in a directory tree one by one and export the sld-files.
It works fine, but slows down incredible after ~100 files.
So I tried the following barebone script with just the essentials  (load shapefile, add it to the map canvas, remove it again and then clear the project) in a loop and I get the same behavior…
 
**from datetime import datetime
for i in range(1, 1000):
                vlayer=QgsVectorLayer ("aShapeFile.shp" ,"run  " + str(i) + " at " + datetime.now().strftime('%H:%M:%S') ,"ogr")
                QgsProject.instance().addMapLayer(vlayer)
                QgsProject.instance().removeMapLayer(vlayer.id())
                QgsProject.instance().clear()**
 
Same result,  the Script slows down after every iteration in the loop AND QGIS-memory consumption goes up!
Do I need to do some garbage cleaning / what am I doing wrong / is this a Memory leak?

Thanks
Peter

Tests done with **clean Profile on Windows 10 64 bit**

QGIS-Version | 3.12.1-București | QGIS-Codeversion | 121cc00ff0
-- | -- | -- | --
Kompiliert   gegen Qt | 5.11.2 | Laufendes   Qt | 5.11.2
Kompiliert   mit GDAL/OGR | 3.0.4 | Läuft   mit GDAL/OGR | 3.0.4
Kompiliert   mit GEOS | 3.8.1-CAPI-1.13.3 | Läuft   mit GEOS | 3.8.1-CAPI-1.13.3
Kompiliert   mit SQLite | 3.29.0 | Läuft   mit SQLite | 3.29.0
PostgreSQL-Client-Version | 11.5 | SpatiaLite-Version | 4.3.0
QWT-Version | 6.1.3 | QScintilla2-Version | 2.10.8
Kompiliert   mit PROJ | 6.3.1 | Läuft   mit PROJ | Rel.   6.3.1, February 10th, 2020
BS-Version | Windows   10 (10.0)
Aktive   Python-Erweiterungen | db_manager;   MetaSearch;   processing

**Comment by elpaso** [comment]
I think @m-kuhn already answered to this: there are some signal-slot connections that keep various QGIS parts in sync (the legend, snapping configuration etc.) and cleanup happens when signals are processed in the main application loop.

I don't think we have an issue here, please reopen if you find an issue after proper signal processing.
