### ISSUE TITLE
Make labeling with relation_aggregate() less inefficient

### ISSUE THREAD

**Issue by uclaros** [qgis/QGIS#35896]
**Feature description.**
Right now, if a label is set to display values pulled with `relation_aggregate()` function, then a separate request is made to the referencing layer for each feature to be labeled. This may pass unnoticed on local connections, but for remote/slow connections the result can be very slow depending on the number of features to be labeled.
I am not sure how this can be achieved, but a single request to the referencing layer should be made.

**Comment by troopa81** [comment]
I close this one as a duplicate of https://github.com/qgis/QGIS/issues/51487
