### ISSUE TITLE
Ubuntu Disco (base of Docker image) reached end-of-life

### ISSUE THREAD

**Issue by strk** [qgis/QGIS#35895]
According to https://wiki.ubuntu.com/Releases the Ubuntu Disco (19.04) release reached end-of-life.
Out in the wild we cannot build the QGIS Docker image anymore due to:
> E: The repository 'http://security.ubuntu.com/ubuntu disco-security Release' no longer has a Release file.

See https://github.com/linz/gazetteer/issues/92

Would it make sense to base the QGIS image on an LTS Ubuntu release instead ?

\cc @3nids

**Comment by 3nids** [comment]
focal is out in a few days, we can give it a try.

**Comment by 3nids** [comment]
let's see what it gives

**Comment by 3nids** [comment]
now using Focal: https://hub.docker.com/layers/qgis/qgis/latest_focal/images/sha256-6966a6ad5a22dcfb147c04bdb22e458c7720d3e960f95547e5e8ae4cb7c63d2d?context=explore

The Disco builds are dropped then
