### ISSUE TITLE
Geometry Generator fails when creating feature. Then works after editing feature attributes. 

### ISSUE THREAD

**Issue by Oisin-JK** [qgis/QGIS#35908]
I'm using QGIS 3.12.1 on Win10 x64.
I have also tried QGIS 3.10.5 on Win10 x64

**Overview**
I have a point layer representing tree positions. I have a calculated field ("rpaR") based on other attributes. I am using a data override to size the simple marker and a geometry generator to create a buffer (simple outline) around the marker. In the image below, the simple marker is arrowed red, and the simple outline from the geometry generator is arrowed blue.
![ptStyle](https://user-images.githubusercontent.com/57039094/79919502-7680d600-8426-11ea-997c-68bb7bb7323b.jpg)

When I create a point, the geometry generator styling is not displayed. If I then edit that point, changing any attribute, it works. 

**DETAIL** 
In the drag and drop form designer, the default value for "rpaR" is as follows:

`( if("dbh1" is null,0,("dbh1" / 1000)^2 * "stems1") + if("dbh2" is null,0,("dbh2" / 1000)^2 * "stems2") + if("dbh3" is null,0,("dbh3" / 1000)^2 * "stems3") + if("dbh4" is null,0,("dbh4" / 1000)^2 * "stems4") + if("dbh5" is null,0,("dbh5" / 1000)^2 * "stems5") )^0.5`

As image below.
![layerproperties_form_rpaR_defaultvalue](https://user-images.githubusercontent.com/57039094/79919577-8f898700-8426-11ea-8096-f9b2629f4cb7.jpg)

I note the text tip below the default value field sometimes reads "column 'dbh1' not found". But I think this is symptomatic of the same issue because when you inspect the "rpaR" field, the expected value is there. 

The simple marker field is as below, with the size set to the value of "rpaR" using the data override 
![layerproperties_symbolselector_simplemarker](https://user-images.githubusercontent.com/57039094/79919902-26eeda00-8427-11ea-891d-8ed10880eb41.jpg)

The geometry generator is as below:
![layerproperties_symbolselector_geometrygenerator](https://user-images.githubusercontent.com/57039094/79919937-30784200-8427-11ea-8924-3176f3eda977.jpg)

**To Reproduce**
I attach an example project with the bug.
[example-bug.zip](https://github.com/qgis/QGIS/files/4512913/example-bug.zip)

1.  Add point feature to layer "atl_qf_tree_pt"
2.  Enter data. Only need to fill in the following fields: "DBH1" (in DIMS tab, and "amenity" on ASSESS tab).
3. After creating a feature, the simplemarker is missing (should be at red arrow in image below). and The geometry generator is also missing. The label is visible.
![ptFeature_missing symbology](https://user-images.githubusercontent.com/57039094/79920655-7eda1080-8428-11ea-8668-62e042646445.jpg)

4. After editing any attribute of the feature missing symbology (simplemarker and geometry generator)are displayed correctly.
![ptFeature_with symbology](https://user-images.githubusercontent.com/57039094/79920931-1e979e80-8429-11ea-8caa-ae7209e14605.jpg)

**Comment by m-kuhn** [comment]
For reference https://gis.stackexchange.com/questions/359066/geometry-generator-possible-bug

**Comment by m-kuhn** [comment]
Can you try to make a minimum example that demonstrates the issue, removing as much of the complexity to reproduce as possible?

**Comment by Oisin-JK** [comment]
Hi Matthias. I thought I had done this. I attached a zip file of a simplified project, 1 layer, with the relevant styling, and steps on how to reproduce. What am I not doing that I should?

**Comment by m-kuhn** [comment]
Hi @Oisin-JK try to limit the problem to the most simple configuration possible. What happens if you skip the default value which is involved? Are you able to simplify the geometry generator code? Can you reproduce it with a layer with only the required attributes?

Try to lower the entry barrier for anyone who is willing to investigate this as much as possible.

**Comment by Oisin-JK** [comment]
My apologies, I should have updated this issue. This is no longer an issue for me. I initially found a work around by: (1) creating a virtual field (vRPA) instead of setting a default value for a a non-virtual field and (2) using a virtual layer for the geometry generator.
