### ISSUE TITLE
Unexpected behaviour of "Merge Selected Feature" in case of error in "Merge Feature Attribute"

### ISSUE THREAD

**Issue by pizzuga** [qgis/QGIS#35905]
Working with two consecutive linestrings (linestrings sharing one point) if the "Merge Feature Attribute" raise an exception for example due to a violation of a postgres trigger in one of the attribute fields of the new merged linestring, the two selected lines are deleted definitively even if one stop editing without saving. This is according to me a bug, because stop editing without saving should come back to the original situation while here the two lines are deleted and not recoverable.

this is the WARNING of QGIS following the attached example

```
Could not commit changes to layer foo

Errors: SUCCESS: 2 feature(s) deleted.
  ERROR: 1 feature(s) not added.
  
  Provider errors:
      PostGIS error while adding features: ERRORE:  a=10 < b=15
    CONTEXT:  funzione PL/pgSQL delete_foo() riga 1 a RAISE


```    
For what I can understand deleting the old linestrings and creating the new linestring are two processes completely separated, while the commit should come only after the second step. 

QGIS versions 3.4.14-Madeira and 2.18 (portable)

[Merge_Selected_Feature.txt](https://github.com/qgis/QGIS/files/4511593/Merge_Selected_Feature.txt)

Attached a very simplified example of a postgres table with two consecutive linestring and a trigger; it is enough to put a value of "a" lower then "b" in the "Merge Feature Attribute" and after the error close editing without saving.

**Comment by gioman** [comment]
> QGIS versions 3.4.14-Madeira and 2.18 (portable)

@pizzuga both too old and unsupported. You must test with the latest 3.10, 3.12 or master.

**Comment by pizzuga** [comment]
Tested in 3.10.5 the problem is solved, now the WARNING is

`2020-04-22T11:38:25     WARNING    Invalid result : Could not store value 'Skipped' in field of type int4.
`
the two lines are merged and the "wrong" value is substituted by the default value suggested  in the "Merge Feature Attribute"
Thank you
