### ISSUE TITLE
Peculiar table behavior when actions are displayed in table

### ISSUE THREAD

**Issue by bkepl** [qgis/QGIS#35904]
I have been experiencing this odd table behavior for several versions. I have created two custom actions to zoom or pan to a feature without having to first select a feature and click the icon at the top of the table or right-click the feature and choose the action from the context menu. I works well to rapidly move through a lot of features, until I sort on any field or edit a feature in any way. Here’s what happens:

1 – After adding Actions:
![1 – After adding Actions](https://user-images.githubusercontent.com/54165328/79889265-c2eaf800-83cb-11ea-8924-75cb9028a175.png)

2 – After sorting any column:
![2 – After sorting any column](https://user-images.githubusercontent.com/54165328/79889054-7bfd0280-83cb-11ea-9ef8-bfc5cafe102a.png)

3 – After editing any feature in any way:
![3 – After editing any feature in any way](https://user-images.githubusercontent.com/54165328/79887565-190a6c00-83c9-11ea-8cc1-be81b9586b73.png)

4 – This behavior occurs even when only the default actions show; this is after sorting any field:
![4 – This behavior occurs even when the default actions show](https://user-images.githubusercontent.com/54165328/79887611-29bae200-83c9-11ea-9eb4-c7ba4ac5429b.png)

**Comment by uclaros** [comment]
same as #33464?

**Comment by bkepl** [comment]
Well, broadly, yes, but I include additional information: the manner in
which icons change and the fact that editing a feature also causes the
problem.

I searched and didn’t find anything similar, but I didn’t search for the
right word! If you think I should, I can close my issue and re-enter it as
a comment to the one you reference.

Bruce

**Comment by gioman** [comment]
> Well, broadly, yes, but I include additional information: the manner in which icons change and the fact that editing a feature also causes the problem.

@bkepl right, but we must try avoid duplicates so please add your notes in https://github.com/qgis/QGIS/issues/33464 thanks!
