### ISSUE TITLE
Raster Label number precision

### ISSUE THREAD

**Issue by pmastrocola** [qgis/QGIS#35917]
Raster symbology (singleband pseudocolor mode) is missing a button to define the precision of numeric values to be shown in the labels, i.e. in the legend. This might solved manually editing the corresponding legend, but not automatically; still it is possible to save and re-load the colormap, but it is not as easy as having an option similar to the one existing when working with graduated symbology of the shape files editor.

**Comment by nyalldawson** [comment]
Duplicate of #22201
