### ISSUE TITLE
Crash modeler after loading model

### ISSUE THREAD

**Issue by zoot-wur** [qgis/QGIS#35919]
## User Feedback

Just after loading existing model. 

## Report Details

**Crash ID**: [c1a1074ec3d06fea23d8c01c628277f16e54a539]('https://github.com/qgis/QGIS/search?q=c1a1074ec3d06fea23d8c01c628277f16e54a539&type=Issues')

**Stack Trace**
<pre>
QgsProcessingToolboxProxyModel::filterAcceptsRow :
QSortFilterProxyModel::columnCount :
QSortFilterProxyModel::hasChildren :
QTreeViewPrivate::layout :
QTreeViewPrivate::layout :
QTreeViewPrivate::layout :
QTreeView::expandAll :
QgsProcessingToolboxTreeView::setFilterString :
QMetaObject::activate :
QLineEdit::qt_static_metacall :
QMetaObject::activate :
QWidgetLineControl::finishChange :
QWidgetLineControl::processKeyEvent :
QLineEdit::keyPressEvent :
QgsPresetSchemeColorRamp::clone :
QWidget::event :
QLineEdit::event :
QgsPresetSchemeColorRamp::clone :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processKeyEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.12.0-Bucure?ti
QGIS code revision: cd141490ec
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by gioman** [comment]
@zoot-wur please attach the model.

**Comment by zoot-wur** [comment]
will the next question be to provide my data as well?

**Comment by gioman** [comment]
> will the next question be to provide my data as well?

@zoot-wur if necessary we also ask for sample data so, yes, possibly.

**Comment by zoot-wur** [comment]
I didn't run it. I did earlier today.

[GAOS_routing_v10.bucharesti.model3.zip](https://github.com/qgis/QGIS/files/4516104/GAOS_routing_v10.bucharesti.model3.zip)

It might be a memory leak. I could try to restart windows and load the model again.

**Comment by roya0045** [comment]
I suspect a badly configured model.

**Comment by Gustry** [comment]
> QGIS Version: 3.12.0-Bucure?ti

Side note, you should always update whenever you can, especially when running a .0 version. It was the first release of the 3.12 series, a lots of bugs have been fixed in the meantime.

**Comment by gioman** [comment]
> Just after loading existing model.

@zoot-wur does not crash here on the latest 3.12.

**Comment by zoot-wur** [comment]
It worked before today so I am not surprised it loads without crash. 

I will first try after a Windows restart (later today or tomorrow) and if this fails try again after an update of QGIS.

**Comment by zoot-wur** [comment]
I updated to the latest. Is a good idea anyway. Model did work again after Windows restart and prior to update. I wonder, when is a model badly configured?
