### ISSUE TITLE
Concatenating strings with NULL restults in NULL

### ISSUE THREAD

**Issue by ghtmtt** [qgis/QGIS#35913]
Not sure if this is a bug or the expected behavior. Concatenating 2 strings when one of them is NULL results is NULL. The `C` field has been created as a concatenation of `A` and `B`:

![immagine](https://user-images.githubusercontent.com/2884884/79946263-e5cee800-846f-11ea-9724-d2f9510089b8.png)

the second row: `aaa || NULL = NULL`. I can use a `CASE WHEN...` or an `if` to check, but I'm unsure this is the expected behavior.

Tested on Debian with QGIS 3.12 from package and QGIS master compiled. In attach a sample. 

[null.zip](https://github.com/qgis/QGIS/files/4514082/null.zip)

**Comment by nyalldawson** [comment]
It's by design, matching postgres/sql behavior. Use "concat" if you want to avoid NULL handling and treat null as empty strings.

**Comment by ghtmtt** [comment]
got it, thanks for the explanation.
