### ISSUE TITLE
"print as raster" crashes QGIS [Qt < 5.13]

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#35929]
Latest QGIS 3.10 on Windows.

Steps followed:

- added postgis vector layer
- created layout
- set page size to custom, 1485x800, landscape
- resolution, 600 dpi
- "print as raster" enabled
- export to pdf > almost instant crash

if the page size it is set to a large standard size, like A0 it does not crash immediately but it seems to hang forever and it eats up a lot of memory (more than 2GB). Maybe in the case of the custom size page the memory eaten is so large that causes a almost instant crash. This seems to be the case because it the resolution is set to 300 dpi does not crash.

Nothing of the above happens if "print as raster" in not selected, also at 600dpi.

**Comment by nyalldawson** [comment]
This is likely a qt bug which was fixed in qt 5.13

**Comment by gioman** [comment]
> This is likely a qt bug which was fixed in qt 5.13

ok so let's recheck this when QGIS will ship with that QT version.

**Comment by nirvn** [comment]
For the record: on Qt 5.12.5, the crash is gone, however QGIS outputs a blank PDF.

**Comment by nirvn** [comment]
In addition, outputting as a PNG image also fails, ending up with a fully transparent image.

**Comment by roya0045** [comment]
Since we are using 5.15, is this still occuring?

**Comment by gioman** [comment]
> Since we are using 5.15, is this still occuring?

@roya0045 Windows installers use 5.11, so I cannot test if the crash is gone (on Ubuntu from repos I believe is even older).

**Comment by roya0045** [comment]
@gioman ah I thought that with the PRs referencing 5.15 that the builds would now all be using qt 5.15...

**Comment by getspatial** [comment]
I see that the issue I posted was a duplicate of this one.  Is there any update on this problem?  I have a map that I need to be able to export to a pdf, and as it has layers with transparency, I have to export as a raster.  Do you have any workarounds?  Would using the dev version make a difference?

**Comment by gioman** [comment]
> Is there any update on this problem?

@getspatial https://github.com/qgis/QGIS/issues/35929#issuecomment-618009407 it is an upstream issue. We must wait for QGIS to be built on a more recent release of QT.

**Comment by getspatial** [comment]
> @getspatial [#35929 (comment)](https://github.com/qgis/QGIS/issues/35929#issuecomment-618009407) it is an upstream issue. We must wait for QGIS to be built on a more recent release of QT.

@gioman Thanks for letting me know.  Given this, are there any workarounds?

**Comment by roya0045** [comment]
Compile qgis with a recent QT version.

**Comment by goened** [comment]
Can I just download a recent QT version (i.e. 5.13) by myself to use it in QGIS? For example here: https://www.qt.io/qt5-13 
How do I integrate it to QGIS then? Or do I have to install the recent QGIS version?

**Comment by gioman** [comment]
> Or do I have to install the recent QGIS version?

@goened try http://download.osgeo.org/osgeo4w/testing/osgeo4w-setup.exe

**Comment by roya0045** [comment]
@goened you must compile qgis with those qt components.

**Comment by goened** [comment]
You mean I can continue to work with 3.10.7 or 3.16.4 and only upgrade the QT components?

**Comment by roya0045** [comment]
@goened if you compile the code for 3.16.4 yes, 3.10 won't be compatible with a recent qt. Look in build from source if you want to try to compile QGIS.

**Comment by gioman** [comment]
> * added postgis vector layer
> 
> * created layout
> 
> * set page size to custom, 1485x800, landscape
> 
> * resolution, 600 dpi
> 
> * "print as raster" enabled
> 
> * export to pdf > almost instant crash

works fine on a build with QT 5.15

**Comment by goened** [comment]
Hi Giovanni,
thanks for your quick help! But for a simple user there still remain some questions.
As I don´t want to work with the 3.18 release but with the LTR, can I simply copy the folder from „C:\OSGeo4W\apps\Qt5“ (which ist he QT 5.15.2) to the folder „C:\Program Files (x86)\QGIS 3.16\apps\qt5“? Is this compatible to other components?
Or can I tell my QGIS 3.16.4 where to find the recent QT-Version on „C:\OSGeo4W\apps\Qt5“?

This must be an issue for many QGIS users that work with windows, mustn ´t it?

Cheers
Neele Dietrich
_______________________________

Neele Dietrich
GERIES INGENIEURE GMBH
Kirchberg 12
D-37130 Gleichen-Reinhausen
Tel.: (05592) 92 76-37
Fax: (05592) 92 76-11
eMail: ***@***.******@***.***>

Internetseite und Soziale Medien:
***@***.******@***.******@***.***D71FD8.ECAB8660]<https://www.youtube.com/channel/UCA6CiOCjCRradka1-6VAlPA>

Geries Ingenieure GmbH, Kirchberg 12, 37130 Gleichen
Registriert beim Amtsgericht Göttingen HRB 2876, Geschäftsführer Dr. Hartmut Geries
_______________________________

Von: Giovanni Manghi ***@***.***>
Gesendet: Montag, 22. März 2021 12:51
An: qgis/QGIS ***@***.***>
Cc: Neele Dietrich ***@***.***>; Mention ***@***.***>
Betreff: Re: [qgis/QGIS] "print as raster" crashes QGIS [Qt < 5.13] (#35929)


Or do I have to install the recent QGIS version?

@goened<https://github.com/goened> try http://download.osgeo.org/osgeo4w/testing/osgeo4w-setup.exe

**Comment by gioman** [comment]
> can I simply copy the folder from „C:\OSGeo4W\apps\Qt5“ (which ist he QT 5.15.2) to the folder „C:\Program Files (x86)\QGIS 3.16\apps\qt5“? Is this compatible to other components? Or can I tell my QGIS 3.16.4 where to find the recent QT-Version on „C:\OSGeo4W\apps\Qt5“?

@goened no you can't. You need a copy of QGIS built/compiled against a recent QT release.



> This must be an issue for many QGIS users that work with windows, mustn ´t it?

it is, and it is "fixed" (as is not even a QGIS bug really). You just need to wait for QGIS releases that will ship with QT > 5.13 or compile yourself the code.
