### ISSUE TITLE
qgis is unexpectedly ended

### ISSUE THREAD

**Issue by Saleh889** [qgis/QGIS#35920]
İ am fed up having that kind of error everytime when i am trying to select elements in atribut table.Also when i want to reshape,cut or trace a polygon.Please help me how can i get rid of them.
my operating system is Windows 8, QGIS version is 3.12

**Comment by gioman** [comment]
@Saleh889 you miss to add most of the required details:

1) operatying system?

2) QGIS version?

3) add the **detailed* steps to follow to replicate the crash (also attach sample data if necessary)


Regardless you can try with a new QGIS profile, no 3rd party plugins, on the latest 3.10 or 3.12 releases.

**Comment by gioman** [comment]
Closing for lack of feedback.
