### ISSUE TITLE
Vector menu empty

### ISSUE THREAD

**Issue by RomainGovaere** [qgis/QGIS#35934]
Hi, 

when i install differents versions of QGIS > 3.x, the vector menu is always empty (only contains "topology check")
i tryed desinstallation, clean register, etc. but it is always the same
i also test "reinitialise user preferences" but doesnt resolve also.

QGIS version 3.10.5-A Coruña, revision code : 984615fe1e
My OS is Windows 10 64 bits

Thanks for your help

**Comment by Gustry** [comment]
You need to enable the "Processing" algorithm in the plugin manager.

**Comment by RomainGovaere** [comment]
Thanks a lot !
i think it could be enabled by default :)

**Comment by Gustry** [comment]
It's already enabled by default. But it was disabled on your computer for some reason

**Comment by RomainGovaere** [comment]
for more details, i often use QGIS in older version (1.8) and i try some extenssions, it's probably the source of this.
the installation was just done in 3.x and i has this problem of the empty menu (not for the 1.8 !)
So i desinstall and install it again, no change, 
so i desinstall and clean the registry and install again. same way

Thanks again
