### ISSUE TITLE
WMS-T options disappear after disabling

### ISSUE THREAD

**Issue by timlinux** [qgis/QGIS#35936]
If I disable WMS-T support, I cannot enable it again:

![wms-t-bug](https://user-images.githubusercontent.com/178003/80068690-f64a9580-8537-11ea-82f2-2011ddf11587.gif)

We should keep the widgets in the source UI and just gray them out when the checkbox is unchecked.

**Comment by Samweli** [comment]
@timlinux this has been fixed here https://github.com/qgis/QGIS/pull/35741
