### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by balatoni558** [qgis/QGIS#35943]
Link to isogeo is unfortunately broken. Thank you for help in advance! There seems to be no option to register? 

https://www.isogeo.com/en/QGIS-Plugin/22

**Comment by Gustry** [comment]
You should report this issue to the plugin author : https://github.com/isogeo/isogeo-plugin-qgis
QGIS can't do anything about it

**Comment by balatoni558** [comment]
> You should report this issue to the plugin author : https://github.com/isogeo/isogeo-plugin-qgis
> QGIS can't do anything about it

Well it is advertised in QGIS and on ISOGEO Website there is no option to Register anymore.

**Comment by Gustry** [comment]
Sorry I don't understand. I guess you found the link in ISOGEO plugin right ?
if yes https://github.com/isogeo/isogeo-plugin-qgis

Maybe you read to quick Isogeo != Osgeo ?
