### ISSUE TITLE
QgsVectorLayer::readStyle() returns false positive

### ISSUE THREAD

**Issue by Djedouas** [qgis/QGIS#35947]
There is no test of QDomNode validity in `QgsVectorLayer::readStyle()` and `QgsVectorLayer::readSymbology()`.

As a result, using the python API, I can't test the success of these methods.

Python script to illustrate, just copy/paste in QGIS python console and run:

```
from qgis.PyQt.QtXml import QDomDocument

layer = QgsVectorLayer('Point?crs=epsg:2154', 'res', 'memory')
assert layer.isValid()
monStyle = QDomDocument()
monStyle.setContent("qsdfqfds")  # invalid content here
assert monStyle.namedItem('qgis').isNull()  # we can see that the node is invalid

# returns false positives
assert layer.readStyle(monStyle.namedItem('qgis'), "Error reading style", QgsReadWriteContext()) 
assert layer.readSymbology(monStyle.namedItem('qgis'), "Error reading symbology", QgsReadWriteContext())
```

I can make a PR adding the `QDomNode::isNull()` check at the begining of the two methods, returning false if it is the case.

**Comment by elpaso** [comment]
I'm not sure: one can argue that it's responsibility of the client code to check for null nodes, I would say that `readStyle` should return false when an error happens while it actually does something, while in the case of a null node it does just nothing so no errors can happen.

But I have no strong opinion, feel free to make a PR if you think it worth.
