### ISSUE TITLE
Crash in Graduated Symbols renderer

### ISSUE THREAD

**Issue by FedericaPalmieri** [qgis/QGIS#35940]
When I use the option Graduated Symbols renderer on the reorganized vector, through process tools, the software crashes.

## Report Details

**Crash ID**: [784a55bb3a0dedb5f8d7e22c6dbb1d6ad84b3eee]('https://github.com/qgis/QGIS/search?q=784a55bb3a0dedb5f8d7e22c6dbb1d6ad84b3eee&type=Issues')

**Stack Trace**
<pre>
QgsGraduatedSymbolRendererWidget::QgsGraduatedSymbolRendererWidget qgsgraduatedsymbolrendererwidget.cpp:510
QgsGraduatedSymbolRendererWidget::create qgsgraduatedsymbolrendererwidget.cpp:411
QgsRendererPropertiesDialog::rendererChanged qgsrendererpropertiesdialog.cpp:251
QMetaObject::activate :
QWidgetLineControl::`default constructor closure' :
QComboBox::setCurrentIndex :
QWidgetLineControl::`default constructor closure' :
QMetaObject::activate :
QComboBoxPrivateContainer::eventFilter :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
QgisApp::showLayerProperties qgisapp.cpp:14341
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QMenu::exec :
QgsLayerTreeView::contextMenuEvent qgslayertreeview.cpp:152
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1607
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.4-A Coru�a
QGIS code revision: 10bc9f2ff2
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment]
@FedericaPalmieri please provide step by step procedure to replicate the issue, also attach sample data. Also try on a new QGIS profile, no 3rd party plugins installed.

**Comment by FedericaPalmieri** [comment]
This is the step by step procedure:
- I open Qgis
- I create a new project
- I add a vector 
- I add a delimited text layer
- I go to vector properties to join the two attribute tables
- I reorganized the fields in process tools > vector table > reorganization of fields
- I create a new variable in calculator fields
- I make the layer permanet 
- I open Simbology in vector properties 
- I click on Graduated Symbols.... CRASH

**Comment by FedericaPalmieri** [comment]
How can I change profile?

**Comment by gioman** [comment]
> This is the step by step procedure:

@FedericaPalmieri can you attach a minimal project+data?

**Comment by gioman** [comment]
> How can I change profile?

settings > user profiles > new profile

**Comment by gioman** [comment]
Closing for lack of feedback.
