### ISSUE TITLE
Some .jpg rasters aren't adding to GDAL georeferencer. 

### ISSUE THREAD

**Issue by GSavelev-VSEGEI** [qgis/QGIS#35957]
I'm georeferencing several scans of old maps, when adding some of them to georeferencer plugin nothing happens (pic.1), with the same (as it looks, apparently, not) taken with the same camera everything works fine (pic.2).

![image](https://user-images.githubusercontent.com/57714410/80129031-3133e400-859f-11ea-812c-0ce7d47088a8.png)
Pic.1. The message says, raster loaded, but it is not seen. (attached o17855_k004.jpg)

![image](https://user-images.githubusercontent.com/57714410/80129631-039b6a80-85a0-11ea-83b0-05c8ecb45181.png)
Pic.2. Almost the same raster, everything works. (attached o17855_k003.jpg)

[source data](https://github.com/qgis/QGIS/files/4524153/qgis_georef_issue.zip)

**QGIS and OS versions**

QGIS version 3.12.2-București
QGIS code revision 8a1fb33634
Compiled against Qt 5.11.2
Running against Qt 5.11.2
Compiled against GDAL/OGR 3.0.4
Running against GDAL/OGR 3.0.4
Compiled against GEOS 3.8.1-CAPI-1.13.3
Running against GEOS 3.8.1-CAPI-1.13.3
Compiled against SQLite 3.29.0
Running against SQLite 3.29.0
PostgreSQL Client Version 11.5
SpatiaLite Version 4.3.0
QWT Version 6.1.3
QScintilla2 Version 2.10.8
Compiled against PROJ 6.3.1
Running against PROJ Rel. 6.3.1, February 10th, 2020
OS Version Windows 10 (10.0)
Active python plugins
db_manager; 
MetaSearch; 
processing

**Comment by roya0045** [comment]
This might be a file format issue, try to use something more suited than jpg such as tiff.

**Comment by uclaros** [comment]
It's a GDAL memory thing.
You need to set the environment variable *GDAL_ALLOW_LARGE_LIBJPEG_MEM_ALLOC* before running QGIS. ie ```set GDAL_ALLOW_LARGE_LIBJPEG_MEM_ALLOC=YES```
See #34558

**Comment by GSavelev-VSEGEI** [comment]
@uclaros, thank you very much!

For future reference by unexperienced users (as me), the environment variable setting, in this case - GDAL_ALLOW_LARGE_LIBJPEG_MEM_ALLOC to YES can be done (Windows QGIS 3.12.2) in Settings > Options > System, Environment section

![image](https://user-images.githubusercontent.com/57714410/80222366-63048380-864f-11ea-8815-dc20d43e3144.png)

P.S. Is there a problem of adding this to the default settings? I'm going to try to post a Feauture request #35982
