### ISSUE TITLE
Windows F12 keyboard shortcut no longer works

### ISSUE THREAD

**Issue by Houska1** [qgis/QGIS#35962]
In 3.10.2 and previously, I mapped F12 as a keyboard shortcut for "Pan map". No problems.
In 3.12.1 and .2 (OSG4Win), it no longer works. (Don't know about 3.10.x, x>2)

- I can define the shortcut under `Settings / Keyboard shortcut` and QGIS appears to recognize that's the key I'm pressing to define it.
- It is correctly represented as `<act shortcut="F12" name="Pan Map"/>` if I save keyboard shortcuts
- But pressing F12 in the map canvas, etc. does nothing.

I can map "Pan map" to a different key, like F9, and it works fine.
I can press F12 and have it recognized in other applications, so it's not something with my system. 

For debugging purposes, I've also tried mapping "About" to F12. That does not work either. So it's something about that key trigger, not the action.

Not a major problem, but ...weird.

Compiled and running against Qt 5.11.2 (as installed by the OSG4W installer), if relevant.

**Comment by nyalldawson** [comment]
You've probably installed a plugin which uses this shortcut, causing a clash (eg the first aid plugin or network logger)

**Comment by Houska1** [comment]
Bingo--it was network logger. Thanks Nyall. I forgot I had "polluted" my otherwise clean testing profile with that plugin to trace something else.
