### ISSUE TITLE
Needless XML attribute shuffling makes versioning processing models with Git impractical

### ISSUE THREAD

**Issue by dericke** [qgis/QGIS#35964]
**Describe the bug**
When saving a model from the Processing Modeler, the order of all attributes within each XML element is shuffled in the model file. For example, 
```xml
<Option type="QString" value="native:centroids_1" name="child_id"/>
```
might become 
```xml
<Option value="native:centroids_1" name="child_id" type="QString"/>
```
The attribute order does not have any effect on appearance or function of the model within QGIS, but does fill Git diffs with noise and masks changes that do matter.

**How to Reproduce**
1. Create a test folder within the QGIS models folder and initialize a new Git repository there
2. In the Processing Toolbox, select **Create New Model...**
3. Add a Vector Layer input
4. Add a simple algorithm that can use the vector layer. I chose Centroids, but any algorithm should work. Give the output a name.
5. Save the model to the test folder
6. Stage the new .model3 file in the new repository and commit
7. Open the repository in a diff viewer that previews changes against the HEAD. I used Visual Studio Code's built-in source control tool
8. Close and reopen QGIS
9. Edit the new model
10. Move one of the model's elements slightly
11. Save the model

**Expected behavior**
In the diff viewer, only the lines containing the coordinates of the element that was moved should show a change. No other lines should show any changes

**Observed behavior**
Most lines containing 2 or more XML attributes show a change. None of the attribute keys or values have changed, just the order they appear within their XML element.

If you do not observe this same behavior, please repeat steps 8–11 at least 5 times. I wasn't able to reproduce the behavior every time, but I was able to randomly reproduce the problem at least once in every 5 cycles. I couldn't determine a cause for why it occurs some times and not others.

**Additional context**
When I ran the above steps, out of an 80-line .model3 file, 27 lines appeared changed when only 2 should have actually changed. This limits the usefulness of versioning my models, as it makes it harder to view changes of substance within the noise of superfluous changes in the XML file.

**QGIS and OS versions**

QGIS version | 3.10.5-A Coruña | QGIS code revision | 984615fe1e
-- | -- | -- | --
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.28.0 | Running against SQLite | 3.28.0
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS Mojave (10.14)
Active python plugins | processing

**Suggested fix**
Sort XML attribute keys alphabetically (or in some other sensible, consistent order) on save.

**Comment by dericke** [comment]
Did some more digging and learned that this is a pretty common problem with `QDomDocument`. Found plenty of results for "qdomdocument sort attributes" on StackOverflow.

**Comment by Gustry** [comment]
This is a known issue with Qt and XML. It's the same for a `qgs` project, for `qml` style.
I think we should close here and move the discussion to #29192. In the background, it's the same issue.
