### ISSUE TITLE
Canvas Action: Selection Dropdown created from Attributes

### ISSUE THREAD

**Issue by frantsch** [qgis/QGIS#35972]
**Feature description.**
Actions of typeCanvas show a dropdown to select one of the features by Feature ID, in case more than one feature are click-selected on the map during run feature action mode.
Instead of Feature ID, the content from one of the feature attributes should be defineable to be shown for this action dropdown selection.  

**Additional context**
Usually a user does not know anything about the Feature ID when he is required to select among several features from the map for an action.

**Comment by DelazJ** [comment]
@frantsch is this still valid? Are you sure it is by the "feature id" you have to select or by the "Display name" field as defined in the layer properties --> Display tab?
