### ISSUE TITLE
Another ArcGIS WMS raster layer type support

### ISSUE THREAD

**Issue by inouterer** [qgis/QGIS#35979]
**Feature description.**

Need XYZ-Tiles-like support for raster layers ArcGIS WMS type "https: // <mapservice-url> / export" (ArcGIS REST API).

**Additional context**

An example of a working request:
https://pkk.rosreestr.ru/arcgis/rest/services/PKK6/Cadastre/MapServer/export?dpi=96&format=PNG32&bbox=(8283322.79,8906432.27,8303632.95,8939167.78)&bboxSR=102100&imageSR=102100&size=1024%2C1024&transparent=true&f=image
Bounds of map canvas:  bbox={$bbox} https://pkk.rosreestr.ru/arcgis/rest/services/PKK6/ZONES/MapServer/export?dpi=96&transparent=true&format=PNG32&bbox={$bbox}&bboxSR=102100&imageSR=102100&size=1024%2C1024&f=imag

**Comment by nyalldawson** [comment]
This is already possible -- just add the server as a "ArcGisMapServer" type instead of WMS
