### ISSUE TITLE
Clipping raster using mask layer ignores the layer filter

### ISSUE THREAD

**Issue by NyakudyaA** [qgis/QGIS#35981]
# Problem

* Load a vector layer in QGIS
* Filter the vector layer
* Load a raster layer.
* Clip the raster layer using the vector layer.

![gdal-clip](https://user-images.githubusercontent.com/2510900/80214782-b53ba980-863b-11ea-9226-e1ee68dbfcfa.png)

The gdal command shown on the processing dialog is like below
```
gdalwarp -of GTiff -cutline /tmp/provinces.shp -cl provinces -crop_to_cutline -dstalpha -multi -co COMPRESS=DEFLATE -co PREDICTOR=2 -co ZLEVEL=9 /tmp/zaf_ppp_2020_3857.tif /tmp/OUTPUT.tif
```

This would clip the layer based on the extent of the province layer.

I would expect it to generate a request like the following

```
gdalwarp -of GTiff -cutline /tmp/provinces.shp -cl provinces -csql "select * from provinces where "PROVNAME" = 'Western Cape' " -crop_to_cutline -dstalpha -multi -co COMPRESS=DEFLATE -co PREDICTOR=2 -co ZLEVEL=9 /tmp/zaf_ppp_2020_3857.tif /tmp/OUTPUT.tif
```

![qgis-12](https://user-images.githubusercontent.com/2510900/80215329-8bcf4d80-863c-11ea-95cd-2e244557f681.png)

**Comment by gioman** [comment]
@NyakudyaA you must use the other way, using the "use selected features only" option or use the appropriate GDAL option in "additional command line parameters".

**Comment by NyakudyaA** [comment]
> @NyakudyaA you must use the other way, using the "use selected features only" option or use the appropriate GDAL option in "additional command line parameters".

@gioman you cannot use `selected features only` when you have filtered the layer. 

I know you have closed this but I think this is still valid because all other processing operations will work for a filtered layer.

* Add a vector layer in QGIS
* Filter the layer and then buffer. It will buffer only the filtered layer not the full extent

![buffer](https://user-images.githubusercontent.com/2510900/80228152-f38e9400-864e-11ea-8f59-6095ddacb006.png)

**Comment by gioman** [comment]
> I know you have closed this but I think this is still valid because all other processing operations will work for a filtered layer.

It probably works also for native QGIS tools. For other providers is probably not possible or must be implemented, which configure as feature request.

**Comment by gioman** [comment]
i.e. "clip with mask layer" is a GDAL tool, not QGIS's.

**Comment by NyakudyaA** [comment]
> i.e. "clip with mask layer" is a GDAL tool, not QGIS's.

Let me see if other gdal tools will natively use a filtered  layer then we can flag it as a Feature because when doing training it is easy to teach users to filter than to write exta gdal commands

**Comment by NyakudyaA** [comment]
@gioman If I use Clip vector by mask layer in processing under GDAL algorithms you can see that the ogr2ogr command correctly references the filter layer so this should also be valid for a raster layer.
![gdal-operation](https://user-images.githubusercontent.com/2510900/80231332-86313200-8653-11ea-88ff-2fa570e5b947.png)

**Comment by alexbruy** [comment]
@NyakudyaA to clip vector layer you MUST specify `clipsrc` and `clipscrlayer` these parameters are not related to the layer filter at all.

**Comment by NyakudyaA** [comment]
> @NyakudyaA to clip vector layer you MUST specify `clipsrc` and `clipscrlayer` these parameters are not related to the layer filter at all.
> 
> This is not a bug.

@alexbruy i know what you need. The issue here is that if you have a filtered layer the raster clip by mask is ignoring the filter and using the full features of the geometry hence rendering the filter invalid. If you feel the other work around to get this working are sufficient you can close the ticket but as specified in the title when you filter a layer and any operations should use only the visible geometry not the full geometry

**Comment by alexbruy** [comment]
@NyakudyaA I'm just pointing out that your previous message about clip by mask is wrong.

**Comment by gioman** [comment]
> @gioman you cannot use `selected features only` when you have filtered the layer.

@NyakudyaA ummm... I really think you can do a selection on a filtered layer.

**Comment by NyakudyaA** [comment]
> > @gioman you cannot use `selected features only` when you have filtered the layer.
> 
> @NyakudyaA ummm... I really think you can do a selection on a filtered layer.

I meant that the two should be exclusive in most cases . If you want to a selection then you should not be filtering at all
