### ISSUE TITLE
Export Map to Image Ignores Atlas-Related Features

### ISSUE THREAD

**Issue by spencerrecneps** [qgis/QGIS#35989]
**Describe the bug**

Layers whose visibility is affected by a Layout Atlas are not exported from the canvas with the `Export Map to Image` option from the `Project->Import/Export` menu.

**How to Reproduce**

[bug_example.zip](https://github.com/qgis/QGIS/files/4530393/bug_example.zip)

1. Open sample project (note: requires Memory Layer Saver plugin)
2. Open map layout
3. Activate Atlas
4. Return to canvas to notice the purple square has appeared
5. Select `Project->Import/Export->Export Map to Image`
6. Save image
7. Open image to notice that the purple square was not exported

Expected behavior: The `Export Map to Image` option should export all features that are visible on the map canvas in its current state.

**QGIS and OS versions**

QGIS version
3.10.3-A Coruña
QGIS code revision
0e1f846438
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.1
Running against PROJ
Rel. 6.3.1, February 10th, 2020
OS Version
Windows 10 (10.0)
Active python plugins
MapsPrinter; 
MemoryLayerSaver; 
PluginLoadTimes; 
qgis2web; 
quick_map_services; 
StreetView; 
timemanager; 
db_manager; 
processing

**Additional context**

**Comment by Pedro-Murteira** [comment]
@spencerrecneps I can't seem to replicate this issue anymore on QGIS 3.16.14 and 3.22.1., the square does not show on canvas after activating atlas. (even with the plugin installed)

**Comment by spencerrecneps** [comment]
I have not noticed this issue in recent versions and don't have the capacity to test the older version at the moment. It probably makes sense to close this as it appears to have been fixed in newer releases.
