### ISSUE TITLE
Print Layout Export: Resolution influences Scale and vice versa/ Export Preview Wrong

### ISSUE THREAD

**Issue by twatzl** [qgis/QGIS#36009]
Hello, 

for digital use I want to export a map in 4k Resolution. So I create a new print layout set the resolution and size to 4k, set the print resolution to 300 ppi, add the map, select the map extends, set the map scale and so on.

In the preview the map is exactly as I expect it to be rendered, however in the actual rendering the map scale is far more detailed than I would expect from the preview. This makes it very hard to do proper exports.

![image](https://user-images.githubusercontent.com/18753370/80317286-35603b80-8803-11ea-9465-a324dd2ad59a.png)

It seems the print resolution (dpi) influences the scale and vice versa. 
From my expectation as a user this should not be the case rather print resolution and scale should be independent and I would expect my export to contain exactly what I am looking at in the preview.

![Country Overview](https://user-images.githubusercontent.com/18753370/80317289-3beeb300-8803-11ea-967b-ca874e634f05.png)

**Comment by twatzl** [comment]
So some more information which might help to fix this: 
- I am using WMTS tile layers
- QGIS Version: 3.12.1-București on Windows

The following 2 images should also give a good idea what is wrong. One is exported with print resolution of 300 dpi the other one with 150. I would expect the labels to be the same size, but with more pixels in one of them.

![300 dpi file](https://user-images.githubusercontent.com/18753370/80406389-4cb32d80-88c4-11ea-8469-af17d0b6657e.png)
![150 dpi file](https://user-images.githubusercontent.com/18753370/80406398-5046b480-88c4-11ea-8049-c8feba1b1a7f.png)

**Comment by nyalldawson** [comment]
This is expected -- WMTS tiles are a raster format, created on the server for use at screen dpi only. By bumping up the dpi in the print layout QGIS is fetching tiles generated for a larger scale to compensate. It's an unfortunate consequence of using WMTS tiles.

The solution is to use a vector tile source.

**Comment by twatzl** [comment]
I see. How does rendering for the maps then work on HiDPI screens?

I will still conduct some tests as the behaviour of this export dialog is still somewhat misterious to me. As I have noticed there are multiple ways to change the resolution and some influence scale and some not 🤷‍♂️.

**Comment by nyalldawson** [comment]
> I see. How does rendering for the maps then work on HiDPI screens?

It's the same
