### ISSUE TITLE
[vector tiles] Support for multiple styles

### ISSUE THREAD

**Issue by saberraz** [qgis/QGIS#36018]
With raster and vector, user can assign multiple styles to a layer. It would be good to add support for multi-styling for vector vector tiles, so users can switch between the styles.

**Comment by wonder-sk** [comment]
This should also work now on master, can you test again @saberraz ?

**Comment by saberraz** [comment]
@wonder-sk it works for the QGIS session: I can create multiple styles and map themes. But it does not get saved with the project. When I save and close the project, all the styles disappear and the map themes are all set to one theme.
