### ISSUE TITLE
postgresql bigint column value doesn't show up in attribute table on master

### ISSUE THREAD

**Issue by tudorbarascu** [qgis/QGIS#36011]
**Describe the bug**

On Debian Bullseye, the PostgreSQL bigint columns values don't show up in the attribute table.

**How to Reproduce**
- Create this table in PostGIS
```
CREATE TABLE public.bad_points (
    id integer PRIMARY KEY,
    geom public.geometry(Point,3844),
    bigint_column bigint
);

INSERT INTO public.bad_points VALUES (22524, '0101000020040F00007C60A53E0D181841CD60462FDBEE2141', 9);
```
- add the table in QGIS and open the attribute table
- The attribute table doesn't show value ``9`` under the ``bigint_column`` column

QGIS version | 3.13.0-Master | QGIS code revision | 31453537f5
-- | -- | -- | --
Compiled against Qt | 5.12.5 | Running against Qt | 5.12.5
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.2 (Debian 12.2-4) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 7.0.0 | Running against PROJ | Rel. 7.0.0, March 1st, 2020
OS Version | Debian GNU/Linux bullseye/sid
Active python plugins | db_manager; MetaSearch; processing

**Additional context**
I can replicate on Master from packages and build from source.
I tested on the same system with QGIS 3.10.5 and 3.12.2 (from packages) and I cannot replicate.
I tested with Master from packages (sid) and I cannot replicate:
```
QGIS version | 3.13.0-Master | QGIS code revision | b73bd58cfb
-- | -- | -- | --
Compiled against Qt | 5.12.5 | Running against Qt | 5.12.5
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.2 (Debian 12.2-4) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 7.0.0 | Running against PROJ | Rel. 7.0.0, March 1st, 2020
OS Version | Debian GNU/Linux bullseye/sid | This copy of QGIS writes debugging output.
Active python plugins | db_manager; MetaSearch; processing
```
Will try to bisect tomorrow.

@uclaros As you have the same system (more or less) could you please test if you can also replicate (should take only a minute).

**Comment by uclaros** [comment]
Sure! Can replicate on 81911c1afc, cannot replicate on 29adf2eea0, if that's any help!

**Comment by tudorbarascu** [comment]
Thanks @uclaros I just bisected and found the introducing commit to be 0d0fe48c3ae7b4e73e101624f4321ed1e2b348e3 ping @espinafre

**Comment by espinafre** [comment]
@uclaros , @tudorbarascu , thanks for pinging me, I'm looking into it.

**Comment by espinafre** [comment]
Hi, @uclaros , @tudorbarascu , I've submitted a new PR (#36040) that will solve this issue; hopefully @m-kuhn will take a look at it. Thanks for reporting.

**Comment by tudorbarascu** [comment]
@espinafre Well.. the first issue is now gone but now for bigint fields that have NULL value I get ``0`` or others like ``2115154``.

@gioman This needs to be reopened.

If I create the following table, on master I see 0 instead of NULL.

```
CREATE TABLE public.bad_points (
    id integer NOT NULL,
    geom public.geometry(Point,3844),
    fk_strada bigint
);

INSERT INTO public.bad_points VALUES (17074, '0101000020040F00007D6A4D566D001841B7EE11A999F22141', NULL);

ALTER TABLE ONLY public.bad_points
    ADD CONSTRAINT bad_points_pkey PRIMARY KEY (id);
```

On a much bigger table, I also see values like ``2115154`` instead of NULL.
