### ISSUE TITLE
Loss of contour data when using 'Rasterize'

### ISSUE THREAD

**Issue by Rasbats** [qgis/QGIS#36048]
**Describe the bug**

A shapefile showing contour data was produced. This showed the legend for the contour lines and also the zero/datum line (zero). When rasterized the zero datum line was missing, also the legend for the contour lines.

**How to Reproduce**

Add the spatialite database to the project.

The connection to the data has been established.
'Right-Click' on the 'soundings' layer to save a Shapefile.

'Export'
'Save Features As...'

'Right-Click' again on the Shapefile. 'Zoom to Layer' shows you the
location of the soundings.
This demonstrates the density of soundings required if contouring is
going to be successful. The survey lines are about 10 metres apart.

Select 'Vector','Contour' from the menu at the top of the screen.

The input is the shapefile of soundings. 'depth' is the data value. If
you go through the list of options and set things up
correctly QGIS will work out min/max depth and you can choose a suitable
contour interval. I needed to play with the number of contours
but eventually a list appeared in the text box. It is possible to apply
colours but probably better to use a single colour.

The contours appear.

To make the contours display better 'Right-Click'. Black will show the
contours best.

We now add labels to the contours.

'Properties'

The shapefile is in vector format. It has to be converted to raster
before it can be exported as a geotiff.

**Raster output is shown. Some of the contours are faded but that will not
affect their display. Unfortunately contour labels disappear. Also the
datum line (0)**

![13](https://user-images.githubusercontent.com/2537240/80456878-3ccc3580-8926-11ea-912f-31f90fd136cd.png)
![19](https://user-images.githubusercontent.com/2537240/80456877-3ccc3580-8926-11ea-9be6-8927d1fba3e3.png)

**QGIS and OS versions**

![qgis](https://user-images.githubusercontent.com/2537240/80457575-718cbc80-8927-11ea-8b5e-66c89d777390.png)

**Additional context**
Shapefile before rasterizing is here ...
(Remove the .pdf)
[dandy.hole.shp.pdf](https://github.com/qgis/QGIS/files/4543946/dandy.hole.shp.pdf)

Brilliant program.

**Comment by gioman** [comment]
@Rasbats 

a few notes:

1) attach here your contour shapefile (all the files: shp, shx, dbf and prj) as a zip file. Only the shp won't work

2) I guess you are using "rasterize" from GDAL (there is also a tool from SAGA), so you should test if using the same tool from the command line (with the same input and parameters) give the same result. If yes then it is likely to be an issue in gdal_rasterize rather than QGIS.

**Comment by Rasbats** [comment]
@gioman 
Thanks for the comment. Files are here;
[OpenCPN.workflow.zip](https://github.com/qgis/QGIS/files/4544504/OpenCPN.workflow.zip)
First steps with this stuff. It was 'Rasterize' from the QGIS menus. I will look at GDAL and try that.

**Comment by gioman** [comment]
@Rasbats your shape as "unknown CRS". Should that be somewhere in Wales?

**Comment by gioman** [comment]
@Rasbats anyway the point is that "rasterize" uses 0 as nodata by default. As you have lines with 0 values you must choose a different nodata value, i.e. -9999. Do that and you'll get the expected result.

**Comment by Rasbats** [comment]
@gioman
Somewhere in Cornwall!!! The OpenCPN plugin uses EPSG:3395 for data collection. When rasterized I change the CRS to EPSG:4326 for export to GeoTiff. I will play with the nodata value.
Appeciate the help. Thanks.
