### ISSUE TITLE
Mbtiles cannot be found

### ISSUE THREAD

**Issue by saberraz** [qgis/QGIS#36049]
I am trying to open a project containing an MBtile layer. The path is correct but it complains the file does not exist.
QGIS 3.10.5

**Comment by saberraz** [comment]
Here is an example project:
[mbtiles_missing.zip](https://github.com/qgis/QGIS/files/4544188/mbtiles_missing.zip)

**Comment by gioman** [comment]
@saberraz isn't this a regression?

**Comment by saberraz** [comment]
I think it is...I did not have this issue before.

**Comment by wonder-sk** [comment]
Ah I see what is happening - the project was created in QGIS >= 3.12 and it is using new functionality from "wms" provider to display MBTiles raster files - older version of QGIS do not support that (only supporting MBTiles via "gdal" provider).

The workaround would be to re-add that layer in QGIS <= 3.10.x and save the project. But with that new versions of QGIS will loose the abilities provided by "wms" provider (better scaling of tiles on high dpi screens and smooth scaling).

We could also prepare a fix for QGIS 3.10 that would detect this unsupported functionality from newer versions of QGIS and auto-convert the layer to use "gdal" provider...

**Comment by nyalldawson** [comment]
@wonder-sk I don't think we need to do anything -- we have never encouraged opening projects from later QGIS versions in earlier versions, and we even have big warnings in the UI which advise users about this.

**Comment by nyalldawson** [comment]
Closing as a wontfix
