### ISSUE TITLE
Missing points (depending on canvas scale) in virtual layer based on sqlite file

### ISSUE THREAD

**Issue by alafr** [qgis/QGIS#36054]
**Describe the bug**
When creating a virtual layer based on a sqlite table, some points disappear from the canvas when zooming or panning.

In Qgis 3.13.0 only, I also get this error message in the top bar: Qt: "SELECT \"GEOM\" FROM _tview LIMIT 1"

**How to Reproduce**

[virtual_layer_bug.zip](https://github.com/qgis/QGIS/files/4544542/virtual_layer_bug.zip)

1. Open the attached project
2. Zoom / pan on a any point
3. The majority of the points disappear (become red) at about 1:10 scale

At wider scales, the points only disappear near the canvas margins, but at closer scales, they disappear even from the middle of the canvas.

At scale 1:50:
![missing points at 1_50](https://user-images.githubusercontent.com/17966696/80468424-73fb1080-893f-11ea-8d1e-b6e9cde7dbb2.PNG)
At scale 1:200:
![missing points at 1_200](https://user-images.githubusercontent.com/17966696/80468429-75c4d400-893f-11ea-99ca-9e4259c3d9cb.PNG)

**QGIS and OS versions**
Tested with the following Qgis versions:

Version de QGIS | 3.12.2-București | Révision du code | 8a1fb33634
-- | -- | -- | --
Compilé avec Qt | 5.11.2 | Utilisant Qt | 5.11.2
Compilé avec GDAL/OGR | 3.0.4 | Utilisé avec GDAL/OGR | 3.0.4
Compilé avec GEOS | 3.8.1-CAPI-1.13.3 | Utilisé avec GEOS | 3.8.1-CAPI-1.13.3
Compilé avec SQLite | 3.29.0 | Fonctionne avec SQLite | 3.29.0
Version du client PostgreSQL | 11.5 | Version de SpatiaLite | 4.3.0
Version de QWT | 6.1.3 | Version de QScintilla2 | 2.10.8
Compilé avec PROJ | 6.3.1 | Fonctionne avec PROJ | Rel. 6.3.1, February 10th, 2020
Version de l'OS | Windows 10 (10.0)
Extensions Python actives | db_manager; MetaSearch; processing

Version de QGIS | 3.13.0-Master | Révision du code | 050dfde009
-- | -- | -- | --
Compilé avec Qt | 5.11.2 | Utilisant Qt | 5.11.2
Compilé avec GDAL/OGR | 3.1.0dev | Utilisé avec GDAL/OGR | 3.1.0dev
Compilé avec GEOS | 3.8.1-CAPI-1.13.3 | Utilisé avec GEOS | 3.8.1-CAPI-1.13.3
Compilé avec SQLite | 3.29.0 | Fonctionne avec SQLite | 3.29.0
Version du client PostgreSQL | 11.5 | Version de SpatiaLite | 4.3.0
Version de QWT | 6.1.3 | Version de QScintilla2 | 2.10.8
Compilé avec PROJ | 7.1.0 | Fonctionne avec PROJ | Rel. 7.1.0, August 1st, 2020
Version de l'OS | Windows 10 (10.0) | Cette copie de QGIS dispose d'une sortie de débogage.
Extensions Python actives | db_manager; MetaSearch; processing

**Additional context**
There are 2 layers:
 - vrt_file PointAsSqlite, with red markers. This layer is based on a VRT file and has no bugs.
 - PointsGeometry, with green markers. This is a virtual layer, querying the Point table.

The VRT file and the Point table both point to the same sqlite table "Point" in the sqlite file "data.PD".

This means that when a red dot appears, a point from the PointsGeometry layer has disappeared.

**Comment by troopa81** [comment]
> In Qgis 3.13.0 only, I also get this error message in the top bar: Qt: "SELECT "GEOM" FROM _tview LIMIT 1"

This error message means nothing, its actually a debug message. #36772 will remove it

For the main issue, I know what's going on here and I'll propose a fix soon

**Comment by alafr** [comment]
I confirm it works nicely in:
3.13.0-Master | 81abbbb74f

@troopa81 Thank you very much for solving the issue!
