### ISSUE TITLE
"Split vector layer": output as shapfiles

### ISSUE THREAD

**Issue by josephjbailey** [qgis/QGIS#36058]
The 'Split vector layer'  is great, but it would be even better if it were possible to have SHP as an option for the output files, instead of just the compulsory GPKG. Workarounds have been suggested (e.g. [here](https://gis.stackexchange.com/questions/314479/qgis-split-vector-layer-gives-me-gpkg-files-but-i-need-shp-files)), but integrating more seamlessly this would be great. Thanks.

**Comment by gioman** [comment]
> but integrating more seamlessly this would be great

in the past the tool outputted to shp, nows it does as gpkg as the tendency is (and will be) to stop using shapes. I'm not sure this will be ever be implemented back.

**Comment by josephjbailey** [comment]
Hello. Thanks for the comment, that's interesting. I'll adapt :)

**Comment by alexbruy** [comment]
You can change default output format in the Processing settings but keep in mind that this will affect all algorithms.

Reverting current state back to producing shapefiles is a won't fix.
