### ISSUE TITLE
Misplaced form layout (drag-n-drop designer)

### ISSUE THREAD

**Issue by saberraz** [qgis/QGIS#36055]
There are a couple of issues:

- Hidden attributes header are still shown
- There is a huge blank space on top of the form

![image](https://user-images.githubusercontent.com/2649047/80470285-b1f53600-8939-11ea-8f5f-197898ec32bf.png)

**Comment by Pedro-Murteira** [comment]
@saberraz I've tested this issue on QGIS 3.22.3. and I can't to replicate it. Did you come across this issue more recently?
