### ISSUE TITLE
Possibility to use curved lines for splitting features/parts

### ISSUE THREAD

**Issue by saberraz** [qgis/QGIS#36053]
Currently, you can split features/parts using lines/multilines. It will be good to add support for splitting features using curved lines too.

**Comment by signedav** [comment]
I think this is possible meanwhile. Can you confirm?
![split](https://user-images.githubusercontent.com/28384354/164182730-d8046b3a-cfcb-4d01-b32f-67c9bbe0206e.gif)

**Comment by YoannQDQ** [comment]
I can confirm it is now possible.
