### ISSUE TITLE
Crash after deleted a raster

### ISSUE THREAD

**Issue by Heryx** [qgis/QGIS#36062]
**Describe the bug**
Qgis crashed after deleted a raster.

**How to Reproduce**

1. Georeferencing a raster 
2. I closed the window of the georeferencer
3. Deleted the raster file from the pannel layer

**QGIS and OS versions**

**QGIS Info**
QGIS Version: 3.4.10-Madeira
QGIS code revision: 3d97aaae88
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

**OS Info**
Windows 10

**Additional context**

## User Feedback

Crash after deleted a raster

## Report Details

*Crash ID*: b0748582d643a0e7f808e4adf396845ad654b3cd

*Stack Trace*
<pre>
QgsMapCanvas::setMapTool :
QgisApp::activateDeactivateLayerRelatedActions :
QMetaObject::activate :
QgisApp::activeLayerChanged :
QgisApp::onActiveLayerChanged :
QMetaObject::activate :
QgsLayerTreeView::currentLayerChanged :
QgsLayerTreeView::onCurrentChanged :
QMetaObject::activate :
QItemSelectionModel::`default constructor closure' :
QItemSelectionModel::qt_static_metacall :
QMetaObject::activate :
QAbstractItemModel::beginRemoveRows :
QgsLayerTreeModel::nodeWillRemoveChildren :
QMetaObject::activate :
QgsLayerTreeNode::willRemoveChildren :
QMetaObject::activate :
QgsLayerTreeNode::willRemoveChildren :
QgsLayerTreeNode::removeChildrenPrivate :
QgsLayerTreeGroup::removeChildren :
QgsLayerTreeGroup::removeChildNode :
QgisApp::removeLayer :
QgisApp::qt_static_metacall :
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QMenu::exec :
QgsLayerTreeView::contextMenuEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.4.10-Madeira
QGIS code revision: 3d97aaae88
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
>  QGIS Version: 3.4.10-Madeira

@Heryx too old, you must upgrade to the latest 3.10 or 3.12. Also before testing again create a new QGIS profile (no 3rd party plugins installed).

**Comment by Heryx** [comment]
@gioman thanks for the answer. I tried many times to install a new version, but I have the same problem any time. This is the warning:

> WARNING    Impossibile caricare la libreria di supporto Python: Impossibile caricare la libreria qgispython: Impossibile trovare il modulo specificato.

![image](https://user-images.githubusercontent.com/11267377/80551049-69ce2600-89c2-11ea-9347-a3462ea9ed74.png)

**Comment by gioman** [comment]
>  I have tried many times to install the new versions, but it always gives me the same error.

@Heryx you have an incomplete/broken install. I would suggest you to try uninstall any QGIS version you may have intalleed, get rid of leftovers and try again with the standalone installer.

**Comment by Heryx** [comment]
Should I also delete the Osgeo4W and Qgis folders?

**Comment by gioman** [comment]
> Should I also delete the Osgeo4W and Qgis folders?

I would say yes.

**Comment by Heryx** [comment]
Perfect! I uninstalled everything and also deleted the Qgis and Osgeo user profiles and folders from Programs. I installed Qgis v. 12 from Osgeo and works fine.
