### ISSUE TITLE
VRTs of COGs display wrong when zoomed out

### ISSUE THREAD

**Issue by drwelby** [qgis/QGIS#36066]
**Describe the bug**

VRTS of large Cloud Optimized Geotiffs in S3 do not render correctly when zoomed out. The colors are shifted. This may be confusion between YCbCr and RGB.

**How to Reproduce**

1) Load this large COG:

`https://opendata.digitalglobe.com/events/covid19-congo/pre-event/2019-01-08/103001008947F600/103001008947F600.tif`

<img width="256" alt="Screen Shot 2020-04-28 at 12 08 43 PM" src="https://user-images.githubusercontent.com/152875/80527348-14096780-8949-11ea-8ea2-3a49ba6c585c.png">

2) Built a VRT of the COG:

`gdalbuildvrt ./congo.vrt /vsicurl/https://opendata.digitalglobe.com/events/covid19-congo/pre-event/2019-01-08/103001008947F600/103001008947F600.tif`

3) Load the VRT

<img width="256" alt="Screen Shot 2020-04-28 at 12 07 04 PM" src="https://user-images.githubusercontent.com/152875/80527269-efad8b00-8948-11ea-8e97-6798d1e2d8b6.png">

**QGIS and OS versions**

QGIS version | 3.12.2-București | QGIS code revision | 8a1fb33634
-- | -- | -- | --
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.28.0 | Running against SQLite | 3.28.0
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS Mojave (10.14)
Active python plugins | stac_browser; SRTM-Downloader; processing; db_manager; MetaSearch

**Comment by rouault** [comment]
For what is worth, it works for me with QGIS master and GDAL master. In your snapshot, the image also looks to be flipped in horizontal and vertical directions. And the georeferencing I get is the correct one since it overlaps nicely with opensteetmap.

**Comment by gioman** [comment]
@drwelby also looks ok on QGIS master on Ubuntu 18.04 and QGIS 3.12 on Windows (and is also oriented the right way).

**Comment by drwelby** [comment]
Ha, I had the Project CRS set for the other side of the globe from testing some other COGs.

Thanks for checking, I'll test on some other version/systems. I just might be the lucky ducky on this one.

**Comment by drwelby** [comment]
I get the same odd colors in 3.2 on the same computer as above.

**Comment by drwelby** [comment]
A coworker gets odd colors also with QGIS v 3.12 but not with QGIS 2.18 (OSX 10.14)

Another coworker sees odd colors with QGIS 3.4.13 and Ubuntu 18.04

**Comment by drwelby** [comment]
Source of the problem sleuthed out by @chloeahampton : Affected systems are trying to use the mask band as band 4 and applying transparency. Going to Properties > Transparency > Custom Transparency Options and changing Transparency Band from `Band 4 (Alpha)` to `None` returns the image to a normal appearance

**Comment by rouault** [comment]
I get expected behaviour by both enabling the transparency band (transparency works) or disabling it (padding appears black)

**Comment by chloeahampton** [comment]
Hm. Very weird. @rouault  what operating system are you using? I am on Mac OS 10.14.5, and also should have the latest versions of GDAL and QGIS.

**Comment by rouault** [comment]
Linux, but operating system is likely completely irrelevant. QGIS and GDAL versions could be, although if you use relatively recent ones, I wouldn't expect big differences in results (but easy to forget the tiny change that makes the whole difference). I'm using very latest QGIS and GDAL compiled from source (master versions)

**Comment by chloeahampton** [comment]
Can you list the version #s? I just compiled the env I am working off of about a week ago, so I don't expect much has changed since then. I am running GDAL 3.0.2 and QGIS 3.12.1.

**Comment by drwelby** [comment]
Also interesting is that if I zoom in enough, the colors switch to appearing correct. I assume this is when the COG overviews are not being used.

**Comment by drwelby** [comment]
If export the VRT to TIFF using QGIS's Save As, the exported tiff does not have color problems.

If I VRT that local exported TIFF, it works correctly.

If I `rio cogeo create` that TIFF to COG, and VRT that, it also works correctly.

So it seems like something to do with overviews that are `vsis3` or `vsicurl`.

**Comment by rouault** [comment]
There have been multi threading fixes done in 3.0.4 regarding /vsicurl/ /vsis3/ that could perhaps explain random corruptions. But I'm not sure QGIS triggered that bug (should probably require more intense multithreading use). You could try to see if turning on/off parallel rendering changes things.

**Comment by drwelby** [comment]
No change with turning parallel rendering off.

**Comment by gioman** [comment]
> No change with turning parallel rendering off.

anyway testing with anything below QGIS 3.10 and GDAL 3 does not make any sense, try to check if with this setup you find a common detail on the systems where you observe the wrong rendering.

**Comment by drwelby** [comment]
>testing with anything below QGIS 3.10 and GDAL 3 does not make any sense

Testing with 2X is how Chloe found the source of the problem - it's the only version that doesn't have transparency rendering.
