### ISSUE TITLE
Error trying to access the Settings / properties menu

### ISSUE THREAD

**Issue by GisPaterna** [qgis/QGIS#36078]
When I try to access the Settings / properties menu it takes a while and finally gives error.
Before, it did not happen and I could access. I have been installing plugins, it could be that some have caused this error.
I have reinstalled the program several times and the error persists.
Greetings and thank you.

## Report Details

**Crash ID**: [c0e1ac8728ea0e674d34ce6cfa5ffc64f700c87d](https://github.com/qgis/QGIS/search?q=c0e1ac8728ea0e674d34ce6cfa5ffc64f700c87d&type=Issues)

**Stack Trace**
<pre>
clRetainDevice :
cl::detail::getInfoHelper<cl::detail::GetInfoFunctor0<int (__stdcall*)(_cl_program *,unsigned int,unsigned int,void *,unsigned int *),_cl_program *>,cl::Device> cl2.hpp:1014
cl::Context::getInfo<4225> cl2.hpp:2880
cl::Device::makeDefault cl2.hpp:2955
std::_Callback_once<std::tuple<void (__cdecl&)(void),std::exception_ptr &>,std::integer_sequence<unsigned int,0>,1> mutex:504
RtlRunOnceExecuteOnce :
InitOnceExecuteOnce :
__crtInitOnceExecuteOnce winapisupp.cpp:225
std::_Execute_once xonce.cpp:14
std::call_once<void (__cdecl&)(void)> mutex:519
cl::Device::getDefault cl2.hpp:2013
QgsOpenClUtils::activeDevice qgsopenclutils.cpp:272
QgsOpenClUtils::activate qgsopenclutils.cpp:310
<lambda_e52bae7ef377df945b84291a90b55216>::operator() qgsopenclutils.cpp:184
std::_Callback_once<std::tuple<<lambda_e52bae7ef377df945b84291a90b55216> &&,std::exception_ptr &>,std::integer_sequence<unsigned int,0>,1> mutex:504
RtlRunOnceExecuteOnce :
InitOnceExecuteOnce :
__crtInitOnceExecuteOnce winapisupp.cpp:225
std::_Execute_once xonce.cpp:14
std::call_once<<lambda_e52bae7ef377df945b84291a90b55216> > mutex:519
QgsOpenClUtils::available qgsopenclutils.cpp:466
<lambda_f3c086a0d874dc54a13c72008918ba07>::operator() qgsoptions.cpp:1155
QtPrivate::QFunctorSlotObject<<lambda_f3c086a0d874dc54a13c72008918ba07>,1,QtPrivate::List<bool>,void>::impl qobjectdefs_impl.h:427
QMetaObject::activate :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::setChecked :
</pre>

**QGIS Info**
QGIS Version: 3.12.2-Bucure?ti
QGIS code revision: 8a1fb33634
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.3.9600

**Comment by Gustry** [comment]
> I have been installing plugins

You should try with a new QGIS profile.
Go in `Settings` -> `User Profile` -> `New profile`. Thanks.

**Comment by Forna73** [comment]
Hey.... He said he can't enter setting...

**Comment by elpaso** [comment]
@GisPaterna did you enable OpenCL acceleration?

There is a key in the settings names `OpenClEnabled`, try setting it to false (or just delete it, because the default is false).

I don't know how to manually edit QGIS settings on windows though.

**Comment by Gustry** [comment]
Indeed ... I read the QGIS Properties dialog.

To create a new profile manually, just in case:
In `QGIS/QGIS3/profiles` (not sure on windows where is the folder), edit the file `profiles.ini` and set a new profile name. The profile will be created automatically when QGIS will restart/

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
