### ISSUE TITLE
Problem printing A1 layouts

### ISSUE THREAD

**Issue by IvanRoero** [qgis/QGIS#36080]
When changing the print settings of the presentation from A4 to A1 it does not save the change and keeps A4 as the print format. This will be able to print a presentation in A1.

![Captura3 10](https://user-images.githubusercontent.com/64520234/80569539-6ace7a00-89f9-11ea-95f8-9689f4cb661f.JPG)

**Comment by Forna73** [comment]
Hi!
I also have severl problems with layouts.... 

https://github.com/qgis/QGIS/issues/34504

**Comment by gioman** [comment]
> When changing the print settings of the presentation from A4 to A1 it does not save the change and keeps A4 as the print format.

@IvanRoero that is not how do you set up the size of a page (also remember that any layout can be multipage and that any page can have a different size).

Right click on a specific page and select "page properties". On the right the "item properties" tab will now show you the settings for that specific page like size, orientation, etc.

![Screenshot_20200429_101806](https://user-images.githubusercontent.com/1951107/80579959-bb96a080-8a02-11ea-9f16-9b23a44ae26c.png)

Then when you are actually printing you can setup the actual size of the paper sheet with the dialog you show in you description.

**Comment by IvanRoero** [comment]
@gioman In the option "element properties" I have the horizontal A1 configured but when I try to print the file it prints in A4
![Captura3 10](https://user-images.githubusercontent.com/64520234/80580673-37e1b180-8a0c-11ea-94bf-e5f6af811a1d.JPG)

In the print dialog box I also set A1 but the result is an A4 file that only covers part of the A1
![Capturas3 10](https://user-images.githubusercontent.com/64520234/80581174-12a17300-8a0d-11ea-92ac-f2c131e5a301.jpg)

**Comment by gioman** [comment]
> In the print dialog box I also set A1 but the result is an A4 file that only covers part of the A1

@IvanRoero if you are exporting ("printing") to PDF try use the QGIS native functionality instead of any other external tool (adobe PDF or else). This way do you get the expected result in terms of size/orientation?

**Comment by gioman** [comment]
![Screenshot_20200429_103946](https://user-images.githubusercontent.com/1951107/80581870-c141b580-8a05-11ea-9b9b-24aadad23f89.png)

**Comment by IvanRoero** [comment]
Using the export in pdf function works correctly

thanks for the input

**Comment by gioman** [comment]
> @gioman Using the export in pdf function works correctly
> 
> thanks for the input

@IvanRoero is there any issue left here? if you want to use an external pdf exporter I guess that you should figure why it is not producing the correct format.

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
