### ISSUE TITLE
Crash removing QgsAnnotation in python

### ISSUE THREAD

**Issue by enricofer** [qgis/QGIS#36098]
**Describe the bug**

Using QsgAnnotationManager removeAnnotation https://qgis.org/api/classQgsAnnotationManager.html#aa13d646dfc42df3c228625a9762669e0 
in python code crash QGIS

**How to Reproduce**
create and run a new python script:
```
from qgis.core import QgsTextAnnotation, QgsProject
from PyQt5.QtGui import QTextDocument

TD =QTextDocument("CENTER")
item = QgsTextAnnotation()
item.setMapPosition(iface.mapCanvas().extent().center())
item.setFrameSize(TD.size())
item.setDocument(TD)
QgsProject.instance().annotationManager().addAnnotation(item)
QgsProject.instance().annotationManager().removeAnnotation(item)
```
The last row crashes QGIS, removing it simply add an annotation in the center of mapCanvas
Executing step by step in python console does not crash

**QGIS and OS versions**

Versione di QGIS | 3.10.4-A Coruña | Revisione codice QGIS | 10bc9f2ff2
-- | -- | -- | --
Compilato con Qt | 5.11.2 | Esecuzione con Qt | 5.11.2
Compilato con GDAL/OGR | 3.0.4 | Esecuzione con GDAL/OGR | 3.0.4
Compilato con GEOS | 3.8.1-CAPI-1.13.3 | Esecuzione con GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
Versione client PostgreSQL | 11.5 | Versione SpatiaLite | 4.3.0
Versione QWT | 6.1.3 | Versione QScintilla2 | 2.10.8
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Windows 10 (10.0)
Active python plugins | db_manager; MetaSearch; processing

**Additional context**

the report detail is the following:

Crash ID: d10b1032d016460e7f60637a71784b062b24b5ed

Stack Trace

QgsFields::~QgsFields qgsfields.cpp:45
QgsSymbol::startRender qgssymbol.cpp:431
QgsAnnotation::drawFrame qgsannotation.cpp:380
QgsAnnotation::render qgsannotation.cpp:143
QgsMapCanvasAnnotationItem::paint qgsmapcanvasannotationitem.cpp:311
QGraphicsScene::dragMoveEvent :
QGraphicsScene::drawItems :
QGraphicsScene::drawItems :
QGraphicsView::paintEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QApplication::windowIcon :
QWidget::event :
QgisApp::event qgisapp.cpp:1929
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
QGraphicsScene::~QGraphicsScene :
QObject::event :
QGraphicsScene::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1607
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.10.4-A Coru�a
QGIS code revision: 10bc9f2ff2
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by stev-0** [comment]
This works fine for me on master on Linux

**Comment by enricofer** [comment]
I tested crash on another QGIS 3.10.5, then I confirm report for Windows platform.

**Comment by SebastienPeillet** [comment]
I reproduced the bug.

Indeed if you test it in the python console, there is no bug, but placed in a script, QGIS crashes.

I open a parenthesis : @enricofer I guess it is about the red layer plugin you made and this [issue](https://github.com/enricofer/redLayer/issues/12) (I'm not a mad investigator, I'm just working with @haubourg :) )

In the red layer plugin case, I tried to change your code to use QgsAnnotationManager, and I got QGIS crash too when I tried using `removeAnnotation` function. From what I see it comes from the fact the QgsAnnotation is deleted [here](https://github.com/qgis/QGIS/blob/master/src/core/annotations/qgsannotationmanager.cpp#L59), and then the QgsMapCanvasAnnotationItem tries to render it [here](https://github.com/qgis/QGIS/blob/master/src/gui/qgsmapcanvasannotationitem.cpp#L309) (that the line 311 you get in the stacktrace).

I made a test, by removing annotation pointer in the QgsMapCanvasAnnotation before destroying the QgsAnnotation and it seems to work... end of parenthesis 

But I don't know why this appends only when we play it on a script or in a plugin so I'm not sure of the fix I suggest above

**Comment by aman16sachdeva** [comment]
Hi @SebastienPeillet can you please provide a little bit of the python code, for how to disconnect/remove annotation from QgsMapCanvasAnnotation? Thanks

**Comment by aman16sachdeva** [comment]
Hello, can anyone give me the python code to avoid this Bug? It's required for the project that I'm working on, and it's little urgent. Thank you.

**Comment by haubourg** [comment]
@aman16sachdeva what says  @SebastienPeillet is that scripting this doesn't work for now, we need to fix qgis core apparently

**Comment by SebastienPeillet** [comment]
Sorry I didn't see the request. As @haubourg said, my script attempt only works after fixing qgis core. But even if I found a cure, I don't understand yet why the bug exists in script but not in the python console...

**Comment by aman16sachdeva** [comment]
@haubourg @SebastienPeillet Thank you both for making it clear.

**Comment by aman16sachdeva** [comment]
Also @haubourg and @SebastienPeillet, I'd like to bring this to your notice, that the work around for me was to make the QgsAnnotation invisible instead of removing it.

Later, while experimenting, I found out this:
If in one cycle (running the python script in my plugin) I made the QgsAnnotation invisible. Later, when running the same script again, if I remove/delete annotations (ONLY the ones which I made invisible in previous cycle), then QGIS did not crash.

**Comment by troopa81** [comment]
@aman16sachdeva I didn't reproduce the issue with 3.10.5-A Coruña or with current master.

Could you test with 3.10.5 or master and tell me if you still meet the issue?

**Comment by zacwang89** [comment]
I can reproduce the bug on 3.4.12-Madeira. 
And @aman16sachdeva workaround didn't work for me.

**Comment by Pedro-Murteira** [comment]
@enricofer Hello, is the crash still replicable in recent versions?
