### ISSUE TITLE
Plugin processing : The plugin will be disabled because it crashed QGIS during last startup.

### ISSUE THREAD

**Issue by romeuvieira** [qgis/QGIS#36122]
Dear all,

yesterday after updating my version of 3.12 to the lates update version, when starting QGIS I always get this message:

"2020-05-01T10:50:16     WARNING    **Plugin processing : The plugin will be disabled because it crashed QGIS during last startup.** Please report an issue and re-enable the plugin when the problem has been solved."

When I try to activate the plugin QGIS crashes.

I have tried version 3.10.5 and it happens the same, but not with 3.8.

Any idea of what can I have done wrong!

IMPORTANT:

If the issue concerns a third party plugin (downloaded with the plugin manager) then it can't be fixed by the QGIS team.
Please raise your issue in the dedicated bug tracker for that specific plugin (as listed in the plugin's description)

Tickets created here will be closed.

**Comment by gioman** [comment]
@romeuvieira hi, this is not a support channel, use the users/developers mailing lists for support. This facility should only be used for bug reports.

Anyway can you please try with a new QGIS profile? Thanks.

**Comment by romeuvieira** [comment]
Thanks.

Just uninstalled the 2 versions and deleted users appdata profile folders, reinstalled and both working now.

P.S. - sorry to open new issue in wrong page.
