### ISSUE TITLE
Applying same value to multiple fields

### ISSUE THREAD

**Issue by saberraz** [qgis/QGIS#36121]
Currently, this is possible using field calculator. But an easier way is:
https://desktop.arcgis.com/en/arcmap/10.3/manage-data/editing-attributes/applying-the-same-attribute-values-to-multiple-features-in-a-layer.htm

**Comment by uclaros** [comment]
You want to apply the same value to multiple fields or multiple features?

**Comment by saberraz** [comment]
Correct...in ArcGIS, when you select multiple features, it allows you edit the form for all the selected features in one go, provided that the value is the same across all the selected features.

**Comment by Gustry** [comment]
Do you mean this https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/attribute_table.html#editing-multiple-fields ?

**Comment by saberraz** [comment]
I'd better RTFM :)
