### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by rperry1989** [qgis/QGIS#36125]
Crash ID: 99310f88596fb5c9f28898180751344e1c50bac3

Stack Trace

QList::append qlist.h:581
proj_collecting_logger qgscoordinatetransform_p.cpp:292
osgeo::proj::datum::Datum::conventionalRS :
osgeo::proj::datum::Datum::conventionalRS :
QgsDatumTransform::transformDetailsFromPj qgsdatumtransform.cpp:380
QgsDatumTransform::operations qgsdatumtransform.cpp:61
QgsDatumTransformDialog::QgsDatumTransformDialog qgsdatumtransformdialog.cpp:202
QgsDatumTransformDialog::run qgsdatumtransformdialog.cpp:47
QgisApp::askUserForDatumTransform qgisapp.cpp:14146
QgisApp::addVectorLayerPrivate qgisapp.cpp:11445
QgisApp::handleDropUriList qgisapp.cpp:1870
::operator() qgisapp.cpp:1790
QtPrivate::QFunctorSlotObject,0,QtPrivate::List,void>::impl qobjectdefs_impl.h:422
QMetaObject::activate :
QTimer::timerEvent :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32Private::sendTimerEvent :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1606
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.10.5-A Coru�a
QGIS code revision: 984615fe1e
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by gioman** [comment]
@rperry1989 not enough infos (as requested by the ticket template).

Please

1) try with a new QGIS profile

2) please add exact steps to follow to replicate the issue, adding sample project/data if needed.

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
