### ISSUE TITLE
CRASH -- RASTER - POSTGIS - BAND linked to TIFF file

### ISSUE THREAD

**Issue by caymo04** [qgis/QGIS#36145]
## User Feedback

Refreshing with 3 RASTER linked with POSTGIS.

This raster, in POSTGIS, are linked to TIFF files. The raster band linked to TIFF file.

Best regards

## Report Details

**Crash ID**: [b25300e4f6d106818e7f7b0388469dbf76ca2356]('https://github.com/qgis/QGIS/search?q=b25300e4f6d106818e7f7b0388469dbf76ca2356&type=Issues')

**Stack Trace**
<pre>
memcpy_repmovs memcpy.asm:114
PQescapeBytea :
PQprintTuples :
PQprintTuples :
PQgetResult :
PQfreeNotify :
PQexec :
GDALRegister_PostGISRaster :
GDALRasterBand::RasterIO :
QgsProcessingModelOutput::toVariant :
QgsRasterIdentifyResult::params :
QgsAbstractDatabaseProviderConnection::TableProperty::GeometryColumnType::operator== :
QgsHillshadeRenderer::block :
QgsBrightnessContrastFilter::block :
QgsHueSaturationFilter::block :
QgsRasterResampleFilter::block :
QgsRasterProjector::block :
QgsRasterIterator::readNextRasterPartInternal :
QgsRasterDrawer::draw :
QgsRasterLayerRenderer::render :
QgsMapRendererParallelJob::renderLayerStatic :
QgsArchive::zip :
QgsImageOperation::overlayColor :
QgsMapRendererParallelJob::cancelWithoutBlocking :
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.1-A Coru�a
QGIS code revision: ef24c526da
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
>  QGIS Version: 3.10.1-A Coru�a

@caymo04 try the latest 3.10 or 3.12, there are have been fixes about postgis rasters.

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
