### ISSUE TITLE
Save transparency style

### ISSUE THREAD

**Issue by constantinogaga** [qgis/QGIS#36155]
Qgis 3.4 Madeira

Trying to save a Style with "no data" value 255

I added a file with a transparency pixel list. And my value for "no data" was 255.

After saving the style and accepting changes, the value of "no data" appears duplicate. (255255).

I fix it including 255 as transparency pixels list but finally is not the same result.

**Comment by gioman** [comment]
> Qgis 3.4 Madeira

too old, please try again with the latest 3.10 or 3.12.

**Comment by constantinogaga** [comment]
Ok. Thanks.

**Comment by alexbruy** [comment]
I can not reproduce with master. Please try with recent version and if issue still exists provide steps to reproduce.

**Comment by constantinogaga** [comment]
Ok...I don't speak english really well but I saved for you a video in this youtube link with the problem. This video have been recorded with the 3.10 qgis version.
https://youtu.be/1eEAYWLIAUs

**Comment by gioman** [comment]
@constantinogaga I also cannot replicate, maybe is data dependent, please attach a sample (and the style file).

**Comment by gioman** [comment]
Closing for lack of further feedback.
