### ISSUE TITLE
Trim/Extend Tool

### ISSUE THREAD

**Issue by jdogbey** [qgis/QGIS#36154]
<!--
## User Feedback

Anytime I use the trim/extend tool. It will automatically freeze and crashed.

## Report Details

**Crash ID**: [f4dc07df322da7d803bc6c83375e05d47872bd16]('https://github.com/qgis/QGIS/search?q=f4dc07df322da7d803bc6c83375e05d47872bd16&type=Issues')

**Stack Trace**
<pre>
QgsVectorLayer::wkbType :
QgsMapToolTrimExtendFeature::canvasMoveEvent :
QgsMapCanvas::mouseMoveEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.0-A Coruña
QGIS code revision: 6c816b4204
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by alexbruy** [comment]
Please provide detailed description.

**Comment by jdogbey** [comment]
Find below my steps

I open Qgis 3.10 or 3.12 in the event of editing a line due to its overshooting or undershooting,  

I click on the trim/extend tool

The software freezes and crashes.

With message below;

**Crash ID: 91df3983a318701b021ac0e78074d8b61844d2e8


Stack Trace


pal::LabelPosition::getId :
QgsMapToolTrimExtendFeature::canvasMoveEvent :
QgsMapCanvas::mouseMoveEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.12.0-Bucure?ti
QGIS code revision: cd141490ec
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363**

**Comment by gioman** [comment]
>  QGIS Version: 3.12.0-Bucure?ti

@jdogbey please update to 3.12.2 and try again. Also try with a new QGIS profile and no 3rd party plugins installed.

**Comment by jdogbey** [comment]
@gioman I will do that

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
