### ISSUE TITLE
Cannot remove materialized views from QGIS Browser

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#36164]
QGIS master on Ubuntu 18.04

```
Unable to delete view "public"."xxx": 
ERROR:  "xxx" is not a view
HINT:  Use DROP MATERIALIZED VIEW to remove a materialized view
```

**Comment by espinafre** [comment]
I'm looking into this. I have a wonderful fix, but these margins are too small to contain it :)

Actually, the fix itself is pretty trivial, but I'm struggling with the test case. As soon as I manage to write one, I will submit a PR.

The change is this, if you are interested in testing locally:

```diff
diff --git a/src/providers/postgres/qgspostgresdataitems.cpp b/src/providers/postgres/qgspostgresdataitems.cpp
index ebffd360db..78a3a27cde 100644
--- a/src/providers/postgres/qgspostgresdataitems.cpp
+++ b/src/providers/postgres/qgspostgresdataitems.cpp
@@ -59,7 +59,7 @@ bool QgsPostgresUtils::deleteLayer( const QString &uri, QString &errCause )
   QString type = resViewCheck.PQgetvalue( 0, 0 );
   if ( type == QLatin1String( "v" ) || type == QLatin1String( "m" ) )
   {
-    QString sql = QString( "DROP VIEW %1" ).arg( schemaTableName );
+    QString sql = QString( "DROP %1VIEW %2" ).arg( type == QLatin1String( "m" ) ? "MATERIALIZED " : QString(), schemaTableName );
     QgsPostgresResult result( conn->PQexec( sql ) );
     if ( result.PQresultStatus() != PGRES_COMMAND_OK )
     {

```

**Comment by gioman** [comment]
> I'm looking into this. I have a wonderful fix, but these margins are too small to contain it :)

hopefully the fix won't be as long as the real prove of the Fermat theorem ;)

**Comment by espinafre** [comment]
@gioman , Olá de aquém-mar! There is the PR; this margin was indeed too small for the unit test, I've given up, and since there is no other similar unit tests, and the change is trivial, I'm comfortable with submitting the PR as it is. Now to get the attention of someone who has commit privileges...
