### ISSUE TITLE
Layout Manager - Legend - Only show items in Linked Map not working 

### ISSUE THREAD

**Issue by nbombers** [qgis/QGIS#36161]
**Describe the bug**
Selecting "Only show items in Linked map" function not working all items in initial map extent are displayed in legend - variables showing Filter by map = false 

**How to Reproduce**

![qgis bug](https://user-images.githubusercontent.com/44692685/80932429-b1a9de80-8e02-11ea-90d1-ba1c2f47889c.PNG)

1. Launch 'Layout Manager'
2. Select 'Legend' 
3. Click on 'Only Shoe Items in Linked Map'
4. See error -->

**QGIS and OS versions**

QGIS version: 3.10.3-A Coruña
QGIS code revision: 0e1f846438
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL/OGR: 3.0.4
Running against GDAL/OGR: 3.0.4
Compiled against GEOS: 3.8.0-CAPI-1.13.1
Running against GEOS: 3.8.0-CAPI-1.13.1 
Compiled against SQLite: 3.29.0
Running against SQLite: 3.29.0
PostgreSQL Client Version: 11.5
SpatiaLite Version: 4.3.0
QWT Version: 6.1.3
QScintilla2 Version: 2.10.8
Compiled against PROJ: 6.3.1
Running against PROJ: Rel. 6.3.1, February 10th, 2020
OS Version: Windows Server 2012 R2 (6.3)
Active python plugins: quick_map_services; 
db_manager; MetaSearch; processing

**Additional context**
The issue has been replicated on 2 different VDI instances, but not on a locally installed version of QGIS 3.10.3

**Comment by nyalldawson** [comment]
You'll need to provide more information to debug this, e.g. a sample project.

**Comment by nbombers** [comment]
[bug test data.zip](https://github.com/qgis/QGIS/files/4574100/bug.test.data.zip)
I haven't been able to replicate the issue this evening so I'm not sure if it's a network / VDI permissions issue or a QGIS issue. I've had two of my Tumut based users report the same issue and I was able to replicate it is this morning using these datasets.

**Comment by Pedro-Murteira** [comment]
@nbombers I'm not being able to replicate this issue on QGIS 3.22.3. (Windows 10). Did you come across this bug in more recent versions?

**Comment by nbombers** [comment]
No the issue didn't come across into the newer versions thanks for checking
