### ISSUE TITLE
Incremental rendering of WMT-S tiles onto map canvas

### ISSUE THREAD

**Issue by pktrigg** [qgis/QGIS#36160]
hi
I am running QGIS V 3.12.1, and seem to have bumped into this issue again. it was previously [https://github.com/qgis/QGIS/issues/22610](https://github.com/qgis/QGIS/issues/22610 )

The server is geoserver running on localhost (for test purposes). I have the wmts setup and it servers tiles as expected. I am independently testing with arcgis pro, which correctly renders the tiles as they are served.

It is clear the rendering waits until all requested tiles arrive before rendering an of them. any chance this can be looked at?
I have been looking at this all day and am now pretty confident there is an issue here.

**Comment by elpaso** [comment]
Is this a bug? Looks more like an enhancement request to me.

**Comment by gioman** [comment]
> Is this a bug? Looks more like an enhancement request to me.

@elpaso description and related tickets seems to indicate that this was an issue that at some point was fixed. https://github.com/qgis/QGIS/issues/18865

**Comment by Pedro-Murteira** [comment]
@pktrigg Hello, is this issue still valid on more recent releases?
