### ISSUE TITLE
"Edit user expression" does not allow to rename the user expression

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#36192]
If I have a user expression I'd like to modify, I can change the expression and the help but not the label. Actually you can but changing the label results in a new user expression and it does not remove the previous one.
Since there's already a "Save user expression" that can generate a new expression from an existing one or from scratch, I'd expect the "Edit" button to modify it in place (taking into account all the exposed options)

**Comment by troopa81** [comment]
Proposed PR #36349
