### ISSUE TITLE
Crash when zooming/panning around a single WMTS layer

### ISSUE THREAD

**Issue by chau-intl** [qgis/QGIS#36197]
I started with an empty project and added a single WMTS layer. While zooming/panning around QGIS crashed. 

The cache is set to 1KB (since I would like to avoid any caching while using the WMTS layer).

It has crashed many times now but I haven't found a way to reproduce it.

Below is the QGIS report (report.txt) and the stack (stack.txt).

## User Feedback

See above.

## Report Details

**Crash ID**: [cdbf00a1707bd39d93333b8f29487f8089383584](https://github.com/qgis/QGIS/search?q=cdbf00a1707bd39d93333b8f29487f8089383584&type=Issues)

**Stack Trace**
<pre>
QObject::metaObject :
QIODevice::channelReadyRead :
QIODevice::write :
QLocalSocket::isSequential :
QHttpMultiPart::qt_metacast :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:429
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
QEventLoop::exec :
QgsWmsTiledImageDownloadHandler::downloadBlocking qgswmsprovider.cpp:4072
QgsWmsProvider::draw qgswmsprovider.cpp:951
QgsWmsProvider::readBlock qgswmsprovider.cpp:973
QgsRasterDataProvider::block qgsrasterdataprovider.cpp:201
QgsSingleBandColorDataRenderer::block qgssinglebandcolordatarenderer.cpp:62
QgsBrightnessContrastFilter::block qgsbrightnesscontrastfilter.cpp:118
QgsHueSaturationFilter::block qgshuesaturationfilter.cpp:123
QgsRasterResampleFilter::block qgsrasterresamplefilter.cpp:162
QgsRasterProjector::block qgsrasterprojector.cpp:787
QgsRasterIterator::readNextRasterPartInternal qgsrasteriterator.cpp:130
QgsRasterIterator::readNextRasterPart qgsrasteriterator.cpp:81
QgsRasterDrawer::draw qgsrasterdrawer.cpp:60
QgsRasterLayerRenderer::render qgsrasterlayerrenderer.cpp:294
QgsMapRendererParallelJob::renderLayerStatic qgsmaprendererparalleljob.cpp:353
QtConcurrent::FunctionWrapper1<void,LayerRenderJob & __ptr64>::operator() qtconcurrentfunctionwrappers.h:81
QtConcurrent::MapKernel<QList<LayerRenderJob>::iterator,QtConcurrent::FunctionWrapper1<void,LayerRenderJob & __ptr64> >::runIteration qtconcurrentmapkernel.h:69
QtConcurrent::MapKernel<QList<LayerRenderJob>::iterator,QtConcurrent::FunctionWrapper1<void,LayerRenderJob & __ptr64> >::runIterations qtconcurrentmapkernel.h:78
QtConcurrent::IterateKernel<QList<LayerRenderJob>::iterator,void>::forThreadFunction qtconcurrentiteratekernel.h:255
QtConcurrent::IterateKernel<QList<LayerRenderJob>::iterator,void>::threadFunction qtconcurrentiteratekernel.h:217
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.13.0-Master
QGIS code revision: 89fe6347ae
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.2.0dev
Running against GDAL: 3.2.0dev

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.14393

## Stack

>00: 0x7FFA774763D0 QIODevice::write
>01: 0x7FFA864AF310 QLocalSocket::isSequential
>02: 0x7FFA865189F0 QHttpMultiPart::qt_metacast
>03: 0x7FFA77533770 QObject::event
>04: 0x7FFA78878B60 QApplicationPrivate::notify_helper
>05: 0x7FFA78875FD0 QApplication::notify
>06: 0x7FFA7C62E090 QgsApplication::notify
Local: this = 0x0000000000000000 -> ?
Parm: receiver = 0x00007FFA8651A560 -> ?
Parm: event = 0x0000000000130017 -> ?
Local: done = ?
Source: c:\src\qgis\src\core\qgsapplication.cpp:429
>07: 0x7FFA7750E9A0 QCoreApplication::notifyInternal2
>08: 0x7FFA77510910 QCoreApplicationPrivate::sendPostedEvents
>09: 0x7FFA77557940 QEventDispatcherWin32::processEvents
>10: 0x7FFAB7851F00 UserCallWinProcCheckWow
>11: 0x7FFAB7851910 DispatchMessageWorker
>12: 0x7FFA77557940 QEventDispatcherWin32::processEvents
>13: 0x7FFA7750A770 QEventLoop::exec
>14: 0x7FFA5AEF9E50 QgsWmsTiledImageDownloadHandler::downloadBlocking
Local: this = 0x00000000000000AB -> ?
Source: c:\src\qgis\src\providers\wms\qgswmsprovider.cpp:4072
>15: 0x7FFA5AEE5360 QgsWmsProvider::draw
Local: this = 0x000001B29AF0C581 -> ?
Parm: viewExtent = 0x0000000000000000 -> ?
Parm: pixelWidth = 0
Parm: pixelHeight = -1695496784
Parm: feedback = 0x000001B2650814A0 -> ?
Local: maxWidth = 0
Local: maxHeight = 0
Local: image = 0x0000000000000000 -> ?
Source: c:\src\qgis\src\providers\wms\qgswmsprovider.cpp:951
>16: 0x7FFA5AECCCB0 QgsWmsProvider::readBlock
Local: this = 0x000001B29AF0BD21 -> ?
Parm: bandNo = 0
Parm: viewExtent = 0x0000000000000000 -> ?
Parm: pixelWidth = -1629742832
Parm: pixelHeight = -1695499024
Parm: block = 0x88001F750E026733 -> ?
Parm: feedback = 0x000001B29AF0B360 -> ?
Local: myExpectedSize = 9799860483345115073
Local: ptr = 0x00007FFA776186A0 -> 128
Local: image = ?
Local: myImageSize = 1865732940768
Source: c:\src\qgis\src\providers\wms\qgswmsprovider.cpp:973
>17: 0x7FFA7CEEC6B0 QgsRasterDataProvider::block
Local: this = 0x000001B29AF0BD50 -> ?
Parm: bandNo = -1695503168
Parm: boundingBox = 0x000001B29AF0C0B0 -> ?
Parm: width = 246441805
Parm: height = -1695566607
Parm: feedback = 0x000001B29AF0C170 -> ?
Local: block = ?
Local: tmpExtent = ?
Local: yRes = 0.000000
Local: providerXRes = 0.000000
Local: xRes = 0.000000
Local: providerYRes = 0.000000
Local: tmpXRes = 0.000000
Local: tmpYRes = -0.000000
Source: c:\src\qgis\src\core\raster\qgsrasterdataprovider.cpp:201
>18: 0x7FFA7CF92F90 QgsSingleBandColorDataRenderer::block
Local: this = 0x00007FFA776186A0 -> ?
Parm: bandNo = 1724033584
Parm: extent = 0x000001B2665963E0 -> ?
Parm: width = 469869728
Parm: height = 0
Parm: feedback = 0x88001D660E386735 -> ?
Local: outputBlock = ?
Local: inputBlock = ?
Local: outputBits = 0x0000000400000001 -> 774123152
Local: inputBits = 0x8E001B530E3667CF -> ?
Local: hasTransparency = ?
Source: c:\src\qgis\src\core\raster\qgssinglebandcolordatarenderer.cpp:62
>19: 0x7FFA7CF54770 QgsBrightnessContrastFilter::block
Local: this = 0x0000000000000018 -> ?
Parm: bandNo = 5046360
Parm: extent = 0x000001B29AF00000 -> ?
Parm: width = 235169593
Parm: height = -1695500175
Parm: feedback = 0x000001B29AF0B3C0 -> ?
Local: r = 469869728
Local: g = 434
Local: outputBlock = ?
Local: bandNumber = 434
Local: inputBlock = ?
Local: f = 0.000000
Local: b = 1717134880
Local: myColor = 171
Local: myNoDataColor = 2002880160
Local: alpha = 0
Source: c:\src\qgis\src\core\raster\qgsbrightnesscontrastfilter.cpp:118
>20: 0x7FFA7CF58010 QgsHueSaturationFilter::block
Local: this = 0x00007FFA776186A0 -> ?
Parm: bandNo = 1724026864
Parm: extent = 0x000001B2665966A0 -> ?
Parm: width = 469869728
Parm: height = 0
Parm: feedback = 0x880023010E0E6727 -> ?
Local: r = 1932206133
Local: h = -2013259186
Local: g = 0
Local: outputBlock = ?
Local: bandNumber = 0
Local: myRgb = 434
Local: l = 0
Local: inputBlock = ?
Local: s = 238118850
Local: alphaFactor = 0.000000
Local: b = 171
Local: myColor = ?
Local: myNoDataColor = 0
Local: alpha = 237791169
Source: c:\src\qgis\src\core\raster\qgshuesaturationfilter.cpp:123
>21: 0x7FFA7CF8E1A0 QgsRasterResampleFilter::block
Local: this = 0x0000000000000000 -> ?
Parm: bandNo = -1697028272
Parm: extent = 0x000001B29AF0B690 -> ?
Parm: width = 247818110
Parm: height = 2002880160
Parm: feedback = 0x000001B266C28DB0 -> ?
Local: dstImg = ?
Local: oversamplingX = -0.000000
Local: resWidth = -1695500704
Local: oversampling = 1108190658985295337830219776.000000
Local: outputBlock = ?
Local: bandNumber = 0
Local: tileBufferPixels = 1752462703
Local: img = ?
Local: providerXRes = 0.000000
Local: inputBlock = ?
Local: resHeight = 0
Local: resampleWidth = 2002880160
Local: outputXRes = 4574208252200108681836662393667584.000000
Local: oversamplingY = 0.000000
Local: sourceTileBufferSize = 0.000000
Local: resampleHeight = 32762
Local: cropped = ?
Local: bufferedExtent = ?
Source: c:\src\qgis\src\core\raster\qgsrasterresamplefilter.cpp:162
>22: 0x7FFA7CF412A0 QgsRasterProjector::block
Local: this = 0x0000000000000000 -> ?
Parm: bandNo = -1697028272
Parm: extent = 0x000001B29AF0B690 -> ?
Parm: width = 247818110
Parm: height = 2002880160
Parm: feedback = 0x000001B266C28DB0 -> ?
Local: inverseCt = ?
Local: doNoData = ?
Local: pd = ?
Local: outputBlock = ?
Local: inputBlock = ?
Local: srcRow = 469869728
Local: pixelSize = 1864485676192
Local: srcCol = 434
Source: c:\src\qgis\src\core\raster\qgsrasterprojector.cpp:787
>23: 0x7FFA7CF00F50 QgsRasterIterator::readNextRasterPartInternal
Local: this = 0x0000000000000018 -> ?
Parm: bandNumber = 5046360
Parm: nCols = 0x000001B29AF00000 -> 1
Parm: nRows = 0x880021B20E046739 -> ?
Parm: block = 0x000001B29AF0B871 -> ?
Parm: topLeftCol = 0x000001B29AF0B3C0 -> -1695500080
Parm: topLeftRow = 0x0000000000000000 -> ?
Parm: blockExtent = 0x000001B29AF0B300 -> ?
Local: pInfo = 0x0000000200000001 -> ?
Local: xmax = 0.000000
Local: ymin = 0.000000
Local: blockRect = ?
Local: viewPortExtent = ?
Local: ymax = -0.000000
Local: xmin = -0.000000
Local: partIt = ?
Source: c:\src\qgis\src\core\raster\qgsrasteriterator.cpp:130
>24: 0x7FFA7CF00E30 QgsRasterIterator::readNextRasterPart
Local: this = 0x3D73706C6C652B20 -> ?
Parm: bandNumber = 237791169
Parm: nCols = 0x00007FFA776186A0 -> 2000155776
Parm: nRows = 0x000001B266C28F30 -> 2002878000
Parm: block = 0x000001B266596620 -> ?
Parm: topLeftCol = 0x000001B21C01A4A0 -> 2002880144
Parm: topLeftRow = 0x0000000000000000 -> ?
Parm: blockExtent = 0x88001A4E0E3167C2 -> ?
Source: c:\src\qgis\src\core\raster\qgsrasteriterator.cpp:81
>25: 0x7FFA7CF6E4D0 QgsRasterDrawer::draw
Local: this = 0x000001B2A61D26F0 -> ?
Parm: p = 0x000001B2A6D98D20 -> ?
Parm: viewPort = 0x000001B29EDC1050 -> ?
Parm: qgsMapToPixel = 0x88001E500E3D6736 -> ?
Parm: feedback = 0x000001B29AF0BD21 -> ?
Local: topLeftCol = 1030975596
Local: block = ?
Local: bandNumber = 1752462703
Local: nCols = 32762
Local: nRows = 2002880160
Local: topLeftRow = 1818569504
Source: c:\src\qgis\src\core\raster\qgsrasterdrawer.cpp:60
>26: 0x7FFA7CF2E870 QgsRasterLayerRenderer::render
Local: this = 0x000001B29EDC1050 -> ?
Local: projector = 0x00000000000000AB -> ?
Local: time = ?
Local: errors = ?
Local: iterator = ?
Local: drawer = ?
Source: c:\src\qgis\src\core\raster\qgsrasterlayerrenderer.cpp:294
>27: 0x7FFA7C8A5BA0 QgsMapRendererCustomPainterJob::doRender
Local: this = 0x0000000000000000 -> ?
Local: hasSecondPass = ?
Local: renderTime = ?
Source: c:\src\qgis\src\core\qgsmaprenderercustompainterjob.cpp:316
>28: 0x7FFA7C8A5B60 QgsMapRendererCustomPainterJob::staticRender
Parm: self = 0x6874756F732B0000 -> ?
Source: c:\src\qgis\src\core\qgsmaprenderercustompainterjob.cpp:264
>29: 0x7FFA7C8ACA50 QtConcurrent::StoredFunctorCall1<void,void (__cdecl*)(QgsMapRendererCustomPainterJob * __ptr64),QgsMapRendererCustomPainterJob * __ptr64>::runFunctor
Local: this = 0x0000000200000001 -> ?
Source: c:\osgeo4w64\apps\qt5\include\qtconcurrent\qtconcurrentstoredfunctioncall.h:432
>30: 0x7FFA7C8AC990 QtConcurrent::RunFunctionTask<void>::run
Local: this = 0x000001B266596620 -> ?
Source: c:\osgeo4w64\apps\qt5\include\qtconcurrent\qtconcurrentrunbase.h:136
>31: 0x7FFA77380CB0 QThreadPoolPrivate::reset
>32: 0x7FFA773893A0 QThread::start
>33: 0x7FFAB56284C0 BaseThreadInitThunk
>34: 0x7FFAB80FE850 RtlUserThreadStart

**Comment by gioman** [comment]
@chau-intl any shareable URL?

**Comment by chau-intl** [comment]
I was testing a couple of different URLs (only one at a time though) and since QGIS crashed I cannot determine exactly which one it was at that time (I don't remember either).

It could be this one: https://services.kortforsyningen.dk/service?request=GetCapabilities&servicename=topo_skaermkort_graa&service=WMTS&version=1.0.0&token=78e44008af162a1ff5a755f96c7c9c43

Using the above URL I tried to make a new crash. I succeeded but I think the crash log points to a different issue. I will add that as new bug.

**Comment by chau-intl** [comment]
@gioman... or do you wan't the other bug here as well?

**Comment by gioman** [comment]
>  or do you wan't the other bug here as well?

no, 1 issue per ticket, thanks!

**Comment by Pedro-Murteira** [comment]
@chau-intl I've also came across this bug and tested it while I was testing #36203 and I'm not being able to replicate this one aswell, QGIS 3.22.3. Are you still having this issue?

**Comment by chau-intl** [comment]
No I haven't seen this crash in a long time. I will close this.
