### ISSUE TITLE
(Another)Crash when zooming/panning around a single WMTS layer

### ISSUE THREAD

**Issue by chau-intl** [qgis/QGIS#36203]
While trying to reproduce the crash I got which is reported in #36197 I got another crash. 

The conditions were the same and I definitely used [this](https://services.kortforsyningen.dk/service?request=GetCapabilities&servicename=topo_skaermkort_graa&service=WMTS&version=1.0.0&token=78e44008af162a1ff5a755f96c7c9c43) WMTS URL.

## User Feedback

See above and in issue #36197.

## Report Details

**Crash ID**: [61f141e410c743d06bd4dab425fce4e85d7522bb](https://github.com/qgis/QGIS/search?q=61f141e410c743d06bd4dab425fce4e85d7522bb&type=Issues)

**Stack Trace**
<pre>
operator<< :
QNetworkDiskCache::insert :
QgsNetworkDiskCache::insert qgsnetworkdiskcache.cpp:94
QSslKey::operator!= :
QSslKey::operator!= :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:429
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
QEventLoop::exec :
QgsWmsTiledImageDownloadHandler::downloadBlocking qgswmsprovider.cpp:4072
QgsWmsProvider::draw qgswmsprovider.cpp:951
QgsWmsProvider::readBlock qgswmsprovider.cpp:973
QgsRasterDataProvider::block qgsrasterdataprovider.cpp:201
QgsSingleBandColorDataRenderer::block qgssinglebandcolordatarenderer.cpp:62
QgsBrightnessContrastFilter::block qgsbrightnesscontrastfilter.cpp:118
QgsHueSaturationFilter::block qgshuesaturationfilter.cpp:123
QgsRasterResampleFilter::block qgsrasterresamplefilter.cpp:162
QgsRasterProjector::block qgsrasterprojector.cpp:787
QgsRasterIterator::readNextRasterPartInternal qgsrasteriterator.cpp:130
QgsRasterIterator::readNextRasterPart qgsrasteriterator.cpp:81
QgsRasterDrawer::draw qgsrasterdrawer.cpp:60
QgsRasterLayerRenderer::render qgsrasterlayerrenderer.cpp:294
QgsMapRendererParallelJob::renderLayerStatic qgsmaprendererparalleljob.cpp:353
QtConcurrent::FunctionWrapper1<void,LayerRenderJob & __ptr64>::operator() qtconcurrentfunctionwrappers.h:81
QtConcurrent::MapKernel<QList<LayerRenderJob>::iterator,QtConcurrent::FunctionWrapper1<void,LayerRenderJob & __ptr64> >::runIteration qtconcurrentmapkernel.h:69
QtConcurrent::MapKernel<QList<LayerRenderJob>::iterator,QtConcurrent::FunctionWrapper1<void,LayerRenderJob & __ptr64> >::runIterations qtconcurrentmapkernel.h:78
QtConcurrent::IterateKernel<QList<LayerRenderJob>::iterator,void>::forThreadFunction qtconcurrentiteratekernel.h:255
QtConcurrent::IterateKernel<QList<LayerRenderJob>::iterator,void>::threadFunction qtconcurrentiteratekernel.h:217
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.13.0-Master
QGIS code revision: 89fe6347ae
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.2.0dev
Running against GDAL: 3.2.0dev

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.14393

## Stack
<pre>
>00: 0xD00000001 ?
>01: 0x7FFA7752D750 operator<<
>02: 0x7FFA8647DA80 QNetworkDiskCache::insert
>03: 0x7FFA7C904BE0 QgsNetworkDiskCache::insert
Local: this = 0xF000000000000000 -> ?
Parm: device = 0xF0000000C0980FE2 -> ?
Local: lock = ?
Source: c:\src\qgis\src\core\qgsnetworkdiskcache.cpp:94
>04: 0x7FFA86495B30 QSslKey::operator!=
>05: 0x7FFA86495B30 QSslKey::operator!=
>06: 0x7FFA77533770 QObject::event
>07: 0x7FFA78878B60 QApplicationPrivate::notify_helper
>08: 0x7FFA78875FD0 QApplication::notify
>09: 0x7FFA7C62E090 QgsApplication::notify
Local: this = 0x696D656F6A6C694D -> ?
Parm: receiver = 0x656972657473696E -> ?
Parm: event = 0x5503062030223174 -> ?
Local: done = ?
Source: c:\src\qgis\src\core\qgsapplication.cpp:429
>10: 0x7FFA7750E9A0 QCoreApplication::notifyInternal2
>11: 0x7FFA77510910 QCoreApplicationPrivate::sendPostedEvents
>12: 0x7FFA77557940 QEventDispatcherWin32::processEvents
>13: 0x7FFAB7851F00 UserCallWinProcCheckWow
>14: 0x7FFAB7851910 DispatchMessageWorker
>15: 0x7FFA77557940 QEventDispatcherWin32::processEvents
>16: 0x7FFA7750A770 QEventLoop::exec
>17: 0x7FFA5AEF9E50 QgsWmsTiledImageDownloadHandler::downloadBlocking
Local: this = 0xFFFFFFFFFFFFFF00 -> ?
Source: c:\src\qgis\src\providers\wms\qgswmsprovider.cpp:4072
>18: 0x7FFA5AEE5360 QgsWmsProvider::draw
Local: this = 0x0000000000440000 -> ?
Parm: viewExtent = 0x0000000300000000 -> ?
Parm: pixelWidth = 5
Parm: pixelHeight = 2011996368
Parm: feedback = 0x0000038900000424 -> ?
Local: maxWidth = 2097267
Local: maxHeight = 4522066
Local: image = 0x000001DB9E83AE70 -> ?
Source: c:\src\qgis\src\providers\wms\qgswmsprovider.cpp:951
>19: 0x7FFA5AECCCB0 QgsWmsProvider::readBlock
Local: this = 0x00007FFA776186A0 -> ?
Parm: bandNo = -1674912400
Parm: viewExtent = 0x000001DB9C423920 -> ?
Parm: pixelWidth = 724014768
Parm: pixelHeight = 0
Parm: block = 0x80001120B2776354 -> ?
Parm: feedback = 0x000001DBA91C6390 -> ?
Local: myExpectedSize = 9799845153067066146
Local: ptr = 0x000001DB9E6EBB61 -> 136
Local: image = ?
Local: myImageSize = 2042892864592
Source: c:\src\qgis\src\providers\wms\qgswmsprovider.cpp:973
>20: 0x7FFA7CEEC6B0 QgsRasterDataProvider::block
Local: this = 0x000001DBA84292A0 -> ?
Parm: bandNo = -1472032096
Parm: boundingBox = 0x000001DBA84292A0 -> ?
Parm: width = -1301779290
Parm: height = 1
Parm: feedback = 0x000000090000000D -> ?
Local: block = ?
Local: tmpExtent = ?
Local: yRes = -0.000000
Local: providerXRes = -0.000000
Local: xRes = -0.000000
Local: providerYRes = 0.000000
Local: tmpXRes = 0.000000
Local: tmpYRes = 0.000000
Source: c:\src\qgis\src\core\raster\qgsrasterdataprovider.cpp:201
>21: 0x7FFA7CF92F90 QgsSingleBandColorDataRenderer::block
Local: this = 0x000001DBA5E74E90 -> ?
Parm: bandNo = 568248867
Parm: extent = 0x000001DBA5E74C50 -> ?
Parm: width = -2147483648
Parm: height = 1869771886
Parm: feedback = 0x80000F63B271632E -> ?
Local: outputBlock = ?
Local: inputBlock = ?
Local: outputBits = 0x000001DBA5E74E90 -> 1600877668
Local: inputBits = 0x80000D3CB26B6328 -> ?
Local: hasTransparency = ?
Source: c:\src\qgis\src\core\raster\qgssinglebandcolordatarenderer.cpp:62
>22: 0x7FFA7CF54770 QgsBrightnessContrastFilter::block
Local: this = 0x000001DB9C5D3A20 -> ?
Parm: bandNo = -1671611872
Parm: extent = 0x61706F726564726F -> ?
Parm: width = 2037672291
Parm: height = 538976266
Parm: feedback = 0x656C6F747463656A -> ?
Local: r = -1636910048
Local: g = 0
Local: outputBlock = ?
Local: bandNumber = 0
Local: inputBlock = ?
Local: f = -0.000000
Local: b = 0
Local: myColor = 4294967040
Local: myNoDataColor = 2658057057
Local: alpha = -1
Source: c:\src\qgis\src\core\raster\qgsbrightnesscontrastfilter.cpp:118
>23: 0x7FFA7CF58010 QgsHueSaturationFilter::block
Local: this = 0x000001DB75FB7840 -> ?
Parm: bandNo = 1978969136
Parm: extent = 0x223D656300000010 -> ?
Parm: width = 170012721
Parm: height = 724858688
Parm: feedback = 0x000001DB75F978D0 -> ?
Local: r = 1
Local: h = -1912599490
Local: g = -1
Local: outputBlock = ?
Local: bandNumber = 7798895
Local: myRgb = 0
Local: l = 475
Local: inputBlock = ?
Local: s = -1301781723
Local: alphaFactor = -0.000000
Local: b = -256
Local: myColor = ?
Local: myNoDataColor = 2659430000
Local: alpha = -1301978334
Source: c:\src\qgis\src\core\raster\qgshuesaturationfilter.cpp:123
>24: 0x7FFA7CF8E1A0 QgsRasterResampleFilter::block
Local: this = 0x000001DB2B34A740 -> ?
Parm: bandNo = -1545215792
Parm: extent = 0x0000000000000000 -> ?
Parm: width = 0
Parm: height = 589824
Parm: feedback = 0x000000010421000E -> ?
Local: dstImg = ?
Local: oversamplingX = 0.000000
Local: resWidth = 7274607
Local: oversampling = 4416581638320396697600.000000
Local: outputBlock = ?
Local: bandNumber = -1635537296
Local: tileBufferPixels = 1030054912
Local: img = ?
Local: providerXRes = -0.000000
Local: inputBlock = ?
Local: resHeight = 7602208
Local: resampleWidth = -1636910239
Local: outputXRes = -0.000000
Local: oversamplingY = 0.000000
Local: sourceTileBufferSize = 0.000000
Local: resampleHeight = 475
Local: cropped = ?
Local: bufferedExtent = ?
Source: c:\src\qgis\src\core\raster\qgsrasterresamplefilter.cpp:162
>25: 0x7FFA7CF412A0 QgsRasterProjector::block
Local: this = 0x000001DB2B34A740 -> ?
Parm: bandNo = -1545215792
Parm: extent = 0x0000000000000000 -> ?
Parm: width = 0
Parm: height = 589824
Parm: feedback = 0x000000010421000E -> ?
Local: inverseCt = ?
Local: doNoData = ?
Local: pd = ?
Local: outputBlock = ?
Local: inputBlock = ?
Local: srcRow = -1636910048
Local: pixelSize = 7955956325402288138
Local: srcCol = 0
Source: c:\src\qgis\src\core\raster\qgsrasterprojector.cpp:787
>26: 0x7FFA7CF00F50 QgsRasterIterator::readNextRasterPartInternal
Local: this = 0x000001DB9C5D3A20 -> ?
Parm: bandNumber = -1671611872
Parm: nCols = 0x61706F726564726F -> ?
Parm: nRows = 0x2231223D79746963 -> ?
Parm: block = 0x626F20202020200A -> ?
Parm: topLeftCol = 0x656C6F747463656A -> ?
Parm: topLeftRow = 0x31223D65636E6172 -> ?
Parm: blockExtent = 0x20202020200A2230 -> ?
Local: pInfo = 0x000001DB9F15B270 -> ?
Local: xmax = -0.000000
Local: ymin = -0.000000
Local: blockRect = ?
Local: viewPortExtent = ?
Local: ymax = 4574208252200108681836662393667584.000000
Local: xmin = 0.000000
Local: partIt = ?
Source: c:\src\qgis\src\core\raster\qgsrasteriterator.cpp:130
>27: 0x7FFA7CF00E30 QgsRasterIterator::readNextRasterPart
Local: this = 0x0000006B636F6C62 -> ?
Parm: bandNumber = -1301978334
Parm: nCols = 0x000001DB9E6EBB61 -> -610373496
Parm: nRows = 0x0000000000000000 -> ?
Parm: block = 0x0000000000000000 -> ?
Parm: topLeftCol = 0x000001DB9E6EBC20 -> 1
Parm: topLeftRow = 0x000001DB9E83AE70 -> 2
Parm: blockExtent = 0x8E000C3EB2686325 -> ?
Source: c:\src\qgis\src\core\raster\qgsrasteriterator.cpp:81
>28: 0x7FFA7CF6E4D0 QgsRasterDrawer::draw
Local: this = 0x00007FFA7761A040 -> ?
Parm: p = 0x6974636580000000 -> ?
Parm: viewPort = 0x000001DB00006E6F -> ?
Parm: qgsMapToPixel = 0x8800102FB2746351 -> ?
Parm: feedback = 0x00007FFA776186A0 -> ?
Local: topLeftCol = 107
Local: block = ?
Local: bandNumber = 1030054912
Local: nCols = 475
Local: nRows = -1636910239
Local: topLeftRow = 1668246626
Source: c:\src\qgis\src\core\raster\qgsrasterdrawer.cpp:60
>29: 0x7FFA7CF2E870 QgsRasterLayerRenderer::render
Local: this = 0x000001DB00006E6F -> ?
Local: projector = 0xFFFFFFFFFFFFFF00 -> ?
Local: time = ?
Local: errors = ?
Local: iterator = ?
Local: drawer = ?
Source: c:\src\qgis\src\core\raster\qgsrasterlayerrenderer.cpp:294
>30: 0x7FFA7C8C2CC0 QgsMapRendererParallelJob::renderLayerStatic
Parm: job = 0x626F20202020200A -> ?
Local: t = ?
Source: c:\src\qgis\src\core\qgsmaprendererparalleljob.cpp:353
>31: 0x7FFA7C8C5500 QtConcurrent::FunctionWrapper1<void,LayerRenderJob & __ptr64>::operator()
Local: this = 0x000001DB9F15B270 -> ?
Parm: u = 0x0000001321DECA30 -> ?
Source: c:\osgeo4w64\apps\qt5\include\qtconcurrent\qtconcurrentfunctionwrappers.h:81
>32: 0x7FFA7C8C5E20 QtConcurrent::MapKernel<QList<LayerRenderJob>::iterator,QtConcurrent::FunctionWrapper1<void,LayerRenderJob & __ptr64> >::runIteration
Local: this = 0x000001DB9F15B270 -> ?
Parm: it = 0x0000001321DECA30 -> ?
Parm: __formal = -256
Parm: __formal = 0x3D65640000000001 -> ?
Source: c:\osgeo4w64\apps\qt5\include\qtconcurrent\qtconcurrentmapkernel.h:69
>33: 0x7FFA7C8C5E90 QtConcurrent::MapKernel<QList<LayerRenderJob>::iterator,QtConcurrent::FunctionWrapper1<void,LayerRenderJob & __ptr64> >::runIterations
Local: this = 0x000001DB9E6EBB61 -> ?
Parm: sequenceBeginIterator = 0x0000000000000000 -> ?
Parm: beginIndex = 0
Parm: endIndex = -1636910048
Parm: __formal = 0x000001DB9E83AE70 -> ?
Local: it = ?
Source: c:\osgeo4w64\apps\qt5\include\qtconcurrent\qtconcurrentmapkernel.h:78
>34: 0x7FFA7C8C58F0 QtConcurrent::IterateKernel<QList<LayerRenderJob>::iterator,void>::forThreadFunction
Local: this = 0x000001DB00006E6F -> ?
Local: blockSizeManager = ?
Local: resultReporter = ?
Source: c:\osgeo4w64\apps\qt5\include\qtconcurrent\qtconcurrentiteratekernel.h:255
>35: 0x7FFA7C8C6390 QtConcurrent::IterateKernel<QList<LayerRenderJob>::iterator,void>::threadFunction
Local: this = 0x000001DB9F15B270 -> ?
Source: c:\osgeo4w64\apps\qt5\include\qtconcurrent\qtconcurrentiteratekernel.h:217
>36: 0x7FFA9F931260 QtConcurrent::ThreadEngineBase::run
>37: 0x7FFA77380CB0 QThreadPoolPrivate::reset
>38: 0x7FFA773893A0 QThread::start
>39: 0x7FFAB56284C0 BaseThreadInitThunk
>40: 0x7FFAB80FE850 RtlUserThreadStart
</pre>

**Comment by Pedro-Murteira** [comment]
@chau-intl I'm not being able to replicate this on QGIS 3.22.3. Are you still having this issue?

**Comment by chau-intl** [comment]
No I haven't seen this crash in a long time. I will close this.
