### ISSUE TITLE
delete layout elements also with keyboard

### ISSUE THREAD

**Issue by Gislindenberg** [qgis/QGIS#36208]
**delete layout elements also with keyboard**
In layout mode you also can delete an element about the menu selection edit --> delete.
I'm missing the possibility to do it with keyboard.

![delete](https://user-images.githubusercontent.com/64850293/81084204-db8ffd80-8ef5-11ea-8c79-ee55d35b66d7.jpg)
![keyboard](https://user-images.githubusercontent.com/64850293/81084785-a2a45880-8ef6-11ea-8aa0-3e2cac1bc6bd.jpg)

**Comment by nyalldawson** [comment]
The "delete" key does this already
