### ISSUE TITLE
[Processing][Vector Creation] Nearest point along geometry

### ISSUE THREAD

**Issue by roya0045** [qgis/QGIS#36209]
Greetings,

I've been using distance to hub on a few occasions and noticed that only the center of the bounding box is used.

This made me want to suggest an improved approach that would use `QgsGeometry::nearestPoint`to either make the nearest point on the surface of the other geometry or make a line directly between the two.

This is useful when you want to 'join' geometry along a line to represent events along a transect or simply to have a way to use the nearest point method between two layers.

**Comment by roya0045** [comment]
If someone is up for it please state your interest otherwise I might attempt this soon and I want to prevent duplicating any efforts.

**Comment by root676** [comment]
I think that is exactly what the `Join by nearest` alg is doing.

**Comment by nyalldawson** [comment]
Yes "join by nearest" does account for the shapes themselves, and that support is present in QgsSpatialIndex. Should be relatively straightforward to enable the right flags on the index in the hub algorithm to get the same behaviour.

**Comment by roya0045** [comment]
@root676 In part but this is not exactly what I have in mind. 

Here is what I am aiming for: To have a point on the main feature that would represent the exact point of the geometry where the nearest feature is. Another possible output would be a line between this closest point and the center of the other geometry or the closest point on the other geometry (closest to closest).

Think of it as an improved version of line to hub that doesn't only use the center. Currently I need something like this to represent points along a transect line to make the 2d graph but it has its uses in other spatial analysis.

@nyalldawson I am not sure if your response is intended for root or for me. But if you have the time could you mention me that flag.

As of now I began working on it by combining the code from join by nearest and join by location to get the base up quickly.

**Comment by root676** [comment]
@roya0045 funny, I have been working on exactly that algorithm while trying to port the ArcGIS Near Table algorithm to QGIS processing. But then I noticed that the Join by nearest alg covers 90% of this functionality. @nyalldawson what do you think about a Near Table alg with additional lines/points output? I have the code ready here.

**Comment by roya0045** [comment]
@root676 I honestly had a hunch that you would do something like this. 😆 Do you have a branch that I can look at? Just to see if I should remove mine or keep on going.

**Comment by root676** [comment]
I had another look at `Join by nearest`: The reason why I didn't open a PR one month ago was that all the features you want to work on are already covered in the exisisting `Join by nearest` algorithm - even for creating geometry from the output eg. lines between the features, start-points, end-points (see the `feature_x`, `feature_y`, `nearest_x`, `nearest_y`). It should be easy to produce a layer from those columns. Therefore I don't see any reason put any more effort in such an algorithm.

**Comment by roya0045** [comment]
@root676 You're right, that should be sufficient. I was confused since I could find the alg in my setup. I'm using mainly 3.4 but by looking at the code I noticed that the copyright was 2017 and the doc stated native join by attribute algorythm. But I still thought it should be in 3.4, which is not the case by looking at the history of the file.

I think I'll update my QGIS finally and I think it would be a good tweak to update the header and doc of that alg to prevent confusion. :/ @nyalldawson  I guess that I will let you tweak the doc when you have 30 seconds of free time since a PR from me would be suboptimal as usual.
