### ISSUE TITLE
Core dump when using identify feature on a vector polygon

### ISSUE THREAD

**Issue by saberraz** [qgis/QGIS#36213]
See attached stacktrace.
[identify_feature.txt](https://github.com/qgis/QGIS/files/4582631/identify_feature.txt)

QGIS version | 3.13.0-Master | QGIS code revision | 0d9a15b751
-- | -- | -- | --
Compiled against Qt | 5.12.4 | Running against Qt | 5.12.4
Compiled against GDAL/OGR | 3.2.0dev-19e5e4eb15 | Running against GDAL/OGR | 3.2.0dev-19e5e4eb15
Compiled against GEOS | 3.9.0dev-CAPI-1.14.0 | Running against GEOS | 3.9.0dev-CAPI-1.14.0
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 12.0 (Ubuntu 12.0-2.pgdg19.04+1) | SpatiaLite Version | 5.0.0-beta0
QWT Version | 6.1.4 | QScintilla2 Version | 2.10.4
Compiled against PROJ | 7.1.0 | Running against PROJ | Rel. 7.1.0, August 1st, 2020
OS Version | Ubuntu 19.10 | This copy of QGIS writes debugging output.
Active python plugins | valuetool; profiletool; SRTM-Downloader; crayfish; cawdor_forestry_db; cartogram3; QuickOSM; SentinelHub; CityJSON-loader; Mergin; BASEmesh; DataPlotly; Discovery; TerrainShading; MetaSearch; processing; db_manager

**Comment by saberraz** [comment]
It is probably related to forms: core dumped happens when I try to open the form too.

**Comment by troopa81** [comment]
I manage to identify a vector polygon and open its form.

Could you provide data and/or procedure to reproduce the issue.

**Comment by rouault** [comment]
I'd say this should have been fixed per:

commit 7cb484cfc3eaae1224f4a688e044dfb6074cee35
Author: Matthias Kuhn <matthias@opengis.ch>
Date:   Wed Jun 10 17:26:13 2020 +0200

    Add safety guard
    
    Fixes a crash if a widget is configured for an inexistent field
