### ISSUE TITLE
No CRS detected on all GPKG and Raster data except SHP

### ISSUE THREAD

**Issue by lamebird** [qgis/QGIS#36211]
Hi! I've upgraded my laptop from Fedora 31 to Fedora 32 a week ago. And after that QGIS (3.12.2) stop reading CRS from my polygon and raster in my geopackage file, even tho DB Manager read it just fine.

I have to manually set every layer crs from invalid to the right CRS (in my data i use WGS84 and WGS84 UTMZone 49). I have tried using all .gpkg file and raster  that i have and none of their crs can be read on my qgis.

Funny thing is qgis read crs from shp just fine.

I have tried reinstaling, changing user profile, deleting all QGIS related file (cache, config), installing LTR (3.10.5), and installing flatpak version. but none of it works. qgis just stop reading crs.

![image](https://user-images.githubusercontent.com/19585925/81092781-57586d00-8f2b-11ea-900d-bb101a248fed.png)
As you can see, DB Manager read crs from my gpkg file just fine, but in layer panel qgis not detecting any crs, and those two data should overlap each other but they dont here because qgis not detecting any crs.

I have tried reading my data in my other laptop (Kde Neon, based on Ubuntu 18.04) with the same qgis version (3.12.2) and it reads crs just fine.

**Comment by nyalldawson** [comment]
How did you install qgis?

**Comment by lamebird** [comment]
Hi, i install it from qgis copr (dani/qgis) that listed on https://www.qgis.org/en/site/forusers/alldownloads.html#fedora
Additionally, i tried the LTR and flatpak version (both from link above) too but still get the same results

**Comment by nyalldawson** [comment]
I suspect that the cope repo hasn't yet been updated for fedora 32. This bug report should be filed against that repo, because I run fedora 32 (with a self built qgis version) and there's no issues at all....

**Comment by lamebird** [comment]
Out of curiosity, I clean installed fedora 32 in vm, then install qgis 3.12.2 from the same copr repo, and crs works fine...
![image](https://user-images.githubusercontent.com/19585925/81112362-ba0c3180-8f48-11ea-995a-8d127c632814.png)
I wonder what's wrong with my system...
Is it because I upgrade not clean install?

**Comment by nyalldawson** [comment]
Does it work if you create a new qgis user profile?

**Comment by lamebird** [comment]
it's not
![ezgif-4-45dd171749dc](https://user-images.githubusercontent.com/19585925/81118113-8209ec00-8f52-11ea-9eec-455b5d927581.gif)

**Comment by nyalldawson** [comment]
Hmmmm. The other thing to try would be to search your system for srs.db files. Where are these located?

**Comment by lamebird** [comment]
It's in /usr/share/qgis/resources/

**Comment by nyalldawson** [comment]
Is there an srs6.db file there too?

**Comment by lamebird** [comment]
It's not, and i cant find any in my system

**Comment by lamebird** [comment]
I also noticed that there is no crs boundaries of every crs that selected (i dont know what its called) in the CRS Selector window (see pict below)
![Untitled](https://user-images.githubusercontent.com/19585925/81472914-275be300-9225-11ea-930a-704e0cc59399.png)
On the left is my current system that qgis do not detect CRS. On the right is fedora 32 running on vm with qgis installed from the same copr repo but no problem with detecting crs.

**Comment by nyalldawson** [comment]
> It's not, and i cant find any in my system

That's definitely the issue. It should be included and installed with any QGIS build which uses proj version 6 or later. This is an issue in the package used to install QGIS, so I suggest you raise this with the package maintainer and see if they have any clues. Feel free to direct them here if they need further clarification!

**Comment by gioman** [comment]
Closing?

**Comment by lamebird** [comment]
Just found out Anaconda is the one who causing this.
Installing Anaconda on my vm (which the crs works fine) caused crs to broke like my system.
Thus removing it from my system solved my problem.
One question, where should i report for this problem?

**Comment by gioman** [comment]
@lamebird can we closed this?

**Comment by lamebird** [comment]
Sure! Thank You!
