### ISSUE TITLE
[Plugin Manager] The Install Experimental Plugin button is shown if there is no version available

### ISSUE THREAD

**Issue by borysiasty** [qgis/QGIS#36217]
The new *Install Experimental Plugin* is hidden if the only available version is stable. However, if there is **no** available version (a C++ plugin or no Internet connection), both buttons are visible, what doesn't look good (especially if the user disabled experimental plugins ;) )

![experimentals](https://user-images.githubusercontent.com/1000043/81103745-c759f980-8f11-11ea-8d64-a7128b95ba3a.png)

**Comment by alexbruy** [comment]
I'd say we should go even further and don't show this button if experimental plugins are not enabled.

**Comment by olivierdalang** [comment]
@borysiasty Thanks for the report, I'll look into it !
