### ISSUE TITLE
QgsVectorLayer in QGIS python console not work

### ISSUE THREAD

**Issue by scku208** [qgis/QGIS#36227]
Hi, I want to load shapefile in qgis python console to debug our plugin, but when I type:

> lyr=QgsVectorLayer(r'‪‪C:\Users\scku\Desktop\temp\HardData.shp', 'layer_name', 'ogr')
> lyr.isValid() # False

it can not be load, I notice OGR warning at log messages:
2020-05-06T11:52:15     WARNING    Cannot open ‪‪C:\Users\scku\Desktop\temp\HardData.shp.()

but I think within my plugin, load vector through  QgsVectorLayer is fine.
I also use older QGIS (2.18.25) or QGIS (3.8.1) under UBUNTU, all are fine.
any idea?

this Problem occur when I use Windows 10 with QGIS 3.10.5, 3.4, 3.12.

thanks for help.

**Comment by nyalldawson** [comment]
Try using forward slashes in your paths instead of backslash

**Comment by scku208** [comment]
@nyalldawson Thanks for the help. because of you. Finally, I found the reason... :P
I try to use python's os.path.exists to prove the path should exists in two slashes method, but... neither is ok.
> os.path.exists(r'‪‪C:\Users\scku\Desktop\temp\HardData.shp')
> False
> os.path.exists(r'‪‪C:/Users/scku/Desktop/temp/HardData.shp')
> False

I found that the reason is... I copy the path from right click the shapefile, select the content (last item), go to the "security" page in windows b/s I think path is too long to type.
The copied path will give a strange word that QGIS python console cannot see... like
r'‪C:\Users\scku\Desktop\temp\HardData.shp'   #there is a word we can not see between r' and C:
( p.s. you can copy the path above and paste to some editor, then move mouse between r' and C: )

after remove that strange word... everything goes well. :)
sorry for bother you guys... many thanks.
