### ISSUE TITLE
Vertex tool override global snapping parameters

### ISSUE THREAD

**Issue by obrix** [qgis/QGIS#36229]
The vertex tool seems to create its own local snapping parameters, overriding the global one. It might not have been an issue until now but the feature to limit snapping to some scale range is bypassed by this behavior. This can be an issue when dealing with huge volume of data.

See https://github.com/qgis/QGIS/blob/master/src/app/vertextool/qgsvertextool.cpp#L742

To reproduce : 

* Set snapping scale limit to global and specify a min and max scale (ex : [5000, 500]).
* Edit a vector layer and use the vertex tool
* Snapping is enabled at any scale

**Comment by nyalldawson** [comment]
Isn't this required for the vertex tool to work correctly? E.g. if you've disabled snapping outside a certain range, then I think your changes will make the vertex tool completely stop operating outside of that zoom range.

**Comment by obrix** [comment]
Yes indeed this is the effect I wanted here. I can describe my use case a bit further

* I have a heavy vector layer from a distant postgis database (100 000s of features)
* A lot of features are queried from the database to rebuild the snapping index very often
* Edition of this vector layer is not practical at small scale but the snapping index is built either way, leading to freezes/long wait for the users (10 seconds to a minute some times) that are useless.

Enabling snapping (and thus snapping index rebuilding) only on a scale where drawing is relevant makes the usability better. This is coupled with the snapping strategy that limit the features used in the index to the canvas extent.

I think the user should not be surprised by snapping not working on some range scale because he/she set the parameters to limit it himself ?

**Comment by 3nids** [comment]
your arguments make sense

ping @wonder-sk thoughts on this?

**Comment by uclaros** [comment]
This is not about snapping, this is about being editable by the vertex tool. Snapping is only a means to achieve that.
This is an undocumented feature and should be mentioned (docs and tooltips) that scale dependent snapping also disables the vertex tool for the specified range.
