### ISSUE TITLE
Can't add script to processing toolbox

### ISSUE THREAD

**Issue by davidlgalt** [qgis/QGIS#36233]
When I attempt to add a script I created (any script) I get an error message like the following:

2020-05-06T03:32:10     WARNING    Could not copy script 'C:/Users/dlgal/AppData/Roaming/QGIS/QGIS3/profiles/default/processing/scripts/IsochromeByAttr.py'
             'C:/Users/dlgal/AppData/Roaming/QGIS/QGIS3/profiles/default/processing/scripts/IsochromeByAttr.py' and 'C:/Users/dlgal/AppData/Roaming/QGIS/QGIS3/profiles/default/processing/scripts\\IsochromeByAttr.py' are the same file

Yes, they are the same file! It's 2 different syntax choices (\\ vs / ) that point to the same file.

I'm using QGIS 3.12 on a Windows 10 machine.

**Comment by alexbruy** [comment]
There is no issue here. You already have script with the same name in the scripts folder, so attempt to add another one failed. Either remove existing script before re-adding it or open script in editor and adjust its code.
