### ISSUE TITLE
Provider not valid- can't add layers of different formats

### ISSUE THREAD

**Issue by wheat33** [qgis/QGIS#36248]
Dear QGIS,

QGIS 3.12. Bucuresti is unable to process bathymerty data that I would like to add. I can't drop it, can't add it as a raster layer or anything else, it shows me the attached message.  If I add a CSV file and try to interpolate it, it doesn't work at all, sowing me another error message. 

![bug](https://user-images.githubusercontent.com/64953916/81272871-5ff59400-904e-11ea-9001-3c0c3145f448.png)
![bug2](https://user-images.githubusercontent.com/64953916/81272873-61bf5780-904e-11ea-93c9-6776bc44da23.png)
![bug3](https://user-images.githubusercontent.com/64953916/81273111-b793ff80-904e-11ea-8ed7-70ed9afd1cff.png)

Thanks for the help!

**Comment by gioman** [comment]
@wheat33 hi, this is not the support facility (use the official mailing lists or gis.stackexchange instead). Anyway let's assume this is a bug report... you must attach here your problematic data (the CSV and the bathimetry layer), or at least a sample the shows the same behavior you describe.

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
