### ISSUE TITLE
WMS fails to parse capabilities in 3.12 but these load fine in 3.2

### ISSUE THREAD

**Issue by AndrewM-** [qgis/QGIS#36244]
View in 3.12.2
![2020-05-07_QGIS3-12_WMS](https://user-images.githubusercontent.com/5060805/81241193-f628ba80-904c-11ea-990b-c8fe3a75a739.jpg)

View in 3.2.3
![2020-05-07_QGIS3-2_WMS](https://user-images.githubusercontent.com/5060805/81241176-ee691600-904c-11ea-91b3-4f20398c8991.jpg)

**Describe the bug**
WMS data sources created in earlier versions of QGIS3 are not available in 3.12.2 as the WMS capabilities are not parsed.  These same WMS sources still work perfectly in earlier versions of QGIS 3.  

**How to Reproduce**
Add a WMS layer to the browser by right-clicking on the WMS icon.  Create a *new connection* and paste in the URL below.  Note that this issue seems to affect WMS data supplied by GeoSciences Australia and does not affect other WMS data sources that I have tried.

URL for WMS layer:
`http://gaservices.ga.gov.au/site_13/services/Geophysical_Grids/MapServer/WMSServer?request=GetCapabilities&service=WMS`

**Comment by nirvn** [comment]
@AndrewM- , works here on QGIS master:
![Screenshot from 2020-05-07 09-22-58](https://user-images.githubusercontent.com/1728657/81247508-65e67780-9044-11ea-862e-45146ca5e8eb.png)

Can you see if there are relevant error messages in the console panel?

**Comment by gioman** [comment]
@AndrewM- works fine also on 3.12 here

![Screenshot_20200507_095657](https://user-images.githubusercontent.com/1951107/81275130-24a49680-9049-11ea-8f4c-ff4452090bfc.png)

**Comment by AndrewM-** [comment]
WMS layers are now working on my PC and I cannot reproduce the issue or the logged messages.  The issue affected two computers, mine and my corporate PC, which is not maintained by me.  The issue may have been at the server end.  Anyway all is good now.  Thank you everyone for checking

**Comment by AndrewM-** [comment]
It seems that the issue is at the server end.  I just found another service for which _get capabilities_ is not functioning.  Perhaps as an enhancement request, we can change the error message from *failed to parse capabilities* to something like *server not found*.

http://www.ga.gov.au/gis/services/earth_science/GA_Surface_Geology_of_Australia/MapServer/WMSServer?request=GetCapabilities

2020-05-08T08:43:42     WARNING    Download of capabilities failed: Error transferring http://www.ga.gov.au/gis/services/earth_science/GA_Surface_Geology_of_Australia/MapServer/WMSServer?request=GetCapabilities&SERVICE=WMS&REQUEST=GetCapabilities - server replied: Not Found

**Comment by gioman** [comment]
> we can change the error message from _failed to parse capabilities_

@AndrewM- that is the correct message (it doesn't matter that there is no service at that URL, QGIS is a WMS/WFS/etc client so it checks if the service returns its capabilities, not if exists at all). Anyway feel free to open a feature request.
