### ISSUE TITLE
Difference function

### ISSUE THREAD

**Issue by arjunaut** [qgis/QGIS#36259]
## User Feedback

Hi I can't seem to run the 'Difference' function without crashing. it has happened on both my laptops so it's either a problem with my layers(i have tried repairing and changing to single part) or with the software. I am a new user, so sorry if I am mistaken or am using the incorrect terminology. 

## Report Details

**Crash ID**: [0ebd757578cf3b11c39bee8f1788db409284b024]('https://github.com/qgis/QGIS/search?q=0ebd757578cf3b11c39bee8f1788db409284b024&type=Issues')

**Stack Trace**
<pre>
QMetaObject::activate :
QgsFeedback::progressChanged :
QgsNativeAlgorithms::tr :
QgsDbscanClusteringAlgorithm::tags :
QgsProcessingAlgorithm::runPrepared :
QgsProcessingAlgRunnerTask::run :
PyInit__core :
QgsTask::start :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.2-A Coru�a
QGIS code revision: d4cd3cfe5a
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.3
Running against GDAL: 3.0.3

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment]
@arjunaut please attach sample data.

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.

**Comment by arjunaut** [comment]
Thanks Giovanni, and sorry for the late reply. Fine to close
    Op donderdag 28 mei 2020 21:47:05 CEST schreef Giovanni Manghi <notifications@github.com>:  
 
 


Closed #36259.
