### ISSUE TITLE
Crash when importing a geotiff file

### ISSUE THREAD

**Issue by etienneeccles** [qgis/QGIS#36250]
## User Feedback

Importing a geotiff

## Report Details

**Crash ID**: [ab15d45463addb1b44270bebaa27c1f350d1d1b6]('https://github.com/qgis/QGIS/search?q=ab15d45463addb1b44270bebaa27c1f350d1d1b6&type=Issues')

**Stack Trace**
<pre>
memcpy memcpy.asm:274
QgsRasterIdentifyResult::params :
QgsAbstractDatabaseProviderConnection::TableProperty::GeometryColumnType::operator== :
QgsSingleBandGrayRenderer::block :
QgsBrightnessContrastFilter::block :
QgsHueSaturationFilter::block :
QgsRasterResampleFilter::block :
QgsRasterProjector::block :
QgsRasterIterator::readNextRasterPartInternal :
QgsRasterDrawer::draw :
QgsRasterLayerRenderer::render :
QgsMapRendererParallelJob::renderLayerStatic :
QgsArchive::zip :
QgsImageOperation::overlayColor :
QgsMapRendererParallelJob::cancelWithoutBlocking :
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.1-A Coru�a
QGIS code revision: ef24c526da
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by gioman** [comment]
>  QGIS Version: 3.10.1-A Coru�a

@etienneeccles too old, please update. If the problem persist

1) try with a new QGIS profile
2) attach here he datasource

**Comment by etienneeccles** [comment]
Updating resolved it, thanks
