### ISSUE TITLE
QGIS ignoring sequence for SERIAL column when inserting a feature into postgres

### ISSUE THREAD

**Issue by lucamanga** [qgis/QGIS#36253]
Hello,

it's a bug that didn't occur in QGIS 2.18.

If I have a table with this column as primary key:

`   ogc_fid SERAL not NULL`

when I enable editing, I notice that QGIS never use the postgres sequence for ogc_fid, and it uses 0.
Using QGIS 2.18, it populates the field correctly with the "nextval(....)"

**Comment by lucamanga** [comment]
Sorry, I forgot: I'm using QGIS 3.10.5 LTR

**Comment by gioman** [comment]
@lucamanga does not seems to be the general case: if I import a layer in PostGIS with any of the several ways we have in QGIS I always get a serial, autoincrementing PK column.

I guess you should specify in detail how you imported the data or manually created the tabele.

**Comment by lucamanga** [comment]
@gioman I simply created the table with CREATE sql query:
`
CREATE TABLE  test
   ogc_fid SERIAL...
   CONSTRAINT ... PRIMARY KEY (ogc_fid)
`

and then I copied datas from another table with another
`
INSERT INTO   test ( fields EXCEPT ogc_fid)
SELECT FROM another ( fields like above)
`

**Comment by espinafre** [comment]
Are you talking about the DB Manager? Are you running this INSERT in the DB Manager? Adding features to your table with the map editing tools work?

**Comment by lucamanga** [comment]
I think I found a bug great as an house! 
I am closing this to open another and more descriptive bug
