### ISSUE TITLE
Problem adding WMTS from browser panel

### ISSUE THREAD

**Issue by saberraz** [qgis/QGIS#36264]
I am trying to add a layer from WMTS from Browser panel. It appears as blank.
If I add the same layer from Data Source Manage > Add WMS/WMTS layer, it appears currectly.

To replicate:
- Add http://wmts.geo.admin.ch/1.0.0/WMTSCapabilities.xml?lang=fr to your WMTS list
- Add 112 Par satellite from Browser panel (nothing appears)
- Add 112 Par satellite from Data Source Manager > Add WMS/WMTS layer. It prompts you to set the date. And it shows you the layer currectly.

**Comment by Samweli** [comment]
Hi @saberraz, I confirm this issue happens in master and also in QGIS 3.10.

**Comment by SrNetoChan** [comment]
Confirmed on 3.16 and master (3.17 RC)

**Comment by pblottiere** [comment]
Confirmed on ArchLinux with master. I'm taking a look.

**Comment by bernspi** [comment]
Still open with 3.16.6 and 3.20.0rc. When adding WMTS from Browser Panel the Parameter "&tileDimensions=" is missing. So it won't show the layer in the canvas. If adding the layer from within Panel (Menu) "Add Layer" or "Add Datasource" the Parameter "&tileDimensions=" is not missing.
