### ISSUE TITLE
Using saved style in postgres, there is strange behaviour while adding features

### ISSUE THREAD

**Issue by lucamanga** [qgis/QGIS#36260]
To reproduce:

1) create a postgres table of POINTS with a primary key as SERIAL NOT NULL
2) open it with QGIS (I'm running 3.10.5), enable editing, add point. In the new feature attributes window I see the "nextval(...)" automatically populated value at the primary key. Save all edit and toggle off the edit button
3) now, try to apply a saved style from postgres database to the QGIS layer
4) edit again and add another point: in the new feature attributes window there is no "nextval()" anymore!

**Comment by espinafre** [comment]
Hi, I've set up a test machine to try and reproduce your bug, but alas, with no success. I've created two tables, tb_teste_points and tb_teste_points2:
```sql
CREATE TABLE tb_teste_points
(
    id SERIAL NOT NULL PRIMARY KEY,
    valor character varying(32),
    geom geometry(Point,4674)
);
CREATE TABLE tb_teste_points2
(
    id SERIAL NOT NULL PRIMARY KEY,
    valor character varying(32),
    geom geometry(Point,4674)
);

```
After that, I've opened QGIS 3.10.5 on Windows, created a new project and added the database connection. First, I've added the table tb_teste_points to the project, enabled editing, added a point to it, saved. Then, I've changed its symbology and saved the style to the database: with this I've got a suitable style to try and reproduce your bug.

Now, I've loaded the table tb_teste_points2 (which is empty for the time being). I've added a point as you described (enable edit, add point, save edit, disable edit). Then, I went to properties->symbology->layer rendering->style, and selected the style that I've saved for that first table/layer.
After that, I've edited it again and added a new point, and the nextval string appeared as expected:

![image](https://user-images.githubusercontent.com/25933044/81321536-15354580-9069-11ea-9fde-e4c58dc53732.png)

Are you sure you are trying to edit the same layer, from the same table? What is your PostgreSQL version? Can you show us the CREATE TABLE for the table you are using?

**Comment by lucamanga** [comment]
I've tried on a Posgres 9.4 and 10, same issue.
I can share my data with you:

https://nc.comune.trento.it/s/YzXAYgwPLmaSdaQ

create a schema called `vigili` and restore the `table.sql`;
restore the `style.sql` that contains my styles.

I'm sure the bug is somewhat involved with styles stored in postgres.

**Comment by gioman** [comment]
> I've tried on a Posgres 9.4 and 10, same issue.
> I can share my data with you:
> 
> https://nc.comune.trento.it/s/YzXAYgwPLmaSdaQ
> 
> create a schema called `vigili` and restore the `table.sql`;
> restore the `style.sql` that contains my styles.
> 
> I'm sure the bug is somewhat involved with styles stored in postgres.

@lucamanga cannot replicate using your steps and data.

**Comment by lucamanga** [comment]
I've tried it and I successfully reproduced the bug on a local and different machine (from home).
Steps I have done:
1. install QGIS 3.12 (from official flatpak, because I have Ubuntu 18.04)
2. installed Postgres 9.4 with postgis with docker:
```docker pull mdillon/postgis:9.4```
3. started the postgres container:
```docker run -p 5432 --name postgres -e POSTGRES_PASSWORD=12345 -d mdillon/postgis:9.4-alpine```
4. detected the IP of container by:
```docker inspect postgres | fgrep \"IPAddress -m 1```
5. Opened local Pgadmin III, connected to the docker, created a new database **base**, new schema **vigili** and executed a ```CREATE EXTENSION postgis```
6. re-download the updated sql files  from https://nc.comune.trento.it/s/YzXAYgwPLmaSdaQ
7. execute these psql commands to upload the sql files to database:
```psql --file=style.sql -h 172.17.0.2 base postgres```
```psql --file=table.sql -h 172.17.0.2 base postgres```
8. load the table on QGIS 3.12
9. edit the table and try to add the point
.... do you see the "0" in the attribute table as me ? (note that the custom symbol theme is successfully loaded, the yellow points)

![immagine](https://user-images.githubusercontent.com/23235179/81666830-d3c6e080-9442-11ea-9ce7-63818a96ee1f.png)

**Comment by gioman** [comment]
> install QGIS 3.12 (from official flatpak, because I have Ubuntu 18.04)

@lucamanga unrelated to this ticket: on Ubuntu 18.04 you can use qgis.org repos, you don't need to use flatpak if you don't want to...

**Comment by gioman** [comment]
@lucamanga the style you are using, and that causes what you see, as a "range" widget applied to the OK column... if you change it to "text edit", as it should be (in my opinion) it all works as expected.

**Comment by lucamanga** [comment]
> @lucamanga the style you are using, and that causes what you see, as a "range" widget applied to the OK column... if you change it to "text edit", as it should be (in my opinion) it all works as expected.

Thank you, now it is working. Two questions:

1. will this bug be fixed?
2. in QGIS 2.18 it's working with no problems.

**Comment by gioman** [comment]
>  I tested it in QGIS 2.18, too and it is working without doing this "trick".

@lucamanga ok, but what is the use for the range widget on a field that is meant to be auto-filled?

anyway... please file a new ticket (changing title and description of this one would be too messy), I suggest to use a subject/title with something along "range widget breaks serial/nextval column".



> So, will this bug be fixed?

As usual there is no guarantee of a quick fix (but it may very well happen). If it is a blocker for you then the drill is always the same: create a patch, hire a developer, etc.

**Comment by gioman** [comment]
Closed in favor of https://github.com/qgis/QGIS/issues/36396
