### ISSUE TITLE
Some processing algorithms failing to connect to mapped network drives on windows

### ISSUE THREAD

**Issue by anthony-cooper** [qgis/QGIS#36261]
Tested with Windows 10
QGIS 3.8 and 3.12.2 - tested on clean profile.

Tested with the GDAL polygonize - anecdotal evidence from my organisation suggests this happens on some other processing, but couldn't reproduce on a couple of quick tries

If a layer has been loaded from a mapped network drive when attempting to run the algorithm fails to find the layer.
If the layer has been loaded from the original UNC path the algorithm will run successfully.

Reproduction:
- Map a network drive in windows
- Open the GDAL Polygonize tool
- Select a layer navigating via the mapped network drive

Doesn't reporduce (runs successfully) 
- Open the GDAL Polygonize tool
- Select a layer navigating via the UNC path

> Processing algorithm…
Algorithm 'Polygonize (raster to vector)' starting…
Input parameters:
{ 'BAND' : 1, 'EIGHT_CONNECTEDNESS' : False, 'FIELD' : 'DN', 'INPUT' : 'M:/XXX/XXX/Workspace/Model/TUFLOW/results/BASE/0025/004/grids/XXX_BASE___0025___004_d_Max.asc', 'OUTPUT' : 'TEMPORARY_OUTPUT' }
> GDAL command:
> python3 -m gdal_polygonize "M:/XXX/XXX/Workspace/Model/TUFLOW/results/BASE/0025/004/grids/XXX_BASE___0025___004_d_Max.asc" C:/Users/anthony.cooper/AppData/Local/Temp/processing_1220c045dd0b40c6a70af99ba2793d0a/47b74becc74a460590f5384f32f6acf3/OUTPUT.shp -b 1 -f "ESRI Shapefile" OUTPUT DN
> GDAL command output:
> ERROR 4: M:/XXX/XXX/Workspace/Model/TUFLOW/results/BASE/0025/004/grids/XXX_BASE___0025___004_d_Max.asc: No such file or directory
> Unable to open M:/XXX/XXX/Workspace/Model/TUFLOW/results/BASE/0025/004/grids/XXX_BASE___0025___004_d_Max.asc
> Execution completed in 3.90 seconds
> Results:
> {'OUTPUT': 'C:/Users/anthony.cooper/AppData/Local/Temp/processing_1220c045dd0b40c6a70af99ba2793d0a/47b74becc74a460590f5384f32f6acf3/OUTPUT.shp'}
> Loading resulting layers
> The following layers were not correctly generated.<ul><li>C:/Users/anthony.cooper/AppData/Local/Temp/processing_1220c045dd0b40c6a70af99ba2793d0a/47b74becc74a460590f5384f32f6acf3/OUTPUT.shp</li></ul>You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.

**Comment by nyalldawson** [comment]
In the log window you'll see the "GDAL command" listed. Can you compare and posting the working vs non-working commands?

The next thing to test would be to run the same command from the osgeo command line and report what changes are required to that command in order for it to work correctly with the mapped drives.

**Comment by alexbruy** [comment]
Closed for the lack of feedback. Please reopen if necessary.
