### ISSUE TITLE
QGIS Madiera - Crashed

### ISSUE THREAD

**Issue by Os14-hash** [qgis/QGIS#36287]
Please Help: it crashed 10x in a row and cannot seem to get my head around it.

Report Details

*Crash ID*: b11ef2adb8c3ce6827ae40bad5d03ca92f1e7aad

*Stack Trace*
<pre>
QTextOption::wrapMode :
QTextOption::wrapMode :
QRasterPaintEngine::drawImage :
QRasterPaintEngine::drawImage :
QPainter::drawImage :
QPainter::drawImage :
QgsSimpleMarkerSymbolLayer::renderPoint :
QgsMarkerSymbol::renderPoint :
QgsAnnotation::render :
QgsMapCanvasAnnotationItem::paint :
QGraphicsScene::dragMoveEvent :
QGraphicsScene::drawItems :
QGraphicsScene::drawItems :
QGraphicsView::paintEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QApplication::windowIcon :
QWidget::event :
QgisApp::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
QGraphicsScene::~QGraphicsScene :
QObject::event :
QGraphicsScene::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.4.4-Madeira
QGIS code revision: commit:f6ddc62fdb
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.0
Running against GDAL: 2.4.0

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362
![image](https://user-images.githubusercontent.com/65013297/81392906-a830b700-911f-11ea-8d7a-ae12ecf33038.png)

**Comment by alexbruy** [comment]
Please update to the latest version, 3.4.4 is really old.

**Comment by Os14-hash** [comment]
> Please update to the latest version, 3.4.4 is really old. Also provide extact steps to reproduce issue.

Thanks.

1. This is my version 
![image](https://user-images.githubusercontent.com/65013297/81395800-8c7bdf80-9124-11ea-8f13-e66ac21dbc51.png)

 2. Noticed that in Editing mode with Advanced digitizing tools on, I get no response with frozen screen.

**Comment by gioman** [comment]
> Noticed that in Editing mode with Advanced digitizing tools on, I get no response with frozen screen.

@Os14-hash please:

1) update to the latest 3.10 or 3.12
2) create a new QGIS profile, do not install any 3rd party plugin
3) try again and see if your issues are solved
4) if not attach a sample of data and the detailed steps that lead to the crash
5) 1 issue per ticket, if you have multiple issues file multiple tickets

thanks!

**Comment by Os14-hash** [comment]
Thanks.
It worked
