### ISSUE TITLE
QGIS 3.12 crashes when switching attribute table between docked and undocked

### ISSUE THREAD

**Issue by JoolsMLM** [qgis/QGIS#36288]
This seems to happen when table is in editable mode :

Crash ID: 5e0604c2ad6f5718ec1f917686720af222e4e7be

Stack Trace

QObject::isWidgetType :
QMainWindow::trUtf8 :
QHeaderView::logicalIndexAt :
QWidgetPrivate::inheritStyle :
QWidget::setParent :
QWidget::setParent :
QLayoutPrivate::reparentChildWidgets :
QWidget::setLayout :
QgsAttributeTableDialog::toggleDockMode qgsattributetabledialog.cpp:907
QMetaObject::activate :
QAction::setChecked :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1609
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.12.1-Bucure?ti
QGIS code revision: 121cc00ff0
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by gioman** [comment]
@JoolsMLM please try with a new QGIS profile.

**Comment by JoolsMLM** [comment]
@gioman , sorry I do not understand what you mean by a new profile. Sorry I am new to QGIS!

**Comment by Gustry** [comment]
@JoolsMLM https://docs.qgis.org/3.10/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles
Settings ‣ User Profiles ‣ New profile…

**Comment by JoolsMLM** [comment]
@Gustry 
Thank you. I have created a new profile and the error does not occur when using the new profile. So I guess that this is a problem with one of the settings in my current profile
