### ISSUE TITLE
Incomplete feature drawing should be removed when stopping edit session

### ISSUE THREAD

**Issue by gacarrillor** [qgis/QGIS#36292]
If a line or polygon layer goes to non-editing mode and there is an ongoing (never finished) drawing on canvas for that layer, the drawing should be removed.

Screencast:

![incomplete_digitized_feature](https://user-images.githubusercontent.com/652785/81415988-be824700-910e-11ea-9699-7100ca4021ba.gif)

**Comment by uclaros** [comment]
Same for other tools with a rubberband, like vertex tool, split, add ring etc.
