### ISSUE TITLE
Shortcut to open pyqgis API from QGIS console/script

### ISSUE THREAD

**Issue by ghtmtt** [qgis/QGIS#36338]
**Feature description.**
It would be extremely useful to have a dynamic link from the python console/editor to the pyqgis API website.

Right now we have auto-completion (that is great) but typing something like F1 to open the browser at the page of the class/method would be wonderful.

**Comment by nyalldawson** [comment]
I was thinking it would be great to open this in the new developer tools panel

**Comment by ghtmtt** [comment]
that would be even better!
