### ISSUE TITLE
QGIS crashes while zooming in (too far...) with Labels on.

### ISSUE THREAD

**Issue by zoltanszecsei** [qgis/QGIS#36346]
**Describe the bug**
Hi,
See points 1,2 3  etc below.
If you don't get the crash, try zooming faster.
Mine crashes at zoom level 2:1 and 4:1 (on second attempt to reproduce)

Hope this helps.
Kind regards,
Zoltan

**How to Reproduce**

1. Import 2 points with same coord value from a CSV file EPSG:4326
2. Roll mousewheel to zoom in on them, past 4:1  (see: No crash)
3. Zoom back out to a respectable level
4. Turn on labelling
5. Zoom in again, past 1:1,
3. My system caused an Uh-Oh crash at zoom scale 2:1

**QGIS and OS versions**

QGIS Info
QGIS Version: 3.12.2-Bucure?ti
QGIS code revision: 8a1fb33634
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**Additional context**

Crash ID: e1d226ea3eb384d54cf43ce719faa0b7aacf3f2d

Stack Trace

GEOSEquals_r :
pal::Layer::registerFeature layer.cpp:211
QgsLabelingEngine::processProvider qgslabelingengine.cpp:248
QgsLabelingEngine::registerLabels qgslabelingengine.cpp:287
QgsDefaultLabelingEngine::run qgslabelingengine.cpp:549
QgsMapRendererJob::drawLabeling qgsmaprendererjob.cpp:932
QgsMapRendererParallelJob::renderLabelsStatic qgsmaprendererparalleljob.cpp:399
QtConcurrent::RunFunctionTask::run qtconcurrentrunbase.h:136
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.12.2-Bucure?ti
QGIS code revision: 8a1fb33634
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by m-kuhn** [comment]
Could you attach a sample csv and project file to reproduce?

**Comment by gioman** [comment]
@zoltanszecsei also try with a new QGIS profile.

**Comment by zoltanszecsei** [comment]
Hi Mathias,
I was on the verge of putting this CSV to the list (to keep it separate from #36346).
I was zooming in on point seq=20 (and also 30) when the label crash happened.

My core issue is that when I add this ~ separated CSV to QGIS, I get only 34 features, but note:

    Feature count = 34
    Attribute table has 298 rows
    Select All shows 298 rows selected in attribute table
    Select Features (on screen after 'zoom to layer')  gets 34 items.

So I do not believe my CSV file caused the Label crash, but I am at my wits end trying to work out why the CSV file doesnt load all 298 geometries.

Thanks and regards,
Zoltan

[zoltan_DC.txt](https://github.com/qgis/QGIS/files/4615672/zoltan_DC.txt)

**Comment by gioman** [comment]
> My core issue is that when I add this ~ separated CSV to QGIS, I get only 34 features, but note:

@zoltanszecsei you must use use also the options "decimal separator is comma". If you use you'll get all your points... and still no crash here.

**Comment by zoltanszecsei** [comment]
Hi Gioman,
I did have 'decimal comma is..' set.
When I tried to upload zoltan_DC.csv it failed on unrecognised file type (csv) so I changed the file extension to 'txt'
In your comment above (..If you use you'll get all your points... and still no crash here...)  note that I have 2 issues in this bug report:  The zooming/label issue, and the "I don't get all my Points loaded" issue.
Do I start a separate bug report for the "... not all Points loaded" issue?

Here is my feedback on trying other tick-boxes.
Note that I copeid zoltan_DC.txt and renamed the copied version to '.csv'
The 'DC' in the filename is for "decimal comma"
Please see attached jpegs - and note that I now get zero Points loaded, but in all cases the attribute tables have all 298 rows.
Note too the jpeg filenames.
They show attempts on each of txt and csv versions, and each of "Detect Fields" off and on plus an attempt with minimal options ticked.
All the same results.
Hope this helps.
Regards,
Zoltan
![zoltan_DCtxt](https://user-images.githubusercontent.com/34191005/81794957-376d0e80-9514-11ea-96e4-3d0c5fed7b46.jpg)
![zoltan_DCtxtDetect](https://user-images.githubusercontent.com/34191005/81794967-39cf6880-9514-11ea-9768-7d3f1d33543f.jpg)
![zoltan_DCtxtMinOpts](https://user-images.githubusercontent.com/34191005/81794970-3b009580-9514-11ea-85c6-6e8d41e6cfcd.jpg)
![zoltan_DCversion](https://user-images.githubusercontent.com/34191005/81794975-3c31c280-9514-11ea-9b0c-1e258ad132a2.jpg)
![zoltan_DCcsv](https://user-images.githubusercontent.com/34191005/81794977-3d62ef80-9514-11ea-85d0-7eed0ab0f100.jpg)
![zoltan_DCcsvDetect](https://user-images.githubusercontent.com/34191005/81794983-3f2cb300-9514-11ea-8573-2d44f9fc454c.jpg)
![zoltan_DCcsvMinOpts](https://user-images.githubusercontent.com/34191005/81794986-405de000-9514-11ea-8435-0fc90c980915.jpg)

**Comment by gioman** [comment]
> When I tried to upload zoltan_DC.csv it failed on unrecognised file type (csv) so I changed the file extension to 'txt'

@zoltanszecsei you can attach zip files in Github

>  Do I start a separate bug report for the "... not all Points loaded" issue?

yes, 1 issue per ticket.

> Please see attached jpegs - and note that I now get zero Points loaded, but in all cases the attribute tables have all 298 rows.

you are using the "DMS coordinates" (degrees, minutes, seconds) option which is wrong, you data is in decimal degrees.

**Comment by zoltanszecsei** [comment]
@gioman:  you are using the "DMS coordinates" (degrees, minutes, seconds) option which is wrong, you data is in decimal degrees.

Oh strewth - I did not notice that.
All points loaded now - thanks for noticing that.

So this thread is remains open for the original reason: QGIS crashes with Labels 'ON' and zooming in too close. (I just tested that again)

**Comment by gioman** [comment]
> So this thread is remains open for the original reason: QGIS crashes with Labels 'ON' and zooming in too close. (I just tested that again)

@zoltanszecsei https://github.com/qgis/QGIS/issues/36346#issuecomment-626738855

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.

**Comment by zoltanszecsei** [comment]
Hi Gioman,
I totally do not understand your reason for closing this issue.
If you look at my comment (16 days ago) just before you closing this, I clearly say:
> So this thread is remains open for the original reason: QGIS crashes with Labels 'ON' and zooming in too close. **(I just tested that again)**

So I am not sure what feedback from me is still needed.

Let's look at this issue:
- It is neither urgent nor critical - it is merely a repeatable observation I made, and should you want to remove yet another unintended consequence of (perhaps stupidly) zooming in too far, then put this on the back-burner, but don't close it off saying you are waiting for me.
Hope this helps.
Zoltan.
PS: I'm neither annoyed nor offended, so please don't read any emotion in what I have just posted.

**Comment by m-kuhn** [comment]
I think the main open question is

> @zoltanszecsei also try with a new QGIS profile.

**Comment by m-kuhn** [comment]
@zoltanszecsei any chance to get a project file too (so we can test your exact configuration)?

**Comment by gioman** [comment]
>  I totally do not understand your reason for closing this issue.

@zoltanszecsei you have been asked to try with a new QGIS profile. As the issue cannot be replicated on other systems, then that test is important. No feedback for more than 15 days, ticket closed.

**Comment by zoltanszecsei** [comment]
Hi Gioman - your post above just makes us go round in circles.....
So
My guess is the reason that you cannot replicate it is because you have not turned LABELS on.
Just show the Seq attribute as a label, and roll your mousewheel to zoom in 3 or 4 clicks closer than 1:1
Hope this helps.
Regards,
Zoltan
PS:  Remember to change the .txt in this upload to .qgz
[zoomprob.txt](https://github.com/qgis/QGIS/files/4702518/zoomprob.txt)

**Comment by gioman** [comment]
>  My guess is the reason that you cannot replicate it is because you have not turned LABELS on.

@zoltanszecsei I tested with labels, as you described.

Have you tested with a new QGIS profile? this is the main question.

**Comment by zoltanszecsei** [comment]
How do I change QGIS profile?
Google not very helpful on this.
As this (profile) topic is not very obvious, and with Mathias asking for my project (qgz) file, I wondered if by profile you meant project.
(oops, sorry if I'm wrong on this)

**Comment by gioman** [comment]
> How do I change QGIS profile?

settings > user profiles > new profile

(and do not install any 3rd party plugin).

**Comment by zoltanszecsei** [comment]
Thanks.
Now with new profile (problem exists)
![newprof_UhOh](https://user-images.githubusercontent.com/34191005/83276727-bb441d80-a1d9-11ea-92e7-3d02cefec930.jpg)
[newprof.txt](https://github.com/qgis/QGIS/files/4702697/newprof.txt)

(Change txt to qgz)

**Comment by gioman** [comment]
>  Now with new profile (problem exists)

thanks, now the feeeback label can be removed and the ticket won't be closed.

**Comment by m-kuhn** [comment]
Confirmed here on master (works on 3.10 though)

**Comment by zoltanszecsei** [comment]
Nice find (#36880) , Nyall - thanks :-)
