### ISSUE TITLE
Restarter after crash needs to quote project name

### ISSUE THREAD

**Issue by Houska1** [qgis/QGIS#36348]
QGIS 3.12.2, windows 10 OSGeo4W.

QGIS crashed, got the "unexpectedly crashed? restart?" dialog. Clicked yes, QGIS could not find and load the project. Manual restart and reload of project worked, so all fine, just frightening.

Issue seems to be my project is "\bunch\of\directories\LRL map main.qgz". On the automatic restart, QGIS tried to open "\bunch\of\directories\LRL", "C:\OSGeo4W64\map.qgz" and "C:\OSGeo4W64\main.qgz". So seems the restarter fails to quote the current project filename.

This has happened before (earlier 3.X versions), this is just first time I figured out what the problem is.

(The reason for the crash was something about rebuilding indexes when turning Snap on...will try to replicate and submit separately).

**Comment by gioman** [comment]
> (The reason for the crash was something about rebuilding indexes when turning Snap on...will try to replicate and submit separately).

@Houska1 before submitting it please also try with a new QGIS profile.

**Comment by Houska1** [comment]
@gioman, will do, though right now I can't even replicate the snap-related cause on my own project with my regular profile, that's why I'm holding off on that. But this unquoted filename on restart issue seems broader, independent, and (I think) replicable.

**Comment by alexbruy** [comment]
Duplicates #25532.
