### ISSUE TITLE
Python-Error

### ISSUE THREAD

**Issue by FlyingEagle** [qgis/QGIS#36359]
Ein Fehler trat bei der Ausführung von Python-Code auf: 

RuntimeError: wrapped C/C++ object of type QgsVectorLayer has been deleted 
Traceback (most recent call last):
  File "C:/Users/%USERNAME%/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ale\advanced_line_editor.py", line 299, in currentLayerChanged
    self.currentlayer.editingStarted.disconnect(self.curLayerIsEditable)
RuntimeError: wrapped C/C++ object of type QgsVectorLayer has been deleted

Python-Version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS-Version: 3.12.1-București București, 121cc00ff0 

Python-Pfad:
C:/OSGEO4~1/apps/qgis/./python
C:/Users/%USERNAME%/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/%USERNAME%/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGEO4~1/apps/qgis/./python/plugins
C:\OSGEO4~1\apps\Python37
C:\OSGEO4~1\apps\Python37\Scripts
C:\OSGeo4W64\bin\python37.zip
C:\OSGEO4~1\apps\Python37\DLLs
C:\OSGEO4~1\apps\Python37\lib
C:\OSGeo4W64\bin
C:\OSGEO4~1\apps\Python37\lib\site-packages
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32\lib
C:\OSGEO4~1\apps\Python37\lib\site-packages\Pythonwin
C:/Users/%USERNAME%/AppData/Roaming/QGIS/QGIS3\profiles\default/python
D:\eclipse\plugins\org.python.pydev.core_7.0.3.201811082356\pysrc
C:\Users\%USERNAME%\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms
.
C:/Users/%USERNAME%/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web
C:\Users\%USERNAME%\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
C:\Users\%USERNAME%\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\shapetools\ext-libs
C:/Users/%USERNAME%/Documents/projekte

**Comment by gioman** [comment]
@FlyingEagle The error comes from a 3rd party plugin, you must report it here https://github.com/lwiniwar/ALE/issues
