### ISSUE TITLE
Bug in logical expression

### ISSUE THREAD

**Issue by Renato1978** [qgis/QGIS#36356]
In version 3.12.2 bucaresti, in selection by expression, "VALOR">="X" , the mathematical expression doesn't work.

**Comment by gioman** [comment]
@Renato1978 please provide sample data.

**Comment by andreasneumann** [comment]
hm - of what type is the column "VALOR" - AND is "X" supposed to be a number?

Note that you cannot put double quotes around a value. If it is a number, use no quote, if it is a string, then use single quotes.

Also, if VALOR is a string and you want to compare to numbers, then you might have to cast it to a numeric value.

**Comment by gioman** [comment]
> "VALOR">="X"

if you are wrapping your value X in doublequotes, you are telling QGIS that X is a column name.

If X is a numeric value (in a numeric column) then you should not use quotes or double quotes.

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
