### ISSUE TITLE
Disabled plugins during start 

### ISSUE THREAD

**Issue by jbartolop9** [qgis/QGIS#36358]
Hello Everyone!

I want report a problem when I open QGIS, appear the following message:

"Complemento DigitizingTools: Este complemento estará deshabilitado porque petó QGIS durante el último arranque. Por favor, envíe un informe y rehabilite el complemento cuando el problema se haya resuelto."

This also happen with the processing plugin.

Version that I have installed in my PC is QGIS 3.10.4 of 32 bits on Windows 10 of 64 bits, this ocurred when I installed before osgeo version in advanced mode for enable the library for edit a ESRI geodatabase. I reinstalled it, deleting prior installation archives folder but with latter install the message is permanent.

Before I had QGIS 3.4 and work very good!

I will appreciate if you could help me

Regards,

**Comment by gioman** [comment]
@jbartolop9 go in the plugin manager and enable manually those plugins.

**Comment by nyalldawson** [comment]
This UX was improved for 3.14 to help clarify the situation. We can close this now
