### ISSUE TITLE
merge vector layers: after merging field "source" has incorrect value

### ISSUE THREAD

**Issue by ehanoj** [qgis/QGIS#36375]
I have problem with QGIS 3.12.2, after merging layers is not added correct source field value from layer name but only "INPUT".

Reproduction:
1) I add GDB layers
2) I run tool "merge vector layers"
3) I select all layers, and check true "add source information"
4) RUN
5) Now, Merged layer has field "source" to fill by value "INPUT", not layer names

**Comment by gioman** [comment]
@ehanoj please attach sample data.

**Comment by ehanoj** [comment]
GDB has 1 GB. But same problem produce 2 "scratch temporary layers" (see also attached screenshot):

1. Add layer/add/new scratch temporary layers, type point, add point
2. I run tool "merge vector layers"
3. I select all layers, and check true "add source information"
4. RUN
5. Now, Merged layer has field "source" to fill by value "INPUT", not layer names

BTW:  Merging ESRI Shapefile layers is not afftected.

![Untitled](https://user-images.githubusercontent.com/22144733/81702520-ad696b00-946b-11ea-8a03-3623908db955.png)

**Comment by nyalldawson** [comment]
Please use the native processing "merge vector layers" tool and not the one from the SAGA provider.

**Comment by gioman** [comment]
> Please use the native processing "merge vector layers" tool and not the one from the SAGA provider.

@nyalldawson good catch. I think we can close this as we don't have any way to change SAGA's tools behavior.

**Comment by nyalldawson** [comment]
I've got to admit - this had me completely confused for a long time!! 😁

**Comment by ehanoj** [comment]
Thanks for clear it. 
I do not also know, that it is SAGA script. Name of script is same, GUI is same as internal script. This is very unclear and will made mistakes.

**Comment by nyalldawson** [comment]
In QGIS 3.14 the saga results are shown in toned down grey text, as a way of visually pushing users away from them.

I'll also tag this algorithm as having known issues in order to further caution users against its use.
