### ISSUE TITLE
[modeler] r.cost named outputs are not passed as input to following algs

### ISSUE THREAD

**Issue by luipir** [qgis/QGIS#36379]
**Describe the bug**
In modeler if r.cost output is set with a named output (as in the attached model), the ouptut is not passed as input to the following alg.
If named ouput is removed, then the temporary ouput is correctly passed to the next alg.

**How to Reproduce**

1. Run the attached alg => "Could not load source layer for INPUT_RASTER: invalid value"
because INPUT_RASTER is empty:
Running Reclassify by table [2/2]
Input Parameters:
{ DATA_TYPE: 1, INPUT_RASTER: '', NODATA_FOR_MISSING: False, NO_DATA: -9999, OUTPUT: 'TEMPORARY_OUTPUT', RANGE_BOUNDARIES: 1, RASTER_BAND: 1, TABLE: [0,1000,0,1000,10000,1] }

2. remove "cumulative_cost" out variable from model and run again successfully

**QGIS and OS versions**

QGIS version | 3.13.0-Master | QGIS code revision | 1435076d2f
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 12.2 (Ubuntu 12.2-2.pgdg18.04+1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Ubuntu 18.04.4 LTS | This copy of QGIS writes debugging output.
Active python plugins | processing_whitebox; plugin_reloader; processing_taudem; quick_map_services; galiciasustentable; SpreadsheetLayers; firstaid; IPyConsole; qconsolidate; excel_sync; db_manager; processing; MetaSearch

**Additional context**
Need at last merge o https://github.com/qgis/QGIS/pull/36371 before to allow use grass output algs in modeler

**Comment by luipir** [comment]
[test_r_cost.zip](https://github.com/qgis/QGIS/files/4618307/test_r_cost.zip)
 I forgot to attach the example model

**Comment by luipir** [comment]
r.cost ouptut are set as: QgsProcessingParameterRasterDestination in r.cost.txt
Any available input is searched among QgsProcessingOutputDefinition types as in:
https://github.com/qgis/QGIS/blob/master/src/core/processing/models/qgsprocessingmodelalgorithm.cpp#L884
@nyalldawson @alexbruy  What would be the best fix, add another elements in sources list or just derivate QgsProcessingParameter*Destination also from QgsProcessingOutputDefinition ?
Why a ParameterDestination is not also a OutputDefinition? I'm missing some step?

**Comment by nyalldawson** [comment]
This is an issue in the grass provider -- it's incorrectly just returning the parameter value for the OUTPUT parameter, when it should be returning the path to the file it actually generated.

**Comment by luipir** [comment]
tnx

**Comment by asierrl** [comment]
I found the same issue with r.null. When used within the graphical modeler, its output name is correctly pased to the GDAL raster calculator only if the output is not named. When I name the output the entry parameters for the GDAL:rastercalculator show an empty input A, as Input A: " ".
I'm working with a QGIS 3.16.0-1, GRASS 7.8.3-1  and GDAL library 3.1.4rc2-1, on windows 10 Education (64 bits), version 1909.

**Comment by gioman** [comment]
> I found the same issue with r.null. When used within the graphical modeler, its output name is correctly pased to the GDAL raster calculator only if the output is not named. When I name the output the entry parameters for the GDAL:rastercalculator show an empty input A, as Input A: " ".
> I'm working with a QGIS 3.16.0-1, GRASS 7.8.3-1 and GDAL library 3.1.4rc2-1, on windows 10 Education (64 bits), version 1909.

@asierrl attach the model

**Comment by asierrl** [comment]
Sorry, I didn't know even how to do it. Is a Zip file OK?
This is the final version, but the issue appeared at a middle point of the development, when the model was much simpler. And it happens with any of the two instances of r.null it contains.

[ContarCalasProbaQGIS6.zip](https://github.com/qgis/QGIS/files/5621907/ContarCalasProbaQGIS6.zip)

**Comment by gioman** [comment]
> This is the final version, but the issue appeared at a middle point of the development, when the model was much simpler. And it happens with any of the two instances of r.null it contains.

@asierrl can you kindly provide also some sample input data?

**Comment by asierrl** [comment]
Sure, @gioman, this is the trial dataset I've been using to test the model.

[CalasClasif.zip](https://github.com/qgis/QGIS/files/5622580/CalasClasif.zip)

**Comment by gioman** [comment]
> Sure, @gioman, this is the trial dataset I've been using to test the model.
> 
> [CalasClasif.zip](https://github.com/qgis/QGIS/files/5622580/CalasClasif.zip)

confirmed on 3.16.1, should this be reopened? @luipir @nyalldawson
