### ISSUE TITLE
[modeler] Any command with "." (e.g. grass') can't be used in expressions

### ISSUE THREAD

**Issue by luipir** [qgis/QGIS#36377]
**Describe the bug**
In modeler, if a grass algorithm is used, it's output can't be used in expression generating syntax expression error

**How to Reproduce**

1. Chosse a simple grass alg (e.g. r.cost)
2. create a model with inputs to feed the alg
3. add the grass alg and feed it with input from model
4. Add a new alg to the model having as input an expression getting ouput of previous grass alg (e.g. @r.cost_output) => expression syntax error due to "."

**QGIS and OS versions**

QGIS version | 3.13.0-Master | QGIS code revision | 1435076d2f
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 12.2 (Ubuntu 12.2-2.pgdg18.04+1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Ubuntu 18.04.4 LTS | This copy of QGIS writes debugging output.
Active python plugins | processing_whitebox; plugin_reloader; processing_taudem; quick_map_services; galiciasustentable; SpreadsheetLayers; firstaid; IPyConsole; qconsolidate; excel_sync; db_manager; processing; MetaSearch

**Comment by nyalldawson** [comment]
This will need a similar approach as what you did for the temporary filenames, applied when generating the expression context for a child algorithm

**Comment by luipir** [comment]
@nyalldawson if you missed... is't a really little little bugfix

**Comment by luipir** [comment]
@alexbruy can you give it a look?

**Comment by nyalldawson** [comment]
@luipir there's comments on the pr

**Comment by luipir** [comment]
gosh! I didn't (or I missed?) notifications  sorry... I didn't added unit test becuase there weren't any unit test for that  function, not idea why!

**Comment by luipir** [comment]
seems also '-' is not a safe characters to be used in expression :/
