### ISSUE TITLE
DB Manager Query History double click not copying query

### ISSUE THREAD

**Issue by gakrakow** [qgis/QGIS#36389]
While using DB Manager, Query History, double clicking on a previous query does not copy the query to the execute window. This is true with both sqlite/spatialite and postgresql/postgis databases.

QGS version 3.12.2 on Linux Mint version 18.3.

**Comment by Gustry** [comment]
It's working for me on QGIS 3.10.5 and master.

**Comment by gakrakow** [comment]
Hi Étienne,

Thanks for getting back.

I have been using this feature for years on previous version of QGIS. It currently works fine on QGIS 3.10.5 on Windows 10 or QGIS 3.4.6 on Linux Mint 18.3 but does not work for some reason with QGIS version 3.12.2 on Linux Mint 18.3.

Just thought the developers might want to know.

Thanks,
Greg Krakow
Biodiversity Data Manager, Wildlife Conservation
Wildlife Resources Division<http://georgiawildlife.com/>
Office: (770) 918-6411 | Mobile: (706) 621-0853


________________________________

**Comment by gioman** [comment]
> but does not work for some reason with QGIS version 3.12.2 on Linux Mint 18.3.

any chance you can test master or 3.10?
