### ISSUE TITLE
QGIS saves date time field as a date in saving vector layer fields

### ISSUE THREAD

**Issue by Samweli** [qgis/QGIS#36386]
When editing a vector layer adding a new date time field with corresponding values and saving the layer causes the date time field type to be converted to a date type.

1. Open any vector layer
2. Open it's attribute table and toggle edit mode
3. Add a new date time field using field calculator
4. Assign the new date time field with current date time (you can use now() function in the field calculator )
5. Click Ok in the field calculator.
6. Then click "Save edits" button in horizontal header of the attribute table.

See screenshot sample below 
![datetime_issue_in_qgis](https://user-images.githubusercontent.com/2663775/81747075-2b4f6580-94b0-11ea-97cc-a18d94f14134.gif)

QGIS version
3.13.0-Master
QGIS code revision
59e1dce732
Compiled against Qt
5.9.5
Running against Qt
5.9.5
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.22.0
Running against SQLite
3.22.0
PostgreSQL Client Version
10.12 (Ubuntu 10.12-0ubuntu0.18.04.1)
SpatiaLite Version
4.3.0a
QWT Version
6.1.3
QScintilla2 Version
2.10.2
Compiled against PROJ
6.3.1
Running against PROJ
Rel. 6.3.1, February 10th, 2020
OS Version
Ubuntu 18.04.4 LTS
This copy of QGIS writes debugging output.
Active python plugins
quick_map_services; 
plugin_reloader; 
timemanager; 
qgis-plugin; 
qgisnetworklogger; 
QuickOSM; 
db_manager; 
processing; 
MetaSearch

**Comment by rouault** [comment]
Whic type of vector layer is it ? A shapefile ? If so that's expected given that shapefiles only support Date, and not DateTime

**Comment by Samweli** [comment]
> Whic type of vector layer is it ? A shapefile ? If so that's expected given that shapefiles only support Date, and not DateTime

@rouault yes a shapefile, thanks.

**Comment by gioman** [comment]
> @rouault yes a shapefile, thanks.

@Samweli so this is expected, if you want to save time in a shapefile you must use a text field. Closing?

**Comment by Samweli** [comment]
ok @gioman
