### ISSUE TITLE
Raster calculator: Could not create destination file.

### ISSUE THREAD

**Issue by rafapugli** [qgis/QGIS#36380]
QGIS crashed when i was calculating a raster (NDVI) and now the raster calculator always report the following error " Raster calculator: Could not create destination file" 

I tried to change the project, but the issue persists 

Version: QGIS 3.12.1

**Comment by gioman** [comment]
@rafapugli please try with a new QGIS profile, if the problem persist please attach sample data.

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
