### ISSUE TITLE
QGIS crashes/freezes when adding a large CSV file as delimited text layer

### ISSUE THREAD

**Issue by fet760** [qgis/QGIS#36392]
Operating system: Windows 10 Pro (Version 1909)
QGIS Version: 3.12
Attaching the xlsx version of the csv file as github doesnt support csv files.
I was not having this issue until today. Started using QGIS version 3.10 (more stable) last week and this morning was working fine until noon where it started crashing when uploading this delimited text layer. I restarted my pc, nothing, unistalled version 3.10 and installed version 3.12 but the problem persisted. Thanks for any type of help in advance.
[ATT.xlsx](https://github.com/qgis/QGIS/files/4619070/ATT.xlsx)

**Comment by gioman** [comment]
>  Attaching the xlsx version of the csv file as github doesnt support csv files.

@fet760 just ZIP your CSV and attach it here (github takes ZIPs).

**Comment by gioman** [comment]
@fet760 also try with a new QGIS profile.

**Comment by fet760** [comment]
By new QGIS profile do you mean new project? If so, I have done that
multiple times starting from scratch, everything goes well until that point
where it crashes.

**Comment by gioman** [comment]
@fet760 settings > user profiles > new profile

**Comment by fet760** [comment]
[image: image.png]Tried using profile Fet760 and TEST123, both profiles had
the same issue.

**Comment by gioman** [comment]
@fet760 please attach the original CSV file (as zip).

**Comment by fet760** [comment]
[ATT CSV.zip](https://github.com/qgis/QGIS/files/4622393/ATT.CSV.zip)

**Comment by gioman** [comment]
> [ATT CSV.zip](https://github.com/qgis/QGIS/files/4622393/ATT.CSV.zip)

in my case it causes a freeze rather than a crash, but... the CSV is mostly made of empty cells (of about 1 million lines only ~300 contain data). If you isolate the lines with data it opens with no issues. Now it must e seen if the problem are the empty lines or if is a more general issue with CSVs with so many (empty or not) lines.

**Comment by fet760** [comment]
could you guide me on how to isolate the lines with data.

**Comment by gioman** [comment]
> could you guide me on how to isolate the lines with data.

open the CSV in a robust text editor (not notepad, if you are on Windows use Notepad++) select the lines with data, copy and paste in a new text file with .csv extension.

**Comment by fet760** [comment]
I selected all the blank cells and deleted them. The file went from 11MB to 27KB. It works now. Thanks for your time and help sir hope you have a great rest of the day.

**Comment by gioman** [comment]
Reopening as the issue remains.

**Comment by pocwiard** [comment]
Same thing happens in 3.18, opening the attribute table for large point layer (few millions points) freezes and never finishes. 
PC: i9 with 64GB
Is there a work around it?
I need to add three attributes and re-export as SCV. 
thanks

**Comment by gioman** [comment]
>  Is there a work around it?

@pocwiard try QGIS master, I think there has been a fix recently (but I may be wrong).

**Comment by pocwiard** [comment]
@gioman thanks. I tried to locate how to download the master but I failed miserably. Is there an easy way to download the master?

**Comment by gioman** [comment]
> @gioman thanks. I tried to locate how to download the master but I failed miserably. Is there an easy way to download the master?

@pocwiard try here https://qgis.org/downloads/weekly/

**Comment by pocwiard** [comment]
@gioman thank you very much!
