### ISSUE TITLE
QGIS Server: WFS Request does not use SrsName on the geometry

### ISSUE THREAD

**Issue by ismailsunni** [qgis/QGIS#36398]
**Describe the bug**

I wanted to do GetFeature request using WITHIN. This is the request:
```
<GetFeature xmlns="http://www.opengis.net/wfs" service="WFS" version="1.1.0" outputFormat="GML2" maxFeatures="1000" xsi:schemaLocation="http://www.opengis.net/wfs http://schemas.opengis.net/wfs/1.1.0/wfs.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Query typeName="mosque" srsName="EPSG:4326" xmlns:feature="http://www.qgis.org/gml">
        <Filter xmlns="http://www.opengis.net/ogc">
            <Within>
                <PropertyName>geometry</PropertyName>
                <Polygon xmlns="http://www.opengis.net/gml" srsName="EPSG:4326">
                    <exterior>
                        <LinearRing srsName="EPSG:4326">
                            <posList srsDimension="2">
                        		110 -8
                        		111 -8
                        		111 -7
                        		110 -7
                        		110 -8
                        		</posList>
                        </LinearRing>
                    </exterior>
                </Polygon>
            </Within>
        </Filter>
    </Query>
</GetFeature>
```

it works fine.

But, when I changed the srsName to 21781 (I reproject the points also), like this:

```
<GetFeature xmlns="http://www.opengis.net/wfs" service="WFS" version="1.1.0" outputFormat="GML2" maxFeatures="1000" xsi:schemaLocation="http://www.opengis.net/wfs http://schemas.opengis.net/wfs/1.1.0/wfs.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Query typeName="mosque" srsName="EPSG:21781" xmlns:feature="http://www.qgis.org/gml">
        <Filter xmlns="http://www.opengis.net/ogc">
            <Within>
                <PropertyName>geometry</PropertyName>
                <Polygon xmlns="http://www.opengis.net/gml" srsName="EPSG:21781">
                    <exterior>
                        <LinearRing srsName="EPSG:21781">
                            <posList srsDimension="2">532546 157825 532546 153725 541046 153725 541046 157825 532546 157825</posList>
                        </LinearRing>
                    </exterior>
                </Polygon>
            </Within>
        </Filter>
    </Query>
</GetFeature>
```

It doesn't give me the same result. It gives me:
```
<wfs:FeatureCollection xmlns:wfs="http://www.opengis.net/wfs" xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml" xmlns:ows="http://www.opengis.net/ows" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:qgs="http://www.qgis.org/gml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wfs http://schemas.opengis.net/wfs/1.0.0/wfs.xsd http://www.qgis.org/gml http://localhost:8010/ogc/project?SERVICE=WFS&amp;VERSION=1.1.0&amp;REQUEST=DescribeFeatureType&amp;TYPENAME=mosque&amp;OUTPUTFORMAT=text/xml; subtype%3Dgml/2.1.2">
    <gml:boundedBy>
        <gml:Box srsName="EPSG:4326">
            <gml:coordinates cs="," ts=" ">110.38061696,-7.77314969 110.38061696,-7.77314969</gml:coordinates>
        </gml:Box>
    </gml:boundedBy>
</wfs:FeatureCollection>
```

But, if I change the `srsNme` for the `LinearRing` to 4326 **without** reproject the point, it gives me the expected result.

I have tested with several dataset (gpkg, shp), and the behaviour still the same. It seems QGIS Server didn't consider the srsName for the geometry, but assume directly 4326. Perhaps in the parse request function.

I tried to make a unit test on QGIS, but it seems there is no unit test for WFS capabilities (there is for WMS capabilities). 

**How to Reproduce**

- Setup a simple project
- Serve it on QGIS Server (I use docker image)
- Test with the Request above

**QGIS and OS versions**

I have tested this using two docker images from [Camptocamp](https://hub.docker.com/r/camptocamp/qgis-server) (master) and [openquake](https://hub.docker.com/r/openquake/qgis-server) (QGIS 3.10.4-A Coruña 'A Coruña').

**Additional context**

Having no experience on the QGIS Server and little on CMake, I tried to mimic how the WMS unit test work for WFS, but so far I got 90 CMake-related errors :) )

**Comment by elpaso** [comment]
@ismailsunni if you want to help with providing a failing test I think you can put it in https://github.com/qgis/QGIS/blob/master/tests/src/python/test_qgsserver_wfs.py

**Comment by ismailsunni** [comment]
Thanks @elpaso for the hint, I was looking at the wrong area (C++ unit test) :v: 

I have made a PR with unit test to replicate the issue.

**Comment by elpaso** [comment]
@ismailsunni thank you for the test! I'm looking at the implementation and I see where the error is, unfortunately it's not a quick fix, I'm still looking at what is the best way to solve it.

**Comment by elpaso** [comment]
@ismailsunni I see two distinct but related problems here:

1. the gml geometry (such as in the polygon example) has a 4326 CRS but the exterior ring that defines it has a different CRS (3857), this is currently not implemented in QGIS GML parser and I'm wondering if it should be: it looks like a very wierd use case.
2. the gml geometry  (such as in the polygon example) has a CRS which is different than the CRS of the wfs query.

Case 2. seems the real bug that we should solve  with high priority here: it is probably a pretty common use case.

@rldhont , @pblottiere  I'd like to hear your opinion on these issues.
What do you think?

**Comment by elpaso** [comment]
ok, this fixes the issue at 1. and apparently all the test cases introduced by @ismailsunni  https://github.com/qgis/QGIS/pull/36926

I'm still a little concerned about issue 2. even if there is no failing test case or a bug report, I'll try to add one to see if it is a real issue.

**Comment by elpaso** [comment]
Test added, it seems we don't have an issue after all.

**Comment by rldhont** [comment]
@dmarteau I think you have the same issue in WPS

**Comment by elpaso** [comment]
@rldhont this test passes, it requests 3857 on a 4326 layer and filter using 4326 https://github.com/qgis/QGIS/pull/36926/files#diff-61a1cac6f0799a1d603fac5b80d0f5ddR347

I think the other cases are already tested (request 4326 with a 3857 filter).

But if you think I should add more tests let me know.
