### ISSUE TITLE
QGIS Reader - Analog to ArcGIS Reader

### ISSUE THREAD

**Issue by Saijin-Naib** [qgis/QGIS#36403]
**Feature description.**
I would love to see a QGIS Reader, which would be an analog to ArcGIS Reader. Important functionality of this would be a simplified/cleaned-up UI, mostly Read-Only functionality WITH markups/annotations that can be submitted, and non-locking live-update of deployed project files, so if a Reader project is republished, the clients see the changes immediately without needing to do anything other than "reload".

**Additional context**
I think a possible approach could be a new QGIS map/project format (.QZF) which contains flags that tell a QGIS installation to open it read-only, and also can carry a flag telling QGIS to load in the simplified "Reader" UI.

As for how to approach the non-locking live update thing that ArcGIS Reader does, I think they do it by loading the project file into memory at launch and releasing the lock on the file, then using ArcGIS Reader to watch the file for modifications, and the notifying the user that the file has been changed and needs to be reloaded.

**Why does this matter**
ArcGIS Reader is being deprecated alongside the ArcGIS Desktop 10.x branch, and there is no direct replacement other than ArcGIS Online. Some organizations (read: mine) rely quite heavily upon Reader for people to interact with GIS Data, and many people perform important core job duties using this tool. Having a FOSS equivalent in QGIS makes for a compelling use-case for a FOSS GIS stack, and removes one of the pain points of even upgrading to the Pro/AGOL workflow which is loss of Reader and loss of simplified on-premise data distribution.

**Comment by bvthomsen** [comment]
You can achieve most of the feature request by using the "Interface customization" dialog. It gives the administrator the tools to hide almost all of the QGIS user interface. Combine it with the use of different user profiles means you can redesign the QGIS user interface to almost nothing and assigning the two different setups to different user profiles

**Comment by Saijin-Naib** [comment]
@bvthomsen , I know how to use those features. There are other important things ArcGIS Reader does as I noted above, and with the added possible features in the proposed file format, would allow for this type of feature to work WITHOUT having to first deploy a custom UI/Profile on each and every single machine that MIGHT see that project, over-riding and changing the existing UI/Profles.

**Comment by Saijin-Naib** [comment]
There's something going on the QEPs that's related to what I'm proposing, but headed in a different direction.

https://github.com/qgis/QGIS-Enhancement-Proposals/issues/166

**Comment by andreasneumann** [comment]
With QGIS 2.x there used to be a component called "QGIS Browser", which was a bit similar to ArcCatalog. But there was a lack of investments and interest from both developers and users.

See f.e. https://docs.qgis.org/2.8/en/docs/user_manual/qgis_browser/qgis_browser.html

**Comment by Saijin-Naib** [comment]
I'm familiar with QGIS Browser. That isn't quite the same thing as ArcGIS Reader, nor what I'm asking for and wouldn't address the same user needs.

**Comment by andreasneumann** [comment]
> I'm familiar with QGIS Browser. That isn't quite the same thing as ArcGIS Reader, nor what I'm asking for and wouldn't address the same user needs.

Yes, I know. I just wanted to point out that any such new application will need proper backing (time wise, financially) and a large enough user base willing to invest into it, in order not to follow the same fate that QGIS browser had.

And maybe there is a way with a custom GUI and a starter script that doesn't require a separate application. It might be more future proof.

I'm not denying there is demand for such a tool, but it seems worthwhile to brainstorm different ways to achieve what you want.

**Comment by Saijin-Naib** [comment]
Ah, okay. I didn't read your intent.

Agreed, and that's why I was proposing a wrapper file-format with internal handling within QGIS to change it's appearance only, not a different application with all of that's maintenance burden.

Absolutely, and I appreciate that.

For context, I work professionally for a small/local govt. organization, and there is potential interest in QGIS/FOSS stack for our GIS and other needs, but having a Reader-like tool which **_many_** rely upon and use is critical to even trialing beyond a few people.

To that end, I'm making a custom UI/Profile as suggested by @bvthomsen above since it is trivial to get access/permission to pre-load my config on the machine in question to test, but that doesn't scale well and doesn't address a large benefit to other ways of handling the project files.

**Comment by bvthomsen** [comment]
One of the mantras for open-source is: Don't reinvent the wheel. As a member of the open-source folks I'll admit: We don't always listen to the mantra.

However I'll try to pinpoint exactly what you suggest should be done, because I'm unable to find the need for the proposed alteration.

- The read-only aspect: In the QGIS project used every layer can be marked as "read-only". And the project itself can be marked as read-only by the file system. And the DB based datasources can be read-only using UAC in the database.

- The simplified user-interface: Can be realized using customisation functions in QGIS combined with different user profiles.

- The dynamic reload: Keep the "Refresh"/F5-shortcut button visible. You can implement this even smarter by using PostgreSQL/PostGIS as your datasource: Postgres / QGIS  can implement an automatic trigger refreshing QGIS data from Postgres, when the postgres datasource is updated by other clients.

- Other specialized functions like redlining or overlap analysis on multiple layers: Develop plugins

For the record: Im am not familiar with ArcGIS reader so I might overlook some (for an ArcGIS reader user) obvious functionality.

**Comment by Saijin-Naib** [comment]
If you had experience with how ArcGIS and Reader are deployed in many organizations, you'd likely have more sympathy for why I'm asking for what I'm asking. Given the context of the push to deprecate Desktop/Reader and switch orgs. to AGOL, the time is right for a product switch for many orgs. as they'll need to re-train end-users regardless since Pro/AGOL are so incredibly divergent from the UI/UX of Desktop/Reader that adoption is incredibly difficult. A QGIS Reader-alike that doesn't require as much training, nor a complete restructure of existing infrastructure, I think is an incredible value-add and huge selling point.

-  Read-only:  
You're necessitating architecture change on the behalf of the organization that might want to switch off Reader, while how Reader handles it keeps the dangerous/low information Reader users away from making changes without requiring architecture changes (ACLs and centralized/hosted database with granular user roles). Huge barrier.

- UI:  
Again, huge barrier by necessitating that the profile be shipped/installed on every machine and not carried in the project. Not how Reader handles it.

- Dynamic Reload:  
Requiring hosted/centralized DBMS, big architecture change and barrier to entry. Also, QGIS does not release read/write locks on open projects, so I can't re-publish a project without everyone exiting their projects. Big barrier, not how Reader handles it.

- Other functions:  
QGIS has most of these, but the UX can be poor, especially for non-geospatial folks. 99% of the other people in the org. who use Reader and my products have NFI what GIS is nor do they care. They need an easy tool to consume data for their actual jobs.

**Comment by Saijin-Naib** [comment]
GIS.SE Question concerning pretty much exactly what I've discussed here.
https://gis.stackexchange.com/questions/375847/is-there-a-qgis-version-or-plug-in-for-distributing-a-qgz-project-with-a-simpl
