### ISSUE TITLE
can not start QGIS

### ISSUE THREAD

**Issue by nielsvhal** [qgis/QGIS#36409]
IMPORTANT:

Do NOT use GitHub to post any questions or support requests!
They will be closed immediately and ignored.
Questions should go to the qgis-user mailing list at https://lists.osgeo.org/mailman/listinfo/qgis-user
or other support forums such as https://gis.stackexchange.com/.

GitHub issues are for bug reports and suggestions for new features.

**Comment by nielsvhal** [comment]
Tried everything. Installed 4 times. Just need the program to work. I like Qgis a lot. 
Don't like this.

**Comment by nielsvhal** [comment]
/Applications/QGIS3.10.app/Contents/MacOS/QGIS ; exit;
ERROR 4: Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.
Warning: QWidget::insertAction: Attempt to insert null action
Warning: QWidget::insertAction: Attempt to insert null action
Warning: QWidget::insertAction: Attempt to insert null action
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x000000010a640dc0 (most recent call first):
zsh: abort      /Applications/QGIS3.10.app/Contents/MacOS/QGIS

[Proces voltooid]

**Comment by nielsvhal** [comment]
tried everything with homebrew as well.

**Comment by timlinux** [comment]
@nielsvhal please properly describe your environment and take the trouble to write a clear and informative issue, replacing the boilerplate information with the information it indicates you should include.

If you don't specifically need the LTR version please download and test this one:

https://qgis.org/downloads/macos/qgis-macos-pr.dmg

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
