### ISSUE TITLE
excel relation polygon

### ISSUE THREAD

**Issue by jiptwo** [qgis/QGIS#36407]
Hello
I use qgis 2.18.14 ... because of my client web infrastructure
Currently I have an excel main file with a column ‘’ no_code ’’ and a 2nd column ‘’ description ’’
The column "no_code" has only one code but can have types of code with a letter example: 214b
**1.**I would like to integrate this excel file into qgis 2.18.14
**2.**Except that in qgis 2.18.14… I have a polygon layer with a column ‘’ no_code ’’ and another column ‘’ description ’’
I would like ... when I enter a code or **several codes** when I create or modify a polygon ... that it automatically puts the information in my description column

Bonjour
J’utilise qgis 2.18.14 … a cause de mon infrastructure web client
Présentement j’ai un fichier princpal excel avec une colonne ‘’no_code’’ et une 2e colonne ‘’ description’’
La colonne ‘’no_code’’ a seulement un code mais peut avoir des types de code avec une lettre exemple :  214b
**1.**J’aimerais intégrer ce fichier excel dans qgis 2.18.14 
**2.**Sauf que dans qgis 2.18.14… j’ai une couche en polygone avec une colonne  ‘’no_code’’ et une autre colonne ‘’description’’
J’aimerais ... quand j’inscris un code ou **plusieurs** codes lors de ma création ou modification de polygone … qu’il met automatiquement les informations dans ma colonne description

Windows 10 Pro
QGIS 2.18.14
Plugin Lizmap 3.2 dans QGIS 2.18.14
Linux ubuntu1804
Docker 19.03.6 / postgis10.0-2.4
pgadmin4 / postgis2.5.1 / postgresql10.0
jancelin / docker-lizmap: 3.2rc6 (RC pour la version candidate)
jancelin / docker-qgis-server: 2.18LTR (LTR = Long time release)

**Comment by NyakudyaA** [comment]
You should try gis.stackexchange for these sort of questions.

**Comment by gioman** [comment]
@jiptwo QGIS 2.18 is end of line, no fixes for it (admitting you have found a bug). Please  check on QGIS 3.10/12 and if the problem persist file a new ticket.
