### ISSUE TITLE
Allow setting "OnlineResource" for QGIS server dynamically

### ISSUE THREAD

**Issue by m-kuhn** [qgis/QGIS#36425]
**Feature description.**

It would be nice to be able to set certain server variables as environment variables to have different values in development and production. For example "OnlineResource".

Probably it's most flexible if they are defined as expressions/data defined properties, so they can use environment variables through `env()` or other variables and logic.

**Comment by elpaso** [comment]
I must say that I don't like this very much. OnlineResource should be automatically calculated from the request (incoming) URL and only overridden in very particular cases. And in these cases it's probably fine if it's set in the qgs file.

But may be just me not seeing a strong use case for this feature.

I'm totally fine with making configuration properties data-defined through expressions though.

**Comment by signedav** [comment]
Thanks for your input @elpaso 

I made this implementation in the linked PR (Matthias gave me the feature request description in advance, but we thought it makes sense to have the original use case here).

Maybe you can have a look there? It implements the expression in a data-defined property for the online resource. It's up to the user to use environment variables there or not. 
There are additional ideas as well. Any inputs? Thanks.

**Comment by elpaso** [comment]
> Thanks for your input @elpaso
> 
> I made this implementation in the linked PR (Matthias gave me the feature request description in advance, but we thought it makes sense to have the original use case here).
> 
> Maybe you can have a look there? It implements the expression in a data-defined property for the online resource. It's up to the user to use environment variables there or not.

Yeah, sure, the point on accepting new features is basically that they often make the code larger, more complex and there is always a trade-off between very specific-corner use cases and what's useful for the was majority of users. Unfortunately we all miss the necessary information to take a fully informed decision.

In the server context there are additional concerns, security and information disclosure are probably the most important ones.

> There are additional ideas as well. Any inputs? Thanks.

I like the idea of DD properties. but I don't really like that an env var could implicitly alter the server configuration.

All server config is totally explicit, server config vars are fully documented and they are the only accepted input for the server.

**Comment by sbrunner** [comment]
For me, with the headers (if we are behind a reverse proxy which should be the case to have the HTTPS), with the header:
`Forwarded` (new) or `X-Forwarded-Host` and `X-Forwarded-Proto` (old)
And the `PATH_INFO` environment variable we have everything to generate it automatically...

**Comment by m-kuhn** [comment]
@sbrunner is that meant as another related feature request (to resolve these headers directly in the qgis server implementation) or a potential use case for #36427 (which allows resolving these headers with an expression)?
