### ISSUE TITLE
Unable to save changes after not following the rules for PostGIS

### ISSUE THREAD

**Issue by mere1209** [qgis/QGIS#36431]
Hi,

I have a PostGIS database connected to QGIS where I can make changes to the database. My data is a point layer and a line layer, and the endings of lines must always be snapped to a point from the point layer.

When I don´t follow the rule and try to the, QGIS tells me, that it is not possible. Then I snap the line to a point, and try to save, but then QGIS gives me this error:
      ERROR:  prepared statement "updatefeature" already exists

First when I close QGIS and open it again, I am able to save changes of existing geometries in the layer database.

It looks like QGIS has been sending an update to the database, that the database has discarded because of the rule, but the update still block for new update feature request.

I have tested it in QGIS 3.10.5 and ind QGIS 3.2.2.

**Comment by gioman** [comment]
@mere1209 hard to troubleshoot without using your specific data and database rules/triggers/etc. Can you add a sample in the form a database dump?

**Comment by mere1209** [comment]
Sorry, I don't have access to the database, but I have asked another one to make a sample.

I can see by google it, that the error is old, but people have had trouble replicate the error. I hope that the description can help someone to replicate it and find a soloution.

**Comment by gioman** [comment]
> I hope that the description

@mere1209 maybe, but if the errors depend on some specific database rule than it could be hard, this is why having a sample db is necessary.

**Comment by gioman** [comment]
Not enough infos to debug this.
