### ISSUE TITLE
Not possible to run processing script on master

### ISSUE THREAD

**Issue by Gustry** [qgis/QGIS#36436]
**Describe the bug**

It's not possible to launch a Processing script on master.
The following steps are working on 3.10.5

**How to Reproduce**

1. Processing toolbox
2. Create a new script from template
3. Launch the default script
4. Execute the script, nothing happen, nothing in the log too

**QGIS and OS versions**

Version de QGIS | 3.13.0-Master | Révision du code | 262568e6fb
-- | -- | -- | --
Compilé avec Qt | 5.12.4 | Utilisant Qt | 5.12.4
Compilé avec GDAL/OGR | 2.4.2 | Utilisé avec GDAL/OGR | 2.4.2
Compilé avec GEOS | 3.7.2-CAPI-1.11.2 | Utilisé avec GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
Version du client PostgreSQL | 12.3 (Ubuntu 12.3-1.pgdg19.10+1) | Version de SpatiaLite | 4.3.0a
Version de QWT | 6.1.4 | Version de QScintilla2 | 2.10.4
Compilé avec PROJ | 5.2.0 | Fonctionne avec PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Ubuntu 19.10 | Cette copie de QGIS dispose d'une sortie de débogage.
Extensions Python actives | processing; db_manager; MetaSearch

**Comment by nyalldawson** [comment]
Wow, this is a weird one...
