### ISSUE TITLE
 Incomplete install of 3.4 or 3.10 on Windows - desktop installer is missing

### ISSUE THREAD

**Issue by vvinckmo** [qgis/QGIS#36430]
<!--
I've tried to install 3.4 and 3.10 on my machine (Windows 10) several times . Both times shortcuts for GRASS, SAGA and OSGeo shell are created, but not QGIS itself.
The part desktop installer is missing

**Comment by gioman** [comment]
@vvinckmo the description is completely missing, so this will be closed. Add a proper description and will be reopened. Thanks!

**Comment by vvinckmo** [comment]
Installing QGIS 2.18 or the 3.4 fails. There are parts missing from the file folder such as the desktop installer
