### ISSUE TITLE
Wtyczka processing

### ISSUE THREAD

**Issue by Iza12345** [qgis/QGIS#36435]
Mam awarię z wtyczką processingu zniknela mi całkowicie i nie mogę jej zainstalować ani włączyć.

**Comment by gioman** [comment]
@Iza12345 please file this again in English. Thanks.

**Comment by Iza12345** [comment]
I have a problem with the processing plugin. He writes that there is a
failure and disappeared completely.

czw., 14 maj 2020 o 17:04 Giovanni Manghi <notifications@github.com>
napisał(a):

**Comment by gioman** [comment]
@Iza12345 please follow the template that is presented when opening a new ticket. I will paste it here for your convenience. Also please edit the title/subject to something more descriptive (and in English too):




**Describe the bug**


**How to Reproduce**



**QGIS and OS versions**



**Additional context**

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
