### ISSUE TITLE
Bug when using text buffer on labels and moving / modifying- QGIS 

### ISSUE THREAD

**Issue by simogeo** [qgis/QGIS#36440]
**Describe the bug**

Text buffer is automatically set to auxiliary_storage chosen field when moving or modifying label with labels toolbar. **This makes buffer disappear on the all displayed labels**

**How to Reproduce**

1. Open a layer 
2. Display label with text buffer and apply
3. Move / modify any  label with Label toolbar
4. Just see that all labels have no buffer anymore !
5. Reopen the label dialog and see that label buffer as a dynamic value set to auxiliary chosen field. 

**QGIS and OS versions**

QGIS version | 3.12.2-București | QGIS code revision | 8a1fb33634
-- | -- | -- | --
Compiled against Qt | 5.12.8 | Running against Qt | 5.12.8
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.2 (Ubuntu 12.2-4) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Ubuntu 20.04 LTS
Active python plugins | VectorBender; AnotherDXF2Shape; nettoyeur; mask; Qgis2threejs; GeoCoding; vector_tiles_reader; ORStools; qconsolidate3; shapetools; Hqgis; DataPlotly; french_locator_filter; SRTM-Downloader; Beeline; OSMtools; QNEAT3; db_manager; MetaSearch; processing

**Comment by gioman** [comment]
@simogeo can't replicate here following the provided steps. Can you post a screencast?

**Comment by simogeo** [comment]
mmhh, I've tried again from a new project and it did not happen ... I'll let you know if it appears again

**Comment by gioman** [comment]
Sure.
