### ISSUE TITLE
QgsAbstractDatabaseProviderConnection in PyQGIS

### ISSUE THREAD

**Issue by giswgjs** [qgis/QGIS#36457]
Following https://qgis.org/pyqgis/3.12/core/QgsAbstractDatabaseProviderConnection.html trying to use this class from the Python console is giving an error

```
>>> QgsAbstractDatabaseProviderConnection('my_postgis_connection')
Traceback (most recent call last):
  File "C:\OSGEO4~1\apps\Python37\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
TypeError: qgis._core.QgsAbstractDatabaseProviderConnection represents a C++ abstract class and cannot be instantiated
```
until 3.10 I used the code referred to in https://github.com/qgis/QGIS/issues/35654 to connect to PostGIS DBs, but this seems to be outdated.

What am I missing to connect to PostGIS DBs configured in the settings from 3.12 onwards?

**Comment by elpaso** [comment]
You access connections through data provider metadata, see: https://github.com/qgis/QGIS/blob/master/tests/src/python/test_qgsproviderconnection_postgres.py#L56
