### ISSUE TITLE
Unable to start QGIS 3.12 on Win 10 after upgrading from 3.11

### ISSUE THREAD

**Issue by cannibalflea** [qgis/QGIS#36454]
## User Feedback

After upgrading QGIS from 3.11 to 3.12, I have been unable to start the program. I have tried uninstalling everything and reinstalling it. I have tried upgrading to newer releases of 3.12, but it hasn't solved the issue.

I am using the network installer on Windows 10 x64. 

## Report Details

**Crash ID**: [4138dbbf7fd2ac49ca87962a941d43dddd3140fd](https://github.com/qgis/QGIS/search?q=4138dbbf7fd2ac49ca87962a941d43dddd3140fd&type=Issues)

**Stack Trace**
<pre>
QEventTransitionPrivate::unregister :
QAbstractItemModel::persistentIndexList :
QAbstractItemModelPrivate::rowsInserted :
QAbstractItemModel::endInsertRows :
QMetaObject::activate :
QgsDataItem::populate qgsdataitem.cpp:340
QgsDataItem::childrenCreated qgsdataitem.cpp:315
QMetaObject::activate :
QFutureWatcherBase::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QgsAuthManager::passwordHelperRead qgsauthmanager.cpp:3085
QgsAuthManager::masterPasswordInput qgsauthmanager.cpp:3221
QgsAuthManager::loadAuthenticationConfig qgsauthmanager.cpp:1207
meth_QgsAuthManager_loadAuthenticationConfig sip_corepart2.cpp:189192
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyTuple_New :
PyObject_FastCallKeywords :
PyObject_FastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_sip :
sipVH__core_198 sip_corepart0.cpp:19361
sipQgsDataItemProvider::createDataItem sip_corepart3.cpp:221420
QgsBrowserModel::addRootItems qgsbrowsermodel.cpp:142
QgsBrowserModel::initialize qgsbrowsermodel.cpp:197
QgsBrowserDockWidget::showEvent qgsbrowserdockwidget.cpp:127
QWidget::event :
QDockWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QWidgetPrivate::show_helper :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidget::setVisible :
QgisApp::QgisApp qgisapp.cpp:1444
main main.cpp:1354
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.12.2-Bucure?ti
QGIS code revision: 8a1fb33634
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by m-kuhn** [comment]
Can you delete your profile folder?

**Comment by cannibalflea** [comment]
I thought I had done that. I deleted it again and it solved the issue. Apologies for wasting your time.
