### ISSUE TITLE
Time controller for mesh 1D usability

### ISSUE THREAD

**Issue by PeterPetrik** [qgis/QGIS#36463]
1. Timestep of time slider should be equal or plural of the output time step, so not smaller
2. No data is given at the end of the simulation instead of the last output timestep.

**Comment by vcloarec** [comment]
For 1, I don't see nay solution as the temporal framework of QGIS is general for all layer.

**Comment by vcloarec** [comment]
point 2 fix by #36495

**Comment by nyalldawson** [comment]
You could consider a similar approach as is done for wmts and expose a setting to choose what to do when no dataset matches. For wmts you can pick to "snap" to the closest available time to either the start or end of the range

**Comment by PeterPetrik** [comment]
it would make a great sense to do it this way!

**Comment by vcloarec** [comment]
I finally implement two matching method that can be set in the mesh layer properties widget. See #36495
