### ISSUE TITLE
Incoherent behavior on empty Online Resource defined

### ISSUE THREAD

**Issue by signedav** [qgis/QGIS#36461]
**Describe the bug**

When Online Resource is empty on a WMS request we have a fallback and receive the service URL back:
```
<OnlineResource xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="http://qgis.demo/cgi-bin/qgis_mapserv.fcgi?MAP=/home/david/dev/qgis/QGIS_Server/tests/testdata/qgis_server/test_project.qgs" xlink:type="simple"/>
```
And on other services (like e.g. WCS) it's not returned.

![image](https://user-images.githubusercontent.com/28384354/82026270-d455b600-9692-11ea-8ca2-c9727ded3eb8.png)

**How to Reproduce**

Make WCS or WFS request without any Online Resource definition.

**Tested on current master, but the implementation with the fallback has been here since 3.0**

**Comment by signedav** [comment]
Since it's not a bug in the code but mainly an incoherence I don't know what is the best to do. 

Question is, should there be a fallback on any service request? Then we could append this information to the placeholder text in the property GUI.

**Comment by signedav** [comment]
Maybe you remember the thoughts back then when it has been implemented 9d9e94e6b963b7de53460e37a3e72161d1170679 @sbrunner?
It says it's mandatory (possibly only mandatory in WMS and that's probably why the fallback it's only implemented there).

**Comment by m-kuhn** [comment]
See also comment https://github.com/qgis/QGIS/pull/4700#issuecomment-307326136 and https://github.com/qgis/QGIS/pull/4700#issuecomment-307371085 ( CC @rldhont )

**Comment by Pedro-Murteira** [comment]
@signedav Is this issue still valid on recent versions?
