### ISSUE TITLE
GPKG (and spatialite) DB-level unique constraints are not supported by OGR (and spatialite) provider

### ISSUE THREAD

**Issue by elpaso** [qgis/QGIS#36468]
Create a GPKG with a column having a UNIQUE constraint, QGIS does not recognize the constraint.

**Comment by elpaso** [comment]
Same with spatialite

**Comment by rouault** [comment]
For the OGR side, the cleanest implementation would be to extend the OGR abstraction similarly to what exists for not null or default values to report the unique constraint, and implement it in the OGR GPKG driver.
A more hacky would be to introduce GPKG specific logic in the OGR provider.

**Comment by elpaso** [comment]
@rouault I might try the GDAL way if you could give me some guidance, or leave it to you of course :)

**Comment by elpaso** [comment]
@rouault for now I'm preparing failing test cases and adding them to testproviderbas.py.

**Comment by elpaso** [comment]
@rouault  around here? https://github.com/elpaso/gdal/blob/master/gdal/ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp#L813

**Comment by elpaso** [comment]
.. btw I see that there is a `IsNullable` / `SetNullable` but what about other constraints (and in particular `UNIQUE`) ?

**Comment by rouault** [comment]
> around here? https://github.com/elpaso/gdal/blob/master/gdal/ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp#L813

I don't think this is described by the PRAGMA table_info. sqlite_master should probably be queried

> but what about other constraints (and in particular UNIQUE) ?

That's why I told that the OGR abstraction should be extended

**Comment by elpaso** [comment]
Another question, in case I add `IsUnique` `SetUnique` I guess it needs to be added for **all** supported formats and not just spatialite and gpkg, am I wrong not?

**Comment by elpaso** [comment]
> > around here? https://github.com/elpaso/gdal/blob/master/gdal/ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp#L813
> 
> I don't think this is described by the PRAGMA table_info. sqlite_master should probably be queried
> 

No, it's not. Just wanted to know if that's the file that need to be changed, but there is probably more.

> > but what about other constraints (and in particular UNIQUE) ?
> 
> That's why I told that the OGR abstraction should be extended

**Comment by rouault** [comment]
> Just wanted to know if that's the file that need to be changed

For GPKG (besides generic work to add support for the new abstraction), that should be enough

> I guess it needs to be added for **all** supported formats and not just spatialite and gpkg

not necessarily. We can support it on a few formats only to start with, and others might join after. But we should discuss a bit about the API. In particular unique constraints can be on multiple columns at the same time, so I think there should be something at the OGRFieldDefn level for constraints on a single column and something at the OGRFeatureDefn level for constraints on a set of columns. Does QGIS support constraints on a set of columns ?

**Comment by elpaso** [comment]
> > Just wanted to know if that's the file that need to be changed
> 
> For GPKG (besides generic work to add support for the new abstraction), that should be enough
> 
> > I guess it needs to be added for **all** supported formats and not just spatialite and gpkg
> 
> not necessarily. We can support it on a few formats only to start with, and others might join after. But we should discuss a bit about the API. In particular unique constraints can be on multiple columns at the same time, so I think there should be something at the OGRFieldDefn level for constraints on a single column and something at the OGRFeatureDefn level for constraints on a set of columns. 

Yeah, I've just added ALTER_UNIQUE_FLAG and OGRFieldDefn.IsUnique/SetUnique


> Does QGIS support constraints on a set of columns ?

nope.

**Comment by elpaso** [comment]
Do you have any good idea to extract UNIQUE constraints besides parsing the SQL table definition from "select sql from sqlite_master where type='table' and name='example_table'" ?

**Comment by elpaso** [comment]
My first steps into GDAL :) https://github.com/elpaso/gdal/pull/new/gpkg-unique

**Comment by rouault** [comment]
> besides parsing the SQL table definition from "select sql from sqlite_master where type='table' and name='example_table'" ?

I can't think of a better solution. Kind of annoying to have to parse the table DDL.
And that's not sufficient ... People can create unique constraints differently, by creating a unique index (that's the only way to add a unique constraint after the table has been created, and without rewriting the schema) ...
```
sqlite> create table foo(bar integer);
sqlite> CREATE UNIQUE INDEX idx ON foo(bar);
sqlite> select * from sqlite_master;
table|foo|foo|2|CREATE TABLE foo(bar integer)
index|idx|foo|3|CREATE UNIQUE INDEX idx ON foo(bar)
```
