### ISSUE TITLE
Python API cannot access field constraints with fieldConstraintsAndStrength

### ISSUE THREAD

**Issue by elpaso** [qgis/QGIS#36462]
I could not find any test for `fieldConstraintsAndStrength` so it may have been broken from the beginning, here is a test case where field index 2 is NOT NULL but whatever constraint you have you will always get `{0: 0}` as a result or an empty dict in case of no constraints.

I think the expected result should be a dictionary with the constraint type as key and the strength as value.

```python

In [8]: layer.fields()[2]
Out[8]: <QgsField: text_not_nullable (String)>

In [9]: f = layer.fields()[2]

In [10]: f.constraints()
Out[10]: <qgis._core.QgsFieldConstraints at 0x7ffee6bdb438>

In [11]: c = f.constraints()

In [12]: c.constraints()
Out[12]: <qgis._core.QgsFieldConstraints.Constraints at 0x7ffee6c11438>

In [13]: c2 = c.constraints()

In [14]: c2 & QgsFieldConstraints.ConstraintNotNull
Out[14]: <qgis._core.QgsFieldConstraints.Constraints at 0x7ffee6bdb8b8>

In [15]: bool(c2 & QgsFieldConstraints.ConstraintNotNull)
Out[15]: True

In [16]: bool(c2 & QgsFieldConstraints.ConstraintUnique)
Out[16]: False

In [17]: layer.fieldConstraintsAndStrength(2)
Out[17]: {0: 0}
```

**Comment by yinssl** [comment]
i have the same problem.

**Comment by abderrahim31** [comment]
Almost one year later, and this is still open !
I face the same problem (QGIS 3.10.10) on MacOS

**Comment by gioman** [comment]
> Almost one year later, and this is still open !

@abderrahim31 bugs do not solve themself by miracle.



>  I face the same problem (QGIS 3.10.10) on MacOS

This is outdated, you must test on the latest 3.16 or 3.18 (but probably won't make any difference if this issue is still open. Still 3.10 is EOL).

**Comment by Joonalai** [comment]
This error occurs as well on QGIS 3.18.3.
