### ISSUE TITLE
Software window not woirking properly on 1366x768 resolution

### ISSUE THREAD

**Issue by drcrescencio** [qgis/QGIS#36471]
**Describe the bug**

QGIS 3.12.2 and 3.10.5 software window is not working well when maximized/resized at resolution 1366x768 on Windows 10. No matter if i switch windows bar, try to resize window, etc. It cut the botton part (scale, etc). 
Previous versions I used (3.4+ < 3.10) do not had this problem.
It appears to force 800px (or more) vertical resolution.
This is a common resolution in places where open source software is needed.

**QGIS and OS versions**
QGIS 3.12.2 and 3.10.5
Windows 10 Pro 64bits Version 1909 Build 18363.836

**Additional context**

QGIS version
3.10.5-A Coruña
QGIS code revision
984615fe1e
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.1
Running against PROJ
Rel. 6.3.1, February 10th, 2020
OS Version
Windows 10 (10.0)
Active python plugins
batchvectorlayersaver; 
layertreeicons; 
qgis2web; 
quick_map_services; 
db_manager; 
MetaSearch; 
processing

**Comment by alexbruy** [comment]
Can not reproduce on Windows 10 with screen 1366x768 as well as on smaller screens.

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
