### ISSUE TITLE
qgs expression function

### ISSUE THREAD

**Issue by genfild** [qgis/QGIS#36482]
## User Feedback

Crash ID: b1aaf71c107e98e5b3f16223d7102d50a90d9ab9

Stack Trace

__chkstk :
QgsExpression::Functions qgsexpressionfunction.cpp:5044
QgsExpressionNodeFunction::QgsExpressionNodeFunction qgsexpressionnodeimpl.cpp:911
QgsExpressionNodeFunction::clone qgsexpressionnodeimpl.cpp:1082
QgsExpressionNodeBinaryOperator::clone qgsexpressionnodeimpl.cpp:779
QgsExpressionPrivate::QgsExpressionPrivate qgsexpressionprivate.h:44
QgsExpression::prepare qgsexpression.cpp:377
QgsProperty::prepare qgsproperty.cpp:370
QgsProperty::propertyValue qgsproperty.cpp:481
QgsProperty::value qgsproperty.cpp:512
QgsProperty::valueAsDouble qgsproperty.cpp:585
QgsAbstractPropertyCollection::valueAsDouble qgspropertycollection.cpp:62
QgsLayoutItem::applyDataDefinedSize qgslayoutitem.cpp:1061
QgsLayoutItem::attemptResize qgslayoutitem.cpp:452
QgsLayoutItem::refresh qgslayoutitem.cpp:1177
QgsLayoutItemLegend::refresh qgslayoutitemlegend.cpp:160
meth_QgsLayoutItemLegend_refresh sip_corepart0.cpp:230444

QGIS Info
QGIS Version: 3.10.5-A Coruna
QGIS code revision: 984615fe1e
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

## Report Details

**Crash ID**: [b1aaf71c107e98e5b3f16223d7102d50a90d9ab9](https://github.com/qgis/QGIS/search?q=b1aaf71c107e98e5b3f16223d7102d50a90d9ab9&type=Issues)

**Stack Trace**
<pre>
__chkstk :
QgsExpression::Functions qgsexpressionfunction.cpp:5044
QgsExpressionNodeFunction::QgsExpressionNodeFunction qgsexpressionnodeimpl.cpp:911
QgsExpressionNodeFunction::clone qgsexpressionnodeimpl.cpp:1082
QgsExpressionNodeBinaryOperator::clone qgsexpressionnodeimpl.cpp:779
QgsExpressionPrivate::QgsExpressionPrivate qgsexpressionprivate.h:44
QgsExpression::prepare qgsexpression.cpp:377
QgsProperty::prepare qgsproperty.cpp:370
QgsProperty::propertyValue qgsproperty.cpp:481
QgsProperty::value qgsproperty.cpp:512
QgsProperty::valueAsDouble qgsproperty.cpp:585
QgsAbstractPropertyCollection::valueAsDouble qgspropertycollection.cpp:62
QgsLayoutItem::applyDataDefinedSize qgslayoutitem.cpp:1061
QgsLayoutItem::attemptResize qgslayoutitem.cpp:452
QgsLayoutItem::refresh qgslayoutitem.cpp:1177
QgsLayoutItemLegend::refresh qgslayoutitemlegend.cpp:160
meth_QgsLayoutItemLegend_refresh sip_corepart0.cpp:230444
</pre>

**QGIS Info**
QGIS Version: 3.10.5-A Coruna
QGIS code revision: 984615fe1e
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by Gustry** [comment]
What was the expression? Can you replicate the issue?
You need to describe step by step how to trigger the crash.

**Comment by genfild** [comment]
I need to print an atlas. The layout contains a map and a legend, the dimensions of which vary depending on the contents of the map. Map and size do not have time to change. Therefore, I added an expression function refresh (), which caused a crash.
[data_.zip](https://github.com/qgis/QGIS/files/4638113/data_.zip)

`@qgsfunction(args='auto', group='Custom')
def getHeight(layId, itemId, feature, parent):
    layout = QgsProject.instance().layoutManager().layoutByName(layId)
    item = layout.itemById(itemId)
    #item.refresh()
    return item.rect().height()

@qgsfunction(args='auto', group='Custom')
def getTop(layId, itemId, feature, parent):
    layout = QgsProject.instance().layoutManager().layoutByName(layId)
    item = layout.itemById(itemId)
    #item.refresh()
    return item.y()`
[23_Гео_A3P.pdf](https://github.com/qgis/QGIS/files/4638102/23_._A3P.pdf)
[231_Гео_A4P.pdf](https://github.com/qgis/QGIS/files/4638103/231_._A4P.pdf)

**Comment by nyalldawson** [comment]
Not a qgis issue - it's a problem in your custom code
