### ISSUE TITLE
Rearanging in Layers Panel is broken in Qgis 3.13 on Windows 10 x64

### ISSUE THREAD

**Issue by FelisPimeja** [qgis/QGIS#36493]
Rearanging layers in Layers Panel not working properly.

When I drag a layer it will always land in the bottom of a layers list. Then an info popup appears telling me: _"New layers added from another QGIS instance"_. But the worst thing is that temporary layers content  is completly vanished after that. Here's a quick animation to illustrate the misbehavior:

![qgis layer panel bug](https://user-images.githubusercontent.com/874261/82131763-64097a80-97e1-11ea-9598-1d24d0e2255c.gif)

In Qgis 3.12.3 all is fine.
This is happening in Qgis 3.13.0-Master (OsGeo installation, clean profile / no third plugins installed) on windows 10 x64. 

QGIS version
3.13.0-Master
QGIS code revision
02df2577c8
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.2.0dev
Running against GDAL/OGR
3.2.0dev
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
7.1.0
Running against PROJ
Rel. 7.1.0, August 1st, 2020
OS Version
Windows 10 (10.0)
This copy of QGIS writes debugging output.

**Comment by nyalldawson** [comment]
This was fixed yesterday

**Comment by FelisPimeja** [comment]
So, I'm late. Cool!
