### ISSUE TITLE
when printing atlas the map and legend do not have time to update

### ISSUE THREAD

**Issue by genfild** [qgis/QGIS#36490]
I need to print an atlas. The layout contains a map and a legend, the dimensions of which vary depending on the contents of the map. Map and size do not have time to change. 

[23_Гео_A3P.pdf](https://github.com/qgis/QGIS/files/4638102/23_._A3P.pdf)
[231_Гео_A4P.pdf](https://github.com/qgis/QGIS/files/4638103/231_._A4P.pdf)
[data_.zip](https://github.com/qgis/QGIS/files/4638113/data_.zip)

**Comment by gioman** [comment]
@genfild is this a question or a bug report?

**Comment by genfild** [comment]
Сообщение об ошибке. При печати атласа не успевают обновляться карта и легенда.

**Comment by gioman** [comment]
> The error message. When printing the atlas, the map and legend do not have time to update.

@genfild 
can you please update the subject in order to be more descriptive and also change the description with all the requested infos?

Thanks



**Describe the bug**


**How to Reproduce**



**QGIS and OS versions**



**Additional context**

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
