### ISSUE TITLE
Unable to reorder layers in layer toolbar - 3.13 nightly

### ISSUE THREAD

**Issue by mtb-za** [qgis/QGIS#36497]
**Describe the bug**
Attempting to reorder the layers in the main window's layer panel fails with the message `New layers added from another QGIS instance` and the moved layer is moved to the bottom of the list instead of where it is intended.

**How to Reproduce**

Using 3.13

Once more than one layer is added, try and move a layer. It will move to the end, rather than the desired location with the above error message.

[Screen capture of bugged behaviour](https://imgur.com/a/ucwY5I4)

This seems to happen regardless of the type of layer (tested with a mix of raster and point datasets so far). New profile does not affect the result.

**QGIS and OS versions**

QGIS version | 3.13.0-Master | QGIS code revision | 02df2577c8
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.2.0dev | Running against GDAL/OGR | 3.2.0dev
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 7.1.0 | Running against PROJ | Rel. 7.1.0, August 1st, 2020
OS Version | Windows 10 (10.0) | This copy of QGIS writes debugging output.
Active python plugins | quick_map_services; db_manager; MetaSearch; processing

**Additional context**

**Comment by Gustry** [comment]
It has been already reported and already fixed : https://github.com/qgis/QGIS/issues/36493
