### ISSUE TITLE
Pan Map (hand) blocked

### ISSUE THREAD

**Issue by Corindon** [qgis/QGIS#36507]
In QGIS is 3.12.2. 
When I go from (1) a pdf document where I have been using the "pan" option to navigate (hand), to (2) my open qgis project, the pan tool get stocked as if I was "grabbing" the map and cannot deactivate it. Need to restart QGis to solve the issue.

**Comment by gioman** [comment]
@Corindon please try with a new QGIS profile, no 3rd party plugins installed. If the issue persist please attach a sample project with data and detailed steps to replicate.

**Comment by Corindon** [comment]
thank you for your suggestion @gioman 
Did not manage to replicate the bug with a new QGIS profile. 
Looks like it may be a problem from one of the pluggins. 
Will try to define from which pluggin the problem comes from and reopen a thread..

**Comment by Corindon** [comment]
Update: the problems seems to be using the space bar to activate the pan view. But cannot dsicard it is realted to pluggins,
