### ISSUE TITLE
WCS DescribeCoverage response origin always empty

### ISSUE THREAD

**Issue by AEMPhil** [qgis/QGIS#36504]
When publishing a WCS services with QGIS Server, the "origin" element in the RectifiedGrid node of the spatial domain of a coverage in the DescribeCoverage response appears to always be empty.
In all my attempts, it renders as:
`<gml:origin/>`
It should instead contain a position element, like:
```
<gml:origin>
   <gml:pos>0 0</gml:pos>
</gml:origin>
```
I believe I found the culprit: the position element is never added into the origin element before the latter is added into the response; see source https://github.com/qgis/QGIS/blob/8a7feeddbb8ce3b0b85fc71101c718e4586db1d4/src/server/services/wcs/qgswcsutils.cpp#L164

The fix is likely to add:
`originElem.appendChild( originPosElem );`
between lines 163 and 164

Environment: QGIS Server 3.12 on Ubuntu 19.10

**Comment by gioman** [comment]
> The fix is likely to add:

@AEMPhil could you kindly submit a pull request with this patch?

**Comment by AEMPhil** [comment]
As soon as I find time to get a development environment setup, sure. I'd want to check that the patch doesn't cause other issues before submitting a PR.
I figured someone who already has an environment up and running might want to take care of it.
