### ISSUE TITLE
Missing cluster variables in formulas editor

### ISSUE THREAD

**Issue by rbonnefoi** [qgis/QGIS#36518]
Hi all,

I am under v3.12.1 version of QGIS and I want to tune a cluster rendering. I can't find in the variable list of the formulas editor the cluster variables (at least cluster_size).

It is not showed but seems functionnal as I can use it. I think it is only a matter of display of the variable list (any wrong filter ?).

I would also like to see whether there are other useful cluster variables.

Many thanks.

Remi

**Comment by gioman** [comment]
@rbonnefoi is this a question or a bug report?

**Comment by rbonnefoi** [comment]
Hi Giovanni,

Sorry for this unclear request. In my opinion, it is a kind of regression : as you can see on this video made by Anita Graser a few years ago on 3.0 version [https://youtu.be/gNL-ZSlc4KM], the cluster variables are shown in the formulas editor, which is not the case in 3.12.1 one.
Le 18/05/2020 14:06:54, Giovanni Manghi <notifications@github.com> a écrit :
@rbonnefoi [https://github.com/rbonnefoi] is this a question or a bug report?

**Comment by gioman** [comment]
@rbonnefoi would you mind adding all the requested details asked in the bug report template? Thanks!



**Describe the bug**


**How to Reproduce**



**QGIS and OS versions**



**Additional context**

**Comment by alexbruy** [comment]
They are not missed. Look under "Variables" group, all variables now there and not a top-level items.
