### ISSUE TITLE
Define max/min values in histogram graphics not work

### ISSUE THREAD

**Issue by diogocaribe** [qgis/QGIS#36522]
**Describe the bug**

**How to Reproduce**

1. Add raster layer avaiable in: https://drive.google.com/open?id=1wtGeEigmKNd5EPJjVv37JzgbdXcxNgaF
2. Go to Proprieties of rater layer added
3. Go to Transparency 
4. Set No Data Value in Additional no data value as 0
![Screenshot from 2020-05-18 10-21-54](https://user-images.githubusercontent.com/7991205/82217854-69ee8100-98f1-11ea-8789-da248bcc52ad.png)
5. Go to Histogram >> Press Compute Histogram
6. Change value max and min with botton hand:
![Screenshot from 2020-05-18 10-26-04](https://user-images.githubusercontent.com/7991205/82218261-031d9780-98f2-11ea-9834-43e07a2194e9.png)
6. Press Apply and OK botton:
7. Nothing happened with contrast layer.
8. Open Proprieties again
    The values from max and min of band 1 layer not what set in step 6
![Screenshot from 2020-05-18 10-30-50](https://user-images.githubusercontent.com/7991205/82218699-ab336080-98f2-11ea-81a3-67c9f4eb7454.png)

**QGIS and OS versions**

QGIS version | 3.10.6-A Coruña 
QGIS code revision | ec80021f49
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 10.12 (Ubuntu 10.12-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Linux Mint 19.2
Active python plugins | togglegroupvisibility; imagefootprint_plugin-qgis3; SLD4raster; ee_plugin; ibamaprocessing-master; changeDataSource; toggleactivelayer_plugin; latlontools; catalogotf_plugin; DigitizingTools; processing; MetaSearch; db_manager

**Comment by gioman** [comment]
>  The values from max and min of band 1 layer not what set in step 6

@diogocaribe I don't think that the min/max values used in the histogram panel have any relation/connection to the ones used in symbology.

**Comment by diogocaribe** [comment]
@gioman The older version work when you change value in the histogram panel the symbology value follow them.

**Comment by gioman** [comment]
> @gioman The older version work when you change value in the histogram panel the symbology value follow them.

@diogocaribe ok, can you say what version?

**Comment by diogocaribe** [comment]
@gioman I'm looking for how to downgrade my qgis in order to be sure of this question. The only whae to do it is compile another version? 
By the way, I belive that 3.10.2 have this functionality working well. I'm using the LTR version 3.10 and after update the problem appeared.

**Comment by diogocaribe** [comment]
@gioman The version 3.10.5 is working well.

**Comment by diogocaribe** [comment]
> @gioman The version 3.10.5 is working well.

Yes. We test here but in Windows 10 system. Thanks a lot.

**Comment by diogocaribe** [comment]
@gioman What repository can I install qgis package to receive the solution of this error? Has nightly have this correction?
