### ISSUE TITLE
GeoPDF export: Control Layer order

### ISSUE THREAD

**Issue by davidlgalt** [qgis/QGIS#36535]
**Ability to control the order of layers as they appear in Acrobat's _Layers Navigation Pane_.**
Currently, the order of layers in Acrobat's navigation pane appears to be random--at least I have not been able to figure this out. This means that to make these PDFs understandable to my clients I need to go into Acrobat and reorder the layers after the export.

**Comment by andreasneumann** [comment]
I agree. This would be really important.

I even think it is a bug and not a feature request, but I'm not sure.

In any case, it would be very important that the layer order from the map frame is respected.

**Comment by nyalldawson** [comment]
Relates to https://github.com/qgis/QGIS/issues/34910
