### ISSUE TITLE
refactor: "." Files are not supported as outputs for this algorithm

### ISSUE THREAD

**Issue by ForestEco** [qgis/QGIS#36534]
I am trying to simply refactor an existing date field in a shape file layer which was loaded as a string datatype to refactor as a "date" datatype so I might do SQL queries with it. I keep getting this error even on copied layers using the database manager where I tried to refactor it. Other copies seemed to work where I narrowed the data down which is strange. It might not like one of the records? The source table is a shape file once more. 

I am not making the connection to this error.
"." Files are not supported as outputs for this algorithm
Why might this be happening?

![image](https://user-images.githubusercontent.com/65578840/82276748-211be400-9954-11ea-9a6a-27de1b7094c0.png)

**Comment by gioman** [comment]
@ForestEco please attach sample data.

**Comment by ForestEco** [comment]
Download this data here: **http://gis-michigan.opendata.arcgis.com/datasets/midnr::michigan-state-forest-covertype** Use a full shape dataset.

**Comment by gioman** [comment]
The "refactored" output must be left blank if you want a temporary output, otherwise you must fill it with a proper path and name. You can't just write the output name. I'm not sure if this how all Processing tools work now or if just a (small) annoyance of this specific tool.

**Comment by gioman** [comment]
> Download this data here: **http://gis-michigan.opendata.arcgis.com/datasets/midnr::michigan-state-forest-covertype** Use a full shape dataset.

by the way this layer has invalid geometries, you must fix them first with "fix geometries".

**Comment by ForestEco** [comment]
How would I correct those? Do you know of a good tutorial?

**Comment by ForestEco** [comment]
The "fix geometries" function also has a "." files error. I am still not certain about what to do.

**Comment by ForestEco** [comment]
Strange! It just worked after restarting the app randomly.

**Comment by gioman** [comment]
@ForestEco can we close?

**Comment by ForestEco** [comment]
yes
