### ISSUE TITLE
QT Designer doesn't display QGIS Widgets on 3.10.4 Docker image

### ISSUE THREAD

**Issue by ciaranevans** [qgis/QGIS#36544]
**Describe the bug**

When I run QT Designer from the `qgis/qgis:final-3_10_4_disco` image, I cannot see the QGIS Widgets.

**How to Reproduce**
```
$ xhost +
$ docker run --privileged --net=host --env="DISPLAY" qgis/qgis:final-3_10_4_disco bash -c "designer"
```

Scroll down on the left and there are no QGIS Widgets:
![image](https://user-images.githubusercontent.com/9111975/82306106-86082600-99b6-11ea-9006-abaf20459ca9.png)

---

I believe the file I need is `libqgis_customwidgets.so` but is isn't anywhere on the image:
```
$ apt-get install -y mlocate && updatedb
$ locate libqgis_customwidgets.so
# Gives no output
```

I do have:
```
/QGIS/debian/libqgis-customwidgets.install
/QGIS/debian/libqgis-customwidgets.lintian-overrides
```

But running the `/QGIS/debian/libqgis-customwidgets.install` gives:
```
/QGIS/debian/libqgis-customwidgets.install: line 1: usr/lib/*/qt?/plugins/designer/libqgis_customwidgets.so*: No such file or directory
```

**QGIS and OS versions**

Docker image: `qgis/qgis:final-3_10_4_disco`

**Additional context**

I'm hoping to use this Docker image for VS Codes Remote Containers plugin for developing QGIS plugins. I want to be able to have peers checkout the repo and have a working dev environment from the get-go, regardless of host OS'. This particular image has the QGIS + Python version that our internal IT dept have installed across all users machines so it's pretty imperative we use this one.

Many thanks! ❤️

**Comment by ciaranevans** [comment]
I've also trialled this with:
```
qgis/qgis:release-3_10_focal
qgis/qgis:final-3_10_5
qgis/qgis:release-3_12_focal
```

But still no widgets available. Is there a step I need to take?

**Comment by ciaranevans** [comment]
@3nids Apologies for the mention! Perhaps you might know what I'm missing? 😄

**Comment by 3nids** [comment]
see #36571

**Comment by ciaranevans** [comment]
> see #36571

That's great! Many thanks! 

Do you know the rough timeline of that being available? 

Really appreciate the quick addressing of it!
