### ISSUE TITLE
QGIS Temporal Button Behaviour

### ISSUE THREAD

**Issue by ismailsunni** [qgis/QGIS#36550]
1. I found this "bug" on the temporal navigation button. Basically, we can click on the play button and makes it on the unclicked state but the animation is still running. The same applies to the reverse play button. Perhaps it would be good to have the pause button activated, whenever the play or reverse play button clicked for the second time (and the animation is paused). I am not sure what's is the best/good behavior for this one.

2. The second bug, after playing animation, then I click the "turn off temporal navigation". What should the expected result? Should QGIS show all layers/features without temporal restriction or just pause the animation at that time we click the "turn off temporal navigation" button? I prefer the first one though.

I think I can make the fix, but not sure which behavior is the preferred one.

**Comment by nirvn** [comment]
If you want to pause the animation, click pause. Turning of temporal navigation shouldn't duplicate that, it's pointless.

Switching temporal navigation off should be acting as ig you'd remove a filter string on a layer. The temporal constraints / filters are gone. Just like a non-temporal layout map item.

**Comment by nirvn** [comment]
On point 1, I agree there is a UX issue. IMHO, we should always have one of the following three buttons in a pressed state: play, reverse play, pause.

**Comment by nyalldawson** [comment]
@nirvn this was fixed, right?

**Comment by ismailsunni** [comment]
confirmed fixed for point 1

**Comment by nirvn** [comment]
I think point 2 was a non issue. We can close.
