### ISSUE TITLE
Not all features of QGIS Desktop are available to me

### ISSUE THREAD

**Issue by mdnk889** [qgis/QGIS#36558]
When I click Raster from the menu, I only see the Raster calculator and align raster options. I don't get all the other features.
![image](https://user-images.githubusercontent.com/22156445/82363322-f9f70c80-9a50-11ea-8f05-24fc6ff2802f.png)

**Comment by gioman** [comment]
@mdnk889 enable the Processing toolbox in the plugin manager.

**Comment by mdnk889** [comment]
thanks a lot
