### ISSUE TITLE
Temporal WMS settings are hidden in Source tab (and requests only specify the frame start time by default)

### ISSUE THREAD

**Issue by anitagraser** [qgis/QGIS#36552]
For some temporal WMS, it is necessary to specify the time range of the frame rather than just the start time of the frame.

For example, I have a GeoServer WMS with time dimension that serves a point layer where each point has a time stamp. Using temporal control, I'd like to specify the time range of features that should be plottet, however, QGIS only sends the start time in the map request:

![qgis_temporal_wmst_request](https://user-images.githubusercontent.com/590385/82331603-a222bc00-99e4-11ea-9d95-2f83ba2c17ac.PNG)

**Comment by ismailsunni** [comment]
I got the same behavior here.

**Comment by Samweli** [comment]
Hi @anitagraser, @ismailsunni ,that is the default mode for WMS-T layers, you can customize this in the layer properties under source tab, there is an option called "Time slice mode", this defaults to "Match Start of Range", if you want to specify the time range you can change this into "Use Whole Temporal Range".

**Comment by ismailsunni** [comment]
@Samweli 
Do you mean like this:
![image](https://user-images.githubusercontent.com/1421861/82340267-545f8100-99ef-11ea-9a16-059cb96face4.png)
I tried that, but it request without TIME parameter

**Comment by anitagraser** [comment]
Ah, i see! I saw it but didn't expect that this was related. It's a bit confusing to have part of the config in the Source tab while there is a dedicated Temporal tab. Also why is it called "Use static WMS-T capabilities"?

**Comment by nirvn** [comment]
+1 to move WMS-T temporal UI into the temporal panel.

**Comment by Samweli** [comment]
> @Samweli
> Do you mean like this:
> ![image](https://user-images.githubusercontent.com/1421861/82340267-545f8100-99ef-11ea-9a16-059cb96face4.png)
> I tried that, but it request without TIME parameter

Not there @ismailsunni, like this 
![new_use_dates_only_position](https://user-images.githubusercontent.com/2663775/82341807-91c90c00-99f9-11ea-8ec1-56b90eae86bc.png)

**Comment by Samweli** [comment]
> I saw it before but didn't expect that this was related. It's a bit confusing to have part of the config in the Source tab while there is a dedicated Temporal tab

It is in a source tab because most of the WMS-T settings are specific to WMS layers only, it might be confusing for other users to see WMS specific settings while they only want to deal with layer temporal settings only.

> Also why is it called "Use static WMS-T capabilities"?

This is because the settings here include using the WMS-T capabilities to configure/update the layer's temporal state.

**Comment by Samweli** [comment]
> Another question related to this menu/dialog: on the first time I open the tab, no radio button is checked (like in your screenshot). It's strange to not have a default value. And what happened if there is no radio button selected?

You are right @ismailsunni, this is already fixed here https://github.com/qgis/QGIS/pull/36547

**Comment by ismailsunni** [comment]
No, I mean the radio button between `Use static WMS-T temporal range` and `Pass project temporal range to provider`.

**Comment by anitagraser** [comment]
>> I saw it before but didn't expect that this was related. It's a bit confusing to have part of the config in the Source tab while there is a dedicated Temporal tab
>
> It is in a source tab because most of the WMS-T settings are specific to WMS layers only, it might be confusing for other users to see WMS specific settings while they only want to deal with layer temporal settings only.

In that case, it imho would make sense to have WMS-T setting in the Temporal tab but only display them if it's a WMS-T layer. It looks quite clear from the conversation here that nobody is expecting this setting in the Source tab.

>> Also why is it called "Use static WMS-T capabilities"?
>
> This is because the settings here include using the WMS-T capabilities to configure/update the layer's temporal state.

The word "static" in this context is confusing for me. It sounds like an option that would allow me to override the server settings.

**Comment by Samweli** [comment]
> Also, is it possible to set the start and end date-time from the WMS T min and max time?

So yes and no @ismailsunni, if a WMS-T layer capabilities specifies it's dimension extent in interval, this is loaded automatically in the start and end datetime inputs in the static WMS-T settings in the layer properties, otherwise user have to specify the min and max from the capabilities.


> No, I mean the radio button between `Use static WMS-T temporal range` and `Pass project temporal range to provider`


The default state is that none of those options are used ( because the temporal range from the animation is the one used ), in order to use those options you will have to disable first the temporal properties in the "Temporal tab".

**Comment by Samweli** [comment]
> In that case, it imho would make sense to have WMS-T settings in the Temporal tab but only display them if it's a WMS-T layer. It looks quite clear from the conversation here that nobody is expecting this setting in the Source tab.

I get your point @anitagraser but having the WMS-T settings in the source tab rather temporal tab enables usage of those settings even when the temporal properties of the layer are disabled. That is you can still request for a WMS-T layer with a certain time value. If we put them in Temporal tab, it would be confusing to use them while the temporal properties are disabled.

**Comment by anitagraser** [comment]
> I get your point @anitagraser but having the WMS-T settings in the source tab rather temporal tab enables usage of those settings even when the temporal properties of the layer are disabled. 

We could have both settings groups on the Temporal tab without having them depend on each other:

![wmst](https://user-images.githubusercontent.com/590385/82354381-03f11f00-9a01-11ea-91d7-c847e696805f.png)

> If we put them in Temporal tab, it would be confusing to use them while the temporal properties are disabled.

I think having another set of temporal settings on the Source tab is more confusing.

@nyalldawson and @timlinux what do you think?

**Comment by timlinux** [comment]
@anitagraser I agree, it would be nice to have all the temporal options on one tab, two group boxes as per your mockup. I think there will still be some confusion even with them combined as the options are pretty complicated. I made this diagram once which tries to tease out the permutations:

![TemporalQGISHighLevelArchitecture](https://user-images.githubusercontent.com/178003/82381295-dbc5e800-9a21-11ea-9366-f9f219b324a3.png)

It would be great to figure out how to make all these options more digestible....

**Comment by anitagraser** [comment]
Thanks @timlinux ! Maybe you can help me understand the terminology used in these dialogs: 
Why is it necessary to enable "static WMS-T capabilities" to set the desired time slice mode?

**Comment by anitagraser** [comment]
@timlinux I just stumbled over this issue again and - since I had completely forgotten about the hidden settings - I was worried that WMS-T support is broken. Is anyone working on Temporal Controller currently?

**Comment by rduivenvoorde** [comment]
see #39994. I also think those props could be better found in the temporal tab. 
Also: I think the dropdown shows 'range' where 'frame' is meant.

**Comment by jratike80** [comment]
I agree that it does feel a bit odd that this is what the user is seeing

![image](https://user-images.githubusercontent.com/1751612/120372456-e054fa00-c31f-11eb-90ce-03c960527533.png)

and by default the "to" field does not have any function at least with WMT-T layers. Would it be possible to deactivate the field in that case?

**Comment by nyalldawson** [comment]
Please test with master/3.19. this has been reworked now.

**Comment by rduivenvoorde** [comment]
I know it is closed, but I did some trials to move around the items in the controller:
https://github.com/qgis/QGIS/pull/42548
