### ISSUE TITLE
feature specific legend in qgis

### ISSUE THREAD

**Issue by awa5114** [qgis/QGIS#36557]
It seems to me that the legend and scalebar in QGIS Atlas cannot change per feature. Is there a way to have a separate, manually tweaked scalebar and legend for each page in my Atlas? How do I do this without using some complicated qgis expression?

**Comment by gioman** [comment]
@awa5114 is this a question? a feature request?

**Comment by awa5114** [comment]
a question...

**Comment by gioman** [comment]
@awa5114 questions must be asked in the users or developers mailing list, the QGIS IRC channel or gis.stackexchange. This facility is for bug reports and feature requests. Thanks!

**Comment by awa5114** [comment]
I would argue that this is a bug also. Not being able to set legends and scalebar properties for each distinct feature in an atlas is heavily counterintuitive. It defeats the purpose of having an atlas....

**Comment by gioman** [comment]
> I would argue that this is a bug also

@awa5114 if is also a bug you must file the report as required:



**Describe the bug**


**How to Reproduce**



**QGIS and OS versions**



**Additional context**

**Comment by nyalldawson** [comment]
It's possible anyway - set data defined properties on the items. Or a blunt force approach is to make multiple different scale bars and legends in different styles, and control their visibility on a per atlas feature with a data defined visibility expression.

**Comment by awa5114** [comment]
It is possible, but its much more time consuming to do it in both of the ways you propose. Furthermore legend positioning and scalebar size are properties that belong to the layout, not the features themselves. The miscellaneous layout items like legend, scalebar, text and north arrow ought to be defined per "layout page" in an Atlas...

**Comment by awa5114** [comment]
Also, what if the item I would like to adjust per atlas page is actually a group? There doesn't seem to be any data-defined control for group positioning

**Comment by esnyder-rve** [comment]
Currently working on adding data-defined overrides for the scalebar layout item.

**Comment by esnyder-rve** [comment]
Can this feature request be re-opened?
