### ISSUE TITLE
Qgis se cuelga cuando despliego configuración ----> opciones

### ISSUE THREAD

**Issue by juanclj** [qgis/QGIS#36559]
Crash ID: 01d899d404e4a7520e4d3208f6f1bf74f973df38

Stack Trace

QString::arg :
QgsOpenClUtils::deviceId qgsopenclutils.cpp:300
QgsOpenClUtils::devices qgsopenclutils.cpp:70
::operator() qgsoptions.cpp:1153
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::setChecked :
QgsOptions::QgsOptions qgsoptions.cpp:1203
QgisApp::createOptionsDialog qgisapp.cpp:11040
QgisApp::showOptionsDialog qgisapp.cpp:11046
QgisApp::options qgisapp.cpp:10927
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1606
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.10.5-A Coru�a
QGIS code revision: 984615fe1e
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by luipir** [comment]
please:
1) write in english if possible
2) fill minimum info as requested in the form to fill an issue

Until that moment we have to close the issue to lack of minimal info to proceed.
BTW Thank's to try to report the issue.

Regards

********************
Porfa:
1) escribes en ingles si es posible
2) rellena las info que se piden en la plantilla cuando abre el report del fallo

hasta que no rellena estos datos tenemos que cerrar el fallo por falta de ls minima informaciones para seguir adelante.

De todo modo agradecemos que haya reportado el fallo

un saludo
