### ISSUE TITLE
Set source coordinate reference system for XYZ layer is not working on QGIS 3.13 Win x64

### ISSUE THREAD

**Issue by FelisPimeja** [qgis/QGIS#36562]
When I try to change CRS for XYZ layer through Properties, no transformation applies and CRS always resets to 3857.
QGIS 3.13 Win x64 clean profile? no plugins/
No problems with QGIS 3.12 Win x64
![qgis xyz layer bug](https://user-images.githubusercontent.com/874261/82387035-9a900100-9a3e-11ea-898d-d76928ba835c.gif)

**Comment by nyalldawson** [comment]
This is fixed on master already

**Comment by FelisPimeja** [comment]
It's the second time I'm late with bug report. Glad to hear!
