### ISSUE TITLE
QGIS reports "no layers" in GeoPackage when geopackage directory is write protected

### ISSUE THREAD

**Issue by bvthomsen** [qgis/QGIS#36574]
(Borderline bug  , maybe more of a feature request)

When a directory containing af GeoPackage becomes write protected, QGIS can't open the GeoPackage because it's inhibited in creating the 2 wal files in the same directory where the GeoPackage resides.  This situation is reported to the user in the relatively obscure QGIS log facility.

However, when trying to see the layers inside the GeoPackage, QGIS shows an totally empty GeoPackage - **no layers** at all.

That is **not** smart. It will upset users (It certainly did upset me :-) . They will believe, that their precious layers in the GeoPackage is destroyed. However, the layers is perfectly alright. If you copy the GeoPackage to another filesystem, QGIS will happily open the layers from the copy.

(My case involves a partly corrupted xFAT partion, which - unknowingly to me - became write protected. With the aforementioned results)

IMHO, In stead of making a discreet log entry, a better approach would be to have a big, fat error message informing users that they have a problem with the underlying file system, inhibiting QGIS in opening the package.

**Comment by elpaso** [comment]
What do you mean with "when trying to see the layers inside the GeoPackage"? 
From the browser?

**Comment by bvthomsen** [comment]
Yes, from the QGIS browser...

I navigate to the directory and click on the icon representing the geopackage file, but it doesn't "open", i.e show any of the individual tables in the GeoPackage.

However, If I copy the geopackage to another (writeable) directory, It works perfectly with the copy: Showing all the tables in the copy.  

It behaves like this because the original directory containing the GeoPackage is write protected - In my case because the xfat-based drive was partly corrupted,  making the directory read-only.

I have no beef with this behaviour. The problem is, that the error is only - very discreetly - reported using the QGIS log facility. 

I would like to have a big fat red error message telling the user, that QGIS can't open the GeoPckage because the *directory* is read-only. 

Otherwise the user can mistake the situation for a destroyed or corrupted GeoPackage, not the real error.

**Comment by elpaso** [comment]
@bvthomsen your diagnosis is correct, I checked it in a debug session. 
The overall problem is that we don't have a consistent way to bubble up errors (or warnings, like in this case) from the data provider to the user.

I'll check if it's possible to show something meaningful in the GPKG browser data items.

**Comment by elpaso** [comment]
A small step forward:

![qgis-read-only-gpkg-bug](https://user-images.githubusercontent.com/142164/83964670-cc162280-a8ae-11ea-98a8-30d932cd498e.png)

**Comment by elpaso** [comment]
@bvthomsen the problem here is that I cannot really get the reason (read-only) of the failure from the underlying library (GDAL), because it is just a warning and warnings are not captured and bubbled up to the client code.

**Comment by rouault** [comment]
Hum, I cannot reproduce issue with opening read-only GPKG in QGIS:
```
mkdir ro
copy poly.gpkg
chmod -R a+w ro
```
And I can just open fine ro/poly.gpkg in QGIS
Looking in the logs, it will first try to open in read-write mode, and then fallback to read-only

**Comment by bvthomsen** [comment]
Windows only problem ?

This is the message, that's generated in the QGIS log facility (Dialog "Log messages" , tab "GDAL") :

> 2020-06-07T14:41:06     WARNING    Cannot open D:/bo/fff.gpkg.(disk I/O error: this file is a WAL-enabled database. It cannot be opened because it is presumably read-only or in a read-only directory.)

The message appears in the log when I double click on the gpkg file (not the layer) in the QGIS browser.
Is it  possible to catch the error and display it alongside the file icon/name in the QGIS browser (or _anywhere_ that gets the users immediate attention) ?

**Comment by rouault** [comment]
> Windows only problem ?

no, from the error message, it is related to the file to be already in WAL mode (which is normally only a transient state, if QGIS could be closed properly), and in read-only directory. I can reproduce on Linux too now (my previous attempt was on a GPKG in default DELETE mode)

**Comment by gacarrillor** [comment]
> > Windows only problem ?
> 
> no, from the error message, it is related to the file to be already in WAL mode (which is normally only a transient state, if QGIS could be closed properly), and in read-only directory. I can reproduce on Linux too now (my previous attempt was on a GPKG in default DELETE mode)

Hi @rouault, I'm getting this error as well while developing a plugin:

`ERROR 1: disk I/O error: this file is a WAL-enabled database. It cannot be opened because it is presumably read-only or in a read-only directory.`

My GPKG folder is /tmp/, so it's never a read-only directory. I run a couple of commands from an external .jar to extract certain set of data from the GPKG, but I'm not sure that it causes the error afterwards.

Do you know if one could recover the DB connection after such error message or if it's there any workaround?

I'd like to avoid asking users to start a new QGIS project.

**Comment by gacarrillor** [comment]
For the record;

I ended up running a vacuum on the DB, like [here](https://github.com/qgis/QGIS/blob/2d1aa68f0d044f2aced7ebeca8d2fa6b754ac970/python/plugins/db_manager/db_plugins/spatialite/connector.py#L555), after I was writing to the DB via PyQGIS, so that the external .jar could read a sanitized DB. 

That fixed my problem!
