### ISSUE TITLE
QGIS Server WFS 1.1: issue with axis order

### ISSUE THREAD

**Issue by ismailsunni** [qgis/QGIS#36584]
**Describe the bug**

I am trying to use QGIS Server to serve a WFS with a time dimension and view it using the new QGIS temporal handler.

Unfortunately, the features are not shown on QGIS. I checked the requested URL with QGIS Network Logger plugin, and this is the request:

```
http://localhost:8380/?LAYERS=eq-filtered&ACCEPTVERSIONS=2.0.0,1.1.0,1.0.0&SERVICE=WFS&REQUEST=GetFeature&VERSION=1.1.0&TYPENAME=eq-filtered&SRSNAME=EPSG:4326&BBOX=-0.0985539665264239,119.31367704126752471,1.21353055886411432,120.62576156665805627,EPSG:4326
```

and this is the returns
```xml
<wfs:FeatureCollection xmlns:wfs="http://www.opengis.net/wfs" xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml" xmlns:ows="http://www.opengis.net/ows" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:qgs="http://www.qgis.org/gml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wfs http://schemas.opengis.net/wfs/1.0.0/wfs.xsd http://www.qgis.org/gml http://localhost:8380/?LAYERS=eq-filtered&amp;ACCEPTVERSIONS=2.0.0,1.1.0,1.0.0&amp;SRSNAME=EPSG:4326&amp;SERVICE=WFS&amp;VERSION=1.1.0&amp;REQUEST=DescribeFeatureType&amp;TYPENAME=eq-filtered&amp;OUTPUTFORMAT=text/xml; subtype%3Dgml/3.1.1">
    <gml:boundedBy>
        <gml:Envelope srsName="EPSG:4326">
            <gml:lowerCorner>-0.09855397 119.31367704</gml:lowerCorner>
            <gml:upperCorner>1.21353056 120.62576157</gml:upperCorner>
        </gml:Envelope>
    </gml:boundedBy>
</wfs:FeatureCollection>
```

The BBOX seems wrong (longitude and latitude in the wrong place).

I tried to "fix" the BBOX, like this:
```
http://localhost:8380/?LAYERS=eq-filtered&ACCEPTVERSIONS=2.0.0,1.1.0,1.0.0&SERVICE=WFS&REQUEST=GetFeature&VERSION=1.1.0&TYPENAME=eq-filtered&SRSNAME=EPSG:4326&BBOX=119.31367704126752471,-0.0985539665264239,120.62576156665805627,1.21353055886411432,EPSG:4326
```

and I got the expected result:
```xml
<wfs:FeatureCollection xmlns:wfs="http://www.opengis.net/wfs" xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml" xmlns:ows="http://www.opengis.net/ows" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:qgs="http://www.qgis.org/gml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wfs http://schemas.opengis.net/wfs/1.0.0/wfs.xsd http://www.qgis.org/gml http://localhost:8380/?LAYERS=eq-filtered&amp;ACCEPTVERSIONS=2.0.0,1.1.0,1.0.0&amp;SRSNAME=EPSG:4326&amp;SERVICE=WFS&amp;VERSION=1.1.0&amp;REQUEST=DescribeFeatureType&amp;TYPENAME=eq-filtered&amp;OUTPUTFORMAT=text/xml; subtype%3Dgml/3.1.1">
    <gml:boundedBy>
        <gml:Envelope srsName="EPSG:4326">
            <gml:lowerCorner>119.31367704 -0.09855397</gml:lowerCorner>
            <gml:upperCorner>120.62576157 1.21353056</gml:upperCorner>
        </gml:Envelope>
    </gml:boundedBy>
    <gml:featureMember>
        <qgs:eq-filtered gml:id="eq-filtered.52">
            <gml:boundedBy>
                <gml:Envelope srsName="EPSG:4326">
                    <gml:lowerCorner>119.9 0.21</gml:lowerCorner>
                    <gml:upperCorner>119.9 0.21</gml:upperCorner>
                </gml:Envelope>
            </gml:boundedBy>
            <qgs:geometry>
                <Point xmlns="http://www.opengis.net/gml" srsName="EPSG:4326">
                    <pos xmlns="http://www.opengis.net/gml" srsDimension="2">119.9 0.21</pos>
                </Point>
            </qgs:geometry>
            <qgs:id>20140923172220</qgs:id>
            <qgs:time>2014-09-23 10:15:20</qgs:time>
            <qgs:location_description>Sulteng</qgs:location_description>
            <qgs:magnitude>5.1</qgs:magnitude>
            <qgs:depth>30</qgs:depth>
        </qgs:eq-filtered>
    </gml:featureMember>
// ommited
    <gml:featureMember>
        <qgs:eq-filtered gml:id="eq-filtered.3288">
            <gml:boundedBy>
                <gml:Envelope srsName="EPSG:4326">
                    <gml:lowerCorner>119.68 -0.05</gml:lowerCorner>
                    <gml:upperCorner>119.68 -0.05</gml:upperCorner>
                </gml:Envelope>
            </gml:boundedBy>
            <qgs:geometry>
                <Point xmlns="http://www.opengis.net/gml" srsName="EPSG:4326">
                    <pos xmlns="http://www.opengis.net/gml" srsDimension="2">119.68 -0.05</pos>
                </Point>
            </qgs:geometry>
            <qgs:id>20190604073528</qgs:id>
            <qgs:time>2019-06-04 00:35:28</qgs:time>
            <qgs:location_description>Sulawesi Tengah</qgs:location_description>
            <qgs:magnitude>4.1</qgs:magnitude>
            <qgs:depth>10</qgs:depth>
        </qgs:eq-filtered>
    </gml:featureMember>
</wfs:FeatureCollection>
```
So, there is a problem either in the QGIS Server or the temporal handling of QGIS. The WMS from the same QGIS Server itself is working fine.

I tested with a WFS from a [GeoServer](https://geonode.wfp.org/geoserver/wfs). It does not have a time field as Datetime, but a string, so I created one from it. It's working fine on QGIS temporal handling. So, probably the problem is on the QGIS Server one. Or perhaps there is a different way to handle WFS server?

**How to Reproduce**

1. Setup a QGIS Server with a vector layer that has a time attribute
2. Access the WMS and WFS from QGIS (master)

**QGIS and OS versions**

QGIS version | 3.13.0-Master | QGIS code revision | 53091b34b1
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 10.12 (Ubuntu 10.12-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Ubuntu 18.04.4 LTS | This copy of QGIS writes debugging output.
Active python plugins | QuickOSM; quick_map_services; qgisnetworklogger; latlontools; Mergin; qgis2web; QuickWKT; qfieldsync; MetaSearch; processing

**Additional context**

**Comment by nyalldawson** [comment]
It's definitely NOT an issue in the new client side temporal code -- it's either an issue in the wfs provider or qgis server

**Comment by rouault** [comment]
> The BBOX seems wrong (longitude and latitude in the wrong place).

no, that's correct. With WFS >= 1.1, EPSG:4326 is in latitude, longitude order. However using "EPSG:4326" isn't recommended, and "urn:ogc:def:crs:EPSG::4326" should rather be used to avoid any ambiguity on axis order. Might be a QGIS server issue. You could probably force to WFS 1.0 to avoid that issue

**Comment by ismailsunni** [comment]
Hi @rouault @nyalldawson 
Thanks, I set it to WFS 1.0 and the issue is gone. Does it mean that QGIS Server only serves WFS 1.0?
And where can use/set `urn:ogc:def:crs:EPSG::4326` on the request? I couldn't find it on the CRS menu to setup the QGIS Server.

**Comment by rouault** [comment]
> Does it mean that QGIS Server only serves WFS 1.0?

Looking closer, it has code to support 1.0 and 1.1. But 1.1 support seems to be currently non-compliant regarding EPSG axis order.

**Comment by ismailsunni** [comment]
I think the comment from @rouault (https://github.com/qgis/QGIS/issues/36584#issuecomment-634572392) has enough information for the issue.

**Comment by elpaso** [comment]
@ismailsunni would you please have a look to my PR if that fixes your issues?

**Comment by ismailsunni** [comment]
Hi @elpaso how can I test QGIS Server from my own build? I usually use a docker image for QGIS Server. Thanks

**Comment by elpaso** [comment]
`qgis_mapserver` binary

**Comment by elpaso** [comment]
@ismailsunni gentle ping

**Comment by ismailsunni** [comment]
hi @elpaso 
thanks for the hint, I managed to run it. I got the landing page! But how can I test it on QGIS?

I tried several URLs for the WFS (and WMS) like localhost:8000 but it doesn't work. I tried to check with the URL on the landing page, like 
> http://localhost:8000/project/7c47541c4d7e51726abe31189d12e939

I can get the capabilities (using postman), but I can't add the URL on QGIS (it says `Download of capabilities failed: Connection refused` or `Download of landing page failed: Connection refused`

**Comment by elpaso** [comment]
forget the landing page and pass MAP=...&SERVICE=WMS...

**Comment by ismailsunni** [comment]
Ah, thanks @elpaso 

I tried with the same project as in my [first comment](https://github.com/qgis/QGIS/issues/36584#issue-621907053), but it still gives me the same result.

```
http://localhost:8000/?LAYERS=eq-filtered&ACCEPTVERSIONS=2.0.0,1.1.0,1.0.0&SERVICE=WFS&REQUEST=GetFeature&VERSION=1.1.0&TYPENAME=eq-filtered&SRSNAME=EPSG:4326&BBOX=-0.0985539665264239,119.31367704126752471,1.21353055886411432,120.62576156665805627,EPSG:4326
```

I got:
```
<wfs:FeatureCollection xmlns:wfs="http://www.opengis.net/wfs" xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml" xmlns:ows="http://www.opengis.net/ows" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:qgs="http://www.qgis.org/gml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wfs http://schemas.opengis.net/wfs/1.0.0/wfs.xsd http://www.qgis.org/gml http://localhost:8000/?LAYERS=eq-filtered&ACCEPTVERSIONS=2.0.0,1.1.0,1.0.0&SRSNAME=EPSG:4326&SERVICE=WFS&VERSION=1.1.0&REQUEST=DescribeFeatureType&TYPENAME=eq-filtered&OUTPUTFORMAT=text/xml; subtype%3Dgml/3.1.1">
<gml:boundedBy>
<gml:Envelope srsName="EPSG:4326">
<gml:lowerCorner>-0.09855397 119.31367704</gml:lowerCorner>
<gml:upperCorner>1.21353056 120.62576157</gml:upperCorner>
</gml:Envelope>
</gml:boundedBy>
</wfs:FeatureCollection>
```

**Comment by elpaso** [comment]
Are you testing https://github.com/qgis/QGIS/pull/41242 ?

We are now following GeoServer conventions and EPSG:4326 is supposed to be interpreted as LON-LAT order.

 I don't know what you are testing but it seems to me `-0.0985539665264239,119.31367704126752471` is LAT-LON

**Comment by ismailsunni** [comment]
hi @elpaso 

Yes, I use your branch.

And yes, it was my mistake. I have checked again the URL, it is fixed now.

I also have tested on QGIS, I can see my features now (I can't see it previously, like I mentioned in my first comment above).

Thanks for the fix!
