### ISSUE TITLE
[Cad] snapping occurs to segment instead of point when a constraint is set

### ISSUE THREAD

**Issue by olivierdalang** [qgis/QGIS#36585]
**Describe the bug**

With the CAD advanced digitizing, snapping occurs to {the extension of} segments instead of points when a constraint is set.

Instead, it should prioritize vertices over segments (as with regular snapping) and only snap to segments when segments snapping is enabled.

**How to Reproduce**

1. lock an angle constraint (ctrl + a)
2. try to snap to a point of a linestring
3. see that the snapping occurs to {the extension of} the segment instead of the point

**QGIS and OS versions**

master (3.13) current and ltr

**Additional context**

**Comment by uclaros** [comment]
Constraints imposed by the Advanced Digitizing should *never* be ignored, regardless of snapping though.
If I lock an angle, it means I really really absolutely need that angle. If I then want to snap to a vertex that does not satisfy the angle, I should unlock the angle first.

**Comment by olivierdalang** [comment]
@uclaros Yes the hard constraints are preserved, snapping just sets the position along the hard constraint (this is already the case, the issue is just about snapping priority in this scenario)

**Comment by uclaros** [comment]
@olivierdalang OK, I misunderstood. So if I'm not mistaken this time too, when advanced digitizing constraints are set, they always have priority.
So
- *Snap to vertex* means snap to closest point to vertex while preserving constraint.
- *Snap to segment* means snap to segment or extension of segment while preserving constraint.

**Comment by olivierdalang** [comment]
Exactly. (the issue was that `snap to vertex` did not happen with a constraint, so you could only `snap to segment`)
