### ISSUE TITLE
Issue with the opacity of Polygon vector while printing

### ISSUE THREAD

**Issue by mhdSahal** [qgis/QGIS#36580]
While trying to make print of polygon vector, Fill opacity is affecting the border opacity when fill style is Horizontal. 
The tool working fine when fill style is solid.

below the styling that I have used
fill opacity is 152 
border opacity is 255 
fill style is Horizontal

while trying to print, the opacity of border is being replaced with the opacity of fill color

**Comment by gioman** [comment]
@mhdSahal attach a sample project+data.

**Comment by mhdSahal** [comment]
[bug.zip](https://github.com/qgis/QGIS/files/4656572/bug.zip)
 
Please find the attached
