### ISSUE TITLE
Compatibility Warning for Field Names

### ISSUE THREAD

**Issue by rsgillespie** [qgis/QGIS#36602]
**Feature description**
To help avoid compatibility issues, I suggest providing a warning in the Layer Properties dialog when naming fields with characters that are not supported by other software. Anyone reading this probably has better ideas than I on how to achieve this, but I am imagining an icon, perhaps an exclamation point, would appear next to the row containing the offending characters in the table on the Fields tab, an icon that can be clicked on to reveal a message. The message might say that a field name starting with a letter and consisting of only alphanumeric characters and underscores is recommended for compatibility with other software. I have no idea how hard that would be to implement. 

A possibly simpler alternative would be to include the compatibility help text at the bottom of the dialog window, similarly to the dependencies tab, as circled in the screenshot below.

![image](https://user-images.githubusercontent.com/45669353/82508238-4a09b980-9ab9-11ea-931c-bc17c35ea084.png)

**Additional context**
As of version 3.10.6, it is possible to name a field, at least in a shapefile, with spaces, periods, hyphens, brackets, and beginning with an underscore, all of which are [not supported in ArcGIS](https://support.esri.com/en/technical-article/000005588). The fact that QGIS supports a wider variety of field names is great, but it can lead to confusing compatibility issues when files that work fine in QGIS don't work in ArcGIS.

I had an issue recently that this feature could have helped to avoid. I had imported data from a spreadsheet with R, which adds periods in place of unsupported characters in field names by default. I opened the files and worked with the data in QGIS without incident, which is wonderful. When I sent the files to colleagues who use ArcGIS, however, they were able to load the feature class, but the attribute tables were missing. I'm hesitant to admit how long it took me to realize what was going on, and meanwhile my colleagues were unable to work with my data. It's a mistake I will never make again, but I think the QGIS UI can make it easier for others to avoid.

**Comment by alexbruy** [comment]
Duplicates #21532.
