### ISSUE TITLE
Symbology using relations does not propagate in QGIS Server

### ISSUE THREAD

**Issue by NyakudyaA** [qgis/QGIS#36614]
# Problem

I have a QGIS project with a relations setup. One of the tables is set up with the styles using relations

![relation-symbology](https://user-images.githubusercontent.com/2510900/82532300-5afe0d80-9b41-11ea-82d0-688f15903101.png)

The style that appears in QGIS looks like
![style-qgis](https://user-images.githubusercontent.com/2510900/82532422-a1ec0300-9b41-11ea-8063-28079b777230.png)

The corresponding wms from QGIS Server looks like

![Screenshot from 2020-05-21 09-06-26](https://user-images.githubusercontent.com/2510900/82532820-6271e680-9b42-11ea-9ee4-f02041c57dce.png)

PS: I am not sure if it's a bug or a feature request. I will try to setup a demo project and share.

I am using QGIS Server 3.10 and 3.12 in docker

**Comment by elpaso** [comment]
At first sight, it smells like a bug to me...

**Comment by elpaso** [comment]
@NyakudyaA ping me when the test project is ready.

**Comment by NyakudyaA** [comment]
> @NyakudyaA ping me when the test project is ready.

Ping @elpaso 
[bug-issue.zip](https://github.com/qgis/QGIS/files/4669248/bug-issue.zip)

**Comment by elpaso** [comment]
@NyakudyaA I just opened your project but I can't see any issue: WMS is on the right, local project on the main map:

![immagine](https://user-images.githubusercontent.com/142164/82816515-92e7b680-9e9b-11ea-8998-b478a9994d99.png)

**Comment by NyakudyaA** [comment]
> @NyakudyaA I just opened your project but I can't see any issue: WMS is on the right, local project on the main map:
> 
> ![immagine](https://user-images.githubusercontent.com/142164/82816515-92e7b680-9e9b-11ea-8998-b478a9994d99.png)

@elpaso what setup do you have there. Which QGIS Server version are you using.

**Comment by rldhont** [comment]
Bugfix has been done around relation in QGIS Server https://github.com/qgis/QGIS/pull/33476 and https://github.com/qgis/QGIS/pull/33557 Relations used QgsProject.instance() but it's has been fixed

**Comment by NyakudyaA** [comment]
@elpaso I have just tried this with a different qgis server image and it actually returns the proper image. So this must be a specific implementation of QGIS Server from lizmap that has a bug. I will report it to them to investigate.
