### ISSUE TITLE
Field length and precision options are permanently shown when creating a temporary scratch layer

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#36616]
Menu Layer --> Create Layer --> New temporary scratch layer
In the "new fields" section, enter a name
Play with the type combobox (boolean, text, whole number, date...): You'd notice that field and precision options are always available despite not being relevant. Could be confusing.
We should disable them when they are not relevant.

**Comment by alexbruy** [comment]
Which revision are you using? This should be already fixed.

**Comment by DelazJ** [comment]
6c89fcf8db
Will update in the day and let you know

**Comment by DelazJ** [comment]
Confirmed. Sorry for the noise.
