### ISSUE TITLE
QGIS fails to open postgis raster resource that contains capital letters in table name

### ISSUE THREAD

**Issue by arkanoid87** [qgis/QGIS#36610]
> QGIS version | 3.10.4-A Coruña | QGIS code revision | 10bc9f2ff2
> -- | -- | -- | --
> Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
> Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
> Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.6.2-CAPI-1.10.2 4d2925d6
> Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
> PostgreSQL Client Version | 10.12 (Ubuntu 10.12-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
> QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2

When trying to open raster via QGIS Browser I get the following error
```
Invalid Layer : GDAL provider Cannot get GDAL raster band: 
Raster layer Provider is not valid (provider: gdal, URI:  PG: dbname='MYDB' host=myserver.com port=6665 user='foo' password='bar' sslmode=disable mode=2 schema='public' column='rast' table='FOOLAYER'
```

I tried to use same query line with gdalinfo command line, I get partial results
```
gdalinfo "PG: dbname='MYDB' host=myserver.com port=6665 user='foo' password='bar' sslmode=disable mode=2 schema='public' column='rast' table='FOOLAYER'"

ERROR 1: Error getting band metadata while creating raster bands
<follows complete CRS and bounds descriptions but no bands>
```

I've been wandering around the db structure via dbadmin, but I've found no issues there, so I went back to command line and finally got the resource correctly by using double quoted table field:
```
gdalinfo "PG: dbname='MYDB' host=myserver.com port=6665 user='foo' password='bar' sslmode=disable mode=2 schema='public' column='rast' table='\'FOOLAYER\''"
```

**Comment by elpaso** [comment]
This is the expected behavior. See: https://stackoverflow.com/questions/20878932/are-postgresql-column-names-case-sensitive

**Comment by gioman** [comment]
@elpaso shouldn't the behavior be consistent with vector tables? that ones can be loaded from the browser when they have uppercase letters in their name. QGIS seems to always double quote schema and table names. Just asking.

**Comment by arkanoid87** [comment]
> This is the expected behavior. See: https://stackoverflow.com/questions/20878932/are-postgresql-column-names-case-sensitive

I'm sorry but the very same stackoverflow link you shared shows that this is NOT the expected behaviour.

Let me recap some facts:
- [x] postgreSQL is case-sensitive
- [x] raster2pgsql deals with case-sensitive schemas and table names by using the "-q" option
- [x] I can work with case-sensitive postGIS data with other programs and scripts
- [x] QGIS connector/browser doesn't ask for any schema name or table name but builds the GDAL connection string by itself. Same connection string drives gdalinfo to same error.
- [x] QGIS is partially capable of dealing with case-sensitive table contents, i.e. renaming schema from QGIS browser works for both capital to not-capital conversions
- [x] QGIS fails to add taster to canvas where other program succeeds

Using lower-case-with-underscore schemas and table names is NOT a postgreSQL requirement.
https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS
> Quoting an identifier also makes it case-sensitive, whereas unquoted names are always folded to lower case. For example, the identifiers FOO, foo, and "foo" are considered the same by PostgreSQL, but "Foo" and "FOO" are different from these three and each other. (The folding of unquoted names to lower case in PostgreSQL is incompatible with the SQL standard, which says that unquoted names should be folded to upper case. Thus, foo should be equivalent to "FOO" not "foo" according to the standard. If you want to write portable applications you are advised to always quote a particular name or never quote it.)

If you are saying that lower-case-with-underscore schemas and table names is a QGIS requirement for postGIS, I'd expect a meaningful error message or a warning at least, instead of blaming user/postGIS with "ERROR 1: Error getting band metadata while creating raster bands"

Therefore I think that this issue should be addressed somehow and should not be considered "expected behaviour".

**Comment by arkanoid87** [comment]
@gioman I'd like to ask you a review on this issue and consider re-opening

**Comment by elpaso** [comment]
Can you check if this is still an issue on 3.12 or master version? 
We are using a completely different provider to open PG rasters now.

**Comment by gioman** [comment]
Works fine on 3.16.2, reopen if necessary.
