### ISSUE TITLE
<ServerException>Layer(s) not valid</ServerException>

### ISSUE THREAD

**Issue by catalinmiraute** [qgis/QGIS#36623]
Hello, I am having the following issue on GetCapabilities on a WMS service published via QGIS Server, with data stored in Postgres: 
<ServerException>Layer(s) not valid</ServerException>

The QGIS Server logs:
CRITICAL Server[3188]: Error, Layer(s) tglimjud_5782aaeb_5d5a_4549_9037_af213a471756 not valid in project /webserver/data/prod/rep1/Test.qgz
WARNING Server[3188]: <ServerException>Layer(s) not valid</ServerException>
I am using QGIS 3.12.3.
Any ideea where to look?

**Comment by gioman** [comment]
@catalinmiraute please attach a dump of that table/layer.

**Comment by Gustry** [comment]
@catalinmiraute First thing to check is if QGIS Server can access your data? Did you save credentials (login/password) in the QGS project? Did you use a Postgresql service file? Or did you use the authentication database?

**Comment by catalinmiraute** [comment]
Hi guys, I solved the problem :) !
It was from credentials and acces and right on Postgres.
Tks a lot, you are great, will keep in touch.

**Comment by catalinmiraute** [comment]
@Gustry: I am having this issue again, with a QGS project pointing to layers/data stored in MS SQL DB. The DB credentials are saved in the project.
The MS SQL DB is responding to Telnet command.
The Qgis Server is installed on Ubuntu 20.04 and works correct,I tested using a QGS project pointing to a shapefile stored local.
Is there something else should I check for?
Tks!

**Comment by gioman** [comment]
> @Gustry: I am having this issue again, with a QGS project pointing to layers/data stored in MS SQL DB. The DB credentials are saved in the project.
> The MS SQL DB is responding to Telnet command.
> The Qgis Server is installed on Ubuntu 20.04 and works correct,I tested using a QGS project pointing to a shapefile stored local.
> Is there something else should I check for?
> Tks!

@catalinmiraute is this a different problem from the one originally reported? if yes this must be filed in a new ticket.

**Comment by catalinmiraute** [comment]
@gioman I have no ideea, the result "Layer(s) not valid" is the same, only the environment is change - Qgis Server on Ubuntu

**Comment by catalinmiraute** [comment]
... and data in MS SQL DB

**Comment by gioman** [comment]
> I have no ideea, the result "Layer(s) not valid"

@catalinmiraute the original description is about PostgreSQL, this https://github.com/qgis/QGIS/issues/36623#issuecomment-639481177 seems about MS SQL Server.

**Comment by catalinmiraute** [comment]
Yes, you are right, my mistake.

**Comment by gioman** [comment]
> Yes, you are right, my mistake.

@catalinmiraute please file a new ticket, use a meaningful subject and a detailed description, thanks.

**Comment by joseffb-mla** [comment]
Im having this issue with postgres. everything works in the desktop client then when I goto check the qgis server WMS I get that error. 

Can you confirm the process of saving the credentials in the project (or link to it) so I can be sure to have done that. Thanks!
