### ISSUE TITLE
Custom function in GraduatedRenderer

### ISSUE THREAD

**Issue by fengshang1972** [qgis/QGIS#36621]
I created a custom function for QgsGraduatedSymbolRenderer as below:
        @qgsfunction(args="auto", group='Custom')
        def myexpression(incr, feature, parent):
            val = feature["value"]
            return(val+incr)

And then called:
nr = QgsGraduatedSymbolRenderer('myexpression(5)', ranges)
layer.setRenderer(nr)
Everything works fine and the features are rendered correctly.

But if I called: 
incr = 5
nr = QgsGraduatedSymbolRenderer('myexpression(incr)', ranges)
layer.setRenderer(nr)
The myexpression function will not be called at all and the layer is not rendered.

**Comment by nyalldawson** [comment]
This is expected -- the QGIS expression engine has no knowledge of local python variables like `incr`.

The correct approach here is to use QgsExpressionContext, with a custom QgsExpressionContextScope containing a variable named "incr" set to your desired value.

In any case, this isn't a QGIS bug, and support questions like this should be asked on gis.stackexchange.com instead.
