### ISSUE TITLE
Calling fieldConstraintsAndStrength(0) crashes QGIS from Python

### ISSUE THREAD

**Issue by elpaso** [qgis/QGIS#36622]
I need to investigate it:

Failed assertion in SIP lib:

```
assert layer.isValid()
layer.fieldConstraintsAndStrength(0)                                                                                                                                                          
python: siplib.c:13030: get_from_convertor: asserzione "sipTypeIsClass(td)" non riuscita.
Annullato
```

**Comment by elpaso** [comment]
I cannot reproduce anymore, must have been a local issue.

**Comment by gacarrillor** [comment]
Reopening because I also stumble upon this issue.

Steps to reproduce: 

1. Load/create a vector layer. 
2. Open layer properties --> Attributes form.
3. Choose a field and check the `Not Null` constraint.
4. Accept the changes and enter the following line in the Python console:

    `layer.fieldConstraintsAndStrength(field_index)`

5. As soon as you execute the line, QGIS crashes.

**Comment by 3nids** [comment]
I stumbled on the same issue today on Travis while I have no issue locally.
This seems to be related to the version of sip.

**Comment by 3nids** [comment]
@gacarrillor what is your OS version? sip version?

**Comment by gacarrillor** [comment]
This is the about dialog's system info:


QGIS version | 3.14.0-Pi | QGIS code revision | 9f7028fd23
-- | -- | -- | --
Compiled against Qt | 5.12.8 | Running against Qt | 5.12.8
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.2 (Ubuntu 12.2-4) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Ubuntu 20.04 LTS | This copy of QGIS writes debugging output.

**Comment by alexbruy** [comment]
Can't reproduce with the latest master (e5e6a13671) on Linux. Python 3.10.12 and SIP 4.19.25.
