### ISSUE TITLE
AssetFinda Plugin

### ISSUE THREAD

**Issue by emmaj789** [qgis/QGIS#36639]
Hi,

When attempting to add an asset using QGIS and the AssetFinda plugin, I can create the asset and view it in AssetFinda but it won't show up on QGIS spatially. I am unsure as to why I am having trouble with it now as two days ago I could do the exact thing with no trouble at all and I haven't changed anything. Same method and same program (at least I think so (using QGIS 3.8 Zanzibar)).

Any assistance would be much appreciated as I'm new to this program.

**Comment by NathanW2** [comment]
Best to raise this with the AssetFinda devs as that is their plugin

**Comment by emmaj789** [comment]
Where would be the best place for this? I have no idea where that would be.

Thanks.

**Comment by NathanW2** [comment]
AssetFinda page: https://assetfinda.com/contact-us
