### ISSUE TITLE
Attribute table in Print Composer doesn't refresh

### ISSUE THREAD

**Issue by EnFiore** [qgis/QGIS#36647]
[attribute_table_print_composer.zip](https://github.com/qgis/QGIS/files/4667702/attribute_table_print_composer.zip)
Hi,
I have noticed that if there is some expression into fields in Attribute table added to Print Composer, when you change the Source, table showed doesn't change, but if you open attribute they refer to the new source. 
This issue causes that you have to create a new Attribute Table e reformatting it or you have to close QGIS and than table showed is correct.

This issue affects QGIS 3.10.6-A Coruña

**update**
issue may be related to layer and style block and not at expression in attribute table

**Comment by gioman** [comment]
@EnFiore please attach a sample project+data.

**Comment by EnFiore** [comment]
I have attached project.
To reproduce the issue:

1. 1. Open print composer
2. Select table
3. change te source

issue may be related to  layer and style block and not at expression in attribute table
