### ISSUE TITLE
Save selection as new temporary layer

### ISSUE THREAD

**Issue by NyakudyaA** [qgis/QGIS#36646]
# Problem

* Load a layer into QGIS
* Use the selection tools to select a subset of data.
* Choose export selected - Add the option to save selected as a temporary scratch layer.
![-Untitled Project - QGIS 9cc37a124e_001](https://user-images.githubusercontent.com/2510900/82643975-d5e22980-9c10-11ea-8b69-5ff62cc90f4d.png)

**NB** It's quite useful to create a new temporary layer from the existing subset. I know there is a duplicate layer and using filters

**Comment by uclaros** [comment]
A handy workaround is *Copy Features* and *Paste Features As* > *Temporary Scratch Layer*
`ctrl+c` - `ctrl+alt+v`

**Comment by NyakudyaA** [comment]
> A handy workaround is _Copy Features_ and _Paste Features As_ > _Temporary Scratch Layer_
> `ctrl+c` - `ctrl+alt+v`

Thanks,  Didn't know about this work around. Maybe it's enough to do it this way

**Comment by gioman** [comment]
> Maybe it's enough to do it this way

closing?

**Comment by NyakudyaA** [comment]
> > Maybe it's enough to do it this way
> 
> closing?

Yes, we can close this.
