### ISSUE TITLE
Crash repport

### ISSUE THREAD

**Issue by guillaumelevieux** [qgis/QGIS#36649]
Crash ID: ed5d5ec973b366c2ee071f6886c412fcf10b8d6f

Stack Trace

QMetaObject::activate :
QgsMapRendererCustomPainterJob::cancelWithoutBlocking qgsmaprenderercustompainterjob.cpp:159
QgsMapCanvas::stopPreviewJobs qgsmapcanvas.cpp:2475
QgsMapCanvas::refreshMap qgsmapcanvas.cpp:529
QMetaObject::activate :
QTimer::timerEvent :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32Private::sendTimerEvent :
QEventDispatcherWin32::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1606
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.10.6-A Coru�a
QGIS code revision: ec80021f49
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment]
@guillaumelevieux please add all the requested infos:



**Describe the bug**


**How to Reproduce**



**QGIS and OS versions**



**Additional context**

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
