### ISSUE TITLE
Crash when deleting print layout items

### ISSUE THREAD

**Issue by justmematej** [qgis/QGIS#36656]
Hello,
we are having issues while editing (deleting from) a plot layout in latest QGIS.
We can reproduce the issue when we remove more than one map from the plot layout at the same time. If we delete map one by one, it works. 

We were able to reproduce the issue on two installs with the 3.10.6 installed as well.
Crash report is:
Crash ID: bec74bf0e7d9b7c9344cc101e1cbdf414a9eaf65

Stack Trace

QgsLayoutItem::writeXml qgslayoutitem.cpp:614
QgsLayoutItemUndoCommand::saveState qgslayoutitemundocommand.cpp:60
QgsLayoutUndoStack::beginCommand qgslayoutundostack.cpp:51
QgsLayoutItem::beginCommand qgslayoutitem.cpp:973
QgsLayoutLegendWidget::composerMapChanged qgslayoutlegendwidget.cpp:741
QMetaObject::activate :
QgsLayoutItemComboBox::itemChanged moc_qgslayoutitemcombobox.cpp:150
QMetaObject::activate :
QWidgetLineControl::`default constructor closure' :
QComboBox::setCurrentIndex :
QComboBox::setCurrentIndex :
QWidgetLineControl::`default constructor closure' :
QMetaObject::activate :
QAbstractItemModel::endRemoveRows :
QSortFilterProxyModel::removeRows :
QSortFilterProxyModel::sortRole :
QSortFilterProxyModel::`default constructor closure' :
QMetaObject::activate :
QAbstractItemModel::beginRemoveRows :
QgsLayoutModel::setItemRemoved qgslayoutmodel.cpp:574
QgsLayout::removeLayoutItem qgslayout.cpp:563
QgsLayoutView::deleteItems qgslayoutview.cpp:867
QgsLayoutView::deleteSelectedItems qgslayoutview.cpp:852
QMetaObject::activate :
QAction::activate :
QAction::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QShortcutMap::dispatchEvent :
QShortcutMap::tryShortcut :
QWindowSystemInterface::handleShortcutEvent :
QGuiApplicationPrivate::processKeyEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1606
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.10.5-A Coruna
QGIS code revision: 984615fe1e
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment]
@justmematej is the same problem described here? https://github.com/qgis/QGIS/issues/31549

**Comment by justmematej** [comment]
Yes, it seems to be the same one.

**Comment by gioman** [comment]
@justmematej just to be sure, please try also with a new QGIS profile.

**Comment by roya0045** [comment]
I'm curious to know if the issue could be caused by a lock on the xml. I guess the solution would possibly be to delete thing sequentially with a stop between things or keep the xml in memory and only write when all changes have occured if the xml is the bottleneck.

**Comment by samillar94** [comment]
I have the same issue - I pressed delete on a map and legend and the thing stopped responding. 

## Report Details

**Crash ID**: [2ae723f8dd04170d6a7bec3a2343664123ff786b](https://github.com/qgis/QGIS/search?q=2ae723f8dd04170d6a7bec3a2343664123ff786b&type=Issues)


**Stack Trace**
<pre>
QgsLayoutItem::writeXml qgslayoutitem.cpp:614
QgsLayoutItemUndoCommand::saveState qgslayoutitemundocommand.cpp:60
QgsLayoutUndoStack::beginCommand qgslayoutundostack.cpp:51
QgsLayoutItem::beginCommand qgslayoutitem.cpp:973
</pre>


**QGIS Info**
QGIS Version: 3.10.6-A Coru�a
QGIS code revision: ec80021f49
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
> I have the same issue - I pressed delete on a map and legend and the thing stopped responding.

@samillar94 have you tried with a new QGIS profile?

**Comment by samillar94** [comment]
Hi @gioman haven't come across the term "profile" before in QGIS - if you mean a new session, it happens consistently when I try to delete the same thing, but I usually can delete items. If you mean layouts, it happens on various layouts. If you mean versions, I think I have had the problem on 3.10.2, but not sure.

**Comment by gioman** [comment]
> Hi @gioman haven't come across the term "profile" before in QGIS - if you mean a new session, it happens consistently when I try to delete the same thing, but I usually can delete items. If you mean layouts, it happens on various layouts. If you mean versions, I think I have had the problem on 3.10.2, but not sure.

@samillar94 settings > user profiles > new profile

**Comment by samillar94** [comment]
Well, every day's a school day! Can confirm @gioman the problem persists with a new user profile.

**Comment by gioman** [comment]
@samillar94 can you provide a sample project (with data and layouts) that shows the problem for you. I can't replicate here.

**Comment by samillar94** [comment]
OK I may be a while though
