### ISSUE TITLE
Exporting to a ESRI ShapeFIle converts LineStrings to MultiLineStrings

### ISSUE THREAD

**Issue by albertonavasrubio** [qgis/QGIS#36655]
**Describe the bug**

When you export a layer with geometry= Linestring by code or inside the desktop application with the option Export to -->  save layer as ESRI Shapefile, you always get a layer with geometry=MultilinString regardless of the checked options

QgsVectorFileWriter.writeAsVectorFormat(layer, 'layer.shp', 'utf-8',driverName=''ESRI Shapefile)

**How to Reproduce**

In the Python Console:

orglayer=QgsVectorLayer('LineString?crs=epsg:25830','orglayer','memory')

QgsVectorFileWriter.writeAsVectorFormat(orglayer,'c:/temp/layer.shp','utf-8',driverName='ESRI Shapefile')
exportlayer=QgsVectorLayer('c:/temp/layer.shp','exportlayer','ogr')

print ('layer type to export: ' + str(orglayer.wkbType()))
print ('layer type from export: ' + str(copylayer.wkbType()))

**QGIS and OS versions**

QGIS 3.12.2
Windows10 Home

**Additional context**

**Comment by gioman** [comment]
@albertonavasrubio how are you checking of the resulting SHP is multi? in QGIS layer properties?

QGIS always promote SHPs to MULTI. You may want to check with ogrinfo to see if they are really MULTI or not.

**Comment by agiudiceandrea** [comment]
Hi @albertonavasrubio, Shapefile layer types to store points, lines and polygons geometry (without considering Z and M) are called by [ESRI](https://www.esri.com/library/whitepapers/pdfs/shapefile.pdf): Point, MultiPoint, PolyLine, Polygon.

As you can see, for points only there are two separate layer types: one for singlepart point geometries and one for multipart point geometries (also multipart with one point)
For lines and polygons there is only one type each, which can store, in the same layer, mixed singlepart and multipart features. So they are actually handled, respectively, as MultiLineString and MultiPolygon. In these (multi) layers, each feature can be either a singlepart feature or a multipart feature.

**Comment by albertonavasrubio** [comment]
@agiudiceandrea, @gioman Thanks for your sup,port. So if i have understood the only way to have a layer  from a shapefile with LineString  features instead of MultiLineString Featrures is doing a multipart to singlepart conversión after import. It not depends on the way the lines are stored in the shapefile and there is not a verification of that , neither and option to directly import as a singlepart all the features strored in the shapefile.

**Comment by nyalldawson** [comment]
Actually the ONLY way is to use a different format. Even if you run Multiparts to Singleparts, if you save the result as a shapefile then they'll be multilinestrings in QGIS.

**Comment by gioman** [comment]
Closing?

**Comment by nyalldawson** [comment]
Yes - there's nothing which can be done here

**Comment by agiudiceandrea** [comment]
@albertonavasrubio, to be more clear, in the Shapefile format specification, for MultiPoint, PolyLine (actually MultiLineString), Polygon (actually MultiPolygon), there is non difference between a singlepart or a multipart geometry: it can store a multipart with only one part (so you can consider it a singlepart) or with more then one part (so you can consider it a multipart). It depends on what you have to do.

In PyQgis you can use e.g.:
`geometry.constGet().partCount()`
to count the parts in the geometry of each feature so you can also test if the feature contains a singlepart (=1 part) geometry or a multipart (>1 parts) one

and
```python
for part in geometry.constParts():
    # do something with part
```
in this case each `part` will be a LineString (if you are handling a PolyLine/MultiLineString Shapefile).

With the field calculator you can use the function `num_geometries`.

**Comment by albertonavasrubio** [comment]
Thanks
