### ISSUE TITLE
Merging master into branch slowly reformats python files

### ISSUE THREAD

**Issue by uclaros** [qgis/QGIS#36652]
**Feature description.**
When merging master into a branch to keep it up to date or to resolve a conflict of a PR that is waiting to be merged, the git commit hook triggers a reformatting of python files even though 
they are unchanged. If the PR branch is a couple of month old, the files can be a lot.
It's not a big issue, but it would be nice if somehow  this wait could be avoided

**Comment by nyalldawson** [comment]
I'd suggest rebasing instead of merging

**Comment by uclaros** [comment]
But then a force push is required

**Comment by nyalldawson** [comment]
..but it keeps the history MUCH cleaner (I'd argue we shouldn't permit any PR containing a merge commit). Force push is fine, so long as it's to your branch!

**Comment by uclaros** [comment]
Thanks for clearing this out, I was worried that force pushing to an unmerged PR would be frowned upon by those watching the history of changes in the PR. I'll keep it in mind for my PRs that are based on pretty old masters!
