### ISSUE TITLE
Some dialog windows cannot be dragged in Linux (examples: Options and Layer properties)

### ISSUE THREAD

**Issue by fmartinp** [qgis/QGIS#36658]
**Describe the bug**
Some QGIS dialog windows cannot be moved (examples: Options and Layer properties) in Ubuntu 20.04. The dialog window gets the focus and the main QGIS window turns in grey. The main window is not clickable and the dialog window cannot be dragged in the screen independently to the QGIS main window.

**How to Reproduce**

1. Go to 'Settings' in the menu and click on Options
2. An Options dialog window appears and the main QGIS window turns to grey.
3. Try to drag the Options dialog window with the mouse.
4. The Options dialog window and the main QGIS window move as a group. So, the dialog window cannot be dragged to any other position relative to the main QGIS window.

This problem occurs also with the Layer Properties window which has a bigger impact since the user cannot see the results of the changes in the properties until it closes the Layer Properties window.

**QGIS and OS versions**

QGIS version | 3.12.3-București | QGIS code revision | 8234261527
-- | -- | -- | --
Compiled against Qt | 5.12.8 | Running against Qt | 5.12.8
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.2 (Ubuntu 12.2-4) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Ubuntu 20.04 LTS
Active python plugins | timemanager; db_manager; MetaSearch; processing

**Comment by uclaros** [comment]
Under what Desktop Environment / Window Manager?

**Comment by Gustry** [comment]
Ubuntu is using Gnome. This is the default behavior in your desktop environment @fmartinp 
Use Gnome Tweak Tools and disable this. I got the same issue too.
https://askubuntu.com/questions/109321/popup-dialogs-attached-to-window-title-and-not-movable-how-to-detach-modal-dial

**Comment by fmartinp** [comment]
Indeed, first time ever that I saw that option.
Thank you @Gustry!

I will close the issue.
