### ISSUE TITLE
"No parameter definition for the sink 'OUTPUT'" in Algorith 'Mean coordinate(s)'

### ISSUE THREAD

**Issue by joohe** [qgis/QGIS#36669]
<img width="756" alt="05F974B1-11EF-43A3-91D2-271F894A5D71" src="https://user-images.githubusercontent.com/65799142/82720611-0220a780-9cf0-11ea-842d-bdf528c60f49.png">

Whenever I try to run something, not only mean coordinates but also buffer or any other things, I cannot have any output because of this issue.

‘No parameter definition for the sink OUTPUT’

It is not a problem of settings or files, because when I run the same project using my friend’s Mac, it just worked well.
I guess this is a problem of my Mac, but I’m not sure.
I rebooted my Mac and relaunched QGIS several times.
I use QGIS 3.12.

Let me know how I can solve this issue.
Thanks!

**Comment by gioman** [comment]
> , because when I run the same project using my friend’s Mac

@joohe this make us think is a local issue or something specific in your macOS env. What are the differences with your friend macOS? 

Do you have issues if the path leading to your inputs and outputs does not have special chars?

**Comment by joohe** [comment]
I also think that it is a local issue, and maybe the path leading to output is not a big problem. But the problem is, I don’t know why it happens, either 😂
My Mac version is Catalina 10.15.4 and idk my friend’s.

Do you think Formatting my Mac would solve the issue? I really want to get rid of these errors😭

**Comment by nyalldawson** [comment]
There's something very wrong happening here -- it's definitely a local issue only.
