### ISSUE TITLE
Expose 3d:tessellate processing tool in PyQgis

### ISSUE THREAD

**Issue by Dan-Eli** [qgis/QGIS#36661]
**Feature description.**

Proposition to create the appropriate SIP bindings to expose the C function to Python. so that the tessellate processing tool is visible from PyGqgis.

**Additional context**

We need to use the processing tool 3d:tessellate in a QGIS standalone processing script. Presently, when we try to use it gives the following error

```
Traceback (most recent call last):
  File "C:/Users/berge/PycharmProjects/qgis_geo_sim/runner_chordal_axis.py", line 19, in <module>
    processing.run("3d:tessellate", {'INPUT': 'D:/OneDrive/Personnel/Daniel/QGIS/Kingston/Kingston_sub9.gpkg|layername=Road', 'OUTPUT': 'TEMPORARY_OUTPUT'})
  File "C:\OSGeo4W64\apps\qgis\python\plugins\processing\tools\general.py", line 106, in run
    return Processing.runAlgorithm(algOrName, parameters, onFinish, feedback, context)
  File "C:\OSGeo4W64\apps\qgis\python\plugins\processing\core\Processing.py", line 125, in runAlgorithm
    raise QgsProcessingException(msg)
_core.QgsProcessingException: Error: Algorithm 3d:tessellate not found
```

The following question has been published on [GIS Exchange related to this issue](https://gis.stackexchange.com/questions/362584/qgis-standalone-application-in-python-cant-access-3dtessellate-processing-tool)

**Comment by alexbruy** [comment]
Tesselate algorithm can be called from Processing and all necessary geometry API calls already exposed to Python.

Most likely your script does not initialize QGIS and Processing correctly.

**Comment by nyalldawson** [comment]
Actually there is an issue here -- the tesselate algorithm is in the separate 3d provider, which currently is NOT possible to initialize from a standalone script because it's not expose to Python.

Changing to a bug report
