### ISSUE TITLE
When removing layers of a group QGIS crass

### ISSUE THREAD

**Issue by OmarTapiaSilva** [qgis/QGIS#36664]
this is the report of the crash:

Crash ID: 934796d8f1385032928172ee618078e56613aaa3

Stack Trace

QString::QString :
QMetaObject::activate :
QMetaObject::activate :

QGIS Info
QGIS Version: 3.12.3-Bucure?ti
QGIS code revision: 8234261527
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by gioman** [comment]
@OmarTapiaSilva Please try again with a new QGIS profile, no 3rd party plugins installed. If the problem persist add a sample project + data and **detailed** steps to replicate.

**Comment by OmarTapiaSilva** [comment]
Thanks!. I'll do it.

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
