### ISSUE TITLE
Cannot see single quote ' in the Expression Editor

### ISSUE THREAD

**Issue by sshuair** [qgis/QGIS#36686]
**Describe the bug**

I cannot see the single quote `'` in the Expression Editor. You can check out the the image.
The expression is `rpad('Hello', 10, 'x')` but I can't recognize them. 
![image](https://user-images.githubusercontent.com/5787131/82750876-e8fa2280-9de5-11ea-9e37-b66f33badb58.png)

**How to Reproduce**

**Additional context**

QGIS version | 3.13.0-Master | QGIS code revision | 42ba3d78fe
-- | -- | -- | --
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.28.0 | Running against SQLite | 3.28.0
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS 10.15
Active python plugins | SpreadsheetLayers; processing; db_manager; MetaSearch

**Comment by gioman** [comment]
@sshuair it is on your keyboard :)

**Comment by sshuair** [comment]
Do you mean that this is the reason for my keyboard? BTW, how to fix it ?

**Comment by gioman** [comment]
> Do you mean that this is the reason for my keyboard? BTW, how to fix it ?

@sshuair what I'm saying that when creating an expression there are parts that you have to write them manually. Your keyboard surely allows you to write symbols like single quotes, double quotes, etc.

**Comment by nyalldawson** [comment]
@gioman you've misinterpreted the bug -- @sshuair HAS typed the ' character (you can verify this by seeing the correct output expression preview at the bottom of the dialog), it's just not showing on their screen.

**Comment by gioman** [comment]
> you've misinterpreted the bug

@nyalldawson ok

**Comment by sshuair** [comment]
@nyalldawson That's exactly what I mean.

**Comment by nirvn** [comment]
I'll have a look.

**Comment by nirvn** [comment]
I had a look, can't reproduce on my end, and fonts seem to be set properly.

It might be an upstream bug with QScintilla on OS X with HiDPI screens.

**Comment by nirvn** [comment]
@sshuair , BTW, looking at your screenshot, it seems the font used in the editor isn't monospace. Did you change the font used there (via python console)?

**Comment by sshuair** [comment]
@nirvn Yes, It's not monospace.  And I did not change the font by the python console or anything else.
I has found that the python console has the same problem.
![image](https://user-images.githubusercontent.com/5787131/82775323-f52fbf80-9e79-11ea-9410-a234d96c9afe.png)

This is the font setting of my QGIS. And my laptop is MacBook Pro with retina.
![image](https://user-images.githubusercontent.com/5787131/82775376-201a1380-9e7a-11ea-92af-ad0b1b7dad66.png)

![image](https://user-images.githubusercontent.com/5787131/82775398-2ad4a880-9e7a-11ea-9920-6f352cf5888e.png)

**Comment by nirvn** [comment]
Interestingly, your python console is broken, but the python script editor to its right isn't.

**Comment by nirvn** [comment]
@sshuair , are you using self-compiled builds?

**Comment by sshuair** [comment]
No, I install the nightly version `qgis_nightly_master_20200523_122948.dmg` from https://qgis.org/downloads/macos/nightly/?C=M;O=D

**Comment by nirvn** [comment]
@sshuair , can you go in the python console's settings dialog and attach a screenshot of the console settings panel ( i.e., you attached above a screenshot of the console editor panel, can you do the same for the first 'console' panel)?

**Comment by sshuair** [comment]
this is the console setting panel.
![image](https://user-images.githubusercontent.com/5787131/82776969-3a0a2500-9e7f-11ea-819b-3248910a28fa.png)

**Comment by nirvn** [comment]
Thanks; I hope #36692 will improve things for you. Give the nightly .dmg a try in a couple of days.

**Comment by sshuair** [comment]
Ok, I'll try it when the nightly dmg file is ready.

**Comment by gioman** [comment]
@sshuair for what it is worth: I just tested on 3.12.2 on a clean macOS 10.15 installation and I can't confirm. Maybe this happens only on master(?).

**Comment by sshuair** [comment]
@nirvn  It's now fixed. Thanks !  QGIS code revision : [38673f5a7f](https://github.com/qgis/QGIS/commit/38673f5a7f)

![image](https://user-images.githubusercontent.com/5787131/82961208-48774e80-9fef-11ea-868e-d09642f08a7b.png)

**Comment by nirvn** [comment]
@sshuair , fantastic, glad to hear it worked out.
