### ISSUE TITLE
Outdated help for labels "data-defined" placement group options

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#36680]
In labels properties --> Placement --> Data-defined, place the mouse over a data-defined widget.
The Usage section states: 
```
In edit mode, layer's relevant labeling map tool is:
  Defined attribute field --> enabled
  Defined expression --> disabled
```
I think this is a comment from an old time when you needed edit mode to start using label toolbar. And these are the only widgets for which you'd see this message, while more properties are concerned by the tools.

Moreover I'm not sure the comment is clear enough. I could not figure out the difference between fields and expressions other than the label map tools (rotate and move) replace expressions with the corresponding auxiliary storage field. It was not clear to me what they do if I use existing fields, virtual or not.

**Comment by pblottiere** [comment]
Hi @DelazJ,

> I think this is a comment from an old time when you needed edit mode to start using label toolbar. And these are the only widgets for which you'd see this message, while more properties are concerned by the tools.

We could probably just remove the `Usage` section to be in sync with others data-defined widgets. What do you think?

**Comment by DelazJ** [comment]
Hi @pblottiere 
Yes, it would probably help to avoid confusion, and more inline with others
