### ISSUE TITLE
Auxiliary storage fields not visible in form view or using the "Identify" tool 

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#36682]
I made visible some auxiliary storage fields in my attribute table. I can see them in table view.
But using the Identifier tool or moving to the attribute table form view, they don't seem to appear, as you can see in the screenshot below
![image](https://user-images.githubusercontent.com/7983394/82739138-6e75c800-9d3d-11ea-86c0-587c51b22556.png)
master https://github.com/qgis/QGIS/commit/7ee0fce60f4

**Comment by nyalldawson** [comment]
These default to the "hidden" widget. You need to change it from that in order to see them
