### ISSUE TITLE
Remove the option for Project home

### ISSUE THREAD

**Issue by saberraz** [qgis/QGIS#36687]
Under project properties, there is an option to set Project home. IMO, Project home is where the project is located.

Having this option causes confusion when project and its associated files are moved around as it messes up with the relative path and other references to the project.

![image](https://user-images.githubusercontent.com/2649047/82752018-34470d80-9db3-11ea-8935-6cac0fdca0d9.png)

**Comment by nyalldawson** [comment]
Not a bug. It's designed for cases where project aren't stored in the root folder of a wider project.

**Comment by saberraz** [comment]
This will break for example attachment to attribute tables, if the project moves around to other systems. Here is an example:
https://github.com/lutraconsulting/input/issues/655

I am sure it will cause problem with QGIS server  too.

**Comment by nyalldawson** [comment]
It's entirely optional though - if you don't manually set it it will follow the qgs file location by default

**Comment by elpaso** [comment]
And there are also projects stored in DBs where the home can be set to a shared network folder.

**Comment by damidb** [comment]
I left project home in project properties (project in QGIS) blank. I still cannot load pictures in my mergin maps app form: picture (in the form): "not a valid value". The pictures pops up in the form but I cannot save it...:  when trying, a "object cannot be saved, check mandatory fields" message pops up. It's a jpg file.
In QGIS I use in the attachement widget "@project_folder" and "relative to project path".
Even at mergin maps support they don't offer me a solution..
authorities in smartphone OK: phone, media, location...
Using smartphone alaxy A41, win10 and QGIS 3.21..
anybody a solution ?
