### ISSUE TITLE
Custom CRS recognized as Unknown when defined by proj4 string

### ISSUE THREAD

**Issue by gabriel-de-luca** [qgis/QGIS#36688]
**Describe the bug**

When a custom CRS is added from a proj4 string, the WKT definition is not saved in the tbl_srs table of the qgis.db database.
When exporting a layer to the new system an loading it, it is recognized with Unkown CRS system.

**How to Reproduce**

1. Create a new custom CRS with the following proj4 string: `+proj=tmerc +lat_0=-34.6297166 +lon_0=-58.4627 +k=0.999998 +x_0=100000 +y_0=100000 +ellps=intl +towgs84=-148,136,90,0,0,0,0 +units=m +no_defs`
2. Export any layer to the new CRS and load it. The layer CRS property is recognized as Unknown CRS.
3. In the Custom Projections dialog, change the format of the definition to WKT.
4. Reload the layer. The layer CRS property is recgnized with USER code and name

**QGIS and OS versions**

QGIS 3.10.5 at Windows 10 (64-bit) machine, OSGeo4W install.

**Additional context**

In the tbl_srs of qgis.db database, the WKT definition is stored only when the format of the definition in the custom CRS is changed to WKT. 

**Screenshots**

![1-1-customCRS](https://user-images.githubusercontent.com/48416462/82756485-f0eb9f80-9db0-11ea-8647-0147192a51fd.png)

![1-2-qgisdb](https://user-images.githubusercontent.com/48416462/82756483-efba7280-9db0-11ea-9146-018e61d3b18d.png)

![1-3-layerProperties](https://user-images.githubusercontent.com/48416462/82756484-f0530900-9db0-11ea-954f-e099eb354b8b.png)

![2-1-customCRS](https://user-images.githubusercontent.com/48416462/82756482-ef21dc00-9db0-11ea-9cd8-d446aa5fe733.png)

![2-2-qgisdb](https://user-images.githubusercontent.com/48416462/82756480-ee894580-9db0-11ea-9ade-318fa25ac1a3.png)

![2-3-layerProperties](https://user-images.githubusercontent.com/48416462/82756479-ed581880-9db0-11ea-988b-67a717515aa5.png)

**Comment by nyalldawson** [comment]
This is a wont-fix, as it's working as designed. It's not possible to reliably match proj strings to user CRSes defined by proj strings without a LOT of unexpected/dangerous side effects.

Proj strings are a lossy format, discouraged for use in modern workflows. Just don't use them, and use WKT instead.
