### ISSUE TITLE
ValueRelation in OfflineEditing

### ISSUE THREAD

**Issue by Amphibitus** [qgis/QGIS#36698]
By usinge the OfflineEditing Plugin every Valuerelation in the attributedefinitin will be lost . The Layersource by the Valuerelation Part is not change.

Warning Message:
"2020-05-25T11:05:36     WARNING    Fehlender erforderlicher Layer : Layer 'KK_LHAU (offline)' erfordert den Layer 'KK_VSYS' zu laden, der aber nicht gefunden wurde, bitte wenn möglich manuell laden."

The  definition part in the QGIS Project File:

Option name="LayerSource" type="QString" value="MySQL:OrkanDB_Schieder,host=192.168.116.100,port=3306,user=root,tables=KK_VSYS|layername=KK_VSYS"/
![grafik](https://user-images.githubusercontent.com/7237786/82798121-68383680-9e78-11ea-8d7e-c797ab5cd593.png)

![grafik](https://user-images.githubusercontent.com/7237786/82798318-a6355a80-9e78-11ea-9724-05d19c94db8f.png)
 Definitionfields are empty

**Comment by Amphibitus** [comment]
After updating from QGIS 3.12.2 to 3.12.3 and manually changing all entries in the project file " (offline)" to "" (nothing), the value relation works fine

**Comment by gioman** [comment]
> After updating from QGIS 3.12.2 to 3.12.3 and manually changing all entries in the project file " (offline)" to "" (nothing), the value relation works fine

@Amphibitus so closing? or there is still an issue?

**Comment by Amphibitus** [comment]
It is an issue. Why it is necessary to change the qgs File **manually** after export with the Tool

**Comment by signedav** [comment]
@Amphibitus Could you precise what is still the issue here? Maybe you can add an original and an offline project to reproduce the issue. Thanks.
