### ISSUE TITLE
Some EPSG are not well recognize

### ISSUE THREAD

**Issue by Doctor-Who** [qgis/QGIS#36699]
**Describe the bug**

Depending of the SCR of the source raster / vector data, QGIS display Unknown SCR
4326 are diplay fine but 3035 and 2154 

**How to Reproduce**

Load some raster Data (i can do some extract)
Tested with TIF (COG) and also JP2 : same error

See properties :

![Screenshot_20200525_132117](https://user-images.githubusercontent.com/5890416/82809487-80b24c00-9e8c-11ea-8420-f2e441d9ea5a.png)

![Screenshot_20200525_132240](https://user-images.githubusercontent.com/5890416/82809492-827c0f80-9e8c-11ea-9e5d-9229e5af99f0.png)

**QGIS and OS versions**

QGIS 3.12
Proj 7
Linux

**Additional context**

That make me so confused ... 
Retrograding to old LTR 3.4 build with same GDAL / Proj version is working fine.

**Comment by rouault** [comment]
The GDAL version can matter. You need 3.1 at least for the GeoTIFF fix so that a QGIS using PROJ >= 6 doesn't report a unknown CRS

**Comment by Doctor-Who** [comment]
So I've to wait 3.1.1 cause packager seems has some issues with GDAL 3.1 :( 
https://build.opensuse.org/package/show/Application:Geo/gdal 
Thanks for help.

**Comment by nyalldawson** [comment]
Closing as fixed upstream
