### ISSUE TITLE
Error using add-ons.  Plugin uninstalled afterwards

### ISSUE THREAD

**Issue by julianascotton** [qgis/QGIS#36700]
Ao utilizar o complemento do GRASS > v.to.3D, ao clicar no ícone, o software QGIS 3.4 parou de funcionar, o software travou e fechou. Ao iniciar novamente o programa, apareceu um erro, indicando que os complementos foram desinstalados pq fechou o QGIS ao iniciar o complemento. Pediu para reportar o erro e reinstalar assim que resolver o problema. Deste modo, não encontro mais os complementos para instalar. Minha dúvida, é se tem como reparar ou preciso instalar novamente. Obrigada.

English:
When using the GRASS add-on> v.to.3D, when clicking on the icon, the QGIS 3.4 software stopped working, the software crashed and closed. When starting the program again, an error appeared, indicating that the add-ons were uninstalled because QGIS closed when starting the add-on. Asked to report the error and reinstall as soon as the problem is resolved. Thus, I no longer find the add-ons to install. Thanks.

**Comment by gioman** [comment]
@julianascotton Olá

please add the details as asked in the template:



**Describe the bug**


**How to Reproduce**



**QGIS and OS versions**



**Additional context**





Anyway:

3.4 is obsolete, update to the latest 3.10 or 3.12

try with a new QGIS profile, no 3rd party plugins installed.

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
