### ISSUE TITLE
Improvements in Locator feature  search

### ISSUE THREAD

**Issue by andreasneumann** [qgis/QGIS#36701]
**Feature description.**

1. Make the nr of hits configurable (global, per layer, current layer) for the search modes "f" and "af"
2.  improve mode "f" to allow searching in certain columns only: f @my_field my_value - add autocompletion for attribute names if possible
3. In the layer properties fields tab allow to specify if an attribute should be "searchable" (next to the WMS/WFS columns)

About the third item, a rough idea how this could be handled:

![grafik](https://user-images.githubusercontent.com/884476/82812078-7bf09680-9e92-11ea-8b67-e4ef54c212bd.png)

As discussed with @3nids - will be handled as part of our support contract

**Comment by andreasneumann** [comment]
Ah before I forget about it: please add in some extra time for improving the documentation as well.

I think this is right section?

https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html#locator-settings

**Comment by uclaros** [comment]
I think we are missing a visual indicator that the max results has been reached and there are more matching results that are not displayed! Especially if the number of displayed results is configurable.

**Comment by 3nids** [comment]
PR for configuration of max number of results: https://github.com/qgis/QGIS/pull/38628
PR for restricting the active layer search to a specific field with auto completion: https://github.com/qgis/QGIS/pull/38633

**Comment by 3nids** [comment]
PRs for defining which field is searchable:

1. https://github.com/qgis/QGIS/pull/38634 (merged)
2. https://github.com/qgis/QGIS/pull/38687
3. https://github.com/qgis/QGIS/pull/38688

**Comment by 3nids** [comment]
PR for flashing features: https://github.com/qgis/QGIS/pull/38694
