### ISSUE TITLE
QGIS native algorithms hanging connections on inputs after ran

### ISSUE THREAD

**Issue by marcos-fedato** [qgis/QGIS#36728]
**Describe the bug**

After i ran the "native:extractbyattribute" or "native:pointsalonglines" using python processing.run interface, the inputs of the processing becomes "locked" as if the source is still being used.
I'm using geopackage and this causes 2 problems:
1: I can't delete temporary inputs until the process finishes
2: The maximun connections on the underlying SQLite execedes 64 connections over time, becouse my processes iterates over and over using these functions

**How to Reproduce**

Just run one of those algorithms like "native:extractbyattribute" or "native:pointsalonglines" and try to delete the file via system while python has not finished to run.

processing.run("native:extractbyattribute", 
                       {'INPUT': "my.gpkg",
                        'FIELD': "id",
                        'OPERATOR': 0,
                        'VALUE': 1,
                        'OUTPUT': "my2.gpkg"})

os. remove("my.gpkg")

**QGIS and OS versions**

Using windows 10 build 18362
QGS 3.12.3 (i tried to copy the about content, but the about window just showed blank.

**Additional context**
By taking a deep dive into QGS code, i think this may be related to the function:

QgsProcessingFeatureSource *QgsProcessingUtils::variantToSource defined in src/core/processing/qgsprocessingutils.cpp:347

in line 373 e 389 when it creates this temporary source just for use into this processing it passes false to the QgsProcessingFeatureSource constructor in the ownsOriginalSource parameter.

This way the distructor from the QgsProcessingFeatureSource will not kill the source when the QgsProcessingFeatureSource gets distructed.

I haven't tested this possible solution as i don't have a dev env for qgis here, and don't know if there is any other problem this path can lead.

**Comment by nyalldawson** [comment]
Can you share a self-contained script showing this issue?

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
