### ISSUE TITLE
QGIS Bucaresti struggling to work with British National Grid, projection problems and crashing, even after installing suggested file

### ISSUE THREAD

**Issue by Snowdaisy** [qgis/QGIS#36739]
## User Feedback

QGIS Bucaresti doesn't work with British National Grid, it suggested to download and install a file to resolve the projection / transformation issue but its still not working. Initally added OSM and then tried to change CRS to BNG but it wouldnt work. Any help welcome, have seen similar issues discussed here  for 3.10 A Coruna so it may be repeating..

## Report Details

**Crash ID**: [188e441b487e48d0ebd7d07fe63c7c16edf44e05](https://github.com/qgis/QGIS/search?q=188e441b487e48d0ebd7d07fe63c7c16edf44e05&type=Issues)

**Stack Trace**
<pre>
QWidget::actions :
QMenu::clear :
QgisApp::refreshProfileMenu qgisapp.cpp:2986
QMetaObject::activate :
QMetaObject::activate :
QFileSystemWatcher::`default constructor closure' :
QMetaObject::activate :
QFileSystemWatcher::directoryChanged :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
QMessageBox::showEvent :
QMessageBox::critical :
QgisApp::QgisApp qgisapp.cpp:853
main main.cpp:1354
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.12.2-Bucure?ti
QGIS code revision: 8a1fb33634
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment]
@Snowdaisy please add **detailed** steps to replicate the issue.

**Comment by rouault** [comment]
> please add **detailed** steps to replicate the issue.

yes. Does the crash happen just at the moment when you validate the file in the file selection dialog ?

**Comment by nyalldawson** [comment]
Please test with 3.12.3 too -- there's been related changes which may impact this

**Comment by Snowdaisy** [comment]
Hi Both thanks for responding, sorry I'm not technical enough to understand a lot of this and it took up a lot of time so I uninstalled Bucaresti and went back to 3.10 ltr coruna and it's working for me. As above I installed it, played with Irish itm files fine, then opened a new file to use for bng, first used quick maps plugin to load osm but hadn't set csr yet. Then tried to set osm CSR to bng and it came up with lots of error warnings and ended up off west Africa, tried to install suggested file, then tried a few more times, could not figure it out, as I recall unknown projection was an issue at one point

**Comment by nyalldawson** [comment]
Not much to go on here -- I suggest we close unless it can be reproduced in >=3.12.3

**Comment by Snowdaisy** [comment]
Thank you all for your help!
Kind regards
Sinéad
