### ISSUE TITLE
Make the labels "edit rule" widget a real dialog with buttons

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#36761]
Labels --> rule-based labeling, double-click to edit the rule.
You get this (ignore the yellow):
![image](https://user-images.githubusercontent.com/7983394/82980787-93db2e00-9fea-11ea-9f0f-7ba8da289ffd.png)
It would be nice to have a real dialog (like when editing rule-based symbology) with:
- a cancel button (and that would catch the Esc shortcut)
- and a help button to link to doc. For reference the Url would be "working_with_vector/vector_properties.html#rule-based-labeling"

4ddce03f

**Comment by elpaso** [comment]
@DelazJ is this a bug? It seems more like an enhancement to me.

**Comment by DelazJ** [comment]
hmm... Actually, part of this is a regression, happened when we switched from modal dialogs to embedded widgets in properties, as you can see in the figure labels 8 at https://docs.qgis.org/2.14/en/docs/user_manual/working_with_vector/vector_properties.html#rule-based-labeling

**Comment by Pedro-Murteira** [comment]
This is still the case with QGIS 3.16.15 and 3.22.2.
