### ISSUE TITLE
Add setting to NOT ask to close project with memory layers

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS#36763]
Nowadays I work extensively with memory layers, also in plugins. 
I know those are temporary scratch layers, but I'm forced to click 'yes' everytime I want to (re)start QGIS because of this window:

![Screenshot-20200527095024-502x145](https://user-images.githubusercontent.com/731673/82992597-a7dd5a80-9fff-11ea-8ae8-799be74dc520.png)

I have searched in settings if I could disable this, but could not find any setting for that. 

To me it would be nice to have it, though it is not clear to me where to put it... because my temp layers (OR layers I put in /tmp) are often created via PyQGIS, I would not favour the create memory dialog.

I think the Settings/General/Project Files is the best place?

![Screenshot-20200527095420-1144x437](https://user-images.githubusercontent.com/731673/82992869-0c98b500-a000-11ea-821b-eaf2496c3b32.png)

**Comment by andreasneumann** [comment]
Would it make sense on the project level? Or globally for every project?

I guess for you @rduivenvoorde you probably need this "globally", but for others it might be better project wise, e.g. for a project with a lot of analysis stuff going on, you would disable the prompt, but for other projects maybe not. Not sure ...

**Comment by Gustry** [comment]
If your layers are coming from PyQGIS, you can do:
```python
iface.activeLayer().setCustomProperty("skipMemoryLayersCheck", 1)
```
QGIS will not check this layer when closing the project.

**Comment by rduivenvoorde** [comment]
I thought to 'fix' this for my build:

There is already a setting: https://github.com/qgis/QGIS/blob/master/src/app/qgisapp.cpp#L12794

**Comment by nyalldawson** [comment]
There's already an advanced setting for this -- I don't think we should expose this outside of the advanced tab.

**Comment by rduivenvoorde** [comment]
@nyalldawson I think I agree with you (only in advanced tab), now I can set it in code for a layer.
It is just that I could not find it by searching 'memory' or so.
And even looking for 'askToSaveMemoryLayers' does not give results?

**Comment by rduivenvoorde** [comment]
@nyalldawson it looks like askToSaveMemoryLayers is never 'set' but only 'read' (so I can set them via Python, but default they have no value, and do not appear in my setting.ini file?). Not sure if this is with more settings, but should we not inititalize such settings in some central place during startup to the most sensible values? Else these are 'hidden' options?

**Comment by nyalldawson** [comment]
@rduivenvoorde Ah - I think you should consider adding this to the settings ini template file. That should make it appear in the settings using a default value.
