### ISSUE TITLE
QGis don't achieve charging a project in QField

### ISSUE THREAD

**Issue by CCMRayot** [qgis/QGIS#36767]
h2. User Feedback

h2. Report Details

*Crash ID*: 9cdb23784556447a139921d451d9a6ecf9638b1c

*Stack Trace*
<pre>
QgsVectorLayerJoinInfo::joinFieldNamesSubset :
QgsVectorLayerJoinBuffer::writeXml :
QgsVectorLayer::writeXml :
QgsMapLayer::writeLayerXml :
QgsProject::writeProjectFile :
QgsProject::write :
PyInit__core :
PyCFunction_FastCallDict :
PyObject_GenericGetAttr :
PyEval_EvalFrameDefault :
PyObject_GenericGetAttr :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyObject_CallFunctionObjArgs :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.2.3-Bonn
QGIS code revision: commit:9b176802e5
Compiled against Qt: 5.9.2
Running against Qt: 5.9.2
Compiled against GDAL: 2.2.4
Running against GDAL: 2.2.4

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment]
>  QGIS Version: 3.2.3-Bonn

@CCMRayot too old, upgrade to 3.10 or 3.12

and if this is a problem with QField (you **must** describe in **detail** the issue and how replicate it) you must report to in the QField tracker not here.

**Comment by m-kuhn** [comment]
@CCMRayot as @gioman mentionned, please update to a currently supported version. If this problem is not solved, please open an issue at https://github.com/opengisch/qfieldsync/issues
