### ISSUE TITLE
Problem installing QGIS in windows 

### ISSUE THREAD

**Issue by kalliopikout** [qgis/QGIS#36779]
Hello,

I am having an issue installing QGIS on my windows 10 machine. It used to be finely installed, but due to some reasons I had to uninstall.
It has to do with older (2.16) and newer versions (3.0,3.10..).
I am getting a dll related error as you can see in the image attached.

Thanks in advance!
Kalliopi

![image](https://user-images.githubusercontent.com/45163034/83042508-03303c80-a042-11ea-897f-e85a9e36d965.png)

**Comment by gioman** [comment]
@kalliopikout for support please write in the users or developers mailing lists, the QGIS IRC channe of gis.stackexchange. This facility is only to report bugs or file feature requests, thanks!

**Comment by kalliopikout** [comment]
> @kalliopikout for support please write in the users or developers mailing lists, the QGIS IRC channe of gis.stackexchange. This facility is only to report bugs or file feature requests, thanks!

Oh I am sorry!
Many thanks.
