### ISSUE TITLE
Random bug from QGIS

### ISSUE THREAD

**Issue by gaz0070** [qgis/QGIS#36782]
When I tried opeing a project at startup - QGIS froze, then generated error report as per below;

Crash ID: 5b7d7853716001199e29628e91df8bb8e06ddcdd

Stack Trace

QtSharedPointer::ExternalRefCountData::getAndRef :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1606
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.10.5-A Coru�a
QGIS code revision: 984615fe1e
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by Gustry** [comment]
You should try with a new QGIS profile.
Go in `Settings` -> `User Profile` -> `New profile`. Thanks.
It might be due to a plugin.

**Comment by gaz0070** [comment]
sweet thanks for the reply!!!!

 

Ill try that out
 

Gareth Payne
Geographer
Orchard Spatial
022 087 5287

 
 

Sent: Thursday, May 28, 2020 at 10:07 AM

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
