### ISSUE TITLE
UI Resize bug on freshly loaded postgres connexion (datasource manager)

### ISSUE THREAD

**Issue by ponceta** [qgis/QGIS#36794]
**Describe the bug**
After connecting to a PostgreSQL datasource, closing and reopening datasource manager leads to a resizing bug

**How to Reproduce**

![UI_PostgreSQL_datasource_manager](https://user-images.githubusercontent.com/8614223/83123244-fa3c7b00-a0d4-11ea-97ea-28d68b5387ee.gif)

1. Go to a PostgreSQL datasource
2. Click on connect
3. Close or add a layer and close
4. Reopen datasource manager

**QGIS and OS versions**

QGIS 3.10.6 / QGIS 3.12.3 / QGIS dev Nightly
Win 10 x64

**Additional context**

Comes to normal when clicking refresh, connect or resizing the datasource manager.

**Comment by elpaso** [comment]
I tried to fix this issue multiple times (and I cannot reproduce it anymore on my testing machines) but it seems it wasn't really fixed :(

**Comment by Pedro-Murteira** [comment]
I can no longer replicate this bug on QGIS 3.16.14 and 3.22.1 (Tested on Windows 10 and UBUNTU 20.04).
