### ISSUE TITLE
QgsAttributeTableModel loadAttributes Error

### ISSUE THREAD

**Issue by GISerliang** [qgis/QGIS#36790]
**Describe the bug**
In debug mode, crashed when adding one field of vectorlayer

**How to Reproduce**

## In Debug Mode
1. Add a vectorlayer, sucn as shp or postgis
2.Go to "edit mode"
3.Open Attribute Table
4.Add one field and click "OK"
![image](https://user-images.githubusercontent.com/11342604/83109365-dd637000-a0f3-11ea-9f91-aad1f128516f.png)

**Comment by rduivenvoorde** [comment]
Hi, I cannot reproduce this. I loaded a shp file, and add a new field 'kaas' with the button in red line:

But I do not see anything in the debug window.

![Screenshot-20200603194105-771x560](https://user-images.githubusercontent.com/731673/83669916-9df4c200-a5d2-11ea-8e33-74cedaaa8c8d.png)

What OS and QGIS version are you on?

Is it maybe possible to share a shapefile and describe exactly what you do to trigger this?
