### ISSUE TITLE
QGIS 3.12.2 on Windows 10 - crash after exporting selection

### ISSUE THREAD

**Issue by maspiers** [qgis/QGIS#36803]
## User Feedback

I'm not sure what caused this

## Report Details

**Crash ID**: [1aff05dc87b94e91cd85505b8e47c4eb3b5b1b51](https://github.com/qgis/QGIS/search?q=1aff05dc87b94e91cd85505b8e47c4eb3b5b1b51&type=Issues)

**Stack Trace**
<pre>
QWidget::mapTo :
QWidgetPrivate::moveRect :
QApplication::windowIcon :
QApplication::windowIcon :
QWidget::event :
QDockWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1608
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.12.2-Bucure?ti
QGIS code revision: 8a1fb33634
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment]
@maspiers please try with a new QGIS profile, no 3rd party plugins installed.

If the problem persist please add the **detailed** steps to replicate. Thanks.

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
