### ISSUE TITLE
Qgis 3.12 export composer high dpi not working

### ISSUE THREAD

**Issue by johansanders** [qgis/QGIS#36829]
**Describe the bug**
exporting print composer higher than 300 dpi to jpg , to pdf , to printer  always gives error on qgis 3.12 ; not on 3.8

sometimes memory allocation problem and crash
most of the time a blanc result
qgis 3.13 same problem

**on 3.8 no problem , exported 1600dpi without problems**

**Comment by gioman** [comment]
@johansanders operating system? please attach a sample project+data. Thanks

**Comment by johansanders** [comment]
windows10  64 bit 16GB mem 
the project is a mix of shp , gpkg and tif 

qgis 3.8 works impecable, 3.12  and dev version have this problem
vectorized or rasterized no difference

**Comment by e5k** [comment]
Hi all,

Got a similar problem, let me know if you want me to move it as a new issue. I need to export a map for a very large print (~4.5 m), but exporting it at a resolution larger than 1200 dpi crops the output (see attached). Same behaviour on both 3.4 and 3.12. Mid 2018 MBP, 8GB Ram. Project is shp and tif.

Thanks!

PS: I used a custom projection centred on 150E. The attached screenshot gives the impression that the output is cropped at this meridian, but this is just a coincidence. Other attempts have seen the image cropped both before and after this meridian.

<img width="419" alt="Screenshot 2020-06-02 at 8 37 45 AM" src="https://user-images.githubusercontent.com/16320236/83467740-63ddd000-a4ad-11ea-88da-ab5d453cd47e.png">

**Comment by gioman** [comment]
@johansanders @e5k can a sample project (and data) be provided?
