### ISSUE TITLE
Core dump if vector tile layer (file) becomes unavailable

### ISSUE THREAD

**Issue by saberraz** [qgis/QGIS#36821]
To recreate:
1- Open QGIS
2- Add a vector tile file (e.g. mbtile)
3- While the file is open in QGIS, rename or delete the file
4- Causes core dump in QGIS

**Comment by pblottiere** [comment]
Hi @saberraz,

I tried to reproduce the core dump on Archlinux without success. Instead I have a gently error message in my terminal:

```
ERROR 4: /home/pblottiere/Downloads/world_countries_2.mbtiles: No such file or directory
```
