### ISSUE TITLE
gpkg query layers not working with line break after select

### ISSUE THREAD

**Issue by m-kuhn** [qgis/QGIS#36825]
When a query is written in db manager against a GeoPackage and there is a line break directly after the `select`, the preview of the query loads fine. But if it's loaded as a query layer it's empty (no rows) and the column headers do not correspond to the selected fields (they seem to be taken from a different table in the same gpkg).

Broken query:

```
select
*
from
boflaeche;
```

Working query:

```
select *
from
boflaeche;
```

Affects Windows, could not reproduce on Linux.
QGIS 3.10.6 and 3.12.3

**Comment by gioman** [comment]
@m-kuhn "broken" means 0 results or error?

**Comment by m-kuhn** [comment]
>  if it's loaded as a query layer it's empty (no rows) and the column headers do not correspond to the selected fields

**Comment by gioman** [comment]
then this is similar to https://github.com/qgis/QGIS/issues/36205

and I argue that this is a **very dangerous** bug, as it can lead a very wrong, real life, decisions.

**Comment by m-kuhn** [comment]
Followup test:

the project configured on windows and then opened on linux (Fedora 31, qgis 3.10) also shows the "broken" behavior.

**Comment by m-kuhn** [comment]
qgs file:

broken (win 3.10) `select <br> * ...`
```
<datasource>./daen_dm01avch24lv95d.gpkg|layerid=0|subset=select&#xd; *&#xd; from&#xd; boflaeche</datasource>
```

working (win 3.10) `select *<br> ...`
```
<datasource>./daen_dm01avch24lv95d.gpkg|layerid=0|subset=select *&#xd; from&#xd; boflaeche</datasource>
```

working (linux master) `select <br> * ...`
```
<datasource>./daen_dm01avch24lv95d.gpkg|layerid=0|subset=select * from boflaeche</datasource>
```
