### ISSUE TITLE
QGIS 3.12 unknown CRS or Select Transformation

### ISSUE THREAD

**Issue by yhan27** [qgis/QGIS#36837]
**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

<It appears that QGIS 3.12 has an issues with CRS identification. When I add an image (tif, UTM zone) to the canvas, it always asks me to select transformation, and the image's CRS can not be recognized either so it is shown as unknown CRS. This problem does not happen with early version of QGIS like 3.4 when adding the same image file. Any thought? TIA.>

**Comment by rouault** [comment]
Please attach the image. That have been very recent fixes in QGIS and in GDAL (3.1) related to that

**Comment by yhan27** [comment]
![unknown CRS](https://user-images.githubusercontent.com/66029267/83315052-234b3180-a1e3-11ea-97f9-16cf5ccd5322.JPG)
![select transformation](https://user-images.githubusercontent.com/66029267/83315056-280fe580-a1e3-11ea-8473-c56fd5815764.JPG)
![select transformation_ballpark](https://user-images.githubusercontent.com/66029267/83315060-29d9a900-a1e3-11ea-982f-3db94f49ddf7.JPG)

**Comment by rouault** [comment]
I meant to attach the GeoTIFF file or provide a link where to download it, not a screenshot of QGIS.

**Comment by yhan27** [comment]
https://data.tnris.org/collection/b5bd2b96-8ba5-4dc6-ba88-d88133eb6643

and 
https://data.tnris.org/collection/f1d66250-4021-47df-9fe9-9fca286b0f50

Pick an area new Houston. Thanks.

**Comment by rouault** [comment]
Those are actually ERDAS Imagine (.img) files, not GeoTIFF, but I confirm the issue. Fix underway in GDAL
