### ISSUE TITLE
Gereferencer tool missing

### ISSUE THREAD

**Issue by tm-umons** [qgis/QGIS#36841]
**Describe the bug**

Georeferencer tool is missing in the raster menu.

**How to Reproduce**

Click on Raster 
Georeferencer tool is missing

**QGIS and OS versions**

QGIS 3.12.3
Windows 7 SP1 (6.1)

**Additional context**

I don't have this issue with Windows 10

**Comment by pigreco** [comment]
The georeferencer is a plugin and must be activated.

Go to Plugin Management and activate it

![image](https://user-images.githubusercontent.com/7631137/83337882-54992f80-a2bf-11ea-93cd-74b03f77aa36.png)
