### ISSUE TITLE
GRASS file problem with vector in QGIS 3.10.6 with GRASS 7.8.3 

### ISSUE THREAD

**Issue by simone100** [qgis/QGIS#36848]
I show two bugs that I assume they are srongly connected and derived from a common problem.

The version is always the same, namely

**QGIS and OS versions**
QGIS Info
QGIS Version: 3.10.6-A Coru�a
QGIS code revision: ec80021f49
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Describe the bug I**
I open the mapset with the Alaska (but the problem appears even for all other GRASS file with vector) sample training dataset (qgis.org/downloads/data/qgis_sample_data.zip) in the browser panel. I add the GRASS vector to the layers panel and I try to open the attribute table. Unfortunately QGIS always crash with the following message:

**How to Reproduce I**
1. Create a location and mapset and open the mapset in the browser panel
2. Double click on the GRASS vector of the mapset----the grass vector open in the layers panel
3. open the attribute table of the GRASS vector
4. Crash appears: Crash ID: bad343f454b7fa597fcf9b7edefb29273cd290c2

Stack Trace
QTextCodec::toUnicode :
QgsGrassFeatureIterator::setFeatureAttributes qgsgrassfeatureiterator.cpp:711
QgsGrassFeatureIterator::setFeatureAttributes qgsgrassfeatureiterator.cpp:680
QgsGrassFeatureIterator::fetchFeature qgsgrassfeatureiterator.cpp:508
QgsAbstractFeatureIterator::nextFeature qgsfeatureiterator.cpp:63
QgsVectorLayerFeatureIterator::fetchFeature qgsvectorlayerfeatureiterator.cpp:416
QgsAbstractFeatureIterator::nextFeature qgsfeatureiterator.cpp:63
QgsCachedFeatureWriterIterator::fetchFeature qgscachedfeatureiterator.cpp:141
QgsAbstractFeatureIterator::nextFeature qgsfeatureiterator.cpp:63
QgsVectorLayerCache::setFullCache qgsvectorlayercache.cpp:107
QgsDualView::initLayerCache qgsdualview.cpp:340
QgsDualView::init qgsdualview.cpp:128
QgsAttributeTableDialog::QgsAttributeTableDialog qgsattributetabledialog.cpp:185
QgisApp::attributeTable qgisapp.cpp:7767
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QMenu::exec :
QgsLayerTreeView::contextMenuEvent qgslayertreeview.cpp:152
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1606
BaseThreadInitThunk :
RtlUserThreadStart 

**Describe the bug II**
I open the mapset with the Alaska (but the problem appears even for all other GRASS vector) sample training dataset in the browser panel. I right click on the GRASS vector and I click "layer properties". It opens a windows with "metadata/preview/attributes". When I click on attributes QGIS crashes. 

**How to Reproduce II**
1. Create a location and mapset and open the mapset in the browser panel
2. Right click on the GRASS vector of the mapset and click on layer properties. Then click on attributes in the opened windows
4. Crash appears: Crash ID: 59308c1e2617cde8905d1ba28c2dc68e1c3a85c7

Stack Trace
QTextCodec::toUnicode :
QgsGrassFeatureIterator::setFeatureAttributes qgsgrassfeatureiterator.cpp:711
QgsGrassFeatureIterator::fetchFeature qgsgrassfeatureiterator.cpp:504
QgsAbstractFeatureIterator::nextFeature qgsfeatureiterator.cpp:63
QgsVectorLayerFeatureIterator::fetchFeature qgsvectorlayerfeatureiterator.cpp:416
QgsAbstractFeatureIterator::nextFeature qgsfeatureiterator.cpp:63
QgsCachedFeatureWriterIterator::fetchFeature qgscachedfeatureiterator.cpp:141
QgsAbstractFeatureIterator::nextFeature qgsfeatureiterator.cpp:63
QgsAttributeTableModel::loadLayer qgsattributetablemodel.cpp:462
QgsBrowserLayerProperties::loadAttributeTable qgsbrowserdockwidget_p.cpp:282
::operator() qgsbrowserdockwidget_p.cpp:161
QMetaObject::activate :
QTabWidget::~QTabWidget :
QMetaObject::activate :
QTabBar::setCurrentIndex :
QTabBar::mousePressEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1606
BaseThreadInitThunk :
RtlUserThreadStart :

**Comment by gioman** [comment]
@simone100 similar (duplicated?) to https://github.com/qgis/QGIS/issues/35344

**Comment by simone100** [comment]
> @simone100 similar (duplicated?) to #35344

@gioman is similar because the problem also happen with vector, but it is different because he cannot add. I can, but I cannot work with the attribute table or field.
