### ISSUE TITLE
[expression] relation_aggregate has no filter option but order_by

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#36842]
Error is present in 3.10, 3.12 and in the master

![image](https://user-images.githubusercontent.com/7631137/83337293-63311800-a2ba-11ea-87a9-bf7bf3ee259b.png)

https://github.com/qgis/QGIS/blob/master/resources/function_help/json/relation_aggregate#L10

**Comment by DelazJ** [comment]
Duplicate #32702?

**Comment by pigreco** [comment]
> Duplicate #32702?

exact,
it would be enough to change `filter` with `order_by`

**Comment by pigreco** [comment]
Grazie mille @agiudiceandrea
