### ISSUE TITLE
Vector tile disappears when zoom level is more than max zoom in data

### ISSUE THREAD

**Issue by saberraz** [qgis/QGIS#36862]
I have a vector tile layer with maximum zoom level of 7. If I zoom in the map canvas more than 7, the features disappear.

The correct behaviour should be to magnify the last zoom level (in this case 7) of the features for any map canvas zoom levels more than the maximum zoom level in data.
![Peek 2020-06-01 10-55](https://user-images.githubusercontent.com/2649047/83398024-7e08a700-a3f6-11ea-9803-1e3df289e731.gif)
[switzerland.mbtiles.zip](https://github.com/qgis/QGIS/files/4710622/switzerland.mbtiles.zip)

**Comment by saberraz** [comment]
This is due to the wrong max zoom level in the maptiles (14 instead of 7).

**Comment by wonder-sk** [comment]
Can we close this?

**Comment by saberraz** [comment]
Yeah...a problem with the mbtiles metadata.
