### ISSUE TITLE
BIGTIFF error is not obvious in processing log

### ISSUE THREAD

**Issue by baswein** [qgis/QGIS#36867]
**Describe the bug**

When running an algorithm that produces a tiff that is greater than 4GB an error is created in the log stating that BIGTIFF=YES must be used but the algorithm continues and switches back to the Parameters tab after finishing as would be expected in an error free run. While this is usually obvious because the resulting tiff will be missing parts there are many cases where it wouldn't be caught.  

**How to Reproduce**
Run an algorithm that produces a TIFF that is greater that 4GB and observe log. (I'm not sure if you also need to change the desired compression from the default or not as it seems like this https://github.com/qgis/QGIS/issues/13496 would have set BIGTIFF to be used if needed in default)

Error in log: 
![image](https://user-images.githubusercontent.com/15817745/83433435-5a019180-a407-11ea-83ac-50c0bbb3c5e9.png)

Report at bottom of log:
![image](https://user-images.githubusercontent.com/15817745/83433637-6c7bcb00-a407-11ea-93df-ba9979cc4aac.png)

**QGIS and OS versions**

QGIS version
3.12.2-București
QGIS code revision
8a1fb33634
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.1
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
DataPlotly; 
GroupStats; 
pickLayer; 
PluginLoadTimes; 
processing_r; 
quick_map_services; 
toolbargenerator; 
workbench; 
db_manager; 
processing

**Additional context**

**Comment by gioman** [comment]
@baswein I think is more a feature request.

**Comment by rouault** [comment]
@baswein Is it the "Clip Raster by extent" algorithm ? This uses gdal_translate undernearth, right ? It might be a defect of it since it should normally return an error rather than complete to 100%

**Comment by baswein** [comment]
@gioman You would know better than me- I'm fine with it being a feature request. 
@rouault It is the GDAL Raster calculator. It just tripped me up for a minute and I wanted to let people know. Thanks! 
![image](https://user-images.githubusercontent.com/15817745/83441342-5fb1a400-a414-11ea-8614-bbc3f6d249fe.png)

**Comment by rouault** [comment]
The issue was in gdal_calc.py itself. Now fixed

**Comment by baswein** [comment]
@rouault You're amazing! Thanks!

**Comment by baswein** [comment]
@rouault 
I am having a similar result with the GDAL Raster Calculator when I run out of disc space. It may be that this was also fixed when you fixed the other issue. Just thought you should know. 
![image](https://user-images.githubusercontent.com/15817745/85037556-892c3880-b153-11ea-967d-2dbea23b4a26.png)
![image](https://user-images.githubusercontent.com/15817745/85037576-8f221980-b153-11ea-91c2-ee7e66b710fa.png)
If you want me to open up another issue I would be happy to.

**Comment by rouault** [comment]
>  It may be that this was also fixed when you fixed the other issue

yes, the isuse was in gdal_calc.py used by both algorithms

**Comment by baswein** [comment]
Perfect- Thanks!
