### ISSUE TITLE
Freeze when editing vertices while different group is selected in browser

### ISSUE THREAD

**Issue by qu4ntumrush** [qgis/QGIS#36868]
Crash ID: 74bd6b3268a19524b17f72ae16d0c53418f883c8

Stack Trace

QMetaObject::disconnect :
QObject::disconnectImpl :
QgsVertexTool::setHighlightedVertices :
QgsVertexTool::onCachedGeometryDeleted :
QMetaObject::activate :
QgsVectorLayer::featureDeleted :
QMetaObject::activate :
QgsVectorLayerEditBuffer::featureDeleted :
QgsVectorLayerEditBuffer::commitChanges :
QgsVectorLayer::commitChanges :
QgisApp::saveActiveLayerEdits :
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.12.0-Bucure?ti
QGIS code revision: cd141490ec
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
@qu4ntumrush please add **exact** steps to replicate, Please also try with a new QGIS profile. Also update to the latest 3.12, 3.12.o is too old.

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
