### ISSUE TITLE
Add texture shading algorithms to the processing toolbox

### ISSUE THREAD

**Issue by saberraz** [qgis/QGIS#36869]
I came across this set of algorithms which create texture shading:
https://app.box.com/v/textureshading/folder/122668213

Here are some examples:
http://www.shadedrelief.com/texture_shading/

The code appears to be under BSD:
https://app.box.com/v/textureshading/file/540913016576

**Comment by nyalldawson** [comment]
Probably a better candidate for a 3rd party plugin?

**Comment by saberraz** [comment]
Could be a 3rd party plugin...if we don't want to clutter the processing toolbox with more python algorithms :)

**Comment by nyalldawson** [comment]
> if we don't want to clutter the processing toolbox with more python algorithms

Definitely. Given that it's pure python (so can be a plugin), is of limited appeal, and is quite complex, I would much rather it was a 3rd party-maintained functionality.

(I'd also love to see it happen though!)
