### ISSUE TITLE
Winkel Tripel projection - high geometry simplification at low scale

### ISSUE THREAD

**Issue by domlysz** [qgis/QGIS#36898]
**Describe the bug**

When using the Winkel Tripel projection at low scale, feature are displayed as simplified tetragone instead of full geometry. Screenshoots bellow :

![image](https://user-images.githubusercontent.com/5639024/83495572-26cb0b00-a4b8-11ea-85b9-43a272e61292.png)

![image](https://user-images.githubusercontent.com/5639024/83495608-32b6cd00-a4b8-11ea-90cf-6b77358f191b.png)

**How to Reproduce**

- Load a world dataset like [Natural Earth](https://www.naturalearthdata.com/)
- set up the project's projection to Winkel Tripel (EPSG 54042)
- zoom back to see the whole world in the map window and the geometry simplification will appears

**QGIS and OS versions**

QGIS 3.13, GDAL 3.2, PROJ 7.1, bug appears both on Windows and Linux

**Additional context**

**Comment by gioman** [comment]
@domlysz 

layer properties > rendering > simplify geometry (to disable)

**Comment by domlysz** [comment]
that's it ! sorry to annoy the team with an invalid bug report.

Have a nice day

**Comment by nirvn** [comment]
I don't know that this is not a bug here. Disabling the simplification is merely a workaround to not suffer from what appears to be a bug here. 

@nyalldawson , thoughts?

**Comment by nyalldawson** [comment]
I think it's a bug -- we should automatically disable the simplification when this situation occurs
