### ISSUE TITLE
Layout editor window does not remember position and size

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#36907]
**Describe the bug**
The Layout editor window (where you can add a map, legend, etc to blank pages) does not remember its position or size. This can be quite annoying if you have to resize it every time you open it.

**How to Reproduce**

1. Create a new layout
2. Move the Layout editor window somewhere and scale it as you like
3. Close the Layout editor window
4. Open the layout again
5. Notice how the window is not where you put it nor how you scaled it

**QGIS and OS versions**

QGIS version | 3.10.0-A CoruÃ±a | QGIS code revision | 6c816b4204
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Windows 10 (10.0)

**Comment by gioman** [comment]
> 3.10.0-A CoruÃ±a

@kannes this is too old, please test also on the latest 3.10 available.

**Comment by kannes** [comment]
Same behaviour in a version from ~six weeks ago.

QGIS version | 3.13.0-Master | QGIS code revision | af1576a431
-- | -- | -- | --
Compiled against Qt | 5.14.2 | Running against Qt | 5.14.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.32.1
PostgreSQL Client Version | 12.2 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.4
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Arch Linux

**Comment by kannes** [comment]
Thank you @nyalldawson <3
