### ISSUE TITLE
Layout: tickmarks and labels in map frame should be rotated

### ISSUE THREAD

**Issue by andreasneumann** [qgis/QGIS#36904]
**Bug description.**
In a layout, if a frame is activated and uses tickmarks (interior, exterior or both) and the map is rotated, the tick marks and the "draw coordinate" labels should be rotated in sync with the rotation of the coordinate crosses or grid lines.

![grafik](https://user-images.githubusercontent.com/884476/83517934-0ca22480-a4da-11ea-9965-5ad9bf50ed53.png)

Not sure if this can be regarded as a bug or feature request.

Questions: are there cases where the tick marks shouldn't be rotated? If yes, then we'll need an option, but the rotation should be enabled by default.

For the "draw coordinate" labels there should be an option to rotate them or not.

**Comment by olivierdalang** [comment]
@andreasneumann 
I started working on this.

A few questions/comments :

1. IMO it's better to have an option to not rotate ticks, as in some cases it doesn't look good (e.g.  with solid grid lines)

2. There's two ways to draw rotated ticks, either using an "orthogonal size" (e.g. ticks get longer when with a low angle to the frame, to respect orthogonal alignment) or using a "normalized size" (all ticks have the same length, so they don't align orthogonaly). Code-wise it's trivial, but I'm not sure if this deserves yet another option for already complex map grid dialog or if we can just pick the one that we think is best (in which case : which one do we think is best :-) ?).

3. Currently, it's possible to choose "latitude only" or "longitude only" for each border. However, with rotated maps, it would be even better to be able to hide ticks below a certain angle. For instance, displaying ticks for grid lines that intersects the frame with a very low angle (almost parallel to the frame) isn't very helpful nor beautiful. By default, I'd hide ticks at < 30°. This is not really part of this issue, but would improve rotated maps.


### screenshots

"normalized tick length"
![image](https://user-images.githubusercontent.com/1894106/83553265-417a9f80-a50b-11ea-8e66-7bbb51938380.png)

"orthogonal tick length"
![image](https://user-images.githubusercontent.com/1894106/83553376-65d67c00-a50b-11ea-83e7-b93300080829.png)

**Comment by andreasneumann** [comment]
Good question. In general I like the second variation (orthogonal tick length) because all tickmarks end at one line, but in case of very flat (small) angles), the very long lines may also look a bit ugly. But as I understand your comment 3, such very long ticks at flat angles could be suppressed. That would look prettier, I agree.

About coordinate labels: I think that the labels should be aligned at the end of the ticks and  not at their beginning at the map border. But that was not the question here - would you also agree on that?

**Comment by edigonzales** [comment]
@andreasneumann See attached files. These are examples from our surveyors.
[Situationsplan_beglaubigt_75119.pdf](https://github.com/qgis/QGIS/files/4728134/Situationsplan_beglaubigt_75119.pdf)
[GB-Plan-Auszug hoch.pdf](https://github.com/qgis/QGIS/files/4728136/GB-Plan-Auszug.hoch.pdf)
[GB-Plan-Auszug quer.pdf](https://github.com/qgis/QGIS/files/4728137/GB-Plan-Auszug.quer.pdf)

**Comment by andreasneumann** [comment]
Thanks @edigonzales  - we need to cover both cases: exterior and interior ticks

Although we (Kt. Solothurn) probably need primarily need the interior ticks. @olivierdalang please make sure that we can mimic the interior ticks incl. the labels as @edigonzales uploaded the PDF examples.

**Comment by gislars** [comment]
I was just about opening a similar issue about aligning the grid label with a rotated grid. When you use internal labeling the grid labels should have the same rotation as the grid lines.
With QGis 3.10.6 i can only choose between horizontal or vertical label

Is this covered by this issue or should I open a new one?
![qgis_print_grid_label](https://user-images.githubusercontent.com/402166/83738498-aa216380-a654-11ea-9f10-eb49237071b5.png)

**Comment by andreasneumann** [comment]
This ticket should also cover label rotation - thanks for mentioning the other ticket! We would welcome your testing and feedback on this one @gislars once it is in master.

**Comment by andreasneumann** [comment]
@olivierdalang - since this landed in master now, I'm testing it.

In general I am really happy with the results, but there are some issues - do you want me to comment here or open new issues?

It is mainly about avoiding:
- partial draw of labels (clipped off at the map edge). I'd like them to either draw fully or not at all. See
![image](https://user-images.githubusercontent.com/884476/89548711-a7372080-d807-11ea-92a0-84d8e4dbc459.png)

- overlapping labels (can we do something to avoid this?) See
![image](https://user-images.githubusercontent.com/884476/89548797-c3d35880-d807-11ea-9db9-1962b60a2578.png)


Sometimes there are also "redraw" issues. If I click outside of the layout window, labels are often drawn beyond the map frame and then, because they are drawn "outside", they naturally don't refresh/redraw properly, because QGIS (or qt?) thinks it only has to repaint the map frame and not beyond. I can record a movie to demonstrate this.

**Comment by gislars** [comment]
I gave it a new try since it is in master branch now.

- test based on current master
- I'll attach a PDF wich shows a grid on different places on on earth using the atlas feature. The rotation is random.
- I was able to adjust the ticks and label parameter in a way that no overlapping of label occur, but only for one or very few places the same time. Not for all places.
- A frame with exterior/interior ticks has no border, not sure if it should have one. But it can be added with a second grid.

[grid_label_test.pdf](https://github.com/qgis/QGIS/files/5048297/grid_label_test.pdf)

these are the settings used in my test:
![Bildschirmfoto vom 2020-08-09 21-30-06](https://user-images.githubusercontent.com/402166/89740559-03a97280-da8a-11ea-95a9-4dc4399f5b5c.png)

Not really related but an interesting combination: 
I saw https://github.com/qgis/QGIS/pull/38024 and was curios if an non-rectangular form of the map would also apply to the grid. So I tried current master but the grid isn't effected by the clipping.
![Bildschirmfoto vom 2020-08-09 21-52-28](https://user-images.githubusercontent.com/402166/89740628-aeba2c00-da8a-11ea-90e7-871557691504.png)

**Comment by olivierdalang** [comment]
@andreasneumann 
I opened PR https://github.com/qgis/QGIS/pull/38524 with a proposed fix for these issues. Please let me know there what you think of the implementation. I'll close this issue for now, and we can reopen separate issues if some new issues arise linked to rotated ticks.

@gislars 
Thanks again for the extensive testing. It's expected that exterior/interior ticks don't show the border, for which you can just use a regular map item border.

And indeed it would be great if grids respected non-rectangular layouts. If this is useful to you, I'd suggest opening another feature request, as it's a bit a different feature.
