### ISSUE TITLE
Layouts: draw coordinates should allow background rectangles or buffers

### ISSUE THREAD

**Issue by andreasneumann** [qgis/QGIS#36906]
**Feature description.**
In print layouts, when "draw coordinates" is activated, there should be an option to add background rectangles or buffers (oriented automatically with the "draw coordinate" labels --> see also #36904 ), to make the coordinates more legible against the map content.

In order to avoid situations like here:
![grafik](https://user-images.githubusercontent.com/884476/83519681-b97da100-a4dc-11ea-8146-6723d98d5001.png)

Ultimately, it would be nice to enable selective masking to mask only dark symbol levels of the map content, but as a starter, background rectangles or buffers would be good enough. Selective masking in layouts interacting with map content might be too complex ...

**Comment by nyalldawson** [comment]
The solution here is to port the annotation drawing to QgsTextRenderer -- then we get the ability to put shadows, buffers, backgrounds, even HTML coloring in the grid labels.

I've tried this a few times in the past (see .e.g https://github.com/nyalldawson/QGIS/commit/06ab6a7a6d18fc100f7e6fa060ed631b70a64ec6 ), but I've never got the text position a suitable match for the existing text placement... hoping that one day I'll get the chance to revisit this again!

**Comment by olivierdalang** [comment]
Just merged your branch, it work well ! You seem to have a reservoir of great commits hidden in your fork :-)

I'm working on the text placement in #37041 and will include your patch in that PR too.

**Comment by nyalldawson** [comment]
> Just merged your branch, it works well ! You seem to have a reservoir of great commits hidden in your fork

My fork is a graveyard of half finished ideas I'll get back to "some time" 😁

**Comment by andreasneumann** [comment]
@olivierdalang - I think this issue is solved now - isn't it?

I think we can close this one.
