### ISSUE TITLE
Saving and reloading a vector layer from QGIS loses position

### ISSUE THREAD

**Issue by pietervdvn** [qgis/QGIS#36912]
Hey,

I have a project where I created some points based on a geojson file (which in turn came from overpass-turbo).
I dragged this in QGIS, save the project. When reopening the project, the location of all the points is around null island.

Please find an example project + data in [BugReport.zip](https://github.com/qgis/QGIS/files/4719225/BugReport.zip)

An example workflow in a very low quality gif:
![QGIS-Bug](https://user-images.githubusercontent.com/1466478/83560998-62e18880-a517-11ea-9709-52fb5413e8ff.gif)

I'm working on Kubuntu 19.04, QGIS info below:

QGIS version | 3.8.1-Zanzibar | QGIS code revision | dcd95cc648
-- | -- | -- | --
Compiled against Qt | 5.12.2 | Running against Qt | 5.12.2
Compiled against GDAL/OGR | 2.4.0 | Running against GDAL/OGR | 2.4.0
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
PostgreSQL Client Version | 11.4 (Ubuntu 11.4-0ubuntu0.19.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.10.4
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Ubuntu 19.04 |   |  

Feel free to reach out for more questions.

**Comment by Gustry** [comment]
> 3.8.1-Zanzibar

This is too old. Please update your QGIS to latest 3.10 or 3.12.

**Comment by uclaros** [comment]
Your points are in WGS84 (EPSG:4326) and the OSM tiles are in EPSG:3857 but your project has no CRS defined. Setting the project CRS to either of the two (right click on layer -> Set CRS -> Set project CRS from layer) or any other CRS actually, should cure your issue!

**Comment by gioman** [comment]
> Your points are in WGS84 (EPSG:4326) and the OSM tiles are in EPSG:3857 but your project has no CRS defined. Setting the project CRS to either of the two (right click on layer -> Set CRS -> Set project CRS from layer) or any other CRS actually, should cure your issue!

indeed.

**Comment by uclaros** [comment]
Actually, the project should have EPSG:3857 stored, as it's the CRS of the first layer added (that's why it is working correctly on the screencast before closing QGIS). Also, in the qgs file inside the qgz there is a section :
```
  <projectCrs>
    <spatialrefsys>
      <proj4>+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs</proj4>
      <srsid>3857</srsid>
      <srid>3857</srid>
      <authid>EPSG:3857</authid>
      <description>WGS 84 / Pseudo-Mercator</description>
      <projectionacronym>merc</projectionacronym>
      <ellipsoidacronym>WGS84</ellipsoidacronym>
      <geographicflag>false</geographicflag>
    </spatialrefsys>
  </projectCrs>
```
but when opening in QGIS the project has no CRS.
So there probably was a bug somewhere, but already fixed; I cannot reproduce it in master.

**Comment by pietervdvn** [comment]
Setting the project CRS from a layer indeed works. Thanks for the help!
