### ISSUE TITLE
Crash when exporting PDF

### ISSUE THREAD

**Issue by ValentinSastre** [qgis/QGIS#36927]
I've designed a layout for automating cartography generation using the Atlas tool. When I try to export in PDF format (either a single Atlas item or the whole Atlas) the software crashes (crash report below).

I don't have any problems when exporting in image format (png, jpg, etc.). Crashing only happens when exporting as PDF.

Crash report details:

> Crash ID: 58b8e3dca8ca21c11345ed757a0d925974a2ee3a
> 
> Stack Trace
> 
> DllGetClassObject : DllGetClassObject : DllGetClassObject : DllGetClassObject : DllGetClassObject : DllGetClassObject : DllGetClassObject : Ordinal273 : Ordinal273 : Ordinal273 : DocumentPropertySheets : Ordinal361 : DocumentPropertiesW : GdiCurrentProcessSplWow64 : ResetDCW : qt_plugin_query_metadata : QPrintDevice::printableMargins : QWin32PrintEngine::setGlobalDevMode : QWin32PrintEngine::updateMatrix : QWin32PrintEngine::globalDevMode : QWin32PrintEngine::QWin32PrintEngine : qt_plugin_query_metadata : QPrinterPrivate::initEngines : QPrinter::QPrinter : QgsLayoutExporter::exportToPdf : QgsJoinDialog::~QgsJoinDialog : QMetaObject::activate : QAction::activate : QAbstractButton::click : QAbstractButton::mouseReleaseEvent : QToolButton::mouseReleaseEvent : QWidget::event : QApplicationPrivate::notify_helper : QApplication::notify : QgsApplication::notify : QCoreApplication::notifyInternal2 : QApplicationPrivate::sendMouseEvent : QSizePolicy::QSizePolicy : QSizePolicy::QSizePolicy : QApplicationPrivate::notify_helper : QApplication::notify : QgsApplication::notify : QCoreApplication::notifyInternal2 : QGuiApplicationPrivate::processMouseEvent : QWindowSystemInterface::sendWindowSystemEvents : QEventDispatcherWin32::processEvents : CallWindowProcW : DispatchMessageW : QEventDispatcherWin32::processEvents : qt_plugin_query_metadata : QEventLoop::exec : QCoreApplication::exec : main : BaseThreadInitThunk : RtlUserThreadStart :
> 
> QGIS Info QGIS Version: 3.4.9-Madeira QGIS code revision: 54585165bb Compiled against Qt: 5.11.2 Running against Qt: 5.11.2 Compiled against GDAL: 2.4.1 Running against GDAL: 2.4.1
> 
> System Info CPU Type: x86_64 Kernel Type: winnt Kernel Version: 10.0.17134

The layout is a single-page containing three maps, some text and HTML items for attribute displaying, an attribute table and a couple of images.

I've tried to "re-do" the layout from scratch in a newly created QGIS project and the issue is still happening.

The problem happens when doing the export "manually" from the layout window, as well as when trying to do the export from PyQGIS "...exporter.exportAsPdf(...".

**Comment by gioman** [comment]
> QGIS Info QGIS Version: 3.4.9-Madeira

@ValentinSastre too old, please try with the latest 3.10 or 3.12 and with a new QGIS profile.

**Comment by ValentinSastre** [comment]
UPDATE: I've updated to QGIS 3.10.6-A Coruña and the issue is still happening. Every time I try exporting a layout atlas as PDF the software crashes. It happens with any layout I try, even if it only contains a simple map.

Here's the crash report:

> Crash ID: 28d8b32ccd9f23248c6532aafe3ab0f115e24763
> 
> 
> Stack Trace
> 
> 
> DllGetClassObject :
> DllGetClassObject :
> DllGetClassObject :
> DllGetClassObject :
> DllGetClassObject :
> DllGetClassObject :
> DllGetClassObject :
> BCalcTotalOEMDMSize :
> PSUI::LSimpleDocumentProperties :
> PSUI::DrvDocumentPropertySheets :
> DocumentPropertySheets :
> DocumentPropertiesWNative :
> DocumentPropertiesW :
> qt_plugin_query_metadata :
> qt_plugin_query_metadata :
> QPrintDevice::defaultPageSize :
> QWin32PrintEngine::QWin32PrintEngine :
> qt_plugin_query_metadata :
> QPrinterPrivate::initEngines :
> QPrinter::QPrinter :
> QgsLayoutExporter::exportToPdf qgslayoutexporter.cpp:653
> QgsLayoutDesignerDialog::exportToPdf qgslayoutdesignerdialog.cpp:2183
> QMetaObject::activate :
> QAction::activate :
> QAbstractButton::click :
> QAbstractButton::mouseReleaseEvent :
> QToolButton::mouseReleaseEvent :
> QWidget::event :
> QApplicationPrivate::notify_helper :
> QApplication::notify :
> QgsApplication::notify qgsapplication.cpp:418
> QCoreApplication::notifyInternal2 :
> QApplicationPrivate::sendMouseEvent :
> QSizePolicy::QSizePolicy :
> QSizePolicy::QSizePolicy :
> QApplicationPrivate::notify_helper :
> QApplication::notify :
> QgsApplication::notify qgsapplication.cpp:418
> QCoreApplication::notifyInternal2 :
> QGuiApplicationPrivate::processMouseEvent :
> QWindowSystemInterface::sendWindowSystemEvents :
> QEventDispatcherWin32::processEvents :
> UserCallWinProcCheckWow :
> DispatchMessageWorker :
> QEventDispatcherWin32::processEvents :
> qt_plugin_query_metadata :
> QEventLoop::exec :
> QCoreApplication::exec :
> main main.cpp:1606
> BaseThreadInitThunk :
> RtlUserThreadStart :
> 
> 
> 
> 
> QGIS Info
> QGIS Version: 3.10.6-A Coru�a
> QGIS code revision: ec80021f49
> Compiled against Qt: 5.11.2
> Running against Qt: 5.11.2
> Compiled against GDAL: 3.0.4
> Running against GDAL: 3.0.4
> 
> 
> 
> System Info
> CPU Type: x86_64
> Kernel Type: winnt
> Kernel Version: 10.0.17134

**Comment by gioman** [comment]
> UPDATE: I've updated to QGIS 3.10.6-A Coruña and the issue is still happening. Every time I try exporting a layout atlas as PDF the software crashes. It happens with any layout I try, even if it only contains a simple map.

@ValentinSastre have you tried with a new QGIS profile?

**Comment by ValentinSastre** [comment]
Yes. I've created a new profile, opened the project, generated and previewed the Atlas and when I try to export to PDF it crashes. Maybe it's worth saying that I'm working remotely, using the computer I use at work from a Remote Desktop Connection with a VPN. Exporting as an image (png for example, works fine).

**Comment by gioman** [comment]
@ValentinSastre Does it happen regardless of the data loaded in the project?

**Comment by ValentinSastre** [comment]
I've just tested it. I created a new project from scratch containing only a WMS basemap layer and a PostGIS point layer. I created a layout with a simple map controlled by Atlas. When I try to export to PDF it still crashes.

**Comment by gioman** [comment]
@ValentinSastre seems very likely to be a local issue.

**Comment by ValentinSastre** [comment]
⌡

> @ValentinSastre seems very likely to be a local issue.

Any ideas of what could I do to try to solve it? Thank you very much for your time.

**Comment by roya0045** [comment]
Could this be a pdf driver issue? I can't recall if qt uses the host driver or not.

**Comment by gioman** [comment]
@ValentinSastre see https://github.com/qgis/QGIS/issues/37290#issuecomment-648707713

**Comment by gioman** [comment]
Closing for lack of further feedback.
