### ISSUE TITLE
When GPGK created with QGIS - RTree trigger is breaking spatial index

### ISSUE THREAD

**Issue by phidrho** [qgis/QGIS#36935]
**Describe the bug**

When QGIS creates GeoPackage from `New geopackage layer...` with option `Create a spatial index` enabled, created GeoPackage file uses old version of specification `gpkg_rtree_index` (GeoPackage 1.0 Specification Annex L).
This old version of GeoPackage specification had a bug which can corrupt spatial index inside GeoPackage file.

As noted in [GeoPackage Specification ver. 1.2.1 - RTree Spatial Indexes - Requirement 77 - maintaining spatial indexes](
http://www.geopackage.org/spec121/index.html#r77):

> GeoPackage Versions 1.2.0 and prior have an incorrect update3 trigger that will fail in certain circumstances. It is strongly recommended to update older GeoPackages with the correct trigger presented here. The GeoPackage Executable Test Suite has been updated to accept either version of the trigger in older versions and to mandate the corrected version in versions after 1.2.0.

**How to Reproduce**

[trigger_test.gpkg.zip](https://github.com/qgis/QGIS/files/4724332/trigger_test.gpkg.zip)

Run an SQL update on feature table, for example:

- check state of the index before update:

```sql
SELECT
    *
FROM
    rtree_test_geometry;
```

- run the update on fid
```sql
UPDATE
    test
SET
    fid = 3
WHERE
    fid = 1;
```

- check state of the index after update:
```sql
SELECT
    *
FROM
    rtree_test_geometry;
```

**QGIS and OS versions**

QGIS 3.12.3
Kubuntu 18.04

**Additional context**

Current DDL for trigger:

```sql
CREATE TRIGGER rtree_test_geometry_update3
         AFTER UPDATE OF geometry
            ON test
          WHEN OLD.fid != NEW.fid AND 
               (NEW.geometry NOTNULL AND 
                NOT ST_IsEmpty(NEW.geometry) ) 
BEGIN
    DELETE FROM rtree_test_geometry
          WHERE id = OLD.fid;
    INSERT OR REPLACE INTO rtree_test_geometry VALUES (
                                                   NEW.fid,
                                                   ST_MinX(NEW.geometry),
                                                   ST_MaxX(NEW.geometry),
                                                   ST_MinY(NEW.geometry),
                                                   ST_MaxY(NEW.geometry) 
                                               );
END;
```

Should be updated to (\<t\> - table name, \<c\> - column name, \<i\> - id column name): 

```sql
CREATE TRIGGER rtree_<t>_<c>_update3 AFTER UPDATE ON <t>
    WHEN OLD.<i> != NEW.<i> AND
    (NEW.<c> NOT NULL AND NOT ST_IsEmpty(NEW.<c>))
BEGIN
    DELETE FROM rtree_<t>_<c>
    WHERE id = OLD.<i>;

    INSERT OR REPLACE INTO rtree_<t>_<c> VALUES (
        NEW.<i>,
        ST_MinX(NEW.<c>), ST_MaxX(NEW.<c>),
        ST_MinY(NEW.<c>), ST_MaxY(NEW.<c>)
    );
END;
```

Also an `gpkg_extensions` table should be updated to new definition for adequate table name:

```sql
UPDATE
    gpkg_extensions
SET
    definition = 'GeoPackage 1.2.1 Specification Annex F'
WHERE
    table_name = 'test';
```

**Things to consider**

Maybe it would be a good thing to silently update all opened GeoPackages, or at least display a warning when loading a layer with old specification from GeoPackage.

**Comment by rouault** [comment]
The wrong trigger definition was fixed in GDAL 2.3.0

**Comment by gioman** [comment]
@phidrho  and on (k)ubuntu 18.04 there is still is GDAL 2.2.3... so... not an issue anymore?

**Comment by phidrho** [comment]
I just ran update and upgrade, and this is QGIS configuration:

```
QGIS version
3.12.3-București

QGIS code revision
8234261527

Compiled against Qt
5.9.5

Running against Qt
5.9.5

Compiled against GDAL/OGR
2.2.3

Running against GDAL/OGR
2.2.3

Compiled against GEOS
3.6.2-CAPI-1.10.2

Running against GEOS
3.7.1-CAPI-1.11.1 27a5e771

Compiled against SQLite
3.22.0

Running against SQLite
3.31.1

PostgreSQL Client Version
10.12 (Ubuntu 10.12-0ubuntu0.18.04.1)

SpatiaLite Version
4.3.0a

QWT Version
6.1.3

QScintilla2 Version
2.10.2

PROJ.4 Version
493

OS Version
Ubuntu 18.04.4 LTS

Active python plugins
pluginbuilder3; 
ntv2_transformations; 
db_manager; 
processing
```

I have not installed GDAL manually.

**Comment by gioman** [comment]
> I have not installed GDAL manually.

@phidrho to get an update version of GDAL you will have to move on to 20.04.

**Comment by nyalldawson** [comment]
@rouault what do you think about bumping the minimum gdal version to 2.3?

**Comment by rouault** [comment]
> what do you think about bumping the minimum gdal version to 2.3?

I don't have a strong opinion. Always pros & cons in doing so. This would make bionic builds relying on stock GDAL to no longer be available. ubuntugis has GDAL 3.0.4 for bionic

**Comment by gioman** [comment]
> This would make bionic builds relying on stock GDAL to no longer be available

no please! :) we don't want to go back to that time when it was necessary to use ubuntugis
