### ISSUE TITLE
Joined tables cannot be edited even if the "editable join layer" option is checked

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#36934]
QGIS all versions (3.10/2/master)

Take two (editable) tables, join them. When creating the join activate the "editable join layer"  option

![unnamed](https://user-images.githubusercontent.com/1951107/83650761-9b817080-a5b0-11ea-93d0-5c209a67c5c6.png)

now add a feature to the main table:

![unnamed2](https://user-images.githubusercontent.com/1951107/83651575-8bb65c00-a5b1-11ea-9d2d-bfb9c61845d0.png)

**Comment by Saijin-Naib** [comment]
Related?
https://github.com/qgis/QGIS/issues/34239

**Comment by elpaso** [comment]
@gioman I cannot reproduce this using the dataset from the other join-related issue that you seem to be using in the snapshot. Can you please re-attach a project to test with?

**Comment by gioman** [comment]
@elpaso point table
```
CREATE TABLE public.point_layer
(
  fid integer  NOT NULL DEFAULT nextval('attribute_layer_id_seq'::regclass),
  geom geometry(Point,3763),
  height double precision,
  CONSTRAINT point_layer13_pkey PRIMARY KEY (fid)
)
```


geometryless table

```
CREATE TABLE public.attribute_layer
(
  id integer NOT NULL DEFAULT nextval('attribute_layer_id_seq'::regclass),
  fid integer,
  some_value text,
  CONSTRAINT attribute_layer_pkey PRIMARY KEY (id)
)
```

Join created in the point layer.

**Comment by elpaso** [comment]
@gioman thank you, but there are at least a dozen of configuration options that can can be different: the schema is not sufficient that's why I asked for a project.

**Comment by gioman** [comment]
@elpaso an example with GPKGs

[no_edit.zip](https://github.com/qgis/QGIS/files/4746412/no_edit.zip)

My previous testes (with pgsql tables): latest master, clean QGIS profile, Ubuntu 18.04.

**Comment by elpaso** [comment]
@gioman testing you project, I made both layers editable and there is no issue on master:

![Screenshot_20200608_164123](https://user-images.githubusercontent.com/142164/84043748-f9de9280-a9a6-11ea-938a-d4e497c42587.png)


... and:

![Screenshot_20200608_164313](https://user-images.githubusercontent.com/142164/84043927-2e524e80-a9a7-11ea-916e-d3091bad8f71.png)

**Comment by elpaso** [comment]
I think that the "editable join layer" is there to block modifications of the joined layer from the main form regardless of the editable state of the joined layer.

But I didn't write that code so I'm just guessing, is there anything in the documentation that clarify what is the expected behavior?

**Comment by gioman** [comment]
I guess we can close this as a case of RTFM https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/vector_properties.html#joins-properties 

but anyway, as user, is a bit counter intuitive.

**Comment by m-kuhn** [comment]
Discussion w.r.t. UX of edit mode of join layer here: https://github.com/qgis/QGIS/pull/4913#discussion_r128999028
