### ISSUE TITLE
 can't open the "Vector" toolbar 

### ISSUE THREAD

**Issue by joaltomafa** [qgis/QGIS#36943]
No puedo abrir la barra de herramientas "Vectorial", no sé por qué. He desinstalado el programa y lo he vuelto a instalar y sigue sucediendo lo mismo. El software es QGIS 3.6.3. Noosa

I can't open the "Vector" toolbar and I don't know why. I have uninstalled an reinstialled the software and it happnens the same. The software is QGIS 3.6.3. Noosa

**Comment by gioman** [comment]
> The software is QGIS 3.6.3. Noosa

@joaltomafa way too old. Please test on the latest 3.10 or 3.12. Also test using a new QGIS profile.

**Comment by joaltomafa** [comment]
Hello, I have tried with the 3.10 version and it happens the same. Also I have uninstalled and reinstalled the software and it makes no difference.

**Comment by Gustry** [comment]
You should try with a new QGIS profile.
Go in `Settings` -> `User Profile` -> `New profile`. Thanks.

**Comment by joaltomafa** [comment]
Many thanks. It worked out.
