### ISSUE TITLE
Y$ value is invalid 

### ISSUE THREAD

**Issue by Cassiovillani** [qgis/QGIS#36940]
I have used the distance and azimuth calculator plugin. First I was not obtain the values ​​of the distance between the points and trying to fix it I found that when I add a $ Y column to know the coordinate, the program just hangs. I believe that the problems are correlated because when the azimuth values ​​are zeroed also as described below

"flat zimuth and distance: 165 ° 10'14.94 '' and 0.00"

The version I use is 3.4.15

 Thank you!

**Comment by gioman** [comment]
@Cassiovillani 

1) 3.4 is too old, you must teste on the latest 3.10 or 3.12

2) is this about the "distance and azimuth calculator plugin" or a core QGIS functionality?

**Comment by Cassiovillani** [comment]
I'm already change the version. The problema was old version with the EPSG
features. Thank you!

Em qui, 4 de jun de 2020 07:16, Giovanni Manghi <notifications@github.com>
escreveu:
