### ISSUE TITLE
Map tips do not show up in 3.12.2

### ISSUE THREAD

**Issue by frizwi** [qgis/QGIS#36957]
Hi,
I've got a conda installed version of QGIS 3.12.2 on Ubuntu 18LTS that doesn't want to show map tips. They're enabled but nothing shows up - the funny thing is that the mouse pointer is in the shape of crosshairs, is this the issue? On my other non conda install of QGIS 3.12.3, its a "hand" symbol and map tips show up just fine. Is this a known bug in 3.12.2?
Thanks,
-Farhan

**Comment by gioman** [comment]
@frizwi conda installations are not officially supported. If it works with the supported installers then this will be closed.

**Comment by frizwi** [comment]
@gioman yes fair enough, could be a problem with the Qt libraries or something. I guess I'm just wondering whether anyone has seen this behaviour before, i.e. see the crosshair in the attached image instead of the hand symbol? Maybe there's a setting I'm missing or something?
Thanks,
![QGIS](https://user-images.githubusercontent.com/25832467/83823482-765b4200-a717-11ea-96d4-3c0b307b1973.png)

**Comment by gioman** [comment]
> . I guess I'm just wondering whether anyone has seen this behaviour before,

@frizwi better ask in the users or developers mailing lists as they are more suited for questions. Thanks!
