### ISSUE TITLE
DPI Scaling between 4k and 2k screens on Windows

### ISSUE THREAD

**Issue by reyemtm** [qgis/QGIS#36979]
**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

QGIS Version 3.10.5 Standalone
OS - Windows 10

Screen Resolution on Laptop - 4K 3840x2160
Screen Resolution on External Screen - 2K 2560x1440

When I open QGIS on the laptop the application window icons and all look as they should. When I  move the application window to the 2K screen, the application does not scale properly - icons are huge. Other windows apps will show this behavior if part of the application window is on both the 4k screen and the 2k screen, but when the app gets moved completely to the 2k screen the resolution of the app is scaled properly. Chrome is one example. 

If there are settings or other options to help with this situation please let me know.

**Comment by elpaso** [comment]
There are some QT environment variables that control DPI and scaling, AFAIK there isn't anything special about that in QGIS code.

You can have a look to: https://doc.qt.io/qt-5/highdpi.html#high-dpi-support-in-qt

I think this ticket should be closed as an upstream (QT) issue.

**Comment by oesteban-vx** [comment]
#43924 contains more information about this same issue.

**Comment by widsuoids** [comment]
This issue can be fixed on Windows using the following settings:
![image](https://user-images.githubusercontent.com/112546295/231984944-0c66e6d1-d5c5-432c-a4de-32c68eb28091.png)

**Comment by widsuoids** [comment]
This issue can be fixed on Windows using the High DPI Settings in the properties:

QGIS Executable/shortcut -> right click: properties -> Kompatibility ->Change High DPI settings button -> select both checkboxes + System(Advanced) in the dropdown -> (re)start QGIS
