### ISSUE TITLE
Documentation for function is_selected is wrong

### ISSUE THREAD

**Issue by TLDuhamel** [qgis/QGIS#36983]
As discovered in [this stackexchange question](https://gis.stackexchange.com/questions/363873/qgis-expression-get-feature-will-not-evaluate-feature-when-called-within-is?noredirect=1#comment595413_363873), the documentation for the _is_selected_ function appears to be incorrect:
![image](https://user-images.githubusercontent.com/2009756/83818724-2468eb00-a71c-11ea-9469-a3ad6989b2c2.png)

The order of parameters is listed incorrectly.
`is_selected([feature=current feature][,layer=current layer])`
should be
`is_selected([layer=current layer][,feature=current feature])`

And accordingly, the example given should be changed:
`is_selected(get_feature('streets', 'name', "street_name"), 'streets')`
should be
`is_selected('streets', get_feature('streets', 'name', "street_name"))`

As seen in QGIS 3.10.3

**Comment by rduivenvoorde** [comment]
I can check this. How do I assign this to myself?
