### ISSUE TITLE
No QGIS 3.12.3 launcher application on Win 10 64-bit

### ISSUE THREAD

**Issue by noelkuberek** [qgis/QGIS#37001]
The installation process was complete and apparently the QGIS is installed on my machine. There is a QGIS file on my local disk, however, there is no launcher application installed. Thus I can't run the program. I've already tried to reinstall it, and even install version 3.10.6, but the same problem occurred.

**Comment by gioman** [comment]
@noelkuberek a too aggressive antivirus?

**Comment by noelkuberek** [comment]
I'm using only the windows defender. I already used QGIS on this computer, but now I tried to update it and it is not installing properly

**Comment by gioman** [comment]
@noelkuberek still seems a local issue of course (QGIS installers on Windows work just fine).

**Comment by noelkuberek** [comment]
@gioman yes, I searched on the internet, and it seems that no one else had this same issue. I'm trying to find if some other app here is blocking it, thanks anyway

**Comment by Saijin-Naib** [comment]
My install broke as well when I used OSGeo4W to upgrade. Had to re-install with the stand-alone installer to repair it.

Win10 x64, only Windows Defender as well.

**Comment by noelkuberek** [comment]
@Saijin-Naib That's right, I tried to upgrade it using the OSGeo4W, and then the executable file disappeared. I tried to reinstall it using the stand-alone installer, however, that doesn't fix the problem. QGIS is apparently installed but no way to run the program.

**Comment by AlexFinch** [comment]
I just discovered qgis yesterday thanks to a google search and tried to install it on windows. All I have is a shell. No sign of any executable. This is Windows 10 64 bit release 2004.

**Comment by AlexFinch** [comment]
I tried again today. Deleted the OSGeo4W64 directory and ran the installer, choosing express install. It worked this time.

**Comment by gioman** [comment]
Closing for lack of further feedback.

**Comment by BenjaminEsqueda** [comment]
> 
> 
> @gioman yes, I searched on the internet, and it seems that no one else had this same issue. I'm trying to find if some other app here is blocking it, thanks anyway

I have the exactly same problem! No idea of how to solve it and none can help me! It's a shame that this is happening, I've been trying to use Qgis since November! No other app have this issue.

You're not the only one,
here's my thread:
https://github.com/qgis/QGIS/issues/36952
