### ISSUE TITLE
Slow snapping in QGIS 3.10

### ISSUE THREAD

**Issue by saberraz** [qgis/QGIS#37004]
We’ve noticed a delay of approx. 1 minute 40 seconds when enabling snapping in QGis 3.10.5 (and QGis 3.10.6)

This delay was not present in Qgis 3.4

Delay occurs when the highlighted “magnet” icon is clicked, and editing is enabled.

Snapping options are the same in all tested versions

Timing in Qgis versions

Enabling snapping while editing, only appears to affect first time per session

m:s

Qgis 3.10.6

01:41

Qgis 3.10.5

01:28

Qgis3.4

00:03

**Comment by gioman** [comment]
@saberraz Hi Saber, any chance to provide a sample project?

**Comment by saberraz** [comment]
Hi @gioman unfortunately not. It is from a supported client and we will look into that.

**Comment by gioman** [comment]
@saberraz any evidence that it happens also in general, not on that specific project/data?

**Comment by saberraz** [comment]
Let me try and recreate one for the ticket.

**Comment by roya0045** [comment]
What about 3.12?

**Comment by saberraz** [comment]
Appears to be a local issue.
