### ISSUE TITLE
"<ServerException>Layer(s) not valid</ServerException>” on QGIS Server installed on Ubuntu 20.04 and MS SQL DB

### ISSUE THREAD

**Issue by catalinmiraute** [qgis/QGIS#37002]
I have the following configuration: 
1. Ubuntu 20.04 server with QGIS Server 3.10.4-A Coruña and Apache/2.4.41 
2. Windows Server 2019 server with MS SQL Standard Edition
The error is present only when I am accessing a QGS project with layers/data pointing to MS SQl DB.
The DB credentials are saved in the project.
The MS SQL DB is responding to Telnet command.
The Qgis Server works correct, I tested using a QGS project pointing to a shapefile stored local.
Is there something else should I check for?
Tks!

**Comment by gioman** [comment]
@catalinmiraute is this a question or a bug report?

**Comment by catalinmiraute** [comment]
@gioman I don't know yet.

**Comment by catalinmiraute** [comment]
@gioman Let's say that it is a question.
I want to know if I am missing something in how to configure QGS project or if there is something else to check on my QGIS Server configuration.
It is strange because I have just made this test also for a QGS project with layers/data stored in Postgres and the result is the same.

**Comment by catalinmiraute** [comment]
I am accessing the QGIS Server directly, not via virtual host.

**Comment by gioman** [comment]
>  I have just made this test also for a QGS project with layers/data stored in Postgres and the result is the same.

@catalinmiraute you should check if you can really access your endpoints (postgresql or else) from the machine where you have qgis server. Seems really a local issue, as of course in general accessing PostGIS data is not an issue (I can't speak for MS SQL Server).

**Comment by catalinmiraute** [comment]
I have response when telnet for both DB's.
Also, for the MS SQL DB when I make this command:
cmd sqlcmd -S <remoteip> -U <user> -p -Q "SELECT @@VERSION"

**Comment by gioman** [comment]
> I have response when telnet for both DB's.

I don't think telnet gives you a definitive answer.

For PostgreSQL you should test

psql -h host -d database -U user -p port

**Comment by catalinmiraute** [comment]
I can make selects in MS SQl DB, so I need to check something else.
In Apache where can I look? I don't use virtual host.

**Comment by catalinmiraute** [comment]
I don't understand if the authentication mechanism from QGIS can influence this.
For this project I don't use this option.

**Comment by gioman** [comment]
> I don't understand if the authentication mechanism from QGIS can influence this.

@catalinmiraute are you sure you are storing the user and password in clear text in the QGIS project file?

**Comment by catalinmiraute** [comment]
The connection string looks like this for every layer:
<datasource>dbname='****Map' host=***********,1433\SQL2014BDU1 user='sa' password='******' estimatedmetadata=true srid=0 type=LineString disableInvalidGeometryHandling='0' table="dbo"."tgArtera" (geom)</datasource>

But in the <layer-tree-group> looks like this:
<layer-tree-layer expanded="1" source="dbname='****Map' host=********,1433\SQL2014BDU1 user='sa' estimatedmetadata=true srid=0 type=LineString disableInvalidGeometryHandling='0' table=&quot;dbo&quot;.&quot;tgArtera&quot; (geom)" checked="Qt::Checked" name="Artere" legend_exp="" providerKey="mssql" id="tgArtera_ea6cac57_99cd_496d_8a44_323dd6a114a2">

**Comment by catalinmiraute** [comment]
The user and password are stored in clear text

**Comment by gioman** [comment]
> The user and password are stored in clear text

please test the psql command to check if the connection to postgresql works.

**Comment by catalinmiraute** [comment]
I don't have the Postgres installed on Ubuntu.
The PostgresSQL DB it is also on Windows Server.

**Comment by catalinmiraute** [comment]
On that Windows machine I have also Qgis Server installed and there are no problems with connecting to MS SQL DB and PostgreSQL DB, on the same QGS project.

**Comment by gioman** [comment]
> On that Windows machine I have also Qgis Server installed and there are no problems with connecting to MS SQL DB and PostgreSQL DB, on the same QGS project.

@catalinmiraute 
so you see? you likely have a problem connection to your db from remote? for example for postgresql: are postgresql.conf and pg_hba.conf correctly configured?

**Comment by catalinmiraute** [comment]
I found something strange.
When I am running cmd /usr/lib/cgi-bin/qgis_mapserv.fcgi I get this:
Application path not initialized
Application path not initialized
Application path not initialized
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Warning 1: Unable to find driver ECW to unload from GDAL_SKIP environment variable.
Warning 1: Unable to find driver ECW to unload from GDAL_SKIP environment variable.
Warning 1: Unable to find driver JP2ECW to unload from GDAL_SKIP environment variable.
Initializing server modules from  "/usr/lib/qgis/server"

"Checking /usr/lib/qgis/server for native services modules"
"Loading native module /usr/lib/qgis/server/libdummy.so"
"Loading native module /usr/lib/qgis/server/libwcs.so"
"Loading native module /usr/lib/qgis/server/libwfs.so"
"Loading native module /usr/lib/qgis/server/libwfs3.so"
"Loading native module /usr/lib/qgis/server/libwms.so"
"Loading native module /usr/lib/qgis/server/libwmts.so"
QFSFileEngine::open: No file name specified
Content-Length: 54
Content-Type: text/xml; charset=utf-8
Server:  Qgis FCGI server - QGis version 3.10.4-A Coruña
Status:  500

ServerException>Project file error</ServerException

But when I am accessing http://localhost/cgi-bin/qgis_mapserv.fcgi?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities I get the right answer.

**Comment by catalinmiraute** [comment]
> > On that Windows machine I have also Qgis Server installed and there are no problems with connecting to MS SQL DB and PostgreSQL DB, on the same QGS project.
> 
> @catalinmiraute
> so you see? you likely have a problem connection to your db from remote? for example for postgresql: are postgresql.conf and pg_hba.conf correctly configured?

For data stored in MS SQL DB is somethng similar with postgresql.conf and pg_hba.conf  ?

**Comment by catalinmiraute** [comment]
I followed this example: https://docs.qgis.org/testing/en/docs/user_manual/working_with_ogc/server/getting_started.html

If I understand right, in the configuration directives for QGIS Server I should have this lines for data stored in PostgreSQL:
  SetEnv PGSERVICEFILE /home/qgis/.pg_service.conf
  FcgidInitialEnv PGPASSFILE "/home/qgis/.pgpass"

**Comment by gioman** [comment]
> If I understand right, in the configuration directives for QGIS Server I should have this lines for data stored in PostgreSQL:
> SetEnv PGSERVICEFILE /home/qgis/.pg_service.conf
> FcgidInitialEnv PGPASSFILE "/home/qgis/.pgpass"

this is you don't want to store the credentials in clear text in the project. Nevertheless Postgresql do not allow remote connections by default, you must configure those two files (on the sever side), plus the firewall of the server mus have the correct port open.

**Comment by catalinmiraute** [comment]
So, in PostgreSQL case even when you store credentials in clear in the QGS project you need to configure those files?
But for MS SQL should work based on stored credentials in clear in the QGS project?

**Comment by gioman** [comment]
> you need to configure those files

@catalinmiraute yes! by default postgresql **do not** allow remote connections.

**Comment by gioman** [comment]
Closing for lack of further feedback.

**Comment by albtrentadue** [comment]
I fell into this pitfall as well. Good I found this issue.
Maybe this could be stressed more, expecially in the "[7. Containerized deployment](https://docs.qgis.org/3.16/en/docs/server_manual/containerized_deployment.html)" page, because a container usually tries to connect a postgres db from a foreign subnet.

**Comment by disarticulate** [comment]
Seems like ya'll are getting the same arcane error. Perhaps bump the error up to a more visible.

When you set QGIS_SERVER_LOG_LEVEL=0 it's evident on my related/unrelated/related issue:
```
01:27:17 WARNING PostGIS[13]: Connection to database failed
qgis-server-1  | connection to server at "bossman" (127.0.1.1), port 34220 failed: fe_sendauth: no password supplied
qgis-server-1  | 
qgis-server-1  | 01:27:17 WARNING PostGIS[13]: Connection to database failed
qgis-server-1  | connection to server at "bossman" (127.0.1.1), port 34220 failed: fe_sendauth: no password supplied
```
Else you'll keep getting these types of issues wasting everyones time.
