### ISSUE TITLE
Closing 3D view crashes QGIS

### ISSUE THREAD

**Issue by Nic-Rosengren** [qgis/QGIS#37008]
**Describe the bug**

When closing a 3d view window Qgis crashes out completely.  The project is fine until i close the 3d view box.  Only the qgs version of the project opens, the qgz version crashes on startup.  
**How to Reproduce**
Only happens in one particular project.  Closing the 3D window crashes the project.

**QGIS and OS versions**

QGIS Info
QGIS Version: 3.12.3-Bucure?ti
QGIS code revision: 8234261527
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Additional context**
Crash ID: 1efa0e5995cc605c8388e93a4752087fce56cb82

Stack Trace

QgsChunkedEntity::cancelActiveJob qgschunkedentity_p.cpp:437
QgsChunkedEntity::cancelActiveJobs qgschunkedentity_p.cpp:462
QgsTerrainEntity::~QgsTerrainEntity qgsterrainentity_p.cpp:92
QgsTerrainEntity::`scalar deleting destructor' :
QObjectPrivate::deleteChildren :
QObject::~QObject :
Qgs3DMapScene::`scalar deleting destructor' :
Qgs3DMapCanvas::~Qgs3DMapCanvas qgs3dmapcanvas.cpp:64
Qgs3DMapCanvas::`scalar deleting destructor' :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
QWidget::`scalar deleting destructor' :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
Qgs3DMapCanvasDockWidget::`vector deleting destructor' :
QObject::event :
QWidget::event :
QDockWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1608
BaseThreadInitThunk :
RtlUserThreadStart :

**Comment by roya0045** [comment]
The fix would be to check if job is a valid pointer  and returning nothing if invalid, before calling its 'chunck' method https://github.com/qgis/QGIS/blame/7b8bd80994faf05af9ef3385eda1c2bf48ce8fae/src/3d/chunks/qgschunkedentity_p.cpp#L437

**Comment by juancobravo** [comment]
I get this problem often as well

**Comment by gioman** [comment]
> I get this problem often as well

@juancobravo provide the data and exact steps to allow us replicate.
