### ISSUE TITLE
Freeze and Crash after selecting Trim Feature after moving line arc

### ISSUE THREAD

**Issue by qu4ntumrush** [qgis/QGIS#37012]
Crash ID: 91df3983a318701b021ac0e78074d8b61844d2e8

Stack Trace

pal::LabelPosition::getId :
QgsMapToolTrimExtendFeature::canvasMoveEvent :
QgsMapCanvas::mouseMoveEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.12.0-Bucure?ti
QGIS code revision: cd141490ec
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
>  QGIS Version: 3.12.0-Bucure?ti

@qu4ntumrush please update to the latest point release, also please try with a new QGIS profile. If the problem persist please attach a sample project with data and **detailed** steps to replicate.

**Comment by gioman** [comment]
Closing for lack of further feedback.
