### ISSUE TITLE
Inconsistent styling with vector tiles

### ISSUE THREAD

**Issue by saberraz** [qgis/QGIS#37020]
This could be related to https://github.com/qgis/QGIS/issues/36995

In the project below, I cannot see the countries boarder when zoomed out:
https://public.cloudmergin.com/projects/saber/natural-earth

![natural-earth](https://user-images.githubusercontent.com/2649047/83978085-ef67be80-a8fc-11ea-8584-29030320df0b.gif)

**Comment by nyalldawson** [comment]
@saberraz do you have a public QGS project which demonstrates this?
