### ISSUE TITLE
 3.12.3 Using excessive resources + freezing

### ISSUE THREAD

**Issue by hrdrckx** [qgis/QGIS#37029]
3.12.3 
Using excessive resources including:
- high cpu usage when using even basic projects
- high ram usage even when not being used and occasionally when project not loaded
freezing:
- when panning around a map or digitizing on screen the software will 'freeze' every few seconds while it processes.  this lag is endemic and noted by colleagues on 3 different windows pcs and one mac.

**Comment by elpaso** [comment]
I'm sorry but this bug report is not very useful. 

You should try to provide a test project with attached data and an exact step by step procedure that a developer could use to reproduce the issue.

**Comment by gioman** [comment]
@hrdrckx also you may want to try a new QGIS profile (no 3rd party plugins installed) and see if anything changes.

**Comment by gioman** [comment]
Closing for lack of feedback.
