### ISSUE TITLE
Font colour in grid decoration

### ISSUE THREAD

**Issue by hrdrckx** [qgis/QGIS#37028]
QGIS users would greatly benifit from the inclusion of choice of font colour in the
view>decorations>grid & grid properties menu

Currently the Grid line symbol colour can be chose but the text which labels these grid lines cannot and remains the default black which often renders the labels invisible on dark backgrounds.

**Comment by rduivenvoorde** [comment]
@hrdrckx (personal observation) I think if you add an image with such an ugly rendering, it will encourage more people to invest time in this :-) 
At this moment I personally cannot imagine exactly what you mean (but probably others can).

**Comment by hrdrckx** [comment]
![screenshot_20200611-141954](https://user-images.githubusercontent.com/40512017/84352104-49af9a80-abef-11ea-98f3-0e79c32893cc.png)

something like this that just came up on my screen?  I'm sure i could make something much worse if i tried :P

**Comment by rduivenvoorde** [comment]
@hrdrckx ok NOW it is clear :-)

For others: talking about this dialog:

![Screenshot-20200611085534-410x603](https://user-images.githubusercontent.com/731673/84354543-5c12df80-abc1-11ea-8eee-45fe47f902d3.png)

The 'decoration'-items are very old functions, often other options are available.
I was thinking about: there is a 'processing' function called 'Create Grid'.. that creates a grid LAYER which you can style in whatever style you want...

![Screenshot-20200611085005-951x674](https://user-images.githubusercontent.com/731673/84354080-9039d080-abc0-11ea-95a3-9233a07a6e5c.png)

Mmm, trying that out now, I realize it is a hassle to get labels on the edge of your mapcanvas...

So the old decoration thing has it's value apparently. I'll try on the discussion list what others think: add a color button (or text styling?) to the decorations/grid dialog. 
OR maybe create some labeling regime in which the labels always try to end up on the edges of the canvas. In that way it would be possible to create such labels in all other ways, AND we could add it to the Create Grid dialog and maybe get rid of the old decorations stuff?

**Comment by rduivenvoorde** [comment]
Ah, and I also realized now, off course creating a Layout also has the possibilities to create a grid AND you can set the font color for it :-)

![Screenshot-20200611091339-1690x919](https://user-images.githubusercontent.com/731673/84356091-fa07a980-abc3-11ea-844c-309b5fd9a886.png)

**Comment by hrdrckx** [comment]
@rduivenvoorde - great overview thanks!

Regarding your other suggestions:
^as you suggest.  print layout already has this ability to change font style so i imagine implementing it into the decoration is a relatively easy short term goal.

* Creating permanent grid layers as per the create grid function is usually for a different purpose.

For what it's worth, I believe the 'decoration' grid style has it's value and should be retained.
- it is transient and can easily be adjusted
- doesn't require building a new 'grid' for different scales.
- Every user QGIS user i know use this constantly and have wished for it to be more accessible and easier to use.  I am just the first? to mention it as a potential feature request.

However, if developers wish to modernize this function, then that is even more great!
Perhaps:
- with a font/text styling/colour button
- perhaps it's own submenu or more easily accessible location

(Side note: An excellent implementation of the 'decorative' grid function is in the Discover extension of Mapinfo which is easily accessible and can change the spacing of the grid cells dependant on the scale / zoom level.)

**Comment by rduivenvoorde** [comment]
@hrdrckx do you have a screendump of this nice accessible dialog? IF in the future somebody wants to invest time in this, it is always nice to have some inspiration (and most QGIS devs will not have Mapinfo on the ( Linux ;-) ) desktop.

**Comment by hrdrckx** [comment]
> @hrdrckx do you have a screendump of this nice accessible dialog? IF in the future somebody wants to invest time in this, it is always nice to have some inspiration (and most QGIS devs will not have Mapinfo on the ( Linux ;-) ) desktop.

Fortunately (like most wise people) I transitioned away from such unpleasantness to a pure Qgis life many years ago, but i will ask around and perhaps i can get a screenshot.

@nirvn thanks!
