### ISSUE TITLE
macOS nightly build issues

### ISSUE THREAD

**Issue by timlinux** [qgis/QGIS#37034]
Currently nightly builds are broken since two days (there should be a .DMG for each day) at 

https://qgis.org/downloads/macos/nightly/?C=M;O=D

![image](https://user-images.githubusercontent.com/178003/84011478-15797700-a96e-11ea-9db8-7e7066a144b5.png)

CC @PeterPetrik

**Comment by PeterPetrik** [comment]
```
Pulling new translations...
tx INFO: New translations found for the following languages:is, bg, ky
tx INFO: Pulling translations for resource QGIS.qgis-application (source: i18n/qgis_en.ts)
tx INFO: Skipping 'el' translation (file: i18n/qgis_el.ts).
tx INFO: Skipping 'eo' translation (file: i18n/qgis_eo.ts).
tx INFO:  -> en: i18n/qgis_en.ts
tx ERROR: Failed to connect. Server responded with HTTP code 502
tx ERROR: Failed to connect. Server responded with HTTP code 502
```

it could be connected with what @rduivenvoorde reported few days ago? https://lists.osgeo.org/pipermail/qgis-developer/2020-June/061457.html

the problem is that the `i18n` folder is deleted, because we want to download latest translations, but it fail so it cmake reports missing translation folder... 

any idea @jef-n if there was something similar on other platforms before I will try to dig more into the problem?

**Comment by rduivenvoorde** [comment]
> it could be connected with what @rduivenvoorde reported few days ago? https://lists.osgeo.org/pipermail/qgis-developer/2020-June/061457.html

Nope, I did not touch anything yet.
And seeing 
tx INFO: Pulling translations for resource QGIS.qgis-application (source: i18n/qgis_en.ts)
the scripts are just using tx-client to download english, nothing to do with any github/tx integration.

A '502 Bad Gateway' seems more like  a proxy or network problem on their or our side?

**Comment by PeterPetrik** [comment]
@jef-n 
---
- installed 0.13.10 version on server, no better
- tried to generate fresh new API key and tried command `tx pull -a  -s --minimum-perc=35`  - same error
- googling does not help
- contacted the transifex support, let see if they reply.

**Comment by rduivenvoorde** [comment]
@PeterPetrik on which server do you do this?

If I am correct (we did tx pull's on doc also), you need a .tx/config file (well at least we need it), see https://docs.transifex.com/client/config/ is that one maybe missing or broken?

**Comment by PeterPetrik** [comment]
there is one in the repo, this is on the QGIS cloud MacOS server macbuild.qgis.org

**Comment by rduivenvoorde** [comment]
Mmm, trying here locally I get the same:

```
$ tx pull -a -s --minimum-perc=35
tx INFO: Pulling translations for resource QGIS.qgis-application (source: i18n/qgis_en.ts)
tx INFO:  -> is: i18n/qgis_is.ts
tx INFO:  -> nb: i18n/qgis_nb.ts
tx ERROR: Failed to connect. Server responded with HTTP code 502
tx ERROR: Failed to connect. Server responded with HTTP code 502
```

Note that -s is pulling the source file isn't it? So I tried only -s:

```
$ tx pull -a --minimum-perc=35
tx INFO: Pulling translations for resource QGIS.qgis-application (source: i18n/qgis_en.ts)
tx INFO:  -> ar: i18n/qgis_ar.ts
tx INFO:  -> ca: i18n/qgis_ca.ts
tx ERROR: Failed to connect. Server responded with HTTP code 502
tx ERROR: Failed to connect. Server responded with HTTP code 502
```

Then I though to remove the `--minimum-perc=35` but that takes a little longer to end with a 502:


```
$ tx pull -a
tx INFO: Pulling translations for resource QGIS.qgis-application (source: i18n/qgis_en.ts)
tx INFO:  -> fi: i18n/qgis_fi.ts
tx INFO:  -> zh-Hans: i18n/qgis_zh-Hans.ts
tx INFO:  -> pt_BR: i18n/qgis_pt_BR.ts
tx INFO: Skipping 'ar' translation (file: i18n/qgis_ar.ts).
tx INFO:  -> et: i18n/qgis_et.ts
tx INFO:  -> cs: i18n/qgis_cs.ts
tx INFO: Skipping 'tr' translation (file: i18n/qgis_tr.ts).
tx INFO: Skipping 'sl' translation (file: i18n/qgis_sl.ts).
tx INFO:  -> es: i18n/qgis_es.ts
tx INFO:  -> uk: i18n/qgis_uk.ts
tx ERROR: Failed to connect. Server responded with HTTP code 502
tx ERROR: Failed to connect. Server responded with HTTP code 502
```

Better contact Transifex?

**Comment by PeterPetrik** [comment]
> * contacted the transifex support, let see if they reply.

already did 30minutes ago

**Comment by rduivenvoorde** [comment]
@PeterPetrik any news from Transifex? 
According to @jef-n this also affects the Windows nightlies now...

**Comment by timlinux** [comment]
@rduivenvoorde they are still not building for macOS

![image](https://user-images.githubusercontent.com/178003/85121623-0079cf00-b21d-11ea-8ca1-1dff115ab246.png)

![image](https://user-images.githubusercontent.com/178003/85121671-17202600-b21d-11ea-8085-d14ea8beff8b.png)

**Comment by rduivenvoorde** [comment]
@timlinux @PeterPetrik  got a response for the tx people, not sure what the status is now

**Comment by jef-n** [comment]
took 18/20 retries to get the translations into today's release. *phew*

**Comment by timlinux** [comment]
@rduivenvoorde we at least got the PR build that we can link in the downloads page:

<img width="728" alt="image" src="https://user-images.githubusercontent.com/178003/85210275-7e7dc900-b336-11ea-8fb2-119a4267795f.png">

**Comment by timlinux** [comment]
And since last night we got nightlies again:
