### ISSUE TITLE
Issue importing tables  in QGIS from a large MySQL Database using "Add Vector Layer"

### ISSUE THREAD

**Issue by L-Haw** [qgis/QGIS#37040]
When trying to import data (i.e. table) from MySQL using "Add Vector Layer" --> "Database", I enter the details about MySQL connections and click "Test Connection" that shows that I am connected to the MySQL database alright. However, when I click "Add" which is supposed to open a window with a list of tables in my database, QGIS 'stop responding' and crashes after few seconds and I have to force closing QGIS. 
I believe this is related to the large size of my database (~254GB) because the steps above work just fine if I try to connect to a smaller database. 
I tried to import the MySQL table using the Python Console using:
**vlayer = QgsVectorLayer( uri, NewTableName, "ogr" )**
but **vlayer.isValid()** always return 'False'
Is this a common issue with QGIS when connecting to large databases? Is there a way to import a specific table from the database without QGIS having to load the list of all tables in the database?

I am working in **Windows 10** with:
**QGIS 3.12**
**MySQL Workbench 8.0**
**Python 3.7.0**

Thanks in advance for your help!

**Comment by elpaso** [comment]
This is a bug because QGIS should not crash... Any stacktrace?

Workarounds maybe possible because you can add a vector layer from Python.

**Comment by L-Haw** [comment]
Thanks elpaso for taking the time to reply. 
I eventually had to work around the issue by creating my spatial MySQL tables (that I build by processing data in existing tables in my original large database) in a new database. This latter is relatively small and QGIS could access the tables in this small database.
This makes me believe that the issue did come from the large size of MySQL database (~254GB) as maybe QGIS has to read through the entire tables before opening the "Select Vector Layet to Add" window when trying to add a table from MySQL Database connection. I can't confirm this though.

**Comment by Pedro-Murteira** [comment]
@L-Haw Hello, did this issue occur in more recent versions without you having to resort to the mentioned workaround?
