### ISSUE TITLE
Form Value Relation Dropdowns in QField

### ISSUE THREAD

**Issue by manumanul** [qgis/QGIS#37069]
In accordance with this question (https://gis.stackexchange.com/questions/341849/form-value-relation-dropdowns-in-qfield/341852#341852) it seems that it still not possible to form value value relation dropdowns in qfield.

Any chance of fixing this problem? It would be a really important feature :)

**Comment by gioman** [comment]
@manumanul this must be filed in QField bug tracker, thanks!
