### ISSUE TITLE
Obtrusive warning in the auth dialog

### ISSUE THREAD

**Issue by m-kuhn** [qgis/QGIS#37070]
On the authentication dialog, there is a warning if the password is saved in plain text.

The warning itself is important, but the visual attention it requests right now is slightly exaggerated.

![picture](https://user-images.githubusercontent.com/588407/84184412-94b19c80-aa8d-11ea-8a40-5365e3a01ca5.png)

Ideas:

 - De-bold (at least the content, maybe the title "Warning")
 - Switch colors away from red
 - Instead add a :warning: icon

**Comment by elpaso** [comment]
Agreed, do we have anything about warnings in the HIG ? I think something in the lines of the message bar warning should probably looks better.

**Comment by nirvn** [comment]
I don't think a message bar works there. It's a constant state/warning.

+1 for a warning sign and a short non red text. I'll give it a try this week.

**Comment by elpaso** [comment]
> I don't think a message bar works there. It's a constant state/warning.
> 
> +1 for a warning sign and a short non red text. I'll give it a try this week.

I didn't mean to use a message bar, I was suggesting to use the same visual of the warning messages that appear in the message bar, i.e. same color, fonts etc..

**Comment by nyalldawson** [comment]
This is fixed now, right?

**Comment by nirvn** [comment]
Ya.
