### ISSUE TITLE
Unable to save shapefile in QGIS Master

### ISSUE THREAD

**Issue by NyakudyaA** [qgis/QGIS#37091]
# Problem

## Steps

* Load preloaded layer "World Map" 
* Filter using `"NAME" = 'Rwanda'`
* Use QuickOSM to download OSM data.
![quick-osm](https://user-images.githubusercontent.com/2510900/84259284-8ceb0a00-ab18-11ea-8832-3068c5889d2c.png)
* Try to save the polygon `admin_level` to a shapefile

Note the following error.
![error](https://user-images.githubusercontent.com/2510900/84259437-c3c12000-ab18-11ea-87af-fca2da2723af.png)

QGIS Version
![version-qgis](https://user-images.githubusercontent.com/2510900/84259501-dcc9d100-ab18-11ea-818f-404771edcee9.png)

**Comment by gioman** [comment]
> In this case, I think QGIS should gracefully fail with a proper warning about this or any other data source with such limitations

@NyakudyaA @benhur07b nice catch. Please open a feature request like "make QGIS fail gracefully when trying to save as Shapefile a vector with > 345 fields". Thanks!
