### ISSUE TITLE
Salidas continuas del Atlas.

### ISSUE THREAD

**Issue by isrgil** [qgis/QGIS#37096]
El Atlas provoca cierres inesperados.
6eaf2393e84264c20ac6d43e8dbf10a2b1805d69

Stack Trace

QPicture::exec :
QPicture::play :
QPainter::drawPicture :
QgsPaintEffect::sourceAsImage qgspainteffect.cpp:193
QgsShadowEffect::draw qgsshadoweffect.cpp:34
QgsEffectStack::draw qgseffectstack.cpp:115
QgsPaintEffect::end qgspainteffect.cpp:154
QgsTextRenderer::drawBuffer qgstextrenderer.cpp:2846
QgsTextRenderer::drawTextInternal qgstextrenderer.cpp:3729
QgsVectorLayerLabelProvider::drawLabelPrivate qgsvectorlayerlabelprovider.cpp:613
QgsVectorLayerLabelProvider::drawLabel qgsvectorlayerlabelprovider.cpp:429
QgsLabelingEngine::drawLabels qgslabelingengine.cpp:472
QgsDefaultLabelingEngine::run qgslabelingengine.cpp:560
QgsMapRendererJob::drawLabeling qgsmaprendererjob.cpp:932
QgsMapRendererParallelJob::renderLabelsStatic qgsmaprendererparalleljob.cpp:399
QtConcurrent::RunFunctionTask::run qtconcurrentrunbase.h:136
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.12.3-Bucure?ti
QGIS code revision: 8234261527
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362
![bug_atlas](https://user-images.githubusercontent.com/66729377/84263137-359c6800-ab1f-11ea-8e1c-dd5e1a335ca3.png)

**Comment by gioman** [comment]
@isrgil file again in English with the requested infos, thanks!
