### ISSUE TITLE
Can't access the properties of a local layer if VPN is disconnected

### ISSUE THREAD

**Issue by Brasselle** [qgis/QGIS#37104]
Bonjour,
Je suis sur la version 3.10.6 windows 64. Le problème avait été constaté sur la 3.10.5 (sans avoir identifié le problème précisément). 
je n'ai pas d'accès aux propriétés d'une couche locale (seule couche du projet local) sans que mon poste de travail soit connecté au serveur par VPN.

Merci

**Comment by gioman** [comment]
@Brasselle how the VPN relates to your project? do you have any layers in the project that are loaded only if the VPN is connected?

**Comment by Brasselle** [comment]
Sorry again, I translate by Google
To answer your question: The VPN is simply connected. No layer is connected to the server.

I don't think the problem comes from Qgis but there is an abnormal interaction.
I managed to reproduce the problem. It happens when QGIS is open and then I connect to the VPN. At this time, the layer properties window cannot be opened.
If I open the VPN, I have to reboot the OS.

**Comment by gioman** [comment]
> I don't think the problem comes from Qgis but there is an abnormal interaction.

Then what can we do?

**Comment by Brasselle** [comment]
Sorry again, I translate by Google

I do not know.
Qgis developers cannot imagine all the relationships with all software.
But knowing why Qgis is disrupted after stopping server protocols is perhaps an info, a working track ... right?
I just wanted to make a contribution

**Comment by Brasselle** [comment]
Sorry again, I translate by Google
Hello
To continue reporting on the problem encountered, I tested with version 3.4 of QGIS.
In a new local project with 1 local layer, I have no problem accessing the properties of the layer.

I don't understand

**Comment by Brasselle** [comment]
Sorry again, I translate by Google
last consultation before closing
On the absolute way, I have not yet encountered this problem
