### ISSUE TITLE
Processing toolbox should be allways enabled

### ISSUE THREAD

**Issue by AjaxSantos** [qgis/QGIS#37117]
Processing toolbox should be enabled allways, because searching tools in numerous menus destory user experience most effective.
Processing toolbox is not just a plugin. It is a common tool. In [QGIS Documentation](https://docs.qgis.org/2.8/en/docs/user_manual/processing/toolbox.html) it is written, that toolbox is "main element of the processing GUI" and is a part of "daily work".
Problems with searching this toolbox was viewed over [28k](https://gis.stackexchange.com/questions/149413/qgis-processing-toolbox-disappeared) and [12k](https://gis.stackexchange.com/questions/146591/missing-processing-menu-in-qgis) times. This shows, that find this toolbox is difficult and toolbox should be found more easier.
It would be nice, if you make it better.

**Comment by andreasneumann** [comment]
@AjaxSantos thank you for opening this issue request.

But I respectfully disagree. We have numerous users who use QGIS regularly without ever having the need to use Processing. People who use QGIS as a viewer or as an editor and without having any analysis tasks.

I also don't agree that it is so hard to find the processing toolbox.

**Comment by andreasneumann** [comment]
> Problems with searching this toolbox was viewed over [28k](https://gis.stackexchange.com/questions/149413/qgis-processing-toolbox-disappeared) and [12k](https://gis.stackexchange.com/questions/146591/missing-processing-menu-in-qgis) times

The problems on Stack Exchange you cite here refer to very ancient QGIS 2.x versions. THese entries are totally outdated. In QGIS 3.x Processing has it's own menu. What is so hard about it?

**Comment by gioman** [comment]
@AjaxSantos I agree with @andreasneumann

**Comment by AjaxSantos** [comment]
> 
> 
> @AjaxSantos thank you for opening this issue request.
> 
> But I respectfully disagree. We have numerous users who use QGIS regularly without ever having the need to use Processing. People who use QGIS as a viewer or as an editor and without having any analysis tasks.
> 
> I also don't agree that it is so hard to find the processing toolbox.

@andreasneumann Thank you for your answer.
Also for users, which QGIS as a simple viewer or editor, could think about analyses and want to find them. So the toolbox it is an easy and fast way to find something. And this users, that use QGIS for processing, use not ArcGIS because of the count of processing tools, because they need it.
My Point with "easier to find" was, that when processing is diseable (for whatever reason), it is hard to find, where i can find or enable the toolbox.
Maybe it would help, if in [documentation](https://docs.qgis.org/3.10/de/docs/user_manual/processing/toolbox.html) stand at start, that processing menu has to enable by plugin modul.

**Comment by DelazJ** [comment]
See https://github.com/qgis/QGIS-Documentation/pull/5687
