### ISSUE TITLE
Continuous Crashing

### ISSUE THREAD

**Issue by ghellerwagner** [qgis/QGIS#37121]
## User Feedback

I was experiencing crashes on opening a project file with associated layers and server connections, so i uninstalled and reinstalled QGIS completely but encounter the same error and crash when i reopen the program and don't even do anything now.

## Report Details

**Crash ID**: [67d946f7e16887bfd939dfe454d37ea8d66bc49c](https://github.com/qgis/QGIS/search?q=67d946f7e16887bfd939dfe454d37ea8d66bc49c&type=Issues)

**Stack Trace**
<pre>
QSslKey::operator!= :
QSslKey::operator!= :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
QEventLoop::exec :
QThread::exec :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.12.3-Bucure?ti
QGIS code revision: 8234261527
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment]
@ghellerwagner please try with a new QGIS profile.

Please add all the requested infos:

**Comment by uclaros** [comment]
Same crash ID: #34967

**Comment by ghellerwagner** [comment]
## User Feedback

Describe the Bug
- Open QGIS 3.12.3 from start menu as usual, there is lag in intial start up, the standard gui interface shows up, after ~10 seconds the system freezes and the following crash id, strack trace and system information is displayed and i have to reload the program. 

- I created a new profile and within a similar time frame the crash ensued again. 

How to Reproduce 
- Not entirely sure as the issue may be specific to my system. There was only one other issue with the same crash id and the resolution wasn't forthcoming in the issue notes. 

QGIS and OS versions
- I am using Windows 10, and the version of QGIS is 3.12.3, there may conflicting versions as it was previously 3.12.2 and was running fine a couple days ago.


Additional Context
- I am using QGIS on a secure network and it may be related to the firewall/security of the system, i have lodged a ticket with our IT department.

- I have been having issues connecting to the plugin libraries and automatic updates seem to be blocked. However as my work has been fairly simple up to now this hasn't been an issue. 

- I am using a remote connection to operate my desktop computer via a laptop at home. 

- I have been utilising QGIS for ~3 months.



## Report Details

**Crash ID**: [67d946f7e16887bfd939dfe454d37ea8d66bc49c](https://github.com/qgis/QGIS/search?q=67d946f7e16887bfd939dfe454d37ea8d66bc49c&type=Issues)


**Stack Trace**
<pre>
QSslKey::operator!= :
QSslKey::operator!= :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
QEventLoop::exec :
QThread::exec :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>


**QGIS Info**
QGIS Version: 3.12.3-Bucure?ti
QGIS code revision: 8234261527
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by ghellerwagner** [comment]
I just reinstalled version 3.12.2 and experienced the same crashing issue

**Comment by gioman** [comment]
>     * Not entirely sure as the issue may be specific to my system

@ghellerwagner if you don't list the exact steps that lead to the crash then this will anyway be closed as a local issue (because we don't have a clear path to check if is a replicable issue). You should also attach a sample project+data in case the issue is project/data dependent.

**Comment by ghellerwagner** [comment]
@gioman, I have listed all the steps i have taken leading up to and during the crashing events, the system crashes with out any project data attached to it regardless of how i proceed during start up. 

The reason i infer that it may be system specific is because it boots on my other computer without the same issue. I am waiting to hear back from our network guys and if they are forthcoming in answers regarding the program i will post the feed back to hopefully help people in the future if they encounter similar issues. If there is no clear answer from them i will endeavour to diagnose the issue deeper.

**Comment by ghellerwagner** [comment]
The issue has been resolved, it was a network issue on my isolating the QGIS software and resulting in a permissions loop crashing the program. It has been addressed and the software now runs.

**Comment by ghellerwagner** [comment]
This issue has started again, the work around for a short period of time was copying the data8 cahe files from the AppData/Local directory from another computer. This would allow me to operate the program for a short period of time. However it seems that there is a integral file structure calling problem in this area. I just wiped every trace of the program and reinstalled 3.10 LTR version and created a new profile. It seems to be crashing on the QSslKey::operator!= : call step and when i look into this aspect of QGIS i get lost. Is there a setting to stop the cache file being wiped or reset when in use?

**Comment by gioman** [comment]
> was copying the data8 cahe files from the AppData/Local directory from another computer
> The new data8 file is completely empty now,

@ghellerwagner what do you mean?




>  to understand this aspect of QGIS documentation

what aspect?

**Comment by sdieters** [comment]
This is very similar to what is occurring with my set-up #38346, except I was getting a crash during the start up process.
Because of the delay (minute) it initially it looked like a problem opening a project or a file. Does the crash occur if you just open QGIS?

FIX: I was able to fix initial crash by setting the proxy settings Settings> Options> Network to my system settings.

However no matter which of our various proxy settings I used I could now get the Plugin Manager to work.
Symptoms:
Now able to see all the Plugins meaning that a connection is established with the repository 
but when clicking on a Plugin there is a crash.

**Comment by ghellerwagner** [comment]
@sdieters, I found that the main issue with this crash was to do with the network authentication certificates. I have been able to supersede the crashing by getting to the authentication window and manually clearing the authentication caches before it crashes, this seems to stabilize the issue for the time being.

**Comment by ghellerwagner** [comment]
@gioman 
what do you mean?
to understand this aspect of QGIS documentation
what aspect?

The authentication certificate pathways and automatic cache clearing operations.

**Comment by gioman** [comment]
@ghellerwagner still an issue?

**Comment by sdieters** [comment]
We have partial work-arounds. But this still causes us problems.
Stefan

Stefan Dieters   |   Spatial Information Officer
Geodata Services   |   Land Tasmania

Mostly Back in the office:
T :03 6165 3191

Department of Primary Industries, Parks, Water and Environment
Level 9, Lands Building
134 Macquarie Street Hobart TAS 7000
GPO Box 44 Hobart TAS 7001

T: 03 6165 3191  |   M:    |   E: stefan.dieters@dpipwe.tas.gov.au<mailto:stefan.dieters@dpipwe.tas.gov.au>
www.dpipwe.tas.gov.au<http://www.dpipwe.tas.gov.au/>   |   www.thelist.tas.gov.au<http://www.thelist.tas.gov.au/>   |   www.tasmap.tas.gov.au<http://www.tasmap.tas.gov.au/>

[Facebook Land Tasmania]<https://www.facebook.com/landtasmania>[Twitter Land Tasmania]<https://twitter.com/LandTasmania?lang=en>[LinkedIn Land Tasmania]<http://www.linkedin.com/company/land-tasmania>

CONFIDENTIALITY NOTICE AND DISCLAIMER

The information in this transmission may be confidential and/or protected by legal professional privilege, and is intended only for the person or persons to whom it is addressed. If you are not such a person, you are warned that any disclosure, copying or dissemination of the information is unauthorised. If you have received the transmission in error, please immediately contact this Office by telephone, fax or email, to inform us of the error and to enable arrangements to be made for the destruction of the transmission, or its return at our cost. No liability is accepted for any unauthorised use of the information contained in this transmission.

If the transmission contains advice, the advice is based on instructions in relation to, and is provided to the addressee in connection with, the matter mentioned above. Responsibility is not accepted for reliance upon it by any other person or for any other purpose.

**Comment by sdieters** [comment]
This still causes our group trouble. We have some partial work-arounds, but these are very much a kludge. Will review again in new year.

**Comment by ghellerwagner** [comment]
Hi Giovanni,

No matter how many ways i loaded/installed the program or versions or
profiles i tried helped in anyway.  The current work around is to open the
authentication tab in settings as soon as the program loads and clear the
network authentication caches. This seems to  work for the types of jobs
that i am completing however it does not feel like a permanent solution and
does not allow the use of plugins.

Regards

Gideon Heller-Wagner

**Comment by gioman** [comment]
>  No matter how many ways i loaded/installed the program or versions or profiles i tried helped in anyway

@ghellerwagner would you mind edit the title to something more descriptive of your problem?



> This issue has started again, the work around for a short period of time was copying the data8 cahe files from the AppData/Local directory from another computer. This would allow me to operate the program for a short period of time. However it seems that there is a integral file structure calling problem in this area. I just wiped every trace of the program and reinstalled 3.10 LTR version and created a new profile. It seems to be crashing on the QSslKey::operator!= : call step and when i look into this aspect of QGIS i get lost. Is there a setting to stop the cache file being wiped or reset when in use?
> 
> The new data8 file is completely empty now, and seems the contents are not being created.
> 
> Any help in pointing me in the write direction to understand this aspect of QGIS documentation would be appreciated.

it seems you are hitting  a problem related to a very specific scenario, you should raise your issue on the developers mailing list.

**Comment by ghellerwagner** [comment]
Yep no problems, I’ll edit it tomorrow.

**Comment by gioman** [comment]
> Yep no problems, I’ll edit it tomorrow.

@ghellerwagner ping
