### ISSUE TITLE
Numerical edit (edit feature) Paste from clipboard paste with ',' instead of '.'

### ISSUE THREAD

**Issue by erikthysell** [qgis/QGIS#37131]
I am using QGIS 3.10.5 and in Numerical Edit (popup window header says "Edit feature") when I paste values (button at the top) the inserted values are pasted with ',' (comma) instead of '.' (dot) as decimal point. The windows settings are generally Danish but with decimal point as '.' (dot). QGIS locale setting is en_DK which works the same way as system settings.
It is not only when I paste values (both directly from excel but also when copying from notepad++) the pasted values are with a ',' (comma). They should be with '.' (dot).
When I click Numerical Edit and select a feature and the window pops up the numbers are with '.' (dot), so it is only in the pasting process that something goes wrong.
Pasting a single value (clicking in a single field and pasting) it works correctly for that single value, but with many values to paste this is not an option.

**Comment by gioman** [comment]
@erikthysell duplicate of https://github.com/qgis/QGIS/issues/29682 ?

**Comment by elpaso** [comment]
Not sure if it's a duplicate ... anyway, can you please:

1. attach a snapshot of your settings - I'm interested in what is your "Locale" setting (third line from the top in:)

![immagine](https://user-images.githubusercontent.com/142164/84386851-57b2ea80-abf2-11ea-8d13-12ebef596ebd.png)

2. attach a short video with the steps to reproduce the issue

**Comment by gioman** [comment]
> and in Numerical Edit (popup window header says "Edit feature")

@erikthysell can you please clarify what dialog are you referring to? even better if you add attach a short video with the steps to reproduce the issue, thanks.
