### ISSUE TITLE
ubuntu18.04 build error

### ISSUE THREAD

**Issue by GISerliang** [qgis/QGIS#37134]
**Describe the bug**
ubuntu 18.04 LTS, build qgis release 3.10 branch using make, I got two "multiple definition"'s errors.

**How to Reproduce**
using INSTALL.md 3.7 chapter 
![image](https://user-images.githubusercontent.com/11342604/84385577-6913eb00-ac22-11ea-8014-2e562047c3d1.png)

**QGIS and OS versions**
QGIS Version: branch release_3-10
OS Version: Ubuntu 18.04 LTS DESKTOP

**Additional context**

![image](https://user-images.githubusercontent.com/11342604/84385385-0de1f880-ac22-11ea-8bcd-b7ad431a35ad.png)
![image](https://user-images.githubusercontent.com/11342604/84385414-19cdba80-ac22-11ea-8cc6-d18459f0bb80.png)

**Comment by GISerliang** [comment]
I forgot an important ting, I configure "FORCE_STATIC_LIBS" to ON

**Comment by gioman** [comment]
@GISerliang you should ask in the developers mailing lists rather than assuming is a bug (which likely is not).

**Comment by GISerliang** [comment]
@gioman ok, I will not

**Comment by GISerliang** [comment]
@gioman but DownloaderThread multiple definition did not fixed
