### ISSUE TITLE
Homogenize window title separator - Win10

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#37153]
I think it's just a win10 problem

OSGeo4W64 - QGIS master

![image](https://user-images.githubusercontent.com/7631137/84474120-9d22f680-ac8a-11ea-9bda-f97ccf9845a9.png)

![image](https://user-images.githubusercontent.com/7631137/84476180-107a3780-ac8e-11ea-8fed-168939a12025.png)

https://github.com/qgis/QGIS/issues/35761#issuecomment-641850009

**Comment by uclaros** [comment]
Why did we not opt to use a simple ascii character like a dash or the double colons?

**Comment by elpaso** [comment]
@uclaros because these look better and we hoped that in year 2020 any decent compiler for any decent operating system would support UTF8.

We started a few years ago with replacing all `...` with `…` (Horizontal Ellipsis)

**Comment by m-kuhn** [comment]
https://docs.microsoft.com/en-us/cpp/build/reference/utf-8-set-source-and-executable-character-sets-to-utf-8?view=vs-2019 ?

**Comment by elpaso** [comment]
@m-kuhn do you think it worth a try?  Honestly I'll probably quicker in replacing all em-dashes with unicode literals than build QGIS on windows.

**Comment by m-kuhn** [comment]
Sure!

This was a response to 

> ... and we hoped that in year 2020 any decent compiler for any decent operating system would support UTF8.

**Comment by pigreco** [comment]
![image](https://user-images.githubusercontent.com/7631137/84524571-78ef0600-acda-11ea-8adc-51f3cf538421.png)

**Comment by elpaso** [comment]
@pigreco that's a different issue (`...`) please open another ticket and put there any other character issue.
