### ISSUE TITLE
Forms: fix for control visibility by expression needs to be backported to 3.10

### ISSUE THREAD

**Issue by andreasneumann** [qgis/QGIS#37154]
**Describe the bug**
Tabs in attribute forms can be shown/hidden based on an expression.

![image](https://user-images.githubusercontent.com/884476/84484513-27735680-ac9b-11ea-815c-7114c0aefe15.png)

While this works fine in QGIS master, it fails in QGIS 3.10.x

According to @m-kuhn the automatic backport of a fix in master to 3.10 failed and was forgotten to do it manually.

@m-kuhn can you please reference the fix in master?

**Comment by m-kuhn** [comment]
Failed backport here:

https://github.com/qgis/QGIS/pull/35985

**Comment by andreasneumann** [comment]
Backport seems to be done and works fine. Closing.
