### ISSUE TITLE
Strange format for python f-string in Python Console

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS#37160]
Playing a little with some code in Python console and using so called 'f-strings' [0][1]
They appear in a strange font? Smaller? See  screenie

![Screenshot-20200612125223-348x33](https://user-images.githubusercontent.com/731673/84495509-935dbb00-acab-11ea-9b9f-5dd5a10e0d4d.png)

To reproduce (here master on Debian), paste `print(f'writing {iface}')`  in the python console or a file

Is it because it is a 'new' python construct (since python 3.6) so we do not style for it yet, of is it deliberately (then it is just fine :-) )?

[0] https://realpython.com/python-f-strings/
[1] https://www.python.org/dev/peps/pep-0498/

**Comment by uclaros** [comment]
Can't reproduce on master on Debian testing.

![Screenshot_20200612_184557](https://user-images.githubusercontent.com/11358178/84520995-0fbcc200-acdd-11ea-9b66-6c931b191eff.png)

**Comment by rduivenvoorde** [comment]
Mmm, I am on Debian Testing too :-)

**Comment by rduivenvoorde** [comment]
Closing as I think this is because I used an old profile (with older default fonts).
Looks fine in a new profile.
