### ISSUE TITLE
Map canvas, right mouse button

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#37174]
how to reproduce the problem

1. open any project
2. right-click anywhere on the map canvas
3. special characters appear in the context menu

OSGeo4W64b win 10 QGIS 3.13 master

![image](https://user-images.githubusercontent.com/7631137/84528135-64f9d300-acdf-11ea-86a1-d103f31b5f67.png)

![image](https://user-images.githubusercontent.com/7631137/84528279-ab4f3200-acdf-11ea-8c41-f323565c332e.png)

**Comment by roya0045** [comment]
Wasn't that the bad encoding for the elipsis?

**Comment by rduivenvoorde** [comment]
Yes on Debian those are elipsis:

![Screenshot-20200612230146-525x129](https://user-images.githubusercontent.com/731673/84546055-bf575b80-ad00-11ea-8d4b-ad3056132c87.png)

**Comment by roya0045** [comment]
I recall there was a pr to fix this but maybe this was added after.

**Comment by rduivenvoorde** [comment]
Building now with:

`QString( "Set Custom CRS" ).append( QChar( 0x2026 )`

instead of

`QStringLiteral( "Set Custom CRS…" )`

Not sure if this is the best c++ way, but I'll try a PR :-)

**Comment by nyalldawson** [comment]
It's actually missing a tr here -- should be `tr("Set Custom CRS…" )`

**Comment by rduivenvoorde** [comment]
@nyalldawson I thought about that, but thought to see more Actions defined there which seemed to go with captions without tr()... That is why I thought: "Ok, maybe that is automated somewhere...."

Will this also fix the ellipse issue (so no need to do the 0x2026 trick)?
Or should it be:
`QString( tr( "Set Custom CRS" ) ).append( QChar( 0x2026 )`  
or something like that?

Feel free to ignore/close the PR, do whatever is easiest.
