### ISSUE TITLE
Error in function "$area" ?

### ISSUE THREAD

**Issue by theudebert** [qgis/QGIS#37173]
The function "$area" gives a result different from the function "area( $geometry )" !
I calculated the areas of some simple polygons in ArcGIS (9.3) and manually (Libreoffice Calc) and the values of "area( $geometry )" are correct!

I think anyone working with QGIS can easily reproduce this, but I also created a Zip-File with sample data and a sample project file:
[Flaechentest.zip](https://github.com/qgis/QGIS/files/4772138/Flaechentest.zip)

**Comment by gioman** [comment]
@theudebert QGIS version? Operating system?

**Comment by nyalldawson** [comment]
Read the documentation for the functions. They return different values by design.

**Comment by gioman** [comment]
area and $area are slightly different functions.
