### ISSUE TITLE
Memory bad allocation when trying to render mesh vectors in 3d

### ISSUE THREAD

**Issue by saberraz** [qgis/QGIS#37184]
Here is the stack trace:
```
ERROR: Status 4: Requested index is not valid: -1
ERROR: Status 4: Requested index is not valid: -1
../src/core/qgis.cpp:90 : (qgsMalloc) [31194ms] [thread:0x7fffac02f280] Negative or zero size 0.
../src/core/raster/qgsrasterblock.cpp:78 : (reset) [0ms] [thread:0x7fffac02f280] Couldn't allocate data memory of 0 bytes
../src/core/raster/qgsrasterblock.cpp:287 : (setIsNoData) [0ms] [thread:0x7fffac02f280] Image not allocated
need for update
../src/core/raster/qgssinglebandpseudocolorrenderer.cpp:216 : (block) [657ms] [thread:0x7fffac02f280] No raster data!
../src/core/qgsapplication.cpp:447 : (notify) [13335ms] Caught unhandled std::exception: std::bad_alloc
[Thread 0x7fff588d8700 (LWP 2191821) exited]
[Thread 0x7fffb77fe700 (LWP 2191765) exited]
[Thread 0x7fffb7fff700 (LWP 2191764) exited]

```

![image](https://user-images.githubusercontent.com/2649047/84565830-fc086e80-ad63-11ea-836d-dcfe385de5f8.png)

**Comment by vcloarec** [comment]
Issue that comes from arrows spacing parameter that is too small, so the vector grid have too much cells to go in memory... This small arrows spacing comes from your project file that was created before 3D arrows feature, so QGIS doesn't find  this parameter and set ii to 0, and as the spin box has minimum value at 1, the 3D rendering use a arrow grid with a spacing of 1 m... So too much arrow.
Fix by #37195 to avoid the bad alloc message if spacing too small and to prevent having this too much small spacing with project file before this feature.
