### ISSUE TITLE
Count of features is displayed only for the last selected layer of the layout legend

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#37194]
Layout legend items properties --> Layout items section
Select many layers and press the "show feature count" button
Only the last selected layer gets the count

![nosumLegendItem](https://user-images.githubusercontent.com/7983394/84582369-7c25e700-adeb-11ea-8e40-6ab3902c0030.gif)

Actually afaics, the "move up"/"move down" as well as the "edit properties" tools behave the same: they are available when multiselection is done but only act on the last selected item.

**Comment by roya0045** [comment]
Version?

**Comment by roya0045** [comment]
It is present in 3.12.0

**Comment by DelazJ** [comment]
I tried on master, a couple of days old

**Comment by roya0045** [comment]
Yeah most of those use 
  QModelIndex currentIndex = mItemTreeView->currentIndex();
  QgsLayerTreeNode *currentNode = mItemTreeView->currentNode();

This seem to have always been the case.
