### ISSUE TITLE
WMS GetFeatureInfo on time enabled layer does not pass TIME parameter

### ISSUE THREAD

**Issue by tomkralidis** [qgis/QGIS#37191]
**Describe the bug**

Using the new temporal functionality in QGIS nightly, adding a time enabled WMS results in GetFeatureInfo requests not passing `TIME` accordingly.  This results in values on the canvas not corresponding to the values of a given point/pixel when using the identify tool.

**How to Reproduce**

1. Add https://geo.weather.gc.ca/geomet via the WMS provider
2. Enable temporal capability
3. Click the 'identify' tool
4. Show Debugging/Development Tools Panel
5. Query any part of the temporal layer on the map canvas
6. See resulting GetFeatureInfo request in Debugging/Development Tools Panel without `TIME=` passed

**QGIS and OS versions**

QGIS nightly (as of 2020-06-12, from OSGeo4W)

**Additional context**
cc @dukestep

**Comment by timlinux** [comment]
@Samweli can you crack this nut for us please

**Comment by Samweli** [comment]
> @Samweli can you crack this nut for us please

Sure @timlinux, check out https://github.com/qgis/QGIS/pull/37265

**Comment by janveres** [comment]
Hello, qgis 3.18.0 has still this bug, can anybody take a look on it and add the Time parameter to GFI call? thanks
curl 'https://geo.weather.gc.ca/geomet?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&BBOX=58.37233146067413259,-168.08258426966281718,64.27858146067413259,-155.77900280898867891&CRS=EPSG:4326&WIDTH=927&HEIGHT=445&LAYERS=RADAR_1KM_RDBR&STYLES=&FORMAT=image/png&QUERY_LAYERS=RADAR_1KM_RDBR&INFO_FORMAT=application/vnd.ogc.gml&I=327&J=302' -H 'User-Agent: Mozilla/5.0 QGIS/31800'  --compressed

**Comment by gioman** [comment]
> Hello, qgis 3.18.0 has still this bug,

@janveres better file a new ticket.
