### ISSUE TITLE
Freeze when showing attribute table of WFS layer

### ISSUE THREAD

**Issue by 3nids** [qgis/QGIS#37224]
How to reproduce: open a project with WFS layer, try to open attribute table

notice: in this scenario, the credentials are not saved in the project or in the auth manager, but entered at opening of the project (I did not test yet in a different manner)

Here are the different stacks

![image](https://user-images.githubusercontent.com/127259/84635626-c2666d80-aef3-11ea-8486-c58084a58203.png)

![image](https://user-images.githubusercontent.com/127259/84635758-f2ae0c00-aef3-11ea-89b2-277374cd7b97.png)

![image](https://user-images.githubusercontent.com/127259/84636684-263d6600-aef5-11ea-835c-f086d3e8e010.png)

I tried to add a processEvents in `QgsBackgroundCachedFeatureIterator::fetchFeature`, but this brings the freeze to another place (which after a few tries seems to alternate with the first stack above):

![image](https://user-images.githubusercontent.com/127259/84637191-b4195100-aef5-11ea-95ac-04a0ba6a8998.png)

**Comment by 3nids** [comment]
No issue on 3.4.12
Issue reported for 3.10 and confirmed on master.

Most likely, the regression is coming from this commit:  531ba0d6f7b

ping @rouault @nyalldawson

**Comment by 3nids** [comment]
on request, I can provide a demo project

**Comment by gioman** [comment]
@3nids is this specific to a particular service/project? does not seems to be a general issue.

**Comment by 3nids** [comment]
yes, this is for a specific layer.

I could track a bit more the issue:

using the authentication manager solves the issue, which allowed me to see the layer is actually empty.

So, to reproduce the freeze: empty layer + no saved credentials.

**Comment by 3nids** [comment]
apparently removing `restrictToRequestBBOX='1'` in the map layer definition in the project file fixes the issue.
It does sound strange as it's there for any layer and we cannot choose this when loading the layer.
I'll investigate, but if anyone has a clue...

**Comment by rouault** [comment]
@3nids Can you email me the project to reproduce and the layer ?

**Comment by 3nids** [comment]
I just asked to restore the project. I'll let you know asap.

**Comment by 3nids** [comment]
I just sent you the project @rouault
