### ISSUE TITLE
Crash during zoom and pan

### ISSUE THREAD

**Issue by pirx3** [qgis/QGIS#37228]
**Describe the bug**
## User Feedback

QGIS crashed when zooming in on the map view. 

## Report Details

**Crash ID**: [fb655ddf1ace25c93b0ba43c8b28391ee016d79e]('https://github.com/qgis/QGIS/search?q=fb655ddf1ace25c93b0ba43c8b28391ee016d79e&type=Issues')

**Stack Trace**
<pre>
GEOSEquals_r :
GEOSEquals_r :
QgsGeos::shortestLine :
QgsGeometry::shortestLine :
QgsSymbolLayerId::operator< :
QgsSimpleLineCallout::draw :
QgsCallout::render :
QgsVectorLayerLabelProvider::drawCallout :
QgsVectorLayerLabelProvider::drawLabelBackground :
QgsLabelingEngine::drawLabels :
QgsDefaultLabelingEngine::run :
QgsMapRendererJob::drawLabeling :
QgsMapRendererParallelJob::renderLabelsStatic :
QgsLabelingEngine::results :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.12.1-Bucure?ti
QGIS code revision: 121cc00ff0
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by gioman** [comment]
@pirx3 not enough infos: 

add detailed steps that lead to the crash. If necessary attach/link a sample project with data and... try a new QGIS profile.

**Comment by roya0045** [comment]
Seems to be a callout error, a sample project might also be needed.

**Comment by nyalldawson** [comment]
It's likely this was fixed in 3.12.3 already

**Comment by pirx3** [comment]
QGIS will crash each time when I apply the style from the attached style definition file to the attached shape file. Occasionaly this will happen not immediataly after applying but druing pan and zoom. 


[Maßnahmen_Areas.zip](https://github.com/qgis/QGIS/files/4784738/Massnahmen_Areas.zip)
[Auswertung_0620-1221 RoadsMeasure.zip](https://github.com/qgis/QGIS/files/4784740/Auswertung_0620-1221.RoadsMeasure.zip)

**Comment by pirx3** [comment]
Attached also the QGIS project file. 
[Crash_Project.zip](https://github.com/qgis/QGIS/files/4784760/Crash_Project.zip)

**Comment by pirx3** [comment]
I figured out that after removing the leader lines to the labels, the crash is not happening anymore.

**Comment by nyalldawson** [comment]
You need to upgrade to 3.12 -- I'm almost certain this one has already been fixed.

**Comment by gioman** [comment]
Closing for lack of feedback.
