### ISSUE TITLE
Attempting to create a new feature in Spatialite with transaction group and NOT NULL constraint fails

### ISSUE THREAD

**Issue by jdugge** [qgis/QGIS#37236]
When attempting to create a new feature through the Attribute Table of a Spatialite layer that is part of a transaction group and contains a field with a "NOT NULL" constraint without default values a critical SQLite error is thrown: 
```
CRITICAL    Layer airlines : SQLite error: NOT NULL constraint failed: airlines.airline_name
             SQL: INSERT INTO "airlines"( "airline_name") VALUES ( ?)
```
![Peek 2020-06-15 22-43](https://user-images.githubusercontent.com/2399255/84704203-c200bd80-af59-11ea-8de2-ed36ded344fc.gif)

Apparently, when opening the feature form with the new feature, the constraints are prematurely evaluated on the database side. When creating a new feature using the "Add Feature" map tool, the error does not appear (but this causes different problems, see #37222).

Example project and database:
[many_to_many_sqlite.zip](https://github.com/qgis/QGIS/files/4782892/many_to_many_sqlite.zip)

**Comment by elpaso** [comment]
Did you add `DEFERRABLE INITIALLY DEFERRED` to the FK constraints https://www.sqlite.org/foreignkeys.html? I think it's mandatory for this use case.

**Comment by jdugge** [comment]
Yes, the foreign keys have `DEFERRABLE INITIALLY DEFERRED`. The create statements for the tables are

```sql
CREATE TABLE airlines
(
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   airline_name text NOT NULL
)

CREATE TABLE airports
(
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   airport_name text NOT NULL
)

CREATE TABLE airports_airlines
(
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   airport_fk INTEGER
   	REFERENCES airports
   	ON DELETE CASCADE
   	ON UPDATE CASCADE
   	DEFERRABLE INITIALLY DEFERRED,
   airline_fk INTEGER
   	REFERENCES airlines
   	ON DELETE CASCADE
   	ON UPDATE CASCADE
   	DEFERRABLE INITIALLY DEFERRED
)
```

**Comment by elpaso** [comment]
I'm afraid this is a won't fix: the logic behind transaction groups is that a transaction is initiated, then all changes (like when you add a new feature) are sent to the back-end (the DB) immediately for evaluation, the transaction is committed or rolled back when the user saves the changes in any of the layers belonging to the transaction group.

This implementation makes it possible to get the pk value and use it to create "child" features without breaking foreign key constraints or to evaluate a default value directly on the back-end (e. g. sequences, serials etc.).

This works well on SQLITE in the case of foreign keys as long as you set them as deferrable, but there is no deferrable equivalent for `NOT NULL` so this will always fail.

A possible workaround:

![immagine](https://user-images.githubusercontent.com/142164/84757855-f8275700-afc4-11ea-9e08-763f0bed8141.png)

Feel free to re-open if you think there might be other solutions or I missed something.

**Comment by jdugge** [comment]
@elpaso: That does make sense, and it's also what happens with PostGIS layers. However, this doesn't happen with Geopackage layers with the same NOT NULL constraint (see #37222) - in that case, the ID is fetched from the database without baulking at the missing text.

I think it would be better if the failed validation was shown in the text field, giving the user a chance to correct the entry, rather than the current behaviour of failing outright:

![image](https://user-images.githubusercontent.com/2399255/84770002-1e55f280-afd7-11ea-88bf-472e8ae1307e.png)

I'm not sure how this could be implemented, though.

**Comment by elpaso** [comment]
@jdugge do you mind attaching the GPKG sample project? I'd like to check why it behaves differently.

GPKG uses GDAL/OGR directly while the spatialite and postgis provider are native QGIS implementations.

**Comment by jdugge** [comment]
Sure thing: [many_to_many_geopackage.zip](https://github.com/qgis/QGIS/files/4786358/many_to_many_geopackage.zip)
