### ISSUE TITLE
"Automatically hide georeferencer window" option does not correctly restore georeferencer dialog position

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#37230]
I'm georeferencing rasters, using two monitors: QGIS main canvas in the first monitor and the georeferencer dialog in the second one.
1. Select "Add point" button
1. Click the place in the georeferencer window. The "Enter Map coordinates" dialog opens.
1. Select "From map canvas" in that dialog. The georeferencer dialog is reduced
1. Click the actual placement in the main window. The georeferencer and the "Enter map coordinates" dialogs reopen BUT... the georeferencer dialog is not placed at its previous position. I often get it, overlapping the two monitors (somewhat at the middle of the two screens width). This means that I have to move it fully to the second monitor before adding the next gcp point.

This happened until I decided to report and, writing down the steps one by one made me realize that the culprit is the "Automatically hide georeferencer window" option in the "Enter Map coordinates" dialog. Once I unchecked it, I no longer reproduce the issue (normal, the dialog does not hide/show anymore).
But whether this option is checked or not, I think the georeferencer dialog should honor its previous placement (as long as the monitor exists)

Using master 3.13 e9a0c01b21 on Windows 10

**Comment by uclaros** [comment]
This might be a dual monitor thing; in my system the position is kept.
Also, with #37267 it should matter less, just hit space regardless of where the dialog spawns.
