### ISSUE TITLE
Background option in Rules-based labeling creates a shape for each character in the text

### ISSUE THREAD

**Issue by alexandreparente** [qgis/QGIS#37239]
**Describe the bug**
Background option in Rules-based labeling creates a shape for each character in the text

**How to Reproduce**

1. Select the Rule-Base labeling option in the main drop-down list.
2. Define a ruler.
3. Click on the background menu.
4. Set a regular shape such as Rectangle.
5. See error: qgis creates a rectangle for each character in the text.

![Background_rule_label](https://user-images.githubusercontent.com/5301826/84714320-b99d8800-af43-11ea-96e7-8d60794eafd4.png)

Select the Single label labeling option from the main drop-down list and set a regular shape.
Qgis works fine!

![Background_single_label](https://user-images.githubusercontent.com/5301826/84714335-befad280-af43-11ea-8db2-083d2ad483f1.png)

**QGIS and OS versions**

QGIS version | 3.10.3-A Coruña | QGIS code revision | 0e1f8464

Compiled against Qt | 5.12.6 | Running against Qt | 5.12.7
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.7.3-CAPI-1.11.3 | Running against GEOS | 3.7.3-CAPI-1.11.3 b50468f
Compiled against SQLite | 3.27.2 | Running against SQLite | 3.27.2
PostgreSQL Client Version | 12.2 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | KDE Flatpak runtime
Active python plugins | kmltools; refFunctions; CalculateGeometry; latlontools; mapswipetool_plugin; mmqgis; principalcomponents; CalcArea; polystrip; ImportPhotos; quick_map_services; ibama_expressions; MetaSearch; db_manager; processing

AND

Versão do QGIS | 3.12.3-București | Código da versão do QGIS | 8234261527

Compilado sobre Qt | 5.12.8 | Rodando sobre Qt | 5.12.8
Compilado sobre GDAL/OGR | 3.0.4 | Rodando sobre GDAL/OGR | 3.0.4
Compilado sobre GEOS | 3.8.0-CAPI-1.13.1 | Rodando sobre GEOS | 3.8.0-CAPI-1.13.1
Compilado no SQLite | 3.31.1 | Executando contra SQLite | 3.31.1
Versão do cliente PostgreSQL | 12.2 (Ubuntu 12.2-4) | Versão SpatiaLite | 4.3.0a
Versão do QWT | 6.1.4 | Versão QScintilla2 | 2.11.2
Compilado com PROJ | 6.3.1 | Em execução com PROJ | Rel. 6.3.1, February 10th, 2020
Versão SO | Ubuntu 20.04 LTS
Ativar complementos python | qgis_gee_data_catalog; refFunctions; QuickOSM; latlontools; ee_plugin; rectanglify; mmqgis; send2google_earth; SpreadsheetLayers; sentinel2_download; db_manager; processing

**Comment by nyalldawson** [comment]
Are you sure this isn't related instead to the "curved" placement mode?

**Comment by alexandreparente** [comment]
Yes, it's related :)
