### ISSUE TITLE
Copy a Polygon Symbology Layer to a Point Symbology layer

### ISSUE THREAD

**Issue by atabaraud** [qgis/QGIS#37232]
Hi,

There is a problem with QGIS styles because you can't copy a Polygon Symbology Layer to a Point Symbology layer.

You can't do this with a right click on the layer and a left click on the copy or paste style button, it is understandable because polygones and points layer are différent.

But a good functionality will be to have th possibility to copy the color, the value and the legend from the categorise symbol window of a polygon layer and copy it to the categorise symbol window of a point layer. 

![image](https://user-images.githubusercontent.com/38242880/84666985-0bcdb180-af22-11ea-8b86-757014b56c67.png)

**Comment by Saijin-Naib** [comment]
Related: #37232 ?

**Comment by alexbruy** [comment]
Duplicates #14251.
