### ISSUE TITLE
Cannot edit attributes from PostgreSQL tables with floating point PKs

### ISSUE THREAD

**Issue by espinafre** [qgis/QGIS#37245]
Given the following PostgreSQL/PostGIS table:

```sql
CREATE TABLE qgis_test.tb_test_float_pk
(
    pk REAL PRIMARY KEY,
    value VARCHAR(16),
    geom geometry(Point, 4326)
);
INSERT INTO qgis_test.tb_test_float_pk (pk, value, geom) VALUES
    (3.14159, 'first test', ST_SetSRID(ST_Point(-47.887, -15.864), 4326)),
    (2.71828, 'second test', ST_SetSRID(ST_Point(-47.902, -15.763), 4326));
```

The attribute table is correctly shown, but the attributes cannot be edited/saved with QGIS master:

![qgis_edit_float_pk](https://user-images.githubusercontent.com/25933044/84731269-b8358500-af6e-11ea-84ff-0fc523928269.gif)

This was discovered while preparing the test cases for #37172

**Comment by uclaros** [comment]
This looks like an attribute table issue, not a Postgres. Can you try updating the fields with the field calculator?

**Comment by espinafre** [comment]
Yes, the result is equivalent:

![editing_floats_fieldcalc](https://user-images.githubusercontent.com/25933044/84785349-cb257500-afc1-11ea-9a7f-4d25f6e42675.gif)

I've found that quoting floating point PKs in WHERE clauses solves this issue, but there are differences between how PostgreSQL 11 and 12 handle floating points. I'm waiting for #37172 to be merged; as soon as it is in tree, I will open a PR to better discuss the issue and hopefully fix this.

**Comment by espinafre** [comment]
While tackling this issue, I've found that, for the PostgreSQL provider at least, the NUMERIC/DECIMAL data type (which is an arbitrary precision type in the DB) is restricted to 20 digits (src/providers/postgres/qgspostgresprovider.cpp:232) then cast to double, regardless of the original table type specification.

Given the following table definition and data:

```sql
CREATE TABLE qgis_test.tb_test_numeric_pk
(   
    pk NUMERIC(41, 40) PRIMARY KEY,
    value VARCHAR(16),
    geom geometry(Point, 4326)
);
INSERT INTO qgis_test.tb_test_numeric_pk (pk, value, geom) VALUES
    (3.1415926535897932384626433832795028841972, 'first teste', ST_SetSRID(ST_Point(-47.887, -15.864), 4326)),
    (2.7182818284590452353602874713526624977572, 'second test', ST_SetSRID(ST_Point(-47.902, -15.763), 4326)),
    (1.3333333333333333333333333333333333333333, 'third teste', ST_SetSRID(ST_Point(-47.751, -15.644), 4326));
```

This is how current QGIS shows it:
![image](https://user-images.githubusercontent.com/25933044/85332608-a2641a80-b4ae-11ea-8f56-fea102911d4c.png)

The issue can be easily seen on the first row, and the table data cannot be edited; in this case, the value is a PK, but the issue with a non-pk field would be silent loss of precision for NUMERIC fields with precision greater than 15 or so; the attribute table does not reflect what is actually on the database.

For the PostgreSQL REAL (32 bit IEEE-754) and DOUBLE PRECISION (64 bit IEEE-754) types, I've found that changing the PostgreSQL connection variable extra_float_digits to 3 and quoting the values before sending them to the DBMS is sufficient to resolve this issue.

However, since in QGIS the NUMERIC(X, Y) DBMS type is cast to double, this quoting will not work, at least not for primary keys (but ordinary values are correctly saved - with the limitation of casting to double as I've pointed above).

You, more experienced QGIS hackers, what do you think could be done? Is there a way for QGIS to work with arbitrary precision values? Or should these limitations be clearly shown on the documentation - which is, by the way, out of date:

https://docs.qgis.org/testing/en/docs/user_manual/managing_data_source/supported_data.html#primary-key

Current supported primary key types are INTEGER, BIGINT, or anything that is representable as text - which QGIS internally will convert to/from text via the FID map mechanism. Also, the user's documentation doesn't mention clearly that arbitrary precision types are NOT currently supported:

https://docs.qgis.org/testing/en/docs/user_manual/managing_data_source/supported_data.html#support-of-postgresql-data-types

So, what do you think?

**Comment by espinafre** [comment]
@nyalldawson and @elpaso , I would greatly appreciate your input on this, thank you very much!
