### ISSUE TITLE
"Set width" and "hide column" have no effect in table view in relation widget

### ISSUE THREAD

**Issue by jdugge** [qgis/QGIS#37252]
When showing the table view for a relation widget right-clicking on a table column header opens a context menu containing the entries "hide column" and "set width", but clicking these has no effect.

Columns can be hidden using the "organize columns" menu, and the width of the columns can be set by dragging the column header boundaries.

![Peek 2020-06-16 20-59](https://user-images.githubusercontent.com/2399255/84816205-6ba48500-b014-11ea-9453-db06ccd34ac3.gif)

**Comment by SrNetoChan** [comment]
@jdugge does change the hidden and width on the original table "airports_airlines" has any effect?

**Comment by jdugge** [comment]
@SrNetoChan No, the table view for the relation widget always uses the same column widths and visibility.

I've attached a sample project for testing:
[many_to_many_geopackage.zip](https://github.com/qgis/QGIS/files/5197786/many_to_many_geopackage.zip)

**Comment by jdugge** [comment]
@gioman Is more detailed feedback required, or can the Feedback label be removed for now?
