### ISSUE TITLE
Crash/freeze during Voronoi Analysis with large input dataset

### ISSUE THREAD

**Issue by squareIz** [qgis/QGIS#37263]
## User Feedback

I was performing a voronoi analysis on postcode centroids in the uk, approx 1.3M points.  Progress to 99% complete was very quick then spent hours (8+) using 50% of CPU (2 core system) before crashing. Memory usage was about 3Gig throughout.

## Report Details

**Crash ID**: [ee2e21046ae5579cc2f96cda25bc7b17113a2b5d]('https://github.com/qgis/QGIS/search?q=ee2e21046ae5579cc2f96cda25bc7b17113a2b5d&type=Issues')

**Stack Trace**
<pre>
QObject::thread :
QgsProcessingAlgorithm::runPrepared :
QgsProcessingAlgRunnerTask::run :
PyInit__core :
QgsTask::start :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.12.1-Bucure?ti
QGIS code revision: 121cc00ff0
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
@squareIz can you post the link to the dataset? Thanks.

**Comment by squareIz** [comment]
Glad to upload, but the file is 63MB zipped, if you give me a location to download it too I'll send it through.

**Comment by gioman** [comment]
@squareIz use google drive, dropbox, or similar(?).

**Comment by squareIz** [comment]
Sure, here's the link in [DropBox](https://www.dropbox.com/s/fil6ly2dfmmm1v3/GeoPostCode.zip?dl=0) ... its an sqlite file

Let me know if you have any problems reading the file and when you have it and I'll then remove it from DropBox.

**Comment by gioman** [comment]
I see the same on master/linux. Changing format and crs to the input didn't made any difference. Moreover the process is unstoppable and QGIS must be killed.

**Comment by squareIz** [comment]
Thanks for looking into this, unless you have any suggestions I'll try with a smaller data set when I get chance,

**Comment by root676** [comment]
This long delay of the voronoi algorithm is caused by the python implementation for polygon clipping which is performed right after the voronoi calculation. The algorithm will probably finish without if you just give it enough time. I already had a look at the code as this algorithm would be my number 1 favorite for porting to C++, but it is rather complex. I think this issue can only be solved if the algorithm is reworked (preferably in C++) and the inefficient clip mechanic gets replaced.

**Comment by squareIz** [comment]
Thanks for your help, I just tried with a much smaller data set <10k points and it worked without problem.

If anyone out there does the C++ rewrite then please let me know as it will help alot.

As far as waiting for it to complete, the program crashes after about 11 hours as per the original messgae.

Thanks again

**Comment by Pedro-Murteira** [comment]
Still valid on QGIS 3.22.4 and 3.24.0.

**Comment by merkato** [comment]
Same problem with 2.2M points dataset on 3.30.3 - small datasets (about 25k points) very slow (about 15 min on i7-4810MQ CPU @ 2.80GHz/32GB RAM)

**Comment by alexbruy** [comment]
On the latest master using provided dataset creating voronoi poilygons takes ~2-3 mins and there is no crash.
