### ISSUE TITLE
Lookups in tables with more than 100 entries show wrong value in Relation Reference form parts

### ISSUE THREAD

**Issue by Tugark** [qgis/QGIS#37266]
**Describe the bug**

**In short:** Having lookup tables with more than 100 entries which are specified as Relation Reference in Object Forms default to the first entry in the lookup table when the form is opened. This happens for existing objects, so it essentially displays an incorrect value. This only happens when the Reference attribute is declared as not allowing for NULL values.

**Detailed description:** We have lookup tables with more than 100 entries. These are defined as relations and used in forms as Relation Reference:
![image](https://user-images.githubusercontent.com/16555423/84866594-33d02880-b07a-11ea-9d73-1cef031ffea0.png)

For objects whose lookup ID is within the first 100 entries of the lookup table, everything works fine:
![image](https://user-images.githubusercontent.com/16555423/84866484-1307d300-b07a-11ea-8ae7-fc0c7086680a.png)

However, if the lookup ID is above the first 100 entries, the value is defaulted to the first entry in the lookup table when the form is opened. The selection results window shows the correct ID, however.
![image](https://user-images.githubusercontent.com/16555423/84866678-55311480-b07a-11ea-93c7-77593c20908e.png)

This bug is problematic, because if you open the form in Edit mode and save the object, the lookup ID is overwritten (in the above case, the tree with ID 2625 would turn to an Abies alba).

A temporary workaround is to allow NULL-values on the form:
![image](https://user-images.githubusercontent.com/16555423/84866809-86a9e000-b07a-11ea-84da-fbb61159c9f7.png)
 
This leads to the correct display of the ID. In that case, the above example shows the correct ID:
![image](https://user-images.githubusercontent.com/16555423/84866854-99bcb000-b07a-11ea-8bf3-2eae4fae7124.png)

**How to Reproduce**

I attached a sample geopackage, consisting of an object table with geometries (tree) and an attribute table (tree_types). tree has two objects, one with a lookup ID < 100, and one with a lookup ID > 100 (the data shown in the screenshots above).

[tree.zip](https://github.com/qgis/QGIS/files/4790931/tree.zip)

**Steps:**
1. Load both Geopackage layers
2. Define the relation in project settings as follows:
![image](https://user-images.githubusercontent.com/16555423/84867254-25364100-b07b-11ea-8792-965c474711ad.png)
3. Configure the form for the "tree" object as shown in the screenshots above (default values are fine, except the NULL configuration)
4. Open the form and notice how the lookup field changes on the tree bject whose ID is > 100 (Salix caprea changes to Abies alba)
5. Turn on "Allow NULL values" on the form
6. Notice how the field now correctly displays the ID.

You can also add more trees and play around with it.

**QGIS and OS versions**

We are using Windows 10 (various builds) and QGIS 3.10.5.

**Additional context**

While I only attached a Geopackage, we discovered this behaviour with auto-loaded PostGIS relations (Foreign Keys). It also happens with manual relations on PostGIS and in the Geopackage as well.

We also noticed that if we do not use the Relation Reference but the Value Reference, everything works nicely.

I'll be happy to provide more details if needed.

**Comment by andreasneumann** [comment]
@Tugark - could you please also attache a minimal QGIS project with the relation and relation reference widget set up correctly? I am trying to reproduce it here and this would help speed up the bug fixing process a bit.

**Comment by andreasneumann** [comment]
I confirm the issue. I am attaching a sample project.
[relation_reference.zip](https://github.com/qgis/QGIS/files/4791193/relation_reference.zip)

**Comment by andreasneumann** [comment]
Issue appears in master and a recent 3.10. In 3.4, the bug is not present.

**Comment by 3nids** [comment]
Strange, with 3.12 on mac, this seems OK:
![image](https://user-images.githubusercontent.com/127259/84879405-764e3100-b08b-11ea-9368-814487e92de1.png)

**Comment by Tugark** [comment]
@3nids Did you use the QGIS project added by @andreasneumann ? If so, I think the default is already set to "Allow NULL values". When you change this in the form on the "tree" layer, the behaviour as described in the issue appears.

I could reproduce the same behaviour with @andreasneumann's project, but I had to change the "Allow NULL values".

**Comment by andreasneumann** [comment]
> Strange, with 3.12 on mac, this seems OK:
> ![image](https://user-images.githubusercontent.com/127259/84879405-764e3100-b08b-11ea-9368-814487e92de1.png)

I haven't tested 3.12.

Did you disable the "Allow Null Values" checkbox? I guess so, because otherwise we would see "NULL" in the list in your screenshot

**Comment by andreasneumann** [comment]
It could also be that the issue only appears in recent 3.10 and master, due to some recent backports - but I wouldn't know which backport that could be.

**Comment by andreasneumann** [comment]
I will compile 3.12 and test there (on Linux).

**Comment by 3nids** [comment]
> Did you disable the "Allow Null Values" checkbox? I guess so, because otherwise we would see "NULL" in the list in your screenshot

yes

**Comment by 3nids** [comment]
> It could also be that the issue only appears in recent 3.10 and master, due to some recent backports - but I wouldn't know which backport that could be.

I don't see anything yet in the backports.
I am now compiling master to test.

**Comment by 3nids** [comment]
so... yes, issue is confirmed in master on my side, but no issue on 3.12.

To summarize:
3.4: OK
3.10: NOK
3.12: OK
master: NOK

this is getting funnier!

**Comment by 3nids** [comment]
There were a few backports for 3.12: https://github.com/qgis/QGIS/pull/35198
Decision was taken not to backport to 3.10. 
@troopa81 any opinion here?

I will investigate for master what is the issue.

**Comment by andreasneumann** [comment]
hm strange. On my 3.12 build (https://github.com/qgis/QGIS/commit/8234261527) ist is also not ok. The bug also appears on 3.12 on Linux at my system.

**Comment by 3nids** [comment]
I tested 3.12.0.
So, I guess the issue was brought by PR #35198 which is a backport after 3.12.0, so it's in the version you tested.
It has finally been backported too to 3.10: #35783

**Comment by 3nids** [comment]
see PR #37280

**Comment by Tugark** [comment]
Great, would be nice having a fix that fast :-) 
Will this fix also be applied to Qgis 3.10.x or do we have to upgrade to 3.12?
