### ISSUE TITLE
QGIS 3.12.3-2 not showing maps from tile servers when zoom in

### ISSUE THREAD

**Issue by juanmafont** [qgis/QGIS#37272]
After updated this morning (previous version QGIS 3.12.3-1 all ok) can not load layers from tiled web servers. Qgis keep loading but screen keep blanck, the if a try exit from qgis, not success (keep trying load tiled layers)

Using manjaro xfce.

**Comment by gioman** [comment]
@juanmafont any tile server URL we can test?

**Comment by kmcdon** [comment]
@gioman Hi, I seem to also be having the same issue. I could get you some tileserver lists if you need them, but it doesn't seem to care what servers are used. I've tried opening the same project files on OSX/qgis 3.12 and it works fine, but on my linux box it constantly crashes. This started after the update to 3.12.3. Arch linux, KDE Plasma.

I've been unsuccessful in getting debug logging to work, but if you have any tips on how to get that working I'd be glad to get you some logs.

![Screenshot_20200617_082641](https://user-images.githubusercontent.com/21297463/84910724-77279880-b074-11ea-8ccd-4ecd008634c2.png)

**Comment by kmcdon** [comment]
https://github.com/qgis/QGIS/issues/36197
https://github.com/qgis/QGIS/issues/36203

all seem related

**Comment by juanmafont** [comment]
> @juanmafont any tile server URL we can test?

Like kmcdon said, no matter what tile server try, I have tried with default tile server (XYZ tiles openstreetmap) come with QGIS, but if you try it with another from QuickMapServices plugin also fails.
 When you add a layer from tiles server, layers are added, but keep trying load data till infinite. Qgis not crash, keep waiting and you can do other actions, but if you try exit from Qgis, then Qgis says that are some tasks running at backgroud and not exit (you must kill QGIS).  If you see at status bar, left down, you can see two temporal bars.... (there is three tiled layers), always area showed one less time bars than opened tiled layers.
![Screenshot_2020-06-18_12-09-13](https://user-images.githubusercontent.com/6154911/85008240-fe503b80-b15c-11ea-8aa0-9f789369edf8.jpg)

**Comment by juanmafont** [comment]
**IMPORTANT ¡¡¡¡**
   I had discover that if open 'XYZ tile openstreetmap' server layer and do it zoom slowly (waiting every level of zoom be fully loaded) then, the tile map layer is loaded, the problem come if you try load (with mouse wheel) do it zoom over a zoom level that still is not loaded.

**Comment by gioman** [comment]
>  had discover that if open 'XYZ tile openstreetmap' server layer and do it zoom slowly (waiting every level of zoom be fully loaded and all graphic info is showed into map) then, the tile map layer is loaded, the problem come if you try (with mouse wheel) do it zoom over a zoom level that still is not loaded.
> 
> The problem appears when several concurrent requests are launched to increase the zoom level without waiting for the full load of the previous requests.
> 
> Here you can see video:
> https://drive.google.com/file/d/1AxpnKqpz16emDNraJ-gV7My7k672MlpG/view?usp=sharing

I partially replicated the above here on master/ubuntu 18.04: if you scroll the mouse wheel like crazy then the xyz osm layer gets stuck, but after a few moments here it renders as expected.

**Comment by d7rk** [comment]
I have the exact same issue as @juanmafont on Manjaro gnome stable with latest qgis (3.12.3).
It crashes when zooming or when moving to areas not already cached.

**Comment by juanmafont** [comment]
> > had discover that if open 'XYZ tile openstreetmap' server layer and do it zoom slowly (waiting every level of zoom be fully loaded and all graphic info is showed into map) then, the tile map layer is loaded, the problem come if you try (with mouse wheel) do it zoom over a zoom level that still is not loaded.
> > The problem appears when several concurrent requests are launched to increase the zoom level without waiting for the full load of the previous requests.
> > Here you can see video:
> > https://drive.google.com/file/d/1AxpnKqpz16emDNraJ-gV7My7k672MlpG/view?usp=sharing
> 
> I partially replicated the above here on master/ubuntu 18.04: if you scroll the mouse wheel like crazy then the xyz osm layer gets stuck, but after a few moments here it renders as expected.

Hello, @gioman, please, can you test with a map zone not cached.  The problem only happens with not cached map zones, and not waiting to full load of image, doing recurrents zoom.  Thanks.

**Comment by gioman** [comment]
> please, can you test with a map zone not cached.

@juanmafont same observation as before.

**Comment by JohnProv** [comment]
I experience the same issue, Qgis 3.12.3, Arch Linux + KDE.
The following configuration setting helps to reduce the number of times the problem occurs:
Options > Rendering > uncheck 'Render layers in parallel using many CPU cores'.
Thus the problem seems to have to do with parallel downloading/caching/rendering. Slow zooming does not cause the problem, but quick zooming.

**Comment by juanmafont** [comment]
Hi, please close this issue. Must be a library problem of Arch/Manjaro version.

  Exact version using Flatpak QGIS goes ok with Manjaro XFCE.

**Comment by JohnProv** [comment]
See the comments in https://bugs.archlinux.org/task/67057
It seems to not be a problem of Arch Linux.
Can someone look at this annoying problem?

**Comment by Scimmia22** [comment]
It's a bug in Qt 5.15, fixed in https://code.qt.io/cgit/qt/qtbase.git/patch/?id=9d2b474b

Don't be so quick to blame the distro when you bundle old/obsolete libs in the flatpak
