### ISSUE TITLE
Python code associated to a ui form doesn' work in QGIs 3.10.6

### ISSUE THREAD

**Issue by sigmoe** [qgis/QGIS#37279]
**Describe the bug**
A simple python code associated to a personnal ui form doesn't work in QGIS 3.10 whereas it works very well in QGIS 3.4

**How to Reproduce**
1) Add a simple ui form
2) Associate a simple Python code (with a .py external file or directly in internal)
3) Try it using the identify tool on one object of the layer
4) An error message appears:
SystemError: PyEval_EvalFrameEx returned a result with an error set 
Traceback (most recent call last):
  File "", line 1, in 
NameError: name 'test_form_open' is not defined
The above exception was the direct cause of the following exception:
SystemError: PyEval_EvalFrameEx returned a result with an error set
use the identify tool to identify one oobject in the canas

You can try it with my example (attached files). There's no wrong python code: the same code works very well in QGIS 3.4 without any error.

**QGIS and OS versions**

Version de QGIS
3.10.6-A Coruña
Révision du code
ec80021f49
Compilé avec Qt
5.11.2
Utilisant Qt
5.11.2
Compilé avec GDAL/OGR
3.0.4
Utilisé avec GDAL/OGR
3.0.4
Compilé avec GEOS
3.8.1-CAPI-1.13.3
Utilisé avec GEOS
3.8.1-CAPI-1.13.3
Compilé avec SQLite
3.29.0
Fonctionne avec SQLite
3.29.0
Version du client PostgreSQL
11.5
Version de SpatiaLite
4.3.0
Version de QWT
6.1.3
Version de QScintilla2
2.10.8
Compilé avec PROJ
6.3.2
Fonctionne avec PROJ
Rel. 6.3.2, May 1st, 2020
Version de l'OS
Windows 10 (10.0)
Extensions Python actives
cadastre; 
CalculateGeometry; 
excel_sync; 
localiserparcelle; 
OSMDownloader; 
refFunctions; 
SgmDxfImportPro; 
SgmExpressFunctions; 
StreetView; 
db_manager; 
processing

**Additional context**

The bug appears since QGIS 3.10. I've tested in QGIS 3.4 and 3.6 and there's no problem, it works well. In QGIS 3.12, we have the same problem.
[Bug_QGIS 3-10_Forms_with_python.zip](https://github.com/qgis/QGIS/files/4793720/Bug_QGIS.3-10_Forms_with_python.zip)

**Comment by sigmoe** [comment]
I've tested on Linux (Ubuntu 18.04), QGIS 3.1.0.6, and there's no problem, it works well.
So it's seems to be a QGIS for Windows problem (tested on Windows 10 -> problem).

**Comment by sigmoe** [comment]
After several tests, I've found the real problem, because in fact, the bug is not what it seems to be:
The problem is that the 'enable macros' parameter was set to 'Never'. And in this case, instead of obtaining a message explaining that the macros are not allowed, we have the bug.
So the bug is probably linked to the checking of the enable macros parameter, and it's not a problem linked the the form parameters.
Indeed, if I set the 'enable macros' parameter to 'Always', the form with its python code is correctly managed without any problem.

**Comment by gioman** [comment]
> After several tests, I've found the real problem, because in fact, the bug is not what it seems to be:
> The problem is that the 'enable macros' parameter was set to 'Never'. And in this case, instead of obtaining a message explaining that the macros are not allowed, we have the bug.
> So the bug is probably linked to the checking of the enable macros parameter, and it's not a problem linked the the form parameters.
> Indeed, if I set the 'enable macros' parameter to 'Always', the form with its python code is correctly managed without any problem

@sigmoe is this still relevant in recent QGIS releases?

**Comment by sigmoe** [comment]
Tested in QGIS 3.22.5: no more error.
The correction is OK for me.
