### ISSUE TITLE
Different readings of geometry with the same data in different QGIS versions

### ISSUE THREAD

**Issue by pintasart** [qgis/QGIS#37282]
I have a certain code into a plugin that works well in version 3.4.15. 

````Python
#iterate all layers
for layer in layers:       
	if layer.type() != QgsMapLayer.VectorLayer or layer.geometryType() != QgsWkbTypes.LineGeometry:  
		continue
	inViewFeats = layer.getFeatures(QgsFeatureRequest().setFilterRect(viewportPolygon.boundingBox()))
	r = viewportPolygon.boundingBox()
	for feat in inViewFeats:              
		self.selectedFeats.append(feat)

if(len(self.selectedFeats) !=0): 
	selectPoint = []
	for elem in self.selectedFeats:
		geom = elem.geometry().asPolyline()
		...
````

The data is read as LineString in this version.

![image](https://user-images.githubusercontent.com/11482572/84959367-155c4280-b0f7-11ea-9bad-57f3134be88c.png)

However, if using version 3.10.6 I get the following error:

![image](https://user-images.githubusercontent.com/11482572/84959550-771cac80-b0f7-11ea-9eee-73fe08381ada.png)

I notice that the data in version 3.10.6 is read as   MultiLineStringZ

![image](https://user-images.githubusercontent.com/11482572/84959629-a59a8780-b0f7-11ea-89fe-41331684444b.png)

I don't know a reason or find explanations for this. I think this is a bug.

**Comment by nyalldawson** [comment]
No -- it's an intentional change. All linestring shapefiles are read as multilinestring shapefiles in 3.10+
