### ISSUE TITLE
Qgis crash when importing pyproj from plugin or console

### ISSUE THREAD

**Issue by jbeilin** [qgis/QGIS#37289]
I installed on ubuntu 18.04 :

- Qgis 3.12.3 (using the standard process on https://www.qgis.org/en/site/forusers/alldownloads.html#debian-ubuntu)
- pyproj 2.6.1.post1 using pip3 

Each time I try to import pyproj in a plugin or in a console script in Qgis console, Qgis crashes. This code works in spyder3.

```
import pyproj
#print(pyproj.proj_version_str, pyproj.show_versions())
crs4326 = pyproj.CRS.from_epsg(4326)
crs2154 = pyproj.CRS(2154)
p = pyproj.Proj(crs2154)
transformer = pyproj.Transformer.from_crs(crs2154, crs4326, always_xy=True)
lo, la, h = transformer.transform(700000, 6600000, 0)
mu = p.get_factors(lo, la).meridional_scale
print(mu)
```

The issues has been also submitted to pyproj git : https://github.com/pyproj4/pyproj/issues/659

**Comment by elpaso** [comment]
does it crash if you comment all `print` instructions?

**Comment by nyalldawson** [comment]
Not a qgis issue - you're using two different versions of the proj library at once, which results in crashes.

**Comment by jbeilin** [comment]
> does it crash if you comment all `print` instructions?

Yes, even the import section create the crash

**Comment by elpaso** [comment]
Yeah, that's a common pitfall when installing python packages with pip and they have binary libraries that conflict with the libraries QGIS was linked with. Same happens for shapely for example.

**Comment by jbeilin** [comment]
Ok, so I hope the problem will disappear with Qgis 3.14

**Comment by elpaso** [comment]
No: the problem will never disappear: you cannot install conflicting binary libraries.

**Comment by jbeilin** [comment]
Would it be he same if pyproj and Qgis were linked : 
- 1/ against exactly the same proj release i.e. 6.3.1
- 2/ the same major proj release
If the answer to the two questions is no, is there a way to compute coordinate transformations in a plugin without creating the points/geometries and transform them using the Qgis API ?

**Comment by nyalldawson** [comment]
If it's for a qgis plugin, then you really should be using the QgsCoordinateTransform API. Otherwise your transformations will ignore all the user's settings such a the specific co-ordinate operations and datum transforms they've picked, and your results won't (necessarily) match those obtained elsewhere in qgis...

**Comment by jbeilin** [comment]
I manage to make it work using subprocess. 
It works in the Qgis console once wkdir is set. 

The main program : 
```python
import os
import json
import subprocess
import sys

wkdir = ""
sys.executable = "python3"
args = [sys.executable, os.path.join(wkdir, "test_pyproj_qgis.py")]

child_proccess = subprocess.Popen(args, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
child_process_output = child_proccess.communicate(b"5|44|6|44.5")[0]

datajs = json.loads(child_process_output)
print(datajs)
```
The subprocess program : 
```python
import json
import sys

from pyproj import database

bbox = sys.stdin.read()
T = bbox.split('|')
bbox = {'minx': float(T[0]), 'miny': float(T[1]), 'maxx': float(T[2]), 'maxy': float(T[3])}

L = database.get_authorities()
data = {'auth' : L , 'bbox': bbox}
print(json.dumps(data))
```

**Comment by T4mmi** [comment]
> Yeah, that's a common pitfall when installing python packages with pip and they have binary libraries that conflict with the libraries QGIS was linked with. Same happens for shapely for example.

Then how to import/call QGIS version of such libraires ?!  
almost EVERY geoprocessing tools uses GDAL/shapely/proj under the hood ... but none of them are detected by qgis python interpreter's pip (hence you cannot install/use any tool that relies on them).

I think this is a major QGIS problem :(

**Comment by nyalldawson** [comment]
@T4mmi 

> Then how to import/call QGIS version of such libraires ?!

easy -- don't mix and match different sources!

E.g :

- if on linux: Install qgis from your distro's repositories and all python libraries from those same repositories. Don't install some libraries from the repositories and then others manually via pip.
- if on windows: install qgis from osgeo4w (or the official windows installers), and stick with the libraries available from the same source. Those already include shapely and proj. Don't install these manually via pip.
- if on macos: as above -- install qgis via the official installer, and stick with the libraries provided in that installer.

> almost EVERY geoprocessing tools uses GDAL/shapely/proj under the hood

That's true for GDAL and proj, but not shapely. Shapely exposes functionality from the GEOS library, which is also available direct from the PyQGIS library without any added cost of translating geometries from one model to another. If you're writing a QGIS plugin then my advice is to use the native PyQGIS equivalent of the functionality from shapely instead -- it'll be significantly faster and handle things like curved geometries correctly.

**Comment by lucadelu** [comment]
@elpaso @nyalldawson I'm facing the same problem but it seems I have only a Proj version, I'm on debian  and all the installed packages related to proj are:

```
libproj-dev/stable,now 9.1.1-1+b1 amd64 [installed]
libproj25/stable,now 9.1.1-1+b1 amd64 [installed,automatic]
proj-bin/stable,now 9.1.1-1+b1 amd64 [installed]
proj-data/stable,now 9.1.1-1 all [installed]
``` 

the error could came from different pyproj versions?

How can I check if I have any old proj files on my pc?
