### ISSUE TITLE
OpenCL error when using the Raster Calculator

### ISSUE THREAD

**Issue by vagner-silveira** [qgis/QGIS#37297]
**Describe the bug**

If the configuration of the Options menu >>> Acceleration >>> Enable OpenCL acceleration, the raster calculator returns a processing error regarding the expression entered.
When disabling this OpenCL Acceleration setting, the Raster Calculator worked correctly.

**How to Reproduce**
1. Go to the configuration of the Options menu >>> Acceleration >>> "Enable OpenCL acceleration", must be set.
![image](https://user-images.githubusercontent.com/67110743/85055528-b1c02c80-b16b-11ea-9404-123529929be9.png)

2. Open the Raster Calculator and execute an expression (for example: NDVI calculation with the following expression ("Satelite @ 4" - "Satelite @ 1") / ("Satelite @ 4" + "Satelite @ 1").
![image](https://user-images.githubusercontent.com/67110743/85055611-d1efeb80-b16b-11ea-9cce-848bb373bc08.png)

3. Choose the path to the output file.
4. Click on the "OK" Button

5. See error
Error shown on Main Screen
![image](https://user-images.githubusercontent.com/67110743/85055717-019ef380-b16c-11ea-9dac-9034c00fdc25.png)

Error shown in Message Panel
![image](https://user-images.githubusercontent.com/67110743/85055744-0d8ab580-b16c-11ea-8cf9-8f5fa25cbd57.png)

Error shown in the OpenCL Message Panel
![image](https://user-images.githubusercontent.com/67110743/85055757-12e80000-b16c-11ea-8ab3-29aeffbc4213.png)

**QGIS and OS versions**

Versão do QGIS | 3.12.3-București | Código da versão do QGIS | 8234261527
-- | -- | -- | --
Compilado sobre Qt | 5.11.2 | Rodando sobre Qt | 5.11.2
Compilado sobre GDAL/OGR | 3.0.4 | Rodando sobre GDAL/OGR | 3.0.4
Compilado sobre GEOS | 3.8.1-CAPI-1.13.3 | Rodando sobre GEOS | 3.8.1-CAPI-1.13.3
Compilado no SQLite | 3.29.0 | Executando contra SQLite | 3.29.0
Versão do cliente PostgreSQL | 11.5 | Versão SpatiaLite | 4.3.0
Versão do QWT | 6.1.3 | Versão QScintilla2 | 2.10.8
Compilado com PROJ | 6.3.2 | Em execução com PROJ | Rel. 6.3.2, May 1st, 2020
Versão SO | Windows 10 (10.0)
Ativar complementos python | AzimuthDistanceCalculator; DsgTools; FeatureGridCreator; FreehandRasterGeoreferencer; Generalizer3; mmqgis; ParallelLineConstruction; quick_map_services; SemiAutomaticClassificationPlugin; db_manager; MetaSearch; processing

**Additional context**
When the Options >>> Acceleration >>> "Enable OpenCL acceleration" menu setting is disabled, the error is no longer caused, generating the expected result of the Raster Calculator expression.

**Comment by whatnick** [comment]
I would like to work on this issue. Sounds like in my area of expertise and I have resources to address it.

**Comment by elpaso** [comment]
Thank you for the help, much appreciated!

**Comment by whatnick** [comment]
From the error log it may be a super simple fix using quoted strings for windows and linked to the location where QGIS is installed. i.e 
```
Don't understand command line argument "Files/QGIS"
```

**Comment by elpaso** [comment]
@whatnick thanks for the tip!
@vagner-silveira can you check this PR on windows when merged and confirm that it solves your issue?

**Comment by elpaso** [comment]
@vagner-silveira can you please check if https://github.com/qgis/QGIS/pull/37376 solves this issue?

**Comment by whatnick** [comment]
I am happy to check as well settting up master build for QGIS on windows anyway.
