### ISSUE TITLE
Erro OpenCL ao utilizar Calculadora Raster

### ISSUE THREAD

**Issue by vagner-silveira** [qgis/QGIS#37294]
Caso a Aceleração OpenCL estiver ativada no menu de Opções, a calculadora Raster não executas os cálculos retornando em Erro:

![erro 001](https://user-images.githubusercontent.com/67110743/85033925-7dd70e00-b14f-11ea-9254-b46569fd073d.png)
![erro 002](https://user-images.githubusercontent.com/67110743/85033928-7f083b00-b14f-11ea-8e88-a8f263aedc3a.png)
![erro 003](https://user-images.githubusercontent.com/67110743/85033930-7fa0d180-b14f-11ea-986e-e92bb2d38793.png)

**Comment by gioman** [comment]
@vagner-silveira olá, tickets must be filed in English and with all the requested information:



**Describe the bug**


**How to Reproduce**



**QGIS and OS versions**



**Additional context**

**Comment by vagner-silveira** [comment]
Good afternoon.
Thank you very much for explaining how to report a QGIS Bug.
I will follow the procedure in a new post.

thank you
