### ISSUE TITLE
Poligon Divider dont appear in QGIS 3.12

### ISSUE THREAD

**Issue by leandjb** [qgis/QGIS#37300]
This plugin in not complatible with python3. Works fine in my QGIS Desktop (2.18 Las Palmas)

Repository:
https://plugins.qgis.org/plugins/Submission/

IMPORTANT:

If the issue concerns a third party plugin (downloaded with the plugin manager) then it can't be fixed by the QGIS team.
Please raise your issue in the dedicated bug tracker for that specific plugin (as listed in the plugin's description)

Tickets created here will be closed.

**Comment by Gustry** [comment]
As mentioned in your ticket above:

> If the issue concerns a third party plugin (downloaded with the plugin manager) then it can't be fixed by the QGIS team.

https://plugins.qgis.org/plugins/Submission/ Go in Details on their issue tracker.

Did you look to the native Subdivide algorithm in Processing? It's by default now
