### ISSUE TITLE
Locator fuzzy search not showing Edit in place results

### ISSUE THREAD

**Issue by uclaros** [qgis/QGIS#37319]
**Describe the bug**
The **amazing** fuzzy search in the locator returns results from the *Processing Algorithms* category but not from the *Edit Selected Features* category.

**How to Reproduce**
- Add a vector layer
- Hit ctrl+K and type `simpl`, fuzzy search has not kicked in, we get both *Processing Algorithms* and *Edit Selected Features* version of *simplify*.
- Type `smplf`, fuzzy search kicks in and only *Processing Algorithms* simplify is returned.

**QGIS and OS versions**
983e90fb4a on Debian testing

**Additional context**
Did I mention how **fantastic** this feature is? It should be implemented on more search fields like the processing toolbox search or the expression builder!

**Comment by rduivenvoorde** [comment]
@uclaros did you know how easy it is to implement your own 'Locator' (python) plugin? I understand that is different for your Issue/Feature Requests, but it is really cool to make it work, see eg https://github.com/rduivenvoorde/nominatim_locator_filter
