### ISSUE TITLE
Editing Processing Model Crashes QGIS 3.14 (when the model has a variable reference error)

### ISSUE THREAD

**Issue by davidlgalt** [qgis/QGIS#37329]
When attempting to edit a model that was not working, QGIS 3.14 would churn and then crash without opening up the model in the edit window.

In QGIS 3.10 LTR, I opened the model for editing and it revealed that there was an error in my model. It appeared I had (possibly) changed the names of some inputs, and that the downstream reference to them in the Merge Vector Layer algorithm hadn't been changed automatically.

I can fix it and it doesn't cause a crash in 3.10, but it does so every time in 3.14.

Here's an image of the offending error that was causing the crash:
![image](https://user-images.githubusercontent.com/44850852/85222185-134fe900-b36e-11ea-8e3a-dfb38d7e2ae5.png)

Here's the stack trace: 

## Report Details

**Crash ID**: [716792b67152e722f92b71ca89c064639d0c54ce](https://github.com/qgis/QGIS/search?q=716792b67152e722f92b71ca89c064639d0c54ce&type=Issues)

**Stack Trace**
<pre>
QBitArray::QBitArray :
QgsSQLStatement::parserErrorString qgssqlstatement.cpp:149
QgsModelChildAlgorithmGraphicItem::linkPointText qgsmodelcomponentgraphicitem.cpp:993
sipQgsModelChildAlgorithmGraphicItem::linkPointText sip_guipart1.cpp:122701
QgsModelComponentGraphicItem::linkPoint qgsmodelcomponentgraphicitem.cpp:601
QgsModelArrowItem::updatePath qgsmodelarrowitem.cpp:145
QgsModelArrowItem::QgsModelArrowItem qgsmodelarrowitem.cpp:51
QgsModelGraphicsScene::createItems qgsmodelgraphicsscene.cpp:177
meth_QgsModelGraphicsScene_createItems sip_guipart1.cpp:95844
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_sip :
sipVH__gui_73 sip_guipart0.cpp:8307
sipQgsModelDesignerDialog::repaintModel sip_guipart1.cpp:106841
QgsModelDesignerDialog::setModel qgsmodeldesignerdialog.cpp:394
meth_QgsModelDesignerDialog_setModel sip_guipart1.cpp:110017
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyFunction_FastCallDict :
PyTuple_New :
PyObject_FastCallKeywords :
PyObject_FastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:437
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:437
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QMenu::exec :
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QMetaObject::activate :
QWidget::customContextMenuRequested :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
sipQgsProcessingToolboxTreeView::viewportEvent sip_guipart1.cpp:143610
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:437
QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:437
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1618
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.14.0-Pi
QGIS code revision: 9f7028fd23
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
@davidlgalt please attach the model.

**Comment by davidlgalt** [comment]
It's two models and function (attached in the zip file). It also relies on the QuickOSM plugin.

[bug_37329.zip](https://github.com/qgis/QGIS/files/4817347/bug_37329.zip)

**Comment by Gustry** [comment]
> The model calls another model

Shouldn't you include it?

I got : 
> Cannot edit model: The model you are trying to run contains an algorithm that is not available: model:Get OSM Data by Type/Key/Layout

when opening the project

**Comment by davidlgalt** [comment]
Hmmm. I thought I included both models in the project file. Will check.

**Comment by davidlgalt** [comment]
Well I think I accidentally went and fixed the issue on my side, so I can't reproduce the error. 

A couple things though:
1) This is not an issue with your plugin Étienne which is (and continues to be) awesome
2) This is a general issue of how QGIS handles errors in models.

If there is an error in a model, I would like the ability to open up the model and fix the error. What is happening though is that when there is a reference error (like when a parameter or another model that is acting as a subroutine has been renamed), you get an error or even crashing out of QGIS. At that point it's up to the user to open up the model file in a text editor and fix the reference issue. I can do that, but not all QGIS users would be able to, or even know to do that.

**Comment by gioman** [comment]
> Well I think I accidentally went and fixed the issue on my side, so I can't reproduce the error.

@davidlgalt so closing this ticket?




> What is happening though is that when there is a reference error (like when a parameter or another model that is acting as a subroutine has been renamed), you get an error or even crashing out of QGIS

Can you provide an example model file?

**Comment by gioman** [comment]
Closing for lack of feedback.
