### ISSUE TITLE
Attribute Table "Feature Total" label not updated after layer filter

### ISSUE THREAD

**Issue by kaptainkory** [qgis/QGIS#37325]
**Describe the bug**
The attribute table label of "Feature Total" is not updated after layer filter that returns different number of features.

**How to Reproduce**

![Screenshot from 2020-06-20 13-07-47](https://user-images.githubusercontent.com/59102670/85208583-4f943280-b2f7-11ea-8f77-2671a069fda6.png)

**QGIS and OS versions**

QGIS version | 3.13.0-Master | QGIS code revision | 9469f246d7
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.6.2-CAPI-1.10.2 4d2925d6
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 10.12 (Ubuntu 10.12-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Linux Mint 19.3 | This copy of QGIS writes debugging output.
Active python plugins | MetaSearch; processing; db_manager

**Comment by gioman** [comment]
@kaptainkory can't confirm here on master/kubuntu 18.04.

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
