### ISSUE TITLE
Canvas and attribute table do not update correctly when joined table changes

### ISSUE THREAD

**Issue by kaptainkory** [qgis/QGIS#37327]
Joined tables looks to be very buggy.  I am submitting a couple of bug reports that may be related to each other.

**Describe the bug**
When a joined table is changed (e.g. records added/deleted, layer filtered, etc.):

A - The map canvas does not rerender to reflect the changes until it is moved or zoomed.  (This happens even when table join setting "Dynamic form" is true.)

B - The attribute table of layer with join does not update to reflect the changes.

**How to Reproduce**
1. Set up a geometry table joined to a nongeometry table (fig - "fruit db" joined to "fruit test").
2. Apply a layer filter (or add/delete records) to joined table (fig - "fruit db")
3. BUG A - Canvas map does not change to reflect changes until moved or zoomed.
4. BUG B - Attribute table of layer with join does not update to reflect changes (fig - "fruit test").

![Screenshot from 2020-06-20 13-52-04](https://user-images.githubusercontent.com/59102670/85209839-b66a1980-b300-11ea-8bdb-7e72ffecb599.png)

[fruit test.zip](https://github.com/qgis/QGIS/files/4808449/fruit.test.zip)

**QGIS and OS versions**

QGIS version | 3.13.0-Master | QGIS code revision | 9469f246d7
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.6.2-CAPI-1.10.2 4d2925d6
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 10.12 (Ubuntu 10.12-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Linux Mint 19.3 | This copy of QGIS writes debugging output.
Active python plugins | MetaSearch; processing; db_manager

**Comment by gioman** [comment]
> BUG A - Canvas map does not change to reflect changes until moved or zoomed.

true, very minor annoyance imho.



> BUG B - Attribute table of layer with join does not update to reflect changes (fig - "fruit test").

can't confirm here on master/kubuntu 18.04.

**Comment by kaptainkory** [comment]
Run filter on layer that is joined.

![Screenshot from 2020-06-21 11-24-37](https://user-images.githubusercontent.com/59102670/85229917-5af86400-b3b2-11ea-9b3e-3d8614f22e0f.png)

Canvas map and attribute table do not reflect filter applied.  I agree that canvas redraw, in particular, is very minor (and on its own probably not worth a bug report even).

![Screenshot from 2020-06-21 11-24-59](https://user-images.githubusercontent.com/59102670/85229925-66e42600-b3b2-11ea-980e-429f94539b9d.png)

Move or zoom map and filter is reflected on canvas, but not attribute table.

![Screenshot from 2020-06-21 11-25-19](https://user-images.githubusercontent.com/59102670/85229982-ba567400-b3b2-11ea-8161-8c0911fd800c.png)

Manually refresh attribute table and finally all are reflected correctly.
![Screenshot from 2020-06-21 11-25-40](https://user-images.githubusercontent.com/59102670/85229997-d528e880-b3b2-11ea-8bef-f21d05465e81.png)

**Comment by kaptainkory** [comment]
Also see #37325.  I initially opened the "fruit test db" attributed table with a previous layer filter applied (window header correctly reflected as Feature Total: 1).  But then, I cleared the filter and applied a new one.  Header should now reflect Feature Total: 2, but doesn't.

**Comment by benhur07b** [comment]
> BUG A - Canvas map does not change to reflect changes until moved or zoomed.

I'm not sure if it's related but Virtual Layers in QGIS (https://docs.qgis.org/testing/en/docs/user_manual/managing_data_source/create_layers.html#creating-virtual-layers) work the same way. The features of a virtual layer won't update on the canvas until the canvas or map display is manually refreshed via pan, zoom, etc. (http://changelog.kartoza.com/en/qgis/section/data-providers-21/detail/79/?q=2.1).

> BUG B - Attribute table of layer with join does not update to reflect changes (fig - "fruit test").

Tested this one and found a some interesting interactions. 

1. IF I don't have a feature selected on the map canvas and I apply a filter, the "Total: Filtered: Selected:" header does not automatically update. It does however show the correct numbers if I close the attribute table and open it again. For example: Open the attribute table of **fruit test**. Notice "Total: 3, Filtered: 3, Selected: 0" is correct. Apply a filter "NAME"='Banana', the header stays the same but after you close and reopen the attribute table, it shows the correct counts "Total: 1, Filtered: 1, Selected: 0".
![1](https://user-images.githubusercontent.com/22940966/85235734-fbe62e00-b449-11ea-86a2-2ebded7226ac.gif)

2. IF I have a feature selected on the map canvas and apply a filter,  the "Total: Filtered: Selected:" header does automatically update. For example: select the apple feature from **fruit test**. Apply the "NAME"='Banana' filter. Notice that the header gets updated to "Total: 1, Filtered: 1, Selected: 0". Now select the Banana feature. Remove the filter. The header automatically updates to  "Total: 3, Filtered: 3, Selected: 0".
![2](https://user-images.githubusercontent.com/22940966/85235820-c2fa8900-b44a-11ea-9a08-cdf00804e4eb.gif)

**Comment by gioman** [comment]
> Run filter on layer that is joined.
> Canvas map and attribute table do not reflect filter applied.
> Move or zoom map and filter is reflected on canvas, but not attribute table.
> Manually refresh attribute table and finally all are reflected correctly.


I confirm about the map canvas, but not for attribute table which in my case is immediately updated after applying the filter without needing any action.

Note: I have QGIS configured with "show all features" in "data sources" > "attribute table behavior".

**Comment by Pedro-Murteira** [comment]
@kaptainkory Hello, is this issue still valid on recent releases?
