### ISSUE TITLE
QGIS Server WMS return bad CRS

### ISSUE THREAD

**Issue by Loctudy** [qgis/QGIS#37321]
**Describe the bug**
My project use two differents CRS 2154 and 32630.
 In the project properties -> Qgis Server -> csr restriction if I use 2154 + 32630 + 4326
The default crs used by the WMS client will be WGS84 (4326) and at the output is at the wrong position.
Then if you remove 4326 from the crs restriction list, the WMS client will use the first on the list (here 2154) and the output is at the rigth position.

**How to Reproduce**
1) Add two layers with differents crs
2) Activate Server Option with crs including 4326
![crs_restriction](https://user-images.githubusercontent.com/46006254/85151814-88c79680-b254-11ea-8d4b-c5483d979e1a.PNG)
3)Check result using WMS layer
![wms_wrong](https://user-images.githubusercontent.com/46006254/85152138-ef4cb480-b254-11ea-8147-c562da7a8fe7.PNG)
4) Import the WMS layer it will be displayed at the wrong location

5) Then repeat the same procedure by removing 4326 in the crs restriction everything works fine (also the in the fly transformation)
![good](https://user-images.githubusercontent.com/46006254/85152641-8ade2500-b255-11ea-8b6c-aeb447f4b583.PNG)

**QGIS and OS versions**

QGIS version
3.12.0-București
QGIS code revision
cd141490ec
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.1
Running against PROJ
Rel. 6.3.1, February 10th, 2020
OS Version
Windows Server 2016 (10.0)
Active python plugins
db_manager; 
MetaSearch; 
processing

**Additional context**

**Comment by Loctudy** [comment]
I forget to add layers are stored in a pg database

**Comment by rldhont** [comment]
Hi @Loctudy You have used QGIS 3.12.0.

Did you have the same issue with QGIS 3.10.* ?
Can you test with 3.12.3 or 3.14.0 ?

**Comment by Loctudy** [comment]
@rldhont
 unfortunatly I don't have the ability to change my Qgis version.
I need to try later on other computer

**Comment by Loctudy** [comment]
@rldhont 

1.  Just try with version QGIS version 3.14.0-Pi QGIS code revision 9f7028fd23 and Qgis Server with the same version and it is not working.

1.  It is **working fine** with the following config (both Qgis and Qgis server) QGIS version 3.15.0-Master QGIS code revision 8aecfdd93a (Just need to add in your http.conf  FcgidInitialEnv PATH  add => C:\OSGeo4W64\apps\gdal-dev\bin;C:\OSGeo4W64\apps\proj-dev\bin)

1. Working fine with **Qgis server version 3.15.0-Master** and **Qgis Desktop version 3.10.7-A Coruña** QGIS code revision 7b4ca4c8d0

**Comment by elpaso** [comment]
Works with supported versions.
