### ISSUE TITLE
Blend modes degrade rasterization of print composer map items which contain layers selected as 'mask source' by any other project layer

### ISSUE THREAD

**Issue by kevinstadler** [qgis/QGIS#37331]
**Describe the bug**

Rather peculiar bug: when a map item in the print composer is rendered using any blend mode other than 'normal' **and** the map item in question makes use of the new label masking feature, the rasterization of that particular map item won't respect the print layout's export resolution, but instead come out extremely pixellated (seems to be 72dpi). Other map items in the same print layout are rasterized at the proper resolution.

Below are close-ups of 4 different map items exported to the same 300dpi PNG, you can also check the same effect in this [600dpi PDF export](https://github.com/qgis/QGIS/files/4809749/SameMapDifferentBlendmodes.pdf) (sample project below).

![Screen Shot 2020-06-21 at 23 43 28](https://user-images.githubusercontent.com/7602414/85228926-194ed400-b419-11ea-9e11-b927b01a0e2a.png)
![Screen Shot 2020-06-21 at 23 43 34](https://user-images.githubusercontent.com/7602414/85228929-1e138800-b419-11ea-8ae9-3cbfd90b1a46.png)
![Screen Shot 2020-06-21 at 23 43 39](https://user-images.githubusercontent.com/7602414/85228931-1fdd4b80-b419-11ea-8640-8e503f65ec7b.png)
![Screen Shot 2020-06-21 at 23 43 44](https://user-images.githubusercontent.com/7602414/85228932-210e7880-b419-11ea-9361-f4875e900ba6.png)

**How to Reproduce**

Sample project with dummy data file:
[MaskedLabelPrintComposerBlendModesProject.zip](https://github.com/qgis/QGIS/files/4809760/MaskedLabelPrintComposerBlendModesProject.zip)

Open `Project > Layouts > SameMapDifferentBlendModes`, then `Layout > Export as PDF`/`Export as Image` (same effect visible in all formats)

**QGIS and OS versions**

OSX High Sierra 10.13.6

```
QGIS version | 3.12.3-București | QGIS code revision | 8234261527
-- | -- | -- | --
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.28.0 | Running against SQLite | 3.28.0
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS High Sierra (10.13)
Active python plugins | db_manager; MetaSearch
```

**Comment by kevinstadler** [comment]
I tried to pinpoint what exactly about the label masking triggers the rough rasterization, and it's even weirder than I thought:

1. the presence of one problematic layer in the map item causes the entire map item to be rasterized badly (if that map item uses a blend mode other than 'normal').

2. the problematic layers are not actually those to which the masking is *applied* (i.e. the 'masked symbol layers'), but those layers *which are selected as a mask source by at least one other layer **even if the symbol layer that is selected as the 'target' of the mask isn't actually rendered***.

Really not sure why that would be the case, but here's another sample project: [LabelMaskSourcePrintComposerBlendMode.zip](https://github.com/qgis/QGIS/files/4830419/LabelMaskSourcePrintComposerBlendMode.zip)
and a 300dpi exported PDF: [SameMapDifferentBlendmodes.pdf](https://github.com/qgis/QGIS/files/4830431/SameMapDifferentBlendmodes.pdf)

Here are again closeups of the three relevant settings:
![Screen Shot 2020-06-25 at 17 51 04](https://user-images.githubusercontent.com/7602414/85697598-81990080-b70c-11ea-8d11-2fe65a0cf985.png)
![Screen Shot 2020-06-25 at 17 51 12](https://user-images.githubusercontent.com/7602414/85697620-85c51e00-b70c-11ea-8982-b66ca14c317d.png)
![Screen Shot 2020-06-25 at 17 51 08](https://user-images.githubusercontent.com/7602414/85697616-852c8780-b70c-11ea-8a80-1a13dc582952.png)


Also, the problem persists in QGIS 3.14:

QGIS version | 3.14.0-Pi | QGIS code revision | 9f7028fd23
-- | -- | -- | --
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.28.0 | Running against SQLite | 3.28.0
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS High Sierra (10.13)
Active python plugins | db_manager; MetaSearch

**Comment by Pedro-Murteira** [comment]
This issue is still valid on QGIS 3.22.3. (Windows 10)

**Comment by nyalldawson** [comment]
Looks like a duplicate of https://github.com/qgis/QGIS/issues/49488

**Comment by kevinstadler** [comment]
Just tested the original sample project (from first post) in QGIS 3.28.2, didn't manage to reproduce the rasterization bug! 🥳
