### ISSUE TITLE
Unable to see styles stored in the database

### ISSUE THREAD

**Issue by alexmodesto73** [qgis/QGIS#37338]
Since the update to 3.14 it is impossible to see the styles stored in the database, this makes this error:
```
2020-06-22T08:21:29     WARNING    Requête erronée : SELECT styleQML FROM layer_styles WHERE f_table_catalog='fibrea' AND f_table_schema='pit' AND f_table_name='iti' AND f_geometry_column ='geom' AND type='Line' ORDER BY CASE WHEN useAsDefault THEN 1 ELSE 2 END,update_time DESC LIMIT 1 a retourné 7 [ERROR: column "type" does not exist
             LIGNE 1 : ...able_name='iti' AND f_geometry_column ='geom' AND type='Line...
              ^
```

**Comment by elpaso** [comment]
Introduced by: https://github.com/qgis/QGIS/pull/32138

**Comment by elpaso** [comment]
@jgrocha ^

**Comment by jgrocha** [comment]
Thank you @alexmodesto73 for the report. I'm looking into it.

**Comment by jgrocha** [comment]
@alexmodesto73 Your `layer_styles` table was probably created by a previous version of QGIS. Please confirm that was the case.

### The problem

Now this `layer_styles` table has a new column called `type`. QGIS should have noticed the missing column and issued an `"ALTER TABLE layer_styles ADD COLUMN type varchar NULL"`. **For some reason, the new column was not added.**

It would be very useful if you can help us to find why the column was not added. Is it possible that you are now using a different role to connect to Postgis? Is the Postgresql role able to change the table?

If you are able to do so, please enable all request in Postgresql logs and then try again to save the style. Look at the log and find this `ALTER TABLE layer_styles` statement. Did it run? Did it fail?

### Workaround

The workaround is to add that column manually.

### Note

This can only happens when the `layer_styles` already exists, created with QGIS < 3.14.

**Comment by alexmodesto73** [comment]
@jgrocha I confirm
and I still have users of old versions

**Comment by alexmodesto73** [comment]
`"ALTER TABLE layer_styles ADD COLUMN type varchar NULL"`

- save style works
 
but Default saved styles does not loading
log :
```2020-06-22 22:42:23.206 CEST [19775] postgres@postgres LOG:  instruction : SET application_name='QGIS'
2020-06-22 22:42:23.206 CEST [19775] postgres@postgres LOG:  instruction : SELECT EXISTS ( SELECT oid FROM pg_catalog.pg_class WHERE relname='layer_styles')
2020-06-22 22:42:23.206 CEST [19775] postgres@postgres LOG:  instruction : SELECT styleQML FROM layer_styles WHERE f_table_catalog='postgres' AND f_table_schema='divers' AND f_table_name='courbes-niveau' AND f_geometry_column ='geom' AND type='Line' ORDER BY CASE WHEN useAsDefault THEN 1 ELSE 2 END,update_time DESC LIMIT 1```

**Comment by alexmodesto73** [comment]
`SELECT styleQML FROM layer_styles WHERE f_table_catalog='postgres' AND f_table_schema='divers' AND f_table_name='courbes-niveau' AND f_geometry_column ='geom' AND type='Line' `

 **type='Line'** => but type is empty !
Because : 
`"ALTER TABLE layer_styles ADD COLUMN type varchar NULL"`

**Comment by alexmodesto73** [comment]
How many type ?

`2020-06-22 22:50:03.599 CEST [20331] postgres@postgres LOG:  instruction : SELECT styleQML FROM layer_styles WHERE f_table_catalog='postgres' AND f_table_schema='divers' AND f_table_name='dvf-2019' AND f_geometry_column ='geom' AND type='Point' ORDER BY CASE WHEN useAsDefault THEN 1 ELSE 2 END,update_time DESC LIMIT 1`

 * type='Line' 
 * type='Point' 
* ?

**Comment by jgrocha** [comment]
Thank you @alexmodesto73 for the feedback.

You just need to add the column, as you did. Then use the normal save and load style operations from QGIS. QGIS will fill the column with one of those 3 types. You did that. 

You saved the style, but the column type was not filled. It should have a value. That's weird. The same type is used to retrieve the style. As far as I can see, the type is correctly computed (`Line` for your `courbes-niveau` table and `Point` for `dvf-2019` table.

I can not understand what went wrong, but I'm creating a setup with QGIS 3.10 and 3.14 for testing this. I'll report back.

**Comment by jgrocha** [comment]
> How many type ?
> 
> `2020-06-22 22:50:03.599 CEST [20331] postgres@postgres LOG: instruction : SELECT styleQML FROM layer_styles WHERE f_table_catalog='postgres' AND f_table_schema='divers' AND f_table_name='dvf-2019' AND f_geometry_column ='geom' AND type='Point' ORDER BY CASE WHEN useAsDefault THEN 1 ELSE 2 END,update_time DESC LIMIT 1`
> 
>     * type='Line'
> 
>     * type='Point'
> 
>     * type='Polygon'
> 
>     * ?

That's the only possible types. This additional column `type` was introduced because you can have more than one geometry type in the same Postgis table, right? This way, QGIS is able to store different styles for the same table (one style for Lines and another for Points, for example).

**Comment by jgrocha** [comment]
@alexmodesto73 If you are able to write some Python code on QGIS console, you can see what type is computed for a layer. Just select the layer in the layer tree and then run:
```python
layer = iface.activeLayer()
QgsWkbTypes.geometryDisplayString(layer.geometryType())
```

**Comment by elpaso** [comment]
@jgrocha maybe you should change the condition to `(type = ... OR type IS NULL)` to the select queries to be able to load old styles (after the column was added successfully of course)

**Comment by alexmodesto73** [comment]
Corrections in table

The styles with the type field are loaded on:
Qgis 3.4.x
Qgis 3.4.x
Qgis 3.14

**Comment by CoryAlbrecht** [comment]
Regression, #39850 .
