### ISSUE TITLE
Installed GDAL version

### ISSUE THREAD

**Issue by peetw** [qgis/QGIS#37337]
Apologies if this isn't the correct place to ask - I'm not sure whether this is a QGIS issue, or an OSGeo4W issue (I've asked on their mailing list [here](https://lists.osgeo.org/pipermail/osgeo4w-dev/2020-May/003933.html), but have not yet received a response).

Using either the Standalone Installer or the OSGeo4W Network Installer, the version of GDAL installed by either QGIS 3.10.7 or 3.14.0 is still 3.0.4. Are there any plans to update the GDAL dependency version? Specifically, we need to use GDAL 3.1 (or later, although I think 3.2 is still in development?) to access the fix for #34993.

**Comment by gioman** [comment]
@peetw the right place for such questions is the QGIS developers mailing list. Anyway I think that QGIS master from OSGeo4W ships with GDAL 3.1/2.
