### ISSUE TITLE
Processing modeler : Panels position / visibility is not kept

### ISSUE THREAD

**Issue by olivierdalang** [qgis/QGIS#37348]
**Describe the bug**

Panel position/visibilty is reset when reopening the processing modeler Window (this is annoying esp. on small screen where you may want to hide less useful panels such as undo history).

**How to Reproduce**

1. Open the processing modeler
2. Hide the undo history widget
3. Close the processing modeler
4. Open the processing modeler -> the undo history widget has reappeared

**QGIS and OS versions**

```
QGIS version
3.14.0-Pi
QGIS code revision
9f7028fd23
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
pluginbuilder3; 
plugin_reloader; 
qgepplugin; 
QGIS3-getWKT; 
swiss_locator; 
db_manager; 
processing
```

**Comment by alexbruy** [comment]
This is more general than just Processing modeler, also happens with many other dock widgets and there are already open tickets. It is upstream bug.

**Comment by olivierdalang** [comment]
@alexbruy Is it ? I didn't notice other issues in others parts of the interface so far...
Also couldn't find the tickets you're mentioning, could you put the links here for reference ? (so I can close this as duplicate if it's really the same issue)

**Comment by Pedro-Murteira** [comment]
@olivierdalang I can no longer replicate this on QGIS 3.16.14 and 3.22.1.
