### ISSUE TITLE
[postgres] Wrong feature counts when using estimated metadata

### ISSUE THREAD

**Issue by wonder-sk** [qgis/QGIS#37342]
Feature count returned by postgres provider may get wrong. In a case I was debugging, that was a PostgreSQL table with nearly 2M polygons. The estimated number of rows (shown in DB manager, using PostgreSQL query planner statistics) is +/- the same as the true number of rows.

When the layer is loaded with "use estimated metadata" = false, things work fine and featureCount() reports the correct count. But when **"use estimated metadata" = true**, then featureCount() only reports 2 (two!) features.

As a result, that completely breaks the default hybrid indexing strategy for snapping and QGIS tries to load all 2M geometries - which takes a lot of time and memory...

Tested with QGIS 3.10.7 and PostgreSQL 10.3.

Everything works fine in QGIS 3.4. It looks like this got broken in https://github.com/qgis/QGIS/pull/32114 (3.12+) and https://github.com/qgis/QGIS/pull/33019 (backport to 3.10.x)... so it probably affects also 3.14 and master (but I have not tested).

Further testing shows that this is due to the fact that the PostgreSQL uses **parallel query execution** and the EXPLAIN command says at the top-level that it will gather results from two workers:

![Screenshot from 2020-06-22 19-34-32](https://user-images.githubusercontent.com/193367/85319631-15c35780-b4c2-11ea-8e76-ae72763a3025.png)

So... it looks like it is quite fragile to depend on the EXPLAIN command output. My suggestion would be to stick to using `reltuples` from `pg_catalog.pg_class` for tables - and probably just for views we would use the EXPLAIN command which may get broken in the future again.

cc @troopa81

**Comment by haubourg** [comment]
@wonder-sk any idea why the planner estimates only two rows? Are the statistics up to date on the layer? 
I'll try to reproduce

**Comment by wonder-sk** [comment]
@haubourg If you look at the query plan, the second row says `rows=2` which is what the postgresql provider incorrectly parses as the feature count.

What the provider actually expects is output like this, without any parallelization:

![Screenshot from 2020-06-22 22-48-01](https://user-images.githubusercontent.com/193367/85333791-7eb6c980-b4da-11ea-8f53-ac53784c82c1.png)

In this case it would parse the plan correctly with estimated 810 rows...

**Comment by gacarrillor** [comment]
Just wanted to add that this was happening already in March 2018, i.e., even before QGIS v3.4. I had [issues](https://github.com/opengisch/QgisModelBaker/pull/194) with `estimatedmetadata=true` and `featureCount()`.

**Comment by troopa81** [comment]
@wonder-sk You got it right, the plan is different from expected when serialization is enabled for the request (I never face such a case when I pushed the PR). 

The thing is even if I deal with a different plan format, I get no good estimation. For instance, on some sample data, I get:
- count: 3146018
- estimate with no parallelization: 3146460
- estimate with parallelization: 1311025 (with 2 workers)

An ugly workaround could be to disable parallelization temporary but I'd prefer to avoid that. 

I'll think about this and come back with a fix.

**Comment by haubourg** [comment]
@troopa81 according to https://www.cybertec-postgresql.com/en/how-postgresql-estimates-parallel-queries/ 
the right formula seeems to be 

`estimate = estimated_rows / (number_of_cores + (1 – leader_contribution * number_of_cores)`

**Comment by troopa81** [comment]
@haubourg Interesting and it works quite well on my example, but I'm not really found of the _leader_contribution_ magic number which is set to 0.3 in the example. 

I'm wondering if this number could be much greater or lower in some case.  It's still a better solution than what happens now.
