### ISSUE TITLE
QGIS crashes when saving a project

### ISSUE THREAD

**Issue by zavalamo** [qgis/QGIS#37346]
## User Feedback

I have just installed the new version of QGIS and when I try to save a new project or layer the program stopped and this message appears, with the attached report.

## Report Details

**Crash ID**: [30346b76a99141311a8ef822e2e2fac1ea62781d](https://github.com/qgis/QGIS/search?q=30346b76a99141311a8ef822e2e2fac1ea62781d&type=Issues)

**Stack Trace**
<pre>
RtlFreeHeap :
HeapFree :
free :
DllUnregisterServer :
DllUnregisterServer :
CServerContextActivator::CreateInstance actvator.cxx:1000
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1918
CApartmentActivator::CreateInstance actvator.cxx:2251
CProcessActivator::CCICallback actvator.cxx:1716
CProcessActivator::AttemptActivation actvator.cxx:1630
CProcessActivator::ActivateByContext actvator.cxx:1488
CProcessActivator::CreateInstance actvator.cxx:1389
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1918
CClientContextActivator::CreateInstance actvator.cxx:685
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1918
ICoCreateInstanceEx objact.cxx:1397
CComActivator::DoCreateInstance immact.hxx:343
CoCreateInstanceEx actapi.cxx:175
CoCreateInstance actapi.cxx:120
_SHCoCreateInstance :
SHExtCoCreateInstance :
DCA_SHExtCoCreateInstance :
CFSIconOverlayManager::_s_LoadIconOverlayIdentifiers :
CFSIconOverlayManager::CreateInstance :
IconOverlayManagerInit :
GetIconOverlayManager :
FileIconInit :
SHGetImageList :
CBreadcrumbBar::InitBreadcrumbBar :
CAddressBand::_EnsureBreadcrumbBar :
CAddressBand::_CreateAddressBand :
CAddressBand::SetSite :
IUnknown_SetSite :
CBandSite::_AddBandByID :
CBandSite::AddBand :
CNavBar::_CreateBands :
CNavBar::_CreateBar :
CNavBar::ShowDW :
CFileOpenSave::_CreateNavigationBar :
CFileOpenSave::_InitOpenSaveDialog :
CFileOpenSave::s_OpenSaveDlgProc :
UserCallDlgProcCheckWow :
DefDlgProcWorker :
DefDlgProcW :
UserCallWinProcCheckWow :
InternalCreateDialog :
InternalDialogBox :
DialogBoxIndirectParamAorW :
DialogBoxIndirectParamW :
CFileOpenSave::Show :
QDialog::exec :
QFileDialog::getSaveFileUrl :
QFileDialog::getSaveFileName :
QgisApp::fileSaveAs qgisapp.cpp:7139
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:437
QCoreApplication::notifyInternal2 :
QMenu::metaObject :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:437
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:437
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1618
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.14.0-Pi
QGIS code revision: 9f7028fd23
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by gioman** [comment]
> I have just installed the new version of QGIS and when I try to save a new project or layer the program stopped

@zavalamo please try with a new QGIS profile.

**Comment by gioman** [comment]
@zavalamo also: did not happen before the upgrade? what about if you downgrade, still happens?

**Comment by zavalamo** [comment]
This has happened also with 3.10, while 2.18 and earlier, was working without problems.

**Comment by gioman** [comment]
> This has happened also with 3.10, while 2.18 and earlier, was working without problems.

@zavalamo have you tried with a new QGIS profile? this is likely a local issue possibly caused by a 3rd party plugin or a legacy configuration.

**Comment by zavalamo** [comment]
@gioman I am just a basic user, please let me know how to change, modify or create a new QGIS profile.

**Comment by gioman** [comment]
@zavalamo settings > user profiles > new profile (afterward do **not** install any 3rd party plugin before testing).

**Comment by zavalamo** [comment]
@gioman Thank you very much. I'm going to try it and I will inform you about the result. Best regards

**Comment by zavalamo** [comment]
@gioman There is no way. The problem remains. No 3rd party plugin have been installed. The program crashes when some actions are requested, as such as saving the project, create a new layer, ... It seems that one of the problems is to save anything in the computer. The crash happens in this process.

**Comment by gioman** [comment]
@zavalamo I'm afraid you have local issues (because of course what you describe are not general QGIS issues) and not sure if there is much we can do.

**Comment by zavalamo** [comment]
@gioman I think that is a problem of the muy personal computer configuration, because 3.10 is working in the company's computer. Thank you for your support. Best regards from Spain.

**Comment by gioman** [comment]
> because 3.10 is working in the company's computer

@zavalamo can you test 3.14 in this machine?

**Comment by zavalamo** [comment]
@gioman Is not easy in the current situation. I continue to work with 2.18 in my computer. Thank you.

**Comment by gioman** [comment]
> @gioman Is not easy in the current situation. I continue to work with 2.18 in my computer. Thank you.

@zavalamo please reopen this if/when you find any evidence that this is not a local issue.

**Comment by zavalamo** [comment]
@gioman Thank you again. Best regards.
