### ISSUE TITLE
The `qgis.core.QgsMapRendererParallelJob` class `isActive()` method returns True, even if the render is finished, in certain conditions

### ISSUE THREAD

**Issue by emanuelegissi** [qgis/QGIS#37349]
**Describe the bug**

I am trying to add a timeout to map rendering and saving to a file.

The `qgis.core.QgsMapRendererParallelJob` class has a `waitforfinished()` method. But this method does not have a `timeout` parameter as in `qgis.core.QgsTask.waitforfinished(timeout=30000)`.

So I am trying to use the `isActive()` method to check the completion of the running rendering job. Here is the snippet of code I am using in a function:

```
render = QgsMapRendererParallelJob(settings)
render.start()
t0 = time.time()
while render.isActive():
    time.sleep(2)
    dt = int(time.time() - t0)
    if dt > 30:  # timeout
        render.cancelWithoutBlocking()
        return
image = render.renderedImage()
image.save(filepath, imagetype)
```

But this code does not work, as it waits undefinetely. Here is the **bug**: even if the rendering job is finished, `render.isActive()` never returns `True`.

Note that, without the timeout check, this code works well and, after the `waitforfinished()` line, `render.isActive()` correctly returns `False`:

```
render = QgsMapRendererParallelJob(settings)
render.start()
render.waitforfinished()
feedback.pushInfo(f"Render is active: {render.isActive()}")
image = render.renderedImage()
image.save(filepath, imagetype)
```

I suggest fixing the bug of the `isActive()` method, and adding the `timeout` to `waitforfinished`.

**How to Reproduce**

Use the code from previous section.

**QGIS and OS versions**

QGIS version | 3.14.0-Pi | QGIS code revision | 9f7028fd23
-- | -- | -- | --
Compiled against Qt | 5.12.8 | Running against Qt | 5.12.8
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.2 (Ubuntu 12.2-4) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Ubuntu 20.04 LTS
Active python plugins | qgis2fds; active_fire; latlontools; QuickPrint; MetaSearch; processing; db_manager

**Additional context**

None

**Comment by emanuelegissi** [comment]
Any way to circumvent this issue? How to do a timeout when saving the map to an image?

**Comment by nyalldawson** [comment]
Change

    time.sleep(2)

to

    time.sleep(2)
    QCoreApplication.processEvents()

**Comment by emanuelegissi** [comment]
Thank you, it works!
I would have never discovered that by myself. I suggest making `waitforfinished()` cancellable and adding a timeout.
