### ISSUE TITLE
Unable to add new layer to workspace from an Oracle connection.

### ISSUE THREAD

**Issue by ewright-gis** [qgis/QGIS#37352]
**Describe the bug**
Unable to add new layer to workspace from an Oracle connection.  

**How to Reproduce**
Go to Layer --> Add Layer --> Add Oracle Spatial Layer 
Choose an existing connection or create a new one, select the layer to add, press "Add" then nothing happens.  

**QGIS and OS versions**

QGIS version
3.14.0-Pi
QGIS code revision
9f7028fd23
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
db_manager; 
MetaSearch; 
processing

**Additional context**
There don't appear to be any logged errors or messages in the application as to why it is failing.  Existing layers stored in saved workspaces still work. Functionality worked in previous version 3.12.N.  You can add the layer to an older version of QGIS, export to qlr, and then drop it in to 3.14 workspace and that still works as well.

**Comment by uclaros** [comment]
Can confirm on Debian testing. Adding Oracle layers from the data source manager does nothing...
You can still add Oracle layers from the browser without issues though. Just take care not to refresh while a refresh is running and trigger #36512

**Comment by gioman** [comment]
> Can confirm on Debian testing.

@uclaros regression I guess?

**Comment by rduivenvoorde** [comment]
Confirmed here on Windows QGIS 3.14: only browser works, dialog doubleclick or using Add button does nothing...


QGIS version | 3.14.0-Pi | QGIS code revision | 9f7028fd23
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020

**Comment by uclaros** [comment]
Is there a way we could have unit tests for this kind of functionality or is this QEP#180 material?
I was reading @nyalldawson 's comments on https://github.com/qgis/QGIS-Enhancement-Proposals/issues/180 and kind of agreed but then this comes up. Maybe x.x.0 versions should be considered as public betas

**Comment by gioman** [comment]
> or is this QEP#180 material

@uclaros definitely QEP 180 material.  Who proposed it argues that this snafus can and will always happen, having some monkey testing in place will help avoid that.

**Comment by nyalldawson** [comment]
> . Who proposed it argues that this snafus can and will always happen, having some monkey testing in place will help avoid that.

In previous releases we've done a one-week "hands off" period prior to final release. We really should have done that this time too, as it would catch late regressions like this... I think we need to adopt this as a standard, no-exceptions rule.
