### ISSUE TITLE
QGIS error 40 & SCP plugin error SSL certificate failure?

### ISSUE THREAD

**Issue by cdeforesta** [qgis/QGIS#37354]
Hi everyone,

I’m having issues downloading satellite images using the SCP plug-in for QGIS. The satillite images appear in the product list but i cant display a preview image or download the products. I get ‘error 40 – Unable to connect’. I have also added the debug log file, so you guys can have a look. The developer of SCP said "it is an installation issue related to the Python version and SSL certificates. You could try to update the Python version." But i'm not really sure what i'm supposed to do.

P.S i have already reinstalled QGIS multiple times and i’m pretty sure i installed GDAL,OGR,Numpy,SciPy and Matplotlib using Homebrew. (still very new to all of this)

I'll gladly take any help i can get!

Thanks,

Charles

![QGIS error message](https://user-images.githubusercontent.com/63056299/85416880-4614ff80-b56f-11ea-875c-4a6cdaf313eb.png)
[Error log 2.txt](https://github.com/qgis/QGIS/files/4820051/Error.log.2.txt)

**Comment by gioman** [comment]
@cdeforesta this must be filed in the SCP bug tracker, thanks!

**Comment by cdeforesta** [comment]
@gioman Thanks

**Comment by edrea-rae** [comment]
I also have the similar error
What can I do
Please help!
