### ISSUE TITLE
Opening a File GDB changes a date/time field

### ISSUE THREAD

**Issue by rgnixon** [qgis/QGIS#37369]
I extract a File Geodatabase from ArcGIS Online.
I drag and drop it into QGIS 3.14 64-bit (Windows 10).
My locale is correct as New Zealand, timezone +1200.

The bottom two (out of four) Date/Time fields are changed.

Screenshot attached has QGIS data at the top, ArcGIS Online data at the bottom.
![qgis_datetime](https://user-images.githubusercontent.com/28893310/85494374-a7e76f00-b62c-11ea-9dd7-e9b7afbdaca1.jpg)

**Comment by nyalldawson** [comment]
This is a gdal issue. Can you file a bug report for gdal, including your sample layer?

**Comment by rgnixon** [comment]
Hi Nyall, not sure where to go to file it. Got a link for me? Thanks.

**Comment by nyalldawson** [comment]
https://github.com/OSGeo/gdal/issues/new
