### ISSUE TITLE
Split vector layer...

### ISSUE THREAD

**Issue by Giacominibus** [qgis/QGIS#37374]
**Describe the bug**

The file name is not the same as the unique ID field 
**How to Reproduce**

1. Go to 'vector'
2. Click on 'data management tools.'
3. Scroll down to 'Split vector layer...'

**QGIS and OS versions**

3.14.0-Pi

**Additional context**

**Comment by alexbruy** [comment]
Duplicates #37296?

**Comment by Gustry** [comment]
Closing for lack of feedback. I would say it's the same error.
