### ISSUE TITLE
QgsVectorFileWriter creates an invalid GPKG file

### ISSUE THREAD

**Issue by troopa81** [qgis/QGIS#37386]
**Describe the bug**

When I try to create a file with the Python API class _QgsVectorFileWriter_ the produced file cannot be loaded then, QGIS reporting it as an invalid file. 

**How to Reproduce**

From the Python Console, type the following lines

```python
fields=QgsFields()
fields.append(QgsField("note", QVariant.Double))
feat=QgsFeature(fields)
feat.setAttribute("note", 2)
lyrname = "test"
opts = QgsVectorFileWriter.SaveVectorOptions()
opts.driverName = "GPKG"
writer=QgsVectorFileWriter.create("/tmp/test.gpkg", fields, QgsWkbTypes.MultiLineString, QgsProject.instance().crs(), QgsCoordinateTransformContext(), opts, QgsFeatureSink.SinkFlags(), None, lyrname)
writer.addFeature(feat)
```

Then open _test.gpkg_ with QGIS, QGIS prints the following error message

![error](https://user-images.githubusercontent.com/14358135/85584915-dcb0f180-b63f-11ea-8e63-dc78d88b422e.png)

**QGIS and OS versions**

- Debian bullseye
- QGIS master

**Additional context**

N/A

**Comment by nyalldawson** [comment]
You probably need to 

   del writer

At the end, in order to these the lock on created file

**Comment by troopa81** [comment]
> You probably need to
> del writer
> At the end, in order to these the lock on created file

I try this too and I still get an invalid file. Strange sthing is that while debugging, even if I call the del instruction, the writer destructor is never called and so the gdal dataset never destroyed. 

So I call the following with the same writer in order to be sure to reset the internal gdal dataset

```python
writer.writeAsVectorFormat(iface.activeLayer(), "/tmp/tutu.gpkg", "System")
```

But still an invalid file. And the _tutu_ file is valid

**Comment by troopa81** [comment]
As described [here](https://lists.osgeo.org/pipermail/qgis-developer/2020-June/061616.html) a possible workaround is 

```python
md = QgsProviderRegistry.instance().providerMetadata('ogr')
conn = md.createConnection('/tmp/test.gpkg', {})
conn.createVectorTable('', 'test', fields, QgsWkbTypes.MultiLineString, QgsCoordinateReferenceSystem(), True, {})
```
