### ISSUE TITLE
Temporal Controller Drop Down Unresponsive 

### ISSUE THREAD

**Issue by sam-crossman** [qgis/QGIS#37388]
**Describe the bug**

On QGIS 3.14 pi version on Mac OSX, the temporal controller drop-down menu for selecting a field is unresponsive when editing the properties of a layer of points with coordinates and time indices. 
**How to Reproduce**
Layer->Properties->Temporal->Configuration:Single Field with Date/Time->Field drop down is unresponsive even when there is clearly a time column in the attribute table that should be able to be accessed

**QGIS and OS versions**

**Additional context**

**Comment by nyalldawson** [comment]
Is it a "time" field or "datetime" field?

**Comment by sam-crossman** [comment]
It was a "time" field. I updated it to a "datetime" field and everything is working. Apologies for the inconvenience.

**Comment by nyalldawson** [comment]
No problem! https://github.com/qgis/QGIS/issues/36325 describes adding support for "time" fields
