### ISSUE TITLE
spatial join: non-matching features in joined layer despite "discard records which could not be joined"

### ISSUE THREAD

**Issue by petervdwaal** [qgis/QGIS#37381]
Hi,

There is an issue with the "Join attributes by location" algorithm (SpatialJoin.py) regarding the non-matching features from the input layer. The option "Discard records which could not be joined" is not handled properly.
When I enable the option "Discard records which could not be joined" and set the output of the "unjoinable features from the first layer" to "skip output" then the "joined layer" does not contain the non-matching features as I would expect.
But if I enable the "discard..." option and set the output of the "unjoinable features from the first layer" to create a temporary layer then the "joined layer" does also contain the non-matching features as does the output for "unjoinable features".

So I had a look in de SpatialJoin.py file (for QGIS 3.10.7) and the problem is within the if-block at line 257, which handles the output of non-matching features. The condition in the if-statement at line 262 is the culprit since it is always true (assuming the "joined layer" output is not skipped). In my local installation I changed the if statement at line 262 from "if sink is not None:” to "if not discard_nomatch and sink is not None:". Now the result is what I expect it to be.

Can someone please correct this bug? I'm not comfortable enough with Python and Git to do it myself.

Regards, Peter

**Comment by gioman** [comment]
> There is an issue with the "Join attributes by location" algorithm (SpatialJoin.py) regarding the non-matching features from the input layer. The option "Discard records which could not be joined" is not handled properly.
> When I enable the option "Discard records which could not be joined" and set the output of the "unjoinable features from the first layer" to "skip output" then the "joined layer" does not contain the non-matching features as I would expect.
> But if I enable the "discard..." option and set the output of the "unjoinable features from the first layer" to create a temporary layer then the "joined layer" does also contain the non-matching features as does the output for "unjoinable features".
> 
> So I had a look in de SpatialJoin.py file (for QGIS 3.10.7) and the problem is within the if-block at line 257, which handles the output of non-matching features. The condition in the if-statement at line 262 is the culprit since it is always true (assuming the "joined layer" output is not skipped). In my local installation I changed the if statement at line 262 from "if sink is not None:” to "if not discard_nomatch and sink is not None:". Now the result is what I expect it to be.
> 
> Can someone please correct this bug? I'm not comfortable enough with Python and Git to do it myself.

@petervdwaal is  this still an issue on recent releases? if yes can you attach sample data?
