### ISSUE TITLE
QGIS 3.10: Profile:default: Settings->Options->CRS are ignored

### ISSUE THREAD

**Issue by GitHubrist** [qgis/QGIS#37385]
**Describe the bug**

In the default user profile (the only one I have ever used): 
Changes to Settings->Options->CRS are not preserved between QGIS sessions, 
and sometimes, those same CRS defaults are re-set during a session.

As a result of testing with a new-user profile, debug, I confirm the behavior Does Not Exist in the new profile.

I continue with my report because I cannot imagine how any other "setting" can over-ride the saving of "Options" settings.

**How to Reproduce**

QGIS 3.10, Ubuntu 18.04:

1.   % qgis, as user 'default'
2.   Project->Properties->CRS, note default CRS: WGS 84
3.    Settings->Options->CRS, note CRS-for-projects setting: "Use CRS from first layer added."
4.    Change to: Use a default CRS and change default from WGS 84 to EPSG:5070 - NAD83/Conus Albers
5.    still on CRS page, note CRS-for-layers setting: Default CRS: WGS 84 and "Leave as an unknown CRS."
6.    Leave default CRS for layers set to WGS 84
7.    Change to "Use Project CRS"
8.    Unselect "Ask for a datum tranformation" (I don't know which to pick anyway.)
9.    Click "OK" to close Settings window
10.   Project->Properties->CRS, note default CRS still WRS 84
11.   Project->New
12.   Project->Properties->CRS, note CRS has changed to EPSG:5070
13.   Save the new, empty project.
14.   Or don't: the behavior is the same.
15.   Exit QGIS and re-start.
16.   GOTO 1. (that is, changes have been ignored)

**QGIS and OS versions**

QGIS version | 3.10.4-A Coruña | QGIS code revision | 10bc9f2ff2
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.6.2-CAPI-1.10.2 4d2925d6
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 10.12 (Ubuntu 10.12-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Ubuntu 18.04.4 LTS
Active python plugins | BoundingBox; Beeline; kmltools; qNote; QRectangleCreator; qdraw; ClipMultipleLayers; ArcheoCAD; shapetools; processing; MetaSearch

**Additional context**

Repeating: the bug does not appear in newly created user profile.

**Comment by GitHubrist** [comment]
I believe I have traced the problem to the ownership and permissions of the default config file:
~/.local/share/QGIS/QGIS3/profiles/<profilename>/QGIS/QGIS3.ini
which is owned by root, perms 664, in default/,
and owned by user, perms 664, in new profile, debug/.

**Comment by gioman** [comment]
> ~/.local/share/QGIS/QGIS3/profiles/profilename/QGIS/QGIS3.ini
> which is owned by root

@GitHubrist weird, it not like that in 3 ubuntu 18 machines I just checked.

**Comment by GitHubrist** [comment]
@gioman 
Happy to blame myself (now that I've found it!). 
Thank you for checking for me.

**Comment by gioman** [comment]
> Happy to blame myself (now that I've found it!).
> Thank you for checking for me.

@GitHubrist can we close this ticket then?
