### ISSUE TITLE
CRS not correspond to ESPG

### ISSUE THREAD

**Issue by inouterer** [qgis/QGIS#37404]
Why do the standard CRS parameters in QGIS change from version to version and do not correspond to EPSG? For example:

QGIS EPSG:28412 Pulkovo 1942 / Gauss-Kruger zone 12
+proj=tmerc +lat_0=0 +lon_0=69 +k=1 +x_0=12500000 +y_0=0 +ellps=krass +towgs84=25,-141,-78.5,0,0.35,0.736,0 +units=m +no_defs

EPSG EPSG:28412 Pulkovo 1942 / Gauss-Kruger zone 12
+proj=tmerc +lat_0=0 +lon_0=69 +k=1 +x_0=12500000 +y_0=0 +ellps=krass +towgs84=23.92,-141.27,-80.9,-0,0.35,0.82,-0.12 +units=m +no_defs

**Comment by roya0045** [comment]
This should probably be asked in proj6.

**Comment by gioman** [comment]
@inouterer is this a question or a bug report?

**Comment by rouault** [comment]
> Why do the standard CRS parameters in QGIS change from version to version and do not correspond to EPSG

EPSG offers several transformation parameters between Pulkovo 1942 and EPSG:4326. Depending on EPSG database versions and algorithms in PROJ the default one might change. But you should be able to select the transformation parameters that match well your area of interest.
For this CRS, there are 3 non-superseded candidate transformations between EPSG:28412 and EPSG:4326:
- Pulkovo 1942 to WGS 84 (16),  4.5 m, Europe - FSU onshore (+x=25 +y=-141 +z=-78.5 +rx=0 +ry=-0.35 +rz=-0.736 +s=0)
- Pulkovo 1942 to WGS 84 (20), 3 m, Russia - onshore (+x=23.57 +y=-140.95 +z=-79.8 +rx=0 +ry=-0.35 +rz=-0.79 +s=-0.22)
- Pulkovo 1942 to WGS 84 (7), 44 m, Kazakhstan (ert +x=15 +y=-130 +z=-84)

The one with +towgs84=23.92,-141.27,-80.9,-0,0.35,0.82,-0.12 comes from EPSG:1267 "Pulkovo 1942 to WGS 84 (17)", but this has been superseded by EPSG:5044 "Pulkovo 1942 to WGS 84 (20)". If enabling superseded candidates, EPSG:1267 "Pulkovo 1942 to WGS 84 (17)" will be proposed

**Comment by gioman** [comment]
Closing?
