### ISSUE TITLE
Segmentation Fault when opening layout

### ISSUE THREAD

**Issue by techdude1996** [qgis/QGIS#37415]
**Describe the bug**

Segmentation fault occurs when attempting to open a layout in QGIS 3.14 (PI)

**How to Reproduce**

1. Open project
2. Open layout
3. Segmentation Fault

**QGIS and OS versions**

QGIS version | 3.14.0-Pi | QGIS code revision | 9f7028fd23
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | (occurs with --noplugins)

**Additional context**

Thankfully, this doesn't happen on all my projects. In this particular project, I am able to create a new layouts, close and re-open them within the same QGIS session. When I quit QGIS and reload the project, and attempt to open the previously created layout, it crashes.

**Attachment**

Attached is the xml of one of the layouts that crash. I'm assuming this is where the issue lies.
[layout.txt](https://github.com/qgis/QGIS/files/4831999/layout.txt)

**Comment by gioman** [comment]
> Attached is the xml of one of the layouts that crash. I'm assuming this is where the issue lies.
> [layout.txt](https://github.com/qgis/QGIS/files/4831999/layout.txt)

@techdude1996 can you please attach a sample project with the layout and a minimal set of data? Thanks.

**Comment by techdude1996** [comment]
This appears to just be an issue with the particular QGIS file itself, as I am unable to reproduce this error with a different file.

**Comment by gioman** [comment]
@techdude1996 please attach the offending project/layout.

**Comment by techdude1996** [comment]
[Margate Utilities - Working.zip](https://github.com/qgis/QGIS/files/4832136/Margate.Utilities.-.Working.zip)

**Comment by gioman** [comment]
> Margate Utilities - Working.zip

@techdude1996 there are 3 layouts in this project, none of them crashes QGIS here (master on Ubuntu 18.04).

**Comment by gioman** [comment]
@techdude1996 please try with a new QGIS profile, no 3rd party plugins installed.

**Comment by techdude1996** [comment]
@gioman Still causes a segmentation fault.

**Comment by gioman** [comment]
> @gioman Still causes a segmentation fault.

@gioman now here (also on Windows). Try create a sample project (with a minimal dataset) that shows the issue. Without it it would be hard to help.

**Comment by techdude1996** [comment]
@gioman I ended up just recreating a whole new QGIS project file and don't get the segmentation fault. I think there was some weird glitch because this file came from the previous version (3.12). You are free to close this if you wish.

**Solution (Work-Around)**
Recreate the project file.
