### ISSUE TITLE
Legends in layouts 'Split Layers' with uneven Columns

### ISSUE THREAD

**Issue by abodsalas** [qgis/QGIS#37417]
Hello this is a bug that affects legend creation with columns in QGIS 3.14 and Ubuntu 20.04
I have a theme with 27 categories. I wish for the legend to display 9 columns, with 3 categories per column.
QGIS shows 4 columns with 3 categories, 4 categories, 2 categories and 1category, instead of showing 9 columns with 3 categories (9 · 3 = 27 categories).

**How to Reproduce**
Create a polygon layer with 27 polygons, create an Integer field ("Id"), assign value of id = @row_number.
Symbolize polygons by categories, using "Id" field. 
Create Layout, add Legend. Hide the layer's name.
In columns fill Columns with 9, activate Split Layers option.

Below is a caption of the situation.

![imagen](https://user-images.githubusercontent.com/54449155/85763367-9791cb80-b6e2-11ea-9ee2-3b1648bbe222.png)

I'm also attaching a zip file with QGZ and GPKG.
[Bug_Split_Theme_Columns.zip](https://github.com/qgis/QGIS/files/4832712/Bug_Split_Theme_Columns.zip)

*** I believe it may have something to do with the "Space between symbols". When its 0 - 0.5 mm, columns have 3 categories each. As I increase its value, columns begin to scramble.

"Space between symbols" = 0,5 mm
![imagen](https://user-images.githubusercontent.com/54449155/85789912-64106a80-b6fd-11ea-93f1-0d1edd777bd7.png)

"Space between symbols" = 1,0 mm
![imagen](https://user-images.githubusercontent.com/54449155/85789987-80140c00-b6fd-11ea-8d83-7970b495ac32.png)

"Space between symbols" = 3,0 mm
![imagen](https://user-images.githubusercontent.com/54449155/85790074-a33ebb80-b6fd-11ea-9fd6-8bd38173cfad.png)

Andres Bodini

**FIRST EDIT:**
Apparently the error could be in the file: QGIS-master/src/core/qgslegendrenderer.cpp
However I don't know C++..... 

I attach the file in case anyone that knows C++ can help.

[qgslegendrenderer.cpp.zip](https://github.com/qgis/QGIS/files/4973434/qgslegendrenderer.cpp.zip)

**Comment by gioman** [comment]
> Hello this is a bug that affects legend creation with columns in QGIS 3.14

@abodsalas was ok in previous releases?

**Comment by abodsalas** [comment]
All I can say is that the same error occurs in another machine with Windows
10 and QGIS 3.14.

**Comment by gioman** [comment]
True also on 3.10.7.

**Comment by baswein** [comment]
It seems it was true in 2.14 as well. See this stack exchange thread:  https://gis.stackexchange.com/questions/368586/qgis-legend-distribution-of-items-across-columns-recurring-problem?noredirect=1#comment603643_368586 I can confirm that it is still an issue on 3.14.0 on windows.

**Comment by abodsalas** [comment]
> It seems it was true in 2.14 as well. See this stack exchange thread: https://gis.stackexchange.com/questions/368586/qgis-legend-distribution-of-items-across-columns-recurring-problem?noredirect=1#comment603643_368586 I can confirm that it is still an issue on 3.14.0 on windows.

Thanks baswin. So... this is a pretty old BUG in QGIS. I can confirm that QGIS 3.14.1 in Linux Mint 20 Cinnamon still has it.
The only thing I've discovered so far is that the problem is probably in the file: **QGIS-master/src/core/qgslegendrenderer.cpp**

There is a part where it says:
  // We know height of each group and we have to split them into columns
  // minimizing max column height. It is sort of bin packing problem, NP-hard.
  // We are using simple heuristic, brute fore appeared to be to slow,
  // the number of combinations is N = n!/(k!*(n-k)!) where n = groupCount-1
  // and k = columnsCount-1

It seems there is a problem in the calculations, because so many things have to be considered when dividing into columns.
Unfortunately I don't know c++.
I'll attach the **qgslegendrenderer.cpp** file in case anyone that knows c++  can help fix this.

**Comment by baswein** [comment]
Not sure if this is helpful but there seems to be a relationship between Symbol Height and Space Between Symbols. 4mm/1mm doesn't work but 4mm/.99mm does as does 4.01mm/1mm. You can find similar threshold relationships as you go up  in multiples of 4mm and 1mm. For example 8mm/2mm, 12mm/3mm, 16mm/4mm, 20mm/5mm

**Comment by jdugge** [comment]
@abodsalas, @baswein: Thanks for the thorough diagnosis, that saved a lot of time in fixing the bug!

**Comment by OlivaresLD** [comment]
The bug is still present on QGIS 3.22.11. At the moment the only "fix" is to handle the 'Space between symbols' until it fits well.
![imagen](https://user-images.githubusercontent.com/45223906/212131342-2a8ce715-bebd-4771-aab3-c5064f57fc28.png)

**Comment by kaarigar** [comment]
This most annoying bug is not fixed - at least not in the 3.34.2-Prizren version.

**Comment by jdugge** [comment]
@kaarigar Could you describe a way to reproduce the bug? I'll take a look to see why the original bugfix doesn't seem to work in your case.

**Comment by kaarigar** [comment]
> @kaarigar Could you describe a way to reproduce the bug? I'll take a look to see why the original bugfix doesn't seem to work in your case.

This issue happens when a layer is symbolized on say Categorized or Graduated or Rule Based, etc. In this case, tall the categories would appear under a group layer. In the Print Layout legend item, if I suppress the display of the group layer name (by setting Subgroup font size to zero) , the legend items are not properly distributed across columns. I am not sure if this is a user error, but I couldn't find a way to avoid it. Only way I could avoid this was by saving and adding each category as a separate layer. I hope this helps you in your investigations.

![image](https://github.com/qgis/QGIS/assets/44623903/6274d9a8-7165-425b-b85b-0d6f29ba3718)

![image](https://github.com/qgis/QGIS/assets/44623903/f4fe3cf7-142c-4fcd-9b24-6a64a84fc108)

**Comment by jdugge** [comment]
@kaarigar This happens because even with a font size of 0, the title still takes up some space. A better way to hide the title is to set it to "Hidden" using the context menu: https://gis.stackexchange.com/a/439202/1931

This will result in balanced columns in this case.

**Comment by kaarigar** [comment]
> @kaarigar This happens because even with a font size of 0, the title still takes up some space. A better way to hide the title is to set it to "Hidden" using the context menu: https://gis.stackexchange.com/a/439202/1931
> 

@jdugge Thank you for pointing this out - it now gets me what I want!
