### ISSUE TITLE
QGIS 3.14 PI update can not make new MSSQL connecion

### ISSUE THREAD

**Issue by NvBgm** [qgis/QGIS#37427]
After update QGIS3.12 to QGIS 3.14 you can not adding a new MSSQL connection because the OK button on the configuration popup is grey out.
I did a new install clean install on another pc with QGIS3.12 and the possibility to add a new MSSQL connection was oke.
Also after the update on this clean install to version QGIS3.14 the same problem. The OK button on the config screen to add a new MSSQL connection did not work.
It does make connection and it show me the list off databases but it it not possible use the OK button.

![image](https://user-images.githubusercontent.com/8125819/85836509-f57feb00-b796-11ea-99cc-153f18fb1087.JPG)

**Comment by erizk** [comment]
I am having the same issue, if you try to insert a provider/DNS name this will activate the ok button.

my issue here that I don't know how to identify the provider/DNS of an SDE ESRI database on SQL.

**Comment by agiudiceandrea** [comment]
Probably the new behavior was introduced in QGIS 3,14 by @alexbruy with commit https://github.com/qgis/QGIS/commit/e2f106bab96c4cb7d40f0d0ecafcc72af0fb5aa7 (PR https://github.com/qgis/QGIS/pull/35838) in order to fix #26038:

> Ok button in new connection dialog for OGR, PostGIS, Oracle, MSSQL, DB2, XYZ and Vector tile providers enabled only if all required fields are not empty preventing loosing data. Fixes #26038.

https://github.com/qgis/QGIS/blob/56868373635748000fe22fb789afda7bbc172594/src/providers/mssql/qgsmssqlnewconnection.cpp#L253-L258
So "Connection name", "Provider/DSN" and "Host" fields must not be empty.

**Comment by erizk** [comment]
So, anyone can help us, 
what is the provider/dns value for a MSSQL connection?

**Comment by nyalldawson** [comment]
What did you previously use? Did it work with them all empty?

**Comment by erizk** [comment]
Yes it worked properly without provider on version 3.12.

**Comment by nyalldawson** [comment]
Ok. A short term workaround would be to put anything in there to allow saving the setting, and then use the advanced settings editor through the options dialog to remove that unwanted setting...

**Comment by nyalldawson** [comment]
Ok. A short term workaround would be to put anything in there to allow saving the setting, and then use the advanced settings editor through the options dialog to remove that unwanted setting...

**Comment by erizk** [comment]
Thank you nyall, i tried to put anything and the connection was created but when i double click to connect it shows a red warning in the browser and on top of the screen saying that you have a problem with ur dns. I tried to surf the internet to sort out the provider dns for a sql but i didnt found it.

**Comment by agiudiceandrea** [comment]
@erizk is your QGIS running on Windows? Did you try to use `driver={SQL Server}` for the Proider/DSN connection parameter?

**Comment by NvBgm** [comment]
> @erizk is your QGIS running on Windows? Did you try to use `driver={SQL Server}` for the Proider/DSN connection parameter?

For me it works with the suggestion off @agiudiceandrea 

driver={SQL Server}

Thanks

**Comment by agiudiceandrea** [comment]
> > @erizk is your QGIS running on Windows? Did you try to use `driver={SQL Server}` for the Proider/DSN connection parameter?
> 
> For me it works with the suggestion off @agiudiceandrea
> 
> driver={SQL Server}
> 
> Thanks

Well, it seems `driver={SQL Server}` is the dafult when Provider/DSN is empty on Windows OS, while `driver={FreeTDS};port=1433;TDS_Version=auto` is the dafault on other platforms.
https://github.com/qgis/QGIS/blob/56868373635748000fe22fb789afda7bbc172594/src/providers/mssql/qgsmssqlconnection.cpp#L91-L107

**Comment by NvBgm** [comment]
I think i had my party to early because with the "driver={SQL Server}" the connection is establish but i con not retrieve any data from the dbo.

The error i get is: "There are no keyword for DSN or SEVER geven.

**Comment by agiudiceandrea** [comment]
Using  "driver={SQL Server}" is just to allow to make the connection, press ok and saving the connection settings.
Then you can follow the advice of Nyall:
> use the advanced settings editor through the options dialog to remove that [Service] unwanted setting

So the connection should work as before 3.14.

**Comment by erizk** [comment]
I established the connection using the "driver={SQL Server}" but the feature classes were retrieved as attributes table without any geometries in both schemas dbo & sde
noting that if I uncheck the option allowGeometrylessTables I couldn't have any data

**Comment by NvBgm** [comment]
> I established the connection using the "driver={SQL Server}" but the feature classes were retrieved as attributes table without any geometries in both schemas dbo & sde
> noting that if I uncheck the option allowGeometrylessTables I couldn't have any data

Did  you follow the advice of Nyall: ?

**Comment by erizk** [comment]
yes, I did.
the highlighted tables are feature classes 
![image](https://user-images.githubusercontent.com/8122800/86010938-c383b880-ba24-11ea-89a7-0499cc618c0b.png)

**Comment by gioman** [comment]
>  the highlighted tables are feature classes

@erizk is that a native SQL Server database, or it a SQL server being used by ArcGIS server to write data in proprietary ESRI format?

**Comment by erizk** [comment]
SQL server being used by Arcgis for server holding SDEs and DBO database schemas.

**Comment by erizk** [comment]
it is working fine after installing any needed library for MSSQL such as (gdal2-mss SQL native client support), using the "driver={SQL Server}" as a provider/DSN & applying the Nyall's advice (deleting the provider from the advanced settings).

thank you.
