### ISSUE TITLE
esecuzione di processing di dati

### ISSUE THREAD

**Issue by MichelaG71** [qgis/QGIS#37428]
Buongiorno spero sia il posto giusto dove evidenziare una richiesta. Nel tentare di fare del geoprocessing sui dati di Uso del suolo della regione emilia romagna scaricabili al link:

https://geoportale.regione.emilia-romagna.it/download/dati-e-prodotti-cartografici-preconfezionati/pianificazione-e-catasto/uso-del-suolo/2017-coperture-vettoriali-uso-del-suolo-di-dettaglio-edizione-2020/dati-preconfezionati

certe geometrie delle layers sono rilevate come “non valide” ed impediscono qualsiasi operazione di processing, anche impostando quel “Salta (ignora) elementi con geometrie non valide” . Vorrei poter effettuare ad es. un semplice clip della layer.
grazie
Michela

**Comment by gioman** [comment]
@MichelaG71 Hi, this is the QGIS bug tracker and must be used only to report bugs (or supposed ones) and feature requests. For support use the users or developers mailing lists, the QGIS IRC channel or gis.stackexchange.

Anyway you may want to try the "fix geometries" tool on your input before attempting any geoprocessing operation. In fact the linked vector is full of geometry errors (check with PostGIS).
