### ISSUE TITLE
QGIS freeze, lag, stuttering on fresh Windows 10 installation. Solution included.

### ISSUE THREAD

**Issue by ScalingR** [qgis/QGIS#37438]
Problem:
Fresh install of Windows 10 Pro 64 bit and QGIS 3.14 (and older) leads to heavy lags, and delayed responsiveness when interacting with the browser panel. Problem vanishes as soon as browser panel is closed.

Solution:
QGIS seem to have a problem with "ghost"-devices. Had the floppy drive activated in my BIOS settings. Needless to say my machine dont use floppys anymore. It even showed up in Windows-Explorer. Deactivation of the floppy in BIOS was the solution and QGIS is running smooth as expected now. (Should work for similar device problems like card-readers)

**Comment by roya0045** [comment]
There are other report about drives and the browser, this is known. Though the bios thing might be helpful for users.

**Comment by Pedro-Murteira** [comment]
@ScalingR Hello, I was not able to reproduce this issue on all of the more recent releases. Did this issue occur to you more recently?
