### ISSUE TITLE
Postgres view failing if PK / join on bigint.

### ISSUE THREAD

**Issue by GeoJGH** [qgis/QGIS#37437]
Hello

This issue sounds similar to [PgSQL bigint values shown as NULL if they are part of composite PK]( https://github.com/qgis/QGIS/issues/37126 ) although the way to exhibit the issue is totally different.

**Describe the bug**

I am displaying a Postgres view, which contains a join between two tables. If the ID used in the join is of type bigint, then the field selected as being the "feature id" (i.e. the assumed PK) is returned as NULL.

Let's note that
- If the ID is integer, there is no problem
- If no join is involved in the view, there is no problem
- If no field from the joined table is displayed, there is no problem
- If I add an alias to the PK field and keep the main field as the Feature ID (PK) field, the PK is NULL but the alias is populated
- If I select the alias as the Feature ID (PK) field, keeping the join on the main PK field, the alias will be NULL and the main PK will be populated.

It has some serious side effects: 
- Attribute table is said to contain only 1 record (of course, all records having the same NULL PK). 
- Selecting 1 item on the map will select all records.
- It is not possible to open the record form

**How to Reproduce**

In Posgtres, create a view:

CREATE OR REPLACE VIEW publivc.SV_test_key
AS
SELECT sub.some_text, --at least 1 field from the joined table must be used
            src.myID id_alias, -- an Alias on the ID field, so it can be used as the PK
            src.* --the ID and geom
FROM (
        select 1::bigint as myID, st_geomFromText('point(0 0)')::geometry geom
        UNION ALL
        select 2::bigint as myID, st_geomFromText('point(1 1)')::geometry geom) src
LEFT JOIN (select -1::bigint as myID, 'whatever' as some_text) sub 
	ON src.myID = sub.myID
	;

![image](https://user-images.githubusercontent.com/39196082/85900566-0d269600-b7ce-11ea-8d8b-2134b35e596f.png)

![image](https://user-images.githubusercontent.com/39196082/85900665-2fb8af00-b7ce-11ea-9125-4c59c98c3a1c.png)

**QGIS and OS versions**

QGIS version | 3.10.7-A Coruña | QGIS code revision | 7b4ca4c8d0
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | latlontools; QuickWKT; quick_map_services; db_manager; MetaSearch; processing; CustomToolBar

Postgres:  PostgreSQL 12.1, compiled by Visual C++ build 1914, 64-bit
 POSTGIS="3.0.0 r17983" [EXTENSION] PGSQL="120" GEOS="3.8.0-CAPI-1.13.1 " SFCGAL="1.3.2" PROJ="Rel. 5.2.0, September 15th, 2018" LIBXML="2.9.9" LIBJSON="0.12" LIBPROTOBUF="1.2.1" WAGYU="0.4.3 (Internal)"
**Additional context**

**Comment by GeoJGH** [comment]
Oh, I forgot a major detail: It was working fine under 3.10.6

**Comment by gioman** [comment]
@espinafre maybe a regression caused by some recent fix?

**Comment by espinafre** [comment]
Hi, @gioman , I'm investigating this, but it looks like QGIS thinks the column "some_text" in the original query is the primary key. @GeoJGH , thanks for reporting. If you move your field that you need to be the primary key to the top of the view definition, QGIS should display it correctly:

```sql
CREATE OR REPLACE VIEW public.test_bigint_view3 AS
SELECT
        src.myID want_this_to_be_pk, -- an Alias on the ID field, so it can be used as the PK
        sub.some_text, --at least 1 field from the joined table must be used
        src.* --the ID and geom
FROM
(
        SELECT
                1::bigint AS myID,
                ST_GeomFromText('Point(0 0)')::geometry geom
        UNION ALL
        SELECT
                2::bigint AS myID,
                ST_GeomFromText('Point(1 1)')::geometry geom) src
LEFT JOIN
(
        SELECT
                -1::bigint AS myID,
                'whatever' AS some_text) sub
ON src.myID = sub.myID
;
```

I'm still looking at this issue.

**Comment by GeoJGH** [comment]
Great! Thanks a lot for the ultra-fast workaround solution!

I confirm moving the PK to the 1st field works. I can still pick another further field as the feature id column (PK), like `src.myID ` instead of `want_this_to_be_pk` and both fields remain properly populated in the attribute table

**Comment by espinafre** [comment]
You are aware that "want_this_to_be_pk" is an alias for the column src.myID, right? I forgot the optional "AS" keyword on the view definition.

**Comment by GeoJGH** [comment]
Yes, no problem for the alias.

Following your discovery, I pushed a bit the tests and it appears the issue is not related to the join at all, but to the 1st field type only. This 1st field can be a constant. The issue remains dependent on the declared Feature ID (PK) field: no problem with Integers, issues with BIGINT. In the 3 case below, the field `myID` was used as the Feature ID (PK) field.

```sql
--Failure, no join but a text 1st field	
CREATE OR REPLACE VIEW public.SV_test_11
AS
SELECT 'fail' as failure_field, src.*
FROM (
  select 1::bigint as myID, st_geomFromText('point(0 0)')::geometry geom
UNION ALL
  select 2::bigint as myID, st_geomFromText('point(1 1)')::geometry geom
) src
;	
```		
	
```sql
-- OK, 1st field is a number	
CREATE OR REPLACE VIEW public.SV_test_11_ok
AS
SELECT 999::bigint as success_field, src.*
FROM (
  select 1::bigint as myID, st_geomFromText('point(0 0)')::geometry geom
UNION ALL
  select 2::bigint as myID, st_geomFromText('point(1 1)')::geometry geom
) src
;			
```

```sql
--OK, PK is an integer
CREATE OR REPLACE VIEW public.SV_test_11_int
AS
SELECT 'success' as success_TEXT_field, src.*
FROM (
  select 1::int as myID, st_geomFromText('point(0 0)')::geometry geom
UNION ALL
  select 2::int as myID, st_geomFromText('point(1 1)')::geometry geom
) src
;		
```

**Comment by GeoJGH** [comment]
And the 2nd test (with `SELECT 999::bigint as success_field, src.*`) indicates that the 1st field is not considered as the PK, because even though the value is a constant, I can select individual entries. 

I made another test with various values in the 1st field, corresponding to other entries (so values 1, 2, 3, assigned to features whose ID is 3,2,1) and the selection was pointing to the proper feature, so the declared PK was truly used, not the values found in the 1st field

**Comment by Pedro-Murteira** [comment]
@GeoJGH Hello, is this issue still valid on recent releases?

**Comment by GeoJGH** [comment]
@Pedro-Murteira I just re-ran the same queries (public.SV_test_key and public.SV_test_11) under 3.16.14 and it is working fine. I don't know for newer versions
