### ISSUE TITLE
Load all styles associated to a layer when loading the layer

### ISSUE THREAD

**Issue by adjeprado** [qgis/QGIS#37434]
**Feature description.**

Despite it being possible for multiple styles to be saved to a single layer in a GeoPackage, when the layer is loaded again, only the default style is loaded with it. This is despite the layer being identified in the f_table_name attribute of the layer_styles table. Intuitively, it should be expected that all styles associated with the layer would be loaded when the layer is imported into QGIS.

**Additional context**

Currently you can save multiple styles to a layer in the gpkg and when you do this, this is the resulting style selection interface:
![image](https://user-images.githubusercontent.com/48444740/85872007-95447580-b7a5-11ea-99ec-6afbf4e2bd92.png)
However, when this layer is reloaded it results in only the default style being loaded:
![image](https://user-images.githubusercontent.com/48444740/85872093-abeacc80-b7a5-11ea-91a4-bc7b363f24b8.png)

Ideally, QGIS should search through the **layer_styles** table within the gpkg and natively associate the styles listed in the table to the layer if it has the same name as the entry in the **f_table_name column** of the table.

@Gustry has indicated that he developed a plugin for this same issue with postgresql layers: https://github.com/PnGuadeloupe/db-style-manager . Perhaps this feature could be applied to all database  structures within QGIS.

This post was originally made as a possible bug post, which has since been closed: https://github.com/qgis/QGIS/issues/37419

**Comment by gioman** [comment]
I guess this can be extended to any backend that supports style saving, like PostGIS.

**Comment by NyakudyaA** [comment]
I opened up this issue a while back https://github.com/qgis/QGIS/issues/35293

**Comment by adjeprado** [comment]
@NyakudyaA I think the post you made is a little different since it's about loading multiple styles, while my suggestion is to import styles associated to a layer automatically with the layer import. I think both would be nice features, but I'm not sure if you would need to manually load multiple styles if it was done automatically as of import.

**Comment by jfbourdon** [comment]
Just to add a little bit on this feature request here, I would suggest that the default style be named by it's name regardless of the number of available styles instead of just the label _default_.

![image](https://user-images.githubusercontent.com/32580398/184194155-eb7194c4-2e86-4562-b1e5-b4f07d5a5abc.png)

**Comment by gotjoshua** [comment]
Cross listing this 
https://ecodiv.earth/post/save-project-to-geopackage-in-qgis/

One thing i noticed is that after using the [package layers] dialog, changing the styles does not update in the geopackage layer, but rather in the project.

I also cannot use the package layers dialog again to save the same layer "in place" so i need to make another layer, delete the old one and rename the new one to the old name.

Is there a better way to update the styles of a geopackage layer?

**Comment by elpaso** [comment]
IMHO this is a bug but not a regression because it never worked as expected.
