### ISSUE TITLE
Exported map from Print layout displays data outside the map frame when vector tile layers are present

### ISSUE THREAD

**Issue by gvellut** [qgis/QGIS#37443]
When I export a map into PNG from a print layout that includes a map frame that doesn't cover the whole page, the rendered map goes beyond the frame when a vector tile layer is present. 

Here is what I mean (the purple background is the background of the print layout and the black frame is the extent of the map in the layout; the maps have the same extent, I just toggled different layers in the canvas)

Just a vector layer (from a GPKG):

![printmap_onlyline](https://user-images.githubusercontent.com/3685/85921761-cfce1100-b87e-11ea-96ef-f7e0cac6b41d.png)

With a vector tile service in the map (using the Topo layer in the MapTiler QGIS plugin, which adds a standard Vector Tile layer):

![printmap_vector_tileservice](https://user-images.githubusercontent.com/3685/85921763-d066a780-b87e-11ea-9a14-b3a62cb6fd8f.png)

In this case, the GPKG layer also goes beyond the map frame. However, it is clipped to the extent of what is drawn for the vector tile layer.

For comparison, with a raster tile service:

![printmap_raster_tileservice](https://user-images.githubusercontent.com/3685/85921762-d066a780-b87e-11ea-9872-58261dd5f556.png)

I have included a sample QGIS project: [example.zip](https://github.com/qgis/QGIS/files/4840476/example.zip)
1. Open the printmap Print Layout.
2. Export as PNG
3. Toggle the layers in the canvas to see how it changes

I am on macOS 10.14 with QGIS 3.14.

**Comment by nyalldawson** [comment]
Actually a bug in the vector tiles renderer

**Comment by baswein** [comment]
I just encountered this in 3.14.15. Should have it been fixed in that version?

**Comment by nyalldawson** [comment]
@baswein - no, you'll need this week's update (3.14.151?)

**Comment by jmasselink** [comment]
I'm using 3.26.1 and believe I've encountered this issue. See the screenshot drawing the blue water from the MapTiler Planet outside of the map frame.
![image](https://user-images.githubusercontent.com/11066771/182640379-24e8d22e-29b2-4e11-930d-2d8f8f3c8779.png)
