### ISSUE TITLE
Raster quantile symbology does not work for float64 rasters

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#37449]
Sample data: https://github.com/qgis/QGIS/files/4840624/RISCO.zip

Must be tested on 3.10.7 because on 3.14/master quantile symbology is broken, see: https://github.com/qgis/QGIS/issues/37448

From https://github.com/qgis/QGIS/issues/35465#issuecomment-650565325 :

With this raster, quantiles are not correctly calculated (in this case, in QGIS 3.10.7, as it does not work in 3.14).

Rounding that raster and converting to a Int32, it already calculate quantiles correctly (image on the right):

quantile_float64

Using Raster Pixels to Points algorithm to export Float64 pixel values to points, and calculating quantiles in the resulting vector layer, the output is the correct (as seen on the left image).

Running r.quantile in the Float64 raster, the output is correct:

0:20.000000:120.000000
1:40.000000:1320.000000
2:60.000000:2400.000000
3:80.000000:4500.000000 

Also correct exporting to CSV and calculating in R:

> tabela_risco <- read.csv("D:\\RISCO_RASTER_PIXELS_TO_POINTS.csv")
> quantile(tabela_risco$VALUE, probs = c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0))
      0%      10%      20%      30%      40%      50%      60%      70%      80%      90%     100% 
    36.0     72.0    120.0    792.0   1320.0   1920.0   2400.0   3000.0   4500.0   6000.0 218030.4

So, it seems that quantile classification is still failing with some kind of data.

**Comment by elpaso** [comment]
@PedroVenancio is this the expected (correct) output?

![immagine](https://user-images.githubusercontent.com/142164/85942998-6ce78300-b92d-11ea-8fb6-8e13915254d7.png)

**Comment by PedroVenancio** [comment]
Hi @elpaso 

That's correct! Here is the output of other algorithms:

https://github.com/qgis/QGIS/issues/35465#issuecomment-650565325

The only strange thing is the precision of the breaks. Quantiles should show values that exist in raster pixels. These values are:

[RISCO_RASTER_PIXELS_TO_POINTS_GROUP_BY.zip](https://github.com/qgis/QGIS/files/4842052/RISCO_RASTER_PIXELS_TO_POINTS_GROUP_BY.zip)

Do you know why the precision is so high in your breaks?

Thank you very much @elpaso !

**Comment by elpaso** [comment]
> Hi @elpaso
> 
> That's correct! Here is the output of other algorithms:
> 
> [#35465 (comment)](https://github.com/qgis/QGIS/issues/35465#issuecomment-650565325)
> 
> The only strange thing is the precision of the breaks. Quantiles should show values that exist in raster pixels. These values are:
> 
> [RISCO_RASTER_PIXELS_TO_POINTS_GROUP_BY.zip](https://github.com/qgis/QGIS/files/4842052/RISCO_RASTER_PIXELS_TO_POINTS_GROUP_BY.zip)
> 
> Do you know why the precision is so high in your breaks?

To my understanding, this is because of the way it is currently implemented: first the bin size is chosen according to an algorithm which is different for integral types and floating point types and it is limited for both to (now) 10'000'000, so there is a chance that the number of bins is lower than the number of unique values in the raster. 

The bins are all of equal width and the limits of the bins are not likely to be actual raster values (except for smaller integral rasters when the bin count is limited to the values range and the bin has always width = 1).

**Comment by PedroVenancio** [comment]
Thank you very much @elpaso !
