### ISSUE TITLE
Lost project completely after script (and QGIS) became unresponsive

### ISSUE THREAD

**Issue by AlexShafir** [qgis/QGIS#37444]
**Describe the bug**
I have thousands of points in layer. I tried to print them using Python script window. 
It got stuck at some point and I closed application via Task Manager.

When I re-opened project, all my layers were gone (lost project).

**How to Reproduce**

Happened to me only one time, did not reproduce.

```python
dest = QgsProject.instance().mapLayersByName('Random points')[0]

for feat in dest.getFeatures():
	print(feat)
```

**QGIS and OS versions**

QGIS version
3.14.0-Pi
QGIS code revision
9f7028fd23
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 7 SP 1 (6.1)
Active python plugins
db_manager; 
MetaSearch; 
processing

**Comment by gioman** [comment]
> closed application via Task Manager

> ll my layers were gone (lost project)

if you kill the program and you have an unsaved project and layers, of course they will be lost.




> ```python
> dest = QgsProject.instance().mapLayersByName('Random points')[0]
> 
> for feat in dest.getFeatures():
> 	print(feat)
> ```

seems incomplete, can you post the whole script?

**Comment by nyalldawson** [comment]
I don't see anything we can do here -- there's 1000s of ways you could write a python script which locks up qgis. Even something like

   while True:
     pass

Will effectively "lock" qgis.

Your script isn't even buggy, it's just going to take A LOT of time to finish for massive layers...

**Comment by AlexShafir** [comment]
Switched to Processing in the end.
