### ISSUE TITLE
Simple attempt to export a map image to a TIF file

### ISSUE THREAD

**Issue by TooMuch2020** [qgis/QGIS#37452]
Made several attempts to export a Google Map image as a TIF in a 5 minute by 5 minute box over Mogadishu.

Min and Max: 45.250001428306625,45.33333443340225,2.000000603254735,2.083333608350393 [EPSG:4326]
Had four DTED1 files loaded, one vector grid rendered in the same 5 minute by 5 minute boxes. Loaded Google maps and attempted the export. The bounds were pasted above. default DPI, zoom was out so the entire box was in view+ 1:50000
## User Feedback

Attempting to export a map image to TIFF in a 5 minute by 5 minute box

## Report Details

**Crash ID**: [1d5ed672dc1b64fc24118b59e560969ad8cbd8bb](https://github.com/qgis/QGIS/search?q=1d5ed672dc1b64fc24118b59e560969ad8cbd8bb&type=Issues)

**Stack Trace**
<pre>
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QRasterPaintEngine::fillRect :
QRasterPaintEngine::drawImage :
QgsRasterDrawer::drawImage qgsrasterdrawer.cpp:174
QgsRasterDrawer::draw qgsrasterdrawer.cpp:105
QgsRasterLayerRenderer::render qgsrasterlayerrenderer.cpp:272
QgsMapRendererCustomPainterJob::doRender qgsmaprenderercustompainterjob.cpp:316
QgsMapRendererCustomPainterJob::renderPrepared qgsmaprenderercustompainterjob.cpp:235
QgsMapRendererTask::run qgsmaprenderertask.cpp:239
QgsTask::start qgstaskmanager.cpp:83
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.12.3-Bucure?ti
QGIS code revision: 8234261527
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment]
@TooMuch2020 please try with a new QGIS profile, if the problem persist please attach a sample project and the exact steps to follow to replicate the problem.

**Comment by gioman** [comment]
Closing for lack of feedback.
