### ISSUE TITLE
Field calculator Custom function does not recognize MultiLineStringZ geometry records

### ISSUE THREAD

**Issue by lovenjak** [qgis/QGIS#37458]
**Describe the bug**
I am unable to conduct any calculation using Field calculator's custom function while operating on MultiLineStringZ records. However, output preview in Field Calculator's tab Expression provides a correct output. After pressing OK button, however, the geometry is not recognized and I am unable to use it.

[Simple dataset demonstrating the issue](https://github.com/qgis/QGIS/files/4842290/custom-function-bug.zip)

I tried using MultiLineStringZ layer in IDE. Everything works as expected. See `ideScript.py` for a working example. I am unable to create corresponding Field calculator custom function since I am unable to access geometry parts, probably because geometry is unknown. Yet again, output preview provides the same correct numeric result as IDE, but it cannot be applied to all records.

**How to Reproduce**

1. Load shapefile containing MultiLinestringZ records (`data.shp`).
2. Enter Field Calculator, tab Function Editor
3. Create new function file
4. Copy in the content of `getWkbType.py`/`getWkpTypeString.py`
5. Run "Save and Load Functions
6. Switch to Expressions tab and pick getWkbType/getWkbTypeString
7. Check Output preview (1005/'MultiLineStringZ')
8. Select Create New Field, pick new field name and type (integer/text)
9. Press OK
10. Check Attribute table. (0/'Unknown')

**QGIS and OS versions**

QGIS version | 3.10.4-A Coruña | QGIS code revision | 10bc9f2ff2
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Windows 10 (10.0)
Active python plugins | db_manager; MetaSearch; processing

I also tried using the newest QGIS version on another computer but the results remain the same.
3.14.0-Pi @ Windows 10, 10.0.18363

**Additional context**
The output preview is correct, but the final result is not. Since the problem is not in field type, I suppose it is a bug.

**Comment by agiudiceandrea** [comment]
Hi @lovenjak you provided the following custom functions:

```python
from qgis.core import *

@qgsfunction(args='auto', group='Custom')
def getWkbType(feature, parent):
    return feature.geometry().wkbType()

@qgsfunction(args='auto', group='Custom')
def getWkbTypeString(feature, parent):
    geometry = feature.geometry()
    return QgsWkbTypes.displayString(geometry.wkbType())
```

and you use them in the expression tab as `getWkbType()` and `getWkbTypeString()`


try instead:

```python
from qgis.core import *

@qgsfunction(args='auto', group='Custom')
def getWkbType(geom, feature, parent):
    return geom.wkbType()

@qgsfunction(args='auto', group='Custom')
def getWkbTypeString(geom, feature, parent):
    return QgsWkbTypes.displayString(geom.wkbType())
```

and use the functions as `getWkbType( $geometry )` and `getWkbTypeString( $geometry )`
