### ISSUE TITLE
Shapely availability in QGIS

### ISSUE THREAD

**Issue by Dan-Eli** [qgis/QGIS#37462]
I noticed that at least since QGIS 3.4 Shapely library  is part of the regular QGIS distributions.  I know it was not always the case in earlier distribution.

Is it now "normal" for QGIS to include Shapley in the regular distribution?  I would suggest to include somewhere in the documentation a page listing the libraries included in the distribution and for each the version of the library.

Like this, it would be clearer for developper what is accessible from each QGISdistribution.

Note 1: Very good idea to include Shapely in QGIS distribution.  I used a lot Shapely to develop script and it is now easier to port these script into QGIS Processing with Shapley part of the regular distribution.

Note2: This is true for Windows distribution. I do not know the status for Mac and Linux distribution

**Comment by roya0045** [comment]
Should be intended for https://github.com/qgis/QGIS-Documentation and not qgis itself I guess.

**Comment by Dan-Eli** [comment]
Good point.
Did not know that there was a [QGIS-documentation on Git-Hub ](https://github.com/qgis/QGIS-Documentation).  I will push this documentation request there.
