### ISSUE TITLE
Transform CRS bug for Austrian CRS since Version 3.10 

### ISSUE THREAD

**Issue by Ralf1709** [qgis/QGIS#37469]
Hi,
I noticed that the coordinate transformation is not working since version 3.10 for the main austrian coordinatesystems (e.g. EPSG: 31252, 31255, 31282,....). In all previous versions it worked properly out of the box. I'm using QGIS for many years and everything worked fine - but with that issue I can't use all the good new tools with my old projects without converting my layers in an old QGIS version before. But this also not really applicable because I need my layers in that coordinate reference system because it is the system used by the authorities. 

Error message: No transform available between EPSG: 31282 and EPSG: 31252

**Comment by gioman** [comment]
@Ralf1709 

QGIS version?
Platform?
Sample project + data + steps to replicate?

**Comment by gioman** [comment]
Closing for lack of feedback.
