### ISSUE TITLE
Encoding error in project name when saving to gpkg

### ISSUE THREAD

**Issue by noenandre** [qgis/QGIS#37463]
**Describe the bug**
There is a encoding error when saving a Qgis project to a geopackage.  Qgis will garble up non ascii character in the projects name. The result is that Qgis is unable to reopen the project later - without correcting the name field in the qgis_projects table in some external program.

**How to Reproduce**

Create a new empty geopackage. Save the project to the empty geopackage with the name "Bjørg's große project".
Restart Qgis and try to reopen the project.
Open the gpkg file with eg. DB browser for sqlite or DBeaver. 
Expected bytes is 42 6a c3 b8 72 67 27 73 20 67 72 6f c3 9f 65 20 70 72 6f 6a 65 63 74
the actual sequence is 42 6a f8 72 67 27 73 20 67 72 6f df 65 20 70 72  6f 6a 65 63 74.

If you correct the name field in the qgis_projects table - the project will open just fine - even with non ascii characters.

**QGIS and OS versions**
Testet on Windows 10 with Qgis 3.10, 3.12 and 3.14.

**Comment by elpaso** [comment]
This works just fine on linux/master, it's probably a windows-only issue.
