### ISSUE TITLE
Label masking settings gets dropped when attribute contains a comma (updated)

### ISSUE THREAD

**Issue by klakar** [qgis/QGIS#37473]
**Describe the bug**

Established label masks work fine, but can get dropped without warning from time to time.

**How to Reproduce**
1. Create masked labels for point layer
2. Enable masking for line layer
3. Open layer properties dialogue for line layer. 
**Make sure it opens on a tab other than the masking tab,** 
4. and immediately press "Apply" in the dialogue.
5. All masking settings for the line layer will be dropped.

![Screenshot from 2020-06-29 09-02-58](https://user-images.githubusercontent.com/6375959/85984002-c52f8b00-b9e8-11ea-928a-a01a982fab7b.png)

The label mask settings will not be changed.

Re-applying the mask for the layer will fix the style, but this is really annoying especially for complex layers.

**QGIS and OS versions**

QGIS version | 3.14.0-Pi | QGIS code revision | 9f7028fd23
-- | -- | -- | --
Compiled against Qt | 5.12.8 | Running against Qt | 5.12.8
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.2 (Ubuntu 12.2-4) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Pop!_OS 20.04 LTS
Active python plugins | LmOpenData; layout_loader; Qgis2threejs; latlontools; MetaSearch; processing; db_manager

**Additional context**

Not sure if this is the only problem, but it was a repeatable way to induce the bug.

Thanks!

**Comment by haubourg** [comment]
cc @obrix Can you have a look here?

**Comment by obrix** [comment]
I can reproduce this bug. @troopa81 Could it also be linked to https://github.com/qgis/QGIS/pull/36366 ?

**Comment by troopa81** [comment]
> I can reproduce this bug on latest master. @troopa81 Could it also be linked to #36366 ?

Yes, I'm pretty sure this is because we apply the widget settings but they are empty because they are loaded when the tab is shown. I would say that we "just" need to not apply those settings if the widget haven't been initialized.

**Comment by klakar** [comment]
Re-tested on 3.18.1 and the problem is still present. (same system as initial bug report)

**Comment by klakar** [comment]
There has been an improvement for newly created styles and projects, where only a map update (pan, zoom) is required to reset the masks. In some older projects with masking this does not work as well. One issue is found when a project with masks is saved, closed and then opened again. This will remove some mask settings in the "masked" layer.
Creating a new simple line layer with mixed (simple) labels in 3.18 is not showing signs of this problem.
If the problem can be verified to be limited to the "refresh map to fix" issue and "new projects work fine", then I guess this issue can be closed.
If this is indeed the case, and old projects will remain a problem,  I have some projects to recreate to get masking to work...

Working test project included.
[masking_test.zip](https://github.com/qgis/QGIS/files/6284318/masking_test.zip)

**Comment by klakar** [comment]
I also created a small project with data from an old problematic project.

[masking_test_old_styles.zip](https://github.com/qgis/QGIS/files/6284460/masking_test_old_styles.zip)

It has a contour line layer with style categories that should have masks enabled for all parts.
There's also a label layer with masks activated, that should be used as masking layer for the lines.

Even if masks are enabled and the project re-saved. When closed and opened again the masking settings is gone.

**Comment by klakar** [comment]
I think I'm on to a possible identified problem.
If the value that the style is based on contains a "comma", then masking will be dropped when reopening a saved project.
In the "masking_test_old_styles.zip" file the styles that fail to keep the masking settings contains a comma in the attribute table.
If all commas are replaced with "nothing" and the table saved, then masking settings will work even when saved and reopened.

**Comment by roya0045** [comment]
@klakar Could you update the title, there is another ticket with possibly the same issue and I may be good to regroup them.

**Comment by klakar** [comment]
Yes, these that issue is the same as what is described as a remaining problem in this issue.
