### ISSUE TITLE
Marker fill random rotation bug

### ISSUE THREAD

**Issue by gunerphp** [qgis/QGIS#37476]
**Describe the bug**

When I want to set random rotation of markers in polygon fill i see over 50% of symbols are trimmed. 
![image](https://user-images.githubusercontent.com/43408711/85998235-d38e9e80-ba0a-11ea-9721-191849d4ee98.png)

**How to Reproduce**

1. Create new polygon on a polygon layer.
2. Go to Style properties.
3. Set the symbol type as: Fill: markers.
4. Set the marker as anything.
5. Set marker rotation parameter as `rand(0,360)` or something similar.
5. See the effect as on picture above.

**QGIS and OS versions**

Wersja QGIS
3.12.0-București
Rewizja QGIS
cd141490ec
Skompilowane z Qt
5.11.2
Uruchomione z Qt
5.11.2
Skompilowane z GDAL/OGR
3.0.4
Uruchomione z GDAL/OGR
3.0.4
Skompilowane z GEOS
3.8.0-CAPI-1.13.1
Uruchomione z GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
Wersja klienta PostgreSQL
11.5
Wersja SpatiaLite
4.3.0
Wersja QWT
6.1.3
Wersja QScintilla2
2.10.8
Skompilowane z PROJ
6.3.1
Uruchomione z PROJ
Rel. 6.3.1, February 10th, 2020
Wersja systemu operacyjnego
Windows 10 (10.0)
Aktywne wtyczki Pythona
BDOT10k_GML_SHP_Loader; 
changeDataSource; 
ClosestPoint; 
latlontools; 
networks; 
refFunctions; 
db_manager; 
MetaSearch; 
processing

**Comment by nirvn** [comment]
Fixed in 3.14.
