### ISSUE TITLE
QGIS 3.14 crashes when the command "iface.addVectorLayer" or "QgsProject.instance().addMapLayer" is issued in the Python console within QGIS

### ISSUE THREAD

**Issue by haytastan** [qgis/QGIS#37486]
**Describe the bug**

QGIS 3.14 crashes when the command "iface.addVectorLayer" or "QgsProject.instance().addMapLayer" is  issued in the Python console within QGIS
**How to Reproduce**

1. Go to 'the Python console within QGIS'
2. Issue the commands below:
from qgis.core import *
QgsApplication.setPrefixPath("C:/qgis", True)
qgs = QgsApplication([], False)
qgs.initQgis()
from qgis.core import QgsProject
project = QgsProject.instance()
print(project.fileName())
project.write()
import os 
from qgis.core import (QgsVectorLayer)
path_to_layer = os.path.join(QgsProject.instance().homePath(), "data", "vector", "iller", "iller.shp")
print(path_to_layer)
vlayer = QgsVectorLayer(path_to_layer, "Türkiye İlleri", "ogr")
print(vlayer)
project.instance().addMapLayer(vlayer, False)
4. See error -->
Crash ID: 2ec7a9b99f596106f530abffc629a6c5c6eb6938

Stack Trace

QgsStyleProxyModel::QgsStyleProxyModel qgsstylemodel.cpp:677
QgsStyleItemsListWidget::setStyle qgsstyleitemslistwidget.cpp:144
QgsSymbolsListWidget::QgsSymbolsListWidget qgssymbolslistwidget.cpp:42
QgsSymbolSelectorWidget::layerChanged qgssymbolselectordialog.cpp:533
QMetaObject::activate :
QItemSelectionModel::setCurrentIndex :
QAbstractItemView::setCurrentIndex :
QgsSymbolSelectorWidget::QgsSymbolSelectorWidget qgssymbolselectordialog.cpp:306
QgsSingleSymbolRendererWidget::QgsSingleSymbolRendererWidget qgssinglesymbolrendererwidget.cpp:59
QgsSingleSymbolRendererWidget::create qgssinglesymbolrendererwidget.cpp:32
QgsRendererPropertiesDialog::rendererChanged qgsrendererpropertiesdialog.cpp:251
QMetaObject::activate :
QWidgetLineControl::`default constructor closure' :
QComboBox::setCurrentIndex :
QComboBox::setCurrentIndex :
QgsRendererPropertiesDialog::syncToLayer qgsrendererpropertiesdialog.cpp:384
QgsRendererPropertiesDialog::QgsRendererPropertiesDialog qgsrendererpropertiesdialog.cpp:122
QgsLayerStylingWidget::updateCurrentWidgetLayer qgslayerstylingwidget.cpp:450
QMetaObject::activate :
QListWidgetItem::`default constructor closure' :
QMetaObject::activate :
QItemSelectionModel::setCurrentIndex :
QListWidget::setCurrentRow :
QgsLayerStylingWidget::setLayer qgslayerstylingwidget.cpp:275
QMetaObject::activate :
QgsMapLayerComboBox::layerChanged moc_qgsmaplayercombobox.cpp:209
QMetaObject::activate :
QAbstractItemModel::endInsertRows :
QSortFilterProxyModel::insertRows :
QSortFilterProxyModel::sortRole :
QSortFilterProxyModel::`default constructor closure' :
QMetaObject::activate :
QAbstractItemModel::endInsertRows :
QgsMapLayerModel::addLayers qgsmaplayermodel.cpp:182
QMetaObject::activate :
QgsProject::layersAdded moc_qgsproject.cpp:1196
QMetaObject::activate :
QgsMapLayerStore::layersAdded moc_qgsmaplayerstore.cpp:314
QgsMapLayerStore::addMapLayers qgsmaplayerstore.cpp:99
QgsProject::addMapLayers qgsproject.cpp:3257
QgisApp::addVectorLayerPrivate qgisapp.cpp:12417
QgisApp::addSelectedVectorLayer qgisapp.cpp:6221
QgisAppInterface::addVectorLayer qgisappinterface.cpp:141
meth_QgisInterface_addVectorLayer sip_guipart5.cpp:360928
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyImport_Import :
PyImport_Import :
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_sip :
PyInit_Qsci :
QWidget::event :
QFrame::event :
QAbstractScrollArea::event :
PyInit_Qsci :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:437
sipQgsApplication::notify sip_corepart5.cpp:233801
QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:437
sipQgsApplication::notify sip_corepart5.cpp:233801
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processKeyEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1618
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.14.0-Pi
QGIS code revision: 9f7028fd23
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**QGIS and OS versions**
QGIS Version: 3.14.0-Pi
QGIS code revision: 9f7028fd23

**Additional context**

**Comment by nyalldawson** [comment]
> qgs = QgsApplication([], False)
> qgs.initQgis()

This is wrong -- you definitely should NEVER construct a new QgsApplication from WITHIN QGIS. This step is only required for standalone applications.
