### ISSUE TITLE
Minimum bounding geometry : amazing values in calculated fields

### ISSUE THREAD

**Issue by rbonnefoi** [qgis/QGIS#37483]
Hi all,

I just discovered the "minimum bounding geometry" feature in QGis. As I was trying it on a very simple handmade example, I noticed amazing values in the calculated fields (height, width, area, perimeter) of the minimum bounding geometry layer (whether I use minimum oriented rectangle or minimum enclosing circle).

From a relative point of view, all the values are linked. I mean if I check the area field with the calculation height*width or the perimeter with 2*(height+width), the results match.

But it uses an unknown unit, far from what I can get with the measuring tool.

You'll find enclosed my dumb polygons layer I use for test, and the resulting oriented bbox, with two fields added : the actual areas et perimeters calculated directly from the geometry (`$area` and `$perimeter`).

I used the default EPSG:4326 project projection.

[layers.zip](https://github.com/qgis/QGIS/files/4846840/layers.zip)

**Comment by uclaros** [comment]
WGS84 (EPSG:4326) is a geographic CRS and the values you mention are correctly calculated by the algorithm in decimal degrees.

**Comment by gioman** [comment]
> WGS84 (EPSG:4326) is a geographic CRS and the values you mention are correctly calculated by the algorithm in decimal degrees.

This seems to be the reason for the "weird" values you see. Use a projected CRS and they should be ok.

**Comment by rbonnefoi** [comment]
Ok thanks Giovanni and uclaros for your answers. I should have checked with another projection. I thought the EPSG;4326 projection would give me values in meter units, but actually not.

I just checked in the French EPSG:2154 projection, everything is OK.

Sorry for the fake bug post, I should have investigated a bit deeper.

Thanks for the help.
Le 29/06/2020 23:54:01, Giovanni Manghi <notifications@github.com> a écrit :
Closed #37483 [https://github.com/qgis/QGIS/issues/37483].
