### ISSUE TITLE
Apply default value on update ot working in Attributes Form

### ISSUE THREAD

**Issue by ghtmtt** [qgis/QGIS#37497]
**Describe the bug**

The `Apply default value on update` checkbox in the Attributes Form is not updating other features when checked. When the checkbox is checked all the values should be updated with the default value set.

**How to Reproduce**

I've prepared a simple project with a raster and a point vector layer. The point layer has the field `elev` and for all the 3 features the values are NULL.

The default expression to fill the `elev` field is taken directly from the raster: `raster_value('clipped', 1, $geometry)`:

![image](https://user-images.githubusercontent.com/2884884/86095724-a269a900-bab2-11ea-9727-da868bdce74a.png)

When adding a new point the `elev` field is correctly filled with the raster value, but the other points remain empty:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/2884884/86096043-10ae6b80-bab3-11ea-90f2-71b1bc78f7b4.gif)

Project in attach [bug.zip](https://github.com/qgis/QGIS/files/4850073/bug.zip)

**QGIS and OS versions**

Linux Debian SID with QGIS 3.15

**Comment by andreasneumann** [comment]
@ghtmtt - this is not how the "Apply default value on update" works.

It applies only if you edit a _specific_ feature. All the other features are not affected. It is like with SQL: if you have an "on update" trigger it only applies to records you actually update. I think the current behavior makes sense.

If you want to do what you want, you can still use the field calculator.

**Comment by andreasneumann** [comment]
In my opinion this is not a bug. It is just a "misunderstanding" how the "Apply default value on update" works.

We should close this issue.

**Comment by andreasneumann** [comment]
If you are in Multi-edit mode and you update several features at once, then it would of course apply to all features being edited, but not all of the features in the table.

**Comment by ghtmtt** [comment]
@andreasneumann got it, I misunderstood the behavior of the option. Thanks for the explanation!
