### ISSUE TITLE
Large geopackage freezes QGIS 3.10.x on Win10 when closing project

### ISSUE THREAD

**Issue by geistiii** [qgis/QGIS#37507]
Bug description:

Qgis 3.10.x freezes upon closing a project containing huge (1.5 GB +) geopackages. It is possible to open new instances of Qgis and work in those, it is not possible to terminate the frozen window via the task manager. This does happen under Windows 10, but not under Windows 7.

Reproduction:

I cannot provide a light sample, since the culprit dataset is about 1.5 GB large and the projects contain interal data. The geopackage was created by downloading the full extent of the following WFS: [ALKIS data Brandenburg - Germany](https://inspire.brandenburg.de/services/cp_alkis_wfs?SERVICE=WFS&REQUEST=GetCapabilities).

The combination of the large geopackage and other parts of the projects seem to be the problem. Project-versions without the geopackage don't cause freezing.

The issue can be reproduced using a different profile.

The issue seems to be connected to enabled "snapping" and/or "automatic tracing". If "tracing" is turned off, the issue does not (always) occur.

Qgis Version:
3.10.x

OS Version:
Windows 10 Pro Version 1909

**Comment by gioman** [comment]
@geistiii could you test with a new QGIS profile?

**Comment by geistiii** [comment]
> @geistiii could you test with a new QGIS profile?

Did so, the issue persists.

I also did some further testing, there seems to be a connection to "snapping" and especially "automatic tracing". I'll update the issue accordingly.

**Comment by gioman** [comment]
> I also did some further testing, there seems to be a connection to "snapping" and especially "automatic tracing". I'll update the issue accordingly.

@geistiii interesting. It would be very good if you could share a project where there are saved the offending configurations. The dataset as is so large cannot be attached, but it can be linked using a service like dropbox/google drive /etc.
