### ISSUE TITLE
Adding child features with geometry to related table hides the app window when the table of attributes is docked

### ISSUE THREAD

**Issue by Dkrav-UA** [qgis/QGIS#37501]
**Describe the bug**

In a project, we have 2 related tables (1-to-many). Adding child features with geometry to the related table hides the main window. The process still running in the background. If child objects are added from an "Add Feature Form" everything is ok.

**How to Reproduce**

1. Create / Open ([relation_memory.zip](https://github.com/qgis/QGIS/files/4850115/relation_memory.zip)) project with related tables. 
2. Enable "Show Form on Add Feature" option.
3. Add feature to the main table.
4. Add child features thru the "Feature attributes" window
![Add_Feature_attributes](https://user-images.githubusercontent.com/16414895/86098016-368d3d80-babe-11ea-802c-9da5b5997f60.jpg)
5. Everything works as predicted.
![ok](https://user-images.githubusercontent.com/16414895/86098215-7a804280-babe-11ea-9843-603478af5144.jpg)
6. Select feature from the main table.
7. Open Attributes Table in form view.
8. Add child feature.
![add_from_table](https://user-images.githubusercontent.com/16414895/86098617-0d20e180-babf-11ea-9e18-ff0b826f449a.jpg)
9. QGIS Window disappears.

**QGIS and OS versions**

QGIS version | 3.14.0-Pi | QGIS code revision | 9f7028fd23
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 7 SP 1 (6.1)
Active python plugins | db_manager

Ubuntu 18.04

**Additional context**

**Comment by gioman** [comment]
> QGIS Window disappears.

@Dkrav-UA confirmed, this happens **only** when the table of attributes is docked: when is undocked what it disappears is the form dialog, this is because the user is guided to draw the geometry in the map. When this TA is docked this should not happen, as the whole QGIS main window... disappear.

**Comment by Dkrav-UA** [comment]
3.14.1 - not fixed. :(

**Comment by Pedro-Murteira** [comment]
Still valid on QGIS 3.22.4 and 3.24.0.

**Comment by alexbruy** [comment]
Not reproducible with the latest master (e5e6a13671) on LInux.
