### ISSUE TITLE
Crash when verifying topology

### ISSUE THREAD

**Issue by REIMSMetropole** [qgis/QGIS#37509]
Hi, 
I was verifying topology on polygons. I suspect null geom, but couldn't identify them. 
The gpkg is written. 
Everytime I retried to launch the topology verification on my filtered postgis table, same result : it crashes.
Don't know what else to say.

Thks in advance.

## Report Details

**Crash ID**: [19567d1b7c1e0142727fbaa67451004a561a4f79](https://github.com/qgis/QGIS/search?q=19567d1b7c1e0142727fbaa67451004a561a4f79&type=Issues)

**Stack Trace**
<pre>
QgsGeometryCollection::vertexAt qgsgeometrycollection.cpp:813
QgsAbstractGeometry::centroid qgsabstractgeometry.cpp:181
QgsGeometryDuplicateCheck::collectErrors qgsgeometryduplicatecheck.cpp:85
QgsGeometryChecker::runCheck qgsgeometrychecker.cpp:288
QtConcurrent::MapKernel<QList<QgsGeometryCheck * __ptr64>::iterator,QgsGeometryChecker::RunCheckWrapper>::runIteration qtconcurrentmapkernel.h:69
QtConcurrent::MapKernel<QList<QgsFeature>::iterator,QgsGeometrySnapper::ProcessFeatureWrapper>::runIterations qtconcurrentmapkernel.h:78
QtConcurrent::IterateKernel<QList<QgsGeometryCheck * __ptr64>::iterator,void>::forThreadFunction qtconcurrentiteratekernel.h:256
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.6-A Coru�a
QGIS code revision: ec80021f49
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by gioman** [comment]
@REIMSMetropole please attach the datasets and describe the **exact** steps and parameters you are using.

**Comment by REIMSMetropole** [comment]
Open the table
vector > verifier les geom
set the param as I do

[dump_prescription.zip](https://github.com/qgis/QGIS/files/4852764/dump_prescription.zip)


Param : 
![image](https://user-images.githubusercontent.com/5716587/86143439-b7ffc280-baf4-11ea-9fcd-3a68a95363d7.png)

**Comment by gioman** [comment]
@REIMSMetropole I can't cleanly restore your dump:

```
gio=# \i dump_prescription.sql  
CREATE TABLE
CREATE INDEX
psql:dump_prescription.sql:31: ERROR:  invalid byte sequence for encoding "UTF8": 0xe9 0x6c 0x69
psql:dump_prescription.sql:34: ERROR:  invalid byte sequence for encoding "UTF8": 0xe9 0x20 0x63
psql:dump_prescription.sql:37: ERROR:  invalid byte sequence for encoding "UTF8": 0xe9 0x6c 0x69
psql:dump_prescription.sql:40: ERROR:  Geometry SRID (0) does not match column SRID (2154)
psql:dump_prescription.sql:43: ERROR:  Geometry SRID (0) does not match column SRID (2154)
psql:dump_prescription.sql:46: ERROR:  invalid byte sequence for encoding "UTF8": 0xe9 0x20 0x63
psql:dump_prescription.sql:49: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64
psql:dump_prescription.sql:52: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64
psql:dump_prescription.sql:55: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64
psql:dump_prescription.sql:58: ERROR:  invalid byte sequence for encoding "UTF8": 0xe9 0x20 0x63
psql:dump_prescription.sql:61: ERROR:  invalid byte sequence for encoding "UTF8": 0xe9 0x20 0x63
psql:dump_prescription.sql:64: ERROR:  invalid byte sequence for encoding "UTF8": 0xe9 0x20 0x63
psql:dump_prescription.sql:67: ERROR:  invalid byte sequence for encoding "UTF8": 0xe9 0x20 0x63
psql:dump_prescription.sql:70: ERROR:  invalid byte sequence for encoding "UTF8": 0xe9 0x20 0x63
psql:dump_prescription.sql:73: ERROR:  invalid byte sequence for encoding "UTF8": 0xe9 0x20 0x63
psql:dump_prescription.sql:76: ERROR:  invalid byte sequence for encoding "UTF8": 0xe9 0x20 0x63
psql:dump_prescription.sql:79: ERROR:  invalid byte sequence for encoding "UTF8": 0xe9 0x20 0x63
psql:dump_prescription.sql:82: ERROR:  invalid byte sequence for encoding "UTF8": 0xe9 0x20 0x63
psql:dump_prescription.sql:85: ERROR:  Geometry SRID (0) does not match column SRID (2154)
psql:dump_prescription.sql:88: ERROR:  invalid byte sequence for encoding "UTF8": 0xe9 0x20 0x63
psql:dump_prescription.sql:91: ERROR:  invalid byte sequence for encoding "UTF8": 0xe9 0x20 0x63
psql:dump_prescription.sql:94: ERROR:  invalid byte sequence for encoding "UTF8": 0xe9 0x20 0x63
psql:dump_prescription.sql:97: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64
psql:dump_prescription.sql:100: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64
psql:dump_prescription.sql:103: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64
psql:dump_prescription.sql:106: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64
psql:dump_prescription.sql:109: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64
psql:dump_prescription.sql:112: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64
psql:dump_prescription.sql:115: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64
psql:dump_prescription.sql:118: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64
psql:dump_prescription.sql:121: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64
psql:dump_prescription.sql:124: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64
psql:dump_prescription.sql:127: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64
psql:dump_prescription.sql:130: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64
psql:dump_prescription.sql:133: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64
psql:dump_prescription.sql:136: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64
psql:dump_prescription.sql:139: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64
psql:dump_prescription.sql:142: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64
psql:dump_prescription.sql:145: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64
psql:dump_prescription.sql:148: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64
psql:dump_prescription.sql:151: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64
psql:dump_prescription.sql:154: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64
psql:dump_prescription.sql:157: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64
psql:dump_prescription.sql:160: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64
psql:dump_prescription.sql:163: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64
psql:dump_prescription.sql:166: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64
psql:dump_prescription.sql:169: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64
psql:dump_prescription.sql:172: ERROR:  Geometry SRID (0) does not match column SRID (2154)
psql:dump_prescription.sql:175: ERROR:  Geometry SRID (0) does not match column SRID (2154)
psql:dump_prescription.sql:178: ERROR:  Geometry SRID (0) does not match column SRID (2154)
```

**Comment by REIMSMetropole** [comment]
Hi.

It’s not a dump, it’s a sql script. Does it work with psql ?


De : Giovanni Manghi [mailto:notifications@github.com]
Envoyé : mardi 30 juin 2020 17:41
À : qgis/QGIS
Cc : MUCKENSTURM Pierre; Mention
Objet : Re: [qgis/QGIS] Crash when verifying topology (#37509)


@REIMSMetropole<https://github.com/REIMSMetropole> I can't cleanly restore your dump:

gio=# \i dump_prescription.sql

CREATE TABLE

CREATE INDEX

psql:dump_prescription.sql:31: ERROR:  invalid byte sequence for encoding "UTF8": 0xe9 0x6c 0x69

psql:dump_prescription.sql:34: ERROR:  invalid byte sequence for encoding "UTF8": 0xe9 0x20 0x63

psql:dump_prescription.sql:37: ERROR:  invalid byte sequence for encoding "UTF8": 0xe9 0x6c 0x69

psql:dump_prescription.sql:40: ERROR:  Geometry SRID (0) does not match column SRID (2154)

psql:dump_prescription.sql:43: ERROR:  Geometry SRID (0) does not match column SRID (2154)

psql:dump_prescription.sql:46: ERROR:  invalid byte sequence for encoding "UTF8": 0xe9 0x20 0x63

psql:dump_prescription.sql:49: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64

psql:dump_prescription.sql:52: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64

psql:dump_prescription.sql:55: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64

psql:dump_prescription.sql:58: ERROR:  invalid byte sequence for encoding "UTF8": 0xe9 0x20 0x63

psql:dump_prescription.sql:61: ERROR:  invalid byte sequence for encoding "UTF8": 0xe9 0x20 0x63

psql:dump_prescription.sql:64: ERROR:  invalid byte sequence for encoding "UTF8": 0xe9 0x20 0x63

psql:dump_prescription.sql:67: ERROR:  invalid byte sequence for encoding "UTF8": 0xe9 0x20 0x63

psql:dump_prescription.sql:70: ERROR:  invalid byte sequence for encoding "UTF8": 0xe9 0x20 0x63

psql:dump_prescription.sql:73: ERROR:  invalid byte sequence for encoding "UTF8": 0xe9 0x20 0x63

psql:dump_prescription.sql:76: ERROR:  invalid byte sequence for encoding "UTF8": 0xe9 0x20 0x63

psql:dump_prescription.sql:79: ERROR:  invalid byte sequence for encoding "UTF8": 0xe9 0x20 0x63

psql:dump_prescription.sql:82: ERROR:  invalid byte sequence for encoding "UTF8": 0xe9 0x20 0x63

psql:dump_prescription.sql:85: ERROR:  Geometry SRID (0) does not match column SRID (2154)

psql:dump_prescription.sql:88: ERROR:  invalid byte sequence for encoding "UTF8": 0xe9 0x20 0x63

psql:dump_prescription.sql:91: ERROR:  invalid byte sequence for encoding "UTF8": 0xe9 0x20 0x63

psql:dump_prescription.sql:94: ERROR:  invalid byte sequence for encoding "UTF8": 0xe9 0x20 0x63

psql:dump_prescription.sql:97: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64

psql:dump_prescription.sql:100: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64

psql:dump_prescription.sql:103: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64

psql:dump_prescription.sql:106: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64

psql:dump_prescription.sql:109: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64

psql:dump_prescription.sql:112: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64

psql:dump_prescription.sql:115: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64

psql:dump_prescription.sql:118: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64

psql:dump_prescription.sql:121: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64

psql:dump_prescription.sql:124: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64

psql:dump_prescription.sql:127: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64

psql:dump_prescription.sql:130: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64

psql:dump_prescription.sql:133: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64

psql:dump_prescription.sql:136: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64

psql:dump_prescription.sql:139: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64

psql:dump_prescription.sql:142: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64

psql:dump_prescription.sql:145: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64

psql:dump_prescription.sql:148: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64

psql:dump_prescription.sql:151: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64

psql:dump_prescription.sql:154: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64

psql:dump_prescription.sql:157: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64

psql:dump_prescription.sql:160: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64

psql:dump_prescription.sql:163: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64

psql:dump_prescription.sql:166: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64

psql:dump_prescription.sql:169: ERROR:  invalid byte sequence for encoding "UTF8": 0xe0 0x20 0x64

psql:dump_prescription.sql:172: ERROR:  Geometry SRID (0) does not match column SRID (2154)

psql:dump_prescription.sql:175: ERROR:  Geometry SRID (0) does not match column SRID (2154)

psql:dump_prescription.sql:178: ERROR:  Geometry SRID (0) does not match column SRID (2154)

**Comment by gioman** [comment]
> Does it work with psql ?

@REIMSMetropole no, the errors are the ones reported above.

**Comment by REIMSMetropole** [comment]
The user just deleted the datas in the database. I can’t make another dump. 



De : Giovanni Manghi [mailto:notifications@github.com] 
Envoyé : mercredi 1 juillet 2020 10:02
À : qgis/QGIS
Cc : MUCKENSTURM Pierre; Mention
Objet : Re: [qgis/QGIS] Crash when verifying topology (#37509)

Does it work with psql ?
@REIMSMetropole no, the errors are the ones reported above.

**Comment by gioman** [comment]
> The user just deleted the datas in the database. I can’t make another dump.

@REIMSMetropole can you replicate the issue with another dataset?

**Comment by uclaros** [comment]
I repaired you script with proper `st_geomfromtext` for the WKTs and imported successfully.
[dump_prescription_fixed.zip](https://github.com/qgis/QGIS/files/4856736/dump_prescription_fixed.zip)
I cannot replicate the crash on a couple of weeks old master on Debian.

Judging from the stack trace, and the fact that you have a couple of null geometries, it could be a solved issue with recent GEOS and empty geometry collections. Upgrading to the latest version should solve it.

**Comment by gioman** [comment]
Closing for lack of feedback.
