### ISSUE TITLE
Items in a Print Layout eventually cannot be selected or moved with the 'Select/Move Items' tool

### ISSUE THREAD

**Issue by gvellut** [qgis/QGIS#37506]
While switching between items in a Print Layout with the 'Select/Move Items' tool, eventually they cannot be selected or moved.

Here is a GIF of what happens (it is not super clear in the video but, starting from the north arrow, I click on the item and try to move it, but nothing happens then the same for the scalebar; sometimes I can select but cannot move ; It is not shown on this video but  it also happens with the map not just the other decorations). The time to bug varies unfortunately: it is not just the second selected item like in the video but sometimes it works for longer until this issue arises.

![ezgif-3-47e7ce869bc6](https://user-images.githubusercontent.com/3685/86118677-77428200-bad1-11ea-9cec-c9bd970fe937.gif)

To correct the issue, I have to close the layout then reopen it.

**How to Reproduce**

1. Create a new layout
2. Put a map, a north arrow and a scalebar
3. With the Select/Move Items tool, select one of the items and move it then do the same for the other and keep doing that...
4. At some point, you won't be able to select an item and move it

**QGIS and OS versions**

I am on QGIS 3.14 on macOS 10.14

QGIS version | 3.14.0-Pi | QGIS code revision | 9f7028fd23
-- | -- | -- | --
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.28.0 | Running against SQLite | 3.28.0
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS Mojave (10.14)
Active python plugins | FreehandRasterGeoreferencer; firstaid; profiletool; quick_map_services; QGIS3-getWKT; QuickWKT; qgis-maptiler-plugin; plugin_reloader; valuetool; processing; db_manager; MetaSearch; CustomToolBar

**Comment by techdude1996** [comment]
I also have this issue with 3.14 on Windows 10.

**Comment by Pedro-Murteira** [comment]
@gvellut Hello, I've tested this issue using QGIS 3.22.3 on Windows 10/macOS Monterey 12.1, and I can't reproduce it. Did you come across this issue in more recent versions?

**Comment by gvellut** [comment]
I use QGIS 3.18 on Windows 10 these days. It doesn't seem it still happens (or I haven't noticed at least). I will test on macOS and with the latest QGIS version some time this week.

**Comment by wdossett** [comment]
I just ran into this same problem in QGIS 3.44.7 running on Windows. I had a print layout, copied it to create a new version, changed the layout to landscape, and could not move the items around the layout. I could resize them, but not move them.
