### ISSUE TITLE
the keybord shortcut CTRL+C copy only the first cell, not the whole line

### ISSUE THREAD

**Issue by cartoinddigo** [qgis/QGIS#37503]
Hi there,
On the Attribute table, the keybord shortcut CTRL+C copy only the first cell, not the whole line.
It's works fine when using the button.
QGIS 3.14.0-Pi 64bit - release 9f7028fd23
thank's
Thomas.

**Comment by MMR100** [comment]
It is similar to issue #37401

**Comment by cartoinddigo** [comment]
@MMR100 : Almost the same, but this issues concern the attribute table. Copying from the map canva work fine for me, but not from the attribute table (ie to past in Excel or text éditor)

PS : thanks to @gioman for labelling an titling :-)
