### ISSUE TITLE
Mishandling Grib Data Values

### ISSUE THREAD

**Issue by eflowbeach** [qgis/QGIS#37504]
It appears that the grib decoder is failing on these grib2 type of files (attached). Everything appears normal when adding the layer except the data range is -3 to -3.  It should be a fairly broad range for this file like -3 to 700. The histogram also reports a singular spike at -3. I hope that helps! This would be a very useful feature to have working. 

[MRMS_RadarOnly_QPE_72H.latest.grib2.gz](https://github.com/qgis/QGIS/files/4850462/MRMS_RadarOnly_QPE_72H.latest.grib2.gz)

**Comment by PeterPetrik** [comment]
- if loaded as raster (GDAL) it shows range -3 to 211.
- if checked with mdalinfo it shows correct -3 to 775.2
```
\peter@pp-mb:~/Projects/qgis3/build-MDAL/tools$ ./mdalinfo ~/Downloads/MRMS_RadarOnly_QPE_72H.latest.grib2 --stats
mdalinfo 0.8.0
Mesh File: /Users/peter/Downloads/MRMS_RadarOnly_QPE_72H.latest.grib2
Mesh loaded: OK
  Driver: GRIB
  Vertex count: 24500000
  Edge count: 0
  Face count: 24489501
  Edge count: 0
  Projection: GEOGCS["Coordinate System imported from GRIB file",DATUM["unnamed",SPHEROID["Spheroid imported from GRIB file",6378160,298.253916296469]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AXIS["Latitude",NORTH],AXIS["Longitude",EAST]]
Datasets loaded: OK
  Groups count: 1
  Radar Precipitation Accumulation 72-hour [mm]
    driver:        GRIB
    dataset count: 1
    defined on:    vertices
    min:           -3
    max:           775.2
```
- if loaded with qgis 3.16 (ltr to be) it shows ok
<img width="719" alt="Screen Shot 2021-02-03 at 15 51 58" src="https://user-images.githubusercontent.com/804608/106764155-d05e2f80-6637-11eb-9fa2-3f5499d79ba2.png">
