### ISSUE TITLE
Feature request: Native Qrcode

### ISSUE THREAD

**Issue by alexmodesto73** [qgis/QGIS#37511]
Rather than using external urls to generate QRCODEs

Couldn't Qgis do it natively?
This would allow cards to be scanned directly from applications such as: ODK, Qfield

**Comment by Gustry** [comment]
FYI : https://github.com/qgis/QGIS/issues/28997

**Comment by alexbruy** [comment]
Probably should be closed as won'tfix as previous ticket.

**Comment by Gustry** [comment]
There is now a plugin to print qr code : https://plugins.qgis.org/plugins/qrbarcodeitem/
