### ISSUE TITLE
Style raster with discrete values

### ISSUE THREAD

**Issue by s5joschi** [qgis/QGIS#37515]
**Feature description.**
The feature allows to color a raster based on discrete values (e.g. land-use categories) rather then with a continous scale. This could be most easily implemented in -> _Properties_ ->  _Style_  -> Paletted. 
The user should be allowed to insert custom values and then attribute them with a given color. 
e.g. 

0 -> Red
1 -> Blue
2 -> Green

**Additional context**
This feature has been already asked for [here](https://gis.stackexchange.com/questions/194116/styling-discrete-raster-using-qgis) and also shortcomings of the workaround from the first answer in this threat have been raised (Quote: _" But I don't find it very intuitive, mostly when I teach Qgis to new users. Moreover, if I have a value "6" that I don't want to display on my raster, I have a problem: all pixels with "6" will bet a color interpolated between "5" and "7". I can of course say that "6" should be considered as NoData or I can can use the raster calculator to create a new raster without "6" but, again, those are all workarounds. Ideally, I would wish a button "Retrieve all single values". I'll check if it's planned for future versions."_ 

Extra Info: Once a datasource already provides a color palette it is easy to manipulate and change the colors. So the implementation of this feature should be technically very straight forward and eady to achieve.

**Comment by uclaros** [comment]
What is missing from the current implementation of *Paletted/Unique values* render type?

**Comment by s5joschi** [comment]
Ok. I'm still using QGIS 2.14 on Ubuntu. I think this feature was already impelemented in more recent versions. I'll have to update my QGIS version.
