### ISSUE TITLE
Rasters only GPKG will not open in QGIS 3.14

### ISSUE THREAD

**Issue by klakar** [qgis/QGIS#37519]
**Describe the bug**
When using GPKG with more than one rasterlayer QGIS 3.14 will show an error.

![VirtualBox_win10_01_07_2020_12_34_52](https://user-images.githubusercontent.com/6375959/86246825-edb3b280-bbab-11ea-877f-d74dabccce3a.png)

The error also appears if it is a completely empty GPKG.

![Skärmbild från 2020-07-01 14-48-26](https://user-images.githubusercontent.com/6375959/86247186-661a7380-bbac-11ea-8988-29cd3990bf5a.png)

A GPKG with a single raster layer is OK, as is any GPKG including at least one table or vector layer.

**How to Reproduce**

1. Create a new geopackage with an empty table.
2. Remove the empty table from the GPKG in the Browser
3. Refresh the Browser

Alternatively
1. Export rasterlayer to GeoPackage
2. Export second raster as new layer in the GeoPackage
3. Alternatively drag and drop a raster in the GeoPackage in the Browser.
4. Refresh the Browser

Or get this package from GitHub:
https://github.com/klakar/geosupportsystem/blob/master/raster_test2.gpkg

**Workaround**

1. Right click "broken" GeoPackage in Browser
2. Select "Create New Layer or a Table"
3. Add empty table without geometry.
4. Refresh Browser

**QGIS and OS versions**

Tested on Windows10, MacOS 10.14, Linux

QGIS version | 3.14.0-Pi | QGIS code revision | 9f7028fd23
-- | -- | -- | --
Compiled against Qt | 5.12.8 | Running against Qt | 5.12.8
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.2 (Ubuntu 12.2-4) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Ubuntu 20.04 LTS
Active python plugins | processing; MetaSearch; db_manager

**Additional context**

Not sure if this helps, but here's a Twitter link to a conversation about the issue.
https://twitter.com/klaskarlsson/status/1278315954892689408

**Comment by gioman** [comment]
@klakar did it worked as expected in previous releases?

**Comment by elpaso** [comment]
This was introduced by me with: https://github.com/qgis/QGIS/pull/37018

Working on it.
