### ISSUE TITLE
Won't launch

### ISSUE THREAD

**Issue by gummo0** [qgis/QGIS#37514]
I can't even launch the software. I get this warning:

_**QGIS3.14.app can't be opened because Apple cannot check it for malicious software. This software needs to be updated. Contact the developer for more information.**_

I'm running Mac OS Catalina 10.15.5. I even tried QGIS3.10 with the same result.

**Comment by Gustry** [comment]
Solution is here https://github.com/qgis/QGIS/issues/34018#issuecomment-578186707
Many duplicates : https://github.com/qgis/QGIS/search?q=Apple+cannot+check+it+for+malicious+software&type=Issues
