### ISSUE TITLE
Raster calculator formula ignored if used within a model

### ISSUE THREAD

**Issue by andremano** [qgis/QGIS#37513]
See comment: https://github.com/qgis/QGIS/issues/37513#issuecomment-652321865

#######

This issue occurs with **GDAL Raster calculator** and with **GRASS r.mapcalc.simple**. Might be an issue also with other raster calculators but I did not test those.

If you perform an operation with those calculators i.g. A+B, the results are correct if they are used as a single tool, called from the Processing toolbox, but if the same operation is done as part of a workflow of a model the results are wrong.

**How to Reproduce**

1. Open [this project ](https://drive.google.com/file/d/1-pKSrJpmgrujOSj2bsZ9pwhzkHc3BmUy/view?usp=sharing)and import the model _'interactive raster calculator'_
2. From the Processing Toolbox use of the mentioned calculators and try the expression (A * 1) + (B * 1)
3. Use the _'interactive raster calculator'_ model to produce the equivalent expression (defined as `( @raster1 * @multiplicationfactor1 )+( @raster2 * @multiplicationfactor2 )`
4. You should see that both the output _final_ and the output _final_grass_ are the same but different from what you obtained in _step 2_ which is the correct result

**QGIS and OS versions**

QGIS version
3.12.3-București (**also occurs in the LTR**)
QGIS code revision
8234261527
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
csv_tools; 
DataPlotly; 
lizmap; 
pluginbuilder3; 
QNEAT3; 
quick_map_services; 
scriptrunner3; 
valuetool; 
db_manager; 
MetaSearch; 
processing

**Comment by gioman** [comment]
@andremano the issue does not lies in the raster calc tools being used, but rather in the modeller.

In fact from the logs is easy to see that (for example for the GDAL raster calc tool) if an expression is used to define the formula the raster calc has to use, then in reality the formula used is "A*2" that is just the "placeholder" formula for the specific tool.

**Comment by gioman** [comment]
It seems to me that the expression

( @raster1 * @multiplicationfactor1 )+( @raster2 * @multiplicationfactor2 )

using the option "pre-calculated" value, is just simply ignored. In fact if the expression is left empty and the model is run, then it still will go through and the placeholder formula A*2 used.

**Comment by gioman** [comment]
@alexbruy @nyalldawson are we expecting something that is not supposed to work anyway, or is really just a bug?

**Comment by PedroVenancio** [comment]
@andremano 

To make the idea behind your model work in the meanwhile, consider this model:

[Sum_with_Factors.zip](https://github.com/qgis/QGIS/files/4857316/Sum_with_Factors.zip)

**Comment by PedroVenancio** [comment]
> 
> 
> It seems to me that the expression
> 
> ( @raster1 * @multiplicationfactor1 )+( @raster2 * @multiplicationfactor2 )
> 
> using the option "pre-calculated" value, is just simply ignored. In fact if the expression is left empty and the model is run, then it still will go through and the placeholder formula A*2 used.

Yes, it seems that using any other option in Formula field, except "Value", leads to the use of default algorithm formula.

**Comment by luipir** [comment]
> It seems to me that the expression
> 
> ( @raster1 * @multiplicationfactor1 )+( @raster2 * @multiplicationfactor2 )
> 
> using the option "pre-calculated" value, is just simply ignored. In fact if the expression is left empty and the model is run, then it still will go through and the placeholder formula A*2 used.

wrong fomula... fomula is a string with reference to GUI variabls (A, B, etc) not an expression... rsult of the expression is NULL

a correct use of the fomula should be:

'( A * ' || to_string(@multiplicationfactor1) || ')+( B * ' || to_string(@multiplicationfactor2) || ')'

**Comment by luipir** [comment]
with processing mixing gdal you have to "think different" ;)

**Comment by PedroVenancio** [comment]
Perfect @luipir ! 

Is this documented anywhere? Definitively, not trivial without documentation.

**Comment by gioman** [comment]
> Is this documented anywhere?

@PedroVenancio @andremano if now we should open a ticket against QGIS docs, and even better propose a PR with the necessary explanation.

**Comment by andremano** [comment]
Thank you everyone, thank you @luipir (I would never got there on my own...)

**Comment by luipir** [comment]
> Thank you everyone, thank you @luipir (I would never got there on my own...)

well... a better documentation would be fine, feel free to do a Pull request! a automatic workaround to the lack of documentation could be a kind of placeholder or type hint to each QgsProcessingParameter* type to explicit the nature of the input admitted  type.
Should be simple feature to add. If you (someone in this issue) do a feature request I can evaluate the amount of work or oepning discussion with other core dev and UX contributors if it's feasible.

The generic problem is that it's impossible to have all documented due to the nature of processing (front-end for dynamic back-ends)... a self explaining input field could solve/facilitate past and future lack of documentation.

**Comment by andremano** [comment]
I opened a feature request. Not sure if I am pinning it correclty though... [#37575  ](https://github.com/qgis/QGIS/issues/37575)
