### ISSUE TITLE
[3.10.7] Layer dependencies configuration is not persistent

### ISSUE THREAD

**Issue by SebastienPeillet** [qgis/QGIS#37522]
**Describe the bug**

It is possible to configure layer dependencies in the vector layer properties window, but this configuration is erased if the user open again the vector layer properties window and validate it without re-checking the dependency checkboxes.

Specific to QGIS 3.10, as it seems that the bug no longer exists in 3.14 : the section gui/vector has been re-writed from apps by @manisandro [here](https://github.com/qgis/QGIS/pull/33833) and the bug has been probably fixed by @3nids [here](https://github.com/qgis/QGIS/pull/37000) (not sure but it is the last PR to apply significant changes on the dependencies configuration).

The question is : Will there be backport from the changes enunciated above (I guess not, because @manisandro work is flagged as a feature) or is it necessary to apply another fix for 3.10 version ?

**How to Reproduce**

1. Add 2 vector layers in qgis
2. Open the vector layer properties windows on one layer, go to dependency layer tab, and check the other layer as a dependency, validate.
3. Open again the vector layer properties windows : the config stays OK. **Validate** to close (do not use the red cross)
4. Open again the vector layer properties windows : the config went away (the configuration displayed in step 3 is not used to save the dependencies when **Validate** button apply the configuration.

**QGIS and OS versions**

Version de QGIS | 3.10.7-A Coruña | Révision du code | b1e3845ba6
-- | -- | -- | --
Compilé avec Qt | 5.12.4 | Utilisant Qt | 5.12.4
Compilé avec GDAL/OGR | 2.4.2 | Utilisé avec GDAL/OGR | 2.4.2
Compilé avec GEOS | 3.7.2-CAPI-1.11.2 | Utilisé avec GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compilé avec SQLite | 3.29.0 | Fonctionne avec SQLite | 3.29.0
Version du client PostgreSQL | 12.3 (Ubuntu 12.3-1.pgdg19.10+1) | Version de SpatiaLite | 5.0.0-beta0
Version de QWT | 6.1.4 | Version de QScintilla2 | 2.10.4
Compilé avec PROJ | 5.2.0 | Fonctionne avec PROJ | Rel. 5.2.0, September 15th, 2018
Version de l'OS | Ubuntu 19.10 | Cette copie de QGIS dispose d'une sortie de débogage.
Extensions Python actives | MetaSearch; processing; db_manager

not working on 3.12 too

**Comment by 3nids** [comment]
I think it would be possible to introduce the layer tree dependencies only, but it sounds a bit risky for a LTR release.

Looking at the code, it seems that we should call `setItemVisibilityCheckedParentRecursive` rather than `setItemVisibilityChecked`.
I gave it a shot here #37541 but I did not compile and test.

It sounds a bit strange: the original feature is 1a5a7c59054e6197dac83cc64ce8fd15fd2b2cb6 on july 2016 and the issue would have been introduced a few months later (dec 2016): 60a17013770a16b35fec3cd83a85bca9ced5e6ce

Can you give it a try?
