### ISSUE TITLE
QGIS Can't read Shapefiles

### ISSUE THREAD

**Issue by AliAbidi555** [qgis/QGIS#37527]
I've tried opening a shapefile layer in QGIS 3.10 but for some reason it opens an empty shapefile layer. The attribute table is empty. I know the shapefiles arent the problem because I've tried with several different shapefiles. I've attached the image that shows what happens. Ivv'e tried using the python console to do the same. I really can't describe this error any better. I've tried reinstalling QGIS. This is particularly strange since I have no problems opening these files in ArcGIS. Raster files open fine however.  
![qgis_issue](https://user-images.githubusercontent.com/67715334/86297268-d9ca7980-bbc8-11ea-9708-0944c79bf960.PNG)

My python code (minus the directory) is as follows: 

uri="C:/Users/mohda/Documents/RA work/diseases/dengue/aegypti.tif"
iface.addRasterLayer(uri,"rastersample")
uri2="C:/Users/mohda/Documents/RA work/sample_shapefiles/BEN_1999_2011.shp"
#Two different ways to add a vector layer
iface.addVectorLayer(uri2,"shape","ogr")
QgsProject.instance().addMapLayer(vlayer)

vlayer=QgsVectorLayer(uri2,"shape","ogr")

I also used the GUI to  try and open the shapefile with the same result.

**Comment by uclaros** [comment]
Could you share one of the failing shapefiles? There might be something wrong with them...

**Comment by AliAbidi555** [comment]
It's not just those shape files. It's quite literally any shape file
whatsoever.

**Comment by gioman** [comment]
@AliAbidi555 In QGIS general options do you have the "show selected features" option enabled?

**Comment by AliAbidi555** [comment]
Yes, I believe so. Do you mean the drop down menu in Settings>Options>Data
Sources?

**Comment by uclaros** [comment]
Could you navigate to the shapefile from the *Browser Panel* and then right click -> Layer properties? Can you see the feature count? the preview or the attributes?

**Comment by AliAbidi555** [comment]
Yes I can. All of those fields are blank. It just isn't opening any
features whatsoever.

**Comment by roya0045** [comment]
Did you try a clean install/reinstallation?

**Comment by AliAbidi555** [comment]
Yes. I tried installing 3.12, 3.10 and 3.8.1 all with the same result. I'm
wondering if it's an issue with my python installation but that seems
unlikely.

**Comment by uclaros** [comment]
Can you copy-paste here the *Information* page from *Layer Properties*?

**Comment by AliAbidi555** [comment]
![info_page](https://user-images.githubusercontent.com/67715334/86359007-724f1100-bc3e-11ea-8229-797c53bfa436.PNG)

**Comment by uclaros** [comment]
Can you export an existing vector layer to a shapefile? Can you see the features in the resulting layer?

**Comment by AliAbidi555** [comment]
I tried this just now. I exported the layer to a shapefile and tried opening it in ArcGIS and got nothing. For the record, it's not opening ANY vector files. I'm new to QGIS, moving from ArcGIS and I haven't been able to open any vector files in QGIS. However, raster files open fine.

**Comment by roya0045** [comment]
What if you try with a standalone mxe build? See https://github.com/qgis/QGIS/actions?query=workflow%3A"Windows+cross+build+with+MXE", download the artefact, unzip twice and use qgis.exe

**Comment by AliAbidi555** [comment]
I'm sorry, but is there something I'm missing? The above link doesn't lead anywhere.

**Comment by roya0045** [comment]
Simply click on Windows cross build with MXE and select one, then click on the artefact.

**Comment by gioman** [comment]
>  it's not opening ANY vector files

@AliAbidi555 please attach here any of your shapfiles...

**Comment by AliAbidi555** [comment]
Here's one 
[counties.zip](https://github.com/qgis/QGIS/files/4864581/counties.zip)

**Comment by AliAbidi555** [comment]
But again, I've tried with basically every shapefile possible. I also tried a different computer so I think I'm doing something wrong.

**Comment by gioman** [comment]
> Here's one
> [counties.zip](https://github.com/qgis/QGIS/files/4864581/counties.zip)

@AliAbidi555 it is empty, so the problem seems to be in the data, not QGIS.

and in fact OGR reports the following:

```
giovanni@sibirica:~/Downloads/counties$ ogrinfo -so tl_2017_us_county.shp tl_2017_us_county
INFO: Open of `tl_2017_us_county.shp'
      using driver `ESRI Shapefile' successful.

Layer name: tl_2017_us_county
Metadata:
  DBF_DATE_LAST_UPDATE=2020-07-02
Geometry: Polygon
Feature Count: 0
Extent: (0.000000, 0.000000) - (0.000000, 0.000000)
Layer SRS WKT:
GEOGCS["GCS_WGS_1984",
    DATUM["WGS_1984",
        SPHEROID["WGS_84",6378137,298.257223563]],
    PRIMEM["Greenwich",0],
    UNIT["Degree",0.017453292519943295],
    AUTHORITY["EPSG","4326"]]
id: Integer64 (10.0)

```

**Comment by AliAbidi555** [comment]
Hello. This isnt' the only file I have an issue with. I've tried random files online and gotten the same issue. In addition, both this file and every other shapefile open fine in ArcGIS.

**Comment by AliAbidi555** [comment]
[rail_l.zip](https://github.com/qgis/QGIS/files/4864625/rail_l.zip)
Here's another one.

**Comment by uclaros** [comment]
Can you try to drag and drop this shapefile into QGIS?
[try_this.zip](https://github.com/qgis/QGIS/files/4864657/try_this.zip)

**Comment by uclaros** [comment]
> [rail_l.zip](https://github.com/qgis/QGIS/files/4864625/rail_l.zip)
> Here's another one.

This one is empty too..

**Comment by gioman** [comment]
> Hello. This isnt' the only file I have an issue with. I've tried random files online and gotten the same issue. In addition, both this file and every other shapefile open fine in ArcGIS.

@AliAbidi555 is weird, but there must be a reason, and of course is very unlikely to be a bug in OGR (the underlying library that QGIS uses to open this type of data sources, which is used in some way also by Arc*). 

If you are downloading this data from a web site please post here the link/url.

**Comment by AliAbidi555** [comment]
I think I'm following the issue now. All of these are shapefiles that I first opened in ArcGIS and then reopened in QGIS. QGIS seems to be 'emptying' them so that when I reopen them in ArcGIS, they're empty there too.

**Comment by gioman** [comment]
> QGIS seems to be 'emptying' them

@AliAbidi555 very unlikely.

**Comment by gioman** [comment]
@AliAbidi555 post the link/url to download the data from the original source.

**Comment by gioman** [comment]
> QGIS seems to be 'emptying'

@AliAbidi555 in fact it is more likely that is Arc* that does something strange to the data (but being a black box, who knows).

**Comment by AliAbidi555** [comment]
[roads.zip](https://github.com/qgis/QGIS/files/4864785/roads.zip)
Okay here's an example. I can open this fine in ArcGIS. 
![arcgis_opensit](https://user-images.githubusercontent.com/67715334/86369369-56eb0280-bc4c-11ea-899e-eb4e938fad2b.PNG)

Here's an image of it opening it in ArcGIS. Then when I try opening it in QGIS, I get nothing. When I try reopening it in ArcGIS, I also get nothing.

**Comment by AliAbidi555** [comment]
@uclaros. I tried opening the shapefile you sent and again, got nothing 
![try_this](https://user-images.githubusercontent.com/67715334/86370140-54d57380-bc4d-11ea-9944-0084ae1fccfe.PNG)

What's more, I think when I tried opening the file, it got corrupted or something and I believe if you try opening it now, you will also find it's blank: 
[try_this.zip](https://github.com/qgis/QGIS/files/4864877/try_this.zip)

**Comment by roya0045** [comment]
Do you always open the files in arcgis first?

**Comment by AliAbidi555** [comment]
@roya0045. No, I do not. But if I open them in QGIS first and then in ArcGIS I also find an empty file. So it's clearly QGIS that's modifying the files somehow.

**Comment by uclaros** [comment]
Can you open in Arc, close, then reopen in Arc?

**Comment by AliAbidi555** [comment]
@uclaros. Yes I can.

**Comment by uclaros** [comment]
Could it be some kind of a new age https://www.f-secure.com/v-descs/dbase.shtml ?

**Comment by uclaros** [comment]
Could you try unzipping my shapefile directly to a folder on `c:\` and try loading it again?

**Comment by AliAbidi555** [comment]
I doubt it's a virus since it happened on another machine I tried it on. And yes, that's what I did the first time. I unzipped the file to a folder in my documents and tried reading it. Just now, I also tried reading it in Arc to make sure it's viable. As you can see I have no issues. However, when I open it in QGIS, I get nothing and the file is gutted. 
![arcgisopensfine](https://user-images.githubusercontent.com/67715334/86373055-f6aa8f80-bc50-11ea-9e36-b4866089eb5d.PNG)

**Comment by uclaros** [comment]
> I unzipped the file to a folder in my documents and tried reading it

My point is to avoid placing it in Documents folder and put it directly in a folder under C:\ like `c:\try_this\`

**Comment by AliAbidi555** [comment]
So I discovered something new. When I open your file using the file browser, on the right, it opens fine, as you can see. However, when I use either the python commands: 
![major_conffusion](https://user-images.githubusercontent.com/67715334/86374503-a3d1d780-bc52-11ea-9962-ee29b1a9c5eb.PNG)


uri="C:/Users/mohda/Documents/RA work/diseases/dengue/aegypti.tif"
iface.addRasterLayer(uri,"rastersample")
uri2="C:/Users/mohda/Documents/RA work/sample_shapefiles/BEN_1999_2011.shp"
#Two different ways to add a vector layer
iface.addVectorLayer(uri2,"shape","ogr")
QgsProject.instance().addMapLayer(vlayer)

vlayer=QgsVectorLayer(uri2,"shape","ogr")

Or the GUI "Add vector layer" option on the top, it empties the shapefiles. 

![empty_again](https://user-images.githubusercontent.com/67715334/86374523-a9c7b880-bc52-11ea-82f8-9c9e2adef27b.PNG)

**Comment by gioman** [comment]
> Or the GUI "Add vector layer" option on the top, it empties the shapefiles.

@AliAbidi555 I can't confirm... this is getting weirder but still I really think this is **not** a QGIS issue, otherwise we would have been already flooded with tickets from angry users.

Can you please post the link where to download one of your shapes? Or attach the shapefile **before** opening it in QGIS (and ArcGIS) as also a copy **after**having being opened in QGIS.

**Comment by uclaros** [comment]
@AliAbidi555 Do you, by any chance, open the shapefile by doing: Layer -> Create Layer -> New Shapefile Layer... ?

**Comment by AliAbidi555** [comment]
No, I was using 'Layer>Add Layer>Add Vector Layer' 


I think I've managed to isolate the issue. Does QGIS not natively read ALL the associated files other than the shapefiles in the directory? Or do you need to point it to zip files only? If so, I apologize for my ignorance but I must point out that the documentation does NOTHING to make that either clear or intuitive.

**Comment by gioman** [comment]
> NOTHING

@AliAbidi555 there is NOTHING to clarify really. QGIS can open .shp files as any other GIS software OR can open zipped shapefiles.

**Comment by gioman** [comment]
@AliAbidi555 once again (please), Can you please post the link where to download one of your shapes? Or attach the shapefile before opening it in QGIS (and ArcGIS) as also a copy afterhaving being opened in QGIS.

**Comment by AliAbidi555** [comment]
Okay then for some reason, I'm only able to open zipped shapefiles, but not
by pointing it to individual files. I'm not sure what's causing this but
it's not as much an issue since I know how to work around it. Coding wise,
I can set the directory to the folder instead of the shapefile.

**Comment by gioman** [comment]
> I'm only able to open zipped shapefiles,

@AliAbidi555 because zipped shapefiles are **read only**, while of course we already understand that opening directly the .shp datasource something (bad) happens. We are trying to help you, but can you please help us? send over an unspoiled shape and its ruined counterpart.

**Comment by AliAbidi555** [comment]
I'll close this issue for now. I'm sorry for the constant questioning but since this is now an error I can work around.  But I can give you the issue here. 
[try_this (2).zip](https://github.com/qgis/QGIS/files/4865391/try_this.2.zip) Here's the unspoiled file.

And now the spoiled file. 
[try_this (2)_spoiled.zip](https://github.com/qgis/QGIS/files/4865400/try_this.2._spoiled.zip)

**Comment by AliAbidi555** [comment]
Apologies, I didn't mean to close it now. I'll keep it open for the sake of posterity.

**Comment by gioman** [comment]
>  I'll keep it open for the sake of posterity.

@AliAbidi555 without any proof that is a QGIS issue (as is likely not possible to replicate, hopefully) this will be closed sometime in the next future. One more question: can you record a screencast and show us the steps you follow? from the download of the data, to opening in QGIS/Arc*, thanks.

**Comment by gioman** [comment]
> try_this (2)_spoiled.zip

@AliAbidi555 .shx and .prj missing.

**Comment by gioman** [comment]
> And now the spoiled file.
> [try_this (2)_spoiled.zip](https://github.com/qgis/QGIS/files/4865400/try_this.2._spoiled.zip)

@roya0045 I used the "repair shapefile" tool to re-create the .SHX file, and your shape open just fine here...

**Comment by roya0045** [comment]
@gioman wrong @

**Comment by gioman** [comment]
> @gioman wrong @

@roya0045 ?

**Comment by agiudiceandrea** [comment]
@AliAbidi555 I opened the shapefile roads_l_v2, contained in the zipfile [roads.zip](https://github.com/qgis/QGIS/files/4864785/roads.zip) that you provided, several times using ArcMap 9.3.1 and QGIS (3.10.6, 3.12.3, 3.14.0) without any problem

![image](https://user-images.githubusercontent.com/16253859/86395828-2aada100-bca1-11ea-9ac8-625b5e616f70.png)
![image](https://user-images.githubusercontent.com/16253859/86396088-9a239080-bca1-11ea-84f1-c4aaa9eaf1e7.png)

**Comment by gioman** [comment]
Closing for lack of further feedback and as it seems really a local issue.
