### ISSUE TITLE
"Layer(s) not valid" when trying access Oracle datasources in QGIS Server

### ISSUE THREAD

**Issue by MappamondoInfo** [qgis/QGIS#37525]
While migrating a sample Qgis project to Qgis Server (& Lizmap), we get an error if we use a Vector layer whose data source is Oracle Spatial; the project works fine in Qgis Desktop. The project works fine also in Qgis Server if we use the same Vector layer in shapefile format or from a PostGIS data source.
O/S: Windows 10 64bit hosting all the software:
QGIS version 3.4.15-Madeira
Oracle Database version 12c 64bit
Xampp version 7.13.12

Excerpt from qgis_server.log:
16:23:36 INFO Server[10872]: No server python plugins are available
16:23:36 INFO Server[10872]: ******************** New request ***************
16:23:36 INFO Server[10872]: SERVER_NAME127.0.0.1
16:23:36 INFO Server[10872]: REQUEST_URI/cgi-bin/qgis_mapserv.fcgi?map=C%3A%5COSGeo4W64%5Capps%5Cqgis%2Dltr%5Cbin%2FSiti%5FprovaW%5FMM%5Fs02%2Eqgs&request=GetCapabilities&service=WMS&version=1%2E3%2E0
16:23:36 INFO Server[10872]: REMOTE_ADDR127.0.0.1
16:23:36 INFO Server[10872]: HTTP_USER_AGENTLizmap
16:23:36 INFO Server[10872]: MAP:C:\OSGeo4W64\apps\qgis-ltr\bin/Siti_provaW_MM_s02.qgs
16:23:36 INFO Server[10872]: REQUEST:GetCapabilities
16:23:36 INFO Server[10872]: SERVICE:WMS
16:23:36 INFO Server[10872]: VERSION:1.3.0
16:23:36 WARNING [10872]: Invalid data provider oracle
16:23:36 CRITICAL Server[10872]: Layer(s) G_FUGHE_b7eb9bd7_c71d_47e4_bd86_b3b50db07693 not valid
16:23:36 INFO Server[10872]: Request finished in 391 ms

**Comment by gioman** [comment]
@MappamondoInfo 




> REQUEST_URI/cgi-bin/qgis_mapserv.fcgi?

is your server Windows or Linux? 
From the above line it seems to be a Linux one (on Windows typically the URL is like "/qgis-ltr/qgis_mapserv.fcgi.exe") but this other line

>  16:23:36 INFO Server[10872]: MAP:C:\OSGeo4W64\apps\qgis-ltr\bin/Siti_provaW_MM_s02.qgs

seems to indicate you are on Windows.

**Comment by MappamondoInfo** [comment]
The server is Windows 10
 


Da: "Giovanni Manghi" notifications@github.com
A: "qgis/QGIS" QGIS@noreply.github.com
Cc: "MappamondoInfo" info@mappamondoInformatica.it,"Mention" mention@noreply.github.com
Data: Wed, 01 Jul 2020 09:35:06 -0700
Oggetto: Re: [qgis/QGIS] Oracle provider not available in Qgis Server (#37525)



@MappamondoInfo

REQUEST_URI/cgi-bin/qgis_mapserv.fcgi?

is your server Windows or Linux?

From the above line it seems to be a Linux one (on Windows typically the URL is like "/qgis-ltr/qgis_mapserv.fcgi.exe") but this other line

16:23:36 INFO Server[10872]: MAP:C:\OSGeo4W64\apps\qgis-ltr\bin/Siti_provaW_MM_s02.qgs

seems to indicate you are on Windows.

**Comment by gioman** [comment]
> The server is Windows 10

so the URL you are using to call QGIS server seems wrong.

**Comment by MappamondoInfo** [comment]
But the same URL works ok if I use layers in shapefile or PostGIS. With Oracle I get the "Invalid data provider" error in the log


Da: "Giovanni Manghi" notifications@github.com
A: "qgis/QGIS" QGIS@noreply.github.com
Cc: "MappamondoInfo" info@mappamondoInformatica.it,"Mention" mention@noreply.github.com
Data: Wed, 01 Jul 2020 11:20:08 -0700
Oggetto: Re: [qgis/QGIS] Oracle provider not available in Qgis Server (#37525)




The server is Windows 10

so the URL you are using to call QGIS server seems wrong.

**Comment by gioman** [comment]
> But the same URL works ok if I use layers in shapefile or PostGIS. With Oracle I get the "Invalid data provider" error in the log

ok weird. Do you have all the necessary libraries (for Oracle) installed on the server?

**Comment by MappamondoInfo** [comment]
Yes, on the same server, the same project in Qgis Desktop works ok with data in Oracle Spatial, in Qgis server i get the error if I use Oracle provider
 


Da: "Giovanni Manghi" notifications@github.com
A: "qgis/QGIS" QGIS@noreply.github.com
Cc: "MappamondoInfo" info@mappamondoInformatica.it,"Mention" mention@noreply.github.com
Data: Wed, 01 Jul 2020 11:26:32 -0700
Oggetto: Re: [qgis/QGIS] Oracle provider not available in Qgis Server (#37525)




But the same URL works ok if I use layers in shapefile or PostGIS. With Oracle I get the "Invalid data provider" error in the log

ok weird. Do you have all the necessary libraries (for Oracle) installed on the server?

**Comment by vdestefano** [comment]
Hi, I found the same problem using oracle layer (Oracle 12c).
On the same server the project in QGIS Desktop works fine, but with QGIS Server I have this warning in the log:
"WARNING [5248]: Invalid data provider oracle"

This is my configuration :
O/S: WindowsServer 2012-R2 64bit
QGIS ltr version 3.10.9-1
QGIS Server version 3.10.9-1
Oracle instant client 12.1
Apache version 2.4.41 (Apache Lounge VS16 Server built)

How can I check if QGIS Server read correctly the oracle libraries?

**Comment by kartoffelfee** [comment]
Hi, same problem and less ideas on debian. Has anyone of you a solution or some more hints?

**Comment by elpaso** [comment]
@kartoffelfee on debian you should be able to see the loaded providers in the server logs (I don't know about windows, sorry), in any event the debian issue probably deserves a separate ticket.

**Comment by kartoffelfee** [comment]
the only information in the server log is 'Invalid data provider oracle' and I don' know what qgis wants to tell me / what might be missing.
Seems to me to be more a genreal qgis_server problem than an OS-depending issue?

**Comment by elpaso** [comment]
That message means that QGIS (server or desktop is the same) was asked to load a layer using a provider named "oracle" but that provider was not found, 99% of the times it means that QGIS was not built with oracle provider support.

I'm pretty sure that this is a packaging/building issue and that it is not related to the server but to QGIS core libraries (well, technically the provider plugins), packaging is done independently for linux and windows.  @jef-n knows more about this topic.

**Comment by kartoffelfee** [comment]
While you where writing the last comment I talked with @jef-n. To experts with one solution should make it, much better than talking to lawers :)

Thanks!

**Comment by jef-n** [comment]
With our debian packages we don't ship the oracle providers as it requires extra dependencies not found in the base distribution (ie. the oracle instantclient).
In OSGeo4W we ship the instant client and the oracle provider, but as optional component.  So the windows users experiencing this just need to install the packages and users trying to build the debian packages need to build themselves (the packaging files are already prepared for this).  Either way it doesn't seem to be a bug.

**Comment by leojth** [comment]
On Windows, make sure you include the "qgis-oracle-provider" package under libs when selecting packages in the OSGeo4W installer or you will get exactly this behaviour with "_Invalid data provider oracle_".
![bild](https://user-images.githubusercontent.com/5588530/97288125-b1385080-1845-11eb-95d2-5464f9f2d699.png)
