### ISSUE TITLE
RESTful implementation of a QGIS server WMTS URL

### ISSUE THREAD

**Issue by swiss-knight** [qgis/QGIS#37540]
Hi,

I am using this docker image https://hub.docker.com/r/camptocamp/qgis-server to build a simple QGIS server. 
From inside that container, I noticed that QGIS version is:    

```
root@docker-container-id:/project# qgis --version
QGIS 3.10.6-A Coruña 'A Coruña' (ec80021f49)
```

With that, I've build a small project to serve raster imagery through a WMTS.

Everything works fine ; with Firefox, I can access the capabilities.xml and the individual tiles with an URL formatted with `&key=value` pairs according to https://docs.qgis.org/3.10/en/docs/user_manual/working_with_ogc/server/services.html#web-map-tile-service-wmts.

For example, this URL returns the capabilities:

`http://{baseurl}/?SERVICE=WMTS&VERSION=1.3.0&REQUEST=GetCapabilities
`

But if I want to access the exact same resource using the following RESTful formatted URL ;

`http://{baseurl}/1.3.0/WMTSCapabilities.xml`

it doesn't work.
It neither throws me an error (which is a good start), but the page returned by the server says:

`Service unknown or unsupported`

This is how the WMTS is configured in my QGIS project file:

![image](https://user-images.githubusercontent.com/19967599/86346992-fb297500-bc5d-11ea-9c3e-dab7c3099a98.png)

And this what the server tells while it is receiving the request:
```
qgisserver_1  | 10:27:41 INFO Server[79]: ******************** New request ***************                                                   
qgisserver_1  | 10:27:41 INFO Server[79]: Request URL: http://{baseurl}/1.3.0/WMTSCapabilities.xml?                                    
qgisserver_1  | 10:27:41 INFO Server[79]: Environment:                                                                                       
qgisserver_1  | 10:27:41 INFO Server[79]: ------------------------------------------------                                                   
qgisserver_1  | 10:27:41 INFO Server[79]: SERVER_NAME: {baseurl}                                                                       
qgisserver_1  | 10:27:41 INFO Server[79]: REQUEST_URI: /1.3.0/WMTSCapabilities.xml                                                           
qgisserver_1  | 10:27:41 INFO Server[79]: SCRIPT_NAME: /1.3.0/WMTSCapabilities.xml                                                           
qgisserver_1  | 10:27:41 INFO Server[79]: REMOTE_ADDR: {baseip}                                                                       
qgisserver_1  | 10:27:41 INFO Server[79]: SERVER_PORT: 80                                                                                    
qgisserver_1  | 10:27:41 INFO Server[79]: QUERY_STRING:                                                                                      
qgisserver_1  | 10:27:41 INFO Server[79]: REQUEST_METHOD: GET                                                                                
qgisserver_1  | 10:27:41 INFO Server[79]: HTTP_ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8            
qgisserver_1  | 10:27:41 INFO Server[79]: HTTP_USER_AGENT: Mozilla/5.0 (Windows NT 10.0; ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83. 
0.4086.0 Safari/537.36                                                                                                                       
qgisserver_1  | 10:27:41 INFO Server[79]: QGIS_PROJECT_FILE: /etc/qgisserver/project.qgs                                                     
qgisserver_1  | 10:27:41 INFO Server[79]: Trying URL path: /1.3.0/WMTSCapabilities.xml for /wfs3                                             
qgisserver_1  | 10:27:41 WARNING [79]: Service  is not registered                                                                            
qgisserver_1  | 10:27:41 WARNING Server[79]: <ServiceExceptionReport version="1.3.0" xmlns="http://www.opengis.net/ogc">                     
qgisserver_1  |  <ServiceException code="Service configuration error">Service unknown or unsupported</ServiceException>                      
qgisserver_1  | </ServiceExceptionReport>                                                                                                    
qgisserver_1  |                                                                                                                              
qgisserver_1  | 1626 - 10.192.90.216 - - [02/Jul/2020:10:27:41 +0000] "GET /1.3.0/WMTSCapabilities.xml HTTP/1.1" 200 432 "-" "Mozilla/5.0 (Windows NT 10.0; ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4086.0 Safari/537.36"                                                   
qgisserver_1  | 10:27:41 INFO Server[79]: Request finished in 1 ms                                                                           

```

What is wrong there?    
Is this not implemented or am I missing something obvious?

Thanks.

**Comment by elpaso** [comment]
> 
> But if I want to access the exact same resource using the following RESTful format ;
> 
> `http://{baseurl}/1.3.0/WMTSCapabilities.xml`
> 
> it doesn't work.

What is it? Can you point me to the specifications of this RESTful WMTS service?

AFAIK the only restful service implemented in QGIS Server is OAPIF/WFS3.

**Comment by swiss-knight** [comment]
I'm not much enough into these things, but from this old documentation:

https://docs.qgis.org/2.8/en/docs/user_manual/working_with_ogc/ogc_client_support.html

I read this:

> For testing the topo2 layer in this WMTS works nicely. Adding this string indicates that a WMTS web service is to be used instead of a WMS service.
> 
>     2. The RESTful WMTS service takes a different form, a straightforward URL. The format recommended by the OGC is:
> 
> {WMTSBaseURL}/1.0.0/WMTSCapabilities.xml
> 
> This format helps you to recognize that it is a RESTful address. A RESTful WMTS is accessed in QGIS by simply adding its address in the WMS setup in the URL field of the form. An example of this type of address for the case of an Austrian basemap is http://maps.wien.gv.at/basemap/1.0.0/WMTSCapabilities.xml.

And the URL given here (http://maps.wien.gv.at/basemap/1.0.0/WMTSCapabilities.xml) works fine in what I call the "RESTful format" (even if I don't know how it is served actually). So, I wish QGIS server could accept such URL format.

At the very end, I wish I can request my tiles with:    
http://{baseurl}/default/EPSG:3857/{z}/{x}/{y}.png

so that I can use them as a basemap in openstreetmap.

In addition, I was not able to find out what is the so called "_format recommended by the OGC_". Which would obviously be the place to start building my request URL...

**Comment by gioman** [comment]
@swiss-knight closing as questions are to be posted in the users/developers mailing lists.

**Comment by swiss-knight** [comment]
I actually found where the aforementioned RESTful implementation is defined;

![image](https://user-images.githubusercontent.com/19967599/86361697-84e43d00-bc74-11ea-8a0b-8a5cdf0dc4e7.png)

On page 61 of the OGC document titled ["OpenGIS Web Map Tile Service Implementation Standard"](http://portal.opengeospatial.org/files/?artifact_id=35326).
