### ISSUE TITLE
Fields and values also for the Map Layer group

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#37544]
**Feature description.**

In the Field Calc it is possible to call other layers with `gef_feature`, `get_feature_by_id`, `aggregate`, etc ..., but there is no way to display the `fields and values` of the called layer.

Currently it is necessary to close the field calc, while writing an expression, to display the `fields and values` of the layers called

![image](https://user-images.githubusercontent.com/7631137/86370780-6d12b600-bc80-11ea-8a48-e1177eb6b056.png)

**Comment by Korto19** [comment]
Great idea pigreco, I subscribe

**Comment by andreasneumann** [comment]
It is a good idea - but it shouldn't result in a big slowdown of the expression editor while retrieving attributes of dozens of layers.

If implemented, it should use some "on-demand" loading of such attributes only for layers of interest (e.g. when unfolding a selected layer in the the layer list), and not "pre-populate" all layers with all attributes.

**Comment by massimofigaroli** [comment]
Molto interessante!

**Comment by pigreco** [comment]
> It is a good idea - but it shouldn't result in a big slowdown of the expression editor while retrieving attributes of dozens of layers.

I personally work a lot with the `get_feature`,` get_feature_by_id` and `aggregate` functions and I find it annoying every time to close and reopen the expression builder to see the names of the fields of the called layers.

In my opinion, the utility outweighs any performance problems.

Could someone make a cost estimate to make it happen?

**Comment by gioman** [comment]
> Could someone make a cost estimate to make it happen?

@pigreco 
https://qgis.org/en/site/forusers/commercial_support.html

**Comment by bellanz80** [comment]
Great idea pigreco, I commented that it seems to me an essential option for an effective management of all relationships and panels

**Comment by pigreco** [comment]
Alternatively, to avoid weighing down the calc field in the case of many layers, make the list of fields appear under the name of the layer, perhaps using the expression:

```
array_to_string(
map_akeys(
attributes(
get_feature_by_id(@layer_name,0)))
)
```
![image](https://user-images.githubusercontent.com/7631137/127764631-c2dd7821-69ca-4ce8-bee9-efefbae95f36.png)

**Comment by elpaso** [comment]
> It is a good idea - but it shouldn't result in a big slowdown of the expression editor while retrieving attributes of dozens of layers.
> 
> If implemented, it should use some "on-demand" loading of such attributes only for layers of interest (e.g. when unfolding a selected layer in the the layer list), and not "pre-populate" all layers with all attributes.

I don't think this is an issue: the fields are already available in the layer instances, there is no need to do any expensive operation to retrieve them from the layers.

**Comment by pigreco** [comment]
Thank you very much ARPA Piemenonte and @elpaso
