### ISSUE TITLE
Implement version 1.1.0 for WFS-T

### ISSUE THREAD

**Issue by qgis-falk** [qgis/QGIS#37555]
I have integrated a WFS-T in version 1.1.0 in QGIS. This version information is not adopted when generating the transaction XML. This leads to an error when updating the geodata.

The version with which the service is registered in QGIS should also be used when generating the transaction XML.

**Example:** --> **version="1.0.0"**
`
<Transaction xmlns="http://www.opengis.net/wfs"
                                            xmlns:gml="http://www.opengis.net/gml"
                          xsi:schemaLocation="https://geoportal.umwelt.sachsen.de/arcgis/services/gewaessernetz/gewaessernetz_meissen/MapServer/WFSServer
                                                                                                      https://geoportal.umwelt.sachsen.de/arcgis/services/gewaessernetz/gewaessernetz_meissen/MapServer/WFSServer?SERVICE=WFS&amp;REQUEST=DescribeFeatureType&amp;VERSION=1.0.0&amp;TYPENAME=gewaessernetz_gewaessernetz_meissen:Gewaessernetz"
                                            **version="1.0.0"**
                                            service="WFS"                              xmlns:gewaessernetz_gewaessernetz_meissen="https://geoportal.umwelt.sachsen.de/arcgis/services/gewaessernetz/gewaessernetz_meissen/MapServer/WFSServer"
                                            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
               <Update xmlns="http://www.opengis.net/wfs" typeName="gewaessernetz_gewaessernetz_meissen:Gewaessernetz">
                              <Property xmlns="http://www.opengis.net/wfs">
                                            <Name xmlns="http://www.opengis.net/wfs">gewaessernetz_gewaessernetz_meissen:ZWEITNAME</Name>
                                            <Value xmlns="http://www.opengis.net/wfs">ABC</Value>
                              </Property>
                              <Filter xmlns="http://www.opengis.net/ogc">
                                            <FeatureId xmlns="http://www.opengis.net/ogc" fid="Gewaessernetz.145276"/>
                              </Filter>
               </Update>
</Transaction>
`

**Comment by gioman** [comment]
@qgis-falk QGIS version?

**Comment by qgis-falk** [comment]
Right. I forgot to say.
In the current version 3.14.

greetings

**Comment by gioman** [comment]
>  In the current version 3.14.

@qgis-falk can you say if it worked as expected in a previous release?

**Comment by rouault** [comment]
The WFS provider only supports 1.0.0 in transaction mode

**Comment by qgis-falk** [comment]
The XML generated by QGIS for the transaction works correctly except for the version parameter. So it would be nice if the version number were variable.

Would it be possible to turn that into one of the next versions?

**Comment by rouault** [comment]
> So it would be nice if the version number were variable.

I believe a bit more work than just updating the version number is required 

> Would it be possible to turn that into one of the next versions?

Depends on someone contributing that enhancement

**Comment by qgis-falk** [comment]
It may well be that there is more to do.
What options do I have to advance what?

**Comment by gioman** [comment]
>  What options do I have to advance what?

Submit code or hire a developer. In the QGIS.org site there is a page dedicated to commercial support, if needed.

**Comment by symbioquine** [comment]
@rouault Can this be resolved with https://github.com/qgis/QGIS/commit/b1da0810c2dbb125f148f3a04d1df6cb0874d100?

There's still a tiny bug where the version of the DescribeFeatureType URI in the `xsi:schemaLocation` is still [hard-coded](https://github.com/qgis/QGIS/blob/13e4969817e990629748a3342938df0c772e14c4/src/providers/wfs/qgswfsprovider.cpp#L1660) to `1.0.0`, but I'm planning to open a new issue for that...

**Comment by rldhont** [comment]
@symbioquine done https://github.com/qgis/QGIS/pull/40661

**Comment by rouault** [comment]
Yes, closing that issue as resolved with https://github.com/qgis/QGIS/commit/b1da0810c2dbb125f148f3a04d1df6cb0874d100
