### ISSUE TITLE
Support for curved geometries in the Advanced Digitizing operations

### ISSUE THREAD

**Issue by saberraz** [qgis/QGIS#37557]
As the dedicated button for drawing curves has limited usage (only drawing!!), it is proposed to have a toggle for Straight/Curved lines which can be activated during different operations. The toggle will have a shortcut keyboard, which makes it easier for users to quickly switch between curved and straight lines.

CC: @wonder-sk and @vcloarec

**Comment by nyalldawson** [comment]
Good idea!

**Comment by YoannQDQ** [comment]
Fixed by #37685
