### ISSUE TITLE
layer name does not show anymore when loading gpx datasources

### ISSUE THREAD

**Issue by jpjp74** [qgis/QGIS#37551]
With QGIS 3.12, when loading a gpx layer, the name of that gpx layer is displayed in the explorer.
I notice that with version 3.14, only the "type" of the layer (in the gpx sense): "track" or "Waypoint" is displayed. 

Avec QGIS 3.12, lorsque l'on charge une couche gpx, le nom de cette couche gpx s'affiche dans l'explorateur.
Je constate qu'avec la version 3.14, seul le "type" de la couche (au sens gpx) : "track" ou "Waypoint" s'affiche.

**Comment by gioman** [comment]
Confirmed, it works on 3.10 but not on 3.14/master. It happens regardless the way the GPX is loaded ("add vector layer", browser and D&D in the map canvas).
