### ISSUE TITLE
[Feature] Add populateContextMenu to QgsMapCanvas

### ISSUE THREAD

**Issue by jakimowb** [qgis/QGIS#37559]
**Feature description**

It would be awesome if the QgsMapCanvas provides an easy way to extend its context menu.

This could be done e.g. by separating the creation of the default context menu from where it is shown:

1. add a new ``QMenu* QgsMapCanvas::populateContextMenu(QMenu *menu, QgsMapMouseEvent *event)`` that creates the default context menu. Since QGIS 3.14 this is the "Copy Coordinate" menu: 
![image](https://user-images.githubusercontent.com/1404870/86453885-c29da000-bd1e-11ea-8e6e-7410682e8aff.png)

2. call ``QgsMapCanvas::populateContextMenu(...)`` within ``QgsMapCanvas::showContextMenu`` :

````cpp
void QgsMapCanvas::showContextMenu( QgsMapMouseEvent *event )
{
  const QgsPointXY mapPoint = event->originalMapPoint();

  mMenu->clear();
  
  populateContextMenu(mMenu, event)

  if ( mMapTool )
    mMapTool->populateContextMenu( mMenu );

  mMenu->exec( event->globalPos() );
}

````
3. ``QgsMapCanvas::populateContextMenu`` should be available in PyQGIS. This would allow plugin developers to enhance it in inherited classes.

**Additional context**

AFAIK there was no default context menu before QGIS 3.14. Plugin-developers would have created it by implementing [``QWidget::contextMenuEvent(QContextMenuEvent *event)``](https://doc.qt.io/qt-5/qwidget.html#contextMenuEvent) in a child class. Since QGIS 3.14 (aa86c742ef6661fc171c66c914e4c467ad275ea0) the QgsMapCanvas uses ``void QgsMapCanvas::showContextMenu( QgsMapMouseEvent *event )`` to create and show the default context menu:

````cpp
void QgsMapCanvas::showContextMenu( QgsMapMouseEvent *event )
{
  const QgsPointXY mapPoint = event->originalMapPoint();

  mMenu->clear();

  QMenu *copyCoordinateMenu = new QMenu( tr( "Copy Coordinate" ), mMenu );
 //
 // code to build copyCoordinateMenu
 //
  mMenu->addMenu( copyCoordinateMenu );

  if ( mMapTool )
    mMapTool->populateContextMenu( mMenu );

  mMenu->exec( event->globalPos() );
}
````
It is called by the ``mousePressEvent``, which itself handles other important issues, e.g. the state of the current map tool.
By now, changing the QgsMapCanvas context menu e.g. in a python plugin, would required overwrite and re-implement large parts of code, in particular because ``showContextMenu`` is not accessible in PyQGIS.

**Comment by nyalldawson** [comment]
@jakimowb can you submit a pull request? Seems like you've already worked out everything required here!

**Comment by jakimowb** [comment]
@nyalldawson 
My first C++ code ever is available as PR.

However, I am surprised how well every is documented in https://github.com/jakimowb/QGIS/blob/master/INSTALL.md#3-building-on-gnulinux. Neither I know much about Linux, nor am I familiar with C/C++. Nevertheless I was able to build, install and use my modified QGIS in a short time. Thanks for all the effort you and the other put into the documentation. 👍
