### ISSUE TITLE
Export to standard pdf always rasterize vectors elements

### ISSUE THREAD

**Issue by domlysz** [qgis/QGIS#37563]
**Describe the bug**

When exporting to a standard PDF (no geopdf) with the option _Always export as vectors_ checked and the option _Print as raster_ unchecked then the resulting pdf is completly rasterized, even vectors or text elements.

**How to Reproduce**

1. load a vector layer
2. create a new layout, add a map and check the option Always export as vectors
3. export to pdf (keep geopdf option unchecked)

**QGIS and OS versions**

QGIS 3.14 Windows

**Additional context**

Note that because of [this issue](https://github.com/qgis/QGIS/issues/33465) with geopdf export, there is actually no way to produce an high quality pdf for a professional printing, which IMO is critical.

**Comment by bkepl** [comment]
Domlysz,

I am able to correctly export PDFs as vectors even if the map includes rasters, even if I have given the raster transparency and I have vectors layered beneath that raster. Have you set any vector layer to have transparency? I noted a while back that if I set any layer to have a transparency via the **Layer rendering** section of the Layer styling panel, the map will rasterize. If, on the other hand, I set the _symbology_ to have transparency (the symbology as a whole or the fill/outline separately), vector layers will render properly, as vectors.

**Comment by domlysz** [comment]
Hi bkelp,

Thanks for the answer, after some investigation the issue come from effects on some symbols. Disabling the effects allows vector export but layer opacity are not taken into account (fully opaque). On another side geopdf export works correctly with effects and opacity.

**Comment by bkepl** [comment]
Good to know, thank you. I’ve suspected that would be the case (applying
effects to symbols (or to features?)) but I haven’t had the opportunity to
test it yet.

**Comment by nyalldawson** [comment]
I don't think there's any bug here -- some symbol/rendering settings require the whole map to be rasterized and flattened in order to export correctly. Geopdf gives us a bit more flexibility with this, when it's available for export.
