### ISSUE TITLE
Array from aggregate not working in HTML snippet

### ISSUE THREAD

**Issue by M-Rick** [qgis/QGIS#37569]
**Describe the bug**
When adding an aggregate expression in an HTML snippet in a custom form, the result won't be displayed in the form.

**How to Reproduce**
Open the Attributes Form Properties and create a new custom form with an HTML snippet.
In the expression editor create a new aggregate, of any king it doesn't matter.
Insert this expression as a new script in the HTML code field. Nothing will be displayed.

In the screenshot above, I used a quite simple aggregate from a relation aggregate.
It will catch STRING separated comas features from an array. I wrote a 'TEST' text to identify where this should be written.
![Capture d’écran 2020-07-01 à 15 08 05](https://user-images.githubusercontent.com/2520948/86479451-7ff2bc80-bd4c-11ea-9b22-864eb08d0c60.png)

There's no error in the code itself, since the result is displayed in the expression editor.
![Capture d’écran 2020-07-01 à 14 57 50](https://user-images.githubusercontent.com/2520948/86479888-41113680-bd4d-11ea-9e16-0f7550345586.png)

And they are perfectly displayed in the attributes table.
![Capture d’écran 2020-07-01 à 14 57 41](https://user-images.githubusercontent.com/2520948/86479909-4b333500-bd4d-11ea-9f0c-7b6b02b7e707.png)

It works anywhere else like with the print composer.

Same code in a simple text widget in the print composer.
![Capture d’écran 2020-07-01 à 15 02 07](https://user-images.githubusercontent.com/2520948/86480388-34d9a900-bd4e-11ea-9c8d-a7d610cc754f.png)

Same code in an HTML widget in the print composer.
![Capture d’écran 2020-07-01 à 15 06 20](https://user-images.githubusercontent.com/2520948/86480261-f348fe00-bd4d-11ea-947a-45ab5565cf79.png)

**QGIS and OS versions**
10.7 through 10.15 nightly / MacOS 10.14.6 Mojave and 10.15.5 Catalina.
Linux and probably Windows as well.

Version de QGIS | 3.10.7-A Coruña | Révision du code | 7b4ca4c8d0
-- | -- | -- | --
Compilé avec Qt | 5.12.3 | Utilisant Qt | 5.12.3
Compilé avec GDAL/OGR | 2.4.1 | Utilisé avec GDAL/OGR | 2.4.1
Compilé avec GEOS | 3.7.2-CAPI-1.11.2 | Utilisé avec GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compilé avec SQLite | 3.28.0 | Fonctionne avec SQLite | 3.28.0
Version du client PostgreSQL | 11.3 | Version de SpatiaLite | 4.3.0a
Version de QWT | 6.1.4 | Version de QScintilla2 | 2.11.1
Compilé avec PROJ | 5.2.0 | Fonctionne avec PROJ | Rel. 5.2.0, September 15th, 2018
Version de l'OS | macOS Mojave (10.14)
Extensions Python actives | SpreadsheetLayers; QuickOSM; qfieldsync; Mergin; processing; db_manager; MetaSearch

Version de QGIS | 3.10.7-A Coruña | Révision du code | 7b4ca4c8d0
-- | -- | -- | --
Compilé avec Qt | 5.12.8 | Utilisant Qt | 5.12.8
Compilé avec GDAL/OGR | 3.0.4 | Utilisé avec GDAL/OGR | 3.0.4
Compilé avec GEOS | 3.8.0-CAPI-1.13.1 | Utilisé avec GEOS | 3.8.0-CAPI-1.13.1
Compilé avec SQLite | 3.31.1 | Fonctionne avec SQLite | 3.31.1
Version du client PostgreSQL | 12.2 (Ubuntu 12.2-4) | Version de SpatiaLite | 4.3.0a
Version de QWT | 6.1.4 | Version de QScintilla2 | 2.11.2
Compilé avec PROJ | 6.3.1 | Fonctionne avec PROJ | Rel. 6.3.1, February 10th, 2020
Version de l'OS | Ubuntu 20.04 LTS
Extensions Python actives | MetaSearch; processing; db_manager

**Comment by tudorbarascu** [comment]
Just discovered that the HTML widget doesn't do well when you split a function with a newline. Just discovered this yesterday.

Basically:  ``concat('a','b')`` works but
``concat('a',``
``'b')`` Doesn't work cause after ``,`` there's a newline.

@M-Rick Maybe it's this issue here also.. so just make a one liner.
