### ISSUE TITLE
Legend in map atlas anchored to bottom left or bottom right will not correctly reposition in PDF

### ISSUE THREAD

**Issue by bkepl** [qgis/QGIS#37566]
**Describe the bug**
In a map atlas, if I anchor a legend to either the bottom left of bottom right and if the legend is set to limit to the features to the current atlas item, it positions itself properly when I traverse the atlas manually, but when I output the atlas to a PDF or individual PDFs, the legend shifts seemingly at random. Sometimes if atlas items have many features in the legend, the legend will fall off the page or position itself higher on the page.

**How to Reproduce**
1. Create an atlas of villages within a county, with a legend containing names of parks using the county's tax parcels data. 

2. Place the legend at the bottom right of bottom left of the page. 

3. As you manually traverse the atlas, the top off the legend will reposition as needed to accommodate the list of parks. 

4. Output the atlas to a PDF or PDFs. If the first village has five parks and the next has ten, the list will fall off the page. If the next following village has three parks, there will be more space below the legend than there was in the first map. 

**QGIS and OS versions**
3.14 and earlier; Windows 10 Professional

**Additional context**
The only ways I can resolve this is position the legend at the top of the page or to output the PDFs individually as I traverse the atlas.

**Comment by techdude1996** [comment]
I've noticed this issue with Atlas in previous versions as well (not just 3.14). This bug is not only for bottom-right anchor, but also middle-left (which is what I'm using). When the GUI loads the current atlas page, the legend seems to snap into position shortly after the page has "finished loading".

**Comment by TimClifton** [comment]
I could reproduce the issue for all reference points except top left which appears to work correctly. I even tried fixing the X and Y coordinates using data defined overrides and it still moved. It also seems to make a difference to the position depending on which Atlas page you're on when you begin the export. In my example exporting when on Page 1 resulted in different legend positions compared to when I exported while on Page 2.

**Comment by roya0045** [comment]
Is the auto-resizing option on in those cases?

**Comment by pjshelton** [comment]
Hi,
This bug also happens with export to image.
@roya0045 I suspect that that it is the case that auto-resizing is on.

attached is a project with layers which demonstrates the problem.

It is also that the top of the legend is correct for the wrong page.  So in my case, 

- when you look at page 1, the legend top is correct for the data on the third page,
- when you look at page 2, the legend top is correct for the data on the first page,
- and when you look at page 3 the legend top is correct for the data on the second page.

A web search of https://gis.stackexchange.com/ shows that this was happening back in version 2.18
https://gis.stackexchange.com/questions/265163/qgis-map-composer-changing-legend-position-when-exporting-atlas-as-images

And i am using 


QGIS version
3.16.0-Hannover
QGIS code revision
43b64b13f3
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
db_manager; 
MetaSearch; 
processing


[Layout 1.pdf](https://github.com/qgis/QGIS/files/5478763/Layout.1.pdf)
[altasLegendBug.zip](https://github.com/qgis/QGIS/files/5478750/altasLegendBug.zip)

**Comment by pjshelton** [comment]
A workaround that we are using at our place of work is to create each image twice, side by side..  one will have the legend in the wrong position, the other will have it correct.

**Comment by roya0045** [comment]
If you set the data defined variables for the position x and y, does the behaviour changes?

**Comment by pjshelton** [comment]
No.
![image](https://user-images.githubusercontent.com/39154868/97950174-c97a1380-1de1-11eb-94f1-ccdacea53ec2.png)

**Comment by pjshelton** [comment]
[Layout 2pdf.pdf](https://github.com/qgis/QGIS/files/5479291/Layout.2pdf.pdf)

**Comment by esnyder-rve** [comment]
> Is the auto-resizing option on in those cases?
@roya0045 
Yes

**Comment by esnyder-rve** [comment]
Trying to move this problem along, what is the difference behind the scenes of exporting a single page versus exporting the entire atlas?

**Comment by roya0045** [comment]
Shouldn't be too much, are you saying that doing it one by one works fine?

**Comment by esnyder-rve** [comment]
Yes. This is a very annoying bug. I'd love to help (I have a software engineering degree), but I'm not familiar with the QGIS code base.

**Comment by roya0045** [comment]
Then its the exporting process that finishes before the full rendering is done. This is also apparent with legend expressions. @nyalldawson wanted to look at it at some point as my proposed PR only solves the expression issues.

**Comment by roya0045** [comment]
@esnyder-rve if you have the chance, try with an increase dpi to see if that slows enough the map render to allow the legend rendering before exporting

**Comment by esnyder-rve** [comment]
@roya0045 This is what I tried:
Test 01 - **Failed**:
* Export Resolution: 600 dpi
* Always export as vector
* Export Atlas as PDF

Test 02 - **Failed**:
* Export Resolution: 600 dpi
* Print as raster
* Export Atlas as PDF

Test 03 - **Failed**:
* Export Resolution: 600 dpi
* Print as raster
* Export Atlas as images (png)

Attempting to print to 1200 dpi crashes, so 600 was used instead (It's a 24"x36" map atlas, so I'm not surprised)

**Comment by openSourcerer9000** [comment]
Any update on this in 2021? I'm having the same issue

**Comment by roya0045** [comment]
@openSourcerer9000 

1) no
2) yes in the testing suite and some tests are in python such as src/python/test_qgslayoutatlas.py

**Comment by chleidersdorff** [comment]
@roya0045 it would seem that the legend is always generated from the top left and resized from there. I think the fix would be to tie the rendering of the legend to be dependant on the "Reference Point" or to slow the export redering to include resizing of the legend. I would fix the source code but i dont have the skills yet to do this. It seems to be a long standing issue. it works fine if the legend is referenced from the top left, but that is not always possible.

**Comment by esnyder-rve** [comment]
I think I might know what's going on, but I don't know which source file this would be in to check/investigate (suggestions would be helpful). When rendering the legend, the order needs to be `Render Legend --> Get Size --> Move Legend`. However, when exporting via atlas, I think things happen too soon. Like: `Atlas Next Page --> Render Map --> Render Legend --> Get Size --> Export Page --> Move Legend --> Atlas Next Page`. It is weird that this only occurs when exporting an atlas.

**Comment by openSourcerer9000** [comment]
From my tests I'm pretty positive the issue is that when printing, it's doing `anchor legend -> resize legend -> export page -> next atlas page `, when the order of operations should simply be swapped to `resize  legend -> anchor legend -> export page -> next atlas page `. 

A quick search reveals these files, but being unfamiliar with C++/this repo I'm not exactly sure where the operations would be happening:

src/core/layout/qgslayoutitemlegend.h
src/gui/layout/qgslayoutlegendwidget.cpp

**Comment by esnyder-rve** [comment]
> From my tests I'm pretty positive the issue is that when printing, it's doing anchor legend -> resize legend -> export page -> next atlas page , when the order of operations should simply be swapped to resize legend -> anchor legend -> export page -> next atlas page .

Ah.

> A quick search reveals these files, but being unfamiliar with C++/this repo I'm not exactly sure where the operations would be happening:
src/core/layout/qgslayoutitemlegend.h
src/gui/layout/qgslayoutlegendwidget.cpp

I know it wouldn't be the src/gui file since that's the code for the actual UI widget. I found the legend renderer in src/core/qgslegendrenderer.cpp with this line being of importance: https://github.com/qgis/QGIS/blob/33671c187a18c4978cd0d487fb0d0218f573a13d/src/core/qgslegendrenderer.cpp#L148

Looking at the qgslayoutitemlegend.h, this seems interesting.
https://github.com/qgis/QGIS/blob/33671c187a18c4978cd0d487fb0d0218f573a13d/src/core/layout/qgslayoutitemlegend.h#L80
```cpp
signals:

    /**
     * Emitted to refresh the legend.
     * \since QGIS 3.10
     */
    void refreshLegend();

  private slots:

    /**
     * Handle incoming signal to refresh the legend.
     * \since QGIS 3.10
     */
    void forceRefresh();
```

I wonder if this bug exists in versions pre-3.10?

**Comment by esnyder-rve** [comment]
Hey Nyall @nyalldawson :

While looking into this bug, I noticed you had a few commits that would appear to address this issue (or something around that) 0f93e55fce153e2c573ac95c9d15441542c4a4a6 and 530397c1683cc787ef90bc27e2d958779ed0d754 but this issue still exists.

Any ideas on why the legend is not anchored properly with auto-size, map filter, and non-upper-left anchor when exporting an atlas? This issue doesn't appear when exporting an atlas one page at a time, but only when exporting the entire atlas at once.

**Comment by Kapanther** [comment]
@esnyder-rve  amd @nyalldawson its perfect when exporting one page at a time.. but on the batch export it appears to be using the next page's map settings. or possibly the previous atlas pages map settings.

**Comment by esnyder-rve** [comment]
> but on the batch export it appears to be using the next page's map settings. or possibly the previous atlas pages map settings.

It's using the previous page settings (sometimes).

**Comment by Carettaman** [comment]
Hi everyone ! 
I just want to mention that some one in this tchat found a solution that works completly fine ! I just wanted to rewrite it to let people know. 
Because the legend set it place according to the previous map of the atlas you just have to double the entities of the base layer of your atlas. Then all your maps will be doubled and the second ones generated will be correct ! If you name the exports file with the name the entities of your base layer all the Wrong maps will be overwritten by the good ones on your exit file. (look at the pictures for better comprehension ) :) 
![Qgis2](https://user-images.githubusercontent.com/104248118/220157008-893cd306-f832-4446-b919-d760b70538b2.PNG)
![Qgis](https://user-images.githubusercontent.com/104248118/220157010-176b4ddd-4766-4a01-8ea8-9115acf68363.PNG)

**Comment by esnyder-rve** [comment]
I'm not quite sure why this issue is closed. This issue is still present on latest QGIS (3.34.1), and it seems to be worse than previously with more pages in the atlas having the legend incorrectly located. Again, exporting the atlas one page at a time manually avoids this issue.

**Comment by Geoscope19** [comment]
Hello, The problem had been resolved, but I found it in version 3.36.0 (release candidate) and 3.34.5 LTR ([4b308492](https://github.com/qgis/QGIS/commit/4b308492))

**Comment by bkepl** [comment]
This is still an issue in version 3.38.0.

**Comment by ashleyjing123** [comment]
This is still an issue for Qgis 3.34.2 as well...
Can anyone fix it please?
It occurs exporting in pdf as a bulk as as well as individual. Also in image.

Even though I put the anchor point to bottom left. It doesn't fix it.

<img width="296" height="312" alt="Image" src="https://github.com/user-attachments/assets/6b230fcf-11a6-4469-9413-ed072293b6a2" />

**Comment by agiudiceandrea** [comment]
@ashleyjing123 QGIS 3.34.2 is an old version and it is no longer supported. Please try using tha latest currently supported QGIS versions.
