### ISSUE TITLE
Distance Matrix Crashes on Large Dataset

### ISSUE THREAD

**Issue by Ewan20** [qgis/QGIS#37585]
Crash ID: d137e0129c102d1b4d88ffa3af8977bf55ef2cd4

Stack Trace

PyInit_sip :
PyInit_sip :
PyInit_sip :
PyInit_sip :
PyObject_FastCallKeywords :
PyObject_Call :
PyInit_sip :
PyInit__core :
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_sip :
CPLStringList::empty :
PyInit__core :
QgsProcessingAlgorithm::runPrepared :
QgsProcessingAlgRunnerTask::run :
PyInit__core :
QgsTask::start :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.10.4-A Coru�a
QGIS code revision: 10bc9f2ff2
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
@Ewan20 please link/attach the dataset.

**Comment by gioman** [comment]
Closing for lack of feedback.
