### ISSUE TITLE
Print Composer has issues with duplicated layers

### ISSUE THREAD

**Issue by CoreyBurger** [qgis/QGIS#37580]
**Describe the bug**
The Print Composer is not correctly refreshing the map when the layer order has changed

**How to Reproduce**

Add a layer to a group
Drag that layer below another layer
Observe that the print composer has not updated, even if the main window has

![QGIS-PrintComposerNotUpdatingForLayer](https://user-images.githubusercontent.com/30996781/86503042-e5e83f80-bd5e-11ea-8030-4bde0f5cbb8a.png)

**QGIS and OS versions**

QGIS version | 3.14.0-Pi | QGIS code revision | 9f7028fd23
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | QuickOSM; quick_map_services; db_manager; MetaSearch; processing

**Comment by CoreyBurger** [comment]
So further exploration has discovered the bug:

If you Duplicate the layer, the problem disappears. 
If you drag + duplicate the layer, then it gets drawn in the order of the ORIGINAL layer, which in my case is a group ABOVE the layer

The solution for this is to fix drag+ to duplicate the layer and introduce another shortcut for drag + link symbology

**Comment by CoreyBurger** [comment]
#28674 is the bug for the duplicating layer issue

**Comment by gioman** [comment]
> **How to Reproduce**
> 
> Add a layer to a group
> Drag that layer below another layer
> Observe that the print composer has not updated, even if the main window has

@CoreyBurger did a quick test on master/linux and can't confirm.

**Comment by CoreyBurger** [comment]
@gioman - I wonder if this is a Windows only bug, I've seen that mentioned elsewhere. I lack a Linux desktop machine to test right now, but will do so
