### ISSUE TITLE
Changing layer order in Layout crashes QGIS

### ISSUE THREAD

**Issue by MMcBain** [qgis/QGIS#37596]
**Describe the bug**
I am creating a custom legend by arranging a series of overlapping rectangular shapes and labels. Everything is fine if I do that in order, from bottom to top. But if I try and change the order, QGIS crashes immediately.

**How to Reproduce**

**QGIS and OS versions**

QGIS version | 3.15.0-Master | QGIS code revision | 5936249b72
-- | -- | -- | --
Compiled against Qt | 5.12.8 | Running against Qt | 5.12.8
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.2 (Ubuntu 12.2-4) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Ubuntu 20.04 LTS | This copy of QGIS writes debugging output.
Active python plugins | SRTM-Downloader; batchvectorlayersaver; pointsamplingtool; BulkVectorExport; db_manager; processing; MetaSearch

**Additional context**

**Comment by gioman** [comment]
@MMcBain Please try wtih a new QGIS profile, if the problem persist please attach the offending project.

**Comment by gioman** [comment]
Closing for lack of feedback.
