### ISSUE TITLE
Duplicate layer vs copy/paste layer - cannot edit label position with copy/paste

### ISSUE THREAD

**Issue by CoreyBurger** [qgis/QGIS#37591]
**Describe the bug**
There is a difference between Duplicating a layer and Copy/Pasting a layer when it comes to editing label position. 

**How to Reproduce**
1. Create a duplicate of the layer or copy/paste that same layer
2. When you duplicate a layer, you **can** edit the label position of the new layer
3. If you copy/paste a layer, you **cannot** edit the label position of the new layer

**QGIS and OS versions**

QGIS version | 3.14.0-Pi | QGIS code revision | 9f7028fd23
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | QuickOSM; quick_map_services; db_manager; MetaSearch; processing

**Comment by gioman** [comment]
> If you copy/paste a layer, you **cannot** edit the label position of the new layer

@CoreyBurger did a quick test on QGIS master on Linux and can't confirm.

**Comment by roya0045** [comment]
Tested on 3.14.16, Win 10.

Using a temp/scratch layer. Upon copy pasting the layer with the contextual option (right click) the copied layer were empty copies and had no features. As opposed to the original layer.

**Comment by roya0045** [comment]
Behaviour could be replicated with a shapefile layer, geopackage seem exempt of bugs using copy paste.

**Comment by Pedro-Murteira** [comment]
@CoreyBurger After testing with multiple layers and geometry types, I can't replicate this. (Tested on Win 10, QGIS 3.16.14 and 3.22.1.). Is this fixed?
