### ISSUE TITLE
Crash ID: 4ac1cd906c0309ff7723ac4ace2fd72e11909824

### ISSUE THREAD

**Issue by Biologist98** [qgis/QGIS#37601]
Crash ID: 4ac1cd906c0309ff7723ac4ace2fd72e11909824

Stack Trace

QgsStyleModel::style qgsstylemodel.h:80
QgsStyleProxyModel::QgsStyleProxyModel qgsstylemodel.cpp:677
QgsReadOnlyStyleModel::QgsReadOnlyStyleModel qgsstyleitemslistwidget.cpp:33
QgsStyleItemsListWidget::setStyle qgsstyleitemslistwidget.cpp:144
QgsSymbolsListWidget::QgsSymbolsListWidget qgssymbolslistwidget.cpp:42
QgsSymbolSelectorWidget::layerChanged qgssymbolselectordialog.cpp:533
QtPrivate::FunctorCall,QtPrivate::List,void,void (__cdecl QgsSymbolSelectorWidget::*)(void) __ptr64>::call qobjectdefs_impl.h:134
QtPrivate::FunctionPointer::call,void> qobjectdefs_impl.h:168
QtPrivate::QSlotObject,void>::impl qobjectdefs_impl.h:397
QMetaObject::activate :
QItemSelectionModel::setCurrentIndex :
QAbstractItemView::setCurrentIndex :
QgsSymbolSelectorWidget::QgsSymbolSelectorWidget qgssymbolselectordialog.cpp:306
QgsSingleSymbolRendererWidget::QgsSingleSymbolRendererWidget qgssinglesymbolrendererwidget.cpp:59
QgsSingleSymbolRendererWidget::create qgssinglesymbolrendererwidget.cpp:32
QgsRendererMetadata::createRendererWidget qgsrendererregistry.h:180
QgsRendererPropertiesDialog::rendererChanged qgsrendererpropertiesdialog.cpp:251
QtPrivate::FunctorCall,QtPrivate::List,void,void (__cdecl QgsRendererPropertiesDialog::*)(void) __ptr64>::call qobjectdefs_impl.h:134
QtPrivate::FunctionPointer::call,void> qobjectdefs_impl.h:168
QtPrivate::QSlotObject,void>::impl qobjectdefs_impl.h:397
QMetaObject::activate :
QWidgetLineControl::`default constructor closure' :
QComboBox::setCurrentIndex :
QComboBox::setCurrentIndex :
QgsRendererPropertiesDialog::syncToLayer qgsrendererpropertiesdialog.cpp:384
QgsRendererPropertiesDialog::QgsRendererPropertiesDialog qgsrendererpropertiesdialog.cpp:122
QgsLayerStylingWidget::updateCurrentWidgetLayer qgslayerstylingwidget.cpp:450
QtPrivate::FunctorCall,QtPrivate::List,void,void (__cdecl QgsLayerStylingWidget::*)(void) __ptr64>::call qobjectdefs_impl.h:134
QtPrivate::FunctionPointer::call,void> qobjectdefs_impl.h:168
QtPrivate::QSlotObject,void>::impl qobjectdefs_impl.h:397
QMetaObject::activate :
QListWidgetItem::`default constructor closure' :
QMetaObject::activate :
QItemSelectionModel::setCurrentIndex :
QListWidget::setCurrentRow :
QgsLayerStylingWidget::setLayer qgslayerstylingwidget.cpp:275
QtPrivate::FunctorCall,QtPrivate::List,void,void (__cdecl QgsLayerStylingWidget::*)(QgsMapLayer * __ptr64) __ptr64>::call qobjectdefs_impl.h:134
QtPrivate::FunctionPointer::call,void> qobjectdefs_impl.h:168
QtPrivate::QSlotObject,void>::impl qobjectdefs_impl.h:397
QMetaObject::activate :
QgsMapLayerComboBox::layerChanged moc_qgsmaplayercombobox.cpp:209
QgsMapLayerComboBox::rowsChanged qgsmaplayercombobox.cpp:143
QtPrivate::FunctorCall,QtPrivate::List,void,void (__cdecl QgsMapLayerComboBox::*)(void) __ptr64>::call qobjectdefs_impl.h:134
QtPrivate::FunctionPointer::call,void> qobjectdefs_impl.h:168
QtPrivate::QSlotObject,void>::impl qobjectdefs_impl.h:397
QMetaObject::activate :
QAbstractItemModel::endInsertRows :
QSortFilterProxyModel::insertRows :
QSortFilterProxyModel::sortRole :
QSortFilterProxyModel::`default constructor closure' :
QMetaObject::activate :
QAbstractItemModel::endInsertRows :
QgsMapLayerModel::addLayers qgsmaplayermodel.cpp:182
QtPrivate::FunctorCall,QtPrivate::List const & __ptr64>,void,void (__cdecl QgsMapLayerModel::*)(QList const & __ptr64) __ptr64>::call qobjectdefs_impl.h:134
QtPrivate::FunctionPointer const & __ptr64) __ptr64>::call const & __ptr64>,void> qobjectdefs_impl.h:168
QtPrivate::QSlotObject const & __ptr64) __ptr64,QtPrivate::List const & __ptr64>,void>::impl qobjectdefs_impl.h:397
QMetaObject::activate :
QgsProject::layersAdded moc_qgsproject.cpp:1196
::operator() qgsproject.cpp:403
QtPrivate::FunctorCall,QtPrivate::List const & __ptr64>,void, >::call qobjectdefs_impl.h:128
QtPrivate::Functor,1>::call const & __ptr64>,void> qobjectdefs_impl.h:239
QtPrivate::QFunctorSlotObject,1,QtPrivate::List const & __ptr64>,void>::impl qobjectdefs_impl.h:427
QMetaObject::activate :
QgsMapLayerStore::layersAdded moc_qgsmaplayerstore.cpp:314
QgsMapLayerStore::addMapLayers qgsmaplayerstore.cpp:101
QgsProject::addMapLayers qgsproject.cpp:3257
QgsProject::addMapLayer qgsproject.cpp:3297
meth_QgsProject_addMapLayer sip_corepart4.cpp:141341
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyEval_EvalCodeEx :
PyEval_EvalCode :
PyArena_Free :
PyRun_StringFlags :
PyImport_Import :
PyImport_Import :
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyImport_Import :
PyImport_Import :
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:437
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:437
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1618
WinMain mainwin.cpp:170
__scrt_common_main_seh exe_common.inl:253
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.13.0-Master
QGIS code revision: e9a0c01b21
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.2.0dev
Running against GDAL: 3.2.0dev

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
@Biologist98 please try with a new QGIS profile, also please add all the requested infos:



**Describe the bug**


**How to Reproduce**



**QGIS and OS versions**



**Additional context**
