### ISSUE TITLE
QGIS 3.14 won't launch in WIndows 10

### ISSUE THREAD

**Issue by PolashBanerjee** [qgis/QGIS#37603]
Crash ID: 2626c381b07c52078081617ec91a3de0e062a20d

Stack Trace

QWidget::actions :
QMenu::clear :
QgisApp::refreshProfileMenu :
QMetaObject::activate :
QMetaObject::activate :
QFileSystemWatcher::`default constructor closure' :
QMetaObject::activate :
QFileSystemWatcher::directoryChanged :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QCoreApplication::processEvents :
QgisApp::QgisApp :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.14.0-Pi
QGIS code revision: 9f7028fd23
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
@PolashBanerjee as requested in the ticket template, more information is needed:



**Describe the bug**


**How to Reproduce**



**QGIS and OS versions**



**Additional context**
