### ISSUE TITLE
error importing shapefiles to Oracle with DB Manager

### ISSUE THREAD

**Issue by KeilBZA** [qgis/QGIS#37621]
Hallo,

if i try to import an .shp-Layer to Oracle DB i get this Error.

Is this a bug/issue from QGIS? Or an problem with the DB/DB-Connection?

Fehler: 2
Erzeugung der Datenquelle "KEILFRED"."BVL" gescheitert: 
Oracle-Fehler: Konnte Metadaten nicht einfügen.
SQL: ORA-00932: Inkonsistente Datentypen: MDSYS.SDO_DIM_ARRAY erwartet, CHAR erhalten
Konnte Anweisung nicht ausführen
Fehler: INSERT INTO mdsys.user_sdo_geom_metadata(table_name,column_name,srid,diminfo) VALUES (:a,:bb,:bc,:bd)

Error 2
Creation of data source "KEILFRED"."BDL" failed: 
Oracle error: Could not insert metadata.
SQL: ORA-00932: Inkonsistente Datentypen: MDSYS.SDO_DIM_ARRAY erwartet, CHAR erhalten  **(i set QGIS to english, this line still in german)**
Unable to execute statement
Error: INSERT INTO mdsys.user_sdo_geom_metadata(table_name,column_name,srid,diminfo) VALUES (:a,:bb,:bc,:bd)

I can create and edit tables with QGIS without an SDO_Geometry

**Comment by gioman** [comment]
@KeilBZA it seems to me that the error comes from Oracle, not QGIS.

**Comment by uclaros** [comment]
QGIS version? Oracle version?

**Comment by KeilBZA** [comment]
OGIS 3.10.7 / 3.10.5 / 3.14    Oracle 19.0

**Comment by Simon109i** [comment]
Same problem in my case: 

Oracle version:
Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production
PL/SQL Release 12.2.0.1.0 - Production
"CORE	12.2.0.1.0	Production"
TNS for Linux: Version 12.2.0.1.0 - Production
NLSRTL Version 12.2.0.1.0 - Production

QGis version:

QGIS version 3.6.0-Noosa
QGIS code revision 58734527ab
Compiled against Qt 5.11.2
Running against Qt 5.11.2
Compiled against GDAL/OGR 2.4.0
Running against GDAL/OGR 2.4.0
Compiled against GEOS 3.7.0-CAPI-1.11.0
Running against GEOS 3.7.0-CAPI-1.11.0 673b9939
PostgreSQL Client Version 9.2.4
SpatiaLite Version 4.3.0
QWT Version 6.1.3
QScintilla2 Version 2.10.8
Compiled against PROJ 520
Running against PROJ 5.2.0
