### ISSUE TITLE
Regarding QGIS version 3.14 digitization tool plugins crashed message is reflecting

### ISSUE THREAD

**Issue by shankargan** [qgis/QGIS#37624]
IMPORTANT:

Do NOT use GitHub to post any questions or support requests!
They will be closed immediately and ignored.
Questions should go to the qgis-user mailing list at https://lists.osgeo.org/mailman/listinfo/qgis-user
or other support forums such as https://gis.stackexchange.com/.

GitHub issues are for bug reports and suggestions for new features.

**Comment by gioman** [comment]
@shankargan closing as invalid, pleas file tickets following the requested template


 

**Describe the bug**


**How to Reproduce**



**QGIS and OS versions**



**Additional context**
