### ISSUE TITLE
QgsVectorFileWriter fails to write feature

### ISSUE THREAD

**Issue by ChrisWGeorge** [qgis/QGIS#37629]
**Describe the bug**

Using QgsVectorFileWriter to create an ESRI shapefile with the seqeunce

writer = create(...)
writer.addFeature(...)
del writer

produces an empty shapefile.  (I have no reason to think this is only for ESRI shapefiles, just that this is the only format I have used.)

**How to Reproduce**

1. Start QGIS
2. Open Python Console
3. Show Editor
4. Run the attached script (after adjusting the C:/Users/... shapefile path to something valid)
5. Load my_new_shapefile.shp to check attribute table to see it is empty

[vectest.zip](https://github.com/qgis/QGIS/files/4880075/vectest.zip)

The script, apart from the shapefile path, is a copy of the sript on on https://docs.qgis.org/3.10/en/docs/pyqgis_developer_cookbook/vector.html#creating-vector-layers under **Directly from features**

**QGIS and OS versions**

QGIS version | 3.10.6-A Coruña | QGIS code revision | ec80021f49
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | QSWAT3; remotedebug; db_manager; MetaSearch; processing

**Additional context**

**Comment by troopa81** [comment]
Maybe not duplicate, but it looks close or related to #37386

**Comment by elpaso** [comment]
@troopa81 I can have a look a this issue, unless you are already working on it of course.

**Comment by troopa81** [comment]
@elpaso I'm not working on it, I'm glad if you take care of this.

**Comment by elpaso** [comment]
I believe https://github.com/qgis/QGIS/pull/37667 will also fix this issue, @ChrisWGeorge would you be able to test it and confirm?

**Comment by ChrisWGeorge** [comment]
I am happy to test.  Just installed qgis-full-dev and got
QGIS version 3.15.0-Master QGIS code revision ed000d432c
and the problem wasn't fixed, but I suspect this was too early.

Chris

**Comment by elpaso** [comment]
@ChrisWGeorge  download: https://github.com/qgis/QGIS/suites/889329320/artifacts/10548008 unzip twice and run qgis.exe, or wait until tomorrow.

**Comment by elpaso** [comment]
@ChrisWGeorge forget about what I said, that build has no Python, just wait for tomorrow's nightly build.

**Comment by ChrisWGeorge** [comment]
Tested today and is fixed: many thanks.  You can close #37629 and #37630

**Comment by pklampros** [comment]
Backport for this failed, so it's not in 3.10.10 or 3.14.16:
Master PR: https://github.com/qgis/QGIS/pull/37667
3:10 PR backport: https://github.com/qgis/QGIS/pull/37673
3:14 PR backport: https://github.com/qgis/QGIS/pull/37674
