### ISSUE TITLE
QGIS Form opening python function called twice

### ISSUE THREAD

**Issue by endmax** [qgis/QGIS#37639]
I'm using QGIS 3.10.7 LTR on windows

The python code provided inside the code window or inside an external python file is called twice.
![image](https://user-images.githubusercontent.com/2227603/86732898-0ea75800-c031-11ea-8b96-83cbd9b20feb.png)

Consequently when I need to handle signal on some controls I have multiple calls.
For example:

```
def form_open(dlg, layer, feature):
	QgsMessageLog.logMessage("form_open")
	global myComboBox
	myComboBox= dialog.findChild(QComboBox, "OidZona")
	myComboBox.currentIndexChanged.connect(doSomething)

def doSomething():
	msg = str(myComboBox.currentData())
	QgsMessageLog.logMessage(msg)

```

**Comment by Pedro-Murteira** [comment]
I'm not being able to reproduce this issue on QGIS 3.22.4 and 3.24.0. @endmax Hello, is this issue still reproducible in recent releases?
