### ISSUE TITLE
QGIS 3.2.2 crush report

### ISSUE THREAD

**Issue by vizaam** [qgis/QGIS#37634]
h2. User Feedback

h2. Report Details

*Crash ID*: 2158b01f96452b8cf079fabd6f476862ce1a56f9

*Stack Trace*
<pre>
QDockWidget::toggleViewAction :
QgisApp::removeDockWidget :
QgsPresetSchemeColorRamp::clone :
PyCFunction_FastCallDict :
PyObject_GenericGetAttr :
PyEval_EvalFrameDefault :
PyObject_GenericGetAttr :
PyEval_EvalFrameDefault :
PyObject_GenericGetAttr :
PyEval_EvalFrameDefault :
PyErr_Occurred :
PyEval_EvalCode :
PyArena_Free :
PyRun_StringFlags :
instance :
instance :
QgsPluginRegistry::unloadAll :
QgisApp::saveWindowState :
QMetaObject::activate :
QCoreApplicationPrivate::execCleanup :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.2.2-Bonn
QGIS code revision: commit:26842169e9
Compiled against Qt: 5.9.2
Running against Qt: 5.9.2
Compiled against GDAL: 2.2.4
Running against GDAL: 2.2.4

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by gioman** [comment]
>  QGIS Version: 3.2.2-Bonn

@vizaam too old, you must upgrade to 3.10 or 3.14

Moreover you must add the requested infos:



**Describe the bug**


**How to Reproduce**



**QGIS and OS versions**



**Additional context**

**Comment by Gustry** [comment]
It's was the "Crash on exit", it was already been fixed a long time ago. Just upgrade your QGIS to 3.10 now
