### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Gilson-Rangel** [qgis/QGIS#37648]
I was working so this happened.

Crash ID: 04d7d82d47003247e818192529e30b64a55e679e

Stack Trace

QgsGeometry::closestVertex qgsgeometry.cpp:388
QgsPointLocator_VisitorNearestVertex::visitData qgspointlocator.cpp:117
Index::~Index :
Index::~Index :
QgsPointLocator::nearestVertex qgspointlocator.cpp:1170
QgsVertexTool::layerVerticesSnappedToPoint qgsvertextool.cpp:1837
QgsVertexTool::deleteVertex qgsvertextool.cpp:2251
QgsVertexTool::deleteVertexEditorSelection qgsvertextool.cpp:1560
QMetaObject::activate :
QgsVertexEditor::keyPressEvent qgsvertexeditor.cpp:457
QWidget::event :
QDockWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:437
QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:437
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processKeyEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1618
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.14.0-Pi
QGIS code revision: 9f7028fd23
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by gioman** [comment]
@Gilson-Rangel 

please try a new QGIS profile.

If the problem persist:



**Describe the bug**


**How to Reproduce**



**QGIS and OS versions**



**Additional context**

**Comment by gioman** [comment]
Closing for lack of feedback.
