### ISSUE TITLE
How QGIS' cumulative count cut algorithm works (faster version)?

### ISSUE THREAD

**Issue by ekarem** [qgis/QGIS#37649]
Hello,

I'm working on a GIS tool project and I need to implement a fast cumulative count cut algorithm. I wonder how QGIS' faster version of the cumulative count cut algorithm works?

What is the trick to make it faster?

**Comment by alexbruy** [comment]
GitHub is used for bugreports and feature requests. Please ask questions like this one using other support channels e.g. stackexchange, IRC or mailing lists.
