### ISSUE TITLE
Map array isn't working with calculated datas

### ISSUE THREAD

**Issue by M-Rick** [qgis/QGIS#37658]
**Describe the bug**
When trying to create a new map array, if datas are calculated from another expression, the map() command isn't working.

**How to Reproduce**

Open the expression builder.

Create a new map like this one.
`map( '1','AA','2','BB','3','CC','4','DD','5','EE' )`
QGIS will return
`{ '1': 'AA', '2': 'BB', '3': 'CC', '4': 'DD', '5': 'EE' }`

![Capture d’écran 2020-07-07 à 21 14 14](https://user-images.githubusercontent.com/2520948/86831163-db97af80-c096-11ea-8c4d-d92a454203bf.png)

But with any of the following examples it won't work.

**With a string**
![Capture d’écran 2020-07-07 à 21 32 07](https://user-images.githubusercontent.com/2520948/86833126-65e11300-c099-11ea-9962-2d596dcbcc39.png)

![Capture d’écran 2020-07-07 à 21 32 19](https://user-images.githubusercontent.com/2520948/86833142-6b3e5d80-c099-11ea-9037-9a338ca945eb.png)

![Capture d’écran 2020-07-07 à 21 24 47](https://user-images.githubusercontent.com/2520948/86832351-5ca37680-c098-11ea-87d7-439068a6b8af.png)

![Capture d’écran 2020-07-07 à 21 26 08](https://user-images.githubusercontent.com/2520948/86832523-91173280-c098-11ea-8e92-6f4a84cdd3b0.png)

**From a simple array**
![Capture d’écran 2020-07-07 à 21 20 33](https://user-images.githubusercontent.com/2520948/86831907-ccfdc800-c097-11ea-85b4-b3f6b0e810ce.png)

![Capture d’écran 2020-07-07 à 21 20 49](https://user-images.githubusercontent.com/2520948/86831972-de46d480-c097-11ea-9d61-effc94ed2fa1.png)

**QGIS and OS versions**

Issue present in Windows and Linux versions as well.

Version de QGIS | 3.10.7-A Coruña | Révision du code | 7b4ca4c8d0
-- | -- | -- | --
Compilé avec Qt | 5.12.3 | Utilisant Qt | 5.12.3
Compilé avec GDAL/OGR | 2.4.1 | Utilisé avec GDAL/OGR | 2.4.1
Compilé avec GEOS | 3.7.2-CAPI-1.11.2 | Utilisé avec GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compilé avec SQLite | 3.28.0 | Fonctionne avec SQLite | 3.28.0
Version du client PostgreSQL | 11.3 | Version de SpatiaLite | 4.3.0a
Version de QWT | 6.1.4 | Version de QScintilla2 | 2.11.1
Compilé avec PROJ | 5.2.0 | Fonctionne avec PROJ | Rel. 5.2.0, September 15th, 2018
Version de l'OS | macOS Mojave (10.14)
Extensions Python actives | SpreadsheetLayers; QuickOSM; qfieldsync; Mergin; processing; db_manager; MetaSearch

**Additional context**

**Comment by agiudiceandrea** [comment]
Hi @M-Rick It seems you cannot pass a single string to map(), but pairs of parameters.
The sybtax is `map(key1,value1,key2,value2…)`

If you want to create a map using a single string you need to use `json_to_map(string)` or `hstore_to_map(string)`.

**Comment by M-Rick** [comment]
> Hi @M-Rick It seems you cannot pass a single string to map(), but pairs of parameters.
> The sybtax is `map(key1,value1,key2,value2…)`
> 
> If you want to create a map using a single string you need to use `json_to_map(string)` or `hstore_to_map(string)`.

Hi Andrea
But if you look well at my screenshots, this string `'1','AA','2','BB','3','CC','4','DD','5','EE'` works. And all the expressions following are exactly reproducing this exact string. This is why it is strange.

**Comment by agiudiceandrea** [comment]
This '1','AA','2','BB','3','CC','4','DD','5','EE' is not a single string but 10 string separated by a comma, i.e. 10 string parameters: they are correctly processed by the "map" function.
The output of the "replace" function is a single string. A single string, whatever it contains, cannot be processed by the "map" function.
Try instead to to use json_to_map(string) or hstore_to_map(string), e.g.:
hstore_to_map('a=>b, c=>d')
json_to_map('{"a":"b", "c":"d"}')

**Comment by M-Rick** [comment]
> This '1','AA','2','BB','3','CC','4','DD','5','EE' is not a single string but 10 string separated by a comma, i.e. 10 string parameters: they are correctly processed by the "map" function.

But an array create individual strings separated by a coma, right?
So, this should work `map( array( '1','AA','2','BB','3','CC','4','DD','5','EE' ) )` but it doesn't.

> The output of the "replace" function (or the "array_to_string" function) is a single string. A single string, whatever it contains, cannot be processed by the "map" function.
> Try instead to to use json_to_map(string) or hstore_to_map(string), e.g.:
> hstore_to_map('a=>b, c=>d')
> json_to_map('{"a":"b", "c":"d"}')

If I use `json_to_map( to_json( array( '1','AA','2','BB','3','CC','4','DD','5','EE' ) ) )` it does work since QGIS is returning me `[ '1', 'AA', '2', 'BB', '3', 'CC', '4', 'DD', '5', 'EE' ]` So until now, everything seems ok.

But when I want to use map_get( ) function on this, if I follow the example from QGIS 

> map_get(map('1','un','2','deux'),'2') → 'deux'

It should work with the previous result that created me a map.

As a result, when writing `map_get( json_to_map( to_json( array( '1','AA','2','BB','3','CC','4','DD','5','EE' ) ) ), '3')` I should get 'CC'. But it doesn't. QGIS says it couldn't create the map.

**Comment by agiudiceandrea** [comment]
> But an array creates individual strings separated by a coma, right?
No. An array is an array.

> But this `map( '1','AA','2','BB','3','CC','4','DD','5','EE' )` works.

This is the correct way. '1' and 'AA' and '2' and so on are strings passed as parameters for the function. The map function needs at least two parameter to properly create a map object.

> If I use `json_to_map( to_json( array( '1','AA','2','BB','3','CC','4','DD','5','EE' ) ) )` it does work since QGIS is returning me `[ '1', 'AA', '2', 'BB', '3', 'CC', '4', 'DD', '5', 'EE' ]` So until now, everything seems ok.

It's not ok. `[ '1', 'AA', '2', 'BB', '3', 'CC', '4', 'DD', '5', 'EE' ]` represents an array in this context, not a map. "json_to_map" function is only an alias of "from_json" function; it loads a json formatted string; if the json formatted string represents an array, like in your case, it returns an array, not a map.

As I already wrote, in order to create a map object from a single string, you need to format such string as a json format string representing a map like `'{"a":"b", "c":"d"}'`, or as a hstore formatted string representing a map like `'a=>b, c=>d'` and pass this single string to the function json_to_map or hstore_to_map respectively.

Alternatively, you could also use the function "evaluate" with a single string representing the expression you want to evaluate, e.g. `eval('map(\'a\',\'b\')')`

To be more clear, if you have a string like `'1,AA,2,BB,3,CC,4,DD,5,EE'` and want to to convert it to a map object, assuming the elements in the string are in the form key,value,key,value... you need to convert it e.g. to the hstore formatted string `'1=>AA,2=>BB,3=>CC,4=>DD,5=>EE'` using `regexp_replace('1,AA,2,BB,3,CC,4,DD,5,EE', ',([^,]+(?:,|$))', '=>\\1')` the then let hstore_to_map parse that string in order to create a map object:
`hstore_to_map(regexp_replace('1,AA,2,BB,3,CC,4,DD,5,EE', ',([^,]+(?:,|$))', '=>\\1'))`

I hope it is clear also to you now that this is not a bug.

**Comment by M-Rick** [comment]
Hello Andrea

> > But an array creates individual strings separated by a coma, right?
> 
> No. An array is an array.
> 
> > But this `map( '1','AA','2','BB','3','CC','4','DD','5','EE' )` works.
> 
> This is the correct way. '1' and 'AA' and '2' and so on are strings passed as parameters for the function. The "map" function needs at least two parameter to properly create a map object.
> 
> > If I use `json_to_map( to_json( array( '1','AA','2','BB','3','CC','4','DD','5','EE' ) ) )` it does work since QGIS is returning me `[ '1', 'AA', '2', 'BB', '3', 'CC', '4', 'DD', '5', 'EE' ]` So until now, everything seems ok.
> 
> It's not ok. `[ '1', 'AA', '2', 'BB', '3', 'CC', '4', 'DD', '5', 'EE' ]` represents an array in this context (see the square brackets), not a map. "json_to_map" function is only an alias of "from_json" function; it loads a json formatted string; if the json formatted string represents an array, like in your case, it returns an array, not a map.
> 
> As I already wrote, in order to create a map object from a single string, you need to format such string as a json format string representing a map like `'{"a":"b", "c":"d"}'`, or as a hstore formatted string representing a map like `'a=>b, c=>d'` and pass this single string to the function json_to_map or hstore_to_map respectively.
> 
> Alternatively, you could also use the function "evaluate" with a single string representing the expression you want to evaluate, e.g. `eval('map(\'a\',\'b\')')`
> 
> To be more clear, if you have a string like `'1,AA,2,BB,3,CC,4,DD,5,EE'` and want to to convert it to a map object, assuming the elements in the string are in the form key,value,key,value... you need to convert it e.g. to the hstore formatted string `'1=>AA,2=>BB,3=>CC,4=>DD,5=>EE'` using `regexp_replace('1,AA,2,BB,3,CC,4,DD,5,EE', ',([^,]+(?:,|$))', '=>\\1')` then let hstore_to_map parse that string in order to create a map object:
> `hstore_to_map(regexp_replace('1,AA,2,BB,3,CC,4,DD,5,EE', ',([^,]+(?:,|$))', '=>\\1'))`
> 
> or using "eval":
> `eval(concat('map(\'',replace('1,AA,2,BB,3,CC,4,DD,5,EE',',','\',\''),'\')'))`
> 
> I hope it is clear also to you now that this is not a bug.

Thank you for your answer.
I tried to understand your explanations with some tests.
It did work.
Thank you.
