### ISSUE TITLE
Alle Plugins werden nicht gezeigt

### ISSUE THREAD

**Issue by Jassin87** [qgis/QGIS#37651]
IMPORTANT:

If the issue concerns a third party plugin (downloaded with the plugin manager) then it can't be fixed by the QGIS team.
Please raise your issue in the dedicated bug tracker for that specific plugin (as listed in the plugin's description)

Tickets created here will be closed.

**Comment by gioman** [comment]
@Jassin87 please file tickets (subject and description) in English, also the ticket was missing of all the necessary details.
