### ISSUE TITLE
$ID as default on feature creation stopped working in QGIS 3.14

### ISSUE THREAD

**Issue by meyerlor** [qgis/QGIS#37656]
**Describe the bug**
Since I upgraded to QGIS 3.14, the $ID as default in my ID field does not work - it always gives an ID "0" when i create a new feature

**How to Reproduce**
1. Go to Layer Properties -> Attributes Form
2. Select the Field where the ID should be filled in
3. Set "$id" as default value
![grafik](https://user-images.githubusercontent.com/15894401/86792050-63b39000-c06a-11ea-99aa-242b83963fdb.png)

4. Create (digitze) new feature 
5. Values still empty (Fields Test1 = Text, Test2 = integer)
![grafik](https://user-images.githubusercontent.com/15894401/86792300-a2e1e100-c06a-11ea-8db1-a39ca3f64d6a.png)

**QGIS and OS versions**

QGIS: 3.14
Windows 10

**Comment by gioman** [comment]
Confirmed on Linux/QGIS master.

**Comment by meyerlor** [comment]
whats the status of this bug?

**Comment by meyerlor** [comment]
> 
> 
> Confirmed on Linux/QGIS master.

as it is still not working, do you have a workaround? how do you fill in an autoincremented ID-like number to your new items? i'm glad for any hints!

**Comment by gioman** [comment]
> as it is still not working, do you have a workaround? how do you fill in an autoincremented ID-like number to your new items? i'm glad for any hints!

@meyerlor on second thoughts... this has never worked (as one would expect: the point is that "$id" > "Returns the feature id of the current row." and the row you are creating do not exist before saving edits). The expression you mus use is

`maximum("yourfieldname") + 1`

**Comment by meyerlor** [comment]
ok, well then i do it like  you suggested! thanks for clarifying this!
