### ISSUE TITLE
While switching visibility of historic raster image QGIS crashed...

### ISSUE THREAD

**Issue by uwerder1** [qgis/QGIS#37661]
## User Feedback

I had an historic image invisible and switched the visibility on again. I switched between QGIS and the plot template manager and then QGIS crashed!

## Report Details

**Crash ID**: [c0ab8a07ecc79b08768a9e06d71571f8d3992163](https://github.com/qgis/QGIS/search?q=c0ab8a07ecc79b08768a9e06d71571f8d3992163&type=Issues)

**Stack Trace**
<pre>
MoveSmall memcpy.asm:432
VSICreateCachedFile :
GDALRegister_Terragen :
GDALRegister_Terragen :
GDALRegister_Terragen :
GDALRegister_Terragen :
GDALRegister_GTiff :
GDALRasterBand::GetLockedBlockRef :
GDALRasterBand::IRasterIO :
GDALRegister_GTiff :
GDALRasterBand::RasterIO :
QgsGdalProviderBase::gdalRasterIO qgsgdalproviderbase.cpp:299
QgsGdalProvider::readBlock qgsgdalprovider.cpp:911
QgsGdalProvider::block qgsgdalprovider.cpp:672
QgsSingleBandGrayRenderer::block qgssinglebandgrayrenderer.cpp:91
QgsBrightnessContrastFilter::block qgsbrightnesscontrastfilter.cpp:118
QgsHueSaturationFilter::block qgshuesaturationfilter.cpp:123
QgsRasterResampleFilter::block qgsrasterresamplefilter.cpp:162
QgsRasterProjector::block qgsrasterprojector.cpp:885
QgsRasterIterator::readNextRasterPartInternal qgsrasteriterator.cpp:130
QgsRasterDrawer::draw qgsrasterdrawer.cpp:60
QgsRasterLayerRenderer::render qgsrasterlayerrenderer.cpp:272
QgsMapRendererCustomPainterJob::doRender qgsmaprenderercustompainterjob.cpp:316
QgsMapRendererCustomPainterJob::staticRender qgsmaprenderercustompainterjob.cpp:264
QtConcurrent::RunFunctionTask<void>::run qtconcurrentrunbase.h:136
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.12.3-Bucure?ti
QGIS code revision: 8234261527
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment]
>  QGIS Version: 3.12.3-Bucure?ti

@uwerder1 too old, update to 3.14.0 and try again.

If the problem persist try with a new QGIS profile, no 3rd party plugins installed.

If it still persist please attach detailed steps (and data if necessary) that lead to the crash.

**Comment by gioman** [comment]
Closing for lack of feedback.
