### ISSUE TITLE
QGIS crashes on exit

### ISSUE THREAD

**Issue by grantboxer** [qgis/QGIS#37660]
## User Feedback

Crashes on shut down of QGIS

## Report Details

**Crash ID**: [c738d67ac4b2b09ecfaf023db0d7735989633a3d](https://github.com/qgis/QGIS/search?q=c738d67ac4b2b09ecfaf023db0d7735989633a3d&type=Issues)

**Stack Trace**
<pre>
QgsProcessingToolboxModel::addProvider qgsprocessingtoolboxmodel.cpp:276
QgsProcessingToolboxModel::rebuild qgsprocessingtoolboxmodel.cpp:150
QMetaObject::activate :
QgsProcessingRegistry::providerRemoved moc_qgsprocessingregistry.cpp:173
QgsProcessingRegistry::removeProvider qgsprocessingregistry.cpp:126
meth_QgsProcessingRegistry_removeProvider sip_corepart1.cpp:282596
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyEval_EvalCodeEx :
PyEval_EvalCode :
PyArena_Free :
PyRun_StringFlags :
QgsPythonUtilsImpl::evalString qgspythonutilsimpl.cpp:529
QgsPythonUtilsImpl::unloadPlugin qgspythonutilsimpl.cpp:648
QgsPluginRegistry::unloadAll qgspluginregistry.cpp:193
QgisApp::saveWindowState qgisapp.cpp:5103
QMetaObject::activate :
QCoreApplicationPrivate::execCleanup :
QCoreApplication::exec :
main main.cpp:1618
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.14.0-Pi
QGIS code revision: 9f7028fd23
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment]
@grantboxer try with a new QGIS profile, no 3rd party plugins installed.

**Comment by gioman** [comment]
Closing for lack of feedback.
