### ISSUE TITLE
QGIS crashes with google map tiles.

### ISSUE THREAD

**Issue by jhpark16** [qgis/QGIS#37665]
**Describe the bug**

QGIS struggled with xyz google satellite map tile due to network delay. Although I did not use it, QGIS crashed in about a minute. The bug is not present in QGIS-OSGeo4W-3.12.2-2-Setup-x86_64.exe. I believe the bug was introduced in 3.12.3.X.

**How to Reproduce**
QGIS is not stable with xyz google tiles. QGIS operates for a while and then crashes. I used
https://mt1.google.com/vt/lyrs=s&x={x}&y={y}&z={z}

Report Details
Crash ID: 86d32fffada71dc4069a25f6eb80e5479a7c090b

Stack Trace

memcpy_repmovs memcpy.asm:115
QgsWmsProvider::readBlock qgswmsprovider.cpp:925
QgsRasterDataProvider::block qgsrasterdataprovider.cpp:201
QgsSingleBandColorDataRenderer::block qgssinglebandcolordatarenderer.cpp:62
QgsBrightnessContrastFilter::block qgsbrightnesscontrastfilter.cpp:118
QgsHueSaturationFilter::block qgshuesaturationfilter.cpp:123
QgsRasterResampleFilter::block qgsrasterresamplefilter.cpp:162
QgsRasterProjector::block qgsrasterprojector.cpp:810
QgsRasterIterator::readNextRasterPartInternal qgsrasteriterator.cpp:130
QgsRasterDrawer::draw qgsrasterdrawer.cpp:60
QgsRasterLayerRendererFeedback::onNewData qgsrasterlayerrenderer.cpp:60
QgsWmsProvider::draw qgswmsprovider.cpp:874
QgsWmsProvider::readBlock qgswmsprovider.cpp:904
QgsRasterDataProvider::block qgsrasterdataprovider.cpp:201
QgsSingleBandColorDataRenderer::block qgssinglebandcolordatarenderer.cpp:62
QgsBrightnessContrastFilter::block qgsbrightnesscontrastfilter.cpp:118
QgsHueSaturationFilter::block qgshuesaturationfilter.cpp:123
QgsRasterResampleFilter::block qgsrasterresamplefilter.cpp:162
QgsRasterProjector::block qgsrasterprojector.cpp:810
QgsRasterIterator::readNextRasterPartInternal qgsrasteriterator.cpp:130
QgsRasterDrawer::draw qgsrasterdrawer.cpp:60
QgsRasterLayerRenderer::render qgsrasterlayerrenderer.cpp:270
QgsMapRendererCustomPainterJob::doRender qgsmaprenderercustompainterjob.cpp:312
QgsMapRendererCustomPainterJob::staticRender qgsmaprenderercustompainterjob.cpp:261
QtConcurrent::RunFunctionTask::run qtconcurrentrunbase.h:136
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

**QGIS and OS versions**
QGIS Info
QGIS Version: 3.10.7-A Coru�a
QGIS code revision: 7b4ca4c8d0
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Additional context**

**Comment by gioman** [comment]
> QGIS is not stable with xyz google tiles. QGIS operates for a while and then crashes. I used
> [https://mt1.google.com/vt/lyrs=s&x={x}&y={y}&z={z}](https://mt1.google.com/vt/lyrs=s&x=%7Bx%7D&y=%7By%7D&z=%7Bz%7D)

@jhpark16 so the steps to follow are:

add a the layer from  https://mt1.google.com/vt/lyrs=s&x={x}&y={y}&z={z} in an empty project and wait?

**Comment by jhpark16** [comment]
Hi Giovanni,

Try to open the attached qgis file. QGIS could not render a small scale
google satellite map. QGIS-OSGeo4W-3.12.2-2-Setup-x86_64.exe was OK with
this file. I think the problem was introduced with QGIS 3.12.3. Thanks.

Cheers,
Jungho

**Comment by gioman** [comment]
> Try to open the attached qgis file

@jhpark16 there is no .qgs file attached to this ticket.

**Comment by jhpark16** [comment]
Hi Giovanni,

I am sorry. I was not familiar with this system. I just replied to the message with an attachment but the reply did not have the attachment. Here is the file. Thank you for your help.

[BACH_RC_Test4.zip](https://github.com/qgis/QGIS/files/4900382/BACH_RC_Test4.zip)

**Comment by gioman** [comment]
> Try to open the attached qgis file. QGIS could not render a small scale google satellite map. QGIS-OSGeo4W-3.12.2-2-Setup-x86_64.exe was OK with this file. I

@jhpark16 I just tried both on QGIS master and as well as QGIS-OSGeo4W-3.12.2-2-Setup-x86_64.exe, it the same.

The issue is that your project is in EPSG 2193 which is  not  global CRS, but the initial extent of the project is global, so you are asking QGIS to download and reproject a lot of data... and it takes a lot of time (by the way, no crashes here) or ultimately fails. If you switch the project CRS to 3857 or 4326 the tile layer renders immediately.

**Comment by gioman** [comment]
Closing for lack of feedback.
