### ISSUE TITLE
n:m relations with multiple end-points

### ISSUE THREAD

**Issue by andreasneumann** [qgis/QGIS#37675]
**Feature description.**
Consider the following table structure:

![image](https://user-images.githubusercontent.com/884476/86902606-7aabbe00-c10e-11ea-93ba-5ff471c82320.png)

Linking from trails | pipes | buildings to the cooperative works fine, but in the opposite direction only one relation reference widgets can be used, either to trails, or pipes or buildings.

Here we would like to be able to use the same relation three times but specify different end points each time to trails, pipes or buildings.

Currently, I can place the relation widget three times, but they are kind of "linked", when I change them to trails as end points, all three widgets will have the same endpoint.

cc @m-kuhn

**Comment by signedav** [comment]
Just to ensure I understood everything right:
When you add an entry on the relation editor widget in cooperative. Should it create only a connection between cooperative and one of the trails | pipes | buildings? Means in this entry of the `link_table` two fks stay emtpy? Is this correct? 
Is this design mainly to avoid having 3 link_tables?

> Currently, I can place the relation widget three times, but they are kind of "linked", when I change them to trails as end points, all three widgets will have the same endpoint.

It's the same with the fields. You make a widget configuration for one field - no matter how many times you display it. Do you think it would be interesting to have different configurations for the every fields instance as well?

**Comment by andreasneumann** [comment]
Yes, you understood that correctly. One link table for multiple connections. This data structure is generated by ili2db / QGIS ModelBaker when you use class inheritance and the smart2inheritance approach.

As an example data model you can use http://geo.so.ch/models/ALW/SO_ALW_Strukturverbesserungen_20190912.ili (note that this model doesn't correspond with my fictive structure mentioned in this ticket, but it is very similar)

Here is the ili2pg command that I used:

```
java -jar /usr/local/ili2pg-4.3.1/ili2pg.jar \
--dbschema alw_strukturverbesserungen --models SO_ALW_Strukturverbesserungen_20190912 --modeldir 'http://models.geo.admin.ch/;http://geo.so.ch/models;' \
--defaultSrsCode 2056 --strokeArcs --createGeomIdx --createFk --createFkIdx --createEnumTabs --beautifyEnumDispName --createMetaInfo --createUnique --createNumChecks --nameByTopic \
--coalesceMultiLine --coalesceMultiSurface --smart2Inheritance \
--createscript alw_strukturverbesserungen_edit.sql
```

There is an abstract class called "Raeumliches_Element" and several derived classes that extend this abstract class, like "Wegebau_Linie", "Seilbahn_Linie", etc. - There is a n:m ASSOCIATION (relation) named "Genossenschaft_Element" with one single link table for all classes between the derived classes and the "Genossenschaft".

Now, on the side of the "derived classes", ModelBaker creates all the necessary relations, but on the other side, there is just one relation between the link table and the "Genossenschaft". And this can only be configured once, not multiple times for each derived class.

Does this clarify the situation?

**Comment by andreasneumann** [comment]
I'm reopening the ticket here because I discovered a follow-up problem:

Now that the relation can be used several times, we need to be able to override the title of the relation reference widget. We need an additional configuration option here - something like shown in the following two screenshots:

![image](https://user-images.githubusercontent.com/884476/92562382-2c35af80-f276-11ea-9536-18cbfc31ee9b.png)

![image](https://user-images.githubusercontent.com/884476/92562542-6dc65a80-f276-11ea-861e-cac09b6ec6f3.png)

**Comment by andreasneumann** [comment]
Other than that, it seems to work fine!

**Comment by signedav** [comment]
This makes sense. It would be kind of an alias of the relation widget instance. While we had aliases per field (not per widget) I think it would be more a widget setting than an alias :thinking: With fallback relation-name. I'll have to check.

**Comment by signedav** [comment]
Just mentioning this work around:
![image](https://user-images.githubusercontent.com/28384354/92564563-a7e52b80-f279-11ea-9fb8-86658238067a.png)

When you define group boxes containing the relation editor widgets and disable the "showLabel" on the realtion editors it looks like this:
![image](https://user-images.githubusercontent.com/28384354/92564442-72d8d900-f279-11ea-88b7-5a4ea87f72c4.png)

**Comment by andreasneumann** [comment]
> Just mentioning this work around:

Right - this is indeed a workaround. Forgot about that.

It is at the expense of a bit of vertical screen space (the workaround needs a bit more vertical space), but it would work ok.

Thanks for mentioning it.

**Comment by signedav** [comment]
Anyway it would be nicer to have the labels. I'll check if it's an easy thing.
