### ISSUE TITLE
QgsMapLayerComboBox doesn't show layers on QGIS 3.14

### ISSUE THREAD

**Issue by romariocarvalhoneto** [qgis/QGIS#37686]
**Describe the bug**
 It is not a plugin issue. The QgsMapLayerComboBox doesn't show layers on QGIS 3.14. It works on the previous versions of QGIS. 
***
**How to Reproduce**

QgsMapLayerComboBox will not display any layer as reported here with screenshots:
https://github.com/romariocarvalhoneto/Weighted-Multi-Criteria-Analysis---WMCA/issues/5#issue-647074618
***
**QGIS and OS versions**
Works on the previous versions o QGIS. Don't work specifically on version 3.14.
***

**Additional context**

**Comment by bellanz80** [comment]
Confirm.

**Comment by nyalldawson** [comment]
Can you share sample code which demonstrates this issue? This widget is used everywhere in qgis, and there's many unit tests covering it.

**Comment by nyalldawson** [comment]
This is as downstream plugin issue - see comment on referenced bug report
