### ISSUE TITLE
Crash when labelling in orthographic projection

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#37688]
**Describe the bug**
QGIS crashes when I enable labelling in my project that uses an orthographic projection.

**How to Reproduce**

1. Grab [crash.qgz.gz](https://github.com/qgis/QGIS/files/4892204/crash.qgz.gz)
2. Enable labelling for the layer, simply switch from "no labels" to "single labels"
3. QGIS crashes with:

```
qgis: MonotoneChainBuilder.cpp:77: static std::size_t geos::index::chain::MonotoneChainBuilder::findChainEnd(const geos::geom::CoordinateSequence&, std::size_t): Assertion `start < npts' failed.
Aborted (core dumped)

```

**QGIS and OS versions**

QGIS version | 3.15.0-Master | QGIS code revision | a0c3f6f476
-- | -- | -- | --
Compiled against Qt | 5.15.0 | Running against Qt | 5.15.0
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.32.3 | Running against SQLite | 3.32.3
PostgreSQL Client Version | 12.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.5 | QScintilla2 Version | 2.11.5
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Arch Linux
Active python plugins | Qgis2threejs; quick_map_services; QuickWKT; MemoryLayerSaver; timemanager; QuickOSM; vector_tiles_reader; GlobeBuilder; db_manager; processing

**Comment by bellanz80** [comment]
I confirm , whit your Crash.qgz.
but, which EPSG is the project?
My QGIs not recognize the system.

![image](https://user-images.githubusercontent.com/38449926/86952526-bfd4ed80-c118-11ea-8f68-f8f56e3cdf71.png)

**Comment by gioman** [comment]
Confirmed also on QGIS master on Ubuntu 18.04.

**Comment by kannes** [comment]
The CRS has no assigned EPSG code, it is a custom orthographic projection.

Thanks for testing!
