### ISSUE TITLE
Display expression does not show anything if one of the fields is empty

### ISSUE THREAD

**Issue by saberraz** [qgis/QGIS#37701]
I have created an expression for Display Name based on multiple fields,  using  ||  to concatenate the texts. If the fields are not NULL, it displays the expression correctly. But if one or some of the fields are empty, it returns no string. But if I use + for concatenation, it all works.

I suggest to have the behaviour of  ||  same as +, as it more widely used to concatenate texts.

**Comment by andreasneumann** [comment]
Hi @saberraz - this was already discussed at length. We want to align the behavior with SQL.

There are alternative functions concat() and coalesce() which you can use to concatenate string without having to worry about NULL values.

**Comment by andreasneumann** [comment]
I think the idea of QGIS expressions is to always align with SQL behavior if there is an equivalent, even if it has some down sides.

**Comment by saberraz** [comment]
Thanks @andreasneumann it makes perfect sense.
