### ISSUE TITLE
Make more buttons in relation editor configurable

### ISSUE THREAD

**Issue by andreasneumann** [qgis/QGIS#37718]
**Feature description.**
It is suggested to make most (all?) buttons configurable (show | don't show) in the relation editor widget:

![image](https://user-images.githubusercontent.com/884476/87062333-36ebae00-c20d-11ea-8a9a-57197ae5ede0.png)

![image](https://user-images.githubusercontent.com/884476/87062512-6ac6d380-c20d-11ea-8407-cc30c35d70df.png)

This includes:
- Add child feature (important, as in some projects we only want to allow to link/unlink existing features)
- duplicate child feature
- delete child feature
- zoom to child feature

**Comment by andreasneumann** [comment]
I'm just testing this and something seems to be odd with
- add child feature
- zoom to child feature

See my configuration:
![image](https://user-images.githubusercontent.com/884476/87689239-44aeaf80-c788-11ea-92b1-99dcbeed10df.png)

and how it is displayed:
![image](https://user-images.githubusercontent.com/884476/87689500-90f9ef80-c788-11ea-883c-ed0a22676941.png)

**Comment by andreasneumann** [comment]
Correction:
Add child feature seems to be ok. It is correctly hidden with my configuration. I mixed this up with "Add Polygon|Linestring|Point" feature.

For the latter, there is no way to hide it yet - right?

Could we also make this configurable?

**Comment by signedav** [comment]
Note: `mZoomToFeatureButton` is set to visible not only according the settings but on `QgsRelationEditorWidget::updateButtons()` (on setting buttons to enabled etc.) and on `QgsRelationEditorWidget::setRelations` according if the layers are spatial. So it overwrites the config. Maybe I can fix that within the implementation of #37675

**Comment by andreasneumann** [comment]
@signedav or @3nids - any update on this? The "Zoom to child feature" is still displayed when I disable it in the configuration.
