### ISSUE TITLE
Missing Edit button in embedded child layer forms

### ISSUE THREAD

**Issue by dd-a** [qgis/QGIS#37712]
Description:

In QGis 3.14 (and probably 3.12 as well), when working with forms and layer relations, the form of the child layer within the parent form does not have the edit button (yellow pen) by default.  To make it appear it is necessary to collapse the child-form and expand it again.  See the joined image.  

![missing edit button](https://user-images.githubusercontent.com/6814394/87038124-989c2000-c1ed-11ea-9135-3cd13519724c.png)

This is very puzzling for new users who can't find where to add a new entity.

Version de QGIS | 3.14.0-Pi | Révision du code | 9f7028fd23
-- | -- | -- | --
Compilé avec Qt | 5.12.3 | Utilisant Qt | 5.12.3
Compilé avec GDAL/OGR | 2.4.1 | Utilisé avec GDAL/OGR | 2.4.1
Compilé avec GEOS | 3.7.2-CAPI-1.11.2 | Utilisé avec GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compilé avec SQLite | 3.28.0 | Fonctionne avec SQLite | 3.28.0
Version du client PostgreSQL | 11.3 | Version de SpatiaLite | 4.3.0a
Version de QWT | 6.1.4 | Version de QScintilla2 | 2.11.1
Compilé avec PROJ | 5.2.0 | Fonctionne avec PROJ | Rel. 5.2.0, September 15th, 2018
Version de l'OS | macOS 10.15

I have this on MacOS but I'm pretty sure it happens in other OS.

**Comment by gioman** [comment]
@dd-a I cannot confirm on Windows and Linux, can you share a sample project+data so we can exclude something project related and eventually tag this as a macOS only issue. Thanks.

**Comment by gioman** [comment]
Closing for lack of feedback.
