### ISSUE TITLE
MIN and MAX operators not working in Raster Calculator(s)

### ISSUE THREAD

**Issue by ghtmtt** [qgis/QGIS#37716]
**Describe the bug**
It seems that ``MIN`` and ``MAX`` operators are not working in the native raster calculator of QGIS and neither in the Processing raster calculator. While the ``ABS`` function is working

**How to Reproduce**

Load a raster that you want and simply enter the following formula ``MIN(raster@1")`` or ``MAX(raster@1")``

Seems a regression because in QGIS 3.10 is working. See the following picture, **left** QGIS 3.15 and **right** 3.10

**MIN** and **MAX** (not working)

![image](https://user-images.githubusercontent.com/2884884/87055953-41a24500-c205-11ea-9e06-d33220911a3b.png)

**ABS** (working)

![image](https://user-images.githubusercontent.com/2884884/87056110-74e4d400-c205-11ea-815a-b3d3f05ff918.png)

Cannot do the same comparison with Processing because ``min``, ``max`` and ``abs`` have been introduced in a second moment. The following screenshot is only of 3.15 and compares ``MIN`` and ``ABS``

![image](https://user-images.githubusercontent.com/2884884/87056235-a2318200-c205-11ea-8a46-aff16e0530dc.png)

Version affected is for sure 3.15 (compiled) on Linux

**Comment by gioman** [comment]
@ghtmtt see https://github.com/qgis/QGIS/issues/35583#issuecomment-647746639

**Comment by ghtmtt** [comment]
thanks @gioman. 

Well the crash of issue #35583 seems solved because the expression is tagged as not valid.

Well that's a little bit more than counter intuitive from a user point of view. Especially because `abs` seems to return the absolute value of a single band of a raster. Maybe we can change the name of the buttons or add a tooltip? 

GDAL raster calculator seems working in this way (getting the minimum/maximum within a single band)

@elpaso what do you think?

**Comment by pblottiere** [comment]
Considering the current implementation, I think it's more a feature request than a bug report. Bet let's wait for @elpaso opinion.

**Comment by elpaso** [comment]
I think @luipir comment say it all: https://github.com/qgis/QGIS/issues/35583#issuecomment-656192760

MIN/MAX are binary operators that return min and max from two values.

**Comment by ghtmtt** [comment]
Maybe aa tooltip is helpful. Maybe it's me but I really expected something else for this function...

**Comment by ghtmtt** [comment]
just for reference I'll add that there is now the `Cell Statistic` algorithm that is calculating statistics among different raster layers
