### ISSUE TITLE
Raster layers exported from GeoPackage have no projection

### ISSUE THREAD

**Issue by jebins** [qgis/QGIS#37735]
Hi,

**Describe the bug**
Exporting a raster layer from a GeoPackage database to a geotiff drops the projection.

**How to Reproduce**

1. Connect to your GeoPackage database using the explorer.
2. Right click on the raster layer > Export the layer > To a file.
3. Choose a filename and a SCR.
4. Check the SCR with "gdalinfo".

**QGIS and OS versions**

QGIS | 3.10.5-A Coruña
-- | --
Qt | 5.12.8
GDAL/OGR | 3.0.4
GEOS | 3.8.0-CAPI-1.13.1
SQLite | 3.31.1
PostgreSQL | 12.2 (Ubuntu 12.2-4)

**Comment by gioman** [comment]
> **How to Reproduce**
> 
>     1. Connect to your GeoPackage database using the explorer.
> 
>     2. Right click on the raster layer > Export the layer > To a file.
> 
>     3. Choose a filename and a SCR.
> 
>     4. Check the SCR with "gdalinfo".

@jebins cannot confirm here with data of my own. Can you attach a sample dataset?

**Comment by gioman** [comment]
Closing for lack of feedback.
