### ISSUE TITLE
Possibility of own settings for searches in the locator

### ISSUE THREAD

**Issue by xrazdwa** [qgis/QGIS#37743]
I would like to be able to define which fields in which layers would be searched, then instead of searching everything with a command (af searchstring) I would use the command according to my own settings, which would speed up the search process of searching several layers at once.

**Comment by gacarrillor** [comment]
This is kinda possible right now.

Filter layers to appear in locator searches:
![image](https://github.com/qgis/QGIS/assets/652785/c302ff46-7664-4f63-a6e8-c2cc0c5393c1)

Choose which layer field will be used for searches from the locator:
![image](https://github.com/qgis/QGIS/assets/652785/5b5895dc-dc43-4d61-a6de-b992158f4a9f)

---------------
Is there something missing to accomplish what you're proposing here?
