### ISSUE TITLE
Digitizing and snapping toolbars not visible

### ISSUE THREAD

**Issue by sawernke** [qgis/QGIS#37753]
**Describe the bug**

QGIS3.14: The digitizing and snapping toolbars are not visible. I toggled them on and off several times, and they are just not there. I uninstalled and reinstalled 3.14, and the problem persists.
**How to Reproduce**

**QGIS and OS versions**
3.14, Win10 x64

View: Toolbars>Digitizing / View:Toolbars>Snapping
**Additional context**

**Comment by gioman** [comment]
@sawernke cannot replicate here. Probably you undocked the toolbars and lost track of them. Try with a new QGIS profile.

**Comment by gioman** [comment]
Closing for lack of feedback.
