### ISSUE TITLE
Broken layers auto-find function freezes QGIS

### ISSUE THREAD

**Issue by elpaso** [qgis/QGIS#37757]
The (relatively) new feature "Auto-find" in the broken layer dialog freezes QGIS completely in some cases.

I've been able to reproduce this in a few cases, try opening the attached project and click on "Auto-Find" in the broken layers dialog.

[MS_itopen.zip](https://github.com/qgis/QGIS/files/4906354/MS_itopen.zip)

**Comment by elpaso** [comment]
CC @roya0045

**Comment by roya0045** [comment]
Its not a freeze per say, its just searching  layer, I have tried to give feedback by showing a progress bar but it seems that the process doesn't allow the bar to pop up sometimes. I'm wondering if it could be done in a background thread.

But yeah, it demands a lot of ressource if the possible paths are deep to explore.

Suggestions are welcomed.

**Comment by elpaso** [comment]
> Its not a freeze per say, 

Well, I waited ~ 10 minutes with QGIS completely unresponsive ... I'd call it a freeze/hang.

Anyway, this is a serious bug, are you sure there is no infinite loop somewhere?

> its just searching layer,

Where exactly? In the whole filesystem?

> I have tried to give feedback by showing a progress bar but it seems that the process doesn't allow the bar to pop up sometimes. 

The process must be user-interruptible.

> I'm wondering if it could be done in a background thread.

I think it's the right choice.

**Comment by roya0045** [comment]
@elpaso the only issue that I have with background thread is users trying to use a project when the sources haven't all been found.

Yes the layers are searched in an outward spiral pattern until the search directory reaches a point where its too close to the root.

**Comment by roya0045** [comment]
I'll try what failed previously as I used the progress dialog and process all events. I'll see if I can use a background thread instead.
