### ISSUE TITLE
copy style and paste style works not as expected

### ISSUE THREAD

**Issue by kk-qgis** [qgis/QGIS#37762]
**Describe the bug**
I have to click twice to the copy style before I can paste the style to another layer

**How to Reproduce**

1. go to a layer an use the context menu >>Styles>>Copy Style
2. go to the targetlayer us the context menu >>Sytles>>there is no context men Paste Style
3. go to the same layer 1 an use the context menu >>Styles>>Copy Style
4. go to the targetlayer (2) us the context menu >>Sytles>>at the second attempt there will be the context menu Paste Style

**QGIS and OS versions**

QGIS version | 3.14.0-Pi | QGIS code revision | 9f7028fd
-- | -- | -- | --
Compiled against Qt | 5.14.2 | Running against Qt | 5.14.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 12.2 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | KDE Flatpak runtime
Active python plugins | VectorBender; QuickMultiAttributeEdit3; polystrip; qfieldsync; MetaSearch; db_manager; processing

**Additional context**

**Comment by gioman** [comment]
@kk-qgis can't confirm here.

Are the layers vectors or rasters?

**Comment by kk-qgis** [comment]
Vector layers

**Comment by gioman** [comment]
> Vector layers

@kk-qgis post a screencast please.

**Comment by kk-qgis** [comment]
this my first screencast of my life
![Peek 2020-07-12 20-23](https://user-images.githubusercontent.com/59770558/87253723-c4cdd000-c47d-11ea-967a-457fc83b9ac4.gif)

**Comment by gioman** [comment]
> this my first screencast of my life

@kk-qgis thanks, I definitely do not confirm on Ubuntu (QGIS installed from repos) and Windows.

Maybe is a glitch when installing with Flatpack.

**Comment by kk-qgis** [comment]
I have installed QGIS via Flatpack. But it is the same with QGIS installed via Synaptic

**Comment by gioman** [comment]
> I have installed QGIS via Flatpack. But it is the same with QGIS installed via Synaptic

@kk-qgis what flavor of Linux do you use?

**Comment by kk-qgis** [comment]
zorin os 15.2 which is based on ubuntun 18.04
