### ISSUE TITLE
Split with lines causes data loss

### ISSUE THREAD

**Issue by kk-qgis** [qgis/QGIS#37761]
**Describe the bug**
I have a memory line layer and with this layer I want to split geoms of gpkg-file by using the edit in place mode. After finsihing the job there is not the expect result but aduplication of geoms in the gpk-file

**How to Reproduce**

1. load a poly-layer of gpkg-file
2. creaete a memory line line
3. active edit in place mode
4. start the processing tool split with lines
5. no split but a duplication of geoms

**QGIS and OS versions**

QGIS version | 3.14.0-Pi | QGIS code revision | 9f7028fd
-- | -- | -- | --
Compiled against Qt | 5.14.2 | Running against Qt | 5.14.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 12.2 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | KDE Flatpak runtime
Active python plugins | VectorBender; QuickMultiAttributeEdit3; polystrip; qfieldsync; MetaSearch; db_manager; processing

**Additional context**

**Comment by kk-qgis** [comment]
if the linelayer is a shp-file there is no result

**Comment by gioman** [comment]
@kk-qgis I can't confirm, but actually is even worst than you describe.

I don't see any difference while splitting with a shapefile or a memory layer, the split occur, but...

when saving edits QGIS throws errors like

```
      Erro OGR ao criar elemento -166: failed to execute insert : UNIQUE constraint failed: albu.fid
      Erro OGR ao criar elemento -167: failed to execute insert : UNIQUE constraint failed: albu.fid
      Erro OGR ao criar elemento -168: failed to execute insert : UNIQUE constraint failed: albu.fid
      Erro OGR ao criar elemento -169: failed to execute insert : UNIQUE constraint failed: albu.fid
      Erro OGR ao criar elemento -170: failed to execute insert : UNIQUE constraint failed: albu.fid
      Erro OGR ao criar elemento -171: failed to execute insert : UNIQUE constraint failed: albu.fid
      Erro OGR ao criar elemento -172: failed to execute insert : UNIQUE constraint failed: albu.fid
      Erro OGR ao criar elemento -177: failed to execute insert : UNIQUE constraint failed: albu.fid
      Erro OGR ao criar elemento -178: failed to execute insert : UNIQUE constraint failed: albu.fid
```

it is **only** at this moment that some of the split geometries get duplicated.

But the worst is when discarding changes (as they can't be saved): some of the split geoms vanish... really a bad bug.

**Comment by kk-qgis** [comment]
After the split job I use the processingtool delete duplicate geometries. It removes 50 % of the geoms

**Comment by roya0045** [comment]
Unique IDs and geometry splitting is often problematic.

**Comment by gioman** [comment]
> Unique IDs and geometry splitting is often problematic.

and data loss as well :)
