### ISSUE TITLE
Report pages cannot be re-ordered

### ISSUE THREAD

**Issue by timlinux** [qgis/QGIS#37770]
I love reports but it really needs some love :-(

I have other issues (e.g. regular crashing when exporting), but for now, the biggest bug (you could argue it is a missing feature but IMHO it is a bug because it really destroys a lot of my productivity when designing a report) is that you cannot re-order groups and sections. Without that capability I basically need to start over every time I want to move a section up or down in the print order.

<img width="445" alt="image" src="https://user-images.githubusercontent.com/178003/87235429-ed00f480-c3d3-11ea-8be8-eae6784fd605.png">

**Comment by Gustry** [comment]
There is already a ticket open : https://github.com/qgis/QGIS/issues/29060

**Comment by timlinux** [comment]
@Gustry oh sorry, thanks for the heads up - I searched the queue before making the ticket but I missed that one....
