### ISSUE TITLE
Vertext Tool not moving vertices on MSSQL Server layer

### ISSUE THREAD

**Issue by johnfix** [qgis/QGIS#37784]
Using QGIS Pi:

I open a layer for editing and chose the "Vertex Tools (current layer)" and QGIS builds the indexes. Once built I attempt to move the vertices of a line. The vertices highlight in red, but when I click in another location, nothing happens.

 should note this layer "Roads" is almost a copy of another layer "Roads Display." I was able to move the "Roads Display", but now when I want to move the "Roads" I can't seem to edit them. 

Is this an indexing or cache issue?

This layer is in SQL Server and I have all rights to it. Some kind of row lock?

Thanks.

**Comment by uclaros** [comment]
Could you try the following and report back?
1. select a couple of features from the offending layer.
2. edit -> copy features
3. edit -> paste features as -> temporary scratch layer
4. try to use the vertex tool on the new scratch layer

**Comment by johnfix** [comment]
I tried the steps below. I could move some of the vertices, but other vertices would not move.

I see the thin dashed red line showing my mouse location and where I would be moving the vertex, but when I mouse up, nothing happens.

I even turned snapping off in case it was a snapping tolerance issue.

When I select the tool, I do see a message in orange at the top about:
“Used a ballpark transformation from EPSG:2248 to EPSG:3395
3395 is the coordinate system of my data.

I do have many layers in a large dataset. The indexing to prepare for this tool takes 30-60 seconds to complete.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by uclaros** [comment]
Could you share here some of the lines whose vertices you cannot move?
Your issue seems more like it's tied to your data / projections rather than the provider (sqlserver).

**Comment by johnfix** [comment]
Attached is a zip file of the layers in shapefile format. Unfortunately I did not have an issue with the shapefiles.

I can not tell if this is a QGIS software issue, or perhaps a mouse issue. It seems sometimes my left click does not register as a left click. But I did a lot of work to click properly. It took multiple tries, but I was able to get the vertices to move.

I don’t think I am being much help. Sorry.

Please let me know if you need anything else.

Thanks.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by gioman** [comment]
> or perhaps a mouse issue

:) @johnfix have you tried a different one?

**Comment by johnfix** [comment]
Yes, I just tried a new mouse and it seem to work as expected. I’m sorry I didn’t realize this sooner…but seriously, I am an IT professional.
Thank you.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
