### ISSUE TITLE
QGIS Crashes any time I try to load more than one raster data from the .h5  data from NASA's EOS website

### ISSUE THREAD

**Issue by kevnuk** [qgis/QGIS#37782]
## User Feedback

Everytime I try to load more than one raster data from the SMAP .h5 file I downloaded from NASA's EOS website, QGIS crashes.

## Report Details

**Crash ID**: [168404ad131070ba2466332b61e176156b56af84](https://github.com/qgis/QGIS/search?q=168404ad131070ba2466332b61e176156b56af84&type=Issues)

**Stack Trace**
<pre>
H5SL_insert :
H5SL_insert :
H5I_register :
H5Gopen1 :
GDALRegister_HDF5 :
H5G_iterate :
H5G__link_iterate_table :
H5G__compact_iterate :
H5G__obj_iterate :
H5G_iterate :
H5Giterate :
GDALRegister_HDF5 :
H5G_iterate :
H5G__link_iterate_table :
H5G__dense_iterate :
H5G__obj_iterate :
H5G_iterate :
H5Giterate :
GDALRegister_HDF5 :
H5G_iterate :
H5G__link_iterate_table :
H5G__compact_iterate :
H5G__obj_iterate :
H5G_iterate :
H5Giterate :
GDALRegister_HDF5 :
GDALRegister_HDF5Image :
GDALOpenEx :
GDALOpen :
QgsProcessingModelOutput::toVariant :
QgsRenderChecker::elapsedTime :
QgsAbstractDatabaseProviderConnection::TableProperty::GeometryColumnType::operator== :
QgsSingleBandGrayRenderer::block :
QgsBrightnessContrastFilter::block :
QgsHueSaturationFilter::block :
QgsRasterResampleFilter::block :
QgsRasterProjector::block :
QgsRasterIterator::readNextRasterPartInternal :
QgsRasterDrawer::draw :
QgsRasterLayerRenderer::render :
QgsMapRendererParallelJob::renderLayerStatic :
QgsArchive::zip :
QgsImageOperation::overlayColor :
QgsImageOperation::flipImage :
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.5-A Coru�a
QGIS code revision: 984615fe1e
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
> I downloaded from NASA's EOS website

@kevnuk can you please post the direct link to the data?

Also try with a new QGIS profile.

**Comment by kevnuk** [comment]
This is the link to the data; https://n5eil01u.ecs.nsidc.org/SMAP/SPL2SMAP_S.002/2020.07.09/

Thanks.

**Comment by gioman** [comment]
> This is the link to the data; https://n5eil01u.ecs.nsidc.org/SMAP/SPL2SMAP_S.002/2020.07.09/

@kevnuk an account is needed. Can you just re-upload the files to some place like Dropbox and link them here? thanks.

**Comment by kevnuk** [comment]
@gioman please find link from Google Drive; https://drive.google.com/file/d/1ZRswW9IrpJ4bDBnR6GKF-pf6cN4y1hsG/view?usp=sharing

**Comment by gioman** [comment]
@kevnuk the link point to just one file, aren't needed more?

**Comment by kevnuk** [comment]
@gioman the file is a .h5 file that contains several files embedded in it. When you try to load the file in qgis by drag and drop, you will see the numerous files that can be selected.

**Comment by gioman** [comment]
@kevnuk I can load the whole dataset on Linux without issues. On Windows the dataset does not load at all, probably a missing driver/library I can't find it right now (anyway it is weird, as gdalinfo works).

**Comment by kevnuk** [comment]
@gioman I guess I will just continue to load them one after the other as I deem fit. 

Thanks for your support.

**Comment by gioman** [comment]
> I guess I will just continue to load them one after the other as I deem fit.

@kevnuk my comment was just a matter of understand if is a general bug or if it is specific for some platform. Actually it would be also necessary to understand why this type of datasources do not open on clean installation of QGIS on Windows.

**Comment by kevnuk** [comment]
@gioman I agree with you completely. It is good to know why the error occurs so it can be averted. I tried your suggestion about using another profile, but this thing happened. In fact, the project does not load completely anymore, it crashes before it finish loading. I just have to use other work arounds, by that I mean; open a new project and load data one after another. I even tried using FME, but FME does not have the .h5 format supported.

Thanks again.
