### ISSUE TITLE
Problems with properties options on shape layers

### ISSUE THREAD

**Issue by salomonal** [qgis/QGIS#37796]
QGIS 3.X crashes when i go to Rclick -> Properties 

It works in raster layers 
Also works in QGIS 2.18 versión

**Comment by gioman** [comment]
@salomonal QGIS version? Operating system? Have you tried with a new QGIS profile (no 3rd party plugins installed)?

**Comment by salomonal** [comment]
Hi @gioman 

Im working with windows 10 x64, and i tried with 3.14 and the ltr 3.10.7 

before post i uninstall all packages (qgis, osgeo, etc) and install again and... it´s the same

**Comment by gioman** [comment]
> before post i uninstall all packages (qgis, osgeo, etc) and install again and... it´s the same

@salomonal you don't have to re-install, but create a new QGIS profile

settings > profiles > new profile

**Comment by salomonal** [comment]
@gioman ¡funciona!

Perfect! Thank you so much
