### ISSUE TITLE
Python Fehler erscheint beim öffnen von Google Physical

### ISSUE THREAD

**Issue by Gustav648** [qgis/QGIS#37792]
Hallo Leute, ich habe folgendes Problem. Beim öffnen von Open Layers Plugin und anschließendes klicken auf Google Physical erscheint folgende Fehlermeldung. 
Python-Fehler: Ein Fehler trat bei der Ausführung von Python-Code auf: Mehr Details im Protokoll (Python-Fehler).
Ich habe QGIS schon deinstalliert und neu installiert das brachte aber leider keinen Erfolg.  Auch habe ich OpenLayers Plugin gelöscht und neu installiert, ebenfalls ohne Erfolg. 
Hat jemand von euch vielleicht Vorschläge was ich noch versuchen könnte ?
Ich danke im vorraus.

**Comment by gioman** [comment]
@Gustav648 Hi, tickets must be filed in English, thanks!

**Comment by Gustav648** [comment]
Hello folks, I have the following problem. When opening Open Layers Plugin and then clicking on Google Physical, the following error message appears.
Python Error: An error occurred when python code was executed: More details in the log (Python error).
I have already uninstalled QGIS and reinstalled this was unfortunately not successful. I also deleted and reinstalled OpenLayers plugin, also to no avail.
Does any of you have any suggestions what else I could try?
I thank you in advance.
