### ISSUE TITLE
Python error appears when opening Google Physical

### ISSUE THREAD

**Issue by Gustav648** [qgis/QGIS#37793]
Hello folks, I have the following problem. When opening Open Layers Plugin and then clicking on Google Physical, the following error message appears.
Python Error: An error occurred when python code was executed: More details in the log (Python error).
I have already uninstalled QGIS and reinstalled this was unfortunately not successful. I also deleted and reinstalled OpenLayers plugin, also to no avail.
Does any of you have any suggestions what else I could try?
I thank you in advance.

**Comment by gioman** [comment]
@Gustav648 if the problem is with a 3rd party plugin such the OpenLayers one you must contact the plugin author/s. Cheers!
