### ISSUE TITLE
Cannot save edits in form view unless changing focus on a different feature

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#37795]
QGIS master on Linux.

I'm editing a few attributes of a record in table while in form view.

After editing the values of an attribute moving the focus to a different attribute of the same record is not enough to trigger the "save edits" button to become active, it is in fact necessary to move the focus to an entirely different record, which is very inconvenient

**Comment by gioman** [comment]
Still true on the latest master.

**Comment by alexbruy** [comment]
The save button becomes available in the latest master (e5e6a13671), though the feature's preview value in the list is still displayed in red italics. Probably we should close this and open a separate ticket for preview value update.
