### ISSUE TITLE
Field filter does not work on boolean field configured with the "checkbox" widget

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#37794]
QGIS master:

I have a PostGIS table with a boolean filter configured with the "checkbox" filter.

The "field filter" option does nothing, it shows a checkbox (as expected) but regardless if is checked or not no records show in the table.

"field filter" works on another boolean field without the "checkbox" widget: the user must write "true" or "false" and the expected records show in the table.

**Comment by roya0045** [comment]
I always felt like the boolean field to be finnicky...

**Comment by ponceta** [comment]
Same problem encountered in Lausanne and Pully, still an issue on QGIS 3.22 

("tunnel_or_bridge"='') AND (TRUE) AND (TRUE) AND (TRUE)

**Comment by elpaso** [comment]
If someone attaches a test project and data I can have a look.

**Comment by gioman** [comment]
> If someone attaches a test project and data I can have a look.

ok.

**Comment by gioman** [comment]
> If someone attaches a test project and data I can have a look.

@elpaso gpkg with project in it attached. You can use the "metadata_available" field (is on of the lasts in the table).
[cat.zip](https://github.com/qgis/QGIS/files/8132149/cat.zip)

**Comment by elpaso** [comment]
> > If someone attaches a test project and data I can have a look.
> 
> @elpaso gpkg with project in it attached. You can use the "metadata_available" field (is on of the lasts in the table). [cat.zip](https://github.com/qgis/QGIS/files/8132149/cat.zip)

Cannot reproduce on current master.

**Comment by elpaso** [comment]
![bug_47507](https://user-images.githubusercontent.com/142164/155522925-5570c80e-4b28-4bd9-86c8-24eee72dbc65.gif)

**Comment by lindacamathias** [comment]
the field filter for a bool field does still not work for me. 

1. in qgis, i created a **new geopackage layer** (via qgis> create layer) with just a **boolean field** in it. 
2. i **added some features** (via add feature in attribute table) 
3. **manually activated some of the checkboxes**, some deactivated. 
4. **saved** features
--> check field filter for that boolean field -> no records shown 

 i did also try with 3.42.0 after seeing sth in this direction was fixed ( https://github.com/qgis/QGIS/pull/60552 )
unfortunately with the same outcome.
