### ISSUE TITLE
SplitGeometry doesn't return topological points

### ISSUE THREAD

**Issue by alistaireverett** [qgis/QGIS#37806]
**Describe the bug**
Since upgrading from QGIS 3.6, I've seen that SplitGeometry doesn't return topological points regardless of the boolean True/False which has been passed, this seems to the case in QGIS 3.10 and 3.14.

It looks like splitGeometry is undergoing some changes, should this functionality be maintained in the meantime or is this something which will be deprecated in the future? If so, is there a suggested alternative method of getting the topo points now?

**How to Reproduce**

In QGIS 3.10:

```
>>> geometry = QgsGeometry.fromWkt('CompoundCurveZ ((2749546.2003820720128715 1262904.45356595050543547 100, 2749557.82053794478997588 1262920.05570670193992555 200))')
>>> split_line = [QgsPointXY(2749544.19, 1262914.79), QgsPointXY(2749557.64, 1262897.30)]
>>> result, new_geometries, point_xy = geometry.splitGeometry(split_line, True)
>>> len(point_xy)
0
```
The same steps in QGIS 3.6 give:
```
>>> len(point_xy)
1
```

**QGIS and OS versions**

QGIS version | 3.10.1-A Coruña | QGIS code revision | ef24c526da
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.6.2-CAPI-1.10.2 4d2925d6
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 10.10 (Ubuntu 10.10-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Ubuntu 18.04.4 LTS
Active python plugins | plugin_reloader; digitizingScreen; latlontools; MetaSearch; processing; db_manager

**Additional context**

**Comment by alistaireverett** [comment]
Just a note - this also affects the Split Features tool in the GUI 
![image](https://user-images.githubusercontent.com/7837535/87418848-bf35ce80-c5d2-11ea-9ba7-a9350de74961.png)

**Comment by alistaireverett** [comment]
For anyone who needs a temporary fix, I've used something similar to this to get the intersection if it's not returned by splitGeometry:

```
if len(point_xy) == 0:
    split_geom = QgsGeometry.fromPolylineXY(split_line)
    point_xy = split_geom.intersection(geometry).asPoint()
```

**Comment by uclaros** [comment]
Can you run the new `splitGeometry` variant that accepts `QgsPoint` instead of the deprecated that accepts `QgsPointXY` ?
I think the problem is in the way the deprecated method calls the new one., but I cannot run the new method directly from python to test, I always get `TypeError: index 0 has type 'QgsPoint' but 'QgsPointXY' is expected`

The GUI split features tool is, I think, a different bug.

**Comment by alistaireverett** [comment]
Unfortunately I have the same issue with the new version of splitGeometry, I would be happy to switch over to using that if possible.

But I see you've found the issue with the deprecated version, thanks.

**Comment by uclaros** [comment]
> Unfortunately I have the same issue with the new version of splitGeometry

I'm opening this and the split map tool as separate issues.
