### ISSUE TITLE
Messed up data types after running SAGA snap points to lines

### ISSUE THREAD

**Issue by Sissi-LEI** [qgis/QGIS#37808]
**Describe the bug**
I run SAGA 'snap points to lines' tool using the belowing files:
points layer: CSV files contain x/y coordinates
Snap feature: OSM street shapefile

The output seems have changed data type and returned symbols that don't make any sense (see screenshot below)
![image](https://user-images.githubusercontent.com/32822638/87431655-dda1c700-c5de-11ea-9c11-7f519b171300.png)

**QGIS and OS versions**
QGIS version: 3.14.0-Pi
QGIS code revision: 9f7028fd23
Qt version: 5.11.2
GDAL version: 3.0.4
GEOS version: 3.8.1-CAPI-1.13.3
PROJ version: Rel. 6.3.2, May 1st, 2020

**Comment by gioman** [comment]
@Sissi-LEI does it happens if you run the same tool with the same data from the SAGA gui or from the SAGA command line?

**Comment by Sissi-LEI** [comment]
> @Sissi-LEI does it happens if you run the same tool with the same data from the SAGA gui or from the SAGA command line?
Hi, Thank you very much for coming back. I never used SAGA gui before, just tried to load data in the same tool in SAGA but it only read .sprm which I believe a raster type data? Is there a way that I could read CSV or shapefile instead? 
thank you in advance

**Comment by Sissi-LEI** [comment]
> @Sissi-LEI does it happens if you run the same tool with the same data from the SAGA gui or from the SAGA command line?

Hi, Thank you very much for coming back. I never used SAGA gui before, just tried to load data in the same tool in SAGA but it only read .sprm which I believe a raster type data? Is there a way that I could read CSV or shapefile instead?
thank you in advance

**Comment by gioman** [comment]
> Hi, Thank you very much for coming back. I never used SAGA gui before, just tried to load data in the same tool in SAGA but it only read .sprm which I believe a raster type data? Is there a way that I could read CSV or shapefile instead?
> thank you in advance

@Sissi-LEI please attach your data here (as zip).

**Comment by Sissi-LEI** [comment]
> > Hi, Thank you very much for coming back. I never used SAGA gui before, just tried to load data in the same tool in SAGA but it only read .sprm which I believe a raster type data? Is there a way that I could read CSV or shapefile instead?
> > thank you in advance
> 
> @Sissi-LEI please attach your data here (as zip).
Thank you I've attached the sample data below.
[QGIS_SampleData.zip](https://github.com/qgis/QGIS/files/4919922/QGIS_SampleData.zip)

**Comment by gioman** [comment]
@Sissi-LEI no issues whatsoever with the data you sent both on Windows and Linux. The screenshot you posted does not make much sense, the number of fields do not match the one of the point layer you attached.

**Comment by Sissi-LEI** [comment]
> @Sissi-LEI no issues whatsoever with the data you sent both on Windows and Linux. The screenshot you posted does not make much sense, the number of fields do not match the one of the point layer you attached.

Hi Due to the size restriction I have to clip the shapefile, for the CSV, I only kept the lat.lng and IDs as other columns might contain credentials, but apart from removing columns I didn't change anything. Would you think it could be useful that I replace the credential info and keep all columes?

**Comment by gioman** [comment]
> Would you think it could be useful that I replace the credential info and keep all columes?

@Sissi-LEI with the data you previously attached the issue is not replicable, so it is better to attach exactly the data is giving you problems (of course remove/replace the sensible infos).

**Comment by Sissi-LEI** [comment]
> > Would you think it could be useful that I replace the credential info and keep all columes?
> 
> @Sissi-LEI with the data you previously attached the issue is not replicable, so it is better to attach exactly the data is giving you problems (of course remove/replace the sensible infos).
Thank you I could prepare exactly the same data, however I tested the Sample data which I sent over previously and even the sample data returned the same error, so my assumption is maybe it's not something to do with the data? I have attached the screenshot of the result return by 'Snap Points to Lines' using the sample data. Sorry, I am not a professional please correct me if I was wrong.
![image](https://user-images.githubusercontent.com/32822638/87538437-1b145c00-c694-11ea-9cd2-978e90147a2e.png)

**Comment by gioman** [comment]
>  however I tested the Sample data which I sent over previously and even the sample data returned the same error, so my assumption is maybe it's not something to do with the data? I have attached the screenshot of the result return by 'Snap Points to Lines' using the sample data. Sorry, I am not a professional please correct me if I was wrong.

@Sissi-LEI ok, so please attach a screencast of the steps you are following.

**Comment by Sissi-LEI** [comment]
> > however I tested the Sample data which I sent over previously and even the sample data returned the same error, so my assumption is maybe it's not something to do with the data? I have attached the screenshot of the result return by 'Snap Points to Lines' using the sample data. Sorry, I am not a professional please correct me if I was wrong.
> 
> @Sissi-LEI ok, so please attach a screencast of the steps you are following.

1. Run 'Snap points to lines' from processing toolbox 
![image](https://user-images.githubusercontent.com/32822638/87553622-0becd880-c6ab-11ea-8968-a484e99d7c92.png)
2. Set SamplePoints as Points and SampleStreet as Snap Features, Click Run
3. After the operation I have the 'Result' output as shown below:
![image](https://user-images.githubusercontent.com/32822638/87554156-b1a04780-c6ab-11ea-91ad-77ee7d5e2a08.png)
I've also attached the module log hope it helps
[Snap Points to Lines Log.txt](https://github.com/qgis/QGIS/files/4925659/Snap.Points.to.Lines.Log.txt)

**Comment by gioman** [comment]
@Sissi-LEI 

![Screenshot_20200715_172607](https://user-images.githubusercontent.com/1951107/87570293-4f057680-c6c0-11ea-9684-5447ddeec8dc.png)

**Comment by Sissi-LEI** [comment]
> @Sissi-LEI
> 
> ![Screenshot_20200715_172607](https://user-images.githubusercontent.com/1951107/87570293-4f057680-c6c0-11ea-9684-5447ddeec8dc.png)

this is confusing.... I even tried uninstall and reinstall QGIS, but not quite sure which I have done wrong..

**Comment by gioman** [comment]
> I even tried uninstall and reinstall QGIS, but not quite sure which I have done wrong

@Sissi-LEI if there is a bug then re-installing will not help. Anyway the evidence seems to indicate that if there is a bug it happens under circumstances that are not yet clear.

On my Windows testing machines (Win in EN or PT_PT) I do not have the reported problem. What language is your OS? Do you have some specific regional settings?

**Comment by Sissi-LEI** [comment]
> > I even tried uninstall and reinstall QGIS, but not quite sure which I have done wrong
> 
> @Sissi-LEI if there is a bug then re-installing will not help. Anyway the evidence seems to indicate that if there is a bug it happens under circumstances that are not yet clear.
> 
> On my Windows testing machines (Win in EN or PT_PT) I do not have the reported problem. What language is your OS? Do you have some specific regional settings?

my OS is windows 10 and the language setting is in English, the region has been set in UK. The snap points to line worked fine last week, just from this week this issue started.

**Comment by gioman** [comment]
> The snap points to line worked fine last week, just from this week this issue started.

@Sissi-LEI did you changed/updated QGIS version since it last worked?

**Comment by Sissi-LEI** [comment]
> > The snap points to line worked fine last week, just from this week this issue started.
> 
> @Sissi-LEI did you changed/updated QGIS version since it last worked?

No I didn't, only when I found this problem appeared then I tried to uninstall/reinstall, for both QGIS 3.14 and a few previous versions, none of them fixed this issue...

**Comment by gioman** [comment]
@Sissi-LEI everything seems to point to an issue in your system, not QGIS. Please test on a different machine to verify this last statement.

**Comment by gioman** [comment]
Closing for lack of feedback.
