### ISSUE TITLE
QGIS - Working with Date Column using SQLite

### ISSUE THREAD

**Issue by Catacombe** [qgis/QGIS#37818]
I have an issue when previewing **date field** using SQLite in QGIS.
Previously, I had some records of _date data_ using **text field**, and I can preview the data in QGIS using attribute table.
But, as I try to sort the **text field** (_date data_) ASC/DESC, the problem occurs since I can't get what is expected, as the _date data_ isn't sorted accordingly.
So, I try to move the _date data_ in the **text field** to a new **date field** (using _spatialite-gui_ tools) while expecting the sort process will have a better result.
As the result, I can preview the _date data_ in the new **date field** (using spatialite-gui tools), but the sort process using SQL Command (ASC/DESC) still not get what I was expecting. The new **date field** will not sort the **date data** accordingly (the result is the same as sorting using the **text field** as previous result).
And the worst is, QGIS will not show the **date data** when I try to open the table using attribute table (_null_ content).

![Capture](https://user-images.githubusercontent.com/46992423/87506061-9d048500-c694-11ea-93fb-0a881b14d216.JPG)

**Comment by gioman** [comment]
>  And the worst is, QGIS will not show the **date data** when I try to open the table using attribute table (_null_ content).

@Catacombe please attach sample data.

**Comment by Catacombe** [comment]
Dear @gioman ,
Sorry for late response.
As you can see, there's an issue in QGIS viewer, especially for the **date field**.

**Spatialite-gui view**

![view_Spatialite_Gui](https://user-images.githubusercontent.com/46992423/88012757-e8aba880-cb44-11ea-8531-666d426ea377.JPG)

**DB Manager view**

![view_DBManager](https://user-images.githubusercontent.com/46992423/88012792-feb96900-cb44-11ea-911f-15d493c7689e.jpg)

**QGIS 3.14 view**

![view_QGIS](https://user-images.githubusercontent.com/46992423/88012832-142e9300-cb45-11ea-8fdb-f63d1d55964e.JPG)

Thanks....

**Comment by gioman** [comment]
> Dear @gioman ,
> Sorry for late response.
> As you can see, there's an issue in QGIS viewer, especially for the **date field**.

@Catacombe please **attach** (as zip) sample data.

**Comment by Catacombe** [comment]
Dear @gioman ,

Attached is the data I used in my QGIS project.

[
[Data.zip](https://github.com/qgis/QGIS/files/4963634/Data.zip)
](url)

**Comment by nirvn** [comment]
In QGIS, a field with DATE type requires a format like '2020-01-01', not '1 Jan 2020'. If you want to use the latter, keep your field type as TEXT. DB Manager handles DATE type as TEXT, so does spatialite-gui.

**Comment by Catacombe** [comment]
Wow, thanks a lot @nirvn ... now I know how DB Manager and Spatialite-gui handles the **date filed** (or other type field) that differ from QGIS.
Next time, I'll pay attention to these kind of issues.
