### ISSUE TITLE
QGIS can't be set as active window

### ISSUE THREAD

**Issue by dmitrykinakh** [qgis/QGIS#37827]
**Describe the bug**
The issue started appearing to me when I jumped to Qgis 3. If you have many apps running and QGIS was hidden, then you need to hide any other apps running so the QGIS window will be visible. See the video for details.

**How to Reproduce**

1. Install QGIS 3.10 or 3.14 on Windows 10
2. Open app
3. Move any other app on top of it and click on Qgis app
4. Verify it will not be set as the active app

Video - https://www.screencast.com/t/gNSXwRIr

**QGIS and OS versions**
The current released version of QGIS is 3.14.0. 
We are working on 3.15-Master. It will go into feature freeze on 2020-09-11 12:00:00 UTC and be released as 3.16 on 2020-10-23 12:00:00 UTC. 
Details on changes can be found on github at https://github.com/qgis/QGIS/commits/master.

**Comment by dmitrykinakh** [comment]
Note: initial 3.0.0 version does not have this issue.

**Comment by Pedro-Murteira** [comment]
@dmitrykinakh I'm not able to replicate this issue on QGIS 3.22.3. on Windows. Meanwhile, did you stop having this issue?

**Comment by dmitrykinakh** [comment]
I've re-installed windows and installed the latest version of QGIS - all works fine now.
