### ISSUE TITLE
Cannot run the non deprecated QgsGeometry.splitGeometry method from python

### ISSUE THREAD

**Issue by uclaros** [qgis/QGIS#37821]
**Describe the bug**
`QgsGeometry.splitGeometry` has two variants, one accepting iterable with  `QgsPointXY`s (deprecated) and one accepting iterable with `QgsPoint`s.
While calling `QgsGeometry().splitGeometry()` the returning error shows that there are two overloaded methods, when passing an iterable with `QgsPoints` we get an `TypeError: index 0 has type 'QgsPoint' but 'QgsPointXY' is expected`

**How to Reproduce**
On a python console run `QgsGeometry().splitGeometry([QgsPoint()],False)`

or

run the sample code from the docs:
```
geometry = QgsGeometry.fromWkt('CompoundCurveZ ((2749546.2003820720128715 1262904.45356595050543547 100, 2749557.82053794478997588 1262920.05570670193992555 200))')
split_line = [QgsPoint(2749544.19, 1262914.79), QgsPoint(2749557.64, 1262897.30)]
result, new_geometries, point_xy = geometry.splitGeometry(split_line, False)
```

**QGIS and OS versions**
master on Debian testing

**Comment by m-kuhn** [comment]
CC @lbartoletti

**Comment by uclaros** [comment]
The same happens with other methods that have one variant accepting `QVector<QgsPointXY>` and one accepting `QgsPointSequence` like `QgsVectorLayer::splitFeatures`

**Comment by lbartoletti** [comment]
Yes, it seems it's because python (sip) can not have same method with different type. 

BTW, the order matter, if in `qgsgeometry.h` order of the methods is:

```
Q_DECL_DEPRECATED OperationResult splitGeometry( const QVector<QgsPointXY> &splitLine, QVector<QgsGeometry> &newGeometries SIP_OUT, bool topological, QVector<QgsPointXY> &topologyTestPoints SIP_OUT, bool splitFeature = true ) SIP_DEPRECATED;
OperationResult splitGeometry( const QgsPointSequence &splitLine, QVector<QgsGeometry> &newGeometries SIP_OUT, bool topological, QgsPointSequence &topologyTestPoints SIP_OUT, bool splitFeature = true );
```

you have to pass QVector<QgsPointXY>

but it requires `QVector<QgsPoint>` aka `QgsPointSequece` with this order:

```
OperationResult splitGeometry( const QgsPointSequence &splitLine, QVector<QgsGeometry> &newGeometries SIP_OUT, bool topological, QgsPointSequence &topologyTestPoints SIP_OUT, bool splitFeature = true );
Q_DECL_DEPRECATED OperationResult splitGeometry( const QVector<QgsPointXY> &splitLine, QVector<QgsGeometry> &newGeometries SIP_OUT, bool topological, QVector<QgsPointXY> &topologyTestPoints SIP_OUT, bool splitFeature = true ) SIP_DEPRECATED;
```

But, Is this solution acceptable? (only one of the two methods is always proposed in python)

**Comment by m-kuhn** [comment]
Options:

1. Nice solution: provide `%MethodCode`, inspect the argument type and call the appropriate method
2. Provide `SIP_PYNAME` for the alternative

**Comment by lbartoletti** [comment]
>     1. Nice solution: provide `%MethodCode`, inspect the argument type and call the appropriate method

For me, this is the best solution. But, for now, I don't know how to do it with SIP. If you or @3nids had the time, go ahead.If not, I'll try to see how to do that; hopefully I'll be able to do it before the end of this bugfix (not sure :/).

**Comment by 3nids** [comment]
you can have a look for sipCanConvertToType (for instance in QgsPoint constructor).
