### ISSUE TITLE
Travis fails when running deprecated code in unit tests

### ISSUE THREAD

**Issue by uclaros** [qgis/QGIS#37822]
**Describe the bug**
A deprecation warning on unit tests causes travis to fail.
My understanding of *deprecated* is a warning to devs to adapt their code because a method will be removed in next API break. Until the API break though, the method should be guaranteed to work as expected.
I don't know if this is easy to implement but I think that deprecated unit tests should be removed only once the method is removed.

**Comment by m-kuhn** [comment]
Calls to deprecated functions need to be wrapped into `Q_NOWARN_DEPRECATED_PUSH`, `Q_NOWARN_DEPRECATED_POP`

**Comment by uclaros** [comment]
That's great! I'm closing this and updating my offending tests.
