### ISSUE TITLE
Split features map tool only adds topological points to same layer

### ISSUE THREAD

**Issue by uclaros** [qgis/QGIS#37823]
**Describe the bug**
When splitting features with the *split features* map tool and having *topological editing* enabled, topological points are added only to intersecting features of the same layer. To correctly preserve topology, all editable vector layers should have the points added, just like when using the *vertex tool*.

**QGIS and OS versions**
master on Debian testing

**Comment by m-kuhn** [comment]
See also #37806

**Comment by uclaros** [comment]
It's actually unrelated. I've already issued a PR for that one.
