### ISSUE TITLE
Temporal controller monthly time step uses 30 days instead of a month to loop

### ISSUE THREAD

**Issue by RousseauLambertLP** [qgis/QGIS#37829]
**How to Reproduce**

1. Add a WMS layer with a monthly time step, for example you can use https://geo.weather.gc.ca/geomet?LAYER=CANSIPS.MEM.ETA_TT.10
2. In the layer panel, open the layer properties and open the temporal feature. Make sure the values are: `Start date: 2013-05-01 00:00:00 / End date: 2018-10-01 00:00:00`
3. Open the Temporal controller in the `animated temporal navigation` and hit the refresh button, then change time step to `1 month`
4. Click the `go to next frame` button and you will see that it looks like it loops over 30 days instead of a full month. For the layer above here are some of the time steps I get: `2013-05-01 00:00:00, 2013-05-31 00:00:00, 2013-06-30 00:00:00, 2013-07-30 00:00:00, 2013-08-29 00:00:00, etc` 

**QGIS and OS versions**

QGIS version | 3.15.0-Master | QGIS code revision | 2e2acf9170
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.2.0dev | Running against GDAL/OGR | 3.2.0dev
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 7.2.0 | Running against PROJ | Rel. 7.2.0, November 1st, 2020
OS Version | Windows 10 (10.0) | This copy of QGIS writes debugging output.
Active python plugins | openlayers_plugin; qgis2web; qgisnetworklogger; quick_map_services; tile_plus; db_manager; MetaSearch

**Additional context**

We have seen this behavior for every monthly time interval WMS layer we have tested in the tool, which result in layers not been displayed.

CC @tomkralidis

**Comment by rduivenvoorde** [comment]
@RousseauLambertLP I'm thinking about having a look at @dminor 's pull request, but was wondering about some edge cases like:
- what if somebody chooses 30th of januari, what will be the next timestep then (given februari only has 28 days)?
- or more general 31th of a month (half of the months do not have a 31th day), what about that?
Do you have a good idea for those cases? 
Like 'remember the actual number, but in months wich do not have a 31th day, take 30? 
Or.. if there is not a 31th  (or 30, 29th) day, take the 30days (average) for that step (but remember the actual date and use it if it is possible?
I tried to test the wms example you give, but apparently it has a problem as I receive errors all the time (non time related)?

**Comment by Samweli** [comment]
> * what if somebody chooses 30th of januari, what will be the next timestep then (given februari only has 28 days)?

@rduivenvoorde I think from user perceptive, the next timestep should default to the last day of the next month(for this case it ll be 28th February)

**Comment by rduivenvoorde** [comment]
@Samweli @nyalldawson are we sure this is to be closed? In my test here with the url of the original issuer:

https://geo.weather.gc.ca/geomet?LAYER=CANSIPS.MEM.ETA_TT.10

Things work initially great. You start on the first of the month and you step through all 'firsts' of the upcoming months.

But it get heary when you set the timestep to 1 day, go to some day (like the 23th), then change to 30 days, which will by QGIS converted to 1 month(!), and then (seeing "timestep 1 month") QGIS steps 30 days again?

Also: because of the code that tries to guess what I want (if I set 7 days, make it a week etc etc), QGIS makes it harde to actually SET the start/end of the timestep.

Would it not be better to let the user really decide in what kind of steps the controller is going (like: if I want it 7 days, do not make it a week or so?)

I do understand this is getting rather complex... so don't get me wrong :-(
(I tried to make a screencast.. but failed)

@RousseauLambertLP @dminor can you confirm?

**Comment by Samweli** [comment]
> then change to 30 days, which will by QGIS converted to 1 month(!), and then (seeing "timestep 1 month") QGIS steps 30 days again?

@rduivenvoorde  I confirm this on master and QGIS 3.16


> are we sure this is to be closed?

I think this is closed, we may need to open another ticket to address the timestep setting issue.

**Comment by rduivenvoorde** [comment]
Sure? so 2 tickets?

- one which is actually the same as this one? As we cannot use the geomet-service after some fiddling? Should we not keep this one?

- one which addresses the 'guessing' behavior ( I think it is this: https://github.com/qgis/QGIS/blob/master/src/gui/qgstemporalcontrollerwidget.cpp#L541 ?)

**Comment by Samweli** [comment]
> so 2 tickets?

no , only one ticket. 

> * one which addresses the 'guessing' behavior ( I think it is this


this is the only ticket that should be opened, a fix for this should also fix other problems as this issue is the root of the other misbehaviour.

**Comment by Samweli** [comment]
ping @rduivenvoorde

**Comment by rduivenvoorde** [comment]
@Samweli I created: https://github.com/qgis/QGIS/issues/40871 yesterday

**Comment by Samweli** [comment]
I see @rduivenvoorde, but I think  https://github.com/qgis/QGIS/issues/40871 is about another issue, let me open the issue about the 'guessing' stuff.

**Comment by Samweli** [comment]
@rduivenvoorde see https://github.com/qgis/QGIS/issues/40894

**Comment by rduivenvoorde** [comment]
@RousseauLambertLP can you please test. I think this one can be closed.

**Comment by gioman** [comment]
Closing for lack of feedback.

**Comment by RousseauLambertLP** [comment]
Sorry for not replying, I was in parental leave for the last 8 months.

I tested QGIS 3.20 temporal animation tool using https://geo.weather.gc.ca/geomet?LAYER=CANSIPS.MEM.ETA_TT.10 and the monthly time step (default time step for this WMS layer) and I see the correct behavior for this layer. 
The layer loops on the months and not 30 days, which was the issue here.

Thanks all for this work!
