### ISSUE TITLE
Cannot import saved batch process of Model

### ISSUE THREAD

**Issue by neonntt** [qgis/QGIS#37838]
**Describe the bug**
I have created a model using Graphical Modeler in QGIS 3.14. The works fine as a single process.
I then created a Batch Process. The batch process also works fine.
Then I saved the Batch Process.
Now when open the saved Batch Process JSON file, it does not load and gives the following error 
  'An error has occurred while executing Python code: 

NameError: name 'QDateTime' is not defined 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python/plugins\processing\gui\BatchPanel.py", line 543, in load
    value = eval(params[param.name()])
  File "", line 1, in 
NameError: name 'QDateTime' is not defined

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.14.0-Pi Pi, 9f7028fd23 '

Second issue is that one of the input fields does not show up in the columns when we are creating the Batch process.

The saved batch file opens in QGIS 3.10, but the 'Datetime' input of the Graphical Modeler shows an error and does not work. I guess there is not 'Datetime' input in 3.10

**How to Reproduce**

1. Go to Graphical Modeler
2. Create a model
3. Run the model
4. Select 'Run as Batch Process'
5. Create the batch Process and save it.
6. Close the Batch Process and open it again
7. Load the same saved batch Process
8. See the error --> NameError: name 'QDateTime' is not defined

**QGIS and OS versions**

QGIS version
3.14.0-Pi
QGIS code revision
9f7028fd23
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
db_manager; 
MetaSearch; 
processing
![QDateTime Error](https://user-images.githubusercontent.com/61984947/87633331-d0a8e300-c758-11ea-8a46-a62fccbb6bbc.jpg)

**Additional context**

**Comment by roya0045** [comment]
Title seems quite wrong, shouldn't it be "Cannot import saved batch process of Model".

**Comment by gioman** [comment]
> though there are some minor issues

those are already reported?

**Comment by neonntt** [comment]
> > though there are some minor issues
> 
> those are already reported?

Honestly, I have not checked. I was just trying to see if the saved JSON file opens in 3.10, which it does without the error reported in 3.14.
Thanks

**Comment by neonntt** [comment]
So i checked loading the saved modeler file in 3.10 again and noticed that while no error was shown on loading, the 'Datetime' input that I was using was shown as an error in the Graphical Modeler. So it is not really working in 3.10 as indicated by me earlier.

I am taking a user input of time through the 'Datetime' input of the Graphical Modeler in 3.14. I checked and found the Datetime is not an input in 3.10 Graphical Modeler. So i guess the issue may be in  the way Datetime is being handled in 3.14 Graphical Modeler Batch Processing. 

I have attached the screenshots of the graphical modeler in 3.10 and 3.14.

Until the issue is resolved, is there another way of taking the user defined Date and Time as an input to the model?
Thanks
[Date Time QGIS error.docx](https://github.com/qgis/QGIS/files/4977727/Date.Time.QGIS.error.docx)

**Comment by neonntt** [comment]
Bug seems to be confirmed to be with 'Datetime' input. Tried a batch with a modeler which does not include 'Datetime', that works fine.

Can someone please have a look at it.

**Comment by neonntt** [comment]
Also, my final output from the modeler is an Extract by Attribute output. I would like to save it as a file (ideally a file which merges all the outputs in a Batch iteration). But when i keep the Extracted Attributes to Model Output and give it a name, it does not show up in the Batch configuration...not sure why...
