### ISSUE TITLE
New feature is hidden when created from attribute table

### ISSUE THREAD

**Issue by andreasneumann** [qgis/QGIS#37847]
When creating a new feature from the attribute table with a no-geometry table, the new feature is added, but it is added to the bottom of the form or table and not activated properly. The user has to manually scroll down to the very bottom and activate the new feature in the form manually.

I would expect either:
- QGIS would activate the new feature in the form right away in the already existing form view
- QGIS would open the new feature in a separate form window

see [video](https://youtu.be/YiaSdFL4TYs)

The issue appears in both master and QGIS 3.10.

**Comment by andreasneumann** [comment]
Might be related to issue #37846

**Comment by nyalldawson** [comment]
> QGIS would open the new feature in a separate form window

This is what we used to do, but it was rather odd behaviour because the attribute table was already visible containing the new row.

**Comment by andreasneumann** [comment]
> This is what we used to do, but it was rather odd behaviour because the attribute table was already visible containing the new row.

Yes - but the current behavior is even more odd: you add a new feature --> then you don't see anything until you get it that you have to scroll down to the very bottom. Can't QGIS do that for me? I mean the scroll-down and focus of the newly added record?

**Comment by andreasneumann** [comment]
@suricactus - I tested it - much better! It works fine if the attribute table is in "form mode", but if it is in "table mode", there is still the issue that the  newly created feature is added and not focused. Are you able to address the case of the "table mode" as well? Do you understand what I mean or should I record a video?

**Comment by suricactus** [comment]
Yup, it's clear, I will fix that these days too.

**Comment by roya0045** [comment]
Is this fixed then?

**Comment by andreasneumann** [comment]
Seems to be fixed an backported

**Comment by suricactus** [comment]
Glad to hear @andreasneumann  :)
