### ISSUE TITLE
Exporting to geopackage changes field type from DATE to DATETIME

### ISSUE THREAD

**Issue by uclaros** [qgis/QGIS#37857]
**Describe the bug**
When exporting a layer from oracle to geopackage, all input fields of type DATE are silently converted to type DATETIME in the output file.

**QGIS and OS versions**
15a4c39 on Debian testing

**Additional context**
This is a regression, it works as expected on my 3.13 build.

**Comment by rouault** [comment]
It seems this behaviour is related to a change in the Oracle provider:

commit 3fae26fe98a32e6f921448512f47ad24abd8cc1e
Author: Nyall Dawson <nyall.dawson@gmail.com>
Date:   Thu May 14 11:50:02 2020 +1000

[oracle] Treat DATE field types as datetime values
Fixes #28559

Looking at Oracle documentation, https://docs.oracle.com/cd/E11882_01/server.112/e10729/ch4datetime.htm#i1006006 , DATE can indeed stores hour, minute, seconds, so mapping to QGIS DateTime data type is appropriate

So not a bug
