### ISSUE TITLE
why not use virtual deconstructor for QgsMapTool base class?

### ISSUE THREAD

**Issue by xiaozhaolook** [qgis/QGIS#37855]
**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

I found that the base class for map tool QgsMapTool' deconstructor function without virtul keyword, is it a bug?

**Comment by m-kuhn** [comment]
It could be added for clarity but doesn't make any difference technically. See https://stackoverflow.com/questions/2198379/are-virtual-destructors-inherited

If you think it's worth it, you are very welcome to open a pull request that adds it. I'll close this anyway as there is no strict need for it.

Thank you.

**Comment by xiaozhaolook** [comment]
notice the class QgsMapTool inherit from QObject which has a virtual deconstructor, so it is really unecessary to add virtual keyword before it' subclass deconstructor, by the way , I have another question about how and when the QgsMapCanvasAnnotationItem was added to the scene of mapCanvas, can you give me some help , thank you in advance

**Comment by m-kuhn** [comment]
Hi,

> I have another question about how and when the QgsMapCanvasAnnotationItem was added to the scene of mapCanvas, can you give me some help , thank you in advance

Please note that this is not a support forum here. It's an issue tracker to keep track of bugs and feature requests for QGIS.

I would suggest to use one of the [support and discussion channels](https://qgis.org/en/site/forusers/support.html) with a clear description of your goal and what you tried so far. For your questions, I would guess the developer mailing list would be well suited.

**Comment by xiaozhaolook** [comment]
Ok, thank you
