### ISSUE TITLE
Unexpected ending 

### ISSUE THREAD

**Issue by ParishChandra** [qgis/QGIS#37853]
## User Feedback

I was just panning my project and it got crashed. I didn't even save my project, as it hardly has any SHP file opened yet. But I had created a few joins which I have to recreate again now.

## Report Details

**Crash ID**: [ed5d5ec973b366c2ee071f6886c412fcf10b8d6f](https://github.com/qgis/QGIS/search?q=ed5d5ec973b366c2ee071f6886c412fcf10b8d6f&type=Issues)

**Stack Trace**
<pre>
QMetaObject::activate :
QgsMapRendererCustomPainterJob::cancelWithoutBlocking :
QgsMapCanvas::stopPreviewJobs :
QgsMapCanvas::refreshMap :
QMetaObject::activate :
QTimer::timerEvent :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32Private::sendTimerEvent :
QEventDispatcherWin32::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.12.2-Bucure?ti
QGIS code revision: 8a1fb33634
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment]
>  QGIS Version: 3.12.2-Bucure?ti

@ParishChandra too old please update to 3.14 or use the latest LTR (3.10). If the problem persist please try a new QGIS profile (no 3rd party plugins installed).

**Comment by gioman** [comment]
Closing for lack of feedback.
