### ISSUE TITLE
QGIS 3.14 crashes when opened field calculator

### ISSUE THREAD

**Issue by Viskovitz** [qgis/QGIS#37863]
## User Feedback

After delete the QGIS3 folder and installed some plugins, I just opened the field calculator and QGIS 3.14 crashes.

## Report Details

**Crash ID**: [f0113925dcc21708f51acd83f69841e9dee86825](https://github.com/qgis/QGIS/search?q=f0113925dcc21708f51acd83f69841e9dee86825&type=Issues)

**Stack Trace**
<pre>
QBitArray::QBitArray :
QgsProcessingParameterDefinition::name qgsmaplayerdependency.h:67
QgsExpressionTreeView::updateFunctionTree qgsexpressiontreeview.cpp:295
QgsExpressionTreeView::QgsExpressionTreeView qgsexpressiontreeview.cpp:128
Ui_QgsExpressionBuilderWidgetBase::setupUi ui_qgsexpressionbuilder.h:371
QgsExpressionBuilderWidget::QgsExpressionBuilderWidget qgsexpressionbuilderwidget.cpp:79
Ui_QgsFieldCalculatorBase::setupUi ui_qgsfieldcalculatorbase.h:110
QgsFieldCalculator::QgsFieldCalculator qgsfieldcalculator.cpp:52
QgisApp::fieldCalculator qgisapp.cpp:8467
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:437
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:437
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1618
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.14.0-Pi
QGIS code revision: 9f7028fd23
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
@Viskovitz please try with a new QGIS profile, it is needed to test if this happens with a clean profile, no 3rd party plugins installed.

If the problem persist then attach the layer where this happens.

**Comment by Viskovitz** [comment]
In an new profile the field calculator start fine.

I'm installing the plugins one by one to check if it's a problem related to one of them.

**Comment by gioman** [comment]
> I'm installing the plugins one by one to check if it's a problem related to one of them.

reopen if you find is a QGIS issue and not a plugin one.
