### ISSUE TITLE
How to install QGIS 3.14 Pi on ubuntu 18.04 lts ??

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#37868]
I installed on **Ubuntu 18.04 LTS** _QGIS 3.14_ using the following commands: (as described [here](https://qgis.org/it/site/forusers/alldownloads.html#debian-ubuntu))

## using the repository - Ubuntu

`https://qgis.org/ubuntu/`

```
sudo apt-get update
sudo apt-get install gnupg software-properties-common
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 51F523511C7028C3
sudo add-apt-repository "deb     https://qgis.org/ubuntu `lsb_release -c -s` main"
sudo apt-get update
```
by running the last command:
```
pigreco@lenovo:~$ sudo apt-get install qgis qgis-plugin-grass
```
I get the following message:
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 qgis : Depends: libqgis-3d3.14.0 but it is not going to be installed
        Depends: libqgis-analysis3.14.0 but it is not going to be installed
        Depends: libqgis-app3.14.0 but it is not going to be installed
        Depends: libqgis-core3.14.0 but it is not going to be installed
        Depends: libqgis-gui3.14.0 but it is not going to be installed
        Depends: python3-qgis (= 1:3.14.0+28bionic) but
1:3.15.0+git20200708+a49cb7c9f3+28bionic-ubuntugis is to be installed
        Depends: qgis-providers (= 1:3.14.0+28bionic) but
1:3.15.0+git20200708+a49cb7c9f3+28bionic-ubuntugis is to be installed
 qgis-plugin-grass : Depends: qgis-provider-grass (= 1:3.14.0+28bionic) but
it is not going to be installed
                     Depends: grass740
                     Depends: libgdal20 (>= 1.8.0) but it is not going to be installed
                     Depends: libqgis-app3.14.0 but it is not going to be installed
                     Depends: libqgis-core3.14.0 but it is not going to be installed
                     Depends: libqgis-gui3.14.0 but it is not going to be installed
                     Depends: libqgisgrass7-3.14.0 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
email: http://osgeo-org.1560.x6.nabble.com/How-to-install-QGIS-in-Debian-11-tt5442328.html

## using the repository instead - UbuntuGIS

`https://qgis.org/ubuntugis/`

everything seems ok, but by launching `qgis_process list` I only get the `native` algorithms (190).

**Comment by gioman** [comment]
@pigreco please ask questions in the users or developers mailing lists, thanks!

By the way, you have probably mixed up repositories/sources, this is why you get the "unmet dependencies" problem. Remove any qgis, gdal, proj and geos related package, clean up your sources, update sources and try re-install.

**Comment by pigreco** [comment]
@gioman 

we have already written two emails in qgis-user and the answers are vague.
We are not developers and we do NOT understand how to solve the problem.

There is a detailed guide on how to install QGIS on linux for beginners

1. http://osgeo-org.1560.x6.nabble.com/use-the-new-standalone-console-processing-tool-in-a-server-without-a-GUI-tt5442135.html
2. http://osgeo-org.1560.x6.nabble.com/How-to-install-QGIS-in-Debian-11-tt5442328.html

**Comment by gioman** [comment]
@pigreco on a clean Ubuntu 18.04 machine

`sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key 51F523511C7028C3`

`sudo nano /etc/apt/sources.list`

and add the following line

`deb https://qgis.org/ubuntu bionic main`

save (CTRL-O) and exit (CTRL-X), then

`sudo apt-get update`

`sudo apt-get install qgis`

**Comment by pigreco** [comment]
@gioman 

by running this command from shell:

`grep '^[^#]' /etc/apt/sources.list /etc/apt/sources.list.d/*`

I get:

```
pigreco@lenovo:~$ grep '^[^#]' /etc/apt/sources.list /etc/apt/sources.list.d/*
/etc/apt/sources.list:deb http://archive.ubuntu.com/ubuntu/ bionic main restricted
/etc/apt/sources.list:deb http://archive.ubuntu.com/ubuntu/ bionic-updates main restricted
/etc/apt/sources.list:deb http://archive.ubuntu.com/ubuntu/ bionic universe
/etc/apt/sources.list:deb http://archive.ubuntu.com/ubuntu/ bionic-updates universe
/etc/apt/sources.list:deb http://archive.ubuntu.com/ubuntu/ bionic multiverse
/etc/apt/sources.list:deb http://archive.ubuntu.com/ubuntu/ bionic-updates multiverse
/etc/apt/sources.list:deb http://archive.ubuntu.com/ubuntu/ bionic-backports main restricted universe multiverse
/etc/apt/sources.list:deb http://security.ubuntu.com/ubuntu/ bionic-security main restricted
/etc/apt/sources.list:deb http://security.ubuntu.com/ubuntu/ bionic-security universe
/etc/apt/sources.list:deb http://security.ubuntu.com/ubuntu/ bionic-security multiverse
/etc/apt/sources.list.d/mc3man-ubuntu-trusty-media-bionic.list:deb http://ppa.launchpad.net/mc3man/trusty-media/ubuntu bionic main
/etc/apt/sources.list.d/mc3man-ubuntu-trusty-media-bionic.list.save:deb http://ppa.launchpad.net/mc3man/trusty-media/ubuntu bionic main
/etc/apt/sources.list.d/rmescandon-ubuntu-yq-bionic.list:deb http://ppa.launchpad.net/rmescandon/yq/ubuntu bionic main
/etc/apt/sources.list.d/rmescandon-ubuntu-yq-bionic.list.save:deb http://ppa.launchpad.net/rmescandon/yq/ubuntu bionic main
/etc/apt/sources.list.d/ubuntugis-ubuntu-ubuntugis-unstable-bionic.list:deb http://ppa.launchpad.net/ubuntugis/ubuntugis-unstable/ubuntu bionic main
/etc/apt/sources.list.d/ubuntugis-ubuntu-ubuntugis-unstable-bionic.list.save:deb http://ppa.launchpad.net/ubuntugis/ubuntugis-unstable/ubuntu bionic main
```

what's wrong??

**Comment by gioman** [comment]
> /etc/apt/sources.list.d/ubuntugis-ubuntu-ubuntugis-unstable-bionic.list:deb http://ppa.launchpad.net/ubuntugis/ubuntugis-unstable/ubuntu bionic main

@pigreco if you use the ubuntugis repo then you need to use the right qgis.org too which is

`deb https://qgis.org/ubuntugis bionic main`

you don't use ubuntugis then you need to use

`deb https://qgis.org/ubuntu bionic main`

**Comment by pigreco** [comment]
@gioman 

since I already have the ubuntugis repository, I add `deb https://qgis.org/ubuntugis bionic main`  and then I do this:

```
sudo apt-get update
sudo apt-get install gnupg software-properties-common
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 51F523511C7028C3
sudo add-apt-repository "deb https://qgis.org/ubuntugis` lsb_release -c -s` main "
sudo apt-get update
sudo apt-get install qgis qgis-plugin-grass
```

it's correct?

**Comment by gioman** [comment]
If you manually added

deb https://qgis.org/ubuntugis bionic main

then

sudo add-apt-repository "deb https://qgis.org/ubuntugis` lsb_release -c -s` main "

is not necessary. Beside this seems ok.

**Comment by pigreco** [comment]
@gioman 

OK thanks.

but I get this message:

```
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 qgis : Depends: python3-qgis (= 1:3.14.1+28bionic-ubuntugis) but 1:3.15.0+git20200708+a49cb7c9f3+28bionic-ubuntugis is to be installed
        Depends: qgis-providers (= 1:3.14.1+28bionic-ubuntugis) but 1:3.15.0+git20200708+a49cb7c9f3+28bionic-ubuntugis is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by gioman** [comment]
@pigreco try nout use ubuntugis.

Remove/comment the lines about ubuntugis, change the qgis.org repo to

deb https://qgis.org/ubuntugis bionic main

remove/purge any qgis,gdal,proj,geos related packages, update your source and install.

Also check if inside /etc/apt/sources.list.d/ you don't have other source files that point to repositories that may conflict with qgis.org one.

**Comment by pigreco** [comment]
@gioman @nyalldawson 

thanks to the help of Marco Braida (@marcobra) I managed to clean Ubuntu and install QGIS 3.14.1 with grass 7.0.4 and gdal 2.2.3

by issuing the command

`qgis_process list`

i only get 191 `native` algorithms, no grass and gdal algorithms.

throwing

`qgis_process plugin`

I get:

```
Available plugins
(* indicates loaded plugins which implement Processing providers)

   processing
```

but the processing folder is there, I have also seen that there are the algorithms grass7 (100 files * .py) and gdal (59 files * .py)

what to do??

**Comment by marcobra** [comment]
As you said me about your WSL installed Ubuntu with and the missing grass and gdal files in available list processing algorithms was permissions issue and file owner of your QGIS3.ini file we have solved with terminal commands below:
```
sudo chmod 661 $HOME/.local/share/QGIS/QGIS3/profiles/default/QGIS/QGIS3.ini
sudo chown $USER:$USER $HOME/.local/share/QGIS/QGIS3/profiles/default/QGIS/QGIS3.ini
```

**Comment by gioman** [comment]
>  was permissions issue

not a general issue anyway

**Comment by pigreco** [comment]
@marcobra @gioman @nyalldawson 

the real problem is that the QGIS3.ini file is NOT properly created in Ubuntu without gui and therefore you need to add it manually

[PythonPlugins]
Processing = true

the fact of the permissions is related to the fact that I modified the ini file from win and not from ubuntu (so it has nothing to do)

**Comment by marcobra** [comment]
ok by the way the above terminal commands dress the permissions and owner of that file

**Comment by coderzbx** [comment]
before you execute sudo apt-get update && sudo apt-get install qgis python-qgis qgis-plugin-grass
change your gpg-key to 2020, execute these commands:
wget -O - https://qgis.org/downloads/qgis-2020.gpg.key | gpg --import
gpg --fingerprint F7E06F06199EF2F2
gpg --export --armor F7E06F06199EF2F2 | apt-key add -
sudo apt-get update && sudo apt-get install qgis python-qgis qgis-plugin-grass
