### ISSUE TITLE
Add font metrics methods as expression functions

### ISSUE THREAD

**Issue by m-kuhn** [qgis/QGIS#37862]
Because it would help to dynamically calculate sizes here and there.

**Comment by nyalldawson** [comment]
If you're thinking of adding this, you'll likely need to first create a new "render context" expression scope, since these metrics are all highly render context dependent.

**Comment by pjshelton** [comment]
I think that #24291 is asking for the same thing.

**Comment by gioman** [comment]
Closing as duplicate.
