### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by mikhailov-sergey** [qgis/QGIS#37861]
**Describe the bug**

When opening the tiff-file, the amount of free RAM decreases. If you delete the layer containing the file, the occupied memory is not returned back. if In the future you also open the file and close it, the size of the occupied RAM only increases.
For example: with this file https://drive.google.com/file/d/1UH-h7FKYr-gyN5i_qcvomq04g2WVRd5a/view?usp=sharing , I got to 25gb, then there was no reason in continuing.

**How to Reproduce**

1. Open new empty project
2. Drag and drop tiff-file to QGIS
3. Remove layer (Ctrl+D)
4. Drag and drop file and remove layer again (repeat as many times as you like)
Note that the amount of free RAM increases and is not returned when you delete a layer

**QGIS and OS versions**

QGIS version: 3.15.0-Master
OS: Ubuntu 18.04
Git commit: 25179aea3a1e3ce1c44f098a8a4d1074b07a1719

**Comment by gioman** [comment]
@mikhailov-sergey I have tried on master on ubuntu 18.04 and I'm struggling to replicate (at least with a 500mb tiff as sample data).

**Comment by mikhailov-sergey** [comment]
@gioman I tried to find the reason for this memory consumption in the source code. I found that if a tiff-file needs a vrt ( function initBaseDataset in a file qgsgdalprovider.cpp ), then memory is consumed very quickly (until OS stops working). Could you explain what happens if we get into the conditions
`if ( ( hasGeoTransform`
`         && ( mGeoTransform[1] < 0.0`
`              || mGeoTransform[2] != 0.0`
`              || mGeoTransform[4] != 0.0`
`              || mGeoTransform[5] > 0.0 ) )`
`       || GDALGetGCPCount( mGdalBaseDataset ) > 0`
`       || GDALGetMetadata( mGdalBaseDataset, "RPC" ) )`
`  { `
` QgsLogger::warning( QStringLiteral( "Creating Warped VRT." ) );`
 `if ( GDALGetMetadata( mGdalBaseDataset, "RPC" ) )`
`   {`
`        mGdalDataset =`
`        QgsGdalUtils::rpcAwareAutoCreateWarpedVrt( mGdalBaseDataset, nullptr, nullptr,`
`            GRA_NearestNeighbour, 0.2, nullptr );`
`    }`
`    else`
`    {`
`      mGdalDataset =`
`        GDALAutoCreateWarpedVRT( mGdalBaseDataset, nullptr, nullptr,`
`                                 GRA_NearestNeighbour, 0.2, nullptr );`
`    }`
and, if possible, test with files that fit these conditions, is this normal application's work?

If we get into condition 
`else`
`  {`
`    mGdalDataset = mGdalBaseDataset;`
`  }`
memory is consumed normally.

**Comment by roya0045** [comment]
Unsure if related but I find that having a basemap and browsing images or remote images with a xml does gradually increase memory usage and can lead to crash due to out of memory. This occurs with 3.1416 on Win10.

**Comment by gioman** [comment]
> If we get into condition
> 
> ```c++
> else
>   {
>     mGdalDataset = mGdalBaseDataset;
>   }
> ```
> 
> memory is consumed normally.

@mikhailov-sergey have you ever submitted a patch/pull request?

**Comment by MrChebur** [comment]
I can confirm this bug in QGIS 3.18.1, see the gif animation. Adding images and removing them does not fully restore the occupied memory in Windows 10:
```
New empty qgis project memory usage: 224.1
Iteration 1: 334.2
Iteration 2: 400
Iteration 3: 446.4
and so on...
```
![memory bug](https://user-images.githubusercontent.com/20655102/116678133-6ea52b80-a9c2-11eb-82da-4ce5bdad60b2.gif)

**Comment by Pedro-Murteira** [comment]
This is still valid on QGIS 3.22.3. (Windows 10)

**Comment by elpaso** [comment]
The test project is unreachable.

**Comment by Pedro-Murteira** [comment]
> The test project is unreachable.

I've used my own files and noticed that memory usage never reverts back to exact values as before. I used the same method as @MrChebur, I didn't use the original test project.

**Comment by MrChebur** [comment]
> The test project is unreachable.

As an image for testing, I recommend using an empty bmp file, which you can easily create in any raster editor. The size of the file can be changed by changing the number of pixels, so if the size is 10 000 by 10 00 pixels, the file size will be about 300 mb.

**Comment by gioman** [comment]
@MrChebur @Pedro-Murteira I tried again (on 3.22.3) by adding and removing the same time a bunch of jp2 sentinel images:

https://drive.google.com/file/d/1-wlqRgx5ptKEltL4EVwAJOzNkQFdQKSG/view?usp=sharing

and every time, after removing the images, QGIS ram consumption returned to normal levels. If you can please link sample data that demonstrate the problem.

**Comment by MrChebur** [comment]
@gioman 
Tested memory leak again (OS Windows 10) with QGIS version 3.22.3-Białowieża QGIS code revision1628765ec7 and this bmp file:
[10 000 by 10 000 pixels empty file.zip](https://github.com/qgis/QGIS/files/8000070/10.000.by.10.000.pixels.empty.file.zip)

![qgis-bin_tNmCXC0aI2](https://user-images.githubusercontent.com/20655102/152472184-df894e26-f524-4392-894d-67d811de5203.gif)

**Comment by gioman** [comment]
> Tested the memory leak again with this bmp file (the bug was confirmed, see video below):

@MrChebur not here, even with your data and following exactly what you show, QGIS returns always to normal RAM usage, which in my case is about 240mb.

**Comment by MrChebur** [comment]
@gioman 
Please paste here the information about QGIS (located in: `Help` -> `About`).

**Comment by gioman** [comment]
QGIS version | 3.22.3-Białowieża | QGIS code revision | 1628765ec7
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
Compiled against GEOS | 3.10.0-CAPI-1.16.0 | Running against GEOS | 3.10.2-CAPI-1.16.0
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
GroupStats | 2.2.5
inspireatomclient | 0.8.1
lizmap | 3.7.1
qfieldsync | v3.4.4
quick_map_services | 0.19.27
raster_tracer | 0.3.2
SpreadsheetLayers | 2.0.1
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.5
otbprovider | 2.12.99
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.22.3-Białowieża
QGIS code revision
[1628765ec7](https://github.com/qgis/QGIS/commit/1628765ec7)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
Compiled against GEOS
3.10.0-CAPI-1.16.0
Running against GEOS
3.10.2-CAPI-1.16.0
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009




Active Python plugins

**Comment by Pedro-Murteira** [comment]
I've also tested this several times, and the result is always around the same numbers (RAM Usage). I used the attached file to test it. The build-up on RAM is very minor but it doesn't completely reset.
Iteration 1 (start of QGIS): 195
Iteration 2: 202
Iteration 3: 207
Iteration 4: 209
Iteration 5: 213

**Comment by Pedro-Murteira** [comment]
QGIS version
3.22.3-Białowieża
QGIS code revision
1628765ec7
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.0-CAPI-1.16.0
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

**Comment by MrChebur** [comment]
The memory leak still persists in QGIS 3.26.2-Buenos Aires (QGIS code revision feec3d3b12f).
Can anyone confirm this? (other than @gioman, who couldn't reproduce it).

**Comment by kannes** [comment]
This does not replicate it for me with 3.30 on Linux but maybe someone can build a reproducible script like this?

```
for i in range(50):
    print(i)
    raster_file = processing.run(
        "native:createrandomnormalrasterlayer", 
        {
            'EXTENT':'-25,25,-25,25 [EPSG:4326]',
            'TARGET_CRS':QgsCoordinateReferenceSystem('EPSG:4326'),
            'PIXEL_SIZE':0.01,
            'OUTPUT_TYPE':0,
            'MEAN':0,
            'STDDEV':1,
            'OUTPUT':'TEMPORARY_OUTPUT'
        }
    )["OUTPUT"]

    raster_layer = QgsRasterLayer(raster_file, "layer")
    QgsProject.instance().addMapLayer(raster_layer)
    QgsProject.instance().removeAllMapLayers()
```

**Comment by MrChebur** [comment]
@kannes 
 Windows 10 test with bmp raster file: [10 000 by 10 000 pixels empty file.zip](https://github.com/qgis/QGIS/files/8000070/10.000.by.10.000.pixels.empty.file.zip) 
Results: [Memory leak (insert script output here to show your results).xlsx](https://github.com/qgis/QGIS/files/11551835/Memory.leak.insert.script.output.here.to.show.your.results.xlsx)


Use this script to reproduce:
``` python
import psutil  # this is not standard library. Check https://pypi.org/project/psutil/


def find_process_by_name(name):
    for pid in psutil.pids():
        process_ = psutil.Process(pid)
        if process_.name() == name:
            return process_


path_to_raster = r'C:\10 000 by 10 000 pixels empty file.bmp'
process_name = 'qgis-bin.exe'

process = find_process_by_name(process_name)
if process is None:
    raise f'{process_name} not found!'

columns = ['iteration'] + list(process.memory_info()._fields)
print('\t'.join(columns))

for iteration in range(1, 1000):

    mem_info = process.memory_info()  # https://psutil.readthedocs.io/en/latest/#psutil.Process.memory_info
    mem_info_as_string = [str(value) for value in mem_info]
    mem_values = [str(iteration)] + mem_info_as_string
    print('\t'.join(mem_values))

    rlayer = QgsRasterLayer(path_to_raster, f"new_rasert_layer_{iteration}")
    if not rlayer.isValid():
        raise ValueError('Input layer is not valid!')
    QgsProject.instance().addMapLayer(rlayer)
    QgsProject.instance().removeAllMapLayers()
```

**Comment by kannes** [comment]
Nice! With your script I can confirm that this has a memory leak on Archlinux with QGIS 3.30.2-'s-Hertogenbosch as well.

**Comment by MrChebur** [comment]
@gioman Can we reopen this issue, since it is confirmed?

**Comment by kannes** [comment]
ping @gioman
