### ISSUE TITLE
Can't move the properties window in QGIS when using it in Ubuntu.

### ISSUE THREAD

**Issue by 1-Sean** [qgis/QGIS#37878]
**Describe the bug**
Can't move/drag the properties window in QGIS when using it in Ubuntu.  

**QGIS and OS versions**

QGIS version | 3.10.7-A Coruña | QGIS code revision | 7b4ca4c8d0
-- | -- | -- | --
Compiled against Qt | 5.12.8 | Running against Qt | 5.12.8
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.2 (Ubuntu 12.2-4) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Ubuntu 20.04 LTS

**Additional context**

Moving the he attribute table or other secondary windows works fine. Just seems to be a problem for the properties and options window .

**Comment by Gustry** [comment]
This is a setting in your Gnome settings.
https://github.com/qgis/QGIS/issues/36658
