### ISSUE TITLE
qgis_process incorrectly lists GRASS algorithms even if GRASS is not installed

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/QGIS#37877]
**Describe the bug**

The `qgis_process list` command incorrectly lists the GRASS algorithms among the available processing algorithms even when GRASS is not installed in the system.

Conversely, SAGA algorithms are correctly not listed if SAGA is not installed.

**QGIS and OS versions**

QGIS 3.15.0 e91abdc23f (qgis-dev 3.15.0-18) on Windows 10.

**Additional context**

PR https://github.com/qgis/QGIS/pull/34617 New standalone console tool for running processing algorithms

**Comment by alexbruy** [comment]
IMHO this is not a bug. This tool just lists algorithms from **enabled** providers. Backends setup/installation is not related to the Processing as we ship algorithms with QGIS not with backends.

**Comment by agiudiceandrea** [comment]
Anyway, I think currently there is an inconsistency in the behavior of `qgis_process list` in handling GRASS, SAGA and OTB algorithms.

While GRASS algs are always listed, even when GRASS is not installed, SAGA and OTB algorithms are not listed if SAGA is not installed or OTB "can not be activated":

https://github.com/qgis/QGIS/blob/d0dda27afa2cda4c7a21e1ed89adbb427788b7a2/python/plugins/processing/algs/saga/SagaAlgorithmProvider.py#L95-L100

https://github.com/qgis/QGIS/blob/9fedd2c581e23b0eaac024a9b62530d2428f2f16/python/plugins/processing/algs/otb/OtbAlgorithmProvider.py#L128-L130


Moreover `qgis_process list` generates a list of "Available algorithms" and the word "available" me think of algs that can be used. But I'm not a native speakers of English, so I may have misunderstood.
