### ISSUE TITLE
Wiederherstellung einer angefangenen Digitalisierung von Polygonen, Polylinien

### ISSUE THREAD

**Issue by LadyxD** [qgis/QGIS#37873]
Hallo QGIS Entwickler,
ich hätte folgende Bitte, die man bei einer neuen QGIS Version mit berücksichtigen könnte.
Beim Digitalisieren, besonders von umfangreichen Gebieten mit vielen Details wird das angefangene Polygon erst gespeichert wenn man die Rechte Maustaste betätigt, Drückt man jedoch ausversehen beispielsweise die ESC-Taste ist das gesamte Polygon, was man digitalisiert hat, gelöscht und leider auch nicht über Rückgängig Option oder STRG+Z wiederherzustellen. Sodass man leider von vorne wieder anfangen kann. Es wäre schön wenn es eine Option gebe, dass die angefangenen digitalisierten Daten wiederherzustellen sind.

Lieber Gruß

LadyxD

**Comment by gioman** [comment]
@LadyxD please file bug tickets and feature requests in English, thanks for understanding!
