### ISSUE TITLE
Crashing randomly

### ISSUE THREAD

**Issue by GeoSheds** [qgis/QGIS#37882]
## User Feedback

Random, clicking a layer to view attribute table and closing. 

## Report Details

**Crash ID**: [7bbb52d1d974c4ad87adc808f1f7715c2091b6b0]('https://github.com/qgis/QGIS/search?q=7bbb52d1d974c4ad87adc808f1f7715c2091b6b0&type=Issues')

**Stack Trace**
<pre>
memcmp :
CPLStringList::empty :
QgsRasterDataProvider::block :
QgsSingleBandColorDataRenderer::block :
QgsBrightnessContrastFilter::block :
QgsHueSaturationFilter::block :
QgsRasterResampleFilter::block :
QgsRasterProjector::block :
QgsRasterIterator::readNextRasterPartInternal :
QgsRasterDrawer::draw :
QgsRasterLayerRendererFeedback::onNewData :
CPLStringList::PartialFindString :
CPLStringList::empty :
QgsRasterDataProvider::block :
QgsSingleBandColorDataRenderer::block :
QgsBrightnessContrastFilter::block :
QgsHueSaturationFilter::block :
QgsRasterResampleFilter::block :
QgsRasterProjector::block :
QgsRasterIterator::readNextRasterPartInternal :
QgsRasterDrawer::draw :
QgsRasterLayerRenderer::render :
QgsMapRendererCustomPainterJob::doRender :
QgsMapRendererCustomPainterJob::staticRender :
QgsMapRendererJob::renderingTime :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.1-A Coru�a
QGIS code revision: ef24c526da
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
>  QGIS Version: 3.10.1-A Coru�a

@GeoSheds too old, you must upgrade to 3.10.7. If the problem persist you must try with a new QGIS profile, no 3rd party plugins installed.

**Comment by GeoSheds** [comment]
Thank you very much. Really appreciate your time, I’ll give it a go.
Regards
Geo

**Comment by GeoSheds** [comment]
## User Feedback

Update: Updated from 3.10 to 3.14; Continues to crash; Using name and polygon layers and google earth xyz layer. It may be a layer issue I'm not sure how to diagnose the issue. 

## Report Details

**Crash ID**: [cb2105fc0af59cf95a9466685fee0bc2952bf7cf](https://github.com/qgis/QGIS/search?q=cb2105fc0af59cf95a9466685fee0bc2952bf7cf&type=Issues)


**Stack Trace**
<pre>
memcmp :
QgsWmsProvider::readBlock qgswmsprovider.cpp:998
QgsRasterDataProvider::block :
QgsSingleBandColorDataRenderer::block :
QgsBrightnessContrastFilter::block :
QgsHueSaturationFilter::block :
QgsRasterResampleFilter::block :
QgsRasterProjector::block :
QgsRasterIterator::readNextRasterPartInternal :
QgsRasterDrawer::draw :
QgsRasterLayerRendererFeedback::onNewData :
QgsWmsProvider::draw qgswmsprovider.cpp:947
QgsWmsProvider::readBlock qgswmsprovider.cpp:977
QgsRasterDataProvider::block :
QgsSingleBandColorDataRenderer::block :
QgsBrightnessContrastFilter::block :
QgsHueSaturationFilter::block :
QgsRasterResampleFilter::block :
QgsRasterProjector::block :
QgsRasterIterator::readNextRasterPartInternal :
QgsRasterDrawer::draw :
QgsRasterLayerRenderer::render :
QgsMapRendererParallelJob::renderLayerStatic :
QgsArchive::zip :
QgsImageOperation::overlayColor :
QgsArchive::zip :
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>


**QGIS Info**
QGIS Version: 3.14.0-Pi
QGIS code revision: 9f7028fd23
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
>  Continues to crash;

@GeoSheds you must try with a new QGIS profile, settings > user profiles > new profile

**Comment by gioman** [comment]
Closing for lack of feedback.
