### ISSUE TITLE
layer properties dialog takes >30 seconds to show up for vector layers when qgis profile folder is on network drive

### ISSUE THREAD

**Issue by beerockxs** [qgis/QGIS#37899]
Using QGIS 3.14 on windows with a fresh user profile and no non-core plugins installed, the layer properties dialog takes >30 seconds to appear after clicking on it. Using the same database with QGIS 2.18, it takes about 1 second.

**Comment by andreasneumann** [comment]
might be the same issue as #34942 ?

Can you please check if this is the case? If yes, then this is solved in the nightly.

**Comment by beerockxs** [comment]
This happens with a project that has only the single layer, so I don't believe it's #34942

**Comment by beerockxs** [comment]
This applies to shapefile layers as well, for raster layers, the delay is < 1 sec

**Comment by beerockxs** [comment]
I also tried using the current nightly from OSGEO4W, and it still happens.


QGIS version | 3.15.0-Master | QGIS code revision | 3af038f861
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.2.0dev | Running against GDAL/OGR | 3.2.0dev
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 7.2.0 | Running against PROJ | Rel. 7.2.0, November 1st, 2020
OS Version | Windows 7 SP 1 (6.1) | This copy of QGIS writes debugging output.
Active python plugins | db_manager; MetaSearch; processing

**Comment by gioman** [comment]
@beerockxs just to be sure... try with a new QGIS profile.

**Comment by beerockxs** [comment]
As I said in the initial report, I did create a new profile. With QGIS 3.10, it takes also less than 1 second.

**Comment by gioman** [comment]
>  I did create a new profile

sorry I overlooked that.

**Comment by uclaros** [comment]
Does this also happen if you try with a shapefile located on a local folder and not on a mapped drive or over the network? Could be windows networking issues.

**Comment by beerockxs** [comment]
It also happens with local shapefiles.

**Comment by roya0045** [comment]
The master show was post-fix regarding the mask loading. There is something else at play.

**Comment by elitonfilho** [comment]
I can confirm the same: properties dialog on a single geopackage file takes ~10 seconds to open on QGIS 3.14.1

Version details:

QGIS version | 3.14.1-Pi | QGIS code revision | de08d6b71d
-- | -- | -- | --
Compiled against Qt | 5.11.3 | Running against Qt | 5.11.3
Compiled against GDAL/OGR | 2.4.0 | Running against GDAL/OGR | 2.4.0
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.27.2 | Running against SQLite | 3.27.2
PostgreSQL Client Version | 11.7 (Debian 11.7-0+deb10u1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.10.4
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Debian GNU/Linux 10 (buster)
Active python plugins | db_manager; processing

**Comment by beerockxs** [comment]
Is there anything I as a user can do to help find the cause for this?

**Comment by gioman** [comment]
> Is there anything I as a user can do to help find the cause for this?

@beerockxs hard to say, seems a local issue. Have you tried on a different machine?

**Comment by beerockxs** [comment]
Further debugging revels that this is tied to the location of the qgis profile folder. When I move it out of my windows profile folder, which is on a networked folder, the dialog pops up in ca. 1.5 seconds.

**Comment by roya0045** [comment]
Why is your profile folder on a network folder and not locally?

**Comment by uclaros** [comment]
Corporate environment with roaming profiles probably

**Comment by beerockxs** [comment]
Exactly

**Comment by NathanW2** [comment]
If you want to have a crack at possibly debugging this.  There is a tool
called Procmon. It's quite handy to show timings for how long each
operation takes like reading files, etc, it might be loading a lot of small
files or something which is slowing something down.  I can put together
some notes on how to use it if you haven't used it before.

**Comment by beerockxs** [comment]
I'll gladly look into that, some pointers on how to use it would be great.

**Comment by beerockxs** [comment]
I looked into this a bit, there are a few operations that happen multiple times and take quite long, like these:

09:49:24,8723953	qgis-dev-bin-g7.exe	17640	CreateFile	\\bamdefm-fsv01.prod.bam.nl\..\.designer\backup\.designer\xpm\new_attribute.png	BAD NETWORK NAME	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: N, ShareMode: Read, Write, AllocationSize: n/a
09:49:24,9356350	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	NOT FOUND	Control: FSCTL_DFS_GET_REFERRALS
09:49:25,0001448	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	Control: FSCTL_NETWORK_DELETE_CONNECTION
09:49:25,0002462	qgis-dev-bin-g7.exe	17640	CloseFile	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	
09:49:25,1412229	qgis-dev-bin-g7.exe	17640	CreateFile	C:\Users\sebastian.brocks\AppData\Local\mime	NAME NOT FOUND	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a
09:49:25,1421748	qgis-dev-bin-g7.exe	17640	CreateFile	C:\ProgramData\mime	NAME NOT FOUND	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a
09:49:25,1431132	qgis-dev-bin-g7.exe	17640	CreateFile	C:\OSGeo4W64\bin\mime	NAME NOT FOUND	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a
09:49:25,1436424	qgis-dev-bin-g7.exe	17640	CreateFile	C:\OSGeo4W64\bin\data\mime	PATH NOT FOUND	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a
09:49:25,1441814	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\ppp_de_users$\sebastian.brocks	INVALID PARAMETER	Control: FSCTL_IS_VOLUME_MOUNTED
09:49:25,1448691	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	NOT FOUND	Control: FSCTL_DFS_GET_REFERRALS
09:49:25,2065468	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	Control: FSCTL_NETWORK_DELETE_CONNECTION
09:49:25,2065914	qgis-dev-bin-g7.exe	17640	CloseFile	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	
09:49:25,3183492	qgis-dev-bin-g7.exe	17640	CreateFile	\\bamdefm-fsv01.prod.bam.nl\..\.designer\backup\.designer\xpm\new_attribute.png	BAD NETWORK NAME	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: N, ShareMode: Read, Write, AllocationSize: n/a
09:49:25,3189085	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	NOT FOUND	Control: FSCTL_DFS_GET_REFERRALS
09:49:25,3765968	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	Control: FSCTL_NETWORK_DELETE_CONNECTION
09:49:25,3767530	qgis-dev-bin-g7.exe	17640	CloseFile	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	
09:49:25,4849751	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	NOT FOUND	Control: FSCTL_DFS_GET_REFERRALS
09:49:25,5432678	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	Control: FSCTL_NETWORK_DELETE_CONNECTION
09:49:25,5432964	qgis-dev-bin-g7.exe	17640	CloseFile	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	
09:49:25,6703678	qgis-dev-bin-g7.exe	17640	CreateFile	\\bamdefm-fsv01.prod.bam.nl\..\.designer\backup\.designer\xpm\new_attribute.png.bmp	BAD NETWORK NAME	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: N, ShareMode: Read, Write, AllocationSize: n/a
09:49:25,6707897	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	NOT FOUND	Control: FSCTL_DFS_GET_REFERRALS
09:49:25,7122242	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	Control: FSCTL_NETWORK_DELETE_CONNECTION
09:49:25,7122611	qgis-dev-bin-g7.exe	17640	CloseFile	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	
09:49:25,8227188	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	NOT FOUND	Control: FSCTL_DFS_GET_REFERRALS
09:49:25,8645450	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	Control: FSCTL_NETWORK_DELETE_CONNECTION
09:49:25,8646141	qgis-dev-bin-g7.exe	17640	CloseFile	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	
09:49:26,0093225	qgis-dev-bin-g7.exe	17640	CreateFile	\\bamdefm-fsv01.prod.bam.nl\..\.designer\backup\.designer\xpm\new_attribute.png.cur	BAD NETWORK NAME	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: N, ShareMode: Read, Write, AllocationSize: n/a
09:49:26,0101426	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	NOT FOUND	Control: FSCTL_DFS_GET_REFERRALS
09:49:26,0877576	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	Control: FSCTL_NETWORK_DELETE_CONNECTION
09:49:26,0878008	qgis-dev-bin-g7.exe	17640	CloseFile	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	
09:49:26,2345794	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	NOT FOUND	Control: FSCTL_DFS_GET_REFERRALS
09:49:26,3342663	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	Control: FSCTL_NETWORK_DELETE_CONNECTION
09:49:26,3343181	qgis-dev-bin-g7.exe	17640	CloseFile	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	
09:49:26,5046386	qgis-dev-bin-g7.exe	17640	CreateFile	\\bamdefm-fsv01.prod.bam.nl\..\.designer\backup\.designer\xpm\new_attribute.png.gif	BAD NETWORK NAME	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: N, ShareMode: Read, Write, AllocationSize: n/a
09:49:26,5055897	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	NOT FOUND	Control: FSCTL_DFS_GET_REFERRALS
09:49:26,5802599	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	Control: FSCTL_NETWORK_DELETE_CONNECTION
09:49:26,5802964	qgis-dev-bin-g7.exe	17640	CloseFile	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	
09:49:26,7144483	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	NOT FOUND	Control: FSCTL_DFS_GET_REFERRALS
09:49:26,7780971	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	Control: FSCTL_NETWORK_DELETE_CONNECTION
09:49:26,7781738	qgis-dev-bin-g7.exe	17640	CloseFile	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	
09:49:26,9304154	qgis-dev-bin-g7.exe	17640	CreateFile	\\bamdefm-fsv01.prod.bam.nl\..\.designer\backup\.designer\xpm\new_attribute.png.icns	BAD NETWORK NAME	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: N, ShareMode: Read, Write, AllocationSize: n/a
09:49:26,9307512	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	NOT FOUND	Control: FSCTL_DFS_GET_REFERRALS
09:49:27,0288895	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	Control: FSCTL_NETWORK_DELETE_CONNECTION
09:49:27,0289386	qgis-dev-bin-g7.exe	17640	CloseFile	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	
09:49:27,1182244	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	NOT FOUND	Control: FSCTL_DFS_GET_REFERRALS
09:49:27,1627355	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	Control: FSCTL_NETWORK_DELETE_CONNECTION
09:49:27,1627625	qgis-dev-bin-g7.exe	17640	CloseFile	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	
09:49:27,2603952	qgis-dev-bin-g7.exe	17640	CreateFile	\\bamdefm-fsv01.prod.bam.nl\..\.designer\backup\.designer\xpm\new_attribute.png.ico	BAD NETWORK NAME	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: N, ShareMode: Read, Write, AllocationSize: n/a
09:49:27,2610883	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	NOT FOUND	Control: FSCTL_DFS_GET_REFERRALS
09:49:27,3525992	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	Control: FSCTL_NETWORK_DELETE_CONNECTION
09:49:27,3526307	qgis-dev-bin-g7.exe	17640	CloseFile	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	
09:49:27,4713027	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	NOT FOUND	Control: FSCTL_DFS_GET_REFERRALS
09:49:27,5197334	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	Control: FSCTL_NETWORK_DELETE_CONNECTION
09:49:27,5197913	qgis-dev-bin-g7.exe	17640	CloseFile	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	
09:49:27,6155116	qgis-dev-bin-g7.exe	17640	CreateFile	\\bamdefm-fsv01.prod.bam.nl\..\.designer\backup\.designer\xpm\new_attribute.png.jpeg	BAD NETWORK NAME	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: N, ShareMode: Read, Write, AllocationSize: n/a
09:49:27,6159524	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	NOT FOUND	Control: FSCTL_DFS_GET_REFERRALS
09:49:27,6741186	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	Control: FSCTL_NETWORK_DELETE_CONNECTION
09:49:27,6741692	qgis-dev-bin-g7.exe	17640	CloseFile	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	
09:49:27,7955948	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	NOT FOUND	Control: FSCTL_DFS_GET_REFERRALS
09:49:27,8516116	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	Control: FSCTL_NETWORK_DELETE_CONNECTION
09:49:27,8516797	qgis-dev-bin-g7.exe	17640	CloseFile	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	
09:49:27,9880747	qgis-dev-bin-g7.exe	17640	CreateFile	\\bamdefm-fsv01.prod.bam.nl\..\.designer\backup\.designer\xpm\new_attribute.png.jpg	BAD NETWORK NAME	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: N, ShareMode: Read, Write, AllocationSize: n/a
09:49:27,9885913	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	NOT FOUND	Control: FSCTL_DFS_GET_REFERRALS
09:49:28,0568026	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	Control: FSCTL_NETWORK_DELETE_CONNECTION
09:49:28,0568518	qgis-dev-bin-g7.exe	17640	CloseFile	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	
09:49:28,2228248	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	NOT FOUND	Control: FSCTL_DFS_GET_REFERRALS
09:49:28,2739475	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	Control: FSCTL_NETWORK_DELETE_CONNECTION
09:49:28,2740796	qgis-dev-bin-g7.exe	17640	CloseFile	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	
09:49:28,3597081	qgis-dev-bin-g7.exe	17640	CreateFile	\\bamdefm-fsv01.prod.bam.nl\..\.designer\backup\.designer\xpm\new_attribute.png.pbm	BAD NETWORK NAME	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: N, ShareMode: Read, Write, AllocationSize: n/a
09:49:28,3611508	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	NOT FOUND	Control: FSCTL_DFS_GET_REFERRALS
09:49:28,4076290	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	Control: FSCTL_NETWORK_DELETE_CONNECTION
09:49:28,4076742	qgis-dev-bin-g7.exe	17640	CloseFile	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	
09:49:28,5248141	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	NOT FOUND	Control: FSCTL_DFS_GET_REFERRALS
09:49:28,5764115	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	Control: FSCTL_NETWORK_DELETE_CONNECTION
09:49:28,5764386	qgis-dev-bin-g7.exe	17640	CloseFile	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	
09:49:28,7045231	qgis-dev-bin-g7.exe	17640	CreateFile	\\bamdefm-fsv01.prod.bam.nl\..\.designer\backup\.designer\xpm\new_attribute.png.pgm	BAD NETWORK NAME	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: N, ShareMode: Read, Write, AllocationSize: n/a
09:49:28,7048495	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	NOT FOUND	Control: FSCTL_DFS_GET_REFERRALS
09:49:28,7523643	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	Control: FSCTL_NETWORK_DELETE_CONNECTION
09:49:28,7523946	qgis-dev-bin-g7.exe	17640	CloseFile	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	
09:49:28,9058190	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	NOT FOUND	Control: FSCTL_DFS_GET_REFERRALS
09:49:28,9509764	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	Control: FSCTL_NETWORK_DELETE_CONNECTION
09:49:28,9510120	qgis-dev-bin-g7.exe	17640	CloseFile	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	
09:49:29,0864858	qgis-dev-bin-g7.exe	17640	CreateFile	\\bamdefm-fsv01.prod.bam.nl\..\.designer\backup\.designer\xpm\new_attribute.png.png	BAD NETWORK NAME	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: N, ShareMode: Read, Write, AllocationSize: n/a
09:49:29,0867688	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	NOT FOUND	Control: FSCTL_DFS_GET_REFERRALS
09:49:29,1507730	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	Control: FSCTL_NETWORK_DELETE_CONNECTION
09:49:29,1508489	qgis-dev-bin-g7.exe	17640	CloseFile	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	
09:49:29,2779303	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	NOT FOUND	Control: FSCTL_DFS_GET_REFERRALS
09:49:29,3609193	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	Control: FSCTL_NETWORK_DELETE_CONNECTION
09:49:29,3609741	qgis-dev-bin-g7.exe	17640	CloseFile	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	
09:49:29,4577570	qgis-dev-bin-g7.exe	17640	CreateFile	\\bamdefm-fsv01.prod.bam.nl\..\.designer\backup\.designer\xpm\new_attribute.png.ppm	BAD NETWORK NAME	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: N, ShareMode: Read, Write, AllocationSize: n/a
09:49:29,4581637	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	NOT FOUND	Control: FSCTL_DFS_GET_REFERRALS
09:49:29,5215801	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	Control: FSCTL_NETWORK_DELETE_CONNECTION
09:49:29,5216057	qgis-dev-bin-g7.exe	17640	CloseFile	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	
09:49:29,6258492	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	NOT FOUND	Control: FSCTL_DFS_GET_REFERRALS
09:49:29,6795593	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	Control: FSCTL_NETWORK_DELETE_CONNECTION
09:49:29,6795941	qgis-dev-bin-g7.exe	17640	CloseFile	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	
09:49:29,7532181	qgis-dev-bin-g7.exe	17640	CreateFile	\\bamdefm-fsv01.prod.bam.nl\..\.designer\backup\.designer\xpm\new_attribute.png.svg	BAD NETWORK NAME	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: N, ShareMode: Read, Write, AllocationSize: n/a
09:49:29,7540867	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	NOT FOUND	Control: FSCTL_DFS_GET_REFERRALS
09:49:29,8144863	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	Control: FSCTL_NETWORK_DELETE_CONNECTION
09:49:29,8145440	qgis-dev-bin-g7.exe	17640	CloseFile	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	
09:49:29,9021827	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	NOT FOUND	Control: FSCTL_DFS_GET_REFERRALS
09:49:29,9524472	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	Control: FSCTL_NETWORK_DELETE_CONNECTION
09:49:29,9525455	qgis-dev-bin-g7.exe	17640	CloseFile	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	
09:49:30,0966981	qgis-dev-bin-g7.exe	17640	CreateFile	\\bamdefm-fsv01.prod.bam.nl\..\.designer\backup\.designer\xpm\new_attribute.png.svgz	BAD NETWORK NAME	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: N, ShareMode: Read, Write, AllocationSize: n/a
09:49:30,0971792	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	NOT FOUND	Control: FSCTL_DFS_GET_REFERRALS
09:49:30,1494310	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	Control: FSCTL_NETWORK_DELETE_CONNECTION
09:49:30,1495056	qgis-dev-bin-g7.exe	17640	CloseFile	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	
09:49:30,2971852	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	NOT FOUND	Control: FSCTL_DFS_GET_REFERRALS
09:49:30,3486904	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	Control: FSCTL_NETWORK_DELETE_CONNECTION
09:49:30,3487218	qgis-dev-bin-g7.exe	17640	CloseFile	\\bamdefm-fsv01.prod.bam.nl\IPC$	SUCCESS	
09:49:30,5160952	qgis-dev-bin-g7.exe	17640	CreateFile	\\bamdefm-fsv01.prod.bam.nl\..\.designer\backup\.designer\xpm\new_attribute.png.tga	BAD NETWORK NAME	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: N, ShareMode: Read, Write, AllocationSize: n/a
09:49:30,5163492	qgis-dev-bin-g7.exe	17640	FileSystemControl	\\bamdefm-fsv01.prod.bam.nl\IPC$	NOT FOUND	Control: FSCTL_DFS_GET_REFERRALS

**Comment by Pedro-Murteira** [comment]
Hello @beerockxs I've tested this issue on QGIS 3.22.3. and I'm not being able to reproduce it. Did you come across this issue more recently?
