### ISSUE TITLE
Editing a PostGIS layer that has a foreign key consisting of multiple columns does not work when using relation reference widget

### ISSUE THREAD

**Issue by beerockxs** [qgis/QGIS#37896]
Using QGIS 3.14 on Windows, when I have a postgis layer that has a foreign key consisting of two columns, I can't edit the two columns when I set the relation reference widget type on both columns.

**Comment by beerockxs** [comment]
However, when I set the reference widget type only on the first column, it works, but only partially. The dropdown that appears when clicking in the attribute cell of the first column has an extra entry like this "(1) ()" where 1 is the value of the first column, in addition to the populated list of all entries in the referenced table that are listed with the appopriate display expression.

**Comment by Pedro-Murteira** [comment]
@beerockxs Hello, is it still valid on recent versions?
