### ISSUE TITLE
QGIS not working after installed Postgres

### ISSUE THREAD

**Issue by wdhawthorne** [qgis/QGIS#37908]
## User Feedback

After I install Postgres and Giswater, and uninstalled them, now I can't use QGIS again. I've already uninstalled them and installed them back, clear registries many times, but nothing seems to work.

## Report Details

**Crash ID**: [70507434ed785a113cdb249200d2a9737eb8e5fe](https://github.com/qgis/QGIS/search?q=70507434ed785a113cdb249200d2a9737eb8e5fe&type=Issues)

**Stack Trace**
<pre>
operator<< :
operator<< :
QMetaType::save :
QVariant::save :
operator<< :
QSettings::value :
QSettings::value :
QSettings::sync :
QThreadPool::maxThreadCount :
QUrlQuery::setQueryItems :
QXmlStreamStringRef::~QXmlStreamStringRef :
QSettings::QSettings :
QgsSettings::QgsSettings :
QgsPluginRegistry::loadPythonPlugin :
QgsPluginRegistry::restoreSessionPlugins :
QgisApp::QgisApp :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.6-A Coru�a
QGIS code revision: ec80021f49
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by uclaros** [comment]
Take a look at #34870

**Comment by gioman** [comment]
> Take a look at #34870

yes, @wdhawthorne remove manually your user profile folder and see if it helps.

**Comment by wdhawthorne** [comment]
Thanks a lot guys, it worked.
