### ISSUE TITLE
Refactor Fields Expression Dialogue does not recognise fields from the selected table

### ISSUE THREAD

**Issue by thillyard** [qgis/QGIS#37912]
**Describe the bug**
when developing an expression in the "Expression Dialog" of  the "Refactor Fields" tool, the preview reports that the "Expression is invalid" when entering a field that exists in the table that the refactor field is operating on. This is despite the field existing and the expression being valid

**How to Reproduce**
1. Use the refactor fields tool from the processing toolbox on any feature layer
2. go into the "Expression Dialog" for any field to be mapped
3. even with the default expression of the current field that is mapped the expression is shown as invalid
4. When clicking on "(more info)" the user is presented with "Eval Error: Column '<chosen_field>' not found"  where the <chosen_field> is the desired field to be mapped.

**QGIS and OS versions**

QGIS version
3.14.1-Pi
QGIS code revision
de08d6b71d
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
crayfish; 
FreehandRasterGeoreferencer; 
go2streetview; 
icsm_ntv2_transformer; 
kmltools; 
LAStools; 
latlontools; 
mapswipetool_plugin; 
mmqgis; 
NNJoin; 
openlayers_plugin; 
OSMDownloader; 
qconsolidate3; 
qNote; 
SDEllipse; 
searchlayers; 
SRTM-Downloader; 
StreetView; 
TerrainShading; 
timemanager; 
valuetool; 
db_manager; 
MetaSearch; 
processing

**Comment by gioman** [comment]
Confirmed on master too.
