### ISSUE TITLE
Crash running Viewshed

### ISSUE THREAD

**Issue by mrpaulday** [qgis/QGIS#37915]
## User Feedback

Running Viewshed overnight, crashed in the morning
Large 5m DEM (OS Terrain 5), 75 targets, calculating cumulative viewshed to 100km

## Report Details

**Crash ID**: [6bdc15eef93fa06fad98a53b9bfd465135722e1f](https://github.com/qgis/QGIS/search?q=6bdc15eef93fa06fad98a53b9bfd465135722e1f&type=Issues)

**Stack Trace**
<pre>
QObject::thread :
`QgsProcessingAlgorithm::runPrepared'::`1'::catch$46 qgsprocessingalgorithm.cpp:519
_CallSettingFrame handlers.asm:50
__FrameHandler3::CxxCallCatchBlock frame.cpp:1499
RcConsolidateFrames :
QgsProcessingAlgorithm::runPrepared qgsprocessingalgorithm.cpp:502
QgsProcessingAlgRunnerTask::run qgsprocessingalgrunnertask.cpp:66
sipQgsProcessingAlgRunnerTask::run sip_corepart1.cpp:91980
QgsTask::start qgstaskmanager.cpp:78
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.7-A Coru�a
QGIS code revision: 7b4ca4c8d0
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
@mrpaulday r.viewshed from the GRASS/Processing toolbox, or a tool from a 3rd party plugin?

**Comment by mrpaulday** [comment]
Sorry, it's the Visibility Analysis plugin from Zoran Čučković - I'll close this issue and resubmit to Zoran.
