### ISSUE TITLE
[Postgres] Cannot edit attribute when there is no primary key

### ISSUE THREAD

**Issue by troopa81** [qgis/QGIS#37917]
**Describe the bug**

It's impossible to edit attribute from a table which doesn't define a primary key. All widgets are disabled

**How to Reproduce**

1. Create table

```sql
create table test_double( id serial, myint integer, name character varying, geom geometry(Point,4326) ); 
```
*Note:* fails also if id is a simple *integer* and not a serial

2. Load layer in QGIS
3. Add a point
4. Widget are all disabled

![grayed](https://user-images.githubusercontent.com/14358135/88182176-29342080-cc30-11ea-9fa8-b1179f27289e.png)

If you click on OK and add the feature, the Save icon is also grayed.

**QGIS and OS versions**

QGIS master
Debian bullseye
Postgres 12

**Additional context**

Looks like the primary key is [mapped to ctid](https://github.com/qgis/QGIS/blob/master/src/providers/postgres/qgspostgresprovider.cpp#L1514)

**Comment by rouault** [comment]
It doesn't seem to be a bug to me. Having "id serial" is not sufficient to guarantee unicity
You can do the following for example:
```
insert into test_double values (1, null, null, null);
insert into test_double values (1, null, null, null);
```
which row should be updated ... ?

**Comment by rouault** [comment]
Closing. Re-open if I'm missing something

**Comment by troopa81** [comment]
> which row should be updated ... ?

True, I didn't think about updating, only inserting...
