### ISSUE TITLE
Crash using atlas-preview when labeling with buffer-drawing effects

### ISSUE THREAD

**Issue by koenigherford** [qgis/QGIS#37938]
**Descrption**
QGIS crashes on Atlas-preview when labeling a line-dataset with enabled drawing effects "source / outer glow" in labeling-buffer.

**How to Reproduce**
Small project with a a reduced (openstreetmap-)line dataset (only for labeling purpose). Layer-visibility enabled. 
Used repair-tool from processing to avoid issues caused by data.
Set a labeling buffer (size 0.3 mm) and following drawing effects 

![grafik](https://user-images.githubusercontent.com/28433436/88254506-ca18ef00-ccb5-11ea-8d1f-88f3a3bd2b36.png)

Source 
![grafik](https://user-images.githubusercontent.com/28433436/88254284-19125480-ccb5-11ea-8c2c-dbfa67e8b279.png)

and Outer glow
![grafik](https://user-images.githubusercontent.com/28433436/88254323-39daaa00-ccb5-11ea-9b07-b4fc0d2af890.png)

Have another dataset with processing-simplified and processing-repaired polygons as atlas-layer. Styling as default. Layer-visibility disabled. 

If "drawing effects" of buffer are disabled a atlas-preview runs without problems.

QGIS crashes on atlas-preview with enabled drawing-effects of buffer (depending on size of polgon and line-dataset) immediately or after a small amount of pages.

Sample project/dataset is attached

[qgis_test.zip](https://github.com/qgis/QGIS/files/4964003/qgis_test.zip)

**QGIS and OS versions**

Tested it on a fresh, new QGIS 14.1 version on my private laptop with a fresh windows-10 acer-laptop with described behaviour.
Tested it on another Windows 10 computer of a colleague with QGIS 12.x with described behaviour.
Tested it on my office-computer with QGIS 3.8.3. with described behaviour.

QGIS Info
QGIS Version: 3.8.3-Zanzibar
QGIS code revision: 685d8b15d2
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by Gustry** [comment]
> QGIS Version: 3.8.3-Zanzibar

This is too old. 3.8 is not maintained anymore. Try again with latest 3.14 3.10.

**Comment by koenigherford** [comment]
As described before: Same issue with a newest 3.14.1 version installed two days before (private laptop). Had login-data for github only in my office (3.8.3 there).

**Comment by Gustry** [comment]
I edited my message about the profile too

**Comment by koenigherford** [comment]
As there are different computers (the 3.14.1 with default-profile) there are different, independent profiles. What should be tested in detail ?

**Comment by Gustry** [comment]
> As there are different computers (the 3.14.1 with default-profile) there are different, independent profiles. 

Can you still try? Maybe you got the same issue in both profiles ?

**Comment by ralfkoenig** [comment]
I can confirm to be able reproduce the crash with 2 different profiles (_default | qgis-test-profile_) on a fresh installation of QGIS 3.14.1. when enabeling labeling-buffer-drawing-effects and starting an atlas-preview of the sample data above (project saved as 3.14.1.-project before).

Profile settings were not changed after creation.

**Log-Message from default-profile:**

Crash ID: 0ad442123510e180b50b0582bc1eb9817f311eda


Stack Trace


QPicture::boundingRect :
QPicture::boundingRect :
QgsPaintEffect::sourceAsImage qgspainteffect.cpp:186
QgsDrawSourceEffect::draw qgspainteffect.cpp:251
QgsEffectStack::draw qgseffectstack.cpp:115
QgsPaintEffect::end qgspainteffect.cpp:154
QgsTextRenderer::drawBuffer qgstextrenderer.cpp:337
QgsTextRenderer::drawTextInternal qgstextrenderer.cpp:1311
QgsVectorLayerLabelProvider::drawLabelPrivate qgsvectorlayerlabelprovider.cpp:639
QgsVectorLayerLabelProvider::drawLabelPrivate qgsvectorlayerlabelprovider.cpp:644
QgsVectorLayerLabelProvider::drawLabelPrivate qgsvectorlayerlabelprovider.cpp:644
QgsVectorLayerLabelProvider::drawLabel qgsvectorlayerlabelprovider.cpp:446
QgsLabelingEngine::drawLabels qgslabelingengine.cpp:473
QgsDefaultLabelingEngine::run qgslabelingengine.cpp:561
QgsMapRendererJob::drawLabeling qgsmaprendererjob.cpp:951
QgsMapRendererCustomPainterJob::doRender qgsmaprenderercustompainterjob.cpp:352
QgsMapRendererCustomPainterJob::staticRender qgsmaprenderercustompainterjob.cpp:264
QtConcurrent::RunFunctionTask::run qtconcurrentrunbase.h:136
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.14.1-Pi
QGIS code revision: de08d6b71d
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362
