### ISSUE TITLE
QGIS LTR3.14: Cannot find proj.db when running standalone in python3.7

### ISSUE THREAD

**Issue by earthcli** [qgis/QGIS#37931]
QGIS LTR3.14: Cannot find proj.db when running standalone in python3.7
I have installed QGIS LTR3.14 with OSGeo4w express desktop install. I can run the below code successfully in the QGIS GUI:
from qgis.core import *
from osgeo import gdal, ogr, osr

While I want to run Qgis modules standalone in python, but I get an error about the proj.db.
Error: proj_create_from_database: Cannot find proj.db

The python.exe used is located in C:\\OSGeo4W64\\apps\\Python37, I have set the environment as below according to the document from the forum,
I wonder whether this is related to the QGIS version 3.14? Also the infomation about the GDAL version showing "Compiled against GDAL/OGR 3.0.4 Running against GDAL/OGR3.0.3", 
Should I update the gdal or using the dev version of QGIS?
Additionly, I have also installed R and also the sf, rgdal, gdalultilities packages in my computer. 

```
import sys, os
#Must set other paths 
os.chdir('D:/') 
#Add QGIS to system path
sys.path = ['',
            'C:/OSGeo4W64/apps/qgis/bin',
            'C:/OSGeo4W64/apps/Python37', 
            'C:/OSGeo4W64/apps/Python37/Scripts', 
            'C:/OSGeo4W64/apps/Python37/DLLs', 
            'C:/OSGeo4W64/apps/Python37/lib', 
            'C:/OSGeo4W64/apps/Python37/lib/site-packages', 
            'C:/OSGeo4W64/apps/Python37/lib/site-packages/pywin32_system32',
            'C:/OSGeo4W64/apps/Python37/lib/site-packages/numpy/.libs',
            'C:/OSGeo4W64/apps/Python37/lib/site-packages/pyproj/proj_dir/share\proj',
            'C:/OSGeo4W64', 
            'C:/OSGeo4W64/bin',            
            'C:/OSGeo4W64/apps/qgis/qtplugins', 
            'C:/OSGeo4W64/apps/qgis/python', 
            'C:/OSGeo4W64/apps/qgis/python/plugins',  
            'C:/OSGeo4W64/apps/qgis-rel-dev',
            'C:/OSGeo4W64/apps/qgis-rel-dev/bin',
            'C:/OSGeo4W64/apps/qgis-rel-dev/qtplugins',
            'C:/OSGeo4W64/apps/gdal-dev/bin',
            'C:/OSGeo4W64/apps/share/gdal',
            'C:/OSGeo4W64/bin/gdalplugins',
            'C:/OSGeo4W64/apps/gdal-dev/bin/gdalplugins',
            'C:/OSGeo4W64/apps/Qt5',
            'C:/OSGeo4W64/apps/Qt5/bin',
            'C:/OSGeo4W64/apps/Qt5/lib',
            'C:/OSGeo4W64/apps/Qt5/include',
            'C:/OSGeo4W64/apps/Qt5/plugins',
            'C:/OSGeo4W64/apps/Qt5/translations',
            'C:/OSGeo4W64/apps/Qt5/plugins/platforms',
            'C:/Users/QIN/AppData/Roaming/QGIS/QGIS3/profiles/default/python',
            'C:/Users/QIN/AppData/Roaming/QGIS/QGIS3/profiles/default/python/plugins']

os.environ['PYTHONPATH'] = r'C:\OSGeo4W64\share\gdal'
os.environ['GDAL_DATA'] = r'C:\OSGeo4W64\share\gdal'
os.environ['GDAL_DRIVER_PATH'] = r'C:\OSGeo4W64\bin\gdalplugins'         
os.environ['PROJ_LIB'] = r'C:\OSGeo4W64\share\proj'
#os.environ['PROJ_LIB'] = r'C:\OSGeo4W64\apps\Python37\lib\site-packages\osgeo\data\proj'
#os.environ['PROJ_LIB']  = r'C:\OSGeo4W64\apps\Python37\lib\site-packages\pyproj\proj_dir\share\proj'
#os.environ['PROJ_LIB'] = os.path.dirname(sys.argv[0])


os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = r'C:\OSGeo4W64\apps\Qt5\plugins'
os.environ['PATH'] += r'C:\OSGeo4W64\apps\Qt5\bin'
QGISprefixpath=r'C:\OSGeo4W64\apps\qgis'


from qgis.core import *
from osgeo import gdal, ogr, osr
#import QGIS procesing algorithms
try:
    from qgis.core import *
    from qgis.analysis import QgsNativeAlgorithms
    from osgeo import gdal, ogr, osr
    # Set QGIS prefix
    QgsApplication.setPrefixPath(QGISprefixpath, True)
    qgs=QgsApplication([], False)
    qgs.initQgis()
    
    #Import QGIS and native algorithms
    import processing
    from processing.core.Processing import Processing
    Processing.initialize()
    QgsApplication.processingRegistry().addProvider(QgsNativeAlgorithms())

except:
    print("Qgis import unsuccessful")

else:
    print("Qgis import successful!")

```
QGIS version 3.14.1-Pi QGIS code revision de08d6b71d
Compiled against Qt 5.11.2 Running against Qt 5.11.2
Compiled against GDAL/OGR 3.0.4 Running against GDAL/OGR3.0.3
Compiled against GEOS3.8.1-CAPI-1.13.3 Running against GEOS3.8.1-CAPI-1.13.3

Compiled against PROJ6.3.2 Running against PROJRel. 6.3.2, May 1st, 2020
OS Version Windows 10 (10.0)
Active python plugins db_manager; MetaSearch; processing

**Comment by gioman** [comment]
@earthcli please ask in the developers mailing list if you are doing it right.

**Comment by uclaros** [comment]
Strings containing backslashes (`\`) should either have them replaced with forward slashes (`/`), escaped with another backslash (`\\`) or mark the string as raw by prefixing it with an r (`r'c:\'`).
Some of your path strings comply to the above, some do not.

**Comment by enzedrailmaps** [comment]
Small point: 3.14 is not the LTR at current. That is 3.10. If you really 
mean LTR install 3.10.8

**Comment by earthcli** [comment]
> Strings containing backslashes (`'c:\'`) should either have them replaced with forward slashes (`'c:/'`), escaped with another backslash (`'c:\\'`) or mark the string as raw by prefixing it with an r (`r'c:\'`).
> Some of your path strings comply to the above, some do not.

Sorry, this is not correctly wraped by the editor. All ths sys.path looks like "\\" initially in my code, however, the QGISprefixpath environment is wrongly wriiten, I have fixed it, but the error still exist. Thanks for your suggestion.

**Comment by earthcli** [comment]
> Small point: 3.14 is not the LTR at current. That is 3.10. If you really mean LTR install 3.10.8
> […](#)
> On 23/07/20 12:08 pm, earthcli wrote: QGIS LTR3.14: Cannot find proj.db when running standalone in python3.7 I have installed QGIS LTR3.14 with OSGeo4w express desktop install. I can run the below code successfully in the QGIS GUI: from qgis.core import * from osgeo import gdal, ogr, osr While I want to run Qgis modules standalone in python, but I get an error about the proj.db. Error: proj_create_from_database: Cannot find proj.db The python.exe used is located in C:\OSGeo4W64\apps\Python37, I have set the environment as below according to the document from the forum, I wonder whether this is related to the QGIS version 3.14? Also the infomation about the GDAL version showing "Compiled against GDAL/OGR 3.0.4 Running against GDAL/OGR3.0.3", Should I update the gdal or using the dev version of QGIS? <snip>

Thanks for remindering. 3.14 is good only if the proj.db problem is solved.
