### ISSUE TITLE
Standard Dialog Buttons Missing German Translations in 3.10.8

### ISSUE THREAD

**Issue by JPPauly** [qgis/QGIS#37939]
**Describe the bug**

Most standard dialog buttons are missing german translations: "Close", "Cancel", "Discard", "Help"

**How to Reproduce**

1. Go to 'Einstellungen' > 'Optionen'
2. Close and Help buttons are in english.

OR 

1. Create new project
2. Close QGIS
3. 'Projekt speichern' dialog has buttons in english.

**QGIS and OS versions**

QGIS 3.10.8 on Windows 7

**Additional context**

**Comment by rduivenvoorde** [comment]
For what I know the standard buttons labels are not part of QGIS translations, but of Qt-translations.
We have the same in Dutch.

I've tried to partner up with the dutch KDE community, which do a lot of Qt translation but the Qt-translating proces is so complex that I gave up. 

See: https://github.com/qgis/QGIS/issues/19919 for more information

**Comment by JPPauly** [comment]
Thats wierd, in version 3.10.0 and 3.10.1 we have standard buttons in german even though these versions were apparently compiled with the same Qt version (5.11.2) as 3.10.8.

**Comment by rduivenvoorde** [comment]
@JPPauly  THAT is weird indeed, are you 100% sure it is the same Qt version?

Can you install them next to each other?
Are we talking Windows or Linux here?
What kind of install do you use for QGIS?

**Comment by JPPauly** [comment]
Falls alarm. It was an installation error on my part...

Many thanks for the answers.
