### ISSUE TITLE
QGIS crashes when using the Mesh option in 3D MAP View

### ISSUE THREAD

**Issue by irinon** [qgis/QGIS#37942]
Hi there!

I've started using QGIS a few days ago, learning on the go. It's the first time that I use this forum, so please be patient and forgive me if I ask silly questions ;-) 

So I'm trying to learn how to create 3D terrain maps from terrain elevation models with the 3D map view, but QGIS always crashes when I try to render the mesh... not sure if it's my laptop fault ( Intel i7 - 1.80 to 1.99GHz / 8GB RAM / NVIDIA GeForce GTX 1650 with Max-Q Design) or if I'm doing something wrong...

Below the error code that I get:

```
QgsWindow3DEngine::window :
QgsWindow3DEngine::window :
QgsTerrainDownloader::tileImageToHeightMap :
QgsTerrainDownloader::tileImageToHeightMap :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.12.1-Bucure?ti
QGIS code revision: 121cc00ff0
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362
```

Thanks in advance for your help!

**Comment by gioman** [comment]
> QGIS Version: 3.12.1-Bucure?ti

@irinon too old, update to the latest 3.14 and try again.

**Comment by irinon** [comment]
Thanks @gioman ! It worked now!
