### ISSUE TITLE
Creating a custom projection identical to a native one results in different coordinates locations for them

### ISSUE THREAD

**Issue by EranGeo** [qgis/QGIS#37947]
**Bug Description**
When I create a custom projection using parameters from an existing CRS I get different locations for both original CRS and custom one entering the same coordinate. That is: though the NATIVE and the CUSTOM CRS should be exactly the same, they are not. 
**How to make the CUSTOM CRS to output the same as the NATIVE ONE?**

**How to Reproduce**
1. Settings
2. Custom Projections
3. Add new CRS button
4. Give a meaningful name. example: "exactly like 6991 but custom"
5. Copy parameters from existing CRS
6. Choose EPSG:6991
7. Change the format to 'Proj String' 
8. Change back to 'WKT'
9. Save
![NATIVE VS CUSTOM CRS](https://user-images.githubusercontent.com/47955227/88298972-7f759200-cd0a-11ea-85ea-64c05c9b7e2a.gif)
10. Open new project
11. Set its CRS to NATIVE CRS (6991)
12. Create a new point layer (or use the GPKG attached) with NATIVE 6991 coordinates.
13. Insert one point with certain coordinates [for example: x: 208420 y: 749180]

14. Create new point layer with "exactly like 6991 but custom" CRS.
15. Change project CRS to "exactly like 6991 but custom"
16. Insert a point with the **same** coordinates from section 13.
17. Compare the two layers output location - I got approx 155 m difference.
![image](https://user-images.githubusercontent.com/47955227/88297755-fc077100-cd08-11ea-9d5d-efd5bfcda100.png)

**QGIS and OS versions**
QGIS version | 3.10.8-A Coruña | QGIS code revision | d09a4f2388
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | AnotherDXF2Shape; changeDataSource; DataPlotly; DigitizingTools; lrs; mapswipetool_plugin; mmqgis; OSMDownloader; profiletool; qgis-open-data-master; qgis2web; qgiscloud; qgis_versioning; QuickMultiAttributeEdit3; QuickOSM; quick_map_services; shapetools; SRTM-Downloader; StreetView; VectorBender; vector_tiles_reader; WaterNetAnalyzer-master; xyToPoint; db_manager; MetaSearch; processing

**Additional notes**
The WKT of the two differ in several lines
![image](https://user-images.githubusercontent.com/47955227/88300038-b8623680-cd0b-11ea-90e4-73ab692c6a0e.png)
[6991 as custom CRS WKT.txt](https://github.com/qgis/QGIS/files/4966676/6991.as.custom.CRS.WKT.txt)
[6991 NATIVE CRS WKT.txt](https://github.com/qgis/QGIS/files/4966677/6991.NATIVE.CRS.WKT.txt)

**Attaching**
1. GPKG with sample data
[different_crs_layers.zip](https://github.com/qgis/QGIS/files/4966733/different_crs_layers.zip)

**Comment by nyalldawson** [comment]
Proj definitions of CRSes are a lossy format, so the round trip through a proj definition will result in a DIFFERENT crs definition. It's natural in this case that the results it gives are different.

The solution is to avoid using proj definitions and always use WKT definitions instead. That's why "WKT" has the "recommended" label in the custom projection dialog.
