### ISSUE TITLE
Rendering of labels in WMS requests does not respect the tile_buffer parameter when the request have the parameter TILED= TRUE and a tile buffer is set in the project propertie

### ISSUE THREAD

**Issue by karl-magnus** [qgis/QGIS#37945]
**Description**
The rendering of labels in WMS requests does not respect the tile_buffer parameter when the request have the parameter TILED= TRUE and a tile buffer is set in the project properties. This works for symbols, solved by @troopa81 and discussed here  #30071  . In this two adjacent images there is a clipped label up to the right in the lower. In the image directly north of this the part of the symbol for the point is rendered correctly even if it is outside the requested area but the label is not there. The symbols are the point features holding the label used just for illustrating the difference between symbols and labels.
![bild](https://user-images.githubusercontent.com/4749245/88277952-da46c380-cce1-11ea-8111-29ee54ec14d1.png)
![bild](https://user-images.githubusercontent.com/4749245/88277881-bc795e80-cce1-11ea-885c-a3769974d16c.png)

**How to Reproduce**

1. Download data and project.
[demo_data.zip](https://github.com/qgis/QGIS/files/4965753/demo_data.zip)
2. Deploy on QGIS Server adjusting paths in the project to fit your environment.
3. Request WMS images from the server. Replace host to your host.
[http://path_to_your_qgis_server?MAP=tiled_label.qgs&TILED=TRUE&LAYERS=label_test&TRANSPARENT=true&SRS=EPSG%3A3008&FORMAT=image%2Fpng%3B%20mode%3D8bit&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&BBOX=134186.78272,6211280.17408,147733.4784,6224826.86976&WIDTH=512&HEIGHT=512](http://path_to_your_qgis_server?MAP=tiled_label.qgs&TILED=TRUE&LAYERS=label_test&TRANSPARENT=true&SRS=EPSG%3A3008&FORMAT=image%2Fpng%3B%20mode%3D8bit&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&BBOX=134186.78272,6211280.17408,147733.4784,6224826.86976&WIDTH=512&HEIGHT=512)
[http://path_to_your_qgis_server?MAP=tiled_label.qgs&TILED=TRUE&LAYERS=label_test&TRANSPARENT=true&SRS=EPSG%3A3008&FORMAT=image%2Fpng%3B%20mode%3D8bit&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&BBOX=134186.78272,6224826.86976,147733.4784,6238373.56544&WIDTH=512&HEIGHT=512](http://path_to_your_qgis_server?MAP=tiled_label.qgs&TILED=TRUE&LAYERS=label_test&TRANSPARENT=true&SRS=EPSG%3A3008&FORMAT=image%2Fpng%3B%20mode%3D8bit&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&BBOX=134186.78272,6224826.86976,147733.4784,6238373.56544&WIDTH=512&HEIGHT=512)

**QGIS and OS versions**
Tested on QGIS 3.10 Desktop and Server.

**Comment by karl-magnus** [comment]
Forgot to follow up on this. Would it be possible to get an estimate on this bug/feature? @troopa81 perhaps? Seems it would be a necessary function in our setup.

**Comment by troopa81** [comment]
> Forgot to follow up on this. Would it be possible to get an estimate on this bug/feature? @troopa81 perhaps? Seems it would be a necessary function in our setup.

I need to give another look to the code, see if it's difficult or not. For an estimation, you can contact me here:  julien dot cabieces at oslandia dot com

**Comment by elpaso** [comment]
@troopa81 any followup on this?

**Comment by karl-magnus** [comment]
We have ordered the work. Estimated to be ready in the end of June.

**Comment by elpaso** [comment]
@karl-magnus thank you for the reply, that is good news. 

Next time it would be polite if you or whoever will do the job could drop a comment here to notify other users and developers that there is some ongoing work on the issue :wink:

**Comment by karl-magnus** [comment]
Yes, of course. Forgot that since we switched to e-mail conversation.

**Comment by troopa81** [comment]
@elpaso my bad, I should have put a little comment here

**Comment by elpaso** [comment]
> @elpaso my bad, I should have put a little comment here

@troopa81 no problem: nothing really happened :)
