### ISSUE TITLE
QGIS 3.14.1: vector and raster menu entries missing

### ISSUE THREAD

**Issue by rbonnefoi** [qgis/QGIS#37955]
Hi all,

I just updated my QGIS version from 3.14 to 3.14.1 and noticed all the entries of the menus "vector" and "raster" have left, except those ones (I use a French version):
![image](https://user-images.githubusercontent.com/12908619/88383426-c915b980-cdaa-11ea-88a9-72dacbe2d2ae.png)
![image](https://user-images.githubusercontent.com/12908619/88383332-979cee00-cdaa-11ea-89de-87ebf3260967.png)

I also can't copy/paste anymore any vector shape from one layer to another. Nothing in the log messages seems to say something is wrong.

Here is the detailed version informations:
![image](https://user-images.githubusercontent.com/12908619/88383143-39700b00-cdaa-11ea-86de-360ea9a340b9.png)

Have I missed anything during the update ? I done many QGIS upgrades but never experienced such a problem.

[edit] I just tried to downgrade to 3.14.0, and the entries are still missing, while they were here before upgrading.

Thanks for any help or advice.

Regards,

Remi.

**Comment by Gustry** [comment]
In your plugins, enable `Processing`, does it fix the issue?

**Comment by rbonnefoi** [comment]
Indeed, it solved the problem. No idea how it got unselected. Maybe it worthes a glance at the install process of 3.14.1 version, just to be sure it doesn't disable the plugin.
But maybe I did it by mistake.

Many thanks for the tip.
