### ISSUE TITLE
Postgis raster support: raster not properly rendered

### ISSUE THREAD

**Issue by jgrocha** [qgis/QGIS#37968]
**Describe the bug**

### The raster 

I have a one band only raster (generated with `gdal_grid`) that displays correctly in QGIS (available as attachment 
[dem_linear_cdn.zip](https://github.com/qgis/QGIS/files/4978725/dem_linear_cdn.zip)) when loaded from file.

```bash
gdal_grid -l validation.curva_de_nivel_points_interval -a_srs EPSG:3763 -a linear -ot Float32 -of GTiff -txe -48658 -38737 -tye 167016 171072 -outsize 2480 1014 "PG:host=localhost port=5433 user=geobox dbname=homologacao sslmode=disable" dem_linear_cdn.tif --config GDAL_NUM_THREADS ALL_CPUS
```

### raster2pgsql

When I upload the same raster to Postgis, it seems to be properly stored.

```bash
raster2pgsql -s 3763 -d -C -M dem_linear_cdn.tif validation.dem_linear_cdn | psql -h localhost -p 5433 -U geobox homologacao
```

### Check the rasters

I'm able to retrieve the same values from the same pixels, using:

```bash
$ gdallocationinfo -l_srs EPSG:3763 PG:"host=localhost port=5433 user=geobox dbname=homologacao schema=validation table=dem_linear_cdn" -42677.86, 168856.68
Report:
  Location: (1494P,460L)
  Band 1:
    <LocationInfo></LocationInfo>
    Value: 94.1874771118164

$ gdallocationinfo -l_srs EPSG:3763 dem_linear_cdn.tif -42677.86, 168856.68
Report:
  Location: (1494P,460L)
  Band 1:
    Value: 94.1874771118164
```

## The problem

The Postgis raster is not correctly displayed in QGIS (the raster on the left, on the following screen capture). When zooming in, the render disappears and does not show anything.

Using Value tool, we can notice that some pixel values are correctly retrieved, while there are many with zero value. Moving the mouse around, it changes between pixels with values and pixels with 0. At lower scales (1:70k), the values are always good. At higher scales (like 1:2k), there are values with zero.

![Screenshot from 2020-07-26 23-05-57](https://user-images.githubusercontent.com/163681/88490782-f1add700-cf95-11ea-8f70-ba97066a268b.png)

Using PyQGIS, the values seems to be correctly retrieved. I've tested for locations where the value tool return 0, but in PyQGIS, the returned value is correct.

```python
layer = iface.activeLayer()
val, res = layer.dataProvider().sample(QgsPointXY(-42677.86, 168856.68), 1)
print(val)

94.1874771118164
```

**How to Reproduce**

The dataset where is noticed this issue is attached

To reproduce the problem, you have to insert the raster into Postgis. Then use both raster (from the file system and from Postgis), side by side, on the same project. QGIS is not able to render the one from PostGIS.

**QGIS and OS versions**

Current master

**Additional context**

```sql
# select postgis_full_version();
                                                                                         postgis_full_version                                                                                         
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 POSTGIS="3.1.0dev 3e1ea07" [EXTENSION] PGSQL="120" GEOS="3.8.0-CAPI-1.13.1 " PROJ="7.0.0" GDAL="GDAL 3.2.0dev-1c7fef4227-dirty, released 2020/05/23" LIBXML="2.9.4" LIBJSON="0.13.1" TOPOLOGY RASTER
(1 row)
```

**Comment by jgrocha** [comment]
As an additional note, if the raster is tiled, the display improves, but there is some problem getting the tiles in correct order (the tiled raster on the left, on the following screen capture; the good one on the right)

```bash
raster2pgsql -t 200x200 -s 3763 -d -C -M -I dem_linear_cdn.tif validation.dem_linear_cdn | psql -h localhost -p 5433 -U geobox homologacao
```

![Screenshot from 2020-07-27 09-29-57](https://user-images.githubusercontent.com/163681/88520953-33696c80-cfec-11ea-8bf6-eae0db97e715.png)

**Comment by gioman** [comment]
> I have a one band only raster

@jgrocha so the described issue if for this specific dataset only, correct?

**Comment by jgrocha** [comment]
Wow! Bug fixed! Confirmed with current master.

Both rasters (from file and from Postgis) are displayed well. Thank you @elpaso 

![Screenshot from 2020-07-28 18-12-19](https://user-images.githubusercontent.com/163681/88698542-17ee8680-d0fe-11ea-9b05-665383bdbf44.png)
