### ISSUE TITLE
TIN interpolation create strange triangles - Error in the interpolation

### ISSUE THREAD

**Issue by cesarcorreo** [qgis/QGIS#37979]
**Describe the bug**
I'm performing a TIN interpolation following a road (12 km long and 60 m wide) with a regular layer of points in a grid of 10x10 m. 
The triangles created "look for" points or values very far.
The surface interpolated are 2x2m but also tried 0.5x0.5m 
The problem in localised in some areas (Red circles) and in others works fine (Blue circles)
I also did the interpolation in ArcGIS and it worked properly.
(Maybe limit the distance where a point look for another could solve the problem)
Last screenshot compares the results from ArcGIS (natural neighbor) in green and from QGIS (Red)

**How to Reproduce**
I'll share the point layer to the assign person (not a public file)

**QGIS and OS versions**

QGIS version
3.14.0-Pi
QGIS code revision
9f7028fd23
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
ale; 
AnotherDXF2Shape; 
autoSaver; 
ClosestPoint; 
contour; 
DataPlotly; 
dimensioning; 
dimensions_selector; 
EasyCustomLabeling; 
FeatureGridCreator; 
freehandEditing3; 
gdrive_provider; 
geoscience; 
GroupStats; 
HCMGIS; 
ImportPhotos; 
kmltools; 
KP_find; 
LAStools; 
latlontools; 
lines_around_point; 
LocatePoints; 
mapswipetool_plugin; 
MBTiles2img; 
Mergin; 
mmqgis; 
NNJoin; 
OSMDownloader; 
PluginLoadTimes; 
pointsamplingtool; 
polystrip; 
profiletool; 
qchainage; 
Qgis2threejs; 
qgis2web; 
qgiscloud; 
QGISSortAndNumber-master; 
qgis_resource_sharing; 
qProf; 
QuickOSM; 
quick_map_services; 
rasterstats; 
refFunctions; 
searchlayers; 
SelectWithin; 
SpreadsheetLayers; 
SRTM-Downloader; 
StreetView; 
SuperLabeling; 
TopoUSM-QGIS-master; 
valuetool; 
zoomtopaste; 
db_manager; 
MetaSearch; 
processing

**Additional context**

![Ph1](https://user-images.githubusercontent.com/25932761/88519956-374cbd00-cff3-11ea-8930-02ac04477ac1.PNG)
![Ph2](https://user-images.githubusercontent.com/25932761/88519964-3ae04400-cff3-11ea-9a03-ef8279028dd6.jpg)
![Ph3](https://user-images.githubusercontent.com/25932761/88519974-3ddb3480-cff3-11ea-8d79-2fde9d767d28.jpg)
![Ph4](https://user-images.githubusercontent.com/25932761/88519978-3fa4f800-cff3-11ea-83be-9150b8177ff2.jpg)
![Ph5](https://user-images.githubusercontent.com/25932761/88519984-416ebb80-cff3-11ea-9a6a-ca5365e3da85.jpg)
![Ph6](https://user-images.githubusercontent.com/25932761/88520677-2f414d00-cff4-11ea-9496-859cbe78dd24.PNG)

**Comment by gioman** [comment]
@cesarcorreo can you please attach the dataset?

**Comment by cesarcorreo** [comment]
I sent you the file (not to be shared)

**Comment by gioman** [comment]
I connfirm the issue on QGIS master too.

**Comment by vcloarec** [comment]
@cesarcorreo , I am on fixing issues in the TIN interpolation. Can you share you data, so I can test with it?

**Comment by cesarcorreo** [comment]
> @cesarcorreo , I am on fixing issues with TIN interpolation. Can you share your data, so I can test with it?

Thanks Vincent.
Would you mind yo give me a mail to send you the file? (3 mb aprox)
I shouldn't share it.
Best

**Comment by vcloarec** [comment]
@cesarcorreo : vcloarec@gmail.com

**Comment by cesarcorreo** [comment]
Sent.
