### ISSUE TITLE
QGIS crashes when trying to add tables (excel or csv) to active layers

### ISSUE THREAD

**Issue by marcboschmatas** [qgis/QGIS#37982]
Crash ID: 3aa4cc64bc451c8e1e5adfdff8b64c608b3c7885

Stack Trace

QBitArray::QBitArray :
QgsAggregateCalculator::filter :
QgsRuleBasedRenderer::convertFromRenderer :
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QMetaObject::activate :
QgisInterface::currentLayerChanged :
QMetaObject::activate :
QgisApp::activeLayerChanged :
QgisApp::onActiveLayerChanged :
QgisApp::handleDropUriList :
QgsPluginRegistry::operator= :
QgisApp::identify :
QMetaObject::activate :
QTimer::timerEvent :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32Private::sendTimerEvent :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.12.2-Bucure?ti
QGIS code revision: 8a1fb33634
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment]
>  QGIS Version: 3.12.2-Bucure?ti

@marcboschmatas too old, please update to the latest 3.14. Also try with a new QGIS profile. If the problem persist please attach sample data and the **detailed** steps to follow that are lading to the crash.

**Comment by marcboschmatas** [comment]
@gioman I have updated QGIS to 3.14 and I keep getting the same error. The process simply looking for an excel file with the data I need to join to a shapefile in the explorer and dragging it down to the active layer list. Then, it freezes for a long time and finally crashes. This is the data I'm trying to load but I keep getting the same error with any other file except for shp/gpkg/geojson and so on.
[renta media limpio.xlsx](https://github.com/qgis/QGIS/files/4981678/renta.media.limpio.xlsx)




Crash ID: 72bcc46d08ae29ec58898dfa90c65eb4913b7574


Stack Trace


QBitArray::QBitArray :
QgsMeshDriverMetadata::description qgsprovidermetadata.cpp:311
QgsRuleBasedRenderer::convertFromRenderer qgsrulebasedrenderer.cpp:1304
meth_QgsRuleBasedRenderer_convertFromRenderer sip_corepart1.cpp:78473
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QMetaObject::activate :
QgisInterface::currentLayerChanged moc_qgisinterface.cpp:761
QMetaObject::activate :
QgisApp::activeLayerChanged moc_qgisapp.cpp:2741
QgisApp::onActiveLayerChanged qgisapp.cpp:694
QgisApp::handleDropUriList qgisapp.cpp:2083
::operator() qgisapp.cpp:1952
QtPrivate::QFunctorSlotObject,0,QtPrivate::List,void>::impl qobjectdefs_impl.h:422
QMetaObject::activate :
QTimer::timerEvent :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:439
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32Private::sendTimerEvent :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1618
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.14.1-Pi
QGIS code revision: de08d6b71d
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment]
@marcboschmatas I can't replicate on a clean projetc on Win 10 with QGIS 3.14.1

**Comment by marcboschmatas** [comment]
Creating a new profile solved it, thank you so much.
