### ISSUE TITLE
I get an error when I open Google Earth Pro C:\Users\wehr7\AppData\Local\Temp\Google_Earth_Pro_7.3.3.7699_64-bit_200727-114100_1.dmp

### ISSUE THREAD

**Issue by VivaRahman1995** [qgis/QGIS#37986]
IMPORTANT:

If the issue concerns a third party plugin (downloaded with the plugin manager) then it can't be fixed by the QGIS team.
Please raise your issue in the dedicated bug tracker for that specific plugin (as listed in the plugin's description)

Tickets created here will be closed.

**Comment by gioman** [comment]
@VivaRahman1995 this is not Google Earth pro bug tracker. Cheers!

**Comment by VivaRahman1995** [comment]
Whenever i try to open Google Earth Pro,it shows me an error message and a
diagnostic message,when ever i click windows + R,it opens QGIS and it shows
me two error messages,i need a solution to this
