### ISSUE TITLE
Label buffer

### ISSUE THREAD

**Issue by chanteclair12** [qgis/QGIS#37985]
Hello everybody,
I encounter a bug on the version of Qgis 3.x (3.4.5, 3.10 and 3.14.0)

1st bug: the label buffers are not kept when reopening a project. The option is always checked but the size is zero and must be redefined each time.

Have you observed these dysfunctions as well? Did I miss a step in using these features?
Thanks, have a good day.

**Comment by gioman** [comment]
@chanteclair12 please file separate tickets for each issue you find. Please test if using a new QGIS profile anything changes: settings > user profiles > new profile.

**Comment by chanteclair12** [comment]
@gioman sorry for the 2 purposes in the same ticket. I separated them and renamed this one.
It is the same with a new profile. It is also the same on others computers with same versions.

**Comment by gioman** [comment]
@chanteclair12 what operating system are you using?
