### ISSUE TITLE
Generate XYZ Tiles has missing data across the 180th meridian.

### ISSUE THREAD

**Issue by Jeremy-Doneghue** [qgis/QGIS#37995]
**Describe the bug**

Generate XYZ Tiles (Directory) fails to render properly across the 180th meridian. I'm trying to create a map of Fiji which happens to intersect this line. The algorithm fails to capture data right on either side of the meridian as can be seen in this screenshot of my tiles in Openlayers.

<img width="583" alt="Screen Shot 2020-07-28 at 3 55 24 PM" src="https://user-images.githubusercontent.com/8892185/88617473-e15b4080-d0ea-11ea-9d05-e03b7049f78e.png">

**How to Reproduce**

Try to save XYZ tiles with an extent that crosses the 180th meridian.

**QGIS and OS versions**

QGIS version | 3.14.1-Pi | QGIS code revision | de08d6b71d
-- | -- | -- | --
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.28.0 | Running against SQLite | 3.28.0
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS Mojave (10.14)
Active python plugins | processing; db_manager; MetaSearch

**Additional context**

My guess is that there is some kind of number precision problem of data to the east of 179.9999 and west of -179.9999.

**Comment by gioman** [comment]
@Jeremy-Doneghue did a quick test and seems ok to me now.
