### ISSUE TITLE
Crash when opening existing project

### ISSUE THREAD

**Issue by regann1** [qgis/QGIS#37993]
## User Feedback

I had an existing project open, and I opened up a different project from inside of QGIS. QGIS crashed - so am submitting bug report. 

## Report Details

**Crash ID**: [149516e960bed515e1b86853bee2dff97267efcd](https://github.com/qgis/QGIS/search?q=149516e960bed515e1b86853bee2dff97267efcd&type=Issues)

**Stack Trace**
<pre>
QBitArray::QBitArray :
QgsCoordinateReferenceSystem::QgsCoordinateReferenceSystem :
QgsAnnotation::mapPositionCrs :
QgsMapCanvasAnnotationItem::updatePosition :
QgsMapCanvas::updateCanvasItemPositions :
QMetaObject::activate :
QgsMapCanvas::setExtent :
QgsMapCanvas::setDestinationCrs :
QgsMapCanvas::readProject :
QMetaObject::activate :
QgsProject::readProject :
QgsProject::readProjectFile :
QgsProject::unzip :
QgsProject::read :
QgsProject::read :
QgisApp::addProject :
QgisApp::fileOpen :
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.12.2-Bucure?ti
QGIS code revision: 8a1fb33634
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

QGIS version | 3.12.2-București | QGIS code revision | 8a1fb33634
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Windows 10 (10.0)
Active python plugins | DigitizingTools; qdraw; db_manager; MetaSearch; processing

**Comment by gioman** [comment]
> 3.12.2-București

@regann1 too old, you must try with the latest QGIS 3.14.

**Comment by gioman** [comment]
Closing for lack of feedback.
