### ISSUE TITLE
Crash when zooming out and reprojecting WMTS raster layers. 

### ISSUE THREAD

**Issue by palmerj** [qgis/QGIS#37997]
**Describe the bug**

When zooming out the mapcanvas and reprojecting a raster that falls outside the mapcavnas projection method range qgis will coredump. 

**How to Reproduce**

1. Create WMTS connections with https://basemaps.linz.govt.nz/v1/tiles/WMTSCapabilities.xml?api=c01ebz4bjx2z03a1ea64jkfkpqp
2. Create a new project
3. Add first layer 'aerial Auckland rural 2010-2012 0.50m RGBA' from WMTS connection to map with EPSG:2193 projection
4. Add second layer  'aerial Gebco 2020 305-75m' from WMTS connection to map with EPSG:3857 projection.
5. Zoom out to a global extent using wheel mouse
6. Crash. See coredump here: https://gist.github.com/palmerj/bbf68e684823c97978d888d26735c894

Doesn't seem to occur every time. I but if I repeat the process within the same application session by creating a new project and starting again I can get a crash.

**QGIS and OS versions**

QGIS version | 3.14.0-Pi | QGIS code revision | 9f7028fd23
-- | -- | -- | --
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.28.0 | Running against SQLite | 3.28.0
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS 10.15
Active python plugins | IPyConsole; QuickWKT; qgis-maptiler-plugin; processing; db_manager; MetaSearch

**Additional context**

So far only tested on MacOSX

**Comment by gioman** [comment]
@palmerj tested on a clean macOS Catalina machine, with the installer for QGIS 3.14.1, no crash

![IMG_20200728_161020_9](https://user-images.githubusercontent.com/1951107/88684706-0a7cd080-d0ed-11ea-87c6-6a457c09eace.jpg)

**Comment by gioman** [comment]
Closing for lack of further feedback.
