### ISSUE TITLE
Raster visualisation: Paletted/unique view - no decimal numbers possible

### ISSUE THREAD

**Issue by decnet100** [qgis/QGIS#38000]
Hello dear Qgis-Team, 
would like to report a non-critical bug/limitation/inconvenience that I encountered with the paletted view/display for raster layers. 

The problem: I received a geotiff raster layer that contains percentages, meaning decimal numbers between 0 and 1, with all values falling under distinct classes; these values have a non-linear relation to the properties I want to display: Very low and very high values don't interest me, except for one pretty high value class; otherwise, everything useful is in the middle of the range - hence the idea to assign a paletted view. It was impossible to:
a) receive a correct automatic classification - seems like the paletted view expects integer numbers only.
b) enter decimal values as class definitions - the entry of decimal separator(s) simply didn't work.

The circumstances and attempted fixes:
I used 3.10 and latest 3.14 under Windows. I tried setting the locales and decimal separators to English-USA both systemwide and/or for QGIS override, as it seems to allows the entry of commas for some reason, while entirely blocking periods, and I believed that might have something to do with the locale setting. To no avail.

Existing Workarounds:
Obviously, one can use a raster calculation of RasterValue  * 1000  to turn these into integers, or use the pseudocolor display to assign custom colors for value ranges, but I think it's a rather confusing inconvenience as it stands, especially with the weird blockage of periods while commas are possible to enter (but ignored). 

Maybe this will be simple to fix, by allowing an existing type of decimal inputs there?

Best regards and thanks for everything you do!

Christian Demmler, Innsbruck

**Comment by gioman** [comment]
@decnet100 

1)
the decimal separator issue seems likley to be the same as https://github.com/qgis/QGIS/issues/33859 and https://github.com/qgis/QGIS/issues/34426 which was fixed in https://github.com/qgis/QGIS/commit/15a4c3928c26a77509629047edbee14140b39784 not sure if it has been backported. You should test QGIS master and report back.

2) have you tried the "round raster" tool in the Processing toolbox?

3) you are right, raster symbology, especially float ones is a pain. For this I have been in discussion recently with a core developer to understand how we can improve the situation and at what cost. Will probably launch a crowdfunding after the summer holidays.

Said all the above I think that this should be closed. Agree?

**Comment by decnet100** [comment]
I think it could be the same issue, but not quite certain - I think the min/max (which I also encountered previously, but could in fact solve by switching locales) is a bit of a different problem, the paletted/unique symbology was a lot more stubborn and I tend to think its entire classification form just can't deal with floats at all in its current form..? 
I absolutely agree on the raster symbology situation, it might be one of the most benefitial things for QGIS to have better/more streamlined options for rasters; after all, in my own work 90% of all projects use some sort of data raster, and making them look nice takes up a big amount of work in QGIS.

**Comment by gioman** [comment]
> I think it could be the same issue, but not quite certain - I think the min/max decimal point issue (which I also encountered previously, but could in fact solve by switching locales

@decnet100 please try on QGIS master.

**Comment by gioman** [comment]
> I absolutely agree on the raster symbology situation, it might be one of the most benefitial things for QGIS to have better/more streamlined options for rasters; after all, in my own work 90% of all projects use some sort of non-RGB-data raster, and making them look nice takes up a big amount of my time in QGIS.

@decnet100 we will try to improve in the next future.

**Comment by elpaso** [comment]
I think this is fixed, can you please try with 3.18?
