### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by chanteclair12** [qgis/QGIS#38009]
Hello everybody,
I encounter a bug on the version of Qgis 3.x (3.4.5, 3.10 and 3.14.0).

I create a theme in my Qgis project with several layers. 
Then I create a composer: in the properties of the map, Layers tab, I check "Follow the theme of the map" and choose the appropriate theme. Automatically, the buffers in my label layer are reset ! 
I have tried to re-register the theme under another name, recreate it ... still the same behavior.

Have you observed these dysfunctions as well? Did I miss a step in using these features?

**Comment by gioman** [comment]
@chanteclair12 what operating system? can you please attach a sample project (with data) that shows the issue you describe?

**Comment by chanteclair12** [comment]
@gioman my OS is Windows 10 Professionnal.
Here is a link to a sample project with open datas (https://we.tl/t-GsuCTsz14Y).
There is 2 layers (REG and COM). Both have buffers on labels. When you will open the project, buffer label of layer COM should be to 0 (while i put it on 0.8). 
I also made 2 themes and a composer : if you try to follow the theme TEST2, it should also resize buffer label of the Layer COM to 0 (to see it, you need to refresh the composeur and the map too).

**Comment by gioman** [comment]
> Here is a link to a sample project with open datas (https://we.tl/t-GsuCTsz14Y).

@chanteclair12 just tested your project and can't replicate any of the issue you describe.

**Comment by chanteclair12** [comment]
I just changed my computer and had the same behavior on the old one. 
I do not understand this problem...
Sorry for the trouble. Thanks for your help.
