### ISSUE TITLE
Can't save styles in postgresql containing font markers

### ISSUE THREAD

**Issue by GISsymbology** [qgis/QGIS#38008]
**Description**
Can't save the .qml styles in postgresql when they contain font marker

**How to Reproduce**
1. Load test project 
2. Import data in postgis 
3. load the new postgis layer
4. copy the gpkg layer style and paste into the postigis layer
5. try to save the style in postgresql using layer - > properties -> style -> save style -> save in database (postgis)
6. See error  QGIS:
Save style to DB (postgres) : Unable to save layer style. It's not possible to insert a new record into the style table. Maybe this is due to table permissions (user=). Please contact your database administrator. 
7. See error in postgresql log -->

2020-07-28 15:15:56 CEST DETTAGLI:  line 604: invalid character in attribute value
               <prop k="chr" v="^^"/>
                                ^
        line 604: attributes construct error
               <prop k="chr" v="^^"/>
                                ^
        line 604: Couldn't find end of Start Tag prop line 604
               <prop k="chr" v="^^"/>
                                ^
        line 604: PCDATA invalid Char value 30
               <prop k="chr" v="^^"/>
       [...]

**QGIS 3.14.1 OS Linux Mint 20
QGIS version | 3.14.1-Pi | QGIS code branch | Release 3.14
-- | -- | -- | --
Compiled against Qt | 5.12.8 | Running against Qt | 5.12.8
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.3 (Ubuntu 12.3-1.pgdg20.04+1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Linux Mint 20
Active python plugins | qconsolidate3; qfieldsync; lizmap; quick_map_services; db_manager; processing

[test_qml.gpkg.zip](https://github.com/qgis/QGIS/files/4988576/test_qml.gpkg.zip)

**Comment by elpaso** [comment]
Fixed in #38034
