### ISSUE TITLE
I having a problem with QGIS Madeira

### ISSUE THREAD

**Issue by VivaRahman1995** [qgis/QGIS#38012]
IMPORTANT:

If the issue concerns a third party plugin (downloaded with the plugin manager) then it can't be fixed by the QGIS team.
Please raise your issue in the dedicated bug tracker for that specific plugin (as listed in the plugin's description)

Tickets created here will be closed.
I having a problem with QGIS Madeira,when i open it,it said,"the plugin will be disabled because it crashed QGIS during last startup Please report an issue and re-enable the plugin when the problem has been solved"and it this is affecting my google earth pro app on windows 10

**Comment by gioman** [comment]
> Tickets created here will be closed.

@VivaRahman1995 tickets created here will be closed...




> I having a problem with QGIS Madeira,when i open it,it said,"the plugin will be disabled because it crashed QGIS during last startup Please report an issue and re-enable the plugin when the problem has been solved"and it this is affecting my google earth pro app on windows 10

please try with a new QGIS profile: settings > users profiles > new profile

also QGIS Madeira is EOL (end of life), upgrade to 3.10 or 3.14.

**Comment by VivaRahman1995** [comment]
the problem is persisting Gioman
