### ISSUE TITLE
"Show selected features" is very slow in recent versions

### ISSUE THREAD

**Issue by anitagraser** [qgis/QGIS#38018]
There seems to be a performance regression concerning "Show selected features" in the attribute table of recent QGIS versions. (See also https://twitter.com/DrChrisGeoSci/status/1288120808951312389)

I've tested this with the Natural Earth dataset ne_10m_populated_places layer. The expression "NAME" like 'A%' is close to instantaneous but switching to "Show selected features" takes forever and freezes QGIS master and 3.14 in a way that looks like it crashed (i.e. "not responding" on Windows). 

In 3.4 "Show selected features" is much faster. There's no freeze.

**Comment by gioman** [comment]
@anitagraser I was also about to report this. I wonder if/when would be a good moment to start speaking seriously what to do with the attribute table: its performance/UX is really under par compared to other GIS packages, regressions are frequent and we really don't want to bring all this problems in QGIS 4.

**Comment by haubourg** [comment]
+1 I also noticed this serious regression recently on a customer's project.

**Comment by andremano** [comment]
I did the same test you did (NE data) on 3.12 and did not notice that problem. Maybe it was introduced as of 3.14?

**Comment by nyalldawson** [comment]
My money is on https://github.com/qgis/QGIS/pull/36188 being the culprit.

**Comment by uclaros** [comment]
Shift+F6 works fast. Switching from *Show visible on map* to *Show selected features* is fast, so is switching between other modes.
It's only switching from *Show all features* to *Show selected features* and the opposite that is slow.

**Comment by gioman** [comment]
> My money is on #36188 being the culprit.

@signedav gentle ping.

**Comment by signedav** [comment]
Thanks for pinging @gioman I'll take a look.

**Comment by drcrescencio** [comment]
I got same problem with qgis 3.14.0. Slowdown to show 8 attributes of 17.000 lines dataset.

**Comment by soli004** [comment]
Same problem here using QGIS 3.14.1 and macOS 10.16.6, open up a polygon layer with + 10 000 polygons and a joined txt file.
As soon as I want to open the attribute table I get the beachball spinning and it never ends so have to kill the process. Another file with + 500 polygons opens with no problem even when selecting...

**Comment by signedav** [comment]
I could reproduce it too with @anitagraser s dataset. It can happen on selecting "Show All Features" after "Show selected Features" as well, right? 
Still I couldn't find the problem yet. It's taking long time to execute this call https://github.com/qgis/QGIS/blob/master/src/gui/attributetable/qgsattributetablefiltermodel.cpp#L335 but this cannot be the issue.

**Comment by riccardoklinger** [comment]
same here with Geofabirk dataset (roads, both shapefile as well as part of a geopackage) the "Show selected features" in the attribute table is giving me a spinner "not responding": 
I was checking this on 3.10.8 ... This is somehow awkward, because this should have never happened to a new LTR...
![grafik](https://user-images.githubusercontent.com/7377897/89100507-c3962000-d3f7-11ea-8d4b-bedbe85a82a7.png)

**Comment by gioman** [comment]
@signedav thanks! right know I can't compile, could you check if the revert solves also this? https://github.com/qgis/QGIS/issues/38068

**Comment by ismailsunni** [comment]
Hi, @gioman or @signedavis, has this fix merged to QGIS 3.10.x release? If so, which one? 3.10.10? 
Thanks!

**Comment by signedav** [comment]
Backported here #38170 
It reverted the commit leading to this issue here. And reintroduced the minor bug that the counter of features is not always updated.

**Comment by ismailsunni** [comment]
Thanks, @signedav!

**Comment by weca-theo** [comment]
> @anitagraser I was also about to report this. I wonder if/when would be a good moment to start speaking seriously what to do with the attribute table: its performance/UX is really under par compared to other GIS packages, regressions are frequent and we really don't want to bring all this problems in QGIS 4.

re: Attribute table - there needs to be an option to limit Attribute table to show, say, 100 items. This would be another option alongside 'Show selected features', 'Show visible features', 'Show all features'. Sometimes a user will just want to see a sample of a large dataset's attribute table, but still wants to see all features rendered on the map. Also having this option saved at project level  (ie. project properties) instead of QGIS/user profile level, would be useful.
