### ISSUE TITLE
Field calculator should not show the "date & time" datatype for shapefiles

### ISSUE THREAD

**Issue by PedroVenancio** [qgis/QGIS#38011]
**How to Reproduce**

1. Download for instance: https://firms.modaps.eosdis.nasa.gov/data/active_fire/c6/shapes/zips/MODIS_C6_Europe_24h.zip
2. Unzip and load in QGIS
3. This shapefile has an ACQ_DATE (Date) and an ACQ_TIME (String) fields.
4. To convert them to a single Datetime field, in Field Calculator:
Output field name: ACQ_DTTM
Output field type: Date & Time
Expression: to_datetime("ACQ_DATE" || ' ' || left("ACQ_TIME",2) || ':' || right("ACQ_TIME",2))

Preview is correct:
![imagem](https://user-images.githubusercontent.com/1331581/88688830-a90b3080-d0f1-11ea-87d2-9eb2db2c4ac3.png)

New field in Attribute Table also correct:
![imagem](https://user-images.githubusercontent.com/1331581/88691680-14a2cd00-d0f5-11ea-95db-a8eceb1c5198.png)

And also in Fields Properties:
![imagem](https://user-images.githubusercontent.com/1331581/88692097-95fa5f80-d0f5-11ea-9681-af6050e55691.png)

4. However, when I Save Edits, it changes the new field type to Date, loosing time information:
![imagem](https://user-images.githubusercontent.com/1331581/88691878-4fa50080-d0f5-11ea-8bc3-d172ef6f18de.png)

![imagem](https://user-images.githubusercontent.com/1331581/88692740-54b67f80-d0f6-11ea-9ff4-885fc70a83fc.png)

5. If I export the Shapefile to GeoPackage and add the new field after it, everything works fine. So, this seems to only affect Shapefiles.

**QGIS and OS versions**

Tested on QGIS 3.14.1 and QGIS 3.10.8, both on Windows 10.

**Comment by gioman** [comment]
@PedroVenancio there is no time support in SHP

https://en.wikipedia.org/wiki/Shapefile#Data_storage

anyway QGIS should not show "date/time" in the FC for such format.

**Comment by PedroVenancio** [comment]
Yes, sorry for the noise @gioman .

Do you think you can edit ticket subject to point to the real issue, that is the **Date & Time** format available in Field Calculator of shapefile data sources?

**Comment by gioman** [comment]
Done.

**Comment by DelazJ** [comment]
@gioman is it not: "Field calculator should **NOT** show the "date & time" datatype for shapefiles"?

**Comment by gioman** [comment]
> @gioman is it not: "Field calculator should **NOT** show the "date & time" datatype for shapefiles"?

@DelazJ thanks for spotting the typo.

**Comment by dminor** [comment]
It looks like this is coming straight from [GDAL](https://github.com/OSGeo/gdal/blob/380d11c6036d6c0456412d758e57abcabee569cf/gdal/ogr/ogrsf_frmts/shape/ogrshapedriver.cpp#L387). I'm going to try opening a pull request to fix this there. We might also want a workaround in QGIS in the mean time.
