### ISSUE TITLE
Data-defined fill color not working with classified symbology

### ISSUE THREAD

**Issue by KoZwo** [qgis/QGIS#38014]
When you use a data-defined fill color (HEX or RGB values in a field to determine polygone fill color) the polygone in your map are displayed with the right color BUT in the legend every element is classified with random colors. 

Exemple : 
In MAP : Polygone X is Blue on the canevas using color data contained in a field.

In legend : Polygone X is random color based on the classification.

This problem is very annoying and makes things sooo much more complicated when dealing with thousands of entities.

(Pardon my english)

Tested on :

QGIS 3.10.6 and QGIS 3.14.1
Windows 10

Screenshots:

**See how the colors in the legend do not match  the ones in the canevas**

![Capture](https://user-images.githubusercontent.com/67976177/88705671-db129780-d0dd-11ea-8737-d1dd3c99f343.PNG)

**Where to specify data-defined color using a field with RGB or HEX  color codes**

![InkedCouleur1_LI](https://user-images.githubusercontent.com/67976177/88706553-00ec6c00-d0df-11ea-8995-28d8b48f3593.jpg)

To replicate : 

1. Create a layer with random polygones
2. Create a field and add HEX or RGB color codes for each polygones
3. Create a classified symbology
4. Use the Hex or RGB field for the fill colors (Like shown in my second screenshot)
5. Open a map-layout and add a legend (or just look at the legend in the symbology window of the layer)

You will see that the color shown in the legend do not correspond to the one show in the canevas

**Comment by gioman** [comment]
@KoZwo 

qgis version?

operating system?

detailed steps to replicate (if it helps attach also screenshots/screencast)?

**Comment by KoZwo** [comment]
> 
> 
> @KoZwo
> 
> qgis version?
> 
> operating system?
> 
> detailed steps to replicate (if it helps attach also screenshots/screencast)?

**Comment by gioman** [comment]
@KoZwo I can't replicate, please attach a sample project+data.

**Comment by KoZwo** [comment]
> 
> 
> @KoZwo I can't replicate, please attach a sample project+data.

Sorry for late response, there you go!
[GitHub_Symbology.zip](https://github.com/qgis/QGIS/files/5022455/GitHub_Symbology.zip)

**Comment by gioman** [comment]
@KoZwo I see. Is something it surfaces recurrently and that I tend to forget.

This is anyway a long standing issue (or better... a feature request), see for a long discussion:

https://issues.qgis.org/issues/11491
https://github.com/qgis/QGIS/issues/19761

closing as duplicate.
