### ISSUE TITLE
QGIS crashed on saving changes to layer (.shp file)

### ISSUE THREAD

**Issue by PhiliusMaximus** [qgis/QGIS#38027]
## User Feedback

I was just saving a polygon layer - a shapefile - and QGIS crashed.

## Report Details

**Crash ID**: [0c4a6e3abb55312e07cd3fbc4ce83a809da0bf9c](https://github.com/qgis/QGIS/search?q=0c4a6e3abb55312e07cd3fbc4ce83a809da0bf9c&type=Issues)

**Stack Trace**
<pre>
memcpy memcpy.asm:444
VSICreateCachedFile :
SASetupDefaultHooks :
SHPReadObject :
SHPPartTypeName :
SHPPartTypeName :
QgsOgrFeatureIterator::fetchFeature qgsogrfeatureiterator.cpp:369
QgsAbstractFeatureIterator::nextFeature qgsfeatureiterator.cpp:63
QgsVectorLayerFeatureIterator::fetchFeature qgsvectorlayerfeatureiterator.cpp:416
QgsAbstractFeatureIterator::nextFeature qgsfeatureiterator.cpp:63
QgsVectorLayerRenderer::drawRenderer qgsvectorlayerrenderer.cpp:306
QgsVectorLayerRenderer::render qgsvectorlayerrenderer.cpp:284
QgsMapRendererCustomPainterJob::doRender qgsmaprenderercustompainterjob.cpp:312
QgsMapRendererCustomPainterJob::staticRender qgsmaprenderercustompainterjob.cpp:261
QtConcurrent::RunFunctionTask<void>::run qtconcurrentrunbase.h:136
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.8-A Coru�a
QGIS code revision: d09a4f2388
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
@PhiliusMaximus please try with a new QGIS profile, no 3rd party plugins installed.

**Comment by gioman** [comment]
Closing for lack of feedback.
