### ISSUE TITLE
Qgis NOTIFY layer - POSTGIS

### ISSUE THREAD

**Issue by wincent3** [qgis/QGIS#38029]
Hello, 
I found problem and no solutions on web. 

Using QGIS 3.14 + Postgis. I use postgresql funcions with triggers as notyfi on the layer. 
On all poligons layer working fine. Problem is the same sql not working on POINT layers. 
Get error msg layer don`t see filds. 

Like: I make layer TEST with filds  ID, Fild1 (text)

```
In trigger:
CREATE TRIGGER TEST_trigger
AFTER INSERT OR UPDATE OR DELETE 
ON public."TEST"
FOR EACH ROW
EXECUTE PROCEDURE public.TEST_function();
```
Funcion:
```
CREATE OR REPLACE FUNCTION public.TEST_function()
RETURNS trigger AS
$BODY$ 
DECLARE
BEGIN
CASE TG_OP
	WHEN 'INSERT' THEN
		NEW.Fild1 = (
			'try to do something'
		);
		UPDATE public."TEST" SET "Fild1" = NEW.Fild1 WHERE pbulic."TEST"."id"=NEW.id ;
	
	RETURN NULL;
	WHEN 'UPDATE' THEN
		RETURN NULL;
	WHEN 'DELETE' THEN
	        RETURN NULL;
END CASE;
END;
$BODY$
  LANGUAGE plpgsql 
```

-->

**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by gioman** [comment]
@wincent3 is this a bug report or a support request?

**Comment by wincent3** [comment]
@gioman Hi, i`m not sure where is exacly problem.
Is it in qgis or postgis... i`m not a profesional coder. But if you can help i will be happy

**Comment by gioman** [comment]
@wincent3 the issue (admitting is an issue in QGIS) is not well described, seems more a problem about how you wrote your postgresql function. Please ask for support in the right channels, the QGIS users/mailing lists, gis.stackexchange, etc.

If it turns out is a QGIS issue then please reopen this ticket.

**Comment by wincent3** [comment]
SQL script is no problem this same funcion working when LAYER in QGIS is set as POLYGON.

**Comment by gioman** [comment]
@wincent3 then please describe better what are your layers (add SQL definitions to allow recreate the tables), what your workflow in QGIS and what you want to achieve.

**Comment by wincent3** [comment]
Ok. Step by step. 
I make layer in QGIS set GEOMETRY as POINT.  Makeing filds as ID nad TEXT in atributes. 
Importing to DB (postgres) from QGIS. 
Adding layer postgis. 
In properties of layer, -> Render -> using notfify messege -> my trigger funkcion.
And on Postgres make script for trigger, and funkcion.

This same way for layer AS POLIGON, all it is fine. Working well. But problem is on POINT layer. 
error msg here (but in polish):
"
Nie można zatwierdzić zmian dla warstwy TEST
Błędy: BŁĄD: nie dodano 1 obiektu.
Błędy dostawcy: Błąd PostGIS podczas dodawania obiektów: ERROR: column "fild1" of relation "TEST" does not exist LINE 1: UPDATE public."TEST" SET field1 = 'wpisz tek... ^ QUERY: UPDATE public."TEST" SET field1 = 'wpisz tekst' WHERE public."TEST"."id" = NEW.id CONTEXT: PL/pgSQL function public.TEST_function() line 8 at SQL statement
"

**Comment by gioman** [comment]
> **ERROR: column "fild1" of relation "TEST" does not exist**

@wincent3 the error is in your SQL code

**Comment by wincent3** [comment]
Still no. :) i was copy the same script for POLYGON layer working well, for POINT layer is that problem.

**Comment by gioman** [comment]
> Still no. :) i was copy the same script for POLYGON layer working well, for POINT layer is that problem.

@wincent3 write down the SQL definition for table "TEST".

**Comment by wincent3** [comment]
I Was not do it from SQL  table was exported from QGIS
Just make NEW temporary as POINTS, and use DB Menager i qgis
![image](https://user-images.githubusercontent.com/68949840/88805981-2006fe80-d1b0-11ea-9bc2-3c61d125ebd9.png)
like this one, and import to DB.

**Comment by gioman** [comment]
>  like this one, and import to DB.

@wincent3 I'll try another angle: to you have  a column named "fild1" in your point layer?

**Comment by wincent3** [comment]
Yes. 
I will record a shor movie and upload to web to show the problem.

**Comment by gioman** [comment]
> Yes.

@wincent3 post the SQL definitions of your tables (when you import a table in a DB you can see what is the SQL code that generated that table, QGIS manager show you that too).

**Comment by wincent3** [comment]
ok, I found problem.
After update qgis, when db_menager generate TABLE (import) it`s start make sequence in sql for ID.
and at TABLE seting default value (from nextVal:)  > 
So QGIS can read it and set nr ID from SQL. 
But here is problem.  IF I generate nr in QGIS as new poit, and QGIS seting default value as NEXT (2,3,4,5,6) if you dalete someting like 3 QGIS still will get 7,8,9,10... 

But SQL start to see difrend ID. and now.

If I make trigger for layer -> (points, or plygon) need to delete sequencer from DB, and Delete deflaut from ID of TABLE. 
Ten I can use  NEW.id in SQL   (becuse it started to see from QGIS value).

We can clouse task it`s not correct for point layer but maby i am doing wrong from sql site. 
But if future, it will be much more easer to make QGIS id generator as in Postgres like (serial verible).

**Comment by gioman** [comment]
> it will be much more easer to make QGIS id generator as in Postgres like (serial verible)

@wincent3 you can add a "serial" column to a postgtresql table in QGIS.

**Comment by wincent3** [comment]
But ten is a problem when you use trigger at insert and use NEW.   
Becuse qgis see record as NEW with his ID, but postgres still have no ID before add to db. it feuture not bug
