### ISSUE TITLE
QGIS crash when splitting a circle feature at nodes

### ISSUE THREAD

**Issue by AurusHuang** [qgis/QGIS#38028]
**Describe the bug**
When using "Split Feature" tool and immediately click a circular feature's rightmost node, QGIS crashes. 

**How to Reproduce**
1. Create a circle. To be simple, make the circle "upright" (i.e. the diameter is horizontal). 
2. Click "Split Feature" tool and click the circle's rightmost node. 
3. QGIS crashes. 

**QGIS and OS versions**
See report below. 

**Additional context**
```Crash ID: f6c68447cd298fb8789c5ac722f40f640c40a6df


Stack Trace


QString::operator= :
QVector::takeAt qvector.h:184
QgsGeometry::splitGeometry qgsgeometry.cpp:856
QgsVectorLayerEditUtils::splitFeatures qgsvectorlayereditutils.cpp:369
QgsVectorLayer::splitFeatures qgsvectorlayer.cpp:1377
QgsMapToolSplitFeatures::cadCanvasReleaseEvent qgsmaptoolsplitfeatures.cpp:97
QgsMapToolAdvancedDigitizing::canvasReleaseEvent qgsmaptooladvanceddigitizing.cpp:93
QgsMapCanvas::mouseReleaseEvent qgsmapcanvas.cpp:1790
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:439
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:439
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1618
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.14.1-Pi
QGIS code revision: de08d6b71d
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363
```

**Comment by gioman** [comment]
> **How to Reproduce**
> 
>     1. Create a circle. To be simple, make the circle "upright" (i.e. the diameter is horizontal).
> 
>     2. Click "Split Feature" tool and click the circle's rightmost node.
> 
>     3. QGIS crashes.

@AurusHuang I cannot replicate or I cannot understand exactly how to replicate.

So...

1) try with a new QGIS profile, no 3rd party plugins installed

2) if the problem persist please attach a screencast of the whole process

**Comment by gioman** [comment]
Closing for lack of feedback.

**Comment by Intuos5** [comment]
When splitting a polyline with the split feature tool and snaps enabled, splitting a vertex of the polyline to which the tool snaps, crashes QGIS, this occurs consistently (regardless of the feature) and must therefore be a bug. 

## Report Details

**Crash ID**: [bf5aad7d7cd503fbd2a55c218e9659b47c0ef268](https://github.com/qgis/QGIS/search?q=bf5aad7d7cd503fbd2a55c218e9659b47c0ef268&type=Issues)


**Stack Trace**
<pre>
QString::operator= :
QgsGeometry::splitGeometry :
QgsGeometry::splitGeometry :
QgsVectorLayerEditUtils::splitFeatures :
QgsVectorLayer::splitFeatures :
QgsMapToolSplitFeatures::cadCanvasReleaseEvent :
QgsMapToolAdvancedDigitizing::canvasReleaseEvent :
QgsMapCanvas::mouseReleaseEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>


**QGIS Info**
QGIS Version: 3.16.9-Hannover
QGIS code revision: 9f8d2f79
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.1
Running against GDAL: 3.3.1



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

**Comment by gioman** [comment]
> When splitting a polyline with the split feature tool and snaps enabled, splitting a vertex of the polyline to which the tool snaps, crashes QGIS, this occurs consistently (regardless of the feature) and must therefore be a bug.

@Intuos5 please try with a new QGIS profile, no 3rd party plugins installed. If the problem persist then file a new ticket, attaching sample data and with detailed steps to replicate.
