### ISSUE TITLE
Bug plug in

### ISSUE THREAD

**Issue by nocemassao** [qgis/QGIS#38047]
Crash ID: 472ea3512682a3798d2cecc71f612973b1cc7185

Stack Trace

QMetaObject::activate :
QHttpMultiPart::qt_metacast :
QSslKey::operator!= :
QSslKey::operator!= :
QMetaObject::activate :
QAbstractSocket::proxyAuthenticationRequired :
QMetaObject::activate :
QAbstractSocket::proxyAuthenticationRequired :
QNetworkProxyQuery::networkConfiguration :
QMetaObject::activate :
QAbstractSocket::disconnected :
QAbstractSocket::canReadLine :
QNetworkProxyQuery::networkConfiguration :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:439
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
QEventLoop::exec :
QThread::exec :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.14.1-Pi
QGIS code revision: de08d6b71d
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.16299

**Comment by gioman** [comment]
@nocemassao 

please add detailed steps to replicate

edit the title in order to be meaningful 

try with a new QGIS profile: settings > profiles > new profile

**Comment by nocemassao** [comment]
Qgis - complement - list - new
Crash ID: 472ea3512682a3798d2cecc71f612973b1cc7185


Stack Trace


QMetaObject::activate :
QHttpMultiPart::qt_metacast :
QSslKey::operator!= :
QSslKey::operator!= :
QMetaObject::activate :
QAbstractSocket::proxyAuthenticationRequired :
QMetaObject::activate :
QAbstractSocket::proxyAuthenticationRequired :
QNetworkProxyQuery::networkConfiguration :
QMetaObject::activate :
QAbstractSocket::disconnected :
QAbstractSocket::canReadLine :
QNetworkProxyQuery::networkConfiguration :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:439
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
QEventLoop::exec :
QThread::exec :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.14.1-Pi
QGIS code revision: de08d6b71d
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.16299
![qgis complement error](https://user-images.githubusercontent.com/33576768/89559408-0129ed00-d7ec-11ea-8411-673ac800babd.JPG)

**Comment by gioman** [comment]
@nocemassao please try with a new QGIS profile: settings > user profiles > new profile

**Comment by gioman** [comment]
Closing for lack of feedback.
