### ISSUE TITLE
Identify Features Incorrect Selection

### ISSUE THREAD

**Issue by JamesMaxwellHarrison** [qgis/QGIS#38052]
I posted this issue on gis.stackexchange.com and it was suggested I post it here.
https://gis.stackexchange.com/questions/368847/identify-features-incorrect-selection?noredirect=1#comment604354_368847 

**Describe the bug**

The identify features tool returns the wrong selection when I try to select multiple features. In the image, I am trying to select the orange region, but QGIS is identifying the red region (located right above the popup window).

Note that clicking a single feature works correctly, only the "click-and-drag" works incorrectly.

![](https://i.stack.imgur.com/XkJds.png)

**How to Reproduce**

The shapefile (15MB zipped, 30MB unzipped) can be found at the following link:
https://cdn.vanderbilt.edu/vu-my/wp-content/uploads/sites/133/2019/04/14090344/RR1826-1911Modified0509161.zip

Load the shapefile and then try to use the click-and-drag identify features tool

**QGIS and OS versions**

QGIS version
3.14.1-Pi
QGIS code revision
de08d6b71d
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
db_manager; 
MetaSearch; 
processing

**Additional context**

I also tried using GeoPandas to convert the shapefile (originally in ESRI:102003) to EPSG:4326 before loading into QGIS. This does not allow me to select any features at all with the "click-and-drag" method (even when the project CRS is EPSG:4326). This change in behvaior makes me think the issue is with some CRS setting.

**Comment by gioman** [comment]
@JamesMaxwellHarrison just tested on the same QGIS version and same OS and OS version, seems to work fine here:

![Screenshot_20200730_182029](https://user-images.githubusercontent.com/1951107/88953890-7304b280-d291-11ea-86a9-564606eb816e.png)

**Comment by JamesMaxwellHarrison** [comment]
Odd. I have tried this so many times. I even reinstalled QGIS and re-downloaded the file. Still doesn't work. Thanks anyway.

**Comment by gioman** [comment]
@JamesMaxwellHarrison please try with a new QGIS profile.

**Comment by JamesMaxwellHarrison** [comment]
Sorry, I assumed user profiles were reset on re-install. That worked. Thanks.
