### ISSUE TITLE
Batch processing - 'Verbose Logging' as input parameter

### ISSUE THREAD

**Issue by spatialthoughts** [qgis/QGIS#38054]
Running a model in batch processing mode adds a 'Verbose Logging' input. The column headers and the column values are all in wrong order. There is no column to specify the output layer. The whole batch processing dialog for models look quite wrong. See thie screenshot

<img width="845" alt="verbose" src="https://user-images.githubusercontent.com/5227506/88963683-db6d8700-d2c5-11ea-93fc-9299fc1b031e.png">

Also attached a model that you can use to reproduce, but this happens with all the models. Right-click on any model and select 'Execute as a batch process' 

[maritime_piracy_model.model3.zip](https://github.com/qgis/QGIS/files/5003331/maritime_piracy_model.model3.zip)

**QGIS and OS versions**

QGIS version | 3.14.1-Pi | QGIS code revision | de08d6b71d
-- | -- | -- | --
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.28.0 | Running against SQLite | 3.28.0
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018

**Additional context**

**Comment by nyalldawson** [comment]
Actually it seems like just the header titles are out of sync -- the table contents are correct
