### ISSUE TITLE
Modeler does not pass on 'Pre-Calculated Value' expression to algorithms

### ISSUE THREAD

**Issue by spatialthoughts** [qgis/QGIS#38055]
This is a regression with 3.14. When adding an expression as 'Pre-calculated Value' in the modeler, the expression value is passed on as None to the algorithm. 

Consider the attached test.model3 . It takes an integer input and uses 'Extract by Expression' algorithm to extract the matching feature from the input. The expression is added as 'Pre-calculated Value' input in the algorithm. When running, the algorithm fails and log shows the  value **EXPRESSION: None** . The same happens with other algorithms such as Field Calculator that uses expressions.

<img width="750" alt="model1" src="https://user-images.githubusercontent.com/5227506/88968322-cba57100-d2cc-11ea-8e26-3cbe3d114e35.png">
<img width="883" alt="model2" src="https://user-images.githubusercontent.com/5227506/88968347-cf38f800-d2cc-11ea-9c93-59ff70000166.png">

Change the input to 'Value' and adding the same expression fixes this. But it exposes yet another bug. The expression here uses input value, but the input is not connected to the algorithm.
<img width="946" alt="model3" src="https://user-images.githubusercontent.com/5227506/88968806-833a8300-d2cd-11ea-9cb1-9018629eb385.png">

Attaching the model file and sample data that can reproduce these problems.
[model_and_data.zip](https://github.com/qgis/QGIS/files/5003558/model_and_data.zip)

**QGIS and OS versions**

**Additional context**

**Comment by nyalldawson** [comment]
There's no bug here -- as the expression builder for precalculated expression explains at the bottom of the dialog, your expression needs to return a **string** which evaluates to an expression

**Comment by spatialthoughts** [comment]
@nyalldawson Thanks. My bad. Enclosing the expression in single quotes works. The second issue remains though. The input parameter doesn't get connected to the algorithm if the expression is returned as a string.

<img width="1013" alt="model4" src="https://user-images.githubusercontent.com/5227506/89033942-909b5000-d355-11ea-8166-6bebcc167ce9.png">

**Comment by nyalldawson** [comment]
To confirm -- this is just a visual thing, the algorithm runs correctly?

**Comment by spatialthoughts** [comment]
Yes. The model runs fine. The bug is that when the expression is written as a string, the visual line connecting the input disappears.

**Comment by Pedro-Murteira** [comment]
Still valid on QGIS 3.22.4 and 3.24.0.

**Comment by alexbruy** [comment]
Can we close this as it is not a bug, see https://github.com/qgis/QGIS/issues/38055#issuecomment-666664117
