### ISSUE TITLE
Empty Geometry not according to standard

### ISSUE THREAD

**Issue by adepoch** [qgis/QGIS#38065]
Hi. I've created a geopackage via right click options. Asked for a new layer. Opened table view, and put the new payer in edit mode. Then added a record from that window and hit save (no geometry created). I've then pulled apart the geometry for that record using Python and SQLite and found that the record has NULL for the geometry column. This is not according to the standard of what an empty geometry should contain. https://www.geopackage.org/spec/#gpb_spec . There should be an object that contains flags indicating an empty geometry, and I think it's meant to have no envelope. If not, then how do I create such an object. I need this for a project I'm working on.

**Comment by nyalldawson** [comment]
This will need to be filed on the gdal issue tracker, as gdal is used to write geopackage files.
