### ISSUE TITLE
GeoPDF exports fails with custom CRS layers

### ISSUE THREAD

**Issue by archaeobotics** [qgis/QGIS#38064]
**Describe the bug**
Trying to export a GeoPDF from Map Composer including layers with a rotated custom CRS (Proj string: +proj=omerc +lat_0=47.173836897 +lonc=8.4550705414 +alpha=29.3 +k=1 +x_0=750 +y_0=250 +gamma=0 +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs) generates "Could Not Create Printer" error. The problem was not present before GeoPDF export was introduced, normal PDF export works flawlessly. The problem seems to mainly occur with "old" layers digitized or imported prior to the release of QGIS 3.10, newly digitized data will work without problems. This might be related to the issue described [here](https://github.com/qgis/QGIS/issues/34438)?

**How to Reproduce**
In Map Composer add a map object with a layer in a rotated custom CRS (Proj string see above), then try to export a GeoPDF.
Error message => "Could Not Create Printer".

**QGIS and OS versions**
QGIS 3.10 and 3.14.1 on Windows 10

**Comment by nyalldawson** [comment]
I can't reproduce this. Using the provided CRS exports without issue here (see attachment). Are you able to provide a sample project?
[Layout 2a.pdf](https://github.com/qgis/QGIS/files/5258862/Layout.2a.pdf)

**Comment by gioman** [comment]
Closing for lack of feedback.
