### ISSUE TITLE
Travis: gdal_edit.py not available to test Gdal Assign Projection processing algorithm

### ISSUE THREAD

**Issue by rldhont** [qgis/QGIS#38079]
**Describe the bug**
To fix #37920, the Gdal Assign Projection processing algorithm has been fixed and a test has been created #37919.
The test has been deactivated on Travis because `gdal_edit.py` is not available. https://github.com/qgis/QGIS/blob/master/python/plugins/processing/tests/GdalAlgorithmsRasterTest.py#L138
```
Processing(0): GDAL execution console output
/bin/sh: 1: gdal_edit.py: not found
```

**How to Reproduce**

1. Remove the `@unittest.skipIf` decorator in GdalAlgorithmsRasterTest
2. Run the test with the same environment as travis
3. Check the log and see the message `/bin/sh: 1: gdal_edit.py: not found`

**Additional context**

It seems that `gdal_edit.py` is available in `python-gdal` package and not in `python3-gdal`.

**Comment by nyalldawson** [comment]
Why not add this to the testing image docker container? It sounds like a valuable addition to me!

**Comment by alexbruy** [comment]
Seems `python3-gdal` already added to the testing container.
