### ISSUE TITLE
The output preview of make_interval function does not correspond to the provided help example

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#38073]
See in image below what the output preview proposes and what the help example states
![image](https://user-images.githubusercontent.com/7983394/89068105-ddd8eb00-d370-11ea-9799-b37708ef267d.png)
I would have expected they both show something similar but my tests seem to return always a value in days and not a concatenated string of various value/units. TBH, I don't know what is the storage format of interval so did not explore too much...

**Comment by rduivenvoorde** [comment]
@DelazJ had a short look into this, the interval is an QGIS only class: QgsInterval
https://qgis.org/api/classQgsInterval.html which internal data is seconds (I think).

The output preview indeed is not as in the Examples, but always shown in days. But the logic is ok, as:

```make_interval(hours:=3,days:=1)``` shows ```<interval: 1.125 days>```

which is 'right'. I cannot find where the 'toString' or formatting is done for the Preview...

**Comment by rduivenvoorde** [comment]
Ah found it:
https://github.com/qgis/QGIS/blob/master/src/core/expression/qgsexpression.cpp#L979
So looks like it is hardcode in 'days'..
Note: https://github.com/qgis/QGIS/blob/master/src/core/expression/qgsexpression.cpp#L977 I think is copy/paste issue

So I think easiest would be to change the 'Examples' text.

Another option would be to maybe add (comples?) formatting logic which substract full days(hours/months/weeks/years etc) and the recursively prints the resulting unit?

**Comment by rduivenvoorde** [comment]
@DelazJ with a simple if/else chain 
```
    if (interval.days() > 1 )
    {
      return startToken + tr( "interval: %1 days" ).arg( interval.days() ) + endToken;
    }
    else if (interval.hours() > 1 )
    {
      return startToken + tr( "interval: %1 hours" ).arg( interval.hours() ) + endToken;
    }
    else if (interval.minutes() > 1 )
    {
      return startToken + tr( "interval: %1 minutes" ).arg( interval.minutes() ) + endToken;
    }
    else
    {
      return startToken + tr( "interval: %1 seconds" ).arg( interval.seconds() ) + endToken;
    }
```

it is easy to get something like this:

```
make_interval(years:=0.75)
<interval: 273.938 days>

make_interval(days:=2, hours:=3)
<interval: 2.125 days>

make_interval(hours:=3,days:=1)
<interval: 1.125 days>

make_interval(minutes:=30)
<interval: 30 minutes>

make_interval(minutes:=0.5,seconds:=5)
<interval: 35 seconds>
```

wouldn't that be 'good enough'?

Then fix the examples and done?
Happy to do this pr

**Comment by DelazJ** [comment]
Hi @rduivenvoorde 
Thanks for looking into this.
TBH I'm not a time-related feature users and was mainly reporting an inconsistency I found while reviewing docs.
I think something to consider is how easy the output could be reused, eg to create a date using existing functions, or to compare them. I don't know if it's currently the case but, not make it a dead end result could be good.
The last suggestion looks like a dead end solution, something people could use the extracting and formatting functions to come to. Not sure it should be the default but again I'm not a regular user.

**Comment by roya0045** [comment]
I guess this can be closed.

**Comment by DelazJ** [comment]
Yes, thanks for reminding
