### ISSUE TITLE
prepare_commit.sh / astyle.sh do not work in  WSL-shell when platform astyle is used

### ISSUE THREAD

**Issue by iona5** [qgis/QGIS#38089]
When i execute `prepare_commit.sh` in my WSL bash i get this error
```
user@computer:~/coding/qgis-dev/qgis-master$ scripts/prepare_commit.sh
Cannot open default option file /mnt/e/Personal/coding/qgis-dev/qgis-master/E:
Artistic Style has terminated
```
I am using the platform `astyle` installed via apt, i do not build with HAVE_ASTYLE.

There seems to be an explicit conversion from unix-paths to Windows-paths in astyle.sh when loading the options file. 

https://github.com/qgis/QGIS/blob/46a91533d6a17c52400bba7d1e7332fa6d2748cf/scripts/astyle.sh#L90-L92

This always kicks in when using WSL, but here it is causing trouble because in my case the conversion is not needed. When i comment that part out in astyle.sh everything works fine.

I am not really sure what the rationale for the current implementation is - probably using an qgisstyle built along with QGIS? Thats why i am a little hesitant to create a PR, but this would be my approach in that case:

```bash
# when using the qgisstyle built alongside QGIS on windows platforms,
# convert path to options file
if [ $ASTYLE != "astyle" ] ; then
        if type -p cygpath >/dev/null; then
                ASTYLEOPTS="$(cygpath -w "$ASTYLEOPTS")"
        fi

        if type -p wslpath >/dev/null ; then
                ASTYLEOPTS="$(wslpath -a -w "$ASTYLEOPTS")"
        fi
fi
```

if somebody knowledgeable about this can confirm, i of course can go ahead and fix this.

**Comment by m-kuhn** [comment]
See https://github.com/qgis/QGIS/pull/8460
CC @nyalldawson

**Comment by Pedro-Murteira** [comment]
@iona5 Hello, is this issue still valid on more recent releases?

**Comment by iona5** [comment]
yes it seems to be. on latest master (#180ae3bc16):
```bash
user@pc:/mnt/e/Personal/coding/qgis-dev/qgis-master$ which astyle
/usr/bin/astyle
user@pc:/mnt/e/Personal/coding/qgis-dev/qgis-master$ astyle -V
Artistic Style Version 3.1
```
adding a change ....
```bash
user@pc:/mnt/e/Personal/coding/qgis-dev/qgis-master$ echo "// some random change" >> src/core/qgsapplication.h
user@pc:/mnt/e/Personal/coding/qgis-dev/qgis-master$ git diff
diff --git a/src/core/qgsapplication.h b/src/core/qgsapplication.h
index ebb86704e1..adcc3c1dce 100644
--- a/src/core/qgsapplication.h
+++ b/src/core/qgsapplication.h
@@ -1152,3 +1152,4 @@ class CORE_EXPORT QgsApplication : public QApplication
 // clazy:excludeall=qstring-allocations

 #endif
+// some random change
```
and then trying `prepare_commit.sh`gives the same error
```bash
user@pc:/mnt/e/Personal/coding/qgis-dev/qgis-master$ scripts/prepare_commit.sh
Cannot open default option file /mnt/e/Personal/coding/qgis-dev/qgis-master/E:
Artistic Style has terminated

``` 
workaround to check `$ASTYLE` as per my first post still valid as well.
