### ISSUE TITLE
Good afternoon. I created a plugin. An error appears when enabling this plugin

### ISSUE THREAD

**Issue by Denis-develop** [qgis/QGIS#38098]
**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by Denis-develop** [comment]
[BugReport.txt](https://github.com/qgis/QGIS/files/5014161/BugReport.txt)

**Comment by Denis-develop** [comment]
help me find the reason for the error

**Comment by nyalldawson** [comment]
This isn't a support service -- ask on the QGIS mailing list or on gis.stackexchange.com instead!
