### ISSUE TITLE
composer attribute table sort by virtual or joined fields doesn't work

### ISSUE THREAD

**Issue by ADAMKEPES** [qgis/QGIS#38094]
composer attribute table sort by virtual or joined fields doesn't work    qgis 3.14 version

**Comment by gioman** [comment]
@ADAMKEPES 

please add detailed steps (and if needed sample data) that lead to the issue.

This is what you must add to tickets:



**Describe the bug**


**How to Reproduce**



**QGIS and OS versions**



**Additional context**

**Comment by ADAMKEPES** [comment]
[dxf line label problem.zip](https://github.com/qgis/QGIS/files/5014805/dxf.line.label.problem.zip)

just try to set labeling of line layer to center, from above/beyond. And then the software freezes

**Comment by gioman** [comment]
> just try to set labeling of line layer to center, from above/beyond. And then the software freezes

@ADAMKEPES is this ticket about sorting a table in a composer, or about labelling?

Please add step by step instructions to replicate the issue.



> composer attribute table sort by virtual or joined fields doesn't work qgis 3.14 version

no problem in doing this with your project, tested on QGIS master on Linux.

**Comment by ADAMKEPES** [comment]
sorry. that was for another thread. On windows 10 version, it completely freezes.

Here is the sort problem file. Jost go to composer view and see on the attribute table it can't be sorted.

[sort problem.zip](https://github.com/qgis/QGIS/files/5014869/sort.problem.zip)

**Comment by gioman** [comment]
Sorting by virtual field works here, not by joined one.

**Comment by ADAMKEPES** [comment]
maybe i have tried to make virtual field from joined field and then try to sort by that. Not works by joined field, that is the problem.

**Comment by gioman** [comment]
> maybe i have tried to make virtual field from joined field and then try to sort by that.

this seems to work.

**Comment by ADAMKEPES** [comment]
not working for me, i have tried with my first response. The basic problem would still remain unsolved with that solution.

**Comment by Pedro-Murteira** [comment]
@ADAMKEPES Hello, is this issue still valid on more recent releases?
