### ISSUE TITLE
CSV date field being interpreted as time type

### ISSUE THREAD

**Issue by sjmelhuish** [qgis/QGIS#38091]
**Describe the bug**
Since 3.14.0-Pi the behaviour of CSV import has changed. Previously with "Record and Fields Options -> Detect Field Types" selected UK-format date fields would result in a QString field. Interpretation as a date would be nice, I suppose,  but this is harmless. However, in 3.14 such a field is interpreted as a time, resulting in a meaningless QTime field. Dates entered in ISO 8601 format as interpreted correctly, yielding a QDate.

**How to Reproduce**

I have provided a zip containing an example project. It loads 2 CSV files. 
* `date-issue-sample.csv` contains a single point with a field named `Valid From (dd/mm/yyyy)`. The single row fills this field with a UK-format date - `01/03/2004`
*  `date-issue-sample2.csv` contains a single point with a field named `Valid From (dd/mm/yyyy)`. The single row fills this field with the same date in ISO 8601-format - `2004-03-01`

The UK date is given a QTime value of `01:03:20.000`
The ISO date is given a QDate value of `2004-03-01`

**QGIS and OS versions**

QGIS version
3.14.0-Pi
QGIS code revision
9f7028fd23
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
db_manager; 
MetaSearch; 
processing

**Additional context**

[Date-Issue.zip](https://github.com/qgis/QGIS/files/5011906/Date-Issue.zip)

Thank you,
Simon Melhuish, G4TJC
[Summits On The Air](https://www.sota.org.uk/)

**Comment by nirvn** [comment]
@sjmelhuish , which locale is your system / QGIS on?

**Comment by sjmelhuish** [comment]
English - UK

**Comment by nirvn** [comment]
@sjmelhuish , can you open QGIS' python console and type this command: `QTime.fromString('01/03/2004').isValid()` and let me know whether it returns True or False? Thanks

**Comment by sjmelhuish** [comment]
```
QTime.fromString('01/03/2004').isValid()
True
```

**Comment by nirvn** [comment]
@sjmelhuish , how insane is that :) OK, try this command: `QTime.fromString('01/03/2004',Qt.ISODate).isValid()` -- does it still return True?

**Comment by sjmelhuish** [comment]
```
QTime.fromString('01/03/2004',Qt.ISODate).isValid()
True
```

**Comment by uclaros** [comment]
Could this be related to #37857 ?
