### ISSUE TITLE
QgsVectorLayer::uniqueValues() returns both None and NULL on memory layer

### ISSUE THREAD

**Issue by uclaros** [qgis/QGIS#38107]
**Describe the bug**
Running `QgsVectorLayer::uniqueValues()` on a field that contains only null values we get a set `{None}`

If one edits a value in the attribute table and re-set it to null, then the returned set is `{None, NULL}`

**Comment by elpaso** [comment]
This might be provider-related, can you attach a sample project with data?

**Comment by uclaros** [comment]
> This might be provider-related, can you attach a sample project with data?

Seems to be an issue with the memory layer provider; I cannot reproduce it with a geopackage layer.
However, trying with a shapefile, I noticed that empty or whitespace strings are converted to `NULL`
[uniqueValues.zip](https://github.com/qgis/QGIS/files/5015572/uniqueValues.zip)

The layer in the attached project had `'asdf', '', ' ', '  '` as values for the f1 field. After saving and reopening the attribute table they're nulls. Should I open a different issue?

**Comment by uclaros** [comment]
Actually, values in shapefile text fields are `trim()`ed before saving, removing whitespaces from the start and end of the string!

**Comment by uclaros** [comment]
I can no longer replicate this on 5c87f70 on debian testing.
What I still notice though is that when adding a new field to a memory layer then `layer.uniqueValues(0)` returns `{None}`.
After editing values on the field and clearing them, then the same method returns `{NULL}`.
This is strange but insignificant, we could close this.
