### ISSUE TITLE
QGIS icon sizes too large on lower resolution screen

### ISSUE THREAD

**Issue by deepalimody** [qgis/QGIS#38109]
I use 2 screens. One that is resolution 1920x1080 and laptop screen of resolution 3840x2160.
I need QGIS to look the same on both screens. Currently the icons are far too large on the lower resolution screen.
Is there a solution?
![lower resolution screen](https://user-images.githubusercontent.com/65011736/89173753-6094bc80-d5a2-11ea-9413-09dfdce59f5c.jpg)
![higher resolution screen](https://user-images.githubusercontent.com/65011736/89173758-625e8000-d5a2-11ea-8f86-540587980f86.jpg)

**Comment by gioman** [comment]
@deepalimody is this a question or a bug report?

**Comment by deepalimody** [comment]
It’s a question. Is there a solution to the problem?

If not, then it’s a bug report : )

**Comment by gioman** [comment]
> It’s a question.

@deepalimody this place is to report bugs. If  you are unsure you should first look for some feedback on the users or developers mailing lists. If confirmed  (is a bug) then file a ticket here. Anyway... Icons size is defined at the application level, in settings > general > application. So you can open two instances of QGIS and set the icon size you prefer in each instance. But when closing and reopening you'll probably have the same initial problem.

**Comment by nirvn** [comment]
It's likely in part a bug. QGIS (Qt?) doesn't handle multi monitor with varying DPIs.

**Comment by gioman** [comment]
> It's likely in part a bug. QGIS (Qt?) doesn't handle multi monitor with varying DPIs.

closing as upstream issue?

**Comment by deepalimody** [comment]
Yes thats fine,
Thank you for your response and the method for resizing icons. It helps somewhat.
