### ISSUE TITLE
Shapefile string fields get trimmed()

### ISSUE THREAD

**Issue by uclaros** [qgis/QGIS#38112]
**Describe the bug**
Values entered on a shapefile's string field are automatically `trimmed()` removing leading and trailing whitespaces.

**How to Reproduce**
- Load a shapefile with a string field
- Start editing
- Open the attribute table and edit the string field for some feature, entering a string beginning and ending with a whitespace.
- Save
- Refresh
- The value is now trimmed.

Is this expected shapefile behaviour?

**Comment by gioman** [comment]
Confirmed here too on master/linux. Not sure if is expected.

**Comment by roya0045** [comment]
IMO it's a good thing as trying to find a leftover whitespace can be annoying.

**Comment by iona5** [comment]
i would rather expect that strings are trimmed. especially when copy/pasting you accidentally pick up a whitespace, a tab or a linebreak.

what would be the use case wanting to include leading/trailing whitespaces?

**Comment by gioman** [comment]
> what would be the use case wanting to include leading/trailing whitespaces?

not sure what could be the use case but in general in QGIS we want things to work as much as similar as database in backends and clients. I don't know a DB client (I use PgAdmin and DBeaver) that trims leading/trailing whitespaces automatically.

**Comment by iona5** [comment]
> don't know a DB client (I use PgAdmin and DBeaver) that trims leading/trailing whitespaces automatically.

hmm, if this is just project policy than i agree. but i personally never expect QGIS to behave like a db-client GUI (and i've worked with these a lot) and i imagine a lot of QGIS users don't do either (if they'd ever know what a db-client is ;) ). i think the problem with copy/paste is quite common and i'd rather have my GIS help me in that case, but maybe thats just me :)

**Comment by rouault** [comment]
This is a behaviour of OGR / Shapelib.
In .dbf, field content is normally right padded with spaces when it doesn't occupy the full width of the column. So on reading, removing right padded is generally the right thing to do. On reading, the driver also removes left padding. I'm not sure of the reason for this, probably that some writers would left-pad instead of right-pad. Anyway, this is the behaviour of shapelib since day one, so 20 years.

**Comment by uclaros** [comment]
> So on reading, removing right padded is generally the right thing to do. On reading, the driver also removes left padding.

So, there is no distinction between an empty string, a whitespace string and null for the shapefile?

**Comment by rouault** [comment]
> So, there is no distinction between an empty string, a whitespace string and null for the shapefile?

Not really. As a special behavior, on reading shapelib will consider a fully blank string field as a NULL string.

**Comment by uclaros** [comment]
Yup, I'm covered!
