### ISSUE TITLE
Layer misalignment in newer QGIS versions (3.14+)

### ISSUE THREAD

**Issue by alin-c** [qgis/QGIS#38110]
I have a folder containing a .qgz file and some other auxiliary files (.gpkg, .shp, .prj...) that should display an underlying OSM Standard map, another map taken from the Romanian surveying agency and some polygon layers on top.
The project was created with QGIS 3.8: [Simnic.zip](https://github.com/qgis/QGIS/files/5015831/Simnic.zip)

Without any modifications, opened side-by-side in the two versions of QGIS, it is displayed correctly in **QGIS 3.8.3**:
![qgis3 8 3](https://user-images.githubusercontent.com/46907466/89180271-1a3b5f80-d59a-11ea-89db-796178a07902.png)

but in **QGIS 3.14.1** it is misaligned:
![qgis3 14 1](https://user-images.githubusercontent.com/46907466/89180283-20c9d700-d59a-11ea-9f9f-ae9ec7a9ebf6.png)

Can you please fix this alignment issue or provide a workaround for it in QGIS 3.14+? Otherwise, I'm stuck with the older version that works.

Thank you.

**Comment by gioman** [comment]
@alin-c change your project CRS to 3844, it will align properly, 31700 is deprecated

https://spatialreference.org/ref/epsg/31700/

Recent releases of QGIS use modern versions of important dependencies, like for PROJ and GDAL.

**Comment by alin-c** [comment]
I've just changed the project CRS and (so far) the layers are displayed correctly.
I guess it wasn't a bug, but a "feature".
Thank you @gioman
