### ISSUE TITLE
Extremely slow loading postgis layers from huge databases

### ISSUE THREAD

**Issue by borysiasty** [qgis/QGIS#38114]
With the postgres provider, the layer load performance depends heavily on number of tables in database, because QgsPostgresProvider::loadFields() fetches the whole pg_type table.

In my case of a database with hundreds of thousands tables, with poor connection, instantiation of one layer may take over one minute, what makes big projects opening **over one hour** (!).

By filtering only due records of pg_type, that time is lowered into seconds.

**Comment by weca-theo** [comment]
"By filtering only due records of pg_type, that time is lowered into seconds."
Can you explain this more? Having same issue in 3.22.8 and 3.28.1.

**Comment by borysiasty** [comment]
@weca-theo Sorry for the late reply. It was quite a while ago, but from what I can recall and reconstruct from the pull request, the old behavior was like that: When fetching column metadata for instantiating a QgsLayer, first select the whole `pg_type` table, and then find the necessary records: 

https://github.com/qgis/QGIS/pull/38158/files#diff-8fc1e19bdc3a51f281bf3789e7087de205ae9287ad1a30225aaaf7d92e033154L812

So I added a `WHERE oid IN ()` clause to that query:
https://github.com/qgis/QGIS/pull/38158/files#diff-8fc1e19bdc3a51f281bf3789e7087de205ae9287ad1a30225aaaf7d92e033154R911

for only collecting oids of columns used by this layer. Going upwards through the code, the list od oids come from this query:    

https://github.com/qgis/QGIS/pull/38158/files#diff-8fc1e19bdc3a51f281bf3789e7087de205ae9287ad1a30225aaaf7d92e033154L830

Please note the `mQuery` variable may be misleading. In case of query-based layers, the query fetches all the resulting columns. But in case of a normal layer, based on a single table, I'm pretty sure that `mQuery` just contains that table name. 

That fix helped a lot in that time. Perhaps you're experiencing a different problem...

**Comment by weca-theo** [comment]
> 

My problem is during .qgz project file load, 1000s of SQL metadata queries are being performed for every PostGIS table loaded in the project. Also these queries are made for every column within that table. Project load times of 2-5 minutes for a project with only 100 layers.

Example queries, as seen in the new SQL query logging tool:

`"SQL": "SELECT domain_name, domain_schema FROM information_schema.columns WHERE table_name='example_table_name' AND column_name='example_column_name'"`
and
`"SQL": "SELECT typtype FROM pg_type WHERE typname='example_data_type'"`
