### ISSUE TITLE
attribute tables

### ISSUE THREAD

**Issue by jimbo-jones1313** [qgis/QGIS#38129]
for some reason column names in attribute tables are changing; the first one read "site" but became "_1"
the second read "specimen" but became a character from what I believe to be Japanese Katana (or similar)
![qgis](https://user-images.githubusercontent.com/63853386/89263993-7f429400-d632-11ea-9da4-f291d66b548f.PNG)
when data was entered into the tables, it disappeared as soon as anything was saved
the column names were then changed to Chinese...
![qgis2](https://user-images.githubusercontent.com/63853386/89264117-ab5e1500-d632-11ea-8f17-f97e909471d7.PNG)

editing contents in attribute tables should be something one takes for granted...

**Comment by jimbo-jones1313** [comment]
this is the result of attempting to create .shp files... editing the resulting .dbf files only generates more Chinese characters

**Comment by uclaros** [comment]
This looks like  #38037
Please share more info: QGIS / OS versions, system locale, how did you create the shapefile, what encoding did you use, how did you add the fields?

**Comment by jimbo-jones1313** [comment]
qgis 3.14, Win10, English language
created shapefile by using "create layer/new shapefile layer"
encoding: utf-16

**Comment by jimbo-jones1313** [comment]
added fields by typing in a field name, then pressing "add to fields list" button

**Comment by uclaros** [comment]
OK, I can kind of replicate it here too. I've got the japanese field but can't get the chinese to show! =p
Using UTF-16 seems to cause this. If you do not have a specific need for UTF-16 use the more tested utf-8 until this is investigated.

**Comment by jimbo-jones1313** [comment]
i just used utf-16 because that was the default... but utf-8 does seem to solve it: thanx!

**Comment by gioman** [comment]
See: http://osgeo-org.1560.x6.nabble.com/gdal-dev-Shapefiles-encoded-in-UTF-16-td5395870.html

closed as upstream issue.

**Comment by uclaros** [comment]
@gioman If utf-16 is not supported it should not be in that list! And even if it is left there, it definitely should not be the default value under no circumstances!

**Comment by gioman** [comment]
> If utf-16 is not supported it should not be in that list! And even if it is left there, it definitely should not be the default value under no circumstances!

I agree, but better file a separate ticket.
