### ISSUE TITLE
unstable?

### ISSUE THREAD

**Issue by jimbo-jones1313** [qgis/QGIS#38130]
## User Feedback

No idea.
It just crashed.

## Report Details

**Crash ID**: [ca1b656ae203ef3498968a2a01063e0d40c5dfa8](https://github.com/qgis/QGIS/search?q=ca1b656ae203ef3498968a2a01063e0d40c5dfa8&type=Issues)

**Stack Trace**
<pre>
QgsProcessingToolboxModel::data qgsprocessingtoolboxmodel.cpp:436
</pre>

**QGIS Info**
QGIS Version: 3.14.1-Pi
QGIS code revision: de08d6b71d
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by uclaros** [comment]
> No idea.
> It just crashed.

This information is not of much use to anyone trying to understand what caused the crash.
You don't need to know what caused the crash, but describing what you did just before the crash can be a good lead for a developer!

**Comment by gioman** [comment]
@jimbo-jones1313 the required infos are always the same:

1) a meaningful title

2) a detailed description of what you were doing when the crash occurred

3) try do the same and see if QGIS crashes in a consistent way

4) check if the crash is project/data dependant, if so attach sample project/data

5) try with a new QGIS profile, no 3rd party plugins installed.

**Comment by roya0045** [comment]
He seems to imply that there are crash caused by conversion here https://github.com/qgis/QGIS/blob/b4f5b48b35532e6109985da1ef5f1700630013f2/src/gui/processing/qgsprocessingtoolboxmodel.cpp#L436  in a  model.

**Comment by gioman** [comment]
Closing for lack of feedback.
