### ISSUE TITLE
Allow IDw and TIN interpolation algorithms to be used with modeler inputs

### ISSUE THREAD

**Issue by spatialthoughts** [qgis/QGIS#38139]
IDW and TIN interpolation native algorithms in QGIS uses a special UI widget InterpolationWidgets that cannot be used in the modeler. While one is able to add these algorithms to a model, it is not possible to use model input or algorithm outputs for interpolation - making it impossible to use in a model.

<img width="1396" alt="idw" src="https://user-images.githubusercontent.com/5227506/89292374-e6d00200-d679-11ea-8aaf-65e6205f66b0.png">

This is the case in both 3.10 LTR and 3.14.

**Comment by alexbruy** [comment]
Duplicates #30029
