### ISSUE TITLE
Crash after paste polyline

### ISSUE THREAD

**Issue by BvYp** [qgis/QGIS#38136]
## User Feedback

In making the exercise in chapter 5.2.2 of the QGIS tutorial I didn't manage to get the second vertical line in the image visible after using "add node item". Instead of drawing a new polyline, I copied the first vertical line and pasted it, then the application crashed.

## Report Details

**Crash ID**: [c3b1bda7f575e06dde841337010c4d75de6462c1](https://github.com/qgis/QGIS/search?q=c3b1bda7f575e06dde841337010c4d75de6462c1&type=Issues)

**Stack Trace**
<pre>
QGraphicsScene::wheelEvent :
QGraphicsScene::wheelEvent :
QGraphicsScene::wheelEvent :
QGraphicsScene::wheelEvent :
QGraphicsScene::wheelEvent :
QGraphicsScene::wheelEvent :
QGraphicsScene::wheelEvent :
QGraphicsScene::wheelEvent :
QGraphicsScene::drawItems :
QGraphicsView::paintEvent :
QgsLayoutView::paintEvent qgslayoutview.cpp:1148
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
</pre>

**QGIS Info**
QGIS Version: 3.14.1-Pi
QGIS code revision: de08d6b71d
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
@BvYp please try with a new QGIS profile, settings > user profiles > new profile

**Comment by BvYp** [comment]
I have made a new profile and with the same actions there is no crash, so this was helpfull. I can now copy polylines but still I cannot make a new visible one. I can see all its properties but it does not show visible in the layout. All the properties seem the same as the two polylines I did make before.

**Comment by gioman** [comment]
> I cannot make a new visible one.

is the layer using a categorized symbology, and the new line you are drawing is not given an attribute values that matches one of the symbology classes?
