### ISSUE TITLE
Layout preview does not respect resolution potentially leading to wrong WM(T)S layer rendering

### ISSUE THREAD

**Issue by 3nids** [qgis/QGIS#38140]
With a screenshot: on the left the layout preview, on the right the output PDF (at 300 DPI)
![image](https://user-images.githubusercontent.com/127259/89296104-3276b180-d662-11ea-8a50-7937c6d8864e.png)

Manually setting the DPI to 90 "fixes" this, so that the output would use the same scale for the WMTS layer than the preview.

To properly fix this, we would need to use the same resolution for the preview than the output.
Is this an accessible solution?
Is this easily achieved?

**Comment by roya0045** [comment]
Wasn't this always the case as the displayed layer only take into account the extent displayed and the default resolution. This is why the web layer never matches the layout unless you zoom to the full layout and use matching output resolution..

**Comment by baswein** [comment]
Is this a different issue or the same https://github.com/qgis/QGIS/issues/36847#issue-627924529

**Comment by gioman** [comment]
@3nids seems the same to me.

> Is this a different issue or the same [#36847 (comment)](https://github.com/qgis/QGIS/issues/36847#issue-627924529)
