### ISSUE TITLE
Exception when opening / typing in python console

### ISSUE THREAD

**Issue by m-kuhn** [qgis/QGIS#38142]
@nirvn do you have a suspicion what could have gone wrong here?

```
An error has occurred while executing Python code: 

IndexError: list assignment index out of range 
Traceback (most recent call last):
  File "/usr/share/qgis/python/console/console_sci.py", line 431, in keyPressEvent
    self.updateSoftHistory()
  File "/usr/share/qgis/python/console/console_sci.py", line 352, in updateSoftHistory
    self.softHistory[self.softHistoryIndex] = self.text()
IndexError: list assignment index out of range


Python version: 3.8.3 (default, May 29 2020, 00:00:00) [GCC 10.1.1 20200507 (Red Hat 10.1.1-1)] 
QGIS version: 3.14.1-Pi Pi, exported 
```

PS. cannot reproduce after restarting qgis

**Comment by roya0045** [comment]
Considering the existing safeguards, I think the most probable thing that occured was that the index was at 0 and that the list was empty. Or since the index can be len of the list, it meas that the value is out of the list. But I only hhad a cursory glance.

**Comment by nirvn** [comment]
@m-kuhn , was that on a new profile? Showed up when you opened the console, after the first key stroke, or something else?

**Comment by m-kuhn** [comment]
Thanks!
