### ISSUE TITLE
removeDockWidget causes qgis crash

### ISSUE THREAD

**Issue by lucashrosa** [qgis/QGIS#38157]
h2. User Feedback

I used removeDockWidget function to configure my own interface (removing all panels but these: 'Layers', 'StatistalSummaryDockWidget', 'IdentifyResultsDock', 'GPSInformation', 'MessageLog', 'Overview'], and qgis crashed after right click on a layer

h2. Report Details

*Crash ID*: fccbb2752896f2730aa058eaa21e0028278eedc7

*Stack Trace*
<pre>
QWidgetPrivate::close_helper :
QgsUndoWidget::setUndoStack :
QgisApp::onActiveLayerChanged :
QMetaObject::activate :
QgsLayerTreeView::currentLayerChanged :
QgsLayerTreeView::onCurrentChanged :
QMetaObject::activate :
QItemSelectionModel::setCurrentIndex :
QAbstractItemView::mousePressEvent :
QTreeView::mousePressEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.4.8-Madeira
QGIS code revision: commit:04ee8e0761
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.14393

**Comment by gioman** [comment]
>  QGIS Version: 3.4.8-Madeira

@lucashrosa too old, you must test on the latest 3.10 or 3.14.

**Comment by lucashrosa** [comment]
> > QGIS Version: 3.4.8-Madeira
> 
> @lucashrosa too old, you must test on the latest 3.10 or 3.14.

Thanks Giovanni, but problem also appears in Qgis 3.10. New report error:

## Report Details

**Crash ID**: [0bef8c9ff9ce9b6e5a60ae565171829906c1ba79](https://github.com/qgis/QGIS/search?q=0bef8c9ff9ce9b6e5a60ae565171829906c1ba79&type=Issues)


**Stack Trace**
<pre>
QList<QItemSelectionRange>::size :
QgsAdvancedDigitizingCanvasItem::paint :
QGraphicsScene::dragMoveEvent :
QGraphicsScene::drawItems :
QGraphicsScene::drawItems :
QGraphicsView::paintEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QApplication::windowIcon :
QWidget::event :
QgisApp::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
QGraphicsScene::~QGraphicsScene :
QObject::event :
QGraphicsScene::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>


**QGIS Info**
QGIS Version: 3.10.5-A Coru�a
QGIS code revision: 984615fe1e
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.14393

**Comment by uclaros** [comment]
Please add steps to reproduce, it's not clear what you did there

**Comment by gioman** [comment]
> Please add steps to reproduce, it's not clear what you did there

>  QGIS Version: 3.10.5-A Coru�a

also 3.10.5 is not the latest release of 3.10 (that would be 3.10.8 at the moment).

**Comment by lucashrosa** [comment]
I do execute this function to "clean" interface and to keep just a few panels 

> def removePanels():
    panels_to_keep = ["Layers", "StatisticalSummaryDockWidget", "IdentifyResultsDock", "GPSInformation", "MessageLog", "Overview"]
    for panel in iface.mainWindow().findChildren(QDockWidget):                 
        if panel.objectName() not in panels_to_keep:
            iface.mainWindow().removeDockWidget( panel )       #crash qgis

**Comment by uclaros** [comment]
I think the proper way to do what you are trying to achieve is through *Settings > Interface Customization...*

**Comment by lucashrosa** [comment]
> I think the proper way to do what you are trying to achieve is through _Settings > Interface Customization..._

Ok, I agree, but I need to do this programmatically, inside a plugin execution.
The purpose of this is to keep only the functions (toolbars, panels) that users will need, doing customization for them

**Comment by lucashrosa** [comment]
> > Please add steps to reproduce, it's not clear what you did there
> 
> > QGIS Version: 3.10.5-A Coru�a
> 
> also 3.10.5 is not the latest release of 3.10 (that would be 3.10.8 at the moment).

## User Feedback

new version, old error

## Report Details

**Crash ID**: [ed85c457af178176d9d27266e15714dcd8c87ced](https://github.com/qgis/QGIS/search?q=ed85c457af178176d9d27266e15714dcd8c87ced&type=Issues)


**Stack Trace**
<pre>
QWidgetPrivate::close_helper :
QgsUndoWidget::setUndoStack :
QgisApp::onActiveLayerChanged :
QMetaObject::activate :
QgsLayerTreeView::currentLayerChanged :
QgsLayerTreeView::onCurrentChanged :
QMetaObject::activate :
QItemSelectionModel::setCurrentIndex :
QAbstractItemView::mousePressEvent :
QTreeView::mousePressEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>


**QGIS Info**
QGIS Version: 3.10.8-A Coru�a
QGIS code revision: d09a4f2388
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.14393

**Comment by gioman** [comment]
> I do execute this function to "clean" interface and to keep just a few panels

@lucashrosa for good measure you should ask in the developers mailing list if you are doing it right.

**Comment by nyalldawson** [comment]
I think this is a "wontfix". There's plenty of changes you could make by randomly removing integral parts of the qgis window via python which will lead to crashes. This isn't reflective of a bug in qgis, just a consequence of the python API being completely open.

If anything, it's a feature request to allow to undo dock to be removed.
