### ISSUE TITLE
Cant install plugins

### ISSUE THREAD

**Issue by federicogodan** [qgis/QGIS#38160]
**Describe the bug**
When I open Qgis and go to Help->plugins the manage plugins menu dont show, so I cant install or uninstall any plugin.

**How to Reproduce**

1. Go to Help
2. Click on Plugins
3. Nothing happens

**QGIS and OS versions**
OS: Fedora 30 (Wayland and X)

QGIS version | 3.14.1-Pi | QGIS code branch | Release 3.14
-- | -- | -- | --
Compiled against Qt | 5.13.2 | Running against Qt | 5.13.2
Compiled against GDAL/OGR | 2.3.2 | Running against GDAL/OGR | 2.3.2
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.30.0 | Running against SQLite | 3.30.0
PostgreSQL Client Version | 12.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Fedora 31 (Workstation Edition)
Active python plugins | db_manager; MetaSearch; processing

**Additional context**
None.

**Comment by roya0045** [comment]
Just go in Plugin directly instead of Help. Though I'm not sure what is the use of the Plugin in the Help menu.

**Comment by federicogodan** [comment]
Using Plugin menu directly works.

**Comment by gioman** [comment]
I'm not really sure why we have (now?) a "plugins" entry in "help", my guess is that is by mistake. Anyway it is not (I hope) a way to access the plugin manager, which is from the "Plugins" menu. This should be asked in the developers mailing list.

**Comment by nyalldawson** [comment]
@gioman it's intended as a central place for installed plugins to add their own help links. E.g. help>plugins> my plugin docs.

The intention is to avoid every plugin having to create submenus under the plugins menu in order for them to have somewhere to expose their help link.

**Comment by roya0045** [comment]
@nyalldawson In this case would it be a good idea to write 'Plugin Help' instead of only 'Plugin', yes it is redundant but removes any possible confusion.

**Comment by gioman** [comment]
> t's intended as a central place for installed plugins to add their own help links. E.g. help>plugins> my plugin docs.
> 
> The intention is to avoid every plugin having to create submenus under the plugins menu in order for them to have somewhere to expose their help link.

@nyalldawson thanks, I didn't know that.
