### ISSUE TITLE
can't import anymore CSV files located on a network share

### ISSUE THREAD

**Issue by Etaniram** [qgis/QGIS#38163]
**Describe the bug**
In QGIS 3.14.1 I am unabe to import a UTF-8 CSV file as point data using UTM X and UTM Y coordinates like I have for quite some time now. This only occurs with CSV files hosted over my network connection on a separate computer that we use for collaboration. I made a .CSV file in Excel on my desktop that imported properly then moved it to our network storage and I was unable to import the CSV. I downloaded the long-term release 3.10 and it worked fine with both files no problem. Seems to be limited to 3.14.1. I tried a clean install but that did not work.

Returns the following "Critical Error" with some information from paths redacted.

Layer is not valid: The layer file://remote-desktop/DESK%20Documents/USA/Nevada/Nye%20Co,%20NV/%20Information/UTM%20Coordinates%20LMs.csv?type=csv&maxFields=10000&detectTypes=no&xField=Easting&yField=Northing&crs=EPSG:26711&spatialIndex=no&subsetIndex=no&watchFile=no is not a valid layer and can not be added to the map. Reason:

**How to Reproduce**

Reproduced with new files and old files. Import is unsuccessful from the start.

**QGIS and OS versions**

3.14.1 -Pi

**Comment by gioman** [comment]
> hosted over my network connection on a separate computer that we use for collaboration

@Etaniram what kind of share is? samba? nfs? other?

**Comment by Etaniram** [comment]
It is just a simple Windows Share. The remote PC is used to host over a Windows 10 shared folder. We are in the process of changing over to an NFS, but haven't gotten to that point yet.

**Comment by gioman** [comment]
Confirmed also here, nasty regression.
