### ISSUE TITLE
Crash ID: c06417bf575d0d9dfd06f736cbebb4aad290f686

### ISSUE THREAD

**Issue by fernandocostabsb** [qgis/QGIS#38164]
Crash ID: c06417bf575d0d9dfd06f736cbebb4aad290f686

Stack Trace

QList::QList qlist.h:809
QgsLayerTreeNode::children qgslayertreenode.h:110
QgsLayerTreeModel::rowCount qgslayertreemodel.cpp:89
QAbstractItemModel::hasChildren :
QSortFilterProxyModel::hasChildren :
QTreeView::doItemsLayout :
QTreeViewPrivate::updateScrollBars :
QTreeView::updateGeometries :
QMetaObject::activate :
QHeaderView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QWidgetPrivate::setStyle_helper :
QWidgetPrivate::inheritStyle :
QWidgetPrivate::setStyle_helper :
QWidgetPrivate::inheritStyle :
QWidgetPrivate::setStyle_helper :
QWidgetPrivate::inheritStyle :
QWidgetPrivate::setStyle_helper :
QWidgetPrivate::inheritStyle :
QWidgetPrivate::setStyle_helper :
QWidgetPrivate::inheritStyle :
QWidgetPrivate::setStyle_helper :
QWidgetPrivate::inheritStyle :
QWidget::setParent :
QWidget::setParent :
QWidgetAction::releaseWidget :
QToolBar::widgetForAction :
QToolBar::widgetForAction :
QWidget::~QWidget :
QToolBar::`scalar deleting destructor' :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
QgisApp::`vector deleting destructor' :
main main.cpp:1607
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.10.7-A Coru�a
QGIS code revision: 7b4ca4c8d0
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment]
@fernandocostabsb please add detailed steps to replicate. Please edit the title with a meaningful one. Also try with a new QGIS profile.

**Comment by gioman** [comment]
Closing for lack of feedback.
