### ISSUE TITLE
Fix feature attributes not shown in relation form

### ISSUE THREAD

**Issue by mhugent** [qgis/QGIS#38173]
https://github.com/qgis/QGIS/blob/0b9a75c9bf37f06d519d7b0887f5dab240eaf5a3/src/gui/editorwidgets/qgsrelationreferencewidget.cpp#L306

I'm just debugging a case where the relation form is not filled with attributes if 'chain filters' is not checked. However there are no filters at all. The reason seems to be that the lines

QVariant nullValue = QgsApplication::nullRepresentation();
QgsFeatureRequest request = mComboBox->currentFeatureRequest();
mReferencedLayer->getFeatures( request ).nextFeature( mFeature );

are not executed. Moving the if ( mChainFilters ) from l.306  down after these three lines solves this issues. I'm not familiar with the code, do you think it is a good idea to do so or is there an argument against it?

**Comment by m-kuhn** [comment]
`mEmbedForm` should be true when the form is shown. `mFeature` could be fetched conditionally if one of chainFilters or embedForm is set?

**Comment by mhugent** [comment]
Yes, mEmbedForm is true. Fetching if ( mChainFilters || mEmbedForm ) sounds like a good idea

**Comment by mhugent** [comment]
PR created: https://github.com/qgis/QGIS/pull/38251

**Comment by rduivenvoorde** [comment]
@mhugent I think this one can be closed, yes?
