### ISSUE TITLE
QGIS 3.x.x does not start

### ISSUE THREAD

**Issue by jens-ks** [qgis/QGIS#38172]
Dear QGIS-Community,
we have problems getting QGIS 3.x. to work on our pool computers at our university. We had no problems with 2.18.x.
On the other hand 3.12.x, 3.10.x, 3.4.12 LTR do not start because of a dll-error. see attached screenshots

![Unbenannt3](https://user-images.githubusercontent.com/69297486/89509602-ce71fb80-d7cf-11ea-8cbf-e5512cdc8ef4.PNG)
![Unbenannt1](https://user-images.githubusercontent.com/69297486/89509605-cf0a9200-d7cf-11ea-9ec9-a3d4f6b0a620.PNG)
![Unbenannt](https://user-images.githubusercontent.com/69297486/89509608-cfa32880-d7cf-11ea-9126-74e630f2164c.PNG)

Some program, I mean it was Vectorworks, puts in C: \ Windows \ System32 \ dlls, all of which start with QT5 ****. Dll.
We got version 3.4.<8 to work by deleting all dlls with QT5 ****. dll in C: \ Windows \ System32 \. But this has not helped us now.

The computers are set up annually. Windows 10 Enterprise, Autocad 2020, Vectorworks 2020, ArcGis10.6
The distribution works via a hard disk clone with Fogproject.

What information do I have to add so that the matter can be better assessed?

Most bug reports with a similar topic refer to older versions
https://issues.qgis.org/issues/19061
https://gis.stackexchange.com/questions/240159/qgis-2-18-the-program-cant-start-because-qgis-app-dll-is-missing-from-your-com
https://issues.qgis.org/issues/19652

I would be very happy if we can provide the students with the current ltr version every year.  As i am not the system admin, i apologize for any inaccuracies. We are very grateful for any information,
jens

**Comment by roya0045** [comment]
These types of issues are hard to address as QGIS dependent on some system variables to work properly. This feels like it was a network installation, but I may be mistaken.

If this is the case could you test with the exe installer on one system to see if that resolves some issues?

**Comment by jens-ks** [comment]
> These types of issues are hard to address as QGIS dependent on some system variables to work properly. This feels like it was a network installation, but I may be mistaken.
> 
> If this is the case could you test with the exe installer on one system to see if that resolves some issues?

attempting a manual installation led to the same result. what other information about the ecosystem would be helpful to isolate the problem?

**Comment by roya0045** [comment]
Multiple things may cause dependencies conflicts. These can be quite system specific. If you are in a bind and don't need plugins or processing you could try a MXE build as I found them to be more robust but more gimped than a fully installed QGIS.

Maybe official devs have a clue about how to diagnose this, I don't recall seeing one.

**Comment by jens-ks** [comment]
Many thanks for your response. Unfortunately we need the plugins or the full installation. We have the feeling that the problem could be related to the parallel installation of the CAD software mentioned, as the error also occurred on the students' private laptops if they had installed vectorworks, for example.

How does the good professional practice look like in relation to the software handling of the folder C: \ Windows \ System32 \ dlls,?
The problem does not occur with any other software. So my colleagues see the blame on qgis. Every hint where I can start helps me. It is difficult for me to advertise QGIS  if we already fail during the installation. So far it has been a success story

**Comment by roya0045** [comment]
Could you try installing QGIS before vectorworks to see if both are usable in this way?

**Comment by jens-ks** [comment]
we can try that. however, I assume that it will not be an option to do without vectorworks.

**Comment by gioman** [comment]
> Some program, I mean it was Vectorworks, puts in C: \ Windows \ System32 \ dlls, all of which start with QT5

@jens-ks this is the source of your problems I guess, as this software causes you the classic DLL hell. You should ask to the developers of this software is is possible for them to not pollute Windows system folders.

> we can try that. however, I assume that it will not be an option to do without vectorworks.

My guess is that without it QGIS will start, if is the case then it is not really a QGIS issue.

**Comment by jens-ks** [comment]
> > Some program, I mean it was Vectorworks, puts in C: \ Windows \ System32 \ dlls, all of which start with QT5
> 
> @jens-ks this is the source of your problems I guess, as this software causes you the classic DLL hell. You should ask to the developers of this software is is possible for them to not pollute Windows system folders.
> 
> > we can try that. however, I assume that it will not be an option to do without vectorworks.
> 
> My guess is that without it QGIS will start, if is the case then it is not really a QGIS issue.

Thank you for the feedback. I'll ask that we test this. I also understand that then it is not a bug in QGIS. I'm just afraid that the problem sticks to QGIS because it doesn't occur with any other software... at least in the perception of the faculty.

**Comment by roya0045** [comment]
@gioman The maker is IBM, since the issue only occurs with QGIS I would guess that this is caused by a global search of dll, there are some ways to prevent such conflict such as changing search path for the app or statically linking them. I'm not sure what would be the preferable approach but  QGIS has ways to improve the situation in regards to dll. Maybe those option have been explored previously though.

There are generic options here: https://en.wikipedia.org/wiki/DLL_Hell
and specific to qt https://doc.qt.io/qt-5/qt-conf.html

I'm not sure what is done actually or has been tried, this issue seems to pop from time to time.

**Comment by jef-n** [comment]
Another case where https://github.com/qgis/QGIS/issues/26891#issuecomment-495889169 can help diagnose.   Qt should not be in system32.   Does copying the `qgis*-bin.exe` and the corresponding `.env` to the apps/Qt5/bin directory and starting from there help?   But that's only for the Qt case. DLLs located in the same directory are preferred, then system32 and the directories in PATH.  So putting stuff in system32 blocks the lookup in PATH, so whatever is in system32 will block our versions in PATH.  And copying all DLLs and EXEs into one directory would probably cause other conflicts.  Moving qgis into the qt directory would cause the same problem for other DLLs (eg. OpenSSL) on machines where there are other conflicting DLLs in system32.  qgis was already moved from apps/qgis/bin into the bin directory to workaround those cases.

**Comment by jens-ks** [comment]
many thanks. i will discuss this with the system admin and hope we can solve the problem.

**Comment by roya0045** [comment]
@jens-ks Jurgen just added a fix that should help. @jef-n Should the fix be backported just in case?
