### ISSUE TITLE
QgsLogger() does not output anything

### ISSUE THREAD

**Issue by tschmetzer** [qgis/QGIS#38188]
Dear developers,

I am developing some code in the QGIS Python Console. As I cannot set any breakpoints and print cannot be used due to multithreading I tried to use the QgsLogger class as described in the documentation. Unfortunately I couldn't get any output. Also there are no examples or comments regarding this topic in any public GIS related user group.
I even tried to set some environment variables in order to force the logging which didn't work out.

This is the code I use:

```
from qgis.core import QgsLogger

logname= "c:/temp/test.log"

# Set environment variables
os.environ['QGIS_LOG_FILE'] = logname
os.environ['QGIS_DEBUG'] = '3'

print ("Logfile: ",QgsLogger.logFile())
QgsLogger.critical("QgsLoggerTest1")
QgsLogger.debug("QgsLoggerTest2")

QgsLogger.logMessageToFile("Mymessage")
print ("Debuglevel: ",QgsLogger.debugLevel())
```

The output in the console is as follows:

```
Logfile:  
Debuglevel:  0
```

No file was created in c:/temp/test.log nor was the output written to any tab in the log messages window.

I'm running the following system:
QGIS version | 3.14.1-Pi | QGIS code revision | de08d6b71d
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | GroupStats; nominatim; QuickOSM; db_manager; MetaSearch; processing

**Comment by gioman** [comment]
@tschmetzer is this a question or a bug report?

**Comment by tschmetzer** [comment]
Sorry for not being clear about that. It depends on the circumstances. I am neither a logging expert nor a QGIS expert but my expectation would be that - as according to the documentation - at least the debug message is output to the console window. But it definitely is not output. I do not know the root cause of it.

If it's a user's fault then the outcome of this topic should to go to documentation, where I have already opened a separate issue as the documentation is incomplete anyways:
https://github.com/qgis/QGIS-Documentation/issues/5995

But let's first see if this issue is reproduceable.

**Comment by roya0045** [comment]
https://docs.qgis.org/3.10/en/docs/pyqgis_developer_cookbook/communicating.html#logging Does this help?

**Comment by tschmetzer** [comment]
Sorry for not being clear enough. This mentioned documentation is incomplete and missing examples. I was not able to log anything following that documentation. There is a link to https://qgis.org/pyqgis/3.10/core/QgsLogger.html#qgis.core.QgsLogger where the first sentence clearly states "QgsLogger is a class to print debug/warning/error messages to the console" which does not happen.
Maybe this bug is not correctly adressed here in QGIS and should be adressed to pygis?

Can anybody please test this logging functionality in his setup and report if he encounters the same problem or not?

**Comment by m-kuhn** [comment]
QgsLogger will only output if a) QGIS is built in debug mode (i.e. use a nightly build, not a relased version). If I'm not mistaken, on windows you will also need something like DebugView to actually connect to the output.

**Comment by tschmetzer** [comment]
Thank you for sharing that valuable information! In this case the following questions arise:
- Shouldn't this basic information go into the documentation?
- How do other people without development environment produce and evaluate debug scripting output?
With QgsMessageLog.logMessage() I was not able to completely cover all necessary outputs as not every function can be converted by the str() function whereas print() is able to output these contents (e.g. `QgsMessageLog.logMessage(str(feature.geometry()), 'Calculation', level=Qgis.Info)` doesn't output anything at all whereas `print(feature.geometry())` outputs the whole geometry as expected. Yet print() statements extremely slow down the data processing. 
- People developing individual scripts on base of PyGIS do not necessarily participate in the QGIS development process. Are there any meaningful arguments against suggesting and providing the QgsLogger also in the productive/release version of QGIS?

**Comment by m-kuhn** [comment]
> Thank you for sharing that valuable information! In this case the following questions arise:
> 
>     * Shouldn't this basic information go into the documentation?

Absolutely! Adding this would be much appreciated!

> 
>     * How do other people without development environment produce and evaluate debug scripting output?
>       With QgsMessageLog.logMessage() I was not able to completely cover all necessary outputs as not every function can be converted by the str() function whereas print() is able to output these contents (e.g. `QgsMessageLog.logMessage(str(feature.geometry()), 'Calculation', level=Qgis.Info)` doesn't output anything at all whereas `print(feature.geometry())` outputs the whole geometry as expected. Yet print() statements extremely slow down the data processing.

Try `repr(feature.geometry())` to convert to a string

> 
>     * People developing individual scripts on base of PyGIS do not necessarily participate in the QGIS development process. Are there any meaningful arguments against suggesting and providing the QgsLogger also in the productive/release version of QGIS?

QgsLogger is mostly thought for internal logging of the qgis application itself for the development process and adds overhead if enabled. I would suggest to have a look at python specific logging facilities like https://docs.python.org/3/library/logging.html

**Comment by tschmetzer** [comment]
> > Thank you for sharing that valuable information! In this case the following questions arise:
> > ```
> > * Shouldn't this basic information go into the documentation?
> > ```
> 
> Absolutely! Adding this would be much appreciated!

-> has been integrated into https://github.com/qgis/QGIS-Documentation/issues/5995

> > ```
> > * How do other people without development environment produce and evaluate debug scripting output?
> >   With QgsMessageLog.logMessage() I was not able to completely cover all necessary outputs as not every function can be converted by the str() function whereas print() is able to output these contents (e.g. `QgsMessageLog.logMessage(str(feature.geometry()), 'Calculation', level=Qgis.Info)` doesn't output anything at all whereas `print(feature.geometry())` outputs the whole geometry as expected. Yet print() statements extremely slow down the data processing.
> > ```
> 
> Try `repr(feature.geometry())` to convert to a string

Great hint! Works sometimes but not always though.

> > ```
> > * People developing individual scripts on base of PyGIS do not necessarily participate in the QGIS development process. Are there any meaningful arguments against suggesting and providing the QgsLogger also in the productive/release version of QGIS?
> > ```
> 
> QgsLogger is mostly thought for internal logging of the qgis application itself for the development process and adds overhead if enabled. I would suggest to have a look at python specific logging facilities like https://docs.python.org/3/library/logging.html

This is the toughest and most important topic. Unfortunately even explicit filehandler handled logging is output in the QGIS python console (refer to attached file) and is as slow a the print() statement. Also the logging handler persists even after the execution of the code is finished and every log line is output x times the code had been run since QGIS startup.
The output of the debug logging information is something essential and I find it hard to understand why I seem to be the first person to bring this up and why this issue has not been regarded in times before QGIS 3.14.
Any ideas how I can log in Python without having the logger spamming my QGIS console output? Is there any "official solution/information" how this can be achieved?

**Comment by tschmetzer** [comment]
[nur_logger.log](https://github.com/qgis/QGIS/files/5085294/nur_logger.log)

**Comment by m-kuhn** [comment]
Hi @tschmetzer 

Thanks for having taken the time to add more information to the documentation.

The QgsLogger facility is mainly thought for *internal* logging of the *QGIS application* and not targetted at plugin development. I think this is the important fact, that needs to be communicated in the API documentation.

What QGIS offers is tools to send information to the user (QgsMessageBar for high priority things, QgsMessageLog for low priority things).

If you want a log that is really developer oriented, you are much better off focusing on the great tools that python offers out of the box (e.g. the `logging` module). These tools can be used to log to a file without printing to the console. It does not make a lot of sense for QGIS to reinvent the wheel here and creating specific new tools.

**Comment by tschmetzer** [comment]
Dear @m-kuhn 

thank you for taking the time again. I think there is a misunderstanding. With all my last statement I was referring to exactly this native Python `logging ` module. The problem is: It doesn't work proberly within the QGIS console.

**Comment by m-kuhn** [comment]
Oh, sorry, I missed that point!

Have you had a look at this already? https://stackoverflow.com/q/33711475/2319028

**Comment by tschmetzer** [comment]
Yes I tried to use the basicConfig in [nur_logger.zip](https://github.com/qgis/QGIS/files/5085299/nur_logger.zip) and now again with this code: 

```
def logToFile():
    import logging
    logging.basicConfig(filename='c:\temp\example.log',level=logging.DEBUG)
    logging.info("trying to log to file")

logToFile()
```

Unfortunately no file is written when executin this code in the Python console

**Comment by m-kuhn** [comment]
Your code works for me (on linux). So I guess the filename escaping is the problem.
Try `r'c:\...\.'` or `'c:\\...\\.'`

**Comment by tschmetzer** [comment]
Thank you so much Matthias! Though `r'c:\...\.'` does not work `'c:\\...\\.'` does and the output is written **only** to that given filename an **not** on stdout in the QGIS Python console. Also importantly to note that when the _filename_ argument with  `logging.basicConfig(..)` function is altered the whole QGIS application needs to be restarted in order to take effect.

Again I emphasize all this information should go into the GIS and PyGIS documenation. Other than that I would regard the issue to be resolved and the topic can be closed.

**Comment by m-kuhn** [comment]
Glad it helped!

@tschmetzer your participation on these documents is much appreciated. I would see this fit perfectly in a new chapter "Logging" in the PyQGIS Cookbook. This is a community effort on github https://github.com/qgis/QGIS-Documentation/tree/master/docs/pyqgis_developer_cookbook

**Comment by guyanf** [comment]
@tschmetzer Hi guys, I can't using the logging module  in pyqgis.
I want to output the logfile to local file, but there is not any file.

Even I using the code:


def logToFile():
    import logging
    logging.basicConfig(filename='/home/XXX/aa/nohup.out', level=logging.DEBUG)
    logging.info("trying to log to file")


logToFile()


os: ubuntu 21.04  python 3.9 qgis 3.20

Thanks.
