### ISSUE TITLE
Coordinate Transformation Difference between QGIS and Proj

### ISSUE THREAD

**Issue by edips** [qgis/QGIS#38190]
I transformed coordinates on PyQgis and Proj command line and there is 3.8 meters difference between the transformations. I used the same EPSG codes. 
For Proj 6.3:

```
echo 35.53 38.75 | cs2cs +init=epsg:4326 +to +init=epsg:23036
Result: 719891.09	4292257.07
```
For PyQgis 3.10:

```
x, y = 35.53, 38.75
src = QgsCoordinateReferenceSystem(4326)
dest = QgsCoordinateReferenceSystem(23036)
tform = QgsCoordinateTransform(src, dest, QgsProject.instance())
point = tform.transform(QgsPointXY(x, y))
print ("coordinates: ", point)
Result: coordinates:  <QgsPointXY: POINT(719887.53 4292255.79)>
```

I think Proj command line result is more accurate. Is there a way to fix it for QGIS?

**Comment by stev-0** [comment]
Hi @edips you need to specify the full environment you are using as if the proj version is < 6 in your QGIS install (which is might be due to GDAL's dependency) then it is expected that the coordinate tranform would be different. Can you paste the output of Help->About please for your QGIS version?

**Comment by stev-0** [comment]
On the other hand I get the same, and I definitely have GDAL 3.0.4, which I think should have fixed all those issues.

**Comment by edips** [comment]
Hello @stev-0  I use QGIS 3.10 LTS , I installed QGIS from package manager on Ubuntu 20.04. I also installed Proj 6.3 from package manager. 
On the other hand I tested coordinate transformation with QGIS 3.15 c++ API, the coordinate transformation result was the same with QGIS 3.10. I will share the c++ code.

**Comment by nyalldawson** [comment]
You need to check using the exact same co-ordinate operation as qgis is using, or the proj tool may be using a different operation.

**Comment by edips** [comment]
QGIS version | 3.10.4-A Coruña | QGIS code branch | Release QGIS code branch.3
-- | -- | -- | --
Compiled against Qt | 5.12.8 | Running against Qt | 5.12.8
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.2 (Ubuntu 12.2-4) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Pop!_OS 20.04 LTS
Active python plugins | FeatureGridCreator; shapetools; AzimuthMeasurement; Mergin; pluginbuilder3; ThinGreyscale; raster_tracer; latlontools; qfieldsync; quick_map_services; AzimuthDistanceCalculator; LandSurveyCodesImport; QuickOSM; qgsAzimuth; processing; db_manager; MetaSearch

**Comment by edips** [comment]
@nyalldawson I don't know what is the equivalent of cs2cs tool of Proj for PyQGIS. Maybe cs2cs does coordinate transformation and datum transformation at the same time. I will search about it on Proj document.

**Comment by edips** [comment]
I tested QGIS 3.15 API with QgsQuick. The result is the same with QGIS 3.10. QGIS 3.15 uses Proj 6.3.1 and GDAL 3.0.4

```
QString SurveyingUtils::transformer()
{
    QgsCoordinateReferenceSystem source = QgsCoordinateReferenceSystem("EPSG:4326");
    QgsCoordinateReferenceSystem destination = QgsCoordinateReferenceSystem("EPSG:23036");
    if(!(source.isValid()) || !(destination.isValid())){
        qDebug() << "source.isValid()? " << source.isValid() << " destination.isValid()? " << destination.isValid();
        return "";
    }
    QgsPointXY srcPoint = QgsPointXY( 35.53,  38.75);
    QString coords;
    QgsCoordinateTransformContext context;
    QgsQuickMapSettings *mMapSettings = nullptr;
    if ( mMapSettings )
      context = mMapSettings->transformContext();
    QgsCoordinateTransform mTransform(source, destination, context);
    mTransform.transform( srcPoint );
    coords = mTransform.transform( srcPoint ).toString(8);
    return coords;
}
```

**Comment by rouault** [comment]
The issue is that you use a default transformation context that will use the default datum transformation parameters, which are not optimal for your point in Turkey

So with the following,
```
ops = QgsDatumTransform.operations(src,dest)
for op in ops:
	print(op.name, op.proj, op.areaOfUse, op.bounds)
```
you'll see that ops[1] is the one used by PROJ's cs2cs

```
Inverse of ED50 to WGS 84 (30) + UTM zone 36N
+proj=pipeline +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +proj=push +v_3 +step +proj=cart +ellps=WGS84 +step +inv +proj=helmert +x=-84.1 +y=-101.8 +z=-129.7 +rx=0 +ry=0 +rz=0.468 +s=1.05 +convention=position_vector +step +inv +proj=cart +ellps=intl +step +proj=pop +v_3 +step +proj=utm +zone=36 +ellps=intl
Turkey
<QgsRectangle: 25.62000000000000099 34.42000000000000171, 44.82999999999999829 43.45000000000000284>) 
```

And then
```
tformctxt = QgsCoordinateTransformContext()
tformctxt.addCoordinateOperation(src,dest,ops[1].proj)
tform = QgsCoordinateTransform(src, dest, tformctxt)
point = tform.transform(QgsPointXY(x, y))
print(point)
```
displays the same result as cs2cs:
<QgsPointXY: POINT(719891.09165802097413689 4292257.06863298639655113)>

**Comment by edips** [comment]
@rouault Thank you very much for your informative answer. I was trying to figure out the optimal datum transformation (ED500 to WGS 84 (30)) in QGIS. Finally I got it.
