### ISSUE TITLE
Possible Issue with Placing Labels on Features With Duplicate Names

### ISSUE THREAD

**Issue by lagniappist** [qgis/QGIS#38203]
Have repeatedly had an issue with QGIS 3.14.0 (Mac) in manually placing (or automatically placing) labels for features with a duplicate name attribute but different attributes and placed in different locations. this especially happens when the label is moved off a polygon, and a callout is used, but not always.

In this case it's trying to apply labels for specific French lieux-dits (place names), which often are identical in different towns. i.e., "Le Bourg" might be found in multiple villages, as it is in the Beaujolais region, which i'm currently mapping. 

for example, here is a polygon showing "Le Bourg" in the village of Chiroubles:

![Screen Shot 2020-08-08 at 11 48 38 AM](https://user-images.githubusercontent.com/55245689/89714744-f77cc280-d96e-11ea-8294-f8035f2b215c.png)

which is being mapped to another "Le Bourg" in the village of Saint-Julien, about 25 km away (and all the way across the map extent):

![Screen Shot 2020-08-08 at 11 48 53 AM](https://user-images.githubusercontent.com/55245689/89714775-34e15000-d96f-11ea-8b0d-9b97e97c1be6.png)

the result being a callout line that runs all the way down the map (it's too long to even capture the length in one shot):

![Screen Shot 2020-08-08 at 12 05 16 PM](https://user-images.githubusercontent.com/55245689/89714836-88539e00-d96f-11ea-93eb-74131153b00a.png)
![Screen Shot 2020-08-08 at 12 05 08 PM](https://user-images.githubusercontent.com/55245689/89714838-88539e00-d96f-11ea-8d63-7cf411550545.png)

i've tried a number of workarounds, including changing the name field ("nom") used for labels — removing a preposition, etc — and adding an additional field ("nom_actuel") so that i could edit the labels without losing the original dataset. but as soon as there's a duplicate label name, the mismapping of the label recurs.

right now my current (not great) workaround has been to create a duplicate dataset (no symbology, just labels) to house any problem duplicate labels, and have them labeled separately from the 2nd dataset.

a few other things:

(1) the label for one of the mismapped polygons often shows in red (unplaced) in editing, but the incorrect callouts aren't drawn. the mismapping is only visible when rendering in the Layout window, or in the exported map.

![Screen Shot 2020-08-08 at 11 51 19 AM](https://user-images.githubusercontent.com/55245689/89715004-8211f180-d970-11ea-83f4-4de45a7ac576.png)

(2) the polygons being mislabeled are in fact discrete polygons with discrete data. here are the attribute fields for the two in the above example:

![Screen Shot 2020-08-08 at 11 52 01 AM](https://user-images.githubusercontent.com/55245689/89715022-b7b6da80-d970-11ea-8a93-9cac41708919.png)
![Screen Shot 2020-08-08 at 11 51 52 AM](https://user-images.githubusercontent.com/55245689/89715023-b84f7100-d970-11ea-94f1-58147b429529.png)

(3) it is possible this is occurring because of the size of the dataset. in this case, the file with the lieux-dits is 5006 features. i'm working to create a smaller test dataset to see if the problem replicates in that case. that said, only a fraction of them are being mapped: 473, to be precise.

(4) original data source is the French government's official cadastral data, customized with additional fields for my classification needs. original files, and my files, are in geojson format.

HOW TO REPRODUCE:

(1) set two polygons with duplicate label fields in different areas of the map extent, as above.
(2) set a label rule in Attributes — in this case Rule-based labeling — looking for a value in either of two fields — with callouts turned on.

![Screen Shot 2020-08-08 at 12 33 38 PM](https://user-images.githubusercontent.com/55245689/89715383-73790980-d973-11ea-8bc7-828b03f9c6ee.png)

(3) render with a map extent that contains both features. again, see above.

again, will work to create a smaller sample dataset here for possible reproduction

**QGIS and OS versions**

QGIS version | 3.14.0-Pi | QGIS code revision | 9f7028fd23
-- | -- | -- | --
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.28.0 | Running against SQLite | 3.28.0
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS High Sierra (10.13)
Active python plugins | latlontools; mmqgis; processing; db_manager; MetaSearch

**Comment by DelazJ** [comment]
Sorry I didn't read/experiment all your description but be aware that the label tools needs to uniquely identify your features to avoid such problems. And based on the Attribute Table you show, I don't think your data has such a field. Add an integer field, populate it with $id or @rownum and then, when you enable the custom labeling tool, indicate that field as id (I don't remember the right naming) and try again.
Keep us informed.

**Comment by lagniappist** [comment]
@DelazJ thanks so much!  (and honestly i wouldn't wish recreating this data scenario on anyone.)

your point about unique id makes total sense. i've created a duplicate file with the unique id field added, and switched the id field to that.  will report back on whether that resolves the issue.  again, a bit thanks ...

**Comment by roya0045** [comment]
Isn't Commune a unique ID?

**Comment by DelazJ** [comment]
No. Lieux-dits is a subset of communes. And even then, having a unique-values field in the dataset is not enough; afaict you need to specify it when enabling the labels tool.

**Comment by DelazJ** [comment]
Btw, https://docs.qgis.org/3.10/fr/docs/user_manual/working_with_vector/vector_properties.html#labeling

**Comment by lagniappist** [comment]
yep, as @DelazJ notes, there would be unique records with a combination of commune + lieu-dit, but a unique primary key (id) is required to be set prior to labeling in order for the attribute fields to be stored in SQL / labels rendered correctly.

i couldn't easily find a way to port the current x/y data for my existing labels over to a new version of the file with the correct ID. but having set up a new file for potential duplicates and setting the id correctly DID work just fine. so @DelazJ again, a big thanks. (and btw the French version of the instructions are so remarkably clear!)  lesson learned on my end going forward ...

**Comment by DelazJ** [comment]
Great. This report can then be closed.
> and btw the French version of the instructions are so remarkably clear!

Merci. Si ça vous dit d'y participer (soit en traducteur ou relecteur), ce serait pas de refus. Il suffit de créer un compte sous Transifex et rejoindre le groupe dans le projet QGIS-Docs & Website (ou desktop). Plus d'infos à https://qgis.org/fr/site/getinvolved/translate.html#becoming-a-translator et instructions techniques à https://docs.qgis.org/3.10/fr/docs/documentation_guidelines/do_translations.html#translate-a-manual
