### ISSUE TITLE
QuickMapServices will not load

### ISSUE THREAD

**Issue by Rockhawk171** [qgis/QGIS#38208]
**Describe the bug**
QuickMapServices will not load. I have tried on 3.10, 3.12 and now 3.14.

I have removed and re-installed several times plus simply reloaded. I can go back to past projects where web services were used and can create a new project from there.

I'm using a new laptop Predator Helios 300 with Windows 10 Professional

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by roya0045** [comment]
Contact plugin authors. QGIS doesn't own the plugin.
