### ISSUE TITLE
QGIS 3.14 install error in Debian 10 

### ISSUE THREAD

**Issue by k-tkach** [qgis/QGIS#38204]
**Describe the bug**

Hello,
I have a problem with the installation of QGIS 3.14, the problem is that when I install QGIS 3.14 there was not 3.14 version, there was 2.18 version. 
I do everything that apear in the QGIS webpage but I have this error:

_Obj:1 http://dl.google.com/linux/chrome/deb stable InRelease
Des:2 https://qgis.org/debian unstable InRelease [3.691 B]
Err:2 https://qgis.org/debian unstable InRelease
  Las siguientes firmas no fueron válidas: EXPKEYSIG 51F523511C7028C3 QGIS Archive Automatic Signing Key (2019) <qgis-developer@lists.osgeo.org>
Leyendo lista de paquetes... Hecho
W: Error de GPG: https://qgis.org/debian unstable InRelease: Las siguientes firmas no fueron válidas: EXPKEYSIG 51F523511C7028C3 QGIS Archive Automatic Signing Key (2019) <qgis-developer@lists.osgeo.org>
E: El repositorio «https://qgis.org/debian unstable InRelease» no está firmado.
N: No se puede actualizar de un repositorio como este de forma segura y por tanto está deshabilitado por omisión.
N: Vea la página de manual apt-secure(8) para los detalles sobre la creación de repositorios y la configuración de usuarios._

Sorry I speak spanish, and I don't know how to modify the terminal in english.
Later I update the key by:
wget -O - https://qgis.org/downloads/qgis-2019.gpg.key | gpg --import
gpg --fingerprint 51F523511C7028C3

kevin@debian:~$ wget -O - https://qgis.org/downloads/qgis-2019.gpg.key | gpg --import
--2020-08-08 14:31:08--  https://qgis.org/downloads/qgis-2019.gpg.key
Resolviendo qgis.org (qgis.org)... 2606:4700:3035::681b:8adc, 2606:4700:3030::681b:8bdc, 2606:4700:3033::ac43:a792, ...
Conectando con qgis.org (qgis.org)[2606:4700:3035::681b:8adc]:443... conectado.
Petición HTTP enviada, esperando respuesta... 200 OK
Longitud: 1839 (1,8K) [application/pgp-keys]
Grabando a: “STDOUT”

-                           100%[=========================================>]   1,80K  --.-KB/s    en 0s      

2020-08-08 14:31:10 (42,7 MB/s) - escritos a stdout [1839/1839]

gpg: key 51F523511C7028C3: 1 signature not verified due to missing key
gpg: clave 51F523511C7028C3: "QGIS Archive Automatic Signing Key (2019) <qgis-developer@lists.osgeo.org>" not changes
gpg: Cantidad total procesada: 1
gpg:              sin cambios: 1

kevin@debian:~$ gpg --fingerprint 51F523511C7028C3
pub   rsa4096 2019-08-08 [SCEA] [caducó: 2020-08-08]
      8D5A 5B20 3548 E500 4487  DD19 51F5 2351 1C70 28C3
uid        [  caducada ] QGIS Archive Automatic Signing Key (2019) <qgis-developer@lists.osgeo.org>

So I don't know how to continuo. I could install QGIS 2.18 but it is imposible to install QGIS 3.14

**Comment by jef-n** [comment]
key updated
