### ISSUE TITLE
Failure to connect to an instance of OGC API - Features

### ISSUE THREAD

**Issue by ghobona** [qgis/QGIS#38216]
The [QGIS documentation](https://docs.qgis.org/testing/en/docs/user_manual/working_with_ogc/ogc_client_support.html#wfs-and-wfs-t-client) says that one can add an instance of OGC API - Features by providing the landing page through the "Create a New WFS Connection" dialog.

Unfortunately the steps described **do not work** when trying the Reference Implementation of OGC API - Features, which has a landing page at https://services.interactive-instruments.de/t15/daraa

![Screenshot 2020-08-10 at 08 04 14](https://user-images.githubusercontent.com/18121038/89758609-249cb280-dae0-11ea-98c0-ca385458f6b3.png)

Tested against:

QGIS version | 3.10.1-A Coruña
-- | --
Compiled against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2
Compiled against SQLite | 3.28.0
PostgreSQL Client Version | 11.3
QWT Version | 6.1.4
Compiled against PROJ | 5.2.0
OS Version | macOS 10.15
Active python plugins | processing; db_manager; MetaSearch
QGIS code revision | 1e6b1a3eda
Running against Qt | 5.12.3
Running against GDAL/OGR | 2.4.1
Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Running against SQLite | 3.28.0
SpatiaLite Version | 4.3.0a
QScintilla2 Version | 2.11.1
Running against PROJ | Rel. 5.2.0, September 15th, 2018

**Comment by gioman** [comment]
@ghobona works fine on Windows, possibly a macOS only issue?

**Comment by gioman** [comment]
> 3.10.1-A Coruña

@ghobona also you must use 3.14, there is no "OGC API features" option in  the "version" configuration of a WFS connection in QGIS 3.10.

**Comment by ghobona** [comment]
@gioman Ok, thanks. I will try QGIS 3.14.

**Comment by ghobona** [comment]
Works well with QGIS 3.14.16-Pi.
