### ISSUE TITLE
add mssql querylayer

### ISSUE THREAD

**Issue by DocOC86** [qgis/QGIS#38217]
**Feature description.**
It would be nice to add a querylayer with a mssql connection.

**Additional context**
The adding of a querylayer for postgis connection looks like this:

`uri = QgsDataSourceUri()`
`uri.setConnection(host, ort, database, user, password)`
`uri.setDataSource("","(SELECT distinct  ID FROM Mapdata)","THE_GEOM", "","ID")`
`vectorlayer = QgsVectorLayer(uri.uri(), "MAP_LAYER", "mssql")`
`QgsProject.instance().addMapLayer(vectorlayer, True)`

**Comment by alexbruy** [comment]
Duplicates #19301.
