### ISSUE TITLE
Single-band raster morphs to a multi-band raster when saved to the project's GeoPackage

### ISSUE THREAD

**Issue by PavlaGraham** [qgis/QGIS#38227]
Single-band raster morphs to a multi-band raster when saved to the project's GeoPackage

I have two sets of fifty single band rasters. Both sets contain references to the same images.
One set consists of GeoTiff file format files and the second set consists of NetCDF-4 file format files.
In QGIS, I create two sets of virtual layer rasters. The first virtual layer is built with the fifty GeoTiff files. The second virtual layer is built with the fifty NetCDF-4 files. Both virtual layers are single band rasters with the pixel values range corresponding to their source rasters.
I save each virtual layer into the project’s GeoPackage (using the Raw Data option in the Save-as dialogue box).
The virtual layer built with the GeoTiff files transforms during the save-as process to a multi-band RGBA raster.
The virtual layer built with the NetCDF files, when saved to the project’s GeoPackage, retains its single-band format with the original pixel values range.

I observe this same behaviour, a single-band raster file saved to a GeoPackage morphing to a multi-band raster in the following scenario:
I have sixteen single-band tiff files created in QGIS through the Rasterize (vector to raster) process. All pixel values in these sixteen rasters are 1.
I then run the GRASS r.series algorithm with a single aggregate operation, count. I run this process twice: Once I save the aggregate file as a tiff file, then I run the process again, this time saving the output as a NetCDF file.
In both cases the aggregate layers are single-band rasters.
I then save each layer to the project’s GeoPackage (using the Raw Data option in the Save as dialogue box).
The aggregate layer, which started as the GeoTiff file, transforms during the Save-as GeoPackage process to a multiband raster.
The aggregate layer which started as the NetCDF file, retains its single-band format after being saved to the project’s GeoPackage.

QGIS 3.14 installed on Windows 10 64-bit OS

**Additional context**

**Comment by gioman** [comment]
> I save each virtual layer into the project’s GeoPackage (using the Raw Data option in the Save-as dialogue box).
> The virtual layer built with the GeoTiff files transforms during the save-as process to a multi-band RGBA raster.

@PavlaGraham I cannot replicate, can you provide a sample project+data?

**Comment by PavlaGraham** [comment]
Further to my initial post:
I have re-created part of the first example, creating a virtual layer from 50 tiff files and then saving the virtual layer to the project’s GeoPackage. – I enclose the project and the source dataset:

[LandCover2015MawasCentralKalimantan.zip](https://github.com/qgis/QGIS/files/5056876/LandCover2015MawasCentralKalimantan.zip)


- the group ‘LandCover2015TiffFiles’ contains links to the fifty raters downloaded from https://lpdaacsvc.cr.usgs.gov/appeears/;
- the fifty rasters are in a folder ‘GeoTiffFilesProductMCD12Q1BOSFMawasYr2015’;
- I create virtual raster from these fifty files, ‘LandCover2015TiffFilesVirtualLayer’; the layer is single-band rater with pixel values in the same range as the original tiff files;
- I then save the ‘LandCover2015TiffFilesVirtualLayer’ to the project’s GeoPackage, (using the Save As, Raw Data option, dialogue box), saving it as ‘LandCover2015TiffFilesVirtualLayerGPKG’; this layer becomes a multiband RGBA raster;

Actually, I went a step further than my initial post: I also saved the downloaded fifty rasters to the project’s GeoPackage; these individual single-band layers also became multiband rasters when saved to the GeoPackage!
The virtual layer, built with these packaged fifty rasters, ‘LandCover2015VirtualLayerExTiffFilesGPKG’, is also a multi-band raster.

**Comment by gioman** [comment]
@PavlaGraham probably there is no bug here (not 100% sure anyway).

GDAL translate returns exactly the same 4 band result

`gdal_translate -of GPKG -b 1 LandCover2015TiffFilesVirtualLayer.vrt test.gpkg`

while the same operation to geotiff returns a 1 band raster

`gdal_translate -of gtiff LandCover2015TiffFilesVirtualLayer.vrt test.tif`

Moreover here
https://gdal.org/drivers/raster/gpkg.html

we can read

"By default, the driver will expose a GeoPackage dataset as a four band (Red,Green, Blue,Alpha) dataset, which gives the maximum compatibility with the various encodings of tiles that can be stored."

which is compatible with the observation in QGIS.

**Comment by nyalldawson** [comment]
Let's close this?
