### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by jclaborde** [qgis/QGIS#38239]
Crash ID: 5552e451b4cb8edf15f4dd9afa13384a9f83fd15

Stack Trace

osgeo::proj::datum::Datum::conventionalRS :
osgeo::proj::datum::Datum::conventionalRS :
osgeo::proj::datum::Datum::conventionalRS :
OGRSpatialReference::exportToWkt :
QgsOgrUtils::OGRSpatialReferenceToWkt qgsogrutils.cpp:739
QgsOgrUtils::OGRSpatialReferenceToCrs qgsogrutils.cpp:746
QgsOgrProvider::crs qgsogrprovider.cpp:3716
QgsVectorLayer::setCoordinateSystem qgsvectorlayer.cpp:3269
QgsVectorLayer::setDataSource qgsvectorlayer.cpp:1609
QgsVectorLayer::QgsVectorLayer qgsvectorlayer.cpp:177
QgisApp::addVectorLayerPrivate qgisapp.cpp:11429
QgisApp::handleDropUriList qgisapp.cpp:1869
::operator() qgisapp.cpp:1789
QtPrivate::QFunctorSlotObject,0,QtPrivate::List,void>::impl qobjectdefs_impl.h:422
QMetaObject::activate :
QTimer::timerEvent :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32Private::sendTimerEvent :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1606
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.10.8-A Coru�a
QGIS code revision: d09a4f2388
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**How to Reproduce**

Select zip, drag and drop shp files from Explorer to layers

**QGIS and OS versions**
The import of this project run normally in version 3.4......3.6.....3.8......... but fails on latest versions 3.10....3.14

**Comment by gioman** [comment]
> Select zip, drag and drop shp files from Explorer to layers

@jclaborde cannot replicate, please try with a new QGIS profile.

**Comment by roya0045** [comment]
@gioman the error is probably specific to gis dataset, @jclaborde can you import the data when unzipped?

**Comment by gioman** [comment]
Closing for lack of feedback.
