### ISSUE TITLE
qgis-server with docker behind reverse proxy

### ISSUE THREAD

**Issue by svamet** [qgis/QGIS#38236]
**Describe the bug**
get capabilities displays host and port from docker container even if you set server_port in apache.conf

so is there a way to specify the host, port, and protocol of the front facing reverse proxy in a QGIS Server option that QGIS Server generates the appropriate XML?

**Comment by gioman** [comment]
@svamet Hi, is this a question or a bug report?

**Comment by sbrunner** [comment]
It looks to be booth:
- bug report: QGIS should take care on headers setted by the reverse proxy (see e.-g. https://tools.ietf.org/html/rfc7239)
- question: The workaround is to set the `Advertised URL` in all the service, in Project/Settings/QGIS server

**Comment by svamet** [comment]
thanks for your answers and yes, it is both. 

- bug: do i get this right that this is a bug at the moment?
- question: this works, but i think thats not a solution for a dev/prod environment. Or do i miss something?

**Comment by NyakudyaA** [comment]
Please specify what docker containers you are using. An example of the docker-compose and the reverse proxy config.

**Comment by FrediWeber** [comment]
We use a custom Docker image. The container runs in Kubernetes and we use
Istio (Envoy) as a service mesh / reverse proxy. We already tried the
X-Forwarded-Proto, X-Forwarded-Port etc.
The container runs on port 8080 (non-root).
We looked at the code and it looks like the Env values for specifying the
port, proto etc. are not respected if a port etc. are already present in
the URL scheme. (e.g. the reverse proxy calls the URL
„http://qgis-server:8080“ but the front-facing server listens on
„https://qgis.example.org:443“)

The workaround with the QGIS project file is not really satisfying as we‘re
trying to use the same projects in different environments with different
user-facing URLs.

Maybe there would be a quick fix if the defined variables / envs would take
precedence over the request URL scheme but I don‘t know if there is a
reason that it was programmed this way.

mazano <notifications@github.com> schrieb am Di. 11. Aug. 2020 um 18:28:

**Comment by elpaso** [comment]
Hi, 
I think you have two options here if you don't want to set the `Advertised URL` in the project:

1. Pass to QGIS Server the front-facing full URI in `REQUEST_URI` (Nginx does not part the scheme/host/port by default)
2. strip scheme, domain and port from `REQUEST_URI` so that it contains only the path and query string (like Nginx does by default) and set `SERVER_PORT`, `SERVER_NAME` and `HTTPS` 

Most of the times you need to rewrite the URI anyway in order to not expose `?MAP=/full_path_to_qgs_project.qgs`.

**Comment by FrediWeber** [comment]
Thank you very much for this hint. We'll likely be able to use this workaround. We use Apache and we were not really able to override the `REQUEST_URI` there but I don't see a reason to not switch to nginx.
Nevertheless I think that `SERVER_PORT` etc. should take precedence over the URL scheme https://github.com/qgis/QGIS/blob/0b3ec39050528cfe85a255a366bdb8f2bd6f04b3/src/server/qgsfcgiserverrequest.cpp#L48.
IMO it is expected behavior that if a server admin explicitly sets these values they should be considered before the URL scheme.

**Comment by FrediWeber** [comment]
Even though we unset `REQUEST_URI`, `SCRIPT_NAME` and `PORT` and set the `SERVER_NAME` to the correctly set `$host` variable it doesn't seem to respect them. The only variable that is respected with Apache and nginx is `HTTPS`.
relevant nginx config:

```
server {
  listen 8080 default_server;
  location / {
    include fastcgi_params;
    fastcgi_param HTTPS $qgis_ssl;
    fastcgi_param SERVER_NAME $host;
    fastcgi_param SERVER_PORT "";
    fastcgi_param REQUEST_URI "";
    fastcgi_param SCRIPT_NAME "";
    fastcgi_pass unix:/var/qgis/qgisserver.socket;
  }
}
```

Is somebody able to run QGIS Server on a non standard port behind a reverse proxy on a standard port?

**Comment by elpaso** [comment]
See https://www.digitalocean.com/community/tutorials/understanding-and-implementing-fastcgi-proxying-in-nginx

**Comment by elpaso** [comment]
Tip: move the include at the end of the block.

**Comment by juusechec** [comment]
This is possible for apache?

**Comment by juusechec** [comment]
For NGINX that works for me:
```
       location /qgisserver {
                gzip           off;
                #include        fastcgi_params;
                fastcgi_param QGIS_DEBUG              1;
                fastcgi_param QGIS_SERVER_LOG_FILE    /var/log/qgis/qgisserver.log;
                fastcgi_param QGIS_SERVER_LOG_LEVEL   0;
                fastcgi_param QGIS_AUTH_DB_DIR_PATH "/home/qgis/qgisserverdb/";
                fastcgi_param QGIS_AUTH_PASSWORD_FILE "/home/qgis/qgisserverdb/qgis-auth.db";
                fastcgi_param DISPLAY ":99";
                
                fastcgi_param  QUERY_STRING       $query_string;
                fastcgi_param  REQUEST_METHOD     $request_method;
                fastcgi_param  CONTENT_TYPE       $content_type;
                fastcgi_param  CONTENT_LENGTH     $content_length;

                fastcgi_param  SCRIPT_NAME        $fastcgi_script_name;
                fastcgi_param  REQUEST_URI        $request_uri;
                fastcgi_param  REQUEST_URI        $query_string;
                fastcgi_param  DOCUMENT_URI       $document_uri;
                fastcgi_param  DOCUMENT_ROOT      $document_root;
                fastcgi_param  SERVER_PROTOCOL    $server_protocol;
                fastcgi_param  REQUEST_SCHEME     $scheme;

                fastcgi_param  GATEWAY_INTERFACE  CGI/1.1;
                fastcgi_param  SERVER_SOFTWARE    nginx/$nginx_version;

                fastcgi_param  REMOTE_ADDR        $remote_addr;
                fastcgi_param  REMOTE_PORT        $remote_port;
                fastcgi_param  SERVER_ADDR        $server_addr;

                # variables for reverse proxy
                # you can debug any value with add-header
                # add_header X-SERVER_NAME "$SERVER_NAME";
                fastcgi_param  HTTPS              "on";
                fastcgi_param  SERVER_PORT        "8000";
                fastcgi_param  SERVER_NAME        "reverse-proxy.com";

                # PHP only, required if PHP was built with --enable-force-cgi-redirect
                fastcgi_param  REDIRECT_STATUS    200;

                fastcgi_pass   unix:/var/run/qgisserver.socket;
        }
```

**Comment by svamet** [comment]
> e include at the end of the block.

This solved the problem. Sorry for the late reply.
