### ISSUE TITLE
Qgis-Server GetMap request returns a blank image

### ISSUE THREAD

**Issue by juliermegeotube** [qgis/QGIS#38238]
I am running Qgis-Server@3.14 and Qgis-Desktop@3.10. 
Following the directions in here https://docs.qgis.org/3.4/en/docs/training_manual/qgis_server/wms.html, I am getting a blank image for all GetMap request. Any insight in this matter will be very appreciated.
![qgis_server-getMap-blank_image](https://user-images.githubusercontent.com/14243472/89941149-007cc680-dbf1-11ea-9f9a-24025a12b7c3.png)

**Comment by gioman** [comment]
> Any insight in this matter will be very appreciated.

@juliermegeotube is this a question or a bug report?

**Comment by juliermegeotube** [comment]
@gioman Sorry for not setting the labels, but I suggest as a feedback and question.

**Comment by gioman** [comment]
> CRS=EPSG%3A4326&
> BBOX=432786,4372992,3358959,7513746&

@juliermegeotube this is not tight, your CRS is 4326, degrees, while your BBOX is clearly in meters.

**Comment by gioman** [comment]
Closing for lack of feedback.
