### ISSUE TITLE
QGIS crash when opening project file saved in previous stable version

### ISSUE THREAD

**Issue by jatinpandya** [qgis/QGIS#38248]
## User Feedback

Opening a project file saved by a previous stable version. Some of the datasources referenced in the qgs file were missing and ignored while loading.

## Report Details

**Crash ID**: [90bbd7fc7fc5498158eeb7f6acd97b31d4e13dbe](https://github.com/qgis/QGIS/search?q=90bbd7fc7fc5498158eeb7f6acd97b31d4e13dbe&type=Issues)

**Stack Trace**
<pre>
QgsPointDisplacementRenderer::drawGrid qgspointdisplacementrenderer.cpp:432
QgsPointDisplacementRenderer::drawGroup qgspointdisplacementrenderer.cpp:107
QgsPointDistanceRenderer::drawGroup qgspointdistancerenderer.cpp:156
QgsPointDistanceRenderer::stopRender qgspointdistancerenderer.cpp:343
QgsPointDisplacementRenderer::stopRender qgspointdisplacementrenderer.cpp:145
QgsVectorLayerRenderer::drawRenderer qgsvectorlayerrenderer.cpp:368
QgsVectorLayerRenderer::render qgsvectorlayerrenderer.cpp:284
QgsMapRendererParallelJob::renderLayerStatic qgsmaprendererparalleljob.cpp:265
QtConcurrent::MapKernel<QList<LayerRenderJob>::iterator,QtConcurrent::FunctionWrapper1<void,LayerRenderJob & __ptr64> >::runIteration qtconcurrentmapkernel.h:69
QtConcurrent::MapKernel<QList<LayerRenderJob>::iterator,QtConcurrent::FunctionWrapper1<void,LayerRenderJob & __ptr64> >::runIterations qtconcurrentmapkernel.h:78
QtConcurrent::IterateKernel<QList<QgsImageOperation::ImageBlock>::iterator,void>::forThreadFunction qtconcurrentiteratekernel.h:256
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.8-A Coru�a
QGIS code revision: d09a4f2388
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by roya0045** [comment]
A sample project might be needed to reproduce and debug.

**Comment by gioman** [comment]
Closing for lack of feedback.
