### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by cmundy** [qgis/QGIS#38249]
QGIS working normally yesterday. Installed Mergin plugin without problems, and uploaded project to Mergin. Next attempt to start QGIS and every attempt since results in crash.

Crash ID: a66f6f108c60995de376243f855ab1567c6d293d

Stack Trace

QEventTransitionPrivate::unregister :
QAbstractItemModel::persistentIndexList :
QAbstractItemModelPrivate::rowsInserted :
QAbstractItemModel::endInsertRows :
QMetaObject::activate :
QgsDataItem::populate qgsdataitem.cpp:338
QgsDataItem::childrenCreated qgsdataitem.cpp:313
QMetaObject::activate :
QFutureWatcherBase::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QgsAuthManager::passwordHelperRead qgsauthmanager.cpp:3091
QgsAuthManager::masterPasswordInput qgsauthmanager.cpp:3227
QgsAuthManager::loadAuthenticationConfig qgsauthmanager.cpp:1211
meth_QgsAuthManager_loadAuthenticationConfig sip_corepart2.cpp:273824
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyTuple_New :
PyObject_FastCallKeywords :
PyObject_FastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_sip :
sipVH__core_57 sip_corepart0.cpp:19862
sipQgsDataItemProvider::createDataItem sip_corepart3.cpp:177320
QgsBrowserModel::addRootItems qgsbrowsermodel.cpp:140
QgsBrowserModel::initialize qgsbrowsermodel.cpp:193
QgsBrowserDockWidget::showEvent qgsbrowserdockwidget.cpp:127
QWidget::event :
QDockWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QWidgetPrivate::show_helper :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidget::setVisible :
QgisApp::QgisApp qgisapp.cpp:1369
main main.cpp:1352
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.10.8-A Coru�a
QGIS code revision: d09a4f2388
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by roya0045** [comment]
Mergin plugin issue not QGIS. you probably ticked the "remember credentials", never tick remember credentials. It has been fixed in newer qgis version I think. @gioman I guess this can be closed when you have the time to.

**Comment by cmundy** [comment]
Thanks for responding so quickly. I have uninstalled QGIS, stripped all QGIS entries from the Registry and re-installed. Same problem. I found the Mergin plugin in users/appdata/...  and deleted that - QGIS loads now. Thanks for the help.
