### ISSUE TITLE
[expressions] named parameters and geometric predicates

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#38246]
In functions that have two geometries as arguments (see functions: intersect, contains, touches etc ...) the named parameters do not work, see attached screenshots:

here it works `geometry_a` and not `geometry1`
![image](https://user-images.githubusercontent.com/7631137/90048851-55ddd400-dcd4-11ea-8fc1-6f65a36b0f73.png)

it doesn't work here
![image](https://user-images.githubusercontent.com/7631137/90049028-8e7dad80-dcd4-11ea-93dd-c990f6b6736a.png)

no distinction between topics:
![image](https://user-images.githubusercontent.com/7631137/90049050-95a4bb80-dcd4-11ea-893a-44e1978fce3e.png)

![image](https://user-images.githubusercontent.com/7631137/90049075-9b020600-dcd4-11ea-891f-44263faea313.png)

![image](https://user-images.githubusercontent.com/7631137/90049091-a1907d80-dcd4-11ea-8521-aea8567192c5.png)

arguments should be homogenized, because there are:
1. `geometry`
2. `geometry1`
3. `geometry a`

**Comment by pigreco** [comment]
here `geometry1` works
![image](https://user-images.githubusercontent.com/7631137/90050326-524b4c80-dcd6-11ea-988b-20297e36f3fd.png)

**Comment by roya0045** [comment]
I agree that the expressions with two geometries need to be improved. For Within I never know which geometry goes where until I reversed them.
