### ISSUE TITLE
Unable to build 3.15 on CentOS 7 using GCC 9.2.0

### ISSUE THREAD

**Issue by S0sh0rt** [qgis/QGIS#38242]
I am unable to build 3.15 on CentOS 7 using GCC 9.2.0.
I use -D_GLIBCXX_USE_CXX11_ABI=0 to avoid many other errors relating to CXX11.

Is there something missing from the makefiles for qgsbasicnumericformat.cpp and qgsfractionnumericformat.cpp?

[ 50%] Linking CXX shared library ../../output/lib/libqgis_core.so
CMakeFiles/qgis_core.dir/numericformats/qgsbasicnumericformat.cpp.o: In function `QgsBasicNumericFormat::formatDouble(double, QgsNumericFormatContext const&) const':
qgsbasicnumericformat.cpp:(.text+0x19d): undefined reference to `std::basic_stringstream<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::basic_stringstream()'
CMakeFiles/qgis_core.dir/numericformats/qgsfractionnumericformat.cpp.o: In function `QgsFractionNumericFormat::formatDouble(double, QgsNumericFormatContext const&) const':
qgsfractionnumericformat.cpp:(.text+0x1b6): undefined reference to `std::basic_stringstream<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::basic_stringstream()'
collect2: error: ld returned 1 exit status
make[2]: *** [output/lib/libqgis_core.so.3.15.0] Error 1
make[1]: *** [src/core/CMakeFiles/qgis_core.dir/all] Error 2
make: *** [all] Error 2

**Comment by gioman** [comment]
@S0sh0rt you should ask first on the developers mailing list rather than filing immediately a bug ticket.

**Comment by S0sh0rt** [comment]
I attempted to email the developer group, but bounced because I am not a member. I attempted to join but never received any confirmation.  I also emailed Nyall without response.
Please pardon my reopening of this developer/build issue.  I'd like to complete this build and deploy to my linux users.

**Comment by gioman** [comment]
>  but bounced because I am not a member

@S0sh0rt you must subscribe the list, it is open.

**Comment by S0sh0rt** [comment]
Yes, I did attempt to subscribe, but nothing.

**Comment by pblottiere** [comment]
Hi @S0sh0rt,

I'm willing to take a look but I'm not familiar with CentOS and I'd like to reproduce your compilation environment. First, how did you install GCC 9 on your Cent OS 7?

**Comment by gioman** [comment]
Closing for lack of feedback.
