### ISSUE TITLE
qgis_process problems: Scripts and Models folders, GRASS launch tool, GeoPackage output parameter

### ISSUE THREAD

**Issue by Dan-Eli** [qgis/QGIS#38247]
I have been testing the qgis_process since the correction in QGIS 3.14.1 it's working well including Models and Python Processing Scripts.  Great addition.

The following tests were done on Windows using QGIS 3.14.1

Below are 3 issues concerning qgis_process

**Issue#1**
In interactive mode, it is possible to add folders where QGIS will look for custumized (home made) Models and Processing Scripts by clicking in the menu _Settings > Options... > Processing_ and adding the required folders in Models and Scripts sections.  These options are important for an organization in order to share Models and Processing Scrits between employee.

The new qgis_process tool is not looking into these folders so it thinks that the Models or Scripts are missing.  I had to move the Models and Scripts into the _Default User Profile_ directories in order for qgis_process to execute them. It would be important that QGIS interactive mode and QGIS batch mode have the same behaviour regarding where Models and Scripts are located and loaded

**Issue#2**
When we type the command` C:\Program Files\QGIS 3.14\bin>qgis_process-qgis.bat list` it lists all _Available Algorithms_ even the one in the GRASS library.

But when I tried to run GRASS library tools I had the following error message: 

`GRASS GIS 7 folder is not configured. Please configure it before running GRASS GIS 7 algorithms.ERROR:  GRASS GIS 7 folder is not configured. Please configure it before running GRASS GIS 7 algorithms.`

I had to create a new qgis_process-qgis.bat 

```
@echo off
call "%~dp0\o4w_env.bat"
call "%OSGEO4W_ROOT%\apps\grass\grass78\etc\env.bat"
call qt5_env.bat
call py3_env.bat
@echo off
path %
OSGEO4W_ROOT%\apps\qgis\bin;%OSGEO4W_ROOT%\apps\grass\grass78\lib;%OSGEO4W_ROOT%\apps\grass\grass78\bin;%PATH%
set QGIS_PREFIX_PATH=%OSGEO4W_ROOT:\=/%/apps/qgis
set GDAL_FILENAME_IS_UTF8=YES
rem Set VSI cache to be used as buffer, see #6448
set VSI_CACHE=TRUE
set VSI_CACHE_SIZE=1000000
set QT_PLUGIN_PATH=%OSGEO4W_ROOT%\apps\qgis\qtplugins;%OSGEO4W_ROOT%\apps\qt5\plugins
set PYTHONPATH=%OSGEO4W_ROOT%\apps\qgis\python;%PYTHONPATH%
"%OSGEO4W_ROOT%\apps\qgis\bin\qgis_process.exe" %*
```

Line 3 is new and line 8 is modified

In interactive mode there are 2 files (`qgis.bat` and `qgis-grass7.bat`) that can be used to launch QGIS depending if we want to launch QGIS with or without GRASS. In batch mode with qgis_process it should be the same 2 files: `qgis_process-qgis.bat` and `qgis_process-qgis-grass7.bat`.

**Issue#3**
Most of the individual algorithms have an Input and Output parameters
For GeoPackage input vector files we can use  `--INPUT="C:/Map.gpkg|layername=Road_in`" to access the Road layer in the file C:/Map.gpkg
For GeoPackage output vector file we cannot use `--OUTPUT="C:/Map.gpkg|layername=Road_out` we must use `--OUTPUT="C:/Map.gpkg"` without the capacity to specify the layer name.
It would help if the behaviour of the input and output parameters were the same.

**Comment by DelazJ** [comment]
@Dan-Eli These are different issues to handle so it's better (strongly advised) you split the report: one issue one report. Thanks

**Comment by Dan-Eli** [comment]
OK, I will post 3 new issues and close that one

**Comment by Dan-Eli** [comment]
this issue as been splitted into the following 3 issues:
https://github.com/qgis/QGIS/issues/38272
https://github.com/qgis/QGIS/issues/38271
https://github.com/qgis/QGIS/issues/38269

I'm closing this one...
