### ISSUE TITLE
QGIS3 all versions: extremely slow in Attribute Table Filtering after Windows Update

### ISSUE THREAD

**Issue by junkchandu** [qgis/QGIS#38244]
**Describe the bug**
I routinely use shapefiles containing 10,000 to 40,000 polygons having 10-40 attributes. Opening the attribute table and filtering (simple or advanced) is something I constantly do. Till recently, even with 40,000 rows and 40 columns, filtering was very fast. Now, after a Windows Update, QGIS 3 (all versions) seem to take an enormous amount of time for a simple task.
E.g., shapefile with 11,000 rows and 34 columns (fields): filtering for "GISarea" > "official area" took 30 seconds. In a larger file (40k rows) similar operations take 3 minutes. Note: once an operation is completed, other filter operations are fast. Till one closes the attribute table. After that, one has to go through the lengthy wait again.

The same operation used to take me a few seconds before Windows updated in May 2020. Even today, on a colleague's computer running older versions of windows (but same QGIS 3.10.6 LTR version), it takes only a few seconds. Alternatively, on my computer, QGIS 2.18.3 takes only 2-3 seconds. So it is some combination of QGIS3 and the latest Windows update that is 

**How to Reproduce**

<!-- Steps, sample datasets and qgis project file to reproduce the behavior. Screencasts or screenshots welcome

1. Go to polygon layer in Layer Panel, Right click and choose Open Attribute Table'
2. Click on 'Show All Features' and choose 'Advanced Filter'. In filter expression window, enter some simple filter, such as Value of some variable greater than some threshold or equal to some specific value. Click 'Ok'
3. See how long the filter takes to complete.

**Sample dataset**
[Village layer.zip](https://github.com/qgis/QGIS/files/5062843/Village.layer.zip)

**QGIS and OS versions**
OS Version: **Window 10, build 10.18362** 
(My laptop is Lenovo X1 Carbon. But the problem has been replicated on a new Dell Inspiron 3593 system with same Window 10 build number)

QGIS version
3.10.6-A Coruña
QGIS code revision
ec80021f49
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
SpreadsheetLayers; 
db_manager; 
MetaSearch; 
processing

**Additional context**

I have tested this problem with colleagues: New laptop+ same Windows build+ QGIS 3.10.6 = problem occurs. But with QGIS 2.18.3 on the same new laptop, it does not occur. Older Windows version: I am not able to rollback my windows version, hence cannot test on my laptop, but with colleagues who have windows 7 or older Windows 10 versions, the problem does not occur even with QGIS 3.10.6.

**Comment by gioman** [comment]
@junkchandu same as https://github.com/qgis/QGIS/issues/38018 ?

**Comment by gioman** [comment]
Closing as duplicate.
