### ISSUE TITLE
The linestringZ SHP are systematically loaded as multilinestringZ.

### ISSUE THREAD

**Issue by FERRATON** [qgis/QGIS#38252]
see attached file of single lines in 2.5D.
With QGIS 3.4 features are identified as linestring25D
with QGIS 3.10 features are identified as MultilinestringZ
If we export in gpkg, features are identified as linestringZ.
[BDTopage_2020_Troncons_bac_a_sable.zip](https://github.com/qgis/QGIS/files/5067846/BDTopage_2020_Troncons_bac_a_sable.zip)

**Comment by nyalldawson** [comment]
This is by design -- if you search the tracker you'll find plenty of other tickets explaining the rationale
