### ISSUE TITLE
qgis_process does not manage user defined Script and Models folders

### ISSUE THREAD

**Issue by Dan-Eli** [qgis/QGIS#38269]
I have been testing the qgis_process since the correction in QGIS 3.14.1 it's working well including Models and Python Processing Scripts. Great addition.

I notices the following problem using qgis_process

In interactive mode, it is possible to add folders where QGIS will look for custumized (home made) Models and Processing Scripts by clicking in the menu Settings > Options... > Processing and adding the required folders in Models and Scripts sections. These options are important for an organization in order to share Models and Processing Scrits between employee.

The new qgis_process tool is not looking into these folders so it thinks that the Models or Scripts are missing. I had to move the Models and Scripts into the Default User Profile directories in order for qgis_process to execute them. It would be important that QGIS interactive mode and QGIS batch mode have the same behaviour regarding where Models and Scripts are located and loaded

The tests were done on Windows using QGIS 3.14.1

**Comment by alexbruy** [comment]
Works fine on master.

**Comment by Dan-Eli** [comment]
I retested today and you are right it's working
I'm sorry, I,ll be more carefull next time before submitting a QGIS issue
