### ISSUE TITLE
When creating a Bookmark the Name value should be pre-selected for easy replacement

### ISSUE THREAD

**Issue by spilth** [qgis/QGIS#38265]
**Feature description.**

As an avid QGIS bookmarker
I want the `Name` value of a New Bookmark to be pre-selected
So that I can start typing the name of my new bookmark immediately

**Additional context**

I often want to quickly make a Bookmark using the shortcut key for it. Since I rarely want the bookmark's name to be `New bookmark`, I erase what is already there and type a new name. It would be faster if the text was pre-selected so I could just start typing

<img width="600" alt="Screen Shot 2020-08-13 at 9 22 32 AM" src="https://user-images.githubusercontent.com/13157/90146610-dccb9480-dd46-11ea-8743-00e01c3e708f.png">

**Comment by ismailsunni** [comment]
Already implemented on QGIS 3.22 and QGIS master. Perhaps we can close this one.
