### ISSUE TITLE
QGis can not overwrite shapefile closed by pyqgis

### ISSUE THREAD

**Issue by pvandegeer** [qgis/QGIS#38276]
When creating a shapefile through a plugin or otherwise and subsequently closing the shapefile and trying to overwrite it, it fails. However, closing the file 'by hand': right click it -> remove layer, allows it to be overwritten.

Possibly related or the same issues are described and linked to in the question and comments here:
https://gis.stackexchange.com/questions/328232/deleting-shapefile-and-related-extension-files-from-folder-when-not-in-use

**How to Reproduce**
Run this code in Python console twice:
```
QgsProject.instance().removeAllMapLayers()
vl = QgsVectorLayer("Point", "temporary_points", "memory")
pr = vl.dataProvider()
vl.startEditing()
pr.addAttributes( [ QgsField("name", QVariant.String)] )
vl.commitChanges()
transform_context = QgsCoordinateTransformContext()
save_options = QgsVectorFileWriter.SaveVectorOptions()
save_options.driverName = "ESRI Shapefile"
save_options.overrideGeometryType = QgsWkbTypes.Point
save_options.fileEncoding = "System"
save_options.actionOnExistingFile = QgsVectorFileWriter.CreateOrOverwriteFile
QgsVectorFileWriter.writeAsVectorFormatV2(vl, r'c:\temp\test.shp', transform_context, save_options)
shp_layer = iface.addVectorLayer(r'c:\temp\test.shp', "" , "ogr")    

```
Run it again and it succeeds. Again: it fails. Etc..

Removing layers with QgsProject.instance().clear() or del results in the same issue.

**QGIS and OS versions**
QGIS-versie
3.14.1-Pi
QGIS code revisie
de08d6b71d
Gecompileerd tegen Qt
5.11.2
Gebruikt nu Qt
5.11.2
Gecompileerd tegen GDAL/OGR
3.0.4
Gebruikt nu GDAL/OGR
3.0.4
Gecompileerd tegen GEOS
3.8.1-CAPI-1.13.3
Gebruikt nu GEOS
3.8.1-CAPI-1.13.3
Gecompileerd tegen SQLite
3.29.0
Uitgevoerd met SQLite
3.29.0
PostgreSQL Client Versie
11.5
SpatiaLite-versie
4.3.0
QWT versie
6.1.3
QScintilla2 Versie
2.10.8
Gecompileerd tegen PROJ
6.3.2
Gebruikt nu PROJ
Rel. 6.3.2, May 1st, 2020
Versie OS
Windows 10 (10.0)
Actieve plug-ins van Python
FeatureGridCreator; 
GeometryShapes; 
pdokservicesplugin; 
pluginbuilder3; 
plugin_reloader; 
RuimtelijkePlannen; 
db_manager; 
MetaSearch; 
processing; 
coring_tools; 
layer_writer

**Additional context**
I'm trying to write a plugin that creates a layer based on some db fields. 
After tuning some settings it should be able to recreate it and overwrite the file.

**Comment by gioman** [comment]
@pvandegeer you should ask in the developers mailing list if you are doing it right.

**Comment by jfbourdon** [comment]
There is several threads on SE about this like [here](https://gis.stackexchange.com/questions/77218/releasing-pyqgis-file-locks) and [here](https://gis.stackexchange.com/questions/353336/unload-qgsvectorlayer-from-python-script/371017#371017) and  [I asked for a similar issue on the dev list](https://lists.osgeo.org/pipermail/qgis-developer/2020-August/061999.html) not long ago. In your case, you just need to directly remove `shp_layer` from the map by adding  `QgsProject.instance().removeMapLayer(shp_layer.id())` at the end of your script.

That being said, I also had some weird problems lately with `writeAsVectorFormatV2()` that were not present with the old `writeAsVectorFormat()`.

**Comment by pvandegeer** [comment]
That works. But it doesn't make any sense. I want to show the maplayer and only remove and overwrite it on the next (user initiated run). 

`removeAllMapLayers `(or `removeMapLayer `or `del `for that matter) should release the files and allow them to be overwritten of deleted.
