### ISSUE TITLE
QGIS Post Install fail

### ISSUE THREAD

**Issue by arojas314** [qgis/QGIS#38278]
[<!--]
After installing QGIS through OSGEO4w, I receive a message about a post install fail. The report shows that many different .bat files failed to run. Here is just one example from the install report (/var/log/setup.log):

_2020/08/11 18:37:25 running: cmd.exe /c "C:\OSGeo4W64\\etc\postinstall\qgis-grass-plugin7.bat"
2020/08/11 18:37:26 abnormal exit: exit code=1_

I am unable to use grass, or any other plugins (like LAStools). I went through the process of manually uninstalling qgis (osgeo) and removing any folders and files. After re-installing, I still receive the same post install errors. I am installing QGIS version 3.14, but even installing the stable release (3.10) returns the same error.

Any suggestions would be very much appreciated. Thanks!

**Comment by gioman** [comment]
> Any suggestions would be very much appreciated. Thanks!

@arojas314 is this a question or a bug report?

**Comment by roya0045** [comment]
Try with the standalone installer?

**Comment by arojas314** [comment]
@gioman This is a question. How can I change the bug label to question? Thanks.

**Comment by gioman** [comment]
> How can I change the bug label to question?

@arojas314 questions must be asked on the users or developers mailing list. This facility is only for bug reports and feature requests. Anyway one possible reason for your problem could a particularly aggressive antivirus software.
