### ISSUE TITLE
Layout Window Crash when Trying to edit a Fixed Table

### ISSUE THREAD

**Issue by Jaydekay** [qgis/QGIS#38280]
## User Feedback

Trying to edit a fixed table in Layout window. 
Crash occurs when I click the Edit Table button in the Item Properties tab.
This is happening to a table I have already created.
I can create a new fixed table and Edit Table , but only the first time. When I try to edit it again it crashes.

## Report Details

**Crash ID**: [a73443f25c0ba92e42796b2feafa1cf7bf040078]('https://github.com/qgis/QGIS/search?q=a73443f25c0ba92e42796b2feafa1cf7bf040078&type=Issues')

**Stack Trace**
<pre>
QBitArray::QBitArray :
QgsAbstractMetadataBase::title :
QgsLayoutManualTableWidget::setTableContents :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.12.1-Bucure?ti
QGIS code revision: 121cc00ff0
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by nirvn** [comment]
@Jaydekay , good news, this is fixed in QGIS' latest release. Please update :)
