### ISSUE TITLE
Data loss when exporting to ESRI Shapefile file format

### ISSUE THREAD

**Issue by phidrho** [qgis/QGIS#38299]
**Describe the bug**
When saving an existing layer to ESRI Shapefile format - if field contains only empty space characters (" ") - one or more, the software automatically removes this data and sets NULL values while exporting.

I have received some data in `.gdb` format, and when I processed data I exported to shapefile and sent data back to the original author, they compared attributes with FME in new and old data, and all fields with empty spaces were gone. I don't know why they are keeping data like that, and not like NULLs, but it is obvious that data loss has happened.

**How to Reproduce**
[Video demo](https://youtu.be/qbB5Ds1f4so) - python errors in the video are due to attribute painter plugin, ignore it

1. Create or open new layer, and create new text field
2. Create some features and populate that text field with one or more space characters: " "
3. Right-click on layer > export > save features as... > choose ESRI Shapefile
4. After new layer is loaded, check attribute table or identify features > empty characters and no characters records (empty string) have been replaced with NULL values

**QGIS and OS versions**
```
Windows 10 Pro 64-bit
Version 1903
```

```
QGIS version
3.12.3-București
QGIS code revision
8234261527
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
attributePainter; 
InvisibleLayersAndGroups; 
lockzoom; 
mmqgis; 
db_manager; 
processing
```

**Comment by roya0045** [comment]
Same as #38112

**Comment by gioman** [comment]
@phidrho I agree, is the same as #38112

**Comment by phidrho** [comment]
ok, I'll close it then, as it's already been discussed
