### ISSUE TITLE
An asterisk is erroneously present at the end of some sentences in autogenerated sip.in files

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/QGIS#38291]
**Describe the bug**
An asterisk is erroneously present at the end of some sentences in autogenerated sip.in files, for example in qgslogger.sip.in:
https://github.com/qgis/QGIS/blob/eeb2526048517ff4ae4b686c831c5bed50d75244/python/core/auto_generated/qgslogger.sip.in#L46-L48

https://github.com/qgis/QGIS/blob/eeb2526048517ff4ae4b686c831c5bed50d75244/python/core/auto_generated/qgslogger.sip.in#L74-L76

https://github.com/qgis/QGIS/blob/eeb2526048517ff4ae4b686c831c5bed50d75244/python/core/auto_generated/qgslogger.sip.in#L85-L87

This creates a corrisponding issue in pyqgis documentation e.g. in https://qgis.org/pyqgis/master/core/QgsLogger.html

![image](https://user-images.githubusercontent.com/16253859/89714753-59eeb680-d9a1-11ea-9e45-be96f01c3d2f.png)

On the contrary, the asterisks are not present in the API documentation https://qgis.org/api/classQgsLogger.html

**Additional context**

https://github.com/qgis/pyqgis/issues/62

**Comment by m-kuhn** [comment]
It comes from some (very old) `*/` end of block comment being written without a newline like 99% of qgis don't do this.

I guess it's easier to adjust the comments than to fix the sip generator script.

https://github.com/qgis/QGIS/blob/master/src/core/qgslogger.h#L104

**Comment by agiudiceandrea** [comment]
I tried search for *.h in \src\ with the following RegExp `^(?!\s*\/\*|\s*\/\/\!).*[^\*\r\n\t\f\v ]\*\/$`
It catches about 130 lines (I'm not sure if it finds all the affected lines, nor if all the found lines are actually affected...)
Is there a way to fix them automatically?

**Comment by m-kuhn** [comment]
It looks like you are better with regex than I am :-D
Give it a shot and look at the diff?

**Comment by m-kuhn** [comment]
thx nyall

**Comment by agiudiceandrea** [comment]
It seems the asterisks are always wrongly there in the pyqgis documentation, despite the fix was merged on Aug 20, 2020 and the pyqgis doumentation results updated on Aug 22, 2020.
