### ISSUE TITLE
Out Of Memory with CRS EPSG:3078

### ISSUE THREAD

**Issue by jjimenezshaw** [qgis/QGIS#38295]
**Describe the bug**
QGIS runs out of memory using `EPSG:3078` `NAD83 / Michigan Oblique Mercator`

**How to Reproduce**
1. Load Open Street Map tile server
2. Select EPSG:3078 in "Project Properties - CRS"
3. Accept without preferred transformation using a gridfile from proj-datum
4. If you are too near, zoom out to see the full continent
5. Wait until the OS (Ubuntu 20.04) kills the process. In the meantime my computer was not responding

**QGIS and OS versions**

QGIS version | 3.14.1-Pi | QGIS code revision | de08d6b71d
-- | -- | -- | --
Compiled against Qt | 5.12.8 | Running against Qt | 5.12.8
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.2 (Ubuntu 12.2-4) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Ubuntu 20.04.1 LTS
Active python plugins | processing; MetaSearch; db_manager

**Additional context**
RAM: 8 GB, swap: 8 GB.
Running `dmesg` I can see: `Out of memory: Killed process 4849 (qgis.bin) total-vm:35653024kB, anon-rss:7599700kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:31540kB oom_score_adj:0`
I have not installed any gridfile from `proj-datum`.
I do not know if this is a `PROJ` problem, or only reproducible in `QGIS`. I tried a single transformation using `cs2cs`, and I didn't have any problem.

**Comment by gioman** [comment]
@jjimenezshaw probably not a thing that is specific to this CRS, but rather ti any case where you are trying to reproject a global layer with a global CRS into a local one.

**Comment by gioman** [comment]
Closing for lack of feedback.
