### ISSUE TITLE
3D  view panel cannot be inserted into the top of the canvas

### ISSUE THREAD

**Issue by bellanz80** [qgis/QGIS#38293]
Hi, 
I noticed an incorrect behavior when hooking the 3D view panel, at the top of the canvas. In particular, QGIS goes into crash.

1) I load a tif DEM
2) change the style to hillshade
3) change the resample in bilinear
4) open 3D panel
5) I adjust the parameters
6) I select the panel and try to hook it on the upper wall: crash

Note: 
a) I only get the crash if I hook it at the top: on the right there's no problem.

b) I already checked several DEM formats, and I get the same error with tiff, GRD, ADF

c) some other users have already done the test: some things are wrong, others are not.

Windows 10 64 bit
QGIS 3.14.1 / 3.10.8 /  New profile, NO Plug.

I attach DEM, 
[DEM_EPSG_32615.zip](https://github.com/qgis/QGIS/files/5077043/DEM_EPSG_32615.zip)

images and a video.
[VIDEO.zip](https://github.com/qgis/QGIS/files/5077054/VIDEO.zip)

![image](https://user-images.githubusercontent.com/38449926/90290116-eb977180-de42-11ea-9daf-995b31622160.png)
![image](https://user-images.githubusercontent.com/38449926/90290161-fce07e00-de42-11ea-820f-a324cc3c2f95.png)

**Comment by gioman** [comment]
No crash on 3.10.8 ion Ubuntu 20.04.

**Comment by bellanz80** [comment]
The bug continues also in QGIS 3.16
Windows 10 
I attach an example video

[https://www.youtube.com/watch?reload=9&v=bUpF3axHuwU&feature=youtu.be](url)

**Comment by DelazJ** [comment]
@bellanz80 Can you try with a [new profile](https://docs.qgis.org/3.10/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)?
