### ISSUE TITLE
[Vector Tile] printing goes beyond the definition of the map tile

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#38302]
how to play:
1. add a vector tile to a new project
2. create a print layout
3. add map (see screenshot below)
4. export as image or PDF
5. the printing is different from the layout, the vector tile goes beyond the definition of the box.

I attach project (qgz).

[test.zip](https://github.com/qgis/QGIS/files/5078956/test.zip)

i used this url:
  https://www.qwant.com/maps/tiles/ozbasemap/{z}/{x}/{y}.pbf

## OSGeo4W64 Win 10 - QGIS 3.14.1 Pi (in the master it works fine!)

![image](https://user-images.githubusercontent.com/7631137/90315643-59b06700-df1d-11ea-9d35-480f4037872d.png)

### layout

![layout](https://user-images.githubusercontent.com/7631137/90315553-c5de9b00-df1c-11ea-9cb2-56f47e58b0d3.png)

### I export as a png image

![test](https://user-images.githubusercontent.com/7631137/90315592-edcdfe80-df1c-11ea-806a-09acc582e9bf.png)

### I export as PDF

[test.pdf](https://github.com/qgis/QGIS/files/5078970/test.pdf)

**Comment by bellanz80** [comment]
I confirm, on windows 10 64 bit, QGIS 3.14.1

**Comment by gioman** [comment]
@pigreco duplicate of https://github.com/qgis/QGIS/issues/37443 ?

**Comment by pigreco** [comment]
> @pigreco duplicate of #37443 ?

yes
