### ISSUE TITLE
Exporting a PDF from qgis 3.10.5.A which included Bing Imagery and four vector layers

### ISSUE THREAD

**Issue by peterfrancon** [qgis/QGIS#38313]
QGIS 3.10.5.A Coruna

Crashed during Export to PDF from Layout Manager.
Bing imagery is misplaced on the map.

Maybe it didn't like such a large export (A3) with all geodata included in the PDF.

There are four other layers.

Report Details...
Crash ID: 85eb41a8bd937fe4e3b1ae55ad823c3b61fbccca

Stack Trace

QgsMapRendererStagedRenderJob::renderCurrentPart :
QgsLayoutItemMap::paint :
QGraphicsScene::dragMoveEvent :
QGraphicsItem::dragMoveEvent :
QGraphicsEffectSource::draw :
QgsLayoutEffect::draw :
QGraphicsScene::drawItems :
QGraphicsScene::drawItems :
QGraphicsScene::render :
QgsLayoutExporter::renderRegion :
QgsLayoutExporter::renderPage :
QgsLayoutExporter::printPrivate :
QgsLayoutExporter::QgsLayoutExporter :
QgsLayoutExporter::handleLayeredExport :
QgsLayoutExporter::exportToPdf :
QgisApp::actionAddWcsLayer :
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.10.5-A Coru�a
QGIS code revision: 984615fe1e
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment]
@peterfrancon do you have the "print as raster" option enabled?

**Comment by peterfrancon** [comment]
No gioman. That was an option I overlooked. Thanks for the reply. I'll try it again.  Actually it worked nicely with OSM served from a Tile Server.

**Comment by gioman** [comment]
> Bing imagery is misplaced on the map.
> 
> Maybe it didn't like such a large export (A3) with all geodata included in the PDF.
> 
> There are four other layers.

@peterfrancon can you share the project (and necessary data)?

**Comment by peterfrancon** [comment]
I wondered if it just gave up exporting to A3, but read about the Tile Server working somewhere, so I tried that method, which worked. I'm working on an FTTx network, largely polyline data, and there wasn't much data involved. 

I would share it, but my client asked that my work remain confidential.

**Comment by gioman** [comment]
>  I would share it my work

@peterfrancon wihtout a way/project/description to consistently replicate the issue there isn't much we can do here. Aren«t you able to replicate on similar project without using sensitive/private data?

**Comment by peterfrancon** [comment]
Setting up example data takes an age, but here are some examples screen grabs showing gaps in the Bing imagery. The large circular image is exported using 'Microsoft Print to PDF'. I find all Atlas outputs work well with that printer driver. 

As for data, there were about 5 or 6 layers, points and linestrings, two layers were served from a spatialite db. There are no more than 1,000 records of data in the composition. 

I did have some initial problems with the Export mis-projecting Bing imagery, but I can't reporoduce that error.  

![Not full coverage with Bing Imagery A3 Landscape export MS PDF writer](https://user-images.githubusercontent.com/22873128/90523918-59a2a800-e165-11ea-90e0-e59a40f3ef7f.JPG)
![gaps in imagery NOT as a Raster](https://user-images.githubusercontent.com/22873128/90523923-5a3b3e80-e165-11ea-97c6-c679238eb6e1.JPG)
![Not full coverage with Bing Imagery A3 Landscape export MS PDF writer 02](https://user-images.githubusercontent.com/22873128/90523925-5ad3d500-e165-11ea-9d79-d93f3d7a7381.JPG)
![Not full coverage with Bing Imagery A3 Landscape export MS PDF writer 03](https://user-images.githubusercontent.com/22873128/90523926-5ad3d500-e165-11ea-92fb-cdbea2af9eda.JPG)
