### ISSUE TITLE
Ubuntu Focal - fresh repo install python support issue --> Couldn't load SIP module

### ISSUE THREAD

**Issue by leogaggl** [qgis/QGIS#38310]
This seems to be a recurring issue that happened with previous versions of Ubuntu version repositories, but I wasn't able to find a fix in any of the previous bug reports.

**How to Reproduce**

Clean install of QGIS from QGIS repo

deb     [arch=amd64] https://qgis.org/ubuntu focal main
deb-src [arch=amd64] https://qgis.org/ubuntu focal main

Error:

```
Couldn't load SIP module.
Python support will be disabled.


Traceback (most recent call last):
  File "", line 1, in 
ModuleNotFoundError: No module named 'qgis'
```

Python version:
3.8.2 (default, Jul 16 2020, 14:00:26) 
[GCC 9.3.0]

QGIS version:
3.14.15-Pi 'Pi', d5114d2cfa

**QGIS and OS versions**

Ubuntu 20.04LTS Focal Fossa 64bit
QGIS Pi 3.14.15

QGIS version | 3.14.15-Pi | QGIS code revision | d5114d2cfa
-- | -- | -- | --
Compiled against Qt | 5.12.8 | Running against Qt | 5.12.8
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.2 (Ubuntu 12.2-4) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Ubuntu 20.04.1 LTS

**Additional context**
Here is the list of installed modules

dpkg -l | grep qgis | awk '{print $2}'

libqgis-3d3.14.15
libqgis-analysis3.14.15
libqgis-app3.14.15
libqgis-core3.14.15
libqgis-customwidgets
libqgis-gui3.14.15
libqgis-native3.14.15
libqgis-server3.14.15
libqgisgrass7-3.14.15
libqgispython3.14.15
python3-qgis
python3-qgis-common
qgis
qgis-common
qgis-plugin-grass
qgis-plugin-grass-common
qgis-provider-grass
qgis-providers
qgis-providers-common

**Comment by JohnMoutafis** [comment]
This was happening in Ubuntu 18.04 with an incompatible PyQt version. Can you try the following:

```
$ pip3 uninstall PyQt5
$ sudo apt-get install python3-pyqt5
```
found here: [https://askubuntu.com/a/1144031/960429](url) with the following explanation:

> PyQt in PyPI is not compatible with the installed Qt

**Comment by antonellosalis** [comment]
I already tryied. It did not work on Debian Testing

`Not uninstalling pyqt5 at /usr/lib/python3/dist-packages, outside environment /usr
Can't uninstall 'PyQt5'. No files were found to uninstall.
`

**Comment by lanecodes** [comment]
I am also having this issue. Presumably this is linked to the (now closed) #321

**Comment by antonellosalis** [comment]
I solved it in Debian-GNU Linux, only thanks to the developers that fixed the QGIS version.

**Comment by gioman** [comment]
Not a general issue.
