### ISSUE TITLE
qgis 3.14.15 build failure: "Policy "CMP0071" is not known to this version of CMake"

### ISSUE THREAD

**Issue by GvMariani** [qgis/QGIS#38327]
**Describe the bug**
The main CMakeLists.txt file claims to require cmake "3.1.0" as minimum, but then it sets "CMP0071": this policy was introduced in cmake 3.10 and is not recognized.
This situation causes a build failure when using any cmake < 3.10 (in my building setup cmake 3.7.2)... 
Perhaps a typo ("3.1.0" instead of "3.10)"? Or someone forgot to update the cmake requirement?

**How to Reproduce**
1. Install the sources
2. Run cmake (< 3.1.0) with the desired options
3. Watch the error: "CMake Error at CMakeLists.txt:11 (CMAKE_POLICY):
                              Policy "CMP0071" is not known to this version of CMake."

**QGIS and OS versions**
QGIS 3.14.15
Rosa Linux Fresh R11 [a Mandriva derivative] x86_64

**Additional context**
Trying to build latest QGIS sources to update distribution package.
The issue is still present in the master branch.

**Comment by m-kuhn** [comment]
I have added an update to bump the minimum version. You could be lucky just removing this line in CMakeLists.txt (just to get it to build).
