### ISSUE TITLE
Layout legend map source change not working

### ISSUE THREAD

**Issue by danzig666** [qgis/QGIS#38326]
Legend symbol scales won't change when switching source maps in layouts with multiple maps. See attached sample project and screen recording.

**QGIS and OS versions**
3.14.15-Pi on Windows 10 

![VYLj4Cf4yE](https://user-images.githubusercontent.com/5346511/90375906-e66e3880-e075-11ea-96a1-acbfed46addb.gif)
[sample_project.zip](https://github.com/qgis/QGIS/files/5083097/sample_project.zip)

**Comment by roya0045** [comment]
Just click outside of the legend for a refresh.

**Comment by danzig666** [comment]
> Just click outside of the legend for a refresh.

No it does not refresh, ever. Just try it with the attached project.
