### ISSUE TITLE
Semi-Automatic Classification Plugin is not working

### ISSUE THREAD

**Issue by RAKA6890** [qgis/QGIS#38342]
**Describe the bug**
Semi-Automatic Classification Plugin some files are missing or crashed.
Crash ID: 2a39923cea313ba9593cde8930098917d9a41b9f
Stack Trace:
QDockWidget::toggleViewAction :
QgisApp::removeDockWidget qgisapp.cpp:3960
meth_QgisInterface_removeDockWidget sip_guipart3.cpp:243832
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyEval_EvalCodeEx :
PyEval_EvalCode :
PyArena_Free :
PyRun_StringFlags :
QgsPythonUtilsImpl::runStringUnsafe qgspythonutilsimpl.cpp:307
QgsPythonUtilsImpl::runString qgspythonutilsimpl.cpp:324
QgsPythonRunnerImpl::runCommand qgisapp.cpp:10803
QgsPythonRunner::run qgspythonrunner.cpp:33
QgsPluginManager::buttonUninstall_clicked qgspluginmanager.cpp:1382
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
meth_QgsPluginManagerInterface_showPluginManager sip_guipart2.cpp:70212
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyEval_EvalCodeEx :
PyEval_EvalCode :
PyArena_Free :
PyRun_StringFlags :
QgsPythonUtilsImpl::runStringUnsafe qgspythonutilsimpl.cpp:307
QgsPythonUtilsImpl::runString qgspythonutilsimpl.cpp:324
QgsPythonRunnerImpl::runCommand qgisapp.cpp:10803
QgsPythonRunner::run qgspythonrunner.cpp:33
QgisApp::showPluginManager qgisapp.cpp:10781
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1606
BaseThreadInitThunk :
RtlUserThreadStart :

**How to Reproduce**

 QGIS Unexcpectedly Ended. 
                         

**QGIS and OS versions** 
QGIS Info:
QGIS Version: 3.10.9-A Coruña
<img width="1920" alt="3" src="https://user-images.githubusercontent.com/69835130/90473238-0cf8a600-e140-11ea-8f0c-dec8e03a9a25.png">
<img width="1920" alt="1" src="https://user-images.githubusercontent.com/69835130/90473244-11bd5a00-e140-11ea-9c51-fcd98660bbed.png">
<img width="1920" alt="2" src="https://user-images.githubusercontent.com/69835130/90473247-14b84a80-e140-11ea-9d1d-f054d7e03114.png">
<img width="1920" alt="Exit" src="https://user-images.githubusercontent.com/69835130/90473266-1aae2b80-e140-11ea-9d12-6cd0416be82d.png">

QGIS code revision: bf47e9d3e1
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info:
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

QGIS version
3.10.9-A Coruña
QGIS code revision
bf47e9d3e1
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
scpplugin; 
SemiAutomaticClassificationPlugin; 
db_manager; 
MetaSearch; 
processing

**Additional context**

QGIS Exit Problems.

**Comment by Gustry** [comment]
Please report the issue to the plugin author. Not QGIS itself.
