### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by sdieters** [qgis/QGIS#38346]
Crash on Start-up for QGIS 3.14, 3.14.15 and earlier QGIS3.10 version. Under windows 10.
I am an infrequent user of QGIS, it was working on 20 July 2020, but not working today 18 Aug 2020. I have tried re-installing QGIS, doing a reboot. The crash occurs on start-up even when there is no other interaction aside from launching the application. Another user same Win 10 set up reported crashes on earlier QGIS version. Crashes occurred before an after most recent Win 10 update.

Crash ID: 67d946f7e16887bfd939dfe454d37ea8d66bc49c

Stack Trace

QSslKey::operator!= :
QSslKey::operator!= :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:439
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
QEventLoop::exec :
QThread::exec :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.14.15-Pi
QGIS code revision: d5114d2cfa
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by Gustry** [comment]
You might have something wrong in your QGIS User profile.
Please try to make a new one, you can rename your current profile, QGIS will re-create the one called `default`.
Have a look there to know where profiles are : https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles
They aren't removed when you desinstall QGIS

**Comment by sdieters** [comment]
Thanks Etienne

I have renamed the old profile, rerun QGIS, it created a new default profile, but still crashed a couple of minutes after start-up.
QGIS 3.14.15 is responsive for a little while so I created a new profile. Again using that profile I had a crash, even without any user input.


I have just loaded QGIS 3.14  on a laptop under windows 10. It is similar but not identical environment to my work computer. There seems to be no problem with either the very old Wein 2.8 or newer 3.14.15 installation on the laptop. So it is something that has changed in our organization environment.
 I am checking with other users in our organization.

Any ideas would be welcome.

Stefan

Stefan Dieters   |   Spatial Information Officer
Geodata Services   |   Land Tasmania

Currently working from home:
T :03 62 72 25 16
M:04 59 23 49 39

Department of Primary Industries, Parks, Water and Environment
Level 9, Lands Building
134 Macquarie Street Hobart TAS 7000
GPO Box 44 Hobart TAS 7001

T: 03 6165 3191  |   M:    |   E: stefan.dieters@dpipwe.tas.gov.au<mailto:stefan.dieters@dpipwe.tas.gov.au>
www.dpipwe.tas.gov.au<http://www.dpipwe.tas.gov.au/>   |   www.thelist.tas.gov.au<http://www.thelist.tas.gov.au/>   |   www.tasmap.tas.gov.au<http://www.tasmap.tas.gov.au/>

[Facebook Land Tasmania]<https://www.facebook.com/landtasmania>[Twitter Land Tasmania]<https://twitter.com/LandTasmania?lang=en>[LinkedIn Land Tasmania]<http://www.linkedin.com/company/land-tasmania>

CONFIDENTIALITY NOTICE AND DISCLAIMER

The information in this transmission may be confidential and/or protected by legal professional privilege, and is intended only for the person or persons to whom it is addressed. If you are not such a person, you are warned that any disclosure, copying or dissemination of the information is unauthorised. If you have received the transmission in error, please immediately contact this Office by telephone, fax or email, to inform us of the error and to enable arrangements to be made for the destruction of the transmission, or its return at our cost. No liability is accepted for any unauthorised use of the information contained in this transmission.

If the transmission contains advice, the advice is based on instructions in relation to, and is provided to the addressee in connection with, the matter mentioned above. Responsibility is not accepted for reliance upon it by any other person or for any other purpose.

**Comment by Gustry** [comment]
Same crash ID : https://github.com/qgis/QGIS/issues/37121 Have you look?

**Comment by a-saadallah** [comment]
i've had something similar and it turns out that i messed up my python installation. De-install all, and then rerun osgeo again. i assume you are using osgeo network installer.

**Comment by gioman** [comment]
> Same crash ID : #37121 Have you look?

Closing as duplicate,

**Comment by sdieters** [comment]
This specific crash has been resolved. It was case of adding proxy information to QGIS. 
However an issue very similar to Same crash ID: #37121.

**Comment by ghellerwagner** [comment]
@sdieters, I found that the main issue with this crash was to do with the network authentication certificates. I have been able to supersede the crashing by getting to the authentication window and manually clearing the authentication caches before it crashes, this seems to stabilize the issue for the time being.
