### ISSUE TITLE
When editing attribute table, the field calculator progress bar runs multiple times

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#38357]
While updating a field using the field calculator, I get a progress bar (which is nice) loading the features and it processes more than once (actually the first time I ran it, I had to abort it at the 4th round, and then trying to capture the issue for report, it sometimes did it in a row (I used another layer) or twice)

![fieldCalcProgress](https://user-images.githubusercontent.com/7983394/90596137-9bc3fc00-e1ee-11ea-8ca6-e7d495e8b638.gif)

Moreover:
* I find scary the field name becoming "extra column"
* Can we add more text to the progress bar dialog, explaining what's going on or a more descriptive title?--I was unsure whether aborting would stop the update or the loading of the result in the attribute table... The dialog mentions loading (no update or edit) so one could assume that the update is already done?

QGIS version | 3.15.0-Master | QGIS code revision | 6712278a42b
-- | -- | -- | --
Compiled against Qt | 5.12.8 | Running against Qt | 5.12.8
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.2 (Ubuntu 12.2-4) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Ubuntu 20.04.1 LTS | This copy of QGIS writes debugging output.
Active python plugins | db_manager; MetaSearch; processing

**Comment by gioman** [comment]
@DelazJ does it happens only when creating virtual fields? Anyway this does not seems right to me, all that time to compute 800 results for an expression? Can you say if this was the same in previous releases?

**Comment by gioman** [comment]
I overlooked that was an aggregate expression, so it is normal that can take a while. Does it make any difference if you try that expression with the table of attributes closed? I recall a problem about running operations with the field calculator with the TA open being much slower compared than running them with the TA closed.
