### ISSUE TITLE
Atlas duplicates pages in exported pdf

### ISSUE THREAD

**Issue by AlisterH** [qgis/QGIS#38356]
![qgis atlas sort bug](https://user-images.githubusercontent.com/714600/90588772-912a5680-e230-11ea-8478-4bd424560637.PNG)

I have used the composer "atlas" functionality, using a shape file coverage layer with features identified alphabetically A to V.
When I test exporting the atlas to pdf without specifying a column to sort by, it seems to work correctly (but I can't be sure it always will).
When I specify the column to sort by, it usually (not 100% of the time) produces a pdf with duplicates of some or all pages.  What happens is the progress dialog gets to 100%, closes, then reopens and does more pages (see screenshot above).
Sometimes just one page is duplicated: A, A, B, C ...
Sometimes two pages: A, B, A, B, A, B, C, D ...
Often it creates two copies of all the pages, plus more of the first few pages: A, B, C, D, A, B, C, D ... V, A, B, C, D ... V.

I suspect the unpredictable results are something to do with what has been previewed in the composer.
The problem occurs across multiple QGIS versions (at least from 3.4.x to 3.14.x).
I tried in a new user profile and the problem still occurs.
When I "save as" to make a copy of the project, the new project doesn't seem to have the same issue.
A normal save does not fix it.
When I remove most of the layers (trying to create a minimal example project), and do a normal save it seems to be fixed. 

I have seen the same problem before.  Any suggestions for how I can debug it to figure out what causes the problem? Best I can think of is to remove the layers one at a time, saving and checking if the problem occurs.

**Comment by gioman** [comment]
@AlisterH it this replicable with any project/data?

**Comment by AlisterH** [comment]
It doesn't occur with every project, and as I said, a "save as" seems to fix it.  
It is problematic enough that I'd like to try to get to the bottom of it - if you don't pay attention while it is exporting, then you might not notice that your pdf has been output with duplicate pages.  
When I get a chance I'll try to package up the most minimal project I can to replicate it, but it's going to be a bit laborious.  I was hoping there might be a way to debug what it is actually doing as it does the export, but I'm guessing it won't be possible without tinkering in the source.

**Comment by gioman** [comment]
> When I get a chance I'll try to package up the most minimal project I can to replicate it,

@AlisterH were you able to create a sample project?

**Comment by privatemajory** [comment]
I know this issue is closed but I'd like to let you know that this happens to me as well with QGIS 3.22 LTR, especially when the atlas has a lot of pages (1000+)

**Comment by eysupa** [comment]
I have to agree with this, I also still have this bug in Version 3.22.11. The atlas is about 190 pages and whenever I export it, the first two pages are duplicated.

**Comment by nicogodet** [comment]
@eysupa Could you share a sample project+data to reproduce ?

**Comment by humberto77** [comment]
Our team also has this problem.  The first page is always duplicated in PDF export.  We are using 3.28 and 3.30, where we observed the issue.

**Comment by nicogodet** [comment]
@humberto77 As requested for others, could you share a sample project to reproduce ?
I export many atlas without this issue

**Comment by humberto77** [comment]
It is a very large project with sensitive data.  I regret I am not able to share.

**Comment by mblesius** [comment]
@humberto77 
Do you have multipe map frames on the atlas page?

**Comment by humberto77** [comment]
> @humberto77 Do you have multipe map frames on the atlas page and are both controlled by the atlas?

Yes, we have 2 map frames.  One is used as an overview.  Note I attempted to create a new project and reproduce the duplicate 1st page.  I was able to reproduce a pdf once with the duplicate page.  However subsequent tries the pdf looked fine.  I may revisit the problem if I can think of anything.

**Comment by AlisterH** [comment]
> Do you have multipe map frames on the atlas page and are both controlled by the atlas?

I can't speak for others, but I have never made a map with more than one frame controlled by the atlas.
And I'm pretty sure the last time I experienced this bug I didn't even have an overview map - there was just one frame on the page.

**Comment by ptycharly** [comment]
Just for share, I had the same issue. I restarted the computer then it worked.

**Comment by matjash** [comment]
This issue is still present in QGIS 3.28.13. Unfortunately there seems to be no pattern when it happens. Until now I only had problems with first page printed twice.

**Comment by nyalldawson** [comment]
@matjash until someone provides a sample project demonstrating this issue there's nothing that can be done.

Can you supply one?

**Comment by matjash** [comment]
Here is a project with data. Also sample of output when error hapens and (correct)output after reopening layout.
It is hard to reproduce the problem. While trying, closest to consistent way to get duplicated pages in atlas was, to change layer lock in map properties and/or not having the first page set on preview when printing atlas. But not always. 
The most reliable part of error  is, once you get duplicated pages it will keep on happening everytime you run atlas until you close layout and open it again (QGIS restart not needed).  
I know it is not relevant if you have one or more maps in layout. 

I`m thinking maybe something to do with selection of page in atlas preview. Couple of times when trying to reproduce duplication, i got different kinds of duplication (instead of corectly print pages 1, 2, 3, 4, 5;  I got mostly 1, 1, 2, 3, 4, 5; but also: 1, 2, 3, 1, 2, 3, 4, 5).
I didnt pay attention then but i think I had page 5 in preview when I ran atlas and I got only page 1 duplicated and 2,3 or 4 when 1,2,3 were duplicated. 

I hope this is of any help.


 
[Priprava kart.zip](https://github.com/qgis/QGIS/files/14758195/Priprava.kart.zip)

> @matjash until someone provides a sample project demonstrating this issue there's nothing that can be done.
> 
> Can you supply one?

**Comment by nyalldawson** [comment]
@matjash I've test that project and am unable to reproduce. Have you tried from a clean profile with no plugins installed? Perhaps there's a plugin causing this issue.

**Comment by AlisterH** [comment]
Sorry, deleted the last part of that comment as I initially misunderstood what I was looking at.

**Comment by matjash** [comment]
@AlisterH great find! I can confirm, solely a lot of clicking back and forth through atlas pages will cause duplication. 
In my case, after turning preview off and on, duplication doesnt happen anymore. 
@nyalldawson I tried with clean profile, no plugins.
I could still not determine the numer or combination of clicks, it seems random. Sometimes i did cca 20 clicks and got duplicated page, sometimes over 30 still didnt. What would be another way to pinpoint the problem.

**Comment by EwenH** [comment]
Thank you @AlisterH and @matjash for finding clicking around may be the issue. I tried testing having the initial page of the atlas viewed and then the last page of the atlas viewed and both generated the duplicate. This issue appears present in 3.40.7-Bratislava

**Possible local remedy**
The work around for those who maybe impacted is (from above) is that before you print to PDF, close the Print Layout window, reopen the Print Layout and then export the atlas to PDF which will hopefully remove the duplicate page. Always check your work first if you can.

Thanks to all who have contributed.
