### ISSUE TITLE
DB Manager: cannot add anymore query layers

### ISSUE THREAD

**Issue by arnaudDup** [qgis/QGIS#38366]
I encounter a problem with The DB Manager plugin.
I have a postGIS database up, using the connector I can access the db, create view, However I cannot load the SQL query as layer.

When I select to 'Load as new layer', set the columns, geometry column and layer prefix nothing loads and there is no error report or explanation as to why not. I tried different options and the problem comes from the geometry columns selection.

![geometry](https://user-images.githubusercontent.com/14861337/90616209-d5f4c400-e215-11ea-8fbf-16d5aaec79ae.png)
![erro](https://user-images.githubusercontent.com/14861337/90616802-91b5f380-e216-11ea-9862-36a1b5688025.png)
Do you have any suggestions ?

**Comment by gioman** [comment]
@arnaudDup have a look in QGIS log (settings > panels > logs).

**Comment by arnaudDup** [comment]
The only log related to this issue is:
'2020-08-19T13:12:24     WARNING    Invalid PostgreSQL layer'

**Comment by arnaudDup** [comment]
The problem seems to come from the current version (3.14.15-PI).
I tried the exact same sequence of actions with an other QGIS version and it worked like a charm.

**Comment by gioman** [comment]
> The problem seems to come from the current version (3.14.15-PI).
> I tried the exact same sequence of actions with an other QGIS version and it worked like a charm.

@arnaudDup thanks for checking.

**Comment by elpaso** [comment]
Is this still a problem with current versions? Can we close?
If not, please provide a ste-by-step procedure to reproduce the issue and the necessary data.

**Comment by gioman** [comment]
> Is this still a problem with current versions? Can we close?

@elpaso I recently used this functionality on the latest 3.10 and it was fine.

**Comment by arnaudDup** [comment]
It worked on my current version, thanks !
