### ISSUE TITLE
Cannot commit changes to PostGIS layer with field calculator

### ISSUE THREAD

**Issue by jguelat** [qgis/QGIS#38360]
One gets an error message when trying to save edits after adding a text column using the field calculator (using a PostGIS table). Here's how to reproduce the bug:

1. Create a new PostGIS table (for example with an id field and a geometry field).
2. Open the attribute table and click on the field calculator.
3. Using the field calculator, create a new field with field type "Text, unlimited length (text)" and add some text content (the same bug also occurs with char and varchar).
4. Try to save edits

The following warning will appear:

Could not commit changes to layer temp

Errors: SUCCESS: 1 attribute(s) added.
  ERROR: field with index 2 is not the same!
  Provider: postgres
  Storage: PostgreSQL database with PostGIS extension
  expected field: name=dfdd type=QString typeName=text len=-1 precision=0
  retrieved field: name=dfdd type=QString typeName=text len=-1 precision=-1

5. Try to save the edits a second time, no more warning

The bug only occurs when the field calculator creates a new field. One workaround consists in creating a new empty text field and then using the field calculator to add some content. 

QGIS versions: 3.14.15 and 3.10.9
OS: Windows 10

**Comment by gioman** [comment]
Confirmed here too on Ubuntu 20.04, QGIS 3.10.8 and a layer on a PostgreSQL 9.6 server.

Very bad problem/regression.

**Comment by dminor** [comment]
I think the problem was introduced with this commit: https://github.com/qgis/QGIS/commit/96aa671307d937488cd9a74f39bdf7df0175d4a8. It looks like PostGIS (or perhaps the PostGIS provider) uses -1 to represent an unset precision, but spatialite (and perhaps others) use 0.

**Comment by gioman** [comment]
> I think the problem was introduced with this commit: [96aa671](https://github.com/qgis/QGIS/commit/96aa671307d937488cd9a74f39bdf7df0175d4a8)

@dminor so old an no one noticed it before? seems unlikely, but I cannot comment from a technical point of view.

**Comment by dminor** [comment]
That line is causing the problem, but it's entirely possible that something else has changed since then to cause the bug to only show up now.

**Comment by jguelat** [comment]
Thanks a lot!
