### ISSUE TITLE
not responding after click override button

### ISSUE THREAD

**Issue by nnzrr** [qgis/QGIS#38362]
## User Feedback

click data defined override botton and not responding

## Report Details

**Crash ID**: [1a289f1fb92020b43becccfc365517c0c0472d7e](https://github.com/qgis/QGIS/search?q=1a289f1fb92020b43becccfc365517c0c0472d7e&type=Issues)

**Stack Trace**
<pre>
QgsPropertyOverrideButton::aboutToShowMenu qgspropertyoverridebutton.cpp:474
</pre>

**QGIS Info**
QGIS Version: 3.14.1-Pi
QGIS code revision: de08d6b71d
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
@misto please add all the necessary information: detailed steps to replicate the issue, add a project/data if necessary. Also first try with a new QGIS profile, no 3rd party plugins installed.

**Comment by gioman** [comment]
Closing for lack of feedback.
