### ISSUE TITLE
Matplotlib, python-Numpy and Scipy error, QGIS crash

### ISSUE THREAD

**Issue by Evanilton** [qgis/QGIS#38373]
Hi.
I just updated QGIS to its 3.14.15 version and somehow the Semiautomaticlassification (SCP) plugin is creating some of a mess with Matplotlib, Scypy and Python-Numpy. When I try to instal those from the OSGEO4W setup, it shows already installed and does not solve the problem with a reinstallation. On the other hand, QGIS crashes whether I close it, try to reinstall or uninstall the plugin altogether.
Does anyone know a way to deal with this issue?
Thanks

**Comment by gioman** [comment]
@Evanilton please contact the SCP author.

**Comment by Evanilton** [comment]
Thanks
Solved the problem by going back to 3.12
