### ISSUE TITLE
QGIS crashes on Exit

### ISSUE THREAD

**Issue by samirraouf** [qgis/QGIS#38391]
## User Feedback

The program crashes when I try to close the QGIS. It happened several times.

## Report Details

**Crash ID**: [533376728e5523b2835d2f7e33464e1f304dd042](https://github.com/qgis/QGIS/search?q=533376728e5523b2835d2f7e33464e1f304dd042&type=Issues)

**Stack Trace**
<pre>
QDockWidget::toggleViewAction :
QgisApp::removeDockWidget qgisapp.cpp:3960
meth_QgisInterface_removeDockWidget sip_guipart3.cpp:243832
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyEval_EvalCodeEx :
PyEval_EvalCode :
PyArena_Free :
PyRun_StringFlags :
QgsPythonUtilsImpl::evalString qgspythonutilsimpl.cpp:529
QgsPythonUtilsImpl::unloadPlugin qgspythonutilsimpl.cpp:648
QgsPluginRegistry::unloadAll qgspluginregistry.cpp:191
QgisApp::saveWindowState qgisapp.cpp:4653
QMetaObject::activate :
QCoreApplicationPrivate::execCleanup :
QCoreApplication::exec :
main main.cpp:1606
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.9-A Coru?a
QGIS code revision: bf47e9d3e1
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by Gustry** [comment]
Same crash ID : https://github.com/qgis/QGIS/issues/33207

Are you using SCP plugin? Desinstall it and check.
If it's still crashing, try with a new QGIS user profile.

**Comment by samirraouf** [comment]
Many thanks. It worked fine after uninstalling.
Best regards, Samir
