### ISSUE TITLE
Topology Checker returns 'Feature not found in the layer'

### ISSUE THREAD

**Issue by northrivergeo** [qgis/QGIS#38399]
Platform: Windows and Linux (Ubuntu)
Version: 3.14.15 

I've attached an error.zip and in that there is a QGZ and a Geopackage. The Geopackage has a polygon layer that has gaps and overlaps. So open it up the QGZ and do the following (It may be set up but in case you want to replicate): 

1. Add the layer from the geopackage 
2. Activate the topology checker 
3. Set up a rule that the layer can't have gaps 
4. Click the error in the Topology Check panel and you'll get a "Feature not found in the layer. The layer has probably changed. Run topology check again".  It will zoom to the error correctly. 

![Screenshot from 2020-08-20 08-43-28](https://user-images.githubusercontent.com/389868/90772175-478a4c00-e2c2-11ea-9c8a-9b84c8b30528.png)

5. As far as I know nothing has changed. This doesn't happen with a rule for overlaps. 

Anyway - I searched and didn't find another error - BUT - I may have missed something. 

[error.zip](https://github.com/qgis/QGIS/files/5103078/error.zip)

**Comment by gioman** [comment]
@rjhale1971 Hi Randal, there is no "topology_check.gpkg" in the zip file. Cheers!

**Comment by rjhale1971** [comment]
I blame everything but my ability to properly create a zip file (thank you). 

[error_2.zip](https://github.com/qgis/QGIS/files/5103528/error_2.zip)

**Comment by gioman** [comment]
Confirmed also on LTR on Ubuntu 20.04. As far as I remember (I can't check older releases now) this is a regression.

**Comment by agiudiceandrea** [comment]
Confirmed using QGIS 3.10.1, QGIS 3.4.5 and QGIS 2.18.23 on Windows.

**Comment by Pedro-Murteira** [comment]
I can still reproduce this on QGIS 3.16.15 and 3.22.2.

**Comment by alexbruy** [comment]
Not reproducible with the latest master (f344919474) on LInux.

**Comment by agiudiceandrea** [comment]
It no longer even occur using QGIS 3.28.11 on Windows.
