### ISSUE TITLE
Zoom to layer overwrites locked scale bug

### ISSUE THREAD

**Issue by luxenborg** [qgis/QGIS#38417]
**Describe the bug**

when scale is locked. (I use this feature all the time, when designing my maps)
![image](https://user-images.githubusercontent.com/42667051/90874940-ade59c00-e3a0-11ea-85b8-e59d74b5e21a.png)

And you "zoom to layer". (another feature i use all the time, for varius reasons)
![image](https://user-images.githubusercontent.com/42667051/90874836-8abaec80-e3a0-11ea-9371-f685ee4a579a.png)

The scale changed, and it shouldn't.   
![image](https://user-images.githubusercontent.com/42667051/90875035-d1104b80-e3a0-11ea-814b-089eacac5510.png)

In my opinion the zoom to layer feature should use the scale when unlocked and the magnifying glass when locked.
This is a bug and not a feature request. When you lock something you shouldn't be able to change it in any way.

I really hope someone knows how to fix this, I will be a happy man and might buy a cake :-)
thx in advance
Jan

**How to Reproduce**
If you do just like i have described in the above "bug report". It will do this every time. 

**QGIS and OS versions**

All versions of QGIS 

QGIS-version
3.14.15-Pi
QGIS-koderevision
d5114d2cfa

**Additional context**

**Comment by elpaso** [comment]
I see that there is another bug: if you use the magnifier to zoom out and pan the map the scale is changed even when it's locked.

**Comment by elpaso** [comment]
Just because you promised a cake :wink:

**Comment by luxenborg** [comment]
Ha ha... thanks so very very much! even though i did **not** specify when, where or who eats the cake. Let see if we can figure something out :-D But thank you for looking at the issue.
Jan

**Comment by elpaso** [comment]
@luxenborg while you are baking the cake, you could give it a try to https://github.com/qgis/QGIS/pull/38954 and see if you spot any other issue?

**Comment by luxenborg** [comment]
this so cool... i'm super thankful that you fixed it :-) im working on Qgis 3.16.1 now and i have just noticed that, it seems the fix isn't working if i click "zoom to object" from the attributes table... Is that something that you could easily fix or is that a huge amount of work?

**Comment by elpaso** [comment]
@luxenborg no idea :) Please file another ticket and I'll possibly have a look during the next bugfixing round.

**Comment by luxenborg** [comment]
Okay, i'll do that. It might be awhile, but i'll do it.
I'm doing my final exam at the moment. So it might be a few weeks before i return to normal life and have better time for describing an issue report :-)

**Comment by elpaso** [comment]
Assuming fixed
