### ISSUE TITLE
When embedding a layer, the display expression of a relation reference is not taken over

### ISSUE THREAD

**Issue by kingemir** [qgis/QGIS#38422]
**Describe the bug**

When embedding a layer, the display expression of a relation reference is not taken over

**How to Reproduce**

1. In project A, create layer _X_ with field _x_ and layer _Y_ with fields _y_id_ and _y_alt_. 
2. In project A, set a relation of strength "association" between Layers X and Y: Field _x_ of layer X is referencing to layer Y over its field y_id. 
2. In project A, go to properties of a layer X -> Attributes form -> x. Set Widget Type to "Relation reference", choose the relation which was set under step 2, type y_alt into the Display expression field. 
2. See how values of attribute x are replaced by the values y_alt in the table of X. That's the desired behaviour. 
3. Save project A.
4. Create project B. In project B, go to Layer -> "Embed Layers and Groups" and embed the layers X and Y from project A. 
5. Open attribute table of layer X in project B. Expected behaviour: values y_alt should be displayed in field x. Observed behaviour: field x displays its original value.

**QGIS and OS versions**

QGIS version | 3.14.15-Pi | QGIS code revision | d5114d2cfa
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | GroupStats; QgisModelBaker; quick_map_services; slyr; SpreadsheetLayers; db_manager; MetaSearch; processing

**Additional context**

**Comment by troopa81** [comment]
I didn't reproduce exactly the issue you reported, though I meet #38796 that I had just fixed 

A part from that, when you embed some layers from project, the relation is not automatically imported (maybe it should be, but I think it's more a Feature request than a bug), so when you open the widget you should see this 

![norelations](https://user-images.githubusercontent.com/14358135/93336905-aa6ef480-f828-11ea-8b0f-d09a7c733c83.png)

But, If I recreate the relation, everything just works fine. Here is a [test project](https://github.com/qgis/QGIS/files/5232120/bug_refwidget_embedlayer.zip)

**Comment by kingemir** [comment]
Thanks @troopa81 for testing and clarifying. True, when recreating the relation, it works. The problem is, we work with projects which contain each more than 30 relations. These projects are generated automatically by the plugin QGIS Model Baker, by the way. To re-enter each relation manually is out of question in our case. Do you know a way how to import relations manually? Ok, I will close the issue and open a feature request for automatic import of relations.

**Comment by troopa81** [comment]
> Do you know a way how to import relations manually? 

I don't see any way to import relations. 

> Ok, I will close the issue and open a feature request for automatic import of relations.

I think it could be nice to have a checkbox "Import embedded layers relation" in the embedded layers feature.

**Comment by kingemir** [comment]
@troopa81 Thanks for the reply. 

> I think it could be nice to have a checkbox "Import embedded layers relation" in the embedded layers feature.

Would you mind adding this comment to #38955 ? Thanks
