### ISSUE TITLE
Export map to kmz

### ISSUE THREAD

**Issue by HugoP27** [qgis/QGIS#38434]
**Feature description.**
Currently one can only export each individual layer in your QGIS project to kmL and not the whole map. There is also an issue when exporting point layers to kml, it doesn't keep the symbology nor the labels, it defaults to Google Earth's yellow pins. It would be awesome if this feature is added, there are plugins like the Garmin one and others, but they fall short of production grade tools. 

**Additional context**

I hope to start contributing to the development of QGIS very soon and submitting pull requests.

**Comment by gioman** [comment]
> Currently one can only export each individual layer in your QGIS project to kmL and not the whole map.

@HugoP27 you can export multiple layers in a project to a whatever format using the Processing toolbox in batch mode.



> There is also an issue when exporting point layers to kml, it doesn't keep the symbology nor the labels, it defaults to Google Earth's yellow pins. It would be awesome if this feature is added, there are plugins like the Garmin one and others, but they fall short of production grade tools.

this options do not work for you?

![Screenshot_20200823_175645](https://user-images.githubusercontent.com/1951107/90984000-1b90f400-e56a-11ea-8022-5cdac056144d.png)

**Comment by HugoP27** [comment]
Hi

Thank you for coming back to me. for some reason the points don't keep the symbology when I select the option shown in your screenshot.

Thanks will try the batch export

Kind regards
Hugo

________________________________

**Comment by gioman** [comment]
> or some reason the points don't keep the symbology

probably because of this explanation: https://issues.qgis.org/issues/13688#note-2

**Comment by HugoP27** [comment]
Jip Seems like it
