### ISSUE TITLE
Georeferencer plugin blocks files even after it is closed

### ISSUE THREAD

**Issue by MrChebur** [qgis/QGIS#38435]
**Describe the bug**
Georeferencer plugin locks files even after adding a new file or closing Georeferencer windows. 
The lock disappears after closing QGIS.

![Cg1YcVmmxR](https://user-images.githubusercontent.com/20655102/91005414-44f46300-e5f0-11ea-8719-5bf3af931199.gif)

**QGIS and OS versions**
QGIS version
3.14.15-Pi
QGIS code revision
d5114d2cfa
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
AppendFeaturesToLayer; 
DigitizingTools; 
FreehandRasterGeoreferencer; 
latlontools; 
MagicWand-master; 
qgsAzimuth; 
quick_map_services; 
valuetool; 
db_manager; 
MetaSearch; 
processing

**Comment by uclaros** [comment]
Just a note, the georeferencer is no longer a plugin!

**Comment by Pedro-Murteira** [comment]
@MrChebur I can no longer reproduce this issue on QGIS 3.22.3 (Windows 10). Are you still having this issue?

**Comment by MrChebur** [comment]
> @MrChebur I can no longer reproduce this issue on QGIS 3.22.3 (Windows 10). Are you still having this issue?

Indeed. Closed.
