### ISSUE TITLE
Broken Python

### ISSUE THREAD

**Issue by PCdurham** [qgis/QGIS#38449]
After trying to install third party python packages, QGIS no longer detects python support.  Processing tab is not available and in plugins, only 7 plugins are available in 'all'.  System tab in the plugin manager reports that no python support is detected.  Problem caused after the following:

1- run OS4GEO as admin
2-py3_env
3-pp install...

Problem persists even after I remove and re-install QGIS.  Tried 3.4.15, 3.10.8, 3.10.9 and 3.14.15.

**Comment by jef-n** [comment]
Which extension are you trying to install?

**Comment by PCdurham** [comment]
There is no processing toolbox at all. Installing sklearn in the python env seems to be causing the problem. Do I need to downgrade scipy?

**Comment by jef-n** [comment]
Installing sklearn worked fine for me - and also loads fine in `qgis-ltr-dev`.

**Comment by PCdurham** [comment]
Ok I'll move this problem to Stack Exchange.

**Comment by PCdurham** [comment]
posted here:
https://stackoverflow.com/questions/63592980/qgis-3-broken-disabled-python

The bug still persists.  When I uninstall the faulty version, python support remains broken.  It seems that the un-install does not clear something related to Python and the problem persists even after a clean install.

**Comment by gioman** [comment]
> The bug still persists.

@PCdurham have you tested on a different (clean) machine?

**Comment by jef-n** [comment]
see also #38441

**Comment by PCdurham** [comment]
I could test on other machines, but am a little reluctant since they have working installs of 3.4. But, I can confirm that a windows system restore followed by a clean install of 3.10.8.  the scipy issue mentioned above does not seem to affect 3.10.8.  
Thanks

**Comment by jef-n** [comment]
> The scipy issue mentioned above does not seem to affect 3.10.8.

And that should already be fixed in `qgis-ltr-dev` (see #38441)
