### ISSUE TITLE
Colliding keyboard shortcuts disappear

### ISSUE THREAD

**Issue by oskarlin** [qgis/QGIS#38459]
I have given a lot of tools new keyboard shortcuts in order to increase the speed of my workflow. One tool I often use is _Split features_. When I head to _Keyboard Shortcuts_ and search for _Split features_ I can see two tools with the same name. If I assign one of them everything is fine but when I restart the app, both these tools are assigned with my key for some reason which lead to the shortcut not working. If I remove the shortcut from one of them, it starts to work again. But same thing happens when I restart QGIS, both are assigned again. And so on.

I'm using 3.14.0-Pi on MacOS.

**Comment by DelazJ** [comment]
Do you have a plugin installed that adds a second "Split features" entry? I can see only one "split features" entry in 3.14.15 and 3.15 in my keyboard shortcuts list.

**Comment by oskarlin** [comment]
I have no idea. This his how it looks when I search for split:

<img width="420" alt="Screenshot 2020-08-27 at 13 12 55" src="https://user-images.githubusercontent.com/2736990/91435696-06b4a900-e867-11ea-8cd7-61a7858cb1e9.png">

**Comment by DelazJ** [comment]
Some of them are not default tools. Don't you have the "multipart split" plugin installed?

**Comment by oskarlin** [comment]
I have these plugins installed:

<img width="225" alt="Screenshot 2020-08-27 at 13 54 27" src="https://user-images.githubusercontent.com/2736990/91439171-d3751880-e86c-11ea-846a-8dc91c465c46.png">

**Comment by DelazJ** [comment]
The "Digitizing tools" (and not "multipart split" as I stated earlier) might be the culprit. It adds a tool named "Split Features" (btw with the same icon!?), reason why you find two in the results.
About the fix, I think it's the plugin that should either rename or remove this duplicate(?) tool. @bstroebl ?

**Comment by gioman** [comment]
I agree this is a 3rd party plugin issue, not QGIS's itself.
