### ISSUE TITLE
TimeController taking BOTH upper and lower limit into account of timeframes

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS#38468]
See also some info in this Thread:
https://lists.osgeo.org/pipermail/qgis-developer/2020-August/062066.html

The idea is that when you time-filter data with a frame of 60 minutes, that the lower limit is taken, but the upper limit is not
![Screenshot-20200827094104-971x539](https://user-images.githubusercontent.com/731673/91412020-74ea7300-e849-11ea-8801-82cec0d76bdb.png)

This is a project including data (6 points, with start and end time, frames of one hour):
[TimeTestDataProject.zip](https://github.com/qgis/QGIS/files/5134771/TimeTestDataProject.zip)

This is a movie to show that apparently the lower AND upper limit are taken into account:
[timedots_movie.zip](https://github.com/qgis/QGIS/files/5134775/timedots_movie.zip)

Not that you can see that the upper limit is taken into account using these configurations:
- Single Field with Date/Time with only t_start and a Event duration of 60 minutes
- Separate Fields for Start and End 
- Using expressions eg:  to_time(  "t_start" ) and  to_time(  "t_end" )
I did not test 'Separate field for Start and Event Duration'... but I think that will also have the issue

**Comment by roya0045** [comment]
does the mentioned PR fixes this?

**Comment by rduivenvoorde** [comment]
@roya0045 Nope, not yet. It is not clear to me where this issue exactly happens. The code (query) in the TimeController stuff is ok, debugging it I see that it is indeed taking the lower border into account (>=) and not the upper border (<), but still I see the issue...

**Comment by rduivenvoorde** [comment]
I think I have a clue what the issue is here:

The final QgsExpression is build up like this:

```
QStringLiteral( "(%1 %2 %3 AND %1 %4 %5) OR %1 IS NULL" ).arg( 
    QgsExpression::quotedColumnRef( mStartFieldName ),
    range.includeBeginning() ? QStringLiteral( ">=" ) : QStringLiteral( ">" ),
    dateTimeExpressionLiteral( range.begin() + QgsInterval( -mFixedDuration, mDurationUnit ) ),
    range.includeEnd() ? QStringLiteral( "<=" ) : QStringLiteral( "<" ),
    dateTimeExpressionLiteral( range.end() ) );
```
Meaning for a Range/Frame of QDateTime(2020-08-26 01:00:00.000 UTC) - QDateTime(2020-08-26 02:00:00.000 UTC)
AND a so called 'event duration time' of exact 3600 secs (1 hour),
the expression becomes(!):
```
"(\"t_start\" >= make_datetime(2020,8,26,0,0,0) AND \"t_start\" < make_datetime(2020,8,26,2,0,0)) OR \"t_start\" IS NULL"
```
which is actually wrong/too big (the filter frame becomes 2 hours big).

The crux (I think) is this part in the expression:
```
dateTimeExpressionLiteral( range.begin() + QgsInterval( -mFixedDuration, mDurationUnit ) )
```
I think(!) the idea is this that if an even has an duration of say one hour, that then it is not a moment, but a range, so instead of only taking the start in account, we mean: if the start of this event is in this frame, OR if event PLUS its duration is in this frame: count it as true. 
BUT the code now ADDS this interval not to the event, but SUBSTRACTS it from the frame-start, giving rise (in this case) of a frame window of 2 hours (while it should be) 1 hour.

I am not sure how to fix this... 
To fix this we should be able to say something like:
```(t_start + duration) >= frame_begin AND t_start < frame_end```
but in the expression we only give the datetime-attribute, so we cannot add or substract time there I think?

Does this sound plausible?

**Comment by rduivenvoorde** [comment]
Mmm, thinking and trying here. It has something todo with the edge's of the events.
What about IF an event has an duration (and will be resizing the frame) do NOT take the limits in account (so > and <).
BUT IF an event has NO duration, THEN you should take the limits (?? I think both) into account.

Does this makes sense? Or is still the crux that we are resizing the frames instead of the event's?

**Comment by nyalldawson** [comment]
Hmmm... I guess there's some room for both interpretations.

Either a fixed duration of an hour would mean that an event goes exactly from "3:00:00.0000 to 4:00:00.0000" or it goes from "3:00:00.00000 to 3:59:59.999999999".

If the later is the generally expected case then how about we change the expression to :

    "(\"t_start\" > make_datetime(2020,8,26,0,0,0) AND \"t_start\" < make_datetime(2020,8,26,2,0,0)) OR \"t_start\" IS NULL"

Does that solution work for you?

**Comment by nyalldawson** [comment]
(i.e. first comparison goes from >= to just >)

**Comment by rduivenvoorde** [comment]
> Either a fixed duration of an hour would mean that an event goes exactly from "3:00:00.0000 to 4:00:00.0000" or it goes from "3:00:00.00000 to 3:59:59.999999999".

@nyalldawson  I think the last, as if you do the otherway around then the 'limits/edges' have no clear place in one of the two former/next frames, they should be placed in both then. Although there is some ambiguity in using both 'event duration' and 'include end/begin' in this reasoning? @Samweli what you think?

So I'm going to test this:
```
return QStringLiteral( "(%1 > %2 AND %1 < %3) OR %1 IS NULL" ).arg( 
   QgsExpression::quotedColumnRef( mStartFieldName ),
   dateTimeExpressionLiteral( range.begin() + QgsInterval( -mFixedDuration, mDurationUnit ) ),
    dateTimeExpressionLiteral( range.end() ) );
```
This at least fixes #38468 but I will try to break it with other setups :-)

**Comment by timlinux** [comment]
We had a long discussion about the expected behaviour and these diagrams summarise the behaviour:

The current behaviour:

![image](https://user-images.githubusercontent.com/178003/107399261-68588f00-6af8-11eb-96ad-a12098846765.png)


Proposed behaviour:


![image](https://user-images.githubusercontent.com/178003/107399137-4d861a80-6af8-11eb-849a-530a67749e94.png)


![image](https://user-images.githubusercontent.com/178003/107399100-4101c200-6af8-11eb-99b8-c4b474153c75.png)

**Comment by rduivenvoorde** [comment]
The original fix for this did not fix all possible temporal cases, so reopening...
