### ISSUE TITLE
Blocking of SAGA & GRASS batch files by MS AppLocker

### ISSUE THREAD

**Issue by MattHec** [qgis/QGIS#38469]
Dear QGIS Developers,

due to recent security measures of my organization, execution of programs (exe, bat, etc…) is only possible in a certified folder e.g. C:/Programs/...

The SAGA integration in QGIS is based on the creation and execution of a temporal .bat file (“SAGA_batch_job.bat”) createt in %OSDRIVE%\USERNAME\AppData\QGIS\QGIS3\PROFILES\DEFAULT\PROCESSING\SAGA_BATCH_JOB.BAT calling SAGA from the command prompt with the individual parameters of the respective tool.
Similarly GRASS uses a .bat file (Grass_Batch_job.cmd) for some tools and OTB and others also use executable files in folders outside the QGIS programm folder structure.

These batch files/executable files get blocked by the Microsoft Windows AppLocker
Is there a possibility to relocate these batch files within the C/Programs/QGIS3.xx/somewhere… folder to avoid blocking by infamous applocker? Certifcation and excemption of these files by my organisation is apparently not possible.

Thank for your help! 
Matthias 

e.g.
![grafik](https://user-images.githubusercontent.com/70195585/91413409-5d13ee80-e84b-11ea-9442-af10b9d55b95.png)

**Comment by gioman** [comment]
> Is there a possibility to relocate these batch files within the C/Programs/QGIS3.xx/somewhere… folder to avoid blocking by infamous applocker?

@MattHec please raise your question on the developers mailing list.
