### ISSUE TITLE
Fields added using vector properties doesn't show on the forms tab

### ISSUE THREAD

**Issue by SrNetoChan** [qgis/QGIS#38463]
**Describe the bug**

When, in the vector layer properties, one creates a new field (virtual or not), switching to the Forms tab, the new fields don't show immediately. Clicking Apply does not solve it.

You need to close the layer properties and open it again.

Not sure if it's a bug or feature report.

**How to Reproduce**

![Peek 2020-08-26 15-51](https://user-images.githubusercontent.com/3607161/91321272-5ab38500-e7b6-11ea-9b37-32a945013639.gif)

**QGIS and OS versions**

QGIS version | 3.10.9-A Coruña | QGIS code revision | bf47e9d3e1
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 10.12 (Ubuntu 10.12-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Ubuntu 18.04.5 LTS
Active python plugins | timemanager; socarto_recart_tools; db_manager; processing

**Additional context**

**Comment by timlinux** [comment]
IMHO a bug - been a common frustration for me in the past too...

**Comment by DelazJ** [comment]
See #26350

**Comment by SrNetoChan** [comment]
> See #26350

Let's close this one then.
