### ISSUE TITLE
'Select by polygon' doesn't select anymore geometries with errors

### ISSUE THREAD

**Issue by tjukanovt** [qgis/QGIS#38460]
**Describe the bug**
When trying to do a seleciton on a layer, not all features inside the drawn polygon are being selected. 

**How to Reproduce**

1. Add layer (mine is a polygon GeoPackage in EPSG:3879
2. Click on 'Select features by area/polygon'
3. Try to select features
4. See error in the screenshot below

**QGIS and OS versions**
QGIS version 3.14.15-Pi running on Windows 10. No plug-ins installed in this fresh profile.

**Additional context**

Here's how it **should work** and how it works in 3.10:
![select_310](https://user-images.githubusercontent.com/13899537/91290874-ddc7e180-e79c-11ea-93d0-c74203d2a3ab.gif)

Here's how it "works" in the latest 3.14:
![select_314](https://user-images.githubusercontent.com/13899537/91290885-e1f3ff00-e79c-11ea-831e-837701d95c16.gif)

**Comment by gioman** [comment]
>     1. Add layer (mine is a polygon GeoPackage in EPSG:3879

@tjukanovt please attach your dataset

**Comment by tjukanovt** [comment]
@gioman You can download that here: https://drive.google.com/file/d/1riNfISQb9xNXIfWjJITNgyeJC4gK4GpN/view?usp=sharing

**Comment by tjukanovt** [comment]
Actually my guess at the moment is that it has something to do with invalid geometries.

**Comment by gioman** [comment]
> Actually my guess at the moment is that it has something to do with invalid geometries.

@tjukanovt good catch, seems is really the case. Anyway is a regression.

**Comment by tjukanovt** [comment]
Thanks for changing the title to a more descriptive one. Just noticed that this appears also in the 3.12 LTR
