### ISSUE TITLE
Minor GUI glitch: Edit menu showing Select and Add xxxx menu items while not usable

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS#38470]
This is a minor GUI glitch, but I happened to search for something in QGIS while I did not have any project opened (see screenshot), and then in the Edit menu there were some menu-times usable (well not sub items), while I think these should be deactivated:

- Select (there is not project, nor features so nothing to select)? In this menu-item there are sub-menu items also activated

- The Add Circle/Rectangle/Regular Polgyon/Ellipse/Annotation items are activated (though they cannot do anything as their sub-items ARE deactivated.

![Screenshot-20200827101746-1141x744](https://user-images.githubusercontent.com/731673/91415794-d52fe380-e84e-11ea-9e9b-90ebc77e3913.png)

**Comment by DelazJ** [comment]
@rduivenvoorde I propose a PR for this, in which I did not disable the "Annotations"; I think they can be used without any layer
