### ISSUE TITLE
Layer Error

### ISSUE THREAD

**Issue by daveQGIS** [qgis/QGIS#38477]
I am going through Steps 5 & 6 of the training, but I do not see that map background in QGIS program. I added the layer correctly (I reviewed those steps 3 or 4 times to be sure). Now, there is an exclamation point in a triangle, and when I click on it, a window opens labelled (Layer Error) and the text in the window states:

"Network error: Error transferring http://services.arcgisonline.com/arcgis/rest/services/World_Imagery/MapServer/export?bbox=-88.156369,41.767919,-88.154548,41.768861&size=1617,837&format=PNG32&layers=show:&transparent=true&f=image - server replied: Internal Server Error"

I tried closing the program and reopening, turning my computer off and back on, but the issue persists. Can you please help me get this fixed?

**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by roya0045** [comment]
The doc is possibly outdated or the source has changed. This might be more of a documentation issue than QGIS itself. @DelazJ @gioman could it be a doc issue?

**Comment by DelazJ** [comment]
> I am going through Steps 5 & 6 of the training, but I do not see that map background in QGIS program

@daveQGIS can you point the doc you are referring to, please?

**Comment by gioman** [comment]
>  Internal Server Error"

@daveQGIS it is the remote service that is not working, not QGIS. The service eventually must be replaced in QGIS docs, please file a ticket against QGIS docs repository.

**Comment by DelazJ** [comment]
> The service eventually must be replaced in QGIS docs, please file a ticket against QGIS docs repository.

Not sure it's docs issue. I don't recall we have any mention of arcgisonline service in our docs, reason why I was asking the url of the training.

**Comment by daveQGIS** [comment]
Hi Tyler,

Please see that email chain below. I removed the "World Imagery" layer (as
you and I discussed over the phone) and tried Section 3 of the training. It
didn't seem to work, so I removed the layer again and tried a 3rd time.
Still nothing, unfortunately. Here are the screenshots of what I am seeing.
The first is the error icon (triangle with exclamation point inside).

[image: image.png]

When I click on the error, here is the window that pops up:

[image: image.png]

Any ideas on how this can be fixed? Your help is greatly appreciated!

Best Regards,

*Dave Kinder*
*(951) 533-0850*

<http://enhancedscanning.com/>
*For your convenience, on the Enhanced Scanning website, you can download
our W-9 <https://enhancedscanning.com/downloadable-forms/>, a Standard COI
<https://enhancedscanning.com/downloadable-forms/>, or request a Custom COI
<https://enhancedscanning.com/downloadable-forms/>.*
