### ISSUE TITLE
QGIS forgets the project CRS (and set the project to "No CRS")

### ISSUE THREAD

**Issue by jguelat** [qgis/QGIS#38473]
QGIS forgets the project CRS when creating new documents and set it to "No CRS". Here's how to reproduce the bug with a fresh profile:

1. Open QGIS and create a new empty project (by clicking on the icon in the toolbar or Project -> New or Ctrl-N).
2. Save the empty project (you can also add some layers, this doesn't matter).
3. Close QGIS and open again the freshly saved project.
4. The project CRS is gone.

Suprisingly, this doesn't happen if you open QGIS and directly save the document (without clicking on the new document icon first).

QGIS: 3.10.9 and 3.14.15
OS: Windows 10

**Comment by jguelat** [comment]
I guess the Projections/Transformations label would be appropriate, too

**Comment by pigreco** [comment]
I confirm

**Comment by uclaros** [comment]
I cannot reproduce on Linux Debian with a few weeks old master build (df2a311782).
I tried with setting the default crs for new projects to 4326, 2100 or 'first layer added' in combination with 4326 and 2100.
In all the above cases the project loaded with the correct crs.
Maybe your default crs choice matters?

**Comment by jguelat** [comment]
I tried with a fresh new profile with a default crs set to 4326 and with my own profile where the default is 2056 and it happens with both of them.

**Comment by uclaros** [comment]
Maybe it's a windows only thing?

**Comment by andreasneumann** [comment]
Same here on Linux with current master. The projection setting is gone after reopening of the project.

**Comment by uclaros** [comment]
I rebuilt master and now I can reproduce it too!
So it could have been introduced somewhere between 655c2ca and d5114d2

**Comment by nyalldawson** [comment]
I'm also unable to reproduce -- could someone post some more workflows to demonstrate this? Or a sample project?

**Comment by uclaros** [comment]
The easiest way for me to replicate is:
1. Open QGIS (new clean profile)
2. Ctrl+N, Ctrl+S, type name, save
3. Project > Open Recent > pick first entry

The *New project* (ctrl+n) step is crucial.
Here are two sample projects: 
[BugReport.zip](https://github.com/qgis/QGIS/files/5254240/BugReport.zip)

The first one (save.qgs) is produced by simply clicking save when QGIS starts. When reopened, CRS is correctly set.
The second one (new_save.qgs) is produced by doing ctrl+n and then ctrl+s when QGIS starts. When reopened, CRS is missing.

A diff shows that the second one is missing the following lines:
```
    <SpatialRefSys>
      <ProjectionsEnabled type="int">1</ProjectionsEnabled>
    </SpatialRefSys>
```
Adding those by hand resolves the issue.

**Comment by PeterDrexel** [comment]
Is still an Isuue in 3.16 on Windows 10
