### ISSUE TITLE
gdal2tiles fails when the input raster is very small (7x8)

### ISSUE THREAD

**Issue by Nodjo** [qgis/QGIS#38474]
I want to export tiles from a very small raster (7x8) and the tiles are all transparent.

I found out that if I translate the raster to increase its size (say give it a width of 100), then the output is as expected.

Here's my code (I'm using gdal2tiles python bindings but I've also reproduced this issue with multiple versions of gdal2tiles.py)

`gdal2tiles.generate_tiles(in_raster_path, out_dir, zoom='12-24')`

I'm attaching the raster file
[bug_gdal2tiles.zip](https://github.com/qgis/QGIS/files/5136771/bug_gdal2tiles.zip)

**Comment by gioman** [comment]
> but I've also reproduced this issue with multiple versions of gdal2tiles.py

@Nodjo if the GDAL tool behave the same then is not a QGIS issue (as QGIS is "just" a GUI for GDAL command line utilities).

**Comment by roya0045** [comment]
What if you don't set the zoom param?

**Comment by alexbruy** [comment]
This should be asked in the GDAL support channels, as code snippet is a pure GDAL code.
