### ISSUE TITLE
Processing/GDAL "GRID (IDW)" do not work with CSV as input

### ISSUE THREAD

**Issue by AlaaSmati** [qgis/QGIS#38485]
Hi all,
I keep getting the same error message while trying to make an interpolation Grid (Inverse distance to a power) on QGIS v3.10.9. I've already tried with different versions of QGIS but I received the same error message everytime. I also tried the "save to file" and "save to temporary file", same issue as well. Also tried with different .csv files, same :( Any idea to fix it please? 
Log below.

QGIS version: 3.10.9-A Coruña
QGIS code revision: bf47e9d3e1
Qt version: 5.11.2
GDAL version: 3.0.4
GEOS version: 3.8.1-CAPI-1.13.3
PROJ version: Rel. 6.3.2, May 1st, 2020
Processing algorithm…
Algorithm 'Grid (Inverse distance to a power)' starting…
Input parameters:
{ 'ANGLE' : 0, 'DATA_TYPE' : 5, 'EXTRA' : '', 'INPUT' : 'file:///C:/Users/IBTISSEM/Desktop/Desktop/Env%20Sc%202/Thesis/QGIS/RMSslope.csv?type=csv&maxFields=10000&detectTypes=yes&xField=longitude&yField=latitude&zField=RMSslope&crs=EPSG:4326&spatialIndex=no&subsetIndex=no&watchFile=no', 'MAX_POINTS' : 0, 'MIN_POINTS' : 0, 'NODATA' : 0, 'OPTIONS' : '', 'OUTPUT' : 'TEMPORARY_OUTPUT', 'POWER' : 2, 'RADIUS_1' : 0, 'RADIUS_2' : 0, 'SMOOTHING' : 0, 'Z_FIELD' : 'RMSslope' }

GDAL command:
gdal_grid -l None -zfield RMSslope -a invdist:power=2.0:smothing=0.0:radius1=0.0:radius2=0.0:angle=0.0:max_points=0:min_points=0:nodata=0.0 -ot Float32 -of GTiff file:///C:/Users/xxx/Desktop/Desktop/Env%20Sc%202/Thesis/QGIS/RMSslope.csv?type=csv&maxFields=10000&detectTypes=yes&xField=longitude&yField=latitude&zField=RMSslope&crs=EPSG:4326&spatialIndex=no&subsetIndex=no&watchFile=no C:/Users/xxx/AppData/Local/Temp/processing_b68fa59a58e04149a54f468513abd38b/8c2432964c95473d8f0789941d21a595/OUTPUT.tif
GDAL command output:

FAILURE: No output file specified.

Usage: gdal_grid [--help-general]

[-ot {Byte/Int16/UInt16/UInt32/Int32/Float32/Float64/

CInt16/CInt32/CFloat32/CFloat64}]

[-of format] [-co "NAME=VALUE"]

[-zfield field_name] [-z_increase increase_value] [-z_multiply multiply_value]

[-a_srs srs_def] [-spat xmin ymin xmax ymax]

[-clipsrc <xmin ymin xmax ymax>|WKT|datasource|spat_extent]

[-clipsrcsql sql_statement] [-clipsrclayer layer]

[-clipsrcwhere expression]

[-l layername]* [-where expression] [-sql select_statement]

[-txe xmin xmax] [-tye ymin ymax] [-outsize xsize ysize]

[-a algorithm[:parameter1=value1]*] [-q]

<src_datasource> <dst_filename>

Available algorithms and parameters with their defaults:

Inverse distance to a power (default)

invdist:power=2.0:smoothing=0.0:radius1=0.0:radius2=0.0:angle=0.0:max_points=0:min_points=0:nodata=0.0

Inverse distance to a power with nearest neighbor search

invdistnn:power=2.0:radius=1.0:max_points=12:min_points=0:nodata=0

Moving average

average:radius1=0.0:radius2=0.0:angle=0.0:min_points=0:nodata=0.0

Nearest neighbor

nearest:radius1=0.0:radius2=0.0:angle=0.0:nodata=0.0

Various data metrics

<metric name>:radius1=0.0:radius2=0.0:angle=0.0:min_points=0:nodata=0.0

possible metrics are:

minimum

maximum

range

count

average_distance

average_distance_pts

Linear

linear:radius=-1.0:nodata=0.0

'maxFields' is not recognized as an internal or external command,

operable program or batch file.

'detectTypes' is not recognized as an internal or external command,

operable program or batch file.

'xField' is not recognized as an internal or external command,

operable program or batch file.

'yField' is not recognized as an internal or external command,

operable program or batch file.

'zField' is not recognized as an internal or external command,

operable program or batch file.

'crs' is not recognized as an internal or external command,

operable program or batch file.

'spatialIndex' is not recognized as an internal or external command,

operable program or batch file.

'subsetIndex' is not recognized as an internal or external command,

operable program or batch file.

'watchFile' is not recognized as an internal or external command,

operable program or batch file.

Execution completed in 0.23 seconds
Results:
{'OUTPUT': 'C:/Users/xxx/AppData/Local/Temp/processing_b68fa59a58e04149a54f468513abd38b/8c2432964c95473d8f0789941d21a595/OUTPUT.tif'}

Loading resulting layers
The following layers were not correctly generated.<ul><li>C:/Users/xxx/AppData/Local/Temp/processing_b68fa59a58e04149a54f468513abd38b/8c2432964c95473d8f0789941d21a595/OUTPUT.tif</li></ul>You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.

**Comment by gioman** [comment]
It happens with the GDAL tool (not QGIS's one) and only if the input is a CSV, possibily affects also other GDAL tools. Tested on both Linux and Windows.

On Windows there are also some additional error message:

```
'maxFields' is not recognized as an internal or external command,

operable program or batch file.

'detectTypes' is not recognized as an internal or external command,

operable program or batch file.

'xField' is not recognized as an internal or external command,

operable program or batch file.

'yField' is not recognized as an internal or external command,

operable program or batch file.

'crs' is not recognized as an internal or external command,

operable program or batch file.

'spatialIndex' is not recognized as an internal or external command,

operable program or batch file.

'subsetIndex' is not recognized as an internal or external command,

operable program or batch file.

'watchFile' is not recognized as an internal or external command,

operable program or batch file.
```

**Comment by AlaaSmati** [comment]
Can this be fixed from the user side? Or is there any alternatives or work around that can help please?

**Comment by gioman** [comment]
> Or is there any alternatives or work around

@AlaaSmati use the QGIS native tool, not GDAL's or do not use CSVs as inputs (save them as SHP or GPKGs).

**Comment by alexbruy** [comment]
Issue with CSV imputs was already reported in #31267, so I close this.
