### ISSUE TITLE
QGIS fails to import scipy.special python module

### ISSUE THREAD

**Issue by jakimowb** [qgis/QGIS#38489]
The current OSGeo4W QGIS python shell fails to import the [scipy.special](https://docs.scipy.org/doc/scipy-1.4.1/reference/tutorial/special.html) module. Interestingly this happens in the QGIS python shell only, but not if the import is called in the OSGeo4W CLI python (without the QGIS GUI).

**How to Reproduce**
```python
import scipy
scipy.version.version
'1.4.1'
import scipy.special
Traceback (most recent call last):
  File "C:\OSGEO4~1\apps\Python37\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\scipy\special\__init__.py", line 634, in <module>
    from . import _ufuncs
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.
```

**QGIS and OS versions**

QGIS version | 3.14.15-Pi | QGIS code revision | d5114d2cfa
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins |

**Comment by Gustry** [comment]
Another duplicate from these last few days https://github.com/qgis/QGIS/issues?q=is%3Aissue+scipy+is%3Aclosed ?
Especially https://github.com/qgis/QGIS/issues/38372

**Comment by jakimowb** [comment]
Ah ok, sorry for open this topic again.
