### ISSUE TITLE
Print Composer Preview atlas resets chosen attribute table attributes

### ISSUE THREAD

**Issue by py-qgis-user** [qgis/QGIS#38481]
**Describe the bug**
I have a print composer layout, in which i linked the Map, Text and Attribute Tables to the current atlas feature.
I have a bunch of Attribute Tables, which each only give 1 attributes (set by clicking the 'Attributes...' button from the image below and removing all columns except for one) of the atlas layer. When I print the atlas or preview it now everything is fine.

When I save the project, close Qgis and restart it again the problem occurs: at first the Print Composer layout seems ok.
Yet, when I click then click 'Preview Atlas', all the Attribute Tables reset and show all the columns. (hence forcing me to fix them all again).

![image](https://user-images.githubusercontent.com/66588460/91531642-66fe2600-e90d-11ea-9ae1-237cf228aac1.png)

**QGIS and OS versions**
Windows10 64bit

QGIS version
3.4.5-Madeira
QGIS code revision
89ee6f6e23
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
2.4.0
Running against GDAL/OGR
2.4.0
Compiled against GEOS
3.7.0-CAPI-1.11.0
Running against GEOS
3.7.0-CAPI-1.11.0 673b9939
PostgreSQL Client Version
9.2.4
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
520
Running against PROJ
5.2.0

**Comment by Gustry** [comment]
> 3.4.5-Madeira

This is more than one year old. You should update and check if the problem still exists in current maintained versions.

**Comment by py-qgis-user** [comment]
> > 3.4.5-Madeira
> 
> This is more than one year old. You should update and check if the problem still exists in current maintained versions.

Company computer sadly, so not possibility to update.
Maybe someone can test, to see if we can close this issue?

**Comment by roya0045** [comment]
@py-qgis-user you might be able to test an MXE build. https://github.com/qgis/QGIS/actions?query=workflow%3A%22Windows+cross+build+with+MXE%22 choose one, get artifact, unzip twice, use qgis.exe

**Comment by gioman** [comment]
>  Maybe someone can test, to see if we can close this issue?

@py-qgis-user can you provide a sample project with data?

**Comment by py-qgis-user** [comment]
I was able to test on 3.12
After fixing it in there and saving, the issue is gone.
-> Seems to be fixed
