### ISSUE TITLE
QGIS crashes when using GRASS tool v.to.rast.attr

### ISSUE THREAD

**Issue by brucewiland** [qgis/QGIS#38496]
## User Feedback

Everytime I try to use v.to.rast.attr in the Grass 7.8.3 tools of QGIS 3.10.9, the program crashes when I select an input vector map in the dropdown box. The input vector map is created in the step just before this using v.in.ogr.qgis and completes successfully.

## Report Details

**Crash ID**: [2c38da36e8c8fe1a5a9e43addacef9648498e765](https://github.com/qgis/QGIS/search?q=2c38da36e8c8fe1a5a9e43addacef9648498e765&type=Issues)

**Stack Trace**
<pre>
RtlRaiseStatus :
 ?? ::FNODOBFM::`string' :
longjmp :
G_fatal_error :
G_getenv :
db_read_dbmscap :
db_start_driver :
db_start_driver_open_database :
QgsGrassVectorLayer::fields qgsgrassvector.cpp:124
QgsGrassModuleInput::currentFields qgsgrassmoduleinput.cpp:1076
QgsGrassModuleVectorField::updateFields qgsgrassmoduleparam.cpp:1120
QMetaObject::activate :
QgsGrassModuleInput::onLayerChanged qgsgrassmoduleinput.cpp:1242
QMetaObject::activate :
QWidgetLineControl::`default constructor closure' :
QComboBox::setCurrentIndex :
QComboBox::setCurrentIndex :
QWidgetLineControl::`default constructor closure' :
QMetaObject::activate :
QAbstractItemModel::endInsertRows :
QStandardItemModel::insertRows :
QStandardItem::insertRow :
QStandardItemModel::insertRow :
QComboBox::insertItem :
QgsGrassModuleInput::onChanged qgsgrassmoduleinput.cpp:1180
QMetaObject::activate :
QComboBox::qt_static_metacall :
QMetaObject::activate :
QLineEdit::qt_static_metacall :
QMetaObject::activate :
QWidgetLineControl::finishChange :
QWidgetLineControl::internalSetText :
QComboBox::setCurrentIndex :
QComboBox::setCurrentIndex :
QgsGrassModuleInputComboBox::hidePopup qgsgrassmoduleinput.cpp:606
QComboBoxPrivateContainer::eventFilter :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1606
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.9-A Coru�a
QGIS code revision: bf47e9d3e1
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by gioman** [comment]
@brucewiland the GRASS plugin is basically abandoned, if possible use the GRASS tools in the QGIS/Processing toolbox. Anyway I tested v.to.rast.at on QGIS 3.14.15 on Windows and it was fine for me. Please attach a sample of the problematic data.

**Comment by brucewiland** [comment]
I downloaded and installed QGIS 3.14.15. It  also crashed. Attached is a zip file containing a test project file, the shapefile, and the GRASS folder. 
[test.zip](https://github.com/qgis/QGIS/files/5188233/test.zip)

**Comment by gioman** [comment]
> I downloaded and installed QGIS 3.14.15. It also crashed. Attached is a zip file containing a test project file, the shapefile, and the GRASS folder.
> [test.zip](https://github.com/qgis/QGIS/files/5188233/test.zip)

@brucewiland still works here

![Screenshot_20200908_194927](https://user-images.githubusercontent.com/1951107/92516023-784c0a00-f20c-11ea-9715-2484e425e218.png)

so there is something else at play.

**Comment by brucewiland** [comment]
@gioman that is interesting. Every time I select an input vector map in the dropdown box, it immediately hangs up and crashes. The crash report details are essentially the same every time as those I show in my original post.  Is there anything in the crash report that would give a clue to what is going on? It just occurred to me that the files are on a network drive. I wonder if that might have something to do with it. I will try putting the files on the local drive and see what happens. I will also try to install QGIS on another computer and see if the same thing happens.

**Comment by brucewiland** [comment]
@gioman I ran it on my other computer (Windows 10) and it worked, but it still crashes on the Windows 7 computer. I don't know if it is Windows 7 itself causing the problem or something else related to my computer. If it is not Windows 7 itself, I don't know where to look to solve the problem unless there is something in the crash report stack trace that provides a clue.

**Comment by gioman** [comment]
@brucewiland 

> If it is not Windows 7 itself, I don't know where to look to solve the problem unless there is something in the crash report stack trace that provides a clue.

ok, but sorry we have to close this as is likely to be a local issue until proven otherwise.
