### ISSUE TITLE
Problems with QGIS

### ISSUE THREAD

**Issue by adolfholp** [qgis/QGIS#38491]
## User Feedback

Cargué un MDE, y traté de mostrarlo completo, el programa comenzó a no mostrar el mapa base y después de interntar mostrarlo, apareció esta ventana.

## Report Details

**Crash ID**: [9b2fcd69d660c43526132af775dc4a6af0c5765b](https://github.com/qgis/QGIS/search?q=9b2fcd69d660c43526132af775dc4a6af0c5765b&type=Issues)

**Stack Trace**
<pre>
memcpy memcpy.asm:194
QgsWmsProvider::readBlock qgswmsprovider.cpp:928
QgsRasterDataProvider::block qgsrasterdataprovider.cpp:201
QgsSingleBandColorDataRenderer::block qgssinglebandcolordatarenderer.cpp:62
QgsBrightnessContrastFilter::block qgsbrightnesscontrastfilter.cpp:118
QgsHueSaturationFilter::block qgshuesaturationfilter.cpp:123
QgsRasterResampleFilter::block qgsrasterresamplefilter.cpp:162
QgsRasterProjector::block qgsrasterprojector.cpp:810
QgsRasterIterator::readNextRasterPartInternal qgsrasteriterator.cpp:130
QgsRasterDrawer::draw qgsrasterdrawer.cpp:60
QgsRasterLayerRenderer::render qgsrasterlayerrenderer.cpp:272
QgsMapRendererParallelJob::renderLayerStatic qgsmaprendererparalleljob.cpp:16707566
QtConcurrent::MapKernel<QList<QPair<QgsVectorDataProvider *,QgsFeatureRequest> >::iterator,QtConcurrent::FunctionWrapper1<void,QPair<QgsVectorDataProvider *,QgsFeatureRequest> const &> >::runIteration qtconcurrentmapkernel.h:68
QtConcurrent::MapKernel<QList<QgsImageOperation::ImageBlock>::iterator,QgsImageOperation::ProcessBlockUsingPixelOperation<QgsImageOperation::HueSaturationPixelOperation> >::runIterations qtconcurrentmapkernel.h:77
QtConcurrent::IterateKernel<QList<QgsImageOperation::ImageBlock>::iterator,void>::forThreadFunction qtconcurrentiteratekernel.h:256
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
__RtlUserThreadStart :
_RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.8-A Coru�a
QGIS code revision: d09a4f2388
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment]
Please post again in English, adding the **detailed** steps to replicate. If necessary attach a sample project with data. Also please try with a new QGIS profile.
