### ISSUE TITLE
Cannot save changes to geopackage layer

### ISSUE THREAD

**Issue by gubuntu** [qgis/QGIS#38495]
**Describe the bug**

I am making attribute edits to a geopackage layer but cannot save them:

```
Could not commit changes to layer countries

Errors: ERROR: 1 attribute value change(s) not applied.
  
  Provider errors:
      OGR error setting feature 253: sqlite3_step() failed:
      ne_10m_admin_0_countries.geometry violates Geometry constraint [geom-type or SRID not allowed]
      OGR error committing transaction: sqlite3_exec(COMMIT) failed: cannot commit - no transaction is active
```
also
``
 WARNING    Unbalanced call to leaveUpdateMode() w.r.t. enterUpdateMode()
```
The layer draws fine and the geometry is MultiPolygon, 4326.

**QGIS and OS versions**

QGIS version | 3.14.15-Pi | QGIS code revision | d5114d2cfa
-- | -- | -- | --
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.28.0 | Running against SQLite | 3.28.0
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS 10.15
Active python plugins | ORStools; SpreadsheetLayers; lrs; DataPlotly; quick_map_services; stac_browser; Discovery; qfieldsync; qchainage; OSMDownloader; qgis_resource_sharing; openlayers_plugin; Projestions; mmqgis; processing_circuitscape; mapswipetool_plugin; Mergin; travel_time_platform_plugin; nominatim_locator_filter; geocatbridge; timemanager; processing; db_manager; MetaSearch

**Comment by gioman** [comment]
@gubuntu just to be sure is not plugin related... please test with a new QGIS profile.

**Comment by RyanJMcGowan** [comment]
I often get exactly this error. I am on a network environment, and I suspect when the network drive is sleeping, it garbage collects active connections. It only seems to be a problem on longer editing sessions. The key error is "failed: cannot commit - no transaction is active"
The workaround I have been doing is to copy all the shapes into a new layer and save that layer. Then replace the original geopackage with the new geopackage and restart QGIS.

**Comment by Pedro-Murteira** [comment]
I'm not being able to reproduce this issue on QGIS 3.22.4 and 3.24.0. @gubuntu Hello, did you come across this issue in more recent releases?

**Comment by gubuntu** [comment]
I haven't tried but happy to close.

**Comment by RyanJMcGowan** [comment]
I'm on 3.24.0 and had this issue as recent as this week.

**Comment by Skipper-is** [comment]
I'm using 3.40.8 and can replicate. It also seems to happen when having a long editing session (and not saving in between). Also over a network drive same as @RyanJMcGowan. His workaround works, but is far from ideal. Can it not just try a reconnect if that happens?

**Comment by RyanJMcGowan** [comment]
I'm on 3.36 and haven't had this issue in some time, probably because I replaced my server with one that doesn't hate me.

I am however still able to replicate in 3.36:

1. Create a vector geopackage layer.
2. Create some geometry.
3. Release your IP from command prompt. Or disconnect from Wifi, etc.
4. Keep editing.
5. Reconnect.
6. Save edits.

The layer will be unable to save any of the edits, permanently. There is no way to reconnect to the geopackage without losing edits. A new layer has to be created and the geometry copied over, with the old layer closing without saving.
