### ISSUE TITLE
Saving OSM PBF datasource to GPKG very slow

### ISSUE THREAD

**Issue by soli004** [qgis/QGIS#38492]
Download OSM from geofabrik.de (sweden_latest.osm.pbf)
Open the file via "Add vector layer"
Select "multipolygons" only
Select features after open in QGIS:
"place" = 'island' OR "place" = 'islet'
Result 43470 features selected
Save selected features to GeoPackage, saving time = + 20 hours
Left it overnight and after 9 hours of saving it says 40% and +22 hours more to go!!!
No other layers in QGIS (to save memory and processing power)
Total memory used during saving process = 8 GB, so there is no memory problem 
Something must be wrong here...

Download link
http://download.geofabrik.de/europe/sweden.html

Configuration:
QGIS version 3.14.15-Pi
MacOS Mojave ver. 10.14.6
MacBookPro 13-inch
Processor: 3.1 GHz i7
Memory: 16 GB

**Comment by gioman** [comment]
@soli004 

Seems to work fine on LTR on Linux.
It took about 5/6 minutes, which is certainly more than expected. Possibly it took certainly more time it took with ogr2ogr:

`ogr2ogr -f GPKG sweden.gpkg sweden-latest.osm.pbf multipolygons -sql "SELECT * FROM multipolygons WHERE "place" = 'island' OR "place" = 'islet'"
`

In general adding/working with a (large?) PBF datasource is incredibly slow, from rendering, to filtering and opening the attribute table.

Testing a filter against this datasource it always return an error, but the filter can be applied regardless.

**Comment by soli004** [comment]
After 24 hours of saving I killed the process and checked the file size (38 MB!) That is extremely slow, would probably never end...

I will have a go with LTR to see if that is better. I have done this before so it is probably version specific, but as said, large PBF datasource is incredible slow.....

**Comment by soli004** [comment]
Hmmm... did try to open the filed that was saved so far. I could suprisingly open it, the gpkg file had 29786 objects... nearly done... ;)

**Comment by gioman** [comment]
> nearly done

check with QGIS LTR if possible.

**Comment by soli004** [comment]
QGIS LTR tested, no changes...
6 min to display map on canvas
2 min for select features
10 min into saving the percentage start showing
1% Estimated time remaining: 1523:55 minutes, the numbers continue going up.... + 1600: now...

**Comment by gioman** [comment]
so this is probably a macos only issue.

**Comment by soli004** [comment]
Probably, I do have a win machine, will test tomorrow morning....

**Comment by soli004** [comment]
As the windows machine was next to me...
QGIS LTR
Windows 8.1 Enterprise
Processor 3 Ghz i7
Memory 16GB
Similar time for display and select features...

15 minutes into saving, still no percentage and estimated time remaining info...

I consider this to be macOS and Windows problem what I can see....

**Comment by gioman** [comment]
I will test macOS and Win tomorrow, Linux is "fine" saving, but the general slowness is really a pain. Not sure if this is a regression compared to QGIS 2.*.

**Comment by soli004** [comment]
Any feedback!?

**Comment by gioman** [comment]
> Any feedback!?

@soli004 slow but saves ok also on Windows.

**Comment by soli004** [comment]
Another test on third Windows machine. Same configuration as previous.

After 20 minutes it start showing 1% Estimated time remaining: 2205:35 minutes.... and the numbers are growing....
Spend two days for saving is definitely not ideal.... your configuration must be way better than mine...

**Comment by gioman** [comment]
> your configuration must be way better than mine

@soli004 actually I tested on a pedestrian Windows virtual machine. You have something else at play, please test with a new QGIS profile.

**Comment by soli004** [comment]
New QGIS profile
No difference, same as previous tests.
Will downgrade to QGIS 3.4 to see if that helps.....

**Comment by soli004** [comment]
QGIS 3.4.15 LTR
Window 8.1 Enterprise
Same issue as above, no difference...

**Comment by soli004** [comment]
QGIS 2.18.15
Same Windows machine...
Slow but was able to save the selected features in 2-3 minutes, huge difference...

**Comment by gioman** [comment]
let's see what others see in their machines.

**Comment by soli004** [comment]
There seems to be a workaround to be able to save.
Instead of "Select Features by Expression..." for the whole multipolygons set, use filter and then save the filtered features.
Steps:
1. Open the file via "Add vector layer".
2. Select "multipolygons" only
3. Use filter after open:
"place" = 'island' OR "place" = 'islet'
4. Save the filtered features
5. Done

Took two-three minutes to save. Forgot to mentioned that in version 2.18.15 I was not able to use select, it returned 0 features selected. Instead I used the filter and that worked. The same approach work for QGIS 3.10 LTR.
The problem lies within the selecting features by expression and saving from there...

**Comment by Pedro-Murteira** [comment]
@soli004 Hello, is this still valid on more recent releases?
