### ISSUE TITLE
Problems loading Google Satellite from XYZ Tiles in QGIS 3.14

### ISSUE THREAD

**Issue by Wallegt** [qgis/QGIS#38497]
Hello everybody;
Yesterday, i was using new QGIS 3.14 and load a Google Satellite imagery from XYZ Tiles in my project. Today, i started the same project and surprise! Google Satellite is not available at all; no imagery display. I tried to delete the layer and load again and nothing happens, try to load other tiles like OSM, Hybrid, Google Maps and non of these works...
But, if i create a new project and load de Google Satellite Tiles it works fine... some idea what´s happening? thanks a lot

**Comment by gioman** [comment]
@Wallegt Hi, this is not a support channel. For help/questions please post the users or developers mailing list.

Anyway my bet is that your project is in a local CRS and when you add a XYZ (global) layer, QGIS cannot (rightly) reproject the whole thing.
