### ISSUE TITLE
attempting to load a non-spatial table crashes QGIS

### ISSUE THREAD

**Issue by gubuntu** [qgis/QGIS#38494]
**Describe the bug**
any table without a geometry column that I try to load from any source or provider immediately crashes QGIS as soon as I try to add it to the canvas. 

Browser layer properties does show the table's contents.

**How to Reproduce**

I've tried various tables so it won't help to provide a sample. 

Sources I've tried include csv, geopackage, postgis, pds, xslx

Providers include browser, delimited text, postgis

**QGIS and OS versions**

QGIS version | 3.14.15-Pi | QGIS code revision | d5114d2cfa
-- | -- | -- | --
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.28.0 | Running against SQLite | 3.28.0
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS 10.15
Active python plugins | ORStools; SpreadsheetLayers; lrs; DataPlotly; quick_map_services; stac_browser; Discovery; qfieldsync; qchainage; OSMDownloader; qgis_resource_sharing; openlayers_plugin; Projestions; mmqgis; processing_circuitscape; mapswipetool_plugin; Mergin; travel_time_platform_plugin; nominatim_locator_filter; geocatbridge; timemanager; processing; db_manager; MetaSearch

AND

QGIS version | 3.10.9-A Coruña | QGIS code revision | bf47e9d3e1
-- | -- | -- | --
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.28.0 | Running against SQLite | 3.28.0
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS 10.15
Active python plugins | ORStools; SpreadsheetLayers; lrs; DataPlotly; quick_map_services; stac_browser; Discovery; qfieldsync; qchainage; OSMDownloader; qgis_resource_sharing; openlayers_plugin; Projestions; mmqgis; processing_circuitscape; mapswipetool_plugin; Mergin; travel_time_platform_plugin; nominatim_locator_filter; geocatbridge; timemanager; processing; db_manager; MetaSearch

**Comment by nirvn** [comment]
My money is on one of your active plugins causing the crash. Try with a new plugin-less profile.

**Comment by gioman** [comment]
Settings > user profiles > new profile

**Comment by mradamcox** [comment]
Thanks for this tip. I was also getting crashes with non-spatial CSVs today, and then disabled the GeoCatBridge plugin (the most recent one I had added) and that fixed the issue. Will go check out the repo for that plugin now.

**Comment by mradamcox** [comment]
https://github.com/GeoCat/qgis-bridge-plugin/issues/106

**Comment by gubuntu** [comment]
I can confirm a no-plugin profile did the trick, then my normal profile with GeoCatBridge disabled fixed the problem. Thanks!
