### ISSUE TITLE
Task: update website link

### ISSUE THREAD

**Issue by mwtoews** [qgis/QGIS#38506]
This is a _very_ simple task for anyone that can update this GitHub project.

Currently, the website is `http://qgis.org` (see "homepage" in https://api.github.com/repos/qgis/QGIS).

This should be updated to `https://qgis.org` (to use HTTPS).

To do this, just click the cog icon near "About" at https://github.com/qgis/QGIS and add a <kbd>s</kbd> in the right spot. Easy!

**Comment by rduivenvoorde** [comment]
Thanks, done
