### ISSUE TITLE
QGIS Crashes on shutdown

### ISSUE THREAD

**Issue by grantboxer** [qgis/QGIS#38501]
## User Feedback

Crashes on shutdown

## Report Details

**Crash ID**: [73f6350f61df3a28525698f32a31297815158bf3](https://github.com/qgis/QGIS/search?q=73f6350f61df3a28525698f32a31297815158bf3&type=Issues)

**Stack Trace**
<pre>
QObject::connect :
PyInit_QtCore :
PyObject_FastCallKeywords :
PyObject_Call :
PyInit_sip :
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyEval_EvalCodeEx :
PyEval_EvalCode :
PyArena_Free :
PyRun_StringFlags :
QgsPythonUtilsImpl::evalString qgspythonutilsimpl.cpp:529
QgsPythonUtilsImpl::unloadPlugin qgspythonutilsimpl.cpp:648
QgsPluginRegistry::unloadAll qgspluginregistry.cpp:193
QgisApp::saveWindowState qgisapp.cpp:5106
QMetaObject::activate :
QCoreApplicationPrivate::execCleanup :
QCoreApplication::exec :
main main.cpp:1618
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.14.15-Pi
QGIS code revision: d5114d2cfa
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by gioman** [comment]
@grantboxer please test with a new QGIS profile, no 3rd party plugins installed.

**Comment by gioman** [comment]
Closing for lack of feedback.
