### ISSUE TITLE
Sudden massive slow-down of QGIS

### ISSUE THREAD

**Issue by LasaVecu** [qgis/QGIS#38517]
## User Feedback

Just trying to open a QGIS file that I had opened dozens  of times before with no problems at all.
I have major problems with QGIS since a day or two. Things have slowed down to a crawl on: quite suddenly, from one day to another. Everything else works fine.
Help appreciated.

## Report Details

**Crash ID**: [4d0fdac8df7f5b00480243a071b5f9ff1ee349e4](https://github.com/qgis/QGIS/search?q=4d0fdac8df7f5b00480243a071b5f9ff1ee349e4&type=Issues)

**Stack Trace**
<pre>
QgsSymbolSelectorWidget::updatePreview qgssymbolselectordialog.cpp:458
QtPrivate::QFunctorSlotObject<<lambda_ccc3f2ad3e85477ef07f1fe159c82fac>,0,QtPrivate::List<>,void>::impl qobjectdefs_impl.h:421
QMetaObject::activate :
</pre>

**QGIS Info**
QGIS Version: 3.10.9-A Coru�a
QGIS code revision: bf47e9d3e1
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

**Comment by gioman** [comment]
>  Help appreciated.

@LasaVecu try with a new QGIS profile



> Just trying to open a QGIS file

do you mean "project"? Anyway if the new profile do not helps you must add here more details: what are the steps that lead to the crash?  is the crash data/project dependent? can yyou share  a sample project/data?

**Comment by gioman** [comment]
Closing for lack of feedback.
