### ISSUE TITLE
DXF exports line with a width

### ISSUE THREAD

**Issue by mikaelbt** [qgis/QGIS#38513]
Hi,

When exporting a polygon from QGIS into DXF format, and then importing the DXF to Sketchup Pro (Pro version needed..), what i get is not a line but 2 lines with a surface (face) in between. 

The Sketchup community found the bug in the QGIS DXF export : 
When opening the DXF file in the notepad, below the lines : 
"AcDbPolyline" and "CONTINUOUS" there is a value of "-1.0". 

When this value is set to 0, the import of the DXF into Sketchup is correct: the result is a single line. 

How to reproduce : 
1. Create a polygon in QGIS
2. File > Import/Export... > Export project in DXF
3. Select only the layer of the polyline
4. in sketchup Pro : File > Import...  
5. Select the DXF file.
6. the double line appears instead of the single line.

**Comment by Pedro-Murteira** [comment]
@mikaelbt Hello, I can not reproduce this issue because I don't have the software mentioned in the report. Is this still an issue in more recent versions of QGIS?
