### ISSUE TITLE
World files names with nordic letters don't work

### ISSUE THREAD

**Issue by oskarlin** [qgis/QGIS#38510]
**Describe the bug**

When using file names with å ä ö QGIS doesn't recognise the world file. 

**How to Reproduce**

These files work:
file.tif
file.tfw

These files doesn't work:
fäle.tif
fäle.tfw

**QGIS and OS versions**
QGIS 3.14.0-Pi
MacOS

**Additional context**
I might have reported this bug before but I can't find anything when I search for it here. Sorry if it's a duplicate.

**Comment by gioman** [comment]
> When using file names with å ä ö QGIS doesn't recognise the world file.

@oskarlin does GDAL (gdalinfo) recognize world files with such names?

**Comment by oskarlin** [comment]
> > When using file names with å ä ö QGIS doesn't recognise the world file.
> 
> @oskarlin does GDAL (gdalinfo) recognize world files with such names?

I tried now and no, gdalinfo doesn't seem to recognise those files either.

**Comment by gioman** [comment]
> I tried now and no, gdalinfo doesn't seem to recognise those files either.

@oskarlin so this is not a QGIS issue, but rather a GDAL one. You must file this issue on the GDAL bug tracker.

**Comment by oskarlin** [comment]
> > I tried now and no, gdalinfo doesn't seem to recognise those files either.
> 
> @oskarlin so this is not a QGIS issue, but rather a GDAL one. You must file this issue on the GDAL bug tracker.

All right. I'll file it over there instead!
