### ISSUE TITLE
Missing/dropped table columns when importing polygon data in GeoJSON format to PostGIS/PostgreSQL

### ISSUE THREAD

**Issue by MatthiasHinz** [qgis/QGIS#38514]
I am trying to import GeoJson files into a PostGIS database using the QGIS graphical modeller. The imported database table has less columns than the original input data. The reason is maybe that the columns are dropped when a temporary GeoPackage-file is created by the algorithm.

The files are from the following source:

https://ec.europa.eu/eurostat/web/gisco/geodata/reference-data/administrative-units-statistical-units/nuts
e.g.
https://gisco-services.ec.europa.eu/distribution/v2/nuts/geojson/NUTS_RG_01M_2016_3035_LEVL_0.geojson

After routinely repairing the geometries, I am using the following algorithm for importing the data:

`processing.run("gdal:importvectorintopostgisdatabaseavailableconnections", {'DATABASE':'db_opengeoedu','INPUT':'memory://MultiPolygon?crs=EPSG:3035&field=id:string(0,0)&field=COAST_TYPE:integer(0,0)&field=MOUNT_TYPE:integer(0,0)&field=CNTR_CODE:string(0,0)&field=FID:string(0,0)&field=NUTS_ID:string(0,0)&field=NUTS_NAME:string(0,0)&field=LEVL_CODE:integer(0,0)&field=URBN_TYPE:integer(0,0)&uid={75ec2ff5-136c-44b2-a8a7-f5ea7d220173}','SHAPE_ENCODING':'','GTYPE':8,'A_SRS':None,'T_SRS':None,'S_SRS':None,'SCHEMA':'public','TABLE':'test123','PK':'id','PRIMARY_KEY':'','GEOCOLUMN':'geom','DIM':0,'SIMPLIFY':'','SEGMENTIZE':'','SPAT':None,'CLIP':False,'WHERE':'','GT':'','OVERWRITE':True,'APPEND':False,'ADDFIELDS':False,'LAUNDER':False,'INDEX':False,'SKIPFAILURES':False,'PROMOTETOMULTI':True,'PRECISION':True,'OPTIONS':''})`

However, the data table that arrives in PostGIS contains four columns and the geometry. All remaining columns of the original input data are dropped for some reason. OGR/GDAL does not seem to be the problem. The algorithm executes a command such as the following:

`ogr2ogr -progress --config PG_USE_COPY YES --config SHAPE_ENCODING "utf-8" -f PostgreSQL PG:" dbname='db' host=localhost port=XXX user='postgres' password='XXX' sslmode=disable active_schema=eurostat " -lco DIM=2 /tmp/processing_WTpocG/31d34dad49ac4f3c8f324a04fde8bdac/INPUT.gpkg INPUT -append -addfields -nlt MULTIPOLYGON -lco GEOMETRY_NAME=geom -nln eurostat.nuts_regionen -nlt PROMOTE_TO_MULTI`

This command works fine from the command line using the original data, but the supplied temporary file `INPUT.gpkg` already has missing columns.

```
QGIS Version | 3.14.15-Pi
GDAL/OGR | 3.0.4
```
The problem occurs on both, Ubuntu focal and Windows 10. The workflow used to work fine in previous versions of QGIS.

**Comment by gioman** [comment]
Works fine for me on QGIS LTR on Focal using the provided input data and the ogr based tool both in and out the modeller.

@MatthiasHinz maybe there is something more in your model, please attach it here.

**Comment by MatthiasHinz** [comment]
@gioman Thank you for trying it out! That is confusing me, because switch to  the LTR release and using a clean profile didn't solve my problem. You can find the model here:
https://github.com/opengeoedu/opencaching_uebung/blob/master/models/nuts2postgis.model3

The default database connection value 'db_opengeoedu' may have to be adjusted to your settings.

**Comment by gioman** [comment]
>  https://github.com/opengeoedu/opencaching_uebung/blob/master/models/nuts2postgis.model3

@MatthiasHinz 

you are "losing" the attributes at "Objektfilter nach Ländercode". But as I don't speak German I don't understand really what is going on. Anyway if you use "Datei herunterladen" as input (for the import and create view operations) you get all the attributes.
