### ISSUE TITLE
Crashing when adding or removing layers in a project. No other activities. 

### ISSUE THREAD

**Issue by Dewidine** [qgis/QGIS#38528]
## User Feedback

QGIS has been crashing for the past few days, every time I upload layers or try and do any spatial process, like splitting a shapefile into multiple single filES. This time its crashed as I was opening a project and I deselected a layer. 

## Report Details

**Crash ID**: [37e1cc22bbf29497cb42785a212ea620c95f1673](https://github.com/qgis/QGIS/search?q=37e1cc22bbf29497cb42785a212ea620c95f1673&type=Issues)

**Stack Trace**
<pre>
QgsMapRendererParallelJob::renderLayerStatic qgsmaprendererparalleljob.cpp:265
QtConcurrent::MapKernel<QList<LayerRenderJob>::iterator,QtConcurrent::FunctionWrapper1<void,LayerRenderJob & __ptr64> >::runIteration qtconcurrentmapkernel.h:69
QtConcurrent::MapKernel<QList<LayerRenderJob>::iterator,QtConcurrent::FunctionWrapper1<void,LayerRenderJob & __ptr64> >::runIterations qtconcurrentmapkernel.h:78
QtConcurrent::IterateKernel<QList<QgsImageOperation::ImageBlock>::iterator,void>::forThreadFunction qtconcurrentiteratekernel.h:256
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.8-A Coru�a
QGIS code revision: d09a4f2388
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by gioman** [comment]
Closing for lack of feedback.
