### ISSUE TITLE
QGIS Browser do not list the "raster_columns" table

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#38533]
On a PostGIS backend with the postgis_raster extension enabled there are a couple of tables/views in public, raster_columns and raster_overiews.

The latter is shown in QGIS Browser, DB Manager and the "Add PostGIS layer" dialog, while the former only show in DB Manager.

QGIS LTR/3.10 on Ubuntu 20.04.

**Comment by elpaso** [comment]
Is this 3.10 only? In master I can see all tables: 
![immagine](https://user-images.githubusercontent.com/142164/93855662-24373000-fcb8-11ea-8c75-0cc7265d0d5a.png)

**Comment by gioman** [comment]
> Is this 3.10 only? In master I can see all tables:

correct, work ok on master, closing.
