### ISSUE TITLE
Incomplete "geometry_columns" table

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#38534]
On a PostgreSQL endpoint with PostGIS enabled there is a table/view in public called "geometry_columns", that contains the "catalog" of spatial tables in the specific database.

This table shows ok as a preview in DB Manager, but when added in a QGIS project (regardless of the method) it only show 1 record.

QGIS LTR/3.10 on Ubuntu 20.04.

**Comment by uclaros** [comment]
The `geometry_columns` view lacks a primary key, that's probably why it can't be displayed properly. In master, if I select all four `f_table_catalog`, `f_table_schema`, `f_table_name` and `f_geometry_column` fields as feature id, it loads OK.

**Comment by alexbruy** [comment]
@gioman looks like this is indeed because of the missed primary key. Do you want to keep this open?
