### ISSUE TITLE
Processing: when saving results to PostGIS the geometry column is called "the_geom"

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#38535]
Is since long that the default name for the geometry column (in PostGIS) has changed to just "geom".

QGIS LTR/3.10 on Ubuntu 20.04.

**Comment by nyalldawson** [comment]
This is fixed in 3.14 -- I don't think we should change for 3.10, it's possible it may break existing workflows

**Comment by alexbruy** [comment]
@gioman can we close this?
