### ISSUE TITLE
Relation widget in input form tabs - NULL value filled with data in form

### ISSUE THREAD

**Issue by AnnijaViktorija** [qgis/QGIS#38549]
**BUG**

Created Relation widget with NULL value allowed not working as expected in drag&drop forms when widget is not used in first tab of form.

|    Relation widget    |  Referenced layer
|:-------------------------:|:-------------------------:|
![](https://user-images.githubusercontent.com/56792983/91963309-605d1d80-ed16-11ea-99aa-a5d9000492f9.png) |  ![](https://user-images.githubusercontent.com/56792983/91963688-e0838300-ed16-11ea-8830-cdd6e8dd64de.png)

**Attribute table**
In attribute table it can be observed that there is no value.
![](https://user-images.githubusercontent.com/56792983/91964377-bb434480-ed17-11ea-859b-dba7195e08dd.png)
**Form view**
In form views first tab relation widget looks fine. But starting from second tab, NULL value is filled with data from referenced layer. Analog action occurs when "Identify Features" is used.
         First tab           |      Second tab
|:-------------------------:|:-------------------------:|
![](https://user-images.githubusercontent.com/56792983/91964615-08bfb180-ed18-11ea-8159-055f7fcf891b.png)  |  ![](https://user-images.githubusercontent.com/56792983/91964692-212fcc00-ed18-11ea-9afd-530c558c5b8e.png)

**REPRODUCE**

[Problem.zip](https://github.com/qgis/QGIS/files/5161615/Problem.zip)

1.1. Open layers 'Persons' attribute table.
1.2. See that columns 'hobby' and 'address' are empty.
1.3. Switch to form view.
1.4. Switch to second tab 'Extra info'.
1.5. See that columns 'hobby' and 'address' are not empty (expected NULL).

2.1. Open layers 'Persons copy' attribute table.
2.2. See that columns 'hobby' and 'address' are empty.
2.3. Switch to form view.
2.4. See that column 'hobby' shows NULL value as expected.
2.4. Switch to second tab 'Extra info'.
2.5. See that column 'address' is not empty (expected NULL).

**QGIS and OS versions**

QGIS version | 3.10.5-A Coruña | QGIS code branch | Release QGIS code branch.3
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 10.12 (Ubuntu 10.12-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
Compiled against PROJ | 7.0.0 | Running against PROJ | Rel. 7.0.0, March 1st, 2020
OS Version | Ubuntu 18.04.5 LTS

Problem occurs with QGIS 3.14 as well.

**Comment by AnnijaViktorija** [comment]
This problem occurs with the QGIS 3.10.5.
With QGIS 3.14. problem can be reproduced with "Identify Features" tool.

**Comment by elpaso** [comment]
@AnnijaViktorija since you mentioned value relation and the complete, this might be related (and fixed): https://github.com/qgis/QGIS/issues/38552

**Comment by troopa81** [comment]
The risk of merging #38771 is too high, so better live with issue in 3.10 than break anything.

In current master, everything works fine, in forms and from the identifyTool.
