### ISSUE TITLE
All versions of QGIS 3 keep on hanging after Windows 10 May 2020 update

### ISSUE THREAD

**Issue by stefanismyname** [qgis/QGIS#38541]
I have tested QGIS 3 with various versions (including the long term stable release) on various PCs that have the Windows 10 May 2020 update installed. QGIS keeps on hanging for extended periods of time, making it impossible to perform simple tasks. After every second or third mouse click, the app starts hanging for approximately 10-15 seconds before resuming.

I have also tried removing all 3rd party plugins, and even with a clean profile, the issue persists.

**Comment by gioman** [comment]
@stefanismyname try with a new QGIS profile.
