### ISSUE TITLE
QGIS crashes at panning/zooming after win10 entered standby-mode

### ISSUE THREAD

**Issue by Meibes** [qgis/QGIS#38546]
**Describe the bug**
If QGIS is open and you wake the pc from standby-mode QGIS fails to display raster-data and eventually crashes. Sometimes specific zoom levels are still being displayed while others don't work. There is no problem with vector layers from the same source.

**How to Reproduce**

1. open project
2. let windows10 enter standby
3. wake the pc
4. switch to QGIS
5. move/zoom the map

in 3.10.9 (not sure if this was also displayed in earlier versions) QGIS displayed a warning icon near the raster-layer with following contents:
IReadBlock failed at X offset 0, Y offset 0: TIFFReadEncodedTile() failed.,IReadBlock failed at X offset 0, Y offset 0: TIFFReadEncodedTile() failed.,IReadBlock failed at X offset 0, Y offset 0: TIFFReadEncodedTile() failed.
IReadBlock failed at X offset 0, Y offset 0: TIFFReadEncodedTile() failed.
IReadBlock failed at X offset 4, Y offset 4: TIFFReadEncodedTile() failed.,IReadBlock failed at X offset 4, Y offset 4: TIFFReadEncodedTile() failed.,IReadBlock failed at X offset 4, Y offset 4: TIFFReadEncodedTile() failed.
IReadBlock failed at X offset 4, Y offset 4: TIFFReadEncodedTile() failed.
IReadBlock failed at X offset 4, Y offset 6: TIFFReadEncodedTile() failed.,IReadBlock failed at X offset 4, Y offset 6: TIFFReadEncodedTile() failed.,IReadBlock failed at X offset 4, Y offset 6: TIFFReadEncodedTile() failed.
IReadBlock failed at X offset 4, Y offset 6: TIFFReadEncodedTile() failed.
IReadBlock failed at X offset 5, Y offset 8: TIFFReadEncodedTile() failed.,IReadBlock failed at X offset 5, Y offset 8: TIFFReadEncodedTile() failed.,IReadBlock failed at X offset 5, Y offset 8: TIFFReadEncodedTile() failed.
IReadBlock failed at X offset 5, Y offset 8: TIFFReadEncodedTile() failed.
IReadBlock failed at X offset 5, Y offset 5: TIFFReadEncodedTile() failed.,IReadBlock failed at X offset 5, Y offset 5: TIFFReadEncodedTile() failed.,IReadBlock failed at X offset 5, Y offset 5: TIFFReadEncodedTile() failed.
IReadBlock failed at X offset 5, Y offset 5: TIFFReadEncodedTile() failed.
IReadBlock failed at X offset 43, Y offset 41: TIFFReadDirectory:Failed to read directory at offset 12989466,IReadBlock failed at X offset 43, Y offset 41,IReadBlock failed at X offset 43, Y offset 41
IReadBlock failed at X offset 43, Y offset 41: TIFFReadDirectory:Failed to read directory at offset 12989466
IReadBlock failed at X offset 43, Y offset 41
IReadBlock failed at X offset 80, Y offset 31: TIFFReadDirectory:Failed to read directory at offset 12989466,IReadBlock failed at X offset 80, Y offset 31,IReadBlock failed at X offset 80, Y offset 31
IReadBlock failed at X offset 80, Y offset 31: TIFFReadDirectory:Failed to read directory at offset 12989466
IReadBlock failed at X offset 80, Y offset 31
IReadBlock failed at X offset 45, Y offset 6: TIFFReadEncodedTile() failed.,IReadBlock failed at X offset 45, Y offset 6: TIFFReadEncodedTile() failed.,IReadBlock failed at X offset 45, Y offset 6: TIFFReadEncodedTile() failed.
IReadBlock failed at X offset 45, Y offset 6: TIFFReadEncodedTile() failed.
IReadBlock failed at X offset 26, Y offset 8: TIFFReadEncodedTile() failed.,IReadBlock failed at X offset 26, Y offset 8: TIFFReadEncodedTile() failed.,IReadBlock failed at X offset 26, Y offset 8: TIFFReadEncodedTile() failed.
IReadBlock failed at X offset 26, Y offset 8: TIFFReadEncodedTile() failed.
IReadBlock failed at X offset 6, Y offset 9: TIFFReadEncodedTile() failed.,IReadBlock failed at X offset 6, Y offset 9: TIFFReadEncodedTile() failed.,IReadBlock failed at X offset 6, Y offset 9: TIFFReadEncodedTile() failed.
IReadBlock failed at X offset 6, Y offset 9: TIFFReadEncodedTile() failed.
IReadBlock failed at X offset 0, Y offset 9: TIFFReadEncodedTile() failed.,IReadBlock failed at X offset 0, Y offset 9: TIFFReadEncodedTile() failed.,IReadBlock failed at X offset 0, Y offset 9: TIFFReadEncodedTile() failed.
IReadBlock failed at X offset 0, Y offset 9: TIFFReadEncodedTile() failed.
IReadBlock failed at X offset 32, Y offset 41: TIFFReadDirectory:Failed to read directory at offset 12989466,IReadBlock failed at X offset 32, Y offset 41,IReadBlock failed at X offset 32, Y offset 41
IReadBlock failed at X offset 32, Y offset 41: TIFFReadDirectory:Failed to read directory at offset 12989466
IReadBlock failed at X offset 32, Y offset 41
IReadBlock failed at X offset 76, Y offset 89: TIFFReadDirectory:Failed to read directory at offset 12368012,IReadBlock failed at X offset 76, Y offset 89,IReadBlock failed at X offset 76, Y offset 89
IReadBlock failed at X offset 76, Y offset 89: TIFFReadDirectory:Failed to read directory at offset 12368012
IReadBlock failed at X offset 76, Y offset 89
IReadBlock failed at X offset 86, Y offset 94,IReadBlock failed at X offset 86, Y offset 94,IReadBlock failed at X offset 86, Y offset 94
IReadBlock failed at X offset 86, Y offset 94
IReadBlock failed at X offset 89, Y offset 100,IReadBlock failed at X offset 89, Y offset 100,IReadBlock failed at X offset 89, Y offset 100
IReadBlock failed at X offset 89, Y offset 100

in 3.10.8 QGIS crashed with the following log (I don't have access to this pc and since the "copy report" button is disabled by default, the pc-user decided to do a screenshot instead):

![crash](https://user-images.githubusercontent.com/26258451/91955785-f9366d80-ed03-11ea-9432-feadc682109b.png)

**QGIS and OS versions**

QGIS was installed via osgeo4w, win10 64bit latest updates

**Additional context**

all gis data is located on a nas, there is no data on the pc itself, shapes and postgis work without problems, raster data (tiff) doesn't work. if qgis is closed and restarted everything works again without problems

**Comment by gioman** [comment]
@Meibes does it happens if the rasters are on the local disk rather than a NAS?

**Comment by uclaros** [comment]
I used to have similar issues when an external hard disk containing my raster entered sleep due to inactivity.

**Comment by Meibes** [comment]
@gioman this was not tested

**Comment by gioman** [comment]
> @gioman this was not tested

it is necessary to understand if the remote nature of the datasource is a factor or not.

**Comment by Meibes** [comment]
## User Feedback
now with the full log 

## Report Details

**Crash ID**: [46816175573d857be55e121fa69917979fdd7d7c](https://github.com/qgis/QGIS/search?q=46816175573d857be55e121fa69917979fdd7d7c&type=Issues)

**Stack Trace**

<pre>

memcpy_repmovs memcpy.asm:114

VSICreateCachedFile :

GDALRegister_Terragen :

GDALRegister_Terragen :

GDALRegister_Terragen :

GDALRegister_Terragen :

GDALRegister_GTiff :

GDALRasterBand::GetLockedBlockRef :

GDALRasterBand::IRasterIO :

GDALRegister_GTiff :

GDALProxyRasterBand::IRasterIO :

GDALRasterBand::RasterIO :

VRTComplexSource::SetColorTableComponent :

VRTComplexSource::RasterIO :

VRTSourcedRasterBand::IRasterIO :

GDALRasterBand::RasterIO :

QgsProcessingModelOutput::toVariant :

QgsRasterIdentifyResult::params :

QgsScaleBarSettings::alignment :

QgsPalettedRasterRenderer::block :

QgsBrightnessContrastFilter::block :

QgsHueSaturationFilter::block :

QgsRasterResampleFilter::block :

QgsRasterProjector::block :

QgsRasterIterator::readNextRasterPartInternal :

QgsRasterDrawer::draw :

QgsRasterLayerRenderer::render :

QgsMapRendererCustomPainterJob::doRender :

QgsMapRendererCustomPainterJob::staticRender :

QgsMapRendererJob::renderingTime :

QThreadPoolPrivate::reset :

QThread::start :

BaseThreadInitThunk :

RtlUserThreadStart :

</pre>

**QGIS Info**

QGIS Version: 3.10.9-A Coru�a

QGIS code revision: bf47e9d3e1

Compiled against Qt: 5.11.2

Running against Qt: 5.11.2

Compiled against GDAL: 3.0.4

Running against GDAL: 3.0.4

**System Info**

CPU Type: x86_64

Kernel Type: winnt

Kernel Version: 10.0.18362

**Comment by gioman** [comment]
> it is necessary to understand if the remote nature of the datasource is a factor or not.

@Meibes this is still unanswered.

**Comment by Meibes** [comment]
and another one, slightly different

Crash ID: 9ae998b60ae54de33b08223740e71bdaff65fc30


**Stack Trace**

<pre>
memcpy_repmovs memcpy.asm:114
VSICreateCachedFile :
GDALRegister_Terragen :
GDALRegister_Terragen :
GDALRegister_Terragen :
GDALRegister_Terragen :
GDALRegister_GTiff :
GDALRasterBand::GetLockedBlockRef :
GDALRasterBand::IRasterIO :
GDALRegister_GTiff :
GDALProxyRasterBand::IRasterIO :
GDALRasterBand::RasterIO :
VRTComplexSource::SetColorTableComponent :
VRTComplexSource::RasterIO :
VRTSourcedRasterBand::IRasterIO :
GDALRasterBand::RasterIO :
QgsProcessingModelOutput::toVariant :
QgsRasterIdentifyResult::params :
QgsScaleBarSettings::alignment :
QgsPalettedRasterRenderer::block :
QgsBrightnessContrastFilter::block :
QgsHueSaturationFilter::block :
QgsRasterResampleFilter::block :
QgsRasterProjector::block :
QgsRasterIterator::readNextRasterPartInternal :
QgsRasterDrawer::draw :
QgsRasterLayerRenderer::render :
QgsMapRendererParallelJob::renderLayerStatic :
QgsMapRendererParallelJob::renderingFinished :
QgsMapRendererParallelJob::renderingFinished :
QgsImageOperation::flipImage :
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>
**QGIS Info**
QGIS Version: 3.10.9-A Coru�a
QGIS code revision: bf47e9d3e1
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4


**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

**Comment by Meibes** [comment]
> 
> 
> > it is necessary to understand if the remote nature of the datasource is a factor or not.
> 
> @Meibes this is still unanswered.

I will ask the user to copy the data to a local drive
