### ISSUE TITLE
Infinite hang with a layer style based on a joined column

### ISSUE THREAD

**Issue by maltaesousa** [qgis/QGIS#38551]
**Describe the bug**

When displaying a layer joined to another layer and styling it based on a joined column, the rendering performance drops a lot, sometimes resulting in an infinite "Not responding" Window.

**How to Reproduce**

1. Download the demo project [here](https://sitn.ne.ch/web/qgis/test_join.zip).
2. Unzip and open `join.qgz`, you should see red rectangles.
3. Zoom in / out -> everything is ok. The active layer has a simple style.
4. Activate _joined_polygons_categorized_ layer which has a style based on the joined layer
5. Zoom out -> progress bar in the status bar takes some time.
6. Do some zoom in / out quick, progress bar stays "progressing", trying to do exit QGIS will result in a "Not responding" window.

**QGIS and OS versions**

Version de QGIS | 3.14.15-Pi | Révision du code | d5114d2cfa
-- | -- | -- | --
Compilé avec Qt | 5.11.2 | Utilisant Qt | 5.11.2
Compilé avec GDAL/OGR | 3.0.4 | Utilisé avec GDAL/OGR | 3.0.4
Compilé avec GEOS | 3.8.1-CAPI-1.13.3 | Utilisé avec GEOS | 3.8.1-CAPI-1.13.3
Compilé avec SQLite | 3.29.0 | Fonctionne avec SQLite | 3.29.0
Version du client PostgreSQL | 11.5 | Version de SpatiaLite | 4.3.0
Version de QWT | 6.1.3 | Version de QScintilla2 | 2.10.8
Compilé avec PROJ | 6.3.2 | Fonctionne avec PROJ | Rel. 6.3.2, May 1st, 2020
Version de l'OS | Windows 10 (10.0)
Extensions Python actives | changeDataSource; searchlayers; MetaSearch; processing

**Additional context**

Same behavior if the layers are on PostGIS.

**Comment by elpaso** [comment]
Cannot reproduce on linux/master.

**Comment by maltaesousa** [comment]
Installed a fresh 3.14.15 QGIS on a Windows 10 (1803) with fresh profile: same problem. I also tried on an Ubuntu and was not able to reproduce.

**Comment by gioman** [comment]
> Do some zoom in / out quick, progress bar stays "progressing", trying to do exit QGIS will result in a "Not responding" window.

@maltaesousa I was able to replicate this on Windows and QGIS 3.14 but NOT on 3.10.

**Comment by maltaesousa** [comment]
Thanks all for your tests, I can replicate this on 3.10.1 (Windows) also.

**Comment by gioman** [comment]
>  3.10.1

@maltaesousa then probably is something very tricky to trigger.
