### ISSUE TITLE
Projet don't load

### ISSUE THREAD

**Issue by OptiConseils** [qgis/QGIS#38562]
Hi, my projet don't load. I don't know what to do.
![1](https://user-images.githubusercontent.com/70661810/92024470-3e6e9580-ed2c-11ea-8efb-724ec61ea391.JPG)
![2](https://user-images.githubusercontent.com/70661810/92024471-3f072c00-ed2c-11ea-92a7-0a3946f39555.JPG)
![3](https://user-images.githubusercontent.com/70661810/92024473-3f072c00-ed2c-11ea-885f-a2b901679efd.JPG)

**Comment by gioman** [comment]
@OptiConseils can you give more details?
what it contains (type and number of datasources)? Did it opened fine before starting to show the problem? what QGIS version you use? on what platform?

**Comment by OptiConseils** [comment]
I have multiple layers, 14 WMS. It open fine just the first time, when I create projet and add layers. If I close it and reopen it, it will do this (see picture I already show). My Qgis version is 3.10. I use it on Windows 10. First, I tried to but everyting on the cloud, it does that. After, I restarted on the computer (in local), it does the same. I but and old version of the projet (template) and it does the same..

**Comment by gioman** [comment]
@OptiConseils can you share the project?

**Comment by OptiConseils** [comment]
It said they don't support that file type. How can I do?

**Comment by gioman** [comment]
> @gioman It said they don't support that file type. How can I do?

@OptiConseils zip it then it will allow you to attach the zip file.

**Comment by OptiConseils** [comment]
@gioman 
[client_Rachel.zip](https://github.com/qgis/QGIS/files/5169017/client_Rachel.zip)

**Comment by gioman** [comment]
It also not opening here, on  QGIS 3.10 on Linux.

**Comment by gioman** [comment]
Moreover is not possible to cancel the operation, and QGIS is stuck, leaving as only option to kill the program.

**Comment by OptiConseils** [comment]
So where do I should look to repair the projet? Have you more idea? Do I check layers or WMS? My old projet are functionals so, it's something that change in the projet between..

**Comment by gioman** [comment]
I'm not sure if is a layer in the project that is causing the issue, but it may be worth a try.

You can unzip the QGZ file and get a QGS, this can be edited with a text editor (a good one like Notepad++) and you can try remove layer definitions one by one, save and see if it loads in QGIS.

**Comment by OptiConseils** [comment]
Thank you I will try.

**Comment by nyalldawson** [comment]
@OptiConseils 

Here's a repaired version of the project.

[fixed.zip](https://github.com/qgis/QGIS/files/5171875/fixed.zip)
