### ISSUE TITLE
QGIS Linear Z interpolation on snapping works when adding new feature, does not when editing existing ones

### ISSUE THREAD

**Issue by 2cbarata** [qgis/QGIS#38561]
The interpellation of the Z value when snapping in the creation of a new feature is done well in QGIS 3.14 but when editing elements this does not happen. 

![inter_3d](https://user-images.githubusercontent.com/1490248/92015285-74ba0e00-ed48-11ea-9abc-13cd03c16fa4.gif)

QGIS version: 3.14.15-Pi
QGIS code revision: d5114d2cfa
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL/OGR: 3.0.4
Running against GDAL/OGR: 3.0.4
Compiled against GEOS: 3.8.1-CAPI-1.13.3
Running against GEOS: 3.8.1-CAPI-1.13.3
Compiled against SQLite: 3.29.0
Running against SQLite: 3.29.0
PostgreSQL Client Version: 11.5
SpatiaLite Version: 4.3.0
QWT Version: 6.1.3
QScintilla2 Version: 2.10.8
Compiled against PROJ: 6.3.2
Running against PROJ: Rel. 6.3.2, May 1st, 2020
OS Version: Windows 10 (10.0)

**Comment by SrNetoChan** [comment]
@2cbarata that is weird. I am almost sure I have succeeded doing that operatiin in the past. Can you please try to enable topological editing?

**Comment by 2cbarata** [comment]
The topological editing is enable, that is why a new vertex is added to the horizontal line when the snap is made. This happens with all types of elements, lines, points and polygons.

**Comment by 2cbarata** [comment]
The same situation with polygons, with topological editing turned on and segment snap.

![inter_3d_pol](https://user-images.githubusercontent.com/1490248/92235298-56b8ee80-eeab-11ea-942b-7cc18714b11c.gif)

**Comment by SrNetoChan** [comment]
I just realized that 3D snapping on segments was not available on QGIS 3.10. I believe this very nice feature was introduced by @lbartoletti.

**Comment by lbartoletti** [comment]
You're right @SrNetoChan It was introduced in https://github.com/qgis/QGIS/pull/31163 but the Z is only snapped from vertex (segments, middle, etc, return default Z value). I had to look to add this support, but I worked on other projects?
