### ISSUE TITLE
Raster resampling:  problem loading output layers 

### ISSUE THREAD

**Issue by zhanghui2020** [qgis/QGIS#38575]
IMPORTANT:

Do NOT use GitHub to post any questions or support requests!
They will be closed immediately and ignored.
Questions should go to the qgis-user mailing list at https://lists.osgeo.org/mailman/listinfo/qgis-user
or other support forums such as https://gis.stackexchange.com/.

GitHub issues are for bug reports and suggestions for new features.

**Comment by gioman** [comment]
@zhanghui2020 please reopen with all the necessary information.
