### ISSUE TITLE
pythonnet don't Work good in Qgis 3.10.9

### ISSUE THREAD

**Issue by GillesGAUTIERM2A** [qgis/QGIS#38586]
I use pythonnet to include wpf ihm in Qgis.
With Qgis 3.10.6 these lines are working and not with 2.10.9.
the environement of python changed?

- the code to execute in python console (this code need WindowsFormsIntegration.dll) :

import clr
clr.AddReference("System.Windows.Forms")
clr.AddReference("System.Drawing")
clr.AddReference("C:/temp/WindowsFormsIntegration.dll")
from System.Windows.Forms import *
from System.Drawing import *
from System.Windows.Forms.Integration import ElementHost

host = ElementHost()
print('HOST : ' ,host)

- error :

System.ArgumentException: Impossible de trouver la police '?'.
   à System.Drawing.FontFamily.GetGdipGenericSansSerif()
   à System.Drawing.FontFamily.get_GenericSansSerif()
   à System.Drawing.SystemFonts.get_DefaultFont()
   à System.Windows.Forms.Control.get_DefaultFont()
   à System.Windows.Forms.Control.get_Font()

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS3~1.14\apps\Python37\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "<string>", line 9, in <module>
System.Reflection.TargetInvocationException: Une exception a été levée par la cible d'un appel.
   à System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   à System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   à System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   à System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   à System.Windows.Forms.Integration.PropertyMap.Apply(String propertyName)
   à System.Windows.Forms.Integration.PropertyMap.AddDefaultPropertyTranslators()
   à System.Windows.Forms.Integration.ElementHost.StartPropertyMapping()
   à System.Windows.Forms.Integration.ElementHost..ctor()

**Comment by gioman** [comment]
@GillesGAUTIERM2A is this still relevant in recent QGIS releases?
