### ISSUE TITLE
qgis terms of license pop up bug

### ISSUE THREAD

**Issue by jcampos-berkeley** [qgis/QGIS#38588]
Every time I go to settings>Desktop & Screen Saver on my Mac, a message pops up asking me to agree or disagree with the terms of agreement for using QGIS.  This occurs even after uninstalling QGIS from my Mac. Is there any way to resolve this issue such that I don't have to deal with his message anymore?
<img width="644" alt="Screen Shot 2020-09-03 at 1 00 35 PM" src="https://user-images.githubusercontent.com/60199375/92161884-1e031180-ede6-11ea-8556-b2d76f064e5e.png">

**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by PeterPetrik** [comment]
Hi @jcampos-berkeley, this window comes from DMG installer. I think you have some stale qgis install process running in background for any reason. you can find the process and kill it by for example in terminal 

```
 ps -a | grep -i qgis 
> this will show process PID
kill <PID>
```

or simply try to restart your computer to see if the issue persists.

**Comment by gioman** [comment]
Closing for lack of feedback.
