### ISSUE TITLE
QgsProcessingAlgRunnerTask started inside function crashes QGIS

### ISSUE THREAD

**Issue by Joonalai** [qgis/QGIS#38583]
**Describe the bug**

PyQGIS code starting `QgsProcessingAlgRunnerTask` inside non-global scope crashes QGIS. This happens with QGIS algorithms and plugin algorithms. 

Using `globals` as mentioned [here](https://gis.stackexchange.com/a/325871/123927) does help with similar problems when using other kinds of `QgsTask`s but not with `QgsProcessingAlgRunnerTask`.

![qgis_crash_instantly_](https://user-images.githubusercontent.com/33314057/92118522-451a0d00-edff-11ea-9157-6aa811c60b9e.gif)

**How to Reproduce**

1. Open Python console inside QGIS
2. Open or paste the file below to the console (code is example from [cookbook](https://docs.qgis.org/3.10/en/docs/pyqgis_developer_cookbook/tasks.html#task-from-a-processing-algorithm) but creating a task is moved to a function)
<details>

```python
from functools import partial
from qgis.core import (QgsTaskManager, QgsMessageLog,
                       QgsProcessingAlgRunnerTask, QgsApplication,
                       QgsProcessingContext, QgsProcessingFeedback,
                       QgsProject)

MESSAGE_CATEGORY = 'AlgRunnerTask'

def task_finished(context, successful, results):
    if not successful:
        QgsMessageLog.logMessage('Task finished unsucessfully',
                                 MESSAGE_CATEGORY, Qgis.Warning)
    output_layer = context.getMapLayer(results['OUTPUT'])
    # because getMapLayer doesn't transfer ownership, the layer will
    # be deleted when context goes out of scope and you'll get a
    # crash.
    # takeMapLayer transfers ownership so it's then safe to add it
    # to the project and give the project ownership.
    if output_layer and output_layer.isValid():
        QgsProject.instance().addMapLayer(
             context.takeResultLayer(output_layer.id()))

def run_task():
    alg = QgsApplication.processingRegistry().algorithmById(
                                          'qgis:randompointsinextent')
    context = QgsProcessingContext()
    feedback = QgsProcessingFeedback()
    params = {
        'EXTENT': '0.0,10.0,40,50 [EPSG:4326]',
        'MIN_DISTANCE': 0.0,
        'POINTS_NUMBER': 50000,
        'TARGET_CRS': 'EPSG:4326',
        'OUTPUT': 'memory:My random points'
    }
    task = QgsProcessingAlgRunnerTask(alg, params, context, feedback)
    task.executed.connect(partial(task_finished, context))
    QgsApplication.taskManager().addTask(task)
```

</details>

3. Run the code
4. Write `run_task()` to the console and hit enter
5. Repeat previous part if crash does not happen immediately

**QGIS and OS versions**

<details>

```
QGIS version | 3.14.15-Pi | QGIS code revision | d5114d2cfa
-- | -- | -- | --
Compiled against Qt | 5.12.8 | Running against Qt | 5.12.8
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.2 (Ubuntu 12.2-4) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Ubuntu 20.04.1 LTS
Active python plugins | db_manager; MetaSearch; processing
```

</details>

Also apparently fails with 3.10 using Windows 10.

**Additional context**

**Comment by tjukanovt** [comment]
I was able to recreate the bug on Windows 10 and QGIS 3.14.15 and the following set-up. 
`
QGIS version
3.14.15-Pi
QGIS code revision
d5114d2cfa
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
DigitransitGeocoder; 
GlobeBuilder; 
`
First try worked fine, but second got QGIS **totally** stuck.

**Comment by troopa81** [comment]
Like said in the gis.stackexchange ticket I do think it's a matter of scope. 

The application crashes when accessing the feedback object because this one *could* (or not, that's why it crashes sometimes and sometimes not) have been deleted by the Python garbage collector when the task is running. 

`feedback` object is destroyed at the end of the `run_task` method call. But the task is running is an other thread and could access the object after the method end.

Just move the `feedback` and `context` variable initialization at the beginning and you see it works all the time

```python
from functools import partial
from qgis.core import (QgsTaskManager, QgsMessageLog,
                       QgsProcessingAlgRunnerTask, QgsApplication,
                       QgsProcessingContext, QgsProcessingFeedback,
                       QgsProject)

MESSAGE_CATEGORY = 'AlgRunnerTask'
context = QgsProcessingContext()
feedback = QgsProcessingFeedback()
    
def task_finished(context, successful, results):
    if not successful:
        QgsMessageLog.logMessage('Task finished unsucessfully',
                                 MESSAGE_CATEGORY, Qgis.Warning)
    output_layer = context.getMapLayer(results['OUTPUT'])
    # because getMapLayer doesn't transfer ownership, the layer will
    # be deleted when context goes out of scope and you'll get a
    # crash.
    # takeMapLayer transfers ownership so it's then safe to add it
    # to the project and give the project ownership.
    if output_layer and output_layer.isValid():
        QgsProject.instance().addMapLayer(
             context.takeResultLayer(output_layer.id()))

def run_task():
    alg = QgsApplication.processingRegistry().algorithmById(
                                          'qgis:randompointsinextent')

    params = {
        'EXTENT': '0.0,10.0,40,50 [EPSG:4326]',
        'MIN_DISTANCE': 0.0,
        'POINTS_NUMBER': 50000,
        'TARGET_CRS': 'EPSG:4326',
        'OUTPUT': 'memory:My random points'
    }
    task = QgsProcessingAlgRunnerTask(alg, params, context, feedback)
    task.executed.connect(partial(task_finished, context))
    QgsApplication.taskManager().addTask(task)

```
