### ISSUE TITLE
Batch processing changes the order and type of model's inputs

### ISSUE THREAD

**Issue by andremano** [qgis/QGIS#38590]
When trying to run the model attached to this report as a batch process, the order and type of inputs is changed and/or swaped.
Screenshot below shows how the batch dialog looks in 3.10 (correct): 

![image](https://user-images.githubusercontent.com/6665872/92169103-1cb00400-ee3b-11ea-827b-3ba3db9dafad.png)

The same dialog under QGIS 3.14 however looks like this: 

![image](https://user-images.githubusercontent.com/6665872/92169868-4c5f0c00-ee3b-11ea-8ba4-39f90446eeb3.png)

Maybe relevant information: the model was created some time ago but using QGIS 3.4 if I recall correctly.
[collapse_risk.zip](https://github.com/qgis/QGIS/files/5171198/collapse_risk.zip)

**Comment by nyalldawson** [comment]
This was fixed in 3.14.15

**Comment by andremano** [comment]
AH great! Thanks!
