### ISSUE TITLE
Crash while open vector affine transform

### ISSUE THREAD

**Issue by ayadiAhmedSaid** [qgis/QGIS#38600]
This happens a lot when I open affine transform QGIS crashes even before I start running the algorithme

Crash ID: 5269db1b8e2808988380922fb9afc9755af133b9

Stack Trace

QgsMapRendererParallelJob::cancelWithoutBlocking qgsmaprendererparalleljob.cpp:132

QGIS Info
QGIS Version: 3.14.1-Pi
QGIS code revision: de08d6b71d
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment]
> affine transform

@ayadiAhmedSaid isn't this a 3rd party plugin?

**Comment by gioman** [comment]
Closing for lack of feedback.
