### ISSUE TITLE
"Export to GPKG" missing(?)

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#38614]
In processing there is a "export to spatialite" tool, that does exactly what the name suggests.

Seems a bit weird that there is no equivalent "export to gpkg" tool, as we advertise the gpkg format as a first class citizen in QGIS.

One note:
this tool is very handy especially in batch mode, to export in one go several layers to a single datasource, anyway it is a bit unconvenient that the SL datasource must exist beforehand. It would be better the tool to be able to create one on the fly if necessary.

Second note: trying to use the "export to spatialite" on gpkg rather than a SL datasource makes qgis fails silently: no errors but also no layer exported.

**Comment by alexbruy** [comment]
Duplicates #24003.
