### ISSUE TITLE
Style dialog dows not show render example when using "Meters at scale"

### ISSUE THREAD

**Issue by mlechner** [qgis/QGIS#38631]
When using Meters at Scale to style a line layer for the Simple Line in Single symbol the render example in the style dialog does not show up. This happens as well when switching to categorized symbology.

**How to Reproduce**

Open a line layer. Set "Symbology" to "Single symbol" and the "Stroke width" of "Simple Line" to 5.0 an "Meters at scale".
The preview of the line giving an idea on how this will look like disapears.
Its even getting worse when changing the "Symbology" to "categorized" and classifying the dataset.

**QGIS and OS versions**

QGIS 3.10.8, 3.14.15, may be more

**Comment by roya0045** [comment]
Could it be possible that your current POV is too far away to display 5meters?

**Comment by mlechner** [comment]
> Could it be possible that your current POV is too far away to display 5meters?

Its not the rendering of the features in the mapcanvas. The rendering in the mapcanvas is absolutely ok (besides a possible discussion if the features should disapear when zooming out a lot - they do not, but are still rendered as a hairline). But the redering preview in the styles dialog widgets and the symbol(s) in the legend can not be seen.

**Comment by andreasneumann** [comment]
Might be related to https://github.com/qgis/QGIS/issues/38606 ?
If it is the same, then this will be handled by our support contract. Should be fixed during feature freeze and released in 3.16, hopefully also backported to 3.10.

**Comment by mlechner** [comment]
@andreasneumann without double checking, I'm pretty sure it's a duplicate to #38606 
Closing this issue. Thnx.
