### ISSUE TITLE
Organize columns not working if the table is empty

### ISSUE THREAD

**Issue by SrNetoChan** [qgis/QGIS#38653]
**Describe the bug**

While preparing a couple of layers for final users, I was using Organize columns to change the order of some fields and hide some other. Some layers it didn't seem to work, no matter what I did. I realized then that it only happens on empty layers. If I add a row, all my configuration would show up immediately. But, if I remove all rows, the problem appears again.

**How to Reproduce**

1. Create a new table, a scratch layer will do.
2. Add a few columns, 3 or 4
3. Open the attribute table
4. Rigth-click one of the columns and open the organize columns
5. Change the order of the columns and hide some
6. Notice that the changes does not seem to be applied except for the number of columns showing
7. Add a feature. Notice that the order is fixed
8. remove all feature. Notice that the order goes back to the unsorted one.

![Peek 2020-09-09 00-56](https://user-images.githubusercontent.com/3607161/92538917-e8bc5080-f237-11ea-877f-97e686177c78.gif)

**QGIS and OS versions**

QGIS version | 3.10.9-A Coruña | QGIS code revision | bf47e9d3e1
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 10.12 (Ubuntu 10.12-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Ubuntu 18.04.5 LTS
Active python plugins | Mergin; socarto_recart_tools; db_manager; processing

**Additional context**

**Comment by SrNetoChan** [comment]
Also confirmed in master:


QGIS version | 3.15.0-Master | QGIS code revision | 014de9614d
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 12.4 (Ubuntu 12.4-1.pgdg18.04+1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Ubuntu 18.04.5 LTS
Active python plugins | Mergin; socarto_recart_tools; processing; db_manager

**Comment by troopa81** [comment]
This issue had already been reported but I fail to find it.

This is a Qt issue, I created a [ticket](https://bugreports.qt.io/browse/QTBUG-72922) in january 2019 but as you can see, there is not a lot of activity...

**Comment by SrNetoChan** [comment]
> This issue had already been reported but I fail to find it.
> 
> This is a Qt issue, I created a [ticket](https://bugreports.qt.io/browse/QTBUG-72922) in january 2019 but as you can see, there is not a lot of activity...
> 

Maybe it was closed for being a upstream problem.

**Comment by troopa81** [comment]
> Maybe it was closed for being a upstream problem

The QGIS issue was closed indeed. But even in closed ticket I can't find it.

**Comment by troopa81** [comment]
I close the ticket because it's an upstream problem
