### ISSUE TITLE
QGIS 3.14.15 Crashing on exit

### ISSUE THREAD

**Issue by Mikester-Calgary** [qgis/QGIS#38667]
Crash ID: 533376728e5523b2835d2f7e33464e1f304dd042

Stack Trace

QDockWidget::toggleViewAction :
QgisApp::removeDockWidget qgisapp.cpp:4410
meth_QgisInterface_removeDockWidget sip_guipart5.cpp:368320
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyEval_EvalCodeEx :
PyEval_EvalCode :
PyArena_Free :
PyRun_StringFlags :
QgsPythonUtilsImpl::evalString qgspythonutilsimpl.cpp:529
QgsPythonUtilsImpl::unloadPlugin qgspythonutilsimpl.cpp:648
QgsPluginRegistry::unloadAll qgspluginregistry.cpp:193
QgisApp::saveWindowState qgisapp.cpp:5106
QMetaObject::activate :
QCoreApplicationPrivate::execCleanup :
QCoreApplication::exec :
main main.cpp:1618
BaseThreadInitThunk :
RtlUserThreadStart :

Crash report below;

QGIS Info
QGIS Version: 3.14.15-Pi
QGIS code revision: d5114d2cfa
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

4. See error -->

**QGIS and OS versions**

**Additional context**

**Comment by Gustry** [comment]
Same crash ID https://github.com/qgis/QGIS/issues/33207
Remove the plugin to fix it.
