### ISSUE TITLE
QGIS unexpectedly ended

### ISSUE THREAD

**Issue by tarhunageodata** [qgis/QGIS#38664]
**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by tarhunageodata** [comment]
Crash ID: 533376728e5523b2835d2f7e33464e1f304dd042


Stack Trace


QDockWidget::toggleViewAction :
QgisApp::removeDockWidget qgisapp.cpp:3960
meth_QgisInterface_removeDockWidget sip_guipart3.cpp:243832
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyEval_EvalCodeEx :
PyEval_EvalCode :
PyArena_Free :
PyRun_StringFlags :
QgsPythonUtilsImpl::evalString qgspythonutilsimpl.cpp:529
QgsPythonUtilsImpl::unloadPlugin qgspythonutilsimpl.cpp:648
QgsPluginRegistry::unloadAll qgspluginregistry.cpp:191
QgisApp::saveWindowState qgisapp.cpp:4653
QMetaObject::activate :
QCoreApplicationPrivate::execCleanup :
QCoreApplication::exec :
main main.cpp:1606
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.10.9-A Coru�a
QGIS code revision: bf47e9d3e1
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Runni
ng against GDAL: 3.0.4



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by tarhunageodata** [comment]
Please help to solve this issue.

**Comment by Gustry** [comment]
Same crash ID https://github.com/qgis/QGIS/issues/33207
Remove the plugin to fix it.
