### ISSUE TITLE
gdal_rasterize not working when file has '&' symbol in name

### ISSUE THREAD

**Issue by seanaxn1135** [qgis/QGIS#38674]
**Describe the bug**

Say I have a .shp file named 3-4-Sports&Recreation,.shp. When I process it with gdal: rasterize in the QGIS Desktop 3.12.2, it produces an error.

**How to Reproduce**

1. Name a .shp file with the symbol '&' 
(Example of what I used: 3-4-Sports&Recreational.shp)

2. Open processing toolbox in QGIS Desktop
3. Run a process with the shp file mentioned in 1.
(I personally used gdal: rasterize)

**Output**
2020-09-10T18:17:04     INFO    gdal_rasterize -l 3-4-Sports&Recreation -a 1 -tr 10.0 10.0 -a_nodata 0.0 -te (epsg value) -ot Float32 -of GTiff "C:\\-insert filepath-\\3-4-Sports&Recreation.shp" C:/Users/seteg/AppData/Local/Temp/processing_wXkxBr/9666ad0115c94e149c3d41dd31f23216/OUTPUT.tif
2020-09-10T18:17:04     INFO    GDAL execution console output
             ERROR 6: One and only one of -3d, -burn or -a is required.
             
             Usage: gdal_rasterize [-b band]* [-i] [-at]
             
              {[-burn value]* | [-a attribute_name] | [-3d]} [-add]
             
              [-l layername]* [-where expression] [-sql select_statement]
             
              [-dialect dialect] [-of format] [-a_srs srs_def] [-to "NAME=VALUE"]*
             
              [-co "NAME=VALUE"]* [-a_nodata value] [-init value]*
             
              [-te xmin ymin xmax ymax] [-tr xres yres] [-tap] [-ts width height]
             
              [-ot {Byte/Int16/UInt16/UInt32/Int32/Float32/Float64/
             
              CInt16/CInt32/CFloat32/CFloat64}] [-optim {[AUTO]/VECTOR/RASTER}] [-q]
             
              
             
             'Recreation' is not recognized as an internal or external command,
             
             operable program or batch file.

**Solution**
The process is able to run if you change the name of the shp file to exclude '&' symbol. (eg: SportsRecreation.shp)
Not sure if this is intended.

Please close this issue if is intended.

Thanks.

**QGIS and OS versions**

QGIS Desktop 3.12.2
Windows 10 Home OS

**Comment by gioman** [comment]
@seanaxn1135 does it happens if you run gdal_rasterize from the command line?

**Comment by seanaxn1135** [comment]
> @seanaxn1135 does it happens if you run gdal_rasterize from the command line?

It works when I run it from the OSGeo4W Shell
