### ISSUE TITLE
Custom CRS does not always switch parameters correctly from wkt to proj string

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#38689]
1. Open Settings --> Custom Projection... dialog
1. With "proj string" format enabled, paste  the following parameters: `+proj=vandg +lon_0=0 +x_0=0 +y_0=0 +R_A +a=6371000 +b=6371000 +units=m +no_defs`. You can test; it's returned as valid definition.
1. Switch to wkt format: you get a conversion of the parameters. Great!
```
PROJCRS["unknown",
    BASEGEOGCRS["unknown",
        DATUM["unknown",
            ELLIPSOID["unknown",6371000,0,
                LENGTHUNIT["metre",1,
                    ID["EPSG",9001]]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8901]]],
    CONVERSION["unknown",
        METHOD["Van Der Grinten"],
        PARAMETER["Longitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["False easting",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]]]
```
1. Switch back to proj string format: you get the same text as for wkt (except some indentation changes) and not the expression I enter at the beginning
![image](https://user-images.githubusercontent.com/7983394/92834229-104b1e80-f3da-11ea-9393-bd44711e6ac7.png)

NOTA: I tried with copy-pasting the epsg4326 proj parameters and the switch between the formats works as expected

QGIS version | 3.15.0-Master | QGIS code revision | 5c241c84be
-- | -- | -- | --
Compiled against Qt | 5.12.8 | Running against Qt | 5.12.8
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.4 (Ubuntu 12.4-0ubuntu0.20.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Ubuntu 20.04.1 LTS | This copy of QGIS writes debugging output.
Active python plugins | db_manager; MetaSearch; processing

**Comment by nyalldawson** [comment]
Can the projinfo tool convert this wkt to proj string? Not all wkt is representable as a proj string...

**Comment by rouault** [comment]
I can't reproduce this with QGIS master and PROJ master (with PROJ 6.3 branch, converting the WKT to PROJ.4 string works, so I don't think this is a PROJ issue)
