### ISSUE TITLE
When running in place "repair geometries" with a selection it is unclear if it only affects the selected features

### ISSUE THREAD

**Issue by m-kuhn** [qgis/QGIS#38680]
Run "repair geometries" in place with a selection. The algorithm is started without a dialog and reports "successfully finished". It is unclear to the user if it was selected only or not. Checking in the processing history, the flag "selectedOnly=True" can be seen.

I see two options:

 - Offer a dialog to let the user check/uncheck "selected only"
 - Report the number of features in the confirmation dialog of the in place editing

**Comment by SrNetoChan** [comment]
I would prefer the second solution. IMHO This in place algorithms are much more effective if they can skip dialogs.

**Comment by m-kuhn** [comment]
If you "delete features" and you have selected features outside the currently visible extent, you will be warned. A confirmation dialog showing the number of features would be analogue.
No strong opinion, I can very well live with a confirmation only and trust the undo.
