### ISSUE TITLE
QGIS cannot open properly plugins and other

### ISSUE THREAD

**Issue by gudiyagani** [qgis/QGIS#38686]
![qgis ladm-col](https://user-images.githubusercontent.com/56818858/92775840-598c7580-f3bc-11ea-8e98-550c7c46efbf.png)
![python error](https://user-images.githubusercontent.com/56818858/92775885-63ae7400-f3bc-11ea-82ee-f3b47a4cde4d.png)
![python error-](https://user-images.githubusercontent.com/56818858/92775915-6a3ceb80-f3bc-11ea-9602-6cbcf665857b.png)
![qgis error-](https://user-images.githubusercontent.com/56818858/92775967-732dbd00-f3bc-11ea-80a1-38f5f7e9e390.png)

IMPORTANT:

Do NOT use GitHub to post any questions or support requests!
They will be closed immediately and ignored.
Questions should go to the qgis-user mailing list at https://lists.osgeo.org/mailman/listinfo/qgis-user
or other support forums such as https://gis.stackexchange.com/.

GitHub issues are for bug reports and suggestions for new features.

**Comment by gioman** [comment]
@gudiyagani QGIS 3.12 is outdated, update to 3.14. Also you seem to have a local issue with files permissions.

**Comment by gioman** [comment]
@gudiyagani also... you get that messages with all plugins, or just specific ones?

**Comment by gacarrillor** [comment]
Hi @gudiyagani , the first screenshot is a warning. You can solve it in this way (documented in the plugin's GitHub repo):

https://github.com/SwissTierrasColombia/Asistente-LADM-COL/issues/347#issuecomment-655597209

Don't know about the other screenshots.

**Comment by gioman** [comment]
> Don't know about the other screenshots.

they seems other 3rd party plugins error messages.

**Comment by gacarrillor** [comment]
> > Don't know about the other screenshots.
> 
> they seems other 3rd party plugins error messages.

Right, I would invite @gudiyagani to create issues for those specific plugins in each plugin's issue page, since this is not a problem of QGIS itself.
