### ISSUE TITLE
Double highlight frames over world map in CRS properties dialogs

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#38690]
I'm not sure there should be two frames over the world map
![image](https://user-images.githubusercontent.com/7983394/92838998-c36a4680-f3df-11ea-80a1-d62c3d246398.png)

**Comment by nyalldawson** [comment]
One is the canvas extent, the other is the area of use of the CRS

**Comment by DelazJ** [comment]
Ah... OK. Closing then.
I never noticed (probably because my area of work is often small within the CRS extent) or is it a new feature?
