### ISSUE TITLE
Can't initiate class QgsAbstractLayoutIterator to print multiple pages in one pdf

### ISSUE THREAD

**Issue by TANK2003** [qgis/QGIS#38696]
As describe in the doc [hhttps://qgis.org/api/classQgsLayoutExporter.html#a5da9df5b81c7c60e46395f7a6fccc22c](url), to print multiple pages in one PDF we can use the static method `QgsLayoutExporter.exportToPdf` with first parameter a QgsAbstractLayoutIterator . But how to get / construct a QgsAbstractLayoutIterator object without using a Atlas ?

Thanks

**Comment by nyalldawson** [comment]
Not a bug -- it's an abstract class, you need to use one of the existing subclasses (e.g. QgsLayoutAtlas) or create your own subclass
