### ISSUE TITLE
Field filter in attribute table does not work for boolean

### ISSUE THREAD

**Issue by huber-j** [qgis/QGIS#38704]
Situation:
Database layer (tested with point layers on a postgis server and in a Geopackage) with one or more fields of type boolean (t/f).

When a boolean field is selected as a "Field Filter" in the bottom left menu of the attribute table, the field name appears with a checkbox next to it. As soon as the checkbox is clicked (set either to "true" or "false") all entries in the attribute table disappear.

Filtering works when using an advanced filter expression like
"this_bool_field" IS TRUE

So there seems to be a problem with the standard field filter. Tested on Windows 10 with QGIS 3.14.15-Pi and Master (3.15.0 d6a761d980).

**Comment by gioman** [comment]
@huber-j duplicate of https://github.com/qgis/QGIS/issues/37794 ?

**Comment by huber-j** [comment]
Sorry, yes - somehow I missed that one when looking for entries before creating the ticket.
