### ISSUE TITLE
Server GetLegendGraphics doesn't take into account of HEIGHT/WIDTH parameters

### ISSUE THREAD

**Issue by troopa81** [qgis/QGIS#38706]
**Describe the bug**

QGIS Server GetLegendGraphics seems to not take into account HEIGHT/WIDTH and SRCWIDTH/SRCHEIGHT parameters. Whatever you set for these parameters, the result is the same.

**How to Reproduce**

[bug_legendgraphics_hw.zip](https://github.com/qgis/QGIS/files/5210024/bug_legendgraphics_hw.zip)

1. Start QGIS Server with the above projet and datas
2. execute following GetLegendGraphics request http://localhost:8000/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetLegendGraphic&LAYER=points&FORMAT=image/png&STYLE=d%C3%A9faut&SLD_VERSION=1.1.0&TRANSPARENT=true&HEIGHT=500&SRCWIDTH=500
3. Change the HEIGHT/WIDTH parameters or the SRCWIDTH/SRCHEIGHT
4. Image is always the same and has the same size 81 x 68

This issue is related to this documentation issue https://github.com/qgis/QGIS-Documentation/pull/6005 

@signedav @pblottiere Any thoughts on that?

**QGIS and OS versions**

QGIS master
Linux Debian bullseye

**Additional context**

From what I understand HEIGHT/WIDTH controls the legend output size and SRCWIDTH/SRCHEIGHT is used to determine the size of the symbols when used both in the request. If you set only HEIGHT/WIDTH parameters then it's used to determine the size of the symbols, in order to keep backwards compatility. 

A quick look at the code tells me that legend settings size is not used when [computing legend size](https://github.com/qgis/QGIS/blob/master/src/core/qgslegendrenderer.cpp#L148)

**Comment by elpaso** [comment]
I'm not so sure this is a bug, it is probably more a feature request: there is no way to set the legend image size unless you are using a `RULE`. In that case you can specify the WIDTH and HEIGHT and they determine the generated image size.

**Comment by pblottiere** [comment]
Hello @troopa81,

> QGIS Server GetLegendGraphics seems to not take into account HEIGHT/WIDTH and SRCWIDTH/SRCHEIGHT parameters. > Whatever you set for these parameters, the result is the same.

You can take a look to the `TestQgsServerWMSGetLegendGraphic::test_wms_getLegendGraphics_rule` unit test. In this case you have an example where `WIDTH/HEIGHT` parameters have a direct impact on the resulting image.

**Comment by troopa81** [comment]
Thanks @elpaso and @pblottiere for these informations, I managed to make it work.

I'm gonna propose a documentation modification to reflect this behavior, and close this ticket.
