### ISSUE TITLE
DE PUNTOS A LINEAS

### ISSUE THREAD

**Issue by Ramon-Cabello** [qgis/QGIS#38708]
En la versión en español de QGIS no existe la función de PUNTOS A LINEAS (así como existe por ejemplo de POLÍGONOS A LINEAS O DE LINEAS A POLÍGONOS). En la versión en portugués si existe. En la versión antigua de QGIS 2.18 existía el complemento POINT2ONE que hacía esa función muy bien. En las versiones nuevas de QGIS ¿hay algún complemento que haga esa función?. Desde ya muchas gracias.

**Comment by gioman** [comment]
@Ramon-Cabello please file again in English, thanks!

**Comment by Ramon-Cabello** [comment]
In the Spanish version of QGIS there is no POINTS TO LINES function (as there is, for example, from POLYGONS TO LINES OR FROM LINES TO POLYGONS). In the Portuguese version if it exists. In the old version of QGIS 2.18 there was the POINT2ONE plugin that did that function very well. In the new versions of QGIS, is there a plugin that does this function? From already thank you very much.

**Comment by uclaros** [comment]
What you're looking for is the *Points to paths* processing algorithm

**Comment by gioman** [comment]
"pontos a ruta".
