### ISSUE TITLE
The TIN interpolation tool does not work within the processing models

### ISSUE THREAD

**Issue by sebastianmr6** [qgis/QGIS#38717]
Checklist before submitting

- [ ] Search through existing issue reports and gis.stackexchange.com to check whether the issue already exists
https://gis.stackexchange.com/questions/288363/the-tin-interpolation-tool-does-not-work-within-the-processing-models-in-qgis-3

**Describe the bug**
I am creating a model, at the moment I fill the parameters of the TIN Interpolation tool it is not possible to select layers that come out of a previous process

**How to Reproduce**

1. Create a blank model
2. Add a line layer
3. Add the TIN Interpolation process
4. Enter the parameters using the information generated in the same model
5. It is not possible to select the input layer none generated in the same model

**QGIS and OS versions**

Versión de QGIS | 3.10.9-A Coruña | Revisión del código de QGIS | bf47e9d3e1
-- | -- | -- | --
Compilado contra Qt | 5.11.2 | Ejecutándose contra Qt | 5.11.2
Compilado contra GDAL/OGR | 3.0.4 | Ejecutándose contra GDAL/OGR | 3.0.4
Compilado contra GEOS | 3.8.1-CAPI-1.13.3 | Ejecutándose contra GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
Versión del cliente PostgreSQL | 11.5 | Versión de SpatiaLite | 4.3.0
Versión de QWT | 6.1.3 | Versión de QScintilla2 | 2.10.8
Compilado contra PROJ | 6.3.2 | Ejecutándose contra PROJ | Rel. 6.3.2, May 1st, 2020
Versión del SO | Windows 10 (10.0)
Active python plugins | openlayers_plugin; Qgis2threejs; db_manager; MetaSearch; processing

![Captura de pantalla 2020-09-12 163901](https://user-images.githubusercontent.com/32719931/93005436-7c32a180-f516-11ea-8ad8-765a6dfd973d.jpg)

**Comment by alexbruy** [comment]
Duplicates #30029.
