### ISSUE TITLE
Processing: when saving results to PostGIS the username/password is asked even if the credential is stored in the connection properties

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#38718]
QGIS 3.10 on all OSes.

Having a PostGIS connection with the username/password stored/saved, when using a QGIS processing tool that allows to save the results to PostGIS the credential is asked to the user. This apparently happens only once, the first time this functionality is used in a working session. If QGIS is closed and reopened than the credential is asked again.

**Comment by nyalldawson** [comment]
This should be fixed in 3.14 and later -- can you confirm? (If so, the changes are way too intrusive to permit backporting, so I'd suggest closing)

**Comment by gioman** [comment]
Confirmed working on 3.14.
