### ISSUE TITLE
Could not commit changes to layer, field with index 4 is not the same!

### ISSUE THREAD

**Issue by DickRawson** [qgis/QGIS#38712]
I was editing fields in an attribute table view. I also added a column for unstructured commentary. I clicked the floppy-diskette icon to SAVE the attribute table for layer Places_points and received this result:

-----------------------

```
Could not commit changes to layer Places_points

Errors: SUCCESS: 1 attribute(s) added.
ERROR: field with index 4 is not the same!
Provider: ogr
Storage: SQLite
expected field: name=Status type=QString typeName=string len=40 precision=0
retrieved field: name=status type=QString typeName=String len=40 precision=0

```
----------------------

I notice some differences in capitalization between the expected and retrieved lines.

QGIS 3.14.15.
Windows 10, Version 2004. OS build 19041.508

**Comment by gioman** [comment]
@DickRawson steps/data to replicate?

**Comment by DickRawson** [comment]
So far, attempts to replicate with a simpler project operated correctly instead of failing. So, I cannot provide steps and data to replicate. The actual project gave another failure today, however. 

2020-09-13 17:00-ish UTC-7
Could not commit changes to layer Places_points

Errors: SUCCESS: 1 attribute(s) added.
ERROR: field with index 5 is not the same!
Provider: ogr
Storage: SQLite
expected field: name=Hide type=bool typeName=bool len=0 precision=0
retrieved field: name=hide type=bool typeName=Boolean len=0 precision=0

In both these examples, retrieved values differ from the expected values, but appear to be different encodings for the same meanings: e.g., string vs. String, and bool vs. Boolean. There seems to be confusion about the rules.
