### ISSUE TITLE
Issue to Import DWG points into QGIS

### ISSUE THREAD

**Issue by robheld1985** [qgis/QGIS#38723]
hi
I have a question with the attached DWG file 
> step 1  - I create geopackage layer in the admin directory

> step 2  - from project I choose  - dwg/dxf import and a new windows open

> immediately  a red line appear which says  -  couldn't open layer list

> step 3  - after few seconds the  red line disappear but when im trying to
import a dwg - nothing happens

Any ideas?

thanks
[Konturpunkte.zip](https://github.com/qgis/QGIS/files/5215417/Konturpunkte.zip)

Rob

**Comment by robheld1985** [comment]
File Attached

**Comment by gioman** [comment]
@robheld1985 seems to work as expected here on 3.14

![Screenshot_20200914_102318](https://user-images.githubusercontent.com/1951107/93068438-5c18f480-f674-11ea-92ea-1211aeb7c72d.png)

**Comment by gioman** [comment]
Closing for lack of feedback.

**Comment by M5610020** [comment]
![image](https://user-images.githubusercontent.com/43448202/163436355-1e604992-03fa-4108-bc6a-cad7998ae9df.png)
I get this issue while importing DWG to QGIS using Geopackage.
