### ISSUE TITLE
incorrect representation of the collapsed legend in the layout.

### ISSUE THREAD

**Issue by FERRATON** [qgis/QGIS#38729]
The leader line of collapsed legend are not correctly positioned in the layout.
The PDF export is correct as well as the view in the legend properties.
see see attachment.
QGIS 3.10.6
![2020-09-14 11_32_34-_Mise en page 1](https://user-images.githubusercontent.com/2129643/93069675-3f81ba00-f67e-11ea-93c7-cdd80a62a147.png)

**Comment by nyalldawson** [comment]
This is fixed in 3.14, but the changes are intrusive to backport to 3.10
