### ISSUE TITLE
CRS Selector asks: Specify CRS for layer Annotations

### ISSUE THREAD

**Issue by raymondnijssen** [qgis/QGIS#38739]
**Describe the bug**

When
* starting QGIS
or
* creating a new empty project
or
* closing the application

while QGIS settings are set to "Prompt for CRS" for new layers without CRS info

the CRS Selector Dialog pops up with the question:
"Specify CRS for layer Annotations"

**How to Reproduce**

1. Settings -> Options -> CRS: CRS for Layers: "Leave as an unknown CRS (no action)"
2. Project -> New
(new project opens without problem)
3. Settings -> Options -> CRS: CRS for Layers: "Prompt for CRS"
4. Project -> New
(CRS Selector appears)

**QGIS and OS versions**

QGIS version | 3.15.0-Master | QGIS code revision | 4fe3d2f4e6
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.6.2-CAPI-1.10.2 4d2925d6
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 10.14 (Ubuntu 10.14-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Ubuntu 18.04.5 LTS
Active python plugins |  

**Additional context**

Seems like something in the background is creating a layer "Annotations" without CRS info.

**Comment by pigreco** [comment]
I confirm, and it's annoying

## OSGeo4W64 WIn 10
