### ISSUE TITLE
Using QGIS on a Microsoft surface pro

### ISSUE THREAD

**Issue by birder12** [qgis/QGIS#38746]
I was wondering if QGIS actually works on a microsoft surface pro? I downloaded it and everything, but when I try open a .shp file the following error comes up: Layer is not valid: The layer C:/Users/Izzyg/Documents/lab 1/__MACOSX/GEOG2480_F20_Lab01Data/countries/ne_10m_admin_0_countries.shp is not a valid layer and can not be added to the map. Reason: 

IMPORTANT:

Do NOT use GitHub to post any questions or support requests!
They will be closed immediately and ignored.
Questions should go to the qgis-user mailing list at https://lists.osgeo.org/mailman/listinfo/qgis-user
or other support forums such as https://gis.stackexchange.com/.

GitHub issues are for bug reports and suggestions for new features.

**Comment by NathanW2** [comment]
Yes QGIS will work fine on the Surface Pro.  That sound like a corrupt or
missing files with your shapefiles.

**Comment by nyalldawson** [comment]
Can you please transfer this question to the QGIS mailing list at https://lists.osgeo.org/mailman/listinfo/qgis-user
or other support forums such as https://gis.stackexchange.com/ ? It's not a QGIS bug.
