### ISSUE TITLE
QGIS crashes when enabling Processing

### ISSUE THREAD

**Issue by grantboxer** [qgis/QGIS#38749]
This version of QGIS sometimes does not run and when it does run when I go to enable the Processing toolbox, QGIS crashes.

QGIS version | 3.14.16-Pi | QGIS code revision | a235a149f0
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | quick_map_services; SpreadsheetLayers; db_manager

**Comment by nicogodet** [comment]
Related to https://github.com/qgis/QGIS/issues/38483

**Comment by lozpeng** [comment]
yes,not only with 3.14.16 ,it has the same problem with 3.15-master if try to enable processing plugin.But the application will not crash, and the processing toolbox is usable, then if close the application and restart qgis,it crashes.
logged as following :
-----------------
 An error has occurred while executing Python code: 

RecursionError: maximum recursion depth exceeded while calling a Python object 
Traceback (most recent call last):
  File "F:/Dev/GIS/QGIS/Install/./python\qgis\utils.py", line 777, in _import
    new_path = os.environ['PATH']
  File "../Python37\lib\os.py", line 675, in __getitem__
    value = self._data[self.encodekey(key)]
  File "../Python37\lib\os.py", line 744, in encodekey
    return encode(key).upper()
  File "../Python37\lib\os.py", line 738, in check_str
    if not isinstance(value, str):
RecursionError: maximum recursion depth exceeded while calling a Python object


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.15.0-Master Master, 9e84cf0

**Comment by nicogodet** [comment]
@lozpeng https://github.com/qgis/QGIS/commit/44b4a75a0a772604c73c6bb0d901b2599e9779d9
Has been fixed in master

**Comment by jef-n** [comment]
and the other branches
