### ISSUE TITLE
PostgreSQL Foreign tables not visible, impossible to load

### ISSUE THREAD

**Issue by pcav** [qgis/QGIS#38757]
Tables imported in PostgreSQL as foreign data wrapper are not visible, neither from file browser nor from DB Manager. They can be listed smoothly from psql with the usual `\detr` command.
Unsure whether this can be listed as a feature request or as a bug.
QGIS 3.10 on Debian Sid.

**Comment by elpaso** [comment]
Did you try master? See https://github.com/qgis/QGIS/pull/34914

**Comment by pcav** [comment]
Fixed in https://github.com/qgis/QGIS/pull/34914
Thanks @elpaso
