### ISSUE TITLE
Warning message: Missing layer form dependency : layer 'layerX' requires layer 'layerY' to be loaded 

### ISSUE THREAD

**Issue by troopa81** [qgis/QGIS#38796]
**Describe the bug**

When loading a layer with a relation and relation reference widget set, I get the following warning message

> Missing layer form dependency : layer 'layerX' requires layer 'layerY' to be loaded but 'layerY' could not be found, please load it manually if possible.

I'm working on a PR

**How to Reproduce**

1. Load [projectA.zip](https://github.com/qgis/QGIS/files/5231122/projectA.zip)
2. The warning message appears

The widget seems to be working though

**QGIS and OS versions**

QGIS master
Debian bullseye

Works in 3.10

**Additional context**

**Comment by elpaso** [comment]
@troopa81 I did that development, do you want me to have a look?

**Comment by troopa81** [comment]
@elpaso No, I fixed it. I was writing test and about to propose a PR

**Comment by elpaso** [comment]
I see it was introduced by 6548dff38dec9a28a7915cb23bc89724d0d6b0b8, better ask @3nids to review that.

**Comment by elpaso** [comment]
@troopa81 I'm sorry but this was wrong. You changed the xml tag names (for no reason) and now we have this https://github.com/qgis/QGIS/issues/39025 (which has also another cause). I'm reverting this commit and please leave it to me.

**Comment by elpaso** [comment]
@troopa81 forget about that, I'm testing with a project created where relations were stored with old tag names. Sorry for the noise.
