### ISSUE TITLE
Processing “eliminate selected polygons” doesn't work with PyQGIS

### ISSUE THREAD

**Issue by PeterDrexel** [qgis/QGIS#38808]
QQGIS 3.14.15 on Windows 10 64bit

I try to use the processing-tool qgis:eliminateselectedpolygons in a script:

_tempvlayer = QgsVectorLayer(inshape, "tempLayer", "ogr")
QgsProject.instance().addMapLayer(tempvlayer)
processing.run("qgis:selectbyattribute", {'INPUT':tempvlayer,'FIELD':'area','OPERATOR':4,'VALUE':'5','METHOD':0})
processing.run("qgis:eliminateselectedpolygons", {'INPUT':tempvlayer,'MODE':2,'OUTPUT':outshapefile})_

It seems that the the selected features aren't taken into account.
Is this a bug?

See also https://stackoverflow.com/questions/62938288/function-eliminate-selected-polygons-doesnt-work-with-pyqgis

Thanks
Peter

**Comment by nyalldawson** [comment]
I can't reproduce -- this works fine for me.

**Comment by PeterDrexel** [comment]
Hi Nyall, 
thanks for looking into this issue!

It is not working here on Windows 10 64 bit, I tried also in 3.15. Master.
You can find a screencast and some sampledata in the zip.
Just run the following in the Python-console:

_inshapefile = 'd:/in.shp'
tempvlayer = QgsVectorLayer(inshapefile, "in", "ogr")
QgsProject.instance().addMapLayer(tempvlayer)
processing.run("qgis:selectbyattribute", {'INPUT':tempvlayer,'FIELD':'area','OPERATOR':4,'VALUE':'5','METHOD':0})
resshapefile = 'd:/res.shp'
processing.run("qgis:eliminateselectedpolygons", {'INPUT':tempvlayer,'MODE':2,'OUTPUT':resshapefile})
resvlayer = QgsVectorLayer(resshapefile, "res", "ogr")
QgsProject.instance().addMapLayer(resvlayer)_

Both source and result files have the same amount of features (704) and are identical.
If it would work, the number of features should go down to 16 (works when I use the toolbox manualy)

Thanks 
Peter


[eliminate.zip](https://github.com/qgis/QGIS/files/5345698/eliminate.zip)

**Comment by nyalldawson** [comment]
Confirmed -- thanks for the feedback!
