### ISSUE TITLE
Shift values issue while creating new field under DB Manager

### ISSUE THREAD

**Issue by remigods** [qgis/QGIS#38800]
Hi,
My colleague faces an peculiar issue under QGIS 2.18 and QGIS 3.14 (reinstalled twice!).
Under DB Manager, when running a classic SQL query with a fake field like below, values are shift compared to field names.

SELECT 'value_text' AS created_field, name, geom  -- name and geom come from a Postgres table1
FROM table1

Result:
name, geom          -- created_field is not displayed
value_text, MisterX -- values are shift and geom values are dropped for any weird reason...

This bug can be avoided using a formula instead of the created field like 'value_text'||'' AS created_field.
I have no clue how could we solve this issue!
Is this an issue with the QGIS installation? Although we tried to install QGIS 3.14 in addition to QGIS 2.18.

Thanks in advance

**Comment by gioman** [comment]
@remigods can you post a real table and a real query we can test?

**Comment by remigods** [comment]
Not sure it will help, since it does work on another computer, but in case:

```
SELECT '2154' AS SCR, the_geom
FROM m_obs
LIMIT 10
```
![image](https://user-images.githubusercontent.com/49519083/93348898-18221d00-f837-11ea-948b-fdc663d82feb.png)

**Comment by gioman** [comment]
>  since it does work on another compute

@remigods please try with a new QGIS profile.

**Comment by remigods** [comment]
What do you mean by QGIS profile? A new fresh installation. It has been already done from 2.18 to 3.14 with the same issue.
Or try from another Windows session?

Thanks for the precision.

**Comment by gioman** [comment]
> What do you mean by QGIS profile? A new fresh installation. It has been already done from 2.18 to 3.14 with the same issue.
> Or try from another Windows session?

@remigods settings > user profiles > new profile. Do not install any 3rd party plugin before testing again (on the new profile).

**Comment by remigods** [comment]
Tried with a new profile, but the same bug occurs ...

**Comment by elpaso** [comment]
Works for me on current master:

![immagine](https://user-images.githubusercontent.com/142164/93853947-22b83880-fcb5-11ea-9e53-1d0c22046001.png)

**Comment by gioman** [comment]
@remigods is your observation specific to your table "m_obs"? if yes then post a dump with at least the table structure.

**Comment by remigods** [comment]
No, it happens whatever the table used. We just tried under another Windows session, and the same bug occurs.

Again, it does work when my colleague specifies a formula like '2154' || '' AS SCR.
This work on another computer too, without any issue. But installing again QGIS does not solve the problem, that's why I need your ideas.

Thanks!

**Comment by gioman** [comment]
> No, it happens whatever the table used. We just tried under another Windows session, and the same bug occurs.

@remigods tested too on 3.14 on a clean Windows machine on a PostGIS table, no issues.

**Comment by gioman** [comment]
Closing for lack of further feedback.
