### ISSUE TITLE
ERROR DE COMPLEMENTO AZIMUT DISTANCE CALCULATOR

### ISSUE THREAD

**Issue by Ramon-Cabello** [qgis/QGIS#38818]
Cuando utilizo la nueva versión de QGIS (10.9 La Coruña) y realizo el cálculo (de un polígono) - con el complemento Azimuths Distance Calculator - sale esta advertencia ""The limit of a patrimonial area must be a single part geometry". 
Si efectúo el mismo cálculo, con el mismo polígono, en Qgis 2.18 no tengo problemas.

**Comment by Ramon-Cabello** [comment]
When I use the new version of QGIS (10.9 La Coruña) and perform the calculation (of a polygon) - with the Azimuths Distance Calculator plugin - I get this warning "" The limit of a heritage area must be a geometry of a single part ".
If I do the same calculation, with the same polygon, in Qgis 2.18 I have no problems.

**Comment by nyalldawson** [comment]
This is an issue in the plugin, not in qgis itself
