### ISSUE TITLE
Enable appending layers to existing geopackage when using package layers algorithm

### ISSUE THREAD

**Issue by NyakudyaA** [qgis/QGIS#38812]
# Problem

The current implementation of package layer algorithm does not allow a user to append layers to an existing geopackage. 
The default behavior is to overwrite an existing geopackage even when a user hasn't specified the option to overwrite existing geopackage.

![Peek 2020-09-16 17-21](https://user-images.githubusercontent.com/2510900/93358704-190c7c00-f842-11ea-8bb7-5cf613ba0a3a.gif)

![geopkg](https://user-images.githubusercontent.com/2510900/93358778-2fb2d300-f842-11ea-9051-67eab08a76ad.png)

**NB** I think this should be a bug but I am not sure

**Comment by gioman** [comment]
@NyakudyaA did it worked as expected in previous QGIS releases?

**Comment by NyakudyaA** [comment]
> @NyakudyaA did it worked as expected in previous QGIS releases?

Just tested in 3.10.8-A Coruña and it works as expected

**Comment by roya0045** [comment]
Alg was not modified since Oct 2019, but the QgsVectorFileWriter has been modified. This might be the cause.

**Comment by uclaros** [comment]
The warning is misleading, the layer is actually appended to the existing geopackage if *Overwrite existing geopackage* is not checked.

**Comment by gioman** [comment]
> The warning is misleading, the layer is actually appended to the existing geopackage if _Overwrite existing geopackage_ is not checked.

I checked on 3.16.1 and seems to me too that it works as expected. Closing?

**Comment by uclaros** [comment]
No, the misleading message should be fixed first. I say change the title to
reflect current situation.

**Comment by gioman** [comment]
> No, the misleading message should be fixed first.

@uclaros that message does comes from the operating system? if yes can we handle it?
