### ISSUE TITLE
UnicodeDecodeError when opening *.qgs project with cyrillic text in the font name

### ISSUE THREAD

**Issue by MrChebur** [qgis/QGIS#38832]
**Describe the bug**

I am getting UnicodeDecodeError when I open a qgs project with Cyrillic symbols in the font name:

```
An error has occurred while executing Python code: 

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 0: invalid continuation byte 
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 0: invalid continuation byte


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.14.15-Pi Pi, d5114d2cfa 

Python Path:
C:/OSGEO4~1/apps/qgis/./python
C:/Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGEO4~1/apps/qgis/./python/plugins
C:\OSGEO4~1\apps\Python37
C:\OSGEO4~1\apps\Python37\Scripts
C:\OSGeo4W64\bin\python37.zip
C:\OSGEO4~1\apps\Python37\DLLs
C:\OSGEO4~1\apps\Python37\lib
C:\OSGeo4W64\bin
C:\OSGEO4~1\apps\Python37\lib\site-packages
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32\lib
C:\OSGEO4~1\apps\Python37\lib\site-packages\Pythonwin
C:/Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\username\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools
C:\Users\username\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools
C:/Users/username/Desktop/testing
```

Here is my [qgs_project.zip](https://github.com/qgis/QGIS/files/5238343/bugged_project.zip) with empty layout that only contains one text label. 
The label font contains cyrillic text causing this error. 
If you try to open the qgs file with a text editor, it will be a line like this:

`        <LabelFont description="MS Shell Dlg 2,60,-1,5,50,0,0,0,0,0,Обычный" style="Обычный"/>`

**QGIS and OS versions**

QGIS version
3.14.15-Pi
QGIS code revision
d5114d2cfa
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
AppendFeaturesToLayer; 
DigitizingTools; 
FreehandRasterGeoreferencer; 
latlontools; 
MagicWand-master; 
mapswipetool_plugin; 
qgsAzimuth; 
quick_map_services; 
valuetool; 
db_manager; 
MetaSearch; 
processing

**Comment by elpaso** [comment]
Looks like a plugin issue. Try with a clean profile.

**Comment by MrChebur** [comment]
@elpaso Indeed, when I open my project with a new profile, I don't get any errors. And after removing all plugins, the problem was resolved. Thank you so much!

**Comment by MrChebur** [comment]
By the way, this error was caused by the QuickMapServices plugin: https://github.com/nextgis/quickmapservices/issues/new
