### ISSUE TITLE
All "Create circle" edits on a 4326 layer (geo crs) in non geo crs projec generate flipped hamburgers buns

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS#38830]
I understand this is some projection artifact, but I think we should not create hamburgers when we tell to create circles :-)

Should it not be possible to create circles in a geographic crs layer (project?) maybe?

Or is it that a temporary layer cannot handle arc's? Nope, I saved it as gpkg and it still creates buns

![Screenshot-20200917112935-489x502](https://user-images.githubusercontent.com/731673/93452747-13ae4080-f8d9-11ea-88ca-f387f5a4efe9.png)

To reproduce:
- create a clean project in EPSG:28992
- load the layer 'provincies' (provinces) from this wms: https://geodata.nationaalgeoregister.nl/bestuurlijkegrenzen/ows?SERVICE=WMS& so you have some reference
- now create a temporary polygon layer and use 4326 as layer crs, the layer is immidiatly editable
- in menu Edit/Add Circle select one of the ways to create a circe (the all show the same artifact)
- note that DURING the edit the circle shown is perfectly fine

![Screenshot-20200917113253-597x538](https://user-images.githubusercontent.com/731673/93453182-a4851c00-f8d9-11ea-9b3f-3d80da53d083.png)

But AFTER the edit (right mouse button), the circle becomes the flipped hamburger...

When going back to epsg:4326 as project crs the geometries stay 'warped', so it is not *only* projection.

![Screenshot-20200917113005-416x373](https://user-images.githubusercontent.com/731673/93452798-24f74d00-f8d9-11ea-9859-4e69f2719cb4.png)

**Comment by gioman** [comment]
@rduivenvoorde duplicate of https://github.com/qgis/QGIS/issues/38493 ?

**Comment by rduivenvoorde** [comment]
@gioman yep definitly... I close this one
