### ISSUE TITLE
QGIS with GRASS not open because an error

### ISSUE THREAD

**Issue by alepr** [qgis/QGIS#38845]
I have a problem when i started qgis 3.14.16-2 in windows 10, when i try to start the app, appear this window. 
![image](https://user-images.githubusercontent.com/37672577/93494216-c632d300-f8da-11ea-86ee-673ab951335b.png)
and then this other window. 
![image](https://user-images.githubusercontent.com/37672577/93494534-245fb600-f8db-11ea-8902-cfe47a92f004.png)
I install the software with osgeo4w installer.

**Comment by jef-n** [comment]
Do you happend to have RStudio installed?  And did you install qgis-grass-plugin7 3.14.16-2 or 3.14.16-3?

**Comment by alepr** [comment]
Hi, thanks for the prompt reply, yes i have installed RStudio and i have de qgis-grass-plugin7 3.14.16-2 but i had the problem with the 3.14.16-1 too

**Comment by jef-n** [comment]
Please update OSGeo4W.

**Comment by alepr** [comment]
> Please update OSGeo4W (see also https://trac.osgeo.org/osgeo4w/ticket/641)

Thanks, it worked for me
