### ISSUE TITLE
Copying features as WKT or JSON doesn't work from attribute tables

### ISSUE THREAD

**Issue by y-vasyunin** [qgis/QGIS#38857]
Tested on a clean profile with a simple shape file, attached to this report.

**Describe the bug**

In the previous versions of QGIS, as I remember, when I selected a row in an attribute table and pressed CMD-C, I copied all attributes of the feature with WKT coordinates. Now it doesn't work: after pressing CMD-C, you get only a value from one cell, even if the whole row is highlighted. However, I should notice that copying the feature from a map canvas works and allows getting textual attributes with WKT coordinates.

**How to Reproduce**

1. Add a vector layer to your project.
2. Open its attribute table.
3. Select a feature so that the whole row is highlighted
4. Press CMD-C to copy the feature.
5. Get a single cell value instead of complete attributes of the feature.

<img width="682" alt="qgis" src="https://user-images.githubusercontent.com/18553297/93601871-205a9380-f9c2-11ea-9acc-8fcc9f46b55f.png">

* CMD-C executed in the attribute table (№1 in the picture) copies just a cell value `43`.
* CMD-C executed in the map canvas (№2), after the feature was selected by a "Select feature" tool, gives the following output:

```
wkt_geom	fid	name	category	note
MultiPoint ((-71.81940369994404705 -12.99918079999627629))	43	Lambrampata	big	
```

**QGIS and OS versions**

QGIS version | 3.14.15-Pi | QGIS code revision | d5114d2cfa

Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.28.0 | Running against SQLite | 3.28.0
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS 10.15
Active python plugins | QuickOSM; zoom_level; profiletool; quick_map_services; GeoCoding; QuickWKT; Qgis2threejs; OSMDownloader; lockzoom; valuetool; processing; db_manager

**Additional context**

My attribute table is in a dock mode.
[2020-09-18 qgis-bug-copy-as-wkt.zip](https://github.com/qgis/QGIS/files/5245729/2020-09-18.qgis-bug-copy-as-wkt.zip)

**Comment by uclaros** [comment]
This is the same as #37503 and should be fixed with #38810
You can use the *copy selected rows to clipboard* icon on the attribute table until you have a version that includes the fix.
