### ISSUE TITLE
Crash upon saving

### ISSUE THREAD

**Issue by Pachuquero** [qgis/QGIS#38866]
## User Feedback

Saving and closing and, subsequent, upon just closing crashes QGIS (corresponding reports below).

## Report Details

**Crash ID**: [ece7e42b38ddbef052745aa2d10e41e55b5b81bb](https://github.com/qgis/QGIS/search?q=ece7e42b38ddbef052745aa2d10e41e55b5b81bb&type=Issues)

**Stack Trace**
<pre>
QgisApp::projectTemporalRangeChanged :
QMetaObject::activate :
QgsProject::clear :
QgisApp::closeProject :
QgisApp::fileExit :
QWidget::event :
QgisApp::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::close_helper :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processCloseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.14.15-Pi
QGIS code revision: d5114d2cfa
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

-------------------------------------------------------

Second time around when just closing QGIS

## User Feedback

Closing QGIS caused a crash

## Report Details

**Crash ID**: [ece7e42b38ddbef052745aa2d10e41e55b5b81bb](https://github.com/qgis/QGIS/search?q=ece7e42b38ddbef052745aa2d10e41e55b5b81bb&type=Issues)

**Stack Trace**
<pre>
QgisApp::projectTemporalRangeChanged :
QMetaObject::activate :
QgsProject::clear :
QgisApp::closeProject :
QgisApp::fileExit :
QWidget::event :
QgisApp::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::close_helper :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processCloseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.14.15-Pi
QGIS code revision: d5114d2cfa
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
@Pachuquero Please test with a new QGIS profile.

**Comment by Pachuquero** [comment]
@gioman I created a new profile and same thing happened. I then installed the latest update 3.14.16-2 and (again) I can open my project but it crashes upon closing. Below the report.

I suppose I should add my layers to a new project...

## User Feedback

Opened and closed a previous project

## Report Details

**Crash ID**: [56f27d44bbafb5194f016810bfadc15d1d840442](https://github.com/qgis/QGIS/search?q=56f27d44bbafb5194f016810bfadc15d1d840442&type=Issues)


**Stack Trace**
<pre>
QgisApp::projectTemporalRangeChanged qgisapp.cpp:11204
QMetaObject::activate :
QgsProject::clear qgsproject.cpp:800
QgisApp::closeProject qgisapp.cpp:12986
QgisApp::fileNew qgisapp.cpp:6337
QgisApp::fileClose qgisapp.cpp:6310
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:439
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:439
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1618
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>


**QGIS Info**
QGIS Version: 3.14.16-Pi
QGIS code revision: df27394552
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
@Pachuquero any chance you can attach here one of your crashing projects (with the necessary data)?

**Comment by gioman** [comment]
What type of datasources you have in your crashing projects?

**Comment by Pachuquero** [comment]
Polygons, lines, PNG

**Comment by gioman** [comment]
> Polygons, lines, PNG

I mean, what format: shapefiles? esri file geodatabases? etc.

**Comment by Pachuquero** [comment]
sqlite made with QGIS

**Comment by gioman** [comment]
> sqlite's made with QGIS

can you attach the project and data?

**Comment by Pachuquero** [comment]
Just finished remaking the project and it has no issue now. Many thanks for all the efforts - much appreciated!

Cheers!
