### ISSUE TITLE
Digitize with curve button is un-synced

### ISSUE THREAD

**Issue by uclaros** [qgis/QGIS#38872]
**Describe the bug**
The *Digitize with curve* button may seem pressed while actual functionality is digitize without curve.

**How to Reproduce**
1. Add a line/polygon layer and start editing
2. Press the *Digitize with curve* button. The button is pressed and we're digitizing with curves.
3. Close and re-run QGIS
4. Add a line/polygon layer and start editing
5. The *Digitize with curve* button is still pressed but we're digitizing with straight segments instead of curves.
6. Clicking the button again makes it look not pressed and everything is back in sync

**QGIS and OS versions**
640f046c1c on Debian

**Additional context**
Ping @vcloarec

**Comment by uclaros** [comment]
I could also get the button disabled (unclickable) while the active tool is still *Add line feature*:
1. Add vector layer
2. Start editing
3. Click *Add feature* - *Digitize with curve* button becomes clickable
4. Put pc on sleep mode eg. close the laptop lid
5. Wake pc from sleep
6. We are still on *Add feature* mode but the *Digitize with curve* button is unclickable.

**Comment by vcloarec** [comment]
I think both are fixed by https://github.com/qgis/QGIS/pull/38880
