### ISSUE TITLE
Crash on loading large image file

### ISSUE THREAD

**Issue by IOUyi** [qgis/QGIS#38874]
## User Feedback

when i add Band 8 of Landsat 7 into input layer of Fill nodata

## Report Details

**Crash ID**: [699e72b28f022648573273aacffe382f9a675f9d](https://github.com/qgis/QGIS/search?q=699e72b28f022648573273aacffe382f9a675f9d&type=Issues)

**Stack Trace**
<pre>
VSICreateCachedFile :
OGRPGCommonAppendFieldValue :
OGRPGCommonAppendFieldValue :
OGRLayer::FeatureIterator::FeatureIterator :
OGRLayer::begin :
OGRLayer::GetFeatureCount :
QgsOgrProviderUtils::GDALOpenWrapper :
QgsOgrProviderUtils::quotedValue :
QgsOgrProviderUtils::GDALOpenWrapper :
QgsOgrProviderUtils::ogrTypeFromQgisType :
QgsOgrDbLayerInfo::QgsOgrDbLayerInfo :
QgsOgrProviderUtils::createEmptyDataSource :
QgsProviderRegistry::createProvider :
QgsVectorLayer::setDataProvider :
QgsVectorLayer::setDataSource :
QgsVectorLayer::QgsVectorLayer :
QgsProcessingRegistry::removeProvider :
QgsProcessingUtils::loadMapLayerFromString :
QgsProcessingUtils::mapLayerFromString :
QgsProcessingParameters::parameterAsLayer :
QgsProcessingParameters::parameterAsLayer :
QgsProcessingParameters::parameterAsRasterLayer :
PyInit__core :
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QMetaObject::activate :
QWidgetLineControl::`default constructor closure' :
QComboBox::setCurrentIndex :
QComboBox::setCurrentIndex :
QWidgetLineControl::`default constructor closure' :
QMetaObject::activate :
QAbstractItemModel::endInsertRows :
QSortFilterProxyModel::insertRows :
QSortFilterProxyModel::sortRole :
QSortFilterProxyModel::`default constructor closure' :
QMetaObject::activate :
QAbstractItemModel::endInsertRows :
QgsMapLayerModel::setAdditionalItems :
QgsProcessingMapLayerComboBox::setValue :
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QMetaObject::activate :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyFunction_FastCallDict :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.7-A Coru�a
QGIS code revision: 7b4ca4c8d0
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment]
> when i add Band 8 of Landsat 7 into input layer of Fill nodata

@IOUyi please

test on a new QGIS profile, if the problem persist:

1) attach/link the data
2) describe the **detailed** steps that lead to the crash

**Comment by gioman** [comment]
Closing for lack of feedback.
