### ISSUE TITLE
Error QGIS 3.14.15

### ISSUE THREAD

**Issue by barbozars** [qgis/QGIS#38883]
Hi, please install Qgis 3.14.15 and I have this problem.
![QGIS Error](https://user-images.githubusercontent.com/71569581/93689013-29b23180-fa90-11ea-860e-0464982e5d79.PNG)

Please help

**Comment by gioman** [comment]
@barbozars  please file again with a meaningful title and all the requested info, thanks!




**Describe the bug**


**How to Reproduce**



**QGIS and OS versions**



**Additional context**
