### ISSUE TITLE
QGIS Unexpectedly Ended when activating 3D view layer

### ISSUE THREAD

**Issue by MichealYani** [qgis/QGIS#38889]
**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by gioman** [comment]
@MichealYani please file again and actually fill all the requested info. Thanls!

**Comment by MichealYani** [comment]
Hi,

I am creating collines cluster using QGIS but my QGIS fails to add the 3D view map layer it crashes and until I had to restart QGIS again. 
Crash ID: 30fea667380023f531d67304025c50a70d189058


Stack Trace


DrvSetContext :
MakeAnyCurrent :
wglMakeCurrent :
QOpenGLContext::makeCurrent :
Qt3DRender::Render::MaterialParameterGathererJob::materialToPassAndParameter :
Qt3DRender::Render::QRenderPluginFactoryIf::create :
Qt3DRender::Render::Renderer::doRender :
Qt3DRender::Render::Renderer::render :
Qt3DRender::Render::AbstractRenderer::~AbstractRenderer :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.14.16-Pi
QGIS code revision: df27394552
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

Tha

**Comment by gioman** [comment]
> I am creating collines cluster using QGIS but my QGIS fails to add the 3D view map layer it crashes and until I had to restart QGIS again.

@MichealYani does it happens with a specific elevation dataset or any? have you tried with a new QGIS profile?

**Comment by PeterPetrik** [comment]
could be related to https://github.com/qgis/QGIS/pull/39287, can you please provide minimal example that can be used to reproduce the issue?

**Comment by gioman** [comment]
Closing for lack of feedback.
