### ISSUE TITLE
Can no longer switch from pan/zoom to previously used tool with right mouse button

### ISSUE THREAD

**Issue by uclaros** [qgis/QGIS#38895]
**Describe the bug**
With the removal of the *Coordinate Capture* core plugin ( #36693 ) in QGIS 3.14, one can no longer use right click in order to switch back from pan/zoom tool to the previous tool. Instead, the *Copy coordinate* context menu appears, although the pan and zoom cursors do not visibly point to a specific coordinate.
Many people only use the mouse wheel / middle button pan to roam the map, but IMHO the most efficient way is most of the times to use a shortcut for the zoom tool (I use Z), right-click to switch back to previous tool and zoom last with a shortcut (I use mouse back button).
A very common scenario is while digitizing, to need to zoom-in very close for just a specific point. Zooming with the wheel might need more map redraws than needed, while *Z, drag small zoom window, repeat if necessary, **right click**, click while zoomed, then zoom last* is super fast.

**How to Reproduce**
1. Start digitizing (new feature/split/node tool etc)
2. Select the pan or zoom tool
3. Right click on the canvas, instead of switching back to digitizing, the *Copy coordinate* context menu appears.

**QGIS and OS versions**
3.14

**Additional context**
The issue is also apparent on the georeferencer, where copying coordinates doesn't make much sense, unless the raster is already georeferenced.

Gently pinging @nyalldawson for his opinion!

**Comment by nyalldawson** [comment]
Would adding a generic keyboard shortcut for "previous map tool" solve this?

**Comment by uclaros** [comment]
It wouldn't be of great aid, since it would occupy one more shortcut that users would need to memorize. And if I am to remember another shortcut, I may as well just remember my previous tool's shortcut! The big plus with right clicking is that it's simple and intuitive: *I'm done zooming, right click*. Just like *I'm done digitizing, right click*.

Two possible solutions in case the context menu is definitely here to stay are:
1. Implement the following logic to the zoom tool: 
- Press Z: Zoom tool is activated
- If one starts dragging while Z is still pressed then create a rectangle to zoom to
- Release Z to switch back to previous tool
- If Z was released before mouse was clicked, then just switch to the zoom tool as it is now.
This partly simulates how Z was working on arcmap, I don't know if it still does.
2. Use shift + middle mouse button to zoom to dragged window without changing tool, just like middle mouse pan works, but with zoom!
3. Add a *Switch back to previous tool* entry to the context menu, right next to the cursor.

These are not mutually exclusive of course.

**Comment by uclaros** [comment]
Ok, so I found out #3149 that I was not aware of! It's like (2) from my previous post, but not for all tools. Also, intuitively, the identify tool should add features to the identified list with shift and remove with the ctrl.
If we migrate #3149 functionality to *shift+middle button* then it will work the same for all tools, and shift-ctrl+identify to add-remove identified features can then be implemented.

**Comment by nyalldawson** [comment]
> Add a Switch back to previous tool entry to the context menu, right next to the cursor.

I'd go with this then, but make it explicit about the tool e.g. "Switch Back to Add New Features Tool"

> If we migrate #3149 functionality to shift+middle button then it will work the same for all tools, and shift-ctrl+identify to add-remove identified features can then be implemented.

-1 to that -- we originally used shift + left mouse to emulate the behavior of web mapping clients, and it's now a long established user interaction in QGIS.

There's a flag available for map tools QgsMapTool::AllowZoomRect which allows individual tools to switch off this behavior, and that's used by the select tools to enable shift + select to add to the selection. Potentially this could be done for the identify tool too.

**Comment by uclaros** [comment]
>  we originally used shift + left mouse to emulate the behavior of web mapping clients, and it's now a long established user interaction in QGIS.

...that only works on some tools. What is missing is a fast way to use drag-to-zoom regardless of the current tool. How about just adding shift-middle mouse to always drag-zoom? I think it will be very handy since it will work with all tools and will not interfere with other functionalities and I will no longer need the previous tool shortcut :)

**Comment by nyalldawson** [comment]
What about copying the shortcut used in layout designer? (Ctrl + Space + click to zoom into point, Ctrl + Alt + Space + left click to zoom out at point, and Ctrl + Space+ click  and drag to zoom into a region)

**Comment by uclaros** [comment]
It makes good sense to share shortcuts with the designer, but the drawback I see is that it requires one more button to press and if space is pressed slightly before ctrl then the *pan without mouseclick* kicks in instead. Also, ctrl+click might interfere with a tool's keypress handling logic - vertex tool for example.
Since ctrl+space semantically means ctrl+pan, I'd go with implementing ctrl+middle mouse to drag-zoom.

**Comment by uclaros** [comment]
Revisiting my issues with a Feedback label because of the new stale policy:
The fast drag-zoom is still sorely missed! Any hint on where the middle mouse pan is handled for the map canvas? A quick `grep -inr middlebutton` only shows handling `Qt::MiddleButton` in layout and 3d...
