### ISSUE TITLE
Data Source Manager | WMS/WMTS Window not resizable

### ISSUE THREAD

**Issue by gitvox** [qgis/QGIS#38903]
In Data Source Manager, the Window opened by the WMS/WMTS button is not resizable in the vertical direction.  Almost impossible to use with a 15" screen.  Horizontal direction is resizable.  The other window options on the DSM toolbar (WFS, PostGIS etc.) are resizable in both vertical and horizontal directions.
Just add the toolbar and try to resize the various options - WMS/WMTS does not work in the vertical direction.
QGIS 3.14.16, Ubuntu Desktop 20.04.1 LTS, X11

**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

![image](https://user-images.githubusercontent.com/71618561/93729495-8fc6b380-fb79-11ea-8c85-132deb66d88f.png)

**Additional context**

**Comment by elpaso** [comment]
I'm on Ubuntu and I cannot reproduce (or I don't understand what you mean, can you attach a video showing the issue?):
![qgis-wms-window-resize](https://user-images.githubusercontent.com/142164/93869124-b3017800-fccb-11ea-91da-8390102f69ba.gif)

**Comment by gitvox** [comment]
Yes, I have attached it here.  I start with the PostGIS button, and you can
see that the Data
Source Manager window is resizable as expected.  When I switch the focus to
the WMS button you can see the window is only resizable in the horizontal
direction.  It is not possible to use the vertical resize cursor, or the
"corner drag" resize cursor to change the vertical dimension.  The same
behavior occurs with the VIrtual Layer button.
Also, as previously noted by another user, when switching the focus from,
for example the PostGIS button to the WMS button, the window size changes.
But when switching focus from the PostGIS to another properly functioning
button, the window size is preserved.
Thank you for inquiring about this issue.
IJR

**Comment by Pedro-Murteira** [comment]
@gitvox I can no longer replicate this issue on QGIS 3.22.3. Are you still experiencing this behaviour?

**Comment by gitvox** [comment]
I cannot remember what version I was on when I reported the issue.  But I
am now on 3.16.9 (Windows 10 21H2) and am having no problems resizing
WMS/WMTS or any other window so far.
Thanks for your inquiry, and your hard work on a great GIS.
Ian
