### ISSUE TITLE
Processing crashes on startup (All plugins disabled, including GRASS)

### ISSUE THREAD

**Issue by techdude1996** [qgis/QGIS#38914]
**Describe the bug**
Processing plugin crashes QGIS on startup with additional processing plugins (i.e. SAGA plugin by Alexander Bruy)
Similar to #38772, but disabling Grass does not change anything, not sure if it's the same underlying issue.

It does not crash with a new profile, but still shows a warning (see **Additional Context** below)

When disabling all plugins, closing QGIS, opening QGIS, and turning on Processing, this message is presented:

    An error has occurred while executing Python code: 

    RecursionError: maximum recursion depth exceeded while calling a Python object 
    Traceback (most recent call last):
      File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 777, in _import
        new_path = os.environ['PATH']
      File "C:\OSGEO4~1\apps\Python37\lib\os.py", line 675, in __getitem__
        value = self._data[self.encodekey(key)]
      File "C:\OSGEO4~1\apps\Python37\lib\os.py", line 744, in encodekey
        return encode(key).upper()
      File "C:\OSGEO4~1\apps\Python37\lib\os.py", line 738, in check_str
        if not isinstance(value, str):
    RecursionError: maximum recursion depth exceeded while calling a Python object

    Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
    QGIS version: 3.14.16-Pi Pi, a235a149f0 

    Python Path:
    C:/OSGEO4~1/apps/qgis/./python
    C:/Users/me/AppData/Roaming/QGIS/QGIS3\profiles\default/python
    C:/Users/me/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
    C:/OSGEO4~1/apps/qgis/./python/plugins
    C:\OSGEO4~1\apps\Python37
    C:\OSGEO4~1\apps\Python37\Scripts
    C:\OSGeo4W64\bin\python37.zip
    C:\OSGEO4~1\apps\Python37\DLLs
    C:\OSGEO4~1\apps\Python37\lib
    C:\OSGeo4W64\bin
    C:\OSGEO4~1\apps\Python37\lib\site-packages
    C:\OSGEO4~1\apps\Python37\lib\site-packages\win32
    C:\OSGEO4~1\apps\Python37\lib\site-packages\win32\lib
    C:\OSGEO4~1\apps\Python37\lib\site-packages\Pythonwin
    C:/Users/me/AppData/Roaming/QGIS/QGIS3\profiles\default/python

**How to Reproduce**
1. Start QGIS
1. *Crashes on startup
1. Restart QGIS
1. *Processing Plugin crashed QGIS and has been disabled
1. Disable all plugins
1. Restart QGIS
1. Enable Processing (doing this before restarting QGIS causes a crash)
1. *Error message above shows, but does not crash
1. Per #38772, disable Grass plugin provider
1. Close QGIS
1. Restart QGIS
1. Enable extra processing plugins (does not crash)
1. Do stuff
1. Close QGIS
1. Repeat cycle

**QGIS and OS versions**

QGIS version | 3.14.16-Pi | QGIS code revision | a235a149f0
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | processing

**Additional context**

A clean new user profile gives the same message as above, but as a warning instead in the Python Error Log:

    2020-09-21T09:07:08     WARNING    Traceback (most recent call last):
                  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 777, in _import
                  new_path = os.environ['PATH']
                  File "C:\OSGEO4~1\apps\Python37\lib\os.py", line 675, in __getitem__
                  value = self._data[self.encodekey(key)]
                  File "C:\OSGEO4~1\apps\Python37\lib\os.py", line 744, in encodekey
                  return encode(key).upper()
                 RecursionError: maximum recursion depth exceeded

**Comment by jef-n** [comment]
Update to df27394552 (as in 3.14.16-2 in OSGeo4W / standalone installer).
