### ISSUE TITLE
Projections not reading in MacOS Nightly Build 

### ISSUE THREAD

**Issue by mapninja** [qgis/QGIS#38919]
Nightly build isn't reading CRS from properly projected layers:

Here is one that actually reads, but not properly. THis is a file straight from Natural Earth, unaltered:
![image](https://user-images.githubusercontent.com/1517244/93789340-92abbd80-fbe6-11ea-9e41-0521470ea767.png)

Here, an elevation datasets with WGS84 is not reading at all:

![image](https://user-images.githubusercontent.com/1517244/93789501-c7b81000-fbe6-11ea-8174-21b7aeb3f7ae.png)
Here is a cut& Paste of the Metadata from the Raster:

```
Name | BayTopo
-- | --
Path | /Users/maples/Dropbox/Fundamentals/data/BayTopo.tif
CRS |  
Extent | -122.0500000579999949,35.7833332080000019 : -120.2166667259999997,36.9166665400000014
Unit |  
Width | 55
Height | 34
Data type | UInt16 - Sixteen bit unsigned integer
GDAL Driver Description | GTiff
GDAL Driver Metadata | GeoTIFF
Dataset Description | /Users/maples/Dropbox/Fundamentals/data/BayTopo.tif
Compression |  
Band 1 | STATISTICS_MAXIMUM=12000STATISTICS_MEAN=11041.975473802STATISTICS_MINIMUM=9642STATISTICS_STDDEV=336.94550876308STATISTICS_VALID_PERCENT=47.97
More information | AREA_OR_POINT=Area
Dimensions | X: 55 Y: 34 Bands: 1
Origin | -122.05,36.9167
Pixel Size | 0.03333333330909082209,-0.03333333329411763274

```

Version info:

`

QGIS version | 3.15.0-Master | QGIS code revision | 61a1801e3d
-- | -- | -- | --
Compiled against Qt | 5.14.2 | Running against Qt | 5.14.2
Compiled against GDAL/OGR | 3.1.2 | Running against GDAL/OGR | 3.1.2
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.4
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | macOS 10.15
Active python plugins | processing; db_manager; MetaSearch

`

**Comment by PeterPetrik** [comment]
bug is https://github.com/qgis/QGIS/blob/1c1febc0d664a865cf368d5c7f58b669e5dabad8/src/app/main.cpp#L1227 with combination with https://doc.qt.io/qt-5/qstring.html#append 

it appends `/proj` twice to the path, causing pointing to wrong proj dir 
```
import os
os.getenv('PROJ_LIB')
'/opt/QGIS/qgis-dev/bundle/QGIS.app/Contents/Resources/proj/proj'
```

**Comment by dkav** [comment]
Re request in #38595. Output from os.getenv('PROJ_LIB'):
> '/Applications/QGIS.app/Contents/Resources/proj'
project.db is present in the folder.

I noticed when I added a new layer the following error was reported in Terminal:
> ERROR 1: PROJ: proj_identify: Cannot find proj.db

**Comment by PeterPetrik** [comment]
can you retest with https://qgis.org/downloads/macos/nightly2/qgis_nightly2_master_20200923_062253.dmg ?

**Comment by dkav** [comment]
Fixed in qgis_nightly2_master_20200923_133843. Thanks!
