### ISSUE TITLE
Crash upon expression selection

### ISSUE THREAD

**Issue by agmt5989** [qgis/QGIS#38912]
## User Feedback

Working on a polygon shapefile in an attempt to select features using the "Select by Expression" tool. The window suddently stopped responding, and I got this crash report.

## Report Details

**Crash ID**: [ba71804da88fdeaf8594842bef72caf40b246d42](https://github.com/qgis/QGIS/search?q=ba71804da88fdeaf8594842bef72caf40b246d42&type=Issues)

**Stack Trace**
<pre>
operator< :
QgsProcessingModelAlgorithm::designerParameterValues :
QgsLimitedRandomColorRamp::valMin :
QgsObjectCustomProperties::value :
QgsMapLayer::customProperty :
QgsExpressionContextUtils::layerScope :
QgsExpressionContextUtils::globalProjectLayerScopes :
QgsVectorLayer::selectByExpression :
QgsExpressionSelectionDialog::mActionSelect_triggered :
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.14.15-Pi
QGIS code revision: d5114d2cfa
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

**Comment by gioman** [comment]
@agmt5989 please try with a new QGIS profile, no 3rd party plugins installed.

**Comment by roya0045** [comment]
Its strange that the crash occurred when creating the layer scope. The layer/project might need to be shared to debug if its repeatable.

**Comment by agmt5989** [comment]
There were no plugins loaded. In fact, after restarting the application, I
was able to achieve my objective.
