### ISSUE TITLE
GIS Georeferencing issues

### ISSUE THREAD

**Issue by zyalela** [qgis/QGIS#38910]
Hi, I am working on a project that requires me to digitize a geological raster image that is in TIFF format, I georeferenced it but unfortunately when I ran the process the image is loading as a black rectangle, any help?

**Comment by gioman** [comment]
@zyalela is this a support request or a big report? If is the former then this is not the right place, use the users mailing list. If is the latter you must add all the necessary info, mainly:

Steps to replicate
Data/project to replicate

**Comment by gioman** [comment]
Closing for lack of feedback.
