### ISSUE TITLE
Wrong GRASS processing description files

### ISSUE THREAD

**Issue by zhanggaolei001** [qgis/QGIS#38938]
in line 6:
"QgsProcessingParameterEnum|sort|Sort output by distance|asc;desc|0"
I think it should be something like this:
"QgsProcessingParameterEnum|sort|Sort output by distance|asc;desc|False|0"
or:
"QgsProcessingParameterEnum|sort|Sort output by distance|asc;desc|True|0"

**Comment by zhanggaolei001** [comment]
Same problem in the file"r.report.txt",line 14

**Comment by zhanggaolei001** [comment]
And maybe this:"v.net.visibility.txt",line 6

**Comment by gioman** [comment]
@zhanggaolei001 Could you please post a pull request with the changes?

**Comment by zhanggaolei001** [comment]
> @zhanggaolei001 Could you please post a pull request with the changes?

All right~
