### ISSUE TITLE
Bug during the opening of a project made on QGIS 3.8

### ISSUE THREAD

**Issue by Iragon5935** [qgis/QGIS#38941]
Crash ID: 9dff1e2b30e05a56e4d406c77eb6d64187b156b0

Stack Trace

QXmlStreamStringRef::~QXmlStreamStringRef :
QgsExpressionContext::clearCachedValues :
QHashData::free_helper :
QgsExpressionContextScope::~QgsExpressionContextScope :
QgsError::summary :
QgsExpressionContext::~QgsExpressionContext :
QgsMapRendererJob::needTemporaryImage :
QgsMapRendererJob::cleanupJobs :
QgsMapRendererParallelJob::renderingFinished :
QMetaObject::activate :
QFutureWatcherBase::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.8.0-Zanzibar
QGIS code revision: 11aff65f10
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment]
>  QGIS Version: 3.8.0-Zanzibar

@Iragon5935 way too old. Please use the latest 3.10 or 3.14.

**Comment by Iragon5935** [comment]
@gioman : I begin to use the 3.10 version of QGIS but I don't understand why some of my project still work with 3.8 but others not even if they both were created on QGIS 3.8.

Thanks for the advise anyway.

**Comment by gioman** [comment]
>  but I don't understand why some of my project still work with 3.8 but others not even if they both were created on QGIS 3.8.

@Iragon5935 I don't understand what this means: do your projects open if you use the latest 3.10 or 3.14 (regardless the version they were created with)?

**Comment by Iragon5935** [comment]
yes the 3.10 works perfectly
