### ISSUE TITLE
QGIS 3.10.10 crashes MDB datasources with SQL filter

### ISSUE THREAD

**Issue by goened** [qgis/QGIS#38943]
We are working with 3.10.7 in the office and saved all projects with this version. I updated the QGIS-version on my computer to 3.10.10, deinstalled the old version, but when I open certain projects they crash without error report.

I looked for other bug reports on GitHub and found similar notices. So I did following steps to find/solve the problem:
- I renamed my old (default) profile so that QGIS made a new default-profile
- When I opened QGIS (blank) I cleared the cache and checked/unchecked the box to allow network-proxies
- I cleared the connection cache for authentification (Authentifizierungsverbindungscache)
- I have no plugins installed.

I found out that I could open certain simple projects, but complexer ones didn´t work.

So I installed QGIS 3.10.10 on a "fresh" computer, where there was no (older) QGIS installed before. I had the same problem with the complexer QGIS-project-file: crash without error report.
In the project I have wms-services, connected database (Access), atlas in the layout.

I tried the same with version 3.14.16 - same.

It must have to do something with the projects, but unfortunately I don´t get the error report. Can you suggest any way to record bugs?

**Comment by elpaso** [comment]
You can try to identify which layers are causing the crash. Make a copy of the "broken" project and try to remove the layers one by one until the project loads without crashes. 
If the crash is random it could be very difficult to reproduce the issue.

In order to get help from the developers you must provide the "broken" project and all necessary data that can be used to reproduce the issue on a developer's machine so that we can run QGIS through a debugger and see what's going on internally.

If you don't want or cannot share the project I'd recommend you to get commercial support and make the developer sign an NDA so that you can share the project.

**Comment by goened** [comment]
Hi Alessandro,
thanks for your quick reply. I will check the projects first and then come back to you later.

Mit freundlichen Grüßen
Neele Dietrich
_______________________________

Neele Dietrich
GERIES INGENIEURE GMBH
Kirchberg 12
D-37130 Gleichen-Reinhausen
Tel.: (05592) 92 76-37
Fax: (05592) 92 76-11
eMail: dietrich@geries.de<mailto:dietrich@geries.de>

Internetseite und Soziale Medien:
[cid:image010.jpg@01D690D8.52935010]<http://geries.de/>[facebookx]<http://www.facebook.com/geries.de>[twitterx]<https://twitter.com/geries_ing>[cid:image011.jpg@01D690D8.52935010]<https://www.instagram.com/geriesingenieure/>[cid:image012.jpg@01D690D8.52935010]<https://www.youtube.com/channel/UCA6CiOCjCRradka1-6VAlPA>

Geries Ingenieure GmbH, Kirchberg 12, 37130 Gleichen
Registriert beim Amtsgericht Göttingen HRB 2876, Geschäftsführer Dr. Hartmut Geries
_______________________________

Von: Alessandro Pasotti <notifications@github.com>
Gesendet: Dienstag, 22. September 2020 11:25
An: qgis/QGIS <QGIS@noreply.github.com>
Cc: Neele Dietrich <dietrich@geries.de>; Author <author@noreply.github.com>
Betreff: Re: [qgis/QGIS] QGIS 3.10.10 crashes without error report (#38943)


You can try to identify which layers are causing the crash. Make a copy of the "broken" project and try to remove the layers one by one until the project loads without crashes.
If the crash is random it could be very difficult to reproduce the issue.

In order to get help from the developers you must provide the "broken" project and all necessary data that can be used to reproduce the issue on a developer's machine so that we can run QGIS through a debugger and see what's going on internally.

If you don't want or cannot share the project I'd recommend you to get commercial support and make the developer sign an NDA so that you can share the project.

**Comment by roya0045** [comment]
Do you have any scripts/macros or other similar customizations enable on those projects?

**Comment by goened** [comment]
not as far as I know.

I integrated wms by quick map services, but in 3.10.7 I deleted all wms and tried to open in 3.10.10 but still crashed. 
I am going to check the other layers (as dxf, mdb,...)

**Comment by goened** [comment]
I found the problem: it is because of integrated mdb-files. In our projects we have tables of mdb-databases (added to the projects as a vektor-layer as a "file" NOT as a ODBC-database connection) and these tables we connect to shape-files. When I delete the mdb-files I can open the projects! I tried it with two different projects with different DB.

When I integrate the DB in Version 3.10.7 as a vektorlayer as a ODBC-database connection and try then to open it with 3.10.10 (in another computer) it opens only when I don´t have the DB added in the microsoft "ODBC data source" window. When I add it the same way as on the other computer QGIS crashes as well.

**Comment by gioman** [comment]
> integrated mdb-files

@goened esri personal geodatabases? geomedia? Can you attach a sample?

**Comment by goened** [comment]
I mean Microsoft Access Database. But apparantly it works with simple mdb-database (I created a new one) but not with complexer ones. I have to create anonymous test data that I can attach.

**Comment by goened** [comment]
Apparantly Microsoft Access SQL-expressions cause the problems within the database when openening QGIS 3.10.10 or 3.14.16.

If there are expressions like "B_Nachname: Wenn(IstNull([T_Auswahl].[Auswahlfeld]);"N.n.";Wenn(InStr([T_Auswahl].[Auswahlfeld];", ")=0;[T_Auswahl].[Auswahlfeld];Links([T_Auswahl].[Auswahlfeld];InStr([T_Auswahl].[Auswahlfeld];", ")-1)))" in the head of the query QGIS crashes.
I will attach tables for you as an simple example.

[TestDB.zip](https://github.com/qgis/QGIS/files/5281277/TestDB.zip)
 
Until QGIS 3.10.7 we used the same expression and QGIS worked fine!

**Comment by Pedro-Murteira** [comment]
@goened Hello, is this issue still present on recent versions?

**Comment by goened** [comment]
Infact the crash without any notification doesn´t occur anymore. But since version 3.16 I can´t open Access-DB in QGIS anymore. When they are already in the existing project, they cannot be used anymore/they have no connection.
