### ISSUE TITLE
Automatic embedding or importing relations when embedding layers

### ISSUE THREAD

**Issue by kingemir** [qgis/QGIS#38955]
**Feature description.**

When embedding several layers from another project, it would be very useful if all relations which concern these layers would also be automatically embedded (or alternatively imported, if embedding should be impossible).

**Additional context**

As described in #38422, relations are in QGIS not yet automatically embedded or imported when embedding layers from other projects. However, such a feature would be very useful especially in cases where projects contain a big amout of relations, such as the ones created by the extension QGIS Model Baker which generates projects automatically, following the requirements which are described in Interlis data models.

**Comment by troopa81** [comment]
Like I said in #38422, I think it could be nice to have a checkbox "Import embedded layers relation" in the embedded layers feature.

> automatically embedded (or alternatively imported, if embedding should be impossible).

I think it would indeed be better to embed them instead of import/copy them.
