### ISSUE TITLE
Image Export Error when installing QGIS with Flatpack

### ISSUE THREAD

**Issue by craigr78** [qgis/QGIS#38950]
When trying to export to image from a QGIS Layout is get this Image Export Error message:

Cannot write to /home/xxx/Desktop/test.jpg. This file may be open in another application.

This is the same issue raised by greenmansinger in "error message in export to image #35202", but the issue was closed due to a lack of feedback.
The file destination, file (image) type, and file name do not mitigate the issue.
I was not able to attach an example project, but if you create a layout and try to export to image, you should encounter the same problem.

QGIS version | 3.14.16-Pi | QGIS code revision | a235a149
-- | -- | -- | --
Compiled against Qt | 5.14.2 | Running against Qt | 5.14.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 12.2 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | KDE Flatpak runtime
Active python plugins | processing; MetaSearch; db_manager

**Comment by gioman** [comment]
> KDE Flatpak runtime

@craigr78 does it happens if you install QGIS from the QGIS.org repo?

**Comment by craigr78** [comment]
I cannot figure out how to install QGIS 3.14 from the repo. I added ubuntugis unstable, but am only able to install 3.10.9. FYI the issue does not exist when installing 3.10.9 from the repo.

**Comment by gioman** [comment]
> I cannot figure out how to install QGIS 3.14 from the repo. I added ubuntugis unstable, but am only able to install 3.10.9. FYI the issue does not exist when installing 3.10.9 from the repo.

@craigr78 if you use also ubuntugis then you have to use the proper qgis.org repo that builds upon ubuntugis dependencies. If you don't use uit then you get a mess. https://qgis.org/en/site/forusers/alldownloads.html#repositories

**Comment by craigr78** [comment]
Thanks for the guidance @gioman...to answer your original question, I do not have an issue exporting to image when installing from the QGIS.org repo...so I guess the issue is with the flatpak.

**Comment by gioman** [comment]
> .so I guess the issue is with the flatpak

@craigr78 ok, I'm not sure if we officially support flatpack.

**Comment by nyalldawson** [comment]
We don't --- bugs need to be filed with the flatpak maintainer
