### ISSUE TITLE
Error loading QGIS  " could not set environment variable "

### ISSUE THREAD

**Issue by 375000384** [qgis/QGIS#38974]
after the qgis was installed in my laptop, i start qgis, then the system tips:
 " oops, looks like an error loading qgis  
details:
could not set environment variable:
 "
how to solve the problem.

**Comment by gioman** [comment]
@375000384 please file again following the guidelines:




**Describe the bug**


**How to Reproduce**



**QGIS and OS versions**



**Additional context**

**Comment by 375000384** [comment]
os versions:  windows 10 pro  x64
qgis  versions: QGIS-OSGeo4W-3.10.10-2-Setup-x86_64.exe
laptop: surface
i used the qgis two years On many computers，and this is the first time that this problem has arisen.

**Comment by gioman** [comment]
> and this is the first time that this problem has arisen.

@375000384 also looks alike a local computer issue, does not seems really a general one.

**Comment by gioman** [comment]
@375000384 try raise your problem in the users mailing lists, maybe someone had your same problem.

**Comment by 375000384** [comment]
> @375000384 try raise your problem in the users mailing lists, maybe someone had your same problem.
yes ,i think so .
think you.
