### ISSUE TITLE
Add Vector Layer hang QGIS on complex, multi-layer project

### ISSUE THREAD

**Issue by jjk0giap** [qgis/QGIS#38978]
In QGIS 3.10, very big project, ~200 vector layers with many rule-based styles, addidng new vector layer - freeze QGIS, with no crash. 
With small projects there is no problem, same project on QGIS 2.18 - layers add with no problem, so this is regression. 

**How to Reproduce**
1. Open any very big project
2. Go to Add Vector Layer dialog
3. Select multiple files, (I've tried on SHP)
4. Click Add 
5. Layers are added to layer tree, but QGIS freeze on canvas refresh. Add Layer  Dialog cannot be closed, or even moved.

**QGIS and OS versions**
Affected QGIS versions - 3.10, 3.12, 3.14, 3.15 nightly
Windows 10 64bit

**Context**
I've tried with --noplugins option and with new user profile.

**Comment by gioman** [comment]
@jjk0giap can you please try with a new QGIS profile to check if it makes any difference? thanks.

**Comment by jjk0giap** [comment]
Prease read **Context**

**Comment by gioman** [comment]
> Prease read **Context**

@jjk0giap that was added later, I answered based on the notification I received:

![Screenshot_20200923_142525](https://user-images.githubusercontent.com/1951107/94018592-b0288500-fda8-11ea-8b4c-a6f528c6366f.png)

**Comment by jjk0giap** [comment]
New clue: drag&drop with test 12 SHP files:
1. Empty project is very fast, usuable almost immediately
2. Big project is very slow, takes 1-2 minute to refresh canvas after layers are added, later works normally.
Same for drag&drop Spatialite database.

**Comment by matosang** [comment]
I have this exact same issue.

**Comment by matosang** [comment]
One thing I've noticed is that after a new layer is added to layer tree, and when QGIS freeze on canvas refresh, if I leave the application to grind away, it can eventually become functional, but it can take 10-20 or more minutes. Not sure why it takes so long...

**Comment by petercornelissen** [comment]
I have a problem that is probably related to this. I've tried new profiles, rebuilding the project etc. and it all works fine for a while then eventually it freezes when trying to add a new lay, pan a raster, move a layer etc. for 5 or 10 minutes. If you save the project, exit and restart it all works fine again until you add something else. I'm now using GeoPackages, but I had the same problem with ShapeFiles and why I went to GeoPackages hoping that would solve the problem, but it didn't make any difference. 3.12 and 3.14 both exhibit the probelm.

**Comment by elpaso** [comment]
Unless someone can provide a test project with data that developers can use to reliably reproduce the issue on theirs machine I don't see how we can even try to fix this issue. Any volunteer?

**Comment by nirvn** [comment]
This _sounds like_ it could have been addressed by @m-kuhn 's recent work speeding up large layer trees. 

Otherwise, as @elpaso said just now, it's unlikely it'll be fixed unless someone provides a test project. For people who are reporting this: try to attach a "slow" project's .qgs / .qgz file here without the datasets, if the problem has to do with a large layer tree, it can be diagnosed without the datasets themselves.

**Comment by jjk0giap** [comment]
OK, on this project problem presists without any dataset:
[test2.zip](https://github.com/qgis/QGIS/files/5291629/test2.zip)

**Comment by nirvn** [comment]
@jjk0giap , testing on my linux machine, I can't see any noticeable freeze. What 3.15 did you try? (i.e., commit revision string in the about dialog)

**Comment by nirvn** [comment]
@jjk0giap , the commit @m-kuhn authored which I think might fix the issue reported here is https://github.com/qgis/QGIS/commit/673d6727ee0b99ea2ff0bd8df498134706341a00 , it was committed 8 days ago. If you haven't tried 3.15 in the last week or so, give it a try again (via osgeo4w installer).

**Comment by nirvn** [comment]
There is however a 5-10 sec freeze when the canvas scale is changed (i.e. when zooming in/out).

Hotspot graph of 5-10 sec freeze:
![image](https://user-images.githubusercontent.com/1728657/94424910-3122ba80-01b5-11eb-9b92-68b50f976478.png)

**Comment by nirvn** [comment]
For the freeze to occur, the layer tree items must all be expanded. The reason for the freeze is, as hotspot hints at, the cost of re-drawing hundreds of layer tree item names.

**Comment by jjk0giap** [comment]
previous test was on 3.15.0-60, also today 3.15.0-64 seems affected:
![image](https://user-images.githubusercontent.com/17615745/94434850-ab921100-019a-11eb-8685-b7d7c27785c2.png)

**Comment by nirvn** [comment]
1/ disable your plugins
2/ by "seems affected", what do you mean? With plugin disabled, is it still freezing when you add a layer or only when you pan/zoom?

**Comment by jjk0giap** [comment]
1. Plugins disabled
2. Layer tree collapsed, freezing 1-2 minutes when I click "Add" button, First resresh is laggy, Pan works normally. But every zoom in/out take more time than normally, after zoom - pan still OK.

**Comment by petercornelissen** [comment]
The problem for me is that it is all fine for a while with a new profile and starts after a few layers added. The problem goes away on a restart until again another layer is added. Once the problem starts it continues thereafter unless I create another new profile. I've tried disabling all plug-ins. It seems that it is using memory and then not releasing it, so if I could something like a refresh? 

I only have a relatively few layers, but they are repeated with filters as most of the lines, polygons and points are used multiple tines.

I'm currently using 3.14.16, but the problem has been there at least since 3.10

[NWW2016 Onwards - Normalized (GeoPackage).zip](https://github.com/qgis/QGIS/files/5293103/NWW2016.Onwards.-.Normalized.GeoPackage.zip)

**Comment by matosang** [comment]
My project that has this same issue also repeats the use of many layers (lines) with different styles applied to the layers. Not sure if that is relevant or not.

**Comment by m-kuhn** [comment]
I tested the project from https://github.com/qgis/QGIS/issues/38978#issuecomment-699927579 . I could reproduce the freeze on add layer problem with a nightly build from 2 weeks ago but not any more with a new build. So it seems it's fixed for 3.16. We can discuss a backport to 3.10.

**Comment by jjk0giap** [comment]
@m-kuhn how many new files You added at once? More layers You add at once makes qgis slower. I tested on yesterday nightly build (revision on screenshot ^^), problem is still there. If I save project and reopen it - no zoom issue.

**Comment by petercornelissen** [comment]
When the issue is there, I only need to add a single layer and it freezes up.

**Comment by gioman** [comment]
> So it seems it's fixed for 3.16

@m-kuhn closing?

**Comment by m-kuhn** [comment]
I think so.
If someone still has the issue with an up to date nightly build, let's open a new, clean issue where we can target that one in a focused manner.

**Comment by jjk0giap** [comment]
I can confirm refresh problem after adding is resolved, but "AddLayer" window is still unresponsible for some time after click "Add" button. Compared to 2.18 where add is almost insant. Drag&drop vector files - OK

**Comment by m-kuhn** [comment]
@jjk0giap thanks for the feedback. Can you open a new issue with a description of this problem, steps to reproduce, sample project if applicable...

**Comment by jjk0giap** [comment]
This is main subject of this issue, could be re-open. Backport of current solutions to LTR is possible?
