### ISSUE TITLE
plugin install from zip file extracts unreliable pugin name

### ISSUE THREAD

**Issue by uwer** [qgis/QGIS#38971]
**Describe the bug**

under pyqgis package directory
 pyplugin_installer/installer.py
553         with zipfile.ZipFile(filePath, 'r') as zf:
554             pluginName = os.path.split(zf.namelist()[0])[0]

os.path.split return head and tail, if subdirectories are present only the tailing slash is removed (as coming from the zf.namelist())
This will lead to a failure loading the plugin the first time (subsequent loading will be probably be fine).

**How to Reproduce**

create python plugin with sub-packages and install from zip file
and observe the installation succeed but loading fail

**QGIS and OS versions**
reproduced on Win10 and OSX
3.10.x and 3.14.x

**Additional context**

Solution; don't use os.path.split but string split with '/'  as per  ZIP spec (4.4.17.1) and extract first element.

**Comment by uwer** [comment]
line no under 3.14.x are 565/566

**Comment by roya0045** [comment]
I have installed plenty of plugins this way with 3.10 and 3.14 and it never failed. Could you detail more your case or provide your plugin zip for replicating?

**Comment by uwer** [comment]
Hi Alex, thanks for taking the time to respond. I too have installed many plugins this way and i know it works perfectly. The error outlined in my original report concerns installation only and the error causing the subsequent importing of the incorrectly assembled package name to fail the loading of the plugin at installation time - on restart everything is fine.  
I would probably go one further and say that it depends on the order of entries in the zip file, if the first entry includes a subdirectory - and before submitting I tested it and indeed i can confirm that is what causes the issue.
My suggestion of a fix would address this scenario. U

**Comment by Gustry** [comment]
You must give us more info like zip name, the files tree inside the zip etc ...
Avoid dash in the folder name, use underscore.

**Comment by uwer** [comment]
Thanks Étienne, i am aware of that, I have attached  a zip file with packaging script producing a successful and a failing plugin. Noting again that the plugin will run but not at install time.
[simple_src.zip](https://github.com/qgis/QGIS/files/5399023/simple_src.zip)

**Comment by uwer** [comment]
I understand this is an edge case but has anybody taken the time to look at this ?

**Comment by Pedro-Murteira** [comment]
@uwer Hello, is this isse still valid in more recent releases?
