### ISSUE TITLE
Override @symbol_layer gives different results in preview or in layout

### ISSUE THREAD

**Issue by Inrap** [qgis/QGIS#38980]
**goal**
I categorized a layer using 3 fields, the default labels are identical to the values.
In the layout legend, I want the labels to show only 2 fields.

**Describe the bug**
Therefore, I replaced @symbol_label by, to start with, one field (**1** in picture below). If preview is correct (**2** in picture), the result is not (**3**) . (Of course, it doesn't work better with the second field.)
![image](https://user-images.githubusercontent.com/32261793/94020319-15817380-fdb3-11ea-90a8-e68e3265d291.png)

I also tried to override @symbol_label with a @symbol_label2 equal to "SYSTEM" (the first field I want for label) but this also failed  :
![image](https://user-images.githubusercontent.com/32261793/94021738-a573ed00-fdb4-11ea-9a5c-fcfc0c96f26f.png)

Is it a bug or what is the proper way to modifiy a label symbol ?

**versions and OS**
QGIS 3.14 Pi/W10

**Comment by roya0045** [comment]
You're trying to provide a field to an expression? I'm not even sure what you are trying to do. Features in each category can have multiple values for the given field for each category. If you want to set things properly you should do it in your categories first.

Fields are greatly useful when used to perform aggregates and to return a single string that contains information from the dependent layers. This is mostly why the fields are available. Using fields directly will cause a wonky behavior as expected. Don't forget that the preview is done for a single feature, and the legend items are not single features.

**Comment by roya0045** [comment]
You should just modify the text by double clicking on each legend item and changing the text. Though you'll need to remove the set expression as you don't have the @symbol_label variable displayed.

**Comment by roya0045** [comment]
@gioman  Do you think this warrant a feedback tag? Or it could be closed as it's just a misunderstanding of how the feature works.

**Comment by gioman** [comment]
Closing for lack of feedback.
