### ISSUE TITLE
r.rgb layers are not correctly generated

### ISSUE THREAD

**Issue by FelixTheAwesomeCat** [qgis/QGIS#38982]
I am trying to use r.rgb to split my raster into thee separate rasters (R,G,B bands). 
Each time I try r.rgb I get the red error massage: 

> The following layers were not correctly generated.
> • C:/Users/Felix/AppData/Local/Temp/processing_hQOjSy/a3a562fa8e1a423ca4c8698e923ca01a/red.tif
> • C:/Users/Felix/AppData/Local/Temp/processing_hQOjSy/c396aa3b10a84565a52ada1c53cb9751/green.tif
> • C:/Users/Felix/AppData/Local/Temp/processing_hQOjSy/eb24f00c75eb4813bfe7f10af7238d85/blue.tif
> You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.

Theres no difference whether I choose to save as temp file or not. I tried on two Computers with different RGB rasters, both Win 10. I think the problem is, that after importing the raster maps, it is not able to save them in the temp folder?

> Importing raster map <rast_5f6b63079109d2.red>...
> 0..3..6..9..12..15..18..21..24..27..30..33..36..39..42..45..48..51..54..57..60..63..66..69..72..75..78..81..84..87..90..93..96..99..100
> ERROR: raster map <rast_5f6b63079109d2red> could not be found.

Help appreciated!
This is the complete log:

> Win 10
> QGIS version: 3.14.16-Pi
> QGIS code revision: df27394552
> Qt version: 5.11.2
> GDAL version: 3.0.4
> GEOS version: 3.8.1-CAPI-1.13.3
> PROJ version: Rel. 6.3.2, May 1st, 2020
> Processing algorithm…
> Algorithm 'r.rgb' starting…
> Input parameters:
> { 'GRASS_RASTER_FORMAT_META' : '', 'GRASS_RASTER_FORMAT_OPT' : '', 'GRASS_REGION_CELLSIZE_PARAMETER' : 0, 'GRASS_REGION_PARAMETER' : None, 'blue' : 'TEMPORARY_OUTPUT', 'green' : 'TEMPORARY_OUTPUT', 'input' : 'C:/Users/Felix/Desktop/RGB Test.tif', 'red' : 'TEMPORARY_OUTPUT' }
> 
> g.proj -c proj4="+proj=utm +zone=32 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"
> r.in.gdal input="C:\Users\Felix\Desktop\RGB Test.tif" output="rast_5f6b63079109d2" --overwrite -o
> g.region n=5666567.6913 s=5666536.8635 e=510504.1778 w=510443.5507 res=0.012541808026475658
> g.region raster=rast_5f6b63079109d2red
> r.out.gdal -t -m input="rast_5f6b63079109d2red" output="C:/Users/Felix/AppData/Local/Temp/processing_hQOjSy/a3a562fa8e1a423ca4c8698e923ca01a/red.tif" format="GTiff" createopt="TFW=YES,COMPRESS=LZW" --overwrite
> g.region raster=rast_5f6b63079109d2green
> r.out.gdal -t -m input="rast_5f6b63079109d2green" output="C:/Users/Felix/AppData/Local/Temp/processing_hQOjSy/c396aa3b10a84565a52ada1c53cb9751/green.tif" format="GTiff" createopt="TFW=YES,COMPRESS=LZW" --overwrite
> g.region raster=rast_5f6b63079109d2blue
> r.out.gdal -t -m input="rast_5f6b63079109d2blue" output="C:/Users/Felix/AppData/Local/Temp/processing_hQOjSy/eb24f00c75eb4813bfe7f10af7238d85/blue.tif" format="GTiff" createopt="TFW=YES,COMPRESS=LZW" --overwrite
> Starting GRASS GIS...
> WARNUNG: Sperren gleichzeitiger Zugriffe auf ein Mapset ist unter Windows nicht möglich.
> Cleaning up temporary files...
> Executing <C:\Users\Felix\AppData\Local\Temp\processing_hQOjSy\grassdata\grass_batch_job.cmd> ...
> C:\Users\Felix\Documents>chcp 1252 1>NUL
> C:\Users\Felix\Documents>g.proj -c proj4="+proj=utm +zone=32 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"
> Die Standard Region wurde auf die neue Projektion aktualisiert. Wenn Sie aber mehrere Mapsets haben, sollten Sie `g.region -d` in jedem ausführen, um die Einstellungen von der Standardregion zu übernehmen.
> Projektionsinformationen aktualisiert
> C:\Users\Felix\Documents>r.in.gdal input="C:\Users\Felix\Desktop\RGB Test.tif" output="rast_5f6b63079109d2" --overwrite -o
> Übersteuere die Überprüfung der Projektion.
> Importing 4 raster bands...
> Importing raster map <rast_5f6b63079109d2.red>...
> 0..3..6..9..12..15..18..21..24..27..30..33..36..39..42..45..48..51..54..57..60..63..66..69..72..75..78..81..84..87..90..93..96..99..100
> Importing raster map <rast_5f6b63079109d2.green>...
> 0..3..6..9..12..15..18..21..24..27..30..33..36..39..42..45..48..51..54..57..60..63..66..69..72..75..78..81..84..87..90..93..96..99..100
> Importing raster map <rast_5f6b63079109d2.blue>...
> 0..3..6..9..12..15..18..21..24..27..30..33..36..39..42..45..48..51..54..57..60..63..66..69..72..75..78..81..84..87..90..93..96..99..100
> Importing raster map <rast_5f6b63079109d2.alpha>...
> 0..3..6..9..12..15..18..21..24..27..30..33..36..39..42..45..48..51..54..57..60..63..66..69..72..75..78..81..84..87..90..93..96..99..100
> C:\Users\Felix\Documents>g.region n=5666567.6913 s=5666536.8635 e=510504.1778 w=510443.5507 res=0.012541808026475658
> C:\Users\Felix\Documents>g.region raster=rast_5f6b63079109d2red
> FEHLER: Rasterkarte <rast_5f6b63079109d2red> konnte nicht gefunden werden.
> C:\Users\Felix\Documents>r.out.gdal -t -m input="rast_5f6b63079109d2red" output="C:/Users/Felix/AppData/Local/Temp/processing_hQOjSy/a3a562fa8e1a423ca4c8698e923ca01a/red.tif" format="GTiff" createopt="TFW=YES,COMPRESS=LZW" --overwrite
> FEHLER: Rasterkarte oder Gruppe <rast_5f6b63079109d2red> nicht gefunden.
> C:\Users\Felix\Documents>g.region raster=rast_5f6b63079109d2green
> FEHLER: Rasterkarte <rast_5f6b63079109d2green> konnte nicht gefunden werden.
> C:\Users\Felix\Documents>r.out.gdal -t -m input="rast_5f6b63079109d2green" output="C:/Users/Felix/AppData/Local/Temp/processing_hQOjSy/c396aa3b10a84565a52ada1c53cb9751/green.tif" format="GTiff" createopt="TFW=YES,COMPRESS=LZW" --overwrite
> FEHLER: Rasterkarte oder Gruppe <rast_5f6b63079109d2green> nicht gefunden.
> C:\Users\Felix\Documents>g.region raster=rast_5f6b63079109d2blue
> FEHLER: Rasterkarte <rast_5f6b63079109d2blue> konnte nicht gefunden werden.
> C:\Users\Felix\Documents>r.out.gdal -t -m input="rast_5f6b63079109d2blue" output="C:/Users/Felix/AppData/Local/Temp/processing_hQOjSy/eb24f00c75eb4813bfe7f10af7238d85/blue.tif" format="GTiff" createopt="TFW=YES,COMPRESS=LZW" --overwrite
> FEHLER: Rasterkarte oder Gruppe <rast_5f6b63079109d2blue> nicht gefunden.
> C:\Users\Felix\Documents>exit
> Execution of <C:\Users\Felix\AppData\Local\Temp\processing_hQOjSy\grassdata\grass_batch_job.cmd> finished.
> Cleaning up temporary files...
> Drücken Sie eine beliebige Taste . . .
> Execution completed in 2.49 seconds
> Results:
> {'blue': <QgsProcessingOutputLayerDefinition {'sink':TEMPORARY_OUTPUT, 'createOptions': {'fileEncoding': 'System'}}>,
> 'green': <QgsProcessingOutputLayerDefinition {'sink':TEMPORARY_OUTPUT, 'createOptions': {'fileEncoding': 'System'}}>,
> 'red': <QgsProcessingOutputLayerDefinition {'sink':TEMPORARY_OUTPUT, 'createOptions': {'fileEncoding': 'System'}}>}
> 
> Loading resulting layers
> The following layers were not correctly generated.
> • C:/Users/Felix/AppData/Local/Temp/processing_hQOjSy/a3a562fa8e1a423ca4c8698e923ca01a/red.tif
> • C:/Users/Felix/AppData/Local/Temp/processing_hQOjSy/c396aa3b10a84565a52ada1c53cb9751/green.tif
> • C:/Users/Felix/AppData/Local/Temp/processing_hQOjSy/eb24f00c75eb4813bfe7f10af7238d85/blue.tif
> You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.

**Comment by gioman** [comment]
@FelixTheAwesomeCat can you attach a sample of the data you are using as input? thanks!

**Comment by FelixTheAwesomeCat** [comment]
Sure, I had to .zip it though since Geotifs are not supported!
[RGB Test.zip](https://github.com/qgis/QGIS/files/5271290/RGB.Test.zip)

**Comment by agiudiceandrea** [comment]
@gioman the issue is a missing point in the name of the layer band...

The procedure firstly imports:
Importing raster map <rast_5f6b63079109d2.red>
Importing raster map <rast_5f6b63079109d2.gree>
Importing raster map <rast_5f6b63079109d2.blue>
Importing raster map <rast_5f6b63079109d2.alpha>

but subsequently  tries to use intead:
g.region raster=rast_5f6b63079109d2red
r.out.gdal -t -m input="rast_5f6b63079109d2red"
g.region raster=rast_5f6b63079109d2green
r.out.gdal -t -m input="rast_5f6b63079109d2green"
g.region raster=rast_5f6b63079109d2green
r.out.gdal -t -m input="rast_5f6b63079109d2green"
g.region raster=rast_5f6b63079109d2blue
r.out.gdal -t -m input="rast_5f6b63079109d2blue"

As you can see, there is a missing point in the name of the grass layers.

**Comment by agiudiceandrea** [comment]
Hi @FelixTheAwesomeCat,
you can try to fix the issue just replacing line 60 of r.rgb.py in [QGIS_install_dir]\apps\qgis\python\plugins\processing\algs\grass7\ext\

`grassName = '{}{}'.format(alg.exportedLayers['input'], color)`

with

`grassName = '{}.{}'.format(alg.exportedLayers['input'], color)`

**Comment by FelixTheAwesomeCat** [comment]
That fixed it! Thank you
