### ISSUE TITLE
Vertex tool: showing outline of unvisible, readonly features

### ISSUE THREAD

**Issue by lukas-hribik** [qgis/QGIS#38992]
**Describe the bug**
Please watch self-explaning video:
http://www.icsp.sk/20200924_095112.mp4

Settings->Options->Digitizing->Enable snapping by default must be set to TRUE before creating new project.

**QGIS and OS versions**
qgis 3.14.16
os win10

**Comment by uclaros** [comment]
Can you provide sample data? Or steps to reproduce with any data set?

**Comment by lukas-hribik** [comment]
You can reproduce with any datasets - just use two temporary layer.

Steps:
1) use clean user profile
2) change "Enable snapping by default" do True in Settings
3) create new project
4) create 2 new temporary polygon layer and draw at least one feature to each one
5) make one layer invisible and readonly (0 disable editing)
6) make second layer visible and editable
7) activate vertex tool
8) navigate mouse to any feature's vertex in invisible layer - you will see red outline of invisible feature
