### ISSUE TITLE
QGIS crashes while loading 

### ISSUE THREAD

**Issue by hannesaddec** [qgis/QGIS#38993]
## User Feedback

just loaded QGIS 3.10.3 LTR in Lutra training - due to being in an out of reverse proxy

## Report Details

**Crash ID**: [472ea3512682a3798d2cecc71f612973b1cc7185]('https://github.com/qgis/QGIS/search?q=472ea3512682a3798d2cecc71f612973b1cc7185&type=Issues')

**Stack Trace**
<pre>
QMetaObject::activate :
QHttpMultiPart::qt_metacast :
QSslKey::operator!= :
QSslKey::operator!= :
QMetaObject::activate :
QAbstractSocket::proxyAuthenticationRequired :
QMetaObject::activate :
QAbstractSocket::proxyAuthenticationRequired :
QNetworkProxyQuery::networkConfiguration :
QMetaObject::activate :
QAbstractSocket::disconnected :
QAbstractSocket::canReadLine :
QNetworkProxyQuery::networkConfiguration :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
QEventLoop::exec :
QThread::exec :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.3-A Coru�a
QGIS code revision: 0e1f846438
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.16299

**Comment by gioman** [comment]
>  QGIS Version: 3.10.3-A Coru�a

@hannesaddec too old, you must upgrade to the latest release of 3.10.

Also try with a new QGIS profile, no 3rd party plugins installed.

If the problem persist please add all the details needed to replicate the issue.

**Comment by hannesaddec** [comment]
unfortunately upgrade is not possible. removing the .ini file helped..
