### ISSUE TITLE
Contour label error (not in plugin)  Extraction/Contour dropdown within QGIS, not plug--WRONG ELEVS shown

### ISSUE THREAD

**Issue by moody1951** [qgis/QGIS#38999]
**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**  3.14.16 pi

Generate contours in the UTM zone and units that comes with the dem.
Contours look good.
Check them with profiler plugin, and they look good.
Label the contours, and the elevation labels are grossly erroneous.
This is not done with a plugin.  It is inside the Raster/Extraction routine and performed on any good DEM.

![image](https://user-images.githubusercontent.com/71227980/94142803-73a26b00-fe34-11ea-935b-2e9658a4a0a9.png)

**Additional context**

**Comment by gioman** [comment]
> and performed on any good DEM

@moody1951 with a good DEM of mine I have no issues whatsoever, following your steps (I used the "contour" tool in processing and the "profile" plugin). So please attach a DEM of yours that do not return the expected results.

**Comment by roya0045** [comment]
Are you using the ID to label the contour insteadd of the elevation attribute?

**Comment by moody1951** [comment]
Roya,
THANK YOU SO MUCH.  That was it. Works perfectly now.

**Comment by roya0045** [comment]
@moody1951 Happens to the best of us.
