### ISSUE TITLE
SAGA Resampling filter can't create output layer

### ISSUE THREAD

**Issue by FelixTheAwesomeCat** [qgis/QGIS#39007]
Using SAGA Resampling filter with an RGB Geotiff does not create output layer.
This is the Error I recieve:
> Load Result Layer
> The following layers were not correctly generated
> • C:/Users/Felix/AppData/Local/Temp/processing_LxPPJg/0ba274f587b64756904437c37e9fc932/HIPASS.sdat
> • C:/Users/Felix/AppData/Local/Temp/processing_LxPPJg/49771a0231c84c4aa85ccef7c07f1268/LOPASS.sdat

In the log i could also find this:
> Error: input file [C:/Users/Felix/AppData/Local/Temp/processing_LxPPJg/5f6b46a4c9544c19a7350b7d8e5ceff6/RGBTest.sgrd]
> Error: Grid

Here is a sample data:
[RGB Test.zip](https://github.com/qgis/QGIS/files/5276499/RGB.Test.zip)

This is the full log:

> WIN 10
> QGIS-Version: 3.14.16-Pi
> QGIS-Codeversion: df27394552
> Qt-Version: 5.11.2
> GDAL-Version: 3.0.4
> GEOS-Version: 3.8.1-CAPI-1.13.3
> PROJ-Version: Rel. 6.3.2, May 1st, 2020
> Verarbeite Algorithmus…
> Algorithmus Resampling filter startet…
> Eingabeparameter:
> { 'GRID' : 'C:/Users/Felix/Desktop/RGB Test.tif', 'HIPASS' : 'TEMPORARY_OUTPUT', 'LOPASS' : 'TEMPORARY_OUTPUT', 'SCALE' : 10 }
> 
> io_gdal 0 -TRANSFORM 1 -RESAMPLING 3 -GRIDS "C:/Users/Felix/AppData/Local/Temp/processing_LxPPJg/5f6b46a4c9544c19a7350b7d8e5ceff6/RGBTest.sgrd" -FILES "C:/Users/Felix/Desktop/RGB Test.tif"
> grid_filter "Resampling Filter" -GRID "C:/Users/Felix/AppData/Local/Temp/processing_LxPPJg/5f6b46a4c9544c19a7350b7d8e5ceff6/RGBTest.sgrd" -SCALE 10.0 -LOPASS "C:/Users/Felix/AppData/Local/Temp/processing_LxPPJg/4a377d3fa48e49729d9cb00942fdff58/LOPASS.sdat" -HIPASS "C:/Users/Felix/AppData/Local/Temp/processing_LxPPJg/d899189f103e4dff9401316f63947482/HIPASS.sdat"
> 
> C:\OSGeo4W64\bin>set SAGA=C:/OSGEO4~1/apps\saga-ltr
> 
> C:\OSGeo4W64\bin>set SAGA_MLB=C:/OSGEO4~1/apps\saga-ltr\modules
> 
> C:\OSGeo4W64\bin>PATH=C:\OSGEO4~1\apps\qgis\bin;C:\OSGEO4~1\apps\grass\grass78\lib;C:\OSGEO4~1\apps\grass\grass78\bin;C:\OSGEO4~1\apps\Python37;C:\OSGEO4~1\apps\Python37\Scripts;C:\OSGEO4~1\apps\Python37;C:\OSGEO4~1\apps\Python37\Scripts;C:\OSGEO4~1\apps\qt5\bin;C:\OSGEO4~1\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\system32\WBem;C:\OSGEO4~1\apps\Python37\lib\site-packages\pywin32_system32;C:\OSGEO4~1\apps\Python37\lib\site-packages\numpy\.libs;C:/OSGEO4~1/apps\saga-ltr;C:/OSGEO4~1/apps\saga-ltr\modules
> 
> C:\OSGeo4W64\bin>call saga_cmd io_gdal 0 -TRANSFORM 1 -RESAMPLING 3 -GRIDS "C:/Users/Felix/AppData/Local/Temp/processing_LxPPJg/5f6b46a4c9544c19a7350b7d8e5ceff6/RGBTest.sgrd" -FILES "C:/Users/Felix/Desktop/RGB Test.tif"
> ____________________________
> 
> ##### ## ##### ##
> ### ### ## ###
> ### # ## ## #### # ##
> ### ##### ## # #####
> ##### # ## ##### # ##
> ____________________________
> 
> SAGA Version: 2.3.2 (64 bit)
> 
> ____________________________
> library path: C:\OSGEO4~1\apps\saga-ltr\modules\
> library name: io_gdal
> library : GDAL/OGR
> tool : Import Raster
> author : O.Conrad (c) 2007 (A.Ringeler)
> processors : 12 [12]
> ____________________________
> 
> 
> 
> Parameters
> 
> 
> Grids: No objects
> Files: "C:/Users/Felix/Desktop/RGB Test.tif"
> Select from Multiple Bands:
> Alphanumeric Sorting: yes
> Transformation: yes
> Resampling: B-Spline Interpolation
> 
> 
> loading: C:/Users/Felix/Desktop/RGB Test.tif
> 
> 
> 
> Driver: GTiff
> 
> Bands: 4
> 
> Rows: 4834
> 
> Columns: 2458
> 
> 
> 
> Transformation:
> 
> x' = 510443.550700 + x * 0.012542 + y * 0.000000
> 
> y' = 5666567.691300 + x * 0.000000 + y * -0.012542
> 
> 
> loading: RGB Test [1/4]
> 
> 
> 
> warning: top-to-bottom and left-to-right cell sizes differ.
> Difference: 0.000000
> 
> using cellsize: 0.012542
> 
> 
> 
> 
> 
> 
> warning: top-to-bottom and left-to-right cell sizes differ.
> Difference: 0.000000
> 
> using cellsize: 0.012542
> 
> 
> 
> 
> 
> 
> warning: top-to-bottom and left-to-right cell sizes differ.
> Difference: 0.000000
> 
> using cellsize: 0.012542
> 
> 
> 
> 
> C:\OSGeo4W64\bin>call saga_cmd grid_filter "Resampling Filter" -GRID "C:/Users/Felix/AppData/Local/Temp/processing_LxPPJg/5f6b46a4c9544c19a7350b7d8e5ceff6/RGBTest.sgrd" -SCALE 10.0 -LOPASS "C:/Users/Felix/AppData/Local/Temp/processing_LxPPJg/4a377d3fa48e49729d9cb00942fdff58/LOPASS.sdat" -HIPASS "C:/Users/Felix/AppData/Local/Temp/processing_LxPPJg/d899189f103e4dff9401316f63947482/HIPASS.sdat"
> Error: input file [C:/Users/Felix/AppData/Local/Temp/processing_LxPPJg/5f6b46a4c9544c19a7350b7d8e5ceff6/RGBTest.sgrd]
> Error: Grid
> ____________________________
> 
> ##### ## ##### ##
> ### ### ## ###
> ### # ## ## #### # ##
> ### ##### ## # #####
> ##### # ## ##### # ##
> ____________________________
> 
> SAGA Version: 2.3.2 (64 bit)
> 
> ____________________________
> library path: C:\OSGEO4~1\apps\saga-ltr\modules\
> library name: grid_filter
> library : Filter
> tool : Resampling Filter
> author : O.Conrad (c) 2012
> processors : 12 [12]
> ____________________________
> 
> Load grid: C:/Users/Felix/AppData/Local/Temp/processing_LxPPJg/5f6b46a4c9544c19a7350b7d8e5ceff6/RGBTest.sgrd...
> failed
> 
> Usage: saga_cmd grid_filter 11 [-GRID <str>] [-LOPASS <str>] [-HIPASS <str>] [-SCALE <double>]
> -GRID:<str> Grid
> Grid (input)
> -LOPASS:<str> Low Pass Filter
> Grid (output)
> -HIPASS:<str> High Pass Filter
> Grid (output)
> -SCALE:<double> Scale Factor
> Floating point
> Minimum: 1.000000
> Default: 10.000000
> 
> C:\OSGeo4W64\bin>exit
> Ausführung nach 11.70 Sekunden abgeschlossen
> Ergebnisse:
> {'HIPASS': 'C:/Users/Felix/AppData/Local/Temp/processing_LxPPJg/d899189f103e4dff9401316f63947482/HIPASS.sdat',
> 'LOPASS': 'C:/Users/Felix/AppData/Local/Temp/processing_LxPPJg/4a377d3fa48e49729d9cb00942fdff58/LOPASS.sdat'}
> 
> Lade Ergebnis Layer
> Die folgenden Layer wurden nicht erzeugt.
> • C:/Users/Felix/AppData/Local/Temp/processing_LxPPJg/0ba274f587b64756904437c37e9fc932/HIPASS.sdat
> • C:/Users/Felix/AppData/Local/Temp/processing_LxPPJg/49771a0231c84c4aa85ccef7c07f1268/LOPASS.sdat
> • C:/Users/Felix/AppData/Local/Temp/processing_LxPPJg/4a377d3fa48e49729d9cb00942fdff58/LOPASS.sdat
> • C:/Users/Felix/AppData/Local/Temp/processing_LxPPJg/d899189f103e4dff9401316f63947482/HIPASS.sdat
> Im 'Protokoll-Fenster' im QGIS-Hauptfenster sind mehr Informationen zur Ausführung des Algorithmus zu finden.

**Comment by gioman** [comment]
@FelixTheAwesomeCat as far as I remember SAGA mostly needs single band rasters as inputs. Please try the same operation directly using SAGA, for example from the command line.

**Comment by FelixTheAwesomeCat** [comment]
It works fine in SAGA 7.6.3. In SAGA 2.3.2 I cant choose more then one layer, so I think you are right. Are there any plans to change to version 7? 2.3.2 seems very old and clunky to me!

**Comment by gioman** [comment]
> 2.3.2 seems very old and clunky to me

@FelixTheAwesomeCat there is a "saga" behind this SAGA matter... Plain is to remove all the external providers from Processing al let plugins handle them. In fact there are already Processing plugins that support more recent versions of SAGA.

**Comment by FelixTheAwesomeCat** [comment]
Could you tell me one which uses more recent saga versions? Probably good to get rid of them...most problems I have come from OTB, SAGA and GRASS implementation

**Comment by gioman** [comment]
> Could you tell me one which uses more recent saga versions?

i.e. https://plugins.bruy.me/
