### ISSUE TITLE
Only first row for Postgis raster table in DB Manager preview and when adding layer to Map canvas

### ISSUE THREAD

**Issue by FelisPimeja** [qgis/QGIS#39017]
I've got a postgis raster table with several rows, say 2. When I try to preview this raster in DB Manager it shows me only first row. 
Then if I add it to Map canvas I also see only one tile for the first row. Interesting thing that in layer properties Raster histogram is calculated correctly with Min/Max values for all the rows in a table. As I can remember in several previous versions of Qgis (for example 3.8.1) DB Manager showed all raster rows and it was correctly adding all raster tiles to canvas. Is it a regression?

Qgis 3.16 Nightly (and Qgis 3.10 also):
![image](https://user-images.githubusercontent.com/874261/94212732-a7859b00-fedd-11ea-915d-ae773763c460.png)
![image](https://user-images.githubusercontent.com/874261/94212762-ba986b00-fedd-11ea-9b7d-546ef05513f6.png)
![image](https://user-images.githubusercontent.com/874261/94213093-adc84700-fede-11ea-861c-9939c893e298.png)

Qgis 3.8.1:
![image](https://user-images.githubusercontent.com/874261/94212781-c84df080-fedd-11ea-82b4-eec10b5b2207.png)
![image](https://user-images.githubusercontent.com/874261/94213109-b9b40900-fede-11ea-8baf-09256fa23bbb.png)

System config:
Windows 10

QGIS version
3.15.0-Master
QGIS code revision
3119eb7
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.2.0dev
Running against GDAL/OGR
3.2.0dev
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
7.2.0
Running against PROJ
Rel. 7.2.0, November 1st, 2020
OS Version
Windows 10 (10.0)
This copy of QGIS writes debugging output.

**Comment by elpaso** [comment]
Can you please attach a (possibly small) DB dump to reproduce the issue?

**Comment by FelisPimeja** [comment]
> Can you please attach a (possibly small) DB dump to reproduce the issue?

Ok. Here it is.
It creates tmp.rast_test table which contains 2 rows:
![image](https://user-images.githubusercontent.com/874261/94248115-b0e72580-ff26-11ea-99c6-72090dda5f9f.png)

And here how it looks like in Qgis 3.8.1:
![image](https://user-images.githubusercontent.com/874261/94248290-f277d080-ff26-11ea-8045-152a64da2016.png)

 
[t1.zip](https://github.com/qgis/QGIS/files/5281671/t1.zip)

**Comment by elpaso** [comment]
Is this a DB-Manager issue only or do you also have problems in QGIS desktop application outside of DB-Manager (for example in the browser or when adding the layer to the canvas)?

**Comment by FelisPimeja** [comment]
> Is this a DB-Manager issue only or do you also have problems in QGIS desktop application outside of DB-Manager (for example in the browser or when adding the layer to the canvas)?

Same behavior when I add layer to canvas from DB Manager. I can see only tile from the first row.
