### ISSUE TITLE
Different behaviour with raster calculator between Windows 10 and Ubuntu 18.04

### ISSUE THREAD

**Issue by MaxDragonheart** [qgis/QGIS#39028]
QGIS 3.10
OS: Windows 10 and Ubuntu 18.04

I've tried to make a difference between two raster. On Windows 10 I've an incorrect result because all pixel are between 9998 and 9999 but the same process with the same data on Ubuntu 18.04 gave a correct result. I've do this on the desktop with dual boot Windows 10/Ubuntu 18.04

[Here ](https://drive.google.com/file/d/1nbaNKF1W5LJwiLNm4r2E82qDz5xwsXaN/view?usp=sharing)the original data

**Comment by elpaso** [comment]
Remember: we have three different raster calculators in QGIS, please add all the steps to reproduce the issue.

**Comment by MaxDragonheart** [comment]
It's right, excuse me.

`QGIS menu > Raster > Raster Calculator`

Then DSM - DTM.

**Comment by gioman** [comment]
> I've tried to make a difference between two raster. On Windows 10 I've an incorrect result because all pixel are between 9998 and 9999 but the same process with the same data on Ubuntu 18.04 gave a correct result. I've do this on the desktop with dual boot Windows 10/Ubuntu 18.04

@MaxDragonheart I get identical results on Linux Ubuntu and Windows 10.

**Comment by MaxDragonheart** [comment]
OK, maybe is a problem on my PC

**Comment by gioman** [comment]
Closing for lack of further feedback.
