### ISSUE TITLE
Digitizing properties and saving edited layers

### ISSUE THREAD

**Issue by ludovico85** [qgis/QGIS#39022]
Setting the topology checks option in the vector digitizing properties dialog doesn't allow the Save Layer Edits to work properly, that is the software leaves the editing mode.

1. Create a polygon vector layer
2. Set the topology checks option in the vector digitizing properties dialog (any of the three options - Gap, Missing vertex or Overlap)
3. Start crating a new polygon
4. Click on Save Layer Edits

![ice_video_20200925-075355](https://user-images.githubusercontent.com/24815399/94231859-1fb38700-ff05-11ea-976d-d0d5567be767.gif)

**QGIS and OS versions**

3.10.10
3.14.16
Windows 10

**Comment by gioman** [comment]
I have the strong sensation there is already a ticket about this issue, but can't find it now.

**Comment by Pedro-Murteira** [comment]
I can still replicate this issue on QGIS 3.16.15 and 3.22.2. (Windows 10)

**Comment by alexbruy** [comment]
Fixed in the latest master (f344919474).
