### ISSUE TITLE
Scale dependent snapping does not activate as long as it displays the scale as "1:xxxxxx"

### ISSUE THREAD

**Issue by uclaros** [qgis/QGIS#39031]
**Describe the bug**
When defining per layer scale dependent snapping, the scale is not considered unless focus has changed from the scale drop down to another widget of the individual layer settings and the scale display changes from `1:1000` to `1000`.

See screencast:
![snap_scale](https://user-images.githubusercontent.com/11358178/94254446-759d2480-ff2f-11ea-8012-e45d1dc5403a.gif)

**How to Reproduce**
1. Enable advanced snapping with per layer scale dependent snapping
2. Select min scale for a layer from the drop down.
3. Close the advanced configuration widget
4. The value set is not respected

**QGIS and OS versions**
02f5c13ea0 on Debian

**Additional context**
ping @obrix

**Comment by obrix** [comment]
I can reproduce the issue. Seems to be a problem with a missing trigger of the call to setModelData on the QgsSnappingLayerDelegate. Ping @troopa81
