### ISSUE TITLE
QGIS no longer imports my csv file the same way what could have changed?

### ISSUE THREAD

**Issue by alexxmarsh44** [qgis/QGIS#39035]
Every time I import my CSV file it would plot the GPS coordinated on the map.  I import the openstreetmap first then my csv file on top of it.  Now all of a sudden it imports it ok then the coordinates are no longer placed on the map.  I have not changed anything what could have caused this?   I am afraid I may be the victim of hackers that have manipulated the code so I need to be sure that no other reason could have caused this.  Thank you.

**Comment by roya0045** [comment]
>  I am afraid I may be the victim of hackers that have manipulated the code so I need to be sure that no other reason could have caused this. Thank you.

Wat.

Just use add text delimited layer to import csv files and ensure they are properly loaded.

**Comment by gioman** [comment]
> Every time I import my CSV file it would plot the GPS coordinated on the map

are you doing it the right way? using the "add delimited text layer" tool?

**Comment by gioman** [comment]
Closing for lack of feedback.
