### ISSUE TITLE
No QGIS plugins found in /Applications/QGIS3.10.app/Contents/MacOS/../PlugIns/qgis

### ISSUE THREAD

**Issue by baditaflorin** [qgis/QGIS#39044]
**Describe the bug**

**How to Reproduce**

1. Go to Qgis website
2. Download the latest Qgis version (either LTS or latest) and install on MacosX Catalina
3. Click Plugins menu -> Manage and Install Plugins
You will get this error `No QGIS plugins found in /Applications/QGIS3.10.app/Contents/MacOS/../PlugIns/qgis`
4. You will see 0 available plugins to install.

**QGIS and OS versions**

QGIS version | 3.10.10-A Coruña | QGIS code revision | 1869829378
-- | -- | -- | --
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.28.0 | Running against SQLite | 3.28.0
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS 10.15

**Additional context**

I also get this red banner 
```Authentication System: DISABLED. Resources authenticating via the system can not be accessed```
But Qgis never asks for permission

**Comment by baditaflorin** [comment]
This link works perfectly https://www.dropbox.com/sh/w43am79lkx716p0/AABJp0sUUCaXTX5MLg41h36oa?dl=0&preview=qgis_ltr_final-3_4_5_20190222_082309.dmg

Discovered using archive.org https://web.archive.org/web/20190511133939/https://lutraconsulting.github.io/qgis-mac-packager/

**Comment by PeterPetrik** [comment]
Hi @baditaflorin can you try 
1. Start the new profile (clean) and restart QGIS 
2. Install https://qgis.org/downloads/macos/nightly/qgis_nightly_master_20200930_033402.dmg. It has completely reworked packaging mechanism than LTR and will be next QGIS 3.16.
