### ISSUE TITLE
Cost allocation in module r.cost doesn't work in QGIS version 3.4.15 and 3.10.2 and 3.10.5

### ISSUE THREAD

**Issue by Cebrian007** [qgis/QGIS#39049]
I have generated a a raster map indicating the cost of traversing each cell in the north-south and east-west directions in order to use it to make a cost allocation map. I have used various versions of QGIS, 3.4.15,3.10.2 and 3.10.5 and none of them seem to work. I get the same error message in the 3 versions, for which I believe it is a bug. I have attached a screenshot of the error message.
![Captura de pantalla 2020-09-26 194947](https://user-images.githubusercontent.com/71940751/94347066-80d87900-0031-11eb-8da0-4cc893bff9db.png)

**Comment by gioman** [comment]
> I have generated a a raster map indicating the cost of traversing each cell

@Cebrian007 please attach it here.

**Comment by Cebrian007** [comment]
I guess you mean the friction map but the system doesn't let me attach the zip file because apparently it is too big (512 MB). Any suggestions about how to attach it is very welcome Gioman

**Comment by gioman** [comment]
>  Any suggestions about how to attach it is very welcome

@Cebrian007 use google drive, dropbox, wetransfer, etc.

**Comment by Cebrian007** [comment]
I am sorry for my clumsiness, I can use google drive but where do I send the email?

**Comment by Cebrian007** [comment]
Sorry, I got it now. I can send it to the same email address where I am receiving the notifications, right?

**Comment by gioman** [comment]
> I am sorry for my clumsiness, I can use google drive but where do I send the email?

from gdrive you can a share link you can post here.

**Comment by gioman** [comment]
> Sorry, I got it now. I can send it to the same email address where I am receiving the notifications, right?

 no, share the link here, do not send any email.

**Comment by Cebrian007** [comment]
I am trying to find the way to share the link

**Comment by Cebrian007** [comment]
https://1drv.ms/u/s!AlnZAZ4TUGR5gbdqShBSDedH4WVGxg?e=SXXaFj

**Comment by Cebrian007** [comment]
By the way Gioman, I forgot to mention that the weirdest thing is that the cumulative cost tool works fine in the module r.cost. The issue is only with the cost allocation tool

**Comment by gioman** [comment]
> By the way Gioman, I forgot to mention that the weirdest thing is that the cumulative cost tool works fine in the module r.cost. The issue is only with the cost allocation tool

 @Cebrian007 I get identical results in QGIS and using native GRASS. So please test in native GRASS, if the results are the same them please file a ticket on the GRASS bug tracker.

**Comment by Cebrian007** [comment]
Yes, I am pretty sure this is due to a bug. I will later test it in native GRASS

**Comment by gioman** [comment]
> Yes, I am pretty sure this is due to a bug

@Cebrian007 if the results (in QGIS and native GRASS) are the same and one result is botched then the bug is in GRASS, not QGIS.

**Comment by Cebrian007** [comment]
Yes, the bug probably is in GRASS
