### ISSUE TITLE
QGIS-server WMTS custom tilematrix set: mismatch between original data and wmts version 

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS#39040]
[28992.zip](https://github.com/qgis/QGIS/files/5283458/28992.zip)

In that zip is data (a simple geopackage) AND a project file. Loading it in QGIS you should see:

![Screenshot-20200925164508-1015x520](https://user-images.githubusercontent.com/731673/94281094-7d1ff600-ff4e-11ea-80e9-f372c7b62482.png)

From the official document:
https://www.geonovum.nl/uploads/standards/downloads/nederlandse_richtlijn_tiling_-_versie_1.1.pdf
AND from our national service WMTS url:
https://geodata.nationaalgeoregister.nl/wmts?VERSION=1.0.0&request=GetCapabilities
I got the following properties for the WMTS (and edited those in the Grids table):
EPSG:28992
Top: 903402.00  (these are meters)
Left: -285401.92
Min.Scale: 12288000.00
Last level 14

Creating a QGIS server from this results in the right tilematrix:

```
<TileMatrixSet><ows:Identifier>EPSG:28992</ows:Identifier><ows:SupportedCRS>EPSG:28992</ows:SupportedCRS><TileMatrix><ows:Identifier>0</ows:Identifier><ScaleDenominator>12288000</ScaleDenominator><TopLeftCorner>-285401.92 903402</TopLeftCorner><TileWidth>256</TileWidth><TileHeight>256</TileHeight><MatrixWidth>1</MatrixWidth><MatrixHeight>1</MatrixHeight></TileMatrix>
```

as from the offical pdok service:

```
<TileMatrixSet><ows:Identifier>EPSG:28992</ows:Identifier><ows:SupportedCRS>urn:ogc:def:crs:EPSG::28992</ows:SupportedCRS><TileMatrix><ows:Identifier>00</ows:Identifier><ScaleDenominator>1.2288E7</ScaleDenominator><TopLeftCorner>-285401.92 903402.0</TopLeftCorner><TileWidth>256</TileWidth><TileHeight>256</TileHeight><MatrixWidth>1</MatrixWidth><MatrixHeight>1</MatrixHeight></TileMatrix>
```

So I think that is ok. Creating the WMTS now and requesting it in the WMS/WMTS dialog show the proper layer and tilesets:

![Screenshot-20200925165334-479x362](https://user-images.githubusercontent.com/731673/94282047-ab520580-ff4f-11ea-8ea5-9da2bc15e91a.png)

But then loading the layer shows it is shifted:

![Screenshot-20200925165438-861x434](https://user-images.githubusercontent.com/731673/94282243-df2d2b00-ff4f-11ea-9384-cb9fd920121c.png)

To double check you can add the 'opentopo' layer from this public WMTS:

https://geodata.nationaalgeoregister.nl/wmts?VERSION=1.0.0&request=GetCapabilities

As you can see the wmts seems shifted:

![Screenshot-20200925165624-1103x488](https://user-images.githubusercontent.com/731673/94282508-36cb9680-ff50-11ea-8d88-4df85df42f94.png)

NOTE: we did have this kind of shifts earlier, when we used different proj params for EPSG:28992, and the default epsg params where not right yet in the official db...

But as you can see the data itself is exactly mapping the PDOK WMTS. and I would think the project/data and the server/data would use the same epsg:28992 definitions?

**Comment by rldhont** [comment]
@rduivenvoorde can you provide data and project ?

**Comment by rduivenvoorde** [comment]
yes yes, sorry. I'm busy, I accidently push the OK button... :-)

**Comment by rldhont** [comment]
It was juste a reminder, thanks
