### ISSUE TITLE
Wrong limit parameter behavior for geometry_overlay_intersects function

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#39068]
If I use `limit:=2`, then I get the expected value (a single feature)
![image](https://user-images.githubusercontent.com/7983394/94442109-d92f8800-01a3-11eb-990b-6c3daf9f9717.png)
If I use `limit:=1`,it's expected to return that same value but it instead returns an empty list (and not coherent wit the docs in the third panel (the limit is supposed to be included)
![image](https://user-images.githubusercontent.com/7983394/94441838-86ee6700-01a3-11eb-9e50-83c85f92d63a.png)

But if I use limit with the geometry_overlay_disjoint, it works as expected
![image](https://user-images.githubusercontent.com/7983394/94447925-a472ff00-01aa-11eb-8015-d8c61e5a0384.png)

QGIS version | 3.15.0-Master | QGIS code revision | 0fb7c44645
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.2.0dev | Running against GDAL/OGR | 3.2.0dev
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 7.2.0 | Running against PROJ | Rel. 7.2.0, November 1st, 2020
OS Version | Windows 10 (10.0) | This copy of QGIS writes debugging output.
Active python plugins |

**Comment by DelazJ** [comment]
Testing a bit more, I found out that `limit` (with geometry_overlay_intersects for what i checked) does not represent the number of results to return but the max of the features ID to return. IOW if limit is >= the resulting features $id, then they are returned
![image](https://user-images.githubusercontent.com/7983394/94450284-5ca1a700-01ad-11eb-81e0-361a2db58ea0.png)
If I understood correctly, the example above should return features 4 and 5

**Comment by m-kuhn** [comment]
Could you run the same test with another data source (gpkg, shp, ...) I have an assumption that this might be scratch layer related rather than geometry_overlay related...

**Comment by DelazJ** [comment]
Not sure "scratch layer" is the culprit. I tried on my ubuntu20.04 build and could not reproduce, using either shapefile or scratch layer of the same data. The report above was with win10 osgeo4w.
Maybe something to do with geos version (ref. a recent report with intersection)? Here's my Ubuntu about, I'll post the Windows one tomorrow

QGIS version | 3.15.0-Master | QGIS code revision | 8d2a0d1ebb
-- | -- | -- | --
Compiled against Qt | 5.12.8 | Running against Qt | 5.12.8
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.4 (Ubuntu 12.4-0ubuntu0.20.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Ubuntu 20.04.1 LTS | This copy of QGIS writes debugging output.
Active python plugins | db_manager; MetaSearch; processing

**Comment by DelazJ** [comment]
I updated the report with the version info and tested with shapefile. I also got incomplete results when the limit is not greater than the feature $id. Then I delete some features and the function returns the missing results once their $id becomes lower than the set limit.

**Comment by m-kuhn** [comment]
CC @olivierdalang

**Comment by olivierdalang** [comment]
Ok I think I found the bug : the limit parameter was limiting the feature request BEFORE the spatial test... I'll open a PR shortly
