### ISSUE TITLE
GRASS r.stream.extract crash

### ISSUE THREAD

**Issue by GISstudentJeremy** [qgis/QGIS#39060]
Hello everyone,

I've been having an issue with the r.stream.extract crashing QGIS. Everything is in the correct CRS and the plugin is enabled. The elevation layer I'm using is a .tif file. I'm not sure how to access the crash reports to see what the problem is. 

Any troubleshooting advice or questions would be helpful for this issue. You guys are my only hope, thank you

**Comment by gioman** [comment]
@GISstudentJeremy are you referring to the tool in the Processing toolbox or the GRASS plugin?

What QGIS version do you use? On what operating system? Can you attach sample data?

**Comment by GISstudentJeremy** [comment]
Hi gioman,

I am referring to the grass plugin I think. The version I'm using is the QGIS Desktop 3.12.3 with GRASS 7.8.3. The data I'm using is a clipped .tif file from the National Hydrography dataset here-- https://datagateway.nrcs.usda.gov/GDGOrder.aspx  Is there any other info you would need to help me troubleshoot the issue?? Thank you so much, I really appreciate it

**Comment by gioman** [comment]
> National Hydrography dataset here-- https://datagateway.nrcs.usda.gov/GDGOrder.aspx

@GISstudentJeremy can you please attach the dataset (as zip) here? the link you posted do not point directly to a specific dataset?

**Comment by GISstudentJeremy** [comment]
https://drive.google.com/file/d/19F6IukNsMJ-ozr0FNRwTs-Tc7DUcTUk4/view?usp=sharing

Sorry about that, here is a google drive link since the zipped files is too large

**Comment by gioman** [comment]
@GISstudentJeremy works for me on both on Linux and Windows. It is a quite heavy analysis, maybe you are missing some RAM do be able to run the analysis to the end?

**Comment by GISstudentJeremy** [comment]
Should I give it more memory before running? My computer has been able to
do it before is the thing. Now anytime I run r.stream.extract it stops
responding

**Comment by gioman** [comment]
> My computer has been able to do it before is the thing.

@GISstudentJeremy with the same dataset? Can you try on a different machine?

**Comment by roya0045** [comment]
If ressource limitation is an issue maybe there are other memory heavy programs that uses too much ressources and make it fails when those programs are active?

**Comment by GISstudentJeremy** [comment]
I don't think resource limitations are the issue since I was able to fully run the application and tools before. Could there be the possibility of GRASS tools not installing correctly??

**Comment by gioman** [comment]
> I don't think resource limitations are the issue since I was able to fully run the application and tools before. Could there be the possibility of GRASS tools not installing correctly??

@GISstudentJeremy see https://github.com/qgis/QGIS/issues/39060#issuecomment-700244453 and also please try run the same analysis on native GRASS to see if it makes any difference.

**Comment by GISstudentJeremy** [comment]
I just ran it on a remote desktop computer from the school and the crash occurred again. I clipped the raster down to a more manageable size as well.  Currently I'm importing the same Raster on Native GRASS but it's taking a bit. What settings should I have to be running the GRASS tools on QGIS?

**Comment by gioman** [comment]
> What settings should I have to be running the GRASS tools on QGIS?

none particular, is auto-configuring if you use the standalone installer. Anyway please also update your QGIS, 3.12 is too old.

**Comment by GISstudentJeremy** [comment]
On the remote desktop it is using 3.14 and the crash still occurs in the same manner. If you're willing to talk over skype, teams or over the phone we might be able to solve the issue faster and make a forum post showing the fix. I understand you're not personal support on GIS issues but you've been a great help so far and I greatly appreciate it Gioman
 
![Capture](https://user-images.githubusercontent.com/71992649/94997893-ffb64000-0562-11eb-89c2-9ac7f116bf7f.PNG)

**Comment by gioman** [comment]
> the crash

@GISstudentJeremy in your screenshot I don't see any crash. I see a Windows message "not responding" that it can mean that a program really is stuck, but frequently just means "I'm thinking hard". Have you tried leaving the process run for enough time?

**Comment by gioman** [comment]
Closing for lack of further feedback.
