### ISSUE TITLE
QGIS Master crashes when expanding PostgreSQL database in DB Manager

### ISSUE THREAD

**Issue by RNanclares** [qgis/QGIS#39074]
**Describe the bug**
QGIS crashes when expanding a postgresql database in the Database Manager.
**How to Reproduce**
Open QGIS. > Go to DB Manager > Expand database in PostGIS section > results in "QGIS died on signal 11Aborted (core dumped)"

**QGIS and OS versions**
QGIS Master 3.15 QGIS code revision | 138762146e
Postgresql 12 + Postgis 3.0.2 (POSTGIS="3.0.2 2fb2a18" [EXTENSION] PGSQL="120" GEOS="3.8.0-CAPI-1.13.1 " PROJ="6.3.1" LIBXML="2.9.10" LIBJSON="0.13.1" LIBPROTOBUF="1.3.3" WAGYU="0.4.3 (Internal)")

Pop_OS! 20.04

**Comment by gioman** [comment]
@RNanclares duplicate of https://github.com/qgis/QGIS/issues/38393 ?

**Comment by RNanclares** [comment]
sorry!
