### ISSUE TITLE
in QGIS 3.10.10 project related spatial bookmarks also appear in other projects

### ISSUE THREAD

**Issue by lajunek** [qgis/QGIS#39077]
**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by gioman** [comment]
@lajunek can you please fill the necessary info?

Describe the bug

How to Reproduce

QGIS and OS versions

Additional context

**Comment by gioman** [comment]
Closing for lack of feedback.
