### ISSUE TITLE
GetLegendImage URL should respect the ignore GetMap value in GetCapabilities check box with WMS & WMTS requests

### ISSUE THREAD

**Issue by ianturton** [qgis/QGIS#39080]
**Describe the bug**

If a WMTS reports an incorrect URL in it's capabilities document QGis allows users to ignore them but getLegend requests don't ignore the capabilities value. Until #21425 is implemented then make the legend graphic url dependent on if the getMap URL is being ignored.  

**How to Reproduce**

1. Install a local GeoServer and break the capabilities file by adding a non existent url in the proxy url under global settings.
2. Add the WMTS getCapabilities link from the GeoServer front page to QGIS, checking the ignore url for gettile and getfeatureinfo boxes
3. Install QGIS Network logger
4. add a layer from the GeoServer install
5. No legend is displayed - instead of generating a correct URL from the base of the getCapabilities request it will attempt to use the incorrect one from the capabilities document.

**QGIS and OS versions**

QGIS version
3.14.16-Pi
QGIS code revision
a235a14
Compiled against Qt
5.12.8
Running against Qt
5.12.8
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1
Compiled against SQLite
3.31.1
Running against SQLite
3.31.1
PostgreSQL Client Version
12.4 (Ubuntu 12.4-0ubuntu0.20.04.1)
SpatiaLite Version
4.3.0a
QWT Version
6.1.4
QScintilla2 Version
2.11.2
Compiled against PROJ
6.3.1
Running against PROJ
Rel. 6.3.1, February 10th, 2020
OS Version
Ubuntu 20.04.1 LTS
Active python plugins
vrtbuilderplugin;
autoSaver;
Projestions;
QGISSortAndNumber-master;
QGIS3-getWKT;
qgis_hats;
MemoryLayerSaver;
isochrones;
firstaid;
OSMDownloader;
qchainage;
plugin_reloader;
Beeline;
profiletool;
polystrip;
TerrainShading;
cartogram3;
Hqgis;
pluginbuilder3;
quick_map_services;
osgb-plugin;
pointsamplingtool;
DataPlotly;
QuickWKT;
timemanager;
processing;
MetaSearch;
db_manager;
qgis_resource_sharing;
qgisnetworklogger

**Additional context**

**Comment by agiudiceandrea** [comment]
@Pedro-Murteira this is fixed after https://github.com/qgis/QGIS/pull/41596 since 3.16.6.

**Comment by agiudiceandrea** [comment]
@Pedro-Murteira if the user was referencing to GetLegendGraphic instead of (incorrect?) GetLegendImage, then this issue is now fixed after https://github.com/qgis/QGIS/pull/41596 since 3.16.6.
