### ISSUE TITLE
WFS - some features are missing

### ISSUE THREAD

**Issue by pathmapper** [qgis/QGIS#39081]
**Describe the bug**
For a given WFS some features are missing despite they are included in the WFS GML response which works flawlessly in QGIS.
The bug might be related to circular arcs and exists on Linux and Windows.

**How to Reproduce**
1. Add the following WFS: https://geoservices.krzn.de/security-proxy/services/wfs_kvie_jagdbezirke with layer **gis:kvie_jagdbezirke**
4. See error: Some features are missing
<img src="https://user-images.githubusercontent.com/20856381/94569777-6212f600-026e-11eb-85e6-c5c3ccd40e24.png" width="500">

---

**Missing features in red:**

![grafik](https://user-images.githubusercontent.com/20856381/94569638-3a239280-026e-11eb-855c-41703374c8d0.png)

**QGIS and OS versions**

**Windows**
QGIS-Version | 3.14.16-Pi | QGIS-Codeversion | df27394552
-- | -- | -- | --
Kompiliert gegen Qt | 5.11.2 | Laufendes Qt | 5.11.2
Kompiliert mit GDAL/OGR | 3.0.4 | Läuft mit GDAL/OGR | 3.0.4
Kompiliert mit GEOS | 3.8.1-CAPI-1.13.3 | Läuft mit GEOS | 3.8.1-CAPI-1.13.3
Kompiliert mit SQLite | 3.29.0 | Läuft mit SQLite | 3.29.0
PostgreSQL-Client-Version | 11.5 | SpatiaLite-Version | 4.3.0
QWT-Version | 6.1.3 | QScintilla2-Version | 2.10.8
Kompiliert mit PROJ | 6.3.2 | Läuft mit PROJ | Rel. 6.3.2, May 1st, 2020
BS-Version | Windows 10 (10.0)
Aktive Python-Erweiterungen | QuickOSM; db_manager; MetaSearch; processing

**Linux**

QGIS version | 3.14.16-Pi | QGIS code revision | a235a149f0
-- | -- | -- | --
Compiled against Qt | 5.11.3 | Running against Qt | 5.11.3
Compiled against GDAL/OGR | 2.4.0 | Running against GDAL/OGR | 2.4.0
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.27.2 | Running against SQLite | 3.27.2
PostgreSQL Client Version | 11.7 (Debian 11.7-0+deb10u1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.10.4
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Debian GNU/Linux 10 (buster)
Active python plugins | ClipMultipleLayers; quick_map_services; scriptrunner3; LAStools; canvas_clipper; savedialog; loadthemall; clipper; kmltools; MapsPrinter; mmqgis; pluginbuilder3; vector_tiles_reader; layerGroupFilter; plugin_reloader; realcentroid; mask; MetaSearch; db_manager; processing

**Additional context**
Missing features are having circular arcs, e.g. the following one:
```
<gis:kvie_jagdbezirke gml:id="kvie_jagdbezirke2604">
  <gis:NAME_JAGDBEZIRK>Vorst-Schmitzheide</gis:NAME_JAGDBEZIRK>
  <gis:NR_JAGDBEZIRK>083</gis:NR_JAGDBEZIRK>
  <gis:JAGDGENOSSENSCHAFT>Vorst-Schmitzheide</gis:JAGDGENOSSENSCHAFT>
```

Here is a request from QGIS:
https://geoservices.krzn.de/security-proxy/services/wfs_kvie_jagdbezirke?SERVICE=WFS&REQUEST=GetFeature&VERSION=2.0.0&TYPENAMES=gis:kvie_jagdbezirke&TYPENAME=gis:kvie_jagdbezirke&SRSNAME=urn:ogc:def:crs:EPSG::25832

If you save the response as GML ([wfs_kvie_jagdbezirke.zip](https://github.com/qgis/QGIS/files/5299716/wfs_kvie_jagdbezirke.zip)) and open it in QGIS, the features are not missing.

**Comment by rduivenvoorde** [comment]
@pathmapper I think this is because the WFS Dataprovider creates a spatialite database file to 'cache' the features (and be able to do paging etc). And I think(! and did some googling) that spatialite just does not do circular arcs. 
So you see them in your GML because then there is no spatialite cache.

Maybe @rouault could give an answer to the question *if* there is a workaround for this? Or if rewriting this cache (https://github.com/qgis/QGIS/blob/master/src/providers/wfs/qgsbackgroundcachedshareddata.cpp) to use gpkg (concludig from https://gdal.org/drivers/vector/gpkg.html that gdal can write circular stuff in it :-) ) 
For a small set (which can retrieve all features in one featureresponse) you can ideed use the Networklogger to capture the data via curl (there is a 'Copy as cURL' context menu) and save it as gml...

**Comment by rouault** [comment]
Fix in https://github.com/qgis/QGIS/pull/39113

The Spatialite WFS cache stores geometries as an opaque blob, so it can deal with circular ones.

**Comment by rduivenvoorde** [comment]
@rouault super cool! THAT is service :-) Building now to test it!

**Comment by rduivenvoorde** [comment]
Works!! 

![Screenshot-20201001135452-1033x413](https://user-images.githubusercontent.com/731673/94806082-b09ace80-03ed-11eb-942f-ad3518b94df2.png)

@pathmapper you have to test it either in a compiled version of yourself, or wait till this Pull Request ends up in one of the nightly (windows) builds. But: THANKS Even!

**Comment by pathmapper** [comment]
@rduivenvoorde @rouault thanks a lot for the fast response and the fix!

I've tried the fix with the windows build artifact from the PR (https://github.com/qgis/QGIS/suites/1272556715/artifacts/19625244) and can confirm that the bug reported here is fixed for this WFS.

**Comment by rduivenvoorde** [comment]
@pathmapper huh? That is clever? I did not know that!! Supercool to give average Windows users the possibility to test a PR!! Thanks for letting us know!
So you just downloaded the artifact from: https://github.com/qgis/QGIS/pull/39113/checks?check_run_id=1192973785 ?
Or can you describ how you came to the actual artifact?
I think we should put that in our documentation!

**Comment by pathmapper** [comment]
@rduivenvoorde yep, very cool feature. To show the download link for the artifact, in the PR just click on _Show all checks_ , then _Details_ of `Windows cross build with MXE` and finally on _Artifacts_ (top right corner). 

I think this works only if you are logged in to GitHub.

<img src="https://user-images.githubusercontent.com/20856381/94816796-9a483f00-03fc-11eb-8615-31050b1770f0.png" width="700">


<img src="https://user-images.githubusercontent.com/20856381/94816451-2017ba80-03fc-11eb-9426-9d5b9c468fef.png" width="700">


<img src="https://user-images.githubusercontent.com/20856381/94816551-463d5a80-03fc-11eb-9750-224a0a696470.png" width="700">
