### ISSUE TITLE
Failure with identifier sequence when adding feature

### ISSUE THREAD

**Issue by valtterilap** [qgis/QGIS#39093]
**Describe the bug**

When trying to add a new feature to a layer that uses generate identity always on the primary key, I get a failure when opening the attribute window when qgis tries to get the next value from the database. This is caused because qgis doesn't understand to use the right schema and tries to get the value without a search path.

**How to Reproduce**
Create a layer that uses GENERATED ALWAYS AS IDENTITY and try to add new feature

**QGIS and OS versions**

QGISin versio
3.14.16-Pi
QGIS-koodin versio
df27394552
Käännetty käyttäen Qt:tä
5.11.2
Suoritetaan käyttäen QT:tä
5.11.2
Käännetty käyttäen GDAL/OGR:ia
3.0.4
Suoritetaan käyttäen GDAL/OGR:ia
3.0.4
Käännetty käyttäen GEOS
3.8.1-CAPI-1.13.3
Suoritetaan käyttäen GEOSia
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL:n clientin versio
11.5
SpatiaLite-versio
4.3.0
QWT-versio
6.1.3
QScintilla2-versio
2.10.8
Käännetty käyttäen PROJ:ia
6.3.2
Suoritetaan käyttäen PROJ:ia
Rel. 6.3.2, May 1st, 2020
Käyttöjärjestelmän versio
Windows 10 (10.0)
Aktiiviset python-lisäosat
Kaava-O; 
plugin_reloader;
db_manager; 
MetaSearch; 
processing

**Additional context**

Here's my table
```
CREATE TABLE akaa_gk19.spatial_plan
(
    identifier INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    planning_object_identifier UUID NOT NULL DEFAULT uuid_generate_v4(),
    geom GEOMETRY(MultiPolygon, PROJECTSRID) NOT NULL,
    CONSTRAINT spatial_plan_pkey PRIMARY KEY (identifier)
)
```

And here's the error I get
```
2020-09-30T02:10:12     WARNING    Virheelinen kysely: SELECT nextval("spatial_plan_identifier_seq"::regclass) palautti 7 [ERROR: column "spatial_plan_identifier_seq" does not exist
             LINE 1: SELECT nextval("spatial_plan_identifier_seq"::regclass)
              ^
             ]
```

**Comment by elpaso** [comment]
@valtterilap I'm testing this issue right now with current QGIS master but I cannot reproduce the error. 

Would you be able to test current master build and check if the issue can be reproduced?

You can find a recent self-contained build for windows here: https://github.com/qgis/QGIS/suites/1265428175/artifacts/19438278

You download and unzip the package (twice) in a temporary directory and run qgis from the directory.

**Comment by valtterilap** [comment]
Didn't work with that. This time I got error:
```
2020-10-07T23:16:32     CRITICAL    Taso Kaava : PostGIS-virhe kun lisättiin kohteita: ERROR: cannot insert into column "identifier"
             DETAIL: Column "identifier" is an identity column defined as GENERATED ALWAYS.
             HINT: Use OVERRIDING SYSTEM VALUE to override.
             
```
I have the option checked to get defaults from the database.

**Comment by elpaso** [comment]
I rechecked and it works for me, there is even a test case in CI that passes. Feel free to re-open but make sure to add additional context to be able to reproduce on current master and 3.16.

**Comment by valttlapp** [comment]
Hi,
I was able to find the root cause of the bug. When the table is in other than public schema qgis cannot find the identity sequence because the search path doesn't include the layer's schema, and schema is included in the SELECT nextval query.
