### ISSUE TITLE
Double rendering with rule based symbology

### ISSUE THREAD

**Issue by roya0045** [qgis/QGIS#39098]
Sometimes rule based symbology can render the same feature twice.

I'm not sure if we want exclusive rendering or possibly multiple renders except for the ELSE clause.
[rule-based-prj.zip](https://github.com/qgis/QGIS/files/5305192/rule-based-prj.zip)

Tested on Win 10 QGIS 3.14.16 while trying to reproduce another bug(unable to edit some rule based feature geometry, quite inconsistent).

**Comment by nyalldawson** [comment]
This is by design. It's permitted, and left to the user to create suitable rules to either show one or many symbols depending on their needs.

**Comment by roya0045** [comment]
@nyalldawson Excellent, just wanted to make sure this was intentional!
