### ISSUE TITLE
QGIS keeps crashing when trying to show selected features in the attribute table

### ISSUE THREAD

**Issue by hamalpat** [qgis/QGIS#39102]
## User Feedback

QGIS keeps crashing when I have features (shapefile, polygons) selected and I try to show the selected features in the attribute table. Even with 10 or so features selected this occurs. Just bringing this to your attention, haven´t checked (yet) if similar problem and thus solution exists. 

## Report Details

**Crash ID**: [d5ef1418722eaa93bbd0a2c07776cf6cff4df2c3]('https://github.com/qgis/QGIS/search?q=d5ef1418722eaa93bbd0a2c07776cf6cff4df2c3&type=Issues')

**Stack Trace**
<pre>
QModelIndex::flags :
QAbstractItemView::currentChanged :
QMetaObject::activate :
QItemSelectionModel::`default constructor closure' :
QItemSelectionModel::qt_static_metacall :
QMetaObject::activate :
QAbstractItemModel::beginRemoveRows :
QSortFilterProxyModel::removeRows :
QSortFilterProxyModel::flags :
QSortFilterProxyModel::filterRole :
QSortFilterProxyModel::invalidateFilter :
QgsAttributeTableFilterModel::setFilterMode :
QgsDualView::setFilterMode :
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QMenu::exec :
QToolButton::paintEvent :
QToolButton::showMenu :
QToolButton::~QToolButton :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::mousePressEvent :
QToolButton::mousePressEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.1-A Coru�a
QGIS code revision: ef24c526da
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
>  3.10.1

@hamalpat too old, please upgrade to the latest point release. If the problem persist try with a new QGIS profile.

**Comment by hamalpat** [comment]
Okay I will update to the latest version, thanks!

**Comment by gioman** [comment]
Closing for lack of further feedback.
