### ISSUE TITLE
QGIS tries to save array fields to PostGIS incorrectly 

### ISSUE THREAD

**Issue by CoryAlbrecht** [qgis/QGIS#39106]
**Description**
When trying to update an existing feature to PostGIS that has a field of type UUID[] and that field is empty, it tries to use the SQL text `predecessor=E'{""}'`, but `""`, an empty string, is an illegal value for type UUID.

QGIS should be using `predecessor=E'{}'` to save an empty array of UUID values.

**Steps to recreate**
1. PostgreSQL database with PostGIS and UUID-OSSP extensions already installed
2. Import the attached dump
3. Create a QGIS project and open lawta.timeline_level1 as a layer
4. Toggle layer to editable
5. Edit a feature and change the date
6. Save the layer

**Extra info**
Console log when this occurs:
```
../../src/core/qgsmessagelog.cpp:29 : (logMessage) [247405ms] 2020-09-30T15:17:00 PostGIS[1] Erroneous query: UPDATE "lawta"."timeline_level1" SET "start_date"='1347-08-03',"info_url"=E'{""}',"flag_url"=E'{""}',"predecessors"=E'{""}',"successors"=E'{""}' WHERE "id"=11 AND "feature_uuid"::text='2b46575d-a1e5-44d7-a4ef-94bd07acbc63' returned 7 [ERROR:  invalid input syntax for type uuid: ""
LINE 1: ...fo_url"=E'{""}',"flag_url"=E'{""}',"predecessors"=E'{""}',"s...
                                                             ^
]
../../src/core/qgsvectordataprovider.cpp:740 : (pushError) [7ms] PostGIS error while changing attributes: ERROR:  invalid input syntax for type uuid: ""
LINE 1: ...fo_url"=E'{""}',"flag_url"=E'{""}',"predecessors"=E'{""}',"s...
                                                             ^

../../src/core/qgsmessagelog.cpp:29 : (logMessage) [10ms] 2020-09-30T15:17:00 Messages[2] Layer timeline_level1 : PostGIS error while changing attributes: ERROR:  invalid input syntax for type uuid: ""
LINE 1: ...fo_url"=E'{""}',"flag_url"=E'{""}',"predecessors"=E'{""}',"s...
                                                             ^

../../src/core/qgsmessagelog.cpp:29 : (logMessage) [7ms] 2020-09-30T15:17:00 [1] Commit errors:
  ERROR: 1 attribute value change(s) not applied.
  
  Provider errors:
      PostGIS error while changing attributes: ERROR:  invalid input syntax for type uuid: ""
    LINE 1: ...fo_url"=E'{""}',"flag_url"=E'{""}',"predecessors"=E'{""}',"s...
                                                                 ^
```

Dump of PostGIS 2.5 db schema created with `/usr/bin/pg_dump --file "/home/cory/Downloads/postgis-example-1.sql" --host "pg1.db.cory.albrecht.name" --port "5432" --username "cory" --no-password --verbose --format=p --schema "lawta" "Alternate History"` and then gzipped.
[postgis-example-1.sql.gz](https://github.com/qgis/QGIS/files/5307959/postgis-example-1.sql.gz)

QGIS version | 3.15.0-Master | QGIS code revision | ef7ecbf95b
-- | -- | -- | --
Compiled against Qt | 5.12.8 | Running against Qt | 5.12.8
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.4 (Ubuntu 12.4-0ubuntu0.20.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Ubuntu 20.04.1 LTS | This copy of QGIS writes debugging output.
Active python plugins | CanadianWebServices; qgis2web; quick_map_services; Qgis2threejs; qgiscloud; postgisQueryBuilder; QuickOSM; OSMDownloader; OnlineRoutingMapper; processing; db_manager; MetaSearch

**Comment by stev-0** [comment]
Can you close your last duplicate issue #29277, if you are going to open this new one (albeit easier to reproduce)

**Comment by stev-0** [comment]
Workaround is to make sure that the `uuid[]` fields use the List widget rather than the default Text Edit widget.

Not sure why it should default to Text Edit given the field is an array - that probably needs looking into.

**Comment by stev-0** [comment]
See [this comment ](https://github.com/qgis/QGIS/blob/869e148f6946579ec053e4cd72ffe4746fc97e90/src/gui/editorwidgets/core/qgseditorwidgetautoconf.cpp#L100)in the code to see why this doesn't work. Given this fact, seems like a bad idea to change anything, so looks like you will have to change the field manually to get this to work the way you want it to.

**Comment by CoryAlbrecht** [comment]
@stev-0 Ah, yes, thanks for finding that one. I was unable to. Also, I cannot close things here.

**Comment by stev-0** [comment]
@CoryAlbrecht - pretty sure anyone can close issues they started - the close button to the left of the comment button appears if you have admin rights or are the issue owner

**Comment by CoryAlbrecht** [comment]
@stev-0 I did not create 29277, the redmine importer did, thus I cannot close it.

**Comment by stev-0** [comment]
Oh right, I thought you were talking about this issue. You can close this one right?

**Comment by CoryAlbrecht** [comment]
@stev-0 I have the close button on this issue, yes, but I don't want to close it. I want it fixed.

**Comment by stev-0** [comment]
Hi @CoryAlbrecht - I've explained why this issue exists and the workaround - if you or anyone else can think of a way to deal with the issue you have whilst at the same time preventing any other unintended consequences caused by the interplay with QGIS field defaults and Postgres field defaults as per the [code comments](https://github.com/qgis/QGIS/blob/869e148f6946579ec053e4cd72ffe4746fc97e90/src/gui/editorwidgets/core/qgseditorwidgetautoconf.cpp#L100) referenced above then by all means suggest it.

It might also help if you quoted replies - some of your comments above are a bit ambiguous which particular comment you are replying to.
