### ISSUE TITLE
Default values do not change when running model from modeler

### ISSUE THREAD

**Issue by roya0045** [qgis/QGIS#39115]
Maybe there is a way to do this but I'm not sure how in 3.14.16.

Basically I would like a way to removed cached values or simply not save them for some fields.

Here is my current use case. I have a model using expressions, the expressions are exposed in the input in case I need to tweak them at run time but most of the time the changes that I make are in the default values of the model.

Now since I have run the model once, those values are never updated and the previous default values are still set as input since they were cached values.

Optimally I think that default values should never be cached and only when altered directly they should be cached, as this makes changing default value useless.

**Comment by roya0045** [comment]
Related to #34895 , @nyalldawson  I think I'm proposing an improvement but I'm not too sure how easy this is to do and if it doesn't go against the spirit of your PR (though I doubt that maintaining unwanted default values was intended).

**Comment by roya0045** [comment]
Or this could be considered a bug to be fixed...

**Comment by roya0045** [comment]
@gioman would you feel this is more fit to be a bug rather than a feature? I can reword things if needed.

**Comment by gioman** [comment]
I'm not really the right person to decide if is a feature request or a bug, let's wait the answer of a developer.

**Comment by roya0045** [comment]
I was just curious from a user perspective, I assume that most people would think its a bug that their default value never changes when executing their model..

**Comment by gioman** [comment]
> I assume that most people would think its a bug

yes, I feel the same.

**Comment by roya0045** [comment]
@gioman could you change the tag to Bug? Thanks

**Comment by roya0045** [comment]
@nyalldawson would simply removing elements force the default to appear when exporting the settings or would that simply break things?

**Comment by roya0045** [comment]
@nyalldawson I'm thinking about filtering the values from createProcessingParameters that are passed in stdesignerparametervalues here https://github.com/qgis/QGIS/blob/2e7bebcf201d095b74b47c7f56406dab640d27e5/python/plugins/processing/modeler/ModelerDialog.py#L146

though I'm not sure if there is any easy way to check for default values that were not changed.

Or maybe I should add a button to simply purged cached values as they stick around forever.

Any opinion on this?
