### ISSUE TITLE
Node tool snapping to invisible layers

### ISSUE THREAD

**Issue by m-kuhn** [qgis/QGIS#39118]
We have two polygon layers.
We set the advanced snapping configuration to snap to both layers. Then we set the snapping configuration to only the active layer.
Then we use the node tool with only the active layer.
When the second (not edited) layer is invisible, the node tool also tries to edit features from that layer (unexpected).
When the second (not edited) layer is visible, the node tool does not edit features from that layer (expected).

QGIS: 3.14.16, macOS

**Comment by uclaros** [comment]
Fixed in master by #39027

**Comment by Coakwell** [comment]
Has this been released as a fix yet

**Comment by uclaros** [comment]
At the moment it should only exist in the nightlies.
It should be released with 3.16 in a couple of weeks. Not sure if ltr 3.10
is affected.
