### ISSUE TITLE
Provider Settings for GRASS avoid to active OTB

### ISSUE THREAD

**Issue by hrralph** [qgis/QGIS#39112]
Bug description:
OTB cannot be activated on MacOS because GRASS reports a wrong path when trying to confirm the setting.

How to Reproduce the issue:
1. Open QGIS > Preferences > Processing
2. In the Providers tab, open the OTB section
3. Check activate and set the path to the OTB folder
4. Click OK

<img width="861" alt="Bildschirmfoto 2020-10-01 um 11 47 15" src="https://user-images.githubusercontent.com/29124423/94795434-9953e500-03dd-11eb-9d1f-2760be50f272.png">

Result:
The following error message appears and no OTB settings are confirmed (means OTB cannot be activated):
Wrong value for parameter "GRASS7 folder":
Specified path does not exist:
/Applications/QGIS 3.app/Contents/MacOS/grass7

<img width="418" alt="Bildschirmfoto 2020-10-01 um 12 00 22" src="https://user-images.githubusercontent.com/29124423/94795537-c0aab200-03dd-11eb-974e-5e24f5332123.png">

QGIS and OS versions:
QGIS 3.12 and 3.14
MacOS 10.14.6

Additional context:
I tried to check the GRASS path in the package and /Applications/QGIS 3.app/Contents/MacOS/grass7 does not exist in QGIS 3.12 and 3.14
One thing is that /Applications/QGIS 3.app is the wrong filename (it should be /Applications/QGIS3.12.app or /Applications/QGIS3.14.app) and the folder /grass7 does not exist in Contents/MacOS/

I also tried to remove the GRASS path in the settings but the same error occured.
Note: All GRASS tools work well in my installation.

**Comment by PeterPetrik** [comment]
Hi hrralph. We have reworked the packaging system from ground and the QGIS 3.16 will be released with the new way. I cannot replicate your issue with the current nightly build https://qgis.org/downloads/macos/nightly/qgis_nightly_master_20200930_122919.dmg . Can you please try to install it and let me know if it has the same problem? Thanks!

**Comment by hrralph** [comment]
Hi PeterPetrik!
Thank you for the quick response.
Well the GRASS folder issue seems to be gone now, but I still can't activate OTB because of another path issue.

This is what I set in the preferences of QGIS:
<img width="506" alt="Bildschirmfoto 2020-10-01 um 14 18 51" src="https://user-images.githubusercontent.com/29124423/94808412-674c7e00-03f1-11eb-8f46-8e7b3ea3f0b5.png">

This is the response from QGIS when I try to confirm the settings:
<img width="417" alt="Bildschirmfoto 2020-10-01 um 14 16 09" src="https://user-images.githubusercontent.com/29124423/94808496-83501f80-03f1-11eb-863f-7d5bb974800c.png">

The path to my OTB installation is correct and the file that QGIS misses (otbApplicationLauncherCommandLine) is in there - see the content of the Finder window:
<img width="699" alt="Bildschirmfoto 2020-10-01 um 14 18 26" src="https://user-images.githubusercontent.com/29124423/94808606-aaa6ec80-03f1-11eb-84af-365cf9861bf3.png">

I installed OTB following these instructions https://www.orfeo-toolbox.org/CookBook-6.4/Installation.html using

chmod +x OTB-7.1.0-Darwin64.run
./OTB-7.1.0-Darwin64.run

**Comment by PeterPetrik** [comment]
You have double "bin" in Path, folder should be without bin I assume in settings

**Comment by hrralph** [comment]
Thats a good point, I tried this first but forgot to report. When I use /Applications/OTB-7.1.0-Darwin64 I receive the following message:
<img width="420" alt="Bildschirmfoto 2020-10-01 um 15 19 56" src="https://user-images.githubusercontent.com/29124423/94814641-e6de4b00-03f9-11eb-92c8-aa16362e458c.png">

That's why I tried with /bin then...

**Comment by PeterPetrik** [comment]
I can run it OK.

![Screenshot 2020-10-01 at 15 47 48](https://user-images.githubusercontent.com/804608/94817644-851fe000-03fd-11eb-9922-f5f7fea56c3d.png)

**Comment by hrralph** [comment]
Great, it works now. I didn`t found that hint with /lib/otb/applications and was blended by the message with the otbApplicationLauncherCommandLine file.

Thank you!
