### ISSUE TITLE
'Control feature rendering order' does not work when using field from a Join

### ISSUE THREAD

**Issue by TLDuhamel** [qgis/QGIS#39127]
**Describe the bug**

Control Feature Rendering Order does not appear to work as expected, when using a field which is coming from a joined CSV layer.

**How to Reproduce**

QGIS project and resources, created on a clean new profile: [QGIS bug report - Control Feature Rendering Order with join field.zip](https://github.com/qgis/QGIS/files/5315124/QGIS.bug.report.-.Control.Feature.Rendering.Order.with.join.field.zip)

1. Go to the Properties -> Symbology tab for the layer `vector_layer (joined to CSV) - rendering order does not work`
2. Go to Layer Rendering, and tick 'Control feature rendering order', Click into the 'Define Order' view.
3. Select "join_layer_render_order" as the field. Select Descending order:
![image](https://user-images.githubusercontent.com/2009756/94869192-522f2800-04a1-11eb-85bd-1871972f315c.png)

At this stage, we would expect to see the smaller, yellow/green points to be rendered above the bigger, darker points. But the rendering order rule does not appear to be applied.

For comparison, see the other layer `vector_layer vector_layer (joined fields saved as permanent attributes) - rendering order does work`, which **has the fields saved permanently**, and the rendering rule is applied as expected:
![image](https://user-images.githubusercontent.com/2009756/94869853-abe42200-04a2-11eb-89fd-2ec51fb5be68.png)

**QGIS and OS versions**

QGIS version
3.10.7-A Coruña
QGIS code revision
7b4ca4c8d0
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
db_manager; 
MetaSearch; 
processing

**Comment by Pedro-Murteira** [comment]
@TLDuhamel I can't reproduce this issue on both QGIS 3.16,15 and 3.22.2. Rendering seems to work as expected on these later releases. Am I missing something here or is this in fact fixed?

**Comment by TLDuhamel** [comment]
Thanks for having a look @Pedro-Murteira 

I have now also tested the issue in QGIS 3.18.1 and I confirm it can not be reproduced in this version, so the issue appears to be fixed.
