### ISSUE TITLE
SpatiaLite 5.0.0 in QGIS

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#39120]
The stable version of `SpatiaLite` is 5.0.0 starting from 23/08/2020 it was announced here [0], in the official website [1] we find the sources.

QGIS currently has SpatiaLite 4.3 which is another 5 years old.

Here [2] all the news.

It would be nice to see SpatiaLite 5.0 in QGIS 3.16 Hannover

[0] https://www.gaia-gis.it/fossil/libspatialite/index
[1] https://groups.google.com/g/spatialite-users/c/K3gcP9_C1Zo/m/TTZKbn_zCAAJ
[2] https://www.gaia-gis.it/fossil/libspatialite/wiki?name=5.0.0-doc

**Comment by rmarzocchi84** [comment]
Nice idea. I like cooperation between GFOSS

**Comment by nyalldawson** [comment]
This is a packaging request, not qgis. You should file it on the osgeo4w tracker.

**Comment by pigreco** [comment]
https://trac.osgeo.org/osgeo4w/ticket/643#ticket
