### ISSUE TITLE
QGIS unexpectedly error

### ISSUE THREAD

**Issue by StudioLaFauci** [qgis/QGIS#39139]
Crash ID: a7ac41b4b88fc23dc7319d405431d5756e42b68a

Stack Trace

QgsMultiBandColorRenderer::block :
QgsBrightnessContrastFilter::block :
QgsHueSaturationFilter::block :
QgsRasterResampleFilter::block :
RtlAnsiStringToUnicodeString :
PyInit__multiarray_umath :

QGIS Info
QGIS Version: 3.12.3-Bucure?ti
QGIS code revision: 8234261527
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by gioman** [comment]
>  QGIS Version: 3.12.3-Bucure?ti

@StudioLaFauci too old, update to the latest 3.14. Re-try with a new QGIS profile. If the problem persist add ALL the requested info:



**Describe the bug**


**How to Reproduce**



**QGIS and OS versions**



**Additional context**

**Comment by gioman** [comment]
Closing for lack of feedback.
