### ISSUE TITLE
Layer reprojection works differently between profiles

### ISSUE THREAD

**Issue by tjukanovt** [qgis/QGIS#39134]
**Describe the bug**
Layer reprojection works differently between in my "normal" profile and a fresh profile where I tried to debug it. The reprojected layer (3857 --> 4326) disappears. It does seem to be in "the right place" as if I click zoom to layer in the temp layer, it does zoom to the same extent as the original layer. 

**How to Reproduce**
1. Add layer to project
2. Reproject to 4326 as a temp layer

Here's what happens in my "normal" profile...
![reproject_bug](https://user-images.githubusercontent.com/13899537/94914402-a2af8100-04b3-11eb-8ae2-f90c6b615ef1.gif)

...and here's what happens with a fresh profile:
![reproject_bug_new_profile](https://user-images.githubusercontent.com/13899537/94914428-acd17f80-04b3-11eb-8e19-add6f16677aa.gif)

So something different is happening there, but why?

**QGIS and OS versions**

Normal profile where bug appears:
```
QGIS version
3.14.16-Pi
QGIS code revision
df27394552
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
DigitransitGeocoder; 
GlobeBuilder; 
Hqgis; 
KuntagmlLoader; 
latlontools; 
mmqgis; 
OnlineRoutingMapper; 
ORStools; 
pgRoutingLayer; 
Qgis2threejs; 
qgis2web; 
qgis_resource_sharing; 
QNEAT3; 
QuickOSM; 
slyr_community; 
timemanager; 
db_manager; 
MetaSearch; 
processing
```

Fresh profile where bug doesn't appear:
```
QGIS version
3.14.16-Pi
QGIS code revision
df27394552
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
db_manager; 
MetaSearch; 
processing

```

**Additional context**

Could be related somehow to these unresolved mysterious reprojection issues: https://github.com/qgis/QGIS/issues/37809

Sample file: [ssd_gov_primary_schools.zip](https://github.com/qgis/QGIS/files/5317340/ssd_gov_primary_schools.zip)

**Comment by gioman** [comment]
> Here's what happens in my "normal" profile...

@tjukanovt can you try to "clean" your normal profile? i.e. removing manually 3rd party plugins folders,  then see if it makes any difference.

**Comment by uclaros** [comment]
...or try to install same plugins to new profile and see what happens!

**Comment by tjukanovt** [comment]
So I uninstalled all plugins from my profile. and it worked for a while. But now it's there again. The issue seems to be with layers and project mixed with EPSG:3857 and EPSG:4326 and temporary layers. 

But not sure anymore if this is about reprojection. Somehow the layers are not just drawn on canvas. As you can see from the screen capture, the data seems to be in the right place, if I click zoom to layer on the temporary layer, the canvas goes to the right place but nothing is shown.
![reproject_bug_v3](https://user-images.githubusercontent.com/13899537/95046981-e988bb00-06ed-11eb-8900-d7ac23e42248.gif)

Is there a way I could debug this myself and see what is happening?

**Comment by gioman** [comment]
> Is there a way I could debug this myself and see what is happening?

@tjukanovt can you provide a precise set of steps (and data) that can be used to replicate the issue?

**Comment by tjukanovt** [comment]
@gioman 👇🏼

1. Add the sample data GeoPackage (provided in the original post) to an empty project
2. Reproject it to to EPSG:4326 with _Reprojet layer_ processing tool and save the results to a temporary file (not on disk). So basically run the tool and don't change any parameters. 
3. If a new layer **does** appear on the canvas in the right place, remove the temporary layer from the project, minimize QGIS window and leave QGIS running for around five minutes and try again (yes it sounds weird, but this behavior makes me think that it could be some kind of memory/garbage collection issue?)
4. Try step 2 again and the layer does not appear anymore
5. Restart QGIS and things work like normal

**Comment by gioman** [comment]
> * Add the sample data GeoPackage (provided in the original post) to an empty project
> 
> * Reproject it to to EPSG:4326 with _Reprojet layer_ processing tool and save the results to a temporary file (not on disk). So basically run the tool and don't change any parameters.
> 
> * If a new layer **does** appear on the canvas in the right place, remove the temporary layer from the project, minimize QGIS window and leave QGIS running for around five minutes and try again (yes it sounds weird, but this behavior makes me think that it could be some kind of memory/garbage collection issue?)
> 
> * Try step 2 again and the layer does not appear anymore



@tjukanovt nope, cannot replicate.

**Comment by Saijin-Naib** [comment]
QGIS version | 3.14.16-Pi | QGIS code revision | df27394552
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | bettereditor; CalculateGeometry; MemoryLayerSaver; ORStools; slyr; SpreadsheetLayers; zoom_level; db_manager; MetaSearch; processing

Mmm, I can't repro either following the steps outlined below:  
1. Add the sample data GeoPackage (provided in the original post) to an empty project
2. Reproject it to to EPSG:4326 with Reprojet layer processing tool and save the results to a temporary file (not on disk). So basically run the tool and don't change any parameters.
3. If a new layer does appear on the canvas in the right place, remove the temporary layer from the project, minimize QGIS window and leave QGIS running for around five minutes and try again (yes it sounds weird, but this behavior makes me think that it could be some kind of memory/garbage collection issue?)
4. Try step 2 again and the layer does not appear anymore
5. Restart QGIS and things work like normal

**Comment by gioman** [comment]
> * Add the sample data GeoPackage (provided in the original post) to an empty project
> 
> * Reproject it to to EPSG:4326 with Reprojet layer processing tool and save the results to a temporary file (not on disk). So basically run the tool and don't change any parameters.
> 
> * If a new layer does appear on the canvas in the right place, remove the temporary layer from the project, minimize QGIS window and leave QGIS running for around five minutes and try again (yes it sounds weird, but this behavior makes me think that it could be some kind of memory/garbage collection issue?)
> 
> * Try step 2 again and the layer does not appear anymore
> 
> * Restart QGIS and things work like normal

@Saijin-Naib still can't replicate (tested on 3.14 and master on Windows).

**Comment by tjukanovt** [comment]
I will close this for now if nobody else is able to reproduce it.
