### ISSUE TITLE
qgis doesnt start after win 10  2004 update 

### ISSUE THREAD

**Issue by heike-0815** [qgis/QGIS#39132]
after update to win 10 2004 qgis doesn't start:
see pictures below

![fmeldung-qgis](https://user-images.githubusercontent.com/72252970/94909201-201ec580-04a3-11eb-947b-29377ff97b75.JPG)
![Pfad](https://user-images.githubusercontent.com/72252970/94909215-2614a680-04a3-11eb-91ad-d50b384e82c5.JPG)
![qgis-bin env](https://user-images.githubusercontent.com/72252970/94909228-29a82d80-04a3-11eb-97dc-7b2647143197.JPG)

in the env.file the path is correct and the file cqis_app.dll is present in the rigt place.

Any idea?

**Comment by gioman** [comment]
@heike-0815 please post questions on the users/developers mailing lists, if it turns to be really a QGIS bug then file a ticket here, thanks!
