### ISSUE TITLE
Trouble ordering elements in layout's composer

### ISSUE THREAD

**Issue by nicogodet** [qgis/QGIS#39136]
**Describe the bug**

Ordering elements in layout doesn't give expected results.

**How to Reproduce**

1. Create a new composer
2. Create a bunch of element (type does not matter)
3. Try to order element as desired

**Try to insert an element "insert" between elements 1 and 2**
![image](https://user-images.githubusercontent.com/39594821/94919298-91b33f80-04b4-11eb-9d66-984376e3cec8.png)

_Expected result :_
"insert" goes between 1 and 2
![image](https://user-images.githubusercontent.com/39594821/94919318-9972e400-04b4-11eb-8a0e-a10124c9c03f.png)

_Actual result :_
"insert" goes between 2 and 3
![image](https://user-images.githubusercontent.com/39594821/94919380-b0b1d180-04b4-11eb-98c5-2649fa9b28b1.png)

**Try to put "insert" on top : goes in second position**
![image](https://user-images.githubusercontent.com/39594821/94919502-df2fac80-04b4-11eb-988b-072eb11e8345.png)
![image](https://user-images.githubusercontent.com/39594821/94919515-e3f46080-04b4-11eb-9c65-3c0ea165b12b.png)

**Try to put "insert" at the bottom : just can't, "insert" doesn't move**
![image](https://user-images.githubusercontent.com/39594821/94919572-fc647b00-04b4-11eb-9f01-b45eb1214bb2.png)

**QGIS and OS versions**
Qgis 3.14.16-2 Windows

**Additional context**

None

**Comment by SebastienPeillet** [comment]
@nicogodet thanks for the well described bug ! I proposed a PR #39241 to fix it
