### ISSUE TITLE
Error al abrir el programa.

### ISSUE THREAD

**Issue by SabanSequen** [qgis/QGIS#39145]
Hace algunos días, me ha mostrado el error al abrir el programa, cosa que no me había pasado desde la última actualización.

Crash ID: 828110b4dc6e839b56b87cbe22ebe39763e5ff77

Stack Trace

PyErr_NoMemory :
PyObject_SetAttrId :
PyMethodDef_RawFastCallDict :
PyException_SetTraceback :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyObject_CallMethodIdObjArgs :
PyObject_CallMethodIdObjArgs :
PyUnicode_FindChar :
PyImport_ImportModuleLevelObject :
PyDict_GetItemString :
PyMethodDef_RawFastCallDict :
PyObject_FastCallDict :
PyObject_GC_New :
PyObject_CallFunction :
PyImport_Import :
PyImport_ImportModule :
PyInit_sip :
PyInit_sip :
PyUnicode_EncodeCharmap :
PyUnicode_EncodeCharmap :
PyUnicode_EncodeCharmap :
PyMethodDef_RawFastCallDict :
PyException_SetTraceback :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyObject_CallMethodIdObjArgs :
PyObject_CallMethodIdObjArgs :
PyUnicode_FindChar :
PyImport_ImportModuleLevelObject :
PyDict_GetItemString :
PyMethodDef_RawFastCallDict :
PyObject_FastCallDict :
PyObject_GC_New :
PyObject_CallFunction :
PyImport_Import :
PyImport_ImportModule :
PyInit_QtCore :
PyUnicode_EncodeCharmap :
PyUnicode_EncodeCharmap :
PyUnicode_EncodeCharmap :
PyMethodDef_RawFastCallDict :
PyException_SetTraceback :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyObject_CallMethodIdObjArgs :
PyObject_CallMethodIdObjArgs :
PyUnicode_FindChar :
PyImport_ImportModuleLevelObject :
PyType_Lookup :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyImport_Import :
PyImport_Import :
PyMethodDef_RawFastCallDict :
PyException_SetTraceback :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyObject_CallMethodIdObjArgs :
PyObject_CallMethodIdObjArgs :
PyUnicode_FindChar :
PyImport_ImportModuleLevelObject :
PyDict_GetItemString :
PyException_SetTraceback :
PyException_SetTraceback :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyFunction_FastCallDict :
PyObject_CallMethodIdObjArgs :
PyObject_CallMethodIdObjArgs :
PyImport_ImportModuleLevelObject :
PyType_Lookup :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyImport_Import :
PyImport_Import :
PyMethodDef_RawFastCallDict :
PyException_SetTraceback :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyObject_CallMethodIdObjArgs :
PyObject_CallMethodIdObjArgs :
PyUnicode_FindChar :
PyImport_ImportModuleLevelObject :
PyDict_GetItemString :
PyException_SetTraceback :
PyException_SetTraceback :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyObject_CallMethodIdObjArgs :
PyObject_CallMethodIdObjArgs :
PyUnicode_FindChar :
PyImport_ImportModuleLevelObject :
PyType_Lookup :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyEval_EvalCodeEx :
PyEval_EvalCode :
PyArena_Free :
PyRun_StringFlags :
instance :
instance :
instance :
instance :
QgisApp::loadPythonSupport :
QgisApp::QgisApp :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.14.0-Pi
QGIS code revision: 9f7028fd23
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
>  QGIS Version: 3.14.0-Pi

@SabanSequen 

1) update to the latest point release

2) try with a new QGIS profile

3) If problem persist please add ALL the requested info



**Describe the bug**


**How to Reproduce**



**QGIS and OS versions**



**Additional context**




4) file tickets in English, thanks!
