### ISSUE TITLE
GDAL Vector to Raster (gdal_rasterize) fail to produce ESRI ASCII as output

### ISSUE THREAD

**Issue by rmarzocchi84** [qgis/QGIS#39140]
The following command do not works using ESRI Ascii grid as output. Perhaps is a limit of gdal_rasterize, but I suggest ot limit output format list. 

![image](https://user-images.githubusercontent.com/4061154/94939419-693a3e00-04d2-11eb-9f0d-b3ba8b57d35a.png)

Here the syntax of gdal command

```
gdal_rasterize -l area_sorgente_proiettata -a rockdens -tr 5.0 5.0 -a_nodata 0.0 -te 457604.51146594144 5087357.733367669 457636.3696023076 5087381.37545834 -ot Float32 -of AAIGrid "C:\\Users\\assis\\Downloads\\R__Riunione\\R_ Riunione\\area_sorgente_proiettata.shp" "C:/Users/assis/Downloads/R__Riunione/R_ Riunione/prova2.asc"
```
Here the input file:
[area.zip](https://github.com/qgis/QGIS/files/5318781/area.zip)

OS: Windows 10

QGIS version
3.10.9-A Coruña
QGIS code revision
bf47e9d3e1
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
db_manager; 
MetaSearch; 
processing

**Comment by rmarzocchi84** [comment]
Sorry, I add the error message obtained also from OsGeo Shell: 

Output driver `AAIGrid' not recognised or does not support direct output file creation.
The following format drivers are configured and support direct output:
  -> `GeoRaster'
  -> `VRT'
  -> `GTiff'
  -> `NITF'
  -> `HFA'
  -> `ELAS'
  -> `MEM'
  -> `BMP'
  -> `PCIDSK'
  -> `PCRaster'
  -> `ILWIS'
  -> `SGI'
  -> `Leveller'
  -> `Terragen'
  -> `netCDF'
  -> `HDF4Image'
  -> `ISIS3'
  -> `ISIS2'
  -> `PDS4'
  -> `ERS'
  -> `RMF'
  -> `RST'
  -> `INGR'
  -> `GSBG'
  -> `GS7BG'
  -> `PDF'
  -> `MBTiles'
  -> `MRF'
  -> `PNM'
  -> `PAux'
  -> `MFF'
  -> `MFF2'
  -> `BT'
  -> `LAN'
  -> `IDA'
  -> `GTX'
  -> `NTv2'
  -> `CTable2'
  -> `KRO'
  -> `ROI_PAC'
  -> `RRASTER'
  -> `BYN'
  -> `NWT_GRD'
  -> `ADRG'
  -> `SAGA'
  -> `DB2ODBC'
  -> `GPKG'
  -> `NGW'
  -> `ENVI'
  -> `EHdr'
  -> `ISCE'

**Comment by gioman** [comment]
@rmarzocchi84 this should be changed to feature request (also editing the title) and ask to hide the formats that GDAL cannot create.

**Comment by rmarzocchi84** [comment]
> @rmarzocchi84 this should be changed to feature request (also editing the title) and ask to hide the formats that GDAL cannot create.

The solutions can be: 
- add a transalte command after the gdal_rasterize to export also the format not supported from gdal_rasterize 
- hide formats

The first solution is more complicated but is better for end user. 

IMHO the first solution is a feature request, the second one is a bug correction because actually QGIS do not works correctly

**Comment by alexbruy** [comment]
>  I suggest ot limit output format list.

We already show only creatable raster formats in the format selector.

It is not a QGIS bug. The same comman will not work from the command line. The problem here is that `gdal_rasterize` uses Create() not CreateCopy() to create output raster while AAIGrid driver only supports CreateCopy().
