### ISSUE TITLE
Simple merge of 4 LIDAR tif tiles changes elevations

### ISSUE THREAD

**Issue by Sutts99** [qgis/QGIS#39148]
QGIS 3.6.0-Noosa

A very simple operation - merging 4 unmodified National LIDAR Programme DTM tiles (tif format) into a single tif.

1. Load the 4 tif tiles into QGIS using Layer->Add Layer->Add Raster Layer

2. The four tiles display their minimum and maximum elevations (see attached).  The lowest and highest elevations are 43.42m and 106.69m.

![OfficialTileHeights](https://user-images.githubusercontent.com/72280665/94976053-96571280-050b-11eb-8e2c-b1ad25f50ae4.png)

3. The four tiles are merged using Raster->Miscellaneous->Merge.  All settings are left as default and "Save To File" is selected with the .tif format.

4. A single merged tif file is created (attached).  Looks good but if you take a look at the min/max elevation, the min elevation has reduced by several meters and the max has changed slightly too.  This doesn't fill me with confidence and must surely be a bug as in this game accuracy is key.

![MergedTileHeights](https://user-images.githubusercontent.com/72280665/94976061-9ce58a00-050b-11eb-8fe7-b83cf5d8c06e.png)

Or am I doing something wrong?

Thanks!

**Comment by Gustry** [comment]
> QGIS 3.6.0-Noosa

3.6.0 is too old, especially a `.0` which is not very stable. Please upgrade to a maintained version of QGIS. 3.14.X or 3.10.X

**Comment by Sutts99** [comment]
Will try that Gustry, thank you!

**Comment by gioman** [comment]
> Will try that Gustry, thank you!

@Sutts99 also you have to check the properties of the resulting raster, in the symbology tab, as QGIS by default uses an estimate strategy to compute min/max values,  you can can change that to "actual (slower)" and you'll get what you expect. Reopen if necessary.
