### ISSUE TITLE
Shape Items (Layout) and geometry generator

### ISSUE THREAD

**Issue by ludovico85** [qgis/QGIS#39159]
The shape items tool in the print layout window allows to customize the style of the selected shape also with the geometry generator. However, it seems that this function in actually disabled. 

1. Create a layout
2. Add a shape item such as a rectangle
3. Style the rectangle with the geometry generator. Trying to create the centroid of the rectangle with the expression: centroid($geometry)
4. Nothing happens

![Cattura](https://user-images.githubusercontent.com/24815399/94992948-cfd06200-058d-11eb-938c-0809c0685f32.JPG)

**Comment by gioman** [comment]
@ludovico85 

QGIS version?

Operating System?

**Comment by ludovico85** [comment]
QGIS 3.10.10 and 3.14.16
Windows 10

**Comment by pigreco** [comment]
I confirm, the geometry generator seems disabled even if I used a geometry in the form wkt: `geom_from_wkt ('Polygon ((0 5, 10 5, 10 0, 0 0, 0 5))')`

## Osgeo4W64 Win 10 QGIS 3.10, 3.14, master
