### ISSUE TITLE
Move Feature or Edit Vertex crashes while building index

### ISSUE THREAD

**Issue by johnfix** [qgis/QGIS#39158]
QGIS v3.18 crashes often when I use the "Move Feature(s)" and/or the "Vertex Tool" while it builds the temporary indexes. Sometimes the indexes are build successfully and I am able to use the tools, but often QGIS crashes.

When building the indexes is successful, it takes about 30 seconds to a minute + to complete. I try to do nothing during that period so it may complete.

My layers are a mix of shapefile, MS SQL layers, and XYZ Tiles.

Here is one of my crash reports (couldn't find on Git, maybe not available yet?):
## User Feedback

Was trying to use the Vertex Tool (current layer) on a line layer I was editing

## Report Details

**Crash ID**: [bf17277032991459cfb7437b3986ecff11adb6b8](https://github.com/qgis/QGIS/search?q=bf17277032991459cfb7437b3986ecff11adb6b8&type=Issues)

**Stack Trace**
<pre>
RtlEnterCriticalSection :
EnterStmtCS :
SQLGetDiagRecW :
providerMetadataFactory :
QgsAbstractFeatureIterator::nextFeature :
QgsVectorLayerFeatureIterator::fetchFeature :
QgsAbstractFeatureIterator::nextFeature :
QgsPointLocator::rebuildIndex :
QgsLayoutAtlas::sortFeatures :
QgsTask::start :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.14.15-Pi
QGIS code revision: d5114d2cfa
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

**Comment by gioman** [comment]
@johnfix Try with a new QGIS profile, no 3rd party plugins installed.

**Comment by uclaros** [comment]
Can you also check if it is reproducible without the MS SQL layers?

**Comment by johnfix** [comment]
@gioman Just to confirm, by a "new profile" do you mean creating a new file and disable all 3rd party plug-ins and then load the data layer? 

Or is there another process for a "new QGIS profile"? Thanks.

**Comment by gioman** [comment]
> Or is there another process for a "new QGIS profile"? Thanks.

@johnfix settings > user profiles > new profile

**Comment by johnfix** [comment]
I loaded only Shapefiles of buildings, roads, and address points for a county in Pennsylvania and an XYZ from Google. I can start editing and moving address points without problem. When I switch editing to building polygons, I can move some vertices, but other highlight and fail to move. I move the entire polygon and then I can move individual vertices. 

I did load the Microsoft Geopackage with buildings (entire US) and when I tried to edit....had a hard crash with no QGIS crash dialog.

My "normal" editing environment includes street level data from MS SQL will millions of records for each layer. I have layers like address points, buildings, roads, railroads, municipal boundaries, water lines and water polygons.

Indexing can take 1/2 minute to a minute when it works.

Antidotally, it seems to fail more often when I am zoomed in very close, perhaps 1:500 scale.

**Comment by johnfix** [comment]
@gioman  and @uclaros I have done several test in several different scenarios. Here is what I think it causing the problem...if I have snapping enabled when I enabling editing for a layer (address point layer with millions of records) QGIS crashes.

If I disable snapping before enabling editing for the layer, QGIS does not crash and functions as expected. I can enable editing once the temporary indexes have been built and it does not crash.

I did create a new profile with no third party plug-ins enabled. I added many of the MS SQL layers in the main project file. I started editing without snapping and it worked as expected. I enabled snapping and started editing, the index occurred and everything worked as expected.

So, I'm not sure how snapping and the profile/plug-ins are interacting to create a problem. 

Any other ideas to test?

Thanks for your help.

**Comment by uclaros** [comment]
I would export the mssql features to a geopackage and try to replicate and see if it is provider related.

**Comment by johnfix** [comment]
@gioman and @uclaros I have continued to test. I can use the vertex tool without crashing if I disable snapping first. I can enable snapping AFTER I select the vertex tool and it has completed the indexing.

I will try again with snapping enable, but will keep my mouse OFF the map while the indexes are building. Perhaps it is trying to find snapping candidates while the indexes are being built and this causes a conflict?
