### ISSUE TITLE
Zoom level in maps url not working with new "Add a goto locator" feature

### ISSUE THREAD

**Issue by klakar** [qgis/QGIS#39167]
**Describe the bug**
When copying a Google maps url it may have decimals in the "z" value.
This will generate exaggerated scale in QGIS.
Removing the decimals will fix the issue.

**How to Reproduce**
Add Google maps url to the locator of the type:

https://www.google.se/maps/@57.6630623,14.9742081,15z

The url above will work fine (scale 1:22569), but including decimals in the z-value will generate wrong scale.

https://www.google.se/maps/@57.665305,14.9753512,15.25z

The url above will generate the scale 1:739571904

**QGIS and OS versions**

QGIS version | 3.15.0-Master | QGIS code revision | ef7ecbf95b
-- | -- | -- | --
Compiled against Qt | 5.12.8 | Running against Qt | 5.12.8
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.4 (Ubuntu 12.4-0ubuntu0.20.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Linux Mint 20 | This copy of QGIS writes debugging output.
Active python plugins | LmOpenData; DataPlotly; latlontools; layout_loader; mmqgis; Qgis2threejs; qfieldsync; Discovery; postgis_geoprocessing; MetaSearch; processing; db_manager

**Additional context**

**Comment by ismailsunni** [comment]
It seems it's already fixed in master and 3.22

**Comment by klakar** [comment]
This problem seems to be fixed in 3.24 too.
