### ISSUE TITLE
Feedback: QgsTextRenderer for drawing map grid text in layouts not HTML compatible

### ISSUE THREAD

**Issue by klakar** [qgis/QGIS#39160]
**Describe the bug**
Not really a bug, more like feedback on a new feature in Master.

Using QgsTextRenderer for grid labels in layout is great, but the option to render the text as html has limited value, since the text seems to be "placed" before it is rendered. 

This means that if you have html tags in your label string they will occupy space creating an open distance from the actual rendered text to the location where it should be placed.

Just as an example, using the following expression as a grid label source:
`'<span style="color:blue;">' || @grid_number || '</span><span style="color:red;">Degree</span>'`

Will show up as:
![Skärmbild från 2020-10-03 16-04-51](https://user-images.githubusercontent.com/6375959/94993575-3fe0e700-0592-11eb-8131-768143eac9af.png)

**How to Reproduce**

See above.

**QGIS and OS versions**

QGIS version | 3.15.0-Master | QGIS code revision | ef7ecbf95b
-- | -- | -- | --
Compiled against Qt | 5.12.8 | Running against Qt | 5.12.8
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.4 (Ubuntu 12.4-0ubuntu0.20.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Linux Mint 20 | This copy of QGIS writes debugging output.
Active python plugins | LmOpenData; DataPlotly; latlontools; layout_loader; mmqgis; Qgis2threejs; qfieldsync; Discovery; postgis_geoprocessing; MetaSearch; processing; db_manager

**Additional context**

**Comment by nyalldawson** [comment]
@olivierdalang can you investigate this please? It was working correctly before your recent grid annotations work.

**Comment by olivierdalang** [comment]
Ok, it seems I had missed some lines when merging my changes, sorry for that !

Just opened a PR, I hope I won't have to battle against QgsRenderChecker this time :-)

Thanks for the very clear report @klakar
