### ISSUE TITLE
qgis snapping feature is flawed if  "Snapping to Common Angles" is ON

### ISSUE THREAD

**Issue by faridcher** [qgis/QGIS#39166]
**Describe the bug**

The snapping is on for a layer and the snapping markers (pink square marker for vertex and pink hourglass marker for segment) are shown when digitizing. However, dangles get created which means the snapping does not function right. Increasing the Tolerance in "Advanced Config Dialog" does not help

**How to Reproduce**
create a simple linear layer in a Geopackage and try to digitize it. Try to snap to endpoints, vertices, and segments. At the same time with "Topology Checker" tool, define a rule "must not have dangles" on the same layer and check the topology of the digitized lines.

![image](https://user-images.githubusercontent.com/9982519/95007817-ce03ae80-0620-11eb-9c89-ca1169e9b94d.png)

![image](https://user-images.githubusercontent.com/9982519/95007824-e4aa0580-0620-11eb-982f-233e009d0cba.png)

**QGIS and OS versions**
GIS version | 3.10.9-A Coruña on Debian unstable (sid)

**Additional context**

**Comment by uclaros** [comment]
Snapping most probably works fine, I've snapped a few gazillion vertices myself. It's the Topology checker's definition of dangle that is flawed, as it seems to report a dangle when a start/end point is snapped on a vertex that is not a start/end point.
The *Geometry Checker* core plugin works better and does not falsely report dangles.

**Comment by gioman** [comment]
> Snapping most probably works fine, I've snapped a few gazillion vertices myself. It's the Topology checker's definition of dangle that is flawed, as it seems to report a dangle when a start/end point is snapped on a vertex that is not a start/end point.
> The _Geometry Checker_ core plugin works better and does not falsely report dangles.

I also think is the topology checker, not the snapping. At some point we should really merge the topology and geometry checker, the current situation is really confusing for users.

**Comment by faridcher** [comment]
@uclaros Both have problems. You mentioned the Topology Checker problem. In order to ensure the snapping flaw, I will provide more examples shortly.

**Comment by uclaros** [comment]
> Both have problems.

I totally agree! Repairing and maintaining topology is a weak spot of qgis IMHO.

To ensure that snapping worked, you can enable topological editing and try to move a node with the vertex tool. If both vertices move together then snapping worked, and I'm pretty sure that will be the case!

**Comment by faridcher** [comment]
thanks. In addition to zooming maximally, that's how I have been checking connectivity.

**Comment by uclaros** [comment]
If you don't find any issues with snapping and the problem is indeed on the Topology Checker side, could you please adjust the title accordingly?

**Comment by faridcher** [comment]
@uclaros The snapping has problem indeed. I will provide more info on when exactly it does not work alright. please be patient. thanks

**Comment by faridcher** [comment]
@uclaros 

I found the root of the bug. It happens with "Snapping to Common Angles" is on (e.g. 90, 180, ..) in "Advanced Digitizing" panel. 
try these steps to replicate: digitize a rectangle with 4 features; one feature per side. The last side won't snap even though the pink rectangle marker of vertex snapping is shown. If "Snapping to Common Angles" is off, it works fine.
This bug has killed me in the past 2-3 months and I gladly found its source. Hope someone provide a fix soon.

thanks

**Comment by uclaros** [comment]
That's what I thought when I first saw your screenshot! I've been bitten by it too and disable the feature on first occurence.
This is not a bug, since *Advanced Digitizing* has greater precedence than normal snapping. And it should have greater precedence to be able to do cool stuff like d,a,x,y locking etc.
However, having *Snap to common angles* set to right angles by default **is** a bug. *Snap to common angles* should be *opt-in* not *opt-out*!

**Comment by faridcher** [comment]
The vertex/segment snapping marker is misleading. Once it is shown, the user expect the snapping and I think it should take precedence. This is how AutoCAD works as well. As soon as you see the snapping marker, it guarantees the segment/vertex snapping even though angular snapping is on. Any if the precedence won't change in future, please provide a keybinding to toggle Angular Snapping. It should also be document either in the QGIS documentation or better right in the buttons tooltips that Angular Snapping has higher precedence over Vertex/Segment snapping.
