### ISSUE TITLE
Python Console colors not changable via settings

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS#39173]
Changing the colors of elements in the Scintilla panes (like Python console and editor) are not reflected in the actual console and editor.
Checked in current master on Linux and Windows build nightly:
- open QGIS
- open the python console
- open the settings (via the little tool button in the Python Console)
- change an obvious color, like 'default' or 'background' to pure red for example
- close the settings
- the colors are not reflected in current console and editor

I double checked (by building/checking) the pull request in which this color stuff was merged into one base class:
https://github.com/qgis/QGIS/pull/37602

But there the colors were still changing immediately...

@slarosa can you confirm this on your machine? I think(!) this is since moving the settings to the main settings?

**Comment by slarosa** [comment]
Yes, I confirm, this is related to @nyalldawson's  work in progress. Introduced in #39157 and I think will be fixed in #39165 :-)

**Comment by rduivenvoorde** [comment]
Ah :-)
Apparently I'm always a little behind ;-)
Close this one then?

**Comment by slarosa** [comment]
better to keep it open for the moment.

**Comment by nyalldawson** [comment]
Fixed in master
