### ISSUE TITLE
"explode lines" processing tool removes features if more than one feature are selected when "Automatic Creation of Transaction Group" is enabled

### ISSUE THREAD

**Issue by faridcher** [qgis/QGIS#39177]
**Describe the bug**
"Explode Lines" tool successfully explodes a single Linestring feature. But if more than one features are selected, it deletes some of them.

**How to Reproduce**
create a linear layer in a Geopackage. Digitize at least two Linestring (with more than one segment) feature. Select them and run "explode lines" processing algorithm on the selected features. 
![image](https://user-images.githubusercontent.com/9982519/95031064-ae23c780-06c0-11eb-837e-b3f4ea42bee0.png)

**QGIS and OS versions**
Qgis 3.10.9 on Debian unstable

**Additional context**

**Comment by gioman** [comment]
@faridcher cannot confirm on QGIS 3.10.10, Ubuntu 20.04.

**Comment by faridcher** [comment]
upgraded to 3.10.10 and the problem persists. Ubuntu is Debian derivative and I don't think it is OS specific. I can record a video if that helps.

thanks

**Comment by gioman** [comment]
> upgraded to 3.10.10 and the problem persists. Ubuntu is Debian derivative and I don't think it is OS specific. I can record a video if that helps.

@faridcher try with a new QGIS profile.

**Comment by faridcher** [comment]
A new profile did not help. However, the problem relates to the qgis project file and it occurs when "Automatic Creation of Transaction Group" is enabled in the "Project Properties > Data Sources". Un-checking that option solves it.

**Comment by elpaso** [comment]
This may be fixed by https://github.com/qgis/QGIS/pull/39257 with GDAL >= 2.3.0.

**Comment by Pedro-Murteira** [comment]
Couldn't reproduce this issue on QGIS 3.22.4 and 3.24.0. @faridcher Did you come across this issue in more recent versions?

**Comment by faridcher** [comment]
Still present in QGIS 3.22.4. @Pedro-Murteira did you enable "transaction groups" in "project properties" dialog before testing?

**Comment by Pedro-Murteira** [comment]
@faridcher I didn't, but I've tested just now with "transaction groups" checked, and I can also confirm.

**Comment by alexbruy** [comment]
Not reproducible with the latest master (f344919474). With and without "Automatic Transactions Group" nothing is removed.

**Comment by faridcher** [comment]
@alexbruy thank you for testing. I am unable to test with master but is still present in 3.28.11. Did you select more than one feature?

**Comment by alexbruy** [comment]
I tested using the same steps as in the issue description, with selected features.

**Comment by faridcher** [comment]
@alexbruy please state your exact version instead of "master". I and many others are unable to test with master. thanks

**Comment by alexbruy** [comment]
@faridcher right now I'm on a2643b801c9b3a765ce5e0fabd235762f25aa7fe
