### ISSUE TITLE
make a field with "Value Map" widget editable and searchable in "Edit Attribute" dialog

### ISSUE THREAD

**Issue by faridcher** [qgis/QGIS#39179]
**Feature description.**
A field with "value map" is only selectable through a combo box. When the number of items increases (e.g. 20+), finding a particular item is cumbersome because it is not searchable. Furthermore, it would be great to enable the user to enter arbitrary text into a "Value Map" field or simply clear the text value to set the field to NULL. Now, I select a feature and use "field calculator" to enter arbitrary value/NULL into a "value map" field as a workaround.

**To reproduce** 

create a layer in a Geopackage with a field of type string. Then select the "Attribute Form" tab in the "Layer Properties Dialog". Select the field and set its "Widget Type" to "Value Map" and add a few items. Then, digitize a few features , select them and try to edit the attribute with "Edit > Modify Attributes of Selected Features" dialog. 

**Additional context**
In this example, lab layer has label field with "value map" widget type with 528 items. 

![image](https://user-images.githubusercontent.com/9982519/95039114-c3a6ea80-06dc-11eb-9bac-3a1fb7a751d7.png)

**Comment by uclaros** [comment]
> A field with "value map" is only selectable through a combo box. When the number of items increases (e.g. 20+), finding a particular item is cumbersome because it is not searchable.

The combobox is searchable. You can start typing when it has focus and the matching entry is selected as you type. You don't have visual feedback of what you type though, just like when browsing files on the windows explorer.



> Furthermore, it would be great to enable the user to enter arbitrary text into a "Value Map" field or simply clear the text value to set the field to NULL.

You can use the *Add "NULL" value* button when defining your mappings so that you can select null from the combobox.
If you want arbitrary values though, then the value map is not the right widget for you. you can try the *Unique Values* widget with *editable* checked.

**Comment by faridcher** [comment]
@uclaros thank you for your response. I had already tested Unique Values. I want the behavior of Unique Values widget but with predefined values as in Value Map. Now Unique Values only search through the values already set in a field. 

Searching the Value Map is by the initial letter which is slow when the fields has many items that start with a letter (e.g. in my case). 

Thanks for the pointer to "Add Null value button" which I missed.

**Comment by uclaros** [comment]
You're welcome!
Value map, as its name implies, is a map of key-value pairs. If it was dynamic, like the unique values widget, then you would also need a way to provide a value for the key you typed, making it more complicated.
For your use case, I would go with the unique values widget, then I would add a geometryless feature for each predefined value as a populated index. Maybe we could implement a *unique values with predefined index* mode to avoid adding the extra features.

Also, searching the value map is not only by first letter, you can continue typing and entry changes accordingly.

**Comment by faridcher** [comment]
@uclaros geometryless feature workaround seems nasty; the statistical report on the layer would be wrong; it messes up with other analyses like join queries.

"Unique Values" with predefined index mode is the way to go. Can this be implemented somehow?
