### ISSUE TITLE
crash while editing data

### ISSUE THREAD

**Issue by Meibes** [qgis/QGIS#39187]
## User Feedback

unfortunatly I can't say much about this crash because it happend to a colleague some time ago, she just kept the report

## Report Details

**Crash ID**: [acd228819760d9d9c6a13879e96e573c47d1d64e](https://github.com/qgis/QGIS/search?q=acd228819760d9d9c6a13879e96e573c47d1d64e&type=Issues)

**Stack Trace**

<pre>

memcpy_repmovs memcpy.asm:114

QgsVectorLayerFeatureIterator::updateChangedAttributes qgsvectorlayerfeatureiterator.cpp:1146

QgsVectorLayerFeatureIterator::fetchFeature qgsvectorlayerfeatureiterator.cpp:428

QgsAbstractFeatureIterator::nextFeature qgsfeatureiterator.cpp:63

QgsFeatureSource::allFeatureIds qgsfeaturesource.cpp:124

QgsVectorLayer::selectAll qgsvectorlayer.cpp:559

QMetaObject::activate :

QAction::activate :

QAbstractButton::click :

QAbstractButton::mouseReleaseEvent :

QToolButton::mouseReleaseEvent :

QWidget::event :

QApplicationPrivate::notify_helper :

QApplication::notify :

QgsApplication::notify qgsapplication.cpp:418

QCoreApplication::notifyInternal2 :

QApplicationPrivate::sendMouseEvent :

QSizePolicy::QSizePolicy :

QSizePolicy::QSizePolicy :

QApplicationPrivate::notify_helper :

QApplication::notify :

QgsApplication::notify qgsapplication.cpp:418

QCoreApplication::notifyInternal2 :

QGuiApplicationPrivate::processMouseEvent :

QWindowSystemInterface::sendWindowSystemEvents :

QEventDispatcherWin32::processEvents :

UserCallWinProcCheckWow :

DispatchMessageWorker :

QEventDispatcherWin32::processEvents :

qt_plugin_query_metadata :

QEventLoop::exec :

QCoreApplication::exec :

main main.cpp:1606

BaseThreadInitThunk :

RtlUserThreadStart :
</pre>

**QGIS Info**

QGIS Version: 3.10.9-A Coru�a

QGIS code revision: bf47e9d3e1

Compiled against Qt: 5.11.2

Running against Qt: 5.11.2

Compiled against GDAL: 3.0.4

Running against GDAL: 3.0.4

**System Info**

CPU Type: x86_64

Kernel Type: winnt

Kernel Version: 10.0.18362

**Comment by gioman** [comment]
> unfortunatly I can't say much about this crash because it happend to a colleague some time ago, she just kept the report

@Meibes it is replicable? if yes, can she try with a new QGIS profile?

**Comment by gioman** [comment]
Closing for lack of feedback.
