### ISSUE TITLE
Crash when exporting to image too large

### ISSUE THREAD

**Issue by thommo17** [qgis/QGIS#39189]
**Describe the bug**

When trying to export to image if you have the pixel dimensions over ~25,000 in the X or Y axis the program will crash.

**How to Reproduce**

Simply try to export any map to image over 25,000 pixels.

**QGIS and OS versions**

QGIS 3.12.3

Windows 10 64bit

**Additional context**

This issue has been happening for quite while for me and I have just used Photoshop as a work around to stitch images together but it would be great to be able to do higher resolution images for printing maps. I have one map I print on B0 size paper at 600DPI.

I wouldn't mind if I could just set the program to work over a few hours to do what I wanted as long as it didn't crash and eventually gave me a good image at the end.

## User Feedback

Basically trying to export to image anything over around 25,000 pixels in the X or Y axis will give me this error

## Report Details

**Crash ID**: [1d5ed672dc1b64fc24118b59e560969ad8cbd8bb](https://github.com/qgis/QGIS/search?q=1d5ed672dc1b64fc24118b59e560969ad8cbd8bb&type=Issues)

**Stack Trace**
<pre>
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QRasterPaintEngine::fillRect :
QRasterPaintEngine::drawImage :
QgsRasterDrawer::drawImage :
QgsRasterDrawer::draw :
QgsRasterLayerRenderer::render :
QgsMapRendererCustomPainterJob::doRender :
QgsMapRendererCustomPainterJob::renderPrepared :
QgsMapRendererTask::run :
QgsTask::start :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.12.3-Bucure?ti
QGIS code revision: 8234261527
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by nyalldawson** [comment]
This is an upstream Qt bug -- it will be fixed when the QGIS windows package updates the included Qt version (hopefully for 3.16)
