### ISSUE TITLE
Python console/editor: Line numbers appear double in editor and console?

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS#39181]
After the recent beautifull work to move all 'editor' color settings to the main settings, currently in the python console and editor there is something going wrong with the line numbers in the QScintilla panels.

These are the panel with a clean start

![Screenshot-20201005082942-888x367](https://user-images.githubusercontent.com/731673/95046698-f81ea480-06e4-11eb-8b06-3741947e79a4.png)

This when you move to a dark theme:

![Screenshot-20201005083105-885x362](https://user-images.githubusercontent.com/731673/95046780-24d2bc00-06e5-11eb-8f8e-09671e6be10e.png)

Another observation is that parts of the editor are not 'listening' to the theme (or overriding stuff).
Could be my fault, when creating the base class, I know there is some fiddling with colors and columns to be able to copy the console text without the '>>>' cursor etc  @nirvn @slarosa 

https://github.com/qgis/QGIS/blob/master/python/console/console_base.py ?

Note that in the preview panel in the main settings all looks good, so it is definitly something console specific...

QGIS version | 3.15.0-Master | QGIS code revision | f5cd52f81b
-- | -- | -- | --
Compiled against Qt | 5.14.2 | Running against Qt | 5.14.2
Compiled against GDAL/OGR | 3.1.3 | Running against GDAL/OGR | 3.1.3
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.33.0 | Running against SQLite | 3.33.0
PostgreSQL Client Version | 13.0 (Debian 13.0-2) | SpatiaLite Version | 5.0.0
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.5
Compiled against PROJ | 7.1.1 | Running against PROJ | Rel. 7.1.1, September 1st, 2020
OS Version | Debian GNU/Linux bullseye/sid | This copy of QGIS writes debugging output.
Active python plugins | MetaSearch; processing; db_manager

**Comment by nyalldawson** [comment]
My most recent PR (#39180) fixes this
