### ISSUE TITLE
Thickness of the dotted line 

### ISSUE THREAD

**Issue by FilatovAV** [qgis/QGIS#39201]
**The thickness of the dotted line changes the distance between the strokes. If the thickness is set manually and not by a field from the database, the line display does not change. (The field in the database is checked.)**

**QGIS Version - 3.14.16-P**
![1-0](https://user-images.githubusercontent.com/38399107/95177882-6a67b580-07c7-11eb-903a-01133f93d493.png)
![1-1](https://user-images.githubusercontent.com/38399107/95177887-6b004c00-07c7-11eb-9312-4f0fd06c21d8.png)
![1-2](https://user-images.githubusercontent.com/38399107/95177889-6b004c00-07c7-11eb-92d5-1b26a187daa8.png)
![1-3](https://user-images.githubusercontent.com/38399107/95177890-6b004c00-07c7-11eb-8683-9273798c090f.png)
![1-4](https://user-images.githubusercontent.com/38399107/95177891-6b98e280-07c7-11eb-9951-7e40501d3ae4.png)
![1-5](https://user-images.githubusercontent.com/38399107/95177895-6b98e280-07c7-11eb-969c-6cc6526023b0.png)

**Comment by andreasneumann** [comment]
This actually not a bug - but you need to set the "Cap Style" to Flat to avoid that behavior:

![image](https://user-images.githubusercontent.com/884476/95181298-646fd580-07c3-11eb-9c1d-57eae8009c6c.png)

That setting also influences the individual strokes in a dashed line, not only the line ends. Setting it to flat avoids that the gaps are getting smaller

**Comment by andreasneumann** [comment]
hm - maybe there is a different issue, then what I mentioned above.

You say that it works fine, unless you set it from a field or expression?

**Comment by FilatovAV** [comment]
Yes, if I set the thickness with my hands, everything is OK

**Comment by nyalldawson** [comment]
Can you please test with a nightly release of 3.16? I believe this is already fixed.

**Comment by FilatovAV** [comment]
> Can you please test with a nightly release of 3.16? I believe this is already fixed.

Please tell me where can I download the nightly build installer?

**Comment by andreasneumann** [comment]
@FilatovAV - what OS are you on?

For Windows there are weekly builds at https://qgis.org/downloads/weekly/ - and we recently discovered that the Travis CI builds can also be used for testing - they are linked at Github - see https://github.com/qgis/QGIS/issues/39081#issuecomment-702148377

Hope this helps.

**Comment by FilatovAV** [comment]
@andreasneumann 
I have Windows, thank you I will try.

**Comment by FilatovAV** [comment]
the program works the same as in the previous version. when you change the line thickness, the stroke length also changes. At the same time, I tried different "style caps"
![2-1](https://user-images.githubusercontent.com/38399107/95303125-7e74eb00-088b-11eb-8766-53246ed88733.png)
