### ISSUE TITLE
SVG symbols do not scale with map magnifier

### ISSUE THREAD

**Issue by 3nids** [qgis/QGIS#39208]
100%:
![Screenshot 2020-10-06 at 11 54 57](https://user-images.githubusercontent.com/127259/95186875-c4b64580-07ca-11eb-9df0-fe50586ed639.png)

800%:
![image](https://user-images.githubusercontent.com/127259/95186928-d3046180-07ca-11eb-8ce8-2fd4c6772482.png)

**Comment by nirvn** [comment]
@3nids , are you sure the SVG marker size unit type isn't set to pixel?

**Comment by nirvn** [comment]
@3nids , are you sure the SVG marker size unit type isn't set to pixel?

**Comment by 3nids** [comment]
yes it is....thanks a lot.
Although, I would still expect to see it scaled no?

**Comment by roya0045** [comment]
Pixels are relative to your screen, not the map.
