### ISSUE TITLE
Issue with postgis layer and relation widget

### ISSUE THREAD

**Issue by Vstorm911** [qgis/QGIS#39210]
Hi everybody.

I'm having an issue when using postgis databases to make gis diagrams. The issue is that when i configure some relations on my db, and then applying this relation in qgis, sometimes the relation widget shows only "NULL". This issue is happening somewhat randomly. The issue is depicted in the following image:

![image](https://user-images.githubusercontent.com/72465028/95240791-4ade8600-07e3-11eb-82d1-69b24af5ad64.png)

Now, if i edit the feature i can select another item from the related table, wich shows the correct information:

![image](https://user-images.githubusercontent.com/72465028/95240946-7c575180-07e3-11eb-9c91-27d07e7b7e29.png)

Then i can choose the original item, and it shows the correct data:

![image](https://user-images.githubusercontent.com/72465028/95241111-b45e9480-07e3-11eb-8551-fcbf5fa9448d.png)

But when i finalize the edit and save the data, it returns to showing NULL:

![image](https://user-images.githubusercontent.com/72465028/95241254-df48e880-07e3-11eb-8af3-92c5cd6aa3db.png)

I haven't been able to find any info of this.

Thanks in advance for your support.

Bast Regards!

**Comment by gioman** [comment]
@Vstorm911 QGIS version? Operating system?

**Comment by Vstorm911** [comment]
Oh sorry, i'm using version 3.10.6 in Windows 10x64

**Comment by gioman** [comment]
> 3.10.6

@Vstorm911 too old, update to the latest point release.

**Comment by Vstorm911** [comment]
i see, i'll try and come back with the results.

Thanks!

**Comment by Vstorm911** [comment]
I confirm that the issue is solved using the version 3.14. Thanks for your answers.
