### ISSUE TITLE
Windows 8.1 - QGis desktop software closing with issue

### ISSUE THREAD

**Issue by sanku2009** [qgis/QGIS#39215]
**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by sanku2009** [comment]
When I tried to add a layer from Layer tab and trying to select file from local my folder it showing error and stopped the application. Attached the screen shot.
![QGIS-Issue](https://user-images.githubusercontent.com/49359440/95276514-5f3d7580-0819-11eb-8af3-938841f49ce3.JPG)

**Comment by gioman** [comment]
@sanku2009 please try with a new QGIS profile. Also please say what QGIS version are you using.

**Comment by roya0045** [comment]
It just seems to be the windows explorer bug. This is a duplicate if that's the case.

**Comment by gioman** [comment]
Closing for lack of feedback.
