### ISSUE TITLE
Can't get info on WFS feature in MacOS nightly build 

### ISSUE THREAD

**Issue by pellegoeg** [qgis/QGIS#39223]
Hi,

Testing nightly build on mac os x, qgis_nightly_master_20201005_122844.dmg

**How to Reproduce**

1. Open project attached in nightly build 20201005_122844, [projectfiles.zip](https://github.com/qgis/QGIS/files/5338833/projectfiles.zip)
2. Zoom to "strategisk vejnet"
3. Identify a feature
4. See error on screenshot

Notice nothing in attribute tables and not posible to select a feature in wfs layer

![Screenshot 2020-10-07 at 09 09 38](https://user-images.githubusercontent.com/5758748/95299304-c5f47a80-087d-11eb-973f-a45a981623a7.png)

If project opened in 3.10 or 3.14, wfs service working as expected:
![Screenshot 2020-10-07 at 09 22 08](https://user-images.githubusercontent.com/5758748/95299832-a0b43c00-087e-11eb-9e6e-871397b09efc.png)

**QGIS and OS versions**

QGIS version | 3.15.0-Master | QGIS code revision | ac6ee22602
-- | -- | -- | --
Compiled against Qt | 5.14.2 | Running against Qt | 5.14.2
Compiled against GDAL/OGR | 3.1.2 | Running against GDAL/OGR | 3.1.2
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.4
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | macOS Mojave (10.14)
Active python plugins | DataPlotly; qad; qgis-maptiler-plugin; processing; db_manager; MetaSearch; Kortforsyningen; ImportPhotos

**Additional context**

2 different wfs services have be trying, same error.

**Comment by PeterPetrik** [comment]
@pellegoeg anything suspicious in the MessageLog dialog? 
@gioman would it be possible to test on win/linux is it is only macos issue?  thanks

**Comment by pellegoeg** [comment]
Messagelog for WFS is saying:
2020-10-07T09:39:46     WARNING    Cannot create temporary SpatiaLite cache.: GDALCreate() failed: OGR was built without libspatialite support
             ... sorry, creating/writing any SpatiaLite DB is unsupported

**Comment by gioman** [comment]
Works fine on master/windows.

**Comment by PeterPetrik** [comment]
fixed GDAL's [SQLite / Spatialite RDBMS](https://gdal.org/drivers/vector/sqlite.html) driver by https://github.com/qgis/QGIS-Mac-Packager/commit/54872e06a43ef61bf6dae8242e121bd5cec8be11

should be fixed in tomorrow's nightly build

**Comment by pellegoeg** [comment]
I will do

**Comment by PeterPetrik** [comment]
should be this one qgis_nightly_master_20201007_075531.dmg

**Comment by pellegoeg** [comment]
Working in lastnightly:

QGIS version | 3.15.0-Master | QGIS code revision | cfba539e0c
-- | -- | -- | --
Compiled against Qt | 5.14.2 | Running against Qt | 5.14.2
Compiled against GDAL/OGR | 3.1.2 | Running against GDAL/OGR | 3.1.2
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.4
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | macOS Mojave (10.14)
Active python plugins | Kortforsyningen; DataPlotly; ImportPhotos; qad; qgis-maptiler-plugin; processing; db_manager; MetaSearch



![Screenshot 2020-10-08 at 14 23 09](https://user-images.githubusercontent.com/5758748/95457999-e7369300-0971-11eb-939e-20d901337e10.png)
