### ISSUE TITLE
Topology Checker Tool: removing a rule does not persist once the project is saved

### ISSUE THREAD

**Issue by faridcher** [qgis/QGIS#39236]
In Topology Checker Tool (TCT), removing a rule from the **Topology rule settings** does not persist once the project is saved.
It will show up again when the QGIS project is re-opened. To reproduce, add at least two rules to TCT and then save the project. Then remove a rule, save, close and open the project. The removed rule is back!

thanks

**Comment by alexbruy** [comment]
Duplicates #33244.
