### ISSUE TITLE
OSGEO4W installer Win10 error - date October 7, 2020

### ISSUE THREAD

**Issue by antoniolocandro** [qgis/QGIS#39240]
Once installation is finished I get the following error

![image](https://user-images.githubusercontent.com/4627073/95357386-0b687600-0885-11eb-8eba-a066f0f0d1cb.png)

After clicking OK I get the next error

![image](https://user-images.githubusercontent.com/4627073/95357492-2804ae00-0885-11eb-8c85-944de28956fc.png)

**Comment by roya0045** [comment]
Dependencies conflict, duplicate ticket.

**Comment by antoniolocandro** [comment]
Ok how do I resolve it? Or I need to wait?

**Comment by roya0045** [comment]
You can try with the dedicated installer (not osgeo) to see if it works fine.

**Comment by antoniolocandro** [comment]
Alternative solution provided by Jef on Freenode: reinstall opencl fixed the problem

I think this issue should be left open until fixed in the installer probably

**Comment by gioman** [comment]
> I think this issue should be left open until fixed in the installer probably

@antoniolocandro but must be filed in the osgeo4w tracker, not here.

**Comment by jef-n** [comment]
> I would rather have the dependencies fixed as I have other things already configured. Is there anything I can do on my end?

The dependencies are fine - you probably did a windows updates inbetween that touched opencl.  The opencl package was previously installed and didn't meanwhile change - but reinstalling aligned it with your current setup.
