### ISSUE TITLE
Passwords are URL-encoded before base64 encoding for HTTP Basic auth

### ISSUE THREAD

**Issue by captaincoordinates** [qgis/QGIS#39243]
**Describe the bug**

QGIS supports HTTP Basic authentication when adding a WMS source if the user provides a username and password. The format for an HTTP Basic auth header is "Authorization: Basic _base64-encoded-user:pass_". When the password includes a reserved URL character e.g. % QGIS is URL-encoding the character before base64 encoding. This results in the wrong password being provided to the WMS and an authentication failure.

**How to Reproduce**
1. Add a WMS to QGIS with any valid URL (does not need to be a valid WMS to satisfy step 6) and provide the username & password "user" & "pa%%word" in the service definition's Basic auth tab. HTTP and not HTTPS may be preferable for inspecting traffic
2. Open QGIS Network Logger plugin, or establish some other way of inspecting HTTP traffic
3. Expand the added WMS to initiate a GetCapabilities request (it does not matter if the request fails)
4. Inspect the HTTP headers issued with the GetCapabilities request
5. Base64-decode the encoded value after "Basic " in the "Authorization" header
6. Observe text "user:pa%25%25word" showing that % in pa%%word have been URL-encoded

**QGIS and OS versions**
QGIS 3.10.10
MacOS 10.15.6

**Additional context**

**Comment by agiudiceandrea** [comment]
I can confirm the wrong behavior for WMS with HTTP Basic authentication.
The issue doesn't happen with WCS or WFS connections.

**Comment by elpaso** [comment]
I'm having trouble to reproduce this issue on master, can you try master?

I wrote a test for this issue and I cannot reproduce it, also I don't see any place in the authentication methods code where this url percent encoding could happen, I wonder if it's an artifact from the QGIS Network Logger plugin, are you sure that what you observed in the logger is what gets down into the wire?

This is my test case:

```python

# -*- coding: utf-8 -*-
"""
Tests for Basic Auth

From build dir, run: ctest -R PyQgsAuthBasicMethod -V

.. note:: This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.
"""

import os
import tempfile
import base64

from qgis.core import QgsApplication, QgsAuthManager, QgsAuthMethodConfig, QgsNetworkAccessManager
from qgis.PyQt.QtCore import QFileInfo, QUrl
from qgis.testing import start_app, unittest
from qgis.PyQt.QtNetwork import QNetworkRequest

AUTHDBDIR = tempfile.mkdtemp()
os.environ['QGIS_AUTH_DB_DIR_PATH'] = AUTHDBDIR


__author__ = 'Alessandro Pasotti'
__date__ = '13/10/2020'
__copyright__ = 'Copyright 2020, The QGIS Project'

qgis_app = start_app()


class TestAuthManager(unittest.TestCase):

    @classmethod
    def setUpAuth(cls, username, password):
        """Run before all tests and set up authentication"""
        assert (cls.authm.setMasterPassword('masterpassword', True))
        # Client side
        auth_config = QgsAuthMethodConfig("Basic")
        auth_config.setConfig('username', username)
        auth_config.setConfig('password', password)
        auth_config.setName('test_basic_auth_config')
        assert (cls.authm.storeAuthenticationConfig(auth_config)[0])
        assert auth_config.isValid()
        return auth_config

    @classmethod
    def setUpClass(cls):
        """Run before all tests"""
        cls.authm = QgsApplication.authManager()
        assert not cls.authm.isDisabled(), cls.authm.disabledMessage()

        cls.mpass = 'pass'  # master password

        db1 = QFileInfo(cls.authm.authenticationDatabasePath()
                        ).canonicalFilePath()
        db2 = QFileInfo(AUTHDBDIR + '/qgis-auth.db').canonicalFilePath()
        msg = 'Auth db temp path does not match db path of manager'
        assert db1 == db2, msg

    @classmethod
    def tearDownClass(cls):
        """Run after all tests"""
        pass

    def setUp(self):
        """Run before each test."""
        pass

    def tearDown(self):
        """Run after each test."""
        pass

    def _get_decoded_credentials(self, username, password):
        """Extracts and decode credentials from request Authorization header"""

        ac = self.setUpAuth(username, password)
        req = QNetworkRequest(QUrl('http://none'))
        self.authm.updateNetworkRequest(req, ac.id())
        auth = bytes(req.rawHeader(b'Authorization'))[6:]
        # Note that RFC7617 states clearly: User-ids containing colons cannot be encoded in user-pass strings
        u, p = base64.decodestring(auth).split(b':')
        return u.decode('utf8'), p.decode('utf8')

    def testHeaderEncoding(self):
        """Test credentials encoding"""

        for creds in (
            ('username', 'password'),
            ('username', r'pa%%word'),
        ):
            self.assertEqual(self._get_decoded_credentials(*creds), creds)

if __name__ == '__main__':
    unittest.main()

```

**Comment by agiudiceandrea** [comment]
@elpaso, tested with QGIS 3.15.0-Master QGIS code revision 5c8013df61 on Windows 7 64 bit (OSGeoW)
traffic captured using Wireshark

same user=`user` and password=`pa%%word` for WMS, WFS and WCS connections

* WMS
```
GET /testpasswms?SERVICE=WMS&REQUEST=GetCapabilities HTTP/1.1
Host: www.testpass.com
Cache-Control: no-cache
Pragma: no-cache
Authorization: Basic dXNlcjpwYSUyNSUyNXdvcmQ=
User-Agent: Mozilla/5.0 QGIS/31500
Connection: Keep-Alive
Accept-Encoding: gzip, deflate
Accept-Language: it-IT,en,*
```
WMS -> `Authorization: Basic dXNlcjpwYSUyNSUyNXdvcmQ=` -> decoded (base64) -> `user:pa%25%25word`



* WFS
```
GET /testpasswfs?SERVICE=WFS&REQUEST=GetCapabilities&ACCEPTVERSIONS=2.0.0,1.1.0,1.0.0 HTTP/1.1
Host: www.testpass.com
Cache-Control: no-cache
Pragma: no-cache
Authorization: Basic dXNlcjpwYSUld29yZA==
User-Agent: Mozilla/5.0 QGIS/31500
Connection: Keep-Alive
Accept-Encoding: gzip, deflate
Accept-Language: it-IT,en,*
```
WFS -> `Authorization: Basic dXNlcjpwYSUld29yZA==` -> decoded (base64) -> `user:pa$$word`

*WCS
```
GET /testpasswcs?SERVICE=WCS&REQUEST=GetCapabilities&VERSION=1.0.0 HTTP/1.1
Host: www.testpass.com
Authorization: Basic dXNlcjpwYSQkd29yZA==
User-Agent: Mozilla/5.0 QGIS/31500
Connection: Keep-Alive
Accept-Encoding: gzip, deflate
Accept-Language: it-IT,en,*
```
WCS -> `Authorization: Basic dXNlcjpwYSUld29yZA==` -> decoded (base64) -> `user:pa$$word`


in QGIS3.ini

WMS\testpasswms\username=user
WMS\testpasswms\password=pa%%word

WFS\testpasswfs\username=user
WFS\testpasswfs\password=pa%%word

WCS\testpasswcs\username=user
WCS\testpasswcs\password=pa$$word

**Comment by agiudiceandrea** [comment]
@elpaso, tested with QGIS 3.15.0-Master QGIS code revision 5c8013df61 on Windows 7 64 bit (OSGeoW)
traffic captured using Wireshark

same user=`user` and password=`pa%%word` for WMS, WFS and WCS connections

* WMS
```
GET /testpasswms?SERVICE=WMS&REQUEST=GetCapabilities HTTP/1.1
Host: www.testpass.com
Cache-Control: no-cache
Pragma: no-cache
Authorization: Basic dXNlcjpwYSUyNSUyNXdvcmQ=
User-Agent: Mozilla/5.0 QGIS/31500
Connection: Keep-Alive
Accept-Encoding: gzip, deflate
Accept-Language: it-IT,en,*
```
WMS -> `Authorization: Basic dXNlcjpwYSUyNSUyNXdvcmQ=` -> decoded (base64) -> `user:pa%25%25word`



* WFS
```
GET /testpasswfs?SERVICE=WFS&REQUEST=GetCapabilities&ACCEPTVERSIONS=2.0.0,1.1.0,1.0.0 HTTP/1.1
Host: www.testpass.com
Cache-Control: no-cache
Pragma: no-cache
Authorization: Basic dXNlcjpwYSUld29yZA==
User-Agent: Mozilla/5.0 QGIS/31500
Connection: Keep-Alive
Accept-Encoding: gzip, deflate
Accept-Language: it-IT,en,*
```
WFS -> `Authorization: Basic dXNlcjpwYSUld29yZA==` -> decoded (base64) -> `user:pa%%word`

*WCS
```
GET /testpasswcs?SERVICE=WCS&REQUEST=GetCapabilities&VERSION=1.0.0 HTTP/1.1
Host: www.testpass.com
Authorization: Basic dXNlcjpwYSUld29yZA==
User-Agent: Mozilla/5.0 QGIS/31500
Connection: Keep-Alive
Accept-Encoding: gzip, deflate
Accept-Language: it-IT,en,*
```
WCS -> `Authorization: Basic dXNlcjpwYSUld29yZA==` -> decoded (base64) -> `user:pa%%word`


in QGIS3.ini

WMS\testpasswms\username=user
WMS\testpasswms\password=pa%%word

WFS\testpasswfs\username=user
WFS\testpasswfs\password=pa%%word

WCS\testpasswcs\username=user
WCS\testpasswcs\password=pa%%word

**Comment by elpaso** [comment]
aahhh, I see: you are NOT using the QGIS authentication manager but the plaintext unencrypted project-level storage for credentials, I'll check that.
