### ISSUE TITLE
SVG symbol with modifiable fill and stroke color

### ISSUE THREAD

**Issue by faridcher** [qgis/QGIS#39254]
I have parameterized the stroke color of the  attached SVG file (search for 'param' string) to be used as a SVG marker in the Symbology definition of a layer. I change the color of this SVG marker to magenta via the interface, however, the color is not restored in the symbol definition dialog when I re-open it for further adjustment and it defaults to black again. This makes the stroke color (magenta) to be lost upon a change to another property in the symbol definition dialog. 

![image](https://user-images.githubusercontent.com/9982519/95435928-1217eb80-0960-11eb-9940-671a08bbd9ad.png)

[doo.zip](https://github.com/qgis/QGIS/files/5346453/doo.zip)

**Comment by nyalldawson** [comment]
This is fixed for 3.16

**Comment by faridcher** [comment]
@nyalldawson great. thanks.
