### ISSUE TITLE
Debian Testing Installation from Reporsitories: Could'n t load SIP Module

### ISSUE THREAD

**Issue by antonellosalis** [qgis/QGIS#39259]
**Error Message on Python at start and no Python support in QGIS**
I found the same problems in the past but no ways to solve it unless wait for a new SIP release or QGIS bugfix., this is the message when i Start QGIS:
Couldn't load SIP module.
Python support will be disabled.

Traceback (most recent call last):
  File "", line 1, in 
  File "/usr/lib/python3/dist-packages/qgis/__init__.py", line 78, in 
    import qgis.gui
  File "/usr/lib/python3/dist-packages/qgis/gui/__init__.py", line 25, in 
    from qgis._gui import *
ValueError: PyCapsule_GetPointer called with incorrect name
Python version:
3.8.6 (default, Sep 25 2020, 09:36:53) 
[GCC 10.2.0]

QGIS version:
3.10.10-A Coruña 'A Coruña', exported

Python path:
['/usr/share/qgis/python', '/home/antonello/.local/share/QGIS/QGIS3/profiles/default/python', '/home/antonello/.local/share/QGIS/QGIS3/profiles/default/python/plugins', '/usr/share/qgis/python/plugins', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/home/antonello/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/dist-packages', '/usr/lib/python3/dist-packages']

**How to Reproduce**

Just launch QGIS in Debian Testing

**QGIS and Debian testing**

**Comment by marcscama** [comment]
Hi, i confirm thé bug under à fresh debian testing.
Under linuxmint everithing works ok. Some python lib must bé update i Will try to replace some library...
Thanks

**Comment by marcscama** [comment]
No solutions for thé moment.  Debian déveloper must update thé packages and thé python dependecies

**Comment by antonellosalis** [comment]
A bug fix has been released. 
A simple:
```
apt update 
apt upgrade
```
Solved everythink.

Thank you guys.
A.
