### ISSUE TITLE
a relation widget  (e.g. one to many) doesn't show up in the "Edit feature's attributes dialog" if it is activated by "Edit > Modify attributes of selected features" menu

### ISSUE THREAD

**Issue by faridcher** [qgis/QGIS#39256]
Qgis 3.10.10

Relations (e.g. one to many) widget doesn't show up in the **Edit feature's attributes dialog** if it is activated by **Edit > Modify attributes of selected features** menu. It shows fine if activated from **Identify dialog edit feature** button. To reproduce, use the attached Geopackage and qgis project file. 'labs' layer has a many-to-many relation with 'owners' attribute table and a one-to-many relation with 'rents' table which are defined in the qgis project file. Try to select a labs' feature and edit its attribute. Launch the "edit attribute dialog" from the "edit" menu and from the identify dialog to see the difference.

Activated with Shift+E (from the Edit menu):
![image](https://user-images.githubusercontent.com/9982519/99126203-e94bdb80-261a-11eb-9564-d1d108bf6c8f.png)

Activated from Identify Window:
![image](https://user-images.githubusercontent.com/9982519/99126241-008ac900-261b-11eb-85fd-57ac595d6ef6.png)

[test.zip](https://github.com/qgis/QGIS/files/5346749/test.zip)

**Comment by Pedro-Murteira** [comment]
Still valid on QGIS 3.22.3.

**Comment by domi4484** [comment]
@faridcher I suppose you were trying to edit multiple features at the same time (as the widget looks like in multiediting mode). The relation editor widget supports multiediting only from QGIS 3.24. For older versions it is simply not shown.

@Pedro-Murteira in 3.22 you should at least see two empty groups like this right?
![image](https://user-images.githubusercontent.com/9881900/151306088-27650832-66ee-478d-b045-91b2deeff4ed.png)

**Comment by Pedro-Murteira** [comment]
@domi4484 yes, correct

**Comment by faridcher** [comment]
@domi4484 I just selected a single feature and opened the editor dialog. The same happens with 3.16.15.

**Comment by domi4484** [comment]
@faridcher you are right I also just tried with 3.16.
I think that for a single feature the attribute form should not open in multiedit mode. But 3.16 will be soon end of life and this will probably remain so.

**Comment by gioman** [comment]
> But 3.16 will be soon end of life and this will probably remain so.

@domi4484 correct, there are no more fixes for 3.16, so this is fixed in 3.22 and later this can be closed.

**Comment by alexbruy** [comment]
Seems fixed in the latest master (f344919474). Please reopen if necessary

**Comment by faridcher** [comment]
@alexbruy Seems to be fixed in 3.28.11. thank you for testing.
