### ISSUE TITLE
Graphics modeler crashes after editing child model.

### ISSUE THREAD

**Issue by MrChebur** [qgis/QGIS#39260]
## User Feedback

The following steps will crash QGIS 3:
1. Open the Graphical modeller.
2. Create your custom model (parent) and save it.
3. Create another custom model (submodel) and save it.
4. Insert the submodel into the parent model and save it.
5. Modify the submodel and save it.
6. Edit the parent model (an infinite loop will appear leading to a failure).

## Report Details

**Crash ID**: [5ef3b1b179838436c9284492de789b95b01b994a](https://github.com/qgis/QGIS/search?q=5ef3b1b179838436c9284492de789b95b01b994a&type=Issues)

**Stack Trace**
<pre>
QBitArray::QBitArray :
QgsRenderChecker::renderedImage qgsrenderchecker.h:88
QgsModelChildAlgorithmGraphicItem::linkPointText qgsmodelcomponentgraphicitem.cpp:993
sipQgsModelChildAlgorithmGraphicItem::linkPointText sip_guipart1.cpp:122701
QgsModelComponentGraphicItem::linkPoint qgsmodelcomponentgraphicitem.cpp:601
QgsModelArrowItem::updatePath qgsmodelarrowitem.cpp:145
QgsModelArrowItem::QgsModelArrowItem qgsmodelarrowitem.cpp:51
QgsModelGraphicsScene::createItems qgsmodelgraphicsscene.cpp:177
meth_QgsModelGraphicsScene_createItems sip_guipart1.cpp:95844
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_sip :
sipVH__gui_73 sip_guipart0.cpp:8314
sipQgsModelDesignerDialog::repaintModel sip_guipart1.cpp:106841
QMetaObject::activate :
QMetaObject::activate :
QgsModelOutputGraphicItem::deleteComponent qgsmodelcomponentgraphicitem.cpp:1187
sipQgsModelOutputGraphicItem::deleteComponent sip_guipart1.cpp:119277
QgsModelDesignerDialog::deleteSelected qgsmodeldesignerdialog.cpp:698
QMetaObject::activate :
QAction::activate :
QAction::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:439
QCoreApplication::notifyInternal2 :
QShortcutMap::dispatchEvent :
QShortcutMap::tryShortcut :
QWindowSystemInterface::handleShortcutEvent :
QGuiApplicationPrivate::processKeyEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1618
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.14.16-Pi
QGIS code revision: df27394552
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

**Comment by nyalldawson** [comment]
Can you share your models please?

**Comment by MrChebur** [comment]
> Can you share your models please?

@nyalldawson 
Here it is: [models.zip](https://github.com/qgis/QGIS/files/5352562/models.zip)
Reproducing the error: [Crash video.zip](https://github.com/qgis/QGIS/files/5352565/Crash.video.zip)

**Comment by MrChebur** [comment]
fixed in https://github.com/qgis/QGIS/pull/40743
