### ISSUE TITLE
Advanced digitizing: Self-snapping does not work with layers using geographic CRS / only works with first edited layer

### ISSUE THREAD

**Issue by jdugge** [qgis/QGIS#39268]
In QGIS 3.14, when creating a new feature using advanced digitizing on a layer with a geographic CRS (such as EPSG:4326), self-snapping does not work: vertices of the feature currently being digitized do not snap.

Snapping to existing features of the same layer works fine. So does editing an existing feature: the current state of the feature is correctly used for snapping. The problem only occurs when creating new features.

![Peek 2020-10-08 21-15](https://user-images.githubusercontent.com/2399255/95503900-4c0edf00-09ac-11eb-8edd-ca769df56c3a.gif)

In QGIS Master, the behaviour has changed a bit:

In QGIS Master, self-snapping for new features only works for layers that use the same CRS as the first layer that was edited in the QGIS session. If you first edit a layer using EPSG:4326, self-snapping will be fine for that layer and any other layers that use EPSG:4326, but if you then edit a layer that uses a different CRS, self-snapping will not work for new features.

To reproduce:

1. Open the [test project](https://github.com/qgis/QGIS/files/5359960/Self_snapping_issue_39268.zip).
2. Activate edit mode for layer "EPSG_3857". Make sure that Advanced Digitizing mode is active, and that Snapping for all layers and Self Snapping are enabled.
3. Start creating a new feature. Self-snapping works.
4. Activate edit mode for layer "EPSG_4326".
5. Start creating a new feature. Self-snapping does not work.

Repeat, editing the layers in reverse order:

1. Restart QGIS, open the project again.
2. Activate edit mode for layer "EPSG_4326".
4. Start creating a new feature. Self-snapping works.
5. Activate edit mode for layer "EPSG_3587".
6. Start creating a new feature. Self-snapping does not work.

![Peek 2020-10-10 22-35](https://user-images.githubusercontent.com/2399255/95664754-08061080-0b4b-11eb-9ac1-d23f770394f9.gif)

**Comment by gioman** [comment]
> , self-snapping does not work: vertices of the feature currently being digitized do not snap.

@jdugge it does not work also on a layer with a projected crs here, but why that would work? doing that you would create a duplicate node, which is a geometry error.

**Comment by jdugge** [comment]
@gioman: Self-snapping is a new feature that was introduced in QGIS 3.14. The main use case is not for creating duplicate nodes, but rather for snapping to existing nodes in construction mode or while other constraints are active. This is useful for digitizing rectangular features, for example. See https://github.com/qgis/QGIS/pull/36200 for an explanation.

I'm surprised that it doesn't work for you with a layer using a projected CRS. Have you activated the "Self snapping" mode (the right-most button of the top panel in my video)?

**Comment by gioman** [comment]
@jdugge let me check if I have done everything right.

**Comment by jdugge** [comment]
Strangely, it seems like the behavior has changed between QGIS 3.14 and current Master (1258afe635). Here is a [test project](https://github.com/qgis/QGIS/files/5359658/Self_snapping_issue_39268.zip) using EPSG:3857 and two layers.

* On QGIS 3.14, self-snapping only works for the layer using the geographic CRS EPSG:4326.
* On Master, self-snapping only works for the layer using the projected CRS EPSG:3857.
