### ISSUE TITLE
Hatching / Labelling of LRS/Calibrated Routes

### ISSUE THREAD

**Issue by klainkaliber** [qgis/QGIS#39263]
**Feature description.**

QGIS is missing a way to label calibrated routes, i.e. "hatches" in ESRI terminology. Hatches are dashes/points/markers combined with numbers along routes that usually show the chainage of a calibrated route (in shape files: "has m-values").

This is a basic visualisation functionality needed for everyone working with road networks.

Below an example of a hatched calibrated line.
The hatching is done dynamically, there are no geometric objects that are saved to the disk.

![hatches](https://user-images.githubusercontent.com/3832138/95467769-24088700-097e-11eb-9709-a1ab1ff51a9b.jpg)

**Additional context**

Calibration itself can be done by using the LRS plugin, so this is already a QGIS functionality. Even more advantageous would be the possibility to manage multiple, time dependend, linear referencing systems. Reason for that is that roads sometimes change their layout as e.g. a by-pass is built. Then the length and hence the chainage changes over time. I wonder if this would be achievable with the new time functionality.

**Comment by nyalldawson** [comment]
I would like to look into this, but do not have access to the ESRI licenses required to generate calibrated routes. Are you able to share some data + an MXD or LYR file containing this symbology option? Screenshots of the ArcMap configuration for the hatches would be appreciated also!!

**Comment by klainkaliber** [comment]
Great!
I attach a MXD containing:
- a calibrated Route (data source is OSM); calibration was actually done in QGIS/LRS 
       [OSM_Bayern_motorway_route_calibrated5QGIS.shp]
- the chainage points that were used for the calibration [A93_RouteCalibration.shp]
- Route Events [A93_Route_Events.xlsx]

The route is hatched, hatches shoud be visisble on opening of MXD.

Below some screenshots from the Hatches Dialogue in ArcMap:

![Screenshot_MXD](https://user-images.githubusercontent.com/3832138/95556820-30d7ba00-0a14-11eb-940f-54803385099d.jpg)

![grafik](https://user-images.githubusercontent.com/3832138/95557007-7d22fa00-0a14-11eb-849d-930e6da6f0b8.png)

![grafik](https://user-images.githubusercontent.com/3832138/95557054-8ad87f80-0a14-11eb-93fc-ec04a7a32b37.png)

![grafik](https://user-images.githubusercontent.com/3832138/95557106-9deb4f80-0a14-11eb-964e-63dcb29fe38d.png)

![grafik](https://user-images.githubusercontent.com/3832138/95557138-a6dc2100-0a14-11eb-87e2-caccd955d200.png)

![grafik](https://user-images.githubusercontent.com/3832138/95557191-b8252d80-0a14-11eb-8d91-d2108df0413c.png)







[QGIS_Hatches.zip](https://github.com/qgis/QGIS/files/5353300/QGIS_Hatches.zip)

**Comment by nyalldawson** [comment]
Thanks @klainkaliber !

**Comment by pjshelton** [comment]
Hi,
To create these using extra layers, I add extra vertices to the road, extract vertices to points, then use the M value on the points as the displayed value.
Doing the above without the extra layer, requires adding the extra vertices to the road, then using the geometry generator to create a multipoint object (thus getting a point at each required distance), but then, instead of displaying an attribute from the object data table, you will need to display the m value of each point.  This value is currently not available.

This is all before making sure each label is set out  so that as you move along the line you meet the bottom of each label first.  Each label should be rotated the same way with respect to the direction of the line.  This means that if the roads fold over on its self the labels are upside down on that part of the road that comes down the page.

In the image at the top of the page, the 95 should be the other way around if this is to be used as "Chainage" in Australia. 

Does the Arc version allow for an offset from the line?

**Comment by pjshelton** [comment]
Also, sometimes roads are made up of more than one feature.  So I would like to ask for the ability to add an offset along the line for the first mark that is not a multiple of the hashing interval.

**Comment by pjshelton** [comment]
Actually, to be a "Chainage" in Australia, all the numbers except the 95 need to be turned around in that first image.

**Comment by pjshelton** [comment]
On reading #21642 I realised that this could be a marker line type.  All you need to to do is expose either the distance along the line for each maker, or its maker number (where each marker id is the count along the line) and then using the function line_interpolate_point(), line_interpolate_angle(), and m() everything you need can be calculated and displayed using Marker line with Font Marker.

Also, #21642 goes a long way to solving my concern about the "object" being made up of multiple features.

**Comment by pjshelton** [comment]
![image](https://user-images.githubusercontent.com/39154868/103447747-180d3680-4cdb-11eb-9505-f6ea73f5e08b.png)
What is missing, and would be a solution for this request, is a new 'with interval' measure that knows about the m values on the line object.

**Comment by klainkaliber** [comment]
> 
> Does the Arc version allow for an offset from the line?

Yes, you can define a lateral offset - see second screenshot of "Layer Properties".

**Comment by pjshelton** [comment]
The function that would do the new measure would be the Postgres ST_LocateAlong() which apparently interpolates if the required measure is not on a vertex.

**Comment by pjshelton** [comment]
My marker line solution has a current problem in that the font maker can not be offset from the line properly.  the line that gets used for measuring is the offset line, not the original.  And the offset label x and y do not work the way I would like them to for this use case.

**Comment by pjshelton** [comment]
I also tried using the hashed line type and using a font marker on the hash line, but the @geometry_point_num is tied to the hash line not the line being hashed.

**Comment by pjshelton** [comment]
#20166 is a duplicate. 

Just realised that the marker line only guarantees that the marks are that far apart, and are not measured from the beginning of the feature.

**Comment by klainkaliber** [comment]
I think this could be closed as the feature was implemented in QGIS 3.40
see
https://qgis.org/project/visual-changelogs/visualchangelog340/#feature-add-linear-referencing-symbol-layer-type

Thank you very much, Nyall!
