### ISSUE TITLE
Crash QGIS

### ISSUE THREAD

**Issue by Octansf** [qgis/QGIS#39262]
## User Feedback

I create a new script from template and when click on save as, search for folder to put my file and click on save button QGIS explode

## Report Details

**Crash ID**: [db167c9365fe5cd4e60710d9d5cd5fe7040bdb3d](https://github.com/qgis/QGIS/search?q=db167c9365fe5cd4e60710d9d5cd5fe7040bdb3d&type=Issues)

**Stack Trace**
<pre>
UserCallWinProcCheckWow :
DispatchClientMessage :
_fnDWORD :
KiUserCallbackDispatcherContinue :
ZwUserPeekMessage :
PeekMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1618
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.14.16-Pi
QGIS code revision: df27394552
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by roya0045** [comment]
Error in code, not qgis.

**Comment by gioman** [comment]
@Octansf Post the code to get some support. Will reopen if it turns out to be a QGIS issue.
