### ISSUE TITLE
Export or "Save as" a layer into current working directory instead of user directory

### ISSUE THREAD

**Issue by mapperfr** [qgis/QGIS#39279]
"Export" or "Save As..." a layer currently in the layer selector opens the user directory (/home/user on Linux) and not the working directory. Would be nice to be able set the behaviour in the preferences: user directory or working directory.

QGIS 3.14.16 under Ubuntu 20.04.

**Comment by gioman** [comment]
I believe there are already other tickets asking the same.

**Comment by JeremyG** [comment]
Yeah there must be indeed but I couldn't find them yet! I'll keep looking and report here if I find anything.

**Comment by alexbruy** [comment]
Related to #35651.
