### ISSUE TITLE
gdal_translate

### ISSUE THREAD

**Issue by magman2** [qgis/QGIS#39271]
GQIS version 3.10
Raster | Extraction | Clip Raster by Extent
text in windows says 
'Clipping extent(xmin,xmax,ymin,ymax)' is incorrect should be
'Clipping extent(xmin,ymax,xmax,ymin)
also the delimiter of these parameters changes from comma (lat,long) so space (UTM)

Despite this QGIS still works well ! for this operation at least on ERMapper ERS files I am using.

Problem is when I am calling gdal_translate myself in other code. I use QGIS to help with syntax and testing.

Amazing software - many thanks to all !

**Comment by magman2** [comment]
Clarification
QGIS swaps these parameters before calling gdal_translate hence my confusion.
These parameters are entered in QGIS as comma separated but gdal_translate uses space delimited - always.
Would be more robust to check that xMin < x_max and y_min < y_max

Suggestion
'Clipping extent(xmin,xmax,ymin,ymax)' is changed to
'Clipping extent(xmin,xmax,ymin,ymax) comma separated here - parameters swapped and space delimited when calling gdal_translate' (or as help when hover over Edit Box).

**Comment by gioman** [comment]
@magman2 where is the issue here? The widget that defines the clipping extent write it in the GUI as xmin,xmax,ymin,ymax, and then this is rearranged as necessary when running the tool, so what?

**Comment by magman2** [comment]
Thanks for the follow up.

The widget works fine. Just the swapping of parameter is a bit confusing at first.
