### ISSUE TITLE
ImportError: cannot import name 'ScriptUtils' from 'processing.script

### ISSUE THREAD

**Issue by alechamizo** [qgis/QGIS#39277]
Hi,

My QGIS Versión de QGIS: 3.14.16-Pi Pi, df27394552  generates an error when it starts. I installed QGIS 3.14.16 in a new computer and copied the folder of user from other computer (AppData\Roaming\QGIS\QGIS3\profiles\)
May be the reason for errors?
Thanks

ImportError: cannot import name 'ScriptUtils' from 'processing.script' (C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python/plugins\processing\script\__init__.py) 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python\qgis\utils.py", line 312, in loadPlugin
    __import__(packageName)
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python/plugins\processing\__init__.py", line 26, in 
    from processing.tools.general import *  # NOQA
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python/plugins\processing\tools\general.py", line 32, in 
    from processing.core.Processing import Processing
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python/plugins\processing\core\Processing.py", line 52, in 
    from processing.script import ScriptUtils
ImportError: cannot import name 'ScriptUtils' from 'processing.script' (C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python/plugins\processing\script\__init__.py)

Versión de Python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Versión de QGIS: 3.14.16-Pi Pi, df27394552 

Ruta de Python:
C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python
C:/Users/achamizo/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/achamizo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS3~1.14\apps\Python37
C:\PROGRA~1\QGIS3~1.14\apps\Python37\Scripts
C:\Program Files\QGIS 3.14\bin\python37.zip
C:\PROGRA~1\QGIS3~1.14\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.14\apps\Python37\lib
C:\Program Files\QGIS 3.14\bin
C:\PROGRA~1\QGIS3~1.14\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.14\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.14\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.14\apps\Python37\lib\site-packages\Pythonwin
C:/Users/achamizo/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\achamizo\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms
.

**Comment by gioman** [comment]
@alechamizo please ask questions on the users or developers mailing lists. Thanks!
