### ISSUE TITLE
QGIS 3.14.16 crash on opening project

### ISSUE THREAD

**Issue by EzVal** [qgis/QGIS#39285]
After installing the new release QGIS desktop does not open project files that contains joins on MS ACCESS tables. The problem does non appear on version 3.14.0 - 32 bit
OS: Win 10 pro 64 bit
QGIS Versione: 3.14.16 32 bit
MS ACCESS version: 16 - 32bit
[Example.zip](https://github.com/qgis/QGIS/files/5355454/Example.zip)

**Comment by gioman** [comment]
@EzVal Try with a new QGIS profile

**Comment by gioman** [comment]
Closing for lack of feedback.
