### ISSUE TITLE
QGIS 3.14.16 crash on export from map window

### ISSUE THREAD

**Issue by grantboxer** [qgis/QGIS#39298]
## User Feedback

QGIS crashes on creating export jpg from image

## Report Details

**Crash ID**: [1d5ed672dc1b64fc24118b59e560969ad8cbd8bb](https://github.com/qgis/QGIS/search?q=1d5ed672dc1b64fc24118b59e560969ad8cbd8bb&type=Issues)

**Stack Trace**
<pre>
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QRasterPaintEngine::fillRect :
QRasterPaintEngine::drawImage :
QgsRasterDrawer::drawImage qgsrasterdrawer.cpp:174
QgsRasterDrawer::draw qgsrasterdrawer.cpp:105
QgsRasterLayerRenderer::render qgsrasterlayerrenderer.cpp:299
QgsMapRendererCustomPainterJob::doRender qgsmaprenderercustompainterjob.cpp:316
QgsMapRendererCustomPainterJob::renderPrepared qgsmaprenderercustompainterjob.cpp:235
QgsMapRendererTask::run qgsmaprenderertask.cpp:245
QgsTask::start qgstaskmanager.cpp:83
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.14.16-Pi
QGIS code revision: df27394552
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by Gustry** [comment]
Clicking on the crash ID link, it leads to #39189, duplicate @grantboxer ?

**Comment by gioman** [comment]
Closing as duplicate.
