### ISSUE TITLE
QGIS layout crash when re-ordering items

### ISSUE THREAD

**Issue by klakar** [qgis/QGIS#39309]
**Describe the bug**
Trying to reorder the items in a layout with drag-and-drop will (eventually) crash QGIS.

**How to Reproduce**
1. Start a layout (no need to add any data)
2. Add **three** shapes to the layout.
![Skärmbild från 2020-10-11 10-37-34](https://user-images.githubusercontent.com/6375959/95674028-d2deda00-0bad-11eb-87f9-461d82e723d9.png)
3. Try to reorder the items in the Items panel.

Items will not reorder, and eventually QGIS crash.

**QGIS and OS versions**

QGIS version | 3.15.0-Master | QGIS code revision | 9efa05b1e2
-- | -- | -- | --
Compiled against Qt | 5.12.8 | Running against Qt | 5.12.8
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.4 (Ubuntu 12.4-0ubuntu0.20.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Linux Mint 20 | This copy of QGIS writes debugging output.
Active python plugins | latlontools; MetaSearch; processing; db_manager

**Additional context**
From Terminal:
```
Fatal: ASSERT failure in QList<T>::at: "index out of range", file /usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h, line 544
QGIS died on signal -1Could not attach to process.  If your uid matches the uid of the target
process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
ptrace: Operationen inte tillåten.
No thread selected
No stack.
gdb returned 256
Avbruten (SIGABRT) (minnesutskrift skapad)

```

**Comment by nyalldawson** [comment]
This is already fixed in a newer build
