### ISSUE TITLE
QGIS 3.10.10 no longer supports browsing GRASS repositories

### ISSUE THREAD

**Issue by mankoff** [qgis/QGIS#39301]
**Describe the bug**

Yesterday, using 3.10.9, I could brows GRASS repositories in the Browser. My "G" folders (my GRASS locations) appeared both as a folder, and again with the GRASS icon which exposed the mapsets and rasters and vectors therein.  That special icon and view of the GRASS folder is gone.

This page on GRASS integration https://docs.qgis.org/3.10/en/docs/user_manual/grass_integration/grass_integration.html#loading-grass-raster-and-vector-layers says `If you don’t see GRASS location item, verify in Help ‣ About ‣ Providers if GRASS vector provider is loaded.`

On that page, I see

```
9. GRASS 7 vector provider
10. GRASS 7 raster provider
```

And I have all the GRASS tools listed under the "Processing Toolbox".

Finally, when I go to Plugins, GRASS is installed, but when I toggle it off and then on, I get this message in the QGIS Log:

`
2020-10-10T06:35:21     WARNING    GRASS init error : Problem in GRASS initialization, GRASS provider and plugin will not work : Module built against version 2020-10-05T18:11:37+00:00 but trying to use version 2020-10-05T19:53:30+00:00. You need to rebuild GRASS GIS or untangle multiple installations.
`

As far as I know I only have 1 version of GRASS installed, by the OS, using the same `deb` source as QGIS. That GRASS version hasn't changed anytime recently, only QGIS has (yesterday, when this issue appeared).

I haven't done anything to change my GRASS install, only upgrade QGIS per the OS suggestion. I'm on Kubuntu 20.04 LTS using `deb http://ppa.launchpad.net/ubuntugis/ubuntugis-unstable/ubuntu focal main` in `/etc/apt/sources.list.d`.

**QGIS and OS versions**

QGIS version | 3.10.10-A Coruña | QGIS code branch | Release 3.10
-- | -- | -- | --
Compiled against Qt | 5.12.8 | Running against Qt | 5.12.8
Compiled against GDAL/OGR | 3.1.3 | Running against GDAL/OGR | 3.1.3
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.4 (Ubuntu 12.4-0ubuntu0.20.04.1) | SpatiaLite Version | 5.0.0
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 7.1.1 | Running against PROJ | Rel. 7.1.1, September 1st, 2020
OS Version | Ubuntu 20.04.1 LTS
Active python plugins | send2google_earth; latlontools; processing; MetaSearch; db_manager

**Comment by mankoff** [comment]
Hello. QGIS just upgraded again, even though I'm running LTS. I get the same error:

> 2021-01-26T05:33:26     WARNING    GRASS init error : Problem in GRASS initialization, GRASS provider and plugin will not work : Module built against version 2020-12-23T15:13:18+00:00 but trying to use version 2021-01-05T16:37:09+00:00. You need to rebuild GRASS GIS or untangle multiple installations.

I've just removed and re-installed QGIS and GRASS and still get this error. Unfortunately I do not know what I did last time to fix it, and this bug was quickly closed without support. Do you have any suggestions how to get QGIS to browse GRASS locations after an upgrade?

**Comment by gioman** [comment]
> I've just removed and re-installed QGIS and GRASS and still get this error. Unfortunately I do not know what I did last time to fix it, and this bug was quickly closed without support. Do you have any suggestions how to get QGIS to browse GRASS locations after an upgrade?

@mankoff QGIS 3.16 on Ubuntu 20.04. QGIS is installed using qgis.org repos **without** using the Ubuntugis one. Opening a GRASS mapset/location and adding layers from it works ok.
