### ISSUE TITLE
QGIS 3.10.10: Generate XYZ tiles (Directory) - Execution failed

### ISSUE THREAD

**Issue by Konstantinos-Sk** [qgis/QGIS#39304]
[ImageAndPoints.zip](https://github.com/qgis/QGIS/files/5359953/ImageAndPoints.zip)

**Describe the bug**

The execution of the tool `Generate XYZ tiles (Directory)` fails after clicking `Run` button.

**How to Reproduce**

I will write down all the steps I did. 

1. Run QGIS program and Click on `Raster tab > georeferencer` (if the plugin is not installed, click on `Plugins tab > Manage and Install plugins...` and under `Installed` tab tick `Georeferencer GDAL` to enable).
2. In Georeferencer window, click on `File > Open Raster` and select `2384.jpg` (the attached picture).
3. In Georeferencer window, click on `File > Load GCP Points` and select `2384.jpg.points` (the attached coordinates).
4. In Georeferencer window, click on `File > Start Georeferencing` and it will ask for transformation type. Click `OK`.
5. In the box that opened, set `Transformation type: Polynomial2`, `Resampling method: Nearest neighbour` and `Target SRS: EPSG:4326 - WGS 84`. Set an `Output raster` and save it as `2384_modified.tif` file. Last tick `Load in QGIS when done`. Click `OK`.
6. In Georeferencer window, click on `File > Start Georeferencing` one last time so it will start processing.
7. Now `2384_modified` is loaded in `Layers` box (at the left side by default). Open `Processing Toolbox` (Ctrl+Alt+T) and type `xyz` in search box.
8. Click on `Generate XYZ tiles (Directory)` and another window opens with parameters.
9. In `Extent (xmin, xmax, ymin, ymax)` click on the `...` and select `User Layer Extent` and click `OK`.
10. Set `Minimum zoom: 2` and `Maximum zoom: 7`
11. Tick `Use inverted tile Y axis (TMS convention) [optional]` and set an `Output directory`.
12. Click `Run`.

**QGIS and OS versions**

QGIS version: 3.10.10-A Coruña
Windows 7 Ultimate Service Pack 1

**Additional context**

```python
QGIS version: 3.10.10-A Coruña
QGIS code revision: 8b051b9a43
Qt version: 5.11.2
GDAL version: 3.0.4
GEOS version: 3.8.1-CAPI-1.13.3
PROJ version: Rel. 6.3.2, May 1st, 2020
Processing algorithm…
Algorithm 'Generate XYZ tiles (Directory)' starting…
Input parameters:
{ 'BACKGROUND_COLOR' : QColor(0, 0, 0, 0), 'DPI' : 96, 'EXTENT' : '-3002.4051096826083,3000.8280953125172,-3000.255191098833,3000.7554173746357 [EPSG:4326]', 'METATILESIZE' : 4, 'OUTPUT_DIRECTORY' : 'C:\\Users\\%USER%\\Downloads\\OpenLayers
![2384](https://user-images.githubusercontent.com/6353082/95664130-b1e69c80-0b4d-11eb-94a8-946e06c01466.jpg)
![2384](https://user-images.githubusercontent.com/6353082/95664157-f3774780-0b4d-11eb-9442-31726552705c.jpg)
[ImageAndPoints.zip](https://github.com/qgis/QGIS/files/5359950/ImageAndPoints.zip)



', 'OUTPUT_HTML' : 'TEMPORARY_OUTPUT', 'QUALITY' : 75, 'TILE_FORMAT' : 0, 'TILE_HEIGHT' : 256, 'TILE_WIDTH' : 256, 'TMS_CONVENTION' : True, 'ZOOM_MAX' : 7, 'ZOOM_MIN' : 2 }

Traceback (most recent call last):
File "C:/PROGRA~2/QGIS3~1.10/apps/qgis-ltr/./python/plugins\processing\algs\qgis\TilesXYZ.py", line 574, in processAlgorithm
self.generate(writer, parameters, context, feedback)
File "C:/PROGRA~2/QGIS3~1.10/apps/qgis-ltr/./python/plugins\processing\algs\qgis\TilesXYZ.py", line 289, in generate
metatiles = get_metatiles(self.wgs_extent, zoom, self.metatilesize)
File "C:/PROGRA~2/QGIS3~1.10/apps/qgis-ltr/./python/plugins\processing\algs\qgis\TilesXYZ.py", line 122, in get_metatiles
left_tile, top_tile = deg2num(north_edge, west_edge, zoom)
File "C:/PROGRA~2/QGIS3~1.10/apps/qgis-ltr/./python/plugins\processing\algs\qgis\TilesXYZ.py", line 71, in deg2num
ytile = int((1.0 - math.log(math.tan(lat_rad) + (1 / math.cos(lat_rad))) / math.pi) / 2.0 * n)
ValueError: math domain error

Execution failed after 0.07 seconds

Loading resulting layers
Algorithm 'Generate XYZ tiles (Directory)' finished
HTML output has been generated by this algorithm.
Open the results dialog to check it.
```

**Comment by roya0045** [comment]
`'EXTENT' : '-3002.4051096826083,3000.8280953125172,-3000.255191098833,3000.7554173746357 [EPSG:4326]'`
Seriously? how is that even a bug if you can't make a valid layer.

**Comment by Konstantinos-Sk** [comment]
The map has the center of the image as x, y = 0.0, 0.0

bottom left corner:
minx = -3000.0
miny = -3000.0

top right corner:
maxx = 3000
maxy = 3000

I use these two corners as latLngBounds in LeafLet and everything works as expected.

**Comment by gioman** [comment]
> I use these two corners as latLngBounds in LeafLet and everything works as expected.

@Konstantinos-Sk those bound in WGS84 do not make any sense.

**Comment by roya0045** [comment]
I don't think the proposed use case is valid. Who in their right mind would georeference something that wraps around the earth 16 times? I think that failing the execution is perfectly valid in this case.

**Comment by gioman** [comment]
Closing for lack of further feedback.
