### ISSUE TITLE
Add icone in the panel layers

### ISSUE THREAD

**Issue by Emmanuel-Duguey** [qgis/QGIS#39311]
Can we add icone in the panel layers ? it would be very helpfull  to help users to organise properly all the layers, as it is done in the 3D software 
![icone_](https://user-images.githubusercontent.com/66991820/95675584-9f557d00-0bb8-11eb-8797-effae045d420.png)

**Comment by nicogodet** [comment]
https://github.com/YoannQDQ/qgis-layer-tree-icons

**Comment by Emmanuel-Duguey** [comment]
thank you for the plugin, it woudl be great also to change the color and the font to the group item

**Comment by nicogodet** [comment]
You can try to open an issue for a feature request on plugin repo.
