### ISSUE TITLE
[Georeferencer] Make georeferencer less strict with CRS

### ISSUE THREAD

**Issue by roya0045** [qgis/QGIS#39314]
Currently the georeferencer and the canvas point selector need to be in the same projection to work properly.

I am proposing to add an attribute to the point indicating the original projection of the point. When the point are manually entrered we can assume that they are of the projected source if within boundary.

These could be added to the QgsGeorefDataPoint by rigging somethiing qgsmapcoordsdialog

optimally the projection correction would occur when setting the coordinates of the map and once set when a point is added.

This would simplify things. and prevent users from having to fiddle with projections.

**Comment by nyalldawson** [comment]
Good idea. The current situation is far from perfect!!

**Comment by gioman** [comment]
> canvas point selector need to be in the same projection to work properly.

@roya0045 in the past it used to work as expected: you could pick point over a project with CRS "a" and in georef configuration choose CRS "b" and the result would have been transformed on the the fly.

**Comment by roya0045** [comment]
I'm thinking about adding the crs selector to the qgsmapcoordsdialog that default to the project selection. This should help prevent ambiguity in regards to manual inputs.

**Comment by roya0045** [comment]
Implemented
