### ISSUE TITLE
qgis-bin-q7.exe access point not found

### ISSUE THREAD

**Issue by ecodiv** [qgis/QGIS#39310]
**Describe the bug**
After installing QGIS (v3.14.16-2) with GRASS GIS (v7.8.1-4) and the qgis-grass-plugin 7 (tried v3.14.16-3 and 16-2) using the osgeo4w installer, opening the QGIS with GRASS results in an error message

![csrss_EtslgpcKZ5](https://user-images.githubusercontent.com/7816789/95674518-0bcc7e00-0bb1-11eb-918b-3fbb4e4000d4.png)

In English: Can not find the access point procedure ?glyphache@QFontEngine@@QEBAPEAVQFontEngineGlphy Cache@@PEBXW4GlyphFormat@1@AEBVQTransform@@@Z in DLL file c:\osgeo4~\app\qt5\bin\Qt5OpenGL.dll

**How to Reproduce**

Install QGIS, GRASS GIS, and qgis-grass-plugin using OSGeo4W custom install

**QGIS and OS versions**

Windows 10, QGIS v3.14.16-2, GRASS v7.8.1-4, qgis-grass-plugin 7 (tried both v3.14.16-3 and v3.14.16-2)

**Additional context**

**Comment by gioman** [comment]
@ecodiv 

On a clean Windows 10 machine I can't replicate what you describe, but on activating the GRASS plugin I get


_2020-10-12T10:32:43     WARNING    GRASS init error : Problem in GRASS initialization, GRASS provider and plugin will not work : Module built against version 8bcecc9a6 but trying to use version d8fbd49af. You need to rebuild GRASS GIS or untangle multiple installations._


that I guess depends on the fact that QGIS package is 3..14.16-2 and the GRASS plugin one is 3.14.16-3. Downgrading the latter to -2 and everything is ok.

**Comment by agiudiceandrea** [comment]
Hi @ecodiv , is RStudio installed in your system?

**Comment by ecodiv** [comment]
Hi @gioman ,  thanks for the feedback. I also tried to downgrade, didn't make a difference though. 
 @agiudiceandrea , yes, I've Rstudio installed.

**Comment by agiudiceandrea** [comment]
@ecodiv,@gioman this is a known issues... See https://github.com/qgis/QGIS/issues/38476, https://github.com/qgis/QGIS/issues/38845, https://trac.osgeo.org/osgeo4w/ticket/641

You can workaround the issue editing the file qgis-bin-g7.env and removing the string ";C:\Program Files\RStudio\bin" (or whatever is the RStudio installation folder in your system) from the PATH variable string.

**Comment by ecodiv** [comment]
@agiudiceandrea thanks, that did the trick. Thanks!
