### ISSUE TITLE
some problems for qgis project compiling

### ISSUE THREAD

**Issue by kuazhangxiaoai** [qgis/QGIS#39322]
I have 8 problems for qgis project compiling ,as following :

![error_list](https://user-images.githubusercontent.com/54108453/95708802-c337c200-0c8f-11eb-9f24-9cc031f4236a.PNG)

![error_list](https://user-images.githubusercontent.com/54108453/95708831-dd71a000-0c8f-11eb-8fe5-9f4ebe6d57c1.PNG)

Thanks for your answers of one or more of all errors.

**Comment by gioman** [comment]
@kuazhangxiaoai please ask questions on the developers mailing list. Or file tickets following the guidelines/instructions.
