### ISSUE TITLE
Can't Copy Columns from Attribute Table in QGIS 3.14

### ISSUE THREAD

**Issue by ar-siddiqui** [qgis/QGIS#39331]
**Describe the bug**
I want to copy only visible columns from Attribute Table into Excel, this used to work in previous QGIS versions but is not working in 3.14.

**How to Reproduce**

1. Go to 'Attribute Table of any layer'
2. Right-click any column heading and click organize columns, turn off few columns.
3. Now do Ctrl C and paste in Excel, it will not work
4. If you go to canvas and ctrl C there, it will copy all columns, not just the selected one.

**QGIS and OS versions**

QGIS version | 3.14.16-Pi | QGIS code revision | df27394552
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | ClipMultipleLayers; curve_number_generator; MapsPrinter; mapswipetool_plugin; MemoryLayerSaver; MultipleLayerSelection; multiple_layers_edit; plugin_reloader; profiletool; qgis_resource_sharing; searchlayers; send2google_earth; StreetView; valuetool; db_manager; processing

**Comment by gioman** [comment]
>  this used to work in previous QGIS version

@ar-siddiqui 3.10? earlier?

**Comment by ar-siddiqui** [comment]
Yes it used to work in 3.10 and earlier

**Comment by Pedro-Murteira** [comment]
@ar-siddiqui I can't replicate this issue on QGIS 3.22.2, are you still having this problem?

**Comment by ar-siddiqui** [comment]
I can't replicate either on QGIS 3.16.12 as well, this might have been fixed.
