### ISSUE TITLE
Drop field(s) - add option to drop all fields except selected field(s)

### ISSUE THREAD

**Issue by pathmapper** [qgis/QGIS#39345]
**Feature description**

`Drop field(s)` - add option to drop all fields except selected field(s).

Implementation could be a dropdown for the same input with

- Field(s) to drop (default - to keep compatibility with existing models)
- Field(s) to keep

**Additional context**

This would be especially useful when using `Drop field(s)` in models where one vector field input would be used for several algorithms.

There are workarounds available, but these are having drawbacks:
https://gis.stackexchange.com/a/376229
https://gis.stackexchange.com/q/375494

**Comment by root676** [comment]
You might comment on this open PR: #39114 

It implements your feature request (at least partially).

**Comment by pathmapper** [comment]
Thanks for pointing me to the PR @root676, I've searched for related issues only.

Don't know if this issue should remain open until the PR is merged, please feel free to close here.

**Comment by pathmapper** [comment]
https://github.com/qgis/QGIS/pull/40225 is merged.
