### ISSUE TITLE
Runtime Error While Executing Python Code

### ISSUE THREAD

**Issue by Stevenj279** [qgis/QGIS#39377]
This evening when I opened QGIS' "Settings", "Options" to check the "Rendering" settings, I didn't make any changes and then clicked on"OK" to exit. The window closed and the error message below immediately popped up. Restarting QGIS and/or  rebooting the PC has no effect - This error is constant.  Of note is that I've been using QGIS for over a year or two, and this was the first time I'd opened the Settings - Options tabs. I'm assuming (hoping) that this is a minor bug and that it is not having any effects on my GIS projects in the background that I'm not aware of. Error message follows:

An error has occurred while executing Python code: 

RuntimeError: wrapped C/C++ object of type DemShadingAlgorithm has been deleted 
Traceback (most recent call last):
  File "C:/Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\TerrainShading\dem_shading_provider.py", line 80, in loadAlgorithms
    self.addAlgorithm( alg )
RuntimeError: wrapped C/C++ object of type DemShadingAlgorithm has been deleted

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.12.3-București București, 8234261527 

Python Path:
C:/Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\TerrainShading
C:/PROGRA~1/QGIS3~1.12/apps/qgis/./python
C:/Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.12/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS3~1.12\apps\Python37
C:\PROGRA~1\QGIS3~1.12\apps\Python37\Scripts
C:\Program Files\QGIS 3.12\bin\python37.zip
C:\PROGRA~1\QGIS3~1.12\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.12\apps\Python37\lib
C:\Program Files\QGIS 3.12\bin
C:\PROGRA~1\QGIS3~1.12\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.12\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.12\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.12\apps\Python37\lib\site-packages\Pythonwin
C:/Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python
.
C:/Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Video_UAV_Tracker
C:\Users\User\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
C:\Users\User\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins

====
QGIS "About" table:

QGIS version
3.12.3-București
QGIS code revision
8234261527
Compiled against Qt 5.11.2
Running against Qt 5.11.2
Compiled against GDAL/OGR 3.0.4
Running against GDAL/OGR 3.0.4
Compiled against GEOS 3.8.1-CAPI-1.13.3
Running against GEOS 3.8.1-CAPI-1.13.3
Compiled against SQLite 3.29.0
Running against SQLite 3.29.0
PostgreSQL Client Version 11.5
SpatiaLite Version 4.3.0
QWT Version 6.1.3
QScintilla2 Version 2.10.8
Compiled against PROJ 6.3.2
Running against PROJ Rel. 6.3.2, May 1st, 2020
OS Version Windows 7 Pro SP 1 (6.1) 64 bit

Active python plugins
CityJSON-loader; 
FreehandRasterGeoreferencer; 
gimpselectionfeature_plugin; 
kmltools; 
kml_style_importer; 
latlontools; 
LayerMetadataSearch; 
map-coords-plugin; 
Qgis2threejs; 
searchlayers; 
SRTM-Downloader; 
TerrainShading; 
VectorBender; 
Video_UAV_Tracker; 
db_manager; 
processing

**Comment by alexbruy** [comment]
Please try with clean profile and no 3rd party plugins installed.

**Comment by roya0045** [comment]
This seems to be a plugin error entirely.

**Comment by gioman** [comment]
Closing for lack of feedback.
