### ISSUE TITLE
Oracle Error: ORA-01000: maximum open cursors exceeded

### ISSUE THREAD

**Issue by Crapaud04** [qgis/QGIS#39370]
In QGIS 3.12 and 3.14, there is a bug related to layer opening on a spatial Oracle database.
After a certain amount of layer manipulation, I have no more data and in the error messages from Oracle in QGIS I got this message.

```
Error: ORA-01000: maximum number of open cursors exceeded
              Cannot execute this declaration 
```

I tested on old version like 3.10 and I don't have the problem.

**Comment by Jean-Roc** [comment]
What is our Oracle version ? Can you give us steps to reproduce it ?

**Comment by Crapaud04** [comment]
Version Oracle : Oracle Database 11g Release 11.1.0.7.0 - Production

Step 1 : Add layers Oracle
Step 2 : Change layer styling  or maps deplacement
Step 3 : After multiple action such as Step 2, Layers is blank no data
Step 4 : In the QGIS Oracle log

`2020-10-15T15:59:01     WARNING    Fetching features failed.
             SQL: SELECT "GEOMETRIE","CLEGCES","ANOMALIES_2017" FROM "DBO"."S04_HYDRANT_PT_EAU" "FEATUREREQUEST" WHERE sdo_filter("GEOMETRIE",mdsys.sdo_geometry(2003,:a,NULL,mdsys.sdo_elem_info_array(1,1003,3),mdsys.sdo_ordinate_array(:bb,:bc,:bd,:be)))='TRUE'
             Error: ORA-01000: maximum number of open cursors exceeded
             Unable to execute statement `

Between step 2 and 3, in the QGIS Oracle log I got the message that I have that in 3.12 and 3.14.

`2020-10-15T15:54:39     WARNING    Fetching features failed.
             SQL: SELECT "GEOMETRIE","CLEGCES" FROM "DBO"."S04_GAZ_PONCT" "FEATUREREQUEST" WHERE sdo_filter("GEOMETRIE",mdsys.sdo_geometry(2003,:a,NULL,mdsys.sdo_elem_info_array(1,1003,3),mdsys.sdo_ordinate_array(:bb,:bc,:bd,:be)))='TRUE'
             Error: ORA-01426: numeric overflow
             Unable to execute statement`

But i can open a new QGIS, in the same time and is possible add layers Oracle in the new project.

**Comment by Crapaud04** [comment]
The bug is still present in version 3.16.0.

**Comment by jmonticolo** [comment]
I got the same error :
```
WARNING Fetching features failed. SQL:SELECT "GEOM","pk" FROM "MY_SCHEMA"."QGIS_POINT_DATA" "FEATUREREQUEST" WHERE sdo_filter("GEOM",mdsys.sdo_geometry(2003,:a,NULL,mdsys.sdo_elem_info_array(1,1003,3),mdsys.sdo_ordinate_array(:bb,:bc,:bd,:be)))='TRUE' AND (mod("FEATUREREQUEST"."GEOM".sdo_gtype,100) IN (1,5))
             Erreur: ORA-01426: numeric overflow
```

- QGIS 3.18.3
- OS : Windows 10
- Oracle instant client 12.1.0.1.0-1
- Oracle version :
```sql
SELECT * FROM v$version WHERE banner LIKE 'Oracle%';
-- Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production
```

- Test data (inspired from QGIS Oracle provider test data) :
```sql
-- DROP TABLE MY_SCHEMA.QGIS_POINT_DATA;
-- DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'POINT_DATA' AND COLUMN_NAME = 'GEOM';
-- COMMIT;
CREATE TABLE MY_SCHEMA.QGIS_POINT_DATA ("pk" INTEGER PRIMARY KEY, GEOM SDO_GEOMETRY);
INSERT INTO MY_SCHEMA.QGIS_POINT_DATA ("pk", GEOM)
 SELECT 0, SDO_GEOMETRY( 2001, 2154, SDO_POINT_TYPE(600000, 6810000, NULL), NULL, NULL) from dual UNION ALL
 SELECT 1, SDO_GEOMETRY( 2001, 2154, SDO_POINT_TYPE(600100, 6810100, NULL), NULL, NULL) from dual UNION ALL
 SELECT 2, SDO_GEOMETRY( 2001, 2154, SDO_POINT_TYPE(600200, 6810200, NULL), NULL, NULL) from dual;

INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME, COLUMN_NAME, DIMINFO, SRID) VALUES ( 'POINT_DATA', 'GEOM', SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X',592196.997,6806854.997,0.001),SDO_DIM_ELEMENT('Y',723762.003,6890713.003,0.001)),2154);
COMMIT;
```

The bug doesn't occur with WGS 84 (EPSG: 4326) point data.

1. Create the test data table in a new project
2. Open QGIS and load the test data table `QGIS_POINT_DATA`
3. Zoom to layer. The 3 points are displayed but in the lower right corner, the QGIS project CRS is unknown.
4. Select the right CRS `RGF 93 / Lambert-93` (EPSG: 2154), then the points disappear and a list of Oracle error ` WARNING Fetching features failed.` appear.

**Comment by jmonticolo** [comment]
Just installed and tested on the new 3.20.0 version and the bug is fixed, all clear for me !
