### ISSUE TITLE
Measurement tool gives wrong numbers

### ISSUE THREAD

**Issue by rikicarra** [qgis/QGIS#39374]
Using QGis 3.14.16 on iMac. My current project is on EPSG3857

Using the Measurement Tool I get wrong numbers, if the real distance is 10 m I get 14 m from the linear measurement tool. If I measure an area the measurement is about twice the real. If I interrogate a polygon I get the right area, as such I suppose it's a bug of the Measurement Tool.

**Comment by gioman** [comment]
> EPSG3857

@rikicarra The google/pseudo mercator CRS is not one you can rely on for precise measurements.
