### ISSUE TITLE
QGIS crash on creating a geopackage including a coordinate trasformation of the raster tiles

### ISSUE THREAD

**Issue by arinissinen** [qgis/QGIS#39376]
## User Feedback

I am having four raster tiles in EPSG:3067, and I create a virtual raster to join them. Next I want to save the virtual raster into a geopackage having coordinate system EPSG:3857.

It appears that trying to save the geopackage and enforce a coordinate transformation in the process shall crash the software.

## Report Details

*Crash ID*: de13be2a3f01cec4b12e9b0211da1bf5ded28dd7

*Stack Trace*
<pre>
QgsRasterFileWriter::writeImageRaster :
QgsRasterFileWriter::writeRaster :
QgsRasterFileWriterTask::run :
QgsTask::start :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.8.3-Zanzibar
QGIS code revision: 685d8b15d2
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by nyalldawson** [comment]
Version 3.8 is no longer supported. Please upgrade to a current release and retest.
