### ISSUE TITLE
Field calculator processing algorithm lost field name in existing model

### ISSUE THREAD

**Issue by uclaros** [qgis/QGIS#39387]
**Describe the bug**
I have a model created some month ago that contains a few *Field Calculator* algorithms. The resulting field name is blank if I try to run the model with master 69faea81d9, causing the model to fail.

In older version:
![image](https://user-images.githubusercontent.com/11358178/96097884-2a48b700-0eda-11eb-9b5a-3a650d0b9205.png)

In 69faea81d9:
![image](https://user-images.githubusercontent.com/11358178/96098059-5d8b4600-0eda-11eb-8d64-0e5160602fca.png)

This is caused by the c++ port of the algorithm and the UX changes in #38695.
Ping @suricactus

**Comment by suricactus** [comment]
Thanks for the report. I will check why it went wrong now.

**Comment by suricactus** [comment]
@uclaros is it possible to share the model to ease my life a bit :)

**Comment by uclaros** [comment]
Sure!
Here is a simple case failing.
[temp_model.model3.zip](https://github.com/qgis/QGIS/files/5383633/temp_model.model3.zip)
