### ISSUE TITLE
Once mesh contour rendering is disabled, it can't be enabled again

### ISSUE THREAD

**Issue by timlinux** [qgis/QGIS#39394]
Problem:

If I drag and drop the attached mesh into QGIS, it defaults to contour symbology (yay!)

[LionsHeadMeshs.zip](https://github.com/qgis/QGIS/files/5385112/LionsHeadMeshs.zip)

But if you uncheck contour rendering, there is no way to re-enable it again.

![mesh-contour-render-issue](https://user-images.githubusercontent.com/178003/96132186-01ccb700-0ef2-11eb-9f10-ecfe9ac1e949.gif)

cc @vcloarec

**Comment by PeterPetrik** [comment]
it can be enabled from the general tab...

**Comment by timlinux** [comment]
Thank you @PeterPetrik. For those following along at home, this is the workflow for re-enabling it.

![mesh-contours](https://user-images.githubusercontent.com/178003/96137828-08a8f900-0ef5-11eb-8c15-4d8fc823a1f4.gif)

**Comment by AlisterH** [comment]
FWIW the discoverability of this is a massive "papercut".
Does the checkbox **really** need to be disabled when you turn off contours?
Even though I've seen this previously, when someone asked me for help with it today I couldn't remember it at all...
