### ISSUE TITLE
Identify Results of Mesh layer depend on Temporal Controller status?

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS#39396]
To me something does not seem to be very consequent when you identify meshes in a Mesh layer:

If I load a Mesh layer (holding more then 20 'groups/layers/dimensions, or what you call those'...
And style one of those groups I want to view.
And activate the identify tool to click in one of the faces, I will see (rightfully) ONLY the activated/visible group.

![Screenshot-20201015170644-837x507](https://user-images.githubusercontent.com/731673/96149110-3d26b000-0f09-11eb-8f45-0067c0e9010d.png)

But if I make the Temporal Controller active (that netcdf HAS a time dimension), and again identify the same face, the Identify Results panel is filled with ALL groups I have in the netcdf?

![Screenshot-20201015170735-835x992](https://user-images.githubusercontent.com/731673/96149276-6a735e00-0f09-11eb-96c8-0d0a6d57453b.png)

That seems not very consequent? I think that the identify tool should either always ONLY show the visible/active group, OR always ALL groups.
Note that changing the 'Mode' ('Current Layer', 'Top Down' etc) do NOT change the behaviour.
Another note: it IS or can be helpfull to see the face information of all groups!  Maybe an idea would be to show them all in the Top Down* modes? OR create an extra option in the little settings tool?

Or am I missing some deeper insight in the combination of Temporal Controller and Mesh layers?

PS I cannot attach the netcdf here in public, but I'm happy to make it available for anybody if needed.

**Comment by PeterPetrik** [comment]
<img width="1018" alt="Screenshot 2020-12-01 at 15 20 03" src="https://user-images.githubusercontent.com/804608/100752285-b52d3480-33e8-11eb-860e-1186912bbfd3.png">

I think the is by design of things. If you have temporal controller on, you see in identify all dataset group that are present in the current time range. if you have it off, only the dataset group and dataset(time) that is set in static dataset settings is shown (other datasets are hidden).

Only possible improvement would be possiblity to add a new column to this "available datasets"  that "possible to query/identify" similar to what we have for layers.

**Comment by vcloarec** [comment]
The logic is:
- In static mode (temporal controller off **or** layer forced to be static in the source tab of mesh layer properties): only the static dataset are displayed in the identify map tool. Indeed temporal dataset group could not be defined if time is not defined...
- In temporal mode (temporal controller on **and** layer **not** forced to be static in the source tab of mesh layer properties: all dataset groups available for the time step are displayed in the identify map tool

Actually, when you disable dataset groups in this source tab of the mesh layer layer properties, disabled dataset groups are not available anymore for displaying in the canvas. The logic would require that disabling dataset group would lead to not displaying also in the identify map tool... That is not the case but this PR fix this issue :#40388
