### ISSUE TITLE
TIN Mesh Creation processing alg does not correctly apply CRS

### ISSUE THREAD

**Issue by timlinux** [qgis/QGIS#39395]
When I create a new mesh from a point collection, and specify the output CRS, the generated mesh loads but indicates that it has no valid CRS. The sample dataset I used is provided as an attachment to https://github.com/qgis/QGIS/issues/39394 so I won't replicate it here. Here is the workflow I used to create a grid:

![mesh-crs-issue](https://user-images.githubusercontent.com/178003/96136441-b4e9e000-0ef3-11eb-88e0-31f3da593149.gif)

After the grid is added to the canvas, it indicates that it has no valid CRS.

CC @vcloarec

**Comment by vcloarec** [comment]
I think 2DM format does not support CRS (not very sure, I have to check...)
Can you try with UGRID (best to use this one) or Selafin format?

**Comment by timlinux** [comment]
@vcloarec Hi!

> Can you try with UGRID (best to use this one) or Selafin format?

UGRID is not available as an option for me

2DM is the default - hence me using that

I tested Selafin and it creates a mesh which is completely flat!

![flat-mesh](https://user-images.githubusercontent.com/178003/96147009-d3090d80-0efe-11eb-9cf2-2aff5fe9714e.gif)

**Comment by vcloarec** [comment]
UGRID not available? odd... @PeterPetrik, is UGRID format depends on platform?

And Selafin format does not support Z value vertices of the mesh...  Z value are stored as a dataset group. As 3D terrain is built with the Z value of mesh vertices, Terrain from Selafin format are flat... For now the workaround for this format is to display in 3D the layer not as Terrain but as layer dataset (activated in the 3D tab of the layer). In this case, it is dataset groups that are used to built the 3D view.

I am thinking to add an option to choose a dataset group for Terrain, but not for now...

**Comment by timlinux** [comment]
@vcloarec hmm I have tried your suggestions, it also doesnt seem to work.

![flat-selafin](https://user-images.githubusercontent.com/178003/96154228-7e699080-0f06-11eb-9ccd-128a8d3fb92d.gif)

**Comment by timlinux** [comment]
@vcloarec hmm I have tried your suggestions, it also doesnt seem to work.

![flat-selafin](https://user-images.githubusercontent.com/178003/96154228-7e699080-0f06-11eb-9ccd-128a8d3fb92d.gif)


[MeshScreencast.zip](https://github.com/qgis/QGIS/files/5391593/MeshScreencast.zip)

**Comment by timlinux** [comment]
Here is the same dataset with 3d point geometries.

[MeshScreencastZ.zip](https://github.com/qgis/QGIS/files/5391648/MeshScreencastZ.zip)

**Comment by vcloarec** [comment]
@timlinux , can we close this issue now?
