### ISSUE TITLE
QGIS Processing Plugin is not working in Windows10. I have tried reinstalling 3.10 and 3.14 versions of qgis but the problem remains same.

### ISSUE THREAD

**Issue by RajRj** [qgis/QGIS#39418]
When I activate the Processing plugin under the Plugins, it is showing the following crash report.

QObject::thread :
messageOutputViewer_ qgisapp.cpp:578
meth_QgsMessageOutput_createMessageOutput sip_corepart4.cpp:179729
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyErr_PrintEx :
sipQgsProcessingAlgorithm::name sip_corepart2.cpp:77596
meth_QgsProcessingAlgorithm_name sip_corepart2.cpp:77965
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_sip :
sipVH__core_1 sip_corepart0.cpp:22376
sipQgsProcessingProvider::loadAlgorithms sip_corepart1.cpp:284215
QgsProcessingProvider::refreshAlgorithms qgsprocessingprovider.cpp:76
meth_QgsProcessingProvider_refreshAlgorithms sip_corepart1.cpp:286079
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_sip :
sipVH__core_27 sip_corepart0.cpp:22178
sipQgsProcessingProvider::load sip_corepart1.cpp:284248
QgsProcessingRegistry::addProvider qgsprocessingregistry.cpp:101
meth_QgsProcessingRegistry_addProvider sip_corepart1.cpp:282542
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyTuple_New :
PyObject_FastCallKeywords :
PyObject_FastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyEval_EvalCodeEx :
PyEval_EvalCode :
PyArena_Free :
PyRun_StringFlags :
QgsPythonUtilsImpl::evalString qgspythonutilsimpl.cpp:529
QgsPythonUtilsImpl::startPlugin qgspythonutilsimpl.cpp:627
QgsPluginRegistry::loadPythonPlugin qgspluginregistry.cpp:314
QgsPluginManager::loadPlugin qgspluginmanager.cpp:286
QgsPluginManager::pluginItemChanged qgspluginmanager.cpp:670
QMetaObject::activate :
QStandardItemModel::`default constructor closure' :
QMetaObject::activate :
QAbstractItemModel::dataChanged :
QStandardItemModel::itemChanged :
QStandardItem::setData :
QStandardItemModel::setData :
QSortFilterProxyModel::setData :
QStyledItemDelegate::editorEvent :
QAbstractItemView::selectionModel :
QAbstractItemView::edit :
QAbstractItemView::mouseReleaseEvent :
QListView::mouseReleaseEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:439
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:439
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
meth_QgsPluginManagerInterface_showPluginManager sip_guipart3.cpp:251028
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyEval_EvalCodeEx :
PyEval_EvalCode :
PyArena_Free :
PyRun_StringFlags :
QgsPythonUtilsImpl::runStringUnsafe qgspythonutilsimpl.cpp:307
QgsPythonUtilsImpl::runString qgspythonutilsimpl.cpp:324
QgsPythonRunnerImpl::runCommand qgisapp.cpp:11784
QgsPythonRunner::run qgspythonrunner.cpp:33
QgisApp::showPluginManager qgisapp.cpp:11762
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:439
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:439
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1618
BaseThreadInitThunk :
RtlUserThreadStart :

**Comment by DelazJ** [comment]
@RajRj Could you try with a new [user profile](https://docs.qgis.org/3.10/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)?

**Comment by roya0045** [comment]
Need more info on version, OS, instal method, etc

**Comment by gioman** [comment]
@RajRj beside the missing info as noted by @roya0045 please also try with a new QGIS profile.

**Comment by RajRj** [comment]
Thank you everyone. The issue got solved. It was due to one of my recent scripts saved under the scripts folder. Once I removed all these scripts, the processing plugin started working fine.
