### ISSUE TITLE
New Map View options should be a checkbox instead of radio buttons 

### ISSUE THREAD

**Issue by arno974** [qgis/QGIS#39423]
When creating a New Map View the synchronize options are displayed as a radio buttons. As a result, once one of the options is selected, it is no longer possible to desynchronize the new map from the main map. Does it make sense to change this radio buttons by a mutually inclusive checkbox ?

![image](https://user-images.githubusercontent.com/425243/96239253-87af3780-0fb0-11eb-801f-5bb4c0a935e5.png)

**Comment by Pedro-Murteira** [comment]
Still true on QGIS 3.16.14 and 3.22.1.

**Comment by alexbruy** [comment]
Fixed in master
