### ISSUE TITLE
Date field NULL in QGIS, but ok in postgis table

### ISSUE THREAD

**Issue by Djedouas** [qgis/QGIS#39420]
I have a postgis table with a date field.
When I open the attribute table or the form on this table in QGIS, all the dates are NULL.
When I look at the table content with PgAdmin or DBManager plugin in QGIS, all the dates are filled in with their values.

On the attribute table or the form I can set a date, but after saving the layer and refreshing the attribute table, the date becomes NULL again, but it has been correctly updated in postgres table!

Tested on QGIS `3.4.13`, `3.10.10`, `3.14.16`.

**Before in QGIS**
![image](https://user-images.githubusercontent.com/34267385/96228308-b79d1180-0f95-11eb-806b-e8c2c1d23030.png)

**Before in PgAdmin**
![image](https://user-images.githubusercontent.com/34267385/96228679-2c704b80-0f96-11eb-964a-a356cced7db1.png)

**Editing in QGIS**
![image](https://user-images.githubusercontent.com/34267385/96228359-c8e61e00-0f95-11eb-8cae-fad068358dd3.png)

**Saved in QGIS, before refreshing**
![image](https://user-images.githubusercontent.com/34267385/96228391-d1d6ef80-0f95-11eb-926a-7f5659dec405.png)

**After refreshing the attribute table: dates are NULL**
![image](https://user-images.githubusercontent.com/34267385/96228450-e915dd00-0f95-11eb-8f24-cbe8465202a3.png)

**In PgAdmin: the date has been updated**
![image](https://user-images.githubusercontent.com/34267385/96228887-76593180-0f96-11eb-9b79-5d21d10c0914.png)

**Comment by gioman** [comment]
@Djedouas jas the column being given the "date/time" widget in QGIS? if yes does it makes any difference if you reset it to "text edit"? What version of PostgreSQL/PostGIS are you using? Can you attach a sample (dump) of your table (at least the structure)?

**Comment by Djedouas** [comment]
Thanks @gioman 😃 
Yes the column has been given the "date/time" widget (I set the date with the mini-calendar).
I set it to "text edit" and I did all the tests again, on all 3 QGIS versions, and I still have exactly the same results/behavior.

**PostGIS version from `SELECT PostGIS_Version();`:**
2.3 USE_GEOS=1 USE_PROJ=1 USE_STATS=1

**Table structure and data:**
```
create table test_date_qgis (
    id_demande SERIAL PRIMARY KEY NOT NULL,
    geom_demande geometry(Point,2154),
    date_demande date
);
insert into test_date_qgis values (2, ST_GeometryFromText('POINT(0 0)', 2154), '1111-11-11')
```

**Comment by gioman** [comment]
@Djedouas seems fine here on 3.10 on Ubuntu 20.04

![Screenshot_20201016_140141](https://user-images.githubusercontent.com/1951107/96261302-3014ca00-0fb8-11eb-8b7c-2ab4bb5fedb9.png)

**Comment by Djedouas** [comment]
Indeed! :/
I'm on Windows 10

**Comment by Djedouas** [comment]
Tested on Windows 7, same problem

**Comment by Djedouas** [comment]
Tested on a geopackage export of the table, no problem, the date (exported as NULL) can be edited and saved and recovered.

**Comment by gioman** [comment]
>  I'm on Windows 10

@Djedouas Windows fine too here

![Screenshot_20201016_141435](https://user-images.githubusercontent.com/1951107/96262651-0066c180-0fba-11eb-97d5-69a2cc955801.png)

**Comment by gioman** [comment]
> Tested on Windows 7, same problem

@Djedouas try with a new QGIS profile.

**Comment by Djedouas** [comment]
Created a brand new QGIS profile, on brand newly installed QGIS 3.14.
Still having the problem 😢 

![image](https://user-images.githubusercontent.com/34267385/96263498-5be97d00-0fc3-11eb-9ae7-1f66a5bebfb6.png)
![image](https://user-images.githubusercontent.com/34267385/96263600-7a4f7880-0fc3-11eb-8c81-20d8b3138148.png)

**Comment by gioman** [comment]
@Djedouas try a different machine.

**Comment by Djedouas** [comment]
> 
> 
> @Djedouas try a different machine.

The test I did on Windows 7 was on a different machine already.
I've just tested on another Windows 10 machine, still having the problem.

I'm on a company computer, but I can't guess what's different than your configuration.
Can the extensions create the problem? On DBManager extension I can see the dates...

![image](https://user-images.githubusercontent.com/34267385/96265202-73c20080-0fc5-11eb-934e-9e0a33052a73.png)

**Comment by gioman** [comment]
>  but I can't guess what's different than your configuration

@gioman for a start the language: I can't see how is related but anyway is a difference, is all in English, included the OS.

> Can the installed extensions create the problem?

Have you really tried a new QGIS profile, without installing in it any 3rd party plugin?

**Comment by Djedouas** [comment]
> Have you really tried a new QGIS profile, without installing in it any 3rd party plugin?

Yes, brand new QGIS profile especially for testing this

**Comment by Djedouas** [comment]
> @gioman for a start the language: I can't see how is related but anyway is a difference, is all in English, included the OS.

I set the locale to EN_US in the preferences, and the language to EN_US too, in the override system locale section, in General.
After restart, still same problem.

**Comment by gioman** [comment]
I have no other ideas on the possible cause, let's see if other confirm.

**Comment by Djedouas** [comment]
Resolved!

In the `postgres.conf` file, I changed `datestyle='sql, dmy'` into `datestyle='iso, dmy'` and now everything works correctly!
Thanks @gioman for helping, I had the idea look at my postgres conf seeing that the issue was not reproductible.
