### ISSUE TITLE
Newly created map in Print Layout has no id

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#39425]
**Describe the bug**
A newly created map in a Print Layout has no `id`. This makes it impossible to use expressions referencing it unless the user renames the map (that will update the id) or manually set an `id`.

**How to Reproduce**

1. New Print Layout
2. Add Map
3. Map is automatically named "Map 1" as shown in the items list in the top right of the Layout window, looking at the variables however it seems to have a blank `id`.
4. Add a label
5. Use e.g. `map_get( item_variables('Map 1'), 'map_scale')` as expression for it
6. No label will be shown
7. Rename the map to "Map 0" and update the expression accordingly
8. The label will show the scale

**QGIS and OS versions**

QGIS version | 3.15.0-Master | QGIS code revision | b3066af303
-- | -- | -- | --
Compiled against Qt | 5.15.1 | Running against Qt | 5.15.1
Compiled against GDAL/OGR | 3.2.0dev-84d747c0ef-dirty | Running against GDAL/OGR | 3.2.0dev-84d747c0ef-dirty
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.33.0 | Running against SQLite | 3.33.0
PostgreSQL Client Version | 12.4 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.5 | QScintilla2 Version | 2.11.5
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Arch Linux

**Comment by justmematej** [comment]
Works perfectly! Thanks 👍

**Comment by roya0045** [comment]
Yep id seems to be faked for display
https://github.com/qgis/QGIS/blob/7b28cc6b0c0aa5cee8c7ef0240191500a844d22a/src/core/layout/qgslayoutitemmap.cpp#L142

**Comment by nyalldawson** [comment]
This was fixed by https://github.com/qgis/QGIS/pull/40928
