### ISSUE TITLE
Raster > Miscellaneous > Merge fails

### ISSUE THREAD

**Issue by nevisnoel** [qgis/QGIS#39449]
With recent nightly builds the raster merge command fails.
[Traceback.docx](https://github.com/qgis/QGIS/files/5397618/Traceback.docx)

**Comment by gioman** [comment]
@nevisnoel this report is incomplete, please add the requested infos.

**Comment by gioman** [comment]
**Describe the bug**


**How to Reproduce**



**QGIS and OS versions**



**Additional context**

**Comment by roya0045** [comment]
Are they in the same crs?

**Comment by nevisnoel** [comment]
**Describe the bug**

Whenever I load OS OpenData DEM files into QGIS they display correctly, but when I try to merge multiple files using Raster > Miscellaneous > Merge I always get an error message. It happens with both ASC files and also GeoTIFFs.

The following layers were not correctly generated.
• /Users/noel/Desktop/MERGED/MERGED.tif


**How to Reproduce**

It happens every time I try to carry out this procedure with DEM files.


QGIS and OS versions

QGIS 3.15.0-Master (nightly build)

QGIS version: 3.15.0-Master
QGIS code revision: 0a5321abf8
Qt version: 5.14.2
GDAL version: 3.1.2
GEOS version: 3.8.1-CAPI-1.13.3
PROJ version: Rel. 6.3.2, May 1st, 2020

macOS Mojave 10.14.6


**Additional context**

I also had the QGIS 3.14.16 'Pi' installed.  I have now deleted this, but the merge process still fails.

I'm working with OS OpenData ASC files. They are all EPSG 27700 (Brit Nat Grid).

**Comment by roya0045** [comment]
What if you convert them to something like tiff, firsthand and then merge?

**Comment by nevisnoel** [comment]
The same result with GeoTIFF files. No file is created.

The following layers were not correctly generated.
• /Users/noel/Desktop/Test/Merged.tif

**Comment by gioman** [comment]
macOS only issue?

**Comment by nevisnoel** [comment]
Yes. That seems to be the case. I installed Parallels on my macOS iMac and installed the latest Windows version of the nightly build of QGIS and that works without any problems.
I also discovered that Raster > Projections > Warp (Reproject) ... also fails on the macOS version, but works OK on the Windows version.
[Reproject log.docx](https://github.com/qgis/QGIS/files/5432651/Reproject.log.docx)

**Comment by alexbruy** [comment]
Looking at the log, it is more like packaging or installation issue than QGIS bug. It failed to load `osgeo` Python module. Does it work from the command-line?

**Comment by gioman** [comment]
@nevisnoel works fine here with master downloaded from https://qgis.org/en/site/getinvolved/mailinglists.html and using macOS 10.15.7

**Comment by nevisnoel** [comment]
Thanks. There is a new master up today, which now works fine on macOS Catalina 10.15.7. (Yesterday's link was still QGIS 3.14 and gave the errors.) So this is now sorted for QGIS 3.16 with macOS Catalina.
However, it still gives the same errors with macOS Mojave.
I'll stick with macOS Catalina!

**Comment by gioman** [comment]
Also because we probably (not 100% sure) don't support macOS < catalina.
