### ISSUE TITLE
Using the WMS-provider.inspect as feature in pyqgis gives: "unable to convert a C++ 'QgsFeatureStoreList' instance to a Python object"

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS#39479]
plz see:
https://lists.osgeo.org/pipermail/qgis-user/2020-October/046834.html

in short:
- users want to run a script to fire WMS-GetFeatureInfo-requests in pyQGIS
- but the layer.dataProvider().identify in combi with IdentifyFormatFeature returns a result which cannot (yet?) be used in PyQGIS:

```TypeError: unable to convert a C++ 'QgsFeatureStoreList' instance to a Python object```
or:
```cannot unpack non-iterable QgsRasterIdentifyResult object```

Is this missing some SIP magic? 
Or is this not supposed to work?

Note that 
https://docs.qgis.org/3.10/en/docs/pyqgis_developer_cookbook/raster.html#query-values
do not work on a WMS?

To reproduce:
```
l=qgis.utils.iface.addRasterLayer(
"crs=EPSG:28992&layers=Bebouwingvlak&styles=&format=image/png&url=https://geodata.nationaalgeoregister.nl/kadastralekaart/wms/v4_0?", # uri
"buildings", # name for layer (as seen in QGIS)
"wms" # dataprovider key
)

result = l.dataProvider().identify( QgsPointXY(104606,490213),
             QgsRaster.IdentifyFormatHtml,
             QgsRectangle(104391.1406077263819,490161.0749502293766,104899.6563292678911,490283.3410253541078),
             1465,
             352,
             96)     
print(result.results()[0])  # OK

result = l.dataProvider().identify( QgsPointXY(104606,490213),
             QgsRaster.IdentifyFormatText,
             QgsRectangle(104391.1406077263819,490161.0749502293766,104899.6563292678911,490283.3410253541078),
             1465,
             352,
             96)
print(result.results()[0])  # OK

result = l.dataProvider().identify( QgsPointXY(104606,490213),
             QgsRaster.IdentifyFormatFeature,
             QgsRectangle(104391.1406077263819,490161.0749502293766,104899.6563292678911,490283.3410253541078),
             1465,
             352,
             96)
print(result.results()[0])  # prints: unable to convert a C++ 'QgsFeatureStoreList' instance to a Python object

```

**Comment by agiudiceandrea** [comment]
> Note that
https://docs.qgis.org/3.10/en/docs/pyqgis_developer_cookbook/raster.html#query-values
do not work on a WMS?

Maybe it is due to the fact that this WMS server does not support the IdentifyValue capability?

**Comment by rduivenvoorde** [comment]
@agiudiceandrea I am not familiar with the IdentifyValue capability? Is this a new WMS request? 
Or do you mean 'getFeatureInfo'? Because that last one does definitly work. I think the problem that the short 'identify' and 'sample' versions do not work because a WMS always needs 'context', as in Width/Height and Bbox params?

**Comment by agiudiceandrea** [comment]
@rduivenvoorde, with your layer (and AFAIK generally with WMS layers) : `print(l.dataProvider().capabilities())` returns `928` (decimal) == 01110100000 (binary) which maps to:
Identify = True // at least one identify format supported
IdentifyValue = False // numerical values 
IdentifyText = True // WMS text 
IdentifyHtml = True // WMS HTML 
IdentifyFeature = True // WMS GML -> feature 

https://github.com/qgis/QGIS/blob/4f834cafb88780baa76cd02fbdee193435fea248/src/core/raster/qgsrasterinterface.h#L183-L196

This means that the WMS raster layer does not support QgsRaster::IdentifyFormatValue format so both identify() and sample() will fail: `QgsError: WMS provider Format not supported`

For a WCS layers, print(l.dataProvider().capabilities())` usually returns `98`, i.e. Identify = True, IdentifyValue = True.

**Comment by rduivenvoorde** [comment]
Cool. Thanks Nyall!
