### ISSUE TITLE
Add progress bar in field calculator when opened from attribute table or toolbar

### ISSUE THREAD

**Issue by nicogodet** [qgis/QGIS#39474]
**Feature description.**

Add progress bar in field calculator when opened from attribute table or toolbar.
![image](https://user-images.githubusercontent.com/39594821/96425072-e3213580-11fb-11eb-8eb6-f37833e2492f.png)

Progress is shown in Windows taskbar but not in field calculator window.
![image](https://user-images.githubusercontent.com/39594821/96430100-08b13d80-1202-11eb-82a1-6bc3281c7adc.png)

**Additional context**

None

**Comment by alexbruy** [comment]
Duplicates #15284?

**Comment by nicogodet** [comment]
@alexbruy Absolutely.
