### ISSUE TITLE
Unknown CRS for EPSG 2056

### ISSUE THREAD

**Issue by RAglx** [qgis/QGIS#39482]
Dear QGIS-Team,

If I add the attached shapefile to QGIS, it says "Unbekanntes KBS", even though
the WKT in the .prj file seems fine.

I tried to insert the WKT entries for LV95 from [epsg.io](//epsg.io/2056.wkt) and [spatialreference.org ](https://spatialreference.org/ref/epsg/ch1903-lv95/ogcwkt/) in the prj-file, but still no luck.

With QGIS 3.10.1-1 everything worked fine but from QGIS 3.10.2-2 on, it just doesn't work anymore.
Maybe it relates to this issue https://github.com/qgis/QGIS/issues/34993 ?
It still doesn't work with 3.14.0.

Below I posted the information for the last version it worked, and the
version it didn't work anymore.

I'm not sure if it's really a QGIS problem or has to do with a used library.
I have no deeper knowledge how all the things work together.

Thank you for looking into this.
Greets

**QGIS and OS versions**

Last working:

QGIS-Version | 3.10.1-A Coruña | QGIS-Codeversion | ef24c526da
-- | -- | -- | --
Kompiliert   gegen Qt | 05.11.2002 | Laufendes Qt | 05.11.2002
Kompiliert   mit GDAL/OGR | 3.0.2 | Läuft mit GDAL/OGR | 3.0.2
Kompiliert   mit GEOS | 3.8.0-CAPI-1.13.1 | Läuft mit GEOS | 3.8.0-CAPI-1.13.1
Kompiliert   mit SQLite | 3.29.0 | Läuft mit SQLite | 3.29.0
PostgreSQL-Client-Version | 11.5 | SpatiaLite-Version | 04.03.2000
QWT-Version | 06.01.2003 | QScintilla2-Version | 02.10.2008
Kompiliert   mit PROJ | 06.02.2001 | Läuft mit PROJ | Rel. 6.2.1, November 1st, 2019
BS-Version | Windows 10 (10.0)
Aktive Python-Erweiterungen | qgisnetworklogger;
quick_map_services;
db_manager;
MetaSearch;
processing

First not working:

QGIS-Version | 3.10.2-A Coruña | QGIS-Codeversion | d4cd3cfe5a
-- | -- | -- | --
Kompiliert   gegen Qt | 05.11.2002 | Laufendes Qt | 05.11.2002
Kompiliert   mit GDAL/OGR | 3.0.3 | Läuft mit GDAL/OGR | 3.0.3
Kompiliert   mit GEOS | 3.8.0-CAPI-1.13.1 | Läuft mit GEOS | 3.8.0-CAPI-1.13.1
Kompiliert   mit SQLite | 3.29.0 | Läuft mit SQLite | 3.29.0
PostgreSQL-Client-Version | 11.5 | SpatiaLite-Version | 04.03.2000
QWT-Version | 06.01.2003 | QScintilla2-Version | 02.10.2008
Kompiliert   mit PROJ | 06.03.2000 | Läuft mit PROJ | Rel. 6.3.0, January 1st, 2020
BS-Version | Windows 10 (10.0)
Aktive Python-Erweiterungen | qgisnetworklogger;
quick_map_services;
db_manager;
MetaSearch;
processing

[test.zip](https://github.com/qgis/QGIS/files/5402994/test.zip)

**Comment by nyalldawson** [comment]
@RAglx 
This CRS definition doesn't actually directly match EPSG:2056. It's a "bound crs of EPSG:2056", which isn't the same thing.

It should still appear and function correctly, it's just that recent QGIS versions are more picky about identifying CRS and now (correctly) don't match definitions like your one.
