### ISSUE TITLE
Edición de capas vectoriales provenientes de ArcGIS

### ISSUE THREAD

**Issue by Miriam-Heredia** [qgis/QGIS#39484]
Utilizando la versión 3.10 de QGIS al editar (generar o borrar) y guardar vectores de una capa que fue generada en ArcGIS, QGIS me muestra el siguiente error:

**Error 1 de ORG [3]: Failed to delete file C:/CartografiaQCU_ver3/01003001/Frente_de_Manzana.qix. Permission denied**

Después de mostrar ese error, cierro QGIS y observo que en la carpeta donde tengo la información genera un archivo con la extensión .qix del shape que edite.

Al abrirlo nuevamente, en la interfaz no se observan algunos vectores y en la tabla de atributos si.

![Error_QGIS_QIX](https://user-images.githubusercontent.com/73129916/96497968-0d312280-1211-11eb-9eab-f36446728248.jpg)

**Comment by gioman** [comment]
@Miriam-Heredia please file ticket in English (PS the qix file is the spatial index, you can remove it safely and regenerate it if necessary. QGIS do not generate it automatically as far as I know, you must do it manually in the layer properties).
