### ISSUE TITLE
Atlas tool contains some empty views, some data shown on multiple views

### ISSUE THREAD

**Issue by justmematej** [qgis/QGIS#39480]
Hello,

we would like to use Atlas tool to generate views similar to this:
![areas](https://user-images.githubusercontent.com/19887936/96463887-7de33980-1227-11eb-92a4-84b86469fc74.png)

We are getting some empty where there is nothing in the layer we select as a guidance and some parts of the input data is in multiple views, which doesn't make sense.
![image](https://user-images.githubusercontent.com/19887936/96464006-9ce1cb80-1227-11eb-8fd9-a7d589181a30.png)

Our load is to get fixed scale views (without empty/double views).

Thanks!

**Comment by gioman** [comment]
@justmematej please add all the requested info, like QGIS version and Operating system used.

Anyway here it would be much better if you could provide a sample project+data.

**Comment by gioman** [comment]
Not replicable here. Closing for lack of further feedback.
