### ISSUE TITLE
Not showing content of mbtiles

### ISSUE THREAD

**Issue by leon-faerber** [qgis/QGIS#39483]
The German „Bundesamt für Kartographie und Geodäsie“ provides mbtiles from their TopPlusOpen product (e.g. here: https://daten.gdz.bkg.bund.de/produkte/topplus_open/TopPlusOpen/aktuell/utm32s/).
Unfortunately these mbtile files can not be displayed by Qgis. They open without any error message, but no content is displayed.

**Comment by gioman** [comment]
@leon-faerber if it is raster tiles:

```
gdalinfo 3.mbtile 
ERROR 4: `3.mbtile' not recognized as a supported file format.
gdalinfo failed - unable to open '3.mbtile'.
```

if it is vector

```
ogrinfo -so 3.mbtile tiles
INFO: Open of `3.mbtile'
      using driver `SQLite' successful.

Layer name: tiles
Geometry: None
Feature Count: 1024
Layer SRS WKT:
(unknown)
FID Column = rowid
zoom_level: Integer (0.0)
tile_column: Integer (0.0)
tile_row: Integer (0.0)
tile_data: Binary (0.0)
last_modified: DateTime (0.0) DEFAULT (datetime('now','localtime'))
```


in both cases the problem seems to be the data not QGIS.

**Comment by gioman** [comment]
Closing for lack of feedback.

**Comment by kannes** [comment]
For anyone ending up here: Those ".mbtile" files are non-standard files in EPSG:25832 (created and used by MapProxy). GDAL/QGIS only knows how to handle MBTiles in EPSG:3857.

To even initially load these you have to rename the files to ".mbtiles".
