### ISSUE TITLE
Labels disappear from map

### ISSUE THREAD

**Issue by i-s-o** [qgis/QGIS#39490]
**Describe the bug**
Depending on the position of the layer on the map, some labels disappear. Note that even the candidate positions in label debug view don't show.

Another possible issue: some of the candidate label positions bunch up together in unexpected spots, other spots remain empty.
Another issue: the "Zoom Last" button doesn't go to the previous zoom level.
[I can open separate tickets for these other issues if there is a need for that]

**How to Reproduce**
[disappearing-labels.zip](https://github.com/qgis/QGIS/files/6127679/disappearing-labels.zip)
Using the project saved within the attached GPKG, move the map around, depending on the position of a feature within the canvas, some labels disappear:
![2020-10-19_20-15-40](https://user-images.githubusercontent.com/1661549/96531704-3b862080-1258-11eb-86b6-bcf652aedf75.gif)

**QGIS and OS versions**
3.10.10-2 (8b051b9a43), Windows 10
3.15.0-master (0a5321abf8), Ubuntu 20.04
3.19.0-master (3f5b16592), Windows 10

**Additional context**
Tested with clean profile, without any plugins.

**Comment by gioman** [comment]
FYI it happens only when using the "centroid > visible polygon" option is used, and certain portions of a polygon are visible. It also happens when using "free" for positioning. Not seems to happen when using "centroid > whole polygon". There are no geometry errors in the provided layer.

**Comment by strk** [comment]
How do I activate label debug view ?

**Comment by i-s-o** [comment]
> How do I activate label debug view ?

![image](https://user-images.githubusercontent.com/1661549/98038280-dc451600-1dea-11eb-8d86-2304691287a2.png)
![image](https://user-images.githubusercontent.com/1661549/98038301-e6671480-1dea-11eb-9f93-729435c86682.png)

**Comment by pjshelton** [comment]
Is #33560 related to this?

**Comment by nyalldawson** [comment]
This is no longer reproducible -- likely fixed in the recent GEOS releases.
