### ISSUE TITLE
QGIS 3.14.15 crashes upon exit

### ISSUE THREAD

**Issue by Nimrod51** [qgis/QGIS#39499]
Hi!
I'm facing the issue with  QGIS 3.14.15 consistently crashes upon exit, regardless of activity done (can also be a blank map).  I've tried uninstalling and re-installing QGIS, but problem persists.

Running Windows 10 64bit. 

Are there any workarounds?

Thanks,
Nimrod

Crash ID: 4615ef8c8bea964910debf5e20abe1edab2351c0

Stack Trace

QDockWidget::toggleViewAction :
QgisApp::removeDockWidget :
QgsPresetSchemeColorRamp::clone :
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyEval_EvalCodeEx :
PyEval_EvalCode :
PyArena_Free :
PyRun_StringFlags :
instance :
instance :
QgsPluginRegistry::unloadAll :
QgisApp::saveWindowState :
QMetaObject::activate :
QCoreApplicationPrivate::execCleanup :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.14.15-Pi
QGIS code revision: d5114d2cfa
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by Gustry** [comment]
You should try with a new QGIS profile.
https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles

**Comment by Nimrod51** [comment]
That really seems to have solved it, thanks for the super quick reply!  My best guess is something is wrong with one of the plugins I installed.  Starting a new session on Windows with a new profile was as simple as `qgis.bat --profile name`. Thanks again!
