### ISSUE TITLE
overlay_* returns element instead of a list of the element when limit:=1

### ISSUE THREAD

**Issue by nicogodet** [qgis/QGIS#39495]
### **Feature description.**

_**Actual behavior**_
`overlay_*('layer', expression, limit:=1)` returns `[element]`

_**Enhanced behavior**_
`overlay_*('layer', expression, limit:=1)` returns `element`

It could be more intuitive if it returns `element` instead of `[element]` when _limit_ is set to _1_
It would avoid using `overlay_*('layer', expression, limit:=1)[0]` 

### **Additional context**

None

**Comment by m-kuhn** [comment]
I can see where you are coming from.
On the other hand, the limit parameter can also be dynamic e.g. `overlay_*('layer', expression, limit:="number_of_trees")` which would be super hard to deal with the proposed change. To keep things simple I would prefer to keep as is.

**Comment by nyalldawson** [comment]
Agreed - if we change the return type dynamically then it'll be impossible to write robust expressions.
