### ISSUE TITLE
Crash on very long attribute values on mouse over in identify features widget

### ISSUE THREAD

**Issue by chau-intl** [qgis/QGIS#39494]
I have a PostGIS table with point features where one attribute value has a length of 127.073 characters.

Steps to reproduce:
- Add the PostGIS layer to QGIS.
- Inspect a feature.
- Place the cursor over the attribute value with the high character count.
=> QGIS crashes.

The crash is not caught, QGIS just dies.

I have tested on QGIS 3.15 (2626ad6130) on Windows 10 x64.

**Comment by gioman** [comment]
@chau-intl Any chance you can attach a small sample?

**Comment by chau-intl** [comment]
@gioman, I have created a [GeoPackage](https://github.com/qgis/QGIS/files/5407197/test_data.zip) with one point and one attribute value and (un)luckily the issue persist when using it instead of a PostGIS layer.

**Comment by gioman** [comment]
Seems ok on the latest 3.10 and 3.14, now testing master.

**Comment by gioman** [comment]
Master is also ok here, on Windows.

**Comment by chau-intl** [comment]
I have found this in the Windows Event Log / Application:

```
Faulting application name: qgis-dev-bin.exe, version: 0.0.0.0, time stamp: 0x5f8cfbf3
Faulting module name: ucrtbase.dll, version: 10.0.17763.719, time stamp: 0x15f8b9b3
Exception code: 0xc0000409
Fault offset: 0x000000000006e91e
Faulting process id: 0x293c
Faulting application start time: 0x01d6a6bf803b970d
Faulting application path: C:\OSGeo4W64\bin\qgis-dev-bin.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report Id: d22bb5df-8758-4c02-a4dd-b51630e2d161
Faulting package full name: 
Faulting package-relative application ID: 
```

Does it help?

**Comment by gioman** [comment]
> Does it help?

not sure, in the meantime can you try with a new QGIS profile?

**Comment by chau-intl** [comment]
I have tried on two other PC's (both windows 10 x64) and the same happens there. I have tried with a clean profile, issue still persists.

Just for reference, I have created a short video illustrating the issue and how I encounter it on QGIS 3.14.16: https://youtu.be/2knvEnIwvjE

**Comment by uclaros** [comment]
It works kind of ok for me on master on Debian. It does not crash, but it displays a tooltip across the screen with horizontally stretched letters.
Could depend on Qt version, mine is built against Qt 5.14.2

**Comment by rduivenvoorde** [comment]
I can reproduce on Wndows here with QGIS-dev version from osgeo4w:

QGIS version | 3.15.0-Master | QGIS code revision | 2626ad6130
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.2.0dev | Running against GDAL/OGR | 3.2.0dev
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 7.2.0 | Running against PROJ | Rel. 7.2.0, November 1st, 2020
OS Version | Windows 10 (10.0) | This copy of QGIS writes debugging output.

Trying to capture debug info (see https://www.qgis.org/en/site/getinvolved/development/bugreporting.html#log-output-on-
windows and setting 'set QGIS_DEBUG=5' in the qgis-dev.bat file does not reveal much more.
```
00002897	20.84279633	[18308] Fatal: createDIB: CreateDIBSection failed (-1x21, format: 6)	
```

[WIND.ZIP](https://github.com/qgis/QGIS/files/5410423/WIND.ZIP)

See zipped log. Note though that we are in transition to newer version of Qt... (and a new release). @jef 3.16 probably will stil have 5.11 yes?

**Comment by jef** [comment]
> @jef 3.16 probably will stil have 5.11 yes?

Wrong `jef` 😅

**Comment by rduivenvoorde** [comment]
> Wrong `jef` sweat_smile

Ah, duh. sorry meant to be @jef-n  :-)
Thanks for letting us know!

**Comment by jef** [comment]
No problem :) Good luck!

**Comment by gioman** [comment]
>  Apparently Qt is trying to create a much too big bitmap...

@rduivenvoorde so this is ultimately an upstream issue?

**Comment by rduivenvoorde** [comment]
That is what I read in the stackoverflow message yes: Windows trying to create a bitmap in memory which it cannot hold.
But I hope others, more technical then me can confirm.

**Comment by gioman** [comment]
Closing as upstream issue.

> That is what I read in the stackoverflow message yes: Windows trying to create a bitmap in memory which it cannot hold.
