### ISSUE TITLE
Layout becoming unresponsive and QGIS ultimately crashing when moving and/or editing an attribute table without a valid source layer

### ISSUE THREAD

**Issue by gjsa73** [qgis/QGIS#39501]
## User Feedback

Had just moved the position of an attribute table in a layout

## Report Details

**Crash ID**: [8c785d3b23091a279fbc5c659deb7dab72cf2913](https://github.com/qgis/QGIS/search?q=8c785d3b23091a279fbc5c659deb7dab72cf2913&type=Issues)

**Stack Trace**
<pre>
QgsLayoutTable::calculateMaxRowHeights qgslayouttable.cpp:983
QgsLayoutTable::totalHeight qgslayouttable.cpp:1029
QgsLayoutTable::recalculateFrameSizes qgslayouttable.cpp:824
QMetaObject::activate :
QgsLayoutItem::attemptMove qgslayoutitem.cpp:511
QgsLayoutItem::attemptMoveBy qgslayoutitem.cpp:543
QgsLayoutMouseHandles::mouseReleaseEvent qgslayoutmousehandles.cpp:619
QGraphicsItem::sceneEvent :
QGraphicsScene::sendEvent :
QGraphicsScene::sendEvent :
QGraphicsScene::mouseReleaseEvent :
QGraphicsScene::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGraphicsView::mouseReleaseEvent :
QgsLayoutView::mouseReleaseEvent qgslayoutview.cpp:980
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1606
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.10-A Coru�a
QGIS code revision: 8b051b9a43
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
@gjsa73 try with a new QGIS profile.

**Comment by roya0045** [comment]
"an attribute table without a valid source layer" what?

**Comment by gioman** [comment]
Closing for lack of feedback.
