### ISSUE TITLE
GetPrint: other layers than those in the map theme are printed, if selected, but not visible

### ISSUE THREAD

**Issue by jgrocha** [qgis/QGIS#39507]
**Describe the bug**

Compositions with maps following map theme works perfectly on QGIS desktop.

The same composition, if printed with GetPrint using QGIS Server will show other layers than those visible in the map theme.

The additional layers included in GetPrint are the ones selected, but not visible.

The following layer tree shows layers selected, _but not visible_, that are printed. These layers from group **PO - QUALIFICAÇÃO do solo 1A** shouldn't be printed by QGIS Server.

![Captura de ecrã de 2020-10-20 19-23-54](https://user-images.githubusercontent.com/163681/96628473-2cf84180-130a-11eb-81ec-6de0a1eb3936.png)

**How to Reproduce**

1. Create a composition with a map following a map theme
2. Print the composition using QGIS Server
3. Check other layers, make sure the group is disabled and update the map theme
4. Repeat the previous GetPrint request.
5. The additional non visible layers will be included in the output.
6. The same composition, if printed in QGIS desktop, will keep only the layers visible in the map theme.

**QGIS and OS versions**

Current master, 3.15.0-Master

**Additional context**

The work around is to deselected all layers.

**Comment by elpaso** [comment]
Can you please attach:
- failing project + data
- the exact URL calls to reproduce the issue
