### ISSUE TITLE
Pressing Escape to close the Identify Results window resets its size on next open

### ISSUE THREAD

**Issue by psychedelicious** [qgis/QGIS#39511]
**Describe the bug**
Closing the Identify Results window (when the panel is popped-out into its own window - that is, not docked to the main QGIS window) with the Escape key, the next time it opens, it is super tiny and has to be manually resized to be usable. If it is closed using the normal titlebar close button, it does not shrink itself on next open.

**How to Reproduce**

1. Identify a feature.
2. Click the button to pop-out or undock the Identify Results panel from the main QGIS window so that it is in its own window.
3. Ensure the window is resized to a usable size and not the smallest it can be. Example:
<img width="474" alt="image" src="https://user-images.githubusercontent.com/4822129/96648368-f8709e00-137a-11eb-800a-991c04c0743e.png">

4. Close it with the titlebar window close button.
5. Identify a feature. Note that the window remembers its size. 
6. Press Escape to close the Identify Results window.
7. Identify a feature. The window has now resized itself. Example:
<img width="173" alt="image" src="https://user-images.githubusercontent.com/4822129/96648420-0de5c800-137b-11eb-83c9-3b1aa8f96a49.png">

**QGIS and OS versions**

QGIS version | 3.14.1-Pi | QGIS code revision | de08d6b71d
-- | -- | -- | --
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.28.0 | Running against SQLite | 3.28.0
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS 10.15
Active python plugins | quick_map_services; GarminCustomMap; poiexport; qgis-maptiler-plugin; shapetools; Mergin; processing; db_manager; MetaSearch

**Additional context**

- [x] Search through existing issue reports and gis.stackexchange.com to check whether the issue already exists
- [x] Test with a [clean new user profile](https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html?highlight=profile#working-with-user-profiles).
- [x] Create a light and self-contained sample dataset and project file which demonstrates the issue

**Comment by Pedro-Murteira** [comment]
I can still replicate this on QGIS 3.16.14 and 3.22.1.
