### ISSUE TITLE
Histogram plot shows wrong frequencies when calculated from a multiband virtual raster

### ISSUE THREAD

**Issue by andremano** [qgis/QGIS#39512]
Calculating the histogram for a multiband virtual raster appears to yeld wrong frequencies `[image1]`. If the virtual raster is exported to geotif, the histogram calculated over the exported tif is the expected `[image2]`.

![image1](https://user-images.githubusercontent.com/6665872/96658044-eb848800-1343-11eb-95c5-cca074520e16.png)

![image2](https://user-images.githubusercontent.com/6665872/96658070-f9d2a400-1343-11eb-9aa2-a0f850a408a6.png)

**How to Reproduce**

Use the project [I attach to this report](https://drive.google.com/file/d/1vrHfoD2vySiQh-5yhl3WZLET60ImfVMU/view?usp=sharing) to conduct the workflow described below

- Create the _virtual raster_ with the `Build Virtual Raster `tool using the stack as shown below and leaving other options unchanged/default. 

![image](https://user-images.githubusercontent.com/6665872/96695128-95d2ce80-1389-11eb-8884-a8af80d12719.png)

- Export the Virtual layer to GeoTiff (using `Export` > `Save as`), using default parameters

- Compare the histograms of the _virtual_ and _tif_ rasters

**QGIS and OS versions**

QGIS version
3.10.10-A Coruña
QGIS code revision
8b051b9a43
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
AcATaMa; 
batchvectorlayersaver; 
DataPlotly; 
lizmap; 
mmqgis; 
ORStools; 
pluginbuilder3; 
QGIS3-getWKT; 
QNEAT3; 
quick_map_services; 
scriptrunner3; 
SemiAutomaticClassificationPlugin; 
temporalprofiletool; 
valuetool; 
db_manager; 
MetaSearch; 
processing

**Additional context**

Assuming this is a bug, it is around for some time because I have a screenshot of this operation taken 2 years ago (this is in the context of educational material) and the histogram appears to be wrong already back then.

**Comment by gioman** [comment]
@andremano the raster "resampling_stack_no_agg.tif" is missing and you don't say how you exported it from the VRT. The VRT in your project is a multiband layer, which justifies the histogram. If you create a new VRT with the provided iputs and you make it singleband the resulting histogram seems ok

![Screenshot_20201021_083506](https://user-images.githubusercontent.com/1951107/96692988-a0d43180-137e-11eb-8253-bd22d6966819.png)

**Comment by andremano** [comment]
@gioman I updated the description. With one band virtual rasters it seems fine, the problem appears to occur only with multi-band virtual layers.

**Comment by Pedro-Murteira** [comment]
@andremano Hello, i'm being unable to reproduce this issue. Can you still reproduce it on recent versions?
