### ISSUE TITLE
No transform available between EPSG:2100 and Unknown CRS

### ISSUE THREAD

**Issue by dmamalis** [qgis/QGIS#39526]
**Describe the bug**

After updating from 3.4 to 3.10 all my projects seem to be having the same two issues:
1. any new layer is being set to a different CRS than the project settings
![Screenshot_20201021_121458](https://user-images.githubusercontent.com/5211553/96709149-f7ebfd80-13a2-11eb-886f-1018e89dbc5a.png)
2. When I try to generate a 3d Map view I get the reported error "No transform available between EPSG:2100 and Unknown CRS" and the 3d view remains blank white

I have read a lot of issues reporting similar issues so I did take care of updating to 3.10.10 through the ubuntugis repos and got GDAL 3.1.3 and PROJ 7.1.1 however the problem insists even when starting a fresh project under a new and clean user profile
![Screenshot_20201021_134536](https://user-images.githubusercontent.com/5211553/96709915-04248a80-13a4-11eb-9848-114f5b524d7c.png)

**How to Reproduce**

You can reproduce with the following:
1. Zipped DEM file in img format [0488040740.zip](https://github.com/qgis/QGIS/files/5415478/0488040740.zip)
2. Project file [testNewProfile.zip](https://github.com/qgis/QGIS/files/5415276/testNewProfile.zip)

**QGIS and OS versions**

This is running under Kubuntu 20.04
QGIS version | 3.10.10-A Coruña | QGIS code branch | Release 3.10
-- | -- | -- | --
Compiled against Qt | 5.12.8 | Running against Qt | 5.12.8
Compiled against GDAL/OGR | 3.1.3 | Running against GDAL/OGR | 3.1.3
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.4 (Ubuntu 12.4-0ubuntu0.20.04.1) | SpatiaLite Version | 5.0.0
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 7.1.1 | Running against PROJ | Rel. 7.1.1, September 1st, 2020
OS Version | Ubuntu 20.04.1 LTS
Active python plugins | ViewshedAnalysis; processing; db_manager; MetaSearch

**Additional context**

If I understand correctly, this was supposed to be solved as reported in https://github.com/qgis/QGIS/issues/36699
I also went through https://github.com/qgis/QGIS/issues/39482 but unfortunately it doesn't share enough info on how to proceed.

**Comment by gioman** [comment]
> You can reproduce with
> [testNewProfile.zip](https://github.com/qgis/QGIS/files/5415276/testNewProfile.zip)

@dmamalis there is not data in this zip, just the project file.

**Comment by dmamalis** [comment]
> > You can reproduce with
> > [testNewProfile.zip](https://github.com/qgis/QGIS/files/5415276/testNewProfile.zip)
> 
> @dmamalis there is not data in this zip, just the project file.

Sorry for that, I just updated the issue

**Comment by gioman** [comment]
> Sorry for that, I just updated the issue

@dmamalis 

This is what gdalinfo (based on GDAL 3) reports. It seems that the CRS of the layer is not recognized/incomplete(?). What should be the CRS?

```
giovanni@nigripes:~$ gdalinfo Downloads/0488040740.img 
Driver: HFA/Erdas Imagine Images (.img)
Files: Downloads/0488040740.img
Size is 920, 720
Coordinate System is:
ENGCRS["Transverse Mercator",
    EDATUM[""],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["meters",1]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["meters",1]]]
Data axis to CRS axis mapping: 1,2
Origin = (487699.999583955679554,4077300.000416044145823)
Pixel Size = (5.000832088651654,-5.000832088651654)
Corner Coordinates:
Upper Left  (  487700.000, 4077300.000) 
Lower Left  (  487700.000, 4073699.401) 
Upper Right (  492300.765, 4077300.000) 
Lower Right (  492300.765, 4073699.401) 
Center      (  490000.382, 4075499.701) 
Band 1 Block=512x512 Type=Float32, ColorInterp=Undefined
  Description = Layer_1
  Min=0.000 Max=197.988 
  Minimum=0.000, Maximum=197.988, Mean=3.501, StdDev=18.652
  Overviews: 460x360, 230x180, 115x90, 57x45
```

**Comment by dmamalis** [comment]
These are the project settings I have been working with on several projects under QGIS 3.4 
The DEM files are supposed to be EPSG2100 - GGRS87 / Greek Grid

![Screenshot_20201021_144418](https://user-images.githubusercontent.com/5211553/96715240-f4a93f80-13ab-11eb-8559-a15a9ec2e21c.png)

**Comment by gioman** [comment]
your layer CRS info should read like

```
giovanni@nigripes:~$ projinfo EPSG:2100
PROJ.4 string:
+proj=tmerc +lat_0=0 +lon_0=24 +k=0.9996 +x_0=500000 +y_0=0 +ellps=GRS80 +towgs84=-199.87,74.79,246.62,0,0,0,0 +units=m +no_defs +type=crs

WKT2:2019 string:
PROJCRS["GGRS87 / Greek Grid",
    BASEGEOGCRS["GGRS87",
        DATUM["Greek Geodetic Reference System 1987",
            ELLIPSOID["GRS 1980",6378137,298.257222101,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4121]],
    CONVERSION["Greek Grid",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",24,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9996,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",500000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["unknown"],
        AREA["Greece - onshore"],
        BBOX[34.88,19.57,41.75,28.3]],
    ID["EPSG",2100]]
```

**Comment by dmamalis** [comment]
Behold
```(base) user@pc:~$ projinfo EPSG:2100
PROJ.4 string:
+proj=tmerc +lat_0=0 +lon_0=24 +k=0.9996 +x_0=500000 +y_0=0 +ellps=GRS80 +towgs84=-199.87,74.79,246.62,0,0,0,0 +units=m +no_defs +type=crs

WKT2:2019 string:
PROJCRS["GGRS87 / Greek Grid",
    BASEGEOGCRS["GGRS87",
        DATUM["Greek Geodetic Reference System 1987",
            ELLIPSOID["GRS 1980",6378137,298.257222101,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4121]],
    CONVERSION["Greek Grid",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",24,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9996,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",500000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["unknown"],
        AREA["Greece - onshore"],
        BBOX[34.88,19.57,41.75,28.3]],
    ID["EPSG",2100]]
```

**Comment by roya0045** [comment]
So why don't you just switch th projection to the good version istead of the proj4 corrupted one?

**Comment by nyalldawson** [comment]
I think we can close this one -- in my understanding it's a data issue, not a qgis one.

**Comment by dmamalis** [comment]
> So why don't you just switch th projection to the good version istead of the proj4 corrupted one?

Because, as i describe in the question, any new layer is being set to a different CRS than the project settings. It looks like something is not being stored correctly.

I played a bit with native linux tiff tools and the GeoTags seem to be corrupted with Tag 34737 being set to `Transverse Mercator|` 
I alos tried @rouault 's solution with [gdal_remove_towgs84](https://github.com/OSGeo/gdal/blob/master/gdal/swig/python/samples/gdal_remove_towgs84.py) but it reported that the file doesn't need patching.

As of now, the only thing that seems to work is using `gdal_edit.py` to edit the CRS tag and reload the file. 

The question here is if this could be a bug and what caused it.

**Comment by dmamalis** [comment]
> I think we can close this one -- in my understanding it's a data issue, not a qgis one.

@nyalldawson I might lack the qgis details to give in depth suggestions of what is going on , but this looks like an issue coming from upgrading from 3.4 to 3.10. There have been quite a lot of reports regarding similar problems especially while GDAL was still before 3.1.3. If the data works perfectly and is tagged appropriately in 3.4, how can I be sure that this is just a data issue? 
How can this be a data issue if the data has been

**Comment by nyalldawson** [comment]
Because 3.4 was really quite naive when it came to projections -- just because 3.4 (actually, it's any application based on proj library version < 6 ) gave one result doesn't mean that it was in any way correct.
