### ISSUE TITLE
[Forms][Relations] Isn't possible to hide fields in child form 

### ISSUE THREAD

**Issue by jonnyforestGIS** [qgis/QGIS#39523]
Checklist before submitting

- [X] Search through existing issue reports and gis.stackexchange.com to check whether the issue already exists
- [X] Test with a [clean new user profile](https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html?highlight=profile#working-with-user-profiles).
- [X] Create a light and self-contained sample dataset and project file which demonstrates the issue
- [X] Crete a video with the issue

**Describe the bug**
Child table from a relation don't hide the columns correctly.

**How to Reproduce**
1. Open the sample dataset
2. Click on Identify Results on the point from the Station layer to open the form.
3. Change the view to attribute table
4. Try to hide columns by right click
5. Or try to do Right-click on the column and use organize fields remove the selection of the fields to hide and ok. Then you will see the right behaviour but if select again the point with the Identify Results and go again to table attribute view the hidden fields appear again.

Dataset and video
[sample.zip](https://github.com/qgis/QGIS/files/5415114/sample.zip)

**QGIS and OS versions**
Tested on 3.10.10 LTR and 3.14.5

QGIS   version | 3.10.10-A Coruña | QGIS code revision | 8b051b9a43
-- | -- | -- | --
Compiled   against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled   against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled   against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled   against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL   Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT   Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled   against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | 
db_manager;
MetaSearch;
processing

QGIS   version | 3.14.16-Pi | QGIS code revision | df27394552
-- | -- | -- | --
Compiled   against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled   against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled   against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled   against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL   Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT   Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled   against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | 
db_manager;
MetaSearch;
processing

**Comment by gioman** [comment]
Confirmed here on 3.10.10 on Linux.

**Comment by jdugge** [comment]
Related/duplicate: #37252
