### ISSUE TITLE
Show feature count of Processing outputs

### ISSUE THREAD

**Issue by andremano** [qgis/QGIS#39522]
**Feature description.**
The insights from outputs generated with **_Processing_** tools, especially those related with overlays or aggregations, would be more immediate if the 'Show feature count' was toggled on automatically when these layers are added to the `Layers panel`. 

This could also be a check box showing in the context of any tool that outputs vector or tabular data, or a general **_Processing_** option the user could activate if he wishes.

Another option maybe, would be include it as part of a style defintion?

**Additional context**
In the example below, the overlapping_training the result of a model where the most important information is the number of features:

![image](https://user-images.githubusercontent.com/6665872/96704109-f6670900-1393-11eb-9a33-a8a91bd0a531.png)

If this tool is a recurrent task, or if it runs in batch mode it is a bit cumbersome to do the right-click show feature count for all the layers.

**Comment by uclaros** [comment]
You can select many layers and right-click -> *show feature count* to enable feature count for all selected layers.

**Comment by gioman** [comment]
> You can select many layers and right-click -> _show feature count_ to enable feature count for all selected layers.

The request is about to enable feature count automatically when a Processing output is added to the project. Or make the feature count part of the style (as Processing outputs can be assigned automatically a style).

**Comment by roya0045** [comment]
This seems like such a fringe case to me. I would just suggest creating a script to toggle on those things and use it in the models or as a macro.

**Comment by gioman** [comment]
> This seems like such a fringe case to me

sure, but among ~1500 feature requests is not even close to be the edgier case.

**Comment by uclaros** [comment]
>  it is a bit cumbersome to do the right-click show feature count for all the layers.

My comment addressed this part, as a workaround until the feature is implemented.

**Comment by andremano** [comment]
> You can select many layers and right-click -> _show feature count_ to enable feature count for all selected layers.

Thanks, didn't know that!

**Comment by andremano** [comment]
> > You can select many layers and right-click -> _show feature count_ to enable feature count for all selected layers.
> 
> The request is about to enable feature count automatically when a Processing output is added to the project. Or make the feature count part of the style (as Processing outputs can be assigned automatically a style).

Personally, I believe the first one is the way to go.  I suggested an alternative approach (style based approach) in the hope that it is easier to implement.

**Comment by andremano** [comment]
> This seems like such a fringe case to me. I would just suggest creating a script to toggle on those things and use it in the models or as a macro.

I am aware of that, there is even an example [here.](https://gis.stackexchange.com/questions/318190/setting-qgis-to-show-feature-count-always-when-layer-is-loaded) But lets face it, that is an approach only very advanced users feel comfortable with. Also in, my experience, the _count_ is a very common sought answer in the context of analysis - I think it would be nice to make it as straightforward as possible.

**Comment by gacarrillor** [comment]
I find the proposal useful.

> ...or a general Processing option the user could activate if he wishes.

I like this solution and volunteer to implement it if any core dev gives a "+1".

**Comment by roya0045** [comment]
This doesn't seem to be viable for a core alg. This is more of a customisation thing rather than a needed tool IMO. Especially since it didn't generate data but only need to interact with the UI similar to a trigger.

**Comment by nyalldawson** [comment]
Just a note that any option like this would need to default to off - calculating the feature count is can sometimes be quite expensive, depending on the output data format.

**Comment by roya0045** [comment]
Its literally getting the QgsVectorLayer and calling https://qgis.org/pyqgis/3.4/core/QgsVectorLayer.html#qgis.core.QgsVectorLayer.countSymbolFeatures. @gacarrillor

**Comment by gacarrillor** [comment]
> Just a note that any option like this would need to default to off - calculating the feature count is sometimes quite expensive, depending on the output data format.

Agreed, it should be off by default.

**Comment by uclaros** [comment]
I suggest an option like *Show feature count for newly added layers* : disabled | always | processing results

**Comment by andremano** [comment]
Glad to see the proposal gathers some report. 

> I suggest an option like _Show feature count for newly added layers_ : disabled | always | processing results

I agree, this would be great!

**Comment by gacarrillor** [comment]
> I suggest an option like Show feature count for newly added layers : disabled | always | processing results

I was thinking about it as a Processing option, not a general one. 
What do you think @nyalldawson?

**Comment by pathmapper** [comment]
A processing option to automatically show the feature count for processing outputs would be very welcome. I find myself very often checking the feature count after doing some processing for which currently a number of clicks are needed.

Also a general option  for newly added layers would be nice. When adding new layers, e.g. from WFS, showing the feature count is most of the time the first thing I do.

Both options off by default according to https://github.com/qgis/QGIS/issues/39522#issuecomment-713914897.

If such an option would not make it's way into QGIS, maybe an alternative would be a button for the layers widget to show the feature count for all layers with one single click (or using a keyboard shortcut):

![grafik](https://user-images.githubusercontent.com/20856381/123623735-18ac0300-d80e-11eb-8cda-b283d40a01c8.png)

**Comment by gacarrillor** [comment]
@andremano Just to let you know that this will be a Processing option in QGIS 3.28.

**Comment by andremano** [comment]
Thanks @gacarrillor! Much appreciated!
