### ISSUE TITLE
conditional formatting full row of attribute table and pyqgis

### ISSUE THREAD

**Issue by vowasemp** [qgis/QGIS#39532]
**Describe the bug**
conditional formatting full row rules are not applied if the attribute is updated via python when only one row is selected. If several rows are selected, the conditional formatting full row rules are applied for all the features except the first feature of the selection.

**How to Reproduce**
1. select one row in the attribute-table of a postgis-geometry layer
2. conditional formatting full row with condition "focus"=1 -> background color red
2. apply the following code:
                        selected_feature = layer.selectedFeatures()
                        layer.startEditing()
                        for feature in selected_feature:
                            feature["focus"] = 1
                            layer.updateFeature(feature)                                 
                        layer.commitChanges()
3. the conditional formatting full row rule is not applied
4. if several features are selected and the python-code is applied, the conditional formatting full row rules are applied for all the features except the first feature of the selection 

**QGIS and OS versions**

QGIS version | 3.10.7-A Coruña | QGIS code revision | 7b4ca4c8d0
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | VowaMaa; VowaOrnithoImport; VowaRingFilter; VowaSwisstopoBasemapLV95; VowaSynthese; VowaTmoFilter; geometry_paster; openlayers_plugin; pluginbuilder3; plugin_reloader; qfieldsync; qgis2web; SLD4raster; splitmultipart; swiss_locator; vrtbuilderplugin; db_manager; MetaSearch; processing

**Additional context**

**Comment by vowasemp** [comment]
we are ready to provide financial support for the bufixing

**Comment by gioman** [comment]
> we are ready to provide financial support for the bufixing

@vowasemp https://qgis.org/en/site/forusers/commercial_support.html
