### ISSUE TITLE
Zoom to extent wrong

### ISSUE THREAD

**Issue by antoniolocandro** [qgis/QGIS#39538]
The following dataset is an XML/GML which GDAL kind of interprets for the most part correctly, however it seems QGIS takes the bounding box inverted in EPSG4326 the order is lat,lon but it seems QGIS bbox for the zoom interprets lon,lat

To open just extract the zip file and add to QGIS master as it requires GDAL 3.2 I think to be viewed
[EA_AIP_DS_FULL_20170701.zip](https://github.com/qgis/QGIS/files/5418079/EA_AIP_DS_FULL_20170701.zip)

**Comment by gioman** [comment]
> To open just extract the zip file and add to QGIS master as it requires GDAL 3.2 I think to be viewed

@antoniolocandro The only difference that I can see is that in master there is a polygon layer that is recognized as "curvepolygon" and when added renders as a string. In QGIS < master this layer is recognized as polygon and renders as expected. Other than this I don't see any x/y inversion, all the other features render in the same place on all versions.

Maybe you should raise this in he GDAL tracker, but not really sure.

**Comment by gioman** [comment]
@antoniolocandro ask gdal's guys also about why the "zomm to layer" for such dataset is all over the place but not in the right place for this type of dataset.

**Comment by antoniolocandro** [comment]
If you select one of the layers and click zoom to layer it goes to an empty spot maybe this gif will explain myself better
![example](https://user-images.githubusercontent.com/4627073/96774670-8fe9e700-13a3-11eb-8940-bc0f73ca6f3d.gif)

**Comment by gioman** [comment]
> If you select one of the layers and click zoom to layer it goes to an empty spot maybe this gif will explain myself better

yes I saw that, but that is not the only issue, see my comment above.

**Comment by antoniolocandro** [comment]
Oh sorry I didn't see the the previous comment, will ask to the GDAL guys

**Comment by elpaso** [comment]
Inverted axis is a "classic" when getting data from WFS, what's the source of your GML?

**Comment by roya0045** [comment]
Welp Even added a fix, I assum that Antionio will have to way until the fixed gdal version gets into qgis or make his custom build.

**Comment by gioman** [comment]
> added a fix

@roya0045 link?

**Comment by roya0045** [comment]
@gioman https://github.com/OSGeo/gdal/commit/a3aad911aa32cb3fe61804ba96ca44eedbdd9071

**Comment by gioman** [comment]
> @gioman [OSGeo/gdal@a3aad91](https://github.com/OSGeo/gdal/commit/a3aad911aa32cb3fe61804ba96ca44eedbdd9071)

@roya0045 thanks! @antoniolocandro reopen if necessary after testing with the patched GDAL release.

**Comment by antoniolocandro** [comment]
Thank you it works with the patch still have some small issues but I think it is the way the XML/GML is encoded

**Comment by antoniolocandro** [comment]
> Inverted axis is a "classic" when getting data from WFS, what's the source of your GML?

This is not from a WFS it is a standard defined for aviation which I think ultimately will end up being served through WFS however current practice is to just download files like the one I showed. Just in case it peaks your interest http://www.aixm.aero/
