### ISSUE TITLE
Data Source Manager- Connecting to ArcGISFeatureServer

### ISSUE THREAD

**Issue by matthew2157** [qgis/QGIS#39576]
Using Data Source Manager to create a new connection here:
https://arc.arkansashighways.com/arcgis/rest/services/SIR/TrafficGroup/FeatureServer/0 

![image](https://user-images.githubusercontent.com/73350077/97013786-166f0780-150f-11eb-8972-e0f63d3d97be.png)

Results in - The Query returned no layers.
![image](https://user-images.githubusercontent.com/73350077/97013920-46b6a600-150f-11eb-981d-1c80351ee272.png)

Whuh?TF?

**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by gioman** [comment]
>  https://arc.arkansashighways.com/arcgis/rest/services/SIR/TrafficGroup/FeatureServer/0

@matthew2157 this service times out, always.

**Comment by jonnyforestGIS** [comment]
@gioman I can confirm that the server is down. I test a simple ping as well and I can't find the host. Isn't a QGIS problem. Cheers

**Comment by matthew2157** [comment]
Thank you!
