### ISSUE TITLE
Drag and Drop element of the Layer Order Panel is no longer working

### ISSUE THREAD

**Issue by Isaacson33** [qgis/QGIS#39573]
As per the title. Rendering is respecting the order imported from projects made under previous versions, but dragging the layers in the Layer Order Panel has no effect - the layer name doesn't move. Switching layer on and off with the checkboxes still works.

I've checked with several projects, including a brand new project not imported from previous versions. I've also tested on another computer (running the same spec) to make sure it's not machine-related.

Also checked with all but official plugins removed (processing and DBmanager only)

My spec

QGIS version | 3.14.16-Pi | QGIS code branch | Release 3.14
-- | -- | -- | --
Compiled against Qt | 5.15.1 | Running against Qt | 5.15.1
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.33.0 | Running against SQLite | 3.33.0
PostgreSQL Client Version | 12.4 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.5 | QScintilla2 Version | 2.11.5
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Manjaro Linux
Active python plugins | clipper; quick_map_services; TomBio; db_manager; processing

**Comment by roya0045** [comment]
Since you're obviously using a custom build on linux, with QT5.15 that could be why.

**Comment by Isaacson33** [comment]
> Since you're obviously using a custom build on linux, with QT5.15 that could be why.

Sorry, I don't know what you mean by 'custom build', could you elaborate.

**Comment by roya0045** [comment]
You have clearly compiled it yourself with a version of qt that is not fully supported. Any issues are probablt caused by yourself.

**Comment by Isaacson33** [comment]
I just installed it from the Arch repository as I've always done, which in turn is built directly from https://qgis.org/downloads without any additions, here's the full PKGBUILD

```
pkgname=qgis
pkgver=3.14.16
pkgrel=1
pkgdesc='Geographic Information System (GIS) that supports vector, raster & database formats'
url='https://qgis.org/'
license=(GPL)
arch=(x86_64)
depends=(exiv2 gdal gsl hicolor-icon-theme libzip protobuf python-qscintilla-qt5 python-sip qca qt5-3d
         qt5-serialport qt5-webkit qtkeychain qwtpolar spatialindex)
makedepends=(cmake fcgi python-setuptools python-six qt5-tools txt2tags sip)
optdepends=('fcgi: Map server'
            'gpsbabel: GPS Tools plugin'
            'python-gdal: DB Manager plugin; Processing plugin'
            'python-jinja: MetaSearch plugin'
            'python-owslib: MetaSearch plugin'
            'python-psycopg2: DB Manager plugin; Processing plugin'
            'python-pygments: MetaSearch plugin'
            'python-numpy: Processing plugin'
            'python-yaml: Processing plugin')
source=("https://qgis.org/downloads/$pkgname-$pkgver.tar.bz2")
sha256sums=('c9915c2e577f1812a2b35b678b123c58407e07824d73e5ec0dda13db7ca75c04')

prepare() {
  [[ -d build ]] || mkdir build
}

build() {
  cd build
  cmake -G "Unix Makefiles" ../$pkgname-$pkgver/ \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DWITH_3D=TRUE \
    -DWITH_SERVER=TRUE \
    -DWITH_CUSTOM_WIDGETS=TRUE \
    -DBINDINGS_GLOBAL_INSTALL=TRUE \
    -DQGIS_MANUAL_SUBDIR=share/man \
    -DWITH_QWTPOLAR=TRUE \
    -DWITH_INTERNAL_QWTPOLAR=FALSE
  make
}

package() {
  cd build
  make DESTDIR="$pkgdir" install
}

'''
I don't see anything 'custom' there. Am I missing it?

**Comment by roya0045** [comment]
However you got QT 5.15.1

**Comment by Isaacson33** [comment]
> However you got QT 5.15.1

I don't understand what you're saying at all. Qgis 'About' says it's compiled against QT 5.15.1. I'm running QT 5.15.1. What is the problem that you're trying to highlight - that I have the wrong version of Qt, or that I have the 'wrong' version of Qgis?

In either case, how would I find out what the right version of Qt was when the About section says it's compiled against the version I actually have?

I haven't 'custom built' anything.

**Comment by roya0045** [comment]
>What is the problem that you're trying to highlight - that I have the wrong version of Qt, or that I have the 'wrong' version of Qgis?
1st one, as I have been saying all the time.
Master only now support 5.14 as per https://github.com/qgis/QGIS/pull/38887
5.14.16 was done with Qt 5.11.2, if I recall.

**Comment by nyalldawson** [comment]
@roya0045 

> Master only now support 5.14 

That's not the case - I personally build with 5.15

**Comment by roya0045** [comment]
@nyalldawson what about when building 3.14.16?

**Comment by nyalldawson** [comment]
That should work too!

**Comment by roya0045** [comment]
I fail what other than a QT issue might explain this report. Especially since it seems to be quite an isolated case.

**Comment by elpaso** [comment]
Building with 5.15 here too, no issues so far.

**Comment by Isaacson33** [comment]
So what now? We've established it's not a 'custom build', it's running against the version of QT it's built against. The bug is still asking for feedback - is there something else I need to provide. I know @gioman has mentioned before something about 'feedback' being used as a generic 'needs more info' type label, so I need to ask if it's specifically referring to some information you're expecting from me, or just generally. If it is QT, this wouldn't be the first QT incompatibility problem . See https://github.com/qgis/QGIS/issues/33581. That was never actually resolved either.

If there's some generic incompatibility between the way Qgis is built and some implementations of QT, it would be good to know. If no-one's got time to fix it we could at least put a warning on the downloads page like there is currently for Android 5.

**Comment by Isaacson33** [comment]
Just updated, my specifications now are

QGIS version
3.16.0-Hannover
QGIS code branch
Release 3.16
Compiled against Qt
5.15.1
Running against Qt
5.15.1
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.33.0
Running against SQLite
3.33.0
PostgreSQL Client Version
12.4
SpatiaLite Version
4.3.0a
QWT Version
6.1.5
QScintilla2 Version
2.11.5
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Manjaro Linux
Active python plugins
TomBio; 
db_manager; 
processing

No change in the issue, layer rendering order is still broken. No Qt issues with any other applications I'm running.

**Comment by Pedro-Murteira** [comment]
@Isaacson33 Hello, I'm not able to reproduce this issue on the more recent versions (3.22.4 & 3.24.0). Did you come across this issue on more recent versions?
