### ISSUE TITLE
QGIS 3.14-2 Startfehler beim initialisieren Dateifilter

### ISSUE THREAD

**Issue by bahnwege** [qgis/QGIS#39587]
## User Feedback

Beim Start kommt es beim initialisieren der Dateifilter zu folgendem Abbruch:

## Report Details

**Crash ID**: [f295ccab5ea050c2e1a8fd0784836c2ee77d2cca](https://github.com/qgis/QGIS/search?q=f295ccab5ea050c2e1a8fd0784836c2ee77d2cca&type=Issues)

**Stack Trace**
<pre>
QgsLayerTreeFilterProxyModel::layerTreeModel qgslayertreefilterproxymodel.cpp:99
QgisApp::setupConnections qgisapp.cpp:4136
QgisApp::QgisApp qgisapp.cpp:1479
main main.cpp:1364
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.14.16-Pi
QGIS code revision: df27394552
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by roya0045** [comment]
English pls.

**Comment by bahnwege** [comment]
At the start the following abort occurs when initializing the file filter:

**Comment by roya0045** [comment]
Could you provide more information on the filter expression and the source?

**Comment by bahnwege** [comment]
no idea, QGIS start aborts with an error window unexpendly ended.

**Comment by gioman** [comment]
> no idea, QGIS start aborts with an error window unexpendly ended.

@bahnwege so QGIS crashes when it starts if when "initializing the file filter"?

regardless, if you are able to start QGIS please try with a new QGIS profile. If you are unable to start QGIS try removing manually the QGIS user profile folder first.

**Comment by bahnwege** [comment]
Thank you, bug found: The cause was the Layer Treeicon plugin.
