### ISSUE TITLE
Select Transformation Windows is too big and can't resize to click OK

### ISSUE THREAD

**Issue by antoniolocandro** [qgis/QGIS#39589]
![image](https://user-images.githubusercontent.com/4627073/97087590-74bbe900-15e8-11eb-89f3-956157d579da.png)

QGIS version
3.17.0-Master
QGIS code revision
ac0c5781ef
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.3.0dev
Running against GDAL/OGR
3.3.0dev
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
7.2.0
Running against PROJ
Rel. 7.2.0, November 1st, 2020
OS Version
Windows 10 (10.0)
This copy of QGIS writes debugging output.
Active python plugins
DigitizingTools; 
MemoryLayerSaver; 
qgis2web; 
quick_map_services; 
shapetools; 
db_manager; 
MetaSearch; 
processing

**Comment by roya0045** [comment]
Pressing enter should work fine in the meantime.

**Comment by antoniolocandro** [comment]
thanks, that works in the meantime

**Comment by Pedro-Murteira** [comment]
This issue is still true on QGIS 3.16.15 and 3.22.2, it appears to be connected to screen resolution. As mentioned in this issue, Enter works as a workaround.

**Comment by gioman** [comment]
There are other tickets with similar issues. In many cases the QGIS UI is really no more optimized to work on resolution pf 1368x768 or lower.

**Comment by antoniolocandro** [comment]
I think the window is made excessively large by listing the area of use when it is also shown in the preview map, probably would be better to just put a link to an online resource for those who would read over the places it is applicable vs those that will just use the bounding boxes. 

In any case, is there a place in the documentation or in the qgis download website section that at least tells users that a screen resolution lower than a value may show truncated/cut windows?

**Comment by DelazJ** [comment]
I think that adding a scrollbar to the whole dialog could help to resize it, here.

**Comment by DelazJ** [comment]
On ubuntu 20.04, i don't have the same rendering for this transformation. Probably because i have an older proj version (6.3.1)?
Anyway #46675 adds the scroll area and I am able to get this rendering. If someone with the detailed info version could give it a shot...
![image](https://user-images.githubusercontent.com/7983394/147873305-3ae03092-f4ef-4e69-813b-054fdc76f3ea.png)

**Comment by antoniolocandro** [comment]
I no longer have a small screen to test this out but it seems reasonable as an option to allow to click OK or Cancel
