### ISSUE TITLE
Can manage to compile QGIS_QUICK

### ISSUE THREAD

**Issue by YannPara** [qgis/QGIS#39597]
Hi evrybody,

I try to compile QGIS with QUICK ON and QML components, but withou success..
I think ther might be a bug but I am not sure.
All helps will be nice
Thanks a lot

`
3>------ Début de la génération : Projet : qgis_quick_plugin, Configuration : RelWithDebInfo x64 ------
3>qgis_quick_plugin.vcxproj -> C:\OSGeo4W64\QGIS\ms-windows\osgeo4w\build-qgis-test-x86_64\output\bin\RelWithDebInfo\qgis_quick_plugin.dll
3>qgis_quick_plugin.vcxproj -> C:/OSGeo4W64/QGIS/ms-windows/osgeo4w/build-qgis-test-x86_64/apps/qgis-test/pdb/qgis_quick_plugin.pdb (Full PDB)
3>QQmlComponent: Component is not ready
3>file:///C:/OSGeo4W64/QGIS/ms-windows/osgeo4w/build-qgis-test-x86_64/src/quickgui/plugin/typelist.qml:2:1: plugin cannot be loaded for module "QgsQuick": Cannot load library C:\OSGeo4W64\QGIS\ms-windows\osgeo4w\build-qgis-test-x86_64\src\quickgui\plugin\QgsQuick\qgis_quick_plugin.dll: Le module spÚcifiÚ est introuvable.
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: La commande "setlocal
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: cd C:\OSGeo4W64\QGIS\ms-windows\osgeo4w\build-qgis-test-x86_64\src\quickgui\plugin
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: C:
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: "C:\Program Files\CMake\bin\cmake.exe" -E make_directory C:/OSGeo4W64/QGIS/ms-windows/osgeo4w/build-qgis-test-x86_64/src/quickgui/plugin/QgsQuick
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: "C:\Program Files\CMake\bin\cmake.exe" -E copy C:/OSGeo4W64/QGIS/src/quickgui/plugin/qmldir C:/OSGeo4W64/QGIS/ms-windows/osgeo4w/build-qgis-test-x86_64/src/quickgui/plugin/QgsQuick
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: "C:\Program Files\CMake\bin\cmake.exe" -E copy C:/OSGeo4W64/QGIS/ms-windows/osgeo4w/build-qgis-test-x86_64/output/bin/RelWithDebInfo/qgis_quick_plugin.dll C:/OSGeo4W64/QGIS/ms-windows/osgeo4w/build-qgis-test-x86_64/src/quickgui/plugin/QgsQuick
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: C:\OSGeo4W64\apps\Qt5\bin\qmlplugindump.exe QgsQuick 0.1 . -noinstantiate --output C:/OSGeo4W64/QGIS/ms-windows/osgeo4w/build-qgis-test-x86_64/output/qml/QgsQuick/qgsquick.qmltypes
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmEnd
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmErrorLevel
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: exit /b %1
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmDone
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :VCEnd" s'est arrêtée avec le code 3.
`

**Comment by saberraz** [comment]
Have a look at the QGIS recipe for Input with is based on QGIS Quick:
https://github.com/lutraconsulting/input-sdk/blob/master/win/recipes/qgis/recipe.bat

**Comment by YannPara** [comment]
Thanks a lot ! I will looks at this recipe.
