### ISSUE TITLE
Data from another record for the object

### ISSUE THREAD

**Issue by FilatovAV** [qgis/QGIS#39599]
I found another error, but already in the weekly build 3.15.
in this case, the object field "LineType" == "2g_474_1a”, but the program reads it as" Continuous” it clearly takes this data from another record.
![3](https://user-images.githubusercontent.com/38399107/97117326-fa888300-1713-11eb-822c-ffed0b8ac5da.png)
![1](https://user-images.githubusercontent.com/38399107/97117327-fb211980-1713-11eb-955f-8cb86cf3aaf8.png)
![2](https://user-images.githubusercontent.com/38399107/97117328-fbb9b000-1713-11eb-9ac2-08f58631ebb9.png)
![4](https://user-images.githubusercontent.com/38399107/97117329-fd837380-1713-11eb-8a6e-efab80e0e5d8.png)

**Comment by roya0045** [comment]
Do you have one feature whose value for the field "LineType" is 'Continuous'?

**Comment by FilatovAV** [comment]
There is also a "LineType" is "Continuous" but I edit lines where "LineType" is "2g_476_1 a", there can't be such a thing.

**Comment by roya0045** [comment]
The expression builder doesn't care about the line what you are doing, in this cases it has access to the fill data of the layer and is presenting the information that the selected feature would display. If there is indeed a 'Continuous' value in the field "LineType" then this is not a bug. Restraining the preview to  any specific subset of feature could be doable, though this would b a bad idea IMO . Though with a setting or toggle it might be ok if it can be implemented reliably.

**Comment by FilatovAV** [comment]
I mean that in this case "LineType" can't be "Continuous" because I edit an object where "LineType" is " 2g_476_1 a". Посмотрите на изображения я там отметил важные моменты.

**Comment by gioman** [comment]
> I mean that in this case "LineType" can't be "Continuous" because I edit an object where "LineType" is " 2g_476_1 a". Look at the images I marked important points there.

@FilatovAV a sample project/data demonstrating the issue would help here.

**Comment by FilatovAV** [comment]
Maybe this will help?

![1](https://user-images.githubusercontent.com/38399107/97151830-1d04b580-1781-11eb-99f4-300139463b57.png)
![2](https://user-images.githubusercontent.com/38399107/97151835-1ece7900-1781-11eb-8d77-ce4b3cfbd16e.png)
![3](https://user-images.githubusercontent.com/38399107/97151837-1f670f80-1781-11eb-843c-19a9ee9eb64b.png)

**Comment by DelazJ** [comment]
@FilatovAV the value shown at the bottom of the dialog (in the last picture) is not specifically the one of the feature you are editing. It's the result of the first feature fetched from your data. If you want to see what happens with your current feature, use the blue arrow or the combobox just above and select that value from the list. Some explanation at https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/expression.html#the-interface

**Comment by FilatovAV** [comment]
Ok, so the error is different, if I explicitly set the svg file, it is loaded, but if I set the path to the file in the function, it is not.

**Comment by gioman** [comment]
> Ok, so the error is different, if I explicitly set the svg file, it is loaded, but if I set the path to the file in the function, it is not.

@FilatovAV can you please update title and description, or even better file a new ticket? thanks.

**Comment by DelazJ** [comment]
Is it normal that you have unquoted parenthesis in your expression and QGIS does not complain 🤔 ? What happens if you remove the parenthesis?

**Comment by FilatovAV** [comment]
> Is it normal that you have unquoted parenthesis in your expression and QGIS does not complain 🤔 ? What happens if you remove the parenthesis?

If I remove the brackets, the result is the same. This is a consequence of my experiments.

**Comment by FilatovAV** [comment]
> > Ok, so the error is different, if I explicitly set the svg file, it is loaded, but if I set the path to the file in the function, it is not.
> 
> @FilatovAV can you please update title and description, or even better file a new ticket? thanks.

Created a new ticket.
