### ISSUE TITLE
Build fails on ubuntu 18.04 due to error with synccrsdb

### ISSUE THREAD

**Issue by pwicks86** [qgis/QGIS#39598]
**Describe the bug**
Attempting to build on Ubuntu 18.04 results in the following error:

```
free(): invalid pointer
Aborted (core dumped)
src/crssync/CMakeFiles/synccrsdb.dir/build.make:57: recipe for target 'src/crssync/CMakeFiles/synccrsdb' failed
make[2]: *** [src/crssync/CMakeFiles/synccrsdb] Error 134
CMakeFiles/Makefile2:4288: recipe for target 'src/crssync/CMakeFiles/synccrsdb.dir/all' failed
make[1]: *** [src/crssync/CMakeFiles/synccrsdb.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```
This is running on ubuntu 18.04, using PROJ 6.3.2 built from source. 

**How to Reproduce**

1. `mkdir build`
2. `cmake ..`
3. `make`

**QGIS and OS versions**

QGIS: 012ae4ea47a26c8c3703a32c46faf3deff33aebc
OS: Ubuntu 18.04

**Additional context**

I found a few references to what sounded like similar errors and most pointed at incompatible PROJ versions. However, I've verified that cmake is pointing to the version of PROJ that I built from source, so not sure where I'm going wrong

**Comment by gioman** [comment]
@pwicks86 rather than assuming is a bug you should ask first in the developers mailing list.

**Comment by gioman** [comment]
Closing for lack of feedback.
