### ISSUE TITLE
Python error with latest Flatpak

### ISSUE THREAD

**Issue by asitemade4u** [qgis/QGIS#39603]
**Describe the bug**
When opening the freshly updated Flatpak version of QGis, I get this Python error:

```
Traceback (most recent call last):
  File "", line 1, in 
  File "/app/share/qgis/python/qgis/__init__.py", line 70, in 
    from qgis.PyQt import QtCore
  File "/app/share/qgis/python/qgis/PyQt/QtCore.py", line 24, in 
    from PyQt5.QtCore import *
ModuleNotFoundError: No module named 'PyQt5.sip'

Python version:
3.8.5 (default, Nov 10 2011, 15:00:00) 
[GCC 10.2.0]

QGIS version:
3.14.16-Pi 'Pi', a235a149

Python path:
['/app/share/qgis/python', '/home/stsinc/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python', '/home/stsinc/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins', '/app/share/qgis/python/plugins', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/usr/lib/python3.8/site-packages', '/app/lib/python3.8/site-packages', '/app/lib/python3.8/site-packages/numpy-1.19.2-py3.8-linux-x86_64.egg', '/app/lib/python3.8/site-packages/MarkupSafe-1.1.1-py3.8-linux-x86_64.egg']
```
It does not prevent me from accessing QGis, qhich seems to be working fine as usual otherwise.

**How to Reproduce**
- Install the Flatpak that was released yesterday (20201025) over the previous version
- Launch QGis

**QGIS and OS versions**

QGIS version | 3.14.16-Pi | QGIS code revision | a235a149
-- | -- | -- | --
Compiled against Qt | 5.15.1 | Running against Qt | 5.15.1
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.32.1 | Running against SQLite | 3.32.1
PostgreSQL Client Version | 12.2 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.5 | QScintilla2 Version | 2.11.5
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | KDE Flatpak runtime

**Comment by nyalldawson** [comment]
The flatpak releases aren't supported by the QGIS project -- they are a downstream community effort. You'll need to file this bug at flathub against the QGIS package there instead.
