### ISSUE TITLE
Import ers file shows different datum

### ISSUE THREAD

**Issue by newexco-kv** [qgis/QGIS#39607]
**Describe the bug**

When I import a .ers file into QGIS, the datum/projection seems to be changing unfavourably. For example, the file I am trying to import, has datum GDA94, Projection MGA55, however QGIS recognises this as PNG94, PNGMG94.

**How to Reproduce**

Reproducible by adding ers file to the QGIS map.

**QGIS and OS versions**

QGIS version
3.14.16-Pi

**Additional context**

**Comment by gioman** [comment]
@newexco-kv please link/attach a sample.

**Comment by gioman** [comment]
Closing for lack of feedback.
