### ISSUE TITLE
Problem with vector tile - rendering artefacts

### ISSUE THREAD

**Issue by saberraz** [qgis/QGIS#39613]
I am using ESRI Basemap in QGIS and I can see some borderlines from tiles:
![image](https://user-images.githubusercontent.com/2649047/97147479-7c52cd80-1761-11eb-89a4-f954454c36d2.png)

To replicate
- Add this link for the tile URL: https://basemaps.arcgis.com/v1/arcgis/rest/services/World_Basemap/VectorTileServer/tile/{z}/{y}/{x}.pbf

- Add this link for style URL:
https://basemaps.arcgis.com/b2/arcgis/rest/services/World_Basemap/VectorTileServer/resources/styles/root.json

**Comment by gioman** [comment]
@saberraz on 3.22.2 with

https://basemaps.arcgis.com/arcgis/rest/services/OpenStreetMap_v2/VectorTileServer

https://www.arcgis.com/sharing/rest/content/items/3e1a00aeae81496587988075fe529f71/resources/styles/root.json?f=pjson

seems ok to me. Can you give it a try?

**Comment by saberraz** [comment]
Thanks Gio, sorry for the late response.
