### ISSUE TITLE
QGIS-3.10.11on Ubuntu 20.04

### ISSUE THREAD

**Issue by Oerist** [qgis/QGIS#39616]
I got the following error message following today's qgis3.10.10->qgis3.10.11 upgrade:

===================================================================================================
Udpakker qgis-plugin-grass (1:3.10.11+32focal) ...
Sætter qgis-providers (1:3.10.11+32focal) op ...
	- 'VirtualXPath'	[XML Path Language - XPath]
	- 'VirtualXPath'	[XML Path Language - XPath]
	- 'VirtualXPath'	[XML Path Language - XPath]
free(): invalid pointer
Aborted (core dumped)
dpkg: fejl under behandling af pakken qgis-providers (--configure):
 installed qgis-providers package post-installation script subprocess returned e
rror exit status 134
Sætter libqgispython3.10.11 (1:3.10.11+32focal) op ...
dpkg: afhængighedsproblemer forhindrer konfiguration af qgis:
 qgis afhænger af qgis-providers (= 1:3.10.11+32focal); men:
  Pakken qgis-providers er ikke sat op endnu.

dpkg: fejl under behandling af pakken qgis (--configure):
 afhængighedsproblemer - efterlader den ukonfigureret
Sætter libqgis-customwidgets (1:3.10.11+32focal) op ...
Ingen apportrapport skrevet da fejlbeskeden indikerer, at det er en opfølgningsf
ejl fra en tidligere fejl.
                          dpkg: afhængighedsproblemer forhindrer konfiguration a
f qgis-plugin-grass:
 qgis-plugin-grass afhænger af qgis (= 1:3.10.11+32focal); men:
  Pakken qgis er ikke sat op endnu.

dpkg: fejl under behandling af pakken qgis-plugin-grass (--configure):
 afhængighedsproblemer - efterlader den ukonfigureret
Sætter libqgis-analysis3.10.11 (1:3.10.11+32focal) op ...
Ingen apportrapport skrevet da fejlbeskeden indikerer, at det er en opfølgningsf
ejl fra en tidligere fejl.
                          dpkg: afhængighedsproblemer forhindrer konfiguration a
f python3-qgis:
 python3-qgis afhænger af qgis-providers (= 1:3.10.11+32focal); men:
  Pakken qgis-providers er ikke sat op endnu.

dpkg: fejl under behandling af pakken python3-qgis (--configure):
 afhængighedsproblemer - efterlader den ukonfigureret
Sætter libpdal-base9 (2.0.1+ds-1build3) op ...
Ingen apportrapport skrevet da MaxReports (maks rapporter) allerede er nået
                                                                           Sætte
r libqt5charts5:amd64 (5.12.8-0ubuntu1) op ...
Sætter libqgis-3d3.10.11 (1:3.10.11+32focal) op ...
Sætter libqgisgrass7-3.10.11 (1:3.10.11+32focal) op ...
Sætter qml-module-qtcharts:amd64 (5.12.8-0ubuntu1) op ...
Sætter qgis-common (1:3.10.11+32focal) op ...
Sætter libqgis-app3.10.11 (1:3.10.11+32focal) op ...
Sætter python3-qgis-common (1:3.10.11+32focal) op ...
Sætter libpdal-plugin-pgpointcloud (2.0.1+ds-1build3) op ...
Sætter libpdal-plugin-icebridge (2.0.1+ds-1build3) op ...
Sætter libpdal-plugin-python (2.0.1+ds-1build3) op ...
Sætter libqgis-server3.10.11 (1:3.10.11+32focal) op ...
Sætter qgis-provider-grass (1:3.10.11+32focal) op ...
Sætter libpdal-plugin-faux (2.0.1+ds-1build3) op ...
Sætter grass-core (7.8.2-1build3) op ...
/usr/lib/grass78/etc/python/grass/pygrass/gis/__init__.py:75: SyntaxWarning: "is
" with a literal. Did you mean "=="?
  if value is '':
/usr/lib/grass78/etc/python/grass/temporal/core.py:65: SyntaxWarning: "is" with 
a literal. Did you mean "=="?
  if do_profiling is "True" or do_profiling is "1":
/usr/lib/grass78/etc/python/grass/temporal/core.py:65: SyntaxWarning: "is" with 
a literal. Did you mean "=="?
  if do_profiling is "True" or do_profiling is "1":
/usr/lib/grass78/etc/python/grass/temporal/core.py:582: SyntaxWarning: "is not" 
with a literal. Did you mean "!="?
  if driver_string is not None and driver_string is not "":
/usr/lib/grass78/etc/python/grass/temporal/temporal_algebra.py:2295: SyntaxWarni
ng: "is" with a literal. Did you mean "=="?
  if map_i.get_type() is "raster" or map_i.get_type() is "raster3d":
/usr/lib/grass78/etc/python/grass/temporal/temporal_algebra.py:2295: SyntaxWarni
ng: "is" with a literal. Did you mean "=="?
  if map_i.get_type() is "raster" or map_i.get_type() is "raster3d":
Sætter libpdal-plugin-sqlite (2.0.1+ds-1build3) op ...
Sætter libpdal-plugins (2.0.1+ds-1build3) op ...
Behandler udløsere for man-db (2.9.1-1) ...
Behandler udløsere for shared-mime-info (1.15-1) ...
Behandler udløsere for desktop-file-utils (0.24-1ubuntu3) ...
Behandler udløsere for mime-support (3.64ubuntu1) ...
Behandler udløsere for hicolor-icon-theme (0.17-2) ...
Behandler udløsere for gnome-menus (3.36.0-1ubuntu1) ...
Behandler udløsere for libc-bin (2.31-0ubuntu9.1) ...
Der opstod fejl under behandlingen:
 qgis-providers
 qgis
 qgis-plugin-grass
 python3-qgis
E: Sub-process /usr/bin/dpkg returned an error code (1)
=================================================================================================

Last update I got the same error message, then I installed the libraries for PostgreSQL 13 from their repositories, and the error went away.  Just, now, would it be back to the postgre SQL 12 libraries?

**Comment by gioman** [comment]
@Oerist no issues updating to 3.10.11 on focal here, please check that you have no mixed up repos.

**Comment by Oerist** [comment]
> @Oerist no issues updating to 3.10.11 on focal here, please check that you have no mixed up repos.

Well I solved it by downgrading to libpq-dev and libpq5 for postgres12 and purged postgres13. I just keep the postgresSQL13, in case, I ll need it for the next upgrade.
