### ISSUE TITLE
LinestringZ z value not being honoured in 3D Map.

### ISSUE THREAD

**Issue by pjshelton** [qgis/QGIS#39611]
**Describe the bug**
LinestringZ z value 
not being honoured in 3DMap when Altitude clamping Absolute and Altitude binding Vertex.

**How to Reproduce**
load a linestringZ from a Geopackage
Set the 3D Altitude clamping to Absolute
Set the 3D Altitude binding to Vertex
Uncheck Render as simple 3D lines
![image](https://user-images.githubusercontent.com/39154868/97140674-e0e54b00-17a8-11eb-8eaf-b914cd76971e.png)
View in 3D map. 
The red bar should be at the same height as the green line. But on my copy of QGIS it is not.
![image](https://user-images.githubusercontent.com/39154868/97140789-1e49d880-17a9-11eb-9d64-b57792b8e297.png)

The attached zip file contains the geopackage and project file for the images I have used in this bug report.
You will have to re base the path to each layer in the poject file.

**QGIS and OS versions**
QGIS version
3.15.0-Master
QGIS code revision
2626ad6130
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.2.0dev
Running against GDAL/OGR
3.2.0dev
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
7.2.0
Running against PROJ
Rel. 7.2.0, November 1st, 2020
OS Version
Windows 10 (10.0)
This copy of QGIS writes debugging output.
Active python plugins
db_manager; 
MetaSearch; 
processing

[QTT20010-GS.zip](https://github.com/qgis/QGIS/files/5437180/QTT20010-GS.zip)

**Comment by nyalldawson** [comment]
The current workaround is to check the "render as simple 3d lines" option
