### ISSUE TITLE
Qgis Dev Unable load plugin 

### ISSUE THREAD

**Issue by Korto19** [qgis/QGIS#39614]
Link to plugin repository is wrong

**Comment by gioman** [comment]
@Korto19 Can you elaborate and add the requested details?

**Comment by Korto19** [comment]
Here's the question
![immagine](https://user-images.githubusercontent.com/36882050/97154764-98139f00-1774-11eb-9d23-0734b3142ae3.png)

**Comment by uclaros** [comment]
See http://osgeo-org.1560.x6.nabble.com/QGIS-Developer-plugins-xml-for-3-16-and-3-17-td5448458.html

**Comment by Pedro-Murteira** [comment]
This issue no longer happens in version 3.22.3.
