### ISSUE TITLE
QGIS Query Builder, Complicated view and unreadable statements With unicode Language .

### ISSUE THREAD

**Issue by ibrahimman2** [qgis/QGIS#39621]
**Feature description.**

the problem is when i write query statements i can not read it or edit it cuz of complex view as you see in the picture in red square 
![Untitled](https://user-images.githubusercontent.com/72745233/97181523-0c196b80-17a4-11eb-95b8-024cc5b15945.jpg)
.

**Additional context**

**Comment by DelazJ** [comment]
Probably related to #39232

**Comment by ibrahimman2** [comment]
Old versions like QGIS-OSGeo4W-3.4.5-1-Setup-x86_64 Same problem and new one QGIS-OSGeo4W-3.14.16-2-Setup-x86_64 also same problem . tested on win 7 64x , win 8.1 64x and win 10 64x also i tried to change locale language unicode and same problem.
on ARCMAP in arcgis it works fine .
I hope to fix this problem .
thanks in advanced for your efforts to improve .


![arcmap](https://user-images.githubusercontent.com/72745233/97274561-7df1c380-183d-11eb-8348-0991bb42f173.jpg)

**Comment by ibrahimman2** [comment]
> Probably related to #39232
> Did it use to work in previous versions? And please fill information about your working environment.

this is same problem .

**Comment by gioman** [comment]
Closing as duplicate.
