### ISSUE TITLE
[Ubuntu 18.04] Crash opening properties dialog for raster, WMS, etc (not vector) layers.

### ISSUE THREAD

**Issue by barryrowlingson** [qgis/QGIS#39628]
**Describe the bug**

QGIS crashes with signal 11 on Linux when opening the properties dialog of a raster, xyz tiles, or WMS layer - possibly other types of layer too, but *not* for a vector layer or vector tiles layer.

```
GIS died on signal 11Could not attach to process.  If your uid matches the uid of the target
process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
ptrace: Operation not permitted.
No thread selected
No stack.
gdb returned 0
Aborted (core dumped)
```

**How to Reproduce**

1. Open QGIS with no plugins and a new user session
2. Add a TIFF as a layer.
3. Right-click on layer in layer list, select properties
4. crash

**QGIS and OS versions**

QGIS version | 3.16.0-Hannover | QGIS code revision | 43b64b13f3
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.6.2-CAPI-1.10.2 4d2925d6
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 10.14 (Ubuntu 10.14-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Ubuntu 18.04.5 LTS
Active python plugins | SpreadsheetLayers; rasterizestring; qgisgbifapi; SRTM-Downloader; ORStools; quick_map_services; qgis-maptiler-plugin; simplesvg; qgis_resource_sharing; QPackage; concavehull; LCPNetwork; qconsolidate3; cartolinegen; minimum_spanning_tree; leastcostpath; PeliasGeocoding; QuickOSM; GeoCoding; HEREqgis; ViewshedAnalysis; DataPlotly; qtiles3; qgis2web; plugin_reloader; db_manager; MetaSearch; processing

**Additional context**

Definitely worked last week but that was probably 3.14 and perhaps earlier libs of everything - did updates over the weekend.

**Comment by gioman** [comment]
@barryrowlingson can't confirm on Ubuntu 20.04 and QGIS 3.16 installed with qgis.org repos

**Comment by roya0045** [comment]
How is `SpreadsheetLayers; rasterizestring; qgisgbifapi; SRTM-Downloader; ORStools; quick_map_services; qgis-maptiler-plugin; simplesvg; qgis_resource_sharing; QPackage; concavehull; LCPNetwork; qconsolidate3; cartolinegen; minimum_spanning_tree; leastcostpath; PeliasGeocoding; QuickOSM; GeoCoding; HEREqgis; ViewshedAnalysis; DataPlotly; qtiles3; qgis2web; plugin_reloader; db_manager; MetaSearch; processing` No plugins?

**Comment by barryrowlingson** [comment]
Oops. That was a QGIS session started with plugins. It *does* crash without plugins.

**Comment by barryrowlingson** [comment]
Tried it on another machine, from a very clean user install (rm -rf'd ~/.local/share/QGIS, start QGIS, don't import settings from QGIS2, run with --noplugins. Same crash behaviour. 

Here's the about info on this second machine, seems identical. PROJ looks old though, has QGIS not moved past PROJ4?

QGIS version | 3.16.0-Hannover | QGIS code revision | 43b64b13f3
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.6.2-CAPI-1.10.2 4d2925d6
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 10.14 (Ubuntu 10.14-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Ubuntu 18.04.5 LTS
Active python plugins |

**Comment by roya0045** [comment]
QT 5.9?

**Comment by roya0045** [comment]
How do you install QGIS, out of curiosity?

**Comment by barryrowlingson** [comment]
installation is via apt, and I have this in my apt sources:

```
deb https://qgis.org/debian bionic main 
deb-src https://qgis.org/debian bionic main
```

I'm thinking the solution might be "Upgrade ubuntu to  20.x", but 18.x has another 6 months of support from Canonical...

**Comment by Dkrav-UA** [comment]
Same error when trying to open QGIS options (Settings\Options)

QGIS version | 3.16.0-Hannover | QGIS code revision | 43b64b13f3
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 10.14 (Ubuntu 10.14-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Ubuntu 18.04.5 LTS
Active python plugins | MetaSearch; processing; db_manager

**Comment by roya0045** [comment]
The ubuntu 18.04 seem to be having issues in general, possibly due to qt 5.9?

**Comment by gisn8** [comment]
Until there's a fix for this, can we get QGIS 3.14 put back in the Ubuntu repository? There's no sense to allow people to keep downloading/updating to a version with such a gaping problem.

**Comment by barryrowlingson** [comment]
I've installed Qt 5.14 from the https://launchpad.net/~beineri/+archive/ubuntu/opt-qt-5.14.2-bionic PPA and QGIS works with that.

Note you need to source a config file to set the QT path before running QGIS to get this:

QGIS version | 3.16.0-Hannover | QGIS code revision | 43b64b13f3
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.14.2
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.6.2-CAPI-1.10.2 4d2925d6
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 10.14 (Ubuntu 10.14-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Ubuntu 18.04.5 LTS
Active python plugins | SpreadsheetLayers; rasterizestring; qgisgbifapi; SRTM-Downloader; ORStools; quick_map_services; qgis-maptiler-plugin; simplesvg; qgis_resource_sharing; QPackage; concavehull; LCPNetwork; qconsolidate3; cartolinegen; minimum_spanning_tree; leastcostpath; PeliasGeocoding; QuickOSM; GeoCoding; HEREqgis; ViewshedAnalysis; DataPlotly; qtiles3; qgis2web; plugin_reloader; db_manager; MetaSearch; processing

**Comment by roya0045** [comment]
@barryrowlingson Thanks for confirming that the issue was coming from the outdated QT!

**Comment by barryrowlingson** [comment]
Fix by installing QT 5.14 from beineri PPA:

```
sudo add-apt-repository ppa:beineri/opt-qt-5.14.2-bionic
sudo apt-get update
sudo apt install qt514-meta-full 
source /opt/qt514/bin/qt514-env.sh
qgis
```

Note that you need to source the /opt/qt514/bin/qt514-env.sh before running qgis in any new shell. If you run from an icon or system menu you'll have to incorporate that into your login or system startup somehow.

**Comment by faalkao** [comment]
> Fix by installing QT 5.14 from beineri PPA:
> 
> ```
> sudo add-apt-repository ppa:beineri/opt-qt-5.14.2-bionic
> sudo apt-get update
> sudo apt install qt514-meta-full 
> source /opt/qt514/bin/qt514-env.sh
> qgis
> ```
> 
> qt514-meta-full is quite large (1Gb) but qt514-meta-minimal failed since QGIS uses a lot outside the packages in that meta package. I don't know what minimal set of individual packages are sufficient for QGIS.
> 
> Note that you need to source the /opt/qt514/bin/qt514-env.sh before running qgis in any new shell. If you run from an icon or system menu you'll have to incorporate that into your login or system startup somehow.

Thanks. It worked for me.

**Comment by gioman** [comment]
See also https://github.com/qgis/QGIS/issues/39782

**Comment by luipir** [comment]
fixed with https://github.com/qgis/QGIS/pull/39935

**Comment by Dkrav-UA** [comment]
Ubuntu 18.04 not entirely  fixed.  Open Settings\Options. Try to search parameter and your out.

**Comment by gioman** [comment]
> Try to search parameter and your out.

@Dkrav-UA this is another issue, already reported in another ticket.
