### ISSUE TITLE
When zoom out or move the canvas, feature selections disappears on lines which has the same line in opposite direction

### ISSUE THREAD

**Issue by metecad** [qgis/QGIS#39624]
I have a road network data. In this data, I have segments (lines) which has a **twin segment** in the opposite way in the same layer. It is being considered as a single carriageway. So it is just the segments start points and end points are **interconnected in reverse** (which will lead me to determine the direction). Thus I have an issue,

When I select one or multiple features and try to zoom out (change the scale) a little bit or move the canvas a little further, the selections just disappear.

**QGIS INFO**

QGIS version
3.4.12-Madeira
QGIS code revision
625767347a
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
2.4.1
Running against GDAL/OGR
2.4.1

**Comment by nirvn** [comment]
3.4 has long reached its end of life. Update to the latest 3.16 LTR, and reopen this issue if can still replicate the problem.
