### ISSUE TITLE
Alphachannel of fill colors in diagrams resets to 100% automatically

### ISSUE THREAD

**Issue by MrXsquared** [qgis/QGIS#39633]
**Describe the bug**
When setting Opacity for diagram fill colors, it automatically resets Opacity to 100% when hitting OK or Apply to confirm the settings. No transparency is applied. Best to see in attached .gif:

![dl](https://user-images.githubusercontent.com/44526431/97229694-09853900-17d9-11eb-95a8-c30c18cd4ae5.gif)

**How to Reproduce**

1. Create a diagram of your choice
2. Apply a transparent fill color to its attributes
3. Hit OK to confirm your settings

**QGIS and OS versions**
Tested on Windows 10 64bit versions of 
- 3.10.11
- 3.14.15
- 3.16.0
All three versions are affected.
- Option not available in 3.4.12; therefore not reproducible here

**Additional context**
Not sure if this feature just is still in development?
Other transparency options (like line color or draw effects) for diagrams are not affected.

**Comment by roya0045** [comment]
Transparency is controlled from the transparency setting in the rendering tab as per this line:
https://github.com/qgis/QGIS/blob/4668927ce432b198b3c572535ff234343c5042f5/src/gui/vector/qgsdiagramproperties.cpp#L837
There is also this one that sets opacity to 255 but I did look too much in depth for its usage.
https://github.com/qgis/QGIS/blob/4668927ce432b198b3c572535ff234343c5042f5/src/gui/vector/qgsdiagramproperties.cpp#L448

Seeing this I don't think it's a bug but indended.  Something could be done but I don't see a perfect solution to handle two alpha  settings properly without creating confusion.

**Comment by Pedro-Murteira** [comment]
Whether it is intended or not, this issue is still present on versions QGIS 3.16.15 and 3.22.2.

**Comment by alexbruy** [comment]
Seems fixed in the latest master (f344919474).
