### ISSUE TITLE
QGIS Desktop crashing at the time of closing.

### ISSUE THREAD

**Issue by myselfanomitra** [qgis/QGIS#39639]
## User Feedback

I faced this issue while closing QGIS. This is happening for a long time. I tried downgrading the software and upgrading it again, but no help.

## Report Details

**Crash ID**: [942aeea632a5370937224581c285bc986a2593c9](https://github.com/qgis/QGIS/search?q=942aeea632a5370937224581c285bc986a2593c9&type=Issues)

**Stack Trace**
<pre>
QgsProcessingToolboxModel::addProvider :
QgsProcessingToolboxModel::rebuild :
QMetaObject::activate :
QgsProcessingRegistry::providerRemoved :
QgsProcessingRegistry::removeProvider :
PyInit__core :
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyEval_EvalCodeEx :
PyEval_EvalCode :
PyArena_Free :
PyRun_StringFlags :
instance :
instance :
QgsPluginRegistry::unloadAll :
QgisApp::saveWindowState :
QMetaObject::activate :
QCoreApplicationPrivate::execCleanup :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.14.16-Pi
QGIS code revision: df27394552
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

**Comment by nirvn** [comment]
Very likely a plugin issue. Try with clean profile.

**Comment by roya0045** [comment]
Agreed seems like a processing provider from a plugin.

**Comment by gioman** [comment]
Closing for lack of feedback.
