### ISSUE TITLE
Texts not visible / not overlayed

### ISSUE THREAD

**Issue by justmematej** [qgis/QGIS#39646]
Hello,

we have a lot of texts that are linked to "small" geometries, i.e. lines and when zooming out, those texts are not visible.
For example:
![image](https://user-images.githubusercontent.com/19887936/97298032-23636200-1853-11eb-8ffa-2b0adffb04b0.png)

There is text "podboj", however since the line part is so short, there is no text visible when zooming out.
![image](https://user-images.githubusercontent.com/19887936/97298138-4aba2f00-1853-11eb-9547-7d0428d9bf9f.png)

This way we have a lot of information that is not visible when we plot out all the maps in a fixed scale, for example 1:2000. 
Can we somehow "force" the label outputs to be visible at all zoom levels?

Thanks.

**Comment by gioman** [comment]
@justmematej questions must be posted on the users or developers mailing lists. Thanks!

**Comment by roya0045** [comment]
@justmematej please take a look in the rendering or placement tab the option is there.

**Comment by nyalldawson** [comment]
Not a bug
