### ISSUE TITLE
Ubuntu 18.04 - Unmet dependencies - can't install QGIS 3.16

### ISSUE THREAD

**Issue by dragonfly-lover** [qgis/QGIS#39644]
**Describe the bug**

Tryng to install debian package for ubuntu 18.04
![image](https://user-images.githubusercontent.com/36678626/97286835-286ce500-1844-11eb-87f0-4b91c411ef52.png)

1. sudo apt install qgis

**QGIS and OS versions**

Ubuntu 18.04 + Neon

**Additional context**

Here are the repos i use.

![image](https://user-images.githubusercontent.com/36678626/97288515-36bc0080-1846-11eb-9925-9cebfaf828ac.png)

**Comment by gioman** [comment]
@dragonfly-lover wrong repo, your are using the debian one, there is one specific for Ubuntu.

**Comment by jef-n** [comment]
> @dragonfly-lover wrong repo, your are using the debian one, there is one specific for Ubuntu.

qgis.org/ubuntu and qgis.org/debian point to the same repo.    As there not only vanilla ubuntu source in places there might be other interfering packages installed.  Try to manually install the requested dependencies and check what's blocking those.   python3-qgis=1:3.16.0+28bionic  is available (https://qgis.org/debian/pool/main/q/qgis/python3-qgis_3.16.0+28bionic_amd64.deb)

**Comment by dragonfly-lover** [comment]
Sorry, please reopen the bug, updating the repo to the ubuntu specific doesn't solve the issue.
![image](https://user-images.githubusercontent.com/36678626/97293821-7a663880-184d-11eb-8490-4b8343bf21a8.png)
here's tthe response of apt:
![image](https://user-images.githubusercontent.com/36678626/97293952-a1246f00-184d-11eb-99b3-469ac3626ec8.png)

**Comment by gioman** [comment]
>  here's tthe response of apt:

@dragonfly-lover do you have repos with packages that may conflict, like ubuntugis?

**Comment by jef-n** [comment]
That's the same as above - I meant the dependencies, ie. try installing python3-qgis and check what happens

**Comment by dragonfly-lover** [comment]
So, at the end of the chain i see

- python3-qgis depends on qgis-providers

- qgis-providers depends on qtbase-abi-5-9-5

- the following message is obscure to me.


![image](https://user-images.githubusercontent.com/36678626/97295066-23f9f980-184f-11eb-9aa5-b58a21170381.png)

**Comment by dragonfly-lover** [comment]
here's my version of libqt5core5a (it's 5.14)
![image](https://user-images.githubusercontent.com/36678626/97295560-c0240080-184f-11eb-97eb-e3e8716f2f6a.png)

**Comment by jef-n** [comment]
That doesn't originate from ubuntu (or ubuntugis or qgis) and is apparently incompatible.

**Comment by dragonfly-lover** [comment]
@jef-n what may have happend?

**Comment by jef-n** [comment]
you installed non-ubuntu Qt (neon!?).   apt-cache policy libqt5core4a

**Comment by dragonfly-lover** [comment]
here it is. So, it seems like neon's qt install conflicts with qgis packages? what should i do (probably i can't revert libqt5core only uninstalling neon)?
![image](https://user-images.githubusercontent.com/36678626/97300292-8c000e00-1856-11eb-84f9-b5e2fc66e605.png)

**Comment by jef-n** [comment]
[Building package from source](https://github.com/qgis/QGIS/blob/master/INSTALL.md#310-building-debian-packages) for neon is probably the safest bet.

**Comment by dragonfly-lover** [comment]
nevertheless, this seems a problem for every neon user and not a single user setup issue. please @gioman, i updated the title to point the neon issue, can you set the bug to open again?

**Comment by jef-n** [comment]
There no buggy neon packages.

**Comment by gioman** [comment]
>  please @gioman, i updated the title to point the neon issue, can you set the bug to open again?

is this really a QGIS bug? does not seems to me, @jef-n ?

**Comment by jef-n** [comment]
The packages are not meant for neon - and so it's not a bug if they don't work on neon.

**Comment by dragonfly-lover** [comment]
so the one alternative for neon users is to compile from scratch? neon uses almost the same packages of ubuntu (infact it installs on top of ubuntu), so probably the problem is only that it doesn't recognize libqt5core5a 5.14.2 as an updated revision of 5.9.5.

any way to solve this?

**Comment by jef-n** [comment]
Qt is probably the most important dependency of all.  bionic has 5.9.    neon has 5.14 - that is not a minor update.
