### ISSUE TITLE
QGIS Server on Windows does not respect axis order in WMS 1.3

### ISSUE THREAD

**Issue by leojth** [qgis/QGIS#39642]
**Bug description**
When installing QGIS server on Windows with OSGeo4W installer, the server is not handling axis order correctly when calling service as WMS version 1.3. It works when running QGIS Server on Linux, but not on Windows.

* Tested on Windows with QGIS Server 3.16, 3.14 and 3.12 with the same result: not working.
* Tested on Linux with Docker image openquake/qgis-server:3.14.15-ubuntu: working as expected.

**Background**
As you probably known, in WMS 1.3, the coordinates in the BBOX parameter should be entered in the same order that the coordinate system defines its axis. For example EPSG:3006 defines North first and then East. The x/y axis must therefore be swapped in WMS 1.3 compared to WMS 1.0. This is where QGIS Server on Windows fail. As a result, many GIS software fail, and in QGIS Desktop, "ignore axis order" must be checked if consuming a WMS 1.3 served by QGIS Server on Windows.

**How to Reproduce**
1. Download the attached zip-file containing a qgis-project and a geopackage file. [railways_in_ostersund.zip](https://github.com/qgis/QGIS/files/5444270/railways_in_ostersund.zip)

2. Place both in c:\temp\
3. Start QGIS server on Windows and call with the following URL:

```
[your-server-url]?SERVICE=WMS&VERSION=1.0.0&REQUEST=GetMap&MAP=c:\temp\railways_in_ostersund.qgs&LAYERS=railways_ostersund&STYLES=&SRS=EPSG:3006&BBOX=481962.30703142704,7004057.336736175,482371.90703753056,7004466.936742279&WIDTH=1024&HEIGHT=1024&FORMAT=image/png&TRANSPARENT=true&DPI=96
```

That should give you a picture with some railway lines. See picture at the bottom of this page.

4. Change version to 1.3. According to EPSG:3006 (SWEREF99 TM) specification, the axis order is North/East so the BBOX is swapped.

```
[your-server-url]?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&MAP=c:\temp\railways_in_ostersund.qgs&LAYERS=railways_ostersund&STYLES=&CRS=EPSG:3006&BBOX=7004057.336736175,481962.30703142704,7004466.936742279,482371.90703753056&WIDTH=1024&HEIGHT=1024&FORMAT=image/png&TRANSPARENT=true&DPI=96
```

Nothing shows.

5. Now, try again but with the wrong axis order East/North

```
[your-server-url]?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&MAP=c:\temp\railways_in_ostersund.qgs&LAYERS=railways_ostersund&STYLES=&CRS=EPSG:3006&BBOX=481962.30703142704,7004057.336736175,482371.90703753056,7004466.936742279&WIDTH=1024&HEIGHT=1024&FORMAT=image/png&TRANSPARENT=true&DPI=96
```

Now you see the map again, same as with version 1.0, but using the wrong BBOX.

Correct display of WMS request shown in the picture below
![bild](https://user-images.githubusercontent.com/5588530/97274296-c193ff80-1834-11eb-9404-cdbf689553e5.png)

**Comment by leojth** [comment]
This seems to be a packaging issue. It actually works when I use the "proj-dev" package (version 8) instead of "proj" package (version 6) in the OSGeo4W installer.

**Comment by leojth** [comment]
Here's an update after some additional tests.
* Official QGIS Server 3.18 - does not work
* Official QGIS Server 3.18 - with share/proj replaced with proj-dev package - does not work
* Compiled QGIS Server 3.18 with proj-dev (v8) - works as expected!

**Comment by elpaso** [comment]
Still valid? Can we close this issue?

**Comment by leojth** [comment]
Confirmed working in QGIS Server 3.20!
