### ISSUE TITLE
Broken link for shapefile driver in datasource manager

### ISSUE THREAD

**Issue by NyakudyaA** [qgis/QGIS#39647]
# Problem

When adding the shapefile you get the above link
![broken-link](https://user-images.githubusercontent.com/2510900/97310065-7cd78b00-186b-11eb-8aa2-c9ffcb3f9484.png)

Currently, the link points to https://gdal.org/drv_shape.html

![shp-dr](https://user-images.githubusercontent.com/2510900/97308905-10a85780-186a-11eb-9c73-b18dfebc7fbf.png)

instead of https://gdal.org/drivers/vector/shapefile.html#vector-shapefile

**Comment by gioman** [comment]
Where exactly is this link?

**Comment by NyakudyaA** [comment]
> Where exactly is this link?

Updated the description

**Comment by roya0045** [comment]
Seems fixed, no link now.
