### ISSUE TITLE
error launching QGIS (qt5Sql.dll)

### ISSUE THREAD

**Issue by dimdle** [qgis/QGIS#39654]
Hi there, 
today i tried to install QGIS on another computer but the installation always gives me an error with the qt5Sql.dll

![grafik](https://user-images.githubusercontent.com/12907384/97365077-5e8e8100-18a5-11eb-9827-f2ba981242a2.png)

I have no idea how to solve this. On other machines i never had Issues with the network installer. 

Any ideas, what the Problem could be? 

Thx in advance!

**Comment by gioman** [comment]
@dimdle do you have a qt5Sql.dll file in your c:/windows folder (or subfolders) ?

**Comment by dimdle** [comment]
hello gioman
yes, the dll ist here:  c:\OSGeo4W64\apps\Qt5\bin\Qt5Sql.dll

it was downloaded from the osgeo network installer.

**Comment by gioman** [comment]
> hello gioman

@dimdle my question is if you any other copy of that file inside the **C:\windows** folder (or subfolders).

**Comment by dimdle** [comment]
oh sorry!  
there're quite a few Qt5Sql.dll on C disk, but not in c:\windows folder or subfolder

here's the list 
c:\Program Files\Google\Google Earth Pro\client\Qt5Sql.dll
c:\Program Files\ParaView 5.6.0-Windows-msvc2015-64bit\bin\Qt5Sql.dll
c:\Program Files\SMS 13.0 64-bit\Mesa\Qt5Sql.dll
c:\Program Files\SMS 13.0 64-bit\Qt5Sql.dll
c:\OSGeo4W64\apps\Qt5\bin\Qt5Sql.dll
c:\MEDUSA4_PERSONAL_V6_2\medsys\med\share\qt5sql.dll
c:\Program Files (x86)\Acronis\TrueImageHome\Qt5Sql.dll
c:\Program Files (x86)\Polar\Polar FlowSync\Qt5Sql.dll

**Comment by agiudiceandrea** [comment]
@dimdle What QGIS version are instaling? Is RStudio installed in your system?

**Comment by dimdle** [comment]
i installed QGIS 3.16, but the error came also when installing 3.14 or the long term 3.10

the error is always followed by these 3 other error messages
![grafik](https://user-images.githubusercontent.com/12907384/97431965-83bdd680-191b-11eb-91cb-39bdfa702334.png)
![grafik](https://user-images.githubusercontent.com/12907384/97431991-8fa99880-191b-11eb-93c8-87147028ddd1.png)
![grafik](https://user-images.githubusercontent.com/12907384/97432056-a5b75900-191b-11eb-8cf2-cfdfc18c9693.png)

RSTUDIO ist not installed on this machine 

[setup.log.full.zip](https://github.com/qgis/QGIS/files/5451612/setup.log.full.zip)

**Comment by gioman** [comment]
@dimdle german does not tell me much but this type of errors are very similar in aspect to the case when a bunch of DLL in use by QGIS are present also in c:\windows\system32 (or SysWOW64) where were placed by other software that should not have (contributing to what is usually called "dll hell"). Check again if those DLLs are really not also in c:\windows\system32 or c:\windows\SysWOW64

**Comment by dimdle** [comment]
@gioman 
I just found the following .dll's named something with qt5 in C:\Windows

c:\Windows\System32\Qt5Core.dll
c:\Windows\System32\Qt5Gui.dll
c:\Windows\System32\Qt5Network.dll
c:\Windows\System32\Qt5OpenGL.dll
c:\Windows\System32\Qt5Widgets.dll
c:\Windows\System32\Qt5Xml.dll

**Comment by gioman** [comment]
> c:\Windows\System32\Qt5Core.dll
> c:\Windows\System32\Qt5Gui.dll
> c:\Windows\System32\Qt5Network.dll
> c:\Windows\System32\Qt5OpenGL.dll
> c:\Windows\System32\Qt5Widgets.dll
> c:\Windows\System32\Qt5Xml.dll

That is possibly the source of your problem. You can try remove them and see if QGIS starts. Of course removing them will make other program/s stop work (you can always put them back), but this programs should have never placed those DLL in your windows folder in the first place.

**Comment by dimdle** [comment]
Thank you very much!!
The installation process now ended successfully!

**Comment by jef-n** [comment]
Same as https://github.com/qgis/QGIS/issues/26891#issuecomment-495889171.  https://github.com/qgis/QGIS/issues/26891#issuecomment-495889169 for diagnostics.
