### ISSUE TITLE
pop-up windows grow larger after every sequential openin

### ISSUE THREAD

**Issue by oivoi** [qgis/QGIS#39675]
I've been creating line polygons into a shapefile, after creating each polygon, a window pops up for me to fill in the characteristics of the polygon. I typically do not enter values for these lines, and click ok; the line is created and stored.

After every sequential polygon creation the popup window grows, only on the y axis though. The window can be dragged down to its original size, but the task becomes frustrating after a while, the narrow edges are also hard to grabb.

Sometimes this occurs on my laptop and the popups grow so tall they surpas the size of my screen, and I cant click the OK button or grab the base of the window to make it smaller. This technically forces me to restart the program as I cant create polygons anymore. This incident happens with other popup windows too, but the "bug" is harder to recreate with them.

QGIS version
3.4.2-Madeira
QGIS code revision
22034aa070
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
2.3.2
Running against GDAL/OGR
2.3.2
Compiled against GEOS
3.7.0-CAPI-1.11.0
Running against GEOS
3.7.0-CAPI-1.11.0 673b9939
PostgreSQL Client Version
9.2.4
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
520
Running against PROJ
5.2.0

**Comment by gioman** [comment]
>  3.4.2-Madeira

@oivoi too old, you must use the latest installer for 3.10 or 3.16.

**Comment by gioman** [comment]
Closing for lack of further feedback.
