### ISSUE TITLE
3D map polygon edges at wrong elevation

### ISSUE THREAD

**Issue by MauroDallapina** [qgis/QGIS#39674]
Fixed in master

_Originally posted by @nyalldawson in https://github.com/qgis/QGIS/issues/35672#issuecomment-643880184_

Is it possible to fix the same problem in QGIS 3.10 (LTR)?

Thanks

**Comment by gioman** [comment]
@MauroDallapina you must comment in the original ticket or in the PR that fixed the issue on master.
