### ISSUE TITLE
Duplicate vertex when digitizing line with filegdb

### ISSUE THREAD

**Issue by esnyder-rve** [qgis/QGIS#39680]
**Describe the bug**
When digitizing lines, a duplicate vertex is added for each segment's starting vertex. I can only produce this with ESRI's File GeoDatabase (.gdb).

**How to Reproduce**

1. Have point layer
2. Have line layer
3. Vertex snapping enabled
4. Digitize line between points
5. Notice duplicate vertices at each line segment's beginning.

![2020-10-28](https://user-images.githubusercontent.com/61027950/97441557-3df31500-18ff-11eb-89fc-6a1a7ee49904.gif)

**Screencast Walkthrough**
1. Showing that there is only one inlet at each location, there are no overlapped inlets.
2. Showing the problem with a single line segment. The first vertex gets duplicated.
3. Looking at the vertex editor to show the duplicate vertex and deleting it.
4. Showing the problem with multiple segments. The first vertex for each segment gets duplicated.
5. Looking at the vertex editor to show the duplicate vertices and deleting them.

**QGIS and OS versions**

QGIS version
3.16.0-Hannover
QGIS code revision
43b64b13f3
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
annotationManager; 
BezierEditing; 
cartography_tools; 
firstaid; 
FreehandRasterGeoreferencer; 
Go2NextFeature3; 
joinmultiplelines; 
latlontools; 
loadthemall; 
MemoryLayerSaver; 
mmqgis; 
monokai; 
MultipleLayerSelection; 
powerpan; 
processing_r; 
processing_saga; 
processing_taudem; 
processing_wbt; 
qlyrx; 
QuickMultiAttributeEdit3; 
redLayer; 
searchlayers; 
SelectWithin; 
slyr_community; 
Submission; 
db_manager; 
processing

**Additional context**
Tried to reproduce with clean profile and scratch layers, cannot reproduce.

**Comment by gioman** [comment]
>  Tried to reproduce with clean profile and scratch layers, cannot reproduce.

@esnyder-rve does it happens with a new profile and fgdb datasource?

**Comment by esnyder-rve** [comment]
Yes

**Comment by gioman** [comment]
Does it happen with **any** fgdb, or just specific ones? if is the latter please attach a sample.

**Comment by gioman** [comment]
> I've tried it with a couple of fgdb, and the same thing occurs.

 @esnyder-rve can you attach one of them?

**Comment by esnyder-rve** [comment]
[Stormwater.gdb.zip](https://github.com/qgis/QGIS/files/5453104/Stormwater.gdb.zip)

**Comment by gioman** [comment]
>  The area given in the sample is shown in the gif above.

@gioman I cannot replicate here on QGIS 3.16 on Windows.

**Comment by esnyder-rve** [comment]
I guess I just have the fun ones like #37415 (also mine, but this was from my personal account).

**Comment by gioman** [comment]
@esnyder-rve likely a plugin issue as in https://github.com/qgis/QGIS/issues/39991#issuecomment-725986427
