### ISSUE TITLE
WMS Layer Properties "Selected Layers" / "Other Layers" links are not working

### ISSUE THREAD

**Issue by pathmapper** [qgis/QGIS#39689]
**Describe the bug**
If the WMS Layer Properties are opened in the QGIS browser, the **Selected Layers** / **Other Layers** links are not working:

<img src="https://user-images.githubusercontent.com/20856381/97540194-91c73200-19c3-11eb-8ff1-8413cbfb164c.png" width="500">

Same is true if the metadata is shown in the properties widget:

<img src="https://user-images.githubusercontent.com/20856381/97540527-1023d400-19c4-11eb-88dc-d35e0294b8f9.png" width="300">

**How to Reproduce**

1. Add a WMS connection, e.g. `https://www.wms.nrw.de/geobasis/wms_nw_dop`
2. Right click on a layer and choose _Layer Properties_.
3. **Selected Layers** / **Other Layers** links are not working
4. Same links in the _properties widget_ are not working.

![links_wms_metadata](https://user-images.githubusercontent.com/20856381/97541609-b9b79500-19c5-11eb-8f47-3ba8b808092d.gif)

**QGIS and OS versions**

QGIS version | 3.16.0-Hannover | QGIS code revision | 43b64b13f3
-- | -- | -- | --
Compiled against Qt | 5.11.3 | Running against Qt | 5.11.3
Compiled against GDAL/OGR | 2.4.0 | Running against GDAL/OGR | 2.4.0
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.27.2 | Running against SQLite | 3.27.2
PostgreSQL Client Version | 11.9 (Debian 11.9-0+deb10u1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.10.4
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Debian GNU/Linux 10 (buster)
Active python plugins | ClipMultipleLayers; quick_map_services; scriptrunner3; LAStools; canvas_clipper; savedialog; loadthemall; clipper; kmltools; qgis-maptiler-plugin; MapsPrinter; mmqgis; pluginbuilder3; vector_tiles_reader; layerGroupFilter; plugin_reloader; realcentroid; mask; MetaSearch; db_manager; processing

**Additional context**

If the metadata is shown via the legend (right click on the layer -> _Properties_ -> _Information_) both links are working.

**Comment by Pedro-Murteira** [comment]
I can still reproduce this on QGIS 3.16.14 and 3.22.1.
