### ISSUE TITLE
Fixed display scale for symbols in Layer Panel / Layer Legend

### ISSUE THREAD

**Issue by giswgjs** [qgis/QGIS#39681]
**Feature description.**

The legend in the layer panel is practically unusable (at least quite ugly) for symbols whose sizes unit is defined as "map units" or "meters at scale", see screenshot. The symbol size in the Layer Legend updates when toggling e.g. 'Show feature count' (3.16.0):

![grafik](https://user-images.githubusercontent.com/17158239/97441219-c1752c00-1928-11eb-90c6-309ed769526e.png)

I would like to suggest an option of using a **fixed scale for the display of such symbols** in the Layer Panel, e.g. as a setting under Settings > Options > Canvas&Legend.

The GUI could be a check box together with a combo box or line edit:

![grafik](https://user-images.githubusercontent.com/17158239/97442446-2715e800-192a-11eb-9082-b42fcf4426b9.png)

**Additional context / related sources.**

https://gis.stackexchange.com/questions/308551/fixed-qgis-layer-symbol-size-in-layer-legend

https://github.com/qgis/QGIS/issues/24613

**Comment by roya0045** [comment]
@gioman if this is a bug ticket there are already duplicates of this.

**Comment by gioman** [comment]
Related to https://github.com/qgis/QGIS/issues/33755 ?
