### ISSUE TITLE
Double Click on a Raster in TOC causes Crash QGIS 3.16 and Master on Windows

### ISSUE THREAD

**Issue by Antoviscomi** [qgis/QGIS#39692]
to reproduce:
1 add a raster in a view;
2 double click on a raster

Crash ID: 58f30138b653894852cdf003bd4a85f35a1f3f8c

Stack Trace

QObject::isWidgetType :
QMainWindow::trUtf8 :
QHeaderView::logicalIndexAt :
QWidget::setStyleSheet :
QgsCollapsibleGroupBoxBasic::updateStyle qgscollapsiblegroupbox.cpp:386
QgsCollapsibleGroupBoxBasic::showEvent qgscollapsiblegroupbox.cpp:115
QgsCollapsibleGroupBox::showEvent qgscollapsiblegroupbox.cpp:561
QWidget::event :
QGroupBox::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QWidgetPrivate::show_helper :
QWidget::setVisible :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidget::setVisible :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidget::setVisible :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidget::setVisible :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidget::setVisible :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidget::setVisible :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidget::setVisible :
QDialog::setVisible :
QgisApp::showLayerProperties qgisapp.cpp:15943
QgisApp::layerProperties qgisapp.cpp:9163
QgisApp::layerTreeViewDoubleClicked qgisapp.cpp:659
QtPrivate::FunctorCall,QtPrivate::List,void,void (__cdecl QgisApp::*)(QModelIndex const & __ptr64) __ptr64>::call qobjectdefs_impl.h:134
QtPrivate::FunctionPointer::call,void> qobjectdefs_impl.h:168
QtPrivate::QSlotObject,void>::impl qobjectdefs_impl.h:397
QMetaObject::activate :
QAbstractItemView::doubleClicked :
QTreeView::mouseDoubleClickEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1637
WinMain mainwin.cpp:197
__scrt_common_main_seh exe_common.inl:253
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.17.0-Master
QGIS code revision: cf37cb94f3
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.3.0dev
Running against GDAL: 3.3.0dev

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by Antoviscomi** [comment]
Crash ID: bcf947f63bdfb1fdcaf78c3b570f96498038e624


Stack Trace


QObject::isWidgetType :
QMainWindow::trUtf8 :
QHeaderView::logicalIndexAt :
QWidget::setStyleSheet :
QgsCollapsibleGroupBoxBasic::updateStyle qgscollapsiblegroupbox.cpp:386
QgsCollapsibleGroupBoxBasic::showEvent qgscollapsiblegroupbox.cpp:115
QgsCollapsibleGroupBox::showEvent qgscollapsiblegroupbox.cpp:561
QWidget::event :
QGroupBox::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QWidgetPrivate::show_helper :
QWidget::setVisible :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidget::setVisible :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidget::setVisible :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidget::setVisible :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidget::setVisible :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidget::setVisible :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidget::setVisible :
QDialog::setVisible :




QGIS Info
QGIS Version: 3.16.0-Hannover
QGIS code revision: 4af1cbfb97
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.3.0dev
Running against GDAL: 3.3.0dev



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by gioman** [comment]
@Antoviscomi cannot confirm here, same QGIS versions same OS. Please try with a new QGIS profile.

**Comment by Antoviscomi** [comment]
> @Antoviscomi cannot confirm here, same QGIS versions same OS. Please try with a new QGIS profile.

ok @gioman  with a new clean profile it works fine, thank you

**Comment by PedroVenancio** [comment]
@Antoviscomi Can you check if you double click several times, you get the crash? Sometimes it only crashes here after 12, 15 ... double clicks.

**Comment by luipir** [comment]
crash in the same codeline as in https://github.com/qgis/QGIS/issues/3969

**Comment by Antoviscomi** [comment]
@PedroVenancio yes It Crashes sometimes after  three and sometimes two clicks

**Comment by Antoviscomi** [comment]
@luipir @PedroVenancio @gioman In addition I've noticed that if I delete C:\...AppData\Roaming\QGIS\QGIS3\profiles\default\QGIS\ QGIS3.ini, then I open a clean project with default profile, double click it works fine (I double click for about 15-20times)

**Comment by luipir** [comment]
> @luipir @PedroVenancio @gioman In addition I've noticed that if I delete C:...AppData\Roaming\QGIS\QGIS3\profiles\default\QGIS\ QGIS3.ini, then I open a clean project with default profile, double click it works fine (I double click for about 15-20times)

does not work in my case

**Comment by Antoviscomi** [comment]
this bug was fixed in #39693 then from today update, in 3.16  there is no crashes so I close this topic
![Anonimo](https://user-images.githubusercontent.com/12639444/99533216-cff1b900-29a5-11eb-94a0-1b1530905ca4.jpg)
