### ISSUE TITLE
QGIS crashes on shutdown

### ISSUE THREAD

**Issue by rbwinst-usgs** [qgis/QGIS#39697]
## User Feedback

I added two adjacent GeoTIFF rasters. I converted each of them to ASCII raster (*.asc). One of them was saved in the default location. I used cut and paste to move it to the location of the original files. The other convert raster was saved in the original location. Neither converted raster was added to the project. I then closed the project without saving it.

## Report Details

**Crash ID**: [30c51af0d66d75ece0d06eb969ea1b67efff90d5]('https://github.com/qgis/QGIS/search?q=30c51af0d66d75ece0d06eb969ea1b67efff90d5&type=Issues')

**Stack Trace**
<pre>
osgeo::proj::datum::Datum::conventionalRS :
osgeo::proj::datum::Datum::conventionalRS :
osgeo::proj::datum::Datum::conventionalRS :
OGRSpatialReference::~OGRSpatialReference :
OGRSpatialReference::~OGRSpatialReference :
GDALRegister_GenBin :
GDALRegister_GenBin :
QgsAbstractDatabaseProviderConnection::TableProperty::GeometryColumnType::operator== :
QgsGdalLayerItem::~QgsGdalLayerItem :
QgsAbstractDatabaseProviderConnection::TableProperty::GeometryColumnType::operator== :
QgsRasterPipe::~QgsRasterPipe :
QgsRasterLayer::~QgsRasterLayer :
QgsVectorLayerProperties::`default constructor closure' :
QgsMapLayerStore::removeMapLayers :
QgsMapLayerStore::removeMapLayers :
QgsMapLayerStore::removeAllMapLayers :
QgsProject::clear :
QgisApp::closeProject :
QgisApp::fileExit :
QWidget::event :
QgisApp::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::close_helper :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processCloseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.0-A Coru�a
QGIS code revision: 6ffa89eb3e
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by nirvn** [comment]
Download the latest LTR version, you're running on an outdated .0 release. This is most likely fixed.

**Comment by gioman** [comment]
@rbwinst-usgs repen if it happens also with 3.10.11 (test also with a new QGIS profile).
