### ISSUE TITLE
Exclude fields in WMS/WFS doesn't show anymore in 3.16

### ISSUE THREAD

**Issue by Gustry** [qgis/QGIS#39699]
**Describe the bug**

In QGIS 3.16/Master, fields which are hidden in WMS/WFS doesn't show in the UI.

Same project opened in QGIS 3.10 and QGIS Master

![Screenshot from 2020-10-29 16-27-28](https://user-images.githubusercontent.com/1609292/97595606-23ef2a80-1a04-11eb-9bbb-00260b5423c3.png)

**How to Reproduce**

Open the given project in QGIS 3.10 and Master : 
[tests.zip](https://github.com/qgis/QGIS/files/5459504/tests.zip)

1. Make a layer with some hidden fields in WMS/WFS, a project coming from 3.10, or using PyQGIS in QGIS Master.
2. Open vector layer properties, it doesn't show up

**QGIS and OS versions**

QGIS version | 3.17.0-Master | QGIS code revision | 7a14973234
-- | -- | -- | --
Compiled against Qt | 5.12.8 | Running against Qt | 5.12.8
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 13.0 (Ubuntu 13.0-1.pgdg20.04+1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Ubuntu 20.04.1 LTS | This copy of QGIS writes debugging output.
Active python plugins | quick_map_services; lizmap; plugin_reloader; Mergin; pg_metadata; cadastre; db_manager; processing

I think @3nids you made some changes here, no?

**Comment by gioman** [comment]
@Gustry if you click on the "configuration" dropdown you get the options to exclude from WMS/WFS

**Comment by Gustry** [comment]
@gioman As you can see in my screenshot, the "Configuration" is all white, but it should be different, the field configuration is not the same.

My screenshot shows the **same** project opened in QGIS 3.10 and 3.16.
The project is in the ZIP.

**Comment by gioman** [comment]
>  The project is in the ZIP.

@Gustry this is your project in my 3.16

![Screenshot_20201029_174147](https://user-images.githubusercontent.com/1951107/97611457-1f2f7400-1a0e-11eb-943c-191a318847ab.png)

**Comment by Gustry** [comment]
@gioman Look my screenshot in QGIS 3.10, on the top.
Some fields are already hidden in WMS and WFS for the last **3** fields.
So the list shouldn't be all white in QGIS 3.16, there should be already some checkbox **checked**.

Sorry if I wasn't clear, I'm not in front of QGIS ;-)

**Comment by 3nids** [comment]
I'll have a look at it tomorrow.

**Comment by gioman** [comment]
> Sorry if I wasn't clear, I'm not in front of QGIS ;-)

@Gustry no, sorry me as I only got now what you meant, and it was pretty clear.
