### ISSUE TITLE
Silent Installation issue with postinstall batch scripts

### ISSUE THREAD

**Issue by pnrthomp** [qgis/QGIS#39723]
**Describe the bug**

- Silent installation fails during postinstall batch scripts.

From postinstall.log:
C:\PROGRA~1\QGIS3~1.10>exit /b 0 
Running postinstall qgis-ltr-grass-plugin7.bat...

C:\PROGRA~1\QGIS3~1.10>textreplace -std -t bin\qgis-ltr-grass7.bat 

C:\PROGRA~1\QGIS3~1.10>if "C:\Users\Public\Desktop\QGIS 3.10" == "" set OSGEO4W_DESKTOP=~$folder.common_desktop$ 

C:\PROGRA~1\QGIS3~1.10>copy bin\qgis-ltr-bin.exe bin\qgis-ltr-bin-g7.exe 
        1 file(s) copied.

C:\PROGRA~1\QGIS3~1.10>copy bin\qgis-ltr-bin.vars bin\qgis-ltr-bin-g7.vars 
        1 file(s) copied.

C:\PROGRA~1\QGIS3~1.10>call "C:\PROGRA~1\QGIS3~1.10\bin\qgis-ltr-grass7.bat" --postinstall 
The system cannot find the path specified.
'qt5_env.bat' is not recognized as an internal or external command,
operable program or batch file.
'py3_env.bat' is not recognized as an internal or external command,
operable program or batch file.

The installation stops at this point. No start menu items are created.

**How to Reproduce**

QGIS-OSGeo4W-3.10.11-1-Setup-x86_64.exe (probably all 3.xx).

**Additional context**
- system is Windows 10

[postinstall.log](https://github.com/qgis/QGIS/files/5466994/postinstall.log)

**Comment by gioman** [comment]
@pnrthomp can't confirm here on a Windows 10 machine.

**Comment by gioman** [comment]
Closing for lack of further feedback.
