### ISSUE TITLE
Problem (also crash) with NetCDF files

### ISSUE THREAD

**Issue by PedroVenancio** [qgis/QGIS#39729]
I'm getting the problem I've reported some days ago in mailing list, now in QGIS 3.16:

http://osgeo-org.1560.x6.nabble.com/gdal-dev-QGIS-from-OSGeo4W-crashes-with-latest-update-on-NetCDF-td5448139.html

There I've reported a crash when I was trying to open some NetCDF file (for instance http://mf2.ipma.pt/downloads/?latest=arome.2m.relative_humidity&region=PT2 ) as raster file, as mesh layer or simply when I open a folder with a NetCDF file inside Browser.

Today I've also got a crash in the first time I opened a NetCDF, but I can't reproduce the crash now. 

However, I can't, for instance, to convert the NetCDF to GeoTIFF and the problem seems related:

```
gdal_translate -of GTiff -co COMPRESS=DEFLATE -co PREDICTOR=2 -co ZLEVEL=9 NETCDF:"D:\\AROME_OPER_001_FC_SP_PT2_025_RH_2-HTGL_2020103100.nc":NDVI D:/AROME_OPER_001_FC_SP_PT2_025_RH_2-HTGL_2020103100.tif
GDAL command output:
Warning 1: Recode from UTF-8 to CP_ACP failed with the error: "Invalid argument".

Warning! ***HDF5 library version mismatched error***

The HDF5 header files used to compile this application do not match

the version used by the HDF5 library to which this application is linked.

Data corruption or segmentation faults may occur if the application continues.

This can happen when an application was compiled by one version of HDF5 but

linked with a different version of static or shared HDF5 library.

You should recompile the application or check your shared library related

settings such as 'LD_LIBRARY_PATH'.

You can, at your own risk, disable this warning by setting the environment

variable 'HDF5_DISABLE_VERSION_CHECK' to a value of '1'.

Setting it to 2 or higher will suppress the warning messages totally.

Headers are 1.10.4, library is 1.10.5

SUMMARY OF THE HDF5 CONFIGURATION

=================================



General Information:

-------------------

HDF5 Version: 1.10.5

Configured on: 2020-10-20

Configured by: Visual Studio 14 2015 Win64

Host system: Windows-10.0.19041

Uname information: Windows

Byte sex: little-endian

Installation point: D:/src/osgeo4w64/src/hdf5/osgeo4w/install-x86_64



Compiling Options:

------------------

Build Mode: 

Debugging Symbols: 

Asserts: 

Profiling: 

Optimization Level: 



Linking Options:

----------------

Libraries: 

Statically Linked Executables: OFF

LDFLAGS: /machine:x64

H5_LDFLAGS: 

AM_LDFLAGS: 

Extra libraries: 

Archiver: 

Ranlib: 



Languages:

----------

C: yes

C Compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe 19.0.24215.1

CPPFLAGS: 

H5_CPPFLAGS: 

AM_CPPFLAGS: 

CFLAGS: /DWIN32 /D_WINDOWS /W3

H5_CFLAGS: 

AM_CFLAGS: 

Shared C Library: YES

Static C Library: YES



Fortran: OFF

Fortran Compiler: 

Fortran Flags: 

H5 Fortran Flags: 

AM Fortran Flags: 

Shared Fortran Library: YES

Static Fortran Library: YES



C++: ON

C++ Compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe 19.0.24215.1

C++ Flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc

H5 C++ Flags: 

AM C++ Flags: 

Shared C++ Library: YES

Static C++ Library: YES



JAVA: OFF

JAVA Compiler: 



Features:

---------

Parallel HDF5: OFF

Parallel Filtered Dataset Writes: 

Large Parallel I/O: 

High-level library: ON

Threadsafety: ON

Default API mapping: v110

With deprecated public symbols: ON

I/O filters (external): DEFLATE DECODE

MPE: 

Direct VFD: 

dmalloc: 

Packages w/ extra debug output: 

API Tracing: OFF

Using memory checker: OFF

Memory allocation sanity checks: OFF

Function Stack Tracing: OFF

Strict File Format Checks: OFF

Optimization Instrumentation: 

Bye...

Execution completed in 1.46 seconds
Results:
{'OUTPUT': 'D:/AROME_OPER_001_FC_SP_PT2_025_RH_2-HTGL_2020103100.tif'}

Loading resulting layers
The following layers were not correctly generated.
• D:/AROME_OPER_001_FC_SP_PT2_025_RH_2-HTGL_2020103100.tif
You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.
```

QGIS version | 3.16.0-Hannover | QGIS code revision | 43b64b13f3
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)

I asked a friend to test and he confirms the crash both at add data, browser e drag and drop.

**Comment by PedroVenancio** [comment]
Also confirmed in 3.10.11

QGIS version
3.10.11-A Coruña
QGIS code revision
d2171173e4
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)

**Comment by jelreyes** [comment]
I am having the same problem with QGIS LTR, QGIS master/weekly (QGIS 3.15) in Windows OS.

**Comment by PedroVenancio** [comment]
@jef-n Can you check if this issue is related to the rebuild of netCDF lib against the new HDF5 lib?

**Comment by jef-n** [comment]
Fixed in OSGeo4W

**Comment by t31060** [comment]
when i try to open a netcdf file qgis just closes, no message error, just close
