### ISSUE TITLE
No python header files in QGIS 3.16 for MA

### ISSUE THREAD

**Issue by spengli-berlin** [qgis/QGIS#39728]
The changed python module handling in QGIS 3.16 works quite well. However, when I try to install psutil module, I get the error "fatal error: 'Python.h' file not found".
Can I install the python-dev package in the QGIS for that?

**Comment by spengli-berlin** [comment]
The changed python module handling in QGIS 3.16 works quite well. However, when I try to install psutil module, I get the error  "fatal error: 'Python.h' file not found".
Can I install the python-dev package in the QGIS for that?

**Comment by gioman** [comment]
@spengli-berlin please ask questions in the users or developers mailing list, or use the QGIS irc channel. Thanks!
