### ISSUE TITLE
QGIS losing data when value relation column types are mismatched

### ISSUE THREAD

**Issue by tomasMizera** [qgis/QGIS#39722]
**Describe the bug**
Value relation data might get lost when referenced layer in value relation widget has key column of different data type than original layer has.

**How to Reproduce**

1. Have project with two layers:
   - Layer A is a vector layer (in screenshots called _test_) with point geometry and contains attribute of type **integer** which will be used for value relation (called _valuerelation_ in screenshots)
   - Layer B is a no-geometry layer (in screenshots called _reftable_) and contains **string** column type (called _type_ in screenshots) which will be used as referenced column 

![image](https://user-images.githubusercontent.com/22449698/97732405-c4ae1a80-1ad6-11eb-8fdc-f939b6b43c25.png)

2. Right click on layer A -> properties -> Attributes Form
3. Setup valuerelation to be a `value relation widget` that references Layer B with key column `type` (the string one we created)
![image](https://user-images.githubusercontent.com/22449698/97732475-dee7f880-1ad6-11eb-906f-4fb779136a37.png)

4. Apply and close
5. Toggle editing and create new point on Layer A (remember value you put in to valuerelation)
![image](https://user-images.githubusercontent.com/22449698/97732731-430abc80-1ad7-11eb-898b-673f891654cc.png)

6. Save layer edits and exit editing mode
7. Inspect created feature with `Identify features`
8. You will notice that value of value relation attribute is **zero** (even though we set it to `type28`)!
![image](https://user-images.githubusercontent.com/22449698/97732798-5ae24080-1ad7-11eb-9f9b-57652710b66b.png)

**QGIS and OS versions**

QGIS version | 3.14.0-Pi | QGIS code revision | 7da0f639f7
-- | -- | -- | --
Compiled against Qt | 5.12.8 | Running against Qt | 5.12.8
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.2 (Ubuntu 12.2-4) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Ubuntu 20.04 LTS | This copy of QGIS writes debugging output.
Active python plugins | OSMDownloader; plugin_reloader; Mergin; QuickOSM; MetaSearch; processing; db_manager

**Additional context**
You propably noticed that we used **Integer** attribute to reference **Text** attribute in referenced layer.
I think QGIS should either not allow to create value relationship when types are mismatched or at least warn user when creating new feature that his value relation data might be lost.

[Link to project stored on Mergin](https://public.cloudmergin.com/projects/tomas/vr-forms/tree)

**Problem**

QVariant's `toInt()` function returns `0` when it can not convert QVariant to integer, this is probably the problem.

**Comment by gioman** [comment]
> 3.14.0-Pi

@tomasMizera this is too old, you must check if this confirms also on the latest 3.16.

**Comment by saberraz** [comment]
Tested in master and works as expected.
