### ISSUE TITLE
Keyboard shortcuts not functional.

### ISSUE THREAD

**Issue by Dizzy84** [qgis/QGIS#39735]
Hi,
The "modify the following entity in the attribute table" keyboard shortcut does not work.
As for the previous entity.

Best regards

**Comment by roya0045** [comment]
Did you check if the shortcut was set or if the layer is in edit mode?

**Comment by Dizzy84** [comment]
Hi, thank you for your answer.
I finally understood that the shortcut only works in "form view" of the
attribute table.

So now I'm using it. But I opened another post to suggest creating a
shortcut that could work in all modes, also in the map view. I've seen that
some people start to create python functions for that, I tried them but it
didn't work for me:
https://plugins.qgis.org/plugins/go2nextfeature/

Well I continue with the shortcut function in form view.

Thank's a lot for your answer.

Gilles
