### ISSUE TITLE
shortcut to select and focus automatically on next feature

### ISSUE THREAD

**Issue by Dizzy84** [qgis/QGIS#39736]
Hi, 

I'm looking for a tool/shortcut that will allow to move to next record and focus on it automatically.

This could be really useful when you edit existing features.

I've seen that ther is a aolready a shortcut thaat could maybe do what I'm looking for. But it looks like this shortcut dosn't work anymore. So I can't chek if it focus automatically on the next feature. If not, it could be really helpful to have one.

Many thanks, 

Gilles

PS: ther is one on arcgis that you can find description here; in the "selecting in the table" title :
https://desktop.arcgis.com/en/arcmap/10.3/manage-data/tables/keyboard-shortcuts-for-working-with-tables.htm

**Comment by MrChebur** [comment]
There is a plugin for this feature: [go2nextfeature](https://gitlab.com/albertodeluca/go2nextfeature)
