### ISSUE TITLE
"Create constant raster layer" has hardcoded limit for pixel size

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#39732]
**Describe the bug**
If you enter a pixel size smaller than 0.01 in the "Create constant raster layer" processing tool, it will automatically change it to 0.01.

When passing a smaller pixel size to it via pyqgis, it will fail with a `QgsProcessingException`: "Incorrect parameter value for PIXEL_SIZE"

This makes it impossible to use for detailed rasters in coordinates systems with big values like EPSG:4326.

**How to Reproduce**

1. Set your project CRS to EPSG:4326
2. Launch the "Create constant raster layer" processing tool
3. Enter 0.001 as "Pixel size"
4. The tool will automatically set the value to 0.01

**QGIS and OS versions**
QGIS version | 3.17.0-Master | QGIS code revision | 7a14973234
-- | -- | -- | --
Compiled against Qt | 5.15.1 | Running against Qt | 5.15.1
Compiled against GDAL/OGR | 3.3.0dev-a9ff452a51-dirty | Running against GDAL/OGR | 3.3.0dev-a9ff452a51-dirty
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.33.0 | Running against SQLite | 3.33.0
PostgreSQL Client Version | 12.4 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.5 | QScintilla2 Version | 2.11.5
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Arch Linux

**Comment by roya0045** [comment]
Not sure why the default value is smaller than the minvalue https://github.com/qgis/QGIS/blob/6de9f602562d2e6bb9495b4723e63e27e0690244/src/analysis/processing/qgsalgorithmconstantraster.cpp#L69

**Comment by femkepragt** [comment]
Does anyone know if this bug can be solved somehow? Or how I could work around this issue? I still run into this issue, and I don't know how other wise to create an empty raster with a very specific pixel size (608 meters) in CRS EPSG:4326.

**Comment by roya0045** [comment]
@femkepragt try with a crs that is not in degree then reproject it.

**Comment by kannes** [comment]
And be aware that this very specific pixel size in meters would only work for a very small extent in WGS84!

You could probably change the value in the line @roya0045 referenced above and compile it, but that might be complicated depending on your system and knowledge in that area.

**Comment by kannes** [comment]
@alexbruy in https://github.com/qgis/QGIS/pull/39734#issuecomment-739712304 you mentioned working on this in another PR, could you link that here if it exists already? Thanks :)

**Comment by agiudiceandrea** [comment]
It seems a similar issue occurs with the 8 "**Create random raster layer**" processing tools, in which the minimum value for the `PIXEL_SIZE` parameter is set to `0.01` (while, the default value is set to `1`)
https://github.com/qgis/QGIS/blob/2d1aa68f0d044f2aced7ebeca8d2fa6b754ac970/src/analysis/processing/qgsalgorithmrandomraster.cpp#L43-L44

In other tools, the minimum value for similar parameters is set to `0`:
- in the "Convert map to raster" processing tool, the minimum value for the `MAP_UNITS_PER_PIXEL` parameter is set to `0` and the default value is set to `100`
https://github.com/qgis/QGIS/blob/2d1aa68f0d044f2aced7ebeca8d2fa6b754ac970/src/analysis/processing/qgsalgorithmrasterize.cpp#L87-L93
- in the "**Raster calculator**" processing tool, the minimum value for the `CELLSIZE` parameter is set to `0` and the default value is set to `0`
https://github.com/qgis/QGIS/blob/9da78ed2e4afb2347720427a857a10563f67c5ce/python/plugins/processing/algs/qgis/RasterCalculator.py#L83-L86

**Comment by Pedro-Murteira** [comment]
This is still valid on QGIS 3.22.3.

**Comment by kannes** [comment]
`native:rasterize` simply fails with 
```
Error creating GDAL output layer
Execution failed after 0.07 seconds
```
if one sets the `MAP_UNITS_PER_PIXEL` to `0`. GDAL throws an error in the background which is not communicated tot he user (only in the terminal): `ERROR 1: Attempt to create 0x0 dataset is illegal,sizes must be larger than zero.`

I think I can handle the coding to make them all the Raster Creation algorithms (and maybe `native:rasterize` too) use `0` as default value and fail algorithm execution with a proper red message in the log if the size is not >0. That seems more reasonable as it gives freedom to the user and fails "gracefully".

Please assign the issue to me :)
