### ISSUE TITLE
QGIS 3.16 Execute as Batch Process - Can't add new row

### ISSUE THREAD

**Issue by jcm36** [qgis/QGIS#39740]
**Describe the bug**
In the new QGIS 3.16 release, I am no longer able to add a new row (new batch item) in the "Exectue Batch Process" window for all of the various processing tools

**How to Reproduce**

1. Right Click on any of the processing tools (tested with my own custom models, and built in processing tools)
2. Select the "Execute as Batch Process" menu item
3. Fill in the input boxes for the first item
4. Click the "+" Add New Row button to add a new batch item. A new row does not get added

**QGIS and OS versions**

QGIS version
3.16.0-Hannover
QGIS code revision
43b64b13f3
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
AnotherDXF2Shape; 
CalculateGeometry; 
kmltools; 
linz-data-importer; 
MapsPrinter; 
profiletool; 
qchainage; 
qepanet; 
QuickOSM; 
quick_map_services; 
processing

**Additional context**

N/a

**Comment by roya0045** [comment]
Already reported and fixed

**Comment by jcm36** [comment]
Great, thanks!
