### ISSUE TITLE
Create Points Layer From Table algorithm does not work in processing modeler

### ISSUE THREAD

**Issue by basilrabi** [qgis/QGIS#39744]
**Describe the bug**

The algorithm `Create Points Layer From Table` works if used directly. But when using it in the processing modeler, geometries are created with `NULL` coordinates.

**How to Reproduce**
100%

1. Extract and open the [project](https://github.com/qgis/QGIS/files/5473133/project.zip).
2. In the processing toolbox, Open `Project models` > `Test` > `Test`
3. Using the layer `data` as input, run the algorithm.

You will see no geometries in the output layers although I'm not confident if I used the algorithm correctly in the modeller 🤔.

**QGIS and OS versions**

QGIS version | 3.17.0-Master | QGIS code branch | master 9935bbe05e6e8709bc3fc120c23c721e862726f5
-- | -- | -- | --
Compiled against Qt | 5.15.1 | Running against Qt | 5.15.1
Compiled against GDAL/OGR | 3.1.3 | Running against GDAL/OGR | 3.1.3
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.33.0 | Running against SQLite | 3.33.0
PostgreSQL Client Version | 12.4 | SpatiaLite Version | 5.0.0-beta0
QWT Version | 6.1.5 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Fedora 33 (Workstation Edition)
Active python plugins | string_reader; quick_map_services; MetaSearch; db_manager; processing

**Comment by gioman** [comment]
@basilrabi the problem seems to be the space in the columns names of your CSV, I removed it and it worked as expected.

**Comment by basilrabi** [comment]
[no_space_in_column.zip](https://github.com/qgis/QGIS/files/5480588/no_space_in_column.zip)
Tried removing the spaces in column names (csv and processing model). Also made the column names small letters. Still no luck. Geometry still has NULL coordinates. Can I see your project file that works @gioman ?

**Comment by gioman** [comment]
> Can I see your project file that works @gioman ?

@basilrabi I used your project, I just removed the spaces and re-run the model.

**Comment by basilrabi** [comment]
@gioman , does [this project](https://github.com/qgis/QGIS/files/5480588/no_space_in_column.zip) work for you without any modification?

**Comment by gioman** [comment]
> @gioman , does [this project](https://github.com/qgis/QGIS/files/5480588/no_space_in_column.zip) work for you without any modification?

@basilrabi you must get rid of the double quotes around the column names.

**Comment by basilrabi** [comment]
Thank you @gioman
