### ISSUE TITLE
[Oracle] Cannot load any oracle layer 

### ISSUE THREAD

**Issue by troopa81** [qgis/QGIS#39759]
**Describe the bug**

There is the following error when loading an oracle layer 

```
Layer is not valid : The layer dbname='XEPDB1' host=localhost port=1521 user='QGIS' password='qgis' srid=5698 type=Polygon25D table="QGIS"."POLY_DATA" (GEOM) is not a valid layer and can not be added to the map. Reason: Invalid provider
```

**How to Reproduce**

1. Create an oracle connection
2. Double click on a table from the browser
3. the error message appears, no layer is loaded

**QGIS and OS versions**

QGIS master
Debian testing

**Additional context**

This is due to #39656. It's because not all providers implement [correctly decodeUri method](https://github.com/qgis/QGIS/blob/master/src/core/qgsprovidermetadata.h#L332), like Oracle for instance. I don't know if Oracle is the only one not implementing it. Should we just implement it in Oracle or deal with the case where the provider doesn't implement it?

cc @rduivenvoorde

**Comment by nyalldawson** [comment]
We should implement this for Oracle -- there's other things which are broken if the provider doesn't implement this

**Comment by rduivenvoorde** [comment]
@troopa81 my issue with oracle is that I do not have an instance available to test. Is there any Oracle provider publically available?

@jef mmm, thinking out loud now: issues.qgis.org is a big machine doing almost nothing... what about running this 'free' oracle version there? And then (we can give aacces to) people with ssh access to that machine, so they can create a tunnel (over ssh) to the Oracle db there? Load some (test) data there etc etc? I will sent an email to the dev list

**Comment by troopa81** [comment]
@rduivenvoorde 

You can run an oracle instance with this command

```shell
docker run -d -e ORACLE_SID="XE" -e ORACLE_PWD="adminpass" -e ORACLE_PDB="ORCLPDBTEST" -e ORACLE_CHARACTERSET="AL32UTF8" -p 0.0.0.0:1521:1521 "oslandia/oracle-for-qgis-tests:18.4.0-xe"
```
and from the QGIS root dir to populate the base

```shell
./tests/testdata/provider/testdata_oracle.sh localhost
```

> what about running this 'free' oracle version there? 

Using docker here is IMHO the best solution because it's simple and it's the reference for QGIS CI.

**Comment by rduivenvoorde** [comment]
Docker is fine, though you also need sqlplus to run the testdata... and it failed...

Anyway, I think the Delimited Line provider (csv) has the same problem...

**Comment by rduivenvoorde** [comment]
Ok, running. It takes 10 minutes to start up on my (rather beefy) laptop...
(checking with `docker ps -a` till it shows 'healty')

After installing sqlplus I was able to run 
```
./tests/testdata/provider/testdata_oracle.sh localhost
```
Which seem to go fine.
Then I can connect to database XEPDB1 with user QGIS... (why XEPDB1?, thought the db was called XE? And see testdata.
Next step: compile oracle with oracle provider...

**Comment by troopa81** [comment]
> why XEPDB1?, thought the db was called XE? And see testdata.

I'm no Oracle expert, but I think PDB (Pluggable Database) are *databases* and XEPDB1 is the default one. To me create a PDB is the equivalent of *createdb* in PostGres. Not sure though.

> Next step: compile oracle with oracle provider...

Thank you for taking care of this. Let me know if you meet some issues, maybe I can help.

**Comment by rduivenvoorde** [comment]
Via the dialogs I can load all data fine. It is only via Browser that I get an error yes?

**Comment by troopa81** [comment]
> Via the dialogs I can load all data fine. It is only via Browser that I get an error yes?

Yes, indeed

**Comment by rduivenvoorde** [comment]
Ok, running db and connecting with QGIS...

**Comment by rduivenvoorde** [comment]
@nyalldawson grepping on decodeUri it seems that actually ONLY postgres is implementing that?

```
$ cd src
$ grep -ir QgsPostgresProviderMetadata::decodeUri
providers/postgres/qgspostgresprovider.cpp:QVariantMap QgsPostgresProviderMetadata::decodeUri( const QString &uri )
```

So you say ALL providers should have a decodeUri (and probably also a 'encodeUri') like pg provider? See
https://github.com/qgis/QGIS/blob/master/src/providers/postgres/qgspostgresprovider.cpp#L5713-L5802

In python console doing `iface.mapCanvas().currentLayer().dataProvider().uri().encodedUri()` does only show parts of all metadata for some types of layers here...

**Comment by rduivenvoorde** [comment]
If I just copy the postgres implementatie, the browser works again.!
So I have to find out the possible uri parts and create a proper version.
But will be friday probably, because tomorrow I've other responsibilities...

**Comment by nyalldawson** [comment]
> actually ONLY postgres is implementing that

That's cos you're grepping for QgsPostgresProviderMetadata::decodeUri 😆

> does only show parts of all metadata for some types of layers here..

encodedUri is a different beast - it does something else entirely

**Comment by rduivenvoorde** [comment]
> That's cos you're grepping for QgsPostgresProviderMetadata::decodeUri laughing

ah, duh...  Sorry
Ok, so implement decodeUri ann encodeUri (and encodedUri is different...)

**Comment by nyalldawson** [comment]
Exactly! The crucial part is to make the round trip through decode -> encode lossless
