### ISSUE TITLE
Wrong results converting vectors to Float32 rasters - Rasterize, Rasterization, Round Raster algorithms

### ISSUE THREAD

**Issue by PedroVenancio** [qgis/QGIS#39755]
Because decimal to float (IEEE754) conversion is not an exact conversion, I'm getting wrong results in reclassifications done after converting vectors to rasters.

I have a polygons layer with a "value" field that has 2 decimal places.

Converting it to raster with **gdal_rasterize** (**Rasterize (vetor to raster)**), the output is different if I choose it as Float32 or Float64.

Here is a sample Project: https://cld.pt/dl/download/61894ebd-ade0-4f12-8aa3-1405ab2690cc/Float_Issue_Project.zip

These are the commands I use (inside QGIS or in CLI):

```
gdal_rasterize -l polygons -a value -tr 5.0 5.0 -a_nodata 0.0 -te 61738.6841 107228.3171 63464.9242 108429.7802 -ot Float32 -of GTiff D:\Testes\Float_Issue\polygons.gpkg D:/Testes/Float_Issue/polygons_rasterize_float32.tif

Info:
Name polygons_rasterize_float32
Path D:\Testes\Float_Issue\polygons_rasterize_float32.tif
CRS EPSG:3763 - ETRS89 / Portugal TM06 - Projected
Extent 61738.6840999999985797,107229.7801999999937834 : 63463.6840999999985797,108429.7801999999937834
Unit meters
Width 345
Height 240
Data type Float32 - Thirty two bit floating point
GDAL Driver Description GTiff
GDAL Driver Metadata GeoTIFF
Dataset Description D:\Testes\Float_Issue\polygons_rasterize_float32.tif
Compression
Band 1
STATISTICS_MAXIMUM=18537
STATISTICS_MEAN=3782.009546874
STATISTICS_MINIMUM=0.12999999523163
STATISTICS_STDDEV=7001.5216220675
STATISTICS_VALID_PERCENT=100
More information
AREA_OR_POINT=Area
Dimensions X: 345 Y: 240 Bands: 1
Origin 61738.7,108430
Pixel Size 5,-5
```

```
gdal_rasterize -l polygons -a value -tr 5.0 5.0 -a_nodata 0.0 -te 61738.6841 107228.3171 63464.9242 108429.7802 -ot Float64 -of GTiff D:\Testes\Float_Issue\polygons.gpkg D:/Testes/Float_Issue/polygons_rasterize_float64.tif

Info:
Name polygons_rasterize_float64
Path D:\Testes\Float_Issue\polygons_rasterize_float64.tif
CRS EPSG:3763 - ETRS89 / Portugal TM06 - Projected
Extent 61738.6840999999985797,107229.7801999999937834 : 63463.6840999999985797,108429.7801999999937834
Unit meters
Width 345
Height 240
Data type Float64 - Sixty four bit floating point
GDAL Driver Description GTiff
GDAL Driver Metadata GeoTIFF
Dataset Description D:/Testes/Float_Issue/polygons_rasterize_float64.tif
Compression
Band 1
STATISTICS_MAXIMUM=18537
STATISTICS_MEAN=3782.0095468599
STATISTICS_MINIMUM=0.13
STATISTICS_STDDEV=7001.521622075
STATISTICS_VALID_PERCENT=100
More information
AREA_OR_POINT=Area
Dimensions X: 345 Y: 240 Bands: 1
Origin 61738.7,108430
Pixel Size 5,-5
```

Looking at output in Value Tool:

![imagem](https://user-images.githubusercontent.com/1331581/97877486-2bb91280-1d15-11eb-92d6-38342db8d028.png)

So, if the conversion is to a Float64 raster, pixel values have 2 decimal places, as the original data.

If the conversion is to a Float32 raster, several pixel values assume 16 decimal places.

```
Float32: 0.2199999988079071
Float64: 0.22
Original value: 0.22
```

This is due, as Andrea Giudiceandrea said in the dev mailing list, to the decimal to floating point numbers conversion, and can be confirmed here:
https://www.binaryconvert.com/convert_double.html

The most accurate representation of **0.22** in
float single precision (**32 bit**) is  **0.2199999988079071044921875**
float double precision (**64 bit**) is **0.220000000000000001110223024625** 

Where this becomes a serious problem is when the values are used, for instance, for a reclassification process (with **Reclassify by Table**). Imagine these rules:

```
[0 - 0.22[ = 1
[0.22 - 0.5[ = 2
>= 0.5 = 3
```

Pixels 0.22 are reclassified as 2;
Pixels 0.2199999988079071 are reclassified as 1.

![imagem](https://user-images.githubusercontent.com/1331581/97877985-ee08b980-1d15-11eb-91fb-dc3addcbdd02.png)

So, Float64 gives the right results and Float32 gives wrong results.

However, if instead of gdal_rasterize I use **OTB Rasterization**, no matter whether I use float (Float32) or double (Float64) dtype, I always get wrong results, just like gdal_rasterize with Float32.

This can be really tricky and lead to wrong results.

I would say that as a workaround, maybe making Float64 as GDAL -ot <type> default could be safer?

Also the **Round Raster** algorithm fails here, because if the input is a Float32, for instance, with 0.2199999988079071044921875, the output will be as the same type and it is not rounded.

**Comment by gioman** [comment]
> Also the **Round Raster** algorithm fails here, because if the input is a Float32, for instance, with 0.2199999988079071044921875, the output will be as the same type and it is not rounded.

@PedroVenancio I fully subscribe this issue (thanks Pedro for the very precise report), it is a pain work with such data in all ways: analysis, re-classification and symbology.

**Comment by alexbruy** [comment]
Shouldn't it be reported in the GDAL tracker as this also happens with calling GDAL directly from the command-line?

**Comment by alexbruy** [comment]
@PedroVenancio is this a bug? The `Rasterize (vector to raster)` algorithm allows you to choose output data type, so you can always get desired result. Or I miss your point here?

**Comment by PedroVenancio** [comment]
> @PedroVenancio is this a bug? The `Rasterize (vector to raster)` algorithm allows you to choose output data type, so you can always get desired result. Or I miss your point here?

Hi @alexbruy 
In fact I believe it is not a bug, because it is due to the decimal to floating point numbers conversion, and even the Float64 does not give a precise representation 
0.22 -> the most accurate representation in float double precision (64 bit) is 0.220000000000000001110223024625

But it could lead to wrong results. 

Making Float64 as GDAL -ot default was just a suggestion as a workaround, to be safer, but it is also not a final solution.

@rouault What do you think about this?

Thanks!
