### ISSUE TITLE
qgsXYZTilesConnections import fails with "Connection with name [name] already exists. Overwrite?"

### ISSUE THREAD

**Issue by pathmapper** [qgis/QGIS#39756]
**Describe the bug**
`qgsXYZTilesConnections` import fails with `Connection with name [name] already exists. Overwrite?` despite the names are different.

**How to Reproduce**

1. Create an XML file with the following content or take it from the zip file: [xyz_sample_connections.zip](https://github.com/qgis/QGIS/files/5475526/xyz_sample_connections.zip)

```XML
<!DOCTYPE connections>
<qgsXYZTilesConnections version="1.0">
    <xyztiles tilePixelRatio="0" password="" url="https://tile.openstreetmap.org/{z}/{x}/{y}.png" zmax="19" referer="" name="OpenStreetMap" zmin="0" authcfg="" username=""/>
    <xyztiles tilePixelRatio="0" password="" url="http://11.22.333.444/osm/{z}/{x}/{y}.png" zmax="19" referer="" name="OpenStreetMap (self hosting)" zmin="0" authcfg="" username=""/>
</qgsXYZTilesConnections>
```
2. Clear all existing XYZ Tile connections in QGIS browser 
3. Import the XML file (_Load Connections..._ -> _Select all_ -> _Import_)
4. See error:  `Connection with name 'OpenStreetMap' already exists. Overwrite?`

Despite the names are different, it looks like not the whole name is considered - only the first part until the blank is considered.

<img src="https://user-images.githubusercontent.com/20856381/97878207-9d498e80-1d1e-11eb-9775-8477a485b9f4.gif" width="600">

**QGIS and OS versions**

QGIS version | 3.16.0-Hannover | QGIS code revision | 43b64b13f3
-- | -- | -- | --
Compiled against Qt | 5.11.3 | Running against Qt | 5.11.3
Compiled against GDAL/OGR | 2.4.0 | Running against GDAL/OGR | 2.4.0
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.27.2 | Running against SQLite | 3.27.2
PostgreSQL Client Version | 11.9 (Debian 11.9-0+deb10u1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.10.4
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Debian GNU/Linux 10 (buster)
Active python plugins | ClipMultipleLayers; quick_map_services; scriptrunner3; LAStools; canvas_clipper; savedialog; loadthemall; clipper; kmltools; qgis-maptiler-plugin; MapsPrinter; mmqgis; pluginbuilder3; vector_tiles_reader; layerGroupFilter; plugin_reloader; realcentroid; mask; MetaSearch; db_manager; processing

**Comment by jgrocha** [comment]
Thank you @pathmapper fr reporting this.

This only happens, because you are using the **OpenStreeMap** as an identifier. If you change OpenStreetMap to **OpenSeaMap** and **OpenSeaMap (self hosting)**, for example, everything will work as expected.

OpenStreetMap identifier is used internally, as the default XYZ Tile service provided. If the user deletes it, we know that the user does not want it and **we don't show it again**. I'll review the logic behind. It can be improved for sure.

**Comment by pathmapper** [comment]
Hi @jgrocha, thanks for your explanation and looking into this.

You're right, with **OpenSeaMap** and **OpenSeaMap (self hosting)** it is working as expected.

We're generating and hosting our own OSM tiles to take some traffic from the OSM servers but want to keep also the default OSM server connection.

Good to know that this limited to **OpenStreeMap** as an identifier and not a general issue :+1:.

**Comment by pathmapper** [comment]
@gioman is this fixed?

**Comment by gioman** [comment]
> @gioman is this fixed?

@pathmapper I don't think there is anything to fix, you can't create connections with "OpenStreeMap" as identifier. Eventually this can be documented (if not already).

**Comment by pathmapper** [comment]
@gioman thanks, you're right about the current situation. @jgrocha wrote in https://github.com/qgis/QGIS/issues/39756#issuecomment-721152095:

>  I'll review the logic behind. It can be improved for sure.

So maybe _fixed_ was the wrong wording but I assumed this issue would stay open to track the improvement.
But if you think it's better to close here, that's fine with me.

**Comment by pathmapper** [comment]
@gioman it turns out that you **can** create a XYZ connection with "OpenStreetMap" as identifier if you do it manually with 
`New Connection...`.

So the issue here is that `Import Connections...` fails for a connection with "OpenStreetMap" as identifier.

https://user-images.githubusercontent.com/20856381/104034133-c845d800-51d0-11eb-8eed-45f348f8c233.mp4

**Comment by pluberd** [comment]
It also fails with "Mapzen Global Terrain".

Overall I don't like this "feature". If a user deletes a default entry, why does it make sense to block reimporting it later? It is absolutly senseles and only steals time of the useres to find this thread.
