### ISSUE TITLE
Will only connect to python via the app store in Pop!_OS 20.1 

### ISSUE THREAD

**Issue by WHBSpeiser** [qgis/QGIS#39767]
Hi!

When QGIS is run in Pop!_OS 20.1 if it is opened either through the application shortcut or via terminal, an error occurs where QGIS doesn't run with python because PyQt5 isn't connecting. However, this error doesn't occur when opened directly though the app store.

**Comment by Pedro-Murteira** [comment]
Hello @WHBSpeiser, I'm not able to test due to not having this OS installed on any of my machines, but did you by any chance come across this issue more recently?

**Comment by WHBSpeiser** [comment]
Hi Pedro,

Honestly don't really remember this issue, but have used QGIS since and the OS has been updated to 21.0-  I'm sure either the issue has been resolved with the OS or the issue was just some botched installation.  Thanks for your help and contributions to this awesome platform, cheers!
