### ISSUE TITLE
Provide packages for Ubuntu 20.10 (Groovy Gorilla)

### ISSUE THREAD

**Issue by vpavic** [qgis/QGIS#39764]
The https://qgis.org/ubuntu/dists/ doesn't provide packages for `groovy` yet.
Please consider adding this, as Ubuntu 20.10 was released on Oct 22nd.

**Comment by vpavic** [comment]
I just noticed 09d6185, which landed in `master` less than hour ago (I searched the repo before that apparently) - I assume that means this is basically resolved?

**Comment by rjhale1971** [comment]
Just checking in - I'm actually looking for the same thing. I upgraded one test box and realized there isn't a 20.10 package yet.

**Comment by vpavic** [comment]
This seems resolved, as https://qgis.org/ubuntu/dists/ now lists `groovy`.
It would be nice if someone from the maintainers could confirm though.
