### ISSUE TITLE
Open Data Source Manager Update issue

### ISSUE THREAD

**Issue by jhpark16** [qgis/QGIS#39768]
Open data source manger does not show the content.

To reproduce this problem,
1. Start QGIS LTR version 3.10.11-A Coruna (3.10.11-1-setup_x86-x64.exe) and add a vector data source by clicking "open data source manager" button
2.Choose a vector layer, add and close the dialog window.
3. Click "open data source manager" button and Vector layer does not show any content (source type and source)
4. Choose other entry such as Raster and choose vector again, it will show the source type and source.
5. I believe it is a bug introduced in a recent version.
Thanks.

**Comment by gioman** [comment]
> Click "open data source manager" button and Vector layer does not show any content (source type and source)

@jhpark16 cannot confirm here, tested on Windows 10.

**Comment by gioman** [comment]
Closing for lack of further feedback.
