### ISSUE TITLE
QGIS crashes when adding PostGIS raster layer

### ISSUE THREAD

**Issue by Betzebu1959** [qgis/QGIS#39779]
**Describe the bug**

Add Layer -> add raster layer --> select Postgis table --> add

**QGIS and OS versions**

**Additional context**

## User Feedback

Event systematically occurs when trying to add a raster layer from a Postgis raster column

## Report Details

**Crash ID**: [0febf7b9d900af49a45ae44ebd556853fdd3c708](https://github.com/qgis/QGIS/search?q=0febf7b9d900af49a45ae44ebd556853fdd3c708&type=Issues)

**Stack Trace**
<pre>
GDALGenImgProjTransform :
GDALWarpOperation::ComputeSourceWindow :
GDALWarpOperation::CollectChunkListInternal :
GDALWarpOperation::CollectChunkList :
GDALWarpOperation::ChunkAndWarpImage :
QgsGdalUtils::resampleSingleBandRaster qgsgdalutils.cpp:175
QgsPostgresRasterProvider::readBlock qgspostgresrasterprovider.cpp:499
QgsRasterDataProvider::block qgsrasterdataprovider.cpp:156
QgsMultiBandColorRenderer::block qgsmultibandcolorrenderer.cpp:189
QgsBrightnessContrastFilter::block qgsbrightnesscontrastfilter.cpp:119
QgsHueSaturationFilter::block qgshuesaturationfilter.cpp:123
QgsRasterResampleFilter::block qgsrasterresamplefilter.cpp:164
QgsRasterProjector::block qgsrasterprojector.cpp:890
QgsRasterIterator::readNextRasterPartInternal qgsrasteriterator.cpp:130
QgsRasterDrawer::draw qgsrasterdrawer.cpp:60
QgsRasterLayerRenderer::render qgsrasterlayerrenderer.cpp:321
QgsMapRendererParallelJob::renderLayerStatic qgsmaprendererparalleljob.cpp:353
QtConcurrent::MapKernel<QList<QPair<QgsVectorDataProvider * __ptr64,QgsFeatureRequest> >::iterator,QtConcurrent::FunctionWrapper1<void,QPair<QgsVectorDataProvider * __ptr64,QgsFeatureRequest> const & __ptr64> >::runIteration qtconcurrentmapkernel.h:69
QtConcurrent::MapKernel<QList<QgsImageOperation::ImageBlock>::iterator,QgsImageOperation::GaussianBlurOperation>::runIterations qtconcurrentmapkernel.h:78
QtConcurrent::IterateKernel<QList<QgsImageOperation::ImageBlock>::iterator,void>::forThreadFunction qtconcurrentiteratekernel.h:256
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.16.0-Hannover
QGIS code revision: 43b64b13f3
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

**Comment by elpaso** [comment]
Can you please attach a plain SQL dump of the smallest dataset to reproduce the issue?

**Comment by elpaso** [comment]
Also required: Postgres/Postgis versions.

**Comment by Betzebu1959** [comment]
Dear alpaso,

thanks for the quick reaction.

[browse_test_insert.txt](https://github.com/qgis/QGIS/files/5480974/browse_test_insert.txt)

1. Postgres Version is 13.0
2. Postgis version is  3.0.2
3. Please find the original Psql insert attached


Best regards

**Comment by elpaso** [comment]
There is an error in your dataset:

```sql
qgis_tests=# select srid, st_astext(extent) from raster_columns where r_table_name = 'esa_browse_test';
 srid |                   st_astext                   
------+-----------------------------------------------
 4326 | POLYGON((0 -487,0 0,1218 0,1218 -487,0 -487))
```

the extent does not look like a valid 4326 polygon, that is the root cause of the issue, that said, QGIS/GDAL shouldn't crash.
