### ISSUE TITLE
QGIS 3.16 Version is keep on Crashing and Not Responding

### ISSUE THREAD

**Issue by JannTugas** [qgis/QGIS#39770]
## User Feedback

It keeps on Crashing! Whenever I Move the Vertex point, whenever I move something, it Crashed!

## Report Details

**Crash ID**: [714cdebb4294d246220d704f0aa9214c11d910ad](https://github.com/qgis/QGIS/search?q=714cdebb4294d246220d704f0aa9214c11d910ad&type=Issues)

**Stack Trace**
<pre>
QgsGeometryValidator::checkRingIntersections qgsgeometryvalidator.cpp:69
QgsGeometryValidator::run qgsgeometryvalidator.cpp:328
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.16.0-Hannover
QGIS code revision: 43b64b13f3
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

**Comment by nicogodet** [comment]
Fixed by https://github.com/qgis/QGIS/pull/39769 ?

**Comment by gioman** [comment]
> It keeps on Crashing! Whenever I Move the Vertex point, whenever I move something, it Crashed!

@JannTugas try with a new QGIS profile, no 3rd party plugins installed.

**Comment by ar-jan** [comment]
I have the same problem (same Crash ID).

**Comment by gioman** [comment]
> I have the same problem (same Crash ID).

@ar-jan  try with a new QGIS profile, no 3rd party plugins installed.

**Comment by donkeychen** [comment]
I have a testing file for this crash id
===================================
how to duplicate this issue:
1. There is 1 feature in the layer (multipart, with a self-intersect error)
2. Add this layer.
3. Use vector-geometry tool-check validity tool to find out a self-intersection error point.
4. Start editing
5. Use vector tool to modify any edge connected  to the error point.
===================================
However, if I split the multipart feature into 3 single-part features,
(by using plugin Multipart Split 1.0.0)
the modifying by vector tool would be okay.

[20201122.zip](https://github.com/qgis/QGIS/files/5579243/20201122.zip)

**Comment by gioman** [comment]
> how to duplicate this issue:

@donkeychen have you tried with a new QGIS profile? Also update to the latest 3.10 or 3.16.

**Comment by donkeychen** [comment]
hi, @gioman 

QGIS Info
QGIS Version: 3.16.0-Hannover
QGIS code revision: 43b64b13f3
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

**Comment by gioman** [comment]
>  QGIS Version: 3.16.0-Hannover

@donkeychen the latest is 3.16.1 and you must test with a new QGIS profile.

**Comment by donkeychen** [comment]
hi, @gioman,
I have no 3.16.1, would you help to test the attached file
[20201122.zip](https://github.com/qgis/QGIS/files/5580314/20201122.zip)

**Comment by gioman** [comment]
> hi, @gioman,
> I have no 3.16.1, would you help to test the attached file.
> Thank you.

@donkeychen have you tried with a new QGIS profile and no 3rd party plugins installed?

**Comment by donkeychen** [comment]
I just tried. same issue on 3.16.0-Hannover

**Comment by gioman** [comment]
> I just tried. same issue on 3.16.0-Hannover

@donkeychen you must also try 3.16.1, this point release has received many fixes.

**Comment by nyalldawson** [comment]
This is definitely fixed in 3.16.1

**Comment by donkeychen** [comment]
hi, @gioman  and @nyalldawson ,
I only found 3.16.0.2 from https://qgis.org/downloads/
However, I will try the 3.16.1 if I can get it later.
