### ISSUE TITLE
QGIS 3.16 Turkish language support missing

### ISSUE THREAD

**Issue by berkayoruc** [qgis/QGIS#39774]
QGIS 3.14 has Turkish user interface support. But, there is no Turkish language support in 3.16 for user interface.

**Comment by DelazJ** [comment]
@berkayoruc languages are automatically pulled in QGIS when they are translated at min at 35% (if I recall correctly) to avoid too many texts in English while someone was expecting using another locale.
Here are the ratio of [translations for turkish](https://www.transifex.com/qgis/QGIS/language/tr/) (you will probably need to log in to transifex to see the page). See https://qgis.org/tr/site/getinvolved/translate.html#becoming-a-translator to join translation team and help your community get their language back.

![Capture d’écran 2020-11-03 à 10 08 39](https://user-images.githubusercontent.com/7983394/97966899-ba349f00-1dbc-11eb-9e9c-272156b0c951.png)
@gioman, I'm not sure this is a QGIS issue.

**Comment by gioman** [comment]
>  @gioman, I'm not sure this is a QGIS issue.

@DelazJ Yeah I agree... I didn't think about the minimum amount of translated strings, thanks for catching this.

**Comment by berkayoruc** [comment]
Thank you @DelazJ . I will check what did you say and translate some word for Turkish.

**Comment by nawt12** [comment]
shocked when install 3,16 and can't find the Türkçe Language.  SO we need to translate too much word.

**Comment by katpatuka** [comment]
At transifex I see Turkish 36.2% and 90,601 strings to translate but it's still not available for QGis Zürich...

**Comment by DelazJ** [comment]
@katpatuka it depends on when Turkish reached the 35% threshold: before or after the release date? If after, it's normal. You might want to check the dev version of Zurich which, if I'm not wrong, daily pulls translation. Also, since there are many versions being translated, make sure that the ratio you see is really the one of the version you are expecting.

**Comment by DelazJ** [comment]
Ah, sorry... forgot to say, Zurich is end of life (no 3.18.4), so no there won't be official version with Turkish then. Better target 3.20...
