### ISSUE TITLE
QGIS unexpectedly ended

### ISSUE THREAD

**Issue by Marius-Swart** [qgis/QGIS#39776]
## User Feedback

The program crashed when closing the program by clicking on the -buttonX in the top right hand corner of the window. This happens quite often when closing the program. 

## Report Details

**Crash ID**: [ece7e42b38ddbef052745aa2d10e41e55b5b81bb](https://github.com/qgis/QGIS/search?q=ece7e42b38ddbef052745aa2d10e41e55b5b81bb&type=Issues)

**Stack Trace**
<pre>
QgisApp::projectTemporalRangeChanged :
QMetaObject::activate :
QgsProject::clear :
QgisApp::closeProject :
QgisApp::fileExit :
QWidget::event :
QgisApp::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::close_helper :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processCloseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.14.1-Pi
QGIS code revision: de08d6b71d
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

**Comment by gioman** [comment]
>  QGIS Version: 3.14.1-Pi

@Marius-Swart please try with a new QGIS profile, no 3rd party plugins installed. Also try with the latest LTR release (3.10) or with 3.16 (3.14 is discontinued).

**Comment by nicogodet** [comment]
Btw this kind on crash happens when `layer.providerType()` return an empty string (or unregistered provider ?).

[This QgsProviderMetadata](https://github.com/qgis/QGIS/blob/master/src/app/qgisapp.cpp#L11533L11534) can not be initialized and Qgis crash on [next line](https://github.com/qgis/QGIS/blob/master/src/app/qgisapp.cpp#L11536).

The IF condition could be more robust and check for `layer.providerType() in QgsProviderRegistry.providerList()` ?
