### ISSUE TITLE
QgsMapSettings.setLayers() does not accept list of layers. 

### ISSUE THREAD

**Issue by vegovs** [qgis/QGIS#39788]
**Describe the bug**
QgsMapSettings.setLayers()  requires list of layers but does not accept a list: 

Traceback (most recent call last):
  File "/usr/lib/python3.8/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "<string>", line 84, in <module>
  File "<string>", line 65, in export_basedata_as_img
TypeError: index 0 has type 'list' but 'QgsMapLayer' is expected

**How to Reproduce**
settings = QgsMapSettings()
settings.setLayers([QgsProject.instance().mapLayersByName(layer1), QgsProject.instance().mapLayersByName(layer2)])

**Comment by nyalldawson** [comment]
settings.setLayers([QgsProject.instance().mapLayersByName(layer1), QgsProject.instance().mapLayersByName(layer2)])

mapLayersByName returns a list -- so you're passing a list of lists. 

try

    settings.setLayers([QgsProject.instance().mapLayersByName(layer1)[0], QgsProject.instance().mapLayersByName(layer2)[0]])

**Comment by vegovs** [comment]
Thanks! :D
