### ISSUE TITLE
Identify Features ignores temporal controller filtering

### ISSUE THREAD

**Issue by Mi-Kbs-gis** [qgis/QGIS#39798]
**Description**
Temporal controller filtering will be ignord while using "Identify Features"

I'm using the temporal controller to jump over coss sections.
The station along a river is used as identifer of each cross section.
Sadly the access from the temporal controller with my data works just with a pseudo date (build by an expression).

[sampleproject.zip](https://github.com/qgis/QGIS/files/5486892/sampleproject.zip)
![filtersetting](https://user-images.githubusercontent.com/25895003/98094763-fda90f00-1e89-11eb-82f4-95f07e5260bb.PNG)
![objectinfo](https://user-images.githubusercontent.com/25895003/98094779-01d52c80-1e8a-11eb-8776-62e86eb0a9d9.PNG)

**How to Reproduce**

1. animated time navigation 
2. Set up a Date (for example 0051-01-01)
3. Now use Map Tool "Identify Features" and try to click on the feature
Not only one Feature is highlighted and listed in the docked panel.
In this case the filtering is ignored.

I used QGIS 3.16.0 and Windows 10

QGIS-Version | 3.16.0-Hannover | QGIS-Codeversion | 43b64b13f3
-- | -- | -- | --
Kompiliert gegen Qt | 5.11.2 | Laufendes Qt | 5.11.2
Kompiliert mit GDAL/OGR | 3.1.4 | Läuft mit GDAL/OGR | 3.1.4
Kompiliert mit GEOS | 3.8.1-CAPI-1.13.3 | Läuft mit GEOS | 3.8.1-CAPI-1.13.3
Kompiliert mit SQLite | 3.29.0 | Läuft mit SQLite | 3.29.0
PostgreSQL-Client-Version | 11.5 | SpatiaLite-Version | 4.3.0
QWT-Version | 6.1.3 | QScintilla2-Version | 2.10.8
Kompiliert mit PROJ | 6.3.2 | Läuft mit PROJ | Rel. 6.3.2, May 1st, 2020
BS-Version | Windows 10 (10.0)
Aktive Python-Erweiterungen | AppendFeaturesToLayer; bkggeocoder; covid19_tracker; DataPlotly; FreehandRasterGeoreferencer; GeoCoding; geomAttribute; geoprocAlgos; GroupStats; inspireatomclient; joinmultiplelines; map_md; menu_from_project; mmqgis; NNJoin; Offline-MapMatching; qfieldsync; QGeoloGIS; qgis-maptiler-plugin; Qgis2threejs; qgis_range_filters-master; qlyrx; QuickOSM; quick_map_services; radolan2map; raster_tracer; slyr_community; temporalprofiletool; TerrainShading; ThToolBox; timemanager; wfsclient; db_manager; MetaSearch; processing

**Comment by CoryAlbrecht** [comment]
I note that the attributes table also shows *all* features in the layer, not just the ones that the temporal controller lets show on the canvas. That is confusing. Could that and the Identify Features issue presented here have the same root problem?

**Comment by CoryAlbrecht** [comment]
Related to #39856 ?
