### ISSUE TITLE
Add option to store layer paths relative to a QGIS GPKG project container

### ISSUE THREAD

**Issue by cxcandid** [qgis/QGIS#39796]
While working a lot with QGIS projects stored inside Geopackage files, I would love to have an option to add layers with a relative path to the parent project Geopackage container. This would prevent errors in case of renaming the GPKG container file, and gives us the option to use a GPKG file as template for new projects.

As a temporary  workaround, I implemented a simple PathResolver-Plugin to replace the GPKG datasources during project opening:

    from qgis.core import QgsPathResolver,QgsProject
    import re

    def processor(path):
        # Replace GPKG datasource if project is stored in GPKG
        if re.search('[^/]+\.gpkg',path,flags=re.IGNORECASE):
          m = re.search('[^/]+\.gpkg',QgsProject.instance().fileName(),flags=re.IGNORECASE)
          if m and not re.search(m.group(0),path,flags=re.IGNORECASE):
              print('Repl. Old: %s' % path)
              path = re.sub('[^/]+\.gpkg',m.group(0),path,flags=re.IGNORECASE)
              print('With  New: %s' % path)
        return path

    class changeGpkgPath:
        def __init__(self, iface):
            pass

        def initGui(self):
            self.processor = QgsPathResolver.setPathPreprocessor(processor)

        def unload(self):
            QgsPathResolver.removePathPreprocessor(self.processor)

**Comment by gioman** [comment]
@cxcandid related to https://github.com/qgis/QGIS/issues/37440 ?

**Comment by cxcandid** [comment]
@gioman of course it's related ... didn't know that there is another request.

**Comment by gioman** [comment]
Ok, closing as duplicate then.
