### ISSUE TITLE
[Edit in Place] count points in the polygon does not work

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#39807]
The `Count Points in Polygon` algorithm works fine, but when used with `Edit in Place`  it doesn't work, i.e. it doesn't add in the field with the count.

How to reproduce it:
1. add two layers, one polygonal and one point;
2. from the processing tools, activate Edit in place and start it;
3. insert the polygon as the first layer and the points as the second;
4. launch the algorithm;
5. when opening the attribute table of the polygonal layer there is no field with the count.

## Even with a clean profile it doesn't work!

![image](https://user-images.githubusercontent.com/7631137/98138671-a2940e00-1ec3-11eb-9157-a95e4d439dae.png)

[RipGeo01012020_g.zip](https://github.com/qgis/QGIS/files/5489119/RipGeo01012020_g.zip)

**Comment by bellanz80** [comment]
I confirm, on QGIS 3.16 and 3.14.0,
Windows 10

**Comment by gioman** [comment]
@pigreco interesting, here on 3.16 there is no such tool when activating the "edit features in place" option

![Screenshot_20201104_164522](https://user-images.githubusercontent.com/1951107/98140384-49c17700-1ebd-11eb-82e1-eb04c3edb6cf.png)

**Comment by pigreco** [comment]
@gioman 

> @pigreco interesting, here on 3.16 there is no such tool when activating the "edit features in place" option

have you tried to select a polygonal layer?

**Comment by gioman** [comment]
> have you tried to select a polygonal layer?

sorry you are right, I was sure i had it.

**Comment by pigreco** [comment]
@gioman 
> sorry you are right, I was sure i had it.

if you confirm it is a bug, please remove feedback

**Comment by SrNetoChan** [comment]
Confirmed also on Ubuntu 18.04

**Comment by uclaros** [comment]
Is modifying the fields even supported by the current implementation of in place editing? Because if not, then the bug is that the algorithm is flagged as supporting in place edits while it shouldn't!

**Comment by agiudiceandrea** [comment]
See also https://lists.osgeo.org/pipermail/qgis-user/2020-December/047426.html

**Comment by DelazJ** [comment]
> Is modifying the fields even supported by the current implementation of in place editing? Because if not, then the bug is that the algorithm is flagged as supporting in place edits while it shouldn't!

According to what I read in the [docs](https://docs.qgis.org/3.16/en/docs/user_manual/working_with_vector/editing_geometry_attributes.html#the-processing-in-place-layer-modifier), it shouldn't be listed if it adds fields to the existing layer. Unless rules have changed and docs needs update.
