### ISSUE TITLE
versions 3.16 and 3.17 does not handle geotiff

### ISSUE THREAD

**Issue by mikhailtchernychev** [qgis/QGIS#39808]
I have geotiff files, including one saved from QGIS, which exhibit the following:

- add raster layer - works fine.
- double-click on the layer, QGIS crashes.

Running Ubuntu 18.04
Thank you
Mikhail

[martinez_saved.zip](https://github.com/qgis/QGIS/files/5489230/martinez_saved.zip)

**Comment by gioman** [comment]
duplicate of https://github.com/qgis/QGIS/issues/39628 and several other recent identical reports.
