### ISSUE TITLE
Dissolvence creation fails

### ISSUE THREAD

**Issue by MattUm** [qgis/QGIS#39800]
Goodmorning,
I have a problem with QGIS (I'm currently using version 2.14).
I have to do a dissolvence of a clip by categories, the process starts, but it stops when it reaches 100% and give me nothing. The file exists in the creation folder, but even if I load the shapefile on the program it shows me only a partial dissolvence of the territory.
I've done the same process with another clip and it works correctly.
Can someone help me with this problem?
I also tried to use new versions of QGIS and I tried to clip the vector in smaller piecies to dissolve one at time, but it brought me back the same problem.
I have attached some pictures hoping they will help to better understand the problem.
I need it for a school project and I'm pretty desperate.
Thanks in advance.
![Error_QGIS_1](https://user-images.githubusercontent.com/73936953/98097080-c720c380-1e8c-11eb-9a46-964d9c157690.png)
![Error_QGIS_2](https://user-images.githubusercontent.com/73936953/98097087-c9831d80-1e8c-11eb-8f24-e8603391c2f4.png)

**Comment by nyalldawson** [comment]
Don't use qgis 2.14 - that's severely out of date. Update to a newer supported release and retest please!

**Comment by MattUm** [comment]
Hi @nyalldawson 
I tried also using new versions (3.12 and 3.14), but, before having the above problem, in a previous process, QGIS informed me that the geometries of a vector were not valid and I don't know how to modify them.
Could you help me?

**Comment by gioman** [comment]
>  (3.12 and 3.14),

@MattUm they are both outdated and unsupported. You must use the latest LTR (3.10) or the 3.16 release.

Anyway, if you have geometry errors you must fix them beforehand, use the "fix geometries" tool.

**Comment by MattUm** [comment]
Hi @gioman 
Then I'll try to dowload one of these versions, but I've never fixed a geometry.
PS: are you italian? In that case, we should write about this in italian here or by private messages if something written in English is not understood

**Comment by gioman** [comment]
@MattUm 

![Screenshot_20201104_131223](https://user-images.githubusercontent.com/1951107/98115907-6e0e5b00-1e9f-11eb-9ca8-e8f624ac2b5c.png)

**Comment by MattUm** [comment]
@gioman 
I tried to use a new version of QGIS (3.16), but it reported me another problem: MPC didn't give me the result I expected (it looks like a buffer) and the clip of that MPC failed with the message "No spatial index in the input layer.
How could I fix this?
I attach some pictures of the problem
![Error_QGIS_1](https://user-images.githubusercontent.com/73936953/98155309-50a8b380-1ed6-11eb-8a89-f7aeace36f44.png)
![Error_QGIS_2](https://user-images.githubusercontent.com/73936953/98155313-51d9e080-1ed6-11eb-8fbb-5ccfd045cbd9.png)

**Comment by gioman** [comment]
>  How could I fix this?

@MattUm please attach your data. PS studying wolf mortality (or kills)? cool, I specialize(d) in small carnivores, a lot of telemetry...

**Comment by MattUm** [comment]
@gioman 
What data are you talking about? Are you talking about shapefiles and other files obtained by various processes?
Anyway, that's a random project given me at university, I study animal behaviour.

**Comment by gioman** [comment]
> What data are you talking about?

@MattUm the data you are using as input for the operations you are trying to do and you are reporting giving you problems.

**Comment by MattUm** [comment]
@gioman 
How could I attach my data? Files are too big and this chat gives me the message that it supports only smaller than 10MB.
Sorry for being late, but yesterday I was pretty busy.

**Comment by gioman** [comment]
>  How could I attach my data? Files are too big and this chat gives me the message that it supports only smaller than 10MB.

@MattUm create a zip. If is too big link it, using google drive. dropbox or similar services.

**Comment by MattUm** [comment]
@gioman 
Here's the link. Tell me if I shared it correctly, please
https://drive.google.com/drive/folders/1bNVf5ffqkjEvxAxesI6zMgP0m5s0NBxC?usp=sharing

**Comment by gioman** [comment]
>  Here's the link. Tell me if I shared it correctly, please

@MattUm link is not public

**Comment by MattUm** [comment]
@gioman How can I do that? I never used this kind of sites

**Comment by gioman** [comment]
> How can I do that? I never used this kind of sites

@MattUm it s a google drive option when you create the share (to make the link public).

**Comment by MattUm** [comment]
https://drive.google.com/drive/folders/1O0wsuQyFGCZqbctZCi3WSEekTiLKcf31?usp=sharing
Ok, this one should work, let me know as soon as you can

**Comment by gioman** [comment]
>  Ok, this one should work, let me know as soon as you can

@MattUm ok the data is downloadable, now what? there are two polygon layers, none of them seems to be the input in the screenshots in https://github.com/qgis/QGIS/issues/39800#issue-735983339

also to test what you show in the screenshot in https://github.com/qgis/QGIS/issues/39800#issuecomment-721907535 is needed the layer "MPC_cuneo".

**Comment by gioman** [comment]
@MattUm so please add all the necessary data and detail what operations are you trying to do describing expected results VS obtained results (or errors).

**Comment by MattUm** [comment]
> none of them seems to be the input in the screenshots in [#39800 (comment)]
Because that file is in the older version of the program (2.14), but everyone told me to download a new one.
There are **all** the files of the project made by the version 2.14 and there is the file named "MPC_Cuneo":
https://drive.google.com/drive/folders/1JsRqeNbVPlPolsmHBleFAB0ERCJYHu_O?usp=sharing

**Comment by gioman** [comment]
> Because that file is in the older version of the program (2.14), but everyone told me to download a new one.

 @MattUm data being used is not related with the software (or software version) you are using. Moreover in recent qgis releases you can open projects created with older releases.

**Comment by gioman** [comment]
>  There are **all** the files of the project made by the version 2.14 and there is the file named "MPC_Cuneo":

@MattUm as already answered in https://github.com/qgis/QGIS/issues/39800#issuecomment-721718014 your input layer "basso piemonte" has invalid geometries, that must be fixed with the "fix geometries" tool. After that you can clip with "mcp_cuneo" without issues and the following dissolve of the clipped layer also works without issues.

https://drive.google.com/file/d/1ac7ZAWtqIDxL3BRtOTiuQ9LHBZNcklGN/view?usp=sharing

**Comment by MattUm** [comment]
@gioman but I can't obtain the file because of the error of the last photo I attached in a previous comment.
I can leave in this link all the files of the project crated with the new version, that one that gives me an error for wrong geometries:
https://drive.google.com/drive/folders/1v1BkXpoG7giuBJJTCub8JmuEbY2TZ58i?usp=sharing

**Comment by MattUm** [comment]
@gioman Thank you so much! 
And now I only need to put that file in my project? Because I see is a .gpkg file and I always added shapefile to start new project. Does it works same even if  it's in a different format?
