### ISSUE TITLE
QGIS doesn't recognize KBS from MS SQL Server data Source

### ISSUE THREAD

**Issue by wisenmann** [qgis/QGIS#39818]
When loading Data from MS SQL Server Data Base in QGIS 3.12 but also 3.16, the KBS isn't recognized and QGIS asks for it.
Nevertheless in > Layer Properties - Information the KBS is correctly mentioned. But it is not comfortable to always specify it explicitly.

**Comment by nyalldawson** [comment]
What exactly is a "KBS"? Can you clarify this issue please? (Ideally with some sample sql scripts)
