### ISSUE TITLE
Object Properties Tab in Layout

### ISSUE THREAD

**Issue by Forna73** [qgis/QGIS#39813]
Hi!
I checked the online documentation, but can't understand if this is a bug or normal behavior...
I have several maps in a layout. I'm designing the final output for the print and I need to shift map windows here and there to adjust things. Everytime I make a shift or adjustment the map window starts rendering the impage. The problem is it takes minutes to render and I can't do nothing cause qgis is freezed till the end of the process. It is taking me countless time even for a minor adjustment. In the old "Print Composer" (QGis 2.x) I could select to not show the map window content, and I could make all the changes in seconds. I also could load the composer in no time to print it leaving the option to not show the contents...

As in the attached image, in Qgis 3.10 there's a check box "Don't draw map's objects". I thought it could be the solution for my problem, but nothing happens checking or unchecking the check box. Qgis still renders the map.

So my question is: is it a bug?

![obj_prp](https://user-images.githubusercontent.com/12034365/98225824-850f8480-1f55-11eb-96e1-11efd1066c0c.jpg)

**Comment by Forna73** [comment]
Ops.... wrong translation for the check box... it's "draw map's objects"

**Comment by gioman** [comment]
@Forna73 you had already opened https://github.com/qgis/QGIS/issues/34473 that was closed because the option (that was once available) was removed, by design I guess. Please raise the matter in the users and/or developers mailing list. If it turns to be a valid request (to re-introduce the functionality) please re-open this ticket as feature request.

**Comment by gioman** [comment]
> Ops.... wrong translation for the check box... it's "draw map's objects"

@Forna73 see the QGIS user manual for the meaning of this option.

https://docs.qgis.org/3.16/en/docs/user_manual/print_composer/composer_items/composer_map.html

**Comment by gioman** [comment]
@Forna73 to improve the situation you describe be sure to have parallel rendering enabled and use a preset with only a few layers enabled during the layout creation phase.

**Comment by gioman** [comment]
@Forna73 https://gis.stackexchange.com/a/305631
