### ISSUE TITLE
QGIS 3.16 (and 3.12) fails to send auth header to ArcGIS Enterprise (OAuth2 and GIS Tokens)

### ISSUE THREAD

**Issue by PeterReyne** [qgis/QGIS#39822]
**Bug description**

QGIS fails to include an http authorisation header when adding a secured Map or Feature service/layer from ArcGIS Enterprise to a project, after successfully connecting to the ArcGIS Enterprise site via OAuth2 authentication configuration (also seems to affect ArcGIS GIS tokens).

- QGIS will successfully connect to the ArcGIS Portal via a correctly configured OAuth2 or GIS Token authorisation provider
- QGIS will successfully scrape the ArcGIS Server services available at the URI configured in the ArcGIS Feature or Map service data source (the authorisation header is sent)
- After getting the list of available services, QGIS will FAIL to add a selected ArcGIS Feature or Map service to the QGIS Project (the authorisation header is NOT sent and ArcGIS Server rejects the request with a 499 token required message)

This guide was helpful in configuring OAuth2 against ArcGIS Enterprise (Portal)
https://north-road.com/2020/06/04/securely-accessing-enterprise-arcgis-portal-sites-through-qgis/

*The error from QGIS 3.16:*
```
2020-11-06T09:54:02     CRITICAL    Layer is not valid : The layer bbox='-389618,-111325,389618,111325' crs='EPSG:3857' filter='' url='https://censored/arcgis/rest/services/censored/censored/FeatureServer/3' is not a valid layer and can not be added to the map. Reason: AFSProvider getLayerInfo failed
```

*The error from ArcGIS Server*
```
{"error":{"code":499,"message":"Token Required","details":[]}}
```

**How to Reproduce**

Because this relates to secured resources I can't supply detailed test cases in a public forum but am happy to supply an engineer with test services/accounts/access/support on my end to enable them to reproduce the issue. I also have a fiddler trace showing the traffic from QGIS to ArcGIS Enterprise.

*Pre-requisites*
- A secured ArcGIS Enterprise/Portal service
- An OAuth2 access/secret key for the ArcGIS Enterprise site

*Steps*
1. Settings -> Options -> Authorization: Add an OAuth2 provider for an ArcGIS Enterprise (Portal) site
2. Layers -> Data Source Manager -> ArcGIS Feature Service: Configure an ArcGIS Feature (or Map) Service provider to the ArcGIS Enterprise site and set the OAuth2 configuration from step 1 for authentication
3. 'Connect' to the ArcGIS Feature Service from Data Source Manager, log in to the ArcGIS Enterprise site when prompted
4. Observe QGIS successfully lists the feature services accessible to the account (Fiddler trace shows requests with auth header)
5. Select a service/layer and 'Add' to the QGIS Project
6. Observe QGIS error, fails to add the service/layer (Fiddler trace shows request without auth header)

**QGIS and OS versions**
Tested QGIS 3.12 and 3.16, details for 3.16 below

```
QGIS version
3.16.0-Hannover
QGIS code revision
43b64b13f3
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
db_manager; 
MetaSearch; 
processing
```

**Additional context**

We operate a large ArcGIS Enterprise installation with many open and not-so open map, feature and image services.
While we are primarily an Esri shop for server-side infrastructure, we seek to support customers who use open source and other non-Esri GIS software.

I found this issue as a result of testing how we can better support QGIS users accessing our ArcGIS Enterprise installation.

**Comment by nyalldawson** [comment]
Does it work correctly if you add them via the browser panel instead?

**Comment by nyalldawson** [comment]
Actually - confirmed.

**Comment by PeterReyne** [comment]
@nyalldawson I get a different error when adding the FS from the browser tree, but could be an issue with the ArcGIS server, not QGIS. Even though you confirmed the bug I'll check this out as a workaround. Thanks!

**Comment by PeterReyne** [comment]
@nyalldawson I can confirm adding the ArcGIS Feature Service layer from the browser tree correctly includes the auth header so the workaround is good - thankyou.

I encountered a separate issue where QGIS issues the request below, before loading the layer which I may raise as a separate issue. Leaving here for completeness more than anything. This request can be slow to respond and QGIS may time out, resulting in the layer not being added to the project.

The issue is probably whether QGIS should prevent the ArcGIS Feature service layer being added to the project if it takes longer than the QGIS timeout to respond, or just ignore it and add anyway, or include some pagination.
https://censored/arcgis/rest/services/censored/censored/FeatureServer/3/query?f=json&where=1%3D1&returnIdsOnly=true

An approach could be to include a set limit of 1000 results to ensure the records are returned promptly
https://censored/arcgis/rest/services/censored/censored/FeatureServer/3/query?f=json&where=1%3D1&returnIdsOnly=true&resultOffset=0&resultRecordCount=1000
