### ISSUE TITLE
Allow search in expression string builder to show results from allowable arguments, not only function name

### ISSUE THREAD

**Issue by ThoStaKa** [qgis/QGIS#39828]
**Feature description.**
In expression string builder, when I enter a search term, I would appreciate if any allowable arguments could be included in the results. For example when I search for "extent", the expression "layer_property" which has an argument named "extent" should be shown as a result.

A suggestion / mock-up of how a search result might look is attached as picture

![image](https://user-images.githubusercontent.com/34090557/98340482-b8154f00-200d-11eb-88ad-34b2025d7036.png)

**Comment by gacarrillor** [comment]
`Extent` is actually one of the allowed values for the argument `property`, i.e., it's a domain value, so supporting argument names as search keys won't necessarily fix this.

On the other hand, function tags are the preferred way to improve function discoverability, so I guess it'd be enough to just add more tags to the `layer_property` function (including the tag `extent`).
