### ISSUE TITLE
QGIS 3.16 crashes when clicking "intersect" in topbar vector menu

### ISSUE THREAD

**Issue by soraimperial** [qgis/QGIS#39823]
/newb user alert

Just installed 3.16 yesterday (came from 3.14) and everytime I try to click Intersect (from the top bar), it crashes.
First time it happened it allowed me to open the Intersect menu, then crashed on running, the next 12-14 times just crashed on clicking Intersect. It also doesn't open the "QGIS crashed unexpectedly" sad face menu, I have to manually terminate the process (left it crashed for 4h at one point).

This happened with different datasets, after restarting PC and fresh 3.16 install.

Tried the same project with the same datasets in 3.14 and went at first try.
It's very akin to the problem that several people reported (I also had it) on crashes in 3.14 when click anywhere in a docked Processing Toolbox.

Running QGIS 3.16.0 in Win10.

**Comment by SrNetoChan** [comment]
@soraimperial can you please try to create a new profile and see if it works?

![image](https://user-images.githubusercontent.com/3607161/98317546-98ae0000-1fd4-11eb-993b-d8e9fdacd9aa.png)

**Comment by soraimperial** [comment]
@SrNetoChan Yop, worked (even tho took me ages to find intersect 'cause the new profile came as is half portuguese-half english for some reason and everything is in a different order).

So something in my profile is messing with the tools? Can I rebuild my profile on the new one or does this mean that the bug is appended to something in my personal settings?

**Comment by SrNetoChan** [comment]
Start by disabling all the plugins on the old profile. If that helps, activate one by one to find the culprit.

If it doesn't help, something went wrong on your configuration. Might be worthy to understand what.

**Comment by soraimperial** [comment]
Only non-standard plugins (besides grass and stuff) I have are Visualist and Crayfish.Then I changed language to english and dark mode GUI, no other stuff. So will be easy to check what the culprit is.

Thank you!

**Comment by SrNetoChan** [comment]
@gioman Wouldn't it make sense to try to hunt down this? If the same profile was working for 3.14, maybe there will be more users facing issues due to legacy configuration.
