### ISSUE TITLE
QGIS 3.10 LTR closes/crashes when opening new project using Windows OS

### ISSUE THREAD

**Issue by jelreyes** [qgis/QGIS#39832]
I am currently using Windows 10 and I've been trying to install and reinstall the long-term release of QGIS 3.10 Acoruna but it still crashes when opening a new project or any existing project. No error message appears, it only closes suddenly. I've been trying to look for answers in previous bug reports but nothing solves my problem. Please help. I also tried installing the latest version (not the LTR) but it also crashes.

**Comment by gioman** [comment]
@jelreyes try with a new QGIS profile, no 3rd party plugins installed.

Settings > user profiles > new profile

**Comment by jelreyes** [comment]
> Settings > user pr

Hi, thank you for your reply. I found out that i can open other files except .nc files. Whenever i open a netcdf file or a project containing netcdf file, it crashes. I tried looking for answers but the issues are usually in ubuntu and I am a windows os user. I also tried installing the latest version in qgis master but it also has the same issue.

**Comment by gioman** [comment]
> Hi, thank you for your reply. I found out that i can open other files except .nc files. Whenever i open a netcdf file or a project containing netcdf file, it crashes. I tried looking for answers but the issues are usually in ubuntu and I am a windows os user. I also tried installing the latest version in qgis master but it also has the same issue.

@jelreyes is this one? https://github.com/qgis/QGIS/issues/39729
