### ISSUE TITLE
Topological editing does not work

### ISSUE THREAD

**Issue by Bernd-Vogelgesang** [qgis/QGIS#39835]
**Describe the bug**
When I split a feature with "Split features" and then try to adjust a shared vertex, even with "Topological editing" enabled, the vertex tool only changes one polygon and produces overlapping polygons.

**How to Reproduce**

1. Create a new polygon layer (here geopackage)
2. Digitize a polygon
3. use "Split features" tool to split the polygon
4. Enable topological editing in the "snapping options"
5. Move a shared vertex with the vertex tool

**QGIS and OS versions**

QGIS-Version | 3.16.0-Hannover | QGIS-Codeversion | 43b64b13f3
-- | -- | -- | --
Kompiliert gegen Qt | 5.12.8 | Laufendes Qt | 5.12.8
Kompiliert mit GDAL/OGR | 3.0.4 | Läuft mit GDAL/OGR | 3.0.4
Kompiliert mit GEOS | 3.8.0-CAPI-1.13.1 | Läuft mit GEOS | 3.8.0-CAPI-1.13.1
Kompiliert mit SQLite | 3.31.1 | Läuft mit SQLite | 3.31.1
PostgreSQL-Client-Version | 12.4 (Ubuntu 12.4-0ubuntu0.20.04.1) | SpatiaLite-Version | 4.3.0a
QWT-Version | 6.1.4 | QScintilla2-Version | 2.11.2
Kompiliert mit PROJ | 6.3.1 | Läuft mit PROJ | Rel. 6.3.1, February 10th, 2020
BS-Version | Linux Mint 20
Aktive Python-Erweiterungen | MetaSearch; db_manager; processing

**Additional context**

![Bildschirmfoto vom 2020-11-06 12-05-32](https://user-images.githubusercontent.com/5012038/98359754-fd934580-2028-11eb-9dd2-3d4cf8689d36.png)
Haven't been digitizing  for a while, so maybe I just oversee a simple trick. But if that was the case, the process would be very unintuitive.
Fresh install, new profile.

**Comment by gioman** [comment]
@Bernd-Vogelgesang maybe you are hitting this? https://github.com/qgis/QGIS/issues/29648

**Comment by Bernd-Vogelgesang** [comment]
I confirm, this is the same as  #29648
Didn't find this in the issues list cause I did not browse that far in the past. (April 2019!)
How should I explain this to a beginner when even I step into this trap?

**Comment by gioman** [comment]
>  How should I explain this to a beginner when even I step into this trap?

@Bernd-Vogelgesang I feel your pain, I also don't clearly understand how this regression has been overlooked in the last year and half rounds of bug fixing. Closing as duplicate.
