### ISSUE TITLE
Add advanced text formatting options to Text Box in Print Composer

### ISSUE THREAD

**Issue by robintw** [qgis/QGIS#39848]
**Feature description.**
When formatting labels in QGIS you have access to all sorts of advanced text formatting options such as buffers, backgrounds, shadows, and so on. These don't appear to be available for formatting text added as a text box in the Print Composer. It would be awesome if these text boxes could have the same formatting options.

**Additional context**
For reference, here are the list of text formatting features available for labels:

<img width="853" alt="Screen Shot 2020-11-06 at 16 12 14" src="https://user-images.githubusercontent.com/296686/98388835-24627380-204b-11eb-854e-df01e07dd86e.png">

**Comment by timclc** [comment]
I would like to see this feature advanced as well. It gives greater freedom for customizing content in the Print Composer and i have had to find complicated workarounds to achieve good results.

**Comment by ioalexei** [comment]
Adding a +1 for this request. Specifically I'd like to be able to use buffers/halos on text added as a layout item

**Comment by TurboGraphxBeige** [comment]
@ioalexei Good news, it's already there! I don't remember which version this feature was added, but it's been there for a few months at least already.

**Comment by ioalexei** [comment]
@TurboGraphxBeige  Thanks for the heads up! Just found the relevant setting, great to know it's now possible

**Comment by robintw** [comment]
@ioalexei Can you point me to where the settings are? I had a brief look and couldn't find them for a text box in the Print Layout.

**Comment by ioalexei** [comment]
In 3.30.0, when you select a text item in the layout, you can click the Font button under Appearance to get the advanced settings: 
![image](https://github.com/qgis/QGIS/assets/3179403/e48670bf-ef59-421e-b98c-08453e454bd4)

I think the relevant part of the user guide needs to be updated, so I'll open an issue for that.

**Comment by ingridkm** [comment]
Hi All,

The advanced text formatting options for the text box in Print Composer have disappeared in my QGIS (3.22.1). Does anyone know how to activate the advanced text formatting options. It now appears like in the picture below. 

![image](https://github.com/qgis/QGIS/assets/36295369/72ebd249-88f8-4676-a1ca-2445e9b1bee2)

**Comment by nyalldawson** [comment]
@ingridkm upgrade to a newer qgis version -- this wasn't supported in 3.22

**Comment by ingridkm** [comment]
It has worked. Thanks @nyalldawson.
