### ISSUE TITLE
Adding WFS layers broken in master

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS#39847]
In 3.16 I could add one of the layers (pick 'provincies' = smallest) from the following service via the WFS dialog, using the following service url:
```
https://geodata.nationaalgeoregister.nl/bestuurlijkegrenzen/wfs
```

In master this fails.

Trying the same via iface.addRasterLayer idem dito:
The following works in 3.16 and fails in master using the Python console:
```
iface.addVectorLayer(
"https://geodata.nationaalgeoregister.nl/bestuurlijkegrenzen/wfs?SERVICE=WFS&VERSION=1.0.0&REQUEST=GetFeature&TYPENAME=bestuurlijkegrenzen:provincies&SRSNAME=EPSG:28992",
"wfs example",
"WFS")
```

**Comment by elpaso** [comment]
https://geodata.nationaalgeoregister.nl/bestuurlijkegrenzen/wfs?SERVICE=WFS&REQUEST=GetFeature&VERSION=1.0.0&TYPENAME=bestuurlijkegrenzen:provincies&SRSNAME=EPSG:28992&OUTPUTFORMAT=GML3

error | "Service Unavailable"
-- | --
timestamp | 1604677451077
status | 503

**Comment by rduivenvoorde** [comment]
That was a hickup in our national WFS service I think at THIS moment that url returns our 12 provinces.

But *that* is indeed the case that QGIS is creating 'wrong'(?) url's
In the network monitor after registring the service I see url's like: ?SERVICE=WFS&REQUEST=GetCapabilities&ACCEPTVERSIONS=2.0.0,1.1.0,1.0.0 without host part...

As said: service is now available:

https://geodata.nationaalgeoregister.nl/bestuurlijkegrenzen/wfs?SERVICE=WFS&REQUEST=GetCapabilities

And using that url (truncated by QGIS till https://geodata.nationaalgeoregister.nl/bestuurlijkegrenzen/wfs in the wfs dialog results in 3 layers, it is just that loading a WFS layer does not work.
I hit this because of:  #39846 in which the Oracle provider did not implement encodeUri and decodeUri, and I found that the WFS provider also didn't. So I even added those (based on code from the WMS provider, see below), but that did not help either:
```
QVariantMap QgsWfsProviderMetadata::decodeUri( const QString &uri ) const
{
  const QUrlQuery query { uri };
  const auto constItems { query.queryItems() };
  QVariantMap decoded;
  for ( const auto &item : constItems )
  {
    decoded[ item.first ] = item.second;
  }
  return decoded;
}

QString QgsWfsProviderMetadata::encodeUri( const QVariantMap &parts ) const
{
  QUrlQuery query;
  QList<QPair<QString, QString> > items;
  for ( auto it = parts.constBegin(); it != parts.constEnd(); ++it )
  {
    items.push_back( {it.key(), it.value().toString() } );
  }
  query.setQueryItems( items );
  return query.toString();
}
```
