### ISSUE TITLE
Create random raster layer (uniform distribution) does not create pixels with decimal values

### ISSUE THREAD

**Issue by PedroVenancio** [qgis/QGIS#39845]
@root676 

I'm not sure if this is a bug report or a feature request, but I can't create a random raster layer, for instance, with values from 0.0 to 1.0, even choosing Float32 or Float64 data types. 

Also, following the default behaviour (By default, the values will range between the minimum and maximum value of the specified output raster type), if I choose Byte and keep min and max bounds as zero, the output is a raster will all pixels with zero.

So, it seems some kind of a bug.

**Comment by root676** [comment]
Thanks for reporting - I'll have a look.
