### ISSUE TITLE
Percentile and Percentrank functions in Cell Statistics

### ISSUE THREAD

**Issue by PedroVenancio** [qgis/QGIS#39844]
The idea was to get something like the LibreOffice Calc / MS Excel functions:

  - **PERCENTILE**: https://help.libreoffice.org/latest/en-US/text/scalc/01/04060184.html?DbPAR=CALC#bm_id3153100

![imagem](https://user-images.githubusercontent.com/1331581/98375899-abf3b680-203a-11eb-9c21-55a759989d7a.png)

The output is, for each cell, the value of the given percentile. The reference layer would be exactly as in actual Cell Statistics, giving the extent and resolution of the output.

  - **PERCENTRANK**: https://help.libreoffice.org/latest/en-US/text/scalc/01/04060184.html?DbPAR=CALC#bm_id3148807

![imagem](https://user-images.githubusercontent.com/1331581/98375987-c9c11b80-203a-11eb-951c-26060c3b9d25.png)

The output is the percentage rank of each pixel value of reference layer, given the correspondent pixel values in the raster stack. The reference layer here is the base for the calculations, giving the VALUE parameter of PERCENTRANK algorithm, besides the extent and resolution of the output.

This idea was already discussed with @root676 in https://github.com/qgis/QGIS/pull/36835

**Comment by root676** [comment]
Thanks for opening the ticket - this should be easy to implement. :wink:

**Comment by root676** [comment]
This feature request can be closed - it has been implemented. :wink:
