### ISSUE TITLE
When in Temporal Controller mode, the Identify Features tool selects too many items

### ISSUE THREAD

**Issue by CoryAlbrecht** [qgis/QGIS#39856]
**Describe the bug**
When you have a layer with temporal data in it and you have turned on the temporal controller so you only see the features relevant to your timeframe, the Identify Features tool still selects all features at that point, including the ones not shown by by the temporal controller that are outside the specified timeframe.

**How to Reproduce**
1. Open a layer with temporal data, and set the temporal settings
2. Use the temporal control to display your desired timeframe
3. Select the Identify Features tool and click on a point that you know is inside different features in different timeframes

Before clicking with the Identify Features tool. Notice the single set of features (countries with their borders in black)
![image](https://user-images.githubusercontent.com/8172909/98400003-51099180-2031-11eb-85ce-f433a54b526d.png)

After clicking, note the multiple features in the Identify results panel to the right. Only one of them was visible in the first screencap.
![image](https://user-images.githubusercontent.com/8172909/98400077-6ed6f680-2031-11eb-8db1-1aede0b35530.png)

**Expected Results**
Only the single feature shown by the temporal controller should be selected.

**Versions and such**
QGIS version | 3.16.0-Hannover | QGIS code revision | fd9b11d8df
-- | -- | -- | --
Compiled against Qt | 5.12.8 | Running against Qt | 5.12.8
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.4 (Ubuntu 12.4-0ubuntu0.20.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Ubuntu 20.04.1 LTS | This copy of QGIS writes debugging output.
Active python plugins | processing; db_manager; MetaSearch

**Comment by uclaros** [comment]
Same as #39798 ?

**Comment by imanhn** [comment]
@CoryAlbrecht do you have any simple dataset and a project file(.qgz). I would take care of it.

**Comment by CoryAlbrecht** [comment]
I note that the attributes table also shows *all* features in the layer, not just the ones that the temporal controller lets show on the canvas. That is confusing. Could that and the Identify Features issue presented here have the same root problem?

**Comment by CoryAlbrecht** [comment]
related to #39798 ?

**Comment by nirvn** [comment]
Fixed on master.
