### ISSUE TITLE
erro python

### ISSUE THREAD

**Issue by lemosnatasha** [qgis/QGIS#39860]
**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

O Qgis versão 3.10.11 esta apresentando a seguinte mensagem de erro ao tentar realizar o pré-processamento de imagens L8 para cálculo dos índices espectrais. Necessito de ajuda, pois já desinstalei e reinstalei o Qgis e o erro persiste.

Um erro ocorreu enquanto executava o código Python: 
ValueError: could not convert string to float: 
Traceback (most recent call last):
  File "C:/Users/lemos/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SemiAutomaticClassificationPlugin\maininterface\landsatTab.py", line 640, in performLandsatCorrection
    self.landsat(cfg.ui.label_26.text(), o)
  File "C:/Users/lemos/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SemiAutomaticClassificationPlugin\maininterface\landsatTab.py", line 283, in landsat
    e = self.landsat8reflectance(sat, str(nm[len(nm) - 1]), REFLECTANCE_MULT, REFLECTANCE_ADD, RADIANCE_MULT, RADIANCE_ADD, RADIANCE_MAXIMUM, REFLECTANCE_MAXIMUM)
  File "C:/Users/lemos/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SemiAutomaticClassificationPlugin\maininterface\landsatTab.py", line 496, in landsat8reflectance
    radM = float(RADIANCE_MAXIMUM_BAND)
ValueError: could not convert string to float: 

Versão do Python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Versão do QGIS: 3.10.11-A Coruña A Coruña, d2171173e4 
Caminho do Python:
•	C:/PROGRA~1/QGIS 3.10/apps/qgis-ltr/./python
•	C:/Users/lemos/AppData/Roaming/QGIS/QGIS3\profiles\default/python
•	C:/Users/lemos/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
•	C:/PROGRA~1/QGIS 3.10/apps/qgis-ltr/./python/plugins
•	C:\PROGRA~1\QGIS 3.10\apps\Python37
•	C:\PROGRA~1\QGIS 3.10\apps\Python37\Scripts
•	C:\Program Files\QGIS 3.10\bin\python37.zip
•	C:\PROGRA~1\QGIS 3.10\apps\Python37\DLLs
•	C:\PROGRA~1\QGIS 3.10\apps\Python37\lib
•	C:\Program Files\QGIS 3.10\bin
•	C:\PROGRA~1\QGIS 3.10\apps\Python37\lib\site-packages
•	C:\PROGRA~1\QGIS 3.10\apps\Python37\lib\site-packages\win32
•	C:\PROGRA~1\QGIS 3.10\apps\Python37\lib\site-packages\win32\lib
•	C:\PROGRA~1\QGIS 3.10\apps\Python37\lib\site-packages\Pythonwin
•	C:/Users/lemos/AppData/Roaming/QGIS/QGIS3\profiles\default/python

No aguardo, agradeço.

Cordialmente, 

Natasha.

**Comment by Gustry** [comment]
> C:/Users/lemos/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SemiAutomaticClassificationPlugin\maininterface\landsatTab.py"

The QGIS project can't do anything about a third party plugin. You must report the issue in the plugin code repository.
