### ISSUE TITLE
IAU CRSs are missing

### ISSUE THREAD

**Issue by BerginJay** [qgis/QGIS#39866]
**Describe the bug**

In Version 3.14-pi, there are several IAU CRSs, like *IAU2000:30100 Moon_2000* and *IAU2000:30120 Moon_south_pole_stereographic*, etc. But after updating to version 3.16 I can't find those IAU CRSs in the predefined CRS list.
 
**How to Reproduce**

1. Update to version 3.16 and open qgis
2. Open project properties --> CRS --> use filter to search any IAU CRS

**QGIS and OS versions**

- OS: MacOS 10.15.7

- QGIS: 3.16.0-Hannover

**Additional context**

I don't think it is a good idea If QGIS does remove those IAU CRSs. For those who study other planets and moons, QGIS is a very good tool. And these IAU CRSs are convenient.

**Comment by nyalldawson** [comment]
Qgis completely relies on the proj library for its crs database now. This issues needs to be filed with the proj project (that said, they are already aware of it and trying to get it resolved. If you have knowledge in this field they would very much appreciate extra assistance!)
