### ISSUE TITLE
Option to Display/Enter in Lat/Lon Format in the Status Bar Coordinate Field

### ISSUE THREAD

**Issue by ozhamlet** [qgis/QGIS#39876]
**Feature description.**
Provide an option in the 'General | Coordinate and Bearing Display' section of  'Project Properties' to allow a choice in the coordinates order between Lat/Lon or Lon/Lat.

**Additional context**
This would allow the user to more easily copy and paste between other systems that use the more common Lat/Lon order.

**Comment by drf5n** [comment]
The `Lat Lon Tools` plugin has some of this functionality under its `Copy/Display Coordinate` feature.

**Comment by ozhamlet** [comment]
> 
> 
> The `Lat Lon Tools` plugin has some of this functionality under its `Copy/Display Coordinate` feature.

Thanks for that.  I can see that works for 'exporting' a Lat/Lon pair from QGIS.   What I'm also needing is to go to a Lat/Lon in QGIS that I've copied into the clipboard from another app without having to copy each value separately or to copy both together and then reverse the order.

**Comment by drf5n** [comment]
Does the `Lat Lon Tools` feature `Zoom to Coordinate` work for you?

**Comment by ozhamlet** [comment]
Yes, that's it.  I didn't realise that's what it did.  Thanks for pointing it out.
