### ISSUE TITLE
Add "Delete Selected" feature to Identifyplugin

### ISSUE THREAD

**Issue by imanhn** [qgis/QGIS#39875]
Deleting a feature is to some extent hard, However in most of GIS systems there is a delete where ever the user can view the attributes. Our customers asked us to put delete there and I couldn't agree more that it is a SHOULD. So I added a new button to the top toolbar of the Identify plugin for this purpose.

It does not ask for confirmation because the user can still commit/rollback or even undo.

It does not delete a group of features and just delete one single feature each time which I believe is enough. if someone has a different opinion, Please, I'll be happy to hear and make the necessary changes.

This feature has already implemented and has been pull requested with another issue  (#39842) Sorry, I couldn't separate them!

Looks like I can't right?

P.S : Should I open a feature request as an "Issue" prior to a pull request? or it is not necessary?

![delete selected](https://user-images.githubusercontent.com/9729773/98452019-aa241300-2160-11eb-8229-c755dd6e0ca1.png)

**Comment by uclaros** [comment]
I don't think this is a good idea. The identify tool is supposed to be read only and IMHO it should remain that way. You described workflow could be simulated with an attribute tabe in form view set to display only selected features instead.

**Comment by nyalldawson** [comment]
My personal view is the same as @uclaros  -- there's already a range of ways to delete specific features and I don't think it's a good idea to bring this functionality into QGIS. 

But please note that this could be addressed by a plugin or custom map layer action -- it doesn't have to be in the out of the box QGIS install! So if your customers need this functionality then you're able to address this for them in alternative ways specific to their needs.

Closing this as a wontfix as a result.

**Comment by imanhn** [comment]
Thanks Richard(@nyalldawson) and @uclaros for your comment on this.

I have to admit, in environmental GIS we don't have such huge usage of delete feature. Yet in utility GIS, there is a great deal of change in their network (layers) and for that sake, an easy access to a delete feature -- as well as some other functionalities of course which I had hope that I could implement here -- is needed. With this in mind, the whole logic of making a layer editable and then be able to edit it could be a subject to debate, As in utility GIS, all layers should be editable. this feature that I have already added (PR) follows this design. 

Putting a delete icon in identify plugin helps users to delete a feature, based on its location (click coordinate) and the attributes at the same time. And I know, this functionality is already there, nonetheless, It should be much more easier because of the frequency of its usage.

if QGIS is also supposed to cover utility sector's need, there are a number of features that must be considered to be added to the platform. I would personally love to embed the editor form (feature edit form) into the identify plugin, to avoid unnecessary clicks. Please put yourself in operators shoes here and loose your principle a little bit.

Please take a look at the following snapshot that I have taken from other platforms which may convey the importance of having some manipulation functionality over the identify plugin.

![sw1](https://user-images.githubusercontent.com/9729773/98496117-17fe3680-2256-11eb-86f1-3be798d97904.PNG)
![supermap](https://user-images.githubusercontent.com/9729773/98496151-28161600-2256-11eb-860f-9ec671888984.png)

Thanks for your time
