### ISSUE TITLE
QGIS app would not open for MacBook Pro

### ISSUE THREAD

**Issue by angelika-concirrus** [qgis/QGIS#39881]
<img width="424" alt="Screenshot 2020-11-08 at 09 59 51" src="https://user-images.githubusercontent.com/50147274/98462240-b6cd5900-21aa-11eb-9fd0-6b5aa837eb67.png">

After installing QGIC Version 3.16 for MacOS, the app would not run. Error message:

"QGIS" can’t be opened because Apple cannot check it for malicious software. This software needs to be updated. Contact the developer for more information.

**Comment by roya0045** [comment]
https://github.com/qgis/QGIS/issues/34018#issuecomment-578186707

**Comment by agiudiceandrea** [comment]
https://qgis.org/en/site/forusers/download.html#mac
> Download for macOS
> Official All-in-one, signed installers
> Mac Installer Packages for macOS High Sierra (10.13) and newer.
> 
> QGIS is not yet notarized as required by macOS Catalina (10.15) security rules. On first launch on, use right click on the QGIS app icon and choose Open.
