### ISSUE TITLE
Missing Language Information on QGIS Settings and on Help->About Menu

### ISSUE THREAD

**Issue by ValPinnaSardinia** [qgis/QGIS#39883]
**Describe the bug**

In the last weeks, the Sardinian Translation was added in all the current versions (3.10.11, 3.16.0-11 and 3.17.0). 

Unfortunately, in all of the version, the language information (flag and language name) are missing and in the  Settings->Options->Override System Locale->User Interface Translation drop-down menu the language is shown as empty space.

Also, in the Help->About->Translators the language flag is missing.

**How to Reproduce**

1. Open Settings -> Options 
2. Select Override System Locale 
3. Open User Interface Translation drop-down menu
4. Scroll to the bottom. Here is visible an empty line which matches with the newly Sardinian Language (sc)

**QGIS and OS versions**

QGIS versions 3.10.11, 3.16.0-11 and 3.17.0

**Additional context**

As coordinator and translator of the language, I am more than happy to provide help and resources, if required. 

Valerio P

**Comment by skampus** [comment]
+1

**Comment by Korto19** [comment]
+1
