### ISSUE TITLE
QGIS is Slow when Vertex Editor is Active

### ISSUE THREAD

**Issue by jake9wi** [qgis/QGIS#39890]
**Describe the bug**

1.  When vertex editor tool is active all actions in qgis become sluggish.
2.  Deleting vertexes is slow.
    - A few vertexes take a few seconds; more takes longer.
    - Longest I've waited is a half hour; average is a few minutes.

**How to Reproduce**

1. Load a line type dataset (I am using elevation contours stored in a gpkg).
2. Enter vertex editor mode.
3. Highlight some nodes by dragging the mouse.
4. Delete the nodes with the DEL key.

**QGIS and OS versions**

QGIS version | 3.10.11-A Coruña | QGIS code revision | d2171173e4
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | latlontools; QuickOSM; searchlayers; db_manager; processing

**Comment by uclaros** [comment]
>     * A few vertexes take a few seconds

How many are a few?
Is it sluggish without selecting any vertices?

**Comment by gioman** [comment]
@jake9wi also try with a new QGIS profile.

**Comment by roya0045** [comment]
@gioman 3.10.11 is the current LTR?

**Comment by gioman** [comment]
> @gioman 3.10.11 is the current LTR?

it is

**Comment by jake9wi** [comment]
It is sluggish with out selecting any vertices. Selecting four or six vertices takes a five or ten seconds.

**Do note** that this was with data set and project in different CRS's. After I posted this issue I noticed the CRS's where different and tried re-projecting data set to be same as project and this improved the deleting speed; it also improved speed  when no vertices where selected.

**Comment by gioman** [comment]
> It is sluggish with out selecting any vertices. Selecting four or six vertices takes a five or ten seconds.

@jake9wi have you tried a new QGIS profile?

**Comment by jake9wi** [comment]
> 
> 
> > It is sluggish with out selecting any vertices. Selecting four or six vertices takes a five or ten seconds.
> 
> @jake9wi have you tried a new QGIS profile?

No I have not yet.

**Comment by gioman** [comment]
Closing for lack of further feedback.

**Comment by firebblade** [comment]
is this still on ?
