### ISSUE TITLE
Keyboard shortcut for "Save As..." (project) and "Save As..." (export layer) keeps overwriting themselves

### ISSUE THREAD

**Issue by mocmichal** [qgis/QGIS#39903]
I would like to set keyboard shortcut for **"Save As..."** in Project menu and in Layer menu differently !
Currently they keep overwriting themselvs (after restart).
![bug_qgis_saveas_keyboardshortcut_overwriting](https://user-images.githubusercontent.com/5244956/98531750-16963380-2281-11eb-8ca0-2e607ec97db9.JPG)

**Comment by roya0045** [comment]
What if you use any other shortcut? Do they also reset or only the standard shortcuts?

**Comment by mocmichal** [comment]
Any shortcut I assign to those two "save as..." menus become one after opening qgis again.
I guess it cannot distinguish between the two, when loading.

**Comment by mocmichal** [comment]
unfortunately for me it is still the same (on 3.22.1) 
works fine, once I set the shortcuts up. Then, after closing and opening the program again none of the shortcuts works.

**Comment by mocmichal** [comment]
https://user-images.githubusercontent.com/5244956/144726283-4458910b-1796-45d6-9f0a-10e2ba4db2b1.mp4

**Comment by Pedro-Murteira** [comment]
@mocmichal I followed your steps and this time I was able to replicate it aswell, with that confirming it is still an actual bug
