### ISSUE TITLE
Header row of spreadsheet data ignored on import (.xlsx/.ods/...)

### ISSUE THREAD

**Issue by Bernd-Vogelgesang** [qgis/QGIS#39908]
**Describe the bug**
While importing any kind of spreadsheets like .xlsx, .ods etc, no matter which way (as vector data through Data Source Manager or drag-and-drop), the table headers get ignored, so there are only Field1, Field2, Field3 ... and the order of the rows seems to be completely random.

**How to Reproduce**

Open the attached table either by drag-and-drop or through the Data Manager

**QGIS and OS versions**

QGIS version | 3.16.0-Hannover | QGIS code revision | 43b64b13f3
-- | -- | -- | --
Compiled against Qt | 5.12.8 | Running against Qt | 5.12.8
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.4 (Ubuntu 12.4-0ubuntu0.20.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Linux Mint 20
Active python plugins | processing_saga_nextgen; quick_map_services; processing; MetaSearch; db_manager

**Additional context**
Tables were produced with LibreOffice 6.4.6.2 on Linux Mint 20, QGIS 3.16
[baykompv_werte2.xlsx](https://github.com/qgis/QGIS/files/5510179/baykompv_werte2.xlsx)

**Comment by gioman** [comment]
@Bernd-Vogelgesang does it work as expected on 3.10?

**Comment by uclaros** [comment]
I think that defining the header row is only supported on delimited text layers.
The messed order, which also happens on delimited text layers, can be fixed with a custom sort to `$id`

**Comment by gioman** [comment]
> I think that defining the header row is only supported on delimited text layers.

@uclaros no, it worked also for XLS and CSV layers added directly to the project.

**Comment by Bernd-Vogelgesang** [comment]
@gioman Nope. Just reverted to 3.10 and both the xlsx and ods have the same behaviour. Surprisingly a file that I saved "accidently" as xls works fine. Confusing.

**Comment by gioman** [comment]
>  [baykompv_werte2.xlsx](https://github.com/qgis/QGIS/files/5510179/baykompv_werte2.xlsx)

@Bernd-Vogelgesang as soon as you clear formatting and change the column name that is named "30" it works as expected.

And this seems to be an OGR issue.

your table with no formatting and column "30" renamed to something that has only letters:

```
giovanni@nigripes:~/Downloads$ ogrinfo -so baykompv_werte2.xlsx Tabelle1
INFO: Open of `baykompv_werte2.xlsx'
      using driver `XLSX' successful.

Layer name: Tabelle1
Geometry: None
Feature Count: 445
Layer SRS WKT:
(unknown)
KAT: Integer (0.0)
CODE: String (0.0)
TITEL: String (0.0)
G: Integer (0.0)
W: Integer (0.0)
N: Integer (0.0)
GW: Integer (0.0)
BK: String (0.0)
nnnn: String (0.0)
LRT: String (0.0)
```

your table with no formatting and column called "30":

```
giovanni@nigripes:~/Downloads$ ogrinfo -so baykompv_werte2.xlsx Tabelle1
INFO: Open of `baykompv_werte2.xlsx'
      using driver `XLSX' successful.

Layer name: Tabelle1
Geometry: None
Feature Count: 446
Layer SRS WKT:
(unknown)
Field1: String (0.0)
Field2: String (0.0)
Field3: String (0.0)
Field4: String (0.0)
Field5: String (0.0)
Field6: String (0.0)
Field7: String (0.0)
Field8: String (0.0)
Field9: Integer (0.0)
Field10: String (0.0)

```

your table with formatting and column "30" renamed to something that has only letters:

```
giovanni@nigripes:~/Downloads$ ogrinfo -so baykompv_werte2.xlsx Tabelle1 | more
INFO: Open of `baykompv_werte2.xlsx'
      using driver `XLSX' successful.

Layer name: Tabelle1
Geometry: None
Feature Count: 446
Layer SRS WKT:
(unknown)
Field1: String (0.0)
Field2: String (0.0)
Field3: String (0.0)
Field4: String (0.0)
Field5: String (0.0)
Field6: String (0.0)
Field7: String (0.0)
Field8: String (0.0)
Field9: String (0.0)
Field10: String (0.0)
Field11: String (0.0)
Field12: String (0.0)
Field13: String (0.0)
Field14: String (0.0)
Field15: String (0.0)
Field16: String (0.0)
Field17: String (0.0)
Field18: String (0.0)
Field19: String (0.0)
Field20: String (0.0)
Field21: String (0.0)
Field22: String (0.0)
Field23: String (0.0)
Field24: String (0.0)
Field25: String (0.0)
...
...
...
```

**Comment by Bernd-Vogelgesang** [comment]
my bad. didn't see the 30. Actually it meant §30 and I thought this might cause problems. haha.
The formatting seems not to have an influence. Renaming the 30 clumn did the trick. Sorry for the noise, sometimes you can't see the forest ...
