### ISSUE TITLE
Bug QGIS .combine() - Output with NULL Geometry

### ISSUE THREAD

**Issue by arx-it** [qgis/QGIS#39900]
Hello,

I have a problem with .combine() QGIS algorithm.

Steps (how to reproduce) :
- 1. Layer "initGeo " selection and then `initGeo = [f for f in iface.activeLayer().getFeatures()][0].geometry()`
- 2. Layer "modifGeo" selection and then `modifGeo = [f for f in iface.activeLayer().getFeatures()][0].geometry()`
- 3. `initGeo.combine(modifGeo)`

Result :
_<QgsGeometry: null>_

Is there a solution or is it because of my "initGeo" geometries (that are multipart) ?

Thank you.

- initGeo :
![image](https://user-images.githubusercontent.com/12830337/98524495-928b7e00-2277-11eb-8e49-5865da47d80f.png)

- modifGeo :
![image](https://user-images.githubusercontent.com/12830337/98523793-9cf94800-2276-11eb-8120-bbab79e44e26.png)

**Comment by gioman** [comment]
@arx-it is this a question or a bug report?

**Comment by arx-it** [comment]
For me, it is a bug ( I need to combine these two geometries into 1 ), I have written a question to give possible directions

**Comment by gioman** [comment]
> For me, it is a bug

Can you check please by asking in the developers mailing list?

**Comment by arx-it** [comment]
Yes, done

**Comment by lbartoletti** [comment]
@arx-it please, can you attach your data?

**Comment by arx-it** [comment]
Yes, here are the data 

[problem_Combine.zip](https://github.com/qgis/QGIS/files/5690755/problem_Combine.zip)

**Comment by gioman** [comment]
> Yes, here are the data
> 
> [problem_Combine.zip](https://github.com/qgis/QGIS/files/5690755/problem_Combine.zip)

@arx-it there seems to be something very weird/wrong about your data:

1) if you zoom in enough they disappear
2) the tool "multi part to singlepart" has no effect on them
3) if I resave them (i.e. as shapefiles) with the same CRS they land in a different place...

but... the result of 3) works well with your code

`<QgsGeometry: MultiPolygon (((601052.84880504058673978 2428133.81203362997621298, 601051.99060504056978971 2428132.13303363043814898, 601051.02840504061896354 2428130.51203363016247749, 601049.96590504061896354 2428128.95303363027051091, 601048.80740504059940577 2428127.46503363037481904, 601047.55730504053644836 2428126.0520336301997304, 601046.22070504061412066 2428124.71903363056480885, 601044.80280504061374813 2428123.47403363045305014, 601043.30920504056848586 2428122.31903363019227982, 601041.74580504058394581 2428121.26003363030031323, 601040.11880504060536623 2428120.30103363003581762, 601038.43460504058748484 2428119.44603363052010536, 601036.69980504061095417 2428118.69703363021835685, 601034.921305040596053 2428118.05903363041579723, 601033.10610504052601755 2428117.5340336300432682, 601031.26140504062641412 2428117.12303363066166639, 601029.39440504054073244 2428116.82803363027051091, 601027.51250504062045366 2428116.65103363059461117, 600967.25190504058264196 2428111.36603363044559956, ...>

`

**Comment by lbartoletti** [comment]
@arx-it I think your problem is that your geometries are not valid:

>>> initGeo.constGet().isValid() # (False, "Trou à l'extérieur de l'enveloppe")
>>> modifGeo.constGet().isValid() # (False, Self Intersection)

**Comment by gioman** [comment]
> @arx-it I think your problem is that your geometries are not valids:

@lbartoletti yes, now the question is.... why "fix geometries" does nothing?

**Comment by lbartoletti** [comment]
> > @arx-it I think your problem is that your geometries are not valids:
> 
> @lbartoletti yes, now the question is.... why "fix geometries" does nothing?

fix geometries works for me (c)

```
modifRepaired = processing.run("native:fixgeometries", {'INPUT':'/tmp/problem_Combine.gpkg|layername=modifGeo','OUTPUT':'TEMPORARY_OUTPUT'})
initRepaired = processing.run("native:fixgeometries", {'INPUT':'/tmp/problem_Combine.gpkg|layername=initGeo','OUTPUT':'TEMPORARY_OUTPUT'})
initFeat = QgsFeature()
modifFeat = QgsFeature()
initIt = initRepaired['OUTPUT'].getFeatures()
initIt.nextFeature(initFeat)
modifIt = modifRepaired['OUTPUT'].getFeatures()
modifIt.nextFeature(modifFeat)
initGeom = initFeat.geometry()
modifGeom = modifFeat.geometry()
comb = initGeom.combine(modifGeom)
print(comb.asWkt(2))
# 'MultiPolygon (((601052.85 2428133.81, 601051.99 2428132.13, 601051.03 2428130.51, 601049.97 2428128.95, 601048.81 2428127.47, 601047.56 2428126.05, 601046.22 2428124.72, 601044.8 2428123.47, 601043.31 2428122.32, 601041.75 2428121.26, 601040.12 2428120.3, 601038.43 2428119.45, 601036.7 2428118.7, 601034.92 2428118.06, ...
```

**Comment by arx-it** [comment]
Thank you !

Yes, I saw the little holes in the polygons.

Ok for the solution consisting in resaving them into another data.

It works with the fix with "native:fixgeometries".
We tried with "makeValid" function, but it didn't work. Are there differences between "native:fixgeometries and "makeValid" functions ?
