### ISSUE TITLE
Qgis 3.16 keeps crashing randomly: intersect and zoom factor

### ISSUE THREAD

**Issue by soraimperial** [qgis/QGIS#39917]
After reporting issue #39823, although a new blank profile seemed to be working, eventually QGIS 3.16 keeps crashing at random. No plugins now, blank profile with american english language.

When clicking intersect, I have about 50% chance of it crashing. Reload, doesn't crash again. Then decides crashing again.
Same happens with Dissolve. Other tools do not seem to crash at random. Always working with the same dataset.
About 10% of times crashes when clicking the docked processing toolbox.

A few of these problems happen with 3.14 as well, but less regularly.

New problem:
Setting>Options>Map Tools > Change Zoom factor
First, it crashed 4x when clicking Map Tools (like I said, new profile, only changed language to english).
When it finally opened, changed zoom factor to 110%), now it doesn't load any data (about 5minutes with no rendering, orange bar down there keeps loading) and then crashes. Ram usage before crashing was already up to 10Gb.
Data was loading before changing the zoom factor. It also doesn't load on 3.14, so it seems like changing zoom factor (which was changed before and I can't work with the standard 200%) creates this issue.

Returning to my old profile (which has the plugins, the night mapping, and was creating crash #39823), which has 100% zoom factor, solves this problem. Setting to 100% zoom on the blank profile does not solve it.

Getting extremely frustrated, been working with QGIS for over a year, and even though I had some random crashes, I haven't been hours on end getting crashes with whatever I do.

Report copy:

## User Feedback

Crashed 

## Report Details

**Crash ID**: [a8a23a950746c63171532350116b4c8e20312f45](https://github.com/qgis/QGIS/search?q=a8a23a950746c63171532350116b4c8e20312f45&type=Issues)

**Stack Trace**
<pre>
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QObject::setProperty :
QHeaderView::setMovable :
QHeaderView::logicalIndexAt :
QMainWindow::trUtf8 :
QHeaderView::logicalIndexAt :
QWidget::setStyleSheet :
</pre>

**QGIS Info**
QGIS Version: 3.16.0-Hannover
QGIS code revision: 43b64b13f3
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by roya0045** [comment]
similar as #39693 possible duplicate

**Comment by gioman** [comment]
> When clicking intersect, I have about 50% chance of it crashing. Reload, doesn't crash again. Then decides crashing again.
> Same happens with Dissolve. Other tools do not seem to crash at random. Always working with the same dataset.
> About 10% of times crashes when clicking the docked processing toolbox

@soraimperial is QGis crashing or are you talking about errors while running those geoprocessing tools? Regadless can you please attach the data that is causing you troubles?

> New problem:
> Setting>Options>Map Tools > Change Zoom factor
> First, it crashed 4x when clicking Map Tools (like I said, new profile, only changed language to english).
> When it finally opened, changed zoom factor to 110%), now it doesn't load any data (about 5minutes with no rendering, orange bar down there keeps loading) and then crashes. Ram usage before crashing was already up to 10Gb.
> Data was loading before changing the zoom factor. It also doesn't load on 3.14, so it seems like changing zoom factor (which was changed before and I can't work with the standard 200%) creates this issue.

please report it in a new ticket. Also please attach a sample project+data that we ca use to replicate the problem.

**Comment by soraimperial** [comment]
@gioman Qgis is actually crashing: 80% of the times requires me to close the process, 20% of the times shows the sad face crash screen.

I cannot attach the specific data, as it is to my best knowledge confidential (government agency data), but is has happened with other datasets since then. But one of the layers that I was trying to intersect with my own data is this:
http://mapas.dgterritorio.pt/DGT-ATOM-download/COS_Final/COS2018_v1/COS2018_v1.zip

Also, this ticket is for the "new problem": also crashes on zoom factor. The intro (on the problems with intersect), as stated, was opened on ticket #39823.

But so far, it seems to have resolved spontaneously. I have worked 4h this afternoon without ever encountering the problem again: I stopped using the new blank profile and returned to the profile that experienced the #39823 problem.

**Comment by gioman** [comment]
>  http://mapas.dgterritorio.pt/DGT-ATOM-download/COS_Final/COS2018_v1/COS2018_v1.zip

@soraimperial I'm from Portugal I know well this dataset. But I need to understand what type of layer you are using to intersect against the COS, so I can try to replicate the issue.

Also note that the COS is notoriously to have a lot of geometry errors, you must clean it before using in a whatever geoprocessing operation. The COS is also a very large dataset, if you are using it whole as a input layer is normal to have long processing times, and possibly you are hitting some memory limit (especially on Windows).


> Also, this ticket is for the "new problem": also crashes on zoom factor. The intro (on the problems with intersect), as stated, was opened on ticket #39823.

Sorry I don't understand this. To issue reporter we ask to describe the problem possibly by creating a list of detailed steps that lead to the issue. Can you please? 

obrigado

**Comment by soraimperial** [comment]
@gioman Okay, I'll try to be more clear. I'm a huge newb on QGIS (less than a year and self-taught), so sorry if I'm not explaining properly.

1) I was working with a clean, small version of this dataset (only Alentejo Litoral). V.clean and zero buffer. No geometry problems remaining, as far as QGIS showed. I was intersecting it with a hand drawn polygon layer, without any geometry problems and a very simple attribute table.
2) It crashed on several ocasions, BEFORE processing. What I reported on #39823 were crashes when clicking the Intersect button on the top bar. Just clicking it, didn't even open and then stayed crashed until I manually closed the process. It also crashed on double click on symbology and properties ( similar to #39693). I solved it temporarily by using a clean blank profile.
3) Since I was in a new profile and couldn't zoom properly to work, I entered the Setting>Options>Map Tools > Change Zoom factor.
4) It crashed 4 or 5 times when just clicking Map Tools.
5) Then it randomly worked (and hasn't crashed on Map Tools since) and I changed Zoom Factor to 110%.
6) None of my 20 layers now loaded, but the program wasn't crashed. It just stayed rendering, without showing any information. Until it crashed. I wasn't doing any processing whatsoever. Same problem happened as well when I returned to blank profile 3.14.
7) I still had ram left. The most that QGIS used was 10Gb when it was trying to load the information (I had 3 layers visible), system was using 2Gb, so I still had 4Gb of RAM left. Again, I wasn't processing anything. The crashes were either on clicking, before processing, and later on just trying to render the image.
8) I returned to my personal profile on 3.16, and now Map Tools opens perfectly. Zoom factor of 100% and 110% both work and the data renders. The previous problems on #39823 (random crashes) were also suddenly gone. 
9) After opening this thread... I haven't had a single problem, kept on working with the same datasets (intersect, dissolve, merge layers, calculations with the attribute table, creating new gpkg and changing symbology, all fine). 
10) This seems to happen every once in a while. Every two months I have a few days where it crashes no matter what I do and then it just "fixes itself" outta nowhere, without me doing anything. And again, I am not talking about crashes or errors while processing (I also have them, but those i know that are to blame on the layers).

**Comment by gioman** [comment]
>     1. I was working with a clean, small version of this dataset (only Alentejo Litoral). V.clean and zero buffer. No geometry problems remaining, as far as QGIS showed. I was intersecting it with a hand drawn polygon layer, without any geometry problems and a very simple attribute table.

@soraimperial so if your input are a subset of the COS and a hand drawn polygon... can't you share them? The COS is free/open and the hand drawn polygon should not be sensitive info :) 

By the way...  now in QGIS you have the "fix geometries" tool, which simplifies a lot the operation of cleaning geometries.

For the rest... thanks, is a lot of information. Would you like to try explain the issue to me by phone? if yes please write me at giovanni dot manghi at naturalgis dot pt and I will give you my phone number.

**Comment by soraimperial** [comment]
The hand drawn polygons will be part of a strategic document from a government agency, impending release and under discussion in the Conselho de Ministros and several other national institutions. Proooobably it is okay, but the full contents of the document that will include our cartographic products are currently under "reserved/confidential" classification, so I rather not risk without permission. Even if you guys work with a lot of public institutes. I will check with my superiors.

And sorry, I also used the fix geometries, yes. Forgot it. I always use the 3 solutions: fix geometries, v.clean and a zero buffer, when working with COS. Maybe overkill, but the COS was the first dataset I ever worked with, and this solution was the first one I got to 100% abolish errors.

Thanks! Atm I am not able to talk on the phone due to a health issue, but will pick up on your offer if the problems returns, thank you so much!

**Comment by gioman** [comment]
> The hand drawn polygons will be part of a strategic document from a government agency, impending release and under discussion in the Conselho de Ministros and several other national institutions. Proooobably it is okay, but the full contents of the document that will include our cartographic products are currently under "reserved/confidential" classification, so I rather not risk without permission. Even if you guys work with a lot of public institutes. I will check with my superiors.
> 
> And sorry, I also used the fix geometries, yes. Forgot it. I always use the 3 solutions: fix geometries, v.clean and a zero buffer, when working with COS. Maybe overkill, but the COS was the first dataset I ever worked with, and this solution was the first one I got to 100% abolish errors.

@soraimperial what is left do here? we don't have any project/dataset we can use to replicate the issues you describe, and with our own data we cannot replicate. I suggest closing this. Then contact me directly when you can, if there is  an issue we can reopen this.

**Comment by gioman** [comment]
Closing for lack of feedback.
