### ISSUE TITLE
qgis (3.16) flatpak is missing "pip3" command

### ISSUE THREAD

**Issue by larsks** [qgis/QGIS#39912]
**Describe the bug**

According to [the documentation](https://qgis.org/en/site/forusers/alldownloads.html#flatpak), one can install additional Python modules into the QGIS flatpak environment like this:

```
flatpak run --command=pip3 org.qgis.qgis install urllib3 --user
```

But this command fails; it appears that neither `pip` nor `pip3` are available in the flatpak environment.

**How to Reproduce**

1. Install the QGIS flatpak  as described in https://qgis.org/en/site/forusers/alldownloads.html#flatpak
2. Run `flatpak run --command=pip3 org.qgis.qgis install pygments --user`
4. See error:

    ```
    bwrap: execvp pip3: No such file or directory
    ```

**QGIS and OS versions**

QGIS version | 3.16.0-Hannover | QGIS code revision | 43b64b13
-- | -- | -- | --
Compiled against Qt | 5.15.1 | Running against Qt | 5.15.1
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.32.1 | Running against SQLite | 3.32.1
PostgreSQL Client Version | 12.2 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.5 | QScintilla2 Version | 2.11.5
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | KDE Flatpak runtime
Active python plugins | db_manager

**Comment by jef-n** [comment]
The flatpak releases aren't supported by the QGIS project -- they are a downstream community effort. You'll need to file this bug at flathub against the QGIS package there instead.

**Comment by larsks** [comment]
@jef-n how about the docker image (which looks like it's built automatically via github actions)? I'm seeing some issues there as well.
