### ISSUE TITLE
QGIS 3.14.16 not showing spatialite's timestamp values in Attribute Table

### ISSUE THREAD

**Issue by lomasz** [qgis/QGIS#39929]
**Description**
I opened in QGIS (3.14.16) spatialite's table which has timestamp type field, but values in this field are not visible (NULL) in Attribute Table.

In DB Manager's table tab these values are visible correctly, but in Attribute Table they are NULL.

**Steps to reproduce:**
1. Add layer: spatialite with `timestamp` type field.
[![Table structure][1]][1]
2. Go to DB Manager - choose '`Table` tab - timestamp values are correctly
[![DB Manager - Table][2]][2]
3. Go to `Attribute Table` for this layer - timestamp values are NULL.
[![Attribute Table][3]][3]
[![Layer Fields][4]][4]

  [1]: https://i.stack.imgur.com/tfDVG.png
  [2]: https://i.stack.imgur.com/HzgTT.png
  [3]: https://i.stack.imgur.com/sPoCp.png
  [4]: https://i.stack.imgur.com/J1ddp.png

**Comment by nirvn** [comment]
@lomasz , can you open the information panel of that layer properties and take a screenshot? I'm looking to confirm whether your layer is opened via the OGR provider of QGIS' native spatialite provider.

**Comment by lomasz** [comment]
![image](https://user-images.githubusercontent.com/14858816/98658678-9ab0ef80-2343-11eb-9cc3-4ef8ae931938.png)

**Comment by nirvn** [comment]
@lomasz , thanks -- can you share your dataset (or a sample of it) here?

**Comment by lomasz** [comment]
https://drive.google.com/file/d/1NvGkO66Rp7Gftk_kk7xRAa1PEsDe_JhL/view

**Comment by nirvn** [comment]
PR #39931 fixes your issue:
![image](https://user-images.githubusercontent.com/1728657/98664363-de741b00-237c-11eb-8b68-7a2c11d28a5f.png)

It'll be available in the next 3.16.1 release (in ~1 week). Thanks for reporting the issue & providing a sample dataset.

**Comment by lomasz** [comment]
Nice, thanks! 👍
