### ISSUE TITLE
DXF Export Crash

### ISSUE THREAD

**Issue by RHARCSURVEYS** [qgis/QGIS#39925]
**### When trying to export project to dxf, the dialog noes not appear and the program Crashes.**

**QGIS and OS versions**

QGIS version | 3.8.1-Zanzibar | QGIS code revision | dcd95cc648
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.0 | Running against GEOS | 3.7.2-CAPI-1.11.0 b55d2125
PostgreSQL Client Version | 9.2.4 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Windows 10 (10.0) |   |  

AND********************

QGIS version | 3.16.0-Hannover | QGIS code revision | 43b64b13f3
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | geosys-plugin; oneatlas-qgis-plugin-1_0_1; planet_explorer; qveg; rastertimeseriesmanager; db_manager; MetaSearch; processing

**Comment by SrNetoChan** [comment]
@RHARCSURVEYS Can you please try using a more recent version of QGIS, either 3.10.11 (current long term release) or 3.16.0 (most recent stable release)?

3.8 more than 1.5 years old and it's no longer supported.

**Comment by gioman** [comment]
Also try with a new QGIS profile (on 3.10 or 3.16).

**Comment by RHARCSURVEYS** [comment]
Sorry if this is a dumb question… How do you create a new profile???

Kind Regards,

Rowan Hunt
Survey Draftsman
rowanh@arcsurveys.com.au<mailto:rowanh@arcsurveys.com.au>
Phone: (07) 54 955 977
www.arcsurveys.com.au

[Title: Facebook - Description: Facebook icon]<https://www.facebook.com/ArcSurveys/> [Title: LinkedIn - Description: LinkedIn icon] <https://au.linkedin.com/company/arc-surveys-pty-ltd>
 [cid:image007.png@01D6B821.ADB489D0] <https://www.12d.com/community/2018-innovation-awards.html>
[cid:image008.png@01D6B821.ADB489D0]<http://www.arcsurveys.com.au/>
This message and any associated attachments may contain Privileged and / or Confidential Information and is intended solely for the named addressees. Distribution or copying of any part of this transmission by anyone other than the addressees is prohibited. If you received this message in error, please delete the message and destroy any printed copies. Views in the message are those of the individual sender. It is recommended that you scan this email and attachments before opening. ARC Surveys does not accept any responsibility or liability for loss or damage arising from opening this email.

**Comment by SrNetoChan** [comment]
Settings > User profiles > New profile...

https://docs.qgis.org/3.10/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles

**Comment by RHARCSURVEYS** [comment]
Tried the new profile and got the same crash:

Crash ID: e3ef196493fa88043ba3392945696f96e8c1fc1b<https://github.com/qgis/QGIS/search?q=e3ef196493fa88043ba3392945696f96e8c1fc1b&type=Issues>


Stack Trace

QgsMarkerSymbolLayer::scaleMethod qgsarrowsymbollayer.h:57
QgsDiscoverRelationsDialog::relations :
QgsDiscoverRelationsDialog::relations :
QgisApp::dxfExport :
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :



QGIS Info
QGIS Version: 3.16.0-Hannover
QGIS code revision: 43b64b13f3
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

Kind Regards,

Rowan Hunt
Survey Draftsman
rowanh@arcsurveys.com.au<mailto:rowanh@arcsurveys.com.au>
Phone: (07) 54 955 977
www.arcsurveys.com.au

[Title: Facebook - Description: Facebook icon]<https://www.facebook.com/ArcSurveys/> [Title: LinkedIn - Description: LinkedIn icon] <https://au.linkedin.com/company/arc-surveys-pty-ltd>
 [cid:image007.png@01D6B8CD.4ACC5580] <https://www.12d.com/community/2018-innovation-awards.html>
[cid:image008.png@01D6B8CD.4ACC5580]<http://www.arcsurveys.com.au/>
This message and any associated attachments may contain Privileged and / or Confidential Information and is intended solely for the named addressees. Distribution or copying of any part of this transmission by anyone other than the addressees is prohibited. If you received this message in error, please delete the message and destroy any printed copies. Views in the message are those of the individual sender. It is recommended that you scan this email and attachments before opening. ARC Surveys does not accept any responsibility or liability for loss or damage arising from opening this email.

**Comment by SrNetoChan** [comment]
I am not able to replicate using 3.16 on a fresh Windows installation.

@RHARCSURVEYS could you share the project you are using that is causing the crash?

**Comment by RHARCSURVEYS** [comment]
Should be everything needed to replicate
[PLP0561_ARC_PROJECT_2.zip](https://github.com/qgis/QGIS/files/5527179/PLP0561_ARC_PROJECT_2.zip)
[ARC_PLP_BDY_28-09-2017.zip](https://github.com/qgis/QGIS/files/5527181/ARC_PLP_BDY_28-09-2017.zip)
[DCDB_MGA 28-09-17 Cadastral_data_QLD_CADASTRE_DCDB any_PARCEL_TYP__Lot Type Parcel.zip](https://github.com/qgis/QGIS/files/5527182/DCDB_MGA.28-09-17.Cadastral_data_QLD_CADASTRE_DCDB.any_PARCEL_TYP__Lot.Type.Parcel.zip)

**Comment by RHARCSURVEYS** [comment]
Oh and this one
[QSC_Extracted_Data_20201106_143747490000-9156.zip](https://github.com/qgis/QGIS/files/5527195/QSC_Extracted_Data_20201106_143747490000-9156.zip)

**Comment by SrNetoChan** [comment]
Sorry @RHARCSURVEYS but there are lots of missing layers. Can you please send on single zip file with both the project and the data in their relative path so that opening the project is automatic?

**Comment by RHARCSURVEYS** [comment]
I think I found it... Layers CRS was GDA94/MGA Zone 56.
Australia Recently Shifted to the new coord sys GDA 2020. Threw a spanner in the works. Made the data do a harold holt and left me up shit creek.
Sorry for the dodgy upload, first time having to raise an issue.

**Comment by nyalldawson** [comment]
@RHARCSURVEYS I understand you perfectly, but i suspect 99.9% of the readers here have no clue what you just said 😂

**Comment by RHARCSURVEYS** [comment]
Ken oath, Cobber! Those other Flamin' Gallahs might think I've got a few kangaroos loose in the top paddock.

**Comment by nyalldawson** [comment]
In any case, the CRS diff shouldn't result in a crash! Can you answer @SrNetoChan's question and send an updated project so that we can fix?

**Comment by gioman** [comment]
> Ken oath, Cobber! Those other Flamin' Gallahs might think I've got a few kangaroos loose in the top paddock.

is this some kind of (AU?) slang?

**Comment by gioman** [comment]
Closing for lack of feedback.
