### ISSUE TITLE
Native Raster Calculator does not deal correctly with no data pixels when GPU acceleration is enabled

### ISSUE THREAD

**Issue by PedroVenancio** [qgis/QGIS#39926]
It seems that native Processing Raster Calculator (https://docs.qgis.org/3.16/en/docs/user_manual/working_with_raster/raster_analysis.html#raster-calculator) does not deal well with no data pixels as any other raster calculator (gdal_calc, r.mapcalc.simple, SAGA Raster Calculator), that just keep the no data in the output layer. Please see in the following screenshot, where all give no data (the operation is just a sum), native Raster Calculator gives 256. 

![imagem](https://user-images.githubusercontent.com/1331581/98613266-da4cec80-22ed-11eb-91d2-3c2fd232602e.png)

I don't know where this value come from, because the output image is a Float32:

```
Name | Native Raster Calculator
Extent | 61738.6840999999985797,107229.7801999999937834 : 63463.6840999999985797,108429.7801999999937834
Unit | meters
Width | 345
Height | 240
Data type | Float32 - Thirty two bit floating point
GDAL Driver Description | GTiff
GDAL Driver Metadata | GeoTIFF
Band 1 | STATISTICS_MAXIMUM=256STATISTICS_MEAN=49.730265700483STATISTICS_MINIMUM=4STATISTICS_STDDEV=95.667489502732STATISTICS_VALID_PERCENT=100
More information | AREA_OR_POINT=Area
Dimensions | X: 345 Y: 240 Bands: 1
Origin | 61738.7,108430
Pixel Size | 5,-5
```

Here is a sample dataset: https://cld.pt/dl/download/78bcfadd-30c8-4bde-b710-98eb9cb5e03f/Raster_Calculator_No_Data.zip 

Try a sum or a multiplication of both rasters and look at the output. 

Another issue in native Raster Calculator is that the Expression is not saved in Processing history, so if it is open from history list to be re-executed, the expression needs to be inserted again.

Tested on Windows, with QGIS 3.10 and 3.16.

**Comment by SrNetoChan** [comment]
Can't confirm on QGIS 3.10.11 LTR (ubuntu 18.04 and xubuntu 20.04), neither on QGIS 3.16.0 (xubuntu 20.04).

Couldn't use QGIS raster calculator on a self-compiled QGIS 3.16.0 on ubuntu 18.04, it always says that expression is empty.

**Comment by SrNetoChan** [comment]
Couldn't confirm in Windows 10 both 3.10.11 and 3.16.0 either. Seems like some local issue.

**Comment by nicogodet** [comment]
I can confirm on 3.16 windows.
I will provide a sample.

**Comment by gioman** [comment]
@PedroVenancio can't confirm here, tested on 3.10 on Windows and 3.16 on Ubuntu 20.04.

**Comment by PedroVenancio** [comment]
Ok, in a clean profile, it does not happen.

But happens even starting QGIS with --noplugins, so I believe that is not a plugin conflict issue.

Any hint about a setting that can be causing this behaviour?

**Comment by PedroVenancio** [comment]
Ok, I think I've found the source of the issue. 

With the OpenCL acceleration enabled, I've the issue. 

Without OpenCL acceleration, the output is correct.

![imagem](https://user-images.githubusercontent.com/1331581/98663041-7acbfc80-2340-11eb-920a-e65a90e72284.png)

This makes sense to you @elpaso ?

**Comment by SrNetoChan** [comment]
Confirmed that at least in 3.10 on Linux with OpenCL acceleration enabled will replicate the problem.

**Comment by elpaso** [comment]
@SrNetoChan and with OpenCL disabled?

**Comment by SrNetoChan** [comment]
@elpaso if the acceleration is disable I wasn't able to replicate the problem.

**Comment by PedroVenancio** [comment]
> @elpaso if the acceleration is disable I wasn't able to replicate the problem.

Yes, same behaviour on Windows with 3.16.

**Comment by elpaso** [comment]
@PedroVenancio can you please attach a small sample? Just to make sure I'm testing the same scenario.

**Comment by gioman** [comment]
> Here is a sample dataset: https://cld.pt/dl/download/78bcfadd-30c8-4bde-b710-98eb9cb5e03f/Raster_Calculator_No_Data.zip

@PedroVenancio link above.

**Comment by PedroVenancio** [comment]
> 
> 
> > Here is a sample dataset: https://cld.pt/dl/download/78bcfadd-30c8-4bde-b710-98eb9cb5e03f/Raster_Calculator_No_Data.zip
> 
> @PedroVenancio link above.

Yes @elpaso simply open that project and try to do a sum or any other simple operation between two included rasters with and without OpenCL acceleration enabled, and check what happens to the no data values in the output.
