### ISSUE TITLE
SAGA Random Terrain generation - Bug

### ISSUE THREAD

**Issue by jkr-wrk** [qgis/QGIS#39945]
When running the Random Terrain Generation from the Toolbox with all settings to default, there is one setting you have to pick.
The only option I have for 'Target Dimensions' is [0] User defined.

So the settings are:
grid_calculus "Random Terrain Generation" -RADIUS 10 -ITERATIONS 10 -TARGET_TYPE 0 -USER_CELL_SIZE 1.0 -USER_COLS 100 -USER_ROWS 100 -TARGET_GRID "%userprofile%/Temp/processing_GIBBERISH/processing_GIBBERISH/GIBBERISH/TARGET_GRID.sdat"

I see a message in the log: Error: select a tool

The following layers were not correctly generated.<ul><li>BLABLA</li></ul>You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.

I get the same results in **QGIS on Windows 7** - 3.10/3.14/3.16

There is no output from this tool. When opening SAGA and run the Tool there is output.

**Comment by gioman** [comment]
@jkr-wrk what operating system?

**Comment by jkr-wrk** [comment]
Edited my original post "QGIS on Windows 7".

**Comment by gioman** [comment]
> Edited my original post "QGIS on Windows 7".

@jkr-wrk standalone installer or osgeo4w?

**Comment by jkr-wrk** [comment]
Stand alone installer

**Comment by agiudiceandrea** [comment]
The Saga tool "[Random Terrain Generation](http://www.saga-gis.org/saga_tool_doc/2.1.3/grid_calculus_6.html)" was renamed to "[Random Terrain](http://www.saga-gis.org/saga_tool_doc/2.3.0/grid_calculus_6.html)" in SAGA 2.3.2 which is installed by OSGeo4W.
Moreover, the parameters have also been renamed.

**Comment by gioman** [comment]
> The Saga tool "[Random Terrain Generation](http://www.saga-gis.org/saga_tool_doc/2.1.3/grid_calculus_6.html)" was renamed to "[Random Terrain](http://www.saga-gis.org/saga_tool_doc/2.3.0/grid_calculus_6.html)" in SAGA 2.3.2 which is installed by OSGeo4W.
> Moreover, the parameters have also been renamed.

I'll patch it.

**Comment by gioman** [comment]
See https://github.com/qgis/QGIS/pull/39965
