### ISSUE TITLE
Error in "zone histogram" tool

### ISSUE THREAD

**Issue by cacostam** [qgis/QGIS#39941]
The "zone histogram" tool calculates values when the output is executed as temporary, different from when the output is executed as a file. 

If you run the "zone histogram" tool with "temporary file" as the output, the tool will give you a value as a solution. If you try to save the temporary file to a shp file on your computer, the values of the attribute table calculated with the tool will change.

**Comment by jonnyforestGIS** [comment]
Hi, @cacostam do you mean the algorithm Zonal Histogram from Raster Analysis?
Please provide Operating System and QGIS Version.

Regards

**Comment by PedroVenancio** [comment]
@cacostam I cannot confirm here, on QGIS 3.16.

Can you provide some test dataset?

**Comment by cacostam** [comment]
The tool is: Zonal Histogram from Raster Analysis
The operating system of the computers on which the tests were carried out was Windows 10
Tests were made in QGIS 3.10.11 to Coruña.


Attached are the test data.

**Comment by jonnyforestGIS** [comment]
I tested with your DATA in Windows 10:
QGIS 3.10.10 - OK values are equal with temporary and saved into a file.
QGIS 3.10.11 - OK values are equal with temporary and saved into a file.

**Comment by gioman** [comment]
Closing for lack of feedback and is not reproducible.
