### ISSUE TITLE
Qgis crash whem import srtm from Topodata INPE

### ISSUE THREAD

**Issue by adssonandre** [qgis/QGIS#39951]
**Describe the bug**
Qgis crash and close his window, when a try to import some SRTM image from Topodata INPE (http://www.webmapit.com.br/inpe/topodata/)

**How to Reproduce**
Just importing some SRTM image from Topodata INPE anyway

**QGIS and OS versions**
I am using Qgis 3.10.11 LTR on Ubuntu 20.04 LTS

**Comment by gioman** [comment]
@adssonandre cannot confirm, also o Ubuntu 20.04. I tried http://www.dsr.inpe.br/topodata/data/geotiff/05S585ZN.zip

By the way that data does not seems to have a valid CRS, I think

```
gdalinfo 05S585ZN.tif 
Driver: GTiff/GeoTIFF
Files: Downloads/05S585ZN.tif
Size is 5400, 3600
proj_uom_get_info_from_database: unit of measure not found
proj_create_from_database: datum not found
proj_create_from_database: ellipsoid not found
proj_create_from_database: prime meridian not found
proj_uom_get_info_from_database: unit of measure not found
Coordinate System is:
ENGCRS["projection=lat/long   units= deg",
    EDATUM[""],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]]]
Data axis to CRS axis mapping: 1,2
Origin = (-58.500000000000000,-5.000000000000000)
Pixel Size = (0.000277778481481,-0.000277777777778)
Metadata:
  AREA_OR_POINT=Area
  TIFFTAG_RESOLUTIONUNIT=2 (pixels/inch)
  TIFFTAG_SOFTWARE=IDRISI KILIMANJARO
  TIFFTAG_XRESOLUTION=87.699997
  TIFFTAG_YRESOLUTION=87.699997
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  ( -58.5000000,  -5.0000000) 
Lower Left  ( -58.5000000,  -6.0000000) 
Upper Right ( -56.9999962,  -5.0000000) 
Lower Right ( -56.9999962,  -6.0000000) 
Center      ( -57.7499981,  -5.5000000) 
Band 1 Block=5400x1 Type=Float32, ColorInterp=Gray



```

**Comment by gioman** [comment]
ok, if you manually give that layer the 4326 CRS it goes in the right place, but in origin is not well defined in the datasource.

![Uploading Screenshot_20201111_111443.png…]()

**Comment by adssonandre** [comment]
I opened Qgis through the Ubuntu terminal and when i try to import the SRTM, the terminal showed that:

**Fatal Python error: PyThreadState_Get: no current thread
Python runtime state: initialized

Current thread 0x00007f2bba439f80 (most recent call first):
<no Python frame>
Aborted (core dumped)**

I could not define CRS, because the software crash.

**Comment by gioman** [comment]
> I opened Qgis through the Ubuntu terminal and when i try to import the SRTM, the terminal showed that:

@adssonandre this do not seems to be a general QGIS issue, is more likely a local one. Please try on a different machine. You may want to try also on a new QGIS profile, to check if it makes any difference.

**Comment by gioman** [comment]
Closing for lack of feedback.
