### ISSUE TITLE
Double dissolvence fails

### ISSUE THREAD

**Issue by MattUm** [qgis/QGIS#39963]
Goodmorning,
I have an issue with a QGIS project: I tried to make a second dissolvence on a file using QGIS 3.16, the process has reached 100%, but it doesn't give me the resulting file. The file I want was created in the right folder, but, even if added on the map, it seems to be wrong (it's as if it wasn't there).
I used the same process with another file and it worked, so I think the starting file (named "2_CF_Mezzo_Piemonte) has a problem. 
Could someone help me, please? I had asked a question on this forum previously and I got great support, so I thought I'd write here again. I'm quite disperate with this project.
I also attach a photo of the error and all the data with a Google Drive link, I hope it helps.
https://drive.google.com/drive/folders/1-heQZM2v7lcdTP7km64AXo9PznjrffCa?usp=sharing
Thanks in advance.
![D-Dissolvence fails](https://user-images.githubusercontent.com/73936953/98821787-49caf500-2430-11eb-9f48-9a416034ab2b.png)

**Comment by gioman** [comment]
@MattUm there is no "dissolve_clip_mpc_torino" (as seen in your screenshot) in the provided zip. Anyway the probable source of your problem is that your input has geometry problems, you must clean it, using the "fix geometries" tool as already pointed to you in https://github.com/qgis/QGIS/issues/39800#issuecomment-721723639

**Comment by MattUm** [comment]
Hi @gioman !
I use QGIS in italian and I tried to search that funcion, but I find only this window (in the photo) that controls my geometries. 
Is it near the function I reported in this comment? I tried also searching on Google, but the only tutorials I found includes active script editing
![Validità geometrie](https://user-images.githubusercontent.com/73936953/98849228-2feed980-2453-11eb-8391-32ceb8f91845.png)

**Comment by gioman** [comment]
> Hi @gioman !
> I use QGIS in italian and I tried to search that funcion, but I find only this window (in the photo) that controls my geometries.
> Is it near the function I reported in this comment? I tried also searching on Google, but the only tutorials I found includes active script editing

@gioman it is in the processing toolbox and you can search it with its English name "fix geometries" even if your system is in another language. Please attach the required input layer.

**Comment by MattUm** [comment]
Ok, I probably fixed it.
Thank you so much, @gioman ! You are a QGIS hero!
