### ISSUE TITLE
Tessellation crushes with a triangle

### ISSUE THREAD

**Issue by isaomatsunami** [qgis/QGIS#39976]
**Describe the bug**
tessellation crushes QGIS when one of the target features is a triangle.

**How to Reproduce**

1. Create a new Project and create a shape file with a single feature of triangle
2. Apply tessellation
3. QGIS crushes

**QGIS and OS versions**

QGISバージョン | 3.16.0-Hannover | QGISコードリビジョン | 4af1cbfb97
-- | -- | -- | --
コンパイル時のQtバージョン | 5.14.2 | 実行中のQtバージョン | 5.14.2
コンパイル時のGDAL/OGRバージョン | 3.1.2 | 実行中のGDAL/OGRバージョン | 3.1.2
コンパイル時のGEOSバージョン | 3.8.1-CAPI-1.13.3 | 実行中のGEOSバージョン | 3.8.1-CAPI-1.13.3
コンパイル時のSQLiteバージョン | 3.31.1 | 実行中のSQLiteバージョン | 3.31.1
PostgreSQLクライアントバージョン | 12.3 | SpatiaLiteバージョン | 4.3.0a
QWTバージョン | 6.1.4 | QScintilla2 バージョン | 2.11.4
コンパイル時のPROJバージョン | 6.3.2 | 実行中のPROJバージョン | Rel. 6.3.2, May 1st, 2020
OSのバージョン | macOS 10.15
Active pythonプラグイン | QNEAT3; contour; GroupStats; realcentroid; processing; db_manager; MetaSearch

The Linux version also crushes.

**Additional context**

Square and Polygon with more vertices works fine.

**Comment by uclaros** [comment]
That's strange, I've added a test to cover this specific case while fixing  #36024

**Comment by isaomatsunami** [comment]
MultiPolygon of which one of the parts is a triangle also make QGIS crush.

Temporally I can avoid it by making triangles into triangle-looking polygons.

**Comment by uclaros** [comment]
This is a regression, it seems the test was modified and broken by #36981.
Until this gets fixed, you can avoid the crash by using Z enabled polygon layers.

**Comment by isaomatsunami** [comment]
Thank you. I will.
