### ISSUE TITLE
Geopackages saved from scratch files do not save relative to project.

### ISSUE THREAD

**Issue by drf5n** [qgis/QGIS#39975]
**Describe the bug**

Saving a scratch layer as a geopackage with a relative filename does not produce a geopackage in the project home directory.

**How to Reproduce**

1) Create a new project with a fresh profile
2) Create a Scratch layer
3) Click on the DIP-icon to open the menu for saving the scratch layer
4) enter a plain filename (screenshot below)
5) save. (Note the saved file message with the bare filename.) (screenshot below) 
6) Note also that the project does not have a file or home yet

or 

1) Create a new project with a fresh profile
2) Save the project
3) Create a Scratch layer
4) Click on the DIP-icon to open the menu for saving the scratch layer
5) enter a plain filename  (screenshot below)
6) save. 
7) Open Project Properties and note the path to the project file and the 'relative' paths (screenshot below)
8) Check the project directory fo the file.

**QGIS and OS versions**

QGIS version | 3.16.0-Hannover | QGIS code revision | 4af1cbfb97
-- | -- | -- | --
Compiled against Qt | 5.14.2 | Running against Qt | 5.14.2
Compiled against GDAL/OGR | 3.1.2 | Running against GDAL/OGR | 3.1.2
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.4
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | macOS Mojave (10.14)
Active python plugins | processing; db_manager; MetaSearch

**Additional context**

I noticed this problem when trying to re-open a project from a different profile. The saved geopackage wasn't in the same directory as the project file, and I was unable to find it on my system.  The same profile will reopen the project with the geopackage layer, so the data is somewhere.  Is it stored relative to something in the profile rather than the project?

![image](https://user-images.githubusercontent.com/2236516/98858299-61a17980-242e-11eb-897b-f074fd2bb045.png)

![image](https://user-images.githubusercontent.com/2236516/98858439-98778f80-242e-11eb-8ee9-0c76095d20b9.png)

![image](https://user-images.githubusercontent.com/2236516/98859096-a4b01c80-242f-11eb-8270-0eaf19b365f6.png)

![image](https://user-images.githubusercontent.com/2236516/98859239-db863280-242f-11eb-8fdf-e19f4df057b0.png)

**Comment by roya0045** [comment]
same issue as #35651,but in linux

**Comment by drf5n** [comment]
I found my files using the Python Console:

```
import os
os.getcwd()
os.listdir()

```

![image](https://user-images.githubusercontent.com/2236516/98896908-1c099e80-2478-11eb-8614-f1f1bc1ae0eb.png)

On OSX, this initial working directory could be `/` if you start QGIS by opening a file in Finder, or from the command line with "open project.qgz".  If I open a fresh profile, the initial working directory is `/Applications/QGIS.app/Contents/MacOS`

This might explain this error while trying to save a scratch layer with a plain name fails with a normal QGIS invocation on MacOS, but works for a fresh profile: The fresh profile is in a user-writable location, but the normal default tries to write in the root directory.

![image](https://user-images.githubusercontent.com/2236516/98897926-74da3680-247a-11eb-8067-8e453027b5ae.png)
 

I like the workaround posed https://github.com/qgis/QGIS/issues/35651#issue-595785633 with a startup like:

```
import os

# set the working directory at startup (otherwise it defaults to the bin location)
os.chdir(os.environ['HOME'])

```
...which is a more consistent and usable place than the `/` from a normal invocation or the `/Applications/QGIS.app/Contents/MacOS.

**Comment by PeterPetrik** [comment]
is this macos only?

**Comment by gioman** [comment]
> same issue as #35651,but in linux

Closing as duplicate then.

**Comment by gioman** [comment]
> is this macos only?

@PeterPetrik no, seems to be true an all platforms.

**Comment by drf5n** [comment]
> > is this macos only?
> 
> @PeterPetrik no, seems to be true an all platforms.

Yes: Windows, MacOS, and apparently Linux.

**Comment by djcronkw** [comment]
Yes I have this problem on windows also.
