### ISSUE TITLE
Extra vertex on polygon

### ISSUE THREAD

**Issue by Gusarovmax** [qgis/QGIS#39991]
An extra vertex is added (the first point is duplicated) when creating a polygon

**Comment by uclaros** [comment]
The last vertex of a polygon should always be the same as the first. So a triangle has 4 vertices by design, two of which are the same.

**Comment by Gusarovmax** [comment]
But at the same time, incorrect geometry is created, which is checked by standard means, and errors of the object geometry are displayed. Versions earlier than 3.14 did not have this problem.

**Comment by uclaros** [comment]
Can you please add the exact steps to replicate the issue?

**Comment by Gusarovmax** [comment]
1. Create a polygon layer in any of the projections
2. Editing a layer
3. Add Polygon Tool
4. Create object on the map
5. Save layer edits
6. Click on the object with the "edit nodes" tool (the extra node is highlighted in green)
7. Make sure there is a front node (drag nodes)
8. Check with the "Check geometry" tool)
9. Make sure that every polygonal object created has extra nodes

**Comment by Gusarovmax** [comment]
Update:
Sorry, version 3.16. No 3.14

**Comment by uclaros** [comment]
Can you also try with a clean profile - no plugins?
Maybe it's relevant to #39680

**Comment by Gusarovmax** [comment]
If plugins are disabled, the problem does not appear. I confirm.
#39680 has an identical problem but with line features.
I can't work without plugins. What could be the problem with an extra node?

**Comment by gioman** [comment]
>  I can't work without plugins. What could be the problem with an extra node?

@Gusarovmax you must find what plugin is the culprit and warn the author/s.

**Comment by Gusarovmax** [comment]
The problem disappeared after restarting plugins.
Thanks!

**Comment by Gusarovmax** [comment]
The culprit is the module Processing

**Comment by gioman** [comment]
> The culprit is the module Processing

@Gusarovmax that is a core plugin, are you sure?

**Comment by Gusarovmax** [comment]
Yes, I personally restarted only it and the problem disappeared

**Comment by Gusarovmax** [comment]
Can I open a new thread on this issue?

**Comment by gioman** [comment]
> Yes, I personally restarted only it and the problem disappeared

@Gusarovmax so you have it active now and no issue?

**Comment by gioman** [comment]
> Can I open a new thread on this issue?

@Gusarovmax no wait, I would like to confirm it here before opening a new ticket.

**Comment by Gusarovmax** [comment]
@gioman How else can I help?

**Comment by Gusarovmax** [comment]
@gioman after restarting the processing module in one session, the problem does not appear

**Comment by Gusarovmax** [comment]
The problem went deeper. Disconnected absolutely all modules. Created 5 polygon objects. 3 out of 5 have an extra node created. 2 out of 5 have no problems with geometry, there is no extra node.

**Comment by gioman** [comment]
> Disconnected absolutely all modules

@Gusarovmax disabling plugins without restarting QGIS may not be enough. Try restart QGIS after having disabled all the 3rd party plugins. Even better if you can uninstall them, or more easily... use a new QGIS profile.

**Comment by Gusarovmax** [comment]
@gioman Created a new profile and repeated the creation of the polygon - there is an extra node.
Then I disabled all modules and reloaded the program. Created a polygon - no extra nodes.
I turned on all the modules again, created a polygon. There are no extra nodes, but the "Advanced digitize tool (Orange triangle)" button failed - it is no longer active.
The problem remains in the old profile.

**Comment by gioman** [comment]
> @gioman Created a new profile and repeated the creation of the polygon - there is an extra node.
> Then I disabled all modules and reloaded the program. Created a polygon - no extra nodes.

@Gusarovmax I can't replicate this. meaning that in both scenarios the first and last vertexes are always repeated. This is coherent with WKT definition of geometries https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry For good measure I also checked on polygons that were created on other GIS software, is the same.
