### ISSUE TITLE
Time-aware identify tool

### ISSUE THREAD

**Issue by anitagraser** [qgis/QGIS#39993]
**Feature description.**
Currently, the identify tool is not time-aware. This makes it very hard to use it on large time-enabled layers.
Making the identify tool time-aware would enable users to make them only list features within the current time period.

**Additional context**
Since TimeManager used to apply a subset string on the layer data provider, time-awareness of identify was the default/only behavior when working with TimeManager.

Related to: #39076

**Comment by nirvn** [comment]
@anitagraser , already fixed :)

**Comment by anitagraser** [comment]
@nirvn thanks, then #39856 should probably be closed too
