### ISSUE TITLE
QGIS crash when adding labels

### ISSUE THREAD

**Issue by svaccari** [qgis/QGIS#40000]
## User Feedback

Added labels to an existing layer.
Some labels have a "newline" character.
Crash is reproducible.

## Report Details

**Crash ID**: [fac08c4d641b5df30e1800c11464ff2011bcfb9a](https://github.com/qgis/QGIS/search?q=fac08c4d641b5df30e1800c11464ff2011bcfb9a&type=Issues)

**Stack Trace**
<pre>
QFontMetrics::horizontalAdvance :
QgsFontMarkerSymbolLayer::characterToRender :
QgsFontMarkerSymbolLayer::bounds :
QgsMarkerSymbol::bounds :
QgsVectorLayerLabelProvider::getPointObstacleGeometry :
QgsVectorLayerJoinInfo::setUsingMemoryCache :
QgsVectorLayerJoinInfo::setUsingMemoryCache :
QgsMapRendererParallelJob::renderLayerStatic :
QgsArchive::zip :
QgsImageOperation::overlayColor :
QgsImageOperation::flipImage :
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.16.0-Hannover
QGIS code revision: 43b64b13f3
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

**Comment by gioman** [comment]
> Added labels to an existing layer.
> Some labels have a "newline" character.
> Crash is reproducible.

@svaccari try with a new QGIS profile, if problem persist attach sample project+data.

**Comment by svaccari** [comment]
@gioman a new profile didn't help. Crash occurs also on Mac.
I created a new project importing the same layer from scratch and it didn't crash.
At the moment I cannot upload the original project with data (both for size and privacy reasons).

**Comment by gioman** [comment]
> I created a new project importing the same layer from scratch and it didn't crash.
> At the moment I cannot upload the original project with data (both for size and privacy reasons).

@svaccari reopen if /when you find a way to replicate it in a consistent manner.
