### ISSUE TITLE
Running (connection) Task makes it impossible to Quit QGIS

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS#40001]
I'm playing with Oracle, sometimes running the Oslandia Oracle db in Docker.
If the db is NOT started, and I try to open the connection node in Browser, I get asked for the credentials (which are fine, but there is just no listener running...). So if I cancel that, there is still a task being started 'Scanning tables for...' (see screenshot. 

But if I try to quit QGIS then, I'm presented the 'do you want o try canceling...' but whatever I click there, yes or no,  I'm not able to quit QGIS (except by a kill on commandline...)

I'm not sure if this is related to the Oracle Provider not (yet) implementing the new db api. 
I checked with the Postgres provider, and there (after stopping my db) I get an immidiate response, and there is no 'Task' hanging around.

Should I add an Oracle tag? 
I have seen another issue or mail (or in a chat) about somebody unable to quit QGIS because a Task was running, but I could not find it...

![Screenshot-20201112145454-1109x636](https://user-images.githubusercontent.com/731673/98955960-cd074c00-24ff-11eb-8eda-8f2b91a08e31.png)

QGIS version | 3.17.0-Master | QGIS code revision | 5375508f72
-- | -- | -- | --
Compiled against Qt | 5.15.1 | Running against Qt | 5.15.1
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.33.0 | Running against SQLite | 3.33.0
Compiled against PDAL | 2.2.0 | Running against PDAL | 2.2.0 (git-version: Release)
PostgreSQL Client Version | 13.0 (Debian 13.0-4) | SpatiaLite Version | 5.0.0
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.5
Compiled against PROJ | 7.2.0 | Running against PROJ | Rel. 7.2.0, November 1st, 2020
OS Version | Debian GNU/Linux bullseye/sid | This copy of QGIS writes debugging output.
Active python plugins | MetaSearch; processing; db_manager

**Comment by gioman** [comment]
> Should I add an Oracle tag?

@rduivenvoorde I don't think so. It is a nagging issue affecting also network folders for example.

**Comment by gioman** [comment]
By the way... it also happens with certain Processing processes... the process is in the QGIS task bar, is unkillable and the only option it is to xkill QGIS.

**Comment by roya0045** [comment]
The process can only be cancelled if a feedback cancel check is reached. This is why it can be finnicky. Either more check would need to be added or a more 'violent' way to stop the thread should be implemented if possible.

**Comment by uclaros** [comment]
Not being able to cancel is one issue, but a task stuck at 'Scanning tables for...' while no listener exists is another! The later could be related to #35855

**Comment by m-kuhn** [comment]
> The process can only be cancelled if a feedback cancel check is reached.

There are 2 possibilities:

 1. Implement the feedback check in oracle and every other potentially blocking place
 2. Add a "task has not responded in x seconds, kill it?" like operating systems do for processes

I think the two are not mutually exclusive

**Comment by troopa81** [comment]
I have a fix for this one, I just have to fix few other details and propose a PR soon
