### ISSUE TITLE
Crashed Unexpectedly

### ISSUE THREAD

**Issue by bedo2405** [qgis/QGIS#40015]
Crash ID: 65355f270eeb2e87ce8d00850d759dfc996fccbc

Stack Trace

QMimeType::staticMetaObject :
QgsVectorLayer::isModified qgsvectorlayer.cpp:3624
QgsLayerTreeModel::data qgslayertreemodel.cpp:244
QModelIndex::data :
QStyledItemDelegate::initStyleOption :
QStyledItemDelegate::sizeHint :
QTreeViewPrivate::widthHintForIndex :
QTreeView::sizeHintForColumn :
QHeaderView::resizeSections :
QHeaderView::visualIndexAt :
QTreeView::indexRowSizeHint :
QTreeViewPrivate::itemHeight :
QTreeView::dataChanged :
QMetaObject::activate :
QAbstractItemModel::dataChanged :
QgsLayerTreeModel::layerNeedsUpdate qgslayertreemodel.cpp:853
QMetaObject::activate :
QMetaCallEvent::placeMetaCall :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1637
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.16.0-Hannover
QGIS code revision: 43b64b13f3
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
@bedo2405 too few infos, the **requested** ones are:



**Describe the bug**


**How to Reproduce**



1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error -->

**QGIS and OS versions**



**Additional context**

**Comment by gioman** [comment]
Closing for lack of feedback.
