### ISSUE TITLE
crash on close discarding the project

### ISSUE THREAD

**Issue by grguido** [qgis/QGIS#40028]
## User Feedback

When I close and discard project

## Report Details

**Crash ID**: [56f27d44bbafb5194f016810bfadc15d1d840442](https://github.com/qgis/QGIS/search?q=56f27d44bbafb5194f016810bfadc15d1d840442&type=Issues)

**Stack Trace**
<pre>
QgisApp::projectTemporalRangeChanged qgisapp.cpp:11468
QMetaObject::activate :
QgsProject::clear qgsproject.cpp:817
QgisApp::closeProject qgisapp.cpp:13386
QgisApp::fileNew qgisapp.cpp:6451
QgisApp::fileClose qgisapp.cpp:6424
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1637
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.16.0-Hannover
QGIS code revision: 43b64b13f3
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
@grguido plesae try with a new QGIS profile.

**Comment by nicogodet** [comment]
Fixed by https://github.com/qgis/QGIS/pull/39789

**Comment by roya0045** [comment]
@gioman can close?
