### ISSUE TITLE
The docker container is not working

### ISSUE THREAD

**Issue by sebastianoscarlopez** [qgis/QGIS#40024]
The docker container is not working. It happens with final-3_14_14 and latest

The steps to reproduce
docker pull qgis/qgis:final-3_14_14

docker run -it qgis/qgis:final-3_14_14

It stuck with this text
INFO success: Xvfb entered RUNNING state, process has stayed up for > than 1 seconds

**Comment by gioman** [comment]
@sebastianoscarlopez wrong repository where to file the ticket?
