### ISSUE TITLE
Cannot change "data source" for a layer addeded with the delimited text provider

### ISSUE THREAD

**Issue by Forna73** [qgis/QGIS#40027]
Hi!

I'm in Qgis 3.10.8 on Windows 10

I have a .CSV layer of points and I made a backup copy  of the file in a new folder in my system. When I opened Qgis and tried to change the data source for the layer pointing the new file position Qgis seems to work without problems, but the Layer isn't drawn on the map. Checking the table I discovered the data have been  corrupted.

I tried several other .CSV files with same problem. No problems with .SHP files.

You can reply this by simply creating a .CSV file with points and coord with some kind of data. Make a copy and save in another position on your system, then in Qgis try to change the source orgin for the layer.
![a](https://user-images.githubusercontent.com/12034365/99078001-f1c1f900-25bd-11eb-8d1b-1c0b12d52e08.jpg)
![b](https://user-images.githubusercontent.com/12034365/99078012-f5ee1680-25bd-11eb-9670-54ea77be24dc.jpg)

**Comment by gioman** [comment]
@Forna73 duplicate of https://github.com/qgis/QGIS/issues/35144 ?

**Comment by roya0045** [comment]
Maybe related to encoding handling, but I'm not sure.

**Comment by Forna73** [comment]
Actually I can't edit a .csv file as described in that post... I can't
enable the edit mode for them.

Il ven 13 nov 2020, 18:41 Alex <notifications@github.com> ha scritto:

**Comment by gioman** [comment]
> You can reply this by simply creating a .CSV file with points and coord with some kind of data. Make a copy and save in another position on your system, then in Qgis try to change the source orgin for the layer.

@Forna73 sorry, it is unclear to me how to replicate. Correct the below steps if I got them wrong, please:

1) add to QGIS a CSV (as a point layer with the "delimited text" provider? as geometry less table adding directly to the project?)
2) make copy of this CSV (with QGIS? with the operating system file explorer?)
3) edit the original CSV in QGIS?

please clarify.

**Comment by Forna73** [comment]
Hi!
Sorry for the delay....


   1. let's create a .csv file and name it 1.csv (I use LibreOffice) with
   some data (coords for position and so on) and store where you wish.
   2. In Qgis create a layer with the .csv file
   3. Now let's create a new 2.csv file or make a simple copy of the first
   one an save it in another folder
   4. In Qgis right click on the csv layer previously created and "change
   data source" pointing to the new 2.csv

That's all... Qgis simply don't show the layer and data are corrupted as
per the image I attached.

Il giorno sab 14 nov 2020 alle ore 12:12 Giovanni Manghi <
notifications@github.com> ha scritto:

**Comment by Pedro-Murteira** [comment]
Still valid on QGIS 3.22.4 and 3.24.0.

**Comment by alexbruy** [comment]
Seems fixed in the latest master (f344919474).
