### ISSUE TITLE
Unexpected Enum Handling Postgres QGIS

### ISSUE THREAD

**Issue by ian330** [qgis/QGIS#40032]
- [done] Search through existing issue reports and gis.stackexchange.com to check whether the issue already exists
- [done ] Test with a [clean new user profile]
- [done] Create a light and self-contained sample dataset and project file which demonstrates the issue

CREATE TYPE my_enum AS ENUM ('foo', 'bar');

CREATE TABLE public.test_data (
	id integer DEFAULT 1,
	enum_test my_enum NOT NULL DEFAULT 'foo'::my_enum,
	geom geometry(MULTIPOLYGON, 4326)
)

**Describe the bug**

expected behavior: a enum type field will have a user selectable drop down of enum values when editing an attribute table. This works perfectly in most cases. However, when a default value is specified for an enum field from a Postgres table, QGIS  does not provide a drop down of values for editing the attribute table.

**How to Reproduce**

create a postgres table with an enum column that has a default value:

CREATE TYPE my_enum AS ENUM ('foo', 'bar');

CREATE TABLE public.test_data (
	id integer DEFAULT 1,
	enum_test my_enum DEFAULT 'foo',
	geom geometry(MULTIPOLYGON, 4326)
)

Connect to postgres and load public.test_data as a new layer in QGIS. Insert a new feature and commit the insert. As expected the default value ('foo' in this case) appears in the attribute table for the newly created feature. However, upon further editing of the table, there is no selectable dropdown provided for cells in the enum field "enum_test". Looking at the layer properties, QGIS has interpreted the enum column as type:QString and type name:my_enum which seems correct.

If table is dropped and recreated without a default value for enum_test, QGIS handles the enum field as expected providing a drop down of values for editing after new rows have been inserted. 

**QGIS and OS versions**

QGIS version
3.10.9-A Coru񡊑GIS code branch
Release 3.10
Compiled against Qt
5.14.2
Running against Qt
5.14.2
Compiled against GDAL/OGR
3.1.3
Running against GDAL/OGR
3.1.3
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.33.0
Running against SQLite
3.33.0
PostgreSQL Client Version
12.4 (Debian 12.4-1+build2)
SpatiaLite Version
5.0.0
QWT Version
6.1.4
QScintilla2 Version
2.11.2
Compiled against PROJ
7.1.0
Running against PROJ
Rel. 7.1.0, August 1st, 2020
OS Version
Debian GNU/Linux rodete
Active python plugins
MetaSearch; 
db_manager; 
processing

**Additional context**

Currently, DBA must choose between providing a default value for their users or a selectable list of values if their Postgres table has an enum field.

**Comment by elpaso** [comment]
@ian330 can you please check if this issue is still valid for QGIS master builds?

**Comment by stev-0** [comment]
I think this might be related to [this](https://github.com/qgis/QGIS/blob/869e148f6946579ec053e4cd72ffe4746fc97e90/src/gui/editorwidgets/core/qgseditorwidgetautoconf.cpp#L100). See a bit more context in #39106. A workaround is to manually set the Attribute Form widget to Enumeration - the reason it isn't done automatically is because of the default clause.
