### ISSUE TITLE
QGIS 3.16 : snapping on vertices doesn't work

### ISSUE THREAD

**Issue by multicompte4** [qgis/QGIS#40031]
On 3.16 the snapping doesn't work anymore on vertices (it works fine on 3.10), while the preferences>options>numerisation>snapping>"activate default snapping" button is checked and the default snapping mode is on "vertices"
(tolerance is also correctly set)

screens shots :
snapping on lines OK in 3.10 : https://zupimages.net/viewer.php?id=20/46/u0cv.png
snapping on lines OK in 3.16 : https://zupimages.net/viewer.php?id=20/46/7o8f.png
snapping on vertices KO in 3.16 : https://zupimages.net/viewer.php?id=20/46/0v5w.png
snapping on vertices OK in 3.10 : https://zupimages.net/viewer.php?id=20/46/g1ec.png
snapping options : https://zupimages.net/viewer.php?id=20/46/2nx7.png

Version de QGIS : 3.16.0-Hannover
Révision du code : 43b64b13f3
Compilé avec Qt : 5.11.2
Utilisant Qt : 5.11.2
Compilé avec GDAL/OGR : 3.1.4
Utilisé avec GDAL/OGR : 3.1.4
Compilé avec GEOS : 3.8.1-CAPI-1.13.3
Utilisé avec GEOS : 3.8.1-CAPI-1.13.3
Compilé avec SQLite : 3.29.0
Fonctionne avec SQLite : 3.29.0
Version du client PostgreSQL : 11.5
Version de SpatiaLite : 4.3.0
Version de QWT : 6.1.3
Version de QScintilla2 : 2.10.8
Compilé avec PROJ : 6.3.2
Fonctionne avec PROJ : Rel. 6.3.2, May 1st, 2020
Version de l'OS : Windows 10 (10.0)
Extensions Python actives : db_manager ; MetaSearch ; processing

Let me know if it still miss some informations

**Comment by gioman** [comment]
> Let me know if it still miss some informations

@multicompte4 I cannot replicate or I'm understanding how to replicate. I tested on 3.16 on Windows.
Attaching a  small sample project+data would be very useful, specifying what layer you are editing and what layer your are snapping to.

**Comment by multicompte4** [comment]
Here is a simple data set where no snapping works (snapping line on points or snapping line on line) :
[test.zip](https://github.com/qgis/QGIS/files/5545107/test.zip)
Now that I tested with the 2 versions on several data sets, I figured it must come from my data because now no snapping works at all, in 3.16 nor 3.10 .....
Is there something corrupting my datas ?
(Sometimes QGIS is very long to undestand a new action from me, like entering or quiting the edition mode, or simply leaving the application : it writes "ne répond pas" (no responding) and offers me to force quitting, wich I do sometimes when I just want to leave the app. Maybe it comes from there ?)

**Comment by gioman** [comment]
> Maybe it comes from there ?)

@multicompte4 your project has the snapping **not** active, if you enable it, then works as expected. Please check.

**Comment by gioman** [comment]
Closing for lack of feedback.
