### ISSUE TITLE
No tooltips on QGIS 3.16.0 with Ubuntu 20.04

### ISSUE THREAD

**Issue by rjbaniel** [qgis/QGIS#40049]
Hello - I've just installed QGIS 3.16.0 on Ubuntu 20.04, using the instructions for Ubuntu at https://qgis.org/en/site/forusers/alldownloads.html#debian-ubuntu

When I open the application, I can't get tooltips to show up when hovering over any toolbar items, etc.

If I open the application by running 'qgis' from the command line, I get this error message:
`Failed to load module "appmenu-gtk-module"`

I did already have the packages appmenu-gtk2-module and appmenu-gtk-module installed. After I installed appmenu-gtk3-module as well and then ran qgis from the command line again, the error message didn't appear, but I still didn't have tool tips.

Here are the details on my QGIS install:

QGIS version | 3.16.0-Hannover | QGIS code revision | 43b64b13f3
-- | -- | -- | --
Compiled against Qt | 5.12.8 | Running against Qt | 5.12.8
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.4 (Ubuntu 12.4-0ubuntu0.20.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Ubuntu 20.04.1 LTS
Active python plugins | processing; db_manager; MetaSearch

Thank you for any help you can provide, and for all of your work on this amazing project!

**Comment by gioman** [comment]
@rjbaniel on Kubuntu 20.04 they are ok.

**Comment by gioman** [comment]
Will also try Ubuntu.
