### ISSUE TITLE
Wrong values using Raster Calculator

### ISSUE THREAD

**Issue by Angelablanco7910** [qgis/QGIS#40056]
**Describe the bug**
I need to calculate the NDVI of a four-band imagery using Raster Calculator. The output file is distorted. The output is divided in two areas. On area is black and the other area is like a reduced image of the original.

**How to Reproduce**

1. Go to Raster 
2. Click on Raster Calculator
3. Type the formula: ("Valencia_crops@4" - "Valencia_crops@3")/ ("Valencia_crops@4" + "Valencia_crops@3")
4. Give Output layer: 'NDVI'
5. Click on "Selected Layer Extend"

**QGIS and OS versions**

QGIS 3.10.11. Menu: Raster / Raster Calculator
Windows 10

**Additional context**

**Comment by gioman** [comment]
@Angelablanco7910 do you have GPU acceleration enabled in QGIS?

**Comment by Angelablanco7910** [comment]
Thank you very much Gioman.  I disable the Option: "Enable OpenCL accelareration" in Settings / Options /Acceleration. The Raster Calculator output works as expected.
