### ISSUE TITLE
Expression widget does not list fields when Selected features only is checked

### ISSUE THREAD

**Issue by uclaros** [qgis/QGIS#40055]
**Describe the bug**

In processing algorithms that use a `QgsProcessingParameterExpression`, the widget has a combobox populated with the available fields. If the *Selected features only* checkbox is checked, then the expression widget no longer shows the fields in the combobox.

**How to Reproduce**
- Load a vector layer with some features
- Run an algorithm that uses a `QgsProcessingParameterExpression`, for example *Order by expression*
- Click on the expression widget combobox button: the layer's fields are listed
- Go to the map canvas and select some features
- Back to the algorithm dialog, check *Selected features only*
- Click on the expression widget combobox button: the layer's fields are **not** listed

**QGIS and OS versions**
69faea8 on Debian testing

**Comment by tudorbarascu** [comment]
Also noticed this!

**Comment by uclaros** [comment]
The fields are also missing from the *Fields and Values* branch in the expression builder dialog. Instead of the fields there is `NULL`.
@tudorbarascu how did you test with Buffer? It does not have an expression combobox!

**Comment by tudorbarascu** [comment]
> The fields are also missing from the _Fields and Values_ branch in the expression builder dialog. Instead of the fields there is `NULL`.
> @tudorbarascu how did you test with Buffer? It does not have an expression combobox!

@uclaros Mine does? :)
![image](https://user-images.githubusercontent.com/3179646/124549319-ace21f80-de37-11eb-9784-c4f181fab7c0.png)

Just noticed this wasn't backported? It still doesn't work on 3.16.8

**Comment by uclaros** [comment]
But there's no *Fields* combo box in your screenshot!

**Comment by tudorbarascu** [comment]
it's also broken on master actually. In the screenshot .. I'm showing the data driven expression for distance.. and there's the expression there.. where the fields are not available in the expression box..

**Comment by gioman** [comment]
> it's also broken on master actually.

@tudorbarascu should this be reopened?

**Comment by uclaros** [comment]
It works ok for the fields widget like in *Order by expression* algorithm, it is still broken for the data defined expression builder.
