### ISSUE TITLE
Ubuntu LTR repository returning wrong version

### ISSUE THREAD

**Issue by CoryAlbrecht** [qgis/QGIS#40054]
According to the [download page](https://qgis.org/en/site/forusers/alldownloads.html#linux), If you use the repo https://qgis.org/ubuntu-ltr you should be getting  3.10LTR when you go to install QGIS on Ubuntu. However, one gets 3.16 instead..

I mentioned this on the QGIS Developers group when the website went down 6 days ago, but nobody acknowledged the problem.

**Comment by jef-n** [comment]
Because it's not reproducable.

```
$ grep ubuntu-ltr /etc/apt/sources.list
deb	https://qgis.org/ubuntu-ltr			bionic		main
deb	https://qgis.org/ubuntu-ltr			eoan		main
deb	https://qgis.org/ubuntu-ltr			focal		main
$ apt-cache policy qgis
qgis:
  Installed: (none)
  Candidate: 1:3.10.11+32focal 500
  Version table:
     1:3.10.11+32focal 500
        500 https://qgis.org/ubuntu-ltr focal/main amd64 Packages
     1:3.10.11+31eoan 500
        500 https://qgis.org/ubuntu-ltr eoan/main amd64 Packages
     1:3.10.11+28bionic 500
        500 https://qgis.org/ubuntu-ltr bionic/main amd64 Packages
```

**Comment by gioman** [comment]
I also can't confirm, just downloaded to 3.10 from 3.16 on my ubuntu 20.04 machine.
