### ISSUE TITLE
Cannot Clip Raster with Polygon with SAGA

### ISSUE THREAD

**Issue by SebastianKasan** [qgis/QGIS#40070]
Working in A Coruna, I cannot succed clipping a raster with a boundary shp-file with the Saga Clipping Tool for Raster files.

It seems like it only works with the first layer of the .tif orthomosaic. In Saga UI it is possible to perform the clipping on all layers of a raster and select individual bands. 

That option is missing and this only the first layer gets clipped..

**Comment by gioman** [comment]
> Working in A Coruna, I cannot succed clipping a raster with a boundary shp-file with the Saga Clipping Tool for Raster files.

@SebastianKasan please attach the data you are using as input. Thanks.

**Comment by SebastianKasan** [comment]
I will create a small sample of the data....
