### ISSUE TITLE
Labeling issue

### ISSUE THREAD

**Issue by aaronmcblt** [qgis/QGIS#40075]
New user, I need to label points with UTM coordinates. I know it’s simple but I’ve been at this all day. Gah!

Any help would be appreciated

**Comment by SrNetoChan** [comment]
As stated when you first created this issue, Github Issue tracker is not the place to ask questions about how to use QGIS.

Please try one of these channels instead:

http://osgeo-org.1560.x6.nabble.com/QGIS-User-f4125267.html

https://gis.stackexchange.com/
