### ISSUE TITLE
QGIS 3.16 crashes when using Cell statistics tool "Ignore NoData"

### ISSUE THREAD

**Issue by Shefir13** [qgis/QGIS#40092]
Hi,

I’m trying to use the new tool in QGIS 3.16 “Cell statistics”. However, whenever I choose to tick the box “ignore NoData values” and run the tool, QGIS crashes. I have tried it with different multiband rasters in different formats (NC, tiff, GeoTIFF) but whenever I choose to ignore NoData values the program crashes. I have tried to run the tool on a clean working space and with my usual project, but nothing seems to work.

To reproduce this bug:

- Have a multiband raster (my current projection is in EPSG 4326: WGS 84)
- Open Cell statistics
- Input and reference layer the same raster
- Statistics: Mean
- Check the box “Ignore NoData values”
- Run the tool

→ QGIS Crashes

QGIS version

QGIS version | 3.16.0-Hannover | QGIS code revision | 43b64b13f3
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | LocatePoints;    mmqgis;    NNJoin;    PointConnector;    quick_map_services;    rastertimeseriesmanager;    refFunctions;    db_manager;    MetaSearch;    processing

**Comment by Shefir13** [comment]
This is the latest crash report:

**Crash ID**: [4a80e847411ced91ce650b7f92e8ae659b890227](https://github.com/qgis/QGIS/search?q=4a80e847411ced91ce650b7f92e8ae659b890227&type=Issues)


**Stack Trace**
<pre>
QgsRasterAnalysisUtils::medianFromCellValues qgsrasteranalysisutils.cpp:335
QgsCellStatisticsAlgorithm::processAlgorithm qgsalgorithmcellstatistics.cpp:290
QgsProcessingAlgorithm::runPrepared qgsprocessingalgorithm.cpp:532
QgsProcessingAlgRunnerTask::run qgsprocessingalgrunnertask.cpp:66
sipQgsProcessingAlgRunnerTask::run sip_corepart4.cpp:9325
QgsTask::start qgstaskmanager.cpp:83
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>


**QGIS Info**
QGIS Version: 3.16.0-Hannover
QGIS code revision: 43b64b13f3
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by root676** [comment]
Can you provide your datasets for testing?

**Comment by root676** [comment]
From your bug report it seems like you are using a single multiband-raster as input. Cell Statistics needs an input of multiple singleband-rasters to work properly. Have you tried splitting the multiband raster into singleband rasters?

**Comment by Shefir13** [comment]
Hi,

As it is data from Marine Copernicus, I cannot directly share it (it is not mine to share). However, you can download the dataset from Marine Copernicus here: https://resources.marine.copernicus.eu/?option=com_csw&view=details&product_id=BALTICSEA_REANALYSIS_PHY_003_011

I used data for CHL daily mean values between 01.01.2013-31.12.2013, and the geographical coverage: 59-61 N, 18-22 E.
Each band consists of daily means. 

I have tried with shorter data-periods, as well as savingthe NetCDF file as a tiff file to see if the data format would resolve the issue. Nothing works as QGIS 3.16 crashes whenever I choose to Ignore NoData values.

Cheers!

**Comment by Shefir13** [comment]
Hi,

I replied before I saw your second reply.

The cell statistics tool for QGIS 3.16 has worked with multiband rasters when I choose not to check the box "Ignore NoData values". I'll test to see if splitting the data into 365 different bands will resolve the issue.

**Comment by Shefir13** [comment]
Sadly, splitting the raster into separate bands did not resolve the issue. This happened when I split the raster layers into separate files and bands:

## Report Details

**Crash ID**: [4a80e847411ced91ce650b7f92e8ae659b890227](https://github.com/qgis/QGIS/search?q=4a80e847411ced91ce650b7f92e8ae659b890227&type=Issues)


**Stack Trace**
<pre>
QgsRasterAnalysisUtils::medianFromCellValues qgsrasteranalysisutils.cpp:335
QgsCellStatisticsAlgorithm::processAlgorithm qgsalgorithmcellstatistics.cpp:290
QgsProcessingAlgorithm::runPrepared qgsprocessingalgorithm.cpp:532
QgsProcessingAlgRunnerTask::run qgsprocessingalgrunnertask.cpp:66
sipQgsProcessingAlgRunnerTask::run sip_corepart4.cpp:9325
QgsTask::start qgstaskmanager.cpp:83
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>


**QGIS Info**
QGIS Version: 3.16.0-Hannover
QGIS code revision: 43b64b13f3
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by root676** [comment]
Thanks for reporting this - It seems the error comes from stacks that consist purely of NoData cells which are currently not handled by the algorithm (but should be). I checked it with two rasters containing only NoData values at certain cell locations. Bugfix incoming. :wink:
