### ISSUE TITLE
Shapefile layers: problems exporting to PDF when using filenames containing non-ASCII characrters

### ISSUE THREAD

**Issue by AntonioPestana** [qgis/QGIS#40106]
My project's geographic data is stored in two sets of shapefile format files, one set for for polygons and the other for lines. These two sets of "shapefiles" were generated using the same piece of software and both of them represent the same geographic data (all using EPSG:4326 coordinates). The only distinction between sets is the filename: for one set the characters used for the filenames are pure ASCII, for the other one they aren't.

I've created a QGIS map using the second set of shapefiles (the one with non-ASCII filenames). I used a very simple layout for exporting my map to one layered geopdf. I noticed that if I use the default export options the process aborts throwing the "Could not create print device" error. However if I uncheck the "Include Attributes" checkbox of the export options for the "Todas as Parcelas Áreas" layer, the export is made and the resulting pdf file looks fine.... I got no problems exporting to pdf using the same layout and the first set of shapefiles.

Using QGIS 3.16.0 code revision 43b64b13f3 and Windows 10.

[Link to my data.](https://drive.google.com/drive/folders/1OhWK1PU8HKyn_nhJz9lpIpMSaw5Sf7i7?usp=sharing)

**Comment by gioman** [comment]
> I've created a QGIS map using the second set of shapefiles (the one with non-ASCII filenames). I used a very simple layout for exporting my map to one layered geopdf. I noticed that if I use the default export options the process aborts throwing the "Could not create print device" error. However if I uncheck the "Include Attributes" checkbox of the export options for the "Todas as Parcelas Áreas" layer, the export is made and the resulting pdf file looks fine.... I got no problems exporting to pdf using the same layout and the first set of shapefiles.

@AntonioPestana I have just tested your data on my testing Windows10/QGIS 3.16 installation: no problem/error exporting to GeoPDF. 

Suggested to detail the detailed list of steps to replicate the issue, or even better attach a sample project.

**Comment by AntonioPestana** [comment]
@gioman Please try this [link](https://drive.google.com/drive/folders/115_b3FDuiUATJoQHE-0MyL37ZoETBTYJ?usp=sharing)

**Comment by gioman** [comment]
> @gioman Please try this [link](https://drive.google.com/drive/folders/115_b3FDuiUATJoQHE-0MyL37ZoETBTYJ?usp=sharing)

@AntonioPestana confirmed, thanks.

**Comment by agiudiceandrea** [comment]
I can confirm also on Windows 7: the issue is triggered by the file name (actually by the layer id which is created using the file name), not by the layer name.
