### ISSUE TITLE
Options: Changed from layout to digitalization

### ISSUE THREAD

**Issue by PeddaSteam** [qgis/QGIS#40119]
## User Feedback

I'm in the layout options and changed to digitalization. Got the crash everytime at this stage.

## Report Details

**Crash ID**: [9360500b93d60fbd8a026581b6cb6fa1972a7733](https://github.com/qgis/QGIS/search?q=9360500b93d60fbd8a026581b6cb6fa1972a7733&type=Issues)

**Stack Trace**
<pre>
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QMainWindow::trUtf8 :
QHeaderView::logicalIndexAt :
QWidget::setStyleSheet :
QgsCollapsibleGroupBoxBasic::updateStyle qgscollapsiblegroupbox.cpp:386
QgsCollapsibleGroupBoxBasic::showEvent qgscollapsiblegroupbox.cpp:115
QWidget::event :
QGroupBox::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QWidgetPrivate::show_helper :
QWidget::setVisible :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidget::setVisible :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidget::setVisible :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidget::setVisible :
QStackedLayout::setCurrentIndex :
QMetaObject::activate :
QListWidgetItem::`default constructor closure' :
QMetaObject::activate :
QItemSelectionModel::setCurrentIndex :
QAbstractItemView::mousePressEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
QgisApp::showOptionsDialog qgisapp.cpp:12344
QtPrivate::QFunctorSlotObject<<lambda_4dfd86d576e92f3f8c7f01985340f751>,0,QtPrivate::List<>,void>::impl qobjectdefs_impl.h:421
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1637
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.16.0-Hannover
QGIS code revision: 43b64b13f3
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

**Comment by gioman** [comment]
@PeddaSteam please try with a new QGIS profile.

**Comment by roya0045** [comment]
Seems to be the style bug that has ben fixed.

**Comment by nyalldawson** [comment]
Yep this is fixed
