### ISSUE TITLE
QgsVectorLayer.addFeature() fails with auxiliary table join, but QgsVectorDataProvider.addFeatures() succeeds 

### ISSUE THREAD

**Issue by jlayt** [qgis/QGIS#40126]
**Describe the bug**
We have an in-house python plugin that uses buffered editing to copy features from one layer to another. This normally works fine, but fails when the Move Label feature has created a join to the auxiliary table. It succeeds if we directly update the data provider instead.

**How to Reproduce**

Create shapefiles fromLayer and toLayer, add a labelled feature to toLayer and use Move Label to join to the auxiliary table, add features to fromLayer.

Simplified code snippet that fails only after join has been made.

```python
if toLayer.startEditing():
    for feature in fromLayer.getFeatures():
        ok = toLayer.addFeature(feature)
        if not ok:
            break
    if ok:
        ok = toLayer.commitChanges()
    if not ok:
        toLayer.rollBack()
```

Using `ok = toLayer.addFeatures([feature])` also fails, but if I use `ok = toLayer.dataProvider().addFeatures([feature])` inside the loop instead the code succeeds.

**QGIS and OS versions**

Have tried both 3.14.15 and 3.16.0

QGIS version | 3.14.15-Pi | QGIS code revision | d5114d2cfa
-- | -- | -- | --
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.28.0 | Running against SQLite | 3.28.0
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS 10.15
Active python plugins | numericalDigitize; VectorBender; LPGetLibraryInfo; AnotherDXF2Shape; plaingeometryeditor; LPMaps; ArkSpatial; volume_calculation_tool; MemoryLayerSaver; LPFigureBuilder; plugin_reloader; processing; db_manager; MetaSearch

QGIS version | 3.16.0-Hannover | QGIS code revision | 4af1cbfb97
-- | -- | -- | --
Compiled against Qt | 5.14.2 | Running against Qt | 5.14.2
Compiled against GDAL/OGR | 3.1.2 | Running against GDAL/OGR | 3.1.2
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.4
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | macOS 10.15
Active python plugins | numericalDigitize; VectorBender; LPGetLibraryInfo; AnotherDXF2Shape; plaingeometryeditor; LPMaps; volume_calculation_tool; MemoryLayerSaver; LPFigureBuilder; plugin_reloader; processing; db_manager; MetaSearch; ArkSpatial

**Additional context**

None.

**Comment by gioman** [comment]
@jlayt have you asked also in the developers mailing list?
