### ISSUE TITLE
Duplicated effect types and properties when styling layers using draw effects

### ISSUE THREAD

**Issue by NyakudyaA** [qgis/QGIS#40124]
# Problem

* Navigate to layer styling
* Select Draw effects under layer rendering
![default](https://user-images.githubusercontent.com/2510900/99392632-aae94180-28e4-11eb-9281-e01a91e91fc6.png)

* Change the effect type from the `Source` to something else i.e Drop Shadow. Notice that drop shadow is duplicated in the effect properties.
![drop-shadow](https://user-images.githubusercontent.com/2510900/99392784-f3a0fa80-28e4-11eb-851b-9c6d1ca74e4c.png)

I could not see any difference between the two `Drop Shadow` effects that are available.

This occurs for only the following effect types `Drop Shadow,Inner Glow,Inner Shadow,Outer Glow`

*PS* I am not sure if this is a bug or by design so feel free to close if it's by design

Tested on QGIS 3.14.1 and QGIS 3.16.0

**Comment by gioman** [comment]
> QGIS 3.16.0

@NyakudyaA cannot replicate/see it on 3.16 on Ubuntu 20.04

**Comment by NyakudyaA** [comment]
> > QGIS 3.16.0
> 
> @NyakudyaA cannot replicate/see it on 3.16 on Ubuntu 20.04

I tried with no-plugins and still could replicate even on master. I will try with a clean profile and revert

**Comment by NyakudyaA** [comment]
This might be something on my machine only. Tested on windows. Will close and reopen if I find the source of the error
