### ISSUE TITLE
QGIS-Settings: Check checkbox "Evaluate default value" does not store the "enabled" setting

### ISSUE THREAD

**Issue by koenigherford** [qgis/QGIS#40129]
In QGIS-settings you can check Datasource-"Enable default value"-checkbox.
**After confirming** your choice and **reopening** the settings you see that the checkbox is still disabled althrough it was enabled before.
![grafik](https://user-images.githubusercontent.com/28433436/99405765-6615d880-28ed-11eb-8ad6-af26759127bb.png)

(This may produce issues when establishing new parent-/child-relations without saving the parent-feature first.)

**How to Reproduce**
see above

**QGIS and OS versions**
QGIS 3.16.0 -fresh installation - no project loaded

**Comment by gioman** [comment]
It is also try on 3.10.11 on Ubuntu 20.04

**Comment by signedav** [comment]
This checkbox is defined in the ui-file here https://github.com/qgis/QGIS/blob/master/src/ui/qgsoptionsbase.ui#L2091 but nowhere else used. So it does nothing.

Seems to be introduced here: https://github.com/qgis/QGIS/commit/c6565da36fcc1fef149801e7ec490ad5a99381f7
Should this setting exist here at all? Or did we lost something on a redesign? @DelazJ do you remember?

We do have the same option in the project properties. Maybe it should be only there...

**Comment by 3nids** [comment]
It was apparently added by me.... 
https://github.com/qgis/QGIS/commit/a1369955de3d4daca445daa6b066e646369326e3#diff-e0fe055875ca8f5233723ad0e101b958203b823b0fc283be81d6c73c8f78987dR1813

It really looks like a bad rebase.
It feels safe to remove this option.
The actual setting is in the project properties dialog.

**Comment by signedav** [comment]
@koenigherford The setting can be made in the Project Properties instead.
![image](https://user-images.githubusercontent.com/28384354/109652301-e50ee400-7b5f-11eb-99a7-e60858358642.png)

**Comment by 3nids** [comment]
unrelated test failure
