### ISSUE TITLE
[Master] No transform is available between EPSG:3035 and EPSG:25832

### ISSUE THREAD

**Issue by tobwen** [qgis/QGIS#40134]
**Describe the bug**
I'm getting this message:
```
"No transform is available between ETRS89-extended / LAEA Europe and EPSG:25832 - ETRS89 / UTM zone 32N."
"No coordinate operations are available between these two reference systems"
```

**How to Reproduce**
1. Set project CRS to `EPSG:25832`
2. Load a raster, which is in CRS `EPSG:3035`
3. run _GDAL_'s  `rgb2pct` on it (`python3 -m rgb2pct -n 6 -of GTiff input.tif output.tif`)
4. rightclick on the newly created layer
5. click `Layer CRS` 
6. click`Set Project CRS from Layer`
7. QGIS statusbar says `Unknown CRS`

**QGIS and OS versions**
software | version / build / revision
---------|---------------------------
QGIS version | 3.17.0-Master
QGIS code revision | 6cbbf5ebd1
Compiled against Qt | 5.11.2
Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.3.0dev
Running against GDAL/OGR | 3.3.0dev
Compiled against GEOS | 3.8.1-CAPI-1.13.3
Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0
Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5
SpatiaLite Version | 4.3.0
QWT Version | 6.1.3
QScintilla2 Version | 2.10.8
Compiled against PROJ | 8.0.0
Running against PROJ | Rel. 8.0.0, March 1st, 2021

- binaries from _OSGeo4W_, 64-bit
- Microsoft Windows 10, Version 1909 (Build 18363.1198), 64-bit

**Additional information**
This seems to be a _proj_ or _GDAL_ problem. 
<details>
<summary>output of gdalnfo (on input file)</summary>

```
> gdalinfo "input.tif"
Driver: GTiff/GeoTIFF
Files: input.tif
Size is 6402, 8586
Coordinate System is:
PROJCRS["ETRS89-extended / LAEA Europe",
    BASEGEOGCRS["ETRS89",
        ENSEMBLE["European Terrestrial Reference System 1989 ensemble",
            MEMBER["European Terrestrial Reference Frame 1989"],
            MEMBER["European Terrestrial Reference Frame 1990"],
            MEMBER["European Terrestrial Reference Frame 1991"],
            MEMBER["European Terrestrial Reference Frame 1992"],
            MEMBER["European Terrestrial Reference Frame 1993"],
            MEMBER["European Terrestrial Reference Frame 1994"],
            MEMBER["European Terrestrial Reference Frame 1996"],
            MEMBER["European Terrestrial Reference Frame 1997"],
            MEMBER["European Terrestrial Reference Frame 2000"],
            MEMBER["European Terrestrial Reference Frame 2005"],
            MEMBER["European Terrestrial Reference Frame 2014"],
            ELLIPSOID["GRS 1980",6378137,298.257222101,
                LENGTHUNIT["metre",1]],
            ENSEMBLEACCURACY[0.1]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4258]],
    CONVERSION["Europe Equal Area 2001",
        METHOD["Lambert Azimuthal Equal Area",
            ID["EPSG",9820]],
        PARAMETER["Latitude of natural origin",52,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",10,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["False easting",4321000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",3210000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["northing (Y)",north,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["easting (X)",east,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["Statistical analysis."],
        AREA["Europe - European Union (EU) countries and candidates. Europe - onshore and offshore: Albania; Andorra; Austria; Belgium; Bosnia and Herzegovina; Bulgaria; Croatia; Cyprus; Czechia; Denmark; Estonia; Faroe Islands; Finland; France; Germany; Gibraltar; Greece; Hungary; Iceland; Ireland; Italy; Kosovo; Latvia; Liechtenstein; Lithuania; Luxembourg; Malta; Monaco; Montenegro; Netherlands; North Macedonia; Norway including Svalbard and Jan Mayen; Poland; Portugal including Madeira and Azores; Romania; San Marino; Serbia; Slovakia; Slovenia; Spain including Canary Islands; Sweden; Switzerland; Turkey; United Kingdom (UK) including Channel Islands and Isle of Man; Vatican City State."],
        BBOX[24.6,-35.58,84.17,44.83]],
    ID["EPSG",3035]]
Data axis to CRS axis mapping: 2,1
Origin = (4031700.000000000000000,3547700.000000000000000)
Pixel Size = (100.000000000000000,-100.000000000000000)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  COMPRESSION=PACKBITS
  INTERLEAVE=PIXEL
Corner Coordinates:
Upper Left  ( 4031700.000, 3547700.000) (  5d28'58.22"E, 54d57'11.83"N)
Lower Left  ( 4031700.000, 2689100.000) (  6d10'46.14"E, 47d14'54.01"N)
Upper Right ( 4671900.000, 3547700.000) ( 15d28'32.84"E, 54d54'53.94"N)
Lower Right ( 4671900.000, 2689100.000) ( 14d37'56.31"E, 47d13' 0.20"N)
Center      ( 4351800.000, 3118400.000) ( 10d26'25.54"E, 51d10'33.11"N)
Band 1 Block=6402x1 Type=Byte, ColorInterp=Red
  Mask Flags: PER_DATASET ALPHA
Band 2 Block=6402x1 Type=Byte, ColorInterp=Green
  Mask Flags: PER_DATASET ALPHA
Band 3 Block=6402x1 Type=Byte, ColorInterp=Blue
  Mask Flags: PER_DATASET ALPHA
Band 4 Block=6402x1 Type=Byte, ColorInterp=Alpha
```

</details>

<details>
<summary>output of gdalnfo (on output file)</summary>

```
> gdalinfo "output.tif"
Driver: GTiff/GeoTIFF
Files: output.tif
Size is 6402, 8586
Coordinate System is:
ENGCRS["ETRS89-extended / LAEA Europe",
    EDATUM[""],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]]]
Data axis to CRS axis mapping: 1,2
Origin = (4031700.000000000000000,3547700.000000000000000)
Pixel Size = (100.000000000000000,-100.000000000000000)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  ( 4031700.000, 3547700.000)
Lower Left  ( 4031700.000, 2689100.000)
Upper Right ( 4671900.000, 3547700.000)
Lower Right ( 4671900.000, 2689100.000)
Center      ( 4351800.000, 3118400.000)
Band 1 Block=6402x1 Type=Byte, ColorInterp=Palette
  Color Table (RGB with 256 entries)
...
```

</details>

**Comment by gioman** [comment]
> Load a raster, which is in CRS `EPSG:3035`

@tobwen can you link/attach a sample?

**Comment by tobwen** [comment]
Sure, I'm currently working on it. The whole dataset is under copyright, but I can extract a sample and add output from _gdalinfo_.

**Comment by tobwen** [comment]
Here's a sample: [sample_3035.zip](https://github.com/qgis/QGIS/files/5556235/sample_3035.zip)

**Comment by gioman** [comment]
> Here's a sample: [sample_3035.zip](https://github.com/qgis/QGIS/files/5556235/sample_3035.zip)

@tobwen cannot replicate on master on Windows and 3.16 on Ubuntu 20.04.

**Comment by tobwen** [comment]
Oh, seems like the sample file works. So maybe the problem is on the original file? Let me check,

**Comment by rouault** [comment]
@tobwen 

> ERROR 1: PROJ: proj_create_from_database: SQLite error on SELECT name, coordinate_system_auth_name, coordinate_system_code, geodetic_crs_auth_name, geodetic_crs_code, conversion_auth_name, conversion_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM projected_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name

This message comes from a PROJ < 7.2 binary trying to use a PROJ >= 7.2 proj.db . There's likely a mix-up of PROJ versions in your installation

**Comment by gioman** [comment]
> This message comes from a PROJ < 7.2 binary trying to use a PROJ >= 7.2 proj.db . There's likely a mix-up of PROJ versions in your installation

The reporter is on Windows so is likely to have installed QGIS master with OSGeo4W.

**Comment by rouault** [comment]
> The reporter is on Windows so is likely to have installed QGIS master with OSGeo4W.

This might be some conflict between QGIS-dev and GDAL-stable+PROJ-stable being installed. When rgb2pct.py is forked by QGIS, it probably not use QGIS-dev/GDAL-dev/PROJ-dev but GDAL-stable+PROJ-stable, but the PROJ_LIB environment variable points to proj.db of PROJ-dev . Maybe a missing installation of the gdal-dev-python package of however it is called ?

**Comment by gioman** [comment]
> This might be some conflict between QGIS-dev and GDAL-stable+PROJ-stable being installed. When rgb2pct.py is forked by QGIS, it probably not use QGIS-dev/GDAL-dev/PROJ-dev but GDAL-stable+PROJ-stable, but the PROJ_LIB environment variable points to proj.db of PROJ-dev . Maybe a missing installation of the gdal-dev-python package of however it is called ?

@jef-n any idea?

**Comment by tobwen** [comment]
_gdal-dev-env_ is installed and works. Also, as you can see on the table, the version of _GDAL_ is `3.3.0dev`, so _QGIS_ seems to make use of it.

Let me quickly run this in QGIS:
```python
import osgeo.gdal
print osgeo.gdal.__version__
```

**Comment by jef-n** [comment]
run ``qgis-dev --postinstall`` and/or ``qgis-dev-g7 --postinstall`` from the osgeo4w shell to update the .envs

**Comment by tobwen** [comment]
I've run it - without any visual feedback.

Nothing changed:
```python
import osgeo.gdal
print(osgeo.gdal.__version__)
3.1.4
```

I'll try a fresh install this evening.

**Comment by gioman** [comment]
> I'll try a fresh install this evening.

Closing for lack of further feedback.
