### ISSUE TITLE
Error on Raster tools: Convert map to raster

### ISSUE THREAD

**Issue by Jordibadia-arc** [qgis/QGIS#40132]
When I use the raster tool: convert map to raster, the result of the extraction results in a huge uniform colour square, much larger than the window that I mark, and without any of the original web base features, even if it is google or open street map... Where is the error, in my settings ? Or in the QGis program ?
Thank you for your help

Please contat to:
jordibadia.arc@☻gmail.com
+55 41 997418319
Jordi Badia

![Captura-3](https://user-images.githubusercontent.com/56209227/99433204-fd7a2c00-28eb-11eb-89f6-206056f80771.png)
![Captura-2](https://user-images.githubusercontent.com/56209227/99433221-023ee000-28ec-11eb-924c-21d4048247a4.png)

**Comment by gioman** [comment]
@Jordibadia-arc is this a question or a bug report?

If is a question then this is **not** the right channel, as stated here:

https://github.com/qgis/QGIS/issues/new/choose

![Screenshot_20201117_195453](https://user-images.githubusercontent.com/1951107/99440821-04fefc80-290f-11eb-8287-8466b4b02b51.png)

If is a bug report then you did it wrong, it must follow the guidelines/template shown here

https://github.com/qgis/QGIS/issues/new?assignees=&labels=Bug&template=10_bug_report.md&title=



**Describe the bug**


**How to Reproduce**



1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error -->

**QGIS and OS versions**



**Additional context**




Thanks for understanding.

**Comment by CataGV** [comment]
HI! I'm new here... how could I fix this problem??
Thanks in advance

**Comment by JBCH69** [comment]
set the project of GQIS as the same epgs of the shape with rectangular polygon
