### ISSUE TITLE
Translate raster in .asc format (AAIgrid) with a specific value NODATA_value=-9999 in the header is replaced by nan in the main text...

### ISSUE THREAD

**Issue by ilikeqgis** [qgis/QGIS#40157]
**Describe the bug**

When you translate a raster (geotiff) file with a specified nodata value (-9999 to replace nan) to an asc file, you get an .asc file with the good header (NODATA_value -9999) but with bad main text (NODATA_value nan)

**Example : **  
[Myfile_export_asc_1.zip](https://github.com/qgis/QGIS/files/5559530/Myfile_export_asc_1.zip)

ncols        10
nrows        9
xllcorner    698362.000000000000
yllcorner    6946119.000000000000
cellsize     1.000000000000
**NODATA_value  -9999**
 **nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan** 55.299999237060546875 55.299999237060546875 55.200000762939453125 55.200000762939453125 55.200000762939453125
 **nan nan nan nan** 55.299999237060546875 55.299999237060546875 55.299999237060546875 55.299999237060546875 55.200000762939453125 55.200000762939453125
 **nan nan nan** 55.40000152587890625 55.299999237060546875 55.299999237060546875 55.299999237060546875 55.299999237060546875 55.299999237060546875 55.200000762939453125
 **nan nan** 55.40000152587890625 55.40000152587890625 55.40000152587890625 55.299999237060546875 55.299999237060546875 55.299999237060546875 55.299999237060546875 55.200000762939453125
 **nan** 55.5 55.40000152587890625 55.40000152587890625 55.40000152587890625 55.40000152587890625 55.299999237060546875 55.299999237060546875 55.299999237060546875 55.299999237060546875
 55.5 55.5 55.40000152587890625 55.40000152587890625 55.40000152587890625 55.40000152587890625 55.40000152587890625 55.299999237060546875 55.299999237060546875 55.299999237060546875
 55.5 55.5 55.5 55.40000152587890625 55.40000152587890625 55.40000152587890625 55.40000152587890625 55.299999237060546875 55.299999237060546875 55.299999237060546875

**How to Reproduce**
Use a 

1. Load Myfile.tif (a geotiff with NODATA_Value=nan)
[Myfile.zip](https://github.com/qgis/QGIS/files/5559454/Myfile.zip)
2. Go to 'Menu Raster > Conversion > Translate (Convert Format)...'
![1_Translate_tif_with_nan_to_asc_with_specified_nodata_value_to_asc_export_1](https://user-images.githubusercontent.com/7483093/99521216-703ee200-2994-11eb-9574-a7e85a88dfa6.jpg)
3. Assign a specified nodata value : nodata_value=-9999
4. Convert it to .asc file : C:/Temp/Myfile_export_asc_1.asc
If you edit the .asc file, you get a good header but with bad main text [Myfile_export_asc_1.zip](https://github.com/qgis/QGIS/files/5559530/Myfile_export_asc_1.zip)... like described above.

**To get the good value : -9999 in the main text, you must do these processings :**
1. Load Myfile.tif (a geotiff with NODATA_Value=nan)
 [Myfile.zip](https://github.com/qgis/QGIS/files/5559454/Myfile.zip) 
2. Go to 'Menu Raster > Conversion > Translate (Convert Format)...'
![1_Translate_tif_with_nan_to_asc_with_specified_nodata_value_to_asc_export_1](https://user-images.githubusercontent.com/7483093/99521216-703ee200-2994-11eb-9574-a7e85a88dfa6.jpg)
3. Assign a specified nodata value : nodata_value=-9999
4. Convert it to .asc file : C:/Temp/Myfile_export_asc_1.asc (you get a good header with bad main text : [Myfile_export_asc_1.zip](https://github.com/qgis/QGIS/files/5559530/Myfile_export_asc_1.zip))
The GDAL/OGR console call gives: 
gdal_translate -a_srs EPSG:2154 -a_nodata -9999.0 -of AAIGrid C:/Temp/Myfile.tif C:/Temp/Myfile_export_asc_1.asc
5. Load .asc file (good header with bad main text) : Myfile_export_asc_1.asc
6. Click right mouse and the file : Save as...
![2a_saveas_export_1_asc_to_geotiff](https://user-images.githubusercontent.com/7483093/99521530-cf045b80-2994-11eb-985d-42940be74af8.jpg)
Save this first .asc file to GeoTiff...
![2b_saveas_(Myfile_export_asc_1)_to_geotiff_(My_export_asc_1_saveas_to_geotiff)](https://user-images.githubusercontent.com/7483093/99521554-d6c40000-2994-11eb-9318-9f3ff4ec18dd.jpg)
7. open the new GeoTiff : 
[Myfile_export_asc_1_saveas_to_geotiff.zip](https://github.com/qgis/QGIS/files/5559541/Myfile_export_asc_1_saveas_to_geotiff.zip)

8. Translate the new GeoTiff to .asc file again. Go to 'Menu Raster > Conversion > Translate (Convert Format)...'
![3_Translate_(My_export_asc_1_saveas_to_geotiff)_to_asc_export_2](https://user-images.githubusercontent.com/7483093/99521584-e3e0ef00-2994-11eb-872e-d2f162370871.jpg)
The GDAL/OGR console call gives: 
gdal_translate -a_srs EPSG:2154 -of AAIGrid C:\Temp\Myfile_export_asc_1_saveas_to_geotiff.tif C:/Temp/Myfile_export_asc_2.asc

9. Then, you get an .asc file with the good header and good main text like this : 
[Myfile_export_asc_2.zip](https://github.com/qgis/QGIS/files/5559537/Myfile_export_asc_2.zip)

ncols        10
nrows        9
xllcorner    698362.000000000000
yllcorner    6946119.000000000000
cellsize     1.000000000000
**NODATA_value  -9999
 -9999.0 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999
 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999
 -9999 -9999 -9999 -9999 -9999** 55.299999237060546875 55.299999237060546875 55.200000762939453125 55.200000762939453125 55.200000762939453125
 **-9999 -9999 -9999 -9999** 55.299999237060546875 55.299999237060546875 55.299999237060546875 55.299999237060546875 55.200000762939453125 55.200000762939453125
 **-9999 -9999 -9999** 55.40000152587890625 55.299999237060546875 55.299999237060546875 55.299999237060546875 55.299999237060546875 55.299999237060546875 55.200000762939453125
 **-9999 -9999** 55.40000152587890625 55.40000152587890625 55.40000152587890625 55.299999237060546875 55.299999237060546875 55.299999237060546875 55.299999237060546875 55.200000762939453125
 **-9999** 55.5 55.40000152587890625 55.40000152587890625 55.40000152587890625 55.40000152587890625 55.299999237060546875 55.299999237060546875 55.299999237060546875 55.299999237060546875
 55.5 55.5 55.40000152587890625 55.40000152587890625 55.40000152587890625 55.40000152587890625 55.40000152587890625 55.299999237060546875 55.299999237060546875 55.299999237060546875
 55.5 55.5 55.5 55.40000152587890625 55.40000152587890625 55.40000152587890625 55.40000152587890625 55.299999237060546875 55.299999237060546875 55.299999237060546875

 
**QGIS and OS versions**

QGIS version 3.16.0-Hannover
QGIS code revision 43b64b13f3
Compiled against Qt 5.11.2
Running against Qt 5.11.2
Compiled against GDAL/OGR 3.1.4
Running against GDAL/OGR 3.1.4
Compiled against GEOS 3.8.1-CAPI-1.13.3
Running against GEOS 3.8.1-CAPI-1.13.3
Compiled against SQLite 3.29.0
Running against SQLite 3.29.0
PostgreSQL Client Version 11.5
SpatiaLite Version 4.3.0
QWT Version 6.1.3
QScintilla2 Version 2.10.8
Compiled against PROJ 6.3.2
Running against PROJ Rel. 6.3.2, May 1st, 2020
OS Version Windows 10 (10.0)

**Additional context**

**Comment by gioman** [comment]
@ilikeqgis I guess you get the same results if your do the whole thing by just running the GDAL commands from the command line, right? If yes then you must report this to GDAL, not here.

**Comment by gioman** [comment]
Closing for lack of feedback.
