### ISSUE TITLE
regarding the working of software

### ISSUE THREAD

**Issue by snehastephenson** [qgis/QGIS#40165]
While adding a ring its always showing that there was an unknown error occured ,so cant create /add a ring . why this happens ? whats the right way to solve this problem

**Comment by gioman** [comment]
https://github.com/qgis/QGIS/issues/new/choose

![Screenshot_20201118_183859](https://user-images.githubusercontent.com/1951107/99572971-5cfc3880-29cd-11eb-8730-a5fe6788c33d.png)


https://github.com/qgis/QGIS/issues/new?assignees=&labels=Bug&template=10_bug_report.md&title=



**Describe the bug**


**How to Reproduce**



1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error -->

**QGIS and OS versions**



**Additional context**
