### ISSUE TITLE
Whenever I perform any Raster extraction such as 'Clip Raster by Extent'  or  'Clip Raster by Mask layer'

### ISSUE THREAD

**Issue by rahulkgour** [qgis/QGIS#40163]
Whenever I perform any Raster extraction operations such as 'Clip Raster by Extent'  or  'Clip Raster by Mask layer'

**I get the below error and doesn't get any desired output.**

Log:

QGIS version: 3.10.11-A Coruña
QGIS code revision: d2171173e4
Qt version: 5.12.3
GDAL version: 2.4.1
GEOS version: 3.7.2-CAPI-1.11.2 b55d2125
PROJ version: Rel. 5.2.0, September 15th, 2018
Processing algorithm…
Algorithm 'Clip raster by mask layer' starting…
Input parameters:
{ 'ALPHA_BAND' : False, 'CROP_TO_CUTLINE' : True, 'DATA_TYPE' : 0, 'EXTRA' : '', 'INPUT' : 'type=xyz&zmin=0&zmax=22&url=https://services.arcgisonline.com/arcgis/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}', 'KEEP_RESOLUTION' : False, 'MASK' : '/Users/rahulgour/Desktop/STR/GIS/vectorGrid/vectorGridSTR.gpkg', 'MULTITHREADING' : False, 'NODATA' : None, 'OPTIONS' : '', 'OUTPUT' : '/Users/rahulgour/Desktop/STR/GIS/ClipSTRGridWise.tif', 'SET_RESOLUTION' : False, 'SOURCE_CRS' : QgsCoordinateReferenceSystem('EPSG:3857'), 'TARGET_CRS' : QgsCoordinateReferenceSystem('EPSG:3857'), 'X_RESOLUTION' : None, 'Y_RESOLUTION' : None }

GDAL command:
gdalwarp -s_srs EPSG:3857 -t_srs EPSG:3857 -of GTiff -cutline /Users/rahulgour/Desktop/STR/GIS/vectorGrid/vectorGridSTR.gpkg -cl vectorGridSTR -crop_to_cutline type=xyz&zmin=0&zmax=22&url=https://services.arcgisonline.com/arcgis/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x} /Users/rahulgour/Desktop/STR/GIS/ClipSTRGridWise.tif
GDAL command output:
/bin/sh: /Users/rahulgour/Desktop/STR/GIS/ClipSTRGridWise.tif: No such file or directory

FAILURE: No target filename specified.

Usage: gdalwarp [--help-general] [--formats]

[-s_srs srs_def] [-t_srs srs_def] [-to "NAME=VALUE"]* [-novshiftgrid]

[-order n | -tps | -rpc | -geoloc] [-et err_threshold]

[-refine_gcps tolerance [minimum_gcps]]

[-te xmin ymin xmax ymax] [-tr xres yres] [-tap] [-ts width height]

[-ovr level|AUTO|AUTO-n|NONE] [-wo "NAME=VALUE"] [-ot Byte/Int16/...] [-wt Byte/Int16]

[-srcnodata "value [value...]"] [-dstnodata "value [value...]"] -dstalpha

[-r resampling_method] [-wm memory_in_mb] [-multi] [-q]

[-cutline datasource] [-cl layer] [-cwhere expression]

[-csql statement] [-cblend dist_in_pixels] [-crop_to_cutline]

[-of format] [-co "NAME=VALUE"]* [-overwrite]

[-nomd] [-cvmd meta_conflict_value] [-setci] [-oo NAME=VALUE]*

[-doo NAME=VALUE]*

srcfile* dstfile

Available resampling methods:

near (default), bilinear, cubic, cubicspline, lanczos, average, mode, max, min, med, Q1, Q3.

Execution completed in 0.23 seconds
Results:
{'OUTPUT': '/Users/rahulgour/Desktop/STR/GIS/ClipSTRGridWise.tif'}

Loading resulting layers
The following layers were not correctly generated.<ul><li>/Users/rahulgour/Desktop/STR/GIS/ClipSTRGridWise.tif</li></ul>You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.

**Comment by gioman** [comment]
@rahulkgour are you trying to clip tile layers as inputs?

**Comment by rahulkgour** [comment]
> @rahulkgour are you trying to clip tile layers as inputs?

Yes @gioman.

**Comment by gioman** [comment]
> Yes @gioman.

they are not supported inputs.
