### ISSUE TITLE
extend tracing to advanced digitizing toolbar

### ISSUE THREAD

**Issue by lajunek** [qgis/QGIS#40183]
**I would be glad if tracing also works with advanced digitizing tools as create hole, reshape feature, add part etc**

**Additional context**

**Comment by saberraz** [comment]
This is already supported for most of those tools. Have you tried to use it?

**Comment by lajunek** [comment]
for 3.10 LTR as well?

**Comment by saberraz** [comment]
It should be mostly there since we implemented it in QGIS 2.14!

**Comment by lajunek** [comment]
Ok so it depends on the usage of the tools, I have to check out. Is there a "movie" about the usage of tracing ?

**Comment by saberraz** [comment]
You need to make sure you have your tracing set properly, and the tool should just "work":
https://docs.qgis.org/3.16/en/docs/user_manual/working_with_vector/editing_geometry_attributes.html?highlight=trace#automatic-tracing
