### ISSUE TITLE
importing SE (ogc symbology encoding) and/or converting to SLD (ogc style layer definition) new feature

### ISSUE THREAD

**Issue by harryplotter33** [qgis/QGIS#40186]
best regards to all !

i'd like to import in qgis *.se xml (ogc symbology encoding) file generated by Geomedia and convert them to *.sld xml (ogc style layer definition) to use them in qgis and Geoserver.

I there a way to do that ?

Thanks to all !

**Comment by gioman** [comment]
> I there a way to do that ?

@harryplotter33 please post questions on the users or developers mailing list.

**Comment by saberraz** [comment]
An extra point for  the nice username @harryplotter33 !
