### ISSUE TITLE
Value-list in value-relation stays empty within a 1:n-relation when using current_parent_value('parent_field')

### ISSUE THREAD

**Issue by koenigherford** [qgis/QGIS#40194]
The value-list in value-relation stays empty within a 1:n-relation when using current_parent_value('parent_field') in the first step when creating a new child-feature (which is not an expected behaviour) but is filled as expected after confirming a empty value-list.

Some sceenshots and the attached-sample-project shows more than thousand words...:
I set up a sample project with following settings:

![grafik](https://user-images.githubusercontent.com/28433436/99704694-065c3080-2a99-11eb-9f97-79e51c09978f.png)

The child-features-layer is empty.

The relation is set up like:
![grafik](https://user-images.githubusercontent.com/28433436/99705289-d2353f80-2a99-11eb-96f0-d6a423729d29.png)

![grafik](https://user-images.githubusercontent.com/28433436/99705110-97330c00-2a99-11eb-9bc5-9bc607738b89.png)

(Step 0: Create some parent-features and save them because of #40129)

When editing the parent-feature to add child-features (Step 1: Identify; Step 2: Add new feature) the **avaliable value-list stays empty** (Step 3) 

![grafik](https://user-images.githubusercontent.com/28433436/99706965-1b868e80-2a9c-11eb-9664-1c36b9b297e6.png)

After pressing OK (Step 4) the value-list **is filled now as expected** (Step 5).
This causes following problems:
Problem 1: In step 3/4 the User thinks, something is set up wrong/he may think not to be able to create a new feature, but step 5 shows, all iss set up well and creation of child-features is possible
Problem 2: Unnecessary steps to create a feature.

![grafik](https://user-images.githubusercontent.com/28433436/99707380-a5cef280-2a9c-11eb-8f5d-55cb56c0fc1a.png)

Sample project:
[current_parent_value_test_project.zip](https://github.com/qgis/QGIS/files/5568942/current_parent_value_test_project.zip)

**QGIS 3.16.0**

**Comment by elpaso** [comment]
The bad new is that it wasn't designed to work like that: the "parent" form is for embedded forms only.

The good new is that using drag and drop designer and setting "Force hide form on add feature" it works as expected because in that case the embedded sub-form has a parent.

![immagine](https://user-images.githubusercontent.com/142164/100102606-20fd2380-2e64-11eb-89b2-12ece81b44d5.png)

**Comment by elpaso** [comment]
Not a bug IMO, maybe it could be better documented.

**Comment by gioman** [comment]
We need either the "Bug" or "Feature request" labels. If is not a bug or a feature request this should be closed. Or eventually moved to the docs tracker.

**Comment by koenigherford** [comment]
@elapso: Could not reproduce your approach: My LayerPropertiesDialog looks different in various places: 

Checkboxes (from right side of your sceenshot) are missing.
![grafik](https://user-images.githubusercontent.com/28433436/100151205-23ca3980-2ea1-11eb-9722-2a91029563ad.png)

Form stays empty
![grafik](https://user-images.githubusercontent.com/28433436/100151498-81f71c80-2ea1-11eb-8248-9ba57c7cbde8.png)


QGIS-Version | 3.16.0-Hannover | QGIS-Codeversion | 43b64b13f3
-- | -- | -- | --
Kompiliert gegen Qt | 5.11.2 | Laufendes Qt | 5.11.2
Kompiliert mit GDAL/OGR | 3.1.4 | Läuft mit GDAL/OGR | 3.1.4
Kompiliert mit GEOS | 3.8.1-CAPI-1.13.3 | Läuft mit GEOS | 3.8.1-CAPI-1.13.3
Kompiliert mit SQLite | 3.29.0 | Läuft mit SQLite | 3.29.0
PostgreSQL-Client-Version | 11.5 | SpatiaLite-Version | 4.3.0
QWT-Version | 6.1.3 | QScintilla2-Version | 2.10.8
Kompiliert mit PROJ | 6.3.2 | Läuft mit PROJ | Rel. 6.3.2, May 1st, 2020
BS-Version | Windows 10 (10.0)


What mistake did I do ?

**Comment by koenigherford** [comment]
Excuse me. My mistake. 
Your approach worked.
