### ISSUE TITLE
The installation fails miserably.

### ISSUE THREAD

**Issue by Guyver2095** [qgis/QGIS#40208]
I have been a Qgis user for years, however with the Ubuntu - Linux Mint 20, it has become impossible to install a different (Newer version) of qgis from repositories.

In fact if unstable ubuntugis repositury is installed, Qgis breaks:
  Conflicts: <uim-qt3>
  Break: qgis-common
  Break: qgis-provider-grass

 And as an additional problem the gpg key produces the following message.

gpg: key F7E06F06199EF2F2: 1 signature not verified due to missing key
gpg: key F7E06F06199EF2F2: "QGIS Archive Automatic Signing Key (2020) <qgis-developer@lists.osgeo.org>"

This happens with many versions og Qgis and apt sources modiffications Ubuntugis-unstable, nightly build, etc.

Given the large number of problems for installation, GrassGis comunication problems and plug in failures,  have you ever thought about closing your site and removing your software from public until you have a real working version of your real software front end again?

You should consider it ...

**Comment by nyalldawson** [comment]
Closed due to breaking code of conduct

**Comment by gioman** [comment]
Thanks @nyalldawson
