### ISSUE TITLE
QGIS Crashing on closing down

### ISSUE THREAD

**Issue by simonmakoni** [qgis/QGIS#40214]
h2. User Feedback

This crash occurs when I shut down the QGIS after drawing a polygon feature using my plugin. 

I cannot see any reason this happens. Any assistance you can give would be much appreciated. 

h2. Report Details

*Crash ID*: 403bc0d8e36e0d574d2a471a3ae4c9b691ee6fbd

*Stack Trace*
<pre>
QgsVertexTool::~QgsVertexTool :
QgsVertexTool::~QgsVertexTool :
QgisApp::~QgisApp :
CPLStringList::operator[] :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.4.8-Madeira
QGIS code revision: commit:04ee8e0761
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by Zuzuesque** [comment]
## User Feedback

I meant to open a new ticket, but this seems related so I will just add it here. Whenever I am done working and want to close Qgis, it crashes. It doesn't seem to matter what I did last, even just adjusting some polygon feature or label, it always closes with an error.

## Report Details

**Crash ID**: [ece7e42b38ddbef052745aa2d10e41e55b5b81bb](https://github.com/qgis/QGIS/search?q=ece7e42b38ddbef052745aa2d10e41e55b5b81bb&type=Issues)

**Stack Trace**
<pre>
QgisApp::projectTemporalRangeChanged qgisapp.cpp:11468
QMetaObject::activate :
QgsProject::clear qgsproject.cpp:817
QgisApp::closeProject qgisapp.cpp:13386
QgisApp::fileExit qgisapp.cpp:6402
QWidget::event :
QgisApp::event qgisapp.cpp:2173
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QWidgetPrivate::close_helper :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processCloseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1637
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.16.0-Hannover
QGIS code revision: 43b64b13f3
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

**Comment by gioman** [comment]
> I meant to open a new ticket, but this seems related so I will just add it here. Whenever I am done working and want to close Qgis, it crashes. It doesn't seem to matter what I did last, even just adjusting some polygon feature or label, it always closes with an error.

@Zuzuesque try with a new QGIS profile, no 3rd party plugins installed.

**Comment by gioman** [comment]
>  QGIS Version: 3.4.8-Madeira

@simonmakoni 

too old, you must test with the latest 3.10 or 3.16

Also you need to test with a new QGIS profile, no 3rd party plugins installed except yours.

If the source of the problem is your plugin then you likely need to fix your code, as a misuse of the API can lead to crashes (ask in the QGIS developers mailing list).

**Comment by roya0045** [comment]
@Zuzuesque 100% unrelated

**Comment by roya0045** [comment]
@Zuzuesque there is already a tocket with your stack trace and it should be solved in the next release I think.

**Comment by gioman** [comment]
Closing for lack of feedback.
