### ISSUE TITLE
Vertex Tool

### ISSUE THREAD

**Issue by jisoooh0202** [qgis/QGIS#40215]
Hello, there. 

Vertex Tool has bug?

When I am trying to delete the points of line, it is unexpectedly ended.
I thought it was maybe because of my computer, so I tried with several other computers (laptops, macbook, desktop). it happens all the time. 
Did anyone had this problem or just me?

## User Feedback

vertex tool is not working.
everytime click something, it is happening.

## Report Details

**Crash ID**: [cbbdf4dc1d1c76df53148e01cc03c42d5832a57c](https://github.com/qgis/QGIS/search?q=cbbdf4dc1d1c76df53148e01cc03c42d5832a57c&type=Issues)

**Stack Trace**
<pre>
QgsGeometryValidator::checkRingIntersections qgsgeometryvalidator.cpp:69
QgsGeometryValidator::validatePolygon qgsgeometryvalidator.cpp:234
QgsGeometryValidator::run qgsgeometryvalidator.cpp:315
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.16.0-Hannover
QGIS code revision: 43b64b13f3
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

**Comment by gioman** [comment]
> Hello, there.
> 
> Vertex Tool has bug?
> 
> When I am trying to delete the points of line, it is unexpectedly ended.
> I thought it was maybe because of my computer, so I tried with several other computers (laptops, macbook, desktop). it happens all the time.
> Did anyone had this problem or just me?

@jisoooh0202 from

**Comment by gioman** [comment]
> Hello, there.
> 
> Vertex Tool has bug?
> 
> When I am trying to delete the points of line, it is unexpectedly ended.
> I thought it was maybe because of my computer, so I tried with several other computers (laptops, macbook, desktop). it happens all the time.
> Did anyone had this problem or just me?

@jisoooh0202 from

https://github.com/qgis/QGIS/issues/new/choose

![Screenshot_20201121_170511](https://user-images.githubusercontent.com/1951107/99882958-ed2fbd00-2c1b-11eb-8428-0e4ed744a5a2.png)

If you are sure that is a bug, then report it following the template proposed in

https://github.com/qgis/QGIS/issues/new?assignees=&labels=Bug&template=10_bug_report.md&title=




**Describe the bug**


**How to Reproduce**



1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error -->

**QGIS and OS versions**



**Additional context**
