### ISSUE TITLE
"Title case" and "Force first letter to capital" have almost no difference

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#40218]
In Style Manager, open a text format properties, formatting tab
Switching the type case values, both "Title case" and "Force first letter to capital" seem to keep the existing case of all letters except the first one of **each** word to which they apply an uppercase. The only difference i can find is that one capitalizes the first letter of prepositions (which I think is an English-centric rule) and the other doesn't.
I'd have expected one of them to return either:
* each first letter in capital and the rest in lowercase: the behavior of title function (`title('hello WOrld')`)
* or only the first letter of the whole text in uppercase: `upper(left('hello WOrld', 1))  ||  lower(substr('hello WOrld',2))`

![titlecase](https://user-images.githubusercontent.com/7983394/99887730-10239680-2c47-11eb-8806-47dbc72e5ef3.gif)

QGIS version | 3.17.0-Master | QGIS code revision | 1b56825791
-- | -- | -- | --
Compiled against Qt | 5.12.8 | Running against Qt | 5.12.8
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.5 (Ubuntu 12.5-0ubuntu0.20.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Ubuntu 20.04.1 LTS | This copy of QGIS writes debugging output.
Active python plugins | db_manager; MetaSearch; processing

**Comment by nyalldawson** [comment]
This is by design -- try feeding an entirely upper or entirely lower case string in to see the difference

**Comment by roya0045** [comment]
Almost no difference and no difference is not the same thing. Unsure how this is a bug.

**Comment by DelazJ** [comment]
> This is by design -- try feeding an entirely upper or entirely lower case string in to see the difference

@nyalldawson Hmm... I see! So texts need to be in single type case (mind checking https://github.com/qgis/QGIS-Documentation/pull/6293/files, please? Thanks). There's no `title()` function full equivalent.

> Almost no difference and no difference is not the same thing.

Oh! Really? 😠
