### ISSUE TITLE
QGIS crashing unexpectedly

### ISSUE THREAD

**Issue by jefflin1234** [qgis/QGIS#40222]
Crash ID: 15f80ad89052923f0b6e7732113e6482470996a9

Stack Trace

memcpy_repmovs memcpy.asm:114
VSICreateCachedFile :
RawRasterBand::AccessLine :
RawRasterBand::IReadBlock :
GDALRasterBand::GetLockedBlockRef :
GDALRasterBand::IRasterIO :
RawRasterBand::IRasterIO :
GDALRegister_EHdr :
GDALRasterBand::RasterIO :
QgsProcessingModelOutput::toVariant :
QgsRasterIdentifyResult::params :
QgsAbstractDatabaseProviderConnection::TableProperty::GeometryColumnType::operator== :
QgsRasterInterface::bandStatistics :
QgsAbstractDatabaseProviderConnection::TableProperty::GeometryColumnType::operator== :
QgsRasterLayer::computeMinMax :
QgsRasterLayer::refreshRenderer :
QgsRasterLayer::refreshRendererIfNeeded :
QgsRasterLayerRenderer::QgsRasterLayerRenderer :
QgsRasterLayer::createMapRenderer :
QgsMapRendererJob::prepareJobs :
QgsMapRendererParallelJob::start :
QgsMapCanvas::refreshMap :
QMetaObject::activate :
QTimer::timerEvent :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32Private::sendTimerEvent :
QEventDispatcherWin32::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
QGIS has been crashing continuously for me, when operating on both 3.14 and 3.10

QGIS Info
QGIS Version: 3.14.16-Pi
QGIS code revision: df27394552
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by rduivenvoorde** [comment]
@jefflin1234 you should realy give more information: what kind of data (preferably a small test set of you crashing data), what were you doing exactly, steps to reproduce etc etc.
Without such data it is undoable for devs to try to reproduce you crash, which is needed to investigate.
Although QGIS should never crash... often this has something to do some strange data things.

**Comment by gioman** [comment]
>  QGIS Version: 3.14.16-Pi

@jefflin1234 

update to 3.16.1
try with a new QGIS profile
if the problem persist add the detailed steps to replicate, adding a sample project+data if necessary

**Comment by gioman** [comment]
Closing for lack of feedback.
