### ISSUE TITLE
Generate MBTiles - Some zoom levels have missing tiles

### ISSUE THREAD

**Issue by samath99** [qgis/QGIS#40232]
After generating MBTiles that have a zoom of 10-22. Some of the tiles are missing in specific zoom levels.
i extract the MBtiles files using https://github.com/mapbox/mbutil and verify that some tiles are missing

**Comment by gioman** [comment]
@samath99 you miss to add most of the requested info:

QGIS version?
Operating system?
Detailed steps to replicate?

and more:

What is your input?
if you repeat the task, it is always the same tiles missing? or differ?

**Comment by samath99** [comment]
QGIS version? 3.12.2 & 3.14.0-P 
Operating system? windows
Detailed steps to replicate?

1- I have 3shp files on my layer panel for building | curbs | road.
2- processing toolbox -- > Rastertools -->Generate XYZ tiles(MBTiles)
3 - on the process box 
            - extent = use map canvas extent
            - min zoom = 10 or 12
            - max zoom = 22
            - DPI = 96
            - Background = Transparent
            - Format = PNG
            - metrial size = 4
and Hit on RUN

4- Then i'm updating the output file on TileServer GL on my local to test

5- some zoom levels tiles are missing, when you repeat the same tile is missing. If you change the "Min zoom Level " number on the process missing tile will be change 



What is your input? As i mentioned early im using 3 SHP file layers activated onces (Polygons / Lines)

**Comment by gioman** [comment]
> QGIS version? 3.12.2 & 3.14.0-P

@samath99 they are both outdated and unsupported. You must try on 3.16.1 or use the LTR release, 3.10.

Also you must answer to:

>  if you repeat the task, it is always the same tiles missing? or differ?

**Comment by samath99** [comment]
> > QGIS version? 3.12.2 & 3.14.0-P
> 
> @samath99 they are both outdated and unsupported. You must try on 3.16.1 or use the LTR release, 3.10.
> 
> Also you must answer to:
> 
> > if you repeat the task, it is always the same tiles missing? or differ?

**Comment by samath99** [comment]
Hi thanks for your reply, initially I was using 3.10, and because of the same issue I switched to 3.12.2 & 3.14.0.
As you mentioned ill try the 3.16.1 and give you and update thanks in advanced

**Comment by samath99** [comment]
Hi @gioman i used 3.16.1-Hannover and Still missing tiles occurs in some zoom level. Is this because I'm using polygons that we draw manually using qgis?

**Comment by gioman** [comment]
> Hi @gioman i used 3.16.1-Hannover and Still missing tiles occurs in some zoom level. Is this because I'm using polygons that we draw manually using qgis?

@samath99 attach some data we can use to replicate the issue.
