### ISSUE TITLE
QGIS crashes whenever I open the layout of my project and activate the Atlas function

### ISSUE THREAD

**Issue by denilsonjesus** [qgis/QGIS#40236]
Whenever I open the layout of my project and activate the Atlas function.

Crash ID: 8fce2f3715e8712a31a117241005e6e746080b4e

Stack Trace

QgsExpression::QgsExpression qgsexpression.cpp:155
qgis::make_unique qgis.h:426
QgsVectorLayerFeatureIterator::prepareExpression qgsvectorlayerfeatureiterator.cpp:738
QgsVectorLayerFeatureIterator::prepareField qgsvectorlayerfeatureiterator.cpp:918
QgsVectorLayerFeatureIterator::prepareFields qgsvectorlayerfeatureiterator.cpp:797
QgsVectorLayerFeatureIterator::QgsVectorLayerFeatureIterator qgsvectorlayerfeatureiterator.cpp:180
QgsVectorLayer::getFeatures qgsvectorlayer.cpp:998
VTableCursor::filter qgsvirtuallayersqlitemodule.cpp:279
vtableFilter qgsvirtuallayersqlitemodule.cpp:642
sqlite3_blob_bytes :
sqlite3_blob_bytes :
sqlite3_blob_bytes :
Sqlite::Query::step qgsvirtuallayersqlitehelper.cpp:120
QgsVirtualLayerFeatureIterator::fetchFeature qgsvirtuallayerfeatureiterator.cpp:271
QgsAbstractFeatureIterator::nextFeature qgsfeatureiterator.cpp:63
QgsFeatureIterator::nextFeature qgsfeatureiterator.h:376
QgsVectorLayerFeatureIterator::fetchFeature qgsvectorlayerfeatureiterator.cpp:442
QgsAbstractFeatureIterator::nextFeature qgsfeatureiterator.cpp:63
QgsFeatureIterator::nextFeature qgsfeatureiterator.h:376
QgsVectorLayerRenderer::drawRenderer qgsvectorlayerrenderer.cpp:346
QgsVectorLayerRenderer::render qgsvectorlayerrenderer.cpp:317
QgsMapRendererCustomPainterJob::doRender qgsmaprenderercustompainterjob.cpp:319
QgsMapRendererCustomPainterJob::staticRender qgsmaprenderercustompainterjob.cpp:267
QtConcurrent::StoredFunctorCall1::runFunctor qtconcurrentstoredfunctioncall.h:432
QtConcurrent::RunFunctionTask::run qtconcurrentrunbase.h:136
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.16.0-Hannover
QGIS code revision: 2bd49ff5a2
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.3.0dev
Running against GDAL: 3.3.0dev

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

**Comment by gioman** [comment]
>  QGIS Version: 3.16.0-Hannover

@denilsonjesus 

update to 3.16.1
try with a new QGIS profile, no 3rd party plugins installed
if the problem persist attach a sample project+data to allow us replicate the issue

**Comment by roya0045** [comment]
Do you have expressions set in some places? You seem to have an iterator running in an iterator. The project may be needed to debug if available.

**Comment by denilsonjesus** [comment]
Yes, I have expressions. I can send the project.
Thanks

Denilson de Jesus
________________________________
De: Alex <notifications@github.com>
Enviado: segunda-feira, 23 de novembro de 2020 10:56
Para: qgis/QGIS <QGIS@noreply.github.com>
Cc: denilsonjesus <denilson.jesus@hotmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [qgis/QGIS] QGIS crashes whenever I open the layout of my project and activate the Atlas function (#40236)


Do you have expressions set in some places? You seem to have an iterator running in an iterator. The project may be needed to debug if available.

**Comment by denilsonjesus** [comment]
I will try.

and I will send de project too.
Thanks

Denilson de Jesus
Celular:     (11) 96361-9745
Fone:        (11) 3775-5141 (Comercial)

________________________________
De: Giovanni Manghi <notifications@github.com>
Enviado: segunda-feira, 23 de novembro de 2020 08:54
Para: qgis/QGIS <QGIS@noreply.github.com>
Cc: denilsonjesus <denilson.jesus@hotmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [qgis/QGIS] QGIS unexpectedly ended (#40236)


QGIS Version: 3.16.0-Hannover

@denilsonjesus<https://github.com/denilsonjesus>

update to 3.16.1
try with a new QGIS profile, no 3rd party plugins installed
if the problem persist attach a sample project+data to allow us replicate the issue

**Comment by denilsonjesus** [comment]
Denilson de Jesus compartilhou um arquivo do OneDrive com você. Para exibi-lo, clique no link abaixo.
<https://1drv.ms/u/s!Ap1glRHWcuhOlTCLxc8em4Z-D008>
[https://r1.res.office365.com/owa/prem/images/dc-generic_20.png]<https://1drv.ms/u/s!Ap1glRHWcuhOlTCLxc8em4Z-D008>
toqgis.7z<https://1drv.ms/u/s!Ap1glRHWcuhOlTCLxc8em4Z-D008>

Hi ,
I sent my project with layout problem for you.
Thank you for help.

Denilson de Jesus

________________________________
De: Alex <notifications@github.com>
Enviado: segunda-feira, 23 de novembro de 2020 10:56
Para: qgis/QGIS <QGIS@noreply.github.com>
Cc: denilsonjesus <denilson.jesus@hotmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [qgis/QGIS] QGIS crashes whenever I open the layout of my project and activate the Atlas function (#40236)


Do you have expressions set in some places? You seem to have an iterator running in an iterator. The project may be needed to debug if available.

**Comment by gioman** [comment]
Crash confirmed also here on Linux.

**Comment by roya0045** [comment]
what expressions are used in the layout? Or maybe the whole project?

**Comment by denilsonjesus** [comment]
Hi

On MAP
I used filter on properties

"CAT_1_LEGENDA" IS NULL
"CAT_1_LEGENDA" = 'PROVÍNCIA RONDÔNIA-JURUENA'
"CAT_1_LEGENDA" = 'PROVÍNCIA TAPAJÓS-PARIMA'

on layer style
"CAT_3_LEGENDA" = '  Formação Pimenta Bueno'
"CAT_1_LEGENDA" = 'PROVÍNCIA RONDÔNIA-JURUENA'

on layout  I don´t used any on the project that i sent for you.

Denilson


________________________________
De: Alex <notifications@github.com>
Enviado: quarta-feira, 16 de dezembro de 2020 17:35
Para: qgis/QGIS <QGIS@noreply.github.com>
Cc: denilsonjesus <denilson.jesus@hotmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [qgis/QGIS] QGIS crashes whenever I open the layout of my project and activate the Atlas function (#40236)


what expressions are used in the layout? Or maybe the whole project?

**Comment by gioman** [comment]
> Crash confirmed also here on Linux.

@denilsonjesus I tested again your project on the latest 3.16 and cannot replicate the crash anymore, please give it a try.

**Comment by denilsonjesus** [comment]
I opend it again on QGSI 3.16.1.
I received de the follow answer when I actived the ATLAS function
[cid:06916f11-a111-4858-87f3-288275633e78]


And i remember now a I used virtual layer

select  ROW_NUMBER() OVER() AS Rowid, geometry,CAT_2,CAT_3,CAT_4,
SIGLA_UNID , CAT_1 AS  CAT_1_LEGENDA   ,
          ' '
|| Upper( case     when CAT_4 is null AND CAT_3 is null
THEN CAT_2  = CAT_4    ELSE CAT_2    END  ) AS  CAT_2_LEGENDA,
     '  '
||  case     when CAT_4 is null
THEN CAT_3  = CAT_4    when CAT_4 is NOT null
THEN  CAT_3    END   AS  CAT_3_LEGENDA,
  '   ' |
|  coalesce(CAT_4, CAT_3, CAT_2)||' (' || Numero ||')'   AS CAT_4_LEGENDA  ,    Numero
from geologia_integrada    order by NUMERO DESC


Denilson de Jesus
Celular:     (11) 96361-9745
Fone:        (11) 3775-5141 (Comercial)

________________________________
De: Giovanni Manghi <notifications@github.com>
Enviado: sexta-feira, 18 de dezembro de 2020 12:29
Para: qgis/QGIS <QGIS@noreply.github.com>
Cc: denilsonjesus <denilson.jesus@hotmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [qgis/QGIS] QGIS crashes whenever I open the layout of my project and activate the Atlas function (#40236)


Crash confirmed also here on Linux.

@denilsonjesus<https://github.com/denilsonjesus> I tested again your project on the latest 3.16 and cannot replicate the crash anymore, please give it a try.

**Comment by roya0045** [comment]
Could the accents be causing the crash?

**Comment by denilsonjesus** [comment]
I Opened the same  project that i sent for you. I started the layout e active the preview ATLas option and a I received the only follow msg.When I click on OK the QGIS close
[cid:ae2e5f7c-29ba-40f4-b9bd-502ccc23ddc4]

BUT, I tried to do the process again, and it works now. I don´t know what happen.

Denilson

________________________________
De: Alex <notifications@github.com>
Enviado: sexta-feira, 18 de dezembro de 2020 13:06
Para: qgis/QGIS <QGIS@noreply.github.com>
Cc: denilsonjesus <denilson.jesus@hotmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [qgis/QGIS] QGIS crashes whenever I open the layout of my project and activate the Atlas function (#40236)


Could the accents be causing the crash?

**Comment by gioman** [comment]
> BUT, I tried to do the process again, and it works now. I don´t know what happen.

@denilsonjesus tested on windows too, no crash. Likely to be a local issue.
