### ISSUE TITLE
QGIS not connecting to ODBC source anymore

### ISSUE THREAD

**Issue by CommunyAS** [qgis/QGIS#40234]
Dear all,

I have a problem connecting to ODBC data sources (particularly a FileMaker Pro database with FileMaker Pro 18 ODBC installed) in QGIS 3.10.8 LTR or QGIS 3.16.0.
Trying to connect to a database (connection specifications are correct) I get this message.

> Connection failed - Check settings and try again.
> Extended error information:
> Unable to initialize ODBC connection to DSN for ... [database specifications]> 

I just checked if it works with the younger versions, included the latest version (QGIS 3.14 and 3.16) - same problem.

It, however, works perfectly in QGIS 3.4.10 (and other applications like MS Excel).
I already searches through the preferences, but found nothing that might fix this problem.

Im running
- macOS 10.13.6
- ODBC Manager 1.0.19 / iODBC 2.52.14 - both 64 bit
- QGIS 3.16.0 and QGIS 3.4.10 (the latter connects to ODBC)

Does anyone has an idea how to fix this problem?

Best wishes,
André

**Comment by gioman** [comment]
> I have a problem connecting to ODBC data sources

@CommunyAS please attach a sample we can use for testing.

**Comment by gioman** [comment]
Also add detailed steps to replicate the issue.

**Comment by CommunyAS** [comment]
Steps:

1. Add layers > Add vector layer
2. select _Database_ as Source Type
3. Submenu _Database_
- _Type_ select _ODBC_
- press _New_ button
- enter specifications (e.g. Name, Host, Database, Authentication ...)

see screenshots

OR
3. Submenu _Database_ > select predefine connection
4. press _Add_ button
5. the following message is displayed
> Invalid Data Source: ODBC:Admin@MatKomp_NeoBz is not a valid or recognized data source.

In QGIS 3.4.10 it both procedures work without problems.

![Screen Shot 2020-11-23 at 12 58 48 (CET)](https://user-images.githubusercontent.com/74900017/99959979-4880bd00-2d8c-11eb-9c5b-4ed555be9d00.png)
![Screen Shot 2020-11-23 at 12 59 01 (CET)](https://user-images.githubusercontent.com/74900017/99959977-474f9000-2d8c-11eb-8611-d3584d244a0a.png)

**Comment by gioman** [comment]
> Steps:
> 
>     1. Add layers > Add vector layer
> 
>     2. select _Database_ as Source Type
> 
>     3. Submenu _Database_
> 
> 
>     * _Type_ select _ODBC_
> 
>     * press _New_ button
> 
>     * enter specifications (e.g. Name, Host, Database, Authentication ...)

@CommunyAS thanks. Can you attach a sample of your odbc datasource?

**Comment by CommunyAS** [comment]
The data sources are FileMaker Pro databases that I cannot share. I never had problems connecting to FileMaker DBs since early versions of QGIS 2 until QGIS 3.5

**Comment by gioman** [comment]
> FileMaker Pro databases

@CommunyAS the persons that may be able to fix this may have not access to such type of datasources, attaching a sample (even with fake data) will be very useful.

**Comment by gioman** [comment]
> macOS 10.13.6

@CommunyAS can you check please if this a macOS only issue?

**Comment by CommunyAS** [comment]
> can you check please if this a macOS only issue?

Sorry, I have no Windows PC at hand.

> the persons that may be able to fix this may have not access to such type of datasources, attaching a sample (even with fake data) will be very useful.

I attached a sample FileMaker database containing one table _Lagetypen_ with data.

[TestDB.fmp12.zip](https://github.com/qgis/QGIS/files/5583525/TestDB.fmp12.zip)

**Comment by CommunyAS** [comment]
I stumbled upon a similar issue posted from someone referring to another software and gave it a try:

Obviously there is a problem that QGIS cannot connect to ODBC sources via system DNS.
But **QGIS can connect the ODBC sources via user DNS**.

I checked with two FileMaker Pro databases (FMP 18.0.8) successfully and the connection is quite quick.
