### ISSUE TITLE
QGIS / “create grid” consumes far more memory on linux than on windows 

### ISSUE THREAD

**Issue by nhofer** [qgis/QGIS#40239]
I am using QGIS 3.10 both on windows and on Linux (3.10.8+28bionic) with the same RAM and CPU resources. When running the tool "create grid" QGIS behaves strange on Linux: For a certain extent (~ 100x100km), when creating a grid with 20m-100m cell size, memory consuming doesn't go beyond ~2,5-3GB. With 15m cell size, the calculations seem to exponentiate a lot - and it takes up to 30GB memory (not a steady increase, but rather abrupt) and it won't finish either. As my goal was initially a 10m grid - with this cellcize QGIS seems to crash a few minutes after running the tool, as memory goes up abruptly, however I don't any messages or warnings.

On windows, running the same tool with the same parameters behaves differently: for the 10m grid only half of the memory (max. 7-8GB from 16GB) is used - I don't know what causes this strange behavior on Linux ... (?)

**Comment by gioman** [comment]
@nhofer is this a question or a bug report?

**Comment by nhofer** [comment]
as ths behaviour is not explainable to me, its both a question and possibly a bug.

**Comment by gioman** [comment]
@nhofer I think I was able to replicate on Linux (but had to use grids of  10m size, and an area  much larger than 10x10km). What I see is also that the memory is not released after the operation ends, can you confirm it?

**Comment by gioman** [comment]
>  can you confirm it?

@nhofer never mind, it took a while but then the memory was released.

**Comment by nhofer** [comment]
@gioman We had to kill a process which hung on the init process to free the memory - I forgot to mention that before.

**Comment by gioman** [comment]
> We had to kill a process which hung on the init process to free the memory - I forgot to mention that before.

@nhofer it was necessary here, in fact the operation itself was very fast and didn't hung QGIS (16GB or RAM here).

**Comment by nhofer** [comment]
@gioman made a mistake i my original comment. The area I am using is 100x100xkm , not 10x10km, sorry... Can you test it again?

**Comment by gioman** [comment]
@nhofer I have to correct myself again: this tool leaks memory and if you kill the tool before it eats up all the RAM then the memory will not be released unless closing QGIS.

**Comment by root676** [comment]
@nhofer are you using the `Rectangle (Polygon)` option for the grid type?

**Comment by nhofer** [comment]
@root676 yes, polygon type.

**Comment by gioman** [comment]
> @nhofer are you using the `Rectangle (Polygon)` option for the grid type?

@root676 also tested with a polygon, square, grid.

**Comment by root676** [comment]
@gioman @nhofer I had a quick chance to test it yesterday but the memory leak doesn't apper in my version (ubuntu) - memory stays pretty stable. I hit another constraint: the raster was too big to fit into a shapefile (strange OGR errors). I think I'll test this again.

**Comment by gioman** [comment]
> the raster

@root676 raster? are we speaking about the same tool?

**Comment by root676** [comment]
@gioman sry - thats just my wrong wording. It is the Create grid algorithm that creates vector grids. :wink:

**Comment by gioman** [comment]
@root676 

https://drive.google.com/file/d/1o3P_xP1UcQZlWeTk9q69rvfvJu0DNgEQ/view?usp=sharing

**Comment by root676** [comment]
@gioman thanks - I'll try again.

**Comment by root676** [comment]
So tested this again but to me there is no sign of a memory leak that is related to the `Create grid` algorithm. @gioman in your screen GIF you save the grid to a temporary output which creates a layer that is stored in memory (see data provider of the created layer). This stores the huge vector grid totally in memory and fills it up. It doesn't if you save the grid to disk.

The real bug for me is that the memory doesn't get cleared when one removes the finished memory layer from the project or stops the memory layer from being filled by the algorithm (the case that is shown in your screen GIF). Then the layer still stays in my RAM. Maybe we have to revisit the **destruction of memory layers** in this case? @gioman can you confirm this too?

**Comment by gioman** [comment]
>  @gioman can you confirm this too?

@root676 yes you are right (of course, silly me).

> Then the layer still stays in my RAM.

yes, this seems to be the real issue.

**Comment by gioman** [comment]
@nhofer back to the original report... I can't confirm a large memory use on Linux when saving the output to disk.

**Comment by gioman** [comment]
Another related issue: the process can be canceled if outputting to memory layer, it can't if saving to disk (QGIS must be killed).

**Comment by nyalldawson** [comment]
I'm not saying there's not a leak here , but I don't think @gioman's screencast reveals this -- all it's showing is the increasing amount of memory reserved for the qgis process, not the actual memory in use after the algorithm is canceled.

See https://stackoverflow.com/a/131346/1861260. It's considerably more tricky, but you need to use the valgrind massif tool to measure the actual memory in use and determine whether it IS still in use after canceling the algorithm. (Note that default valgrind tool won't likely report a leak here, especially if the layer is being kept in a python variable which isn't being freed (since that's not technically a formal leak as the memory WILL get freed on application exit/cleanup) -- that's why you'd need to use massif).

**Comment by nyalldawson** [comment]
> Another related issue: the process can be canceled if outputting to memory layer, it can't if saving to disk (QGIS must be killed).

That's likely a symptom of the geopackage spatial index being rebuild on every added feature (ie. it will eventually cancel, but it's just waiting for the sqlite operation to finish... which will take forever). This was fixed in QGIS 3.16 along with the massive speed boosts we got from deferring the spatial index creation till after all the features are added.

**Comment by nhofer** [comment]
> 
> 
> @nhofer back to the original report... I can't confirm a large memory use on Linux when saving the output to disk.

hmm. Do you have any clue what else could cause that in my case more than 30GB RAM are used (and that the process doesnt finish? Is it possible to set memory parameters or something in qgis?

**Comment by gioman** [comment]
> Do you have any clue what else could cause that in my case more than 30GB RAM are used (and that the process doesnt finish?

@root676 when saving to disk the memory usage is stable here, if saving to memory layer ram usage grows (as expected, see above comments). Are you saving to disk or outputting to memory layer?

**Comment by nhofer** [comment]
@gioman i am saving to disk.

**Comment by gioman** [comment]
> @gioman i am saving to disk.

@nhofer can you post the parameters you are using (including the extent and CRS)?

**Comment by nhofer** [comment]
@gioman 

grid type: rectangle polygon
grid extent: 499513, 609850, 5190269, 5300407
horizontal and vertical spacing both 10m
no overlay
crs: EPSG:32633

**Comment by gioman** [comment]
> grid type: rectangle polygon
> grid extent: 499513, 609850, 5190269, 5300407
> horizontal and vertical spacing both 10m
> no overlay
> crs: EPSG:32633

@nhofer no discernible memory spike here on Ubuntu 20.04.

**Comment by nhofer** [comment]
I just started it again 10min ago, and memory is beyond 40GB and still running. I ll wait what happens to the end.
How long did the processing take you @gioman ? And are you using QGIS 3.10? thx

**Comment by nyalldawson** [comment]
@nhofer are you able to test with 3.16? There's definitely been some substantial improvements in how outputs from algorithms are written to disk and I think they may help here.

**Comment by nhofer** [comment]
Is it possible that the output is too large for a shapefile (the shp itself has more than 4gb and the dbf >3GB after computation)? It doesnt open.. Trying as geojson, geopackage,..?

@nyalldawson i will check

**Comment by gioman** [comment]
> @nhofer are you able to test with 3.16? There's definitely been some substantial improvements in how outputs from algorithms are written to disk and I think they may help here.

I used 3.10.11, no issues.

**Comment by gioman** [comment]
> Is it possible that the output is too large for a shapefile (the shp itself has more than 4gb and the dbf >3GB after computation)? It doesnt open.. Trying as geojson, geopackage,..?

The resulting gpkg is 24gb, it took quite some time, but along the process never seen any spike in ram usage. Definitely you can't use SHP as output format.

**Comment by gioman** [comment]
> The resulting gpkg is 24gb,

that is 120 million features...

**Comment by root676** [comment]
@nhofer did you check the details we last discussed? Did you still encounter problems with `Create grid` or can we close this issue?

**Comment by gioman** [comment]
Closing for lack of feedback.

**Comment by posikifi** [comment]
Hi @gioman et al.

I think this is still a problem on Windows (on Linux I haven't seen any problems). I have test on Windows 10 with latest development version (3.27.0 adec434efc) and LTR (3.26.3). "Create grid..." (with output to temporary layer) will eat all memory from my desktop. And if I won't stop it manually, finally my desktop will crash. 

Some notes:
- I can create grid when I save the result to file (or database), problem seems to be only with "Temporary layer" output
- Problem is on Windows, not other OSes (or I just test Ubuntu, but I presume other Linuxes and MacOS don't have similar problems)
- Workaround solution is that user is not using "Temporary layers". However, we are running QGIS in Citrix enviroment, where we can't limit usage of QGIS tools (at least not easily).

I hope somebody can figure this out and find solution. If you need funding to fix this, please let me know.

P
