### ISSUE TITLE
Changing SVG-file-setting from "local file" to "embedded file" resets color-settings of SVG-files

### ISSUE THREAD

**Issue by koenigherford** [qgis/QGIS#40237]
I had to switch my SVG-file-settings from local-file to "embedded-SVG" (to use the project in QFIELD).

I've got several SVG's with the ability to set custom fill-colors (same svg with different color-symbology in different rules).

When changing my settings to embedded-svg-file fill-colors are reset to default-color (stored in svg), line colors are reset too.

It would be nice to maintain the rule-specific-color-settings  which were set before
![grafik](https://user-images.githubusercontent.com/28433436/99964461-93ea9980-2d93-11eb-9317-9ee11700acbd.png)

**Comment by j-lippmann** [comment]
Btw: this plugin could be interesting for you
https://github.com/DocOC86/embedding_svg_projectfile

**Comment by gioman** [comment]
@koenigherford seems to work fine on recent releases.
