### ISSUE TITLE
QgsExpressionContextGenerator for QgsExpressionLineEdit crashes QGIS

### ISSUE THREAD

**Issue by jakimowb** [qgis/QGIS#40238]
**Description**

A `QgsExpressionContextGenerator::createExpressionContext()` can be used to define a `QgsExpressionContext` to be used for defining QgsExpressions in a `QgsExpressionLineEdit`. However, the following python code ends in a QGIS crash. Did I implement the Generator(QgsExpressionContextGenerator) the wrong way?

````python
from qgis.core import (
    QgsExpressionContextGenerator, QgsExpressionContext, QgsExpressionContextUtils
)

from qgis.gui import QgsExpressionLineEdit

class Generator(QgsExpressionContextGenerator):

    def __init__(self, *args, **kwds):
        super(Generator, self).__init__(*args, **kwds)

    def createExpressionContext(self) -> QgsExpressionContext:
        context = QgsExpressionContext([QgsExpressionContextUtils.globalScope()])
        print(f'Generated QgsExpressionContext: {context}', flush=True)
        return context

gen = Generator()
w = QgsExpressionLineEdit()
w.setExpression("'click edit button ->'")
w.registerExpressionContextGenerator(gen)
w.show()

# now click on edit button to produce a crash

````

**How to Reproduce**

1. Open the QGIS python shell (CTRAL + ALT + P)
2. Open the Editor and copy + paste the example code to
3. Run the python code to show the 
4. Click the Edit Button to cause a crash. 
![grafik](https://user-images.githubusercontent.com/1404870/99965039-913c7400-2d94-11eb-9def-5d3c4024d433.png)

**QGIS and OS versions**
I can reproduce the crash with QGIS 3.16 & 3.17 on Windows 10 and Ubuntu 20

QGIS version | 3.16.0-Hannover | QGIS code revision | 43b64b13f3
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | processing

**Additional context**

Stack Trace:

````

QBitArray::QBitArray :
QgsExpressionContextScope::QgsExpressionContextScope qgsexpressioncontext.cpp:43
QgsExpressionContext::operator= qgsexpressioncontext.cpp:271
PyInit_sip :
sipVH__core_66 sip_corepart0.cpp:22648
sipQgsExpressionContextGenerator::createExpressionContext sip_corepart9.cpp:102482
QgsExpressionLineEdit::editExpression qgsexpressionlineedit.cpp:165
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1637
BaseThreadInitThunk :
RtlUserThreadStart :
````

**Comment by roya0045** [comment]
This should be asked on the dev/user mailing list rather than filling  a bug ticket outright. @gioman  Would you suggest the same?

**Comment by gioman** [comment]
@roya0045 yes I agree.

**Comment by jakimowb** [comment]
I just subscribed to the list and will ask the same there again, ok?

**Comment by jakimowb** [comment]
So far nobody I never got response via the mailing list

**Comment by roya0045** [comment]
@jakimowb what if you do things the normal way and create scope as disting variable and append it. Some things might be going out of scope your way.

**Comment by jakimowb** [comment]
Thanks @roya0045, indeed it the volatile scope variable. Changing the Generator solved it:

````
class Generator(QgsExpressionContextGenerator):

    def __init__(self, *args, **kwds):
        super(Generator, self).__init__(*args, **kwds)
        self.mScope = QgsExpressionContextUtils.globalScope()

    def createExpressionContext(self) -> QgsExpressionContext:
        context = QgsExpressionContext([self.mScope])
        print(f'Generated QgsExpressionContext: {context}', flush=True)
        return context

````

**Comment by roya0045** [comment]
@jakimowb I'm glad this helped!
