### ISSUE TITLE
Crash when browsing to save file

### ISSUE THREAD

**Issue by roya0045** [qgis/QGIS#40244]
Crash ID: c9bf9c1fe959b2046c803d450c2a8b0d526fc2a4

Stack Trace

CThumbnailCacheDataFile::_VerifyThumbnailAtOffset :
CThumbnailCacheDataFile::GetThumbnail :
CThumbnailCache::_TryGetThumbnailFromCache :
CThumbnailCache::GetImage :
CIconCache::GetIcon :
CSparseCallback::ForceImagePresent :
CSparseImageList::_Callback_ForceImagePresent :
CSparseImageList::ForceImagePresent :
CLayerCallback::ForceImagePresent :
CLayerImageList::ForceImagePresent :
CImageListContainerBase::ForceImagePresent :
CPrivateIconSparseCallback::ForceImagePresent :
CSparseImageList::_Callback_ForceImagePresent :
CSparseImageList::ForceImagePresent :
CLoadSystemIconTask::InternalResumeRT :
CRunnableTask::Run :
CShellTask::TT_Run :
CShellTaskThread::ThreadProc :
CShellTaskThread::s_ThreadProc :
ExecuteWorkItemThreadProc :
RtlpTpWorkCallback :
TppWorkerThread :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.16.0-Hannover
QGIS code revision: 43b64b13f3
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.15063

Occured when trying to save a file. Opened the dialog to browse and got the crash. Possibly due to latency.

**Comment by gioman** [comment]
@roya0045 is this replicable?

**Comment by roya0045** [comment]
@gioman Don't think so, I just wanted to log the trace in case some else had this issue. I doubt this will occur anytime soon.

**Comment by alexbruy** [comment]
Should we close this as it is not clear how to reproduce?

**Comment by roya0045** [comment]
It's old enough that it might not be viable anymore.
