### ISSUE TITLE
Open projects stored in GPKG via drag&drop

### ISSUE THREAD

**Issue by cxcandid** [qgis/QGIS#40252]
It would be really nice, if we could open QGIS projects stored inside a GPKG file via drag&drop. 
An UI extension to handle this is highly appreciated, at least by me :-)

Or is it possible to give the QGIS GPKG files a separate extension, so that we could open QGIS GPKG projects by double click inside the os?

**Comment by jgrocha** [comment]
Hi @cxcandid 

Each geopackage can store as many projects as you want. Should we open the first? Should we open it if there is only one project? 

What do you think, if there are many projects stored?

**Comment by cxcandid** [comment]
Hi @jgrocha ... Good question!

Here's just my opinion for the 2 different cases we face: 

1) drag&drop file into QGIS => should show list of layers and a list of projects
2) open GPKG from OS => show list of projects or open project directly, if only one project is available

**Comment by cxcandid** [comment]
Many thanks to @NyallDawson for implementing this! https://www.qgis.org/en/site/forusers/visualchangelog322/index.html#feature-load-projects-from-gpkg-using-drag-and-drop
