### ISSUE TITLE
Attribute table filter freezes qgis

### ISSUE THREAD

**Issue by dingausmwald** [qgis/QGIS#40256]
Another basic gis functionality not working since versions.

Atm at windows 10, x64
qgis 3.16

opening the attribute table of a geopackage layer with 47000 points on a network drive freezes qgis and takes about 10 seconds. This is okay.
Trying to use the filter function with 2 attributes freezes qgis completely after pressing "select features".

Just filtering data guys! I have to export data to excel to do the job.

**Comment by gioman** [comment]
Duplicate of https://github.com/qgis/QGIS/issues/27899
