### ISSUE TITLE
Layer filter and joined fields

### ISSUE THREAD

**Issue by uclaros** [qgis/QGIS#40257]
**Describe the bug**
When trying to add a filter to a layer containing joined fields, a dialog spawns that says:
```
You are about to set a subset filter on a layer that has joined fields.
Joined fields cannot be filtered, unless you convert the layer to a virtual layer first.
Would you like to create a virtual layer out of this layer first ?
```
This dialog has the following issues:
- It does not make clear what the problem is. It should say something like *Joined fields cannot be **used in filters**, ...*
- It is pretty obtrusive. You keep getting informed that you cannot filter by joined fields even when just want to filter by original fields, and need to press no every time. It would be better if the field filter dialog opened normally and it was somehow suggested to create a virtual layer instead, but users that don't want to can just ignore the suggestion.
- It implies that clicking Yes is the right thing to do. I don't have good experiences with virtual layers, and clicked yes one hour ago. My log is flooded with `Oracle[1] Oracle SRID 0 not found.` showing that it is accessing the remote (50ms away) database for each feature (not good)!

**Comment by gioman** [comment]
> It does not make clear what the problem is. It should say something like _Joined fields cannot be **used in filters**, ..._

@uclaros "Joined fields cannot be filtered" seems pretty much the same as "Joined fields cannot be used in filters"

> * It is pretty obtrusive. You keep getting informed that you cannot filter by joined fields even when just want to filter by original fields, and need to press no every time. It would be better if the field filter dialog opened normally and it was somehow suggested to create a virtual layer instead, but users that don't want to can just ignore the suggestion.

maybe better file a feature request for this



> * It implies that clicking Yes is the right thing to do. I don't have good experiences with virtual layers, and clicked yes one hour ago. My log is flooded with `Oracle[1] Oracle SRID 0 not found.` showing that it is accessing the remote (50ms away) database for each feature (not good)!

still true? can be replicated with postgresql/postgis?
