### ISSUE TITLE
RGB feature and legend color function

### ISSUE THREAD

**Issue by Glurback** [qgis/QGIS#40269]
**RGB feature and legend color function**
<Hi all. Would be change my life if only I could find functions that would allow to color a set of categorized attribute based on a either a defined attribute library (may exist but couldn't find, failed using the project style manager) or R,G,B fields as the "Color_RGB" function does but that would apply to both features AND to legend. And all classes at once, not one by one (aargh!) >

**PS**
<--QGis definitely rocks!-->

**Comment by DelazJ** [comment]
> I could find functions that would allow to color a set of categorized attribute based on a either a defined attribute library (may exist but couldn't find, failed using the project style manager)

I'm not sure whether I understand correctly but I wonder if this is not already available. Give a try to the "Match to saved symbols" option in "Advanced" menu at the bottom of the Layer Properties --> Symbology tab --> Categorized (https://docs.qgis.org/3.10/en/docs/user_manual/working_with_vector/vector_properties.html#categorized-renderer)

**Comment by Glurback** [comment]
Hi there! Thanks for the help!
That would partially work but to do so I would have to save set up each style, enter manually the code for each so it can recall the style for each code for the "match to save symbols” option. Idea is there but not convenient as I have hundreds of symbols to create, one by one. 
Is there any way to 
1) massively edit a symbol file to avoid doing it one by one? Or how to switch from a spreadsheet library to an xml style file recognised by QGis?
2) Creating and/or editing it so color will apply on either line, point or polygon features?
