### ISSUE TITLE
Field Calculator locks up

### ISSUE THREAD

**Issue by cjackel29** [qgis/QGIS#40263]
## User Feedback

I'm running this in the Field Calculator directly from the Main Window, NOT the attribute table.

array_first(aggregate(
layer:= 'TexasGasTransmission_TSPmeterLocations',
aggregate:='array_agg',
expression:=LOC_NAME,
filter:=levenshtein(LOC_NAME, attribute(@parent, 'SYS_NM')) <= 12,
order_by:=levenshtein(LOC_NAME, attribute(@parent, 'SYS_NM'))
))

## Report Details

**Crash ID**: [554eba1420fc6c398db06e4f716d35451db35728](https://github.com/qgis/QGIS/search?q=554eba1420fc6c398db06e4f716d35451db35728&type=Issues)

**Stack Trace**
<pre>
QgsStringUtils::levenshteinDistance qgsstringutils.cpp:210
fcnLevenshtein qgsexpressionfunction.cpp:1283
QgsStaticExpressionFunction::func qgsexpressionfunction.h:447
QgsExpressionFunction::run qgsexpressionfunction.cpp:109
QgsExpressionNodeFunction::evalNode qgsexpressionnodeimpl.cpp:950
QgsExpressionNode::eval qgsexpressionnode.cpp:29
QgsExpression::evaluate qgsexpression.cpp:372
QgsAbstractFeatureIterator::setupOrderBy qgsfeatureiterator.cpp:190
QgsAbstractFeatureIterator::ref qgsfeatureiterator.cpp:138
QgsOgrFeatureSource::getFeatures qgsogrfeatureiterator.cpp:601
QgsVectorLayerFeatureIterator::QgsVectorLayerFeatureIterator qgsvectorlayerfeatureiterator.cpp:300
QgsVectorLayer::getFeatures qgsvectorlayer.cpp:998
QgsAggregateCalculator::calculate qgsaggregatecalculator.cpp:126
QgsVectorLayer::aggregate qgsvectorlayer.cpp:4327
fcnAggregate qgsexpressionfunction.cpp:682
QgsStaticExpressionFunction::func qgsexpressionfunction.h:447
QgsExpressionFunction::run qgsexpressionfunction.cpp:109
QgsExpressionNodeFunction::evalNode qgsexpressionnodeimpl.cpp:950
QgsExpressionNode::eval qgsexpressionnode.cpp:29
QgsExpressionFunction::run qgsexpressionfunction.cpp:98
QgsExpressionNodeFunction::evalNode qgsexpressionnodeimpl.cpp:950
QgsExpressionNode::eval qgsexpressionnode.cpp:29
QgsExpression::evaluate qgsexpression.cpp:372
QgsFieldCalculator::accept qgsfieldcalculator.cpp:303
QMetaObject::activate :
QDialogButtonBox::~QDialogButtonBox :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
QgisApp::fieldCalculator qgisapp.cpp:8591
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1637
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.16.1-Hannover
QGIS code revision: b381a90dca
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by cjackel29** [comment]
This worked in 3.10 and then started locking up Today, 11/24/2020 after installing latest version of 3.10. I thought installing 3.16 would solve, but it still locks up

**Comment by gioman** [comment]
> This worked in 3.10 and then started locking up Today, 11/24/2020 after installing latest version of 3.10. I thought installing 3.16 would solve, but it still locks up

@cjackel29 please attach a sample of the data you are using with the reported expression.

**Comment by roya0045** [comment]
The use of @parent and a joined layer might be why? I recall some things were changed in the relation code.
