### ISSUE TITLE
Unable to save data layers or GIS projects

### ISSUE THREAD

**Issue by xz310** [qgis/QGIS#40264]
Hi, I'm in QGIS 3.10.11 (Windows). I've got some real difficulties in saving data layers and even GIS projects as a whole.

For data layers: After importing csv. files and sometimes refactoring them, I found it hard to make the refactored data layer permanent to the project. As a result, although I click "save" everytime before exiting GIS, the refactored data layer is always "unavailable" when I open the project again, and layers related to it (e.g. Proportion E&A, Proportion Malays) always grey out. See screenshoots below: 
![1](https://user-images.githubusercontent.com/74983277/100132959-74806900-2e86-11eb-8a9f-aeb87f4774bf.png)
![2](https://user-images.githubusercontent.com/74983277/100132971-764a2c80-2e86-11eb-897b-7378bbf41e29.png)

For GIS projects: I have no problem exiting and reopening a GIS project by double-clicking or from QGIS. However, all of the layers become unavailble once I move the project to a different location - say, another folder in my laptop (see screenshoot below); when I upload the project to Google Drive or send it as an email attachment, my collegues also have troubles loading it.
![3](https://user-images.githubusercontent.com/74983277/100133077-9c6fcc80-2e86-11eb-9edd-c44e5427549e.png)

I've tried to copy all of the workfiles to my default Drive, where QGIS is installed. But that doesn't see to fix the problem. 

Thanks!

**Comment by gioman** [comment]
@xz310 in your project settings are you using absolute or relative paths?

**Comment by xz310** [comment]
@gioman Hello, I'm using the relative path. Would changing to the absolute one make a difference? Thanks for your assistance!

**Comment by gioman** [comment]
> As a result, although I click "save" everytime before exiting GIS, the refactored data layer is always "unavailable" when I open the project again, and layers related to it (e.g. Proportion E&A, Proportion Malays) always grey out. See screenshoots below:

@xz310 are you creating temp layers (and not making them permanent afterward)?

**Comment by xz310** [comment]
Basically, yes. The refactored data layer seems to be the big problem: I've no idea in which format I should save it, and thus I can't really make it permanent. I've tried to save it in shapefile, csv, and a lot more, but I either receive an error message or have the refactored layer messed up afterwards.

**Comment by xz310** [comment]
@gioman sorry, please see the reply above.

**Comment by gioman** [comment]
> I've tried to save it in shapefile, csv, and a lot more, but I either receive an error message or have the refactored layer messed up afterwards.

@xz310 you must describe here a specific case (attaching sample data if necessary), but this do not seems to be related to the issue you reported here (that is not an issue: if you don't make permament temp layer is normal you loose them), so please file a new ticket.
