### ISSUE TITLE
Split feature does not split correctly

### ISSUE THREAD

**Issue by Ellebjerg** [qgis/QGIS#40277]
Hi,

I have in QGIS 3.16 tried to split a number of line features with the split feature tool. If I snap to a node with the split feature tool, nothing happens. If I split between two nodes, the two line parts between the two nodes are made into two separate lines, but the remainder of the line is now a multiline consisting of the two separate parts on each end of the section which was split.

Best regards,
Lars Ellebjerg

**Comment by gioman** [comment]
@Ellebjerg please add sample data, and in this specific case also a small screencast would be very useful to understand what you are doing and if there is really an issue. Thanks.

**Comment by gioman** [comment]
@Ellebjerg maybe you are hitting this very old bug? https://github.com/qgis/QGIS/issues/14070

**Comment by Ellebjerg** [comment]
I have attached five screen shots showing the lines before and after the split. I will follow up with sample data. And no, the line in this example does not selfintersect. It is a road running east to west with only small bends.

However, I come to think that it may be because the original geometry is formed by a union of several geometries (one for each intersection) in PostgreSQL based on the municipal road code.

![sshot_1](https://user-images.githubusercontent.com/10741426/100256138-b4a62100-2f44-11eb-8d5e-1583345367e0.png)
![sshot_2](https://user-images.githubusercontent.com/10741426/100256153-b96ad500-2f44-11eb-8405-3bb28bba6c3d.png)
![sshot_3](https://user-images.githubusercontent.com/10741426/100256170-bcfe5c00-2f44-11eb-95a5-4e7583ded060.png)
![sshot_4](https://user-images.githubusercontent.com/10741426/100256180-c12a7980-2f44-11eb-8ec9-5d82916f680e.png)
![sshot_5](https://user-images.githubusercontent.com/10741426/100256194-c5569700-2f44-11eb-839a-2c4a3b0b678a.png)

**Comment by Ellebjerg** [comment]
The data was stored as a multicurve-feature, but transforming it to multiline-feature makes no difference.

I have attached a small dump in a geopackage. I have tried the same split on these data with the exact same result.

[sample_data.zip](https://github.com/qgis/QGIS/files/5598176/sample_data.zip)

**Comment by gioman** [comment]
> [sample_data.zip](https://github.com/qgis/QGIS/files/5598176/sample_data.zip)

@Ellebjerg you have zipped the wrong file.

**Comment by Ellebjerg** [comment]
Sorry, this should be better

[sample_data.zip.zip](https://github.com/qgis/QGIS/files/5598218/sample_data.zip.zip)

**Comment by gioman** [comment]
> [sample_data.zip.zip](https://github.com/qgis/QGIS/files/5598218/sample_data.zip.zip)

@Ellebjerg in this sample there is the same place/area represented in the screenshots? I can't see it.

**Comment by Ellebjerg** [comment]
There is an east-west bound road about one fourth up from the southern end. This is the road which I was trying to split.

**Comment by gioman** [comment]
> There is an east-west bound road about one fourth up from the southern end. This is the road which I was trying to split.

@Ellebjerg your line is already split, the cut you describe results in the expected result to me.

![Peek 2020-11-25 18-08](https://user-images.githubusercontent.com/1951107/100266247-67787e00-2f49-11eb-9b65-b88eca5ceebc.gif)

**Comment by Ellebjerg** [comment]
Strange. Why does it produce the result shown in my screendumps on my pc, when it obviously behaves correctly on yours?
I even tried on the gpkg before uploading it with the same result.

**Comment by Ellebjerg** [comment]
Have you tried selecting one of the long sections on each side of the intersecting road. When I try selecting the part on one side, Both parts are selected, as it is also displayed in my screendump, so they are stil one feature.

**Comment by gioman** [comment]
> When I try selecting the part on one side, both parts are selected, as it is also displayed in my screendump, so they are stil one feature.

@Ellebjerg yes, it is a multipart geometry,



> I would expect these two parts to be split, when I do a single split through the road-

by "split" you mean separate them so to have single parts geometries instead?

**Comment by Ellebjerg** [comment]
Yes, that is exactly what I mean. That is to my understandig from the QGIS Documantation what the split feature tool is supposed to do. Otherwise I would use the Split parts.

**Comment by gioman** [comment]
> I mean split them into separate features. That is to my understandig from the QGIS Documantation what the split feature tool is supposed to do.

@Ellebjerg my opinion: no, I don't expect the "cut" of a part of a multipart feature to result in the split of the parts in separated geometries. To do the multipart <> singlepart conversion there are other means. But let's see what others have to say about.

**Comment by Ellebjerg** [comment]
I did a single cut through the feature as shown in the second of my screendumps. This resulted in the feature being split into three parts as shown in screendumps 3, 4 and 5. I cannot in anyway se the logic in this.

**Comment by gioman** [comment]
> I did a single cut through the feature as shown in the second of my screendumps. This resulted in the feature being split into three separate features as shown in screendumps 3, 4 and 5. I cannot in anyway se the logic in this.

@Ellebjerg look at my screencast: the part that has been cut become two new geometries. The rest remain as a single multipart geometry. Again, to me this seems the expected result.

**Comment by Ellebjerg** [comment]
Im my first screendump I have marked a single feature, which is the whole road. For some reason this does not seem to be the case in the data which I uploaded, so please disregard the uploaded data.
 I selected one row in my attribute table resulting in the selection shown in screendump 1. One cut through this (screendump 2) resulted in three separate features (screendump 3, 4 and 5). I have tried the same procedure in other parts of the data with the same result.
To me it makes no sense that one cut should result in a single feature being split into three features, two of which run from the cut to the nodes defining the line segment which was cut, and one part comprised of the remainder of the original feature on both sides of the two new features.

**Comment by gioman** [comment]
> . For some reason this does not seem to be the case in the data which I uploaded

@Ellebjerg it is the case, is a multipart geometry.

![Screenshot_20201126_121139](https://user-images.githubusercontent.com/1951107/100349594-9beb4900-2fe0-11eb-8526-498f122063d3.png)

**Comment by Ellebjerg** [comment]
By split I mean, that I would expect the feature to be split into two separate features, one on each side of the split-line. I have shown it to my colleagues, who would expect the same behavior. However, I get the problem now. We see it as one line, but this is obviously not the case when it is a multiline. The various parts may not even be connected.

I withdraw the issue.
