### ISSUE TITLE
crash when extrem zoom out with mesh layer

### ISSUE THREAD

**Issue by vcloarec** [qgis/QGIS#40283]
with extreme zoom out, this line https://github.com/qgis/QGIS/blob/74edcbed5f8d302813427206f92de662a1e3c615/src/core/mesh/qgsmeshlayerrenderer.cpp#L104 can calculate an excessive output size that lead to a extreme used of memory and eventually to a crash of QGIS when rendering.

With 3.16 and master

**Comment by PeterPetrik** [comment]
could be connected to https://github.com/qgis/QGIS/issues/20856
