### ISSUE TITLE
QGIS crashes when I open excel files using openpyxl model in Processing script

### ISSUE THREAD

**Issue by cftao** [qgis/QGIS#40297]
IMPORTANT:

QGIS exit when i open excle file use openpyxl model in "Processing Script fremwork".
I just open a excle file.

My Code 

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """     
            pExlFile = openpyxl.load_workbook("D:\Config.xlsx")
            pSheet = pExlFile["Sheet"]
            pStr = pSheet['B3']

QGIS Unexceptedly ended.
Crash ID: 8ed7476273d654ba53319b620c01d1336f6ba6f3

Stack Trace

QObject::thread :
QgsProject::writeProject :
_CallSettingFrame handlers.asm:50
__CxxCallCatchBlock frame.cpp:1322
RcConsolidateFrames :
QgsProcessingAlgorithm::runPrepared :
QgsProcessingAlgRunnerTask::run :
PyInit__core :
QgsTask::start :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

**Comment by roya0045** [comment]
can you even import openpyxl in the python console?

**Comment by cftao** [comment]
I  have imported openpyxl，for example

***************************************************************************
*                                                                         *
*   This program is free software; you can redistribute it and/or modify  *
*   it under the terms of the GNU General Public License as published by  *
*   the Free Software Foundation; either version 2 of the License, or     *
*   (at your option) any later version.                                   *
*                                                                         *
***************************************************************************
"""

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,
                       QgsFeatureSink,
                       QgsProcessingException,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterFile,
                       QgsProcessingParameterNumber)
from qgis import processing
import xlrd
import openpyxl
from openpyxl import load_workbook


Another，all coding example


    def processAlgorithm(self, parameters, context, feedback):
        """
        该模块主程序.
        """
        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.
        source = self.parameterAsSource(
            parameters,
            self.HYDRANT,
            context
        )
        pExlFile = openpyxl.load_workbook("D:\Config.xlsx")
        pSheet = pExlFile["图层对应表"]
        pStr = pSheet['B3'].value
        
        # If source was not found, throw an exception to indicate that the algorithm
        # encountered a fatal error. The exception text can be any string, but in this
        # case we use the pre-built invalidSourceError method to return a standard
        # helper text for when a source cannot be evaluated
        if source is None:
            raise QgsProcessingException(self.invalidSourceError(parameters, self.HYDRANT))

        (sink, dest_id) = self.parameterAsSink(
            parameters,
            self.OUTPUT,
            context,
            source.fields(),
            source.wkbType(),
            source.sourceCrs()
        )



        # Send some information to the user
        feedback.pushInfo('CRS is {}'.format(source.sourceCrs().authid()))
        feedback.pushInfo('测试'+ pStr)
        

        # If sink was not created, throw an exception to indicate that the algorithm
        # encountered a fatal error. The exception text can be any string, but in this
        # case we use the pre-built invalidSinkError method to return a standard
        # helper text for when a sink cannot be evaluated
        if sink is None:
            raise QgsProcessingException(self.invalidSinkError(parameters, self.OUTPUT))

        # Compute the number of steps to display within the progress bar and
        # get features from source
        total = 100.0 / source.featureCount() if source.featureCount() else 0
        features = source.getFeatures()

        for current, feature in enumerate(features):
            # Stop the algorithm if cancel button has been clicked
            if feedback.isCanceled():
                break

            # Add a feature in the sink
            sink.addFeature(feature, QgsFeatureSink.FastInsert)

            # Update the progress bar
            feedback.setProgress(int(current * total))

        # To run another Processing algorithm as part of this algorithm, you can use
        # processing.run(...). Make sure you pass the current context and feedback
        # to processing.run to ensure that all temporary layer outputs are available
        # to the executed algorithm, and that the executed algorithm can send feedback
        # reports to the user (and correctly handle cancellation and progress reports!)
        if False:
            buffered_layer = processing.run("native:buffer", {
                'INPUT': dest_id,
                'DISTANCE': 1.5,
                'SEGMENTS': 5,
                'END_CAP_STYLE': 0,
                'JOIN_STYLE': 0,
                'MITER_LIMIT': 2,
                'DISSOLVE': False,
                'OUTPUT': 'memory:'
            }, context=context, feedback=feedback)['OUTPUT']

        # Return the results of the algorithm. In this case our only result is
        # the feature sink which contains the processed features, but some
        # algorithms may return multiple feature sinks, calculated numeric
        # statistics, etc. These should all be included in the returned
        # dictionary, with keys matching the feature corresponding parameter
        # or output names.
        return {self.OUTPUT: dest_id}

**Comment by cftao** [comment]
I can run the coding in python console,for example

Python Console
Use iface to access QGIS API interface or Type help(iface) for more info
Security warning: typing commands from an untrusted source can lead to data loss and/or leak
import openpyxl
pExlFile = openpyxl.load_workbook("D:\Config.xlsx")
pSheet = pExlFile["图层对应表"]
pStr = pSheet['B3'].value
print(pStr)
阀门

**Comment by Pedro-Murteira** [comment]
@cftao Hello, is this issue still valid on more recent releases?

**Comment by cftao** [comment]
xlrd instead



---Original---
From: ***@***.***&gt;
Date: Tue, Mar 22, 2022 20:23 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [qgis/QGIS] QGIS crashes when I open excel files using openpyxl model in Processing script (#40297)




 
@cftao Hello, is this issue still valid on more recent releases?

**Comment by cftao** [comment]
OK



---Original---
From: ***@***.***&gt;
Date: Tue, Mar 22, 2022 20:37 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [qgis/QGIS] QGIS crashes when I open excel files using openpyxl model in Processing script (#40297)




 
@cftao shall we close this issue then?
