### ISSUE TITLE
QGIS crashed

### ISSUE THREAD

**Issue by jimbo-jones1313** [qgis/QGIS#40295]
## User Feedback

just another day, another crash

## Report Details

**Crash ID**: [c8dfcba9d0bae8b2a5df0265b41023463aa164b0](https://github.com/qgis/QGIS/search?q=c8dfcba9d0bae8b2a5df0265b41023463aa164b0&type=Issues)

**Stack Trace**
<pre>
QObject::thread :
</pre>

**QGIS Info**
QGIS Version: 3.16.1-Hannover
QGIS code revision: b381a90dca
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by roya0045** [comment]
this will need far more information to be remotely useful.

**Comment by uclaros** [comment]
Hey @jimbo-jones1313 I know crashing is frustrating, but you have to focus a little on helping the developers that can help cure the crashes!
Imagine your car's brakes fail and you crash, then call the car maker's engineering department, show them a photo of your crashed car and tell them *"Another day, another crash"* and expect those guys to understand there's a glitch on the braking system and redesign it so the next car you buy will have brakes that will not fail in the same way.

**Comment by jimbo-jones1313** [comment]
well, i don't know what else to add to it; don't know which crash that was, there have been so many

**Comment by gioman** [comment]
> well, i don't know what else to add to it; don't know which crash that was, there have been so many

@jimbo-jones1313 you must describe what you were doing. Also you must try if using a new QGIS profile improves things.

**Comment by jimbo-jones1313** [comment]
i installed the new update (3.16.1) yesterday, if that's what you mean

**Comment by gioman** [comment]
> i installed the new update (3.16.1) yesterday, if that's what you mean

no. Settings > User profiles > New profiles 

and afterwards do not install any 3rd party plugin.

**Comment by jimbo-jones1313** [comment]
my only "plug-ins" are GRASS, SAGA and GDAL.

**Comment by gioman** [comment]
> my only "plug-ins" are GRASS, SAGA and GDAL.

you must try a new QGIS profile anyway, is not just a matter of plugins.

**Comment by gioman** [comment]
Closing for lack of feedback.
