### ISSUE TITLE
Plugin processing: This plugin is disabled because it previously crashed QGIS.

### ISSUE THREAD

**Issue by cftao** [qgis/QGIS#40304]
IMPORTANT:

I installed qgis3.16.
When i open qgis, "Plugin processing: This plugin is disabled because it previously crashed QGIS."
I can not open toolbox.

**Comment by roya0045** [comment]
@cftao deactivate and reactivate the processing plugin in the plugin manager.
@gioman can you close?

**Comment by gioman** [comment]
I'm not getting all the notifications from Github...
