### ISSUE TITLE
artifacts from using "polygon properties"

### ISSUE THREAD

**Issue by jimbo-jones1313** [qgis/QGIS#40300]
Interesting consequence from, I assume, using "edge detection" software
(https://user-images.githubusercontent.com/63853386/100346377-0c479980-2fe4-11eb-98fa-8dac2d684055.PNG)

**Comment by gioman** [comment]
@jimbo-jones1313 you must file tickets the right way, adding the requested infos in the ticket template



**Describe the bug**


**How to Reproduce**



1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error -->

**QGIS and OS versions**



**Additional context**

**Comment by gioman** [comment]
If necessary also attach sample data we can use to replicate the problem.
