### ISSUE TITLE
Import CSV file plots coordinates in the middle of the ocean

### ISSUE THREAD

**Issue by alexxmarsh44** [qgis/QGIS#40313]
Here is me importing the CSV file into QGIS:
![csvimport](https://user-images.githubusercontent.com/59932969/100424478-83137f80-3042-11eb-8fcc-e1abfdc342ab.png)

Here is the CRS window:
![Screenshot from 2020-11-26 23-32-53](https://user-images.githubusercontent.com/59932969/100423990-c9b4aa00-3041-11eb-8597-1df029f49f4b.png)

And finally here is the plot I get out in the middle of the ocean instead of in Nevada, in the United States:

![ocean screen](https://user-images.githubusercontent.com/59932969/100424498-8a3a8d80-3042-11eb-8493-30d067f610a8.png)

Any idea why it doesn't line up?  The plot is the correct shape as it follows the route I drove in my car but it always puts the dots out in the center of the ocean.  I would really appreciate some incite as this has been bugging me for while and renders this software useless to me.

**Comment by gioman** [comment]
>  I would really appreciate some incite as this has been bugging me for while and renders this software useless to me.

@alexxmarsh44 the problem is likely to be in your data, but to be sure you must attach here your dataset, or at least a sample.

**Comment by roya0045** [comment]
Either the data or the projection used. Most likely not a bug but a bad projection setting or invalid data generated from the sensor. @alexxmarsh44 without the data this seems like a common error.

**Comment by gioman** [comment]
Closing for lack of feedback.
