### ISSUE TITLE
Filtering bug and difference on the same expression as select features using an expression

### ISSUE THREAD

**Issue by tudorbarascu** [qgis/QGIS#40316]
**Describe the bug**

Having the following table (pipes) with a field called ``diameter`` as text.

ogc_fid | diameter (text)
-- | --
 1 | 500
 2 | 500
 3 | B 500
 4 | 500
 5 | 500

I wanted to get all the pipes with diameter bigger than 500 with the following expression:
``to_int(left("diameter",1)) >= 5``

The expression logic is get the first character, turn it into integer, see if it's bigger than 5. (the original expression is more complex and this is the shortest I could reproduce).

The feature filter only select the first two.. and it gets stuck.. at feature no. 3 (B 500) **without continuing** to get the features 4 and 5 which should be in the results (only the first two features get filtered)

If I use the same expression with ``select features using an expression`` I get all the 4 results that pass the filter.

Of course.. the original table is far larger and it took quite a while to figure out how to reproduce and why. Very annoying but I'm really glad I could pinpoint the issue.Thanks.

**How to Reproduce**

1. Get the geojson table and add it to a QGIS project:
[pipes.zip](https://github.com/qgis/QGIS/files/5607812/pipes.zip)

```
{
"type": "FeatureCollection",
"name": "pipes",
"features": [
{ "type": "Feature", "properties": { "diameter": "500" }, "geometry": null },
{ "type": "Feature", "properties": { "diameter": "500" }, "geometry": null },
{ "type": "Feature", "properties": { "diameter": "B 500" }, "geometry": null },
{ "type": "Feature", "properties": { "diameter": "500" }, "geometry": null },
{ "type": "Feature", "properties": { "diameter": "500" }, "geometry": null }
]
}
```
2. Filter the attribute table using advanced filter: ``to_int(left("diameter",1)) >= 5``
Only 2 pipes are shown.. instead of 4.

**QGIS and OS versions**

**Tested with Master and 3.10.11 under Debian Testing; Tested under Windows with 3.10.8.**

QGIS version | 3.17.0-Master | QGIS code revision | c0a579c719
-- | -- | -- | --
Compiled against Qt | 5.15.1 | Running against Qt | 5.15.1
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.33.0 | Running against SQLite | 3.33.0
PostgreSQL Client Version | 13.1 (Debian 13.1-1+b1) | SpatiaLite Version | 5.0.0
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.5
Compiled against PROJ | 7.2.0 | Running against PROJ | Rel. 7.2.0, November 1st, 2020
OS Version | Debian GNU/Linux bullseye/sid | This copy of QGIS writes debugging output.
Active python plugins | pluginbuilder3; project_export_inspire; pg_history_viewer; water_topology_plugin; water_analytics; plugin_reloader; qtibia_docs_py3; scriptrunner3; QuickWKT; trackable_project_files; db_manager; processing

**Comment by gioman** [comment]
>     1. Get the sqlite table and add it to a QGIS project:
>        [features.zip](https://github.com/qgis/QGIS/files/5607624/features.zip)

@tudorbarascu Hi Tudor, I cannot add the dataset: "Invalid Data Source: /tmp/features.sqlite is not a valid or recognized data source.".

**Comment by tudorbarascu** [comment]
Hi @gioman, redid in geojson... also pasted the geojson def just to be sure. Thanks a lot! The bug is probably of high importance as it's not yielding any error and filtering should be top notch.

**Comment by gioman** [comment]
> The bug is probably of high importance as it's not yielding any error and filtering should be top notch.

confirmed also here on Windows and Linux.

**Comment by elpaso** [comment]
Agreed about the bug (it should not just stop on the error without notice), but what to you think that `to_int('B')` should return? IMO this is an invalid result.

**Comment by gioman** [comment]
> (it should not just stop on the error without notice)

it does not in the "select by expression" dialog, and returns the expected selected features.

**Comment by elpaso** [comment]
Which is? Again what logic value should be returned by `to_int('B')` ? Looks more like an `8` than a `0` to me.

IMO there is no expected results on errors: the expected result is an error message or a warning.

**Comment by gioman** [comment]
> Which is?

sorry I should have written "expected" with quotes. It was just to underline that the same expression dialog returns different results when opened in two different places.

**Comment by elpaso** [comment]
Got it, I was more concerned about what is the expected/correct behavior.

**Comment by tudorbarascu** [comment]
I

> Which is? Again what logic value should be returned by `to_int('B')` ? Looks more like an `8` than a `0` to me.
> 
> IMO there is no expected results on errors: the expected result is an error message or a warning.

Hi @elpaso  Thanks for looking into this. I didn't expect an error to be thrown but I did expect that the iterator continues to check the features left if they fit the expression (like in the select feat by expression). Thanks again.

**Comment by elpaso** [comment]
> I
> 
> > Which is? Again what logic value should be returned by `to_int('B')` ? Looks more like an `8` than a `0` to me.
> > IMO there is no expected results on errors: the expected result is an error message or a warning.
> 
> Hi @elpaso Thanks for looking into this. I didn't expect an error to be thrown but I did expect that the iterator continues to check the features left if they fit the expression (like in the select feat by expression). Thanks again.

That's fair. But if the expression has an error the user must be warned in some way.

**Comment by elpaso** [comment]
How about this?

![immagine](https://user-images.githubusercontent.com/142164/100460632-d1b72d00-30c7-11eb-895f-b6db2e958580.png)

**Comment by tudorbarascu** [comment]
Looks great!
