### ISSUE TITLE
Grass init error

### ISSUE THREAD

**Issue by jmlsiqueira** [qgis/QGIS#40327]
Hi

I have the following error message when I installed QGIS 3.10.4 ltr:

Grass init error: Grass was not found in 'C: / PROGRA ~ 1 / QGIS 3.10 / apps / grass / grass78' (GISBASE), provider and plugin will not work. I use windows 10, the latest updated version.

I start QGIS using QGIS Desktop 3.10.4 with GRASS 7.8.2.

I have already uninstalled, cleaned logs, redoed installation and the same error persists. The same thing with versions 3.2.3 and 3.10.12.

Could anyone help with this error?

-- 
--
Thanks
João Marcelo Lopes
Keep Playing

**Comment by gioman** [comment]
> Could anyone help with this error?

@jmlsiqueira use the QGIS mailing lists for questions

![Screenshot_20201129_100702](https://user-images.githubusercontent.com/1951107/100538949-c6304700-322a-11eb-87d4-05ab22150aa3.png)

I just tested/used GRASS tools on Windows with the QGIS processing toolbox, and no issues whatsoever. QGIS was installed using the standalone installers or the osgeo4w, no differences. Check if there is some other program (i.e. an AV) that can cause your QGIS installation to be incomplete (or that blocks some processes when they are called).
