### ISSUE TITLE
QGIS crashes when working with Vertex Editor

### ISSUE THREAD

**Issue by RBA-deepbv** [qgis/QGIS#40320]
## User Feedback

I am comparing two linestring layers containing one line each. Specifically I want to compare the geometry, for which I use Vertex Editor. Both compared layers are in editing mode. If swap between them to see the vertices list, QGIS crashes as soon as I want to exit editing mode on any of the layers.

To reproduce the crash:
1. Load 2 polyline layers and enter editing mode
2. view one of them in vertex editor
3. select the other one
4. select again the first one and try to turn off the editing mode

## Report Details

**Crash ID**: [de78d32b8f12013fb8c4557159959b7933b46d48](https://github.com/qgis/QGIS/search?q=de78d32b8f12013fb8c4557159959b7933b46d48&type=Issues)

**Stack Trace**
<pre>
QMetaObject::disconnect :
QObject::disconnectImpl :
QgsVertexTool::setHighlightedVertices qgsvertextool.cpp:2510
QgsVertexTool::deactivate qgsvertextool.cpp:336
QgsMapCanvas::setMapTool qgsmapcanvas.cpp:2021
QgisApp::activateDeactivateLayerRelatedActions qgisapp.cpp:14589
QgisApp::layerEditStateChanged qgisapp.cpp:14356
QMetaObject::activate :
QgsVectorLayer::rollBack qgsvectorlayer.cpp:3429
QgisApp::toggleEditing qgisapp.cpp:11044
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1637
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.16.1-Hannover
QGIS code revision: b381a90dca
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment]
@RBA-deepbv plesae try with a new QGIS profile.

**Comment by RBA-deepbv** [comment]
@gioman I've just tried with a new QGIS profile. The problem persists...

**Comment by gioman** [comment]
> The problem persists...

@RBA-deepbv attach the data, or a sample that causes the crash for you.

**Comment by RBA-deepbv** [comment]
At first I was trying it on my actual data. But it crashed on me even if I used 2 linestring scratch layers with randomly clicked lines. I attach to this post 2 layers I used last time.
[sample lines.zip](https://github.com/qgis/QGIS/files/5607979/sample.lines.zip)

**Comment by gioman** [comment]
> * Load 2 polyline layers and enter editing mode
> 
> * view one of them in vertex editor
> 
> * select the other one
> 
> * select again the first one and try to turn off the editing mode

@RBA-deepbv tested also on Win10 and QGIS 3.16.1 and cannot replicate. Maybe attaching a screencast would help understanding the exact sequence of steps you are following.

**Comment by RBA-deepbv** [comment]
@gioman 

Hereby the screencast. At the end the Crash Report should appear, but it is not recorded to the video. Apparently it records only active window.
[QGIS crash when working with Vertex Editor.zip](https://github.com/qgis/QGIS/files/5608436/QGIS.crash.when.working.with.Vertex.Editor.zip)

**Comment by gioman** [comment]
> Hereby the screencast. At the end the Crash Report should appear, but it is not recorded to the video. Apparently it records only active window.
> [QGIS crash when working with Vertex Editor.zip](https://github.com/qgis/QGIS/files/5608436/QGIS.crash.when.working.with.Vertex.Editor.zip)

@RBA-deepbv nope, cannot replicate. Are you positive you don't have any 3rd party plugin installed?

**Comment by RBA-deepbv** [comment]
That's indeed weird... I've made the screencast on a fresh QGIS profile (as you advised). There are no 3rd party plugins. The newest version of QGIS was installed today, in attempt to solve this. Sample files are saved by QGIS.

I use my QGIS profiles from root of C: drive, but I've tested just now that it doesn't matter.
I've also tried it on another Windows user account, but no difference either. 

I am not sure if it matters to have 3 versions of QGIS installed... Otherwise, I don't know what else I could check...

**Comment by gioman** [comment]
> Otherwise, I don't know what else I could check...

@RBA-deepbv can you check on a different machine?

**Comment by RBA-deepbv** [comment]
@gioman I've checked on another Windows10 computer. QGIS 3.10.8 is installed there. I've made a new QGIS profile on that machine as well. It is also crashing... attached the crash log from this one.

I've also tested it additionally on Apple computer with Mac OS Big Sur. This was the first QGIS installation ever on this machine (3.16.1). The steps I've described resulted in unexpected exit as well...

[qgis crash.txt](https://github.com/qgis/QGIS/files/5608973/qgis.crash.txt)

**Comment by agiudiceandrea** [comment]
I can replicate using QGIS 3.4, 3.16 and 3.17-master on Windows following the exact procedure showed in the provided screencast video with the provided layer or with two newly created memory layers.

**Comment by gioman** [comment]
Can see it now, it affects also 3.10 and Linux.

**Comment by gioman** [comment]
This has to be a regression... I can't see how this can't possibly be.

**Comment by RBA-deepbv** [comment]
Awesome to see that this is solved so quick! Many thanks for quick action :)
