### ISSUE TITLE
Unknown operation caused crash

### ISSUE THREAD

**Issue by donkeychen** [qgis/QGIS#40328]
hi, there is a crash report of the following data in a project.
[20201118.zip](https://github.com/qgis/QGIS/files/5610985/20201118.zip)
[20201122.zip](https://github.com/qgis/QGIS/files/5610986/20201122.zip)
(2020118= one point data with wrong geometry in #40084 , 20201122= a self-intersection polygon for testing #39770)
the testing result of #39770 is passed.  

I started editing of these layers, and do some setting in setting - options.
I tried to add new self-intersection polygon in the polygon layers,
and added new point without filling any value. 
(I don't know what I did and caused the crash, and didn't remember that if I saved the the editing, because I AFK for something, and the crash report is shown when I was back. Maybe it hanged earlier.)  

Crash ID: baf4961f2c7320cd6e04c085ed6c8954e2a49afe

Stack Trace

Index::~Index :
qsort :
Index::~Index :
Index::~Index :
Index::~Index :
Index::~Index :
Index::~Index :
Index::~Index :
Index::~Index :
QgsPointLocator::onFeatureDeleted qgspointlocator.cpp:1143
QMetaObject::activate :
QgsVectorLayer::featureDeleted moc_qgsvectorlayer.cpp:1235
QMetaObject::activate :
QgsVectorLayerEditBuffer::featureDeleted moc_qgsvectorlayereditbuffer.c

pp:368
QUndoCommand::undo :
QUndoStack::setIndex :
QgsVectorLayer::rollBack qgsvectorlayer.cpp:3410
QgisApp::toggleEditing qgisapp.cpp:11022
QgisApp::checkUnsavedLayerEdits qgisapp.cpp:13262
QgisApp::fileExit qgisapp.cpp:6399
QWidget::event :
QgisApp::event qgisapp.cpp:2173
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QWidgetPrivate::close_helper :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processCloseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1637
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.16.1-Hannover
QGIS code revision: b381a90dca
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

**Comment by gioman** [comment]
> (I don't know what I did and caused the crash, and didn't remember that if I saved the the editing, because I AFK for something, and the crash report is shown when I was back. Maybe it hanged earlier.)

@donkeychen without a cleat path to the crash it will be hard to understand what went wrong. As usual please try with a new QGIS profile, no 3rd party plugins installed.

**Comment by donkeychen** [comment]
@gioman  Yes, new profile without 3rd party plugin involved.
I am sorry for these lacking information.

**Comment by gioman** [comment]
With a clear idea about how replicate this I fear there is not much we can do.

**Comment by donkeychen** [comment]
It's okay.
I know that we need to replicate the issue.
