### ISSUE TITLE
Raster Layer Resampling option missing

### ISSUE THREAD

**Issue by Dnn2Dnn** [qgis/QGIS#40325]
![image](https://user-images.githubusercontent.com/75152323/100493175-1e9e1080-3167-11eb-9ef0-6f147b78feb8.png)
Image OUT doesn't contain Pixel Aggregate (averaging) Option anymore. Image stretch changes after selecting Cubic and\or Bilinear resampling.

**Comment by gioman** [comment]
average was renamed "bilinear"

https://github.com/qgis/QGIS/commit/9163100cb74d61fe0dda0231b49b535e8da748bc#diff-2e7d001bc9f4a118e7a7871e0f8b1cef2b56400cbc740d30b12c17e927ac5db1
