### ISSUE TITLE
Sort Feature in Atlas and Report fails if attribute column name has space

### ISSUE THREAD

**Issue by microcebus** [qgis/QGIS#40332]
**Describe the bug**
This doesn't appear to have been reported before as far as I can tell, but if you try to use the sort feature in either the Atlas or Report, if there is a space in the attribute column label, then the sort fails and it defaults to sorting by fid. This occurs in a geopackage file btw.

**How to Reproduce**
So 'sort_order' as an attribute table column label works but 'sort order' fails

**QGIS and OS versions**
QGIS 3.16.x and 3.10.x
macOS Catalina and Mojave
Windows 10

Thanks again to the team for all the effort in QGIS. 

Luke

**Comment by roya0045** [comment]
Can confirm
