### ISSUE TITLE
Filter is not applied in duplicated layers

### ISSUE THREAD

**Issue by janhec** [qgis/QGIS#40349]
When duplicating a layer with filtering active, the filtering appears to be done again.
This is imo not a logical action when duplicating a layer and it would save time when the same filtered data are used.
However, there might be another reason for the lengthy layer duplication that I am not aware of.
Priority for me: not that high...

**Comment by troopa81** [comment]
What type of *filters* are you talking about? 

If you talk about *Provider Feature filter*, it's well copied when duplicated. 

Attribute table filter is not even saved when you close the window, so it seems to be the wanted behavior.

**Comment by gioman** [comment]
Closing for lack of feedback.
