### ISSUE TITLE
QGIS crashes when exporting a layout to pdf

### ISSUE THREAD

**Issue by mjrVdL** [qgis/QGIS#40353]
## User Feedback

QGIS crashes when exporting a layout to pdf.
Layout uses an atlas witch generates 147 pages. Crash seems to occur at random (ie not allways when generating the same page). 
Project is rather complex, making use of relations, joins and virtual fields and I'm unable to reproduce the crash with a small sample.

I hope this helps.
M.

## Report Details

**Crash ID**: [7347857b0698cebe1c11ff06f1cd7b87be701e9d]('https://github.com/qgis/QGIS/search?q=7347857b0698cebe1c11ff06f1cd7b87be701e9d&type=Issues')

**Stack Trace**
<pre>
QgsExpression::QgsExpression :
QgsVectorLayerEditUtils::translateFeature :
QgsVectorLayerFeatureIterator::prepareExpression :
QgsVectorLayerFeatureIterator::prepareFields :
QgsVectorLayerFeatureIterator::QgsVectorLayerFeatureIterator :
QgsVectorLayer::getFeatures :
QgsVectorLayerFeatureIterator::FetchJoinInfo::addJoinedAttributesDirect :
QgsVectorLayerFeatureIterator::addJoinedAttributes :
QgsVectorLayerFeatureIterator::addVirtualAttributes :
QgsVectorLayerFeatureIterator::fetchFeature :
QgsAbstractFeatureIterator::nextFeature :
QgsVectorLayerJoinInfo::setEditable :
QgsVectorLayerJoinInfo::setEditable :
QgsMapRendererParallelJob::renderLayerStatic :
QgsArchive::zip :
QgsImageOperation::overlayColor :
QgsMapRendererParallelJob::cancelWithoutBlocking :
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.12.0-Bucure?ti
QGIS code revision: cd141490ec
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by gioman** [comment]
>  QGIS Version: 3.12.0-Bucure?ti

@mjrVdL too old and unsupported, you must test on the latest 3.10 or 3.16.

**Comment by mjrVdL** [comment]
Thanks for this quick response. 
I'll ask my company for an upgrade (not allowed to do it myself, a security thing it seems...), and try again.
M.

**Comment by roya0045** [comment]
Its also possible that you run out of resources.

**Comment by gioman** [comment]
Closing for lack of feedback.
