### ISSUE TITLE
Add $geometry shortcut buttons to field calculator and expression builder 

### ISSUE THREAD

**Issue by ValPinnaSardinia** [qgis/QGIS#40358]
Considering the frequent use of $geometry in many of the expressions created in the field calculator, it could be very useful to add this string to the shortcut buttons into the field calculator and expression builder.

Valerio Pinna

**Comment by roya0045** [comment]
there is an autocomplete, just type '$geo'  and it should be fine. I don't think duplicating things for ease of use is a good idea as its a sliperry slope.

**Comment by ValPinnaSardinia** [comment]
Your answer makes sense to. Also if considering the new functions, you need to type `$geomet` to be able to use the autocomplete.
