### ISSUE TITLE
Zonal Statistics as batch process

### ISSUE THREAD

**Issue by PedroVenancio** [qgis/QGIS#40356]
Hi all,

I'm seeing that Zonal Statistics had changed the way how it works between QGIS 3.10 and 3.16, but I can't find any documentation about it.

Zonal Statistics on QGIS 3.10 saved the metrics calculated in new fields of the vector layer containing zones. So, running the algorithm as batch process, I was able to calculate some statistics for hundreds of raster layers, all in the same vector layer containing zones.

Now on QGIS 3.16, the default is to Zonal Statistics generate a new vector layer. Of course it's possible to create hundreds of vector layers and just consider the last one, but this seems a drawback in the way how Zonal Statistics used to work.

I thought "Append to Layer" option from @nyalldawson could be the workaround, but I can't understand well this option:
https://qgis.org/en/site/forusers/visualchangelog314/index.html#feature-allow-appending-processing-results-to-existing-layers

Is there a way to overcome this? If not it seems a drawback in Zonal Statistics usage.

**Comment by gioman** [comment]
@PedroVenancio this the PR that changed the tool https://github.com/qgis/QGIS/pull/38650

The title says "Add Zonal statistics algorithm that creates a new output" so I always assumed that the PR added a new tool, and didn't changed the old one. Is this correct @m-kuhn @nyalldawson ?

**Comment by m-kuhn** [comment]
The tool has been aligned with the way most processing tools work.
For consistency with the rest of processing it seems to make sense to me.
Also if you consider a use case where you have immutable zones (e.g. read only database) and calculate an updated statistics dataset every day, this was previously not possible.

I can see where you are coming from, however, this is not a "zonal statistics" problem but a general processing problem. See also this (still very relevant) QEP: https://github.com/qgis/QGIS-Enhancement-Proposals/issues/89

Meanwhile, the "old" version has been left in place and marked as deprecated (https://github.com/qgis/QGIS/pull/38650/files#diff-f566bc55f4f6772a9a4b48a65798543fe10eb2ebb0872eb02a322eedc731e21dR72)

**Comment by alexbruy** [comment]
See #29504 and #38650. Looks like you are using feature based algorithm (which creates a new output) instead of old one (which alters input vector).

**Comment by PedroVenancio** [comment]
Hi @m-kuhn 

I understand the move and it makes sense. However, in this particular case, old Zonal Statistics behaviour was very useful. So keeping both algorithms (old and feature based) could make sense I believe. As far as I can understand, the old one is not available from GUI flagged as deprecated, right?

**Comment by m-kuhn** [comment]
I think so. Yes.
You could create a wrapper model to make it available.

**Comment by PedroVenancio** [comment]
It works @m-kuhn 

![imagem](https://user-images.githubusercontent.com/1331581/100679586-b66a4d00-3367-11eb-9df0-4c55b6ae438d.png)

But I still tend to think that native:zonalstatistics could be available out-of-the-box in Processing GUI, as it covers some specific use cases.

**Comment by gioman** [comment]
> But I still tend to think that native:zonalstatistics could be available out-of-the-box in Processing GUI, as it covers some specific use cases.

I agree with @PedroVenancio 

@PedroVenancio @m-kuhn should we open a feature request?

**Comment by m-kuhn** [comment]
Please do

**Comment by gioman** [comment]
> Please do

done https://github.com/qgis/QGIS/issues/40400
