### ISSUE TITLE
Empty Relation Editor should show no child-form instead of empty child-form

### ISSUE THREAD

**Issue by signedav** [qgis/QGIS#40351]
When having a feature's relation editor displayed with no child features, the child form is displayed empty (with NULL values).  
![relationeditor_02](https://user-images.githubusercontent.com/28384354/100605915-efbfa000-3308-11eb-8d62-8bbdf3bb1540.png)

This leads to confusion (especially when the user is creating a new parent feature) - sometimes the user assumes that an empty child is created as well.

Not sure if this should be labeled as a bug or as a feature request.

**QGIS and OS versions**
OS: Windows 10 and Ubuntu 20.04
QGIS: Master and 3.16

**Comment by 3nids** [comment]
This has been fixed by #42906
