### ISSUE TITLE
Identifiable option in Project Properties is not working anymore

### ISSUE THREAD

**Issue by PedroVenancio** [qgis/QGIS#40357]
Identifiable option in Project Properties -> Data Sources is not working both on QGIS 3.10.12 and 3.16.1.

To reproduce, you can use the project inside this GPKG: https://github.com/timlinux/QGIS/files/5613089/CasteloBranco.zip

![imagem](https://user-images.githubusercontent.com/1331581/100623440-15a17080-331a-11eb-9d7f-32008146b561.png)

I was trying to make "dashboard" layer unidentifiable, but the option seems to be broken and I still can Identify those features. 

The same happens with Searchable option, that is, I still can locate the layer in the locator widget.

**Comment by roya0045** [comment]
@gioman I'm curious to know if the High Priority tag is of any use. 

The check is still in the code, https://github.com/qgis/QGIS/blob/93f9ec2f79f9cdbeaa237c3d6407766a3ec13189/src/gui/qgsmaptoolidentify.cpp#L174

I'm unsure if the flag is not set/saved somehow?

**Comment by gioman** [comment]
> I'm curious to know if the High Priority tag is of any use

I use it for regressions and issues causing crash and data corruption. Maybe this type of tickets are not all tagged as "high priority" but I'm in the process of reviewing all tickets, so they will be sooner or later.

**Comment by roya0045** [comment]
I'll try to see what might be the issue.
