### ISSUE TITLE
PYTHONPATH does not appear to be updated in minor version changes

### ISSUE THREAD

**Issue by janhec** [qgis/QGIS#40352]
After updating from 3.10 through 3.16 I found PYTHONPATH C:\Program Files\QGIS 3.10\apps\Python37\Scripts, which in my case impeded gdal_merge. After updating through options->system to C:\Program Files\QGIS 3.16\apps\Python37\Scripts, gdal_merge worked again.

**Comment by gioman** [comment]
@janhec have you set that variable manually?

as far as I can see that variable is set on QGIS start, and is read-only (here  below examples for 3.10 and 3.16 installed on the same machine):

![Screenshot_20201130_131424](https://user-images.githubusercontent.com/1951107/100614495-22b86280-330e-11eb-901b-47ec9a3dbc31.png)

![Screenshot_20201130_131446](https://user-images.githubusercontent.com/1951107/100614514-28ae4380-330e-11eb-92df-ded3b7888b1a.png)

**Comment by janhec** [comment]
I see what you mean. I don't recall selecting "Use custom variables", but
that is why, as you suggested.
Sorry for the bother, I think we can close this one. I have unselected the
option now.
Thanks,
Jan
[image: image.png]
