### ISSUE TITLE
Layer list of a WMS connection is not refreshed in browser

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#40350]
See https://github.com/qgis/QGIS/issues/39476#issuecomment-734899713

Create a WMS connection

Connect with browser > user see the list of layers

Modify the WMS service (i.e. add a new layer)

Try refresh the connection in browser > new layer do not show

Go to "Add WMS layer" and connect to service

Return to browser and refresh > new layer shows up

Tested on 3.10 and 3.16 on Windows and Linux.

**Comment by Samweli** [comment]
@gioman I'm not able to reproduce this on QGIS 3.16.1, the refresh on WMS connection works as expected.

**Comment by gioman** [comment]
@Samweli see below (using QGIS Server as example):

![Peek 2020-12-01 11-11](https://user-images.githubusercontent.com/1951107/100733387-0415a280-33c6-11eb-9dc5-d250e9a84ccc.gif)

**Comment by alexandreleroux** [comment]
Same for me, on macOS with QGIS 3.16.0, right clicking on a WMS connection from the browser panel and selecting "Refresh" does not refresh the corresponding WMS GetCapabilities.

**Comment by Samweli** [comment]
ok @gioman and @alexandreleroux will take a look and get back.

**Comment by pathmapper** [comment]
https://github.com/qgis/QGIS/issues/25545 could be duplicate/related.

**Comment by rduivenvoorde** [comment]
Just to be sure: are we sure that QGIS is NOT requesting the new capabilities?

I ask because I know that when you run QGISserver as fastcgi, I think you have to restart apache to reflect configuration parameters...

And a little test with a local Geoserver running: I see that QGIS with EVERY push on the button is requesting new capabilities, no caching involved.

**Comment by dncpax** [comment]
Just stumbled on this today... I noticed that even deleting the entry, and recreating with same name and url it does not refresh the cap doc. You still don't see new layers in the service. If you use a differente name it works fine.

**Comment by gioman** [comment]
> Just stumbled on this today... I noticed that even deleting the entry, and recreating with same name and url it does not refresh the cap doc. You still don't see new layers in the service. If you use a differente name it works fine.

@dncpax 3.20?

**Comment by dncpax** [comment]
@gioman sorry, it's 3.16...
