### ISSUE TITLE
[Processing] "Remove duplicate vertices" creates a corrupted layer if tolerance threshold would delete a ring

### ISSUE THREAD

**Issue by nicogodet** [qgis/QGIS#40361]
**Describe the bug**

I use "Remove duplicate vertices" to simplify a layer.
I set the Tolerance to 20 m for example.

Output layer is fully bugged.

Input
![image](https://user-images.githubusercontent.com/39594821/100644575-c9672800-333b-11eb-95fd-55d5882def4c.png)

Output:
![image](https://user-images.githubusercontent.com/39594821/100644598-d257f980-333b-11eb-868c-de4603d2d9aa.png)
DUH no issue here you would say !

Try to identify features:
![image](https://user-images.githubusercontent.com/39594821/100644697-f3204f00-333b-11eb-88f7-8591092dda5f.png)
No feature here !
Canvas is correctly painted.

Instead of a temporary layer, let's create a output file.
![image](https://user-images.githubusercontent.com/39594821/100644872-2bc02880-333c-11eb-8ff9-6e11c3b574d2.png)
DUH no issue here you would say !

If i zoom in:
![image](https://user-images.githubusercontent.com/39594821/100644901-3a0e4480-333c-11eb-8a19-6d0d7b1a112f.png)
It only shows features that I can identify
Attribute table is fully populated.

**How to Reproduce**

Sample file : [shape.zip](https://github.com/qgis/QGIS/files/5617658/shape.zip)
I joined the output file from above (notice .cpg is missing !)

1. Load sample file named shape.shp from zip.
2. Delete duplicate vertices with tolerance set to 20m.
3. Try to identify a feature, try to export the temp layer (output will not contain all displayed feature.

I also tried to "Repare the geometry" before delete duplicate vertices -> same output
"Check validity" on shape.shp with GEOS is perfectly fine (no error). I tried to "Remove duplicate vertices" on the valid output of "Check validity" but without success.

It seems that this issue happens when tolerance is high enougth to "delete" a ring.
Default tolerance create a valid output.
Increasing tolerance creates a corrupted output.

**QGIS and OS versions**
Tested on Qgis 3.16.1 OsGeo4W fresh new profile.

**Additional context**
shape.shp is the output of https://github.com/nicogodet/PostTelemac/blob/clean-and-drop-Qgis2/PostTelemac/meshlayertools/toshape/posttelemac_util_extractshp.py
As "repare geometry" and "check validity" don't report any error, I consider this output as a valid layer.

**Comment by nicogodet** [comment]
[scratch.zip](https://github.com/qgis/QGIS/files/5618485/scratch.zip)

Layer made from scratch, issue can be reproduce.
![image](https://user-images.githubusercontent.com/39594821/100659931-9def3800-3351-11eb-9aaa-e71f8f2cc960.png)

Execute the alg on scratch.shp with a tolerance of 50m and see what happens for the 2 ring framed in red.
![image](https://user-images.githubusercontent.com/39594821/100660203-f8889400-3351-11eb-8de3-872c98a07000.png)

The feature is painted on canvas but I can't interact with it.

**Comment by andreasneumann** [comment]
Thank you @nicogodet  for reporting this issue.

But it is kind of a "misuse" of algorithm. To simplify geometry you don't use the "remove duplicate vertices" - there are other specialized algorithms available for simplification.

If you use extreme tolerance values you can also expect garbage results.

I am not claiming that the "remove duplicate vertices" works correctly in all situations, but I would recommend you to use other algorithms for feature simplification.

**Comment by nicogodet** [comment]
@andreasneumann I always forget "Simplify"... I'm not really satisfied with this alg.
For now, v.clean with a large tolerance and minimal area gives the best result to reduce the number of vertex without loosing the global geometry.

**Comment by gioman** [comment]
> @andreasneumann I always forget "Simplify"... I'm not really satisfied with this alg.
> For now, v.clean with a large tolerance and minimal area gives the best result to reduce the number of vertex without loosing the global geometry.

@nicogodet the tool you are looking for is (GRASS's) v.generalize, which is **very** powerful and do not spoils the topology of your layer (as GRASS is fully topological).

**Comment by gioman** [comment]
> @nicogodet the tool you are looking for is (GRASS's) v.generalize, which is **very** powerful and do not spoils the topology of your layer (as GRASS is fully topological).

@nicogodet and by the way... when using GRASS tools in Processing the layers are also cleaned...

**Comment by nicogodet** [comment]
Thanks @gioman !

Regarding the initial issue, I will let you decide if you want to close it or let it open.

**Comment by gioman** [comment]
> Regarding the initial issue, I will let you decide if you want to close it or let it open.

I think I'll close it as the remove duplicate vertices is anyway not the right tool to simplify/generalize vectors.
