### ISSUE TITLE
Categorized Symbology doesn't work anymore

### ISSUE THREAD

**Issue by marple2go** [qgis/QGIS#40379]
In the previous version you could generate a tree of seperated categories which would appear in de Legend of Layers, when you choose Classifying on Categories in the Symbology-tab in Layer-properties.
In v.3.16.1 all attemps to classify the Values result in one Symbol with a Value-description "All other values".
![Knipsel](https://user-images.githubusercontent.com/70636770/100730896-f57dba00-33ca-11eb-9f5c-1a9945c5db48.JPG)

**Comment by gioman** [comment]
@marple2go can't confirm here, works as expected on 3.16.1 on Windows and Linux. Please attach your data.

**Comment by marple2go** [comment]
Well, i think this issues can be closed. There's something in my used sources. Older and new initiated projects are working right. Afterwards,  I was too quick to post this message,
