### ISSUE TITLE
Can we set shortcuts for actions on the attribute table toolbar?

### ISSUE THREAD

**Issue by donkeychen** [qgis/QGIS#40387]
hi,
Even if #29633 was closed, it was perhaps the similar issue on 3.16.1
For example:
I set the following shortcuts 
"Toggle Editing" : E
"Select Features by Expression…" : CTRL+F
"Set layer Edits" : CTRL+S    (I override the original setting)

There was two layers added to the project, and the attribute table was set "dock" 
By selecting layer A to make it active. Press F6, and the attribute table of layer A is docking now.
I use "E" to toggle editing on layer A, and the attribute table of layer A is toggled to editing mode too.
I can use "CTRL+E" to toggle it, because the action of the attribute toolbar is "toggle editing mode"
If I selecting another layer, B, in the layers panel,
"E" can "toggle edit" (layer B) and "CTRL+E" "toggle editing mode" (layer A) now.

however, the actions of attribute table toolbar is (or not) ambiguous is depend on if the user set the same shortcuts to the default shortcuts (which are undefinable by user).
The "Set layer Edits" and "save edits" are "CTRL+S" for me fortunately, but "CTRL+S" for other users maybe ambiguous.
My "Select Features by Expression…" and "Select/Filter features using form" are ambiguous now.

May users set the shortcuts of the toolbar on attribute table?
The actions were not listed in "keyboard shortcuts" setting interface, we can't override the default shortcuts of it.

**Comment by gioman** [comment]
@donkeychen is this a bug report? a feature request? else?

**Comment by donkeychen** [comment]
@gioman 
I don't know how to define it. I know the shortcuts operation, it did make sense.
However, the default predefined shortcuts of the attribute table is not listed on the setting menu.
Even if I checked all listed shortcuts for confirming that there is no duplicated shortcut defined, the ambiguous definitions are still hidden somewhere.

**Comment by gioman** [comment]
@donkeychen I cannot understand your description, but may be its just me. Maybe others will understand it just fine.

**Comment by gioman** [comment]
@donkeychen anyway if this is a question, then you should post it on the users mailing lists, not here.

**Comment by DelazJ** [comment]
I understand that there are some default shortcuts in QGIS (eg, some of the attribute table's?) that are not available in Settings --> Configure shortcuts dialog, so that @donkeychen could customize them at will.

**Comment by donkeychen** [comment]
@DelazJ 
Yes, 
The "Actions" listed in [Settings][keyboard shortcuts] are actions of toolbar(s) of main window. --- Term 1
The "Actions" of toolbar of the attribute table is not listed. --- Term 2.
I feel that the "predefined/default" shortcuts for Term 2. will make users define ambiguous shortcuts.
Since Term 2 are named as different one, why not list then in the dialog?

(My OS is windows 10, I don't know if these behavior are same on other platform.)

**Comment by gioman** [comment]
@donkeychen this is a good example of something that should be moved to https://github.com/qgis/QGIS/discussions agree?

**Comment by donkeychen** [comment]
@gioman, agree :)
