### ISSUE TITLE
Delimited text provider add layer dialog always adds a non spatial table

### ISSUE THREAD

**Issue by m-kuhn** [qgis/QGIS#40383]
1. Add a delimited text layer with X and Y field
2. A table without geometry is added

QGIS Master

**Comment by m-kuhn** [comment]
Likely introduced by 1132494fcb679e814857d5cf7fa4f1712b52f5e1 (https://github.com/qgis/QGIS/pull/39656) and the delimited text encodeUri / decodeUri methods not preserving all information.

**Comment by nirvn** [comment]
Very weird. I just did this a few days ago and it worked just fine.

**Comment by m-kuhn** [comment]
@nirvn I'm on it, wait an hour or two before loosing too much time here

**Comment by m-kuhn** [comment]
I was working on an old branch by accident.
