### ISSUE TITLE
Decoration : Automatic angle of Nord arrow is wrong

### ISSUE THREAD

**Issue by GlaDal** [qgis/QGIS#40394]
When I toggle automatic option for the angle of my north arrow - an SVG from Qgis repository (in the decoration on the canvas), it rotates in a false direction. My project don't have any rotation (default parameter in the status bar is 0°).

Go to "View"-Decorations-North Arrow
Activate 'north arrow'
Select a new SVG 
Check 'automatic'
Click on 'OK'
The arrow is not well oriented.

Version : 3.16 on Windows 10

**Comment by gioman** [comment]
@GlaDal this ticket is uncomplete, please add all the requested infos.



**Describe the bug**


**How to Reproduce**



1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error -->

**QGIS and OS versions**



**Additional context**

**Comment by roya0045** [comment]
Arrow should orient to the north of the map projection. This ticket doesn't prove that the current behavior is wrong in any way.
