### ISSUE TITLE
QGIS crashes with "Open Existing Model..." from processing toolbox or "Edit Model..." from QGIS browser

### ISSUE THREAD

**Issue by pathmapper** [qgis/QGIS#40397]
**Describe the bug**
QGIS crashes with `Open Existing Model...` from processing toolbox or `Edit Model...` from QGIS browser.

**How to Reproduce**

1. Open the following model from the processing toolbox with `Open Existing Model...` or open the contextmenu of the model in QGIS browser and choose `Edit Model...` :
[QGIS_model_crash.zip](https://github.com/qgis/QGIS/files/5629589/QGIS_model_crash.zip)

2. See error --> QGIS crashes

**QGIS and OS versions**

QGIS version | 3.16.1-Hannover | QGIS code revision | b381a90dca
-- | -- | -- | --
Compiled against Qt | 5.11.3 | Running against Qt | 5.11.3
Compiled against GDAL/OGR | 2.4.0 | Running against GDAL/OGR | 2.4.0
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.27.2 | Running against SQLite | 3.27.2
PostgreSQL Client Version | 11.9 (Debian 11.9-0+deb10u1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.10.4
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Debian GNU/Linux 10 (buster)
Active python plugins | ClipMultipleLayers; quick_map_services; scriptrunner3; LAStools; canvas_clipper; savedialog; loadthemall; clipper; kmltools; qgis-maptiler-plugin; MapsPrinter; Discovery; mmqgis; pluginbuilder3; vector_tiles_reader; layerGroupFilter; plugin_reloader; realcentroid; mask; MetaSearch; db_manager; processing

**Additional context**

- The model was created using the QGIS model builder and QGIS crashed when the model was run from the model builder.
- From QGIS browser the model could be run.

**Comment by gioman** [comment]
@pathmapper no crash here on 3.16.1 on Ubuntu 20.04 and Windows 10. Please try with a new QGIS profile.

**Comment by pathmapper** [comment]
@gioman thanks, don't know what happened but it's not crashing anymore (with the same profile).
