### ISSUE TITLE
QGIS Server (Windows) doesn't support UNC path names in Geopackage map URIs

### ISSUE THREAD

**Issue by cxcandid** [qgis/QGIS#40396]
Playing around with QGIS Server 3.16.1-1 in Windows 2016, I managed to use Geopackage URIs in WMS URLs successfully:
`http://myserver:8080/qgis/qgis_mapserv.fcgi?map=geopackage:C:%5CData%5CQGIS%5Ctest.gpkg?projectName%3Dtest`

Unfortunately, it won't work if I use UNC path names to specify the map:
`http://myserver:8080/qgis/qgis_mapserv.fcgi?map=geopackage:%5C%5Cmypc%5Cqgis%5Ctest.gpkg?projectName%3Dtest`

Using UNC paths with *.qgz map sources works like a charm:
`http://myserver:8080/qgis/qgis_mapserv.fcgi?map=geopackage:%5C%5Cmypc%5Cqgis%5Ctest.qgz`

It seems to me that QGIS Server doesn't honor UNC path names in geopackage URIs.

**Comment by elpaso** [comment]
I'd say won't fix.
