### ISSUE TITLE
ArcGIS Feature Server documentation

### ISSUE THREAD

**Issue by cefect** [qgis/QGIS#40406]
Some sort of API documentation for QgsVectorLayer access to a ArcGIS Feature Server (providerLib='arcgisfeatureserver') would be very helpful.

Currently, the user is left to guess which parameters this provider accepts.  For example, 'filter' seems to be included but is not working ([issue  27635)](https://github.com/qgis/QGIS/issues/27635)

**Comment by elpaso** [comment]
Wrong repo? https://github.com/qgis/QGIS-Documentation/
