### ISSUE TITLE
Feature count is wrong in Processing output

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#40408]
On 3.16 seems ok.

On 3.10: run a processing tool that outputs a vector, and choose the "save as geopackage" option. If the layer is added to the project and the feature count activated, the count is 0.

Tested on Windows 10 and Ubuntu 20.04.

**Comment by nyalldawson** [comment]
I fixed this for 3.16, but the changes required were very intrusive and not suitable for backporting to 3.10. I think this is a "wontfix".

**Comment by gioman** [comment]
Ok, now you say this I kind of recall another ticket on this matter... sorry for the noise.
