### ISSUE TITLE
WMS provider: crash when drawing canvas in event loop

### ISSUE THREAD

**Issue by roya0045** [qgis/QGIS#40409]
Crash occured when browing are then map, on win 10 QGIS3.16.1

Seems related to a 'heavy' project causing timeout. 

Crash ID: 81a63d091fb0660bae4e33070582aa5d7ff1c22a

Stack Trace

QCoreApplication::notifyInternal2 :
QEventDispatcherWin32Private::sendTimerEvent :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
QEventLoop::exec :
QgsWmsProvider::draw qgswmsprovider.cpp:974
QgsWmsProvider::readBlock qgswmsprovider.cpp:996
QgsRasterDataProvider::block qgsrasterdataprovider.cpp:212
QgsSingleBandColorDataRenderer::block qgssinglebandcolordatarenderer.cpp:62
QgsBrightnessContrastFilter::block qgsbrightnesscontrastfilter.cpp:119
QgsHueSaturationFilter::block qgshuesaturationfilter.cpp:123
QgsRasterResampleFilter::block qgsrasterresamplefilter.cpp:164
QgsRasterProjector::block qgsrasterprojector.cpp:890
QgsRasterIterator::readNextRasterPartInternal qgsrasteriterator.cpp:130
QgsRasterDrawer::draw qgsrasterdrawer.cpp:60
QgsRasterLayerRenderer::render qgsrasterlayerrenderer.cpp:321
QgsMapRendererCustomPainterJob::doRender qgsmaprenderercustompainterjob.cpp:319
QgsMapRendererCustomPainterJob::staticRender qgsmaprenderercustompainterjob.cpp:267
QtConcurrent::RunFunctionTask::run qtconcurrentrunbase.h:136
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

**Comment by roya0045** [comment]
Possibly cause by tiny residual lines (1.x e-07 and e-11 lines). These tiny geometry seemed to prevent proper rendering and crash everything due to the rendering delays.

**Comment by alexbruy** [comment]
Is this still true?

**Comment by roya0045** [comment]
Haven't encountered as far as I remember, or the stack trace didn't show up at least. Will close for now.
