### ISSUE TITLE
qgis pluggin not detecting python support on fedora 32

### ISSUE THREAD

**Issue by hob814** [qgis/QGIS#40419]
![Screenshot from 2020-11-23 03-28-39](https://user-images.githubusercontent.com/70345092/101008737-b5990d00-3559-11eb-9335-26d18273c725.png)

**Describe the bug**

**How to Reproduce**

after downloading qgis there was an error shows up about not detecting python after some trying to fix it the error stopped but still I cant download plugins and this error states.
i got python  3.8.6
qgis  3.16.1

**QGIS and OS versions**

**Additional context**

**Comment by gioman** [comment]
@hob814 you must fix your python python3-qgis installation.

**Comment by hob814** [comment]
@gioman at least I know where to start now, but how do I know what is the problem with python3-qgis. should I delete it then install it again because I already did that and it didn't help

**Comment by hob814** [comment]
now after downloading python3-qgis using the code:
`sudo dnf copr enable dani/qgis-testing sudo dnf install python3-qgis`
It still doesn't work a new problem appeared
![Screenshot from 2020-12-03 16-52-02](https://user-images.githubusercontent.com/70345092/101061172-1c351f80-3588-11eb-87aa-0079400d215c.png)
![Screenshot from 2020-12-03 16-49-41](https://user-images.githubusercontent.com/70345092/101061188-1fc8a680-3588-11eb-96ba-7cdf714f8c2d.png)

**Comment by gioman** [comment]
@hob814 

```
sudo dnf copr enable dani/qgis
sudo dnf install qgis python3-qgis qgis-grass
```

on Fedora 33, no problems whatsoever.

**Comment by loleg** [comment]
Thanks @gioman that worked for me even without the `copr` line.

It might help to add a note to https://apps.fedoraproject.org/packages/qgis
