### ISSUE TITLE
Keyboard shortcuts not working in Toggle Map Only mode

### ISSUE THREAD

**Issue by uclaros** [qgis/QGIS#40424]
**Describe the bug**
When enabling the *Map Only* mode by *Settings > Toggle Map Only* (ctrl+shift+tab), keyboard shortcuts stop working (except for space and arrow keys). 

**QGIS and OS versions**
5c87f705 on debian testing

**Additional context**
An easier *switch back to normal* shortcut (esc?) would also be nice in case one forgets the assigned one!

**Comment by Pedro-Murteira** [comment]
Still partialy valid on QGIS 3.22.3. Apart from the arrow keys and space bar, "ctrl +1", "ctrl+2", etc etc, can be used aswell.

**Comment by rgc03** [comment]
I have the same bug with QGIS 3.22.5 (Windows 10).
It would be nice to have this problem solved
Thank you

**Comment by SavelevGeo** [comment]
Issue still remains,
QGIS version
3.24.2-Tisler
QGIS code revision
13c1a028
