### ISSUE TITLE
Disable JPEG lossy compression on Byte data type when exporting raster to a geopackage

### ISSUE THREAD

**Issue by NicolasCadieux** [qgis/QGIS#40425]
**Feature description.**
GeoPackage raster original aim was initially for visualisation purposes.  Thus, for Byte input, the default tile format uses JPEG lossy compression  (https://gdal.org/drivers/raster/gpkg.html#tile-formats). Therefore, when one exports a 8 bit single band tiff, the created tile in the GeoPackage is a 4 band lossy compressed raster (Identical RGB plus an opaque channel).  This is particularly problematic for classification data or any data that needs to stored using lossless compression (DEM, hyper spectral Data... (basically anything that is not just a pretty picture).

**Additional context**
On 8bit data, using the "-ot Int16" switch seems to solve the problem but Even Rouault suggest using the  "-co TILE_FORMAT=PNG" to activate the lossless compression. Any raster file export that automatically uses lossy compression should be changed to a lossless compression unless the user is explicitly told before hand, that their data will change because of the lossy compression.

Cheers!
Nicolas Cadieux

**Comment by luipir** [comment]
yes please... just faced now this problem

**Comment by NicolasCadieux** [comment]
"-co TILE_FORMAT=PNG". See above.

**Comment by Llaves** [comment]
from the QGIS layer export dialog, you can add these parameters as

![tile_format](https://user-images.githubusercontent.com/6778818/191990868-42f1134c-51db-4743-9e27-c8da141ffdda.png)

**Comment by rouault** [comment]
In GDAL 3.6, 1-band Byte GPKG rasters will default to PNG compression: https://github.com/OSGeo/gdal/pull/6425
