### ISSUE TITLE
User-submitted layer name field in WMS add layer dialog is never reset once modified

### ISSUE THREAD

**Issue by landryb** [qgis/QGIS#40421]
**Describe the bug**
User-submitted layer name field  in WMS add layer dialog is never reset once modified

**How to Reproduce**

Go to add wms layer (ctrl-shift-w), connect to a server, select a layer, the 'layer name' field at the bottom of the dialog is filled with the layer name from the selected layer. Select another layer, the field is updated with the layer name from the newly selected layer.

For some reason you don't like the layer name from the server and decide to put 'my nice layer name' in the field.

From that point, selecting another layer will never reset the 'layer name' field at the bottom of the dialog.

- even after connecting to another server
- even after closing and reopening the dialog

there will always be 'my nice layer name' in the field, so one manually needs to update it everytime a layer is added.

**QGIS and OS versions**

3.16.1 on OpenBSD, but has been happening since forever

**Additional context**

**Comment by elpaso** [comment]
@landryb the fix is trivial but I wonder what was intention of the developer who implemented the current behavior. 

I can see a use case for that: imagine that I wanted to add several layers and I wanted to override the names of all the layers using a common suffix.

In that case I would like to keep my last entered name for further modifications of the names for the layers I will add next.

Does it make sense?

@jef-n do you have any memories about this?

**Comment by landryb** [comment]
if that's real, then that usecase seem .. convoluted, and imo this shouldnt be the default :)

**Comment by landryb** [comment]
oh no, not those stupid bots again.

**Comment by gioman** [comment]
> oh no, not those stupid bots again.

@landryb why? it was not activated to bother people, but to try keep our bug queue clean. If the issue in not stale we will remove the feedback label, as in this case.

**Comment by landryb** [comment]
from experience, bugs marked as stale tend to be closed, while here i think it *is* a bug, whether or not someone replies on it...

from my understanding the feedback flag is for devs only who can comment on issues, so i cant remove it myself. thanks for removing it !

**Comment by gioman** [comment]
> from experience, bugs marked as stale tend to be closed, while here i think it _is_ a bug, whether or not someone replies on it...

@landryb we will be watching the stale tickets, and acts when necessary to remove this label as also the feedback one.

**Comment by Pedro-Murteira** [comment]
This is still true on QGIS 3.16.14 and 3.22.1., although this is a minor inconvenience and there are workarounds. (changing the layer name on it's properties or changing the layer name individualy before adding to the layer panel)

**Comment by alexbruy** [comment]
Duplicates #28858
