### ISSUE TITLE
RuntimeError: wrapped C/C++ object of type RasterizeStringAlgorithm has been deleted

### ISSUE THREAD

**Issue by belliniAndre** [qgis/QGIS#40423]
For me everything was fine, as it has always been with QGIS, since version 2.8. I installed version 3.10.12 (LTR), and I needed to change the SRC settings to run a custom system, and I received this error, and I received this same error when trying to enable TAUDEM and OTB, this happens whenever I conclude with "OK " the operation.
Um erro ocorreu enquanto executava o código Python:

RuntimeError: wrapped C/C++ object of type RasterizeStringAlgorithm has been deleted
Traceback (most recent call last):
  File "C:/Users/belli/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\rasterizestring\rasterize_string_provider.py", line 60, in loadAlgorithms
    self.addAlgorithm( alg )
RuntimeError: wrapped C/C++ object of type RasterizeStringAlgorithm has been deleted
Versão do Python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]
Versão do QGIS: 3.10.11-A Coruña A Coruña, d2171173e4
Caminho do Python:
·                     C:/Users/belli/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\rasterizestring
·                     C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python
·                     C:/Users/belli/AppData/Roaming/QGIS/QGIS3\profiles\default/python
·                     C:/Users/belli/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
·                     C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python/plugins
·                     C:\PROGRA~1\QGIS3~1.10\apps\Python37
·                     C:\PROGRA~1\QGIS3~1.10\apps\Python37\Scripts
·                     C:\Program Files\QGIS 3.10\bin\python37.zip
·                     C:\PROGRA~1\QGIS3~1.10\apps\Python37\DLLs
·                     C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib
·                     C:\Program Files\QGIS 3.10\bin
·                     C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages
·                     C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32
·                     C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32\lib
·                     C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\Pythonwin
·                     C:/Users/belli/AppData/Roaming/QGIS/QGIS3\profiles\default/python
·                     C:\Users\belli\AppData\Local\acatama\python37
·                     C:\Users\belli\AppData\Local\acatama\python37\lib\site-packages
·                     C:\Users\belli\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools
·                     C:\Users\belli\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools
·                     C:\Users\belli\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DsgTools
·                     C:\Users\belli\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DSGTools_Op\auxiliar
·                     C:\Users\belli\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DSGTools_Op\QuickGeocoder\dependencies
·                     C:\Users\belli\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms
·                     C:/Users/belli/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web
C:\Users\belli\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins

SO WINDOWS 10 64Bits

Peço Desculpas, caso tenha feito algo errado, iniciante aqui no github

**Comment by jef-n** [comment]
Plugin issue - please report to the plugins bug tracker.

**Comment by belliniAndre** [comment]
Apparently I won't even be able to make myself understood. Because at no point in the message did he say the Problem is a Plugin. I said the problem in some situations. Nevermind ......! I already gave up. The thing is to take a break at Qgis yourself, do what. 6 years on the road with Qgis. Two years of struggle for my University to adopt some practices in Qgis went down the drain. Thanks.

**Comment by gioman** [comment]
> Because at no point in the message did he say the Problem is a Plugin

@belliniAndre 
`
File "C:/Users/belli/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\rasterizestring\rasterize_string_provider.py", line 60, in loadAlgorithms`
