### ISSUE TITLE
Crash ID: f493eb4f2ddf8c0a9a16c8f5c0b6a2a14e25f4af

### ISSUE THREAD

**Issue by Rahua85** [qgis/QGIS#40430]
Stack Trace

QListData::begin :
QgsMessageBar::popWidget :
QgsMessageBarItem::urlClicked :
QMetaObject::activate :
QTextBrowser::~QTextBrowser :
QMetaObject::activate :
QWidgetTextControl::acceptRichText :
QWidgetTextControl::modificationChanged :
QWidgetTextControl::processEvent :
QWidgetTextControl::processEvent :
QTextEdit::selectionChanged :
QTextEdit::mouseReleaseEvent :
QWidget::event :
QFrame::event :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.14.16-Pi
QGIS code revision: df27394552
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by DelazJ** [comment]
@Rahua85 You need to explain what you were doing when the crash occurred and please upgrade to 3.16.1. The 3.14 version is no longer maintained.

**Comment by gioman** [comment]
Closing for lack of feedback.
