### ISSUE TITLE
Sieve Feature - Can't get to work, says it can't find the original file but it is there saved! 

### ISSUE THREAD

**Issue by CSP1293** [qgis/QGIS#40445]
Trying to use the sieve function on a mapping exercise.

Have narrowed down multiple areas on a map and trying to sieve them to the area with 10 of more pixels but it keeps coming up saying it can't find the file it's sieved from. No-one else in my group is having this problem and we are doing the exact same thing!!! 
I am going mental i've done it a few times and still the same problem.

PLEASE HELP ME 

![Picture1](https://user-images.githubusercontent.com/75481512/101161111-fb240b80-3627-11eb-8f31-83d985380893.png)

**Comment by gioman** [comment]
See https://github.com/qgis/QGIS/issues/new/choose use the QGIS users mailing list for questions https://qgis.org/en/site/forusers/support.html
