### ISSUE TITLE
QGIS forward declaration of nlohmann/json breaks other libs that depend on json

### ISSUE THREAD

**Issue by dirtshell** [qgis/QGIS#40441]
**Describe the bug**
I have a C++ Qt application I am developing that uses QGIS for a map display. I am also using another lib in this application. Both this custom lib and QGIS use nlohmann/json for JSON serialization. If I try to build my project with both QGIS and my custom lib, I get a bunch of `function redefined` compilation errors. They look like this:

```
In file included from [REDACTED]
/usr/include/nlohmann/json.hpp:911:8: error: redefinition of default argument for ‘class<template-parameter-1-1>’
 struct adl_serializer
        ^~~~~~~~~~~~~~
In file included from /usr/include/qgis/qgsabstractgeometry.h:29:0,
                 from /usr/include/qgis/qgsgeometry.h:34,
                 from /usr/include/qgis/qgsfeature.h:574,
                 from /usr/include/qgis/qgsexpressioncontext.h:26,
                 from /usr/include/qgis/qgsrendercontext.h:28,
                 from /usr/include/qgis/qgssymbol.h:25,
                 from /usr/include/qgis/qgsannotation.h:25,
                 from /usr/include/qgis/qgssvgannotation.h:21,
                 from [REDACTED]/mainwindow.cpp:18:
/usr/include/qgis/json_fwd.hpp:24:10: note: original definition appeared here
 template<typename T = void, typename SFINAE = void>
```

I can fix this issue by not including QGIS or my other lib. But not both.

**How to Reproduce**

Sorry busy right now, will update with an example. 

**QGIS and OS versions**

3.16 dev files from the Ubuntu repos, Ubuntu 18.04

**Additional context**

From the looks of it, this issue is caused in `json_fwd.hpp` and the fact that it mirrors the `nlohmann` namespace to override some behavior. I am not sure how to fix this though.

**Comment by nyalldawson** [comment]
I suggest you fix it by manually renaming the classes in the other version you include

**Comment by dirtshell** [comment]
Maybe I am misunderstanding, but I don't think its an issue with any of my class names. The error is thrown from the include. In my custom lib I am `#include <nlohmann/json>`ing the JSON library. This #include is including `json.h` with all of its declarations. And when I include QGIS, that includes the `json_fwd` from QGIS's includes and that attempts to reinclude `json.h`. I am not sure how this works. 

Part of the problem may also be that I am now also including the nlohmann JSON libs from my system now?

Regardless, for now I managed to work around the issue by checking if the macro variable `INCLUDE_NLOHMANN_JSON_FWD_HPP` has been defined. Here is how I use it in the header in my custom lib.

```
#include foo
#include bar
#include my_other_lib 
// Handles namespace conflict with QGIS's inclusion of nlohmann/json
#ifndef INCLUDE_NLOHMANN_JSON_FWD_HPP_
    #include <nlohmann/json.hpp>
#endif

// the rest of your code
```

**Comment by gioman** [comment]
@dirtshell shouldn't this be asked in the developers mailing list rather than assuming that is a QGIS bug?
