### ISSUE TITLE
Refactoring fails when making data layers permanent 

### ISSUE THREAD

**Issue by xz310** [qgis/QGIS#40446]
Hi, I'm in QGIS 3.10.11 (Windows). I've got some troubles with data refactoring. 

I started by importing a csv. file from my desktop, and since data were recognised as texts (string data) in the attribute table , I went for refactoring. 

![image](https://user-images.githubusercontent.com/74983277/101159470-c1560380-362d-11eb-8462-946c05066697.png)

I changed data to numerical ones (Interger 64 for whole numbers, Double for decimal numbers) in the refactoring window, 

![image](https://user-images.githubusercontent.com/74983277/101160455-59082180-362f-11eb-8252-db65928acf56.png)

but upon saving the file as a seperate csv. file the data became texts (string data) again. 

![image](https://user-images.githubusercontent.com/74983277/101160740-d59b0000-362f-11eb-918b-3978a1660404.png)

When I left the layer as a temporary layer I got exactly what I want. 

![image](https://user-images.githubusercontent.com/74983277/101160842-fcf1cd00-362f-11eb-8d57-062039dbcf02.png)

I also tried making temporary layer(s) and then making them permanent in the layer column. However, this brought me back to the csv layer with string data only. 

I hope this is clear, please help me. Thanks!

**Comment by gioman** [comment]
> I hope this is clear, please help me. Thanks!

CSV columns are always treated as text (unless you manually add a csvt file), while the temp file is a different format (gpkg) able to handle different datatypes.
