### ISSUE TITLE
Repeatedly getting "QGIS unexpectedly ended" on a project file

### ISSUE THREAD

**Issue by ygarb** [qgis/QGIS#40447]
## User Feedback

Hi,

I had a crash working in QGIS (trying to drag-drop load a SID file by mistake) and since then I cannot open the project I was working on.  I get a "successfully loaded" notice and then it goes into unresponsive for some time, and then an "Uh-oh" crash.  This occurs repeatedly, including when I turn off the "render" before loading the project.  It is a largish project that took me time to assemble, with a backup that is a bit old, so I am very eager to reload it without the offensive element that causes it to crash, or, at least, to salvage the information in it....

Thanks.

## Report Details

**Crash ID**: [b14ba659850dc58a0f00542dac47d15430563b27](https://github.com/qgis/QGIS/search?q=b14ba659850dc58a0f00542dac47d15430563b27&type=Issues)

**Stack Trace**
<pre>
WTFCrash :
WTF::ParkingLot::forEach :
WTF::ParkingLot::forEach :
RtlRunOnceExecuteOnce :
InitOnceExecuteOnce :
__crtInitOnceExecuteOnce winapisupp.cpp:225
WTF::ParkingLot::forEach :
WTF::ParkingLot::parkConditionally :
WTF::LockBase::lockSlow :
WTF::ParallelHelperPool::doSomeHelping :
WTF::createThread :
WTF::detachThread :
thread_start<unsigned int (__cdecl*)(void * __ptr64)> :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.14.16-Pi
QGIS code revision: df27394552
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by gioman** [comment]
>  QGIS Version: 3.14.16-Pi

@ygarb too old and unsupported, you must test with 3.16.1

**Comment by gioman** [comment]
You must also try with a new QGIS profile, no 3rd party plugins installed.

**Comment by ygarb** [comment]
Great, thanks for both suggestions and rapid (!) response.  Will upgrade to 3.16.1 and try with new QGIS profile.

Y


Prof. Yaakov Garb
Department of Sociology and Anthropology &
Department of Geography and Environmental Development

Ben Gurion University of the Negev
ygarb@bgu.ac.il<mailto:ygarb@bgu.ac.il>  |  https://bgu.academia.edu/yaakovGarb   |  +972-547-560-667   |  Skype: y-garb

**Comment by roya0045** [comment]
> WTFCrash :
WTF::ParkingLot::forEach :
WTF::ParkingLot::forEach :
RtlRunOnceExecuteOnce :
InitOnceExecuteOnce :
__crtInitOnceExecuteOnce winapisupp.cpp:225
WTF::ParkingLot::forEach :
WTF::ParkingLot::parkConditionally :
WTF::LockBase::lockSlow :
WTF::ParallelHelperPool::doSomeHelping :

This is clearly not coming from QGIS. The custom plugin/code is clearly the source of the crash.

**Comment by ygarb** [comment]
## User Feedback

OK, this worked, with a minor wrinkle.  Thanks!

I followed your advice and Updated to Hannover (3.16.1), and created a new profile only a plugins installed (am not sure how this subset was determined), which I disabled before loading the project file that crashed things last time.  It crashed again, and I pasted this report below.  **However**,  upon pressing restart, it loaded up with the new profile (with the small subset of plugins enabled) and the project all intact.  And it did so very much faster than what I am used to (so about 100 raster layers, though only a few rendered, and a dozen vector layers).   So, for now, I can breathe a sigh of relief on having a working system, and I will try activate/install plugins bit by bit to see where the problem lay/lies.  Thank you.

I will not close the report yet as I did get two things in the log messages

1. (C:/OSGEO4~1/apps/qgis/plugins/grassplugin7.dll  missing) 
2.  a critical warning, namely "2020-12-05T11:35:49     WARNING    Unable to load C:\OSGeo4W64\bin\profile".  After the restart, I now have 3 profiles:  the crashing on ("default"), the fresh one I created ("20201204 profile") and a new one it created, entitled "20201204".  An uninformed guess: was the inability to load a profile because the one I made has a space in it, and it automatically created a version without the space?

Y.

## Report Details

**Crash ID**: [b14ba659850dc58a0f00542dac47d15430563b27](https://github.com/qgis/QGIS/search?q=b14ba659850dc58a0f00542dac47d15430563b27&type=Issues)


**Stack Trace**
<pre>
WTFCrash :
WTF::ParkingLot::forEach :
WTF::ParkingLot::forEach :
RtlRunOnceExecuteOnce :
InitOnceExecuteOnce :
__crtInitOnceExecuteOnce winapisupp.cpp:225
WTF::ParkingLot::forEach :
WTF::ParkingLot::parkConditionally :
WTF::LockBase::lockSlow :
WTF::ParallelHelperPool::doSomeHelping :
WTF::createThread :
WTF::detachThread :
thread_start<unsigned int (__cdecl*)(void * __ptr64)> :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>


**QGIS Info**
QGIS Version: 3.16.1-Hannover
QGIS code revision: b381a90dca
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by gioman** [comment]
> I will not close the report yet as I did get two things in the log messages

If those are linked to some kind of issue then please file separate tickets, thanks!

**Comment by roya0045** [comment]
Just as more info, the error trace is from WebKit.
