### ISSUE TITLE
Raster calculator bug

### ISSUE THREAD

**Issue by camilotp** [qgis/QGIS#40448]
Hi,
For two times in a row my QGIS ended unexpectedly due to some problem using Raster calculator.

Crash ID: 6fd8b45790a8870c10e0e52579cb665697b14605

Stack Trace

QgsRasterMatrix::twoArgumentOperation :
QgsRasterCalcNode::calculate :
QgsRasterCalcNode::calculate :
QgsRasterCalcNode::calculate :
QgsRasterCalcNode::calculate :
QgsRasterCalcNode::calculate :
QgsRasterCalcNode::calculate :
QgsRasterCalcNode::calculate :
QgsRasterCalcNode::calculate :
QgsRasterCalcNode::calculate :
QgsRasterCalcNode::calculate :
QgsRasterCalcNode::calculate :
QgsRasterCalcNode::calculate :
QgsRasterCalcNode::calculate :
QgsRasterCalcNode::calculate :
QgsRasterCalcNode::calculate :
QgsRasterCalcNode::calculate :
QgsRasterCalcNode::calculate :
QgsRasterCalcNode::calculate :
QgsRasterCalcNode::calculate :
QgsRasterCalcNode::calculate :
QgsRasterCalculator::processCalculation :
QgisApp::showRasterCalculator :
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.10.10-A Coru�a
QGIS code revision: 8b051b9a43
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

Thanks

**Comment by gioman** [comment]
@camilotp you must specify the operation/formula and attach/link the data that is causing this crash.

Also you must try with a new QGIS profile, no 3rd party plugins installed.

**Comment by gioman** [comment]
Closing for lack of feedback.
