### ISSUE TITLE
Issues with jpeg2000 (.jp2) map

### ISSUE THREAD

**Issue by DiegoSal91** [qgis/QGIS#40458]
Hi, everyone. I'm new here but I searched for this issue and didn't find anything specificly related to this. I started using QGis 3.16 not long ago on my Windows 10 machine and whenever I added a jp2 raster map, I got these issues:

2020-12-04T17:10:02     CRITICAL    No transform available between This file was created with the ECW JPEG 2000 SDK build 3.3.0.161 copyright 1998-2005 by ER Mapper. This GeoJP2 header was translated from the following ER Mapper style registration information: 
              fOriginX: 659620.500000 
              fOriginY: 9594554.100000 
              fCellIncrementX: 0.300000 
              fCellIncrementY: and EPSG:4326
2020-12-04T17:10:02     CRITICAL    No transform available between This file was created with the ECW JPEG 2000 SDK build 3.3.0.161 copyright 1998-2005 by ER Mapper. This GeoJP2 header was translated from the following ER Mapper style registration information: 
              fOriginX: 659620.500000 
              fOriginY: 9594554.100000 
              fCellIncrementX: 0.300000 
              fCellIncrementY: and SRC personalizado

But didn't mind them because the map would load anyway and could use it for what I wanted to use it. But a couple of days ago, I decided to install Linux (Pop! OS 20.10, especifically) on my laptop which I don't use a lot but I decided to download QGis there too. It works fine but when I want to load the same map, not only I get the same error messages, but the image won't render and I get these messages under the render tab:

2020-12-04T12:19:46     WARNING    LOJA_7964bdde_bc4d_41ef_9d5f_3669f9421c66 :: /home/diegosalazar/Documentos/Ortofotografia/LOJA.jp2, band 2: IReadBlock failed at X offset 0, Y offset 0: opj_get_decoded_tile() failed,/home/diegosalazar/Documentos/Ortofotografia/LOJA.jp2, band 3: IReadBlock failed at X offset 0, Y offset 0: opj_get_decoded_tile() failed,/home/diegosalazar/Documentos/Ortofotografia/LOJA.jp2, band 1: IReadBlock failed at X offset 0, Y offset 0: opj_get_decoded_tile() failed

2020-12-04T12:19:46     WARNING    LOJA_7964bdde_bc4d_41ef_9d5f_3669f9421c66 :: /home/diegosalazar/Documentos/Ortofotografia/LOJA.jp2, band 2: IReadBlock failed at X offset 0, Y offset 0: opj_get_decoded_tile() failed

2020-12-04T12:19:46     WARNING    LOJA_7964bdde_bc4d_41ef_9d5f_3669f9421c66 :: /home/diegosalazar/Documentos/Ortofotografia/LOJA.jp2, band 3: IReadBlock failed at X offset 0, Y offset 0: opj_get_decoded_tile() failed

2020-12-04T12:19:46     WARNING    LOJA_7964bdde_bc4d_41ef_9d5f_3669f9421c66 :: /home/diegosalazar/Documentos/Ortofotografia/LOJA.jp2, band 1: IReadBlock failed at X offset 0, Y offset 0: opj_get_decoded_tile() failed

I've been looking for solutions to this and found none. I've tried on Linux Mint (same results), Manjaro (it crashed the program) and Ubuntu (where I couldn't manage to install it, for some reason).
Just now, I noticed that the GDAL/OGR compilation (which seems to be the issue based on my research but could be wrong... I hope I'm saying it right, my QGis is in Spanish) is v. 3.1.3 on Linux and v. 3.1.4 on Windows. Hope you guys can help me.

**Comment by gioman** [comment]
@DiegoSal91 attach/link data, thanks. But also try with 

`gdalinfo yourfile.jpg`

if GDAL do not recognize it, then is not a QGIS issue.

**Comment by DiegoSal91** [comment]
I'm sorry, I'm a noob on this, how do I do that?

**Comment by gioman** [comment]
> I'm sorry, I'm a noob on this, how do I do that?

from the linux command line

`gdalinfo /path/to/your/file.jp2`

and paste here the output.

**Comment by DiegoSal91** [comment]
Ok, I did what you mentioned, this is what I got:

diegosalazar@pop-os:~$ gdalinfo /home/diegosalazar/Documentos/Ortofotografia/LOJA.jp2
Driver: JP2OpenJPEG/JPEG-2000 driver based on OpenJPEG library
Files: /home/diegosalazar/Documentos/Ortofotografia/LOJA.jp2
Size is 177102, 315018
Coordinate System is:
ENGCRS["This file was created with the ECW JPEG 2000 SDK build 3.3.0.161 copyright 1998-2005 by ER Mapper.  This GeoJP2 header was translated from the following ER Mapper style registration information:
	fOriginX:			659620.500000
	fOriginY:			9594554.100000
	fCellIncrementX:		0.300000
	fCellIncrementY:",
    EDATUM[""],
    CS[Cartesian,2],
        AXIS["easting",east,
            ORDER[1],
            LENGTHUNIT["unknown",1]],
        AXIS["northing",north,
            ORDER[2],
            LENGTHUNIT["unknown",1]]]
Data axis to CRS axis mapping: 1,2
Origin = (659620.500000000000000,9594554.099999999627471)
Pixel Size = (0.300000000000000,-0.300000000000001)
Image Structure Metadata:
  INTERLEAVE=PIXEL
Corner Coordinates:
Upper Left  (  659620.500, 9594554.100) 
Lower Left  (  659620.500, 9500048.700) 
Upper Right (  712751.100, 9594554.100) 
Lower Right (  712751.100, 9500048.700) 
Center      (  686185.800, 9547301.400) 
Band 1 Block=1024x1024 Type=Byte, ColorInterp=Undefined
  Overviews: 88551x157509, 44276x78755, 22138x39378, 11069x19689, 5535x9845, 2768x4923, 1384x2462, 692x1231, 346x616, 173x308, 87x154, 44x77
  Overviews: arbitrary
  Image Structure Metadata:
    COMPRESSION=JPEG2000
Band 2 Block=1024x1024 Type=Byte, ColorInterp=Undefined
  Overviews: 88551x157509, 44276x78755, 22138x39378, 11069x19689, 5535x9845, 2768x4923, 1384x2462, 692x1231, 346x616, 173x308, 87x154, 44x77
  Overviews: arbitrary
  Image Structure Metadata:
    COMPRESSION=JPEG2000
Band 3 Block=1024x1024 Type=Byte, ColorInterp=Undefined
  Overviews: 88551x157509, 44276x78755, 22138x39378, 11069x19689, 5535x9845, 2768x4923, 1384x2462, 692x1231, 346x616, 173x308, 87x154, 44x77
  Overviews: arbitrary
  Image Structure Metadata:
    COMPRESSION=JPEG2000
Band 4 Block=1024x1024 Type=Byte, ColorInterp=Undefined
  Overviews: 88551x157509, 44276x78755, 22138x39378, 11069x19689, 5535x9845, 2768x4923, 1384x2462, 692x1231, 346x616, 173x308, 87x154, 44x77
  Overviews: arbitrary
  Image Structure Metadata:
    COMPRESSION=JPEG2000

**Comment by gioman** [comment]
> Ok, I did what you mentioned, this is what I got:

@DiegoSal91 thanks, seems GDAL on your Linux machine can read this datasource. So now it must be seen why it does not open in QGIS. For this you must attach/link one of your maps, thanks.

**Comment by DiegoSal91** [comment]
Ok... I'll see what I can do because it's quite a large file (7.1 Gb) and essentially the only one on .jp2. The other are .tiff and open without issues.

**Comment by gioman** [comment]
> Ok... I'll see what I can do because it's quite a large file (7.1 Gb) and essentially the only one on .jp2. The other are .tiff and open without issues. Also, huge thanks for your help.

@DiegoSal91 just tested a few samples on my Ubuntu 20.04 QGIS 3.16 installation, all ok.

**Comment by DiegoSal91** [comment]
Huh. That just creates more questions... could it be my file? Going to try your version of Ubuntu and see what happens (didn't have much luck installing QGis on 20.10 tho)

**Comment by gioman** [comment]
>  (didn't have much luck installing QGis on 20.10 tho)

just use LTR releases, 18.04 or 20.04.

**Comment by DiegoSal91** [comment]
It has to be some issue with my map then... no luck on LTR releases (Ubuntu apparently hates me but had better luck with Pop! OS LTR 20.04). I'll try to convert it from my Windows machine to see if I can fix the problem.

**Comment by roya0045** [comment]
As a workaround I would suggest using gdal to convert the file to another format, and then if the custom CRS issue remain either just assign a projection,reproject or georeference the file to something up to date. This should improve usability of the file.

**Comment by DiegoSal91** [comment]
That sounds like a possible solution. Could you tell me how to do that? I've been trying to export it as a GeoTIFF on my Windows machine but either I'm doing something wrong, or it's not the right way to do it.

**Comment by roya0045** [comment]
Look at https://gdal.org/programs/gdal_translate.html to do it from the console or the QGIS processing tool.

**Comment by gioman** [comment]
> Look at https://gdal.org/programs/gdal_translate.html to do it from the console or the QGIS processing tool.

@DiegoSal91 be aware that translating a large jp2 to a geotiff can result in a very large output, unless using some compression. Anyway... do we have an issue here? I can open jp2 files on Ubuntu 20.04.

**Comment by roya0045** [comment]
@gioman its clear that the data source has some issues and its strange that gdal is ok but qgis not as much. But this seems like quite a fringe case that can be solved with a workaround.

**Comment by DiegoSal91** [comment]
It definitely seems there's an issue with my file. I tried to convert it into tiff but the end result was, essentially, a black image (with only the top section of the map being visible) after so many errors that the program stopped reporting them. I'm going to look for a different map and test any other possible issues. Thank you so much to all of you for your time and help.
