### ISSUE TITLE
QSqlTableModel tries to select pg_attrdef.adsrc but it was removed in PostgreSQL 12.0

### ISSUE THREAD

**Issue by stefan-overkamp** [qgis/QGIS#40469]
**Describe the bug**

This is not a QGIS bug but an incompatibility of QGIS actual Qt version 5.11.2 with PostgreSQL 12.

We have a plugin that uses a QtSql.QSqlDatabase to connect to PostgreSQL 12 and a QSqlTableModel.
On QSqlTableModel.select() we get the error pg_attrdef.adsrc does not exist
see: https://bugreports.qt.io/browse/QTBUG-79033

**How to Reproduce**

db = QtSql.QSqlDatabase.addDatabase("QPSQL")
db.setHostName('myhost.de')
db.setPort(5432)
db.setConnectOptions("requiressl=true")
db.setDatabaseName("mydatabase")
db.setUserName("username") 
db.setPassword("password")
success = db.open()  
model =  QSqlTableModel()
model.setTable("employee")
model.setEditStrategy(QSqlTableModel.OnManualSubmit)
model.select()

**QGIS and OS versions**

Windows 10 3.16.1-Hannover
PostgreSQL > 11, see https://www.postgresql.org/docs/11/catalog-pg-attrdef.html

**Additional context**

There is a patch:
https://bugreports.qt.io/secure/attachment/87896/adsrc.patch
Without this patch QSqlTableModel::select() returns false and does not populate the object with data.

I am not familiar with applying this patch to QGIS/Qt 5.11.2

**Comment by roya0045** [comment]
you could compile qgis with a more recent QT, also the minimal qt version should be set to 5.12.? soon if I recall and qt5.15 should be supported soon.

**Comment by jef-n** [comment]
Might be a OSGeo4W issue - but there's a pending update the will take it to Qt 5.15.
