### ISSUE TITLE
Support expressions in legend item label 

### ISSUE THREAD

**Issue by HugoP27** [qgis/QGIS#40465]
**Feature description.**
It would he awesome if legend item labels could be edited using expressions. For example, if I have a layer with 3 polygons, each with a unique value, i'd like to show area stats along with the legend, so currently a legend looks like this:
Area rock fragment percentage
'blue area' 50%
'yellow area' 60%
'red area' 70%

I'd like to use an expression to include attribute values in each legend items' label like this :
Area rock fragment percentage
'blue area' 50% | 20 ha | 40% of area
'yellow area' 60% | 10 ha | 20% of area
'red area' 70% | 20 ha | 40% of area

**Additional context**
When entering an expression like this: @label || '|' || "area" || ' ha | ' ||"percentage“ ||'% of area' 

It displays the desired result in the preview, but once you click ok, the legend item label is the expression enclosed in square braces. 

Just a 'nice to have'. I currently do this manually but im almosr sure it can be done with Pyqgis. a standard function in Q to achieve this would just be awesome

**Comment by DelazJ** [comment]
HI @HugoP27 
Isn't this already the case, using the expression button at the bottom of the legend items frame?
See https://docs.qgis.org/3.10/en/docs/user_manual/print_composer/composer_items/composer_legend.html#legend-items
Using aggregate and assuming you use default legend labels
`concat(@symbol_label, ' | ', aggregate('yourlayer','sum', $area, yourfield=@symbol_label))` returns the symbol class followed by aggregated area

**Comment by roya0045** [comment]
Can be done already, PR improving the situation are in limbo.

**Comment by DelazJ** [comment]
@roya0045 so, we close ?
> Using aggregate and assuming you use **default** legend labels

Then for my curiosity, how do I retrieve the features if the `@symbol_label` is different from the value stored in the field? eg, I edited the label in the Symbology tab to have something more meaningful than an attribute value, what would be the filter expression?

**Comment by roya0045** [comment]
@DelazJ cannot be done at the moment as symbol_label will be the only variable that changes for each symbol. See #33819 for the proper solution. Though complex expressions as an issue in the rendering pipeline, PR #34476 solves part of the issue but if the rendering is too fast (90dpi or 100% zoom( the expression will not even have the time to be rendered in the canvas or in the output. Nyall wanted to look at least at that issue.

**Comment by roya0045** [comment]
@gioman Think we can close this as it is can be done already?
