### ISSUE TITLE
Print Layout does not show paper size above A4 / letter

### ISSUE THREAD

**Issue by fnx2k** [qgis/QGIS#40466]
**Describe the bug**

In the layout Editor, page size above A4 are not shown and customized size cannot be adjusted to paper size above A4

**How to Reproduce**

Set a new user
Start a new project
1. Go to Layout Manager
2. Click on Layout > Page Setup
3. Click on Page Size
![page_size](https://user-images.githubusercontent.com/24877447/101267684-bd280400-375b-11eb-8917-f53e3dfd67ef.png)

Paper sizes only up to ~A4 available
![Capture_page_selection](https://user-images.githubusercontent.com/24877447/101267515-d4fe8880-3759-11eb-9058-129505e3c090.png)
**QGIS and OS versions**

QGIS version | 3.10.12-A Coruña | QGIS code revision | 75c848ffb1
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.6.2-CAPI-1.10.2 4d2925d6
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 10.15 (Ubuntu 10.15-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Linux Mint 19.3

**Additional context**
Page sizes seem to be limited by the capacity of default printer 
But printer selection is done only after page size and layout are set.

At the printing level, even for a A4 printer, Poster printer, or a printer scale, or PDF printing may be selected

A warning may appear, but user should be able to select the page sizes he/she needs in the layout editor.

**Comment by DelazJ** [comment]
Hi @fnx2k 
> Click on Layout > Page Setup

This dialog is to print the layout on a paper, hence bound to your printer settings.
> A warning may appear, but user should be able to select the page sizes he/she needs in the layout editor.

To change layout page, right-click over the page in the layout and you gett access to page properties tab. See https://docs.qgis.org/3.10/en/docs/user_manual/print_composer/overview_composer.html#updating-page-properties

**Comment by gioman** [comment]
I think we can safely close this...
