### ISSUE TITLE
Error: The plugin will be disabled because it crashed QGIS during last startup. Please report an issue and re-enable the plugin when the problem has been solved.

### ISSUE THREAD

**Issue by rahulkgour** [qgis/QGIS#40481]
I have been getting issue as mentioned, couldn't move forward with processing of rasters.

**Error: The plugin will be disabled because it crashed QGIS during last startup. Please report an issue and re-enable the plugin when the problem has been solved.**

Was using latest QGIS, then after getting this error, I reinstalled the same version, but issue persist, then downgraded to LTR QGIS 3.10.12, but no luck.

I have also re-installed my Python to 3.8.6.

Please help as this is seriously blocking my progress. I would be really grateful. Thanks.

**Comment by roya0045** [comment]
Which plugin?

**Comment by rahulkgour** [comment]
> Which plugin?

apologies for not mentioning the plugin name, It is because of Semi-Automatic Classification Plugin (SCP).

**Comment by Gustry** [comment]
As mentioned in the issue template @rahulkgour, QGIS repository is not responsible for third party plugins. You must report the plugin author, not QGIS itself.
