### ISSUE TITLE
Processing/GRASS tool fails to generate output

### ISSUE THREAD

**Issue by sakuya-izayoi-0518** [qgis/QGIS#40499]
I found something that looked like a bug.
so, When I run the  [i.pansharpen] command, it finally fails.
The output message is as follows. 
[Read output layer The next layer was not generated correctly.
• C: /Users/user/AppData/Local/Temp/processing_SiwLfp/2d043cc5b43542f58a317c16a7f5c1f8/redoutput.tif
• C: /Users/user/AppData/Local/Temp/processing_SiwLfp/7278fd9f94164d6fbd5483d23b909f7a/greenoutput.tif
• C: /Users/user/AppData/Local/Temp/processing_SiwLfp/97e48a96f6724a079668047d048ef753/blueoutput.tif
Check the "Log Message Panel" in the QGIS main window to see more information about running the algorithm.]

And another GRASS command same too.

Calculations can be performed on QGIS316.
Something is wrong with QGIS310.

**Comment by gioman** [comment]
Please provide a sample dataset.

>  Check the "Log Message Panel" in the QGIS main window to see more information about running the algorithm.]

@sakuya-izayoi-0518 have you checked the log?

> And another GRASS command same too.

for example?

**Comment by gioman** [comment]
@sakuya-izayoi-0518 also please choose meaningful titles.

**Comment by sakuya-izayoi-0518** [comment]
Thanks for Action.
I checked the logs, but I didn't know. help.

Please provide a sample dataset.
→
B2_cut.tif = Blue
B3_cut.tif = Green
B4_cut.tif = Red
B8_cut.tif = Pan

[smaple.zip](https://github.com/qgis/QGIS/files/5658849/smaple.zip)


And another GRASS command same too.
→Sorry,this mean,Same even if the parameters are changed.

**Comment by gioman** [comment]
> Thanks for Action.
> I checked the logs, but I didn't know. help.

@sakuya-izayoi-0518 works the same  here on both 3.10.12 and 3.16.1 on Windows 10.

**Comment by roya0045** [comment]
Grass doesn't like temporary outputs. That may be the issue.

**Comment by gioman** [comment]
> Grass doesn't like temporary outputs. That may be the issue.

worked fine for me with temp outputs.

**Comment by roya0045** [comment]
@gioman strange, most grass tools I tend to try fail with temporary outputs but work with defined outputs.

**Comment by gioman** [comment]
Closing for lack of further feedback.
