### ISSUE TITLE
Form container not restored (and crash) when embedded in geopackage

### ISSUE THREAD

**Issue by rolandhill** [qgis/QGIS#40495]
Using QGIS 3.16.1 on Ubuntu

I made a form with 3 layers in a single geopackage and 3 subforms as below
![image](https://user-images.githubusercontent.com/2024003/101449473-f8ede400-397c-11eb-95a8-173d680cea55.png)

I then set up the relations and saved all the style information to the geopackage. Everything worked as it should and I can close and open the project and the form still works.

If I open the form as a vector source in a new project then 2 of the subforms are restored properly, but not the third. It should look like this
![Screenshot_20201208_164630](https://user-images.githubusercontent.com/2024003/101449816-977a4500-397d-11eb-83ab-fe5ff8c8390d.png)

but instead looks like this - note that there is nothing showing under the Picture container. I suspect something is there but shows as a blank line. If you click on the Picture container or the blank line below then QGIS will usually crash.
![Screenshot_20201208_164507](https://user-images.githubusercontent.com/2024003/101449849-a52fca80-397d-11eb-8529-e59a9e2b3ad0.png)

1. A test geopackage is attached. To repeat:
2. Open test.gpkg, including all 3 layers.
3. Click on Site and go to Properties
4. Go to Attributes Form
5. Click on the Picture container in Form Layout - it might crash.
6. Expand the Picture container and click on the blank line below it - it might crash here.

To fix:

1. Delete the Picture container
2. Add a new container called picture
3. Drag the picture layer under the new Picture container
4. Click OK. Everything works again.
5. Save all the picture layer styles to the geopackage, create a new project and go back to step 1.
 
Thanks for your efforts!

Roland
[test.gpkg.zip](https://github.com/qgis/QGIS/files/5657451/test.gpkg.zip)

**Comment by gioman** [comment]
> * Click on the Picture container in Form Layout - it might crash.
> 
> * Expand the Picture container and click on the blank line below it - it might crash here.

Crash confirmed here on 3.16.1 on Ubuntu 20.04.

**Comment by gioman** [comment]
Do not crash on 3.10.12.
