### ISSUE TITLE
Integer overflow errors creating and saving virtual layers

### ISSUE THREAD

**Issue by larsks** [qgis/QGIS#40503]
**Describe the bug**

Creating a virtual layer from a shapefile and then attempting to save that virtual layer as a new shapefile results in an integer overflow.

**How to Reproduce**

1. Load [cb_2018_us_state_5m.zip](https://github.com/qgis/QGIS/files/5662380/cb_2018_us_state_5m.zip) (https://www2.census.gov/geo/tiger/GENZ2018/shp/cb_2018_us_state_5m.zip) into a project
2. Create a new virtual layer with the following query:

    ```
    select * from cb_2018_us_state_5m
    ```
3. Attempt to save the virtual layer as a new shapefile

QGIS will fail with:

```
Export to vector file failed.
Error: Feature write errors:
Error converting value (198956658395) for attribute field ALAND: Value "198956658395" is too large for integer field
[...]
Only 4 of 56 features written.
```

**QGIS and OS versions**

QGIS version | 3.16.1-Hannover | QGIS code branch | Release 3.16
-- | -- | -- | --
Compiled against Qt | 5.12.8 | Running against Qt | 5.12.8
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.5 (Ubuntu 12.5-0ubuntu0.20.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Ubuntu 20.04.1 LTS
Active python plugins | kmltools; qgis_resource_sharing; GeoCoding; OSMDownloader; DataPlotly; mask; QuickOSM; quick_map_services; QPackage; timemanager; db_manager; MetaSearch; processing

**Additional context**

**Comment by larsks** [comment]
NB: this bug seems to crop up *regardless* of the destination file format: e.g., trying to export the data as a GeoJSON or KML fails with the same error.

**Comment by roya0045** [comment]
Only repeatable with this datasource?

**Comment by larsks** [comment]
@roya0045 not sure. Let me grab a different dataset and find out.

**Comment by roya0045** [comment]
I'm just curious to know if it might be an int conversion issue from bigint to normal int or something along those lines.

**Comment by larsks** [comment]
It's surprisingly hard to find another dataset that includes large integer fields.

Note that simply re-exporting the shapefile layer works fine; the issue only crops up when exporting the *virtual* layer.

**Comment by larsks** [comment]
It seems to be independent of the data source. If I create a vector layer with a single feature and I create a field `area` with a large value (e.g. `3788339000825`), I can reproduce the error described in this bug report.

**Comment by roya0045** [comment]
so int64 are not taken into acount and considered as int32?

**Comment by larsks** [comment]
Looks that way.

**Comment by roya0045** [comment]
Though looking at the exporter code and the behavior the Qgsfield seems to be taken into account and used as is. So loss of information might occur when creating the virtual layer. I would suspect that the field type estimationg when creating the virtual layer is the issue. Are the field the same as in the source layer?

**Comment by roya0045** [comment]
Ok the column for the layer are defined by the columnDef, which is a custom class where the scalartype can be set and then used here https://github.com/qgis/QGIS/blob/f3ae29d9737f4ad7c8ccb301af04a7e7cd10d004/src/providers/virtual/qgsvirtuallayerprovider.cpp#L448
First an attempt to get the type from the data is donehttps://github.com/qgis/QGIS/blob/a8de679601be931bd356a69f4b1cbb224581339d/src/providers/virtual/qgsvirtuallayerqueryparser.cpp#L175
if that fails here a basic int is coerced https://github.com/qgis/QGIS/blob/a8de679601be931bd356a69f4b1cbb224581339d/src/providers/virtual/qgsvirtuallayerqueryparser.cpp#L226
This might be the offending part.

**Comment by larsks** [comment]
@roya0045 there appear to be *two* problems. The original shapefile contains this data:

| NAME | ALAND |
|---|---|
| Connecticut | 12542619303 |

But when imported into a virtual layer, that becomes:

| NAME | ALAND |
|---|---|
| Connecticut | -342282585 |

So there appear to be problems both when going from shapefile `->` virtual layer **and** when exporting virtual layer `->` shapefile.

**Comment by szymadam** [comment]
@larsks I'm following this subject from GisStackExchange. To make it more complicated, in QGIS 3.14 Virtual Layer also already has incorrect values (trimmed by Integer range issue), but importing Virtual Layer to shapefile (or gpkg) works (i.e. doesn't crash) but of course with incorrect values. Which makes sense, because values are already trimmed/altered to "plain" integer. In QGIS 3.16 it behaves just as you described.

**Comment by troopa81** [comment]
I find a way to solve the issue, I'll propose a fix quickly
