### ISSUE TITLE
QGIS print - map scale and scalebar not same scale

### ISSUE THREAD

**Issue by Ellebjerg** [qgis/QGIS#40514]
![Nyt billede](https://user-images.githubusercontent.com/10741426/101605654-bd95f880-3a02-11eb-8a5d-b473124ed192.png)

As it can be seen in the screendump, the scalebar does not match the map scale. The map scale is set to 1:7000, but the scalebar is 1:6999.999993. A very small difference of little practical importance, but the 1:6999.999993 looks rediculous in the print.

Best regards
Lars Ellebjerg

**Comment by nyalldawson** [comment]
Click on the scale bar, and change the number format to reduce the number of decimal places

**Comment by Ellebjerg** [comment]
Thanks!
