### ISSUE TITLE
CRS Selector doesn't populate 

### ISSUE THREAD

**Issue by newexco-kv** [qgis/QGIS#40512]
**Describe the bug**

**How to Reproduce**

1. Upload .ers file
2. Try to select different CRS, and it won't work. -->

![Capture](https://user-images.githubusercontent.com/59000926/101589751-07dba180-3a24-11eb-8230-b6265ff6210a.PNG)

**QGIS and OS versions**
Using the latest version of QGIS.

**Additional context**

**Comment by gioman** [comment]
> Upload .ers file

@newexco-kv please attach/link a sample



>  Using the latest version of QGIS.

latest ltr? latest lr? master?
Which OS?

**Comment by roya0045** [comment]
Sometimes self compiled qgis can't link with proj, occured to me when compiling on some system.

**Comment by newexco-kv** [comment]
Hi Giovanni,

Here is the attached .ers file.

I am using QGIS 3.14.16 (Pi)

I am currently using Windows 10 Pro.

Thanks,

Kushil


Kushil vaghjiani •
junior geophysicist
[Newexco Logo]
Ph: +61 8 9227 1266 / Fx: +61 8 9227 1677
15 Joel Terrace, East Perth Western Australia, 6004
[award icon] AMEC Prospector Award 2009   [award icon]  Excellence in Mining & Exploration Discovery of the Year 2008

**Comment by gioman** [comment]
> Here is the attached .ers file.

@newexco-kv no attachments.

**Comment by DelazJ** [comment]
@newexco-kv Still no attachment
As per the text at the bottom of the message box "_Attach files by dragging & dropping, selecting or pasting them._ in the message box"

**Comment by roya0045** [comment]
@newexco-kv don't reply in email, go on github

**Comment by newexco-kv** [comment]
Here you go... Unfortunately could only post through a zip folder.
[Lachlan_SRTM3.zip](https://github.com/qgis/QGIS/files/5713160/Lachlan_SRTM3.zip)

**Comment by gioman** [comment]
> Here you go... Unfortunately could only post through a zip folder.

@newexco-kv I cannot load this dataset on Windows and Linux
```

gdalinfo Desktop/Lachlan_SRTM3.ers 
ERROR 4: `Desktop/Lachlan_SRTM3.ers' not recognized as a supported file format.
gdalinfo failed - unable to open 'Desktop/Lachlan_SRTM3.ers'.
```

but support for this format is evailable by default on GDAL

https://gdal.org/drivers/raster/index.html

so maybe the attachment is corrupted?

**Comment by gioman** [comment]
> Here you go... Unfortunately could only post through a zip folder.
> [Lachlan_SRTM3.zip](https://github.com/qgis/QGIS/files/5713160/Lachlan_SRTM3.zip)

@newexco-kv in fact the file only contains

```
DatasetHeader Begin
	Version		= "7.0"
	Name		= "Lachlan_SRTM3.ers"
	LastUpdated	= Fri Feb 19 05:13:43 GMT 2016
	DataSetType	= ERStorage
	DataType	= Raster
	ByteOrder	= LSBFirst
	CoordinateSpace Begin
		Datum		= "GDA94"
		Projection	= "MGA55"
		CoordinateType	= EN
		Units		= "METERS"
		Rotation	= 0:0:0.0
	CoordinateSpace End
	RasterInfo Begin
		CellType	= IEEE4ByteReal
		NullCellValue	= -999999
		CellInfo Begin
			Xdimension	= 90
			Ydimension	= 90
		CellInfo End
		NrOfLines	= 2487
		NrOfCellsPerLine	= 2079
		RegistrationCoord Begin
			Eastings	= 499905
			Northings	= 6125085
		RegistrationCoord End
		RegistrationCellX	= 0
		RegistrationCellY	= 2486
		NrOfBands	= 1
	RasterInfo End
DatasetHeader End
```

**Comment by newexco-kv** [comment]
Maybe try these two files together?

[QGIS_BUG_FIX.zip](https://github.com/qgis/QGIS/files/5722268/QGIS_BUG_FIX.zip)

**Comment by gioman** [comment]
> Maybe try these two files together?

the dataset has no CRS

```
gdalinfo Lachlan_SRTM3.ers 
Driver: ERS/ERMapper .ers Labelled
Files: Lachlan_SRTM3.ers
       Lachlan_SRTM3
Size is 2079, 2487
Origin = (499905.000000000000000,6348825.000000000000000)
Pixel Size = (90.000000000000000,-90.000000000000000)
Corner Coordinates:
Upper Left  (  499905.000, 6348825.000) 
Lower Left  (  499905.000, 6124995.000) 
Upper Right (  687015.000, 6348825.000) 
Lower Right (  687015.000, 6124995.000) 
Center      (  593460.000, 6236910.000) 
Band 1 Block=2079x1 Type=Float32, ColorInterp=Undefined
  NoData Value=-999999

```


when you add it in QGIS you must specify the correct CRS manually (in the layer properties, not the project ones).
