### ISSUE TITLE
QGIS unexpectedly ended

### ISSUE THREAD

**Issue by ajadhav4** [qgis/QGIS#40524]
QGIS unexpectedly ended after adding a table from file geodatabase
[QGIS_3.14_Error.txt](https://github.com/qgis/QGIS/files/5665857/QGIS_3.14_Error.txt)

**Comment by gioman** [comment]
@ajadhav4 this report is incomplete, you must follow the directions you can see here: https://github.com/qgis/QGIS/issues/new?assignees=&labels=Bug&template=10_bug_report.md&title=

Please update to 3.16.1 and try with a new QGIS profile (no 3rd party plugins installed), if the problem persist file a new ticket with all the requested info.
