### ISSUE TITLE
Crash when selecting an object

### ISSUE THREAD

**Issue by Nicobjorn** [qgis/QGIS#40527]
## User Feedback

The crash happened about 10 seconds after clicking on a line objet in order to display its information. QGIS seemed to be struggling for some time before it gave up and crashed. The QGIS window froze during that time.

## Report Details

**Crash ID**: [1aff05dc87b94e91cd85505b8e47c4eb3b5b1b51](https://github.com/qgis/QGIS/search?q=1aff05dc87b94e91cd85505b8e47c4eb3b5b1b51&type=Issues)

**Stack Trace**
<pre>
QWidget::mapTo :
QWidgetPrivate::moveRect :
QApplication::windowIcon :
QApplication::windowIcon :
QWidget::event :
QDockWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.12-A Coru�a
QGIS code revision: 75c848ffb1
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
@Nicobjorn please try with a new QGIS profile, no 3rd party plugins installed.

**Comment by gioman** [comment]
@Nicobjorn if the problem persist attach the project/data we can use to replicate locally.

**Comment by gioman** [comment]
Closing for lack of feedback.
