### ISSUE TITLE
QGIS 3.16 crash when trying to Repair Datasource of a QGIS 3.10 project file

### ISSUE THREAD

**Issue by landConsult** [qgis/QGIS#40523]
## User Feedback

With QGIS 3.10 LTR I created a bigger project with postgis layers and some local *.png raster files, everything works fine. But when I try to open this project with QGIS 3.16 I get an error message saying that the raster files cannot be found (the path to the folder and files has not changed since I last opened it sucessfully with QGIS 3.10).
First I tried to fix the paths in the error message window, without success, the correct paths stayed "red" (instead of green). Then I opened the project anyway with the option to keep the layer information in the Layer window, because the raster files are definitely in the given folder. 
I tried then to repair the data source information (right click on the missing raster layers, marked with the red alert sign, and choose "repair datasource"), then QGIS 3.16 crashed (I repeated it three times and the last time I saw the authentification window for the postgis layers poping up and dissappearing again for a second, before QGIS crashed.   

## Report Details

**Crash ID**: [c0b2899890d31304692dd3813f68225b3336d26d](https://github.com/qgis/QGIS/search?q=c0b2899890d31304692dd3813f68225b3336d26d&type=Issues)

**Stack Trace**
<pre>
QgsLayerTreeOpacityWidget::QgsLayerTreeOpacityWidget qgslayertreeembeddedwidgetsimpl.cpp:73
QgsLayerTreeOpacityWidget::Provider::createWidget qgslayertreeembeddedwidgetsimpl.cpp:151
QgsLayerTreeView::modelRowsInserted qgslayertreeview.cpp:211
QMetaObject::activate :
QAbstractItemModel::endInsertRows :
QgsLayerTreeModel::addLegendToLayer qgslayertreemodel.cpp:1366
QgsLayerTreeModel::refreshLayerLegend qgslayertreemodel.cpp:555
QgsLayerTreeModel::layerLegendChanged qgslayertreemodel.cpp:840
QMetaObject::activate :
QgsMapLayer::setLegend qgsmaplayer.cpp:1799
QgsRasterLayer::init qgsrasterlayer.cpp:599
QgsRasterLayer::setDataSource qgsrasterlayer.cpp:902
<lambda_2633e97846438430bc44765b7b9f9713>::operator() qgisapp.cpp:8254
QgisApp::changeDataSource qgisapp.cpp:8312
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QMenu::exec :
QgsLayerTreeView::contextMenuEvent qgslayertreeview.cpp:170
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1637
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.16.1-Hannover
QGIS code revision: b381a90dca
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

**Comment by gioman** [comment]
@landConsult can you open that raster datasources in a new empty project in QGIS 3.16?

**Comment by roya0045** [comment]
Could you retest on a recent version if this is still valid? The bad layer handler should be fixed. Though I'm not sure if your source has some issues or if its qgis.

**Comment by gioman** [comment]
Closing for lack of feedback.
