### ISSUE TITLE
Crash while 3D view

### ISSUE THREAD

**Issue by pyspider** [qgis/QGIS#40526]
**Describe the bug**

Crash ID: a56861973ca5301d4b022526f839f28880e06d26

Stack Trace

QgsTilingScheme::tileToExtent :

**How to Reproduce**

1. Go to '3D view'
2. Click on 'full view'
3. See error -->Qgis unexpectedly ended

[000.zip](https://github.com/qgis/QGIS/files/5666275/000.zip)

**QGIS and OS versions**

QGIS Info
QGIS Version: 3.12.2-Bucure?ti
QGIS code revision: 8a1fb33634
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363
**Additional context**

**Comment by roya0045** [comment]
Update to a recent version and see if it still crashes.

**Comment by gioman** [comment]
@pyspider also try a new QGIS profile.

**Comment by pyspider** [comment]
It still crashes on QGIS 3.16.1 using new QGIS profile.  No error message was returned and shut down immediately!

**Comment by gioman** [comment]
> It still crashes on QGIS 3.16.1 using new QGIS profile. No error message was returned and shut down immediately!

@pyspider attach the project and data that makes your QGIS crash.

**Comment by pyspider** [comment]
> > It still crashes on QGIS 3.16.1 using new QGIS profile. No error message was returned and shut down immediately!
> 
> @pyspider attach the project and data that makes your QGIS crash.
>here is the file that makes QGIS crash.

[000.zip](https://github.com/qgis/QGIS/files/5668102/000.zip)

**Comment by gioman** [comment]
> [000.zip](https://github.com/qgis/QGIS/files/5668102/000.zip)

@pyspider no issues here

![Screenshot_20201209_192231](https://user-images.githubusercontent.com/1951107/101677021-e8f50380-3a53-11eb-90df-ea6985d72390.png)

**Comment by roya0045** [comment]
Maybe system or OS specific issues?

**Comment by gioman** [comment]
I will try on Windows.

**Comment by gioman** [comment]
It is fine for me on 3.10 on Windows 10, cannot say about 3.16 because of https://github.com/qgis/QGIS/issues/40324

**Comment by pyspider** [comment]
> It is fine for me on 3.10 on Windows 10, cannot say about 3.16 because of #40324

It is still crashes on 3.10.12-A Coruña (installed qgis-full-ltr through osgeo) and shut down by force.  Integrated gpu on the machine (Intel® UHD Graphics 620).

**Comment by gioman** [comment]
> It is still crashes on 3.10.12-A Coruña

@pyspider you may want to add a small screencast that shows exactly the steps you follow to generate the crash. Thanks.

**Comment by pyspider** [comment]
> > It is still crashes on 3.10.12-A Coruña
> 
> @pyspider you may want to add a small screencast that shows exactly the steps you follow to generate the crash. Thanks.
1. try a new QGIS profile.
2. switch project's CRS
3. new 3d map view
4. 3d map canvas is blank, then shut down immediately!

[3D_view_crash.pdf](https://github.com/qgis/QGIS/files/5674143/3D_view_crash.pdf)

**Comment by gioman** [comment]
> switch project's CRS

@pyspider this may be relevant, what CRS do you use?

**Comment by pyspider** [comment]
> > switch project's CRS
> 
> @pyspider this may be relevant, what CRS do you use?

WGS 84 EPSG:4326 (see the pdf)

**Comment by gioman** [comment]
> WGS 84 EPSG:4326 (see the pdf)

QGIS explicitly warns the user to choose a projected CRS, not a geographic one. Anyway this may be the source of the issue, from your screenshot I see that you also check the "no CRS" checkbox... let me check here...

**Comment by gioman** [comment]
> WGS 84 EPSG:4326 (see the pdf)

@pyspider 
![Screenshot_20201210_163248](https://user-images.githubusercontent.com/1951107/101800612-6167cd00-3b05-11eb-9933-27a9af70236c.png)

**Comment by pyspider** [comment]
Sorry, the image link is broken here. Could you add it as attachment? Thx!

**Comment by gioman** [comment]
>     4\. 3d map canvas is blank, then shut down immediately!

@pyspider 
I can replicate the blank 3d view and this is expected with "no CRS" for the project (as there are 3D parameters that are expected do be in map units, the units of your **projected** CRS), but still no crash, not even under Windows 10.

**Comment by gioman** [comment]
> Sorry, the image link is broken here. Could you add it as attachment? Thx!

[Screenshot_20201210_163248.zip](https://github.com/qgis/QGIS/files/5674351/Screenshot_20201210_163248.zip)

**Comment by pyspider** [comment]
> > Sorry, the image link is broken here. Could you add it as attachment? Thx!
> 
> [Screenshot_20201210_163248.zip](https://github.com/qgis/QGIS/files/5674351/Screenshot_20201210_163248.zip)

**Comment by pyspider** [comment]
> > > Sorry, the image link is broken here. Could you add it as attachment? Thx!
> > 
> > 
> > [Screenshot_20201210_163248.zip](https://github.com/qgis/QGIS/files/5674351/Screenshot_20201210_163248.zip)

It is working using projected CRS on 3.12.2. But another DEM file (data size about 1G ) generated blank 3d view using the same projected CRS. 
![3d_view](https://user-images.githubusercontent.com/11908580/101812768-c39cee00-3b56-11eb-8dc7-57d4d1bfcbd5.jpg)

**Comment by gioman** [comment]
> But another DEM file (data size about 1G ) generated blank 3d view using the same projected CRS.

@pyspider this seems a different issue, please update the title and description. Also a link to the DEM would be helpful.

**Comment by pyspider** [comment]
> > But another DEM file (data size about 1G ) generated blank 3d view using the same projected CRS.
> 
> @pyspider this seems a different issue, please update the title and description. Also a link to the DEM would be helpful.

I can not upload the DEM file because of the file szie that exceeds the limit (<=10 MB).

**Comment by gioman** [comment]
> I can not upload the DEM file because of the file szie that exceeds the limit (<=10 MB).

@pyspider for that reason I wrote "link", not "attach".

**Comment by pyspider** [comment]
> > I can not upload the DEM file because of the file szie that exceeds the limit (<=10 MB).
> 
> @pyspider for that reason I wrote "link", not "attach".

see https://github.com/qgis/QGIS/issues/40547
