### ISSUE TITLE
The GRASS console doesn't function in QGIS 3.16.1 on Mac 10.14.6

### ISSUE THREAD

**Issue by drf5n** [qgis/QGIS#40533]
I don't have a crash, but the GRASS console doesn't function.

I'm on QGIS 3.16.1 with a Mac 10.14.6:

QGIS version | 3.16.1-Hannover | QGIS code revision | 3ecbe06f78
-- | -- | -- | --
Compiled against Qt | 5.14.2 | Running against Qt | 5.14.2
Compiled against GDAL/OGR | 3.1.2 | Running against GDAL/OGR | 3.1.2
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.4
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | macOS Mojave (10.14)
Active python plugins | processing; db_manager; MetaSearch

I opened a fresh profile, and did
 *  Plugins/Manage and Install Plugins/ Enable Grass / Close
 * Plugins/GRASS/Open Mapset/GISdbase : Select the .../QGIS-Sample-Data-master/qgis_sample_data/grassdata/  (downloaded and from https://docs.qgis.org/3.16/en/docs/user_manual/introduction/getting_started.html#label-sampledata ) And OK
 * Plugins/GRASS/Open GRASS Tools
* GRASS Tools/Modules/GRASS MODULES/ GRASS Shell
* Click in the box and type stuff like 'r.relief -help'

![image](https://user-images.githubusercontent.com/2236516/101679461-68231100-3a2d-11eb-8d86-bae96985efa9.png)

It is not a working console shell as it should be under https://docs.qgis.org/3.16/en/docs/user_manual/grass_integration/grass_integration.html#the-grass-toolbox section 21.14.2.2 "Using the GRASS Shell" -- I should be able to type commands like 'r.relief -help' but the window doesn't seem to accept input or respond.

![image](https://user-images.githubusercontent.com/2236516/101679846-e1226880-3a2d-11eb-877e-9d64b282d52b.png)

Under Plugins/GRASS/GRASS Options I see this which matches my QGIS install location:

![image](https://user-images.githubusercontent.com/2236516/101680157-4a09e080-3a2e-11eb-83f6-f24bfd526ea6.png)

```
$ ls -la /Applications/QGIS.app/Contents/MacOS/grass*
lrwxr-xr-x  1 drf  admin  20 Nov 30 07:13 /Applications/QGIS.app/Contents/MacOS/grass -> ../Resources/grass78
lrwxr-xr-x  1 drf  admin  20 Nov 30 07:13 /Applications/QGIS.app/Contents/MacOS/grass78 -> ../Resources/grass78

$ ls -la /Applications/QGIS.app/Contents/Resources/grass*
/Applications/QGIS.app/Contents/Resources/grass:
total 72
drwxr-xr-x@    6 drf  admin    192 Nov 30 06:51 .
drwxr-xr-x@   34 drf  admin   1088 Nov 30 07:03 ..
-rw-r--r--@    1 drf  admin  34055 Apr 23  2019 locations.gml
drwxr-xr-x@ 1058 drf  admin  33856 Nov 30 06:51 modules
drwxr-xr-x@    4 drf  admin    128 Nov 30 06:51 qtermwidget
drwxr-xr-x@    9 drf  admin    288 Nov 30 06:51 scripts

/Applications/QGIS.app/Contents/Resources/grass78:
total 352
drwxr-xr-x@  23 drf  admin    736 Nov 30 07:03 .
drwxr-xr-x@  34 drf  admin   1088 Nov 30 07:03 ..
-rw-r--r--@   1 drf  admin  16316 Sep 22 11:29 AUTHORS
-rw-r--r--@   1 drf  admin   1301 Sep 22 11:29 CHANGES
-rw-r--r--@   1 drf  admin   1645 Sep 22 11:29 CITING
-rw-r--r--@   1 drf  admin   1410 Sep 22 11:29 COPYING
-rw-r--r--@   1 drf  admin  17987 Sep 22 11:29 GPL.TXT
-rw-r--r--@   1 drf  admin   9385 Sep 22 11:29 INSTALL
-rw-r--r--@   1 drf  admin   9247 Sep 22 11:29 REQUIREMENTS.html
-rwxr-xr-x@   1 drf  admin  85691 Nov 30 07:01 _grass
drwxr-xr-x@ 381 drf  admin  12192 Sep 22 11:30 bin
-rw-r--r--@   1 drf  admin   3918 Sep 22 11:29 contributors.csv
-rw-r--r--@   1 drf  admin   2753 Sep 22 11:29 contributors_extra.csv
drwxr-xr-x@   3 drf  admin     96 Nov 30 07:03 docs
drwxr-xr-x@   3 drf  admin     96 Sep 22 11:26 driver
drwxr-xr-x@  29 drf  admin    928 Nov 30 07:03 etc
drwxr-xr-x@  25 drf  admin    800 Sep 22 11:30 fonts
-rwxr-xr-x@   1 drf  admin    358 Sep 17 04:47 grass
drwxr-xr-x@ 100 drf  admin   3200 Nov 30 07:03 lib
drwxr-xr-x@ 142 drf  admin   4544 Sep 22 11:30 scripts
drwxr-xr-x@   5 drf  admin    160 Sep 22 11:29 share
drwxr-xr-x@   7 drf  admin    224 Sep 22 11:30 tools
-rw-r--r--@   1 drf  admin   4341 Sep 22 11:29 translators.csv

```

_Originally posted by @drf5n in https://github.com/qgis/QGIS/issues/38961#issuecomment-742012154_

**Comment by gioman** [comment]
@dkav the GRASS plugin is abandoned as it hasn't received any attention since long. It is probably even on the kill list of some main developer. Not sure if it is worth at all to put any effort on it. As a QGIS user that does a lot of geoprocessing and analysis, since we have GRASS in the Processing toolbox the GRASS plugin has become basically irrelevant. For anything GRASS in the Processing toolbox can't do, power uses can just use native GRASS.

How this is different from https://github.com/qgis/QGIS/issues/40534 ?

**Comment by drf5n** [comment]
It differs from https://github.com/qgis/QGIS/issues/40534 in that this is isn't focused on the crash.  It may be similar to https://github.com/qgis/QGIS/issues/38961 , but that was closed.

**Comment by gioman** [comment]
> It differs from #40534 in that this is isn't focused on the crash. It may be similar to #38961 , but that was closed.

ok, but the bottom line is that the GRASS plugin is unmaintained and probably broken (at least on macOS, possibly also on other OSes).

**Comment by dkav** [comment]
@gioman if the GRASS plugin is truly abandoned why is it included as a core plugin and why do the [currents docs](https://docs.qgis.org/3.16/en/docs/user_manual/grass_integration/grass_integration.html) reference it? Also, code changes (albeit minor) still occur in the [plugin folder](https://github.com/qgis/QGIS/commits/master/src/plugins/grass). I am not invested it is inclusion but I will use if it is functional.

**Comment by drf5n** [comment]
A big chunk of the GRASS plugin looks like a fork of KDE terminal code.  I wonder if several GRASS terminal issues could be solved with referring to something like https://github.com/lxqt/qtermwidget ?   I see that they dealt with some font issues with https://github.com/lxqt/qtermwidget/commit/fa4a1bad42fc6282b72e17d2bbcab305975b42a0 

Could outsourcing the https://github.com/qgis/QGIS/tree/master/src/plugins/grass/qtermwidget functionality and maintenance to the https://github.com/lxqt/qtermwidget repository as a Git subtree or a submodule be an option?

**Comment by Sheraztahir20** [comment]
In our expert opinion, [Synthetic Grass](https://www.go-turf.com/) is a smart investment that's worth the money every time. In the long run, a synthetic lawn will cost less money and time than a natural grass lawn. It can stand up to wear and tear from pets, foot traffic, and kids and will look gorgeous for years to come.

**Comment by Sheraztahir20** [comment]
In order to provide the perfect Toto site to our members in line with this confidence, we form a cooperative relationship with the sites below, so you can bet safely without worrying about eating and running on affiliated Toto sites that have been verified by **[먹튀닷컴](https://thelinuxblog.com/)**. In addition, for all those who use our eating and running verification company, deposits of up to 200 million won are deposited at each eating and running verification site and used to recover damage from eating and running.

**Comment by dkav** [comment]
This issue needs to be closed as the Grass console (shell) has been removed. See https://github.com/qgis/QGIS/pull/53597.
