### ISSUE TITLE
QGIS crashes after importing a wpt file

### ISSUE THREAD

**Issue by sdkamat123** [qgis/QGIS#40539]
**Describe the bug**

**How to Reproduce**

4. See error -->

**QGIS and OS versions**

QGIS version
3.16.0-Hannover
QGIS code revision
43b64b13f3
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
BatchHeatmaps-master; 
db_manager; 
processing

**Additional context**

Crash ID: 9be8b929f490f5bdd9170d46a5e5844e1e63b93d

Stack Trace

geos::noding::snapround::MCIndexSnapRounder::computeVertexSnaps :
geos::noding::snapround::MCIndexSnapRounder::computeVertexSnaps :
GEOSEquals_r :
OGRToOGCGeomType :
OGRLayer::FilterGeometry :
SHPPartTypeName :
QgsOgrFeatureIterator::fetchFeature qgsogrfeatureiterator.cpp:387
QgsAbstractFeatureIterator::nextFeature qgsfeatureiterator.cpp:63
QgsVectorLayerFeatureIterator::fetchFeature qgsvectorlayerfeatureiterator.cpp:442
QgsAbstractFeatureIterator::nextFeature qgsfeatureiterator.cpp:63
QgsVectorLayerRenderer::drawRenderer qgsvectorlayerrenderer.cpp:346
QgsVectorLayerRenderer::render qgsvectorlayerrenderer.cpp:317
QgsMapRendererParallelJob::renderLayerStatic qgsmaprendererparalleljob.cpp:353
QtConcurrent::MapKernel >::iterator,QtConcurrent::FunctionWrapper1 const & __ptr64> >::runIteration qtconcurrentmapkernel.h:69
QtConcurrent::MapKernel::iterator,QgsImageOperation::GaussianBlurOperation>::runIterations qtconcurrentmapkernel.h:78
QtConcurrent::IterateKernel::iterator,void>::forThreadFunction qtconcurrentiteratekernel.h:256
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.16.0-Hannover
QGIS code revision: 43b64b13f3
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

**Comment by Gustry** [comment]
You should try with a new QGIS profile.
https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles

and also fill all required information in your ticket.

**Comment by gioman** [comment]
>  3.16.0-Hannover

@sdkamat123 also update to 3.16.1 and attach/link a sample of the problematic data.

**Comment by gioman** [comment]
Closing for lack of feedback.
