### ISSUE TITLE
Rotating camera with point cloud data is very confusing

### ISSUE THREAD

**Issue by saberraz** [qgis/QGIS#40530]
...as it uses the terrain for the point of reference.

**Comment by roya0045** [comment]
@saberraz wasn't that always the case with 3D? and is this even a bug or just a UI/UX issue?

**Comment by saberraz** [comment]
It is particularly an issue with point cloud, as users usually will end up with a flat terrain.

**Comment by uclaros** [comment]
This is unrelated to point cloud data.
I also find camera movement in 3D both bad UX and buggy.
- Normal pan is good and intuitive.
- Middle mouse drag to rotate has double-sensitivity on the Vertical axis than on the Horizontal making it **very** unstable to use, almost unpredictable. This is probably a bug, I can't imagine why it could be that way on purpose.
- Middle mouse drag to rotate rotates the view around some indistinguishable point (the middle of the scene?) while intuition says it should rotate around the terrain point where the cursor was when clicked (just like google earth does). Showing a marker on the center of rotation would be a huge UX improvement too!
- Ctrl + Click drag to rotate should keep the camera position and rotate around it ... well, tbh, I don't even know what exactly it does right now!!

**Comment by uclaros** [comment]
>     * Ctrl + Click drag to rotate should keep the camera position and rotate around it ... well, tbh, I don't even know what exactly it does right now!!

Apparently, upgrading from qt 5.14.2 to qt 5.15.2 and rebuilding resolved the drunken camera movement I was experiencing!!
Now the only issue with ctrl+click drag to rotate is that the camera does not stay 100% put while rotating, but it slightly moves too, because instead of directly setting the camera's pitch and yaw, its location is recalculated from the center of the scene.

**Comment by jedfrechette** [comment]
> * Middle mouse drag to rotate rotates the view around some indistinguishable point (the middle of the scene?) while intuition says it should rotate around the terrain point where the cursor was when clicked (just like google earth does). Showing a marker on the center of rotation would be a huge UX improvement too!

Plus one for rotating around the position of the cursor when the tumble operation was initiated. Currently, rotation seems to occur around the center of the viewport. That means that if you want to rotate around a specific point you first need to move that point to the center of the viewport, which is inevitably imprecise, then initiate the tumble. Rotating around the cursor position would decrease that operation to a single step and make it more precise.

**Comment by jonnyforestGIS** [comment]
Hi @saberraz, I don't know if this is related but, when the point cloud is measured in absolute values, you need to do the offset to the minimum value of Z to "normalize". This improves a lot of navigation and search. 

If a point cloud is georeferenced, you are dealing with the sea level distance so this will create a distance between ground and point of view of the point cloud, So you need to add an offset with a negative value using the minimum Z. The plus of this is that you can see the scale with real Z values of the point cloud objects.

In point cloud that is already normalized in relative values, you don't need to do the offset.

**Comment by wonder-sk** [comment]
This should get fixed with https://github.com/qgis/QGIS/pull/45979
