### ISSUE TITLE
Georeferencing plugin doesnt work

### ISSUE THREAD

**Issue by LucPorter** [qgis/QGIS#40531]
Georeferencing tool is not working (unresponsive), as in nothing happens when you click on it.

I have tried using it on a new project but still nothing. Thanks for your thoughts.

QGIS 3.4.5

**Comment by roya0045** [comment]
Update your qgis first.

**Comment by gioman** [comment]
> QGIS 3.4.5

@LucPorter reopen if it still happen using a recent QGIS release, like the latest 3.10 or 3.16.
