### ISSUE TITLE
Blank 3d view for large DEM

### ISSUE THREAD

**Issue by pyspider** [qgis/QGIS#40547]
**Describe the bug**

 A big size DEM file (about 1GB) generated blank 3d view on 3.12.2.

ps.  The 3d view is still carshes on 3.10 & 3.16. Shut down by force immediately! 
**How to Reproduce**

1. set projected CRS [ESRI:102027]
2. new 3d view
4. See error --> the 3d canvas is still blank.

**QGIS and OS versions**

QGIS version 3.12.2-București

OS Version Windows 10 (10.0)

**Additional context**
The DEM file link: https://www.jianguoyun.com/p/Dbp8qs8QhdHtBxiSqdMD

**Comment by gioman** [comment]
>  The DEM file link: https://www.jianguoyun.com/p/Dbp8qs8QhdHtBxiSqdMD

@pyspider download link only works if creating an account on the hosting platform, if possible use one that does not need that.

**Comment by pyspider** [comment]
> > The DEM file link: https://www.jianguoyun.com/p/Dbp8qs8QhdHtBxiSqdMD
> 
> @pyspider download link only works if creating an account on the hosting platform, if possible use one that does not need that.

Pls find the new DEM file link here https://www.jianguoyun.com/p/DR1TEFMQhdHtBxiZtdMD

I set the sharing permission config to allow unregistered user to download.

**Comment by gioman** [comment]
> Pls find the new DEM file link here https://www.jianguoyun.com/p/DR1TEFMQhdHtBxiZtdMD

@pyspider if you punt a basemap under your DEM you'll notice that it is in the wrong place, and with the wrong scale. You somehow give the DEM the 3857 CRS but it is still in 4326, If you create a copy that is really in 3857 (or any other projected CRS) and it will work as expected.

**Comment by pyspider** [comment]
> > Pls find the new DEM file link here https://www.jianguoyun.com/p/DR1TEFMQhdHtBxiZtdMD
> 
> @pyspider if you punt a basemap under your DEM you'll notice that it is in the wrong place, and with the wrong scale. You somehow give the DEM the 3857 CRS but it is still in 4326, If you create a copy that is really in 3857 (or any other projected CRS) and it will work as expected.

Thanks:) Yes. The previous CRS of DEM is wrong uisng 3875. It is really in 4326. After I set the projected CRS, 3d canvas is work as expected.
