### ISSUE TITLE
Intersection acts like clip

### ISSUE THREAD

**Issue by dingausmwald** [qgis/QGIS#40546]
Qgis 3.16
windows 10 64x

trying to cut a line by polygon boarders. Clip deletes parts that are not in the polygon. Intended behaviour.
Intersect should just cut the line at boarders and keep them all. But acts like clip.

**Comment by gioman** [comment]
@dingausmwald attach sample dataset, thanks.

**Comment by dingausmwald** [comment]
Sry, i was wrong. Intersection acts exactly like clip.

**Comment by gioman** [comment]
> ut still, shouldn intersect keep all parts?

no, in this case (line vs polygon) the result is the same. You are looking to 1) transform the polygon to lines 2) use the "split with lines" tool.
