### ISSUE TITLE
Weird output from "Line density" function

### ISSUE THREAD

**Issue by momeni133** [qgis/QGIS#40545]
Hello everyone,
I ran the "line density" function in QGIS, but the result is just some horizontal stripes. I am using Linux version of QGIS. I have attached a screenshot of the resulted layer and the settings I used here: https://www.dropbox.com/s/8ylkdj107vfxwig/line_density.png?dl=0
I am not sure if it is a bug?

Many thanks

**Comment by gioman** [comment]
@momeni133 QGIS version? Operating system?

**Comment by gioman** [comment]
@momeni133 also attach the necessary input data.

**Comment by momeni133** [comment]
I am using QGIS v 3.16 and my operating system is Linux Mint 20.04
and I clipped a small part of my original data here: https://www.dropbox.com/s/aogp9ar331g4fl3/roads_small.zip?dl=0
I am running the function with "search radius" = 500m  and "pixel size" = 30m

**Comment by gioman** [comment]
@momeni133 same QGIS version and OS here, results seems correct

![Screenshot_20201210_153301](https://user-images.githubusercontent.com/1951107/101792861-177ae900-3afd-11eb-8807-15aec0c4668f.png)

**Comment by momeni133** [comment]
OK. Thanks! it was very helpful. I think I must re-install the software because apparently, it is not working properly on my laptop!
Thanks again

**Comment by gioman** [comment]
> OK. Thanks! it was very helpful. I think I must re-install the software because apparently, it is not working properly on my laptop!
> Thanks again

@momeni133 closing?
