### ISSUE TITLE
Saving Esri Floating Grid as GTiff change data values

### ISSUE THREAD

**Issue by gasato** [qgis/QGIS#40550]
**Describe the bug**

[QGISBugESRIGrid.zip](https://github.com/qgis/QGIS/files/5676064/QGISBugESRIGrid.zip)

I have an ESRI Binary Floating Point Grid loaded on QGIS as a raster layer. When I save it as GeoTiff, data and values changes.

**How to Reproduce**

1. Go to 'Add Layer/raster Layer'
2. Add 'newalt/hdr.adf' (newalt is the ESRI grid name)
3. Click on layer
4. Mouse right button/export/Save as
5. Parameters:
5.1. Raw data
5.2 Format: GeoTiff
5.3 File Name: newalt_gtiff.tif
5.4 SRC: "Same as project" (EPSG:22183)
6. Zoom to 3444862.01,7325400.77, scale 1:7000
7. ESRI GRID and GeoTiff looks different
8. Identify tool shows different values in different areas

**QGIS and OS versions**

Versión de QGIS | 3.16.1-Hannover | Revisión del código de QGIS | b381a90dca
-- | -- | -- | --
Compilado contra Qt | 5.12.8 | Ejecutándose contra Qt | 5.12.8
Compilado contra GDAL/OGR | 3.0.4 | Ejecutándose contra GDAL/OGR | 3.0.4
Compilado contra GEOS | 3.8.0-CAPI-1.13.1 | Ejecutándose contra GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
Versión del cliente PostgreSQL | 12.5 (Ubuntu 12.5-0ubuntu0.20.04.1) | Versión de SpatiaLite | 4.3.0a
Versión de QWT | 6.1.4 | Versión de QScintilla2 | 2.11.2
Compilado contra PROJ | 6.3.1 | Ejecutándose contra PROJ | Rel. 6.3.1, February 10th, 2020
Versión del SO | Ubuntu 20.04.1 LTS
Active python plugins | QGeoloGIS; qProf; LineDirectionHistogram; gisquick-qgis-plugin; SRTM-Downloader; Mergin; qgSurf; qgiscloud; Qgis2threejs; mmqgis; MenuBuilder; DataPlotly; cartography_tools; processing; db_manager

**Additional context**

**Comment by gioman** [comment]
@gasato if you choose a CRS for the output that is different from the input then a reprojection (and a resampling) is applied and changes are expected. If you choose the same CRS as the input then results are identical, see:

![Screenshot_20201210_230455](https://user-images.githubusercontent.com/1951107/101840609-54b29b80-3b3c-11eb-902a-f39c16dbc51d.png)

**Comment by gasato** [comment]
Thanks for your rapid answer.

Yes, you are rigth: I checked it. But I haven't noted  a warning msg when "save as" is choosed (i.e. "warning a raster transformation will be performed" ). Neither it asked for reprojection parameters. When a transformation is performed we hope  the program will ask for what kind of reprojection method  will be applied (i.e. nearest neighbour, bilinear, etc.) then is possible to know what kind of result you will have.

I hope this comment helps.

Cheers

**Comment by gioman** [comment]
> But I haven't noted a warning msg when "save as" is choosed (i.e. "warning a raster transformation will be performed" )

@gasato if you are choosing an output CRS that differs from the input you know that a transformation is being done... anyway feel free to file a feature request.



> Neither it asked for reprojection parameters

QGIS shows you dialog asking for reprojections parameters (when there are more than 1 available) when doing on the fly reprojection. This does not happen yet when using tools like the one in the Processing toolbox, as far as I know. There may be a feature request or not, again feel free to open one if there isn't one already.



> i.e. nearest neighbour, bilinear, etc.)

use the "warp" tool in the Processing toolbox.
