### ISSUE TITLE
Error when Installing QGIS on linux Mint 20.04

### ISSUE THREAD

**Issue by momeni133** [qgis/QGIS#40559]
Hello everyone,
I am trying to install the QGIS on my laptop with Linux mint 20.04 OS, but I am receiving the below errors. I am not sure if it is a bug or I am doing something wrong. It would be so appreciated if you could help me with this.
`apt install qgis qgis-plugin-grass`

> Reading package lists... Done

> Building dependency tree       
> Reading state information... Done
> Suggested packages:
>   gpsbabel
> The following NEW packages will be installed:
>   qgis qgis-plugin-grass
> 0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
> 2 not fully installed or removed.
> Need to get 0 B/6,678 kB of archives.
> After this operation, 9,699 kB of additional disk space will be used.
> Selecting previously unselected package qgis.
> (Reading database ... 438074 files and directories currently installed.)
> Preparing to unpack .../qgis_1%3a3.16.1+32focal_amd64.deb ...
> Unpacking qgis (1:3.16.1+32focal) ...
> Selecting previously unselected package qgis-plugin-grass.
> Preparing to unpack .../qgis-plugin-grass_1%3a3.16.1+32focal_amd64.deb ...
> Unpacking qgis-plugin-grass (1:3.16.1+32focal) ...
> 

> Setting up qgis-providers (1:3.16.1+32focal) ...
> 	- 'VirtualXPath'	[XML Path Language - XPath]
> 	- 'VirtualXPath'	[XML Path Language - XPath]
> 	- 'VirtualXPath'	[XML Path Language - XPath]
> free(): invalid pointer
> Aborted (core dumped)
> dpkg: error processing package qgis-providers (--configure):
>  installed qgis-providers package post-installation script subprocess returned e
> rror exit status 134
> dpkg: dependency problems prevent configuration of qgis:
>  qgis depends on qgis-providers (= 1:3.16.1+32focal); however:
>   Package qgis-providers is not configured yet.
> 

> dpkg: error processing package qgis (--configure):

>  dependency problems - leaving unconfigured
> dpkg: dependency problems prevent configuration of qgis-plugin-grass:
>  qgis-plugin-grass depends on qgis (= 1:3.16.1+32focal); however:
>   Package qgis is not configured yet.

> dpkg: error processing package qgis-plugin-grass (--configure):

>  dependency problems - leaving unconfigured
> dpkg: dependency problems prevent configuration of python3-qgis:
>  python3-qgis depends on qgis-providers (= 1:3.16.1+32focal); however:
>   Package qgis-providers is not configured yet.

> dpkg: error processing package python3-qgis (--configure):

> dependency problems - leaving unconfigured

> Processing triggers for shared-mime-info (1.15-1) ...

> Processing triggers for desktop-file-utils (0.24+linuxmint1) ...
> Processing triggers for mime-support (3.64ubuntu1) ...
> Processing triggers for hicolor-icon-theme (0.17-2) ...
> Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
> Processing triggers for man-db (2.9.1-1) ...
> Errors were encountered while processing:
>  qgis-providers
>  qgis
>  qgis-plugin-grass
>  python3-qgis
> E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by gioman** [comment]
>  I am not sure if it is a bug or I am doing something wrong. It would be so appreciated if you could help me with this.

@momeni133 it is most likely a problem of your machine, as this is not replicable on other Ubuntu 20.04 based OSes installations.

Remove all packages related with QGIS, GRASS, GDAL, PROJ and GEOS.

Check your repositories: use the qgis.org ones, if you using also the ubuntugis one then be sure you are using also the right qgis.org repo that uses ubuntugis dependencies.

**Comment by gioman** [comment]
Closing for lack of feedback.

**Comment by CarolineHaslebacher** [comment]
According to @gioman's suggestion, I executed the following:
```
sudo apt-get remove --auto-remove qgis-providers
sudo apt purge gdal* --auto-remove
sudo apt purge qgis* python-qgis* --auto-remove
sudo apt purge grass* --auto-remove
sudo apt purge proj* --auto-remove
sudo apt purge geos* --auto-remove
```

now every file used by QGIS should be gone.
I went on with:
```
sudo apt-get update
sudo apt install -f qgis qgis-plugin-grass
```

(It should also work without the `-f` in the last line of code, but this makes sure that broken packages are fixed.)

**Comment by dpsspatial** [comment]
I can also confirm this issue on Linux Mint. I have resorted to using the version on the software channel, but it is stuck at version 3.16. Updating to 3.22, 3.26 are throwing dependency errors left and right.

**Comment by dpsspatial** [comment]
I was having the same issues as noted above, but after following all the purge commands above, and thoroughly cleaning old keys, sources.list references, etc. I can sucessfully install 3.22 via debian-ltr on linux mint (focal).
