### ISSUE TITLE
Qgis doesn't start and no more advice or problem item appears

### ISSUE THREAD

**Issue by Francesco824** [qgis/QGIS#40553]
When I try to start a file saved in Qgis it doesn't work (even if below it's the sentence 'Qgis is ready', but there is no advice or problem report, it just appears this window and do anything else. If I try to click on it it just suggest me to close or wait the answer of the program, but eventually it happens nothing else.
My version is Qgis 3.10.0 A Coruna.
![1](https://user-images.githubusercontent.com/75839108/101898591-b1e63580-3bac-11eb-844e-7d063b51eabc.png)
![2](https://user-images.githubusercontent.com/75839108/101898597-b3176280-3bac-11eb-8117-4c63a23e9b03.png)

**Comment by gioman** [comment]
> Qgis 3.10.0 A Coruna.

@Francesco824 which is anyway too old, try with the latest 3.10 or 3.16.

This is not a general QGIS issue, of course, so if the problem persist is better to raise this in the users or developers mailing list, as this is for reporting QGIS bugs only.
