### ISSUE TITLE
Empty "Exclude layers" selection list in Server settings dialog when using projects saved in GPKG files or PGSQL databases

### ISSUE THREAD

**Issue by cxcandid** [qgis/QGIS#40552]
I cannot exclude any layers in QGIS Server dialog (Project Properties --> QGIS Server -->Exclude layers) when the QGIS Project is opened from a GeoPackage file. The dialog box for selecting restricted layers and groups is empty.

**Comment by elpaso** [comment]
Confirmed on master. This is not a regression: it was never implemented and it requires substantial changes to `QgsProjectLayerGroupDialog`.

**Comment by bdecarne** [comment]
Same for a project loaded from PostgreSQL database !
