### ISSUE TITLE
Removing layer while Select by expression dialog is open causes crash

### ISSUE THREAD

**Issue by uclaros** [qgis/QGIS#40554]
**Describe the bug**
Removing a layer while *Select by expression* dialog for this layer is open causes QGIS to crash.

**How to Reproduce**
- Load any vector layer and click *Select features using an expression*  (ctrl+F3)
- Remove the layer (or *close project* or *new project* or *open other project*)
- boom

**QGIS and OS versions**
5c87f705 on debian testing

**Comment by roya0045** [comment]
@uclaros Should it prevent removal or do nothing until ran or close the dialog?

**Comment by uclaros** [comment]
IMO, the dialog should be closed upon layer removal, just like with an open attribute table.
