### ISSUE TITLE
Autocomplete in Python Console adds class to searched  word.

### ISSUE THREAD

**Issue by Dkrav-UA** [qgis/QGIS#40555]
**Describe the bug**
Autocomplete in Python Console adds class (everything in parenthesis) to searched word.  

**How to Reproduce**

1. Start the Python Console
2. Start typing commands (for example '_iface.currentLayer'_)
3. In the dropdown list pick the desired option.
4. See error --> Command added and it's class. **_iface.currentLayer (qgis.core.QgsReportSectionContext)_**

**QGIS and OS versions**

QGIS version | 3.16.1-Hannover | QGIS code revision | b381a90dca
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 10.15 (Ubuntu 10.15-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Ubuntu 18.04.5 LTS
Active python plugins | MetaSearch; processing; db_manager

**Comment by roya0045** [comment]
Cannot replicate on 3.16.1 on win10. Though behaviour is dependent on qscintilla. The old QT dependencies may be the cause.

**Comment by Dkrav-UA** [comment]
> 
> 
> Cannot replicate on 3.16.1 on win10. Though behaviour is dependent on qscintilla. The old QT dependencies may be the cause.

But the same mechanism works fine in Actions Editor.

**Comment by roya0045** [comment]
@gioman considering the dependencies listed this is clearly a weird build with outdated dependencies. This can also be a local issue. I'm not sure this can be solvable until the dependencies issue are ruled out.

**Comment by gioman** [comment]
> I'm not sure this can be solvable until the dependencies issue are ruled out.

@Dkrav-UA can you test on 20.04?

**Comment by Dkrav-UA** [comment]
> > I'm not sure this can be solvable until the dependencies issue are ruled out.
> 
> @Dkrav-UA can you test on 20.04?

20.04 works fine.

**Comment by gioman** [comment]
> 20.04 works fine.

so... does not this prove this is an upstream issue?

**Comment by roya0045** [comment]
@gioman I think this can safely be closed.
