### ISSUE TITLE
RecursionError when importing `py` on Ubuntu 18.04

### ISSUE THREAD

**Issue by maximlt** [qgis/QGIS#40564]
I encountered this bug while developing a plugin that uses `pandas`. The version of `pandas` that is distributed by the package manager on Ubuntu 18.04 is **0.22**. It has the module `py` as a dependency (version 1.5.2), I narrowed down the `RecursionError` I got to this specific module.

Note that this issue has already been reported, but to my understanding the previous issues were closed without fixing the problem or providing a solution: https://github.com/qgis/QGIS/issues/30446, https://github.com/qgis/QGIS/issues/33191 and https://github.com/qgis/QGIS/issues/33612.

Here is the traceback I got from running `import py` in the Python console.
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 794, in _import
    if mod and '__file__' in mod.__dict__:
  File "/usr/lib/python3/dist-packages/py/_vendored_packages/apipkg.py", line 168, in __dict__
    self.__makeattr(name)
  File "/usr/lib/python3/dist-packages/py/_vendored_packages/apipkg.py", line 148, in __makeattr
    result = importobj(modpath, attrname)
  File "/usr/lib/python3/dist-packages/py/_vendored_packages/apipkg.py", line 69, in importobj
    module = __import__(modpath, None, None, ['__doc__'])
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3/dist-packages/py/__metainfo.py", line 1, in <module>
    import py
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 794, in _import
    if mod and '__file__' in mod.__dict__:
  File "/usr/lib/python3/dist-packages/py/_vendored_packages/apipkg.py", line 168, in __dict__
    self.__makeattr(name)
  File "/usr/lib/python3/dist-packages/py/_vendored_packages/apipkg.py", line 148, in __makeattr
    result = importobj(modpath, attrname)
  File "/usr/lib/python3/dist-packages/py/_vendored_packages/apipkg.py", line 69, in importobj
    module = __import__(modpath, None, None, ['__doc__'])
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 794, in _import
    if mod and '__file__' in mod.__dict__:
  File "/usr/lib/python3/dist-packages/py/_vendored_packages/apipkg.py", line 168, in __dict__
    self.__makeattr(name)
  File "/usr/lib/python3/dist-packages/py/_vendored_packages/apipkg.py", line 148, in __makeattr
    result = importobj(modpath, attrname)
  File "/usr/lib/python3/dist-packages/py/_vendored_packages/apipkg.py", line 69, in importobj
    module = __import__(modpath, None, None, ['__doc__'])
...
...
...
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 794, in _import
    if mod and '__file__' in mod.__dict__:
  File "/usr/lib/python3/dist-packages/py/_vendored_packages/apipkg.py", line 168, in __dict__
    self.__makeattr(name)
  File "/usr/lib/python3/dist-packages/py/_vendored_packages/apipkg.py", line 148, in __makeattr
    result = importobj(modpath, attrname)
  File "/usr/lib/python3/dist-packages/py/_vendored_packages/apipkg.py", line 69, in importobj
    module = __import__(modpath, None, None, ['__doc__'])
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "<frozen importlib._bootstrap>", line 200, in _lock_unlock_module
RecursionError: maximum recursion depth exceeded
```

I couldn't really figure out the issue, but here are some of my findings:
* Running `import py` outside of QGIS causes no error
* QGIS overrides the builtin import function in its `utils.py` module here https://github.com/qgis/QGIS/blob/5deda1f4567aa0b6a6b00cd6c623d3fc0055ebe6/python/utils.py#L814
* The import function defined by QGIS wants to get access to the `__dict__` attribute of the imported module
* `py` or exactly `apipkg` that it vendors tries to reconstruct all the module attributes somehow dynamically, which can lead to some new imports https://github.com/pytest-dev/py/blob/d4111cae5572809a23d3d5cc88bed8e4af720929/py/_vendored_packages/apipkg/__init__.py#L152
* This import is made by the function overridden by QGIS utils.py
https://github.com/pytest-dev/py/blob/d4111cae5572809a23d3d5cc88bed8e4af720929/py/_vendored_packages/apipkg/__init__.py#L72

I'm not sure this is the root cause of the issue, this `py` module seems to do a lot of special things.

I'd be interested in working on this issue, some guidance is welcomed :)

**How to Reproduce**

1.Open the Python console in QGIS
2. Execute `import py`

**QGIS and OS versions**

QGIS version | 3.16.1-Hannover | QGIS code revision | b381a90dca
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.6.2-CAPI-1.10.2 4d2925d6
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 10.15 (Ubuntu 10.15-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Ubuntu 18.04.5 LTS
Active python plugins | valuetool; coretests; profiletool; qgistester; firstaid; pluginbuilder3; plugin_reloader; processing; db_manager; MetaSearch

**Workaround**

* Set the environment variable `QGIS_NO_OVERRIDE_IMPORT` to 1. It might have some bad side effects and this is not very user friendly anyway
https://github.com/qgis/QGIS/blob/5deda1f4567aa0b6a6b00cd6c623d3fc0055ebe6/python/utils.py#L812
* `pandas` removed its dependency to `py` in May 2019 (https://github.com/pandas-dev/pandas/pull/26458). Installing a more recent version with `pip3 install --user pandas==0.25.3` solved the issue as this version is used by QGIS rather than the one installed by the package manager

**Comment by maximlt** [comment]
This is a snippet that reproduces the RecursionError when I execute it with my Python system version, it's a stripped version of the `_import` function defined in `utils.py`.

```python
import builtins
_builtin_import = builtins.__import__

def _import(name, globals={}, locals={}, fromlist=[], level=None):
    if level is None: level = 0
    mod = _builtin_import(name, globals, locals, fromlist, level)
    "__file__" in mod.__dict__
    return mod

builtins.__import__ = _import
_import("py")
```

**Comment by maximlt** [comment]
In the module `utils.py` the variable `available_plugins` is a list that stores apparently the plugins available to QGIS (that's what its name says after all :) )

https://github.com/qgis/QGIS/blob/5deda1f4567aa0b6a6b00cd6c623d3fc0055ebe6/python/utils.py#L271-L285

This is the value of `available_plugins` that I got:
```
['rastertimeseriesmanager', 'devnull', 'valuetool', 'DataPlotly', 'qgis_resource_sharing', 'debug_vs', 'coretests', 'profiletool', 'qgistester', 'GroupStats', 'firstaid', 'crayfish', 'pluginbuilder3', 'plugin_reloader', 'report', 'mesma', 'processing', 'db_manager', 'MetaSearch']
```

I don't really understand why in the custom `_import` function defined in `utils.py` it is checked whether the imported package is in the list of the `available_plugins`, since packages and plugins seem to be two different things (at least to me :upside_down_face: ) 

https://github.com/qgis/QGIS/blob/5deda1f4567aa0b6a6b00cd6c623d3fc0055ebe6/python/utils.py#L792-L798

**Comment by roya0045** [comment]
The tickets were mentionned because they were out of scope for the issue reports. Proposing PR to address this is fine but listing any error coming from python doesn't make sense. As suggested in the other reports and for consistency I don't think this is the right place to discuss this.

**Comment by maximlt** [comment]
Hi and thanks for your reply @roya0045 

Actually, it works fine in Python. This command **doesn't raise any error** when in run it in my system's Python interpreter.
```python
import py
```
Which is a good thing. This `py` package is used a lot in the python ecosystem, see theses [stats](https://pypistats.org/packages/py) from PyPi.

However running the same command **in the QGIS python console** raises the RecursionError I and the previous issues reported, so I think it's fair to argue that it's exactly the right place to discuss about this :smiley:

**Comment by roya0045** [comment]
From what I understand of the qgis python setup it aims to use its own environment (if you are familiar with conda you should be familiar with this). In order to provide stable python functions in qgis (processing and other plugins). If you want your plugin to work you'll need to find a way to have this work properly in the QGIS environment. The issues in qgis are there to deal with elements that are related with QGIS 'out of the box'. Importing pandas is not a thing that is proeminent and assumed to be doable with only qgis on the system and pandas is not in the dependencies or existing 'core' plugins. This is why I think this is out of scope and should be brought to the dev mailing list as its not a new point.

**Comment by maximlt** [comment]
I see your point, the integrated interpreter is just meant to run specific code, mostly from the PyQGIS API, so I shouldn't be too surprised that there are bugs for things that are as you say out of scope of the QGIS project (although it's not so obvious for a user :smiley: )

I just wish that this issue could stay open for a little while for the following reasons:
* QGIS patches the builtin import function of Python. Even if it's working in most cases, it's not working with this `py` package (that imports itself somehow when its `__dict__` attribute is called). QGIS itself has some Python dependencies. They worked fine with the patch as it is, but that bug might appear later when some other dependencies are added. Additionally, even if it's out of scope for QGIS, there are many packages out there that have Python dependencies, installing them while installing the plugin or asking the users to install them by themselves. Solving this bug might improve their situation.
* I've made the effort to narrow down the issue as much as I could in the hope that it would serve someone with more experience here. I'd like to see if I can get some guidance for a PR, I've also asked some questions that I hope could find an answer, specially this one https://github.com/qgis/QGIS/issues/40564#issuecomment-743731715

**Comment by roya0045** [comment]
You are aware that the py library is also a third party that is in maintenance mode and is not updated anymore. This dependency may be the one that need to be removed from libraries that people want to inclue.

**Comment by maximlt** [comment]
Yes I'm well aware of that ! I also know that when one installs pandas on Ubuntu 18.04 whose end of life is in 2013 `py` is installed as its one of its dependencies, which I mentioned earlier.

I'll submit a simple fix in a PR and let's see what you think about it :)

**Comment by roya0045** [comment]
If the proposed PR address the situation and does not break any existing code I doubt anyone will have objections.
