### ISSUE TITLE
Systematic crash using postgresql/postgis data

### ISSUE THREAD

**Issue by rbonnefoi** [qgis/QGIS#40579]
Hi all, 

I am experiencing several problems with the last version of QGIS (3.16.1) while using huge amount of data from Postgresql / Postgis.

I coped with many crashes, but managed to find solutions.

Last problem : systematic crash while trying to duplicate a virtual layer builded from postgis source and/or try to open the properties window of the layer.

I just tried with the LTR version (3.10) : crashes also.

Here is the crash report : 
[crash_report.txt](https://github.com/qgis/QGIS/files/5687623/crash_report.txt)

Any help will be greatly appreciated.

Feel free to contact me if further information needed.

Regards,

Remi.

**Comment by gioman** [comment]
@rbonnefoi try a new QGIS profile, no 3rd party plugins installed.

**Comment by jgrocha** [comment]
I was not able to replicate the problem with current master on Ubuntu, Postgresql 11.7, Postgis 2.5.4.

On a project with several Postgis layers, I've created one virtual layer based on an existing Postgis layer (a layer with about 100k polygons). It took a few seconds, but the layer was created and I was able to check its properties, change style, etc. No crash.

@rbonnefoi Can you tell us more about your setup? Postgresql and Postgis version. Local or remote database?

**Comment by gioman** [comment]
Closing for lack of feedback.
