### ISSUE TITLE
Can't add .shp layers by drag&drop action

### ISSUE THREAD

**Issue by Qbert70** [qgis/QGIS#40575]
ESRI .shp layers that can be regularly imported from layer>add layer menu can't be addedby dragging and dropping in the main window

Versione di QGIS
3.16.0-Hannover
Revisione codice QGIS
43b64b13f3
Compilato con Qt
5.11.2
Esecuzione con Qt
5.11.2
Compilato con GDAL/OGR
3.1.4
Esecuzione con GDAL/OGR
3.1.4
Compilato con GEOS
3.8.1-CAPI-1.13.3
Esecuzione con GEOS
3.8.1-CAPI-1.13.3
Compilato su SQLite
3.29.0
In esecuzione su SQLite
3.29.0
Versione client PostgreSQL
11.5
Versione SpatiaLite
4.3.0
Versione QWT
6.1.3
Versione QScintilla2
2.10.8
Compilato con PROJ
6.3.2
Esecuzione con PROJ
Rel. 6.3.2, May 1st, 2020
Versione SO
Windows 10 (10.0)
Attiva python plugin
autoSaver; 
GeoCoding; 
mmqgis; 
OnlineRoutingMapper; 
ORStools; 
qProf; 
db_manager; 
MetaSearch; 
processing

**Comment by gioman** [comment]
> ESRI .shp layers that can be regularly imported from layer>add layer menu can't be addedby dragging and dropping in the main window

@Qbert70 any error message?



> 3.16.0-Hannover

update to 3.16.1

**Comment by Qbert70** [comment]
Qgis turn the pointer icon into a forbidden sign. No error, program working. The only issue is to have to load layers via menu. The layer from the browser (downloaded from servers) are normally added via drag+drop

**Comment by gioman** [comment]
> Qgis turn the pointer icon into a forbidden sign.

@Qbert70 seems a local issue, works as expected here on the same operating system.

**Comment by roya0045** [comment]
Do you have read write acces to the data itself?

**Comment by Qbert70** [comment]
> Do you have read write acces to the data itself?
Yes sure. 
 
> @Qbert70 seems a local issue, works as expected here on the same operating system.
 I think so. I've got another pc that works fine. I was wondering if anybody had got same issue out there

thank everybody for your time. If I found the problem I'll post here

**Comment by andreatitolo** [comment]
I don't know if it's your case, but I saw the same behaviour (same QGIS and OS version) when running qgis as administrator. Running qgis NOT in administrator mode allows the shp to be dragged and dropped again in the main window.

**Comment by Qbert70** [comment]
It's my case! GENIUS! THAT'S IT!!!!!!! THAAAAAAAAAAAAAAAAANK YOU. big thank you, Grazie Andrea.
Lesson: don't run as administrator if it's not necessary (I don't even remember why it was so).
Better make it clear in the appropriate section of the forum

> I don't know if it's your case, but I saw the same behaviour (same QGIS and OS version) when running qgis as administrator. Running qgis NOT in administrator mode allows the shp to be dragged and dropped again in the main window.

**Comment by ale-1106** [comment]
solo paso a dejar mis agradecimientos al crack que comento que el error se debía a ejecutar qgis en modo admin. GENIO!!!!!
