### ISSUE TITLE
"Import geotagged photos" fails for jpg / jpeg on Windows

### ISSUE THREAD

**Issue by pathmapper** [qgis/QGIS#40583]
**Describe the bug**
`Import geotagged photos` algorithm fails for jpg / jpeg on Windows.

**How to Reproduce**

1. Unzip [sample_jpg.zip](https://github.com/qgis/QGIS/files/5688584/sample_jpg.zip)
2. Use the `Import geotagged photos` algorithm from the processing toolbox with the input folder containing the sample image.
4. See error --> `Could not open ...`

**QGIS and OS versions**

QGIS version | 3.16.1-Hannover | QGIS code revision | b381a90dca
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | Discovery; ImportPhotos-adapted_path; joinmultiplelines; mmqgis; QPackage; db_manager; MetaSearch; processing

**Additional context**

This happens for a lot of different images captured with different devices.

On Linux it works with QGIS 3.16.1, but it's compiled against GDAL/OGR **2.4.0**.

Might be related to GDAL but I'm not entirely sure (`gdalinfo` fails also: https://github.com/OSGeo/gdal/issues/3284).

Also with several image viewers (e.g. GIMP) the sample jpg works flawlessly and it's possible to show the EXIF data.

**Comment by gioman** [comment]
Works on 3.16.1 on ubuntu 20.04, which uses GDAL 3 (to say that I don't think GDAL is the culprit).

**Comment by nyalldawson** [comment]
OSGeo/gdal#3284 definitely suggests this is either an upstream or osgeo4w packaging issue. In any case, it's not a qgis bug.
