### ISSUE TITLE
QGIS unexpectedly ended

### ISSUE THREAD

**Issue by mccainjm** [qgis/QGIS#40609]
## User Feedback

Had just opened the project and had only zoomed in on a location when it stopped responding

## Report Details

**Crash ID**: [0244ee72e63b812093e103e8e4f6ec581183255c]('https://github.com/qgis/QGIS/search?q=0244ee72e63b812093e103e8e4f6ec581183255c&type=Issues')

**Stack Trace**
<pre>
osgeo::proj::datum::Datum::conventionalRS :
osgeo::proj::datum::Datum::conventionalRS :
osgeo::proj::datum::Datum::conventionalRS :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::transformCoords :
QgsCoordinateTransform::transformBoundingBox :
QgsMapRendererJob::reprojectToLayerExtent :
QgsMapRendererJob::prepareJobs :
QgsMapRendererParallelJob::start :
QgsMapCanvas::refreshMap :
QMetaObject::activate :
QTimer::timerEvent :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32Private::sendTimerEvent :
QEventDispatcherWin32::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.4-A Coru�a
QGIS code revision: 10bc9f2ff2
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.16299

**Comment by roya0045** [comment]
update to a more recent version first. I'm pretty sure this was fixed a good while ago.

**Comment by gioman** [comment]
Closing for lack of feedback.
