### ISSUE TITLE
"QGIS unexpectedly ended" message after reprojecting 382MB polygon layer

### ISSUE THREAD

**Issue by cotrujilloc** [qgis/QGIS#40606]
Good day.

I've been having trouble reprojecting a 382MB polygon layer. I've tried five times already with the "Reproject layer" function but QGIS keeps on crashing. It shows the "QGIS unexpectedly ended" window. Below the message that appears in that window.

This layer itself is the result of transforming into polygon a raster dataset (it is a tif of the population distribution of the DRCongo, a big country, but the raster itself is not so big, 25MB). 

Do you have any advice on how can I fix this? Thanks in advance.

Crash ID: ffc485992db59bda633a330389c3d8b52f05270c
Stack Trace
VSICreateCachedFile :

QGIS Info
QGIS Version: 3.8.3-Zanzibar
QGIS code revision: 685d8b15d2
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

**Comment by gioman** [comment]
>  QGIS Version: 3.8.3-Zanzibar

@cotrujilloc way tool old. You must test on the latest 3.10 or 3.16. If the problem persist please link the input dataset, and specify to what CRS you are trying to reproject to.

**Comment by gioman** [comment]
Closing for lack of feedback.
