### ISSUE TITLE
QGIS Freezing but using of ram or CPU is not high

### ISSUE THREAD

**Issue by grzmak** [qgis/QGIS#40625]
I have an issue in qgis. I got a project in QGIS, and this is very big. But I have a very good computer with CPU with high speed and 16GB RAM spaces. In my project qgis very often freezing but using of cpu and ram are not bigger. I have enabled option in qgis with using cpu and memory. I want to use qgis quickly, without any freeze, it is possible to repair my problem?

**Comment by gioman** [comment]
@grzmak your description is too vague.

What QGIS version do you use?

What OS?

What kind of data do you have in your project?

Doing what QGIS is slow/freezes?

Have you tried with a new QGIS profile?

**Comment by grzmak** [comment]
I use the latest version, which is 3.16.1 Hannover. My OS is Windows 10, version 20H2. Problem is not only on this project, but generally.  QGIS after click on elements, for example menu or layer is not replying for about one or two minutes and then works normally, but when I zoom my maps the problem returns.  I don't know what is new QGIS Profile. In windows I see the qgis-bin.exe is not replying in freezeing moment, but there is very little memory and cpu usage on qgis-bin.exe.

**Comment by uclaros** [comment]
Try closing the *Browser panel* in QGIS if you have it enabled. Windows sometimes cause delays with inaccessible network drives.

**Comment by gioman** [comment]
>  I don't know what is new QGIS Profile

@grzmak settings > user profiles > new profile. And do not install any 3rd party plugin before testing on the new profile.

**Comment by grzmak** [comment]
Closing browser panel helps me. I had disconnected remote disk on windows and it is a problem, because Qgis try to connect it all time.

**Comment by elpaso** [comment]
This issue is hitting many people, I'm no Windows developer by I'm wondering if there is a way to know when a network disk is connected and prevent QGIS brower to scan it.

**Comment by nyalldawson** [comment]
@elpaso there's win (not qt) API which we could use to determine if a drive is remote. I wonder if we should skip the auto scanning of any non-local drives to help with this...

**Comment by uclaros** [comment]
The same solution could also be applied to reading recent projects. Recent projects in an unreachable drive can cause huge startup times

**Comment by Louis-Backstrom** [comment]
I've been having this issue, once again fixed by closing the Browser window. It would be great to be able to have QGIS ignore network drives when scanning, or whatever it takes to fix this issue. Currently on 3.16.3.

**Comment by gioman** [comment]
> Currently on 3.16.3

@Louis-Backstrom try update to 3.16.14.
