### ISSUE TITLE
QGIS server doesn't honor resampling method

### ISSUE THREAD

**Issue by timautin** [qgis/QGIS#40629]
Hello,

I'm using QGIS server to display a DEM as hillshade on an OpenLayers website through WMS. I have set the resampling method to bilinear, which works fine in QGIS:

![qgis](https://user-images.githubusercontent.com/3846288/102390029-36352000-3fd4-11eb-9694-58b32472dcaf.jpg)

But when viewing my project though QGIS server's WMS, I'm getting this:

![qgis-server](https://user-images.githubusercontent.com/3846288/102390072-3fbe8800-3fd4-11eb-8a21-bd805dec8455.jpg)

I get the same in QGIS if I set the resampling to near.

To reproduce:
- get a DEM tif
- add it to QGIS, open the layers properties and set its rendering type to hillshading, and resampling method to cubic or bilinear
- view the layer through WMS
-> the resampling on the WMS is always near even though you chose not cubis / bilinear

What I'd expect:
The resampling method should be used for QGIS server's WMS layers.

QGIS version:

Version de QGIS | 3.4.4-Madeira | Révision du code | f6ddc62
-- | -- | -- | --
Compilé avec Qt | 5.5.1 | Utilisant Qt | 5.5.1
Compilé avec GDAL/OGR | 2.2.2 | Utilisé avec GDAL/OGR | 2.2.2
Compilé avec GEOS | 3.5.1-CAPI-1.9.1 | Utilisé avec GEOS | 3.5.1-CAPI-1.9.1 r4246
Version du client PostgreSQL | 9.5.2 | Version de SpatiaLite | 4.3.0a
Version de QWT | 6.1.2 | Version de QScintilla2 | 2.9.1
Version de PROJ.4 : | 492

**Comment by gioman** [comment]
> 3.4.4-Madeira

@timautin too old, you must test on 3.10.12 or 3.16.1

**Comment by timautin** [comment]
Ooops indeed, and I wasn't testing with 3.4.4 but an even older version. It's already fixed in 3.4.4, sorry for the noise!

**Comment by Gustry** [comment]
You should still upgrade, 3.4 is not maintained.
Glad it's fixed

**Comment by timautin** [comment]
`You should still upgrade, 3.4 is not maintained.`

Well, 3.4.4 is the latest version I get on my Ubuntu 16.04 LTS (using the unstable ppa, by default it's much older), and I can't upgrade to a newer Ubuntu for now.

**Comment by timautin** [comment]
Oh well, in fact the server having the bug is up to date:

$ qgis_mapserver --version
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
QGIS Development Server 3.16.0-Hannover

I can confirm that it works on my dev computer using version 3.4.4, and not on the server. Same project, same WMS request. Please reopen.

**Comment by gioman** [comment]
Works fine on qgis server 3.10.12 on Ubuntu 20.04. Can't test on 3.16 right now.

**Comment by gioman** [comment]
> Can't test on 3.16 right now.

@timautin works also fine on QGIS Server 3.16 here.

**Comment by timautin** [comment]
Weird, maybe it's tif-dependent. I uploaded a project triggering the bug here: https://www.ewalk.app/data/tmp/bug.zip

This GetMap request:

http://localhost/cgi-bin/qgis_mapserv.fcgi?MAP=/path/to/bug.qgz&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=color%2Chillshade&WIDTH=1024&HEIGHT=1024&CRS=EPSG%3A3395&STYLES=&DPI=180&BBOX=645128.518726889%2C5293569.956861597%2C645281.3927834594%2C5293722.830918167

Gives me this on 3.4.4:
![qgis-3 4 4](https://user-images.githubusercontent.com/3846288/102613251-714d6580-4132-11eb-91b5-ba6a1fdfa01b.png)

And this on 3.16:
![qgis-3-16](https://user-images.githubusercontent.com/3846288/102613234-6d214800-4132-11eb-9977-e6ca507c37c4.png)

I also just noticed that our 3.16 server is using GDAL 2.4.0 while on my 3.4.4 dev machine I installed version 3.2.0. May it be a GDAL bug?

**Comment by gioman** [comment]
> Weird, maybe it's tif-dependent. I uploaded a project triggering the bug here: https://www.ewalk.app/data/tmp/bug.zip

@timautin works fine here on qgis-server 3.16 on a Ubuntu 20.04 server.

**Comment by timautin** [comment]
@gioman Thanks for testing and reporting. Could you give me the GDAL version of your server (gdalwarp --version)?

**Comment by gioman** [comment]
> @gioman Thanks for testing and reporting. Could you give me the GDAL version of your server (gdalwarp --version)?

@timautin it is gdal 3
