### ISSUE TITLE
labeling settings partly not saved

### ISSUE THREAD

**Issue by Diethart123** [qgis/QGIS#40622]
**Describe the bug**

**How to Reproduce**

4. See error -->

**QGIS and OS versions**

**Additional context**

**Comment by Diethart123** [comment]
some of the labeling settings are not saved in the project. For example "Line height" and settings for "Leader lines" (Führungslinien). Didn't check all font settings - I only noticed it again and again with individual settings
![Zeilenhöhe_not_saved](https://user-images.githubusercontent.com/76101669/102337339-a1f69900-3f92-11eb-9452-3ddc1d1f8f43.JPG)

**Comment by nyalldawson** [comment]
Is this specific to locales using "," as a decimal separator? Are you able to test changing your QGIS to use an english locale with "." as the separator and confirm whether it resolves the issue?

**Comment by Diethart123** [comment]
Hallo,
i do not think, that it is specific to locales using "," or ".".
The bug occurs sometimes and not in all project. But it occurs always in the field „label“ or „buffers“.


Von: Nyall Dawson <notifications@github.com>
Gesendet: Mittwoch, 20. Januar 2021 01:12
An: qgis/QGIS <QGIS@noreply.github.com>
Cc: Diethart Ehms <diethart.ehms@achten-jansen.de>; Author <author@noreply.github.com>
Betreff: Re: [qgis/QGIS] labeling settings partly not saved (#40622)


Is this specific to locales using "," as a decimal separator? Are you able to test changing your QGIS to use an english locale with "." as the separator and confirm whether it resolves the issue?

**Comment by Diethart123** [comment]
Hi,
I realized the problem.
There is a problem with the format of the field.
It occurs with me in several fields. i.a. in the fields "Line width" and "Size X" and "Size Y".
After saving, real characters are lost because the cell format is "integer" - I guess.
You probably have to check all data fields in the layout area.

***@***.***D73CDC.3E943150]



Von: Nyall Dawson ***@***.***>
Gesendet: Mittwoch, 20. Januar 2021 01:12
An: qgis/QGIS ***@***.***>
Cc: Diethart Ehms ***@***.***>; Author ***@***.***>
Betreff: Re: [qgis/QGIS] labeling settings partly not saved (#40622)


Is this specific to locales using "," as a decimal separator? Are you able to test changing your QGIS to use an english locale with "." as the separator and confirm whether it resolves the issue?

**Comment by gioman** [comment]
> After saving, real characters are lost because the cell format is "integer" - I guess.

@Diethart123 not sure I understand, you are saying then that the problem was on your side, right?

**Comment by Diethart123** [comment]
I guess that the cell format ist „integer“ so that it rejects a number that ist „real“
So the problem is not on my side….


Von: Giovanni Manghi ***@***.***>
Gesendet: Donnerstag, 29. April 2021 11:26
An: qgis/QGIS ***@***.***>
Cc: Diethart Ehms ***@***.***>; Mention ***@***.***>
Betreff: Re: [qgis/QGIS] labeling settings partly not saved (#40622)


After saving, real characters are lost because the cell format is "integer" - I guess.

@Diethart123<https://github.com/Diethart123> not sure I understand, you are saying then that the problem was on your side, right?

**Comment by gioman** [comment]
> I guess that the cell format ist „integer“ so that it rejects a number that ist „real“ So the problem is not on my side….

@Diethart123 sorry, is this about auxiliary storage? Can you attach a small sample project + data?

**Comment by Diethart123** [comment]
here is the projekt….

Von: Giovanni Manghi ***@***.***>
Gesendet: Donnerstag, 29. April 2021 12:48
An: qgis/QGIS ***@***.***>
Cc: Diethart Ehms ***@***.***>; Mention ***@***.***>
Betreff: Re: [qgis/QGIS] labeling settings partly not saved (#40622)


I guess that the cell format ist „integer“ so that it rejects a number that ist „real“ So the problem is not on my side….

@Diethart123<https://github.com/Diethart123> sorry, is this about auxiliary storage? Can you attach a small sample project + data?

**Comment by gioman** [comment]
> here is the projekt….

@Diethart123 to send attachments you must use the GitHub we site, you can't send them by replying via email.

**Comment by Diethart123** [comment]
[GITHUB.zip](https://github.com/qgis/QGIS/files/6403314/GITHUB.zip)

**Comment by gioman** [comment]
@Diethart123 I tried saving that label configuration on two systems that use the comma as decimal separator (win10 in PT and DE). No issues with both QGIS 3.16 and 3.18.

**Comment by Diethart123** [comment]
Hallo, thanks for your support...
the problem seems to occur only on my computer- i've tested it on several other computers with different projects and different versions of QGIS. If you have any idea, what I can do, please let me know. 
Otherwise this issue can be closed.

**Comment by Diethart123** [comment]
when I change de decimal-seperator in the basic setting of my computer from "," to "." , then everything works fine.
I tried to change the setting in QGIS in the "otpions" here:
![grafik](https://user-images.githubusercontent.com/76101669/116850686-59faaa80-abf1-11eb-8d81-36e990b4cf56.png)
but every change I tried does not work.
I give up now... probably a new computer will also work faster

**Comment by gioman** [comment]
> when I change de decimal-seperator in the basic setting of my computer from "," to "."

@Diethart123 where is that exactly?

**Comment by Diethart123** [comment]
its here:
![grafik](https://user-images.githubusercontent.com/76101669/116867118-cdf67c00-ac0c-11eb-82d0-f3cb1ef0773d.png)
A friend of mine has the same problem on his computer with this. We have solved the problem within QGIS...
look here:
![grafik](https://user-images.githubusercontent.com/76101669/116867423-70166400-ac0d-11eb-94d8-31236b85bb77.png)
but its not satisfying at all because normaly it works but on some computers not....

**Comment by gioman** [comment]
> when I change de decimal-seperator in the basic setting of my computer from "," to "." , then everything works fine.

@Diethart123 by default Win10 in DE uses the comma "," as separator and saving decimal values in the labels properties work just fine.

Also using a data defined property, using an appropriate decimal column (as the "angle" one in your sample data) works as expected. I'm using QGIS 3.16/3.18 on a clean Win 10 machine in DE language.

**Comment by Diethart123** [comment]
As I said. The problem does occur on some computers - one of them is brand new with a clean Win 10 setup. One other computers everything works correctly. I think we can't solve the problem but we have found an individual solution while using "data defined property"

**Comment by gioman** [comment]
@Diethart123 where do we stand with this issue?

**Comment by Diethart123** [comment]
Hi, the problem ist not solved yet but we helped us with  "data defined property" - then it workes properly. The problem occurs on some pc, on others not. It doesn't matter if it ist a brand new pc with a new Win 10 and QGIS setup or an old one..... Perhaps you have to wait until other users have got a clue how to solve it. Thanks a lot

**Comment by gioman** [comment]
> until other users have got a clue how to solve it.

@Diethart123 I guess that is needed to understand how to reliably replicate it.
