### ISSUE TITLE
Shapefile and also attribute table will not always load in QGIS 3.16.1

### ISSUE THREAD

**Issue by spergularia** [qgis/QGIS#40638]
**Describe the bug**

**How to Reproduce**

4. See error -->

**QGIS and OS versions**

**Additional context**

**Comment by gioman** [comment]
@spergularia reopen adding all the requested info as stated here

https://github.com/qgis/QGIS/issues/new?assignees=&labels=Bug&template=10_bug_report.md&title=



**Describe the bug**


**How to Reproduce**



1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error -->

**QGIS and OS versions**



**Additional context**
