### ISSUE TITLE
Loading large shapefile, Crash in 3.14

### ISSUE THREAD

**Issue by DrewFrance** [qgis/QGIS#40645]
## User Feedback

Loading a large 2+ gig shapefile. No other layers.

## Report Details

**Crash ID**: [d435efb8b8d75a23ae63bd9543aeec2b7322a5a0](https://github.com/qgis/QGIS/search?q=d435efb8b8d75a23ae63bd9543aeec2b7322a5a0&type=Issues)

**Stack Trace**
<pre>
GDALReadWorldFile2 :
OGRFieldDefn::IsNullable :
OGRFieldDefn::IsNullable :
OGRCurveCollection::hasCurveGeometry :
OGRCurveCollection::hasCurveGeometry :
IGMLReader::~IGMLReader :
IGMLReader::~IGMLReader :
IGMLReader::~IGMLReader :
RegisterOGRLIBKML :
GDALOpenEx :
QgsOgrProviderUtils::GDALOpenWrapper :
QgsOgrProviderUtils::GDALOpenWrapper :
QgsOgrProviderUtils::getLayer :
QgsOgrProviderUtils::ogrTypeFromQgisType :
QgsOgrLayerNotValidException::QgsOgrLayerNotValidException :
QgsOgrProviderUtils::createEmptyDataSource :
QgsProviderRegistry::createProvider :
QgsVectorLayer::setDataProvider :
QgsVectorLayer::setDataSource :
QgsVectorLayer::QgsVectorLayer :
QgisApp::addVectorLayersPrivate :
QgisApp::addVectorLayers :
QgisApp::qt_static_metacall :
QMetaObject::activate :
QgsDataSourceManagerDialog::addVectorLayers :
QMetaObject::activate :
QgsAbstractDataSourceWidget::addVectorLayers :
QgsProjectStorageGuiProvider::QgsProjectStorageGuiProvider :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
QgisApp::dataSourceManager :
QgisApp::identifyMapTool :
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.14.16-Pi
QGIS code revision: df27394552
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by roya0045** [comment]
3.14 won't be fixed, try with a current version instead to see if still valid.

**Comment by roya0045** [comment]
Also possible upstream issue.

**Comment by gioman** [comment]
> Loading a large 2+ gig shapefile. No other layers.

@DrewFrance upgrade QGIS, try with a new QGIS profile.

**Comment by gioman** [comment]
Closing for lack of feedback.
