### ISSUE TITLE
Pan Map to Selection in the View menu is enabled even for non-spatial and raster layers

### ISSUE THREAD

**Issue by TurboGraphxBeige** [qgis/QGIS#40647]
The item "Pan Map to Selection" in the "View" menu is always enabled, even when a non-spatial layer or a raster is selected in the layer tree. A behavior like the "Zoom to Selection" would be expected where it's only enabled when a vector layers is selected in the layer tree.

Tested on 3.10 and also the current master branch from the git repository.

**Comment by TurboGraphxBeige** [comment]
Let me know what you think, I'll make the PR with the referenced commit then.

**Comment by uclaros** [comment]
Ideally, both pan and zoom to selection should be disabled when there is no selection on the active layer. Same goes for the same actions on the attribute table, imo.
