### ISSUE TITLE
db manager table view duplicates

### ISSUE THREAD

**Issue by Jeroen-GroeneBij** [qgis/QGIS#40642]
Hi all,

After upgrading from qgis 3.10.4 to 3.16.1 I noticed two issues with DB Manager. I do not know if these are related, but they do co-exist.

edit: the other bug is described in #40643 

First is a bug in the DB Manager tab Table where you get a preview of the table.
I have narrowed it down to qgis 3.12.0 as the first version to have this bug, It doesn't exist in 3.10.12 or earlier, and it does exist in 3.14 and 3.16 as well.

The bug shows in all tables tested. The table view is duplicating some rows, without adding rows. So, a table with 300 rows and a primary key will still show 300 rows, but some rows are duplicated in the view and other are non-existent. Mind, it is only in the Table view. When queried, (select* from table order by primary key), the result is correct.
The duplication seems random over different tables, but is consistent per table. Selecting the same table after restarting, gives the exact same duplication. Exporting the table to a different database on a different machine, shows the exact same duplication in DB Manager on that machine.

I use qgis64 bit on windows 64bit machines. Database is a postgresql 11 with postgis 2.5

To reproduce:
use the following gpkg 
[gemeente2018kleinleeg.zip](https://github.com/qgis/QGIS/files/5708878/gemeente2018kleinleeg.zip)

It contains 380 rows, 4 fields including geom (fid,geom, gemcode,gemnaam)

Edited to clarify some steps:
Open the gpkg in qgis 3.12 or up
Open db manager, use the import-tool to import the layer into your own database
OR
Use the import tool from DB Manager to import the gpkg directly into your own database

After import, select the imported table in db manager
Open tab Table and check for duplicate rows

For me, a duplication is shown on row number 104 (fid 104, gemcode 0302, gemnaam Nunspeet), which is duplicated on row number 204 (the same fid 104, gemcode 0302, gemnaam Nunspeet)
There are more duplications.
And it gets worse: when clicking some of the rows it changes values sometimes, but not always. So clicking row 204 sometimes changes the values to a different fid with corresponding gemcode and gemnaam.

It is definitely a view issue. The data itself is not affected.

**Comment by raymondnijssen** [comment]
Hi Jeroen, I tried to reproduce this but some of the steps are unclear to me:
- Should I unzip the gpkg? (I did)
- What do you mean with "Import to database"? Making a new gpkg connection from the DB-manager (using "New Connection" from the GeoPackage context menu? Or are you really importing data from the gpkg to another database?
 
![image](https://user-images.githubusercontent.com/681851/102590789-56b6c480-4111-11eb-9930-2053703c80f5.png)

I tried this in a recent QGIS 3.17 and it looks like this. All id's seem correct.

**Comment by Jeroen-GroeneBij** [comment]
Thank you Raymond for trying. 
First thing I learned from this feedback is the geopackage option in DB Manager. I never noticed it before, nor used it.

Indeed, when opening the gpkg like you have, all looks good.

The issues arise after importing the layer into your own postgis database. I have never used the direct way of importing a gpkg, that is why my steps were first to open the gpkg in qgis. Then use db manager to import the layer into your database.
Then select that layer from your database and open Table view.

I just tested importing the layer directly from the gpkg file into my database (so without opening the gpkg in qgis) and the same issues are there. The data is transferred to the database correctly, it is just the Table view that shows duplicates.

The problem actually isn't with the data at all. I see this behaviour on many tables in my database. It seems to be related to the number of rows: I haven't seen this yet for tables less then a 100 rows or so, and I have seen it with lager tables. Maybe it just happens when scrolling through large tables and there is something weird with refreshing the view?

**Comment by gioman** [comment]
> The issues arise after importing the layer into your own postgis database.

@Jeroen-GroeneBij it may be important to know how you imported the data inti postgis from the gpkg. Using the drag and drop functionality in DB Manager? Using the import tool in DB Manager? Using the import tools in the Processing toolbox?

**Comment by Jeroen-GroeneBij** [comment]
Using the import tool in DB Manager

**Comment by gioman** [comment]
Ok, I see the duplication in the table preview of DB Manager.

**Comment by gioman** [comment]
See also https://github.com/qgis/QGIS/issues/23522

**Comment by willemhoffmans** [comment]
Hello Jeroen and others,

Indeed, something very strange happens. I imported a CBS dataset **gemeenten2020** from a geopackage. Did it by ogr2ogr, so NOT in DB Manager itself. But the Table View ends up with a complete mess, as this short movie shows. A whole lot of rows change into something different if you scroll downward en upward in the table view!

https://user-images.githubusercontent.com/20768892/114873414-8e9df200-9dfb-11eb-887e-5c90e16e0080.mp4

**Comment by alexbruy** [comment]
Can't reproduce with the latest master (096d741fe1) on Linux.

**Comment by Jeroen-GroeneBij** [comment]
Confirmed, can't reproduce either. Seems fixed. Thank you.
