### ISSUE TITLE
Can't install QGIS on Mac with Catalina 10.15.7

### ISSUE THREAD

**Issue by lewil11** [qgis/QGIS#40657]
is:issue is:open Hi, I'm new to QGIS and recently downloaded it. Now my Mac is upgraded to Catalina 10.15.7 and I can no longer install QGIS despite right clicking on the QGIS app icon and choosing Open on first launch on. Are there any plans to fix that? Best, Lena

**Comment by gioman** [comment]
Check your system security options, probably macOS is blocking QGIS to start.

**Comment by lewil11** [comment]
Thank you for replying so swiftly. I have looked there and QGIS doesn’t even show. And I’ve googled to be sure where to look. Any other ideas?

**Comment by lewil11** [comment]
Hi Giovanni,
Thank you for replying so swiftly. I have looked there and QGIS doesn’t even show. And I’ve googled to be sure where to look. Any other ideas?
Lena



Från: Giovanni Manghi <notifications@github.com>
Svara till: qgis/QGIS <reply@reply.github.com>
Datum: fredag 18 december 2020 16:24
Till: qgis/QGIS <QGIS@noreply.github.com>
Kopia: "lena.wilsby@lrfmedia.se" <lena.wilsby@lrfmedia.se>, Author <author@noreply.github.com>
Ämne: Re: [qgis/QGIS] Can't install QGIS on Mac with Catalina 10.15.7 (#40657)


Check your system security options, probably macOS is blocking QGIS to start.

**Comment by gioman** [comment]
> If they have, do you have any other suggestions?

no, it works just fine on my macOS catalina mac mini. Suggestion: post the question on the QGIS users mailing list.

**Comment by lewil11** [comment]
Thank you, Giovanni! I will. Have a niece weekend!

Skickat från min iPhone

18 dec. 2020 kl. 21:08 skrev Giovanni Manghi <notifications@github.com>:

﻿

If they have, do you have any other suggestions?

no, it works just fine on my macOS catalina mac mini. Suggestion: post the question on the QGIS users mailing list.
