### ISSUE TITLE
SVG QGIS logos are malformed

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#40659]
I have tested the new [SVG logos](https://github.com/qgis/QGIS/pull/40518) and have these results:

![image](https://user-images.githubusercontent.com/7631137/102635244-58a17780-4153-11eb-823e-70ee187c342b.png)

![image](https://user-images.githubusercontent.com/7631137/102635362-7e2e8100-4153-11eb-9274-6051c346b3d0.png)

**Comment by agiudiceandrea** [comment]
Hi @pigreco, it seems to me the svg logos added with https://github.com/qgis/QGIS/pull/40518 are correctly rendered by QGIS, while the minified ones subsequently introduced by https://github.com/qgis/QGIS/pull/40577 are weirdly rendered by QGIS. Do you confirm this different behavior?

**Comment by pigreco** [comment]
exact @agiudiceandrea the SVGs featured https://github.com/timlinux/QGIS/tree/4093cef2b90a48583d7f8884e854992af74d4be2/images/svg/logos are ok

**Comment by Korto19** [comment]
I confirm too
