### ISSUE TITLE
TIN interpolation crashes QGIS or creates empty output

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#40668]
Add the attached line layer

Interpolate the "elevation" attribute using "Break lines" or "structure lines" as type.

QGIS 3.10.12 crashes.

QGIS 3.16.1 creates an empty output.

If using "points" as type works 
[cn.zip](https://github.com/qgis/QGIS/files/5717883/cn.zip)
ok on both versions.

Tested on Windows 10.

**Comment by vcloarec** [comment]
#40670 seems fix this issue for 3.16.
For 3.10 ... too much deep changes is necessary...
