### ISSUE TITLE
Sometimes tiles in 3d map view are blank until refreshed

### ISSUE THREAD

**Issue by uclaros** [qgis/QGIS#40685]
**Describe the bug**
Sometimes when using a 3d map view, nothing is rendered in the view, or one of the rendered tiles is blank. Zooming/panning/rotating/resizing the 3d map window refreshes the view and fixes this.
This could be a local issue, not sure.

**How to Reproduce**
1. Open the attached project [tmp_project.zip](https://github.com/qgis/QGIS/files/5721623/tmp_project.zip)
2. Create a new 3d map view
3. The 3d map window is blank.
4. Resize the 3d map view / pan / zoom / rotate camera, and the 3d content is drawn

**QGIS and OS versions**
677ccf5a on debian testing

**Additional context**
This always happens when creating a new view for me, but sometimes, on larger maps, a single 3d tile is left blank in the view.

**Comment by nyalldawson** [comment]
It's not a local issue - I see it too

**Comment by roya0045** [comment]
@uclaros In my experience the blank view stays, see #40324, unsure if 'duplicate'

**Comment by nyalldawson** [comment]
@roya0045 #40324 is definitely a different issue - the issue described here results in just tiles missing temporarily, but otherwise working 3d view

**Comment by roya0045** [comment]
@nyalldawson ah right, well technically in my case all tiles were black/undisplayed. I'm unsure if the root cause is the same or not.

**Comment by Pedro-Murteira** [comment]
I was able to replicate this on QGIS 3.22.2. I've tested on QGIS 3.16.15 aswell, but had the same problem as @roya0045. Overall, this is still an actual bug.

**Comment by kannes** [comment]
I can not reproduce it with the project provided in the initial post but I see missing tiles or vanishing tiles (shown while "loading tiles" but gone once done) with some reasonably big extruded polygon datasets (~x00,000 features).

My terminal is full of messages like:
`src/core/qgsmessagelog.cpp:29 : (logMessage) [0ms] [thread:0x55c59ab6bbd0] 2022-07-29T20:54:30 3D[1] geometry's coordinates are too close to each other and simplification failed - skipping`

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>


QGIS version | 3.27.0-Master | QGIS code revision | 2e622be6f9c
-- | -- | -- | --
Qt version | 5.15.5
Python version | 3.10.5
GDAL/OGR version | 3.6.0dev-030ff40cf8-dirty
PROJ version | 9.0.1
EPSG Registry database version | v10.064 (2022-05-19)
GEOS version | 3.11.0-CAPI-1.17.0
SQLite version | 3.39.1
PDAL version | 2.4.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.2.0
QScintilla2 version | 2.13.3
OS version | Arch Linux

</body></html>

**Comment by wonder-sk** [comment]
@uclaros this seems to be the same issue as #48334 right?

**Comment by uclaros** [comment]
I'm not sure if it's the same or related.
For me, using the attached project, the newly opened 3d view is completely blank until I move the mouse cursor within the view :confused: . But I remember that when I opened the issue, I needed to pan/rotate the view in order to get it to appear, but camera control has changed a lot since then.

I would track those two in parallel as separate issues.
