### ISSUE TITLE
re-enable the "use min covering extent from input layers" option in Processing

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#40717]
Was available in 3.10 and disappeared in 3.16.

**Comment by roya0045** [comment]
Is that for extent parameters or something else that I can't recall?

**Comment by nyalldawson** [comment]
Really all it did was set the parameter value as "none" - ie the same as if the parameter was made optional and left unspecified.

@gioman I think this should be closed, and replaced with specific tickets for algorithms were the extent is non optional yet should be optional...

**Comment by gioman** [comment]
> Really all it did was set the parameter value as "none" - ie the same as if the parameter was made optional and left unspecified.
> 
> @gioman I think this should be closed, and replaced with specific tickets for algorithms were the extent is non optional yet should be optional...

@nyalldawson not sure if I explained well the request. In 3.10 the "use min covering extent from input layers" option appears in any Processing module that has the "extent" parameter and multiple rasters as input, like the QGIS raster calculator. But this option actually does not work (which I guess configures as a bug)... if the option was removed as bugged then this ticket should be left open, as it was convenient to have... but if there is any other good reason to not have anymore than I guess we can close.

3.10
![Screenshot_20210102_171946](https://user-images.githubusercontent.com/1951107/103462810-b4592c80-4d1f-11eb-9c49-95c01437cc66.png)

3.16
![Screenshot_20210102_172103](https://user-images.githubusercontent.com/1951107/103462814-b8854a00-4d1f-11eb-82c3-09819a046b24.png)

**Comment by nyalldawson** [comment]
@gioman the explanatory text  in 3.10 also shows my findings -- the setting is identical to having the parameter value as "not set". So the issue is in one or more particular algorithms (and probably has always been the case for those algorithms). If you can identify them then I can check...

**Comment by gioman** [comment]
@nyalldawson for now only found it in QGIS raster calc and GRASS r.mapcalc.simple

**Comment by nyalldawson** [comment]
@gioman qgis raster calc looks fine to me -- if the extent is not set then it is calculated using all input layers. Are you able to provide a sample where this fails?

**Comment by gioman** [comment]
> @gioman qgis raster calc looks fine to me -- if the extent is not set then it is calculated using all input layers. Are you able to provide a sample where this fails?

@nyalldawson I probably always interpreted the wrong way how this option works. Sorry for the noise. 

Note: in QGIS raster calc the parameter "output extent" is not really optional (it is in fact mandatory as the output cellsize and output CRS, never fully understand why they show as "optional" in their labels), so leaving it to "not set" does not allow the tool to run... and there is no option to set the extent to the one covered by all inputs... not sure of this configures as bug.
