### ISSUE TITLE
WMS title and abstract is not displayed for WMS provided by QGIS Server

### ISSUE THREAD

**Issue by pathmapper** [qgis/QGIS#40736]
**Describe the bug**
WMS title is not displayed in QGIS browser for WMS provided by QGIS Server.

**How to Reproduce**

1. Create a new WMS connection using the URL: http://168.119.115.196/cgi-bin/missing_title/qgis_mapserv.fcgi
2. Open the connection in QGIS browser
3. See error --> Title is not displayed:

<img src="https://user-images.githubusercontent.com/20856381/102983507-76ccf600-450c-11eb-9b20-0be0c7ce9dd2.png" width="500">

Using a browser to request the GetCapabilities document, the title is there:
http://168.119.115.196/cgi-bin/missing_title/qgis_mapserv.fcgi?service=WMS&version=1.3.0&request=GetCapabilities

<img src="https://user-images.githubusercontent.com/20856381/102983746-d4614280-450c-11eb-9ab8-3f1febf569b6.png" width="700">

**QGIS and OS versions**

QGIS version | 3.16.2-Hannover | QGIS code revision | f1660f9da5
-- | -- | -- | --
Compiled against Qt | 5.11.3 | Running against Qt | 5.11.3
Compiled against GDAL/OGR | 2.4.0 | Running against GDAL/OGR | 2.4.0
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.27.2 | Running against SQLite | 3.27.2
PostgreSQL Client Version | 11.9 (Debian 11.9-0+deb10u1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.10.4
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Debian GNU/Linux 10 (buster)
Active python plugins | ClipMultipleLayers; quick_map_services; scriptrunner3; LAStools; canvas_clipper; savedialog; loadthemall; clipper; kmltools; qgis-maptiler-plugin; MapsPrinter; Discovery; mmqgis; pluginbuilder3; vector_tiles_reader; layerGroupFilter; plugin_reloader; realcentroid; mask; QuickOSM; MetaSearch; db_manager; processing

**Additional context**

[project_and_data_used_for_qgis_server.zip](https://github.com/qgis/QGIS/files/5734481/project_and_data_used_for_qgis_server.zip)

---

For other WMS the title is displayed in QGIS browser, e.g.:
https://www.wms.nrw.de/geobasis/wms_nw_dop

<img src="https://user-images.githubusercontent.com/20856381/102984347-be07b680-450d-11eb-901c-0d6d42d83c91.png" width="400">

https://www.wms.nrw.de/geobasis/wms_nw_dop?service=WMS&version=1.3.0&request=GetCapabilities

<img src="https://user-images.githubusercontent.com/20856381/102984556-0b842380-450e-11eb-994b-a2e7bb14d0c0.png" width="700">

**Comment by gioman** [comment]
It is not a Browser only issue, "title" and "abstract" also do not show in the "add WMS layer" dialog when establishing a connection.

**Comment by pathmapper** [comment]
Good find @gioman, added also **Abstract** and **Short name** to the sample project:

[sample_project_title_abstract.zip](https://github.com/qgis/QGIS/files/5735048/sample_project_title_abstract.zip)

<img src="https://user-images.githubusercontent.com/20856381/102995420-46438700-4521-11eb-9c44-576ec261bff6.png" width="400">


http://168.119.115.196/cgi-bin/missing_title/qgis_mapserv.fcgi?service=WMS&version=1.3.0&request=GetCapabilities

![grafik](https://user-images.githubusercontent.com/20856381/102995714-ee595000-4521-11eb-82f7-f2e0912e9393.png)

---

**Short name** is displayed in the "add WMS layer" dialogue where **Title** and **Abstract** are missing:

<img src="https://user-images.githubusercontent.com/20856381/102995589-adf9d200-4521-11eb-96cf-c0a90db865df.png" width="300">

Also tried the sample QGIS Server WMS using **another** GIS software and the **Abstract** and **Title** are displayed:

![grafik](https://user-images.githubusercontent.com/20856381/102996022-93742880-4522-11eb-9218-aeeb4ed49858.png)


## Summary
| software        | title          | abstract  |
| :------------- |:-------------| -----|
| QGIS Desktop 3.16.2      | :x:  | :x:  |
| Firefox Browser (getCapabilities)      |    :heavy_check_mark:   |   :heavy_check_mark: |
| another GIS software     |   :heavy_check_mark:  |:heavy_check_mark:|

**Comment by pathmapper** [comment]
After taking a closer look at the [OpenGIS Web Map Service (WMS) Implementation Specification](http://portal.opengeospatial.org/files/?artifact_id=14416) it's getting clearer what's happening here:

1. 
QGIS **Desktop** doesn't show _Title_ and _Abstract_ of the `<Service>` element (spec 7.2.4.3. General service metadata) for QGIS Browser and the "add WMS layer" dialogue at all. Instead it is showing _Title_ and _Abstract_ of the available layers including parent layers.
Regarding parent layers, from spec 7.2.4.5 (Layers and styles): 
> Each  available  map  is  advertised  by  a  <Layer>  element  in  the  service  metadata.  Conceptually,  each  Layer  is  a  distinct entity. However, as a means of classifying and organizing layers, and as a means of reducing the size of the  service  metadata,  a  single  parent  Layer  may  enclose  any  number  of  additional  layers,  which  may  be  hierarchically  nested  as  desired.

Looks like in the project properties the term _root layer_ is used instead of _parent layer_ (for the _Short name_ field).

2.
 QGIS **Server** adds a  _parent/root layer_ using the _Short name_ field of the project properties for  `<Name>`, but it doesn't include  `<Title>` and `<Abstract>` for this _parent/root layer_ for getCapabilities and there's no way to set them in the project properties.

<img src="https://user-images.githubusercontent.com/20856381/103062317-17bfbd80-45ae-11eb-8418-9194eb257367.png" width="500">


Spec 7.2.4.6.2
> A  `<Title>`  is  mandatory  for  all  layers

Spec 7.2.4.6.4
> The optional `<Abstract>` and `<KeywordList>` elements are optional, but a server should provide them.

A solution here might be  to use  _Title_ and _Abstract_ defined in project properties also for  `<Title>` and `<Abstract>`  of the _parent/root layer_.
