### ISSUE TITLE
Install QGIS with libogdi

### ISSUE THREAD

**Issue by HanwGeek** [qgis/QGIS#40730]
**Describe the bug**

I install `QGIS` in Ubuntu18.04, but it says:
```shell
/usr/lib/qgis/crssync: error while loading shared libraries: libogdi.so.3.2: cannot open shared object file: No such file or directory
```
And when I install `libogdi3.2`, then install `QGIS`. It removes `libogdi3.2` and install `libogdi4.1`
```shell
Removing libogdi3.2 (3.2.0+ds-2) ...
Selecting previously unselected package libogdi4.1.
(Reading database ... 467797 files and directories currently installed.)
Preparing to unpack .../00-libogdi4.1_4.1.0+ds-1~bionic0_amd64.deb ...
Unpacking libogdi4.1 (4.1.0+ds-1~bionic0) ...
```
But then it requires me `libogdi3.2` again. What should I do to fix this? Thanks!
**How to Reproduce**

`sudo apt-get install QGIS`

**QGIS and OS versions**
OS: Ubuntu18.04

**Additional context**

**Comment by gioman** [comment]
@HanwGeek no problems whatsoever on a clean 18.04 machine using qgis.org repos.
