### ISSUE TITLE
Bizarre behavior of Decorations/Scale Bar

### ISSUE THREAD

**Issue by zirneklitis** [qgis/QGIS#40748]
**Describe the bug**
Decoration -> Scale Bar uses a misleading planimetric measurement. 'Zoom last' corrects the measurement.

Zooming or panning does not change the incorrectness of the measurement. 'Zoom last' does.

**How to Reproduce**

1. Open the attached project (Scale_Bar.zip).
2. Try to Zoom or/and pan the canvas.
3. -> Wrong planimetric measurement.
4. Try to use Zoom history.
5. -> The planimetric measurement is correct now

**QGIS and OS versions**

QGIS 3.16.0 / Fedora 32 x64
QGIS 3.14.16 / Fedora 28 x64
QGIS 3.16.2 / Windows 7 Enterprise x64

**Additional context**

There was no such strange behaviour while using  QGIS 3.12 / Windows 7 Enterprise x64.

![about-14-Linux](https://user-images.githubusercontent.com/3538610/103065508-64f85b00-45bf-11eb-9880-d8788cc0ed0f.png)
![about-16-Linux](https://user-images.githubusercontent.com/3538610/103065510-6590f180-45bf-11eb-904f-a19a2ea13f6c.png)
![about-Windows](https://user-images.githubusercontent.com/3538610/103065511-66298800-45bf-11eb-80a2-b00baa539361.png)

https://user-images.githubusercontent.com/3538610/103065512-66298800-45bf-11eb-8035-6ad00168174a.mp4

![scalebar](https://user-images.githubusercontent.com/3538610/103065513-66c21e80-45bf-11eb-87ef-e9293167d6ac.png)
[Scale_Bar.zip](https://github.com/qgis/QGIS/files/5738390/Scale_Bar.zip)

https://user-images.githubusercontent.com/3538610/103065514-67f34b80-45bf-11eb-9bc8-69f9e9d372c3.mp4

**Comment by agiudiceandrea** [comment]
I can confirm the regression. The Scale Bar map decoration correctly works up to QGIS 3.12.3. The issue occurs since QGIS 3.14.0.

**Comment by fred4x4** [comment]
Never knowingly used before, but Zoom Last is my saviour - many thanks!"!
I just newly instaklled installed 3.16.2 in case it fixed the problem in the LTR 3.10.13 (but it didn't).
I can reproduce this fault very simply with:-
------------------------------------------------
launch QGIS 3.16.2
Project / New
Layer / Add Layer / Add Vector Layer
=> Source ...
=>=> LAY-BAS150-55.shp
=>=> Open
=> Add Close
View / Decorations / Grid...
=> Enable Grid : checked
=> X : 10000
=> Y : 10000
=> OK
View / Decorations / Scale Bar...
=> Enable Scale Bar : checked
=> OK
------------------------------------------------
Layer is just four corrdinates of a rectangle for Brintish National Grid (EPSG 27700) converted to a path with the integrated Points to Path tool. 7Zipped shape files attached. png screenshot before Zoom Last also attached.
![40748](https://user-images.githubusercontent.com/77586007/104853435-c11d7900-58f8-11eb-8548-acc660f0b5e2.png)
[LAY-BAS150-55.zip](https://github.com/qgis/QGIS/files/5826644/LAY-BAS150-55.zip)

Thx Martin.

**Comment by agiudiceandrea** [comment]
I think the regression was inadvertently introduced with PR https://github.com/qgis/QGIS/pull/37084.

**Comment by fred4x4** [comment]
Sorry - I left the grid X and Y at 30km each in the picture.
Scale Bar should have been the same lentgth as one side of a grid square, but is clearly not.
Thx for your quick acknowledgement Andrea.
