### ISSUE TITLE
Abnormal hanging and Python error

### ISSUE THREAD

**Issue by Fuad59** [qgis/QGIS#40740]
IMPORTANT:

If the issue concerns a third party plugin (downloaded with the plugin manager) then it can't be fixed by the QGIS team.
Please raise your issue in the dedicated bug tracker for that specific plugin (as listed in the plugin's description)

Tickets created here will be closed.
I have installed some plugin from the dedicated "plugins" option. After that getting Python error messages. (i.e. 2020-12-23T21:14:46     WARNING    Python error : Couldn't load plugin 'qgis_gee_data_catalog' due to an error when calling its classFactory() method See message log (Python Error) for more details). 
.----2020-12-23T21:14:44     WARNING    warning:C:/Users/forest/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GlobeBuilder\definitions\settings.py:54: DeprecationWarning: QgsCoordinateReferenceSystem.createFromId() is deprecated
              _crs.createFromId(4326))
And the Qgis is stopping abnormally and getting hang most of the time. Please, give me suggestion to solve this problem.

**Comment by gioman** [comment]
Error is from a 3rd party plugin, not QGIS. Contact the authors.

**Comment by Fuad59** [comment]
Thanks for the feedback
