### ISSUE TITLE
Add 'Average' resampling to raster symbology

### ISSUE THREAD

**Issue by jscarto** [qgis/QGIS#40746]
**Feature description.**
QGIS versions 3.14 and prior had 'average' resampling as an option when zoomed out. Apparently some changes to the drop-down text removed that and now calls it bilinear.

It would be fantastic to have true 'average' resampling added (back) to this menu.

**Additional context**
There must have been more than just a text change, as the current (QGIS 3.16) bilinear resampling is not doing the same thing as the previous (QGIS 3.14 and prior) average resampling, as shown below.

In this example, all panels are from QGIS 3.16 except the last, which is from QGIS 3.14. The average and bilinear results are not the same, and some functionality has been lost along the way. Getting this back would be incredible and much appreciated.

![resampling](https://user-images.githubusercontent.com/1316770/103030287-7f7ff500-4529-11eb-81aa-4cf7d7d9dd9d.png)

**Comment by monticola2** [comment]
I'd appreciate this, too. I am now getting some artefacts with bilinear und cubic resampling that were not there with average before.

**Comment by monticola2** [comment]
Okay, I found the solution for my problem - I had enabled "early resampling". Disabling it (in QGIS 3.16.3) renders the raster just like the old average. It seems the problem is the early resampling.

**Comment by monticola2** [comment]
Another note: When the raster is reprojected OTF (i.e. project crs not the same as raster crs), the artefacts stay no matter whether "early resampling" is enabled or disabled.

**Comment by gioman** [comment]
> Another note: When the raster is reprojected OTF (i.e. project crs not the same as raster crs), the artefacts stay no matter whether "early resampling" is enabled or disabled.

@monticola2 this is a longstanding known issue.

**Comment by monticola2** [comment]
> 
> 
> > Another note: When the raster is reprojected OTF (i.e. project crs not the same as raster crs), the artefacts stay no matter whether "early resampling" is enabled or disabled.
> 
> @monticola2 this is a longstanding known issue.

I don't get these artefacts/false colours with QGIS 3.10.13 and average resampling in a reprojected raster.

**Comment by jscarto** [comment]
> I don't get these artefacts/false colours with QGIS 3.10.13 and average resampling in a reprojected raster.

Same here as recently as 3.14. Perhaps the devs were aware of this for a while, but it is completely new and unfortunately undocumented behavior for users.

I think the big issue is there is no indication to the user that the new rendering options are so dependent on all layers and the project having the same projection, and that it will not work as it used to/as expected with OTF projection.

A warning in the UI could go a long way to prevent this confusion until the resampling options once again work as expected with OTF projection.

**Comment by monticola2** [comment]
Unfortunately, I am getting similar artefacts to the ones from bilinear using the new average resampling option (only available with early resampling enabled) in 3.18.0.

**Comment by EJFielding** [comment]
Is there an explanation somewhere about what the `early resampling` option in 3.18 is supposed to do? I did a search and ended up on this GitHub issue page.
