### ISSUE TITLE
Sorry :( It looks something unexpected happened that we didn't handle and QGIS ended unexpectedly.

### ISSUE THREAD

**Issue by mvdsvnit** [qgis/QGIS#40762]
Crash ID: ca44fc1770ff62f76b908ae8ab2f255b15b2cc4f

Stack Trace

QgsExpression::evaluate qgsexpression.cpp:360
QgsGraduatedSymbolRenderer::valueForFeature qgsgraduatedsymbolrenderer.cpp:138
QgsGraduatedSymbolRenderer::originalSymbolForFeature qgsgraduatedsymbolrenderer.cpp:150
QgsFeatureRenderer::willRenderFeature qgsrenderer.cpp:366
QgsMapTip::fetchFeature qgsmaptip.cpp:243
QgsMapTip::showMapTip qgsmaptip.cpp:119
QgisApp::showMapTip qgisapp.cpp:14225
QMetaObject::activate :
QTimer::timerEvent :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32Private::sendTimerEvent :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1637
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.16.1-Hannover
QGIS code revision: b381a90dca
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.3.9600

**Comment by roya0045** [comment]
Can you share the data or the symbology/project that crashes? Is it consistent and did you try with a new profile to ensue no plugins interfere?

**Comment by gioman** [comment]
@mvdsvnit please add:



**Describe the bug**


**How to Reproduce**



1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error -->

**QGIS and OS versions**



**Additional context**

**Comment by mvdsvnit** [comment]
Now I am using QGIS 3.10 stable version. No issues in it.

Thanks

**Comment by roya0045** [comment]
@gioman This may be a regression if 3.10 is fine and 3.16.1 crashes. It should be investigated.

**Comment by gioman** [comment]
@mvdsvnit please describe how to replicate the crash, and if necessary attach a sample project with data.

**Comment by m-kuhn** [comment]
@mvdsvnit if you have any chance to submit a sample project here that would be great. I have fixed a potential issue and it would be great if I could verify it with your project.
