### ISSUE TITLE
Where I can get the development kit (headers, libs, bins) for QGis 3.4.10 x64?

### ISSUE THREAD

**Issue by softempire** [qgis/QGIS#40765]
IMPORTANT:

Do NOT use GitHub to post any questions or support requests!
They will be closed immediately and ignored.
Questions should go to the qgis-user mailing list at https://lists.osgeo.org/mailman/listinfo/qgis-user
or other support forums such as https://gis.stackexchange.com/.

GitHub issues are for bug reports and suggestions for new features.

**Comment by gioman** [comment]
@softempire questions are to be asked in the users/developers mailing lists.
