### ISSUE TITLE
Field Calculator in Processing toolbox crashes QGIS when checking the "selected features only"

### ISSUE THREAD

**Issue by yuvrajsunger** [qgis/QGIS#40763]
**Bug Description**
QGIS Crashes upon selecting the "Selected features only" option for Input layer of the Field Calculator Algorithm.

**How to Reproduce**

1. Go to 'Processing Toolbox' and open 'Field Calculator' Algorithm.
2. Click on "Selected features only" option for Input layer.
3. QGIS stops responding and crashes after sometime.

![image](https://user-images.githubusercontent.com/52693754/103148627-c834e980-4787-11eb-9cee-7d832cb0215b.png)
![image](https://user-images.githubusercontent.com/52693754/103148665-3f6a7d80-4788-11eb-9c81-102715f31f54.png)
![image](https://user-images.githubusercontent.com/52693754/103148681-65901d80-4788-11eb-9f7a-c001c36f0994.png)

**QGIS and OS versions**

QGIS version
3.16.1-Hannover
QGIS code revision
b381a90dca
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
AnotherDXF2Shape; 
QuickOSM; 
QuickPrint; 
quick_map_services; 
SRTM-Downloader; 
db_manager; 
MetaSearch; 
processing

**Additional context: Crash Report**

Crash ID: 7f18ff2b84d715258f8322aced552bfe828742ff

Stack Trace

QgsVectorLayer::displayExpression qgsvectorlayer.cpp:3546
QgsFeaturePickerModelBase::setSourceLayer qgsfeaturepickermodelbase.cpp:57
QgsExpressionBuilderWidget::setLayer qgsexpressionbuilderwidget.cpp:286
QgsProcessingExpressionWidgetWrapper::setParentLayerWrapperValue qgsprocessingwidgetwrapperimpl.cpp:2011
QMetaObject::activate :
QgsAbstractProcessingParameterWidgetWrapper::widgetValueHasChanged moc_qgsprocessingwidgetwrapper.cpp:160
QMetaObject::activate :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::setChecked :
QCheckBox::nextCheckState :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QMetaObject::activate :
QAbstractItemView::doubleClicked :
QTreeView::mouseDoubleClickEvent :
sipQgsProcessingToolboxTreeView::mouseDoubleClickEvent sip_guipart2.cpp:95416
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
sipQgsProcessingToolboxTreeView::viewportEvent sip_guipart2.cpp:95953
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1637
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.16.1-Hannover
QGIS code revision: b381a90dca
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by roya0045** [comment]
Confirmed crash on win 10 @suricactus do you have any clues what might cause this? I assume its related to QgsProcessingFeatureSource

**Comment by gioman** [comment]
Confirmed also on 3.16.2 on Ubuntu 20.04.
