### ISSUE TITLE
MetaSearch: "Could not create crs: urn:ogc:def:crs:OGC:1.3:CRS84" error when a bounding box is specified

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/QGIS#40778]
**Describe the bug**

When a bounding box is specified (i.e. setting Xmin, Xmax, Ymin, Ymax different from -180, 180,
-90, 90) in the "Search" tab of the MetaSearch Catalog Client plugin, with almost all the CSW default Catalog Services the search request gets no result and they throw an error similar to the following one:

`Search error: 'Raised exception while searching metadata : org.fao.geonet.csw.common.exceptions.NoApplicableCodeEx: code=NoApplicableCode, locator=null, message=Error when parsing spatial filter (version: 1.1.0):<ogc:Filter xmlns:ogc="http://www.opengis.net/ogc">\r\n <ogc:And>\r\n <ogc:BBOX>\r\n <ogc:PropertyName>ows:BoundingBox</ogc:PropertyName>\r\n <gml:Envelope xmlns:gml="http://www.opengis.net/gml" srsName="urn:ogc:def:crs:OGC:1.3:CRS84">\r\n <gml:lowerCorner>5.7043393 58.853735</gml:lowerCorner>\r\n <gml:upperCorner>5.7544107 58.883453</gml:upperCorner>\r\n </gml:Envelope>\r\n </ogc:BBOX>\r\n <ogc:PropertyIsLike wildCard="%" singleChar="_" escapeChar="\\">\r\n <ogc:PropertyName>csw:AnyText</ogc:PropertyName>\r\n <ogc:Literal>barnehage</ogc:Literal>\r\n </ogc:PropertyIsLike>\r\n </ogc:And>\r\n</ogc:Filter>. Error is: java.lang.RuntimeException: Parsing failed for Envelope: java.lang.RuntimeException: Could not create crs: urn:ogc:def:crs:OGC:1.3:CRS84'`

See also the thread at https://lists.osgeo.org/pipermail/qgis-user/2020-December/047589.html on qgis-user mailing list.

The issue occurs with all the CSW default Catalog Services except Italy, New Zealand and USA national CSWs.

**QGIS and OS versions**

QGIS 3.10 and QGIS 3.16

**Comment by roya0045** [comment]
So you're suggesting that a conversion step to wgs84 should always be done for the bounding box?

**Comment by agiudiceandrea** [comment]
@roya0045 the issue is due to the fact that the string "urn:ogc:def:crs:OGC:1.3:CRS84" used as crs identifier is not recognised by most of the default CSW servers.

**Comment by pvgenuchten** [comment]
hi @agiudiceandrea, thanks for reporting. many of the catalogues you mention are based on geonetwork. the [issue](https://github.com/geonetwork/core-geonetwork/pull/4488) in older version of geotools was reported a while back and has been resolved and will be released in the upcoming 3.12 release
