### ISSUE TITLE
Near-Sided CRS projections fail (attempted forward projection from (inf, inf))

### ISSUE THREAD

**Issue by spillner** [qgis/QGIS#40771]
After giving up on 3D mode for a while (https://github.com/qgis/QGIS/issues/40766), I tried to simulate what I need with the Near-Sided projection family supported by proj4.  However, both of the Near-Sided projections distributed with QGIS (ESRI:53049 and ESRI:54049) generate an "Exception" dialog with the error message

    forward transform of (inf, inf)
    Error: Fallback transform failed

Steps to reproduce:
1. Load any vector dataset (for testing, I'm using https://hub.arcgis.com/datasets/UIA::uia-latitude-longitude-graticules-and-world-countries-boundaries)
2. Open the Project Properties and select the CRS tab (e.g. using the projection button on the bottom-right)
3. Select either of the Near-Sided options (ESRI:53049 or ESRI:54049) and hit OK
4. Attempt to manipulate the Map View pane in any way that will force a redraw (e.g. pan or zoom)
5. Observe the Exception dialog described above.  Rather than shifting to a Near-Sided perspective, the previous bitmap is still shown in the Map View pane.
6. If you shift from one Near-Sided projection to the other, the MapView pane will clear (all white)
7. If you shift back to another type of projection, the MapView will redraw and behave normally.
8. You can then loop back to step 2 of this procedure and observe the same error behavior again.

QGIS and OS versions:
QGIS version | 3.16.2-Hannover | QGIS code revision | f1660f9da5
-- | -- | -- | --
Compiled against Qt | 5.12.8 | Running against Qt | 5.12.8
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.5 (Ubuntu 12.5-0ubuntu0.20.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Ubuntu 20.04.1 LTS
Active python plugins | MetaSearch; db_manager; processing

**Comment by nyalldawson** [comment]
This is an upstream proj issue -- it's fixed in newer proj versions

**Comment by spillner** [comment]
Can confirm these projections work after building QGIS against Proj 7.2, thanks!
