### ISSUE TITLE
QGIS unexpectly ended

### ISSUE THREAD

**Issue by weixiaojun2020** [qgis/QGIS#40770]
QGIS always crashed when i start it, i don know why. Below are the crash infomation.

Crash ID: ccaa86226c1c7e7c84b4af34d882fbbb30464718

Stack Trace

QRingBuffer::reserve :
QSslEllipticCurve::shortName :
QMetaObject::activate :
QAbstractSocket::disconnected :
QAbstractSocket::canReadLine :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
QEventLoop::exec :
QThread::exec :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.10.13-A Coru?a
QGIS code revision: 311f3bbade
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by gioman** [comment]
@weixiaojun2020 try removing manually the QGIS profiles folders (if you have important things in there, make a backup first) and try again.

`AppData\Roaming\QGIS\QGIS3\profiles\`

**Comment by weixiaojun2020** [comment]
Thanks a lot! I will try. -------- 原始邮件 --------发件人： Giovanni Manghi <notifications@github.com>日期： 2020年12月28日周一 02:21收件人： qgis/QGIS <QGIS@noreply.github.com>抄送： weixiaojun2020 <15653820425@163.com>, Mention <mention@noreply.github.com>主    题： Re: [qgis/QGIS] QGIS unexpectly ended (#40770)
@weixiaojun2020 try removing manually the QGIS profiles folders (if you have important things in there, make a backup first) and try again.
AppData\Roaming\QGIS\QGIS3\profiles\

**Comment by weixiaojun2020** [comment]
Sorry. but I did not find this folder. could you please tell me where is it? -------- 原始邮件 --------发件人： Giovanni Manghi <notifications@github.com>日期： 2020年12月28日周一 02:21收件人： qgis/QGIS <QGIS@noreply.github.com>抄送： weixiaojun2020 <15653820425@163.com>, Mention <mention@noreply.github.com>主    题： Re: [qgis/QGIS] QGIS unexpectly ended (#40770)
@weixiaojun2020 try removing manually the QGIS profiles folders (if you have important things in there, make a backup first) and try again.
AppData\Roaming\QGIS\QGIS3\profiles\

**Comment by gioman** [comment]
> Sorry. but I did not find this folder. could you please tell me where is it?

@weixiaojun2020 it is in your Windows user folder:

c:\users\**yourusername**\AppData\Roaming\QGIS\QGIS3\profiles\

**Comment by weixiaojun2020** [comment]
ok. thanks a lot!发自我的华为手机-------- 原始邮件 --------发件人： Giovanni Manghi <notifications@github.com>日期： 2020年12月30日周三 03:57收件人： qgis/QGIS <QGIS@noreply.github.com>抄送： weixiaojun2020 <15653820425@163.com>, Mention <mention@noreply.github.com>主    题： Re: [qgis/QGIS] QGIS unexpectly ended (#40770)

Sorry. but I did not find this folder. could you please tell me where is it?

@weixiaojun2020 it is in your Windows user folder:
c:\users*yourusername*\AppData\Roaming\QGIS\QGIS3\profiles\
