### ISSUE TITLE
QGIS crashes when removing vertex of a multipart geometry in qgis 3.16

### ISSUE THREAD

**Issue by gulab402** [qgis/QGIS#40783]
The crash occurs when removing vertices of a multipart geometry.
The multipart geometry was created with the Merge selected features tool.

Crash ID: cbbdf4dc1d1c76df53148e01cc03c42d5832a57c

Stack Trace
QgsGeometryValidator::checkRingIntersections :
QgsGeometryValidator::validatePolygon :
QgsGeometryValidator::run :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.16.0-Hannover
QGIS code revision: 43b64b13f3
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by nyalldawson** [comment]
Upgrade to 3.16.2 - this is fixed already
