### ISSUE TITLE
Ubuntu 20.04 Couldn't load SIP module. Python support will be disabled.

### ISSUE THREAD

**Issue by AdeSupriyadi** [qgis/QGIS#40782]
Everytime start QGIS always appeare popup error message:

Couldn't load SIP module.
Python support will be disabled.

Traceback (most recent call last):
  File "", line 1, in 
ModuleNotFoundError: No module named 'qgis'

Python version:
3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0]

QGIS version:
3.16.2-Hannover 'Hannover', f1660f9da5

Python path:
['/usr/share/qgis/python', '/home/ade/.local/share/QGIS/QGIS3/profiles/default/python', '/home/ade/.local/share/QGIS/QGIS3/profiles/default/python/plugins', '/usr/share/qgis/python/plugins', '/home/linuxbrew/.linuxbrew/Cellar/python@3.8/3.8.6_1/lib/python38.zip', '/home/linuxbrew/.linuxbrew/Cellar/python@3.8/3.8.6_1/lib/python3.8', '/home/linuxbrew/.linuxbrew/Cellar/python@3.8/3.8.6_1/lib/python3.8/lib-dynload', '/home/linuxbrew/.linuxbrew/Cellar/python@3.8/3.8.6_1/lib/python3.8/site-packages']

![image](https://user-images.githubusercontent.com/14267724/103258256-0a983980-49c7-11eb-94b7-f47fb45f7699.png)

and All plugins was lose

QGIS 3.16.2-Hannover
OS: ubuntu 20.04

![image](https://user-images.githubusercontent.com/14267724/103258404-64006880-49c7-11eb-875e-d4c7c5c07189.png)

**Comment by esohkevin** [comment]
Just an idea that worked for me, not sure if it will for you - try deactivating all virtual python environments before starting qgis

**Comment by roya0045** [comment]
Possible  local dependencies conflict/issues.

**Comment by gioman** [comment]
@AdeSupriyadi this is certainly a local issue. QGIS installs with no issues on Ubuntu 20.04 using the qgis.org repos (and not having other libraries installed manually so they can conflict with the official packages).
