### ISSUE TITLE
my qgis can't open any system in vector(o), what is the problem? My qgis version is 31.6

### ISSUE THREAD

**Issue by lljy1027** [qgis/QGIS#40797]
IMPORTANT:

Do NOT use GitHub to post any questions or support requests!
They will be closed immediately and ignored.
Questions should go to the qgis-user mailing list at https://lists.osgeo.org/mailman/listinfo/qgis-user
or other support forums such as https://gis.stackexchange.com/.

GitHub issues are for bug reports and suggestions for new features.

**Comment by Gustry** [comment]
> Do NOT use GitHub to post any questions or support requests!
They will be closed immediately and ignored.

As written above.

**Comment by lljy1027** [comment]
I'm so sorry about that.
I'm a newbie in github and qgis, can you teach me where to post the problem?

Étienne Trimaille <notifications@github.com> 于 2020年12月30日周三 下午2:14写道：

**Comment by Gustry** [comment]
> I'm a newbie in github and qgis, can you teach me where to post the problem?

Everything is written in your first post.
gis.stackexchange.com is a good place.

**Comment by lljy1027** [comment]
Ok, I'll check it out.
Thank you

Étienne Trimaille <notifications@github.com> 于 2020年12月30日周三 下午2:22写道：
