### ISSUE TITLE
Selection tool is not time aware

### ISSUE THREAD

**Issue by CoryAlbrecht** [qgis/QGIS#40818]
**Describe the bug**
When selecting a feature in a layer for which the new temporal controller (NTC) is activated, the selection tool selects all possible features in the chosen area including features which were filtered out by the NTC and are not visible on the map. It should only be selecting the visible feature.

Initial layer with temporal objects:
![image](https://user-images.githubusercontent.com/8172909/103447530-7c3be600-4c5a-11eb-8528-a29498abd676.png)
Selecting a feature:
![image](https://user-images.githubusercontent.com/8172909/103447574-06844a00-4c5b-11eb-8a1e-874fd7c7bfe6.png)
Selected feature:
![image](https://user-images.githubusercontent.com/8172909/103447560-dd63b980-4c5a-11eb-94b8-353ccec43d9a.png)
Pasted features:
![image](https://user-images.githubusercontent.com/8172909/103447598-54994d80-4c5b-11eb-896b-45f2d171979d.png)

**How to Reproduce**
1. make a layer with temporally-scoped features that overlap physically but not temporally
2. turn on the new temporal controller and chose a time frame where only 1 feature shows
3. use the freehand selection tool to select the feature, but make sure you "unknowingly" make the selection area go over top of features that are invisible because they were filtered out by the NTC
4. copy the selected "feature"
5. make a scratch layer
6. paste the selected feature and see the notice that you pasted multiple features

**QGIS and OS versions**
QGIS version | 3.17.0-Master | QGIS code revision | 5deda1f456
-- | -- | -- | --
Compiled against Qt | 5.12.8 | Running against Qt | 5.12.8
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
Compiled against PDAL | 2.0.1 | Running against PDAL | 2.0.1 (git-version: Release)
PostgreSQL Client Version | 12.5 (Ubuntu 12.5-0ubuntu0.20.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Ubuntu 20.04.1 LTS | This copy of QGIS writes debugging output.
Active python plugins | ImageServerConnector; db-style-manager; AzimuthDistanceCalculator; cartography_tools; quick_map_services; qgis-maptiler-plugin; QuickOSM; bettereditor; BackupLayer; OSMDownloader; deactivate_active_labels; Discovery; processing; db_manager; MetaSearch

**Comment by CoryAlbrecht** [comment]
If you're pasting back to the layer that is new temporal controller (NTC) enabled, you won't see all of them. You'll only see that single object you expected to singularly selected and none of the others. They are still there, though, and will get saved as duplicate objects when you save that layer.

So because of this bug, I now have who knows how many unnecessarily reduplicated objects that were pasted in and never, ever shown because the NTC _immediately_ filters out of view any features which do not match the current temporal frame. (With the old TimeManager plugin, they would stay visible until you saved the layer.)

I was trying to trace edges for a new feature but tracing was crapping out due to some vertices on the same spot. knew Because of #29601 (processing toolbox can't handle array fields from PostGIS layers) I knew where the bad vertices were but could not use the processing tools to fix them. But then because of #40790 (vertex tool does not respect temporal controller) I couldn't use the Vertex Tool select the right feature for editing things as it would only select the features that had been filtered out by the NTC but were on top of the one I had visible and needed to edit. Plus, because of bug #40789 (tracer does not respect temporal controller) I am not 100% sure about which feature was actually making the tracing tool crap out as there are multiple temporally distinct features with the same edges in a stack at that location that the vertex tool cannot access due to being below.

I'm more than a little bit annoyed right now at this and cannot help but feel that the NTC was badly designed and poorly tested.

**Comment by roya0045** [comment]
Tool interaction with unrendered layer are not  always related to the time controller. the behavior may be specific to each tool. The time control aspect also behave distinctly than symbology, which may also change things, mostly for selection. From what I recall the time controller is mostly aimed as a display tool and not as much for data manipulation/management.

**Comment by rduivenvoorde** [comment]
@CoryAlbrecht I'll sent an mail to the list too. But can you maybe add a small testing dataset in this case? So just easier to check for others? 
In general I think the 'evolution' of QGIS/software features behaves like this: somebody has a use case or feature, a developer creates a fix for it as fast as possible. Other trys to use that fix and see that it does not fit their usecase, o back to reporting, etcetcetc 
So: good that you report/discuss this. And as a user of the master branch you are automatically also a tester :-)
In general: Let's stay positive.

**Comment by CoryAlbrecht** [comment]
> @CoryAlbrecht I'll sent an mail to the list too. But can you maybe add a small testing dataset in this case? So just easier to check for others?
> In general I think the 'evolution' of QGIS/software features behaves like this: somebody has a use case or feature, a developer creates a fix for it as fast as possible. Other trys to use that fix and see that it does not fit their usecase, o back to reporting, etcetcetc
> So: good that you report/discuss this. And as a user of the master branch you are automatically also a tester :-)
> In general: Let's stay positive.

I get that QGIS is open source and that volunteers work on stuff that interests them without a team working on a priority list, but I don't think that should also be the excuse for adding features that go and break a bunch of other stuff inside it. When new features are added, there needs to be some level of testing and validation to make sure that doesn't happen. 

I wouldn't be quite so frustrated if this were only in the master branch, but it's also been in the release versions. :-1:

**Comment by CoryAlbrecht** [comment]
And I just found out that this bug also resulted in me having **unknowingly deleted features** that were hidden because of the temporal filtering but invisibly selected anyways. Hypothetically I could use either the weekly PostgreSQL backups or the ZFS snapshots to get them back, but practically that's impossible as I don't know when they would have gotten deleted.

Data loss makes me angry.
