### ISSUE TITLE
Crashes when going into 3D mode and configuring QGIS

### ISSUE THREAD

**Issue by mfstanton** [qgis/QGIS#40820]
Crash ID: ee9144da3509e262e6a8e1a8e244fd24af6225c6

Stack Trace

QgsTilingScheme::tileToExtent :
QgsTerrainDownloader::dataSource :
QgsDemTerrainGenerator::writeXml :
QgsDemTerrainGenerator::createChunkLoader :
QgsWindow3DEngine::window :
QgsWindow3DEngine::window :
Qgs3DMapScene::updateScene :
Qgs3DMapScene::onCameraChanged :
QMetaObject::activate :
QgsCameraController::setLookingAtPoint :
QgsMeshTimeFormatDialog::saveSettings :
QMetaObject::activate :
QWidgetLineControl::`default constructor closure' :
QComboBox::setCurrentIndex :
QWidgetLineControl::`default constructor closure' :
QMetaObject::activate :
QComboBoxPrivateContainer::eventFilter :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.10.2-A Coru�a
QGIS code revision: d4cd3cfe5a
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.3
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

**Describe the bug**

**How to Reproduce**

4. See error -->

**QGIS and OS versions**

**Additional context**

**Comment by mfstanton** [comment]
I have been struggling with this for a week. The New Map 3D projection software does not work and i can't even get the image to rotate properly on the screen. I am running a PNY Nvidia P400 card but even with the card disabled I get the error but cannot find log info ANYWHERE on my system

**Comment by roya0045** [comment]
first update to the latest LTR to see if that has been solved yet.

**Comment by gioman** [comment]
@mfstanton 

1) update to the latest 3.10 or 3.16

2) try with a new QGIS profile

3) check if is a duplicate of other reports, i.e. https://github.com/qgis/QGIS/issues/40766

4) add **exact** steps to replicate, and if necessary sample data

**Comment by mfstanton** [comment]
Thank you, I did upgrade to 3.16. I can reproduce it with 8 DSM and Ortho Tiffs.  Part of the problem is that it has not been consistent in where it crashes but it has been in the 3D configuration scripts. I will get a precise set of data for you.
