### ISSUE TITLE
infinite loop with mssql provider

### ISSUE THREAD

**Issue by vcloarec** [qgis/QGIS#40836]
an infinite loop appears here : https://github.com/qgis/QGIS/blob/72065310f53ae2b02de4efe6a0430a63d6b9d599/src/core/qgsabstractdatabaseproviderconnection.cpp#L449

To reproduce:
expand a MSSQL layer in the browser
or
run the test : https://github.com/qgis/QGIS/blob/master/tests/src/python/test_qgsproviderconnection_mssql.py

Version : master

The issue seems to appear with this PR (@elpaso ): https://github.com/qgis/QGIS/pull/40726

**Comment by elpaso** [comment]
@vcloarec the test passes for me. 

Honestly I cannot see an error in that piece of code (that has been completely rewritten in my queued PR  https://github.com/qgis/QGIS/pull/40750 btw): the loop will eventually exit because the iterator will return an empty row.

**Comment by vcloarec** [comment]
thanks @elpaso, so maybe it comes from my database... I've tried with your PR #40750, and QGIS crashed...

**Comment by elpaso** [comment]
> thanks @elpaso, so maybe it comes from my database... I've tried with your PR #40750, and QGIS crashed...

If you have a stacktrace can you please attach it to the #40750 PR?
