### ISSUE TITLE
Field Calculator storing last entered expression

### ISSUE THREAD

**Issue by lajunek** [qgis/QGIS#40850]
**Feature description.**

**Comment by jmonticolo** [comment]
Isn't that what you are looking for : [https://docs.qgis.org/3.16/en/docs/user_manual/working_with_vector/functions_list.html?highlight=recent#recent-functions](https://docs.qgis.org/3.16/en/docs/user_manual/working_with_vector/functions_list.html?highlight=recent#recent-functions) ?

**Comment by roya0045** [comment]
It's already a thing, please look harder.
