### ISSUE TITLE
Unable to right click GeoPackage table from browser

### ISSUE THREAD

**Issue by timlinux** [qgis/QGIS#40856]
When I try to delete a table from any geopackage in browser, I get an error 'wrong number of columns returned by query'. This happens immediately when I right click on the table entry.

![image](https://user-images.githubusercontent.com/178003/103657211-84996700-4f61-11eb-988f-cf2e484f9f2f.png)

QGIS version | 3.17.0-Master | QGIS code revision | d11d28ca3e
-- | -- | -- | --
Compiled against Qt | 5.14.2 | Running against Qt | 5.14.2
Compiled against GDAL/OGR | 3.1.3 | Running against GDAL/OGR | 3.1.3
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.33.0 | Running against SQLite | 3.33.0
PostgreSQL Client Version | 12.5 (Ubuntu 12.5-0ubuntu0.20.10.1) | SpatiaLite Version | 5.0.0
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 7.1.0 | Running against PROJ | Rel. 7.1.0, August 1st, 2020
OS Version | Pop!_OS 20.10 | This copy of QGIS writes debugging output.
Active python plugins | QuickOSM; Mergin; SpreadsheetLayers; qgis-maptiler-plugin; SRTM-Downloader; LDMP; MetaSearch; processing; db_manager

**Comment by roya0045** [comment]
Master only?

**Comment by gioman** [comment]
@roya0045 @timlinux it is ok on master on Windows, and as well on 3.16.2 This may be a Linux only thing (I can replicate on master on Ubuntu 20.04).

**Comment by gioman** [comment]
@timlinux this affects also DB Manager

```
_core.QgsProviderConnectionException: Error listing tables from /home/giovanni/Downloads/u2_2157_clean.gpkg: Error listing tables from /home/giovanni/Downloads/u2_2157_clean.gpkg: wrong number of columns returned by query 
Traceback (most recent call last):
  File "/usr/share/qgis/python/plugins/db_manager/db_model.py", line 456, in rowCount
    self._refreshIndex(parent, True)
  File "/usr/share/qgis/python/plugins/db_manager/db_model.py", line 505, in _refreshIndex
    if item.populate():
  File "/usr/share/qgis/python/plugins/db_manager/db_model.py", line 198, in populate
    tables = database.tables()
  File "/usr/share/qgis/python/plugins/db_manager/db_plugins/plugin.py", line 572, in tables
    tables = self.connector.getTables(schema.name if schema else None, sys_tables)
  File "/usr/share/qgis/python/plugins/db_manager/db_plugins/gpkg/connector.py", line 263, in getTables
    vectors = self.getVectorTables(schema)
  File "/usr/share/qgis/python/plugins/db_manager/db_plugins/gpkg/connector.py", line 286, in getVectorTables
    for table in self.core_connection.tables(schema, QgsAbstractDatabaseProviderConnection.Vector | QgsAbstractDatabaseProviderConnection.Aspatial):
_core.QgsProviderConnectionException: Error listing tables from /home/giovanni/Downloads/u2_2157_clean.gpkg: Error listing tables from /home/giovanni/Downloads/u2_2157_clean.gpkg: wrong number of columns returned by query
```

**Comment by elpaso** [comment]
@timlinux I cannot reproduce, can you please add step-by-step procedure to reproduce? (there are at least two different ways to delete a layer from the browser: the file browser and the GPKG connections, I tested both successfully)

**Comment by elpaso** [comment]
Maybe you had the same layer expanded in the GPKG connections?

**Comment by nyalldawson** [comment]
I also see this error, with all geopackages

**Comment by elpaso** [comment]
@nyalldawson any hint to reproduce, because I cannot?

**Comment by elpaso** [comment]
I suspect that the refresh uses cached list of tables, but I'd like to reproduce it instead of searching a fix in the blind.

**Comment by elpaso** [comment]
We might add signals to the connections API but I'd like to avoid that if it's not strictly necessary.
