### ISSUE TITLE
Can't export as image in print composer

### ISSUE THREAD

**Issue by lamebird** [qgis/QGIS#40852]
**Checklist before submitting**

- [✓ ] Search through existing issue reports and gis.stackexchange.com to check whether the issue already exists
- [✓ ] Test with a [clean new user profile](https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html?highlight=profile#working-with-user-profiles).
- [✓ ] Create a light and self-contained sample dataset and project file which demonstrates the issue

**Describe the bug**

Export as image window (file picker) don't appear in latest version of qgis (3.16.2), even though it works in previous.
Export as SVG and PDF works as it should

**How to Reproduce**

1. Go to print composer
2. Click on Export as image

https://user-images.githubusercontent.com/19585925/103632327-b7018f00-4f76-11eb-9eaa-20feb030c591.mp4

**QGIS and OS versions**

QGIS version | 3.16.2-Hannover | QGIS code branch | Release 3.16
-- | -- | -- | --
Compiled against Qt | 5.15.2 | Running against Qt | 5.15.2
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.34.0 | Running against SQLite | 3.34.0
PostgreSQL Client Version | 12.4 | SpatiaLite Version | 5.0.0-beta0
QWT Version | 6.1.5 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Fedora 33 (Workstation Edition)
Active python plugins | GeoCoding; temporalprofiletool; OSMDownloader; CalculateGeometry; latlontools; localmaxfilter; SemiAutomaticClassificationPlugin; slyr_community; processing; MetaSearch; db_manager

**Additional context**

**Comment by nyalldawson** [comment]
Hmm - I can confirm. It's specific to Fedora 33 though (or maybe just Qt 5.15?) -- seems like the Qt file picker dialog functionality is broken. :scream:

**Comment by roya0045** [comment]
@nyalldawson  #40665 also

**Comment by roya0045** [comment]
And also #40808

**Comment by uclaros** [comment]
@nyalldawson Debian works fine with the same qt version. If you look at the stacktrace in #40808 it seems related to `/usr/lib64/qt5/plugins/platformthemes/libqgnomeplatform.so` that fedora is using.

**Comment by nyalldawson** [comment]
Fixed in fedora by https://bodhi.fedoraproject.org/updates/FEDORA-2021-c8bf9e1d53
