### ISSUE TITLE
Split geometry takes long on layers with many features

### ISSUE THREAD

**Issue by wonder-sk** [qgis/QGIS#40860]
**Describe the bug**

Split feature tool sometimes takes very long time (it can be tens of seconds) when splitting features in a vector layer with many features - even if the split only involves a couple of geometries.

This has been originally reported on pull request #37295 (which addressed slow split of complex polygons), but this issue is reproducible with both line and polygon layers, so not directly related to that PR.

From a quick test, all the slowness happens inside QgsVectorLayerUtils::createFeature() called from QgsVectorLayerEditUtils::splitFeatures() - a single call to createFeature() can take hundreds of milliseconds.

**How to Reproduce**

Best to download dataset provided by @albertodeluca - a roads layer with 1.3M line features.
https://drive.google.com/file/d/167mqdxOwEB9jgJvgTw-MPSfYddI9lKZs/view?usp=sharing

1. Load osm.gpkg from the package above - add both layers (roads, cutline)
2. Zoom to the cutline
3. Select roads as the active, make it editable and select "split features" tool
4. Draw a split line similar to the one in "cutline" layer
5. It will take very long time (tens of seconds) to finish this relatively simple split

**QGIS and OS versions**

QGIS master / 3.16, any OS

Users say that QGIS 3.4 is very fast to do the same action.

**Comment by roya0045** [comment]
The operation seems simple enough, create a feature list containing a single feature with the provided geometry and the  feature attributes. Could the attribute fetching be the bottleneck on large datasets?

**Comment by albertodeluca** [comment]
Thanks a bunch @wonder-sk
