### ISSUE TITLE
Please force geometry_overlay_ parameters "expression" and "filter" to be strings

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#40878]
Trying to figure out how the `expression` parameter of the new `geometry_overlay_` expression functions works I realised that you can pass some things (I still haven't figured it out yet) as verbatim expression, not as a string that gets then evaluated on the resulting "result" feature.

So for example in a Geometry Generator that makes a line from the centroids of each feature on layerA to the centroid of the closest feature on layerB you might write something like:

```
make_line(
  centroid(
    $geometry  -- here it means the geometry of the feature currently evaluated
  ),
  centroid(
    array_first(
      geometry_overlay_nearest( 
        'layerB',
        $geometry  -- here it means the geometry of a feature of layerB
      )
    )
  )
)
```

Here `$geometry` once means "the geometry of the feature currently evaluated" and then when used as parameter for `geometry_overlay_nearest` it changes meaning and is now "the geometry of a different feature currently evaluated as part of an expression". Suddenly the very same $geometry means something completely different within the same expression. That is very confusing and goes against what I understand most programming languages work like.

The meaning would be clear if the expression parameter would be forced to be a string, so e. g.

```
make_line(
  centroid($geometry),
  centroid(
      array_first(
      geometry_overlay_nearest( 
        'layerB',
        '$geometry'  -- now a string and obviously not the same as $geometry
      )
    )
  )
)
```

This affects all the `geometry_overlay_` functions and their parameters `expression` and `filter`.

This would also allow a more dynamic way of building these expressions I guess, if one could build a string for complex logic (not saying that this would be a good idea ;) ).

**Comment by m-kuhn** [comment]
This is the same for aggregates (for a long time). The advantage is syntax highlighting. It's a question of the "context". We can't change it without breaking a lot of things.
To build strings with logic you can already use `eval`.
I think this is a won't fix.

**Comment by m-kuhn** [comment]
What could be done is improving the editor with context sensitivity for tooltips and autocompletion (different attribute names). That's not an easy task I suspect.

**Comment by nyalldawson** [comment]
I think strings would be a general step back -- you'd end up with a nightmare situation trying to handle escaping and a less usable result all round. And there's precedent here anyway -- in SQL you don't put subclauses and join constraints as string expressions

So if anything this is a documentation request....

**Comment by kannes** [comment]
Oh I see. Thanks! If this was used before then changing it would break a lot of existing projects.

Expressions are such a weird mixture of functional(?) programming and other things. :)

Feel free to close if it makes no sense. I want to try improve the documentation for these functions anyways and would try to add a note there then.

**Comment by m-kuhn** [comment]
> I want to try improve the documentation for these functions anyways and would try to add a note there then.

Thank you in advance
