### ISSUE TITLE
Temporal controller widget skips to end of Range when switching UP in units(ize)

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS#40871]
Some time ago we added functionality to 'remember' current position on the TimeSlider when changing Step or StepSize in the Temporal Controller Widget.

But recent commits seem to break this?

To test, load the following 6 points as commaseparated file:
[6dots.zip](https://github.com/qgis/QGIS/files/5775560/6dots.zip)

- Enable the layer 'temporal' with "t_start" as Start field and "t_end" as End field
- set Timestep to 1 hour (if not already set)
- Now do one step (so we are in (hour)frame 2, starting at 2:00-3:00
- Now change '1 hours' to '1 minutes' in the widget.
- The slider keeps it's position: frame is now 2:00 till 2:01 (OK!)
- Now: move the 'minutes' back to 'hour'. Instead of going back to 2:00-3:00 it moves to the END of the timeslider?

So: going down (smaller units) is OK, but going up goes wrong?
I tried to debug, and the findBestFrameNumberForFrameStart still seems to find the right frame:
https://github.com/qgis/QGIS/blob/master/src/core/qgstemporalnavigationobject.cpp#L315
But after emitting some signals, QGIS seems lost.

I'm pretty sure this was working earlier.

**Comment by rduivenvoorde** [comment]
Also see https://github.com/qgis/QGIS/issues/37829 which (later problem) probably is rooted in the same issue

**Comment by Samweli** [comment]
@rduivenvoorde I confirmed this issue few days ago, but recently I can't reproduce it in master, everything seems to work as expected, do you still find this issue on QGIS master?

**Comment by rduivenvoorde** [comment]
@Samweli confirmed here, I think this is fixed now. Thanks! Will close.
