### ISSUE TITLE
Print layout label - ability to have same text rendering options like in map labels

### ISSUE THREAD

**Issue by lieti** [qgis/QGIS#40879]
Hi, many times I´m facing to cartographical issue with text elements in the print layout.
When I need to put text informations directly to the map area, like credits, reference system etc., problem is that I cannot distinguish them from the background with using of halo, drop shadow etc.
I will really appreciate to have same rendering options like in case of map labels.

I know workarounds like GIMP postprocessing, semitransparent rectangle on background, or to have separate point layer with this informations like map label, than separate map frames with those labels (thanks to @WonderSK 😉 ). It’s working, but it is bit overkill.  
Thanks in advance.

**Comment by andreasneumann** [comment]
@lieti - transparent backgrounds and blend modes are already possible in QGIS layouts:

Other effects like drop-shadows not yet.

Also: if you draw shapes separately behind your text, you can use all style options like in QGIS symbology, including draw effects like drop-shadows.

Can you clarify what exactly you are missing?

**Comment by lieti** [comment]
Hi, sorry for confusion. 
I want to have this possibility, text with halo:
![obrázok](https://user-images.githubusercontent.com/34206797/103823704-e269a400-5072-11eb-8348-132ba47282cf.png)

But with text (layout labels) items I have no option to set halo, or dropp shadow:
![obrázok](https://user-images.githubusercontent.com/34206797/103824048-76d40680-5073-11eb-8fa7-71bfb7811ddc.png)

I can partially solve it with semitransparent background of text field, but that is not practical for map design:
![obrázok](https://user-images.githubusercontent.com/34206797/103824347-01b50100-5074-11eb-9064-4f1034a87c1d.png)

**Comment by YoannQDQ** [comment]
Implemented in https://github.com/qgis/QGIS/pull/46305 (QGIS 3.24)
