### ISSUE TITLE
NSIS - Silent upgrade hangs scripted installs

### ISSUE THREAD

**Issue by willgoerzen** [qgis/QGIS#40880]
**Describe the bug**

When upgrading QGIS to a newer version with the silent switch it calls the uninstall.exe without silent switches. This shows the uninstall GUI and causes scripted installations (and Config Manager) to hang as it's waiting for user input. For admins, a workaround is to uninstall software manually first. Tested with 3.10.12 → 3.10.13 but the NSIS .nsi script seems to be the same between 3.16 and 3.10. Also would affect re-install and downgrade scenarios.

**How to Reproduce**

1. Have old version of QGIS installed (like 3.10.12)
2. While old version is installed, attempt to install new version with /S switch like: "QGIS-OSGeo4W-3.10.13-2-Setup-x86_64.exe /S"
3. Prompt appears asking if upgrade is desired, then brings up the uninstall wizard from the uninstaller
4. Expected behaviour is to automatically uninstall without confirmation or dialog boxes (when using /S switch).

**QGIS and OS versions**

QGIS 3.10.12/.13
Windows 10 1809

**Additional context**

This would only affect sysadmins that use the prebuilt installer and are upgrading their QGIS installations via command line. They can just script the uninstall manually but it's a bug nonetheless.

**Comment by alexbruy** [comment]
Please check with the new v2 installer.
