### ISSUE TITLE
Add a "Layer Styling panel" button to (empty?) Vector toolbar.

### ISSUE THREAD

**Issue by stragu** [qgis/QGIS#40884]
**Feature description.**

Given how useful the Layer Styling panel is, it would be great to add to the default toolbars a "Layer styling panel" button** that opens the Layer Styling panel, with the most recently used tab opened.

This would make it more discoverable, and more easily accessible than when using the menu (View > Panels > Layer Styling Panel)

**Additional context**

The default toolbar in QGIS has a "Layer Labeling Options" button (in the Label toolbar) that opens the side panel called "Layer Styling", with the "Labels" tab active.

I assume many users like using the Layer Styling panel for changing the layer style (mainly the symbology and labelling) and see the result in real time, without an extra window open. And I assume many users like me use the "Layer Labelling Options" button to open the Layer Styling panel to then straight away change to the Symbology tab.

I think it would be an improvement in user experience to **add to the default toolbars a more general "Layer styling panel" button** that opens the Layer Styling panel, with the most recently used tab opened.

I don't think there is a reason why the access to the Labels tab should be prioritised. I suspect users want to see a live update of changes to the symbology just as much as they want to see labels updated live.

If this sounds like a good change, what needs to be done is:

- Add a new button called "Layer styling panel" to either the (currently empty?) Vector toolbar, or maybe to the Project toolbar (next to the Style Manager button)
- Create a relevant icon (something that mixes a 3D shape, a tag and a brush?)
- Make sure the panel opens with the most recently used tab

![image](https://user-images.githubusercontent.com/1747497/103851693-0fab6600-50f6-11eb-8285-f29fa3487d1c.png)

Version of QGIS currently used:

QGIS version | 3.10.12-A Coruña | QGIS code revision | 75c848ffb1
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | db_manager; MetaSearch; processing

**Comment by jmonticolo** [comment]
Two remarks :
- Why Vector Toolbar because layer styling panel works for raster layers too ?
- There is already a very handy shortcut on top of [the layer panel](https://docs.qgis.org/3.16/en/docs/user_manual/introduction/general_tools.html#layers-panel) : ![symbology icon](https://docs.qgis.org/3.16/en/_images/symbology.png)

**Comment by stragu** [comment]
Ah yes, sorry, my bad! I never noticed that button. Closing now, and thanks for the reply!
