### ISSUE TITLE
Temporal controller widget overwrite timestep and timestep unit for some input values.

### ISSUE THREAD

**Issue by Samweli** [qgis/QGIS#40894]
As mention by @rduivenvoorde  here https://github.com/qgis/QGIS/issues/37829#issuecomment-755205663

The temporal controller widget timestep and timestep unit input get changed when user input some values.
Example: setting 30 timestep and days as timestep unit will automatically be changed to 1 timestep and months as the timestep 
unit and setting 7 timestep and days as timestep unit will also be changed to 1 timestep and weeks as the timestep unit.

This issue is on QGIS master and QGIS 3.16

see below screenshot

![guessing_issue_in_TC](https://user-images.githubusercontent.com/2663775/103932145-70589400-5132-11eb-99a0-7c6464a6bfb2.gif)

**Comment by rduivenvoorde** [comment]
@Samweli I'm building your pr now and will report back. But I was wondering, are we now removing the whole 'guessing and try to make better' part? I mean: I'm ok with that, but I'm wondering if others have an opinion on this..:-)

**Comment by rduivenvoorde** [comment]
Ok, now the unit dropdown does not change to new units (so does not switch automagically to a week if you clicked 7 days....). Which is fine with me, but I wonder if it is ok with the original author.

What is still broken (no related to this I think but on the earlier refactoring), is that IF you change the unit that you always go back to step 0 (zero). While earlier we try to guess what the best position was. See https://github.com/qgis/QGIS/issues/40871

(I still had an one occurrence of skipping to the end (once), but I cannot reproduce it anymore)

**Comment by Samweli** [comment]
> Which is fine with me, but I wonder if it is ok with the original author.

@vcloarec what do you think?

> (I still had an one occurrence of skipping to the end (once), but I cannot reproduce it anymore)

same to me, I can't reproduce it on the current master branch.

**Comment by vcloarec** [comment]
> @vcloarec what do you think?

I have commented the PR
