### ISSUE TITLE
Crash when indexing features

### ISSUE THREAD

**Issue by TurboGraphxBeige** [qgis/QGIS#40895]
## User Feedback

I think the QGIS project can be considered a "big project" with a 4-5 vector layers with >100k or >1M features. The crash happened apparently when indexing. I switched to a different window in Windows and it crashed a few seconds later.

## Report Details

**Crash ID**: [5d6e6219ad5befb2e14175ad9dc170123a31f5a5](https://github.com/qgis/QGIS/search?q=5d6e6219ad5befb2e14175ad9dc170123a31f5a5&type=Issues)

**Stack Trace**
<pre>
sqlite3_blob_bytes :
sqlite3_blob_bytes :
sqlite3_blob_bytes :
VRTSimpleSource::IsSimpleSource :
DBFSetWriteEndOfFileChar :
QgsSQLiteExpressionCompiler::operator= :
QgsAbstractFeatureIterator::nextFeature :
QgsVectorLayerFeatureIterator::fetchFeature :
QgsAbstractFeatureIterator::nextFeature :
QgsPointLocator::rebuildIndex :
QgsLayoutAtlas::sortFeatures :
QgsTask::start :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.14.0-Pi
QGIS code revision: 9f7028fd23
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
>  QGIS Version: 3.14.0-Pi

@TurboGraphxBeige way too old, you must upgrade to the latest 3.16 and test again.

**Comment by gioman** [comment]
Also try with a new QGIS profile.

**Comment by TurboGraphxBeige** [comment]
I think it's time to update to 3.16 indeed.

**Comment by roya0045** [comment]
Might be an out of memory error also.

**Comment by TurboGraphxBeige** [comment]
Is there some way to trigger a re-index? I'll take a closer look at memory usage.
