### ISSUE TITLE
Processing (densify) cannot use/see attributes, when used in model

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS#40900]
I'm not very experienced with creating Processing models, but I encountered the following:

- create a simple line layer in a real world projection (say epsg:28992), make sure to also add a 'number'  attribute of type integer !
- draw a super simple line, and use "10" as attribute value for 'number'
- now in processing search for 'densify' and choose the algorithm 'Densify by count'
- a popup will show up, and you can either via 'edit' or just by choosing the 'number' attribute set the 'Number of vertices to add' to the attribute value:
![Screenshot-20210108090601-895x427](https://user-images.githubusercontent.com/731673/103989952-c0feda00-5190-11eb-9c53-9aefc9d6b3d3.png)
- RUN and see there is a new 'Densified' layer with indeed the number of new vertices: ALL OK !!

But now: try to create a new model, search for the 'Densify by count' and see in screenshots, that I am not able to use the 'number attribute'??
Which I think is a bug? Or is this a known limitation of using the alg's in Processing?

![Screenshot-20210108090833-1075x469](https://user-images.githubusercontent.com/731673/103990370-6154fe80-5191-11eb-9a33-419bd8839c47.png)

![Screenshot-20210108090911-789x737](https://user-images.githubusercontent.com/731673/103990388-6a45d000-5191-11eb-9fc0-416289d5370a.png)

**Comment by rduivenvoorde** [comment]
Just also tested on Windows master (and earlier on Linux master and 3.16)

**Comment by nyalldawson** [comment]
It's a known limitation of models -- we don't know what the actual input layers will be, so there's no way to know what fields will be available at different stages of the model. It will still work correctly if you manually type the field names.

**Comment by rduivenvoorde** [comment]
@nyalldawson the dialog seems to indicate to know what the input is (as it is one of the variables you have to set in it)? But I accept your word off course, probably a limitation of (re)using the algorithm dialogs?

You are right: if I use the attribute name in the expression box ( so use "number" in the case above) the layer is created with the right amount of vertices.

It ends though with this dialog: 

![Screenshot-20210108092700-1128x343](https://user-images.githubusercontent.com/731673/103992326-3fa94680-5194-11eb-9249-6afd72b6201d.png)

Close this?

**Comment by gioman** [comment]
> It's a known limitation of models -- we don't know what the actual input layers will be, so there's no way to know what fields will be available at different stages of the model. It will still work correctly if you manually type the field names.

@rduivenvoorde closing as known issue? changing it to feature request?

**Comment by rduivenvoorde** [comment]
@gioman dunno, not sure if it is feasible to make such things work... 

I happily accept a 'close as known limitation' if dev's tell's me that it would add to many complexities.

**Comment by roya0045** [comment]
@rduivenvoorde the stack trace should not occur... I'll try to see what's causing this.

**Comment by roya0045** [comment]
I'm confused, you can run alg as standalong without the whole model? I'm assuming this is not in 3.16 or what I could do in my build branch, Or maybe I'm misreading things.

**Comment by rduivenvoorde** [comment]
@roya0045 what I mean 'outside of a model' running is that you just run that one algorithm on a layer, that is the 'normal' use of all the algorithm's isn't it? Well to me it is :-)

**Comment by roya0045** [comment]
@rduivenvoorde ah right, I was confused by your comment as I though the standalone alg was using the modeler dialog and caused the error.
