### ISSUE TITLE
QGIS3 with GDAL LVBAG driver support

### ISSUE THREAD

**Issue by jhpoosthoek** [qgis/QGIS#40905]
**QGIS3 with GDAL LVBAG driver support**
When will QGIS3 support GDAL 3.2? I ask this because I would like to use the LVBAG driver which was added to GDAL 3.2: https://gdal.org/drivers/vector/lvbag.html

**Comment by jef-n** [comment]
QGIS does support GDAL 3.2

**Comment by jhpoosthoek** [comment]
I was not specific enough, to rephrase my question: when will QGIS3 support the GDAL LVBAG driver? I currently use the QGIS Standalone Installer Version 3.16 (64 bit) for Windows which uses GDAL 3.1.4, released 2020/10/20.
