### ISSUE TITLE
Filtering attributes does not work when editing multiple features at the same time

### ISSUE THREAD

**Issue by Sallagispo** [qgis/QGIS#40910]
**Describe the bug:** 
When I create a filter expression in Properties >  Attributes Form, the filter works correctly when I edit my data through the Attribute table (see fig. 1). It also works when I create a new feature and Attribute form pops (fig. 2). However, when I choose multiple features from the map and use form for editing, the filtering does not work (see fig. 3). Instead, all the values are still visible.

![image](https://user-images.githubusercontent.com/36758706/104023920-050ed080-51cb-11eb-88ea-cd191febd6a3.png)
Figure 1. This is fine, filtering works as it is supposed to.

![image](https://user-images.githubusercontent.com/36758706/104023996-1f48ae80-51cb-11eb-9d2b-774300b84b0e.png)
Figure 2. Filtering works also in this Attribute form when I create a new feature.

![image](https://user-images.githubusercontent.com/36758706/104024036-2f608e00-51cb-11eb-8d9e-f0231328a565.png)
Figure 3. Here the problem is visible: when I edit attributes of multiple, selected features at the time, filtering does not work.

**How to Reproduce:**
In my case, I have two-leveled classification for areas (land use classes). In level 1, you can choose any one-lettered code (from A to I). In level 2, you should respect the choice that is already done in level 1 and only select from allowed sub-levels (e.g. A1, A2, or A3, if the first level is set to A). This filtering is done in field ‘level2’ with the following expression:

 "koodi1"=current_value('level1')

Screenshots of tables from which the values come from is in fig.4. As you can see, there is a separate field called “koodi1” that refers to the upper level classification and that is used in filtering expression.

![image](https://user-images.githubusercontent.com/36758706/104024107-469f7b80-51cb-11eb-8c17-1fdef17fa765.png)
Figure 4. Content of tables that are related to level1 and level2 fields. There is a field ‘koodi1’ in the table of level2 that refers straight to level1 codes.

**QGIS and OS Versions:**
QGIS version | 3.16.1-Hannover | QGIS code revision | b381a90dca
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | SelectByRelationship;    db_manager;    MetaSearch;    processing

**Additional context**
This bug has been occurred in various QGIS versions, at least in 3.4 and 3.10, and for all my colleagues and customers I have discussed with. It does not matter whether I’m editing a temporary scratch layer, or a ready-made geopackage or a shapefile layer.
I am concerned that this is something that stays unnoticed by many QGIS users; they are happy when they manage to create a filter and then they rely on it.

**Comment by gioman** [comment]
@Sallagispo just a hunch: probably it was never implemented in the multi-tool. Maybe a dev can give a answer, not sure but I think that @m-kuhn worked on it, or am I wrong?

**Comment by m-kuhn** [comment]
I am pretty sure in the multi edit form the context was never adjusted to reflect the current state of the form.

I think @elpaso integrated this feature for single feature attribute forms and probably knows better if multi editing was ever on the radar for this.

**Comment by elpaso** [comment]
@m-kuhn well, it's been a while but IIRC it was never implemented for multi feature editing. I can have a quick look if this is an easy fix but I can't make any promise.

**Comment by gioman** [comment]
> @m-kuhn well, it's been a while but IIRC it was never implemented for multi feature editing. I can have a quick look if this is an easy fix but I can't make any promise.

@elpaso moving to feature request?
