### ISSUE TITLE
QGIS3.16 crash when it starts up.

### ISSUE THREAD

**Issue by HanwGeek** [qgis/QGIS#40911]
**Describe the bug**

**How to Reproduce**

1. Open QGIS

**QGIS and OS versions**

QGIS: 3.16
OS: Ubuntu18.04
Qt: 5.14

**Additional context**

```shell
QGIS died on signal 11Could not attach to process.  If your uid matches the uid of the target
process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
ptrace: Operation not permitted.
No thread selected
No stack.
gdb returned 0
[1]    25210 abort (core dumped)  qgis
```
QGIS crashed after showing logo. Where can I get more error log and fix this? Thanks!

**Comment by gioman** [comment]
@HanwGeek how did you installed QGIS on ubuntu? using qgis.org repos? self compiling the code?

**Comment by HanwGeek** [comment]
> @HanwGeek how did you installed QGIS on ubuntu? using qgis.org repos? self compiling the code?

@gioman I installed QGIS from qgis.org repos.

**Comment by gioman** [comment]
@HanwGeek you likely have a local issue, on clean machines there are no installation issue. Suggestion: remove any geos,proj,qgis,gdal related packages, and try again.

**Comment by HanwGeek** [comment]
> @HanwGeek you likely have a local issue, on clean machines there are no installation issue. Suggestion: remove any geos,proj,qgis,gdal related packages, and try again.

I install & use QGIS3.4 from ubuntugis for a while. And it works great. At present, I want to upgrade QGIS to 3.16 to use some python api. Meanwhile, I have a self-compiled gdal3.1.3, so I am still working on it to find the causes.

**Comment by gioman** [comment]
> ubuntugis

@HanwGeek have you used the specific qgis.org repo that make use of ubuntugis dependencies?

**Comment by HanwGeek** [comment]
> have you used the specific qgis.org repo that make use of ubuntugis dependencies?

Sorry, I haven't figure it out whether qgis.org repo use any of ubuntugis dependencies. For now I am removing all packages may relate to QGIS.

**Comment by gioman** [comment]
@HanwGeek https://qgis.org/ubuntugis/

**Comment by HanwGeek** [comment]
> @HanwGeek https://qgis.org/ubuntugis/

I just use the ubuntugis repo, not that one under qgis.org for my QGIS3.4. Is there any difference?

**Comment by gioman** [comment]
if you are having trouble with qgis packages coming from the ubuntugis repo then you should ask to them. Anyway I suggest you to use the official ones. You can choose to use the one that needs also the ubuntugis repo, or the one that do not need it.

**Comment by HanwGeek** [comment]
> if you are having trouble with qgis packages coming from the ubuntugis repo then you should ask to them. Anyway I suggest you to use the official ones. You can choose to use the one that needs also the ubuntugis repo, or the one that do not need it.

Sorry, for now I install QGIS3.16 from qgis.org repo. And that's the problem i encontered.

**Comment by gioman** [comment]
> Sorry, for now I install QGIS3.16 from qgis.org repo. And that's the problem i encontered.

@HanwGeek again: you are using the ubuntugis repo, then you must use https://qgis.org/ubuntugis/

**Comment by gioman** [comment]
> @HanwGeek again: you are using the ubuntugis repo, then you must use https://qgis.org/ubuntugis/

@HanwGeek if you are not using anymore the ubuntugis repo, but you used previously, then you must clean all the dependencies (geos,gdal,proj, etc) and use https://qgis.org/ubuntu

**Comment by HanwGeek** [comment]
@gioman Thanks! I removed all dependencies and install QGIS from qgis.org. I can start QGIS now. but the gdal from qgis.org shows a problem
```python
AttributeError: module '_gdal' has no attribute 'DirEntry_name_get'
```
Can I fix this?

**Comment by gioman** [comment]
> AttributeError: module '_gdal' has no attribute 'DirEntry_name_get'

@HanwGeek when/where this shows?

**Comment by HanwGeek** [comment]
> > AttributeError: module '_gdal' has no attribute 'DirEntry_name_get'
> 
> @HanwGeek when/where this shows?

When it shows `restoring loaded plugins` under the logo. In fact, when I try to `from osgeo import gdal` at python3.6. It tells me the same error. So I think it may a problem with `gdal`.

**Comment by gioman** [comment]
> When it shows `restoring loaded plugins` under the logo. In fact, when I try to `from osgeo import gdal` at python3.6. It tells me the same error. So I think it may a problem with `gdal`.

@HanwGeek maybe coming from a 3rd party plugin? go in plugin manager and disable all plugins, then restart QGIS.

**Comment by HanwGeek** [comment]
> > When it shows `restoring loaded plugins` under the logo. In fact, when I try to `from osgeo import gdal` at python3.6. It tells me the same error. So I think it may a problem with `gdal`.
> 
> @HanwGeek maybe coming from a 3rd party plugin? go in plugin manager and disable all plugins, then restart QGIS.

It should be a problem with GDAL. Anyway, I have achieved a great progress! Thanks a lot!

**Comment by HanwGeek** [comment]
> > When it shows `restoring loaded plugins` under the logo. In fact, when I try to `from osgeo import gdal` at python3.6. It tells me the same error. So I think it may a problem with `gdal`.
> 
> @HanwGeek maybe coming from a 3rd party plugin? go in plugin manager and disable all plugins, then restart QGIS.

It's about the gdal from qgis.org, even after I clean all gdal libs.

**Comment by gioman** [comment]
> It's about the gdal from qgis.org, even after I clean all gdal libs.

@HanwGeek qgis.org repos do not ship any gdal version.
