### ISSUE TITLE
Python module statsmodels not importing in Python console

### ISSUE THREAD

**Issue by GSavelev-VSEGEI** [qgis/QGIS#40924]
Python module statsmodels not importing in Python console:
```
import statsmodels
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'statsmodels'
```
I have checked via `pip list`, and it's there.
pandas module and numpy, for example are imported without any problem
```
import pandas
globals()['pandas']
<module 'pandas' from 'C:\\PROGRA~1\\QGIS3~1.16\\apps\\Python37\\lib\\site-packages\\pandas\\__init__.py'>
```

I have tried restarting Windows and QGIS, clean profile and LTR version

same problem with sklearn

**QGIS and OS versions**

QGIS version
3.16.2-Hannover
QGIS code revision
f1660f9da5
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
attributeBasedClustering; 
autoSaver; 
BezierEditing; 
clusterpoints; 
DataPlotly; 
GeoTrace; 
LineDirectionHistogram; 
Mergin; 
multilayerselect; 
numericalDigitize; 
profiletool; 
Qgis2threejs; 
qProf; 
QuickOSM; 
quick_map_services; 
SemiAutomaticClassificationPlugin; 
slyr; 
processing

**Comment by roya0045** [comment]
@gioman are external imports out of scopes, just like plugin support? 

@GSavelev-VSEGEI Is pip even reading from the right environment?

**Comment by gioman** [comment]
@GSavelev-VSEGEI works fine on QGIS 3.16.2 on Ubuntu 20.04.

**Comment by roya0045** [comment]
@gioman path resolution work differently on windows. Now there was recently a fix for external imports, we'll have to see if it helps.

**Comment by gioman** [comment]
@roya0045 @GSavelev-VSEGEI I installed statsmodels with pip3 on the osgeo4w console, and after that it imports fine on QGIS 3.16.2 on Windows too.

**Comment by GSavelev-VSEGEI** [comment]
Thanks to everybody!

I'm sorry, I didn't know QGIS sets up its own python on Windows.

The easiest way is step-by-step (well there're three of them) described [here](https://gis.stackexchange.com/a/359002/155670).

This worked, of course, for me also:
> @roya0045 @GSavelev-VSEGEI I installed statsmodels with pip3 on the osgeo4w console, and after that it imports fine on QGIS 3.16.2 on Windows too.
