### ISSUE TITLE
qgis crashes when closing file or quitting

### ISSUE THREAD

**Issue by Schwaeble** [qgis/QGIS#40932]
User Feedback
Each time I load a particular file, and want to close it again or quit the program, the program. crashes. I removed all layers from the file and rebuild it, the file still crashes

Report Details
Crash ID: 56f27d44bbafb5194f016810bfadc15d1d840442

Stack Trace

QgisApp::projectTemporalRangeChanged :
QMetaObject::activate :
QgsProject::clear :
QgisApp::closeProject :
QgisApp::fileNew :
QgisApp::fileClose :
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
QGIS Info
QGIS Version: 3.14.15-Pi
QGIS code revision: d5114d2
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

**Comment by m-kuhn** [comment]
Can you repeat the test with the latest QGIS 3.16 (3.14 is EOL)?
If it still happens, are you able to share this particular file?

**Comment by Schwaeble** [comment]
That was a strange trip. It started that I had 3.16 installed just recently. Through this incident, I noticed that I unbeknown was still running 3.14. Now I’m running 3.16 is which is listed as Hannover in the installed programs list. But it comes up as 3.2 Bonn and it fixed the problem.

Thank you guys for what you are doing for us. It is such a tremendous service. 

Jake
