### ISSUE TITLE
3.16.2-Hannover Max OSX Font dialog box bug

### ISSUE THREAD

**Issue by renevandervelde** [qgis/QGIS#40934]
Clicking the font dialog box in the layout manager causes Qgis 3.16.2 to quit without displaying an errormessage. 

OS: Mac OSX 10.13.6

**Comment by renevandervelde** [comment]
Similarity with https://github.com/qgis/QGIS/issues/40278 but bug is also happening in Title box font dialog in Legenda.

**Comment by roya0045** [comment]
As stated in the other ticket, can you update to 10.15?

**Comment by gioman** [comment]
closing as duplicate, eventually add your notes in the other ticker.

**Comment by renevandervelde** [comment]
No... other software requirements prevent me from currently updating
towards 10.5

Op ma 11 jan. 2021 om 01:05 schreef Alex <notifications@github.com>:
