### ISSUE TITLE
Errormessage gpx export QGIS 3.16.2 Hannover German

### ISSUE THREAD

**Issue by drugstorer-172** [qgis/QGIS#40955]
I have a simple shapefile with 2 fields: ID and Name.
When I try to export it into a gpx file, I always get this message:
Export in Vektordatei schlug fehl.
Fehler: Erzeugung des Felds id gescheitert (OGR-Fehler: Field of name 'id' is not supported in GPX schema. Use GPX_USE_EXTENSIONS creation option to allow use of the element.)
The file is created but empty.
I filled the ID-field with numbers but same problem. KML export is ok.
What do I wrong??

Gerhard

**Comment by gioman** [comment]
@drugstorer-172 

https://gdal.org/drivers/vector/gpx.html

`GPX_USE_EXTENSIONS: By default, the GPX driver will discard attribute fields that do not match the GPX XML definition (name, cmt, etc…). If GPX_USE_EXTENSIONS=YES is specified, extra fields will be written inside the<extensions> tag.`

In other words: if you want to write a GPX that contains column names that are not part of the specifications then you need to use the option

GPX_USE_EXTENSIONS=YES


![Screenshot_20210112_124631](https://user-images.githubusercontent.com/1951107/104316328-38f03b80-54d4-11eb-9c04-927fa68ebf48.png)

**Comment by drugstorer-172** [comment]
Thanks a lot. It works. Now you made a happy guy 🥇 
Gerhard
