### ISSUE TITLE
qgis minimizes panel width when I have panels at both sides

### ISSUE THREAD

**Issue by vincentschut** [qgis/QGIS#40954]
**Describe the bug**
When using panels at both sides of the screen (e.g. browser and layers left, value tool and layer styling right side), qgis miminizes the panel widths at each new startup.
Instead I'd like qgis to retain the exact panel widths that I had when I closed qgis.

**How to Reproduce**
Start qgis with new profile, put browser and layer panel at the left side of the window, put layer styling panel at the right side of the window. Resize the panel widths so they become a bit larger and better usuable. Close qgis. Reopen qgis. Panels are there, but are resized to have a much smaller width.

**QGIS and OS versions**

Linux (fedora 33), qgis master. Bug has been there for some time though (few weeks, months maybe, don't recall exactly because I first thought it was a problem with my profile)

**Comment by nyalldawson** [comment]
It's a qt 5.15 bug unfortunately. Remains to be seen if we can workaround this in QGIS...

**Comment by nirvn** [comment]
It's a huge PITA.

**Comment by nirvn** [comment]
We'll likely suffer from it for a long time now that Qt won't release any more 5.15 LTRs unless a workaround is found. :cry:

**Comment by vincentschut** [comment]
Ah, good to know, thanks for the info. Shall I close this bug report then? Or would you like to leave it open?

**Comment by vincentschut** [comment]
Related question then: is qgis already compatible (and usable) with qt6? Or does it depend on any of the modules that are planned only to appear in 6.1 or even 6.2?

**Comment by roya0045** [comment]
@nirvn I didn't check the code but could the values be cached by qgis and reapplied on startup as a backup mechanism for 5.15?

**Comment by vincentschut** [comment]
I know it's probably stating the obvious, but having a workaround for this would ease my qgis life considerably (it is a huge PITA indeed)...

**Comment by jfbourdon** [comment]
Over a year ago I reported the same king of bug and as Nyall said, it's upstream (#27408) so I reported on the Qt side [Docked panel height changed on next startup](https://bugreports.qt.io/browse/QTBUG-75362) and [Undocked panel shifting](https://bugreports.qt.io/browse/QTBUG-75364) . I got a suggestion for the second bug but I really don't have to know-how to look if it could be a fix in QGIS.

**Comment by vincentschut** [comment]
Fixed by #44222 , thank you @nyalldawson !

**Comment by Hannes-Ole** [comment]
This bug describes pretty well what I am experiencing, acutally on all my currently installed QGIS versions:
3.16.11 / 12
3.22.5
3.24.3
Whenever I startup, the LEFT panels are super small. For some reason resizing it also takes ages.
Is there a file in which the panel size should be "remembered"? Could this be damaged in my case?
Anyone else having similar issues?

![grafik](https://user-images.githubusercontent.com/72789281/174978929-b2466e47-0298-4629-b6a5-1d3633bcfa15.png)
