### ISSUE TITLE
crash and frequent not responding

### ISSUE THREAD

**Issue by stevem1983** [qgis/QGIS#40958]
## User Feedback

Crash while saving, but continually not responding when trying to do various task. Have uninstalled both versions and reinstalled both versions and still happening.

**Comment by gioman** [comment]
@stevem1983 report largely incomplete. Try with a new QGIS profile, no 3rd party plugins installed. Update to the latest 3.10 or 3.16. If the problem persist file a new ticket with all the requested details https://github.com/qgis/QGIS/issues/new?assignees=&labels=Bug&template=10_bug_report.md&title=
