### ISSUE TITLE
field calculator

### ISSUE THREAD

**Issue by patriziac2021** [qgis/QGIS#40969]
IMPORTANT:

when i activate field calculator on my project in qgis version 3.10 it blocked so that  I can't longer work in Qgis and crashed.

**Comment by gioman** [comment]
@patriziac2021 

https://github.com/qgis/QGIS/issues/new?assignees=&labels=Bug&template=10_bug_report.md&title=



**Describe the bug**


**How to Reproduce**



1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error -->

**QGIS and OS versions**



**Additional context**
