### ISSUE TITLE
`reportError` in subclass of QgsProcessingFeedback doesn't run

### ISSUE THREAD

**Issue by kadirsahbaz** [qgis/QGIS#40978]
I am not sure if it is a bug. 

Based on the answer posted [here][1] by Nyall Dawson, if you subclass `QgsProcessingFeedback`, you can implement your own custom logic dealing with the error.

> ```
> class MyFeedBack(QgsProcessingFeedback):
> 
>     def reportError(self, error, fatalError=False):
>         print(error)
> 
> ...
> 
> res = processing.run("TOOL_NAME", params, feedback=MyFeedBack())
> ```

`layer_a` and `layer_b` both have invalid geometries. When I run the following script I get `invalid geometry` error as expected.

```
class MyFeedBack(QgsProcessingFeedback): 
    def reportError(self, error, fatalError=False): 
        print("ERROR!")

params = {'INPUT': layer_a, 'OVERLAY': layer_b, 'OUTPUT': 'TEMPORARY_OUTPUT'}
processing.run("native:intersection", params, feedback=MyFeedBack())
```

According to [documentation][2], `reportError` method should run in case of any error. But the method doesn't run although the processing tool throws an error. It doesn't print ` ERROR!`.

QGIS 3.16.2-Hannover, Ubuntu 20.04.1 LTS  
QGIS 3.16.0-Hannover, Windows 10 x64

  [1]: https://gis.stackexchange.com/questions/310787/getting-log-message-from-qgis-processing-framework
  [2]: https://qgis.org/api/classQgsProcessingFeedback.html#ad1c14839a74c2ef1a5caef4b57a638b9

**Comment by nyalldawson** [comment]
If a python exception is raised when running the algorithm then reportError won't be called -- you need to try/except the call to processing.run
