### ISSUE TITLE
QGIS Crash due to changing "Show all objects" to "Only selected objects" in attribute table

### ISSUE THREAD

**Issue by Maetthubern** [qgis/QGIS#40979]
## User Feedback

In the attribute table, I was in Edit Mode, had a String field selected (cursor was blinking) and then went from "Show all objects" to "Only show selectes objects. Subsquently, QGIS crashed"

## Report Details

**Crash ID**: [d5ef1418722eaa93bbd0a2c07776cf6cff4df2c3](https://github.com/qgis/QGIS/search?q=d5ef1418722eaa93bbd0a2c07776cf6cff4df2c3&type=Issues)

**Stack Trace**
<pre>
QModelIndex::flags :
QAbstractItemView::currentChanged :
QMetaObject::activate :
QItemSelectionModel::`default constructor closure' :
QItemSelectionModel::qt_static_metacall :
QMetaObject::activate :
QAbstractItemModel::beginRemoveRows :
QSortFilterProxyModel::removeRows :
QSortFilterProxyModel::flags :
QSortFilterProxyModel::filterRole :
QSortFilterProxyModel::invalidateFilter :
QgsAttributeTableFilterModel::setFilterMode qgsattributetablefiltermodel.cpp:338
QgsDualView::setFilterMode qgsdualview.cpp:373
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QMenu::exec :
QToolButton::paintEvent :
QToolButton::showMenu :
QToolButton::~QToolButton :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::mousePressEvent :
QToolButton::mousePressEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1637
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.16.2-Hannover
QGIS code revision: f1660f9da5
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

**Comment by gioman** [comment]
@Maetthubern please try with a new QGIS profile, no 3rd party plugins installed.

**Comment by gioman** [comment]
If the problem persist please attach a sample project + data.
