### ISSUE TITLE
QField export basemap single layer exports all the layers (literally) instead of a single one

### ISSUE THREAD

**Issue by tdeboss** [qgis/QGIS#40972]
IMPORTANT:

If the issue concerns a third party plugin (downloaded with the plugin manager) then it can't be fixed by the QGIS team.
Please raise your issue in the dedicated bug tracker for that specific plugin (as listed in the plugin's description)

Tickets created here will be closed.

**Comment by roya0045** [comment]
please read.

**Comment by tdeboss** [comment]
i know what it states, i am just being polite and sharing over here too
