### ISSUE TITLE
Identify features via rectangle does not work in all scenarios

### ISSUE THREAD

**Issue by stefanuhrig** [qgis/QGIS#40985]
The identification of features via rectangle does not always work if a vector layer is using a CRS different from the project CRS.

If a rectangle is drawn, the rectangle is transformed to the vector layer's CRS, and the transformed rectangle is used to query the vector layer. Currently, the rectangle transformation of the Identify Feature functionality transforms only the lower-left and upper-right corner of the rectangle.

However, after transformation to the vector layer CRS, the rectangle is not necessarily an axis-parallel rectangle anymore (or a rectangle at all).

The following video recorded by @m-kuhn shows the issue:

https://user-images.githubusercontent.com/10857909/104437896-a3b27d00-558f-11eb-9e1c-0fd3053f9ae6.mp4

In this particular case, the project used CRS EPSG:2056 (a CRS for Switzerland), the vector layer used EPSG:4326 and the point was located near Canada.

The following image shows why the feature selection fails:

![image005](https://user-images.githubusercontent.com/10857909/104438178-fd1aac00-558f-11eb-91d0-e06ea22a1c0b.png)

The tilted rectangle is the result of transforming all corners of the rectangle to the vector layer CRS while the axis-parallel rectangle is the result of just transforming the lower-left and upper-right corner.

The rectangle transformation is done by `QgsMapToolIdentify::identifyVectorLayer()`, which calls
- `QgsMapTool::toLayerCoordinates()`
- `QgsMapSettings::mapToLayerCoordinates()`
- `QgsCoordinateTransform::transform()`

`QgsCoordinateTransform` already contains the method `transformBoundingBox()` that deals with these projection issues by generating intermediate points. Maybe it would be a solution to use that method instead.

If you agree to use `transformBoundingBox()` (or if you have a different suggestion how to solve the issue), I can prepare a pull request. However, I will need some guidance, especially when it comes to creating a regression test.

**Comment by elpaso** [comment]
@stefanuhrig if you are going to fix it yourself would you please assign this issue to yourself so that other developers don't spend their time looking at it?

If you need any assistance with the tests, I can help.

I would recommend to start adding a failing test case to one of the existing python tests, then apply your modifications and make it pass.

**Comment by stefanuhrig** [comment]
@elpaso It seems I don't have permission to assign the issue to myself. Can you assign it to me or give me the necessary permissions?

Would `tests/srs/app/testqgsmaptoolidentifyaction.cpp` be the proper file to add the test? I couldn't find a Python based test.

**Comment by gioman** [comment]
> @elpaso It seems I don't have permission to assign the issue to myself. Can you assign it to me or give me the necessary permissions?

@stefanuhrig done.

**Comment by Pedro-Murteira** [comment]
@stefanuhrig Hello, I'm not being able to reproduce this issue on QGIS 3.22.4 and 3.24.0. Did you come across this issue more recently?

**Comment by stefanuhrig** [comment]
No, but I didn't try it for a long time. Let me re-check...

**Comment by stefanuhrig** [comment]
I tried it on 3.24.0.2 RC and could not reproduce the issue anymore. I'll close the issue.
