### ISSUE TITLE
'Save Keyboards Shortcuts' results in an (almost) empty file

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS#40995]
Using the 'Save' button in the Keyboard Shortcuts dialog (Settings/Keyboard Shortcuts) results in a file with only:
```
<!DOCTYPE shortcuts>
<qgsshortcuts locale="en_US" version="1.0"/>
```
Not really sure if this is a bug or by design... 

It could be that 'saving' the shortcuts ONLY save the non-defaults ones? 

Background of the question is somebody asking for a list of shortcuts on the Telegram channel.

@nyalldawson / North Road created a nice one: https://north-road.com/qgis-3-0-shortcuts/

It would be supercool to be able to let QGIS spit out something like that? 
But a simple list with ALL shortcuts (not only the non-default ones) would already be great.

![Screenshot-20210113174903-975x755](https://user-images.githubusercontent.com/731673/104482793-a630c900-55c7-11eb-8a99-71793f4c0446.png)

**Comment by uclaros** [comment]
Yes, the exported shortcuts are the ones stored in settings, so only non default ones. Maybe change this to a feature request?

**Comment by rduivenvoorde** [comment]
Ok let's make this a Feature Request to (optionally?) save ALL shortcuts into the export file.

And while on it: export to pdf format too ;-)
