### ISSUE TITLE
r.watershed error on macOS

### ISSUE THREAD

**Issue by nportilloda** [qgis/QGIS#40996]
When using the r.watershed tool, here is the error that is arising. I've tried changing the GRASS path to custom /Applications/QGIS.app/Contents/Resources/grass78 and it doesn't seem to work either. I have used a threshold as suggested in some older posts. 

![image](https://user-images.githubusercontent.com/63715922/104487714-ba77c480-55cd-11eb-8793-17eac8ede07d.png)

Here are the screenshots of the log panel:
![image](https://user-images.githubusercontent.com/63715922/104487764-ccf1fe00-55cd-11eb-9910-316ba126915a.png)
![image](https://user-images.githubusercontent.com/63715922/104487785-d4190c00-55cd-11eb-89a8-fe804f208e5e.png)
![image](https://user-images.githubusercontent.com/63715922/104487798-d8452980-55cd-11eb-8c45-dfab1af30015.png)
![image](https://user-images.githubusercontent.com/63715922/104487807-dbd8b080-55cd-11eb-9d21-ca610f28332c.png)

and the log error from the r.watershed window

https://github.com/qgis/QGIS/discussions/40991#discussion-1760291

`QGIS version: 3.16.2-Hannover
QGIS code revision: c6ac5a6052
Qt version: 5.14.2
GDAL version: 3.1.2
GEOS version: 3.8.1-CAPI-1.13.3
PROJ version: Rel. 6.3.2, May 1st, 2020
Processing algorithm…
Algorithm 'r.watershed' starting…
Input parameters:
{ '-4' : False, '-a' : True, '-b' : False, '-m' : False, '-s' : False, 'GRASS_RASTER_FORMAT_META' : '', 'GRASS_RASTER_FORMAT_OPT' : '', 'GRASS_REGION_CELLSIZE_PARAMETER' : 0, 'GRASS_REGION_PARAMETER' : None, 'accumulation' : 'TEMPORARY_OUTPUT', 'basin' : 'TEMPORARY_OUTPUT', 'blocking' : None, 'convergence' : 5, 'depression' : None, 'disturbed_land' : None, 'drainage' : 'TEMPORARY_OUTPUT', 'elevation' : '/Users/nereaportillo/GoogleDrive/HydrologyCourse_Tutorial/Tutorial1/StartingFiles/ProducedFiles/ClippedRaster_100.tif', 'flow' : None, 'half_basin' : 'TEMPORARY_OUTPUT', 'length_slope' : 'TEMPORARY_OUTPUT', 'max_slope_length' : None, 'memory' : 300, 'slope_steepness' : 'TEMPORARY_OUTPUT', 'spi' : 'TEMPORARY_OUTPUT', 'stream' : 'TEMPORARY_OUTPUT', 'tci' : 'TEMPORARY_OUTPUT', 'threshold' : 10000 }

g.proj -c proj4="+proj=utm +zone=32 +datum=WGS84 +units=m +no_defs"
r.in.gdal input="/Users/nereaportillo/GoogleDrive/HydrologyCourse_Tutorial/Tutorial1/StartingFiles/ProducedFiles/ClippedRaster_100.tif" band=1 output="rast_5fff03d50c3b23" --overwrite -o
g.region n=5220505.948041441 s=4997005.948041441 e=761957.6499743497 w=605957.6499743497 res=100.0
r.watershed elevation=rast_5fff03d50c3b23 threshold=10000 convergence=5 memory=300 -a accumulation=accumulationda7f058a515d4042be4019d89f074b90 drainage=drainageda7f058a515d4042be4019d89f074b90 basin=basinda7f058a515d4042be4019d89f074b90 stream=streamda7f058a515d4042be4019d89f074b90 half_basin=half_basinda7f058a515d4042be4019d89f074b90 length_slope=length_slopeda7f058a515d4042be4019d89f074b90 slope_steepness=slope_steepnessda7f058a515d4042be4019d89f074b90 tci=tcida7f058a515d4042be4019d89f074b90 spi=spida7f058a515d4042be4019d89f074b90 --overwrite
g.region raster=accumulationda7f058a515d4042be4019d89f074b90
r.out.gdal -t -m input="accumulationda7f058a515d4042be4019d89f074b90" output="/private/var/folders/rd/wzfh_5h110l121rmlxn61v440000gn/T/processing_GbfqfG/380e1af20b9742279de873637b6a3743/accumulation.tif" format="GTiff" createopt="TFW=YES,COMPRESS=LZW" --overwrite
g.region raster=drainageda7f058a515d4042be4019d89f074b90
r.out.gdal -t -m input="drainageda7f058a515d4042be4019d89f074b90" output="/private/var/folders/rd/wzfh_5h110l121rmlxn61v440000gn/T/processing_GbfqfG/8af72f5d223b4c0580960ed8d10e9d6d/drainage.tif" format="GTiff" createopt="TFW=YES,COMPRESS=LZW" --overwrite
g.region raster=basinda7f058a515d4042be4019d89f074b90
r.out.gdal -t -m input="basinda7f058a515d4042be4019d89f074b90" output="/private/var/folders/rd/wzfh_5h110l121rmlxn61v440000gn/T/processing_GbfqfG/406ebc609b1e4a8e915809b63fc99287/basin.tif" format="GTiff" createopt="TFW=YES,COMPRESS=LZW" --overwrite
g.region raster=streamda7f058a515d4042be4019d89f074b90
r.out.gdal -t -m input="streamda7f058a515d4042be4019d89f074b90" output="/private/var/folders/rd/wzfh_5h110l121rmlxn61v440000gn/T/processing_GbfqfG/6238708b6f384f8f88eb4b2bed9c513e/stream.tif" format="GTiff" createopt="TFW=YES,COMPRESS=LZW" --overwrite
g.region raster=half_basinda7f058a515d4042be4019d89f074b90
r.out.gdal -t -m input="half_basinda7f058a515d4042be4019d89f074b90" output="/private/var/folders/rd/wzfh_5h110l121rmlxn61v440000gn/T/processing_GbfqfG/86c83b4372ff400181286a969191f4ed/half_basin.tif" format="GTiff" createopt="TFW=YES,COMPRESS=LZW" --overwrite
g.region raster=length_slopeda7f058a515d4042be4019d89f074b90
r.out.gdal -t -m input="length_slopeda7f058a515d4042be4019d89f074b90" output="/private/var/folders/rd/wzfh_5h110l121rmlxn61v440000gn/T/processing_GbfqfG/74e08f54aae54e8083d6aeab2bd9c2c8/length_slope.tif" format="GTiff" createopt="TFW=YES,COMPRESS=LZW" --overwrite
g.region raster=slope_steepnessda7f058a515d4042be4019d89f074b90
r.out.gdal -t -m input="slope_steepnessda7f058a515d4042be4019d89f074b90" output="/private/var/folders/rd/wzfh_5h110l121rmlxn61v440000gn/T/processing_GbfqfG/7ed4b36c2a4a45f0902c49cc441e73e2/slope_steepness.tif" format="GTiff" createopt="TFW=YES,COMPRESS=LZW" --overwrite
g.region raster=tcida7f058a515d4042be4019d89f074b90
r.out.gdal -t -m input="tcida7f058a515d4042be4019d89f074b90" output="/private/var/folders/rd/wzfh_5h110l121rmlxn61v440000gn/T/processing_GbfqfG/ad1718f30f5a44329ceaa060b73ebf65/tci.tif" format="GTiff" createopt="TFW=YES,COMPRESS=LZW" --overwrite
g.region raster=spida7f058a515d4042be4019d89f074b90
r.out.gdal -t -m input="spida7f058a515d4042be4019d89f074b90" output="/private/var/folders/rd/wzfh_5h110l121rmlxn61v440000gn/T/processing_GbfqfG/ea17295e8b7f421e9c588d444dda9dd9/spi.tif" format="GTiff" createopt="TFW=YES,COMPRESS=LZW" --overwrite
Default locale settings are missing. GRASS running with C locale.
Starting GRASS GIS...
Cleaning up temporary files...
Executing </private/var/folders/rd/wzfh_5h110l121rmlxn61v440000gn/T/processing_GbfqfG/grassdata/grass_batch_job.sh> ...
Default region was updated to the new projection, but if you have multiple mapsets `g.region -d` should be run in each to update the region from the default
Projection information updated
Over-riding projection check
Importing raster map <rast_5fff03d50c3b23>...
0..3..6..9..12..15..18..21..24..27..30..33..36..39..42..45..48..51..54..57..60..63..66..69..72..75..78..81..84..87..90..93..96..99..100
dyld: Library not loaded: @rpath/libgrass_raster.7.8.dylib
Referenced from: /Applications/QGIS.app/Contents/Resources/grass78/etc/r.watershed/ram
Reason: image not found
WARNING: Subprocess failed with exit code 6
WARNING: category information for [accumulationda7f058a515d4042be4019d89f074b90] in [PERMANENT] missing or invalid
WARNING: category information for [tcida7f058a515d4042be4019d89f074b90] in [PERMANENT] missing or invalid
WARNING: category information for [spida7f058a515d4042be4019d89f074b90] in [PERMANENT] missing or invalid
WARNING: category information for [drainageda7f058a515d4042be4019d89f074b90] in [PERMANENT] missing or invalid
WARNING: category information for [basinda7f058a515d4042be4019d89f074b90] in [PERMANENT] missing or invalid
WARNING: category information for [streamda7f058a515d4042be4019d89f074b90] in [PERMANENT] missing or invalid
WARNING: category information for [half_basinda7f058a515d4042be4019d89f074b90] in [PERMANENT] missing or invalid
WARNING: category information for [length_slopeda7f058a515d4042be4019d89f074b90] in [PERMANENT] missing or invalid
WARNING: category information for [slope_steepnessda7f058a515d4042be4019d89f074b90] in [PERMANENT] missing or invalid
ERROR: Raster map <accumulationda7f058a515d4042be4019d89f074b90> not found
ERROR: Raster map or group <accumulationda7f058a515d4042be4019d89f074b90> not found
ERROR: Raster map <drainageda7f058a515d4042be4019d89f074b90> not found
ERROR: Raster map or group <drainageda7f058a515d4042be4019d89f074b90> not found
ERROR: Raster map <basinda7f058a515d4042be4019d89f074b90> not found
ERROR: Raster map or group <basinda7f058a515d4042be4019d89f074b90> not found
ERROR: Raster map <streamda7f058a515d4042be4019d89f074b90> not found
ERROR: Raster map or group <streamda7f058a515d4042be4019d89f074b90> not found
ERROR: Raster map <half_basinda7f058a515d4042be4019d89f074b90> not found
ERROR: Raster map or group <half_basinda7f058a515d4042be4019d89f074b90> not found
ERROR: Raster map <length_slopeda7f058a515d4042be4019d89f074b90> not found
ERROR: Raster map or group <length_slopeda7f058a515d4042be4019d89f074b90> not found
ERROR: Raster map <slope_steepnessda7f058a515d4042be4019d89f074b90> not found
ERROR: Raster map or group <slope_steepnessda7f058a515d4042be4019d89f074b90> not found
ERROR: Raster map <tcida7f058a515d4042be4019d89f074b90> not found
ERROR: Raster map or group <tcida7f058a515d4042be4019d89f074b90> not found
ERROR: Raster map <spida7f058a515d4042be4019d89f074b90> not found
ERROR: Raster map or group <spida7f058a515d4042be4019d89f074b90> not found
Execution of </private/var/folders/rd/wzfh_5h110l121rmlxn61v440000gn/T/processing_GbfqfG/grassdata/grass_batch_job.sh> finished.
Cleaning up temporary files...
Default locale settings are missing. GRASS running with C locale.
Starting GRASS GIS...
Cleaning up temporary files...
Executing </private/var/folders/rd/wzfh_5h110l121rmlxn61v440000gn/T/processing_GbfqfG/grassdata/grass_batch_job.sh> ...
ERROR: Raster map <accumulationda7f058a515d4042be4019d89f074b90> not found
ERROR: Raster map or group <accumulationda7f058a515d4042be4019d89f074b90> not found
ERROR: Raster map <drainageda7f058a515d4042be4019d89f074b90> not found
ERROR: Raster map or group <drainageda7f058a515d4042be4019d89f074b90> not found
ERROR: Raster map <basinda7f058a515d4042be4019d89f074b90> not found
ERROR: Raster map or group <basinda7f058a515d4042be4019d89f074b90> not found
ERROR: Raster map <streamda7f058a515d4042be4019d89f074b90> not found
ERROR: Raster map or group <streamda7f058a515d4042be4019d89f074b90> not found
ERROR: Raster map <half_basinda7f058a515d4042be4019d89f074b90> not found
ERROR: Raster map or group <half_basinda7f058a515d4042be4019d89f074b90> not found
ERROR: Raster map <length_slopeda7f058a515d4042be4019d89f074b90> not found
ERROR: Raster map or group <length_slopeda7f058a515d4042be4019d89f074b90> not found
ERROR: Raster map <slope_steepnessda7f058a515d4042be4019d89f074b90> not found
ERROR: Raster map or group <slope_steepnessda7f058a515d4042be4019d89f074b90> not found
ERROR: Raster map <tcida7f058a515d4042be4019d89f074b90> not found
ERROR: Raster map or group <tcida7f058a515d4042be4019d89f074b90> not found
ERROR: Raster map <spida7f058a515d4042be4019d89f074b90> not found
ERROR: Raster map or group <spida7f058a515d4042be4019d89f074b90> not found
Execution of </private/var/folders/rd/wzfh_5h110l121rmlxn61v440000gn/T/processing_GbfqfG/grassdata/grass_batch_job.sh> finished.
Cleaning up temporary files...
Execution completed in 5.12 seconds
Results:
{'accumulation': '/private/var/folders/rd/wzfh_5h110l121rmlxn61v440000gn/T/processing_GbfqfG/380e1af20b9742279de873637b6a3743/accumulation.tif',
'basin': '/private/var/folders/rd/wzfh_5h110l121rmlxn61v440000gn/T/processing_GbfqfG/406ebc609b1e4a8e915809b63fc99287/basin.tif',
'drainage': '/private/var/folders/rd/wzfh_5h110l121rmlxn61v440000gn/T/processing_GbfqfG/8af72f5d223b4c0580960ed8d10e9d6d/drainage.tif',
'half_basin': '/private/var/folders/rd/wzfh_5h110l121rmlxn61v440000gn/T/processing_GbfqfG/86c83b4372ff400181286a969191f4ed/half_basin.tif',
'length_slope': '/private/var/folders/rd/wzfh_5h110l121rmlxn61v440000gn/T/processing_GbfqfG/74e08f54aae54e8083d6aeab2bd9c2c8/length_slope.tif',
'slope_steepness': '/private/var/folders/rd/wzfh_5h110l121rmlxn61v440000gn/T/processing_GbfqfG/7ed4b36c2a4a45f0902c49cc441e73e2/slope_steepness.tif',
'spi': '/private/var/folders/rd/wzfh_5h110l121rmlxn61v440000gn/T/processing_GbfqfG/ea17295e8b7f421e9c588d444dda9dd9/spi.tif',
'stream': '/private/var/folders/rd/wzfh_5h110l121rmlxn61v440000gn/T/processing_GbfqfG/6238708b6f384f8f88eb4b2bed9c513e/stream.tif',
'tci': '/private/var/folders/rd/wzfh_5h110l121rmlxn61v440000gn/T/processing_GbfqfG/ad1718f30f5a44329ceaa060b73ebf65/tci.tif'}

Loading resulting layers
The following layers were not correctly generated.
• /private/var/folders/rd/wzfh_5h110l121rmlxn61v440000gn/T/processing_GbfqfG/380e1af20b9742279de873637b6a3743/accumulation.tif
• /private/var/folders/rd/wzfh_5h110l121rmlxn61v440000gn/T/processing_GbfqfG/406ebc609b1e4a8e915809b63fc99287/basin.tif
• /private/var/folders/rd/wzfh_5h110l121rmlxn61v440000gn/T/processing_GbfqfG/6238708b6f384f8f88eb4b2bed9c513e/stream.tif
• /private/var/folders/rd/wzfh_5h110l121rmlxn61v440000gn/T/processing_GbfqfG/74e08f54aae54e8083d6aeab2bd9c2c8/length_slope.tif
• /private/var/folders/rd/wzfh_5h110l121rmlxn61v440000gn/T/processing_GbfqfG/7ed4b36c2a4a45f0902c49cc441e73e2/slope_steepness.tif
• /private/var/folders/rd/wzfh_5h110l121rmlxn61v440000gn/T/processing_GbfqfG/86c83b4372ff400181286a969191f4ed/half_basin.tif
• /private/var/folders/rd/wzfh_5h110l121rmlxn61v440000gn/T/processing_GbfqfG/8af72f5d223b4c0580960ed8d10e9d6d/drainage.tif
• /private/var/folders/rd/wzfh_5h110l121rmlxn61v440000gn/T/processing_GbfqfG/ad1718f30f5a44329ceaa060b73ebf65/tci.tif
• /private/var/folders/rd/wzfh_5h110l121rmlxn61v440000gn/T/processing_GbfqfG/ea17295e8b7f421e9c588d444dda9dd9/spi.tif
You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.`

Here is the link for the original post discussion:
https://github.com/qgis/QGIS/discussions/40991#discussion-1760291

This is the reply from one of the Collaborators:
@nportilloda the module works fine on Linux and Windows, it may be very well that Processing/GRASS is not working on macOS, it won't be surprising as they are several other reports about it. Anyway I can give it a try on my (very secondary) mac mini. Attach/link the data (the digital elevation model) so we are sure is not something that is data dependent.

_Originally posted by @gioman in https://github.com/qgis/QGIS/discussions/40991#discussioncomment-279289_

**Comment by gioman** [comment]
Oddly enough it seems that Processing/GRASS works well in general on macOS, but for some reason the r.watershed does not. This is both a good and bad news.... good as is not a general issue on macOS, bad because we now have to understand why this specific module does not work (and here is the oddity, as the way this module works has nothing different compared to other working ones, like r.slope.aspect or r.contour or many more others.

**Comment by PeterPetrik** [comment]
looks like a bug in packager: https://github.com/qgis/QGIS-Mac-Packager/blob/610b41dcd8929a14ed6344399d9662955aaef35b/qgis_bundle/recipes/grass/recipe.sh#L235 
it is in extra subdirectory so it does not find the correct libraries on the relative paths. will fix

**Comment by PeterPetrik** [comment]
should be fixed in https://qgis.org/downloads/macos/nightly/qgis_nightly_master_20200701_123103.dmg

**Comment by nportilloda** [comment]
Perfect! Just tried it and it is working!! Thanks!

**Comment by asioleh** [comment]
Hi, I was trying to run r.watershed, but it doesn't work and shows this message:

QGIS version: 3.18.3-Zürich
Qt version: 5.15.2
GDAL version: 3.2.2
GEOS version: 3.9.1-CAPI-1.14.2
PROJ version: Rel. 7.2.1, January 1st, 2021
Processing algorithm…
Algorithm 'r.watershed' starting…
Input parameters:
{ '-4' : False, '-a' : False, '-b' : False, '-m' : False, '-s' : False, 'GRASS_RASTER_FORMAT_META' : '', 'GRASS_RASTER_FORMAT_OPT' : '', 'GRASS_REGION_CELLSIZE_PARAMETER' : 0, 'GRASS_REGION_PARAMETER' : None, 'accumulation' : 'TEMPORARY_OUTPUT', 'basin' : 'TEMPORARY_OUTPUT', 'blocking' : None, 'convergence' : 5, 'depression' : None, 'disturbed_land' : None, 'drainage' : 'TEMPORARY_OUTPUT', 'elevation' : '/private/var/folders/tr/hfk0hwj17hzbqhnthrp6wf7c0000gn/T/processing_eJIkcy/a89a9dcd432c4a3fa29f6004e8e9af03/RESULT.sdat', 'flow' : None, 'half_basin' : 'TEMPORARY_OUTPUT', 'length_slope' : 'TEMPORARY_OUTPUT', 'max_slope_length' : None, 'memory' : 300, 'slope_steepness' : 'TEMPORARY_OUTPUT', 'spi' : 'TEMPORARY_OUTPUT', 'stream' : 'TEMPORARY_OUTPUT', 'tci' : 'TEMPORARY_OUTPUT', 'threshold' : 100 }

Traceback (most recent call last):
File "/Applications/QGIS3.18.app/Contents/MacOS/../Resources/python/plugins/processing/algs/grass7/Grass7Algorithm.py", line 423, in processAlgorithm
getattr(self, fullName)(parameters, context, feedback)
File "/Applications/QGIS3.18.app/Contents/MacOS/../Resources/python/plugins/processing/algs/grass7/Grass7Algorithm.py", line 480, in processInputs
self.loadRasterLayerFromParameter(
File "/Applications/QGIS3.18.app/Contents/MacOS/../Resources/python/plugins/processing/algs/grass7/Grass7Algorithm.py", line 731, in loadRasterLayerFromParameter
self.loadRasterLayer(name, layer, external, band)
File "/Applications/QGIS3.18.app/Contents/MacOS/../Resources/python/plugins/processing/algs/grass7/Grass7Algorithm.py", line 746, in loadRasterLayer
self.setSessionProjectionFromLayer(layer)
File "/Applications/QGIS3.18.app/Contents/MacOS/../Resources/python/plugins/processing/algs/grass7/Grass7Algorithm.py", line 1044, in setSessionProjectionFromLayer
self.setSessionProjection(layer.crs())
File "/Applications/QGIS3.18.app/Contents/MacOS/../Resources/python/plugins/processing/algs/grass7/Grass7Algorithm.py", line 1051, in setSessionProjection
file_name = Grass7Utils.exportCrsWktToFile(crs)
File "/Applications/QGIS3.18.app/Contents/MacOS/../Resources/python/plugins/processing/algs/grass7/Grass7Utils.py", line 95, in exportCrsWktToFile
f.write(wkt)
UnicodeEncodeError: 'ascii' codec can't encode character '\xb0' in position 921: ordinal not in range(128)

Execution failed after 0.18 seconds

Loading resulting layers
Algorithm 'r.watershed' finished


I don't know what the problem is. Any help? 
Thanks in advance

**Comment by gioman** [comment]
> Hi, I was trying to run r.watershed, but it doesn't work and shows this message:

@asioleh post your input and parameters used.

**Comment by asioleh** [comment]
Hi, @gioman, thanks for your attention
The raster I'm trying to use the r.watershed is the result of these pre-processed actions:

1- Merged two previous rasters
2- Clipped by mask layer
3- Used GDAL Fill nodata...
4- Used Fill Sinks (SAGA)

The raster resulted is the "ChapadaD_FilledDEM" and the only parameter I put was the "Minimum size of exterior watershed basin", 100

![Screen Shot 2021-06-04 at 15 31 42](https://user-images.githubusercontent.com/84868398/120848315-0ad6cb00-c54b-11eb-8f80-a61e7af0d674.png)
![Screen Shot 2021-06-04 at 15 32 20](https://user-images.githubusercontent.com/84868398/120848326-0e6a5200-c54b-11eb-9fde-49bbc404b1e6.png)
![Screen Shot 2021-06-04 at 15 55 11](https://user-images.githubusercontent.com/84868398/120850118-60ac7280-c54d-11eb-9c81-90d743e90cc0.png)
![Screen Shot 2021-06-04 at 15 55 56](https://user-images.githubusercontent.com/84868398/120850119-61450900-c54d-11eb-90e2-ae9806707f75.png)

**Comment by gioman** [comment]
>  4- Used Fill Sinks (SAGA)

@asioleh post/link/attach this.

**Comment by asioleh** [comment]
this?
![Screen Shot 2021-06-04 at 17 02 02](https://user-images.githubusercontent.com/84868398/120856776-b6394d00-c556-11eb-94b2-48817c8e95fb.png)
![Screen Shot 2021-06-04 at 17 02 12](https://user-images.githubusercontent.com/84868398/120856793-b89ba700-c556-11eb-86e4-f2fbf334da9d.png)

**Comment by gioman** [comment]
> this?

@asioleh the file, we need the input for r.watershed (so the output of fillsinks).

**Comment by asioleh** [comment]
Oh, sorry... The info on the link of the fillsinks:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<PAMDataset>
<SRS>PROJCS["WGS 84 / UTM zone 23S",GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",-45],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",500000],PARAMETER["false_northing",10000000],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH],AUTHORITY["EPSG","32723"]]</SRS>
</PAMDataset>

**Comment by gioman** [comment]
> Oh, sorry... The info on the link of the fillsinks:

@asioleh we need the file, the raster (a dem) that is the output of fillsinks.

**Comment by asioleh** [comment]
See if You can open this, because I was having problem to save the fillsink

[ChapadaD.tif.zip](https://github.com/qgis/QGIS/files/6601492/ChapadaD.tif.zip)

**Comment by gioman** [comment]
> [ChapadaD.tif.zip](https://github.com/qgis/QGIS/files/6601492/ChapadaD.tif.zip)

@asioleh works for me on 3.18.3 on macOS Catalina, with or without Fill Sinks first.

**Comment by gioman** [comment]
> How did you do it?

@tinti152131 installed QGIS 3.18.3 on macOS Catalina.

**Comment by tinti152131** [comment]
@gioman I also got QGIS 3.18.3 (but in macOS BigSur) 

@asioleh I have different raster data in my project, one "original" that I downloaded and one "processed" that I reprojected using "warp". I can do the r.watershed with the original data but not, with the reprojected one. During my research I found some post that the error might be related to "non Asci letters" like ö, ü, ä but I checked that several times and I dont see those letters in my project. Unfortunately I need to combine different "original" rasters and as soon as I combine them, I get the same error like you got. So I dont know why but something is wrong and as Iam not very experienced with phyton I cant solve it. But I will let you know if I find a solution.

**Comment by asioleh** [comment]
@tinti152131 I didn't pay attention to the fact that I used the target CRS when I clipped the original rasters. I tried the r.watershed without changing the CRS and it worked. And when I try to change the CRS info on the original raster, it gets lost (doesnt show any image). So I think the problem is an error on the program to relocate the map and this makes the r.watershed doesnt work.

**Comment by gioman** [comment]
> So I think the problem is an error on the program to relocate the map

@asioleh there is no reprojection: GRASS tools process the data (and outputs it) in its original CRS.

**Comment by tinti152131** [comment]
@gioman  you are right
@asioleh I now used the original data (without any changes in the CRS) and it worked out! In the end I reprojected the output (shapefile of my chosen watershed) so I can place it on the right spot in my map. Worked for me this way. Hope it does for you as well!

**Comment by asioleh** [comment]
Yes, I realized it. That the r.watershed will not work on rasters reprojected.

**Comment by asioleh** [comment]
> there is no reprojection: GRASS tools process the data (and outputs it) in its original CRS.

I'm not sure about it, because:

> works for me on 3.18.3 on macOS Catalina, with or without Fill Sinks first.

this raster doesn't work for me, but it worked for you. That raster was clipped with another CRS (not the original). And I know that on Windows it is possible to run r.watershed with a clipped raster with a different CRS.

Thanks anyway, I'm juts glad that r.watershed is working.

**Comment by gioman** [comment]
> That raster was clipped with another CRS (not the original)

@asioleh describe **in detail** the steps you are following. Attach data if needed.

**Comment by asioleh** [comment]
@gioman 
1. merged two original raster (CRS 4326)
2. clip the merged raster (CRS 4326) with the vector was CRS 4618, targeted to CRS 32723 and assigned zero to "specific nodata value"
![Screen Shot 2021-06-08 at 17 08 37](https://user-images.githubusercontent.com/84868398/121251070-d762ac00-c87c-11eb-85c5-553726301ef9.png)

**Comment by gioman** [comment]
> * merged two original raster (CRS 4326)
> 
> * clip the merged raster (CRS 4326) with the vector was CRS 4618, targeted to CRS 32723 and assigned zero to "specific nodata value"

@asioleh and here lies the issue: you can clip a raster with an extent defined in CRS does do not match the raster CRS, but the clipped raster CRS is the same as the original, in your case 4326 and there are analysis (a lot of them) that need a projected CRS (in meters) for the inputs. 4326 is in degrees.

**Comment by asioleh** [comment]
@gioman yeah, it should be a projected CRS in meters, thats why I tried to target to CRS 32723 to run r.watershed. 
so you are saying that even though I target to CRS 32723 the clipped raster, will it remain as 4326? because the info on the clipped raster says (thats the one you could run and I couldn't): 
![Screen Shot 2021-06-08 at 18 45 52](https://user-images.githubusercontent.com/84868398/121262166-11867a80-c88a-11eb-86d1-511e91ef8c76.png)
 
But when I keep it in CRS 4326, as this one, it runs:
![Screen Shot 2021-06-08 at 18 50 01](https://user-images.githubusercontent.com/84868398/121264323-595ad100-c88d-11eb-841c-11ad43f0dded.png)
I really don't understand why, sorry
