### ISSUE TITLE
Outputs attributes tables from Processing/SAGA have crippled special chars if input is not a shapefile

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#40992]
Take a vector with special/accented characters in its attribute table.

If you processing this with Processing/SAGA and the input format is not a shapefile then the output will have those chars crippled.

This do not happen if the input is a shapefile and also do not happen if running from the CLI the same SAGA command that QGIS runs.

**Comment by roya0045** [comment]
Is it with saga only? I find it strange that some element of the ui would force an encoding on specific output format.

**Comment by gioman** [comment]
> Is it with saga only?

@roya0045 GDAL and GRASS tools seems not affected.

**Comment by alexbruy** [comment]
SAGA Provider was not maintained and now remowed from QGIS (see #50834). Users are encouraged to use the 3rd-party plugins instead.
