### ISSUE TITLE
geom_to_wkt() generates not closed polygon

### ISSUE THREAD

**Issue by nilufercipa** [qgis/QGIS#41008]
I have a gpkg file and I am changing the geometry to wkt format by using the expression `geom_to_wkt( $geometry )` in the Field Calculator.
As it is in the picture, the geometry type is not written in capital letters, and the polygon is not closed as the WKT standard states. I tested it in  3.10.13,  3.12. and 3.16.2. The output is always as in the image. I am on  Windows 10 64bit. 

![image](https://user-images.githubusercontent.com/68850468/104567684-5990d080-564f-11eb-9f6b-09a7e32ba8fc.png)

My output speaks against what the [documentation ](https://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/geometry.html#geometry-construction)here says
>A Polygon is represented by a list of linear rings (i.e. closed linestrings). The first ring is the outer ring (boundary), optional subsequent rings are holes in the polygon. Note that unlike some programs, QGIS will close the ring for you so there is no need to duplicate the first point as the last

**Comment by uclaros** [comment]
Can you try `geom_to_wkt( buffer( $geometry, 0 ) )` and see if it returns a closed polygon this time? The issue could be in your data; `geom_to_wkt` seems to be working fine for me.

**Comment by nilufercipa** [comment]
@uclaros I have tried it with the expression you suggested. Yes, I got the results with closed coordinates.

**Comment by uclaros** [comment]
Then the problem is in your geometries. You could repair them by running the `Fix geometries` processing algorithm.

**Comment by nilufercipa** [comment]
Is it normal that QGIS loads the layer without warning

**Comment by uclaros** [comment]
I guess it would be costly to check every geometry on every layer added. Warnings are usually fired when running processing algorithms, plus, you can always check your data with the *Check validity* processing algorithm.

**Comment by nilufercipa** [comment]
Yes, it returns "ring 0 with less than four points". Thanks a lot @uclaros

**Comment by kadirsahbaz** [comment]
I have a `Polygon ` layer (say `raw_layer`). 

There are no invalid geometries when I use _Check Validity_.  When I use `geom_to_wkt( $geometry )`  for `raw_layer` it doesn't return a closed polygon. But it returns the closed polygon for `Valid output` layer (from _Check Validity_ tool). 

While `raw_layer` is `Polygon`, `Valid output` returned by `Check Validty` is `MultiPolygon`.

There is something weird.

**Comment by nilufercipa** [comment]
@kadirsahbaz I observed similar behavior. When I should `Fix geometries` as @uclaros  suggest and then I ran ` geom_to_wkt( $geometry )`  and it returns 'MultiPolyg'.

**Comment by uclaros** [comment]
If one geometry in your dataset has more than one outer ring, then the resulting layer is promoted to multi to accommodate for that geometry. You can run *Multipart to singleparts* and compare the number of features to see if you indeed have multipolygons. Ifyou do not, it is probably a bug!
