### ISSUE TITLE
Translations for "First Run Dialog" still point to the 3.4 changelog link

### ISSUE THREAD

**Issue by TurboGraphxBeige** [qgis/QGIS#41028]
After installing QGIS and running it for the first time, the "Welcome to QGIS" is shown (aka QgsFirstRunDialog). The translated versions of this dialog shows the correct version of QGIS but the link at the bottom of the dialog still points to the 3.4 changelog (http://changelog.qgis.org/en/qgis/version/3.4-LTR/) while it should point to https://changelog.qgis.org/en/qgis/version/3.16/ (or https://www.qgis.org/en/site/forusers/visualchangelog316/index.html).

I haven't looked at ALL the translated languages, but I can confirm it affects at least the following:

- fr
- it
- nl
- es
- de

Tested on 3.16.2

![QGISbug_3_16_2_french_changelog](https://user-images.githubusercontent.com/59714546/104674507-c341c680-56b1-11eb-980d-67c90340af65.png)

**Comment by TurboGraphxBeige** [comment]
@jef-n So I'm not sure how this works for the translations. Simply changing the link like you did in your commit will be enough to propagate the new link to all the translations?

**Comment by DelazJ** [comment]
@TurboGraphxBeige generally speaking, this change is pulled by transifex and existing translations are lost, meaning that English sentence with correct link is used in the GUI until it is translated. But afaics, someone (@jef-n ?) already updated the translations in Transifex. So should be good running a really recent dev version

**Comment by roya0045** [comment]
@TurboGraphxBeige This can be closed?

**Comment by TurboGraphxBeige** [comment]
> 
> 
> @TurboGraphxBeige This can be closed?

Yup!
