### ISSUE TITLE
excel files and vrt problems updating data.. new rows doesn´t load

### ISSUE THREAD

**Issue by miguelzuza** [qgis/QGIS#41021]
I recently discovered an unexpected behavior with excel files.

When you attach an excel file QGIS creates a .vrt file that links the information within the file that you can reload from QGIS.

If you add rows to the excel file they doesn’t appear in QGIS when reloading (as you would expect)

I checked the vrt file and it´s like this one 
<?xml version="1.0" encoding="UTF-8"?>
<OGRVRTDataSource>
    <OGRVRTLayer name="SIMETRICOS-Hoja1">
        <SrcDataSource relativeToVRT="1">SIMETRICOS.xlsx</SrcDataSource>
        
        <SrcSql dialect="sqlite">SELECT * FROM 'Hoja1' **LIMIT 120** OFFSET 1</SrcSql>
        <Field name="NOMBRE" src="Field1" type="String"/>
        <Field name="SIMETRICO" src="Field2" type="String"/>
    </OGRVRTLayer>
</OGRVRTDataSource>

It creates a limit determined the first time you create the link and not updating the number of rows when you reload the file

It doesn’t load even if you change that number manually in the file

This may be very problematic as  users may think it reload all the items of the file including new rows

**Comment by gioman** [comment]
> When you attach

@miguelzuza do you mean "add" to a QGIS project? how you add the XLS file to the project? please be specific.

Also: what is your QGIS version? and your operating system?

**Comment by miguelzuza** [comment]
sorry.. tried in a new file and works.. something happened in the qgis file I was working 

It was with create layer from a spreadsheet file (add spreadsheet layer ) QGIS 3.16.2 Windows 10

but can´t reproduce the error with a new file

**Comment by miguelzuza** [comment]
I close the issue.. I have it on a file but can´t reproduce it

**Comment by gioman** [comment]
> add spreadsheet layer

@miguelzuza also because it is a 3rd party plugin, not core QGIS.
