### ISSUE TITLE
python/qgis/__init__.py messes up PATH environment

### ISSUE THREAD

**Issue by simolv** [qgis/QGIS#41020]
Hello,

Simon from setec hydratec here. We use Qgis as a tool for ou hydraulics simulations. First contribution.

**Describe the bug**

I noticed a bug while importing qgis modules from a Python initialised outside of Qgis itself (Windows 10, Qgis 3.10, Python 3.7):

The PATH environment variable is changed when importing ``from qgis``

**How to Reproduce**

Using the minimal code below:

````python
import os
for s in os.environ['PATH'].split(';'):
    print(s)

print('==================================')

from qgis.PyQt.QtCore import QCoreApplication
for s in os.environ['PATH'].split(';'):
    print(s)
````

outputs : 

````
C:\Users\simon.olive\Desktop>python path.py
C:\Program Files\QGIS 3.10\apps\qgis-ltr\bin
C:\Program Files\QGIS 3.10\apps\Python37
C:\Program Files\QGIS 3.10\apps\qgis-ltr\python
C:\Program Files\QGIS 3.10\apps\Python37\Scripts
C:\Program Files\QGIS 3.10\bin
C:\Program Files\QGIS 3.10\apps\Qt5\bin
C:\WINDOWS\system32
C:\WINDOWS
C:\WINDOWS\system32\WBem
C:\Program Files\QGIS 3.10\apps\Python37\lib\site-packages\pywin32_system32
C:\Program Files\QGIS 3.10\apps\Python37\lib\site-packages\numpy\.libs
C:\Program Files\PostgreSQL\9.6\bin

C:\Program Files\QGIS 3.10\apps\Python37\lib\site-packages\pywin32_system32
==================================
C:\PROGRA~1\QGIS 3.10\apps\qgis-ltr\bin
C:\PROGRA~1\QGIS 3.10\apps\Python37
C:\PROGRA~1\QGIS 3.10\apps\Python37\Scripts
C:\PROGRA~1\QGIS 3.10\apps\qt5\bin
C:\PROGRA~1\QGIS 3.10\bin
C:\WINDOWS\system32
C:\WINDOWS
C:\WINDOWS\system32\WBem
````

*Path has changed.*

**QGIS and OS versions**

````
Version de QGIS
3.10.6-A Coruña
Révision du code
ec80021f49
Compilé avec Qt
5.11.2
Utilisant Qt
5.11.2
Compilé avec GDAL/OGR
3.0.4
Utilisé avec GDAL/OGR
3.0.4
Compilé avec GEOS
3.8.1-CAPI-1.13.3
Utilisé avec GEOS
3.8.1-CAPI-1.13.3
Compilé avec SQLite
3.29.0
Fonctionne avec SQLite
3.29.0
Version du client PostgreSQL
11.5
Version de SpatiaLite
4.3.0
Version de QWT
6.1.3
Version de QScintilla2
2.10.8
Compilé avec PROJ
6.3.2
Fonctionne avec PROJ
Rel. 6.3.2, May 1st, 2020
Version de l'OS
Windows 10 (10.0)
Extensions Python actives
plugin_reloader
````

**Additional context**

Issue seems to be the ````envfile = list(path_split[:-4])```` in function ````setupenv```` ( below) of file```` python/qgis/__init__.py````. Would be nice not to break people's environnements like that, as it is possible to import from qgis without having run the .bat files to init QGIS thus not having the las 4 environment path being those of QGIS.

````python
def setupenv():
    """
    Set the environment for Windows based on the .vars files from the
    OSGeo4W package format.
    """
    # If the prefix path is already set the we don't do any more path setup.
    if os.getenv('QGIS_PREFIX_PATH'):
        return

    # Setup the paths based on the .vars file.
    from pathlib import PurePath

    path_split = PurePath(os.path.dirname(os.path.realpath(__file__))).parts

    try:
        appname = os.environ['QGIS_ENVNAME']
    except KeyError:
        appname = path_split[-3]

    envfile = list(path_split[:-4])
    envfile.append("bin")
    envfile.append("{0}-bin.env".format(appname))
    envfile = os.path.join(*envfile)

    if not os.path.exists(envfile):
        return

    with open(envfile) as f:
        for line in f:
            linedata = line.split("=")
            name = linedata[0]
            data = linedata[1]
            os.environ[name] = data
````

Tagging @wonder-sk (autor of said file)

Thank you very much for any advice here

**Comment by roya0045** [comment]
That's normal and wanted. Don't import from this outside of qgis, install things in the osgeo environment.

**Comment by roya0045** [comment]
Ref https://github.com/qgis/QGIS/issues/40924

**Comment by vmora** [comment]
> Don't import from this outside of qgis.

@roya0045 unit testing pieces of a plugin or making a standalone application are legid use-cases IMHO

@simolv I just noticed that defining the QGIS_PREFIX_PATH environment variable will solve the problem. Sorry I did not see that when we discussed the issue.

**Comment by roya0045** [comment]
@vmora expecting qgis to use any random installed python environment other than the one installed by qgis (either in osgeo or in qgis) doesn't make too much sense. Testing anything should be done in the environment where is it used and not outside of it.

**Comment by vmora** [comment]
@roya0045 the o4w_env.bat and py3_env.bat were run prior to the test, so the environment, althought incomplete, doesn't exactly deserve the random qualifier ;o)

**Comment by roya0045** [comment]
If the issues comes with trying to interact with something outside, it's excepted to not work due to dependencies issue. To have a good and replicable environment that will be stable for qgis users, you should use the environment that will be created and used by the app. ;)

**Comment by saberraz** [comment]
@vmora in your case using MDAL (https://github.com/lutraconsulting/MDAL) will resolve your problem :) :)

**Comment by wonder-sk** [comment]
Sounds like setting QGIS_PREFIX_PATH is the way to go as @vmora says.

I am not familiar with that setupenv() function... the copyright header (maybe confusingly) only states who created the file, not all the contributors in the years after - best to use git blame :-)
