### ISSUE TITLE
QGIS crashed while entering data

### ISSUE THREAD

**Issue by bertramrabe** [qgis/QGIS#41034]
**Describe the bug**

While entering data (new points in a point-layer) qgis crashes (whole system freezes), and I can nothing do but force the system shutdown. It happened twice within one hour. 

Here some more infos: It happened within a QGIS-Project with about 100 Layers. When I enter new points in a point-Layer (number of data in this Layer about 100) in this big project, the system reacts rather slowly. And yesterday it crashed twice. When I do the same in another project with only 5 layers (entering new points in the same Layer as before), the systems reacts quite quicker, and I could not reproduce the problem. My computer has a RAM of 6 GB. Nevertheless it would be nice, if the system would be stable even in a QGIS-project with 100 Layers.
**How to Reproduce**

4. See error -->

**QGIS and OS versions**
QGIS 3.10.13-A Coruna, OS Ubuntu 20.04

**Additional context**

**Comment by gioman** [comment]
@bertramrabe please try a new QGIS profile, no 3rd party plugins installed. If the problem persist attach the problematic data.

**Comment by roya0045** [comment]
More info needed regarding the data source and your relation to that source.

**Comment by bertramrabe** [comment]
I published more infos above about the problems. Nearly all data are local gis-shapefiles. And also a google layer with aerial view and also a layer with opentopomap. But it seems to me, the crash is caused only in projects with very many layers (100).

**Comment by gioman** [comment]
> But it seems to me, the crash is caused only in projects with very many layers (100).

@bertramrabe have you tried on a new QGIS profile?

**Comment by bertramrabe** [comment]
How do I create a new QGIS profile? You do not mean a new project?

**Comment by SrNetoChan** [comment]
Just create a new profile and replicate what you have done that cases the crash.

To create a new, clean, profile go to Settings > User Profiles > New

**Comment by bertramrabe** [comment]
I created a new profile now (I never did this before), und I tried in the same project (100 layers) to enter new points in the same point-layer. Maybe the system reacts a little bit faster, but not much (it takes about 4 seconds to fill in just one new point.).

How can I tell the system, that it uses as default the new created profile, when I start QGIS?

**Comment by gioman** [comment]
> ), und I tried in the same project (100 layers) to enter new points in the same point-layer

@bertramrabe it crashed?

**Comment by bertramrabe** [comment]
No, it did not crash. I cannot reproduce the problem (neither with the old profile nor with the new). The crash happened on Friday twice within 1 hour work filling in points in this layer. 
Is it normal, that it takes several seconds, when you enter just one point to a point-layer, within a project of 100 Layers (but only 3 layers are active)?

**Comment by gioman** [comment]
> No, it did not crash. I cannot reproduce the problem (neither with the old profile nor with the new). The crash happened on Friday twice within 1 hour work filling in points in this layer

@bertramrabe continue work with the new profile, do not install 3rd party plugins, and reopen if QGIS crash again (doing the same operation subject of this ticket)



> Is it normal, that it takes several seconds, when you enter just one point to a point-layer, within a project of 100 Layers (but only 3 layers are active)?

you miss to give important infos:

what datatype is?

did you tried the same layer in a new empty project?

**Comment by bertramrabe** [comment]
as I told above: yes I tried the same layer in a new empty project (only with google aerial view and also a layer with opentopomap as map-background), and all ran very quickly. 
The project with 100 layers consists of layers of ESRI-Shapefiles. And google aerial view and a layer with opentopomap as map-background.
My questions are:
1. Is it normal, that it takes several seconds, when you enter just one point to a point-layer, within a project of 100 Layers (but only 3 layers are active=visible)
2. How can I tell the system, that it uses as default the new created profile, when I start QGIS?

**Comment by roya0045** [comment]
Are the files on your computer or a remote server?

**Comment by bertramrabe** [comment]
the files are on my computer.

**Comment by gioman** [comment]
>     1. Is it normal, that it takes several seconds, when you enter just one point to a point-layer, within a project of 100 Layers (but only 3 layers are active=visible)

@bertramrabe there are a number of reasons why a layer could become slow to edit in the context of a project (i.e. relations, joins, expressions used for defaults/constraints, etc.), without the project is hard to say. If you can please attach it here.

**Comment by bertramrabe** [comment]
@gioman: there are no relations, joins etc. in this project. I am not sure, if it has something to do with this layer. If so: I attach the shapefile to this post.
I can not reproduce that the system crashes. But I can reproduce, that this point-layer takes a second more just when I fill in a new point.
[points bertram.zip](https://github.com/qgis/QGIS/files/5903264/points.bertram.zip)
Since the last update of QGIS (3.10.14) it became a little bit better.

**Comment by gioman** [comment]
> I can not reproduce that the system crashes. But I can reproduce, that this point-layer takes a second more just when I fill in a new point.
> [points bertram.zip](https://github.com/qgis/QGIS/files/5903264/points.bertram.zip)

@bertramrabe it is instantaneous here, on both Windows and Linux. I still believe that what you see is probably related to your project, without it (or at least a version of it that shows the symptoms you describe) is hard to say what is wrong. And ultimately if this issue is not replicable in a consistent way this issue will be closed.

**Comment by bertramrabe** [comment]
@gioman: Would it help for you, when I would post the project-qgs - without the ca. 100 layers in it?

**Comment by gioman** [comment]
> Would it help for you, when I would post the project-qgs - without the ca. 100 layers in it?

@bertramrabe do you see the slow down in a project copy where those ~100 layers are missing?

**Comment by bertramrabe** [comment]
@gioman when I remove most of the 100 Layer, and save the same project (qgs) only with 3 Layers, then there is no delay while entering data in the layer I posted above

**Comment by gioman** [comment]
> @gioman when I remove most of the 100 Layer, and save the same project (qgs) only with 3 Layers, then there is no delay while entering data in the layer I posted above

@bertramrabe then is needed to have a look at the full project.

**Comment by roya0045** [comment]
There are other such issues with multiple layers and delays.

**Comment by bertramrabe** [comment]
Would it be enough to post the project-qgs? Or do you need all 100 layers? (if you need all 100 layers, it would not be possible to post, and I would close this issue.

**Comment by gioman** [comment]
> There are other such issues with multiple layers and delays.

@roya0045 is this a question or a statement? if is the latter can you point me to the tickets/discussions?

**Comment by roya0045** [comment]
@roya0045 I'm fairly certain there was another recent active issue where having too many layers caused slow down with some operations. I may be misremembering.

**Comment by gioman** [comment]
> Would it be enough to post the project-qgs? Or do you need all 100 layers? (if you need all 100 layers, it would not be possible to post

@bertramrabe the point is that if is not possible to replicate an issue there is not much that can be done (most of the times). I tried also with a large project here, and can't see any delay editing the layer you posted.

**Comment by bertramrabe** [comment]
ok
