### ISSUE TITLE
3.18 icon updates

### ISSUE THREAD

**Issue by nyalldawson** [qgis/QGIS#41040]
Some newly introduced icons need rework prior to release:

- ~~Point cloud layer icon: wrong style compared with other layer types (color vs monochrome). Also needs a variant in the data source manager monochrome+dark blueish style for use in data source manager~~
- ~~Point cloud layer elevation properties: Reuse of poorly matching existing icon~~
- ~~SAP/hana provider icons: need reworking to ideally remove the text strings, which are unreadable at certain sizes and bad for localisation~~
- need dedicated icons for fly/terrain 3d navigation modes
- point cloud "extent only" renderer needs an icon
- point cloud 3d "single color" renderer needs an icon
- merged features renderer: needs a proper icon instead of using the inverted polygon icon

**Comment by stefanuhrig** [comment]
I'll take care of finding an alternative for the HANA icons.

**Comment by stefanuhrig** [comment]
I've opened #41102 with new icons for SAP HANA.

**Comment by SrNetoChan** [comment]
@nyalldawson can you assign me to this one, please.

**Comment by gioman** [comment]
> @nyalldawson can you assign me to this one, please.

done.

**Comment by nirvn** [comment]
Point one addressed here: https://github.com/qgis/QGIS/pull/41394

**Comment by SrNetoChan** [comment]
@nyalldawson said:
> * need dedicated icons for fly/terrain 3d navigation modes

Is this for the settings combobox? I don't see any icons on the toolbar (which would be welcome, I guess

**Comment by nyalldawson** [comment]
@SrNetoChan ignore those -- the buttons didn't get added yet, it will need to wait till 3.20

**Comment by SrNetoChan** [comment]
All other missing icons are now ready on #41490
