### ISSUE TITLE
WHEN IMPORTING CSV QGIS IT IS LOCKED

### ISSUE THREAD

**Issue by JAVIERSIG** [qgis/QGIS#41044]
Hello; I have this persistent problem anyway.
It is when trying to import a delimited file, with the add delimited text layer tool.
Qgis always crashes.
I have deleted and reinstalled everything about Qgis on multiple occasions, but it keeps happening.
I don't know why or how to solve the problem.

If you could help me I would be very grateful.

I send the crash report

Thanks

Crash ID: aad9a4f139019da75c13684d32bf9fb04faa4c69

Stack Trace

QBitArray::QBitArray :
QgsCalloutAbstractMetadata::name qgscalloutsregistry.h:62
QgsRuleBasedRenderer::convertFromRenderer qgsrulebasedrenderer.cpp:1304
meth_QgsRuleBasedRenderer_convertFromRenderer sip_corepart2.cpp:66034
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QMetaObject::activate :
QgisInterface::currentLayerChanged moc_qgisinterface.cpp:810
QMetaObject::activate :
QgisApp::activeLayerChanged moc_qgisapp.cpp:2766
QgisApp::onActiveLayerChanged qgisapp.cpp:698
QMetaObject::activate :
QgsLayerTreeView::currentLayerChanged moc_qgslayertreeview.cpp:229
QgsLayerTreeView::onCurrentChanged qgslayertreeview.cpp:294
QMetaObject::activate :
QItemSelectionModel::setCurrentIndex :
QAbstractItemView::setCurrentIndex :
QgisApp::autoSelectAddedLayer qgisapp.cpp:4910
QtPrivate::QSlotObject) __ptr64,QtPrivate::List const & __ptr64>,void>::impl qobjectdefs_impl.h:403
QMetaObject::activate :
QgsLayerTreeRegistryBridge::addedLayersToLayerTree moc_qgslayertreeregistrybridge.cpp:165
QgsLayerTreeRegistryBridge::layersAdded qgslayertreeregistrybridge.cpp:77
QMetaObject::activate :
QgsProject::legendLayersAdded moc_qgsproject.cpp:1210
QgsProject::addMapLayers qgsproject.cpp:3354
QgsProject::addMapLayer qgsproject.cpp:3384
meth_QgsProject_addMapLayer sip_corepart8.cpp:74097
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1637
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.16.2-Hannover
QGIS code revision: f1660f9da5
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
@JAVIERSIG try with a new QGIS profile, no 3rd party plugins installed. If the problem persist attach the problematic data and describe the exact steps to follow that lead to the crash.

**Comment by JAVIERSIG** [comment]
Thanks for the reply.
It is not a third-party plugin; it is from the tool itself incorporated in Qgis; send image.
I just choose a csv file, mark the field delimitation, and import. This is where it gets stuck.
I don't know if this information is enough.
Thanks a lot

![Captura2](https://user-images.githubusercontent.com/17898868/104810665-7d424b00-57f6-11eb-81e0-85a6457b09e4.JPG)

**Comment by gioman** [comment]
> It is not a third-party plugin;

@JAVIERSIG I have not said that is a third party plugin. What I said is that you must test with a new QGIS profile (settings > user profiles  > new profile) and that in the new profile you must not install any 3rd party plugin before testing.

**Comment by gioman** [comment]
> This is where it gets stuck.

@JAVIERSIG if after the new profile test the problem persist please attach/link the problematic data.

**Comment by JAVIERSIG** [comment]
Hello; uy ,,, yes yes, right. I have created a new profile and successfully imported a csv; but why does it happen like this ?; Does it mean that in this new profile I could not create a pluggin or install from a third party?

Thanks a lot

**Comment by gioman** [comment]
> Hello; uy ,,, yes yes, right. I have created a new profile and successfully imported a csv; but why does it happen like this ?; Does it mean that in this new profile I could not create a pluggin or install from a third party?

@JAVIERSIG it could mean that a 3rd party plugin you have installed is interacting in a bad way with your QGIS installation, but QGIS is not responsible for such plugins. There maybe other causes. If you find that the cause is not a 3rd party plugin then please reopen this ticket.
