### ISSUE TITLE
QGIS WMS Server: different image extent returned for WMS 1.1.1 and WMS 1.3.0 for EPSG:4326

### ISSUE THREAD

**Issue by rbuffat** [qgis/QGIS#41051]
First, I'm sorry I can't state much information about the WMS server, as I do not operate it.

I suspect that [this WMS server](https://geo.so.ch/api/wms?SERVICE=WMS&REQUEST=GetCapabilities&version=1.3.0) is using QGIS, as it contains the qgs XML namespace `xmlns:qgs="http://www.qgis.org/wms"`.

With WMS 1.3.0 and EPSG:4326, respectively CRS:84 the same image is returned:
https://geo.so.ch/api/wms?LAYERS=ch.so.agi.orthofoto_2016_rgb&STYLES=&FORMAT=image/jpeg&CRS=EPSG:4326&WIDTH=1024&HEIGHT=1024&BBOX=47.21956811231548,7.470703125,47.23448963529918,7.49267578125&VERSION=1.3.0&SERVICE=WMS&REQUEST=GetMap

https://geo.so.ch/api/wms?LAYERS=ch.so.agi.orthofoto_2016_rgb&STYLES=&FORMAT=image/jpeg&CRS=CRS:84&WIDTH=1024&HEIGHT=1024&BBOX=7.470703125,47.21956811231548,7.49267578125,47.23448963529918&VERSION=1.3.0&SERVICE=WMS&REQUEST=GetMap

However, when WMS 1.1.1 is used, the latitude direction of the image extent is different:
https://geo.so.ch/api/wms?LAYERS=ch.so.agi.orthofoto_2016_rgb&STYLES=&FORMAT=image/jpeg&SRS=EPSG:4326&WIDTH=1024&HEIGHT=1024&BBOX=7.470703125,47.21956811231548,7.49267578125,47.23448963529918&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap

I tried to find a related issue in the issue tracker, but I couldn't find any. But it could also just be that I searched for the wrong keywords. As said before, I do not operate the server, but I could try to contact the operators to inquiry more information if this is helpful.

**Comment by gioman** [comment]
@rbuffat 1.1.1 in QGIS server does not seems implemented https://docs.qgis.org/3.16/en/docs/server_manual/services.html#web-map-service-wms if you try 1.1.0 it works as expected (the same image as 1.3.0 is returned).

**Comment by rbuffat** [comment]
@gioman Thanks for the link, I should have checked in advance. 

```
Returns GetCatabilities for WMS 1.3.0:  https://geo.so.ch/api/wms?SERVICE=WMS&REQUEST=GetCapabilities&version=1.3.0
Returns GetCatabilities for WMS 1.1.1: https://geo.so.ch/api/wms?SERVICE=WMS&REQUEST=GetCapabilities&version=1.1.1
Returns GetCatabilities for WMS 1.3.0: https://geo.so.ch/api/wms?SERVICE=WMS&REQUEST=GetCapabilities&version=1.1.0
Returns GetCatabilities for WMS 1.3.0: https://geo.so.ch/api/wms?SERVICE=WMS&REQUEST=GetCapabilities&version=1.0.0
```

The [WMS 1.3.0 specification](https://www.ogc.org/standards/wms#downloads) defines the following procedure for version number negotiation:

> 6.2.4    Version number negotiation
> A  WMS  client  may  negotiate  with  a  server  to  determine  a  mutually  agreeable  protocol  version.  Negotiation  is  performed using the GetCapabilities operation (described in 7.2) according to the following rules. All  service  metadata  shall  include  a  protocol  version  number  and  shall  comply  with  the  XML  DTD  or  Schema  defined for that version. In response to a GetCapabilities request (for which the VERSION parameter is optional) that does not specify a version number, the server shall respond with the highest version it supports. In response to  a  GetCapabilities  request  containing  a  version  number  that  the  server  implements,  the  server  shall  send  that  version. If the server does not support the requested version, the server shall respond with output that conforms to a version it does support, as determined by the following rules: 
> * If a version unknown to the server and higher than the lowest supported version is requested, the server shall send the highest version it supports that is less than the requested version. 
> * If a version lower than any of those known to the server is requested, then the server shall send the lowest version it supports. 
> * If  the  client  does  not  support  the  version  sent  by  the  server,  it  may  either  cease  communicating  with  the  server or send a new request with a different version number that the client does support. 

I suppose this server does not implement the WMS 1.3.0 specification in this regard. 


> @rbuffat 1.1.1 in QGIS server does not seems implemented https://docs.qgis.org/3.16/en/docs/server_manual/services.html#web-map-service-wms if you try 1.1.0 it works as expected (the same image as 1.3.0 is returned).

With WMS 1.3.0 the BBOX parameter uses the axis ordering of the CRS (for EPSG:4326 this is latitude, longitude). Older versions of the standard use the traditional GIS x,y order. See also Section "6.7.4    Bounding    boxes" in the WMS 1.3.0 specification. The [image for WMS 1.1.0](https://geo.so.ch/api/wms?LAYERS=ch.so.agi.orthofoto_2016_rgb&STYLES=&FORMAT=image/jpeg&SRS=EPSG:4326&WIDTH=1024&HEIGHT=1024&BBOX=7.470703125,47.21956811231548,7.49267578125,47.23448963529918&VERSION=1.1.0&SERVICE=WMS&REQUEST=GetMap) is just an empty image. Probably because the change in the bbox coordinate order is not taken into account (Maybe the server just defaults to WMS 1.3.0, but then it is strange that the SRS instead of CRS parameter is accepted).

As I said, I just infer that this is a QGIS server from the namespace of the GetCapabilitites request. Maybe it is not a QGIS server at all.

**Comment by gioman** [comment]
> As I said, I just infer that this is a QGIS server from the namespace of the GetCapabilitites request. Maybe it is not a QGIS server at all.

@rbuffat can you try on a local installation of QGIS Server?

**Comment by rbuffat** [comment]
@gioman I could reproduce the WMS version number negotiation issue. For WMS 1.1.0 or WMS 1.0.0 it seems to just default to WMS 1.3.0. 

I could not yet reproduce the issue that the latitude axis for WMS 1.1.1 is not the same as for WMS 1.3.0 with a test dataset. However, I found another WMS server with similar behavior, except that also the axis ordering of WMS 1.3.0 is ignored for EPSG:4326, which renders EPSG:4326 unusable for this server : 


> WMS 1.3.0 query with correct axis ordering:
> https://www.ogd.stadt-zuerich.ch/wms/geoportal/Orthofoto_2013_Stadt_Zuerich___Fruehling?FORMAT=image/jpeg&VERSION=1.3.0&SERVICE=WMS&REQUEST=GetMap&LAYERS=OP_2013_STZH.tif&STYLES=&CRS=EPSG:4326&WIDTH=256&HEIGHT=256&BBOX=47.36859434521338,8.525390625,47.3834738721015,8.54736328125
> 
> WMS 1.3.0 query with x,y axis ordering:
> https://www.ogd.stadt-zuerich.ch/wms/geoportal/Orthofoto_2013_Stadt_Zuerich___Fruehling?FORMAT=image/jpeg&VERSION=1.3.0&SERVICE=WMS&REQUEST=GetMap&LAYERS=OP_2013_STZH.tif&STYLES=&CRS=EPSG:4326&WIDTH=256&HEIGHT=256&BBOX=8.525390625,47.36859434521338,8.54736328125,47.3834738721015
> 
> WMS 1.1.1 query with x,y axis ordering:
> https://www.ogd.stadt-zuerich.ch/wms/geoportal/Orthofoto_2013_Stadt_Zuerich___Fruehling?FORMAT=image/jpeg&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&LAYERS=OP_2013_STZH.tif&STYLES=&SRS=EPSG:4326&WIDTH=256&HEIGHT=256&BBOX=8.525390625,47.36859434521338,8.54736328125,47.3834738721015

**Comment by gioman** [comment]
Maybe a QGIS server developer wants to chime in, @elpaso maybe?

**Comment by pblottiere** [comment]
Hello @gioman and @rbuffat,

I don't have time right now but I can take a look tomorrow. In the meantime I'll do some testing.

**Comment by elpaso** [comment]
@pblottiere see also:  https://github.com/qgis/QGIS/pull/41242

**Comment by pblottiere** [comment]
About the version number negotiation, I noticed several issues. 

1. a WMS 1.3.0 `GetCapabiltiies` document is returned even if the version is lower than 1.1.1 (as mentionned by @rbuffat in https://github.com/qgis/QGIS/issues/41051#issuecomment-762466547, it should not)
2. the `GetCapabilities` document returned in case of `VERSION=1.1.1` is not valid. Indeed, `OnlineResource` definitions are still indicating 1.3.0:

``` xml
<OnlineResource xlink:href="http:SERVICE=WMS&amp;VERSION=1.3.0&amp;REQUEST=GetCapabilities?" xmlns:xlink="http://www.w3.org/1999/xlink" xlink:type="simple"/>
```

I'm working on a PR to fix that. I'll take a look to axis ordering after.

**Comment by pblottiere** [comment]
> About the version number negotiation, I noticed several issues.

> - a WMS 1.3.0 GetCapabiltiies document is returned even if the version is lower than 1.1.1 (as mentionned by @rbuffat in #41051 (comment), it should not)

I made some refactoring in the WMS service to properly deduce and spread the version number for all requests (https://github.com/qgis/QGIS/pull/41376) so it should be fixed now.

I'm going to take a look on the axis inversion now.

**Comment by pblottiere** [comment]
Hello. I finally took some time to investigate the remaining issues mentioned here.


> Maybe the server just defaults to WMS 1.3.0, but then it is strange that the SRS instead of CRS parameter is accepted

This is normal and expected as stated in the documentation: https://docs.qgis.org/3.16/en/docs/server_manual/services.html#srs-crs

> I could not yet reproduce the issue that the latitude axis for WMS 1.1.1 is not the same as for WMS 1.3.0 with a test dataset. However, I found another WMS server with similar behavior, except that also the axis ordering of WMS 1.3.0 is ignored for EPSG:4326, which renders EPSG:4326 unusable for this server :

> WMS 1.3.0 query with correct axis ordering:
> https://www.ogd.stadt-zuerich.ch/wms/geoportal/Orthofoto_2013_Stadt_Zuerich___Fruehling?FORMAT=image/jpeg&VERSION=1.3.0&SERVICE=WMS&REQUEST=GetMap&LAYERS=OP_2013_STZH.tif&STYLES=&CRS=EPSG:4326&WIDTH=256&HEIGHT=256&BBOX=47.36859434521338,8.525390625,47.3834738721015,8.54736328125

=> it should work but it does not

> WMS 1.3.0 query with x,y axis ordering:
> https://www.ogd.stadt-zuerich.ch/wms/geoportal/Orthofoto_2013_Stadt_Zuerich___Fruehling?FORMAT=image/jpeg&VERSION=1.3.0&SERVICE=WMS&REQUEST=GetMap&LAYERS=OP_2013_STZH.tif&STYLES=&CRS=EPSG:4326&WIDTH=256&HEIGHT=256&BBOX=8.525390625,47.36859434521338,8.54736328125,47.3834738721015

=> it works but it should not

> WMS 1.1.1 query with x,y axis ordering:
> https://www.ogd.stadt-zuerich.ch/wms/geoportal/Orthofoto_2013_Stadt_Zuerich___Fruehling?FORMAT=image/jpeg&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&LAYERS=OP_2013_STZH.tif&STYLES=&SRS=EPSG:4326&WIDTH=256&HEIGHT=256&BBOX=8.525390625,47.36859434521338,8.54736328125,47.3834738721015

=> it works as expected

I did some tests locally and the WMS 1.3.0 works fine but not the WMS 1.1.1:

![issue](https://user-images.githubusercontent.com/9266424/119966215-62a18f00-bfab-11eb-905e-7b93504fe3fa.png)

So it's basically the reverse situation of what we're seeing on the `https://www.ogd.stadt-zuerich.ch/wms/geoportal/Orthofoto_2013_Stadt_Zuerich___Fruehling` server. So I'd say that:

- `https://www.ogd.stadt-zuerich.ch/wms/geoportal/Orthofoto_2013_Stadt_Zuerich___Fruehling` is out of date
-  we have an issue with WMS 1.1.1 axis in master

And while investigating, I noticed some inconsistencies in the documentation about axis ordering and WMS 1.1.1 vs 1.3.0. I'd like to fix that before closing this issue.

**Comment by pblottiere** [comment]
Nope, I had made a mistake in my WMS 1.1.1 request, everything works fine on master! 

However I still have to update the documentation to fix inconsistencies.

**Comment by pblottiere** [comment]
The PR updating the documentation has been merged.

Thanks for raising the issue @rbuffat :+1:
