### ISSUE TITLE
QGIS 3.10.13-A - Attribute Table editing with Field Calculator locks up Windows 10

### ISSUE THREAD

**Issue by cjackel29** [qgis/QGIS#41057]
I attempt to Add/Subtract fields or Update fields in Field Calculator and QGIS locks up.

**Comment by gioman** [comment]
@cjackel29 

this are the infos that you must add here



**Describe the bug**


**How to Reproduce**



1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error -->

**QGIS and OS versions**



**Additional context**

**Comment by gioman** [comment]
@cjackel29 but before everything: try with a new QGIS profile (do not install any 3rd party plugin in the new QGIS profile).

**Comment by roya0045** [comment]
If the layer has 3 million features that's normal. Though I think the eval and redraw might be combined somehow to prevent reloading the table twice.
