### ISSUE TITLE
Adding an XYZ tile using PyQGIS in PyCharm

### ISSUE THREAD

**Issue by LiamHems** [qgis/QGIS#41058]
I am trying to add a XYZ Open Street Map tile into my QGIS project, using PyQGIS. I am currently trying to use PyCharm to start with, to see if my script is running correctly. I have looked through various other questions but none have worked successfully so far. I have also tried to add the link with %7Bz%7D/%7Bx%7D/%7By%7D instead of {z}/{x}/{y} but still no luck. The code works perfectly inside the QGIS Python Console but does not seem to run in PyCharm. My code is:

`urlWithParams = 'type=xyz&url=https://tile.openstreetmap.org/{z}/{x}/{y}.png&zmax=19&zmin=0&crs=EPSG3857'`
`rlayer2 = QgsRasterLayer(urlWithParams, 'OpenStreetMap', 'wms')`
`QgsProject.instance().addMapLayer(rlayer2)`

But when I run the script, an error occurs as my other raster and vector layer is added, but the OpenStreetMap layer becomes invalid and is not added to my exported map, even though it tells me in the script that rlayer2.isValid (as can be seen below).

`OpenStreetMap_9b914e8c_7637_411a_beea_397b7f36f2c8': <QgsRasterLayer: 'OpenStreetMap' (Invalid)`

I would like to add a base map to my exported map but when I try to export a map currently, it only exports a .png of this, with no base map but the other data added – see attached image.

A link to download my data - https://we.tl/t-HGNzIFq7e5

[CATAC2021bfyw Event](https://user-images.githubusercontent.com/77631355/104937156-59713780-59a5-11eb-8922-a66ce55c24d3.png)

Kindest Regards, Liam

**Comment by gioman** [comment]
@misto ask in the users or developers mailing list.
