### ISSUE TITLE
Optional QgsProcessingParameterExpression defaults to field if input has one field

### ISSUE THREAD

**Issue by uclaros** [qgis/QGIS#41063]
**Describe the bug**

A processing algorithm that uses an optional `QgsProcessingParameterExpression` defaults its value to input field if the input layer has one field only, instead of being left blank like when there are more fields or no fields.

**How to Reproduce**
Open a point layer that has a single field and load the c++ points to path algorithm. Both order expression and group expression defaults to the single field instead of being blank.

**QGIS and OS versions**
Master on debian testing

**Comment by nyalldawson** [comment]
Possibly a matter of just setting QgsFieldExpressionWidget::setAllowEmptyFieldName(true) in QgsProcessingExpressionWidgetWrapper::createWidget() for optional expressions
