### ISSUE TITLE
Allow layers to be add as Favorite in Browser

### ISSUE THREAD

**Issue by jfbourdon** [qgis/QGIS#41060]
**Feature description.**
Allow layers to be add as Favorite in Browser the same way it's currently done with directories. The layer could be a file, a WMS or a database connection, any file that is viewed as a layer by QGIS.

![addAsFavorite](https://user-images.githubusercontent.com/32580398/104943638-0cc93480-5984-11eb-98c4-19b4d6918588.png)

**Additional context**
I often have the need to import some base layer to rapidly check something like an continus aerial photography layer as a WMS, a reference grid or a global corse DEM. These layers being in different directories, it needs many clicks to reach them. Copying them all in the same place is either not possible (like web services) or advisable (risk of outdated data).

I must say that always using the same base project template with everything loaded is an alternative but I find it a bit more cumbersome.

**Comment by Gustry** [comment]
Just as a side note, you can look to the "Layers menu from project" plugin. Quite useful as a workaround.

**Comment by alexbruy** [comment]
Duplicates #18825.
