### ISSUE TITLE
QGIS crash exporting canvas as image

### ISSUE THREAD

**Issue by GAM386** [qgis/QGIS#41077]
## User Feedback

Exporting a google stellite map to a large georeferenced .png.

## Report Details

**Crash ID**: [cdf76bee9068992244bad10f7bc062d611a283bc](https://github.com/qgis/QGIS/search?q=cdf76bee9068992244bad10f7bc062d611a283bc&type=Issues)

**Stack Trace**
<pre>
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QRasterPaintEngine::penChanged :
QPolygonF::united :
QRasterPaintEngine::drawImage :
QRasterPaintEngine::drawImage :
QgsRasterDrawer::drawImage qgsrasterdrawer.cpp:174
QgsRasterDrawer::draw qgsrasterdrawer.cpp:105
QgsRasterLayerRenderer::render qgsrasterlayerrenderer.cpp:274
QgsMapRendererCustomPainterJob::doRender qgsmaprenderercustompainterjob.cpp:312
QgsMapRendererCustomPainterJob::renderPrepared qgsmaprenderercustompainterjob.cpp:233
QgsMapRendererTask::run qgsmaprenderertask.cpp:240
QgsTask::start qgstaskmanager.cpp:78
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.13-A Coru�a
QGIS code revision: 311f3bbade
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
@GAM386 please add the requested info:



**Describe the bug**


**How to Reproduce**



1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error -->

**QGIS and OS versions**



**Additional context**





Also try with a new QGIS profile, no 3rd party plugins installed.

**Comment by GAM386** [comment]
1) Open the attached

2) click through Project…export to image

3) extent of canvas, 2400dpi, georeferencing

4) save

5) wait a few minutes.

6) error window.

 

Thank you.

**Comment by gioman** [comment]
> 1) Open the attached

@GAM386 there are no attached datasources/files here.

**Comment by gioman** [comment]
> 3) extent of canvas

@GAM386 better if you also attach your project

**Comment by roya0045** [comment]
And don't infringe the code of conduct of google product, and not use an outrageous dpi.

**Comment by GAM386** [comment]
Understood, but that would defeat the purpose.  Outrageous is in the eye of the beholder.  :-)

 

If the info I’ve submitted is not sufficient, please disregard/delete my report.

 

It worked before updating to 3.10.13, so I’m going to try a downdate.

 

Thank you.

**Comment by gioman** [comment]
>  If you can attach a project and data we can use to quickly reproduce the issue it would be very helpful.

@GAM386 or at least tell us what is the layer that you are trying to export as image (maybe is from the QuickMapServices plugin?) and the extension you are trying to export.

**Comment by roya0045** [comment]
@gioman I think the crash is just from exporting any projection to image with said dpi and any raster or web service.

**Comment by gioman** [comment]
> @gioman I think the crash is just from exporting any projection to image with said dpi and any raster or web service.

@roya0045 I tried: at that resolution I can export to PNG without crashes... but I didn't tried with a large geographic extension (of course)... using a quite local geographic extension the output image has already a size in the tens of thousands of pixels of WxH... at a country level that would be an absurd size... maybe we need to had some upper limit in that dialog...

**Comment by GAM386** [comment]
Thanks – attached is a version of what I’m working with.  The objective is to export a georeferenced image (or sub-images…) of the area covered for use in mapping very fine detail on an orienteering map at 1:10,000 scale.

 

I did not have any better luck with the full map on 13.10.12/13/14/16, but I did just get about 1/3 of the area to export properly on 13.10.14.

 

I was able to get the whole image at 2400dpi a week or so ago, but I did so under a different projection that I’ve not yet been able to identify for the purposes of doing a ‘transform from,’ hence my effort to replicate the full area image export.

**Comment by gioman** [comment]
> Thanks – attached is a version of what I’m working with.

@GAM386 if you are answering this thread via email we are not getting the attachment. You must use the GitHub web site https://github.com/qgis/QGIS/issues/41077 and attach the necessary files (as zip) there.

**Comment by roya0045** [comment]
@GAM386 email attachments are not supported on github, go on the web page and upload the files in the comments, not via email.

**Comment by GAM386** [comment]
Here you go. Thank you.
[USAFA_JacksValleyGeorefImage003.zip](https://github.com/qgis/QGIS/files/5836627/USAFA_JacksValleyGeorefImage003.zip)

**Comment by gioman** [comment]
> Here you go. Thank you.
> [USAFA_JacksValleyGeorefImage003.zip](https://github.com/qgis/QGIS/files/5836627/USAFA_JacksValleyGeorefImage003.zip)

It saved with no crashes here (QGIS master, Ubuntu 20.04).

**Comment by GAM386** [comment]
@Giovanni

 

The whole map?  Great!   

 

Could you please tell me what dpi did you use, what was the size of the output .png file, and what version of GQIS are your running?  Sorry, I don’t know what “master” refers to.

 

The full area file I made a week or so ago is 275MB.  Oddly, the subsection I was able to do 10mins ago came out to 521MB, so it doesn’t really follow that smaller is better…

 

I have an Ubuntu laptop with 18.04 running.  I’ll update it and load QGIS to see if that workaround can handle the full image. 

 

Thank you.

**Comment by gioman** [comment]
> The whole map? Great!

@GAM386 the extent that shows when you open the attached project.

**Comment by gioman** [comment]
>  Could you please tell me what dpi did you use, what was the size of the output .png file, and what version of GQIS are your running?

@GAM386 2400dpi, 750mb, "master" is the development version of QGIS.

**Comment by gioman** [comment]
> It saved with no crashes here (QGIS master, Ubuntu 20.04).

@GAM386 no crashes also on Windows (QGIS 3.16).

**Comment by GAM386** [comment]
Thank you.  It crashes at full size on all the QGIS versions I’ve tried.  Win 10 Home, i9-9900K, 64GB RAM.

 

I’ll try the Ubuntu route or just settle for subsections.

**Comment by gioman** [comment]
>  It crashes at full size

@GAM386 please define "fullsize". Are you trying to export the **whole** google satellite layer in your project? or just the extent that shows when opening the project? or a different extent (if this is the case please let us see the extent values)?

**Comment by DelazJ** [comment]
@GAM386 maybe try with a [clean profile](https://docs.qgis.org/3.16/en/docs/user_manual/introduction/qgis_configuration.html?highlight=profile#working-with-user-profiles)

**Comment by GAM386** [comment]
“Fullsize” = the extent that shows on the screen: 509500-514000 x 4318850-4321500 (UTM13N).

Thank you.

**Comment by gioman** [comment]
> “Fullsize” = the extent that shows on the screen: 509500-514000 x 4318850-4321500 (UTM13N).

@GAM386 ok thanks. So no crashes here with that. Please also try with a new QGIS profile.

**Comment by GAM386** [comment]
Worked perfectly, full size, 3000dpi in Ubuntu 20.04, QGIS 13.10.16.

 

The exported file is 1.2GB, so I’m probably better off dealing with subparts, anyway, but I’m pleased to have found a solution.

 

Thank you all very much for your help.

**Comment by GAM386** [comment]
Crashed under a new profile on my Win machine.

**Comment by gioman** [comment]
> Crashed under a new profile on my Win machine.

@GAM386 it could be a memory (lack of) issue. Anyway as @elpaso told before if this is the case QGIS should not crash.
