### ISSUE TITLE
Editing Model with bad reference crashes QGIS 

### ISSUE THREAD

**Issue by davidlgalt** [qgis/QGIS#41073]
Using 3.16.2, a model I had created crashed QGIS when I attempting to open the model for editing. Was able to edit, find the source of the problem, and fix it using 3.10.

**How to Reproduce**
In 3.10 I was able to see that one of the inputs that the Merge Vector Layers algorithm was using was empty. I removed the reference, saved and after that, I was able to edit the model in 3.16 again.

I'm not sure how the model got corrupted in the first place. Generally, if you change the handle of an algorithm in the designer it changes the references to it downstream. For some reason that did not happen in this case. In any case, the Model Designer should be able to work with models that have broken references.

Sadly, I have fixed my model so it would not be of much use here.

**Comment by gioman** [comment]
@davidlgalt without the broken model I'm not sure there is much we can do.

**Comment by davidlgalt** [comment]
I rescued the broken model. A script syncing my files between 2 computers had not run in the last week.

Here it is (crashy as ever):
https://www.dropbox.com/s/ctgeqhl28x7sdwc/Track_Changes.model3?dl=1

**Comment by gioman** [comment]
> I rescued the broken model. A script syncing my files between 2 computers had not run in the last week.

@davidlgalt " Cannot edit model: The model you are trying to run contains an algorithm that is not available: loci:Geocodio"


[Track_Changes.model3.zip](https://github.com/qgis/QGIS/files/5842053/Track_Changes.model3.zip)

**Comment by davidlgalt** [comment]
I replaced with a model that does not include that custom algorithm. It does still include a reference to a custom model (Tracking Add Columns), but I can't remove this as it is directly related to the issue, so I have included it, in the zip archive below.

https://www.dropbox.com/s/2shhu8yvyac4p5c/TrackChangesModel.zip?dl=1

**Comment by gioman** [comment]
> I replaced with a model that does not include that custom algorithm.

@davidlgalt on QGIS master on Ubuntu 20.04 the model can be edited and saved with no issues.

[TrackChangesModel.zip](https://github.com/qgis/QGIS/files/5845191/TrackChangesModel.zip)

**Comment by davidlgalt** [comment]
Hmmm. Maybe this is a Windows issue then. I just ran into the issue again today. I could open or edit a model because it was referring to another model that it said did not exist. I looked and the model that is said wasn't there appeared to in fact be there, and it appeared to have an identical name.  It through the same error in 3.16.2 and the latest master (3.17 code revision: 8a8d2a2c66).

Again, 3.10 allowed me to open the model and when I clicked on the name I discovered that there was a single trailing space after the name. I removed it and saved. Miraculously, it allowed me to open the model again in 3.16.

My issue is not so much that there's an error -- that was more than likely user error. My issue is that the new versions of QGIS prevent you from being able to open the model to discover and fix your error.

**Comment by gioman** [comment]
> Hmmm. Maybe this is a Windows issue then.

it seems to be a version related issue: on Windows I can edit your "track changes and update" model on master but not on 3.16. Whatever the fix was implemented it should be backported to 3.16 (if possible).

**Comment by gioman** [comment]
> it seems to be a version related issue: on Windows I can edit your "track changes and update" model on master but not on 3.16. Whatever the fix was implemented it should be backported to 3.16 (if possible).

@davidlgalt after all it seems also a platform issue; I was sure I could edit that model on Windows/master but now it crashes all the time.

**Comment by Pedro-Murteira** [comment]
@davidlgalt Hello, I'm not being able to reproduce a crash. Can you still reproduce it? (QGIS 3.22.5 and 3.24.1. on Windows 10)
