### ISSUE TITLE
Empty String '' is shown as NULL with a spatialite layer using OGR provider

### ISSUE THREAD

**Issue by Infiziert90** [qgis/QGIS#41076]
**Describe the bug**

In QGIS 3.16.2 empty string fields (value '') are shown as NULL and not an empty field like in 3.10.13  
![image](https://user-images.githubusercontent.com/22648449/105034879-6e5bd280-5a5a-11eb-92f0-5f31072bf971.png)

What it should look like
![image](https://user-images.githubusercontent.com/22648449/105035265-fe9a1780-5a5a-11eb-90e9-346515633ea5.png)

Image from the DB Browser for SQLite with BIL1 set too NULL to show the difference that the fields are truly empty strings and not NULL
![image](https://user-images.githubusercontent.com/22648449/105035031-acf18d00-5a5a-11eb-9e62-c4071488d6ae.png)

**How to Reproduce**

Have a string field with the value '' 

**QGIS and OS versions**
Tested with 3.10.13 and 
QGIS version
3.16.2-Hannover
QGIS code revision
f1660f9da5

**Comment by elpaso** [comment]
This is very provider-specific. Can you please add a test project and data?

**Comment by Infiziert90** [comment]
Here a small test db
in 3.16.2 it shows me NULL and in 3.10.13 the expected empty field

[altlastm_mgwl.zip](https://github.com/qgis/QGIS/files/5835908/altlastm_mgwl.zip)

**Comment by gioman** [comment]
@Infiziert90 QGIS master on Ubuntu 20.04

![Screenshot_20210119_130434](https://user-images.githubusercontent.com/1951107/105038176-e4f6d100-5a56-11eb-85bf-53a0a8bdebbe.png)

**Comment by DelazJ** [comment]
@Infiziert90 What about your representation for null value setting https://docs.qgis.org/3.10/en/docs/user_manual/introduction/qgis_configuration.html#data-sources-settings

**Comment by Infiziert90** [comment]
![image](https://user-images.githubusercontent.com/22648449/105039054-5edf8800-5a60-11eb-8839-399d009f6cf3.png)


QGIS version 3.16.2-Hannover on  Windows 10

**Comment by Infiziert90** [comment]
@DelazJ 
![image](https://user-images.githubusercontent.com/22648449/105039375-c72e6980-5a60-11eb-95ac-cc9514759689.png)

changed nothing, so it should be the default

**Comment by DelazJ** [comment]
I meant what happens if you remove "Null" from the last field

**Comment by Infiziert90** [comment]
Empty fields, but for all NULL fields ... so even integer fields with a true NULL are now completely empty

**Comment by gioman** [comment]
> QGIS version 3.16.2-Hannover on Windows 10

@Infiziert90 @elpaso I see the same, but just on Windows (tested 3.10, 3.16 and master)

![Screenshot_20210119_151003](https://user-images.githubusercontent.com/1951107/105054092-838c2d80-5a69-11eb-9ec9-8f117b8c682f.png)

**Comment by gioman** [comment]
This 3.10.14 on Windows here, so also a different observation compared to @Infiziert90 

![Screenshot_20210119_151950](https://user-images.githubusercontent.com/1951107/105054390-d9f96c00-5a69-11eb-8ad7-4208210cd391.png)

**Comment by Infiziert90** [comment]
Freshly installed 3.10.13 on a new PC that never had any QGIS installed and it happens the same for me ... NULL and not an empty field

But on my 3.10.13 maschine that had it constantly updated it is still an empty field as it is in the ubuntu master version

So some bug with the default preview that changed recently?

**Comment by elpaso** [comment]
There are (at least) two different ways (and two different providers) you can open a sqlite file: one is the spatialite provider and the other one is the GDAL (ogr) provider.

Which one are you using?

**Comment by elpaso** [comment]
Here is 3.16 on windows (MXE build, GDAL 2.x), OGR provider on the left, spatialite provider on the right

![immagine](https://user-images.githubusercontent.com/142164/105156666-6ceae280-5b0c-11eb-9d78-3e61c9321a23.png)


I suspect this might be GDAL-version dependent when using ogr provider.

Anyone can test on windows with QGIS >= 3.16 and GDAL >= 3.x ?

**Comment by Infiziert90** [comment]
Yeah thats exactly what is happening and i not noticed it before hand ...

i always drag&drop the SQL File into QGIS, but on the other maschine i made a SpatialLite connection 
![image](https://user-images.githubusercontent.com/22648449/105158141-f18a3080-5b0d-11eb-881c-67e0c8e6740b.png)

And as you said, with SpatialLite it is shown correctly

**Comment by elpaso** [comment]
ok, so I guess this depends on the GDAL version. I have no time to test a QGIS with GDAL >= 3.x on windows.

**Comment by Infiziert90** [comment]
![image](https://user-images.githubusercontent.com/22648449/105158954-d79d1d80-5b0e-11eb-8c4c-c7f56d2552de.png)
 Spatial on the left and drag&drop on the right

QGIS version
3.16.2-Hannover
Compiled against GDAL/OGR
3.1.4
Compiled against SQLite
3.29.0

**Comment by gioman** [comment]
> ok, so I guess this depends on the GDAL version. I have no time to test a QGIS with GDAL >= 3.x on windows.

@elpaso same observations as @Infiziert90 in https://github.com/qgis/QGIS/issues/41076#issuecomment-763488871 on QGIS master on Windows/OSGeo4W On Master/Ubuntu 20.04 on the other hand is correct in both ways.

Linux


QGIS version | 3.17.0-Master | QGIS code revision | df2c9ff931
-- | -- | -- | --
Compiled against Qt | 5.12.8 | Running against Qt | 5.12.8
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
Compiled against PDAL | 2.0.1 | Running against PDAL | 2.0.1 (git-version: Release)
PostgreSQL Client Version | 12.5 (Ubuntu 12.5-0ubuntu0.20.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Ubuntu 20.04.1 LTS | This copy of QGIS writes debugging output.



Windows:

Versão do QGIS | 3.17.0-Master | Revisão do código do QGIS | 740c41f5a8
-- | -- | -- | --
Compilado com Qt | 5.11.2 | Em execução com Qt | 5.11.2
Compilado com GDAL/OGR | 3.1.4 | Em execução com GDAL/OGR | 3.3.0dev
Compilado com GEOS | 3.8.1-CAPI-1.13.3 | Em execução com GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
Versão de cliente PostgreSQL | 11.5 | Versão SpatiaLite | 4.3.0
Versão QWT | 6.1.3 | Versão QScintilla2 | 2.10.8
Compilado com PROJ | 8.0.0 | Em execução com PROJ | Rel. 8.0.0, March 1st, 2021
OS Version | Windows 10 (10.0) | Esta cópia do QGIS escreve a saída de depuração.

**Comment by elpaso** [comment]
@gioman can we conclude that:

1. the issue is only with OGR provider?
2. the issue is windows only?

I tested on linux master with GDAL 3.2.0 and I cannot reproduce.

A a side note, on your windows test you are running  QGIS with a different GDAL than it was compiled with.

**Comment by gioman** [comment]
> * the issue is only with OGR provider?
> 
> * the issue is windows only?

@elpaso as far as I can see is both "yes"



> A a side note, on your windows test you are running QGIS with a different GDAL than it was compiled with.

@elpaso I just use osgeo4w, I don't compile QGIS on Windows, so it must be an issue with Windows packaging(?).

**Comment by gioman** [comment]
Funny thing here on Windows the icons for the layers in the Spatialite connection in the QGIS browser are wrong

![Screenshot_20210120_105931](https://user-images.githubusercontent.com/1951107/105165769-a9b7d900-5b0e-11eb-83b3-f924ddb20922.png)

but layers can be added normally (with double click).

**Comment by gioman** [comment]
> are wrong

3.10, 3.16 and master, all via osgeo4w.

**Comment by elpaso** [comment]
I'm currently building on windows with newest GDAL and see if I can debug it, but it will probably take several hours :( 

I'm wondering if it worth the effort...

**Comment by gioman** [comment]
> I'm wondering if it worth the effort...

is there any alternative to fixing it? I mean... this can lead to very wrong results for some individual/organization that uses spatialite data-sources in their workforce.

**Comment by gioman** [comment]
FYI I tested QGIS master on macOS and there is all ok too.

**Comment by elpaso** [comment]
> > I'm wondering if it worth the effort...
> 
> is there any alternative to fixing it? 

At least there is a workaround, that is to use the spatialite provider.

**Comment by gioman** [comment]
> At least there is a workaround, that is to use the spatialite provider.

true.
