### ISSUE TITLE
line_substring returns an empty geometry when distances are exact (e.g., computed with distance_to_vertex)

### ISSUE THREAD

**Issue by alkra** [qgis/QGIS#41081]
**Describe the bug**

I wanted to draw only parts of a linear feature, with a geometry generator.  I identified the parts I was interested in using a range of vertex numbers. I could not find a "substring" function taking a vertex range as argument, so I used line_substring together with distance_to_vertex.

    line_substring($geometry, distance_to_vertex($geometry, "VERT1"), distance_to_vertex($geometry, "VERT2"))

But then, the features were not drawn. I tried using that formula with geom_to_wkt in a virtual field:

    LINESTRING EMPTY

**How to Reproduce**

The attached self-contained project demonstrates the issue.
 
[bugXXX.qgz](https://github.com/qgis/QGIS/files/5836949/bugXXX.zip)

**QGIS and OS versions**

QGIS version: 3.17.0-Master
QGIS code revision: a84647cf30
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL/OGR: 3.2.1
Running against GDAL/OGR: 3.2.1
Compiled against GEOS: 3.9.0-CAPI-1.16.2
Running against GEOS: 3.9.0-CAPI-1.16.2
Compiled against SQLite: 3.34.0
Running against SQLite: 3.32.3
PostgreSQL Client Version: 13.1 (Debian 13.1-1+b1)
SpatiaLite Version: 5.0.0
QWT Version: 6.1.4
QScintilla2 Version: 2.11.6
Compiled against PROJ: 7.2.1
Running against PROJ: Rel. 7.2.1, January 1st, 2021
OS Version: Debian GNU/Linux bullseye/sid
This copy of QGIS writes debugging output.

**Additional context**

**Comment by alkra** [comment]
I investigated the issue further. In src/core/geometry/qgslinestring.cpp:1083, the case when `startDistance == distanceTraversed` is not handled (unless `startDistance` is 0.0). I'm preparing a pull request.

**Comment by gioman** [comment]
> I'm preparing a pull request.

@alkra nice, thanks!
