### ISSUE TITLE
HANA connection dialog is all messed up on linux/master

### ISSUE THREAD

**Issue by elpaso** [qgis/QGIS#41103]
![immagine](https://user-images.githubusercontent.com/142164/105166385-b0971980-5b17-11eb-8fa2-f29883fb3c76.png)

**Comment by mrylov** [comment]
Which Linux and theme do you use @elpaso?

**Comment by elpaso** [comment]
I'm on Ubuntu 20.04 and KDE, but there is clearly a layout issue in the dialog and I think it will impact other skins too.

**Comment by mrylov** [comment]
@elpaso, could you please check whether #41119 fixes the issue in your case?

**Comment by mrylov** [comment]
@elpaso, I assume this issue can be closed.

**Comment by elpaso** [comment]
To close issues automatically just put "Fixes #xxxx" in the PR message (or in the commit directly).
