### ISSUE TITLE
Fallo inesperado QGIS

### ISSUE THREAD

**Issue by gtja77** [qgis/QGIS#41104]
Buenos días....

Al ingresar en a la aplicación QGIS 3.16, se ha procedido a crea un proyecto y al  etiquetar un vector se cierra de manera inesperada.

Espero puedan ayudarme, abajo dejo el error que me presenta:

Warning: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Warning: Empty filename passed to function
Warning: QXcbConnection: XCB error: 3 (BadWindow), sequence: 2521, resource id: 23213204, major code: 40 (TranslateCoords), minor code: 0
QGIS died on signal 11Abortado

Jairo González

**Comment by gioman** [comment]
@gtja77 tickets must be filed in English and must contain the following info


####


**Describe the bug**


**How to Reproduce**



1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error -->

**QGIS and OS versions**



**Additional context**


####


Before reporting try with a new QGIS profile and see if the issue persist. If it does attach a sample project with data.
