### ISSUE TITLE
Georeferencer should use multithreaded GDAL image warper

### ISSUE THREAD

**Issue by justinbb** [qgis/QGIS#41101]
Georeferencing is used a lot. Currently it is done single-threaded, which can take a long time for large image files. Computers are usually multicore these days, and GDAL has had a multi-threaded image warper function for over a decade. Why not use it?

In file QGIS/src/app/georeferencer/qgsimagewarper.cpp, function QgsImageWarper::warpFile(), the following two lines have existed unchanged since 2010:

```
  eErr = oOperation.ChunkAndWarpImage( 0, 0, destPixels, destLines );
//  eErr = oOperation.ChunkAndWarpMulti(0, 0, destPixels, destLines);

```

Clearly the possibility of using multithreaded image warping was considered at the time but not actually activated. Eleven years later, surely GDAL's multithreaded warper is functional and safe? (Or do I presume too much?)

**Comment by gioman** [comment]
>   eErr = oOperation.ChunkAndWarpImage( 0, 0, destPixels, destLines );
> //  eErr = oOperation.ChunkAndWarpMulti(0, 0, destPixels, destLines);

@justinbb can you propose a patch?

**Comment by roya0045** [comment]
Though since this may be considered a feature, depending on the freeze it may take quite a while before being seen in releases.

**Comment by justinbb** [comment]
I think this is all that's required. [GDAL documentation](https://gdal.org/tutorials/warp_tut.html#performance-optimization) implies that ChunkAndWarpMulti is a drop-in replacement for ChunkAndWarpImage, as long as GDAL is made with multithreading (the default).

[qgsimagewarper.cpp-patch.txt](https://github.com/qgis/QGIS/files/5843656/qgsimagewarper.cpp-patch.txt)

**Comment by gioman** [comment]
> [qgsimagewarper.cpp-patch.txt](https://github.com/qgis/QGIS/files/5843656/qgsimagewarper.cpp-patch.txt)

@justinbb nice thanks! can you make it in the form of a pull request?

**Comment by roya0045** [comment]
@justinbb If you are unsure you can use this guide as a reference https://docs.qgis.org/3.16/en/docs/documentation_guidelines/first_contribution.html

**Comment by gioman** [comment]
> @justinbb If you are unsure you can use this guide as a reference https://docs.qgis.org/3.16/en/docs/documentation_guidelines/first_contribution.html

The patch is so simple I guess ot can be simply done using the GH web gui.

**Comment by justinbb** [comment]
That wasn't so hard. :-) Thanks for the guidance!

**Comment by gioman** [comment]
> That wasn't so hard. :-) Thanks for the guidance!

@justinbb wait, you have merge it in your fork, you need to make the open the PR against the QGIS repo (master branch) :)

**Comment by justinbb** [comment]
@gioman Sigh. I read the documentation too quickly and missed that part. This time it should be good (once the checks finish).

**Comment by uclaros** [comment]
Have you tested this? Is there a measurable gain? What happens when gdal is not built with multi-threading support?

**Comment by justinbb** [comment]
@uclaros My feature request (which I initially supposed would be taken care of by someone familiar with this part of QGIS) rather rapidly advanced to a patch and then a pull request. There is certainly a performance problem to be solved, and the GDAL documentation implies that this patch will help. But no, it is not tested.
I am willing and able to take this on more seriously and do testing. However, since I am not already a QGIS developer, it will involve getting a development environment set up (or discovering resources on Github with which I am only barely familiar). It will take a week or two to find time and to work through it all.

**Comment by roya0045** [comment]
@uclaros If you look at the existing PR by Mathieu I think this is safe to assume that it does help as mentioned by Even, no need to force @justinbb  to test this given the fact that we know this will improve performance.

**Comment by uclaros** [comment]
Yup, I saw the discussion in the PR right after I posted this.
