### ISSUE TITLE
Add 'Autosize All Columns' to Attribute Table context menu

### ISSUE THREAD

**Issue by dmatranga** [qgis/QGIS#41108]
**Feature description.**

Add the option to 'Autosize All Columns' to the Attribute Table context menu.
![image](https://user-images.githubusercontent.com/75672/105212829-91968880-5b13-11eb-92eb-4785c2a1598f.png)

**Steps to reproduce:**

* Right-click layer in Layers panel >
* Open attribute table >
* Right-click a column >
* This context menu appears
* Request: add another menu item called 'Autosize All Columns', which resizes all the columns in a given attribute table view.

_Current Context Menu_
![image](https://user-images.githubusercontent.com/75672/105212750-79bf0480-5b13-11eb-9149-9a6340aca113.png)

**Additional context**

**Comment by benwirf** [comment]
As a very simple feature improvement, I think this could be a perfect start for a novice contributor like myself. I have successfully implemented this in my build as seen in the gif below.

![Peek 2021-01-29 20-57](https://user-images.githubusercontent.com/47767794/106280736-068f5e00-628a-11eb-8cb9-d56fe0bfe295.gif)

I have also added another action ‘Set Width All’ to the context menu which allows to set a width value to be applied to all columns (see below).

![Peek 2021-01-29 20-58](https://user-images.githubusercontent.com/47767794/106280920-3cccdd80-628a-11eb-99d8-65fc33a37e2f.gif)

The code changes are quite small and un-intrusive. If there is some indication from core devs that this would be worthwhile to add, I would be happy to start the process of making (my first) pull request.
In that case, I would be greatly appreciative if any experienced devs would be willing to give me some help with writing and running unit tests (if required). Perhaps @nyalldawson, any chance I could bug you for some pointers at some stage?

**Comment by gioman** [comment]
@benwirf make a pull request.

**Comment by theroggy** [comment]
This has been implemented and merged... so could be closed.

As a variant on the theme, it would also be nice if there was a configuration setting to always apply this automatically when opening an attribute table... E.g. here:
![image](https://github.com/qgis/QGIS/assets/1565789/197a2631-1b0f-4843-9ede-a1671047a446)

**Comment by benwirf** [comment]
Hi @theroggy, yes- that would certainly be a nice extension to this functionality. I am very happy to work on this; I don't think it will be too difficult to implement. I'm fairly busy with my day job for the next couple of weeks, but I will try to make a start on this soon and I will open a new PR as soon as I can.

**Comment by agiudiceandrea** [comment]
Fixed by https://github.com/qgis/QGIS/pull/41276.

**Comment by theroggy** [comment]
@benwirf thanks for this!!!
