### ISSUE TITLE
Invalid ellipsoidAcronym for EPSG:104903 

### ISSUE THREAD

**Issue by BerginJay** [qgis/QGIS#41105]
**Describe the bug**

CRS "EPSG:104903 GCS_Moon_2000" has no available ellipsoid acronym which should be "Moon2000"

**How to Reproduce**

1. create a new layer with "EPSG:104903 GCS_Moon_2000" CRS
2. Open python console and type `QgsProject.instance().mapLayer('layerid').crs().ellipsoid()`
3. which would return an empty str ''

However, as for IAU2000:30100, these steps would produce the right "Moon2000" acronym string.

**QGIS and OS versions**

QGIS version | 3.10.11-A Coruña | QGIS code revision | d2171173e4
-- | -- | -- | --
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.28.0 | Running against SQLite | 3.28.0
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS 10.15
Active python plugins | processing; MetaSearch; CircleCraters

**Additional context**

I don't know if this error is due to QGIS. If it is due to other dependencies like Proj, please tell me and just close the issue, and I am sorry about that.

**Comment by gioman** [comment]
> f it is due to other dependencies like Proj, please tell me and just close the issue, and I am sorry about that.

likely to be a Proj issue rather than QGIS.

**Comment by roya0045** [comment]
I suggest updating to the latest 3.16 to see if its still valid as you are using proj 5.2, which won't be used anymore anyway.

**Comment by nyalldawson** [comment]
This wont be fixed -- the support for proj versions < 6 is unmaintained now. The solution is to update to a version which uses proj 6 or later.

**Comment by BerginJay** [comment]
QGIS 3.16 doesn't have CRS  IAU2000:30100, but "EPSG:104903 GCS_Moon_2000" gives the right ellipsoid. Thanks anyway.
