### ISSUE TITLE
WMS throws LayerNotDefined when layer name contains plus sign (+)

### ISSUE THREAD

**Issue by billtian** [qgis/QGIS#41116]
**Describe the bug**

WMS throws LayerNotDefined when layer name contains plus sign (+)

**How to Reproduce**

1. create a qgs map document that contains a layer with name contains plus sign, etc abcd+efg.img
2. use the map file created in step 1 to serve as WMS
3. Send GetMap request with LAYERS asigned to the layer name contains plus sign
4. WMS throws LayerNotDefined exception

**QGIS and OS versions**

QGIS version | 3.4.11-Madeira | QGIS code branch | Release 3.4
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.4.2 | Running against GDAL/OGR | 2.4.0
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
PostgreSQL Client Version | 10.10 (Ubuntu 10.10-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
Compiled against PROJ | 520 | Running against PROJ | 5.2.0

**Additional context**

output in logs show that LAYERS has changed in WMS Request parameters.

```
12:28:47 INFO Server[5043]: ******************** New request ***************
12:28:47 INFO Server[5043]: SERVER_NAME127.0.0.1
12:28:47 INFO Server[5043]: REQUEST_URI/qgisserver/cgi-bin/qgis_mapserv.fcgi?SERVICE=WMS&REQUEST=GetMap&VERSION=1.3.0&MAP=%2Fdata%2Fcloud-cache%2Flayers%2Fthumbnail%2F71%2F11349.qgs&LAYERS=110105BJ2%2BTDOM.img&BBOX=116.34285240918803%2C39.80697114571101%2C116.64127411602777%2C40.090459385245225&SRS=CRS:84&WIDTH=256&HEIGHT=256&FORMAT=image/png&TRANSPARENT=TRUE
12:28:47 INFO Server[5043]: REMOTE_ADDR127.0.0.1
12:28:47 INFO Server[5043]: CONTENT_TYPE
12:28:47 INFO Server[5043]: HTTP_USER_AGENTJava/1.8.0_275
12:28:47 WARNING [5043]: formatString is: image/png
12:28:47 INFO Server[5043]: BBOX:116.34285240918803,39.80697114571101,116.64127411602777,40.090459385245225
12:28:47 INFO Server[5043]: FORMAT:image/png
12:28:47 INFO Server[5043]: HEIGHT:256
12:28:47 INFO Server[5043]: LAYERS:110105BJ2+TDOM.img
12:28:47 INFO Server[5043]: MAP:/data/cloud-cache/layers/thumbnail/71/11349.qgs
12:28:47 INFO Server[5043]: REQUEST:GetMap
12:28:47 INFO Server[5043]: SERVICE:WMS
12:28:47 INFO Server[5043]: SRS:CRS:84
12:28:47 INFO Server[5043]: TRANSPARENT:TRUE
12:28:47 INFO Server[5043]: VERSION:1.3.0
12:28:47 INFO Server[5043]: WIDTH:256
12:28:47 INFO Server[5043]: WMS Request parameters:
12:28:47 INFO Server[5043]:  - SRS : CRS:84
12:28:47 INFO Server[5043]:  - WIDTH : 256
12:28:47 INFO Server[5043]:  - HEIGHT : 256
12:28:47 INFO Server[5043]:  - BBOX : 116.34285240918803,39.80697114571101,116.64127411602777,40.090459385245225
12:28:47 INFO Server[5043]:  - LAYERS : 110105BJ2 TDOM.img
12:28:47 INFO Server[5043]:  - FORMAT : image/png
12:28:47 INFO Server[5043]:  - TRANSPARENT : TRUE
12:28:47 INFO Server[5043]:  - VERSION : 1.3.0
12:28:47 INFO Server[5043]: Request finished in 1 ms

```

**Cause**

parameters has been decoded in `QgsServerParameters::load` before processed by WMS service.

QgsWmsParameters 's constructor call `QgsServerParameters::load` to decod the url that has been decoded before and replace `+` with `%20`, so `+` became ` ` (space) when processed by WMS.

May be we can process `mUnmanagedParameters` in  `QgsServerParameters` directly.

Thanks !

**Comment by elpaso** [comment]
Version 3.4 is not supported anymore, I'm checking if this is still an issue on current master.

**Comment by elpaso** [comment]
I checked and I think the server is doing it right:

layer name is `test+plus` in this project, a request should encode the `+` literal sign in the url as follows:

```
?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&LAYERS=test%2Bplus&STYLES=&FORMAT=image/png&BBOX=-170,-80,170,80&HEIGHT=500&WIDTH=500&CRS=EPSG:4326
```

The response is correct (and the encoded `+` is decoded correctly):
```
Server(0): WMS Request parameters:
Server(0):  - CRS : EPSG:4326
Server(0):  - WIDTH : 500
Server(0):  - HEIGHT : 500
Server(0):  - BBOX : -170,-80,170,80
Server(0):  - LAYERS : test+plus
Server(0):  - FORMAT : image/png
Server(0):  - VERSION : 1.1.1
```

My conclusion is that there is a bug in the QGIS desktop WMS provider, meaning that the layer names as read from a `GetCapabilities` response are not urlencoded before being passed into the `GetMap` call.

**Comment by manisandro** [comment]
@elpaso I had tracked down a similar issue here [1] but then got sidetracked by other work.

[1] https://github.com/qgis/QGIS/pull/39436

**Comment by elpaso** [comment]
@manisandro mmm, that one is about POST in the server though. 

This one is about the client WMS data provider that does not encode layer names.

I don't see any issue in the server for GET calls (see: [1]) but I didn't check POST.

[1] https://github.com/qgis/QGIS/pull/41211/files#diff-3b0c9608257217d29fef2fbff710edda17c03905e52b66d9cca84a2e8fd40f4fR1824

Do you want me to continue from #39436 or are you going to finish it ?

**Comment by manisandro** [comment]
@elpaso I've rebased and resubmitted #39436 as #41217 - if I recall correctly, I ended up getting stuck at a test failure in a related area where I was not sure whether the test was bad or whether my PR had side-effects. If you could give that a look once travis is through, I'd appreciate it.
