### ISSUE TITLE
lineStringZ length calculation function

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#41115]
In the QGIS field calculator there are over 100 geometric functions but none to calculate the length of `LineStringZ`.
- `$lenght` calculates the length respecting the project settings (ellipsoidal length)
- `lenght ($geometry)` calculates the 2D Cartesian length

it would be very useful to be able to calculate the 3D Cartesian length as visible from the information through icon ![](https://docs.qgis.org/3.16/it/_images/mActionIdentify.png)

![image](https://user-images.githubusercontent.com/7631137/105318904-628c1f80-5bc4-11eb-97d9-636584fe082e.png)

**Comment by agiudiceandrea** [comment]
It shouldn't be very difficult

```cpp
static QVariant fcnLength3D( const QVariantList &values, const QgsExpressionContext *, QgsExpression *parent, const QgsExpressionNodeFunction * )
{
  // two variants, one for geometry, one for string
  if ( values.at( 0 ).canConvert<QgsGeometry>() )
  {
    //geometry variant
    QgsGeometry geom = QgsExpressionUtils::getGeometry( values.at( 0 ), parent );
    if ( geom.type() != QgsWkbTypes::LineGeometry )
      return QVariant();

    return QVariant( qgsgeometry_cast< const QgsLineString * >( geom.constGet() )->length3D() );
  }

  return QVariant();
}
```

**Comment by rmarzocchi84** [comment]
> It shouldn't be very difficult.
> Relevant code to add in [qgsexpressionfunction.cpp](https://github.com/qgis/QGIS/blob/master/src/core/expression/qgsexpressionfunction.cpp):
> 
> ```c++
> static QVariant fcnLength3D( const QVariantList &values, const QgsExpressionContext *, QgsExpression *parent, const QgsExpressionNodeFunction * )
> {
>   if ( values.at( 0 ).canConvert<QgsGeometry>() )
>   {
>     QgsGeometry geom = QgsExpressionUtils::getGeometry( values.at( 0 ), parent );
>     if ( geom.type() == QgsWkbTypes::LineGeometry )
>       return QVariant( qgsgeometry_cast< const QgsLineString * >( geom.constGet() )->length3D() );
>   }
>   return QVariant();
> }
> ```

Only C++ for field calculator core developement or also python?

**Comment by roya0045** [comment]
@rmarzocchi84 The proposed code would add the function to the field calc, though you'd still need to expose it in the related files. It's already in python https://github.com/qgis/QGIS/blob/0f292cfb36ba862a4103a0957bb41510edd4de27/python/core/auto_generated/geometry/qgslinestring.sip.in#L459

**Comment by pigreco** [comment]
it would be better if the length calculation did it also for `MultiLineStringZ` which are very popular.

thank you very much @agiudiceandrea

**Comment by pigreco** [comment]
https://github.com/qgis/QGIS/pull/41780
