### ISSUE TITLE
Server WMS GetFeatureInfo feature ID inconsitencies

### ISSUE THREAD

**Issue by elpaso** [qgis/QGIS#41124]
QGIS Server GetFeatureInfo returns different feature IDs for the same request on different instances.

Scenario:
- provider postgres, standard ordinary spatial layer with int64 pk, indexes and all
- multiple server instances behind a load balancer

What happens here is that depending on which particular request hits the instances first, the feature IDs assigned by the data provider (which are incremental starting from 1) change. The FID->PK mapping is cached so **this issue won't be present when using a single instance**.

So, the same client issuing the same request might hit a different instance of the server, getting back results with different feature IDs for the same feature.

I know that it is possible to instruct some load balances to always route a certain IP to the same instance instead of using round-robin or other schemes, but I believe that we should have way to consistently assign the same feature ID in a `GetFeatureInfo` response.

This is a pretty serious bug that prevent to use QGIS server in production under heavy load.

I cannot see a simple solution here, we cannot change the internal representation of `QgsFeature::id()` (qlonglong) without rewriting QGIS from the ground up, what we can probably do is to implement a `QString QgsFeature::providerId()` that delegates to the data provider to produce a consistent string representation of the feature ID to be used in these situations.

The data provider will calculate the stable feature ID from the PKs in a way that it make it easy to retrieve the feature from its `providerId`.

Any word of wisdom or other idea?

CC: @rldhont @pblottiere @dmarteau @mhugent

**Comment by rldhont** [comment]
@elpaso a `QgsServerFeatureId::getServerFid` has been implemented and used in WFS to avoid this issue. I was thinking that it is used in `GetFeatureId`

**Comment by mhugent** [comment]
Yes, I remember having the same problem in WFS, therefore implementing getServerFid. It should solve the problem for datasources with PK columns.

**Comment by elpaso** [comment]
@rldhont @mhugent thank you, I'll look into the WFS code and se if we can reuse that system.

**Comment by rldhont** [comment]
@m-kuhn has proposed to create a `QgsPersistentFeatureId` to solve this issue in QGIS and not only the server https://github.com/qgis/QGIS/pull/10034#issuecomment-494764774 But I think it has to be a QEP first.

**Comment by elpaso** [comment]
> @m-kuhn has proposed to create a `QgsPersistentFeatureId` to solve this issue in QGIS and not only the server [#10034 (comment)](https://github.com/qgis/QGIS/pull/10034#issuecomment-494764774) But I think it has to be a QEP first.

Nice, that was exactly what I had in mind. I think we really need something like that.
