### ISSUE TITLE
qgis_process is not showing algorithm providers installed via a python plugin

### ISSUE THREAD

**Issue by janzandr** [qgis/QGIS#41120]
**Describe the bug**

I installed and activated a python plugin that provides a processing algorithms (e.g. "Append Features to Layer" plugin).

![image](https://user-images.githubusercontent.com/45030715/105356540-d2fe6500-5bf3-11eb-8417-99047b484b85.png)

When running "qgis_process plugins" from OSGeo4W shell, the new provider is not found:
![image](https://user-images.githubusercontent.com/45030715/105356842-38525600-5bf4-11eb-96b0-9a8c5cf46f45.png)

I also tried to run the command from within QGIS Python Console, but that gives the same result:

![image](https://user-images.githubusercontent.com/45030715/105357040-82d3d280-5bf4-11eb-8904-3c1b86db37ad.png)

**Comment by Gustry** [comment]
You should report to the plugin author and add the flag `hasProcessingProvider` in the metadata.txt and it should work.
https://docs.qgis.org/3.10/en/docs/pyqgis_developer_cookbook/plugins/plugins.html#plugin-metadata-table

Reopen if it's not working.

**Comment by AndreasRabe** [comment]
I added the `hasProcessingProvider=True` to metadata.txt, but that didn't solved the problem.

Here is a minimalistic plugin that implements a processing provider with one algorithm:
![image](https://user-images.githubusercontent.com/45030715/105466189-2c1dd580-5c94-11eb-9f2a-2ceaeea33ee4.png)

I installed the plugin via Install from ZIP and activated it, but `qgis_process` is still not listing it. Maybe I miss an important detail. Thanks for your support!

[dummyplugin.zip](https://github.com/qgis/QGIS/files/5854420/dummyplugin.zip)

**Comment by Gustry** [comment]
You should follow the second link. You are missing the `initProcessing`. Can you try again ?

**Comment by AndreasRabe** [comment]
I fixed that, but still not working. Here is the updated plugin:

[dummyplugin.zip](https://github.com/qgis/QGIS/files/5854538/dummyplugin.zip)

**Comment by Gustry** [comment]
Reopening in the meantime.
Because it should work. I have already adapted plugins a few weeks ago.

**Comment by Gustry** [comment]
Put `yes` instead of `True`. It's working.
Like mentioned https://docs.qgis.org/3.10/en/docs/pyqgis_developer_cookbook/processing.html#updating-a-plugin
Agreed, it should work as well.

The table should be updated : https://docs.qgis.org/3.10/en/docs/pyqgis_developer_cookbook/plugins/plugins.html#plugin-metadata-table

**Comment by AndreasRabe** [comment]
It worked, thanks a lot.

**Comment by gacarrillor** [comment]
> You should report to the plugin author and add the flag `hasProcessingProvider` in the metadata.txt and it should work.
> https://docs.qgis.org/3.10/en/docs/pyqgis_developer_cookbook/plugins/plugins.html#plugin-metadata-table

I'm with @Gustry here.
Not only fix your local copy of the plugin, but also contact the plugin author (for the example you gave, `Append Features to Layer`, it happens to be me :) ).

A [PR](https://github.com/gacarrillor/AppendFeaturesToLayer/pulls) will be much appreciated :+1:

**Comment by AndreasRabe** [comment]
I edited the metadata and the plugin and created PR.

**Comment by DelazJ** [comment]
> Put yes instead of True.

@Gustry Maybe `hasProcessingProvider` should allow True/False (like the other parameters in the metadata file)? Unlike https://github.com/qgis/QGIS-Documentation/pull/3517/files#r264070345 I failed to have `true` or `True` work  on a local plugin( ie being recognized by qgis_process -not aware of any other tool this parameter is meant to be used with). Or do we need to align the docs?

**Comment by Gustry** [comment]
The bug is still valid @gioman so I remove feedback.

Either we need to update to documentation, or indeed it would be better to upgrade QGIS core
