### ISSUE TITLE
Transparency problem with no-data pixels in ArcGIS MapServer layer

### ISSUE THREAD

**Issue by berniejconnors** [qgis/QGIS#41126]
We have been publishing ArcGIS Server map services since 2009.  It is important to us that our users have quality open source GIS software to access our map services.

**Bug Description**

No-data pixels in an ArcGIS Image service are not transparent.  The problem with the no-data pixels is dependant upon the method used to add the ArcGIS Image Service to the QGIS project.  Both methods *should* give the same result but they don’t.  Method 1 below will produce **opaque** no-data pixels.  Method 2 will produce **transparent** no-data pixels.

**How to Reproduce**
*METHOD 1*

1. Layer > Add Layer > Add ArcGIS MapServer Layer
2. Click the “New” Server connection button
3. Provide a Name for the connection and provide a URL.  **Use the URL for the root of the ArcGIS Server REST services**, e.g., [https://geonb.snb.ca/image/rest/services/](https://geonb.snb.ca/image/rest/services/)
4. Click the OK button to close the “Create a New ARCGISMAPSERVER Connection” dialogue box
5. Click the “Add” button in the Data Source Manager window.  An “ArcGISMapServer” item will appear in the Browser Pane:
![qgis_browser_pane](https://user-images.githubusercontent.com/13241302/105382124-21a50280-5be6-11eb-87f3-8c67c7ef5f0a.jpg)
6. Expand the ArcGISMapServer item to expose the desired MapServer layer:
![qgis_browser_pane2](https://user-images.githubusercontent.com/13241302/105382509-852f3000-5be6-11eb-8c14-cb2141ac426a.jpg)
7.	Drag and drop the ArcGISMapServer layer onto the map.  The no-data pixels are opaque:
![qgis_opaque_nodata](https://user-images.githubusercontent.com/13241302/105382718-c1629080-5be6-11eb-929c-96e3dd6f5e0b.jpg)
The layer properties show **format=’jpg’**.  JPEG does not support transparency:
![qgis_layer_properties1](https://user-images.githubusercontent.com/13241302/105383261-4cdc2180-5be7-11eb-97e2-32a6b4111211.png)

*METHOD 2*
1.	Layer > Add Layer > Add ArcGIS MapServer Layer
2.	Click the “New” Server connection button
3.	Provide a Name for the connection and provide a URL.  **Use the full URL for the desired Image Service**, e.g., [https://geonb.snb.ca/image/rest/services/Elevation/DEM_Hillshade_Multi_MNE_Ombrage_Multiple/ImageServer/](https://geonb.snb.ca/image/rest/services/Elevation/DEM_Hillshade_Multi_MNE_Ombrage_Multiple/ImageServer/) 
4.	Click the OK button to close the “Create a New ARCGISMAPSERVER Connection” dialogue box
5.	Click the “Add” button in the Data Source Manager window.  The new Image Service will be added to the map.  The no-data pixels are transparent:
![qgis_transparent_nodata](https://user-images.githubusercontent.com/13241302/105383775-dc81d000-5be7-11eb-982f-24da14269461.jpg)
The layer properties show **format=’’**. I presume this will allow ArcGIS Image server to return the default image format. The default format is “jpgpng”.  This format returns a JPG if there are no transparent pixels in the requested extent; otherwise, it returns a PNG (png32):
![qgis_layer_properties2 png](https://user-images.githubusercontent.com/13241302/105384036-24085c00-5be8-11eb-95a0-add79c0a63a1.jpg)

**Summary**

- Method 2 correctly displays the transparent no-data pixels
- Method 1 returns opaque no-data pixels but will be far more convenient for users that will need to add many layers from our ArcGIS Servers.  
- Both methods should return the same results.

I am not a programmer but it seems to me this should be a very easy fix.  The API request that is sent to ArcGIS Server needs to be modified so the returned image is not in the JPG format.  If the "&format=" parameter is ommitted the default image format will provide transparency for nodata pixels.  [ArcGIS REST API Reference for "exportImage"](https://geonb.snb.ca/image/sdk/rest/index.html#//02ss00000075000000). 

**QGIS and OS versions**

- QGIS version - 3.10.13-A Coruña but also seen in 3.16
- Microsoft Windows 10 Enterprise, 64-bit

**Comment by roya0045** [comment]
Are you saying that you are fine with either results as long as they are consistent or is there a preferred one? 

Also does not specifying the format allows the result to switch format? I would guess that having no format imposed would be the best solution if the format is optional. I'm not familiar with web providers and the specifications though.

**Comment by berniejconnors** [comment]
@roya0045 the preferred result is to have transparency for nodata pixels.

I am not a programmer but it seems to me this should be a very easy fix. The API request that is sent to ArcGIS Server needs to be modified so the returned image is not in the JPG format. If the "&format=" parameter is ommitted the default image format will provide transparency for nodata pixels. [ArcGIS REST API Reference for "exportImage"](https://geonb.snb.ca/image/sdk/rest/index.html#//02ss00000075000000).

**Comment by berniejconnors** [comment]
I am curious why the API request is different between the two methods I described above.  Shouldn't both methods be using the same code to request an image from ArcGIS Server?

**Comment by roya0045** [comment]
I think the forced format comes from the query used to enumerate the layers for the service in the browser. This is the attribute that may be used to coerce the format, as it seems safer to use a known format is some cases.

**Comment by roya0045** [comment]
One important point is that Nyall recently reworked the code for arcgis rest, I have no clue if that change will affect that behaviour. @gioman if you have a moment to spare eventually, could you test if this behavior is unchanged in master.

**Comment by gioman** [comment]
> @gioman if you have a moment to spare eventually, could you test if this behavior is unchanged in master.

@roya0045 I confirm the described behavior on master.

**Comment by roya0045** [comment]
@gioman Thanks! I'll try to look into it this weekend.

**Comment by roya0045** [comment]
Did a quick test on 3.12 with the network logger plugin, the non-specified format asks for png32, whereas the specified asks for jpg, so a format is specified in the request, just not the source presented.

**Comment by gioman** [comment]
> Did a quick test on 3.12 with the network logger plugin, the non-specified format asks for png32, whereas the specified asks for jpg, so a format is specified in the request, just not the source presented.

@roya0045 if it was the WMS client this shows (after connecting to the endpoint) what formats (png, jpg, etc.) the server makes available for a map to be downloaded. In this case it seems that QGIS defaults to png in both the browser and the "add WMS layer" dialog. This option does not seems to show in the ArcGis map server client, not sure if it is because it does not exist such option or else.

**Comment by roya0045** [comment]
Ok so the offending line is https://github.com/qgis/QGIS/blob/12a7afb1f32a30ebb83961ad75b1ad904b33a018/src/core/providers/arcgis/qgsarcgisrestquery.cpp#L324 now I simply removed the jpg and let it empty and it was fine. Going to do a PR to see if this is a bad move.

**Comment by roya0045** [comment]
@berniejconnors We'll see if the PR is accepted. Also I noticed you had some default things exposed, I'm not sure if this was intended or not. The 2017 test dem also seems 'broken' but with no forced format the ND pixels are not shown.

**Comment by berniejconnors** [comment]
> @berniejconnors We'll see if the PR is accepted. Also I noticed you had some default things exposed, I'm not sure if this was intended or not. The 2017 test dem also seems 'broken' but with no forced format the ND pixels are not shown.

@roya0045 it is okay for our REST services to be exposed. Our mandate is to provide map services to the public.  Feel free to use our services in your testing.

P.S. I am very impressed with the response to my very first QGIS bug report.

**Comment by roya0045** [comment]
@berniejconnors Response to tickets will varying depending on many factors, I felt like trying to help on this one as it will affect many users and can be a nice user experience improvement, whitout too much code to rework. I also like the approach of NB in regards to open geospatial data as opposed to other provinces.

**Comment by berniejconnors** [comment]
Thanks. We appreciate the recognition of our open services and open data. https://www.snb.ca/geonb

**Comment by berniejconnors** [comment]
@roya0045 will it be possible to have this bug fix included in the 3.18 release in February?

**Comment by roya0045** [comment]
At this point this is out of my control. I'd say maybe.
