### ISSUE TITLE
Offline editing plugin Layers and non-geometric tables are sometimes not exported to offline project

### ISSUE THREAD

**Issue by Amphibitus** [qgis/QGIS#41133]
Describe: 
**Offline editing plugin Layers and non-geometric tables are sometimes not exported to offline project**

How to Reproduce: 
**If i export a project to a OFFLINE Geopackage only some layers are exported. I try it with diffrent projects**

QGIS and OS versions: 
**QGIS since 3.14 on Windows 10 on Debian Server** 

Additional context:

This is related only to geopackage.
if it is forced to use spatialite this does not occur.

I think it is a problem from the Offline editing plugin inside QGIS

The plugin works fine in the local directory, but some layers are created in the geopackage on a server but there are no entries in the table. There is a problem with the rights of the folder!

I disabled the oplocks option on the server and it works fine.
It looks like the offline_editing plugin opens the data.gpkg file several times during the process.

Is there any solution to keep using the oplock option continuously?

"OpLocks are made to enable simultaneous file access by multiple users while also improving performance for synchronized caches. In a synchronized cache, when a client requests a file from a server, the shared file may be cached to avoid subsequent trips over the network to retrieve it."

Also see here( https://github.com/opengisch/qfieldsync/issues/100) but i think it is a problem fom "Offline editing plugin"

**Comment by gioman** [comment]
@Amphibitus can you please add the requested info? Thanks.




**Describe the bug**


**How to Reproduce**



1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error -->

**QGIS and OS versions**



**Additional context**
