### ISSUE TITLE
project.layersAdded is emitted before layerTreeRoot is updated with new added layer.

### ISSUE THREAD

**Issue by sem-geologist** [qgis/QGIS#41135]
**project.layerTreeRoot.children is not updated before project.layersAdded is emitted**
background:
I am developing the plugin (in python), which adds dockable widget chemical/periodic table to control visibility of layers with chemical information; it parses names of layers and enables and checks the atom buttons on the widget (periodic table), and other way around (changes checked state of layers which contain element name or abreviation in TOC when pressed/depressed the button in periodic table). That's the main idea of plugin.

Being a lazy person I seek for most abstract ways to interact between the widget and the qgis TOC (that also allows to keep code small as possible). It is quite confusing that layers can be addressed as instances of different classes, which contain different sets of methods.
So for detecting and scanning the layer name, if it contains chemical meaning, I made method which is called (connected to) `project.layersAdded` signal (by `project` I mean `QgsProject.instance()`). layersAdded returns QgsRasterLayer, the type which (as far as I had investigated) has no method to see if layer is checked in TOC. This information can be acquired using layerTreeRoot methods (i.e. `findLayer()` to get the instance of `QgsLayerTreeLayer` of same layer using its `id()` method, or with `layerTreeRoot.checkedLayers()` getting the list of checked instances of  `QgsRasterLayer` and checking if added layer is in that list. This somehow does not affect if loading from project file, but during live addtion (double click or drag and drop from browser) of new layers (i need to test removing).

**How to Reproduce**

1. in python console execute this short working example:
```python
project = QgsProject.instance()
ltr = project.layerTreeRoot()

def print_project_layers_vs_ltr(layers_added):
    print("***** starting layer adding cycle ****") 
    print("what layers added:")
    print(layers_added)
    print("what project.mapLayers() sees:")
    print(project.mapLayers())
    print("what ltr.children() sees:")
    print(ltr.children())
    print("what ltr.findLayer() returns:")
    print(ltr.findLayer(layers_added[0].id()))
    print("ending layer adding cycle\n")

project.layersAdded.connect(print_project_layers_vs_ltr)
```
2. try adding the layers and see the console output, notice the missing new entries in layerTreeRoot.children(), or returned `None` with `findLayer()` method using obtained id of new layer.
3. Try to add more than two layers at once (i.e. dragging and dropping two layers from browser). take a note that only the last layer from two (or more) got not registered in `layerTreeRoot`.
4. If manually we try to execute in python interpretor `ltr.children()`, we see that the returned list is fully updated.

4th observation leads to conclusion that layerTreeRoot is updated after emision of `project.layersAdded` signal.

If there is no fix possible I would appreciate suggestion for work around.

**QGIS and OS versions**
QGIS version | 3.16.1-Hannover | QGIS code branch | Release 3.16
-- | -- | -- | --
Compiled against Qt | 5.12.9 | Running against Qt | 5.12.9
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.33.0 | Running against SQLite | 3.33.0
PostgreSQL Client Version | 12.3 | SpatiaLite Version | 5.0.0
QWT Version | 6.1.5 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 7.1.1 | Running against PROJ | Rel. 7.1.1, September 1st, 2020
OS Version | KDE neon User Edition 5.19
Active python plugins | plugin_reloader; MetaSearch; processing; db_manager

OS is rather little relevant as I run this in conda environment.

**Additional context**

~~Optional API inconsistency spotted: project instance contains signal called `layersAdded` which suggest that signal returns list of layers being added, while in real it returns single layer Added encapsulated in list. It behaves same if loading project or adding layers live, I could not found a way to make it emit more than one layer at time. If that is a case it should be renamed with next major version and return layer not encapsulated in list.~~ *(irrelevant)*

BTW, the conda way of installing qgis is the best thing ever which solves so many conflicting library problems on linux and allows to use conflicting plugins.

**Fix**
The problem with above is due to misunderstanding how layer loading works. This is correct behavior of `layersAdded` signal of project instance. There is similar signal called `legendLayerAdded` which emits after `layerTreeRoot` is updated with new layers, and so using that instead of `layersAdded` fixes the problem.

**Comment by gioman** [comment]
@sem-geologist you should ask in the developers mailing list.

**Comment by nicogodet** [comment]
I also noticed this behavior when developing a plugin.

I update a layer list based on their visibility in map canvas. 
`QgsProject.instance().layerTreeRoot().findLayer(QgsProject.instance().mapLayersByName(layer.name())[0].id()).isVisible()`
When i call this function on signal layersAdded, `findLayer` can not find added layer.

**Comment by roya0045** [comment]
Have you tried with https://github.com/qgis/QGIS/blob/82d3b0f3eec2118ed5ee4ed9b0547df68d83fa75/src/core/project/qgsproject.h#L1816 or layerWasAdded?

**Comment by nicogodet** [comment]
I will try legendLayersAdded.

I tried layersWasAdded but same.

**Comment by sem-geologist** [comment]
Thanks to all, I tried with `legendLayerAdded` and this should work as intended. It sheds light with above example (connecting example function to `legendLayerAdded` signa instead of layersAddedl). It behaves differently when loading project. With project loading `layerTreeRoot` is populated fully with layers (as children or grand,grand...children) before emitting `legendLayerAdded` layer by layer where when drag-dropping few layers from browser it interleaves layerTreeRoot expansion in-between legendLayerAdded events with correct precedence (legendLayerAdded is correctly emitted later than adding `LayerTreeNode` to `layerTreeRoot`. 
Sorry for this issue as it looks that is my own fault not getting enough into documentation. But I am happy this will help @nicodet as well, so at least it is not an empty attempt.

BTW `layerWasAdded` is marked (in API documentation) to be deprecated, it should not be used at all, particularly for new plugins. While I find `legendLayerAdded` to sound more correct to what it does (singular form) I still can't understand why it encapsulates returned layer object inside python list.

**Comment by gioman** [comment]
@sem-geologist closing then?

**Comment by sem-geologist** [comment]
lets wait a moment for @nicogodet , Also I would like to add fix at top, so if someone would get on the same issue could find the solution.

**Comment by roya0045** [comment]
Yeah it seems the name of the signal is mostly for internal handling and integration rather than external use, but changing it would cause API breakage, though I'm glad the legend signal works fine, it should also be more appropriate as it wont trigger with layers not added to the legend.

**Comment by nicogodet** [comment]
You can close. Thanks @roya0045.

**Comment by roya0045** [comment]
@nicogodet Glad I could help!
