### ISSUE TITLE
Setting high map units values in draw effect properties cause lockup/crash. (Was: Symbology Draw Effects causes crash)

### ISSUE THREAD

**Issue by Llaves** [qgis/QGIS#41149]
In a vector layer with categorized symbology, attempting to change the units for a drop shadow effect causes Qgis to become unresponsive and/or crash.

**How to Reproduce**

Unpack the attached files and load the project.
[EffectsCrash.zip](https://github.com/qgis/QGIS/files/5861392/EffectsCrash.zip)
Open the properties for the NMCounties layer (the only layer).
Open the Symbology tab.
Select the styling for category Taos
Click on symbol
Click on Simple Fill
Click on the Draw Effects star icon
Select drop shadow
Set Offset units to map units
Set Blur radius units to map units
Type 5000 into the value for the offset
Type 5000 into the value for blur radius
at this point qgis freezes on my system
The map is in UTM13, which is in meters, so a blur offset and radius of 5000 = 5km is perfectly reasonable for this map

**QGIS and OS versions**
3.16.2 and 3.10.5 both exhibit this behavior

QGIS version | 3.16.2-Hannover | QGIS code revision | f1660f9da5
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | latlontools; MemoryLayerSaver; PluginLoadTimes; plugin_reloader; vector_tiles_reader; db_manager; processing

**Additional context**

Windows 10, 64 bit

**Comment by roya0045** [comment]
If it crashes do you have a stack trace that you could share?

**Comment by Llaves** [comment]
Qgis becomes unresponsive, consuming nearly 100% of CPU,but it doesn't actually crash and produce a stack trace. I am attaching a minidump produced by Sysinternals Procdump. I hope that's useful.

[qgis-bin.exe_210123_220239.zip](https://github.com/qgis/QGIS/files/5861605/qgis-bin.exe_210123_220239.zip)

**Comment by roya0045** [comment]
Yeah I also noticed that higher map to scale values were an issue. No clues why this is the case. But this only happens when setting the value. Rendering is fine afterward.

**Comment by roya0045** [comment]
I think a more fitting title for this ticket would be "Setting high map units values in draw effect properties cause lockup/crash"

Though now I'm curious as to why we have 'Map Units' in this and 'Meters at scale' for symbols, the latter is fine with high values...

**Comment by roya0045** [comment]
I also have a feeling that the issue may be related to the preview rather than the operation itself.

**Comment by Llaves** [comment]
Having tested and confirmed @roya0045 's point that it's large values and not the units, I've changed the title as he suggested.

I'm not sure it's strictly a preview issue. After setting the blur radius to a large value (100) in millimeters and then waiting a long time for the program to respond, I get long (minutes) delays after I click OK at each stage to get back to the main interface. I now tried to open the properties dialog again and the program becomes unresponsive.

**Comment by roya0045** [comment]
@Llaves The render behaves fine on the map canvas right? If the slowdown only occurs in the dialog this confirms that previews may be the cause of the slowdown as map rendering is fine.

On my short test the map was fine. Now to see the real issue we would need to check execution time of each functions, and I don't have the tool for this and my current dev build is quite limited at the moment.

**Comment by Llaves** [comment]
For the transform effect, setting large values does not hang the program, but there seems to be a hard limit of -999. This doesn't make sense in map units as that's 1km for a meter CRS, which is not much for a country-scale map.
I was able to set the drop shadow offset to 5000 map units, but it has been hanging for 5 minutes now trying to set the blur radius to 5000 map units, so I can't really say if it renders.

**Comment by Houska1** [comment]
It seems I've also been caught by this, with a roads layer (lines), categorical renderer with each of 5 categories having an outer glow of 2-5m and a small (~1m) blur radius. 3.16.1 and .2 Windows.  I had some complex data-driven calculations in the rendering and blamed those (and have rolled back that change so can't test sorry), but seems to fit this issue description to a T.

**Comment by roya0045** [comment]
Though even in mm with high values I also get similar behaviour, so it might not be unique to the meters at scale after all. The conversion doesn't help but fundamentaly I think simply adding a render where the limit is out of bound (for the preview or in general) may be the issue.

**Comment by roya0045** [comment]
Got this trace using 600mm shadow


QTextOption::wrapMode :
QTextOption::wrapMode :
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QRasterPaintEngine::rasterBuffer :
QRasterPaintEngine::rasterBuffer :
QRasterPaintEngine::fill :
QPaintEngineEx::draw :
QPaintEngineEx::drawPath :
QPicture::exec :
QPicture::play :
QPainter::drawPicture :
QgsPaintEffect::sourceAsImage :
QgsGlowEffect::draw :
QgsEffectStack::draw :
QgsPaintEffect::end :
QgsVectorLayerJoinInfo::setEditable :
QgsMapRendererParallelJob::renderLayerStatic :
QgsArchive::zip :
QgsImageOperation::overlayColor :
QgsMapRendererParallelJob::cancelWithoutBlocking :
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
