### ISSUE TITLE
dxf project export crash

### ISSUE THREAD

**Issue by Francisco-Belmonte** [qgis/QGIS#41157]
bug: QGIS 3.10.9 crashes when trying to export to dxf a project
OS versions: Windows 10 64bit  

How to Reproduce:

    Go to 'Project'-> Import/Export -> Export Project to DXF.
The program starts thinking and after a few second, crashes giving the error below:
    
Crash ID: 7577d48518c05c780b6863b24875154ceb076fd7

Stack Trace

QgsMarkerSymbolLayer::scaleMethod :
QgsDiscoverRelationsDialog::trUtf8 :
QgsDiscoverRelationsDialog::trUtf8 :
QgisApp::dxfExport :
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.10.9-A Coru�a
QGIS code revision: bf47e9d3e1
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

**Comment by gioman** [comment]
@Francisco-Belmonte please add the requested infos, as requested in the report an issue template. Please also try with a new QGIS profile, if the problem persist attach a sample project+data.



**Describe the bug**


**How to Reproduce**



1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error -->

**QGIS and OS versions**



**Additional context**

**Comment by Francisco-Belmonte** [comment]
updated report.

Thanks

**Comment by gioman** [comment]
> updated report.

@Francisco-Belmonte have you tried a new QGIS profile?

Can you please attach the offending DXF?

**Comment by gioman** [comment]
@Francisco-Belmonte also update your 3.10 installation, 3.10.9 is obsolete.

**Comment by Francisco-Belmonte** [comment]
> 
> 
> > updated report.
> 
> @Francisco-Belmonte have you tried a new QGIS profile?
> 
> Can you please attach the offending DXF?

I´m sorry, but no dxf file is created. QGIS simply ends without exporting anything.

**Comment by gioman** [comment]
> I´m sorry, but no dxf file is created. QGIS simply ends without exporting anything.

@Francisco-Belmonte sorry I meant the other way around: attach the data you are trying to export to a DXF.

**Comment by Francisco-Belmonte** [comment]
> @Francisco-Belmonte have you tried a new QGIS profile?

You got it!!. 
Creating a new profile, everithing works now. 
Any way to fix default profile to work again?
THANKS

**Comment by gioman** [comment]
>  Any way to fix default profile to work again?

the problem is probably caused by a 3rd party plugin, you must remove them, re-install them one by one and test what is the offending one. The you can let the author know (not here).

**Comment by tazyeenalam** [comment]
Did anyone find out which plugin might be the cause? As I am facing the same issue. Thanks!
