### ISSUE TITLE
flatpak-version of QGIS 3.16.3 does not render jpg-raster

### ISSUE THREAD

**Issue by kk-qgis** [qgis/QGIS#41150]
**Describe the bug**

flatpak-version of QGIS 3.16.3 does not render jpg-raster
**How to Reproduce**

1. add Raster layer
2. go to the jpg-file
3. and click ok
4. in the map-canvas is no jpg-file
5. Error:Invalid Layer: GDAL provider Cannot open GDAL dataset /home/cirrusklaus/Dokumente/01-aktuelle-Projekte/233-UVS-Passau/01-Datenein-ausgang/Geodaten-von/210125-Lubis/DOP20_utm32_828500_5389500_500.jpg: libjpeg: Wrong JPEG library version: library is 62, caller expects 80 Raster layer Provider is not valid (provider: gdal, URI: /home/cirrusklaus/Dokumente/01-aktuelle-Projekte/233-UVS-Passau/01-Datenein-ausgang/Geodaten-von/210125-Lubis/DOP20_utm32_828500_5389500_500.jpg

**QGIS and OS versions**

QGIS version | 3.16.3-Hannover | QGIS code revision | 94ac9f21
-- | -- | -- | --
Compiled against Qt | 5.15.2 | Running against Qt | 5.15.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.32.1 | Running against SQLite | 3.32.1
PostgreSQL Client Version | 12.2 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.5 | QScintilla2 Version | 2.11.6
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | KDE Flatpak runtime
Active python plugins | QuickMultiAttributeEdit3; polystrip; AnotherDXF2Shape; Serval; qfieldsync; db_manager; processing

**Additional context**

It is no problem to load the aerial image in the tiff-format

**Comment by gioman** [comment]
@kk-qgis see https://github.com/qgis/QGIS/issues/39912#issuecomment-723996266
