### ISSUE TITLE
CRITICAL Qt : QXcbConnection: Error message while opening/closing Plugin Manager

### ISSUE THREAD

**Issue by SrNetoChan** [qgis/QGIS#41154]
**Describe the bug**

The following error message is showed when using the Plugin Manager:
2021-01-25T02:06:17     CRITICAL    Qt : QXcbConnection: XCB error: 3 (BadWindow), sequence: 1666, resource id: 18877555, major code: 40 (TranslateCoords), minor code: 0

I can only **reproduce the error on the very first start of a fresh installation o QGIS** on Linux. The next times I start QGIS, it no longer happens.

Was not able to reproduce it on Windows 10

**How to Reproduce**

1. Install QGIS on a clean Linux machine
2. Open QGIS
3. Open the Plugin Manager
4. Activate all core plugins
5. Close the plugin manager
6. See the error

**QGIS and OS versions**

QGIS version | 3.17.0-Master | QGIS code revision | fba5093f18
-- | -- | -- | --
Compiled against Qt | 5.12.8 | Running against Qt | 5.12.8
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
Compiled against PDAL | 2.0.1 | Running against PDAL | 2.0.1 (git-version: Release)
PostgreSQL Client Version | 12.5 (Ubuntu 12.5-0ubuntu0.20.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Ubuntu 20.04.1 LTS | This copy of QGIS writes debugging output.
Active python plugins | db_manager; processing; MetaSearch

**Additional context**

**Comment by gioman** [comment]
@SrNetoChan how do you install master on Ubuntu 20.04?

**Comment by roya0045** [comment]
Isn't that just a debug message for debug build such as master/nightly.

**Comment by SrNetoChan** [comment]
@roya0045 maybe you are right. I am not familiar with these messages. If someone confirms that this is not actually as critical as the message says we can just close it.

**Comment by gioman** [comment]
@SrNetoChan on master you get a ton of message like

`Qt: QXcbConnection: XCB error: 3 (BadWindow), sequence: 64852, resource id: 36252125, major code: 40 (TranslateCoords), minor code: 0`

in the message bar, not sure why but they will never go then in the releases.

**Comment by gioman** [comment]
I think is safe to close.

**Comment by SrNetoChan** [comment]
> @SrNetoChan how do you install master on Ubuntu 20.04?

Using this on the sources file:

https://qgis.org/ubuntu-nightly

**Comment by SrNetoChan** [comment]
> @SrNetoChan on master you get a ton of message like
> 
> `Qt: QXcbConnection: XCB error: 3 (BadWindow), sequence: 64852, resource id: 36252125, major code: 40 (TranslateCoords), minor code: 0`
> 
> in the message bar, not sure why but they will never go then in the releases.

So, this is never showed to the end user?even so, if they are not that important, I wonder why the critical error message bar, and not just a warning.

**Comment by gioman** [comment]
> So, this is never showed to the end user?

no, they only show on master.

**Comment by nyalldawson** [comment]
> not sure why but they will never go then in the releases.

They are qt warnings -- sometimes they reveal real bugs, other times they are noise. But we show them in the debug builds just in case they are revealing real problems.

**Comment by SrNetoChan** [comment]
My bad. I guess I have never turned debug mode when I compile master.

In that case, it seems like developers will know what to do with it this messages, and there is no need fill the bug tracker with it.

Can someone close this? I don't have permission for that.
