### ISSUE TITLE
Crash reprojecting a global layer into a local CRS

### ISSUE THREAD

**Issue by GAM386** [qgis/QGIS#41151]
## User Feedback

Opening a project with an OSM Standard Map.  Project file attached.  QGIS crashes with this project every time, and it first did so before I could finalize the location.  I was trying to get to an area on the US Air Force Academy N of Colorado Springs, CO, USA.  Thank you.

## Report Details

**Crash ID**: [3c320693e393fff880da22d61499b7ac39ba280a](https://github.com/qgis/QGIS/search?q=3c320693e393fff880da22d61499b7ac39ba280a&type=Issues)

**Stack Trace**
<pre>
memcpy_repmovs memcpy.asm:114
QgsWmsProvider::readBlock qgswmsprovider.cpp:929
QgsRasterDataProvider::block qgsrasterdataprovider.cpp:201
QgsSingleBandColorDataRenderer::block qgssinglebandcolordatarenderer.cpp:62
QgsBrightnessContrastFilter::block qgsbrightnesscontrastfilter.cpp:118
QgsHueSaturationFilter::block qgshuesaturationfilter.cpp:123
QgsRasterResampleFilter::block qgsrasterresamplefilter.cpp:162
QgsRasterProjector::block qgsrasterprojector.cpp:810
QgsRasterIterator::readNextRasterPartInternal qgsrasteriterator.cpp:130
QgsRasterDrawer::draw qgsrasterdrawer.cpp:60
QgsRasterLayerRendererFeedback::onNewData qgsrasterlayerrenderer.cpp:60
QgsWmsProvider::draw qgswmsprovider.cpp:878
QgsWmsProvider::readBlock qgswmsprovider.cpp:908
QgsRasterDataProvider::block qgsrasterdataprovider.cpp:201
QgsSingleBandColorDataRenderer::block qgssinglebandcolordatarenderer.cpp:62
QgsBrightnessContrastFilter::block qgsbrightnesscontrastfilter.cpp:118
QgsHueSaturationFilter::block qgshuesaturationfilter.cpp:123
QgsRasterResampleFilter::block qgsrasterresamplefilter.cpp:162
QgsRasterProjector::block qgsrasterprojector.cpp:810
QgsRasterIterator::readNextRasterPartInternal qgsrasteriterator.cpp:130
QgsRasterDrawer::draw qgsrasterdrawer.cpp:60
QgsRasterLayerRenderer::render qgsrasterlayerrenderer.cpp:274
QgsMapRendererParallelJob::renderLayerStatic qgsmaprendererparalleljob.cpp:265
QtConcurrent::MapKernel<QList<LayerRenderJob>::iterator,QtConcurrent::FunctionWrapper1<void,LayerRenderJob & __ptr64> >::runIteration qtconcurrentmapkernel.h:69
QtConcurrent::MapKernel<QList<QgsImageOperation::ImageBlock>::iterator,QgsImageOperation::ProcessBlockUsingPixelOperation<QgsImageOperation::GrayscalePixelOperation> >::runIterations qtconcurrentmapkernel.h:78
QtConcurrent::IterateKernel<QList<QgsImageOperation::ImageBlock>::iterator,void>::forThreadFunction qtconcurrentiteratekernel.h:256
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.14-A Coru�a
QGIS code revision: 8374282d2a
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363
[JacksValleyVegTest_20210124.zip](https://github.com/qgis/QGIS/files/5862599/JacksValleyVegTest_20210124.zip)

**Comment by gioman** [comment]
@GAM386 the layer is global (3857) and your project is in a "local" CRS (is a UTM one for north america), there is a limit to how much you can reproject a global CRS into a local one. Said that QGIS should not crash, but anyway... no crash here on 3.16 on Linux (it just do not show anything, but as as soon you zoom in or change the project to 3857 it shows fine).

**Comment by GAM386** [comment]
Thank you.  

- Yes, I’ve found that what crashes with QGIS on my win PC does not crash on my Linux laptop.  Is there something about windows I can set so that it doesn’t choke on QGIS so often? 

- I’ve already created a new profile, that made no difference.

- the program into which I intend to import my QGIS output (OCAD) seemed not to accept EPSG:3857 to-date, hence my use of EPSG:32613.  OCAD accepts EPSG:3857 now, so I’ll switch my default in QGIS to that projection.

Galen

**Comment by roya0045** [comment]
You are running out of memory due to the reprojection of the WMS. Zoom in and then reproject and its fine, just don't try to view the whole world with a small crs.

**Comment by gioman** [comment]
> s there something about windows I can set so that it doesn’t choke on QGIS so often?

@GAM386 if it a memory consumption issue (because I guess that reprojecting a lot of data means also a lot of memory usage) then windows is junk compared to Linux.

**Comment by GAM386** [comment]
Thanks – trouble is, OSM in QGIS starts on the whole world, so I don’t have any choice… it crashes on trying to zoom in to a reasonable area.

**Comment by gioman** [comment]
> trouble is, OSM in QGIS starts on the whole world

you can set QGIS to create new projects in 3857 and/or to have new layers added as disabled.

**Comment by GAM386** [comment]
Thank you, that seems to work nicely.

**Comment by gioman** [comment]
@GAM386 no crashes here on Windows too (a Windows 10 VM with 8GB of RAM) maybe you just have a crashy installation/system, see also https://github.com/qgis/QGIS/issues/41077#issuecomment-762912211

**Comment by roya0045** [comment]
I also had no crash, I'd classify as a local issue.
