### ISSUE TITLE
Better handling of duplicated FIDs in GPKGs

### ISSUE THREAD

**Issue by enzedrailmaps** [qgis/QGIS#41156]
FID field is autogenerated as apparently requiring to be UNIQUE yet each table that contains a FID field generates its own sequence of field values that are not globally unique.

When data is pasted between two tables that have the same field structure and is different data, yet the FID values can be duplicated as for each table the FID is only unique within that table, therefore duplication is entirely possible. The table/layer management built into Qgis has no means of resolving these conflicts, resuilting in data loss as the pastes are rejected with the error message and cannot be posted in the layer.

The suggested resolution would be to discard incoming FID values from a paste and generate new ones as the FID value in any case has no relevance to the end user and only exists for apparent data provider requirements.

This issue is specific to local file Geopackage layer format.

**Comment by elpaso** [comment]
Can you please describe the steps to reproduce in details and attach a sample project and data? That would make it easier and faster for a developer to test on her own machine.

**Comment by gioman** [comment]
I  really feel that this issue has been reported in other tickets, and possible solutions discussed there for example https://github.com/qgis/QGIS/issues/38855 and also tickets about processing (as far as I remember). Trying to find them.

**Comment by gioman** [comment]
> Can you please describe the steps to reproduce in details and attach a sample project and data? That would make it easier and faster for a developer to test on her own machine.

create an empty gpkg

make a copy of it

digitize features in both the gpkgs

try copy/paste features from one gpkg to the other

**Comment by roya0045** [comment]
I agree with @gioman this is not new and not a bug if you copy an attribute that should be unique but isn't. This is a know issue/quirk of gpkg and fixes are up to the user at this point.

**Comment by gioman** [comment]
> This is a know issue/quirk of gpkg and fixes are up to the user at this point.

yeah... but this does not really help us make the users like GPKGs... :(

**Comment by roya0045** [comment]
Even devs don't like it. The feature request is quite valid, but this is not a bug IMO. I usually just delete all values and  let it repopulate on such occasions.

**Comment by m-kuhn** [comment]
There was also a discussion about allowing the fid to be hidden from the gui if it's called `_hidden_fid`. This will make it an implementation detail the ogr provider can handle internally in a safe way.

**Comment by gioman** [comment]
> Trying to find them.

one of the relevant ones: https://github.com/qgis/QGIS/issues/36378

**Comment by Bernd-Vogelgesang** [comment]
> I agree with @gioman this is not new and not a bug if you copy an attribute that should be unique but isn't. This is a know issue/quirk of gpkg and fixes are up to the user at this point.

Maybe you are "technically" right that this is no bug. But when this "feature" renders the usage of geopackage useless for work that 40-year-old data formats do without a glitch, and which users are performing in their everyday life for decades, than I really have to scratch my head.
And I never found anywhere a warning stating "Sorry, you can't just not copy/paste features from one layer to another without the risk of loosing your data"

**Comment by elpaso** [comment]
> > Can you please describe the steps to reproduce in details and attach a sample project and data? That would make it easier and faster for a developer to test on her own machine.
> 
> create an empty gpkg
> 
> make a copy of it
> 
> digitize features in both the gpkgs
> 
> try copy/paste features from one gpkg to the other

This works for me, I think you are missing a step (save) before copy/paste.

**Comment by elpaso** [comment]
@gioman I cannot reproduce the issue on master with GDAL 3.2.0.

The unique constraint on the `fid` is correctly identified and handled by the code, there are checks in place that were explicitly written to handle this situation.

The expected behavior (and I checked with a debugger that it is working correctly) is that when the features are pasted in the destination layer any `fid` that is not unique is replaced with the default provider's value `Autogenerate` (for GPKGs) and when the destination layer is saved they are treated like new features (and Autogenerate becomes the new `fid` for the pasted features).

According to my analysis:
- this would be a bug and not a feature request because it's supposed to work out of the box
- I cannot reproduce, so please fill in the gaps in the description **and attach a failing project and data** 

The claim:

> The table/layer management built into Qgis has no means of resolving these conflicts,

is wrong because we have code and tests in place to handle this case.

The reason why I was asking for a sample project and data are exactly aimed to prevent this kind of waste of time: I've spent more than one hour without being able to reproduce the issue, I've run it through a debugger, inspected the destination DB and checked for any inconsistency in the `fid` values of the destination table without finding any evidence of misbehavior.

**Comment by gioman** [comment]
> @gioman I cannot reproduce the issue on master with GDAL 3.2.0.

@elpaso re-checking the procedure now.

**Comment by gioman** [comment]
> @gioman note that GDAL version matters: [OSGeo/gdal#2622](https://github.com/OSGeo/gdal/pull/2622)

@elpaso confirmed ok on qgis master with gdal 3.3

**Comment by roya0045** [comment]
I guess this should be closed then.  Thanks @elpaso !

**Comment by gioman** [comment]
Is this also fixed then? https://github.com/qgis/QGIS/issues/36378

**Comment by elpaso** [comment]
@gioman can we make it mandatory for users to specify the version of QGIS, GDAL and the O.S. in the tickets?

**Comment by gioman** [comment]
> @gioman can we make it mandatory for users to specify the version of QGIS, GDAL and the O.S. in the tickets?

@elpaso I have already looked a way to make the page to file an issue act like a form, with mandatory fields, but so far haven't found a way. I think that actually is not supported by GH.

**Comment by gioman** [comment]
> Is this also fixed then? #36378

answering to myself: no.

**Comment by enzedrailmaps** [comment]
Handling f the same type of field called ogr_fid in spatialite manages 
to automatically update in the limited experience I have with that format.
