### ISSUE TITLE
QgsClassificationMethod.setLabelPrecision causes crash

### ISSUE THREAD

**Issue by ChrisWGeorge** [qgis/QGIS#41165]
**Describe the bug**

The setLabelPrecision statement in the attached script causes QGIS to crash, I think when triggerRepaint is executed.  If the setLabelPrecision statement is removed all is well.

**How to Reproduce**

1. Unzip rendertest.zip 
1. Correct path to channel.shp in rendertest.py
2. Run rendertest.py

**QGIS and OS versions**

QGIS version | 3.10.13-A Coruña | QGIS code revision | 311f3bbade
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | plugin_reloader; QSWAT3; QSWAT3_64; QSWATPlus3_64; remotedebug; db_manager; MetaSearch; processing

[rendertest.zip](https://github.com/qgis/QGIS/files/5867193/rendertest.zip)

**Additional context**

**Comment by ChrisWGeorge** [comment]
I have since discovered that if you comment out the setLabelPrecision statement, run it once (which is OK), renove the layer just added, and run it again it crashes.

**Comment by roya0045** [comment]
Because it encounters an invalid pointer. If you use invalid pointers it will crash. It should be an easy fix though.

**Comment by ChrisWGeorge** [comment]
If the Feedback label means I should respond, I don't understand.  If layer.triggerRepaint() causes a crash then the invalid pointer is not in my code: the previous line, which executes without any problem, is layer.setOpacity(1), so layer is not nonexistent.

**Comment by gioman** [comment]
> If the Feedback label means I should respond, I don't understand. If layer.triggerRepaint() causes a crash then the invalid pointer is not in my code: the previous line, which executes without any problem, is layer.setOpacity(1), so layer is not nonexistent.

@ChrisWGeorge ask in the developers mailing list too.

**Comment by roya0045** [comment]
I have got no issues using on their own.
```python
method = QgsClassificationJenks()
precision = method.labelPrecision()
method.setLabelPrecision(precision-1)
method.setLabelFormat('%1 - %2')

**Comment by ChrisWGeorge** [comment]
I did not understand the previous comment.  
1.  The crash only occurs when triggerRepaint is called, and this comment does not address that.
2.  I originally suspected that the calls of setLabelPrecision and setLablelFormat might be causing the crash, so I commented them out, but the crash still happened.  This comment reinstates them.

**Comment by ChrisWGeorge** [comment]
I have tried again on the latest LTR, 3.16.  rendertest.py still causes QGIS to crash.  If, however, the call of setLabelPrecision is removed there is no problem.

**Comment by ChrisWGeorge** [comment]
Experimenting with this further today I am unable to replicate the crash.
