### ISSUE TITLE
ImportError, undefined symbol: _ZdlPvm, version Qt_5

### ISSUE THREAD

**Issue by diegstroyer** [qgis/QGIS#41174]
**Describe the bug**

When program starts, before version logo, appears the message about can't use SIP. This error block use or install plugins and execute python console.

Error message appears after launch the program.

**Error message:**

No s'ha pogut carregar el mòdul SIP.
El suport  phyton es desactivarà

Traceback (most recent call last):
  File "", line 1, in 
  File "/usr/lib/python3/dist-packages/qgis/__init__.py", line 70, in 
    from qgis.PyQt import QtCore
  File "/usr/lib/python3/dist-packages/qgis/PyQt/QtCore.py", line 24, in 
    from PyQt5.QtCore import *
ImportError: /home/diego/.local/lib/python3.8/site-packages/PyQt5/QtCore.so: undefined symbol: _ZdlPvm, version Qt_5

Versió phyton:
3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0]

Versió del QGIS:
3.16.3-Hannover 'Hannover', 94ac9f21b8

Ruta del Python:
['/usr/share/qgis/python', '/home/diego/.local/share/QGIS/QGIS3/profiles/default/python', '/home/diego/.local/share/QGIS/QGIS3/profiles/default/python/plugins', '/usr/share/qgis/python/plugins', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/home/diego/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/dist-packages', '/usr/lib/python3/dist-packages']

**QGIS and OS versions**

Versió del QGIS | 3.16.3-Hannover | Revisió del codi QGIS | 94ac9f21b8
-- | -- | -- | --
Compilat per Qt | 5.12.8 | S'executa amb Qt | 5.12.8
Compilat per GDAL/OGR | 3.0.4 | S'executa amb GDAL/OGR | 3.0.4
Compilat per GEOS | 3.8.0-CAPI-1.13.1 | S'executa amb GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
Versió del client PostgreSQL | 12.5 (Ubuntu 12.5-0ubuntu0.20.04.1) | Versió de SpatiaLite | 4.3.0a
Versió del QWT | 6.1.4 | Versió de QScintilla2 | 2.11.2
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
Versió OS | Ubuntu 20.04.1 LTS

**Comment by roya0045** [comment]
Seems to be an install issue.

**Comment by diegstroyer** [comment]
I think that QT version is the issue, lools like it's biulded to work with qt 5.12.8, but ubuntu 20.04 have the versión 5.14.1.

I was triying to reinstall 3.10 and 3.16 and the issue persist. I also tried uninstalling python3-pyqt5 and installing a different version using pip, but version 5.12.8 does not exist, and other 5.12.* have same error.

**Comment by roya0045** [comment]
You can try to install the nightly version, master supports 5.15 at least,

**Comment by diegstroyer** [comment]
Ok, i will try it.

But now, I'm compiling 3.16 from master git and have an error related with this issue:

`/usr/share/sip/PyQt5/QtCore/qcalendar.sip:28:10: fatal error: qcalendar.h: El fitxer o directori no existeix
   28 | #include <qcalendar.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [python/CMakeFiles/python_module_qgis__gui.dir/build.make:1216: python/CMakeFiles/python_module_qgis__gui.dir/gui/sip_guipart4.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:7246: python/CMakeFiles/python_module_qgis__gui.dir/all] Error 2
make: *** [Makefile:152: all] Error 2`


When run the failed compilation binary, the message that appears is the same as precompiled package from repository and related in the first post.

**Comment by diegstroyer** [comment]
Same error in nightly versions (3.10 and 3.17).

Can't work with QGIS because python tools not work. :(

**Comment by roya0045** [comment]
This seems to be a python issue, I'm not sure why its using your local python instead of the one in QGIS.

**Comment by diegstroyer** [comment]
I don't know, QGIS 3.10 working for long time in 20.04.

**Comment by diegstroyer** [comment]
You make me in the right way!!! Thanks a lot.

Renamed local python directory and QGIS works again, I'm not sure when I created this environment, but I think that can be erased... FOREVER!!!! :P

Thanks!!

**Comment by roya0045** [comment]
@diegstroyer Glad you got this sorted out!

**Comment by ZLiu97** [comment]
> You put me in the right way!!! Thanks a lot.
> 
> Renamed local python directory and QGIS works again, I'm not sure when I created this environment, but I think that can be erased... FOREVER!!!! :P
> 
> Thanks!!

Hi, I try to fix the same issue for few days but still no luck. What did you do to solve this?

**Comment by diegstroyer** [comment]
Look at your bashrc file and locate local python environment, check first that this env is not used by another application or project, I suggest to you that comment the path in bashrc and reload variables. Then, try to launch QGIS again.

**Comment by dennisushi** [comment]
In my case, this error appeared due to importing gym before pyrep. Switching the order solved it for me.

**Comment by dennisushi** [comment]
In my case, this error appeared due to importing gym before pyrep. Switching the order solved it for me. Which indicates that this error can occur when something overrides the used qt path.

**Comment by Renbago** [comment]
Hi @diegstroyer im not prof of qt5 problem but the currently also i'm getting this problem. As u said i search the python path exc exc but i couldn't understand what should i do, could be more spesificly what should i do for  solve the problem

**Comment by diegstroyer** [comment]
Hi,

The solution is explained in previous messages, in resume: qgis is trying
to use local python environment, you need to verify that situation checkin
your bashrc file. If it's your situation (make a security copy of your
bashrc file first), comment PYTHONPATH and reload variables.

This works for me because I had and python env created for another purpose
and have no real use for nothing, and qgis was reading the bashrc path to
that environment.

El dv., 26 d’abr. 2024, 22:50, Baha Dursun ***@***.***> va
escriure:
