### ISSUE TITLE
QGIS Crashes

### ISSUE THREAD

**Issue by manishesri** [qgis/QGIS#41189]
I am trying to run a Python script on QGIS version 3.10 and every time I run the script QGIS unexpectedly crashes. Please do let me know if there are any workaround I should be following. I have attached the screenshot of the crash.
Thanks & Regards
![crash_SS](https://user-images.githubusercontent.com/59059129/105857915-c5d8e000-6010-11eb-94ce-8df0f9dd2739.JPG)

**Comment by roya0045** [comment]
Fix your script.

**Comment by gioman** [comment]
@manishesri ask in the developers mailing list (you must provide your script).
