### ISSUE TITLE
choosing predefined labels for layers

### ISSUE THREAD

**Issue by APOS80** [qgis/QGIS#41186]
**Feature description.**
In the style manager you can make symbols/labels/text. Choosing a predefined symbol for a layer is easy BUT there is no obvious way to choose to use a predefined label.

I think choosing a predfined label for your layer should  be as easy as with symbols. 

As it is now I cant find a way to use my predefined label.

**Comment by DelazJ** [comment]
Maybe I misunderstand your request but the labels you define should appear in the Label --> text tab of the layer properties (bottom widget -- if compatible with the layer type and assuming you are displaying the group/tag they belong to). The tab shown at https://docs.qgis.org/3.16/en/docs/user_manual/working_with_vector/vector_properties.html#labels-properties
