### ISSUE TITLE
running tests insider Docker does not work with tags later then 3_14

### ISSUE THREAD

**Issue by JanCaha** [qgis/QGIS#41181]
I came across this issue while working on [Processing R Provider Plugin](https://github.com/north-road/qgis-processing-r). Running the command `docker exec -it qgis-testing-environment sh -c "qgis_testrunner.sh processing_r.test_suite.test_package"` returns `ERROR: no output from the test runner! (exit code: 0)` with never release versions while working fine with older versions (it seems that anything before 3_16 works). The issue can be seen in the  [log from Travis](https://travis-ci.org/github/north-road/qgis-processing-r/builds/735898967). With 3_4 version everything works but the latest version fails with the described issue.

I did some testing and come across couple of issues in `/QGIS/.docker/qgis_resources/test_runner/qgis_testrunner.py` which I can provide details for. This cause some of the problems but not all of them. And while i got the `qgis_testrunner.py` to work, I am not able to figure out why `qgis_testrunner.sh` does not receive any output.

If possible I would like to discuss the issue and help to solve it :-)

**Comment by elpaso** [comment]
I originally developed that feature but I'm not using it anymore, IIRC @Gustry was using it in production.

Anyway, if you can provide a patch to make it work again it would be certainly very welcome.

**Comment by Gustry** [comment]
I'm indeed using it, but I haven't really tried something newer than 3.10 for now on CI (I'm still on the 3.10 LTR)
I will upgrade soon to 3.16.

@elpaso What you are using now for testing a plugin ?

**Comment by elpaso** [comment]
@Gustry nothing: I'm not currently maintaining any plugin except for the ancient ones (that never had tests).

**Comment by JanCaha** [comment]
I can provide patch for `qgis_testrunner.py` and there is also one python module (`pexpect`) missing from the docker image. These issues I can provide fixes for, without any problem.

This way the tests can be runned using command:
`python3 /QGIS/.docker/qgis_resources/test_runner/qgis_testrunner.py processing_r.test_suite.test_package`

But I have no idea how to fix `qgis_testrunner.sh` which does not work even after these fixes.

I can provide PR for the issues I found and maybe then it would be more obvious, where the issue in `qgis_testrunner.sh` is.

**Comment by JanCaha** [comment]
The basic PR is here: #41183 
It fixes the main issues.

I would also suggest changing the line in `qgis_testrunner.py`:
`sys.path.append(os.getcwd())`
to:
`sys.path.append("/tests_directory/")`.

With this change it would not be necessary to move into the directory manually. Would that makes sense?

**Comment by JanCaha** [comment]
#41230 should provide final fix for this issue.

**Comment by JanCaha** [comment]
The issue is now fixed. Today's release of qgis/qgis:latest runs the tests as expected.
