### ISSUE TITLE
OpenCL Acceleration not found on macOS

### ISSUE THREAD

**Issue by JoeyJostar** [qgis/QGIS#41182]
**Describe the bug**
When going to Options -> Acceleration I can't enable OpenCL.
Clicking the checkbox results in the generic error/warning text regarding no OpenCL compatible devices found and may need to install additional libraries. Same problem happens under QGIS 3.12

<img width="883" alt="Screen Shot 2021-01-26 at 8 21 51 pm" src="https://user-images.githubusercontent.com/78017371/105826361-c5dadf00-6014-11eb-9cf5-98ad4bcff5e4.png">

**Additional context**
Yet running QGIS 3.4 allows me to enable the acceleration and choose between options.
 
<img width="883" alt="Screen Shot 2021-01-26 at 8 22 42 pm" src="https://user-images.githubusercontent.com/78017371/105826403-cecbb080-6014-11eb-828c-efa2783f1703.png">

**QGIS and OS versions**

QGIS version | 3.16.2-Hannover | QGIS code revision | c6ac5a6052
-- | -- | -- | --
Compiled against Qt | 5.14.2 | Running against Qt | 5.14.2
Compiled against GDAL/OGR | 3.1.2 | Running against GDAL/OGR | 3.1.2
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.4
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | macOS Mojave (10.14)
Active python plugins | awap; interfacecatchment; splitmultipart; processing; db_manager; MetaSearch

**Comment by JPAbdalla** [comment]
Thank you!!! I'm only a user, but I noticed this while ago, but I was thinking that I was doing something wrong or been stupid somehow, cause I searched for it, and didn't find anything concrete and yet saw some devs using GPU on their Macs just fine (but I couldn't find their version of QGIS to compare).
