### ISSUE TITLE
Readflag FlagTrustLayerMetadata trigger bad layer in QgsProject with NETCDF

### ISSUE THREAD

**Issue by dmarteau** [qgis/QGIS#41209]
**Describe the bug**

Reading a `QgsProject` with `QgsProject.FlagTrustLayerMetadata` trigger a  `unavailable layers found` found warning.

**How to Reproduce**
With pyQgis with a project containing one netcdf layer

```
readflags = QgsProject.ReadFlags()
readflags |= QgsProject.FlagTrustLayerMetadata
​prj = QgsProject()
prj.read(os.path.join(datapath,'private/netcdfproject.qgs'),readflags)
Qgis : 1 unavailable layers found:
Qgis :  * NETCDF:"./1_16_MN_102_W_K-35-10-D_K-35-11-C.nc":elevation
=> True
```

Without flags:

```
readflags = QgsProject.ReadFlags()
​prj = QgsProject()
prj.read(os.path.join(datapath,'private/netcdfproject.qgs'),readflags)
=> True
```

In both case the layer seems to be loaded anyway:
```
prj.mapLayers()
=> {'NETCDF__1_16_MN_102_W_K_35_10_D_K_35_11_C__elevation_9cb87476_40cf_413f_81a0_23227b6c45be': <QgsRasterLayer: 'NETCDF:"1_16_MN_102_W_K-35-10-D_K-35-11-C":elevation' (gdal)>}
```

The problem occurs with any project containing NetCDF layers.

**QGIS and OS versions**

Qgis 3.16+

**Additional context**

In Qgis server this will prevent loading projects when  `QGIS_SERVER_IGNORE_BAD_LAYERS` is set to `no`

**Comment by rldhont** [comment]
`QgsDataProvider::ReadFlags` is not used in `QgsGdalProvider`. In `QgsGdalProviderMetadata::createProvider`, the `readflags` has not to be passed to the `QgsGdalProvider` constructor. The third parameter in the `QgsGdalProvider` provider is a boolean to activte raster update. So if `readflags` is not empty, the update parameter becomes true and the `QgsGdalProvider` try to get update capabilities, if it has not update capabilities like for NETCDF file, the provider is invalid.
