### ISSUE TITLE
My QGIS lacks processing toolbox

### ISSUE THREAD

**Issue by Icaro1301** [qgis/QGIS#41205]
Hi,
I downloaded QGIS on my work PC and in the toolbar I cannot find the toolbox "processing" and the tools for analysis (I am trying to attach a print).
Conversely, in the same QGIS on another PC I can find this toolbox.
  
Can you help me to solve this unfortunate and strange problem? 

![QGIS](https://user-images.githubusercontent.com/78080657/105979587-25c49a80-6094-11eb-822f-178ab097b907.png)

**Comment by Gustry** [comment]
Go in your plugin manager and enable the "Processing plugin".
It should be ok. Reopen if necessary.

**Comment by Icaro1301** [comment]
Thank you! it works 👍
