### ISSUE TITLE
"QGIS3.10.app" can't be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by brad-nickerson** [qgis/QGIS#41203]
Please help.  I also received the same message after downloaded and installing QGIS 3.16.  There is no "Open" option on the pop-up error window.  I am able to run QGIS3.8.app.  
<img width="421" alt="QGIS3 10app_error" src="https://user-images.githubusercontent.com/5037912/105970377-b0d76d80-605f-11eb-82ec-80f05612bfd0.png">
Additional note in the pop-up window says "This software needs to be updated.  Contact the developer for more information."  I am running macOS Catalina version 10.15.7.  Is there some action I can take to overcome the inaccessibility of later versions of QGIS?  Any help will be appreciated.

**Comment by roya0045** [comment]
https://github.com/qgis/QGIS/issues/34018#issuecomment-578186707

**Comment by Gustry** [comment]
It would be nice I think if someone having enough write permissions can **pin** the related ticket. It would stay at the top of the list.

**Comment by roya0045** [comment]
@Gustry just a dedicated element in the issue creation list. Though people don't always read the prefilled template...

**Comment by gioman** [comment]
> @Gustry just a dedicated element in the issue creation list. Though people don't always read the prefilled template...

@Gustry @roya0045 I have in mind a deep refactoring of the https://github.com/qgis/QGIS/issues/new/choose page, problem is that is not clear at all to me (and others I have asked) if/how  is possible to customize it.
