### ISSUE TITLE
CRS fails to get propagated in raster processing from temporary (memory) layer

### ISSUE THREAD

**Issue by Houska1** [qgis/QGIS#41214]
QGIS 3.16.3 OSGeo4W

1. Start with saved (tif) raster _Input_ with CRS set. 
2. Apply a raster processing operation; output a temporary (memory) layer _Temp1_. So far, so good, that layer's CRS is correctly set.
3. Apply a raster processing operation to _Temp1_. to generate _Temp2_. Whether or not _Temp2_ is saved to disk or temporary (memory), its CRS is undefined until set manually via right clicking in the layer tree. 

_Temp2_ is displayed properly on the map (since it defaults to project CRS on display), but further processing on it chokes since its CRS is undefined.

In case it matters, my project and layer CRS are EPSG:2951 (mentioning since a lot of ballpark transforms are used vs 3857, 4326, and more standard UTM CRSes). The raster processing I've used are `gdal:sieve` and `grass:r.neighbors`.

**Comment by gioman** [comment]
@Houska1 it was a GRASS/Processing issue that has been fixed recently.

**Comment by gioman** [comment]
https://github.com/qgis/QGIS/pull/40837
