### ISSUE TITLE
Geojson files in browser always have a 'polygon'-icon symbol

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS#41234]
It's tiny, but the the QGIS browser panel tries to see which kind of geometry is in every datatype: you see a point symbol if it is a point shapefile etc etc.

With geojson files, it looks like it always shows the polygon symbol:

![Screenshot-20210128112050-319x201](https://user-images.githubusercontent.com/731673/106124003-e614b600-615a-11eb-9770-e33254424fe4.png)

although both files are points there.
To check: put zip below somewhere (either with or without unzipping)

[test.zip](https://github.com/qgis/QGIS/files/5886414/test.zip)

then browse to that folder.

Not sure how the 'type'-testing normally is done, but given that almost all geojsons have just one type in them, it looks like peeping in it and check first available features seems possible?
Or is there another reason for this behaviour?

**Comment by gioman** [comment]
@rduivenvoorde duplicate of https://github.com/qgis/QGIS/issues/40980 ?

**Comment by gioman** [comment]
https://github.com/qgis/QGIS/issues/17347#issuecomment-495725656

**Comment by rduivenvoorde** [comment]
Argh, yes. Thank Giovanny I searched for geojson, because I thought this was only geojson related...

Setting "Check file contents" helps :-)
