### ISSUE TITLE
Invalid (constraint-violating) childeren can be saved

### ISSUE THREAD

**Issue by koenigherford** [qgis/QGIS#41233]
**Describe the bug**
If you have al relation in your project with parent and child layer and enable a constraint for the child-features it's possible to save all child-features although some of them are invalid.

In my sample dataset my constraint expression is "data" ='correct_data' and "enforce expression constraint" is checked.

![grafik](https://user-images.githubusercontent.com/28433436/106115755-646c5a80-6151-11eb-9bf8-70bd7c026a5f.png)

If the field "data" contains constraint-violating-data the constraint recognizes this and changes the field colour to orange.
![grafik](https://user-images.githubusercontent.com/28433436/106116376-215eb700-6152-11eb-9188-46e703e25f8a.png)
But it's still possible to save the data, which is not expected:

![grafik](https://user-images.githubusercontent.com/28433436/106116605-64208f00-6152-11eb-9d58-a95e2825e5f4.png)

This causes bad/invalid data

Sample dataset is attached

QGIS version | 3.16.3-Hannover | QGIS code revision | 94ac9f21b8
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | changeDataSource; qfieldsync; qgis2web; quick_map_services; SpreadsheetLayers; db_manager; processing

[issue_wrong_children.zip](https://github.com/qgis/QGIS/files/5886085/issue_wrong_children.zip)

**Comment by DelazJ** [comment]
> If the field "data" contains constraint-violating-data the constraint recognizes this and changes the field colour to orange.

According to the [docs](https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/vector_properties.html#default-values), if "enforce constraints" is checked, the cell in form should display red if unmet, and not orange. So it looks like the enforce check state is not taken into account.

**Comment by koenigherford** [comment]
I think red/orange are the same according to the docs because the red cross at the end of the line shows, that the constraint is violated:
![grafik](https://user-images.githubusercontent.com/28433436/106131709-4f98c280-6163-11eb-9f3a-674007c67d92.png)

The docs say "if it does not meet all the requirements, then a yellow or red cross is displayed near the field. [...].A red cross can not be ignored and does not allow you to save your modifications until they meet the constraints. It appears when the checkbox Enforce constraint option is checked."

So the first step of check works as expected (red cross=invalid feature) but to be able to save this invalid feature is -as I think -not as expected and described by the docs...

**Comment by DelazJ** [comment]
OK. Paying more attention to the testing, I noticed that the cross color changes with the checkbox, but honestly the red cross deserves to be redder.
So yes, the hard constraint checkbox is recognized but as you mention, it doesn't prevent from saving.

**Comment by koenigherford** [comment]
It seems that it only occurs when Drag and Drop Designer in parent-layer is used and "force hide form on add feature" is checked.
![grafik](https://user-images.githubusercontent.com/28433436/106139420-b02cfd00-616d-11eb-8f15-33f1bc9bfcdb.png)

**Comment by 3nids** [comment]
I am not sure how this should be fixed.

In a standard form, it's the OK button which is disabled preventing from leaving the feature in an invalid state.

Now in an embedded form, there is no OK button. 
It is the same in the table view actually, the constraint is not checked.

In the attribute table, we could make that the delegate doesn't let you enter an invalid value.
But it's not possible in the embedded form.

The only solution I see would be to check the constraints on commit. But this is quite a big change.
Any thoughts here? ping @m-kuhn @nirvn @nyalldawson

**Comment by m-kuhn** [comment]
A concern from the first hour of implementing this.
I don't have a perfect solution ready unfortunately.

We might add some logic to prevent the user from closing the parent window while an invalid child entry could not yet be saved. However I think this won't be easy to implement, even more in a way that is straightforward for the user to handle in case of warnings.

**Comment by 3nids** [comment]
A possible solution would be:
1. display a red banner saying that leaving the form in its current state (with failing constraints) will lead to losing the pending changes
2. in `QgsAttributeForm::save`, we add a boolean option to discard saving if the constraints are not respected.

@m-kuhn what do you think?

**Comment by m-kuhn** [comment]
The banner would always be shown as long as there are failing (hard) constraints? That sounds like a transparent and feasible approach :+1: 
Only thing, I would prefer orange or yellow over red (it's more a warning than an error)

**Comment by koenigherford** [comment]
I think this will be a acceptable solution
