### ISSUE TITLE
Parent layers with invalid (constraint-violating) child-features can be saved

### ISSUE THREAD

**Issue by koenigherford** [qgis/QGIS#41239]
**Describe the bug**
If you have a relation in QGIS and a parent-layer with child-features which are violating constraints the parent feature can be saved althrough the data of the child-features is invalid.

There will be a lot of cases in daily work, where it's very important to have correct parent- and child-data together. 

There will szenarios where it's required that a parent-feature can only be saved, when all child-feature-data is valid.

This requirement of good data („all child-feature-data has to be valid“) can not be met because of the following issue:
During collecting data and (because of #41233) parent features can have child-features which do not meet the constraints/are invalid). Nevertheless you can save the data. This is a behaviour which is not expected. In my opinion a parent feature shall (optionally) always have valid child-features, which are not violating constraints.

Then you establish a constraint expression in the child-layer and check „enforce expression constraint“ and collect some features which are violating the constraint. Nevertheless saving of the parent is allowed.

For debbuging purpose i added a virtual field "mistakes" which stores the constraint-violations in a field, which is accessible from the parent-layer:
`case when  "data" = 'correct_data'  then 0 else 1 end`

In the the parent-layer there is a virtual field:
The first (`"sum_constraint_violations_of_child_features"`)  with the expression: 
`relation_aggregate(relation:= 'children', aggregate:='sum', expression:="mistakes"`
counts the mistakes/constraint-violations

I captured some "invalid" child-data:

![grafik](https://user-images.githubusercontent.com/28433436/106140016-7f999300-616e-11eb-90f6-b6639db235af.png)

Then I was able to save the parent-layer (constraint against the virtual field was not set because of another bug report (virtual layers are not updated after updating child features) following in a few minutes). 

In my opinion it is not ideal to be able to save parent features with invalid children (optionally). 

To make a workaround with auxiliary virtual-constraint-check-fields is not ideal too because 
-you will get redundant /double coinstraint checks with higher risks of invalid rules
-project gets more complicated
-the existing bug of not updating virtual fields (coming soon)

![grafik](https://user-images.githubusercontent.com/28433436/106142791-35b2ac00-6172-11eb-8f1d-8c78a5f20b30.png)

A sample data-project is attached.

**QGIS and OS versions**

QGIS version | 3.16.3-Hannover | QGIS code revision | 94ac9f21b8
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | changeDataSource; qfieldsync; qgis2web; quick_map_services; SpreadsheetLayers; db_manager; processing

[issue_parent_with_invalid_children.zip](https://github.com/qgis/QGIS/files/5887557/issue_parent_with_invalid_children.zip)

**Comment by 3nids** [comment]
To me the parent layer is independent from the children layers. I wouldn't like to prevent from adding features to a layer depending on related features on another layer.

I will reply for the other issue in the dedicated thread.

I'd suggest `won't fix` for this one, but this is maybe a personal opinion.

**Comment by gioman** [comment]
Closing for lack of feedback.
