### ISSUE TITLE
summary staistics not found in "join atributes by location" function into QGIS 3.10.5 version

### ISSUE THREAD

**Issue by edebiassi** [qgis/QGIS#41247]
![Error qgis 2](https://user-images.githubusercontent.com/78165726/106174508-df466d00-6173-11eb-9b75-5dbcafbbc1f7.png)
![Error qgis 1](https://user-images.githubusercontent.com/78165726/106174533-e66d7b00-6173-11eb-9a6a-9189ea040c07.png)

**Comment by gioman** [comment]
@edebiassi are you asking for a new feature? or are you saying that should be there and there isn't?

**Comment by edebiassi** [comment]
Deberia estar ahi y no está

**Comment by edebiassi** [comment]
it should be there and not is

**Comment by gioman** [comment]
> it should be there and not is

can you see that option in a previous QGIS version?

**Comment by gioman** [comment]
@edebiassi by the way 3.10.5 is old, you should upgrade to the latest point release regardless.

**Comment by edebiassi** [comment]
ok, I will update to a new version

**Comment by gioman** [comment]
> The issue keep in to qgis 16.3 version

@edebiassi can you elaborate? in what version you have seen/used this option?

**Comment by gioman** [comment]
> The issue keep in to qgis 16.3 version

@edebiassi or are you saying that there should be this option?

**Comment by edebiassi** [comment]
Yes, according to training manual for qgis 16.3 desktop version, it shloud be that option
![image](https://user-images.githubusercontent.com/78165726/106187222-158be880-6184-11eb-8c09-c5a0fd0f0fb2.png)

**Comment by roya0045** [comment]
Seems to be a documentation mixup.

**Comment by gioman** [comment]
@roya0045 @edebiassi the mixup that the docs should say that the tool is "join layer by location (summary)" that is only available from the Processing toolbox. "join by location" is available both from the vector menu and the Processing toolbox.
