### ISSUE TITLE
No aparece el resumen estadistico en la union por atributos Qgis 3.10.5

### ISSUE THREAD

**Issue by edebiassi** [qgis/QGIS#41245]
IMPORTANT:

Do NOT use GitHub to post any questions or support requests!
They will be closed immediately and ignored.
Questions should go to the qgis-user mailing list at https://lists.osgeo.org/mailman/listinfo/qgis-user
or other support forums such as https://gis.stackexchange.com/.

GitHub issues are for bug reports and suggestions for new features.

**Comment by gioman** [comment]
@edebiassi please file ticket in English, follow the tamplate and use the proper link https://github.com/qgis/QGIS/issues/new?assignees=&labels=Bug&template=10_bug_report.md&title=



**Describe the bug**


**How to Reproduce**



1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error -->

**QGIS and OS versions**



**Additional context**
