### ISSUE TITLE
(optionally) Save all child-layer/child-feature-changes when a parent-layer/parent-feature is saved

### ISSUE THREAD

**Issue by koenigherford** [qgis/QGIS#41246]
**Feature description.**
It would be great - especially for mobile data collection - if steps to collect data can be reduced. 

To achieve this it would be great if the user has an option in project-settings (or other places) to save all changes of child-layers /c hild-features automatically too when a parent-feature / parent-layer is saved. 

Another approach may be to have an additional button like "Save changes of parent and all child-features/layers"

Especially if you have a parent table with some relations to different child tables it may be boring for data-collectors to be forced to save data changes of every table table by table.

**Comment by signedav** [comment]
Could the transaction groups be a solution for you?
![image](https://user-images.githubusercontent.com/28384354/106291462-ee005300-624b-11eb-828d-d5bd24673cc7.png)

**Comment by koenigherford** [comment]
Oh, excuse me. Did not realize, you have implemented this already. Works perfect. Thanks
