### ISSUE TITLE
Crash while creating new features with snapping enabled

### ISSUE THREAD

**Issue by TurboGraphxBeige** [qgis/QGIS#41251]
## User Feedback

Crashed twice while moving mouse on map canvas with the "Create New Feature" tool activated, edit mode enabled on a temporary layer (line) with snapping enabled. No crash when snapping is disabled. No crash with a new profile even with snapping enabled.

## Report Details

**Crash ID**: [33463ef9cb41440af8a7e86e7a3c57849c2eb6df](https://github.com/qgis/QGIS/search?q=33463ef9cb41440af8a7e86e7a3c57849c2eb6df&type=Issues)

**Stack Trace**
<pre>
sqlite3_blob_bytes :
sqlite3_blob_bytes :
sqlite3_blob_bytes :
SASetupDefaultHooks :
DBFSetWriteEndOfFileChar :
QgsOgrFeatureIterator::fetchFeature qgsogrfeatureiterator.cpp:387
QgsAbstractFeatureIterator::nextFeature qgsfeatureiterator.cpp:63
QgsVectorLayerFeatureIterator::fetchFeature qgsvectorlayerfeatureiterator.cpp:442
QgsAbstractFeatureIterator::nextFeature qgsfeatureiterator.cpp:63
QgsPointLocator::rebuildIndex qgspointlocator.cpp:951
QgsPointLocatorInitTask::run qgspointlocatorinittask.cpp:34
QgsTask::start qgstaskmanager.cpp:83
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.16.2-Hannover
QGIS code revision: f1660f9da5
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
> No crash with a new profile even with snapping enabled.

@TurboGraphxBeige sorry I overlooked this.

**Comment by gioman** [comment]
> No crash with a new profile even with snapping enabled

@TurboGraphxBeige the culprit is likely a 3rd party plugins. Remove them one by one to find the bad one.

**Comment by TurboGraphxBeige** [comment]
> > No crash with a new profile even with snapping enabled
> 
> @TurboGraphxBeige the culprit is likely a 3rd party plugins. Remove them one by one to find the bad one.

Still crash without any plugin loaded. But then again, no crash with a new profile. 

I also noticed it is indexing when the crash occurs.

**Comment by gioman** [comment]
> Still crash without any plugin loaded. But then again, no crash with a new profile.

@TurboGraphxBeige ummm.... can you share a sample project+data?

**Comment by TurboGraphxBeige** [comment]
Well, I'm trying to reproduce the issue and now it doesn't crash anymore. It does "freeze" a few seconds then index features, but now no crash.
I guess we could close the ticket.
