### ISSUE TITLE
Grass v.to.rast.attr module crash

### ISSUE THREAD

**Issue by SammmyAhmad** [qgis/QGIS#41256]
The module dialog jus wouldn't let me enter the "Name of input vector map", when the drop-down menu appears, i select my file, and boom, it crashes.
[crash report.txt](https://github.com/qgis/QGIS/files/5891237/crash.report.txt)
[crash report.txt](https://github.com/qgis/QGIS/files/5891238/crash.report.txt)

Crash ID: 67d5a4efc951a2641dd866afbaab92163afafb22

Stack Trace

RtlRaiseStatus :
RtlUnwindEx :
_longjmp_internal :
G_fatal_error :
G_getenv :
db_read_dbmscap :
db_start_driver :
db_start_driver_open_database :
QgsGrassVectorLayer::fields :
version :
version :
QMetaObject::activate :
version :
QMetaObject::activate :
QWidgetLineControl::`default constructor closure' :
QComboBox::setCurrentIndex :
QComboBox::setCurrentIndex :
QWidgetLineControl::`default constructor closure' :
QMetaObject::activate :
QAbstractItemModel::endInsertRows :
QStandardItemModel::insertRows :
QStandardItem::insertRow :
QStandardItemModel::insertRow :
QComboBox::insertItem :
version :
QMetaObject::activate :
QComboBox::qt_static_metacall :
QMetaObject::activate :
QLineEdit::qt_static_metacall :
QMetaObject::activate :
QWidgetLineControl::finishChange :
QWidgetLineControl::internalSetText :
QComboBox::setCurrentIndex :
QComboBox::setCurrentIndex :
version :
QComboBoxPrivateContainer::eventFilter :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.10.12-A Coru�a
QGIS code revision: 75c848ffb1
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

**Comment by gioman** [comment]
@SammmyAhmad used recently this tool on Windows with no issues. Likely a local issue. Try with a new QGIS profile.
