### ISSUE TITLE
QGIS crash when adding a PostgreSQL table 

### ISSUE THREAD

**Issue by rmarzocchi84** [qgis/QGIS#41252]
## User Feedback

I try to add a PostgreSQL table from browser or DB Manager

## Report Details

**Crash ID**: [bab2a4ff4b7b406c63322cd61eea271e752e308a](https://github.com/qgis/QGIS/search?q=bab2a4ff4b7b406c63322cd61eea271e752e308a&type=Issues)

**Stack Trace**
<pre>
QBitArray::QBitArray :
QgsSymbolLayerAbstractMetadata::name qgssymbollayerregistry.h:45
QgsRuleBasedRenderer::convertFromRenderer qgsrulebasedrenderer.cpp:1304
meth_QgsRuleBasedRenderer_convertFromRenderer sip_corepart1.cpp:460453
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QMetaObject::activate :
QgisInterface::currentLayerChanged moc_qgisinterface.cpp:705
QMetaObject::activate :
QgisApp::activeLayerChanged moc_qgisapp.cpp:2124
QgisApp::onActiveLayerChanged qgisapp.cpp:661
QgisApp::handleDropUriList qgisapp.cpp:1907
QgsLayerItemGuiProvider::handleDoubleClick qgsinbuiltdataitemproviders.cpp:462
QgsBrowserDockWidget::itemDoubleClicked qgsbrowserdockwidget.cpp:179
QMetaObject::activate :
QAbstractItemView::doubleClicked :
QTreeView::mouseDoubleClickEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1606
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.13-A Coru�a
QGIS code revision: 311f3bbade
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

**Comment by gioman** [comment]
@rmarzocchi84 please try with a new QGIS profile, no 3rd party plugins installed. If the problem persist attach a dump of the offending table/layer.

**Comment by rmarzocchi84** [comment]
@gioman I confirm it is a problem of my profile. I cannot open any kind of PostGIS table without geometry (from any connection). I will try to understand if there is a plugin which create the problem andf update the issue

**Comment by rmarzocchi84** [comment]
I was lucky.. I try to disable two plugin with keywods "postGIS" and the problem seem related to GeoCatBridge plugin. I hope it can be useful to other users, I close the issue and open a issue on geocatbridge repository
