### ISSUE TITLE
Vertex Tool withdraw a vertex from a segment when it snaps a vertex to the segment in Topology Editing mode

### ISSUE THREAD

**Issue by faridcher** [qgis/QGIS#41274]
Unlike Create Feature and Trim/Extend tools, Vertex Tool withdraw a vertex from a segment when it snaps the vertex to the segment in Topology Editing mode. To reproduce, digitize two lines like below and while Topology Editing is on, try to snap the left line to somewhere along the right line; the left line snaps correctly but no vertex is created. Trying to achieve the same result with Create Feature or Trim/Extend tool, a vertex is generated at the snapped point along the right line segment; I think this should be the case with the Vertex Tool as well when Topology Editing is on.

![Screenshot from 2021-01-30 17-37-32](https://user-images.githubusercontent.com/9982519/106358690-eeb7e880-6322-11eb-84c6-c844cd91c974.png)

The Vertex Tool itself could later be used to manually add this intermediate vertex but this is sub-optimal.

Qgis 3.10.12

**Comment by gioman** [comment]
@faridcher works as expected on QGIS master on Ubuntu 20.04.

**Comment by faridcher** [comment]
@gioman have you enabled "Advanced Digitizing"?

**Comment by gioman** [comment]
> @gioman have you enabled "Advanced Digitizing"?

@faridcher yes. Please attach a sample project+data.

**Comment by faridcher** [comment]
It only happens when Advanced Digitizing is enabled. The issue persists with a new QGIS project and a new empty Linear layer inside a geopackage. Could it be QGIS version specific?

**Comment by gioman** [comment]
> Could it be QGIS version specific?

@faridcher it could, please try the latest 3.16 and/or master.

**Comment by uclaros** [comment]
> It only happens when Advanced Digitizing is enabled.



@faridcher Are you sure that snapping to segment has actually occurred and you are not accidentally snapping to common angles (90deg) though advanced digitizing?

**Comment by faridcher** [comment]
@uclaros yes, Snapping to Common Angles is off and the segment snapping marker is shown. When the Advanced Digitizing is off, it works all right. 

Current QGIS on Debian unstable is 3.10.14; I will build the master version once I got the time.

**Comment by uclaros** [comment]
I can replicate this on 3.10, but not on 3.14 nor master. I assume it has been fixed.

**Comment by gioman** [comment]
> 3.16 LTR is around the corner though!

@uclaros agree, closing? @faridcher
