### ISSUE TITLE
"Split features" causes data loss

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#41283]
QGIS master on Ubuntu 20.04

*) load a (not multi)polygon GPKG

*) split one polygon and try to save edits > 

```
Errors: ERROR: 1 feature(s) not added - geometry type is not compatible with the current layer.
  SUCCESS: 1 geometries were changed.
```

which is the first problem, because the split should generate polygon feature (not multi) so there should not be any problem in saving edits at this point

*) discard edits > one of the polygons generated by the split is lost(!)

[split_bug.gpkg.zip](https://github.com/qgis/QGIS/files/5900058/split_bug.gpkg.zip)

![Peek 2021-01-31 16-12](https://user-images.githubusercontent.com/1951107/106390218-38fe9f80-63df-11eb-9ba0-09c01cdd7405.gif)

**Comment by roya0045** [comment]
Related to/caused by #40873 ?

**Comment by gioman** [comment]
> Related to/caused by #40873 ?

@wonder-sk maybe?

**Comment by uclaros** [comment]
@gioman Your data is broken, the actual geometries are *MultiPolygons* stored in a *Polygon* layer. You can check by selecting one feature and running something like 
```python 
[f.geometry().asWkt() for f in iface.activeLayer().getSelectedFeatures()]
```
I don't know how this might have happened, or if it is a common case, but yes, it definitely should be handled better by QGIS.

**Comment by gioman** [comment]
> I don't know how this might have happened, or if it is a common case, but yes, it definitely should be handled better by QGIS.

@uclaros thanks for checking.

1) The attached layer was created by saving a postgis layer as GPKG via "save as..." and specifying that had to be of type "polygon", so if there was a mess up this was QGIS fault.

2) There should not be any data loss under no circumstance.

**Comment by uclaros** [comment]
> * The attached layer was created by saving a postgis layer as GPKG via "save as..." and specifying that had to be of type "polygon", so if there was a mess up this was QGIS fault.

can you check the geometries in the postgis layer? This is a potential bug in the *save as* routine.

> * There should not be any data loss under no circumstance.

I could not agree more!

**Comment by gioman** [comment]
> can you check the geometries in the postgis layer?

```
[f.geometry().asWkt() for f in iface.activeLayer().getSelectedFeatures()]
['MultiPolygon (((648513.94425414595752954 4096425.00260931067168713, 649102.11695312836673111 4092081.57344759441912174, 652721.6412545588100329 4092624.50209280895069242, 653400.30206107697449625 4095791.58585656061768532, 652495.42098571942187846 4096515.49071684665977955, 648513.94425414595752954 4096425.00260931067168713)))', 'MultiPolygon (((654663.88272611063439399 4094672.31302315276116133, 657243.38521641923580319 4091923.66282856138423085, 659273.15766780963167548 4095771.77310098893940449, 655890.20358215901069343 4096194.6423616954125464, 654663.88272611063439399 4094672.31302315276116133)))', 'MultiPolygon (((648419.13805620337370783 4103614.10241263126954436, 649349.92975959181785583 4111658.80213477369397879, 644164.09026928490493447 4108135.09068623185157776, 648419.13805620337370783 4103614.10241263126954436)))', 'MultiPolygon (((657482.71349646267481148 4106505.01669293642044067, 657325.62779706879518926 4112840.80656848754733801, 652351.2473162638489157 4110798.69247636804357171, 654131.55190939409658313 4105667.22629616921767592, 657482.71349646267481148 4106505.01669293642044067)))']
```




> This is a potential bug in the _save as_ routine.

![Screenshot_20210131_202405](https://user-images.githubusercontent.com/1951107/106396810-4b3e0500-6402-11eb-9347-58464113b194.png)

**Comment by uclaros** [comment]
Yikes, this is dangerous! I just checked, you can actually create a Point geopackage layer filled with MultiPolygons, by exporting from a MultiPolygon layer and selecting Point geometry, there is no restriction! This deserves a separate issue. If for some reason we want to have this versatility, we should have big warning signs when the user is about to screw things up!

**Comment by roya0045** [comment]
@uclaros weren't all geometry types always selectable in this dialog? I'm pretty sure there were never any restraints.

**Comment by gioman** [comment]
> @uclaros weren't all geometry types always selectable in this dialog? I'm pretty sure there were never any restraints.

@roya0045 I don't remember (things change very quickly at times), but thinking as a user I hoped that selecting "polygon" in that dropdown would have allowed me to save as POLYGON a layer that is defined as MULTIPOLYGON but that I knew it actually didn't had any multi part geometry. I'm expecting an error message on any other circumstance (try saving a layer with multi part geometries to a not multi layer or saving to a wrong geometry type).

**Comment by gioman** [comment]
> but thinking as a user I hoped that selecting "polygon" in that dropdown would have allowed me to save as POLYGON a layer that is defined as MULTIPOLYGON but that I knew it actually didn't had any multi part geometry

Also because of by the the "force multi-type" flag...

**Comment by uclaros** [comment]
I think that *force multi-type* should be removed and multi-types added to the drop down list. Then properly warn about incompatible combinations like multi to single or wrong geometry type.

**Comment by gioman** [comment]
> Let's move this to a different thread and keep this to the data-loss issue which is caused by the _partial save_.

@uclaros I fear that if we move this to another ticket it will not get the necessary attention.

**Comment by roya0045** [comment]
Optimally we could restrain it when existing, unsure why all the choices are there https://github.com/qgis/QGIS/blob/6387a4258590b3cad3e9fe211ebda71c30fbc410/src/gui/ogr/qgsvectorlayersaveasdialog.cpp#L140

**Comment by uclaros** [comment]
Some formats allow mixed geometry types in the same layer, like Oracle for example. So there are cases where one might want to export to a specific type. Most use cases are OK with automatic though. I think the simplest solution would be some *'I hope you know what you're doing'* warning when switching from automatic

**Comment by gioman** [comment]
>  think the simplest solution would be some _'I hope you know what you're doing'_ warning when switching from automatic.

@uclaros ummm... not sure about that.

**Comment by elpaso** [comment]
@gioman do I get this right that the issue is with "Save features as..." allowing the user to override the "Automatic" option and it has nothing to do with splitting geometries ?

If this is the case please rewrite the issue title accordingly and tag this a UX/UI.

**Comment by gioman** [comment]
> do I get this right that the issue is with "Save features as..." allowing the user to override the "Automatic" option and it has nothing to do with splitting geometries ?
> 
> If this is the case please rewrite the issue title accordingly and tag this a UX/UI.

@elpaso there two issues one of them being with the "save as" operation that I still need to split in a new ticket.

The issue with the "split features" tool remain: there are cases where a layer can be loaded, a feature split and then even discarding the changes there is data loss.

**Comment by uclaros** [comment]
@elpaso It is actually a combination of the following:
1. "Save features as..." allows to save multi-type features in a single-type layer.
2. QGIS cannot *INSERT* multi-type features in a single-type layer (correctly warns on failed commit) but it has no problem *UPDATE*ing features from single-type to multi-type in a single-type layer.
