### ISSUE TITLE
QGIS crashes when cancelling add child form

### ISSUE THREAD

**Issue by uclaros** [qgis/QGIS#41295]
**Describe the bug**

On a project with a 1:n relation, in the layer form's relation widget, if one clicks on the *add child feature* but then cancel the child feature form, QGIS will crash.

**How to Reproduce**
1. Open a project with a 1:n relation , eg. the advanced bee farming from https://github.com/opengisch/QField/tree/master/resources/demo_projects
2. Identify a parent feature, open its form and start editing parent (apiary)
3. Go to the child relation widget (review tab)
4. Click *Toggle editing mode for child layer*
5. Click *Add child feature*
6. Change your mind and click cancel on the child feature's form
7. Gently weep

**QGIS and OS versions**
 1f91895 on Debian testing

**Comment by roya0045** [comment]
By looking at the code this line seems to be the issue https://github.com/qgis/QGIS/blob/57c5a6fc26ae06b696051cf20c28efb4ab80c199/src/gui/qgsrelationeditorwidget.cpp#L356 as there is no hasGeometry check and assumes a value exists.

**Comment by uclaros** [comment]
Child layer is a geometryless table.
Crash happens at `Fatal: ASSERT: "result" in file ../src/gui/qgsabstractrelationeditorwidget.cpp, line 264`

**Comment by roya0045** [comment]
@uclaros Yes, same thing, your error is within addFeature, though checking for geometry might not be the idea, the problem is still that addFeature is called ;)
