### ISSUE TITLE
Error message is meaningless when add part fails

### ISSUE THREAD

**Issue by m-kuhn** [qgis/QGIS#41294]
1. Create a new project, enable "avoid overlap"
2. Digitize a (couple of) features
3. Use "add part" to add a new part on top of an existing feature
4. 
![image](https://user-images.githubusercontent.com/588407/106466368-86404700-649b-11eb-9982-e65bb50e39ef.png)

**Comment by gioman** [comment]
@m-kuhn In enlish it shows

`Add part: Add part: Feature geom is single part and you've added more than one`

that while correct it completely unnecessary. Is that one?

**Comment by roya0045** [comment]
Is it a mistranslation  more than a qgis issue?

**Comment by m-kuhn** [comment]
The case here is: a single polygon layer and a feature without geometry, trying to add the geometry to this existing geometryless feature.
It's also reproducible with a multipolygon layer (see screencast)

![Peek 2021-02-01 15-15](https://user-images.githubusercontent.com/588407/106470087-63646180-64a0-11eb-9943-b9a1fa14270d.gif)

**Comment by uclaros** [comment]
I confirm, it should behave like the *Add polygon feature* tool and spawn a `CRITICAL    Add feature : The feature cannot be added because its geometry collapsed due to intersection avoidance`

Furthermore, I firmly believe that a simple warning should be shown every time a geometry is modified due to intersection avoidance, be it from adding parts, features, pasting or whatever. Avoid intersection is a fantastic feature, but hell is it dangerous if one forgets it on the wrong state!!!

**Comment by gioman** [comment]
>  It's also reproducible with a multipolygon layer (see screencast)

@m-kuhn I can't replicate that on QGIS master and a scratch layer.


What I observe (on scratch layers, postgis and gpkg) is that the "add part" do not respect the "avoid overlaps" setting!

Moreover I found that on GPKGs created as POLYGONS (not multi) you can add parts to features! and the message is 

`Add part: Add part: Feature geom is single part and you've added more than one`

What a mess! @roya0045 @uclaros @m-kuhn  can you confirm my observations?

**Comment by roya0045** [comment]
A good first step may be to disable part tools for singlepart dataset.

**Comment by uclaros** [comment]
> What I observe (on scratch layers, postgis and gpkg) is that the "add part" do not respect the "avoid overlaps" setting!

For me it does, but shows the empty warning message, just as Matthias shows on the screencast.

Regarding creating multiparts on singlepart layers, this has always been the case, you are not allowed to commit edits though. The most common case I've seen of creating multiparts on singlepart layers is by the merging polygons that are not actually snapped. You can also create multiparts with the in-place-editing overlay algorithms.

**Comment by gioman** [comment]
> For me it does, but shows the empty warning message, just as Matthias shows on the screencast.

@uclaros not here

![Peek 2021-02-01 16-20](https://user-images.githubusercontent.com/1951107/106486422-88a99d80-64a9-11eb-8b5a-62a9314a88b9.gif)


>  you are not allowed to commit edits thoug

try this

[bug_add_part.gpkg.zip](https://github.com/qgis/QGIS/files/5905137/bug_add_part.gpkg.zip)

**Comment by uclaros** [comment]
@gioman you have not enabled avoid overlap, you have to also switch the global selector from *Allow overlap* to *Follow advanced configuration*

> try this

I can add parts but cannot commit:
```
Could not commit changes to layer bug_add_part

Errors: ERROR: 1 feature(s) not added - geometry type is not compatible with the current layer.
```

**Comment by m-kuhn** [comment]
> A good first step may be to disable part tools for singlepart dataset.

It can be used to add geometries to features without geometry (and it's used like this here in prod)

**Comment by gioman** [comment]
> It can be used to add geometries to features without geometry (and it's used like this here in prod)

@m-kuhn which -we must be honest- it is very counter intuitive. Why a user should look to use the "add part" tool to add the missing main geometry to a record?

**Comment by m-kuhn** [comment]
I'm very open to suggestions how this can be improved.
At the moment to my knowledge that's the supported way to do it( so we cannot just phase it out).

**Comment by gioman** [comment]
> I'm very open to suggestions how this can be improved.
> At the moment to my knowledge that's the supported way to do it( so we cannot just phase it out).

@m-kuhn it was not a critique to you, it has always been like that and it has always been weird :)

**Comment by m-kuhn** [comment]
No offense taken. Just trying to stay focused here.

**Comment by m-kuhn** [comment]
you might want to open a new issue for this

**Comment by gioman** [comment]
> I can add parts but cannot commit:

@uclaros this is a multipolygon

[this_is_a_multipolygon.gpkg.zip](https://github.com/qgis/QGIS/files/5905727/this_is_a_multipolygon.gpkg.zip)

![Peek 2021-02-01 17-57](https://user-images.githubusercontent.com/1951107/106498545-6028a000-64b7-11eb-910c-2ca4c98a1b68.gif)

What is wrong? the "avoid overlaps" setting in ignored.


this is a polygon

[this_is_a_polygon.gpkg.zip](https://github.com/qgis/QGIS/files/5905729/this_is_a_polygon.gpkg.zip)

![Peek 2021-02-01 18-00](https://user-images.githubusercontent.com/1951107/106498621-733b7000-64b7-11eb-84c7-c9d25c527288.gif)

What is wrong? As you can see is possible to add parts in a polygon layer and the save the edits. The "avoid overlaps" setting is taken into account and the result acts weirdly, as the "multipart" geometry cannot be selected by its parts, and even the "multi to simple" tool fails to separate the "parts".

**Comment by gioman** [comment]
More GPKG weirdness (or plain bugs) after https://github.com/qgis/QGIS/issues/41283 ...

**Comment by uclaros** [comment]
> What is wrong? the "avoid overlaps" setting in ignored.

You have not enabled avoid overlaps. 
![image](https://user-images.githubusercontent.com/11358178/106502033-84db4280-64cc-11eb-870c-b1cf7f8149ab.png)

That's why I say this is dangerous...

**Comment by gioman** [comment]
> You have not enabled avoid overlaps.

@uclaros yes i did it, in "project > snapping options > advanced".

**Comment by uclaros** [comment]
No, you did not. You only checked *avoid overlaps* for the layer in the advanced config. You also need to set the master switch  (the one in my screenshot) from  ***Allow overlap*** to ***Follow advanced configuration***

**Comment by gioman** [comment]
> No, you did not. You only checked _avoid overlaps_ for the layer in the advanced config. You also need to set the master switch (the one in my screenshot) from _**Allow overlap**_ to _**Follow advanced configuration**_

@uclaros ummm... puzzled... so why it works for the other case (polygon) in my screencast?

**Comment by uclaros** [comment]
Ok, so it seems you *cannot* add a new multipart geometry to a singlepart layer, on commit you get:
```
Could not commit changes to layer bug_add_part

Errors: ERROR: 1 feature(s) not added - geometry type is not compatible with the current layer.
```

You can however add parts to an already saved singlepart, like in your screencast.

So there is checking taking place on INSERTing features but not on UPDATEing features, and this is the part (no pun intended) we should take care of!
The psychedelic result in your second screencast is not caused by avoid overlap, rather by the incompatible geometry. The second part is interpreted as an inner ring instead of a second outer ring and things get funky!

**Comment by gioman** [comment]
> The psychedelic result in your second screencast is not caused by avoid overlap, rather by the incompatible geometry. The second part is interpreted as an inner ring instead of a second outer ring and things get funky!

@uclaros jeeez, what a mess.

**Comment by uclaros** [comment]
You can get in the same situation if you get a polygon, punch a hole, and then move the hole's vertices outside the outer ring with the vertex tool. We can't avoid handling such corrupt geometries, but we can reduce the ways of producing them.

**Comment by gioman** [comment]
> Is the regression tag appropriate after all?

the message that is the main subject of this ticket seems to me (I can be wrong) something that didn't show up in the past (or maybe it was just different, more meaningful), if confirmed is a regression. I will check.

**Comment by m-kuhn** [comment]
Is there still a feedback needed from my side?

**Comment by gioman** [comment]
> Is there still a feedback needed from my side?

I guess no.
