### ISSUE TITLE
QGIS crashes when trying to link existing child features

### ISSUE THREAD

**Issue by uclaros** [qgis/QGIS#41314]
**Describe the bug**

On a project with a 1:n relation, in the layer form's relation widget, if one clicks on the *link existing child features*, select a child feature and click ok, QGIS will crash with a:
```
Fatal: ASSERT: "mRelation.polymorphicRelation().isValid()" in file ../src/gui/qgsabstractrelationeditorwidget.cpp, line 484
```

**How to Reproduce**

1. Open a project with a 1:n relation , eg. the advanced bee farming from https://github.com/opengisch/QField/tree/master/resources/demo_projects
2. Identify a parent feature, open its form and start editing parent (apiary)
3. Go to the child relation widget (review tab)
4. Click Toggle editing mode for child layer
5. Click Link existing child features
6. Select an existing review feature and click ok
7. Gently weep

**QGIS and OS versions**
1f91895 on Debian testing

**Comment by SebastienPeillet** [comment]
I reproduced the bug. It seems like a it's just a little mistake. There is a check on the link action (qgsabstractrelationeditorwidget.cpp) that verifies if the relation is polymorphic or not... but it leads to polymorphic check if the relation is **not** polymorphic :)

```cpp
      if ( mRelation.type() == QgsRelation::Normal ) // should be QgsRelation::Generated
      {
        QgsPolymorphicRelation polyRel = mRelation.polymorphicRelation();

        Q_ASSERT( mRelation.polymorphicRelation().isValid() );
```
