### ISSUE TITLE
Missing drop-down option and legend for mesh layer

### ISSUE THREAD

**Issue by ANitecka** [qgis/QGIS#41317]
**Describe the bug**
While working with an imported mesh layer, there is no option to use 'drop-down' icon to excess the legend for the chosen dataset (as it works with the raster layers). It results in not being able to view the legend and add it to the map layout.
This feature is available in QGIS 3.12 version.

**How to Reproduce**
Example of the desired result:

![QGIS_3_12_mesh_layer_symbology](https://user-images.githubusercontent.com/40445780/106619718-2a47f200-6571-11eb-86b0-ee2d99f162b5.PNG)
![QGIS_3_12_mesh_legend](https://user-images.githubusercontent.com/40445780/106619724-2b791f00-6571-11eb-800a-605a668cee30.PNG)

**QGIS and OS versions**

QGIS-Version
3.14.16-Pi
QGIS-Codeversion
df27394552
Kompiliert gegen Qt
5.11.2
Laufendes Qt
5.11.2
Kompiliert mit GDAL/OGR
3.0.4
Läuft mit GDAL/OGR
3.0.4
Kompiliert mit GEOS
3.8.1-CAPI-1.13.3
Läuft mit GEOS
3.8.1-CAPI-1.13.3
Kompiliert mit SQLite
3.29.0
Läuft mit SQLite
3.29.0
PostgreSQL-Client-Version
11.5
SpatiaLite-Version
4.3.0
QWT-Version
6.1.3
QScintilla2-Version
2.10.8
Kompiliert mit PROJ
6.3.2
Läuft mit PROJ
Rel. 6.3.2, May 1st, 2020
BS-Version
Windows 10 (10.0)
Aktive Python-Erweiterungen
crayfish; 
db_manager; 
MetaSearch; 
processing

**Additional context**

**Comment by gioman** [comment]
>  3.14.16-Pi

@ANitecka this is outdated, please try on the latest 3.16.

**Comment by ANitecka** [comment]
Thank you for a fast answer. It does not work on the 3.16 version either. 
<img width="187" alt="QGIS_3_16_mesh_layer" src="https://user-images.githubusercontent.com/40445780/106624257-beb45380-6575-11eb-9306-6e73bff1db58.PNG">

**Comment by gioman** [comment]
> Thank you for a fast answer. It does not work on the 3.16 version either.

@ANitecka please attach/link the data.

**Comment by vcloarec** [comment]
@ANitecka , I can replicate with opening existing project that has a mesh layer. Does it happen when you add  new mesh layer to project?
