### ISSUE TITLE
Unable to download and install Plugin

### ISSUE THREAD

**Issue by semiautomaticgit** [qgis/QGIS#41336]
**Describe the bug**
Unable to download and install the Semi-Automatic Classification Plugin in QGIS.
Please see https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/issues/152

**How to Reproduce**

1. Go to Manage and Install Plugins
2. Search Semi-Automatic Classification Plugin
3. The available version listed is 7.5.4 but the latest version uploaded yesterday is 7.5.6
4. Click install Plugin
5. See error --> Plugin installation failed: Error transferring https://plugins.qgis.org/plugins/SemiAutomaticClassificationPlugin/version/7.5.4/download/ - server replied: Not Found

I'm the author of the plugin. 
I removed the version 7.5.4. 
I already tried to unapprove and approve the latest version.
Is there something I can do from the plugin side?

Thank you

**Comment by Gustry** [comment]
Closing in favor of the ticket above. This issue is on the server side I think.

**Comment by semiautomaticgit** [comment]
> Closing in favor of the ticket above. This issue is on the server side I think.

Thank you very much
