### ISSUE TITLE
Group has no name when importing sublayers from browser panel

### ISSUE THREAD

**Issue by jdlom** [qgis/QGIS#41343]
When importing sublayers from browser panel, the group name is blank.

Works great from the data source manager and with a drag and drop from the file browser.

![group_sublayers_empty_from_browser](https://user-images.githubusercontent.com/8641271/106803512-98211600-6664-11eb-9a7f-2a19f85ae316.gif)

QGIS version | 3.17.0-Master | QGIS code revision | 29a816a3eb
-- | -- | -- | --
Compiled against Qt | 5.12.8 | Running against Qt | 5.12.8
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
Compiled against PDAL | 2.0.1 | Running against PDAL | 2.0.1 (git-version: Release)
PostgreSQL Client Version | 12.5 (Ubuntu 12.5-0ubuntu0.20.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Ubuntu 20.04.1 LTS | This copy of QGIS writes debugging output.

Same issue on QGIS 3.16.3

**Comment by roya0045** [comment]
From your gif it looks like the group contains the layers and is not empty, just has no name. Or am I missing something?

**Comment by gioman** [comment]
> Or am I missing something?

@jdlom yeah I was thinking the same... if this is a bug report please edit your title and description to make it more meaningful, thanks.

**Comment by jdlom** [comment]
> From your gif it looks like the group contains the layers and is not empty, just has no name. Or am I missing something?

@roya0045 You're right, I had just changed the title.

**Comment by elpaso** [comment]
Can you attach the kml?

**Comment by jdlom** [comment]
@elpaso : it's a layer iavailable in the testdata folder.
https://github.com/qgis/QGIS/blob/master/tests/testdata/multilayer.kml
