### ISSUE TITLE
Cannot Create New Tables in a Geopackage (browser)

### ISSUE THREAD

**Issue by rhewy** [qgis/QGIS#41342]
**Bug**

![image](https://user-images.githubusercontent.com/4993063/106800607-86fce880-6615-11eb-8185-b04cc24cee5b.png)

**How to Reproduce**
1. Use the browser to create a gpkg in a folder (do not add as a connection)
2. Right click on the gpkg and select new table

**QGIS and OS versions**
QGIS 3.16.3
Windows 10

**Work around**
1. Use the browser to create a gpkg in a folder
2. Right click on the gpkg and select  'Add connection'
3. Right click on the gpkg and select new table

**Solution B**
Add layer could automatically add the gpkg as a connection if the gpkg in not currently in the connections list

**Solution A**
Refactor the code so that a gpkg is recognized in the same manner. Currently something is different between a gpkg in a folder and the same gpkg as a connection.

**Comment by gioman** [comment]
Confirmed.

**Comment by nyalldawson** [comment]
3.16 only?

**Comment by gioman** [comment]
> 3.16 only?

also master.

**Comment by rhewy** [comment]
This will probably not help but this video I made last year (Jan-16-2020) QGIS did not behave in the current fashion
https://youtu.be/ygpDxjHsGMA?t=200

**Comment by nyalldawson** [comment]
Ah - so it only occurs when the geopackage has no existing tables? Could you try dragging and dropping some other layer into the gpkg first, and then creating the table?

**Comment by rhewy** [comment]
The error occurs with exiting layers (these layers are empty)
![image](https://user-images.githubusercontent.com/4993063/106812686-de568500-6624-11eb-9c98-00da957edaaf.png)

**Comment by rhewy** [comment]
FYI - With data in the layers the error still occurs
