### ISSUE TITLE
Cut & Paste into Excell sheet

### ISSUE THREAD

**Issue by Pio1972** [qgis/QGIS#41356]
## User Feedback

I was pasting a selection of records into a MSExcell sheet

## Report Details

**Crash ID**: [f79c7767ae8f98e0e67605a63bb9794cfa448921](https://github.com/qgis/QGIS/search?q=f79c7767ae8f98e0e67605a63bb9794cfa448921&type=Issues)

**Stack Trace**
<pre>
memcpy memcpy.asm:194
VSICreateCachedFile :
VSIFReadL :
</pre>

**QGIS Info**
QGIS Version: 3.10.7-A Coru�a
QGIS code revision: 7b4ca4c8d0
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by Gustry** [comment]
> QGIS Version: 3.10.7-A Coru�a

3.10 is not maintained anymore. You should update to a maintained version of QGIS : 3.16.

You should try with a new QGIS profile.
https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles

**Comment by roya0045** [comment]
VSICreateCachedFile come from gdal, but I think the issue might be an out of memory or something else. Can you replicate this consistlently with the same dataset and selection on a recent qgis?

**Comment by gioman** [comment]
Closing for lack of feedback.
