### ISSUE TITLE
QGISServer: the 'QGIS Server Catalog'/landing page is only possible in the root of the webserver: make it configurable

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS#41354]
See this dev list thread:
https://lists.osgeo.org/pipermail/qgis-developer/2021-February/063033.html

Currently the QGIS Server Catalog landing page only works when you use the rewrite rules to run the fastcgi in the root  of the webserver.

Alesandro proposes to use a QGIS_SERVER_BASE or QGIS_SERVER_BASE_URL to be able to use that on other url's then the /

```
IMO in a real deployment no one will ever use the path
/cgi-bin/qgis_mapserv.fcgi without rewriting it so I don't think it's
a real issue, anyway a possible solution would be to create yet
another server setting that allows us to specify the base path of the
server (in your case: `/cgi-bin/qgis_mapserv.fcgi`) so that we can
prepend it to the match (that would become
`/cgi-bin/qgis_mapserv.fcgi/`).

This is the reason for:
https://github.com/elpaso/qgis-server-docker/blob/production/default.conf#L45
```

**Comment by elpaso** [comment]
I would probably go for `QGIS_SERVER_LANDING_PAGE_URL_PREFIX`, defaults to `/`.

I'm wondering if it could be useful for other situations/APIs but I think that each API will deserve its own prefix.

**Comment by dmarteau** [comment]
Hi, 

I would like to add some comments  of my experience of running qgis server with a middleware proxy that do not use `/` as base urls and seems to be related to this issue:

* If you attempt to get the metadata of a layer you get an uri like /project/<some_id>/..... : this makes the link unusuable in the context of a proxified url.

* It seems also that the landing_page api does not consumme urls like other services: in `wfs3` service the  prefix uri is returned correctly in the handled responses: if I give `/whatever/wfs3/.....` , I will get correctly formatted urls in the response. But with the landing_page api, declaring `/catalog` as prefix and fetching` `/whatever/catalog/...` will return a 404. 

* Setting /ows/catalog as landing page you may reach the uri /ows/catalog/index.html but not `/catalog/` as it return an invalid unterminated response whenever using server from pyQgis  .

**Comment by elpaso** [comment]
> Hi,
> 
> I would like to add some comments of my experience of running qgis server with a middleware proxy that do not use `/` as base urls and seems to be related to this issue:
> 
>     * If you attempt to get the metadata of a layer you get an uri like /project/<some_id>/..... : this makes the link unusuable in the context of a proxified url.
> 
>     * It seems also that the landing_page api does not consumme urls like other services: in `wfs3` service the  prefix uri is returned correctly in the handled responses: if I give `/whatever/wfs3/.....` , I will get correctly formatted urls in the response. But with the landing_page api, declaring `/catalog` as prefix and fetching` `/whatever/catalog/...` will return a 404.
> 
>     * Setting /ows/catalog as landing page you may reach the uri /ows/catalog/index.html but not `/catalog/` as it return an invalid unterminated response whenever using server from pyQgis  .

Hi, I think I've fixed it already in master. Can you check it? https://github.com/qgis/QGIS/pull/43960

**Comment by dmarteau** [comment]
@elpaso 

Tested with latest master:  the metadata URL is ok.

> Setting /ows/catalog as landing page you may reach the uri /ows/catalog/index.html but not `/catalog/` as it return an invalid unterminated response whenever using server from pyQgis  .

This is still the case: I need to fetch  explicity `index.html` otherwise it returns an invalid response (0 length content)

**Comment by elpaso** [comment]
@dmarteau I've added some tests here but I cannot reproduce your issue: https://github.com/qgis/QGIS/pull/44158

Can you provide a failing test case?

**Comment by dmarteau** [comment]
@elpaso: My bad, the problem was on my side: the request to the landing page root url return a 302 and it was not handled correctly by my python script as it is a zero length response... 

So far, all is working ok now, thanks.

**Comment by elpaso** [comment]
@dmarteau can you approve  #44158 ? :smile_cat:
