### ISSUE TITLE
QGISServer: /wfs 3 endpoint does not show all collections available?

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS#41358]
If you have several projects in your project folder you will end up when you got to 
http://yourserver/
You will see the 'QGIS Server Catalog' landing page. Something like this:

![Screenshot-20210204125232-673x768](https://user-images.githubusercontent.com/731673/106889116-dad80200-66e7-11eb-95e4-f9587a09f991.png)

I think it is not intuitive that when you go to:
http://yourserver/wfs3
that you then ONLY see one project (or no project)?

I can go off course via 'metadata/services' in one of the tiles also go to the WFS3 endpoint:
http://localhost/project/db92faba309f0408ab62b2fda30b319f/wfs3

But:

1) would it not be more intuitive to use (instead of the uuid like id's for the projects) to have simple numbers, or even the 'titles' or 'shortnames' of the projects?
I can think of the fact that this is delibeartly, so to 'hide' all services, but I think the idea of the whole OAPI stuff is that you can discover everything over the web?

2) would it not be nice that IF you have several projects (that is: QGIS_SERVER_LANDING_PAGE_PROJECTS_DIRECTORIES defined) that the 'main' wfs3 endpoint then would list  available endpoints (as json?)? 
OR just go to the 'QGIS Server Catalog' page?

Just some thoughts...

**Comment by elpaso** [comment]
> I think it is not intuitive that when you go to:
> http://yourserver/wfs3
> that you then ONLY see one project (or no project)?

I would agree, but OAPIF/WFS3 it's a standard: we cannot do anything about it. It has the concept of "collections" that maps 1-1 to our concept of "layers" but there is no grouping of collections into what we call a "project". 

Think of it as the good old WFS/WMS: you can serve a single project at a time.

> 
> I can go off course via 'metadata/services' in one of the tiles also go to the WFS3 endpoint:
> http://localhost/project/db92faba309f0408ab62b2fda30b319f/wfs3
> 
> But:
> 
>     1. would it not be more intuitive to use (instead of the uuid like id's for the projects) to have simple numbers, or even the 'titles' or 'shortnames' of the projects?

Nope, that's not guaranteed to be unique.

>        I can think of the fact that this is delibeartly, so to 'hide' all services, but I think the idea of the whole OAPI stuff is that you can discover everything over the web?

Yes: it was deliberate
No: the reason is not to hide anything but to guarantee uniqueness and a standardized identifier format that I can identify with a regexp in the URL routers, I came up with the md5 hash but I agree that it's not very nice.

Anyway, if you want to implement some more elaborate logic to use unique project (short)names instead of the hash I would be happy to review it.

> 
>     2. would it not be nice that IF you have several projects (that is: QGIS_SERVER_LANDING_PAGE_PROJECTS_DIRECTORIES defined) that the 'main' wfs3 endpoint then would list  available endpoints (as json?)?
>        OR just go to the 'QGIS Server Catalog' page?
> 

Unfortunately, WFS3/OAPIF is one thing and it's standardized (we even applied to OGC certification), while the "landing page" is entirely my invention. 

Ultimately, we have the freedom to do whatever we want with our custom landing page/catalog but we cannot change the OAPIF/WFS3 API and its landing page (we can change the HTML/JS/CSS though, but not the API itself).

To add more context, the landing page (catalog) effort was triggered exactly by that: I did like the landing page idea of WFS3 but I wanted to make it a "catalog" user friendly landing page where you can access multiple projects and that works out of the box (well, not for you, I know :smile: ) with only one single variable configuration (the directories setting).

**Comment by rduivenvoorde** [comment]
Ok, clear. I get your points...

About unique names, I will think about this and try to implement. Some idea's for now:

- can we maybe use the FILENAME of the qgz file then? (given they are in the same directory, there theoretically they cannot be the same)?

- instead of using md5 hashes (of what exactly? not of the projectnames as then they would still be te same?), just use simple counters? Or a combi of projectname + counter? Or (preferably) only add a counter if the projectname isn't unique? I do understand that you want these counters te stay te same if a new project is added... so probably... yeah... tricky...

- is there some shorter hash (like 4 to 5 characters) possible so they can be shown in the landing page?

- about /wfs3 endpoint, I think that is not defined for the server /-endpoint, but probably for the collection endpoint? So if a projectfile/collection is named 'world2021' then the wfs3 endpoint would ideally end up on /world2021/wfs3
And / would (I think) just have no endpoint (because it IS not an endpoint)? So we are/should be free to come up with a nice (json) endpoint ourselves? (or just the catalog)...

I do understand this talk all takes a lot of time.... not going into coding, it's just that I try to keep things a little intuitive if possible...

**Comment by elpaso** [comment]
> Ok, clear. I get your points...
> 
> About unique names, I will think about this and try to implement. Some idea's for now:
> 
>     * can we maybe use the FILENAME of the qgz file then? (given they are in the same directory, there theoretically they cannot be the same)?
> 

Nope: you can specify more than a single directory for projects so you can have duplicates, same goes for postgis projects.

>     * instead of using md5 hashes (of what exactly? not of the projectnames as then they would still be te same?), just use simple counters? Or a combi of projectname + counter? Or (preferably) only add a counter if the projectname isn't unique?
> 
>     * and what about making the user responsible for making sure the project shortnames are unique (we can add a note in the server tab?). Then at least we can use it, and we only pick up the first one we see/find?

Nope: this would violates my zero-config policy and you could have multiple users working on multiple folders and/or multiple PG connections.

I would probably prefer a logic to add  an incremental integer to non-unique shortnames.

> 
>     * is there some shorter hash (like 4 to 5 characters) possible so they can be shown in the landing page?
> 

That's easy to do, I don't know how short could it be to be sure we don't have clashes though.

>     * about /wfs3 endpoint, I think that is not defined for the server /-endpoint, but probably for the collection endpoint? So if a projectfile/collection is named 'world2021' then the wfs3 endpoint would ideally end up on /world2021/wfs3

I don't see any difference here to what we have currently for WFS and WMS: either you set a project through an env var or you pass it with `MAP`. Except that WFS3 explicitly forbids to add anything in the query string, so `?MAP=....` is in theory violating the specs.

My solution in the landing page also avoids the `?MAP=...` by using unique hashes.

>       And / would (I think) just have no endpoint (because it IS not an endpoint)? So we are/should be free to come up with a nice (json) endpoint ourselves? (or just the catalog)...

That's exactly the idea of the landing page catalog: respond to `/` (or the base URL, whatever it is).

> 
> 
> I do understand this talk all takes a lot of time.... not going into coding, it's just that I try to keep things a little intuitive if possible...

Let's just agree that the definition of "intuitive" is rather vague and subjective?

I though that the catalog, served by default on `/` was exactly the definition of intuitive, it even gives you a nice self explanatory warning when there are no projects configured in the catalog.

**Comment by elpaso** [comment]
IMO this is a won't fix and we can close.

Think at WFS3 as another OGC protocol, it is designed to serve one project at a time exactly as with WMS, WFS etc.

For your use case the is the landing page/catalog.
