### ISSUE TITLE
Write Vector Tiles, both MBtiles and XYZ, not producing output, 3.16.0-Hannover

### ISSUE THREAD

**Issue by kyliejane** [qgis/QGIS#41367]
When running Write Vector Tiles (from Processing), either MBtiles or XYZ, it does not produce tiles. Both seem to run OK and "finish", there are no errors in the log, however in the case of XYZ nothing is produced, in the case of MBtiles, a 16kb "empty" file is produced. Tested with multiple projects.

**How to Reproduce**

1. Go to Processing -> Write Vector Tiles (either/both MBtiles and XYZ)
2. Fill in parametres, layers (one layer or many), extent (tried all options), choose file location (or leave a temporary file)
3. Run
4. XYZ produced nothing, no directories or files
5. MBtiles produces "empty" mbtiles file of 16kb size (always 16kb no matter the amount of layers added or different projects).
6. Same results testing with Lutra's sample project at https://www.lutraconsulting.co.uk/blog/2020/06/10/vectortiles-part1/
7. Log files below.

**QGIS and OS versions**
3.16.0-Hannover
Windows 10
(version screenshot attached)

![mbtiles](https://user-images.githubusercontent.com/1030684/106964569-69a35800-6796-11eb-8098-070f99cecd5d.PNG)
![xyz](https://user-images.githubusercontent.com/1030684/106964601-73c55680-6796-11eb-99fd-b9d6e5348784.PNG)
![version](https://user-images.githubusercontent.com/1030684/106964777-c141c380-6796-11eb-8460-41b929513f36.PNG)

**Comment by roya0045** [comment]
Please validate on a recent qgis release and try with a new profile to valide if this error still occurs for you.

**Comment by rduivenvoorde** [comment]
@kyliejane can you provide an example project or data?

I downloaded the stuff from Lutra, but in the survey.gpkg there are zero features == NO data.
So creating tiles from that will not work.... or am I wrong?

Isn't the extent you are creating tiles for: 947444,949840,6003483,6005332 ok?  
I'm used to W,S,E,N extents, like the opening extent of the lutra project: 944591,6000420 : 955727,6007817

And: using only z from 0 to 3, that are not so many z-levels, are you sure that should result in tiles?

I opened the roads of Natural Earth (in the lutra project), zoomed to Paris:

![Screenshot-20210206001946-2017x1179](https://user-images.githubusercontent.com/731673/107099181-44076480-6811-11eb-83de-119031f0d6b3.png)

Used THAT extent (as you see that is west,south,east,north), see this in processing params:

And then I have tiles: 

[OUTPUT.zip](https://github.com/qgis/QGIS/files/5935796/OUTPUT.zip)

So: to me this is working, IF you select data, the right extent and appropriate zoomlevels.

Please provide more info if you fail to reproduce my test

**Comment by gioman** [comment]
Closing for lack of feedback.
