### ISSUE TITLE
new "smart" cache renderer do not work with map rotation

### ISSUE THREAD

**Issue by vcloarec** [qgis/QGIS#41360]
On master.

How to reproduce:
- Load a raster layer with long rendering (or simulate it by enable SIMULATE_SLOW_RENDERER in the source fle) 
- map rotation = 90°
- pan the map

--> the rendering is like before this smart rendering or make a weird pre-rendering

https://user-images.githubusercontent.com/7416892/106895233-5c1e9d00-66c6-11eb-8974-09f6dc18b8b2.mp4

Not sure, but I think this come from a bad transform of the cache image when there is a map rotation

**Comment by roya0045** [comment]
Rotation seems to be a common issue with rendering judging by the lingering issues. Maybe they were just forgotten also.

**Comment by PeterPetrik** [comment]
for 3.18 the invalid use of cache is used, full support of smart map updates with rotation should be added as feature later on (e.g. other stuff is not supported too, see `QgsMapCanvas::startPreviewJobs()`)
