### ISSUE TITLE
Download Qgis on MacOS

### ISSUE THREAD

**Issue by EmmaP33** [qgis/QGIS#41361]
Hi !

I'm a student from France and I can't download Qgis on my macbook air, which is a MacOS Big Sur from 2020 (11.1)

Does the developer is going to change that ? Is he going to upgrade Qgis or not ? 
I really need Qgis for my studies and I don't want to change my computer juste for this problem.

Thank you and sorry for my English 
Emma

**Comment by gioman** [comment]
>  and I can't download Qgis on my macbook

https://qgis.org/en/site/forusers/download.html
