### ISSUE TITLE
New GTiff create option not offered for QGIS raster processing

### ISSUE THREAD

**Issue by Houska1** [qgis/QGIS#41378]
OSGeo4W 3.17.0 version '9fe1c17719' and also 3.16.3

Defined a new GTiff creation option set (via Options / GDAL). It is valid and works fine for e.g. exporting a raster layer from the layer tree.
![Screen_Capture_-_5_Feb__11_58_am](https://user-images.githubusercontent.com/48919900/107065462-cf014400-67aa-11eb-8dcf-de9db36d7806.png)

However, selecting this creation option set in the Advanced Options of a QGIS raster processing algorithm (e.g. Clip Raster by Mask Layer, but also tried Warp) does not populate the parameter list, which stays empty.
![Screen_Capture_-_5_Feb__0_00_pm](https://user-images.githubusercontent.com/48919900/107065757-23a4bf00-67ab-11eb-97cc-255802d24906.png)

Selecting one of the "out of the box" options sets, like JPEG or High Compression, does populate the list and execute properly. 
I've tested and the options I'm specifying are consistent with the datatype of the raster being processed, and the options can be manually entered via the + button.

**Comment by nicogodet** [comment]
Duplicate #40235
