### ISSUE TITLE
Menu pop off

### ISSUE THREAD

**Issue by Ehespinosa** [qgis/QGIS#41377]
**Describe the bug**

Some menus pop off the screen and cannot be used.
**How to Reproduce**
Start GUI

4. See error -->

**QGIS and OS versions**
Qgis 3.14 Fedora 33

**Additional context**

**Comment by gioman** [comment]
@Ehespinosa please clarify. It is not clear at all what this is about and how to replicate. Also you are using an outdated QGIS version.

**Comment by Ehespinosa** [comment]
Sorry it's very possible that my explanation is confusing.
I send a screenshot of what happens to me. When you open some menus, they are partially disabled because they go off the screen.
![Captura de pantalla de 2021-02-05 17-50-28](https://user-images.githubusercontent.com/78610814/107063981-4cdd4380-67db-11eb-86f9-6dd097b0ab4d.png)

**Comment by roya0045** [comment]
Can you update to a recent version, just to validate of this is still an issue and please provide your qgis  to validate if QT or qgis is the issue.

**Comment by gioman** [comment]
> I send a screenshot of what happens to me

@Ehespinosa it is still not clear to me what I'm looking at. A little screencast is probably better than a still image.

**Comment by roya0045** [comment]
@gioman menus are too wide and it goes out of screen. The screenshot is the extent of his current display.

**Comment by Ehespinosa** [comment]
Yes, the screenshot sent is what appears when opening the edit menu.
I will try to make a screenshot, it is possible that it can be understood better.

**Comment by TurboGraphxBeige** [comment]
@Ehespinosa  What is your screen resolution?

@roya0045 @gioman I wonder if #40812 could fix the issue this person is having.

**Comment by Ehespinosa** [comment]
The screen resolution is 1366x768, I have tried 1280x720 and the same thing happens.

**Comment by Ehespinosa** [comment]
The screen resolution is 1366x768, I have tried 1280x720 and the same thing happens.

**Comment by rduivenvoorde** [comment]
QGIS nowadays needs a lot of space, these are rather small screen resolutions I think. Some years back we tried to be usable on small screens, but as functionality grows, so do the needed screens.

But looking at your screenshot there also seems something funny with all menu's. Can you run other Qt or KDE applications fine?

You are running spanish(??) if you run english, does it also show like this?

I set my resolution also to 1366x768 but then it looks ok:

![Screenshot-20210206003357-1368x768](https://user-images.githubusercontent.com/731673/107099882-25a26880-6813-11eb-8075-b2f2af373911.png)

Do you run some special Linux distro? Or which Window manager? It looks like Gnome? Some special theme?

Can you try to create a fresh profile and see what happens then?

**Comment by Ehespinosa** [comment]
I have already turned off the computer for today, tomorrow I will try
these solutions, thanks.

**Comment by uclaros** [comment]
@rduivenvoorde you have #40812 merged while @Ehespinosa clearly does not! 1366x768 is a resolution we should try to support as a minimum and I don't think it's hard to do.

**Comment by Ehespinosa** [comment]
My operating system is Fedora 33, with Gnome 3.38.3 and Wayland, I think the problem is here but I don't know how to solve it.

**Comment by nyalldawson** [comment]
Have you tried using an xorg session instead of Wayland?

**Comment by uclaros** [comment]
@nyalldawson Maybe have #40812 backported to 3.16?

**Comment by nyalldawson** [comment]
Hmmmm - it's rather intrusive to users to change UI like that in a patch release. Ultimately it's a DE/OS issue at play, because qt should automatically be overflowing these menus. That's why I suspect Wayland may be the cause (in my experience qt under Wayland isn't ready for end user use yet, there's still too many outstanding issues)

**Comment by uclaros** [comment]
OK, though I find displaying this humongus menu at least as intrusive! :laughing:

**Comment by Ehespinosa** [comment]
Finally I have found the solution to the problem, I have started my system in a KDE environment and QGIS works perfectly, so the problem is that it is not well understood either with Gnome or with Wayland.
Thanks to all for the help.

**Comment by Ehespinosa** [comment]
https://insurgente.org/el-gobierno-mas-progresista-de-la-historia-no-contempla-la-nacionalizacion-de-la-electricidad-pese-a-ser-un-bien-basico/


Somos el único de los grandes países europeos que no tiene eléctrica
pública.

**Comment by Ehespinosa** [comment]
https://www.libresdecontaminanteshormonales.org/2021/09/13/lista-de-plaguicidas-altamente-peligrosos-de-pan-internacional/

**Comment by Ehespinosa** [comment]
NO al desalojo del huerto Las Vías en Arganzuela #HuertoLasVíasSeQueda
Asociación Vecinal Pasillo Verde Imperial España


Los vecinos y las vecinas del distrito de Arganzuela de Madrid siembran
y cuidan del Huerto Las Vías desde que la Junta Municipal del Distrito
cedió una parcela sin uso del Polideportivo Marqués de Samaranch a la
Asociación Vecinal del barrio dentro del programa de Huertos Urbanos
Comunitarios en 2017. Abierto a toda la vecindad, es un punto de
encuentro y convivencia en el distrito que reúne a varias generaciones
en torno a la siembra y el cuidado de las plantas. Entre sus numerosas
actividades, el Huerto recibe la visita y participación de niños,
jóvenes, adultos y mayores: visitas semanales de los niños y niñas del
cercano Colegio Marqués de Marcenado, para que los más pequeños tengan
su primer contacto con la agricultura, grupo de personas atendidas por
el Centro de Rehabilitación Psicosocial (CRPS) de Arganzuela, o de
grupos de mayores de Madrid Salud, dentro del programa de
#SoledadNoDeseada del Ayuntamiento.
El Huerto Las Vías es ahora un vergel, fruto de horas de esfuerzo, duro
trabajo e ilusión de muchos hortelanos y hortelanas, que miran con
incomprensión y estupor cómo la junta municipal de Arganzuela exige que
todos los cultivos sean arrancados y destruidos antes del 22 de enero. 

En estos tiempos de pandemia, el Huerto Las Vías es salud, física y
mental, para tantos vecinos y vecinas de Madrid, de todas las edades.

El pasado 22 de diciembre, la Junta Municipal notificó a la AV Pasillo
Verde-Imperial que debía desmantelar el huerto antes del 22 de enero,
alegando que la asociación vecinal no había solicitado la prórroga de
la cesión en tiempo y forma. 

La cuestión es que, después de un año en la parcela cedida, el
Ayuntamiento hizo obras en el polideportivo y el Huerto se trasladó
provisionalmente a otra parcela alternativa, sin uso, también dentro
del recinto del Polideportivo Marqués de Samaranch. Ese traslado supuso
una suspensión del plazo de concesión. Cuando acabaron las obras, la AV
Pasillo Verde-Imperial solicitó volver a la parcela inicial, pero el
Ayuntamiento informó que no podían autorizarlo al no estar
recepcionadas las obras aún por el Ayuntamiento, y así hasta el pasado
22 de diciembre cuando la junta municipal comunica a la Asociación
Vecinal Pasillo Verde-Imperial que debe desalojar el Huerto Las Vías y
dejar la parcela como se entregó: una escombrera abandonada y sin uso. 
Al no recibir notificación por parte del Ayuntamiento que había
recepcionado las obras, que se podía volver a la parcela inicial y, por
lo tanto, que se ponía de nuevo en marcha el reloj de la cesión, la
Asociación Vecinal Pasillo Verde consideraba que seguía vigente la
suspensión temporal de la cesión y no solicitó la renovación de la
misma. 

Por todo ello, pedimos a doña Cayetana Hernández de la Riva, concejala
presidenta de la Junta Municipal de Arganzuela, y a don José Luis
Martinez-Almeida, alcalde Madrid, que no destrocen el esfuerzo, el duro
trabajo y la ilusión de tantos vecinos y vecinas del distrito y
otorguen la renovación de la concesión para la utilización del huerto
por 2 años más según las condiciones iniciales.
-- 
Emilio Herrera Espinosa
***@***.***
678829870

**Comment by Ehespinosa** [comment]
https://www.elsaltodiario.com/biodiversidad/nuevo-frente-recuperar-la-janda-mayor-humedal-espana


Otro desastre ecológico provocado por la agricultura intensiva que se debe
corregir.

**Comment by Ehespinosa** [comment]
Teresa Rodríguez ۞ ***@***.***_) twitteó a las 11:54 a. m. on dom., abr.
17, 2022:
Vox y OkDiario crean y difunden el bulo de que "un grupo de menas" han
boicoteado una procesión en Graná. Lo demiente la Cofradía, la Policía y la
prensa local pero mantienen el bulo. Su obsesión con los menores es
enfermiza. No son critianos ni cofrades, son Herodes y Pilatos.
https://t.co/BzeqD6I7BC
(
https://twitter.com/TeresaRodr_/status/1515629806112714757?t=3bFndYu9TwirSSbDOW3DDA&s=03
)

**Comment by Ehespinosa** [comment]
Sin prensa libre no hay democracia.

**Comment by Ehespinosa** [comment]
Anticapitalistas Extremadura ***@***.***) twitteó a las 6:15 p. m. on
dom., jul. 17, 2022:
Las Hurdes. Cambio climático. Sierra de Gata. Sequía. Monfragüe. Aumento de
las temperaturas. Garganta de los Infiernos. Desertificación. Valle del
Jerte. https://t.co/BiIJKYiLiC
(
https://twitter.com/Anticapiext/status/1548703056719749120?t=s_rUNlLYLltyDcbCpnFVrg&s=03
)

**Comment by Ehespinosa** [comment]
https://www.elsaltodiario.com/educacion-concertada/junta-andalucia-crea-direccion-general-ensenanza-concertada

**Comment by Ehespinosa** [comment]
https://www.facebook.com/100085599673761/posts/pfbid0HquFGzRcBMTX7jv4D1FyRbZSMeL4hhQcXjTP4UuSE75M8RLnksZ43hF9tHM54HQCl/?sfnsn=scwspmo

**Comment by Ehespinosa** [comment]
https://www.eldiario.es/andalucia/moreno-lanza-anzuelo-fiscal-empresarios-catalanes-independizar_1_9551712.html


Baja impuestos a los ricos, pide ayuda al Gobierno central para poder
financiar los cada vez menores servicios públicos. Robar a los pobres para
darles a los ricos.

**Comment by Ehespinosa** [comment]
https://www.twitch.tv/elsaltodiario

**Comment by Ehespinosa** [comment]
https://www.elsaltodiario.com/suscribirse/
