### ISSUE TITLE
replace geometry generator icon for labels placed via geometry

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#41388]
in the current icon there are three dots `...`, I think it would be better to use the classic icon with the symbol ![](https://docs.qgis.org/3.16/it/_images/mIconExpression.png) to adapt it to all the others

![image](https://user-images.githubusercontent.com/7631137/107121844-e0bf1600-6894-11eb-8f88-e3a431e0d543.png)

## OSGeo4W64 QGIS 3.16 Hannover

**Comment by agiudiceandrea** [comment]
See https://github.com/qgis/QGIS/pull/58665.
