### ISSUE TITLE
Graphical selection tool: Not all features are selected

### ISSUE THREAD

**Issue by tschmetzer** [qgis/QGIS#41396]
When I select a features by graphical selection only a part of them is selected. I can see this in the attribute table. Due to legal terms I will show the deficiency graphically by exporting the selected features to a new layer. Please note that the features are vertical polygons (data from walls). Please refer to the screenshots.

![wall_selection](https://user-images.githubusercontent.com/67278094/107148570-30184b80-6954-11eb-8c6d-442aadceeaeb.png)

![selected_walls_export](https://user-images.githubusercontent.com/67278094/107148574-40302b00-6954-11eb-9bd6-bb434f0cc90d.png)

![exported_features_of_selected_walls](https://user-images.githubusercontent.com/67278094/107148579-44f4df00-6954-11eb-87d6-f5e78e3663c5.png)

Is this problem well known or is it new so I need to create a more detailed example with dataset and detailed description?

Used QGIS Version is 3.14

**Comment by gioman** [comment]
> Used QGIS Version is 3.14

@tschmetzer it is  too old. Try the latest 3.16 with a new QGIS profile (no 3rd party plugins installed).

if the problem persist you must tell us more: what type of datasource (format? is table? is a view?, etc.) also it would be better if you can attach a sample of the problematic data.

**Comment by roya0045** [comment]
Could it be a multiline saved to line issue ?

**Comment by rduivenvoorde** [comment]
Or (if data is geopackage), maybe related to https://github.com/qgis/QGIS/issues/36291(being there is no uniek id as first column)?

**Comment by tschmetzer** [comment]
Guys, really sorry to keep you busy. I just upgraded my QGIS to version 3.16.3 and everything works now as it should. 
I was using an ESRI shapefile with a MultiPolygonZ geometry as input and I hadn't changed anything besides a new file name for the export.
