### ISSUE TITLE
crashed during projection transformation

### ISSUE THREAD

**Issue by nyerges1** [qgis/QGIS#41390]
## User Feedback

During projection tranformation.

## Report Details

**Crash ID**: [ffc485992db59bda633a330389c3d8b52f05270c](https://github.com/qgis/QGIS/search?q=ffc485992db59bda633a330389c3d8b52f05270c&type=Issues)

**Stack Trace**
<pre>
VSICreateCachedFile :
</pre>

**QGIS Info**
QGIS Version: 3.16.3-Hannover
QGIS code revision: 94ac9f21b8
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by roya0045** [comment]
More info needed. The vsi trace comes from gdal.

What data, what tranform, any ways to replicate?

**Comment by gioman** [comment]
@nyerges1 also try with a new QGIS profile no 3rd party plugins installed. If the problem persist add *detailed* steps to replicate and also sample project+data.

**Comment by nyerges1** [comment]
@roya0045 @gioman Thanks for you help. I'm working on it. Probably the problem was with the original projection. QGIS was just after the install, and no 3rd party involved.

**Comment by gioman** [comment]
Closing for lack of feedback.
