### ISSUE TITLE
Crash trying to load ArcGis community map vector tiles

### ISSUE THREAD

**Issue by Houska1** [qgis/QGIS#41401]
OSGeo4W 3.17 Master

I've used Maptiles vector tiles successfully, but tried using ArcGis Living Atlas' community basemap vector tiles.
Generated the hard crash below (after not responding for a while).

Now, I'm not sure one *should* be able to use ArcGis' tiles with QGIS (usage rights/authentication, and maybe a ArcGis vs Mapbox syntax issue too, not sure). But if not valid, shouldn't crash as outcome.

I added a connection in the Browser under vector tiles as below:

- URI: https://basemaps.arcgis.com/arcgis/rest/services/World_Basemap_v2/VectorTileServer
- Style file: https://www.arcgis.com/sharing/rest/content/items/273bf8d5c8ac400183fc24e109d20bcf/resources/styles/root.json?f=pjson
(the above are from https://www.arcgis.com/home/item.html?id=273bf8d5c8ac400183fc24e109d20bcf )
- No login/authentication (also possible this is the problem, but again, shouldn't hard crash in response)

---

Crash ID: cb50c884db2346ea0a850400ac82e4892702f852

Stack Trace
QgsMapBoxGlStyleConverter::parseFillLayer qgsmapboxglstyleconverter.cpp:317
QgsMapBoxGlStyleConverter::parseLayers qgsmapboxglstyleconverter.cpp:107
QgsMapBoxGlStyleConverter::convert qgsmapboxglstyleconverter.cpp:48
QgsVectorTileLayer::loadDefaultStyle qgsvectortilelayer.cpp:462
QgisApp::handleDropUriList qgisapp.cpp:2134
::operator() qgisapp.cpp:2001
QtPrivate::FunctorCall,QtPrivate::List,void, >::call qobjectdefs_impl.h:128
QtPrivate::Functor,0>::call,void> qobjectdefs_impl.h:239
QtPrivate::QFunctorSlotObject,0,QtPrivate::List,void>::impl qobjectdefs_impl.h:427
QMetaObject::activate :
QTimer::timerEvent :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:471
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32Private::sendTimerEvent :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1637
WinMain mainwin.cpp:197
__scrt_common_main_seh exe_common.inl:253
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.17.0-Master
QGIS code revision: 15267f9e6c
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.3.0dev

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

**Comment by gioman** [comment]
@Houska1 no crash on master with Ubuntu 20.04. Just to be sure... try with a new QGIS profile, no 3rd party plugins installed.

**Comment by Houska1** [comment]
Hmm. New profile does _not_ fix things **if I try to add the layer to my current project**. But in the process I discovered that it is **fine in either profile if I add layer to a brand new project**. And also fine if I add the layer in a new project, save it as a .qlr file, and then add the layer into my current project from the .qlr file (as opposed to direct from the connection in the browser).

So let's leave this in Feedback and I'll try to generate a minimal project in which it fails (my current project is big and unwieldy to share).

**Comment by gioman** [comment]
> my current project

@Houska1 what CRS has your project?

**Comment by Houska1** [comment]
2951. But that's not the problem either. I tried brand new project in 3857 and 2951, both fine.

**Comment by nyalldawson** [comment]
> Now, I'm not sure one should be able to use ArcGis' tiles with QGIS

It should definitely be working fine

> (usage rights/authentication

Basically depends on your particular license setup with ESRI. For commercial users of AGOL it's NOT against their TOS to use these resources in other clients. For free users, it is. But that's up to you to manage -- the AGOL service itself doesn't police the use of these services.
