### ISSUE TITLE
crash when starting vertex tool to edit polygon feature

### ISSUE THREAD

**Issue by beerockxs** [qgis/QGIS#41415]
## User Feedback

started vertex tool editiing in memory polygon layer

## Report Details

**Crash ID**: [938047eed6c48915cad9c1dca7266e6a612cb75a](https://github.com/qgis/QGIS/search?q=938047eed6c48915cad9c1dca7266e6a612cb75a&type=Issues)

**Stack Trace**
<pre>
QgsRasterRenderer::setOpacity :
QgsRasterRenderer::setOpacity :
QgsRasterRenderer::setOpacity :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.17.0-Master
QGIS code revision: cf37cb94f3
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.3.0dev
Running against GDAL: 3.3.0dev

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by gioman** [comment]
@beerockxs please try with a new QGIS profile, no 3rd party plugins installed. If the problem persist please add exact steps to replicate and a sample project+data as well.

**Comment by roya0045** [comment]
I fail to see how the vertex tool causes crash when rendering a raster.

**Comment by roya0045** [comment]
My best guess would be that you ran out of resource during the indexing phase while rendering a raster.

**Comment by beerockxs** [comment]
There is no raster layer in the project.

**Comment by roya0045** [comment]
Any basemap or other web map services?

**Comment by gioman** [comment]
Unclear how to replicate without a sample project. Closing for lack of feedback.
