### ISSUE TITLE
Multi-step transformation for Web Mercator <-> GDA2020 crs's

### ISSUE THREAD

**Issue by PCON82** [qgis/QGIS#41418]
In QGIS 3.10.14 LTR, on the fly reprojections between web mercator (3857,900913,102113 etc) and GDA94/GDA2020 are inconsistent.

For example a wms source with both options for 3857 (Pseudo Mercator) and 3111 (VicGrid GDA94) offset each other by ~1.5 to NNE while viewed within a 7899 project (VicGrid GDA2020). This offset is the difference between GDA94 and GDA2020. Change the project to 3111 and the two wms layers now align. 

I believe this is due to null transformation between WGS84 and GDA94 (1150) /GDA2020 (8450) as per this Qld gov doc https://www.dnrme.qld.gov.au/__data/assets/pdf_file/0011/1458830/gda2020-datum-publish-data.pdf

This doc also mentions Esri are handling this by using a two-step approach with GDA94 as the intermediary, first transform GDA2020 to GDA94 and then to web mercator or web mercator to GDA94 then to GDA2020.

** Actual Request
Is this possible to have a two step on the fly reprojection within QGIS between web mercator crs's and GDA2020 crs's?

Yes simple solution is to only use project crs in 3111 (the intermediary) even though digitising to 7899 using 3857 source (7899 <-> 3111 aligns and 3857 <-> 3111 aligns) . But just throwing out there to see if the two step on the fly is possible.

**Comment by nyalldawson** [comment]
This needs filing with the "proj" library, not qgis. But ultimately it won't be solved in proj until new transform codes are added to the epsg registry to handle this situation. It's a known issue with icsm, and currently the null transform IS the correct and expected result. GDA2020 just isn't ready for use with wgs84 based datums (include web mercator)
