### ISSUE TITLE
Empty layer names adding Raster layer from GDAL / OGCAPI driver

### ISSUE THREAD

**Issue by jerstlouis** [qgis/QGIS#41428]
**Describe the bug**
When using the GDAL OGCAPI driver, adding a top-level OGC API landing page as a raster layer shows a dialog to select layers to add where all the layer names are empty, despite GDAL having non-empty `NAME` and `DESC` fields for each layers.
Suspecting special characters like `/` and `:` and `?` are part of the issue.

This makes it hard to use if a server has hundreds of collections and you have no idea which one you are adding.

**How to Reproduce**

Add OGCAPI:https://maps.ecere.com/ogcapi as a raster layer

**QGIS and OS versions**

Recent development build (QGIS 12e8130beb)
Windows 7 64 bit

**Additional context**

It might be desirable that GDAL returns the collection `id` as the NAME, and either the `title` or the `description` as the DESC.
![image](https://user-images.githubusercontent.com/5140074/107271260-fad63100-6a19-11eb-8139-0533b5a2d91d.png)

**Comment by gioman** [comment]
@jerstlouis shouldn't this be reported to GDAL?

**Comment by rouault** [comment]
> shouldn't this be reported to GDAL?

no, this is a QGIS bug. I'm on it

**Comment by gioman** [comment]
> no, this is a QGIS bug. I'm on it

ok cool.
