### ISSUE TITLE
Inconsistent treatment of case sensitivity in field names

### ISSUE THREAD

**Issue by enzedrailmaps** [qgis/QGIS#41426]
Some data providers allow field names using mixed case, others allow only lowercase. When creating a value map in data entry form definitions, mixed case can be used. However, the field name used in value maps is case sensitive, and will not match to a field in the layer if the case is wrong. This is inconsisten with the behaviour of other parts of a layer's styles, such as symbology rules, which will work in a case insensitive manner.

**Comment by rduivenvoorde** [comment]
@enzedrailmaps QGIS cannot change the fact that different providers need/want different case styles.
So it depends on if functionality used is to be interpreted by QGIS (then 'we' are boss, so can do whatever we want), OR if the field names are used/sent by the provider (as probably in value maps).

Can you maybe create some examples?

And/or do you have a solution for this yourself?

**Comment by gioman** [comment]
Closing for lack of feedback.
