### ISSUE TITLE
Imported GeoTIFF not using data extent to select CRS - NAD83 vs NAD83(CSRS)

### ISSUE THREAD

**Issue by bal-agates** [qgis/QGIS#41456]
**Describe the bug**
When I import a GeoTIFF created with EPSG 26913 "NAD83 / UTM zone 13N" it defaults to EPSG 2957 "NAD83(CSRS) / UTM zone 13N"

**How to Reproduce**
Enclosed is "gdalinfo" for one GeoTIFF that shows the problem.  The GeoTIFF was created using the QGIS raster georeferencer from an uncalibrated TIFF.  Note that GeoTIFF appears not to contain either EPSG 26913 or 2957 but is described in lower level details.  Using Project > Properties... and comparing EPSG 26913 and 2957 the only difference I see is the extent.  EPSG 26913 is for latitudes from 29° to 84° (my range) and EPSG 2957 is for latitudes from 49° to 84° (outside of my range).  My extent is available in the GeoTIFF.  QGIS does not appear to be using the extent in selecting a CRS.  

**Workarounds**
The PROJ4 parameters between EPSG 26913 and 2957 appear to be the same so this may not affect the calibration.  I am not knowledgeable enough to be certain it will not affect the calibration.  To eliminate any possible confusion I can manually select the expected CRS.  This is an extra step.

**QGIS and OS versions**
QGIS version | 3.10.10-A Coruña | QGIS code revision | 1869829378
-- | -- | -- | --
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.28.0 | Running against SQLite | 3.28.0
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS High Sierra (10.13)
Active python plugins | qgis_resource_sharing; QuickOSM; db_manager; MetaSearch; processing

**Additional Notes**
I believe the NAD83(CSRS) are for "Canadian Spatial Reference System" and might be optimized for higher latitudes.  My data was for the United States.  Even if it doesn't matter for my case there could be other cases where not checking the data extent against the CRS extent might matter.

[gdalinfo.txt](https://github.com/qgis/QGIS/files/5952684/gdalinfo.txt)

**Comment by gioman** [comment]
@bal-agates attach/link the datatset, thanks.

**Comment by bal-agates** [comment]
The problem I encountered is more nuanced than I first thought.  Enclosed is a bunch of data with test cases.  To see the problem:
 
1. Create a new QGIS project
2. In Project > Properties... Set the CRS to EPSG:26913
3. Import <pactola_dam_c255_lzw_2_georef.tif>

Upon import I first see a dialog warning <Screen captures/06 message when importing into project.png> displaying the Source CRS as EPSG:2957.  After clicking OK the image is displayed and the project CRS (lower right corner) has been changed to EPSG:2957.  I have saved this state as <nad83_csrs_2.qgz>.  There is an anomaly that may or may not be related in that the import does not look correct until I change the layer properties Symbology "Render type" from "Multiband color" to "Paletted/Unique values".

Here is another sequence that does NOT show the problem.

1. Create a new QGIS project
2. In Project > Properties... Set the CRS to EPSG:26913
3. Import <pactola_dam_c255_lzw_1_georef.tif>

This is aved at <nad83_csrs_1.qgz>.  Note that on import I do not see the dialog warning and the image is displayed properly without manually changing the layer properties Symbology.

The only difference between these that I can see is the CRS info embedded in the GeoTIFF.  For the version with problems <pactola_dam_c255_lzw_2_georef.tif> it seems a lot more complicated.  This version came from the QGIS Raster > Georeferencer.

Information on how I created the datasets.

- After I had imported the original (larger image with apparent problem) I manually created a mask layer and used QGIS Raster > Extraction > Clip Raster by Mask Layer... to create a smaller test case.  When I exported the image I encountered problems getting the indexed colormap copied to the new image (an unrelated bug) so I generated an RGB image by selecting "Rendered image" in the export dialog creating <pactola_dam_rgb_1_georef.tif>.
- I had first suspected something with my paletted (indexed) colormap or LZW compression so external to QGIS I used GDAL's rgb2pct.py to convert the above image to indexed colormap and then gdal_translate to add the LZW compression creating <pactola_dam_c255_lzw_1_georef.tif>.  Each step appeared to carry through the CRS without my touching it.  Since this does not exhibit the problem it is probably not related to the GeoTIFF being indexed or using LZW compression.
- The original image I encountered problems with was created by importing a PDF into GIMP 2.10.22, cropping the image to the map portion, converting to 255 value indexed colormap and saving as TIFF with LZW compression.  I then georeferenced this with QGIS.  To simulate this path as closely as possible I manipulated <pactola_dam_rgb_1_georef.tif> using GIMP to strip off the georeference information, converting to indexed colormap and saving as TIFF with LZW compression to <pactola_dam_c255_lzw_2.tif>.  I then used the QGIS Raster > Georeferencer to calibrate this with using <pactola_dam_c255_lzw_2.tif.points> to create <pactola_dam_c255_lzw_2_georef.tif>.  This exhibits the same problem as I first saw.

One of my theories is there is something in the CRS of the "bad" GeoTIFF that is causing CRS parsing problems on import.  That could also explain why the paletted colormap is recognized in one case and not the other.  Another theory is that the georeferencer is adding CRS information to the GeoTIFF that it should not.

[NAD83_CSRS.zip](https://github.com/qgis/QGIS/files/5959068/NAD83_CSRS.zip)

**Comment by rouault** [comment]
The issue here is due to your QGIS version using old GDAL and PROJ versions. With latest versions, pactola_dam_c255_lzw_2_georef.tif is recognized with a custom CRS :
```
BOUNDCRS[
    SOURCECRS[
        PROJCRS["UTM Zone 13, Northern Hemisphere",
            BASEGEOGCRS["GRS 1980(IUGG, 1980)",
                DATUM["unknown",
                    ELLIPSOID["GRS80",6378137,298.257222101,
                        LENGTHUNIT["metre",1,
                            ID["EPSG",9001]]]],
                PRIMEM["Greenwich",0,
                    ANGLEUNIT["degree",0.0174532925199433,
                        ID["EPSG",9122]]]],
            CONVERSION["Transverse Mercator",
                METHOD["Transverse Mercator",
                    ID["EPSG",9807]],
                PARAMETER["Latitude of natural origin",0,
                    ANGLEUNIT["degree",0.0174532925199433],
                    ID["EPSG",8801]],
                PARAMETER["Longitude of natural origin",-105,
                    ANGLEUNIT["degree",0.0174532925199433],
                    ID["EPSG",8802]],
                PARAMETER["Scale factor at natural origin",0.9996,
                    SCALEUNIT["unity",1],
                    ID["EPSG",8805]],
                PARAMETER["False easting",500000,
                    LENGTHUNIT["metre",1],
                    ID["EPSG",8806]],
                PARAMETER["False northing",0,
                    LENGTHUNIT["metre",1],
                    ID["EPSG",8807]]],
            CS[Cartesian,2],
                AXIS["easting",east,
                    ORDER[1],
                    LENGTHUNIT["metre",1,
                        ID["EPSG",9001]]],
                AXIS["northing",north,
                    ORDER[2],
                    LENGTHUNIT["metre",1,
                        ID["EPSG",9001]]]]],
    TARGETCRS[
        GEOGCRS["WGS 84",
            ENSEMBLE["World Geodetic System 1984 ensemble",
                MEMBER["World Geodetic System 1984 (Transit)"],
                MEMBER["World Geodetic System 1984 (G730)"],
                MEMBER["World Geodetic System 1984 (G873)"],
                MEMBER["World Geodetic System 1984 (G1150)"],
                MEMBER["World Geodetic System 1984 (G1674)"],
                MEMBER["World Geodetic System 1984 (G1762)"],
                ELLIPSOID["WGS 84",6378137,298.257223563,
                    LENGTHUNIT["metre",1]],
                ENSEMBLEACCURACY[2.0]],
            PRIMEM["Greenwich",0,
                ANGLEUNIT["degree",0.0174532925199433]],
            CS[ellipsoidal,2],
                AXIS["geodetic latitude (Lat)",north,
                    ORDER[1],
                    ANGLEUNIT["degree",0.0174532925199433]],
                AXIS["geodetic longitude (Lon)",east,
                    ORDER[2],
                    ANGLEUNIT["degree",0.0174532925199433]],
            USAGE[
                SCOPE["Horizontal component of 3D system."],
                AREA["World."],
                BBOX[-90,-180,90,180]],
            ID["EPSG",4326]]],
    ABRIDGEDTRANSFORMATION["Transformation to WGS84",
        METHOD["Position Vector transformation (geog2D domain)",
            ID["EPSG",9606]],
        PARAMETER["X-axis translation",0,
            ID["EPSG",8605]],
        PARAMETER["Y-axis translation",0,
            ID["EPSG",8606]],
        PARAMETER["Z-axis translation",0,
            ID["EPSG",8607]],
        PARAMETER["X-axis rotation",0,
            ID["EPSG",8608]],
        PARAMETER["Y-axis rotation",0,
            ID["EPSG",8609]],
        PARAMETER["Z-axis rotation",0,
            ID["EPSG",8610]],
        PARAMETER["Scale difference",1,
            ID["EPSG",8611]]]]
```
which is appropriate given its content:
```
$ listgeo NAD83_CSRS/pactola_dam_c255_lzw_2_georef.tif
Geotiff_Information:
   Version: 1
   Key_Revision: 1.0
   Tagged_Information:
      ModelTiepointTag (2,3):
         0                 0                 0                
         620760.056        4881661.112       0                
      ModelPixelScaleTag (1,3):
         3.04927106418328  3.04927106418328  0                
      End_Of_Tags.
   Keyed_Information:
      GTModelTypeGeoKey (Short,1): ModelTypeProjected
      GTRasterTypeGeoKey (Short,1): RasterPixelIsArea
      GTCitationGeoKey (Ascii,33): "UTM Zone 13, Northern Hemisphere"
      GeographicTypeGeoKey (Short,1): User-Defined
      GeogCitationGeoKey (Ascii,86): "GCS Name = GRS 1980(IUGG, 1980)|Datum = unknown|Ellipsoid = GRS80|Primem = Greenwich|"
      GeogGeodeticDatumGeoKey (Short,1): User-Defined
      GeogAngularUnitsGeoKey (Short,1): Angular_Degree
      GeogEllipsoidGeoKey (Short,1): User-Defined
      GeogSemiMajorAxisGeoKey (Double,1): 6378137          
      GeogInvFlatteningGeoKey (Double,1): 298.257222101    
      GeogPrimeMeridianLongGeoKey (Double,1): 0                
      GeogTOWGS84GeoKey (Double,3): 0                0                0                
      ProjectedCSTypeGeoKey (Short,1): User-Defined
      ProjectionGeoKey (Short,1): Proj_UTM_zone_13N
      ProjLinearUnitsGeoKey (Short,1): Linear_Meter
      End_Of_Keys.
   End_Of_Geotiff.
```

I also verified that the georeferencer outputs a GeoTIFF with corret EPSG:26913 CRS when configuring that in the georeferencer. So nothing to fix. Just updating to recent GDAL & PROJ version is needed
