### ISSUE TITLE
Graphic Modeler fails to open table which it has just saved to PostgreSQL

### ISSUE THREAD

**Issue by Ellebjerg** [qgis/QGIS#41461]
Hi,

I am using Graphic Modeler to generate a polygon dataset and save it to a PostgreSQL database. The dataset is generated correctly, and when opened through Data Source Manager it is loaded without any problems. But when asking Graphic Modeler to open the data source as part of running the model, I get an error which is not even related to this table.

My table is saved as grunddata.geodk_vejnet_komplan, but the error in the QGIS log is:

WARNING    Erroneous query: SELECT 0, array_agg(DISTINCT st_srid("geometri")::text || ':' || UPPER(geometrytype("geometri"))) FROM "grunddata"."dbo_geo_jordstykker_kommune_ft" returned 7 [ERROR: column "ejerlavsnavn" of foreign table "dbo_geo_jordstykker_kommune_ft" converts OGR "String" to "bytea"

grunddata.dbo_geo_jordstykker_kommune_ft is a foreign table connected to SQL Server. It seems strange that an error in this foreign table should affect the loading of i well functioning ordinary table.

I don't know if this is an error in QGIS or in PG, but somehow it seems to concern the communication between the two.

The Graphic Modeler is a fine tool with great potential for making QGIS an even more valuable tool for handling data. A nice improvement would be the possibility to save data to an existing table in a database or to replace an existing table with a new one containing the data from the model.

Thanks for your contributions to a great product.

Best regards,
Lars Ellebjerg

**Comment by SrNetoChan** [comment]
Can you share your model? or a sample model where we can see what tools you are using?

I suggest you look into the Execute and Load SQL, may be what you need to load a table in postgreSQL.


@Ellebjerg said:
> The Graphic Modeler is a fine tool with great potential for making QGIS an even more valuable tool for handling data. A nice improvement would be the possibility to save data to an existing table in a database or to replace an existing table with a new one containing the data from the model.

It's already possible to do that. You can use the GDAL Export to PostgreSQL tool to export the result to the database. There are two options that will allow to either override an existing table, or append to the existing table.

![Export to PostgreSQL (New Connection)_343](https://user-images.githubusercontent.com/3607161/107460302-c795be00-6b4f-11eb-8ef4-0d9a216124bd.png)

**Comment by gioman** [comment]
@Ellebjerg I also think that this in not clear, having the model and the necessary data to to replicate the workflow seems necessary.

**Comment by gioman** [comment]
Closing for lack of feedback.
