### ISSUE TITLE
No source for landingpage JavaScript in QGIS server

### ISSUE THREAD

**Issue by sebastic** [qgis/QGIS#41468]
The lintian QA tool reported that the source for the landingpage JavaScript is missing, only the minified JS is included:
```
E: qgis source: source-is-missing resources/server/api/ogc/static/landingpage/js/app.fa6cb20b.js line length is 8064 characters (>512)
E: qgis source: source-is-missing resources/server/api/ogc/static/landingpage/js/chunk-123bc409.ef3c4d35.js line length is 32768 characters (>512)
E: qgis source: source-is-missing resources/server/api/ogc/static/landingpage/js/chunk-5cedae10.b1aed77d.js line length is 32768 characters (>512)
E: qgis source: source-is-missing resources/server/api/ogc/static/landingpage/js/chunk-db289a14.4c4313be.js line length is 13993 characters (>512)
E: qgis source: source-is-missing resources/server/api/ogc/static/landingpage/js/chunk-vendors.ebebb286.js line length is 11861 characters (>512)
```
```
$ ls -l resources/server/api/ogc/static/landingpage/js/
total 3752
-rw-r--r-- 1 bas bas    8105 Jan 15 13:09 app.fa6cb20b.js
-rw-r--r-- 1 bas bas   31869 Jan 15 13:09 app.fa6cb20b.js.map
-rw-r--r-- 1 bas bas  283265 Jan 15 13:09 chunk-123bc409.ef3c4d35.js
-rw-r--r-- 1 bas bas 1075201 Jan 15 13:09 chunk-123bc409.ef3c4d35.js.map
-rw-r--r-- 1 bas bas  227266 Jan 15 13:09 chunk-5cedae10.b1aed77d.js
-rw-r--r-- 1 bas bas  764635 Jan 15 13:09 chunk-5cedae10.b1aed77d.js.map
-rw-r--r-- 1 bas bas   14045 Jan 15 13:09 chunk-db289a14.4c4313be.js
-rw-r--r-- 1 bas bas   49967 Jan 15 13:09 chunk-db289a14.4c4313be.js.map
-rw-r--r-- 1 bas bas  243652 Jan 15 13:09 chunk-vendors.ebebb286.js
-rw-r--r-- 1 bas bas 1123581 Jan 15 13:09 chunk-vendors.ebebb286.js.map
```

**Comment by elpaso** [comment]
Sources are here [1], nobody has found the time to move them yet.

The biggest issue is not copying the files though, it is the build/develop system that is alien technology to the QGIS universe, this is the reason why I'm maintaining a parallel implementation as a separate Python plugin I didn't integrate it with QGIS source tree in the firs place.

https://github.com/elpaso/qgis-server-landing-page-plugin/tree/master/plugins/landingpage/app

Anyway, feel free to move the sources where you see fit.

**Comment by sebastic** [comment]
jsonFormatter may serve as an example (#34586).

Just include the landingpage sources in the QGIS source tree.

The JS ecosystem is not particularly great when it comes to compatibility with Free Software principals.

Personally I wouldn't use any of the modern tools and just use plain unminified JS for any service that isn't plain HTML. It becomes just another script in that case like Python.

**Comment by elpaso** [comment]
@sebastic I agree in principle, but there are practical and technical good reasons for minifying js code.

**Comment by sebastic** [comment]
If non-minified JS is not an option for the landing page in QGIS, its sources must be included in the QGIS source tree.

Ideally building the minified JS files is also part of the QGIS build process.

The current situation is not acceptable as the preferred form of modification is not available.

**Comment by elpaso** [comment]
@sebastic  got it. https://github.com/qgis/QGIS/pull/41469
