### ISSUE TITLE
Add singleband/pseudocolor render type for WMS raster

### ISSUE THREAD

**Issue by lucamanga** [qgis/QGIS#41470]
I noted that single-band WMS has only a render type available, "single band".

Can it have the other render types, for example "single band - pseudocolors"? This is why I have converted an ASC -> GeoTiff and it is served by a WMS server.

**Comment by gioman** [comment]
@lucamanga a WMS do not get the raw data from the server, I guess this is the reason that not all symbology methods are available. If the same layer is published as WCS then the client receives the raw data, and the user can apply the usual methods for raster symbology.

**Comment by lucamanga** [comment]
Thank you. Using the raster via WCS source is THE solution!
