### ISSUE TITLE
Signal committedAttributeValuesChanges not emitted when project in auto transaction mode

### ISSUE THREAD

**Issue by ygversil** [qgis/QGIS#41477]
**Describe the bug**

Having two layers in the same GeoPackage loaded in the same project, and having the project in "auto transaction" mode, when one tries to edit a feature's attribute in one layer and to save the changes, the signal `committedAttributeValuesChanges` is not emitted.

This is especially annoying when using the Offline Editing plugin: when switching the project to auto transaction mode (so that all layers go into edit mode at once), every modified feature is not recorded by the plugin since the plugin relies on the `committedAttributeValuesChanges` signal to record changes. Thus all attribute changes are lost.

**How to Reproduce**

1. Create a new GeoPackage layer named `layer_a` in a file named `test_auto_transaction_signal_bug.gpkg`. It can be a `Point` layer. Give it a field named `name` with type text.
2. Add a point to this layer with name `Foo`: switch to edit mode, add the point wherever you like, fill the form with name `Foo`, and exit edit mode saving the changes.
3. Create a new GeoPackage layer named `layer_b` in the same file. `No geometry` and no field.
4. Go to `Project > Properties`, `Data Sources` tab, and check the `Automatically create transaction groups where possible` box. Close the properties dialog.
5. Back in the main window, select the `layer_a` layer and switch to edit mode. Thanks to the project properties, the `layer_b` layer also switch automatically to edit mode.
6. Open the Python console: `Plugins -> Python Console`.
7. Type the following Python commands that connect a simple function to the `committedAttributeValuesChanges` signal. The function simply logs the layer id to the messages panel.
    ```python
    >>> def log_changed_values(layer_id, changes):
    ...     QgsMessageLog.logMessage(layer_id, 'General', Qgis.Info)
    ...
    >>> layer = iface.activeLayer()
    >>> edit_buffer = layer.editBuffer()
    >>> edit_buffer.committedAttributeValuesChanges.connect(log_changed_values)
    ```
8. Edit the point previously added in `layer_a`, changing its name to `Bar`. Leave edit mode saving the changes.
9. Look at the messages panel,`General` tab: there is no message indicating that the function has been ran. **The expected result is a message with the `layer_a` id.**
10. Now go back to `Project > Properties` and uncheck the `Automatically create transaction groups where possible` box.
11. Back in the main window, select the `layer_a` layer and switch to edit mode (now `layer_b` stays in normal mode).
12. In the Python console type the following two commands refreshing the edit buffer and the signal connection (since we have leaved edit mode before entering it again):
    ```python
    >>> edit_buffer = layer.editBuffer()
    >>> edit_buffer.committedAttributeValuesChanges.connect(log_changed_values)
    ```
13. Edit the point previously added in `layer_a`, changing its name to `Baz`. Leave edit mode saving the changes.
14. Look at the messages panel,`General` tab: there is a message with `layer_a` id.

**QGIS and OS versions**

QGIS 3.16.3, both on Windows 10 et Archlinux.

**Additional context**

Oddly, everything seems to work fine when `layer_a` is the only layer in the GeoPakage, that is when `layer_b` is not loaded or does not exists at all.
I haven't tried with other signals like `committedGeometriesChanges`.

**Comment by elpaso** [comment]
This is not a trivial fix, apparently when the transaction groups were implemented the contract was broken.
It is not only the signals that are not emitted, all other functions are broken as well (for instance `QgsVectorLayerEditBuffer::changedAttributeValues` and all others).

**Comment by elpaso** [comment]
Not sure if we can close this after #41539, @ygversil can you please check if this is still an issue?
