### ISSUE TITLE
Bad allocation when opening a project

### ISSUE THREAD

**Issue by FilatovAV** [qgis/QGIS#41497]
when I try to open the properties of the 2g_05x2 line, an error appears - "Bad allocation"

![image](https://user-images.githubusercontent.com/38399107/107618532-c3a69080-6c62-11eb-892a-f512f9ba95f0.png)

QGIS version
![image](https://user-images.githubusercontent.com/38399107/107618617-e9cc3080-6c62-11eb-8360-c56411d7b276.png)
[cdf2000.zip](https://github.com/qgis/QGIS/files/5964072/cdf2000.zip)

The project file is attached

**Comment by gioman** [comment]
@FilatovAV your project point to a bunch of data (postgis?) that are not accessible. Just the project is not enough to test locally what is going on and eventually troubleshoot the problem. Please attach a sample project+data that demonstrates the issue, also please try with a new QGIS profile (and no 3rd party plugins).

**Comment by gioman** [comment]
We all actually the "bad allocation" message show when opening the attached project, but still not data in it, and that can be a factor.

**Comment by FilatovAV** [comment]
The problem manifests itself when we want to open the properties of the line type. Third-party plugins are not used.

**Comment by FilatovAV** [comment]
The problem is that if there is no data source, the error should not appear.

**Comment by FilatovAV** [comment]
Therefore, I do not agree with the name of the problem that was issued.

**Comment by gioman** [comment]
> Therefore, I do not agree with the name of the problem that was issued.

@FilatovAV it is not a general issue (when opening a project with missing layers), so the title is correct.

**Comment by FilatovAV** [comment]
it looks like I figured it out this is the problem of incorrect paths to svg files

**Comment by rduivenvoorde** [comment]
@FilatovAV maybe if you can provide more info? Then we can maybe add some security measures that this will not happen, even when there are incorrect svg path/files?
Was it pointing to non-excisting path's?
Or corrupt svg files?
Or do I need a point file, with svg symbols and... the symbol removed?
Plz help :-)

**Comment by FilatovAV** [comment]
1. An error message appears when there are no files in the specified path;
2. But here is what is very strange. This path changes in some incredible way when you open the file on another computer, the reason is completely unclear to me.
![1](https://user-images.githubusercontent.com/38399107/107805035-ce9e1580-6d75-11eb-9b6c-5993c6c29fbf.png)

**Comment by gioman** [comment]
@FilatovAV could you please provide a zip file will all the SVGs that are referenced in your project?

L2g_476_1.svg
L2g_476_2c.svg
...
...
...

thanks.

**Comment by FilatovAV** [comment]
I attach the files
[Egs2000.zip](https://github.com/qgis/QGIS/files/5973894/Egs2000.zip)

**Comment by gioman** [comment]
The project behaves in a very weird way: even after editing it at making it point to the provided SVG files it still has issues when opening it. It must be said that the project was *not* provided with the necessary data and that the layer styles being used have many data defined properties. It's unclear to me if with the datasources the project opens ok or not. @FilatovAV

**Comment by FilatovAV** [comment]
I fixed the project by specifying the path to the data again. Whether there is a data source or not is not important, the project does not give that error. 

At the same time, I wrote the path to the svg line elements as "C:/Egs/Qgis/Egs2000/Line/L2g_121_3.svg" but when we opened this project on another computer, we saw a slightly different path, which was no longer suitable.

[cdf2000.zip](https://github.com/qgis/QGIS/files/5978373/cdf2000.zip)

**Comment by gioman** [comment]
> I fixed the project by specifying the path to the data again. Whether there is a data source or not is not important, the project does not give that error.

@FilatovAV closing then?

**Comment by FilatovAV** [comment]
But we didn't find the reason

**Comment by gioman** [comment]
> But we didn't find the reason

Can you attach the data please?

**Comment by FilatovAV** [comment]
Tell me how? Maybe I can attach at least some of it
But I don't think the reason for the error is in the data source

**Comment by gioman** [comment]
> Tell me how?

create a zip. If your data is postgis create a dump with pg_dump.

**Comment by FilatovAV** [comment]
sent by mail

**Comment by gioman** [comment]
@FilatovAV I have been able to put together your project (but what a pain!), I think

![Screenshot_20210215_214142](https://user-images.githubusercontent.com/1951107/107995944-166fa780-6fd7-11eb-97d3-4e4f7bfbacb0.png)

Then I tried remove the SVG symbols from where the project expect them (attaching them again as they seem vanished from the thread) and no "bad allocation" on project load or while opening the layers properties

[Egs2000.zip](https://github.com/qgis/QGIS/files/5984265/Egs2000.zip)

Same thing if I pull the data, no "bad allocation".

**Comment by FilatovAV** [comment]
Yes, but the reason for this is not clear. 
And the very appearance of the error can cause big problems. 
If there are many such errors. It is better to show it implicitly.

**Comment by rduivenvoorde** [comment]
This could very much be a typical Windows thing. Did we not have this error also in case of huge images being created (overflowing Windows max images size limits or so)? Not sure if Windows is helpful to get info about this....
I think it's also hard (and a lot of code) to handle all possible issues that can popup if a user creates very complex styling/images/etcetc, but then pull away data/images...

**Comment by rduivenvoorde** [comment]
@FilatovAV the svg paths are relative and created based on the SVG search paths given by the user (OR 'guessed' by QGIS during installation or creation of a profile). You are right that it is sometimes unclear why I still drag so many (old) svg-paths with me....

**Comment by FilatovAV** [comment]
Maybe you're right. But in previous versions of QGIS, the message did not appear. 
And "? " always signals to us that the data is not found.
This was the reason why I couldn't figure out what was going on at first.

**Comment by gioman** [comment]
> I think it's also hard (and a lot of code) to handle all possible issues that can popup if a user creates very complex styling/images/etcetc, but then pull away data/images...

@rduivenvoorde I agree. This seems to be an edge case. 

@FilatovAV I tested also on Windows: no bad allocation even when pulling the SVG or the data from under the project.

![Screenshot_20210216_094628](https://user-images.githubusercontent.com/1951107/108046129-31283780-703c-11eb-9ce1-8240f12d42e9.png)

**Comment by FilatovAV** [comment]
when using this qgz file, there is a problem, then I fixed it by writing the paths
[cdf2000.zip](https://github.com/qgis/QGIS/files/5988242/cdf2000.zip)

**Comment by gioman** [comment]
> when using this qgz file, there is a problem,

@FilatovAV yes I see. But the main point/question here is... how do you get to the point that you have such broken project?

What I tried to do was 

1) fix your project (both the paths to the SVG and the datasources)

2) move the SVG to another location and make unavailable the datasources

the above does *not* cause the project to break down as the ones you are posting. So... what are the steps to break them?

**Comment by FilatovAV** [comment]
Unfortunately, I did not do this=) 
We only know that the description of one or more linear objects was changed and then everything was broken

**Comment by gioman** [comment]
> Unfortunately, I did not do this=)

@FilatovAV so what you would like us to do?



>  We only know that the description of one or more linear objects was changed and then everything was broken

Can you explain what "changing the description" means? We need a clear way to replicate the issue (starting from a working project).

**Comment by FilatovAV** [comment]
By changing the description of a linear object, I mean all these settings
![image](https://user-images.githubusercontent.com/38399107/108063859-e83ca700-706c-11eb-9024-27fd1488fcbc.png)

**Comment by gioman** [comment]
>  I mean all these settings

@FilatovAV I believe it is still too vague.

**Comment by FilatovAV** [comment]
Yes, I also did not find the cause of the problem

**Comment by gioman** [comment]
> Yes, I also did not find the cause of the problem

@FilatovAV We can leave this open, but without a clear way to replicate then likely no developer will ever touch this issue.

**Comment by FilatovAV** [comment]
Well, let's close it =) If there are new cases, I will write to you, thank you very much =)
