### ISSUE TITLE
QGIS 3.10 in Print Composer, cannot add SVG file, instead QGIS imported jpg files from the folder, cannot remove jpg files 

### ISSUE THREAD

**Issue by JJDokes** [qgis/QGIS#41492]
In print composer I wanted to import my own svg file of a north arrow.  Inserted a stock/built in north arrow, clicked on it, went to Item Properties > Search Directories > Add, found the folder that had my svg file in it, clicked on Select Folder, and all images in the folder were added (svg, jpg, and png) to QGIS's print composer pictures folder, with no opportunity to pick a particular image (I just wanted the one svg I had of a north arrow, not all of the images in the folder).  Not wanting all images I tried to remove most of them using the Remove button, but that did not remove the files.

I searched my entire C drive for the file names of some of the images, but they were not found.  I assume QGIS changed the file names so they could not be found that way.  I looked through QGIS's folder where it stores the images for Print Composer, and did not find my images that were added/imported (I installed QGIS with OSGEO4).  I also tried searching App Data, though included in the search of C drive.

This may not be a bug and may just be my incompetence, but to me the following look like bugs:

1) All image files in a folder are added to QGIS's Print Composer upon clicking on Select folder when looking for the file to add using QGis's Print Composer after clicking the Add... button, and,

2)  Added/imported images cannot be removed using print composer's Remove button and the images cannot be found even with a search of the entire drive (apparently renamed to unknown names).

You should be able to replicate as follows:
1)  Start a map with QGIS 3.10,
2)  Open Print Composer and add a map,
3)  Add a north arrow to the map,
4)  Click on the north arrow and go to Item Properties > Search Directories > Add, then select a folder with multiple images in it to add to Print Composer's stock images.

Presto chango, all images in the folder should be imported into QGIS's Print Composer without warning, even if you don't want them all.

5)  Try to select any of the imported images and use the Remove button to remove them.  Nothing happens, nothing is removed.

Here is a screenshot of the files that were imported (though not wanted), in the search directories dialog.

![QGISproblem](https://user-images.githubusercontent.com/55560731/107601053-6961ed00-6bda-11eb-8727-760921b9329d.png)

Nothing in documentation I could find about where to find the image files I accidentally uploaded (not in the folder indicated in the image search dialog, or anywhere else I could find).

Not the end of the world and could just leave the files where they are, but...

THANK YOU FOR YOUR OUTSTANDING WORK ON QGIS!  IN CASE YOU DON'T KNOW IT YOU ARE HELPING MANY PEOPLE HELP MAKE THE WORLD A BETTER PLACE.

QGIS version | 3.10.10-A Coruña | QGIS code revision | 8b051b9a43
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | AzimuthDistanceCalculator; batch_gps_importer; beePen; CalculateGeometry; GarminCustomMap; leastcostpath; mmqgis; NITK_RS-GIS_17; qchainage; qgis2web; VectorBender; db_manager; processing; qdraw; ale; DigitizingTools

**Describe the bug**

**How to Reproduce**

4. See error -->

**QGIS and OS versions**

**Additional context**

**Comment by DelazJ** [comment]
>   4.  Click on the north arrow and go to Item Properties > Search Directories > Add, then select a folder with multiple images in it to add to Print Composer's stock images.
>
>Presto chango, all images in the folder should be imported into QGIS's Print Composer without warning, even if you don't want them all.

You selected a folder! So you add what is in the folder; QGIS has no means to know what image you want or not. It just scans a folder, shows you what is in the folder you add. It's a folder based feature, not file by file. Up to you to select the file to use in your project.
About the remove button, I confess that I am unable to find what it actually does.

Anyways... 3.10 is End of life (no more fixes expected) and this dialog has been restructured in newer releases (e.g 3.16): no more add/remove button and you can select single file from your folders. Worth giving a test.

**Comment by JJDokes** [comment]
DelazJ, thank you for your excellent answer.  I did not tell QGIS to add a folder, I was on my way to find the file in the folder so I could add that.  Regardless, it sounds like that problem is fixed in 3.16.  From a developer's perspective 3.10 is end of life.  However, from a non-developer user's perspective 3.10 is listed as the stable release on the download page.  This problem was not a killer for me and I can leave the images where they are, and sounds like it is fixed in 3.16, so I will probably wait until 3.16 is listed as a stable release and switch then.  

Thank you for your work on QGIS.  In my book you guys are heroes.  I see QGIS as a great equalizer, between John and Jane Q. Public and Government and large corporations.  You and others working on QGIS give anyone a chance to make their point by making and presenting meaningful maps without the need for a huge budget or government funding.  Very good.

**Comment by gioman** [comment]
> . However, from a non-developer user's perspective 3.10 is listed as the stable release on the download page

@JJDokes correct, but 3.16 will be LTR in a matter of days, this also means thata is unlikely that any fix will be ported to 3.10, so we can safely close this.

**Comment by JJDokes** [comment]
gioman, thank you for that good news about 3.16 soon being the stable release.  I will check and switch when 3.16 is the stable release.  I agree with closing.
