### ISSUE TITLE
Add range to rule is not working

### ISSUE THREAD

**Issue by levivarga91** [qgis/QGIS#41513]
**Describe the bug**
I would like to use refine selectes rulet-> add range to rule, but it is not working. It is displayed only the main rule symbol.

**How to Reproduce**

![2021-02-11_16h29_42](https://user-images.githubusercontent.com/61519338/107658594-923fbc00-6c86-11eb-979d-613670e9eb71.png)

**QGIS and OS versions**

Qgis 3.16

**Additional context**

**Comment by roya0045** [comment]
That could be an issue in your expressions. Can you share the project so someone can validate? Sample data might be needed if possible.

Also please provide all needed informations.

**Comment by DelazJ** [comment]
What happens if you deactivate the display of the orange outline top symbol (in that rule's properties dialog)?

**Comment by levivarga91** [comment]
oooooohm of course nothing.

**Comment by levivarga91** [comment]
okayyyy! roya0045 is true! The problem was been with the expression.  The program automatically uses ( marker  insted of  " thus it don't interpret  the rules. So thx for the helping!

**Comment by roya0045** [comment]
So we can close this?

**Comment by levivarga91** [comment]
yes thx!

**Comment by levivarga91** [comment]
yes thx!
