### ISSUE TITLE
Be able to edit in the Provider Feature Filter

### ISSUE THREAD

**Issue by bokkenka** [qgis/QGIS#41531]
**Feature description.**
It would be wonderful to be able to type directly into the Provider Feature Filter rather than having to open the Query Builder.

**Additional context**
I usually have a filter on my data...  Something like `"COMP_NO" IN (70, 76, 77)`.  When I need to change it, I usually need to add or change a number in the tuple.  It would be nice to be able to just change the query right there rather than having to open the Query Builder.

![qgis_screenshot](https://user-images.githubusercontent.com/30788178/107776490-3e28ec00-6d07-11eb-8e2b-b3b620c5a80b.png)

**Comment by nicogodet** [comment]
Right click in layers tree -> "Filter..."
![image](https://user-images.githubusercontent.com/39594821/107780770-6df7e400-6d47-11eb-939b-7834a6f54c72.png)

It opens the query builder instead of going in layer properties, source then query builder.

Is it what you are looking for ?

**Comment by bokkenka** [comment]
Yes, thank you very much.  I missed it there.  That will work prefectly.
