### ISSUE TITLE
Exp or Pow and Exp10 in Mathematical Functions

### ISSUE THREAD

**Issue by PedroVenancio** [qgis/QGIS#41533]
In QGIS Expressions we have **ln**, **log10** and **log** mathematical functions [0]. So, **base e**, **base 10** and **base n** logarithms.

However, we only have **exp** (**base e** exponential).

So, it would be good to have **exp10** and an **expn** (or **pow**) that would return the value of exponential of the passed value and base.

 [0] https://docs.qgis.org/3.16/en/docs/user_manual/working_with_vector/functions_list.html#mathematical-functions) has

**Comment by roya0045** [comment]
You do know that the standard exponent operator works in expressions. We don't need duplicate things if `^` works as intended.

I'm not sure about the use of this request...

**Comment by PedroVenancio** [comment]
You're right, I did not tried `^` operator. I've searched for "pow" / "power" / "exp" and did not searched for the operator. Maybe the search box should also search in functions help, but that is another theme.

**Comment by roya0045** [comment]
Just like 'plus' or 'add' doesn't pop up.  Having an alias method can be a slippery slope. But I agree that this button can be overlooked.

**Comment by PedroVenancio** [comment]
@roya0045 
My thinking here was based on the mathematical functions that we have in Expressions, that are similar to the functions present in spreadsheet software, like https://help.libreoffice.org/3.4/Calc/Mathematical_Functions

There the redundance is also present with the operator `^`. But I agree that there are more important things to think and work than in something that is solved by the operator!
