### ISSUE TITLE
Qgis: Semi-automatic Plugins- Random Forest (AttributeError)

### ISSUE THREAD

**Issue by SyedTuhinAli** [qgis/QGIS#41534]
I am using QGIS Semi-automatic Plugins. When I try to run the Random Forest classifier, the following error displayed "AttributeError: 'str' object has no attribute 'setContrastEnhancement' " please find the error text below:

[random forest error.txt](https://github.com/qgis/QGIS/files/5974000/random.forest.error.txt)

Qgis: v 3.16.3
Semi-automatic Plugins: v. 7.6.0 
Python: built-in with the Qgis

snap gpt executable file "C:\Program Files\snap\bin\gpt.exe" in the processing setting has already provided

The maximum-likelihood classifier works.

Thanks

**Comment by gioman** [comment]
@SyedTuhinAli ypu must write the to the plugin/s author/s.
