### ISSUE TITLE
GPS related expressions

### ISSUE THREAD

**Issue by saberraz** [qgis/QGIS#41543]
It would be helpful to have GPS specific expression. One use case would be having geo-fencing in QGIS based mobile apps. Another use case would be collection of GPS metadata

- gps position (something like now(gps_position) can report the current location)
- gps time
- vertical/horizontal accuracy
- number of satellites
- correction age
- ....

**Comment by jonnyforestGIS** [comment]
Hi @saberraz, this Feature request is related with this #35846 ?

Cheers

**Comment by nyalldawson** [comment]
These are available in Qfield - possibly it's straightforward to move their code core?

**Comment by saberraz** [comment]
Thanks @jonnyforestGIS . I close this in favour of my original one.

@nyalldawson in not aware of QF capturing or having the expressions, but it makes sense to have it in QGIS.
