### ISSUE TITLE
jpg quality slider in Composer

### ISSUE THREAD

**Issue by ChameleonScales** [qgis/QGIS#41559]
**Feature description.**
A way to set the jpg compression level when exporting images from the composer.

**Additional context**
Currently the jpeg quality is quite low and shows compression artifacts. I sometimes have to first export in png and then convert to jpg with a 95% quality from imagemagick.
A slider that would be in one of the export dialogs would remove that step for me. It could be either in the "Save Layout As" (file browsing) dialog or the following "Export Options" dialog.
It could also show up in the "Atlas" tab of the composer under "Output".

**Comment by bazmap** [comment]
I'm amazed that this feature isn't already available... A must have :-)
