### ISSUE TITLE
Gpkg Point layer Category symbology not working with filtered layer

### ISSUE THREAD

**Issue by ntrip6** [qgis/QGIS#41565]
**Describe the bug**

**How to Reproduce**

4. See error -->

**QGIS and OS versions**

**Additional context**

**Comment by gioman** [comment]
@ntrip6 can you add the requested info? thanks.


Describe the bug

How to Reproduce

    Go to '...'
    Click on '....'
    Scroll down to '....'
    See error -->

QGIS and OS versions

Additional context

**Comment by ntrip6** [comment]
How to reproduce:
1. create Point layer in a local geopackage with Integer Feature ID number field (FeatID) and an Integer Category field for symbology filled with 0 and 1. My dataset has thousands records.
2. Add a Provider Feature Filter query to the Layer Source properties such as 
"FeatID" > 26 AND "FeatID" < 300
3. Save properties and update layer.
4. Under Layer Symbology create a Categorized symbology using the Category field
0 with one symbol, 1 with another, and QGIS offers "all other values".

error --> The only symbols that appear are "All other values". The categories 0 and 1 do not show.
Turning off the Provider Filter removed the issue.

**Comment by gioman** [comment]
>  How to reproduce:

@ntrip6 can't confirm here, you may want to attach/link your dataset and sample project.

![Screenshot_20210215_200525](https://user-images.githubusercontent.com/1951107/107989009-38622d80-6fc9-11eb-944b-2ad23cb1fd37.png)

**Comment by ntrip6** [comment]
Thank you for your quick followup.  It seems like it was a hiccup in display refresh pointing to the local GPKG because it's now working for me after saving and reloading the layer.
