### ISSUE TITLE
SQLite files containing 2 or more raster layers are incorrectly added to the map

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/QGIS#41560]
**Describe the bug**

When a **SQLite** file contains more than 1 raster layer and you **drag and drop** the **SQLite** file into the map or you use the "**Data Source Manager** / Raster" dialog window to add the layer to the map, then:

the "Select Raster Layers to Add..." dialog window appears showing only values in the "Layers ID" column but with the "Layer name" column blank

![image](https://user-images.githubusercontent.com/16253859/107935923-4c367100-6f82-11eb-8599-c65ec25ea1ca.png)

The selected raster layer(s) are then added with "Dataset Description":

`RASTERLITE:filepath/filename.sqlite,table=rasterlite_layer_name`

but with a blank name instead of a proper name like "raster_layer_name" or "filename raster_layer_name" (as for vector layers).

The issue doesn't occur with raster layers contained in a GeoPackage, (With QGIS 3.4.x and 3.10.1 the issue occurred also for raster layers contained in a GeoPackage).

Using the **Browser panel** is not possible to add to the map the rasterlite rasters contained in a sqlite file, but only the related metadata tables.

**How to Reproduce**

- add the file 2rlayer.sqlite (from the compressed archive [2rlayer.sqlite.zip](https://github.com/qgis/QGIS/files/5981023/2rlayer.sqlite.zip)) which contains two raster layers.

**QGIS and OS versions**

QGIS 3.16.3
Windows 7 / OSGeo4W

**Additional context**

Previously reported for QGIS 3.4 in https://issues.qgis.org/issues/20050 -> https://github.com/qgis/QGIS/issues/27872

**Comment by nyalldawson** [comment]
This seems to be fixed in master now -- can you confirm?
