### ISSUE TITLE
HTML frame dissapear when moving another item in map composer

### ISSUE THREAD

**Issue by WhitespaceQ** [qgis/QGIS#41579]
HTML frame on map composer in QGIS 3.16.3 will disappear if any other map element were moved using the 'Select/Move Items' tool.

1. Create a layout with HTML frame and any other object(s) touching the HTML frame
2. Move the other object using 'Select/Move Items' tool
3. The HTML frame will disappear 

**QGIS and OS versions**

Reproducible on QGIS 3.16.3 (64 bit) running on Windows 10 20H2

**Comment by gioman** [comment]
> Create a layout with HTML frame and any other object(s) touching the HTML frame

@WhitespaceQ can you attach a sample project or layout template, thanks.

**Comment by gioman** [comment]
Closing for lack of feedback.
