### ISSUE TITLE
Georeferencer: control point Y coordinate does not accept pasted data

### ISSUE THREAD

**Issue by Colins2** [qgis/QGIS#41589]
**Describe the bug**

When using the dialog to input control point coordinates, the X coordinate text box works fine but the Y box will not accept pasted data. It does accept typed in data
**How to Reproduce**
as above

4. See error -->

**QGIS and OS versions**

QGIS version | 3.16.0-Hannover | QGIS code revision | 43b64b13f3
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | Serval; ThRasE; valuetool; db_manager; MetaSearch; processing

**Additional context**

I cut and paste the coordinate values from another source. Longitude works, Latitude doesnt.

**Comment by roya0045** [comment]
Can you test on a more recent version of 3.16? Also the dialog was changed for 3.18, unsure if this is also present on master.

**Comment by uclaros** [comment]
Can you paste X values in Y field or Y values in X field?
The issue could be with the Y values you cut.

**Comment by gioman** [comment]
This remembers me also of https://github.com/qgis/QGIS/issues/32960

**Comment by Colins2** [comment]
Thanks for all the quick responses.
@uclaros no, I wasn't able to do that. I couldn't paste anything into the Y
coordinate window although, as I mentioned, I could enter data manually and
the coordinates were correctly formed.
@Alex I have just installed 3.16.3 and the function works as expected.
@ Giovanni I looked at that report but it didn't seem to be the same as I
was experiencing. I had no problem with the data itself once entered. My
problem was only that I couldn't paste values.

Everything is working now, looking forward to 3.18.
Colin

**Comment by roya0045** [comment]
Thanks for validating! Could you close the ticket on github ;)

**Comment by Colins2** [comment]
Issue closed.

**Comment by Colins2** [comment]
Done :-)

**Comment by Colins2** [comment]
I thought I had already closed this issue?

**Comment by Colins2** [comment]
Should be closed now

**Comment by Colins2** [comment]
I thought I had already closed this issue. It was resolved the same day as
it was posted.

Regards
Colin
