### ISSUE TITLE
Add Point Cloud Not showing up in data source manager

### ISSUE THREAD

**Issue by GGDRriedel** [qgis/QGIS#41581]
**Describe the bug**
The new feature to add point clouds(LAZ/LAS) does not show in provided qgis install. 
![grafik](https://user-images.githubusercontent.com/48824691/108042319-ed373180-703f-11eb-9d44-287554ffbf8a.png)

**How to Reproduce**
Install like instructed here: 
https://www.lutraconsulting.co.uk/blog/2021/02/15/qgis-point-cloud-windows/

![grafik](https://user-images.githubusercontent.com/48824691/108042475-1e176680-7040-11eb-8b9e-d27f6b3588ca.png)

**QGIS and OS versions**

QGIS version | 3.17.0-Master | QGIS code revision | 68f1d306ff
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.3.0dev
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 8.0.0 | Running against PROJ | Rel. 8.0.0, March 1st, 2021
OS Version | Windows 10 (10.0) | This copy of QGIS writes debugging output.
Active python plugins | AGT; GeoCoding; LAStools; lrs; Mergin; mmqgis; openlayers_plugin; ORStools; processing_fusion; profiletool; qgis-maptiler-plugin; Qgis2threejs; qgis2web; qgis_resource_sharing; QuickOSM; quick_map_services; raster_tracer; SemiAutomaticClassificationPlugin; SpreadsheetLayers; SRTM-Downloader; timemanager; db_manager; processing

**Additional context**

It is showing in the main menus dropdowns: 
![grafik](https://user-images.githubusercontent.com/48824691/108042699-6e8ec400-7040-11eb-9b5b-a049f06e2fe1.png)

**Comment by gioman** [comment]
@saberraz ping

**Comment by saberraz** [comment]
@GGDRriedel did you install qgis-dev usint the **NEW** OSGeo4W installer:
http://download.osgeo.org/osgeo4w/testing/osgeo4w-setup.exe

**Comment by GGDRriedel** [comment]
Yes. Like instructed, installed into seperate folder. 
Installed for ALL USERS

However, I did NOT change the packet download directory. (\AppData\Local\Temp)

**Comment by GGDRriedel** [comment]
Rerunning the new OSGeo4W installer does not show PDA under installed packages, maybe that's it?

**Comment by NEDJIMAbelgacem** [comment]
I think you need to run the executable from <OSGEO4W install folder>/bin/qgis-dev-bin.exe

**Comment by GGDRriedel** [comment]
Did.
When you run  the bin directly it doesn't even show up in the dropdown. When you run the .bat it shows the dropdown option

**Comment by jonnyforestGIS** [comment]
Win10 (Home Edition)
I uninstall my previous version to avoid .dll conflict and did a fresh install using the testing package and appear correctly.

**Comment by GGDRriedel** [comment]
Unfortunately I can't do that, I need other versions for production

**Comment by gioman** [comment]
>  I uninstall my previous version to avoid .dll conflict and did a fresh install using the testing package and appear correctly.

Closing? It seems the issue originates from a mix up of packages installed from different installers.

**Comment by jonnyforestGIS** [comment]
@GGDRriedel I understand. 

@gioman I did base on the talking with @PedroVenancio. Fresh install with this testing package solves the issue.

**Comment by saberraz** [comment]
There was a note:
**Note**: This is a completely revamped and different packaging system than the current OSGeo4W installer. _To avoid any clash with your current installation, it is recommended to use a different path to install the new packages_. The new packaging only supports 64-bit platform.

**Comment by gioman** [comment]
> This is a completely revamped and different packaging system than the current OSGeo4W installer

@saberraz is this new osgeo4w installer supposed to replace the old one starting from the new upcoming releases? A far as I have understand it has several issues @jonnyforestGIS @PedroVenancio

**Comment by GGDRriedel** [comment]
I do not understand why this was closed. 

I installed into a completely new directory. For all intends and purposes this is a completely fresh . 

I did NOT change the package DOWNLOAD directory. 

However, the Note says "install directory". 
I assumed this is for the install of QGIS, not for the download location of the temporary install files

**Comment by saberraz** [comment]
hi @gioman this is supposed to be for testing purposes at this stage. As usual, if things do not get tested, we won't be aware of the issues.

@GGDRriedel I suggest to use different Download and Install for the new OSGeo installer to keep it completely segregated from your production work. I will change the notes to include Download folder too.

**Comment by GGDRriedel** [comment]
I did a completely new install with sepearate package download directory as well as install directory, the problem persits

**Comment by gioman** [comment]
> hi @gioman this is supposed to be for testing purposes at this stage. As usual, if things do not get tested, we won't be aware of the issues.

@saberraz sure. I was just asking because we are testing but releases are very soon. Also is not very clear to me where to report issues about this new osgeo4w, here?

**Comment by GGDRriedel** [comment]
Shouldn't correct install versions and so on be visible in the version report I included in the first message?

**Comment by GGDRriedel** [comment]
Threw out every other QGIS 3.17 version I had despite being in completely different install as well as package download folders. 

Noticed that PDAL is not in the list of installed dependencies when isntalling the dev build. 

Here is the list of dependencies it gives me: 
curl	(7.67.0-1)
	The CURL HTTP/FTP library and commandline utility.
	Required by: gdal-dev, proj-dev, netcdf

curl-ca-bundle	(20191119-1)
	CURL CA certificates
	Required by: curl

exiv2	(0.26-1)
	Image metadata library
	Required by: qgis-dev

expat	(2.1.0-1)
	The Expat XML Parser library
	Required by: exiv2, gdal-dev, ogdi

fcgi	(2.4.1-2)
	FastCGI Library
	Required by: qgis-dev

freexl	(1.0.2-1)
	The FreeXL library for accessing Excel (.xls) spreadsheet.
	Required by: spatialite, gdal-dev

gdal-dev	(3.3.0-98)
	The GDAL/OGR library and commandline tools (nightly master)
	Required by: python3-gdal-dev

geos	(3.8.1-1)
	The GEOS geometry library
	Required by: qgis-dev, spatialite, liblwgeom, gdal-dev

gsl-libs	(1.15-1)
	GNU Scientific Library (GSL)
	Required by: qgis-dev

hdf4	(4.2.14-1)
	The HDF4 library for reading and writing HDF4 format
	Required by: gdal-dev

hdf5	(1.10.5-5)
	The HDF5 library for reading and writing HDF5 format
	Required by: qgis-dev, netcdf

iconv	(1.14-1)
	Codepage translation Library
	Required by: qgis-dev, spatialite, freexl

iconv-vc14	(1.15-1)
	Codepage translation Library
	Required by: gdal-dev

icu-libs	(56.1-3)
	ICU (library)
	Required by: qtwebkit-qt5-libs

libjpeg	(6b-4)
	A library for manipulating JPEG image format files
	Required by: gdal-dev, libtiff

libjpeg12	(6b-4)
	A library for manipulating 12bit JPEG image format files
	Required by: libtiff

liblwgeom	(3.0.0-2)
	liblwgeom
	Required by: spatialite

libmysql	(6.1.9-1)
	MySQL Client Library.
	Required by: gdal-dev

libpng	(1.6.3-1)
	the official PNG reference library
	Required by: gdal-dev

libpng-vc14	(1.6.29-1)
	the official PNG reference library
	Required by: openjpeg

libpq	(11.5-1)
	The libpq library for accessing PostgreSQL + psql commandline client
	Required by: qgis-dev, gdal-dev

libspatialindex	(1.9.0-1)
	The libspatialindex library
	Required by: qgis-dev

libtiff	(4.0.8-1)
	A library for manipulating TIFF format image files (runtime)
	Required by: proj-dev, openjpeg

libxml2	(2.9.1-1)
	An XML read/write library
	Required by: spatialite

libzip-libs	(1.2.0-2)
	libzip (runtime library)
	Required by: qgis-dev

msvc2015	(1.0.0-1)
	msvc2015
	Required by: spatialite, icu-libs

msvcrt	(1.0.3-1)
	Microsoft Visual C/C++ Runtimes
	Required by: qgis-dev, oci, opencl, shell, setup, openjpeg

msvcrt2008	(1.0.0-1)
	Microsoft Visual C/C++ 2008 Runtimes
	Required by: msvcrt

msvcrt2010	(1.0.0-2)
	Microsoft Visual C/C++ 2010 Runtimes
	Required by: msvcrt

msvcrt2015	(2.0-2)
	Microsoft Visual C/C++ 2015/2017/2019 Runtimes
	Required by: libpq, geos, libspatialindex, qt5-libs, python3-core, libzip-libs, exiv2, protobuf, hdf5, openssl, sqlite3, proj, liblwgeom, msvc2015, szip, proj-dev, curl, libmysql, netcdf, xerces-c, hdf4, ogdi, iconv-vc14, zstd, libtiff, xz

netcdf	(4.7.3-2)
	The NetCDF library and commands for reading and writing NetCDF format
	Required by: gdal-dev

oci	(12.1.0.1.0-1)
	Oracle Instant Client
	Required by: qgis-dev

ogdi	(4.1.0-1)
	OGDI data access library (mainly for VPF reading)
	Required by: gdal-dev

opencl	(2.0.10-5)
	KhronosGroup OpenCL runtime
	Required by: qgis-dev

openjpeg	(2.3.0-1)
	OpenJPEG
	Required by: gdal-dev

openssl	(1.1.1d-2)
	OpenSSL Cryptography (Runtime)
	Required by: libpq, qt5-libs, python3-core, curl

openssl10	(1.0.2j-1)
	OpenSSL 1.0 Cryptography (Old Runtime)
	Required by: libzip-libs, openssl

proj	(6.3.2-1)
	The PROJ library and commands for coordinate system transformations.
	Required by: spatialite, liblwgeom

proj-datumgrid	(1.8-1)
	Assorted PROJ datum grid shift files
	Required by: proj, proj-dev

proj-dev	(8.0.0-49)
	The PROJ library and commands for coordinate system transformations (nightly master).
	Required by: gdal-dev

proj-hpgn	(1.0-1)
	PROJ.4 HPGN (HARN) grid shift files
	Required by: proj, proj-dev

protobuf	(3.11.4-2)
	Protocol Buffers - Google's data interchange format
	Required by: qgis-dev

pyqt5	(5.11.3-2)
	Python bindings for Qt5.
	Required by: qgis-dev, python3-qscintilla

python3-certifi	(2020.4.5.2-1)
	Python package for providing Mozilla's CA Bundle.
	Required by: python3-requests

python3-chardet	(3.0.4-2)
	Universal encoding detector for Python 2 and 3
	Required by: python3-requests

python3-core	(3.7.0-4)
	Python3 core interpreter and runtime
	Required by: qgis-dev, sip-qt5, pyqt5, python3-qscintilla, python3-jinja2, python3-markupsafe, python3-pygments, python3-python-dateutil, python3-pytz, python3-nose2, python3-mock, python3-httplib2, python3-future, python3-pyyaml, python3-requests, python3-plotly, python3-pyproj, python3-owslib, python3-gdal-dev, python3-psycopg2-binary, python3-six, python3-coverage, python3-pbr, python3-certifi, python3-chardet, python3-idna, python3-urllib3, python3-retrying, python3-numpy

python3-coverage	(4.5.1-1)
	Code coverage measurement for Python
	Required by: python3-nose2

python3-future	(0.16.0-2)
	Clean single-source support for Python 3 and 2
	Required by: qgis-dev

python3-gdal-dev	(3.3.0-98)
	The GDAL/OGR Python3 Bindings and Scripts (nightly master)
	Required by: qgis-dev

python3-httplib2	(0.11.3-1)
	A comprehensive HTTP client library.
	Required by: qgis-dev

python3-idna	(2.9-1)
	Internationalized Domain Names in Applications (IDNA)
	Required by: python3-requests

python3-jinja2	(2.11.1-1)
	A very fast and expressive template engine.
	Required by: qgis-dev

python3-markupsafe	(1.1.1-1)
	Safely add untrusted strings to HTML/XML markup.
	Required by: qgis-dev, python3-jinja2

python3-mock	(2.0.0-2)
	Rolling backport of unittest.mock for all Pythons
	Required by: qgis-dev

python3-nose2	(0.8.0-1)
	nose2 is the next generation of nicer testing for Python
	Required by: qgis-dev

python3-numpy	(1.19.1-1)
	NumPy is the fundamental package for array computing with Python.
	Required by: python3-gdal-dev

python3-owslib	(0.20.0-1)
	OGC Web Service utility library
	Required by: qgis-dev

python3-pbr	(4.3.0-1)
	Python Build Reasonableness
	Required by: python3-mock

python3-plotly	(4.8.2-1)
	An open-source, interactive data visualization library for Python
	Required by: qgis-dev

python3-psycopg2	(2.8.4-1)
	psycopg2 - Python-PostgreSQL Database Adapter (transitional)
	Required by: qgis-dev

python3-psycopg2-binary	(2.8.4-1)
	psycopg2 - Python-PostgreSQL Database Adapter
	Required by: python3-psycopg2

python3-pygments	(2.5.2-1)
	Pygments is a syntax highlighting package written in Python.
	Required by: qgis-dev

python3-pyproj	(2.6.1.post1-1)
	Python interface to PROJ (cartographic projections and coordinate transformations library)
	Required by: qgis-dev, python3-owslib

python3-python-dateutil	(2.8.1-1)
	Extensions to the standard Python datetime module
	Required by: qgis-dev, python3-owslib

python3-pytz	(2020.1-1)
	World timezone definitions, modern and historical
	Required by: qgis-dev, python3-owslib

python3-pyyaml	(5.3.1-1)
	YAML parser and emitter for Python
	Required by: qgis-dev, python3-owslib

python3-qscintilla	(2.10.8-1)
	Python3 bindings for Qt5 QScintilla
	Required by: qgis-dev

python3-requests	(2.23.0-1)
	Python HTTP for Humans.
	Required by: qgis-dev, python3-owslib

python3-retrying	(1.3.3-1)
	Retrying
	Required by: python3-plotly

python3-six	(1.15.0-1)
	Python 2 and 3 compatibility utilities
	Required by: python3-python-dateutil, python3-nose2, python3-mock, python3-plotly, python3-retrying

python3-urllib3	(1.25.9-1)
	HTTP library with thread-safe connection pooling, file post, and more.
	Required by: python3-requests

qca-qt5-libs	(2.1.3-1)
	Qt5 Cryptographic Architecture runtime libraries
	Required by: qgis-dev

qscintilla-qt5	(2.10.8-1)
	Qt5 source code editing component.
	Required by: python3-qscintilla

qt5-devel	(5.11.2-1)
	Qt5 headers and libraries (Development)
	Required by: qgis-dev

qt5-libs	(5.11.2-1)
	Qt5 runtime libraries
	Required by: qgis-dev, qt5-qml, qt5-devel, qt5-tools, qca-qt5-libs, qwt-libs-qt5, pyqt5, qtkeychain-qt5-libs, qtwebkit-qt5-libs, qtwebengine-qt5-libs, qscintilla-qt5

qt5-qml	(5.11.2-1)
	Qt5 QML
	Required by: qgis-dev

qt5-tools	(5.11.2-1)
	Qt5 designer & linguist (Development)
	Required by: qgis-dev

qtkeychain-qt5-libs	(0.9-1)
	Platform-independent Qt API for storing passwords securely.
	Required by: qgis-dev

qtwebengine-qt5-libs	(5.10.1-1)
	WebEngine for Qt5
	Required by: pyqt5

qtwebkit-qt5-libs	(5.212-1)
	WebKit for Qt5
	Required by: pyqt5

qwt-libs-qt5	(6.1.3-5)
	Qt5 widgets library for technical applications (runtime)
	Required by: qgis-dev

setup	(1.0.7-16)
	OSGeo4W Installer/Updater
	Required by: shell

shell	(1.0.2-4)
	OSGeo4W Command Shell
	Required by: gsl-libs, zlib, iconv, fcgi, qt5-tools, qwt-libs-qt5, python3-qscintilla, libxml2, qscintilla-qt5, expat, gdal-dev, setup, libpng, libjpeg, libpng-vc14, libjpeg12

sip-qt5	(4.19.14-1)
	Python3/C++ bindings generator (Development)
	Required by: qgis-dev, pyqt5

spatialite	(4.3.0a-6)
	The SpatiaLite library for adding spatial capabilities to SQLite3 DBMS.
	Required by: qgis-dev, gdal-dev

sqlite3	(3.29.0-1)
	The SQLite3 library for accessing SQLite3 database files.
	Required by: spatialite, qt5-libs, python3-core, gdal-dev, proj-dev

szip	(2.1.1-1)
	SZIP compression library
	Required by: hdf5, hdf4

xerces-c	(3.2.0-1)
	The Xerces-C 3 library for parsing XML files (runtime)
	Required by: gdal-dev

xz	(5.2.3-1)
	XZ-format compression library
	Required by: libtiff

zlib	(1.2.8-1)
	The zlib compression and decompression library (runtime)
	Required by: qgis-dev, qt5-libs, exiv2, protobuf, netcdf, ogdi, openjpeg, libtiff

zstd	(1.4.4-1)
	Zstandard Long Range Match Finder (runtime)
	Required by: gdal-dev

**Comment by jonnyforestGIS** [comment]
@saberraz can we put in this issue some errors about this testing package?

For now, I find this:

Running qgis-dev.bat from osgeoshell gives the following error:

```cmd
'gdal-dev-py3-env.bat' is not recognized as an internal or external command, operable program or batch file.

```
Is calling a bat file that doesn't exist.

**Comment by NEDJIMAbelgacem** [comment]
> qt5-devel (5.11.2-1)
> Qt5 headers and libraries (Development)
> Required by: qgis-dev
> 
> qt5-libs (5.11.2-1)
> Qt5 runtime libraries
> Required by: qgis-dev, qt5-qml, qt5-devel, qt5-tools, qca-qt5-libs, qwt-libs-qt5, pyqt5, qtkeychain-qt5-libs, qtwebkit-qt5-libs, qtwebengine-qt5-libs, qscintilla-qt5

I'm pretty sure the testing version you are supposed to install is linked against Qt5.15

**Comment by GGDRriedel** [comment]
Did a complete fresh install again and it installs qt5-devel-5.11.2 
and no PDAL

**Comment by jef-n** [comment]
testing doesn't have 5.11.2.  You must be using the wrong site (http://download.osgeo.org/osgeo4w instead of http://download.osgeo.org/osgeo4w/testing)

**Comment by GGDRriedel** [comment]
I am 100% sure that I am absolutely not. 

Which downloadsite is the one you are selecting? I am taking oslandia(first in list)

**Comment by GGDRriedel** [comment]
Selecting a different downloadsite, "older" ini  and just going "keep" gives me new dependencies(qt5.15). 

Trying fresh install with that

**Comment by NEDJIMAbelgacem** [comment]
> Which downloadsite is the one you are selecting? I am taking oslandia(first in list)

There is only one download site in the testing installer

**Comment by GGDRriedel** [comment]
Then I must be living in a different reality
![grafik](https://user-images.githubusercontent.com/48824691/108070020-53ce4680-7064-11eb-9a2a-53e6cf73b0ab.png)

**Comment by jef-n** [comment]
The installer just has different default site (and some fixes that relate to the fact that it was built with a newer compiler).  You can still use it to install from the old site or use the old one to install from the new site.  The old one required admin privileges, the new one doesn't anymore (and has a popup when regedit is called, because of that).

**Comment by jef-n** [comment]
> 
> 
> Then I must be living in a different reality
> ![grafik](https://user-images.githubusercontent.com/48824691/108070020-53ce4680-7064-11eb-9a2a-53e6cf73b0ab.png)

Probably leftovers in %OSGEO4W_ROOT%/etc/setup/setup.rc  when mixing sites.

**Comment by PedroVenancio** [comment]
@jef-n Sorry to be posting this here, but I'm seeing some issues with the new installer:

- OSGeo4W.bat is calling the default windows console:
```
@echo off
set OSGEO4W_ROOT=C:\OSGeo4W64
PATH=%OSGEO4W_ROOT%\bin;%PATH%
for %%f in (%OSGEO4W_ROOT%\etc\ini\*.bat) do call %%f
@echo on

@cmd.exe
```

- SAGA is not available in the installer;

- I'm also seeing conflicts between numpy version available on OSGeo4w and the version required by opencv-python installed from pip for Python 3.9. open-cv is a dependency of some QGIS plugins. Maybe include opencv-python and opencv-contrib-python in OSGeo4W would be good.

**Comment by GGDRriedel** [comment]
I am using the new installer. However it seems that I might have selected the wrong download site. 
This wasn't in the instructions.

> 
> 
> > Then I must be living in a different reality
> > ![grafik](https://user-images.githubusercontent.com/48824691/108070020-53ce4680-7064-11eb-9a2a-53e6cf73b0ab.png)
> 
> Probably leftovers in %OSGEO4W_ROOT%/etc/setup/setup.rc when mixing sites.

But the root should be set once I execute the new installer? After all I give it a completely new, fresh empty directory

**Comment by jef-n** [comment]
> @jef-n Sorry to be posting this here, but I'm seeing some issues with the new installer:
 
>     * OSGeo4W.bat is calling the default windows console:

`setup` was overwriting the content of `base` .  should be fixed.

>     * The installer is not creating the shortcuts in start menu;

You probably selected "for all".  That requires admin privileges.

>     * SAGA is not available in the installer;

correct.  the left bit.

> * I'm also seeing conflicts between numpy version available on OSGeo4w and the version required by opencv-python installed from pip for Python 3.9. open-cv is a dependency of some QGIS plugins. Maybe include opencv-python and opencv-contrib-python in OSGeo4W would be good.

um, that's new and was never included.

**Comment by PedroVenancio** [comment]
> > * I'm also seeing conflicts between numpy version available on OSGeo4w and the version required by opencv-python installed from pip for Python 3.9. open-cv is a dependency of some QGIS plugins. Maybe include opencv-python and opencv-contrib-python in OSGeo4W would be good.
> 
> um, that's new and was never included.

Yes, this one is more like a feature request. I'm talking about for instance https://github.com/All4Gis/QGISFMV
It depends on opencv-python and opencv-contrib-python, but installing them from pip, updates numpy. However, I believe this one is not urgent.

- I'm seeing another issue with PROJ. QGIS does not recognize CRS of layers (raster, point cloud) and they are loaded with no CRS. Looking at gdalinfo I get ERROR 1: PROJ: proj_create_from_database: Cannot find proj.db:

```
gdalinfo D:\DRONE\WebODM20210213_50fps\All_com_GCP\odm_orthophoto\odm_orthophoto_2021_02_13_georref_3763_2.tif
GDAL command output:
ERROR 1: PROJ: proj_create_from_database: Cannot find proj.db
ERROR 1: PROJ: proj_create_from_database: Cannot find proj.db
Driver: GTiff/GeoTIFF 
Files: D:\DRONE\WebODM20210213_50fps\All_with_GCP\odm_orthophoto\odm_orthophoto_2021_02_13_georref_3763_2.tif 
Size is 2858, 3053 
Coordinate System is: 
ENGCRS["ETRS89 / Portugal TM06", 
EDATUM[""], 
CS[Cartesian,2], 
AXIS["(E)",east, 
ORDER[1], 
LENGTHUNIT["metre",1]], 
AXIS["(N)",north, 
ORDER[2], 
LENGTHUNIT["metre",1]], 
ID["EPSG",3763]] 
Data axis to CRS axis mapping: 1,2 
Origin = (88187.056403674403555,105530.921289842110127) 
Pixel Size = (0.049998637510099,-0.049998637510099) 
Metadata: 
AREA_OR_POINT=Area 
Image Structure Metadata: 
INTERLEAVE=PIXEL 
Corner Coordinates: 
Upper Left ( 88187.056, 105530.921) 
Lower Left ( 88187.056, 105378.275) 
Upper Right ( 88329.953, 105530.921) 
Lower Right ( 88329.953, 105378.275) 
Center ( 88258.504, 105454.598) 
Band 1 Block=2858x1 Type=Byte, ColorInterp=Red 
Mask Flags: PER_DATASET ALPHA 
Band 2 Block=2858x1 Type=Byte, ColorInterp=Green 
Mask Flags: PER_DATASET ALPHA 
Band 3 Block=2858x1 Type=Byte, ColorInterp=Blue 
Mask Flags: PER_DATASET ALPHA 
Band 4 Block=2858x1 Type=Byte, ColorInterp=Alpha
Process completed successfully
Execution completed in 0.18 seconds
```

**Comment by GGDRriedel** [comment]
Would be cool if you made your own isue and didn't capture this one

**Comment by GGDRriedel** [comment]
So, how do I make the new installer not take the wrong download site? As far as I see it the os4geow root should be set when the setup gets a new install folder?

**Comment by jef-n** [comment]
did you try removing setup.rc?

**Comment by PedroVenancio** [comment]
>     * ERROR 1: PROJ: proj_create_from_database: Cannot find proj.db

Could this one be related to admin privileges @jef-n ?

**Comment by GGDRriedel** [comment]
> 
> 
> did you try removing setup.rc?

I just did and it works now. 


This is probably a problem that many more people trying this out and maybe even in the release will have

**Comment by PedroVenancio** [comment]
>     * I'm also seeing conflicts between numpy version available on OSGeo4w and the version required by opencv-python installed from pip for Python 3.9. open-cv is a dependency of some QGIS plugins. Maybe include opencv-python and opencv-contrib-python in OSGeo4W would be good.

To solve this one is sufficient upgrade also scipy from pip
`python3 -m pip install --upgrade scipy`

So nothing to worry right now.

**Comment by PedroVenancio** [comment]
>     * I'm seeing another issue with PROJ. QGIS does not recognize CRS of layers (raster, point cloud) and they are loaded with no CRS. Looking at gdalinfo I get ERROR 1: PROJ: proj_create_from_database: Cannot find proj.db

This seems to be the main issue right now @jef-n

**Comment by jef-n** [comment]
> > ```
> > * ERROR 1: PROJ: proj_create_from_database: Cannot find proj.db
> > ```
> 
> Could this one be related to admin privileges @jef-n ?

I doubt it.  Did you run the installer as admin?  Otherwise all the files should be owned by the current user anyway.    I cannot reproduce this BTW.

**Comment by GGDRriedel** [comment]
Kindly asking again to make a new issue to discuss unrelated issues. 

I'd much rather have a response of someone about maybe modifying install instructions and caring for install of the new release 3.18 along 3.16 which will inevitably run into the same problem as I did here and close the issue.

**Comment by GGDRriedel** [comment]
Setting this to close. The culprit was the installer using the wrong directory as indicated by 

> 
> 
> > Then I must be living in a different reality
> > ![grafik](https://user-images.githubusercontent.com/48824691/108070020-53ce4680-7064-11eb-9a2a-53e6cf73b0ab.png)
> 
> Probably leftovers in %OSGEO4W_ROOT%/etc/setup/setup.rc when mixing sites.
