### ISSUE TITLE
Can we hide spurious error messages

### ISSUE THREAD

**Issue by timlinux** [qgis/QGIS#41583]
I am working with QGIS master so I don't know if other users experience this, but I get a lot of QMessageBar error messages that interfere with my sense of well being. Here is one example:

![image](https://user-images.githubusercontent.com/178003/108056227-ebbe3700-7048-11eb-99ff-837741fddbf5.png)

Sometimes these messages are in a big block and take up a lot of screen real estate. Sometimes there isn't even a message:

![image](https://user-images.githubusercontent.com/178003/108058328-caab1580-704b-11eb-8b21-bee167a70a6a.png)

They are also generally messages that I as a user cannot do anything about. Are they just artefacts of a debug build or do all users see them? Can they not rather be just put in the debug messages?

**Comment by gioman** [comment]
Agree!

**Comment by rduivenvoorde** [comment]
Yes, I get those too...

**Comment by PedroVenancio** [comment]
I also get several:

`Qt: Retrying to obtain clipboard`

`Qt: QFont::setPointSize: Point size`

**Comment by nyalldawson** [comment]
Short answer - no. These are showing important things for debugging, and can reveal possible sources of crashes or data corruption in the release version. If you're running a nightly debug version then the whole point is to give feedback for things like this prior to the final releases!

**Comment by timlinux** [comment]
@nyalldawson thanks for your reply - can you clarify if these are hidden in release builds?

**Comment by timlinux** [comment]
Also wouldnt we get the same usefulness by dropping in the QGIS Log panel rather than in-your-face on the canvas. If you prefer them in the canvas, would you like us to try to make a reproduceable bug report for each error that pops up so that you (or fine folks like you) can whittle them away?

**Comment by nyalldawson** [comment]
@timlinux 
> can you clarify if these are hidden in release builds?

Yes, definitely

> Also wouldnt we get the same usefulness by dropping in the QGIS Log panel rather than in-your-face on the canvas. If you prefer them in the canvas, would you like us to try to make a reproduceable bug report for each error that pops up so that you (or fine folks like you) can whittle them away?

That's what we used to do. And then we found that the log was full of warnings pointing out valid bugs in code people had written, but it just wasn't visible enough for them to realise. So we decided to make it so obnoxious and "in your face" that it's impossible for developers to ignore, and so the underlying issues get fixed instead of ignored...

**Comment by timlinux** [comment]
Ok cool, thanks for the back story, closing for now.
