### ISSUE TITLE
Data-defined setting in html frame does not work when atlas is enabled

### ISSUE THREAD

**Issue by jdlom** [qgis/QGIS#41590]
**Describe the bug**
In a layout, data-defined url in html frame does not work by a field or by expression when the atlas is enabled. The html frame stays empty.

**How to Reproduce**

1. Create a layout
2. Enable the atlas
3. Add a html item
4. Click on data-defined url and put a path as string like `'file:///my/html/template.html'`
5. See the empty frame

**QGIS and OS versions**
Tested on 3.10.14 on windows
Tested on 3.16.3 Ubuntu Focal
Tested on master

**Additional context**
I think this feature never works on version 3 but I'm not sure about that. The last time I saw this feature works was on qgis 2.18.

**Sample projects**
A sample zip that contains 2 projects which works with **atlas**.
One works well on qgis 2.18 and the other (the .qgz for QGIS 3) does not work.

On QGIS 3 :

![html_frame_qgis3](https://user-images.githubusercontent.com/8641271/108077298-a7dd2900-706c-11eb-8b3f-91cdfe779594.jpg)

On QGIS 2.18 :

![html_frame_qgis218](https://user-images.githubusercontent.com/8641271/108077306-a90e5600-706c-11eb-9b67-ffe7e0a13991.jpg)

Dataset to test:
[test_atlas_html.zip](https://github.com/qgis/QGIS/files/5989336/test_atlas_html.zip)

**Comment by PeterPetrik** [comment]
It doesn't work with `'file:///@project_folder/test.html'` what is used in your project, but works with`'file:///'+@project_folder+'/test.html'`

**Comment by PeterPetrik** [comment]
[test_html_41590.zip](https://github.com/qgis/QGIS/files/5996674/test_html_41590.zip)

If I create project from scratch, it works with expressions if I create it with 
1. Create a layout
2. Add a html item
3. Click on data-defined url and put a path as string like `'file:///'+@project_folder+'/test.html'`

**Comment by jdlom** [comment]
@PeterPetrik Indeed it seems to work but not when the atlas is enabled. I change the issue name and the description.

**Comment by PeterPetrik** [comment]
thanks, I can reproduce it now

**Comment by jdlom** [comment]
Like i said i think it doesn't work since version 3.0 if that can help you. Sorry for reporting this issue so late, I should have explored this problem earlier.

**Comment by PeterPetrik** [comment]
OK, after several hours in debugger .... what I can tell that this is not one-liner fix I was looking for ...

![atlas_html](https://user-images.githubusercontent.com/804608/108396731-76ed2780-7217-11eb-9504-67dd96dc0909.gif)

and some sample qgs extract

```
      <LayoutItem background="true" frame="true" visibility="1" blendMode="5" id="missing text" sectionX="0" hideBackgroundIfEmpty="0" uuid="{8cda9008-54f6-4b58-a5b9-66d2a18f0c13}" opacity="1" sectionWidth="75.3448" size="75.3448,58.0526,mm" groupUuid="" templateUuid="{8cda9008-54f6-4b58-a5b9-66d2a18f0c13}" multiFrame="{bc405ffe-b27a-4434-aa63-15f5e8202617}" itemRotation="0" positionLock="false" zValue="2" outlineWidthM="1.3,mm" excludeFromExports="0" multiFrameTemplateUuid="{bc405ffe-b27a-4434-aa63-15f5e8202617}" sectionY="0" positionOnPage="72.5052,50.063,mm" frameJoinStyle="miter" type="65647" referencePoint="0" hidePageIfEmpty="0" sectionHeight="58.0526" position="72.5052,50.063,mm">
        <FrameColor green="0" alpha="255" red="227" blue="0"/>
        <BackgroundColor green="245" alpha="255" red="255" blue="252"/>
        <LayoutObject>
          <dataDefinedProperties>
            <Option type="Map">
              <Option type="QString" value="" name="name"/>
              <Option type="Map" name="properties">
                <Option type="Map" name="dataDefinedSourceUrl">
                  <Option type="bool" value="true" name="active"/>
                  <Option type="QString" value="'/Users/peter/Downloads/test_html_41590/test.html'" name="expression"/>
                  <Option type="int" value="3" name="type"/>
                </Option>
              </Option>
              <Option type="QString" value="collection" name="type"/>
            </Option>
          </dataDefinedProperties>
          <customproperties/>
        </LayoutObject>
      </LayoutItem>
      <LayoutMultiFrame type="65648" contentMode="1" html="&lt;html>&#xa;B&#xa;&lt;/html>" resizeMode="0" stylesheet="" maxBreakDistance="10" templateUuid="{bc405ffe-b27a-4434-aa63-15f5e8202617}" uuid="{bc405ffe-b27a-4434-aa63-15f5e8202617}" url="" stylesheetEnabled="false" evaluateExpressions="false" useSmartBreaks="false">
        <childFrame templateUuid="{8cda9008-54f6-4b58-a5b9-66d2a18f0c13}" uuid="{8cda9008-54f6-4b58-a5b9-66d2a18f0c13}"/>
        <childFrame templateUuid="{0287c61c-e05b-4e12-b272-f0c4f5017c7c}" uuid="{0287c61c-e05b-4e12-b272-f0c4f5017c7c}"/>
        <childFrame templateUuid="{260c833a-9d6f-4d67-ad47-25e5cf8ddb14}" uuid="{260c833a-9d6f-4d67-ad47-25e5cf8ddb14}"/>
        <childFrame templateUuid="{941543fb-c465-4b53-9474-dc2ff210b67b}" uuid="{941543fb-c465-4b53-9474-dc2ff210b67b}"/>
        <LayoutObject>
          <dataDefinedProperties>
            <Option type="Map">
              <Option type="QString" value="" name="name"/>
              <Option name="properties"/>
              <Option type="QString" value="collection" name="type"/>
            </Option>
          </dataDefinedProperties>
          <customproperties>
            <property key="variableNames"/>
            <property key="variableValues"/>
          </customproperties>
        </LayoutObject>
      </LayoutMultiFrame>
```
my understanding:

1. you click "Add HTML" 
 -  This creates new QgsLayoutItemHtml (aka QgsLayoutMultiFrame in CORE) with one QgsLayoutFrame
 - Also one GUI QgsLayoutFrameQgsLayoutHtmlWidget with one QgsLayoutConfigObject (referencing QgsLayoutItemHtml)
2.  you set the DD property
 - this propagates QgsLayoutConfigObject (referencing QgsLayoutItemHtml) to QgsLayoutItemHtml
 - text in the visual item (frame) is not set 
3. you click on the visual item (frame) on canvas
- This calls `QgsLayoutItemBaseWidget::setItem( QgsLayoutFrame  )`
- The function creates new QgsLayoutConfigObject referencing QgsLayoutFrame
- This bubbles down to QgsLayoutHtmlWidget::setNewItem() -> QgsLayoutHtmlWidget::populateDataDefinedButtons() ->
QgsLayoutItemBaseWidget::updateDataDefinedButton() which already references QgsLayoutFrame and not QgsLayoutItemHtml
4. On QGIS project save, the DD props are saved to QgsLayoutFrame and not the QgsLayoutItemHtml. So when you load the QGIS project, DD props are set on wrong place so it is not loaded

various bugs then relates to various user actions, what and when was clicked or saved or so...

The major problem I see is that the framework to replace the item properties widget  assumes that QgsLayoutConfigObject is unique to one item. But in case of Frame, there are few buttons with DD properties related to frame (width, etc.), but ONE button (url DD prop) that is "shared" between all frames via  QgsLayoutItemHtml..

thanks @nyalldawson and @wonder-sk for help. I think I will leave it for now, so if someone is brave enough to try to fix it....

**Comment by jdlom** [comment]
Thx for the feedback. Waiting for a fix, I'll use the label item with a custom function to read the html file.

**Comment by jdlom** [comment]
Already ? Can't wait to test. Thanks @nyalldawson !
