### ISSUE TITLE
Unicode Decode Error charmap in Processing History of QGIS master installed from the new OSGeo4W installer

### ISSUE THREAD

**Issue by PedroVenancio** [qgis/QGIS#41601]
I'm getting this error when I try to access to Processing history:

```
An error has occurred while executing Python code: 

UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 3116: character maps to 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis-dev/./python/plugins\processing\ProcessingPlugin.py", line 352, in openHistory
    dlg = HistoryDialog()
  File "C:/OSGEO4~1/apps/qgis-dev/./python/plugins\processing\gui\HistoryDialog.py", line 77, in __init__
    self.fillTree()
  File "C:/OSGEO4~1/apps/qgis-dev/./python/plugins\processing\gui\HistoryDialog.py", line 107, in fillTree
    entries = ProcessingLog.getLogEntries()
  File "C:/OSGEO4~1/apps/qgis-dev/./python/plugins\processing\core\ProcessingLog.py", line 68, in getLogEntries
    lines = f.readlines()
  File "C:\OSGEO4~1\apps\Python39\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 3116: character maps to 

Python version: 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)] 
QGIS version: 3.17.0-Master Master, fa9135792 
```

This happens on QGIS master installed from the new OSGeo4W installer, on a portuguese windows 10 machine. 

It does not happen on QGIS 3.16 (standalone).

**Comment by PedroVenancio** [comment]
Creating a new profile, I also do not get this issue. So it must be something with one of my logs in default profile. 

However, it does not happen in previous versions. Can be considered a bug?

**Comment by gioman** [comment]
> Can be considered a bug?

@PedroVenancio I guess it depends on what you had in your other profile :)

**Comment by jonnyforestGIS** [comment]
As  @gioman I don't have this error in my current profile or in a new profile. Probably a "bad" plugin :angel: @PedroVenancio this can be close?

**Comment by PedroVenancio** [comment]
@gioman @jonnyforestGIS 

The issue is definitively related to some characters in my history file, and opening it in a plain text with CP1252 encoding, I see several of them like

![IMG_20210218_111441_572](https://user-images.githubusercontent.com/1331581/108349456-e5f85b00-71da-11eb-9407-95f232cf4105.png)

However, this same file doesn't have problems with QGIS 3.16 and python 3.7.

And I wonder why the history file is not opened with UTF8 encoding, to overcome those issues. The following image shows the same piece of text opened with UTF8.

![IMG_20210218_111444_980](https://user-images.githubusercontent.com/1331581/108349663-2c4dba00-71db-11eb-8179-73fea01d2b36.png)

**Comment by gioman** [comment]
> The issue is definitively related to some characters in my history file, and opening it in a plain text with CP1252 encoding, I see several of them like

@PedroVenancio so seems a valid issue, but not sure how I can replicate.

**Comment by PedroVenancio** [comment]
@gioman  just add this line to the end of your processing.log file and save it

`ALGORITHM|~|2021-02-18 19:10:20|~|processing.run("model:Hillshade 2", {'MDT':'D:/SRTM_PT_25m.tif','native:hillshade_1:Área Hillshade':'TEMPORARY_OUTPUT'})`

Then try to access your history again.

**Comment by gioman** [comment]
> Then try to access your history again.

@PedroVenancio confirmed.

**Comment by alexbruy** [comment]
I can't reproduce with 3.17 (a89241c19d) on ukrainian Windows. Also works fine on Linux with UTF-8 locale.

**Comment by PedroVenancio** [comment]
> 
> I can't reproduce with 3.17 ([a89241c](https://github.com/qgis/QGIS/commit/a89241c19d3e353a155dccc204750b9c27736546)) on ukrainian Windows. Also works fine on Linux with UTF-8 locale.

Hi @alexbruy 
Even adding this line, you don't have the error?

`ALGORITHM|~|2021-02-18 19:10:20|~|processing.run("model:Hillshade 2", {'MDT':'D:/SRTM_PT_25m.tif','native:hillshade_1:Área Hillshade':'TEMPORARY_OUTPUT'})`

I'm with this error consistently with all new OSGeo4W versions (LTR, REL and DEV).

How can I check what file is used to decode history file? 
`..\OSGeo4W64\apps\Python39\Lib\encodings\cp1252.py` is used in new versions with Python 3.9 and I get the error. 

The content of `cp1252.py` is the same in Python 3.7  and Python 3.9, but I don't know if in old versions the `cp1252.py` is used.

Changing the `..\OSGeo4W64\apps\Python39\Lib\encodings\cp1252.py` content and using the `..\OSGeo4W64\apps\Python39\Lib\encodings\utf_8.py` content (just copy&paste), the error does not happen and history works fine.

So, something must be changed.

**Comment by alexbruy** [comment]
@PedroVenancio I don't have any errors with your line added. Just tried in a completely clean VM still not reproducible with latest master build (3.19, 61b6cc21e8) from OSGeo4W. Also no errors with other versions.

**Comment by gioman** [comment]
@PedroVenancio I also can't replicate (anymore).

**Comment by PedroVenancio** [comment]
> 
> @PedroVenancio I don't have any errors with your line added. Just tried in a completely clean VM and still not reproducible with the latest master build (3.19, [61b6cc2](https://github.com/qgis/QGIS/commit/61b6cc21e8a1708c8bcb0302546ac6cf81da6c36)) from OSGeo4W. Also no errors with other versions.

Thanks for testing @alexbruy @gioman 

I believe this result from a coincidence between my SO locale (portuguese) and those characters.

Do you know how can I check what file is used to decode history file? In newer QGIS versions (`QGIS 3.19.0-Master code revision 61b6cc21e`, `QGIS 3.16.4-Hannover code revision 654e76b3cb`, `QGIS 3.18.0-Zürich code revision 2d3150d0`) I know that it is using `..\OSGeo4W64\apps\Python39\Lib\encodings\cp1252.py`, because it fails and stack trace shows it. 

But the older versions (for instance `QGIS 3.16.3-Hannover code revision 94ac9f21b8`) works fine, and `cp1252.py` is equal. So I suspect that, for any reason, it does not use `cp1252.py` to decode history file.

**Comment by PedroVenancio** [comment]
processing.log file is encoded in UTF-8, and I think that is because it gives errors when decoding some character in cp1252.

**Comment by agiudiceandrea** [comment]
I think this issue is related to https://github.com/qgis/QGIS/issues/43834 and https://trac.osgeo.org/osgeo4w/ticket/682.

**Comment by agiudiceandrea** [comment]
@PedroVenancio could you try if changing, line 67 in ProcessingLog.py from
https://github.com/qgis/QGIS/blob/2da0ddf36a29c95dafa86051f9f1d5bea7a3ad36/python/plugins/processing/core/ProcessingLog.py#L67
to
```python
        with open(ProcessingLog.logFilename(), encoding='utf-8') as f:
```
fixes the issue?

**Comment by PedroVenancio** [comment]
@agiudiceandrea 

I confirm that this change solves the issue!

> ```python
>         with open(ProcessingLog.logFilename(), encoding='utf-8') as f:
> ```
