### ISSUE TITLE
proj.db is not available in new OSGeo4W installer

### ISSUE THREAD

**Issue by PedroVenancio** [qgis/QGIS#41600]
@jef-n 

I opened this separate ticket because I think I've found the issue of QGIS does not recognize the CRS of layers (raster, point cloud), being loaded with no CRS. 

gdalinfo gives `ERROR 1: PROJ: proj_create_from_database: Cannot find proj.db`

`gdalinfo D:\DRONE\WebODM20210213_50fps\All_with_GCP\odm_orthophoto\odm_orthophoto_2021_02_13_georref_3763_2.tif`
```
GDAL command output:
ERROR 1: PROJ: proj_create_from_database: Cannot find proj.db
ERROR 1: PROJ: proj_create_from_database: Cannot find proj.db
Driver: GTiff/GeoTIFF 
Files: D:\DRONE\WebODM20210213_50fps\All_with_GCP\odm_orthophoto\odm_orthophoto_2021_02_13_georref_3763_2.tif 
Size is 2858, 3053 
Coordinate System is: 
ENGCRS["ETRS89 / Portugal TM06", 
EDATUM[""], 
CS[Cartesian,2], 
AXIS["(E)",east, 
ORDER[1], 
LENGTHUNIT["metre",1]], 
AXIS["(N)",north, 
ORDER[2], 
LENGTHUNIT["metre",1]], 
ID["EPSG",3763]] 
Data axis to CRS axis mapping: 1,2 
Origin = (88187.056403674403555,105530.921289842110127) 
Pixel Size = (0.049998637510099,-0.049998637510099) 
Metadata: 
AREA_OR_POINT=Area 
Image Structure Metadata: 
INTERLEAVE=PIXEL 
Corner Coordinates: 
Upper Left ( 88187.056, 105530.921) 
Lower Left ( 88187.056, 105378.275) 
Upper Right ( 88329.953, 105530.921) 
Lower Right ( 88329.953, 105378.275) 
Center ( 88258.504, 105454.598) 
Band 1 Block=2858x1 Type=Byte, ColorInterp=Red 
Mask Flags: PER_DATASET ALPHA 
Band 2 Block=2858x1 Type=Byte, ColorInterp=Green 
Mask Flags: PER_DATASET ALPHA 
Band 3 Block=2858x1 Type=Byte, ColorInterp=Blue 
Mask Flags: PER_DATASET ALPHA 
Band 4 Block=2858x1 Type=Byte, ColorInterp=Alpha
Process completed successfully
Execution completed in 0.18 seconds
```

In fact I do not have `proj.db` inside `..\OSGeo4W\share\proj`

I've tested on two separate machines.

Just coping `proj.db` from `..\OSGeo4W64\apps\proj-dev\share\proj` to `..\OSGeo4W\share\proj` solves the issue.

So, shouldn't `proj.db` be shipped inside `..\OSGeo4W\share\proj`?

**Comment by jonnyforestGIS** [comment]
I can confirm the behaviour. The first time didn't see the error because QGIS are using a previous PROJ_LIB variable from existent  PostGIS installation.

**Comment by jef-n** [comment]
The testing repo doesn't have proj-dev.  And proj-7.2.1-1 has proj.db in share/proj.

**Comment by PedroVenancio** [comment]
> 
> The testing repo doesn't have proj-dev. And proj-7.2.1-1 has proj.db in share/proj.

@jef-n proj-dev is from OSGeo4W64 (not testing). I've just copied & paste proj.db from proj-dev to testing share/proj and it worked. 

I've installed testing in two different machines and none of them have proj.db in share/proj.

**Comment by jef-n** [comment]
> > The testing repo doesn't have proj-dev. And proj-7.2.1-1 has proj.db in share/proj.
> 
> @jef-n proj-dev is from OSGeo4W64 (not testing). I've just copied & paste proj.db from proj-dev to testing share/proj and it worked.
> 
> I've installed testing in two different machines and none of them have proj.db in share/proj.

So you are saying you have proj-7.2.1-1 installed and there is/was no share/proj/proj.db?  That's odd.

**Comment by jef-n** [comment]
> So you are saying you have proj-7.2.1-1 installed and there is/was no share/proj/proj.db? That's odd.

No, you were saying that proj.db belongs in proj*-runtime as nothing depended on the tools.

**Comment by PedroVenancio** [comment]
> So you are saying you have proj-7.2.1-1 installed and there is/was no share/proj/proj.db? That's odd.

That's correct @jef-n this is what happens.

**Comment by jef-n** [comment]
> That's correct @jef-n this is what happens.

Odd. Then check setup.log{,.full} for errors - apparently proj-7.2.1-1.tar.bz2 was not extracted successfully.

**Comment by PedroVenancio** [comment]
It seems fixed with proj-7.2.1-2 @jef-n

**Comment by gioman** [comment]
@jef-n @PedroVenancio for what is worth: I just tried the new osgeo4w installer on a clean Win10 machine, in English. No errors on install proj.db is there. Trying launch gdal-dev the splash screen comes up and then... nothing, it stayed there forever. Tried again and it worked.

There seems to be a problem with the numpy package, and this prevents to run Processing.

**Comment by PedroVenancio** [comment]
Yes numpy 1.19.5 seems to be listed but not available (size is ?). Same with scipy 1.6.0-1.
