### ISSUE TITLE
Proj.db not found for SAGA tools on QGIS 3.17 Mac nightly

### ISSUE THREAD

**Issue by PeterPetrik** [qgis/QGIS#41606]
see how to replicate in https://github.com/qgis/QGIS/issues/39801

reported by @spatialthoughts by twitter :) 
https://twitter.com/spatialthoughts/status/1361956135113134080

**Comment by PedroVenancio** [comment]
@PeterPetrik could be related to https://github.com/qgis/QGIS/issues/41600 ?

**Comment by PeterPetrik** [comment]
fixed by https://github.com/qgis/QGIS-Mac-Packager/commit/7a713903cf001a9e156eac60e25e84789e1e534a

@spatialthoughts can you try with tomorrow nightly build and let me know if it does not work ? thanks

**Comment by PeterPetrik** [comment]
@spatialthoughts you can try with qgis_nightly_master_20210217_070925.dmg build now
