### ISSUE TITLE
Unable to change shortcut keys for actions in the layout view (print composer).

### ISSUE THREAD

**Issue by MrChebur** [qgis/QGIS#41610]
**Describe the bug**
Actions available in "Print Composer" are missing in the "Keyboard Shortcuts" list. Even the actions to which hotkeys are assigned are missing. Some actions whose names coincide with the names of actions in the main menu can be found in the "Keyboard Shortcuts" list (for example "Refresh - F5").

**How to Reproduce**

1. Go to 'Settings' =>  'Keyboard Shortcuts'.
2. Search any actions available in the 'Print Composer' menu (no results found).

![5uOG9nrEj0](https://user-images.githubusercontent.com/20655102/108188127-08ce3500-7131-11eb-91db-62105c7e5e50.gif)

**QGIS and OS versions**

QGIS version
3.14.16-Pi
QGIS code revision
df27394552
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
AppendFeaturesToLayer; 
DigitizingTools; 
ee_plugin; 
FreehandRasterGeoreferencer; 
Go2NextFeature3; 
latlontools; 
mapswipetool_plugin; 
minimum_spanning_tree; 
qgis_gee_data_catalog; 
qgsAzimuth; 
sentinel2_download; 
db_manager; 
MetaSearch; 
processing

**Comment by PeterPetrik** [comment]
I think this is more of a feature request than the bug-fix. The shortcuts overrides are registered only for the main window plus very few exceptions https://github.com/qgis/QGIS/blob/a89241c19d3e353a155dccc204750b9c27736546/src/app/qgisapp.cpp#L1644

**Comment by MrChebur** [comment]
@gioman Ok, this is a feature request. Not sure about the feedback. I have nothing to say.
