### ISSUE TITLE
Usability improvement: Quick click gesture to graphically deselect all 

### ISSUE THREAD

**Issue by tschmetzer** [qgis/QGIS#41629]
Usability improvement: Quick click gesture to graphically deselect all (e.g. 3 times click or right click or an additional ctrl/shift/alt key)

**Comment by andreasneumann** [comment]
Isn't that already possible with the keyboard shortcuts?

See 
![image](https://user-images.githubusercontent.com/884476/108336139-0375f680-71d4-11eb-8255-f356a7962994.png)

**Comment by tschmetzer** [comment]
For the keyboard it is. I was thinking of including the mouse but a keyboard shortcut should be enough.
