### ISSUE TITLE
10 bit images appear to be clamped at 255 rather than scaled based on dynamic range

### ISSUE THREAD

**Issue by boxerab** [qgis/QGIS#41647]
Below is a 2x1 10 bit mono PNG.  The first pixel as ~300 and the second pixel is 0. 
QGIS displays the first pixel as 255, but is should be (300/1024) * 256

![ESP_011277_1825_RED](https://user-images.githubusercontent.com/95393/108270439-72ecd700-713d-11eb-82c6-ebbe3e4f073f.png)

**Comment by roya0045** [comment]
A sample is nice, but  pixels may be too minimal. If you have private data you could clip and displace/reproject to anonymize it somewhat. Also a screenshot and the usual qgis info would be appreciated.

**Comment by boxerab** [comment]
Thanks I thought I had attached an image. 

Here is a sample: 
![ESP_011277_1825_RED](https://user-images.githubusercontent.com/95393/108280649-805d8d80-714c-11eb-870d-84a75508a25e.png)

QGIS version 3.10.14

**Comment by gioman** [comment]
> Thanks I thought I had attached an image.

@boxerab there are no attachments here.

**Comment by roya0045** [comment]
@gioman it is there on both post. but its just two pixel as an image and not a file.

**Comment by gioman** [comment]
> but its just two pixel as an image and not a file.

I guess he must attach the original datasource

**Comment by boxerab** [comment]
Correction: as this is a 10 bit PNG, it is stored as 16 bit and there is no way of knowing that the original is 10 bit. So,
pixels should be scaled by 1/65536 .  For TIFF, we do know that it is 10 bit.

**Comment by boxerab** [comment]
@roya0045 the attached tiny image is enough to reproduce the issue.

**Comment by roya0045** [comment]
While the two pixels may be sufficient, this is more and annoyance and doesn't help much anyone that might be interested in fixing this. 

Otherwise you could just translate your data to 16bits and it should be fine.

**Comment by boxerab** [comment]
@roya0045  thanks, if you can point me to the code that does the scaling, I can take a look.

**Comment by roya0045** [comment]
First you can check with gdal info if the min max is correctly read.

**Comment by boxerab** [comment]
@roya0045 perhaps I am misunderstanding the QGIS spec. Do you perform auto adjustment of brightness and contrast ? or just display the pixels scaled to 0-255 ?

**Comment by boxerab** [comment]
This is probably not in fact a bug. Closing.
