### ISSUE TITLE
Export of animation ignores eye-dome lighting

### ISSUE THREAD

**Issue by wonder-sk** [qgis/QGIS#41648]
If I open a point cloud in QGIS, set 3D renderer, open a 3D view and enable eye-dome lighting, things are shaded as expected, e.g.:

![image](https://user-images.githubusercontent.com/193367/108277282-743bf500-7179-11eb-845f-ed65ca627b09.png)

When I use the animation tool in my 3D view, set up a simple animation and then export frames, they are exported without eye dome lighting:

![0021](https://user-images.githubusercontent.com/193367/108277379-9df51c00-7179-11eb-8038-cc610dc74709.jpg)

**Comment by jonnyforestGIS** [comment]
@wonder-sk just an additional info from the last master I tested. If you save the image from the current 3D View QGIS preserve the eye dome in the exporting image.

**Comment by wonder-sk** [comment]
Fixed in #41773

**Comment by wonder-sk** [comment]
@jonnyforestGIS that's right, with a single image export the EDL was working fine, but not with animation export...
