### ISSUE TITLE
Point cloud attributes not showing up on MacOS

### ISSUE THREAD

**Issue by palmerj** [qgis/QGIS#41656]
**Describe the bug**

Load a LAZ file into QGIS. No attribute information is showing. I've tested with multiple LAZ from difference sources. 

See:

<img width="1239" alt="qgis_mac_lidar" src="https://user-images.githubusercontent.com/580022/108314988-e4488a80-720e-11eb-9d69-cc57fd030e9c.png">

**QGIS and OS versions**

QGIS version | 3.17.0-Master | QGIS code revision | 4137287031
-- | -- | -- | --
Compiled against Qt | 5.14.2 | Running against Qt | 5.14.2
Compiled against GDAL/OGR | 3.2.1 | Running against GDAL/OGR | 3.2.1
Compiled against GEOS | 3.9.1-CAPI-1.14.2 | Running against GEOS | 3.9.1-CAPI-1.14.2
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
Compiled against PDAL | 2.2.0 | Running against PDAL | 2.2.0 (git-version: Release)
PostgreSQL Client Version | 12.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.4
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | macOS 10.16
Active python plugins | QuickWKT; linz-data-importer; LandXml; processing; db_manager; MetaSearch

**Comment by nyalldawson** [comment]
Did you wait until the background indexing finished?

**Comment by palmerj** [comment]
How do I know if it's complete? But it might be the issue. With the last file I tested I still have an empty side folder 'ept_USGS_LPC_CA_Klamath_TopoBathy_TL_2018_10TDL155975'. The law file has been loaded for 20mins and it's only 20mb in size.

**Comment by nyalldawson** [comment]
You'll see a task running in the progress bar

**Comment by nyalldawson** [comment]
Sorry, "status bar"!

**Comment by palmerj** [comment]
Thanks no active status bar. However, I've checked the point cloud log and now see:

```
2021-02-18T16:43:04     CRITICAL    Untwine executable not found /Applications/QGIS-Dev.app/Contents/MacOS/lib/qgis/untwine
2021-02-18T17:23:08     INFO    Created output directory /Users/jpalmer/Downloads/ept_USGS_LPC_CA_Klamath_TopoBathy_TL_2018_10TDL155975
2021-02-18T17:23:08     CRITICAL    Untwine executable not found /Applications/QGIS-Dev.app/Contents/MacOS/lib/qgis/untwine
```

**Comment by palmerj** [comment]
BTW this issue was not raised as a notification. I feel it should have been

**Comment by wonder-sk** [comment]
Oh, is the `untwine` executable really missing? That could be a packaging issue...

**Comment by palmerj** [comment]
Yip I think it's missing. The following:

```
% pwd
/Applications/QGIS-Dev.app
% find . | grep -I untwine
```

returns no results in the package bundle.

**Comment by PeterPetrik** [comment]
fixed in https://github.com/qgis/QGIS-Mac-Packager/commit/d19ea69f8e187d712a977cf7f113111e3bbd8e67

should be part of tomorrow's nightly build and rebuilded PR (available in hour or so)
