### ISSUE TITLE
[Point Cloud] Vertical 3D measures

### ISSUE THREAD

**Issue by jonnyforestGIS** [qgis/QGIS#41657]
Checklist before submitting

- [x] Search through existing issue reports and gis.stackexchange.com to check whether the issue already exists
- [x] Test with a [clean new user profile](https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html?highlight=profile#working-with-user-profiles).

**Describe the bug**
Point cloud disappears in 3D View or gives a Qt error: camera Position got Nan, after trying to do a 3d measurement in Z (Vertical) coordinate (for example measure a tree height).  

![image](https://user-images.githubusercontent.com/4480601/108322329-3eb8fb00-71bd-11eb-8ac2-778894d7bc85.png)

If a do a 3D measure on the terrain (horizontal) I don't receive any error.

![image](https://user-images.githubusercontent.com/4480601/108323132-3614f480-71be-11eb-9b74-f5507d2c2ff5.png)

Additionally, the values from measures aren't stored in the measurement temporary layer giving a QT error Retrying to obtain clipboard.

**How to Reproduce**

1. Add a point cloud
2. offset the point cloud (in my case -258).
3. Add a 3D View
4. Create a 3D Measure
5. Click New and try to do a 3d measure in point cloud

**QGIS and OS versions**
Testing the new installer.
https://www.lutraconsulting.co.uk/blog/2021/02/15/qgis-point-cloud-windows/ 

QGIS   version | 3.17.0-Master | QGIS code revision | 93239b150
-- | -- | -- | --
Compiled   against Qt | 5.15.2 | Running against Qt | 5.15.2
Compiled   against GDAL/OGR | 3.2.1 | Running against GDAL/OGR | 3.2.1
Compiled   against GEOS | 3.9.1-CAPI-1.14.2 | Running against GEOS | 3.9.1-CAPI-1.14.2
Compiled   against SQLite | 3.33.0 | Running against SQLite | 3.33.0
Compiled   against PDAL | 2.2.0 | Running against PDAL | 2.2.0 (git-version: 38aa11)
PostgreSQL   Client Version | 13.0 | SpatiaLite Version | 5.0.1-rc1
QWT   Version | 6.1.3 | QScintilla2 Version | 2.11.5
Compiled   against PROJ | 7.2.1 | Running against PROJ | Rel. 7.2.1, January 1st, 2021
OS Version | Windows 10 Version 2009 | This copy of QGIS   writes debugging output.
Active   python plugins | processing

**Comment by PedroVenancio** [comment]
I confirm this behaviour @jonnyforestGIS , also on Linux.

**Comment by roya0045** [comment]
Maybe @ismailsunni or @NEDJIMAbelgacem would have a clue.

**Comment by wonder-sk** [comment]
Measuring on point clouds is not supported yet unfortunately... (The "horizontal" measuring works just because the measure tool ends up picking points from the terrain under the point cloud.)

**Comment by saberraz** [comment]
With the profile tool and support for measuring tools, this ticket is redundant.

**Comment by jonnyforestGIS** [comment]
Hi @saberraz for me make sense. Cheers

**Comment by nadir-advian** [comment]
Any update regarding this?
