### ISSUE TITLE
Least Cost Path more than one legal point

### ISSUE THREAD

**Issue by xnxnxnxnxnxn** [qgis/QGIS#41651]
Failure to create least cost path
ERROR: The start-point layer contains more than one legal point.
 I have dropped the Z values, standardised the CRS, rasterised and classified my vector layer. 
[rcTQiEaG.txt](https://github.com/qgis/QGIS/files/6000025/rcTQiEaG.txt)

**Comment by gioman** [comment]
@xnxnxnxnxnxn 

please re-open with

    a meaningful title

    all the requested infos

Describe the bug

How to Reproduce

    Go to '...'
    Click on '....'
    Scroll down to '....'
    See error -->

QGIS and OS versions

Additional context
