### ISSUE TITLE
Color gradient min and max values are incorrect for grayscale tiff

### ISSUE THREAD

**Issue by kipodon** [qgis/QGIS#41662]
the values I see is 
min: 1.79769e+308
max -1.79769e+308

[gray.zip](https://github.com/qgis/QGIS/files/6002287/gray.zip)

The data is 8 bit grayscale, so those values are incorrect.
no data value is 0. 
I see this tiff as black and white only.
After setting the min and max values to 0 and 255. I can see the data correctly.

I have QGIS 3.16.3

**Comment by gioman** [comment]
There is definitely something very wrong when opening for the first this type of raster (which has min 1 and max 255, checked with GDAL info):

![Screenshot_20210218_114039](https://user-images.githubusercontent.com/1951107/108352013-2b6a5780-71de-11eb-9706-2b578805ab2b.png)

I don't think I have never seen a so large number :)

**Comment by elpaso** [comment]
This is what is happening:

- by default approximate statistics are gathered through GDAL
- GDAL algorithm collect samples in blocks through the diagonal
- the sample raster diagonal in this particular raster has only nodata hence no statistics are gathered

The large numbers you see are actually non appropriate for the data type and this is probably something we can make it better.

The workaround is to select "Actual (slower)" to get accurate statistics.

![immagine](https://user-images.githubusercontent.com/142164/108388603-16f28300-720f-11eb-9a75-a7b6d3b391a3.png)
