### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by John-JW-Kim** [qgis/QGIS#41660]
Crash ID: b541c228e3becd06d17a7cd04bfeaf46b1f8083d

Stack Trace

geos::noding::snapround::MCIndexSnapRounder::computeVertexSnaps :
geos::noding::snapround::MCIndexSnapRounder::computeVertexSnaps :
GEOSEquals_r :
OGRToOGCGeomType :
OGRLayer::FilterGeometry :
SHPPartTypeName :
QgsOgrFeatureIterator::fetchFeature qgsogrfeatureiterator.cpp:387
QgsAbstractFeatureIterator::nextFeature qgsfeatureiterator.cpp:63
QgsVectorLayerFeatureIterator::fetchFeature qgsvectorlayerfeatureiterator.cpp:442
QgsAbstractFeatureIterator::nextFeature qgsfeatureiterator.cpp:63
QgsVectorLayerRenderer::drawRenderer qgsvectorlayerrenderer.cpp:346
QgsVectorLayerRenderer::render qgsvectorlayerrenderer.cpp:317
QgsMapRendererParallelJob::renderLayerStatic qgsmaprendererparalleljob.cpp:353
QtConcurrent::MapKernel::iterator,QtConcurrent::FunctionWrapper1 >::runIteration qtconcurrentmapkernel.h:69
QtConcurrent::MapKernel::iterator,QgsImageOperation::ProcessBlockUsingPixelOperation >::runIterations qtconcurrentmapkernel.h:78
QtConcurrent::IterateKernel::iterator,void>::forThreadFunction qtconcurrentiteratekernel.h:256
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.16.3-Hannover
QGIS code revision: 94ac9f21b8
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

**Comment by gioman** [comment]
@John-JW-Kim please re-file with

a meaningful title

+ all the requested infos




**Describe the bug**


**How to Reproduce**



1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error -->

**QGIS and OS versions**



**Additional context**
