### ISSUE TITLE
Global transparency does nothing for raster contour renderer

### ISSUE THREAD

**Issue by timlinux** [qgis/QGIS#41663]
Maybe one for @wonder-sk ? I have an issue where I am using the raster contour renderer, but the global transparency when using this has no effect:

![contours](https://user-images.githubusercontent.com/178003/108356116-9e2a0180-71e3-11eb-9932-74d66cc56843.gif)

**Comment by gioman** [comment]
@timlinux I also noticed that the "heatmap" symbology for point layers does not have a general transparency controller (the workaround is to set the transparency on each stop of the scale ramp, not very handy).

**Comment by Pedro-Murteira** [comment]
I can still replicate this behaviour on QGIS 3.16.14 and 3.22.1.
