### ISSUE TITLE
[Point Cloud] Different behaviour between entwine and untwine datasets

### ISSUE THREAD

**Issue by Jean-Roc** [qgis/QGIS#41666]
Hi,

QGIS does not show the same behaviour between an EPT created with Entwine and an EPT built by the integrated Untwine, both being produced based on the same LAZ source :

 - there is a geometry offset (both in 2d/3d)
   <img src="https://user-images.githubusercontent.com/736212/108362080-94a89580-71f3-11eb-8199-b182ead9790f.JPG" data-canonical-src="https://user-images.githubusercontent.com/736212/108362080-94a89580-71f3-11eb-8199-b182ead9790f.JPG" width="200" />
 - when using *attribute by ramp* with the entwine ept, no color ramp or min/max is generated, I have to input them manually while with the untwine ept it is automatic
 - in the layer properties, the statistic panel is empty for entwine and filled with untwine

My understanding was that Untwine was meant to create a compatible EPT structure but it seems not be the case here. Untwine has an additional **stats**option which populate the ept.json file, this could explain the ramp problem but not sure about the offset.

**How to Reproduce**

```
entwine build -c config.json

{
    "input": "zone_3.laz",
    "output": "ept_zone_3_entwine",
	"threads":4,
	"tmp":"temp_dir"
}
```

**QGIS and OS versions**
3.17.0-Master 4fc02733c

**Comment by Jean-Roc** [comment]
Just found out that the built-in stats are needed ([source](https://github.com/wonder-sk/point-cloud-experiments/issues/60)), Martin should I close this issue ?

Does the use of pdal info/stat output could help to use an existing EPT ? I have a 117 billions dataset that took a while to compute and upload :)

**Comment by nyalldawson** [comment]
You possibly have an ept generated by an older untwine release. Can you delete the ept file and allow it to be rebuilt from the las?

**Comment by Jean-Roc** [comment]
sorry if I was not clear, the untwine version is the one built-in the new osgeo4w's qgis and it works as expected, that's the EPTs built with Entwine 2.1/PDAL 2.2 that cannot be correctly used.

**Comment by wonder-sk** [comment]
So if I understand correctly, you are facing two issues:
- geometry offset of data when generated from Entwine - how big is the offset? If it is not more than a meter, it is most likely caused by https://github.com/connormanning/entwine/issues/245 - in untwine this has been fixed. There is a task still open in https://github.com/wonder-sk/point-cloud-experiments/issues/75 that would fix the offset issue for existing EPT datasets, which we may implement
- issues due to missing stats - yes for that we have task https://github.com/wonder-sk/point-cloud-experiments/issues/60 but we left it with lower priority as the main use case was for LAS/LAZ files which we process and generate stats at the same time.

As for adding stats to an existing EPT dataset - I think that should be doable, probably by running PDAL using its EPT reader, getting the stats and then semi-manually insert them to ept.json - but I have not done myself (and maybe there's an easier way directly with Entwine).

**Comment by Jean-Roc** [comment]
I merged the statistic output of pdal info into the schema block of the entwine EPT, it does the job !

About the offset, on this sample it is < 1m/X and < 4m/X

Entwine :

```
    {
    	"name": "X",
    	"offset": 1708079.0,
    	"scale": 0.01,
    	"size": 4,
    	"type": "signed",
    	"average": 1708083.815,
    	"count": 42332566,
    	"maximum": 1708114.83,
    	"minimum": 1708043.63,
    	"position": 0,
    	"stddev": 12.12851071,
    	"variance": 147.100772
    }, {
    	"name": "Y",
    	"offset": 9269186.0,
    	"scale": 0.01,
    	"size": 4,
    	"type": "signed",
    	"average": 9269181.453,
    	"count": 42332566,
    	"maximum": 9269227.64,
    	"minimum": 9269145.17,
    	"name": "Y",
    	"position": 1,
    	"stddev": 15.19095399,
    	"variance": 230.7650831
    },
```

Untwine :

```
{
	"name": "X",
	"type": "float",
	"scale": 0.01,
	"offset": 1.70808e+06,
	"size": 8,
	"count": 42332566,
	"maximum": 1.70811e+06,
	"minimum": 1.70804e+06,
	"mean": 1.70808e+06,
	"stddev": 12.1285,
	"variance": 147.101
}, {
	"name": "Y",
	"type": "float",
	"scale": 0.01,
	"offset": 9.26919e+06,
	"size": 8,
	"count": 42332566,
	"maximum": 9.26923e+06,
	"minimum": 9.26915e+06,
	"mean": 9.26918e+06,
	"stddev": 15.191,
	"variance": 230.765
},
```

**Comment by wonder-sk** [comment]
Thanks for the feedback and for the samples from your ept.json - this confirms that the issue would go away once https://github.com/wonder-sk/point-cloud-experiments/issues/75 is implemented.

**Comment by wonder-sk** [comment]
The problem with geometry offset just went away as we merged https://github.com/qgis/QGIS/pull/43055

Shall we close the ticket or is there anything else left?

**Comment by Jean-Roc** [comment]
Thanks Martin, yes I'll close it, I'll test the fix as soon as a nightly win build is available
