### ISSUE TITLE
QGIS crashes when trying to open raster in georeferencer

### ISSUE THREAD

**Issue by karpfen** [qgis/QGIS#41665]
**Describe the bug**
When trying to use the Georeferencer, QGIS closes completely without any warning or message.

**How to Reproduce**

1. Open QGIS
2. Open Georeferencer via Raster/Georeferencer...
3. Click on "Open Raster..." button (alternatively, hit ctrl + o or use File/Open Raster...)
4. QGIS process and windows close

**QGIS and OS versions**

QGIS version | 3.16.3-Hannover | QGIS code branch | Release 3.16
-- | -- | -- | --
Compiled against Qt | 5.15.2 | Running against Qt | 5.15.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.34.1 | Running against SQLite | 3.34.1
PostgreSQL Client Version | 13.1 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.6 | QScintilla2 Version | 2.11.6
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Manjaro Linux
Active python plugins | MetaSearch; processing; db_manager

**Additional context**

I tried this on a new installation of QGIS without any additional plugins. When opening QGIS via the command line, it outputs a message `QGIS died on signal 11Aborted (core dumped)` on crash.

**Comment by gioman** [comment]
@karpfen attach the image you are trying to open in the georeferencer.

**Comment by karpfen** [comment]
@gioman The crash occurs before selecting or opening any image (see steps for reproducing the error).

**Comment by gioman** [comment]
> @gioman The crash occurs before selecting or opening any image (see steps for reproducing the error).

@karpfen then you probably have a local issue, this is not a general one (tested on the supported platforms, i.e. Ubuntu, Windows and macOS).

**Comment by karpfen** [comment]
@gioman Yes, seems like it, although it's strange because it's a clean install on a newly setup machine. Do you have any idea how I could get more info on the crash aside from the very brief log message?

**Comment by uclaros** [comment]
I am not familiar with Manjaro, but it could the same as #40808 ?

**Comment by roya0045** [comment]
@uclaros agreed, this is not specific to the georeferencer but the dialog/native browser and Manjaro.

**Comment by karpfen** [comment]
@uclaros yes, that definitely looks related. I am able to reproduce the crash with the data source manager as well.

**Comment by gioman** [comment]
Closing for lack of feedback.
