### ISSUE TITLE
Crashing each time I am saving

### ISSUE THREAD

**Issue by LucieCubico** [qgis/QGIS#41689]
## User Feedback

I am not able to save my project anymore, it crashes all the time. If you can help I would be very grateful. 

## Report Details

**Crash ID**: [c8df489faa40896b3b21fe32b4bc017eaeca6335](https://github.com/qgis/QGIS/search?q=c8df489faa40896b3b21fe32b4bc017eaeca6335&type=Issues)

**Stack Trace**
<pre>
QgsRasterLayer::writeXml qgsrasterlayer.cpp:2121
QgsMapLayer::writeLayerXml qgsmaplayer.cpp:537
QgsProject::writeProjectFile qgsproject.cpp:2309
QgsProject::write qgsproject.cpp:2174
QgisApp::fileSaveAs qgisapp.cpp:7287
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1637
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.16.3-Hannover
QGIS code revision: 94ac9f21b8
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

**Comment by gioman** [comment]
@LucieCubico you must try with a new QGIS profile, and no 3rd party plugins installed in the new profile.

If the problem persist you must detail the steps that lead to the crash, and attach all necessary relevant project/data.

**Comment by roya0045** [comment]
Out of ressource, locks? I assume this happens with only one project.

**Comment by gioman** [comment]
Closing for lack of feedback.
