### ISSUE TITLE
topology editing does not work if layer crs does not match project crs

### ISSUE THREAD

**Issue by Meibes** [qgis/QGIS#41686]
**Describe the bug**
topology editing does not work if layer crs does not match project crs. in qgis 3.10 and 3.16

**How to Reproduce**

1. open qgis
2. enable snap and topology editing if you have not
3. create temp layer with lines
4. digitize 2-3 lines
5. check if topology editing is working by moving some vertexes
6. save layer
7. change project crs to anything else
8. start edit layer
9. check if topology editing is working (it should not)
10. revert project crs
11. check if topology editing is working (it should)

**QGIS and OS versions**

QGIS-Version
3.16.3-Hannover
QGIS-Codeversion
94ac9f21b8
Kompiliert gegen Qt
5.11.2
Laufendes Qt
5.11.2
Kompiliert mit GDAL/OGR
3.1.4
Läuft mit GDAL/OGR
3.1.4
Kompiliert mit GEOS
3.8.1-CAPI-1.13.3
Läuft mit GEOS
3.8.1-CAPI-1.13.3
Kompiliert mit SQLite
3.29.0
Läuft mit SQLite
3.29.0
PostgreSQL-Client-Version
11.5
SpatiaLite-Version
4.3.0
QWT-Version
6.1.3
QScintilla2-Version
2.10.8
Kompiliert mit PROJ
6.3.2
Läuft mit PROJ
Rel. 6.3.2, May 1st, 2020
BS-Version
Windows 10 (10.0)

**Comment by uclaros** [comment]
This was already reported in #29648 and recently fixed by #41306
