### ISSUE TITLE
Installation via QSGEO4W error:  Could not load qgis_app.dll 

### ISSUE THREAD

**Issue by MoritzBrennecke** [qgis/QGIS#41685]
Installation via OSGEO4W on Windows 10 (advanced install qgis-ltr):
![image](https://user-images.githubusercontent.com/40693210/108473173-fa496000-728d-11eb-8899-834b65915095.png)
Sqlite3.dll pops up during installation:
![image](https://user-images.githubusercontent.com/40693210/108473288-21079680-728e-11eb-9aec-3f857e3a5c2d.png)
After installation, Could not load qgis_app.dll error:
![image](https://user-images.githubusercontent.com/40693210/108473375-3da3ce80-728e-11eb-8bd2-79f0abc7a322.png)
Qgis is not launching.

**Workaround:**
1.	Installation of  « QGIS Standalone »
2.     Copying all files from c : /programmes/QgisXXX/Bin to  c : /OSGEO4W/Bin (exclude those allready existing)
3.	Uninstall standalone (via uninstall in c : /programmes/QgisXXX/Bin)

**So there are obviously some essentiel dlls missing when performing the advanced installation mode of QGIS. I suggest to include them if not many windows users will not use this (once working) very powerfull installer**

**Comment by SebastienPeillet** [comment]
Hello @MoritzBrennecke 

I just verified the oslandia mirror repository and I installed qgis-ltr package without reproducing the problem...

The Sqlite3.dll pop up lets me think about a **md5 sumcheck failure**. Normally, the files you downloaded are located in "local package directory folder : 

![image](https://user-images.githubusercontent.com/18545440/108483343-e9531b80-729a-11eb-8263-c742c60c4918.png)

In it, there is the x86_64/setup.ini file, the checksum for the sqlite3 package must be the same than the real cheksum

![image](https://user-images.githubusercontent.com/18545440/108483512-1dc6d780-729b-11eb-9fb0-4d0d1ecd29c1.png)

For the sqlite3-3.29.0-1.tar.bz package, it's 3afb96de826240086a557558ab2aae51

I checked it also on the serveur : 

![image](https://user-images.githubusercontent.com/18545440/108483865-7dbd7e00-729b-11eb-8daa-808b419ce144.png)

It's possible that there is a mixed between an old attempt to install qgis with OSGeo4W... When it can, it use local files instead of re-downloading files.

To fix it, you can uninstall your OSGeo4W and clean your local packages directory. Doing so, it will download the lastest version of each package and there will be no trouble anymore.

**Comment by SebastienPeillet** [comment]
Futhermore, if the problem persists (even if I don't think it will), you can use a different mirror : 

![image](https://user-images.githubusercontent.com/18545440/108485004-bdd13080-729c-11eb-853c-7959d441b27d.png)

In every case, I don't think it's a QGIS bug :)

**Comment by MoritzBrennecke** [comment]
I had the same problem on several computers (so reproducing works!).
This one is an out of the box laptop (so for sure no prior QGIS installation!)
Also tried different mirrors (did not work).
So these are the files which are not coming with the OSGEO4W Installation (date 18.02.2021):
![image](https://user-images.githubusercontent.com/40693210/108485322-16a0c900-729d-11eb-8dde-ecb1c51317a4.png)
**To reproduce the error**, I cut these files into c:/temp (so they where not there anymore), -> Got the same error message.
Copied back -> Everything is fine.
So for me it seems to be these files!

**Comment by SebastienPeillet** [comment]
... :/ I'm not really sure what appends on your side as I can't reproduce the bug...

But for sure, qgis_app.dll shouldn't be copy in C:\OSGeo4W, this file is installed with the qgis-ltr package : 

![image](https://user-images.githubusercontent.com/18545440/108490022-89607300-72a2-11eb-91d3-f968a5b79046.png)

I just realized that your installation folder is C:\OSGeo4W and not  C:\OSGeo4W64. Are you using a 32bit system ? It can explain I can't reproduced the bug as I have only a 64bit system to test it.

**Comment by MoritzBrennecke** [comment]
Actually more funny than that.
Standalone was with the 3.16 version, so the 3.16 version works, but not the 3.10 version (only installed via OSGEO4W).
So I reinstalled 3.10 via standalone:

- It worked fine launching from C:/programmes/QGIS/bin (standalone)
- And also (without doing anything else!) launching from C:/OSGEO4W/bin/qgis-ltr-bin.exe works!
- Then uninstall QGIS standalone -> It does not work anymore with  C:/OSGEO4W/bin/qgis-ltr-bin.exe works!


Maybe the problems is that I have a domain on login when installing in Windows (some rights problem) even installing with admin rights? Does Windows have to activate the dlls
And I'm using 64bit system and 64 bit installer (so no bug there)

Sorry I cannot investigate any further, so I will use (unfortunately) the standalone which works fine.

**Comment by gioman** [comment]
> Sorry I cannot investigate any further, so I will use (unfortunately) the standalone which works fine.

@MoritzBrennecke seems anyway a local issue and not a general one.

**Comment by GGDRriedel** [comment]
I had this too. 
Make sure to install into new package as well as install folders when using OSGEO4W. 
If you don't and another install is present, the installer will use the old folders to throw these files into

**Comment by MoritzBrennecke** [comment]
Thank you all for the very fast responses and taking the time!

Still do not know why there is this error (In my opinion it has to do with some admin rights when installing and copying the dlls)
Anyway, it is working for me now (I repeated installing standalone /OSGEO4W the uninstall standalone and it worked for the ltr as well). -> Good to know there is one. 
=> Should I close this issue?

**Comment by gioman** [comment]
>  => Should I close this issue?

done.

**Comment by MoritzBrennecke** [comment]
Hello,

Had the time to investigate the issue.
It seems that there is a problem with the sqlite3.dll.
During installation with OSGEO4W I get this error message:
![image](https://user-images.githubusercontent.com/40693210/108707290-13f9da00-7510-11eb-9623-f853b7172524.png)
and this one
![image](https://user-images.githubusercontent.com/40693210/108707496-60451a00-7510-11eb-90a1-0f516fb60666.png)

After installation:
![image](https://user-images.githubusercontent.com/40693210/108707736-bfa32a00-7510-11eb-9ccb-c53b36506d41.png)



_When I copy the **sqlite3.dll** file (which did not install with OSGEO4W but which I took from another QGIS standalone installation and paste it to C:\OSGeo4W64\bin everything works fine.!!
So it seems that this file is not being copied during OSGEO4W installation but I do not know why!

Thank you

**Comment by jef-n** [comment]
@MoritzBrennecke Remove the file from your cache and retry.

**Comment by RossFF80** [comment]
Qt designer has a QGIS plug-in, thats how I worked around it
