### ISSUE TITLE
Crash using TIN interpolation

### ISSUE THREAD

**Issue by MirkoRamoni** [qgis/QGIS#41682]
Crash ID: 8751eff3ff699165138c78667eb0ce44518794de

Stack Trace

QList::append qlist.h:600
DualEdgeTriangulation::triangulatePolygon dualedgetriangulation.cpp:2472
DualEdgeTriangulation::triangulatePolygon dualedgetriangulation.cpp:2477
DualEdgeTriangulation::insertForcedSegment dualedgetriangulation.cpp:1499
DualEdgeTriangulation::addLine dualedgetriangulation.cpp:90
QgsTinInterpolator::insertData qgstininterpolator.cpp:312
QgsTinInterpolator::initialize qgstininterpolator.cpp:141
QgsTinInterpolator::interpolatePoint qgstininterpolator.cpp:56
sipQgsTinInterpolator::interpolatePoint sip_analysispart1.cpp:9421
QgsGridFileWriter::writeFile qgsgridfilewriter.cpp:65
meth_QgsGridFileWriter_writeFile sip_analysispart2.cpp:54
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_sip :
sipVH__core_331 sip_corepart0.cpp:17403
sipQgsProcessingAlgorithm::processAlgorithm sip_corepart2.cpp:190671
QgsProcessingAlgorithm::runPrepared qgsprocessingalgorithm.cpp:502
QgsProcessingAlgRunnerTask::run qgsprocessingalgrunnertask.cpp:66
sipQgsProcessingAlgRunnerTask::run sip_corepart1.cpp:91992
QgsTask::start qgstaskmanager.cpp:78
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.10.14-A Coru�a
QGIS code revision: 8374282d2a
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
@MirkoRamoni please test on the latest 3.16 as this version has fixes that were not ported to 3.10.

**Comment by MirkoRamoni** [comment]
Ok, thank you.

Mirko RAMONI

De : Giovanni Manghi [mailto:notifications@github.com]
Envoyé : vendredi 19 février 2021 11:12
À : qgis/QGIS <QGIS@noreply.github.com>
Cc : Mirko Ramoni <mirko.ramoni@seef.cm>; Mention <mention@noreply.github.com>
Objet : Re: [qgis/QGIS] Crash using TIN interpolation (#41682)


@MirkoRamoni<https://github.com/MirkoRamoni> please test on the latest 3.16 as this version has fixes that were not ported to 3.10.

**Comment by gioman** [comment]
Closing for lack of feedback.
