### ISSUE TITLE
QGis unexpectetedly ended

### ISSUE THREAD

**Issue by evillar19** [qgis/QGIS#41697]
Crash ID: 472ea3512682a3798d2cecc71f612973b1cc7185

Stack Trace

QMetaObject::activate :
QHttpMultiPart::qt_metacast :
QSslKey::operator!= :
QSslKey::operator!= :
QMetaObject::activate :
QAbstractSocket::proxyAuthenticationRequired :
QMetaObject::activate :
QAbstractSocket::proxyAuthenticationRequired :
QNetworkProxyQuery::networkConfiguration :
QMetaObject::activate :
QAbstractSocket::disconnected :
QAbstractSocket::canReadLine :
QNetworkProxyQuery::networkConfiguration :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
QEventLoop::exec :
QThread::exec :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.16.3-Hannover
QGIS code revision: 94ac9f21b8
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

**Comment by DelazJ** [comment]
@evillar19 you need to provide more details about what you were doing when the crash occurs. To help people reproduce and fix.

**Comment by gioman** [comment]
> @evillar19 you need to provide more details about what you were doing when the crash occurs. To help people reproduce and fix.

@evillar19 also try with a new QGIS profile.

**Comment by gioman** [comment]
Closing for lack of feedback.
