### ISSUE TITLE
Buffer processing: Inward buffer produces areas in certain conditions

### ISSUE THREAD

**Issue by tschmetzer** [qgis/QGIS#41696]
For most of my objects the inward buffer tool works fine with a negative distance yet for some features residuals are produced where there shouldn't be any. I don't know if this behaviour is within the specs of a negative buffer or not. There doesn't seem to be a logic behind it besides a multiple processing of the same areas by the inward buffer tool.  I couldn't get rid of the problem varying any parameters besides the _distance_ parameter. The problem occurred in my appended example case only somewhere within the values between 3.9 and 4.55 m. I would expect a behaviour similar to an erosion tool.

It did not happen when the feature object contained more than 4 vertex points. 

Is this behaviour well known, documented and accepted or am I the first one to notice? At least I couldn't find anything in the docs. Any ideas for a workaround?

Thanks in advance!

![inward_buffer_bug_dialog](https://user-images.githubusercontent.com/67278094/108549582-9e162880-72ed-11eb-9f0a-c5f57e8a1dfd.PNG)
![inward_buffer_bug](https://user-images.githubusercontent.com/67278094/108549587-9fdfec00-72ed-11eb-8890-2f0b8d49f2be.PNG)

QGIS version | 3.16.3-Hannover | QGIS code revision | 94ac9f21b8
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | FreehandRasterGeoreferencer; GroupStats; nominatim; QuickOSM; db_manager; MetaSearch; processing

[inward_buffer_base_layer.zip](https://github.com/qgis/QGIS/files/6013494/inward_buffer_base_layer.zip)

**Comment by uclaros** [comment]
Your uploaded archive only contains the `.shp` file of the shapefile. Can you update to also contain at least the `.shx` and `.dbf` files?

**Comment by tschmetzer** [comment]
> 
> 
> Your uploaded archive only contains the `.shp` file of the shapefile. Can you update to also contain at least the `.shx` and `.dbf` files?

I just updated it :)

**Comment by uclaros** [comment]
Seems like an upstream bug in geos, I can also replicate in shapely. Adding a vertex snapped to a segment makes the buffer correctly return an empty geometry.
I opened an ticket on the geos tracker https://trac.osgeo.org/geos/ticket/1101

**Comment by dr-jts** [comment]
This is now fixed in JTS and GEOS main.

**Comment by uclaros** [comment]
> This is now fixed in JTS and GEOS main.

Thanks!
Since it's also backported to GEOS 3.8 and 3.9 the fix should soon land on a qgis release. Should we close this?

**Comment by tschmetzer** [comment]
Depends on how issue closing is handled within QGIS. In the automotive area the author has to test and confirm the successful implementation but here I don't know.
