### ISSUE TITLE
QGIS WMS client fires (too) many requests to WMS server

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS#41691]
(see also https://github.com/qgis/QGIS/issues/41504#issuecomment-779035126)

When you connect to a straight WMS like:
https://geodata.nationaalgeoregister.nl/bestuurlijkegrenzen/ows?SERVICE=WMS&
and choose layer 'gemeenten' in EPSG:28992

At first QGIS fires one request per view: OK
But as soon as you zoom in (to be checked with the F12 debugging window) and then panning you will see like 6 or more requests being fired per 'view' of the canvas.

I collected the fired requests, and then you can see that QGIS retrieves not only current canvast view (in image below the central one), but also the surronding ones:

![nl](https://user-images.githubusercontent.com/731673/108506396-fe3ea780-72b8-11eb-821e-069a7a8bf339.png)

It is not ALWAYS that it fires so many requests, sometimes it's just (rightly) one.

I think a WMS should only request current mapcanvas view, as argumented here:
https://lists.osgeo.org/pipermail/qgis-developer/2021-February/063085.html

I tried to debug and find out WHERE it is decided to fire the surrounding 'tiles', but I cannot find it.

**Comment by rduivenvoorde** [comment]
Another observation during debugging: this (to me) seems to be some kind of threading issue?

If you at a certain moment are in 'fire many requests mode': like panning the whole map lenght, you keep sending 9 (or less) requests per pan action. 
BUT(!) if you put a breakpoint here:
https://github.com/qgis/QGIS/blob/master/src/providers/wms/qgswmsprovider.cpp#L706
and wait for a second before going further (F5), then you do NOT get those requests for surrounding tiles.
As if those surrounding tiles requests are some kind of threading/timing byproduct or so???

**Comment by jgrocha** [comment]
AJAX was the key technology that enabled the web maps we loved so much. The rational is to have asynchronous calls in the background fetching data advance even before it is needed. 

We can discuss how many or which requests should be made. But it is completely awkward to return to a model where we only fetch the area in the canvas. It goes back to the synchronous paradigm, which does not provide a good user experience.

If the server resources are a problem, you should create a caching tier upstream of QGIS to lower the number of requests from the original server. It is quite simple and the user experience is good and server resources are spared.

If you think the current prefetch in place is suboptimal, that should be improved.

**Comment by rduivenvoorde** [comment]
@jgrocha nope, I think you miss the point of the WMS standard: NO prefetching and prerendering: but clear fresh rendering for every request: NO caching. Else use xyx, WMS-c or WMTS.! As said: getting more and more services moving from free to paid per request, it is better to stick to the standard, and only fetch the requests that you should according to it.
Especially in QGIS where it is too easy to move between scales (not deterministic), it is sub optimal (and resource-eating) to 'let's fetch 9 times the amount of viewable space'. 
NOTE: we are talking about WMS here, so NO defines scales. But even when you stay on the same scale, it looks like QGIS is actually NOT using the fetch (let's call them) 'tiles'.

**Comment by elpaso** [comment]
IMHO this is a bug.

**Comment by rduivenvoorde** [comment]
@elpaso I had a short conversation on IRC with 'pnorman' about the OpenStreetMap tiles and your fix for https://github.com/qgis/QGIS/issues/34813 

All works fine for OSM...!

BUT: then I thought to comment the line in which we add the 'prefetch' flag:

https://github.com/qgis/QGIS/blob/master/src/providers/wms/qgswmsprovider.cpp#L2017

If I do that THEN the WMS is NOT requesting the surrounding 'tiles' anymore?

So would it be a solution to figure out IF we are requesting a true WMS as service, and add that to the 'test' IF the 'prefetch' flag is to be added or not?

**Comment by elpaso** [comment]
@rduivenvoorde that should work.

**Comment by pathmapper** [comment]
Fixed by @rduivenvoorde in https://github.com/qgis/QGIS/pull/41832 / https://github.com/qgis/QGIS/pull/41953

**Comment by gioman** [comment]
> Fixed by @rduivenvoorde in #41832 / #41953

@rduivenvoorde @pathmapper so can we close this?

**Comment by pathmapper** [comment]
@gioman yep
