### ISSUE TITLE
Handle Unavalable Layers acting unexpectedly

### ISSUE THREAD

**Issue by Isaacson33** [qgis/QGIS#41690]
On 

QGIS version | 3.16.3-Hannover | QGIS code branch | Release 3.16
-- | -- | -- | --
Compiled against Qt | 5.15.2 | Running against Qt | 5.15.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.34.1 | Running against SQLite | 3.34.1
PostgreSQL Client Version | 13.1 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.6 | QScintilla2 Version | 2.11.6
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Manjaro Linux
Active python plugins | TomBio; db_manager; processing

When opening a project where the main data-source (a spatialite database) has changed name, the 'Handle Unavailable Layers' process is acting unexpectedly. Firstly it's not registering the new name when I correct it, it continues to treat it as an unavailable source even though it's now a bona fide source in the correct directory. Secondly, for three shapefiles that are also part of the project (but needed renaming too), it has simply automatically selected one of the shapefiles in the directory to match all three. Thirdly, when finally selecting 'keep unavailable layers' each unavailable layer is assigned, as a data-source, the entire unavailable source urls all concatenated together into one long text string.

When I repair data-source in the project, it works for one or two layers without fault and then QGIS crashes.

**Comment by gioman** [comment]
> When opening a project

@Isaacson33 can you attach it?

**Comment by Isaacson33** [comment]
> can you attach it?

No, it's sensitive. It's not the sort of problem I can really replicate in a self contained project because the problem arises when trying to change the name of a spatialite database (or moving a database within a directory structure). It something that could only really be replicated on another person's system.

Part of my usual workflow is to copy a qgz project from one directory to another and then point it (using the unavailable layers dialogue) to the new database (exactly the same _relative_ directory location, just a different name). I probably carry out this same workflow twenty times in a year, so I'm quite familiar with it. This time (after upgrade to 3.16.3), it just didn't work - as above.

**Comment by gioman** [comment]
>  It something that could only really be replicated on another person's system.

@Isaacson33 ok, but we need a way to be able to replicate here, otherwise is difficult to help and expect a fix.

**Comment by roya0045** [comment]
@Isaacson33 update your qgis, some aspect might have been solver already

**Comment by Isaacson33** [comment]
>we need a way to be able to replicate here, otherwise is difficult to help and expect a fix.

I understand. Not sure what to do, Try this
[test.zip](https://github.com/qgis/QGIS/files/6010298/test.zip)

1. I rename the sqlite file to something like test2.sqlite and open the project file, the Handle Unavailable Layers dialogue arrives. 
2. I manually rename the source from test.sqlite to test2.sqlite. 
3. Normally I'd expect that to work. Now it just remains as if it were still unavailable.

>update your qgis, some aspect might have been solver already

I have the latest release (though not the nightly). If it's been solved by chance that would be luck indeed. I did check through the bug reports first in case it'd been reported already.

**Comment by roya0045** [comment]
And if you hit 'apply change' after changing the name it doesn't accept it?

**Comment by gioman** [comment]
> And if you hit 'apply change' after changing the name it doesn't accept it?

@roya0045 no, it doesn't work. I'm on master.

**Comment by roya0045** [comment]
Strange, I'll look into it.

**Comment by roya0045** [comment]
@gioman If you have a few moments could you check master or 3.18 on windows? I'm assuming your windows environment will be updated regardless.

**Comment by gioman** [comment]
> @gioman If you have a few moments could you check master or 3.18 on windows? I'm assuming your windows environment will be updated regardless.

@roya0045 not working.

**Comment by roya0045** [comment]
Good, at least it's not platform specific.

**Comment by roya0045** [comment]
@gioman could you remove the feedback label. I think this one is confirmed by you. Hopefully I should be able to inspect this during the week.

**Comment by roya0045** [comment]
@gioman Thanks!

**Comment by roya0045** [comment]
Ok this seems to be specific to spatialite and how the path is represented.

**Comment by roya0045** [comment]
The flags seem to be present. This might be fixed.

**Comment by Pedro-Murteira** [comment]
@roya0045 @Isaacson33 This issue appears to be fixed. Tested on QGIS 3.22.3. (Windows 10)
