### ISSUE TITLE
Custom Function returns NULL value when run in Field Calculator (Preview works fine)

### ISSUE THREAD

**Issue by Jimzi** [qgis/QGIS#41695]
Hi,
This is my first bug report, if it is missing info or not in the correct format please bear with me and let me know and I will edit/provide as needed. Thanks!

I'm working on a project with a _Trees_ layer (points), and an _Irrigation Zones_ layer (polygons) inside a geopackage file.

I'm trying to run a custom function that updates an existing text field on Trees layer called IrrigationZone.
The function checks in what polygon in _Irrigation Zones_ the tree point is contained, so as to update that attribute of the tree for future quick access.

I found a function that suited this application:

```
from qgis.core import *
from qgis.gui import *

@qgsfunction(args='auto', group='Custom')
def is_contained_in(layername, column, feature, parent):
    layer = QgsProject.instance().mapLayersByName(layername)[0]
    for feat in layer.getFeatures():
        if feature.geometry().within(feat.geometry()):
            return feat[column]
```

The function works correctly returning the name of the irrigation zone the tree falls within, and it shows correctly in the Preview field of the Field Calculator, when the following expression is used:

is_contained_in ('Irrigation Zones','Label')

However, when I run the Field Calculator on the layer, all the trees receive a NULL irrigation zone.

To debug I tried the following:
`coalesce(is_contained_in ('Irrigation Zones','Label'),'Why Null?')`
and strangely enough all the trees had a 'Why Null?' updated into the IrrigationZone field.

![FieldCalculatorScreenshot](https://user-images.githubusercontent.com/16478283/108544391-0b768900-72ef-11eb-887a-3b73aa12a7f9.png)

When I use the same function as the label to be displayed on the map, it works fine and displays the correct label for each tree. So it seems that the custom function returns NULL only when I click OK to run the update in the Field Calculator.

**QGIS and OS versions**

QGIS version
3.16.0-Hannover
QGIS code revision
43b64b13f3
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
AppendFeaturesToLayer; 
mmqgis; 
plugin_reloader; 
qad; 
qfieldsync; 
Submission; 
VectorBender; 
db_manager; 
MetaSearch; 
processing

**Comment by uclaros** [comment]
Can you test on the latest version? If it still fails, please attach a sample project with sample data.

**Comment by Jimzi** [comment]
Downloading as we speak.
Version: [3.16.3](https://qgis.org/downloads/QGIS-OSGeo4W-3.16.3-1-Setup-x86_64.exe).
Will update when tested.

**Comment by DelazJ** [comment]
> So it seems that the custom function returns NULL only when I click OK to run the update in the Field Calculator.

Maybe an issue with the field size? Left at 0? 
> I found a function that suited this application:

It does not solve this bug but fyi, QGIS has native functions to do that: see example 4 of [overlap_nearest/within](https://docs.qgis.org/3.16/en/docs/user_manual/working_with_vector/functions_list.html#overlay-nearest) or [aggregates functions](https://docs.qgis.org/3.16/en/docs/user_manual/working_with_vector/functions_list.html#aggregates-functions) with spatial filter.

**Comment by Jimzi** [comment]
Hi @DelazJ  

Yes field size is 0.

I created a small sample project for debugging, with only 9 tree points and two irrigation zones and it works fine!

So I figured maybe my project file is corrupt somehow?

I tried creating a new project and added the two layers from the "Original" geopackage with all data, some 994 trees and 13 irrigation zones with default symbology, no filters, just loaded them as is... same problem.

I tried the suggested QGIS native function `overlay_intersects('Irrigation Zones', Label)` same problem returns an empty array when run but in preview it shows and array containing one string item with the correct irrigation zone name.

Only thing I can think of right now is to try exporting the data to new geopackage, possibly also shape files and test if any of those two work... will keep you posted.

**Comment by DelazJ** [comment]
hi
> Yes field size is 0

You mean the field "IrrigationZone' in your "trees" layer had size=0 or do I misunderstand? If size=0, then it's normal it does not work. You should give a size big enough to store your values. Add another large enough field in your "trees" layer and retry, please.
> I tried the suggested QGIS native function overlay_intersects('Irrigation Zones', Label) same problem returns an empty array when run but in preview it shows and array containing one string item with the correct irrigation zone name.

The correct expression is number4: `array_to_string(overlay_intersects('Irrigation Zones', Label))` You can not store data of array type in a string type field, hence the conversion. The preview shows your expression results; it doesn't guarantee it would store it where you ask.

**Comment by Jimzi** [comment]
Nope same problem...

Attached is the new 'trimmed/cleaned' project file with shape files for the two layers in question.
[QGIS Debug SF.zip](https://github.com/qgis/QGIS/files/6018539/QGIS.Debug.SF.zip)

This doesn't work:
`is_contained_in('Irrigation Zones','Label')`

This function worked!
`array_first(overlay_intersects('Irrigation Zones', Label))`
I tried it on the original file and it also worked.

**Comment by Jimzi** [comment]
Hi @DelazJ

I thought field size 0 means as big as needed... anyhow my zone names never exceed 20 or so characters.

> The preview shows your expression results; it doesn't guarantee it would store it where you ask.

I think possibly that's what was happening... although the custom function seemed to return a string...

**Comment by Jimzi** [comment]
Tried` to_string(is_contained_in('Irrigation Zones','Label'))` but it didn't work.
Only when using the native function it worked.

**Comment by Jimzi** [comment]
Nevermind to_string() I guess its only for numbers.

But I'm sure my output is a string so I tried `left(is_contained_in('Irrigation Zones','Label'),10)` to limit to 10 characters, while outputting to a new field (size 20), instead of updating the existing field I had (size 0).
Didn't work :(

**Comment by DelazJ** [comment]
@Jimzi I gave it a shot and it failed to store the result in a plain string field of 20, and of 254. But using the same expression, I can store the values in a virtual field.
Something seems broken with storing custom functions result in a field... but I can't tell more...

**Comment by Jimzi** [comment]
I suspect its the function itself.

I tried a very simple function to test that returns a string always:

`from qgis.core import *
from qgis.gui import *

@qgsfunction(args='auto', group='Custom')
def my_funct(value1, value2, feature, parent):
    return 'String'`

Then I ran the following in Field Calculator and it worked:
` my_funct(1,1)`

'String' was saved in all of them.

**Comment by uclaros** [comment]
@Jimzi You need to declare `usesgeometry=True` in the function decorator if you want to use the feature's geometry inside the function. Without that, `feature.geometry()` is not available so `if feature.geometry().within(feat.geometry()):` is never true.

If you change the decorator to `@qgsfunction(args='auto', group='Custom', usesgeometry=True)` your function will work as you expect and only return null for the trees that are not within a zone.

**Comment by Jimzi** [comment]
Thanks @uclaros, tested as per your recommendation and it works.
I'm unfamiliar with QGIS programming/python and never heard of decorators before, but reading up on them and learning new concepts is refreshing!

I think the fact that the preview showed correct values and then running the Field Calculator didn't produce the results that it showed in preview threw me off into thinking something was wrong, which turned out to be lack of knowledge on my part. Thanks for everyone's help debugging my brain :) Neurons have been rewired and issue fixed! Cheers!

**Comment by DelazJ** [comment]
sorry, reopening. I still think there's some weird behavior.
@uclaros
> Without that, feature.geometry() is not available so if feature.geometry().within(feat.geometry()): is never true.

In that case, how does it come that the preview is always correct in the field calc? AND that you can save the expected correct values in a **virtual** field (actually the values in this vid are not stored in the table but shown in the Identify features results, another bug I think)
![virtfieldusesgeom](https://user-images.githubusercontent.com/7983394/108952929-9eeee780-766a-11eb-9ce5-219f035cdc53.gif)

14e5c6094 on ubuntu 20.04

**Comment by uclaros** [comment]
Yes, I agree on reopening. 
This happens because there is different expression evaluation code in the field calculator (checks for `usegeometry`) than in the preview widget and the identify results (probably does not check for `usegeometry`)

**Comment by chleidersdorff** [comment]
i think i have the same issue but much simpler, i have a layer in a geopackage. If i run a simple formula to create and/or update a string field it simply returns null. but when run in the browser formula bar it works. simple formula is 

```
lpad($ID||'PR_Py',10,0) 
```
Update from Field Calculator:
![image](https://user-images.githubusercontent.com/52182284/132603015-a377d308-75fd-4fc3-951d-af1173ed3bd4.png)

Update from Browser bar:
![image](https://user-images.githubusercontent.com/52182284/132603189-9fa903ed-22ce-4ffa-97d8-eb9913c28c01.png)

**Comment by ArnaudAcoucite** [comment]
Hi,

I am a new user of QGIS GitHub but have been using QGIS for a few years now. Yet, I am new to create custom functions with PyQGIS.

I think I encounter a similar issue but I can't manage to understand where it comes from.

For example, I tried with the simple function factor_area found on here [](https://howtoinqgis.wordpress.com/2017/05/20/how-to-create-custom-functions-in-qgis-using-the-function-editor/), but by adding a line to print the geometry in Python console:

```
@qgsfunction(args='auto', group='Custom')
def factor_area(factor, feature, parent):
    """ This function returns the area of the current geometry multiplied by a user-defined factor. """
    geom_area = feature.geometry().area()
    print(feature.geometry())
    new_area = factor * geom_area
    return new_area
```
Calling the function in the field calculator seems to give correct values in the preview. A geometry is also identified in the Python console.
![Capture d’écran 2021-09-15 164318](https://user-images.githubusercontent.com/87969978/133457170-a834a12d-fe75-4744-9586-ded78934039c.jpg)

But when clicking on OK, the geometry becomes NULL.
![Capture d’écran 2021-09-15 164440](https://user-images.githubusercontent.com/87969978/133457194-1c665541-6eb3-40f0-a6b8-6e7daaac850e.jpg)

I did several tests. Sometimes the function worked but I can't manage to understand what makes the issue occur.

Thank you for your help!

**Comment by nyalldawson** [comment]
You need to set the "usesgeometry=True" argument on qgsfunction

```
@qgsfunction(args='auto', group='Custom', usesgeometry=True)
def factor_area(factor, feature, parent):
    """ This function returns the area of the current geometry multiplied by a user-defined factor. """
    geom_area = feature.geometry().area()
    print(feature.geometry())
    new_area = factor * geom_area
    return new_area
```

From the function editor help:

```
 : param usesgeometry : Set this to True if your function requires access to
                        feature.geometry(). Defaults to False.
```

**Comment by ArnaudAcoucite** [comment]
Hi,

Thank your for your answer. I already tried according to a previous answer and it didn't worked. But now it works! So thanks, I may have made a mistake.

Also I thought it wasn't necessary because the function editor help in my language (French) says that the default value is True:
`: param usesgeometry: Mettre à faux si votre fonction n'utilise pas feature.geometry(). Vrai par défaut.`

**Comment by DelazJ** [comment]
> Also I thought it wasn't necessary because the function editor help in my language (French) says that the default value is True:
: param usesgeometry: Mettre à faux si votre fonction n'utilise pas feature.geometry(). Vrai par défaut.

Translation fixed now. Should be god in next (point)releases
It was true 3 years (https://github.com/qgis/QGIS/commit/e9c7c86aba8f60b9c4236895552de5b633c2c501). Fact is this kind of long text, with weird/complex formatting are hard to handle for translators and the changes are not always obvious. So possible errors while trying to reuse existing translations.

**Comment by ArnaudAcoucite** [comment]
Thank you for the correction!
