### ISSUE TITLE
Dialog boxes opening too small

### ISSUE THREAD

**Issue by Ruthsmith555** [qgis/QGIS#41712]
Hi all,

Has anyone else experienced this issue where dialog boxes open incredibly small and the cells / text are really condensed and overlapping making data input very difficult? I'm able to expand the dialog box but the information within doesn't expand with it. (Image below)
I'm using an Asus Zenbook but believe the problem also occurs with Lenovo Yoga

![Dialog box issue](https://user-images.githubusercontent.com/79276030/108602456-e723b680-7399-11eb-909b-48311931e203.jpg)
.

I'm using QGIS version 3.10.6 but it also happens in the latest version 

Many thanks for your help!

**Comment by gioman** [comment]
@Ruthsmith555 that is a 3rd party plugin, you must report it to the plugin author.
