### ISSUE TITLE
QGIS is unable to find untwine executable

### ISSUE THREAD

**Issue by kikislater** [qgis/QGIS#41711]
Checklist before submitting

- [x] Search through existing issue reports and gis.stackexchange.com to check whether the issue already exists
- [x] Test with a [clean new user profile](https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html?highlight=profile#working-with-user-profiles).

**Describe the bug**
Qgis 3.18.0 is unable to find untwine in 3D view point cloud

**How to Reproduce**
Build and install QGiS (trough PKGBUILD archlinux system but doesn't matter, same behaviour)

cmake options (build fail with qwtpolar but it's another issue) : 
```
  mkdir build
  cd build
  cmake -G Ninja ../qgis-3.18.0 \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DWITH_3D=TRUE \
    -DWITH_SERVER=TRUE \
    -DWITH_CUSTOM_WIDGETS=TRUE \
    -DBINDINGS_GLOBAL_INSTALL=TRUE \
    -DQGIS_MANUAL_SUBDIR=share/man \
    -DWITH_QWTPOLAR=FALSE \
    -DWITH_INTERNAL_QWTPOLAR=FALSE \
    -DWITH_PDAL=TRUE \
    -DWITH_EPT=TRUE \
    -DWITH_QSPATIALITE=TRUE
  cmake --build .
```

Verify install : 
```
$ pacman -Q qgis
qgis 3.18.0-1
$ pacman -Qo /usr/lib/qgis/untwine 
/usr/lib/qgis/untwine is owned by qgis 3.18.0-1
```
1. Load a LAZ point cloud through qgis explorer 
(no entwine entry visible from add layer menu, don't know if it's a standard behaviour but different from 3.18 changelog)
2. Point cloud info is ok, point cloud feature identification ok 
3. Run new 3D map view
4. Point loud is flat, no error fro log or terminal
5. ***Workaround*** : Closing qgis making an untwine symlink to executable PATH like : `ln -s /usr/lib/qgis/untwine /usr/local/bin/untwine`
6. Reload QGIS, reload point cloud, new 3D view is now displaying point cloud in 3D ! 

**QGIS and OS versions**

Version de QGIS | 3.18.0-Zürich | Branche de code de QGIS | Release 3.18
-- | -- | -- | --
Compilé avec Qt | 5.15.2 | Utilisant Qt | 5.15.2
Compilé avec GDAL/OGR | 3.0.4 | Utilisé avec GDAL/OGR | 3.0.4
Compilé avec GEOS | 3.8.1-CAPI-1.13.3 | Utilisé avec GEOS | 3.8.1-CAPI-1.13.3
Compilé avec SQLite | 3.34.1 | Fonctionne avec SQLite | 3.34.1
Compiled against PDAL | 2.2.0 | Running against PDAL | 2.2.0 (git-version: Release)
Version du client PostgreSQL | 13.1 | Version de SpatiaLite | 4.3.0a
Version de QWT | 6.1.6 | Version de QScintilla2 | 2.11.6
Compilé avec PROJ | 6.3.2 | Fonctionne avec PROJ | Rel. 6.3.2, May 1st, 2020
Version de l'OS | Manjaro Linux
Extensions Python actives | quick_map_services; slyr_community; SemiAutomaticClassificationPlugin; lizmap; Generalizer3; pdaltools; plugin_reloader; flight_planner; MagicWand-master; qgis_resource_sharing; ale; VoGisProfilTool; qconsolidate3; GroupStats; profiletool; SpreadsheetLayers; pluginbuilder3; OSMDownloader; DataPlotly; QGISSortAndNumber-master; LDMP; processing; MetaSearch; db_manager

**Comment by gioman** [comment]
I'm seeing the same on Ubuntu with QGIS installed using qgis.org's repos.

**Comment by palmerj** [comment]
Also see #41656

**Comment by kikislater** [comment]
adding /usr/lib/qgis/ to path is more convenient than a symlink

```
export PATH=$PATH:/usr/lib/qgis
```

But there are libraries under this directory as well. May be, it's worth guiding user or documentation to a proper usage

**Comment by wonder-sk** [comment]
Is this still a valid bug? As far as I know, indexing LAS/LAZ files (using untwine) works on all supported platforms (windows / linux / mac).

**Comment by kikislater** [comment]
It's still valid for me but at this time with Qgis 3.22.2 and pdal 2.3.0, I'm not able to display point cloud ...

**Comment by gioman** [comment]
> It's still valid for me but at this time with Qgis 3.22.2 and pdal 2.3.0, I'm not able to display point cloud ...

@kikislater can you exclude a local issue by testing on a different machine?

**Comment by kikislater** [comment]
yes I have tested on different machine, I will retest in the following days ....

**Comment by kikislater** [comment]
Ok it works with 3.22.2 without symlink...
