### ISSUE TITLE
Pointcloud las. file QGIS crash 

### ISSUE THREAD

**Issue by Ecoystem** [qgis/QGIS#41727]
[

**Describe the bug**

**How to Reproduce**

4. See error -->

**QGIS and OS versions**

**Additional context**

**Comment by Ecoystem** [comment]
[Point cloud crash.txt](https://github.com/qgis/QGIS/files/6019421/Point.cloud.crash.txt)

**Comment by jonnyforestGIS** [comment]
@Ecoystem can you please detail more about this crash. What are the steps to reproduce?

**Comment by gioman** [comment]
@Ecoystem please edit the description adding the requested infos.

**Comment by gioman** [comment]
Closing for lack of feedback.
