### ISSUE TITLE
Raster Calculator: Could not create destination file.

### ISSUE THREAD

**Issue by hennyfer** [qgis/QGIS#41725]
I'm trying to divide values in a layer, and I've set the output layer to be saved to my desktop. After I press "Ok", it says "Raster Calculator: Could not create destination file." What do I do about this?

**Comment by gioman** [comment]
@hennyfer if is a question this must be asked on the users/developers mailing lists. If is a bug report then please use the correct page https://github.com/qgis/QGIS/issues/new?assignees=&labels=Bug&template=10_bug_report.md&title= filling with all the requested infos. Thanks!
