### ISSUE TITLE
[Point Cloud] Open Layers properties crash QGIS with ept.json file

### ISSUE THREAD

**Issue by jonnyforestGIS** [qgis/QGIS#41722]
- [x] Search through existing issue reports and gis.stackexchange.com to check whether the issue already exists
- [x] Test with a [clean new user profile](https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html?highlight=profile#working-with-user-profiles).

**Describe the bug**
When Open a Point Cloud file (ept.json) make crash QGIS master if we try to open the layer properties from the point cloud layer.

**How to Reproduce**

1. Add an ept.json file from a Point Cloud
2. Set the coordinate system from the layer
3. Set the same coordinate system to the project
2. Click on Layer properties
3. QGIS crash immediately.

Animated gif:
![crash](https://user-images.githubusercontent.com/4480601/108634900-de9fae80-7473-11eb-8f18-cc2f50a7ea6d.gif)

**QGIS and OS versions**

QGIS   version | 3.19.0-Master | QGIS code revision | 03eaf9f29
-- | -- | -- | --
Compiled   against Qt | 5.15.2 | Running against Qt | 5.15.2
Compiled   against GDAL/OGR | 3.2.1 | Running against GDAL/OGR | 3.2.1
Compiled   against GEOS | 3.9.1-CAPI-1.14.2 | Running against GEOS | 3.9.1-CAPI-1.14.2
Compiled   against SQLite | 3.33.0 | Running against SQLite | 3.33.0
Compiled   against PDAL | 2.2.0 | Running against PDAL | 2.2.0 (git-version: 38aa11)
PostgreSQL   Client Version | 13.0 | SpatiaLite Version | 5.0.1-rc1
QWT   Version | 6.1.3 | QScintilla2 Version | 2.11.5
Compiled   against PROJ | 7.2.1 | Running against PROJ | Rel. 7.2.1, January 1st, 2021
OS Version | Windows 10 Version 2009 | This copy of QGIS   writes debugging output.
Active   python plugins | processing

**Additional information:**

Logs from QGIS crash:
[qgis-crash-info-329592.txt](https://github.com/qgis/QGIS/files/6018227/qgis-crash-info-329592.txt)

**Comment by roya0045** [comment]
No stack trace?

**Comment by jonnyforestGIS** [comment]
@roya0045 do you want the crash file generated?

**Comment by roya0045** [comment]
I assume that it may be helpful if the issue can't be replicated on linux

**Comment by jonnyforestGIS** [comment]
[report.txt](https://github.com/qgis/QGIS/files/6018375/report.txt)
[stack.txt](https://github.com/qgis/QGIS/files/6018376/stack.txt)

**Comment by PedroVenancio** [comment]
Same behaviour here, with a .las file previously indexed:

```
Crash ID: 916c3321b94d5b47555b8ad258c6d52dc9e2599e

Stack Trace

QgsMarkerSymbolLayer::setOffset :
QgsMarkerSymbolLayer::setOffset :
QgisApp::styleSheetBuilder :
QgisApp::styleSheetBuilder :
QgisApp::styleSheetBuilder :
QgisApp::styleSheetBuilder :
QgisApp::styleSheetBuilder :
QgisApp::styleSheetBuilder :
QgisApp::styleSheetBuilder :
QgisApp::styleSheetBuilder :
QObject::qt_static_metacall :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsMarkerSymbolLayer::setOffset :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsMarkerSymbolLayer::setOffset :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QMenu::exec :
QMenu::exec :
QgsModelViewMouseHandles::qt_metacall :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsMarkerSymbolLayer::setOffset :
QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsMarkerSymbolLayer::setOffset :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
QgisApp::styleSheetBuilder :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.19.0-Master
QGIS code revision: 61b6cc21e
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.2.1
Running against GDAL: 3.2.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

```

What I see is that when I load the .las file for the first time, QGIS cashes it creating the ept and I can open Properties.

If I remove and load the .las file again, it already uses the cache previously created and if I try to open the Properties window, QGIS crashes.

**Comment by Saijin-Naib** [comment]
## User Feedback

Loaded an EPT from OpenDroneMap (sucessfully).
Right-click EPT layer in Layer tree, choose Properties.
Hang then crash.

## Report Details

**Crash ID**: [57005e6dcabdd21d23c36649bc4a7565afa6bf4f](https://github.com/qgis/QGIS/search?q=57005e6dcabdd21d23c36649bc4a7565afa6bf4f&type=Issues)


**Stack Trace**
<pre>
QgsPointCloudLayer::pointCount :
Qgs3DMapCanvasDockWidget::updateFpsCount :
Qgs3DMapCanvasDockWidget::updateFpsCount :
QgsDecorationGridDialog::updateSymbolButtons :
QgisApp::showLayerProperties :
QgisApp::layerProperties :
QObject::qt_static_metacall :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QMenu::exec :
QMenu::exec :
QgsLayerTreeView::contextMenuEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>


**QGIS Info**
QGIS Version: 3.18.0-Z�rich
QGIS code revision: bdef9fb3
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.2.1
Running against GDAL: 3.2.1



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.21318

**Comment by bellanz80** [comment]
I confirm all, on POP_OS 20.10 QGIS 3.18
