### ISSUE TITLE
crashed when exporting layer to csv

### ISSUE THREAD

**Issue by billmenger** [qgis/QGIS#41720]
**Describe the bug**
I had loaded a layer containing about 1.4MM records of all the buildings in Harris County, TX.  Each record contains about 480 bytes of attribute information.  I attempted to export the layer to csv.  It unloaded 908441 records (about 435,550KB) before crashing.   I am unable to reproduce with a sample dataset because it seems to be the size that is the issue.  The export looks good up to the point where it crashed.
**How to Reproduce**
1. Create new project
2. load street-maps
3. load a large dataset layer
4. attempt to export the layer to csv
**Additional context**
## Report Details

**Crash ID**: [5cda54aec7f5af6b8dde7eef3753ebd1ae802678](https://github.com/qgis/QGIS/search?q=5cda54aec7f5af6b8dde7eef3753ebd1ae802678&type=Issues)

**Stack Trace**
<pre>
memcpy memcpy.asm:530
VSICreateCachedFile :
OGRPGCommonAppendFieldValue :
OGRPGCommonAppendFieldValue :
OGRPGCommonAppendFieldValue :
QgsOgrFeatureIterator::fetchFeature qgsogrfeatureiterator.cpp:387
QgsAbstractFeatureIterator::nextFeature qgsfeatureiterator.cpp:63
QgsVectorLayerFeatureIterator::fetchFeature qgsvectorlayerfeatureiterator.cpp:442
QgsAbstractFeatureIterator::nextFeature qgsfeatureiterator.cpp:63
QgsVectorFileWriter::writeAsVectorFormatV2 qgsvectorfilewriter.cpp:3087
QgsVectorFileWriterTask::run qgsvectorfilewritertask.cpp:61
QgsTask::start qgstaskmanager.cpp:83
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.16.3-Hannover
QGIS code revision: 94ac9f21b8
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

**Comment by gioman** [comment]
@billmenger please try with a new QGIS profile, no 3rd party plugins installed. If the problem persist please attach/link your data.

**Comment by billmenger** [comment]
Turned off plugins, selected only the important attributes, and successfully downloaded all records.  Attempting again with plugins off to download full set of attributes, but it looks like it will take a day to complete.  Thank you for the suggestions.

Bill

**Comment by gioman** [comment]
> Turned off plugins, selected only the important attributes, and successfully downloaded all records. Attempting again with plugins off to download full set of attributes, but it looks like it will take a day to complete. Thank you for the suggestions.

@billmenger closing?

**Comment by billmenger** [comment]
It would be best for me to allow the process to complete before closing.  This may uncover a memory leak or other problem, so I'll leave it open until I see a successful export of the full attributes from this layer.

**Comment by gioman** [comment]
> It would be best for me to allow the process to complete before closing. This may uncover a memory leak or other problem, so I'll leave it open until I see a successful export of the full attributes from this layer.

@billmenger does it works with no 3rd party plugins on a new profile?

**Comment by billmenger** [comment]
It would be best for me to allow the process to complete before closing.  This may uncover a memory leak or other problem, so I'll leave it open until I see a successful export of the full attributes from this layer.

**Comment by billmenger** [comment]
After closing and reopening QGIS, and redirecting the output to go to a local disk and not one on mounted from a samba server, the export worked flawlessly.
