### ISSUE TITLE
QGIS crashes when editing Processing script

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#41737]
Found this on master while testing this other ticket

https://github.com/qgis/QGIS/issues/41719

basically a Processing script can be edited without issues, but if the editor dialog is open and the script run, then a subsequent edit causes an instant crash.

**Comment by gioman** [comment]
QGIS master on Ubuntu 20.04.

**Comment by pblottiere** [comment]
I tried to reproduce the issue on ArchLinux but without success:

1. `Create new script from template` in processing toolbox
2.  add a `time.sleep(5)` in `processAlgorithm` method and click on the `Run Script` button in the editor 
3. edit the script while the process is running

=> no crash

**Comment by gioman** [comment]
Cannot replicate anymore too.
