### ISSUE TITLE
Fails to build with PROJ 8.0.0

### ISSUE THREAD

**Issue by sebastic** [qgis/QGIS#41735]
PROJ 8.0.0 has removed `proj_api.h`, this causes `cmake/FindProj.cmake` to fail:
```
//Path to a file.
PROJ_INCLUDE_DIR:PATH=PROJ_INCLUDE_DIR-NOTFOUND

//Path to a library.
PROJ_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libproj.so
```

It should look for `proj.h` when `proj_api.h` is not found.

**Comment by roya0045** [comment]
Is qgis even ready to use proj8?

**Comment by sebastic** [comment]
It's not much different from PROJ 6 & 7 which it already supports.
