### ISSUE TITLE
Raster symbology: colours ordering issue in "Paletted/Unique values" for float rasters

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/QGIS#41747]
**Describe the bug**

With a float 32/64 GeoTIFF raster layer, setting the layer symbology to "Paletted/Unique values", selecting a colour ramp and then clicking on the "Classify" button, the order of the colours is incorrect and does not follow the colour ramp, while the order of the values is correct.

![image](https://user-images.githubusercontent.com/16253859/108787975-3ecb4900-7577-11eb-882b-6b5e5b6892b8.png) ![image](https://user-images.githubusercontent.com/16253859/108788049-69b59d00-7577-11eb-99fb-9d24e9a83782.png)

![Video_2021-02-22_220342](https://user-images.githubusercontent.com/16253859/108788090-7d610380-7577-11eb-93dc-789be4e6b0a3.gif)

The issue doesn't occur with a Byte or Int16 GeoTIFF raster layer.

**How to Reproduce**

1. Add float32.tif (in [float32.zip](https://github.com/qgis/QGIS/files/6026141/float32.zip)) to a project
2. Change the raster symbology render type to "Paletted/Unique values"
3. Select a color ramp (e.g. "Blues")
4. Click on the "Classify" button

**QGIS and OS versions**

QGIS 3.16.3
QGIS 3.19-master

on Windows 7 SP1 64 bit

**Additional context**

The "Raster paletted/unique float support" was introduced with PR https://github.com/qgis/QGIS/pull/39088.

Maybe related to https://github.com/qgis/QGIS/issues/39685, https://github.com/qgis/QGIS/issues/39757, https://github.com/qgis/QGIS/pull/39778

**Comment by elpaso** [comment]
@agiudiceandrea language settings?

**Comment by agiudiceandrea** [comment]
@elpaso tested on Windows (Italian locale).
QGIS settings:
- User interface: American English
- Locale: English UnitedStates (en_US)

**Comment by elpaso** [comment]
@agiudiceandrea thank, it was just to rule out the  `,`/`.` decimal separator issue.
