### ISSUE TITLE
Decimal separator not recognized for layer resolution when Locale is set to fr_FR

### ISSUE THREAD

**Issue by Scolopax** [qgis/QGIS#41766]
**Describe the bug**

Local decimal separator "," is not correctly recognized in the "Save Raster Layer as..." interface for layer resolution parameter.

**How to Reproduce**

With QGIS options System Locale set as 'French France (fr_FR)' for numbers, date and currency formats:
1. Load a raster
2. Right click on the layer > "Export" > "Save as"
3. Set "Output mode" to "Raw data", "Format" to "GeoTIFF", "Create VRT" unchecked
4. Set "Extent" to "Map Canvas Extent"
4. Set horizontal and vertical resolution to "0,5" (point keyboard entry is not available)
5. See error --> "Cannot write raster. Error code: data source creation
Cannot create new dataset  C:\Users\XX\Desktop\test.tif:
Attempt to create 0x0 dataset is illegal,sizes must be larger than zero."

This is particularly a problem when trying to export raster data from a WMS source since resolution cannot be populated with "Layer Resolution" button. A possible workaround consists of defining resolution with column and rows and then go back to the Horizontal/Vertical resolution option and modify parameters with automaticaly inserted decimal separator. Also, scientific notation can be used (e.g. "5e-1") but it is not very intuitive...

When trying with "Create VRT" checked, no error message occurs but the .vrt is "empty".

**QGIS and OS versions**

QGIS 3.16 (same behavior with previous versions)
Windows 10

**Comment by agiudiceandrea** [comment]
It seems to me a duplicate of https://github.com/qgis/QGIS/issues/41284 already fixed with https://github.com/qgis/QGIS/pull/41316.
The fix is currently available only in QGIS 3.18.0 and QGIS 3.19-master. The first QGIS 3.16 fixed version will be QGIS 3.16.5 (https://github.com/qgis/QGIS/pull/41054).

**Comment by Scolopax** [comment]
Indeed. I didn't search correctly within closed issues. Thank you for the fix !
