### ISSUE TITLE
Classifying in Labels: CrashID: 707379a85ce135f031cdee7966b34db224a65e87

### ISSUE THREAD

**Issue by rougerouter** [qgis/QGIS#41767]
**Describe the bug**

**How to Reproduce**

4. See error -->

**QGIS and OS versions**

3.1.6.3
**Additional context**

## User Feedback

I was classify landuse from the training manual

## Report Details

**Crash ID**: [707379a85ce135f031cdee7966b34db224a65e87](https://github.com/qgis/QGIS/search?q=707379a85ce135f031cdee7966b34db224a65e87&type=Issues)

**Stack Trace**
<pre>
QgsGraduatedSymbolRenderer::convertFromRenderer qgsgraduatedsymbolrenderer.cpp:1253
QgsGraduatedSymbolRendererWidget::QgsGraduatedSymbolRendererWidget qgsgraduatedsymbolrendererwidget.cpp:456
QgsGraduatedSymbolRendererWidget::create qgsgraduatedsymbolrendererwidget.cpp:412
QgsRendererPropertiesDialog::rendererChanged qgsrendererpropertiesdialog.cpp:250
QMetaObject::activate :
QWidgetLineControl::`default constructor closure' :
QComboBox::setCurrentIndex :
QWidgetLineControl::`default constructor closure' :
QMetaObject::activate :
QComboBoxPrivateContainer::eventFilter :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
QgisApp::showLayerProperties qgisapp.cpp:16004
QgisApp::layerProperties qgisapp.cpp:9166
QgisApp::layerTreeViewDoubleClicked qgisapp.cpp:658
QMetaObject::activate :
QAbstractItemView::doubleClicked :
QTreeView::mouseDoubleClickEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1637
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.16.3-Hannover
QGIS code revision: 94ac9f21b8
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

**Comment by gioman** [comment]
> **Describe the bug**
> 
> **How to Reproduce**
> 
>     1. Go to '...'
> 
>     2. Click on '....'
> 
>     3. Scroll down to '....'
> 
>     4. See error -->

@rougerouter please add the above requested info.

also please try with a new QGIS profile, no 3rd party plugins.

**Comment by gioman** [comment]
Closing for lack of feedback.
