### ISSUE TITLE
No feedback when trying to add a point cloud layer if compiled without pdal

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#41764]
**Describe the bug**
I had built master without enabling PDAL. When trying to add a point cloud layer, nothing happened.

I guess the option to load such layer should depend on the support for it being compiled in?

**How to Reproduce**
1. Have QGIS without PDAL
2. Add a point cloud layer
3. Nothing is added to the canvas, no error appears

**QGIS and OS versions**
QGIS version | 3.19.0-Master
QGIS code revision | 8a9ea53d816

**Comment by alburen** [comment]
The same here.
I´ve just downloaded from https://qgis.org/downloads/QGIS-OSGeo4W-3.18.0-1-Setup-x86_64.exe and it seems to have been compiled without PDAL.

Also, if I drag a .las or .laz file to QGIS it doesn´t make anything. And if I try to open from the menu as a point cloud file QGIS says that is not a recognized format ("PNOA_2012.laz no es un origen de datos válido o reconocido").
Also, in the list of compatible point cloud formats only appears the EPT.JSON format.

**About QGIS version:**

Versión de QGIS
3.18.0-Zürich
Revisión del código de QGIS
bdef9fb328
Compilado contra Qt
5.11.2
Ejecutándose contra Qt
5.11.2
Compilado contra GDAL/OGR
3.1.4
Ejecutándose contra GDAL/OGR
3.1.4
Compilado contra GEOS
3.8.1-CAPI-1.13.3
Ejecutándose contra GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
Versión del cliente PostgreSQL
11.5
Versión de SpatiaLite
4.3.0
Versión de QWT
6.1.3
Versión de QScintilla2
2.10.8
Compilado contra PROJ
6.3.2
Ejecutándose contra PROJ
Rel. 6.3.2, May 1st, 2020
Versión del SO
Windows 10 (10.0)

**Comment by wonder-sk** [comment]
Unfortunately currently the PDAL provider is not included in the QGIS installers for windows:
https://lists.osgeo.org/pipermail/qgis-user/2021-February/048137.html

Hopefully it will be included sometime soon...

For the time being, one needs to use NEW osgeo4w installer as described here to be able to use LAS/LAZ files:
https://www.lutraconsulting.co.uk/blog/2021/02/15/qgis-point-cloud-windows/
WARNING: if you already use osgeo4w, make sure to use a different installation path for the NEW osgeo4w installer.

**Comment by wonder-sk** [comment]
Fixed by Nyall in #41927 (master) #41938 (3.18)

**Comment by kannes** [comment]
Thank you, @nyalldawson!
