### ISSUE TITLE
Georeferencer hangs on start georef (3.18 and master)

### ISSUE THREAD

**Issue by Houska1** [qgis/QGIS#41770]
Georeferencer hangs after putting up Progress indicator window when told to start georeferencing.
QGIS unresponsive, need to kill process.

Happens in 3.18.0-1 release version (OSGeo4Win) and 3.19 master. Works OK (phew!) on 3.16.4 LTR.
New clean user profile.

Screenshot below.
Example tiff and .points file causing the problem available [in my DropBox](https://www.dropbox.com/s/pwc1l1yhn8fc3io/georeferencer_crash.zip?dl=0) (32 Mb).
I'm using thin plate spline, EPSG:2951 (but also tried 3857), output tiff compress=DEFLATE.

Have found issues posted here regarding *loading* a raster in georeferencer. This is different: not at load, this is after telling georef to go and warp the raster.

![Screen_Capture_-_23_Feb__7_34_am](https://user-images.githubusercontent.com/48919900/108853542-dac77580-75b4-11eb-847f-665344246065.png)

**Comment by gioman** [comment]
@Houska1on master/linux worked fine but the progress bar that on older releases worked ok now is just a frozen dialog. @roya0045 was that you that recently worked on the georef? or it was @nyalldawson ? maybe related to the latest changes?

**Comment by roya0045** [comment]
I'm curious to know if this may be related to the reporting now that multicore is enabled. @nyalldawson Do you think that may be related? It might also be my changes but I'm not too sure how it might affect that part of the process. I'll take a look if its not fixed when I test vector georeferencing.

**Comment by pigreco** [comment]
I confirm, it does not work in 3.18 and in dev

## OSGeo4W64 win 10

**Comment by Korto19** [comment]
I confirm, it does not work in 3.18 and in dev

OSGeo4W64 win 7

**Comment by roya0045** [comment]
Is the crash on windows only?

**Comment by gioman** [comment]
> Is the crash on windows only?

@roya0045 I did not replied the crash on Ubuntu. But the progress bar/dialog is in worst shape than before, also on Linux.

**Comment by nirvn** [comment]
It's 100% the enabling of multithread that led to this issue, I spotted it during the dev cycle after the PR was merged. On my machine, there's no crash but the UI feedback is absent.

**Comment by roya0045** [comment]
@nirvn Thanks for confirming, this what my guess after seeng the feedback code and finding it too vulnerable. I'm glad the issue was identified. Should the dialog be removed and just have an processing task without progressiong just to indicate activity?

**Comment by Houska1** [comment]
@roya0045 and @nirvn: Great the quarry has been spotted! Just noting that -- at least in my case, under Windows -- it sat there with the circle spinning, no progress being shown, not interruptible, for far, far longer than the same georef took when I then re-did it in 3.16.4.  So at least on Windows, it is more than a nonupdating progress bar.

**Comment by Vroxigar** [comment]
Same for me. Any workaround?

**Comment by uclaros** [comment]
> It's 100% the enabling of multithread that led to this issue, I spotted it during the dev cycle after the PR was merged. On my machine, there's no crash but the UI feedback is absent.

@nirvn This change was smelly from the beginning. We literally enabled a line that was commented out in production in order to gain some theoretical IO speed without conducting any measurable testing. 



> Should the dialog be removed and just have an processing task without progressiong just to indicate activity?

I think we should revert until it is properly handled. Progress feedback is absolutely necessary to distinguish that work is indeed being done for big georeferences.

We should also properly benchmark to see what the actual gain is, if any.

**Comment by gioman** [comment]
> I think we should revert until it is properly handled

@uclaros yes please

**Comment by roya0045** [comment]
PR is up, would need someone to validate if this fixes it or if more multithread should be disabled (I doubt it as most were merged after 3.18, but checking would be nice).

**Comment by gioman** [comment]
> PR is up, would need someone to validate if this fixes it or if more multithread should be disabled (I doubt it as most were merged after 3.18, but checking would be nice).

@roya0045 I compiled your branch on Linux and the progress bar is back. I can't say if the crash is gone on Windows as I can't compile on Windows.

**Comment by roya0045** [comment]
@gioman should be fine enough, thank you for takin the time to do this Gio!

**Comment by antoniolocandro** [comment]
Still experiencing this issue updated minutes ago using the new OSGEO4W win10, QGIS LTR works OK

I exported GCP points and loaded into QGIS LTR and noticed a phantom 0,0 which I did not add was included maybe this is causing something in QGIS-dev and QGIS-Zurich

Using DEV
![image](https://user-images.githubusercontent.com/4627073/109225581-131cae80-7783-11eb-9b81-b2bed44884fa.png)

Using LTR
![image](https://user-images.githubusercontent.com/4627073/109225561-0a2bdd00-7783-11eb-97c2-b48b596fc6ba.png)

gcp points & test file (17MB)
[MH_AD-2.MHLM ARC.zip](https://github.com/qgis/QGIS/files/6045990/MH_AD-2.MHLM.ARC.zip)

**Comment by roya0045** [comment]
@antoniolocandro The point is cause by the new line in the point data to add crs, that is not related to the issue, point data files are not retrocompatible. I'm not even sure if the version on osgeo has the fix yet. Can you provide information regarding the first version.

**Comment by pigreco** [comment]
I want to point out that currently the current 3.18 release available for download does NOT work the georef. 3.18.1 should be made available immediately

**Comment by gioman** [comment]
> I want to point out that currently the current 3.18 release available for download does NOT work the georef. 3.18.1 should be made available immediately

@pigreco you must wait a build that contains https://github.com/qgis/QGIS/pull/41789 to test if the fix works or not.

**Comment by asioleh** [comment]
Hi, I got this same problem of Georeferencer hanging with the Progress Indicator and QGIS unresponsive then, but I use Mac OS Catalina. It is QGIS 3.18
Any idea why?

**Comment by mc-geo-rs** [comment]
I experienced this issue on Windows 10 using QGIS 3.22.0, disabling the SemiAutomaticClassificationPlugin (SACP/SCP) plugin and restarting QGIS fixed the issue. Posting so others like me who came from Google will know of the temporary fix.

**Comment by gioman** [comment]
> will know of the temporary fix.

@mc-geo-rs is not a temp fix. It is up to SCP to fix the problem it causes.

**Comment by Houska1** [comment]
@mc-geo-rs, good to note here for those who are currently experiencing this. 
However, for clarity noting that the bug I posted in Feb 2021 was solved in 3.18.1. 
The current (Feb/Mar 2022) bug is separate, and indeed seems to affect those using SCP.

@gioman, I think @mc-geo-rs just means disabling SCP is a temporary fix available to users today to be able to use Georeferencer, irrespective of who needs to actually solve the underlying issue. It does make me wonder if QGIS (core) should maintain a list of known bugs/issues with plugins that affect the ecosystem more broadly (i.e. not just affecting that plugin's internal operations). It's not this project's responsibility to fix them, of course, but it would reduce users' pain and reduce perception of QGIS instability to have a list to cross-check against.  Of course, yet more work....

**Comment by cavrinceanu** [comment]
@mc-geo-rs other happy users thank you. I can report the same issue on QGIS 3.24.1. 
@Houska1  - I honestly spent 2 days before finding this thread, wrapping my head of why is it not working. Wouldn't cross my mind in a million years it is SCP causing it. I presume a QGIS bug  log for plugins would be handy.

**Comment by sboillat** [comment]
> I experienced this issue on Windows 10 using QGIS 3.22.0, disabling the SemiAutomaticClassificationPlugin (SACP/SCP) plugin and restarting QGIS fixed the issue. Posting so others like me who came from Google will know of the temporary fix.

wow this saved me, after hours of searching what was causing this bug. .... thank you so much
