### ISSUE TITLE
GRASS plugin init error on macOS

### ISSUE THREAD

**Issue by agorton-mcclatchy** [qgis/QGIS#41782]
I have a fresh install of QGIS on my machine after trying to diagnose this error. I've erased all of the directories containing configuration information, support libraries, etc. 

When I start QGIS and attempt to enable the Grass plugin, the following error occurs:

`WARNING    GRASS init error : Problem in GRASS initialization, GRASS provider and plugin will not work : Module built against version 2021-02-10T17:13:06+00:00 but trying to use version 2021-02-10T17:08:53+00:00. You need to rebuild GRASS GIS or untangle multiple installations.`

**To recreate:** 
1) Download and install QGIS 3.16.4-Hannover for MacOS. 
2) Start QGIS
3) Enable Grass 7 plugin

**Additional information:**
QGIS version: 3.16.4-Hannover
QGIS code revision: cdb515a206
Compiled against Qt: 5.14.2
Running against Qt: 5.14.2
Compiled against GDAL/OGR: 3.2.1
Running against GDAL/OGR: 3.2.1
Compiled against GEOS: 3.9.1-CAPI-1.14.2
Running against GEOS: 3.9.1-CAPI-1.14.2
Compiled against SQLite: 3.31.1 | 
Running against SQLite: 3.31.1
PostgreSQL Client Version: 12.3 | 
SpatiaLite Version: 4.3.0a
QWT Version: 6.1.4 
QScintilla2 Version: 2.11.4
Compiled against PROJ: 6.3.2
Running against PROJ: Rel. 6.3.2, May 1st, 2020
OS Version: macOS 10.16
Active python plugins: processing; db_manager; MetaSearch

**Comment by gioman** [comment]
Same on 3.18.0 on Catalina, not sure if there is any relation with other macOS/GRASS plugin issues

https://github.com/qgis/QGIS/issues?q=is%3Aopen+is%3Aissue+label%3AMacOS+label%3AGRASS

**Comment by nevw** [comment]
Same on 3.18.0-Zürich on Big Sur 11.2.1
"GRASS init error: Problem in GRASS initialization, GRASS provider and plugin will not work : Module built against version 2021-02-10T17:13:06+00:00 but trying to use version 2021-02-10T17:08:53+00:00. You need to rebuild GRASS GIS or untangle multiple installations."

**Comment by caesar** [comment]
Same error on Big Sur after upgrading to QGIS 3.18.

**Comment by gioman** [comment]
FYI the GRASS plugin is largely unmaintained, if you need GRASS tools better use the Processing toolbox.

**Comment by PeterPetrik** [comment]
So the processing toolbox Grass is working, right?

**Comment by gioman** [comment]
> So the processing toolbox Grass is working, right?

@PeterPetrik this issue is about the QGIS/GRASS plugin, not the Processing toolbox (where GRASS support is implemented in a completely different way).

**Comment by gioman** [comment]
> So the processing toolbox Grass is working, right?

@PeterPetrik yes, is working (well it did the last time I checked that wasn't long ago).

**Comment by jef-n** [comment]
not sure if the grass dylibs carry the version numbers - on windows they do - hence you can only work with DLLs from the same minor release - which hopefully doesn't break ABI - hence I disabled that check in GRASS in (new) OSGeo4W (https://github.com/jef-n/OSGeo4W/blob/master/src/grass/osgeo4w/patch#L50)

**Comment by caesar** [comment]
> FYI the GRASS plugin is largely unmaintained, if you need GRASS tools better use the Processing toolbox.

Isn't the GRASS plugin a core plugin?

**Comment by gioman** [comment]
> Isn't the GRASS plugin a core plugin?

@caesar it is, and as in some other cases this part of QGIS has gone unmaintained. This happened mainly because most of the users that need a GRASS tool an use them from the QGIS/Processing toolbox.

**Comment by caesar** [comment]
Got it, cheers.
I don't really use Grass myself actually but just came looking for the error after I upgraded, in case it affected other QGIS functionality.
For now I'll just disable the GRASS plugin.

**Comment by news24lor** [comment]
I confirm the bug. In the old QGIS 3.16.3, Grass works

**Comment by christro** [comment]
If I am opening the GRASS Tools, the panel is grayed out and and it is not possible to close the panel.

![Screenshot 2021-03-17 at 13 02 07](https://user-images.githubusercontent.com/8968680/111464406-06a3ca00-8721-11eb-9f08-c873df741d1f.png)

No problem, I go back to 3.16.3

**Comment by christro** [comment]
If you need for the future people for user tests on Mac OS I could take some tasks

**Comment by christro** [comment]
I have the same issue with 3.16.6. Do you plan to fix this.

**Comment by gioman** [comment]
> Do you plan to fix this.

@christro the GRASS plugin is unfortunately unmaintained, for the foreseeable future better use GRASS from the Processing toolbox.

**Comment by christro** [comment]
@gioman thank you very much for your fast answer. Is the Grass Plugin unmaintained also for Linux and Windows or only for the Mac.

**Comment by PeterPetrik** [comment]
<img width="569" alt="Screenshot 2021-06-14 at 17 14 42" src="https://user-images.githubusercontent.com/804608/121916009-0b821500-cd34-11eb-8a87-9f98ba9cccc3.png">

works with the latest nightlies, can you please recheck with for example this one? 

https://qgis.org/downloads/macos/nightly/qgis_nightly_master_20210613_123645.dmg

**Comment by christro** [comment]
Thank you very much. I have installed the nightly build. The plugin can be loaded and it is possible to open a mapset and add vector files. If I am adding a raster file, I get the following error message:

```
2021-06-15T11:30:28     CRITICAL    Invalid Layer : GRASS provider Cannot get projection
             Cannot run module
             command: /Applications/QGIS-Dev.app/Contents/MacOS/lib/qgis/grass/modules/qgis.g.info info=proj
             stdout: 
             stderr: dyld: Library not loaded: @rpath/libgrass_gis.7.8.dylib
              Referenced from: /Applications/QGIS-Dev.app/Contents/MacOS/lib/qgis/grass/modules/qgis.g.info7
              Reason: image not found
             
             GRASS provider Cannot get raster extent : Cannot run module
             command: /Applications/QGIS-Dev.app/Contents/MacOS/lib/qgis/grass/modules/qgis.g.info info=size rast=landuse@PERMANENT
             stdout: 
             stderr: dyld: Library not loaded: @rpath/libgrass_gis.7.8.dylib
              Referenced from: /Applications/QGIS-Dev.app/Contents/MacOS/lib/qgis/grass/modules/qgis.g.info7
              Reason: image not found
             
             GRASS provider Cannot get map info
             Cannot run module
             command: /Applications/QGIS-Dev.app/Contents/MacOS/lib/qgis/grass/modules/qgis.g.info info=info rast=landuse@PERMANENT
             stdout: 
             stderr: dyld: Library not loaded: @rpath/libgrass_gis.7.8.dylib
              Referenced from: /Applications/QGIS-Dev.app/Contents/MacOS/lib/qgis/grass/modules/qgis.g.info7
              Reason: image not found
             
             Raster layer Provider is not valid (provider: grassraster, URI: /Volumes/SharedFolders/Home/shared/data/spearfish60_grass7/PERMANENT/cellhd/landuse
```

**Comment by nicogodet** [comment]
Is this still valid with current LTR ?

**Comment by JPAbdalla** [comment]
Yes, just installed QGIS 3.22.11-Białowieża LTR.

Error message below:

2022-10-20T14:04:36     WARNING    Erro de inicialização do GRASS : Problema na inicialização do GRASS, o provedor GRASS e o complemento não funcionará: Module built against version 2021-02-10T17:13:06+00:00 but trying to use version 2021-02-10T17:08:53+00:00. You need to rebuild GRASS GIS or untangle multiple installations.

In QGIS 3.16 was perferct! 👌
<img width="908" alt="Captura de Tela 2022-10-20 às 14 09 57" src="https://user-images.githubusercontent.com/14085312/197014244-6528829c-e394-4a3a-b40d-51e4eefbaa49.png">
<img width="824" alt="Captura de Tela 2022-10-20 às 14 09 45" src="https://user-images.githubusercontent.com/14085312/197014252-b908104c-71f7-40a0-8f32-b5ae8380fbc2.png">

**Comment by christro** [comment]
I have exact the same Problem with Version 3.28 besides an existing 3.22 LTR:

GRASS init error: Problem in GRASS initialization, GRASS provider and plugin will not work : Module built against version 2021-02-10T17:13:06+00:00 but trying to use version 2021-02-10T17:08:53+00:00. You need to rebuild GRASS GIS or untangle multiple installations.

 I think the problem is, that the QGIS MacOS  Iinstaller doesn't really supports multilple QGIS installations in one system. I think this behaviour came with 3.12. For older versions you could have multiple versions at the same MacBook which is much more desirable than the present situation

![Screenshot 2022-11-11 at 23 35 29](https://user-images.githubusercontent.com/8968680/201440187-e9df1fbd-e108-4e5d-ba38-f434829d829c.png)
