### ISSUE TITLE
Problem when snapping objects

### ISSUE THREAD

**Issue by adrianbrosz** [qgis/QGIS#41788]
During digitising:

<img width="569" alt="snap" src="https://user-images.githubusercontent.com/29169682/109000663-4b00f480-76a4-11eb-957d-ce84da5f6a72.png">

**Comment by gioman** [comment]
@adrianbrosz 

1) try with a new QGIS profile, no 3rd party plugins installed

2) if the problem persist please add all the infos requested https://github.com/qgis/QGIS/issues/new?assignees=&labels=Bug&template=10_bug_report.md&title=

also attach a sample project+data if needed.

**Comment by adrianbrosz** [comment]
The issue persists when using new profile without any plugins.

Steps to reproduce:
1) Add new text layer from txt file
2) Choose style for this layer
3) Use snapping:
![obraz](https://user-images.githubusercontent.com/29169682/112946615-0ac6e300-9136-11eb-869f-d467a2be58eb.png)
4) Insert new line objects
5) Cut existing line objects at connection points with new objects
![obraz](https://user-images.githubusercontent.com/29169682/112946829-45c91680-9136-11eb-9702-5e6dba1fbe6e.png)


 

Pozdrawiam,

**Comment by adrianbrosz** [comment]
QGis 3.10, Windows 10 20H2

**Comment by gioman** [comment]
@adrianbrosz please attach a sample project + data.

**Comment by adrianbrosz** [comment]
OK, but the database is over 1GB - provide a link to GDrive?

**Comment by gioman** [comment]
> OK, but the database is over 1GB - provide a link to GDrive?

is ok, but may you want to try find is the same problem is replicable also on a smaller datataset.

**Comment by gioman** [comment]
Closing for lack of feedback.
