### ISSUE TITLE
OSGeo4W-NG - Can Not Load LAS/LAZ

### ISSUE THREAD

**Issue by Saijin-Naib** [qgis/QGIS#41792]
**Describe the bug**
LAS/LAZ files are not able to be listed in QGIS Browser, nor successfully added to a canvas (either by drag and drop or by Data Source Manager).

**How to Reproduce**
Try to open any LAS/LAZ file using the methods listed above.

https://user-images.githubusercontent.com/19295950/109008228-1167c380-767b-11eb-8318-a26af5fc7550.mp4

**QGIS and OS versions**
QGIS version
3.18.0-Zürich
QGIS code revision
bdef9fb3
Compiled against Qt
5.15.2
Running against Qt
5.15.2
Compiled against GDAL/OGR
3.2.1
Running against GDAL/OGR
3.2.1
Compiled against GEOS
3.9.1-CAPI-1.14.2
Running against GEOS
3.9.1-CAPI-1.14.2
Compiled against SQLite
3.33.0
Running against SQLite
3.33.0
Compiled against PDAL
2.2.0
Running against PDAL
2.2.0 (git-version: 38aa11)
PostgreSQL Client Version
13.0
SpatiaLite Version
5.0.1-rc1
QWT Version
6.1.3
QScintilla2 Version
2.11.5
Compiled against PROJ
7.2.1
Running against PROJ
Rel. 7.2.1, January 1st, 2021
OS Version
Windows 10 Version 2009
Active python plugins
bettereditor; 
CalculateGeometry; 
cartography_tools; 
MemoryLayerSaver; 
project_colors_dock; 
slyr; 
toggle_labels_widget; 
zoom_level; 
db_manager; 
MetaSearch; 
processing

**Additional context**
Log Messages - General  
`2021-02-24T08:25:52     WARNING    Unable to load Z:/Static Backups/USERNAME/GIS Thesis Files/Seneca_LIDAR/All_TMcorrected_Seneca_classified.las`

Log Messages - OGR  
`2021-02-24T08:25:52     WARNING    Cannot open Z:/Static Backups/USERNAME/GIS Thesis Files/Seneca_LIDAR/All_TMcorrected_Seneca_classified.las.()`

Log Messages - Messages  
`2021-02-24T08:25:52     CRITICAL    Invalid Data Source : Z:/Static Backups/USERNAME/GIS Thesis Files/Seneca_LIDAR/All_TMcorrected_Seneca_classified.las is not a valid or recognized data source.`

**Comment by wonder-sk** [comment]
Can you please check if:
- in About > Providers - can you see "PDAL point cloud data provider" in the list?
- in Data Source Manager > Point Cloud - are you able to open a LAS/LAZ file there?

Where did you install the OSGeo4W-NG ? Is there a chance you have had a previous version of OSGeo4W installed in the same directory and there is some clash of libraries?

**Comment by Saijin-Naib** [comment]
> * in About > Providers - can you see "PDAL point cloud data provider" in the list?

No, it is not listed.

---

Available QGIS Data Provider Plugins

DB2 Spatial Extender provider

OGC API - Features data provider

WFS data provider

ArcGIS Feature Service data provider

ArcGIS Map Service data provider

Delimited text data provider

EPT point cloud data provider

GDAL data provider

GeoNode provider

GPS eXchange format provider

GRASS 7 vector provider

GRASS 7 raster provider

SAP HANA spatial data provider

MDAL provider

Memory provider

Mesh memory provider

MSSQL spatial data provider

OGR data provider

Oracle data provider

OWS meta provider

PostgreSQL/PostGIS data provider

Postgres raster provider

SpatiaLite data provider

Vector tile provider

Virtual layer data provider

OGC Web Coverage Service version 1.0/1.1 data provider

OGC Web Map Service version 1.3 data provider

Available QGIS Authentication Method Plugins

Basic authentication

ESRI token

Identity certificate authentication

OAuth2 authentication

PKI PKCS#12 authentication

PKI paths authentication

Available Qt Database Plugins

QOCISPATIAL
QOCISPATIAL8
QSPATIALITE
QSQLITE
QMARIADB
QMYSQL
QMYSQL3
QODBC
QODBC3
QPSQL
QPSQL7
Available Qt Image Plugins
Qt Image Plugin Search Paths 
D:/Apps/QGIS/apps/qgis/plugins
D:/Apps/QGIS/apps/qgis/qtplugins
D:/Apps/QGIS/apps/qt5/plugins
D:/Apps/QGIS/apps/Qt5/plugins
D:/Apps/QGIS/bin
bmp
cur
gif
icns
ico
jpeg
jpg
pbm
pdf
pgm
png
ppm
svg
svgz
tga
tif
tiff
wbmp
webp
xbm
xpm


> * in Data Source Manager > Point Cloud - are you able to open a LAS/LAZ file there?
> 
Nope, as indicated above, it does not list it as a supported format, and choosing All Types and selecting a LAS/LAZ yields the Unsupported File Type error.

> Where did you install the OSGeo4W-NG ? Is there a chance you have had a previous version of OSGeo4W installed in the same directory and there is some clash of libraries?

http://download.osgeo.org/osgeo4w/testing/osgeo4w-setup.exe

No chance of conflicts. Prior install of QGIS 3.16 was fully uninstalled, and the directory deleted/emptied prior to install using OSGeo4G-NG from above link to install QGIS 3.18.0-5

**Comment by bellanz80** [comment]
I confirm All.

**Comment by puneethgeospoc** [comment]
I am using version 3.22.14 on m1 Mac. I do not have point cloud support in my Data Source Manager. Not does the drag/drop load las/laz. Any solutions to this coming up ? 
<img width="611" alt="image" src="https://user-images.githubusercontent.com/107855115/213988062-e47117e1-7cc6-4745-8e8f-c0f35d1cda99.png">

**Comment by sheecegardezi** [comment]
@jef-n why did you close this issue? This is not resolved.

**Comment by jef-n** [comment]
> @jef-n why did you close this issue? This is not resolved.

The problem was that the pdalprovider was not packaged in osgeo4w - and that was fixed.
