### ISSUE TITLE
OSGeo4W-NG - EPTs load strangely in 3D View

### ISSUE THREAD

**Issue by Saijin-Naib** [qgis/QGIS#41794]
**Describe the bug**
EPTs load quite strangely in the 3D View. There are two representations of the data loaded at once. The actual 3D Point Cloud and a flat, top-down image that is strictly 2D. The 3D Point Cloud loads at a significant distance above the 2D image of the same scene. It feels like the 3D Scene origin/center coordinates is set to somewhere in the middle of the two, as Terrain-Based Navigation seems to pivot on a point in space there.

**How to Reproduce**
Load an EPT.json (from OpenDroneMap in this instance)
Create New 3D View
Observe that 3D View loads centered on the 2D representation
Zoom/pan around to explore the two representations of the scene

**QGIS and OS versions**

QGIS version
3.18.0-Zürich
QGIS code revision
bdef9fb3
Compiled against Qt
5.15.2
Running against Qt
5.15.2
Compiled against GDAL/OGR
3.2.1
Running against GDAL/OGR
3.2.1
Compiled against GEOS
3.9.1-CAPI-1.14.2
Running against GEOS
3.9.1-CAPI-1.14.2
Compiled against SQLite
3.33.0
Running against SQLite
3.33.0
Compiled against PDAL
2.2.0
Running against PDAL
2.2.0 (git-version: 38aa11)
PostgreSQL Client Version
13.0
SpatiaLite Version
5.0.1-rc1
QWT Version
6.1.3
QScintilla2 Version
2.11.5
Compiled against PROJ
7.2.1
Running against PROJ
Rel. 7.2.1, January 1st, 2021
OS Version
Windows 10 Version 2009
Active python plugins
bettereditor; 
CalculateGeometry; 
cartography_tools; 
MemoryLayerSaver; 
project_colors_dock; 
slyr; 
toggle_labels_widget; 
zoom_level; 
db_manager; 
MetaSearch; 
processing

**Additional context**

https://user-images.githubusercontent.com/19295950/109009045-0b261700-767c-11eb-9d83-22eddafec1d2.mp4

**Comment by saberraz** [comment]
This is not a bug and a feature!

The top image is the 3D representation of your points. And the lower one is the 2D. You can set the 2D image as extent only.

**Comment by Saijin-Naib** [comment]
Can we get an option to hide it and navigate from the top 3D representation? This is highly unusual and does not seem like it would be the intended UX.

**Comment by saberraz** [comment]
At the moment, the behaviour is similar to other data providers. For example a vector can be seen in a flat 2D plane and as 3D objects. Both symbology are available in the 3D map view.

It is indeed confusing for point cloud data.

**Comment by Saijin-Naib** [comment]
> At the moment, the behaviour is similar to other data providers. For example a vector can be seen in a flat 2D plane and as 3D objects. Both symbology are available in the 3D map view.
> 
> It is indeed confusing for point cloud data.

Musing here, but would an extra tab in the View 3D Settings for something like Layer Representation be a possible later fix? This tab would list all layers in the 3D View, and have checkboxes for 2D and 3D representation, allowing the user to set how to view each layer (2D, 3D, or both). Probably similar to the UI/UX of the Project Properties - Data Sources tab/panel where you can choose what layers are able to be identified/searched/etc.

**Comment by Saijin-Naib** [comment]
It'd be nice if we could turn off the 2D representation so it doesn't block the 3D view, like it does for this LAZ data:  
![image](https://user-images.githubusercontent.com/19295950/109342823-70276b80-783a-11eb-8b56-2be1f274f735.png)
