### ISSUE TITLE
DXF export improvements

### ISSUE THREAD

**Issue by ADAMKEPES** [qgis/QGIS#41802]
DXF export has limits:

1. Only 3D lines are exported as 3D geometry. Svg, point and other symbols, texts get 0 height in the dxf file.
2. SVG symbols (used for creating quality CAD drawings from QGIS for example) are exported as block only when there is no expression set on their smybol size and rotation. In other cases they are exported as hatches, rectangles, lines etc by elements of the symbol.
3. All the times you export a project to dxf, you must every time set of the export dxf layer attribute by qgis layers. Why can't it be set in each layer's properties, once and for all?

Only these 3 functions should be developed, To make QGIS a full-scale automatic CAD formatter !

**Comment by roya0045** [comment]
You make a bug issue, but talk about developpement. This is a feature request then? If so your points are not clear and should prefrably split up in 1 feature request per element.

Same if they truly are bug.

**Comment by ADAMKEPES** [comment]
When something is not working properly i think that is a bug. I don't 
think these issues are coded purposely for a reason.

You want to export a geometry.... and that geometry is not the same in 
the exported file... :) I wouldn't call that a feature to be :)

2021. 02. 24. 23:40 keltezéssel, Alex írta:

**Comment by gioman** [comment]
> When something is not working properly i think that is a bug. I don't think these issues are coded purposely for a reason. You want to export a geometry.... and that geometry is not the same in the exported file... :) I wouldn't call that a feature to be :) 

@ADAMKEPES feel free for you or your organization to contribute code or else to help make this QGIS functionality better.

**Comment by ADAMKEPES** [comment]
I would gladly offer some money to contribute to the developement of these
issues. Could you inform me about the amount needed for fixing these things
and the way i could pay it?

Thank you

Giovanni Manghi <notifications@github.com> ezt írta (időpont: 2021. febr.
25., Csü 11:14):

**Comment by gioman** [comment]
> I would gladly offer some money to contribute to the developement of these issues. Could you inform me about the amount needed for fixing these things and the way i could pay it?

@ADAMKEPES https://qgis.org/en/site/forusers/commercial_support.html

**Comment by nyalldawson** [comment]
@ADAMKEPES I'd suggest contacting @jef-n (Norbit) from that list first -- he's had the most experience with DXF/DWG support in QGIS :+1:

**Comment by m-kuhn** [comment]
Exporting a point layer to DXF works for me with default and SVG symbology including heights. Can you provide a sample project to reproduce?
