### ISSUE TITLE
Cannot make qgis.db private copy

### ISSUE THREAD

**Issue by ElCartografo** [qgis/QGIS#41806]
Just installed QGIS from US Census BAS website.  When starting initially after setup, get this error.

Report details:

Crash ID: 9dd447e8923a898061d2ea6718b134d43fc7e2b3

Stack Trace

QList::size :
QgsMessageBar::pushMessage :
QgsMessageBar::pushInfo :
QgisApp::showSystemNotification :
QgisApp::authMessageOut :
QMetaObject::activate :
QgsAuthManager::messageOut :
QgsAuthManager::authDatabaseConnection :
QgsAuthManager::sslCertCustomConfigByHost :
QgsNetworkAccessManager::createRequest :
QNetworkAccessManager::get :
QgsVectorLayerLoadStyleDialog::updateLoadButtonState :
QgsVectorLayerLoadStyleDialog::updateLoadButtonState :
QgisApp::QgisApp :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.4.4-Madeira
QGIS code revision: 73c31df831
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.0
Running against GDAL: 2.4.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

**Comment by nyalldawson** [comment]
QGIS 3.4 is no longer supported -- you need to use either QGIS 3.16.4 or 3.18.0.

**Comment by roya0045** [comment]
Get it from the official source also, 3.4 should be more than a year old.

**Comment by gioman** [comment]
Closing for lack of feedback.
