### ISSUE TITLE
QGIS freezees when adding a CSV with the option "watched"

### ISSUE THREAD

**Issue by noah-clay** [qgis/QGIS#41810]
Added a ~1400 line 'watched' CSV and get repeated full-lock on QGIS 3.18. Works as long as I do not select 'watched'

**Comment by gioman** [comment]
@noah-clay plase

1) attach the CSV

2) add all the infos requested



**Describe the bug**


**How to Reproduce**



1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error -->

**QGIS and OS versions**



**Additional context**

**Comment by gioman** [comment]
Closing for lack of feedback.
