### ISSUE TITLE
change to  my qgs-app.dll,error

### ISSUE THREAD

**Issue by farewell5566** [qgis/QGIS#41827]
Stack Trace

QString::toUtf8_helper :
QString::toUtf8 :
QgsPythonUtilsImpl::evalString qgspythonutilsimpl.cpp:530
Ui_QgsRasterCalcDialogBase::setupUi ui_qgsrastercalcdialogbase.h:160
QgsAngleMagnetWidget::qt_metacall moc_qgsmaptoolrotatefeature.cpp:147
`Ui_MainWindow::setupUi'::`1'::dtor$601 :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.16.2-Hannover
QGIS code branch: Release 3.16
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by gioman** [comment]
@farewell5566 please reopen following the guidelines you find here

https://github.com/qgis/QGIS/issues/new?assignees=&labels=Bug&template=10_bug_report.md&title=
