### ISSUE TITLE
[Point Cloud] EPT loading crashes after QgsMapRendererParallelJob::start

### ISSUE THREAD

**Issue by Jean-Roc** [qgis/QGIS#41828]
Hi,

I'm trying to load an existing ept.json dataset generated with Entwine 2.1.0, this file has been updated to add statistics (see #41666, test with success on another ept).

The last line of the debug log is when QgsMapRendererParallelJob::start is called.

**QGIS and OS versions**

- QGIS 3.19.0-Master 61b6cc21e (OSGEO4W-NG)
- Qt 5.15.2
- PDAL 2.2.0 (git-version: 38aa11)
- Windows 10 Version 1809

**Additional context**

- [Debug log](https://github.com/qgis/QGIS/files/6043443/qgis_ept_crash.log)
- [ept.json](https://github.com/qgis/QGIS/files/6043441/ept_json.txt)
- [metadata.json](https://github.com/qgis/QGIS/files/6043437/metadata_json.txt)
- 
regards,
jean-roc

**Comment by wonder-sk** [comment]
Hmm the debug log can be pointing to the wrong direction and it's not of much use... Could you please submit the backtrace printed when QGIS crashes?

Is this happening every time, and immediately after you load the file?

Is there any chance to get hold of the data you have been using for testing? (Maybe the manual editing of ept.json had some unwanted side effects)

**Comment by Jean-Roc** [comment]
Hi Martin, this data is open but I can't give you access to it as it weights 1.2 To and I'm lacking an http server. There was no backtrace generated, do i need a specific version of qgis to generate one ? The shutdown also happens with the unedited json

**Comment by Jean-Roc** [comment]
@wonder-sk this dataset is now available over [https](https://webimaging.lillemetropole.fr/externe/lidar/2020_scot/ept/) with the original ept.json and the updated ept_stats.json

**Comment by wonder-sk** [comment]
@Jean-Roc  Thanks - I have tried to replicate with master using the URL, but things seem to work fine for me. Could you please try again? QGIS 3.20 also supports streaming remote EPT datasets, so you can use directly the URL to the ept.json file and it should work...

**Comment by Jean-Roc** [comment]
Thanks for the update Martin, I tried on my side with the ogeo4w dev build and I can confirm that it does not crash anymore ! The initial load time is ~20 minutes, it works with the manually added stats !
