### ISSUE TITLE
QGIS 3.18 not loading point cloud in format LAZ or LAS

### ISSUE THREAD

**Issue by SotokanJr** [qgis/QGIS#41838]
Hi, I have installed QGIS from OSGEO on my computer (with windows 10) following the steps from this post:
https://www.lutraconsulting.co.uk/blog/2021/02/15/qgis-point-cloud-windows/
According to with the post, I have download OSGEO from here:
http://download.osgeo.org/osgeo4w/testing/osgeo4w-setup.exe
And once OSGEO has been installed, I have open QGIS from the bin folder using this bat file "qgis-dev.bat".
However, when I drag and drop a LAS or LAZ file I get the next error:
![image](https://user-images.githubusercontent.com/30394020/109220363-bcc66480-77b0-11eb-894e-748311f8682d.png)
Then, I have tried to load the point cloud from the menu (Layer > Add Layer > Add Point Cloud dataset) and I have seen that the LAS/LAZ format are not in the list of recognised files for QGIS.
How can I load then LiDAR point Cloud in QGIS?
Thank you

**Comment by gioman** [comment]
@SotokanJr Questions must be asked in the users or developers mailing lists, or on our IRC/Telegram channels, not here. Thanks!

**Comment by FelisPimeja** [comment]
Absolutely the same problem here.
Fresh install from new OSGeo installer. No LAS/LAZ support

Windows 10 

QGIS version
3.19.0-Master
QGIS code revision
a825b5af35
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.3.0dev
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
8.0.0
Running against PROJ
Rel. 8.0.0, March 1st, 2021
OS Version
Windows 10 (10.0)
This copy of QGIS writes debugging output.
Active python plugins
db_manager; 
MetaSearch; 
processing
