### ISSUE TITLE
QGIS 3.18 - CRITICAL- Problem with GRASS installation: GRASS was not found or is not correctly installed

### ISSUE THREAD

**Issue by hugonbgg** [qgis/QGIS#41831]
I installed QGIS 3.18 using the OSGeo4w express desktop install but the GRASS algorithms do not appear in the toolbox. When I look at the log it is displayed: "QGIS 3.18 - CRITICAL- Problem with GRASS installation: GRASS was not found or is not correctly installed"
Using the advanced install of OSGeo4w the same problem occurs.

It is a new installation and with a new profile, I deleted everything to test if it was not a file conflict.

To reproduce:
- Install QGIS 3.18 using express desktop install on OSgeo4w.
- Start QGIS
- Enable GRASS Plugin
- Enable log messages
**QGIS and OS versions**

QGIS version
3.18.0-Zürich
QGIS code revision
bdef9fb328
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
db_manager; 
MetaSearch; 
processing

**Comment by gioman** [comment]
@hugonbgg duplicate of https://trac.osgeo.org/osgeo4w/ticket/661 ?

**Comment by hugonbgg** [comment]
No, they are different problems. GRASS works normally here, the problem is to access GRASS within QGIS via the processing toolbox.

> @hugonbgg duplicate of https://trac.osgeo.org/osgeo4w/ticket/661 ?

**Comment by gioman** [comment]
> No, they are different problems. GRASS works normally here, the problem is to access GRASS within QGIS via the processing toolbox.

@hugonbgg are you launching QGIS with the "with GRASS" shortcut? if you don't then you don't have GRASS in processing...

**Comment by hugonbgg** [comment]
> > No, they are different problems. GRASS works normally here, the problem is to access GRASS within QGIS via the processing toolbox.
> 
> @hugonbgg are you launching QGIS with the "with GRASS" shortcut? if you don't then you don't have GRASS in processing...

Yes, I am using QGIS with the "with GRASS" shortcut and GRASS 7 is enabled in the plugins.
And yet GRASS is not displayed in the Processing Toolbox and the message log displays "CRITICAL- Problem with GRASS installation: GRASS was not found or is not correctly installed"

**Comment by gioman** [comment]
> Yes, I am using QGIS with the "with GRASS" shortcut and GRASS 7 is enabled in the plugins.
> And yet GRASS is not displayed in the Processing Toolbox and the message log displays "CRITICAL- Problem with GRASS installation: GRASS was not found or is not correctly installed"

@hugonbgg I have just tested on clean Win10 machine using the new osgeo4w installer and all works as expected in GRASS/Processing.

**Comment by gioman** [comment]
Maybe you have missed to install some package with osgeo4w(?).

**Comment by hugonbgg** [comment]
Now it worked! I used the new OSGeo4w installer: http://download.osgeo.org/osgeo4w/testing/osgeo4w-setup.exe
Many thanks @gioman!
In the "old" OSGeo4w, GRASS is not displayed in version 3.18 and 3.16.4.

**Comment by shiquwucan** [comment]
我没明白怎么做的？

**Comment by shiquwucan** [comment]
我用QGIS3.22.5也识别不到grass，但我我没有理解你是怎么让grass恢复使用的？
<img width="878" alt="Snipaste_2024-06-19_11-18-10" src="https://github.com/qgis/QGIS/assets/98943326/bf050857-cdf8-4be4-8341-bb444d567875">
