### ISSUE TITLE
How to solve 'Raster Calculator: Could not create destination file.' ?

### ISSUE THREAD

**Issue by Photsawat** [qgis/QGIS#41845]
I want to find the order of the watershed with a raster calculator. But after completing the input, press ok, the program will show a message 'Raster Calculator: Could not create destination file.'. How can I solve the problem? Thank

**Comment by gioman** [comment]
@Photsawat  Questions must be asked in the users or developers mailing lists, or on our IRC/Telegram channels, not here. Thanks!
