### ISSUE TITLE
3.18 Export Project to DXF not working

### ISSUE THREAD

**Issue by kiri03** [qgis/QGIS#41856]
**Describe the bug**
When using the option Export Project to DXF, QGIS hangs, stops working and after a few seconds the program closes

**How to Reproduce**
Simply load any vector layer and choose the Export Project to DXF option

**QGIS and OS versions**
Versión de QGIS
3.18.0-Zürich
Revisión del código de QGIS
bdef9fb328
Compilado contra Qt
5.11.2
Ejecutándose contra Qt
5.11.2
Compilado contra GDAL/OGR
3.1.4
Ejecutándose contra GDAL/OGR
3.1.4
Compilado contra GEOS
3.8.1-CAPI-1.13.3
Ejecutándose contra GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
Versión del cliente PostgreSQL
11.5
Versión de SpatiaLite
4.3.0
Versión de QWT
6.1.3
Versión de QScintilla2
2.10.8
Compilado contra PROJ
6.3.2
Ejecutándose contra PROJ
Rel. 6.3.2, May 1st, 2020
Versión del SO
Windows 10 (10.0)
Active python plugins
AnotherDXF2Shape; 
FeatureGridCreator; 
jccm_bar3; 
joinmultiplelines; 
kmltools; 
latlontools; 
lrs; 
mmqgis; 
ntv2_transformations; 
openlayers_plugin; 
qchainage; 
qconsolidate3; 
qfieldsync; 
quick_map_services; 
SentinelHub; 
shapetools; 
slyr_community; 
db_manager; 
MetaSearch; 
processing

**Additional context**

**Comment by jef-n** [comment]
Duplicate of #41858
