### ISSUE TITLE
Processing Script: QGIS crashes when layers don't exist

### ISSUE THREAD

**Issue by tschmetzer** [qgis/QGIS#41869]
I've read the c++ wrapper for python is still pretty unstable. Don't know if anybody is interested in the following bug?

there is a crash after _indraw1_ and before _indraw_ 2 and no warning that _debug_layer_ doesn't exist
```
def draw_buffer(geometry,feature,layer_type, own_feature_id, common_feature_ids):
	debug_feature=QgsFeature()
	debug_feature.setGeometry(geometry)
	logging.debug('indraw1')

	debug_feature.setFields(debug_layer.fields())
	logging.debug('indraw2')
```

**Comment by roya0045** [comment]
There are so many ways to crash python that relies on c++ bindings. You're calling a function for a thing that is not defined. That usually end un in a traceback. 

Any bad python code will behave badly and even brick qgis in some cases ( like a bad processing script or bad project macro). Handling those should be improved but I'm not sure how easy that is.

**Comment by nyalldawson** [comment]
We'd need to see more of your script to determine the error

**Comment by roya0045** [comment]
@nyalldawson  I think that simply having an uninitialized variable is enough to crash. Something like `b.help()` should give the same result. Though it depends where it is executed. In the script editor error are handled correctly, not so much in a saved script in the processing toolbox or a macro, from experience.

**Comment by tschmetzer** [comment]
That looks like the **Processing Script** Interface and the **Python Script** Interface handle things differently. Is there a reason for this other than maybe a separate historic growth? Would it make sense to align this and e.g. use the same verification methods to avoid QGIS c++/python bindings running into exceptions and crashes?

I also get errors like _"NameError: free variable 'self' referenced before assignment in enclosing scope"_. 
Maybe my script isn't perfect and it's not such a big deal for me to debug these errors as I have a viable debug possibility and I know the original script had run successfully in the python console. But I imagine for many users that are not very experienced in script writing this could be a big deal and they might be frustrated about the crashes and incomprehensible error messages.

Given this enlightenment I don't know if it adds any value to make available more of my script. But of course I can take the time do so if this is really of any value.

**Comment by gioman** [comment]
@tschmetzer attach/post the script.

**Comment by tschmetzer** [comment]
Attached you can find the script alongside with two sample shapefiles: [richtungsbestimmung.zip](https://github.com/qgis/QGIS/files/6061362/richtungsbestimmung.zip)

Sometimes QGIS just crashes, sometimes error messages are displayed. With the larger file crashes seem to be more likely.

- Crash or critical error on such simple missing imports. The critical error is totally fine but every now and then an complete QGIS crash happens (see stack trace below). Unfortunately I couldn't find out when/why it crashes and when/why not.
2021-03-01T12:19:00     CRITICAL    Traceback (most recent call last):
              File "", line 438, in processAlgorithm
              File "", line 178, in insert_direction
              File "", line 111, in get_direction
             NameError: name 'QgsGeometryUtils' is not defined


- When I set the field filter wrong, e.g.  B_TYPE instead of A_TYPE at lines 140/143 of the script:

`2021-03-01T12:18:44     CRITICAL    TypeError: invalid result from RichtungsProcessingAlgorithm.processAlgorithm(), NoneType cannot be converted to a C/C++ QVariantMap in this context`

The user doesn't know where and why the error occurs.




- Crashes typically include messages like this

Crash ID: 6bdc15eef93fa06fad98a53b9bfd465135722e1f


Stack Trace


QObject::thread :
`QgsProcessingAlgorithm::runPrepared'::`1'::catch$46 qgsprocessingalgorithm.cpp:549
_CallSettingFrame handlers.asm:50
__FrameHandler3::CxxCallCatchBlock frame.cpp:1480
RcConsolidateFrames :
QgsProcessingAlgorithm::runPrepared qgsprocessingalgorithm.cpp:532
QgsProcessingAlgRunnerTask::run qgsprocessingalgrunnertask.cpp:66
sipQgsProcessingAlgRunnerTask::run sip_corepart4.cpp:67608
QgsTask::start qgstaskmanager.cpp:83
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.18.0-Z�rich
QGIS code revision: bdef9fb328
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

**Comment by gioman** [comment]
> Attached you can find the script alongside with two sample shapefiles: [richtungsbestimmung.zip](https://github.com/qgis/QGIS/files/6061362/richtungsbestimmung.zip)

@tschmetzer how is supposed to be used? you attach two vectors, with different CRSs and the script accepts only 1 input.



> Sometimes QGIS just crashes, sometimes error messages are displayed. With the larger file crashes seem to be more likely.

On QGIS master on Linux and I don't get any crash or get any error message that is similar to the one you posted. Actually I get a 


```
Traceback (most recent call last):
File "/home/giovanni/.local/share/QGIS/QGIS3/profiles/default/processing/scripts/Richtungsbestimmung_Processing_anonymized.py", line 438, in processAlgorithm
insert_direction(templayer)
File "/home/giovanni/.local/share/QGIS/QGIS3/profiles/default/processing/scripts/Richtungsbestimmung_Processing_anonymized.py", line 149, in insert_direction
index_wall_layer=build_spatial_index( feature_dict_wall_layer)
File "/home/giovanni/.local/share/QGIS/QGIS3/profiles/default/processing/scripts/Richtungsbestimmung_Processing_anonymized.py", line 37, in build_spatial_index
index = QgsSpatialIndex()
NameError: name 'QgsSpatialIndex' is not defined
```

please help clarify.

**Comment by tschmetzer** [comment]
You can try both input vector layers. Using templayer I wasn't able to produce a crash. With the larger dataset in templayer2 I got the crashes every 2nd or third time modyfiying the attribute name in the script or the layer. You can also just play around by trying to get rid of the error messages by "improving" the script. 

I am calling the script via the processing toolbox like this:
![grafik](https://user-images.githubusercontent.com/67278094/109501525-fe4c5d80-7a97-11eb-9e87-8c5cc3092ec9.png)

If you're still not able to reproduce we can agree on a quick video conference.

**Comment by gioman** [comment]
> I am calling the script via the processing toolbox like this:

@tschmetzer and after opening the script?




> If you're still not able to reproduce we can agree on a quick video conference.

@tschmetzer or just post a screencast of the steps necessary to replicate the problem in your system.

**Comment by tschmetzer** [comment]
> > I am calling the script via the processing toolbox like this:
> 
> @tschmetzer and after opening the script?

After opening I just run it. Sometimes it doesn't crash at the first run.


> 
> > If you're still not able to reproduce we can agree on a quick video conference.
> 
> @tschmetzer or just post a screencast of the steps necessary to replicate the problem in your system.

- reboot Windows
- STart QGIS
- new project
- save project
- drag templayer.dbf into Layers
- drag templayer2.dbf into Layers
- select templayer2
- processing toolbox/scripts/existing scripts -> choose attached file "Richtungsbestimmung_Processing_anonymized.py" -> open
- run script -> run


Sometimes I get this message and no crash:
```
An error has occurred while executing Python code: 

NameError: free variable 'self' referenced before assignment in enclosing scope 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\gui\AlgorithmDialog.py", line 206, in on_complete
    self.feedback.reportError(
NameError: free variable 'self' referenced before assignment in enclosing scope

```

Then I run it again:
- processing toolbox/scripts/existing scripts -> choose attached file
- run script -> run

=> QGIS stalls/freezes for moment and crashes

Looks like sometimes there's a second or third script execution required for to reproduce the crash.

Once this crash is reproduced and fixed I recommend to add the required imports Processing Script interpreter complains about to test if all problems have been found.

**Comment by gioman** [comment]
> => QGIS stalls/freezes for moment and crashes

@tschmetzer ok I replicated the crash on Windows (not before having cleaned you templayer2 shape as it has many geometry errors). Now remains to be seen if your script is ok or not.

**Comment by tschmetzer** [comment]
I ignore geometry errors as polygons are sometimes situated on top of each otherAm 01.03.21, 17:05 schrieb Giovanni Manghi <notifications@github.com>:

   
   
   => QGIS stalls/freezes for moment and crashes 
   
  @tschmetzer ok I replicated the crash on Windows (not before having cleaned you templayer2 shape as it has many geometry errors). Now remains to be seen if your script is ok or not.

**Comment by tschmetzer** [comment]
> 
> I ignore geometry errors as polygons are sometimes situated on top of each other

The attribute A_TYPE means surface type i.e. 1=ground, 2=wall, 3=roof
The only surface type that the QGIS validity algorithm characterizes as invalid are the walls. Walls possess Z-values which from a 2D perspective might seem wrong. I cannot see any error there and also I need the whole data for my algorith which is why I chose to not filter invalid features

![grafik](https://user-images.githubusercontent.com/67278094/109561217-26aa7b00-7add-11eb-8e7e-49f9533cd4fc.png)


I personally highly suspect the validity check/invalid features filtering algorithm to be **incorrect** for certain types of 3D data like the one used in templayer2. I examined several features **point by point** that have been marked as "invalid output"/"error output" by the validity check and all were totally fine for me.

Although this might be a separate issue for QGIS I don't suspect this at all to be the reason why QGIS crashes when the processing algorithm is executed because this same algorithm has been developed, executed and tested (as a different python script file) without any errors.

**Comment by nyalldawson** [comment]
@tschmetzer 
you are accessing non-thread safe api in your script, such as `iface.vectorLayerTools().stopEditing(templayer)`. That's ok to do, but you must ensure that your algorithm does NOT run in a background thread by returning the QgsProcessingAlgorithm.FlagNoThreading flag in your algorithms flags() override.

**Comment by tschmetzer** [comment]
> 
> @tschmetzer
> you are accessing non-thread safe api in your script, such as `iface.vectorLayerTools().stopEditing(templayer)`. That's ok to do, but you must ensure that your algorithm does NOT run in a background thread by returning the QgsProcessingAlgorithm.FlagNoThreading flag in your algorithms flags() override.

Hm, interesting. Thanks for that! Tomorrow I will try to dig deeper into non-thread safe api and how to make my Processing Algorithm non-thread safe. Is there a list of non-thread safe classes? And why was this never a problem when using the Python Script Interface? I'm also asking in order to find potential documentation gaps for improval :)

**Comment by tschmetzer** [comment]
> 
> 
> @tschmetzer
> you are accessing non-thread safe api in your script, such as `iface.vectorLayerTools().stopEditing(templayer)`. That's ok to do, but you must ensure that your algorithm does NOT run in a background thread by returning the QgsProcessingAlgorithm.FlagNoThreading flag in your algorithms flags() override.

That makes sense. So I added 

```
	def flags(self):
		return QgsProcessingAlgorithm.FlagNoThreading
```

But why do I get this RuntimeError now? 

```
An error has occurred while executing Python code: 

RuntimeError: wrapped C/C++ object of type AlgorithmDialog has been deleted 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\gui\AlgorithmDialog.py", line 246, in runAlgorithm
    on_complete(ok, results)
  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\gui\AlgorithmDialog.py", line 201, in on_complete
    self.tr('Execution completed in {0:0.2f} seconds').format(time.time() - start_time))
RuntimeError: wrapped C/C++ object of type AlgorithmDialog has been deleted
```

**Comment by tschmetzer** [comment]
When searching the code base for "QgsProcessingAlgorithm.FlagNoThreading" I found examples and a 

```
	def flags(self):
		return super().flags() | QgsProcessingAlgorithm.FlagNoThreading
```

did the job.

**Comment by tschmetzer** [comment]
Anyways it would be very beneficial for the user to know where such errors have occured, i.e. what erroneous statements they originate from. How difficult would it be to include that?
