### ISSUE TITLE
QGIS 3.18 raises an error when loading a raster layer from a geopackage that has multiple raster layers.

### ISSUE THREAD

**Issue by eloi-ribeiro** [qgis/QGIS#41860]
QGIS 3.18 raises an error when loading a raster layer from a geopackage that has multiple raster layers. If it has only one raster layer, then is fine.  Geopackage raster layers names also display '!!' ahead of their names.

**How to Reproduce**

1. Get an GeoTiff
``` sh
cd ~/Downloads/
wget https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/raster/US_MSR_10M.zip
unzip ~/Downloads/US_MSR_10M.zip
```
2. Convert GeoTiff to gpkg
``` sh
gdal_translate -of GPKG ~/Downloads/US_MSR_10M/US_MSR.tif ~/Downloads/test.gpkg -co RASTER_TABLE=msr01 -co RASTER_DESCRIPTION='First raster layer'
```
3. Create connection to the gpkg file
4. At this point the layer loads in QGIS with no error message
5. Add the same image a second time with a different name. I also tried with a different raster, but result is the same.
``` sh
gdal_translate -co APPEND_SUBDATASET=YES -of GPKG ~/Downloads/US_MSR_10M/US_MSR.tif ~/Downloads/test.gpkg -co RASTER_TABLE=msr02 -co RASTER_DESCRIPTION='Second raster layer'
```
6. Raster layers names display '!!' ahead of their names. At this point both layers raise the same error message when trying to load layer in QGIS 3.18

7. Error message: Invalid Layer: GDAL provider Cannot open GDAL dataset GPKG:/home/user/Downloads/test.gpkg:msr01!!::!!msr01: Raster layer Provider is not valid (provider: gdal, URI: GPKG:/home/user/Downloads/test.gpkg:msr01!!::!!msr01

**QGIS and OS versions**

NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"

QGIS version | 3.18.0-Zürich | QGIS code revision | bdef9fb328
Compiled against Qt | 5.12.8 | Running against Qt | 5.12.8
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
Compiled against PDAL | 2.0.1 | Running against PDAL | 2.0.1 (git-version: Release)
PostgreSQL Client Version | 12.6 (Ubuntu 12.6-0ubuntu0.20.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Ubuntu 20.04.2 LTS
Active python plugins | postgis_geoprocessing; SpeciesExplorer; DigitizingTools; pointsamplingtool; contour; postgisQueryBuilder; SRTM-Downloader; eu_mapper; openlayers_plugin; qgis_versioning; geoscience; covid19_tracker; SentinelHub; postgis_sampling_tool; EuroDataCube; Nuclear-Energy-Plant-Radiations-; valuetool; quick_map_services; StreetView; DotMap; mapswipetool_plugin; db_manager; processing; MetaSearch

**Additional context**

In QGIS 3.16 I did not had this issue.

**Comment by gioman** [comment]
@eloi-ribeiro confirmed here too, master on Ubuntu 20.04-

**Comment by elpaso** [comment]
CC @rouault it is probably a consequence of https://github.com/qgis/QGIS/commit/3f42393a9237db8aec60b377f88728fd76e5825f

**Comment by rouault** [comment]
@eloi-ribeiro @gioman Can you better explain how to reproduce the issue ? I didn't manage to get an error

When doing:

>     3\. Add the same image a second time with a different name. I also tried with a different raster, but result is the same.

the existing connection to the GPKG still lists a single raster table, but I think this is completely unrelated to my changes. I have to restart QGIS to get the connection to display the 2 raster tables, and I can just load them fine as layers in my project.

**Comment by eloi-ribeiro** [comment]
After adding a second raster layer to the same geopackage, refresh the geopackage connection in QGIS and try to load any of the two raster layers.

**Comment by rouault** [comment]
> refresh the geopackage connection in QGIS

I feel dumb to ask, but how do I do that... ?

**Comment by elpaso** [comment]
@rouault from the browser, filesystem directory items...

**Comment by eloi-ribeiro** [comment]
![Screenshot from 2021-02-26 18-37-09](https://user-images.githubusercontent.com/60199870/109334969-b3490500-7861-11eb-8009-c9f7efffab36.png)

**Comment by rouault** [comment]
Ah I missed the Refresh icon... But even with that hint, I don't reproduce the issue. I don't get the leading "!!". Updating my QGIS sources and rebuilding...

**Comment by eloi-ribeiro** [comment]
Are you using QGIS 3.18 and have two layers in the gpkg?

**Comment by rouault** [comment]
> Are you using QGIS 3.18 and have two raster layers in the gpkg?

I was on QGIS master somewhere after the https://github.com/qgis/QGIS/commit/3f42393a9237db8aec60b377f88728fd76e5825f change. Yes I have two raster layers in the gpkg

**Comment by rouault** [comment]
> I was on QGIS master somewhere after the [3f42393](https://github.com/qgis/QGIS/commit/3f42393a9237db8aec60b377f88728fd76e5825f) change

Hum actually not completely sure about that. Anyway rebuild QGIS master now

**Comment by rouault** [comment]
ok, I could reproduce the issue (was on another branch initially, sorry). Fix queued in https://github.com/qgis/QGIS/pull/41871
