### ISSUE TITLE
QgsCheckableCombobox : checkedItemsChanged signal doesn't fire

### ISSUE THREAD

**Issue by sigeal** [qgis/QGIS#41897]
When QgsCheckableCombobox is implemented in a Python plugin, as shown hereafter, checkedItemsChanged signal doesn't fire : print is not executed (also tested with QgsMessageLog).

**How to Reproduce**

```
self.checkableCbx = QgsCheckableComboBox(parent)

self.checkableCbx.checkedItemsChanged.connect(self.checkableCbxChkChanged)

def checkableCbxChkChanged(self, lstChecked):
    print(lstChecked)
```

**QGIS and OS versions**
Version de QGIS | 3.16.4-Hannover | Révision du code | 654e76b3cb
-- | -- | -- | --
Compilé avec Qt | 5.11.2 | Utilisant Qt | 5.11.2
Compilé avec GDAL/OGR | 3.1.4 | Utilisé avec GDAL/OGR | 3.1.4
Compilé avec GEOS | 3.8.1-CAPI-1.13.3 | Utilisé avec GEOS | 3.8.1-CAPI-1.13.3
Compilé avec SQLite | 3.29.0 | Fonctionne avec SQLite | 3.29.0
Version du client PostgreSQL | 11.5 | Version de SpatiaLite | 4.3.0
Version de QWT | 6.1.3 | Version de QScintilla2 | 2.10.8
Compilé avec PROJ | 6.3.2 | Fonctionne avec PROJ | Rel. 6.3.2, May 1st, 2020
Version de l'OS | Windows 10 (10.0)
Extensions Python actives | cadastre; french_locator_filter; lrs; plugin_reloader; quick_map_services; db_manager; processing; synoptique-obj

**Comment by alexbruy** [comment]
Fixed in 415d4831b0.
