### ISSUE TITLE
Crash when using 3d map window

### ISSUE THREAD

**Issue by phipsch63** [qgis/QGIS#41904]
**Describe the bug**
Using 3d map and rotating the viewpoint. Same instability in 3D as in Version 3.14
Last stable version was 3.10.

Stack Trace

Qt3DRender::Render::FrameCleanupJob::updateBoundingVolumesDebug :
Qt3DRender::Render::CalculateBoundingVolumeJob::CalculateBoundingVolumeJob :
Qt3DRender::Render::CalculateBoundingVolumeJob::CalculateBoundingVolumeJob :
Qt3DRender::Render::CalculateBoundingVolumeJob::CalculateBoundingVolumeJob :
Qt3DRender::Render::CalculateBoundingVolumeJob::run :
Qt3DRender::Render::CalculateBoundingVolumeJob::run :
Qt3DRender::Render::CalculateBoundingVolumeJob::CalculateBoundingVolumeJob :
QtConcurrent::ThreadEngineBase::startBlocking :
Qt3DRender::Render::FrameCleanupJob::updateBoundingVolumesDebug :
Qt3DRender::Render::CalculateBoundingVolumeJob::CalculateBoundingVolumeJob :
Qt3DRender::Render::CalculateBoundingVolumeJob::run :
Qt3DRender::Render::CalculateBoundingVolumeJob::run :
Qt3DRender::Render::CalculateBoundingVolumeJob::CalculateBoundingVolumeJob :
QtConcurrent::ThreadEngineBase::startBlocking :
Qt3DRender::Render::FrameCleanupJob::updateBoundingVolumesDebug :
Qt3DRender::Render::CalculateBoundingVolumeJob::CalculateBoundingVolumeJob :
Qt3DRender::Render::CalculateBoundingVolumeJob::run :
Qt3DRender::Render::CalculateBoundingVolumeJob::run :
Qt3DRender::Render::CalculateBoundingVolumeJob::CalculateBoundingVolumeJob :
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.16.4-Hannover
QGIS code revision: 654e76b3cb
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

**Comment by gioman** [comment]
@phipsch63 Can you please attach/link the data that causes the crash? Even better if you can also specify the 3D parameters you are using.

**Comment by phipsch63** [comment]
Please find attached the (main) SHP-File used for the 3D-visualization and the 3D-parameters

![3D-Config01](https://user-images.githubusercontent.com/79761510/111065030-da394500-84b7-11eb-8c1b-a9c197ee0be1.JPG)
![3D-Config02](https://user-images.githubusercontent.com/79761510/111065031-dad1db80-84b7-11eb-8cda-3aa6fb04db2a.JPG)
[Wohngebäude.zip](https://github.com/qgis/QGIS/files/6136454/Wohngebaude.zip)

**Comment by gioman** [comment]
> Please find attached the (main) SHP-File used for the 3D-visualization and the 3D-parameters

@phipsch63 cannot replicate on 3.18. Can you please test it? and  also use a new QGIS profile. If the problem persist please attach your projetc, to be sure we are using the very same parameters are you.

**Comment by gioman** [comment]
Closing for lack of feedback.
