### ISSUE TITLE
Vector Toolbar no longer working/empty

### ISSUE THREAD

**Issue by lydiagardiner** [qgis/QGIS#41902]
I've been creating buffers zones for site locations. I went to create a new site and buffer zone, however now when I click on the Vector button at the top, there's no options available. It no longer shows the geoprocessing/other options to choose from for vector analysis. I'm using the same version, and same project that has had previous buffers created.
![Screenshot (120)](https://user-images.githubusercontent.com/69530830/109393804-a557ba80-791b-11eb-9d5c-bea5496020a6.png)

**Comment by agiudiceandrea** [comment]
@lydiagardiner it seems that the "Processing" core plugin is disabled. Re enable it in order to see and use tools in the Vector menu.

**Comment by lydiagardiner** [comment]
> @lydiagardiner it seems that the "Processing" core plugin is disabled. Re enable it in order to see and use tools in the Vector menu.

Thank you so much - that worked!

**Comment by agiudiceandrea** [comment]
@lydiagardiner if this issue is fixed now for you, please close this bug report.
