### ISSUE TITLE
QGIS 3.18 crashes after georeferencer finishes 

### ISSUE THREAD

**Issue by rjstapel** [qgis/QGIS#41919]
**Description**
QGIS 3.18.0 (Mac 11.2.2) crashes immediately after the Georeferencer is finished. Both points and georeferenced map are stored on device and work properly when reloaded afterwards. The crash occurs both after using large raster files (200MB), as well as small ones (couple of KB).
I did not have any problems using QGIS 3.16, although strictly possible it could also be related to update from Mac OS 11.2.1. 

**Georeferencer settings**

<img width="441" alt="Schermafbeelding 2021-02-28 om 12 25 57" src="https://user-images.githubusercontent.com/7237326/109416936-94fa1b00-79c1-11eb-936e-69f86d937139.png">

Note that I checked the box 'load into QGIS', despite it being unchecked in the screenshot.

**QGIS and OS versions**

QGIS-versie | 3.18.0-Zürich | QGIS code revisie | b514863df1
-- | -- | -- | --
Gecompileerd tegen Qt | 5.14.2 | Gebruikt nu Qt | 5.14.2
Gecompileerd tegen GDAL/OGR | 3.2.1 | Gebruikt nu GDAL/OGR | 3.2.1
Gecompileerd tegen GEOS | 3.9.1-CAPI-1.14.2 | Gebruikt nu GEOS | 3.9.1-CAPI-1.14.2
Gecompileerd tegen SQLite | 3.31.1 | Uitgevoerd met SQLite | 3.31.1
Gecompileerd met PDAL | 2.2.0 | Uitgevoerd met PDAL | 2.2.0 (git-version: Release)
PostgreSQL Client Versie | 12.3 | SpatiaLite-versie | 4.3.0a
QWT versie | 6.1.4 | QScintilla2 Versie | 2.11.4
Gecompileerd tegen PROJ | 6.3.2 | Gebruikt nu PROJ | Rel. 6.3.2, May 1st, 2020
Versie OS | macOS 10.16 [**ACTUALLY, 11.2.2**]
Actieve plug-ins van Python | VectorBender; splitmultipart; polygon_linker; refFunctions; layer_selector; mmqgis; processing; db_manager; MetaSearch

**Comment by Cmattheou** [comment]
Same here. The progress indication stays idle and the resulting modified  file is useless
Attaching printscreen 
![Clipboard01](https://user-images.githubusercontent.com/52811209/109427678-2be3c900-79fc-11eb-80f8-df202332bd59.jpg)

**Comment by gioman** [comment]
Already reported several other times, and likely already fixed. Wait for 3.18.1
