### ISSUE TITLE
Point Symbol disappearing from legend

### ISSUE THREAD

**Issue by lucamanga** [qgis/QGIS#41937]
**Describe the bug**
When I add a PostGIS point layer, the symbol in legend disappears when I uncheck or check it. 
This appears when I enable or not the context based legend.

**How to Reproduce**

1. Add a PostGIS point layer
2. Uncheck the check mark of the layer
3. Legend disappears... forever

**QGIS and OS versions**

QGIS 3.16.4, Windows 7

**Comment by lucamanga** [comment]
This happens with a new created Geopackage file of points, with a simple symbol, also.

**Comment by gioman** [comment]
@lucamanga Can't confirm on QGIS 3.16.4 on Windows 10. 

Please try with a new QGIS profile, no 3rd party plugins installed.

If the problem persist please add a screencast that shows how you get this problem.

**Comment by lucamanga** [comment]
> If the problem persist please add a screencast that shows how you get this problem.

here is it:

https://nc.comune.trento.it/s/LZogeR7CwKdgjce

**Comment by gioman** [comment]
> here is it:

@lucamanga have you tried on a new QGIS profile?

**Comment by gioman** [comment]
> here is it:
> 
> https://nc.comune.trento.it/s/LZogeR7CwKdgjce

@lucamanga can't replicate. You also forgot to mention the "digitize a few features" step in your description (maybe it does not matter at all, but anyway could be important).

**Comment by lucamanga** [comment]
> > here is it:
> 
> @lucamanga have you tried on a new QGIS profile?

Yes, with no plugins loaded. On Windows 7.

**Comment by lucamanga** [comment]
> > here is it:
> > https://nc.comune.trento.it/s/LZogeR7CwKdgjce
> 
> @lucamanga can't replicate. You also forgot to mention the "digitize a few features" step in your description (maybe it does not matter at all, but anyway could be important).

Yes, it's not important. This bug happens when loading a project, too.

**Comment by gioman** [comment]
> Yes, it's not important. This bug happens when loading a project, too.

@lucamanga can you try on a different machine?

**Comment by lucamanga** [comment]
> > Yes, it's not important. This bug happens when loading a project, too.
> 
> @lucamanga can you try on a different machine?

Tried on a Windows 10 (instead of two windows 7 PCs affecting this issue), it is working.

Maybe it's a QT bug ?

**Comment by gioman** [comment]
> Maybe it's a QT bug ?

@lucamanga maybe. Also I'm pretty sure that we do not support anymore Windows 7... so I don't really think that this would get any attention.

**Comment by lucamanga** [comment]
> > Maybe it's a QT bug ?
> 
> @lucamanga maybe. Also I'm pretty sure that we do not support anymore Windows 7... so I don't really think that this would get any attention.

Ok: I think that in the qgis.org website is not precise. It states that it supports "Windows", whatever version...

**Comment by kikislater** [comment]
Could you try with another windows theme. This theme is well know to have tearing and no gpu acceleration

**Comment by lucamanga** [comment]
> Could you try with another windows theme. This theme is well know to have tearing and no gpu acceleration

I changed to "windowsvista" style and "blend of gray" iconset. It's more weird: when I move the mouse into Layer list, the symbol disappears; but when I go to the map, it reappears...

**Comment by kikislater** [comment]
Is this an Aero theme ? You need to test with an aero theme. Is this in Virtual Machine ?

**Comment by lucamanga** [comment]
> Is this an Aero theme ? You need to test with an aero theme. Is this in Virtual Machine ?

No, it's in Remote desktop. Tomorrow I'll test it in "presence".

**Comment by lucamanga** [comment]
I have further investigated: Yes, Aero is enabled
Then I tried to use QGIS standing on the front of the PC. The bug is disappeared: it seems a remote desktop bug in windows 7. This doesn't affect on windows 10 remote desktop.

Thank you for attention.

**Comment by kikislater** [comment]
In some remonte desktop app, it changes to classic theme. Could you share your remote desktop software ?

**Comment by lucamanga** [comment]
> In some remote desktop app, it changes to classic theme. Could you share your remote desktop software ?

xfreerdp but it happens with the standard windows remote desktop, too.

**Comment by kikislater** [comment]
If you are in linux (xfreerdp) you could try to use remmina with rdesktop plugin instead of freerdp. You could also try to adjust your parameters freerdp and rdesktop have some ...
