### ISSUE TITLE
Perte de la géométrie d'une couche shape

### ISSUE THREAD

**Issue by mwohlNCA** [qgis/QGIS#41946]
Bonjour, nous rencontrons un problème récurrent avec nos couches vecteurs. Nous éditons des couches vecteur en mode édition. Une fois les modifications réalisées, nous enregistrons les modifications et enlevons le mode édition. C'est là que le problème intervient. Une fois les modifications enregistrées la géométrie de la couche vecteur disparaît. La table attributaire est elle toujours présente. Cependant les entités n'ont plus de géométrie. Ce problème apparaît lorsque nos couches sont sauvegardées sur le serveur de l'entreprise. Après des recherches sur internet il s'avère que d'autres entreprises possèdent le même problème. Serait il possible de savoir quel est le problème car cela nous perturbe fortement. Merci à vous. 
Voici en pièce jointe une capture d'écran de l'erreur obtenue: 

![image_2021_02_22T16_37_16_197Z](https://user-images.githubusercontent.com/79859135/109523445-a91c4600-7aaf-11eb-895a-67cecd5708bd.png)

Mathys WOHL
SIG NCA Environnement

**Comment by gioman** [comment]
@mwohlNCA hi, tickets must be filed in English. Also the following infos are mandatory:




**Describe the bug**


**How to Reproduce**



1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error -->

**QGIS and OS versions**



**Additional context**
