### ISSUE TITLE
Cannot import CSV with delimited text tool if path contains special chars

### ISSUE THREAD

**Issue by wmeinolf** [qgis/QGIS#41948]
Since update to 3.18 no Delimited Text Layer can be importet from txt file. Error is "layer is not valid".  I'm on Windows 10.. Import still workes w/o any problem on 3.16.3 running on UBUNTU VM, although the path also contains special character:
/home/wm/Schreibtisch/WMeinolf/Geodaten 2017/Thüringen/Hauskoordinaten Thüringen Stand 2018-03-15/2020-03-17-adressen-th-mitKopf.txt. Data are in a plain txt file containing German Umlaute, special Characters äöüß and is UTF-8 coded. Earlier today I could import a Excel exported CSV without issues.

Fresh profile does NOT help!

**How to Reproduce**
Put txt file to import in a folder, which name contains special german character ä, ö, ü or ß.

**QGIS and OS versions**

QGIS-Version | 3.18.0-Zürich | QGIS-Codeversion | bdef9fb328
-- | -- | -- | --
Kompiliert gegen Qt | 5.11.2 | Laufendes Qt | 5.11.2
Kompiliert mit GDAL/OGR | 3.1.4 | Läuft mit GDAL/OGR | 3.1.4
Kompiliert mit GEOS | 3.8.1-CAPI-1.13.3 | Läuft mit GEOS | 3.8.1-CAPI-1.13.3
Kompiliert mit SQLite | 3.29.0 | Läuft mit SQLite | 3.29.0
PostgreSQL-Client-Version | 11.5 | SpatiaLite-Version | 4.3.0
QWT-Version | 6.1.3 | QScintilla2-Version | 2.10.8
Kompiliert mit PROJ | 6.3.2 | Läuft mit PROJ | Rel. 6.3.2, May 1st, 2020
BS-Version | Windows 10 (10.0)
Aktive Python-Erweiterungen | alkisplugin; closest_points; disconnected-islands; ImportPhotos; joinmultiplelines; lizmap; meinotestplugin; mmqgis; networks; ORStools; pluginbuilder3; plugin_reloader; qchainage; qgis-bulk-nominatim-master; Qgis2threejs; qgis2web; QuickOSM; refFunctions; db_manager; MetaSearch; processing

**Additional context**

Test data alreads uploaded under this case: #41924

**Comment by mattbeets** [comment]
The same seems to be the problem for Danish æ, ø, å, (at least for a file path containing an ø), so maybe this is a general unicode/UTF-8 problem for the file path?

**Comment by rocketfinger** [comment]
the same problem with polish characters.

**Comment by nirvn** [comment]
I can confirm this bad regression.
