### ISSUE TITLE
Add geometry types to ShapeFile Layers

### ISSUE THREAD

**Issue by mattfack** [qgis/QGIS#41944]
It would be useful to have the same geometry types for ShapeFile Layers as the ones related to Geopackage or Termporary Scratch Layers.

**Comment by gioman** [comment]
> It would be useful to have the same geometry types for ShapeFile Layers as the ones related to Geopackage or Termporary Scratch Layers.

@mattfack what do you mean? what geom types are you missing?

**Comment by mattfack** [comment]
For instance, LineString is missing (as I mentioned in #41945 ).
Some plugins (such as crayfish) require the user to use LineString, not MultiLineString, thus making it impossible to use ShapeFile Layers.

I know, one can use Geopackage Layer (and this is what I do), but it might be nice to have the same possibilities for ShapeFile Layers as for the other types.

You mentioned on #41945 that it is by design, what does it mean?

**Comment by gioman** [comment]
> You mentioned on #41945 that it is by design, what does it mean?

@mattfack that is a programming choice to threat all geoms in a shapefile as multi.

**Comment by gioman** [comment]
With the exception of points I think, where you can actually choose between point and multipoint.

**Comment by mattfack** [comment]
Ok, I didn't know. 
Can I leave the feature request or should I close it?

**Comment by gioman** [comment]
>  Can I leave the feature request or should I close it?

we should close it, as said this was a design choice.

**Comment by mattfack** [comment]
Ok, I wish I could say something to design choices :)

**Comment by agiudiceandrea** [comment]
@mattfack the [shapefiles format](https://www.esri.com/content/dam/esrisites/sitecore-archive/Files/Pdfs/library/whitepapers/pdfs/shapefile.pdf) doesn't have separate types for Linestring and MultiLinestring. It only has a PolyLine type which allows to store indifferently one or more part for each feature geometry: "PolyLine A PolyLine is an ordered set of vertices that consists of one or more parts."

**Comment by gioman** [comment]
> Ok, I wish I could say something to design choices :) 

@mattfack QGIS is open source, and its developments are also open, so bottom line is that you have a say, if you want.
