### ISSUE TITLE
new ShapeFile layer LineString is MultiLineString

### ISSUE THREAD

**Issue by mattfack** [qgis/QGIS#41945]
**Description**
When creating a new ShapeFile Layer, and selecting LineString as feature type, QGIS generates a MultiLineString.

**How to Reproduce**

1. Go to Layer\Create Layer\ New ShapeFile Layer
2. Select a File name, encoding is UTF-8 as default
3. under Geometry type select LineString
4. Click ok
5. Double click the layer to open layer properties
6. Under geometry there should be Line (MultiLineString)

**QGIS and OS versions**

QGIS version
3.18.0-Zürich
QGIS code revision
bdef9fb328
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
basemesh; 
crayfish; 
processing_wbt; 
profiletool; 
qdraw; 
db_manager; 
MetaSearch; 
processing

**Additional context**

1. When converting a Temporary Scratch Layer or a Geopackage Layer to Esri Shape, the geomtry type is converted (from LineString to MultiLineString), too.
2. Temporary Scratch Layers and Geopackage Layers does not have this problem because they have more feature types available. See feature request #41944

**Comment by gioman** [comment]
@mattfack this is by design.

**Comment by mattfack** [comment]
I assume we cannot say anything concerning design choices?

**Comment by mattfack** [comment]
Closing as #41944

**Comment by nyalldawson** [comment]
@mattfack 
> I assume we cannot say anything concerning design choices?

It's actually a design decision made by ESRI in the shapefile specification -- so no, there's nothing we can do :laughing:  Shapefiles don't have any concept of single vs multi geometries for lines or polygons, so effectively every line/polygon shapefile is a multiline/multipolygon.

The solution is to use a different format if you're needed strict type constraints on line or polygon geometries.

**Comment by mattfack** [comment]
Thanks @nyalldawson 

(btw awesome job with those color gradients!)
