### ISSUE TITLE
QGIS crash when exporting DXF

### ISSUE THREAD

**Issue by gdeneyer** [qgis/QGIS#41940]
**Describe the bug**
## User Feedback

Keep happening each time I try to export a DXF file

## Report Details

**Crash ID**: [4d700434d3e0fb460c9a81b63f4166661261d5f8](https://github.com/qgis/QGIS/search?q=4d700434d3e0fb460c9a81b63f4166661261d5f8&type=Issues)

**Stack Trace**
<pre>
QHash<QModelIndex,QHashDummyValue>::clear qhash.h:591
QgsVectorLayerAndAttributeModel::applyVisibilityPreset qgsdxfexportdialog.cpp:360
QgsDxfExportDialog::mVisibilityPresets_currentIndexChanged qgsdxfexportdialog.cpp:512
QMetaObject::activate :
QWidgetLineControl::`default constructor closure' :
QComboBox::setCurrentIndex :
QComboBox::setCurrentIndex :
QWidgetLineControl::`default constructor closure' :
QMetaObject::activate :
QAbstractItemModel::endInsertRows :
QStandardItemModel::insertRows :
QComboBox::insertItems :
QgsDxfExportDialog::QgsDxfExportDialog qgsdxfexportdialog.cpp:484
QgisApp::dxfExport qgisapp.cpp:7356
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:471
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:471
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1637
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.18.0-Z�rich
QGIS code revision: bdef9fb328
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**How to Reproduce**

4. See error -->

**QGIS and OS versions**

**Additional context**

**Comment by gioman** [comment]
Already reported several time, already fixed, please wait 3.18.1 or downgrade.

**Comment by gdeneyer** [comment]
Hello, 

Sorry this message comes afterwards. I am brand new using Qgis, I use it to manipulate SHP datas (urban data from my city). The import is going wel. 

EDIT : thanks for your answer. 

Gilles

**Comment by gdeneyer** [comment]
Hello,

Thank you Giovanni, sorry I followed the instructions on QGIS to ask to
report the bug.

Best regards,
Gilles

Le lun. 1 mars 2021 à 12:29, Giovanni Manghi <notifications@github.com> a
écrit :

**Comment by gioman** [comment]
> Thank you Giovanni, sorry I followed the instructions on QGIS to ask to report the bug.

@gdeneyer no problem, just remember to search first if there are similar reports.
