### ISSUE TITLE
QGIS crashes on clicking "Set Filter" when connecting to a Spatialite DB with no table selected

### ISSUE THREAD

**Issue by keenanpepper** [qgis/QGIS#41950]
It seems like the first time you connect to a spatialite DB, the "Set Filter" button is disabled until you select a table. However, if you change to a different DB, the "Set Filter" button remains enabled and clicking it causes a crash.

Version: 3.16.3-Hannover on macOS Catalina 10.15.7

Steps to reproduce:

1. Get two different spatialite DBs that you can connect to. I tried with two very simple single-table DBs with one triangle polygon each, and that worked to repro this bug.
2. Open QGIS
3. Open Data Source Manager
4. Open A.sqlite with "New" and connect to it
5. Select a table of A.sqlite, note "Set Filter" becomes enabled
6. Open B.sqlite and connect to it, do **NOT** select any table
7. Note that "Set Filter" remains enabled (this seems wrong of course because after connecting to a new datasource no table is selected)
8. Click "Set Filter", observe QGIS crash

Expected behavior: in step 7 "Set Filter" should be disabled so you can't click on it.
Actual behavior: QGIS crashes. I can supply the whole stacktrace if needed but the top line is:
`0   libspatialiteprovider.so      	0x000000012e209511 QgsSpatiaLiteSourceSelect::setSql(QModelIndex const&) + 177`

**Comment by rduivenvoorde** [comment]
@keenanpepper can you add the small spatialite db's to this issue?
It's just easier to just download them, instead of creating them....

**Comment by gioman** [comment]
> Steps to reproduce:
> 
>     1. Get two different spatialite DBs that you can connect to. I tried with two very simple single-table DBs with one triangle polygon each, and that worked to repro this bug.
> 
>     2. Open QGIS
> 
>     3. Open Data Source Manager
> 
>     4. Open A.sqlite with "New" and connect to it [note "Set Filter" is disabled]
> 
>     5. Select a table of A.sqlite [note "Set Filter" becomes enabled]
> 
>     6. Open B.sqlite and connect to it [note "Set Filter" remains enabled - this seems wrong]
> 
>     7. Click "Set Filter"

@keenanpepper I tried to replicate this steps on a clean 3.16.4 on macOS Catalina and no crash.

Either is a local issue OR I'm not doing the exact steps needed to replicate. It seems to me that the described steps could miss something important. It would be really useful if you can post a screencast of the whole process that leads to a crash in your case.

**Comment by keenanpepper** [comment]
spatialite files
[Archive.zip](https://github.com/qgis/QGIS/files/6069686/Archive.zip)

**Comment by gioman** [comment]
@keenanpepper Ok I replicated, I will edit your steps because it may not be 100% clear how to replicate.

**Comment by gioman** [comment]
Affects also Linux.

**Comment by keenanpepper** [comment]
Thank you, I was about to upload a screen recording but it wouldn't let me attach my first try since it was over 10MB.

**Comment by gioman** [comment]
> Affects also Linux.

Also Windows. Steps to replicate updated.

**Comment by keenanpepper** [comment]
This actually caused me to lose a few hours of work because I (foolishly) had a bunch of temporary memory layers open. Great that somebody else can repro it!
