### ISSUE TITLE
Cannot add a polymorphic relations

### ISSUE THREAD

**Issue by troopa81** [qgis/QGIS#41959]
**Describe the bug**

Nothing happen when I try to create a Polymorphic Relation with the given project

**How to Reproduce**

1. Create PostGIS database and intialize it with the following instructions

```sql
# poly_relations
create table docs ( id serial primary key , filepath  varchar ); 

insert into docs (filepath) values ('pipe_photo1.jpg');
insert into docs (filepath) values ('pipe_photo2.jpg');
insert into docs (filepath) values ('pipe_manual.pdf');
insert into docs (filepath) values ('manhole_photo1.jpg');
insert into docs (filepath) values ('manhole_photo2.jpg');
insert into docs (filepath) values ('manhole_manual.pdf');
insert into docs (filepath) values ('manhole_model.dwg');

create table pipe (  id serial primary key, name varchar );
insert into pipe (name) values ('nom d une pipe');
insert into pipe (name) values ('ceci n est pas une pipe');

create table manhole (  idmh serial primary key, name varchar ); 
insert into manhole (name) values('manhole1');
insert into manhole (name) values('manhole2');

create table obj2doc ( idobj integer, objtable varchar, iddoc integer, 
CONSTRAINT fk_doc  FOREIGN KEY(iddoc) REFERENCES docs(id));

insert into obj2doc values ( 1, 'pipe', 1 );
insert into obj2doc values ( 1, 'pipe', 3 );
insert into obj2doc values ( 2, 'pipe', 2 );
insert into obj2doc values ( 2, 'pipe', 3 );
insert into obj2doc values ( 1, 'manhole', 4 );
insert into obj2doc values ( 1, 'manhole', 6 );
insert into obj2doc values ( 2, 'manhole', 7 );
insert into obj2doc values ( 2, 'manhole', 5 );
insert into obj2doc values ( 2, 'manhole', 6 );
```

2. Open the following project [poly_relations.tar.gz](https://github.com/qgis/QGIS/files/6066448/poly_relations.tar.gz)
3. Try to add a polymorphic relation with the following configuration parameters
![polyrelations](https://user-images.githubusercontent.com/14358135/109605582-a8be9200-7b25-11eb-8675-71bdcbc16460.png)
4. Select OK
5. No relations has been added

**QGIS and OS versions**

Debian bullseye
QGIS a90e3e349a

**Additional context**

**Comment by gioman** [comment]
@troopa81 is this a regression or is just a functionality that never worked as expected?

**Comment by troopa81** [comment]
> @troopa81 is this a regression or is just a functionality that never worked as expected?

More the second, polymorphic relation is a new feature that appears in 3.18 I think

**Comment by gioman** [comment]
> More the second, polymorphic relation is a new feature that appears in 3.18 I think

@troopa81 do you remember who developed this? I don't remember and can't find now.

**Comment by troopa81** [comment]
The feature was brought essentially by these two PRs #40914 and #41009

**Comment by gioman** [comment]
> The feature was brought essentially by these two PRs #40914 and #41009

@suricactus ping

**Comment by suricactus** [comment]
Earlier today I have observed the same on 3.18, but not on master. I will have look now.

**Comment by suricactus** [comment]
Okay, here the problem is that the `manhole` layer does not have `id` column, but `idmh`. I will open a PR where this kind of feedback is being shown to the user.

**Comment by troopa81** [comment]
Thanks @3nids
