### ISSUE TITLE
Clip Raster by Extent on http ImageServer source fails

### ISSUE THREAD

**Issue by maphew** [qgis/QGIS#41956]
**Describe the bug**
The command passed to `gdal_translate` is formatted so that Gdal interprets parameters as a filename.

>ERROR 4: ` crs='EPSG:32145' format='JPGPNG' url='https://maps.vcgi.vermont.gov/arcgis/rest/services/EGC_services/IMG_VCGI_CLR_SP_CACHE/ImageServer'' does not exist in the file system, and is not recognized as a supported dataset name.

**How to Reproduce**

1. Add image service layer to project, `https://maps.vcgi.vermont.gov/arcgis/rest/services/EGC_services/IMG_VCGI_CLR_SP_CACHE/ImageServer`
2. Zoom to a smaller extent
3. Menu:  _Raster >> Extraction >> Clip Raster by Extent_
4. set _[Clipping extent]_ to _Map canvas_
5. Run

**Log**
~~~
QGIS version: 3.18.0-Zürich
QGIS code revision: bdef9fb328
Qt version: 5.11.2
GDAL version: 3.1.4
GEOS version: 3.8.1-CAPI-1.13.3
PROJ version: Rel. 6.3.2, May 1st, 2020
Processing algorithm…
Algorithm 'Clip raster by extent' starting…
Input parameters:
{ 'DATA_TYPE' : 0, 'EXTRA' : '', 'INPUT' : 'crs=\'EPSG:32145\' format=\'JPGPNG\' url=\'https://maps.vcgi.vermont.gov/arcgis/rest/services/EGC_services/IMG_VCGI_CLR_SP_CACHE/ImageServer\'', 'NODATA' : None, 'OPTIONS' : '', 'OUTPUT' : 'd:\\output.tif', 'OVERCRS' : False, 'PROJWIN' : '459944.320700000,461447.154000000,212120.203800000,213231.453800000 [EPSG:32145]' }

GDAL command:
gdal_translate -projwin 459944.3207 213231.4538 461447.154 212120.2038 -of GTiff " crs='EPSG:32145' format='JPGPNG' url='https://maps.vcgi.vermont.gov/arcgis/rest/services/EGC_services/IMG_VCGI_CLR_SP_CACHE/ImageServer'" d:\output.tif
GDAL command output:
ERROR 4: ` crs='EPSG:32145' format='JPGPNG' url='https://maps.vcgi.vermont.gov/arcgis/rest/services/EGC_services/IMG_VCGI_CLR_SP_CACHE/ImageServer'' does not exist in the file system, and is not recognized as a supported dataset name.
Process returned error code 1
Execution completed in 0.20 seconds
Results:
{'OUTPUT': 'd:\\output.tif'}

Loading resulting layers
The following layers were not correctly generated.
• d:\output.tif
You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.
~~~

**Other info**
From a command shell I tried various changes in the commandline, balancing quotes, changing single `'` for `"` and so one, without success. So I'm not sure the fault lies with Qgis. 

~~~
>gdal_translate -projwin 459944.3207 213231.4538 461447.154 212120.2038 -of GTiff "https://maps.vcgi.vermont.gov/arcgis/rest/services/EGC_services/IMG_VCGI_CLR_SP_CACHE/ImageServer" output.tif
ERROR 4: `C:\Users\Matt\AppData\Local\Temp\ImageServer' not recognized as a supported file format.
~~~

I tried creating an WMS.XML file following the example at end of https://gdal.org/drivers/raster/wms.html. Using that works in that gdal_translate completes successfully and creates an image of the expected size and location, but the pixels are all `0`.

~~~
>gdal_translate "https://maps.vcgi.vermont.gov/arcgis/rest/services/EGC_services/IMG_VCGI_CLR_SP_CACHE/ImageServer?f=json" -of wms vt_svc_satimg-rgb.xml
Input file size is 8388608, 8388608

>gdal_translate -projwin 459944.3207 213231.4538 461447.154 212120.2038 vt_svc_satimg-rgb.xml xxx.tif
Input file size is 8388608, 8388608
0...10...20...30...40...50...60...70...80...90...100 - done.

>gdalinfo -mm xxx.tif
Driver: GTiff/GeoTIFF
Files: xxx.tif
Size is 31020, 22938
Coordinate System is:
[...snip...]
Corner Coordinates:
Upper Left  (  459944.276,  213231.502) ( 73d 0'10.70"W, 44d25' 5.55"N)
Lower Left  (  459944.276,  212120.230) ( 73d 0'10.40"W, 44d24'29.54"N)
Upper Right (  461447.094,  213231.502) ( 72d59' 2.77"W, 44d25' 5.84"N)
Lower Right (  461447.094,  212120.230) ( 72d59' 2.48"W, 44d24'29.84"N)
Center      (  460695.685,  212675.866) ( 72d59'36.59"W, 44d24'47.69"N)
Band 1 Block=31020x1 Type=Byte, ColorInterp=Red
    Computed Min/Max=0.000,0.000
Band 2 Block=31020x1 Type=Byte, ColorInterp=Green
    Computed Min/Max=0.000,0.000
Band 3 Block=31020x1 Type=Byte, ColorInterp=Blue
    Computed Min/Max=0.000,0.000
~~~

**What does work** for the same source is ___Save Raster Layer as___. However it's non-optimal (for me) as it's very clicky and can't be batched, but more importantly: can't save the command line to my notes so I can reproduce later.

**Comment by gioman** [comment]
> So I'm not sure the fault lies with Qgis.

@maphew it is not. The QGSI GDAL tools are just a GUI for the GDAL command line utilities. In those utilities you cannot use remote services directly as inputs. You can use the https://gdal.org/drivers/raster/wms.html trick, but then you have to tweak the tool/command parameters to get what you need exactly.

In your example

`gdal_translate -projwin 459944.3207 213231.4538 461447.154 212120.2038 vt_svc_satimg-rgb.xml xxx.tif`

returns

`Warning 1: Computed -srcwin 1.15239e+08 1.0489e+08 31020 22938 falls completely outside raster extent. Going on however.`

which explains why you are not getting what you want.
