### ISSUE TITLE
Expose more Proj's get_factors function through QgsCoordinateTransform or another API

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#41952]
**Feature description.**
I would love to use [Proj's get_factors](https://proj.org/development/reference/functions.html?highlight=proj_factors#c.proj_factors) function but it is not exposed by QGIS' Proj-ish QgsCoordinateTransform or any other API as I know of.

**Additional context**
I would like to release a rewrite of https://github.com/dtutic/ProjFactors but am stuck because of this. While it is possible to use the function via `pyproj`, you need to use a QGIS that is built using the same Proj version as the `pyproj` you end up importing or everything will crash (ref https://github.com/qgis/QGIS/issues/37289)

There might be more functions of Proj suitable for inclusion, I did not check for that.

<3

**Comment by nyalldawson** [comment]
I tried to do this a while back as https://github.com/nyalldawson/QGIS/commit/8663ba775712e5a55c02c71c3b52c3abd414c2b6 -- but could never actually get the proj_factors call at https://github.com/nyalldawson/QGIS/commit/8663ba775712e5a55c02c71c3b52c3abd414c2b6#diff-3dc1305de83b6ca192f89aa8cb74d4ecb8e5f935ea3dff5d0941cb558775669bR298 to return a valid result. Maybe you can spot what I'm missing?

**Comment by kannes** [comment]
Thanks so much!

I am clueless when it comes to C++ so it is hard for me to spot bugs. A quick swap between lat and lon is probably not the issue, right? Or some wrong numeric data type?

The `2222` in https://github.com/nyalldawson/QGIS/commit/8663ba775712e5a55c02c71c3b52c3abd414c2b6#diff-4f213ae1d21039214df40d1c7f83bc76d0b7e62cd570c7e197556c5134144f97R27 is just a placeholder, right?

I am no expert in projection factors so the only test I feel quite confident about is the middle meridian of a UTM zone having a scale factor of 0.9996.

>>> from pyproj import Proj
>>> Proj("epsg:25832").get_factors(9, 0)

gives me a meridional_scale=0.9996000000506514 which looks correct. So maybe that would be a first test case. :)

**Comment by kannes** [comment]
Awesome! Do you know what the problem ended up being?

**Comment by nyalldawson** [comment]
@kannes 

I was originally trying to retrieve the factors for a CRS object, when you can only do it for a projection object...
