### ISSUE TITLE
QGIS crashes on a simple project when labels are enabled

### ISSUE THREAD

**Issue by FranRico** [qgis/QGIS#41968]
## User Feedback

WHILE DIGITIZING SHP POLIGON LAYER QGIS UNEXPECTEDLY ENDED. JUST MOMENT BEFORE I LOAD TRACKS AND WAYPOINTS FROM GPX FILES. WMS TOPOGRAPHIC LAYER WAS LOADED AS WELL. 

## Report Details

**Crash ID**: [dd7daf46120b177aa3e75017b9a1d588248c1c0d](https://github.com/qgis/QGIS/search?q=dd7daf46120b177aa3e75017b9a1d588248c1c0d&type=Issues)

**Stack Trace**
<pre>
GEOSEquals_r :
GEOSEquals_r :
QgsGeos::shortestLine qgsgeos.cpp:2274
QgsGeometry::shortestLine qgsgeometry.cpp:636
<lambda_098e6f315b0c35646bc666a71ce10ce8>::operator() qgscallout.cpp:473
QgsSimpleLineCallout::draw qgscallout.cpp:539
QgsCallout::render qgscallout.cpp:143
QgsVectorLayerLabelProvider::drawCallout qgsvectorlayerlabelprovider.cpp:333
QgsVectorLayerLabelProvider::drawLabelBackground qgsvectorlayerlabelprovider.cpp:311
QgsLabelingEngine::drawLabels qgslabelingengine.cpp:427
QgsDefaultLabelingEngine::run qgslabelingengine.cpp:561
QgsMapRendererJob::drawLabeling qgsmaprendererjob.cpp:1002
QgsMapRendererParallelJob::renderLabelsStatic qgsmaprendererparalleljob.cpp:399
QtConcurrent::RunFunctionTask<void>::run qtconcurrentrunbase.h:136
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.16.4-Hannover
QGIS code revision: 654e76b3cb
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

**Comment by FranRico** [comment]
## User Feedback

WHILE ZOOMING WMS LAYER IT CRASHED, I ZOOM QUICKLY AND BEFORE THE FIRST ZOOM OF THE WMS LAYER HAS BEEN CHARGED

## Report Details

**Crash ID**: [dd7daf46120b177aa3e75017b9a1d588248c1c0d](https://github.com/qgis/QGIS/search?q=dd7daf46120b177aa3e75017b9a1d588248c1c0d&type=Issues)


**Stack Trace**
<pre>
GEOSEquals_r :
GEOSEquals_r :
QgsGeos::shortestLine qgsgeos.cpp:2274
QgsGeometry::shortestLine qgsgeometry.cpp:636
<lambda_098e6f315b0c35646bc666a71ce10ce8>::operator() qgscallout.cpp:473
QgsSimpleLineCallout::draw qgscallout.cpp:539
QgsCallout::render qgscallout.cpp:143
QgsVectorLayerLabelProvider::drawCallout qgsvectorlayerlabelprovider.cpp:333
QgsVectorLayerLabelProvider::drawLabelBackground qgsvectorlayerlabelprovider.cpp:311
QgsLabelingEngine::drawLabels qgslabelingengine.cpp:427
QgsDefaultLabelingEngine::run qgslabelingengine.cpp:561
QgsMapRendererJob::drawLabeling qgsmaprendererjob.cpp:1002
QgsMapRendererParallelJob::renderLabelsStatic qgsmaprendererparalleljob.cpp:399
QtConcurrent::RunFunctionTask<void>::run qtconcurrentrunbase.h:136
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>


**QGIS Info**
QGIS Version: 3.16.4-Hannover
QGIS code revision: 654e76b3cb
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

**Comment by FranRico** [comment]
## User Feedback

Now it's crashed while zooming out with only a vector layer loaded. It crashed when I reached above 1:100.000 scale. (Before that I had used the 3.1415 Qgis version and crashed as well)

## Report Details

**Crash ID**: [dd7daf46120b177aa3e75017b9a1d588248c1c0d](https://github.com/qgis/QGIS/search?q=dd7daf46120b177aa3e75017b9a1d588248c1c0d&type=Issues)


**Stack Trace**
<pre>
GEOSEquals_r :
GEOSEquals_r :
QgsGeos::shortestLine qgsgeos.cpp:2274
QgsGeometry::shortestLine qgsgeometry.cpp:636
<lambda_098e6f315b0c35646bc666a71ce10ce8>::operator() qgscallout.cpp:473
QgsSimpleLineCallout::draw qgscallout.cpp:539
QgsCallout::render qgscallout.cpp:143
QgsVectorLayerLabelProvider::drawCallout qgsvectorlayerlabelprovider.cpp:333
QgsVectorLayerLabelProvider::drawLabelBackground qgsvectorlayerlabelprovider.cpp:311
QgsLabelingEngine::drawLabels qgslabelingengine.cpp:427
QgsDefaultLabelingEngine::run qgslabelingengine.cpp:561
QgsMapRendererJob::drawLabeling qgsmaprendererjob.cpp:1002
QgsMapRendererParallelJob::renderLabelsStatic qgsmaprendererparalleljob.cpp:399
QtConcurrent::RunFunctionTask<void>::run qtconcurrentrunbase.h:136
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>


**QGIS Info**
QGIS Version: 3.16.4-Hannover
QGIS code revision: 654e76b3cb
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

**Comment by nirvn** [comment]
You can turn off your caps lock, it'll like won't get you very far. What you could do is provide a test case that replicates the crash (it seems you've gotten things down to one layer so that should be easy). Just zip a .qgs with the dataset and add it to the ticket.

Cheers.

**Comment by Gustry** [comment]
You should try with a new QGIS profile.
https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles

**Comment by nirvn** [comment]
Looking at the stack trace, crash seems to be linked to label callouts. Do you have those enabled on your vector layer? If so, try to disable it and see if the crash is gone. Report your findings afterward.

**Comment by FranRico** [comment]
Hello Mathieu. Sorry for the caps, I did not notice that. Thanks for the advise.
And thank you Étienne as well. 
I will try to do as you both have said.
Regards,
Fran.

**Comment by FranRico** [comment]
Yes I was, Mathieu. The layer was showing labels. I am trying your suggestion. Thanks!

**Comment by FranRico** [comment]
It works fine with labels disabled.
Many thanks for your help guys.
Regards,
Fran.

**Comment by nirvn** [comment]
@FranRico , don't run away too quickly ;) can you attach a test project to replicate the crash?

**Comment by FranRico** [comment]
Jejejeje Yes, of course. I'll do it right away.

**Comment by FranRico** [comment]
Here it is the file. 

Let me know if you may need something else. I will be pleased to help as long as I can.

Regards,

Fran.

[qgis_crash.zip](https://github.com/qgis/QGIS/files/6068706/qgis_crash.zip)

**Comment by gioman** [comment]
Crash confirmed on master/linux too.
