### ISSUE TITLE
Cell statistic algorithm name() should not be translatable

### ISSUE THREAD

**Issue by nicogodet** [qgis/QGIS#41977]
https://github.com/qgis/QGIS/blob/6af2bd36b1107e575331d24782f8101afa13c88b/src/analysis/processing/qgsalgorithmcellstatistics.cpp#L164-L167
It should be `return QStringLiteral( "cellstatistics" );`
Otherwise we end up with :
```
outputs['StatistiquesDeLaCellule'] = processing.run('native:Statistiques de la cellule', <- translated name here...
                                                     alg_params,
                                                     context=context,
                                                     feedback=feedback,
                                                     is_child_algorithm=True
)
``` 
in processing script...

@gioman tell me if you want me to fill in the issue template but I'm not sure it's needed here...

**Comment by gioman** [comment]
> @gioman tell me if you want me to fill in the issue template but I'm not sure it's needed here...

@nicogodet no need.

**Comment by nicogodet** [comment]
If this is the only line that should be changed to fix this issue, I can propose a PR with github web interface.

**Comment by gioman** [comment]
> I can propose a PR with github web interface.

@nicogodet most welcome.
