### ISSUE TITLE
Decimal separators in Processing are now shown with commas instead of dots

### ISSUE THREAD

**Issue by talledodiego** [qgis/QGIS#41980]
Hi everyone,
I think there is a problem with localization that I noticed between version 3.14 and 3.18 (I did not try with 3.16, I can try it if needed):
when using the command "use layer extent " for instance in rasterize, or other tools, the string has commas as decimal points (my localization is Italian) and also as separation between numbers. In QGIS 3.14 the decimal point was used.
See the following screenshot for QGIS 3.14:
![image](https://user-images.githubusercontent.com/38036285/109713487-92561c00-7ba1-11eb-9e9b-19764764c201.png)

and QGIS 3.18:
![image](https://user-images.githubusercontent.com/38036285/109713543-a26dfb80-7ba1-11eb-8e75-5ad7f15b70d1.png)

If I don't touch anything it works anyway, but if for instance I need to change one of the numbers, I need to change manually the four commas.

Is this an intended behavior? Or is it a bug?

**Comment by elpaso** [comment]
It's a bug.

**Comment by gioman** [comment]
@elpaso this is a consequence of some later change? @SrNetoChan

**Comment by SrNetoChan** [comment]
It might. I will check if a commit I did was the culprit.

**Comment by agiudiceandrea** [comment]
@SrNetoChan a side effect of https://github.com/qgis/QGIS/pull/41316?
Since the decimal separator should be used according to Locale (so it could be possible the decimal separator is a comma), maybe a character different from comma or point should be used to separate the parts of the extent: a space or a semicolon...

**Comment by SrNetoChan** [comment]
> @SrNetoChan a side effect of #41316?
> Since the decimal separator should be used according to Locale (so it could be possible the decimal separator is a comma), maybe a character different from comma or point should be used to separate the parts of the extent: a space or a semicolon...
> Or an exception should be made for the extent string, where the decimal separator must be always the decimal point.
@agiudiceandrea Yes, it might be it. I agree that we should use something different for separating the values, even if it's not because of this bug, visually it looks really ugly and confusing to have 7 commas.
