### ISSUE TITLE
2 adds for plugin ImportPhotos

### ISSUE THREAD

**Issue by drugstorer-172** [qgis/QGIS#41999]
Sorry wrong place.

Gerhard

**Comment by Gustry** [comment]
This repository is for QGIS Desktop itself, not for third party plugin.
You should raise your feature request to the plugin repository : https://github.com/KIOS-Research/ImportPhotos/ if it's this plugin ?

There is a builtin algorithm in the Processing toolbox for importing photo.

**Comment by drugstorer-172** [comment]
Shall I delete it?
