### ISSUE TITLE
Align dash pattern to line length performance issues

### ISSUE THREAD

**Issue by aydin-gis** [qgis/QGIS#41994]
Turning on the option for Align dash pattern to line length results in major performance issues in navigation within the layer style manager.

**How to Reproduce**
New user profile
create scratch layer
draw a line
in the layer styling, add a second simple line, slightly wider than the first.
make this one a dashed line.  Align the dash patter to line length.
Canvas refreshes are unaffected, but navigation in the layer styling panel severely affected. Up to 5 seconds to make changes and refresh screens in the style manager.
Including Exception Bad Allocation error.

**QGIS and OS versions**

QGIS version
3.18.0-Zürich
QGIS code revision
bdef9fb328
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
AnotherDXF2Shape; 
pointsamplingtool; 
profiletool; 
quick_map_services; 
db_manager; 
MetaSearch; 
processing

**Additional context**

**Comment by nyalldawson** [comment]
Can you share the style.xml definition of this symbol please?

**Comment by aydin-gis** [comment]
try this file

**Comment by nyalldawson** [comment]
There's no attachment there...

**Comment by aydin-gis** [comment]
Trying again.  As a zip file.
[
[track.zip](https://github.com/qgis/QGIS/files/6073389/track.zip)
](url)

**Comment by gislars** [comment]
I'd like to add my findings. Using a data defined override I've experienced the same or similar issue. The line dash pattern comes from an data defined override and if null values or values like "0;0" are present, memory and CPU usage rises until QGis crashes.

**Comment by nyalldawson** [comment]
The original issue was fixed by https://github.com/qgis/QGIS/pull/45233
