### ISSUE TITLE
Crash when changing symbology

### ISSUE THREAD

**Issue by bibolette01** [qgis/QGIS#41997]
Bonjour, 
En modifiant les symboles de polylignes ou de points QGIS plante. 
J'obtiens ce rapport d'erreur 
Pouvez vous m'aider SVP?
Bonne journée
______

Crash ID: 547d19cc4cd67897a31360314be24b42b4dfd33c

Stack Trace

QgsMapCanvas::setMapTool qgsmapcanvas.cpp:2021
QgisApp::activateDeactivateLayerRelatedActions qgisapp.cpp:14589
QgisApp::showLayerProperties qgisapp.cpp:16007
QgisApp::layerProperties qgisapp.cpp:9166
QgisApp::layerTreeViewDoubleClicked qgisapp.cpp:658
QMetaObject::activate :
QAbstractItemView::doubleClicked :
QTreeView::mouseDoubleClickEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1637
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.16.3-Hannover
QGIS code revision: 94ac9f21b8
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by DelazJ** [comment]
Bonjour,
Autre conditions que vous pouvez tester: relancez QGIS avec un nouveau profil (menu Préférences--> Profils-->), reproduisez vos modifs pour voir si ça crash toujours. et si oui, mettez à jour QGIS vers la 3.16.4 (au cas où...) et revérifiez si le bug persiste.
Si toujours pas résolu, veuillez indiquer étape par étape ce que vous faites afin d'aider les développeurs à reproduire le crash, de préférence en Anglais (vous pouvez utiliser un traducteur en ligne si besoin). Peut-être faudra-t-il fournir la symbologie que vous utilisez.

**Comment by roya0045** [comment]
Project/data seem to be required to replicate as there seems to be some shenanigans going on.

**Comment by bibolette01** [comment]
> Bonjour,
> Autres conditions que vous pouvez tester: relancez QGIS avec un nouveau profil (menu Préférences -> Profils ->), reproduisez vos modifs pour voir si ça crash toujours. et si oui, mettez à jour QGIS vers la 3.16.4 (au cas où ...) et revérifiez si le bug persiste.
> Si toujours pas résolu, veuillez indiquer étape par étape ce que vous faites pour aider les développeurs à reproduire le crash, en anglais (vous pouvez utiliser un traducteur en ligne si besoin). Peut-être faudra-t-il fournir la symbologie que vous utilisez.

Good morning, 
I will try the profil change first.
If i encounterd the same problem i will sum up the step 
I will inform you about the evolution 
thank you a lot for your reactivity
Have a nice day.

**Comment by gioman** [comment]
Closing for lack of feedback.
