### ISSUE TITLE
Qt: Retrying to obtain clipboard

### ISSUE THREAD

**Issue by Houska1** [qgis/QGIS#42006]
OSGeo4W new "testing" build, 3.18 nightly release candidate (code revision 1bcdbdb6)

Periodically getting a critical log message (and red status bar) saying
```
2021-03-03T10:07:23     CRITICAL    Qt : Retrying to obtain clipboard.
```
It seems to occur at irregular intervals, when QGIS is open but its window is not in the foreground (i.e. I am using a different application). Functionality not impaired when I come back to QGIS, just stress-inducing :)

This did not occur on the 3.18.0 (now retired) release on "old" OSGeo4W, or on 3.19 master there as well too. I *think* the difference may be that here it is compiled and running against Qt 5.15.2 while the "old" ones had an earlier Qt.

BTW, I've also been getting apparently harmless critical Qt warnings regarding axes from the Raster Data Plotting plugin at load time (I filed a bug report at https://bitbucket.org/janzandr/rasterdataplotting/issues/24/axis-error-messages-on-startup ), but this is not at startup and I now have that plugin disabled. QGIS is in the background and it is doing nothing when this happens. But mentioning it here in case the issue is a broader one of Qt being too verbose with needless warnings, for instance.

** Update: it seems more likely to occur when I've actively been using the clipboard with other applications (like when filing this bug report), but not always. Sorry, hard to pinpoint exact trigger because you only see it coming back, and based on the timestamp are then trying to remember "what exactly was I doing 3 minutes 21 seconds ago?"

**Comment by gioman** [comment]
See https://github.com/qgis/QGIS/issues/41583

**Comment by roya0045** [comment]
Seems to just be a debug message. Not sure if this a bug.

**Comment by Houska1** [comment]
Cool. Closing per Nyall's comment on the linked (#41583) issue that these get hidden in actual releases.

**Comment by wong-hao** [comment]
> Cool. Closing per Nyall's comment on the linked (#41583) issue that these get hidden in actual releases.

Hi, I build QGIS from source code and get the same red error log. How to solve or hide it...
