### ISSUE TITLE
Attributes Form, Value relation broken

### ISSUE THREAD

**Issue by stefan-overkamp** [qgis/QGIS#42003]
**Describe the bug**

QGIS Attribute Forms with value relations show different values then in Identify result dialog and database.

**How to Reproduce**

project file and geopackage
https://geodaten.metropoleruhr.de/owncloud/s/N8S98l96zCFeIQL

1. Select Layer radwege
2. Activate feature identify tool and click on a feature
3. Open the features form
4. Compare the value of field Status (e.g. in Betrieb (use)) in identify result dialog and form
5. The form doesn't show correct values, value relations with 1:n configured show no matches
6. Setting the layer to edit mode shows correct values but closing and opening the form again shows false values again

**QGIS and OS versions**

QGIS-Version 3.18.0-Zürich QGIS-Codeversion bdef9fb3
Kompiliert gegen Qt 5.15.2
Windows 10, Version 1909

There is no problem with value relations on:
QGIS-Version 3.16.4-Hannover QGIS-Codeversion 654e76b3cb

**Comment by stefan-overkamp** [comment]
![value_relation_broken](https://user-images.githubusercontent.com/55497288/109815408-e4de1980-7c2f-11eb-9cab-8aef8604eea6.png)

**Comment by roya0045** [comment]
@suricactus do you know if some of your changes might be related to this or could it be something else?

**Comment by elpaso** [comment]
This fixes the issue for me but I'd like to know what was changed to trigger this issue in the first place

```patch
diff --git a/src/gui/editorwidgets/qgsvaluerelationwidgetwrapper.cpp b/src/gui/editorwidgets/qgsvaluerelationwidgetwrapper.cpp
index df790af9fc..3fa2aa4a4d 100644
--- a/src/gui/editorwidgets/qgsvaluerelationwidgetwrapper.cpp
+++ b/src/gui/editorwidgets/qgsvaluerelationwidgetwrapper.cpp
@@ -325,7 +325,7 @@ void QgsValueRelationWidgetWrapper::setFeature( const QgsFeature &feature )
     {
       if ( ! mCache.isEmpty() )
       {
-        updateValues( mCache.at( 0 ).key );
+        updateValues( formFeature().attribute( fieldIdx() ).isValid() ? formFeature().attribute( fieldIdx() ) : mCache.at( 0 ).key );
       }
     } );
   }
```
