### ISSUE TITLE
GRASS tools missing 3.16 LTR

### ISSUE THREAD

**Issue by PCdurham** [qgis/QGIS#42028]
**Describe the bug**

After a fresh download of 3.16 LTR from standalone 64bit installer, GRASS tools are not appearing in the processing toolbox.  Checked and the GRASS tools are activated in the Processing settings. Using Win 10.
**How to Reproduce**

Download 3.16 LTR from standalone installer and open QGIS Desktop 3.16.4 with GRASS 7.8.3. Processing toolbox only has the gdal and saga tools.  But the installer has installed GRASS 7.8.5 in the QGIS folder and it seems to work fine.

**QGIS and OS versions**

QGIS 3.16 LTR standalone 64 bit installer. Windows 10.

**Comment by jonnyforestGIS** [comment]
Hi, 
@PCdurham did you try to open with the icon QGIS Desktop 3.10.6 with GRASS 7.8.3?

**Comment by PCdurham** [comment]
Yes I did. I'll edit the original to show that.

**Comment by gioman** [comment]
@PCdurham just did a clean install of 3.16.4 with a standalone installer and can't confirm this report.

**Comment by roya0045** [comment]
considering #42030 you have some local issues that cannot be replicated, at least easily.

**Comment by PCdurham** [comment]
I'll reset windows to factory and reinstall when 3.16.5 drops.  Will open a new issue if this problem persists.
