### ISSUE TITLE
Error updating PostGIS table when using data driven label position and integer columns

### ISSUE THREAD

**Issue by dr1542** [qgis/QGIS#42022]
I use two integer fields 'x' and 'y' in postgis table to store label postion.
Qgis 3.14 and lower worked fine, but since version 3.16 any saving layer operation after label moving causes postgis error
 ```
PostGIS error while changing attributes: Error: wrong value for integer "2825.086389414024"
 LINE 1: UPDATE work.zones SET "x"='2825.086389414024',"y"='5391.8...
```

QGIS version | 3.18.0-Zürich | QGIS code revision | bdef9fb328
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | db_manager; MetaSearch; processing

gis=# select postgis_version();
            postgis_version
---------------------------------------
 2.2 USE_GEOS=1 USE_PROJ=1 USE_STATS=1

gis=# select version();
                                             version
-------------------------------------------------------------------------------------------------
 PostgreSQL 9.5.3 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2, 64-bit

**Comment by gioman** [comment]
@dr1542 can you please be more specific about the necessary steps to replicate? For example: i tried to replicate (on 3.18) with my on data and here is ok. If would be good if you could provide a sample project+a dump of the table you are using.

**Comment by gioman** [comment]
> Error: wrong value for integer

@dr1542 this seems to suggest you have mismatch between the data type of columns where you want to save the label coordinates and the value you are trying to write in them.

**Comment by dr1542** [comment]
Ноw to replicate.

create table in postgresql/postgis database

```
create table label_test (label varchar, x int, y int, geom geometry(polygon, 0)) with oids;
insert into label_test (label, geom) values ('label1', st_geomfromtext('POLYGON((0 0, 10 0, 5 5, 0 0))')), ('label2', st_geomfromtext('POLYGON((0 -1, 10 -1, 5 -5, 0 -1))'));
```
then add this table to qgis version 3.16+;
unpack from [test.zip](https://github.com/qgis/QGIS/files/6084485/test.zip) and assign to layer style;
try to move label;
try to save changes;
and you will see that instead of integers the update query contains floats.

**Comment by gioman** [comment]
>  and you will see that instead of integers the update query contains floats.

@dr1542 I think is expected that label coordinates are decimal values and not integers. It is not the datatype of the column where you store this values that determines of the coordinate is saved as decimal or integer. This is my understanding, but I maybe wrong.

**Comment by dr1542** [comment]
> I think is expected that label coordinates are decimal values and not integers

@gioman I understand that I can use floats to store position in postgis db, but previous 10 years I was used integers and many my tables and cascaded views depends on it, and I cannot change it without numerous torments. 
Meanwhile in geopackage I can use integers for this.

**Comment by gioman** [comment]
> but previous 10 years I was used integers and many my tables and cascaded views depends on it, and I cannot change it without numerous torments.

ok.

**Comment by dr1542** [comment]
Qgis 3.18.1
Bug remained.

**Comment by gioman** [comment]
> Qgis 3.18.1
> Bug remained.

@dr1542 not sure the fix has been backported to 3.18.

**Comment by dr1542** [comment]
@gioman i'm not sure too now :(

**Comment by dr1542** [comment]
I tested latest night builds and bug still remained.
So I created own workaround. 

`
#this startup script for qgis 3.16+ prevents attempts saving float values
#to integer fields when committing a PostgreSQL data source
#(c) dr_gis at mail.ru. 2021 

from qgis.core import QgsProject
from qgis.utils import iface

def filterPostgreSQL(l):
    if l and l.type()==0 and l.dataProvider().storageType().startswith('PostgreSQL'):
        l.beforeCommitChanges.connect(force2int)

def force2int():
    l=iface.activeLayer()
    ft=[f.type() for f in l.fields()]                    #field types
    ii=[i for i in range(len(ft)) if ft[i]==2][1:] #indexes of integer fields
    ed=l.editBuffer()
    buf=ed.changedAttributeValues()
    for id in buf:
        for i in buf[id]:
            if i in ii:
                ed.changeAttributeValue(id, i, int(buf[id][i]), l.getFeature(id)[i])

QgsProject.instance().layerWasAdded.connect(filterPostgreSQL)
`

I wrote this code into script startup.py and db work correctness was restored
