### ISSUE TITLE
QGIS "Help --> About" no longer copying formatted MarkDown

### ISSUE THREAD

**Issue by Saijin-Naib** [qgis/QGIS#42037]
**Describe the bug**
I believe this cropped up at some point during the 3.16.x release cycle (can't find the specific point in time when it did), but effectively, the text copied from Help --> About is no longer copying as fully-formatted Markdown for easy/clean pasting into GitHub as a table, but instead produces a flat list.

**How to Reproduce**
Click help, click about, Select All, Copy, and Paste into a Rich-Text/MarkDown aware/capable input box.
Observe no MarkDown formatting/syntax preserved.

**QGIS and OS versions**

QGIS version
3.18.0-Zürich
QGIS code revision
bdef9fb328
Compiled against Qt
5.15.2
Running against Qt
5.15.2
Compiled against GDAL/OGR
3.2.1
Running against GDAL/OGR
3.2.1
Compiled against GEOS
3.9.1-CAPI-1.14.2
Running against GEOS
3.9.1-CAPI-1.14.2
Compiled against SQLite
3.33.0
Running against SQLite
3.33.0
Compiled against PDAL
2.2.0
Running against PDAL
2.2.0 (git-version: 38aa11)
PostgreSQL Client Version
13.0
SpatiaLite Version
5.0.1-rc1
QWT Version
6.1.3
QScintilla2 Version
2.11.5
Compiled against PROJ
8.0.0
Running against PROJ
Rel. 8.0.0, March 1st, 2021
OS Version
Windows 10 Version 2009
Active python plugins
CalculateGeometry; 
cartography_tools; 
LAStools; 
MemoryLayerSaver; 
processing_fusion; 
project_colors_dock; 
slyr; 
toggle_labels_widget; 
zoom_level; 
db_manager; 
MetaSearch; 
processing

**Comment by DelazJ** [comment]
Is this still true? Tested with Windows (3.16.10 and 3.21) and select all, ctrl A, ctrl V paste with markdown recognition (aka I get a table). The issues I have is the html text on top and the concatenated name of plugins (as mentioned in #43739)

**Comment by Saijin-Naib** [comment]
QGIS version
3.20.2-Odense
QGIS code revision
9f59a156
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.1
Compiled against PROJ
8.1.0.%3.%4
Running against PROJ
8.1.1
EPSG Registry database version
v10.028 (2021-07-07)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009




Active Python plugins
CalculateGeometry
cartography_tools
LAStools
loadthemall
MemoryLayerSaver
pdaltools-master
photo2shape
processing_fusion
qgis-maptiler-plugin
qgis2web
qgissprp
slyr
zoom_level
db_manager
MetaSearch
processing

**Comment by alexbruy** [comment]
Seems data copied as a markdown, but there are some other issues like in https://github.com/qgis/QGIS/issues/43739. Probably this can be closed.

**Comment by alexbruy** [comment]
Closing in favor of #43739.
