### ISSUE TITLE
QGIS does not recognize the CRS when the data is provided by SQLServer Database with Esri SDE

### ISSUE THREAD

**Issue by eurojam** [qgis/QGIS#42038]
We have a MS SQL Server: Microsoft SQL Server 2016 database with SDE from Esri on Windows Server 2012 R2. Loading data into QGIS results in the QGIS unkown CRS dialog. If we don't select one CRS the layer is displayed with the questionmark for the unknown CRS. But in the layer properties the correct CRS is displayed anyway (QGIS: Version 3.12.2 and 3.16).  

![screenshot_01](https://user-images.githubusercontent.com/46351209/109982274-08719480-7d02-11eb-9ce7-73b052c361be.jpg)
![screenshot_02](https://user-images.githubusercontent.com/46351209/109982272-08719480-7d02-11eb-81f6-c47d0272fd9f.jpg)

**Comment by gioman** [comment]
@eurojam Is this a question?

**Comment by eurojam** [comment]
No it is a bug I believe...

**Comment by gioman** [comment]
> No it is a bug I believe...

@eurojam I don't do MS SQL spatial or not, so I can't check quickly. Would you mind asking in the users/developers mailing list if is a known issue, or maybe if it is just your tables/geometry columns that are defined as expected? Thanks.

**Comment by eurojam** [comment]
ok I did ask gis.stackexchange.com...shall we close this issue then? it could be that the columns are not definded correctly?

**Comment by gioman** [comment]
> gis.stackexchange.com.

@eurojam you should ask the official QGIS developers mailing list not SE.
