### ISSUE TITLE
QGIS server Atlas print behaves inconsistently regarding legend content

### ISSUE THREAD

**Issue by haubourg** [qgis/QGIS#42036]
**Describe the bug**

If, when printing a layout from QGIS server: 
-  the legend block option "auto update" is checked in the layout
AND
- calling printing without the `LAYERS` parameter , or with a subset of the layers like `LAYERS=layer1,layer2`
THEN

the legend will not show the undeclared layers. This is inconsistent with what occurs in the desktop environment (and seems like a bug).

Some examples:

- my map has the following layers : 
 `LAYERS=velo_consigne_individuelle,infos_communes_completes,velo_tempovelo,velo_stationnements__stationnements_cyclables,velo_sd_amenagements_cyclables_existants,velo_itineraire_cyclable,velo_consigne_collective,velo_amenagement__amenagements_cyclables,agences_metrovelo` 

If the "auto update" unckecked and this layer list is full, the getprint produces a full legend.

![image](https://user-images.githubusercontent.com/1629853/109970084-f1787580-7cf4-11eb-9464-957d229f6405.png)

if I remove some layers from the LAYERS parameter, they disappear from the legend but not from the map (which is locked to a map theme) . Here  the call uses only one layer `LAYERS=infos_communes_completes`

![image](https://user-images.githubusercontent.com/1629853/109970519-72377180-7cf5-11eb-8570-73ee1a5a02f3.png)

if I remove the LAYERS parameter, I lose the whole legend content. 

![image](https://user-images.githubusercontent.com/1629853/109970150-0228eb80-7cf5-11eb-912c-f3ef5eac5205.png)

**QGIS and OS versions**

QGIS server 3.18 / Linux Debian from QGIS.org repositories

cc @troopa81

**Comment by elpaso** [comment]
@haubourg isn't the bug that the undeclared layers are shown in the map too? I believe that the query string LAYERS should take precedence and be in control.

Whatever we decide it is the expected behavior, I think we must document it clearly in the documentation: there are multiple possible behaviors in this situation here and each one seems reasonable.

**Comment by haubourg** [comment]
Hi @elpaso ! It might be an interesting feature for sure, if it was documented. Maybe those coding web client features have some requirements here, such as printing only the layers defined on the web client canvas. That would totally make sense. 

In my case I had locked the map to a predefined theme, so I wasn't expecting it to change. Since the `LAYERS=*` parameter exists, and as long as this one respects the map theme layer's list, I'm OK with what you suggests

**Comment by elpaso** [comment]
@haubourg access control plugins also needs to be taken into consideration: see https://github.com/qgis/QGIS/pull/41823, it also works on atlas.

There are a definitely use cases where the web applications need to control which layers and features and attributes are visible and need to be included into an atlas.

**Comment by troopa81** [comment]
> @haubourg isn't the bug that the undeclared layers are shown in the map too? I believe that the query string LAYERS should take precedence and be in control.

I agree. According to the [documentation](https://docs.qgis.org/testing/en/docs/server_manual/services.html#wms-layers) 

> This parameter allows to specify the layers to display on the map.

If LAYERS is empty in your GetPrint/GetMap, then there is no layers at all, and you get an empty map.

QGIS documentation says that LAYERS parameter is not required for GetPrint/GetMap request, which is weird, because the WMS [specification](http://cite.opengeospatial.org/OGCTestData/wms/1.1.1/spec/wms1.1.1.html#table.getmap) says otherwise for GetMap.

I propose to:
- Raise an error if LAYERS is empty and change the documentation to a required parameter
- Fix the GetPrint that should not display layers missing in LAYERS parameter

@elpaso @haubourg What do you think?

**Comment by troopa81** [comment]
@haubourg In the end, does the "auto update" parameter state changes anything to the issue? it doesn't look like according to your examples.

**Comment by troopa81** [comment]
> If the "auto update" unckecked and this layer list is full, the getprint produces a full legend.

Do you really make these examples with "auto update" mode unchecked ? It looks like the legend is static in this mode and never changes no matter what LAYERS parameters is.

**Comment by troopa81** [comment]
> So, if the client does not specify LAYERS we use the defaults set by the layout/map theme, if LAYERS are specified we honor the parameter.

Even if it is indeed two different things, one might expect the same behavior with the same parameters in the two request, no? 
It looks a bit weird to me to have 2 different ways of dealing with LAYERS param, but maybe it's because I don't know much about layout.

**Comment by troopa81** [comment]
> What worries me is that we are changing a well established behavior, applications out there might be relying on the fact that LAYER was not required for GetPrint.

It's indeed a very good argument.

**Comment by elpaso** [comment]
@troopa81 whatever we decide to do **please** remember to update the documentation or we will eventually bounce back and forth on this topic and have issues reported from users :smiley:

**Comment by SebastienPeillet** [comment]
Hi,

The working branch is [here](https://github.com/SebastienPeillet/QGIS/commit/fc301a384c119cd81c8f087051b7e1a0f9694a19).

After discussions with @troopa81 and @haubourg, we conclude that it was needed to : 

- fix legend inconsistency between desktop and server when there is no LAYERS parameter
- regarding layers visibility, LAYERS parameter should take precedence on layout style, including map theme
- LAYERS parameter stays optional to keep compatibility with established applications.

Currently QGIS server has the following behavior : 

MapTheme | LAYERS parameter | Printed map       | Legend       | Bug                     | 
----------------|----------------------------|----------------------|----------------|------------------------|
no               | no                            | all visible  in project   |  no legend | expected legend  |
no               | yes                           | layers listed in LAYERS            | LAYERS    | OK                       |
yes             | no                             | layers visible in the mapTheme             | no legend | expected legend  |
yes             | yes                           | THEME            | LAYERS | map should show layers according LAYERS  |

After my changes, here is the new behavior : 

MapTheme | LAYERS parameter | Visible layers                             | Layer style | Legend       |
----------------|----------------------------|-----------------------------------------|----------------|--------------------|
no               | no                            | all visible layers in project         |  project style |same as layout in desktop |
no               | yes                           | layers listed in LAYERS            | project style |LAYERS elements   |
yes             | no                             | layers visible in the mapTheme  | mapTheme style |same as layout in desktop |
yes             | yes                           | layers listed in LAYERS             | mapTheme style |LAYERS elements |

@haubourg @troopa81 @elpaso, maybe also @rldhont @pblottiere Do we agree on this ?

If so, I'll add tests to my branch and make a PR.

**Comment by elpaso** [comment]
Makes sense to me but did you also have a look to https://github.com/qgis/QGIS/pull/43391 ?

It was tricky to get it right, at first I also tried changing https://github.com/SebastienPeillet/QGIS/commit/fc301a384c119cd81c8f087051b7e1a0f9694a19#diff-fad5b53afb20f316460160db51ff9c26f65d1108d00843ef18707c03c22d0b43R2130 but there were a lot of conflicts with layout exporter logic.

**Comment by SebastienPeillet** [comment]
@elpaso not yet. I'll read it tomorrow. Thank you for the tips

**Comment by SebastienPeillet** [comment]
As always, it tooks me more more time before I could return to this issue...

Your PR partially fixes this bug too ! It miss only a little fix to add legend when user doesn't provide LAYERS parameter and the map item does not follow a map theme (see #43981). But indeed I agree with you that it is tricky to use MapTheme and LAYERS parameters at the same time.

Actually, without changes on qgslayoutitemmap.cpp, here will be the future behavior : 

MapTheme | LAYERS parameter | Visible layers | Layer style | Legend
-- | -- | -- | -- | --
no | no | all visible layers in project | project style | same as layout in desktop
no | yes | layers listed in LAYERS | project style | LAYERS elements
yes | no | layers visible in the mapTheme | mapTheme style | same as layout in desktop
yes | yes | layers listed in LAYERS | **project style** | LAYERS elements

So it will fix this issue but in some way I still find that this is weird that Maptheme style does not apply when LAYERS parameters is used.

**Comment by SebastienPeillet** [comment]
Finally I found a workaround to set override styles to layers that should use particular style due to a map theme. I'm interested by your feedback on it @elpaso . Does it avoid the conflicts you mention abose ?

You'll find the code here :
https://github.com/qgis/QGIS/pull/43981/files#diff-2b31f4f76dacb4bd2240768e67fbe59d416219b9b58b3fece7706a1ebb18fbaeR699-R737

**Comment by elpaso** [comment]
@SebastienPeillet the conflicts were caused by touching `qgslayoutitemmap.cpp` so I think your approach is good because you don't change it.

Unrelated, but since you are on it, can you please create `_assertRed()` `_assertGreen()` etc in the test to make it more readable? I should have done it in the first place :smiley: 

Maybe also add some more comments to explain why we are expecting a certain result, things are getting complicated with all the permutations of LAYERS and STYLES.

**Comment by SebastienPeillet** [comment]
@elpaso  Ok, thank you for your advice !

I added it into QgsServerTestBase and change assertEqual in both test_qgsserver_wms_getprint_legend.py and test_qgsserver_wms_getprint_maptheme.py :+1:

**Comment by elpaso** [comment]
Thank you 😊
