### ISSUE TITLE
QGIS crash when exporting a large map (1300 mm x 900mm) with angle

### ISSUE THREAD

**Issue by NykoTera** [qgis/QGIS#42034]
**Describe the bug**
I need to export large map using QGIS print composer. It works well when I apply simple angle in map's "object properties" (0°, 90°, 180°, 270°).  The printing or exporting work crash when I use any other angle (45°, 60°,...).
![image](https://user-images.githubusercontent.com/44168242/109953121-ebc46500-7cdf-11eb-99d1-f3415d346cdb.png)

**How to Reproduce**

1. Go to 'QGIS print composer' and create a large map, in my case 1300mm * 900 mm for both paper and map size.
2. I use a 1:30000 scale and set a 45° rotation on the map.
3. Export or print the map -> Crash

![QGIS_crash_composer](https://user-images.githubusercontent.com/44168242/109968534-21bf1480-7cf3-11eb-9a9b-8e7a9d07f39b.gif)

Note that the error is not as quick as in the gif. It works a while before the crash.

**QGIS and OS versions**

Version de QGIS | 3.16.4-Hannover | Révision du code | 654e76b3cb
-- | -- | -- | --
Compilé avec Qt | 5.11.2 | Utilisant Qt | 5.11.2
Compilé avec GDAL/OGR | 3.1.4 | Utilisé avec GDAL/OGR | 3.1.4
Compilé avec GEOS | 3.8.1-CAPI-1.13.3 | Utilisé avec GEOS | 3.8.1-CAPI-1.13.3
Compilé avec SQLite | 3.29.0 | Fonctionne avec SQLite | 3.29.0
Version du client PostgreSQL | 11.5 | Version de SpatiaLite | 4.3.0
Version de QWT | 6.1.3 | Version de QScintilla2 | 2.10.8
Compilé avec PROJ | 6.3.2 | Fonctionne avec PROJ | Rel. 6.3.2, May 1st, 2020
Version de l'OS | Windows 10 (10.0)
Extensions Python actives | db_manager; MetaSearch; processing

**Additional context**

I also tried on 3.14.16 and 3.10.14 with same results

The computer config :
Intel Core I7 8565U
8Gb RAM
Nvidia GeForce MX230

**Comment by roya0045** [comment]
Can you copy the stack trace here .

**Comment by NykoTera** [comment]
Of course, here it is :

Crash ID: 45f0af4b5b9fa403ab461e202f1aceac99340f0b

**Stack Trace**

QColorProfile::fromSRgb :
QVectorPath::convertToPainterPath :
QRasterPaintEngine::fillRect :
QRasterPaintEngine::drawImage :
QPainter::drawImage :
QgsShapeburstFillSymbolLayer::renderPolygon qgsfillsymbollayer.cpp:1354
QgsFillSymbol::renderPolygonUsingLayer qgssymbol.cpp:2298
QgsFillSymbol::renderPolygon qgssymbol.cpp:2245
QgsSymbol::renderFeature qgssymbol.cpp:1210
QgsFeatureRenderer::renderFeature qgsrenderer.cpp:130
QgsInvertedPolygonRenderer::stopRender qgsinvertedpolygonrenderer.cpp:342
QgsVectorLayerRenderer::drawRenderer qgsvectorlayerrenderer.cpp:420
QgsVectorLayerRenderer::render qgsvectorlayerrenderer.cpp:317
QgsMapRendererCustomPainterJob::doRender qgsmaprenderercustompainterjob.cpp:319
QgsMapRendererCustomPainterJob::start qgsmaprenderercustompainterjob.cpp:120
QgsMapRendererCustomPainterJob::renderSynchronously qgsmaprenderercustompainterjob.cpp:220
QgsLayoutItemMap::drawMap qgslayoutitemmap.cpp:1342
QgsLayoutItemMap::paint qgslayoutitemmap.cpp:1053
QGraphicsScene::dragMoveEvent :
QGraphicsItem::dragMoveEvent :
QGraphicsEffectSource::draw :
QgsLayoutEffect::draw qgslayouteffect.cpp:33
QGraphicsScene::drawItems :
QGraphicsScene::drawItems :
QGraphicsScene::render :
QgsLayoutExporter::renderRegion qgslayoutexporter.cpp:261
QgsLayoutExporter::renderPage qgslayoutexporter.cpp:174
QgsLayoutExporter::printPrivate qgslayoutexporter.cpp:1278
QgsLayoutExporter::exportToPdf qgslayoutexporter.cpp:684
QgsLayoutDesignerDialog::exportToPdf qgslayoutdesignerdialog.cpp:2272
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1637
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.16.4-Hannover
QGIS code revision: 654e76b3cb
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

**Comment by nyalldawson** [comment]
This is an upstream (qt) bug. You need a release based on qt 5.12 or later, such as the alternative (beta) windows installers. There's nothing we can fix in qgis itself to avoid this.

**Comment by goened** [comment]
I have a similar problem to this issue. QGIS crashes when I try to export bigger maps as pdf-file or the programm doens´t export the entire map. I don´t understand why it worked all the time in the last months but suddenly this issue appeared? Does it have to do with a Windows Update?

You wrote 
„This is an upstream (qt) bug. You need a release based on qt 5.12 or later, such as the alternative (beta) windows installers. There's nothing we can fix in qgis itself to avoid this.“ That means which QGIS-Version should I install? The last LTR has QT 3.11.2.
Should I use version 3.18? How can I find the "alternative (beta) windows installers"?

**Comment by gioman** [comment]
> How can I find the "alternative (beta) windows installers"?

@goened try http://download.osgeo.org/osgeo4w/testing/osgeo4w-setup.exe
