### ISSUE TITLE
Vector to raster gdal bug

### ISSUE THREAD

**Issue by PCdurham** [qgis/QGIS#42030]
**Describe the bug**

Using a buffered vector layer and wanting to rasterise it.  Simple vector to raster but gdal not responding.  Error message is:

GDAL command:
gdal_rasterize -l INPUT -a burn -ts 3566.0 2295.0 -a_nodata 0.0 -te 533673.7632 7662268.5173 569330.132 7685218.3395 -ot Byte -of GTiff C:/Users/Patrice/AppData/Local/Temp/processing_vZvHUE/a1589818b6504ff3bb7cff95687d1d8d/INPUT.gpkg C:/Users/Patrice/AppData/Local/Temp/processing_vZvHUE/3bb63acbaa5c4215b400f4acc1001247/OUTPUT.tif

GDAL command output:
'gdal_rasterize' is not recognized as an internal or external command, operable program or batch file.

**How to Reproduce**

create a vector line. Buffer it. Then vector to raster with any burn in value.

**QGIS and OS versions**
QGIS Desktop 3.16.4 with GRASS 7.8.3, win 10

**Additional context**

**Comment by gioman** [comment]
@PCdurham just tested a clean (standalone) install on 3.16.4 on Win10 and can't confirm your report.

**Comment by roya0045** [comment]
Seems to be a local issue where the environment variables are badly set and the command cannot be found.

**Comment by PCdurham** [comment]
Could be partially true. I reverted to 3.10.14.  GRASS does work now, but the gdal bug remains.

**Comment by gioman** [comment]
> , but the gdal bug remains.

@PCdurham on your machine ;)

**Comment by PCdurham** [comment]
Indeed. Any suggestions?  The gdal provider options don't give a path as a env variable so aside from a complete re-install, I'm not quite sure what to do here.

**Comment by PCdurham** [comment]
I had to backtrack to 3.4.15.  in Madeira, GRASS tools are present and rasterisation works fine.  this solves my immediate problem, but I would still need to update so would like to know how to fix GASS and gdal bugs in 3.16 LTR.

**Comment by PCdurham** [comment]
I'll reset windows to factory and reinstall when 3.16.5 drops.  Will open a new issue if this problem persists.
