### ISSUE TITLE
OSGeo4W-NG: Reinstate QGIS3 shortcut

### ISSUE THREAD

**Issue by Saijin-Naib** [qgis/QGIS#42042]
**Feature description.**
OSGeo4W-NG does not create the generic "QGIS3" shortcut, but only the more explicit QGIS Desktop 3.18.0 shortcut types. This leads to a less than stellar UX as the QGIS Desktop 3.x.x shortcut will have to be re-pinned to the Start Menu, Taskbar, etc. every time a version changes, as the shortcut name itself changes.

Come to think of it, just a QGIS shortcut would be even better, as it would allow it to persist across major version upgrades, as well (QGIS 3.x to QGIS 4.x).

Having the more general QGIS3 shortcut generated by the older OSGeo4W installer was really nice, as it would persists across version upgrades without constantly needing to be re-pinned.

**Comment by roya0045** [comment]
Shouldn't this be filled in the osgeo tracker or here?

**Comment by Saijin-Naib** [comment]
> Shouldn't this be filled in the osgeo tracker or here?

I think Issues are turned off there, or at least I can't file an issue in the OSGeo4w tracker.
What is the best place for this to be filed, then?

**Comment by roya0045** [comment]
Maybe Jürgen has a clue.

**Comment by jef-n** [comment]
> I think Issues are turned off there, or at least I can't file an issue in the OSGeo4w tracker.
> What is the best place for this to be filed, then?

https://trac.osgeo.org/osgeo4w

**Comment by jef-n** [comment]
See also https://trac.osgeo.org/osgeo4w/ticket/666
