### ISSUE TITLE
Georeferencer -- Loaded georeferenced tif and points don't match

### ISSUE THREAD

**Issue by mimi89999** [qgis/QGIS#42044]
**Describe the bug**
Loaded georeferenced tif and points don't match

**How to Reproduce**

1. Load a raster in georefenrecer
2. Georeference it
3. Save it and the points
4. Close the georefenrecer
5. Load the tif and points
6. Notice that the loaded points don't match their location on the tif. CRS issue?

**QGIS and OS versions**

Version de QGIS | 3.16.4-Hannover | Branche de code de QGIS | Release 3.16
-- | -- | -- | --
Compilé avec Qt | 5.15.2 | Utilisant Qt | 5.15.2
Compilé avec GDAL/OGR | 3.2.1 | Utilisé avec GDAL/OGR | 3.2.1
Compilé avec GEOS | 3.9.0-CAPI-1.16.2 | Utilisé avec GEOS | 3.9.0-CAPI-1.16.2
Compilé avec SQLite | 3.34.1 | Fonctionne avec SQLite | 3.34.1
Version du client PostgreSQL | 13.2 (Debian 13.2-1) | Version de SpatiaLite | 5.0.1
Version de QWT | 6.1.4 | Version de QScintilla2 | 2.11.6
Compilé avec PROJ | 7.2.1 | Fonctionne avec PROJ | Rel. 7.2.1, January 1st, 2021
Version de l'OS | Debian GNU/Linux bullseye/sid
Extensions Python actives | OSMDownloader; QuickOSM; contour; processing; db_manager; MetaSearch

**Additional context**

**Comment by gioman** [comment]
> Notice that the loaded points don't match their location on the tif. CRS issue?

@mimi89999 attach a sample + points.

**Comment by uclaros** [comment]
Are you loading the rectified raster the second time?

**Comment by mimi89999** [comment]
I'm loading the raster produced by the georeferencer.

**Comment by gioman** [comment]
> I'm loading the raster produced by the georeferencer.

@mimi89999 so I guess the shift is expected(?).

**Comment by roya0045** [comment]
Seems to be a projection issue between the points and the output. Common with the old approach.

**Comment by uclaros** [comment]
The saved points are supposed to be used with the initial un-georeferenced raster. The coordinates stored in the file are in pixels if there is no georef info or in the initial crs if there is georef info.
Loading the resulting raster with the point file you're trying to use pixel coords from the points file as crs coords in the resulting file, hence the unexpected result.

**Comment by gioman** [comment]
Closing for lack of feedback.
