### ISSUE TITLE
QGIS crashes and GUI doesn't start

### ISSUE THREAD

**Issue by harshmistry96** [qgis/QGIS#42058]
QGIS 3.10.14 keeps on crashing after the "starting GUI" interface. I also tried reinstalling it but still facing the same issue.

Please let me know if any other information is required.

![QGIS_report](https://user-images.githubusercontent.com/48412770/110096315-b37f5e00-7d95-11eb-9eb7-1708b1c21eb9.JPG)

**Comment by gioman** [comment]
@harshmistry96 try https://github.com/qgis/QGIS/issues/42050#issuecomment-791276891

**Comment by gioman** [comment]
See also https://github.com/qgis/QGIS/issues/41934

**Comment by harshmistry96** [comment]
Tried but still facing the same issue.

**Comment by gioman** [comment]
> Tried but still facing the same issue.

seems a local issue, likely caused by something external to QGIS.

**Comment by harshmistry96** [comment]
Could you please suggest what could be causing this problem?

**Comment by roya0045** [comment]
You can remove everything related to qgis and try to install 3.16. Otherwise we can't guess anything with the information you provided.

**Comment by gioman** [comment]
Closing for lack of feedback.
