### ISSUE TITLE
New install of 3.16.4 Unexpectedly ends on start up

### ISSUE THREAD

**Issue by GGaeke** [qgis/QGIS#42050]
Checklist before submitting

- [x] Search through existing issue reports and gis.stackexchange.com to check whether the issue already exists - **Don't see anyone getting this error right on startup.**
- [x] Test with a [clean new user profile](https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html?highlight=profile#working-with-user-profiles). - **Cannot do this as QGIS does not even start.**
- [x] Create a light and self-contained sample dataset and project file which demonstrates the issue - **Again, cannot do this as QGIS does not start.**
-->

**Describe the bug**
QGIS 3.16.4 will not launch. Any time I try to start it, I get the "QGIS unexpectedly ended" error and dialog box.

**How to Reproduce**

Double-clicking the icon to start QGIS 3.16.4

**QGIS and OS versions**

New install of 3.16.4. I was running 3.10 on this system before. I uninstalled 3.10, cleaned up my registry, rebooted and then ran the 3.16.4 installation

**Additional context**
Here's the copy of the report

Crash ID: 32bfed89acf7da3713270efe4dcde2a7fa2a7547

Stack Trace

QEventTransitionPrivate::unregister :
QAbstractItemModel::persistentIndexList :
QAbstractItemModelPrivate::rowsInserted :
QAbstractItemModel::endInsertRows :
QMetaObject::activate :
QgsDataItem::populate qgsdataitem.cpp:513
QgsDataItem::childrenCreated qgsdataitem.cpp:488
QMetaObject::activate :
QFutureWatcherBase::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QgsAuthManager::passwordHelperRead qgsauthmanager.cpp:3111
QgsAuthManager::masterPasswordInput qgsauthmanager.cpp:3247
QgsAuthManager::loadAuthenticationConfig qgsauthmanager.cpp:1225
meth_QgsAuthManager_loadAuthenticationConfig sip_corepart6.cpp:114328
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyTuple_New :
PyObject_FastCallKeywords :
PyObject_FastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_sip :
sipVH__core_206 sip_corepart0.cpp:21507
sipQgsDataItemProvider::createDataItem sip_corepart10.cpp:9152
QgsBrowserModel::addProviderRootItem qgsbrowsermodel.cpp:777
QgsBrowserModel::addRootItems qgsbrowsermodel.cpp:140
QgsBrowserModel::initialize qgsbrowsermodel.cpp:229
QgsBrowserDockWidget::showEvent qgsbrowserdockwidget.cpp:126
QWidget::event :
QDockWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QWidgetPrivate::show_helper :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidget::setVisible :
QgisApp::QgisApp qgisapp.cpp:1537
main main.cpp:1380
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.16.4-Hannover
QGIS code revision: 654e76b3cb
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

**Comment by gioman** [comment]
> **Describe the bug**
> QGIS 3.16.4 will not launch. Any time I try to start it, I get the "QGIS unexpectedly ended" error and dialog box.
> 
> **How to Reproduce**
> 
> Double-clicking the icon to start QGIS 3.16.4
> 
> **QGIS and OS versions**
> 
> New install of 3.16.4. I was running 3.10 on this system before. I uninstalled 3.10, cleaned up my registry, rebooted and then ran the 3.16.4 installation

@GGaeke I know that is not very helpful... but you have clearly a local issue, as this not a general QGIS issue.

You may want to try wipe/delete you configs/profiles dirs (which are NOT removed by uninstalling QGIS).

`C:\Users\username\AppData\Roaming\QGIS\`

**Comment by gioman** [comment]
See also https://github.com/qgis/QGIS/issues/42058

**Comment by gioman** [comment]
See also https://github.com/qgis/QGIS/issues/41934

**Comment by harshmistry96** [comment]
No still having the same issue.

**Comment by gioman** [comment]
Likely a local issue caused by something stranger to QGIS. You should try on a different machine.

**Comment by GGaeke** [comment]
Thanks gioman. Wiping the profiles worked.

**Comment by pgnan** [comment]
@GGaeke Hello GGaeke, I'm struggling with the same problem. Could I ask how did you fix it? deleting the ~/AppData/Roaming/QGIS directory worked?
