### ISSUE TITLE
Masking labels issue with QGIS 3.16.4 on MacOS 11.2.1

### ISSUE THREAD

**Issue by SebSilva** [qgis/QGIS#42059]
Hi, 

I'm having an issue with Masking labels in QGIS 3.16.4 running on macOS 11.2.1. And sorry but for some reason I can't upload a PNG image to make it easier. 
 
I discovered the issue while following the steps of a tutorial to label contour lines (https://www.youtube.com/watch?v=-xzoVF7Z7u0). 

So the idea is to label contour lines with ELEV data over the lines, without having to use buffer. 

I checked the "Enable mask" under the Mask tab of the layer styling, and then went to the Masks (left-side). 

A warning message pops up on top of this left-side-tab-window: "Select both sources and symbol layers or your configuration will be lost". 

I checked the "Masked symbol layers", but then there is no "Mask source" checkbox to check in the bottom window. 

Any idea what may be the issue?

Thanks!

**Comment by gioman** [comment]
@SebSilva is this a question?

**Comment by SebSilva** [comment]
@gioman yes, indeed. Sorry if I'm missing something, but this is my first report.

**Comment by gioman** [comment]
> @gioman yes, indeed. Sorry if I'm missing something, but this is my first report.

@SebSilva questions must be asked in the users or developers mailing lists.

**Comment by SebSilva** [comment]
@gioman  Ok, well copied!
