### ISSUE TITLE
Cannot select objects when symbology rule uses expression containing variables

### ISSUE THREAD

**Issue by drewh1988** [qgis/QGIS#42066]
Using QGIS 3.18.0 for windows. When using rule based symbology and a rule that uses project variables (in my case, using a date variable to filter several layers by a certain date), the features display correctly, however I cannot select them using the select feature tool. If I clear the rule or use a rule that does not contain variables, selection works as expected. Features can still be selected via the attribute table.

**Comment by gioman** [comment]
@drewh1988 please attach a sample project+ data.

Did it worked as expected in previous QGIS releases?

**Comment by roya0045** [comment]
This behaviour is quite inconsistent and I couldn't make a 100% reliable example previously. This is even more apparent when editing geometries and is intermittent.

**Comment by gioman** [comment]
> This behaviour is quite inconsistent and I couldn't make a 100% reliable example previously. This is even more apparent when editing geometries and is intermittent.

@roya0045 did it worked correctly and consistently in the past?

**Comment by roya0045** [comment]
@gioman I didn't try 3.18, but no. A way that worked semi-reliably was using a rule-based symbology with the atlas extent and some others.

**Comment by roya0045** [comment]
Usually my workaround is to duplicate a layer and use single symbol.

**Comment by drewh1988** [comment]
Attached is a qgis project and datafile that replicates the behavior. 
[Test.zip](https://github.com/qgis/QGIS/files/6093614/Test.zip)

**Comment by stratiform** [comment]
Also experiencing this problem in 3.16.5

**Comment by zacwang89** [comment]
I can confirm the issue in 3.16.5 as well. But not in 3.10.14 or 3.14.16

**Comment by roya0045** [comment]
Add an else symbol/category and display it when you select/edit, that usually solves this.

**Comment by gioman** [comment]
> Add an else symbol/category and display it when you select/edit, that usually solves this.

@roya0045 and yet I think that this very counter intuitive for common user, especially of this worked previously without this trick. What do you think?

**Comment by roya0045** [comment]
@gioman I'm not sure if it worked previously. I tried to debug this summarily but it's something deep having an issue with the symbology evaluation. Rendering with expression can be wacky at times.

**Comment by Caligraf21** [comment]
I'm using 3.16.6 LTR and I experience this bug too.

Adding a new category with 'else' rule as @roya0045 proposed solved the bug
