### ISSUE TITLE
Add support for legend of cascaded WMS layers in QGIS Server

### ISSUE THREAD

**Issue by frippe12573** [qgis/QGIS#42063]
In QGIS server it is very important to display the legend for WMS cascade layers which is currently not visible/available in the 3.18 (and even 3.16) QGIS server versions.

**Comment by gioman** [comment]
@frippe12573 I'm pretty sure that this worked as expected on the last LTR (3.10), did it broke?

**Comment by frippe12573** [comment]
> I'm pretty sure that this worked as expected on the last LTR (3.10), did it broke?

I'm sure it is not working on QGIS server 2.18, 3.16 and 3.18, because I tested them.

**Comment by gioman** [comment]
@frippe12573 I have a service running on QGIS Server 3.10 that is cascading the legend for an external WMS service

![Screenshot_20210305_153000](https://user-images.githubusercontent.com/1951107/110136614-cca10280-7dc7-11eb-87d9-751b2b1aff96.png)

**Comment by gioman** [comment]
> I'm sure it is not working on QGIS server 2.18, 3.16 and 3.18, because I tested them.

@elpaso does it rings any bell to you? here seems to be working for me.

**Comment by frippe12573** [comment]
@gioman I tested a map including even a WMS layer from an external Geoserver.

I tested this request: http://geothopica3.igg.cnr.it/cgi-bin/qgis_mapserv.fcgi?map=/dati/lizmap_repo/wms_cascade_test/wms_cascade_test.qgs&SERVICE=WMS&request=GetLegendGraphics&CRS=EPSG:32633&layers=wms_Default_Polygon
I only got a white image including only the layer name, should I use other parameters in the request?

**Comment by gioman** [comment]
I'm also not seeing anymore any legend coming from a cascaded WMS layer. I guess this is a bug, and likely a regression(?).

**Comment by maxencelaurent** [comment]
Here is a reproducer using `qgis/qgis-server:3.36.1-lunar` docker image

https://github.com/maxencelaurent/qgis-issue-42063

# Start the stack

```bash
git clone https://github.com/maxencelaurent/qgis-issue-42063.git
cd qgis-issue-42063
docker compose up
```

The stack contains two QGIS server.

# Reproducer

## 1st QGIS server

First server (`http://localhost:8080/ows/`) serves the `qgis_projects_1/test.gqs` project, which contains one single vector layer named `vector_bat`. Both GetMap and GetLegendGraphic work fine.

Here is a simple `GetMap` query.

http://localhost:8080/ows/?service=WMS&map=/io/data/test.qgs&request=GetMap&version=1.3.0&width=512&height=512&crs=EPSG:2056&BBOX=2539106,1184111,2539880,1184814&LAYERS=vector_bat
![image](https://github.com/qgis/QGIS/assets/6583528/7411e0f3-eafd-4258-9459-f5a2798a5b73)


Here is a simple `GetLegendGraphic` query.
http://localhost:8080/ows/?service=WMS&map=/io/data/test.qgs&request=GetLegendGraphic&version=1.3.0&LAYERS=vector_bat
![image](https://github.com/qgis/QGIS/assets/6583528/77432a61-61f2-4910-a5b1-c1bc2719543c)


## 2nd QGIS server
The second QGIS server publishes the  `qgis_projects_2/test_2.gqs` project. It contains one WMS layer, which is the one provided by the first QGIS server.

The `GetMap` is working as expected.
http://localhost:8081/ows/?service=WMS&map=/io/data/test_2.qgs&request=GetMap&version=1.3.0&width=512&height=512&crs=EPSG:2056&BBOX=2539106,1184111,2539880,1184814&LAYERS=vector_bat_as_wms
![image](https://github.com/qgis/QGIS/assets/6583528/117f40fe-4868-4090-8324-e1536c2dd56a)


The cascaded WMS query is clearly visible in the logs:

2nd server receives the request:
```
qgis-issue-42063-qgisserver2-1  | 10:39:01 INFO Server[25]: ******************** New request ***************
qgis-issue-42063-qgisserver2-1  | 10:39:01 INFO Server[25]: Request URL: http://localhost:8081/ows/?service=WMS&map=/io/data/test_2.qgs&request=GetMap&version=1.3.0&width=512&height=512&crs=EPSG:2056&BBOX=2539106,1184111,2539880,1184814&LAYERS=vector_bat_as_wms
...
```

2nd server cascades request to the first server:
```
qgis-issue-42063-qgisserver1-1  | 10:39:01 INFO Server[25]: ******************** New request ***************
qgis-issue-42063-qgisserver1-1  | 10:39:01 INFO Server[25]: Request URL: http://172.18.0.1:8080/ows/?MAP=/io/data/test.qgs&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=6.640780999999999601%2C46.80535700000000077%2C6.651016000000000261%2C46.81175499999999801&CRS=CRS%3A84&WIDTH=702&HEIGHT=439&LAYERS=vector_bat&STYLES=&FORMAT=image%2Fpng&DPI=90&MAP_RESOLUTION=90&FORMAT_OPTIONS=dpi%3A90&TRANSPARENT=TRUE
...
```
first server response:
```
qgis-issue-42063-qgisserver1-1  | 10:39:01 INFO Server[25]: Request finished in 34 ms
```

second server response:
```
qgis-issue-42063-qgisserver2-1  | 10:39:01 INFO Server[25]: Request finished in 391 ms
```

The GetLegengGraphic query does not work: generated image only contains the layer title.
http://localhost:8081/ows/?service=WMS&map=/io/data/test_2.qgs&request=GetLegendGraphic&version=1.3.0&LAYERS=vector_bat_as_wms
![image](https://github.com/qgis/QGIS/assets/6583528/76969105-fdea-4428-aacc-90967057c645)

It seems the `GetLegengGraphic` query is cascaded as expected, but this request is made asynchronously. Here are the relevant logs:

initial query received by QGIS#2:
```
qgis-issue-42063-qgisserver2-1  | 10:47:36 INFO Server[25]: ******************** New request ***************
qgis-issue-42063-qgisserver2-1  | 10:47:36 INFO Server[25]: Request URL: http://localhost:8081/ows/?service=WMS&map=/io/data/test_2.qgs&request=GetLegendGraphic&version=1.3.0&LAYERS=vector_bat_as_wms
```

Cascaded query received by QGIS#1:
```
qgis-issue-42063-qgisserver1-1  | 10:47:36 INFO Server[25]: ******************** New request ***************
qgis-issue-42063-qgisserver1-1  | 10:47:36 INFO Server[25]: Request URL: http://172.18.0.1:8080/ows/?MAP=/io/data/test.qgs&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetLegendGraphic&LAYER=vector_bat&FORMAT=image/png&STYLE=default&SLD_VERSION=1.1.0&TRANSPARENT=true
```

Initial query response:
```
qgis-issue-42063-qgisserver2-1  | 10:47:36 INFO Server[25]: Request finished in 3 ms
```

Cascaded query response:
```
qgis-issue-42063-qgisserver1-1  | 10:47:36 INFO Server[25]: Request finished in 17 ms
```

Sniffing the traffic with wireshark confirmed this asynchronous behaviour.

# Code analysis

Looking in the code, I guess QgsWmsLegendNode::getLegendGraphic is called asynchronously.

https://github.com/qgis/QGIS/blob/5b2c0e4fa658eb92dafc605230b60320ec369b18/src/core/layertree/qgslayertreemodellegendnode.cpp#L1272

The sync/async behaviour is driven by `QgsLegendSettings::mSynchronousLegendRequests` flag.

It seems the only time this setting is `true` is when printing layouts:
https://github.com/qgis/QGIS/blob/5b2c0e4fa658eb92dafc605230b60320ec369b18/src/core/layout/qgslayoutitemlegend.cpp#L133.

This setting should also be set to true somewhere in `src/server/`

Around here
https://github.com/qgis/QGIS/blob/5b2c0e4fa658eb92dafc605230b60320ec369b18/src/server/services/wms/qgswmsgetlegendgraphics.cpp#L53
or there
https://github.com/qgis/QGIS/blob/5b2c0e4fa658eb92dafc605230b60320ec369b18/src/server/services/wms/qgswmsrenderer.cpp#L117

**Comment by maxencelaurent** [comment]
Starting from my previous comment, I just checked the `getLegendGraphic` behaviour when using `GetPrint` queries.
I added a layout names "layout" in my reproducer.

As expected, the legend is fine when printing PDF maps:
http://localhost:8081/ows/?service=WMS&map=/io/data/test_2.qgs&request=GetPrint&version=1.3.0&width=512&height=512&crs=EPSG:2056&map0:EXTENT=2539106,1184111,2539880,1184814&map0:LAYERS=vector_bat_as_wms&map0:SCALE=25000&map0:STYLED=default,default&TEMPLATE=layout&FORMAT=pdf
![image](https://github.com/qgis/QGIS/assets/6583528/00f62871-0795-4c74-a28c-4f80dc3cc50a)



But the legend is still missing when the FORMAT is not PDF. Here is the same request with `FORMAT=png`.

http://localhost:8081/ows/?service=WMS&map=/io/data/test_2.qgs&request=GetPrint&version=1.3.0&width=512&height=512&crs=EPSG:2056&map0:EXTENT=2539106,1184111,2539880,1184814&map0:LAYERS=vector_bat_as_wms&map0:SCALE=25000&map0:STYLED=default,default&TEMPLATE=layout&FORMAT=png

![image](https://github.com/qgis/QGIS/assets/6583528/674be5bc-9f56-480f-8855-43e996eacc26)
