### ISSUE TITLE
Confusing SRID tooltip for pgraster layers in browser

### ISSUE THREAD

**Issue by timlinux** [qgis/QGIS#42068]
In the browser there is a tooltip for the SRID of raster layers that does not match the layer properties or assigned SRID which had me really confused:
Tooltip:

![Screenshot from 2021-03-05 17-41-27](https://user-images.githubusercontent.com/178003/110153099-7e492f00-7dda-11eb-9044-aa0e39080440.png)

Raster browser node properties:

![image](https://user-images.githubusercontent.com/178003/110152687-f2370780-7dd9-11eb-8263-272194a6677c.png)

QGIS Version:

QGIS version | 3.17.0-Master | QGIS code revision | df28e637cd
-- | -- | -- | --
Compiled against Qt | 5.14.2 | Running against Qt | 5.14.2
Compiled against GDAL/OGR | 3.1.3 | Running against GDAL/OGR | 3.1.3
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.33.0 | Running against SQLite | 3.33.0
PostgreSQL Client Version | 12.5 (Ubuntu 12.5-0ubuntu0.20.10.1) | SpatiaLite Version | 5.0.0
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 7.1.0 | Running against PROJ | Rel. 7.1.0, August 1st, 2020
OS Version | Pop!_OS 20.10 | This copy of QGIS writes debugging output.
Active python plugins | Mergin; quick_map_services; MetaSearch; processing; db_manager

cc @elpaso ?

**Comment by elpaso** [comment]
I see a `srid=0` in you data source, why?

**Comment by jgrocha** [comment]
Can not confirm @timlinux. The tooltip seems fine to me.

My overviews have the correct srid, as pointed out by @elpaso 

![srid-3763](https://user-images.githubusercontent.com/163681/110185353-0dba0680-7e0a-11eb-9d0a-2e51d9a6701e.png)

**Comment by timlinux** [comment]
Ah I missed the srid in my datasource, I was looking at the CRS. I'm still confused why the SRID shows in the datasource. Note that the screenshot above was from right clicking on the layer in the pg section of the browser, not from the added layer after it is loaded in QGIS. I loaded the data into the database, specifying the srid in the process:

https://github.com/kartoza/MarceiraMerginSyncProject/#loading-raster-layers

```
gis=# select r_table_name, srid from raster_columns ;
```

  r_table_name  | srid 
----------------|------
 orthophoto     |    0
 o_2_orthophoto |    0
 o_4_orthophoto |    0
 dtm            |    0
 o_2_dtm        |    0
 o_4_dtm        |    0
 dsm            |    0
 o_2_dsm        |    0
 o_4_dsm        |    0

(9 rows)


How does QGIS determine the CRS in the table properties versus the SRID in the connection string? I will poke around in my raster2pgsql loader to see what I am doing wrong....

**Comment by jgrocha** [comment]
@timlinux Maybe there is some configuration missing in your Postgresql docker image. I always set these two option when running from images, but mostly because I also use out-of-db rasters.
```  
postgres-server:
    image: postgis/postgis:13-master
    environment:
      POSTGIS_ENABLE_OUTDB_RASTERS: 1
      POSTGIS_GDAL_ENABLED_DRIVERS: ENABLE_ALL
```
And, of course, in my initialization script I use:
```
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS postgis_raster;
```
Your `raster2pgsql`seems fine to me. 

But I always make sure that the raster itself has the proper CRS defined. For example, even using `raster2pgsql -s 3763` I do make sure that each tif file or vrt also the right CRS. I use this kind of script very often:
```
#!/bin/bash
for f in *.tif
do
	echo "Processing $f"
  	# assign projection to $f
	gdal_edit.py -a_srs "EPSG:3763" $f
done
```

I summary, I can not help you much because I don't know why your rasters are not properly registered in Postgis. 

Check the CRS of the rasters:
- `gdalinfo orthophoto`
- `gdalinfo dtm`
- `gdalinfo dsm`

Make sure the postgresql image is properly set up (the extensions are loaded and GDAL environment variables are defined).

My rasters are well defined in Postgis and I didn't do anything special:

![rasters](https://user-images.githubusercontent.com/163681/110391915-10ae3480-8060-11eb-897b-18f732aaec02.png)

If you can share one of your failing rasters, I can test it on my environment.

**Comment by timlinux** [comment]
Thanks so much for the helpful hints! I will test tomorrow and revert.

**Comment by timlinux** [comment]
So some feedback on your notes above @jgrocha : 

>      POSTGIS_ENABLE_OUTDB_RASTERS: 1
>     POSTGIS_GDAL_ENABLED_DRIVERS: ENABLE_ALL

I think these vars are both relevant for external rasters. In my case the rasters are loaded as tables in the database.

> CREATE EXTENSION IF NOT EXISTS postgis;
> CREATE EXTENSION IF NOT EXISTS postgis_raster;

Confirm this is the case (I am using the kartoza/postgis image btw).

> But I always make sure that the raster itself has the proper CRS defined.

This I can confirm too - the images are from ODM:

```
timlinux@valley ~/g/M/orthophoto> gdalinfo odm_orthophoto--7March2021.tif 
Driver: GTiff/GeoTIFF
Files: odm_orthophoto--7March2021.tif
Size is 4395, 3737
Coordinate System is:
PROJCRS["WGS 84 / UTM zone 29N",
    BASEGEOGCRS["WGS 84",
        DATUM["World Geodetic System 1984",
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4326]],
    CONVERSION["UTM zone 29N",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",-9,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9996,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",500000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["unknown"],
        AREA["World - N hemisphere - 12°W to 6°W - by country"],
        BBOX[0,-12,84,-6]],
    ID["EPSG",32629]]
``` 

Lastly, I tried manually setting the SRID in PostGIS and get this:

```
gis=# SELECT UpdateRasterSRID(raster, orthophoto, rast, 32629);
ERROR:  column "raster" does not exist
LINE 1: SELECT UpdateRasterSRID(raster, orthophoto, rast, 32629);
                                ^
```

I believe I formulated the above correctly according the [pgraster docs](http://postgis.org/documentation/manual-2.1SVN/RT_UpdateRasterSRID.html).

Anyway, I guess we are now way out in 'not broken here' territory for QGIS so I will close this and move the discussion upstream.

**Comment by NyakudyaA** [comment]
@timlinux I also tested this and I think something is not working fine when using postgis out-db raster with the QGIS Browser, Datasource manager

This is what I did
* Run the docker container
* Run the following commands
```
ALTER DATABASE gis SET postgis.enable_outdb_rasters = true;
ALTER DATABASE gis SET postgis.gdal_enabled_drivers TO 'ENABLE_ALL';
```
* Load my raster in the DB using the following
```
raster2pgsql -s 32733 -t 100x100 -I -R /tmp/srtm_41_19.tif dem | psql -d gis -p 5432 -U docker -h localhost
```
* On my host make sure that the raster also exists in the same path as the docker container - Because I did not mount the file
* Inspect the SRID of the raster using Browser, DBManager and it shows 0.
![Peek 2021-03-09 13-31](https://user-images.githubusercontent.com/2510900/110464714-295c3000-80dc-11eb-91af-c5140add129b.gif)

In the DB I ran the following
```
SELECT (ST_BandMetaData(rast)).* FROM pop12 LIMIT 1;
```

**Comment by jgrocha** [comment]
@NyakudyaA Do you also use Apple laptops without linux, like @timlinux ? That's the problem :-)

Going seriously: I've inserted a ODM generated orto with:
```
raster2pgsql -s 32629 -d -I -C -R -M -l 4,8,16,32,64,128,256,512 `pwd`/odm_orthophoto.tif -F -t 1000x1000 public.odmorto | psql service=osm
```
I've tried in-db and out-of-db and both work well. QGIS browser shows the tip as expected:

![Captura de ecrã de 2021-03-09 11-46-34](https://user-images.githubusercontent.com/163681/110466622-e85d1f00-80cd-11eb-93bd-17745f0a00f1.png)

You both need to check the GDAL version in use. You are running `raster2pgsql` on your host machine and Postgresql in a docker machine, right? Please report both version of GDAL: for the host where you run `raster2pgsql` and for the Postgresql running (using `select postgis_full_version();`).

I suspect that there is some old GDAL some where.

**Comment by NyakudyaA** [comment]
> @NyakudyaA Do you also use Apple laptops without linux, like @timlinux ? That's the problem :-)

haha, I am on ubuntu
> 
> Going seriously: I've inserted a ODM generated orto with:
> 
> ```
> raster2pgsql -s 32629 -d -I -C -R -M -l 4,8,16,32,64,128,256,512 `pwd`/odm_orthophoto.tif -F -t 1000x1000 public.odmorto | psql service=osm
> ```
> 
> I've tried in-db and out-of-db and both work well. QGIS browser shows the tip as expected:
> 
> ![Captura de ecrã de 2021-03-09 11-46-34](https://user-images.githubusercontent.com/163681/110466622-e85d1f00-80cd-11eb-93bd-17745f0a00f1.png)
> 
> You both need to check the GDAL version in use. You are running `raster2pgsql` on your host machine and Postgresql in a docker machine, right? Please report both version of GDAL: for the host where you run `raster2pgsql` and for the Postgresql running (using `select postgis_full_version();`).
> 
> I suspect that there is some old GDAL some where.

Thanks @jgrocha , The problem occurs when you do not specify the `-C` option. If you run the command without that the SRID is not populated.

**Comment by timlinux** [comment]
> > @NyakudyaA Do you also use Apple laptops without linux, like @timlinux ? That's the problem :-)
> 
> haha, I am on ubuntu

I'm on Pop_os!

> Thanks @jgrocha , The problem occurs when you do not specify the -C option. If you run the command without that the SRID is not populated.

Confirmed - adding the -C options resolved the issue for me too. Thanks @jgrocha and @NyakudyaA !
