### ISSUE TITLE
WFS cascade getfeatureinfo fails

### ISSUE THREAD

**Issue by frippe12573** [qgis/QGIS#42062]
The issue is related to the getfeatureinfo function for WFS cascade layer in QGISserver.
In particular, getfeatureinfo doesn't return any value for WFS cascade layer.
In the qgisserver.log only a warning is shown:
`14:47:21 WARNING [16307]: Warning: error parsing post data as XML: at line 1, column 1: error occurred while parsing element. Assuming urlencoded query string sent in the post body.'

I tested a project with just 2 layers: 

- one from a third party: https://demo.geo-solutions.it/geoserver/wfs layer: geosolutions:regioni
- one from my organization: http://repo2.igg.cnr.it/geoserver/IGG/wfs layer: IGG:pozzi_decodificati_tr_pdf

the QGIS project file is available from here: https://filebin.net/co3dlgmm1mwrmmkt

To reproduce the issue, just click on a feature to get the information.
It could happen that for unknown  reasons a results could be shown, but trying other times it starts to stop working.

QGIS server 3.16
QGIS desktop 3.18
Ubuntu18.04 LTS

**Comment by elpaso** [comment]
@frippe12573 can you re-upload the failing project?

**Comment by frippe12573** [comment]
The QGIS project file is available again from here: [Here](http://owncloud.iclos.com/index.php/s/Yeif65RDNppEnHR)

**Comment by elpaso** [comment]
I tested your project and everything looks fine on master.

**Comment by frippe12573** [comment]
> I tested your project and everything looks fine on master.

I have not the possibility to test it quickly in the master version , I have to wait for the new release (I got 3.18.3+32focal), when is the new version foreseen, I mean the new package version?
