### ISSUE TITLE
RuntimeError: wrapped C/C++ object of type AlgorithmDialog has been deleted 

### ISSUE THREAD

**Issue by tschmetzer** [qgis/QGIS#42069]
I wrote a small python script as a processing tool. When I run it I only get a RuntimeError and no other hints.
![grafik](https://user-images.githubusercontent.com/67278094/109501525-fe4c5d80-7a97-11eb-9e87-8c5cc3092ec9.png)

The error Message:
```
An error has occurred while executing Python code: 

RuntimeError: wrapped C/C++ object of type AlgorithmDialog has been deleted 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\gui\AlgorithmDialog.py", line 246, in runAlgorithm
    on_complete(ok, results)
  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\gui\AlgorithmDialog.py", line 201, in on_complete
    self.tr('Execution completed in {0:0.2f} seconds').format(time.time() - start_time))
RuntimeError: wrapped C/C++ object of type AlgorithmDialog has been deleted
```

The script merely reorders some attributes from source and adds them to the sink.

I desperately tried to find out why it doesn't work, consulting gis.stackexchange and other issues. As descibed in https://github.com/qgis/QGIS/issues/41869#issuecomment-789592212 in order to avoid any unknown thread issues I also added the function
```
def flags(self): 
return super().flags() | QgsProcessingAlgorithm.FlagNoThreading
```

I tried adding features directly to the sink via `sink.addFeature(feature)` and at last via a temporal layer whose features are successfully committed before copied to the sink. I suspected the objects not to be written to the memory before completely being transferred to the sink and as soon as the AlgorithmDialog is closed some objects required by the OUTPUT layer aren't available anymore. I tried with and without `QgsFeatureSink.FastInsert`. Nothing worked. And especially no idea why QGIS doesn't point the user to any error (which is why I created this issue). The script itself terminates without any error and the debug logfile shows valid and correct log entries until the end. There's no problem outputting all attribute values of templayer to the debug log. When less than 500 features are calculated and transferred from source to sink the OUTPUT is created without any problems. With more than 1000 features calculated and transferred the runtime error occurs.

I am attaching the script and example data:
[sumDirections.zip](https://github.com/qgis/QGIS/files/6093342/sumDirections.zip)

If this is no bug but an error in my script I am very sorry and I'll reward it with updating the docs for a common mistake I seem to be making and as a solution to this ticket.

(By the way - the geometry.area() method doesn't seem to work on vertical geometries using z-values as it returns 0 or very small values for all walls)

**Comment by gioman** [comment]
> If this is no bug but an error in my script I am very sorry and I'll reward it with updating the docs for a common mistake I seem to be making and as a solution to this ticket.

@tschmetzer if in doubt you should ask in the developers mailing list first.

**Comment by jakimowb** [comment]
@tschmetzer 

I tried to run it and got this error:

````
Algorithm 'Collect and sum wall directions' starting…
Input parameters:
{ 'INPUT' : 'C:/OSGEO4~1/apps/qgis-dev/resources/data/world_map.gpkg|layername=countries', 'OUTPUT' : 'TEMPORARY_OUTPUT' }

Traceback (most recent call last):
File "<string>", line 205, in processAlgorithm
File "<string>", line 38, in init_logger
File "C:\OSGEO4~1\apps\Python37\lib\logging\__init__.py", line 1849, in basicConfig
h = FileHandler(filename, mode)
File "C:\OSGEO4~1\apps\Python37\lib\logging\__init__.py", line 1041, in __init__
StreamHandler.__init__(self, self._open())
File "C:\OSGEO4~1\apps\Python37\lib\logging\__init__.py", line 1070, in _open
return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\temp\\Summe_Richtungsbestimmung_Processing.log'

Execution failed after 0.25 seconds
````

So it might be related to your python-style `logging`. Maybe it helps if you use [`QgsProcessingFeedback.pushInfo(...)`](https://qgis.org/pyqgis/3.18/core/QgsProcessingFeedback.html?highlight=qgsprocessingfeedback#qgis.core.QgsProcessingFeedback.pushInfo) instead?

**Comment by tschmetzer** [comment]
@jakimowbThank you for running my script! Hmm, that's interesting. In contrary the produced log files are showing that the algorithm is executed until the end without any problem or error. Logging has not been an issue for me anymore since I established this stable logging setup half a year ago.No idea why the log file creation fails with your setup. Do others face the same issue? Have you tried creating an empty file with that name? (Which I don't need to do)Anyways I just tried and replaced the logging.debug by feedback.pushDebugInfo (of course not without adding the feedback argument to the calc() method) but besides a VERY slow output I still get the runtime error.Yet I found out that most of the time the runtime error occurs only the second time (!) I run the script when having restarted QGIS before.Regards, Tobias

**Comment by jakimowb** [comment]
@tschmetzer Running the algorithm with `directions_example.shp` and `logging` lines disabled gives me:
````
Feature (1) from “directions_example” has invalid geometry. Please fix the geometry or change the Processing setting to the “Ignore invalid input features” option.
Execution failed after 0.06 seconds
````

A validity check on `directions_example.shp` revealed several errors (3738 of 5318 features).
The processing algorithm finishes without error when using the 1580 valid features only, but did not produce any outputs.

![image](https://user-images.githubusercontent.com/1404870/110257900-32e07d80-7fa0-11eb-87e4-ec5ebc32f846.png)

**Comment by tschmetzer** [comment]
I forgot you mention invalid features need to be ignored (setting "Do not filter (better performance)") as walls are represented as vertical polygons and the validation algorithm seems to (presumably erroneously) recognize an invalid geometry. I checked several geometries by hand and couldn't find anything bad that would prevent my algorithm to run. My algorithms are written for this vertical wall design. Anyways in this particular algorithm the geometry is not of importance as only the attributes are rearranged. As my own algorithm is tailored to that data I am confident to ignore geometries marked as invalid by an algorithm that uses a different definition. See ticket #41963Can you try again turning filtering off? Or do you see any command I'm using ok the script that requires a valid geometry as input data?Regards, Tobias

**Comment by jakimowb** [comment]
Ok, I turned filtering of and now I get your error as well:

````
RuntimeError: wrapped C/C++ object of type AlgorithmDialog has been deleted 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis-dev/./python/plugins\processing\gui\AlgorithmDialog.py", line 269, in runAlgorithm
    on_complete(ok, results)
  File "C:/OSGEO4~1/apps/qgis-dev/./python/plugins\processing\gui\AlgorithmDialog.py", line 224, in on_complete
    self.tr(elapsed_time(start_time, 'Execution completed in')))
  File "C:/OSGEO4~1/apps/qgis-dev/./python/plugins\processing\gui\AlgorithmDialog.py", line 181, in elapsed_time
    str_hours = [self.tr("hour"), self.tr("hours")][hours > 1]
RuntimeError: wrapped C/C++ object of type AlgorithmDialog has been deleted

````

**Comment by jakimowb** [comment]
@tschmetzer it seems that (after removing the logging calls) your script works well when added to the Processing Toolbox.

So it seems that your QgsProcessingAlgorithm needs to be added to a [QgsProcessingProvider](https://qgis.org/pyqgis/3.18/core/QgsProcessingProvider.html) first, like the `ScriptAlgorithmProvider` "Scripts":

![image](https://user-images.githubusercontent.com/1404870/110548567-0d36ae00-8131-11eb-9eb7-ea1f8ca31ce9.png)

**Comment by tschmetzer** [comment]
Oh nice, hadn't tried this option. Adding the script to the toolbox works for me as well!
![grafik](https://user-images.githubusercontent.com/67278094/110613335-71895a00-8191-11eb-8784-e52a9f57c0a8.png)

Interestingly the only thing that happens when the script is added seems that it's copied to `C:\Users\[USERNAME]\AppData\Roaming\QGIS\QGIS3\profiles\default\processing\scripts` and no QgsProcessingProvider statement/reference is added.

Reconsulting the docs https://docs.qgis.org/testing/en/docs/user_manual/processing/toolbox.html I found the following hint:

> Providers can be (de)activated in the Processing settings dialog. By default, only providers that do not rely on third-party applications (that is, those that only require QGIS elements to be run) are active. Algorithms requiring external applications might need additional configuration. Configuring providers is explained in a later chapter in this manual.

This is the  Processing settings dialog the manual is referring to:
![grafik](https://user-images.githubusercontent.com/67278094/110623564-4b69b700-819d-11eb-9ed1-f7db14cfb37e.png)

So scripts seem to be treated as providers. Yet the docs refer to external/third party applications. The only illogical missing part that I don't understand yet is when or what part in my script (or in general any scripts) is regarded as external in contrast to other python scripts that can be run from any path.

I think it would be a good idea to add this hint to the documentation once this missing bit of background information about the reason is understood so that this can be communicated transparently in the docs.

Any ideas?

**Comment by tschmetzer** [comment]
Please review my draft for the documentation content wise:
https://github.com/qgis/QGIS-Documentation/pull/6579

Comments welcome!

**Comment by gioman** [comment]
@tschmetzer can we close this?

**Comment by tschmetzer** [comment]
With the documentation on its way I'd regard this issue as obsolete.
