### ISSUE TITLE
QGIS Unexpectedly ended

### ISSUE THREAD

**Issue by tmorahanpg** [qgis/QGIS#42065]
Windows 10 Home v1909 OS build 18363.1379

In Data Source Manager | Browser, navigating to find the training file exercise_data/world/world.qgs, QGIS hung. I killed it in task manager. Here's the report: 

Crash ID: 5b8ebf2cb8a8bc83a3de8aff5739a2c643f0a74f

Stack Trace

QWidget::mapTo :
QWidgetPrivate::moveRect :
QApplication::windowIcon :
QApplication::windowIcon :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1637
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.16.3-Hannover
QGIS code revision: 94ac9f21b8
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
@tmorahanpg try with a new QGIS profile, no 3rd party plugins installed.

**Comment by gioman** [comment]
Closing for lack of feedback.

**Comment by tmorahanpg** [comment]
Thank you! My problem was solved!
