### ISSUE TITLE
QGIS Crash Report

### ISSUE THREAD

**Issue by AlexSinykin9385** [qgis/QGIS#42091]
I'm attempting to edit a polygon feature layer of world countries. Every time i snap the vertex to the new location it freezes and QGIS Crashes.
![QGIS_CRASH](https://user-images.githubusercontent.com/26166837/110257233-1b7ea180-7f5a-11eb-8300-47129772b21d.png)

**Comment by gioman** [comment]
@AlexSinykin9385 

try with a new QGIS profile, no 3rd party plugins installed.

Add **all** the requested infos here:




**Describe the bug**


**How to Reproduce**



1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error -->

**QGIS and OS versions**



**Additional context**

**Comment by roya0045** [comment]
Also need more information about the data source.

**Comment by AlexSinykin9385** [comment]
I'm using QGIS 3.16. I just tried again by opening a brand new template and loading in the world countries layer file.
The layer can be downloaded here: https://alexsinykingis.maps.arcgis.com/home/item.html?id=4f9a823cb0aa4276b7c37d873372bb1e

Steps 

1. Load QGIS
2. Load the World Country layers
3.  Set the background color to blue
4.  Change the project properties projection to: Australian Antarctic (Geocentric) EPSG 4340
5.  Edit the green line that cuts through antarctica
6.  QGIS Crashes
![image](https://user-images.githubusercontent.com/26166837/110257925-52a28200-7f5d-11eb-8342-4ee6d5de4ce5.png)

**Comment by gioman** [comment]
> The layer can be downloaded here: https://alexsinykingis.maps.arcgis.com/home/item.html?id=4f9a823cb0aa4276b7c37d873372bb1e

@AlexSinykin9385 we don't have ESRI accounts around here ;) please attach the vector here as ZIP or link it to a platform where no credentials are needed. Thanks!




>  just tried again by opening a brand new template

@AlexSinykin9385 do you mean new "profile"?

**Comment by AlexSinykin9385** [comment]
Oops, I thought it would download as .shp. The zip is attached.
[World_Countries.zip](https://github.com/qgis/QGIS/files/6098129/World_Countries.zip)

**Comment by gioman** [comment]
> Oops, I thought it would download as .shp. The zip is attached.
> [World_Countries.zip](https://github.com/qgis/QGIS/files/6098129/World_Countries.zip)

@AlexSinykin9385 no crash here on 3.18 on Linux. But also there are other issues (like not possible to select feature in the canvas and moving nodes/vertexes creates very weird results... anyway both this issue must be reported in separate tickets).

**Comment by AlexSinykin9385** [comment]
Ok, Thanks.

**Comment by gioman** [comment]
Closing for lack of feedback.
