### ISSUE TITLE
Georeferencer not able to create result (3.18)

### ISSUE THREAD

**Issue by Acurus** [qgis/QGIS#42093]
**Describe the bug**

The georeferencer crashes during processing of a simple georeference. No error message is provided.

**How to Reproduce**
1. Load attached dataset in the georeferencer
2. Transformation type: Helmert
3. Resampling: Nearest Neighbour
4. Target CRS 32632
5. Compression LZW
6. Press "Start Georeferencing"

Then the window for the progress bar appears, but does not render a progress bar. And QGIS becomes none responsive. 

When trying the exact same thing in 3.16.4 it works flawlessly.

**QGIS and OS versions**

QGIS version
3.18.0-Zürich
QGIS code revision
bdef9fb3
Compiled against Qt
5.15.2
Running against Qt
5.15.2
Compiled against GDAL/OGR
3.2.1
Running against GDAL/OGR
3.2.1
Compiled against GEOS
3.9.1-CAPI-1.14.2
Running against GEOS
3.9.1-CAPI-1.14.2
Compiled against SQLite
3.33.0
Running against SQLite
3.33.0
Compiled against PDAL
2.2.0
Running against PDAL
2.2.0 (git-version: 38aa11)
PostgreSQL Client Version
13.0
SpatiaLite Version
5.0.1-rc1
QWT Version
6.1.3
QScintilla2 Version
2.11.5
Compiled against PROJ
7.2.1
Running against PROJ
Rel. 7.2.1, January 1st, 2021
OS Version
Windows 10 Version 2009
Active python plugins
lrs; 
qfieldsync; 
shapetools; 
db_manager; 
MetaSearch; 
processing

[georeferencer.zip](https://github.com/qgis/QGIS/files/6099637/georeferencer.zip)

**Comment by gioman** [comment]
@Acurus already reported several times and already fixed. Wait 3.18.1 or use 3.16 in the meantime.

**Comment by Gustry** [comment]
It has already been reported many times. https://github.com/qgis/QGIS/issues?q=is%3Aissue+georeferencer

Wait for 3.18.1

**Comment by Acurus** [comment]
My appologies!
