### ISSUE TITLE
Problem to Create a feature with QGIS in database PostgreSQL PostGIS with Trigger that add the 'id' with a function that is not native to PostgreSQL

### ISSUE THREAD

**Issue by arx-it** [qgis/QGIS#42095]
Hi,

I created a Trigger in PostgreSQL to add new value, for an 'id' field of a layer.

Tests :
- If I create a new row with pgAdmin, it works
- If I create a new entity with ArcGIS Pro, it works
- If I create a new entity with QGIS, it asks to me a value for the id (attributes pannel) and I cannot click OK without enter a value :
![image](https://user-images.githubusercontent.com/12830337/110306080-b7151e00-7ffd-11eb-8e54-960213c58450.png)

I found a workaround, with "Enforce not null constraint" :
![image](https://user-images.githubusercontent.com/12830337/110306361-08251200-7ffe-11eb-8c4a-9aa4a0d6ea2d.png)
But my users need to do this in layers, without pre-parameters in a QGIS Project.

Is it a bug ?
Is there a way to not open the attributes panel after geometry creation ?

Version QGIS 3.14.0
OS : Windows 10

Thank you.

**Comment by gioman** [comment]
> Version QGIS 3.14.0

@arx-it way too old, you must try with the latest 3.16 or 3.18.

if the problem persist please add/attach here your table and trigger SQL definitions.

**Comment by arx-it** [comment]
OK, i try with 3.16 (i saw that there is problems with 3.18 Windows installer) and i come back to you
Thanks

![image](https://user-images.githubusercontent.com/12830337/110308830-e5482d00-8000-11eb-90c6-2d7e2e95f160.png)

**Comment by andreasneumann** [comment]
@arx-it - if you use PostgreSQL, it is advised that you use the following 2 settings (project properties):

- Automatically create transaction groups where possible
- Evaluate default values on provider side

![image](https://user-images.githubusercontent.com/884476/110310557-f85bfc80-8002-11eb-8f9b-2f1693506d1c.png)


If you enable these 2 settings, all layers will be edited at once (in a single transaction, until you save it or close editing with saving). "Evaluate default values on provider side" will fetch the pkey immediately from the PG db without bothering the user with it.

**Comment by arx-it** [comment]
Thank you.
We tried with these options, with QGIS 3.16.4, but we have the same problem.

We use SDE (SDE) overlay in PostgreSQL / PostGIS Database, because some users still use Esri.

Here is the trigger :

`CREATE OR REPLACE FUNCTION update_id() 

RETURNS trigger AS

$BODY$
BEGIN 
NEW.id= sde.next_rowid('appr', test);
RETURN NEW;
END;

$BODY$ LANGUAGE plpgsql
CREATE TRIGGER test_trigger BEFORE Insert
ON appr. test
FOR EACH ROW EXECUTE PROCEDURE update_id ();‍‍‍‍‍`

Thanks

**Comment by arx-it** [comment]
With this option (disabling attributes popup), it works :
![image](https://user-images.githubusercontent.com/12830337/110328950-46312e80-801c-11eb-9e2f-731774286698.png)

**Comment by gioman** [comment]
> With this option (disabling attributes popup), it works  

@arx-it yes this is ind of expected, because the "block" resides in how QGIS adds a constraint for that column. No form, no constraint. At least this is how I read this scenario.

**Comment by gioman** [comment]
>  sde.next_rowid('appr', test);

@arx-it if this is a SDE specific function I guess I will not be able to test it here locally, I have no ESRI stuff.

**Comment by arx-it** [comment]
Ok, this workaround is OK for us, without form

**Comment by andreasneumann** [comment]
hm - I don't agree that this should be closed. If it doesn't work without supressing the form, that seems like an awful bug to me.

However, in my own QGIS projects I don't observe this problem. I think this  deserves to be investigated further. It should certainly work without supressing the attribute editor window.

**Comment by gioman** [comment]
> hm - I don't agree that this should be closed. If it doesn't work without supressing the form, that seems like an awful bug to me.

@andreasneumann agree


> However, in my own QGIS projects I don't observe this problem. I think this deserves to be investigated further.

It probably relates to how QGIS evaluates the column that has this trigger with a function that is not native to PostgreSQL.


@arx-it would you mind to edit the title to better reflect this case?

**Comment by uclaros** [comment]
@arx-it Can you also share the DDL - create statement for a table to replicate?

**Comment by andreasneumann** [comment]
Perhaps the issue here is the "Trigger" versus "Sequence" (the normal case).

**Comment by arx-it** [comment]
Are you able to use this SQL Query ?
Thanks

**Comment by uclaros** [comment]
The problem is that the `ID` field is made to be unique by postgresql's unique index, so QGIS honors it and does not allow entering non unique values on the form (The *not null* and *unique* constraints on the screenshot are greyed out).
Disabling the form makes it work, since no value check is performed and the unique ID is handled directly by the trigger.
Also, this is why the *enforce constraints* checkboxes exist, to allow for such trigger use cases.

**Comment by arx-it** [comment]
Ok thank you for these informations

**Comment by arx-it** [comment]
If its is OK for the community, the workaround with the option (disabling attributes popup) is OK for me

**Comment by arx-it** [comment]
Can I close ?

**Comment by lumin8** [comment]
This really shouldn't be closed.   This affects a greater community of users and appears to persist to 3.24.0-Tisler.   Suppressing a pop up form is quite inconvenient, and isn't an acceptable workaround for pasting features.

Problem:  pasting a feature into a layer directly linked (and in our case, remote) to a PostGIS database does not insert feature due to error of unique id violation.  

````
Errors: ERROR: 1 feature not added.
  
  Provider errors:
      PostGIS error while adding features: ERROR:  null value in column "gid" violates not-null constraint
    DETAIL:  Failing row contains (null [...]
```

**Comment by arxitaqu** [comment]
Thank you for this additional information
