### ISSUE TITLE
Erro no Qgis na parte de Definição de geometria 

### ISSUE THREAD

**Issue by projeto-acoes** [qgis/QGIS#42099]
Ao adicionar uma camada de texto delimitada e ir na parte de configuração para Definição de geometria a única opção de coordenada é a de  latitude long

**Comment by gioman** [comment]
@projeto-acoes Tickets must be filed in English and the following template must be used. Obrigado.



**Describe the bug**


**How to Reproduce**



1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error -->

**QGIS and OS versions**



**Additional context**
