### ISSUE TITLE
Handle bad layers dialog does not support point clouds

### ISSUE THREAD

**Issue by wonder-sk** [qgis/QGIS#42113]
When a QGIS project is loaded with a broken path to a point cloud layer, the user is unable to fix the path in the dialog (browse button is disabled).

It is also strange that the "provider" column says "none" although the project file says it is "pdal" provider.

![image](https://user-images.githubusercontent.com/193367/110384442-ee1b1c00-805d-11eb-95ca-8a8f4e65b3d2.png)

**Comment by roya0045** [comment]
The provider comes from https://github.com/qgis/QGIS/blob/22d082661547abe008c229798f683263bc6323cc/src/app/qgshandlebadlayers.cpp#L129 pdal should also be added to https://github.com/qgis/QGIS/blob/22d082661547abe008c229798f683263bc6323cc/src/app/qgshandlebadlayers.cpp#L131
