### ISSUE TITLE
Empty tabs in the About dialog

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#42131]
![emptyAbout](https://user-images.githubusercontent.com/7983394/110413128-a1e7d000-808d-11eb-8a2e-417bd2b57e40.gif)

QGIS version | 3.19.0-Master | QGIS code revision | c6eec9db10
-- | -- | -- | --
Compiled against Qt | 5.12.8 | Running against Qt | 5.12.8
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.6 (Ubuntu 12.6-0ubuntu0.20.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Ubuntu 20.04.2 LTS | This copy of QGIS writes debugging output.
Active python plugins | db_manager; MetaSearch; processing

**Comment by agiudiceandrea** [comment]
I see all the tabs populated in the MinGW Windows build of a recent QGIS 3.19.0-Master d7a0f0bc

![image](https://user-images.githubusercontent.com/16253859/110470697-75f33b80-80db-11eb-9bbc-bb1dbffc5b59.png)
![image](https://user-images.githubusercontent.com/16253859/110470839-a63ada00-80db-11eb-9b3c-86bfe7d25f42.png)

Anyway, the What's New tab is outdated: it lists "3.12 ‘București’" as the latest available "what's new", so 3.14, 3.16 and 3.18 "what's new" are missing. This also affects QGIS 3.16 and I suppose QGIS 3.18, too. See https://lists.osgeo.org/pipermail/qgis-user/2021-February/048218.html

**Comment by Pedro-Murteira** [comment]
This issue does not occur on QGIS 3.22.3.

**Comment by DelazJ** [comment]
I still do have it on my self-compiled master version on Ubuntu 20.04, new profile
![Peek 15-02-2022 07-50](https://user-images.githubusercontent.com/7983394/154008103-c96832c5-4aad-465d-9d30-b6a760517fe4.gif)

**Comment by gioman** [comment]
> I still do have it on my self-compiled master version on Ubuntu 20.04, new profile

@DelazJ and installing from qgis repos?
