### ISSUE TITLE
Editing POLYGON wants to save as MULTISURFACE

### ISSUE THREAD

**Issue by derekwatling** [qgis/QGIS#42134]
When editing a PostGIS layer ([MULTI]POLYGON) in QGIS 3.16.1 it is saving the edit back as a MULTISURFACE. Is there any way to prevent MULTISURFACE and CURVEd line segments being created?

**Comment by gioman** [comment]
@derekwatling can you elaborate?

do you get an error message?

or have you found it by looking at the logs?

what is your table SQL definition?

**Comment by derekwatling** [comment]
@gioman We have a number of PostGIS tables with definitions similat to:

CREATE TABLE map.suburb (
  pkid INTEGER NOT NULL,
  suburb_name TEXT,
  geom public.geometry,
  CONSTRAINT suburb_pkey PRIMARY KEY(pkid)
) 
WITH (oids = false);

These geometries are all of type [MULTI]POLYGON with srid=3857

When we edit in QGIS (just moving 1 vertex is enough) the resulting geometry being saved back is MULTISURFACE(CURVEPOLYGON((...)))

This came to our attention as 1 of the tables has a trigger that calculates area on the sphere and this requires a transformation to the geography type, which threw an error.

**Comment by gioman** [comment]
@derekwatling what if you declare/create you geom column as [MULTI]POLYGON  and not just as "geometry"?

**Comment by gioman** [comment]
> CREATE TABLE map.suburb (
> pkid INTEGER NOT NULL,
> suburb_name TEXT,
> geom public.geometry,
> CONSTRAINT suburb_pkey PRIMARY KEY(pkid)
> )
> WITH (oids = false);

@derekwatling 


I created the table with the above definition, added the layer to a project specifying to add it as POLYGON, digitized a few features, checked with 

`SELECT ST_GeometryType(geom) FROM suburb;`

geometries are POLYGONS.

**Comment by derekwatling** [comment]
@gioman Thank you for your input. We created a sample table to experiment with, but have been unable to recreate the issue.

I would like to ask how you specify a layer as POLYGON when adding it to a project? I have not been able to find any options.

**Comment by gioman** [comment]
> I would like to ask how you specify a layer as POLYGON when adding it to a project?

i.e. see this screencast

https://github.com/qgis/QGIS/issues/42138#issue-825881610

or just use the normal "add postgis layer" dialog and select both the geom type and CRS (but you really declare both them in your query SQL definition).

**Comment by gioman** [comment]
Closing for lack of feedback.

**Comment by dpsspatial** [comment]
Adding some (late) feedback, but the issue seems to be caused by the generic 'geometry' type in a postgis table, vs. a specific point, linestring, polygon/multipolygon type.

When editing a column of 'geometry' type that contains polygons, QGIS will save edits as multisurface for that specific feature only, meaning the remaining polygons will stay polygon or multipolygon.

However, if a table of the same geometry stored in a specific 'multipolygon' column is edited, the geometry type is not changed.

**Comment by FredrikEkstrom79** [comment]
Why dosn't QGIS saves the edited feature with as simple type as possible? A MultiPolygon with all stright lines dosn't need to be saved as MultiSurface regadless of if the table uses geometry or not. This behavior was changed in QGIS 3.10 if i remember correctly what i have read in other forums (can't find it now) before that everything worked as expercted.

What triggers QGIS to choose MultiSurface before trying to to save it as MultiPolygon?
