### ISSUE TITLE
CRS problems

### ISSUE THREAD

**Issue by EnzoBaldini** [qgis/QGIS#42148]
I have a shapefile of german districts, which I downloaded [here](https://daten.gdz.bkg.bund.de/produkte/vg/vg2500/aktuell/vg2500_01-01.utm32s.shape.zip) and did not change after download. 

Ypou can download the the raw and processed data [here](https://wetransfer.com/downloads/46bad5bc3cba337096109b663e1664b720210309184837/07552a7173d9d46e40fabbe7d12ab1d820210309184900/135f32).

1. I load the shapefile "vg2500_lan" to a new project, select the feature of bavaria and want to save it as a single shapefile "bavaria_25832.shp":

![screenshot_1](https://user-images.githubusercontent.com/50318977/110519337-79071f80-810d-11eb-865d-638afb314f81.PNG)

2. The resulting shapefile lost its crs tag indicated by the questionmark in the layer panel:

![screenshot_2](https://user-images.githubusercontent.com/50318977/110519367-858b7800-810d-11eb-9345-32634294ac8d.PNG)

3. I select again the feature of bavaria in the original shapefile as in step 1. This time I want to save the new layer in EPSG 4326:

![screenshot_3](https://user-images.githubusercontent.com/50318977/110519517-b79cda00-810d-11eb-8081-37c4ceb4693e.PNG)

4. It seems the resulting shapefile gets only the CRS definition but it is not reprojected to the new CRS indicated by the bounding box coordinates in the layers setting and the fact the layer is not appearing in the project on top of the other layers. Because it is still in fact projected in 25832 but with CRS definition EPSG 4326:

![screenshot_4](https://user-images.githubusercontent.com/50318977/110519532-bd92bb00-810d-11eb-99d8-4923aadb5578.PNG)

5. I start a new project. I first load the "bavaria_4326.shp" into the project. The second layer I load into the new project is the original "vg2500_lan.shp". 

![screenshot_5](https://user-images.githubusercontent.com/50318977/110519557-c3889c00-810d-11eb-8679-eb2c333c443c.PNG)

6. I click on "zoom full extent" of the project and get a weird result:

![screenshot_6](https://user-images.githubusercontent.com/50318977/110519770-fdf23900-810d-11eb-9002-ea5955b44cca.PNG)

7. I right-click on the original (!) shapefile "vg2500_lan.shp" and choose "zoom to layer extent". I get again a weird result:

![screenshot_7](https://user-images.githubusercontent.com/50318977/110519855-19f5da80-810e-11eb-9ad1-e20e17778180.PNG)

8. I change the project CRS to 25832. The layer "bavaria_4326" is not shown in the map panel. I assign the CRS 25832 to the layer "bavaria_4326.shp" because I want to proove my assumption from step 4. The "missing" layer "bavaria_4326" is shown again in the map panel.

![screenshot_8](https://user-images.githubusercontent.com/50318977/110523068-eae16800-8111-11eb-9e0a-9926b159d16d.PNG)

This is a serious bug I am experiencing for over 10 months already. It happend on two of my machines with loads of different qgis versions and data formats. I can't reproduce the bug every time but only sometimes. It tends to occur the longer the qgis-session is already going on. Of course I tried different profiles too. And I observed this bug on the machines of 30 - 50% of my qgis students. 

It would be amazing to get another answer than the typical "I can't reproduce the bug". :)

**Comment by gioman** [comment]
> It would be amazing to get another answer than the typical "I can't reproduce the bug". :) 

@EnzoBaldini well... don't get offended if it will come another answer like that. Sometimes is very hard to replicate the problems a user is seeing. Sometimes is just a plain bug, sometimes is not (it could be the data, it could be a 3rd party plugin, it could be the user, etc.). I think we already discussed this in private.

We will see then.

**Comment by EnzoBaldini** [comment]
@gioman. Yes, we discussed it privately. I also posted it on [stackexchange ](https://gis.stackexchange.com/questions/367711/qgis-crs-problems?noredirect=1#comment602102_367711) and here on [github](https://github.com/qgis/QGIS/issues/37809).

**Comment by roya0045** [comment]
What version and os are you on?

**Comment by EnzoBaldini** [comment]
Currently I am using QGIS 3.16.4 on windows-10:

![qgis](https://user-images.githubusercontent.com/50318977/110528217-30089880-8118-11eb-8e26-491389a6f130.PNG)

**Comment by agiudiceandrea** [comment]
I cannot reproduce with QGIS 3.16.4 on Windows 7 and Windows 10 and I've never seen this strange behaviour in any previous version.

The bavaria_25832 and bavaria_4326 shapefiles in data.zip have identical *.shp, *.shx, *.dbf, *.cpg, while bavaria_25832.prj is missing and bavaria_4326.prj contains the 4326 crs definition (but bavaria_4326 is actually in 25832 crs as bavaria_25832).

@EnzoBaldini are there any errors or warnings in the Log Messages Panel? Are you sure the issue does occur in a plain new QGIS user profile without plugins except the core plugins (I see some other plugins in your last screenshot)? Is QGIS installed via OSGeo4W network installer or the standalone installer?

Maybe a screencast could show some clue that is not evident in the screenshots.

**Comment by EnzoBaldini** [comment]
@gioman I am not surprised that you can't reproduce the bug. Even me, I can't reproduce the bug this morning, after I started my PC. But during the day, when I work with QGIS, the bug keeps coming back. I will do as @agiudiceandrea recommended. The next time when the bug occurs, I will take a screencast. After that I will start a new profile and remove 3rd party plugins. Than I will take a second screencast and than we can compare both screencasts. Looking forward :)

**Comment by EnzoBaldini** [comment]
@agiudiceandrea the obve described problem occured also for some of my students that haven't isntalled any plugins yet. I couldn't make a screencast though. Is it possible that the german language package causes these problems? Normally I would guess the language of the GUI does not have anything to do with CRS. But 90% of my students use the german GUI.

**Comment by gioman** [comment]
> That would explain why @gioman and many others can't reproduce the bug.

@EnzoBaldini if I'm not wrong I downloaded and tested Window 10 in DE too.

**Comment by agiudiceandrea** [comment]
@EnzoBaldini, since you think it might be language dependent, you may want to try asking to the German language mailing lists subscribers:
- QGIS-de: qgis-de@lists.osgeo.org | https://lists.osgeo.org/mailman/listinfo/qgis-de | http://osgeo-org.1560.x6.nabble.com/QGIS-de-f5194137.html
- FOSSGIS-Talk: fossgis-talk-liste@fossgis.de ! https://lists.fossgis.de/mailman/listinfo/fossgis-talk-liste ! http://osgeo-org.1560.x6.nabble.com/FOSSGIS-Talk-f4217557.html

if there are other German language users experiencing the same issue.

**Comment by EnzoBaldini** [comment]
@agiudiceandrea Hey Andrea, I tried with German GUI and the problem keeps coming back. Me and my students deal with this bug already almost one year.

**Comment by gioman** [comment]
> @agiudiceandrea Hey Andrea, thank you for your message. I tried with German GUI and the problem keeps coming back. Me and my students deal with this bug already almost one year.

@EnzoBaldini are you able to screencast the whole process, from "new project" to wrong reprojection?

**Comment by EnzoBaldini** [comment]
@gioman  I will try to do that in the coming weeks. Not easy to find the right moment for the "CRS behaviour switch" though... Sometimes it comes after a few moments, sometimes after several hours. Nevertheless I will give it a try

**Comment by gioman** [comment]
@EnzoBaldini where do we stand with this issue?

**Comment by EnzoBaldini** [comment]
@gioman issue still exists. not only for me but also for QGIS users I collaborate with.

**Comment by gioman** [comment]
> @gioman issue still exists. not only for me but also for QGIS users I collaborate with.

@EnzoBaldini have you created the screencast as requested? have you contacted the German community as suggested?
