### ISSUE TITLE
Excel files can not be exported to shapefile format

### ISSUE THREAD

**Issue by tschmetzer** [qgis/QGIS#42149]
When I save/export this example layer [Example_data.xlsx](https://github.com/qgis/QGIS/files/6110608/Example_data.xlsx) as a .shp layer QGIS creates the files .dbf and .cpg but no other files and notifies about an export success and a failure at the same time. The Excel file was created by QGIS when exporting two fields from a different shapefile but that doesn't seem to be the problem (see below). Exporting into the geopackage or spatialite file format works without any probelms.

![grafik](https://user-images.githubusercontent.com/67278094/110518930-0b5af380-810d-11eb-990d-59340c2ee22d.png)

![grafik](https://user-images.githubusercontent.com/67278094/110519393-8cb28600-810d-11eb-802b-5c31442d6bff.png)

![grafik](https://user-images.githubusercontent.com/67278094/110519917-28dc8d00-810e-11eb-8c39-ba3afae77063.png)

tried to export using the encondings utf-8 (default), windows-1252, latin1 but they all produced the same error. I tried different CRSs and geometry types but none worked. I suspected special characters like "ß","ä", "ö" and "ü" to be a problem but even when I replaced all of them by other characters the problem persisted ([Example_data2.xlsx](https://github.com/qgis/QGIS/files/6110782/Example_data2.xlsx)). Even when I create a simple and completely new Excel file without any special characters using MS Excel [example_data5.xlsx](https://github.com/qgis/QGIS/files/6110829/example_data5.xlsx)  I get the same error: 

` Invalid Data Source : C:\temp\example_export5.shp|layername=example_export5 is not a valid or recognized data source.`

QGIS version | 3.18.0-Zürich | QGIS code revision | bdef9fb328
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)

**Comment by nyalldawson** [comment]
This is as expected - a geometry-less shape file is just a dbf file (exact same behaviour happens in arcmap)

**Comment by tschmetzer** [comment]
Ah, I see. Maybe that difference between .shp and .dbf isn't known to all users. Regarding user expectations: 
- The user would not expect a message "CRITICAL Invalid Data Source"
- The user would expect the saved data source to be added to Layers panel

I'd regard this a usability bug. What about shifting this ticket to feature request? Or shall I open a new one? Or would you prefer not to follow up such topics?
