### ISSUE TITLE
Bad layer handler dialog is completely broken

### ISSUE THREAD

**Issue by nyalldawson** [qgis/QGIS#42155]
This dialog is basically completely broken for 3.18. You are only able to fix ogr based layers, trying to fix rasters or mesh results in the layers staying broken after hitting the apply button.

**Comment by roya0045** [comment]
I'll take a look at it.

**Comment by roya0045** [comment]
I did a test with my spatialite PR, using autofind to look up files moved over one folder. Autofind and apply worked fine on 
![image](https://user-images.githubusercontent.com/12854129/110553829-a51fa200-8107-11eb-935c-1f67d622495c.png)
Though the grib2 dataset is interpreted as raster with provider none.

**Comment by nyalldawson** [comment]
It's not the auto-find which is broken, it's the manual repair/browse of paths which is completely ignored

**Comment by roya0045** [comment]
Could we merge my PR and see if this is fixed by it? Browse and manual changes are fine for me.

**Comment by nyalldawson** [comment]
No - I've spent the last 2 hours fixing this mess. We'll merge MY working PR first, and then revisit carefully any further changes you want to make.

**Comment by roya0045** [comment]
Sure thing.
