### ISSUE TITLE
Qfield doesn't open WMS layers

### ISSUE THREAD

**Issue by userdarp06** [qgis/QGIS#42175]
IMPORTANT:

If the issue concerns a third party plugin (downloaded with the plugin manager) then it can't be fixed by the QGIS team.
Please raise your issue in the dedicated bug tracker for that specific plugin (as listed in the plugin's description)

Tickets created here will be closed.

**Comment by gioman** [comment]
@userdarp06 use this

https://github.com/qgis/QGIS/issues/new?assignees=&labels=Bug&template=10_bug_report.md&title=

and fill ALL the requested infos.

**Comment by userdarp06** [comment]
The project in QFIELD with WMS layers was working correctly but now, it doesn't read the layers. Network connection on the tablet is right and I cannot load the WMS completely. Thank you.
![Screenshot_20210310-103448](https://user-images.githubusercontent.com/80389363/110608852-ea39e780-818c-11eb-9af2-50617742212a.png)

**Comment by gioman** [comment]
> The project in QFIELD with WMS layers was working correctly but now, it doesn't read the layers. Network connection on the tablet is right and I cannot load the WMS completely. Thank you.

@userdarp06 report it in the qfield bug tracker, not here.
