### ISSUE TITLE
crash when creating geopdf

### ISSUE THREAD

**Issue by Schwaeble** [qgis/QGIS#42182]
I use windows 10 and tried to create a geopdf. Everything went OK until QGIS was about to create the file when the program crashed. 

Crash ID: 7b066ac7fe0de868f28265dd9fe232e91a233776
QgsMapRendererStagedRenderJob::renderCurrentPart qgsmaprendererstagedrenderjob.cpp:105

QGIS Info
QGIS Version: 3.16.4-Hannover
QGIS code revision: 654e76b3cb
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

**Comment by gioman** [comment]
@Schwaeble try on a new QGIS profile.

**Comment by Schwaeble** [comment]
Thanks gioman. Before reading your comment I just tied again without any change and it worked.

**Comment by Schwaeble** [comment]
I closed the issue too soon. The pdf export only looked like it finished, but when I tried to exit the printing program, qgis crashed, and the pdf was not created. 
Here the report
Crash ID: 99b7261cf6ca387eb84112ab7f09c6b429ddf74c


Stack Trace


QgsMapRendererStagedRenderJob::renderCurrentPart qgsmaprendererstagedrenderjob.cpp:105
QgsLayoutItemMap::paint qgslayoutitemmap.cpp:1051
QGraphicsScene::dragMoveEvent :
QGraphicsItem::dragMoveEvent :
QGraphicsEffectSource::draw :
QgsLayoutEffect::draw qgslayouteffect.cpp:33
QGraphicsScene::drawItems :
QGraphicsScene::drawItems :
QGraphicsScene::render :
QgsLayoutExporter::renderRegion qgslayoutexporter.cpp:261
QgsLayoutExporter::renderPage qgslayoutexporter.cpp:174
QgsLayoutExporter::printPrivate qgslayoutexporter.cpp:1278
::operator() qgslayoutexporter.cpp:582
QgsLayoutExporter::handleLayeredExport qgslayoutexporter.cpp:1775
QgsLayoutExporter::exportToPdf qgslayoutexporter.cpp:586
QgsLayoutDesignerDialog::exportToPdf qgslayoutdesignerdialog.cpp:2272
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1637
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.16.4-Hannover
QGIS code revision: 654e76b3cb
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

**Comment by gioman** [comment]
@Schwaeble Can you share  a sample project+data?

**Comment by Schwaeble** [comment]
Giovanni, what is a QGIS profile? Just a new file? I don’t think I ever created a profile.

Thanks for your help

Jake

**Comment by gioman** [comment]
> Giovanni, what is a QGIS profile? Just a new file? I don’t think I ever created a profile.

@Schwaeble settings > profiles > new profile

**Comment by Schwaeble** [comment]
> @Schwaeble Can you share a sample project+data?

Gioman, tried to include the qgz file but I got a message that github does not support the file type.
How can I get the data and file to you?

**Comment by gioman** [comment]
>  How can I get the data and file to you?

@attach the project and data here, as ZIP file.

**Comment by Schwaeble** [comment]
[crash file.zip](https://github.com/qgis/QGIS/files/6118905/crash.file.zip)
I hope this will work. Here is the original file McKay.qgz and a second attempt to get a different profile McKay2.qgz. These are LIDAR profile images of a forest

**Comment by jgrocha** [comment]
@Schwaeble You should create a zip including all layers to reproduce the problem. I've tried to open the project, but some layers are missing.
![missing layers](https://user-images.githubusercontent.com/163681/110700628-146cc300-81e8-11eb-93e7-b8ecb8216f70.png)

**Comment by Schwaeble** [comment]
The problem was that all the files had too many bytes.
I'll try to recreate the problem with fewer layers

**Comment by jgrocha** [comment]
Thank you @Schwaeble. If you are able to reproduce the problem with fewer layers, you are helping the developers, by narrowing down the problem.

**Comment by Schwaeble** [comment]
I threw all layers out but one of the numbered LIDAR profiles. And it crashes. It does not crash if I create a straight pdf. When you look at the numbered files it seems to be a virtual file without a CS.
I hope that helps

**Comment by Schwaeble** [comment]
@jgrocha @gioman.
I threw all layers out but one of the numbered LIDAR profiles. And it crashes. It does not crash if I create a straight pdf. When you look at the numbered files it seems to be a virtual file without a CS.
I hope that helps

**Comment by jgrocha** [comment]
> @jgrocha @gioman.
> I threw all layers out but one of the numbered LIDAR profiles. And it crashes. It does not crash if I create a straight pdf. When you look at the numbered files it seems to be a virtual file without a CS.
> I hope that helps

Thanks @Schwaeble 

These files are raster files, without any georreference. 
Two questions:
- Why do you add them to the project? Do you add them to the project to be used in the layout?
- How did you added them? Ungeorreferenced files and should be visible around 0,0 coordinates and should appear in the layer panel as in the print screen below. What have you done to have "nothing" about them and just an entry in the layer tree? (I can't do that. There is no properties available for your layers in the layer tree.)

![Captura de ecrã de 2021-03-10 23-22-59](https://user-images.githubusercontent.com/163681/110711509-96181d00-81f7-11eb-8d5a-13b7e8460738.png)

**Comment by jgrocha** [comment]
When you export layers to GeoPDF, you must export valid layers. I think you are trying to export invalid/ghost layers.

What should be visible in the GeoPDF, if the layer itself is not visible in QGIS?

QGIS should crash. Probably QGIS is trying to fetch some information about the layer (metadata, extent, CRS, etc) that does not exist.

There are a lot of references to a plugin called FreehandRasterGeoreferencerLayer. Have you tried QGIS with a new profile, without any plugins installed?

**Comment by jgrocha** [comment]
@Schwaeble Without a project that we can open and reproduce the problem, we can't do much. If you still have this issue, please pack the project properly. You have to send the project file and the data in a zip file. We'll reopen the issue soon as you provide a valid project to replicate the problem.
