### ISSUE TITLE
3DMap Viewer

### ISSUE THREAD

**Issue by EmHain8** [qgis/QGIS#42188]
## User Feedback

I used 3d Map viewer. I upped the tile resolution to 512 and screen resolution to ooooooo16px. The screen goes blank. I am using a DEM and 3 vector files - 1 line and 2 points. I am trying to get a perspective. 

## Report Details

**Crash ID**: [997c4daeb785b66347118aa2a126639dabccc957](https://github.com/qgis/QGIS/search?q=997c4daeb785b66347118aa2a126639dabccc957&type=Issues)

**Stack Trace**
<pre>
Qt3DRender::Render::FrameCleanupJob::updateBoundingVolumesDebug :
Qt3DRender::Render::CalculateBoundingVolumeJob::CalculateBoundingVolumeJob :
Qt3DRender::Render::CalculateBoundingVolumeJob::CalculateBoundingVolumeJob :
Qt3DRender::Render::CalculateBoundingVolumeJob::CalculateBoundingVolumeJob :
Qt3DRender::Render::CalculateBoundingVolumeJob::run :
Qt3DRender::Render::CalculateBoundingVolumeJob::run :
Qt3DRender::Render::CalculateBoundingVolumeJob::CalculateBoundingVolumeJob :
QtConcurrent::ThreadEngineBase::startBlocking :
Qt3DRender::Render::FrameCleanupJob::updateBoundingVolumesDebug :
Qt3DRender::Render::CalculateBoundingVolumeJob::CalculateBoundingVolumeJob :
Qt3DRender::Render::CalculateBoundingVolumeJob::run :
Qt3DRender::Render::CalculateBoundingVolumeJob::run :
Qt3DRender::Render::CalculateBoundingVolumeJob::CalculateBoundingVolumeJob :
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.16.3-Hannover
QGIS code revision: 94ac9f21b8
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Describe the bug**

**How to Reproduce**

1. Go to 3D Map Viewer
2. Click on settings/terrain
3. To set the scene up (to prevent crashing) change the settings to: type = DEM; tile resolution = 32px
4. Click on Advanced
5. change  settings: map tile resolution = 256px; max screen error = 5.0px
6. zoom to view
7. go back to settings
8. Terrain/tile resolution = 16px
9. Advanced/map tile resolution = 512px;
10. The screen goes blank and the QGIS crashes

**Comment by EmHain8** [comment]
## User Feedback

I change the layer properties for the 3D View for one of the vectors as well as the resolotuin to 512px

## Report Details

**Crash ID**: [c80eec05d203637e787b695e028447268cb2710f](https://github.com/qgis/QGIS/search?q=c80eec05d203637e787b695e028447268cb2710f&type=Issues)


**Stack Trace**
<pre>
Qt3DRender::Render::FrameCleanupJob::updateBoundingVolumesDebug :
Qt3DRender::Render::CalculateBoundingVolumeJob::CalculateBoundingVolumeJob :
Qt3DRender::Render::CalculateBoundingVolumeJob::CalculateBoundingVolumeJob :
Qt3DRender::Render::CalculateBoundingVolumeJob::CalculateBoundingVolumeJob :
Qt3DRender::Render::CalculateBoundingVolumeJob::run :
Qt3DRender::Render::CalculateBoundingVolumeJob::run :
Qt3DRender::Render::CalculateBoundingVolumeJob::CalculateBoundingVolumeJob :
QtConcurrent::ThreadEngineBase::startBlocking :
Qt3DRender::Render::FrameCleanupJob::updateBoundingVolumesDebug :
Qt3DRender::Render::CalculateBoundingVolumeJob::CalculateBoundingVolumeJob :
Qt3DRender::Render::CalculateBoundingVolumeJob::run :
Qt3DRender::Render::CalculateBoundingVolumeJob::run :
Qt3DRender::Render::CalculateBoundingVolumeJob::CalculateBoundingVolumeJob :
QtConcurrent::ThreadEngineBase::startBlocking :
Qt3DRender::Render::FrameCleanupJob::updateBoundingVolumesDebug :
Qt3DRender::Render::CalculateBoundingVolumeJob::CalculateBoundingVolumeJob :
Qt3DRender::Render::CalculateBoundingVolumeJob::run :
Qt3DRender::Render::CalculateBoundingVolumeJob::run :
Qt3DRender::Render::CalculateBoundingVolumeJob::CalculateBoundingVolumeJob :
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>


**QGIS Info**
QGIS Version: 3.16.3-Hannover
QGIS code revision: 94ac9f21b8
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by Pedro-Murteira** [comment]
@EmHain8 Hello, i've tried to reproduce this issue on QGIS 3.22.3. but I couldn't. Did you come across this issue more recently?
