### ISSUE TITLE
Models don't run from the browser interface

### ISSUE THREAD

**Issue by lcalisto** [qgis/QGIS#42181]
**Describe the bug**

When, from the browser we do a `double click` or `right click`->`run Model`  on a model, the model interface apear but after clicking the` run button` on the interface they dont run, nothing happens.

If we load the model from the `Processing Toolbox` or from the browser `right click`->`edit Model`->`run `  it does work as expected. 

**How to Reproduce**

See above.

Here is an example of one line and a model with the issue.

[simple_line.zip](https://github.com/qgis/QGIS/files/6115829/simple_line.zip)

**QGIS and OS versions**
The model was initially created in QGIS 3.16.3 on Macos and it was working as expected, this issue only happen on version >= QGIS 3.16.4 

The issue happens on:
QGIS 3.16.4 - MacOS, Linux (Ubuntu 20.04), windows 10
QGIS 3.18.0 - MacOS, I did not tested on this version on Linux or Windows.

**Additional context**

**Comment by andremano** [comment]
Same behaviour here:
QGIS 3.16.3 - Windows 10

**Comment by alexbruy** [comment]
Seems duplicates #39749.
