### ISSUE TITLE
Crash editing Dynamic SVG parameters

### ISSUE THREAD

**Issue by jgrocha** [qgis/QGIS#42183]
**Describe the bug**

Dynamic SVG parameters are cool! It's a very nice feature.

![svg parameters](https://user-images.githubusercontent.com/163681/110655412-f175eb00-81b6-11eb-86e1-4fdc0062f21d.png)

When trying to edit Dynamic SVG parameters, under SVG symbology, QGIS crashes.

**How to Reproduce**

1. Create a project with a point layer with two attributes
2. Set symbology to SVG
3. Use a custom SVG file, like the one present in the tests `test_dynamic_svg.svg`
4. Set the two parameters, and make sure the symbology is ok.
5. Then try to click on the triangle handler/collapse on the Dynamic SVG parameters.
6. QGIS crashes

![simbology](https://user-images.githubusercontent.com/163681/110655012-93490800-81b6-11eb-8ac3-f28986c026dd.png)

![handlers](https://user-images.githubusercontent.com/163681/110655243-cab7b480-81b6-11eb-9b6e-c9cdaa76dc9c.png)

I don't know why the entries in the table have this collapsible option.

**QGIS and OS versions**

Current master 3.19.0-Master, QGIS code revision e763ee59f69, self compiled, Ubuntu 20.04.2, 5.12.8

**Additional context**

```
src/gui/qgscollapsiblegroupbox.cpp:106 : (showEvent) [16ms] did not find a QScrollArea parent
src/gui/qgscollapsiblegroupbox.cpp:370 : (updateStyle) [0ms] groupbox: groupBox style: QgsAppStyle offset: left=0 top=1 top2=2
src/gui/qgscollapsiblegroupbox.cpp:106 : (showEvent) [2ms] did not find a QScrollArea parent
src/gui/qgscollapsiblegroupbox.cpp:370 : (updateStyle) [0ms] groupbox: mParametersGroupBox style: QgsAppStyle offset: left=0 top=1 top2=2
Falha de segmentação (núcleo despejado)
```

**Comment by jgrocha** [comment]
@3nids I don't know exactly the purpose behind the `QTreeView`. Would you like to allow nested parameters? 

To prevent this crash, as far as I can see, we can just prevent the expand of the items. Something like:

```diff
diff --git a/src/ui/symbollayer/widget_svgselector.ui b/src/ui/symbollayer/widget_svgselector.ui
index 9c060e0f753..653a6e74b6d 100644
--- a/src/ui/symbollayer/widget_svgselector.ui
+++ b/src/ui/symbollayer/widget_svgselector.ui
@@ -174,7 +174,11 @@
        </widget>
       </item>
       <item row="0" column="0" colspan="5">
-       <widget class="QTreeView" name="mParametersTreeView"/>
+       <widget class="QTreeView" name="mParametersTreeView">
+        <property name="itemsExpandable">
+         <bool>false</bool>
+        </property>
+       </widget>
       </item>
      </layout>
     </widget>
```
What do you think?

**Comment by klakar** [comment]
Tested on 3.18.1 and this still results in a crash.
