### ISSUE TITLE
When running raster > extraction > contour, the process took so long and Windows Antimalware Service usage constantly ramped up

### ISSUE THREAD

**Issue by WhitespaceQ** [qgis/QGIS#42190]
**Describe the bug**

**How to Reproduce**

1. Go to Raster > Conversion > Contour
2. Load a DEM layer and perform the task
3. CPU usage of Windows' Antimalware Service Executable will be ramped up while gdal_contour.exe stays around 5%
4. See screenshot [here](https://i.imgur.com/lMjvmWW.png)

**QGIS and OS versions**

```
QGIS version
3.16.4-Hannover
QGIS code revision
654e76b3cb
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
CalcArea; 
FreehandRasterGeoreferencer; 
latlontools; 
qgsAzimuth; 
quick_map_services; 
shapetools; 
SRTM-Downloader; 
volume_calculation_tool; 
db_manager; 
MetaSearch; 
processing
```

**Additional context**

```
Edition	Windows 10 Pro
Version	20H2
Installed on	[REDACTED]
OS build	19042.804
Experience	Windows Feature Experience Pack 120.2212.551.0
```

**Comment by gioman** [comment]
@WhitespaceQ do not seems a general issue.

**Comment by roya0045** [comment]
I'm not sure what's the point to this report. qgis doesn't control windows antimalware and gdal_contour works as expected.

**Comment by gioman** [comment]
> I'm not sure what's the point to this report. qgis doesn't control windows antimalware and gdal_contour works as expected.

agree.

**Comment by WhitespaceQ** [comment]
@gioman @roya0045 actually I can live with this, just have to spare additional minutes waiting for tasks. So, this seems like a sporadic issue that roots on Windows Antimalware rather than gdal_contour? This problem plagued me since 3.14 and I'm having difficulties replicating this issue on another machine. With another machine spec-to-spec, on mine gdal_contour run much, much slower.

I also agree that qgis shouldn't have any issue with Windows Antimalware but what I'm experiencing, however counter-intuitive, was real. Any idea on how should I proceed to pinpoint the issue?

**Comment by gioman** [comment]
> Any idea on how should I proceed to pinpoint the issue?

not sure how Windows Antimalware, you could try withelist all the executables that are in the qgis installation folder.

**Comment by gioman** [comment]
Closing for lack of feedback.
