### ISSUE TITLE
Choose attributes of largest feature (polygon) as default attibutes when merging polygons

### ISSUE THREAD

**Issue by koenigherford** [qgis/QGIS#42194]
It would be great to have attributes of largest feature (polygon) as default attibutes when merging polygons, because merging of polygons is often used when revising geometries. Mostly the smaller features shall get the attributes of the larger target-feature.

For example you want to refine a old stream-polygon and digitize the finer boundaries of the stream with the "Split features"-tool: 

![grafik](https://user-images.githubusercontent.com/28433436/110765618-a90d0a80-8254-11eb-90b2-e027887fe2df.png)

When you try to merge the polgons the default-resulting-attribute-values of the merged polygon seem to be the attribute values one of the merged features - but randomly.

"Grass" is target-feature but "stream"-feature is default-value.:
![grafik](https://user-images.githubusercontent.com/28433436/110768250-58e37780-8257-11eb-838d-71fc8938a53a.png)

There will be less work for the user to 
1) select the target feature and
2) click on "take attributes from selected feature"

if the target feature attributes are taken from QGIS by largest feature-area automaticially (or by first selected-feature).

**Comment by koenigherford** [comment]
Thanks for #42205 !!!!

**Comment by DelazJ** [comment]
So can we close this request, @koenigherford ?
With a dedicated button, I'm not sure there's a need to make this option the default

**Comment by koenigherford** [comment]
I think the feature-request can be closed. 
#42205 says, that the feature request can not be realized because of some internal logic. It's appoach reduces the number of clicks during merging attributes after all.
