### ISSUE TITLE
problem making new profile and layouts

### ISSUE THREAD

**Issue by sverbeeren** [qgis/QGIS#42199]
Following actions are not possible:
-making a new profile: when going to Extra/user profiles/new profile only the title of the text box/window appears and nothing more so I cannot continue
- creating new layout or duplicate starting from the layout manager or from an existing layout doesn't work either. The same thing happens, only the title of the text box/window appears and noting more happens.
 
I am working with version 3.16, but had the same problem with version 3.10 at the end.

**Comment by DelazJ** [comment]
> -making a new profile: when going to Extra/user profiles/new profile only the title of the text box/window appears and nothing more so I cannot continue

#. Go to the folder mentioned in https://docs.qgis.org/3.16/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles depending on your OS and delete/move the folder in it. You can also access it through QGIS (Preferences --> User Profiles --> Open the active profile folder)
#. Restart QGIS; it should recreate a new profile from scratch.

Let us know if any of the issues is still there.

**Comment by sverbeeren** [comment]
Making a new profile solved the problem. Thank you very much!
