### ISSUE TITLE
QGIS Icon for MacOS

### ISSUE THREAD

**Issue by rikarudo** [qgis/QGIS#42202]
Hi!

I've created a new QIGS icon for MacOS, Big Sur style.

If you want to try it, you are welcome.

Best regards.

Rikarudo

[QGIS.icns.zip](https://github.com/qgis/QGIS/files/6125407/QGIS.icns.zip)

**Comment by gioman** [comment]
@rikarudo post them on the users/developers mailing list and/or submit them as part of a new theme with a pull request.
