### ISSUE TITLE
23.1.17.8. Select by attribute in docs - swapped methods

### ISSUE THREAD

**Issue by Kozzba** [qgis/QGIS#42219]
Just a small bug in the documentation.

in docs:
![image](https://user-images.githubusercontent.com/62255134/110951052-e51f9880-8344-11eb-8a3f-61013e83123c.png)

in QGIS:
![image](https://user-images.githubusercontent.com/62255134/110950968-c8836080-8344-11eb-8179-384e62b41746.png)

url to docs:
https://docs.qgis.org/3.16/en/docs/user_manual/processing_algs/qgis/vectorselection.html#id19

**Comment by roya0045** [comment]
I guess this would be more appropriate in the documentation report, @DelazJ do you agree or is it better here?

**Comment by DelazJ** [comment]
Generally speaking, anything related with https://docs.qgis.org should indeed be reported in the [docs repo](https://github.com/qgis/QGIS-Documentation). But merging the PR there will close the report here. so we can leave it here from the time being.

About the issue, happens that the order of these options is not consistent among the algs. The docs is coherent with the "select by location" alg, and we probably copied and pasted to the others.
