### ISSUE TITLE
Allow Two Separate QGIS Plugins Under one Provider

### ISSUE THREAD

**Issue by ar-siddiqui** [qgis/QGIS#42211]
I have developed a QGIS processing plugin that has a processing provider of its own. That plugin is working fine. Now I am developing a second plugin and I want to provide it the same provider so that I can have something like this where many algorithms are under Vector Selection Provider:

![image](https://user-images.githubusercontent.com/53625184/110874170-4aba4900-82a1-11eb-854f-56b255e2849d.png)

These two plugins are different and hence I don't want to package them under the same plugin but do want them to have the same provider.

QGIS would rock even more if it allows appending algorithms to the existing provider.

**Comment by nyalldawson** [comment]
I don't think this needs addressing in qgis API. You could make a private API in your plugins to allow to other plugin to add algorithms to the plugins provider and this will work fine.
