### ISSUE TITLE
several tools are blocked in my qgis and i can't return with them.

### ISSUE THREAD

**Issue by AngelaIsaura** [qgis/QGIS#42220]
**Describe the bug**

**How to Reproduce**

4. See error -->

**QGIS and OS versions**

**Additional context**

**Comment by roya0045** [comment]
ok.

**Comment by gioman** [comment]
@AngelaIsaura please add all the requested infos

####
Describe the bug

How to Reproduce

    Go to '...'
    Click on '....'
    Scroll down to '....'
    See error -->

QGIS and OS versions

Additional context

####
