### ISSUE TITLE
QGIS Desktop 3.10 It crashes when start using georeferencer

### ISSUE THREAD

**Issue by dannykingston** [qgis/QGIS#42222]
QGIS Desktop 3.10 crashes at the time of grabbing the first - and last - point in the georeferencer.

(large TIFF file, not actually bigger than the hundreds I used to georeference daily. 

Never happened before, now it's a few days that the error is reccurent and makes the plugin useless.

Thank you,
Daniele

Crash ID: 9dcd5d36514f53142268af5aeed757ecbc230471

Stack Trace

QList::size :
QgsVectorLayer::featureCount :
QgsSnappingUtils::prepareIndex :
QgsSnappingUtils::snapToMap :
version :
QgsMapCanvas::mouseMoveEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.10.2-A Coru�a
QGIS code revision: d4cd3cfe5a
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.3
Running against GDAL: 3.0.3

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

**Comment by roya0045** [comment]
3.10 is not supported anymore anyway. Try on 3.16 to see if it still occurs.

**Comment by gioman** [comment]
@dannykingston also try on a new QGIS profile, if the problem persist on 3.16 please attach the file you are trying to georeference and the ground control points.

**Comment by dannykingston** [comment]
Hi,
just tried with the 3.16.4 but it crashes systematically on this machine.

Here is the report, I won't attach the file for two reasons: 1) is too big 2) the crash occurs with any file.

Thank you,
Daniele




Crash ID: 733f356e094c9989d308fa24c1d99bf66bf34ac0


Stack Trace


QList::size :
QgsVectorLayer::featureCount qgsvectorlayer.cpp:3359
QgsSnappingUtils::prepareIndex qgssnappingutils.cpp:486
QgsSnappingUtils::snapToMap qgssnappingutils.cpp:385
QgsGeorefMapToolEmitPoint::canvasMoveEvent qgsmapcoordsdialog.cpp:175
QgsMapCanvas::mouseMoveEvent qgsmapcanvas.cpp:1994
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1637
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.16.4-Hannover
QGIS code revision: 654e76b3cb
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

**Comment by gioman** [comment]
> on this machine.

@dannykingston so it does not happen on another machine of yours?

> 2) the crash occurs with any file.

then you really have likely a local issue.

**Comment by dannykingston** [comment]
yes, it only happens on my PC at office.
On the other I've got at home there's no problem.

#then you really have likely a local issue.

it looks so, and should be very helpful to know what issue and why it affects just the georeferencer plugin.

**Comment by roya0045** [comment]
Judging from the stack trace I'd think that any action requiring snapping would cause a crash as it seems to be related to one of your layers and not the georeferencer.

**Comment by dannykingston** [comment]
Thank you, I've had to clean up randomly many layers that were opened in the project and it works now.
Didn't believe as possible, before, that "any action requiring snapping would cause a crash" by using the georeferencer, due to the fact that rasters and layers processes looked totally unrelated to me. In addiction, it was possible in the same project to operate with layers and snaps whitout causing any crash.

**Comment by gioman** [comment]
> Didn't believe as possible, before, that "any action requiring snapping would cause a crash" by using the georeferencer, due to the fact that rasters and layers processes looked totally unrelated to me.

@dannykingston well of course they  should not be related. Can you pin point what is the layer causing the issue? and say what are its properties?

**Comment by dannykingston** [comment]
> @dannykingston well of course they should not be related. Can you pin point what is the layer causing the issue? and say what are its properties?

Not able to do the search right now, but I promise to check sooner and submit the results to help finding an explanation.

**Comment by roya0045** [comment]
> QList::size :
> QgsVectorLayer::featureCount qgsvectorlayer.cpp:3359
> QgsSnappingUtils::prepareIndex qgssnappingutils.cpp:486
> QgsSnappingUtils::snapToMap qgssnappingutils.cpp:385
> QgsGeorefMapToolEmitPoint::canvasMoveEvent qgsmapcoordsdialog.cpp:175

The georeference point uses snapping, this is clearly shown in the stacktrace.

**Comment by gioman** [comment]
Closing for lack of feedback.
