### ISSUE TITLE
Crash when changing lightning parameters in 3D Map View

### ISSUE THREAD

**Issue by phipsch63** [qgis/QGIS#42226]
**How to Reproduce**

1. Open 3D Map Window (same data and 3D configs as attached with issue #41904)
2. Tilt down 
3. Open the map view settings
4. Change Lights Intensity from 1.0 to 0.5 (s. Screenshot)
5. Press Apply
6. See error --> (Report details attached)
![3D-Config11](https://user-images.githubusercontent.com/79761510/111065276-2769e680-84b9-11eb-8ad4-d854a3c4e667.JPG)
[Bug_3D-Light.txt](https://github.com/qgis/QGIS/files/6136475/Bug_3D-Light.txt)

**Comment by gioman** [comment]
Confirmed on 3.18.0.

**Comment by Pedro-Murteira** [comment]
@phipsch63 I've tried to REPLICATE  this but I can no longer reproduce a crash (QGIS 3.22.3.). Did you come across this issue in more recent versions of QGIS?
