### ISSUE TITLE
Error in opening a table without geometries coming from a geopackage database

### ISSUE THREAD

**Issue by rrabilotta** [qgis/QGIS#42236]
**Describe the bug**
QGIS (3.16)  is having an unrecoverable critical error when opening a table without geometries from a geopackage format database.

**How to Reproduce**
Opening a geopackage with  non spatial data (no geometries).
1. Connect to a geopackage file (database).
2. Add a table (with no geometry field) to the project.
3. QGIS crashes a couple of minutes after.

Error message:
=========
Crash ID: a0e2010804d85870af6455fce27865b849c05d1e

Stack Trace

QBitArray::QBitArray :
QgsProjectPropertyKey::name qgsproperty.h:164
QgsRuleBasedRenderer::convertFromRenderer qgsrulebasedrenderer.cpp:1304
meth_QgsRuleBasedRenderer_convertFromRenderer sip_corepart2.cpp:66136
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QMetaObject::activate :
QgisInterface::currentLayerChanged moc_qgisinterface.cpp:810
QMetaObject::activate :
QgisApp::activeLayerChanged moc_qgisapp.cpp:2766
QgisApp::onActiveLayerChanged qgisapp.cpp:698
QgisApp::handleDropUriList qgisapp.cpp:2150
QgsLayerItemGuiProvider::handleDoubleClick qgsinbuiltdataitemproviders.cpp:569
QgsBrowserDockWidget::itemDoubleClicked qgsbrowserdockwidget.cpp:179
QMetaObject::activate :
QAbstractItemView::doubleClicked :
QTreeView::mouseDoubleClickEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1637
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.16.3-Hannover
QGIS code revision: 94ac9f21b8
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

**QGIS and OS versions**
QGIS 3.16

**Additional context**
Windows 10 Pro version 20H2.

**Comment by gioman** [comment]
> Add a table (with no geometry field) to the project.

@rrabilotta can't replicate here, can you attach a sample of your data? Have you tried on a new QGIS profile?

**Comment by rrabilotta** [comment]
Hi,

This is the link to download the file: https://1drv.ms/u/s!ApSlkeft5Lv-mY56kbgWEfQtXG_5Lg?e=JurfdD

Thanks.

Rocco Rabilotta Pisters

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: Giovanni ***@***.***>
Enviado: lunes, 15 de marzo de 2021 02:23
Para: ***@***.***>
CC: ***@***.***>; ***@***.***>
Asunto: Re: [qgis/QGIS] Error in opening a table without geometries coming from a geopackage database (#42236)


Add a table (with no geometry field) to the project.

@rrabilotta<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frrabilotta&data=04%7C01%7C%7Ca9604270212e4cb97c3f08d8e78bab81%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637513934346022519%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kJ3TSx9QL58zrsLutjUM5GlYJrkk5h94%2BY%2BSRXyR9i8%3D&reserved=0> can't replicate here, can you attach a sample of your data? Have you tried on a new QGIS profile?

**Comment by gioman** [comment]
> This is the link to download the file: https://1drv.ms/u/s!ApSlkeft5Lv-mY56kbgWEfQtXG_5Lg?e=JurfdD

@rrabilotta cannot replicate. Have you tried on a new QGIS profile?

**Comment by gioman** [comment]
Closing for lack of feedback.
