### ISSUE TITLE
QGIS 3.xx and virtual drives - BUG ON ALL 3.xx versions

### ISSUE THREAD

**Issue by patrickingwer** [qgis/QGIS#42243]
It affects all versions in version 3.xx 
In version 2.18 there are no problems here.

Problem description:
- it does not matter which Windows version is used
- virtual drives are mounted

If the virtual drives are "off", e.g. because of missing VPN connection to the company, QGIS needs very long time to start. In the same way, during work there are often longer "pauses" during which work is impossible.

If there is a VPN connection and the virtual drives are "on" there are no restrictions in working with QGIS 3.xx. The same applies if the virtual drives have been removed - which is not practical.

It looks to me as if the system (QGIS 3.xx) scans all unusable (because of missing VPN) drives during the work - in regular time intervals - and meanwhile, because "no drives" are to be found, stops the work here and blocks.

Does anyone have an idea?
Could someone pass this circumstance on to the developers?

Tested on several computers independently of each other. Especially gravierund under Windows 2004 and up. 

![VPN_off](https://user-images.githubusercontent.com/80682170/111141137-767c4e00-8583-11eb-9e67-69e02ae44929.JPG)
![VPN_on](https://user-images.githubusercontent.com/80682170/111141138-7714e480-8583-11eb-8e73-444c94234c63.JPG)

**Comment by gioman** [comment]
@patrickingwer same as https://github.com/qgis/QGIS/issues/37324 ?

**Comment by patrickingwer** [comment]
Hi Gioman,

yes, absolutely. Its the very same issue. I tried a lot of 3.xx versions. Ever the same result. All on Win10.

Thank you god, I´m not alone with this problem.

Do you have any idea for an solution Gioman?

**Comment by gioman** [comment]
> Do you have any idea for an solution Gioman?

@patrickingwer no, it is a confirmed bug. So you can wait for a fix, or look for commercial support (see QGIS site) and hire a developer that will fix this sooner than later.

Closing as duplicate.
