### ISSUE TITLE
QGIS crashes filtering table by "only selected"

### ISSUE THREAD

**Issue by spono** [qgis/QGIS#42246]
**Describe the bug**
QGIS crashes while filtering a table with not-saved editings (i.e. column addition).

Tested with new profile but only on different shapefiles (so, I can't say it may be related to #27899)

**How to Reproduce**
While editing a shapefile:
1. add a new column
2. click on "Show selected features" -> CRASH

If after point 1 the layer is saved, then the issue doesn't appear at step 2.

**QGIS and OS versions**
W10, QGIS 3.16.4 from Osgeo4W

**Comment by roya0045** [comment]
Cannot confirm on 3.12 with a scratch layer, but works with a geopackage.

**Comment by TurboGraphxBeige** [comment]
I can reproduce the issue on Ubuntu 20.04 and QGIS 3.16.4.

**Comment by gioman** [comment]
@spono no crash on a geopackage on 3.18 on Ubuntu 20.04.

**Comment by gioman** [comment]
@spono also cannot replicate on 3.16.4 on Windows.

**Comment by spono** [comment]
sorry @gioman, I forgot to reply.
in the last week I reinstalled everything few times and discovered that it happens also with blank projectthe last time I tried it crashed even without creating a crash report :/

Try this:
1. create a blank project (predefined CRS)
2. create a new shapefile (physical, no temporary; points; CRS 32632) and add some features (without saving)
3. add new column (no particular format)
4. (check that are all unselected) click on "Show selected features"

Last time I've been lucky and it created a crash report. Here it is:

Crash ID: 30816327029663f259585b439e70110977e416ea


Stack Trace


memcpy_repmovs memcpy.asm:114
QSortFilterProxyModel::qt_metacast :
QSortFilterProxyModel::removeRows :
QSortFilterProxyModel::flags :
QSortFilterProxyModel::filterRole :
QSortFilterProxyModel::invalidateFilter :
QgsAttributeTableFilterModel::setFilterMode qgsattributetablefiltermodel.cpp:338
QgsDualView::setFilterMode qgsdualview.cpp:373
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QMenu::exec :
QToolButton::paintEvent :
QToolButton::showMenu :
QToolButton::~QToolButton :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::mousePressEvent :
QToolButton::mousePressEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1637
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.16.4-Hannover
QGIS code revision: 654e76b3cb
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

**Comment by TurboGraphxBeige** [comment]
Just for the record, I can reproduce this issue even with a Temporary Scratch Layer

**Comment by gioman** [comment]
> Just for the record, I can reproduce this issue even with a Temporary Scratch Layer on Linux but not on Windows.

@TurboGraphxBeige @spono are you you have tested using a new QGIS profile?

**Comment by TurboGraphxBeige** [comment]
> > Just for the record, I can reproduce this issue even with a Temporary Scratch Layer on Linux but not on Windows.
> 
> @TurboGraphxBeige @spono are you you have tested using a new QGIS profile?

Yes.

**Comment by spono** [comment]
> 
> 
> > Just for the record, I can reproduce this issue even with a Temporary Scratch Layer on Linux but not on Windows.
> 
> @TurboGraphxBeige @spono are you you have tested using a new QGIS profile?

yes

**Comment by spono** [comment]
I guess it means nothing in this particular case but, installing 3.16.5 qgis-ltr , I noticed that Osgeo made me install qgis package (version 3.16.3) only to allow the installation of the GRASS plugin.
It's the first time ever that I see that and I don't know if it might be somehow related to a conflict between versions..?

**Comment by TurboGraphxBeige** [comment]
It's happening when calling invalidateFilter() on `line 317` in `.../src/gui/attributetable/qgsattributetablefiltermodel.cpp`
```
void QgsAttributeTableFilterModel::setFilteredFeatures( const QgsFeatureIds &ids )
{
  mFilteredFeatures = ids;
  setFilterMode( ShowFilteredList );
  invalidateFilter();
}
```

**Comment by TurboGraphxBeige** [comment]
It's happening when calling `invalidateFilter()` on `line 342` in .`..src/gui/attributetable/qgsattributetablefiltermodel.cpp`

```
void QgsAttributeTableFilterModel::setFilterMode( FilterMode filterMode )
{
  qDebug() << "setfiltermode";
  if ( filterMode != mFilterMode )
  {
    disconnectFilterModeConnections();
    connectFilterModeConnections( filterMode );
    mFilterMode = filterMode;
    //invalidateFilter();
  }
}
```

**Comment by TurboGraphxBeige** [comment]
Using invalidate() instead of invalidateFilter() seems to avoid the crash using Master on Linux. https://github.com/qgis/QGIS/commit/5626ff0e845454629ca968f5ca9eafe726344f39

**Comment by gioman** [comment]
> Using invalidate() instead of invalidateFilter() seems to avoid the crash using Master on Linux. [5626ff0](https://github.com/qgis/QGIS/commit/5626ff0e845454629ca968f5ca9eafe726344f39)

@TurboGraphxBeige can you propose a patch with a pull request? thanks!

**Comment by TurboGraphxBeige** [comment]
> > Using invalidate() instead of invalidateFilter() seems to avoid the crash using Master on Linux. [5626ff0](https://github.com/qgis/QGIS/commit/5626ff0e845454629ca968f5ca9eafe726344f39)
> 
> @TurboGraphxBeige can you propose a patch with a pull request? thanks!

Sure. I'm just really not sure if it's a good fix. I don't understand why it crashes with invalidateFilter() and I don't understand why using invalidate() fixes it :P

Reviewers will know better than me.

**Comment by TurboGraphxBeige** [comment]
Not stale

**Comment by TurboGraphxBeige** [comment]
Not stale
