### ISSUE TITLE
gdaldem roughness (italian version)

### ISSUE THREAD

**Issue by framassa** [qgis/QGIS#42249]
Using the Italian version of raster tool I can obtain the correct result using default configuration of the Asperità tool (gdaldem roughness). If I modify the field about the file compression (selectioning high compression) I obtain the error below. I guess it's something about the italian name of the tool.

Francesco Massa

----
Versione di QGIS: 3.16.3-Hannover
Revisione codice QGIS: 94ac9f21b8
Versione di Qt: 5.11.2
Versione di GDAL: 3.1.4
Versione di GEOS: 3.8.1-CAPI-1.13.3
Versione di PROJ: Rel. 6.3.2, May 1st, 2020
Algoritmo in esecuzione...
In avvio l'algoritmo 'Asperità' …
Input parameters:
{ 'BAND' : 1, 'COMPUTE_EDGES' : False, 'INPUT' : 'C:/Users/SUNMI/AppData/Local/Temp/processing_WlYOKy/a385193d0ad24556924cfd2df3800a9c/OUTPUT.tif', 'OPTIONS' : '', 'OUTPUT' : 'TEMPORARY_OUTPUT' }

GDAL command:
gdaldem roughness C:/Users/SUNMI/AppData/Local/Temp/processing_WlYOKy/a385193d0ad24556924cfd2df3800a9c/OUTPUT.tif C:/Users/SUNMI/AppData/Local/Temp/processing_WlYOKy/1c5d71b1f85b43ca8bd6b9e720b3dd51/OUTPUT.tif -of GTiff -b 1
GDAL command output:
0...10...20...30...40...50...60...70...80...90...100 - done.

Execution completed in 6.33 seconds
Results:
{'OUTPUT': 'C:/Users/SUNMI/AppData/Local/Temp/processing_WlYOKy/1c5d71b1f85b43ca8bd6b9e720b3dd51/OUTPUT.tif'}

Caricamento layer
Algorithm 'Asperità' finished
Versione di QGIS: 3.16.3-Hannover
Revisione codice QGIS: 94ac9f21b8
Versione di Qt: 5.11.2
Versione di GDAL: 3.1.4
Versione di GEOS: 3.8.1-CAPI-1.13.3
Versione di PROJ: Rel. 6.3.2, May 1st, 2020
Algoritmo in esecuzione...
In avvio l'algoritmo 'Asperità' …
Input parameters:
{ 'BAND' : 1, 'COMPUTE_EDGES' : False, 'INPUT' : 'C:/Users/SUNMI/AppData/Local/Temp/processing_WlYOKy/a385193d0ad24556924cfd2df3800a9c/OUTPUT.tif', 'OPTIONS' : 'COMPRESS=DEFLATE|PREDICTOR=2|ZLEVEL=9', 'OUTPUT' : 'TEMPORARY_OUTPUT' }

GDAL command:
gdaldem roughness C:/Users/SUNMI/AppData/Local/Temp/processing_WlYOKy/a385193d0ad24556924cfd2df3800a9c/OUTPUT.tif C:/Users/SUNMI/AppData/Local/Temp/processing_WlYOKy/7160e6bb49424b4b9987b537a3adf8c1/OUTPUT.tif -of GTiff -b 1 -co COMPRESS=DEFLATE|PREDICTOR=2|ZLEVEL=9
GDAL command output:
Traceback (most recent call last):
File "C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python/plugins\processing\algs\gdal\GdalAlgorithm.py", line 138, in processAlgorithm
GdalUtils.runGdal(commands, feedback)
File "C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python/plugins\processing\algs\gdal\GdalUtils.py", line 108, in runGdal
for line in proc.stdout:
File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\codecs.py", line 322, in decode
(result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8a in position 16: invalid start byte

Execution failed after 0.13 seconds

Caricamento layer
Algorithm 'Asperità' finished

**Comment by agiudiceandrea** [comment]
@framassa I don't think this is due to the Italian translation of the algorithm name.

The issue occurs also with the English language using QGIS 3.16.4:

```
QGIS version: 3.16.4-Hannover
QGIS code revision: 654e76b3cb
Qt version: 5.11.2
GDAL version: 3.1.4
GEOS version: 3.8.1-CAPI-1.13.3
PROJ version: Rel. 6.3.2, May 1st, 2020
Processing algorithm…
Algorithm 'Roughness' starting…
Input parameters:
{ 'BAND' : 1, 'COMPUTE_EDGES' : False, 'INPUT' : 'C:/TEST/dtm_aspromonte.tif', 'OPTIONS' : 'COMPRESS=JPEG|JPEG_QUALITY=75', 'OUTPUT' : 'TEMPORARY_OUTPUT' }

GDAL command:
gdaldem roughness C:/TEST/dtm_aspromonte.tif C:/Users/Andrea/AppData/Local/Temp/processing_gBAPIb/6fc58093ab5a4427ab30d739d6797bed/OUTPUT.tif -of GTiff -b 1 -co COMPRESS=JPEG|JPEG_QUALITY=75
GDAL command output:
Traceback (most recent call last):
File "F:/QGIS/OSGEO4~1.4/qgis/apps/qgis-ltr/./python/plugins\processing\algs\gdal\GdalAlgorithm.py", line 138, in processAlgorithm
GdalUtils.runGdal(commands, feedback)
File "F:/QGIS/OSGEO4~1.4/qgis/apps/qgis-ltr/./python/plugins\processing\algs\gdal\GdalUtils.py", line 108, in runGdal
for line in proc.stdout:
File "F:\QGIS\OSGEO4~1.4\qgis\apps\Python37\lib\codecs.py", line 322, in decode
(result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8a in position 19: invalid start byte

Execution failed after 0.08 seconds

Loading resulting layers
Algorithm 'Roughness' finished
```

and using QGIS 3.19.0-Master (407a93de):
```
QGIS version: 3.19.0-Master
QGIS code revision: 407a93de
Qt version: 5.15.2
GDAL version: 3.2.1
GEOS version: 3.9.0-CAPI-1.16.2
PROJ version: Rel. 7.2.1, January 1st, 2021
Processing algorithm…
Algorithm 'Roughness' starting…
Input parameters:
{ 'BAND' : 1, 'COMPUTE_EDGES' : False, 'INPUT' : 'C:/TEST/dtm_aspromonte.tif', 'OPTIONS' : 'COMPRESS=JPEG|JPEG_QUALITY=75', 'OUTPUT' : 'TEMPORARY_OUTPUT' }

GDAL command:
gdaldem roughness C:/TEST/dtm_aspromonte.tif C:/Users/Andrea/AppData/Local/Temp/processing_cRbETk/d8c92e5a5afd43cb970dd9db734cf0b4/OUTPUT.tif -of GTiff -b 1 -co COMPRESS=JPEG|JPEG_QUALITY=75
GDAL command output:
Warning 6: 'JPEG|JPEG_QUALITY=75' is an unexpected value for COMPRESS creation option of type string-select.
Warning 5: COMPRESS=JPEG|JPEG_QUALITY=75 value not recognised, ignoring.
ERROR 1: PROJ: proj_create_from_name: Cannot find proj.db
0...10...20...30...40...50...60...70...80...90...100 - done.
Process completed successfully
Execution completed in 0.41 seconds
Results:
{'OUTPUT': 'C:/Users/Andrea/AppData/Local/Temp/processing_cRbETk/d8c92e5a5afd43cb970dd9db734cf0b4/OUTPUT.tif'}

Loading resulting layers
Algorithm 'Roughness' finished
```

The issue seems to be due to a bug in the GDAL Roughness algorithm which fails to properly pass the compression parameters.
