### ISSUE TITLE
Unavailable parameter in processing.run documentation

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#42241]
https://qgis.org/pyqgis/master/core/QgsProcessingAlgorithm.html#qgis.core.QgsProcessingAlgorithm.run states
![image](https://user-images.githubusercontent.com/7983394/111133923-5b0d4500-857b-11eb-9b32-6c75e62fd723.png)

`If specified, ok will be set to True if algorithm was successfully run.`Afaics, there is no `ok` in the python parameters; there however seems to be one at https://github.com/qgis/QGIS/blob/b4025442e8faede81766806c1c5ff4c5a4a95c0d/src/core/processing/qgsprocessingalgorithm.h#L379
Also should there be a doc for QgsProcessingExeptions? It's highlighted in the doc but unlike the other classes, no link provided.

**Comment by agiudiceandrea** [comment]
It seems the same occurs for:
- QgsExifTools.getGeoTag https://qgis.org/pyqgis/master/analysis/QgsExifTools.html#qgis.analysis.QgsExifTools.getGeoTag
- QgsLayout.loadFromTemplate https://qgis.org/pyqgis/master/core/QgsLayout.html#qgis.core.QgsLayout.loadFromTemplate
- QgsLayoutItemPage.decodePageOrientation https://qgis.org/pyqgis/master/core/QgsLayoutItemPage.html#qgis.core.QgsLayoutItemPage.decodePageOrientation
- QgsLayoutUtils.decodePaperOrientation https://qgis.org/pyqgis/master/core/QgsLayoutUtils.html#qgis.core.QgsLayoutUtils.decodePaperOrientation
- ...
- ...

**Comment by DelazJ** [comment]
Looking closely to the methods parameters, there's an `SIP_OUT` flag(?) next to the ok parameter, which might explain why it does not appear in PyQGIS doc
https://github.com/qgis/QGIS/blob/b4025442e8faede81766806c1c5ff4c5a4a95c0d/src/core/processing/qgsprocessingalgorithm.h#L390

**Comment by alexbruy** [comment]
Not a bug. Python docs are generated from C++ API docs and above mentioned sentence is true for C++ API call, see https://api.qgis.org/api/classQgsProcessingAlgorithm.html#ae5acd1608189b9f7973540748058b7f2.

**Comment by DelazJ** [comment]
@alexbruy So if I get it correctly, for C++, `ok` is a valid parameter but it's not expected in Python. Not a code bug but looks to me like a confusing information for unaware people. Is there no way we could hide these confusing paragraphs in the generated python docs?
