### ISSUE TITLE
Gdal -overwrite option not added after Qgis asks for overwrite

### ISSUE THREAD

**Issue by nicogodet** [qgis/QGIS#42248]
**Describe the bug**

-overwrite option is missing in gdal command after I explicitly ask for overwrite an existing file when dialog was displayed.
It results in an error
```
Sortie de commande GDAL :
ERROR 1: Output dataset T:/blablabla/Q100_L_MNE.tif exists, 
but some command line options were provided indicating a new dataset 
should be created. Please delete existing dataset and run again.
Le processus a renvoyé le code erreur 1
```

If I manually add `-overwrite` in additional options, it obviously works as expected.

**How to Reproduce**

1. Use for example "Clip raster by mask layer" or "extent"...
2. Clip a raster
3. Clip a raster again and output to previously clipped raster, answer "YES" to the displayed dialog.
4. See error -->

**QGIS and OS versions**

Qgis 3.18.0 new OSgeo4w
Win10

**Additional context**

**Comment by nicogodet** [comment]
Duplicate #31380...
The implemented method in #30377 does not exactly fix both this issue and #31380 as the user would except `-overwrite` option to be added after he answer YES to the displayed dialog.

**Comment by roya0045** [comment]
I'm not sure if this is a bug or should be a feature request now that additional parameters are possible.

**Comment by nicogodet** [comment]
Adding 
```python
  if os.path.exists(out):
    arguments.append('-overwrite')
```
after 
https://github.com/qgis/QGIS/blob/f80a7541ed9d5a277505e0702cbccf9f5f584902/python/plugins/processing/algs/gdal/ClipRasterByMask.py#L180
is a quick fix.

**Comment by Houska1** [comment]
> I'm not sure if this is a bug or should be a feature request now that additional parameters are possible.

I'd say if we (QGIS) ask user whether to overwrite the file, but then ignore a yes reply and fail to instruct GDAL to overwrite, then it's a bug.

**Comment by roya0045** [comment]
> Adding
> 
> ```python
>   if os.path.exists(out):
>     arguments.append('-overwrite')
> ```
> 
> after
> https://github.com/qgis/QGIS/blob/f80a7541ed9d5a277505e0702cbccf9f5f584902/python/plugins/processing/algs/gdal/ClipRasterByMask.py#L180
> 
> 
> is a quick fix.
> Same for every gdal alg...

This will disregard the propt. You need to find a way to obtain the prompt value and then apply it if positive. Not always assume an overwrite.

**Comment by nicogodet** [comment]
The only way to exit dialog filled with an existing filepath is to answer Yes.
So if `os.path.exists(out)` is `True`, it implicitly means you answer Yes.

Unfortunatly I didn't find a way to catch the prompt value in PyQgis doc `QgsProcessingParameterRasterDestination` or `parameterAsOutputLayer`.
But I agree to find a way to catch the prompt value instead of checking if output file exists.

**Comment by nyalldawson** [comment]
I'd argue that the algorithms should ALWAYS use the -overwrite option. This would match the behaviour of the qgis, grass, saga etc algorithms which will always overwrite existing files when the algorithm is run.

The user already has the warning regarding the overwrite when they pick an existing file as the destination from the file picker, so I think it's safe to always overwrite.

**Comment by nicogodet** [comment]
Should I go ahead and propose a PR as it should be simple python ?
2 options:

- Always append `-overwrite`
- Check if output file exists and append `-overwrite` as described in https://github.com/qgis/QGIS/issues/42248#issuecomment-799614794

**Comment by nyalldawson** [comment]
@nicogodet 

That'd be great thanks -- please go with the always overwrite option

**Comment by nicogodet** [comment]
@nyalldawson 

Ok. You can assign me to this issue, the PR might come next week.
