### ISSUE TITLE
[3.16.4] UI not fitting defined sizes

### ISSUE THREAD

**Issue by spono** [qgis/QGIS#42247]
**Describe the bug**
In many cases since the upgrade to 3.16.4 I found discrepancies related to the size of elements.

To ease the comprehension, I attach the four cases I encountered till now:
1. text partially covered because too big if compared to its box
![add_field](https://user-images.githubusercontent.com/14940295/111176458-a63e4c80-85a9-11eb-96eb-ff1101e748d3.png)

2. text partially covered because the box is not big enough (field name was 'area')
![field_name](https://user-images.githubusercontent.com/14940295/111176487-acccc400-85a9-11eb-8344-95000a8ef744.png)

3. big distance between label and related field
![layer_prop](https://user-images.githubusercontent.com/14940295/111176538-b7875900-85a9-11eb-891d-26318b8e2449.png)

4. box of svg files in Print Composer exceeding the bounds of the screen (while the main program window was perfectly within the size of the screen)
![out_of_bounds](https://user-images.githubusercontent.com/14940295/111176567-bd7d3a00-85a9-11eb-8b66-53447210ddd4.png)

**QGIS and OS versions**

QGIS 3.16.4 from Osgeo4W on W10

**Comment by Pedro-Murteira** [comment]
Still valid on QGIS 3.22.3.

**Comment by alexbruy** [comment]
Are you using non-standard UI theme?

**Comment by spono** [comment]
nope, simply using the "Night Mapping" theme.

(BTW: still valid in 3.28.9 on W10)

**Comment by nirvn** [comment]
@spono , is this still an issue?

**Comment by spono** [comment]
@nirvn : using the Night Mapping theme on 3.34.9, only bullet n.1 and n. 4 seems solved.
As a crosscheck I opened a new profile with the base theme and only bullet n. 3 seems unsolved yet, as you can see in the following screenshot:

![UX](https://github.com/user-attachments/assets/35a5e160-c859-4232-b7f3-d425b24a25c3)

**Comment by nirvn** [comment]
@spono , that's the combobox narrowing its width to fit available width on the dialog I think, no?

**Comment by spono** [comment]
it's the combobox in the attribute table of an active layer. The field "HANDLE" is reduced to a poor "HAN", and this is quite a big issue when you have fields wit similar name and different ending. Let's say that increasing the box size x2-z2.5 would be good enough to fit at least the 10-characters names of fields contained in shapefiles leaving enough room on the right bar for most of common use expressions
