### ISSUE TITLE
3.18 Georefencing causing QGIS to crash 

### ISSUE THREAD

**Issue by tookiebunten** [qgis/QGIS#42258]
**Describe the bug**

 Load a .jpg image into the georeferencer. Raster => Georeferencer...

Split screen as per image below. Click on .jpeg image, click on corresponding point on the Open Street. Continue until all points are mapped. Set out put Raster setting. Proceed to load into new layer in the project. This is when QGIS crashes and I have to force quit the application.

**How to Reproduce**

Basically following the usual georefencing process creating points via the map on the jpeg and loading into a new layer

**QGIS and OS versions**

QGIS version
3.18.0-Zürich
QGIS code revision
bdef9fb328
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
batch_hillshader-master; 
processing_fusion; 
ViewshedAnalysis; 
db_manager; 
MetaSearch; 
processing

**Additional context**

![image](https://user-images.githubusercontent.com/370548/111224157-f4694500-85d5-11eb-847d-f7223d50e164.png)

**Comment by nicogodet** [comment]
Duplicate #41770

**Comment by Spartacus1** [comment]
Hi gioman

Please reopen this issue. All the duplicates seem also to be closed. However, in all the latest versions, starting in 3.18, the Georeferencer is not working, at least in macOS. Cheers

**Comment by Spartacus1** [comment]
Already posted an issue entry in the plug-in's bug tracker. 
Cheers
