### ISSUE TITLE
rotate precisely around a snapped-to-point

### ISSUE THREAD

**Issue by faridcher** [qgis/QGIS#42251]
With Rotate tool, the rotation center changes by holding CTRL key and left clicking on the map canvas. However, it is  impossible to precisely snap to a point or a vertex and set it as the rotation center. A nasty [workaround](https://gis.stackexchange.com/questions/322262/rotating-shape-around-defined-point-instead-of-centroid-in-qgis) is to zoom maximally to get within the milimeter vicinity of that point. Please make snapping work with rotate tool.

QGIS 3.10.14

**Comment by uclaros** [comment]
There is already #26936 and #39698 about that.

**Comment by faridcher** [comment]
@uclaros thank you. Closed in the favor of those.
