### ISSUE TITLE
qgis-ltr-bin.exe is not responding

### ISSUE THREAD

**Issue by tl165** [qgis/QGIS#42252]
Hello,

when I try to start QGis 3.16.4 I alwas have the problem: "qgis-ltr-bin.exe is not responding".
 
![qgis-report](https://user-images.githubusercontent.com/80714240/111208766-77d16900-85cb-11eb-94da-826dd4c1035d.PNG)

This problem always apears afte rebooting my Computer for the first time. I already tried newly setting up my Computer but now after the first reboot I have the same problem.

I already search for the problem online but nobody seems to have the exact same issue.

thanks for help or tips, 
tl

**Comment by gioman** [comment]
@tl165 likely a local issue. Try removing the QGIS folder in your Windows user folder (inside AppData).

**Comment by tl165** [comment]
hi gioman,
thanks for the quick answer, but it still does not work. I think it got to be something witch stays on my computer even if I delete QGIS an install it again.
I read somewhere that the problem might be the registry kyes, but I dont know anything about them.
tl

**Comment by gioman** [comment]
> hi gioman,
> thanks for the quick answer, but it still does not work. I think it got to be something witch stays on my computer even if I delete QGIS an install it again.
> I read somewhere that the problem might be the registry kyes, but I dont know anything about them.
> tl

@tl165 sorry, still seems a local issue and not a general one. So can we close?

**Comment by tl165** [comment]
Yes, 
think I won't use qgis then.
thanks & bye
