### ISSUE TITLE
please add input forms for setting output path into Rasterize tools

### ISSUE THREAD

**Issue by chisquare88** [qgis/QGIS#42268]
**Feature description.**

I can't find input forms for setting output path at Rasterize tools (in GDAL->Vector conversion at Processing Toolbox)

**Additional context**

<img width="931" alt="qgis_helpme" src="https://user-images.githubusercontent.com/6187128/111261195-66d53600-8665-11eb-8958-0e48beb62aef.png">

**Comment by gioman** [comment]
@chisquare88 this specific tool is to **overwrite** an existing raster (as the name suggests).
