### ISSUE TITLE
Server: WFS3/API Features - Error 500: HTML template error

### ISSUE THREAD

**Issue by dmarteau** [qgis/QGIS#42275]
**Describe the bug**

Requesting feature collection item in html fail with with internal server error 500:
```
Error parsing template file: /usr/share/qgis/resources/server/api/ogc/templates/wfs3/getFeatures.html - [json.exception.type_error.302] type must be number, but is string
```

Note that a sample project is project is provided but the problem occurs with any project so far.

**How to Reproduce**

Run server and request item collection in html format: ```http://localhost:8888/ows/wfs3/collections/france_parts/items.html?MAP=france_parts``` (or from `http://localhost:8888/ows/wfs3/collections/france_parts.html?MAP=france_parts` and select `france_parts items as HTML`

**QGIS and OS versions**

* Qgis 31604 (Hannover) (official ltr package)
* Ubuntu 20.04 

[project.zip](https://github.com/qgis/QGIS/files/6149606/project.zip)

**Comment by elpaso** [comment]
@rldhont of course I'll take care of it, but I prefer to choose what I'm going to work on by myself.

**Comment by rldhont** [comment]
sorry @elpaso I was thinking like reviewing.

**Comment by elpaso** [comment]
@rldhont no problems. It's fixed but we probably need a test. I thought there were tests but I must be wrong.
