### ISSUE TITLE
Advanced Digitizing regression on snapping on parallel/perpendicular drawing with defined distance

### ISSUE THREAD

**Issue by ponceta** [qgis/QGIS#42279]
**Describe the bug**
When drawing with advanced digitizing, it was possible to draw parallel / perpendicular to previously drawn edge direction. Very efficient when digitizing quickly some geometric "squared" forms.

I can provide more infos on how it worked before if needed.

![AD_snaping_parallel_perpendicular](https://user-images.githubusercontent.com/8614223/111331170-eddbdb80-8670-11eb-987f-87215e5540c9.gif)

**How to Reproduce**

1. Load an editable Layer
2. Click on activate editing / + advanced digitizing
3. Create two vertex in construction mode
4. Set a defined length
5. It is now impossible to snap in the parallel or perpendicular direction as it was in QGIS 3.10.X

**QGIS and OS versions**
QGIS 3.16.4

**Additional context**

**Comment by pigreco** [comment]
I also confirm with a clean profile

## OSGeo4W64 Win 10 QGIS 3.16.4

**Comment by roya0045** [comment]
@uclaros could it be related to #39242 ? Or I'm way off in the rhubarb.

**Comment by uclaros** [comment]
@roya0045 It seems you are spot on! #39242 changed the default setting of *Snap to common angles* from 90deg to disabled, so new profiles have this disabled by default, while older profiles have it on its previously selected setting.
I don't think there is a bug here though, all you have to do is click on the cog on advanced digitizing panel and select the common angle you wish to snap to!

**Comment by roya0045** [comment]
@uclaros would it be better to have it enabled by default and then have user disable it? I'd assume that if a CAD behavior is desired such features should be on at the start? Or was the disabling critical?

**Comment by uclaros** [comment]
It used to be enabled by default and cause trouble to unsuspected users, see #39166 for an example.

**Comment by roya0045** [comment]
I've looked at it, though though I'm not sure that disabling a feature to 'hide' a discrepancy between displayed and actual resolution priority was the final solution (no offense intended). Disabling it by default did not resolve the problem as it should occur anyway once the two are enabled regardless. Unless I am missing something?

**Comment by uclaros** [comment]
The problem is not the order of precedence between snapping and advanced digitizing. The advanced digitizing constraints are always supposed to have higher priority and this is a given. The problem is that when the user does not know it is enabled, the behavior is unexpected! Default settings should be more neutral especially for intrusive features such as this, and they are only a click away for users that actually need them.
Again, we're only talking about clean-profile default values here, change it once and you're good to go!

**Comment by ponceta** [comment]
Hi,
I understand now that this setting is now in the profile, so nothing to fix technically here.
But imagine on the user perspective, it worked on the same project QGIS 3.10.14 and not anymore in 3.16.4, for the end user it's a bug => need to be proactive on communicating this change.

Also on the user perspective, I would prefer an active snapping to common 90-180-270-0 angles by default. When it's hidden and deactivated, for a casual user it doesn't exists. Of course I understand if it's not possible due to technical reasons.

![image](https://user-images.githubusercontent.com/8614223/111422677-55d10700-86ef-11eb-99af-849a68f2192f.png)

https://docs.qgis.org/3.16/en/docs/user_manual/working_with_vector/editing_geometry_attributes.html#snapping-settings

**Comment by uclaros** [comment]
> But imagine on the user perspective, it worked on the same project QGIS 3.10.14 and not anymore in 3.16.4

For the same user it should work the same, since the setting was stored in his profile. Maybe we could have the setting stored on the project too so that a saved project will work the same regardless of profile settings.



> Also on the user perspective, I would prefer an active snapping to common 90-180-270-0 angles by default. When it's hidden and deactivated, for a casual user it doesn't exists. Of course I understand if it's not possible due to technical reasons.

It is possible but it is not desired. Just as snapping, avoid overlaps, snap to intersections etc it should default to disabled.

**Comment by uclaros** [comment]
We could also change the way the *snap to common angles* cog is displayed, so that one can easily distinguish whether it is enabled or disabled without clicking on it!
