### ISSUE TITLE
Pseudocolor renderer - linear color ramp - 8 layers in single legend causing acrobat error with GeoPDF

### ISSUE THREAD

**Issue by davidlgalt** [qgis/QGIS#42288]
I use GeoPDFs to display multiple (more than 10) raster layers in a single acrobat document
. This worked fine until 3.18 where I started getting an error, in the exported GeoPDF. On the QGIS side, it gives no indication of an issue.

The error seems to happen when I have more than 7 continuous raster layers in the same legend. Bizarre, but I have tested multiple times and this seems to be the behavior.

[continuous raster geopdf issue.zip](https://github.com/qgis/QGIS/files/6153494/continuous.raster.geopdf.issue.zip)

**Comment by roya0045** [comment]
acrobat limitation?

**Comment by gioman** [comment]
> This worked fine until 3.18

@davidlgalt this means that you are getting the issue only when using master?

**Comment by davidlgalt** [comment]
I am only getting the issue with the continuous legend style that was
introduced at 3.18. My current workaround is to create multiple legends
none of which have more than 7 layers.

**Comment by roya0045** [comment]
But normal export works fine with the  7+ continuous raster symbols, right?

**Comment by davidlgalt** [comment]
Yes. Normal PDF export (i.e. not GeoPDF) works fine. 

Also, I am adding new sample data as the one I previously added wasn't exactly the same symbology as I was getting the error with.
[318_continuous_raster_error.zip](https://github.com/qgis/QGIS/files/6159933/318_continuous_raster_error.zip)

**Comment by nyalldawson** [comment]
@davidlgalt FYI 3.18.1 introduces an option to disable new graduated legend and use the older separate items style, so when that's released later this week you'll be able to switch back to the 3.16 behavior

**Comment by davidlgalt** [comment]
It seems as though I may have fixed my issue (fingers crossed). When I installed 3.18, I did so using the old osgeo installer -- not knowing there was a new version. 

After I deleted the old OSGeo4W64 directory, reinstalled with the new version and found and repointed all my path references it now seems to be working. The website still seems to be pointing to the old installer. I only got the new installer by clicking the link inside the announcement.

**Comment by davidlgalt** [comment]
@nyalldawson It will be good to have the option to go back to the old style. I do quite like the new style. I would really like to see it have interim values, not display the **Band 1: Height** by default (it's a space-eater) and in horizontal mode have the ability to put the values on top and perhaps angle them.  Of those mods, the interim values are the most important for map readability.

**Comment by davidlgalt** [comment]
I can confirm that a reinstall using the new OSGeo4W installer has fixed this issue for me and that I am no longer receiving the Acrobat errors.
