### ISSUE TITLE
Qgis crash 

### ISSUE THREAD

**Issue by acernegundo** [qgis/QGIS#42282]
Qgis crash when I try to change invalid features filtering option to Skip (ignore) features with invalid geometries

## User Feedback

Qgis crash when I try to change invalid features filtering option to Skip (ignore) features with invalid geometries

## Report Details

**Crash ID**: [d5cca8f3b32c14b99580ae2e4e347837010f090c](https://github.com/qgis/QGIS/search?q=d5cca8f3b32c14b99580ae2e4e347837010f090c&type=Issues)

**Stack Trace**
<pre>
PyDict_MaybeUntrack :
PyDict_MaybeUntrack :
PyMethod_ClearFreeList :
PyMethod_ClearFreeList :
PyMethod_ClearFreeList :
PyType_GenericAlloc :
PyObject_SetItem :
PyObject_FastCallKeywords :
PyObject_Call :
PyInit_sip :
slot_QgsProcessingParameterDefinition_Flags___or__ sip_corepart3.cpp:117649
PyNumber_And :
PyNumber_Or :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyFunction_FastCallDict :
PyTuple_New :
PyObject_FastCallKeywords :
PyObject_FastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_sip :
sipVH__core_1 sip_corepart0.cpp:23255
sipQgsProcessingProvider::loadAlgorithms sip_corepart3.cpp:66476
QgsProcessingProvider::refreshAlgorithms qgsprocessingprovider.cpp:76
meth_QgsProcessingProvider_refreshAlgorithms sip_corepart3.cpp:68340
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_sip :
sipVH__gui_34 sip_guipart0.cpp:8825
sipQgsOptionsPageWidget::apply sip_guipart7.cpp:27612
QgsOptions::saveOptions qgsoptions.cpp:1894
QMetaObject::activate :
QDialog::done :
QMetaObject::activate :
QDialogButtonBox::~QDialogButtonBox :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
QgisApp::showOptionsDialog qgisapp.cpp:12350
meth_QgisInterface_showOptionsDialog sip_guipart10.cpp:171102
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1637
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.16.4-Hannover
QGIS code revision: 654e76b3cb
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

**Comment by gioman** [comment]
@acernegundo please add **detailed steps** to replicate, and also try with a new QGIS profile, no 3rd party plugins installed. If the problem persist attach also project+sample data.

**Comment by Popielica** [comment]
@acernegundo Try turn off and on default processing plugin. Then change option to Skip (ignore) features with invalid geometries.

**Comment by acernegundo** [comment]
> 
> 
> @acernegundo Try turn off and on default processing plugin. Then change option to Skip (ignore) features with invalid geometries.

This step solved the issue, then I changed the option to Skip (ignore) features with invalid geometries. Now everything work ok

Thanks

**Comment by gioman** [comment]
> This step solved the issue, then I changed the option to Skip (ignore) features with invalid geometries. Now everything work ok

@acernegundo if you turn it on again, it crashes? if yes, can you please attach a sample dataset and tell us what tool you are using?
