### ISSUE TITLE
Cannot add new features in MSSQL if primary key name contains a hyphen

### ISSUE THREAD

**Issue by olsen232** [qgis/QGIS#42290]
Apologies, no dataset is included - you can use any dataset you have lying around, as long as you can figure out how to get it loaded onto a MSSQL server.

**Describe the bug**
When editing a MSSQL layer in QGIS, if the layer's primary key field has a name like "test-fid" which has a hyphen in it, then QGIS cannot add any new features to the layer. The UI for adding the new features works, but when it comes time to save those new features, QGIS fails to write the changes, displaying instead the following error message:

```
Could not commit changes to layer test_table

Errors: ERROR: 1 feature(s) not added.
  
  Provider errors:
      [FreeTDS][SQL Server]Statement(s) could not be prepared. [FreeTDS][SQL Server]Incorrect syntax near '-'. QODBC3: Unable to execute statement
```

**How to Reproduce**

To reproduce, you need a MSSQL server that you can connect to using QGIS, which must already have some table with geographic data in it, and to which you can also connect directly to modify the tables (ie, by using `sqlcmd`).

1. On your MSSQL server, find a geographic table that you don't mind messing with to test on. Perhaps you can duplicate an existing table: https://docs.microsoft.com/en-us/sql/relational-databases/tables/duplicate-tables?view=sql-server-2017
2. Open QGIS and connect to your MSSQL database. Add the chosen <test_table> as an active layer. 
3. Verify that you can add new features to <test_table> layer, AND, that you can save the newly created features.
4. Remove the layer from your active layers.
5. Connect to your MSSQL server using `sqlcmd` or similar, and change the name of the primary key column in your test table so that it now contains a hyphen. Using sqlcmd, this is:
`sp_rename '<test_table>.<pk_column_name>' '<new-pk-column-name>';`
`GO`
That is: `sp_rename` followed by `<the fully qualified name of a column, in single quotes>` followed by `<the new name of the column, in quotes, unqualified>`. Then type `GO` on a line of its own.
6. Go back to QGIS. Refresh your connection to the MSSQL, and add <test_table> as an active layer again.
7. Try to add new features to `test_table`. At first it seems to work, but...
8. Try to save the changes and verify that you see the error message attached above.

**QGIS and OS versions**

QGIS version | 3.16.3-Hannover | QGIS code revision | 3a90ea3afd
-- | -- | -- | --
Compiled against Qt | 5.14.2 | Running against Qt | 5.14.2
Compiled against GDAL/OGR | 3.1.2 | Running against GDAL/OGR | 3.1.2
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.4
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | macOS 10.15
Active python plugins | processing; db_manager; MetaSearch

**Comment by hamishcampbell** [comment]
A minimal example and some more investigation.

### Simple Case

You can easily replicate a simple case via the following. With `sqlcmd` run:

```
CREATE SCHEMA test;
CREATE TABLE test.test ([test-field] int);
GO
```

In your DB browser find the table and add it to the map (you might have to select "Show Non-spatial Tables" in the right-click menu for the mssql connection)

<img width="303" alt="Screen Shot 2021-03-17 at 9 52 44 PM" src="https://user-images.githubusercontent.com/295074/111440452-3bd50a00-876b-11eb-8a21-a50ec5a9335d.png">

Select the table in the Layers list, open the attributes table and start editing. Add a new feature with any value:

<img width="298" alt="Screen Shot 2021-03-17 at 9 54 36 PM" src="https://user-images.githubusercontent.com/295074/111440577-5f985000-876b-11eb-8f95-b2fdb1a0ece7.png">

Press "save edits". The save fails and the log message appears like so:

```
2021-03-17T21:52:19     CRITICAL    Layer test : [FreeTDS][SQL Server]Statement(s) could not be prepared. [FreeTDS][SQL Server]Incorrect syntax near '-'. QODBC3: Unable to execute statement
2021-03-17T21:52:19     WARNING    Commit errors : Could not commit changes to layer test
```

### More than one field

It appears that the following table schema will _not_ raise the issue:

```
CREATE TABLE test.test2 (foo int, [test-field] int);
```

Creating features in this schema is fine.

### Setting Primary Key

Following from the previous example, if we set `test-field` as a primary key like so:

```
CREATE TABLE test.test3 (foo int, [test-field] int NOT NULL);
ALTER TABLE test.test3 ADD CONSTRAINT test3_pk PRIMARY KEY ([test-field]);
GO
```

We can no longer insert new features.

### Possible cause

The only case that I can see on inspection where field names might be missing the same square bracket quoting as elsewhere is in this line https://github.com/qgis/QGIS/blob/7af87414a14a11a02ef85ed20fdf52fe36d200f0/src/providers/mssql/qgsmssqlprovider.cpp#L1189.

**Comment by roya0045** [comment]
Field names containing math symbols seem to be an issue in general. You can also notice that when using such a name for a classified render and switching to rule-based. The symbol is interpreted as an operation between the two fields rather than a single field.
