### ISSUE TITLE
Marker Symbol as Labeling Background: Opacity of symbol not used 

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#42308]
**Describe the bug**
When used as labeling background symbol, the opacity of the Marker Symbol itself is not taken into account.

The opacity *can* be controlled by the opacity of the color of the Marker Symbol itself or by using the opacity slider directly in the Layer Styling -> Background dialog. I assume that the latter overrides the opacity slider of the Marker Symbol.

I would expect both sliders to reflect and affect the same data.

(PS: The Marker Symbol's preview in the Background dialog is correctly rendered.)

**How to Reproduce**

1. Use a Marker Symbol as background for labels in Layer Styling -> Background
2. Set the Marker Symbol's opacity to something <100% using the symbol's dialog, not the slider in the labeling background dialog.
3. The opacity does not change.

Example screenshot, according to the Marker Symbol's settings those green circles should be highly transparent:

![image](https://user-images.githubusercontent.com/7661092/111608340-6362bb80-87d9-11eb-9f17-bf8cce7dc81a.png)

**QGIS and OS versions**

QGIS version | 3.18.0-Zürich | QGIS code branch | Release 3.18
-- | -- | -- | --
Compiled against Qt | 5.15.2 | Running against Qt | 5.15.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.35.0 | Running against SQLite | 3.35.1
PostgreSQL Client Version | 13.2 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.6 | QScintilla2 Version | 2.12.1
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Arch Linux

**Comment by Pedro-Murteira** [comment]
@kannes I can no longer replicate this bug on QGIS 3.16.14 and 3.22.1, the opacity changes with the dialog and the sliding bar, as it is originally intended.

**Comment by kannes** [comment]
Thank you so much for testing this! I can also confirm this bug was fixed in the meantime.
