### ISSUE TITLE
Error on adding Arcgis Vector tile layer

### ISSUE THREAD

**Issue by FelisPimeja** [qgis/QGIS#42314]
I'm trying to add ArcGIS Vector Tile layer
Service URL: https://pkk.rosreestr.ru/arcgis/rest/services/Hosted/caddivsion/VectorTileServer
Style URL: https://pkk.rosreestr.ru/arcgis/rest/services/Hosted/caddivsion/VectorTileServer/resources/styles

On adding layer to the map I get an error: CRITICAL    **Layer is not valid : The layer is not a valid layer and can not be added to the map** and a bunch of normal requests in Dev Console

The service is available you can check it through browser:
https://pkk.rosreestr.ru/arcgis/rest/services/Hosted/caddivsion/VectorTileServer/tile/11/673/1617.pbf

![image](https://user-images.githubusercontent.com/874261/111668790-28877480-8827-11eb-84da-4f18594d98a6.png)

Windows 10
QGIS Stable and Master - same behavior

**Comment by FelisPimeja** [comment]
Figured it out. They swapped {x} and {y} in tile address...
Can be added as a generic Vector tiles connection.

**Comment by nyalldawson** [comment]
This is a valid bug, let's get it fixed...
