### ISSUE TITLE
In Layout mode clicking "Image source" to change north arrow symbol leads to exception and total breakdown.

### ISSUE THREAD

**Issue by api2001** [qgis/QGIS#42327]
## User Feedback

Just clicked on North Arrow Item properties on "image source" :-(
Third crash in 15 minutes after using QGIS :-/

## Report Details

**Crash ID**: [8fc10c9862cf4492c40a01d86c64c12a996b6110](https://github.com/qgis/QGIS/search?q=8fc10c9862cf4492c40a01d86c64c12a996b6110&type=Issues)

**Stack Trace**
<pre>
QgsExpressionContextUtils::layoutItemScope :
QgsLayoutItem::createExpressionContext :
QgsPropertyOverrideButton::aboutToShowMenu :
QMetaObject::activate :
QMenu::popup :
QMenu::exec :
QToolButton::paintEvent :
QToolButton::showMenu :
QToolButton::~QToolButton :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::mousePressEvent :
QToolButton::mousePressEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.12.3-Bucure?ti
QGIS code revision: 8234261527
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

**Comment by gioman** [comment]
>  QGIS Version: 3.12.3-Bucure?ti

@api2001 way too old and completely unsupported. You must test with the latest 3.16.4 and if the problem persist also test on a new QGIS profile.

**Comment by api2001** [comment]
Okay sorry, not using qgis too often so time passes by quickly 😉
