### ISSUE TITLE
to_datetime expression function example is broken on non-english locale.

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#42325]
**Describe the bug**
One `to_datetime` expression function example is broken on non-"en" locale.

**How to Reproduce**

The second example for the `to_datetime` function is `to_datetime('June 29, 2019 @ 12:34','MMMM d, yyyy @ HH:mm')` → `2019-06-29T12:34`. "June" is the month name in English and thus the parsing will only work if the user's locale is "en"-something. On a German locale it fails.

- The documentation of the function should include a note about the locale being used by default.
- The affected example should get a note next to the example result.

**QGIS and OS versions**

QGIS-Version | 3.18.0-Zürich | QGIS-Codeversion | bdef9fb328
-- | -- | -- | --
Kompiliert gegen Qt | 5.12.8 | Laufendes Qt | 5.12.8
Kompiliert mit GDAL/OGR | 3.0.4 | Läuft mit GDAL/OGR | 3.0.4
Kompiliert mit GEOS | 3.8.0-CAPI-1.13.1 | Läuft mit GEOS | 3.8.0-CAPI-1.13.1
Kompiliert mit SQLite | 3.31.1 | Läuft mit SQLite | 3.31.1
Gegen PDAL kompiliert | 2.0.1 | Läuft mit PDAL | 2.0.1 (git-version: Release)
PostgreSQL-Client-Version | 12.6 (Ubuntu 12.6-0ubuntu0.20.04.1) | SpatiaLite-Version | 4.3.0a
QWT-Version | 6.1.4 | QScintilla2-Version | 2.11.2
Kompiliert mit PROJ | 6.3.1 | Läuft mit PROJ | Rel. 6.3.1, February 10th, 2020
BS-Version | Ubuntu 20.04.2 LTS

**Comment by kannes** [comment]
I will do those fixes on the weekend.

**Comment by DelazJ** [comment]
Then you might also want to update to_date and format_date
