### ISSUE TITLE
Print Composer vs. Export map as PDF - Problems with WMTS from basemap.at

### ISSUE THREAD

**Issue by pyAlpineRisk** [qgis/QGIS#42330]
I am trying to create a map with QGIS 3.16.4 by using the WMTS of [basemap.at 
](https://maps.wien.gv.at/basemap/1.0.0/WMTSCapabilities.xml) The map in the Print Composer looks fine, but when I try to export my map as PDF, the visualized scale level is changing. It looks like the next larger scale of the tile cache is used for the export. That happens with the Standard Basemap as well as the High DPI version. I am not sure if that is a general QGIS issue or a basemap.at problem.

1. Data Source Manager - WMS/WMTS
2. Add the WMTS of [basemap.at 
](https://maps.wien.gv.at/basemap/1.0.0/WMTSCapabilities.xml)
3. Add the Basemap High DPI
4. Open the Print Composer and add the Basemap. Scale can be 1:10.000 for example
5. Export as PDF
6. Compare the PDF with the map in the Print Composer

**Version: QGIS 3.16.4**

Maybe someone can help me with that problem!? Thanks a lot!

Print Composer
![Basemap_HDPI_PrintComposer_10000](https://user-images.githubusercontent.com/52344347/111788908-e9a5fd00-88c0-11eb-9ed6-83f9f042bce7.JPG)

Exported Map (PDF)
![ExportedMap_BasemapHDPI_10000](https://user-images.githubusercontent.com/52344347/111789201-2d006b80-88c1-11eb-8d75-40971e1cb737.jpg)

**Comment by roya0045** [comment]
Is your output dpi the same?

**Comment by Niki1986** [comment]
Sorry, forgot to mention that.300 DPI and the output also has 300 DPI.

**Comment by Niki1986** [comment]
Yes, you are right. It is the same problem, but it looks like it was not really solved. Changing the export DPI makes no difference. And the other workaround is not really satisfying. The Print Composer should show the same than what I see in my exported map. Despite from that creating a map with QGIS is really awesome!

**Comment by gioman** [comment]
> but it looks like it was not really solved.

@Niki1986 in fact it is not closed. Closing as duplicate.

**Comment by Niki1986** [comment]
Sorry, I did not see #36847 when I started this issue...
