### ISSUE TITLE
Scientific Notation values are interpreted as a decimal number

### ISSUE THREAD

**Issue by andremano** [qgis/QGIS#42333]
**Describe the bug**
Certain expressions can output a value expressed in Scientific Notation (SN). This value however appears to loose its significance once it is calculated, becoming a regular decimal number.

**How to Reproduce**

1 - Add a field `"perimeter"` of type Double to the geopackage attached to this report [test_polygon.zip](https://github.com/qgis/QGIS/files/6171726/test_polygon.zip)
2 - Use the following expression to fill `perimeter($geometry)`
3 - Add a second field `"calc"` and try for example `"perimeter"*10`

The values cast into field `"calc" `are not consistent with Scientif Notation.

This issue could be circumvented if there is a function to convert from SN to Real (See feature request [#42332])

**QGIS and OS versions**

QGIS version
3.16.3-Hannover
QGIS code revision
94ac9f21b8
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
batchvectorlayersaver; 
cartography_tools; 
CityJSON-loader; 
DataPlotly; 
disconnected-islands; 
GeoCoding; 
JSONEater-master; 
latlontools; 
lizmap; 
mmqgis; 
OpenTripPlannerPlugin; 
ORStools; 
pluginbuilder3; 
qgis2web; 
qgis_range_filters-master; 
QNEAT3; 
QPackage; 
QuickOSM; 
quick_map_services; 
SemiAutomaticClassificationPlugin; 
temporalprofiletool; 
valuetool; 
db_manager; 
MetaSearch; 
processing

**Additional context**

This can also be 

a problem in the context of the processing modeler

**Comment by roya0045** [comment]
Pretty sure its the other way around and the notation is just a font for the true float value.

**Comment by gioman** [comment]
> Pretty sure its the other way around and the notation is just a font for the true float value.

@roya0045 it does not seems to be the case, seems a pretty legit bug.

**Comment by roya0045** [comment]
@gioman https://github.com/qgis/QGIS/blob/5bd0058bae511e1b3cfeb07ac5fb41b7028047de/src/core/qgsfield.cpp#L254 uses the float value and relies on qt to convert to a string. Storing any value in scientific notation may lead to loss of information otherwise.

**Comment by andremano** [comment]
I am now closing this bug report as I can confirm this problem does not ocur in the contex of processing model provided you use the correct variables. Thank you for taking the time to look at it.
