### ISSUE TITLE
osgeo4w: updating already installed version to a new version, doesn't change the start search result 

### ISSUE THREAD

**Issue by EranGeo** [qgis/QGIS#42342]
**Describe the bug**

On a MS Windows OS, updating an existing latest realse installation using the `osgeo4w-setup.exe` installer, doesn't change the 'start-search-results' when entering 'qgis'. That is: the search result opens the `[installation_folder]\bin\qgis-bin.exe`, while its current version is displayed using **an old version title**. For example, after installing the new 3.18.1 version, the 'qgis' search result  still obtain the old 3.16.3 installation title:

![windows start - qgis search](https://user-images.githubusercontent.com/47955227/111864680-20d0e880-896b-11eb-95ab-b5543ec76b29.png)

 This doesn't affect the underlining file being opened correctly. 

**How to Reproduce**

1. Install an n-1 version of QGIS on a MS Windows OS, using Osgeo4W installer.
2. search the keyword 'qgis' in the start\win-key dialog. Inspect the result
3. Update the n-1 version to be n version of QGIS, using Osgeo4W installer.
4. search the keyword 'qgis' in the start\win-key dialog. Inspect the result

**QGIS and OS versions**

QGIS version | 3.18.1-Zürich | QGIS code revision | 202f1bf7e5
-- | -- | -- | --
Compiled against Qt | 5.15.2 | Running against Qt | 5.15.2
Compiled against GDAL/OGR | 3.2.2 | Running against GDAL/OGR | 3.2.2
Compiled against GEOS | 3.9.1-CAPI-1.14.2 | Running against GEOS | 3.9.1-CAPI-1.14.2
Compiled against SQLite | 3.33.0 | Running against SQLite | 3.33.0
Compiled against PDAL | 2.2.0 | Running against PDAL | 2.2.0 (git-version: 38aa11)
PostgreSQL Client Version | 13.0 | SpatiaLite Version | 5.0.1-rc1
QWT Version | 6.1.3 | QScintilla2 Version | 2.11.5
Compiled against PROJ | 8.0.0 | Running against PROJ | Rel. 8.0.0, March 1st, 2021
OS Version | Windows 10 Version 2009
Active python plugins | mapswipetool_plugin; OSMDownloader; qgis2web; quick_map_services; db_manager; MetaSearch; processing

**Additional context**

**Comment by jef-n** [comment]
not a qgis issue - but fixed in osgeo4w

**Comment by EranGeo** [comment]
Hi @jef-n ,
Thanks for fixing the issue, Does the fix applies for an already downloaded `osgeo4w-setup.exe` file or do I need to re-download it?
