### ISSUE TITLE
[QGIS 3.16.5] no longer loads VRT ogr layers

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#42346]
With QGIS 3.16.4 I could see the data, with QGIS 3.16.5 I can't see anything, what has changed? and how can i solve?

HOW TO PLAY:

I am attaching a VRT file that works in 3.16.4 and not in 3.16.5 and does not report any problems but the table is empty.

I attach the file; load it into QGIS with dragAndDrop

```
<OGRVRTDataSource>
<OGRVRTLayer name="QGIS-USER-TELEGRAM-REG">
    <SrcDataSource relativeToVRT="0">CSV:/vsicurl/https://docs.google.com/spreadsheets/d/e/2PACX-1vTx6h-a7JI5eNt2VPe7qkSb90lGQPC67-oz-2iXqcW056p1Z0Kkqwmp7cQY-mM-YTtH_8KjZjgnk4f4/pub?gid=1189600571&amp;single=true&amp;output=csv</SrcDataSource>
  <SrcLayer>pub?gid=1189600571&amp;single=true&amp;output=csv</SrcLayer>
    <Field name="cod_reg" type="Integer" />
    <Field name="regione" type="String" />
    <Field name="count cod_reg" type="Integer" />
	<Field name="popolazione" type="Integer" />
	<Field name="incidenza1M" type="Real" />
	<Field name="NUT2" type="String" />
</OGRVRTLayer>
</OGRVRTDataSource>
```

## OSGeo4W NG win 10

![image](https://user-images.githubusercontent.com/7631137/111871833-681ba100-898c-11eb-9d43-6e6c865d865c.png)

## file VRT
[qgis-utenti-telegram_reg.zip](https://github.com/qgis/QGIS/files/6175717/qgis-utenti-telegram_reg.zip)

**Comment by gioman** [comment]
@pigreco works fine here, tested before and after the upgrade from 3.16.4 to 3.16.5

![Screenshot_20210320_152625](https://user-images.githubusercontent.com/1951107/111875476-e464b300-8991-11eb-9718-6acd25c3f461.png)

**Comment by gioman** [comment]
Not visible in the screenshot, but the VRT table is not empty.

**Comment by pigreco** [comment]
@gioman 
did you use the new OSGeo4W?

https://lists.osgeo.org/pipermail/qgis-user/2021-February/048137.html

**Comment by gioman** [comment]
>  did you use the new OSGeo4W?

@pigreco is the new osgeo4w the one linked in qgis.org download page? if not then my opinion is that you should file this in the osgeo4w tracker, not here. https://trac.osgeo.org/osgeo4w/report/1?sort=ticket&asc=0&page=1

**Comment by agiudiceandrea** [comment]
This is definitely an OSGeo4W package issue only related to the new OSGeo4W testing repository.
The provided vrt file works fine with QGIS 3.16.5 and QGIS 3.18.1 installed on Windows 7 via the current OSGeo4W standalone installers (regular OSGeo4W repository).

**Comment by pigreco** [comment]
@agiudiceandrea 
so even in the `* .msi` versions available [here ](http://download.osgeo.org/qgis/win64/)it won't work?

**Comment by agiudiceandrea** [comment]
@pigreco I don't know, but I suppose the issue will occur also with the MSI installer, since it is built with the same packages contained in the new OSGeo4W testing repository.

**Comment by pigreco** [comment]
@gioman @agiudiceandrea 

https://trac.osgeo.org/osgeo4w/ticket/671#ticket

**Comment by pigreco** [comment]
@jef-n 
thank you so much
![image](https://user-images.githubusercontent.com/7631137/111960706-5ce18600-8af0-11eb-917d-a9c1cdcd7f6f.png)
