### ISSUE TITLE
The new standalone 3.18.1 installer installs instead 3.16.3

### ISSUE THREAD

**Issue by alburen** [qgis/QGIS#42344]
**Describe the bug**

After installing the recently compiled installer for windows of QGIS 3.18.1.1, instead, it´s installs QGIS 3.16.3 Hanover. 

Exactly "QGIS-OSGeo4W-3.18.1-1-Setup-x86_64.exe | 20-Mar-2021 06:03 | 390M" from the qgis.org/downloads page

**How to Reproduce**

1. Download and install https://qgis.org/downloads/QGIS-OSGeo4W-3.18.1-1-Setup-x86_64.exe
2. Open QGIS from "QGIS Desktop 3.16.3 with GRASS 7.8.5" from the QGIS 3.18 folder created in the Windows Desktop or from the direct access in the Windows 10 Start menu.

**QGIS and OS versions**

Versión de QGIS
3.16.3-Hannover
Revisión del código de QGIS
94ac9f21b8
Compilado contra Qt
5.11.2
Ejecutándose contra Qt
5.11.2
Compilado contra GDAL/OGR
3.1.4
Ejecutándose contra GDAL/OGR
3.1.4
Compilado contra GEOS
3.8.1-CAPI-1.13.3
Ejecutándose contra GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
Versión del cliente PostgreSQL
11.5
Versión de SpatiaLite
4.3.0
Versión de QWT
6.1.3
Versión de QScintilla2
2.10.8
Compilado contra PROJ
6.3.2
Ejecutándose contra PROJ
Rel. 6.3.2, May 1st, 2020
Versión del SO
Windows 10 (10.0)

**Comment by agiudiceandrea** [comment]
See https://trac.osgeo.org/osgeo4w/ticket/670

**Comment by agiudiceandrea** [comment]
This is fixed now. The new installer QGIS-OSGeo4W-3.18.1-1-Setup-x86_64.exe | 20-Mar-2021 20:29 | 391M correctly installs QGIS 3.18.1.
