### ISSUE TITLE
Saving to GPKG not working if source layer has "fid" field for primary key

### ISSUE THREAD

**Issue by phidrho** [qgis/QGIS#42350]
**Describe the bug**
If source layer has field called "fid", after running processing algorithm and trying to save result as GeoPackage layer, the result layer by default tries to reuse "fid" field as primary key for result layer. Problem occurs when result layer contains more than one feature in result layer for one feature in source layer. In result layer we have an reused "fid" primary key which repeats itself, and (I believe) SQLite throws an error for same primary key occurring more than once, and it stops entire transaction resulting empty result layer.
 
I have figured this out using "Point on surface" processing algorithm, but I believe that more algorithms are affected.

**How to Reproduce**
Run "Point on surface" processing algorithm on multipolygon layer, check option "Create point on surface for each part" and save it to GeoPackage layer.

Video description - https://youtu.be/5PNVjOtB37M

Here is an example project and data.
[example.zip](https://github.com/qgis/QGIS/files/6176367/example.zip)

**QGIS and OS versions**
I have tested on 3.16.3 and 3.18 on Windows
This bug should not be platform related.

**Comment by gioman** [comment]
@phidrho should be solved on installations with GDAL 3.3, see https://github.com/qgis/QGIS/issues/41156

**Comment by phidrho** [comment]
I have installed 3.18.0-15 qgis-rel-dev

QGIS version
3.18.0-Zürich
QGIS code revision
db732fc066
Compiled against Qt
5.11.2
Running against Qt
5.11.2
**Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.3.0dev**
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
8.1.0
Running against PROJ
Rel. 8.1.0, July 1st, 2021
OS Version
Windows 10 (10.0)
This copy of QGIS writes debugging output.
Active python plugins
AutomaticBackup-master; 
flight_planner; 
InvisibleLayersAndGroups; 
lockzoom; 
mmqgis; 
networks; 
qgis2web; 
qgsAzimuth; 
db_manager; 
processing



gdal
![image](https://user-images.githubusercontent.com/1849293/111886118-2c083080-89cc-11eb-92ae-5de15a8688a4.png)
