### ISSUE TITLE
QGIS 3.18.1 Invalid Data Provider when loading a QLR file from Browser

### ISSUE THREAD

**Issue by chleidersdorff** [qgis/QGIS#42366]
When trying to load .qlr files in QGIS 3.18.1 i get the following error: 
"Layer is not valid: The layer Z:/02 Data Library/Topography/Transport/TRAN_CCPRO_Combined.qlr is not a valid layer and can not be added to the map. Reason: Invalid provider".

I have tested this file works fine in the LTR version.

I am on Windows 10. update to 3.18.1 this morning using OSGEO4W. See screenshot below of installed modules etc.

![image](https://user-images.githubusercontent.com/52182284/111927338-1e51c880-8afc-11eb-8ff2-6531bc28a1c6.png)

![image](https://user-images.githubusercontent.com/52182284/111927248-d2068880-8afb-11eb-958d-f915285ef9cb.png)

**Comment by nyalldawson** [comment]
Can you share the .qlr?

**Comment by chleidersdorff** [comment]
Hi Nyall

I can but i just discovered that they work if you drag and drop them into a workspace from the windows explorer but not if you use the QGIS browser panel. Seems to be the same with all my .qlr files.

I have included the qlr file here:
[TENM_CCPRO_EPM_ML_Combined.zip](https://github.com/qgis/QGIS/files/6179427/TENM_CCPRO_EPM_ML_Combined.zip)
