### ISSUE TITLE
QGIS crashes by loading ui file

### ISSUE THREAD

**Issue by beli2go123** [qgis/QGIS#42379]
**Describe the bug**

QGIS crashes by opening a attribute formular using a ui-File.
UI-File works with LTR 3.10 and before. Since update to LTR 3.16 it crashes.

**How to Reproduce**

1. Open a Projekt in QGIS with defined ui file for attribute formular
2. Right Klick on the layer -> view attribut formular
3. Crash

**QGIS  and OS versions**

**Additional context**

**Comment by gioman** [comment]
@beli2go123 attach a sample project/data and the ui file, thanks.

**Comment by beli2go123** [comment]
[qgis_error_ui.zip](https://github.com/qgis/QGIS/files/6182326/qgis_error_ui.zip)

The Files included into the zip file work if they are under c:/temp.
Open the Projekt with 3.10 -> right klick on layer bc_flst_punkt and choose show attribute table.
switch the tabs in the form -> work.
do the same with 3.16 -> maybe it shows the first form, switching the tabs -> crash
do the same with 3.18 -> it wont't show the form and crashes.

thank you.

**Comment by roya0045** [comment]
Might be the changes in qt that broke this. Updating the file to be compatible with 5.15 should help for a while.

**Comment by troopa81** [comment]
I managed to reproduce the issue on Debian, It's due to the fact that the `libqgis_customwidgets.so` qt plugin from 3.10 version is installed and always loaded by QGIS. So it works with 3.10 but it crashes with other installed version. 

What's your OS, how do you install QGIS ? 

I'm pretty sure that if you have only one QGIS installed from an official way (Osgeo4W or debian/ubuntu packages) it'll work.

**Comment by troopa81** [comment]
OK, so I close the issue

**Comment by beli2go** [comment]
I find out the reason why qgis crashes.
Its a comination about the ui file (inside is a QgsRealtionReferenceWidget) and the definiton of the referenced field.
It the type of the field is reference (german: Beziehungsreferenz) there is the first check box after the reference field the "allow NULL" (german: NULL-Werte erlauben). If this box is checked (and there are NULL entries in the table) qgis crashes.
unchecking this box and everything works. It seems that this checkbox does exatly the opposite of the description sasy.

**Comment by PeterPetrik** [comment]
work OK on macOS QGIS 3.20 official all-in-one installer
