### ISSUE TITLE
No GPS-Tracking anymore available

### ISSUE THREAD

**Issue by stefan6605** [qgis/QGIS#42386]
<Neither QGI 3.4 nor 3.14 are anymore able to connect to my GPS- Devices (I have 3 devices of U-bloxx 7), although the so called u-center app is still able to receive the position of the GPS (meaning the GPS-Receivers still working well). Everything worked fine half a year ago, since than I never used this feature in QGIS anymore. I found this problem on both of my Windows-10 devices (Desktop and tablet). So I assume one of the latest Windows-updates is responsible for this issue. Anybody have the same problem?
Any ideas how to solve the problem? 
Thanks’ a lot in advance!
Stefan

**Comment by gioman** [comment]
@nyalldawson was support removed? or this is a legit bug? Not sure I can test this, maybe yes, I just got my GPS loggers back from @timlinux :) (when you talk about timing!)

**Comment by nyalldawson** [comment]
No, it's not been removed. I've tested and it's working correctly for me.

**Comment by jonnyforestGIS** [comment]
Tested on 4 Tablet GPS Getac and works fine. Cheers

**Comment by stefan6605** [comment]
Problem solved. Win10 has now (?) a feature in settings for allowing so called „Desktop-Apps“ access to use the location. This was disabled for both, my tablet as well as Desktop PC. Changing this setting solved the problem. Thanks’ to all contributors.
