### ISSUE TITLE
Add native LAS/LAZ support for LiDAR data

### ISSUE THREAD

**Issue by eabpgeospatial** [qgis/QGIS#42397]
Dear QGIS developers,

I am currently a GIS instructor working at a local College here in Ottawa teaching Geographic Information Systems and I also sell an open source GIS Tutorial Program on my website https://www.geospatialconsulting.app

I have worked both in ArcGIS and QGIS. A couple features that I believe would be useful for QGIS would be native LiDAR las or laz dataset support, with the ability to import, export and create terrain features using point clouds las datasets. You have started to introduce this with QGIS 3.18 but it only supports the EPT format. When I attempt to view the las files from my directory using the QGIS Browser window, QGIS crashes with the version 3.18.1.

ArcGIS recently introduced 3D animated water functionality for polygon symbology. When conducting a sea level analysis, I found this to be very helpful feature for in displaying a 3D animated Sea Level Rise. 

A tool for importing 3D building textures would be helpful. 

A native Pansharpening tool that could PanSharpen two different satellite images e.g. Landsat 5 and OrbView. I have been able to successfully accomplish this using SAGA GIS spectral pan sharpening tool, fusing Ottawa Landsat 5 with OrbView 3 imagery.

Currently I have to leave QGIS to create the 3D buildings using Blender and the Blender GIS plugin. Maybe in a future version of QGIS you could implement the ability to import 3D buildings using open street maps and include textures.

Thank you in advance.

Sincerely,

Eric

Email: eabpgeospatial@rogers.com

**Comment by gioman** [comment]
> When I attempt to view the las files from my directory using the QGIS Browser window, QGIS crashes with the version 3.18.1.

@eabpgeospatial please file a bug ticket using the proper page/template and filling all the requested details (and attaching sample data if needed) https://github.com/qgis/QGIS/issues/new?assignees=&labels=Bug&template=10_bug_report.md&title=

For the rest: please split each feature request in separate ticket, not before checking/searching if an equivalente request already exist. Thanks.



> ArcGIS recently introduced 3D animated water functionality for polygon symbology

link/reference?



> A native Pansharpening tool

like

![Screenshot_20210323_081417](https://user-images.githubusercontent.com/1951107/112114329-dab89680-8baf-11eb-9257-36e2d3a30696.png)

?



> Currently I have to leave QGIS to create the 3D buildings using Blender and the Blender GIS plugin. Maybe in a future version of QGIS you could implement the ability to import 3D buildings using open street maps and include textures.

have you missed the 3D symbology and 3D viewer?

**Comment by wonder-sk** [comment]
@eabpgeospatial actually QGIS 3.18 _does_ support LAS/LAZ out of the box, unfortunately some installers do not include PDAL library which is necessary for LAS/LAZ support. Especially on Windows the situation is very confusing now, as there are multiple different installers, but only some include LAS/LAZ support, and this is not properly documented on the download page :grimacing: 

If you are on windows - here's a little help which installer of QGIS 3.18.x to use - look for the one in section "Standalone installers from OSGeo4W testing packages (MSI)"

![image](https://user-images.githubusercontent.com/193367/112351114-e4ceb800-8cc9-11eb-8174-762d18f09d00.png)

**Comment by eabpgeospatial** [comment]
Thank you for the replies.

This is helpful and I will download the standalone installer and install QGIS 3.18 from the suggested image above. If successful I will incorporate the change in my GIS Tutorial Program.

I should have qualified my statement regarding the Pansharpening tool, by native support I meant including options for Pansharpening in the QGIS raster menu such as Brovey, Spectral, and others. I am hoping eventually there will be a tool that you can pansharpen two images from different dates and also takes into account land form changes. (e.g. Landsat 8 2020 fusing to Orbview 3 2004).

Thanks.

**Comment by gioman** [comment]
> ansharpening in the QGIS raster menu such as Brove

@eabpgeospatial like

![Screenshot_20210325_101013](https://user-images.githubusercontent.com/1951107/112456124-56eadf80-8d52-11eb-82f9-b59ca563176b.png)

?

**Comment by roya0045** [comment]
Should this remain open?
