### ISSUE TITLE
Python error when saving project

### ISSUE THREAD

**Issue by JC-VG** [qgis/QGIS#42391]
An error has occurred while executing Python code: 

ValueError: invalid literal for int() with base 10: '101.0' 
Traceback (most recent call last):
  File "C:/Users/miner/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SemiAutomaticClassificationPlugin\semiautomaticclassificationplugin.py", line 1581, in projectLoaded
    self.resetSCP()
  File "C:/Users/miner/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SemiAutomaticClassificationPlugin\semiautomaticclassificationplugin.py", line 1508, in resetSCP
    cfg.Max_ROI_width_spin.setValue(int(cfg.maxROIWdth))
ValueError: invalid literal for int() with base 10: '101.0'

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.16.3-Hannover Hannover, 94ac9f21b8 

Python Path:
C:/Users/miner/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\networks
C:/Users/miner/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\clusterpoints
C:/PROGRA~1/QGIS 3.16/apps/qgis/./python
C:/Users/miner/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/miner/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS 3.16/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS 3.16\apps\Python37
C:\PROGRA~1\QGIS 3.16\apps\Python37\Scripts
C:\Program Files\QGIS 3.16\bin\python37.zip
C:\PROGRA~1\QGIS 3.16\apps\Python37\DLLs
C:\PROGRA~1\QGIS 3.16\apps\Python37\lib
C:\Program Files\QGIS 3.16\bin
C:\PROGRA~1\QGIS 3.16\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS 3.16\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS 3.16\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS 3.16\apps\Python37\lib\site-packages\Pythonwin
C:/Users/miner/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/miner/OneDrive/Documents/GIS DataBase/Aster GDEM/Aster_RGB/AST_L1T_00301242008145501_20150522184809_93102
C:\Users\miner\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms

Has anyone had an issue similar to this? How to fix it?
Thanks

**Comment by nyalldawson** [comment]
This is a bug in a third party plugin -- you need to report it to the plugin authors instead
