### ISSUE TITLE
An error has occurred while executing Python code: 

### ISSUE THREAD

**Issue by mmeadowsresponse** [qgis/QGIS#42392]
When I start QGIS 3.16.5 I get the following message:

An error has occurred while executing Python code: 

SyntaxError: Missing parentheses in call to 'print'. Did you mean print("\nDownload Complete\n")? 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins\processing\script\ScriptAlgorithmProvider.py", line 121, in loadAlgorithms
    alg = ScriptUtils.loadAlgorithm(moduleName, filePath)
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins\processing\script\ScriptUtils.py", line 66, in loadAlgorithm
    spec.loader.exec_module(module)
  File "", line 724, in exec_module
  File "", line 860, in get_code
  File "", line 791, in source_to_code
  File "", line 219, in _call_with_frames_removed
  File "C:\Users\Matthew\AppData\Roaming\QGIS\QGIS3\profiles\default\processing\scripts\mapsheetdownloaddialog.py", line 515
    print "\nDownload Complete\n"
                                ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("\nDownload Complete\n")?

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.16.5-Hannover Hannover, 58ba7c1ed6 

Python Path:
C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python
C:/Users/Matthew/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Matthew/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3~1.16\apps\Python37
C:\PROGRA~1\QGIS3~1.16\apps\Python37\Scripts
C:\Program Files\QGIS 3.16\bin\python37.zip
C:\PROGRA~1\QGIS3~1.16\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib
C:\Program Files\QGIS 3.16\bin
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\Pythonwin
C:/Users/Matthew/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Matthew/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\joinmultiplelines
C:\Users\Matthew\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms
C:\Users\Matthew\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\SentinelHub\external\oauthlib-3.1.0-py2.py3-none-any.whl
C:\Users\Matthew\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\SentinelHub\external\requests_oauthlib-1.3.0-py2.py3-none-any.whl

**Comment by nyalldawson** [comment]
This is a bug in the "mapsheetdownloaddialog.py" processing script you have installed manually -- that's not a script which is part of QGIS, so you'll need to approach the original author of that script for support.

If you don't know what this script is, deleting the "C:\Users\Matthew\AppData\Roaming\QGIS\QGIS3\profiles\default\processing\scripts\mapsheetdownloaddialog.py" file will remove the error.
