### ISSUE TITLE
Geopackage Performance Bug / OSGEO4W QGIS compiled against GDAL 3.1.4

### ISSUE THREAD

**Issue by Poldy1705** [qgis/QGIS#42407]
Hello,

relating to the closed issues #42177 and #41822 it is very frustrating to see the actual QGIS Distribution 3.18.1 by OSGEO4W is compiled against GDAL Version 3.1.4.

The massive performance bug is fixed by using the GDAL 3.2.1. 
So all QGIS Users with projects based on geopackage layers are in trouble now. 
The bug is so elemtarily, i eaven cannot compile a QWC2 project because the QGIS Server runs into timeout by calling the Capabilities request.

I cannot understand why the bug reported by the original issue #36468 was fixed at the expense of all users using the OSGEO4W platform to install QGIS and it's dependencies.

Even the QGIS project start under 3.18.1 is so slowly compared to the 3.10 LTR. 2 minutes to few seconds.

Is there a possibility to update the GDAL Version for compiling the OSGEO4W QGIS from 3.1.4 to 3.2.x as soon as possible or otherwise refix the fix of #36468 ?

QGIS 3.18.1 Windows 64bit, GDAL 3.1.4

**Comment by gioman** [comment]
@Poldy1705 the installers in the new -experimental- osgeo4w installer give you QGIS with GDAL 3.2.+ I guess is just a matter of  waiting a little bit. Closing?

**Comment by Poldy1705** [comment]
We have to setup new server soon. So it‘s very Important  for me to know when  GDAL Version is updated.
I cannot install the experimental Version for Production environment.
Talking about next QGIS 3.18.2 Release in April or months?

**Comment by gioman** [comment]
>  Talking about next QGIS 3.18.2 Release in April or months?

@Poldy1705 this facility is to report bugs not discussions, if you want a quick reply is better to post in the developers mailing list.

**Comment by nyalldawson** [comment]
@Poldy1705 are you able to share your geopackage file? Do you have multiple layers from a single geopackage loaded into the server project?

**Comment by Poldy1705** [comment]
Yes, we have multiple layers from a single geopackage.
I shared the project. 

You got mail.
