### ISSUE TITLE
Passwords with non-ascii chars are wrongly base64 encoded for HTTP Basic auth 

### ISSUE THREAD

**Issue by landryb** [qgis/QGIS#42405]
**Describe the bug**

QGIS supports HTTP basic authentification, and that works great .. until one uses a password containing a non-ascii character.

I've tested various combinations with curl, and the `Authorization: Basic` header sent by QGIS 3.18 doesnt match the base64 encoded string that curl sends.

eg say with `landry.breuil:testtesté`, curl sends: `Authorization: Basic bGFuZHJ5LmJyZXVpbDp0ZXN0dGVzdMOp` and the server authenticated me okay.

with the same l/p, qgis network logger shows the header sent as `Authorization: Basic bGFuZHJ5LmJyZXVpbDp0ZXN0dGVzd0k=` which, once base64-decoded, reads `landry.breuil:testteswI` which doesn't match what was typed by the user, and the server rejects the authentication. Testing with tcpdump on the server, it receives the header qgis network logger says is sent.

That feels similar to #39243, unless this time its not about url-encoding, rather charset tables ?

**QGIS and OS versions**

QGIS 3.18.0 on OpenBSD

**Additional context**

remote server is nginx with auth-ldap module, which works fine against curl authenticated requests.

**Comment by landryb** [comment]
looking at cb010a347 i'm not sure `QString::fromLatin1( uri ) )` is correct as it changes the potential charset ?

**Comment by elpaso** [comment]
@landryb can you please add steps to reproduce?

**Comment by elpaso** [comment]
Nevermind, I can reproduce the error.

**Comment by landryb** [comment]
thanks @elpaso for looking at this !

Fwiw, i've tested a rebuild of 3.18.1 with c83539c applied on top, and for some reason the `Authorization` header sent is still wrong when using qgis. I suppose that the test added in the commit passes, but for some reason it doesnt fix all usecases ? 

Str:
- add a wms server requiring auth
- enter the login and password(with an accentued letter) in 'basic' tab
- try connecting, the header sent still looks wrong in qgis network logger

**Comment by elpaso** [comment]
@landryb that's exactly the check I did and it works for me:

![immagine](https://user-images.githubusercontent.com/142164/112437494-4e40dc00-8d47-11eb-9a12-1d20f321175a.png)

`cWdpczpxZ2lzQcOow6k=` is decoded to `qgis:qgisAèé`

**Comment by elpaso** [comment]
Oh, I see, you are not using the configurations.

**Comment by landryb** [comment]
yes sorry, should have specified that my testing was outside auth configurations - will confirm everything is okay once i've backported 1ca5782 to my local OpenBSD builds.

**Comment by landryb** [comment]
many thanks, that usecase also works fine with that commit locally applied !

**Comment by elpaso** [comment]
@landryb you're welcome!
