### ISSUE TITLE
Recently-used CRS not memorised among rapid choices

### ISSUE THREAD

**Issue by spono** [qgis/QGIS#42404]
**Describe the bug**
After creating some layers with the same CRS (e.g. 32632), the CRS itself is not memorised as a rapid choice for the creation of future layers.

![choice](https://user-images.githubusercontent.com/14940295/112161072-102ea580-8beb-11eb-9ccc-725da9f77713.png)

**QGIS and OS versions**

QGIS Info
QGIS Version: 3.16.5-Hannover
QGIS code revision: 58ba7c1ed6
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

**Comment by Pedro-Murteira** [comment]
@spono Hello, i've tested this issue and the last CRS used is always amongst the rapid choices, even after reloading QGIS. Did you come across this issue in more recent versions of QGIS? (Tested on QGIS 3.22.3, Windows 10)

**Comment by spono** [comment]
just tried on 3.22.3, W 10, and -among many other issues- this seems solved.
