### ISSUE TITLE
Python error during startup: Could not import script algorithm 

### ISSUE THREAD

**Issue by mmeadowsresponse** [qgis/QGIS#42417]
When I startup QGIS I get a python error.  In the processing tab of log messages window I have the following message:

2021-03-23T16:27:01     CRITICAL    Could not import script algorithm 'export_to_CSV' from 'C:\Users\Matthew\AppData\Roaming\QGIS\QGIS3\profiles\default\processing\scripts\export_to_CSV.py'
             module 'processing' has no attribute 'getObject'

An error has occurred while executing Python code: 

SyntaxError: invalid syntax 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.18/apps/qgis/./python/plugins\processing\script\ScriptAlgorithmProvider.py", line 121, in loadAlgorithms
    alg = ScriptUtils.loadAlgorithm(moduleName, filePath)
  File "C:/PROGRA~1/QGIS3~1.18/apps/qgis/./python/plugins\processing\script\ScriptUtils.py", line 66, in loadAlgorithm
    spec.loader.exec_module(module)
  File "", line 724, in exec_module
  File "", line 860, in get_code
  File "", line 791, in source_to_code
  File "", line 219, in _call_with_frames_removed
  File "C:\Users\Matthew\AppData\Roaming\QGIS\QGIS3\profiles\default\processing\scripts\plugin_upload.py", line 20
    print "Connecting to: %s" % hidepassword(address)
                            ^
SyntaxError: invalid syntax

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.18.1-Zürich Zürich, 202f1bf7e5 

Python Path:
C:/PROGRA~1/QGIS3~1.18/apps/qgis/./python
C:/Users/Matthew/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Matthew/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.18/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS3~1.18\apps\Python37
C:\PROGRA~1\QGIS3~1.18\apps\Python37\Scripts
C:\Program Files\QGIS 3.18\bin\python37.zip
C:\PROGRA~1\QGIS3~1.18\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.18\apps\Python37\lib
C:\Program Files\QGIS 3.18\bin
C:\PROGRA~1\QGIS3~1.18\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.18\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.18\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.18\apps\Python37\lib\site-packages\Pythonwin
C:/Users/Matthew/AppData/Roaming/QGIS/QGIS3\profiles\default/python

This is the version of QGIS I am running:

About:

QGIS version
3.18.1-Zürich
QGIS code revision
202f1bf7e5
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
oneatlas-qgis-plugin-1_0_1; 
SemiAutomaticClassificationPlugin; 
db_manager; 
MetaSearch; 
processing

**Comment by nyalldawson** [comment]
This is a bug in the "export_to_CSV.py" processing script you have installed. That script isn't part of QGIS, so you'll need to go to the script author for support.
