### ISSUE TITLE
Can no longer drag and drop a .qlr file into map window in 3.18.1

### ISSUE THREAD

**Issue by jcm36** [qgis/QGIS#42415]
Hi,

In the new QGIS 3.18.1 I can no longer drag and drop a .qlr file from the Browser panel into the main map window to load the contents of the .qlr file.  Dragging and dropping the qlr gives the following error:

"Layer is not valid: The layer ... ... is not a valid layer and can not be added to the map. Reason: Invalid provider"

I can still load the .qlr file using the menu item "Layer/Add later from definition file"

Here is a screenshot:
![Error Message](https://user-images.githubusercontent.com/9682969/112220528-3e63c200-8c8b-11eb-99da-69691d563988.png)

**How to Reproduce**

From the Browser panel, drag and drop a .qlr file into the main window.

**QGIS and OS versions**

QGIS version
3.18.1-Zürich
QGIS code revision
202f1bf7e5
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
AnotherDXF2Shape; 
CalculateGeometry; 
changeDataSource; 
crayfish; 
DataPlotly; 
kmltools; 
linz-data-importer; 
mapswipetool_plugin; 
mmqgis; 
points_to_catchments; 
processing_wbt; 
profiletool; 
qchainage; 
qepanet; 
QuickOSM; 
quick_map_services; 
Serval; 
processing

**Comment by gioman** [comment]
https://github.com/qgis/QGIS/issues/42366
