### ISSUE TITLE
Latest Release on qgis.org (Ubuntu Bionic) is 3.16 and not expected 3.18

### ISSUE THREAD

**Issue by kalab-oto** [qgis/QGIS#42432]
I tried to update (and also install from scratch) Latest Release (3.18) on Ubuntu Bionic from `qgis.org/ubuntu` repository (I don't use `ubuntugis`), than I found out that the latest version in `ubuntu` repository for Bionic seems to be 3.16.3, while in `ubuntu-ltr` is it version 3.16.5.

LR  - [https://qgis.org/ubuntu/dists/bionic/main/binary-amd64/Packages](https://qgis.org/ubuntu/dists/bionic/main/binary-amd64/Packages)

```
Version: 1:3.16.3+28bionic
Architecture: amd64
```

LTR - [https://qgis.org/ubuntu-ltr/dists/bionic/main/binary-amd64/Packages](https://qgis.org/ubuntu-ltr/dists/bionic/main/binary-amd64/Packages)

```
Version: 1:3.16.5+28bionic
Architecture: amd64
```
My configuration:
```
$ lsb_release -d
Description:	Ubuntu 18.04.5 LTS

$ grep gis /etc/apt/sources.list
deb https://qgis.org/ubuntu bionic main
# deb-src https://qgis.org/ubuntu bionic main

$ sudo apt-cache policy qgis
qgis:
  Instalovaná verze: 1:3.16.3+28bionic
  Kandidát:          1:3.16.3+28bionic
  Tabulka verzí:
 *** 1:3.16.3+28bionic 500
        500 https://qgis.org/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
     2.18.17+dfsg-1 500
        500 http://cz.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages

```

I expected that the Latest Release  in `ubuntu` repository will be 3.18.1 as in repository for Focal dist. Is this for some purpose?

**Comment by gioman** [comment]
@kalab-oto not exactly a bug in the code, this tracker is for. You should raise the problem on the developers mailing list.

**Comment by kalab-oto** [comment]
@gioman Thank you, so I sent it to the QGIS-Developer mailing list.
