### ISSUE TITLE
Do not create subdirectories in cache folder when cache size is 0

### ISSUE THREAD

**Issue by lucamanga** [qgis/QGIS#42436]
**Describe the bug**
Setting the "cache size" to 0, doesn't prevent the QGIS creating subfolders in cache folder (those named 0, 1, 2, etc).

This causes problems on WMS: if the folder is not empty, it throws an error on viewing a WMS. I solved this by denying write access to that cache folder.

**How to Reproduce**
Simply add a WMS layer. Those sub folders are created. 

**QGIS and OS versions**
QGIS 3.16.4 on Windows 7 and 10.

**Comment by alexbruy** [comment]
Can not reproduce with the latest master (096d741fe1) on Linux.

Can you check with the latest QGIS version? Also please elaborate which kind of errors do you see.
