### ISSUE TITLE
Panning map with arrow keys and the new feature of not refreshing the bakground map

### ISSUE THREAD

**Issue by oskarlin** [qgis/QGIS#42438]
**Describe the bug**
With the new version of QGIS (3.18.1) the map canvas is not entirely redrawn when panning which is extremely helpful! But what I've noticed is that if I have a satellite photo in the background and pan the canvas with the keyboard arrows so many stops so that the former map canvas will disappear to the left, for some reason, the whole canvas is shown with the old background map for a while until it get replaced by the new background containing the satellite photo. 

**How to Reproduce**

1. Add a raster background layer.
2. Pan the canvas at least 4 stops with the arrow keys on the computers keyboard.
3. The raster background of the old extent is shown at wrong place until the new background extent is loaded.

**QGIS and OS versions**
3.18.1-Zürich
MacOS 10.15.7

**Comment by Pedro-Murteira** [comment]
@oskarlin Hello, I'm not being able to reproduce this issue, either i'm not doing it correctly or it appears to be fixed. (QGIS 3.22.3). Did you come across this situation more recently?

**Comment by oskarlin** [comment]
Seems like it's working better now! Great!
