### ISSUE TITLE
In raster calculator, the AND and OR buttons insert the translated words

### ISSUE THREAD

**Issue by hermarman** [qgis/QGIS#42441]
When using Spanish language and raster calculator the AND and OR buttons insert the translated words Y (=AND) and O (=OR) into the expression instead of the correct, untranslated ones, resulting in a syntax error.

1. Set language to Spanish
2. Open raster calculator
3. Hit AND or OR buttons (labelled Y or O)
4. The spanish words Y / O are inserted, instead of AND / OR, the expression is incorrect

**QGIS and OS versions**

Versión de QGIS | 3.16.2-Hannover | Revisión del código de QGIS | f1660f9da5
-- | -- | -- | --
Compilado contra Qt | 5.11.2 | Ejecutándose contra Qt | 5.11.2
Compilado contra GDAL/OGR | 3.1.4 | Ejecutándose contra GDAL/OGR | 3.1.4
Compilado contra GEOS | 3.8.1-CAPI-1.13.3 | Ejecutándose contra GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
Versión del cliente PostgreSQL | 11.5 | Versión de SpatiaLite | 4.3.0
Versión de QWT | 6.1.3 | Versión de QScintilla2 | 2.10.8
Compilado contra PROJ | 6.3.2 | Ejecutándose contra PROJ | Rel. 6.3.2, May 1st, 2020
Versión del SO | Windows 10 (10.0)
Active python plugins | gdb2gpkg; mapswipetool_plugin; openlayers_plugin; db_manager; MetaSearch; processing

**Comment by agiudiceandrea** [comment]
I cannot replicate the reported behaviour using QGIS 3.16.5 on Windows (OSGeo4W standalone installer) with "español de España" as user interface translation language:

https://user-images.githubusercontent.com/16253859/112311138-a921f700-8ca5-11eb-9361-c08ac12f2715.mp4

**Comment by agiudiceandrea** [comment]
OK, now I see you are experiencing the issue with the Python version of the raster calculator, the Processing tool "Raster calculator" (qgis:rastercalculator), not the C++ version that is available through the Raster menu.

https://user-images.githubusercontent.com/16253859/112314212-0c615880-8ca9-11eb-98cd-f045c0ed7970.mp4

**Comment by hermarman** [comment]
Yes, that's what I was using, sorry, new to QGIS from other GIS, didn't know there were two different calculators :)

**Comment by hermarman** [comment]
I just noticed that the exact same issue happens with min() and sqrt().

**Comment by elpaso** [comment]
> Yes, that's what I was using, sorry, new to QGIS from other GIS, didn't know there were two different calculators :)

There are three actually :smiley:
