### ISSUE TITLE
QgsProcessingParameterRasterDestination flagged as "advanced" is not showing up under the "Advanced Parameters" group

### ISSUE THREAD

**Issue by AndreasRabe** [qgis/QGIS#42445]
**Describe the bug**

When adding a **QgsProcessingParameterRasterDestination** parameter and flag it as advanced (**QgsProcessingParameterDefinition.FlagAdvanced**), the parameter is not showing up correctly under the **"Advanced Parameters"** group. All other types of parameters are showing up correctly if flagged as advanced.

![image](https://user-images.githubusercontent.com/45030715/112317028-f4d79f00-8cab-11eb-802c-34de8aafbb5e.png)

**QGIS and OS versions**
QGIS-Version
3.16.0-Hannover
QGIS-Codeversion
43b64b13f3
Kompiliert gegen Qt
5.11.2
Laufendes Qt
5.11.2
Kompiliert mit GDAL/OGR
3.1.4
Läuft mit GDAL/OGR
3.1.4
Kompiliert mit GEOS
3.8.1-CAPI-1.13.3
Läuft mit GEOS
3.8.1-CAPI-1.13.3
Kompiliert mit SQLite
3.29.0
Läuft mit SQLite
3.29.0
PostgreSQL-Client-Version
11.5
SpatiaLite-Version
4.3.0
QWT-Version
6.1.3
QScintilla2-Version
2.10.8
Kompiliert mit PROJ
6.3.2
Läuft mit PROJ
Rel. 6.3.2, May 1st, 2020
BS-Version
Windows 10 (10.0)
Aktive Python-Erweiterungen
db_manager; 
MetaSearch; 
processing

**Comment by gioman** [comment]
>  3.16.0-Hannover

@AndreasRabe it is a bit old, can you test on 3.16.5? thanks.

**Comment by AndreasRabe** [comment]
Hi @alexbruy, 

> Maybe we should have another collapsible group for outputs, 

having another collapsible group would be fine for me, but output-parameters are placed after all the input-parameters anyway, so we already have a separation between both types. Putting the advanced outputs after the advanced inputs would be my prefered choice (if possible).

> but honestly I don't see a use case, as outputs which are not needed can be marked as optional and not created by default.

In my understanding, the "optional" flag is used to indicate, that the user can skip the calculation of an output. The "advanced" flag is used to hide the output from the GUI by default, resulting in a cleaner GUI.

Especially hiding optional outputs makes a lot of sense in my opinion.

Take this usecase: the algorithm trains a maschine learner (e.g. a RandomForestClassifier) and stores the model to disk. This would be the main purpose of the algorithm. Optionally, the user can apply the trained model, resulting in a classification raster. By hiding the optional output paraneters, the GUI looks much cleaner.

**Comment by AndreasRabe** [comment]
> @AndreasRabe it is a bit old, can you test on 3.16.5? thanks.

it's the same on QGIS 3.18.1
