### ISSUE TITLE
Label visibility by scale max/min values inconsitencies 

### ISSUE THREAD

**Issue by Forna73** [qgis/QGIS#42443]
I'm testing Qgis 3.16.5, but it is also in Qgis 3.10.8 (actually used).

I'm a little bit confused and I can't understand if it's a real bug or a misunderstandings of mine, but If I create a label and I check the "scale intervals" option I have to select "minimum (excluded) and "maximum (included)".
So I set "minimum" at 1.000.000 and "maximum" at 500.000
From what I understand at a scale between "min" and "max" and at "max" I should see the label, while I shouldn't see it at "minimum".
A part the fact I can't understand the logic to exclude one of the two extremes, actually if I set scale 1:1.000.000 I see the label that I shouldn't and at 1:500.000 scale I don't see it while I should. So basically Qgis does the opposite.
This happens in the CANVAS.
If I create a Layout and I draw 2 windows, one at 1:1.000.000 and the other at 1:500.000, I have the label in both of them!

**Comment by gioman** [comment]
@Forna73 so can you please resume the 

expected VS obtained

 behavior? Thanks

**Comment by Forna73** [comment]
Hi!
As I said as per what I understood from this "included" and "excluded" logic Qgis 3.16.5 does the opposite in the CANVAS, while  in the print layout it doesn't take care of the minimum scale valor.
Clearly I need the label to appear from 1.000.000 to 500.000 and all the scale between, so when I apply this scale visibility option I've found the workaround to set "minimum" (exluded) at 1.000.001 and "maximum" (included) at 499.999.

**Comment by gioman** [comment]
@Forna73 so can we resume the issue as "label scale visibility range min/max values are included in the print composer but are not in the canvas", seems correct?

**Comment by Forna73** [comment]
No!
_"...Qgis 3.16.5 does the opposite in the CANVAS..."_
_"...in the print layout it doesn't take care of the minimum scale valor."_

Both of them have an issue.

**Comment by gioman** [comment]
> Both of them have an issue.

@Forna73 then what is the difference?

**Comment by Forna73** [comment]
Taken for granted that Qgis 3.16.5 does the opposite the setting of Min and Max values, I expect to have the same behavior in print  layout.
Canvas and print layout are not coherent...

**Comment by gioman** [comment]
> Qgis 3.16.5 does the opposite

@Forna73 the opposite of another QGIS version? if yes what version?




> , I expect to have the same behavior in print layout.
> Canvas and print layout are not coherent...

sure, but what is the difference?

**Comment by Forna73** [comment]
let's try to explain this way...
CANVAS
@ minimum (excluded) = I shouldn't see the label => instead I see it => issue
@ maximum (included) = I should see the label => instead I don't see it => issue

PRINT LAYOUT **_(taken for CANVAS issue)_**
In a window set @ minimum (excluded) = I should see the label => I see it => coherent
In a window set @ maximum (included) = I shouldn't see the label => I see it => issue

**Comment by gioman** [comment]
> let's try to explain this way...
> CANVAS
> @ minimum (excluded) = I shouldn't see the label => instead I see it => issue
> @ maximum (included) = I should see the label => instead I don't see it => issue
> 
> PRINT LAYOUT **_(taken for CANVAS issue)_**
> In a window set @ minimum (excluded) = I should see the label => I see it => coherent

@Forna73 thanks. **now** is clear ;)

**Comment by Forna73** [comment]
;-)

**Comment by Pedro-Murteira** [comment]
This is still valid on QGIS 3.22.3.
