### ISSUE TITLE
QgsNetworkReplyContent.content() empty after HTTP error

### ISSUE THREAD

**Issue by nilsnolde** [qgis/QGIS#42442]
**Describe the bug**

When making a request via `QgsNetworkAccessManager`'s blocking methods, in case of a HTTP error I can't get the QGIS API to return the HTTP API's custom error message.. The `QgsNetworkReplyContent.errorString()` is only giving the generic error message based on the HTTP code. I'd expect any response content to be accessible over `QgsNetworkReplyContent.content()`, for errors and success.

**How to Reproduce**

In QGIS console (thanks to @ThomasG77 for the snippet via [SE](https://gis.stackexchange.com/questions/390913/qgsnetworkreplycontent-content-empty-after-http-error):

```python
unworkingUrl = QUrl('https://api.mapbox.com/valhalla/v1')

request = QNetworkRequest(unworkingUrl)
networkAccessManager = QgsNetworkAccessManager()
response = networkAccessManager.blockingGet(request)
status_code = response.attribute(QNetworkRequest.HttpStatusCodeAttribute)
if status_code == 200:
    print(response.content())
else:
    print(response.error())
    print(response.errorString())
    print(bytes(response.content()))
```

The last line will be output as `b''`, but should return `{"message":"Not Found"}`.

**QGIS and OS versions**

QGIS version | 3.18.0-Zürich | QGIS code branch | Release 3.18
-- | -- | -- | --
Compiled against Qt | 5.15.2 | Running against Qt | 5.15.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.34.1 | Running against SQLite | 3.34.1
PostgreSQL Client Version | 13.2 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.6 | QScintilla2 Version | 2.12.0
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Manjaro Linux
Active python plugins | d4s_processing_toolbox; nominatim_locator_filter; quick_api; quick_map_services; data_injection; tardis; ORStools; QuickOSM; mmqgis; plugin_reloader; latlontools; QuickWKT; pluginbuilder3; external_data_connector; valhalla; multi_line_exploder; resource_sharing_plugin; processing; MetaSearch; db_manager; access_road_generator

**Comment by ThomasG77** [comment]
Some clues by looking a the code

`setContent` is the method to fill the content part from the `QgsNetworkReplyContent` and called from https://github.com/qgis/QGIS/blob/master/src/core/network/qgsblockingnetworkrequest.cpp#L399 to do the job when no network error

In the `else` block, no reference https://github.com/qgis/QGIS/blob/master/src/core/network/qgsblockingnetworkrequest.cpp#L402-L411

**Comment by nilsnolde** [comment]
Maybe this shall finally be the time I get involved in core dev.. Most of my plugins deal with remote APIs and now I really got used to the comfort of QgsNetworkAccessManager :)
