### ISSUE TITLE
QGIS close if rename field function is interrupted during processing

### ISSUE THREAD

**Issue by pecard** [qgis/QGIS#42476]
QGIS simply close with no warning after interrupting rename field function (with iterate option selected).

session Info
![imagem](https://user-images.githubusercontent.com/173906/112460987-64ef2f00-8d57-11eb-8c48-7520ccdfa5c0.png)

**Comment by gioman** [comment]
@pecard Viva,

you must add the detailed list of steps to replicate the issue, attaching a sample project and data if necessary.

Please also test with a new QGIS profile.

**Comment by gioman** [comment]
@pecard also you must test on 3.16 or 3.18, as 3.14 is EOL.

**Comment by pecard** [comment]
Ok ok I'll try to add detail to the issue. thanks!
