### ISSUE TITLE
Import of qgis.core fails outside of QGIS

### ISSUE THREAD

**Issue by fuzzysolutions** [qgis/QGIS#42485]
**Describe the bug**
Sinde QGIS 3.18, I fail to load the QGIS API, namely qgis.core module, from applications outside QGIS like PyCharm or Sphinx. I don't get which path could be missing so I assume this could be a bug.

**How to Reproduce**
Most basically, starting python-qgis.bat on C:\OSGeo4W64\bin and importing something from the QGIS API already fails (and this should normally work, shouldn't it?):

```
Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from qgis.core import QgsFeature
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\OSGEO4~2\apps\qgis\python\qgis\core\__init__.py", line 25, in <module>
    from qgis._core import *
ImportError: DLL load failed while importing _core: Das angegebene Modul wurde nicht gefunden.
```

**QGIS and OS versions**

QGIS-Version | 3.18.1-Zürich | QGIS-Codeversion | 202f1bf7e5
-- | -- | -- | --
Kompiliert gegen Qt | 5.15.2 | Laufendes Qt | 5.15.2
Kompiliert mit GDAL/OGR | 3.2.2 | Läuft mit GDAL/OGR | 3.2.2
Kompiliert mit GEOS | 3.9.1-CAPI-1.14.2 | Läuft mit GEOS | 3.9.1-CAPI-1.14.2
Kompiliert mit SQLite | 3.35.2 | Läuft mit SQLite | 3.35.2
Gegen PDAL kompiliert | 2.2.0 | Läuft mit PDAL | 2.2.0 (git-version: 24dd45)
PostgreSQL-Client-Version | 13.0 | SpatiaLite-Version | 5.0.1
QWT-Version | 6.1.3 | QScintilla2-Version | 2.11.5
Kompiliert mit PROJ | 8.0.0 | Läuft mit PROJ | Rel. 8.0.0, March 1st, 2021
BS-Version | Windows 10 Version 2009
Aktive Python-Erweiterungen | RailTopoGIS; GeoCoding; ImportPhotos; LandXml; MemoryLayerSaver; openlayers_plugin; plugin_reloader; qconsolidate3; qgiscloud; qgistester; QPackage; QuickOSM; quick_map_services; db_manager; processing

**Comment by nicogodet** [comment]
Different error

```
C:\OSGeo4W64_new\bin>python-qgis.bat
Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from qgis.core import QgsFeature
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\OSGEO4~2\apps\qgis\python\qgis\__init__.py", line 70, in <module>
    from qgis.PyQt import QtCore
  File "C:\OSGEO4~2\apps\qgis\python\qgis\PyQt\QtCore.py", line 24, in <module>
    from PyQt5.QtCore import *
ImportError: DLL load failed while importing QtCore: Le module spécifié est introuvable.
>>>
```

**Comment by nicogodet** [comment]
linked to https://trac.osgeo.org/osgeo4w/ticket/669 ?

**Comment by agiudiceandrea** [comment]
Using the "regular" (not testing) OSGeo4W shell of QGIS 3.18.1 there is no issue importing from qgis.core

```
F:\QGIS\OSGeo4W_3.18.1\qgis>python-qgis.bat
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from qgis.core import QgsFeature
>>>
```

So it seems a packaging / dependencies issue of the new testing OSGeo4W.

**Comment by fuzzysolutions** [comment]
> linked to https://trac.osgeo.org/osgeo4w/ticket/669 ?

Yes it is, I started it there, but in the meantime after further testing had the feeling it could be caused directly by QGIS.
But as @agiudiceandrea tested ...

> Using the "regular" (not testing) OSGeo4W shell of QGIS 3.18.1 there is no issue importing from qgis.core
...
> So it seems a packaging / dependencies issue of the new testing OSGeo4W.

... we can be sure it's a packaging issue. Thanks for that check, I close it here and hope for a solution there.

@nicogodet : At first, I also had this error message in the shell too (not e.g. in PyCharm). I tried several things and as far as I remember installation of package qt5-tools was the one that solved this issue (and led me to the other one, which I already knew from PyCharm).

**Comment by agiudiceandrea** [comment]
Hi @fuzzysolutions, it seems to me the issue is fixed now in **OSGeo4W testing** with the updated qgis-3.18.1-3 and qgis-common-3.18.1-3 packages.

```
F:\QGIS\SourceDir\qgis>python-qgis.bat
Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from qgis.core import QgsFeature
>>>

```
