### ISSUE TITLE
CRS issue with GRASS raster tools

### ISSUE THREAD

**Issue by hrralph** [qgis/QGIS#42502]
Dear developer team

I found a strange issue regarding the CRS of raster output data in GRASS tools. I explain that bug on an often reproduced case:
I am processing raster data (10x10m)for Austria in EPSG:31287 (MGI /Austria Lambert) and all input data as well as the project itself have this CRS properly defined. When I run different raster tools from the GRASS toolbox (in my case mostly r.reclass and r.neighbors) in QGIS (I tested it on version 3.12, 3.14 and 3.16 as well as on MacOS and Windows - on all setups with the same issue)  the CRS of the output file gets a user defined CRS named USER:100029 plus a lot of projection parameters (those parameters are ident to MGI /Austria Lambert specifications plus WGS84 to MGI transformation parameters). The raster cells of this layers are visually slightly shifted in the map view (see images below).

When I change the CRS in the layer properties > source to EPSG:31287 or assign EPSG:31287 as projection (with GDAL > Raster projections > Assign projection) everything is fine. 

See images below for further details on that issue.

The user defined CRS in the select list:
<img width="1410" alt="HWbqH" src="https://user-images.githubusercontent.com/29124423/112622644-99ccb600-8e2b-11eb-967d-ff1f0ca26f30.png">

The slight cell shift on the left and in place after the assingment of EPSG:31287
<img width="1073" alt="rVGmH" src="https://user-images.githubusercontent.com/29124423/112622660-a0f3c400-8e2b-11eb-9853-e451dd96e5b4.png">

Thank you, Thomas

**Comment by gioman** [comment]
@hrralph try 3.18, it has been fixed there.

**Comment by gioman** [comment]
@hrralph ps: the title seems completely wrong

**Comment by roya0045** [comment]
Title does not match issue.

**Comment by hrralph** [comment]
Thank you for the quick response - I will try QGIS 3.18.
And sorry for the wrong title - GitHub kept the title from another message draft

**Comment by gioman** [comment]
>  I will try QGIS 3.18.

@hrralph reopen if necessary, but the issue you describe is fixed there.
