### ISSUE TITLE
QgsLayoutExporter doesn't work to a network path

### ISSUE THREAD

**Issue by trsbar** [qgis/QGIS#42501]
It's impossible to export a map to a network path. The output indicate a file error.

**To reproduce**

Get file path from `QFileDialog.getSaveFileUrl`
Export to a network file.

```
fileUrl = QtWidgets.QFileDialog.getSaveFileUrl(self.parent, "Enregistrer votre carte", str(Path.home()), "PDF(*.pdf);;JPG(*.jpg)")
if fileUrl[0].isEmpty() == False:
    fileName = fileUrl[0].fileName()
    filePath = fileUrl[0].path()
    # Layout manipulation...
    exporter = QgsLayoutExporter(layout)
    pdf_settings = QgsLayoutExporter.PdfExportSettings()
    pdf_settings.rasterizeWholeImage = True
    ret = exporter.exportToPdf(filePath, pdf_settings)
```

**QGIS and OS versions**
Windows 10 / QGIS 3.10.10

**Additional context**
Works well to a local file

**Comment by roya0045** [comment]
Are you sure your path is not just malformed? There are plenty of things that uses this internally and they have no issues with network path. The error is probably in your code.

**Comment by roya0045** [comment]
@gioman simple ping, if you can please add the feedback tag when you get a moment. Thanks!

**Comment by gioman** [comment]
@roya0045 done

**Comment by gioman** [comment]
Closing for lack of feedback.
