### ISSUE TITLE
Mac plugins not visible to standard user

### ISSUE THREAD

**Issue by ChrisWGeorge** [qgis/QGIS#42507]
**Describe the bug**

If I place a plugin in /Applications/QGIS-LTR.app/Contents/Resources/python/plugins as an admin user then I can see the plugin in the plugins list and install it.   But if I login as a standard user then the plugin does not appear in the plugins list and cannot be installed.  

**How to Reproduce**

See above.

**QGIS and OS versions**

QGIS version | 3.16.5-Hannover | QGIS code revision | 58ba7c1ed6
-- | -- | -- | --
Compiled against Qt | 5.14.2 | Running against Qt | 5.14.2
Compiled against GDAL/OGR | 3.2.1 | Running against GDAL/OGR | 3.2.1
Compiled against GEOS | 3.9.1-CAPI-1.14.2 | Running against GEOS | 3.9.1-CAPI-1.14.2
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.4
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | macOS 10.15
Active python plugins | remotedebug; plugin_reloader; processing; db_manager; MetaSearch

**Additional context**

**Comment by gioman** [comment]
Is this a bug at all? (3rd party) plugins are supposed to be (example for linux)

~/.local/share/QGIS/QGIS3/profiles/qgisprofilename/python/plugins

**Comment by ChrisWGeorge** [comment]
Turned out to be a problem with file permissions.
