### ISSUE TITLE
QGIS 3.18 crashes on new project

### ISSUE THREAD

**Issue by barneynibbs** [qgis/QGIS#42503]
## User Feedback

Just installed 3.18 and tried creating a new project - QGIS crashed.

## Report Details

**Crash ID**: [e67bebfa652dfc5d3a822341008f2e3c66e2df0c](https://github.com/qgis/QGIS/search?q=e67bebfa652dfc5d3a822341008f2e3c66e2df0c&type=Issues)

**Stack Trace**
<pre>
QgsLocatorModelBridge::locator qgslocatormodelbridge.cpp:125
QgisApp::editableLayers qgisapp.cpp:11400
QgisApp::updateLayerModifiedActions qgisapp.cpp:11387
QgisApp::activateDeactivateLayerRelatedActions qgisapp.cpp:14661
QMetaObject::activate :
QgisApp::activeLayerChanged moc_qgisapp.cpp:2800
QgisApp::onActiveLayerChanged qgisapp.cpp:717
QgisApp::closeProject qgisapp.cpp:13616
QgisApp::fileNew qgisapp.cpp:6520
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:475
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:475
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1638
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.18.1-Z�rich
QGIS code revision: 202f1bf7e5
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
@barneynibbs You must test with new QGIS profile. If you can't do it from within QGIS then just wipe out the QGIS folder inside your AppData one (which is in c:\users\yourusername).
