### ISSUE TITLE
Use native FindPackage.cmake scripts

### ISSUE THREAD

**Issue by m-kuhn** [qgis/QGIS#42518]
CMake ships a series of Find[Package].cmake scripts natively.
E.g. FindPython3 is proposed in #42497

There are a couple of candidates to be removed from our codebase and reduce our maintenance effort on them.

- FindGDAL.cmake -> same name
- FindGSL.cmake -> same name
- FindODBC.cmake -> same name
- FindPostgres.cmake -> FindPostgreSQL.cmake
- FindProj.cmake -> FindPROJ4 (also works for newer versions)

@PeterPetrik @jef-n do you see any trouble from windows/macos packaging side?
Should we just remove them and deal with the fallouts / revert if there are issues or do you prefer a different approach / not do it at all?

**Comment by AHB102** [comment]
@m-kuhn Is this issue still open ?

**Comment by m-kuhn** [comment]
Kind of yes, but this issue doesn't seem to be of much help and the definition of done is unclear.
Closing and will follow up as needed.
