### ISSUE TITLE
QGIS3.18.1 rander speed is much longer than 3.16.3

### ISSUE THREAD

**Issue by whyneedausername** [qgis/QGIS#42512]
**Describe the bug**
3.18.1 take 10+second to rander the map instead 3.16.3 rander finished like instant.

**How to Reproduce**
Install 3.18.1 and 3.16.3 both.

**QGIS and OS versions**
My system
G5905 16GB ram, GPU0 intel UHD 610, GPU1 GTX750 Ti. Win10 20H2

**Comment by roya0045** [comment]
..render you mean?

**Comment by nyalldawson** [comment]
This bug report is missing any useful detail to make it usable.
