### ISSUE TITLE
ArcGIS REST Servers - Connection failed: Parsing error

### ISSUE THREAD

**Issue by berniejconnors** [qgis/QGIS#42535]
**Describe the bug**
In QGIS 3.18.1 I cannot connect to ArcGIS Server REST services (also tested in QGIS 3.16.5 with the same results).  I have tried several different servers including:

- https://geonb.snb.ca/arcgis/rest/services
- https://geoappext.nrcan.gc.ca/arcgis/rest/services
- http://sampleserver1.arcgisonline.com/ArcGIS/rest/services

The following messages were displayed in the Log:

> 2021-03-28T15:34:27     WARNING    Network request https://geonb.snb.ca/arcgis/rest/services?f=json timed out

> 2021-03-28T15:36:49     WARNING    Network request https://geoappext.nrcan.gc.ca/arcgis/rest/services?f=json timed out

> 2021-03-28T15:42:54     WARNING    Network request http://sampleserver1.arcgisonline.com/ArcGIS/rest/services?f=json timed out

And in the browser pane the following error message was displayed:

> Connection failed: Parsing error

**How to Reproduce**

1. Open QGIS 3.18.1 (or 3.16.5) and open a new empty project
2. In the Browser pane right click on "ArcGIS REST Servers" and select "New Connection..."
3. Provide a name in the "Name" field - GeoNB
4. Provide a URL  - https://geonb.snb.ca/arcgis/rest/services
3. Click "OK"
4. In the Browser pane attempt to expand the tree for "GeoNB"
5. Wait for the timeout.  An error message will be displayed in the Browser pane and in the QGIS Network mesage log

![image](https://user-images.githubusercontent.com/13241302/112764446-ed333580-8fde-11eb-9efb-d6f4ee6e02d0.png)

**QGIS and OS versions**

> QGIS version
> 3.18.1-Zürich
> QGIS code revision
> 202f1bf7e5
> Compiled against Qt
> 5.11.2
> Running against Qt
> 5.11.2
> Compiled against GDAL/OGR
> 3.1.4
> Running against GDAL/OGR
> 3.1.4
> Compiled against GEOS
> 3.8.1-CAPI-1.13.3
> Running against GEOS
> 3.8.1-CAPI-1.13.3
> Compiled against SQLite
> 3.29.0
> Running against SQLite
> 3.29.0
> PostgreSQL Client Version
> 11.5
> SpatiaLite Version
> 4.3.0
> QWT Version
> 6.1.3
> QScintilla2 Version
> 2.10.8
> Compiled against PROJ
> 6.3.2
> Running against PROJ
> Rel. 6.3.2, May 1st, 2020
> OS Version
> Windows 10 (10.0)
> Active python plugins
> db_manager; 
> MetaSearch; 
> processing

> OS
> Windows 10 Enterprise, Version 1709, OS Build 16299.2166

**Additional context**

**Comment by nyalldawson** [comment]
These all work fine for me. Can you test another workstation on a different internet connection to verify that it's not a local networking/firewall/proxy issue?

**Comment by gioman** [comment]
They work fine here too.

![Screenshot_20210329_102948](https://user-images.githubusercontent.com/1951107/112816823-b65e2d80-9079-11eb-8103-93aacfa679f6.png)

**Comment by berniejconnors** [comment]
Thanks for the feedback @nyalldawson and @gioman.  I'll try to install QGIS on another computer and re-test this issue.

**Comment by berniejconnors** [comment]
I installed QGIS on my personal laptop and the ArcGIS Map Service connection worked perfectly and it was fast.  I tried again on my work laptop and I discovered the ArcGIS Map Service connection will only work while my VPN connection is active.
