### ISSUE TITLE
InputID field in distance matrix output behaves as string while displayed as integer if used as temporary layer

### ISSUE THREAD

**Issue by benjaminh** [qgis/QGIS#42545]
**Describe the bug**
When using distance matrix algorithm with an integer field as input ID, one can't make a join between the created InputID in the Distance matrix algorithm output and the input layer. Indeed, the InputID field is displayed as integer in layer properties, but it behaves as a string.

**How to Reproduce**

1. Create two layers A and B with an ID field of integer type for each layer (here `POINTID` and `TEMPID`)

![Capture du 2021-03-25 17-28-07](https://user-images.githubusercontent.com/1315419/112816727-fb865d80-9081-11eb-960f-f32301d78083.png)

![Capture du 2021-03-25 17-28-48](https://user-images.githubusercontent.com/1315419/112816759-04772f00-9082-11eb-8c3a-d45afbdbcd08.png)

2. Compute distance matrix between the 2 input layers
At this step, the temporary layer properties show InputID field as an integer of length 0. The execution console also displays field as `integer(0,0)`

![Capture du 2021-03-25 17-31-39](https://user-images.githubusercontent.com/1315419/112816803-10fb8780-9082-11eb-947a-80e058985b2b.png)

3. Use `join by attribute value` algorithm between the layer A and the InputID field in the *temporary* output layer created by Distance matrix

![Capture du 2021-03-25 17-41-52](https://user-images.githubusercontent.com/1315419/112816850-1ce74980-9082-11eb-96fa-881fc2ad6ed7.png)

Console should tell you no feature could be matched, just like the types of the fields do not match. Also, if you try to sort the InputID column field, it behaves as a string column (1,10,11,…,2, 21, 22, etc.)

![Capture du 2021-03-25 17-44-34](https://user-images.githubusercontent.com/1315419/112816876-22449400-9082-11eb-99a5-9ccb8792f262.png)

**QGIS and OS versions**

QGIS version | 3.10.8-A Coruña | QGIS code revision | d09a4f2388
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.6.2-CAPI-1.10.2 4d2925d6
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 10.12 (Ubuntu 10.12-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Ubuntu 18.04.5 LTS
Active python plugins | profiletool; FreehandRasterGeoreferencer; pointsamplingtool; processing; MetaSearch; db_manager

**Additional context**
I first opened a discussion on stackoverflow [here](https://gis.stackexchange.com/questions/391086/qgis-join-issue-on-tables-with-generated-unique-value-index-field) on having an issue to make a join, and it looks like someone else identified the problem as using temporary layer. It seems that saving the output layer as geopackage prevent this issue, but in my case, I need to operate on temporary layer, and I guess there is no reason to get a different behaviour, right ?

**Comment by DelazJ** [comment]
@benjaminh Can you try with a more recent QGIS version? 3.10.8 is a bit old, and unmaintained.

**Comment by benjaminh** [comment]
@DelazJ Oh right, when I started QGIS, the banner of 3.10 kept displaying "LTR" so I didn't notice there was a new LTR version.
Yet, I just upgraded to 3.16 (see version and OS table below), and the issue still occurs

QGIS version | 3.16.5-Hannover | QGIS code revision | 58ba7c1ed6
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.6.2-CAPI-1.10.2 4d2925d6
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 10.16 (Ubuntu 10.16-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Ubuntu 18.04.5 LTS
Active python plugins | profiletool; FreehandRasterGeoreferencer; pointsamplingtool; processing; MetaSearch; db_manager

**Comment by alexbruy** [comment]
Seems works fine in the latest master (096d741fe1). Can you re-test?

**Comment by benjaminh** [comment]
I don't have the latest (master) version installed, but I can confirm everything works fine at least with QGIS 3.23 :+1:

**Comment by alexbruy** [comment]
Thanks for checking! Closing then
