### ISSUE TITLE
Import of NetCDF fails upon order of variables

### ISSUE THREAD

**Issue by raphaeljolivet** [qgis/QGIS#42552]
Qgis version : 3.18.0-Zürich

I struggled to import a NetCDF file as a **mesh layer**.
I found that Qgis has strange and undocumented requirements for it.

The file in question : 
- Is fully compliant with [CF conventions ](http://cfconventions.org/) (checked with [CF-checker](https://github.com/cedadev/cf-checker)) 
- Has one time dimension 
- Has bidimensional lat, lon variables
- Has CRS / projection properly set for X and Y variables
- Has a single data variable "gis"
- Has been produced with "nkcs" 

I found first that QGis requires the dimensions to be in a specific order : time, y, x. 
To my knowledge, this does not corresponds to any convention.

Then, if the variables are in alphabetical order (gis, lat, lon, time, x, y ) the file imports correctly : 
- The layer is temporal
- The CRS is set
- Only one data variable "gis" is shown 

However, if the same file has different order of variables (time, x, y, lat, lon, gis) then : 
- The layer is not recognized as temporal
- The CRs is not set
- Two vairable are shown : lat, lon. gis is missing 

I think this should be fixed and / or explained clearly in [the documentation](https://docs.qgis.org/3.4/en/docs/user_manual/working_with_mesh/mesh_properties.html)

I attach both files here : [example-nc-files.zip](https://github.com/qgis/QGIS/files/6222288/example-nc-files.zip)

**Comment by roya0045** [comment]
@PeterPetrik Would you know if such issues are related to MDAL or QGIS-specific?

**Comment by PeterPetrik** [comment]
Hi, this is definitely MDAL issue please let discuss there.

**Comment by vcloarec** [comment]
@raphaeljolivet 
Indeed, it is a MDAL issue that will be fixed.
Can you use your data for testing in MDAL?
