### ISSUE TITLE
Automatically update Spatial Index if layer is edited

### ISSUE THREAD

**Issue by ngodber** [qgis/QGIS#42567]
**Feature description.**
When a layer that already has a spatial index created is edited the spatial index should automatically be recreated.

**Additional context**
Currently, there is a non-obvious issue when the spatial index no longer matches (ie after the layer has been edited) the layer where points will disappear/reappear depending on zoom level. New points that have been copied to the layer will also not display. Currently there are only two fixes available. 1) Manually remove the spatial index file (an option to delete the index in the properties prompt would also be useful here) or 2) recreate the index after every modification. This can be quite tedious during an extended period layer creation  where there is extensive modification and/or usage of spatial processing (which benefits enormously from the spatial index).

**Comment by kannes** [comment]
I've seen this issue being mentioned quite a few times by random people on the internet(tm).

**Comment by nyalldawson** [comment]
This should already be done by the underlying backend (ie ogr, postgres, etc). Can you describe a situation where it's not working correctly?

**Comment by ngodber** [comment]
Hi Nyall,

So I did some additional testing to see if I could trigger the behavior explicitly. So it appears the issue arises when I _add_ features, not delete them. The spatial index seems to automatically be updated when features are deleted, but not when they are added. 

So to reproduce I created a new layer in QGIS and randomly added some points. I think ran 'create spatial index'. I then added more points and saved. This triggered the 'disappear/reappear depending on zoom level' behavior described above. Finally, I edited the layer once again and deleted a couple of randomly selected other points. On save the spatial index was updated and the disappear/reappear behavior ceased. 

Note, I don't believe it is necessary that the default ID column need be unique so wasn't careful about assigning new features valid ID's. 

(As an aside, imagine my shock at discovering a major QGIS dev is based on the Sunshine Coast. Hi from Brisbane!)

Cheers,
Neil

**Comment by ngodber** [comment]
FWIW, this has been something I've run across intermittently for years and indeed figured out I needed to update the spatial index from a forum post somewhere on the webs.

**Comment by nyalldawson** [comment]
@ngodber what underlying data type are you using here? Is it a shp/gpkg/postgres db? 

Do you ONLY see this issue if you run the "create spatial index" tool mid-way through an edit session?

> (As an aside, imagine my shock at discovering a major QGIS dev is based on the Sunshine Coast. Hi from Brisbane!)

Hey down there... and thanks for ruining our Easter! :rofl: :mask: (joking!)

**Comment by ngodber** [comment]
The underlying data class is a shp. Ah sorry, just clarifying, I closed the edit session before creating the spatial index. Just for completeness, I tested 'create spatial index' from layer > properties, and via the toolbox (though I imagine they are probably the same) and the behavior popped up for both. So create spatial index > start editing session > add points > end editing session/save > appear/disappear behavior triggered.

**Comment by ngodber** [comment]
Also lockdown is over in 13 minutes, so you are welcome xD

**Comment by thbaumann** [comment]
I can confirm this issue. A colleague of mine was editing a shapefile and digitizing new lines (with QGIS LTR 3.16.5). The new lines were only visible until she saved the edits. Attached you can find a test-shapefile and a screencast. If you add one more line this line will also be insisible (at certain scales) after saving the edits. If you add more lines the qix file will be deleted by QGIS and the lines are visible again.
Having a look at the sidecarfiles shows that the qix file of the test-shapefile is older than the shp file. I guess it would be good if QGIS could check if the qix file is older than the shp file and if so delete/recreate the file.

Tested with QGIS LTR 3.16.5 and 3.16.8.
[Lines.zip](https://github.com/qgis/QGIS/files/6809859/Lines.zip)

https://user-images.githubusercontent.com/20082727/125478554-fa7d512b-493b-4ef2-b87f-2f8bee147c6f.mp4

**Comment by kannes** [comment]
@peauc it would be best if you write the exact steps (which buttons in which menus *exactly*) and environment to reproduce right here in the bug tracker.

**Comment by peauc** [comment]
Hello @kannes, thank you for taking the time to answer. 
As @ngodber said, my issue is exactly the same as them. 
It works perfectly fine on my linux, but not on the different windows machines of my team.

My guess is that the spacial index file(.qix) is not deleted properly on windows. I've seen on Linux, that if I add a spacial index file (qix), then add a new feature, the index file is deleted. However on windows the file is never deleted, and features have trouble being displayed UNTIL I delete the qix file, then everything is fine.

**Comment by kannes** [comment]
Awesome, thank you @elpaso!
