### ISSUE TITLE
QGIS 3.18 Crash

### ISSUE THREAD

**Issue by grantboxer** [qgis/QGIS#42568]
QGIS crashes on opening the layer properties for a temporary layer. Same problem does not appear to happen with 3.16.

## User Feedback

Crashes on opening Layer Properties.

## Report Details

**Crash ID**: [b0f4fb2661d5cc6c00b8a904bcdf30bdae3d9d27](https://github.com/qgis/QGIS/search?q=b0f4fb2661d5cc6c00b8a904bcdf30bdae3d9d27&type=Issues)

**Stack Trace**
<pre>
QObject::parent :
QLayout::addChildWidget :
QStackedLayout::insertWidget :
QgsRasterLayerProperties::addPropertiesPageFactory qgsrasterlayerproperties.cpp:561
QgisApp::showLayerProperties qgisapp.cpp:16271
QgisApp::layerProperties qgisapp.cpp:9296
QgisApp::layerTreeViewDoubleClicked qgisapp.cpp:677
QMetaObject::activate :
QAbstractItemView::doubleClicked :
QTreeView::mouseDoubleClickEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:475
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:475
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1638
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.18.1-Z�rich
QGIS code revision: 202f1bf7e5
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

**Comment by Gustry** [comment]
@grantboxer, please have a look to comment we made to you, you reported the same crash report a few days ago already #42463

Same Crash ID if you click on it https://github.com/qgis/QGIS/search?q=b0f4fb2661d5cc6c00b8a904bcdf30bdae3d9d27&type=Issues
