### ISSUE TITLE
More info when "Ballpark Transformation" warning is thrown

### ISSUE THREAD

**Issue by marcp1999** [qgis/QGIS#42580]
I have numerous projects that display the dreaded "Ballpark transform" warning upon opening.  Unfortunately they contain over 50 layers, so determining which layers are causing the problem is painful. My suggestion is simply to include the layer name in the message log. 

For example this:
`2021-03-30T10:28:03     WARNING    Used a ballpark transform from EPSG:4326 to EPSG:26913`
would be logged as this
`2021-03-30T10:28:03     WARNING    Layer "Targets" Used a ballpark transform from EPSG:4326 to EPSG:26913`

**Comment by nyalldawson** [comment]
This report cannot be acted on -- we need a reproducible test case in order to proceed further.
