### ISSUE TITLE
The same image added to the "Layers" table becomes either a collapsed layer or an expanded layer. 

### ISSUE THREAD

**Issue by MrChebur** [qgis/QGIS#42596]
**Describe the bug**
The same image added to the "Layers" table becomes either a collapsed layer or an expanded layer. 
The odd numbers are collapsed and the even numbers are expanded.

**How to Reproduce**

1. Add any images to the project.

**Expected result: all raster layers must be collapsed (not expanded).**

![FYMYoM5zJw](https://user-images.githubusercontent.com/20655102/113131627-e272dd80-9236-11eb-8145-a57f268628bc.gif)

**QGIS and OS versions**

QGIS version
3.18.1-Zürich
QGIS code revision
202f1bf7e5
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
AppendFeaturesToLayer; 
DigitizingTools; 
FreehandRasterGeoreferencer; 
Go2NextFeature3; 
latlontools; 
mapswipetool_plugin; 
minimum_spanning_tree; 
qgis_gee_data_catalog; 
qgsAzimuth; 
db_manager; 
MetaSearch; 
processing

**Comment by jfbourdon** [comment]
I would add that the issue isn't present in QGIS 3.16.9.

**Comment by MrChebur** [comment]
Quick fix for `startup.py` located in the `C:\Users\USERNAME\AppData\Roaming\QGIS\QGIS3`


import qgis

```

def collapse_raster_layers(layers: list):
    root = qgis.core.QgsProject.instance().layerTreeRoot()
    for layer in layers:
        if isinstance(layer, qgis.core.QgsRasterLayer):
            layer_node = root.findLayer(layer.id())
            if layer_node is not None:
                if layer_node.isExpanded():
                    layer_node.setExpanded(False)


qgis.core.QgsProject.instance().legendLayersAdded.connect(collapse_raster_layers)
```

**Comment by jfbourdon** [comment]
Nice! However I try to avoid using the %APPDATA% directory (I store my profiles elsewhere) and if I put `startup.py` in the same directory where my `profiles` directory is located, the file isn't read. Do you know which environment variable needs to be changed in order to allow QGIS to find the file? I tried setting the `%APPDATA%` in `qgis.bat`/`qgis-ltr.bat` but it didn't work.

**Comment by alexbruy** [comment]
Can't reproduce with the latest master (2c8e784625) on Linux.

**Comment by MrChebur** [comment]
Can't reproduce with 3.32.3-Lima.
QGIS code revision 67d46100b5

**Comment by jfbourdon** [comment]
Still present in 3.28.11 but since this LTR will be replaced in 5 months, I guess there is no point trying to fix this minor issue.
