### ISSUE TITLE
Crash accessing QgsMultiLineString object using PyQGIS

### ISSUE THREAD

**Issue by tombrennan06** [qgis/QGIS#42612]
This may be the same issue as #41612, but I've distilled it to a very simple use case, so hopefully it is easier to trace.

In PyQGIS, I am trying to load and then do subsequent operations on a MultiLineString geometry. When I try to access the geometry, QGIS crashes reliably.

I've attached a Geopackage with just about the simplest MultiLineString possible ((0 0, 1 1)), and the following Python script which causes the crash:

```
layer = qgis.utils.iface.mapCanvas().layer(0)
feature = layer.getFeature(1)
mls1 = feature.geometry().get()
mls1
```

If I create the MultiLineString manually within PyQGIS (similar to #41612), there is no crash. The crash only seems to occur if the layer is loaded from an external source. Eg the following Python script run via the Python Console creates an identical MultiLineString, and works without crashing:

```
lines = [[[0,0],[1,1]]]
mls = QgsMultiLineString()
for i in [QgsLineString([QgsPoint(x,y) for x,y in i]) for i in lines]:
    _ = mls.addGeometry(i)

old_geometry = QgsGeometry(mls)
mls1 = old_geometry.get()
mls1
```

**Steps to reproduce crash:**
* load attached Geopackage to QGIS - _simple_vector.gpkg_ (simple 1 segment MultiLineString)
* run attached Python script via the Python Console - _crash_loaded_multilinestring.py_

**Attachments in zip file are as follows:**
[attachments.zip](https://github.com/qgis/QGIS/files/6243202/attachments.zip)
* Geopackage: _simple_vector.gpkg_
* Script that causes crash: _crash_loaded_multilinestring.py_
* Script that creates same MultiLineString and does not crash: _nocrash_manual_multilinestring.py_

**QGIS and OS versions**

QGIS version | 3.12.1-București | QGIS code revision | 121cc00ff0
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Windows 10 (10.0)
Active python plugins | processing_wbt; qgis_resource_sharing; QuickOSM; db_manager; MetaSearch; processing

**Stack trace: (this is from Windows 10/QGIS 3.12, but I have replicated the bug on a different Windows 10 machine with a clean install of QGIS 3.18)**

Crash ID: 28f12c4ed0dfaca0a0d0199faadff3fc26701427

Stack Trace

PyInit__core :
PyObject_Repr :
PyFile_WriteObject :
PySys_GetSizeOf :
PyMethodDef_RawFastCallDict :
PyObject_FastCallDict :
PyObject_CallFunctionObjArgs :
PyErr_NoMemory :
PyEval_EvalCodeWithName :
PyImport_Import :
PyImport_Import :
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_sip :
PyInit_Qsci :
QWidget::event :
QFrame::event :
QAbstractScrollArea::event :
PyInit_Qsci :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processKeyEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.12.1-Bucure?ti
QGIS code revision: 121cc00ff0
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

**Comment by gioman** [comment]
> 3.12.1-București

@tombrennan06 3.12 is EOL and unsupported, you must try on the latest 3.16 or 3.18

**Comment by tombrennan06** [comment]
Here is the version info and stack trace from a different machine running 3.18

**Version Info**
QGIS version
3.18.1-Zürich
QGIS code revision
202f1bf7e5
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
db_manager; 
MetaSearch; 
processing

**Stack Trace**

Crash ID: 29cba6091f09b7cd5824b0a72dafffc0f782335c


Stack Trace


slot_QgsMultiLineString___repr__ qgsmultilinestring.sip:84
PyObject_Repr :
PyFile_WriteObject :
PySys_GetSizeOf :
PyMethodDef_RawFastCallDict :
PyObject_FastCallDict :
PyObject_CallFunctionObjArgs :
PyErr_NoMemory :
PyEval_EvalCodeWithName :
PyImport_Import :
PyImport_Import :
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_sip :
sipVH__gui_95 sip_guipart0.cpp:8795
sipQgsCodeEditorPython::keyPressEvent sip_guipart4.cpp:153324
QWidget::event :
QFrame::event :
QAbstractScrollArea::event :
sipQgsCodeEditorPython::event sip_guipart4.cpp:153537
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:475
QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:475
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processKeyEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1638
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.18.1-Zürich
QGIS code revision: 202f1bf7e5
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

**Comment by nyalldawson** [comment]
There's a bug in your code. Try:

```
layer = qgis.utils.iface.mapCanvas().layer(0)
feature = layer.getFeature(1)
# clone the geometry, otherwise the reference points to an invalid location after python garbage collects "feature.geometry()"
mls1 = feature.geometry().get().clone()
mls1
```

OR

```
layer = qgis.utils.iface.mapCanvas().layer(0)
feature = layer.getFeature(1)
geometry = feature.geometry()
mls1 = geometry.get()
mls1
```

**Comment by tombrennan06** [comment]
Thanks @nyalldawson - the second approach above works great. [The first one results in an empty variable(?)]
