### ISSUE TITLE
QGIS crashed when creating a new geopackage

### ISSUE THREAD

**Issue by eroldan01** [qgis/QGIS#42628]
Was saving creating a new Geopackage in portable SSD. 

## Report Details

**Crash ID**: [f7bff7071a0b6032d0a75fc5ec31072a3b7be898](https://github.com/qgis/QGIS/search?q=f7bff7071a0b6032d0a75fc5ec31072a3b7be898&type=Issues)

**Stack Trace**
<pre>
memcpy_repmovs memcpy.asm:114
VSICreateCachedFile :
GDALGeorefPamDataset::GetSpatialRef :
GDALGeorefPamDataset::GetSpatialRef :
GDALGeorefPamDataset::GetSpatialRef :
GDALRegister_GTiff :
GDALRegister_GTiff :
GDALRegister_GTiff :
GDALRasterBand::GetLockedBlockRef :
GDALRasterBand::IRasterIO :
GDALRegister_GTiff :
GDALRasterBand::RasterIO :
QgsGdalProviderBase::gdalRasterIO qgsgdalproviderbase.cpp:316
QgsGdalProvider::readBlock qgsgdalprovider.cpp:1177
QgsGdalProvider::block qgsgdalprovider.cpp:685
QgsMultiBandColorRenderer::block qgsmultibandcolorrenderer.cpp:190
QgsBrightnessContrastFilter::block qgsbrightnesscontrastfilter.cpp:119
QgsHueSaturationFilter::block qgshuesaturationfilter.cpp:123
QgsRasterResampleFilter::block qgsrasterresamplefilter.cpp:124
QgsRasterProjector::block qgsrasterprojector.cpp:815
QgsRasterIterator::readNextRasterPartInternal qgsrasteriterator.cpp:130
QgsRasterDrawer::draw qgsrasterdrawer.cpp:60
QgsRasterLayerRenderer::render qgsrasterlayerrenderer.cpp:328
QgsMapRendererCustomPainterJob::doRender qgsmaprenderercustompainterjob.cpp:317
QgsMapRendererCustomPainterJob::staticRender qgsmaprenderercustompainterjob.cpp:267
QtConcurrent::RunFunctionTask<void>::run qtconcurrentrunbase.h:136
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.18.1-Z�rich
QGIS code revision: 202f1bf7e5
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

**Comment by gioman** [comment]
> Was saving creating a new Geopackage in portable SSD.

@eroldan01 can you please add detailed steps to replicate? If the problem is data dependent also attach sample data.

**Comment by roya0045** [comment]
Seems like a local issue, possibly lack of space as you're trying to import a tiff in a geopackage. The title doesn't mention tiff/raster geocpackage export.
