### ISSUE TITLE
Impossible to create a arc-line polygon in QGIS 3.16

### ISSUE THREAD

**Issue by sigmoe** [qgis/QGIS#42626]
**Describe the bug**
In QGIS 3.16.5, when creating a new polygonal object, it's impossible to draw a polygon with an arc, a line, an arc and a line.
This is a regression, because we could do that in QGIS 3.10.9

**How to Reproduce**
See my video attached to reproduce the same manipulations

**QGIS and OS versions**
Version de QGIS
3.16.5-Hannover
Révision du code
58ba7c1ed6
Compilé avec Qt
5.11.2
Utilisant Qt
5.11.2
Compilé avec GDAL/OGR
3.1.4
Utilisé avec GDAL/OGR
3.1.4
Compilé avec GEOS
3.8.1-CAPI-1.13.3
Utilisé avec GEOS
3.8.1-CAPI-1.13.3
Compilé avec SQLite
3.29.0
Fonctionne avec SQLite
3.29.0
Version du client PostgreSQL
11.5
Version de SpatiaLite
4.3.0
Version de QWT
6.1.3
Version de QScintilla2
2.10.8
Compilé avec PROJ
6.3.2
Fonctionne avec PROJ
Rel. 6.3.2, May 1st, 2020
Version de l'OS
Windows 10 (10.0)
Extensions Python actives
cadastre; 
localiserparcelle; 
SgmDxfImportPro; 
StreetView; 
db_manager; 
processing

**Additional context**
No problem in QGIS 3.10, the problem appears in QGIS 3.16

https://user-images.githubusercontent.com/55922863/113422839-ade55a00-93cd-11eb-8c7c-16b72bcad957.mp4

**Comment by vcloarec** [comment]
hmm, I don't know where it come from, but you can used the new digitizing curve tool:

![curves](https://user-images.githubusercontent.com/7416892/113530742-c18eed00-9594-11eb-9f44-fef3caefc23c.gif)

I think it could work better than before.

**Comment by nyalldawson** [comment]
@vcloarec we should remove the broken tool in my opinion

**Comment by vcloarec** [comment]
but kipping "Add circular string by radius" ? The new one can't do that for now...

**Comment by simogeo** [comment]
@sigmoe != @simogeo but thanks for letting me know about the new feature :-)

**Comment by sigmoe** [comment]
Ok thank your the trick with the new feature

**Comment by sigmoe** [comment]
@vcloarec Just one remark about the new digitizing curve tool: there are too many keys for the keyboard shortcut. Why not use just one keyboard key, C for example, like T for tracing or S for snapping ?

**Comment by vcloarec** [comment]
@sigmoe 
You can change the shortcut in settings if you want.

**Comment by sigmoe** [comment]
@vcloarec I knew for the shortcut modification, but it was just a suggestion for the default shortcut.
