### ISSUE TITLE
"QGIS Unexpectedly Ended"

### ISSUE THREAD

**Issue by tsmcgrath** [qgis/QGIS#42621]
Copied report:
## User Feedback

Just panning and zooming around with two layers on the map. The OSM default plus a polygon geometry of US Wilderness areas. Specifically zoomed into Rock Creek Wilderness on the Oregon Coast.

## Report Details

**Crash ID**: [8b5b7babe92e243e37d2cc03b8967801fbc1e592](https://github.com/qgis/QGIS/search?q=8b5b7babe92e243e37d2cc03b8967801fbc1e592&type=Issues)

**Stack Trace**
<pre>
operator<< :
QNetworkDiskCache::insert :
QgsNetworkAccessManager::unlockAfterSslErrorHandled :
QSslKey::operator!= :
QSslKey::operator!= :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
QEventLoop::exec :
CPLStringList::PartialFindString :
CPLStringList::empty :
QgsRasterDataProvider::block :
QgsSingleBandColorDataRenderer::block :
QgsBrightnessContrastFilter::block :
QgsHueSaturationFilter::block :
QgsRasterResampleFilter::block :
QgsRasterProjector::block :
QgsRasterIterator::readNextRasterPartInternal :
QgsRasterDrawer::draw :
QgsRasterLayerRenderer::render :
QgsMapRendererParallelJob::renderLayerStatic :
QgsMapRendererParallelJob::renderingFinished :
QgsImageOperation::overlayColor :
QgsImageOperation::flipImage :
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.16.3-Hannover
QGIS code revision: 94ac9f21b8
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

**Comment by gioman** [comment]
@tsmcgrath please try with a new QGIS profile, no 3rd party plugins installed.
