### ISSUE TITLE
QGIS crashes when saving project after script execution

### ISSUE THREAD

**Issue by wmeinolf** [qgis/QGIS#42651]
## User Feedback

Reproducable Crash once Script has been executes once.and project shall be saved.
Attached scripts deletes layers and reloades them from GPKG

How to reproduce:
Load Project 210404 Meinotest.qgs
Execute Script
Press Save Project button.

[temp.zip](https://github.com/qgis/QGIS/files/6254666/temp.zip)

## Report Details

**Crash ID**: [2da58aef0f995baef6133b8f01c3a726eb06f654](https://github.com/qgis/QGIS/search?q=2da58aef0f995baef6133b8f01c3a726eb06f654&type=Issues)

**Stack Trace**
<pre>
QBitArray::QBitArray :
QgsMemoryProvider::subsetString qgsmemoryprovider.cpp:683
QgsSnappingConfig::writeProject qgssnappingconfig.cpp:540
QgsProject::writeProjectFile qgsproject.cpp:2301
QgsProject::write qgsproject.cpp:2199
QgisApp::fileSave qgisapp.cpp:7286
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:475
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:475
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1638
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.18.1-Z�rich
QGIS code revision: 202f1bf7e5
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

**Comment by roya0045** [comment]
So your script breaks the project and causes crash when saving? Also that's a lot of duplicate code, you could easily remove 60 to 80% of your script by just iterating.

**Comment by wmeinolf** [comment]
True, however also with duplicate code it should not crash. It also does not crash after script execution. It crash, when save button is clicked.

**Comment by gioman** [comment]
@wmeinolf on QGIS master/Ubuntu 20.04 it crashes when running the script, however you should first ask in the developers mailing list of your script is correct, as you can always end up crashing QGIS if misusing its API.

**Comment by roya0045** [comment]
The script removes layers but they are somewhat still in the project. Then when saving the project the lingering layers now have invalid parameters and that causes the crash. Now either some cleanup step is missing or the removal doesn't work. I recall this was reported also if I recall.

**Comment by wmeinolf** [comment]
The script shall remove some existing layers and reload them with different layername. I split the script im (1) removing layers and (2) reloading layers. Following result:
(a) Start QGIS and run (1) deletes the layers, Project can be saved w/o crash. Exit QGIS normally.
(b) Start QGIS again (Layers gone, as deletet in previous step) and run (2). Layers are loaded, Project can be saved w/o crash. Exit QGIS normally. After reloading the reloaded layers ate perfectly available.

Next Test:
(c) Start QGIS and run (1) deletes the layers, Project can be saved w/o crash. Then run (2) without exiting and restarting QGIS. Layers are loaded, however when save is clickes, QGIS freeze and crash.

So @roya0045 comment, that removed layers are somewhat still in the project may be valid. Can you provide a hint, how I can "cleanup" / tidy the project between removing and reloading the layers?

The hardcoede winsows path is for layerstyle. Loading layerstyle can deleted, as it is not relevant for the crash.

Thanks for your support.

**Comment by jgrocha** [comment]
Debugging the script is out of scope of QGIS issues. If there is a problem in QGIS, you need to isolate it and make it replicable with the minimal code possible. IMHO this issue should be closed as it is, but please open it again, if you are able to find an issue in QGIS.

**Comment by wmeinolf** [comment]
I changed the logic of my script today to avoid deleting and reloading layers from same Geopackage in one shot. As I'm still convinced, that it's a bug, I'll work shortterm on a simple scenario to reproduce the crash and open new case as @jgrocha proposed.

**Comment by jgrocha** [comment]
> I changed the logic of my script today to avoid deleting and reloading layers from same Geopackage in one shot. As I'm still convinced, that it's a bug, I'll work shortterm on a simple scenario to reproduce the crash and open new case as @jgrocha proposed.

@wmeinolf Sorry for asking you to do so, but it helps a lot the developers. Thank you for your cooperation.
