### ISSUE TITLE
message bar is not using the default timeout when pushing a warning

### ISSUE THREAD

**Issue by AndreasRabe** [qgis/QGIS#42661]
**Describe the bug**

When using QgsMessageBar::pushWarning the default timeout is not correctly applied. The warning stays visible and has to be closed manually. 

Can be reproduced in the QGIS Python console:

`>>>iface.messageBar().pushWarning('Warning', 'hello world')`

![image](https://user-images.githubusercontent.com/45030715/113599600-2272ff80-963f-11eb-830c-dcfb5f912944.png)

**QGIS and OS versions**

QGIS version
3.18.1-Zürich
QGIS code branch
Release 3.18
Compiled against Qt
5.12.9
Running against Qt
5.12.9
Compiled against GDAL/OGR
3.2.2
Running against GDAL/OGR
3.2.2
Compiled against GEOS
3.9.1-CAPI-1.14.2
Running against GEOS
3.9.1-CAPI-1.14.2
Compiled against SQLite
3.34.0
Running against SQLite
3.35.2
PostgreSQL Client Version
13.1
SpatiaLite Version
5.0.1
QWT Version
6.1.6
QScintilla2 Version
2.11.2
Compiled against PROJ
8.0.0
Running against PROJ
Rel. 8.0.0, March 1st, 2021
OS Version
Windows 10 (10.0)
Active python plugins
enmap-box; 
rasterdataplotting; 
processing

**Comment by fiddlersfan** [comment]
I can reproduce the behavior in 3.18.1 but not in 3.16.5 (LTR). The responsible function is this one:

https://github.com/qgis/QGIS/blob/b6de378090e35fc362d746ca215d9dbc42e8468e/src/gui/qgsmessagebar.cpp#L215-L233

The changed behavior, if the function is not corrected, should be documented in any case. The description in the documentation is currently not correct: 
https://qgis.org/pyqgis/3.18/gui/QgsMessageBar.html?highlight=pushwarning#qgis.gui.QgsMessageBar.pushWarning

**Comment by nyalldawson** [comment]
@fiddlersfan just to confirm that the changed behaviour IS by design -- warnings and alerts should not be auto-dismissed

**Comment by AndreasRabe** [comment]
Alright, thanks for the clarification.
