### ISSUE TITLE
Possibility to turn grid on/off in layout

### ISSUE THREAD

**Issue by antoniolocandro** [qgis/QGIS#42663]
Usually you may have pre-configured grids in templates but when you open in another extent the scale may be too small and the rendering takes forever of the grid. Also sometimes you may want to hide the grid but not remove it

Basically add a checkbox before the grid name to toggle the visibility on/off

![image](https://user-images.githubusercontent.com/4627073/113606706-985a7500-9605-11eb-8974-095f929e619f.png)

**Comment by fiddlersfan** [comment]
With just one click more you already have this possibilty:

click on "Modify Grid... 

![Screenshot 2021-04-05 200012](https://user-images.githubusercontent.com/18557959/113607526-95817380-9649-11eb-9734-eda80c1fae3d.jpg)

**Comment by antoniolocandro** [comment]
Well sure, but that's an extra click and yes I missed it initially. 

From an user friendly perspective it would be nice if the toggle on/off would be visible in the first panel directly. I can have 3-4 grids in the same map enabled for different reasons and that would be easier to do than click on modify to access the setting

**Comment by antoniolocandro** [comment]
Got this image from a colleague who swears this option was possible in 3.4 , I still believe the tick on/off would be better besides the grid
![image](https://user-images.githubusercontent.com/4627073/114188234-2b492700-9906-11eb-8d5c-c61b3769cd67.png)
