### ISSUE TITLE
QGIS 3.18.1-3 georef still not working on Windows 10 Pro

### ISSUE THREAD

**Issue by cmber** [qgis/QGIS#42665]
I just re-installed QGIS 3.18.1-3.msi on Win 10 and georeferer still hangs and the only option is to kill the process. Any sugestions?

Thanks
CM

**Comment by roya0045** [comment]
Hangs when you hit run?

**Comment by cmber** [comment]
correct, after hitting run it just doesn't do anything. Thought it was related to the progress bar issue mentioned somewhere else here but after waiting for about 4 hours I decided to kill the process.

**Comment by cmber** [comment]
It does work well in QGIS 3.16.4-1

**Comment by roya0045** [comment]
@gioman Gio when you have some extra time, could you do a test on windows? I tried with masted on linux, works fine but I get weird results, I'll try to investigate if there is an issue.

**Comment by gioman** [comment]
> Edit: unrelated issue might be coming from out of range georef.

@roya0045 @cmber tested on Windows 10 pro and QGIS 3.18.1 > no issues here.

**Comment by gioman** [comment]
> but after waiting for about 4 hours

@cmber attach/link the data you are trying to georeference and the GCPs.

**Comment by roya0045** [comment]
Thanks @gioman  this confirms what I was thinking, the install was not clean and may be using broken dll from 3.18 and not 3.18.1.

**Comment by cmber** [comment]
thank you both, @gioman and @roya0045. I does work now. I had to do a clean reinstall as suggested, removing any leftovers in the registry. After does, works perfectly. Thanks again

**Comment by roya0045** [comment]
@cmber glad to know it was a false positive.
