### ISSUE TITLE
Continuous crashes 3.18.1 with Google Terrain Hybrid

### ISSUE THREAD

**Issue by UROwLImP** [qgis/QGIS#42669]
When using XYZ tiles to bring in cover for Fiji from Google Terrain Hybrid dataset, the program crashes within a minute or so of entering the Print Layout composer.

Seems to be ok if I have the Google Terrain Hybrid layer turned off.

Crash ID: 83948bb4810251935d1e7605be6321862d2570d7

Stack Trace

memcpy memcpy.asm:445
QgsWmsProvider::readBlock qgswmsprovider.cpp:1018
QgsRasterDataProvider::block qgsrasterdataprovider.cpp:212
QgsSingleBandColorDataRenderer::block qgssinglebandcolordatarenderer.cpp:62
QgsBrightnessContrastFilter::block qgsbrightnesscontrastfilter.cpp:119
QgsHueSaturationFilter::block qgshuesaturationfilter.cpp:123
QgsRasterResampleFilter::block qgsrasterresamplefilter.cpp:164
QgsRasterProjector::block qgsrasterprojector.cpp:815
QgsRasterIterator::readNextRasterPartInternal qgsrasteriterator.cpp:130
QgsRasterDrawer::draw qgsrasterdrawer.cpp:60
QgsRasterLayerRendererFeedback::onNewData qgsrasterlayerrenderer.cpp:63
QgsWmsProvider::draw qgswmsprovider.cpp:967
QgsWmsProvider::readBlock qgswmsprovider.cpp:997
QgsRasterDataProvider::block qgsrasterdataprovider.cpp:212
QgsSingleBandColorDataRenderer::block qgssinglebandcolordatarenderer.cpp:62
QgsBrightnessContrastFilter::block qgsbrightnesscontrastfilter.cpp:119
QgsHueSaturationFilter::block qgshuesaturationfilter.cpp:123
QgsRasterResampleFilter::block qgsrasterresamplefilter.cpp:164
QgsRasterProjector::block qgsrasterprojector.cpp:815
QgsRasterIterator::readNextRasterPartInternal qgsrasteriterator.cpp:130
QgsRasterDrawer::draw qgsrasterdrawer.cpp:60
QgsRasterLayerRenderer::render qgsrasterlayerrenderer.cpp:328
QgsMapRendererCustomPainterJob::doRender qgsmaprenderercustompainterjob.cpp:317
QgsMapRendererCustomPainterJob::staticRender qgsmaprenderercustompainterjob.cpp:267
QtConcurrent::RunFunctionTask::run qtconcurrentrunbase.h:136
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.18.1-Z�rich
QGIS code revision: 202f1bf7e5
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

**Comment by gioman** [comment]
@UROwLImP please try with a new QGIS profile, if the problem persist add the exact series of steps that lead to the crash, eventually attaching a sample project with data.

**Comment by roya0045** [comment]
You seem to be running out of ressource, local issue unless the composer provide a reliable crash.

**Comment by UROwLImP** [comment]
Thank you all. Running on a higher spec machine with more resources has resolved

**Comment by roya0045** [comment]
@UROwLImP Glad to hear this was indeed the case.
