### ISSUE TITLE
“QGIS” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by IngeKu** [qgis/QGIS#42662]
I have tried to download QGIS on my Macbook and for

1. Download for MacOS
2. Latest release (richest on features) 3.18 AND 
Long term release (most stable) 3.16

Once installed I want to open and receive message: “QGIS” can’t be opened because Apple cannot check it for malicious software.

**Comment by gioman** [comment]
@IngeKu go in macOS security panel and allow the application to run. There are many other tickets about this.
