### ISSUE TITLE
Point Pattern Fill - "Bad Allocation" with Meters at Scale

### ISSUE THREAD

**Issue by aydin-gis** [qgis/QGIS#42668]
Bad allocation error message when using the point pattern fill with a marker set to Meters At Scale.
have tested on two machines, 3.16 and 3.18.1.

Steps to reproduce:
New project, on a new user profile.
New scratch layer, polygon.  
Layer styling, set to the pattern dot default , for example, Pattern Dot Black.
Navigate to Point Pattern Fill, and change the default Millimetres to "Meters at Scale".

**Comment by roya0045** [comment]
Confirmed on master on linux.

**Comment by aydin-gis** [comment]
Can I use Map Units as a work around?
I'm using EPSG:2193, which I believe is based on meters...
Have not been able to find much documentation on this for symbology in QGIS.
