### ISSUE TITLE
print layouts improvements

### ISSUE THREAD

**Issue by EllieLa** [qgis/QGIS#42673]
Hi everyone,
I would like to report a couple of improvements I thought about with my colleagues. I don't know if many others asked for this, but we would **LOVE** to be able to insert some italic words in the legends of the layouts, we know it's possible to have all the legend in italic but we haven't been able to use it only with some words (we tried html but it doesn't work).
Also, we've found it a little difficult to work with multiple pages layouts, the main issue is the layers' stucture, it would be awesome to have some sort of layer tree or groups in order to make it easier to find all the objects of the page.
One last thing, when you drag the viewport's corner into the layout QGIS automatically scales the viewport, it would be amazing if there was an option for modifying the viewport's size without scaling what's inside.

Thank you very much for your attention

**Comment by gioman** [comment]
@EllieLa Hi, please 1 feature request/bug per ticket. Also if your organization needs this improvements you can consider funding the necessary work to implement them.
