### ISSUE TITLE
Changing the order of rendering of symbol layers in "symbol levels" causes QGIS to crash when saving a symbol

### ISSUE THREAD

**Issue by IngMonardiLuca** [qgis/QGIS#42671]
## User Feedback

I was saving a new symbol for a better rendering of sterets on a map

## Report Details

**Crash ID**: [7cd20fb20c733abc26bc897c9837b66adf099cca](https://github.com/qgis/QGIS/search?q=7cd20fb20c733abc26bc897c9837b66adf099cca&type=Issues)

**Stack Trace**
<pre>
QgsSymbolsListWidget::saveSymbol qgssymbolslistwidget.cpp:221
QMetaObject::activate :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
</pre>

**QGIS Info**
QGIS Version: 3.16.5-Hannover
QGIS code revision: 58ba7c1ed6
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

**Comment by gioman** [comment]
@IngMonardiLuca please try with a new QGIS profile, if the problem persist add the exact series of steps that lead to the crash, eventually attaching a sample project with data.

**Comment by IngMonardiLuca** [comment]
I was using the 3.16 version with GRASS.  By changing version (3.16 Hannover LTR) the problem disappeared,

**Comment by IngMonardiLuca** [comment]
Thank you for your fast reply

**Comment by gioman** [comment]
> I was using the 3.16 version with GRASS. By changing version (3.16 Hannover LTR) the problem disappeared,

@IngMonardiLuca this means that if launch QGIS using the "with GRASS" shortcut you can replicate this bug, while if you use the "normal" shortcut it works ok?

**Comment by IngMonardiLuca** [comment]
I have just newly tried, but it works with GRASS as well. I do not know why!?!?!?
This morning, when I saved a new symbol, I wanted to add it also as favorite. Maybe it was this action which caused the "crash"?

**Comment by IngMonardiLuca** [comment]
This morning I tried two times, and for two times I was "thrown out" by QGIS...

**Comment by gioman** [comment]
@IngMonardiLuca describe the **detailed** series of steps that lead to the crash, eventually attaching a sample project with data.

**Comment by IngMonardiLuca** [comment]
I copied and attached the bug report, for I thought was enough. 
All i can do is attaching the file where the problem arose and write a little description about how the problem arise.
Open the roads layer and activate symbology. Amongst all favourite symbols there is one called "strade bordate".
If I want to add a new line in central position (starting from "strade bordate"), when I save the new symbol, after assigning it a new name, the computer does not work anymore and then crashes.
[GEOPACKAGE.zip](https://github.com/qgis/QGIS/files/6264858/GEOPACKAGE.zip)

**Comment by IngMonardiLuca** [comment]
Hi Giovanni
No "strada bordate" is a new custom symbol I created during my daily exercise session. I downloaded QGIS last week and I am doing exercises using the on-line training manual.
I was trying to create several symbols to represent streets on a map in different ways.
So, first, I created a test-symbol named "strada bordate" (and saving it as favourite) and then, second, I modified it by adding a new line to create another test-symbolo named "strade importanti" (and still saving it as favourite). But during this second operation, I could not be able to save: the computer was stopped and then crashed.
What is a QGIS profile? Do I have to uninstall and install again the software? I used both the 3.16 HANNOVER release and the same one, but with GRASS installed. I noticed that the problem arose with the second version (with GRASS).
I'll attach the project file and the resources I used to built the map, I also added some screenshots from my computer. Now, you should have all you need to realise the strange behaviour I noticed.

[BUG.zip](https://github.com/qgis/QGIS/files/6265986/BUG.zip)

**Comment by gioman** [comment]
> What is a QGIS profile?

@IngMonardiLuca settings > user profiles > new profile



> Do I have to uninstall and install again the software?

no



> Now, you should have all you need to realise the strange behaviour I noticed.

no, if the symbol is a custom one you must attach it too. You can export it from QGIS style manager.

Anyway please first try with a new QGIS profile.

**Comment by IngMonardiLuca** [comment]
Hi Giovanni
I recorded a video where you can see what I do.
https://youtu.be/1jPaBZg7ovg
I have the crash also after the creation of a new profile

**Comment by IngMonardiLuca** [comment]
Hi Giovanni
Another strange behaviour.
In the attached file you find the XML file for the new symbol just created.
I add a video where you can see what happened and what I did.

https://youtu.be/6_oFyHWR6D8

[BUG.zip](https://github.com/qgis/QGIS/files/6267695/BUG.zip)

**Comment by gioman** [comment]
@IngMonardiLuca I have been able to replicate the crash on both Linux and Windows, on QGIS >= 3.16 including master.

What does triggers the crash when saving the symbol is some change in the order of rendering of a symbol layers in the "symbol levels" dialog.

**Comment by IngMonardiLuca** [comment]
I am glad to have been helpfull. I hope this problem could be fixed.
