### ISSUE TITLE
An Update needed on Raster>Polygonize

### ISSUE THREAD

**Issue by ungvarizs** [qgis/QGIS#42680]
**This function creates polygon from raster pixels with attribute. 
I used it to vectorize a geotiff picture, with two pixel values 0 and 1. I kept only the polygon with attribute value 1.
**The problem is, the result contains invalid geometries. This should be corrected, that the result have to be correct geometrically. **

Detailed description of my work.
I have an SRTM model for an hilly area (in geotiff). With the raster calculator I make the following expression srtm@1<200   
Result is another geotiff with pixel values 0 (for areas with are higher than 200m) and 1 (for areas which are lower than 200 m). I called the function Polygonize. Result a vector type file format (e.g.Shapefile), with an  attribute field, which value are inherited from the raster. 
I deleted the 0, and kept the 1.  I want further vector geoprocessing (e.g. Clip), but I can not, because this result shapefile may contains several invalid geometries: closed stroke line, or the ring touches the stroke (see on the picture below).

Okay, I have found an alternative way to solve this problem (Contour polygons in Processing tools), but I think the result of the Polyonize have to produce correct geometry. 

Another idea to develop the topology checker: If I queried the invalid geometries of a big polygon object (more than 5000 vertices), it is hard to find the invalid vertices. Sometimes I can see the green cross (invalid vertex),sometimes not. It would  be useful to have a button, which zoom on the invalid vertices one by one. (not only the invalid object).
Here are my test files.
[vas.zip](https://github.com/qgis/QGIS/files/6265952/vas.zip)
)

![image](https://user-images.githubusercontent.com/82045669/113735421-87d8f600-96fc-11eb-955d-e58d473cc2e6.png)

 **

**Additional context**

**Comment by roya0045** [comment]
You can use the fix geometries tool, that would be a good cleanup step.

Though I'm not sure what is the intent of this ticket.

**Comment by ungvarizs** [comment]
Thanks for the tip. fix geometry worked. But some questions I came up:
why is it not implemented into the polygonize? 
why do I got wrong (~invalid) geometry? 
Why have to run another processes to get a geometrically valid result? 
Or  a warning would be enough in somewhere in the Polygonize menu: "You may use fix geometry to get valid geometry output" or something like this. 
**If I redefine the problem, than the vector menu is very good explained in the right side of each submenu, but the raster menu is very incompleted or poorly explained.**  I Hope, in the future we can read some description of the processes directly in the QGIS, not only in the Documentation. :)
 
Another thing Fix geometry tool could be placed in the Vector-> geometry tools. There is only the "Check validity".

Thanks,

**Comment by gioman** [comment]
@ungvarizs the tool you mention is a wrapper around

https://gdal.org/programs/gdal_polygonize.html#gdal-polygonize

if this tool creates wrong geometries you must report the problem to the GDAL project, not here.


You may want to try the "raster pixels to polygon" tool, which is a QGIS native one.

You have also the opportunity to try r.to.vect (GRASS) and "vectorizing grid classes" (SAGA), all of them are in the QGIS Processing toolbox.



> Another thing Fix geometry tool could be placed in the Vector-> geometry tools. There is only the "Check validity".

The "vector" and "raster" menus were only kept to not put off users that are used to them, ultimately they will be removed as **all** geoprocessing tools are anyway in the right place, the Processing toolbox.



> **If I redefine the problem, than the vector menu is very good explained in the right side of each submenu, but the raster menu is very incompleted or poorly explained.**

See above.
