### ISSUE TITLE
QGIS hangs loading pointcloud dataset when it has no SRS defined

### ISSUE THREAD

**Issue by JeltoBuurman** [qgis/QGIS#42696]
Hallo,

I'm Using QGIS 3.18.1  
QGIS-Codeversion: 202f1bf7e5

Since 3.18.1 I can open big Pointclouds form ept. Now I try to generate a big Pointcloud >1.000.000 Points with entwine direct and QGIS hangs when I open the ept.json. When I build a subset with ca 500.000 Point the same happens. The Pointcoud from entwine.io "red rocks" can be opened in QGIS. The amount of data is very big. If wanted, please tell me where i can upload them.

Regards

Jelto Buurman

**Comment by gioman** [comment]
> The amount of data is very big. If wanted, please tell me where i can upload them.

@JeltoBuurman you can't upload it here, use something like Google Drive, Dropbox, etc and then link the dataset here.

**Comment by JeltoBuurman** [comment]
> > The amount of data is very big. If wanted, please tell me where i can upload them.
> 
> @JeltoBuurman you can't upload it here, use something like Google Drive, Dropbox, etc and then link the dataset here.

Hallo, is it possible to transfer the data, withount making them public?

**Comment by gioman** [comment]
> withount making them public

@JeltoBuurman you can surely make private a download on google drive or dropbox. Let's see if some dev is available to see the dataset (so you can give him/her access to it privately).

**Comment by JeltoBuurman** [comment]
Hallo, I found a  reason for the issue: 
My LAZ files have no srs included, so I added it while the build with entwine with:
{
    "input": "inputdir",
   
    "reprojection": {
        "in": "EPSG:25832",
        "out": "EPSG:25832" },
   
    "output": "outputdir"
}
The resulting structure could be converted by entwine  and pdal to tif, but not be read by QGIS (hangs). If I add the SRS to to laz data befor building the ept structure, then everything works.

**Comment by wonder-sk** [comment]
Could you please share your file with me to try it out? If you can't share the dataset publicly, please share it privately with me: martin dot dobias at lutraconsulting dot co dot uk

**Comment by JeltoBuurman** [comment]
Hallo Martin,

 

I generated a zip file and put it to

 

www.norbit.de/~jelto/LAZ <http://www.norbit.de/~jelto/LAZ> 

 

The file is laz.zip. It contains the LAZ files, my ept structure and some json files. Please keep the data privat by your own.

 

Regards

 

Jelto Buurman

 

 

 

Von: Martin Dobias ***@***.***> 
Gesendet: Dienstag, 4. Mai 2021 16:04
An: qgis/QGIS ***@***.***>
Cc: JeltoBuurman ***@***.***>; Mention ***@***.***>
Betreff: Re: [qgis/QGIS] QGIS hangs loading pointcloud dataset when it has no SRS defined (#42696)

 

Could you please share your file with me to try it out? If you can't share the dataset publicly, please share it privately with me: martin dot dobias at lutraconsulting dot co dot uk
