### ISSUE TITLE
Form view shows wrong image attachments when scrolling through features

### ISSUE THREAD

**Issue by generic-user-name-1** [qgis/QGIS#42705]
**Describe the bug**

When scrolling through features in form view sometimes it shows the wrong image attachments if there is no entry in the column instead of no image. I have attached a project where you can reproduce the problem. 
**How to Reproduce**

1. Open the attached project
2. Open attribute table of point layer 
3. Switch to form view
4. Click several times on "navigate to next feature" or previous feature

[sample project.zip](https://github.com/qgis/QGIS/files/6273036/sample.project.zip)

https://user-images.githubusercontent.com/82109492/113899445-1ddc5180-97cd-11eb-8569-e84bb237ea4c.mp4

**QGIS and OS versions**

QGIS Version 3.16.5, new profile, no plugins installed, tested both on Windows 10 and Mac.

QGIS version | 3.16.5-Hannover | QGIS code revision | 58ba7c1ed6
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | db_manager; MetaSearch; processing

**Additional context**

**Comment by troopa81** [comment]
Fixed by #43144
