### ISSUE TITLE
Compile issues trying to install QGIzs 3.16.3 in RHEL8

### ISSUE THREAD

**Issue by LeahOnuoha** [qgis/QGIS#42700]
Trying to install QGIS in a RHEL8 server environment. Ran into compiling issues we haven't been able to resolve:

 Error: Unable to find a match: qt5-qttools-static python3-qt5-devel python3-qscintilla-devel
spatialindex-devel python3-OWSLib qwt-devel sip-devel exiv2-devel
 sudo dnf install qt5-qtbase-private-devel qt5-qtwebkit-devel qt5-qtlocation-devel qt5-qttools-
static qca-qt5-devel qca-qt5-ossl qt5-qt3d-devel python3-qt5-devel python3-qscintilla-qt5-devel
qscintilla-qt5-devel python3-qscintilla-devel python3-qscintilla-qt5 clang flex bison geos-devel
gdal-devel sqlite-devel libspatialite-devel qt5-qtsvg-devel spatialindex-devel expat-devel proj-
devel qwt-qt5-devel gsl-devel postgresql-devel cmake python3-future gdal-python3 python3-
psycopg2 python3-PyYAML python3-pygments python3-jinja2 python3-OWSLib qca-qt5-ossl
qwt-qt5-devel qtkeychain-qt5-devel qwt-devel sip-devel libzip-devel exiv2-devel

- The qt5-qtbase-devel-5.12.5-6.el8.x86_64 version on my RHEL8

- RHEL8 version info:
Static hostname: localhost.localdomain
Icon name: computer-vm
Chassis: vm
Machine ID: b2d969da04fa4d5aa26abc44e0147384
Boot ID: 346b09363f044a34a3a66dacf67e0c65
Virtualization: oracle
Operating System: Red Hat Enterprise Linux 8.3 (Ootpa)
CPE OS Name: cpe:/o:redhat:enterprise_linux:8.3:GA
Kernel: Linux 4.18.0-240.10.1.el8_3.x86_64
Architecture: x86-64

**Comment by roya0045** [comment]
I fail to see how this is a qgis issue.

**Comment by LeahOnuoha** [comment]
Should we not be able to install QGIS in RHEL8? That is currently limiting federal use of qgis

**Comment by roya0045** [comment]
I thought you were trying to self compile. Does Red Hat even has all the required dependencies available?

**Comment by LeahOnuoha** [comment]
No, not trying to self compile. Redhat seems to be missing the standard C libraries QGIS requires. Looking for help fixing this issue.

**Comment by roya0045** [comment]
Have you tried http://elgis.argeo.org/ ? This seems to be the only installation listed for redhat, not sure if its maintained much.
