### ISSUE TITLE
Wrong max value extracted from tif file on grayscale

### ISSUE THREAD

**Issue by mjohenneken** [qgis/QGIS#42703]
**Describe the bug**

I want to load a GeoTIFF file that has 4 distinct values with a maximum value of 4 but the max value of the grayscale is only 2. I would expect that QGIS shows the whole value range by default.
Setting the value range manually works fine.

**How to Reproduce**

1. Use the provided sample tif file
1. Load tif by doubclicking in the browser
2. Observe that the min and max are 1 and 2. Map only displays 2 values
3. Set max value to 4, observe that more data is in the file that was actually shown when loading it

**QGIS and OS versions**

QGIS-Version
3.16.4-Hannover
QGIS-Codeversion
654e76b3cb
Kompiliert gegen Qt
5.11.2
Laufendes Qt
5.11.2
Kompiliert mit GDAL/OGR
3.1.4
Läuft mit GDAL/OGR
3.1.4
Kompiliert mit GEOS
3.8.1-CAPI-1.13.3
Läuft mit GEOS
3.8.1-CAPI-1.13.3
Kompiliert mit SQLite
3.29.0
Läuft mit SQLite
3.29.0
PostgreSQL-Client-Version
11.5
SpatiaLite-Version
4.3.0
QWT-Version
6.1.3
QScintilla2-Version
2.10.8
Kompiliert mit PROJ
6.3.2
Läuft mit PROJ
Rel. 6.3.2, May 1st, 2020
BS-Version
Windows 10 (10.0)
Aktive Python-Erweiterungen
beePen; 
FreehandRasterGeoreferencer; 
Serval; 
db_manager; 
MetaSearch; 
processing

**Additional context**

I have around 20 other files that were produced by exactly the same script. But the attached file is the only one that shows this behavior. In the Information window of the layer, max=2 is shown: 
![Unbenannt](https://user-images.githubusercontent.com/5088045/113891639-8a535280-97c5-11eb-95c6-3b56c7060754.PNG)

[annotation-20.zip](https://github.com/qgis/QGIS/files/6272721/annotation-20.zip)

**Comment by gioman** [comment]
@mjohenneken this depends on the "accuracy" setting in the raster symbology dialog (under min/max value settings): by default is set to "estimate", and if you change it to "actual" and click "apply" you get the real min and max (that by the way seems to be 8 not 4). And as far as I remember there is no option to change that default (if confirmed is really annoying).

**Comment by mjohenneken** [comment]
Okay, that makes sense. If I use the option actual it will set the correct max value (which is 8 in the example, indeed). 
I'm still a bit puzzled why this estimate only fails in this one example out of 20. 
My current use case is to open up files generated by a python script and inspect whether the file contains a binary mask or multiple values. If the max value is estimated to be 2 a tif with multiple values looks like a binary one. A default would be helpful, but I can live with the current behavior.

**Comment by gioman** [comment]
>  why this estimate only fails in this one example out of 20

@mjohenneken can you spot any difference with gdalinfo?

**Comment by mjohenneken** [comment]
I compared it to the other files and cannot spot a difference. I think one aspect is that the tif files don't have embedded statistics. So, QGIS has to calculate its own values. 

The python script essentially just copies these tif files for another dir. I noticed that in the source dir of the file the is not working is the only of the 20 that has an associated .aux.xml sidecar file. Though, the others don't have the sidecar file and still work fine.
```

dataset_base/
    area-1/ 
        annotation-20.tif  (correct max val, gdalinfo shows stats)
        annotation-20.aux.xml
   other-area/
        annotation-20.tif (correct max val, gdalinfo does not show stats)
   .../
dataset_copied/
    area-1/ 
        annotation-20.tif  (false max val estimate, gdalinfo des not show stats)
   other-area/
        annotation-20.tif (correct max val, gdalinfo does not show stats)
   .../
```

Diff between area-1 and another area in dataset_copied/ folder:
![Unbenannt](https://user-images.githubusercontent.com/5088045/114305206-5d5db300-9ad7-11eb-91aa-aba46928721d.PNG)
