### ISSUE TITLE
Geometry Checker core plugin: it is not possible to set and display the default error resolutions settings

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/QGIS#42710]
**Describe the bug**

The default error resolutions settings for the Geometry Checker core plugin are not correctly displayed and it is not possible to correctly set them in the Set Error Resolutions windows.

![image](https://user-images.githubusercontent.com/16253859/113929541-7cff8d80-97f0-11eb-9587-c9357f42d911.png)

The selected error resolutions options are not properly saved and retained, so it is not possible to properly fix multiple errors with selected resolution methods.

The following screencast shows the incorrect behaviour with QGIS 3.18.1 (the same occurs with QGIS 3.16.5)

https://user-images.githubusercontent.com/16253859/113932566-0d8b9d00-97f4-11eb-919f-da057a836da8.mp4

**How to Reproduce**

1. enable the Geometry Checker core plugin
2. run a geometry check using the Geometry Checker plugin selecting some checks (e.g. Self intersections, Duplicate nodes, ...)
3. in the Geometry Checker plugin "Result" tab click on "Error resolution settings" icon
4. in the "Set Error Resolutions" window select some error resolutions methods (e.g. Self intersection: Split feature into a multi-object feature, Duplicate node: Delete duplicate node) and click on the OK button
5. click on "Error resolution settings" icon in order to open again the "Set Error Resolutions" window
6. the previously selected resolutions methods are not displayed and the "No action" option result incorrectly selected instead.

**QGIS and OS versions**

OS: Windows 7 SP1 64 bit
QGIS 3.16.5 (Qt 5.11.2 - OSGeo4W) - QGIS 3.18.1 (Qt 5.11.2 - OSGeo4W) - QGIS 3.18.1 (Qt 5.15.2 - OSGeo4W testing)

**Additional context**

The following screencast shows the correct behaviour with QGIS 3.10.14 (Qt 5.11.2 - OSGeo4W):

https://user-images.githubusercontent.com/16253859/113932899-3f9cff00-97f4-11eb-934e-53eb4b10d49d.mp4

**Comment by alexbruy** [comment]
Duplicates #42489
