### ISSUE TITLE
If parameter name contains single quote, exported model to python is broken

### ISSUE THREAD

**Issue by nicogodet** [qgis/QGIS#42718]
**Describe the bug**

In french (at least), it's common to use the apostrophe in a parameter name.
Ex : `Tableau d'assemblage`, `Hauteur d'eau`, etc...

In a model, you can set a parameter name with an apostrophe and run the model without issue.
But if you export this model to Python, you can not run the script immediately, you have to convert single-quoted string to double-quoted string when the string contains an apostrophe (or escape the apostrophe).

For example:
![image](https://user-images.githubusercontent.com/39594821/113999816-ae14a800-985a-11eb-97e2-366282443aeb.png)
Number parameter

Converted parameter to python 
```python
self.addParameter(QgsProcessingParameterNumber('Hauteurdeau', 'Hauteur d'eau', type=QgsProcessingParameterNumber.Double, defaultValue=None))
```

It should be double-quoted.
```python
self.addParameter(QgsProcessingParameterNumber('Hauteurdeau', "Hauteur d'eau", type=QgsProcessingParameterNumber.Double, defaultValue=None))
```
https://www.python.org/dev/peps/pep-0008/#string-quotes

Very low level priority, fixing the syntaxe takes few seconds after export.

**How to Reproduce**

1. Create a new model
2. Number input with description = `Hauteur d'eau`
3. Run model (accept the warning) -> OK
4. Export the model to python
5. Run script -> NOK : `SyntaxError: invalid syntax `

**QGIS and OS versions**

3.16.5 and 3.18.1 OSGeo4W Testing
Win10

**Additional context**

**Comment by roya0045** [comment]
This would require adding some logic to escape ' and " in variable names. Though the best option is to use anything other than those.

**Comment by nicogodet** [comment]
I was thinking about...
- if string only contains `'` use double-quoted string
- if string only contains `"` use single-quoted string
- if string contains both, it is probably a complex name and the solution could be to warn the user that he has to fix it before running.

**Comment by roya0045** [comment]
Just escaping them would be fine.

**Comment by nicogodet** [comment]
Yes, it would be but it decreases readability.
I escape them only when I have no choice.
