### ISSUE TITLE
Dockable mirror map

### ISSUE THREAD

**Issue by geemont** [qgis/QGIS#42728]
Can to support the multi-window comparison function similar to the Mapinfo？
Now the function of Add New Map in the QGIS menu can only to show the different part of the same layer. 
I want the function which can show the different layer in the different windows.

**Comment by geemont** [comment]
- [ ] 

- [ ]

**Comment by gioman** [comment]
> I want

@geemont if you want it you may want to consider supporting the work to implement the functionality. Look at "commercial support" in QGIS's web site.

**Comment by roya0045** [comment]
I have no clue what is being requested.

**Comment by roya0045** [comment]
I feel like the overview panel is being requested here, see https://docs.qgis.org/3.16/en/docs/user_manual/introduction/general_tools.html?highlight=overview%20panel#overview-panel

**Comment by baswein** [comment]
@geemont - If I understand your request correctly what you want may already be possible. You can set the second map to follow a layer "Theme" that controls what layers are visible and see them both at once. 
![2021-04-09_13-23-05](https://user-images.githubusercontent.com/15817745/114218058-f1dcdf80-9936-11eb-9ba2-46b392dc2d52.gif)

**Comment by geemont** [comment]
> @geemont - If I understand your request correctly what you want may already be possible. You can set the second map to follow a layer "Theme" that controls what layers are visible and see them both at once.
> ![2021-04-09_13-23-05](https://user-images.githubusercontent.com/15817745/114218058-f1dcdf80-9936-11eb-9ba2-46b392dc2d52.gif)

This is I want, thks

**Comment by gioman** [comment]
> This is I want, thks

@geemont so closing?

**Comment by geemont** [comment]
> > This is I want, thks
> 
> @geemont so closing?

Yes, thks
