### ISSUE TITLE
Allow embbed layers to be selected from projects saved in geopackage / PostgreSQL

### ISSUE THREAD

**Issue by NyakudyaA** [qgis/QGIS#42737]
# Problem

QGIS allows saving projects to
* File system as `.qgs` or `.qgz`
* Geopackage
* PostgreSQL

When trying to embed layers and groups coming from another project on the file-based QGIS projects can be selected. It will be nice if the QGIS projects would be selectable from the two other sources

**Comment by jgrocha** [comment]
I think we need to create a new enhanced `QgsProjectWidget` widget that can be used to open any kind of project (file based or stored on the provider). This could replace the simple `QgsFileWidget` that we use in these dialogues.

In the short time, two buttons could be used to implement this on the GUI side.

![embed from all source](https://user-images.githubusercontent.com/163681/114266710-9ae71100-99ef-11eb-98d7-095d4aa08890.png)

**Comment by alexbruy** [comment]
Duplicates https://github.com/qgis/QGIS/issues/31181
