### ISSUE TITLE
Transparency does not work in Diagrams

### ISSUE THREAD

**Issue by Gusapno** [qgis/QGIS#42742]
Hey there, i have the following issue: while working with diagrams (pie chart) i can't set opacity to 0%.

Actually, the option to set opacity to 0% in diagram options exists:

![image](https://user-images.githubusercontent.com/58537560/114213225-58a6cc80-9928-11eb-9230-7d5f4cfc0f58.png)

although , when the changes are applied nothing happens to the layer. For example, i set two parts of the pie chart in 0% transparency like this:

![image](https://user-images.githubusercontent.com/58537560/114215925-d4eedf00-992b-11eb-8030-94be8aecfc14.png)

When changes are saved (apply and pressing OK) nothing happens and if i open the options again, the colors are back to their original values before setting transparency to 0%

![image](https://user-images.githubusercontent.com/58537560/114216087-0d8eb880-992c-11eb-9918-aac57f1705ba.png)

More info:

- I tested it both in polygon and points layer
- All variables used in the pie chart are "double" type (real decimal number)

To reproduce the issue you can download this example dataset:

[exampledata.zip](https://github.com/qgis/QGIS/files/6287475/exampledata.zip)

1. Go to the point or polygon layer options
2. Select diagrams
3. SelectAttributes
4. Double click the color of some attribute
5. Set opacity to 0%
6. Apply the changes and press OK
7. Open again the layer (it's supposed to show the way the change is ignored).

- I am using QGIS 3.16.5 in Windows 10 version 20H2

**Comment by Pedro-Murteira** [comment]
Still valid on QGIS 3.22.3.

**Comment by alexbruy** [comment]
Fixed in the latest master (096d741fe1).
