### ISSUE TITLE
Loading large (2 * 250Mb) NetCDF point files

### ISSUE THREAD

**Issue by GregCocks-NOAA** [qgis/QGIS#42746]
**Describe the bug**

Loading large (2 * 250Mb) NetCDF point files
**How to Reproduce**

4. See error -->

**QGIS and OS versions**

**Additional context**

## User Feedback

Loading some large NetCDF files

## Report Details

**Crash ID**: [bc69e9c2e14772692dec80f4af6b94849ac57840](https://github.com/qgis/QGIS/search?q=bc69e9c2e14772692dec80f4af6b94849ac57840&type=Issues)

**Stack Trace**
<pre>
H5FL_fac_malloc :
H5SL_less :
H5SL_insert :
H5SL_insert :
H5P_copy_prop_plist :
H5P_create_id :
H5Pcreate :
NC4_get_vara :
NC4_get_vara :
NCDEFAULT_get_vars :
nc_get_var1_float :
GDALRegister_netCDF :
GDALRegister_netCDF :
QgsSqlExpressionCompiler::operator= :
QgsAbstractFeatureIterator::nextFeature :
QgsVectorLayerFeatureIterator::fetchFeature :
QgsAbstractFeatureIterator::nextFeature :
QgsVectorLayerLabelProvider::stopRender :
QgsVectorLayerLabelProvider::stopRender :
QgsMapRendererCustomPainterJob::doRender :
QgsMapRendererCustomPainterJob::staticRender :
QgsMapRendererJob::renderingTime :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.5-A Coru�a
QGIS code revision: 984615fe1e
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

**Comment by roya0045** [comment]
3.10.5 is too outdated. Please try on something recent to validate if the issue is even valid anymore.

**Comment by gioman** [comment]
> 3.10.5 is too outdated. Please try on something recent to validate if the issue is even valid anymore.

@GregCocks-NOAA and if the problem persist with 3.16 or 3.18 please also try with a new QGIS profile. If the problem again please attach/link sample data.

**Comment by rduivenvoorde** [comment]
I do load netcdf files of 1Gb without issues in QGIS (as mesh layer).
It looks like you try to load it as a raster (then it uses GDAL)? Can you confirm?

Can you make the data available somewhere?  Then we can try to reproduce it and see if it is GDAL related or QGIS related.
Note that for loading (more dimensional) netcdf files, the mesh provider is better suited.

And please eliminate the option that this is somehow plugin related (it often is), so please try to open it in a fresh profile without plugins.
Also the data itself can be an issue, did you try to open it in other software?
