### ISSUE TITLE
QGIS do not answer with internet active

### ISSUE THREAD

**Issue by TimDax** [qgis/QGIS#42741]
Hello
All versions of Qgis don't answer when Internet is active.
When I cut internet, it works normally.

Os: W10
Qgis : 3.14, 3,16 and 3.18 tested.

I have test with a new profile
I have install and uninstall Qgis.
I have disable Norton AV, all programs it would be the problem but it's all the time do not answer et then, crash .

I'm blocqued ! 
Thank you for help. If someone know the problem ...
Sorry for my english !

Lily

**Comment by roya0045** [comment]
This is clearly a local issue that we cannot help with. I'd suggest reformatting your system.

**Comment by TimDax** [comment]
Ok thank you
