### ISSUE TITLE
trying to export large NetCDF points to CSV from browser window

### ISSUE THREAD

**Issue by GregCocks-NOAA** [qgis/QGIS#42747]
**Describe the bug**

trying to export large NetCDF points to CSV from browser window

**How to Reproduce**

4. See error -->

**QGIS and OS versions**

**Additional context**

## User Feedback

trying to export lrage NetCDF points file to CSV from browser window

## Report Details

**Crash ID**: [b943d9e161fc5841442f6effdb3fa7195460746d](https://github.com/qgis/QGIS/search?q=b943d9e161fc5841442f6effdb3fa7195460746d&type=Issues)

**Stack Trace**
<pre>
H5CX_set_tag :
H5AC_tag :
H5D__flush_real :
H5D__flush :
H5HP_top :
H5SL_iterate :
H5I_iterate :
H5D_flush_all :
H5F__flush :
H5F__flush_real :
H5F_flush_mounts :
H5F_flush_mounts :
H5F__flush :
H5Fflush :
NC4_sync :
NC4_close :
nc_close :
GDALRegister_netCDF :
GDALRegister_netCDF :
QgsOgrProviderUtils::GDALCloseWrapper :
QgsOgrProviderUtils::releaseInternal :
QgsOgrProviderUtils::release :
QgsOgrProviderUtils::canUseOpenedDatasets :
QgsVirtualLayerDefinition::SourceLayer::~SourceLayer :
QgsConcurrentFileWriterImportTask::`default constructor closure' :
QgsVectorLayer::~QgsVectorLayer :
QgsVectorLayerProperties::`default constructor closure' :
QgsMapToolRegularPolygonCenterCorner::cadCanvasReleaseEvent :
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.5-A Coru�a
QGIS code revision: 984615fe1e
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

**Comment by roya0045** [comment]
Please see my comment on your other ticket.

**Comment by gioman** [comment]
> Please see my comment on your other ticket.

@GregCocks-NOAA and if the problem persist with 3.16 or 3.18 please also try with a new QGIS profile. If the problem again please attach/link sample data.
