### ISSUE TITLE
print layout does not take into account temporal settings

### ISSUE THREAD

**Issue by justinbb** [qgis/QGIS#42743]
Print layout uses the current layer visibility settings of the project window. Thus the expectation is that the map as displayed in the project is what will be used as the basis for printing.

However, if there is a temporal layer and temporal navigation is activated, the temporal settings are *not* used by print layout. Instead, the temporal layer is shown as if temporal navigation were inactive.

This is a regression compared to the Time Manager plugin (since Time Manager used feature filters, its temporal settings automatically passed through to print layout).

Issue detected in QGIS 3.16.5.

**Comment by gioman** [comment]
> This is a regression compared to the Time Manager plugin (since Time Manager used feature filters, its temporal settings automatically passed through to print layout).

@justinbb but Time Manager is/was a 3rd party plugin, so this seems a missing feature rather than a bug.

**Comment by nyalldawson** [comment]
Actually it's already possible -- scroll down to the "temporal" settings in the print layout map item properties and set the desired filter range there. It's possible to set a different range for each map in the layout, and you can data-define the ranges too so they work nicely with atlases :+1:

**Comment by justinbb** [comment]
@nyalldawson  Ah!!! That does indeed cover the issue entirely. :-)

I wonder if it would be reasonable to have an option (on by default) to link this value in the print layout to the settings of the current map display, and to reinitialize it when the "Refresh view" toolbar button is pressed. That would make it "just work" for simple layouts and less experienced users, while still making it possible to uncheck the option and set permanent temporal values for more sophisticated layouts.
