### ISSUE TITLE
Drape (set Z value from mesh) not working

### ISSUE THREAD

**Issue by davidjohnson11** [qgis/QGIS#42755]
**Describe the bug**

The Drape tool under 'Vector geometry' isn't working.  It doesn't change existing Z values nor does it create new Z values from the raster as it is supposed to.  It apparently does nothing.

**How to Reproduce**

Here is how I am running it:

![image](https://user-images.githubusercontent.com/64212883/114286922-1d87c480-9a20-11eb-8456-1162996ee24a.png)

The layer Lines contains line objects, which I believe are supposed to have nodes with X, Y and Z coordinates.

After running this, I am using the info tool to inspect the temporary layer created:

![image](https://user-images.githubusercontent.com/64212883/114286988-91c26800-9a20-11eb-8690-bb8fa9277053.png)

As you can see, the closest vertex Z value that it found was 0.  Not correct value.

**QGIS and OS versions**

QGIS version
3.10.0-A CoruÃ±a
QGIS code revision
6c816b4204
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
2.4.1
Running against GDAL/OGR
2.4.1
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
5.2.0
Running against PROJ
Rel. 5.2.0, September 15th, 2018
OS Version
Windows 10 (10.0)
Active python plugins
CanadianWebServices; 
go2streetview; 
quick_map_services; 
SemiAutomaticClassificationPlugin; 
db_manager; 
processing

**Additional context**

The raster dataset was a Geosoft GXF.  The starting vector dataset was a shapefile containing polygon objects.  I transformed these to line objects to use with Drape.  If someone wants to try debugging with my data, I can send it to them.

**Comment by gioman** [comment]
>  3.10.0-A CoruÃ±a

@davidjohnson11 way too old, you must test in 3.16.5 or 3.18.1

**Comment by davidjohnson11** [comment]
> > 3.10.0-A CoruÃ±a
> 
> @davidjohnson11 way too old, you must test in 3.16.5 or 3.18.1

Just downloaded latest long-term QGIS 3.16.5 and re-ran.  Exactly the same result.

**Comment by gioman** [comment]
> Just downloaded latest long-term QGIS 3.16.5 and re-ran. Exactly the same result.

@davidjohnson11 works fine here (3.18.1 and master on Linux), Please attach sample data.

**Comment by davidjohnson11** [comment]
Here are the files I am working with.  You will need to set the raster CRS to the vector CRS.  Vector is shapefile.  Raster is Geosoft GXF.

[GL200177_DEM_ft AZ_State_Plane_East_NAD27_ft.zip](https://github.com/qgis/QGIS/files/6290957/GL200177_DEM_ft.AZ_State_Plane_East_NAD27_ft.zip)
[CMD_district_deposits_ln.zip](https://github.com/qgis/QGIS/files/6290958/CMD_district_deposits_ln.zip)

**Comment by gioman** [comment]
> [GL200177_DEM_ft AZ_State_Plane_East_NAD27_ft.zip](https://github.com/qgis/QGIS/files/6290957/GL200177_DEM_ft.AZ_State_Plane_East_NAD27_ft.zip)
> [CMD_district_deposits_ln.zip](https://github.com/qgis/QGIS/files/6290958/CMD_district_deposits_ln.zip)

@davidjohnson11 works if you save your raster as geotiff.

**Comment by davidjohnson11** [comment]
OK.  I wouldn't have thought that the provenance of the raster would matter once it was imported.  But here we are.  Thanks for the workaround.

**Comment by gioman** [comment]
> OK. I wouldn't have thought that the provenance of the raster would matter once it was imported. But here we are. Thanks for the workaround.

@davidjohnson11 it should, but given the very rare nature of the format "Geosoft GXF" I'm not sure if this would be ever considered for a fix (given the easy workaround).

**Comment by roya0045** [comment]
If the format as a read-only driver, I'd vote to close this as nothing else can be done.

**Comment by davidjohnson11** [comment]
If it only works for GeoTIFF rasters, that should be noted in the documentation, if only to save others the trouble of attempting to use non-compliant raster formats.

**Comment by gioman** [comment]
> If it only works for GeoTIFF rasters,

@davidjohnson1it must be tested (with formats other than geotiff and the not working one you posted), if works only for geotiff it should clearly be documented at least.

**Comment by roya0045** [comment]
See https://gdal.org/drivers/raster/index.html for supported formats.

**Comment by gioman** [comment]
> See https://gdal.org/drivers/raster/index.html for supported formats.

@roya0045 Hi Alex, but this tool do not create a raster or write new values in a raster, it adds raster values to the Z of the vertexes of a polygon (that in origin can be even 2d, the output will be 3d).

**Comment by roya0045** [comment]
@gioman yes but it must read the raster. GXF are supported. So I'm not sure why the values are not applied, other than it need some othr capabilities.
