### ISSUE TITLE
"Check for updates on startup" doesn't do anything

### ISSUE THREAD

**Issue by miladaz** [qgis/QGIS#42752]
**Describe the bug**
Plugins setting "Check for updates on startup" doesn't seem to do anything.

**How to Reproduce**

In Plugins Settings (Plugins > Manage and Install Plugins) > Setting > The option "Check for updates on startup" as it says: "If this function is enabled, QGIS will inform you whenever a new plugin or plugin update is available."
I'm using my own repository. With this option enabled I expect it to inform me "every time QGIS starts" and whenever there is an update for an installed plugin but it doesn't inform me. I can see them in the "Upgradable" tab though.
I expect it to inform me that whenever I start QGIS in a nice message box or something.

**QGIS and OS versions**

QGIS version
3.16.5-Hannover
QGIS code revision
58ba7c1ed6
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
ExamplePlugin

**Additional context**

**Comment by fiddlersfan** [comment]
You'll be notified of new updates when they're available, but not via a big notification box you might expect. It is just a simple icon in the bottom right corner:

![Screenshot 2021-04-10 172905](https://user-images.githubusercontent.com/18557959/114275366-9be56600-9a22-11eb-84fe-2b791b378ef4.jpg)

**Comment by jgrocha** [comment]
I think you can automate your workflow with a simple `startup.py` script. Check the [startup file documentation](https://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/intro.html#the-startup-py-file).

Create this script and install it on all your clients.

You just need to right something like (replace `QuickOSM` with your awesome plugin key):

```
from qgis.utils import iface
from qgis.utils import active_plugins
import pyplugin_installer

def customize():
        if 'QuickOSM' in active_plugins:
                pyplugin_installer.instance().installPlugin('QuickOSM')

iface.initializationCompleted.connect(customize)
```

A simple message is added to the message panel.

![qgis after install plugin](https://user-images.githubusercontent.com/163681/114539281-3eccf880-9c4c-11eb-9be6-c80720a30289.png)

If you want to discuss a more visible feedback about plugins that can be updated, we can keep this issue open and change it to a Feature request. If this startup script is ok for your use case, we can close the issue (and the information will be here, if it helps others).
