### ISSUE TITLE
Can't load AequilibraE

### ISSUE THREAD

**Issue by Pooooooooooooh** [qgis/QGIS#42753]
When I plugin the AequilibraE, I can't load it and showed "Couldn't load plugin 'AequilibraE' due to an error when calling its classFactory() method See message log (Python Error) for more details." How can I solve it?

IMPORTANT:

If the issue concerns a third party plugin (downloaded with the plugin manager) then it can't be fixed by the QGIS team.
Please raise your issue in the dedicated bug tracker for that specific plugin (as listed in the plugin's description)

Tickets created here will be closed.

**Comment by gioman** [comment]
You must ask to the plugins author/s.
