### ISSUE TITLE
TIN Interpolation from vector to raster fails with unknown error

### ISSUE THREAD

**Issue by timlinux** [qgis/QGIS#42766]
I am trying to create a DEM from contours using the TIN interpolation tool.

QGIS version: 3.19.0-Master
QGIS code revision: 6df122bd19
Qt version: 5.14.2
GDAL version: 3.1.3
GEOS version: 3.8.1-CAPI-1.13.3
PROJ version: Rel. 7.1.0, August 1st, 2020

```
Processing algorithm…
Algorithm 'TIN interpolation' starting…
Input parameters:
{ 'EXTENT' : '499482.380000000,521757.950000000,1515163.700000000,1559694.900000000 [EPSG:2006]', 'INTERPOLATION_DATA' : 'dbname=\'gis\' host=localhost port=35432 user=\'docker\' password=\'docker\' sslmode=disable key=\'tid\' srid=2006 type=MultiLineStringZ checkPrimaryKeyUnicity=\'1\' table=\"public\".\"contours\" (geom)::~::1::~::-1::~::1', 'METHOD' : 1, 'OUTPUT' : '/home/timlinux/Downloads/stlucia-dem-from-contours.tif', 'PIXEL_SIZE' : 0.5 }

Traceback (most recent call last):
File "/home/timlinux/dev/cpp/QGIS-Debug-Build/output/python/plugins/processing/algs/qgis/TinInterpolation.py", line 188, in processAlgorithm
writer.writeFile(feedback)
Exception: unknown

Execution failed after 1707.56 seconds (28 minutes 28 seconds)

Loading resulting layers
Algorithm 'TIN interpolation' finished
```
I can see it started writing the output file and then failed:
```
-rw-rw-r-- 1 timlinux timlinux  111 Apr 12 10:43 stlucia-dem-from-contours.tif
```

At worst we should get a meaningful error message, otherwise it would be nice to make the output write properly.

**Comment by gioman** [comment]
@timlinux can you attach a sample dataset?

**Comment by timlinux** [comment]
@gioman Its quite big, I will see if I can replicate with a smaller one

**Comment by timlinux** [comment]
I am not sure if this is a good test dataset, I will test with it at home....

![image](https://user-images.githubusercontent.com/178003/114414190-8305bd80-9ba6-11eb-9424-44787867d265.png)

[contours.zip](https://github.com/qgis/QGIS/files/6297641/contours.zip)

**Comment by gioman** [comment]
@timlinux is the ticket about TIN or IDW? I tested your dataset with IDW (as seen in the screenshot) and trying to create a 1m raster output is just horribly slow, but no crash. A 10m output was created in a few seconds.

The attached dataset has no CRS, but I figured it was 2006 and created a new copy with the proper CRS.

**Comment by gioman** [comment]
I'm also on master on Ubuntu 20.04.

**Comment by baswein** [comment]
Don't know of this is helpful but it worked for me:
QGIS version: 3.18.1-Zürich
QGIS code revision: 202f1bf7e5
Qt version: 5.11.2
GDAL version: 3.1.4
GEOS version: 3.8.1-CAPI-1.13.3
PROJ version: Rel. 6.3.2, May 1st, 2020
Processing algorithm…
Algorithm 'TIN interpolation' starting…
Input parameters:
{ 'EXTENT' : '504546.390000000,506000.000000000,1543000.000000000,1544153.450000000 [EPSG:2006]', 'INTERPOLATION_DATA' : 'C:/Users/B/Desktop//tin/contours/contours.gpkg|layername=contours::~::1::~::-1::~::1', 'METHOD' : 1, 'OUTPUT' : 'TEMPORARY_OUTPUT', 'PIXEL_SIZE' : 0.5 }

Execution completed in 23.66 seconds
Results:
{'OUTPUT': 'C:/Users/B/AppData/Local/Temp/processing_DFaDdG/abfb5556b8ed4cc687970eaf7caf5951/OUTPUT.tif',
'TRIANGULATION': ''}

Loading resulting layers
Algorithm 'TIN interpolation' finished

**Comment by RyosukeKakehashi** [comment]
Hi @agiudiceandrea,
I used qgis on Ubuntu 20.04, and got the same problem.

I'm not sure why, but it worked by using the command line version as follows:
qgis_process run qgis:tininterpolation --INTERPOLATION_DATA=input.shp::~::0::~::1::~::1 --METHOD=0 --EXTENT="xmin,xmax,ymin,ymax" --PIXEL_SIZE=0.0005 --OUTPUT=output.tif

Parameters should be modified according to your GUI log.
