### ISSUE TITLE
Data corrupted when deleting field in a (specific) geopackage layer

### ISSUE THREAD

**Issue by cupain** [qgis/QGIS#42768]
Saving modifications after deleting a field of a geopackage layer also deletes entitie's geometry

**How to Reproduce**

1. Open a new QGIS project
2. Import a new geopackage layer (as [this one](https://ouvrir.passages.cnrs.fr/tutoqgis/donnees/TutoQGIS_07_Champs.zip))
3. Enter in edit mode
4. Open attributes table
5. Delete a field
6. Exit from edit mode, saving modifications
--> entities disappear in the canvas

**QGIS and OS versions**

QGIS 3.16-5, tested on Debian 10 and Windows 10

**Additional context**

This bug does not appear with a shapefile layer

**Comment by agiudiceandrea** [comment]
I can confirm the data corruption (but not any crash) using the provided geopackage with QGIS 3.18.1 (GDAL 3.1.4), 3.18.1 (GDAL 3.2.2), 3.16.5 (GDAL 3.1.4), 3.10.14 (GDAL 3.1.4), and 3.4.5 (GDAL 2.4.0) on Windows 7.
The issue doesn't occur with QGIS 2.18.23 (GDAL 2.2.4).

**Comment by cupain** [comment]
My mistake, indeed it's not a crash, but data corruption. Let me correct the issue's title and description tomorrow

-------- Message d'origine --------

**Comment by roya0045** [comment]
And with master on win10. Resulting data cannot be read and crs is lost.

**Comment by agiudiceandrea** [comment]
Anyway the issue seems related to this particular geopackage file. If you export the layer as a new geopackage and import it in QGIS, then there is no issue deleting fields.

**Comment by gioman** [comment]
> The issue is due to an incorrect trigger in the provided GeoPackage file which was probably created with an old GDAL version (prior to 2.4.0) that had a typo in the statement of the gpkg_metadata_reference_column_name_update trigger.
> See https://issues.qgis.org/issues/20765 (#28585) and [OSGeo/gdal@556738b](https://github.com/OSGeo/gdal/commit/556738b51b0b7b837544968199d359395a71e2ad)

seems a very edge case, it is really worth keeping this open?

**Comment by agiudiceandrea** [comment]
I think that if an older version of QGIS/GDAL created a faulty GeoPackage, then it should be desirable and fair if a newer version of QGIS/GDAL would automatically fix the faulty GeoPackage or inform the user about the issue when the layer is edited and/or not allow the user to delete a field in order to avoid data corruption/loss.

**Comment by TNogatz** [comment]
Had the same issue with this file:

[01.zip](https://github.com/qgis/QGIS/files/6383950/01.zip)

- prerequisite: clean QGIS without plugins, Windows 10. I’ve tested QGIS 2.18.28, 3.10.9, 3.16.5 and 3.18.1 – all with the same result.

- load 01.gpkg into an empty project. The geopackage contains only one layer „TUG_2021_SNR“.
- open the attribute table and delete field „Bemerkungen“ (If you want you can overwrite the contents of the field with NULL before deleting the field. The result will be the same.)
- save edits -> now all geometries are deleted without warning! 
- toggle editing and remove the layer
- again load 01.gpkg into the empty project -> there’s a new layer „TUG_2021_SNR_ogr_tmp“ which contains the attribute table of the deleted geometries. But the geometries are not available any more. In spite of of containing no geometries and no data, the title bar of the attribute table of layer 01_TUG_2021_SNR shows Features total: 24.

**Comment by agiudiceandrea** [comment]
@TNogatz the GeoPackage you provided has the same issue: it was probably created with a very old version of QGIS/GDAL so it contains a typo in the statement of the gpkg_metadata_reference_column_name_update trigger.
As a workaround, import your GeoPackage layer in QGIS, then export it as a new GeoPackage.

**Comment by TNogatz** [comment]
Andrea, thank you for responding so quickly. A colleague told me the geopackage was created using QGIS 3.2
Best wishes, Thomas

**Comment by gioman** [comment]
>  A colleague told me the geopackage was created using QGIS 3.2

@TNogatz yes, and that used an old version of GDAL.

**Comment by rouault** [comment]
Will be fixed in GDAL 3.3.1

**Comment by agiudiceandrea** [comment]
@rouault is there something that could be done from QGIS side to workaround the issue? (expecially for 3.16 LTR branch on systems/distributions that don't update GDAL very often)?

**Comment by rouault** [comment]
>  is there something that could be done from QGIS side to workaround the issue?

ok, I'll see

**Comment by jguelat** [comment]
This should also fix https://github.com/qgis/QGIS/issues/28585

Thanks a lot!
