### ISSUE TITLE
Supporting "set role" when connecting to a postgres database

### ISSUE THREAD

**Issue by davered00** [qgis/QGIS#42763]
**Feature description.**
QGIS would better if there was an option for the role to use when connecting to a postgres database

**Additional context**
I'm working within a postgres database that requires running a 'set role <role>' command before creating/deleting tables within a certain schema. This causes qgis's "Save to Postgresql" feature to always fail. If QGIS could support a "role" input box to specify within authentication info, which then is used within a set role command, sort of like how pgAdmin does it, that would solve this problem.
![qgis_login](https://user-images.githubusercontent.com/18541992/114325457-467e8700-9afe-11eb-8fbc-3017f73e4c86.PNG)
<img width="549" alt="pgadmin_login" src="https://user-images.githubusercontent.com/18541992/114325478-56966680-9afe-11eb-9f68-0333cdf963cd.PNG">

**Comment by roya0045** [comment]
¯\_(ツ)_/¯

**Comment by davered00** [comment]
Sorry, issue was commented out, lol. First time making a github issue

**Comment by jgrocha** [comment]
To make things clear, you are asking something like pgAdmin has: using one role just to connect and then assume the privileges of another role. The limitations (from pgAdmin documentation) are:

_Use the Role field to specify the name of a role that has privileges that will be conveyed to the client after authentication with the server. This selection allows you to connect as one role, and then assume the permissions of this specified role after the connection is established. Note that the connecting role must be a member of the role specified._

Sorry for the ignorance. I never used such a feature (I don't use pgAdmin). Can you describe better in which scenarios is this useful?

**Comment by davered00** [comment]
That is correct.

This is a postgres feature that is useful for automatic permission
management. If the base login user has no permissions to create a
table/view/function/etc, but can promote themselves to a role called
"admin" to create them (done using the noinherit setting), it will be
created under an owner of "admin," and all other users who can promote
themselves to that role will be able to modify the table/view/function/etc.

Without this, you'd have to manually modify the owner every time you
created anything, if you wanted to give other people access to it.


Separately, if you wanted to also set up roles that automatically give just
readonly permissions, or just r/w permissions for all objects (no creating
new ones, themselves) that anyone else would ever create in a certain
schema, you'd need to set up default rules for every possible user that
could create an object, and have to manually repeat that process if you got
a new admin. Without doing that, creating an object and then changing the
owner wouldn't be sufficient, as postgres uses the default permission rules
for the role that first created the table; changing the owner just affects
who can modify the table itself. In that case, you'd need to manually
assign read or r/w permissions correctly for every new object created.

In this case, forcing admins to promote to the "admin" role would make
postgres always use the default permission rules of that "admin" role when
creating objects, which would automatically make sure that any user with
just the "readonly" role or the "r/w" role could access all objects at
their access level, correctly.


Apologies if these explanations are too long-winded, haha. I recently spent
way too much time delving into how postgres permissions work while trying
to set something like this up, and it was not fun. But take my explanations
with a grain of salt, as there is definitely a chance that I might have
missed something and there's a smarter way to do all this.

**Comment by posikifi** [comment]
One scenario is also with PostgreSQL INHERIT/NOINHERIT -feature. PostgreSQL documentation mention:

> A role with the INHERIT attribute can automatically use whatever database privileges have been granted to all roles it is directly or indirectly a member of. Without INHERIT, membership in another role only grants the ability to SET ROLE to that other role; the privileges of the other role are only available after having done so. If not specified, INHERIT is the default. 

Is there anybody who like add this feature to QGIS? We have budget for this implementation.

**Comment by elpaso** [comment]
@posikifi @Bussink you should try to contact one or more companies that offer QGIS commercial support, here is a list: https://www.qgis.org/en/site/forusers/commercial_support.html#qgis-commercial-support

**Comment by posikifi** [comment]
@Bussink @elpaso This feature has alreade implemented: https://github.com/qgis/QGIS/pull/49960

At least 3.28.3 has it and I presume it will available also in next LTR.
