### ISSUE TITLE
Metasearch show password when opening connection properties dialog

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#42760]
In Metasearch the password is shown when editing a connection options

![Screenshot_20210411_172414](https://user-images.githubusercontent.com/1951107/114312575-f813bd00-9aea-11eb-943c-fe977577d93c.png)

in other clients (wms, wfs, etc.) this is hidden

![Screenshot_20210411_172451](https://user-images.githubusercontent.com/1951107/114312600-15488b80-9aeb-11eb-8b75-5184b70ce363.png)

**Comment by timlinux** [comment]
Can you look at this @tomkralidis  (assuming you are still maintaining metasearch)?

**Comment by tomkralidis** [comment]
thanks, will do.

**Comment by tomkralidis** [comment]
Pull request in #42767.  Will this be auto-backported or should I open dedicated PRs?
