### ISSUE TITLE
Raster calculator seems buggy under MacOS but not under Windows

### ISSUE THREAD

**Issue by frchalaoux** [qgis/QGIS#42776]
**Describe the bug**
- Open my project attached to this file and relink with images in the archive if there is a problem
- If you create a new NDVI raster layer with the raster calculator in MacOS GQIS the image width is half from individual bands used to create it and distorted. There is no problem with Windows to create a correct NDVI

**How to Reproduce**

1. Unzip sentinel-2.zip
2. Startup GQIS on MacOS
3. Open sentinel-2 projet
4. Go to 'Raster Calculator'
5. Create a NDVI geotiff image with the B08 and B04 bands : (B8 - B04) / (B08 + B04)
4. Compare the NDVI created under MacOS and observe if there is difference with Windows one present in this project

**QGIS and OS versions**

Version de QGIS | 3.18.1-Zürich | Révision du code | 202f1bf7e5
-- | -- | -- | --
Compilé avec Qt | 5.14.2 | Utilisant Qt | 5.14.2
Compilé avec GDAL/OGR | 3.2.1 | Utilisé avec GDAL/OGR | 3.2.1
Compilé avec GEOS | 3.9.1-CAPI-1.14.2 | Utilisé avec GEOS | 3.9.1-CAPI-1.14.2
Compilé avec SQLite | 3.31.1 | Fonctionne avec SQLite | 3.31.1
Compiled against PDAL | 2.2.0 | Running against PDAL | 2.2.0 (git-version: Release)
Version du client PostgreSQL | 12.3 | Version de SpatiaLite | 4.3.0a
Version de QWT | 6.1.4 | Version de QScintilla2 | 2.11.4
Compilé avec PROJ | 6.3.2 | Fonctionne avec PROJ | Rel. 6.3.2, May 1st, 2020
Version de l'OS | macOS Mojave (10.14)
Extensions Python actives | QuickOSM; SemiAutomaticClassificationPlugin; quick_map_services; cadastre; geosys-plugin; vrtbuilderplugin; processing; db_manager; MetaSearch

Cheers, 
[sentinel-2.zip](https://github.com/qgis/QGIS/files/6298199/sentinel-2.zip)

François-Régis Chalaoux

**Comment by gioman** [comment]
@frchalaoux have you used the raster calculator from the "raster" menu or from the processing toolbox? if you used the one in Processing, which one you used (as there is the QGIS native one and as well the GRASS and SAGA ones)?

**Comment by frchalaoux** [comment]
I used the calculator from the raster menu

**Comment by gioman** [comment]
@frchalaoux tested on 3.18.1 on macOS Catalina, results are ok.

![IMG_20210413_114600_1](https://user-images.githubusercontent.com/1951107/114540929-02020100-9c4e-11eb-9fcf-6888e09155f3.jpg)

**Comment by frchalaoux** [comment]
@gioman and @all, thanks for the test ! Now, what is the road to follow to help ? Should I investigate others things ?

Cheers

**Comment by gioman** [comment]
> @gioman and @ALL, thanks for the test ! Now, what is the road to follow to help ? Should I investigate others things ?

@frchalaoux try on a different machine, to exclude local issues.

**Comment by frchalaoux** [comment]
@gioman, Or on a different account on the same machine. I will to it. Keep in touch

**Comment by frchalaoux** [comment]
Ahhhh, On a clean account and on the same machine the default "Raster Calculator" is working ...
I have to clean my account !

Thanks @gioman

**Comment by frchalaoux** [comment]
The same problem is coming back very often and it seems present that all versions 3.18/3.20. It's very time consuming to recreate each time a new profile. Can we reopen this issue ?

**Comment by gioman** [comment]
> Can we reopen this issue

@frchalaoux only if is proven to be a QGIS issue, and not something caused by a 3rd party plugin.

**Comment by frchalaoux** [comment]
@gioman Should it be sufficient to create a new profil with no plugin ?

**Comment by gioman** [comment]
> @gioman Should it be sufficient to create a new profil with no plugin ?

@frchalaoux it is the first thing we ask to do, use a new profile with no 3rd party plugins to exclude problems caused by plugins or custom/legacy configurations. If it "solves" the issue then you go back to the other profile and get the issue then you know where the problem likely lies.
