### ISSUE TITLE
QGIS Failing to Transform and Display Layer

### ISSUE THREAD

**Issue by ar-siddiqui** [qgis/QGIS#42786]
**Describe the bug**
Sometimes if I have two layers in two different CRS. One of them won't show up or show up at an incorrect location if the Project CRS is different than the layer CRS. I can look at each layer at the correct location if I change the project CRS to the layer CRS, so my assumption is that it has something to do with projection on the fly.

**How to Reproduce**

It happens randomly, the only thing I have noticed is that when this happens there is no transformation available here as well as in settings > options > transformations
![image](https://user-images.githubusercontent.com/53625184/114557466-b3496c80-9c37-11eb-94d4-6a6c5b8d0f05.png)

Using a different version of QGIS and/or completely closing and reopening the QGIS fixes the issue most of the times.

I will update here if I can find a way to reproduce it.

This issue has been happening on and off with me and a few of my colleagues for the past one and a half years I would say, against various versions of QGIS. This has started happening only when QGIS started showing this window, it never happened before.

![image](https://user-images.githubusercontent.com/53625184/114558115-57cbae80-9c38-11eb-8375-6339c828b8c8.png)

**QGIS and OS versions**

QGIS version
3.16.5-Hannover
QGIS code revision
58ba7c1ed6
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
area_weighted_average; 
batchvectorlayersaver; 
changeDataSource; 
curve_number_generator; 
mapswipetool_plugin; 
MemoryLayerSaver; 
mmqgis; 
MultipleLayerSelection; 
QGIS3-getWKT; 
searchlayers; 
send2google_earth; 
spline; 
StreetView; 
valuetool; 
db_manager; 
processing

**Comment by gioman** [comment]
> I will update here if I can find a way to reproduce it.

@ar-siddiqui reopen the ticket if/when you are able to replicate the problem in a consistent and clear way.

**Comment by ar-siddiqui** [comment]
[QGIS_Issue.zip](https://github.com/qgis/QGIS/files/6437799/QGIS_Issue.zip)

@gioman see the attached project. It has a raster and a polygon. Both are in different projections. When I perform zonal statistics all statistics are null. If I reproject the layer to match the layer projection to the raster projection, zonal statistics will perform fine. It can be reproduced. Tried on two different versions of QGIS.

I have come across similar situations before, if you can reproduce the issue please open the issue.

**Comment by gioman** [comment]
> hen I perform zonal statistics all statistics are null.

@ar-siddiqui there are Processing tools that **do** expect to have both input layers in the same CRS.

**Comment by ar-siddiqui** [comment]
@gioman Is Zonal Statistics one of those tools? I checked Algorithm help and documentation and this has not been mentioned anywhere. If I can get confirmation I will then submit a request in the documentation repo to add it.

https://docs.qgis.org/3.10/en/docs/user_manual/processing_algs/qgis/rasteranalysis.html?highlight=zonal%20statistics#zonal-statistics

**Comment by gioman** [comment]
>  Is Zonal Statistics one of those tools?

@ar-siddiqui if it does not work with inputs with different CRSs then... yes I guess.

You can always file a feature request to make it work with inputs with different CRSs. Or maybe someone could even argue is a bug (as many other native QGIS tools do not require the same CRS for inputs), anyway you'll need to file a new specific ticket about this matter (as is not related to this ticket).

**Comment by ar-siddiqui** [comment]
Thanks. Will do.
