### ISSUE TITLE
Attribute table: missing features when copying/pasting from scratch layer

### ISSUE THREAD

**Issue by lukas-hribik** [qgis/QGIS#42798]
Watch video:
http://www.icsp.sk/20210414_230713.mp4

Steps:
1. Open new project
2. Create new shapefile (polygon)
3. Draw 3 features
4. Create new temporary scratch layer
5. Draw 1 features, select it and press CTRL-C
6. Select shapefile layer and open Attribute table
7. Focus on Attribute table and press CTRL-V 
8. Save layer (there are 4 features in table)
9. Delete one feature (not last one)
10. Press CTRL-V (there are 4 features in table)
11. Save layer (there are only 3 features in table - one is missing)

**QGIS and OS versions**

QGIS version
3.18.1-Zürich
QGIS code revision
202f1bf7e5
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
AnotherDXF2Shape; 
cartography_tools; 
changeDataSource; 
clipper; 
deactivate_active_labels; 
DigitizingTools; 
ezprinter; 
FreehandRasterGeoreferencer; 
localcoordinates; 
numericalDigitize; 
db_manager; 
MetaSearch; 
processing

**Comment by gioman** [comment]
Seen the same also on master/linux.

**Comment by lukas-hribik** [comment]
Same problem when copying/pasting from another shapefile or mysql layer (maybe any type of layer is affected).

**Comment by SanttuVP** [comment]
Confirmed the same on LTR (3.16.7) / linux.

**Comment by troopa81** [comment]
I failed to reproduce in 3.16.10 and master. Could you tell me if you still meet the issues with those versions? 

In case of I maybe miss some steps, here is a video of my test
 
![copypaste](https://user-images.githubusercontent.com/14358135/133570527-9b173bf6-4cd9-4a56-b9e3-510dfaf34230.gif)

**Comment by lukas-hribik** [comment]
I'm still able reproduce on 3.20.3 on Windows 10 ver 2009 (clean profile). I don't have installed developer master version, so I will try again on next release.
troopa81 - your steps seems to be right (except I dont use automatic ID generation)
