### ISSUE TITLE
format() expression function incorrect results

### ISSUE THREAD

**Issue by Houska1** [qgis/QGIS#42806]
3.18.1, OSGeo4W release build.

The `format()` expression function provides incorrect results when not all of the %1,%2,... arguments are used

`format('%2',1,2)` returns 1 rather than 2.

However, `format('%2 %1',1,2)` correctly returns 2 1.

(I am encountering this in defining a complex symbology where multiple feature measurements are rendered using a font marker symbol layer. For ease of modification, the format string is pulled out as a variable, but the results are wrong when I set the format string to only actually use some of the computed measurements.)

**Comment by elpaso** [comment]
I don't think this is a bug, the number after the `%` is meant for ordering the arguments, you could in theory have: `format('%99 %11', 1, 2)` that would yield `2 1`.

At least, this is how it works in Qt: https://doc.qt.io/qt-5/qstring.html#arg

**Comment by Houska1** [comment]
I guess if Qt does it that way by design, it's not quite a bug. 

However, it is a shame. It would be helpful if `format(@label_fmt,"Distance","Bearing")` generated (as it does) `100m 45°` if `@label_fmt` is `'%1m %2°'`, but also just  `45°` if `@label_fmt` is `'%2°`. It feels like that is more intuitive and helpful than the use case of a lazy format string of `%32 %77` being equivalent to `%1 %2`.  

Anyway, I'll close this in a few hours unless someone else chimes in that this is worth addressing against Qt's design choice. (I doubt it.)

**Comment by Houska1** [comment]
OK, no one seems to feel this is Wrong, so closing it. In case anyone else ever has this issue, I used python-style format as a workaround with a custom expression function, which behaves as expected:

```
@qgsfunction(args=-1, group='Custom')
def format_p(arglist, feature, parent):
    """
    Replacement for QGIS format() expression function with Python ,format
    """
    fmtstring, *params = arglist
    return fmtstring.format(*params)
```

**Comment by Houska1** [comment]
Since we're not going to change it, at least added guidance in help for the format function to point user to Qt's QString::arg description, which is in general a good idea given the number of different formatting functions out there.
