### ISSUE TITLE
Connect to MSSQL from Ubuntu

### ISSUE THREAD

**Issue by webgis147** [qgis/QGIS#42805]
I try to connect to a SQL Server database running on Windows server from an ubuntu bionic server
I installed msodbcsql17 and msodbcsql17 on the ubuntu machine

I configured the .ini files

    odbcinst.ini:

[SQL Server] 
Description=Microsoft ODBC Driver 17 for SQL Server
Driver=/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.7.so.2.1
UsageCount=1<br/>

    and odbc.ini :

[kplus]
Driver =SQL Server  
Server = ip-adress, 1433  
Database=kplus

I can connect with isql command isql -v kplus pdw usr and query tables.

When I try add MS SQL connection via qgis 3.16 data browser or data source manger I receive the following error:
Error opening connection : Driver not loaded Driver not loaded

When I try to add a Vector Layer via  data source manger i can sucessfully add and test the database connection.
whereas it is not possible to add tables without geometry.
This is a different behavior to Qgis 3.16 running on Windows where i can add MSSQL tables without geometry through all connection possibilities.

**Comment by gioman** [comment]
@webgis147 why not using the native MS SQL provider in QGIS (I'm assuming your are using ODBC instead)?

> When I try add MS SQL connection via qgis 3.16 data browser or data source manger I receive the following error:
> Error opening connection : Driver not loaded Driver not loaded
> 
> When I try to add a Vector Layer via data source manger i can sucessfully add and test the database connection.
> whereas it is not possible to add tables without geometry.
> This is a different behavior to Qgis 3.16 running on Windows where i can add MSSQL tables without geometry through all connection possibilities.

this seems something related to using such driver on Ubuntu, not QGIS itself.

**Comment by webgis147** [comment]
Hi Giovanni,
How do I use the native provider? If I try it similar to Win10, I also receive the "Driver not loaded message". Is it possible to establish a Qgis  connection directly from Linux to an MSSQL Server running on Windows at all? Or do I miss some important requirements.
many thanks for your help!
Johannes
![Screenshot 2021-04-16 072827](https://user-images.githubusercontent.com/11421740/114976776-d6b62680-9e86-11eb-81cc-9688a3ac9c84.png)

**Comment by gioman** [comment]
> How do I use the native provider? If I try it similar to Win10, I also receive the "Driver not loaded message". Is it possible to establish a Qgis connection directly from Linux to an MSSQL Server running on Windows at all? Or do I miss some important requirements.
> many thanks for your help!

@webgis147 you are assuming that this is a bug but probably is just a missing library on Linux. You should ask in the users or developers mailing lists, not here.

**Comment by webgis147** [comment]
Hi Giovanni,
Thanks for your feedback, i raised this issue on gis.stackexchange.com more than a year ago without a result. I will post is now on the developers an user mailing list.

br
Johannes

**Comment by Bud8600** [comment]
Hi, I seem to have the same issue. Did you find any solution yet?

**Comment by murdocha** [comment]
@Bud8600 
I don't believe that there _is_ a "native" MSSQL QGIS "provider" for Linux, but only on Windows QGIS.

I was able to do something similar (accessing MS SQL data in a python QGIS script running on Docker Linux with the qgis/qgis image from Docker hub) using the default MS SQL ODBC driver that comes built-in with the QGIS provided version of GDAL/OGR. 
You might be able to do that and then connect to MS SQL data using the "ogr" provider within the QGIS UI?
