### ISSUE TITLE
WFS layer filter - pre-fill Colums and Table(s) fields in SQL Query Composer

### ISSUE THREAD

**Issue by pathmapper** [qgis/QGIS#42800]
**Feature description.**

WFS layer filter (_Layer contextmenu -> Filter..._ ) - pre-fill Colums and Table(s) fields in SQL Query Composer like in its select source:

Columns -> *
Table(s) -> layer table

<img src="https://user-images.githubusercontent.com/20856381/114824636-7c08c600-9dc5-11eb-950a-ed51aae492bc.png" width="400">

<img src="https://user-images.githubusercontent.com/20856381/114819319-976fd300-9dbd-11eb-86f2-cb01884f4410.png" width="400">

**Additional context**
Starting with QGIS 3.18 (https://github.com/qgis/QGIS/pull/40071) the editor used for filtering the layer has changed from using the _Query Builder_ to _SQL Query Composer_.

**Before:**
<img src="https://user-images.githubusercontent.com/20856381/114818181-9e95e180-9dbb-11eb-9280-f7c4a1eb9e61.png" width="400">

**QGIS 3.18:**
<img src="https://user-images.githubusercontent.com/20856381/114818209-a9507680-9dbb-11eb-9d78-6780329c741c.png" width="400">

Now you have to populate the Colums_ and _Table(s) fields yourself, for the _Query Builder_ this was not needed. Due to this change I've got some user feedback like _"How can I filter a WFS layer with QGIS 3.18?"_ or _"I want the old filter editor back!"_.

Not only for those people it would be extremely helpful if _Colums_ and _Table(s)_ would be pre-filled - if you add a WFS layer via QGIS Browser it's often not obvious which table name to use for a specific layer.

Also this feature is already implemented for WFS select source (_Data Source Manager -> WFS / OGC API Featureas -> Build Query_).

**Comment by jkr-wrk** [comment]
Any possibility to add the sample values function as well? In the query builder it a query on the complete WFS dataset, this was somewhat time-consuming. But a sample of the current viewable dataset could be an option?

For most users the current implementation went from 6 intuitive mouse clicks to 16 not at all intuitive mouse clicks, where it actualy is inpossible to not touch the keyboard.

Current instruction:

1. Click on the inspector
2. Click on the feature you want to filter
3. Right click on the value you want to filter on in the identify results window
4. Click on copy attribute value
5. Right click on layer
6. Click on filter...
7. Click in the Where box
8. Click on 'Columns'
9. Click on the property you want to filter
10. Type ='' in the Where box
11. Paste the clipboard
12. Type * in the Columns box
13. Click in the Table(s) box
14. Click on Tables
15. Click on the Table you want to filter
16. Click OK

Is there any way I can get my Query Builder back... soon :(

**Comment by pathmapper** [comment]
> Is there any way I can get my Query Builder back

@rduivenvoorde started recently a discussion on the dev mailing list about this topic, see https://lists.osgeo.org/pipermail/qgis-developer/2021-October/064180.html and the replies to his post.

**Comment by martinedoesgis** [comment]
+1 for this issue : 

- pre-fill Colums and Table(s) fields in SQL Query Composer
- being able to see Sample or All values for a selected field

The new SQL Query Composer is really not intuitive for users not working with SQL on daily basis. Or at least provide the possibility to switch back to the former Query Builder
