### ISSUE TITLE
Filter expression from relation reference widget on attributes form, not working properly

### ISSUE THREAD

**Issue by joaquinmunoz** [qgis/QGIS#42803]
**Describe the bug**

Filter expression from relation reference widget on attributes form, not working properly when closing project and opening it again.

**How to Reproduce**

1. On Layer Properties/Attibutes Form, set up a 'Relation Reference' Widget Type, tick on 'Filters'
Write a condition on 'Filter expression'.
Apply and OK
2. Add a new feature in that layer by using the form
Check that subset values in drop-down box, meets with filter expression
3. Save and close the project
4. Open the project again
5. Repeat step 2. and check that this time, values in drop-down box are not filtered as expected

![bug_expression2](https://user-images.githubusercontent.com/25054877/114825418-7cee2780-9dc6-11eb-8beb-212a59b7d5d5.gif)

**QGIS and OS versions**

QGIS version
3.16.4-Hannover
QGIS code revision
cdb515a206
Compiled against Qt
5.14.2
Running against Qt
5.14.2
Compiled against GDAL/OGR
3.2.1
Running against GDAL/OGR
3.2.1
Compiled against GEOS
3.9.1-CAPI-1.14.2
Running against GEOS
3.9.1-CAPI-1.14.2
Compiled against SQLite
3.31.1
Running against SQLite
3.31.1
PostgreSQL Client Version
12.3
SpatiaLite Version
4.3.0a
QWT Version
6.1.4
QScintilla2 Version
2.11.4
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
macOS 10.15
Active python plugins
QuickOSM;
freehandEditing3;
AzimuthMeasurement;
quick_map_services;
geometry_paster;
OSMDownloader;
openlayers_plugin;
trail_elevation_stats;
valuetool;
Spanish_Inspire_Catastral_Downloader;
Mergin;
processing;
db_manager;
MetaSearch;
BufferByPercentage

**Additional context**

Layer source is a PostGIS table
A relation must exist in order to set up 'Relation Reference' widget

**Comment by 3nids** [comment]
I could not reproduce with a clean project.

Can you check if the filter is still in the config after saving/re-opening the project?

**Comment by joaquinmunoz** [comment]
Thanks 3nids for your response

If your first action after opening the project is adding a new feature, then the filter doesn't works, but when following the sequence below:

- open the project
- open Layer Properties/Attributes Form
- select the field in 'Form Layout' box (the one you want to filter)
- click OK button
- select Layer and add a new feature

then, the form filter works properly

Hope this information could help

**Comment by 3nids** [comment]
confirmed
