### ISSUE TITLE
crash after loading renamed gml

### ISSUE THREAD

**Issue by janhec** [qgis/QGIS#42819]
## User Feedback

loading an xml with gml content after renaming it to .gml

## Report Details

**Crash ID**: [7949289ebb8e3fe148837904e387c6c4b8a7901f](https://github.com/qgis/QGIS/search?q=7949289ebb8e3fe148837904e387c6c4b8a7901f&type=Issues)

**Stack Trace**
<pre>
QBitArray::QBitArray :
QgsVirtualLayerDefinition::query qgsproperty.h:164
QgsRuleBasedRenderer::convertFromRenderer qgsrulebasedrenderer.cpp:1314
meth_QgsRuleBasedRenderer_convertFromRenderer sip_corepart2.cpp:110753
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QMetaObject::activate :
QgisInterface::currentLayerChanged moc_qgisinterface.cpp:817
QMetaObject::activate :
QgisApp::activeLayerChanged moc_qgisapp.cpp:2800
QgisApp::onActiveLayerChanged qgisapp.cpp:717
QMetaObject::activate :
QgsLayerTreeView::currentLayerChanged moc_qgslayertreeview.cpp:307
QgsLayerTreeView::onCurrentChanged qgslayertreeview.cpp:322
QMetaObject::activate :
QItemSelectionModel::setCurrentIndex :
QAbstractItemView::mousePressEvent :
QTreeView::mousePressEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:475
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:475
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1638
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.18.1-Z�rich
QGIS code revision: 202f1bf7e5
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

**Comment by gioman** [comment]
> loading an xml with gml content after renaming it to .gml

@janhec please attach the file.
