### ISSUE TITLE
export bbox wrong when feature crosses anti-prime-meridion (180 deg)

### ISSUE THREAD

**Issue by sb4** [qgis/QGIS#42827]
**Describe the bug**

I am exporting a layer (CRS: EPSG:4269-NAD83) that only contains the US State of Alaska (highly simplified for this report) with "WRITE_BBOX" set to "True".   The bug is that the bbox array in the JSON output file has "wrong" / unusable longitude values.  I believe the cause is that the "Alaska" feature crosses the antimeridion of 180 deg, and the largest positive longitudes are assumed to be the most "eastward" point, and the largest negative longitude is assumed to be the most "westward" point.  That assumption makes the bbox values useless for defining a bounding box.  I believe the proper algorithm for exporting the bbox array is to first "normalize" the longitude values to a continuous scale (such as -360 to 0), find the min and max longitudes, and then convert back to the convention -180 to 180 scale to include in the bbox array.

**How to Reproduce**

0.  Open the attached zip file and save the attached Shape data files to a folder. (Or the example exported geojson file could also be used).
1.  Create a new CGIS3 project.
2.  Using the CGIS3 browser, locate the Shape data file and double-click it to create a new layer.
3.  Right-click on the layer in the Layers pane, choose "Export | Save Features As" and export the layer to a new file.  Use the following parameters: format "GeoJSON"; CRS "EPSG:4269-NAD83" (some other formats can be used); Geometry Type "Automatic"; COORDINATE_PRECISION "2"; RFC7946 "Yes"; WRITE_BBOX "Yes"
4.  Enter a Filename to save the data in.
5. Click OK

6. Open the output file with any text editor and observe the "bbox" array values for the min and max longitudes.   Then analyze the "coordinates" arrays and find the most westward and eastward longitudes represented.  Compare them to the bbox values.  You should see the discrepancy between the bbox bounding longitudes and the eastmost and westmost longitudes.

**QGIS and OS versions**
 CGIS3 version 3.18.1 Zurich with Windows 10.

QGIS version
3.18.1-Zürich
QGIS code revision
202f1bf7e5
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
autoSaver; 
excel_sync; 
Generalizer3; 
db_manager; 
MetaSearch; 
processing; 
CustomToolBar

[AlaskaAttuSimplified_EPSG4269-NAD83.zip](https://github.com/qgis/QGIS/files/6327907/AlaskaAttuSimplified_EPSG4269-NAD83.zip)

**Additional context**

**Comment by sb4** [comment]
I would like to update my bug report.  I realize that this is probably not a "bug" but perhaps a matter of interpretation of a bounding box on a sphere with a particular coordinate system.  I believe I'm looking for the "tightest" bounding box, and using prime meridian based -180 to 180 coordinates does not do that for the US State of Alaska because it creates a bounding box that stretches around the globe.

It seems we need better control over this issue, or warnings, or some way to better define the bounding box when a layer or features straddle the point where the coordinate system wraps around and starts over (prime antimeridian typically).  I have not yet found a CRS with an antimeridian centered coordinate system -- that might do the trick for handling the case of the bounding box for the US State of Alaska and would still apply for the rest of the country, but it would force a highly unconventional coordinate system on the exported data.  A somewhat preferable coordinate system would be a 0 to -360, where most points in North America would have conventional lat/lon values, and only the few outlying Alaskan islands would have longitudes less than -180.

My use of the bounding box is part of an "in-polygon" algorithm for determining which US State or Canadian Province a GPS coordinate is in.  The bounding boxes are a quick way to eliminate many polygons from examination.  The workaround is to calculate my own bounding boxes by converting the coordinate system on the fly when loading the cartographic data and converting the GPS points also to a 0 to -360 reference.

**Comment by alexbruy** [comment]
Tested with `ogr2ogr` and got the same results. It might be a feature/bugreport for upstream.

@rouault do you think this should be addressed in GDAL?
