### ISSUE TITLE
Change Data Source tool deletes existing layer metadata

### ISSUE THREAD

**Issue by y-vasyunin** [qgis/QGIS#42821]
**Describe the bug**

Changing a data source of a vector layer cleans out its metadata.

**How to Reproduce**

1. Check out that your layer has some filled metadata, such as Abstract and Contact information, in **Layer Properties** -> **Metadata**.
2. Right click on the vector layer in the **Layers Panel** and then **Change Data Source...**
3. Select a new datasource in an appeared popup window. You may even select the current datasource - it will lead to the same end.
4. Apply changes and see that metadata is not preserved. At the same time, custom layer name and its styling remains.

**QGIS and OS versions**

QGIS version | 3.18.1-Zürich | QGIS code revision | 202f1bf7e5
-- | -- | -- | --
Compiled against Qt | 5.15.2 | Running against Qt | 5.15.2
Compiled against GDAL/OGR | 3.2.2 | Running against GDAL/OGR | 3.2.2
Compiled against GEOS | 3.9.1-CAPI-1.14.2 | Running against GEOS | 3.9.1-CAPI-1.14.2
Compiled against SQLite | 3.35.2 | Running against SQLite | 3.35.2
Compiled against PDAL | 2.2.0 | Running against PDAL | 2.2.0 (git-version: 24dd45)
PostgreSQL Client Version | 13.0 | SpatiaLite Version | 5.0.1
QWT Version | 6.1.3 | QScintilla2 Version | 2.11.5
Compiled against PROJ | 8.0.0 | Running against PROJ | Rel. 8.0.0, March 1st, 2021
OS Version | Windows 10 Version 2009
Active python plugins | GeoCoding; ImportPhotos; kmltools; lockzoom; OSMDownloader; profiletool; QuickOSM; QuickWKT; quick_map_services; valuetool; zoom_level; db_manager; MetaSearch; processing

**Comment by fiddlersfan** [comment]
I can reproduce the bug on my end as well. The bug occurs not only when the user actively wants to change the data source, but also when a data source is no longer available at startup ("Handle Unavailable Layers" dialog). Especially in the case it is annoying for the user, because this is not a conscious action...
