### ISSUE TITLE
accessing to PrestoDB through a ODBC driver

### ISSUE THREAD

**Issue by rherasm** [qgis/QGIS#42820]
**Describe the bug**
Unable to load data from a Database PrestoDB v0.227 (AWS) through ODBC driver (Simba ODBC Driver).

**How to Reproduce**
Adding a new layer from a database through ODBC. It crashed after a few minutes.

**QGIS and OS versions**
QGIS 3.18
Windows 10 x64

**Additional context**

Crash ID: 06185e4f55750f7d778aea3693e2e4be9daec2b3

Stack Trace

memcpy_repmovs memcpy.asm:114
CPLODBCStatement::Fetch :
SBNSearchFreeIds :
SBNSearchFreeIds :
QgsOgrProvider::addSubLayerDetailsToSubLayerList qgsogrprovider.cpp:894
QgsOgrProvider::_subLayers qgsogrprovider.cpp:1028
QgsOgrProvider::subLayers qgsogrprovider.cpp:977
QgisApp::addVectorLayersPrivate qgisapp.cpp:5578
QgisApp::addVectorLayers qgisapp.cpp:5490
QgisApp::qt_static_metacall moc_qgisapp.cpp:1729
QMetaObject::activate :
QgsDataSourceManagerDialog::addVectorLayers moc_qgsdatasourcemanagerdialog.cpp:405
QMetaObject::activate :
QgsAbstractDataSourceWidget::addVectorLayers moc_qgsabstractdatasourcewidget.cpp:359
QgsOgrSourceSelect::addButtonClicked qgsogrsourceselect.cpp:503
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:475
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:475
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1638
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.18.1-Z�rich
QGIS code revision: 202f1bf7e5
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

**Comment by gioman** [comment]
@rherasm can you give us a PrestoDB endpoint we can try?

**Comment by rherasm** [comment]
> 
> 
> @rherasm can you give us a PrestoDB endpoint we can try?
Sorry @gioman , I can't provide you it at this time, my current instance is within AWS with not direct access to Internet.
But maybe I could prepare you a testint end-point in the coming days if that could be useful for you in order helping you to fix that bug. I would depend of your availability and period of time needed.
Please confirm it and in such case I'd contact my operations department in order to prepare it. It would be great if we could fix it and include it in the next releases of the product.
Thanks a lot for your help.
cheers.

**Comment by gioman** [comment]
> But maybe I could prepare you a testint end-point in the coming days if that could be useful for you in order helping you to fix that bug. I would depend of your availability and period of time needed.
> Please confirm it and in such case I'd contact my operations department in order to prepare it. It would be great if we could fix it and include it in the next releases of the product.

@rherasm there is no guarantee that anyone will have a look at this problem, even if you provide the endpoint, in its free time or during the bug fixing campaigns, but without the endpoint the chance is basically zero. If you and your organization need a quick fix for this then you should look for commercial support on the qgis.org's web site.
