### ISSUE TITLE
Crash whilte editing legend

### ISSUE THREAD

**Issue by patriciout** [qgis/QGIS#42829]
## User Feedback

I was editing the legend in the map template and accidentally hit the DELETE key when the legend box was selected.
![Captura](https://user-images.githubusercontent.com/82684604/115093777-67255300-9ee9-11eb-8e92-c9a1fc117198.PNG)

## Report Details

**Crash ID**: [697d5b7e89a3daa369ece5b483b5d4dfe097a0a9](https://github.com/qgis/QGIS/search?q=697d5b7e89a3daa369ece5b483b5d4dfe097a0a9&type=Issues)

**Stack Trace**
<pre>
QObject::metaObject :
QMetaObject::cast :
QgsLegendModel::data qgslayoutitemlegend.cpp:1082
QModelIndex::data :
QStyledItemDelegate::sizeHint :
QTreeViewPrivate::widthHintForIndex :
QTreeView::sizeHintForColumn :
QHeaderView::resizeSections :
QHeaderView::sectionSize :
QTreeViewPrivate::updateScrollBars :
QTreeView::updateGeometries :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QWidgetPrivate::sendPendingMoveAndResizeEvents :
QWidgetPrivate::show_helper :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidget::setVisible :
QStackedLayout::setCurrentIndex :
QgsPanelWidgetStack::closePanel qgspanelwidgetstack.cpp:140
QMetaObject::activate :
QgsPanelWidget::panelAccepted moc_qgspanelwidget.cpp:190
QMetaObject::activate :
QObject::~QObject :
QgsLayerTreeLayer::`vector deleting destructor' :
QgsLayerTreeNode::~QgsLayerTreeNode qgslayertreenode.cpp:48
QgsLayerTree::`vector deleting destructor' :
QgsLayoutItemLegend::~QgsLayoutItemLegend :
QgsLayoutItemLegend::`vector deleting destructor' :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1637
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.16.5-Hannover
QGIS code revision: 58ba7c1ed6
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

**Comment by gioman** [comment]
@patriciout please test on a new QGIS profile, is the problem persist attach a sample project+data to allow us replicate.
