### ISSUE TITLE
Exporting FlatGeobuf allow other than UTF-8 encoding

### ISSUE THREAD

**Issue by bjornharrtell** [qgis/QGIS#42834]
FlatGeobuf only supports UTF-8 encoding and the encoding selection should be grayed out as with fx. GeoPackage.

I've as of yet failed to locate what logic controls this.

**Comment by bjornharrtell** [comment]
Thanks @nyalldawson! ❤️

**Comment by uclaros** [comment]
No problem @bjornharrtell ! :)

**Comment by bjornharrtell** [comment]
Oops sorry @uclaros I now see you are the kind author. :) So thank you, too!
