### ISSUE TITLE
Crash on zoom-in

### ISSUE THREAD

**Issue by dario955i** [qgis/QGIS#42833]
Crash ID: 38dfb627cb1973ee90f669124d0cf7c501d37f30

Stack Trace

GEOSEquals_r :
GEOSEquals_r :
QgsGeos::shortestLine :
QgsGeometry::shortestLine :
QgsCallout::QgsCalloutContext::operator= :
QgsSimpleLineCallout::draw :
QgsCallout::render :
QgsVectorLayerLabelProvider::drawCallout :
QgsVectorLayerLabelProvider::drawLabelBackground :
QgsLabelingEngine::drawLabels :
QgsDefaultLabelingEngine::run :
QgsMapRendererJob::drawLabeling :
QgsMapRendererParallelJob::renderLabelsStatic :
QgsMapRendererCustomPainterJob::renderSynchronously :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.16.4-Hannover
QGIS code revision: 654e76b3cb
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
@dario955i please try with a new QGIS profile, no 3rd party plugins installed. If the problem persist please add detailed steps to replicate and as well a sample project with data.

**Comment by roya0045** [comment]
@gioman I'm pretty sure the issues with QgsGeos::shortestLine : are fixed in the latest versions already. I propose closing this.

**Comment by uclaros** [comment]
Probably already fixed by #41986
