### ISSUE TITLE
QGIS SAGA-Toolbox Simple Filter

### ISSUE THREAD

**Issue by ThorstenLWK** [qgis/QGIS#42858]
**Describe the bug**
Using the process <Simple Filter> from the SAGA-toolbox on a raster dataset results in edge pixels showing out of range data.

**How to Reproduce**

1. Go to 'Processing Toolbox SAGA>Raster Filter'
2. Click on 'Simple Filter'>Search Mode "Square">Filter "Smooth">Radius "2"
3. Check the result (Filtered Grid).

**QGIS and OS versions**

QGIS version
3.16.4-Hannover
QGIS code revision
654e76b3cb
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
cartogram3; 
clipper; 
gdm_viewer; 
Multi_Ring_Buffer; 
nominatim; 
QGISSortAndNumber-master; 
SpreadsheetLayers; 
wfsclient; 
xyToPoint; 
db_manager; 
MetaSearch; 
processing

[test_Data.zip](https://github.com/qgis/QGIS/files/6335551/test_Data.zip)
[Bug in QGIS_EN.docx](https://github.com/qgis/QGIS/files/6335639/Bug.in.QGIS_EN.docx)

**Additional context**

**Comment by alexbruy** [comment]
Does it produce different output when you run the same tool with the same input and parameters using SAGA command line tools?

**Comment by ThorstenLWK** [comment]
Yes, when we use SAGA as a stand-alone Programm with the same dataset the Edge Pixels are not produced.

**Comment by gioman** [comment]
> Yes, when we use SAGA as a stand-alone Programm with the same dataset the Edge Pixels are not produced.

@ThorstenLWK you sure you used the same SAGA version used by QGIS and the very same command generated by QGIS? can you post here the command used?

**Comment by ThorstenLWK** [comment]
We use SAGA GIS Ver. 7.7. Simple Filter and compare it to the results we get with QGIS 3.16 SAGA-Toolbox Simple Filter.
Please find attached the SAGA 7.7 information for Simple Filter.
![SAGA_7_7_Simple_Filter](https://user-images.githubusercontent.com/82802670/115254191-65e46800-a12d-11eb-9eac-9c6eaefb823a.png)

**Comment by gioman** [comment]
> We use SAGA GIS Ver. 7.7.

@ThorstenLWK if you are on Windows then QGIS still uses a very old SAGA release (2.something if I'm not wrong). You should check from the CLI with the same SAGA version.

**Comment by ThorstenLWK** [comment]
Thanks! You are right: QGIS 3.16 (Windows 10) uses SAGA Version: 2.3.2 (64 bit). Can you substitute the SAGA 2.3.2 Simple Filter command with the command of the current SAGA Version for the upcoming QGIS-versions? Thanks again!

**Comment by gioman** [comment]
> Thanks! You are right: QGIS 3.16 (Windows 10) uses SAGA Version: 2.3.2 (64 bit)

@ThorstenLWK so we close this?



> Can you substitute the SAGA 2.3.2 Simple Filter command with the command of the current SAGA Version for the upcoming QGIS-versions? Thanks again!

the next generation of installers for windows will come with support for SAGA 7.*

**Comment by ThorstenLWK** [comment]
Thanks again!

**Comment by agiudiceandrea** [comment]
@ThorstenLWK the new Windows MSI installers ship SAGA GIS 7.8.2 and you can already download them from the QGIS download page at https://qgis.org/en/site/forusers/download.html
![image](https://user-images.githubusercontent.com/16253859/115261321-ce364800-a133-11eb-8870-41f62876b48c.png)

**Comment by ThorstenLWK** [comment]
That´s great! Thank you so much for this information. I will try it tomorrow!

**Comment by ThorstenLWK** [comment]
Thanks @ all. The MSI-Version of QGIS 3.18 works for us!

Issue solved.
