### ISSUE TITLE
Label mask settings gets dropped when attribute value contains a comma

### ISSUE THREAD

**Issue by oskarlin** [qgis/QGIS#42868]
**Describe the bug**

Each time I reopen a QGIS file with masking all the categories that has a comma in the attribute name such as "Järnväg med enkelspår, ej elektrifierad" gets dropped.

**How to Reproduce**

1. Style a line layer Categorized based on attributes where it contains a comma. 
2. Mask that layer
3. Close QGIS file
4. Reopen
5. Mask is gone for each layer that has comma in the name

**QGIS and OS versions**
QGIS 3.18.1-Zürich
MacOS 10.15.7

**Additional context**

**Comment by roya0045** [comment]
@gioman This seems to be the same as #37473 despite the title.

**Comment by gioman** [comment]
> @gioman This seems to be the same as #37473 despite the title.

@roya0045 possibly yes, but can't test right now.

**Comment by klakar** [comment]
Yes it is the same as #37473 I changed the title of that one to reflect this since this is the only remaining issue from the original report.

**Comment by nyalldawson** [comment]
Fixed by https://github.com/qgis/QGIS/pull/43318
