### ISSUE TITLE
QGIS Server "Layer(s) not valid" accessing Oracle datasources layer

### ISSUE THREAD

**Issue by lls88** [qgis/QGIS#42864]
Similar to the [issue](https://github.com/qgis/QGIS/issues/37525) , under 
1. Windows 10  64bit 
2. QGIS Server set up: OSGeo4W64
3. Http Apache Server

The qgis-oracle-provider is also installed. But i'm still getting the error in qgis_server.log:
...
WARNING Oracle[12712]: Connection to database failed
CRITICAL Server[12712]: Error, Layer(s) OO_LEITUNGEN_e7f18fd3_2de4_4f2d_8c29_3266abb28a14 not valid in project C:\QGis\world\oracle_lev.qgs
WARNING Oracle[12712]: Connection failed 0s ago - skipping retry
WARNING Server[12712]: <ServerException>Layer(s) not valid</ServerException>
...

**Comment by gioman** [comment]
@lls88 how did you set up the authentication in the QGIS project?

**Comment by elpaso** [comment]
This is not a bug, we are using Oracle in production without issues and I believe it is a configuration/setup issue and that this is not the right place to handle it.

**Comment by lls88** [comment]
> @lls88 how did you set up the authentication in the QGIS project?

I set up a basic authentication for the WMS URL, using the oracle database username and password. Is it right?

**Comment by lls88** [comment]
> This is not a bug, we are using Oracle in production without issues and I believe it is a configuration/setup issue and that this is not the right place to handle it.

Yes, you are right, i must have configured something wrong. Do you have any documentation/guide for me to follow?

**Comment by elpaso** [comment]
Not for windows, sorry.

For Linux:

About authentication: https://docs.qgis.org/3.16/en/docs/user_manual/auth_system/auth_workflows.html#qgis-server-support

This is our working container recipe: https://github.com/g3w-suite/g3w-suite-docker/blob/dev/Dockerfile.qgis-server-oracle.dockerfile
note that you need to download the SDK from oracle and unzip it before building the container, see: https://github.com/g3w-suite/g3w-suite-docker/blob/dev/Dockerfile.qgis-server-oracle.dockerfile#L36-L37
