### ISSUE TITLE
When I export a shp it loses the CRS 

### ISSUE THREAD

**Issue by guisamor** [qgis/QGIS#42861]
Hello!
I am using QGIS 3.18.1 on Windows 10, 
Whenever I export data to a new shapefile (for example only selected features), it doesn't save the .prj file. I need to assign the CRS again.
Thank you.

**Comment by gioman** [comment]
>  Whenever I export data to a new shapefile (for example only selected features), it doesn't save the .prj file. I need to assign the CRS again.

@guisamor weird, can't confirm here. Please try with a new QGIS profile.
