### ISSUE TITLE
QGIS crashing unexpectedly 

### ISSUE THREAD

**Issue by Akshiswdc** [qgis/QGIS#42874]
Crash ID: f2661c87822a2222edf3ebe10235342019bdec73

Stack Trace

QBitArray::QBitArray :
QAction::text :
QgsShortcutsManager::actionByName qgsshortcutsmanager.cpp:295
QgsShortcutsManager::registerAction qgsshortcutsmanager.cpp:89
QgisApp::activateDeactivateLayerRelatedActions qgisapp.cpp:13660
QtPrivate::FunctorCall,QtPrivate::List,void,void (__cdecl QgisApp::*)(QgsMapLayer * __ptr64) __ptr64>::call qobjectdefs_impl.h:134
QtPrivate::FunctionPointer::call,void> qobjectdefs_impl.h:168
QtPrivate::QSlotObject,void>::impl qobjectdefs_impl.h:397
QMetaObject::activate :
QgisApp::activeLayerChanged moc_qgisapp.cpp:2691
QgisApp::onActiveLayerChanged qgisapp.cpp:676
QtPrivate::FunctorCall,QtPrivate::List,void,void (__cdecl QgisApp::*)(QgsMapLayer * __ptr64) __ptr64>::call qobjectdefs_impl.h:134
QtPrivate::FunctionPointer::call,void> qobjectdefs_impl.h:168
QtPrivate::QSlotObject,void>::impl qobjectdefs_impl.h:397
QMetaObject::activate :
QgsLayerTreeView::currentLayerChanged moc_qgslayertreeview.cpp:196
QgsLayerTreeView::onCurrentChanged qgslayertreeview.cpp:276
QtPrivate::FunctorCall,QtPrivate::List,void,void (__cdecl QgsLayerTreeView::*)(void) __ptr64>::call qobjectdefs_impl.h:134
QtPrivate::FunctionPointer::call,void> qobjectdefs_impl.h:168
QtPrivate::QSlotObject,void>::impl qobjectdefs_impl.h:397
QMetaObject::activate :
QItemSelectionModel::setCurrentIndex :
QAbstractItemView::setCurrentIndex :
QgisApp::autoSelectAddedLayer qgisapp.cpp:4665
QtPrivate::FunctorCall,QtPrivate::List const & __ptr64>,void,void (__cdecl QgisApp::*)(QList) __ptr64>::call qobjectdefs_impl.h:134
QtPrivate::FunctionPointer) __ptr64>::call const & __ptr64>,void> qobjectdefs_impl.h:168
QtPrivate::QSlotObject) __ptr64,QtPrivate::List const & __ptr64>,void>::impl qobjectdefs_impl.h:397
QMetaObject::activate :
QgsLayerTreeRegistryBridge::addedLayersToLayerTree moc_qgslayertreeregistrybridge.cpp:165
QgsLayerTreeRegistryBridge::layersAdded qgslayertreeregistrybridge.cpp:77
QtPrivate::FunctorCall,QtPrivate::List const & __ptr64>,void,void (__cdecl QgsLayerTreeRegistryBridge::*)(QList const & __ptr64) __ptr64>::call qobjectdefs_impl.h:134
QtPrivate::FunctionPointer const & __ptr64) __ptr64>::call const & __ptr64>,void> qobjectdefs_impl.h:168
QtPrivate::QSlotObject const & __ptr64) __ptr64,QtPrivate::List const & __ptr64>,void>::impl qobjectdefs_impl.h:397
QMetaObject::activate :
QgsProject::legendLayersAdded moc_qgsproject.cpp:1156
QgsProject::addMapLayers qgsproject.cpp:3136
QgsProject::addMapLayer qgsproject.cpp:3160
meth_QgsProject_addMapLayer sip_corepart3.cpp:35134
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1609
WinMain mainwin.cpp:170
__scrt_common_main_seh exe_common.inl:253
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.11.0-Master
QGIS code revision: 37a4c10a4d
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.0dev
Running against GDAL: 3.1.0dev

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by roya0045** [comment]
@gioman This is clearly a very old custom build or weekly build. I doubt there is anything to do with this..

**Comment by gioman** [comment]
>  QGIS Version: 3.11.0-Master

> @gioman This is clearly a very old custom build or weekly build. I doubt there is anything to do with this..

@Akshiswdc agree, this is way too old. Test again with the latest master, and reopen if the problem persist.
