### ISSUE TITLE
user profile issue

### ISSUE THREAD

**Issue by david4est** [qgis/QGIS#42886]
having installed QGIS 3.16, the top level menu still shows as for 3.4, with no geoprocessing toolbox and several default plugins not loaded (eg, no Vector tools).
Eventually I was able to find my user profile and remove that, so restarting the programme as a totally new user seems to have solved the problem, but clearly would be an issue for anyone with an existing profile.

**Comment by gioman** [comment]
@david4est I fail to understand where is the issue (or how to replicate it): you clearly had a profile with issues, the right move is to use a new one or reset/delete the old one.

**Comment by david4est** [comment]
Dear Giovanni
The point is that things worked perfectly well in QGIS 3.4. Updating to 3.16, the core seemed to work fine, but when I went on to do some more advanced tasks the tools were not available to me and their did not seem to be any simple way to install them.

I appreciate this is an issue with the user profile, which seems to have been retained from 3.4, but if you update a system it is reasonable to expect it to be updated correctly. There is no warning that you need to delete any existing user profile (which was not removed when the earlier version was uninstalled – thus not a complete uninstall) and create a new one.

I have not had similar issues with previous updates to QGIS.

Regards
David

__________________________________
David Forrest PhD, FBCart.S
Senior Lecturer
School of Geographical & Earth Sciences
University of Glasgow, Glasgow G12 8QQ

Please note that I sometimes work outside normal working hours, but do not expect responses out of hours.

For some a map is just a piece of paper
For others it is a passport to adventure …

***@***.***D736B5.D2AAFA40]

The University of Glasgow, charity number SC004401

**Comment by gioman** [comment]
> The point is that things worked perfectly well in QGIS 3.4. Updating to 3.16, the core seemed to work fine, but when I went on to do some more advanced tasks the tools were not available to me and their did not seem to be any simple way to install them.

@david4est I understand, but this do not seems to be a general issue. Is probably something related to your specific old profile, and so seems there is not much we can do (unless this is replicable in a consistent way, which I don't think it is).

**Comment by DelazJ** [comment]
@david4est The fix would have been to reenable the processing plugin. No need to remove the profile, here.
@gioman I don't know if it's that specific. During the last weeks, this is the third time someone is not finding the processing tools that seemed to be there beforehand. At least one mentions that he reinstalls 3.16 so maybe there's something in the upgrade that deactivates processing? Or processing is meant to be deactivated upon installation, regardless previous status?
