### ISSUE TITLE
Hello! I am using QGIS 3.16.3 on Windows 10,  Not displayed the bin grid Shapefile in Qgis. What is the problem.

### ISSUE THREAD

**Issue by Yurii101** [qgis/QGIS#42882]
Hello!
I am using QGIS 3.16.3 on Windows 10,
Not displayed the bin grid Shapefile in Qgis. What is the problem.

this Shapefile is here  
[bin_grid.zip](https://github.com/qgis/QGIS/files/6348887/bin_grid.zip)

**Comment by gioman** [comment]
@Yurii101 as a start, the DBF file is empty.
