### ISSUE TITLE
QGIS 3.16.6 Crashing

### ISSUE THREAD

**Issue by vkagz** [qgis/QGIS#42892]
This is now the fifth time the application has crashed today, while am cleaning my data by deleting the unwanted parts and adding the missing ones. 
Is there a way out, coz it sure is annoying!

Attached below is the Error Code

## Report Details

**Crash ID**: [96bbd39510097c91a859fca5778d6cb090824ec5](https://github.com/qgis/QGIS/search?q=96bbd39510097c91a859fca5778d6cb090824ec5&type=Issues)

**Stack Trace**
<pre>
QgsGeometry::closestSegmentWithContext qgsgeometry.cpp:662
QgsPointLocator_VisitorNearestEdge::visitData qgspointlocator.cpp:275
Index::~Index :
Index::~Index :
QgsPointLocator::nearestEdge qgspointlocator.cpp:1224
_updateBestMatch qgssnappingutils.cpp:218
QgsSnappingUtils::snapToMap qgssnappingutils.cpp:395
QgsMapMouseEvent::snapPoint qgsmapmouseevent.cpp:52
QgsMapToolAdvancedDigitizing::canvasMoveEvent qgsmaptooladvanceddigitizing.cpp:111
QgsMapCanvas::mouseMoveEvent qgsmapcanvas.cpp:1998
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.16.6-Hannover
QGIS code revision: bfd36fddc9
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.16299

**Comment by gioman** [comment]
> Is there a way out

@vkagz 1) please try on a new QGIS profile, no 3rd party plugins installed. 2) if the problem persist then describe in **detail** the necessary steps to replicate attaching the necessary sample project/data.

**Comment by roya0045** [comment]
It is highly possible that the crashes are partly caused by your data. Reducing the number of layers or disabling snapping might solve the issue. Otherwise if you find the offending layer and you are able to share it that might help. Snapping might get some changes soon, that may or may not help.

**Comment by vkagz** [comment]
@roya0045 and @gioman, Thanks for the feedback, I will give both suggestions a try and revert ones succeful
