### ISSUE TITLE
Add the option of temporary layer output to batch processes

### ISSUE THREAD

**Issue by garvamel** [qgis/QGIS#42897]
An example is for instance reprojecting multiple layers. In single run mode reprojecting a layer creates a temporary layer unless set otherwise. In batch mode you are forced to output to a file, even if you don't need that. If you're working with Geopackages it's even more problematic because you can't name the output layer, only the file, so you either:

- overwrite previous runs of the batch
- create one gpkg per layer

Thanks a lot in advance.

**Comment by garvamel** [comment]
> Somewhat duplicate of #27858 Though maybe the geopackage thing could be a bug, didn't check if one existed.

Thanks, yeah it's pretty similar. I did not find it when I searched before posting.

**Comment by gioman** [comment]
Closing as duplicate then.

**Comment by roya0045** [comment]
@garvamel I suggest a new one. The old one is for temporal outputs.

**Comment by mblesius** [comment]
@garvamel Both options you mentioned (output as temporary layers and as individual tables in a geopackage) are already possible, but not well documented - I was also confronted with these problems.

If you want to load the output of the batch processing into temporary layers you can specify just `TEMPORARY_OUTPUT` in the output field. Don't forget to check 'Load layers on completion' then.

If you want to save the output into separate new geopackage layers/tables, you need to specify it in the following syntax:
`ogr:dbname='C:/Path/To/Geopackage.gpkg' table="New_Table" (geom)`
I have described this in more detail in this Stackexchange post: [https://gis.stackexchange.com/questions/373758/](https://gis.stackexchange.com/questions/373758/)

**Comment by garvamel** [comment]
> @garvamel Both options you mentioned (output as temporary layers and as individual tables in a geopackage) are already possible, but not well documented - I was also confronted with these problems.
> 
> If you want to load the output of the batch processing into temporary layers you can specify just `TEMPORARY_OUTPUT` in the output field. Don't forget to check 'Load layers on completion' then.
> 
> If you want to save the output into separate new geopackage layers/tables, you need to specify it in the following syntax:
> `ogr:dbname='C:/Path/To/Geopackage.gpkg' table="New_Table" (geom)`
> I have described this in more detail in this Stackexchange post: https://gis.stackexchange.com/questions/373758/

Brilliant! thanks. Seems unnecessary difficult/obscure right now haha!

**Comment by AlisterH** [comment]
> Brilliant! thanks. Seems unnecessary difficult/obscure right now haha!

I agree.  For temporary outputs here is a simple solution which would make it obvious:
Even in the normal interface (i.e. not running as batch) specifying TEMPORARY_OUTPUT seems to work.  So I would have thought that instead of showing the placeholder text `[create temporary layer]`, it would make sense to just put TEMPORARY_OUTPUT there by default.  Is there any reason this would be a bad idea?

Still in the normal interface, I notice that as well as "Save to File...", the dropdown has an entry for "Save to Geopackage", which asks you for a layername as well as a filename, and builds the string and puts it in the field.  This doesn't seem to obscure, but I still managed to overlook it.

**Comment by AlisterH** [comment]
The dropdown also has an option "Skip output".  Is there any way to specify it in the batch interface?  I tried `SKIP_OUTPUT` and `SKIP` but they don't work.

**Comment by AlisterH** [comment]
> The dropdown also has an option "Skip output". Is there any way to specify it in the batch interface? I tried `SKIP_OUTPUT` and `SKIP` but they don't work.

Oh, of course.  This is default in the batch interface - you just leave it blank.

**Comment by garvamel** [comment]
@AlisterH another question. Is it possible to name the temporary layer in the batch dialog? I have tried many syntaxes and combinations to no avail.

Thanks!
