### ISSUE TITLE
3.18.2 Setup fails to create executable file in startup folder.

### ISSUE THREAD

**Issue by SiteGuy67** [qgis/QGIS#42895]
**Describe the bug**

**How to Reproduce**

1. Download and launch QGIS-OSGeo4W-3.18.2-Setup-x86_64.exe
2. After installation program completes, go to Start>QGIS 3.18
3. Executable program file has not been installed (missing)

**QGIS and OS versions**

**Additional context**

**Comment by roya0045** [comment]
What windows version?

**Comment by SiteGuy67** [comment]
Windows 10.

I've been able to successfully install previous versions.

**Comment by gioman** [comment]
@SiteGuy67 works fine here, on my Windows 10 machine. Probably some local issue (antivirus or similar).
