### ISSUE TITLE
QGIS 3.18 Properties dialog box fixed in place to project window

### ISSUE THREAD

**Issue by JCH-H** [qgis/QGIS#42891]
**Describe the bug**
The layer properties dialog box opens in a fixed position relative to a grayed out project window.  After making changes to the layer properties (ie, changing polygon symbology), you cannot move the properties dialog box away from the project window to see the changes after using the [apply] button.  If you grab the properties dialog box and attempt to move it, the entire QGIS project window moves. If the QGIS project window is maximized, moving the properties dialog box de-maximizes the QGIS project window. You have to close the properties dialog to see the changes, unless the changes are visible around the periphery of the dialog box on the screen.

**How to Reproduce**

**QGIS and OS versions**

QGIS version | 3.18.2-Zürich | QGIS code revision | 515138c171
-- | -- | -- | --
Compiled against Qt | 5.14.2 | Running against Qt | 5.14.2
Compiled against GDAL/OGR | 3.1.3 | Running against GDAL/OGR | 3.1.3
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.33.0 | Running against SQLite | 3.33.0
Compiled against PDAL | 2.1.0 | Running against PDAL | 2.1.0 (git-version: Release)
PostgreSQL Client Version | 12.6 (Ubuntu 12.6-0ubuntu0.20.10.1) | SpatiaLite Version | 5.0.0
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 7.1.0 | Running against PROJ | Rel. 7.1.0, August 1st, 2020
OS Version | Ubuntu 20.10
Active python plugins | clipper; DigitizingTools; processing; MetaSearch; db_manager

**Additional context**

**Comment by nirvn** [comment]
That's the way gnome handles blocking dialogs. You can Google how to tweak this behavior online. Cheers.

**Comment by gioman** [comment]
@JCH-H this is likely to be a problem with the Ubuntu Desktop manager, not QGIS.

**Comment by JCH-H** [comment]
Thanks for the replies, I did just switch back to Ubuntu from Xubuntu when I installed Qgis 3.18 so I'm back to gnome which I haven't used for awhile.  Since it wasn't happening with the attributes window, I thought it was  an issue specific to the properties dialog.  I'll check the settings in gnome.
