### ISSUE TITLE
Open csv file

### ISSUE THREAD

**Issue by walteromero** [qgis/QGIS#42898]
## User Feedback

Open csv file

## Report Details

**Crash ID**: [01457128af6c3f21bb938ae20f253068336759e0](https://github.com/qgis/QGIS/search?q=01457128af6c3f21bb938ae20f253068336759e0&type=Issues)

**Stack Trace**
<pre>
QBitArray::QBitArray :
QgsMultiRenderChecker::report qgsmultirenderchecker.h:126
QgsRuleBasedRenderer::convertFromRenderer qgsrulebasedrenderer.cpp:1314
meth_QgsRuleBasedRenderer_convertFromRenderer sip_corepart2.cpp:110753
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QMetaObject::activate :
QgisInterface::currentLayerChanged moc_qgisinterface.cpp:817
QMetaObject::activate :
QgisApp::activeLayerChanged moc_qgisapp.cpp:2800
QgisApp::onActiveLayerChanged qgisapp.cpp:717
QMetaObject::activate :
QgsLayerTreeView::currentLayerChanged moc_qgslayertreeview.cpp:307
QgsLayerTreeView::onCurrentChanged qgslayertreeview.cpp:322
QMetaObject::activate :
QItemSelectionModel::setCurrentIndex :
QAbstractItemView::setCurrentIndex :
QgisApp::autoSelectAddedLayer qgisapp.cpp:4928
QtPrivate::QSlotObject<void (__cdecl QgisApp::*)(QList<QgsMapLayer * __ptr64>) __ptr64,QtPrivate::List<QList<QgsMapLayer * __ptr64> const & __ptr64>,void>::impl qobjectdefs_impl.h:403
QMetaObject::activate :
QgsLayerTreeRegistryBridge::addedLayersToLayerTree moc_qgslayertreeregistrybridge.cpp:165
QgsLayerTreeRegistryBridge::layersAdded qgslayertreeregistrybridge.cpp:77
QMetaObject::activate :
QgsProject::legendLayersAdded moc_qgsproject.cpp:1210
QgsProject::addMapLayers qgsproject.cpp:3424
QgisApp::addVectorLayerPrivate qgisapp.cpp:13086
QgisApp::addVectorLayer qgisapp.cpp:6413
QgisApp::qt_static_metacall moc_qgisapp.cpp:1721
QMetaObject::activate :
QgsDataSourceManagerDialog::addVectorLayer moc_qgsdatasourcemanagerdialog.cpp:370
QtPrivate::FunctorCall<QtPrivate::IndexesList<0,1,2>,QtPrivate::List<QString const & __ptr64,QString const & __ptr64,QString const & __ptr64>,void,<lambda_09e39cf3592f0a26046776ba7602a513> >::call qobjectdefs_impl.h:128
QMetaObject::activate :
QgsAbstractDataSourceWidget::addVectorLayer moc_qgsabstractdatasourcewidget.cpp:331
QgsDelimitedTextSourceSelect::addButtonClicked qgsdelimitedtextsourceselect.cpp:220
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:475
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:475
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1638
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.18.2-Z�rich
QGIS code revision: 515138c171
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

**Comment by roya0045** [comment]
Stack trace tells a different story, anything reproducible that you can share?

**Comment by walteromero** [comment]
*Lic. Walter Orlando Romero*
http://linkedin.com/in/walteromero
*Informatica(Proyectos, Desarrollos).
*MapInfo and Oracle Spatial Consulting.
*Open Source, Web and Mobile GIS.
Cel: 595-971284088



***@***.***>

**Comment by roya0045** [comment]
@walteromero I suggest to respond on github directly, your reply contained nothing other than your signature.

**Comment by gioman** [comment]
> Open csv file

@walteromero please try with a new QGIS profile, if the problem persist add the detailed steps to replicate, and link/attach the dataset.
