### ISSUE TITLE
"Reuse last entered attribute values" slows creation of new features on large vector

### ISSUE THREAD

**Issue by Kereboraskal** [qgis/QGIS#42909]
**Describe the bug**

Good morning,
working on vector layers (tested with polygons) with a lot of features (millions), I noticed that the digitising setting "Reuse last entered attribute values" slows the creation of new features.
I tried on my data and also on OSM data.
After the creation of the first polygon, when I create another one and finalise the editing with the right-click of the mouse, it takes a long time before showing up the Feature Attributes dialog (tents of seconds), QGIS hangs, and I also noticed a burst use of RAM by QGIS (jumping from around 700 MB to more than 2.5 GB).
If I turn off "Reuse last entered attribute values", the polygons are created instantly, with no delay.
Here’s the link for data test and RAM screenshots first, during and after the creation of a feature with "Reuse last entered attribute values" turned on: https://drive.google.com/drive/folders/1fw0vrzLoak8aU5Hv7uJZAGIPIvKiO0Z3?usp=sharing

**QGIS and OS versions**

QGIS 3.16.5 - WIN 10 PRO 20H2

Versione di QGIS | 3.16.5-Hannover | Revisione codice QGIS | 58ba7c1ed6
-- | -- | -- | --
Compilato con Qt | 5.11.2 | Esecuzione con Qt | 5.11.2
Compilato con GDAL/OGR | 3.1.4 | Esecuzione con GDAL/OGR | 3.1.4
Compilato con GEOS | 3.8.1-CAPI-1.13.3 | Esecuzione con GEOS | 3.8.1-CAPI-1.13.3
Compilato su SQLite | 3.29.0 | In esecuzione su SQLite | 3.29.0
Versione client PostgreSQL | 11.5 | Versione SpatiaLite | 4.3.0
Versione QWT | 6.1.3 | Versione QScintilla2 | 2.10.8
Compilato con PROJ | 6.3.2 | Esecuzione con PROJ | Rel. 6.3.2, May 1st, 2020
Versione SO | Windows 10 (10.0)
Attiva python plugin | Go2NextFeature3; plugin_reloader; qgis2web; QMetaTiles; QuickMultiAttributeEdit3; QuickWKT; quick_map_services; StreetView; db_manager; MetaSearch; processing

**Additional context**

Thanks

**Comment by gioman** [comment]
Also seen on Master on Ubuntu 20.04.

**Comment by roya0045** [comment]
That is strange. The operations used are fairlight straghtforward and the cache should not be affected by the layer size as the values are stored and replaced [in the cache](https://github.com/qgis/QGIS/blob/2d1aa68f0d044f2aced7ebeca8d2fa6b754ac970/src/app/qgsfeatureaction.cpp#L37).

**Comment by roya0045** [comment]
@gioman Nyall added some stuff in early march, does your version of master contain these changes?

**Comment by gioman** [comment]
> @gioman Nyall added some stuff in early march, does your version of master contain these changes?

I install from qgis.org's repo, so I would say yes.
