### ISSUE TITLE
Point Cloud data not shown

### ISSUE THREAD

**Issue by tz2436** [qgis/QGIS#42915]
**Describe the bug**

After drag in the las file, there is only a red extent boundary shown. There is a ept_filename folder created but nothing's inside. 

![Screen Shot 2021-04-22 at 1 24 38 PM](https://user-images.githubusercontent.com/61794189/115759522-543dd300-a36e-11eb-8a26-07ac676bb42a.png)
<img width="183" alt="Screen Shot 2021-04-22 at 1 25 02 PM" src="https://user-images.githubusercontent.com/61794189/115759534-57d15a00-a36e-11eb-8d18-f99d4f4b4527.png">

Tried to open the same file in QGIS 3.18.2 on Win10, it generates thousands of laz files which can be shown when added to QGIS on MacOS system.

Wonder if the las file's too heavy (2GB), it failed to run on MacOS system but succeded on Win10

**How to Reproduce**

Add the file

**QGIS and OS versions**

QGIS version | 3.18.1-Zürich | QGIS code revision | 202f1bf7e5
-- | -- | -- | --
Compiled against Qt | 5.14.2 | Running against Qt | 5.14.2
Compiled against GDAL/OGR | 3.2.1 | Running against GDAL/OGR | 3.2.1
Compiled against GEOS | 3.9.1-CAPI-1.14.2 | Running against GEOS | 3.9.1-CAPI-1.14.2
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
Compiled against PDAL | 2.2.0 | Running against PDAL | 2.2.0 (git-version: Release)
PostgreSQL Client Version | 12.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.4
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | macOS Mojave (10.14)

**Additional context**

**Comment by nicogodet** [comment]
On Windows, the LAS file was also on OneDrive ?

Try to copy your file to another folder and make sur there is no space or special character in the file path.
For ex: copy it in the root folder of your user (/Users/zhangting)

**Comment by tz2436** [comment]
Thanks for the reply! I copied the file to desktop and it works! 
Now it opens another issue that QGIS crashs when I tried to create a 3D Map View #42928

**Comment by nicogodet** [comment]
Initial issue is similar to https://github.com/qgis/QGIS/issues/41833
