### ISSUE TITLE
Crashing when accessing Raster properties

### ISSUE THREAD

**Issue by cavrinceanu** [qgis/QGIS#42911]
## User Feedback

Crashing as I was trying to open raster properties.

## Report Details

**Crash ID**: [e8f1ed9419bee0a2ab02d8faa4992dfc7ef4d285](https://github.com/qgis/QGIS/search?q=e8f1ed9419bee0a2ab02d8faa4992dfc7ef4d285&type=Issues)

**Stack Trace**
<pre>
QObject::parent :
QLayout::addChildWidget :
QStackedLayout::insertWidget :
QgsRasterLayerProperties::addPropertiesPageFactory qgsrasterlayerproperties.cpp:561
QgisApp::showLayerProperties qgisapp.cpp:16271
QgisApp::layerProperties qgisapp.cpp:9296
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:475
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:475
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QMenu::exec :
QgsLayerTreeView::contextMenuEvent qgslayertreeview.cpp:187
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:475
QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:475
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1638
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.18.1-Z�rich
QGIS code revision: 202f1bf7e5
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
@cavrinceanu pleae try with a new QGIS profile, no 3rd party plugins installed (the issue is likely to be a 3rd party plugin).

**Comment by cavrinceanu** [comment]
Seems so. Works clean with a second profile. Thank you! Is there any 3rd party plugin already reported to cause problems? If not, I guess I can close this issue.

**Comment by gioman** [comment]
> Is there any 3rd party plugin already reported to cause problems?

@cavrinceanu you have to figure it out by yourself, by reinstalling one by one your plugins, then warn the author/s.

**Comment by cavrinceanu** [comment]
Thank you! Of course. I was just wondering since I have a lot installed and  perhaps someone reported it earlier. Cheers for the fast help!
