### ISSUE TITLE
Using the mousewheel to zoom in on large hdf5 file crashes QGIS

### ISSUE THREAD

**Issue by ramotswa** [qgis/QGIS#42926]
**Describe the bug**
Zooming in on a roughly 700mb hdf5 file in QGIS causes a crash. 

**How to Reproduce**

1. Download 
--https://e4ftl01.cr.usgs.gov/ECOSTRESS/ECO2LSTE.001/2021.03.04/ECOSTRESS_L2_LSTE_15075_008_20210304T044211_0601_01.h5--
(Updated link:
https://satellitevu-sample.s3.eu-west-2.amazonaws.com/ECOSTRESS_L2_LSTE_15075_008_20210304T044211_0601_01.h5)
2. Open QGIS
3. Drag .h5 file from above into viewer.
4. Select the '//SDS/LST' Raster Layer
5. Click ok.
6. Zoom in using mouse wheel. 
7. QGIS crashes straight away.

Using the manual 'draw a box to zoom ' tool seems to work. However at any zoom level using the mousewheel to zoom crashes QGIS.

**QGIS and OS versions**
QGIS version | 3.18.1-Zürich | QGIS code revision | 202f1bf7e5
-- | -- | -- | --
Compiled against Qt | 5.14.2 | Running against Qt | 5.14.2
Compiled against GDAL/OGR | 3.2.1 | Running against GDAL/OGR | 3.2.1
Compiled against GEOS | 3.9.1-CAPI-1.14.2 | Running against GEOS | 3.9.1-CAPI-1.14.2
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
Compiled against PDAL | 2.2.0 | Running against PDAL | 2.2.0 (git-version: Release)
PostgreSQL Client Version | 12.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.4
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | macOS 10.15.7
Active python plugins | FreehandRasterGeoreferencer; Unfolded; clipper; vector_tiles_reader; QNEAT3; GeoCoding; QuickWKT; rasterstats; Qgis2threejs; processing; db_manager; MetaSearch

**Comment by gioman** [comment]
@ramotswa please try with a new QGIS profile, no 3rd party plugins installed.

**Comment by ramotswa** [comment]
Confirmed.
Blank Profile created. 

QGIS Info;

QGIS version | 3.18.1-Zürich | QGIS code revision | 202f1bf7e5
-- | -- | -- | --
Compiled against Qt | 5.14.2 | Running against Qt | 5.14.2
Compiled against GDAL/OGR | 3.2.1 | Running against GDAL/OGR | 3.2.1
Compiled against GEOS | 3.9.1-CAPI-1.14.2 | Running against GEOS | 3.9.1-CAPI-1.14.2
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
Compiled against PDAL | 2.2.0 | Running against PDAL | 2.2.0 (git-version: Release)
PostgreSQL Client Version | 12.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.4
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | macOS 10.15
Active python plugins | processing; db_manager; MetaSearch


Same error experienced.

**Comment by gioman** [comment]
>     1. Download https://e4ftl01.cr.usgs.gov/ECOSTRESS/ECO2LSTE.001/2021.03.04/ECOSTRESS_L2_LSTE_15075_008_20210304T044211_0601_01.h5

@ramotswa this is link is password protected.

**Comment by ramotswa** [comment]
Apologies - file available here:
https://satellitevu-sample.s3.eu-west-2.amazonaws.com/ECOSTRESS_L2_LSTE_15075_008_20210304T044211_0601_01.h5

**Comment by gioman** [comment]
> Apologies - file available here:

@ramotswa what is the CRS of those layers? the load with no CRS and this may e very well the cause of the problem you see.

**Comment by gioman** [comment]
And also... no crash on 3.18/master on Linux.

**Comment by ramotswa** [comment]
@gioman  - 
That looks correct - there isn't any CRS data on these files:
gdalinfo output:

`Driver: HDF5Image/HDF5 Dataset
Files: ECOSTRESS_L2_LSTE_15075_008_20210304T044211_0601_01.h5
Size is 5400, 5632
Corner Coordinates:
Upper Left  (    0.0,    0.0)
Lower Left  (    0.0, 5632.0)
Upper Right ( 5400.0,    0.0)
Lower Right ( 5400.0, 5632.0)
Center      ( 2700.0, 2816.0)
Band 1 Block=5400x1 Type=UInt16, ColorInterp=Undefined
  Metadata:
    SDS_LST_add_offset=0
    SDS_LST_coordsys=cartesian
    SDS_LST_format=scaled
    SDS_LST_long_name=Land Surface Temperature
    SDS_LST_scale_factor=0.02
    SDS_LST_units=K
    SDS_LST_valid_range=7500 65535
    SDS_LST__FillValue=0`

**Comment by gioman** [comment]
Actually in my testing mac mini with Catalina is even worst, it crashes when adding the datasource to the project. Does not happen on Linux and Windows.
