### ISSUE TITLE
Cannot order a xls table added to a print layout

### ISSUE THREAD

**Issue by admfarias** [qgis/QGIS#42927]
Estou tentando fazer a ordenação de forma descendente dentro de tabela de atributos >> atributos... e o mesmo não aceita quando eu coloco a ordenação por dados 123 de forma descendente ou ascendente a partir de uma tabela importada  do excel.

**Comment by admfarias** [comment]
versão 3.16.6 e 3.18

**Comment by gioman** [comment]
@admfarias tickets must be posted in english. Please edit the post translating title and desciption, obrigado!

**Comment by gioman** [comment]
@admfarias also search the bug tracker, I think there is already a similar report open.

**Comment by admfarias** [comment]
Sorry, I am trying to do the descending sorting within the attributes table >> attributes ... and the same does not accept when I place the sorting by data 123 in a descending or ascending way from a table imported from excel. Version 3.16.6 e 3.18...

**Comment by roya0045** [comment]
Hard to know that is the issue as it may be data specific.

**Comment by gioman** [comment]
> and the same does not accept when I place the sorting by data 123 in a descending or ascending way from a table imported from excel. Version 3.16.6 e 3.18...

@admfarias can you please attach a small sample project+data that shows the issue? thanks.
