### ISSUE TITLE
RuntimeError: Cannot find any suitable spatialite module 

### ISSUE THREAD

**Issue by Eduardo-deJuan** [qgis/QGIS#42925]
When trying to verify DB connection state with the DB Adm tool I get the following Python error

**> Ha ocurrido un error mientras se ejecutaba el código de Python: 
> 
> RuntimeError: Cannot find any suitable spatialite module 
> Traceback (most recent call last):
>   File "/usr/share/qgis/python/plugins/db_manager/db_model.py", line 456, in rowCount
>     self._refreshIndex(parent, True)
>   File "/usr/share/qgis/python/plugins/db_manager/db_model.py", line 505, in _refreshIndex
>     if item.populate():
>   File "/usr/share/qgis/python/plugins/db_manager/db_model.py", line 182, in populate
>     if not connection.connect():
>   File "/usr/share/qgis/python/plugins/db_manager/db_plugins/spatialite/plugin.py", line 78, in connect
>     return self.connectToUri(uri)
>   File "/usr/share/qgis/python/plugins/db_manager/db_plugins/plugin.py", line 142, in connectToUri
>     self.db = self.databasesFactory(self, uri)
>   File "/usr/share/qgis/python/plugins/db_manager/db_plugins/spatialite/plugin.py", line 64, in databasesFactory
>     return SLDatabase(connection, uri)
>   File "/usr/share/qgis/python/plugins/db_manager/db_plugins/spatialite/plugin.py", line 107, in __init__
>     Database.__init__(self, connection, uri)
>   File "/usr/share/qgis/python/plugins/db_manager/db_plugins/plugin.py", line 267, in __init__
>     self.connector = self.connectorsFactory(uri)
>   File "/usr/share/qgis/python/plugins/db_manager/db_plugins/spatialite/plugin.py", line 110, in connectorsFactory
>     return SpatiaLiteDBConnector(uri)
>   File "/usr/share/qgis/python/plugins/db_manager/db_plugins/spatialite/connector.py", line 51, in __init__
>     self.connection = spatialite_connect(self._connectionInfo())
>   File "/usr/share/qgis/python/qgis/utils.py", line 684, in spatialite_connect
>     raise RuntimeError("Cannot find any suitable spatialite module")
> RuntimeError: Cannot find any suitable spatialite module
> 
> 
> Versión de Python: 3.6.12 (default, Dec 02 2020, 09:44:23) [GCC] 
> Versión de QGIS: 3.18.2-Zürich Zürich, exported 
> 
> Ruta de Python:
> /usr/share/qgis/python
> /home/gloriyedu/.local/share/QGIS/QGIS3/profiles/default/python
> /home/gloriyedu/.local/share/QGIS/QGIS3/profiles/default/python/plugins
> /usr/share/qgis/python/plugins
> /usr/lib/python36.zip
> /usr/lib64/python3.6
> /usr/lib64/python3.6/lib-dynload
> /usr/lib64/python3.6/site-packages
> /usr/lib64/python3.6/_import_failed
> /usr/lib/python3.6/site-packages
> /home/gloriyedu/.local/share/QGIS/QGIS3/profiles/default/python
> D:\eclipse\plugins\org.python.pydev_6.2.0.201711281614\pysrc**

Issue happens when clicking on the date base as shown in the following picture.

![image](https://user-images.githubusercontent.com/73610469/115838425-f5ce2e80-a419-11eb-9d45-ea5194c4974c.png)

This happens with both QGIS version 3.16 & 3.18

I'm running OpenSUSE Leap 15.2, x86_64 with KDE

BR, Eduardo

**Comment by gioman** [comment]
@Eduardo-deJuan this seems really a local issue... not a QGIS problem.

**Comment by Eduardo-deJuan** [comment]
Hi all
Yes, It looks more like an installation issue.
I opened this issue also on the OpenSuse forum web page and Marel found that the problem is solved adter creating a missing link 
`sudo ln -s /usr/lib64/mod_spatialite.so.7 /usr/lib64/mod_spatialite.so
`
I don't know if the OpenSuse packaging guys will take this into their lap.

Here is the link to the OpenSuse forum in case it's of interest 
[QGIS Python error "RuntimeError: Cannot find any suitable spatialite module](https://forums.opensuse.org/showthread.php/553074-QGIS-Python-error-quot-RuntimeError-Cannot-find-any-suitable-spatialite-module-quot)

BR, Eduardo
