### ISSUE TITLE
document for `qgis.utils` module

### ISSUE THREAD

**Issue by zacwang89** [qgis/QGIS#42936]
**Feature description.**

There are some useful functions and variables in `qgis.utils` module, but I can't find any information in neither QGIS nor pyqgis API documentations.

Someone else was also looking for the documentation on [gis.stackexchange.com](https://gis.stackexchange.com/questions/203842/seeking-documentation-for-qgis-utils-module).

So can somebody add at least a brief introduction for this module?

Cheers

**Comment by roya0045** [comment]
You're talking about utils.py? That's mostly for internal use, though everything is descriptive and short enough that documentation doesn't seem too warranted. Some even have minimal doc already.

**Comment by zacwang89** [comment]
Hi @roya0045,

Yes, I'm talking about utils.py.
Can I ask where to find such documentation rather than in the utils.py file itself?

**Comment by roya0045** [comment]
The files itself has some functions lightly documented. I don't think they are in the pyqgis cookbook.

**Comment by nicogodet** [comment]
I think it could be useful to list those functions in PyQgis doc website.
It's more intuitive to search in https://qgis.org/pyqgis/master/index.html rather than directly in utils.py file.
