### ISSUE TITLE
Frames from exported animations don't match the frames shown in the temporal controller

### ISSUE THREAD

**Issue by pwicks86** [qgis/QGIS#42932]
**Describe the bug**

The first frame in the temporal explorer does not match the first frame when saving a temporal animation. 

**How to Reproduce**

See attached [zip](https://github.com/qgis/QGIS/files/6367734/simple-test-case.zip)
1. Note that you can step through the frames in the temporal controller and there are 3 frames, one with each shape, square, oval, hexagon.
2. Export the animation.
3. The first frame with the square is missing, instead frame one shows the oval and there are 2 frames with no shapes at the end, rather than the one we see in the temporal controller in the UI.

**QGIS and OS versions**

QGIS version | 3.19.0-Master | QGIS code revision | 1db625b8
-- | -- | -- | --
Qt version | 5.12.8
Python version | 3.8.5
GDAL/OGR version | 3.0.4
PROJ version | 6.3.1
EPSG Registry database version | v9.8.6 (2020-01-22)
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
SQLite version | 3.31.1
PostgreSQL client version | 12.6 (Ubuntu 12.6-0ubuntu0.20.04.1)
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.2
OS version | Ubuntu 20.04.2 LTS
  |   |   |  
This copy of QGIS writes debugging output.
  |   |   |  
Active Python plugins | db_managerprocessingMetaSearch

**Additional context**

From a bit of digging through the code, it looks like the issue is that `currentFrame` is incremented at the beginning of the loop [here](https://github.com/qgis/QGIS/blob/master/src/core/qgstemporalutils.cpp#L119) rather than at the end. I've made that change locally and it seems to fix this issue, but it's certainly possible that I'm missing something. That said, I'm happy to submit a PR for this if that would be useful.

**Comment by nyalldawson** [comment]
@pwicks86 good catch! Can you submit a pr with your change?

**Comment by pwicks86** [comment]
No problem #42934.
