### ISSUE TITLE
QGIS Server: Published WMTS layer displayed with offset 

### ISSUE THREAD

**Issue by andreassteffens** [qgis/QGIS#42942]
Hi,

i'm using QGIS Server 3.16.6 and am trying to publish an orthophoto layer as WMTS. Unfortunately, when i feed the WMTS layer  back into the original project used for publishing it there is a significant offset between the original orthophoto layer and the tiles from service.

I have been trying for some time to figure out if i have configured something wrong .... but came up with nothing. Hence my attempt to post this as an issue ... maybe even a bug.

I've attached ...

- the QGIS project containing the DOP layer i want to publish
- WMTS GetCapabilities document produced by QGIS Server
- screenshot displaying the offset between the original DOP and the tiles published through QGIS Server
- GeoPackage with the coordinates of the reference points displayed in the screenshot

[2021-04-25_issue_project_data.zip](https://github.com/qgis/QGIS/files/6371675/2021-04-25_issue_project_data.zip)

**Comment by andreassteffens** [comment]
One thing striking me about the server's GetCapabilities response for the WMTS was the BoundingBox of the published WMTS layer in CRS EPSG:25832:

`
<ows:BoundingBox crs="EPSG:25832">
    <ows:LowerCorner>660109.327 5293315.749</ows:LowerCorner>
    <ows:UpperCorner>685023.269 5326691.16</ows:UpperCorner>
</ows:BoundingBox>
`

I figured this is supposed to match the bounding box of the layer which natively is in EPSG:25832

`661000.0000000000000000,5294000.0000000000000000 : 684000.0000000002328306,5326000.0000000000000000`

After looking at the code of the WMTS service i guessed this inaccuracy occurs because the layer's bounding box is initially converted to WGS84 and then back to EPSG:25832. After firing up my own QGIS-dev environment and making some changes to the WMTS service (basically skipping chained coordinate transformations if they aren't necessary) the BoudingBox does indeed match layer's native extent.

While this doesn't fix the rendering problem discribed in the original post at least QGIS stops complaining about missing tiles:

![image](https://user-images.githubusercontent.com/46336892/116045208-1c86a200-a672-11eb-84f4-89827afd0505.png)

**Comment by elpaso** [comment]
@rldhont do you have any clue on this issue?

**Comment by elpaso** [comment]
Maybe related to #39040 ?

**Comment by rldhont** [comment]
It is probably the same issue and I have no clue.

The WMTS is only a wrapper around WMS so WMTS parameters has been translated into WMS parameters. There is probably something wrong when calculating BBOX and provide it as string.

**Comment by andreassteffens** [comment]
I think the problem might not be the request translation but the correct initialization of the `tileMatrixInfo` structure. When i publish the WMTS in Pseudo Mercator the tiles are displayed without any visible offset. The result is of course not really satisfying. Tiles are generated by tranforming raster data from EPSG:25832 to Pseudo Mercator and are transformed back to EPSG:25832 by QGIS upon display which results in quite fuzzy raster display.

The difference with respect to the initialization of `tileMatrixInfo` structure is that it's values are hardcoded for Pseudo Mercator in wmtsutils.cpp. For all other coordinate systems the resolution is calculated on the fly based on the minimum scale denominator of the grid definition, the CRS's extent and a couple of other values. Removing the hardcoded initialization for Pseudo Mercator causes QGIS Server to also calculate the values on the fly .... resulting in a different resolution than the one that is hardcoded. Using the resolution that has been calculated on the fly tiles in Pseudo Mercator are also no longer displayed correctly.

**Comment by andreassteffens** [comment]
So changing the line

`resolution = POINTS_TO_M * minScale / QgsUnitTypes::fromUnitToUnitFactor( tmi.unit, QgsUnitTypes::DistanceMeters );`

in wmtsutils.cpp to

```
double inchPerMeter = 39.37;
resolution = minScale / (QgsUnitTypes::fromUnitToUnitFactor(tmi.unit, QgsUnitTypes::DistanceMeters) * inchPerMeter * 90.71428571429);
```

appears to do the trick.

**Comment by llgis** [comment]
Unfortunately I still have this problem when publishing WMTS. The WMTS raster is shifted by several meters when published in EPSG:25832. Only in EPSG:3857 it is located correct, but in very low resolution. This makes WMTS in QGIS server not usable.
Using QGIS Server 3.28 and 3.30 on Windows Server 12.
