### ISSUE TITLE
Scale tool is broken when used in a canvas with distinct CRS than layer

### ISSUE THREAD

**Issue by roya0045** [qgis/QGIS#42953]
Tested on master on windows.

Using the scale tool in a canvas where the projection doesn't match the one of the geometry result in the scaled feature being moved far away.

It would also be nice of the tool worked on lines to stretch them in a group but maintain the topography.

I'll see what I can and want to do.

**Comment by uclaros** [comment]
Did I break this with #42683? Can you test if it was working ok before?

**Comment by roya0045** [comment]
@uclaros It might have been me initially. I'm just making a ticket to remind myself.

**Comment by roya0045** [comment]
@uclaros I also think the behaviour could apply to all geometry, I'll try to work that in at the same time. This is useful when multiple items are selected.

**Comment by uclaros** [comment]
I believe this should fix it? https://github.com/uclaros/QGIS/commit/a7344775290318893ba3427056e98abdc09d0e25

**Comment by roya0045** [comment]
@uclaros I'll start up my VM soon and give it a go if you didn't have the time to test it.

**Comment by uclaros** [comment]
@roya0045 There was a bug with the anchor point when there were selected features. Also when no features were found under the cursor. Finally, it took me a while to notice I had not cleaned up the anchor point properly on my last snapping unit test causing my new test to fail...
I think it's good now!

**Comment by roya0045** [comment]
@uclaros I think the no feature under cursor might explain why expanding lines failed, despite the fact that the code is not exclusive to polygon. Though strangely I can't test it because the toolbar and vector panel is empty. When you get the chance can you check on your end if all is fine?
