### ISSUE TITLE
Interior tick frame size not honored in WGS84

### ISSUE THREAD

**Issue by antoniolocandro** [qgis/QGIS#42963]
Ok so my map is in EPSG:5070 but I want a grid EPSG:4326, everything works ok except the abnormal size of the tick which should be 2mm but because of the rotation it is extended more than what it should be

Using QGIS 3.18.2-1 on Windows 10

![image](https://user-images.githubusercontent.com/4627073/116159956-64c3b580-a6ae-11eb-9249-56b4e583744b.png)

**Comment by olivierdalang** [comment]
Did you try changing the "ticks alignment" setting ?
