### ISSUE TITLE
Crash while searching

### ISSUE THREAD

**Issue by ehthisha** [qgis/QGIS#42982]
## User Feedback

while searching  PIA in the below left bottom after successfully checking more than 15 projects

## Report Details

**Crash ID**: [03364e9e53adf4eabab9cb4afbfb527b314295a3](https://github.com/qgis/QGIS/search?q=03364e9e53adf4eabab9cb4afbfb527b314295a3&type=Issues)

**Stack Trace**
<pre>
QgsLocatorResultsView::selectNextResult qgslocatorwidget.cpp:398
QgsLocatorWidget::eventFilter qgslocatorwidget.cpp:273
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:475
QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:475
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processKeyEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1638
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.18.1-Z�rich
QGIS code revision: 202f1bf7e5
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042
![Qgis -crash](https://user-images.githubusercontent.com/82948568/116229174-b66b4f00-a745-11eb-921f-e54e3abd0da9.PNG)

**Comment by gioman** [comment]
@ehthisha is the crash replicable in a consistent manner? have you tried with a new QGIS profile?
