### ISSUE TITLE
QGIS denendencies on Postgresql12 

### ISSUE THREAD

**Issue by bigopensky** [qgis/QGIS#42984]
Can you explain why the desktop application qgis 3.10,.14-A LTS produces dependencies in the package for the postrgesql-12-client in FreeBSD  12.2-RLEASE-p4. The dependencies producing interferences with the postgresql-11-server setup and anticipates a database server change to version 12.  IMO a simple desktop application **should never** interfere with an server production environment. 

Best Regards Huck

**Comment by gioman** [comment]
@bigopensky please ask in the QGIS developers mailing list, thanks.

**Comment by jef-n** [comment]
Better ask the FreeBSD maintainer(s).
