### ISSUE TITLE
Bad translation (Geman) crashes MetaSearch core plugin when performing catalog search

### ISSUE THREAD

**Issue by FroehDo** [qgis/QGIS#42987]
In version 3.16.6-Hannover (Windows, German locale) I'm receiving the following error when using the core plugin MetaSearch:

> Traceback (most recent call last):
>  File "C:/Users/FroehDo/AppData/Roaming/QGIS/QGIS3\profiles\Freiburg/python/plugins\MetaSearch\dialogs\maindialog.py", line 507, in search
>    self.display_results()
>  File "C:/Users/FroehDo/AppData/Roaming/QGIS/QGIS3\profiles\Freiburg/python/plugins\MetaSearch\dialogs\maindialog.py", line 517, in display_results
>    self.catalog.results['matches']).format(self.startfrom, position)
> ValueError: unexpected '{' in field name
>
>Python-Version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
>QGIS-Version: 3.16.6-Hannover Hannover, bfd36fddc9 

The error appears to be related to the translation to the locale. If I comment the format command in ll 516ff of […]/MetaSearch/dialogs/maindialog.py 

`        msg = self.tr('Showing {0} - {1} of %n result(s)', 'number of results',
                      self.catalog.results['matches']).format(self.startfrom, position)`
like
`        msg = self.tr('Showing {0} - {1} of %n result(s)', 'number of results',
                      self.catalog.results['matches'])  # .format(self.startfrom, position)`

the plugin works as expected and reveils a bad translation string in the gui causing the error above:

![grafik](https://user-images.githubusercontent.com/66945139/116255076-33142280-a772-11eb-883d-52b60fa1e91b.png)

Note the square bracket closing behind the 0!

Best,
Dominik Fröhlich

EDIT: The path in the error message points to AppData instead of the QGIS program directory because I took a copy of the MetaSearch Plugin and moved it to AppData for easier debugging with user priviledges.

**Comment by DelazJ** [comment]
Can be closed. Fixed in Transifex (replace {0] with  {0}) and would be available in 3.16 nightlies.
I think this is the kind of issues that should rely on language communities and not on the QGIS project; language speakers should step in to fix their issues (https://qgis.org/en/site/getinvolved/translate.html#becoming-a-translator)
