### ISSUE TITLE
Label that has data defined position is rendered even if it is outside the map canvas

### ISSUE THREAD

**Issue by Forna73** [qgis/QGIS#42990]
Hi!
I'm on QGis 3.16.6.
I'm sorry but I don't know how to classify this post, if a feature request, a bug or something else...
I'm using labels set in a way that their positions are determined by X,Y coordinates, because I need them in THAT position to avoid overlap with TENs of other labels (not included in the pic below to simplify the explanation of this behavior).
I created a map windows in Print Layout as you can see in A
![A](https://user-images.githubusercontent.com/12034365/116277227-8e9bdb80-a785-11eb-8d8f-ff63d6305617.jpg)

If I shift the map windows content it could happens that some labels are outside the borders, and they should disappear from the map window bacause their X,Y position, but Qgis still shows them if the related geometry is still present in the map window, and put without even trying to prevent them from overlapping each other (LIP333 along North border, LIP88A, LIP88B along south border). and also in way it seems around the centroid of the visible polygon (LIR82 along East border, LIP3 along West border), all regardless of the chosen positioning mode (Horizontal, offset, etc...)
![B](https://user-images.githubusercontent.com/12034365/116277525-da4e8500-a785-11eb-97cb-03b65f326c76.jpg)

Is there a way to prevent this behavior? I'd like to let labels out of the map window if their positions aren't included. What is the use of setting coordinates if Qgis does what it wants?

**Comment by roya0045** [comment]
@gioman This is quite a classic case, have any maps with data defined labels, when the coordinate of the label is outside of the canvas and the geometry is within, the label will use the center point but the callout line will remain.

**Comment by Forna73** [comment]
[labels_along_borders.zip](https://github.com/qgis/QGIS/files/6387156/labels_along_borders.zip)
Hope this help...

**Comment by Forna73** [comment]
It's seems like:
if Qgis could put the label where you want with your settings, it will does;
if Qgis couldn't do that, it will pick the label and put around the centroid of the visible portion of the element (this applys to point and line vectors too).
So it could be usable to have the possibility to choose this behavior, a check box or something that tells Qgis: what to do.
I mean:
if Qgis can draw the label as per your settings that's fine, but if it can't:
1. let Qgis put the label where it wants
2. don't show the label at all

**Comment by Forna73** [comment]
I just tested my files with old Qgis 3.10.8.... and it doesn't show this behavior.
So actually I think it's a bug, at least in 3.16.6

**Comment by gioman** [comment]
> I just tested my files with old Qgis 3.10.8.... and it doesn't show this behavior.
> So actually I think it's a bug, at least in 3.16.6

@Forna73 I'm getting the expected result by disabling "show all labels for this layer (including colliding labels)". Please try.

**Comment by Forna73** [comment]
I can't do that, because in that way qgis doesn't show labels that I need.
The problem is that even a minimal part of geometry (1mm) in the map windows let Qgis put the label I don't need.... and this is making a lot of confusion... I'm having several labels I don't need only cause a minimal geometry portion.... and there's no way to get out of them.
If a label is set with coordinate out of the map windows it MUST not shows up... Qgis 3.16.6 simply always force the label to appear even a minimal part of a geometry is included in the map windows and there is no way to prevent this.

**Comment by roya0045** [comment]
Use an expression to control label render if the option is too much.

**Comment by gioman** [comment]
> it MUST not shows up

@Forna73 the change could have been introduced by design. I suggest you to raise the question on the developers mailing list.

**Comment by Forna73** [comment]
I don't know how to proceed....
Now I'm very busy to revert my file to old Qgis 3.10.8 because I really can't manage this behavior....

> Use an expression to control label render if the option is too much.

Don't know how to do....

**Comment by gioman** [comment]
> I don't know how to proceed....

@Forna73 https://lists.osgeo.org/mailman/listinfo/qgis-developer

**Comment by roya0045** [comment]
@gioman I think gis stackexchange would be a better place to search and ask to search and ask for such things. As it would benefit other users with this issue.

**Comment by gioman** [comment]
> @gioman I think gis stackexchange would be a better place to search and ask to search and ask for such things. As it would benefit other users with this issue.

@roya0045 about the expression, yes. What I meant is that is better to write in the list to understand of the change was introduced by design.

**Comment by Forna73** [comment]
HI... I wrote to the mailing list and gis stackexchange.

I've also found this... I thinks it's related to this problem

https://qgis.org/en/site/forusers/visualchangelog314/index.html#feature-automatic-placement-of-labels-outside-polygons

I'm still trying to understand but I think that some kind of bug in this automatic behavior?
What do you think?

**Comment by gioman** [comment]
> HI... I wrote to the mailing list

@Forna73 I have seen the message. Suggestion: next time describe the problem in the message rather than just linking the Github ticket, this would raise your chances that someone will answer you (not saying that no one will).

> I've also found this... I thinks it's related to this problem

Your labels position is data defined, so that option(s) are likely to be ignored.

**Comment by Forna73** [comment]
It seems nobody is interested in this problem...

**Comment by gioman** [comment]
> It seems nobody is interested in this problem...

@Forna73 what you are expecting? if this is issue is blocking for your workflow you should think about hiring a dev that can fix it for you, unless you can propose a patch. And this is assuming that this change was not introduced by design (something I'm not really sure about).

**Comment by roya0045** [comment]
@gioman I think this is an intended fallback. This is why I think an expression would be adequate to bypass the fallback.

**Comment by gioman** [comment]
> @gioman I think this is an intended fallback. This is why I think an expression would be adequate to bypass the fallback.

@roya0045 I agree.

**Comment by Forna73** [comment]
> I think this is an intended fallback. This is why I think an expression would be adequate to bypass the fallback.
Can you give me any example?

**Comment by roya0045** [comment]
`within(make_point("aux_x","aux_y"),@map_extent)`

**Comment by Forna73** [comment]
mhm... i can't figure out how to apply such kind of expression... I'm not so good...

**Comment by lindacamathias** [comment]
how to apply the expression (sorry the screenshots are in german version but i hope it may still help someone..)

1. Labelstyling -> choose rule-based
![image (4)](https://user-images.githubusercontent.com/77726342/146201446-f8ab2481-9a8b-4a40-9139-34c063f5146b.png)

2. double click on rule text to change it
![image (5)](https://user-images.githubusercontent.com/77726342/146201472-8388faeb-49e5-4f88-a159-83f853df5721.png)

3. put expression in filter: 
![image (6)](https://user-images.githubusercontent.com/77726342/146201514-c6ceb740-b0f3-48ee-a3e4-fe0c86e4fb1a.png)
