### ISSUE TITLE
QGIS 3.16 keeps crashing when working with big raster data!

### ISSUE THREAD

**Issue by DanielHorst** [qgis/QGIS#43008]
## User Feedback

QGIS keeps on crashing. I suspect that something with the loading of heavy/big raster data is not working (in my case working with a 0.1m x 0.1m satelite image). 

## Report Details

**Crash ID**: [9df003a1d6086ce637725c6bc53ad588c9dc2002](https://github.com/qgis/QGIS/search?q=9df003a1d6086ce637725c6bc53ad588c9dc2002&type=Issues)

**Stack Trace**
<pre>
QgsMultiBandColorRenderer::block qgsmultibandcolorrenderer.cpp:279
QgsBrightnessContrastFilter::block qgsbrightnesscontrastfilter.cpp:119
QgsHueSaturationFilter::block qgshuesaturationfilter.cpp:123
QgsRasterResampleFilter::block qgsrasterresamplefilter.cpp:124
QgsRasterProjector::block qgsrasterprojector.cpp:815
QgsRasterIterator::readNextRasterPartInternal qgsrasteriterator.cpp:130
QgsRasterDrawer::draw qgsrasterdrawer.cpp:60
QgsRasterLayerRenderer::render qgsrasterlayerrenderer.cpp:321
QgsMapRendererCustomPainterJob::doRender qgsmaprenderercustompainterjob.cpp:319
QgsMapRendererCustomPainterJob::staticRender qgsmaprenderercustompainterjob.cpp:283
QtConcurrent::StoredFunctorCall1<void,void (__cdecl*)(QgsMapRendererParallelJob *),QgsMapRendererParallelJob *>::runFunctor qtconcurrentstoredfunctioncall.h:432
QtConcurrent::RunFunctionTask<void>::run qtconcurrentrunbase.h:144
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
__RtlUserThreadStart :
_RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.16.5-Hannover
QGIS code revision: 58ba7c1ed6
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

**Comment by gioman** [comment]
> QGIS keeps on crashing. I suspect that something with the loading of heavy/big raster data is not working (in my case working with a 0.1m x 0.1m satelite image).

@DanielHorst please try with a new QGIS profile, no 3rd party plugins installed. If the problem persist please attach/link the offending dataset.

**Comment by gioman** [comment]
Closing for lack of feedback.
