### ISSUE TITLE
QGIS crashes on multiple computers when opening symbology

### ISSUE THREAD

**Issue by levi321321** [qgis/QGIS#43000]
**Describe the bug**

**How to Reproduce**

4. See error -->

**QGIS and OS versions**

**Additional context**

**Comment by uclaros** [comment]
I hope this does not mean that when opening symbology on one computer other computers in the room crash!
(You need to complete all the info you omitted on the report)

**Comment by roya0045** [comment]
Too much missing info.

**Comment by gioman** [comment]
@levi321321 please try with a new QGIS profile (no 3rd party plugins installed).
