### ISSUE TITLE
Target out grid - Interpolation Issue!

### ISSUE THREAD

**Issue by amerr97** [qgis/QGIS#43011]
**Describe the bug**

**How to Reproduce**

4. See error -->

**QGIS and OS versions**

**Additional context**

QGIS version: 3.16.0-Hannover
QGIS code revision: 43b64b13f3
Qt version: 5.11.2
GDAL version: 3.1.4
GEOS version: 3.8.1-CAPI-1.13.3
PROJ version: Rel. 6.3.2, May 1st, 2020
Processing algorithm…
Algorithm 'Natural neighbour' starting…
Input parameters:
{ 'FIELD' : 'Vremenska_TEMPERATURA', 'METHOD' : 2, 'SHAPES' : 'E:\\Podaci\\BHA\\SHAPES\\POINTS\\COUNTIES.SHP', 'TARGET_OUT_GRID' : 'TEMPORARY_OUTPUT', 'TARGET_TEMPLATE' : None, 'TARGET_USER_FITS' : 1, 'TARGET_USER_SIZE' : 100, 'TARGET_USER_XMIN TARGET_USER_XMAX TARGET_USER_YMIN TARGET_USER_YMAX' : None, 'WEIGHT' : 0 }

grid_gridding "Natural Neighbour" -TARGET_DEFINITION 0 -SHAPES "E:\Podaci\BHA\SHAPES\POINTS\COUNTIES.SHP" -FIELD "Vremenska_TEMPERATURA" -METHOD 2 -TARGET_USER_SIZE 100.0 -TARGET_USER_FITS 1 -WEIGHT 0.0 -TARGET_OUT_GRID "C:/Users/Lenovo-X260/AppData/Local/Temp/processing_wzhZWO/e2856e8b57c94e97ac9cfdaa96fc4bc3/TARGET_OUT_GRID.sdat"

C:\Users\Lenovo-X260\Documents>set SAGA=C:/PROGRA~1/QGIS3~1.16/apps\saga-ltr

C:\Users\Lenovo-X260\Documents>set SAGA_MLB=C:/PROGRA~1/QGIS3~1.16/apps\saga-ltr\modules

C:\Users\Lenovo-X260\Documents>PATH=C:\PROGRA~1\QGIS3~1.16\apps\qgis\bin;C:\PROGRA~1\QGIS3~1.16\apps\Python37;C:\PROGRA~1\QGIS3~1.16\apps\Python37\Scripts;C:\PROGRA~1\QGIS3~1.16\apps\qt5\bin;C:\PROGRA~1\QGIS3~1.16\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\system32\WBem;C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\pywin32_system32;C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\numpy\.libs;C:/PROGRA~1/QGIS3~1.16/apps\saga-ltr;C:/PROGRA~1/QGIS3~1.16/apps\saga-ltr\modules

C:\Users\Lenovo-X260\Documents>call saga_cmd grid_gridding "Natural Neighbour" -TARGET_DEFINITION 0 -SHAPES "E:\Podaci\BHA\SHAPES\POINTS\COUNTIES.SHP" -FIELD "Vremenska_TEMPERATURA" -METHOD 2 -TARGET_USER_SIZE 100.0 -TARGET_USER_FITS 1 -WEIGHT 0.0 -TARGET_OUT_GRID "C:/Users/Lenovo-X260/AppData/Local/Temp/processing_wzhZWO/e2856e8b57c94e97ac9cfdaa96fc4bc3/TARGET_OUT_GRID.sdat"
Error: Points
____________________________

##### # ## ##### # ##
____________________________

SAGA Version: 2.3.2 (64 bit)

____________________________
library path: C:\PROGRA~1\QGIS3~1.16\apps\saga-ltr\modules\
library name: grid_gridding
library : Gridding
tool : Natural Neighbour
author : O.Conrad (c) 2008
processors : 4 [4]
____________________________

Load shapes: E:\Podaci\BHA\SHAPES\POINTS\COUNTIES.SHP...

Usage: saga_cmd grid_gridding 3 [-SHAPES <str>] [-FIELD <str>] [-TARGET_DEFINITION <str>] [-TARGET_USER_SIZE <double>] [-TARGET_USER_XMIN <double>] [-TARGET_USER_XMAX <double>] [-TARGET_USER_YMIN <double>] [-TARGET_USER_YMAX <double>] [-TARGET_USER_FITS <str>] [-TARGET_TEMPLATE <str>] [-TARGET_OUT_GRID <str>] [-METHOD <str>] [-WEIGHT <double>]
-SHAPES:<str> Points
Shapes (input)
-FIELD:<str> Attribute
Table field
-TARGET_DEFINITION:<str> Target Grid System
Choice
Available Choices:
[0] user defined
[1] grid or grid system
Default: 0
-TARGET_USER_SIZE:<double> Cellsize
Floating point
Minimum: 0.000000
Default: 1.000000
-TARGET_USER_XMIN:<double> Left
Floating point
Default: 0.000000
-TARGET_USER_XMAX:<double> Right
Floating point
Default: 100.000000
-TARGET_USER_YMIN:<double> Bottom
Floating point
Default: 0.000000
-TARGET_USER_YMAX:<double> Top
Floating point
Default: 100.000000
-TARGET_USER_FITS:<str> Fit
Choice
Available Choices:
[0] nodes
[1] cells
Default: 0
-TARGET_TEMPLATE:<str> Target System
Grid (optional input)
-TARGET_OUT_GRID:<str> Target Grid
Grid (output)
-METHOD:<str> Method
Choice
Available Choices:
[0] Linear
[1] Sibson
[2] Non-Sibsonian
Default: 1
-WEIGHT:<double> Minimum Weight
Floating point
Maximum: 0.000000
Default: 0.000000

C:\Users\Lenovo-X260\Documents>exit
Execution completed in 7.58 seconds
Results:
{'TARGET_OUT_GRID': 'C:/Users/Lenovo-X260/AppData/Local/Temp/processing_wzhZWO/e2856e8b57c94e97ac9cfdaa96fc4bc3/TARGET_OUT_GRID.sdat'}

Loading resulting layers
The following layers were not correctly generated.
• C:/Users/Lenovo-X260/AppData/Local/Temp/processing_wzhZWO/a9da6202350f4643b5661c410446b207/TARGET_OUT_GRID.sdat
• C:/Users/Lenovo-X260/AppData/Local/Temp/processing_wzhZWO/e2856e8b57c94e97ac9cfdaa96fc4bc3/TARGET_OUT_GRID.sdat
You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.

I have tried the latest version 18, 16. and this older and I allways get this error why??!!

**Comment by gioman** [comment]
> QGIS version: 3.16.0-Hannover

@amerr97 please update to the latest QGIS 3.16 as 3.16.0 is too old.

If the problem persist please attach your "COUNTIES.SHP" input file.
