### ISSUE TITLE
Export to DXF is not available to copy @AutoCAD

### ISSUE THREAD

**Issue by JuDalbello** [qgis/QGIS#43012]
Hello from Brazil!

Since QGIS 3.10 when exporting a polygon to DXF it's not possible to copy the geometry at AutoCAD.
It used to work, so I could paste to my DWG map.

SRC is OK.

See the message at Autocad when I try to copy and the file used to generate DXF file.
When I create this file in earlier version it works.

![QGIS bug](https://user-images.githubusercontent.com/83372456/116468120-db93b680-a846-11eb-8403-449d775d0ee2.JPG)
[testegeom.zip](https://github.com/qgis/QGIS/files/6394604/testegeom.zip)

**Comment by gioman** [comment]
> Since QGIS 3.10 when exporting a polygon to DXF

@JuDalbello how do you export to DXF? "save features as..."? project > import/export > export project do DXF? processing > convert format?




> it's not possible to copy the geometry at AutoCAD.

do you mean "open" the generated DXF in AD? if not, what do you mean with "copy"?

**Comment by JuDalbello** [comment]
@gioman At QGIS right mouse button click on layer > Export > Save feature as...
Sending you the prints of dialogue box, sequence 1, 2, 3
>- Just choose the name and place of DWF file, no changes are made on options showed, it returns the prints at the beggining of this conversation
>- tryed to select polygon type = no geometry is exported. DXF is created but it's empty
>- tryed to select the option INCLUDE Z coordinate and the file created returns the same error when copying the polygon at Autocad.

After, at AutoCAD:
Open DXF
Zoom extents to center the geometry on screen
select the polygon
Copy (ctrl + C)
>- after this, I open the AutoCAD file where I need to paste the geometry, and use the command PASTE TO ORIGINAL COORDINATES

It used to work on QGIS 2.18, since 3.10 it doesn't work anymore (see print 2.18 version)
Attached a file produced on 2.18 version, that works properly at AutoCAD. (see zipped file)

Thanks!
![Capturar2](https://user-images.githubusercontent.com/83372456/116553626-b8154e00-a8d0-11eb-820e-9783ad9118b5.JPG)
![Capturar3](https://user-images.githubusercontent.com/83372456/116553637-b9467b00-a8d0-11eb-8dac-dcf2016fc42d.JPG)
![Capturar1](https://user-images.githubusercontent.com/83372456/116553643-b9df1180-a8d0-11eb-802e-10f585e0c1e9.JPG)
[27-098-0036 e 0037.zip](https://github.com/qgis/QGIS/files/6398678/27-098-0036.e.0037.zip)
![2 18 version](https://user-images.githubusercontent.com/83372456/116554141-3a057700-a8d1-11eb-8266-59afbc0677a5.JPG)

**Comment by gioman** [comment]
> At QGIS right mouse button click on layer > Export > Save feature as...

@JuDalbello same result with the other methods?

**Comment by agiudiceandrea** [comment]
It seems the "Copy to clipboard failed" error is a recurring issue with AutoCAD https://www.google.com/search?q=autocad+%22copy+to+clipboard+failed%22

I can copy and past object in the provided dxf drawing using DraftSight 2018 SP3 without issues.

Anyway there is a not addressed report about the same issue when the dxf is exported using the ogr2ogr GDAL tool:
https://github.com/OSGeo/gdal/issues/1213#issuecomment-778738957

**Comment by JuDalbello** [comment]
> It seems the "Copy to clipboard failed" error is a recurring issue with AutoCAD https://www.google.com/search?q=autocad+%22copy+to+clipboard+failed%22
> 
> I can copy and past object in the provided dxf drawing using DraftSight 2018 SP3 without issues.
> 
> Anyway there is a not addressed report about the same issue when the dxf is exported using the ogr2ogr GDAL tool:
> [OSGeo/gdal#1213 (comment)](https://github.com/OSGeo/gdal/issues/1213#issuecomment-778738957)

Thanks @agiudiceandrea it really seams QGIS produces a damaged file.
I'll try to find a friend who uses AutoCad everyday to discuss it.

**Comment by JuDalbello** [comment]
Just found AUDIT command at AutoCAD and it worked. See the print.

Why QGIS is exporting with errors is the question! But I'm not a developer!
Good work folks!

Thanks everybody
![audit](https://user-images.githubusercontent.com/83372456/117495299-d112a480-af4b-11eb-9f15-1c713f12607a.JPG)

**Comment by kikislater** [comment]
> Just found AUDIT command at AutoCAD and it worked. See the print.

It would be interesting if you could compare with meld (or other software like that) difference before and after corrections ...

**Comment by JuDalbello** [comment]
> > Just found AUDIT command at AutoCAD and it worked. See the print.
> 
> It would be interesting if you could compare with meld (or other software like that) difference before and after corrections ...

Hi @kikislater
Sorry but I'm not this expert... I don't know meld or any other program... I really came to show there is a problem at QGIS after 3.10 version. If a developer wants to go deepper and correct it would be great.
I'm an ordinary user.

**Comment by gioman** [comment]
>  I'm an ordinary user.

@JuDalbello you don't need to e a developer to use meld (which has a GUI): it is a program that open 2 files and show you the differences. Is not that hard and it would help a lot.

**Comment by JuDalbello** [comment]
[DXF BEFORE AND AFTER AUDIT.zip](https://github.com/qgis/QGIS/files/6460272/DXF.BEFORE.AND.AFTER.AUDIT.zip)

@agiudiceandrea here they are!

@gioman I don't have permission to install any program at work.

**Comment by AlisterH** [comment]
In future I'd suggest you don't close a ticket like this just because you've found a workaround.  I'm sure nobody wants QGIS to create DXFs that Autocad can't handle properly.

**Comment by AlisterH** [comment]
Note that:
1. this is probably an upstream gdal issue.
2. another workaround is to use "Project>Import/Export>Export Project to dxf", which I presume doesn't use gdal.  But it is broken in many versions of QGIS (and notably crashes 3.18.0, although 3.18.3 seems OK).

**Comment by agiudiceandrea** [comment]
> 2\. But it is broken in many versions of QGIS

Some issues have recently been fixed: https://github.com/qgis/QGIS/pull/41918, https://github.com/qgis/QGIS/pull/43524, https://github.com/qgis/QGIS/pull/43525

**Comment by jbp35** [comment]
I faced the same issue with latest QGIS version today (3.26.0). 

Commands like Audit did not work for me. The only work around I could find to recover the DXF was to :

1) save the DXF file exported from QGIS as a DWG in Autocad
2) create a new autocad file
3) Insert the previously saved DWG file as a block
4) explode the block

**Comment by jbp35** [comment]
I did some research and this is a GDAL issue; I opened an issue there with some initial troubleshooting:

https://github.com/OSGeo/gdal/issues/6013

**Comment by alexbruy** [comment]
Should be fixed in QGIS builds with GDAL >=3.5.2. Please re-test and report back.
