### ISSUE TITLE
QgsProjectionSelectionWidget::selectCrs() cannot be overwritten in Python

### ISSUE THREAD

**Issue by LMA9** [qgis/QGIS#43019]
Code like this will not give effect:
```
class MetricCrsOnlyProjectionSelectionWidget(QgsProjectionSelectionWidget):
    def selectCrs(self):
        dialog = QgsProjectionSelectionDialog(self)
        dialog.setOgcWmsCrsFilter(self._metric_crs_list)
        if dialog.exec():
            self.setValue(dialog.crs().authid())

    @property
    def _metric_crs_list(self):
        return ["EPSG:3384", ]
```
And this return `False`:
`hasattr(QgsProjectionSelectionWidget, 'selectCrs')`

But [here](https://qgis.org/pyqgis/3.16/gui/QgsProjectionSelectionWidget.html) it's listed as method.

**Comment by lbartoletti** [comment]
@LMA9 It works for me on QGIS 3.16

**Comment by lbartoletti** [comment]
Which version are you using?

**Comment by LMA9** [comment]
> Which version are you using?

3.16

**Comment by LMA9** [comment]
> @LMA9 It works for me on QGIS 3.16

I was talking about overwriting. You can overwrite this method?
For me it just run as default.

**Comment by lbartoletti** [comment]
> > @LMA9 It works for me on QGIS 3.16
> 
> I was talking about overwriting. You can overwrite this method?
> For me it just run as default.

It seems:

![selectCrs-2021-06-07_11 07 19 mkv](https://user-images.githubusercontent.com/7521540/120990343-bcab0d00-c780-11eb-946c-b1d64d7a745d.gif)

**Comment by LMA9** [comment]
> 
> 
> > > @LMA9 It works for me on QGIS 3.16
> > 
> > 
> > I was talking about overwriting. You can overwrite this method?
> > For me it just run as default.
> 
> It seems:
> 
> ![selectCrs-2021-06-07_11 07 19 mkv](https://user-images.githubusercontent.com/7521540/120990343-bcab0d00-c780-11eb-946c-b1d64d7a745d.gif)

Looks like a magic... Well it looks like my code is bad. Thanks for answering.
