### ISSUE TITLE
QGIS 3.16 Hannover unexpectedly ended while choosing a plugin I want to install

### ISSUE THREAD

**Issue by lislbe9** [qgis/QGIS#43023]
Crash ID: 472ea3512682a3798d2cecc71f612973b1cc7185

Stack Trace

QMetaObject::activate :
QHttpMultiPart::qt_metacast :
QSslKey::operator!= :
QSslKey::operator!= :
QMetaObject::activate :
QAbstractSocket::proxyAuthenticationRequired :
QMetaObject::activate :
QAbstractSocket::proxyAuthenticationRequired :
QNetworkProxyQuery::networkConfiguration :
QMetaObject::activate :
QAbstractSocket::disconnected :
QAbstractSocket::canReadLine :
QNetworkProxyQuery::networkConfiguration :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
QEventLoop::exec :
QThread::exec :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.16.5-Hannover
QGIS code revision: 58ba7c1ed6
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

I have already deleted the profile but no improvement.

**Comment by gioman** [comment]
@lislbe9 please add all the requested infos, and also try with a new QGIS profile.



**Describe the bug**


**How to Reproduce**



1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error -->

**QGIS and OS versions**



**Additional context**

**Comment by lislbe9** [comment]
@gioman I already tried it with a new QGIS profile.

I wanted to install the ORS Tool and immediately after choosing it in the Pluginlist QGIS crashed. It was not possible tu click the Install Button.

**How to Reproduce**
`1. Go to "Plugins"
`2. Click on "Manage and Install Plugins"`
`3. Click on any available Plugin`
`4. See error`

QGIS Version: 3.16.5-Hannover

![qgis-3-16-Plugin](https://user-images.githubusercontent.com/83392425/116541827-3c28ff00-a8ec-11eb-8b96-9b2863939878.PNG)

**Comment by gioman** [comment]
@lislbe9 can't replicate on both Windows and Linux. You have likely a local issue. Try if the same happens on a different machine.

**Comment by lislbe9** [comment]
Okay thank you @gioman. Maybe the local issue comes with the proxy server we have to use to connect with the internet.

**Comment by gioman** [comment]
> Maybe the local issue comes with the proxy server we have to use to connect with the internet.

@lislbe9 maybe, but if that is the case QGIS should not crash anyway. Does it happens with any plugin? does it happens if you don't use the proxy?
