### ISSUE TITLE
QgsAttributeForm object deleted but UI still showing QGIS 3.16.5

### ISSUE THREAD

**Issue by raulsangonzalo** [qgis/QGIS#43026]
Hello, in our company we use custom forms to connect to multiple scripts to perform multiple tasks across our databases and servers. We have subclassed the forms so they can be instantiated via:

def formOpen(dialog, layerid, featureid):
    MyForm(dialog, layerid, featureid)

We didn't do this in the past. We just declared global variables here and there but we soon found out that they were interfering when you opened a second form. So:
1. Open first form
2. Open second form
3. Go to first form and click Ok/Cancel or any other button that links to a function, and the pointer would be on the second form rather than on the second.

This caused a lot of errors and we told people not to open two forms at once. This is not ok, since they wanted to check multiple layers at the same time.

So we subclassed it and we are getting a similar behaviour when opening multiple forms. We get errors such as "self variable is referenced before assigning" and "c++ object has been deleted". We need to use a lambda function to pass some extra parameters and this triggers it. Normal connections without lambda function do not cause an error but they do not execute, since the form is dead already.

So my guess is that the garbage collector is deleting things for us to free up some memory (developers have better PCs so it's harder to reproduce the errors) but they are not notifying in any way. So the form is deleted but the UI is still there, so if you try to press a button then it will cause an error.

It would be interesting to have a signal that could pass the reference (layer and feature) of the form that has been deleted so we could re-open it or handled it in another way.

**Comment by gioman** [comment]
> It would be interesting to have a signal that could pass the reference (layer and feature) of the form that has been deleted so we could re-open it or handled it in another way.

@raulsangonzalo is this a bug report or a feature request? have you discussed this first in the developers mailing list?

**Comment by raulsangonzalo** [comment]
> > It would be interesting to have a signal that could pass the reference (layer and feature) of the form that has been deleted so we could re-open it or handled it in another way.
> 
> @raulsangonzalo is this a bug report or a feature request? have you discussed this first in the developers mailing list?

Sorry for my afterthoughts. It is indeed a bug. If the object is deleted the ui+python side should be deleted too.

**Comment by m-kuhn** [comment]
I think it would be worth asking a question on gis.se with a minimal example to reproduce. In order to validate that the current behavior is buggy.

**Comment by alexbruy** [comment]
@raulsangonzalo may I ask you to provide a minimal reproducible example? Also it would be nice to ask in the developers mailing list or at stackexchange as Matthias suggested.
