### ISSUE TITLE
Qgis 3 unexpectidly slow for each new window

### ISSUE THREAD

**Issue by ValCUMA85** [qgis/QGIS#43024]
After an uninstallation of Qgis 2.18 working well on the computer, I installed Qgis 3.16. 

Qgis 3.16 is very slow (23-30 second of non responding)  each time a new window appear (symbologie, process, new layer, impress, etc...)

It happend even in the menu, without any project open. 

I totally cleaned the computer from former version of qgis. The problem occures in 32 and 64 bit. 
The computer has a SSD and a godd graphic card. 

DO you have any idea to solve the problem. Because of this I can only work on Qgis 2.18. 

Thankyou

**Comment by gioman** [comment]
@ValCUMA85 of course does not seems a general issue, but rather a local one. Try posting on the users or developers mailing list, you will reach a much larger audience.

**Comment by PietrH** [comment]
I had a similar experience upgrading to Pi  from Bonn and then to 3.18.2. I updated my plugins, disabled them all, removed larger layers, in the end switching back to Bonn seems to have fixed it. Maybe there is something about my QGZ file that is causing an incompatibility? 

I was seeing Python errors regarding the modeltreeview in the processing plugin, probably unrelated.
