### ISSUE TITLE
Toolbars and vector tools

### ISSUE THREAD

**Issue by luanschimidel** [qgis/QGIS#43028]
hello Qgis community, im not getting acess de qgis toolsbar and the vector tools. When i open the software, appears to me a message that my qgis is crashed. I tryed reinstall but the error dont stoped.

**Comment by gioman** [comment]
@luanschimidel please try with QGIS profile

settings > profiles > new profile

**Comment by luanschimidel** [comment]
It worked, thanks very much!!
