### ISSUE TITLE
Map composer grid intervals does not allow values above 9999999

### ISSUE THREAD

**Issue by NyakudyaA** [qgis/QGIS#43039]
# Problem

In map composer a user cannot define grid intervals greater than 9999999 when using projected CRS like `EPSG:3857`

![Screenshot 2021-04-30 at 11 27 50](https://user-images.githubusercontent.com/2510900/116676600-74d9de80-a9a7-11eb-89ca-0c8885fbe417.png)

OS: Mac Mojave
QGIS Version: 3.18.1

**Comment by agiudiceandrea** [comment]
@NyakudyaA would 8 or 9 digits enough?

**Comment by NyakudyaA** [comment]
> @NyakudyaA would 8 or 9 digits enough?

Yes, that should be enough

**Comment by agiudiceandrea** [comment]
So, 8 are ok?
