### ISSUE TITLE
Data Source Manager incorrectly identifies PostGIS raster extent on macOS

### ISSUE THREAD

**Issue by iod-ine** [qgis/QGIS#43042]
**Describe the bug**

When loading a PostGIS raster from the Browser or the Data Source Manager, extent values partially become zero. Because of that the loaded layer is significantly larger than the original, and the extra part is filled with zeros. In the image below, the lower right part that looks like a DEM is the actual raster, and the gray filling around is an artifact.

<img width="1570" alt="Screen Shot 2021-04-30 at 10 25 24 PM" src="https://user-images.githubusercontent.com/62653164/116746025-9f0db980-aa04-11eb-96c8-81a9159973da.png">

Here I loaded the extent that is provided in `raster_columns` view in the database as a vector layer using the DB manager, so everything is correct in the database.

<img width="1570" alt="Screen Shot 2021-04-30 at 10 26 40 PM" src="https://user-images.githubusercontent.com/62653164/116746220-cf555800-aa04-11eb-9e4d-71b7a8a44844.png">

And here is the information that is shown in layer properties, where North and West extents are zero.

<img width="645" alt="Screen Shot 2021-04-30 at 10 27 12 PM" src="https://user-images.githubusercontent.com/62653164/116747184-31628d00-aa06-11eb-992a-55b3a8973c4f.png">

For comparison, here is the original file's information.

<img width="630" alt="Screen Shot 2021-04-30 at 10 24 15 PM" src="https://user-images.githubusercontent.com/62653164/116754543-953e8300-aa11-11eb-8cb6-14b57d4b89db.png">

**How to Reproduce**

1. I uploaded the raster using `raster2pgsql -s 949910 -c -e -C -r -t 100x100 <file> "schema.table" | psql -h localhost -p 5432 -U <user> -d <database>`
2. I loaded the table to QGIS, and the extents are wrong.

**QGIS and OS versions**

QGIS version | 3.18.2-Zürich | QGIS code revision | 44d7dfabbe
-- | -- | -- | --
Compiled against Qt | 5.14.2 | Running against Qt | 5.14.2
Compiled against GDAL/OGR | 3.2.1 | Running against GDAL/OGR | 3.2.1
Compiled against GEOS | 3.9.1-CAPI-1.14.2 | Running against GEOS | 3.9.1-CAPI-1.14.2
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
Compiled against PDAL | 2.2.0 | Running against PDAL | 2.2.0 (git-version: Release)
PostgreSQL Client Version | 12.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.4
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | macOS 11.3
Active python plugins | processing; db_manager; MetaSearch

**Additional context**

I am trying to upload a large DEM to PostGIS by splitting it into 30 smaller regions. The regions that are not touching the origin of the coordinates suffer from this weird extent mismatch: if it lies to the West of the origin, then the East extent becomes zero, if it lies to the South, then the North extent becomes zero, etc. I’m not sure what’s the best way to provide an example dataset in this case. Since I originally thought that the error was on the PostGIS site, I tried all the possible combinations of flags for `raster2psql`. I also tried different projections for the raster. Still the extent is wrong. May be I'm doing something wrong?

**Comment by gioman** [comment]
> May be I'm doing something wrong?

@iod-ine can't replicate using my own test data. Better attach the data you are importing, and describe the extract steps you are following to do the import.

**Comment by iod-ine** [comment]
@gioman I uploaded the raster from my screenshot to [Google Drive](https://drive.google.com/file/d/1kquwhmPPiofKU5gXs4b98GyVvDkZllK2/view?usp=sharing). I got it by slicing up a [larger raster](https://astrogeology.usgs.gov/search/map/Mars/GlobalSurveyor/MOLA/Mars_MGS_MOLA_DEM_mosaic_global_463m) using `Raster` -> `Extraction` -> `Clip Raster by Mask Layer` and a vector of polygons representing quadrants on Mars. To import it, I used `raster2pgsql -s 949910 -c -e -C -r -t 100x100 mgs_mola_dem_463m_mc28.tif mgs_mola_dem.mc28 | psql -h localhost -p 5432 -U admin -d mars_remote_sensing`.

**Comment by gioman** [comment]
@iod-ine 

![Screenshot_20210501_132254](https://user-images.githubusercontent.com/1951107/116782338-5eec1c80-aa80-11eb-95cb-0b776dd7f2d3.png)

**Comment by iod-ine** [comment]
@gioman So it's definitely on my side then. I've very carefully repeated all the steps once again and I'm still getting the wrong extents. Could I have accidentally broken my installation somehow? Could something work differently on MacOS?

**Comment by iod-ine** [comment]
I tested it on my work machine that's running Ubuntu and there is no problem there.

**Comment by gioman** [comment]
> I tested it on my work machine that's running Ubuntu and there is no problem there.

@iod-ine the problem could be on the postgis side, not qgis's. Try connecting to you db on macos with Ubuntu and vice versa-

**Comment by iod-ine** [comment]
@gioman I am using a Docker container with the database and the same image on both machines, so I don't think there is any difference between the databases. Still, just in case, I tried connecting from QGIS on my Mac to the database on Ubuntu, and the result is the same: extent is wrong. I can't really perform the vise versa test at the moment, since I don't have the network set up for it

**Comment by gioman** [comment]
> I can't really perform the vise versa test at the moment, since I don't have the network set up for it

will test on macOS as soon as I can.

**Comment by iod-ine** [comment]
@gioman have you had a chance to test on macOS?

**Comment by gioman** [comment]
> @gioman have you had a chance to test on macOS?

@iod-ine will do later today, thanks for the reminder.

**Comment by gioman** [comment]
> @gioman have you had a chance to test on macOS?

@iod-ine yes I see the problem on macOS, not on the other major platforms.

**Comment by PeterPetrik** [comment]
`raster2pgsql` is not part of standard QGIS bundle on macOS. how you get it installed on your machine?

**Comment by gioman** [comment]
> `raster2pgsql` is not part of standard QGIS bundle on macOS. how you get it installed on your machine?

@PeterPetrik to test I used a remote server, and used raster2pgsql from a Linux machine.

**Comment by PeterPetrik** [comment]
ok, where I can find the schema `mgs_mola_dem.mc28` ?

**Comment by iod-ine** [comment]
@PeterPetrik What do you mean exactly? 

To load the files into the database I use a script that first creates a schema called `mgs_mola_dem`, and then iterates over rasters in a directory uploading them into this schema in the form `mgs_mola_dem.mc{<number>}`. The example `mc28` file is in my [Google Drive](https://drive.google.com/file/d/1kquwhmPPiofKU5gXs4b98GyVvDkZllK2/view?usp=sharing).

**Comment by PeterPetrik** [comment]
ok, missed the coffee, now reading the raster1psql help it is obvious :)

**Comment by PeterPetrik** [comment]
ok, have it replicated locally:
```
docker run --name "postgis" -p 25432:5432 -d -t kartoza/postgis
docker run -v ~/Downloads/:/usr/data --name "postgis" -p 25432:5432 -d -t kartoza/postgis

apt-get update
apt-get install postgis
psql -h localhost -U docker -d gis
raster2pgsql -s 949910 -c -e -C -r -t 100x100 /usr/data/mgs_mola_dem_463m_mc28.tif "public.raster_mc28" | psql -h localhost -p 5432 -U docker -d gis  
```
and in QGIS
![Screenshot 2021-06-16 at 8 40 29](https://user-images.githubusercontent.com/804608/122170216-996a1700-ce7e-11eb-8112-9511af5a2997.png)

**Comment by PeterPetrik** [comment]
The bug happens only with released compile flags, in debug mode it behaves normally.

**Comment by DrMarkEy** [comment]
I have the same issue. Did you find any workaround yet?
