### ISSUE TITLE
Geopackage zoom problems

### ISSUE THREAD

**Issue by veggydawson** [qgis/QGIS#43053]
Geopackage information is only visible when zoomed to layer extents.

I have checked layer visibility, render flag ... all the 'controls' that may stop it working.  I can only see the geogrpahical objects when zooming to the extents of  the geopackage (via one of the layer extents).  As soon as you zoom in, the information disappears from the display.

1. Download Ordnance Survey or Office of National Statistics geopackages ( https://osdatahub.os.uk/downloads/open/OpenZoomstack  or   https://data.gov.uk/dataset/136da37b-57af-4b3d-bd9a-b31bfcb66a25/pollution-removal-geopackage-updated-version)
2. Start a new clean project in QGIS
3. Right-click and "New Connection" on the Geopackage
4. Open the attached Geopackage and select a layer.
5. Right click on opened layer and click on "Zoom to Layer"
6. Geographic atttributes appear
7. Zoom  in to a smaller area
8. All objects now disappear.

I have tried this on OGIS 3.16.6 and QGIS 3.18 on two different machines and both behave the same way.
Linux Neon - fully updated.

Standard shapefiles, if included in the project, display as expected.

**Comment by gioman** [comment]
@veggydawson if this is a bug report please follow the template

https://github.com/qgis/QGIS/issues/new?assignees=&labels=Bug&template=10_bug_report.md&title=



**Describe the bug**


**How to Reproduce**



1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error -->

**QGIS and OS versions**



**Additional context**

**Comment by veggydawson** [comment]
I have done more investigation into this and, after examining the console, I can see error messages being reported when attempting to zoom into a smaller geographic area.

I get:
`
ERROR 1: failed to prepare SQL: SELECT m."id", m."geom", m."type", m."name" FROM "railway_stations" m JOIN "rtree_railway_stations_geom" r ON m."id" = r.id WHERE r.maxx >= 569014.207900486887 AND r.minx <= 595661.770678204484 AND r.maxy >= 105777.877209302227 AND r.miny <= 125632.722790697590
`
The errors are similar - just different parameters for whichever Geopackage is being used and area selected.

I have examined the contents of the Geopackage by browsing it through a SQL query/editor tool.  All the data is intact, appears to be as it should be, and when running the above query, I get the handful of stations (in this case) that I was expecting.

I don't know why QGIS is failing to prepare the query.

Any ideas?

**Comment by gioman** [comment]
> Any ideas?

@veggydawson attach/link the dataset.

**Comment by veggydawson** [comment]
The dataset is the OpenZoomstack from the start of the post. ...but it seems to behave like this with any Geopackage that is in use.  The one above is 11Gb in size, so I can't really attach it. :-)

**Comment by gioman** [comment]
> The dataset is the OpenZoomstack from the start of the post. ...but it seems to behave like this with any Geopackage that is in use. The one above is 11Gb in size, so I can't really attach it. :-) 

@veggydawson cannot download anything from the second link, and the download from the fist link is 4.27GB, is that ok?

**Comment by veggydawson** [comment]
Yep, that's the one.  When uncompressed it opens up to around 11Gb in size.

**Comment by veggydawson** [comment]
The second link is correct.  You have to open the accordion labelled "View Full Summary" to get to the download links.

**Comment by gioman** [comment]
> I don't know why QGIS is failing to prepare the query.

@veggydawson just tested on clean QGIS installation in clean Windows/Linux machine: no issues zooming in/out at any scale for any of the layers in the dataset you linked. Also no such messages in the QGIS log.

**Comment by veggydawson** [comment]
@gioman Thanks for investigating....I have been looking at it  this afternoon and been investigating the problem. The problem, at least for my two installations on Neon Linux (KDE), is that when the files are first loaded, I can only 'see' objects when zooming to extents.  AS I said earlier the data exists as expected in the gpkg files themselves; checked throughSQL browser.  

I then ran the Vector -> Geometry Tools -> Check Validity which reported now errors....and interestingly, showed the points, in this case, as a layer in a zoomed-in state.  I could navigate around on this validity layer without any issues.

So I now tried a couple of other experiments.  From the OS Open Zoomstack file, I have exported the individual layers (tables) to new gpkg files and connected to these data sources and opened them up in QGIS and everything works on these.

Strange behaviour, but now I have a workaround.

THnaks for your help.

**Comment by gioman** [comment]
Closing as likely a local issue. Reopen if you find that is really a QGIS issue.

**Comment by pblottiere** [comment]
I'm reopening this issue because I have the same issue with a layer based on points and stored in geopackage. Actually, some parts of the points "disappear" while I zoom in/out:

![animation](https://user-images.githubusercontent.com/9266424/119826329-324ce880-bef8-11eb-99fa-c5d5006e3297.gif)

BTW, if I export the layer in another geopackage (`Save vector layer as...`), I don't have the issue anymore.

**Comment by pblottiere** [comment]
I don't think it's a QGIS issue. The culprit lines are here: 

https://github.com/qgis/QGIS/blob/0b511cc88126caae4aae193024aa81701b60d06d/src/core/providers/ogr/qgsogrfeatureiterator.cpp#L397-L404

Actually at some zoom level/extent, we're never going into the `while` clause (so points are not rendered). 

I'm preparing a dataset for reproducing the issue but I think it's probably something for @rouault :).

**Comment by disbr007** [comment]
I'm still hitting this exact issue particularly when writing a new geopackage from geopandas.
