### ISSUE TITLE
PyQGIS

### ISSUE THREAD

**Issue by drwsmnlpg** [qgis/QGIS#43056]
Crash ID: e0cc8cf66db3302e5dd1fa5e1c6b2bed7e898822

Stack Trace

QObject::moveToThread :
QgsProcessingAlgorithm::runPrepared :
QgsProcessingAlgRunnerTask::run :
PyInit__core :
QgsTask::start :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

**Comment by Gustry** [comment]
What do you mean by "PyQGIS" ?
Please, fill all required information when reporting a bug.
https://github.com/qgis/QGIS/issues/new?assignees=&labels=Bug&template=10_bug_report.md&title=

The QGIS project can't do anything about a third party plugin. You must report the issue in the plugin code repository.

You should try with a new QGIS profile.
https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles
