### ISSUE TITLE
Cannot execute cmake

### ISSUE THREAD

**Issue by julian-zhuang** [qgis/QGIS#43069]
-- Found exiv2: /usr/lib/libexiv2.so
-- Found HDF5: /usr/lib/libhdf5.so;/usr/lib/libsz.so;/usr/lib/libz.so;/usr/lib/libdl.so;/usr/lib/libm.so (found version "1.12.0")  
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- Found NetCDF: /lib/libnetcdf.so  
-- Found LibXml2: /usr/lib/libxml2.so (found version "2.9.10") 
CMake Deprecation Warning at external/qt-unix-signals/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Using PROJ <6 srs database.
-- Ctest Binary Directory set to: /home/julian/QGis/QGis_BUild/output/bin
-- Configuring incomplete, errors occurred!
See also "/home/julian/QGis/QGis_BUild/CMakeFiles/CMakeOutput.log".
See also "/home/julian/QGis/QGis_BUild/CMakeFiles/CMakeError.log".

[CMakeOutput.log](https://github.com/qgis/QGIS/files/6419957/CMakeOutput.log)
[CMakeError.log](https://github.com/qgis/QGIS/files/6419958/CMakeError.log)

**Comment by gioman** [comment]
@julian-zhuang please ask questions on the developers mailing list, thanks!
