### ISSUE TITLE
Save icon not enabled with many to many relationship and transaction group enabled

### ISSUE THREAD

**Issue by Djedouas** [qgis/QGIS#43061]
**Describe the bug**
The save icon is not enabled when editing links in many to many relationship with layer form.

**How to Reproduce**
Prepare a simple Postgres schema :

```sql
create schema mtom_test;
create table mtom_test.a (
	id serial primary key
);

create table mtom_test.b (
	id serial primary key
);

create table mtom_test.a_b (
	id serial primary key,
	id_a integer references mtom_test.a on delete cascade,
	id_b integer references mtom_test.b on delete cascade
);

insert into mtom_test.a values (1), (2);
insert into mtom_test.b values (1), (2);
```

Parametrize the many to many relationship

1.  Add the 3 tables to a new QGIS project
1.  In the project properties
    1. add the relations with the discovery tool
    2. activate the transaction groups in the datasource section
1. In layer `a` set up the form to be drag and drop
1.  Add the relation to the form
1.  Configure the relation to have a cardinality on table b (id)
1.  Apply and OK
1.  Repeat steps 4 to 7 on layer `b`
1. Activate edit mode on layer `a` (the edit mode is activated for all layers)
2. Open the attribute table of layer `a` and choose a feature
3. Link this feature with a feature of layer `b`

![image](https://user-images.githubusercontent.com/34267385/116894648-97cbf300-ac32-11eb-8718-5e283a7f3156.png)

A new link has been created in `a_b` and appears in the form, but the main save icon is disabled:

![image](https://user-images.githubusercontent.com/34267385/116895133-293b6500-ac33-11eb-8a48-f1e28927d813.png)

![image](https://user-images.githubusercontent.com/34267385/116895039-0c9f2d00-ac33-11eb-8c19-1a030d2d4cbe.png)

**QGIS and OS versions**

Version de QGIS | 3.16.6-Hannover | Révision du code | bfd36fddc9
-- | -- | -- | --
Compilé avec Qt | 5.15.2 | Utilisant Qt | 5.15.2
Compilé avec GDAL/OGR | 3.2.2 | Utilisé avec GDAL/OGR | 3.2.2
Compilé avec GEOS | 3.9.0-CAPI-1.16.2 | Utilisé avec GEOS | 3.9.0-CAPI-1.16.2
Compilé avec SQLite | 3.34.1 | Fonctionne avec SQLite | 3.34.1
Version du client PostgreSQL | 13.2 (Ubuntu 13.2-1) | Version de SpatiaLite | 5.0.1
Version de QWT | 6.1.4 | Version de QScintilla2 | 2.11.6
Compilé avec PROJ | 7.2.1 | Fonctionne avec PROJ | Rel. 7.2.1, January 1st, 2021
Version de l'OS | Ubuntu 21.04
Extensions Python actives | plugin_reloader; remotedebug; shapefile_encoding_fixer; MetaSearch; processing; db_manager

**Additional context**

When we use the transaction group, the save and edit icons of the relation disapears:

#### Without transaction group:

![image](https://user-images.githubusercontent.com/34267385/116895468-8800de80-ac33-11eb-8e13-94c1d4c1ee97.png)

#### With transaction group:

![image](https://user-images.githubusercontent.com/34267385/116895556-9ea73580-ac33-11eb-9c77-ec27eef4d873.png)

So we must rely on the main save icon which is not enabled then.

**Comment by elpaso** [comment]
I'm testing this in master and 3.18 and QGIS crashes badly. I'm not sure that the crash is related to the bug you are describing here but it makes it impossible to reproduce this issue for me.

**Comment by elpaso** [comment]
Confirmed, no crashes now.

@suricactus @signedav this bug is coming from your modifications in https://github.com/qgis/QGIS/blob/master/src/gui/qgsrelationeditorwidget.cpp#L312 .

I see two options here: 

1. enable save edits (and maybe also toggle editing) in the embedded editor when same transaction group (basically reverting your commits there)
2. in QgsAttributeTableDialog construct a list of related layers and connect the layer modified signal to QgsAttributeTableDialog::updateLayerModifiedActions (and change the check to include all related layers)

What do you think?

**Comment by elpaso** [comment]
Yes, that would be option 2, it's the preferred one IMHO.

**Comment by signedav** [comment]
Ah okay. Yes. I would prefer that as well.
