### ISSUE TITLE
QGIS stops requesting WMS layer

### ISSUE THREAD

**Issue by ItaloCunhaBueno** [qgis/QGIS#43071]
I have configured dozens of geoserver WMS layers, when added to QGIS, it reproject and display the layers just fine, checking the request log with F12 shows all requests as it should.

The issue: after some time, QGIS stops requesting the WMS layer and it disappears from the canvas. Clicking in 'Zoom to layer', adjusts canvas extent to layer extent correctly, but the layer does not show.

**Here's a screenshot of the requests:**

![image](https://user-images.githubusercontent.com/47254894/116994727-78bf7680-acaf-11eb-8e8b-a238fb316dec.png)

inside the yellow square are all the correct requests wich have returned image just fine, outside the square, each pair of lines was me removing and adding the layer to see if it reappears, with no success.

**A normal successful request looks like this:**
![image](https://user-images.githubusercontent.com/47254894/116994935-c9cf6a80-acaf-11eb-80d6-bcb12400acda.png)

**the pair of requests after it stops working, looks like this:**
![image](https://user-images.githubusercontent.com/47254894/116995093-000cea00-acb0-11eb-9259-bf4a0e957815.png)
![image](https://user-images.githubusercontent.com/47254894/116995133-0e5b0600-acb0-11eb-8c47-11a95480da9c.png)

**The Geoserver log after everything stops working looks like this:**

```
2021-05-04 07:50:55,597 INFO [geoserver.wms] - 
Request: getServiceInfo
2021-05-04 07:50:55,597 INFO [geoserver.wms] - 
Request: getCapabilities
	BaseUrl = http://10.0.0.18:8080/geoserver/
	Get = false
	Namespace = null
	RawKvp = {TILED=true, HINTS=quality, REQUEST=GetCapabilities, BGCOLOR=0x000000, VERSION=1.1.1, SERVICE=WMS, TRANSPARENT=true}
	Request = GetCapabilities
	RequestCharset = null
	RootLayerEnabled = null
	UpdateSequence = null
	Version = 1.1.1
2021-05-04 07:50:55,957 INFO [geoserver.wms] - 
Request: getServiceInfo
2021-05-04 07:50:55,957 INFO [geoserver.wms] - 
Request: getLegendGraphic
	BaseUrl = http://10.0.0.18:8080/geoserver/
	Env = {}
	Exceptions = SE_XML
	FeatureType = null
	Format = image/png
	Get = false
	Height = 20
	Kvp = {FORMAT=image/png, STYLE=, MAP_RESOLUTION=95, WIDTH=20, HEIGHT=20, REQUEST=GetLegendGraphic, SLD_VERSION=1.1.0, FORMAT_OPTIONS={DPI=95}, VERSION=1.1.1, SERVICE=WMS, SCALE=0.000000, LAYER=REURB_IMAGENS:OS_001_PalhocaPontal_22S_07102019, DPI=95, TRANSPARENT=true}
	Layers = [SimpleFeatureTypeImpl http://www.opengis.net/gml:GridCoverage identified extends Feature(geom:geom,grid:grid,params:params)]
	LegendOptions = {}
	Legends = [LegendRequest [layer=REURB_IMAGENS:OS_001_PalhocaPontal_22S_07102019, name=REURB_IMAGENS:OS_001_PalhocaPontal_22S_07102019 styleName=raster, title=OS_001_PalhocaPontal_22S, legendInfo=null]]
	Locale = null
	RawKvp = {FORMAT=image/png, STYLE=, MAP_RESOLUTION=95, WIDTH=20, HEIGHT=20, REQUEST=GetLegendGraphic, SLD_VERSION=1.1.0, FORMAT_OPTIONS=dpi:95, VERSION=1.1.1, SERVICE=WMS, SCALE=0.000000, LAYER=REURB_IMAGENS:OS_001_PalhocaPontal_22S_07102019, DPI=95, TRANSPARENT=true}
	Request = GetLegendGraphic
	RequestCharset = null
	Scale = 0.0
	Strict = true
	Transparent = true
	Version = 1.1.1
	Width = 20
	Wms = org.geoserver.wms.WMS@22e2fee6
```
**The geoserver log before everything stops looks like a repeated bunch of these lines:**

```
2021-05-04 07:34:20,593 WARN [lite.gridcoverage2d] - Could not reduce the grid geometry inside the valid area bounds: ReferencedEnvelope[-2.147483647E9 : 2.147483647E9, -85.0 : 85.0]
Grid geometry isGridGeometry2D[GeneralGridEnvelope[0..311, 0..316], PARAM_MT["Affine", 
  PARAMETER["num_row", 3], 
  PARAMETER["num_col", 3], 
  PARAMETER["elt_0_0", 0.998397435897436], 
  PARAMETER["elt_0_2", 733018.16469], 
  PARAMETER["elt_1_1", -0.6982649842271293], 
  PARAMETER["elt_1_2", 6932579.77884]]]
2021-05-04 07:34:20,593 WARN [lite.gridcoverage2d] - Could not reduce the grid geometry inside the valid area bounds: ReferencedEnvelope[-2.147483647E9 : 2.147483647E9, -85.0 : 85.0]
Grid geometry isGridGeometry2D[GeneralGridEnvelope[0..303, 0..308], PARAM_MT["Affine", 
  PARAMETER["num_row", 3], 
  PARAMETER["num_col", 3], 
  PARAMETER["elt_0_0", 1.0485197368421053], 
  PARAMETER["elt_0_2", 732747.26469], 
  PARAMETER["elt_1_1", -0.6995145631067962], 
  PARAMETER["elt_1_2", 6932579.77884]]]
```

For now, the only way to make QGIS show the layer correctly again is to shut QGIS down and open the project again. After some time the problem returns.

**Other useful information:**

QGIS network settings:

![image](https://user-images.githubusercontent.com/47254894/116995739-d4d6ca80-acb0-11eb-9311-f0a619e0a354.png)

Geoserver WMS settings:

![image](https://user-images.githubusercontent.com/47254894/116995847-f6d04d00-acb0-11eb-96c0-38d108f8b8b4.png)

QGIS about info:

```
QGIS version
3.16.6-Hannover
QGIS code revision
bfd36fddc9
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
DataPlotly; 
LAStools; 
LoadQSS; 
new_layer_from_selection; 
nominatim_locator_filter; 
plugin_reloader; 
Qgis2threejs; 
qgis2web; 
quick_map_services; 
StreetView; 
db_manager; 
MetaSearch; 
processing

```

I dont think it's a Geoserver problem because it appears that QGIS simply stops requesting the layer (in opposite to show bad request errors).

Any help is welcome. Thanks.

**Comment by gioman** [comment]
> Any help is welcome. Thanks.

@ItaloCunhaBueno does it happens only with this specific endpoint or it happens also with others?

**Comment by ItaloCunhaBueno** [comment]
I had two other people in our network complaining about this exact behaviour. So, yes, it happens in other clients accessing these WMS layers.

**Comment by gioman** [comment]
>  So, yes, it happens in other clients

@ItaloCunhaBueno my question is the other way around, it happens using other (server) endpoints? Does it happens outside your network?

**Comment by ItaloCunhaBueno** [comment]
Our network is not open so I cant tell if it happens to outside access, about other WMS services, I will search for a public WMS link and test it.

**Comment by gioman** [comment]
> Our network is not open so I cant tell if it happens to outside access, about other WMS services, I will search for a public WMS link and test it.

@ItaloCunhaBueno you have to test also outside your network, using a public endpoint, to rule out that the issue is in your network.

**Comment by ItaloCunhaBueno** [comment]
> > Our network is not open so I cant tell if it happens to outside access, about other WMS services, I will search for a public WMS link and test it.
> 
> @ItaloCunhaBueno you have to test also outside your network, using a public endpoint, to rule out that the issue is in your network.

This I cant do, company rules. But would that explain why QGIS is not even trying to request the tiles?

**Comment by gioman** [comment]
> This I cant do, company rules.

@ItaloCunhaBueno you can't test QGIS on a personal PC?

**Comment by ItaloCunhaBueno** [comment]
> > This I cant do, company rules.
> 
> @ItaloCunhaBueno you can't test QGIS on a personal PC?

Well, let me explain my setup:

I'm working from home (bnecause COVID) as every other employee in the company I work, we all use a VPN to connect to the company's network. The geoserver is located in the company's network, wich is not open to the public (hense the VPN) and I cant expose the geoserver services to the public.

My access to the internet does not pass through the VPN (I have internet access with vpn turned off), so I dont think it's something to do with the VPN.

I just tested several layers in a public WMS service and the problem persist, so (thankfully for me) it's not a problem in our geoserver configuration. Must be something in QGIS. And if it's a QGIS configuration problem, it's a default configuration problem because other employees (that arent tech savvy and problably didnt change QGIS configs) are having the same issue.

**Comment by gioman** [comment]
> I just tested several layers in a public WMS service and the problem persist, so (thankfully for me) it's not a problem in our geoserver configuration. Must be something in QGIS. And if it's a QGIS configuration problem, it's a default configuration problem because other employees (that arent tech savvy and problably didnt change QGIS configs) are having the same issue.

@ItaloCunhaBueno are you all using the VPN? if yes you must remove the VPN from the equation. Just test a public endpoint without using the VPN.

**Comment by ItaloCunhaBueno** [comment]
I have now shutdown the VPN and added a plublic WMS layer (https://geoservicos.ibge.gov.br/geoserver/CGEO/ows?SERVICE=WMS&)

**Comment by ItaloCunhaBueno** [comment]
I have now shutdown the VPN and QGIS and start all over. I added some public layers:

https://geoservicos.ibge.gov.br/geoserver/CGEO/ows?SERVICE=WMS&

Still, same behaviour, after some time QGIS stops requesting the layer and what was already there disappears (you dont even have to change zoom level, just panning the canvas makes the layer disappears).

So, VPN out of equasion, our geoserver config out of equasion too.

**Comment by gioman** [comment]
> https://geoservicos.ibge.gov.br/geoserver/CGEO/ows?SERVICE=WMS&
> 
> Still, same behaviour, after some time QGIS stops requesting the layer and what was already there disappears (you dont even have to change zoom level, just panning the canvas makes the layer disappears).

@ItaloCunhaBueno I have added 10/12 layers from the above service, and in a few minutes of zooming and panning I have not lost the visibility of any layer. Can You post a screencast of what you observe? Thanks.

**Comment by ItaloCunhaBueno** [comment]
let qgis rest still for some minutes and see if it disappears when you move. I will try to record a video later today.

**Comment by gioman** [comment]
> let qgis rest still for some minutes

@ItaloCunhaBueno vou almoçar, let's see what happens after.

**Comment by ItaloCunhaBueno** [comment]
Here's is some recording of the problem:

https://drive.google.com/file/d/1yDGZU4gGQChL4kdGmfDUmC8Z4jfKsN7y/view?usp=sharing

Since the problem happened with VPN off and everything we discussed until now, I used my original setup (company's geoserver and VPN):

I added some vector layer just to force QGIS to reproject the WMS layer, then added the WMS, everything works fine (requests are made in the right panel), I then let QGIS rest still for 2 minutes, then pan the canvas. 
As you can see, the WMS layer disappears. To prove that QGIS think it's there, I 'zoom to layer' (for some reason record doesnt show right click menus), QGIS pan with success to the layer extent. The right panel does not show any request being made.
I then remove the layer and add it again, and itial request is made but nothing else.

**Comment by gioman** [comment]
> @ItaloCunhaBueno vou almoçar, let's see what happens after.

@ItaloCunhaBueno left qgis idle for over 1 hour, changed connection from cable to wireless > no issues. With the above public endpoint it works without issues. This do not seems to be a general QGIS issue. Have you tried with a new QGIS profile and see if it makes any difference?

**Comment by ItaloCunhaBueno** [comment]
Created a new profile, same result as in the video, after 2 minutes the layer disappears.

**Comment by gioman** [comment]
> Created a new profile, same result as in the video, after 2 minutes the layer disappears.

@ItaloCunhaBueno ok, it was worth giving a try. Still not a general QGIS issue in my opinion (and after having tested several different endpoints and different versions of QGIS on different platforms).

**Comment by ar-siddiqui** [comment]
Have been using WMS layers a lot in QGIS of late, and this issue has never occurred to me.

**Comment by ItaloCunhaBueno** [comment]
It's probably a Geoserver problem but still, it doesn't explain why QGIS don't even log it trying to request new tiles... Is it possible that geoserver is "banning" the client process that is requesting, and when I restart QGIS I'm able to request againd because it's using a new process ID?
