### ISSUE TITLE
is there a QGIS Add-on that imports an external text-file?

### ISSUE THREAD

**Issue by bertramrabe** [qgis/QGIS#43084]
Is there an addon in QGIS that is able to do the following steps:

QGIS imports an external text-file, opens the project and jumps to the (only) polygon that contains „xyz“ in „field1“.

the external file contains the following information:
name of the qgis-project
name of the layer (e.g. polygon-layer) – for example layer1
name of a field in this layer – for example „field1“
content of this field - for example „xyz“

**Comment by gioman** [comment]
Please raise questions in the users or developers mailing lists.

**Comment by bertramrabe** [comment]
Am Wed, 5 May 2021 07:05:47 -0700, Giovanni Manghi schrieb:
> Please raise questions in the users or developers mailing lists.
>

Where do I find the mailing list?

--
Gesendet  vom Ubuntu-Tablet

**Comment by Gustry** [comment]
https://gis.stackexchange.com/ is very good for asking questions.
Or QGIS Mailing list https://www.qgis.org/fr/site/getinvolved/mailinglists.html
