### ISSUE TITLE
Expression help display broken for operators

### ISSUE THREAD

**Issue by Houska1** [qgis/QGIS#43080]
The help display for expressions fails to show the argument information that is present in the `/resources/function_help/json` file for operators. It is shown correctly for *functions* as opposed to *operators*.

As illustration, compare the help for the `LIKE` operator and the `abs` function.
![Screen_Capture_ed-_5_May__6_18_am](https://user-images.githubusercontent.com/48919900/117128163-0c09b200-ad6b-11eb-94fc-aa740a1d4efe.png)

However, in https://github.com/qgis/QGIS/blob/master/resources/function_help/json/LIKE information on the arguments (wildcards, etc.) is provided:

```
  "arguments": [
    {"arg":"string/number","description":"value"},
    {"arg":"pattern","description":"pattern to compare value with, you can use '%' as a wildcard, '_' as a single char and '\\\\' to escape."}
  ],
```

The same is true for other operators. 

OSGeo4W master and 3.18.x release.

**Comment by gioman** [comment]
@Houska1 worked fine in a previous release?

**Comment by Houska1** [comment]
@gioman, not sure. I don't have LTR on this laptop, so can't verify that. I found the problem since I was intending to sit down and improve the help for the LIKE operator, having found it not specific enough when I accessed it a few months ago. And when I started editing, I saw the json actually had the specifics I wasn't seeing! So I infer that it was already broken in 3.10 and/or 3.12. But probably not broken at some point in the past, since presumably whoever entered argument information in the help json for all operators would have at that time checked it worked.

**Comment by nicogodet** [comment]
It's OK on 2.18 and JSON is the same : 
https://github.com/qgis/QGIS/blob/28c0380166078bcf6605f3784fb87944d5ee688b/resources/function_help/json/LIKE#L5L8
![image](https://user-images.githubusercontent.com/39594821/117166036-4fddd500-adc6-11eb-995a-b6537c011f4b.png)

**Comment by nicogodet** [comment]
Broken on 3.16.6 too

**Comment by Houska1** [comment]
Hmm. Anyone with source who can check the `qgsexpression_texts.cpp` generated by `/resources/process_function_template.py`? In particular, does the argument info for `LIKE` (or other operators) get included? And is the Syntax section right above it valid HTML?

My money is on line 33 of  `/resources/process_function_template.py` choking on operators, therefore generating some unbalanced `<div>` or `<span>` or somesuch that doesn't get cleared out until the end of the subsequent arguments section, failing to display valid argument information in the meanwhile. But that's just a guess.

**Comment by DelazJ** [comment]
@Houska1 something like this you want (found in build/src/core/gsexpression_texts.cpp)?

    functionHelpTexts().insert( QStringLiteral( "LIKE" ),
      Help( QStringLiteral( "LIKE" ), tr( "operator" ), tr( "Returns 1 if the first parameter matches the supplied pattern. Works with numbers also." ),
        QList<HelpVariant>()
          << HelpVariant( tr( "LIKE" ), tr( "Returns 1 if the first parameter matches the supplied pattern. Works with numbers also." ),
            QList<HelpArg>(),
            /* variableLenArguments */ false,
            QList<HelpExample>()
              << HelpExample( tr( "'A' LIKE 'A'" ), tr( "1" ), tr( "" ) )
              << HelpExample( tr( "'A' LIKE 'a'" ), tr( "0" ), tr( "" ) )
              << HelpExample( tr( "'A' LIKE 'B'" ), tr( "0" ), tr( "" ) )
              << HelpExample( tr( "'ABC' LIKE 'B'" ), tr( "0" ), tr( "" ) )
              << HelpExample( tr( "'ABC' LIKE '_B_'" ), tr( "1" ), tr( "" ) )
              << HelpExample( tr( "'ABCD' LIKE '_B_'" ), tr( "0" ), tr( "" ) )
              << HelpExample( tr( "'ABCD' LIKE '_B%'" ), tr( "1" ), tr( "" ) )
              << HelpExample( tr( "'ABCD' LIKE '%B%'" ), tr( "1" ), tr( "" ) )
              << HelpExample( tr( "'1%' LIKE '1\\%'" ), tr( "1" ), tr( "" ) )
              << HelpExample( tr( "'1_' LIKE '1\\%'" ), tr( "0" ), tr( "" ) ),
            QString()
         )
        )
      );

**Comment by Houska1** [comment]
Thanks @DelazJ  Seems I was on the wrong path; looks like qgs_expressionstext.cpp is (now) being generated differently, beyond my ability to effectively play detective. It seems clear from what you pasted, however, that the bug is in whatever code generates this .cpp file from the resources/function_help/json/* for operators.
