### ISSUE TITLE
QgsMapCanvas.fullExtent() returns false extent

### ISSUE THREAD

**Issue by jakimowb** [qgis/QGIS#43097]
**Description**

According to the docs, `QgsMapCanvas::fullExtent()` returns _the combined extent for all layers on the map canvas_.  
Unfortunately this is not true, as `fullExtent` returns the QgsProject extent (defined in `QgsProjectViewSettings::fullExtent()`) by calling `QgsProject::instance()->viewSettings()->fullExtent()`) in:

````
QgsRectangle QgsMapCanvas::fullExtent() const
{
  const QgsReferencedRectangle extent = QgsProject::instance()->viewSettings()->fullExtent();
  QgsCoordinateTransform ct( extent.crs(), mapSettings().destinationCrs(), QgsProject::instance()->transformContext() );
  ct.setBallparkTransformsAreAppropriate( true );
  QgsRectangle rect;
  try
  {
    rect = ct.transformBoundingBox( extent );
  }
  catch ( QgsCsException & )
  {
    rect = mapSettings().fullExtent();
  }

  return rect;
}
````

This probably affects every `QgsMapCanvas` instance with an layer set different to that in the main QGIS map canvas.
In consequence, functions like `QgsMapCanvas::zoomToFullExtent()` operate in an unintended way.

A solution might be to switch the exception logic and return `mapSettings().fullExtent()` by default, as it is generated on the canvas layer stack only. However, I am not aware of possible side-effects on other parts of the QGIS Main App.

**How to Reproduce**

1. Start QGIS
2. Run this python code in the QGIS command line

````
from qgis.core import QgsVectorLayer, QgsProject, QgsApplication, QgsFeature, QgsPointXY, QgsGeometry
from qgis.gui import QgsMapCanvas
import pathlib

# similar issues:
#

# add the "world" vectorlayer to QGIS to
# initialize QgsProject.instance() with a project CRS
uri_world = pathlib.Path(QgsApplication.pkgDataPath()) / 'resources' / 'data' / 'world_map.gpkg'
uri_world = uri_world.as_posix() + '|layername=countries'
lyrWorld = QgsVectorLayer(uri_world)
assert lyrWorld.isValid()
QgsProject.instance().addMapLayers([lyrWorld])

# create layer with a smaller extent
uri = r'Point?crs=epsg:32621&field=id:integer&field=name:string(20)&index=yes'
lyr = QgsVectorLayer(uri, 'small layer', 'memory')
assert lyr.startEditing()
# add 2 points
feat1 = QgsFeature(lyr.fields())
feat1.setGeometry(QgsGeometry.fromPointXY(QgsPointXY(300000, 30000)))
feat2 = QgsFeature(lyr.fields())
feat2.setGeometry(QgsGeometry.fromPointXY(QgsPointXY(400000, 40000)))
lyr.addFeatures([feat1, feat2])
assert lyr.commitChanges()

# add layer to canvas
QgsProject.instance().addMapLayer(lyr, False)
canvas = QgsMapCanvas()
canvas.setLayers([lyr])

print(f'Layer extent: {lyr.extent()}')
print(f'Canvas fullExtent: {canvas.fullExtent()}')

````
The printout shows the heavy difference between `fullExtent()` and the extent of the true canvas layer: 

````
Layer extent: 500000 60000, 550000 61000
Canvas extent: 500000 41769.59247648902237415, 550000 79230.40752351097762585
 fullExtent(): -14449896.52385975793004036 -19649597.96110930666327477, 17169146.12797296047210693 19470285.80787219107151031
````

**QGIS and OS versions**

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.19.0-Master | QGIS code revision | cd3493bba
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.0
GDAL/OGR version | 3.2.2
PROJ version | 8.0.0
EPSG Registry database version | v10.015 (2021-02-11)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.2.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009

</body></html>

**Comment by elpaso** [comment]
@jakimowb 

the current QGIS master logic is: https://github.com/qgis/QGIS/blob/master/src/gui/qgsmapcanvas.cpp#L1110

Can you please check if this implementation solves this issue?

**Comment by jakimowb** [comment]
Thanks @elpaso, with the current master _canvas.fullExtent()_ seems to be correct now.
