### ISSUE TITLE
Bug in histogram visualization for images of type "Byte"

### ISSUE THREAD

**Issue by attozeta** [qgis/QGIS#43098]
**Describe the bug**

When displaying a multiband color histogram, it gets displayed wrong - it seems that the x-axis is stretched wrongly? **EDIT**: this seems only to be the case if the image is of type Byte.

**How to Reproduce**

Open the provided file, double-click it in "Layers" and switch to "Histogram".

**QGIS and OS versions**

QGIS version | 3.18.2-Zürich
QGIS code branch | Release 3.18
Compiled against Qt | 5.15.2
Running against Qt | 5.15.2
Compiled against GDAL/OGR | 3.2.2
Running against GDAL/OGR | 3.2.2
Compiled against GEOS | 3.9.0-CAPI-1.16.2
Running against GEOS | 3.9.0-CAPI-1.16.2
Compiled against SQLite | 3.34.1
Running against SQLite | 3.34.1
PostgreSQL Client Version | 13.2
SpatiaLite Version | 5.0.1
QWT Version | 6.1.5
QScintilla2 Version | 2.11.5
Compiled against PROJ | 7.2.1
Running against PROJ
Rel. 7.2.1, January 1st, 2021
OS Version | Fedora 34 (Workstation Edition)

![example tif justrenameit](https://user-images.githubusercontent.com/8096393/117294810-5e35fa80-ae73-11eb-8082-24350837a23c.png)
![how_it_does_look](https://user-images.githubusercontent.com/8096393/117294830-64c47200-ae73-11eb-9c9c-b9f74f26c50d.png)
![how_it_should_look_like](https://user-images.githubusercontent.com/8096393/117294838-67bf6280-ae73-11eb-9228-a8fe7d9d3f21.png)

**Comment by attozeta** [comment]
Note to the attachments: First is a 3-band byte tif (provided as .png as GitHub does not allow .tiffs, but you can download it and rename it), with the following `gdalinfo`:

```
Driver: GTiff/GeoTIFF
Files: example.tif.justrenameit.png
Size is 858, 685
Coordinate System is:
PROJCRS["MGI / Austria GK M34",
    BASEGEOGCRS["MGI",
        DATUM["Militar-Geographische Institut",
            ELLIPSOID["Bessel 1841",6377397.155,299.1528128,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4312]],
    CONVERSION["Austria Gauss-Kruger M34",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",16.3333333333333,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",1,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",750000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",-5000000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["northing (X)",north,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["easting (Y)",east,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["Engineering survey, topographic mapping."],
        AREA["Austria east of 14°50'E of Greenwich (32°30'E of Ferro)."],
        BBOX[46.56,14.83,49.02,17.17]],
    ID["EPSG",31259]]
Data axis to CRS axis mapping: 2,1
Origin = (678252.000000000000000,218623.000000000000000)
Pixel Size = (10.000000000000000,-10.000000000000000)
Metadata:
  ABSTRACT=Basemap als farbiges Orthofoto
  AREA_OR_POINT=Area
  TITLE=Geoland Basemap Orthofoto
Image Structure Metadata:
  INTERLEAVE=PIXEL
Corner Coordinates:
Upper Left  (  678252.000,  218623.000) ( 15d23'16.93"E, 47d 6'11.54"N)
Lower Left  (  678252.000,  211773.000) ( 15d23'20.85"E, 47d 2'29.73"N)
Upper Right (  686832.000,  218623.000) ( 15d30' 3.84"E, 47d 6'14.70"N)
Lower Right (  686832.000,  211773.000) ( 15d30' 7.29"E, 47d 2'32.88"N)
Center      (  682542.000,  215198.000) ( 15d26'42.23"E, 47d 4'22.26"N)
Band 1 Block=858x3 Type=Byte, ColorInterp=Red
  Minimum=0.000, Maximum=255.000, Mean=111.999, StdDev=40.918
  Metadata:
    STATISTICS_MAXIMUM=255
    STATISTICS_MEAN=111.99915437361
    STATISTICS_MINIMUM=0
    STATISTICS_STDDEV=40.917755936617
    STATISTICS_VALID_PERCENT=100
Band 2 Block=858x3 Type=Byte, ColorInterp=Green
  Minimum=0.000, Maximum=255.000, Mean=109.240, StdDev=39.983
  Metadata:
    STATISTICS_MAXIMUM=255
    STATISTICS_MEAN=109.24033995202
    STATISTICS_MINIMUM=0
    STATISTICS_STDDEV=39.983059464216
    STATISTICS_VALID_PERCENT=100
Band 3 Block=858x3 Type=Byte, ColorInterp=Blue
  Minimum=11.000, Maximum=255.000, Mean=106.549, StdDev=38.638
  Metadata:
    STATISTICS_MAXIMUM=255
    STATISTICS_MEAN=106.54939513042
    STATISTICS_MINIMUM=11
    STATISTICS_STDDEV=38.638074559416
    STATISTICS_VALID_PERCENT=100
```
Second image is how it's displayed for me in QGis and third image is the correct histogram (generated via imagemagick) and doublechecked with Gimp.

**Comment by gioman** [comment]
@attozeta same as https://github.com/qgis/QGIS/issues/39512 ?

**Comment by attozeta** [comment]
I don't think so.

It seems that the x-axis scaling is wrong - and only if the type of the image is 'Byte'.

**Comment by gioman** [comment]
> **EDIT**: this seems only to be the case if the image is of type Byte.

@attozeta attach here a sample, thanks.
