### ISSUE TITLE
I am new to all these and plan to use QGIS for my research paper but while installing, it says it's having an error to write testbase.py

### ISSUE THREAD

**Issue by mochifo** [qgis/QGIS#43102]
I'm a noob to all these and I'm sorry if my concern is a bit shallow :(( I've already deleted the program files and the installer three times but each time would lead to the same error. :(

Here is a picture of my situation while installing it:

![image](https://user-images.githubusercontent.com/83772136/117315109-f787ff80-aeb9-11eb-95e8-af09c5fc2572.png)

**Comment by gioman** [comment]
@mochifo questions have to be posted on the users or developers mailing lists. This facility is only for bug reports and feature requests. Thanks!

**Comment by gioman** [comment]
PS the installer you downloaded seems corrupted.

**Comment by mochifo** [comment]
I'm sorry! I'm totally new here, and I already sent an email to the user email. Thank you!



> PS the installer you downloaded seems corrupted.

I've downloaded the installer from their website: https://www.qgis.org/en/site/forusers/download.html

I still don't have a clue if should just download the stable version rather than the richest features one :(

Btw, thanks for your insight! ^ ^
