### ISSUE TITLE
Unexplained crash when trying to select coordinates from the map canvas (when triggering script via Python)

### ISSUE THREAD

**Issue by paulwittle** [qgis/QGIS#43100]
## User Feedback

I create a script with the following code:
def initAlgorithm(self, config=None):
        self.addParameter(QgsProcessingParameterPoint(self.ORIG, 'Origin coordinates',None,True))

    def processAlgorithm(self, parameters, context, feedback):
        originPoint = self.parameterAsPoint(parameters, self.ORIG, context)

This creates a dialog with the three dot button to pick a point from the map canvas. 

If you run it from the Processing Toolbox it is all fine but if you run it from the Python console using processing.createAlgorithmDialog(\"script:crashexample\",{}).show() it crashes QGIS. 

I'm running it on Windows 10 Home Version 20H2 with QGIS 3.16 Hannover. 

## Report Details

**Crash ID**: [cbe00a70e88eeac853c033c159a67773141e1d58](https://github.com/qgis/QGIS/search?q=cbe00a70e88eeac853c033c159a67773141e1d58&type=Issues)

**Stack Trace**
<pre>
QWidget::showMinimized :
QMetaObject::activate :
QgsProcessingPointPanel::toggleDialogVisibility :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.16.1-Hannover
QGIS code revision: b381a90dca
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

**Additional context**

Full script I'm using to replicate the bug can be found at https://pastebin.com/UaS4rWFW 

I have found the bug to occur on my work devices but this report was from my personal device with no corporate settings. That said; GeoSolutions have also attempted to replicate the error but it did not happen for them so I'm not sure if it will happen 100% of the time.

**Comment by gioman** [comment]
@paulwittle you should submit your script in the users or developers mailing lists, if is not correct there is always a chance to crash the program

**Comment by paulwittle** [comment]
Hi,

The script has already been posted in the mailing list but I don't think anyone noticed it.

Please don't be confused by the script; it is all default so I don't think it has anything to do with the script itself. We are finding QGIS crashes in this way at a number of times but the script seems to make the issue replicatable.

I simply needed something I could share which will hopefully allow others to replicate the issue.

Have you tried running it to see if it crashes for you?

Thanks,
Paul

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by paulwittle** [comment]
Hi,

On the point about local issues. Now I know it crashes on my home pc as well I'd say it is not.

That is sort of the point of the bug report really as I need to know if it crashes for anyone else.

The only key point is that it is installed on Windows not Linux but who knows...it might crash on Linux as well.

I know it doesn't crash in every context but I wanted to see if anyone else finds it crashes for them?
Paul

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by roya0045** [comment]
yes the use of `self.addParameter(QgsProcessingParameterPoint(self.ORIG, 'Origin coordinates',None,True))` seem to be the issue, no stack trace just hanging and vanished.

**Comment by gioman** [comment]
> def initAlgorithm(self, config=None):
> self.addParameter(QgsProcessingParameterPoint(self.ORIG, 'Origin coordinates',None,True))
> 
> ```
> def processAlgorithm(self, parameters, context, feedback):
>     originPoint = self.parameterAsPoint(parameters, self.ORIG, context)
> ```

@paulwittle is this supposed to show in the "scripts" group of the Processing toolbox?

Can you please attach the script, maybe I'm missing something obvious?

**Comment by chpicone** [comment]
I was able to replicate this issue too and looking at the stack trace I was supposing the problem happens when QGIS is trying to minimize the QDialog panel to make the user able to interact with the map canvas.
I took a look on the **qgsprocessingwidgetwrapperimpl.cpp**, method **QgsProcessingPointPanel::selectOnCanvas()**.
Here I guess something wrong emitting the **toggleDialogVisibility** signal.

**Comment by paulwittle** [comment]
Hi @gioman 
The full script should be available via https://pastebin.com/UaS4rWF
If you put it in your processing folder then it should appear under Scripts>Debugging Scripts>Crash Example

Thank you for investigating this for me @chpicone. It is really useful to start identifying the cause. 

I'm sure this used to work at some point but I'm not sure which version it was now; it may have been quite an early version of QGIS v3. 

In case you missed the context, the reason is simply that I wanted to put a button in the toolbars calling the script so the users don't need to open the processing toolbox. As I say the functionality should be pretty common usage (I would have thought) and I know it worked originally because I would not have released it if was crashing QGIS. That said; it is also possible that I wrote it for version 2.18 and perhaps it has never worked since version 3 in which case the breaking change may be in the python version as well. 

Anyway; my goal is simply to have a button which fires a script without crashing QGIS. 

If there is a better way then I'd be happy to hear it :-) Thanks

**Comment by rouault** [comment]
I can't replicate on Linux using QGIS master

**Comment by paulwittle** [comment]
Hi, 
Sorry for now getting back on this. I still encounter this issue periodically however slightly less frequently when not using the script example. I think it is definitely linked to plugins because we as have shown it seems to be linked to minimizing QDialog panels.

Interesting that you can't replicate it on Linux but not massively a surprise to me as I think it would be more likely to have gone unnoticed if it only impacts Windows users. 

What do we need to do to get the issue fixed? Presumably it needs funding?

**Comment by gioman** [comment]
> What do we need to do to get the issue fixed? Presumably it needs funding?

@paulwittle if it is confirmed as a QGIS core issue then if you want the bug solved sooner than later you can contact one of the many developers/companies listed in the "commercial  support" of QGIS's site.

**Comment by paulwittle** [comment]
> I was able to replicate this issue too and looking at the stack trace I was supposing the problem happens when QGIS is trying to minimize the QDialog panel to make the user able to interact with the map canvas. I took a look on the **qgsprocessingwidgetwrapperimpl.cpp**, method **QgsProcessingPointPanel::selectOnCanvas()**. Here I guess something wrong emitting the **toggleDialogVisibility** signal.

Well I'm not sure where the issue is exactly but I think the message above was the closest to tracking it down. However does it mean the issue is actually linked to the QT code? I've I'm honest I've slept and few times since I last looked at this and forgotten where I had got to. I will try to refresh my memory at work tomorrow and reply more sensibly.
