### ISSUE TITLE
Allow Limiting the request For WCS Data to Extents Only

### ISSUE THREAD

**Issue by ar-siddiqui** [qgis/QGIS#43107]
**Feature description.**
WCS coverages are often huge in size while working with them if you zoom out of the map, QGIS will fire hundreds of requests for the data making it almost impossible to work for quite some time. 

QGIS will rock even more if WCS requests can also be limited to Extents like how WFS can be limited to an extent.

**Additional context**
This feature request is linked to #43106

Example data set 
https://elevation.nationalmap.gov/arcgis/services/3DEPElevation/ImageServer/WCSServer?

1. Loaded the layer in the map > map defaults to layer extent.
2. Now wanted to zoom in to an area, so zoomed in, the QGIS start sending hundreds of requests, making it impossible to do anything.

If there was an option to limit to an extent, this could be avoided.

![image](https://user-images.githubusercontent.com/53625184/117351093-50847300-ae7b-11eb-9f18-48eea1117049.png)

QGIS version
3.18.2-Zürich
QGIS code revision
515138c171
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
area_weighted_average; 
batchvectorlayersaver; 
changeDataSource; 
curve_number_generator; 
DataPlotly; 
mapswipetool_plugin; 
MemoryLayerSaver; 
MultipleLayerSelection; 
profiletool; 
QGIS3-getWKT; 
searchlayers; 
send2google_earth; 
spline; 
StreetView; 
valuetool; 
db_manager; 
processing

**Comment by ar-siddiqui** [comment]
#43106

**Comment by alexbruy** [comment]
Duplicates #42528?
