### ISSUE TITLE
"show label" is disabled in widget designer but label keeps displaying in attribute form if you use tabs in the Drag and-Drop Designer and the field widget was placed in any tab

### ISSUE THREAD

**Issue by lindacamathias** [qgis/QGIS#43103]
"show label" is disabled in widget designer but label keeps displaying in attribute form

**How to Reproduce**
1. attributes form: drag and drop designer
2. Click on a layer
3. widget display: **disable "Show label"**

![image](https://user-images.githubusercontent.com/77726342/117330385-eb8a4680-ae95-11eb-8c02-51ec9945ff41.png)
4. apply and ok
5. create a new feature: **attribute formular**

![image](https://user-images.githubusercontent.com/77726342/117332312-f645db00-ae97-11eb-9d32-1334ea21d82c.png)

-> **the label** (here the Alias "Kategorie" **is still displayed** 

when there is no alias defined, the layer name is displayed in the attribute form instead
![image](https://user-images.githubusercontent.com/77726342/117330466-0361ca80-ae96-11eb-906a-7ac43c77c72d.png)
![image](https://user-images.githubusercontent.com/77726342/117330484-0957ab80-ae96-11eb-82c7-669a0d3cf43e.png)

QGIS 3.18

**Comment by fiddlersfan** [comment]
I just did some tests on this: tthe error occurs only if you use tabs in the Drag and-Drop Designer and the field widget was placed in any tab.

 @gioman can you please update the title?
