### ISSUE TITLE
List all layers and their source

### ISSUE THREAD

**Issue by WA-Hui** [qgis/QGIS#43116]
Can somebody please add a facility to list all Layers, The Group the layer belongs to The Data Type and the Source File/web address 

eg: 
Layer Name, Layer Group, Source
Road 1, Roads, Polygon, c:\qgis\myRoads.csv
Road 2, Roads, Points, c:\qgis\myHighways.csv
Geophysics, Geophysics, Raster, c:\qgis\Geophyics\mydtm.ecw
Map1, Background, raster, \\Google\mypay\mymap.gif

This should have the facility to export that as a CSV file

Thanx

**Ian H**

**Comment by alexbruy** [comment]
What you are asking for can be easily done from the Python console or implemented as a plugin.

**Comment by Houska1** [comment]
Check out https://plugins.qgis.org/plugins/LayerBoard/

Export tab on the right hand side.

**Comment by Houska1** [comment]
Re Python code to do precisely what you want, I suspect you will need to write it yourself! 

Section 4 of https://docs.qgis.org/3.16/en/docs/pyqgis_developer_cookbook/ is probably a good place to start. Or examining the code of the LayerBoard plugin.

Once you have tried and have more specific questions, you can probably get help at https://gis.stackexchange.com/

In the meanwhile, I think this Issue can be closed. It is quite unlikely "somebody" will add this functionality to the core when it can be achieved with a plugin or with some scripting, except potentially as an institutionally funded broader enhancement, for instance more broadly focused on layer management and/or project portability.
