### ISSUE TITLE
Layout add a raster image with an expression

### ISSUE THREAD

**Issue by lucienicolier** [qgis/QGIS#43125]
**Describe the bug**
In the layout when you want to add a raster image and getting the link by an expression it switches to SVG image.

**How to Reproduce**

1. Go to 'add a picture'
2. Click on 'raster image'
3. Click on 'data defined override'
4. Click on 'Edit' and add an expression
5. It switches to 'SVG image'

![layout_rasterimage](https://user-images.githubusercontent.com/50236352/117465089-9d3a7d80-af51-11eb-97ce-fe66ba36c39d.gif)

**QGIS and OS versions**

QGIS version | 3.18.2-Zürich | QGIS code revision | 515138c171
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | joinmultiplelines; maplibrary; plugin_reloader; qfieldsync; qgis_resource_sharing; quick_map_services; swiss_locator; vector_tiles_reader; db_manager; MetaSearch; processing

**Comment by nicogodet** [comment]
Duplicate #42280 ?

**Comment by lucienicolier** [comment]
@nicogodet right, sorry
