### ISSUE TITLE
Python plugin not showing in "Installed" list

### ISSUE THREAD

**Issue by MattReimer** [qgis/QGIS#43130]
Let me preface this with: Everything seems to work fine on windows. This is in OSX only

* QGIS version | 3.18.2-Zürich
* OSX Version 11.3.1

### Context:

I have created and submitted a new experimental plugin and I wish to install/uninstall it from my Macbook Pro. I have a fresh install of QGIS 3.18.2 ready to go.

### Reproduction Steps

1. I enable experimental plugins using the checkbox in the plugin manager settings
2. I search for my plugin, find it and click "Install experimental plugin"
![Screen Shot 2021-05-07 at 12 30 29 PM](https://user-images.githubusercontent.com/1063391/117499691-6ef87600-af30-11eb-82bd-4dc66735d370.png)

3. The plugin is installed (yay!) and I can use it normally. 

4. The plugin does not show up in the "Installed" list on the plugin manager. I don't know why 

![Screen Shot 2021-05-07 at 12 24 26 PM](https://user-images.githubusercontent.com/1063391/117499701-715ad000-af30-11eb-90ee-84448009756b.png)

I have also checked that my python plugin isn't throwing any errors.

Hopefully this is just user error but I don't know where to look now.

**Comment by MattReimer** [comment]
Some further context. I completely uninstalled QGIS and re-installed it and this issue was gone. Not sure if that means we should close it or not. This smells like a really tough thing to reproduce.

**Comment by MattReimer** [comment]
Ok. Further FURTHER context: I was having this problem again on another person's computer so I'm starting to think it's reproducible.

**Comment by gioman** [comment]
> Ok. Further FURTHER context: I was having this problem again on another person's computer so I'm starting to think it's reproducible.

@MattReimer please try with a new QGIS profile.

**Comment by gioman** [comment]
@MattReimer just tried on a clean install of QGIS 3.18 on macOS, works as expected.

**Comment by MattReimer** [comment]
New QGIS profile definitely fixed the issue for me but I don't understand why I need to do that. Despite the workaround it seems like a deeper issue here.
