### ISSUE TITLE
Can't Change Canvas Color - Error Generated

### ISSUE THREAD

**Issue by SteamCarriage** [qgis/QGIS#43147]
**Describe the bug**
Trying to change the canvas color I get an error message and the color isn't changed.

**How to Reproduce**
Settings - Options - Canvass & Legend
I change the canvass background color and hit OK at the bottom
Following message window pops up and canvass is not changed.

An error has occurred while executing Python code: 
RuntimeError: wrapped C/C++ object of type QMarxanToolboxInputFolders has been deleted 
Traceback (most recent call last):
  File "C:/Users/rober/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QMarxanToolbox\qmarxan_toolbox_provider.py", line 68, in loadAlgorithms
    self.addAlgorithm( alg )
RuntimeError: wrapped C/C++ object of type QMarxanToolboxInputFolders has been deleted

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.18.2-Zürich Zürich, 515138c171 

Python Path:
C:/Users/rober/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QMarxanToolbox
C:/PROGRA~1/QGIS3~1.18/apps/qgis/./python
C:/Users/rober/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/rober/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.18/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS3~1.18\apps\Python37
C:\PROGRA~1\QGIS3~1.18\apps\Python37\Scripts
C:\Program Files\QGIS 3.18\bin\python37.zip
C:\PROGRA~1\QGIS3~1.18\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.18\apps\Python37\lib
C:\Program Files\QGIS 3.18\bin
C:\PROGRA~1\QGIS3~1.18\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.18\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.18\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.18\apps\Python37\lib\site-packages\Pythonwin
C:/Users/rober/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\rober\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\vector_tiles_reader\ext-libs
D:/~FirstMap/QGIS

Tried starting with a new project as well as with existing projects - same result.  The only thing I not 'weird' above is the use of '\' in directory paths instead of '/' but I'm no programmer so I don't know if its OK or not.  The missing file in the error is in fact in the directory noted.

**Comment by nicogodet** [comment]
It seems related to a plugin `QMarxanToolbox`.
Try with a new profile please.
Settings -> User Profiles -> New profile

**Comment by SteamCarriage** [comment]
Tried Settings -> User Profile -> New Profile and created a new profile. 
Closed QGIS and opened the new profile.
Went to change color and did not get the error when I said 'OK'. Also it did not change the background color but left it as it was (white/cream).
So, in summary, didn't get the error with a new profile but also didn't change the canvas color to the new color.

**Comment by nicogodet** [comment]
It's probably overridden by project properties so Project -> Properties -> General

**Comment by nicogodet** [comment]
The color set in Settings -> Options -> Canvas applies for new projects only.

**Comment by nicogodet** [comment]
You're welcome !
You can close this issue as you solved your problem :)

**Comment by SteamCarriage** [comment]
Thanks to Nicogodet for helping solve this problem!

**Comment by Gustry** [comment]
You should report the error to the plugin author. It is definitely coming from `QMarxanToolbox`. I'm pretty sure it's about the way the plugin is adding Processing algorithm to its provider.
