### ISSUE TITLE
Just for your info

### ISSUE THREAD

**Issue by ansfans** [qgis/QGIS#43140]
## User Feedback

Navigating a complex 3D view

## Report Details

**Crash ID**: [6894c4afa420638e0c63ea31b061fa2fed99af01](https://github.com/qgis/QGIS/search?q=6894c4afa420638e0c63ea31b061fa2fed99af01&type=Issues)

**Stack Trace**
<pre>
TerrainMapUpdateJob::onTileReady qgsterrainentity_p.cpp:225
QMetaObject::activate :
QgsTerrainTextureGenerator::tileReady moc_qgsterraintexturegenerator_p.cpp:138
QgsTerrainTextureGenerator::onRenderingFinished qgsterraintexturegenerator_p.cpp:138
QMetaObject::activate :
QMetaObject::activate :
QMetaObject::activate :
QFutureWatcherBase::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:475
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1638
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.18.2-Z�rich
QGIS code revision: 515138c171
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

**Comment by roya0045** [comment]
ok

**Comment by gioman** [comment]
@ansfans not enough infos: add the detailed steps to replicate. Also try with a new QGIS profile.

**Comment by Gustry** [comment]
Duplicate crash ID #42883 which has more information

**Comment by gioman** [comment]
Closing as duplicate.
