### ISSUE TITLE
QGIS Web View Widget does not load images properly

### ISSUE THREAD

**Issue by jaitor1** [qgis/QGIS#43163]
I have developed a custom slider (html5 + js + css) to be able to add multiple images and files to any inventory item, not only to add it in QGIS but in any Web GIS, corporate webs, etc.

The slider is loaded as a Web Widget (url) that takes the item id as a parameter.

Most of the times when opening the form the image is loaded like this:

[![enter image description here][1]][1]

Sometimes when opening the form in QGIS the second time it is then displayed ok but some other times it keeps beeing displayed always like this...

If I open the url in any web browser it is always displayed ok, the problem is within QGIS.

It looks like a limitation of qgis. Maybe the developper that added this type of Form has not worried about loading a dynamic web or a website that takes time for rendering. Maybe making the form wait for the Ready event of the website solves the issue.

I can't share my slider beacuse its in local network but you can reproduce the issue doing:

1. create a new Text virtual field on a layer al fill it with 'https://unsplash.com/images/feelings/beautiful'. 
2. In the form of the layer set the new field as attachment --> WebView. Leave every other config as it is. 
3. Identify a feature of the layer. You will see that the images are not loaded correctly.

  [1]: https://i.stack.imgur.com/TcJBS.png

**Comment by gioman** [comment]
>     1. create a new Text virtual field

@jaitor1 why virtual?



>     3\. You will see that the images are not loaded correctly.

works fine here on master/Linux

![Screenshot_20210510_174830](https://user-images.githubusercontent.com/1951107/117695349-0a4f4c80-b1b8-11eb-92df-fd1df615e668.png)

**Comment by jaitor1** [comment]
My versión:

![image](https://user-images.githubusercontent.com/12136796/117696636-d24d0700-b1c1-11eb-9c59-a109db21e8bf.png)


Virtual field is not mandatory, I tried with a normal not virtual field and same result:

![image](https://user-images.githubusercontent.com/12136796/117696967-38d22500-b1c2-11eb-898f-fe2128ddb85c.png)

**Comment by luipir** [comment]
could be related with to time to give back the image from server side? as far as I remember the wrapper listen the html ready only set size.

**Comment by jaitor1** [comment]
> > My versión:
> 
> @jaitor1 maybe it won't change anything, but you must try with 3.16 or 3.18, as 3.10 is EOL.

Tested it on QGIS 3.18.2 and same result:

![image](https://user-images.githubusercontent.com/12136796/118111384-e83a1200-b3e3-11eb-8225-246537e7ade7.png)

**Comment by gioman** [comment]
@jaitor1 tested on 3.18.2 on Windows, still works fine here.

**Comment by jaitor1** [comment]
> > My versión:
> 
> @jaitor1 maybe it won't change anything, but you must try with 3.16 or 3.18, as 3.10 is EOL.

All the images of the website are loading ok? Or just the first one? Maybe it's an issue only in Windows then?

**Comment by gioman** [comment]
@jaitor1 

> All the images of the website are loading ok?

yes




> Or just the first one?

all



>  Maybe it's an issue only in Windows then?

I tested on Windows too.

**Comment by jaitor1** [comment]
> @jaitor1
> 
> > All the images of the website are loading ok?
> 
> yes
> 
> > Or just the first one?
> 
> all
> 
> > Maybe it's an issue only in Windows then?
> 
> I tested on Windows too.

I tested it in 6 different windows computers and I had the same bad result in all of them... 

@luipir can you reproduce the issue?

**Comment by luipir** [comment]
> @luipir can you reproduce the issue?

hadn't possibility to test it... seems all point to your web page setup. IMHO you should prepare a open website that replicate the problem.
