### ISSUE TITLE
Qgis outputs empty features when converting from shapefile to GeoJSON even after check validity

### ISSUE THREAD

**Issue by arasharchor** [qgis/QGIS#43168]
**Describe the bug**
We have a large shapefile of polyline features (10km² in 5cm resolution). After applying "check validity", we get valid and invalid layers. Invalid layer seems to be empty with no visible points. By applying create grid (rectangle) on the valid layer, the grid encompasses only the area of visible polylines which is correct.
However, after saving the valid output to a shape file and applying create grid, the resulting grid is several times larger indicating an invisible point has been added which we can't see it.

In investigated this issue further. I converted the shapefiles to GeoJSON and noticed empty features which were still present after check validity.

**How to Reproduce**
Create a layer with empty feature and apply "check validity". save "valid output" layer into a shapefile and then convert it to GeoJSON. You will see empty features are still present.

**QGIS and OS versions**

QGIS version
3.16.3-Hannover
QGIS code revision
94ac9f21b8
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
DamageLevelAssignment; 
joinmultiplelines; 
db_manager; 
MetaSearch; 
processing
OS - Windows 10

**Comment by gioman** [comment]
> Create a layer with empty feature

@arasharchor please attach a sample here.

**Comment by lbartoletti** [comment]
An empty feature is a valid feature. Most exactly, for example "POLYGON EMPTY" is a valid polygon.
