### ISSUE TITLE
Flatpak application | Missing project/organisation name mention

### ISSUE THREAD

**Issue by Ricky-Tigg** [qgis/QGIS#43174]
Hello. As noticeable the worth mentioning mention regards to **project/organisation** name is missing and then dully reported as "_Unknown_" when exhibited by Flatseal '`flatpak run com.github.tchx84.Flatseal`'.

![QGIS_desktop](https://user-images.githubusercontent.com/26058215/117790306-e4768600-b251-11eb-8a15-e2a7e446cd0c.png)

**Comment by gioman** [comment]
@Ricky-Tigg as far as I know we don't package for flatpack, so this should be reported to flathub(?)

**Comment by Ricky-Tigg** [comment]
Don't you intend to redirect it to internal repository **flathub/org.qgis.qgis**?
