### ISSUE TITLE
Rule-based rendering sometimes doesn't show all results

### ISSUE THREAD

**Issue by JohnProv** [qgis/QGIS#43181]
**Describe the bug**

When using rule based rendering, sometimes not all relevant items are rendered. This depends also on the order of the rules.

**How to Reproduce**

1. Download test data (shapefile) from Geofabrik, for example http://download.geofabrik.de/europe/luxembourg-latest-free.shp.zip
2. Open in Qgis a new project and open gis_osm_roads_free_1.shp; this is the road layer.
3. Enable rule-based rendering.
4. Add the following rule: `"fclass" = 'track' OR "fclass" = 'track_grade1' OR "fclass" = 'track_grade2' OR "fclass" = 'track_grade3' OR "fclass" = 'track_grade4' OR "fclass" = 'track_grade5'`
5. Add another rule, for example: `"fclass" = 'motorway' OR "fclass" = 'motorway_link'`
6. If the track-rule is on top, all relevant roads are correctly rendered.
7. Change the track-rule to the bottom, thus the motorway-rule is on top.
8. Now only some track types are rendered, it seems only `track` and `track_grade1`; I would expect that all relevant roads are rendered.

Correct (track-rule is on top):
![afbeelding](https://user-images.githubusercontent.com/67185600/117856399-db0a0f80-b28b-11eb-8784-02cd2cc326b9.png)

Not correct (motorway-rule is on top, look at the missing roads):
![afbeelding](https://user-images.githubusercontent.com/67185600/117856347-cc235d00-b28b-11eb-8e10-1acecf980643.png)

**QGIS and OS versions**

QGIS version | 3.18.2-Zürich | QGIS code branch | Release 3.18
-- | -- | -- | --
Compiled against Qt | 5.15.2 | Running against Qt | 5.15.2
Compiled against GDAL/OGR | 3.2.2 | Running against GDAL/OGR | 3.2.3
Compiled against GEOS | 3.9.1-CAPI-1.14.2 | Running against GEOS | 3.9.1-CAPI-1.14.2
Compiled against SQLite | 3.35.5 | Running against SQLite | 3.35.5
Compiled against PDAL | 2.2.0 | Running against PDAL | 2.2.0 (git-version: Release)
PostgreSQL Client Version | 13.2 | SpatiaLite Version | 5.0.1
QWT Version | 6.1.6 | QScintilla2 Version | 2.12.1
Compiled against PROJ | 8.0.0 | Running against PROJ | Rel. 8.0.1, March 5th, 2021
OS Version | Arch Linux
Active python plugins | MetaSearch; processing; db_manager

**Comment by JohnProv** [comment]
Are you using 3.18.2, or a development edition?
Maybe this has been already fixed?

**Comment by JohnProv** [comment]
I will check this with 3.18.3.

**Comment by JohnProv** [comment]
I'm waiting for the release of Qgis 3.18.3 on Arch Linux.

**Comment by JohnProv** [comment]
Still reproducible in Qgis 3.18.3.

**Comment by gioman** [comment]
> Still reproducible in Qgis 3.18.3.

@JohnProv as per above comment this should be tested against QGIS master, where is apparently fixed.

**Comment by JohnProv** [comment]
Tested with 3.19.0-Master | QGIS code revision b7ea7f2332e.

The problem still exists in Qgis-master!

Correct:
![afbeelding](https://user-images.githubusercontent.com/67185600/120213036-0c468180-c233-11eb-9cd4-6a25d2fe7d8c.png)

After changing the order of the rules:
![afbeelding](https://user-images.githubusercontent.com/67185600/120213001-0486dd00-c233-11eb-93c5-c377586ebc54.png)

**Comment by elpaso** [comment]
confirmed on master

**Comment by elpaso** [comment]
This is an upstream issue in GDAL.
