### ISSUE TITLE
Exporting point vector to .csv do not export the coordinates and can generate an empty file

### ISSUE THREAD

**Issue by gymate-1** [qgis/QGIS#43196]
**Describe the bug**
When I try to export a grid's points' coordinates as a `.csv` file, only an empty `.csv` file is generated.

**How to Reproduce**

https://user-images.githubusercontent.com/13014176/117987199-8c677e80-b33a-11eb-836d-9a77196e1a88.mp4

[The dataset, project file and the generated `.csv` file](https://github.com/qgis/QGIS/files/6467422/Archive.zip) which demonstrates the issue.

1. Open `grid_clipped.shp`
2. Select the `grid_clipped` layer
2. Click on _Layer > Save As..._
3. Choose a file name
4. Uncheck the `FID` field under _Select fields to export and their export options_
5. Choose `AS_XY` under _Layer Options > GEOMETRY_
6. Uncheck _Add saved file to map_
7. Click on _OK_
8. Open the exported `.csv` file
9. See that the file is empty

**QGIS and OS versions**

QGIS version | 3.18.2-Zürich | QGIS code revision | 44d7dfabbe
-- | -- | -- | --
Compiled against Qt | 5.14.2 | Running against Qt | 5.14.2
Compiled against GDAL/OGR | 3.2.1 | Running against GDAL/OGR | 3.2.1
Compiled against GEOS | 3.9.1-CAPI-1.14.2 | Running against GEOS | 3.9.1-CAPI-1.14.2
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
Compiled against PDAL | 2.2.0 | Running against PDAL | 2.2.0 (git-version: Release)
PostgreSQL Client Version | 12.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.4
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | macOS 11.3
Active python plugins | processing; db_manager; MetaSearch

**Comment by gioman** [comment]
> Open `grid_clipped.shp`

@gymate-1 you added only the .shp file, you must also add the .shx, .dbf and .prj ones.

**Comment by gymate-1** [comment]
@gioman My bad! I edited my message, the link now refers to a `.zip` file containing these files too. Thanks for the heads-up!

**Comment by gioman** [comment]
@gymate-1 the result is empty probably because the result can't simply have no fields... and it has no fields because it seems that the X/Y values are never exported, which seems to me is the root of the problem.

**Comment by gioman** [comment]
And this is likely to be a regression, I'm pretty sure it worked fine in the past. I tested on master/Linux.

**Comment by gioman** [comment]
@gymate-1 ...or not. I tested another layer and it works as expected... so it must be seen why it doesn't work on the one you attached.

**Comment by gioman** [comment]
@gymate-1 what is you layer CRS? the project opens with it defined as 4326, which is wrong.

**Comment by gymate-1** [comment]
@gioman It's 23700. But I want to export the coordinates in 4326.

**Comment by gioman** [comment]
> @gioman It's 23700. But I want to export the coordinates in 4326.

@gymate-1 does it look right?

![Screenshot_20210512_191041](https://user-images.githubusercontent.com/1951107/118023737-ca25d080-b355-11eb-8424-41754f1effb7.png)

**Comment by gymate-1** [comment]
@gioman Yeah, totally!

**Comment by gioman** [comment]
> @gioman Yeah, totally!

@gymate-1 as said it seems there seems to be something fishy in your shape, as with other datasets it works. The shape you attached has the issue that has the wrong CRS, anyway even fixing it exporting to CSV do not add the x/y columns.

**Comment by gymate-1** [comment]
> > @gioman Yeah, totally!
> 
> @gymate-1 as said it seems there seems to be something fishy in your shape, as with other datasets it works. The shape you attached has the issue that has the wrong CRS, anyway even fixing it exporting to CSV do not add the x/y columns.

Here's how I created `grid_clipped.shp`:

[Screen recording](https://youtu.be/GYtAQUUiYNA)

[The project file and the shapefile](https://github.com/qgis/QGIS/files/6472978/Archive.zip) to reproduce the steps below.

1. Open `alapterkep.qgz` which contains varoshatar.shp as a layer
2. Click on _Vector > Research Tools > Create Grid..._
3. Select _Grid extent > Calculate from Layer > `varoshatar`_
4. Set _Horizontal spacing_ and _Vertical spacing_ to 500 meters
5. Click _Run_
6. Click _Close_
6. Click on the generated layer `Grid`
7. Click on _Layer > Save As..._
8. Set Format to _ESRI Shapefile_
9. Set File name to `~/grid.shp`
10. Leave CRS as `EPSG:23700`
11. Click _OK_
12. Click on _Vector > Geoprocessing Tools > Clip..._
13. Set the _Input layer_ to `grid`
14. Set the _Overlay layer_ to `varoshatar`
15. Click _Run_
16. Click _Close_
17. Click on the generated layer `Clipped`
18. Click on _Layer > Save As..._
19. Set Format to _ESRI Shapefile_
20. Set File name to `~/grid_clipped.shp`
21. Leave CRS as `EPSG:23700`
22. Click _OK_
23. Repeat the steps in my first comment to reproduce the issue

**Comment by gioman** [comment]
@gymate-1 found it.

Saving as CSV is done (internally) using ogr2ogr with the flag (example)

-lco GEOMETRY=AS_XY

but this only works if the layer is singlepart and in QGIS point shapefiles are forced to MULTI.

So save your grid to a singlepart gpkg layer and the operation will work.

I guess that QGIS should disable that option (geometries as XY or YX or XYZ) when the input is multipart (but notice that exporting geometries as WKT works anyway).

**Comment by gymate-1** [comment]
> So save your grid to a singlepart gpkg layer and the operation will work.

@gioman I saved both grids' layer as `.gpkg` after generating them but it still doesn't work. 😟 If I export `grid_clipped.gpkg` as `.csv `with `GEOMETRY=AS_WKT`, the [generated file](https://github.com/qgis/QGIS/files/6475204/grid_points.csv) still shows that the input is multipart.

**Comment by gioman** [comment]
@gymate-1 did you processed the layer with "multipart to singlepart" before saving as gpkg?

**Comment by gymate-1** [comment]
> @gymate-1 did you processed the layer with "multipart to singlepart" before saving as gpkg?

@gioman No, sorry. But I tried it this way and it works! Thanks a lot for your help!! 🙂

**Comment by gioman** [comment]
> @gioman No, sorry. But I tried it this way and it works! Thanks a lot for your help!! slightly_smiling_face

@gymate-1 see https://github.com/qgis/QGIS/issues/43218

**Comment by koebi** [comment]
I just ran into this exact problem, albeit with temporary layers.
Again, converting multipart to singlepart solved the problem.

@gioman do you have any idea why this is happening with temporary layers?
Is there any way to see that I am dealing with a multipart feature? It states "point", not "multipoint" in my layer properties…
