### ISSUE TITLE
Mesh calculator  max_aggr (  ) giving incorrect results and only working for 2 drivers

### ISSUE THREAD

**Issue by colin6502** [qgis/QGIS#43192]
**Describe the bug**
Max_aggr () function gives results that are very similar to using average_aggr(), and the max_aggr results look wrong (too low) with 3D netCDF mesh data.

**How to Reproduce**
1. load netCDF (.nc) file from a 3D TUFLOW FV model run (time varying mesh)
2. open Mesh Calculator dialogue from Processing Toolbox as Crayfish > Mesh Calculator (note this has different dialogue box than going under the Mesh menu)
3. Select datafile
4. Formula: #max_aggr (   "tracer 2 concentration" )
5. Extent: from datafile
6. Start and end times: for the full dataset
7. Name: trace_2_max
8. Driver: only works with the ASCII_DAT and FLO2D drivers (the others, BINARY_DAT and SELAFIN give error (2).
9. Exported dataset group file: leave as a temporary file
10. Run. When I compare using max_aggr to the average_aggr function it gives the same results. The results of the average function look plausible, but the maximum ones don't. In some fluke, I did get the max_aggr to run correctly once (oddly with the BINARY_DAT driver even though it gave an error), but I can't reproduce this.
11. Note when I use BINARY_DAT the following is a typical error 
           QGIS version: 3.18.2-Zürich
           QGIS code revision: 515138c171
           Qt version: 5.11.2
           GDAL version: 3.1.4
           GEOS version: 3.8.1-CAPI-1.13.3
           PROJ version: Rel. 6.3.2, May 1st, 2020
           Processing algorithm…
           Algorithm 'Mesh calculator' starting…
           Input parameters:
           { 'CRAYFISH_INPUT_ENDTIME' : 720, 'CRAYFISH_INPUT_EXTENT' :            '504552.892900000,529313.576000000,5254165.859800000,5269683.548800000 [EPSG:28355]', 'CRAYFISH_INPUT_FORMULA' : ' max_aggr ( \"tracer 2 concentration\" )', 'CRAYFISH_INPUT_LAYER' : 'C:/temp/output_205.nc', 'CRAYFISH_INPUT_STARTTIME' : 0, 'CRAYFISH_OUTPUT_DRIVER' : 3, 'CRAYFISH_OUTPUT_FILE' : 'TEMPORARY_OUTPUT', 'CRAYFISH_OUTPUT_GROUP' : 'tracer_2_max'            }

           Could not calculate output group (err: 2)
           Execution failed after 14.38 seconds

           Loading resulting layers
           Algorithm 'Mesh calculator' finished

**QGIS and OS versions**

QGIS version
3.18.2-Zürich
QGIS code revision
515138c171
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
ClipMultipleLayers; 
crayfish; 
FreehandRasterGeoreferencer; 
pointsamplingtool; 
profiletool; 
qNote; 
quick_map_services; 
tuflow; 
valuetool; 
db_manager; 
MetaSearch; 
processing

**Additional context**

The datafile I'm using is 40 GB, but I have the same issue on smaller ones
The datafile was loaded via the Tuflow Viewer plugin

**Comment by gioman** [comment]
> The datafile I'm using is 40 GB, but I have the same issue on smaller ones

@colin6502 can you link/attach a sample dataset?

**Comment by vcloarec** [comment]
@colin6502 
There are two distinct mesh calculators : the native one, in the Mesh menu, and the cray fish one, that is a plugin processing.
Have you the same issue in the native one in the Mesh Menu?

**Comment by colin6502** [comment]
> @colin6502
> There are two distinct mesh calculators : the native one, in the Mesh menu, and the cray fish one, that is a plugin processing.
> Have you the same issue in the native one in the Mesh Menu?

I've just tested the native one and it produces different outputs for its max and average, and they are more plausible (ie. the maximum one is larger than the average). The average one is similar to the version produced in the Crayfish mesh calculator under progressing toolbox, but not (visually) the same.

**Comment by mattfack** [comment]
Have you checked the max value of your raster with e.g. grass? This way you know which tool gives you the correct result

**Comment by colin6502** [comment]
> Have you checked the max value of your raster with e.g. grass? This way you know which tool gives you the correct result

Not yet, a good idea. It's not a raster though, it's a temporal mesh - so I would need create a raster for each time step (which is an approximation) and then mosaic them with maximum value envelope. I'll need to create a small output file first to make it manageable.

**Comment by mattfack** [comment]
bummer. However, I verified that the native mesh calculator gives consistent results!
