### ISSUE TITLE
Feature count is wrong when adding features from a table with features of mixed geometries

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#43199]
For example the sample in here

https://github.com/qgis/QGIS/issues/43186

has about 11700 featues in total. Via browser/db manager/add postgis layer we can as separate layers the points, lines or polygons, but the feature count in the map legend is always the one that show the total for all types.

**Comment by elpaso** [comment]
@gioman cannot reproduce:

![immagine](https://user-images.githubusercontent.com/142164/119820486-cebfbc80-bef1-11eb-8624-5a66fb8587ea.png)

**Comment by gioman** [comment]
@elpaso updated to the latest master from QGIS.org's repos and still see the same

![Screenshot_20210527_182239](https://user-images.githubusercontent.com/1951107/119869891-ac8d6500-bf18-11eb-8ab0-36eb86c5c26d.png)





QGIS version | 3.19.0-Master | QGIS code revision | faa8be243e
-- | -- | -- | --
Qt version | 5.12.8
Python version | 3.8.5
GDAL/OGR version | 3.0.4
PROJ version | 6.3.1
EPSG Registry database version | v9.8.6 (2020-01-22)
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
SQLite version | 3.31.1
PDAL version | 2.0.1
PostgreSQL client version | 12.6 (Ubuntu 12.6-0ubuntu0.20.04.1)
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.2
OS version | Ubuntu 20.04.2 LTS

**Comment by elpaso** [comment]
@gioman before removing the feedback did you check for any options difference in the layer definition that I posted (you can see it in the tooltip) ?

**Comment by gioman** [comment]
> @gioman before removing the feedback did you check for any options difference in the layer definition that I posted (you can see it in the tooltip) ?

@elpaso no difference

**Comment by jgrocha** [comment]
There is an obvious explanation (please confirm if it applies @gioman). You have `Use estimated table metadata` option selected for your connection. If enabled, QGIS will not scan the entire table. Right now (after #43419) QGIS will scan the entire table if you do not enable the `Use estimated table metadata` option.

In the browser panel, you might be missing some geometries also. Check if you can see all 3 geometries in the browser panel.

Which such option disabled (the default is to be disabled), the feature count is displayed properly. I have the same output as @elpaso.

![Screenshot from 2021-05-31 12-39-08](https://user-images.githubusercontent.com/163681/120188014-7ba97a80-c20d-11eb-9760-463c9578ca7f.png)

### With Use estimated table metadata enabled

With that option enabled for the Postgis connection, I've also have the Show feature count failing to provide an accurate count.

![Screenshot from 2021-05-31 12-45-17](https://user-images.githubusercontent.com/163681/120188466-1013dd00-c20e-11eb-9578-9a306072f6dd.png)

**Comment by elpaso** [comment]
@jgrocha that's exactly why I asked if the layer definition was exactly the same: `estimatedmetadata=true` is not shown in the data source uri of my test layer, I assumed that it was in @gioman's layer but since he said that  he checked, this remains a mistery.

**Comment by gioman** [comment]
Evidently I was looking at the wrong layer. Sorry for the noise.
