### ISSUE TITLE
SSL certificate for feed.qgis has expired

### ISSUE THREAD

**Issue by chleidersdorff** [qgis/QGIS#43203]
The SSL certificate for the feed.qgis has expired on "Wed May 12 16:16:14 2021 GMT"
See below screenshot for details

I'm using QGIS on Windows 10 Enterprise v1909 build 18363.1556

Qgis version 3.16.6 (LTR) - see screenshot for details.

![image](https://user-images.githubusercontent.com/52182284/118091629-63182280-b40e-11eb-8bba-96edf3f9a6c8.png)

![image](https://user-images.githubusercontent.com/52182284/118091222-ea18cb00-b40d-11eb-98e0-2e2abfde01ee.png)

**Comment by rouault** [comment]
The certificate has now been renewed
