### ISSUE TITLE
QgsLineString does not accept iterable[QgsPointXY] on costructor method

### ISSUE THREAD

**Issue by elitonfilho** [qgis/QGIS#43200]
**Describe the bug**
QgsLineString does not accept iterable[QgsPointXY] on costructor method

It's not a big problem since we could generate a QgsPoint from a QgsPointXY, but the documentation (https://qgis.org/pyqgis/master/core/QgsLineString.html) suggests that QgsLineString should accept QgsPointXY on constructor: " New in version 3.2.
QgsLineString(points: Iterable[QgsPointXY]) Construct a linestring from list of points."

**How to Reproduce**

On console, type:
from qgis.core import QgsLineString
from qgis.core import QgsPointXY
p1 = QgsPointXY(1,1)
p2 = QgsPointXY(2,2)
p3 = QgsPointXY(4,0)
QgsLineString([p1,p2,p3])

**QGIS and OS versions**

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

QGIS version | 3.18.1-Zürich | QGIS code revision | 202f1bf7e5
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | DsgTools; plugin_reloader; quick_map_services; db_manager; MetaSearch; processing; ferramentas_experimentais

</body></html>

**Comment by elpaso** [comment]
Yeah, this happens because the first constructor is called: Python see a list an calls the first constructor that accepts a list (which is the `QgsLineString( const QVector<QgsPoint> &points )`.

I don't thinks there is an easy solution here.
