### ISSUE TITLE
creashed problem

### ISSUE THREAD

**Issue by pulak123625** [qgis/QGIS#43217]
**Describe the bug**
Crash ID: ea6dff41b319bd381224a19d7ed4e66213ec26b0

Stack Trace

QgsLayoutItemAttributeTable::writePropertiesToElement :
QgsLayoutMultiFrame::writeXml :
QgsLayoutMultiFrameUndoCommand::saveState :
QgsLayoutUndoStack::beginCommand :
QgsLayoutMultiFrame::beginCommand :
QgsVertexEditorModel::flags :
QMetaObject::activate :
QgsMapLayerComboBox::layerChanged :
QMetaObject::activate :
QComboBox::editTextChanged :
QMetaObject::activate :
QComboBoxPrivateContainer::eventFilter :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.6.2-Noosa
QGIS code revision: 656500e0c4
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**How to Reproduce**

4. See error -->

**QGIS and OS versions**

**Additional context**

**Comment by gioman** [comment]
>  QGIS Version: 3.6.2-Noosa

 @pulak123625 way too old. You must test on 3.16 or 3.18 and with a new QGIS profile. Reopen if the problem persist, but please add all the necessary steps that lead to the crash. Thanks.

**Comment by pulak123625** [comment]
Thanks
