### ISSUE TITLE
How to disable annoying Vertex Editor popping up

### ISSUE THREAD

**Issue by beyhh** [qgis/QGIS#43213]
Hi there,

is there a way to disable the Vertex Editor panel popping up, saying "Right click on an editable feature to show its table of vertices"? This panel should be visible on demand, i.e. when you actually need to display and edit coordinates in a table but not by default. It's really annoying.

**Comment by gioman** [comment]
Please ask questions in the appropriate channels, the users/developers mailing lists and/or stackexchange.
