### ISSUE TITLE
QGIS 3.18.2 SAGA and GRASS not working

### ISSUE THREAD

**Issue by RookieUser999** [qgis/QGIS#43222]
Windows 10 64 bit
OSGEO4W installer
QGIS 3.18.2

Cant add raster values from a grid.

Yes I have tested a clean user. Same error.

I have also tried standalone installer with different versions. 

I hope i could find a solution because I need Qgis in my work and not grass or saga is working.

LOG: 
QGIS version: 3.18.2-Zürich
QGIS code revision: 515138c171
Qt version: 5.15.2
GDAL version: 3.3.0
GEOS version: 3.9.1-CAPI-1.14.2
PROJ version: Rel. 8.0.1, March 5th, 2021
PDAL version: 2.2.0 (git-version: 365171)
SAGA version 7.8.2 is not officially supported - algorithms may encounter issues
Processing algorithm…
Algorithm 'Add Raster Values to Points' starting…
Input parameters:
{ 'GRIDS' : ['C:/TEST_proj/Q4323E.tif'], 'RESAMPLING' : 3, 'RESULT' : 'TEMPORARY_OUTPUT', 'SHAPES' : 'C:/TEST_proj/test.shp' }

io_gdal 0 -TRANSFORM 1 -RESAMPLING 3 -GRIDS "C:/Users/KlausJåfs/AppData/Local/Temp/processing_JvhxoW/ee3295af1783424a9e59e390861c4ad7/Q4323E.sgrd" -FILES "C:/TEST_proj/Q4323E.tif"
shapes_grid "Add Grid Values to Points" -SHAPES "C:/TEST_proj/test.shp" -GRIDS "C:/Users/KlausJåfs/AppData/Local/Temp/processing_JvhxoW/ee3295af1783424a9e59e390861c4ad7/Q4323E.sgrd" -RESAMPLING 3 -RESULT "C:/Users/KlausJåfs/AppData/Local/Temp/processing_JvhxoW/aee30d3e663c44638d80870b377fbbf1/RESULT.shp"

C:\OSGeo4W\bin>set SAGA=C:/OSGeo4W/apps\saga

C:\OSGeo4W\bin>set SAGA_MLB=C:/OSGeo4W/apps\saga\modules

C:\OSGeo4W\bin>PATH=C:\OSGeo4W\apps\qgis\bin;C:\OSGeo4W\apps\grass\grass78\lib;C:\OSGeo4W\apps\grass\grass78\bin;C:\OSGeo4W\apps\qt5\bin;C:\OSGeo4W\apps\Python39\Scripts;C:\OSGeo4W\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\system32\WBem;C:/OSGeo4W/apps\saga;C:/OSGeo4W/apps\saga\modules

C:\OSGeo4W\bin>call saga_cmd io_gdal 0 -TRANSFORM 1 -RESAMPLING 3 -GRIDS "C:/Users/KlausJÃ¥fs/AppData/Local/Temp/processing_JvhxoW/ee3295af1783424a9e59e390861c4ad7/Q4323E.sgrd" -FILES "C:/TEST_proj/Q4323E.tif"
____________________________

##### # ## ##### # ##
____________________________

SAGA Version: 7.8.2 (64 bit)

88 loaded tool libraries (775 tools):
- tin_viewer
- tin_tools
- table_tools
- table_calculus
- ta_slope_stability
- ta_profiles
- ta_preprocessor
- ta_morphometry
- ta_lighting
- ta_hydrology
- ta_compound
- ta_cliffmetrics
- ta_channels
- statistics_regression
- statistics_points
- statistics_kriging
- statistics_grid
- sim_rivflow
- sim_qm_of_esp
- sim_landscape_evolution
- sim_ihacres
- sim_hydrology
- sim_geomorphology
- sim_fire_spreading
- sim_erosion
- sim_ecosystems_hugget
- sim_cellular_automata
- sim_air_flow
- shapes_transect
- shapes_tools
- shapes_polygons
- shapes_points
- shapes_lines
- shapes_grid
- pointcloud_viewer
- pointcloud_tools
- pj_proj4
- pj_geotrans
- pj_georeference
- io_webservices
- io_virtual
- io_table
- io_shapes_dxf
- io_shapes
- io_pdal
- io_grid_image
- io_grid
- io_gps
- io_esri_e00
- imagery_tools
- imagery_svm
- imagery_segmentation
- imagery_photogrammetry
- imagery_maxent
- imagery_isocluster
- imagery_classification
- grids_tools
- grid_visualisation
- grid_tools
- grid_spline
- grid_gridding
- grid_filter
- grid_calculus_bsl
- grid_calculus
- grid_analysis
- garden_webservices
- garden_learn_to_program
- garden_games
- garden_fractals
- garden_3d_viewer
- docs_pdf
- docs_html
- dev_tools
- db_pgsql
- db_odbc
- contrib_perego
- climate_tools
- tta_tools *
- toolchains *
- terrain_analysis *
- imagery *
- group_files *
- grid_filter *
- gc_tools *
- climate_tools *
- Shapes Tools *
- Polygon Tools *
- Grid Tools *

*) tool chain libraries

Error: select a library
type -h or --help for further information

C:\OSGeo4W\bin>call saga_cmd shapes_grid "Add Grid Values to Points" -SHAPES "C:/TEST_proj/test.shp" -GRIDS "C:/Users/KlausJÃ¥fs/AppData/Local/Temp/processing_JvhxoW/ee3295af1783424a9e59e390861c4ad7/Q4323E.sgrd" -RESAMPLING 3 -RESULT "C:/Users/KlausJÃ¥fs/AppData/Local/Temp/processing_JvhxoW/aee30d3e663c44638d80870b377fbbf1/RESULT.shp"
____________________________

##### # ## ##### # ##
____________________________

SAGA Version: 7.8.2 (64 bit)

____________________________
library path: C:\OSGeo4W\apps\saga\tools\
library name: shapes_grid
library : shapes_grid
tool : Add Grid Values to Points
identifier : 0
author : O.Conrad (c) 2003
processors : 8 [8]
____________________________

Load shapes: C:/TEST_proj/test.shp...

Loading grid: C:/Users/KlausJ+Ñfs/AppData/Local/Temp/processing_JvhxoW/ee3295af1783424a9e59e390861c4ad7/Q4323E.sgrd...
failed
Add Grid Values to Points: could not initialize data objects
Error: executing tool [Add Grid Values to Points]

C:\OSGeo4W\bin>exit
Execution completed in 4.47 seconds
Results:
{'RESULT': 'C:/Users/KlausJåfs/AppData/Local/Temp/processing_JvhxoW/aee30d3e663c44638d80870b377fbbf1/RESULT.shp'}

Loading resulting layers
The following layers were not correctly generated.
• C:/Users/KlausJåfs/AppData/Local/Temp/processing_JvhxoW/74d4ffb2b0b8463d93b6579da638c9ee/RESULT.shp
You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.

**Comment by gioman** [comment]
@RookieUser999 GRASS works if you launch QGIS with the correct "shortcut", the one that says "QGIS 3.* WITH GRASS".



> SAGA Version: 7.8.2 (64 bit)

SAGA 7.* is unsupported, you must use SAGS 2.*. In a not far future we will have SAGA 7 support (with the next gen of Windows installers).

**Comment by RookieUser999** [comment]
Well I tried with QGIS ltr 3.16 and here is the log:

QGIS version: 3.16.6-Hannover
QGIS code revision: bfd36fddc9
Qt version: 5.11.2
GDAL version: 3.1.4
GEOS version: 3.8.1-CAPI-1.13.3
PROJ version: Rel. 6.3.2, May 1st, 2020
Processing algorithm…
Algorithm 'Add raster values to points' starting…
Input parameters:
{ 'GRIDS' : ['C:/TEST_proj/Q4314H.asc'], 'RESAMPLING' : 2, 'RESULT' : 'TEMPORARY_OUTPUT', 'SHAPES' : 'C:\\TEST_proj\\test2.shp' }

io_gdal 0 -TRANSFORM 1 -RESAMPLING 3 -GRIDS "C:/Users/KlausJåfs/AppData/Local/Temp/processing_sbQyLY/b0f25a0050ba457c8c2b0ff3a9d8de6d/Q4314H.sgrd" -FILES "C:/TEST_proj/Q4314H.asc"
shapes_grid "Add Grid Values to Points" -SHAPES "C:\TEST_proj\test2.shp" -GRIDS "C:/Users/KlausJåfs/AppData/Local/Temp/processing_sbQyLY/b0f25a0050ba457c8c2b0ff3a9d8de6d/Q4314H.sgrd" -RESAMPLING 2 -RESULT "C:/Users/KlausJåfs/AppData/Local/Temp/processing_sbQyLY/4fa9a0b7203f428b9e346b5c00ac9636/RESULT.shp"

Execution completed in 7.14 seconds
Results:
{'RESULT': 'C:/Users/KlausJåfs/AppData/Local/Temp/processing_sbQyLY/4fa9a0b7203f428b9e346b5c00ac9636/RESULT.shp'}

Loading resulting layers
The following layers were not correctly generated.
• C:/Users/KlausJåfs/AppData/Local/Temp/processing_sbQyLY/bda8988be99f4ad8adb4887bea48eeb9/RESULT.shp
You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.

**Comment by gioman** [comment]
>  Algorithm 'Add raster values to points' starting…

@RookieUser999 attach here the inputs

**Comment by RookieUser999** [comment]
[Q4314H.zip](https://github.com/qgis/QGIS/files/6479766/Q4314H.zip)

**Comment by RookieUser999** [comment]
and when trying to extract grid values the layer cannot be created. Same if I try to add coordinates to points

**Comment by RookieUser999** [comment]
Could it be the non ascii letters in my name? Because I am the only one in our firm who suffers from this problem.

**Comment by gioman** [comment]
> Could it be the non ascii letters in my name?

@RookieUser999 yes it can. Try create a Windows user with no accents and spaces in it.
