### ISSUE TITLE
Crash when using relation editor widget

### ISSUE THREAD

**Issue by elpaso** [qgis/QGIS#43221]
In master and 3.18, can be reproduced following the instructions in #43061

I've done a quick debug session and there is an endless loop with approximately the following sequence

1. QgsRelationEditorWidget calls `updateUi()`
2. which calls initDualView()
3. QgsDualView calls init
4. QgsDualView calls QgsFeatureListView->setEditSelection()
5. which emits editSelectionChanged
6. then emits currentEditSelectionChanged
7. back into the dual view featureListCurrentEditSelectionChanged()
8. then QgsDualView::initAttributeForm
9. ... QgsAttributeForm::resetValues()
10. QgsRelationWidgetWrapper::setFeature
11. QgsAbstractRelationEditorWidget::setFeature
12. ---> and back to square 1 with `udateUi()` !!!

@suricactus , @domi4484 this is in 3.18 and master but not in 3.16 any chance that your recent changes on the relation widgets broke this? Can you please have a look?

**Comment by domi4484** [comment]
@elpaso I added some "missing" calls to `updateUi()` recently, probably too much. I'll give a look soon.
Maybe this is also related  #42952

**Comment by elpaso** [comment]
@domi4484 indeed, this issue looks like a duplicate of that one, feel free to close.
