### ISSUE TITLE
QGIS Crashes with GDAL 3.3

### ISSUE THREAD

**Issue by esnyder-rve** [qgis/QGIS#43224]
**Describe the bug**
I just installed the updates from OSGeo4W. This crash only occurs when loading a project with a particular PostGIS layer in *some* projects (I saw which layer caused the crash in the VS Debugger). I can reproduce this in QGIS 3.18 and QGIS 3.19 Master from OSGeo4W with the same affected projects.

VS Debugger show the crash here: https://github.com/qgis/QGIS/blob/04717438890f7e1e2ece7b90b9d77a978009e0ef/src/core/providers/ogr/qgsogrprovider.cpp#L590

with exception: `Unhandled exception at 0x00007FFA8A6F1208 (ucrtbase.dll) in qgis-ltr-bin.exe: An invalid parameter was passed to a function that considers invalid parameters fatal.`

**How to Reproduce**

1. Start QGIS
2. Load affected project
3. Crash

**QGIS and OS versions**
QGIS version | 3.16.6-Hannover
------|------
QGIS code revision | bfd36fdd
Compiled against Qt | 5.15.2
Running against Qt | 5.15.2
Compiled against GDAL/OGR | 3.3.0
Running against GDAL/OGR | 3.3.0
Compiled against GEOS | 3.9.1-CAPI-1.14.2
Running against GEOS | 3.9.1-CAPI-1.14.2
Compiled against SQLite | 3.35.2
Running against SQLite | 3.35.2
PostgreSQL Client Version | 13.0
SpatiaLite Version | 5.0.1
QWT Version | 6.1.3
QScintilla2 Version | 2.11.5
Compiled against PROJ | 8.0.1
Running against PROJ | Rel. 8.0.1, March 5th, 2021
OS Version | Windows 10 Version 2004
Active python plugins | *Clean Profile

**Additional context**
Stack Trace
```
ucrtbase.dll!_invoke_watson()
ucrtbase.dll!_invalid_parameter()
ucrtbase.dll!_invalid_parameter_noinfo()
ucrtbase.dll!_stricmp_l()
gdal303.dll!00007ffa0806b451()
qgis_core.dll!QgsOgrProvider::QgsOgrProvider(const QString & uri, const QgsDataProvider::ProviderOptions & options, QFlags<enum QgsDataProvider::ReadFlag> flags) Line 590
qgis_core.dll!QgsOgrProviderMetadata::createProvider(const QString & uri, const QgsDataProvider::ProviderOptions & options, QFlags<enum QgsDataProvider::ReadFlag> flags) Line 3698
qgis_core.dll!QgsVectorLayer::setDataProvider(const QString & provider, const QgsDataProvider::ProviderOptions & options, QFlags<enum QgsDataProvider::ReadFlag> flags) Line 1758
qgis_core.dll!QgsVectorLayer::setDataSource(const QString & dataSource, const QString & baseName, const QString & provider, const QgsDataProvider::ProviderOptions & options, bool loadDefaultStyleFlag) Line 1650
qgis_core.dll!QgsVectorLayer::QgsVectorLayer(const QString & vectorLayerPath, const QString & baseName, const QString & providerKey, const QgsVectorLayer::LayerOptions & options) Line 181
qgis_core.dll!QgsAuxiliaryLayer::QgsAuxiliaryLayer(const QString & pkField, const QString & filename, const QString & table, QgsVectorLayer * vlayer) Line 68
qgis_core.dll!QgsAuxiliaryStorage::createAuxiliaryLayer(const QgsField & field, QgsVectorLayer * layer) Line 596
qgis_core.dll!QgsVectorLayer::loadAuxiliaryLayer(const QgsAuxiliaryStorage & storage, const QString & key) Line 5306
qgis_core.dll!QgsProject::addMapLayers(const QList<QgsMapLayer *> & layers, bool addToLegend, bool takeOwnership) Line 3413
qgis_core.dll!QgsProject::addLayer(const QDomElement & layerElem, QList<QDomNode> & brokenNodes, QgsReadWriteContext & context, QFlags<enum QgsProject::ReadFlag> flags) Line 1237
qgis_core.dll!QgsProject::_getMapLayers(const QDomDocument & doc, QList<QDomNode> & brokenNodes, QFlags<enum QgsProject::ReadFlag> flags) Line 1151
qgis_core.dll!QgsProject::readProjectFile(const QString & filename, QFlags<enum QgsProject::ReadFlag> flags) Line 1590
qgis_core.dll!QgsProject::unzip(const QString & filename, QFlags<enum QgsProject::ReadFlag> flags) Line 3317
qgis_core.dll!QgsProject::read(QFlags<enum QgsProject::ReadFlag> flags) Line 1298
qgis_app.dll!QgisApp::addProject(const QString & projectFile) Line 7014
qgis_app.dll!QgisApp::openProject(const QString & fileName) Line 7490
qgis_app.dll!QgsWelcomePage::recentProjectItemActivated(const QModelIndex & index) Line 207
[External Code]
qgis_core.dll!QgsApplication::notify(QObject * receiver, QEvent * event) Line 458
[External Code]
qgis_core.dll!QgsApplication::notify(QObject * receiver, QEvent * event) Line 458
[External Code]
qgis_app.dll!main(int argc, char * * argv) Line 1637
[External Code]
```

**Comment by roya0045** [comment]
is gdal 3.3 supported in qgis? with master mingw64 I get 3.2

**Comment by gioman** [comment]
@roya0045 it seems that there are issues: https://lists.osgeo.org/pipermail/qgis-developer/2021-May/063605.html 

@PedroVenancio is the same type of crash you got?

**Comment by PedroVenancio** [comment]
Yes it should be the same issue

https://trac.osgeo.org/osgeo4w/ticket/680

@esnyder-rve can you test this sample dataset? 
https://cld.pt/dl/download/85e3df31-1f7d-4826-96f6-3533328c637e/Sample_Project.zip

**Comment by esnyder-rve** [comment]
@PedroVenancio the sample dataset provided crashes both QGS 3.18 and QGS 3.16 LTR.

I can't downgrade GDAL to 3.2 because the OSGeo4W installer does not have 3.2 versions for the packages I need (i.e. I need the gdal-filegdb package, but I can only install 3.3.0-3 or 3.3.0-2).

**Comment by gioman** [comment]
Is GDAL 3.3 used in the standalone installers and the osgeo4w installer linked on qgis.org web site?

**Comment by esnyder-rve** [comment]
GDAL 3.3 is only in the testing OSGeo4W Installer. I'm installed QGIS 3.16 right now via the old network installer which has gdal 3.1.4 in another folder (C:/OSGeo4W-Stable).

**Comment by gioman** [comment]
> GDAL 3.3 is only in the testing OSGeo4W Installer as far as I know

@esnyder-rve I guess is "testing" for some reason :)

**Comment by PedroVenancio** [comment]
> 
> 
> @PedroVenancio the sample dataset provided crashes both QGS 3.18 and QGS 3.16 LTR.
> 
> I can't downgrade GDAL to 3.2 because the OSGeo4W installer does not have 3.2 versions for the packages I need (i.e. I need the gdal-filegdb package, but I can only install 3.3.0-3 or 3.3.0-2).

So, it seems confirmed.

I've tested downgrading to a QGIS version compiled against GDAL 3.2.2 and works fine.

Hope this can be fixed ASAP.
