### ISSUE TITLE
In WMTS (XYZ) implement and allow overzoom beyond max. zoom level

### ISSUE THREAD

**Issue by sfkeller** [qgis/QGIS#43220]
**Feature description**

There are many WMTS/XYZ raster tile servers/services around which provide nice maps (see e.g. http://openwhatevermap.xyz/ ). 
All have to stop at a certain max. zoom level, say 18. 
Zooming in further shows either all of a sudden nothing or "No tiles available..."

In QGIS I often encountered the need to zoom in beyond this max. zoom level, say up to 22.

=> Suggestion is to allow arbitrary overzoom for WMTS/XYZ raster tile connections.

**Additional context**

The WMTS/XYZ "Add connection" dialog already contains "Min. Zoom Level" and "Max. Zoom Level".

This could be extended with a flag "Allow Overzoom [x]" (default: off).

In order to test this, try e.g. this STRAVA Map http://heatmap-external-a.strava.com/tiles/all/bluered/{z}/{x}/{y}.png which stops at max. zoom level 11 (1:200'000).

**Comment by saberraz** [comment]
I might be missing something, but for your second link, if you set the max zoom level correctly:
![image](https://user-images.githubusercontent.com/2649047/118290484-65da4c80-b4ce-11eb-8d7b-ea3b29bceb02.png)

If will display the tiles beyond 11 and keeps zooming in to the last view:
![zoom_level](https://user-images.githubusercontent.com/2649047/118290979-f44ece00-b4ce-11eb-92d9-7f0d3594b93a.gif)

**Comment by sfkeller** [comment]
My bad! You're right.
