### ISSUE TITLE
"Advanced digitizing panel" icon misplaced on the "Advanced digitizing" toolbar

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#43225]
I think it would be more coherent to place the "Advanced digitizing panel" icon at the beginning (it used to be there) and not where it currently displays
![image](https://user-images.githubusercontent.com/7983394/118298325-9f678380-b4df-11eb-8beb-8839bbf12ac3.png)

Version de QGIS | 3.19.0-Master | Révision du code | 7edc0f6079
-- | -- | -- | --
Qt version | 5.12.8
Python version | 3.8.5
GDAL/OGR version | 3.0.4
PROJ version | 6.3.1
EPSG Registry database version | v9.8.6 (2020-01-22)
Compilé avec GEOS | 3.8.0-CAPI-1.13.1 | Utilisé avec GEOS | 3.8.0-CAPI-1.13.1
SQLite version | 3.31.1
PostgreSQL client version | 12.6 (Ubuntu 12.6-0ubuntu0.20.04.1)
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.2
OS version | Ubuntu 20.04.2 LTS

</body></html>

**Comment by roya0045** [comment]
I agree, this would make more sense. Though this doesn't seem to be a bug.
