### ISSUE TITLE
qgis does not display layer attributes when there is a boolean field in layer stored in postgresql

### ISSUE THREAD

**Issue by alexcopa2002** [qgis/QGIS#43223]
qgis does not display layer attributes when there is a boolean field in layer stored in postgresql.

**Comment by gioman** [comment]
@alexcopa2002 you must be more detailed than this. I.e. I have several pgsql tables with boolean fields and they works ok on QGIS.

How can we replicate? Can you attach a dump of your your table? how is the table/layer configured in QGIS?

**Comment by alexcopa2002** [comment]
I have layers stored in a postgresql 8.2.6 database with postgis, all the layers are perfectly read but when any layer has a boolean field, it reads the geometries –they are drawn and visible in qgis- but the attributes are not displayed when trying open the table, this happens only if the layer has a boolean type field.

**Comment by gioman** [comment]
> postgresql 8.2.6

@alexcopa2002 and what about a more recent version of pgsql? can you test it?

**Comment by alexcopa2002** [comment]
not yet, but it is difficult to change the database because it has hundreds of tables in a production system with complex online web developments that must be readjusted, this problem did not happen with versions of qgis 3.8 or earlier, it read the boleans perfectly.

**Comment by gioman** [comment]
> not yet, but it is difficult to change the database because it has hundreds of tables in a production system with complex online web developments that must be readjusted, this problem did not happen with versions of qgis 3.8 or earlier, it read the boleans perfectly.

@alexcopa2002 you don't need to restore the entire db, just one table, on a local installation of a more recent version of pgsql.
