### ISSUE TITLE
Bad Request on feed.qgis.org 

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS#43232]
On my machine I get:

News feed request failed [error: Error transferring https://feed.qgis.org/?after=1619783203&lang=en_US - server replied: Bad Request]

https://feed.qgis.org/?after=1619783203&lang=en_US

![Screenshot-20210515121646-1058x303](https://user-images.githubusercontent.com/731673/118356848-74c90980-b577-11eb-80eb-99d4f13ce9d6.png)

Not sure why lang = en_US, but I start QGIS on an english Debian without any language parameter.
Maybe QGIS picks the wrong language param?
So maybe it is a QGIS issue? It is calling the feed url with the wrong locale code (the one with both the language and the country)

QGIS version | 3.19.0-Master | QGIS code revision | 5084127ab18
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.2
GDAL/OGR version | 3.2.1
PROJ version | 7.2.1
EPSG Registry database version | v10.008 (2020-12-16)
GEOS version | 3.9.0-CAPI-1.16.2
SQLite version | 3.34.1
PDAL version | 2.2.0
PostgreSQL client version | 13.2 (Debian 13.2-1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Debian GNU/Linux bullseye/sid
  |   |   |  
This copy of QGIS writes debugging output.
  |   |   |  
Active Python plugins | pdokservicespluginplugin_reloadertrackable_project_filesFeatureGridCreatorMetaSearchprocessingdb_manager

**Comment by mbernasocchi** [comment]
FWIW, in 3.18.2 (ubuntu) I do not have the warning

**Comment by rduivenvoorde** [comment]
@mbernasocchi it depends on the lang parameter, try the url in the openings post:

https://feed.qgis.org/?after=1619783203&lang=en_US

if you have a swiss locale, not sure what QGIS makes of it then... 
If I start QGIS iwth 'qgis --lang nl', then I seen that it fires

https://feed.qgis.org/?after=1619783203&lang=nl

which is fine...

Another (old) observation is that with my vanilla en_US install I always see:

```
Info: Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
../src/core/qgsapplication.cpp:190 : (QgsApplication) [176ms] loading of qgis translation failed /home/richard/bin/qgis_/master/debug/share/qgis/i18n//qgis_en_US
../src/core/qgsmessagelog.cpp:29 : (logMessage) [29ms] 2021-05-16T12:08:56 [1] Successfully loaded globalsettingsfile path: /home/richard/bin/qgis_/master/debug/share/qgis/resources/qgis_global_settings.ini
../src/app/qgsversionmigration.cpp:92 : (requiresMigration) [1ms] File version is=2
```
another observation that either Qt or QGIS tries to set/find translations based on the LANG environment variable (I think):

```
env | grep -i lang
GDM_LANG=en_US.UTF-8
LANG=en_US.UTF-8
```
