### ISSUE TITLE
Couldn't load SIP module. Version `Qt_5.15` not found

### ISSUE THREAD

**Issue by mwip** [qgis/QGIS#43244]
**Describe the bug**

On startup, I get the following error message: 

```
Couldn't load SIP module.
Python support will be disabled.


Traceback (most recent call last):
  File "", line 1, in 
  File "/usr/lib/python3/dist-packages/qgis/__init__.py", line 70, in 
    from qgis.PyQt import QtCore
  File "/usr/lib/python3/dist-packages/qgis/PyQt/QtCore.py", line 24, in 
    from PyQt5.QtCore import *
ImportError: /lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by /users/<username>/.local/lib/python3.6/site-packages/PyQt5/QtCore.abi3.so)


Python version:
3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0]

QGIS version:
3.16.3-Hannover 'Hannover', 94ac9f21b8

Python path:
['/usr/share/qgis/python', '/users/<username>/.local/share/QGIS/QGIS3/profiles/default/python', '/users/<username>/.local/share/QGIS/QGIS3/profiles/default/python/plugins', '/usr/share/qgis/python/plugins', '/opt/OTB-7.0.0-Linux64/lib/python', '/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload', '/users/<username>/.local/lib/python3.6/site-packages', '/usr/local/lib/python3.6/dist-packages', '/usr/lib/python3/dist-packages']
```

**How to Reproduce**

1. Open QGIS 3.16.3 (LTS, Ubuntu-PPA) 

**QGIS and OS versions**

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.16.3-Hannover | QGIS code revision | 94ac9f21b8
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.6.2-CAPI-1.10.2 4d2925d6
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 10.15 (Ubuntu 10.15-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Ubuntu 18.04.5 LTS
</body></html>

**Additional context**

- I checked my apt install, whether `unattended-upgrades` might have changed something but could not find anything suspicious about it. 
- I checked whether libQt5Core.so.5 existed, and so it does:
```
$ ll /lib/x86_64-linux-gnu/libQt5Core*
lrwxrwxrwx 1 root root      19 Feb  7  2020 /lib/x86_64-linux-gnu/libQt5Core.so.5 -> libQt5Core.so.5.9.5
lrwxrwxrwx 1 root root      19 Feb  7  2020 /lib/x86_64-linux-gnu/libQt5Core.so.5.9 -> libQt5Core.so.5.9.5
-rw-r--r-- 1 root root 5536104 Feb  7  2020 /lib/x86_64-linux-gnu/libQt5Core.so.5.9.5
```
- I reinstalled QGIS using `sudo apt remove qgis && sudo apt autoremove && sudo apt install qgis`, and the error persisted.

**Comment by gioman** [comment]
@mwip just tested on a clean Ubuntu 18.04 machine and with qgis.org's repos; no issues.

**Comment by mwip** [comment]
Apparently, there is something wrong with my `~/.local/lib/python3.6/site-packages/PyQt5`. After moving the folder, QGIS starts just fine.  Here is the "fix":
```
mv ~/.local/lib/python3.6/site-packages/PyQt5 ~/.local/lib/python3.6/site-packages/PyQt5.bak
```
