### ISSUE TITLE
Incorrect mesh layer visualisation with layout temporal range override

### ISSUE THREAD

**Issue by MattScorah** [qgis/QGIS#43242]
**Describe the bug**
I am using  a data defined override to set the temporal range of a map in a layout. The override for both the start and end is set based on fields in the atlas coverage layer (which are just datetime fields). When the temporal range is set this way the mesh layer in my project renders with the incorrect temporal range. Other temporally aware elements (e.g. vectors, layout labels with expressions) draw with the correct timestep. 

When the override is cleared (not just deactivated but cleared) and the temporal range is replaced with the same values the mesh draws with the correct temporal range. The mesh also draws correctly using the temporal controller in the main window. I have tested with GRIB and 2dm+XMDF meshes and the problem is present with both.

1. Main view - mesh (rainbow colors in background) displaying correctly
![MainView](https://user-images.githubusercontent.com/84299605/118426901-74637680-b70f-11eb-867d-0e8ee46df0a8.png)

2. Temporal range set by expression - temporal range evaluates to correct range (seen to right of image) but mesh displays incorrectly, vectors / layout label drawing correctly
![LayoutWithExpression](https://user-images.githubusercontent.com/84299605/118426900-73cae000-b70f-11eb-9661-d807f60e769e.png)

3. Temporal range set by values - mesh displays correctly
![LayoutHardcoded](https://user-images.githubusercontent.com/84299605/118426896-7299b300-b70f-11eb-93ff-e1fd475612b1.png)

**How to Reproduce**
I can provide a dataset / project on request.

**QGIS and OS versions**

> QGIS version
> 3.18.3-Zürich
> QGIS code revision
> 735cc85be9
> Compiled against Qt
> 5.11.2
> Running against Qt
> 5.11.2
> Compiled against GDAL/OGR
> 3.1.4
> Running against GDAL/OGR
> 3.1.4
> Compiled against GEOS
> 3.8.1-CAPI-1.13.3
> Running against GEOS
> 3.8.1-CAPI-1.13.3
> Compiled against SQLite
> 3.29.0
> Running against SQLite
> 3.29.0
> PostgreSQL Client Version
> 11.5
> SpatiaLite Version
> 4.3.0
> QWT Version
> 6.1.3
> QScintilla2 Version
> 2.10.8
> Compiled against PROJ
> 6.3.2
> Running against PROJ
> Rel. 6.3.2, May 1st, 2020
> OS Version
> Windows 10 (10.0)
> Active python plugins
> db_manager; 
> MetaSearch; 
> processing
>

**Comment by gioman** [comment]
>  I can provide a dataset / project on request.

@MattScorah yes thanks, can't you share it here?

**Comment by MattScorah** [comment]
> > I can provide a dataset / project on request.
> 
> @MattScorah yes thanks, can't you share it here?

Sure! See "Issue43242_ExampleProject.qgz" in attached below:
[ExampleProject.zip](https://github.com/qgis/QGIS/files/6496807/ExampleProject.zip)

**How to reproduce**

1. Open "FormattedFrames" layout in example project
2. Preview Atlas and chose an atlas page (e.g. 175, which is the page shown in the images in my first post)
3. In Item Properties for the "ERA5" map and note the temporal range is set to an expression. For page 175 the start and end should evaluate to 2013-01-24 18:00:00 and 2013-01-24 19:00:00 (you may need to deselect / reselect the map to get temporal range fields to update after the atlas page is changed)
4. Clear (not just deactivate but clear) the expressions from both the start and end of the temporal range
5. Change either the start or end manually to force a redraw (e.g. flick the second of the start time up and down one). The rendered mesh will change, even though the start / end time are the same as when populated by the expression

Please let me know if any more information / testing would be helpful

**Comment by vcloarec** [comment]
Hi,
This issue come from that, in the canvas (main windows and layout), the specified time is UTC and mesh layer consider time also as UTC.
But it seems the expression makes locale date/time by default.
So when time is not override, it is ok, mesh layer compare UTC time with UTC time. But with expression, mesh layer compare UTC time with locale time, to there is an offset, this offset could be the offset between UTC and your local time. In my time zone, I don't have the same result when the time is override... 

But vector layers do not care about the time is UTC or local... comparison is done after conversion from/to text without considering the time specification (local or UTC). So for vector layers, no offset...

To fix this, two solutions:
- change how the mesh layer consider the time, that will ask quite a big work...
- force the override time to be UTC.

I prefer the second one and I will try to fix the issue with this one.

For now the work round is to provide an ISO date format with UTC specification. If you format your date like this:
2021-05-19T12:00:00Z 
(Z for UTC)
it could work fine.

**Comment by MattScorah** [comment]
Thanks for the quick response and offering a workaround suggestion. I have tested and confirmed that the workaround resolves the issue for now. An updated version of the example project is below.
[WorkaroundImplemented.zip](https://github.com/qgis/QGIS/files/6518669/WorkaroundImplemented.zip)
