### ISSUE TITLE
Saving project to a postgresql database always set the project "save path" to absolute

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#43259]
Tested on 3.16:

create a project with some postgis layer, set save paths do "relative"

save the project to the DB > save paths are set to "absolute"

the above do not change even when adding some file based datasource to the project

Opening the project properties and se the save paths to "relative" do not work, is just enough to close the dialog and reopen it to have the paths set to absolute again. If the project is then saved locally, then it works as expected.

**Comment by nyalldawson** [comment]
I assume this is by design -- how would a relative path work?

**Comment by gioman** [comment]
> I assume this is by design -- how would a relative path work?

@nyalldawson not sure I understand. At some point I could want save into a DB a project with both postgis layers and file based datasources, and save the paths to the latter with relative paths. The connection string to the postgis layers should not matter (it is not really an absolute/relative path, or am I wrong?)?

**Comment by nyalldawson** [comment]
But what's a file path relative to a database? Eg what does "my_file.svg" or "my_file.shp" actually resolve to?

**Comment by gioman** [comment]
> But what's a file path relative to a database? Eg what does "my_file.svg" or "my_file.shp" actually resolve to?

right... sorry for the silly question.
