### ISSUE TITLE
Long (?) WKT makes delimited text layer fail on 3.16 and 3.18 (works fine on 3.8)

### ISSUE THREAD

**Issue by gerardolm** [qgis/QGIS#43256]
**Describe the bug**
A previously working WKT geometry definition makes "Add delimited text layer" fail. If the record containing the geometry is found at the beginning of the file, no records are added. However, if the record is half-way through the CSV, the records before that one are properly added.

**How to Reproduce**

1. Get CSV file from https://gist.githubusercontent.com/gerardolm/6c3c8d1fbc53f5f301f2991c3e0c65f3/raw/9d31319023d672b81c224d2cd643c1ecba60d7bd/balears.csv
2. Click on 'Layer', 'Add Layer', 'Add Delimited Text Layer...'
3. Choose the CSV file
4. See error reported at the bottom of the modal screen about "badly formatted records discarded"

**QGIS and OS versions**

Fails on:

QGIS version | 3.18.2-Zürich | QGIS code revision | 44d7dfabbe
-- | -- | -- | --
Compiled against Qt | 5.14.2 | Running against Qt | 5.14.2
Compiled against GDAL/OGR | 3.2.1 | Running against GDAL/OGR | 3.2.1
Compiled against GEOS | 3.9.1-CAPI-1.14.2 | Running against GEOS | 3.9.1-CAPI-1.14.2
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
Compiled against PDAL | 2.2.0 | Running against PDAL | 2.2.0 (git-version: Release)
PostgreSQL Client Version | 12.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.4
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | macOS 10.15
Active python plugins | QuickWKT; processing; db_manager; MetaSearch

Works fine on previous version:

QGIS version | 3.8.1-Zanzibar | QGIS code branch | Release 3.8
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.1-CAPI-1.11.0 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
PostgreSQL Client Version | 9.6.10 | SpatiaLite Version | 4.4.0-RC1
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS 10.15 | &nbsp; | &nbsp;

**Additional context**

Not sure if the problem is the size of the WKT string or some other property of the geometry or the WKT sub-strings.

**Comment by gioman** [comment]
@gerardolm maybe we are hitting some limit: I cannot copy/paste the (very large) definition of this WKT... not eveb outside QGIS, like in he kate editor (KDE). Opening directly the CSV also causes the editor to lock.
