### ISSUE TITLE
QGIS unexpectedly ended

### ISSUE THREAD

**Issue by TownTowner** [qgis/QGIS#43253]
Crash ID: d13b3e5abf01e548d3f2241539757d9d7d84ab05

Stack Trace

memcpy_repmovs memcpy.asm:114
QgsWmsProvider::readBlock qgswmsprovider.cpp:1017
QgsRasterDataProvider::block qgsrasterdataprovider.cpp:212
QgsSingleBandColorDataRenderer::block qgssinglebandcolordatarenderer.cpp:62
QgsBrightnessContrastFilter::block qgsbrightnesscontrastfilter.cpp:119
QgsHueSaturationFilter::block qgshuesaturationfilter.cpp:123
QgsRasterResampleFilter::block qgsrasterresamplefilter.cpp:164
QgsRasterProjector::block qgsrasterprojector.cpp:815
QgsRasterIterator::readNextRasterPartInternal qgsrasteriterator.cpp:130
QgsRasterDrawer::draw qgsrasterdrawer.cpp:60
QgsRasterLayerRendererFeedback::onNewData qgsrasterlayerrenderer.cpp:61
QgsWmsProvider::draw qgswmsprovider.cpp:966
QgsWmsProvider::readBlock qgswmsprovider.cpp:996
QgsRasterDataProvider::block qgsrasterdataprovider.cpp:212
QgsSingleBandColorDataRenderer::block qgssinglebandcolordatarenderer.cpp:62
QgsBrightnessContrastFilter::block qgsbrightnesscontrastfilter.cpp:119
QgsHueSaturationFilter::block qgshuesaturationfilter.cpp:123
QgsRasterResampleFilter::block qgsrasterresamplefilter.cpp:164
QgsRasterProjector::block qgsrasterprojector.cpp:815
QgsRasterIterator::readNextRasterPartInternal qgsrasteriterator.cpp:130
QgsRasterDrawer::draw qgsrasterdrawer.cpp:60
QgsRasterLayerRenderer::render qgsrasterlayerrenderer.cpp:321
QgsMapRendererParallelJob::renderLayerStatic qgsmaprendererparalleljob.cpp:353
QtConcurrent::MapKernel >::iterator,QtConcurrent::FunctionWrapper1 const & __ptr64> >::runIteration qtconcurrentmapkernel.h:69
QtConcurrent::MapKernel::iterator,QgsImageOperation::ProcessBlockUsingLineOperation >::runIterations qtconcurrentmapkernel.h:78
QtConcurrent::IterateKernel >::iterator,void>::forThreadFunction qtconcurrentiteratekernel.h:256
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.16.6-Hannover
QGIS code revision: bfd36fddc9
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by gioman** [comment]
@TownTowner try with a new QGIS profile, add all the requested infos.

**Comment by TownTowner** [comment]
> @TownTowner try with a new QGIS profile, add all the requested infos.

sorry , but how to set a new profile ?

**Comment by gioman** [comment]
> sorry , but how to set a new profile ?

@TownTowner settings > user profiles > new profile
