### ISSUE TITLE
Data Source Manager fails to derive exact 3D geometry type for `GeometryZ` PostGIS tables

### ISSUE THREAD

**Issue by brncsk** [qgis/QGIS#43268]
**Describe the bug**
When adding layers from a PostGIS database, QGIS's Data Source Manager offers multiple items in the list view for relations that contain a variety of geometry types. See the following screenshot for an example:

![image](https://user-images.githubusercontent.com/1205180/118610043-a9c59e00-b7bb-11eb-9035-5ddbe67eb55e.png)

(This time it's a materialized view, hence the warning sign).

However, when the table's geometry column is of type `GeometryZ` (see the excerpt from `geometry_columns` below) QGIS fails to downstream this information into the individual list view items so a 2D geometry type is inferred (e.g. `LineString` instead of `LineStringZ`).

There also seems to be no way to manually change the inferred geometry type (which might be by design).

This is problematic because AFAICT there's no way to add these relations as layers w/ a 3D geometry type.

![image](https://user-images.githubusercontent.com/1205180/118610272-e1344a80-b7bb-11eb-84a2-7bbfca2694c2.png)

**How to Reproduce**

1. Open the Data Source Manager
2. Connect to a PostGIS database that has a relation w/ a field of type `geometry(GeometryZ, ...)`
3. Observe QGIS offers multiple layers to add (one for each geometry type).
4. Observe QGIS derives 2D geometry types with no clear option to override this behavior.
5. Add any of the above layers, open Layer Properties, observe geometry is 2D.

**QGIS and OS versions**

QGIS version: 3.18.0-Zürich
OS version: macOS 11.1 (20C69)

**Comment by gioman** [comment]
@brncsk is this specific to the the data source manager or it happens also in DB Manager?

**Comment by gioman** [comment]
Can you attach the SQL definition of the table where you observed this? thanks.

**Comment by brncsk** [comment]
@gioman I'm sorry, I haven't tried w/ the DB Manager.

The following table definition seems to be sufficient to reproduce the problem:

```sql
CREATE TABLE test_3d (geom geometry(GeometryZ));
INSERT INTO test_3d (geom) VALUES
    ('POINT(0 0 0)'),
    ('LINESTRING(0 0 0, 0 0 0)'),
    ('POLYGON((0 0 0, 0 0 0, 0 0 0, 0 0 0))');
```

(Note that it's reproducible regardless whether I use `POINT` or `POINTZ` in the WKT strings, but this might as well be a WKT convention that I'm not familiar with.)

**Comment by gioman** [comment]
> ```sql
> CREATE TABLE test_3d (geom geometry(GeometryZ));
> INSERT INTO test_3d (geom) VALUES
>     ('POINT(0 0 0)'),
>     ('LINESTRING(0 0 0, 0 0 0)'),
>     ('POLYGON((0 0 0, 0 0 0, 0 0 0, 0 0 0))');
> ```

yep, confirmed.
