### ISSUE TITLE
2D and 3D in the 3D-View

### ISSUE THREAD

**Issue by StefanCiesilski** [qgis/QGIS#43263]
In the 3D-View i see the 2D ground also.

![grafik](https://user-images.githubusercontent.com/50232158/118594857-5bf46a00-b7aa-11eb-9a1f-e27624380e90.png)

[CityJSON.zip](https://github.com/qgis/QGIS/files/6498605/CityJSON.zip)
https://github.com/cityjson/cityjson-qgis-plugin

- Load CityJSON Loader plugin
- Load CityJSON file

**QGIS and OS versions**

<meta http-equiv="Content-Type" content="text/html; charset=utf-8"><style type="text/css">
p, li { white-space: pre-wrap; }
</style>

QGIS-Version | 3.18.0-Zürich | QGIS-Codeversion | bdef9fb3
-- | -- | -- | --
Kompiliert gegen Qt | 5.15.2 | Laufendes Qt | 5.15.2
Kompiliert mit GDAL/OGR | 3.2.1 | Läuft mit GDAL/OGR | 3.2.1
Kompiliert mit GEOS | 3.9.1-CAPI-1.14.2 | Läuft mit GEOS | 3.9.1-CAPI-1.14.2
Kompiliert mit SQLite | 3.33.0 | Läuft mit SQLite | 3.33.0
Gegen PDAL kompiliert | 2.2.0 | Läuft mit PDAL | 2.2.0 (git-version: 38aa11)
PostgreSQL-Client-Version | 13.0 | SpatiaLite-Version | 5.0.1-rc1
QWT-Version | 6.1.3 | QScintilla2-Version | 2.11.5
Kompiliert mit PROJ | 7.2.1 | Läuft mit PROJ | Rel. 7.2.1, January 1st, 2021
BS-Version | Windows 10 Version 2004
Aktive Python-Erweiterungen | BGTImport; gml_application_schema_toolbox; slyr_community; db_manager; MetaSearch; processing; CityJSON-loader

**Comment by wonder-sk** [comment]
This is the default behavior of QGIS, not a bug as such: once the layer is rendered on terrain, once as a true 3D entity. In https://github.com/qgis/QGIS-Enhancement-Proposals/issues/215 (which will be addressed in QGIS 3.22), the default behavior will change and in case user has enabled 3D rendering, the map layer will be excluded from rendering on terrain.
