### ISSUE TITLE
Geospatial PDF

### ISSUE THREAD

**Issue by goranbengtsson** [qgis/QGIS#43264]
**Feature description.**
Why is it not possible to save a map from the georeferencing window to a geospatial PDF as well as a geospatial TIFF file? It is possible to save as a PDF from the main window (though only what is visible on the screen). So the technology obviously exists. The advantage of PDF is that the files are significantly smaller in size and a PDF can be opened directly, from eg an email) in Avenza Maps.

**Additional context**

**Comment by gioman** [comment]
@goranbengtsson the print composer can export as both as geospatial pdf and geotiff, isn't what you are asking for?

**Comment by goranbengtsson** [comment]
I have tried to do so but, first, the output resolution is low and bad, second, it seems to me as a way to much work to do instead of have a PDF export option as well as a TIFF option from the georeferencing window. Some years ago the was a splendid plugin ”exportPDF” but it don’t work anymore (Hannover).

Br
Göran

På 18 maj 2021 kl. 10:08:34, Giovanni Manghi ***@***.***) skrev:

@goranbengtsson the print composer can export as both as geospatial pdf and geotiff, isn't what you are asking for?

**Comment by andreasneumann** [comment]
@goranbengtsson - you can change the output resolution in the export from the print layout as well as from the main window.

I do not think it is appropriate to add such export functionality to the  georeferencer window, due to several reasons:

- Georeferencer is still a plugin and not QGIS core
- It is a separate window (for now)
- It is duplicating functionality that exists in both main window and print composer

I think this feature request should be closed.

**Comment by goranbengtsson** [comment]
Thank’s
But if ”Georeferencer is still a plugin and not QGIS core”, how is it than possible to save as a Tiff-file? And not in other file format?
In mail window, as I have found out, it’s only possible to save whar you can see on the the screen as a pdf and not the whole map?
I know several user i sweden who use Qgis as I do and all want this funktion, inside the app, now when the old pdf plugin dos’nt work anymore in Hannover

Br
Göran

Skickat från min iPhone

**Comment by goranbengtsson** [comment]
Correct, thats what I want, but I want the function from georeference window and not the main window. The same way as for tiff save option
Br
Göran

Skickat från min iPhone

**Comment by gioman** [comment]
> But if ”Georeferencer is still a plugin and not QGIS core”, how is it than possible to save as a Tiff-file? And not in other file format?

@goranbengtsson the georeferencer is meant to... georeference images, so it is natural that outputs to GeoTIFF. If you need a geopdf it is also normal you created a layout, and export it to PDF.



> In mail window, as I have found out, it’s only possible to save whar you can see on the the screen as a pdf and not the whole map?

You are mixing up three distinct functionalities: quick save the map canvas to image, the georeferencer and the print composer. Each one of them has its own utility, but at the end are not the same.

> I know several user i sweden who use Qgis as I do and all want this funktion, inside the app, now when the old pdf plugin dos’nt work anymore in Hannover

you (qgis users in Sweden) could consider supporting the development of what you need and/or porting to QGIS 3 the plugin you say worked well for you.

**Comment by goranbengtsson** [comment]
Hi again Giovanni!
I’m so grateful for listen to my wishes, thank’s a lot!

This is the plugin, not longer works with Hannover.

https://plugins.qgis.org/plugins/GeorefExport/

/göran


På 18 maj 2021 kl. 13:18:39, Giovanni Manghi ***@***.***) skrev:

But if ”Georeferencer is still a plugin and not QGIS core”, how is it than possible to save as a Tiff-file? And not in other file format?

@goranbengtsson the georeferencer is meant to... georeference images, so it is natural that outputs to GeoTIFF. If you need a geopdf it is also normal you create a layout, and export it to PDF.

In mail window, as I have found out, it’s only possible to save whar you can see on the the screen as a pdf and not the whole map?

You are mixing up three distinct functionalities: quick save the map canvas to image, the georeferencer and the print composer. Each one of them has its own utility, but at the end are not the same.

I know several user i sweden who use Qgis as I do and all want this funktion, inside the app, now when the old pdf plugin dos’nt work anymore in Hannover

you (qgis users in Sweden) could consider supporting the development of what you need and/or porting to QGIS 3 the plugin you say worked well for you.

**Comment by gioman** [comment]
> This is the plugin, not longer works with Hannover.

@goranbengtsson it is an old plugin, and a 3rd party one (means is not part of QGIS). You must contact the author and see if it is interested in porting it to QGIS 3 or you can fork the code and port it to QGIS 3 yourself (or ask someone to do that).

**Comment by uclaros** [comment]
@andreasneumann The georeferencer is no longer a plugin, since 3.14 it's been in core! Also its window may be configured either as a separate one or a docked one.
@goranbengtsson You can convert your tiff to a pdf by using the *translate (convert format)* geoprocessing tool.

**Comment by goranbengtsson** [comment]
Thank’s a lot! That hears to me that this solve my ”problem”.
As I’m not finding this ”translate” in qgis, can you please send me a screen shot? I would appreciate it a lot!
Br
Göran

Skickat från min iPhone

**Comment by uclaros** [comment]
It should be in menu *Raster > Conversion > Translate (Convert format)...* and in the processing toolbox under *GDAL > Raster conversion > Translate (Convert format)*
