### ISSUE TITLE
Point Cloud Property window resizing issue

### ISSUE THREAD

**Issue by roya0045** [qgis/QGIS#43276]
I'm making a ticket in case anyone else has this. 

When trying to resize the Property window for a Point Cloud layer in QGIS 3.18.2 on windows, the window suddenly disappears and can never be seen again.

This seems to occur on symbology with Attribute by Ramp is active.

Since this is a modal window nothing else can be done for the session.
![Point_cloud_window_issue](https://user-images.githubusercontent.com/12854129/118662096-bcd96d80-b7bd-11eb-9bff-c6ed25c1e915.gif)

**Comment by roya0045** [comment]
@NEDJIMAbelgacem @wonder-sk Do you guys have any clue if this is fixed already or what might be the cause?

**Comment by roya0045** [comment]
![PC_property](https://user-images.githubusercontent.com/12854129/146650796-e87905d7-0d40-41cd-9a41-7ccc25bbb39d.gif)
Still present in the current version

**Comment by roya0045** [comment]
@saberraz I'm aware you guys are loaded, but with the recent crowdfund I'm curious to know if this bug might be fixed, I've quickly looked in the ui files and didn't see anything outright while comparing it to the vectorlayerproperty widget. So I'm unsure what is the root cause that prevent resizing on most tabs, except on the symbology tab where it only scale down.

**Comment by agiudiceandrea** [comment]
The issue still occurs on Windows using QGIS 3.28.12 and QGIS 3.34.0 and QGIS 3.35.0-Master, no matter which symbology type is set nor which tab is selected in the layer properties window.
