### ISSUE TITLE
QGis crashes joining a table

### ISSUE THREAD

**Issue by Magilla60** [qgis/QGIS#43271]
QGis crashes when i join a table.csv. The union field is a text string. The tables contains more records then the layer.shp

Report:
Crash ID: 50abde89ef65d099e7bcaff8bb3c218f46ae397b

Stack Trace

QVariant::clear :
QVariant::operator= :
QgsFeature::setAttribute qgsfeature.cpp:241
QgsAttributeForm::onAttributeChanged qgsattributeform.cpp:887
QMetaObject::activate :
QgsEditorWidgetWrapper::valuesChanged moc_qgseditorwidgetwrapper.cpp:275
::operator() qgstexteditwrapper.cpp:182
QMetaObject::activate :
QLineEdit::qt_static_metacall :
QMetaObject::activate :
QWidgetLineControl::finishChange :
QWidgetLineControl::internalSetText :
QgsTextEditWrapper::setWidgetValue qgstexteditwrapper.cpp:360
QgsEditorWidgetWrapper::setValue qgseditorwidgetwrapper.cpp:82
QgsTextEditWrapper::setFeature qgstexteditwrapper.cpp:230
QgsAttributeForm::resetValues qgsattributeform.cpp:815
QgsAttributeForm::setFeature qgsattributeform.cpp:296
QgsDualView::featureListCurrentEditSelectionChanged qgsdualview.cpp:628
QMetaObject::activate :
QgsFeatureListView::currentEditSelectionChanged moc_qgsfeaturelistview.cpp:281
QgsFeatureListView::editSelectionChanged qgsfeaturelistview.cpp:176
QMetaObject::activate :
QItemSelectionModel::emitSelectionChanged :
QItemSelectionModel::select :
QItemSelectionModel::select :
::operator() qgsfeaturelistview.cpp:479
QMetaObject::activate :
QTimer::timerEvent :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
QgisApp::showLayerProperties qgisapp.cpp:16020
QgisApp::layerProperties qgisapp.cpp:9175
QgisApp::layerTreeViewDoubleClicked qgisapp.cpp:658
QMetaObject::activate :
QAbstractItemView::doubleClicked :
QTreeView::mouseDoubleClickEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1637
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.16.7-Hannover
QGIS code revision: 0471743889
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

**Comment by gioman** [comment]
> QGis crashes when i join a table.csv. The union field is a text string. The tables contains more records then the layer.shp

@Magilla60 please attach the data and the specify the fields used for the join.

**Comment by Magilla60** [comment]
I apologize for the late reply.
The problem was solved by removing a field (multiline text string) from the table.csv.
Thanks for the support anyway!

**Comment by gioman** [comment]
> The problem was solved by removing a field (multiline text string) from the table.csv.
> Thanks for the support anyway!

@Magilla60 good, but if is a general issue it would be better to fix it, so we would still need your sample project+problematic data.
