### ISSUE TITLE
Windows tray notification title

### ISSUE THREAD

**Issue by Houska1** [qgis/QGIS#43270]
Windows tray notifications (e.g. when QGIS finishes something in the background) have the application title munged.

Example - launch QGIS, switch to a different application, QGIS displays the following as a system notification when finished loading. Note title at top.

![IMG_6213](https://user-images.githubusercontent.com/48919900/118628285-77f00f80-b79a-11eb-9dfe-ffbdb101a185.jpg)

OSGeo4Win 3.18.3, but has been around for 3.18.x at least and likely a few versions earlier. Maybe since build change? Not sure.

**Comment by nicogodet** [comment]
Happens also on 3.16.7 on testing OSGeo4W.

@Houska1 regular OSGeo4W or testing ?

**Comment by Houska1** [comment]
@nicogodet : testing
