### ISSUE TITLE
Crash with table set to Show Visible, joins, and left open as QGIS is quit

### ISSUE THREAD

**Issue by Saijin-Naib** [qgis/QGIS#43287]
**Describe the bug**
When QGIS has a default table view setting of Visible On Map combined with an open table and a layer with joins, it will crash repeatedly when closing/exiting provided the table view has not been closed out of first.

**How to Reproduce**
https://user-images.githubusercontent.com/19295950/118881308-ec24d300-b8c0-11eb-862b-61fd84f512d1.mp4

Settings:  
![image](https://user-images.githubusercontent.com/19295950/118881560-3ad26d00-b8c1-11eb-8079-5de75e215184.png)

Set table default view to View Visible On Map  
Have a table with at least one join (I think this is related)  
Close project/QGIS WITHOUT closing the table view first  
Crash

Project file (no data):  
[CAMP-RS_RIN_Update.zip](https://github.com/qgis/QGIS/files/6511454/CAMP-RS_RIN_Update.zip)

**QGIS and OS versions**

QGIS version
3.18.3-Zürich
QGIS code revision
735cc85be9
Compiled against Qt
5.15.2
Running against Qt
5.15.2
Compiled against GDAL/OGR
3.3.0
Running against GDAL/OGR
3.3.0
Compiled against GEOS
3.9.1-CAPI-1.14.2
Running against GEOS
3.9.1-CAPI-1.14.2
Compiled against SQLite
3.35.2
Running against SQLite
3.35.2
Compiled against PDAL
2.2.0
Running against PDAL
2.2.0 (git-version: 365171)
PostgreSQL Client Version
13.0
SpatiaLite Version
5.0.1
QWT Version
6.1.3
QScintilla2 Version
2.11.5
Compiled against PROJ
8.0.1
Running against PROJ
Rel. 8.0.1, March 5th, 2021
OS Version
Windows 10 Version 2009
Active python plugins
CalculateGeometry; 
MemoryLayerSaver; 
slyr; 
zoom_level; 
db_manager; 
MetaSearch; 
processing

**Additional context**
Has been present at least through the entire 3.18 release cycle (about when I started using Show Visible as default table behavior).

**Comment by gioman** [comment]
> Project file (no data):
> [CAMP-RS_RIN_Update.zip](https://github.com/qgis/QGIS/files/6511454/CAMP-RS_RIN_Update.zip)

@Saijin-Naib can you attach a zip with the project and the sample data? Thanks.

**Comment by Saijin-Naib** [comment]
[CAMP-RS_RIN_Update.zip](https://github.com/qgis/QGIS/files/6534796/CAMP-RS_RIN_Update.zip)

**Comment by gioman** [comment]
@Saijin-Naib thanks, crash also seen here following the described steps.

> [CAMP-RS_RIN_Update.zip](https://github.com/qgis/QGIS/files/6534796/CAMP-RS_RIN_Update.zip)
> This should have sufficient data to reproduce the issue, structured the same way as locally (minus these data being hosted on a shared Windows File Server)
