### ISSUE TITLE
Problems with the certificate GEANT OV RSA CA 4

### ISSUE THREAD

**Issue by LauraAlemany** [qgis/QGIS#43297]
Hello, 

In some of our services (for example, https://servicios.idee.es/wms/PNOA/PNOA?service=WMS&request=GetCapabilities), we use certificates from "GEANT OV RSA CA 4”, which in turn is authorised by “USERTrust RSA Certification Authority". Both of them are public authorities accepted by all the latest browsers.

The problem is that "GEANT OV RSA CA 4” certificate is relatively recent (18th of February, 2020) and it doesn’t seem to be included as a trusted web certificate in QGIS since it displays a security warning when we upload a service. 

Could you please include the GEANT OV certificate (here attached: [geant.zip](https://github.com/qgis/QGIS/files/6515608/geant.zip)) as one of your trusted certificates?

Thank you. 

Kind regards, 
Laura Alemany

**Comment by elpaso** [comment]
AFAIK QGIS does not ship root certs by its own. The root certs are provided by the operating system. 

But you can import into QGIS any additional certificate and give it the trust you like.
