### ISSUE TITLE
Loading Map Layout - Vector Layer with Callouts crashes QGIS

### ISSUE THREAD

**Issue by DrewFrance** [qgis/QGIS#43305]
## User Feedback

Loading a Map Layout with a vector layer that is using Callouts, it crashes every time.

## Report Details

**Crash ID**: [73b85ff3b5a432505dc78fb4b822d424085ac27b](https://github.com/qgis/QGIS/search?q=73b85ff3b5a432505dc78fb4b822d424085ac27b&type=Issues)

**Stack Trace**
<pre>
GEOSEquals_r :
GEOSEquals_r :
QgsGeos::shortestLine :
QgsGeometry::shortestLine :
QgsCallout::QgsCalloutContext::operator= :
QgsManhattanLineCallout::draw :
QgsCallout::render :
QgsVectorLayerLabelProvider::drawCallout :
QgsVectorLayerLabelProvider::drawLabelBackground :
QgsLabelingEngine::drawLabels :
QgsDefaultLabelingEngine::run :
QgsMapRendererJob::drawLabeling :
QgsMapRendererCustomPainterJob::doRender :
QgsMapRendererCustomPainterJob::staticRender :
QgsMapRendererCustomPainterJob::renderSynchronously :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.18.1-Z�rich
QGIS code revision: 202f1bf7e5
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

**Describe the bug**

**How to Reproduce**

4. See error -->

**QGIS and OS versions**

**Additional context**

**Comment by gioman** [comment]
@DrewFrance please try with a new QGIS profile, if the problem persist please attach a sample project with data that shows the issue.

**Comment by nyalldawson** [comment]
This was fixed in newer releases - please update to 3.18.3
