### ISSUE TITLE
Couldn't load plugin 'RasterAttributeTable' due to an error when calling its initGui() method 

### ISSUE THREAD

**Issue by M5610020** [qgis/QGIS#43325]
IMPORTANT:

Do NOT use GitHub to post any questions or support requests!
They will be closed immediately and ignored.
Questions should go to the qgis-user mailing list at https://lists.osgeo.org/mailman/listinfo/qgis-user
or other support forums such as https://gis.stackexchange.com/.

GitHub issues are for bug reports and suggestions for new features.

**Comment by nicogodet** [comment]
This should be reported here : https://github.com/noaa-ocs-hydrography/qgis-raster-attribute-table-plugin/issues

And I can't reproduce on 3.18.3 with available version of plugin on qgis repo.
