### ISSUE TITLE
attribute table disaster: disapearing data and automatic conversion to another language

### ISSUE THREAD

**Issue by disastergis** [qgis/QGIS#43329]
Dear smart QGIS people,

I do have several issues with using QGIS, I predict that this could be related, but I am not sure about that. 
The first and most disastrous one is data disappearing. all text data disappears after closing and opening again the document. Data before closing is saved. Additionally, numbers do stay in the table. 
why this happening? and how could I stop this from happening?
The second issue regarding the attribute table is related to the conversion of the titles of columns from I create and QGIS automatically change it in unreadable nonsense. This is also happening after closing and opening files. Furthermore, I do not use any special characters. So how could I stop this disaster from happening?
The last disaster is also related to language but it is related not with .shp, but with QGIS itself. Somehow QGIS while I am installing it recognize the country from which I joining and changes everything into the native language of that country. during installation, I was seeking where I could stop this from happening, but I could not find it. And I could not find where I could change it after installing. This is a very unhelpful and disturbing feature of QGIS. How could I reverse it to English? and stop this automatic stupidity?

Thank you for any advice - helpful or not :)

![Screenshot 2021-05-21 155404](https://user-images.githubusercontent.com/84575797/119140442-d512ec00-ba4c-11eb-8698-9f75ab025791.png)
 

IMPORTANT:

Do NOT use GitHub to post any questions or support requests!
They will be closed immediately and ignored.
Questions should go to the qgis-user mailing list at https://lists.osgeo.org/mailman/listinfo/qgis-user
or other support forums such as https://gis.stackexchange.com/.

GitHub issues are for bug reports and suggestions for new features.

**Comment by gioman** [comment]
> I do have several issues with using QGIS

@disastergis report each one of them using

https://github.com/qgis/QGIS/issues/new?assignees=&labels=Bug&template=10_bug_report.md&title=

and adding all the requested infos:

1) a meaningful title

2) a (short as possible) description

3) the list of detailed steps to replicate the issue

4) attach a sample project+data to allow others replicate


NB
Before any of the above try first using a new QGIS profile, no 3rd party plugins installed.
