### ISSUE TITLE
Old Versions of qgis-server packages missing in repository

### ISSUE THREAD

**Issue by thetuxinator** [qgis/QGIS#43331]
Hi guys, today i discovered, that older versions of packages are not been kept for qgiser-server packages, while they are still there for a part of the lib* packages.

In a debian/Ubuntu repo normally all versions should be kept. as an example, the only available package for Ubuntu is qgis-server_3.16.7+28bionic_amd64.deb and qgis-server_3.16.4+28bionic_amd64.deb is for example no more available. The reason why the old packages should always be kept (and thats the standard in Ubuntu) is that this way you can use a fixed version in your installation commands and also it allows you to for example downgrade to a particular testing and comparison.

kind regards

tuxinator

**Comment by gioman** [comment]
@thetuxinator not a problem with QGIS code (which this bu tracker is about), please raise the matter on the developers mailing list.

**Comment by jef-n** [comment]
our repositories only provide only the latest version.  and bionic is too old.  the qgis.org/ubuntugis provides bionic packages based on dependencies from ubuntugis.
