### ISSUE TITLE
Editing javascript code in HTML Form Editor result in QGIS hanging

### ISSUE THREAD

**Issue by BC-Consulting** [qgis/QGIS#43348]
### How to reproduce

Open `Attributes Form` from vector Properties
Select `Drag and Drop Designer`
Delete all entries under `Form Layout`
Drag and drop `HTML Widget` under `Form Layout`
`Configure HTML Widget` opens
In code editor type:
```
<html>
<head>
</head>
<body>
<script>

</script>
</body>
</html>
```

So far, so good.
Now between the `script` tag type:
**while(true**

And QGIS immediately hangs.
All data is lost as well as all code being entered in the code editor...
This is due to *immediate evaluation* of the code.

### System
QGIS Dev (3.18). Downloaded about 3 weeks ago, installed with  New OSGEO binaries.
Windows10 Pro.

**Comment by gioman** [comment]
> And QGIS immediately hangs.

@BC-Consulting can't confirm on QGIS master on Ubuntu 20.04.

**Comment by BC-Consulting** [comment]
@gioman thanks for testing.
You are absolutely right, in the submitted snippet there is no hang-up!
So, I created a dummy project (whilebug.qgz and whilebug.gpkg in the attached whilebug.zip file). In the code window of the HTML Form for the whilebug layer in the project, just type `while (true` where indicated and QGIS hangs.

To reproduce the bug you need to add references to layer fields (e.g. `var theName = expression.evaluate("\"Name\"")`) and insert the while loop between the definition of `theName` and `document.write(theName)`.

Can you confirm???

[whilebug.zip](https://github.com/qgis/QGIS/files/6527867/whilebug.zip)

**Comment by gioman** [comment]
> Can you confirm???

@BC-Consulting no, all ok here.

**Comment by BC-Consulting** [comment]
@gioman thanks again. Is it Windows10 specific then?

Screenshot attached to show it's really happening here...
![whilebug](https://user-images.githubusercontent.com/9070651/119256735-71123400-bbc2-11eb-9df1-7cf2d91635b9.jpg)

Note that an easy workaround is to use an external editor and copy-paste into the code editor.

**Comment by gioman** [comment]
> @gioman thanks again. Is it Windows10 specific then?

@BC-Consulting works fine on Win 10 here.

**Comment by BC-Consulting** [comment]
@gioman Well, thanks. If it cannot be reproduced, it is then something with my system.
Sorry for the troubles.
I'm closing the issue for now.
