### ISSUE TITLE
All versions of QGIS break the Toggle Editing "pencil" mode. 

### ISSUE THREAD

**Issue by bobg3723** [qgis/QGIS#43353]
I'm using QGIS 3.18 64bit Zurich installed with OSGeo4W64 installer on an Dell Latitude 5290 2-in-1 tablet running Windows 10 and I found a consistent bug. This bug does not occur on my Windows 8.1 desktop running the same version of QGIS.

Problem: The mouse jumps to another screen location when I attempt to click the **Toggle Editing** "_pencil_" icon. That will cause a bug forcing the mouse cursor to jump to the bottom left hand corner of the status bar. I'm also unable to select the _Check QGIS version_ drop down menu item under **Help** when I attempt to hover the mouse over it. That will also cause the mouse cursor to jump away.

This bug happens even when there are no layers loaded yet, but hovering the cursor over the "_pencil_" to attempt to Toggle Editing, the bug still occurs. I've tried different 64bit versions of QGIS stand-alone, Hanover, Zurich, and OSGeo4W64 installer versions. Same problem.

Computer Details-- Tablet: Dell Latitude 5290 2-in-1, Processor: Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz 1.90 GHz, Installed RAM: 8.00 GB (7.86 GB usable), System type: 64-bit operating system, x64-based processor, Pen and touch: Pen and touch support with 10 touch points

Windows Specification-- Edition: Windows 10 Pro, Version: 20H2, Installed on: ‎3/‎28/‎2021, OS build: 19042.985, Experience: Windows Feature Experience Pack 120.2212.2020.0

**Comment by gioman** [comment]
> Problem: The mouse jumps to another screen location when I attempt to click the **Toggle Editing** "_pencil_" icon. That will cause a bug forcing the mouse cursor to jump to the bottom left hand corner of the status bar. I'm also unable to select the _Check QGIS version_ drop down menu item under **Help** when I attempt to hover the mouse over it. That will also cause the mouse cursor to jump away.
> 
> This bug happens even when there are no layers loaded yet, but hovering the cursor over the "_pencil_" to attempt to Toggle Editing, the bug still occurs. I've tried different 64bit versions of QGIS stand-alone, Hanover, Zurich, and OSGeo4W64 installer versions. Same problem.

@bobg3723 this do not seems to be a general issue, but rather a local one.

Please try with a new QGIS profile, no 3rd party plugins installed.

**Comment by bobg3723** [comment]
I launched QGIS the next day. Inexplicably, the bug corrected itself with no intervention on my part. Strange.
