### ISSUE TITLE
crash when deleting a layout object while editing it

### ISSUE THREAD

**Issue by davidleite94** [qgis/QGIS#43350]
While editing a legend on Printing Layout, if you delet the object, QGis crashes.

Here's the report:

Crash ID: 11320892b0456920690737baab07697a8700ab13

Stack Trace

QMap::value qmap.h:656
QgsObjectCustomProperties::value qgsobjectcustomproperties.cpp:37
QgsLayout::customProperty qgslayout.cpp:417
QgsLayerTreeModel::flags qgslayertreemodel.cpp:374
QgsLegendModel::flags qgslayoutitemlegend.cpp:1151
QModelIndex::flags :
QTreeViewPrivate::isIndexExpanded :
QTreeViewPrivate::layout :
QTreeView::doItemsLayout :
QTreeViewPrivate::updateScrollBars :
QTreeView::updateGeometries :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QWidgetPrivate::sendPendingMoveAndResizeEvents :
QWidgetPrivate::show_helper :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidget::setVisible :
QStackedLayout::setCurrentIndex :
QgsPanelWidgetStack::closePanel qgspanelwidgetstack.cpp:140
QMetaObject::activate :
QgsPanelWidget::panelAccepted moc_qgspanelwidget.cpp:190
QMetaObject::activate :
QObject::~QObject :
QgsLayerTreeLayer::`vector deleting destructor' :
QgsLayerTreeNode::~QgsLayerTreeNode qgslayertreenode.cpp:48
QgsLayerTree::`vector deleting destructor' :
QgsLayoutItemLegend::~QgsLayoutItemLegend :
QgsLayoutItemLegend::`vector deleting destructor' :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1637

QGIS Info
QGIS Version: 3.16.6-Hannover
QGIS code revision: bfd36fddc9
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
> While editing a legend on Printing Layout, if you delet the object, QGis crashes.

@davidleite94 please try with a new QGIS profile, no 3rd party plugins installed. If the problem persist please attach a sample project+data.
