### ISSUE TITLE
Crash ID: e03f598b84601530981437a507662f485d0bb74f

### ISSUE THREAD

**Issue by Dianalucina** [qgis/QGIS#43355]
Crash ID: e03f598b84601530981437a507662f485d0bb74f

Stack Trace

QRasterPaintEngine::transformChanged :
QPainter::translate :
QGraphicsScene::dragMoveEvent :
QGraphicsScene::drawItems :
QGraphicsScene::drawItems :
QGraphicsView::paintEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :

QGIS Info
QGIS Version: 3.16.6-Hannover
QGIS code revision: bfd36fddc9
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

**Describe the bug**

**How to Reproduce**

4. See error -->

**QGIS and OS versions**

**Additional context**

**Comment by gioman** [comment]
@Dianalucina please fill the ticket with all the requested infos, and use a meaningful title, thanks.



**Describe the bug**


**How to Reproduce**



1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error -->

**QGIS and OS versions**



**Additional context**
