### ISSUE TITLE
UI: Emphasize that the OGC API URL must point to landing page

### ISSUE THREAD

**Issue by jratike80** [qgis/QGIS#43362]
In the WFS connection dialogue the user gives the OGC API Features connection URL with the URL box. It is documented in https://docs.qgis.org/3.16/en/docs/user_manual/working_with_ogc/ogc_client_support.html#wfs-and-wfs-t-client that user must write the address of the **landing page**
> In case of an OGC API - Features (WFS3), the URL to provide should be the landing page, ie the main page from which it is possible to navigate to all the available service endpoints.

By the OGC API standard the landing page URL contains always a forward slash, see examples from  https://github.com/opengeospatial/ogcapi-features/issues/427.
However, many OGC API examples in the web show the usage of the base address to access the landing page and quite many servers deliver the same landing page contents from addresses with and without the forward slash. For example
https://www.ldproxy.nrw.de/kataster?f=json
https://www.ldproxy.nrw.de/kataster/?f=json

There are also servers that strictly require the landing page URL to include the forward slash. The OAPIF services of the National Land Survey of Finland belongs to those.
This works with QGIS 3.18: https://avoin-paikkatieto.maanmittauslaitos.fi/maastotiedot/features/v1/
This does not work: https://avoin-paikkatieto.maanmittauslaitos.fi/maastotiedot/features/v1
(the service requires api-key that can be acquired through https://omatili.maanmittauslaitos.fi/user/new/avoimet-rajapintapalvelut?lang=en)

QGIS user interface or the logs do not offer any help for the user who tries to make connection with just the base URL because the error from the server is plain "not found".

Suggestions to improve the situation:
1) In case of failure QGIS might automatically make another try by adding the forward slash into the user given URL.
2) In case of failure QGIS might show a message to the user: Connection failed. Check the URL of the landing page.
3) The mouse over hint could show a message that landing page URL is required.

The mouse over hint seems to have also a copy-and-paste error at the moment and it suggests users to use WMS address.

![image](https://user-images.githubusercontent.com/1751612/119340235-f1a46380-bc9a-11eb-9232-df4f630964a7.png)

**Comment by rouault** [comment]
> There are also servers that strictly require the landing page URL to include the forward slash. The OAPIF services of the National Land Survey of Finland belongs to those.

NLS should consider being more tolerant. That should be a trivial fix

**Comment by jratike80** [comment]
> NLS should consider being more tolerant. That should be a trivial fix

Yes, we want that people can use our services easily and we do plan to be more tolerant.

I am not too familiar with Open API but I have been trying to read https://swagger.io/specification/ about the "Path Item Object"

> A relative path to an individual endpoint. The field name MUST begin with a forward slash (/). The path is appended (no relative URL resolution) to the expanded URL from the Server Object's url field in order to construct the full URL.

The text seems to say that if landing page is a path, as it is defined to be in the OGC API Core, then it must begin with `/` even the path is otherwise empty, and correspondingly URL without `/` cannot be a landing page. So it could mean that the NLS service is principally right but that is not crucial for us.
