### ISSUE TITLE
Attribute table open in new virtual desktops on Apple computers with Apple silicon cpus

### ISSUE THREAD

**Issue by sebastianmr6** [qgis/QGIS#43373]
When the attribute table is opened it is automatically opened in full size and in a new desktop, each time a new attribute table is opened a new desktop is created.
![Captura de Pantalla 2021-05-24 a la(s) 6 25 43 p  m](https://user-images.githubusercontent.com/32719931/119418375-7bfdbf00-bcbd-11eb-8c82-0d009eeaf342.png)
Cannot see window control buttons (minimize, maximize, close)
![Captura de Pantalla 2021-05-24 a la(s) 6 25 11 p  m](https://user-images.githubusercontent.com/32719931/119418344-6b4d4900-bcbd-11eb-9250-28f87d95b3d6.png)
stays in a cycle in which he always opens new desks
![Captura de Pantalla 2021-05-24 a la(s) 6 28 01 p  m](https://user-images.githubusercontent.com/32719931/119418534-d1d26700-bcbd-11eb-9bc1-0bce962144e7.png)

**Comment by gioman** [comment]
@sebastianmr6 it won't be easy to check/troubleshoot this given that I don't have a M1 device as also probably any dev. Anyway I'm wondering why this should be a QGIS bug and not just a bug in the way that Apple Silicon runs certain non Arm applications.

**Comment by roya0045** [comment]
It's this more of a Qt level bug?

**Comment by sebastianmr6** [comment]
> @sebastianmr6 it won't be easy to check/troubleshoot this given that I don't have a M1 device as also probably any dev. Anyway I'm wondering why this should be a QGIS bug and not just a bug in the way that Apple Silicon runs certain non Arm applications.

Hi, how can I corroborate that?

**Comment by gioman** [comment]
> Hi, how can I corroborate that?

@sebastianmr6 on Intel macs there is no such issue, this should be enough I guess.

**Comment by ccmorin** [comment]
Looks like this is closed, but wanted to confirm I have the same issue on an intel Mac running Big Sur, it is not apple silicon dependent

**Comment by PierreOn** [comment]
I had the same problem on mac OS 12.3. The problem was solved by creating a new profile or resetting the default one by deleting /Users/user_nameLibrary/Application Support/QGIS/QGIS3/profiles/default. All of my settings where of course lost.
