### ISSUE TITLE
ORS tools crashes QGIS

### ISSUE THREAD

**Issue by al-aminrahman** [qgis/QGIS#43379]
IMPORTANT:

Do NOT use GitHub to post any questions or support requests!
They will be closed immediately and ignored.
Questions should go to the qgis-user mailing list at https://lists.osgeo.org/mailman/listinfo/qgis-user
or other support forums such as https://gis.stackexchange.com/.

GitHub issues are for bug reports and suggestions for new features.

**Comment by nicogodet** [comment]
Should be reported here : https://github.com/GIScience/orstools-qgis-plugin/issues
