### ISSUE TITLE
data.gov CSW removal from MetaSearch plugin

### ISSUE THREAD

**Issue by kalxas** [qgis/QGIS#43386]
GSA is discontinuing the CSW interface of data.gov.
https://github.com/GSA/datagov-deploy/issues/3182
https://www.data.gov/meta/data-gov-to-discontinue-csw-service-on-may-1/

This means that data.gov has to be removed from default search catalogues in MetaSearch plugin.
I will shortly prepare a pull request for this.

**Comment by agiudiceandrea** [comment]
@tomkralidis when do you plan to remove the data.gov CSW server from the default search catalogues in MetaSearch plugin?

**Comment by tomkralidis** [comment]
PR in #45878
