### ISSUE TITLE
Features in Spatial Reference Join Disappeared

### ISSUE THREAD

**Issue by penguinmike66** [qgis/QGIS#43392]
I am working on a layer created by a spatial join.  I edited some fields, and now some of the features show in the attribute table but are not visible on the map.

**Comment by gioman** [comment]
@penguinmike66 please use the correct template

https://github.com/qgis/QGIS/issues/new?assignees=&labels=Bug&template=10_bug_report.md&title=

and fill it with all the requested infos, thanks!
