### ISSUE TITLE
'Follow Map Theme' does not reflect current state of Categorised Symbology 

### ISSUE THREAD

**Issue by tomtommahout** [qgis/QGIS#43395]
If I only select some categories in a Categorised Symbology layer and update the Theme - the Composer map displays all categories.

This particular layer is sourced from a MS Spatial Database, but the same behaviour occurs with Scratch layers.

We use the 'Follow Map Theme' option in Map Composer often to allow one QGIS project with multiple map outputs. Our workaround at the moment is to duplicate the layer and adjust the Layer Filter.

![image](https://user-images.githubusercontent.com/6088298/119579364-5504d180-be12-11eb-9298-8e68ac6a729c.png)

![image](https://user-images.githubusercontent.com/6088298/119579504-9eedb780-be12-11eb-855e-ff8967dcce7d.png)

**Comment by gioman** [comment]
@tomtommahout please attach a sample project+data that can be used to replicate the issue.

**Comment by tomtommahout** [comment]
I'm going to close this as I can't reproduce in a new project.  
The projects we are experiencing this behaviour are created from a project template that was created a few release versions ago.  I'm assuming it's related to old behaviour inheriting from the template.
Thank you for the quick response!
