### ISSUE TITLE
Broken formatting of tables in PyQGIS documentation

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#43405]
See eg
https://qgis.org/pyqgis/master/core/QgsVectorLayer.html
![image](https://user-images.githubusercontent.com/7983394/119625968-07d13180-be0b-11eb-961b-5ecfc3e3cb74.png)
Also true for https://qgis.org/pyqgis/master/core/QgsTextBackgroundSettings.html or https://qgis.org/pyqgis/master/core/QgsMergedFeatureRenderer.html ...
I don't know whether the source is in the pyqgis repo or here but reporting here since this one has more audience....

**Comment by Pedro-Murteira** [comment]
I can still confirm this issue, the format of the the tables in the documentation is still broken.

**Comment by ioalexei** [comment]
Table displays properly for me - Firefox v108.0.1
![image](https://github.com/qgis/QGIS/assets/3179403/79be334a-bff8-46c3-bebd-1e15ca9aba65)

**Comment by DelazJ** [comment]
Yes, let's close it
