### ISSUE TITLE
Moving Node Crash

### ISSUE THREAD

**Issue by Neil-Mansp** [qgis/QGIS#43408]
## User Feedback

QGIS 3.18.3
Moving points on a large polygon
The program crashed repeatedly
Also happened on QGIS 3.16.6 
Validation errors found

## Report Details

**Crash ID**: [0654e0ef3860c7b29f97f642d172209f630bee91](https://github.com/qgis/QGIS/search?q=0654e0ef3860c7b29f97f642d172209f630bee91&type=Issues)

**Stack Trace**
<pre>
geos::noding::snapround::MCIndexSnapRounder::computeVertexSnaps :
geos::noding::snapround::MCIndexSnapRounder::computeVertexSnaps :
GEOSEquals_r :
QgsGeos::relation qgsgeos.cpp:1501
QgsVertexTool::cadCanvasReleaseEvent qgsvertextool.cpp:607
QgsMapToolAdvancedDigitizing::canvasReleaseEvent qgsmaptooladvanceddigitizing.cpp:93
QgsMapCanvas::mouseReleaseEvent qgsmapcanvas.cpp:1972
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:475
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:475
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1638
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.18.3-Z�rich
QGIS code revision: 735cc85be9
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

**Describe the bug**

**How to Reproduce**

4. See error -->

**QGIS and OS versions**

**Additional context**

**Comment by tjukanovt** [comment]
@Neil-Mansp Also if you are not able to share the sample data, you could could define _large_ polygon (i.e. how many vertices), tell the file format and CRS you are using. Those would be helpful when attempting to replicate the crash.
