### ISSUE TITLE
Vector file limit causing crash

### ISSUE THREAD

**Issue by random1781** [qgis/QGIS#43411]
**Describe the bug**

After reaching ~100 visible vector layers (mostly gpx), QGIS either does not render data from newly imported layers and may hang/crash when rendering a change in the map display.

**How to Reproduce**

1. Start with new profile/new project/no plug-ins
2. Import layers until Warning is thrown:

> Warning 4: Failed to open /home/user/gis/adv/public_tracks/Nov2020.gpx: Too many open files.

Layers from files failed to open will be visible in the layer manager, but will not be rendered. QGIS does not crash.

3. Save project and close
4. Open project
5. Force renderer to update (i.e. zoom/pan map)
6. QGIS hangs with errors before crashing. [Full output is here.](https://github.com/qgis/QGIS/files/6547407/error.txt)

**QGIS and OS versions**

QGIS version | 3.18.3-Zürich | QGIS code branch | Release 3.18
-- | -- | -- | --
Compiled against Qt | 5.15.2 | Running against Qt | 5.15.2
Compiled against GDAL/OGR | 3.2.2 | Running against GDAL/OGR | 3.2.2
Compiled against GEOS | 3.9.0-CAPI-1.16.2 | Running against GEOS | 3.9.0-CAPI-1.16.2
Compiled against SQLite | 3.34.1 | Running against SQLite | 3.34.1
Compiled against PDAL | 2.2.0 | Running against PDAL | 2.2.0 (git-version: Release)
PostgreSQL Client Version | 13.2 | SpatiaLite Version | 5.0.1
QWT Version | 6.1.5 | QScintilla2 Version | 2.11.5
Compiled against PROJ | 7.2.1 | Running against PROJ | Rel. 7.2.1, January 1st, 2021
OS Version | Fedora 34 (Workstation Edition)
Active python plugins | MetaSearch; processing; db_manager

**Additional context**

- I cannot cause a crash until closing/reopening a project with all the layers.
- Disabling layer visibility prevents crashes
- Crashing only occurs when the renderer is used (i.e. I can open attribute tables, other context menus, etc.)
- I've read reports of kernel limits regarding file descriptors, but these are all 3+ years old. I've tried raising `ulimit -n 8192` but had no change in behavior.
- This behavior still occurs after a reboot with no other applications open. The system has 16GB of RAM.

**Comment by gioman** [comment]
> Warning 4: Failed to open /home/user/gis/adv/public_tracks/Nov2020.gpx: Too many open files.

@random1781 have you tried to raise the limit for open files at a operating system level?

**Comment by random1781** [comment]
> @random1781 have you tried to raise the limit for open files at a operating system level?

Unless there's a variable that I'm missing, yes:

`ulimit -n 8192`

`fs.file-max = 9223372036854775807`

**Comment by random1781** [comment]
This is my mistake. I was setting `ulimit -n 8192` in one shell and was launching QGIS in a _different_ shell without realizing that `ulimit` was a builtin and not applied system-wide.

Increasing the limit to 8k and launching QGIS in the same shell resolved this issue. No crashes or file limit warnings.
