### ISSUE TITLE
Print Layout will not open in QGIS 3.16

### ISSUE THREAD

**Issue by ervinjn** [qgis/QGIS#43414]
I have just installed QGIS 3.16.   I tried to create a new empty print layout from the Layout Manager.  I chose 'Empty Layout' from the drop-down, and clicked the 'Create' button.   A dialog box popped up entitled 'Create Print Layout'. The box is empty, and nothing else happens.  I am running QGIS 3.16.7 on Windows 10.  I did a stand-alone installation. I have no idea what to do.  In previous versions, the layout window would just open automatically.

I notice that is recommended that I "reach out to a developer" for a high priority issue.  This is definitely high priority for me, but I don't know how to 'reach out to a developer'.  

Really hoping someone can help

QGIS version
3.16.7-Hannover
QGIS code revision
0471743889
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
AzimuthDistanceCalculator; 
FreehandRasterGeoreferencer; 
GroupStats; 
Hotlink; 
LAStools; 
mmqgis; 
openlayers_plugin; 
processing_r; 
qad; 
qconsolidate3; 
QGIS3-getWKT; 
qgiscloud; 
qgis_resource_sharing; 
qgsAzimuth; 
quick_map_services; 
SemiAutomaticClassificationPlugin; 
SpreadsheetLayers; 
db_manager; 
MetaSearch; 
processing; 
CustomToolBar

**Describe the bug**

**How to Reproduce**

4. See error -->

**QGIS and OS versions**

**Additional context**

**Comment by gioman** [comment]
@ervinjn please try with a new QGIS profile, no 3rd party plugins installed.

**Comment by ervinjn** [comment]
Hi gioman.  I'm glad you mention that.  I tried to create a new user profile.  The 'New Profile Name' dialog box popped up, and it too was empty.  I recently took an online QGIS training course, and we did indeed install a number of plugins.  So that could be the issue.  Is there easy way to reset to the defaults, plugin-wise?

**Comment by gioman** [comment]
@ervinjn it seems you really have a local issue. Try to manually delete your QGIS3 folder that inside your AppData folder in your Windows user profile.

**Comment by ervinjn** [comment]
Okay.  I uninstalled all but the core plugins, and I deleted the QGIS3 folder under my AppData.  The issue still persists.

**Comment by gioman** [comment]
> Okay. I uninstalled all but the core plugins, and I deleted the QGIS3 folder under my AppData. The issue still persists.

@ervinjn try a different machine (to check if is still a local issue).

**Comment by ervinjn** [comment]
Okay.  will do.  if it is a local issue, what is the proper way to proceed.

**Comment by gioman** [comment]
> Okay. will do. if it is a local issue, what is the proper way to proceed.

write in the users/developers mailing list, this facility is to report bugs that are verified to be general issues.

**Comment by ervinjn** [comment]
Okay.  Thank you.  I guess what they mean by 'reach out to a developer'.  I'm like, I don't know any developers.  I think this thread can probably be deleted, and I'll post a new on in the other mailing list.

**Comment by ervinjn** [comment]
Giovanni.  I wanted to let you I resolved the issue.  Under menu Settings < Interface Customization, I had a widget cut off.  I had been taking an online training and we had been playing around with the Interface.  I turned them all back on, and it's working.  Thank you for your help.
