### ISSUE TITLE
[Processing] "Warn before executing if parameter CRS's do not match" does not work 

### ISSUE THREAD

**Issue by ghtmtt** [qgis/QGIS#43413]
In the General settings of Processing the `Warn before executing if parameter CRS's do not match` should warn if an algorithm involves many layers and they don't have the same CRS (at least this is my interpretation :) )

But it does not work.

Processing core algorithms handle an automatic on-the-fly conversion but custom scripts or plugin might not and this options is extremely useful.

If the behavior of this option is not the one that I've in mind than sorry for the noise

**Comment by gioman** [comment]
Agree, that option used to work (if I recall it returned a warning before running a tool).

**Comment by alexbruy** [comment]
In fact this still works, however most of the core tools already support inputs in different CRSs. So when running core tools it is unlikely that you will see that warning. To ensure that it still works, try for example core algorithm "Clip Vector By Mask Layer" with layers in different CRSs.

It is responsibility of the 3rd party tools to handle this setting correctly.

**Comment by ghtmtt** [comment]
> It is responsibility of the 3rd party tools to handle this setting correctly.

Are you talking about this piece of code?

```
def flags(self):
    return QgsProcessingAlgorithm.FlagSupportsBatch | QgsProcessingAlgorithm.FlagRequiresMatchingCrs  # cannot cancel!
```

So basically, as you said, is responsibility of the script/plugin/whatever to add this flag so that the setting knows when to be active?

**Comment by gioman** [comment]
> n fact this still works, however most of the core tools already support inputs in different CRSs. So when running core tools it is unlikely that you will see that warning. To ensure that it still works, try for example core algorithm "Clip Vector By Mask Layer" with layers in different CRSs.

@alexbruy ohh... so it never warned (in general for all native qgis tools) when using different CRSs? I was sure about it. Sorry.

**Comment by nyalldawson** [comment]
@gioman 
> ohh... so it never warned (in general for all native qgis tools) when using different CRSs? I was sure about it. Sorry.

It did in QGIS 2.x, but that was because no processing tools in that era did the auto-transformation.

I personally consider it a bug in an algorithm if it doesn't support auto-transformation (or an extreme limitation of a third party library). It's just such user-unfriendly behaviour! (In the case of "Clip Vector By Mask Layer" we should file a feature request upstream!).

**Comment by gioman** [comment]
> It did in QGIS 2.x, but that was because no processing tools in that era did the auto-transformation.

ahhh



> It's just such user-unfriendly behavior! (In the case of "Clip Vector By Mask Layer" we should file a feature request upstream!).

yes, but probably not so easy. For example GRASS data in locations/mapsets have by definition the same CRS. Not sure how easy would be for SAGA and GDAL.

**Comment by ghtmtt** [comment]
so basically this isn't a bug but an expected behavior. Is the following method correct to automatically handle the reprojection?

```
request = QgsFeatureRequest()
request.setDestinationCrs(source.sourceCrs(), context.transformContext()

for i in my_layer.getFeatures(request):
    ......
```

**Comment by nyalldawson** [comment]
@ghtmtt 

Yes, that's perfect :+1:

**Comment by ghtmtt** [comment]
@nyalldawson thanks! @gioman for me the ticket can be closed given that this is the expected behavior. Maybe we can add some documentation somewhere...
