### ISSUE TITLE
Crash on opening

### ISSUE THREAD

**Issue by rat319** [qgis/QGIS#43412]
Crash ID: 7f1e7133ed1d28cfa8fa2c01dac20ff76af8f7c7

Stack Trace

QgsFields::QgsFields :
QgsGrassProvider::fields :
QgsVectorLayer::updateFields :
QgsVectorLayer::readXml :
QgsMapLayer::readLayerXml :
QgsProject::addLayer :
QgsProject::_getMapLayers :
QgsProject::readProjectFile :
QgsProject::read :
QgsProject::read :
QgisApp::addProject :
QgisApp::openProject :
QgsTemporalControllerDockWidget::temporalController :
QMetaObject::activate :
QAbstractItemView::activated :
QAbstractItemView::mouseDoubleClickEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.18.1-Z�rich
QGIS code revision: 202f1bf7e5
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

**Comment by gioman** [comment]
@rat319 please fill al the requested infos?

https://github.com/qgis/QGIS/issues/new?assignees=&labels=Bug&template=10_bug_report.md&title=

Also try with a new QGIS profile, no 3rd party plugins installed.

**Comment by gioman** [comment]
**Describe the bug**


**How to Reproduce**



1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error -->

**QGIS and OS versions**



**Additional context**

**Comment by antoniolocandro** [comment]
I have the same issue, any project created in previos versions I select to open from the Recent Project window for example then it unexpectedly closes.

Using QGIS-dev (OSGEO4W) and Win 10, if I use stand-alone installer it works and opens correctly the projects . Tried without plugins, new profile and same behaviour

**Comment by antoniolocandro** [comment]
Updated OSGEO4W right now and not things are working again.

**Comment by rat319** [comment]
I installed latest standalone.  Seemed to work



Sent from my U.S.Cellular© Smartphone



-------- Original message --------
From: Antonio Locandro ***@***.***>
Date: 5/27/21 5:54 PM (GMT-05:00)
To: qgis/QGIS ***@***.***>
Cc: "Raymond C. Rase" ***@***.***>, Mention ***@***.***>
Subject: Re: [qgis/QGIS] Crash on opening (#43412)


I have the same issue, any project created in previos versions I select to open from the Recent Project window for example then it unexpectedly closes.

Using QGIS-dev (OSGEO4W) and Win 10, if I use stand-alone installer it works and opens correctly the projects . Tried without plugins, new profile and same behaviour

-
