### ISSUE TITLE
Installation failure - QGIS 3.16 or 3.18 on Mac OS 11.2.3 

### ISSUE THREAD

**Issue by GitterMeTimbers** [qgis/QGIS#43410]
I have successful installations of 3.4, 3.8, and 3.10 on this machine. Installing 3.16 or 3.18 yields the same result. The installation appears to be successful, but when opening the application, I get this message:

"QGIS-LTR can't be opened because Apple cannot check it for malicious software. This software needs to be updated. Contact the developer for more information."

Any suggestions?

**Comment by gioman** [comment]
> Any suggestions?

@misto go in macOS system settings and allow QGIS to run.
