### ISSUE TITLE
Refactor incorrectly converts from int64 to int8

### ISSUE THREAD

**Issue by stuskier** [qgis/QGIS#43437]
**Describe the bug**

When refactoring **_non-fid_** fields within a Geopackage attribute table, the output table's _**fid**_ field is also incorrectly converted from **Integer64** to **Integer8**, without the user requesting.  This error only happens when the table contains records; empty tables correctly output the _**fid**_  as **Integer64**.   This problem occurs with layer attribute tables as well as standalone attribute tables.

**How to Reproduce**

1. Refactor a Geopackage table
2. Review the output table's properties
3. Note that the output table's _**fid**_  field is now **Integer8**, when it should be **Integer64**

I am attaching screenshots of input and output table properties.

Input table:

![input_table_properties](https://user-images.githubusercontent.com/12805900/120008221-98387f00-bf8f-11eb-90b8-92876d6fbe57.jpg)

Refactored table:

![refactored_table_properties](https://user-images.githubusercontent.com/12805900/120008457-d0d85880-bf8f-11eb-8db8-fefa336279c6.jpg)

**QGIS and OS versions**

<meta http-equiv="Content-Type" content="text/html; charset=utf-8"><style type="text/css">
p, li { white-space: pre-wrap; }
</style>

QGIS version | 3.18.3-Zürich | QGIS code revision | 735cc85be9
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | batch_hillshader-master; changeDataSource; DissolveWithStats; ee_plugin; GlobeBuilder; GroupStats; LAStools; latlontools; mapswipetool_plugin; mmqgis; MultiDistanceBuffer; NNJoin; PointConnector; pointstopaths; qdraw; qfieldsync; Qgis2threejs; qgis2web; QGISSortAndNumber-master; qgis_gee_data_catalog; QRectangleCreator; quick_map_services; refFunctions; SemiAutomaticClassificationPlugin; Serval; shapetools; SpreadsheetLayers; ViewshedAnalysis; db_manager; MetaSearch; processing

**Additional context**

I first reported this problem in Stackexchange at: https://gis.stackexchange.com/questions/397984/qgis-refactor-fields-curiosity

**Comment by nyalldawson** [comment]
This actually isn't a bug -- the "type name" is just a reflection of some internal name the provider uses for the data type. The important thing is the "Type" column, which remains unchanged.

**Comment by stuskier** [comment]
Thanks, nyalldawson, for looking into this.  I now understand what you are saying: the refactor output **_fid_** remains qlonglong.  However, please allow me to make a case to keep this issue open: I (and others) spent a **lot** of good-faith time head-scratching this issue, and preparing the problem's description for both GIS Stack Exchange as well as this GitHub bug report.  I suspect that others in the future will likewise be puzzled and/or alarmed by the changed output **_fid_** and waste further time.  

Therefore, I propose that this problem be solved as a feature enhancement by simply forcing the _**fid**_ name to be Int64 whenever the type is qlonglong.  I suspect that a relatively small amount of coding time will really pay off for future QGIS users, allowing them to focus on their geospatial work rather than chasing down non-existant bugs.
