### ISSUE TITLE
QGIS 3.18 has an issue with generating XYZ Tiles (MBtiles) at a zoom level of 19+

### ISSUE THREAD

**Issue by Ennahoy** [qgis/QGIS#43447]
I.d like to report an issue with QGIS 3.18 concerning the generation of high density XYZ tiles (MBtiles). 

The issues i am about to report occurs while using the QGIS's QuickMapsService plugin, a.k.a; QMS, to generate maps from the ESRI World Imagery Maps. During the process, if I set the maximum zoom level to 19+ (these specific maps have a maximum zoom level of 22), QGIS fails to deliver what Ive obtained. The program will complete the process, but when i try to view the newly generated map, nothing shows up on the view port navigator despite the process claiming to finish successfully. QGIS becomes very unresponsive and will just show a blank white screen in the view port.  After waiting a long time, I check the task manager; in which Windows will report that 99% of the memory is in use. Soon; Windows will start throwing low memory warnings and my PC eventually becoming 99% unresponsive unless i end the QGIS process via the task manager. Is this some kind of memory leak? I have seen other users of various different issues that are related to mine, but not exact also raise the question of QGIS seemingly suffering from a memory leak under certain circumstances. I am running these instances of QGIS 3.18 on Windows 7 Ultimate 64bit. Its important to note; that I have ran into these issues on more than 1 pc,. One is using an Intel i9, and the other using an AMD RYZEN. 1 Pc has 8gb of DDR3 while the other has 16GB of DDR4. I will note that on the pc with DDR4, the program will eventually load the map, but navigation is unrealistically slow to the point that its useless to try and view it anyway.

In addition to this issue, sometimes while performing the "generate XYZ tiles (mbtiles) tiles" for a large portion of a map, (like a piece of a country); QGIS will throw an error titled "QGIS has unexpectedly crashed". This causes the project to end and the already lengthy process is lost.

What is the course of action for this issue and can/will it be fixed? Can QGIS actually handle these operations? whats the limit?

**Comment by gioman** [comment]
> What is the course of action

@Ennahoy add the detailed steps to replicate as requested by the bug report template

https://github.com/qgis/QGIS/issues/new?assignees=&labels=Bug&template=10_bug_report.md&title=



**Describe the bug**


**How to Reproduce**



1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error -->

**QGIS and OS versions**



**Additional context**




> and can/will it be fixed?

there is no guarantee it will be fixed sooner than layer (admitting the bug is confirmed), If this is a blocker for you then you should consider submitting a patch (if you can code) or hire a developer and have it fixed (see the commercial support page on qgis.org web site).

**Comment by gioman** [comment]
>  generate maps from

what is the extent you are trying to export? and min/max zoom? and tile format? using meta-tiles?

**Comment by Ennahoy** [comment]
Thanks for the quick reply, i will be back soon with the reformatted data and extra information requested.

**Comment by Ennahoy** [comment]
The extent I downloaded is -8527
606.8085,
-8478176.5237,
1996630.4317,
2076513.3027 [EPSG:3857]

of the Esri world imagery map

Min zoom 19 
Max zoom 20

DPI 150

Tile format jpg

Metatile size default 4

Output file was about 5gb

This is just one example I attempted this a number of time with same parameters except the map extent which differed but were always of a similar size.

**Comment by gioman** [comment]
> Output file was about 5gb

@Ennahoy thanks. I tried it and the result is a mbtile file with 7.6gb and roughly 300k X 500k pixels (as per gdalinfo) and probably for this reason I'm not able to load it in QGIS (I'm trying to build overviews, but is taking a very long time).

**Comment by Ennahoy** [comment]
So this is more so a very memory intensive task than an actual memory leak?

And If so what would you recommend as a good amount of memory to tackle this task with in the future?
Thanks

**Comment by gioman** [comment]
> So this is more so a very memory intensive task than an actual memory leak?

@Ennahoy not sure, I did it on a very robust workstation, but I also didn't paid attention to memory consumption.

**Comment by Ennahoy** [comment]
Ok. Well while you look into issue, if the main question could be answered as to if there is an issue with QGIS being able to view layers extremely dense layers, i would appreciate that. While trying to view layers 20 - 22 of certain maps, there is no data. Is this a QGIS problem or an ESRI map problem?

**Comment by gioman** [comment]
>  or an ESRI map problem

@Ennahoy have you tried with something else?

**Comment by Ennahoy** [comment]
Not yet, but those are the two main entities involved in generating the MBTiles that are unviewable. So if it's not qgis's fault, perhaps it's the ESRI Maps
