### ISSUE TITLE
Enhancement of (auto-) completer-function in value-relations

### ISSUE THREAD

**Issue by koenigherford** [qgis/QGIS#43457]
**Using forms in QGIS will be more efficient if the (auto-)completer-function in value-relations in input-forms not only selects the value by the first characters of the input but additionally by a search-pattern within the whole attribute - independent of position in the text
**
As far as I know you now have 2 possibilities to select a value in a value relation:
1) Drop down menu ("Use completer" deactivated)
![grafik](https://user-images.githubusercontent.com/28433436/120145520-f198ec00-c1e3-11eb-9889-82037a148fd5.png)

If there are long lists of selectable entrys this may cause a lot of scrolling through the list. 

Alternatively you can use the "Use completer"-Function:

2) Input with "use completer" activated:
![grafik](https://user-images.githubusercontent.com/28433436/120146133-e98d7c00-c1e4-11eb-9282-bceafbbf974b.png)

But if you do not remember the first characters of the values correctly, it will be hard to select the correct entry. In my example you only know, the person you wanted to select was a "Mouse". 

![grafik](https://user-images.githubusercontent.com/28433436/120146192-0033d300-c1e5-11eb-8cfe-15f34de67f1d.png)

It would be great, if QGIS will return a result as shown below not only if you remember the first characters of the values but alternatively some characters / search pattern somewhere within the attribute (i.e. "Mouse")
![grafik](https://user-images.githubusercontent.com/28433436/120146331-35d8bc00-c1e5-11eb-983f-26fd95bd8c6e.png)

**Comment by signedav** [comment]
Btw. QField does not only support the search of other parts than the start of a word, but also to search  for the "words" seperated by space:
![Peek 2020-11-24 17-33](https://user-images.githubusercontent.com/2820439/100115477-3a5d9a00-2e7b-11eb-984f-0b49b72f11d0.gif)

This option might make sense in QGIS as well?

Since @suricactus made some thoughts about it on the QField implementation he made, he might have an opinion here as well?

**Comment by signedav** [comment]
Anyway. I think it's made on purpose to search for the beginning of the word only. I wonder if people would appreciate to have an option in the widget settings to choose the search-mode...

**Comment by katagen** [comment]
It will be very useful. For exemple, if you have a list of 400 species with common name and latin name in brackets, sometime you remember only the latin name!

**Comment by suricactus** [comment]
@katagen what is the limitation you are experiencing with the current QField version? If you type only the latin or only the common name, it should be found?

@signedav I am not sure if we need to add this as an option, or just add more weight for results that start with the searched term.

**Comment by katagen** [comment]
With QField it's perfect... but on QGIS not!

**Comment by 9ls1** [comment]
Support the search of other parts in QGIS would be great. It would also be convenient if the drop down list could be available (in case you cant remeber the alternatives). See

**Comment by koenigherford** [comment]
Closed because of newly commited feature https://github.com/qgis/QGIS/pull/56733 some hours ago.

Thank you for developing and implementing this feature !
