### ISSUE TITLE
memory layer doesn't support QVariantList type so pasting from an attribute table that has type array doesn't work

### ISSUE THREAD

**Issue by tudorbarascu** [qgis/QGIS#43450]
Well. the title describe it.

Pasting into a memory layer from an attribute table that's based postgresql integer array (any kind of array actually) doesn't work.

Steps to reproduce:

- Create the following table: ``CREATE TABLE test (id serial PRIMARY KEY, demo int[]);``
- INSERT data:                ``INSERT INTO test (demo) SELECT '{0,1}';``
- Add the table in QGIS, open attribute table and select the feature then paste features as temporary scratch layer (CTRL + ALT + V shortcut)
- You get the error :``Paste features: Cannot create field demo (_int4,QVariantList)``

Tested on QGIS Master 3.19 and 3.16.7.

**Comment by nyalldawson** [comment]
Can you confirm which master version you are running? I've tested and can't reproduce. This was likely fixed by https://github.com/qgis/QGIS/pull/42421

**Comment by tudorbarascu** [comment]
Well.. it's actually fixed, I hadn't build for 3 days :)) and I tested before. Niceee.. sorry for the noise :(.
