### ISSUE TITLE
Very slow loading of QGIS project

### ISSUE THREAD

**Issue by francescopoliti** [qgis/QGIS#43466]
With the latest updates of QGIS, on the same computer, projects that previously opened quickly are now taking a long time.

**Comment by Gustry** [comment]
We are missing a lot of information to help you. You should fill a ticket following the template provided.

You should use the "Debug panel" then the "Profiler" to check the loading times for both QGIS Startup AND Project Loading time.
You will get the time breakdown.

Try with a new QGIS Profile as well. Maybe it's a plugin taking a long time, so not QGIS Core.
