### ISSUE TITLE
QGIS/python/plugins/db_manager/ "NoneType error"

### ISSUE THREAD

**Issue by cji82** [qgis/QGIS#43473]
QGIS version 3.18.1
-----------------------------error log ---------------------------------
2021-06-01T09:01:23     WARNING    Traceback (most recent call last):
              File "C:/PROGRA~2/QGIS3~1.18/apps/qgis/./python/plugins\db_manager\dlg_sql_window.py", line 543, in fillColumnCombos
              for col in cols:
             TypeError: 'NoneType' object is not iterable
             
-------------------------query-----------------point data-----------------
select *
from ST_Transform(ST_SetSRID(ST_GeometryFromText('POINT(126.934419305929 37.3990527348242)'),4326),5174) p
----------------------------------------------------------------------------
query resutl = p
new layer load -> Column select( not work) -> load (geometry point data not load...attribute load)

**If QGIS version 3.10 is lower,
Query returns point geometry data**

**Comment by gioman** [comment]
@cji82 no error here on QGIS master running (and loading as point)

```
select 1 AS id, *
from ST_Transform(ST_SetSRID(ST_GeometryFromText('POINT(126.934419305929 37.3990527348242)'),4326),5174) As geom
```

**Comment by cji82** [comment]
> @cji82 no error here on QGIS master running (and loading as point)
> 
> ```
> select 1 AS id, *
> from ST_Transform(ST_SetSRID(ST_GeometryFromText('POINT(126.934419305929 37.3990527348242)'),4326),5174) As geom
> ```
If QGIS version 3.10 is lower,
Query returns point geometry data :)

Dont work QGIS version 3.18.1... point data

**Comment by gioman** [comment]
> Dont work QGIS version 3.18.1... point data

@cji82 works fine here, 3.18.2

![Capture](https://user-images.githubusercontent.com/1951107/120299010-7eb27280-c2c2-11eb-9595-a7e2beedca43.PNG)

**Comment by cji82** [comment]
> > Dont work QGIS version 3.18.1... point data
> 
> @cji82 works fine here, 3.18.2
> 
> ![Capture](https://user-images.githubusercontent.com/1951107/120299010-7eb27280-c2c2-11eb-9595-a7e2beedca43.PNG)

Hmm :(
After the version 3.18.3 upgrade, the test result is the same as before

Is there any effect of Python installed on the system? python installed 2.7
![error2](https://user-images.githubusercontent.com/58581574/120408220-88eb7400-c389-11eb-9e8a-25155e590d36.png)
