### ISSUE TITLE
Composer - Image "raster" and data defined button

### ISSUE THREAD

**Issue by SIG-CLCL** [qgis/QGIS#43485]
**Describe the bug**

Impossibility to use dynamic "raster" images (linked to a field or expression) in the composer. The image type automatically switches to SVG when you use the data defined button to set the image source from a record or using a regular expression and remains blocked like this.
This makes it impossible to use illustrations for an atlas.

**How to Reproduce**

In composer, select an image
1. Go to 'Properties -> Image Raster'
2. Click on 'Field type -> String' and select the data defined button to set the image source from a record or using a regular expression
4. See error -->Image type automatically switches to SVG and gets stuck like this

**QGIS and OS versions**

Version de QGIS : 3.18.3-Zürich
Révision du code : 735cc85be9
Compilé avec Qt : 5.11.2
Utilisant Qt : 5.11.2
Compilé avec GDAL/OGR : 3.1.4
Utilisé avec GDAL/OGR : 3.1.4
Compilé avec GEOS : 3.8.1-CAPI-1.13.3
Utilisé avec GEOS : 3.8.1-CAPI-1.13.3
Compilé avec SQLite : 3.29.0
Fonctionne avec SQLite : 3.29.0
Version du client PostgreSQL : 11.5
Version de SpatiaLite : 4.3.0
Version de QWT : 6.1.3
Version de QScintilla2 : 2.10.8
Compilé avec PROJ : 6.3.2
Fonctionne avec PROJ : Rel. 6.3.2, May 1st, 2020
Version de l'OS : Windows 10 (10.0)

AND

Version de QGIS : 3.16.7-Hannover
Révision du code : 0471743889
Compilé avec Qt : 5.11.2
Utilisant Qt : 5.11.2
Compilé avec GDAL/OGR : 3.1.4
Utilisé avec GDAL/OGR : 3.1.4
Compilé avec GEOS : 3.8.1-CAPI-1.13.3
Utilisé avec GEOS : 3.8.1-CAPI-1.13.3
Compilé avec SQLite : 3.29.0
Fonctionne avec SQLite : 3.29.0
Version du client PostgreSQL : 11.5
Version de SpatiaLite : 4.3.0
Version de QWT : 6.1.3
Version de QScintilla2 : 2.10.8
Compilé avec PROJ : 6.3.2
Fonctionne avec PROJ : Rel. 6.3.2, May 1st, 2020
Version de l'OS : Windows 10 (10.0)

**Additional context**

**Comment by agiudiceandrea** [comment]
Is this a duplicate of https://github.com/qgis/QGIS/issues/42280?

**Comment by SIG-CLCL** [comment]
Yes, it is. Sorry.
