### ISSUE TITLE
QGIS reads CRS wrong

### ISSUE THREAD

**Issue by meyerlor** [qgis/QGIS#43482]
Greetings,
whenever i open a layer (whichever format, .TAB, Geopackage..) which was saved to EPSG:25832 (by QGIS) it reads the CRS as EPSG:7791. It still displays the features on site, but it's still quite confusing why this is happening.

**Comment by gioman** [comment]
> which was saved to EPSG:25832 (by QGIS)

@gioman cannot confirm here:

loaded the world map (by typing "world" in the coordinate display in the bottom bar of QGIS)

selected Germany

exported the selected feature as GPKG in EPSG:25832

resulting layer shows EPSG:25832 in its properties.

**Comment by meyerlor** [comment]
@gioman if i repeat the steps described by you, with a complete fresh user profile, layer properties show now "EPSG:32632" when exporting to MapInfo .TAB. 
Export to SHP/geopackage works as desired - so i guess it's the MapInfo driver - should i report this somwhere else then?
QGIS version is 3.16.7

**Comment by gioman** [comment]
> @gioman if i repeat the steps described by you, with a complete fresh user profile, layer properties show now "EPSG:32632" when exporting to MapInfo .TAB.


@meyerlor does it means that works as expected now also when saving as Mapinfo?

**Comment by meyerlor** [comment]
no, it means it is not working with the export to MapInfo. I checked my QGIS gdal version - it is 3.1.4. Release notes of GDAL show improvements to the MITAB driver in version 3.2 - so i guess we'll have to wait until the new gdal version is included in QGIS?

**Comment by gioman** [comment]
> no, it means it is not working with the export to MapInfo. I checked my QGIS gdal version - it is 3.1.4. Release notes of GDAL show improvements to the MITAB driver in version 3.2 - so i guess we'll have to wait until the new gdal version is included in QGIS. sorry for bothering you!

@meyerlor yes, see

https://github.com/qgis/QGIS/issues/35824

and this

https://github.com/qgis/QGIS/issues/33243

**Comment by agiudiceandrea** [comment]
@meyerlor if you are using Windows, the new QGIS in OSGeo4W testing (https://qgis.org/it/site/forusers/download.html) already ship GDAL 3.2.2/3.3.0.
