### ISSUE TITLE
Label ignores data defined rotation if truncated on edge of layout map

### ISSUE THREAD

**Issue by cxcandid** [qgis/QGIS#43492]
Looks like there is a bug in QGIS 3.18.3-Zürich (Windows 64) where data defined label rotations are lost during truncation on layout map edges. Unfortunately, I couldn't find any setting to prevent this behaviour.

![Clipboard](https://user-images.githubusercontent.com/58068164/120341965-a53ed080-c2f7-11eb-875f-8512285c1fd9.jpg)

**Comment by gioman** [comment]
@cxcandid can you share a small sample project+data that shows the issue? thanks.

**Comment by cxcandid** [comment]
@gioman here's a simple test project showing the issue in the print layout.

[label_test.zip](https://github.com/qgis/QGIS/files/6586246/label_test.zip)

**Comment by gioman** [comment]
Confirmed also on master.

**Comment by cxcandid** [comment]
Oh, what a stupid guy I am! ...this is indeed an intended feature and NOT a bug!
It's sometimes wise to read the full documentation. 😉

To keep the label rotation we have to check *"Allow truncated labels on edges of map"* in the label settings of the layout map.
![toolbar](https://user-images.githubusercontent.com/58068164/148740480-ee7afd37-4297-4995-9b1e-5b339b218420.JPG)
![label_settings](https://user-images.githubusercontent.com/58068164/148740493-d85f8875-0a0e-4dfe-a228-80d79d21a5f2.JPG)
