### ISSUE TITLE
Main window cut off - Windows 10 display scaling on, Layer Styling panel on

### ISSUE THREAD

**Issue by Houska1** [qgis/QGIS#43496]
Trying most recent OSGeo4W (new) 3.19 master.

On startup, bottom ~70 pixels of main window are cut off. 
Main window cannot be resized smaller to make them appear.

Simultaneously, I get the following **log message**:
Qt : QWindowsWindow::setGeometry: Unable to set geometry 1920x1117+0+29 (frame: 1938x1164-9-9) on QWidgetWindow/"QgisAppWindow" on "\\.\DISPLAY1". Resulting geometry: 1920x1051+0+29 (frame: 1938x1098-9-9) margins: 9, 38, 9, 9 minimum size: 1003x1117 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=1021,1164 maxtrack=0,0)

Works **fine in 3.18.3** (and all previous versions).

I run QGIS maximized (full screen), on a laptop with a 1920x1080 screen, with **display screen resolution scaling** (in Windows settings) set to 125%.

The problem does not occur if I set screen resolution scaling to 100% and restart QGIS Master, and comes back if I set it again to 125% (and restart QGIS). So I suspect something has regressed regarding logical vs physical screen DPI at startup.

[I don't know when precisely the regression occurred -- I run the standard release most of the time, but (like now) try the pre-release dev master a few weeks before release.]

**Comment by Houska1** [comment]
Update:
It's related to the Layer Styling panel, which I have full height docked at the right of my screen.
If I close that panel, my main window becomes resizable. If I re-activate it, the problem reoccurs.

If (back in 3.18.3) I move Layer Styling to be docked on top rather than on the right, then back in 3.19 Master I still have the problem, and in addition the top dock is no longer ~20% of the screen, but covers the whole canvas. So it's somehow Layer Styling asking for too much screen vertical real estate?

**Comment by antoniolocandro** [comment]
I can confirm I have the same problem, I don't know anything about scaling as I don't touch the defaults too much. Using windows 10 and the qgis version shown on the screen title bar

![image](https://user-images.githubusercontent.com/4627073/120692788-79415d80-c465-11eb-92c5-d480f6248d1e.png)

**Comment by nyalldawson** [comment]
Probably fixed by https://github.com/qgis/QGIS/pull/43609

**Comment by Houska1** [comment]
Confirmed as fixed in this morning's OSGeo4Win master build. Thanks.

(Did not investigate the temporal controller connection that seems to have precipitated this as per the fix, but have checked that the main window being cut off by the minimum size of the Layer Styling panel issue no longer occurs.)
