### ISSUE TITLE
Storing SVG symbols in sqlite/geopackage

### ISSUE THREAD

**Issue by dr1542** [qgis/QGIS#43506]
**Feature description.**
Storing SVG symbols in sqlite can help make map projects portable. To do this, need to add the SVG extraction procedure to the style creation dialogs in qgis and come up with saving SVG symbols in the sqlite table, maybe using import/export in the style manager.

**Additional context**
I can store vector layers in the geopackage database, styles for them in the layer_styles table, even a project. And it's all in one file, but if I use own SVG symbols and I want to share/distribute my project, there may be difficulties with styles portability.

**Comment by alexbruy** [comment]
This can be achieved by using embedding symbols

**Comment by dr1542** [comment]
>This can be achieved by using embedding symbols
Yes, sometimes. But what if I use data-driven svg symbols?
