### ISSUE TITLE
(Postgresql) view stored in project is not refreshed.

### ISSUE THREAD

**Issue by janhec** [qgis/QGIS#43534]
A (database) view that is altered will keep showing old information when a qgis project, using it, is reopened.
Re-connecting the database has no influence on this.
The (view) alteration in question is a change of table in the view from clause, referring, in my case, to altered geometries.
Loading the view into a blank qgis produces the updated geometry.
Removing and re-inserting the layer in the project also solves the problem.
Suggestion: reload views at project loading time and possibly at refresh (F5).
Admittedly I did not try F5, so I am not sure what would have happened when using it...

**How to Reproduce**
see above
**QGIS and OS versions**
Qgis 64 bit 3.18.3, postgresql 11.12 with postgis 3.12, windows 10 fully updated.

QGIS version
3.18.3-Zürich
QGIS code revision
735cc85be9
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
exportDBmapper; 
geocatbridge; 
joinmultiplelines; 
lizmap; 
OSMDownloader; 
pdokservicesplugin; 
pdok_locatieserver_locator_filter; 
pointsamplingtool; 
profiletool; 
qdraw; 
Qgis2threejs; 
qgis2web; 
qgiscloud; 
QuickOSM; 
quick_map_services; 
raster_tracer-master; 
RuimtelijkePlannen; 
shapetools; 
TlugProcessing; 
db_manager; 
processing

**Additional context**

**Comment by gioman** [comment]
>  The (view) alteration in question is a change of table in the view from clause, referring, in my case, to altered geometries.

@janhec can you post a precise example? I'm trying to replicate, but actually seeing a different thing so probably I'm not replicating the same scenario.

**Comment by janhec** [comment]
Hi,
Give me a little time, I will.
It looks now that the problem only happens when you have several geometry
columns and want to switch to another.
Other view changes seem to work straight away.
