### ISSUE TITLE
App crashes trying to use PyTorch in Ubuntu

### ISSUE THREAD

**Issue by pranay731** [qgis/QGIS#43537]
When trying to import PyTorch in PyQGIS, import works fine, but any other call (torch.device or torch .tensor) crashes the application. The error on terminal: "munmap_chunk(): invalid pointer \n Aborted (core dumped)".
Issue is persistent with Ubuntu 18.04 and 20.04 (Tried QGIS 3.16, 3.12), but works fine with Windows 10 (QGIS 3.16).

**Comment by lbartoletti** [comment]
It's not related to pyqgis but tensor dependencies on Ubuntu ( cc @delhomer )

**Comment by pranay731** [comment]
@lbartolettiI completely do agree with you. But when making the same call from the terminal, there isn't any issues regarding. Only when import is done in a pyqgis interpreter (with all pyqgis modules imported and variables setup), the crash occurs.
I am trying to figure out why. It fails when trying to import the _C module of torch which is build up of cython pyi files compiled to .so library.
Any help would be appreciated.
Thanks.
