### ISSUE TITLE
QGIS hangs when typing a raster protocol url

### ISSUE THREAD

**Issue by gubuntu** [qgis/QGIS#43541]
**Describe the bug**
Start typing a url as an IP address to load a raster via protocol (in my case a COG) and QGIS hangs at some point while typing.

**How to Reproduce**

as above

**QGIS and OS versions**

3.18.2 on Mac

3.16 does not have this issue on mac or Linux.

**Comment by gioman** [comment]
>  Start typing a url as an IP address to load a raster via protocol (in my case a COG) and QGIS hangs at some point while typing.

@gubuntu can you post a sample URL?
