### ISSUE TITLE
impossible to check with a small screen. (start monitoring )

### ISSUE THREAD

**Issue by RAFALCO** [qgis/QGIS#43540]
With a small screen (5" samsung sm g390f) it is not possible to check or uncheck "digitize vertex only when both conditions are met" in tracking parameters ". the text is off screen 

there is no problem on a larger screen. (8" activ tab 3) 
default on qfield 1.9.5 and 1.9.6

**Comment by fiddlersfan** [comment]
As you write yourself this issue concerns Qfield and not QGIS. Please close the issue here and open it here:
https://github.com/opengisch/QField/issues
