### ISSUE TITLE
<geographicflag> changes on every save

### ISSUE THREAD

**Issue by faebebin** [qgis/QGIS#43556]
Using `Trackable QGIS Project` the `<geographicflag>` tag switches every time saving the project from `true `to `false` .

**Comment by gioman** [comment]
@faebebin use this template to report issues, thanks!

https://github.com/qgis/QGIS/issues/new?assignees=&labels=Bug&template=10_bug_report.md&title=

**Comment by m-kuhn** [comment]
thanks for reporting this this is not caused by the plugin

**Comment by gioman** [comment]
At least the title should be changed then ;)

**Comment by m-kuhn** [comment]
Good point, done ;-)

**Comment by m-kuhn** [comment]
@faebebin which qgis version?

**Comment by faebebin** [comment]
➜  ~ qgis --version
QGIS 3.16.7-Hannover 'Hannover' (0471743889)
