### ISSUE TITLE
Atlas exporting to PDF sometimes duplicates first page

### ISSUE THREAD

**Issue by Mario-F-F** [qgis/QGIS#43569]
**Bug Description**

When exporting Atlas to PDF, sometimes, the first page is duplicated

**How to Reproduce**
I have created a demo project: https://github.com/Mario-F-F/data/blob/master/atlas_failure_demo_project_%26_dataset/atlas_fail.gpkg

The project is created to reproduce atlas problem, when, sometimes, duplicates first page. 

1. In canvas, using theme "BASE", select any three lines. 
2. Open "A3_ATLAS (selection) [with basemap]" composer.
3. Generate Atlas PDF (Export Atlas as PDF...). 

Expected result:  PDF with a page for each line selected. 
Result obtained: Most of the times, when Atlas PDF is created, the first page is duplicated. PDF export sample (pages 1 & 2 are the same): https://github.com/Mario-F-F/data/blob/master/atlas_failure_demo_project_%26_dataset/A3_ATLAS%20(selection)%20%5Bwith%20basemap%5D_fail_demo01.pdf

The problem has not been reproduced with "A3_ATLAS (selection)" composer
The problem has not been reproduced with "A3_ATLAS (selection) [with basemap]" when exported to images. Once the atlas has been exported to images, when later exporting to PDF, the problem does not appear

Additional problem: Layer "atlas_fail", style "Atlas". 

Opacity of the symbol is controlled by selection. If line is selected, line is 80% opaque (should be shown). Lines not selected are transparent (opacity = 0).
Line symbol opacity is correct, but start (green) and end (red)  points, generated by "geometry generator", does not get opacity 0  (they are shown) when the line is not selected

**QGIS and OS versions**

<meta http-equiv="Content-Type" content="text/html; charset=utf-8"><style type="text/css">
p, li { white-space: pre-wrap; }
</style> 

Versión de QGIS | 3.18.3-Zürich | Revisión del código de QGIS | 735cc85be9
-- | -- | -- | --
Compilado contra Qt | 5.15.2 | Ejecutándose contra Qt | 5.15.2
Compilado contra GDAL/OGR | 3.3.0 | Ejecutándose contra GDAL/OGR | 3.3.0
Compilado contra GEOS | 3.9.1-CAPI-1.14.2 | Ejecutándose contra GEOS | 3.9.1-CAPI-1.14.2
Compiled against SQLite | 3.35.2 | Running against SQLite | 3.35.2
Compiled against PDAL | 2.2.0 | Running against PDAL | 2.3.0 (git-version: eac774)
Versión del cliente PostgreSQL | 13.0 | Versión de SpatiaLite | 5.0.1
Versión de QWT | 6.1.3 | Versión de QScintilla2 | 2.11.5
Compilado contra PROJ | 8.0.1 | Ejecutándose contra PROJ | Rel. 8.0.1, March 5th, 2021
Versión del SO | Windows 10 Version 2004
Active python plugins | DigitizingTools; GroupStats; mmqgis; processing_r; profiletool; shapetools; SpreadsheetLayers; valuetool; ViewshedAnalysis; db_manager; processing

**Additional context**

N/A

**Comment by alexbruy** [comment]
Can't reproduce with the latest master (5566e42635). Is this still an issue?
