### ISSUE TITLE
Wrong error output location when using Check validity on data with certain type of 3D error

### ISSUE THREAD

**Issue by chau-intl** [qgis/QGIS#43582]
This issue is regarding the location of errors when using the `Vector->Geometry Tools->Check validity...` when having a polygon with different elevation in the start and the end point.

1. Add a feature to a vector layer containing the following geometry (I use the QuickWKT plugin):

    POLYGON((1 1 0, 1 2 1, 2 2 2, 2 1 3, 1 1 4)) 
_Note that this is not a closed ring but rather a spiral._

2. Run the `Vector->Geometry Tools->Check validity` tool.
3. Select the layer containing the geometry and use `QGIS` as the method.
4. Run the tool using the default layer names.
5. Check the layer `Error output` which contains the locations of each error.
6. Even though the error is at coordinate (1,1) the reported location is at (0,0).

![screenshot](https://user-images.githubusercontent.com/6311686/120989919-5625ef00-c780-11eb-9cfe-f6a132fa8b0c.JPG)

I use QGIS 3.18.3 on windows 10 x64.

**Comment by nicogodet** [comment]
It seems that Qgis method does not support 3D input ([source code](https://qgis.org/api/qgsgeometryvalidator_8cpp_source.html#l00389)).

Try GEOS just in case.

**Comment by chau-intl** [comment]
Strange because the error message provided with the feature in the `Error output` seems okay:

`ring 0 not closed`

The `GEOS` method on the other hand doesn't report any errors on the geometry. So I think the `QGIS` method works but just report the wrong location.

**Comment by nicogodet** [comment]
```python
>>> geom = QgsGeometry().fromWkt('POLYGON((1 1 0, 1 2 1, 2 2 2, 2 1 3, 1 1 4))')
>>> geom.validateGeometry(QgsGeometry.ValidatorQgisInternal, QgsGeometry.ValidityFlags())
[<QgsGeometry.Error: L'anneau 0 n'est pas fermé>]
>>> errors = geom.validateGeometry(QgsGeometry.ValidatorQgisInternal, QgsGeometry.ValidityFlags())
>>> errors[0].where()
<QgsPointXY: POINT EMPTY>
```

The position of the error is not provided here : https://qgis.org/api/qgsgeometryvalidator_8cpp_source.html#l00104

**Comment by chau-intl** [comment]
That looks indeed like the issue and I guess a rather simple one to fix. The first point in the line should be the location and I think it is relevant to know where exactly that error is located, since the geometry involved could be large and complex.

**Comment by lbartoletti** [comment]
@chau-intl Start and End Point should be returned. BTW, if the difference is only on the Z it should be indicated. I'm working on a fix.

**Comment by lbartoletti** [comment]
> @chau-intl Start and End Point should be returned. BTW, if the difference is only on the Z it should be indicated. I'm working on a fix.

Well... I forgot that it was a QgsPointXY that was returned by QgsGeometry::Error.
