### ISSUE TITLE
Data Override image source in print composer not working with expressions

### ISSUE THREAD

**Issue by walking-the-talk** [qgis/QGIS#43589]
**Describe the bug**
I am trying to create a print layout that includes images referenced from a field within the active layer within the atlas. Data override using an expression (I have set a variable for the path to the images).

I have used this method lots of times in previous versions of QGIS and I think this matches the guidance in the docs.  I have also just loaded an old project (created in 3.8 I think) and this does not work when printing a report with this feature in 3.18.2. The problem occurs when trying to print/export a report or a print layout.

I hope I've just done something dumb...

**How to Reproduce**

Create a print layout and generate an atlas (the layer includes a field that references one or more images)

Add an image

set a data override for the image source with an expression including a field from the layer, for example:

    concat(@images,'/',"Sections_P1") 

[where @images is the variable for the path to the image and Sections_P1 is the field with the name of the image]

This evaluates to a correct expression (see preview in the screengrab) but when I try to export the layout I get an error - "The source for picture “<Picture>” could not be loaded or is corrupt:"

Just to check, I added a second image, set the data override as the result of the expression in the first image (copied and pasted the text from 'Preview'!) and this image displays as expected - lower left image in screengrab. It also works if I manually select the file (i.e. deactivate the override).

I note that the Item Properties show the second image displayed as 'Raster' but the first image as 'SVG', which is probably indicating that the expression is not functioning?

 ![QGIS_print_composer](https://user-images.githubusercontent.com/19671610/121024839-82e7ff80-c79c-11eb-992c-1a46ad6495ab.jpg)

**QGIS and OS versions**
QGIS 3.18.2, Windows 10

**Comment by nicogodet** [comment]
duplicate https://github.com/qgis/QGIS/issues/42280 ?

**Comment by walking-the-talk** [comment]
Looks like it - I searched for issues similar but didn't find anything that was open... Didn't think to look for closed issues. My apologies.
