### ISSUE TITLE
No module named gdal

### ISSUE THREAD

**Issue by beggers359** [qgis/QGIS#43596]
QGIS was working just fine until I installed the latest version. Now QGIS plugins needing GDAL are broken. Tried total QGIS uninstall and registry scrubbing, and modifying the QGIS path settings. Can't seem to figure it out. Any ideas? Error shown below.

Couldn't load plugin 'cwsi' due to an error when calling its classFactory() method

ModuleNotFoundError: No module named 'gdal'
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS31~1.3/apps/qgis/./python\qgis\utils.py", line 335, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/beggers/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cwsi\__init__.py", line 35, in classFactory
    from .cwsi import CWSI
  File "C:\PROGRA~1/QGIS31~1.3/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/beggers/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cwsi\cwsi.py", line 43, in
    import gdal
  File "C:\PROGRA~1/QGIS31~1.3/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'gdal'

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
QGIS version: 3.18.3-Zürich Zürich, 735cc85be9

Python Path:
C:/PROGRA~1/QGIS31~1.3/apps/qgis/./python

C:/Users/beggers/AppData/Roaming/QGIS/QGIS3\profiles\default/python

C:/Users/beggers/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins

C:/PROGRA~1/QGIS31~1.3/apps/qgis/./python/plugins

C:\Program Files\QGIS 3.18.3\binC:\Program Files (x86)\ArcGIS\bin

C:\Program Files\QGIS 3.18.3\bin\python39.zip

C:\PROGRA~1\QGIS31~1.3\apps\Python39\DLLs

C:\PROGRA~1\QGIS31~1.3\apps\Python39\lib

C:\Program Files\QGIS 3.18.3\bin

C:\PROGRA~1\QGIS31~1.3\apps\Python39

C:\PROGRA~1\QGIS31~1.3\apps\Python39\lib\site-packages

C:\PROGRA~1\QGIS31~1.3\apps\Python39\lib\site-packages\win32

C:\PROGRA~1\QGIS31~1.3\apps\Python39\lib\site-packages\win32\lib

C:\PROGRA~1\QGIS31~1.3\apps\Python39\lib\site-packages\Pythonwin

C:/Users/beggers/AppData/Roaming/QGIS/QGIS3\profiles\default/python

**Comment by gioman** [comment]
@beggers359 not a general QGIS issue, try with a new QGIS profile.

**Comment by Gustry** [comment]
@beggers359 It's a problem with the plugin "cwsi". You should report the issue in their plugin code repository.
https://gdal.org/api/python.html#imports
It seems 3.18.3 is using GDAL > 3.1

`import gdal` => `from osgeo import gdal`

I think we can close.

**Comment by beggers359** [comment]
Happens with any plug-in that needs it, not just CWSI. QWaterModel also comes to mind. Same error. I can show others too.

**Comment by nyalldawson** [comment]
> Happens with any plug-in that needs it, not just CWSI. QWaterModel also comes to mind. Same error. I can show others too.

You need to report this to all the affected plugins. It's a bug in the plugin, not QGIS. The old `import gdal` method has been deprecated for years and years, they've had enough time to reasonably adapt to this.

**Comment by beggers359** [comment]
10-4. Thanks for the input.
