### ISSUE TITLE
Raster calculator: Error occured while performing the calculation 

### ISSUE THREAD

**Issue by Papafritzl** [qgis/QGIS#43592]
**Describe the bug**
I'm trying to combine raster analysis results of 3 different rasters i've created. the expression inserted is  **(aspect_north@1 = 1 AND slope_lte5@1 = 1 ) OR slope_lte2@1 = 1** and I have my reference layer set as well as the output. I then run the expression and get the following LOG (in dutch) 
_Algoritme 'Raster calculator' starten...
Parameters invoer:
{ 'CELLSIZE' : 0, 'CRS' : None, 'EXPRESSION' : '( aspect_north@1 = 1 AND slope_lte5@1 = 1 ) OR slope_lte2@1 = 1', 'EXTENT' : None, 'LAYERS' : ['C:/Users/Gebruiker/Desktop/GIs/exercise_data/raster analyse/Aspect_north.tif'], 'OUTPUT' : 'C:/Users/Gebruiker/Desktop/GIs/exercise_data/raster analyse/all_conditions.tif' }

An error occurred while performing the calculation
Uitvoering mislukt na 0.04 seconden

Resultaatlagen laden
Algoritme 'Raster calculator' voltooid_

 The goal of the analysis is to find which places on the raster are suitable to build houses. The 3 different rasters used are 1 where I determined north facing slopes, 1 where I determined which places have a slope lesser then or equal to 2° and in the last 1 I determined slopes lesser then or equal to 5°. 

**How to Reproduce**

I'm just starting out with QGIS so i'm encountering this problem while following the [trainingguide](https://docs.qgis.org/3.16/en/docs/training_manual/rasters/terrain_analysis.html) starting from 7.3 lesson: terrain analysis. The used data set can be found in QGIS-Training-Data-release_3.16 in the raster map. Starting out with the SRTM_41_19.tif file
1. I first build the Hillshade raster, the aspect raster, slope raster then the aspect_north, slope_intl2 ad slope_intl5 rasters accordingly.
2. I open raster calculater from the raster analyse toolbar
3. I insert the expression **(aspect_north@1 = 1 AND slope_lte5@1 = 1 ) OR slope_lte2@1 = 1**
4. As reference layer I input "aspect_north"
5. I then give the output "all_conditions" and route it to the map I want it saved and run the calculator.
6. Then the error occurs.

**QGIS and OS versions**

QGIS versie: 3.18.3-Zürich
OS: Windows 10

**Additional context**

I followed absolutely the same steps 3 days ago and it worked fine.

**Comment by gioman** [comment]
Works fine here (3.18.3 on Win 10) using the same steps and data.
