### ISSUE TITLE
Documentation enhancement on QgsPointXY vs QgsPoint

### ISSUE THREAD

**Issue by antoniolocandro** [qgis/QGIS#43598]
For some functions it is not clear when to use QgsPointXy vs QgsPoint, I read the QgsPoint is the preferred method so I suggest either stating when one is to be used over the other and even deprecation of QgsPointXY although I have been told QgsPointXY is very lightweight

![image](https://user-images.githubusercontent.com/4627073/121085544-3d790180-c79f-11eb-9f09-76770797820e.png)

Added here as per this thread, https://twitter.com/antoniolocandro/status/1400627534698582018 sorry if this is not the correct place for documentation issues but I wasn't sure if this qualifies as code change also

**Comment by kannes** [comment]
It's never too late to say thanks and since I only just noticed the improved documentation on this: Thanks! This was a really good request and addition. :)
