### ISSUE TITLE
Error reading database file from /usr/share/qgis/resources/srs.db

### ISSUE THREAD

**Issue by aloboa** [qgis/QGIS#43593]
After installing qgis (3.18.3) on Pop!_OS (based on ubuntu 20.04) with
    `sudo apt install qgis qgis-plugin-grass`
I run qgis and at trying to visualize OSM I get:

No transform available between EPSG:4326 and EPSG:3857
and
"resource location error"  
Error reading database file from: /usr/share/qgis/resources/srs.db  
Because of this the projection selector will not work...

and most often qgis has to be crashed by Force Quit

I do have srs.db in that directory with -rw-r--r-- permissions.  
Nothing else has been done with QGIS, this error occurs just after installation.

qgis info: https://www.dropbox.com/s/hecthalhvqh9f2j/Screenshot%20from%202021-06-07%2018-34-45.png?dl=0

**Comment by gioman** [comment]
@aloboa for what is worth: no issues under Ubuntu/Kubuntu 20.04 (and Mint too).

**Comment by aloboa** [comment]
This issue has vanished after upgrading to Pop!_OS 20.1 (based on ubuntu 20.1) and reinstalling qgis.
Do not understand why.
