### ISSUE TITLE
INVALID Cannot use multiple creation options in batch interface for gdal processing algorithms

### ISSUE THREAD

**Issue by AlisterH** [qgis/QGIS#43603]
When running gdal algorithms "as single process" it is possible to specify multiple creation options.
But when running them as a batch it does not seem to be possible.  It should be possible, just by separating them with a space.  QGIS should split them up and add them to the command by putting -co before each option.  But it does not work, at least in recent QGIS versions.

This is from the output of an attempt to run the roughness algorithm with some creation options:
```
Processing algorithm 1/1…
Algorithm Roughness starting…
Input parameters:
{'BAND': 1,
'COMPUTE_EDGES': False,
'INPUT': '92L2P_92KY3_937023e8_e210_424a_9de6_30d03f955da9',
'OPTIONS': 'NUM_THREADS=ALL_CPUS TFW=YES TILED=YES',
'OUTPUT': <QgsProcessingOutputLayerDefinition {'sink':TEMPORARY_OUTPUT, 'createOptions': {}}>}

GDAL command:
gdaldem roughness C:/Processing/lds-auckland-lidar-1m-dem-2013-GTiff_0/92L2P-92KY3.tif C:/Users/alistair/AppData/Local/Temp/processing_HhQozD/b82f34283a44400a8e73b58689a56ac2/OUTPUT.tif -of GTiff -b 1 -co "NUM_THREADS=ALL_CPUS TFW=YES TILED=YES"
GDAL command output:
Process completed successfully
Warning 1: Invalid value for NUM_THREADS: ALL_CPUS TFW=YES TILED=YES
```

Instead of adding each creation option to the command, QGIS 3.18.3 has put them all inside one set of quotes, trying to use them as a single creation option.

**Comment by nicogodet** [comment]
When running as single process creation options are "|" separated, formated by the widget.
```python
@staticmethod
def parseCreationOptions(value):
    parts = value.split('|')
    options = []
    for p in parts:
        options.extend(['-co', p])
    return options
```

Try to set as creation options -> `NUM_THREADS=ALL_CPUS|TFW=YES|TILED=YES`

**Comment by AlisterH** [comment]
Ah, sorry, of course.  I should have looked harder to see if I could find that out.
Thanks.
