### ISSUE TITLE
Overlay_* fail to evaluate value if attribute name contains '-'

### ISSUE THREAD

**Issue by nicogodet** [qgis/QGIS#43616]
**Describe the bug**

Overlays_* functions returns `NULL` when we pass an attribute name that contains `-`.

example : 
`overlay_nearest('layer_id', z-tn)` returns `[NULL]`
Same layer, same feature but attribute name is `z_tn` instead of `z-tn` returns the expected value.

![image](https://user-images.githubusercontent.com/39594821/121142227-1290bb00-c83c-11eb-804f-a7c848b3cd58.png)
![image](https://user-images.githubusercontent.com/39594821/121142335-2cca9900-c83c-11eb-843f-91d99fc350aa.png)
![image](https://user-images.githubusercontent.com/39594821/121142378-35bb6a80-c83c-11eb-9063-27c831c7313c.png)
![image](https://user-images.githubusercontent.com/39594821/121142413-3d7b0f00-c83c-11eb-92b4-7c18e693641f.png)

**QGIS and OS versions**
QGIS 3.18.3 OsGeo4W testing

**Additional context**

BTW, the attribute name should be quoted like in `attribute()` or `get_feature()` ?

**Comment by DelazJ** [comment]
> BTW, the attribute name should be quoted like in attribute() or get_feature() ?

No, it's more like in aggregate functions, so no quotes or double. I'll let the devs explain why 😄

**Comment by uclaros** [comment]
`z-tn` is actually evaluated as `z - tn` since spaces are not required around arithmetic operators.
So your first result is *Null* because there is no `tn` field.
You can enclose field names in double quotes to get the result you want, ie. `overlay_nearest('layer_id', "z-tn")`

**Comment by DelazJ** [comment]
That means that whenever there's "-" in a field used in an expression, the field **MUST** be quoted to avoid unexpected results? Never paid attention to this but I usually prefer '_'.

**Comment by uclaros** [comment]
Same goes for other operators too like `+`,`\`,`/`,`*`,`%` etc, though `-` is probably more common in a field name.

**Comment by nicogodet** [comment]
I usually use "_" it was a typo when I used "-" and too lazy to change...

Thanks for explanations !
