### ISSUE TITLE
Upslope area not working

### ISSUE THREAD

**Issue by ashish195320016** [qgis/QGIS#43613]
I am using 3.18 and used 3.16 and 3.12 before. while i am delineating basins, i am not able to extract the upslope area. it shows that this layers is not corrected generated. then it gives a path to C: drive. i tried it so many times. please help. I dont know what to do.

**Comment by gioman** [comment]
> dont know what to do.

@ashish195320016 file a report the correct way:

https://github.com/qgis/QGIS/issues/new?assignees=&labels=Bug&template=10_bug_report.md&title=

adding all the requested infos (this includes attaching/linking sample data)
