### ISSUE TITLE
Unable to write temporary qgs file

### ISSUE THREAD

**Issue by tschmetzer** [qgis/QGIS#43622]
QGIS is unable to write the project file. This seems to be the case when trying to save after having classified a larger number of values in a layer.

Steps to reproduce:
1. Create new project
2. Add "Pop_sunbelt_minibereich.shp" into the layers from [Pop_sunbelt_minibereich.zip](https://github.com/qgis/QGIS/files/6617204/Pop_sunbelt_minibereich.zip)
3. Select the layer
4. Hit the save project button (should work)
5. Layer styling -> Categorized -> Value:Population -> Classify (Warning: 4334 classes will be built -> Hit "OK")
6. Hit the save project button -> Error message "Unable to write temporary qgs file" should be thrown

![grafik](https://user-images.githubusercontent.com/67278094/121199441-37eceb80-c873-11eb-9730-76924fa1ba95.png)

Probably the better and proper way to go is to use the "graduated" categorization. The interesting thing though is though that with the graduated categorization the user can also choose to have more than 4500 classes and save it anyways. Why is this not possible with a fixed categorization?

The worst thing is that this caused a *corrupted project file* (QGIS shows a completely empty project when loading it
[Schnittmenge.zip](https://github.com/qgis/QGIS/files/6617457/Schnittmenge.zip)) which I was unable to recover as of yet. I haven't tried to reproduce this as I regard it as a consequence to this bug.

Personal comment:
As there is a workaround the bug could be neglected. Yet it needs to be assured that the project file doesn't get corrupted.
Maybe the warning message could suggest something like `High number of classes. Classification would yield XXXX entries which might not be expected. Maybe the "Graduated classification" could be of more value.`

![grafik](https://user-images.githubusercontent.com/67278094/121203906-c44cdd80-c876-11eb-9d65-6b22418fda30.png)

The behaviour was observed with the following version :

QGIS version | 3.18.3-Zürich | QGIS code revision | 735cc85
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0) | &nbsp; | &nbsp;
Active python plugins | FreehandRasterGeoreferencer; GroupStats; nominatim; QuickOSM; db_manager; MetaSearch; processing | &nbsp; | &nbsp;

**Comment by gioman** [comment]
> Add "Pop_sunbelt_minibereich.shp" into the layers from [Pop_sunbelt_minibereich.zip](https://github.com/qgis/QGIS/files/6617204/Pop_sunbelt_minibereich.zip)

@tschmetzer there is only the .shp in here, the .shx, .dbf and .proj are needed too.

**Comment by tschmetzer** [comment]
> 
> 
> > Add "Pop_sunbelt_minibereich.shp" into the layers from [Pop_sunbelt_minibereich.zip](https://github.com/qgis/QGIS/files/6617204/Pop_sunbelt_minibereich.zip)
> 
> @tschmetzer there is only the .shp in here, the .shx, .dbf and .proj are needed too.

I don't understand why they are required to produce the bug as I was able to reproduce it with only the .shp file but here they are all collected in one file:

[Pop_sunbelt_minibereich.zip](https://github.com/qgis/QGIS/files/6619330/Pop_sunbelt_minibereich.zip)

**Comment by gioman** [comment]
> I was able to reproduce it with only the .shp

@tschmetzer a shapefile with only the .shp is corrupted, not possible to open it.

**Comment by gioman** [comment]
> Thanks for the reproduction and confirmation so far!

@tschmetzer sorry, can't confirm on both Linux and Windows :)

**Comment by tschmetzer** [comment]
Is there any further feedback required from my part? I already uploaded the new file. Were you able to reproduce it on any system :)

**Comment by gioman** [comment]
> Is there any further feedback required from my part? I already uploaded the new file. Were you able to reproduce it on any system

@tschmetzer no, I wasn't




> Is there any further feedback required from my part

Have you tried on a different machine?
