### ISSUE TITLE
macOS builds are not up to date

### ISSUE THREAD

**Issue by multiquadric** [qgis/QGIS#43623]
**Describe the bug**

macOS builds for both current versions and long-term are not being updated. builds are failing.
The last complete PR version is 3.18.1
The last complete LTR version is 3.16.5

The download page obfuscates the problem. Mac users may not see the problem.

**How to Reproduce**

This page:
https://qgis.org/en/site/forusers/download.html
has links to DMG files that do not have matching checksums.
The log files for the builds indicate problems.

**QGIS and OS versions**

n/a

**Additional context**

**Comment by agiudiceandrea** [comment]
@multiquadric are your sure the latest available PR version for macOS is QGIS 3.18.1?
It seem to me it's QGIS 3.18.3 (https://qgis.org/downloads/macos/qgis-macos-pr.dmg -> https://qgis.org/downloads/macos/pr/qgis_pr_final-3_18_3_20210608_104042.dmg) and it has a matching sha256 (https://qgis.org/downloads/macos/qgis-macos-pr.sha256sum -> https://qgis.org/downloads/macos/pr/qgis_pr_final-3_18_3_20210608_104042.dmg.sha256sum) `b8b2fc7496716d87886f86762b9a0ebd5e3afef68e029d53338a406f83b1f895`

**Comment by multiquadric** [comment]
@gioman I see that the PR version had a successful build after I posted this Build/Install issue. Good news!
I looked here for the PR versions
https://qgis.org/downloads/macos/pr/?C=M;O=D
and for the LTR versions, I chased down the builds to
https://qgis.org/downloads/macos/ltr/?C=M;O=D
The LTR version build stumbles at the final stages of bundling things up.

**Comment by agiudiceandrea** [comment]
I think @PeterPetrik is already looking at this.

**Comment by agiudiceandrea** [comment]
@multiquadric it seems that now both QGIS PR 3.18.3 and QGIS LTR 3.16.7 builds for macOS are OK.

**Comment by PeterPetrik** [comment]
all is not working

**Comment by multiquadric** [comment]
> all is not working

All is now working! Thanks
