### ISSUE TITLE
Colour Change bug

### ISSUE THREAD

**Issue by mcdgeo** [qgis/QGIS#43630]
## User Feedback

Trying to recolour some vector areas and QGIS crashed

## Report Details

**Crash ID**: [723e9ea2ee69f3f5e18121a480828f8a5d3a89dc](https://github.com/qgis/QGIS/search?q=723e9ea2ee69f3f5e18121a480828f8a5d3a89dc&type=Issues)

**Stack Trace**
<pre>
QgsSymbolLegendNode::setSymbol :
QgisApp::layerTreeViewDoubleClicked :
QMetaObject::activate :
QAbstractItemView::doubleClicked :
QTreeView::mouseDoubleClickEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.18.0-Z�rich
QGIS code revision: bdef9fb328
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

**Comment by Gustry** [comment]
> QGIS Version: 3.18.0-Z�rich

Consider a `.0` version like having a few bugs. Update as possible and try again, 3.18.3.

**Comment by mcdgeo** [comment]
Thank you Étienne.
I’m very new at all this and not an IT wizard, just a geologist!
When I look for the download, 64Bit Desktop, it sends me the same .exe file as before and then does nothing.
What am I doing wrong?
Kind regards

Michael Conan-Davies

Mobile: +61 418 901 731
Email:   ***@***.******@***.***>

**Comment by Gustry** [comment]
> I’m very new at all this and not an IT wizard, just a geologist!

Sure no problem.
There is a release every month : https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule
So always nice to update when possible, especially when using a `.0` version.
Did you use https://qgis.org/fr/site/forusers/download.html ? What do you mean by "it does nothing" ?

**Comment by mcdgeo** [comment]
I’m on a laptop at home.
Current QGIS is closed – but still installed
I chose the OSGeo4W Net Release 64bit
Then selected the Express Desktop Install
It gets as far as the select package dialogue.  Maintained the default selections (QGIS, GDAL, GRASS, GIS,
Click next and it does nothing after that.

Any ideas?

Michael Conan-Davies

Mobile: +61 418 901 731
Email:   ***@***.******@***.***>

**Comment by gioman** [comment]
> I chose the OSGeo4W Net Release 64bit Then selected the Express Desktop Install

@mcdgeo use the standalone installer, is easier https://qgis.org/downloads/QGIS-OSGeo4W-3.18.3-1-Setup-x86_64.exe
