### ISSUE TITLE
Relations are lost when duplicating a layer

### ISSUE THREAD

**Issue by koenigherford** [qgis/QGIS#43637]
**Describe the bug**
QGIS offers the abilitity to duplicate layers (to use a copy of them with other symbology or labeling e.g). 

If a relation is set up with the source-layer as parent-layer in Project/Properties/Relations and you duplicate this layer "relations" to the new copy of the sourec-layer are not added by default or by question: They are lost in Project/Properties/Relations and Layer Properties/Attributes Form/Relations. They have to be set up manually again. Maybe it will be better to duplicate the relations too and assign them to the copy of the layer by default or by question to minimize errors and work.

In many times (for example if you work with virtual fields, which deal with this relations (relation_aggregate)) or when creating forms e.g., it will be important to keep the relations.

**How to Reproduce**
1) Set up a project with a relation as described before.
2) Right-mouse-button-click (context-menu) on parent-layer
3) duplicate layer
4) look into layer-properties: no relation available any more

**QGIS and OS versions**

<meta http-equiv="Content-Type" content="text/html; charset=utf-8"><style type="text/css">
p, li { white-space: pre-wrap; }
</style>

QGIS version | 3.16.5-Hannover | QGIS code revision | 58ba7c1ed6
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)

**Comment by andreasneumann** [comment]
Relations work on internal layer IDs so that the user can later on change the layer name. If you duplicate a layer, it will get  a new layer id and thus the relations won't work anymore.

I wouldn't say that this is a bug.

If you want this functionality I think you should label it as a "feature request".
