### ISSUE TITLE
Python Error After Updating QGIS

### ISSUE THREAD

**Issue by sgrocke** [qgis/QGIS#43631]
I updated my QGIS to the new LTR and have installed a Plug In called Geoscience. Now, when I open QGIS I get the attached error message. I re-downloaded Python 3.9 but I still get the error message and am unable to re-download the Geoscience plugin. Do you have any ideas of what might solve this problem?
![QGIS Error](https://user-images.githubusercontent.com/85599869/121290193-0b4cca00-c89b-11eb-8872-8787e62d7847.jpg)

**Comment by gioman** [comment]
@sgrocke if you remove the plugin the error is gone? if yes then you must report the problem to the plugins authors, not here.

**Comment by Gustry** [comment]
@gioman `qgis.utils` is a normal Python package provided by QGIS which should work IMHO. So I'm not sure why the plugin would messed up here.
Or the plugin change the python path ? I don't know.
