### ISSUE TITLE
Reprojection issues from EPSG:4326 to EPSG:2927

### ISSUE THREAD

**Issue by Oko21** [qgis/QGIS#43654]
Hi all.  This is my first posting.  I have taught myself to use QGIS over the past couple years, and I'm constantly learning.  I hope this inquiry isn't a waste of your time....!

Background:  The CRS I use for my local area in Washington State is EPSG:2927.  However, I collect GPS data in EPSG:4326.  When I use QGIS to reproject the 4326 data into 2927, the 2927 point is mapped by QGIS in exactly the same place as the original 4326 - no offset (datum shift) is evident.

In ArcGIS, I can reproject 4326 into 2927 (or vice-versa), and the points map with an offset (datum shift) evident.  It's about 4-5 feet.

If I load those same points into QGIS - the offset (datum shift) is also evident.  However, if I reproject 4326 into 2927 using QGIS, and then load those exported points into ArcGIS - no offset is evident in ArcGIS!

QGIS is an amazing product, and I acknowledge I am a "Noob."  This is the first time I've run into a wall I can't figure out myself.  That said, can someone help me troubleshoot this?  I've attached a ZIP file containing a GPKG with the shapefiles I created in both ArcMap and QGIS while trying to figure out the problem.

My troubleshooting attempt:  Survey Monument FS3909 is located in Selah, Washington and it's CRS is NAD83 (HARN).  QGIS loads it under EPSG:4152.  I've attached the official data sheet for the monument that shows its projection data.  I shot the monument 3X in EPSG:4326 using a Juniper Systems Geode GNSS receiver, paired, via Bluetooth, with Mapit Spatial running on an Android mobile phone.  I then reprojected the official GPS point for the monument (EPSG:4152) and GPS data I shot of the monument (EPSG:4326) into EPSG:2927 or EPSG:4326 using both ArcGIS and QGIS.  Only reprojection with ArcGIS resulted in the expected datum shift.

I hope this explanation is clear enough for experts like you who run into this stuff often.  I look forward to getting schooled by you.  ;)  Cheers.
[Monument FS3909.zip](https://github.com/qgis/QGIS/files/6626489/Monument.FS3909.zip)

**Comment by Oko21** [comment]
I forgot to mention that the GPKG is a project saved to GPKG, so it can be opened in QGIS via "Project --> Open From --> Geopackage.  Thanks.

**Comment by gioman** [comment]
@Oko21 this would probably has to be asked in the PROJ channels https://proj.org/community/channels.html

**Comment by Oko21** [comment]
Thank you, gioman.  I infer that the best option on that page would be the "Mailing List" communication channel.  I'll check it out.

**Comment by eshattow** [comment]
I am curious, does this remain a problem with recent releases of QGIS?
