### ISSUE TITLE
Deleting "all other values" breaks date based categorise symbology

### ISSUE THREAD

**Issue by nicogodet** [qgis/QGIS#43651]
**Describe the bug**

A video is better than a long story.
![Animation](https://user-images.githubusercontent.com/39594821/121387699-2e36b700-c94b-11eb-98b0-a9a2f072a3a8.gif)

If I convert the datetime attribute to string attribute, I can delete "all other values" without breaking symbology.

**How to Reproduce**

1. Create layer with datetime attribute
2. Create few features with different date
3. Create a categorised symbology based on the datetime attribute
4. Delete "all other values" or uncheck it

**QGIS and OS versions**
Tested on Master, 3.18.3, 3.16.7 OsGeo4W testing

**Additional context**
I can provided layer and style if needed of course.

**Comment by gioman** [comment]
>  I can provided layer and style if needed of course.

@nicogodet yes thanks.

**Comment by nicogodet** [comment]
[Diachronie.zip](https://github.com/qgis/QGIS/files/6630346/Diachronie.zip)

Just load this layer and uncheck "all other values" to reproduce.

**Comment by elpaso** [comment]
@rouault I've tracked this down to https://github.com/OSGeo/gdal/blob/master/gdal/ogr/ogrfeature.cpp#L2451, what happens here is that QGIS rule is set to use ISO-8601 date format `1978-08-02` and the subset string becomes something like `"date" IN ('1978-08-02', '....`

But when evaluating the expression, OGR converts the timestamp to a string which becomes `1978/08/02` and they don't match.

I'm unsure about what to do here: from one perspective I feel that GDAL shouldn't format timestamps using slashes but maybe there is a good reason for that, on the other hand I could try to fix this in QGIS adding some parsing logic to `QgsOgrProviderUtils::setSubsetString` that would check the field definition and replace date literal `-` with `/`.

Do you have recommendation?

**Comment by rouault** [comment]
The serialization of OFTDate fields as YYYY/MM/DD is a historical behavior and cannot be changed lightly.

I don't have enough background on that issue to provide recommendations. Is the issue that QGIS does OGR_F_SetAttributeFilter("my_date_field = 'YYYY-MM-DD'") and that doesn't work when evaluated by GDAL ? I'd say GDAL could likely be enhanced to be tolerant to that. But on a quick try this seems to work already:

```
$ cat test.csv
1,"2021/06/14"

$ cat test.csvt
Integer,Date

$ ogrinfo test.csv -where "field_2 = '2021-06-14'" -al -q

Layer name: test
OGRFeature(test):1
  field_1 (Integer) = 1
  field_2 (Date) = 2021/06/14
```

**Comment by elpaso** [comment]
> The serialization of OFTDate fields as YYYY/MM/DD is a historical behavior and cannot be changed lightly.
> 
> I don't have enough background on that issue to provide recommendations. Is the issue that QGIS does OGR_F_SetAttributeFilter("my_date_field = 'YYYY-MM-DD'") and that doesn't work when evaluated by GDAL ? 

No, the filter set by QGIS is something like `"date" IN ('1978-08-02', '....`, this comes from the QGIS categorized renderer that scans all the rules and builds the `field IN (<list or rule values>)` that is set to the provider.

> I'd say GDAL could likely be enhanced to be tolerant to that. But on a quick try this seems to work already:
> 
> ```
> $ cat test.csv
> 1,"2021/06/14"

try this: `ogrinfo test.csv -where "field_2 IN ('2021-06-14')" -al -q`

**Comment by rouault** [comment]
> try this: `ogrinfo test.csv -where "field_2 IN ('2021-06-14')" -al -q`

ok, this indeed does not work. I guess you would have to tweak https://github.com/OSGeo/gdal/blob/a19328d8691a4c1f36a0b1169aed077f3055147c/gdal/ogr/swq_op_general.cpp#L628 to deal with SWQ_IN

**Comment by elpaso** [comment]
@rouault thanks, I'll fix it in GDAL if I can.

**Comment by elpaso** [comment]
Fixed upstream in GDAL
