### ISSUE TITLE
Crash: QGIS loading OpenDroneMap generated LAZ

### ISSUE THREAD

**Issue by Saijin-Naib** [qgis/QGIS#43655]
## User Feedback

Attempting to load an exported LAZ from OpenDroneMap. This data loaded fine in CloudCompare and LASview.

## Report Details

**Crash ID**: [86eb19b77ca1c48b3f0644a8cc6c0756e9485722](https://github.com/qgis/QGIS/search?q=86eb19b77ca1c48b3f0644a8cc6c0756e9485722&type=Issues)

**Stack Trace**
<pre>
pdal::LasReader::~LasReader :
_CallSettingFrameEncoded handlers.asm:183
__FrameHandler4::FrameUnwindToState frame.cpp:1093
__FrameHandler4::FrameUnwindToEmptyState risctrnsctrl.cpp:218
__InternalCxxFrameHandler<__FrameHandler4> frame.cpp:304
__CxxFrameHandler4 risctrnsctrl.cpp:290
providerGuiMetadataFactory :
RtlpExecuteHandlerForUnwind :
RtlUnwindEx :
__FrameHandler4::UnwindNestedFrames risctrnsctrl.cpp:662
CatchIt<__FrameHandler4> frame.cpp:1302
FindHandler<__FrameHandler4> frame.cpp:600
__InternalCxxFrameHandler<__FrameHandler4> frame.cpp:352
__CxxFrameHandler4 risctrnsctrl.cpp:290
RtlpExecuteHandlerForException :
RtlDispatchException :
RtlRaiseException :
RaiseException :
_CxxThrowException throw.cpp:75
providerGuiMetadataFactory :
providerGuiMetadataFactory :
QgsPointCloudLayer::setDataSource :
QgsPointCloudLayer::QgsPointCloudLayer :
QgsBrowserPropertiesDialog::QgsBrowserPropertiesDialog :
QgsBrowserPropertiesDialog::QgsBrowserPropertiesDialog :
QgsBrowserDockWidget::setPropertiesWidget :
QObject::qt_static_metacall :
QItemSelectionModel::emitSelectionChanged :
QItemSelectionModel::select :
QTreeViewPrivate::select :
QTreeView::setSelection :
QAbstractItemView::mousePressEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.18.3-Z�rich
QGIS code revision: 735cc85be9
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.0
Running against GDAL: 3.3.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.21390

**Problem Data**
[odm_georeferenced_model.zip](https://github.com/qgis/QGIS/files/6626707/odm_georeferenced_model.zip)

**Comment by Forna73** [comment]
Really!?
As I said "from my experience"....
I've always used the standalone installer for windows since Qgis 1.8...
Now I'm on windows 10, i7 4790K, 32Gb ram... so I'm understanding there always has been something wrong with my installation... as I said NEVER succeeded in exporting something more than 300dpi at least in 3.x... because I remember that with the old 2.18 I succeeded exporting a 600dpi, but only a couple of times...

**Comment by gioman** [comment]
> Really!?
> As I said "from my experience"....
> I've always used the standalone installer for windows since Qgis 1.8...
> Now I'm on windows 10, i7 4790K, 32Gb ram... so I'm understanding there always has been something wrong with my installation... as I said NEVER succeeded in exporting something more than 300dpi at least in 3.x... because I remember that with the old 2.18 I succeeded exporting a 600dpi, but only a couple of times...

@Forna73 you commented in the wrong ticket. The right one is https://github.com/qgis/QGIS/issues/43659

**Comment by wonder-sk** [comment]
hi @Saijin-Naib are you able to test with the current master to see if it still crashes? (It loads fine for me on master)

**Comment by Saijin-Naib** [comment]
> hi @Saijin-Naib are you able to test with the current master to see if it still crashes? (It loads fine for me on master)

Are there weekly master snapshots being made again of the OSGeo4W-NG builds with PDAL? If not, I think I'm not going to be able to repro for a while. Only other platform is Alpine Linux and that's using the stable Flatpak of QGIS.

**Comment by wonder-sk** [comment]
Not sure, but there seem to be new snapshots published every now and then - http://download.osgeo.org/osgeo4w/testing/x86_64/release/qgis/qgis-dev/ - I can see there a build from June 10

**Comment by Saijin-Naib** [comment]
Do you think this is recent enough to have the right PRs in it to test?
http://download.osgeo.org/osgeo4w/testing/x86_64/release/qgis/qgis-dev/qgis-dev-3.19.0-40-bb0dfb6ba-1.tar.bz2

I'll try presently.

**Comment by wonder-sk** [comment]
Yeah that should be recent enough...
