### ISSUE TITLE
Processing: Drape / qgis:setzfromraster inconsistent NODATA behaviour

### ISSUE THREAD

**Issue by jlayt** [qgis/QGIS#43650]
**Describe the bug**

The Drape / qgis:setzfromraster processing algorithm is inconsistent in applying the NODATA value when the INPUT geometry lies partly or  fully outside the raster bbox. If the geometry lies only partly inside the bbox, then any vertices outside the bbox have the NODATA value set. If the geometry lies fully outside the bbox then the original geometry is returned as-is and the NODATA value is not set on any vertices. We would expect the NODATA value to still be returned in this scenario.

**How to Reproduce**

1. Go to Processing toolbox and open the Drape command
2. Choose a raster and vector layer where the vectors lie fully and partially outside the raster bbox
3. Set NODATA value to something other than 0, say 1,000,000
4. Run the tool and check the resulting Z values.

**QGIS and OS versions**

<meta http-equiv="Content-Type" content="text/html; charset=utf-8"><style type="text/css">
p, li { white-space: pre-wrap; }
</style>

QGIS version | 3.16.7-Hannover | QGIS code revision | 0999a96c27
-- | -- | -- | --
Compiled against Qt | 5.14.2 | Running against Qt | 5.14.2
Compiled against GDAL/OGR | 3.2.1 | Running against GDAL/OGR | 3.2.1
Compiled against GEOS | 3.9.1-CAPI-1.14.2 | Running against GEOS | 3.9.1-CAPI-1.14.2
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.4
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | macOS 11.4
Active python plugins | numericalDigitize; VectorBender; LPGetLibraryInfo; pre_ex_plan; AnotherDXF2Shape; plaingeometryeditor; pluginbuilder3; MemoryLayerSaver; LPFigureBuilder; plugin_reloader; processing; db_manager; MetaSearch; LPMaps; ArkSpatial

**Additional context**

Note we are running this inside processing scripts using non-rectangular rasters where 0.0 is a valid value. The inconsistent results mean we have to perform extra checks. If the result was consistent we could just check for NODATA.

**Comment by jlayt** [comment]
It would also be incredibly useful if we could set the NODATA to None/Null instead of a number, but I suspect there's something deeply fundamental preventing that.

**Comment by alexbruy** [comment]
Seems fixed in master. Please re-test.
