### ISSUE TITLE
Large Map Export Crashes QGIS

### ISSUE THREAD

**Issue by Detritalgeo** [qgis/QGIS#43659]
## User Feedback

I have a plotter size map (44" by 60") in the layout view I was trying to export as an image (in 600 dpi). I tried png image and pdf but they crashed. "Always export as vectors" was selected. I was then able to get it to work by reducing the DPI to 300 and de-selecting "Always export as vectors"

## Report Details

**Crash ID**: [85d318133934e2d9bf22caecb0666ce5ba5d78ba](https://github.com/qgis/QGIS/search?q=85d318133934e2d9bf22caecb0666ce5ba5d78ba&type=Issues)

**Stack Trace**
<pre>
memcpy_repmovs memcpy.asm:114
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QRasterPaintEngine::rasterBuffer :
QRasterPaintEngine::rasterBuffer :
QRasterPaintEngine::fill :
QPaintEngineEx::draw :
QPaintEngineEx::drawPath :
QgsFillSymbolLayer::_renderPolygon qgssymbollayer.cpp:792
QgsSimpleFillSymbolLayer::renderPolygon qgsfillsymbollayer.cpp:342
QgsFillSymbol::renderPolygonUsingLayer qgssymbol.cpp:2322
QgsFillSymbol::renderPolygon qgssymbol.cpp:2277
QgsLayoutItemPage::draw qgslayoutitempage.cpp:286
QgsLayoutItem::paint qgslayoutitem.cpp:409
QGraphicsScene::dragMoveEvent :
QGraphicsItem::dragMoveEvent :
QGraphicsEffectSource::draw :
QgsLayoutEffect::draw qgslayouteffect.cpp:33
QGraphicsScene::drawItems :
QGraphicsScene::drawItems :
QGraphicsScene::render :
QgsLayoutExporter::renderRegion qgslayoutexporter.cpp:261
QgsLayoutExporter::renderRegionToImage qgslayoutexporter.cpp:300
QgsLayoutExporter::renderPageToImage qgslayoutexporter.cpp:207
QgsLayoutExporter::createImage qgslayoutexporter.cpp:1943
QgsLayoutExporter::exportToImage qgslayoutexporter.cpp:411
QgsLayoutDesignerDialog::exportToRaster qgslayoutdesignerdialog.cpp:2160
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1637
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.16.7-Hannover
QGIS code revision: 0471743889
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

**Comment by gioman** [comment]
@Detritalgeo how is memory consumption by the time it crashes?

**Comment by Forna73** [comment]
To my experience, whatever resolution bigger than 300 crash Qgis.... and this since version 2.xx...

**Comment by gioman** [comment]
> To my experience, whatever resolution bigger than 300 crash Qgis.... and this since version 2.xx...
> I always leave that 300dpi as default... and for .pdf I use external pdf virtual printer, cause I find the one in Qgis lower in image quality and bigger file size.

@Forna73 that's untrue, for example I'm able to export a A0 at 600/1200dpi with high resolution imagery in it without any issues.
