### ISSUE TITLE
not Processing plugin

### ISSUE THREAD

**Issue by jp-ch-v** [qgis/QGIS#43653]
hello,

I have downloaded QGIS 3.16.7- Hannover for Mac, unfortunately the "Processing"  is not activated. I have tried to solve it by creating a new profile but I still don't get the option to activate "Processing".

Could someone help me?

**Comment by gioman** [comment]
> Could someone help me?

@jp-ch-v if you want to report an issue use the correct template adding all the requested infos: https://github.com/qgis/QGIS/issues/new?assignees=&labels=Bug&template=10_bug_report.md&title=

if you want to ask questions write in the users or developers mailing lists or gis.stackexchange.com

Yours do not seems a general issue, Processing works fine on macOS.

Do you see "Processing" listed among the installed plugins? Can you install 3rd party plugins with the plugin manager?
