### ISSUE TITLE
Crash when adding new pointcloud layer from .las

### ISSUE THREAD

**Issue by rkolka** [qgis/QGIS#43666]
**Describe the bug**

QGIS craches when adding new pointcloud layer from .las file. 

Some time ago (probably 3.18.2) it worked and the ept.json file that was created then is read still normally.

**How to Reproduce**

Add new pointcloud layer from .las
1. Go to Layer - Add new pointcloud layer -> select .las file as datasource
 
## Report Details

**Crash ID**: [89120eda83e1d457fe68d7024318dfb0e9b4dbdb](https://github.com/qgis/QGIS/search?q=89120eda83e1d457fe68d7024318dfb0e9b4dbdb&type=Issues)

**Stack Trace**
<pre>
memcpy memcpy.asm:632
QgsPointCloudLayer::setDataSource :
QgsPointCloudLayer::QgsPointCloudLayer :
QgisApp::addPointCloudLayerPrivate :
QgisApp::addPointCloudLayer :
QObject::qt_static_metacall :
QgsDataSourceManagerDialog::addPointCloudLayer :
QObject::qt_static_metacall :
QgsAbstractDataSourceWidget::addPointCloudLayer :
QgsSourceSelectProvider::ordering :
QObject::qt_static_metacall :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS and OS versions**

**QGIS Info**
QGIS Version: 3.18.3-Z�rich
QGIS code revision: 735cc85be9
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.0
Running against GDAL: 3.3.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

**Additional context**

**Comment by gioman** [comment]
@rkolka please attach/link the offending dataset.

**Comment by rkolka** [comment]
[1-1-0-0.zip](https://github.com/qgis/QGIS/files/6636975/1-1-0-0.zip)

**Comment by rkolka** [comment]
For smaller sample, I took one tile from ept-data. Opening 1-1-0-0.laz alone makes a crash. Opening entire ept dataset is normal.

**Comment by gioman** [comment]
> Opening 1-1-0-0.laz alone makes a crash

@rkolka no crash on QGIS master on Ubuntu 20.04

**Comment by rkolka** [comment]
Nightly does not crash on my machine either:
QGIS version 3.19.0-Master
QGIS code revision bb0dfb6ba
Qt version 5.15.2
Python version 3.9.5 
GDAL/OGR version 3.3.0
PROJ version 8.0.1
EPSG Registry database version v10.018 (2021-04-02)
GEOS version 3.9.1-CAPI-1.14.2
SQLite version 3.35.2
PDAL version 2.3.0
PostgreSQL client version 13.0
SpatiaLite version 5.0.1
QWT version 6.1.3
QScintilla2 version 2.11.5
OS version Windows 10 Version 2009

Active Python plugins
LAStools
minimum_spanning_tree
db_manager
MetaSearch
processing
