### ISSUE TITLE
Editing some data tables in GeoPackages doesn't work

### ISSUE THREAD

**Issue by thorsten-reitz** [qgis/QGIS#43664]
**Describe the bug**

The general issue is that when we try to edit some tables that come from a GeoPackage source, editing doesn't work properly. Only new rows can be added, but no values can be changed or rows deleted. Generally, tables with geometry are fine, and some tables with only non-spatial properties also work, but some from the same GeoPackage file do not. I've checked different editing workflows and potential file system/os permission issues but none of that lead me to success so far.

Any help would be very welcome.

NOTE: This issue occurs in a paid-for project. Some (financial) resources to fix it are available if the issue can be confirmed.

**How to Reproduce**

A sample dataset for this issue is available here: 
https://github.com/wetransform-os/geopackage-end/tree/main/DF4_8/MajorRoads

This (almost empty) GeoPackage has been created with https://github.com/halestudio/hale/

After storing the GeoPackage locally, follow these steps to reproduce the issue:

1. In the Browser, go to GeoPackage, and add the downloaded Geopackage as a new connection
2. Expand the GeoPackage connection to see the tables.
3. Double-click on DatasetDefaultProperties to add it to the current project as a  Layer
4. Toggle Edit Mode on that Layer
5. Open the attribute table
6. Try to edit any value or to delete a row

The geometry layers from the same GeoPackage can be edited, as well as some of the data tables.

**QGIS and OS versions**

This issue appears at least in QGIS 3.12, 3.16 and 3.18 on Windows 10, 64bit.

**Comment by uclaros** [comment]
Your table is not editable because it lacks a primary key:
``` sql
CREATE TABLE IF NOT EXISTS "DatasetDefaultProperties" (
  "id" INTEGER,
  "tableName" TEXT,
  "propertyName" TEXT,
  "attribute" TEXT,
  "defaultValue" TEXT
);
```

while your editable tables for comparison do not:
``` sql
CREATE TABLE IF NOT EXISTS "Voidables" (
  "beginLifespanVersion" DATETIME,
  "validFrom" DATETIME,
  "validTo" DATETIME,
  "PrimaryTable_id" INTEGER,
  "tableName" TEXT,
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT
);
```

**Comment by thorsten-reitz** [comment]
@uclaros Ouch, thank you very much for catching that one!

I had originally included a column called `fid` and declared that primary key. Then later I was asked to rename the column, but didn't update the primary key definition.

**Comment by uclaros** [comment]
@thorsten-reitz No problem!
Maybe this can turn into a feature request to allow editing geopackage tables with no PK? Or at least warn the user that a PK is missing?
