### ISSUE TITLE
QGIS doesn't start

### ISSUE THREAD

**Issue by flotschi2004** [qgis/QGIS#43674]
since a windows version update my QGIS does not properly start.  The blank programme window opens but then nothing more happens ; I even don't get an error message. The screen looks just like this:
![image](https://user-images.githubusercontent.com/72551323/121522374-55e25980-c9f5-11eb-874a-9b989c913f7e.png)

Does anybody have an idea what'S the issue?

**Comment by gioman** [comment]
@flotschi2004 write on the users or developers mailing lists for questions https://qgis.org/en/site/getinvolved/mailinglists.html
