### ISSUE TITLE
"Label precision" for raster styling not working when custom QML style is used

### ISSUE THREAD

**Issue by JanChytry** [qgis/QGIS#43670]
I loaded a GeoTiFF raster and loaded/set a custom QML style file for it from the style manager. This QML has set 6 decimal places the labelPrecision attribute. For the colorramp setup, see the tag below:
`<colorrampshader minimumValue="-999" clip="0" labelPrecision="6" classificationMode="2" maximumValue="9" colorRampType="DISCRETE">`

**Important:** The 6-decimal-places labels had been hardcoded in the QML file as well.

When I then attempt to change the "Label precision" option in "Layer Styling" to a different number (say 2) labels seem to change accordingly. When I change focus to another layer and back, labels are back at 6 decimal places. The desired 2-decimal "Label precision" settings does not obviously propagate to a legend in the Print Layout.

Not sure, which other scopes "Label precision" may not work in. Here, I attribute it to a custom QML file used.

Windows 10
QGIS v.3.18.2 with GRASS 
OSGeo4W installation

See attached GeoTIFF file and QML style file to reproduce: [data.zip](https://github.com/qgis/QGIS/files/6630601/data.zip)

**Comment by elpaso** [comment]
Cannot reproduce the issue on current master and 3.18: did you click on "Apply" before changing layer?

**Comment by JanChytry** [comment]
Okay now I feel stupid. Yes, clicking "Apply" works, nevertheless one may assume that having "Live Update" enabled does the thing instantly.

Closing this issue.
