### ISSUE TITLE
Localized decimal separator symbol not respected by layouts

### ISSUE THREAD

**Issue by AntonioPestana** [qgis/QGIS#43678]
I'm on QGIS 3.18.3 using the "Portuguese Portugal" (pt_PT) locale. For this locale the decimal separator is a comma. However, when creating a layout that includes a table having decimal fields, the decimal separator used by QGIS becomes a point.

The ZIP file attached has three very small files:

- "Points", a geopackage consisting of one points layer only, whose attribute table has decimal fields;
- "TableWithCommas", printscreen of the attribute table as displayed by the "Open Attribute Table" command (the decimal separator is a comma, as it should be);
- "LayoutWithoutCommas", printscreen of the Print Layout Window after adding the attribute table to the layout (the decimal separator is now a point).

[WrongLayout.zip](https://github.com/qgis/QGIS/files/6632542/WrongLayout.zip)

**QGIS and OS versions**

QGIS 3.18.3 code revision 735cc85be9
Windows 10 Pro v. 20H2

**Comment by gioman** [comment]
@AntonioPestana is your OS in pt_pt?

**Comment by AntonioPestana** [comment]
Yes, it is.

Giovanni Manghi ***@***.***> escreveu no dia quinta,
10/06/2021 à(s) 16:31:

**Comment by gioman** [comment]
Also preview in the field calculator shows always the dot instead of the comma.

**Comment by elpaso** [comment]
> Also preview in the field calculator shows always the dot instead of the comma.

file a ticket please
