### ISSUE TITLE
Wrong display of netcdf (3Di) 1D mesh

### ISSUE THREAD

**Issue by saberraz** [qgis/QGIS#43676]
I am trying to open this file:
https://github.com/lutraconsulting/MDAL/blob/master/tests/data/3di/1d_loon/results_3di.nc

My 1D mesh is connected to 0,0 point:
![image](https://user-images.githubusercontent.com/2649047/121540470-6945f280-c9fe-11eb-89e0-c3cc1e623702.png)
![image](https://user-images.githubusercontent.com/2649047/121540583-811d7680-c9fe-11eb-8028-0a698c47848e.png)

**Comment by PeterPetrik** [comment]
Looks like the data contains (0,0) point ...
