### ISSUE TITLE
Make layer properties window (and maybe others) modal

### ISSUE THREAD

**Issue by StyXman** [qgis/QGIS#43683]
**Feature description.**
I'm trying to come up with styles for a basemap with 3 layers:

* a height tinted base
* a slope shade modificator
* a hill shade modificator

It would be nice that I could have more than one layer properties window, so I can play with the 3 at the same time, and also enable/disable them to the effects of each layer. Currently I can have only one such window, and because it's modal, I can't even enable/disable the layer while it's open.

I haven't checked the code yet, but if the dialog has the right communication with the underlying model, it should be just a matter of removing the modal bit for the window.

**Comment by Gustry** [comment]
Have you tried the style panel ?

**Comment by StyXman** [comment]
/me puts a brown paper bag over his head.
