### ISSUE TITLE
PYQGIS documentation should have some sort of word wrap

### ISSUE THREAD

**Issue by antoniolocandro** [qgis/QGIS#43690]
When searching through PYQGIS you can notice that distance, distanceSquared, etc are like truncated. I know if I scroll further down I get the same data but in that case there wouldn't be a point of showing this information here also. I think it would benefit users to have a more user friendly interface

![image](https://user-images.githubusercontent.com/4627073/121622344-13d40a80-ca2b-11eb-9306-e7c387f4727e.png)

**Comment by gioman** [comment]
@antoniolocandro shouldn't this be filed under https://github.com/qgis/pyqgis ?

**Comment by DelazJ** [comment]
@antoniolocandro you mean that it's not possible to scroll to the right in the table?

The default readthedocs theme has (had?) an issue that table contents were not wrapped. There have been reports upstream and there's also a report in [pyqgis repository](https://github.com/qgis/pyqgis/issues/36). There is a fix (what we use in the docs repository), and @3nids also initiated a fix (as you will see in the previous link) but it has never been committed.
I think this report can be closed, as a duplicate and in the wrong repo.

**Comment by antoniolocandro** [comment]
Hi yes scroll to the left, using windows PC, On the repository thing it sometimes gets complex to know to which repo issues need to be reported specially if new people want to provide feedback

**Comment by DelazJ** [comment]
> On the repository thing it sometimes gets complex to know to which repo issues need to be reported specially if new people want to provide feedback

Quite true and [not a new issue](https://github.com/qgis/pyqgis/issues/19). I think we should point to the pyqgis repo for reports (maybe using a sidebar, like in the docs), up to maintainers to move to this repo if here is more relevant.

**Comment by gioman** [comment]
>  I think this report can be closed, as a duplicate and in the wrong repo.

ok
