### ISSUE TITLE
QGIS crash after click on expression button of model input

### ISSUE THREAD

**Issue by pathmapper** [qgis/QGIS#43698]
**Describe the bug**

QGIS crash after click on expression button of model input.

## Report Details

**Crash ID**: [3fee5ff78a3e1a8843b5c9ef31dc3a80c00865a7](https://github.com/qgis/QGIS/search?q=3fee5ff78a3e1a8843b5c9ef31dc3a80c00865a7&type=Issues)

**Stack Trace**
<pre>
QListData::begin :
QgsExpressionContext::QgsExpressionContext :
QgsExpressionLineEdit::editExpression :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.18.1-Z�rich
QGIS code revision: 202f1bf7e5
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**How to Reproduce**

1. Execute QGIS model [import-photos.zip](https://github.com/qgis/QGIS/files/6638695/import-photos.zip) via QGIS Browser
2. Click expression button (DeleteTableRow input field)
![grafik](https://user-images.githubusercontent.com/20856381/121692344-50a20f00-cac8-11eb-80fa-129cd2425a10.png)
3. QGIS crashes

**Comment by gioman** [comment]
Confirmed also on master/ubuntu 20.04
