### ISSUE TITLE
Parts of geometry disappear in Illustrator when exporting QGIS to  PDF

### ISSUE THREAD

**Issue by MasterPlan123** [qgis/QGIS#43691]
Hi.
I am having this issue with certain polygons when I export to PDF. Everything looks fine in QGIS, everything fine in print composer, everything fine in the PDF as viewed in Preview or Adobe Reader. When I open the PDF in Illustrator to edit, a section of the outline of a certain polygon completely disappears.

I don't have the problem when I export the entire layer and not a section of it.

I have tried to simplify the Geometries, use the Atlas PDF, use polygons as clipping masks. I also checked all the geometries and fixed the errors. 

Hope you can give me advice on how to fix this problem.

Thank you
Gudrun

![broken QGIS PDF](https://user-images.githubusercontent.com/85719616/121623686-4cb5c300-caaf-11eb-949a-bf8a9c0ab35b.png)
![Not broken QGIS PDF](https://user-images.githubusercontent.com/85719616/121623688-4de6f000-caaf-11eb-86f9-45559745afe9.png)

**Comment by gioman** [comment]
@MasterPlan123 is this a question or a bug report?

**Comment by FelisPimeja** [comment]
@MasterPlan123 , I've also faced that problem. Seems like an Illustrator bug - it fails to render objects with too many points. 

Simple workaround is to simplify geometry before export.
