### ISSUE TITLE
Python error in Processing/GDAL translate (convert format)

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#43709]
In Processing/GDAL translate (convert format) 

the input is chosen by clicking "..." on the right of the input layer slot

a GPKG is selected, and this has more than 1 raster layer, or has just vectors in it

```
_core.QgsProcessingException: Could not load source layer for INPUT: /home/***/test.gpkg not found 
Traceback (most recent call last):
  File "/usr/share/qgis/python/plugins/processing/algs/gdal/GdalAlgorithmDialog.py", line 140, in parametersHaveChanged
    commands = self.algorithm().getConsoleCommands(parameters, context, feedback, executing=False)
  File "/usr/share/qgis/python/plugins/processing/algs/gdal/translate.py", line 124, in getConsoleCommands
    raise QgsProcessingException(self.invalidRasterError(parameters, self.INPUT))
_core.QgsProcessingException: Could not load source layer for INPUT: /home/***/test.gpkg not found
```

tested on QGIS master on Ubuntu 20.04

**Comment by agiudiceandrea** [comment]
This is slightly related to https://github.com/qgis/QGIS/issues/43701 about the tool "Convert format" (gal:convertformat) and multi vector layers datasource as input: in that case, only the first vector layer is processed by the underlying created ogr2ogr command.

**Comment by alexbruy** [comment]
Seems fixed. With the latest master (5566e42635) there is no Python error, instead a user-friendly message is printed in the command-line box.

Please reopen if necessary.
