### ISSUE TITLE
Better support for multilayers gpkg data sources in Processing

### ISSUE THREAD

**Issue by geoxluca** [qgis/QGIS#43701]
**new description**

In Processing (i.e. GDAL "convert format") if the users chooses the "select file..." option for the input, and this is a multi layer datasource (for example a GPKG), then the tool works but only for one layer (probably the first found in the GPKG).

It would be good if for this specific case all the layers in the datasource could be processed, outputting to a user selected folder maybe.

**old description**

when I try to reprojct a multy layer .gpck file with the GDAL>Convert format, the process automaticly add the name of the first layer into gpkg to the origin path of the file.
The result is that will be export only the first layer of the layers collection into the geopackage

**Comment by geoxluca** [comment]
yes sorry
1. Go to GDAL "Convert format"
2. Open a multi layers gpkg file in INPUT vector file
3. you can already see in the console GDAL/OGR in the command windows that compare in the end the name of the first layer into the gpkg file
4. set the new CRS with -t_srs EPSG:32633
5.  set the name of the OTPUT new geopakage file file
6. RUN and you can see that only the first layer (point 3 above) will be created with the new Reference System

**Comment by agiudiceandrea** [comment]
@gioman @geoxluca it seems to me this Feature Request would be fixed by https://github.com/qgis/QGIS/pull/45955.

**Comment by gioman** [comment]
> @gioman @geoxluca it seems to me this Feature Request would be fixed by #45955.

@agiudiceandrea thanks for the heads up!
