### ISSUE TITLE
Processing r.neighbors

### ISSUE THREAD

**Issue by antoniolocandro** [qgis/QGIS#43707]
Would be nice if user was given some notification that the size of the neighborhood needs to be odd prior to executing the tool.  Maybe to add in the description/help. Idea is to prevent user to fail to execute based on this fairly easy to overlook mistake

![image](https://user-images.githubusercontent.com/4627073/121745149-429cc000-cac1-11eb-9fb6-4f2ff601bdff.png)

**Comment by nicogodet** [comment]
Easy to miss it in desc
Maybe in parameter name ?
![image](https://user-images.githubusercontent.com/39594821/121750799-59690400-cb0d-11eb-9397-83464851c553.png)

**Comment by antoniolocandro** [comment]
That looks OK to me, I think users would normally read the parameter.
