### ISSUE TITLE
Measure tool slow to respond and sometimes crashes QGIS

### ISSUE THREAD

**Issue by EddyGC** [qgis/QGIS#43718]
## User Feedback
This happens every time I try and measure a line. It often takes an inordinate amount of time after the "Measure" dialogue box opens before I can actually use the tool. On a few occasions it crashes the program. I've tried a clean install, using earlier versions/later versions, different computers but the same problem exists.

## Report Details

**Crash ID**: [34f167c8c13c5a6bb444b2982e0b62478bbf99d0](https://github.com/qgis/QGIS/search?q=34f167c8c13c5a6bb444b2982e0b62478bbf99d0&type=Issues)

**Stack Trace**
<pre>
QgsVectorLayerFeatureIterator::updateFeatureGeometry qgsvectorlayerfeatureiterator.cpp:1191
QgsVectorLayerFeatureIterator::fetchFeature qgsvectorlayerfeatureiterator.cpp:468
QgsAbstractFeatureIterator::nextFeature qgsfeatureiterator.cpp:63
QgsPointLocator::rebuildIndex qgspointlocator.cpp:951
QgsPointLocatorInitTask::run qgspointlocatorinittask.cpp:34
QgsTask::start qgstaskmanager.cpp:83
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.16.7-Hannover
QGIS code revision: 0471743889
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

**Comment by gioman** [comment]
>  I've tried a clean install

@EddyGC have you tried a new QGIS profile (with no 3rd party plugins installed)?

**Comment by EddyGC** [comment]
Hi Giovanni

Yes, also a clean profile.

After the last crash that prompted me to open a ticket, I attempted to 
use the Measure tool again. Nearly 1 minute (52s) after I clicked and 
opened the dialogue box, I was able to use the tool to measure some 
distances.

I don't know if this helps, but I use HP laptops exclusively (ZBooks). I 
buy those with a separate graphics card - NVidia but the problem has 
only appeared in the last 10 months and has gotten progressively worse.

Cheers
Eddy

**Comment by gioman** [comment]
> Yes, also a clean profile.

@EddyGC does it happens on any project? regardless of the data, projection, etc.?

**Comment by EddyGC** [comment]
It doesn't seem to matter what project I work in or the data it uses (a 
mixture of raster, vector), the lag from opening of the dialogue to 
being able to use the tool is always there.

I'm not sure as to projections. I sometime work in GDA94 and often in 
projected GDA94/MGA. Most of the datasets have been standardised in 
GDA94/MGA.

Cheers
Eddy

**Comment by EddyGC** [comment]
Hi @gioman

I've screen recorded a crash while trying to use the measure tool. It is 
a very large file (+160Mb) which means I can't really upload it unless 
there is another option.

Cheers
Eddy

**Comment by wonder-sk** [comment]
From the backtrace it looks like QGIS is indexing data in the background (in order to allow snapping). What vector layers are you using - local files, or some remote databases? And are those layers containing lots of features? (e.g. tens of thousands or more) Or are you using lots of map layers (how many) ?

**Comment by EddyGC** [comment]
Hi Martin

The file I am using and was using at the time has over 20 layers but 
only 9 (8 vector and 1 raster) enabled at the time. The vector layers 
are local and the raster layer is WMS.

The same issue has arisen when working on even simpler projects with 3 
relatively simple vector layers.

Cheers
Eddy

**Comment by EddyGC** [comment]
I have no further information to add to this issue other than the 
problem continues.

Cheers
Eddy
