### ISSUE TITLE
Measure Line wrong unit for displayed heading on first use

### ISSUE THREAD

**Issue by eshattow** [qgis/QGIS#43732]
QGIS 3.18 on Debian GNU/Linux Bullseye pre-release

When using the measure tool the "Segments [feet]" text header sometimes appears when measure tool default "map units" option is active, but the displayed numbers are actually meters. Selecting any unit option from the measure tool dialog and back to "map units" the displayed number is in feet matching the text header. It happens occasionally, not every time.

1. start QGIS
2. toggle editing (on)  - I do this to get the snapping from a point on a Point layer.
3. Measure Line
4. click near point to snap, click again some other place.

Problem: Measure Line heading shows "Segments [feet]" however numbers displayed are in meters by value. Project default is set to feet. See screenshots
![QGIS318MeasureLineBugUnits](https://user-images.githubusercontent.com/12215438/121963423-f058da80-cd1e-11eb-8e6e-935d9e8f808d.png)
.

Work-around: Always select away from "map units" on Measure Line to some other unit and then back to "map units". Units and headings are then displayed correctly.

This does not always happen, but I am able to reproduce by closing QGIS, open the project, and use the Measure Line tool. Some other situations also make it have this weird behavior, but closing and opening the project is a way to reproduce the issue.

**Comment by fgfletcher** [comment]
re #26723, this reported that the units in the Ruler always revert to the project settings value whenever the Ruler is opened,
which is still the case in QGIS 3.18.
I have not encountered what is described above, measurement units which do not match the header.  When the Measure window is up, chaning the units does correctly change both the header and the measured values.

**Comment by eshattow** [comment]
Same problem persists in QGIS 3.20

**Comment by gioman** [comment]
> Same problem persists in QGIS 3.20

@eshattow there was no fix, so it is normal.
