### ISSUE TITLE
Broken copy-paste of the About page

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#43739]
If you go to Help --> About and copy-paste the About information, you get this result:
- some html tags at the beginning of the report
- joined name of plugins, making the table really wide depending on what you have

<meta http-equiv="Content-Type" content="text/html; charset=utf-8"><style type="text/css">
p, li { white-space: pre-wrap; }
</style>

QGIS version | 3.19.0-Master | QGIS code revision | 85345ee12b
-- | -- | -- | --
Qt version | 5.12.8
Python version | 3.8.5
GDAL/OGR version | 3.0.4
PROJ version | 6.3.1
EPSG Registry database version | v9.8.6 (2020-01-22)
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
SQLite version | 3.31.1
PostgreSQL client version | 12.7 (Ubuntu 12.7-0ubuntu0.20.04.1)
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.2
OS version | Ubuntu 20.04.2 LTS
&nbsp; | &nbsp; | &nbsp; | &nbsp;
This copy of QGIS writes debugging output.
&nbsp; | &nbsp; | &nbsp; | &nbsp;
Active Python plugins | trackable_project_filesMapsPrinterMemoryLayerSaverplugin_reloaderdb_managerMetaSearchprocessing

```

**Comment by Gustry** [comment]
IMHO, we should add a button "Copy table content" or similar, it would be easier than "ctrl+a, ctrl+c" etc ...

**Comment by alexbruy** [comment]
Related issue #42037

**Comment by alexbruy** [comment]
Let's close this and keep #49054.
