### ISSUE TITLE
Reach a point on the field whith a cm accuracy

### ISSUE THREAD

**Issue by Cantalou15** [qgis/QGIS#43747]
**Feature description.**

QGis embedded in a rugged Tablet or PC is a very useful tool with GNSS position.

Actually Qgis is able to connect with internal or external GNSS so it's possible to have a centimetre accuracy while creating a point.

Now the next step is to create a point very precisely at the office and reach this point on the field or the worksite with the same accuracy (less than 3cm).

So, we need a new tool, maybe in the "GPS information panel" with an arrow in compass witch will show the direction and distance to the point to reach (selected on the map).

Of course we also need an automatic zoom management when approaching the point (less than 3m and less than 10cm)

How it works on other Apps

[https://docs.emlid.com/reachrs2/common/reachview/survey/#staking-out-points](url)

[
https://user-images.githubusercontent.com/12166686/96684901-a3358c00-137c-11eb-8d08-1af86a8f40f3.gif](url)

**Additional context**
Who will it be useful for ?

Agricultural services who need to have a survey on soils or cultures at the same place years after years (my situation)

Builders who need to set up a future building using plans drawn at the office.

Surveyors who need to do their job of ... surveyors

Pirate who need to find his buried treasure with a precise map !
...

**Comment by Cantalou15** [comment]
Hope this will concern someone cause I can have an idea but I don't know how to code it !

**Comment by tjukanovt** [comment]
Are you sure you need this to be in QGIS? Maybe you should look in to field data collection tools which integrate to QGIS workflows like Input app or [QField](https://qfield.org/).

**Comment by Cantalou15** [comment]
You're right: QField and Input are very useful with a smartphone. That's why we asked both teams to work on new functionality to guide us and reach a point very precisely. At the moment no open source app seams to be able to do that.
BUT, QGIS is an other level when we need to work outside AND QGIS is able to use GNSS to localise the user on the map ... why not guiding the same user to the point he whant to reach ?

**Comment by tjukanovt** [comment]
I still think that this feature would suit better on the mobile applications than QGIS. Also [Qfield is able to use GNSS](https://qfield.org/docs/fieldwork/gps.html).

**Comment by saberraz** [comment]
See also https://github.com/lutraconsulting/input/issues/822
