### ISSUE TITLE
Legend Resizing Issues in Layout

### ISSUE THREAD

**Issue by normbetland** [qgis/QGIS#43759]
I am having an extreme difficulty in changing the size of my legend in a layout. The program will not allow me to resize it smaller than 500000 mm (which is 5 km!) I have tried to change the units to all my options, but it simply recalibrates and won't let me go smaller than that. I am very much at a loss as to what is causing this issue, when it worked fine the other day in a different project.

**Comment by gioman** [comment]
@normbetland is this a question or a bug report?

**Comment by normbetland** [comment]
Bug
