### ISSUE TITLE
Option "Make lines appear less jagged" break fonts since v3.12

### ISSUE THREAD

**Issue by freeconst** [qgis/QGIS#43777]
QGIS: 3.18.3-Zürich
Qt: 5.15.2
If disable the option on versions including 3.10, the fonts remain readable. Starting from version 3.12, this option disables anti-aliasing not only for lines, but also for fonts, which impairs readability.

![bug](https://user-images.githubusercontent.com/5403268/122402182-eab0fe00-cf85-11eb-955a-5bca21ea1803.png)

**Comment by nyalldawson** [comment]
This is deliberate, and is a wont-fix. Disabling antialiasing now applies to text as well as other map content. There's rationale in https://github.com/qgis/QGIS/issues/17893
