### ISSUE TITLE
Broken Peirce Quincuncial projection - reproject on the fly

### ISSUE THREAD

**Issue by aourednik** [qgis/QGIS#43776]
When swithching to Peirce Quincuncial EPSG 54090, all geometries disappear.

**How to Reproduce**

1. Import a layer of world countries geometries in EPSG:4326. 
2. Zoom to Layer. Result: the world map appears
3. Click on the projection button (bottom right, main screen)
4. Test wheter reproject on thy works
    a) Select the Molweide Projection EPSG 54009. 
    b) Zoom to layer. Result: the world map appears reprojected on the fly in Molweide projection
5. Click on the projection button (bottom right, main screen) and select Peirce Quincuncial EPSG 54090 from the list
6. Zoom to layer

__Nothing appears__

**QGIS and OS versions**

QGIS version | 3.18.3-Zürich | QGIS code revision | 735cc85be9
-- | -- | -- | --
Compiled against Qt | 5.14.2 | Running against Qt | 5.14.2
Compiled against GDAL/OGR | 3.2.1 | Running against GDAL/OGR | 3.2.1
Compiled against GEOS | 3.9.1-CAPI-1.14.2 | Running against GEOS | 3.9.1-CAPI-1.14.2
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
Compiled against PDAL | 2.2.0 | Running against PDAL | 2.2.0 (git-version: Release)
PostgreSQL Client Version | 12.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.4
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | macOS Mojave (10.14)
Active python plugins | QuickOSM; clipper; quick_map_services; qgis2web; latlontools; processing_r; processing; db_manager; MetaSearch

**Comment by PeterPetrik** [comment]
Warning in "CRS" tab:
```
Simplify transform error caught: forward transform of
             (inf, inf)
             Error: Fallback transform failed
```

**Comment by tcwilkinson** [comment]
Note as semi-workaround, it is possible to use a custom CRS using the proj4 string `+proj=peirce_q` plus any options:- see https://proj.org/operations/projections/peirce_q.html 

...However, there's a small catch: PROJ (8.1.?+) seems only to work with positive latitudes (i.e. only the northern hemisphere), so you'll only get the central square of the expected diamond. 

See this PR and commit in PROJ library repos:-
- https://github.com/OSGeo/PROJ/pull/2230
- https://github.com/OSGeo/PROJ/commit/e4bf822158aa5193022e8392f0eddd6510653bfa

Presumably this means that PQ (and similar) cannot be implemented _yet_ in QGIS... :-(

**Comment by tcwilkinson** [comment]
Brief update:- have contributed code to fix the restriction to northern hemisphere. Pull request has been accepted and looks set to make next 8.2.x release of PROJ. 

Function in QGIS will require update to the version of the library that QGIS uses. Don't know what the timescale for that will be.
