### ISSUE TITLE
Program chashed with GTFS Loader

### ISSUE THREAD

**Issue by susanambb** [qgis/QGIS#43775]
## User Feedback

QGIS crashed when loading GTFS zip with GTFS Loader 

## Report Details

**Crash ID**: [a861d0189505b722658dd3b84f4e29507581c307](https://github.com/qgis/QGIS/search?q=a861d0189505b722658dd3b84f4e29507581c307&type=Issues)

**Stack Trace**
<pre>
QSortFilterProxyModel::trUtf8 :
QSortFilterProxyModel::sortRole :
QSortFilterProxyModel::`default constructor closure' :
QMetaObject::activate :
QAbstractItemModel::endInsertRows :
QgsLayerTreeModel::nodeAddedChildren qgslayertreemodel.cpp:756
QMetaObject::activate :
QgsLayerTreeNode::addedChildren moc_qgslayertreenode.cpp:283
QMetaCallEvent::placeMetaCall :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:475
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker  @:
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1638
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.18.3-Z�rich
QGIS code revision: 735cc85be9
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

**Comment by gioman** [comment]
> QGIS crashed when loading GTFS zip with GTFS Loader

@susanambb you must report this to the plugin author/s.
