### ISSUE TITLE
Inverted polygons symbology does not work with holes

### ISSUE THREAD

**Issue by Sallagispo** [qgis/QGIS#43784]
**Describe the bug**
If the polygon layer has a polygon with hole, filled with another polygon, "inverted polygons" symbology does not work properly. The inner polygon is shown as a mask just like any outside area, while it should be part of a "hole" in a mask layer.

**How to Reproduce**
![image](https://user-images.githubusercontent.com/36758706/122525430-e63a2300-d021-11eb-9419-3abf551b166b.png)
Figure 1. Polygon with a hole, filled with another polygon. In this picture I used Categorized symbology to show the polygons.

![image](https://user-images.githubusercontent.com/36758706/122525668-24cfdd80-d022-11eb-8a21-7cb53a5fec88.png)
Figure 2. The same polygons with Single symbol symbology.

![image](https://user-images.githubusercontent.com/36758706/122525772-403ae880-d022-11eb-9ccc-a60ff88d1140.png)
Figure 3. Inverted polygons symbology. You can see that the hole is covered with the mask layer, despite the fact that there is a polygon.

**QGIS and OS versions**

I use freshly installed QGIS 3.16.7 'Hannover' with Windows 10. 
Data format: shapefile and geopackage vector files.

**Additional context**
I have a feeling that this has something to do with [(https://github.com/qgis/QGIS/issues/18759)] (inverted polygons symbology and overlapping polygons).

**Comment by Joonalai** [comment]
This bug still exists in 3.18.3.

**Comment by Joonalai** [comment]
I started to look into it and traced the bug here:

https://github.com/qgis/QGIS/blob/a038a79997fb560e797daf3903d94c7d68e25f42/src/core/symbology/qgsmergedfeaturerenderer.cpp#L352

**Comment by Joonalai** [comment]
If flag `Merge polygons before rendering` is used, the symbology looks as intended.

**Comment by Joonalai** [comment]
@mhugo is there a reason why the flag `Merge polygons before rendering` is not on by default? After testing with some quite huge datasets I didn't notice any performance difference between those two. And the code in the `case QgsMergedFeatureRenderer::MergeAndInvert` is much simpler and works on all cases (even with otherwise invalid geometries). Is it really slower with modern computers?

**Comment by mhugo** [comment]
@Joonalai I am not sure, my last touch to this part of the code was some years in the past.
But from what I can see, there are still calls to potentially expensive operations like buffer (to try to make invalid geometries valid) and union in the `MergeAndInvert` case. So if these operations are really actually not expensive anymore (?) it would be needed to understand exactly why before someone decides to make them the default.

**Comment by gioman** [comment]
> @Sallagispo If flag `Merge polygons before rendering` is used, the symbology looks as intended.

Then this should be closed. Making that option should be discussed separately in a feature requests/improvement ticket.
