### ISSUE TITLE
Wrong geopackage BLOB image rotation

### ISSUE THREAD

**Issue by stuskier** [qgis/QGIS#43789]
At 3.18.3, QGIS does not take EXIF orientation metadata into account when viewing images in a Geopackage table form view, as shown in the example below.  

![Untitledx](https://user-images.githubusercontent.com/12805900/122609233-85671680-d032-11eb-97a4-8beaf956cd5e.jpg)

In comparison, Windows File Explorer, Paint, and IrfanView all correctly display the same image non-rotated, by default:

![Untitledz](https://user-images.githubusercontent.com/12805900/122609105-4933b600-d032-11eb-8f5a-b4f91b48172d.jpg)

There is a very clumsy, time-consuming work-around, using external software such as IrfanView, to reset the EXIF _Orientation_, as discussed in this StackExchange post:  [https://gis.stackexchange.com/questions/401836/qgis-randomly-rotates-images-stored-as-geopackage-blob](url)

However, QGIS _would really rock_ if it acted - by default - just like Windows File Explorer, etc., and took the EXIF orientation metadata into account when viewing images.

**Comment by roya0045** [comment]
Unsure if this QGIS specific or provider specific.

**Comment by nicogodet** [comment]
Is this related to #38611 ?
In QGis in general, EXIF orientation is not supported ?

**Comment by stuskier** [comment]
Yes, perhaps so, in which case this might be a bug, rather than a feature request.

Stu

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by SrNetoChan** [comment]
If it never worked before, despite of what users would expect, it's a feature request, not a bug. See Andreas comment on the linked issue. If this is a big limitation for you, consider sponsoring the implementation or organize a crowdfunding to do it.

**Comment by nicogodet** [comment]
Tested with importPhoto tool (output to shapefile and gpkg), EXIF orientation is supported in table view.

**Comment by nicogodet** [comment]
I used import photo tool juste to create the correct view form.

But how did you create your form ?
It looks like an html view.

When I display the image with "Attachment", orientation is OK.
![image](https://user-images.githubusercontent.com/39594821/122781029-b56f1d80-d2af-11eb-9c0f-fc0ba49686ff.png)

**Comment by Houska1** [comment]
Could this be a Qt/QML `autoTransform` issue? I ran up against it a year or so back, and did my own workaround. It seemed Qt did not treat EXIF orientation consistently, there were some changes made around Qt version 5.5 or so, and when writing QML (in a form) one could get around it by including `autoTransform: true`. If so, it might be a reasonably easy fix.

BTW while borderline, I think this is a bug not a new feature request. If we display JPG images, georeferenced or not, we should display them correctly, which includes incorporating EXIF orientation tags which are quite commonplace.

**Comment by gioman** [comment]
> When I display the image with "Attachment", orientation is OK.

@nicogodet the title seems to suggest that the photo preview comes from a binary/blob field, while normally previews are from a file system path, maybe this is an important difference?

**Comment by nicogodet** [comment]
@gioman After digging, yeah it seems to be an important difference.

You have to retrieve the binary data, convert to base64, then html img...
And based on @Houska1 script on GIS stack ([here](https://gis.stackexchange.com/a/401958)), not sure this is a QGIS issue.

A feature request would be to add ability to display the blob directly (like attachment does).

**Comment by gioman** [comment]
> A feature request would be to add ability to display the blob directly

@nicogodet (I haven't tried) but this is not what @stuskier is describing?

**Comment by nicogodet** [comment]
@gioman Need te be confirmed but yes.

Currently it seems that the only way to display a picture stored as BLOB is to use a QML or HTML widget.
The feature would be to use attachement (which support EXIF orientation) to display the picture.
It's not exactly describe like this in first comment.

**Comment by gioman** [comment]
> The feature would be to use attachement (which support EXIF orientation)

@nicogodet ok got it.

**Comment by stuskier** [comment]
I'm the person that originally submitted this issue.  I received a github notice that it had gone stale because there was no action in the last 14 days.  I'd really like to see this solved, but don't know how to get action on it.  Suggestions?

**Comment by gioman** [comment]
> I'm the person that originally submitted this issue. I received a github notice that it had gone stale because there was no action in the last 14 days. I'd really like to see this solved, but don't know how to get action on it. Suggestions?

@stuskier see https://github.com/qgis/QGIS/issues/43789#issuecomment-864518174 attaching a sample project+sample dataset would also help.
