### ISSUE TITLE
[composer][memory] High memory usage when loading a JPG file in composers

### ISSUE THREAD

**Issue by mdouchin** [qgis/QGIS#43787]
I discovered QGIS has a **high usage of memory** when the project has one or several **print composers** with JPG raster images, usually used to show icons or pictures. 

In my context, the memory usage increase with **~ 250MB for one composer** with one JPG image, which lead to ~ 2.5 Gb if the project has 10 composers with the same JPG logo.

In **QGIS Server** context, where several QGIS workers can be used, the memory consumption adds up. If you have 10 workers, and only one "problematic" project, you fill up your memory pretty fast.

I created a sample project to illustrate the issue, with no layers and ten print composers with only the one attached JPG picture inside.

* Ubuntu 20.04 focal
* Version: QGIS 3.16.5
* Project (rename from .txt to .qgz: I renamed it due to Github extension policy): 
[high_memory_usage_composer.txt](https://github.com/qgis/QGIS/files/6678213/high_memory_usage_composer.txt)

* JPG picture: 
![PDS](https://user-images.githubusercontent.com/3492210/122589033-130d2b00-d060-11eb-91d7-592789d6f280.jpg)

**Comment by mdouchin** [comment]
cc @rldhont @dmarteau

**Comment by rldhont** [comment]
The [QgsLayoutItemPicture](https://qgis.org/api/classQgsLayoutItemPicture.html) has a private `QImage mImage`. The private `mImage` stores and keeps the binary picture to be ready for the rendering.

I have found the the image is loaded at the end of the XML parsing:
* At the en of `QgsLayout::addItemsFromXml`, the items restoration from xml has been finalized https://github.com/qgis/QGIS/blob/master/src/core/layout/qgslayout.cpp#L989
* At the end of `QgsLayoutItemPicture::finalizeRestoreFromXml`, the image is refreshed https://github.com/qgis/QGIS/blob/master/src/core/layout/qgslayoutitempicture.cpp#L904

In the case of the [QgsLayoutItemPicture](https://qgis.org/api/classQgsLayoutItemPicture.html) the image could only be loaded when it is needed before dsipaly the layout in Desktop or before using it in Server. And it will be usefull to clear `mImage` when the layout is unloaded.

**Comment by roya0045** [comment]
@rldhont Nice finding! Was a bugfix planned regarding this or this was only to document the root cause?

**Comment by rldhont** [comment]
@roya0045 this was to document the root case and help to bugfix.
