### ISSUE TITLE
undefined reference to `_qgis_lwgeom_make_valid`

### ISSUE THREAD

**Issue by JiehangXie** [qgis/QGIS#43796]
**Describe the bug**

Compile Error:
```
[ 49%] Linking CXX shared library ../../output/lib/libqgis_core.so
/usr/bin/ld: CMakeFiles/qgis_core.dir/geometry/qgsgeometry.cpp.o: in function `QgsGeometry::makeValid() const':
qgsgeometry.cpp:(.text+0xd45a): undefined reference to `_qgis_lwgeom_make_valid(QgsAbstractGeometry const*, QString&)'
collect2: error: ld returned 1 exit status
make[2]: *** [src/core/CMakeFiles/qgis_core.dir/build.make:13545：output/lib/libqgis_core.so.3.20.0] 错误 1
make[1]: *** [CMakeFiles/Makefile2:3966：src/core/CMakeFiles/qgis_core.dir/all] 错误 2
make: *** [Makefile:166：all] 错误 2
```
“错误” means error in Chinese.

**How to Reproduce**

1. cmake ../
2. make -j4
3. Then when the process goes to 49%, it comes out an error above.

**QGIS and OS versions**
QGIS 3.20,Linux Deepin 5.10.29-amd64-desktop(Debian Linux),Cmake 3.20.4

**Additional context**

**Comment by gioman** [comment]
> Then when the process goes to 49%, it comes out an error above.

 @JiehangXie better ask in the developers mailing list too.

**Comment by ggardet** [comment]
I get the same error on openSUSE Tumbleweed on `armv7` with CMake 3.20.4 and GCC11

**Comment by stumbles** [comment]
I get the same failure using 3.20.2;

[ 12%] Building CXX object src/core/CMakeFiles/qgis_core.dir/flex_qgsmeshcalclexer.cpp.o
[ 12%] Building CXX object src/core/CMakeFiles/qgis_core.dir/qgsexpressionparser.cpp.o
[ 12%] Building CXX object src/core/CMakeFiles/qgis_core.dir/qgsmeshcalcparser.cpp.o
[ 12%] Building CXX object src/core/CMakeFiles/qgis_core.dir/qgsopenclutils.cpp.o
[ 12%] Building CXX object src/core/CMakeFiles/qgis_core.dir/providers/ept/qgseptdataitems.cpp.o
[ 12%] Building CXX object src/core/CMakeFiles/qgis_core.dir/providers/ept/qgseptprovider.cpp.o
[ 12%] Building CXX object src/core/CMakeFiles/qgis_core.dir/pointcloud/qgseptdecoder.cpp.o
[ 12%] Building CXX object src/core/CMakeFiles/qgis_core.dir/pointcloud/qgseptpointcloudindex.cpp.o
[ 12%] Building CXX object src/core/CMakeFiles/qgis_core.dir/pointcloud/qgsremoteeptpointcloudindex.cpp.o
[ 12%] Linking CXX shared library ../../output/lib/libqgis_core.so
/usr/bin/ld: CMakeFiles/qgis_core.dir/geometry/qgsgeometry.cpp.o: in function `QgsGeometry::makeValid() const':
qgsgeometry.cpp:(.text+0x3cd6): undefined reference to `_qgis_lwgeom_make_valid(QgsAbstractGeometry const*, QString&)'
collect2: error: ld returned 1 exit status
make[2]: *** [src/core/CMakeFiles/qgis_core.dir/build.make:13552: output/lib/libqgis_core.so.3.20.2] Error 1
make[1]: *** [CMakeFiles/Makefile2:2015: src/core/CMakeFiles/qgis_core.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
