### ISSUE TITLE
flex-generated code includes "register" keyword

### ISSUE THREAD

**Issue by kyngchaos** [qgis/QGIS#43795]
**Describe the bug**

Compile Error:
`
QGIS-final-3_20_0/build-mojave/src/core/flex_qgsmeshcalclexer.cpp:765:2: error: 
      ISO C++17 does not allow 'register' storage class specifier [-Wregister]
        register yy_state_type yy_current_state;
        ^~~~~~~~~
`
and many more lines in that file.

Maybe there is a flag for flex/bison missing to tell it the C++ std?

**QGIS and OS versions**

QGIS 3.20. macOS 10.15 Catalina, latest Xcode for the system, Clang 12.0.0, targeting macOS 10.14.  Bison 3.7.6.

**Comment by Veence** [comment]
Ah, Apple's flex is 2.5. I’m going to upgrade, thanks

**Comment by kyngchaos** [comment]
I thought Bison is an alternate for flex.  Do I really need a separate flex?

**Comment by jef-n** [comment]
No, bison is an alternative to yacc  - as flex is an alternative to lex.   The parser generated by bison uses the lexer generated by flex.
