### ISSUE TITLE
Import Second QGIS Project

### ISSUE THREAD

**Issue by gafzgarrr** [qgis/QGIS#43808]
**Feature description.**

Import a second QGIS Projekt with different Data base, without loosing Syle.

**Additional context**

Sometimes i have to similar QGIS Projects. I need a solution to create a new QGIS Projekt out of these two Projekts, without loosing the styles of every layer.

**Comment by gioman** [comment]
Save layers styles, as QML (with the same name of the layer) or in your DBs (GPKG, PostGIS) and when you will load the layer into a new project it will load automatically its default style.

**Comment by andreasneumann** [comment]
Are you talking about a Postgis database? If yes, you can use service configurations and then easily point the service configuration centrally to a different db without having to change anything in the QGIS project.

**Comment by PeterDrexel** [comment]
A workaround could be to open both projects in 2 different instances of QGIS and then drag and drop the disired layers from one to the other project.

**Comment by roya0045** [comment]
@PeterDrexel I'm not sure this is a workaround as this should be the proper way to interchange data between projects IMO.
