### ISSUE TITLE
Marker Line displaying symbols on autocrossing features

### ISSUE THREAD

**Issue by nereischan** [qgis/QGIS#43806]
In QGIS 3.16.7:

When using the marker line to show symbols only at the end of the line, symbols are drawn in each intersection of the line with itself.

This happened after I dissolved the shape by a field, but not when I created the lines.

Before dissolving
![image](https://user-images.githubusercontent.com/61959314/122732191-ff0f3680-d2b6-11eb-8d54-3cf1c37318fa.png)

After dissolving
![image](https://user-images.githubusercontent.com/61959314/122732206-046c8100-d2b7-11eb-85cf-d32072c19ca3.png)

[testshp.zip](https://github.com/qgis/QGIS/files/6685225/testshp.zip)

**Comment by gioman** [comment]
> After dissolving

@nereischan attach the data.

**Comment by nereischan** [comment]
> > After dissolving
> 
> @nereischan attach the data.

I edited the post and created some test data for the issue

**Comment by gioman** [comment]
> I edited the post and created some test data for the issue

@nereischan your lines are multipart, but still are split where you see the markers. So I guess this is expected, there is a marker at the end/beginning of each part.

**Comment by nereischan** [comment]
Thank you for your reply

So after using the dissolve tool the lines become multipart, instead of the single part when I created them.

Is there any way to merge the lines by ID and keep them singlepart so the markers only show at the end of the line?

**Comment by gioman** [comment]
> Is there any way to merge the lines by ID and keep them singlepart so the markers only show at the end of the line?

@nereischan use "collect geometries".

**Comment by nicogodet** [comment]
On your primary data, you have self-intersections which are a topology error in many cases. 

I think most of processing tools will create valid geometries (without self-intersections).

**Comment by andreasneumann** [comment]
well - it depends on the nature of the data. For certain topics self-intersections would be totally fine. Think of flight paths of aerial vehicles or birds intersecting themselves. You wouldn't want to split lines in such cases. Even certain streets and railway lines have circular tunnels or bridges where you don't want to split on self-intersections (or real intersections).

**Comment by gioman** [comment]
> well - it depends on the nature of the data. For certain topics self-intersections would be totally fine. Think of flight paths of aerial vehicles or birds intersecting themselves. You wouldn't want to split lines in such cases. Even certain streets and railway lines have circular tunnels or bridges where you don't want to split on self-intersections (or real intersections).

@andreasneumann I agree. So... is really expected for the dissolve tool to split lines at intersections? maybe the "collect geometries" tool was added thinking also about this case(?).

**Comment by nereischan** [comment]
> > Is there any way to merge the lines by ID and keep them singlepart so the markers only show at the end of the line?
> 
> @nereischan use "collect geometries".

Thank you all for your quick replies.

This is exactly what I was looking for I guess.
I will use this instead of the dissolve tool.

Thanks again!

**Comment by andreasneumann** [comment]
> So... is really expected for the dissolve tool to split lines at intersections?

My assumption is that the dissolve tool was created primarily with polygons in mind - the fact that it also works with LineString geometries is probably a poor coincidence. It would be great if the tool could be enhanced to better deal with such cases.

**Comment by gioman** [comment]
> geometries is probably a poor coincidence.

@andreasneumann https://github.com/qgis/QGIS/issues/43811

**Comment by nereischan** [comment]
As a follow-up request, would not it be simpler if the "Marker Symbol" at the last vertex included markers only at the end of the connected line feature?
I think whether the line is multipart or not, the objective of displaying "last vertex only" is to have a single symbol at the end of a connected line.

For example, you may have two birds, each one with a different flying route but with the same table attributes (Name, Species, etc.) and hence want to store them as a single feature, but displaying each route with a marker at the end.
