### ISSUE TITLE
Cannot connect to a remote geonode server using OAuth2

### ISSUE THREAD

**Issue by geogeek11** [qgis/QGIS#43810]
I have tried following [geonode guide](https://docs.geonode.org/en/master/usage/other_apps/qgis/index.html#connect-to-private-layers-by-using-oauth2) to connect to a geonode private layer using OAuth2.

Please check below the settings that I have used to connect to a remote geonode server.
![Screenshot from 2021-06-21 12-20-48](https://user-images.githubusercontent.com/7670475/122754512-aeceaf00-d28b-11eb-83b3-1cffbf564833.png)

After clicking on Test connection, I get the web page below, then I click on authorize
![Screenshot from 2021-06-21 12-22-11](https://user-images.githubusercontent.com/7670475/122754528-b4c49000-d28b-11eb-8cbf-48e73b936984.png)

After that, I get redirected to the web page below, and no connection is set up :
![Screenshot from 2021-06-21 12-22-31](https://user-images.githubusercontent.com/7670475/122754553-baba7100-d28b-11eb-9244-cb3f2205c013.png)

```

Version de QGIS
3.16.4-Hannover
Révision du code
654e76b3cb
Compilé avec Qt
5.11.2
Utilisant Qt
5.11.2
Compilé avec GDAL/OGR
3.1.4
Utilisé avec GDAL/OGR
3.1.4
Compilé avec GEOS
3.8.1-CAPI-1.13.3
Utilisé avec GEOS
3.8.1-CAPI-1.13.3
Compilé avec SQLite
3.29.0
Fonctionne avec SQLite
3.29.0
Version du client PostgreSQL
11.5
Version de SpatiaLite
4.3.0
Version de QWT
6.1.3
Version de QScintilla2
2.10.8
Compilé avec PROJ
6.3.2
Fonctionne avec PROJ
Rel. 6.3.2, May 1st, 2020
Version de l'OS
Windows 7 SP 1 (6.1)
Extensions Python actives
qgis_geonode; 
SemiAutomaticClassificationPlugin; 
db_manager; 
MetaSearch; 
processing
```

**Comment by gioman** [comment]
@geogeek11 are you using the "qgis_geonode" plugin and the error comes from it? If yes you must report this to the plugin author, not here.

**Comment by geogeek11** [comment]
For the current issue, I have uninstalled the plugin 'qgis_geonode', but the same problem remains.

This problem has occurred using qgis before installing that plugin, and during its use, and after its uninstall.

**Comment by gioman** [comment]
You sure the problem is not in the Geonode end?

**Comment by geogeek11** [comment]
Please is there any way to test if the issue comes from Geonode or Qgis ?

**Comment by gioman** [comment]
> Please is there any way to test if the issue comes from Geonode or Qgis ?

Try a different client? I have recently tested your scenario on a vanilla installation of Geonode, and it was working as expected.

**Comment by geogeek11** [comment]
> > Please is there any way to test if the issue comes from Geonode or Qgis ?
> 
> Try a different client? I have recently tested your scenario on a vanilla installation of Geonode, and it was working as expected.

Please which client (other than QGIS) could I use for testing ?

**Comment by gioman** [comment]
> Please which client (other than QGIS) could I use for testing ?

I ignore if there are others.
