### ISSUE TITLE
Duplicate FIDs in "Points along Geometry" tool output

### ISSUE THREAD

**Issue by everydayduffy** [qgis/QGIS#43817]
When using the points along geometry tool on a line layer, the outputs all have an FID with a value of 1. This causes issues when trying to export the output to a geopackage, as unique FIDs seem to be required. 

My suggested improvement is to give each point in the output layer a unique FID.

My session information is:

QGIS version | 3.6.1-Noosa | QGIS code revision | 2468226bc9
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.0-CAPI-1.11.0 | Running against GEOS | 3.7.0-CAPI-1.11.0 673b9939
PostgreSQL Client Version | 9.2.4 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 520 | Running against PROJ | 5.2.0

**Comment by gioman** [comment]
> QGIS version | 3.6.1-Noosa

@everydayduffy way too old. You must try with the latest 3.16 or 3.20.

**Comment by everydayduffy** [comment]
@gioman good point!

Just installed 3.20 and can confirm the same issue exists.

FYI:

QGIS version | 3.20.0-Odense | QGIS code revision | decaadbb31
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.0
PROJ version | 8.0.1
EPSG Registry database version | v10.018 (2021-04-02)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
Active Python plugins | DEMto3DDigitizingToolsOSMDownloaderquick_map_servicesSRTM-Downloaderdb_managerMetaSearchprocessing

**Comment by gioman** [comment]
Yeah, it seems they get the FID of the feature they are being placed on...

**Comment by nicogodet** [comment]
It seems to be a more general issue
Also happens with `Explode lines`, `Extract vertices` when output to temporary layer then trying to save the temp output to a geopackage.

**Comment by nyalldawson** [comment]
Not an issue with processing -- if you save the processing result directly to gpkg then there's no issues, as this situation is already handled in all the listed algorithms. The solution would be to make sure you manually uncheck the "fid" column when saving a memory layer to geopackage.

**Comment by nyalldawson** [comment]
@gioman I think this can be closed -- it's a workflow issue, not a QGIS issue

**Comment by nicogodet** [comment]
@nyalldawson Why does `fid` column is created is the first place ?

Let's take for example "Random points in extent", `fid` column is not created when output to temporary layer (then saving to geopackage is fine) and output directly to geopackage is fine too.

**Comment by nyalldawson** [comment]
It's coming from the original features, which have a field called fid

**Comment by gioman** [comment]
> @gioman I think this can be closed -- it's a workflow issue, not a QGIS issue

I obey :)
