### ISSUE TITLE
QGIS 3.16 not opening

### ISSUE THREAD

**Issue by ybooth** [qgis/QGIS#43812]
Hi
I was running QGIS version 3.16 with no issues last week but today when I try to open it it looks like it's going through the start up process but it's hanging after saying "QGIS Ready!". Our IT department uninstalled and reinstalled the software but it's still not opening. I was wondering if this is something that's been seen before or if anyone has any ideas about why this may be happening. Our whole team is experiencing this issue. 

![image](https://user-images.githubusercontent.com/86242608/122771899-c4999f80-d29e-11eb-98e7-8599ecb1ad0a.png)

**Comment by ybooth** [comment]
Could this be an issue with Windows defender?

**Comment by roya0045** [comment]
Did you remember a password or set anything in the keychain? This caused crashes, sometimes you need to restart until the faulty plugin deactivated, otherwise you can't start a new sessions clean of plugins.

**Comment by gioman** [comment]
> Could this be an issue with Windows defender?

@ybooth it can be several things, but is not a general QGIS issue. Try delete the QGIS profiles folder (back it up if it contains important things like scripts, models, etc.), then try start QGIS.

**Comment by agiudiceandrea** [comment]
> otherwise you can't start a new sessions clean of plugins.

@roya0045 I think you can add `--noplugins` as option in the Windows shortcut target property
https://docs.qgis.org/3.16/en/docs/user_manual/introduction/qgis_configuration.html#noplugins

**Comment by ybooth** [comment]
Thanks everyone for your suggestions. It seems it's likely related to another issue that was reported before (https://github.com/qgis/QGIS/issues/33164). QGIS projects were previously connected to a network drive that has now been taken offline.

**Comment by gioman** [comment]
> Thanks everyone for your suggestions. It seems it's likely related to another issue that was reported before (#33164). QGIS projects were previously connected to a network drive that has now been taken offline.

@ybooth ok, this was fixed in 3.20 here https://github.com/qgis/QGIS/pull/43416

**Comment by agiudiceandrea** [comment]
Is this fixed in 3.16 branch, too? It seems https://github.com/qgis/QGIS/pull/43416 was not (yet) backported.
