### ISSUE TITLE
Get contributed pack issue

### ISSUE THREAD

**Issue by ccalab001** [qgis/QGIS#43820]
Hello,

 I installed the QGIS program on the system and when I try to do the Get contributed pack, it will close the program after 30 seconds. I already uninstalled the program and reinstalled it but still same issues. Not sure what is causing it. Can someone help?

QGIS version
3.18.3-Zürich

Thank you, 

CJ

**Comment by nicogodet** [comment]
Are you talking about QuickMapService plugin ?

**Comment by gioman** [comment]
> Are you talking about QuickMapService plugin ?

@ccalab001 reopen this ticket if is not about the QuickMapservces Plugin, if it is you must report it in the plugin tracker, not here. Thanks!
