### ISSUE TITLE
Could not start GPSBabel

### ISSUE THREAD

**Issue by Warkorentin** [qgis/QGIS#43824]
Hi ! 
Whenever I try to use the GPS plugin, I get the following error :

> Could not start GPSBabel.

Now I have GPSBabel installed on my system and I'm able to use it from command line. 

Any suggestion on what I could do to find the problem/solve this ? 

Thanks a lot 

QGIS version | 3.20.0-Odense | QGIS code revision | decaadbb31
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.2.2
PROJ version | 7.2.1
EPSG Registry database version | v10.008 (2020-12-16)
GEOS version | 3.9.0-CAPI-1.16.2
SQLite version | 3.34.1
PDAL version | 2.2.0
PostgreSQL client version | 13.3 (Ubuntu 13.3-0ubuntu0.21.04.1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 21.04

Active Python plugins | processingdb_managerMetaSearch

**Comment by gioman** [comment]
@Warkorentin maybe setting the correct path to the binary?

![image](https://user-images.githubusercontent.com/1951107/122886289-be0b3680-d337-11eb-9114-c1f6b2aa1943.png)

not sure anyway, I also think that the tool is unmaintained.

**Comment by Warkorentin** [comment]
Thanks for the answer

Unfortunately, after switching to the full path I'm still getting the error

**Comment by gioman** [comment]
> Unfortunately, after switching to the full path I'm still getting the error

too bad, but as said I think it is unmaintained, so not really a big surprise is not working.

**Comment by nyalldawson** [comment]
> not sure anyway, I also think that the tool is unmaintained.

Not entirely true -- I've received a QGIS grant recently to look into this plugin and bring it's functionality into mainstream QGIS :+1:

**Comment by gioman** [comment]
> Not entirely true -- I've received a QGIS grant recently to look into this plugin and bring it's functionality into mainstream QGIS +1

good news then.

**Comment by nyalldawson** [comment]
This should be fixed in 3.22 -- please reopen if not.
