### ISSUE TITLE
Unable to run qgis_process from command line for native:atlaslayouttopdf QGIS algorithm

### ISSUE THREAD

**Issue by ThomasG77** [qgis/QGIS#43823]
I've tried to run below commands in my terminal

1st try **with** `COVERAGE_LAYER` option

```
qgis_process run native:atlaslayouttopdf --project=/home/thomasg/own-projects/sample-qgis-server/projects/atlas_minimum-bug-processing-layout.qgz --COVERAGE_LAYER=/home/thomasg/own-projects/sample-qgis-server/projects/ne_10m_admin_0_countries.shp --LAYOUT=v1_layout_atlas --OUTPUT=/tmp/atlas1.pdf
```

2nd try **without** `COVERAGE_LAYER` option

```
qgis_process run native:atlaslayouttopdf --project=/home/thomasg/own-projects/sample-qgis-server/projects/atlas_minimum-bug-processing-layout.qgz --LAYOUT=v1_layout_atlas --OUTPUT=/tmp/atlas1.pdf
```

In both cases, it complains about not finding the layout from it name

```
----------------
Inputs
----------------

COVERAGE_LAYER:	/home/thomasg/own-projects/sample-qgis-server/projects/ne_10m_admin_0_countries.shp
LAYOUT:	v1_layout_atlas
OUTPUT:	/tmp/atlas1.pdf
project:	/home/thomasg/own-projects/sample-qgis-server/projects/atlas_minimum-bug-processing-layout.qgz


Cannot find layout with name "v1_layout_atlas"
ERROR:	Cannot find layout with name "v1_layout_atlas"
```

I've tested with and without specifying COVERAGE_LAYER as I was not sure if it was mandatory.

The problem is that the atlas layout name exists and has been activated to support atlas. I'm able to run manually the same processing algorithm within my QGIS project with the same layout and with QGIS Python console.

Issue posted due to feedback on Twitter e.g https://twitter.com/nyalldawson/status/1407112648949309442

You will find attached the standalone sample to reproduce. Tell me if you are able to reproduce and if you do not encounter any issue when opening the project.

[atlas_minimum-bug-processing-layout.zip](https://github.com/qgis/QGIS/files/6689952/atlas_minimum-bug-processing-layout.zip)

**QGIS and OS versions**

```QGIS version
3.16.3-Hannover
QGIS code revision
94ac9f21b8
Compiled against Qt
5.9.5
Running against Qt
5.9.5
Compiled against GDAL/OGR
2.2.3
Running against GDAL/OGR
2.2.3
Compiled against GEOS
3.6.2-CAPI-1.10.2
Running against GEOS
3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite
3.22.0
Running against SQLite
3.22.0
PostgreSQL Client Version
10.15 (Ubuntu 10.15-0ubuntu0.18.04.1)
SpatiaLite Version
4.3.0a
QWT Version
6.1.3
QScintilla2 Version
2.10.2
PROJ.4 Version
493
OS Version
Ubuntu 18.04.5 LTS
Active python plugins
qgisnetworklogger; 
db_manager; 
processing
```

**Comment by nyalldawson** [comment]
This :

     --project=/home/thomasg/own-projects/sample-qgis-server/projects/atlas_minimum-bug-processing-layout.qgz 

should be:

     --project_path=/home/thomasg/own-projects/sample-qgis-server/projects/atlas_minimum-bug-processing-layout.qgz

**Comment by ThomasG77** [comment]
Thanks you so much. Never too late make errors...
