### ISSUE TITLE
QGIS crash with open 3D-View and lidar-Data

### ISSUE THREAD

**Issue by PeterDrexel** [qgis/QGIS#43832]
QGIS
(QGIS Info **QGIS Version: 3.20.0-Odense QGIS** code revision: decaadbb31 Compiled against Qt: 5.15.2 Running against Qt:  5.15.2 Compiled against GDAL: 3.3.0 Running against GDAL: 3.3.0)
on **Windows 10 64bit**
(System Info CPU Type: x86_64 Kernel Type: winnt Kernel Version: 10.0.17763)
with **clean profile**:

Loading a laz-File https://drive.cnv.at/index.php/s/DsDARtCfrsfHFpa (drag and drop, wait until the ept_500_-36000_225000-Folder and ...files are created in the background) , open a 3D-view an pan/zoom around a little bit results in a **Uh-oh!**

Crash ID: fc9e3bbe2456a2431136a95cc877671793a66a34
Stack Trace
Qt3DCore::QNode::setEnabled :
QgsPointCloudLayer3DRenderer::writeXml :
Qgs3DMapScene::onFrameTriggered :
QObject::qt_static_metacall :
Qt3DLogic::QFrameAction::triggered :
Qt3DLogic::QFrameAction::onTriggered :
Qt3DCore::QBackendNodePrivate::q_func :
Qt3DCore::QAspectManager::processFrame :
Qt3DCore::QAspectManager::exitSimulationLoop :
QObject::qt_static_metacall :
QUnifiedTimer::setSlowdownFactor :
QAbstractAnimation::setCurrentTime :
QUnifiedTimer::updateAnimationTimers :
QUnifiedTimer::updateAnimationTimers :
QAnimationDriver::advance :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32Private::sendTimerEvent :
QEventDispatcherWin32::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS-Version 3.20.0-Odense QGIS-Codeversion decaadbb31
Qt-Version 5.15.2
Python-Version 3.9.5
GDAL-Version 3.3.0
PROJ-Version 8.0.1
EPSG-Registraturdatenbankversion v10.018 (2021-04-02)
GEOS-Version 3.9.1-CAPI-1.14.2
SQLite-Version 3.35.2
PDAL-Versio 2.3.0
PostgreSQL-Client-Version 13.0
SpatiaLite-Version 5.0.1
QWT-Version 6.1.3
QScintilla2-Version 2.11.5
BS-Version Windows 10 Version 1809

Aktive Python-Erweiterungen
db_manager
MetaSearch
processing

Peter

**Comment by gioman** [comment]
No crash under master/linux.

**Comment by wonder-sk** [comment]
I believe this should be fixed in QGIS 3.24 by https://github.com/qgis/QGIS/pull/47146 - please reopen if not...
