### ISSUE TITLE
Qgis / Oracle / Tnsname

### ISSUE THREAD

**Issue by AlainANTOCI** [qgis/QGIS#43833]
Hi,

I try to connect QGis with Oracle without host and port like sqlplus User/Password@instance comand ? Is it possible with Qgis, oracle work fine on my computers, I try with client 11 and server 11 and now with client 19 and server 19.

Thanks.

**Comment by gioman** [comment]
@AlainANTOCI is this a question? a statement? a bug report? thanks.

**Comment by gioman** [comment]
If is a bug report use the correct link and fill all the requested infos. 

https://github.com/qgis/QGIS/issues/new?assignees=&labels=Bug&template=10_bug_report.md&title=
