### ISSUE TITLE
Incorrect CRS conversion 

### ISSUE THREAD

**Issue by tschmetzer** [qgis/QGIS#43836]
When trying to use the processing algorithm "Clip Raster by Mask Layer" with a mask layer CRS being of type WGS84 pseudo-Mercator (EPSG:3857) and a raster CRS being of type World_Mollweide - Projected (ESRI:54009) then there seems to be a mismatch with the borders at the moment of projection. The WGS84 pseudo-Mercator (EPSG:3857) is used in order to easily define the sunbelt region between 40°N and 40°S. 
I don't know if I am doing something completely wrong and hope this really is a bug report and not a bad user misunderstanding (otherwise I will put this question somewhere else). But my expectation is that the borders of the two layers with even different CRSes do coarsely end up at the same geological locations. Yet some huge areas are left out (green areas within the blue circles).

![grafik](https://user-images.githubusercontent.com/67278094/122903292-8d36fb80-d34f-11eb-8604-3e325f4f7564.png)

Steps to reproduce:
1. Load the vector layer [sunbelt_region.zip](https://github.com/qgis/QGIS/files/6693229/sunbelt_region.zip) and the raster layer [GHS_POP_E2015_GLOBE_R2019A_54009_1K.zip](https://cidportal.jrc.ec.europa.eu/ftp/jrc-opendata/GHSL/GHS_POP_MT_GLOBE_R2019A/GHS_POP_E2015_GLOBE_R2019A_54009_1K/V1-0/GHS_POP_E2015_GLOBE_R2019A_54009_1K_V1_0.zip) into the Layers list. For better visualisation you may want to make the vector layer half transparent and add XYZ map tiles.
![grafik](https://user-images.githubusercontent.com/67278094/122898651-5828aa00-d34b-11eb-97ee-b288e3b6287a.png)

2. Call the processing algorithm "Clip Raster by Mask Layer" and select the two layers with default options
![grafik](https://user-images.githubusercontent.com/67278094/122899367-10565280-d34c-11eb-9f84-3e294870c094.png)

3. To get the same visualisation select "Display no data as" and select a color
![grafik](https://user-images.githubusercontent.com/67278094/122908552-8959a800-d354-11eb-9b17-26542df181f4.png)

Even if I change the mask layer to CRS World_Mollweide in order to have mask layer and raster layer in accordance with each other nothing changes
![grafik](https://user-images.githubusercontent.com/67278094/122912720-ee170180-d358-11eb-9cb7-db2f47cf057e.png)

It becomes clearer why if I **change the Project CRS to World_Mollweide** and see that the mask layer _sunbelt_region_ and _sunbelt_region_mollweide_ don't seem to be projected (correctly?) onto the project or destination CRS:
![grafik](https://user-images.githubusercontent.com/67278094/122910934-0f76ee00-d357-11eb-82e7-bcc6017b952d.png)

I don't know, maybe the projection/conversion/transformation I am expecting/missing here would be a feature or am I totally on the wrong path?

Regarding the QGIS version I am using:
QGIS version | 3.18.3-Zürich | QGIS code revision | 735cc85be9
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | GroupStats; latlontools; nominatim; QuickOSM; db_manager; processing

**Comment by gioman** [comment]
@tschmetzer seems to work as expected here on master/Linux:

![image](https://user-images.githubusercontent.com/1951107/122975151-f6883000-d38a-11eb-9810-ded12ad39d5d.png)

I think is totally expected to get such type of distortion the moment you reproject a layer into a completely different CRS.

**Comment by tschmetzer** [comment]
So I understand it's owed to the current implementation state. I will try and probably  suggest a workaround for my situation  tomorrow.

**Comment by gioman** [comment]
> So I understand it's owed to the current implementation state. I will try and probably  suggest a workaround for my situation  tomorrow.

It is how projections work.

**Comment by tschmetzer** [comment]
> 
> 
> > So I understand it's owed to the current implementation state. I will try and probably  suggest a workaround for my situation  tomorrow.
> 
> It is how projections work.

Well, the question is how projections should be working and how they should be implemented. The current implementation seems to be basic. Again my personal expectation would be that the distortion/displacement is taken into account along the respective lines. Yet when thinking about how this could be implemented it gets really tricky as additional points would need to be inserted in order to represent the shift caused by the projection of a line.

**Comment by tschmetzer** [comment]
> > > So I understand it's owed to the current implementation state. I will try and probably  suggest a workaround for my situation  tomorrow.
> > 
> > 
> > It is how projections work.
> 
> Well, the question is how projections should be working and how they should be implemented. The current implementation seems to be basic. Again my personal expectation would be that the distortion/displacement is taken into account along the respective lines. Yet when thinking about how this could be implemented it gets really tricky as additional points would need to be inserted (e.g. densified) or represented by a Bézier curve in order to represent the shift caused by the projection of a line.

I am currently using this workaround:
https://gis.stackexchange.com/questions/402122/creating-belt-area-using-only-certain-longitudes-but-containing-all-latitudes

As this is not considered bug with regard to what is expected by the deveolopers I suggest to relabel this a feature request named "Automatically convert projected objects". We would need to think about how this feature should be designed and to what extent it should be applicable to a layers' objects.

**Comment by alexbruy** [comment]
Isn't it a data problem then? And IMHO it is a user responsibility to add more vertices whenever there are only start and end points in the segment.

You can easily add more points using corresponding Processing tools. Also it is possible to create a model which will perform both operations at once. I'd say it is not bug and won't fix.

**Comment by gioman** [comment]
> Isn't it a data problem then? And IMHO it is a user responsibility to add more vertices whenever there are only start and end points in the segment.

agree
