### ISSUE TITLE
GRASS not working in Processing/QGIS

### ISSUE THREAD

**Issue by GisUsers** [qgis/QGIS#43844]
After performing a fresh installation of QGIS on a PC running Windows 10 Pro using the new OSGeo4W v2 Network Installer:

- GRASS 7.8.5 is correctly installed but not working within QGIS (GRASS Processing tools are available but fail executing);
- No shortcut(s) "with GRASS" created;
- qgis-bin-g7.exe is not present in the installation directory.

qgis-grass-plugin is installed but of course unavailable within QGIS.
qgis-grass-plugin7 is not installed as it is unavailable in the installer/repository, which I think is the key issue.

Tested on several PCs
Tested both Express and Advanced Install
Tested with both QGIS 3.16 and 3.20 installation

**Comment by nicogodet** [comment]
See https://trac.osgeo.org/osgeo4w/ticket/665 about "with GRASS" shortcut and .exe

Regarding GRASS processing tools, could paste the error ?

On my side, GRASS is working fine with new OSGeo4W v2 Network Installer.

**Comment by nicogodet** [comment]
All 3 installed ?
![image](https://user-images.githubusercontent.com/39594821/122949869-4c091080-d37c-11eb-8fd9-d1c19f5db262.png)

Did you check in `C:\OSGeo4W\apps\qgis\plugins\` if you could find these dll ?

**Comment by GisUsers** [comment]
All 3 installed.
And, yes, the dlls are there.

![20210622162429](https://user-images.githubusercontent.com/61540606/122950508-ccc80c80-d37c-11eb-8ddc-74976ad7a39c.png)

**Comment by nicogodet** [comment]
It seems to be a local issue but on all your computers 😄 
Enterprise policy ? Antivirus ?

Could you try the MSI instead of network installer ?

**Comment by nicogodet** [comment]
And also, clean profile ? (you said fresh install I know)

**Comment by GisUsers** [comment]
No Enterprise policy, no 3rd party antivirus and clean profile.
On 3 different machines!
I just tested the 3.20 MSI on one of the PCs and I have the same issue.
It behaves exactly as when if you run the qgis-bin.exe instead of the qgis-ltr-bin-g7.exe (if it makes sense)

**Comment by gioman** [comment]
> GRASS 7.8.5 is correctly installed but not working within QGIS (GRASS Processing tools are available but fail executing);

@GisUsers Just did an update of 3.16 and 3.20 with the new osgro4w installer. There are no more "with GRASS" shortcuts, but now GRASS tools in Processing seems to work (and produce results) as expected. Just tested here.

**Comment by jef-n** [comment]
> @GisUsers Just did an update of 3.16 and 3.20 with the new osgro4w installer. There are no more "with GRASS" shortcuts, but now GRASS tools in Processing seems to work (and produce results) as expected. Just tested here.

https://trac.osgeo.org/osgeo4w/ticket/665

**Comment by GisUsers** [comment]
Confirmed!
Just updated QGIS (and GRASS plugins) to 3.16.8-2 and 3.20.0-2 using OSGeo4W v2 Network Installer.
Happy to report that GRASS tools in Processing seem to work as expected (both LTR and RC).
Thanks @gioman for the input and kudos to our great devs for the quick fix.
