### ISSUE TITLE
Point Cloud layer configuration window is not fully shown

### ISSUE THREAD

**Issue by Mario-F-F** [qgis/QGIS#43845]
**Describe the bug**
Point Cloud layer configuration window is not fully shown on some screen configurations. Bottom controls are not accesible.

**How to Reproduce**

Computer with 1366x768 screen. 
Run QGIS
Load point cloud data
Open layer configuration

![imagen](https://user-images.githubusercontent.com/10926064/122941041-4c51dd80-d375-11eb-9f09-bec2e7217b38.png)

(layer configuration window cannot be reduced)

**QGIS and OS versions**

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

</head><body>

Versión de QGIS | 3.20.0-Odense | Revisión del código de QGIS | decaadbb31
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.0
PROJ version | 8.0.1
EPSG Registry database version | v10.018 (2021-04-02)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2004
  |   |   |  
Active Python plugins | DigitizingToolsGroupStatsmmqgisprocessing_rprofiletoolshapetoolsSpreadsheetLayersvaluetoolViewshedAnalysisdb_managerMetaSearchprocessing

</body></html>

**Additional context**

N/A

**Comment by gioman** [comment]
> Computer with 1366x768 screen.

it is increasingly harder to use QGIS on screens with such resolution.

**Comment by uclaros** [comment]
Old laptops with 1366x768 displays are still widely used and should be supported. We should set a minimum resolution policy and make sure all new gui stuff comply to it.

**Comment by Pedro-Murteira** [comment]
This issue is still valid on QGIS 3.22.4 and 3.24.0.

**Comment by alexbruy** [comment]
Duplicates #43276
