### ISSUE TITLE
QGIS 3.20 / Oracle

### ISSUE THREAD

**Issue by AlainANTOCI** [qgis/QGIS#43843]
I can't create a connection to Oracle with QGIS 3.20, work with 3.16 and 3.18. My oracle version is 19c client (32 bits), server (64 bits).
with 3.16 or 3.18 connection with database, server and port work (but not with only database) with 3.20 nothing.

![tns](https://user-images.githubusercontent.com/86290850/122931221-fa0cbe80-d36c-11eb-87d0-759c5ae3b97b.jpg)
![connect](https://user-images.githubusercontent.com/86290850/122931223-faa55500-d36c-11eb-98f8-ddd1795ee4f7.jpg)
![error](https://user-images.githubusercontent.com/86290850/122931228-fbd68200-d36c-11eb-93a5-295ca5f3992b.jpg)

**Comment by troopa81** [comment]
Please attach a screenshot of your connexion information dialog. 

If it's related to #43833, you need to leave the host and port blank to use the one described in tnsnames.ora file

**Comment by troopa81** [comment]
Could you post the content of the log messages ?

**Comment by AlainANTOCI** [comment]
Where I can find the log messages ?

**Comment by troopa81** [comment]
![messages](https://user-images.githubusercontent.com/14358135/122947675-9f7a5f00-d37a-11eb-9b70-2ec6b0de5872.png)

**Comment by AlainANTOCI** [comment]
The two message I have :
![Sans titre 4](https://user-images.githubusercontent.com/86290850/122951496-9ccd3900-d37d-11eb-97d0-85a198683087.jpg)
![Sans titre 2](https://user-images.githubusercontent.com/86290850/122951499-9d65cf80-d37d-11eb-833c-5e579791ecda.jpg)

**Comment by troopa81** [comment]
Could you try to set the host (srv-bdd) and port (1521) in the connexion dialog, see if it works.

Where is your tnsnames.ora file on disk?

**Comment by AlainANTOCI** [comment]
With host = srv-bdd and port = 1521, It does not work.

tnsname is in D:\app\client\Alain\product\19.0.0\client_1\network\admin

sqlplus MSAT_ADM/MSAT_ADM@MSAT53 works fine and ODBC connection works and oledb (ADO) connection works

srv-bdd is on server 2019, and qgis on windows 10 21H1

**Comment by thomparker** [comment]
Does QGIS for Windows use the GDAL library packaged with OSGeo4W for Oracle connections? I have enabled the gdal-oracle and qgis-oracle-provider packages, but also cannot connect. In the OSGeo4W shell I tried:

ogrinfo OCI:user/password@host:1521/database:SCHEMA.TABLE
and I got:

ERROR 1: in <unnamed>
ERROR 1: in <unnamed>
FAILURE
Unable to open datasource `OCI:user/password@host:1521/database:SCHEMA.TABLE' with the following drivers.

**Comment by troopa81** [comment]
> Does QGIS for Windows use the GDAL library packaged with OSGeo4W for Oracle connections?

No, QGIS has its own driver. You need to install the oci library but if you see the oracle provider from the explorer, I'm almost certain it's installed. 

It looks like an issue specifc to Windows because everything looks fine on Linux. I'll try to check on Window soon

**Comment by aetor** [comment]
Hello, Her I have the same problem. An Oracle connection, that worked in Qgis 3.18, is not working in the newe 3.20 version?  I am sure that all the settings are right!  I did not have ever had this problem by an upgrade!

**Comment by thomparker** [comment]
> It looks like an issue specifc to Windows because everything looks fine on Linux. I'll try to check on Window soon

I have a suspicion this is related to the new OSGeo4W installer. It didn't work when I tried the test verison of the installer and that would have been prior to 3.20 (possibly 3.18?), but put it down to it being a beta and forgot to report. My understanding is that 3.20 is now packaged using this new version by default.

**Comment by aetor** [comment]
> > It looks like an issue specifc to Windows because everything looks fine on Linux. I'll try to check on Window soon
> 
> I have a suspicion this is related to the new OSGeo4W installer. It didn't work when I tried the test verison of the installer and that would have been prior to 3.20 (possibly 3.18?), but put it down to it being a beta and forgot to report. My understanding is that 3.20 is now packaged using this new version by default.
> 
> Update: It works if the contents of an Oracle Instant Client is copied into the \bin\ folder, so perhaps some dlls are missing?

Can you tell wich DLL I should copy too what folder?

**Comment by troopa81** [comment]
> Can you tell wich DLL I should copy too what folder?

Did you have the `qgis-oracle-provider` package installed from Osgeo4W installer ? I tried this morning and the oci library is correctly installed with this package.

On the other side, the `qgis-oracle-provider` package is not installed when installing qgis package with O4W V2 installer. Is it normal @jef-n ? It seems to me that it was the case in the past

**Comment by jef-n** [comment]
@troopa81 yes, qgis-full includes it, but it's optional for qgis.

**Comment by troopa81** [comment]
@jef-n OK, thanks for the details

**Comment by aetor** [comment]
I tried it all... No connection... 

I someone can tell me step by step how too solve it!  I will be happy

**Comment by thomparker** [comment]
After further investigation I did the following. I installed the oci and qgis-oracle-provider packages via OSGeo4W setup.

Then I removed the oci.dll from my QGIS install. For me that is C:\OSGeo4W\bin as this is an Advanced install.

Then I added my Oracle Client to the PATH Environment variable (under Settings > Options). I copied what was already set and added the Oracle path to the beginning) :
![qgis-environment](https://user-images.githubusercontent.com/29947968/123621126-cf09eb00-d802-11eb-9385-25dec41be65e.PNG)
It then worked after restarting QGIS.

It seems like at a minimum these dlls are needed: oci.dll, oraociicus19.dll and oraons.dll, but the oci package only includes the first.

**Comment by aetor** [comment]
> After further investigation I did the following. I installed the oci and qgis-oracle-provider packages via OSGeo4W setup.
> 
> Then I removed the oci.dll from my QGIS install. For me that is C:\OSGeo4W\bin as this is an Advanced install.
> 
> Then I added my Oracle Client to the PATH Environment variable (under Settings > Options > System). I copied what was already set and added the Oracle path to the beginning) :
> ![qgis-environment](https://user-images.githubusercontent.com/29947968/123621126-cf09eb00-d802-11eb-9385-25dec41be65e.PNG)
> It then worked after restarting QGIS.
> 
> It seems like at a minimum these dlls are needed: oci.dll, oraociicus19.dll and oraons.dll, but the oci package only includes the first.

settings - > options -> system is not there in Qgis, or do you mean  Extra-> Options - System?  

I removed the dll but I con not copy the Paths settings!
the original PATH  = F:\Prog\Oracle\Oracle122_64bit    So what do I have to type.... 

I tried but it did not work.

I am also using autocad on same pc with oracle connection, so I don't want to mesh up things

**Comment by aetor** [comment]
with all due respect, this call is closed, but for foreign users its difficult to understand what they should do!  I am dutch, I try to fix th issue..

**Comment by aetor** [comment]
@jef-n /OSGeo4W@5b933bd is not working in windows 10!

**Comment by jef-n** [comment]
> @jef-n /OSGeo4W@5b933bd is not working in windows 10!

But you did upgrade to oci-19.11-1?

**Comment by aetor** [comment]
> > @jef-n /OSGeo4W@5b933bd is not working in windows 10!
> 
> But you did upgrade to oci-19.11-1?

No, I think that other Oracle connection (autocad and qgis 3.18) are not working anymore when i will install that client. Isn't it possible to build a installer with the right settings?

**Comment by jef-n** [comment]
You could update using the osgeo4w installer

**Comment by aetor** [comment]
> You could update using the osgeo4w installer

did that... not working!

**Comment by jef-n** [comment]
> did that... not working!

So you did use https://download.osgeo.org/osgeo4w/v2/osgeo4w-setup.exe (aka OSGeo4W installer).  And it did upgrade to  `oci-19.11-1`? So you have `oci.dll`, `oraociicus19.dll` and `oraons.dll` in `%OSGEO4W_ROOT%\bin` now?  And it still doesn't work and nothing changed?

**Comment by aetor** [comment]
> > did that... not working!
> 
> So you did use https://download.osgeo.org/osgeo4w/v2/osgeo4w-setup.exe (aka OSGeo4W installer). And it did upgrade to `oci-19.11-1`? So you have `oci.dll`, `oraociicus19.dll` and `oraons.dll` in `%OSGEO4W_ROOT%\bin` now? And it still doesn't work and nothing changed?

I did it like you told here.. still I can NOT log in, into the oracle database :-(

**Comment by aetor** [comment]
I wil stop to try to use 3.20, because my other older version are now corrupt!

**Comment by jef-n** [comment]
> my other older version are now corrupt!

Why?

**Comment by aetor** [comment]
> > my other older version are now corrupt!
> 
> Why?

I Set system variable in settings, and so I lost all Plugins.  I removed the settings and now the old version are working well. 3,20 wil still not connect with Oracle!  I give up.

**Comment by fguiet** [comment]
Hi,

Same issue here.

Everything was working with version 3.14 then I installed version 3.18 nad version 3.20 with no luck.

I managed to make it work by copying all the files of my Oracle Instant Client x64 in the QGIS Bin folder (C:\Program Files\QGIS 3.20.0\bin).

You must use Oracle Instant Client x64 and not 32 bits version otherwise it will not work

My two cents,

**Comment by aetor** [comment]
> Hi,
> 
> Same issue here.
> 
> Everything was working with version 3.14 then I installed version 3.18 nad version 3.20 with no luck.
> 
> I managed to make it work by copying all the files of my Oracle Instant Client x64 in the QGIS Bin folder (C:\Program Files\QGIS 3.20.0\bin).
> 
> You must use Oracle Instant Client x64 and not 32 bits version otherwise it will not work
> 
> My two cents,

this solution Is not working!

**Comment by fguiet** [comment]
> 
> 
> > Hi,
> > Same issue here.
> > Everything was working with version 3.14 then I installed version 3.18 nad version 3.20 with no luck.
> > I managed to make it work by copying all the files of my Oracle Instant Client x64 in the QGIS Bin folder (C:\Program Files\QGIS 3.20.0\bin).
> > You must use Oracle Instant Client x64 and not 32 bits version otherwise it will not work
> > My two cents,
> 
> this solution Is not working!

Sorry, but I can tell you that it did work for me...
