### ISSUE TITLE
MSI installs don't create system-wide icons

### ISSUE THREAD

**Issue by teknowledgist** [qgis/QGIS#43850]
**Describe the bug**
Start Menu and Desktop icons are created only within the installing user's profile.  Subsequent users of the computer are highly unlikely to even know that QGIS is installed, let alone know where/how to start it.

**How to Reproduce**

1. run `msiexec.exe /i QGIS-OSGeo4W-3.20.0-2.msi /qn /norestart` in an elevated console.
2. Check the path for the `QGIS 3.20.0` folder on the desktop to see that it is within the current (or installing) user's profile.
3. Find an icon for `QGIS Desktop 3.20.0` in the Start Menu, right-click and select *Open File Location* and notice it is within the user's profile.
4. Check the path `C:\Users\Public\Desktop` to see that no other users will have a QGIS 3.20 icon on the desktop.
5. Check the path `C:\ProgramData\Microsoft\Windows\Start Menu\Programs\` to see that no other users will have QGIS 3.20 icons in the Start Menu.

**QGIS and OS versions**

QGIS v3.20.0 is what I'm working with, but apparently, [this is present in the earlier MSI too](https://github.com/qgis/QGIS/issues/42574).  

On Windows 10 Enterprise (20H2)

**Additional note**
It appears that the uninstall doesn't remove the Start Menu or Desktop icons even if the installing user is the one uninstalling.

**Comment by roya0045** [comment]
#43819
