### ISSUE TITLE
QGIS Batch Mode Populating Form are producing gaps between rows

### ISSUE THREAD

**Issue by jorgepsantos2002** [qgis/QGIS#43869]
**Describe the bug**

QGIS 3.16 has strange behavior in batch processing forms. Instead of aligning each input raster file corresponding to a band, the algorithm is reading the files and leaving unnecessary spaces. This must be a bug as everything was working during the last LTR version which was 3.10.

**How to Reproduce**

Please see this screencast:
https://drive.google.com/file/d/1FwFKjdLowG1WWK-cuTx_rOoRAm882IdW/view?usp=sharing

**QGIS and OS versions**

Versão do QGIS
3.16.8-Hannover
Código da versão do QGIS
8c50902ea4
Compilado sobre Qt
5.11.2
Rodando sobre Qt
5.11.2
Compilado sobre GDAL/OGR
3.1.4
Rodando sobre GDAL/OGR
3.1.4
Compilado sobre GEOS
3.8.1-CAPI-1.13.3
Rodando sobre GEOS
3.8.1-CAPI-1.13.3
Compilado no SQLite
3.29.0
Executando contra SQLite
3.29.0
Versão do cliente PostgreSQL
11.5
Versão SpatiaLite
4.3.0
Versão do QWT
6.1.3
Versão QScintilla2
2.10.8
Compilado com PROJ
6.3.2
Em execução com PROJ
Rel. 6.3.2, May 1st, 2020
Versão SO
Windows 10 (10.0)
Ativar complementos python
HCMGIS; 
kmltools; 
quick_map_services; 
SpreadsheetLayers; 
db_manager; 
MetaSearch; 
processing

**Comment by gioman** [comment]
See also https://github.com/qgis/QGIS/issues/43875

@jorgepsantos2002 can you share the model?

**Comment by jorgepsantos2002** [comment]
> See also #43875
> 
> @jorgepsantos2002 can you share the model?

Yes, I can. Please [see this attachment](https://drive.google.com/file/d/1ohXvtfFED7L25EK_kuo9Cg0zNsnZWjGJ/view?usp=sharing).

**Comment by gioman** [comment]
> Yes, I can. Please [see this attachment](https://drive.google.com/file/d/1ohXvtfFED7L25EK_kuo9Cg0zNsnZWjGJ/view?usp=sharing).

yep, confirmed also on master/linux.
