### ISSUE TITLE
AccessControl implementation and layergroups

### ISSUE THREAD

**Issue by steelraiden** [qgis/QGIS#43879]
**Describe the bug**
Hi I am trying to implement a QgsAccessControlFilter plugin in qgis server that responds to a GetCapabilities request.

The layerPermissions callback is called as expected, but it works on layers only: the callback doesn't seem to take care of layer groups in the GetCapabilities request. 

I already posted a question on qgis-user-list and it seems that the filter current implementation works on layers only (not 
groups). 

Although it can be very helpful if the filter could take care of the layer groups too, if a layer group has 0 layers because none of the sublayers is readable by the authenticated user, or simply because it has 0 sublayers in the project, it still remains in the GetCapabilities response.

How can I get rid of a layer group without sublayers in a GetCapabilities response?

**QGIS and OS versions**
QGIS version: 3.18
OS: linux debian 10

**Comment by gioman** [comment]
> How can I get rid of a layer group without sublayers in a GetCapabilities response?

@steelraiden questions must be asked in the users or developers mailing lists. Thanks!
