### ISSUE TITLE
Qgis 3.20 Python 3.9 No setuptools installed by default

### ISSUE THREAD

**Issue by nuipek** [qgis/QGIS#43870]
Hi, I'm sorry for selecting the bug tag when it should be feature.
When I go to install packages with python -m pip of type tar indicates that setuptools is not installed, I know it is a legacy installation system but there are still many packages that are in that format, it could be included for compatibility?

c:\Program Files\QGIS 3.20.0\apps\Python39>python -m pip install deepdiff

![2021-06-23_13h29_54](https://user-images.githubusercontent.com/25007278/123089426-369cf080-d427-11eb-9b48-e1fee24e1bea.png)

**Comment by gioman** [comment]
@nuipek python3-setuptools is apparently not a dependency of 3.20 installation with the new osgeo4w installer. If installed manually you get rid of the error. I guess this should be moved to the osgeo4w tracker(?) @jef-n
