### ISSUE TITLE
Wrong results with Intersection process

### ISSUE THREAD

**Issue by CamiloCorredor** [qgis/QGIS#43892]
I've processed data with the intersection algorithm for data that correspond to polygons. 

The result of that intersection isn't complete, certain zones of the polygons are skipped, by  reasons undetermined in the log file. 

The result of execution shoulded create a polygon between de red line a black line, but this zone was skipped.

![image](https://user-images.githubusercontent.com/70957642/123193881-227ae280-d46b-11eb-8d9d-21e2d13c637f.png)

**Comment by gioman** [comment]
> The result of execution shoulded create a polygon between de red line a black line, but this zone was skipped.

@CamiloCorredor please specify what intersection tool are you using (the QGIS native? GRASS's? SAGA's?). Have you checked if your inputs have geometry errors? Please also attach your data.
