### ISSUE TITLE
Mise à jour de l'extension Cadastre

### ISSUE THREAD

**Issue by Ckeller05** [qgis/QGIS#43898]
Bonjour,

J'ai mis à jour le plugin sur la version de QGIS 3.4.15. Mais je ne peux plus l'utiliser à ce jour. 
Un message d'erreur s'affiche, serait-il possible d'avoir à nouveau accès à cette extension, très utile pour mon travail ?

Je vous joins une capture du message d'erreur :
![probleme extension cadastre](https://user-images.githubusercontent.com/86400970/123219750-87ffbb00-d4cd-11eb-9673-4d5d026c90c3.JPG)

En vous remerciant,

Chloé

**Comment by Gustry** [comment]
Bonjour,

En effet, il ne faut pas ouvrir des tickets pour les extensions ici. QGIS n'est pas responsable des extensions.

Ceci dit, vous pouvez mettre à jour sur la dernière version 1.12.1 que je viens de publier à l'instant qui corrige le chargement sur QGIS < 3.10

**Comment by jef-n** [comment]
Und bitte auf Englisch, sonst verstehen das nicht alle.
