### ISSUE TITLE
Plugin Manager Crashes QGIS

### ISSUE THREAD

**Issue by amgiss** [qgis/QGIS#43893]
**Describe the bug**

Plugin Manager becomes unresponsive and crashes QGIS

**How to Reproduce**

1. Go to 'Plugins Menu..'
2. Click on '.Manage and Install Plugins..'
4. Plugin Manager windows goes to '(Not Responding)'...
5. QGIS eventually crashes, or closing the non responsive 'Plugin Manager' windows presents "qgis-bin.exe is not responding" and QGIS crashes

**QGIS and OS versions**

QGIS version
3.20.0-Odense
QGIS code revision
decaadbb31
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.0
PROJ version
8.0.1
EPSG Registry database version
v10.018 (2021-04-02)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

**Additional context**

Clean install via OSGeo4W with prior version removed.

Tried creating a new default profile - same thing happens

Stack references vcruntime?

Crash Report:

**Stack Trace**
<pre>
RaiseException :
_CxxThrowException throw.cpp:75
qBadAlloc :
QCoreApplication::translate :
QHashData::rehash :
QAccessibleCache::insert :
QAccessible::queryAccessibleInterface :
QAccessibleEvent::accessibleInterface :
QAccessible::updateAccessibility :
QLabel::setText :
QMessageBox::setText :
QMessageBox::informativeText :
QMessageBox::QMessageBox :
QMessageBox::showEvent :
QMessageBox::critical :
QgsRemoteEptPointCloudIndex::nodeData :
_CallSettingFrame_LookupContinuationIndex handlers.asm:98
__FrameHandler4::CxxCallCatchBlock frame.cpp:1367
RcConsolidateFrames :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**Stack**
>00: 0x7FFDFA674B20 RaiseException
>01: 0x7FFDF66E6190 _CxxThrowException
Parm: pExceptionObject = 0xBFF0000000000000 -> ?
Parm: pThrowInfo = 0xBFF0000000000000 -> ?
Local: magicNumber = 140727489659008
Local: parameters = ?
Local: pTI = 0x00000212E6B4C470 -> ?
Local: throwImageBase = 0x00007FF7661760B5 -> ?
Local: pWei = 0x00000212E6B4C470 -> ?
Local: ppWei = 0x00000212E6B4C470 -> 0x00000212E6B4C470 -> ?
Source: d:\agent\_work\2\s\src\vctools\crt\vcruntime\src\eh\throw.cpp:75
>02: 0x7FFDC2549A90 qBadAlloc
>03: 0x7FFDC27AEB50 QCoreApplication::translate
>04: 0x7FFDC2593030 QHashData::rehash
>05: 0x7FFDC3865390 QAccessibleCache::insert
>06: 0x7FFDC3863050 QAccessible::queryAccessibleInterface
>07: 0x7FFDC3861CF0 QAccessibleEvent::accessibleInterface
>08: 0x7FFDC3864A30 QAccessible::updateAccessibility
>09: 0x7FFDC3FD0E20 QLabel::setText
>10: 0x7FFDC40B4870 QMessageBox::setText
>11: 0x7FFDC40B2E50 QMessageBox::informativeText
>12: 0x7FFDC40B11A0 QMessageBox::QMessageBox
>13: 0x7FFDC40B4D30 QMessageBox::showEvent
>14: 0x7FFDC40B2500 QMessageBox::critical
>15: 0x7FFDC17C2490 QgsRemoteEptPointCloudIndex::nodeData
>16: 0x7FFDF6FC1060 _CallSettingFrame_LookupContinuationIndex
Source: d:\agent\_work\2\s\src\vctools\crt\vcruntime\src\eh\amd64\handlers.asm:98
>17: 0x7FFDF6FC25A0 __FrameHandler4::CxxCallCatchBlock
Parm: pExcept = 0xBFF0000000000000 -> ?
Local: continuationAddresses = ?
Local: TranslatedCatch = 20441059
Local: pForeignException = 0x000000FBFECF4AC0 -> ?
Local: rethrow = -19945696
Local: FrameInfo = ?
Local: HandlerSearchState = 20441059
Local: pSaveException = 0x000000FBFECF45C0 -> ?
Local: continuationAddress = 0x000000000010000F -> ?
Local: pEstablisherFrame = 0x000000000137E7E3 -> 140727489659008
Local: pSaveContext = 0x0000000000000002 -> ?
Local: pFrameInfo = 0x00007FFDFC9E0B66 -> ?
Local: handlerAddress = 0x00007FFDC118FBC7 -> ?
Local: FuncInfo = ?
Local: pContext = 0x000000000137E7E3 -> ?
Local: UnwindTryState = 20441059
Local: pThisException = 0x000000000137E7E3 -> ?
Source: d:\agent\_work\2\s\src\vctools\crt\vcruntime\src\eh\frame.cpp:1367
>18: 0x7FFDFCA51500 RcConsolidateFrames
>19: 0x7FFDC118FB50 QgsApplication::notify
>20: 0x7FFDC26F52C0 QCoreApplication::notifyInternal2
>21: 0x7FFDC3882950 QGuiApplicationPrivate::processMouseEvent
>22: 0x7FFDC386EC20 QWindowSystemInterface::sendWindowSystemEvents
>23: 0x7FFDC273E220 QEventDispatcherWin32::processEvents
>24: 0x7FFDADD90750 qt_plugin_query_metadata
>25: 0x7FFDC26F1620 QEventLoop::exec
>26: 0x7FFDC26F41F0 QCoreApplication::exec
>27: 0x7FFDC5B8B940 main
>28: 0x7FF7724050AE ?
>29: 0x7FF77240553A ?
>30: 0x7FFDFC8C7020 BaseThreadInitThunk
>31: 0x7FFDFCA02630 RtlUserThreadStart

**QGIS Info**
QGIS Version: 3.20.0-Odense
QGIS code revision: decaadbb31
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.0
Running against GDAL: 3.3.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

**Comment by gioman** [comment]
@amgiss please try with a new QGIS profile.

**Comment by amgiss** [comment]
I have tried a new profile and there is no change.

**Comment by gioman** [comment]
> I have tried a new profile and there is no change.

@amgiss have you tried on a different machine?

**Comment by amgiss** [comment]
I have tried other machines and it will work. Although I'm pretty sure I've had it fail at times.

I have noticed that when it does consistently fail on my main machine that it appears to be some type of memory leak. It just eats all available system memory until it eventually crashes.

**Comment by gioman** [comment]
> I have tried other machines and it will work

@amgiss so it seems is a local issue, if so there isn't much that can be done on this side probably.

**Comment by amgiss** [comment]
This seems to be the same as a previously reported issue. Has been happening since early 3.x - https://issues.qgis.org/issues/19526 appears to be exactly the same and is still open.

I can't see any resolutions for this problem anywhere.

Any suggestions how to further troubleshoot?

**Comment by amgiss** [comment]
Running the Plugin Manager - on Windows at least, appears to trigger a memory leak of some sort. Just running it will cause QGIS to become non-responsive and steadily consume enough memory to eventually crash qgis-bin.exe. 

There may well be a local environmental condition that is triggering this to happen (for me and others), but that condition shouldn't really be able to cause a memory leak unless there was something wrong with the plugin manager software package?

**Comment by amgiss** [comment]
This problem is not fixed with a New QGIS Profile, complete removal and reinstallation with the OSGeo4W installer - including delete AppData Local and Roaming QGIS directories. The standalone QGIS msi installer has the same problem.

The Plugin Manager will run only when running QGIS with "run as administrator" which is still using the regular user's QGIS profile directories. There is possibly some user profile environment differences or permission issue that are causing the issue but I haven't tracked it down.
