### ISSUE TITLE
QGis 3.20 doesn’t compile with a C++ 17 compliant compiler because of ‘register’ declarations

### ISSUE THREAD

**Issue by Veence** [qgis/QGIS#43903]
When trying to compile QGIS 3.20 from source, clang complains because of ‘register’ declarations in flex_qgssqlstatementlexer.cpp, flex_qgsexpressionlexer.cpp and flex_qgsmeshcalclexer.cpp.

e.g.:
`flex_qgssqlstatementlexer.cpp:1626:2: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
        register char *yy_cp = yyg->yy_c_buf_p;
`
I am going to add --std=c++14 to the command line to avoid these errors, but it would be worth fixing them, I think, especially since it seems a minor job (I was too lazy to figure out how the cpp files were generated from the corresponding .ll templates).

**Comment by m-kuhn** [comment]
Which version of flex are you using?
https://github.com/westes/flex/issues/132

**Comment by alexbruy** [comment]
Seems duplicates #43795
