### ISSUE TITLE
SVG Browser not working for North Arrows in 3.20.0

### ISSUE THREAD

**Issue by freeshrugsxd** [qgis/QGIS#43906]
**Describe the bug**

In a Print Layout: Picking an SVG from the SVG Browser does not change the North Arrow.

**How to Reproduce**

1. create and open Layout
2. add North Arrrow
3. go to North Arrow's item properties
4. pick any SVG in the SVG browser

**QGIS and OS versions**

|  | version |
|---|---|
| QGIS version | 3.20.0-Odense|
| QGIS code revision | decaadbb31|
| Qt version | 5.15.2|
| Python version | 3.9.5|
| GDAL/OGR version | 3.3.0|
| PROJ version | 8.0.1|
| EPSG Registry database version | v10.018 (2021-04-02)|
| GEOS version | 3.9.1-CAPI-1.14.2|
| SQLite version | 3.35.2|
| PDAL version | 2.3.0|
| PostgreSQL client version | 13.0|
| SpatiaLite version | 5.0.1|
| QWT version | 6.1.3|
| QScintilla2 version | 2.11.5|
| OS version | Windows 10 Version 2009|
| Active Python plugins | db_manager, MetaSearch, processing |

**Additional context**

It works in 3.16.8

**Comment by nicogodet** [comment]
Duplicate https://github.com/qgis/QGIS/issues/43802 ?

**Comment by freeshrugsxd** [comment]
yes. wow, didn't see that one. Case closed, thanks!
