### ISSUE TITLE
OAPIF URL with query parameters displays error after last page is fetched

### ISSUE THREAD

**Issue by komima** [qgis/QGIS#43905]
**Describe the bug**

Using OAPIF provider vector layer with an URL that contains query parameters makes an extra request after last page to an URL that only contains the original query parameters defined in the data source URL. This request fails and it displays an error-level message on the message bar with not-so-helpful message about invalid protocol.

![image](https://user-images.githubusercontent.com/58747243/123258018-9238ae00-d4fb-11eb-881b-bdce064600b0.png)

**How to Reproduce**

* Open dev tools and start recording network requests.
* Create a OAPIF vector layer with an URL that has query parameters using Python command `QgsProject.instance().addMapLayer(QgsVectorLayer("url='https://beta-paikkatieto.maanmittauslaitos.fi/terrain/features/v1?f=json' typename='quarry'", 'quarry', 'OAPIF'))`.
* Observe behavior:
  * Pages are fetched correctly with an URL that includes the query parameters, and features are displayed on the map.
  * Extra request is made after the last page with an URL containing only the query parameters given in data source URL.

![image](https://user-images.githubusercontent.com/58747243/123258098-a8466e80-d4fb-11eb-83e9-e96ffef43a13.png)

**Possible reason and fix**

https://github.com/qgis/QGIS/blob/master/src/providers/wfs/qgsoapifprovider.cpp#L724

Last page does not contain a link with `rel="next"`, and `itemsRequest.nextUrl()` is supposedly empty. The query parameters are appended to the (empty) URL anyway, and the while loop for paging continues using an URL having only the query parameters.

Possibly fixable by moving line 693 inside the while loop to the beginning after line 695, and removing the same operation from line 724? Start the while loop always by adding the parameters, so the loop exits properly after the last page.

**QGIS and OS versions**

Windows 10 with QGIS 3.16.8 using OSGeo4W v1 installer.

**Additional context**

Support for query parameters was added in https://github.com/qgis/QGIS/pull/38738.

**Comment by Joonalai** [comment]
I would be interested on fixing this.

**Comment by Joonalai** [comment]
I could reproduce this problem with QGIS 3.20.0 on Arch Linux.
