### ISSUE TITLE
Failure to load .gif into print composer

### ISSUE THREAD

**Issue by trackergps** [qgis/QGIS#43917]
**Describe the bug**
Can not load a gif file into print composer,   Gif works in 3.18 and a saved file from 3.18 loads correctly in 3.20.  

**How to Reproduce**

1. Go to Print composer.
2. Click on add a picture
3. Scroll down to picture stored in /bin directory(searched for it) under Raster image
4. See error   Just the red X as no image

**QGIS and OS versions**   New Ver 3.20

![Screenshot 2021-06-24 153923](https://user-images.githubusercontent.com/86445640/123341628-222e2600-d503-11eb-812e-d3e070d8ab93.jpg)
![Screenshot 2021-06-24 154521](https://user-images.githubusercontent.com/86445640/123341695-44c03f00-d503-11eb-8ff1-3fc169db0c79.jpg)
![A-north-clipart-dcrad9Rc9](https://user-images.githubusercontent.com/86445640/123341716-4db11080-d503-11eb-874a-a467c78528f9.gif)

QGIS version
3.20.0-Odense
QGIS code revision
decaadbb31
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.0
PROJ version
8.0.1
EPSG Registry database version
v10.018 (2021-04-02)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
ArcheoCAD
AzimuthDistanceCalculator
contour
CSMapMaker
latlontools
MemoryLayerSaver
mmqgis
parcel_plugin
profiletool
qgsAzimuth
db_manager
processing

**Additional context**

**Comment by nyalldawson** [comment]
Does it work if you manually edit the path and then change back? e.g. add an extra character and then remove

**Comment by trackergps** [comment]
Changed the file name, and then error message no file found,   then changed back and still doesn't work.  It also won't work on the other gif files i use in Print composer

**Comment by trackergps** [comment]
Thank you for responding

**Comment by nyalldawson** [comment]
Ping @3nids

**Comment by trackergps** [comment]
So,  I am somewhat of a rookie as I don't know python,    What should I do?   Is that a request for python?

**Comment by trackergps** [comment]
I think i understand that you passed this along

**Comment by 3nids** [comment]
This should have been fixed in #43805

**Comment by stuskier** [comment]
I am experiencing the same problem with 3.20: I am unable to add .jpg or .png files to a layout using Add Item > Add Picture > Raster Image...

The result is the dreaded red 'X', as shown here

![Capture](https://user-images.githubusercontent.com/12805900/125164979-c9d56600-e149-11eb-92b4-b7ec0e705629.PNG)

This problem does not occur at 3.18.3

**Comment by gioman** [comment]
> I am experiencing the same problem with 3.20

@stuskier try master, maybe the fix was late for 3.20.0 and it will be available only for 3.20.1

**Comment by nicogodet** [comment]
Fixed in 3.20.1
