### ISSUE TITLE
QGIS 3.20.1 crashes panning project/layer with labels enabled

### ISSUE THREAD

**Issue by Xeenych** [qgis/QGIS#43914]
QGIS crashed while scrolling my project.

Crash ID: 43e251103bdee17c157c916c820b2fa630d03c42

Stack Trace

initGEOS :
GEOSGeomTypeId_r :
pal::PointSet::offsetCurveByDistance :
pal::FeaturePart::createCurvedCandidatesAlongLine :
pal::FeaturePart::createCandidates :
pal::Pal::extract :
pal::Pal::extractProblem :
QgsLabelingEngine::solve :
QgsDefaultLabelingEngine::run :
QgsMapRendererJob::drawLabeling :
QgsMapRendererParallelJob::renderLabelsStatic :
QgsMapRendererCustomPainterJob::renderSynchronously :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.20.0-Odense
QGIS code revision: decaadbb31
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.0
Running against GDAL: 3.3.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by roya0045** [comment]
What labeling settings are you using?

**Comment by Xeenych** [comment]
![111](https://user-images.githubusercontent.com/11345848/123375586-b34bde00-d591-11eb-8f5d-7af3d5843f72.jpg)

**Comment by gioman** [comment]
@Xeenych can you attach a sample project+data we can use to replicate the crash?

**Comment by Xeenych** [comment]
Sorry. Can you wait for a 10 days? I'm travelling now.

**Comment by Xeenych** [comment]
Here is the project.
Pan to the SW an QGIS will crash
https://yadi.sk/d/tk0S8y73uvjf8A

**Comment by gioman** [comment]
>  Pan to the SW an QGIS will crash

@Xeenych no crash here on QGIS master on Ubuntu 20.04

**Comment by Xeenych** [comment]
Here is the video on Windows
https://yadi.sk/d/TWWWGFRDvfUu-Q

**Comment by gioman** [comment]
> Here is the video on Windows

@Xeenych yes, crash confirmed on 3.20 and Windows 10.

**Comment by gioman** [comment]
No crash with labels disabled.

**Comment by Xeenych** [comment]
3.20.1 crashes too, but without exception window

**Comment by nyalldawson** [comment]
This should be fixed in 3.20.3 -- can you retest?

**Comment by Xeenych** [comment]
In 3.20.3 it works fine
