### ISSUE TITLE
osgeo4w-setup does not work

### ISSUE THREAD

**Issue by ftrinco** [qgis/QGIS#43926]
osgeo4w-setup.exe did not work, I needed to download the standalone version

![image](https://user-images.githubusercontent.com/63117500/123429453-5bb36f80-d59d-11eb-860f-bba6d0515955.png)

**Comment by nicogodet** [comment]
Try on download.osgeo.org instead of norbit.de

**Comment by AlessioBarba** [comment]
Hi, I'm experiencing the same issue since a couple of days. No matter the mirror I choose, the download always freeze after a while (around the 5-20%). 
![image](https://user-images.githubusercontent.com/72660497/123432313-8962dd80-d5ca-11eb-92ad-ceb42605e5e1.png)

**Comment by gioman** [comment]
Must be reported in the osgeo4w tracker.
