### ISSUE TITLE
Vector Tile sprite URL is incorrectly interpreted when query parameters are present

### ISSUE THREAD

**Issue by wrass** [qgis/QGIS#43925]
Where the sprite URL provided by a Vector Tile style file contains query parameters, QGIS does not add the resolution or file extension to it correctly.  This results in HTTP 404 responses when QGIS attempts to retrieve the sprite.

For example, where access to a vector tile service is secured via API key, a sprite URL provided in the style may include a query parameter, e.g.:
`"sprite": "https://remote.server.address/vector/tile/service/styles?key=0123456789"`

QGIS treats this as a string and blindly appends a resolution and file extension, resulting in an incorrect URL:
`https://remote.server.address/vector/tile/service/styles?key=0123456789@2x.json`

The correct behaviour would be for QGIS to append these values to the path:
`https://remote.server.address/vector/tile/service/styles@2x.json?key=0123456789`

|  |  |
------|------
| QGIS version | 3.20.0-Odense |
| QGIS code revision | decaadbb31 |
| Qt version | 5.15.2 |
| Python version | 3.9.5 |
| GDAL/OGR version | 3.3.0 |
| PROJ version | 8.0.1 |
| EPSG Registry database version | v10.018 (2021-04-02) |
| GEOS version | 3.9.1-CAPI-1.14.2 |
| SQLite version | 3.35.2 |
| PDAL version | 2.3.0 |
| PostgreSQL client version | 13 |
| SpatiaLite version | 5.0.1 |
| QWT version | 6.1.3 |
| QScintilla2 version | 2.11.5 |
| OS version | Windows 10 Version 2009 |

**Comment by wrass** [comment]
Suggested fix (sorry, don't have a build environment set up to test).

Amend:
https://github.com/qgis/QGIS/blob/f14e098eb6e1fca7014a2a4439481dff7555a942/src/core/vectortile/qgsvectortilelayer.cpp#L427
to:
```
QUrl spriteUrl = QUrl( spriteUriBase );
spriteUrl.setPath( spriteUrl.path() + QStringLiteral( "%1.json" ).arg( resolution > 1 ? QStringLiteral( "@%1x" ).arg( resolution ) : QString() ) );
QNetworkRequest request = QNetworkRequest( spriteUrl );
```
Amend:
https://github.com/qgis/QGIS/blob/f14e098eb6e1fca7014a2a4439481dff7555a942/src/core/vectortile/qgsvectortilelayer.cpp#L438
to:
```
QUrl spriteUrl = QUrl( spriteUriBase );
spriteUrl.setPath( spriteUrl.path() + QStringLiteral( "%1.png" ).arg( resolution > 1 ? QStringLiteral( "@%1x" ).arg( resolution ) : QString() ) );
QNetworkRequest request = QNetworkRequest( spriteUrl );
```

**Comment by gioman** [comment]
> Amend:

@wrass could you submit the patch as  Pull Request?

**Comment by wrass** [comment]
@gioman, sure, please see #43928

I was hesitant about creating a PR as I don't have the right environment to build & test properly.
