### ISSUE TITLE
Merge vector layers algorithm only supports selecting one alg output

### ISSUE THREAD

**Issue by timlinux** [qgis/QGIS#43939]
When I use the Merge Vector Layers alg in modeller builder, I should be able to merge two or more alg inputs.

![image](https://user-images.githubusercontent.com/178003/123561010-d77c0a80-d79d-11eb-8d28-ac24adb0e07a.png)

Currently in mode:

* Value: Multiple inputs allowed
* Pre-calculated Value: Alg allowed
* Model Input: Single input allowed only
* Algorithm Ouput: Single input allowed only

QGIS version | 3.18.3-Zürich | QGIS code branch | Release 3.18
-- | -- | -- | --
Compiled against Qt | 5.15.2 | Running against Qt | 5.15.2
Compiled against GDAL/OGR | 3.2.2 | Running against GDAL/OGR | 3.2.2
Compiled against GEOS | 3.9.0-CAPI-1.16.2 | Running against GEOS | 3.9.0-CAPI-1.16.2
Compiled against SQLite | 3.34.1 | Running against SQLite | 3.34.1
PostgreSQL Client Version | 13.2 | SpatiaLite Version | 5.0.1
QWT Version | 6.1.5 | QScintilla2 Version | 2.11.5
Compiled against PROJ | 7.2.1 | Running against PROJ | Rel. 7.2.1, January 1st, 2021
OS Version | Fedora 34 (Workstation Edition)
Active python plugins | joinmultiplelines; QuickOSM; MetaSearch; db_manager; processing

**Comment by nyalldawson** [comment]
Don't set the parameter to "use algorithm output" -- leave it as a value, and click the "..." button to choose the inputs

**Comment by timlinux** [comment]
@nyalldawson thanks for the 39second reply :-) 

That is a bit counter-intuitive isn't it? Or is the idea that if you choose an alg output, that should contain an array of layer names?

**Comment by nyalldawson** [comment]
> that should contain an array of layer names

Yes.. the issue is that the algorithm actually handles a mix. You can have value which is a mix of hardcoded layer paths, input parameters AND other algorithm outputs! So either way it doesn't fit cleanly into the existing categories 🙃

**Comment by timlinux** [comment]
Ok thanks for the info!
