### ISSUE TITLE
No se puede cargar la biblioteca qgispython

### ISSUE THREAD

**Issue by kethale** [qgis/QGIS#43948]
Hola, instale laversión 3.16 de qgism pero al abrirlo ni no aparece la Consola de python del menú complementos, y la lista de complementos no conecta son el respositorio. Quedo al pendiente. Gracias

IMPORTANT:

Do NOT use GitHub to post any questions or support requests!
They will be closed immediately and ignored.
Questions should go to the qgis-user mailing list at https://lists.osgeo.org/mailman/listinfo/qgis-user
or other support forums such as https://gis.stackexchange.com/.

GitHub issues are for bug reports and suggestions for new features.

**Comment by gioman** [comment]
@kethale use this to report issues (in English)

https://github.com/qgis/QGIS/issues/new?assignees=&labels=Bug&template=10_bug_report.md&title=

and add all the requested infos. Thanks!
