### ISSUE TITLE
QGIS won't open previous .qgz projects made

### ISSUE THREAD

**Issue by PorkPill** [qgis/QGIS#43961]
Up until about four days ago v. 3.18.3 was working fine with only minor problems. At some point about four days ago, it no longer allows me to open older projects. Most if not all of these .qgz project files were made and upgraded to V3.18.3. When opening them now, it takes about five seconds, says "project loading" and then it essentially opens a new blank project file without the layers loaded. I've recently upgraded to 3.2 but still they don't open. I work with several people that are having the same issue.

**Comment by gioman** [comment]
@PorkPill try with a new QGIS profile.

**Comment by gioman** [comment]
If it does not make any different you will have probably to attach here a sample project+sample data to allow us replicate the issue.
