### ISSUE TITLE
"Dynamic" PostGIS layer fails with v3.20.0

### ISSUE THREAD

**Issue by BergWerkGIS** [qgis/QGIS#43963]
## Describe the bug

I fairly often use `DB Manager` and the `SQL Window` to directly visualize (`Load as new layer`) the output of existing or custom PostGIS functions instead of querying tables or views.

This works with v3.18.3, but stopped working with v3.20.0

## How to Reproduce

1. Go to `DB Manager`
2. Click on a schema of a PostGIS DB
3. Click on `SQL Window`
4. Paste this code:
  ```sql
  select
    1 fid
    , st_geomfromtext(
      'POINT(16.40977 48.22834)'
      , 4326
    ) geom
  ```
5. Click `Execute`
6. Check `Load as new layer`
6.1. Columns with unique values: `fid`
6.2. Geometry column: `geom`
6.3. Layer name (prefix): `point-test`
7. Click `Load`

### v3.18.3 ✅

![image](https://user-images.githubusercontent.com/4549888/123671592-bf0ffc80-d83e-11eb-9bcb-d5909043ae4c.png)

### v3.20.0 ❌ fails when trying to determine the geometry type

* displays `Database Error` dialog: `There was an error creating the SQL layer, please check the logs for further information.`
* `PostGIS` tab in `Log Messages` panel:
```
WARNING    NOTICE: NOTICE: identifier "(select 1 fid , st_geomfromtext( 'POINT(16.40977 48.22834)' , 4326 ) geom
             ) AS "subQuery_0"" will be truncated to "(select 1 fid , st_geomfromtext( 'POINT(16.40977 48.228"
WARNING    Erroneous query: SELECT 0, array_agg(DISTINCT st_srid("geom")::text || ':' || UPPER(geometrytype("geom")) || ':' || ST_Zmflag("geom")) FROM (SELECT "geom" from "(select 1 fid , st_geomfromtext( 'POINT(16.40977 48.22834)' , 4326 ) geom
             ) AS ""subQuery_0""" ) as _unused returned 7 [ERROR: relation "(select 1 fid , st_geomfromtext( 'POINT(16.40977 48.228" does not exist
             LINE 1: ...' || ST_Zmflag("geom")) FROM (SELECT "geom" from "(select ...
              ^
             ]
WARNING    Invalid PostgreSQL layer
```

## QGIS and OS versions

Tested on:
* Win 10 Enterprise 21H1, QGIS 3.20.0 (Standalone Installer), Postgres 13.1, PostGIS v3.1.0
* Lubuntu 20.04, QGIS 3.20.0, Postgres 13.3, PostGIS v3.1.2

QGIS on Lubuntu:
| | |
| ---- | ---- |
| QGIS version | 3.20.0-Odense |
| QGIS code revision | decaadbb31 |
| Qt version | 5.12.8
| Python version | 3.8.5
| GDAL/OGR version | 3.0.4
| PROJ version | 6.3.1
| EPSG Registry database version | v9.8.6 (2020-01-22)
| Compiled against GEOS | 3.8.0-CAPI-1.13.1
| Running against GEOS | 3.8.0-CAPI-1.13.1 
| SQLite version | 3.31.1
| PDAL version | 2.0.1
| PostgreSQL client version | 12.7 (Ubuntu 12.7-0ubuntu0.20.04.1)
| SpatiaLite version | 4.3.0a
| QWT version | 6.1.4
| QScintilla2 version | 2.11.2
| OS version | Ubuntu 20.04.2 LTS
| Active Python plugins | firstaid test_events pgtopoeditor pluginbuilder3 plugin_reloader QuickWKT db_manager processing

**Comment by gioman** [comment]
Confirmed also on master.

**Comment by BergWerkGIS** [comment]
Tested with `master` as of today and this snippet:

```sql
with t as (
	select * from (values
		(7, 65, 42)
		, (7, 65, 43)
		, (7, 65, 44)
	) v (z, x, y)
)
select 
	row_number() over() fid
	, t.z
	, t.x
	, t.y
	, st_tileenvelope(t.z, t.x, t.y) geom
from t 
```

Works again.
Going to close once a new version has been released.

**Comment by gioman** [comment]
>  Going to close once a new version has been released.

@BergWerkGIS if it is fixed in master this shroud be closed. If the fix is appropriate for a backport it is another matter.

**Comment by BergWerkGIS** [comment]
Don't think this needs to be backported. Works in 3.16 and 3.18.
