### ISSUE TITLE
ECW provider doesn't works on Master a825b5af35

### ISSUE THREAD

**Issue by Antoviscomi** [qgis/QGIS#43977]
Hi all,
I've noticed that ECW raster are not supported in Master https://github.com/qgis/QGIS/commit/a825b5af35,
when I try to add an ECW file on Master only (with gdal-dev-ecw plugin 3.4.0-41 on Windows) QGIS tell:
Layer non valido: GDAL provider Cannot open GDAL dataset N:\Cartografia\Ortofoto\5K\Centro Servizi\575064_orto.ecw: (file: ..\..\..\src\core\providers\gdal\qgsgdalprovider.cpp row: 2921function QgsGdalProvider::initIfNeeded:) Raster layer Sorgente dati non valida (sorgente dati: gdal, URI: N:\Cartografia\Ortofoto\5K\Centro Servizi\575064_orto.ecw (file: ..\..\..\src\core\raster\qgsrasterlayer.cpp row: 659function QgsRasterLayer::setDataProvider:)

**Comment by jef-n** [comment]
Switch to OSGeo4W v2.  The nightlies including master, but excluding the ltr are no longer maintained.
