### ISSUE TITLE
Allow setting the default font to use for labelling

### ISSUE THREAD

**Issue by antoniolocandro** [qgis/QGIS#43971]
QGIS only allows to set the default font for Qt which I believe is later picked up for the labelling engine however it would be better to have the option to specify the default font for labelling independently as Qt font may affect QGIS appearance. Also it would be probably a stretch but it could also be specified that the default font for labelling may be a project variable which could allow even more customization possibilities on a per project basis but this may be too much initially.

**Comment by nyalldawson** [comment]
This is possible since QGIS 3.20 -- just edit the "Default" text symbol in the style manager and set whatever font settings you'd like!

**Comment by antoniolocandro** [comment]
If I set a variable here it will not apply it by default for layers but allow to only select it. Is this the expected behaviour?

![image](https://user-images.githubusercontent.com/4627073/123708572-e5c33880-d828-11eb-844c-fcaabc6fef75.png)
