### ISSUE TITLE
ValueRelation in Attribute form wrong loaded from layer definition file (qlr)

### ISSUE THREAD

**Issue by eurojam** [qgis/QGIS#43978]
**Describe the bug**

Value Relations are not correct loaded from a layerdefinition file as there is a filter set to a strange value like "_069acc1f_d4e7_49ce_b4bf_da8fbee8fbca". The result is that the dropdown in the form will be empty. 

**How to Reproduce**

1. new project
2. load attached qlr
3. layerproperties layer BA_DAT -> forms
4. field: BA_ART_LAT as one example

**QGIS and OS versions**
Windows 10, 64 bit, 3.18 and 3.20 / in 3.16 the qlr file is loaded correctly

**Additional context**

**Comment by eurojam** [comment]
[test_data.zip](https://github.com/qgis/QGIS/files/6732585/test_data.zip)

**Comment by eurojam** [comment]
![2021-06-29 12_07_07-_Unbenanntes Projekt — QGIS  Deutsch](https://user-images.githubusercontent.com/46351209/123780579-a0a81080-d8d3-11eb-88fe-ceb9563b8a24.png)

**Comment by elpaso** [comment]
The attached QLR value relation config points to an absolute layer source: `D:/z_VB-BW/Bearbeitung/20201207_Datenmodell/BA_DAT_test.gpkg|layername=SL_BA_FUNKT`, it will never work. 

Is there any chance that the QLR was exported from a project with relative paths disabled?

**Comment by elpaso** [comment]
mmm, the resolver should work, anyway, checking...

**Comment by eurojam** [comment]
it doesn'matter I think, QGIS loads the right tables anyway. But I attached one with all relative pathes, but the 
[test_data_relative.zip](https://github.com/qgis/QGIS/files/6740395/test_data_relative.zip)
behaviour in 3.18 is the same.

**Comment by elpaso** [comment]
Yeah, the layer is resolved correctly, I had doubts about the widget value relation definition that also references the layer, but it is resolved correctly by name/provider.

**Comment by elpaso** [comment]
Ok, I've found the bug, and it's a nasty one!
