### ISSUE TITLE
No possible to uncheck variable in layer styling for font

### ISSUE THREAD

**Issue by antoniolocandro** [qgis/QGIS#43974]
QGIS 3.20 + WIN10 OSGEO4W

Once the variable is selected it is not possible to unselect

![uncheck-variable](https://user-images.githubusercontent.com/4627073/123709090-b2cd7480-d829-11eb-8007-e84111a5607d.gif)

**Comment by nyalldawson** [comment]
Click "clear" at the bottom of the menu

**Comment by antoniolocandro** [comment]
By clearing at the bottom you can indeed remove the variable but I was under the impression the check box would allow me to not use the variable but maybe I am interpreting wrong since by removing the variable the function would be activated but not with the required parameter
