### ISSUE TITLE
Vector Tab not functioning

### ISSUE THREAD

**Issue by adam-walters** [qgis/QGIS#43980]
The Vector Menu Tab does not function when clicked or hovered over. 

![image](https://user-images.githubusercontent.com/86673529/123821411-5d48a480-d8c9-11eb-9f97-34b2e20a3499.png)

I have re-installed, updated to 3.20, re-booted the computer, the issue remains.

**Comment by Gustry** [comment]
Did you enabled the "Processing" plugin ?

We can't see the "Processing" menu in the toolbar.

**Comment by adam-walters** [comment]
That worked! Thank you.
