### ISSUE TITLE
Make geojson a first class citizen and support mixed geometry types

### ISSUE THREAD

**Issue by openSourcerer9000** [qgis/QGIS#43995]
I can right click a directory in the browser and create an empty shapefile, or get there from the ribbon, but no support for alternative vector formats.
![image](https://user-images.githubusercontent.com/61931826/123978345-68f9a100-d985-11eb-88fd-39b96a87cfb4.png)
![image](https://user-images.githubusercontent.com/61931826/123981088-aceda580-d987-11eb-9da5-bfa6f1a40c45.png)

From a UX standpoint, I would propose simply changing this to "create vector" and adding the option to specify a different file type (and consequently use a different driver under the hood). 

The main concern, however, is lack of support for mixed geometry types. Shapefiles are great, but truncating data and static typing can be unwieldly and they're starting to show their wrinkles. Even ESRI seems to have disowned the format and keeps churning out new flavor-of-the-month proprietary geodatabase formats. Inextensible formats with fixed types,  fixed dimensions, and low character limits are quickly becoming obsolete.  Does QGIS have any plans to get on board with this functionality? Is there a dependency that will ease the process once it adopts mixed geometry types?

**Comment by nyalldawson** [comment]
@openSourcerer9000 what's wrong with geopackage? (Geojson is not a suitable choice for many applications or for large datasets)

**Comment by openSourcerer9000** [comment]
@nyalldawson I just haven't had much exposure to geopackage. Looking into it and it seems to address the limitations of SHP without losing the speed. I would still like to see support for mixed geometry types within 1 layer but we might not be ready for that paradigm shift.

It may be niche but when it comes to extensibility and use on the web, geojson can do stuff like [this](https://kepler.gl/demo/world_flights).
