### ISSUE TITLE
Refresh Geopackage Contents via Right Click -> Refresh

### ISSUE THREAD

**Issue by ahhughes** [qgis/QGIS#43991]
Hi There, 

I have to access QGIS via a bastion (browser) client, and as such F5 never makes it past the host browser and onto QGIS desktop.

Could you please add the ability to refresh the geopackage? I would suggest...

Right click on the geopackage -> Refresh. Or, refresh when the geopackage is opened/expanded (users would have to collapse, then expand to force a refresh). It's quite annoying to have to restart QGIS to see the new contents.

Thank you.

**Comment by gioman** [comment]
@ahhughes sorry is not clear to me: are you saying that clicking on the "refresh" icon in QGIS browser it does not refresh the context of a GPKG connection?

**Comment by roya0045** [comment]
Just hit the refresh button at the top of the browser ? I have not clue what is the point of this to be honest.

**Comment by ahhughes** [comment]
Thanks everyone for looking and responding to this. I am wrong you are all correct, sorry for the disturbance.

The "refresh" button on the top of the QGIS Browser pane does exactly what I want.

Sorry for the noise.
