### ISSUE TITLE
QGIS 3.18 and 3.20 OSGEO or Standalone installed it seems not have Python support on Windows  

### ISSUE THREAD

**Issue by Antoviscomi** [qgis/QGIS#43994]
I've noticed that Processing and Plugin settings does not works for me
The plugin manager settings tell
It seems there is not Python support

**Comment by gioman** [comment]
@Antoviscomi the report is largely incomplete. Fill all the requested info as asked in the template:

https://github.com/qgis/QGIS/issues/new?assignees=&labels=Bug&template=10_bug_report.md&title=

**Comment by Antoviscomi** [comment]
The folder OSGEOW processing algs is not empty but the contents are correctly downloaded

**Comment by Antoviscomi** [comment]
@gioman I've tried on completely clean profile and the step are
1. Download
2. Install
3. Try to use processing 
4. Try install a plugin
5. Try to manage a plugin 
what other I can tell to make complete this report?

**Comment by Antoviscomi** [comment]
Processing does't appear on menu or  in plugin manager

**Comment by gioman** [comment]
>  what other I can tell to make complete this report?

@Antoviscomi are you using the standalone installer or the osgeo4w one? if is the latter, are you using the new one, or the old one?

**Comment by Antoviscomi** [comment]
Standalone and OSGEO v2

**Comment by gioman** [comment]
@Antoviscomi just did an osgeo4w v2 install on Windows 10, and is all ok.

**Comment by Antoviscomi** [comment]
I was on Win7 I just trying on Win10

**Comment by Antoviscomi** [comment]
@gioman I confirm It works properly on Win10 by standalone installer 
now I try by OSGEO

**Comment by agiudiceandrea** [comment]
@Antoviscomi both the Standalone Installer (MSI) and the OSGeo4W Network Installer from the new OSGeo4W v2 repository ship Python 3.9.
Python 3.9 version doesn't support (and normally doesn't work on) Windows 7, because Windows 7 misses a dll needed by Python 3.9.

**Comment by Antoviscomi** [comment]
@agiudiceandrea many thanks then I close this topic
