### ISSUE TITLE
Inverted options for cartographic placement of labels

### ISSUE THREAD

**Issue by antoniolocandro** [qgis/QGIS#44000]
I think the TSL, TSR, BSL and BSR are inverted but I am not completely sure, just wanted to raise it here. See attached image with the debug option enabled to show candidates

![image](https://user-images.githubusercontent.com/4627073/124040293-dfb48f80-d9c1-11eb-82ed-3ceafc8c9722.png)

**Comment by nyalldawson** [comment]
It's correct- "top slightly left" means above the point, slightly to the left of middle. (It's easier to see the difference if you use a longer label text string)

**Comment by antoniolocandro** [comment]
You are right, small text gives the impression it is not, also it means that the anchor point depends on what you choose it is not always the midpoint?

Seems Lower Left
![image](https://user-images.githubusercontent.com/4627073/124044583-fdd2bd80-d9ca-11eb-9df4-2bc4271d38e7.png)

Seems Mid
![image](https://user-images.githubusercontent.com/4627073/124044643-15aa4180-d9cb-11eb-99eb-88cfd01bf0d4.png)

Seems Lower Right

![image](https://user-images.githubusercontent.com/4627073/124044692-38d4f100-d9cb-11eb-95f7-0f99686e7650.png)

Would images like this be a good idea in the documentation? The current documentation just shows this https://docs.qgis.org/testing/en/docs/user_manual/style_library/label_settings.html?highlight=labelling#placement-for-point-layers
