### ISSUE TITLE
Interface customization add note restart is required

### ISSUE THREAD

**Issue by antoniolocandro** [qgis/QGIS#44023]
I was trying to do some customization of the interface and didn't realize that completely close and re-open of QGIS was required so maybe add the following legend somewhere, this could potentially save users the hassle to know why the change did not work only to find out it works after new session is started.

I don't know if the software itself is the best option or just on the docs.

![image](https://user-images.githubusercontent.com/4627073/124194408-c83eda80-da85-11eb-80f9-dd92dcf23ffb.png)

**Comment by DelazJ** [comment]
> I don't know if the software itself is the best option or just on the docs.

The docs already do their parts (https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html#customization)

**Comment by antoniolocandro** [comment]
Probably proof people don’t read the docs or things not easy to find. Either way ppl think docs are enough then this can be closed

**Comment by DelazJ** [comment]
> Probably proof people don’t read the docs 

Unfortunately... only a few do read. 😞 
> or things not easy to find

In this particular case, hitting the help button in the dialog is enough. Couldn't be easier IMHO.
