### ISSUE TITLE
Export to spreadsheet adds ghost attribute

### ISSUE THREAD

**Issue by kobusburger** [qgis/QGIS#44029]
**Describe the bug**

The "Export to spreadsheet" algorithm adds an attribute column with old values but only for a specific layer. I deleted the attribute but the algorithm still show the non-existent attribute with old values. This happens even after I exited and restarted QGIS.
The problem ghost attribute is not there if I save-as the layer to CSV or Excel. See the attached spreadsheet with the exported data and some screenshots. The layer is "Williston outer repeater FR" and the relevant Geopackage is also attached.
[MK+gpkg.zip](https://github.com/qgis/QGIS/files/6754111/MK%2Bgpkg.zip)
[Export to spreadsheet bug.xlsx](https://github.com/qgis/QGIS/files/6754085/Export.to.spreadsheet.bug.xlsx)

The log shows the following:
QGIS version: 3.18.3-Zürich
QGIS code revision: 735cc85be9
Qt version: 5.11.2
GDAL version: 3.1.4
GEOS version: 3.8.1-CAPI-1.13.3
PROJ version: Rel. 6.3.2, May 1st, 2020
Processing algorithm…
Algorithm 'Export to spreadsheet' starting…
Input parameters:
{ 'FORMATTED_VALUES' : False, 'LAYERS' : ['C:/Users/kobus.burger/OneDrive - Zutari/KBProjects/SKA MK+/Design/QGIS/MK+.gpkg|layername=Williston outer repeater fibre cable'], 'OUTPUT' : 'TEMPORARY_OUTPUT', 'OVERWRITE' : True, 'USE_ALIAS' : False }

Exporting layer 1/1: Williston outer repeater FR
Execution completed in 0.41 seconds
Results:
{'OUTPUT': 'C:/Users/kobus.burger/AppData/Local/Temp/1/processing_zSszPW/b9582bab926841e883aa4ab2f91d4943/OUTPUT.xlsx',
'OUTPUT_LAYERS': ['C:/Users/kobus.burger/AppData/Local/Temp/1/processing_zSszPW/b9582bab926841e883aa4ab2f91d4943/OUTPUT.xlsx|layername=Williston '
'outer repeater FR']}

Loading resulting layers
Algorithm 'Export to spreadsheet' finished

**How to Reproduce**
I on reproduce the problem on my project but I do not know it only happens with one specific layer.

**QGIS and OS versions**

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.18.3-Zürich | QGIS code revision | 735cc85be9
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | kmltools; db_manager; MetaSearch; processing

</body></html>

**Additional context**

**Comment by gioman** [comment]
@kobusburger this seems to happen because the "area" column is a virtual one and is part of the default layer style. It seems that the tool takes into account the virtual columns defined in the default style and not in the layer properties of the project being used (where in your case you have removed the "area" virtual column). Can you confirm this observation?

PS
note that I tried remove all saved styles in your gpkg. Apparently I had removed all via GUI but then inspecting the "layers_styles" table shown there were leftovers, one of them about the problematic layer, that had to be removed via SQL.

**Comment by kobusburger** [comment]
Thanks for the valuable feedback. I deleted the styles layer with the DB Manager and the problem went away.

**Comment by gioman** [comment]
> Thanks for the valuable feedback. I deleted the styles layer with the DB Manager and the problem went away.

@kobusburger closing?
