### ISSUE TITLE
No more gdal library installed in QGIS 3.20.0?

### ISSUE THREAD

**Issue by mustafaucr** [qgis/QGIS#44026]
I have a plugin that uses gdal. As you know in previous QGIS versions (before 3.20.0), gdal has been already installed. However now QGIS has not gdal libray in default. Is there any bug or how can I resolve this problem?

![image](https://user-images.githubusercontent.com/36263724/124224387-39c26b80-db0e-11eb-8c89-9d750f9e2e27.png)

**Comment by nicogodet** [comment]
`from osgeo import gdal`
