### ISSUE TITLE
QGIS ended unexpectedly

### ISSUE THREAD

**Issue by JailtonRosa** [qgis/QGIS#44032]
Quando tento fazer a impressão de um Layout em pdf, o QGIS finaliza e não completa a impressão.
O que pode estar causando esse problema?

Aparece o seguinte no Report Details:

Crash ID: 54ded8e5c1fb0acc4f82cfd68e05536e00ceab1c

Stack Trace

memcpy memcpy.asm:406
QBuffer::writeData :
QIODevice::write :
QPdfEngine::drawPath :
QgsSimpleLineSymbolLayer::renderPolyline :
QgsLineSymbol::renderPolylineUsingLayer :
QgsLineSymbol::renderPolyline :
QgsSymbol::renderFeature :
QgsFeatureRenderer::renderFeature :
QgsVectorLayerJoinInfo::setUsingMemoryCache :
QgsVectorLayerJoinInfo::setUsingMemoryCache :
QgsMapRendererCustomPainterJob::doRender :
QgsMapRendererCustomPainterJob::start :
QgsMapRendererCustomPainterJob::renderSynchronously :
QgsLayoutItemMap::drawMap :
QgsLayoutItemMap::paint :
QGraphicsScene::dragMoveEvent :
QGraphicsItem::dragMoveEvent :
QGraphicsEffectSource::draw :
QgsLayoutEffect::draw :
QGraphicsScene::drawItems :
QGraphicsScene::drawItems :
QGraphicsScene::render :
QgsLayoutExporter::renderRegion :
QgsLayoutExporter::renderPage :
QgsLayoutExporter::printPrivate :
QgsLayoutExporter::exportToPdf :
QgisApp::actionPasteLayerStyle :
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.16.4-Hannover
QGIS code revision: 654e76b3cb
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

**Comment by gioman** [comment]
> Quando tento fazer a impressão de um Layout em pdf, o QGIS finaliza e não completa a impressão.
> O que pode estar causando esse problema?

@JailtonRosa tickets must be filed in English (obrigado!). Please try with a new QGIS profile, no 3rd party plugins installed. If this do not change anything please check memory consumption by the time QGIS crashes.

**Comment by roya0045** [comment]
@gioman isn't 3.16.4 too old also?

**Comment by gioman** [comment]
> @gioman isn't 3.16.4 too old also?

yes

**Comment by JailtonRosa** [comment]
Problem solved.
It was a memory consumption issue,
Thanks for the help @gioman
