### ISSUE TITLE
Crash when deleting Child Feature from forms (MSSQL DB)

### ISSUE THREAD

**Issue by Naude555** [qgis/QGIS#44034]
rash ID: d6469e8b442ad2eb289951348aa0944f4b621bd5

Stack Trace

QMimeType::staticMetaObject :
QgsFeatureListView::QgsFeatureListView :
QObject::qt_static_metacall :
QTimer::timerEvent :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QgsDualView::progress :
QObject::qt_static_metacall :
QgsAttributeTableModel::progress :
QgsAttributeTableModel::loadLayer :
QgsDualView::initModels :
QgsDualView::init :
QgsRelationEditorWidget::initDualView :
QgsRelationEditorWidget::updateUi :
QgsAbstractRelationEditorWidget::deleteFeatures :
QgsRelationEditorWidget::deleteSelectedFeatures :
QObject::qt_static_metacall :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.20.0-Odense
QGIS code revision: decaadbb31
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.0
Running against GDAL: 3.3.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

**Comment by gioman** [comment]
@Naude555 does it happen with other backends? what about with a new QGIS profile (no 3rd party plugins installed)?
