### ISSUE TITLE
QGIS crashed (became unresponsive)

### ISSUE THREAD

**Issue by kobusburger** [qgis/QGIS#44031]
**Describe the bug**

QGIS crashed. See crash report
**How to Reproduce**
I do not know how to reproduce the crash

**QGIS and OS versions**
## User Feedback

QGIS crashed while I was zooming and panning

## Report Details

**Crash ID**: [3178e85cf3116b1a03f1beb25f718c2da4c47576](https://github.com/qgis/QGIS/search?q=3178e85cf3116b1a03f1beb25f718c2da4c47576&type=Issues)

**Stack Trace**
<pre>
QTextOption::wrapMode :
QTextOption::wrapMode :
QRasterPaintEngine::drawImage :
QRasterPaintEngine::drawImage :
QPainter::drawImage :
QPainter::drawImage :
QgsSimpleMarkerSymbolLayer::renderPoint qgsmarkersymbollayer.cpp:1157
QgsMarkerSymbol::renderPointUsingLayer qgssymbol.cpp:1971
QgsMarkerSymbol::renderPoint qgssymbol.cpp:2011
QgsAnnotation::drawMarkerSymbol qgsannotation.cpp:395
QgsAnnotation::render qgsannotation.cpp:149
QgsMapCanvasAnnotationItem::paint qgsmapcanvasannotationitem.cpp:319
QGraphicsScene::dragMoveEvent :
QGraphicsScene::drawItems :
QGraphicsScene::drawItems :
QGraphicsView::paintEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:475
QCoreApplication::notifyInternal2 :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QApplication::windowIcon :
QWidget::event :
QgisApp::event qgisapp.cpp:2204
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:475
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
QGraphicsScene::~QGraphicsScene :
QObject::event :
QGraphicsScene::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:475
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1638
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.18.3-Z�rich
QGIS code revision: 735cc85be9
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Additional context**

**Comment by gioman** [comment]
@kobusburger please try withj new QGIS profile, no 3rd party plugins installed. Without a clear description about what caused the crash there is no much sense in keeping this open...

**Comment by roya0045** [comment]
Seems project specific as the crash came from rendering. Would need a sample project or a reliable way to obtain the crash with your settings.

**Comment by kobusburger** [comment]
I may be wrong but I deleted the styles layer in the Geopackage using DB Manager (I had issues with the styles layer) and it now seems that QGIS is stable. Maybe https://github.com/qgis/QGIS/issues/44029#issuecomment-873184899 is related to this.
