### ISSUE TITLE
network driver slowing down or crashing the program

### ISSUE THREAD

**Issue by mahfigithub** [qgis/QGIS#44044]
If the computer has a network drive connected by VPN and the network drive is not connected at the moment, the program becomes very slow and gets stuck in the browser. It's probably trying to connect to files on the network drive. After removing the network drivers, the problem is solved.

**Comment by gioman** [comment]
> If the computer has a network drive connected by VPN and the network drive is not connected at the moment, the program becomes very slow and gets stuck in the browser. It's probably trying to connect to files on the network drive. After removing the network drivers, the problem is solved.

@mahfigithub this was fixed in 3.20, see here https://github.com/qgis/QGIS/pull/43416
