### ISSUE TITLE
"Select features" missing in Qgis 3.16

### ISSUE THREAD

**Issue by Sheggywolf** [qgis/QGIS#44040]
I can't find the button for "select features" in the toolbar or anywhere in toolbox of Qgis 3.16. Suggestions I have found elsewhere, such as to remove "processing" from the processiing menu, don't solve my problem. What can I do to bring this tool back?
![image](https://user-images.githubusercontent.com/86867386/124344452-0e19b100-dbf4-11eb-9cef-7d19cf05a433.png)

**Comment by agiudiceandrea** [comment]
@Sheggywolf the Select Features tools are right there in the toolbar and in the Edit Menu
![image](https://user-images.githubusercontent.com/16253859/124348265-3fd94a80-dbe9-11eb-8727-9bff3c0e35c2.png)

**Comment by andreasneumann** [comment]
@Sheggywolf - if the button is greyed out you need to activate a layer. The select functions need to know on which layer they should work on.
