### ISSUE TITLE
Python support won’t work with QGIS 3.20RC (module export function error)

### ISSUE THREAD

**Issue by Veence** [qgis/QGIS#44042]
Folks,
after I compiled (successfully this time) QGis 3.20RC on my Mac,  I get the following message at launch:

```
Couldn't load PyQGIS.
Python support will be disabled.


Traceback (most recent call last):
  File "", line 1, in 
  File "/Applications/MacPorts/Qgis3.app/Contents/MacOS/../Resources/python/qgis/core/__init__.py", line 25, in 
    from qgis._core import *
ImportError: dynamic module does not define module export function (PyInit__core)
```

Any idea about what could cause that? Linker woes? Extraneous stripping of the symbol table? 

Also, fwiw, I’m using Python 3.9.5 and Apple clang version 12.0.5 (clang-1205.0.22.11)

Thanks!

**Comment by gioman** [comment]
> Any idea about what could cause that? Linker woes? Extraneous stripping of the symbol table?

@Veence questions must be posted in the users or developers mailing lists.

**Comment by Veence** [comment]
> On 4 Jul 2021, at 13:31, Giovanni Manghi ***@***.***> wrote:
> 
> 
> Any idea about what could cause that? Linker woes? Extraneous stripping of the symbol table?
> 
> @Veence questions must be posted in the users or developers mailing lists.

This looks much more like a bug to me than an open question, really.
Pero grazie dell’attenzione :)

Vincent

**Comment by gioman** [comment]
@Veence python support works on official installers for macOS, so it is the other way around...

**Comment by Veence** [comment]
It works now with 3.20.1, so I’m closing it.
