### ISSUE TITLE
Display problem on large screen

### ISSUE THREAD

**Issue by turgeong** [qgis/QGIS#44043]
When displaying a new area on a large screen (4K) (zoom or span), QGIS begin to draw the new area, return briefly to the old area and resume to draw the new area.  It's very annoying when zooming or spanning in a project.

This bug is present on 3.20 and on or precedent versions.  All was fine before on the same project, same computer and same screen.

**Comment by gioman** [comment]
> This bug is present on 3.20 and on or precedent versions

@turgeong this means that before 3.20 is ok?

**Comment by gioman** [comment]
@turgeong can you post a screencast?
