### ISSUE TITLE
Attribute table pop-up moving on screen  

### ISSUE THREAD

**Issue by Gooseman2021** [qgis/QGIS#44050]
Every time I add a new vector point to my layer the pop-up attribute screen opens (as it should). However, it moves vertically down the screen a little bit for every new point so after adding about 7 or 8 new points it has almost disappeared from the bottom of the screen. 

This has only happened since the latest QGIS release 3.20.0

**Comment by nicogodet** [comment]
I think this is a Qt issue as I experience this annoying behavior since I switch to OsGeo4W testing/V2.

**Comment by Gooseman2021** [comment]
Thanks. Do I need to report this somewhere else? Or do you know if there is a fix for it.  It is, as you say, really annoying.

**Comment by nicogodet** [comment]
Also happens with Identify tool.

If you don't close the opened dialog, next click will open a dialog at the same position.
If you close the opened dialog, next click will open a dialog slightly shifted in Y.
![image](https://user-images.githubusercontent.com/39594821/124430484-83f65780-dd6f-11eb-8721-924d15f43794.png)

After a lot of opened windows:
![image](https://user-images.githubusercontent.com/39594821/124430644-b4d68c80-dd6f-11eb-9a93-e76325e88f79.png)

**Comment by Pedro-Murteira** [comment]
Still valid on QGIS 3.22.3.

**Comment by Rennie24** [comment]
- Was still a valid bug in QGIS 3.24.0 w/ Qt 5.15.2 on Windows 10 20H2
- Is still a valid bug on fresh install of QGIS 3.28.0 w/ Qt 5.15.3 on Windows 11 22H2

It appears that Qt's pop-up QDialog that appears when completing digitizing of a new feature is "marching" down and to the right a few pixels on each instance. I searched the [Qt Bug Reports](https://bugreports.qt.io/) but couldn't find an exact issue related to this problem.

**Comment by esnyder-rve** [comment]
Is this an upstream issue (a problem with Qt itself) or is this something that can be addressed on our end?

**Comment by YoannQDQ** [comment]
Calling `restoreGeometry` before the `QDialog `is actually shown have unexpected side-effects. What is happening is the widget is placed on the window as if it had no frame, then when the dialog is made visible (`QDialog::show()` is called) the frame kinda pops into existence, shifting the QDialog downwards (by the height of the windows titlebar) and slighlty rightwards (by some pixels, matching the border width of the window's frame).
#52472 delays the call to restoreGeometry until the dialog is actually shown, hopefuly fixint it without any side effects.
