### ISSUE TITLE
QGIS cannot connect to database

### ISSUE THREAD

**Issue by Michaelgeop** [qgis/QGIS#44057]
Hello,

A user of mine cannot connect to a database on QGIS, it is strange because they can connect to it via other applications such as ArcGIS and FME but not with QGIS. When trying to connect, on version 3.16 we receive the error message 'An error has occurred' and on version 3.20 the error msg is 'Unable to login'. Just to reiterate the database is running and can be connected to through other software just not QGIS for some reason. I have attached screenshots for reference.
![image004](https://user-images.githubusercontent.com/86976581/124500328-7795ed00-ddb7-11eb-9d05-25f731ab638d.jpg)
![image-2021-07-05-16-30-46-683](https://user-images.githubusercontent.com/86976581/124500335-79f84700-ddb7-11eb-977d-eafe5b79d796.png)

Is there any clue as to what is going on here, and what can be done to try and resolve this?

Thanks,
Michael

**Comment by gioman** [comment]
@Michaelgeop what is the backend? Oracle?

**Comment by Michaelgeop** [comment]
Hi @gioman yes it's Oracle

**Comment by gioman** [comment]
@Michaelgeop is this relevant https://github.com/qgis/QGIS/issues/43843 ?

**Comment by Michaelgeop** [comment]
Hi,
This has been resolved now, it looks like the install was corrupted and it works now after reinstalling.
