### ISSUE TITLE
Geodetic equivilent to Interpolate function of QgsGeometry class.

### ISSUE THREAD

**Issue by tristenbarrett** [qgis/QGIS#44073]
**Feature description.**
Requesting geodetic equivalent to **interpolate** function of **QgsGeometry** Class.

**Additional context**
(Apologies if any of the below is incorrect - this is not my specialist area and it's quite possible everything is nonsense.)

I am currently in the process over the last couple of projects of switching our workflow over to QGIS but have hit one key roadblock.  My projects involve long distance cable installations (thousands of kilometres) and one of our key reporting requirements is being able to deliver data points spaced evenly at set distances (usually 10m or 50m) measured ellipsoidal.  All the software used for the actual installation of cabling works in geodetic only (including input/output of data).  Due to the distances involved, no grid projections appear to offer a viable solution.

The various existing plugins for adding points along lines such as Points along geometry (Processing Toolbox) and QChainage do not seem to offer this and all search results seem to imply this is currently not possible.  Comments/requests on plugins asking for this feature have not yet been resolved, leading me to think there may be a deeper functionality lacking.

Having looked at the code for a few tools (particularly QChainage) I note they seem reliant on the Interpolate function for the QgsGeometry class, which the documentation shows to be Cartesian only.  Again, while this is not my professional area and I may be missing things, a look over the other QGIS classes don't seem to reveal a geodetic equivalent.

Could this potentially be added?  I believe I can probably get some small funding approved from my company, though I have zero idea what costing would be.  Cheers!

**Comment by gioman** [comment]
> Could this potentially be added? I believe I can probably get some small funding approved from my company, though I have zero idea what costing would be. Cheers!

@tristenbarrett to reach a wider audience you should also write in the developers mailing list.

**Comment by antoniolocandro** [comment]
Seems you have already asked for something similar here https://github.com/qgis/QGIS/issues/39280

On this note I added this request https://github.com/qgis/QGIS/issues/18745 several years ago including sample code from another project which could be useful if this ever gets implemented

**Comment by tristenbarrett** [comment]
> Seems you have already asked for something similar here #39280


Wow!  I honestly don't remember that!  A lot of projects and a crazy year ago I guess.  Come to think of it, that would have been about the last time I did a similar deliverable  In any case excuse the duplication.

**Comment by tristenbarrett** [comment]
> @tristenbarrett to reach a wider audience you should also write in the developers mailing list.

Thanks for the advice!  Wasn't aware of that before so will go have a look.

**Comment by gioman** [comment]
> Wow! I honestly don't remember that! A lot of projects and a crazy year ago I guess. Come to think of it, that would have been about the last time I did a similar deliverable. In any case excuse the duplication.

@tristenbarrett then closing as duplicate?
