### ISSUE TITLE
Symbol Selector for a Line always initializes with Width units = Millimeters

### ISSUE THREAD

**Issue by euanr** [qgis/QGIS#44070]
The Symbol Selector Dialog Box for a Line always seems to initialize with the Width units set to Millimeters.

You should be able to replicate the error using:
-  Open Symbol Selector
- Change Width units from Millimeters to Inches (or anything else)
- Select OK to close Symbol Selector
- Re-open Symbol Selector
- Width units have reverted to Millimeters, even though the sample of the line has its width updated

![image](https://user-images.githubusercontent.com/77059192/124690712-f0af5480-df1d-11eb-9c15-6471fdb4c2e9.png)
![image](https://user-images.githubusercontent.com/77059192/124690874-3409c300-df1e-11eb-952a-8c30f1ff7c3b.png)
![image](https://user-images.githubusercontent.com/77059192/124690806-12104080-df1e-11eb-9f46-a8f188aa0fc8.png)

**Comment by gioman** [comment]
@euanr can't confirm on 3.16 on Windows. What version are you using?

**Comment by euanr** [comment]
Hi Giovanni, 
Thank you for the fast response. 
I’m using 3.20, the latest version. 
I don’t know if it happened with previous versions. 
Regards,
— Euan

**Comment by gioman** [comment]
I tested also on master, and is ok there too.

**Comment by nicogodet** [comment]
Confirmed on Windows 10 OsGeo4W V2 with 3.20 and Master
On 3.16 UI is different and no issue.

**Comment by gioman** [comment]
i'll test master on Windows, on linux is ok.

**Comment by nicogodet** [comment]
Confirmed on 3.20 on Linux too
