### ISSUE TITLE
QGIS 3.10/3.16 crashed when importing CSV file

### ISSUE THREAD

**Issue by NCiobo** [qgis/QGIS#44082]
**Describe the bug**

The csv file has no coordinate, and I try importing it as CSV format with no geometry, for a join with the attribute table 
here is the error message:

Crash ID: c0d74c7f12d4b641426092dc4840e3568190d885

Stack Trace

QBitArray::QBitArray :
QgsExpressionFunction::name :
QgsRuleBasedRenderer::convertFromRenderer :
PyInit__core :
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QMetaObject::activate :
QgisInterface::currentLayerChanged :
QMetaObject::activate :
QgisApp::activeLayerChanged :
QgisApp::onActiveLayerChanged :
QMetaObject::activate :
QgsLayerTreeView::currentLayerChanged :
QgsLayerTreeView::onCurrentChanged :
QMetaObject::activate :
QItemSelectionModel::setCurrentIndex :
QAbstractItemView::setCurrentIndex :
QgisApp::autoSelectAddedLayer :
QgisApp::identify :
QMetaObject::activate :
QgsLayerTreeRegistryBridge::addedLayersToLayerTree :
QgsLayerTreeRegistryBridge::layersAdded :
QMetaObject::activate :
QgsProject::legendLayersAdded :
QgsProject::addMapLayers :
QgisApp::addVectorLayerPrivate :
QgisApp::addSelectedVectorLayer :
QgisApp::qt_static_metacall :
QMetaObject::activate :
QgsDataSourceManagerDialog::addVectorLayer :
QgsDataSourceManagerDialog::addProviderDialog :
QMetaObject::activate :
QgsAbstractDataSourceWidget::addVectorLayer :
providerGuiMetadataFactory :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
QgisApp::dataSourceManager :
QgisApp::identify :
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.10.14-A Coru�a
QGIS code revision: 8374282d2a
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

data looks like this

![image](https://user-images.githubusercontent.com/29942151/124897015-9201dd80-dfe6-11eb-99f5-86ba6a6cc8b6.png)

**Comment by gioman** [comment]
>  QGIS Version: 3.10.14-A Coru�a

@NCiobo too old, you must test on the latest 3.16 or 3.20. If the problem persist attach the data.

**Comment by NCiobo** [comment]
I tested  on 3.16 a s well, I will see om 3.20 if persists.

**Comment by NCiobo** [comment]
with 3.20 it worked. Thanks!
