### ISSUE TITLE
Missing entries in attributetable in layout with atlas at page break

### ISSUE THREAD

**Issue by baumsicht** [qgis/QGIS#44086]
**Describe the bug**
Missing lines in attributetable in layout with atlas at page break in QGIS 3.16 and 3.18

**How to Reproduce**
1. Create some points.
2. Create a polygon (points are within that polygon)
3. Use polygon as atlas object in a layout.
4. Insert attributtable with points.
5. Entries in table are not showing at page break.

Screencast at https://screencast-o-matic.com/u/6avI/qgis-issue-table-atlas-layout

**QGIS and OS versions**
QGIS-Version
3.16.8-Hannover
QGIS-Codeversion
8c50902ea4
Kompiliert gegen Qt
5.11.2
Laufendes Qt
5.11.2
Kompiliert mit GDAL/OGR
3.1.4
Läuft mit GDAL/OGR
3.1.4
Kompiliert mit GEOS
3.8.1-CAPI-1.13.3
Läuft mit GEOS
3.8.1-CAPI-1.13.3
Kompiliert mit SQLite
3.29.0
Läuft mit SQLite
3.29.0
PostgreSQL-Client-Version
11.5
SpatiaLite-Version
4.3.0
QWT-Version
6.1.3
QScintilla2-Version
2.10.8
Kompiliert mit PROJ
6.3.2
Läuft mit PROJ
Rel. 6.3.2, May 1st, 2020
BS-Version
Windows 10 (10.0)
Aktive Python-Erweiterungen
NNJoin

**Comment by gioman** [comment]
@baumsicht can you add a sample project?

**Comment by baumsicht** [comment]
@gioman I can't reproduce it in a different project, seems to be an issue just with this layout. File avaible at https://cloud.baumsicht.de/index.php/s/aDtkBCTTbN9ZeRE

**Comment by gioman** [comment]
Attaching the zip here as external links often stop to work.

[issue-44086.zip](https://github.com/qgis/QGIS/files/6790570/issue-44086.zip)

**Comment by Pedro-Murteira** [comment]
Still valid on QGIS 3.22.3. (Windows 10)
