### ISSUE TITLE
Join attributes by location on large dataset: consumes all memory and crashes

### ISSUE THREAD

**Issue by justinjngan** [qgis/QGIS#44084]
**Describe the bug**
<When joining attributes by location for two layers that are larger (172,217 complex polygons (dense nodes) and 5,638,125 points, QGIS appears to increase memory usage till all memory is consumed then crashes.>

**How to Reproduce**

1. Added polygon layer (172,217 shapes)
2. Added point layer (5,638,125 points)
3. Memory consumed in Task Manager: 295.6 MB
4. Select Join attributes by location from Processing Tools panel
5. Parameters: discard unjoined records,  one-to-many, create temporary layer for joined and unjoined records
6. Run

I cannot upload the data as I work for the Government and the data is protected.
I can try to describe for you the complexity of the data: 

- the point data is simple with about a six attributes of type INT and FLOAT
- the polygon data is more complex meaning the feature geometries have a dense node distribution. The layer represents coverage of radio waves. The density of the nodes is required to capture the variations in signal strength coming from radio wave emmissions.
- the data spans the width of North America and is about the height of Canada or the US.

**QGIS and OS versions**

QGIS version | 3.16.4-Hannover | QGIS code revision | 654e76b3cb
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | DissolveWithStats; GroupStats; latlontools; SpreadsheetLayers; db_manager; processing

**Additional context**

We are making great strides bringing QGIS into our department and replacing MapInfo as the go-to GIS client. Our work very directly impacts the day-to-day lives of millions of people (points represent houses and buildings. I am hoping this one thing can be escalated and fixed so that we can continue demonstrating the value of QGIS.  Many thanks.

**Comment by gioman** [comment]
@justinjngan will try to replicate with my own data



> We are making great strides bringing QGIS into our department and replacing MapInfo as the go-to GIS client. Our work very directly impacts the day-to-day lives of millions of people (points represent houses and buildings. I am hoping this one thing can be escalated and fixed so that we can continue demonstrating the value of QGIS. Many thanks.

So maybe you may want to consider supporting the work necessary to fix this bug.

**Comment by uclaros** [comment]
Since you can't share the data please provide the following:
1. Data format (geopackage, shapefile, memory layer, database?)
2. Does *check validity* return errors on your layers?
3. Is there a spatial index present on your layers?

**Comment by gioman** [comment]
@justinjngan tested with slightly smaller datasets (50k polygons, admin boundaries, and 1M points), no issues on 3.16.8 on an old Windows machine.
