### ISSUE TITLE
ZMAP format

### ISSUE THREAD

**Issue by gernigon** [qgis/QGIS#44080]
**Describe the bug**
I installed the last Qgis 3.20 (Odense) on Windows 10. It works fine but the new version does not recognized my ZMAP grid files anylonger. (Gdal drive issue ?). 
Als, we cannot import Zmap files in the project anymore
I am back to 3.18 and it was still fine.

**Comment by gioman** [comment]
@gernigon a number of formats have been removed from GDAL recently. You should check that.

ogrinfo --formats
gdalinfo --formats

most likely not a QGIS issue. See https://lists.osgeo.org/pipermail/gdal-dev/2021-January/053260.html
