### ISSUE TITLE
QGIS keeps crashing with labellines

### ISSUE THREAD

**Issue by arer01** [qgis/QGIS#44093]
## User Feedback

Showing labellines in a certain area is crashing the program

## Report Details

**Crash ID**: [b637ee9862584355b1829271df7f9dd2e1a51fa1](https://github.com/qgis/QGIS/search?q=b637ee9862584355b1829271df7f9dd2e1a51fa1&type=Issues)

**Stack Trace**
<pre>
initGEOS :
GEOSCoordSeq_getX_r :
QgsGeos::shortestLine :
QgsGeometry::shortestLine :
QgsCallout::QgsCalloutContext::operator= :
QgsSimpleLineCallout::draw :
QgsCallout::render :
QgsVectorLayerLabelProvider::drawCallout :
QgsVectorLayerLabelProvider::drawLabelBackground :
QgsLabelingEngine::drawLabels :
QgsDefaultLabelingEngine::run :
QgsMapRendererJob::drawLabeling :
QgsMapRendererParallelJob::renderLabelsStatic :
QgsMapRendererCustomPainterJob::renderSynchronously :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.16.7-Hannover
QGIS code revision: 04717438
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.0
Running against GDAL: 3.3.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

**Comment by gioman** [comment]
@arer01 please try with a new QGIS profile. No 3rd party plugins installed.

**Comment by roya0045** [comment]
This is new with shortestLine. Can you share the data and settings that causes the crash?

**Comment by arer01** [comment]
I can share with persons but I don’t want to put it online, if it’s a must a can try to anonymize the file (GDP ☹)

I am guessing its some corrupt features in a ESRI polygon-layer file

I have inspect it in FME and resaved it but it’s not helping

I can put labels but when I press apply on label-lines it crashes, It no timestress, I created the labels in adobe and worked on its just one area

Med vänlig hälsning
Åke Eriksson
Tfn. 070-382 67 10

Från: Alex ***@***.***>
Skickat: den 9 juli 2021 14:15
Till: qgis/QGIS ***@***.***>
Kopia: arer01 ***@***.***>; Mention ***@***.***>
Ämne: Re: [qgis/QGIS] QGIS keeps crashing with labellines (#44093)


This is new with shortestLine. Can you share the data and settings that causes the crash?

**Comment by arer01** [comment]
It happens when I use a new profile no difference

## User Feedback

crashing when pressing apply when adding labellines

## Report Details

**Crash ID**: [b637ee9862584355b1829271df7f9dd2e1a51fa1](https://github.com/qgis/QGIS/search?q=b637ee9862584355b1829271df7f9dd2e1a51fa1&type=Issues)


**Stack Trace**
<pre>
initGEOS :
GEOSCoordSeq_getX_r :
QgsGeos::shortestLine :
QgsGeometry::shortestLine :
QgsCallout::QgsCalloutContext::operator= :
QgsSimpleLineCallout::draw :
QgsCallout::render :
QgsVectorLayerLabelProvider::drawCallout :
QgsVectorLayerLabelProvider::drawLabelBackground :
QgsLabelingEngine::drawLabels :
QgsDefaultLabelingEngine::run :
QgsMapRendererJob::drawLabeling :
QgsMapRendererParallelJob::renderLabelsStatic :
QgsMapRendererCustomPainterJob::renderSynchronously :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>


**QGIS Info**
QGIS Version: 3.16.7-Hannover
QGIS code revision: 04717438
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.0
Running against GDAL: 3.3.0



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

Med vänlig hälsning
Åke Eriksson
Tfn. 070-382 67 10

Från: Giovanni Manghi ***@***.***>
Skickat: den 9 juli 2021 12:05
Till: qgis/QGIS ***@***.***>
Kopia: arer01 ***@***.***>; Mention ***@***.***>
Ämne: Re: [qgis/QGIS] Qgis keeps crashing with labellines (#44093)


@arer01<https://github.com/arer01> please try with a new QGIS profile. No 3rd party plugins installed.

**Comment by gioman** [comment]
> , if it’s a must a can try to anonymize the fil

@arer01 yes thanks.

**Comment by arer01** [comment]
Med vänlig hälsning
Åke Eriksson
Tfn. 070-382 67 10

Från: Giovanni Manghi ***@***.***>
Skickat: den 9 juli 2021 14:32
Till: qgis/QGIS ***@***.***>
Kopia: arer01 ***@***.***>; Mention ***@***.***>
Ämne: Re: [qgis/QGIS] QGIS keeps crashing with labellines (#44093)


, if it’s a must a can try to anonymize the fil

@arer01<https://github.com/arer01> yes thanks.

**Comment by gioman** [comment]
> Med vänlig hälsning Åke Eriksson Tfn. 070-382 67 10 Från: Giovanni Manghi ***@***.***> Skickat: den 9 juli 2021 14:32 Till: qgis/QGIS ***@***.***> Kopia: arer01 ***@***.***>; Mention ***@***.***> Ämne: Re: [qgis/QGIS] QGIS keeps crashing with labellines (#44093) , if it’s a must a can try to anonymize the fil @arer01<https://github.com/arer01> yes thanks.

@arer01 attachments must be send by posting on GH web site, not by email.

**Comment by arer01** [comment]
[Desktop.zip](https://github.com/qgis/QGIS/files/6834164/Desktop.zip)
trying again

**Comment by arer01** [comment]
pressed wrong

**Comment by gioman** [comment]
> [Desktop.zip](https://github.com/qgis/QGIS/files/6834164/Desktop.zip)
> trying again

@arer01 the style you attached has no labels, better to also add a project file, with all the settings needed to replicate the problem.

**Comment by arer01** [comment]
[Downloads.zip](https://github.com/qgis/QGIS/files/6838540/Downloads.zip)


Like this?

**Comment by gioman** [comment]
> Like this?

@arer01 yes, but still no crashes here.

**Comment by arer01** [comment]
You will have to move it

Med vänlig hälsning
Åke Eriksson
Tfn. 070-382 67 10

Från: Giovanni Manghi ***@***.***>
Skickat: den 19 juli 2021 11:52
Till: qgis/QGIS ***@***.***>
Kopia: arer01 ***@***.***>; Mention ***@***.***>
Ämne: Re: [qgis/QGIS] QGIS keeps crashing with labellines (#44093)


Like this?

@arer01<https://github.com/arer01> yes, but still no crashes here.

**Comment by gioman** [comment]
> You will have to move it

@arer01 I did it.

**Comment by arer01** [comment]
If you choose to zoom to entire layer?

Med vänlig hälsning
Åke Eriksson
Tfn. 070-382 67 10

Från: Giovanni Manghi ***@***.***>
Skickat: den 19 juli 2021 12:02
Till: qgis/QGIS ***@***.***>
Kopia: arer01 ***@***.***>; Mention ***@***.***>
Ämne: Re: [qgis/QGIS] QGIS keeps crashing with labellines (#44093)


You will have to move it

@arer01<https://github.com/arer01> I did it.

**Comment by gioman** [comment]
> If you choose to zoom to entire layer?

@arer01 yes, I zoomed in/out and panned extensively.

**Comment by arer01** [comment]
Ok
Then i dont know what to do
mine crashes immediately if I move the it just a bit
The problem is somewhat connected to this feature

wkt_geom
V_VäGO_ID
Avd
Ålder
ÖH
Area
MultiPolygon (((574713.00302483490668237 6605304.3589897844940424, 574712.72385567671153694 6605303.67074190825223923, 574713.00302483479026705 6605304.3589897844940424, 574713.00302483490668237 6605304.3589897844940424)))
99
1 Bete
40
20
0


If I remove that its doesent crash

Med vänlig hälsning
Åke Eriksson
Tfn. 070-382 67 10

Från: Giovanni Manghi ***@***.***>
Skickat: den 19 juli 2021 12:22
Till: qgis/QGIS ***@***.***>
Kopia: arer01 ***@***.***>; Mention ***@***.***>
Ämne: Re: [qgis/QGIS] QGIS keeps crashing with labellines (#44093)


If you choose to zoom to entire layer?

@arer01<https://github.com/arer01> yes, I zoomed in/out and panned extensively.

**Comment by thbaumann** [comment]
I can also reproduce this crash with QGIS 3.16.8.
I guess it has something to do with the fact that QGIS cuts off some digits of the precision (perhaps also for searching the shortestLine) and sees the last two vertices as identical:

![grafik](https://user-images.githubusercontent.com/20082727/127522438-5f958c6e-7ce0-4277-82cd-a0a321706336.png)

(Checking the validity of the layers shows this error.)

If you move the third vertex around 0.1mm than the problem is gone. I used this wkt:
`MultiPolygon (((
574713.00302483490668237 6605304.3589897844940424,
574712.72385567671153694 6605303.67074190825223923,
574713.00303483479026705 6605304.3599897844940424,
574713.00302483490668237 6605304.3589897844940424
)))`
PS: I know that this is more a workaround than a fix.

**Comment by alexbruy** [comment]
Is this still an issue? I can't reproduce with the latest master (5566e42635)

**Comment by arer01** [comment]
I dont know
you have probably solved it, so you can close the

Med vänlig hälsning
Åke Eriksson
Tfn. 070-382 67 10

Från: Alexander Bruy ***@***.***>
Skickat: den 5 oktober 2023 16:07
Till: qgis/QGIS ***@***.***>
Kopia: arer01 ***@***.***>; Mention ***@***.***>
Ämne: Re: [qgis/QGIS] QGIS keeps crashing with labellines (#44093)


Is this still an issue? I can't reproduce with the latest master (5566e42<https://github.com/qgis/QGIS/commit/5566e4263529df39456314d0b08e8083571b5f03>)
