### ISSUE TITLE
gdal:rastercalculator ignoring greater/less than operator

### ISSUE THREAD

**Issue by jfbourdon** [qgis/QGIS#44092]
**Describe the bug**
When doing a simple operation like `A>0` with _gdal:rastercalculator_, the result will be identical to `A`. However, using `greater(A,0)` will produce the expected result. Operator `<` is also causing the same issue.

**How to Reproduce**
1. Open _gdal:rastercalculator_ processing tool
2. Add any raster at `A`
3. Insert expression `A>0`
4. The output will be identical to the input instead of a binary raster

**QGIS and OS versions**
Windows 10 version 1809
QGIS 3.20.0 (GDAL 3.3.0)

**Additional context**
The problem is not with GDAL because calling _gdal_calc.py_ from the OSGeo4W shell will preduce the expected result ([see](https://github.com/OSGeo/gdal/issues/4083)).

The expression seems to not being completely read as the expression `(A+1)>0` will produce `A+1`. Interestingly, using an expression like `A>0` will produce a file named `0` at _%OSGEO4W_ROOT%\bin_ containing the console output (progression numbers) in addition to the normal file output. However, `A<0` won't produce this file.

The issue wasn't present in QGIS 3.14.1.

**Comment by nyalldawson** [comment]
Can you share the two gdal commands generated for 3.16 and 3.20?

**Comment by jfbourdon** [comment]
**3.14.1**
What is shown at _GDAL/OGR console call_:
```
gdal_calc --calc "A>0" --format GTiff --type Float32 -A C:/temp/input.tif --A_band 1 --outfile C:\temp\output.tif
```
The _processing script_:
```python
processing.run("gdal:rastercalculator",
               {'INPUT_A':'C:/temp/input.tif',
               'BAND_A':1,
               'INPUT_B':None,
               'BAND_B':None,
               'INPUT_C':None,
               'BAND_C':None,
               'INPUT_D':None,
               'BAND_D':None,
               'INPUT_E':None,
               'BAND_E':None,
               'INPUT_F':None,
               'BAND_F':None,
               'FORMULA':'A>0',
               'NO_DATA':None,
               'RTYPE':5,
               'OPTIONS':'',
               'EXTRA':'',
               'OUTPUT':'C:\\temp\\output.tif'})
```
___
**3.20.0**
What is shown at _GDAL/OGR console call_:
```
gdal_calc.bat --overwrite --calc "A>0" --format GTiff --type Float32 -A C:/temp/input.tif --A_band 1 --outfile C:\temp\output.tif
```
I just realised that the switch `--overwrite` is always added now. To me, it seems like a dangerous default value without any way to remove it.

The _processing script_ (exact same as 3.14.1):
```python
processing.run("gdal:rastercalculator",
               {'INPUT_A':'C:/temp/input.tif',
                'BAND_A':1,
                'INPUT_B':None,
                'BAND_B':None,
                'INPUT_C':None,
                'BAND_C':None,
                'INPUT_D':None,
                'BAND_D':None,
                'INPUT_E':None,
                'BAND_E':None,
                'INPUT_F':None,
                'BAND_F':None,
                'FORMULA':'A>0',
                'NO_DATA':None,
                'RTYPE':5,
                'OPTIONS':'',
                'EXTRA':'',
                'OUTPUT':'C:\\temp\\output.tif'})
```

**Comment by nyalldawson** [comment]
Hmm so the only real difference is the .bat command. In that case it looks like this is an osgeo4w packaging issue...

**Comment by nicogodet** [comment]
Duplicate #42724

**Comment by gioman** [comment]
closing as duplicate.
