### ISSUE TITLE
QGIS crash after loading WMS layer via script and zooming in and out

### ISSUE THREAD

**Issue by pathmapper** [qgis/QGIS#44095]
## Bug

QGIS crash after loading WMS layer via script and zooming in and out.

## Steps to reproduce

1. Execute the following script via the Processing Toolbox: [script_for_crash.zip](https://github.com/qgis/QGIS/files/6789824/script_for_crash.zip)

2. Quickly zoom in and out using the mouse scroll wheel.

Note: I'm aware that this is not the way to add a layer from a processing script but QGIS shouldn't crash anyway.

## Report Details

**Crash ID**: [9313eccb44c59d5cc381054fb16f1e27ff672720](https://github.com/qgis/QGIS/search?q=9313eccb44c59d5cc381054fb16f1e27ff672720&type=Issues)

**Stack Trace**
<pre>
QObject::property :
QMetaCallEvent::placeMetaCall :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
QEventDispatcherWin32::processEvents :
QEventLoop::exec :
QgsRasterDataProvider::block :
QgsSingleBandColorDataRenderer::block :
QgsBrightnessContrastFilter::block :
QgsHueSaturationFilter::block :
QgsRasterResampleFilter::block :
QgsRasterProjector::block :
QgsRasterIterator::readNextRasterPartInternal :
QgsRasterDrawer::draw :
QgsRasterLayerRenderer::render :
QgsMapRendererParallelJob::renderLayerStatic :
QgsArchive::zip :
QgsImageOperation::overlayColor :
QgsImageOperation::stackBlur :
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.20.0-Odense
QGIS code revision: decaadbb31
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.0
Running against GDAL: 3.3.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
@pathmapper no crash here even if zooming/scrolling like crazy. 3.16 on Windows and master on Ubuntu 20.04.

**Comment by pathmapper** [comment]
@gioman thanks for checking. I can reproduce it every time, maybe try zooming on different locations.

On Windows (stacktrace above) it's a fresh `3.20.0` install using the standalone installer.

Just tried it with `master` on Ubuntu 20.04 and it crashes also there:

![master_on_ubuntu](https://user-images.githubusercontent.com/20856381/125067131-238b5100-e0b4-11eb-84cb-c9b933db3582.gif)



```
Warning: QObject::setParent: Cannot set parent, new parent is in a different thread
Warning: QObject::connect: Cannot queue arguments of type 'QList<QgsMapLayer*>'
(Make sure 'QList<QgsMapLayer*>' is registered using qRegisterMetaType().)
Warning: QObject::connect: Cannot queue arguments of type 'QList<QgsMapLayer*>'
(Make sure 'QList<QgsMapLayer*>' is registered using qRegisterMetaType().)
QGIS died on signal 11Could not attach to process.  If your uid matches the uid of the target
process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
ptrace: Operation not permitted.
No thread selected
No stack.
gdb returned 256
Aborted (core dumped)
```

**Comment by gioman** [comment]
> Just tried it with `master` on Ubuntu 20.04 and it crashes also there:

@pathmapper can you test on a new QGIS profile?

**Comment by pathmapper** [comment]
@gioman, sure, with the new profile there is no need to zoom, QGIS crashed right after executing the script:

![master_on_ubuntu_2](https://user-images.githubusercontent.com/20856381/125068933-59c9d000-e0b6-11eb-97b8-1952fdd97786.gif)

**Comment by gioman** [comment]
let's see if others confirm.

**Comment by NyakudyaA** [comment]
> let's see if others confirm.

Tested on Ubuntu 20.04 with QGIS 3.20.0 and confirmed the crash happens without even zooming in and out

**Comment by gioman** [comment]
> Tested on Ubuntu 20.04 with QGIS 3.20.0 and confirmed the crash happens without even zooming in and out

@NyakudyaA any chance you can test master?

**Comment by NyakudyaA** [comment]
> > Tested on Ubuntu 20.04 with QGIS 3.20.0 and confirmed the crash happens without even zooming in and out
> 
> @NyakudyaA any chance you can test master?

I have tested on master and the issue still occurs

![master](https://user-images.githubusercontent.com/2510900/126653943-263bbf5f-76d1-40d0-8e83-6a040558ea18.png)

**Comment by rouault** [comment]
Some warning fixes in https://github.com/qgis/QGIS/pull/45254
but the reason for the crash is in your script. Processing scripts are run in a dedicated thread, and it is thus unsafe to interact with global QGIS objects that live in the main thread.
If you add the following just after rlayer = QgsRasterLayer(urlWithParams, layername, 'wms') creation, it seems to solve the issue, 
```
        from qgis.PyQt.QtWidgets import QApplication
        rlayer.moveToThread(QApplication.instance().thread())
```
but I wouldn't completely exclude the risk of multi-threading issues in the lines after. Actually all that code should be run in the main thread, probably using a one-time timer attached to the main thread

So this is mostly a "the qgis python API is just an access to the underlying C++ world, but all the complex rules of Qt still apply, and you can easily shoot yourself in the foot"

**Comment by nyalldawson** [comment]
Just to add to @rouault 's answer -- you can make your algorithm return the "FlagNoThreading" flag to force.it to run in that main thread and avoid these issues.

**Comment by pathmapper** [comment]
@rouault @nyalldawson thanks for explaining the backgound and the hints !
