### ISSUE TITLE
Attribute table - Simple edits to column headers

### ISSUE THREAD

**Issue by Intuos5** [qgis/QGIS#44109]
**Feature description.**
It should be easier to change the data, or actually the data headers within the attribute table. Two things come to mind: field length and name. Refactor fields (processing tools) allows for renaming them, but this should be available out of the box in the Attribute table. 
When working with external databases, the names of attribute fields often have limits to the number of useable characters (8 digits). Would it be possible to add a button to change the field length of the headers, so you can input a longer, non-cryptic name? Similarly, it would be awsome if we could rename the headers. The example here shows an Italian database, which I would prefer to translate to English. A single click solution would make this much easier.

![afbeelding](https://user-images.githubusercontent.com/63149655/125089935-1760bd00-e0cf-11eb-8a20-526dbd3cf3b4.png)

**Comment by andreasneumann** [comment]
You can already do that with column aliases - at least for the column headers. The same alias is used for both forms and attribute tables:

![image](https://user-images.githubusercontent.com/884476/125093885-116cdb00-e0d3-11eb-8bb4-16f3050526cf.png)

Good enough?

**Comment by andreasneumann** [comment]
What do you mean with "change the field length of the headers" ?

The headers aren't static in field length anyway. You can use any length with the alias.

**Comment by Intuos5** [comment]
Yeah, I see that that's the case with Aliases and/ or Refactor Field edits, however, when creating new fields, there are only so many characters you can use (10 to be precise) and I cannot seem to change this).

![afbeelding](https://user-images.githubusercontent.com/63149655/125103610-d079c400-e0dc-11eb-8f2d-d433e2cf0077.png)

I understand that there are multiple ways to do these kind of things, but these all require quite a lot of clicks to get to different menus. What I am after is to be able to edit it from the attribute table directly.

**Comment by gioman** [comment]
>  there are only so many characters you can use (10 to be precise)

@Intuos5 only if you shapefiles, if you use a modern format you can use much more.

**Comment by andreasneumann** [comment]
@Intuos5 - what is wrong with using column aliases? You don't need to rewrite/recalculate attributes. Aliases are displayed instead of the internal name - both in forms and in the header of the attribute table.

Besides: in your above example of the field calculator you selected "integer" instead of a "text (unlimited length)" column data type. You need to pick the correct column type and then you can also use longer text.
