### ISSUE TITLE
Keyboard Shortcuts - Unassignable and missing shortcuts for Layer panel operations 

### ISSUE THREAD

**Issue by Intuos5** [qgis/QGIS#44100]
**Feature description.**
There are several features in the right-click menu (within the Layers panel)  that cannot be assigned to keyboard shortcuts. 
These are, amongst others: 
- Move to Top/ Bottom, typically "Ctrl+Shift+]" and "Ctrl + Shift + ["
- Move Layer Forward/ Backward, typically "Ctrl+]" and "Ctrl + [" 
- Isolate layer toggle, the hide deselected function should be able to toggle, meaning that if you use the function twice, it will return to the layers to the previous visibility state
- The Save feature as... is not assignable
- Group functionality: add selected items to a group, typically Ctrl + G, ungrouping is typically Ctrl + Shift + G

I am pretty sure I have missed more, but these are the ones I really miss up to now.  Please feel free to add additional ones in the comments.

**Comment by uclaros** [comment]
The *Group* shortcut is there, select more than one layer and use *Add group* (ctrl-g) to add those to a group.

A handy workaround for the missing shortcuts you mention, are the context menu's letter shortcuts. You can right click on a layer and hit *T* for move to top, or *B* for bottom. Also, *X* then *A* for save features as, *X* then *S* for save selected features as etc.
Once you get used to it is very productive while not reserving global shortcuts!
