### ISSUE TITLE
QGIS crashes loading TOPODATA and SRTM on macOS BigSur

### ISSUE THREAD

**Issue by rgdepaula** [qgis/QGIS#44117]
Hi guys,

I downloaded QGIS 3.16.8 Hannover and had a problem with raster data on macOSX version. My macOSX is the BigSur version 11.4. The problem i had was with the TOPODATA and SRTM raster. After download it i proceed with add the image in hannover. I select the image and when i click at the button ADD to add it in QGIS project, the application close totally. I need to open the application again and restart from zero.

With QGIS 3.10 for macOSX BigSur i don't have this problem and can do my project without problem.

Anybody had the same problem with hannover in macOSX BigSur? Have anything that you can tell me to resolve this bug?

Thanks,

Rodrigo.

**Comment by gioman** [comment]
> BigSur

@rgdepaula it is with the new apple silicon thing, or still with intel?

**Comment by rgdepaula** [comment]
Hi Giovanni,

This is with intel. My MacBook Pro is intel core i7 with 8GB RAM. 

Att.,

Rodrigo de Paula
Enviado via iPhone

**Comment by gioman** [comment]
> This is with intel. My MacBook Pro is intel core i5 with 8GB RAM.

@rgdepaula attach/link the data.

**Comment by rgdepaula** [comment]
Hi Giovanni,

This is the link for you download an image: https://www.webmapit.com.br/inpe/topodata/

The image is too heavy to attached here. You can choose any quadrant on link. When you choose click on name "Altitude". Will start download a data ".zip". You need to decompress it and try upload at QGIS. If you want try the same image i tried, choose the quadrant 13S42_ZN.

Let me know if you have any doubt.

Rodrigo.

**Comment by gioman** [comment]
@rgdepaula works fine here

![image](https://user-images.githubusercontent.com/1951107/125282552-6dbc3e80-e30f-11eb-83c3-f982aedecd4d.png)

Try with a new QGIS profile, no 3rd party plugins installed.

**Comment by rgdepaula** [comment]
Hi Giovanni,

You are the best man! The problem was solved. I only change the profile and the QGIS accept the TOPODATA image.

Thanks a lot.

Att.,

Rodrigo de Paula.

**Comment by rgdepaula** [comment]
Do you know why this is happening if i use my profile? Because will works only on default profile on macOSX?

Att.,

Rodrigo de Paula.

**Comment by gioman** [comment]
> Do you know why this is happening if i use my profile? Because will works only on default profile on macOSX?

@rgdepaula probably a bad 3rd party plugin.
