### ISSUE TITLE
Double click raster in table of contents

### ISSUE THREAD

**Issue by jridout1234** [qgis/QGIS#44119]
When I try to double click or right click a raster in the layer layers table of contents, QGIS crashes.
[qgis-crash-info-7852.txt](https://github.com/qgis/QGIS/files/6795696/qgis-crash-info-7852.txt)

**Comment by jridout1234** [comment]
Version 3.20.0

**Comment by gioman** [comment]
@jridout1234 try with a new QGIS profile, no 3rd party plugins installed.

**Comment by roya0045** [comment]
crash seem to come from base qgis.

Just putting the stack trace in the txt here:

Crash ID: 773f2a4b17b0258f8298d2b44930adab41f1fbd4


Stack Trace


QObject::parent :
QLayout::addChildWidget :
QStackedLayout::insertWidget :
QgsRasterLayerProperties::addPropertiesPageFactory :
QgisApp::showLayerProperties :
QgisApp::layerProperties :
QgisApp::layerTreeViewDoubleClicked :
QObject::qt_static_metacall :
QAbstractItemView::doubleClicked :
QTreeView::mouseDoubleClickEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.20.0-Odense
QGIS code revision: decaadbb31
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.0
Running against GDAL: 3.3.0

**Comment by elpaso** [comment]
I cannot reproduce on Linux/Master.
