### ISSUE TITLE
Cannot load remote http/https/ftp layer if access is password protected

### ISSUE THREAD

**Issue by SubhadipDatta** [qgis/QGIS#44121]
Unable to add zipped shapefile from ftp server. 
![image](https://user-images.githubusercontent.com/37669664/125189585-6c7b0b00-e256-11eb-96f3-96dfc9ca91bb.png).

Please help me with how can I fix this.

**Comment by gioman** [comment]
@SubhadipDatta 

QGIS version?

Operating system?

URL of datasource?

**Comment by SubhadipDatta** [comment]
Version: QGIS 3.16.7
OS: Windows 11
ftp://ftp.geoespaciotech.com/SHP.zip

**Comment by gioman** [comment]
ftp ftp.geoespaciotech.com
Connected to ftp.geoespaciotech.com.
220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
220-You are user number 1 of 50 allowed.
220-Local time is now 01:14. Server port: 21.
**220-This is a private system - No anonymous login**
220-IPv6 connections are also welcome on this server.
220 You will be disconnected after 15 minutes of inactivity.


```
ogrinfo -so ftp://ftp.geoespaciotech.com/SHP.zip
ERROR 1: Access denied: 530
ERROR 1: Access denied: 530
```

**Comment by SubhadipDatta** [comment]
Yes, It is a secure server and I am using login details on QGIS.

**Comment by gioman** [comment]
> Yes, It is a secure server and I am using login details on QGIS.

@SubhadipDatta we need something we can test.

**Comment by SubhadipDatta** [comment]
I'd: rakesh@geoespaciotech.com
Pass: Rakesh@123

**Comment by SubhadipDatta** [comment]
Copy this I have to delete this from here

**Comment by gioman** [comment]
Same for https if the service is password protected, but works if not.

**Comment by SubhadipDatta** [comment]
So can't access to secure ftp?

**Comment by alexbruy** [comment]
It should be possible to specify credentials in the recent QGIS versions
![image](https://github.com/qgis/QGIS/assets/776954/895cedaf-0265-4626-bb86-ed9d79cd318b)
Please check if it works for you.
