### ISSUE TITLE
r.path not contained in Processing toolbox

### ISSUE THREAD

**Issue by skitourenguru** [qgis/QGIS#44125]
**Describe the bug**
The Grass tool [r.path](https://grass.osgeo.org/grass78/manuals/r.path.html) is missed in the GRASS toolbox.

**How to Reproduce**
1. Menu: Processing/Toolbox
2. Enter r.path in the search field

Tool r.path is not found even though its a valid tool ofGRASS 7.8

**QGIS and OS versions**
3.16.8-4 on Windows 10

**Additional remarks**
- The executable is contained in C:\Program Files\QGIS 3.16.8\apps\grass\grass78\bin: r.path.exe
- It seems the tool was forgotten to add to the toolbox
- This is a qGis problem and not a GRASS plugin problem

**Comment by gioman** [comment]
> This is a qGis problem and not a GRASS plugin problem

@skitourenguru sure, but not a bug but rather a feature request. Feel free to submit the necessary description file.

**Comment by skitourenguru** [comment]
Files are already contained in GRASS folder of qGis.
[r.path.zip](https://github.com/qgis/QGIS/files/6800852/r.path.zip)

**Comment by gioman** [comment]
> Files are already contained in GRASS folder of qGis.

@skitourenguru the description file for the Processing toolbox, not the executable

https://github.com/qgis/QGIS/tree/master/python/plugins/grassprovider/description

**Comment by skitourenguru** [comment]
I tried, please check, if its correct, I am not sure:
[r.path.txt](https://github.com/qgis/QGIS/files/6801951/r.path.txt)

**Comment by gioman** [comment]
> I tried, please check, if its correct, I am not sure:

@skitourenguru can you also please also attach a small dataset (and necessary parameters) I can use to test?

**Comment by skitourenguru** [comment]
input: inputDirection.tif (calculated with r.cost)
format: auto
values: leave empty
raster_path: leave empty
vector_path: myResultingShapeFile.shp
start_coordinates: leave empty
start_points: start_points.shp

It should give you one line feature in myResultingShapeFile.shp

[r.path_testData.zip](https://github.com/qgis/QGIS/files/6802736/r.path_testData.zip)

**Comment by gioman** [comment]
https://github.com/qgis/QGIS/pull/44134
