### ISSUE TITLE
Symbology size on HiDPI screens

### ISSUE THREAD

**Issue by m-kuhn** [qgis/QGIS#44128]
On HiDPI screens, symbol sizes are not correctly represented.

The screenshot highlights the problem, square size on this paper is 5 mm, but circles that should be the same size are only roughly half of it.

Last time I checked (a couple of years ago), this did not affect low res displays (96dpi).

This leads to QGIS projects which are represented:
- incorrectly
- differently, depending on DPI
- differently [on QField which respects DPI](https://github.com/opengisch/QField/issues/1970)

![PXL_20210712_152900156](https://user-images.githubusercontent.com/588407/125315012-031ef900-e337-11eb-976a-16eaf145b4f4.jpg)

**Comment by Houska1** [comment]
Is this related to https://github.com/qgis/QGIS/issues/41248 ?

**Comment by m-kuhn** [comment]
Yes, it looks like it references the same (and that #41248 is better investigated than this one)
Can I ask you to test https://github.com/qgis/QGIS/suites/3219192054/artifacts/74539265 and see if #44132 solves the problem on windows too (I only tested on linux)

**Comment by Houska1** [comment]
I've tested and I'm afraid it doesn't solve 41248. To keep us and others sane, I'll reply there with details (https://github.com/qgis/QGIS/issues/41248)
