### ISSUE TITLE
Crash while digitizing

### ISSUE THREAD

**Issue by fabiogiaco** [qgis/QGIS#44122]
Crash ID: 9b235b5395dc01946b5502171c46c714aaf55ce5

Stack Trace

QgsGeometry::closestVertex qgsgeometry.cpp:387
QgsPointLocator_VisitorNearestVertex::visitData qgspointlocator.cpp:117
Index::~Index :
Index::~Index :
QgsPointLocator::nearestVertex qgspointlocator.cpp:1176
_updateBestMatch qgssnappingutils.cpp:213
QgsSnappingUtils::snapToMap qgssnappingutils.cpp:280
QgsMapMouseEvent::snapPoint qgsmapmouseevent.cpp:52
QgsMapToolAdvancedDigitizing::canvasMoveEvent qgsmaptooladvanceddigitizing.cpp:111
QgsMapCanvas::mouseMoveEvent qgsmapcanvas.cpp:2153
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:475
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:475
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1638
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.18.3-Z�rich
QGIS code revision: 735cc85be9
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

**Comment by gioman** [comment]
>  QGIS Version: 3.18.3-Z�rich

@fabiogiaco 

upgrade to 3.20

try with a new QGIS profile, no 3rd party plugins installed

if the above do not help then attach sample project + data and detail the steps necessary to replicate the crash.
