### ISSUE TITLE
Reading ESRI FileGDB domains into QGIS' attribute form widgets doesn't work

### ISSUE THREAD

**Issue by EranGeo** [qgis/QGIS#44123]
**Describe the bug**

Reading ESRI FileGDB domains into QGIS' attribute form widgets doesn't work. Translating coded values domain to their description in QGIS' attribute table doesn't work as well.

**How to Reproduce**

1. Download attached sample FileGDB dataset. [Test.gdb.zip](https://github.com/qgis/QGIS/files/6797560/Test.gdb.zip)
2. Drag and drop `Point_Test` layer (its only layer) from QGIS' browser into the canvas. Alternatively you can use the 'Data Source Manager'.
3. Toggle editing
4. Add new feature
5. Inspect the prompted attribute form. The field `SettelmentType` isn't being assigned with a value map widget despite its affiliation with a coded value domain.
6. Inspect the layer's attribute table. This field is being loaded with its coded values rather than their description.

**QGIS and OS versions**

QGIS version | 3.20.0-Odense | QGIS code revision | decaadbb31
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.0
PROJ version | 8.0.1
EPSG Registry database version | v10.018 (2021-04-02)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins | db_managerMetaSearchprocessing

**Additional context**

In the last version of QGIS, a new behavior was introduced for reading field domains, from supported datasets types, into QGIS' attribute form widgets ([1](https://www.qgis.org/en/site/forusers/visualchangelog320/index.html#feature-read-field-domains-from-datasets), [2](https://github.com/qgis/QGIS/pull/43013)).
I've tested this, and it doesn't work for me.

Therefore I tested the underlying GDAL installation. Everything look good:
```
GDAL VERSION
GDAL 3.3.0, released 2021/04/26
```
```
ogrinfo --formats
[...]
FileGDB -vector- (rw+): ESRI FileGDB
```
```
ogrinfo -listmdd Test.gdb Point_Test
[...]
SettelmentType: Integer(Int16) (0.0), domain name=SetType
```
```
ogrinfo -fielddomain SetType Test.gdb
[...]
Domain SetType:
  Description: The Type Of The Settelment
  Type: coded
  Field type: Integer(Int16)
  Split policy: default value
  Merge policy: default value
  Coded values:
    1: City
    2: Town
    3: Kibutz

1: Point_Test (Point)
```

Some screenshots of the FileGDB in ArcGIS Pro
![image](https://user-images.githubusercontent.com/47955227/125208886-e8e50c80-e29d-11eb-8964-b32a97e67ea5.png)
![image](https://user-images.githubusercontent.com/47955227/125208892-eda9c080-e29d-11eb-9181-07ec0a942d52.png)
![image](https://user-images.githubusercontent.com/47955227/125208898-f26e7480-e29d-11eb-847a-d7833fe3827c.png)

**Comment by roya0045** [comment]
It's guess this is more of a limitation of the driver rather than qgis as the format was/must be retro-engineered.

**Comment by EranGeo** [comment]
Hi @roya0045 ,
Thank you for your input.

As pointed out in the issue's body, the driver seem to work as expected.

**Comment by nyalldawson** [comment]
I've just tested and this works fine using the OpenFileGDB driver. Are you able to test with this driver so that we can narrow down the issue?

**Comment by EranGeo** [comment]
Hi @nyalldawson , I've disabled the FileGDB driver and left the OpenFiileGDB driver untouched (enabled) and restarted QGIS. Doing so, made QGIS to load the point layer with both its coded and range domains.

**Disabling FileGDB driver**
![disabling fgdb](https://user-images.githubusercontent.com/47955227/128524903-ff8a9215-a6ad-41b2-b287-a83e2ec87769.PNG)


**Inspecting attribute table**
![inspecting point attribute table](https://user-images.githubusercontent.com/47955227/128525698-5de62b40-5791-4a78-ba45-4e6c3857a037.PNG)

**Inspecting layer's attributes form properties**
![attributes form - SettelmentType](https://user-images.githubusercontent.com/47955227/128526102-df63b639-68fc-48d6-a564-df3d0f85556b.PNG)

![attributes form - range field](https://user-images.githubusercontent.com/47955227/128526130-8c29f2cc-9d13-469e-b945-76e0853f8f53.PNG)
