### ISSUE TITLE
python folder doesn't exist

### ISSUE THREAD

**Issue by RugnirViking** [qgis/QGIS#44135]
So I was following the steps to create a qgis python application at https://docs.qgis.org/2.8/en/docs/pyqgis_developer_cookbook/intro.html

and encountered an unusual problem - on a fresh install of the latest version of qgis, the python folder that I must link to does not exist

**How to Reproduce**

1. Install QGIS 3.16.8-Hannover on windows (for what it's worth I installed on a different disk to the OS)
2. following documentation, attempt to set PYTHONPATH to qgis/python
3. observe that it is not possible because qgis/python does not in fact exist

**QGIS and OS versions**

QGIS version
3.16.8-Hannover
QGIS code revision
8c50902ea4
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
db_manager; 
MetaSearch; 
processing

**Comment by RugnirViking** [comment]
![qgis](https://user-images.githubusercontent.com/18635337/125369584-cc6bd180-e37c-11eb-8ce8-5c87cc59fe05.PNG)
a simple visual

**Comment by RugnirViking** [comment]
Note that it is possible the folder the documentation would like is now located at "QGIS\apps\qgis-ltr\python" - does documentation need updating?

**Comment by alexbruy** [comment]
There is nothing wrong here. You are looking not in the QGIS installation directory, but in the OSGeo4W root directory.

**Comment by RugnirViking** [comment]
> There is nothing wrong here. You are looking not in the QGIS installation directory, but in the OSGeo4W root directory.

This is the directory I specified when using the QGIS installer

**Comment by gioman** [comment]
> This is the directory I specified when using the QGIS installer. It's a complete fresh install.

@RugnirViking the folder you are looking for is inside "apps" (the enter the QGIS installation folder).

**Comment by alexbruy** [comment]
> This is the directory I specified when using the QGIS installer. It's a complete fresh install. I don't see how it can be the wrong directory

Right, but QGIS installer is based on the OSGeo4W installer which includes and installs a lot of other software. So OSGeo4W root directory is not the same as QGIS root directory. Also keed in mind that QGIS can be installed in other ways, not only with installer and in such cases root directory can be completely different.
