### ISSUE TITLE
qgis:executesql cannot find input layer if it is a temporary layer with accentuated characters

### ISSUE THREAD

**Issue by juliepierson** [qgis/QGIS#44130]
Hi,
When using qgis:executesql algorithm from processing toolbox, if input layer is a temporary layer created by another algorithm with accentuated characters, such as "Reprojeté" created by reprojectlayer algorithm in french, I get the following error message :
<p><b>virtual:</b> Cannot find layer Reprojet%C3%A9_e83003db_00e8_4abd_8b81_365ecd89c9a4

"Reprojeté" is the name set automatically for output temporary layers created by reprojectlayer in french.

When using executesql with a temporary layer without any accentuated characters, everything goes fine.

I'm using QGIS 3.20 with Ubuntu 20.04.

Hope this is clear, thanks for your time !

**Comment by gioman** [comment]
It is... and in my mind this shows once again that the Processing toolbox should not really be translated.

**Comment by elpaso** [comment]
@gioman I disagree, we need to fix the layer name encoding.

**Comment by gioman** [comment]
> @gioman I disagree,

@elpaso you would if you go and see the atrocious translations given to tools names/parameters in some language.

**Comment by elpaso** [comment]
Well, in that case the translations needs to be fixed as well. I don't think that the solution is to not translate.

**Comment by elpaso** [comment]
QDE it was a bug in virtual layer provider: nothing to do with translations.

**Comment by elpaso** [comment]
> Wow, that was quick ! Thanks !!

Happy to help!

**Comment by themaire** [comment]
Hi,

I am sorry to have this issue too even after Elpaso done. I am using QGIS 3.32.0-Lima on Windows.

For me, in a Python processing algorithm, i use 'native:saveselectedfeatures' as a virtuel layer given to 'qgis:executesql'. 
And I get : _core.QgsProcessingException: <p><b>virtual:</b> Cannot find layer Entit_s_s_lectionn_es_57bc4af3_38f5_45c3_b23c_efd93b645708

Excepted : Entités_sélectionnées.

Big thanks to who see what it is.
