### ISSUE TITLE
Data collected in Qfield not synching with project in QGIS

### ISSUE THREAD

**Issue by Socamiste** [qgis/QGIS#44131]
Hello, I have a problem synching data collected in qfield to the main project in QGIS. The data synchronizes but the original project opens, not the updated version with collected data. I cannot save the file after closing; a message appears "unable to perform zip". My reasoning for saving & closing was in the hope that it would read the data from the modified gpkg and the newly added data would appear. I'm using QGIS 3.14 and the latest version of the qfield app. I have tried updating to 3.16 but this doesn't work either. Any help would be greatly appreciated. I have used qfield synch before with no issue.

**Comment by gioman** [comment]
@Socamiste is this about the "qfield sync" plugin?

**Comment by Socamiste** [comment]
@gioman I think it is, data will not sync using the plugin.

**Comment by Socamiste** [comment]
@gioman to elaborate;
2021-07-12T17:14:18     WARNING    Plugin DigitizingTools : The plugin will be disabled because it crashed QGIS during last startup. Please report an issue and re-enable the plugin when the problem has been solved.
2021-07-12T17:35:54     WARNING    Python error : An error has occurred while executing Python code: See message log (Python Error) for more details.

**Comment by gioman** [comment]
> @gioman I think it is, data will not sync using the plugin.

@Socamiste you must report this in the plugin tracker then.

**Comment by Socamiste** [comment]
@gioman ok, thank you
