### ISSUE TITLE
Unexpected kernel trap mode opening QGIS

### ISSUE THREAD

**Issue by mcingotti** [qgis/QGIS#44141]
Hi all

simply launching QGIS desktop causes a device ran problem

(https://imgur.com/J1aJhhL)

I am using QGIS version 3.16.8 Hannover, but I can't notice the same problem launching older versions (2.18.16) or newer (3.4.4)

What I should do?

Thanks for your precious contribution

**Comment by gioman** [comment]
Does it happens with 3.20?

**Comment by mcingotti** [comment]
Yes it is, too

**Comment by gioman** [comment]
it seems you have a nasty local issue.

**Comment by mcingotti** [comment]
Yes I have checked my memory with a memtest, and a note notice me that my RAM may be vulnerable to high frequency row hammer bit flips. 

But the system crashes just with QGIS, and I would know which relation there is between the software and the unexpected error

**Comment by alexbruy** [comment]
Is this still true with the latest versions? Anyway it looks like a local issue.
