### ISSUE TITLE
"Save Raster Layer As..." GUI problem when using high resolution screens

### ISSUE THREAD

**Issue by stuskier** [qgis/QGIS#44154]
**Describe the bug**

At both 3.18.3 and 3.20, right-clicking a raster layer and selecting _Export > Save As_ brings up the _Save Raster Layer As..._ window, as shown below.

Within the window's _Create Options_ section there is a blank pane, partially hidden by the "+, -, _Validate_ and _Help_" buttons, as denoted by the red arrow.

![Untitled](https://user-images.githubusercontent.com/12805900/125558127-658ea7b1-f089-4349-94c7-210b70eee457.png)

It is impossible to read the pane's contents because the buttons block the view, as shown below:

![Untitled_2](https://user-images.githubusercontent.com/12805900/125558299-f2cfe9ca-f5f0-4b71-917c-ddf1f7607dcb.png)

I think that a simple window reformatting would solve the problem

**QGIS and OS versions**
3.18.3, 3.20.  Windows 10

**Additional context**

**Comment by gioman** [comment]
@stuskier what is your screen resolution?

**Comment by stuskier** [comment]
Hello,

3840 x 2400 pixels

Stu

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by alexbruy** [comment]
Duplicates #31328.
