### ISSUE TITLE
Automatic reading of QML files with GeoTiff < temporal enabled >

### ISSUE THREAD

**Issue by bettellam** [qgis/QGIS#44156]
I have GeoTiff raster files, which have a temporal value (Meteorological radar).
For each of them a QML file is automatically produced, where in addition to the raster symbology, the parameters are set (example):
   **< temporal enabled = "1" mode = "0" fetchMode = "0" >
     < fixedRange >
       < start > 2021-07-13T15: 01: 00Z < /start >
       < end > 2021-07-13T15: 10: 00Z < /end >
     < /fixedRange >
   < /temporal >**

When I load the GeoTiff file into my project, the style symbology of the corresponding QML file is automatically applied,
but the section: **< temporal ... .> .... < /temporal >   IS NOT APPLIED**!!!!

To do this I have to go to:
Properties ---> Symbology ----> Style ---> Load Style
and re-read the same QML file.
At this point everything is OK.

Perhaps it is sufficient to update the automatic loading procedure of the QML file 
or perhaps the same procedure is provided only for the part relating to Style Symbology
Thank you
QGIS 3.16.3 -Win10

**Comment by alexbruy** [comment]
Duplicates #42223
