### ISSUE TITLE
'libfftw3-3.dll not found'" running GRASS tools in Processing on osgeo4w v2

### ISSUE THREAD

**Issue by mrtwister3142** [qgis/QGIS#44155]
**Describe the bug**
v.dissolve fails with error
`grass.exceptions.CalledModuleError: Module run None v.extract -d input=vector_60ee8209678d16 output=outputcd457ad00fe54454948c5eb42aa28a2a type=area layer=1 ended with error
Process ended with non-zero return code 3221225781. See errors in the (error) output.`
in QGIS 3.20.0 (GUI)
and with system error 'libfftw3-3.dll not found' in PyQGIS
![Screenshot 2021-07-14 082627](https://user-images.githubusercontent.com/32396976/125574270-f7c1ca49-d421-4b71-ae94-899be95e2074.png)

**How to Reproduce**

1. Open sample dataset.
2. try to dissolve with v.dissolve by field 'T_Id'
4. See error -->

[v.dissolve.log.txt](https://github.com/qgis/QGIS/files/6814027/v.dissolve.log.txt)

**QGIS and OS versions**

QGIS version
3.20.0-Odense
QGIS code revision
decaadbb31
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.1
PROJ version
8.1.0
EPSG Registry database version
v10.027 (2021-06-17)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2004

Active Python plugins
interlis
QgisModelBaker
SpreadsheetLayers
swiss_locator
db_manager
processing

**Additional context**

Sample dataset:
[test.zip](https://github.com/qgis/QGIS/files/6814050/test.zip)

**Comment by gioman** [comment]
Confirmed, it seems to sort pf packing problem in osgeo4w v2.

**Comment by agiudiceandrea** [comment]
It seems the fftw package (which ships libfftw3-3.dll) is missing in the OSGeo4w v2 repository, while it is present in the old OSGeo4w v2 repository and installed as a GRASS dependency.
Maybe it could be better to file a ticket in the OSGeo4W trac system https://trac.osgeo.org/osgeo4w/

**Comment by agiudiceandrea** [comment]
OSGeo4W v2: missing fftw package - GRASS tools not working
https://trac.osgeo.org/osgeo4w/ticket/685
