### ISSUE TITLE
Update/reconfigure GDAL used in workflow MinGW64 build?

### ISSUE THREAD

**Issue by Houska1** [qgis/QGIS#44150]
In testing something unrelated at https://github.com/qgis/QGIS/pull/44132, it turns out the MinGW64 build used in the pull check workflow (https://github.com/qgis/QGIS/blob/master/.github/workflows/mingw64.yml) compiles with GDAL 3.2.2, itself apparently compiled without internal libtiff since it won't recognize LERC-compressed tiff rasters.

Any reason **not** to update it with GDAL **3.3**.0, compiled **with** internal libtiff?  

I note this has been fixed in the OSGeo4W builds, most recently at https://github.com/jef-n/OSGeo4W/commit/6715368dec3a783d448575a0667ca37d9f33a468

**Comment by agiudiceandrea** [comment]
Maybe @manisandro could have more info on this.

**Comment by manisandro** [comment]
gdal-3.3.1 is packaged, the docker container used in the workflow needs to be rebuilt. Per Fedora package policy, bundled libraries are unbundled whenever possible, hence the external libtiff is used.

**Comment by Houska1** [comment]
> Per Fedora package policy, bundled libraries are unbundled whenever possible, hence the external libtiff is used.

Trouble is, per https://gdal.org/drivers/raster/gtiff.html, LERC compression and decompression are supported only with internal libtiff, so layers that were compressed using LERC (which work fine with OSGeo4W installs) come back as "unavailable" to QGIS.

I understand this is just a testing environment, and sometimes things break. But in general by default we should test against the most functionality-rich simple configurations of our ecosystem (that part which is integral, of course, I don't mean we need to add all sorts of plugins and GRASS and ... and ...), except when we deliberately want to see what happens if it's hobbled.

Anyway, I won't belabour the point if it's just me with an isolated problem -- I can test with other projects! -- but I think "doesn't support all file formats" is a good exception to "wherever possible".

**Comment by manisandro** [comment]
Most Linux distros our there unbundle libtiff to use the system version, would be interesting to know why an internal libtiff has to be used resp. whether there is any way to upstream the necessary changes to libtiff. Perhaps @rouault knows more?

**Comment by rouault** [comment]
> LERC compression and decompression are supported only with internal libtiff,

Ah, the doc lags behind. I'll fix it. Since GDAL 3.3.0, LERC compression is possible either using internal libtiff, or using external libtiff 4.3.0 built against https://github.com/esri/lerc since the LERC codec has been moved to upstream libtiff

**Comment by alexbruy** [comment]
Can we close this? As far as I can see, GDAL 3.7.2 is used now and according to @rouault LERC compression should be there since GDAL 3.3.0.

**Comment by Houska1** [comment]
I can't test if LERC is handled by this specific build now, but enough water has flown under the bridge since then that if the issue were to persist, it would have a different dynamic and solution. So I'm closing until/unless someone else encounters a continuation of the issue.
