### ISSUE TITLE
Joined fields are gone when embedding layer in other project

### ISSUE THREAD

**Issue by gdcooman** [qgis/QGIS#44162]
**Describe the bug**

I have a project that contains a base map that is to be used in future projects. In this project I have multiple layers that have joins. These work fine in the base map project itself. However, when I go to embed the base map into a new project, the joins are not there anymore.

**How to Reproduce**

1. Make a project that has atleast two layers. Put a join on one of the layers.
2. Go into a different project and embed both layers that were joined from the first project.
3. Look at the fields of the embedded layer and see that the joined field is not there.

**QGIS and OS versions**

QGIS-version 3.20.0-Odense
Qt version  5.15.2
Python version 3.9.5
GDAL/OGR version 3.3.0
PROJ version 8.0.1
EPSG-register databaseversion v10.018(2021-04-02)
GEOS version 3.9.1-CAPI-1.14.2
SQLite version 3.35.2
PDAL version 2.3.0
PostgreSQL client version 13.0
SpatiaLite version 5.0.1
QWT version 6.1.3
QScintilla2 version 2.11.5
OS version Windows 10 Version 2009
Active Python plug-ins db_manager
MetaSearch
processing

**Comment by gdcooman** [comment]
Update: I just discovered that when you make a duplicate from the embedded layer or group, the joins do work. 

For single layers: right click and choose 'Duplicate Layer'. 

For groups: right click and choose 'Copy Group' and then 'Paste Layer/Group'.

**Comment by troopa81** [comment]
@gdcooman Does this issue still exist in last 3.22.4 or 3.24 ? #46411 should have fixed it

**Comment by gdcooman** [comment]
At the moment I am not actively working with QGIS anymore. Maybe someone else can verify it?
Thanks for the fix btw!

**Comment by troopa81** [comment]
I close the issue, please re-open it if you think the issue still exists
