### ISSUE TITLE
OGR utils loses millisecond and timezone information when parsing GeoJSON features

### ISSUE THREAD

**Issue by komima** [qgis/QGIS#44160]
**Describe the bug**

Parsing GeoJSON features with QgsOgrUtils loses milliseconds and timezone information from the timestamp values.

**How to Reproduce**

Run these commands in QGIS Python console:
```python
the_json = lambda timepart: '{"type": "Feature","id": 1,"geometry": {"type": "Point","coordinates": [0,0]},"properties": {"some_time_field": "2020-01-01T' + timepart + '"}}'
test_output = lambda timepart: QgsJsonUtils.stringToFeatureList(the_json(timepart), QgsJsonUtils.stringToFields(the_json(timepart)))[0]['some_time_field'].toString(Qt.ISODateWithMs)

# and then run some tests with different source timestamps

test_output('22:00:10')
test_output('22:00:10Z')
test_output('22:00:10.123Z')
test_output('22:00:10.123+01:00')
test_output('22:00:10.123-07:00')

```

Observe that all of the above timestamp values in the JSON result in the same string value using `QDateTime().toString(Qt.ISODateWithMs)`, which is what for example postgres provider [uses](https://github.com/qgis/QGIS/blob/master/src/providers/postgres/qgspostgresconn.cpp#L1230) to get the string representation to the SQL query.

**QGIS and OS versions**

QGIS 3.16.8 on Windows 10 using osgeov1 network installer.

**Additional context**

GDAL supports millisecond precision (as implemented [here](https://trac.osgeo.org/gdal/wiki/rfc56_millisecond_precision)), QGIS seems to use a non-millisecond non-timezone preserving parsing [here](https://github.com/qgis/QGIS/blob/master/src/core/qgsogrutils.cpp#L350) (and also millisecond but non-timezone preserving parsing [here](https://github.com/qgis/QGIS/blob/master/src/core/qgsogrutils.cpp#L137) for some other stuff implemented more recently).

**Possible fix**

Include milliseconds when creating the QTime, and apply the timezone flag to the QDateTime. Flag value is 100 +- 1 for each 15min offset from UTC, so the constructor that accepts the spec and offset in seconds could be used instead?

`value = QDateTime( QDate( year, month, day ), QTime( hour, minute, second, millisecond ), Qt::OffsetFromUTC, (tzf - 100) * 15 * 60 );`.

**Comment by Joonalai** [comment]
I will start investigating this one.
