### ISSUE TITLE
Can't add OpenStreetMap XYZ tile layer to canvas: Invalid Data Source URL

### ISSUE THREAD

**Issue by i-s-o** [qgis/QGIS#44166]
**Checklist before submitting**

- [x] Search through existing issue reports and gis.stackexchange.com to check whether the issue already exists
- [x] Test with a [clean new user profile](https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html?highlight=profile#working-with-user-profiles).
- [ ] N/A - Create a light and self-contained sample dataset and project file which demonstrates the issue

**Describe the bug**

In the latest qgis-dev nightly, adding OpenStreetMap layer from the Browser panel generates the following error message:

`Invalid Data Source : type=xyz&url=https://tile.openstreetmap.org/%7Bz%7D/%7Bx%7D/%7By%7D.png&zmax=19&zmin=0 is not a valid or recognized data source.`

**How to Reproduce**

Double-click on OpenStreetMap item under XYZ in Browser panel.

![image](https://user-images.githubusercontent.com/1661549/125670888-7b852861-dda7-4577-bdc1-900096202aa8.png)

**QGIS and OS versions**

Library | Version
--- | ---
QGIS version | 3.21.0-Master
QGIS code revision | 38ea3cc0
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.2.2
PROJ version | 8.0.1
EPSG Registry database version | v10.018 (2021-04-02)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.5
PostgreSQL client version | 11.5
SpatiaLite version | 5.0.1
QWT version | 6.1.5
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2004
This copy of QGIS writes debugging output.
Active Python plugins | 
| db_manager
| grassprovider
| MetaSearch
| processing
| sagaprovider

**Additional context**

Going back a few commits,
Works: https://github.com/qgis/QGIS/runs/3050204740
Doesn't work: https://github.com/qgis/QGIS/runs/3054848424

@elpaso: is there a chance #44139 is the reason?

**Comment by elpaso** [comment]
No, this is the reason: https://github.com/qgis/QGIS/pull/44085#issuecomment-879965536

**Comment by gioman** [comment]
Fixed by https://github.com/qgis/QGIS/pull/44177
