### ISSUE TITLE
Missing refresh conn icon in GPS tools

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS#44165]
I'm not very familiar with the gps tools in QGIS, but I found an older screendump to refresh the usb/gps/dev connections in the Serial Device dropdown, But in my current install the button is empty:

![Screenshot-20210714183232-857x493](https://user-images.githubusercontent.com/731673/125665749-e6a9b1d1-62e2-4ed2-ae9e-b17a8de34e5a.png)

Can others confirm?

**Comment by nyalldawson** [comment]
I can confirm!
