### ISSUE TITLE
georeferencer does not display the pdfs 

### ISSUE THREAD

**Issue by EPINRAP** [qgis/QGIS#44172]
Hi
in qgis 3.20 the georeferencer does not display the pdfs

**Comment by gioman** [comment]
@EPINRAP please add all the requested infos.

**Comment by EPINRAP** [comment]
and what are the requested infos ?

**Comment by nicogodet** [comment]
Try with a new profile

**How to Reproduce**



1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error -->

Provide sample data to reproduce the bug

**Comment by Stuggi92** [comment]
Hi,
I have the same problem with QGIS 3.20.
If I want to open a PDF in the georeferencing window to set control points, only vector information is loaded from the PDF and no raster.

**any PDF Viewer**
<img width="977" alt="View PDF Viewer" src="https://user-images.githubusercontent.com/87688672/126269485-040bbf82-4456-4c81-b435-713302ca9d8c.PNG">

**view in georeferencing window**
<img width="977" alt="View Georeferencer" src="https://user-images.githubusercontent.com/87688672/126269492-577672ba-8902-46ff-80c7-3d9e633632bc.PNG">
