### ISSUE TITLE
Attributes form takes lots of time to open if it's made of several fields

### ISSUE THREAD

**Issue by RobiFag** [qgis/QGIS#44178]
**Describe the bug**
I have a PostgreSQL table with five thousand rows, a hundred columns and it is related to 5 other tables through 1-n relations. An attributes form consisting of 5 tabs has been created and the 100 columns and relations have been divided into it. The value map widget has been set for most of the columns. The form takes a long time (10/20 seconds) to open both when a geometry is queried and created.

The gif below shows the behavior:
![attributes_form](https://user-images.githubusercontent.com/25825472/125749027-7f50098f-934b-45ea-a845-c7df0c19058e.gif)

**QGIS and OS versions**
QGIS version 3.16.8-Hannover and earlier
QGIS code revision 8c50902ea4
Compiled against Qt 5.11.2
Running against Qt 5.11.2
Compiled against GDAL/OGR 3.1.4
Running against GDAL/OGR 3.1.4
Compiled against GEOS 3.8.1-CAPI-1.13.3
Running against GEOS 3.8.1-CAPI-1.13.3
Compiled against SQLite 3.29.0
Running against SQLite 3.29.0
PostgreSQL Client Version 11.5
SpatiaLite Version 4.3.0
QWT Version 6.1.3
QScintilla2 Version 2.10.8
Compiled against PROJ 6.3.2
Running against PROJ Rel. 6.3.2, May 1st, 2020
OS Version Windows 10 (10.0)

**Comment by gioman** [comment]
I also observed this in several occasions.

**Comment by lucalanteri** [comment]
Confirmed. With 30K records, a 40Mbits connection 135 field and 10 related tables the mask needs about 1minute to open.

**Comment by lucalanteri** [comment]
The problem appears to be related to version 3.18. 
The same form opens in 2 seconds with QGIS 3.16 and in 20 seconds with QGIS 3.18

**Comment by RobiFag** [comment]
I confirm the behavior described by @lucalanteri. In my case with QGIS 3.16 opens the form in 15 seconds while QGIS 3.18 closed unexpectedly after about a minute from the query.

**Comment by elpaso** [comment]
If anyone could provide a test project with a minimal set of data that we can use to reproduce the issue we could try to profile the application and see if there is a fix for this problem.

**Comment by lucalanteri** [comment]
Can I sent to you a project connected to my PG database ?

**Comment by elpaso** [comment]
@lucalanteri as long as I can open it from my machine, yes. 

Please try to remove all layers that are not relevant to reprouce the issue, it will be much easier to isolate the problem.

**Comment by lucalanteri** [comment]
@elpaso I sent you a project in private

**Comment by lucalanteri** [comment]
Seems to work fine on QGIS 3.20 and master. The problem for me is limited to QGIS 3.18
