### ISSUE TITLE
[BUG] COG files within .vrt wrapper are treated as normal Tiffs.

### ISSUE THREAD

**Issue by ashleysommer** [qgis/QGIS#44188]
**Describe the bug**
I have some Cloud-Optimised Geotiff files in a directory. They are 12 tiles, making up a complete raster image. The tiles are stitched together using a .vrt file. All of these files are on Object Store in the cloud, they are accessible via HTTP.
Displaying a single COG file works fine, loads quickly and UI is responsive, as expected for a COG. However adding a raster layer with the .vrt file, QGIS downloads the whole of each tile .tif file locally before displaying them. It seems that using vrt, QGIS does not attempt to check if the geotiff files are COG.

**How to Reproduce**

1) (A single COG - this works correctly) Add Raster Layer -> Protocol HTTP -> enter URL:
`https://swift.rc.nectar.org.au/v1/AUTH_05bca33fce34447ba7033b9305947f11/landscapes-csiro-aet-public/2012/2012_02_01/CMRSET_LANDSAT_V2_1_2012_02_01_ETa_0000043776-0000043776.cog.tif`
It takes a few seconds to load, and appears quickly. zooming in and out works pretty well. (this by itself is a 3GB tile).

2) (Single COG via /vsicurl/ - This also works) Delete that layer, Add Raster Layer -> File Source -> enter path:
`/vsicurl/https://swift.rc.nectar.org.au/v1/AUTH_05bca33fce34447ba7033b9305947f11/landscapes-csiro-aet-public/2012/2012_02_01/CMRSET_LANDSAT_V2_1_2012_02_01_ETa_0000043776-0000043776.cog.tif`
This takes less time to load, appears very quickly, and zooming in and out works perfectly. This is because all the COGs handling is done at the GDAL level.

3) (vrt file - this crashes) Delete that layer, try a .vrt file with all the tiles. Try HTTP first:
Add Raster Layer -> HTTP Protocol -> enter URL:
`https://swift.rc.nectar.org.au/v1/AUTH_05bca33fce34447ba7033b9305947f11/landscapes-csiro-aet-public/2012/2012_02_01/2012_02_01_index.vrt`
It freezes QGIS and the process starts downloading huge amounts of data (over 10GB before I killed it).

4) (vrt file via /vsicurl/ - this workaround kind-of works) Kill QGIS. Try the same layer with GDAL:
Add Raster Layer -> File Source -> Enter path:
`/vsicurl/https://swift.rc.nectar.org.au/v1/AUTH_05bca33fce34447ba7033b9305947f11/landscapes-csiro-aet-public/2012/2012_02_01/2012_02_01_index.vrt`
This still freezes QGIS, but only for about 60 seconds, it downloads around 1GB of data, and shows the whole stitched raster, zooming and panning work as expected.

**Versions**

I'm on Ubuntu 20.04, using QGIS via the Flatpak distribution.
I observed this behaviour on QGIS v3.16, v3.18, and just updated to v3.20 and see the same behaviour still.

**Comment by ashleysommer** [comment]
I tried adding Virtual Overviews to my VRT with:
`gdaladdo --config VRT_VIRTUAL_OVERVIEWS YES ./2012_02_01_index.vrt 2 4 8 16 32 64 128`
This added the correct OverviewList to my .vrt, but getting the same behavior as above in QGIS.

**Comment by ashleysommer** [comment]
Update, seems like in QGIS v3.20 scenario 4 behaves the same as scenario 3. It downloads 10GB of data then crashes, I have to kill it.

In earlier versions of QGIS I think this was different.

**Comment by ashleysommer** [comment]
Related (I think): http://osgeo-org.1560.x6.nabble.com/gdal-dev-VRT-and-COG-td5383256.html

**Comment by gioman** [comment]
> I'm on Ubuntu 20.04, using QGIS via the Flatpak distribution.

@ashleysommer curiuosly with the same QGIS version and OS for me the case 2) does not work (it says datasource not valid), what GDAL version use your installation?

**Comment by gioman** [comment]
> Related (I think): http://osgeo-org.1560.x6.nabble.com/gdal-dev-VRT-and-COG-td5383256.html

@ashleysommer seems so. But in this case not sure there is much can be easily done in QGIS.

**Comment by ashleysommer** [comment]
>curiuosly with the same QGIS version and OS for me the case 2) does not work (it says datasource not valid), what GDAL version use your installation?

I'm using the version of GDAL baked into the flatpak image on flathub. Its v3.2.1.
When reproducing the issue, please follow the directions carefully. Scenarios 2) and 4) state to use the "File" Source Type in Raster layer, not "Protocol" source type. Place the `/vsicurl/http://...` path in the "source" box

**Comment by gioman** [comment]
> When reproducing the issue, please follow the directions carefully. Scenarios 2) and 4) state to use the "File" Source Type in Raster layer, not "Protocol" source type. Place the `/vsicurl/http://...` path in the "source" box.

I realized that before clicking "add" it is necessary for "Options" to show up. Anyway it is really not clear how to do that as just pasting the URL and waiting a bit (I image to allow QGIS to retrieve the datasource infos, maybe via gdalinfo) do not seems to be enough.

![image](https://user-images.githubusercontent.com/1951107/126067733-0238d47e-7c9f-4941-aa94-0e0846322915.png)

**Comment by ashleysommer** [comment]
> just pasting the URL and waiting a bit (I image to allow QGIS to retrieve the datasource infos, maybe via gdalinfo) do not seems to be enough.

Sorry, I don't understand what that means. Are you having trouble reproducing this bug?

**Comment by gioman** [comment]
> Are you having trouble reproducing this bug?

no. I'm just noting that when pasting the URI/URL is needed to wait for the "options" to show, if one clicks "add" before it gets always an error. This is not very obvious as "options" can take a while to show up.

**Comment by rouault** [comment]
>  I'm just noting that when pasting the URI/URL is needed to wait for the "options" to show, if one clicks "add" before it gets always an error.

how can you do that ? The UI is freezed until the Options zone is updated

I cannot reproduce any difference of behaviour between the /vsicurl/ way or the "HTTP Protocol" way. This is quite slow for VRT (several minutes), due to QGIS querying statistics. Performance could be improved by storing the statistics in the VRT by doing "gdalinfo -stats the.vrt"

**Comment by ashleysommer** [comment]
@rouault 
You've solved my issue. Generating the stats in the VRT using `gdalinfo -stats the.vrt` helped significantly. It took 9 minutes at 100% CPU to generate the stats for my tiles, and bake it into the VRT file. And that corresponded to the approx 10 minutes freeze I got in QGIS when loading the VRT previously.

When loading the new VRT with stats in it, it loads _instantly_.

Example VRT you can try yourself to see the difference: 
https://swift.rc.nectar.org.au/v1/AUTH_05bca33fce34447ba7033b9305947f11/landscapes-csiro-aet-public/2018/2018_01_01/CMRSET_LANDSAT_V2_1_2018_01_01_ETa.vrt

**Comment by gioman** [comment]
> how can you do that ? The UI is freezed until the Options zone is updated

@rouault just realized that if there is a blank space in front of the URI than it will not show the "options" zone and the user can still press "add" and get the "datasource not valid" error.

**Comment by ashleysommer** [comment]
I think this can be closed. The main issue is the stats weren't included in the VRT file, and for some reason GDAL couldn't ingest pre-computed the stats from the underlying COGs, so the stats needed to be recomputed when adding the layer. On these huge files this takes a very long time pulls down many GB of data and freezes the UI, but I guess thats just how GDAL operates. Adding the stats to the VRT metadata fixed this problem.
