### ISSUE TITLE
Select input visually in Modeler

### ISSUE THREAD

**Issue by uclaros** [qgis/QGIS#44197]
**Feature description.**
When there are many similar algorithms in a model, one has to rename every one of them in order to locate them on the inputs' drop down lists.
It would be very handy if it was possible to choose an input visually by clicking on a model's existing element.
This could be implemented by adding a "pick from model canvas" button next to the input list, when the input type is set to *algorithm output* or *model input*.

**Comment by callis** [comment]
Or drag and drop like in alteryx

**Comment by alexbruy** [comment]
Probably same as #21545

**Comment by uclaros** [comment]
I guess I missed that one! The suggested implementation is different but the idea is pretty much the same.
