### ISSUE TITLE
Topological Vertex editing has become slow

### ISSUE THREAD

**Issue by uclaros** [qgis/QGIS#44198]
**Describe the bug**
When moving vertices on big geometries while having *topological editing* enabled and overlap avoidance on *Follow advanced configuration*, even with no layers enabled to snap or avoid overlaps, then each vertex move takes seconds to complete.

This was introduced by #41658
(pinging @lbartoletti )

**How to Reproduce**
1. Add a polygon layer
2. Enable topological editing
3. Set overlap avoidance to Follow advanced configuration
4. Start editing
5. Use the vertex tool to move a vertex on a large polygon
6. wait 4 seconds for each 2000 vertices in the polygon (on my machine)

**QGIS and OS versions**
02266ef8e6 on Debian bullseye

**Comment by Jean-Roc** [comment]
This behavior can be reproduced on QGIS 3.21 56b9d808ff when using *topological editing* and *avoid overlaps on active layer*

**Comment by uclaros** [comment]
Any update on this @lbartoletti ? Since this was a sponsored feature maybe fixing the regression could be sponsored too?

**Comment by Jean-Roc** [comment]
@uclaros I can reply on the sponsored part, my 2021's budget is closed and 2022's isn't available yet

**Comment by lbartoletti** [comment]
For myself, unfortunately, I have no time to address this issue and others in this bugfix period. I hope I'll can next months.

**Comment by uclaros** [comment]
Thanks @Jean-Roc  for eventually taking care of this :)
