### ISSUE TITLE
QGIS crashes when trying create a Shapefile bigger than 4GB

### ISSUE THREAD

**Issue by tschmetzer** [qgis/QGIS#44202]
When starting a **raster to vectorlayer processing algorithm** error messages are logged in the window after ~40 min and a minute later QGIS crashes. The error message states: 

``` Feature could not be written to <filename>: Feature creation error (OGR error: failed to write shape object. File size cannot reach 4294967276+136.) ``` as can be seen in the following screenshot:

![2021-07-17 03_15_11-Schnittmenge — QGIS](https://user-images.githubusercontent.com/67278094/126029986-32e32a4f-7ff7-4dd8-bb5d-dea64e937bf5.png)

The disk was not full and a 4 GB file size limit doesn't seem to exist as I was able to manually create test files >4GB:
![2021-07-17 03_17_16-temp](https://user-images.githubusercontent.com/67278094/126029928-93123438-f439-428b-8b03-b9e78e1ae970.png)

As input to the algorithm I used the following raster map: (~3.3 GB file size, TIFF file - Width: 144000, Height: 46000, Float32)
https://solargis.com/file?url=download/World/World_DNI_GISdata_LTAy_AvgDailyTotals_GlobalSolarAtlas-v2_GEOTIFF.zip&bucket=globalsolaratlas.info

The error occurs with the raster algorithms "pixels to points" as well as "raster to polygons". Other algorithms haven't been tested but I don't suspect the algorithms themselves. Rather the OGR seems to have a problem writing more than 4 GB. Can't imagine this is an accepted OGR restriction?

<img src="https://user-images.githubusercontent.com/67278094/126030031-afb164c6-37f7-4c83-ba68-6d37e5600b1a.png" width=75% height=75%>
<img src="https://user-images.githubusercontent.com/67278094/126030044-dfeb5258-9ba3-4e9d-b943-ef7f3946cc7b.png" width=75% height=75%>

I am using the latest official QGIS version and the same issue had also occurred in a previous 3.18.x before updating to this latest version:

QGIS version | 3.20.0-Odense | QGIS code revision | decaadbb31
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.1
PROJ version | 8.1.0
EPSG Registry database version | v10.027 (2021-06-17)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2004
  |   |   |  
Active Python plugins | GroupStatslatlontoolsnominatimQuickOSMdb_managerprocessing

**Comment by tschmetzer** [comment]
> As input to the algorithm I used the following raster map: (~3.3 GB file size, TIFF file - Width: 144000, Height: 46000, Float32)
> https://solargis.com/file?url=download/World/World_DNI_GISdata_LTAy_AvgDailyTotals_GlobalSolarAtlas-v2_GEOTIFF.zip&bucket=globalsolaratlas.info

By the way the issue occurred as well with a previous version of the same input source file with a way smaller resolution. I couldn't find it's source again but I still have it on my disk. I didn't know where to upload the 300 MB file (Width 43200, Height 9600, Float32) so I only referenced the above 3.3 GB file.

Another question that crossed my mind in that context is wether a raster input the size 43200 x 9600 x 32Bit=1.658.880.000 Bytes with maybe only one third of the pixels filled with data (the rest is water with no data) can cause a shape file to grow larger than 4 GB. I need to add that I don't know anything about sizes of the structure and feature in a vector layer.

**Comment by agiudiceandrea** [comment]
The ESRI Shapefile format has various limitations.
See http://webhelp.esri.com/arcgisdesktop/9.3/index.cfm?TopicName=Geoprocessing_considerations_for_shapefile_output for detailed information, among which:

> There is a 2 GB size limit for any shapefile component file, which translates to a maximum of roughly 70 million point features. The actual number of line or polygon features you can store in a shapefile depends on the number of vertices in each line or polygon (a vertex is equivalent to a point).

The GDAL/OGR driver has increased that limit up to 4 GB for the .shp component, without limitation for the .dbf component.
See https://gdal.org/drivers/vector/shapefile.html#size-issues:

> Geometry: The Shapefile format explicitly uses 32bit offsets and so cannot go over 8GB (it actually uses 32bit offsets to 16bit words), but the OGR shapefile implementation has a limitation to 4GB.
> 
> Attributes: The dbf format does not have any offsets in it, so it can be arbitrarily large.
> 
> However, for compatibility with other software implementation, it is not recommended to use a file size over 2GB for both .SHP and .DBF files.

You could use another format like e.g. GeoPackage or Spatialite.

Anyway, QGIS should not crash in this situation.

**Comment by tschmetzer** [comment]
Thanks for that valuable information. I tried using GeoPackage and the file size grew until my disk was full (127 GB) and then there was a QGIS crash as well yet with a slightly different error message mentioning a full disk. Unfortunately the screenshot I took wasn't saved properly as the disk was full and the screenshot saving didn't throw an appropriate error message ;)

**Comment by agiudiceandrea** [comment]
@tschmetzer if your raster has 43'200 x 9'600 = 414'720'000 cells containing float32 values, and you use the "Raster pixels to polygons" processing tool, then the corresponding polygon vector layer usually needs at least 8 bytes fox X coordinate and 8 bytes for Y coordinate of each of the 4 vertices (actually 5 in some formats) of each polygon for each pixel (= 64/80 bytes per pixel), plus 8 bytes for a FID and 4/8 bytes for the cell value, plus some overheads ... you will arrive at least about 100/200 or more bytes needed for each pixel of the raster.
