### ISSUE TITLE
Usability issues with "Create mesh layer" dialog?

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#44226]
While playing with the "create new mesh layer" dialog, I found some issues/inconsistencies with other create dialogs:
![image](https://user-images.githubusercontent.com/7983394/126065341-3d60c81c-e1ad-49cc-a8a4-9bc4c4dba58d.png)
- the "file name": should be the first option to select
- the "layer name" option: by default, there's none, unless the file is a container (gpkg, sqlite). the layers panel shows the file name.
- the "file format": it's already available in the file name. Is it necessary?
- the "Initialize mesh" section: It looks weird to me that an option deactivates a setting that is set above (ref. CRS) but no idea where this could be placed if we also want to display selected layer metadata. I also wonder if we can consider this section as a complement, meaning that a checkbox with only files to pick, default behavior being false and empty.
![image](https://user-images.githubusercontent.com/7983394/126072194-53dfa4b6-eb33-4865-a184-797af6c6cd28.png)
If any interest, GUI changes are available in at https://github.com/qgis/QGIS/compare/master...DelazJ:newMeshV2?expand=1 (I prefer to let coding part to more skilled people)

**Comment by vcloarec** [comment]
@DelazJ , thanks for this. I will work on it later when I will fine time...

**Comment by vcloarec** [comment]
>     * the "file format": it's already available in the file name. Is it necessary?

I find interesting to have also here the file format to show explicitly to the user all the possibility.

**Comment by DelazJ** [comment]
@vcloarec Seems all is done. Or is anything left here?

**Comment by DelazJ** [comment]
Let's close then...
