### ISSUE TITLE
Unable to import OpenAIR files in QGIS 3.20

### ISSUE THREAD

**Issue by thommo17** [qgis/QGIS#44238]
**Describe the bug**

In QGIS 3.18 you could import OpenAIR .txt files but in QGIS 3.20 you can't (not a valid or recognized data source)

**How to Reproduce**

Drag any OpenAIR file to QGIS and it will say it isn't recognised

**QGIS and OS versions**

QGIS version
3.20.0-Odense
QGIS code revision
decaadbb31
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.0
PROJ version
8.0.1
EPSG Registry database version
v10.018 (2021-04-02)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
Beeline
pgRoutingLayer
SRTM-Downloader
db_manager
MetaSearch
processing

**Additional context**

Attached is a file that works in 3.18 but not 3.20

[Australian Airspace 05 November 2020_Class R_v1.txt](https://github.com/qgis/QGIS/files/6838176/Australian.Airspace.05.November.2020_Class.R_v1.txt)

**Comment by nyalldawson** [comment]
The openair driver was moved to the unmainted "GDAL extras" drivers at https://github.com/OSGeo/gdal-extra-drivers , and is no longer included with QGIS. You could try filing a ticket with https://trac.osgeo.org/osgeo4w/ and request that it's packaged for QGIS, but you'll likely have more luck if you can find a financial sponsor for the GDAL driver and get it moved back from the extras package to the main GDAL library.
