### ISSUE TITLE
Export Atlas algorithms filter options are ignored when printing

### ISSUE THREAD

**Issue by NyakudyaA** [qgis/QGIS#44242]
# Problem

When using the export algorithm with the filter and coverage layer selected. The algorithm prints all the features exposed in the atlas not a subset of the features.

To replicate 
* Load the project in the geopackage attached
* Choose the algorithm export atlas as either image or pdf
* Set the filter in the dialog
![example-settings](https://user-images.githubusercontent.com/2510900/126138221-1195541a-777e-4007-ad07-807b1ef50d03.png)

* Run the tool
* Notice that the output contains all the features

![qgis-ver](https://user-images.githubusercontent.com/2510900/126138363-a660b86c-b531-4b25-a9cb-f255605526d6.png)
[index.zip](https://github.com/qgis/QGIS/files/6839639/index.zip)

**Comment by roya0045** [comment]
Can confirm, something may be wrong with or the underlying code https://github.com/qgis/QGIS/blob/2d1aa68f0d044f2aced7ebeca8d2fa6b754ac970/src/analysis/processing/qgsalgorithmlayoutatlastoimage.cpp#L143

**Comment by Samweli** [comment]
confirmed this, working for a solution.
