### ISSUE TITLE
Checking for duplicates in Check Geometries hits assert

### ISSUE THREAD

**Issue by uclaros** [qgis/QGIS#44246]
**Describe the bug**
On Check Geometries core plugin when running with *Check for duplicates* enabled on a polygon layer with duplicate features an *assert* is hit and my debug build crashes.

```
Fatal: ASSERT: "QThread::currentThread() == qApp->thread()" in file ../src/analysis/vector/geometry_checker/qgsfeaturepool.cpp, line 111
```

**QGIS and OS versions**
02266ef8e6 on Debian bullseye

**Comment by roya0045** [comment]
From what I recall the assert are only hitable in non-releases. So at least the more used versions are not affected.
