### ISSUE TITLE
Editing/Snapping - QGIS hanging

### ISSUE THREAD

**Issue by 2DegreesWest** [qgis/QGIS#44252]
**Describe the bug**

I have a customer experiencing QGIS hanging when trying to edit using a WFS feed.  After testing we realised that if Snapping was turned on, then the software hung and had to be terminated.  However, if snapping was turned off then there are no issues.  However, they require to snap to the features within the service, therefore making this a requirement.  We found the solution on StackExchange where other users have experienced the same issue but using different feeds/services.  

**How to Reproduce**

1. They are using the OS Features API (Topo-Area) - feed added to map via the Browser window
2. User creates feature layer (tested as gpkg, and shp)
3. Toggle Editing on feature layer
4. QGIS then hangs when the Add Polygon Feature tool is selected and Snapping is enabled 

**QGIS and OS versions**

This was tested on multiple machines and the issue only occurred on a few.  All machines were Windows and various versions were tested from 3.12 to 3.18.  

**Additional context**

**Comment by gioman** [comment]
> and the issue only occurred on a few

@2DegreesWest try with new QGIS profiles, no 3rd party plugins installed.

**Comment by gioman** [comment]
> **How to Reproduce**
> 
>     1. They are using the OS Features API (Topo-Area) - feed added to map via the Browser window
> 
>     2. User creates feature layer (tested as gpkg, and shp)
> 
>     3. Toggle Editing on feature layer
> 
>     4. QGIS then hangs when the Add Polygon Feature tool is selected and Snapping is enabled

@2DegreesWest 

not sure I understand, are you editing layers via WFS-T or editing copies of WFS layers?

**Comment by 2DegreesWest** [comment]
Apologies, I wasn't clear with that - they are using the WFS as a 'base
layer' which they are digitising over the top and saving the edits in the
gpkg or shp they have created.  They also experienced similar issues with
hanging if they just tried to select the features they were interested in
and then tried to export them.

**Comment by gioman** [comment]
> Apologies, I wasn't clear with that - they are using the WFS as a 'base layer' which they are digitising over the top and saving the edits in the gpkg or shp they have created. They also experienced similar issues with hanging if they just tried to select the features they were interested in and then tried to export them.

@2DegreesWest make them try with a new QGIS profile.

**Comment by 2DegreesWest** [comment]
Good morning,
The customer removed all 3rd party apps and created a new profile - carried
out the same process but unfortunately with the same results.  After 30mins
of watching the spinning wheel, they went to close the program and got this
message:

[image: image.png]

The OS Features API is programmed that it should only call back 100
features in the area of interest.  Is QGIS trying to create an index on the
whole service instead before it can do anything else?
Thanks,
Richard

**Comment by gioman** [comment]
> The customer removed all 3rd party apps and created a new profile

@2DegreesWest no need to remove manually plugins, a new QGIS profile is always empty.



> [image: image.png]

you must send images using GH web interface, not by replying by email.


> Is QGIS trying to create an index on the whole service instead before it can do anything else?

hard to say. Can you attach all is needed (a sample project+data) to allow us replicate?
