### ISSUE TITLE
Atlas Output filename expression not updated

### ISSUE THREAD

**Issue by chleidersdorff** [qgis/QGIS#44261]
Working on QGIS 3.16.8 i have an expression that labels the map with the scale formatted in M, K or nothing suffix.

I use this in a label on the page and filenames but when exporting an atlas canvas that has multiple scales the filename expression is not updated and keeps the last page update.

I think this has something to do with the order of operations during the export.

expression used for filenames:
```
@layout_name ||'_'||replace( @atlas_pagename ,' ','')||'_'||
CASE 
WHEN map_get( item_variables('Map 1'), 'map_scale')>=1000000 THEN round( map_get( item_variables('Map 1'), 'map_scale')/1000000,4) || 'M'
WHEN map_get( item_variables('Map 1'), 'map_scale')>=1000 THEN round( map_get( item_variables('Map 1'), 'map_scale')/1000,4) || 'k'
ELSE round( map_get( item_variables('Map 1'), 'map_scale'),4)
END||'_A4P'
```
the expression updated in the label on the page but not the filenames.
![image](https://user-images.githubusercontent.com/52182284/126260057-becc8625-3c20-405f-9c07-5d3af1e05083.png)

![image](https://user-images.githubusercontent.com/52182284/126259950-f3b50bc9-9fdd-4a09-9118-c03d1eabbe3f.png)

Update 21-July-2021:
I have tested this in the latest version (Odense) and it works as expected, so it must be something in the LTR.

**Comment by roya0045** [comment]
Just a sidenote, instead of repeating the map get, look at using `with_variable` ;)

**Comment by chleidersdorff** [comment]
thanks @gioman that is definitely true, i created that expression a long time ago and it is in all my templates :) i will go back one day and update them. For anyone out there who were wondering how this would look, this is the re-formatted expression, it a little cleaner to look at:
```
with_variable('mymapscale',map_get( item_variables('Map 1'), 'map_scale'),
CASE 
WHEN @mymapscale>=1000000 THEN round( @mymapscale/1000000,4) || 'M'
WHEN @mymapscale>=1000 THEN round( @mymapscale/1000,4) || 'k'
ELSE round( @mymapscale,4)
END
)
```

**Comment by gioman** [comment]
> For anyone out there who were wondering how this would look, this is the re-formatted expression, it a little cleaner to look at:

@chleidersdorff so this can be closed?

**Comment by roya0045** [comment]
@gioman I was simply suggesting an improvement, I don't think reducing the complexity of the expression should change anything.

**Comment by chleidersdorff** [comment]
@gioman no the update was simply an improvement on the expression i used, it still does not fix the bug!

**Comment by chleidersdorff** [comment]
> > For anyone out there who were wondering how this would look, this is the re-formatted expression, it a little cleaner to look at:
> 
> @chleidersdorff so this can be closed?

I haven't had a chance to check if the bug has been fixed in the new version, if it has then I guess the picket could be closed.

**Comment by roya0045** [comment]
@chleidersdorff Do you know if it's still present?
