### ISSUE TITLE
Issue of the QGIS installation

### ISSUE THREAD

**Issue by yulan0215** [qgis/QGIS#44265]
Hi:
I would like to ask a question regarding the issue of QGIS installation in Ubuntu system.
I used the Ubuntu 20.04 and the version of python is: 3.8.10. I used the installation method in the weblink: https://qgis.org/en/site/forusers/alldownloads.html#debian-ubuntu
The problem is that the plugin "processing is missing". The details are shown below:
![image](https://user-images.githubusercontent.com/62309959/126279274-aeea0a25-f0c7-433f-bed6-27de66aa3c69.png)
I will appreciate if you can tell me how to solve this problem!

**Comment by gioman** [comment]
Check if you are using the right repos (i.e. if you are using Ubuntugis you must use the proper qgis.org's repo, same thing if you are not).

**Comment by yulan0215** [comment]
> Check if you are using the right repos (i.e. if you are using Ubuntugis you must use the proper qgis.org's repo, same thing if you are not).
Thx! I will check it!
