### ISSUE TITLE
QGIS crashed during pyramid build of georeference grayscale image

### ISSUE THREAD

**Issue by uvonwerder** [qgis/QGIS#44279]
## User Feedback

I started building pyramids on a single gray image and then moved to the internet browser to view historic aerial imageries. Then suddently QGIS crashed. I have to say that I kept QGIS running over night but had no worning when starting this morning. I have been working with QGIS for about 1 hour before the crash took place. I hope that helps you to find the bug! Thanks for your support!

## Report Details

**Crash ID**: [96dab6056de2ec69f979e489f0139887946528a4](https://github.com/qgis/QGIS/search?q=96dab6056de2ec69f979e489f0139887946528a4&type=Issues)

**Stack Trace**
<pre>
memcpy_repmovs memcpy.asm:114
VSICreateCachedFile :
GDALGeorefPamDataset::GetSpatialRef :
GDALGeorefPamDataset::GetSpatialRef :
GDALGeorefPamDataset::GetSpatialRef :
GDALRegister_GTiff :
GDALRegister_GTiff :
GDALRegister_GTiff :
GDALRasterBand::GetLockedBlockRef :
GDALRasterBand::IRasterIO :
GDALRegister_GTiff :
GDALRasterBand::RasterIO :
GDALRegenerateOverviews :
GDALRegenerateOverviewsMultiBand :
GDALRegenerateOverviews :
GTIFFBuildOverviews :
GTIFFBuildOverviews :
GDALDefaultOverviews::BuildOverviews :
GDALDataset::IBuildOverviews :
GDALRegister_GTiff :
GDALDataset::BuildOverviews :
QgsGdalProvider::buildPyramids qgsgdalprovider.cpp:2111
QgsRasterLayerProperties::buttonBuildPyramids_clicked qgsrasterlayerproperties.cpp:1456
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:475
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:475
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1638
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.18.2-Z�rich
QGIS code revision: 515138c171
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

**Comment by gioman** [comment]
>  QGIS Version: 3.18.2-Z�rich

@uvonwerder try with 3.20 and with a new QGIS profile. If the problem persist then describe the exact steps to replicate, adding sample data if needed.
