### ISSUE TITLE
QGIS Crash When Attempting to Use Points along geometry plugin on MultiLineString Layers

### ISSUE THREAD

**Issue by nalacour** [qgis/QGIS#44278]
I continue to have QGIS v. 3.16.8 crash when I attempt to use the Points along geometry plugin on any layers with a MultiLineString geometry. Works fine for LineString geometries. Crash report details below:

Crash ID: ce57b06b067cbc0a99b660dc0c69abd557319ad2

Stack Trace

QgsGeometryCollection::vertexAt qgsgeometrycollection.cpp:859
QgsGeometry::interpolateAngle qgsgeometry.cpp:2368
QgsPointsAlongGeometryAlgorithm::processFeature qgsalgorithmpointsalonggeometry.cpp:197
QgsProcessingFeatureBasedAlgorithm::processAlgorithm qgsprocessingalgorithm.cpp:1008
QgsProcessingAlgorithm::runPrepared qgsprocessingalgorithm.cpp:532
QgsProcessingAlgRunnerTask::run qgsprocessingalgrunnertask.cpp:66
sipQgsProcessingAlgRunnerTask::run sip_corepart4.cpp:9482
QgsTask::start qgstaskmanager.cpp:83
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.16.8-Hannover
QGIS code revision: 8c50902ea4
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

**Comment by gioman** [comment]
> Points along geometry plugin

@nalacour plugin or native processing tool?

**Comment by nalacour** [comment]
@gioman, native processing tool.

**Comment by gioman** [comment]
> @gioman, native processing tool.

@nalacour attach sample data and show the parameters used.
