### ISSUE TITLE
New Shapefile layer silently overwrite existing files

### ISSUE THREAD

**Issue by GeoJGH** [qgis/QGIS#44299]
QGIS version | 3.16.8-Hannover | QGIS code revision | 8c50902ea4
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)

When creating a new Shapefile ( menu `Layer / Create layer / new Shapefile Layer...`), one can either select or write a new layer name. When selecting it (using the `...` button), the `full path + name + .shp extension` is returned. If such file already exists, a warning is shown.

If the user just enters a name, without the `.shp` extension, (with or without a path), the set of Shapefile files are created. Any existing Shapefile will be overwritten without any warning.

Expected behavior: a warning should be shown that the layer will be overwritten

Step to reproduce:
1) 1st file: menu `Layer / Create layer / new Shapefile Layer...`, enter the name `test`, select a geometry type and click ok to create the shapefiles
2) overwrite: Remove current layer,  menu `Layer / Create layer / new Shapefile Layer...`, enter the same name `test`, select a geometry type and click ok to create the shapefiles --> files are overwritten, no warning is shown
3) warning with extension: Remove current layer,  menu `Layer / Create layer / new Shapefile Layer...`, enter the same name, with extension `test.shp`, select a geometry type and click ok to create the shapefiles -->A warning is shown informing that the layer already exists and will be overwritten

**Comment by uclaros** [comment]
Confirmed on Linux too. The *data corruption* flag is appropriate I think.

What's also not nice is that in the case that the warning *is* shown, if cancel is pressed the *New shapefile layer* dialog is closed losing all entered fields.
