### ISSUE TITLE
Selecting an SVG in the layout freezes the map for close to one minute

### ISSUE THREAD

**Issue by bkepl** [qgis/QGIS#44337]
Including a network location in "Path(s) to search for Scaleable Vector Graphic (SVG) symbols" under Settings -> Options causes QGIS to lock for nearly a minute when selecting any linked SVG in a layout.

**QGIS version**
**Version where problem _does not_ exist**

QGIS version | 3.16.8-Hannover | QGIS code revision | 8c50902e
-- | -- | -- | --
Compiled against Qt | 5.15.2 | Running against Qt | 5.15.2
Compiled against GDAL/OGR | 3.3.0 | Running against GDAL/OGR | 3.3.0
Compiled against GEOS | 3.9.1-CAPI-1.14.2 | Running against GEOS | 3.9.1-CAPI-1.14.2
Compiled against SQLite | 3.35.2 | Running against SQLite | 3.35.2
PostgreSQL Client Version | 13.0 | SpatiaLite Version | 5.0.1
QWT Version | 6.1.3 | QScintilla2 Version | 2.11.5
Compiled against PROJ | 8.0.1 | Running against PROJ | Rel. 8.0.1, March 5th, 2021
OS Version | Windows 10 Version 2009
Active python plugins | HCMGIS; latlontools; MemoryLayerSaver; mmqgis; pickLayer; PluginLoadTimes; qdraw; qNote; quick_map_services; Submission; db_manager; MetaSearch; processing

**versions installed where described problem _DOES_ exist**

QGIS version | 3.18.3-Zürich | QGIS code revision | 735cc85be9
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | HCMGIS; latlontools; MemoryLayerSaver; mmqgis; pickLayer; PluginLoadTimes; qdraw; qNote; quick_map_services; Submission; db_manager; MetaSearch; processing

QGIS version | 3.20.0-Odense | QGIS code revision | decaadbb31
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.0
PROJ version | 8.0.1
EPSG Registry database version | v10.018 (2021-04-02)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins | HCMGISlatlontoolsMemoryLayerSavermmqgispickLayerPluginLoadTimesqdrawqNotequick_map_servicesSubmissiondb_managerMetaSearchprocessing

**Comment by gioman** [comment]
> 3.18.3-Zürich

@bkepl 3.18 is unsupported, you must test on 3.20/master.

**Comment by nicogodet** [comment]
@gioman 3rd table is 3.20

I also notice this issue BTW
Qgis takes few seconds (10/20) to load all SVG in picture layout and after it's quite a PIA to navigate trough SVGs as it's slow.
Only happens on >3.18

**Comment by gioman** [comment]
> @gioman 3rd table is 3.20

sorry I overlooked that.

**Comment by bkepl** [comment]
I'm curious about this being marked as stale. Has it been determined by someone to be trivial? It sure isn't trivial when I'm working on a layout.

**Comment by bkepl** [comment]
This is still an issue with version 3.20.2.

**Comment by bkepl** [comment]
This is still an issue with version 3.23. I find I'm forced to open projects in 3.16 if I have to make anything more than the most minor changes to a layout, particularly if I'm under a deadline. This is too bad, since the ability to add layer notes in version >= 3.20 is truly wonderful.

**Comment by bkepl** [comment]
This is still an issue with 3.22. Since there are reasons I want to use this latest version, I tried a few things. It seems the problem is including a path on a drive mapped to a network location. The easiest way to resolve this is remove this path from the search paths for symbols, and when I want to add a symbol such as a custom North arrow, I just browse to it. That doesn't slow anything down.

This is not an issue with having that network drive included a source for layout templates.

**Comment by gioman** [comment]
> It seems the problem is including a path on a drive mapped to a network location.

@bkepl can you edit the title to better reflect your findings? thanks.

**Comment by bkepl** [comment]
@gioman, that is correct. (Just so it doesn't get lost, I want to reiterate that 3.16 and before don't have this problem.)

**Comment by bkepl** [comment]
This seems to be no longer an issue.
