### ISSUE TITLE
Continuous crash

### ISSUE THREAD

**Issue by gianlugeol** [qgis/QGIS#44339]
Crash ID: f572ed28c66aa60dcdb17792eb9dd243350e762e

Stack Trace

QgsGeometry::closestVertex :
QgsPointLocator::verticesInRect :
SpatialIndex::TPRTree::Data::Data :
SpatialIndex::TPRTree::Data::Data :
QgsPointLocator::nearestVertex :
QgsSnappingUtils::~QgsSnappingUtils :
QgsSnappingUtils::snapToMap :
QgsSnappingUtils::snapToMap :
PyInit__core :
PyArg_ParseTuple_SizeT :
PyEval_EvalFrameDefault :
PyFloat_FromDouble :
PyEval_EvalFrameDefault :
PyFunction_Vectorcall :
PyFloat_FromDouble :
PyVectorcall_Call :
PyObject_Call :
QgsPresetSchemeColorRamp::clone :
QgsMapCanvas::mouseMoveEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.20.0-Odense
QGIS code revision: decaadbb31
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.0
Running against GDAL: 3.3.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041
Hello everybody
I've continuous program crash while I'm working with polygon layer and this is the report
Gian

**Comment by gioman** [comment]
@gianlugeol Please add detailed steps to replicate. Also test on a new QGIS profile, no 3rd party plugins installed.

**Comment by gianlugeol** [comment]
I'm working with a ready-made polygon layer. I'm just doing polygon cutting and joining and data attribution with the attributepainter plugin. It frequently happens that after some of these cutting operations and after a change of view, once I activate the split elements tool, the program collapses, giving me the error I posted above

**Comment by gioman** [comment]
> I'm working with a ready-made polygon layer. I'm just doing polygon cutting and joining and data attribution with the attributepainter plugin. It frequently happens that after some of these cutting operations and after a change of view, once I activate the split elements tool, the program collapses, giving me the error I posted above

@gianlugeol try with a new QGIS profile, no 3rd party plugins installed. If the problem persist attach a sample project + data and list the detailed steps that lead to the crash.
