### ISSUE TITLE
Coding problems when running algorithms

### ISSUE THREAD

**Issue by viniciuspg** [qgis/QGIS#44340]
**Describe the bug**
Dear Ones,
In Brazil we use UTF-8 encoding. In the list of Qgis 3.16.8-Hannover compiled 5.15.2 (QGIS version code 8c50902) there is UTF-8 appears twice.But the biggest problem is that when running any algorithm that saves a new shp layer, the UTF-8 encoding is preserved, but the new layer opens with Windows-1252 encoding. If we change the encoding to UTF-8, the data is correct in the attribute table. Otherwise, the characters appear with problems. This forces you to correct the encoding manually each time a layer resulting from processing is opened. This becomes very problematic for building models with the modeler. We have tried to correct the encoding at the end with an algorithm to "set the encoding", but it has no output, so it is not possible to start a process in UTF-8 and end it in the same encoding.

If you have any questions, please feel free to contact me.

Thank you very much.

**How to Reproduce**

1. Open a shp saved in UTF-8 encoding that contains special characters such as ô ã like the names of Brazilian cities: "São Paulo, Florianópolis, São Gonçalo";
2. Use the "correct geometry" algorithm from the process box;
3. Check the encoding of the resulting layer will be windows-1252 instead of UTF-8). Also, the attribute table will be misconfigured;
4. Adjust the encoding of the layer by right-clicking on the vector layer, information, change to UTF-8 encoding (note that it appears twice in the list, but either one works); 
5. Check the attribute table again. It will be correct, but for the layer to actually be in UTF-8 encoding you need to right click on the vector layer and "export layer in UTF-8 encoding;
6. Open the exported layer, which will now open in UTF-8 and the table will be correct. But there is no way to run this process in batch, at least I didn't find it.

**QGIS and OS versions**

Versão do QGIS
3.16.8-Hannover
Código da versão do QGIS
8c50902e
Compilado sobre Qt
5.15.2
Rodando sobre Qt
5.15.2
Compilado sobre GDAL/OGR
3.3.0
Rodando sobre GDAL/OGR
3.3.0
Compilado sobre GEOS
3.9.1-CAPI-1.14.2
Rodando sobre GEOS
3.9.1-CAPI-1.14.2
Compilado no SQLite
3.35.2
Executando contra SQLite
3.35.2
Versão do cliente PostgreSQL
13.0
Versão SpatiaLite
5.0.1
Versão do QWT
6.1.3
Versão QScintilla2
2.11.5
Compilado com PROJ
8.0.1
Em execução com PROJ
Rel. 8.0.1, March 5th, 2021
Versão SO
Windows 10 Version 2009
Ativar complementos python
dzetsaka; 
FreehandRasterGeoreferencer; 
ImportPhotos; 
latlontools; 
mmqgis; 
quick_map_services; 
shapetools; 
MetaSearch; 
processing

Windows 10 Home Single Language
20H2
12/‎03/‎2021
19042.1110
Windows Feature Experience Pack 120.2212.3530.0

**Additional context**

**Comment by agiudiceandrea** [comment]
@viniciuspg if I undertand correctly your issue, you need to change the file encoding of the output layer in processing algorithm window:
![image](https://user-images.githubusercontent.com/16253859/126751738-b4ad6747-c3c8-4bd9-a915-b90c2303899d.png)

**Comment by uclaros** [comment]
>     3\. Check the encoding of the resulting layer will be windows-1252 instead of UTF-8). Also, the attribute table will be misconfigured;

Can you check the content of this shapefile's `.cpg` file with a text editor? Does it say `1252` or `UTF-8`?
