### ISSUE TITLE
Large JPG raster display slow since QGIS 3.16.5

### ISSUE THREAD

**Issue by crclwcca** [qgis/QGIS#44358]
**Describe the bug**

**How to Reproduce**

4. See error -->

**QGIS and OS versions**

**Additional context**

**Comment by crclwcca** [comment]
Since I installed QGIS 3.16.5 I've noticed very slow large raster display performance. I upgrade every year or so since 2015 and this is the first time I've noticed the problem. It takes much longer to display data and the interface is unresponsive long after the image has been rendered.

**Comment by gioman** [comment]
> QGIS 3.16.5

@crclwcca so you started see a difference after 3.16.4?

Have you tried a new QGIS profile?
On what OS you work?
What format is your raster? and size?
Do you have overviews?
Can you link/attach a sample?

**Comment by crclwcca** [comment]
QGIS 3.16.5 and 3.16.9

<<Answers to QGIS questions below>>
@crclwcca so you started see a difference after 3.16.4?

<<Yes - And the problem I'm having is that when I take any action involving a large JPG image (aerial photography) the image display takes longer than it did with previous versions and the whole application interface freezes up for several seconds after the image finally displays - during that time I can't push any menu buttons, draw windows for zooming on the map canvas, or select anything from the layers dialog. Sometimes (Not responding) flashes in the window title>>

Have you tried a new QGIS profile?

<<Not yet>>

On what OS you work?

<< Windows 10x64 Computer has 16GB RAM with an SSD system drive and HD data drive - both healthy

What format is your raster? and size?

<<It's a JPG 26665 x 15647  When I display a GeoTIFF file of similar dimensions I DO NOT have a problem>>

Do you have overviews?

<<My system has enough power that I don't normally need overviews. For testing this issue I created a full set and it displayed a bit faster but the interface still froze after the image displayed>>


Can you link/attach a sample?

<<No - Sorry>>

**Comment by gioman** [comment]
> Can you link/attach a sample?
> 
> <<No - Sorry>>

@crclwcca it would really be important if you can find the time to suggest/link us a freely available dataset that show the behavior you describe.

**Comment by crclwcca** [comment]
OK The attached contains 2 test images both 26679 x 18676 one in JPG format and the other in TIF. Both CRS NAD83/UTM10N.
The JPG image is causing the entire QGIS interface to slow down and become balky and erratic. For example with the JPG image the coordinate readout stops updating as you move the cursor. On my system adding the JPG file to the map slows things down somewhat. Adding it again as a new layer really slows things down. There is no problem with the TIF image. I tried reinstalling from 3.16.5 to 3.16.9 and the problem was reduced by half - but is still evident. With JPG images the problem is definitely related to image size in lines and pixels. If I resize the image to half the lines/pixels it speeds up, but is still not as fast as TIF.
Normally I don't really need to use overviews - but I tried them and they didn't do much good - the interface still acts up.
[qgis 3.16 display issue test images.zip](https://github.com/qgis/QGIS/files/6951701/qgis.3.16.display.issue.test.images.zip)

Is there a problem with the JPEG JFIF driver since 3.16.4 (which was OK). Or is it related to my system? 
Thanks

**Comment by gioman** [comment]
Tested on Linux and Windows on 3.20.1 and 3.16.9, works fine here:


https://user-images.githubusercontent.com/1951107/128672299-18f42314-92fb-4163-9730-4abe6d50b799.mp4

**Comment by crclwcca** [comment]
Thanks for checking it out. Looks fine on your end. Can you think of any reason why I would see the problem with a JPG file, but not with a TIF that has identical geometry and spectral content? In any case I can still work with large JPGs, but I have to wait a few seconds for the interface. Is there some parameter in my profile that is causing this?

**Comment by gioman** [comment]
>  Is there some parameter in my profile that is causing this?

@crclwcca have you tried a new QGIS profile?

**Comment by crclwcca** [comment]
Yes - I created a new one and now it's faster than ever.  Now I need to re-install plugins etc to get my customization back. Can you point me to the best way to do that?
Thanks

**Comment by gioman** [comment]
> Now I need to re-install plugins etc to get my customization back. Can you point me to the best way to do that?

@crclwcca you may want to do the other way around, use you original profile and disable one by one 3rd plugins until you find the culprit (given that the issue is caused by a 3rd party plugin).

**Comment by crclwcca** [comment]
OK - I'll try that

**Comment by crclwcca** [comment]
The culprit was the Value Tool plugin - found by deactivating all of them then activating them one by one cumulatively. Took about an hour but worth it.
