### ISSUE TITLE
Hi, I'm using Mac OS Big Sur, Ver 11.4.  Just tried to install QGIS LTR.  The system returns an error message:  "QGIS-LTR" can't be opened because Apple cannot check it for malicious software.  This software needs to be updated. Contact the developer for more information.    

### ISSUE THREAD

**Issue by Alfred16007** [qgis/QGIS#44357]
**Describe the bug**

**How to Reproduce**

4. See error -->

**QGIS and OS versions**

**Additional context**

**Comment by jef-n** [comment]
"QGIS is not yet notarized as required by macOS Catalina (10.15) security rules. On first launch, please right-click on the QGIS app icon, hold down the Option key, then choose Open."
