### ISSUE TITLE
Tables with self-relationships in PostGIS cause QGIS to crash

### ISSUE THREAD

**Issue by tjukanovt** [qgis/QGIS#44353]
If a PostGIS table contains a table with self-relationships, that seems to be crashing QGIS. Self-realtionships can be mapped e.g. with pgModeler: https://pgmodeler.io/support/docs/310-relationships?v=0.9.2

If/when QGIS is not able to handle these relations, there could be some kind of an error message or warning instead of a crash. 

**How to Reproduce**

- Create a new PostGIS database as follows:
```SQL
DROP DATABASE IF EXISTS selfdebug;
CREATE DATABASE selfdebug;

CREATE EXTENSION postgis
WITH SCHEMA public;

CREATE TABLE public.testobject (
	id smallint NOT NULL GENERATED ALWAYS AS IDENTITY ,
	geom geometry(MULTIPOLYGON, 3857),
	id_testobject smallint,
	CONSTRAINT testobject_pk PRIMARY KEY (id)

);

ALTER TABLE public.testobject ADD CONSTRAINT testobject_fk FOREIGN KEY (id_testobject)
REFERENCES public.testobject (id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
```
- Connect to database and add your layer to QGIS
- Discover relations (Project --> Properties --> Discover relations
- Start editing an object
- See things crash

**QGIS and OS versions**

QGIS version 3.18.2-Zürich running in Windows 10

PostGIS verison 13 running in Docker

**Comment by gioman** [comment]
> * Connect to database and add your layer to QGIS
> 
> * Discover relations (Project --> Properties --> Discover relations
> 
> * Start editing an object
> 
> * See things crash

@tjukanovt no crash on QGIS master on Ubuntu 20.04.

**Comment by tjukanovt** [comment]
Updated to 3.20.1 and indeed the crash is gone.
