### ISSUE TITLE
Profiles from Lines SAGA missing tail

### ISSUE THREAD

**Issue by coefficient1900** [qgis/QGIS#44360]
**Describe the bug**
When using the SAGA tool "Profiles from Lines" it is not guaranteed that the last point of the profil lies at the end of the examined line (but it is possible that these coincide). If that is the case, the reported lengths are obviously wrong. Because it is a SAGA issue, this could be the starting point to create a QGIS inherent tool for obtaining the surface length by a DEM.

**How to Reproduce**
1. Create a new line shape layer (I used CRS: 25832 ETRS89/UTM32N) where you have a DEM available.

2. Use the SAGA tool "Profils from Lines" to obtain the surface length along that line.

3. Check whether the last point of the profil is exactly at the end of the line.
![DEM_Profile_SAGA](https://user-images.githubusercontent.com/86417466/126861962-69ef7931-9cdd-4d26-9a62-055301fd09b8.PNG)

![DEM_Profile_SAGA_end1](https://user-images.githubusercontent.com/86417466/126862083-71ae7b61-ec9b-4729-aeb1-e9137e3be36b.PNG)

![DEM_Profile_SAGA_end2](https://user-images.githubusercontent.com/86417466/126862088-2e121a86-83cd-4aa4-b1b3-54b8b411fe42.PNG)

**QGIS and OS versions**

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.20.1-Odense | QGIS code revision | 1c3c5cd6
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.1
PROJ version | 8.1.0
EPSG Registry database version | v10.018 (2021-04-02)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins | db_managerMetaSearchprocessing

</body></html>

**Additional context**
I am using a windows machine with a new profile.

This behaviour occurred in the version 3.16.8, 3.18.3 and 3.20.1.

The archive contains a dem and the origin line which was used to go through the steps described above.
[demand2dline.zip](https://github.com/qgis/QGIS/files/6872082/demand2dline.zip)

**Comment by gioman** [comment]
> Because it is a SAGA issue,

@coefficient1900 it is a SAGA issue, you get the same results if you run the tool from the CLI.


Note to myself: this tool must be split in two as the parameters "PROFILE" and "PROFILES" cannot coexist, as the second only work if "SPLIT" is true and the first only when "SPLIT" is false.

**Comment by coefficient1900** [comment]
@gioman thanks for the confirmation!

Does somebody has connections to the SAGA community to forward this issue?
