### ISSUE TITLE
Graphical Modeler: Underscore in input names are ignored

### ISSUE THREAD

**Issue by reueld** [qgis/QGIS#44378]
**Describe the bug**

Any underscore "_" in an input name is ignored in processing.

**How to Reproduce**

1. Create an input called "Input_A"
2. Try using this input in any expression using @Input_A . This does not work
3. Try using this input in any expression with @InputA . This works

Similarly, there cannot be two inputs with similar names differentiated with an underscore. Not sure if this is by design or a bug. Eg:
1. Create an input called "InputA"
2. Create an input called "Input_A". Does not show in model.

**QGIS and OS versions**

QGIS version
3.16.9-Hannover
QGIS code revision
9f8d2f79
Compiled against Qt
5.15.2
Running against Qt
5.15.2
Compiled against GDAL/OGR
3.3.1
Running against GDAL/OGR
3.3.1
Compiled against GEOS
3.9.1-CAPI-1.14.2
Running against GEOS
3.9.1-CAPI-1.14.2
Compiled against SQLite
3.35.2
Running against SQLite
3.35.2
PostgreSQL Client Version
13.0
SpatiaLite Version
5.0.1
QWT Version
6.1.3
QScintilla2 Version
2.11.5
Compiled against PROJ
8.1.0
Running against PROJ
Rel. 8.1.0, July 1st, 2021
OS Version
Windows 10 Version 2009
Active python plugins
attributeBasedClustering; 
NNJoin; 
QuickOSM; 
quick_map_services; 
wpgpDatasets; 
db_manager; 
MetaSearch; 
processing

**Additional context**

**Comment by Koyaani** [comment]
@reueld The problem of '_' is fixed. We can add a parameter "inputA" and "input_A". However, this information is not the names of the parameters but their description. In the expressions, it is the names of the parameters that are used.

With this model parameters :
![](https://user-images.githubusercontent.com/37629967/135074681-55faec66-6373-4863-b6c0-9ad036a1d215.png)

You can see the list of parameter names here :
![](https://user-images.githubusercontent.com/37629967/135074771-8cee8eca-f36d-459c-97ac-d1264a18a988.png)
