### ISSUE TITLE
add option to filter for binary vector fields when using QgsProcessingParameterField

### ISSUE THREAD

**Issue by janzandr** [qgis/QGIS#44372]
**Feature description.**

Currently you can filter for fields of type Numeric, String and DateTime.

Would be nice to have a new option for filtering for binary fields, e.g. **QgsProcessingParameterField.Binary**

![image](https://user-images.githubusercontent.com/45030715/126948700-d54cc5e7-f1de-4856-9544-c401b2faad7f.png)

**Comment by alexbruy** [comment]
Implemented in #54665

**Comment by janzandr** [comment]
Thanks a lot.
