### ISSUE TITLE
Rule Based Symbology not working if filter is based on column with "-" in its name

### ISSUE THREAD

**Issue by MakkieSA** [qgis/QGIS#44379]
Certain Vector Layers not displaying on Map with Rule Based Symbology (Version 3.16.9 & 3.20.1) Work on older versions

**Comment by gioman** [comment]
@MakkieSA please attach sample data and detail the necessary steps to replicate.

**Comment by MakkieSA** [comment]
Please see attached polygon shapefile and QGIS style file attached in Zip file.

If I load the shapefile in QGIS 3.16.3 and
load the style file on the shapefile it works as expected.

If I do exactly the same in QGIS 3.16.9 and QGIS 3.20.1, the shape disappear/doesn't display on my map.

Hope this helps.


[QGIS Error.zip](https://github.com/qgis/QGIS/files/6892141/QGIS.Error.zip)

**Comment by gioman** [comment]
Seems to be caused by the "-" in the column name used for creating the rules. If you use an equivalent column without "-" it works.

**Comment by MakkieSA** [comment]
Thanks GiovanniI will check.Regards
-------- Original message --------From: Giovanni Manghi ***@***.***> Date: 2021/07/28  12:48  (GMT+02:00) To: qgis/QGIS ***@***.***> Cc: MakkieSA ***@***.***>, Mention ***@***.***> Subject: Re: [qgis/QGIS] Rule Based Symbology not working if filter is based on column with "-" in its name (#44379) 
Seems to be caused by the "-" in the column name used for creating the rules. If you use an equivalent column without "-" it works.

**Comment by nicogodet** [comment]
@gioman It seems similar to https://github.com/qgis/QGIS/issues/43616 as if the attribute name contains "-" some qgis features fail ?

**Comment by gioman** [comment]
> @gioman It seems similar to #43616 as if the attribute name contains "-" some qgis features fail ?

seems related.

**Comment by MakkieSA** [comment]
Hello GiovanniYes, can confirm, once "-" removed from field name all sorted.Thanks & regards
-------- Original message --------From: Giovanni Manghi ***@***.***> Date: 2021/07/28  15:15  (GMT+02:00) To: qgis/QGIS ***@***.***> Cc: MakkieSA ***@***.***>, Mention ***@***.***> Subject: Re: [qgis/QGIS] Rule Based Symbology not working if filter is based on column with "-" in its name (#44379) 

@gioman It seems similar to #43616 as if the attribute name contains "-" some qgis features fail ?

seems related.

**Comment by gioman** [comment]
This do not seems completely fixed, see https://github.com/qgis/QGIS/issues/46459

**Comment by roya0045** [comment]
> This do not seems completely fixed, see #46459

I'm pretty sure it's fixed, I think it's just the conversion that is broken, not quite the same sadly.
