### ISSUE TITLE
No version change when downloading and installing 3.20.1. Version number not bumped?

### ISSUE THREAD

**Issue by garvamel** [qgis/QGIS#44381]
The issue is for macOS.

 I had 3.20.0 and downloaded 3.20.1 when the notice came up. 

After installing and reopening, the notice of a new version still comes up and the newly installed download still shows up as 3.20.0.

I don't know if the issue is only the version number, or the installer package was not changed to 3.20.1 in the server for download.

This is the about window:

![image](https://user-images.githubusercontent.com/17742377/127064478-c3436fb1-4f49-405b-907c-64411440d396.png)
 
Thanks

**Comment by agiudiceandrea** [comment]
Unfortunately, the latest available versions for macOS are 3.16.8 and 3.20.0.

Anyway, the user is not informed about the actual version available for download for macOS:
![image](https://user-images.githubusercontent.com/16253859/127110133-4fb7515f-0780-4e91-b983-031b3318c9d8.png)

**Comment by garvamel** [comment]
I keep getting this, though:

![image](https://user-images.githubusercontent.com/17742377/127191494-8372f268-0c81-4867-b713-cf85b0818693.png)

**Comment by garvamel** [comment]
Ahh, ok. The notice is for all QGIS, independent of whether it was packed for my platform or not.

Thanks!

**Comment by gioman** [comment]
> Ahh, ok. The notice is for all QGIS, independent of whether it was packed for my platform or not.

correct.

**Comment by PeterPetrik** [comment]
The macOS packages are ready for use:

Point Release (PR) 3.20.1
https://qgis.org/downloads/macos/pr/qgis_pr_final-3_20_1_20210805_162007.dmg

Long Term Release (LTR) 3.16.9
https://qgis.org/downloads/macos/ltr/qgis_ltr_final-3_16_9_20210806_022813.dmg

and Nightly 3.21.0
https://qgis.org/downloads/macos/nightly/qgis_nightly_master_20210805_123338.dmg
