### ISSUE TITLE
Download link for Mac OS installer for 3.16.9 is incorrect

### ISSUE THREAD

**Issue by ormanci** [qgis/QGIS#44408]
### What is the bug or the crash?

The download page for Mac OS installer says the QGIS LTR version is supposed to be 3.16.9, but the actual link points to 3.16.8. Please update the Mac OS installer link so MAC users can get the most current and correct QGIS LTR. Thanks!

### Steps to reproduce the issue

Go to https://qgis.org/en/site/index.html, click Download Now button, and click the QGIS macOS Installer 3.16 and the resulting dmg package actually contains QGIS 3.16.8 instead of 3.16.9. 

### Versions

QGIS version | 3.16.8-Hannover | QGIS code revision | 8c50902ea4
-- | -- | -- | --
Compiled against Qt | 5.14.2 | Running against Qt | 5.14.2
Compiled against GDAL/OGR | 3.2.1 | Running against GDAL/OGR | 3.2.1
Compiled against GEOS | 3.9.1-CAPI-1.14.2 | Running against GEOS | 3.9.1-CAPI-1.14.2
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.4
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | macOS 11.2
Active python plugins | GeometryShapes; QuickOSM; quick_map_services; Multi_Ring_Buffer; openlayers_plugin; processing; db_manager; MetaSearch

**Comment by agiudiceandrea** [comment]
See https://github.com/qgis/QGIS-Website/issues/925 and https://github.com/qgis/QGIS/issues/44381

**Comment by gioman** [comment]
Closing as duplicate.

**Comment by PeterPetrik** [comment]
The macOS packages are ready for use:

Point Release (PR) 3.20.1
https://qgis.org/downloads/macos/pr/qgis_pr_final-3_20_1_20210805_162007.dmg

Long Term Release (LTR) 3.16.9
https://qgis.org/downloads/macos/ltr/qgis_ltr_final-3_16_9_20210806_022813.dmg

and Nightly 3.21.0
https://qgis.org/downloads/macos/nightly/qgis_nightly_master_20210805_123338.dmg
