### ISSUE TITLE
Downloading stopped at 75% and would go no further

### ISSUE THREAD

**Issue by Keevilboy** [qgis/QGIS#44404]
IMPORTANT:

Do NOT use GitHub to post any questions or support requests!
They will be closed immediately and ignored.
Questions should go to the qgis-user mailing list at https://lists.osgeo.org/mailman/listinfo/qgis-user
or other support forums such as https://gis.stackexchange.com/.

GitHub issues are for bug reports and suggestions for new features.

**Comment by gioman** [comment]
Not an issue with QGIS code. This tracker is for issues about QGIS the program.
