### ISSUE TITLE
Strange shifted Image obtain with Clip raster by mask layer

### ISSUE THREAD

**Issue by frchalaoux** [qgis/QGIS#44402]
[Report_FRC_log.txt](https://github.com/qgis/QGIS/files/6884902/Report_FRC_log.txt)

**Describe the bug**
When you "clip raster by mask layer" the resulting image result is shifted. The raster and vector objects are in the same EPSG
and whatever option on resolution from input or output parameter nothing is changing this strange shift

**How to Reproduce**

1. Import the raster and vector polygone files
2. Use Clip Raster by mask layer process
3. Select the two files (attachement)
4. Choose to keep the resolution of input file
4. Observe the shift between the original raster and the clipped image

**QGIS and OS versions**

QGIS 3.20 on MacOS Mojave
[Report_FRC.zip](https://github.com/qgis/QGIS/files/6884842/Report_FRC.zip)

**Comment by gioman** [comment]
@frchalaoux it is a GDAL based tool. Do you get the same result by running the operation from the command line?

**Comment by nicogodet** [comment]
@frchalaoux Use an adapted projection (EPSG:2154 for your case) and no issue.
Reproject both your layer in 2154 and clip.
![image](https://user-images.githubusercontent.com/39594821/127150820-10429178-91dd-430d-8baa-a6869ab9c79b.png)

Using 4326, clipped image was different than yours but still shifted a bit.

**Comment by frchalaoux** [comment]
Yes, I obtain the same issue with a new profil and on the CLI. The form of the pixel reflects the projection but the pixels should be all the same be superimposed !?

**Comment by gioman** [comment]
> Yes, I obtain the same issue with a new profil and on the CLI.

@frchalaoux then is not a QGIS issue.

**Comment by frchalaoux** [comment]
I did the reprojections in 2154 and I clipped again. I obtain the same type of problem with QGIS and CLI-GDAL but the CLI-GDAL and QGIS images are slighly differents
[Report_FRC_2154.zip](https://github.com/qgis/QGIS/files/6886981/Report_FRC_2154.zip)
 (see attachement).  And you, did you get problems with CLI-GDAL ?

**Comment by gioman** [comment]
> and CLI-GDAL but the CLI-GDAL

@frchalaoux is the command created/issued by QGIS and the one you typed in the CLI indentical?

**Comment by nicogodet** [comment]
I had no issue using reprojected layers (see my previous comment).

**Comment by frchalaoux** [comment]
> > and CLI-GDAL but the CLI-GDAL
> 
> @frchalaoux are the commands created/issued by QGIS and the one you typed in the CLI indentical?

Yes, I copied the same command line from QGIS interface to my shell

**Comment by frchalaoux** [comment]
I would like to correct :

Yes in the total 4326 (layer and project), I obtain the same issue and I check it with a new profil and on the CLI/GQIS. The form of the pixel reflects the projection but the pixels are shifted all the same but seem superimposed. I mean not shifted one in relation to the other but shifted compared to the image before the clip (see attached image).

[GDAL_OUTPUT_4326.tif.zip](https://github.com/qgis/QGIS/files/6887177/GDAL_OUTPUT_4326.tif.zip)

What could be the next step for my problem ?

**Comment by frchalaoux** [comment]
I'm not agree to close the issue without choose what to do next, not you ?

**Comment by gioman** [comment]
> I'm not agree to close the issue without choose what to do next, not you ?

@frchalaoux this is the command generated by QGIS (example)

`gdalwarp -overwrite -s_srs EPSG:2154 -t_srs EPSG:2154 -of GTiff -cutline /home/giovanni/Downloads/Report_FRC_2154/Report_FRC_2154/Florentin_parcelles_C_2154.gpkg -cl Florentin_parcelles_C_2154 -crop_to_cutline /home/giovanni/Downloads/Report_FRC_2154/Report_FRC_2154/NDVI_Full_09062021_2154.gpkg /tmp/processing_NqlIPY/011dc3fcc57a4d0399539ebd93011703/OUTPUT.tif`

and running the same from the CLI creates an identical result.

[Report_FRC_2154.zip](https://github.com/qgis/QGIS/files/6891694/Report_FRC_2154.zip)

**Comment by frchalaoux** [comment]
> > I'm not agree to close the issue without choose what to do next, not you ?
> 
> @frchalaoux this is the command generated by QGIS (example)
> 
> `gdalwarp -overwrite -s_srs EPSG:2154 -t_srs EPSG:2154 -of GTiff -cutline /home/giovanni/Downloads/Report_FRC_2154/Report_FRC_2154/Florentin_parcelles_C_2154.gpkg -cl Florentin_parcelles_C_2154 -crop_to_cutline /home/giovanni/Downloads/Report_FRC_2154/Report_FRC_2154/NDVI_Full_09062021_2154.gpkg /tmp/processing_NqlIPY/011dc3fcc57a4d0399539ebd93011703/OUTPUT.tif`
> 
> and running the same from the CLI creates an identical result.
> 
> [Report_FRC_2154.zip](https://github.com/qgis/QGIS/files/6891694/Report_FRC_2154.zip)

1/ I used your command line to create a tiff (NDVI_Full_09062021_2154 + CLI_2154_FRC_GIOMAN on the figure) is shift in QGIS compared to the original.

2/ There is a big shift between your cli file (NDVI_Full_09062021_2154 + CLI_2154_GIOMAN) and mine with the same command line displayed it in QGIS over the (NDVI_Full_09062021_2154).

I also checked if the difference did no come from the application display. The result is the same with "Monteverdi" from OTB distribution.

My opinion is firstly gdalwarp from Anaconda/MacOS seems not identical to yours and secondly your image (ggis.tiff) on my QGIS Mac is shifted with my origin file. Your 2 files are not shifted together in my QGIS or  "Monteverdi" but have with the same shift with the original image 
[FRC_GIOMAN.pdf](https://github.com/qgis/QGIS/files/6892352/FRC_GIOMAN.pdf)
!

What do you think about that ?

**Comment by gioman** [comment]
> What do you think about that ?

@frchalaoux maybe is a macOS issue, please try on a different platform.

**Comment by frchalaoux** [comment]
> > What do you think about that ?
> 
> @frchalaoux maybe is a macOS issue, please try on a different platform.

Exactly the same result with QGIS 3.18.1 on Windows with Parallels Desktop on my MacBook Pro !

@gioman What is your platform ?

**Comment by gioman** [comment]
> @gioman What is your platform ?

@frchalaoux ubuntu 20.04

**Comment by frchalaoux** [comment]
> > @gioman What is your platform ?
> 
> @frchalaoux ubuntu 20.04

In some minutes I'll test a virtual machine 18.04.1-Ubuntu on my Mac and a friend will do it on real Windows machine

**Comment by nicogodet** [comment]
Was OK on Win10 OsGeo4W v2
Qgis 3.20.1

**Comment by frchalaoux** [comment]
Hi @all,

 Not OK for on Linux Ubuntu 20.04 and QGIS 3.20.1 with my Parallels virtual machine on my MacBook Pro (see attachements). There is the same shift between cli or QGIS image with the original. And on all the images you send me there a little shift on all my QGIS platforms
<img width="967" alt="QGIS_CLI_Linux_Clipped_2154" src="https://user-images.githubusercontent.com/911908/127456570-6501c136-f6e0-4acf-8286-ecc6644b77e0.png">

Can you recognize there is also a problem on your platforms and we should investigate ?

**Comment by gioman** [comment]
> And on all the images you send me there a little shift on all my QGIS platforms
> Can you recognize there is also a problem on your platforms and we should investigate ?

@frchalaoux 

if you refers  to https://github.com/qgis/QGIS/files/6891694/Report_FRC_2154.zip then no, I can't see any shift, not even a very small one.

![image](https://user-images.githubusercontent.com/1951107/127472428-8b70c19e-7835-4d7b-bcfc-4d546711b589.png)

**Comment by frchalaoux** [comment]
> if you refers to https://github.com/qgis/QGIS/files/6891694/Report_FRC_2154.zip then no, I can't see any shift, not even a very small one.

OK, there is no shift between cli and gis generated image (1-0) but there a shift on my QGIS platforms between the original image and your produced image with QGIS and GADAL (attachement, ) I think it's similar for you, no ?
<img width="1207" alt="qgis-cli-gioman_QGIS-macos_FRC" src="https://user-images.githubusercontent.com/911908/127485005-26f570eb-721b-44cb-b027-6f17ac03008b.png">

**Comment by gioman** [comment]
> but there a shift on my QGIS platforms between the original image and your produced image with QGIS and GADAL

@frchalaoux you are clipping a raster with a polygon who's boundaries do no match the pixels/boundaries of your input raster, so it is expected that output pixels won't match the ones of the input...

**Comment by frchalaoux** [comment]
> > but there a shift on my QGIS platforms between the original image and your produced image with QGIS and GADAL
> 
> @frchalaoux you are clipping a raster with a polygon who's boundaries do no match the pixels/boundaries of your input raster, so it is expected that output pixels won't match the ones of the input...

Ok, I can admit. So for, you is here an other solution to clip properly ?

**Comment by gioman** [comment]
@frchalaoux I would resample the input to a higher resolution or use the "align raster" tool on the output.

**Comment by frchalaoux** [comment]
@gioman Thanks a lot !

**Comment by frchalaoux** [comment]
In the mid time I resolved my problem outside GQIS with some lines of Python. The project is attached to this message.

Cheers, François-Régis
[Florentin.zip](https://github.com/qgis/QGIS/files/6910960/Florentin.zip)
