### ISSUE TITLE
I've gone through few bugs while working with QGIS3.18.3 recently.

### ISSUE THREAD

**Issue by JacobyoonDH** [qgis/QGIS#44400]
1.	Table error (urgent problem for us)
-	While working with QGIS3.18.3, the information in the attribute table is inconsistent with the actual object information on the map (they don't match!)
-	Only way we found to deal with this problem was just restart the attribute table
 
2.	Vertex snaps error
-	Rarely vertex snaps ruin the shape of the object automatically.
 (Sometimes it makes the shape of object invisible)
-	This problem won’t stop until we restart the entire program

https://user-images.githubusercontent.com/88027325/127125276-260a4363-9a08-41f2-b47f-337986bc0d96.mp4

3.	Error that occur while selecting object

-  Once an object is selected, it is not displayed in the attribute table.
-  Just like other solutions Turning off the attribute table and re-enabling it is the only way to bring the attribute table to normal.

https://user-images.githubusercontent.com/88027325/127125578-719dfeca-0961-4678-abe2-cd4df85fe427.mp4

(there's a video below to better explain my problem.)
Hope this problem would get solved soon :)

**Comment by jef-n** [comment]
3.18 is EOL.  Verify that the issue also exists with 3.20 and/or 3.16 (LTR)

**Comment by gioman** [comment]
> 3.18 is [EOL](https://en.wikipedia.org/wiki/End-of-life_product). Verify that the issue also exists with 3.20 and/or 3.16 (LTR)

@JacobyoonDH also: 

1 issue per ticket

use meaningful titles

add all the necessary/requested infos, attaching a sample project+data when necessary



**Describe the bug**


**How to Reproduce**



1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error -->

**QGIS and OS versions**



**Additional context**

**Comment by uclaros** [comment]
Are the data stored in a database?
Are other users editing the same data at the same time?

**Comment by JacobyoonDH** [comment]
> Are the data stored in a database?
> Are other users editing the same data at the same time?

No the data is stored in desktop not database

**Comment by uclaros** [comment]
> Are other users editing the same data at the same time?

**Comment by gioman** [comment]
Also try with a new QGIS profile, no 3rd party plugins installed.
