### ISSUE TITLE
Label masking causes layout vector & raster to be mis-aligned

### ISSUE THREAD

**Issue by TonyShep** [qgis/QGIS#44426]
### What is the bug or the crash?

It seems that if label masking is enabled, when viewing the map layout, raster and vector layers appear mis-aligned on the layout. If printing, or exporting to PDF, or exporting to raster the output is correct.

Disable masking, and the layout is then correctly displayed.

I have attached a QGIS project file with data. Description as follows:
 QGIS Project file
 Layout with two identical map windows, one with masking one without.  Its easy to see that when looking at the screen one is not correctly aligned.
 PDF output (correct)
 Screen shot (alignment issues clear to see)

Tested on both 3.20.0 and 3.20.1
Not an issue on versions prior to 3.20

Regards
Tony
[QGIS-3.20-Masking-Issues.zip](https://github.com/qgis/QGIS/files/6896055/QGIS-3.20-Masking-Issues.zip)

### Steps to reproduce the issue

As above

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.20.1-Odense | QGIS code revision | 1c3c5cd6
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.1
PROJ version | 8.1.0
EPSG Registry database version | v10.018 (2021-04-02)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins | ClipMultipleLayersDataPlotlygisquick-qgis-pluginImportPhotoslinz-data-importerMerginprofiletoolqgis2webqgiscloudqgis_resource_sharingQPackageQuickOSMquick_map_servicesSentinelHubsplitmultipartSplitPolygonShowingAreasdb_managerprocessing

</body></html>

**Comment by tomass** [comment]
Some additional info which might help.
I have a map with a lot of vector layers and a hillshade from raster (geotiff).
Now in print layout, if zoom is set to 100% (lower right corner) - then position of raster is good.
If I increase the zoom to 101% - raster moves in direction of NW:
If zoom is increased to 102% - raster moves even further in the same direction.

And some pictures, look at hillshade for the river.
Zoom = 100%
![image](https://user-images.githubusercontent.com/969513/135728206-77e3db27-9223-41b1-95b2-4b52f8e6b15f.png)

Zoom = 101%
![image](https://user-images.githubusercontent.com/969513/135728256-f8839d41-1516-4060-9fcf-c1ff7969f31e.png)

Zoom = 102%
![image](https://user-images.githubusercontent.com/969513/135728294-265fc564-69e5-473f-930f-f553455bbcc0.png)

Zoom = 104%
![image](https://user-images.githubusercontent.com/969513/135728314-cd552ddc-9fa2-4eb4-80d0-236e95dcbeef.png)

Direction is same (strongly Westwards, slightly Northwards) and distance of displacement correlates to zoom level set.
If I remove all maskings - raster gets back to its correct position.
