### ISSUE TITLE
Attributes Form won’t recognize filled required field when using it in 3 or more tabs.

### ISSUE THREAD

**Issue by vru** [qgis/QGIS#44423]
### What is the bug or the crash?

Attributes Form won’t recognize filled required field when using it in 3 or more tabs.
This field is used in all 3 tabs. Only in the last tab it is recognized as required field (with red x or green v). In tab 2 you need to change the value to close the dialog and add the point.

First tab: all the required fields are filled and checked:
![image](https://user-images.githubusercontent.com/1300788/127347265-2a4f049e-3f01-4f86-95a5-ecbf4c4a1500.png)

Third tab: 2 fields also used in tab 1 are filled and checked:
![image](https://user-images.githubusercontent.com/1300788/127347580-0b029a88-f134-403e-8cbc-5debfc4f2c51.png)

Second tab: 1 required field which is used in tab 1 en 2 is filled but not checked:  
![image](https://user-images.githubusercontent.com/1300788/127347841-83426f9c-e1d1-4742-ad50-82341b3ab9d3.png)

### Steps to reproduce the issue

Use the identity tool for adding a point.
Fill the required fields.
One field is used in different tabs.
This field is populated automatic in the other tabs.
In tab 1 and 3 the input is validated/correct.
In tab 2 (same field/value) the input doesn't get recognized as validated/correct.

### Versions

3.18.3 Zurich

**Comment by gioman** [comment]
> 3.18.3 Zurich

@vru this version is EOL, you must test also on 3.20 (or 3.16).

**Comment by vru** [comment]
@gioman Same issue with version 3.20. With version 3.10.2 no issues.

**Comment by alexbruy** [comment]
Still an issue? I can't reproduce using provided steps on latest master (5566e42635)
