### ISSUE TITLE
icons not visible in the Layer Notes 

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#44425]
### What is the bug or the crash?

the icons for bold, italic, underline and strikethrough are not visible in the Layer Notes window; as shown in the figure

![image](https://user-images.githubusercontent.com/7631137/127375341-ad66e181-8dc1-434f-a7b8-1895b80b5e0b.png)

### Steps to reproduce the issue

1. right click on a layer present in the TOC
2. in the context menu select Add Layer Notes ...

## OSGeo4W64 win10

```

QGIS version 3.20.1-Odense
QGIS code revision 1c3c5cd6
Qt version 5.15.2
Python version 3.9.5
GDAL/OGR version 3.3.1
PROJ version 8.1.0
EPSG Registry database version v10.027 (2021-06-17)
GEOS version 3.9.1-CAPI-1.14.2
SQLite version 3.35.2
PDAL version 2.3.0
PostgreSQL client version 13.0
SpatiaLite version 5.0.1
QWT version 6.1.3
QScintilla2 version 2.11.5
OS version Windows 10 Version 2009
```

### Additional context

the problem is also present in the master

Thank you

**Comment by gioman** [comment]
Is fine on master/Ubuntu 20.04.

**Comment by agiudiceandrea** [comment]
It seems the Layer Notes uses the QgsRichTextEditor widget (introduced with PR https://github.com/qgis/QGIS/pull/42863) so it uses the "[themed icons](https://doc.qt.io/qt-5/qicon.html#fromTheme)" which are only available by default on X11 based systems (GNU\Linux) and are not available by default on Mac and Windows systems:

> By default, only X11 will support themed icons. In order to use themed icons on Mac and Windows, you will have to bundle a compliant theme

So, I think on Windows and Mac a freedesktop compatible icon theme (e.g. https://github.com/KDE/oxygen-icons) is needed to be installed and a fallback search paths for the unthemed incons should be set.

**Comment by nyalldawson** [comment]
@agiudiceandrea it's probably easier just to copy these couple of icons to the qgis tree instead

**Comment by pigreco** [comment]
could someone put the links to the icons here?
then, where should I put them?
