### ISSUE TITLE
Trying to cut a line crashed QGIS 3.16.5

### ISSUE THREAD

**Issue by padmoo** [qgis/QGIS#44420]
## User Feedback

Wanted to cut a line

## Report Details

**Crash ID**: [110a0382142c08c88ac37df9859e2ad685d2aaf7](https://github.com/qgis/QGIS/search?q=110a0382142c08c88ac37df9859e2ad685d2aaf7&type=Issues)

**Stack Trace**
<pre>
QString::operator= :
QgsGeometry::symDifference :
QgsGeometry::splitGeometry :
QgsGeometry::splitGeometry :
QgsVectorLayerEditUtils::splitFeatures :
QgsVectorLayer::splitFeatures :
QgsMapToolSplitFeatures::cadCanvasReleaseEvent :
QgsMapToolAdvancedDigitizing::canvasReleaseEvent :
QgsMapCanvas::mouseReleaseEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.16.5-Hannover
QGIS code revision: 58ba7c1ed6
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

### Steps to reproduce the issue

Try cutting a line, no line currently works, but was fine 30 mins ago.

### Versions

QGIS version
3.16.5-Hannover
QGIS code revision
58ba7c1ed6
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
autoSaver; 
nominatim; 
QGIS3-getWKT; 
quick_map_services; 
db_manager; 
MetaSearch; 
processing

**Comment by gioman** [comment]
@padmoo try with a new QGIS profile, no 3rd party plugins installed.
