### ISSUE TITLE
StopIteration problem when running DKI Jakarta Basic.qgs project of InaSafe 5.0.1

### ISSUE THREAD

**Issue by haytastan** [qgis/QGIS#44438]
### What is the bug or the crash?

The following problem(s) were encountered whilst running the analysis : StopIteration

Diagnostics:
In file "C:\Users/hayati.tastan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1470, in run self.style()
In file "C:\Users/hayati.tastan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\inasafe\safe\impact_function\impact_function.py", line 2489, in style classes = generate_classified_legend(
In file "C:\Users/hayati.tastan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\inasafe\safe\impact_function\style.py", line 126, in generate_classified_legend analysis_row = next(analysis.getFeatures())

### Steps to reproduce the issue

1. Open DKI Jakarta Basic.qgs project of InaSafe 5.0.1
2. Run the analysis.

### Versions

QGIS version
3.20.1-Odense
QGIS code revision
1c3c5cd6
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.1
PROJ version
8.1.0
EPSG Registry database version
v10.018 (2021-04-02)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 1803

Active Python plugins
AequilibraE
Anaximandre
AnotherDXF2Shape
attributeBasedClustering
BatchHeatmaps-master
BDOO_GML_Loader
BulkVectorExport
bulkvectorexportwithstyle
ClipMultipleLayers
covid19_tracker
easy_raster_splitter
ee_plugin
FastVersion
FeatureGridCreator
GeoCoding
geospatialsimulation
HCMGIS
HTML_Generator-main
ibamaprocessing
inasafe
JSONEater-master
Qgis2threejs
quick_map_services
db_manager
MetaSearch
processing
CustomToolBar

**Comment by Gustry** [comment]
The QGIS project can't do anything about a third party plugin. You must report the issue in the plugin code repository.
