### ISSUE TITLE
When searching in functions, string_to_array is always returned

### ISSUE THREAD

**Issue by uclaros** [qgis/QGIS#44433]
### What is the bug or the crash?

When searching the functions in an expression editor, `string_to_array` is always on the results regardless of the search string.

### Steps to reproduce the issue

1. Add a vector layer
2. Use *select by expression*
3. Use the functions' *search* field and type anything
4. *string_to_array* is in the results!

### Versions

3cd62b3cbb on Debian Bullseye

**Comment by nicogodet** [comment]
Master only ?

Seems ok on 3.20.1
![image](https://user-images.githubusercontent.com/39594821/127486229-efaee96c-475b-4dc0-9794-a7474b33cea7.png)

**Comment by uclaros** [comment]
Could be master only, I tried on an older 3.15 build (02f5c13ea0) I have and cannot reproduce.

**Comment by agiudiceandrea** [comment]
It seems to me this regression may have been introduced with commit https://github.com/qgis/QGIS/commit/55608c2188896dd85602511ea38f1daeb932a26f#diff-ff13608308ddea5a27ab09922eb42329c927306c66f884d7de22b0abda25742b (from PR https://github.com/qgis/QGIS/pull/44383).

I don't know how to fix it (apart from reverting the above commit).

**Comment by uclaros** [comment]
You're right!
It seems that `QSortFilterProxyModel::filterRegularExpression()` called here:
https://github.com/qgis/QGIS/blob/af9a72eda6922f0ee08a2fd28f26dafbaa079d92/src/gui/qgsexpressiontreeview.cpp#L841-L845
returns an empty `QRegularExpression` so it matches every tag, and `string_to_array` is the only function with tags defined so it gets displayed in the results.
Before 55608c2 `QSortFilterProxyModel::filterRegExp()` was used that returned a `QRegExp` containing the correct search pattern.
Maybe this is an upstream bug in QT?
@nyalldawson is it ok to keep the `fiterRegExp()` method here?

**Comment by nyalldawson** [comment]
@uclaros looks like the line calling "setFilterWildcard" on the proxy model will need changing to setFilterRegularExpression, using a QRegularExpression built using fromWildcard.

We can't leave filterRegExp here, it breaks the qt 6 builds.

**Comment by agiudiceandrea** [comment]
@uclaros anyway, while `setFilterWildcard()` sets a QRegExp in Qt < 6 (and thus `filterRegExp()` should be used to retrieve the filter Qt < 6), it sets a QRegularExpression in Qt >= 6 so `filterRegularExpression()` could be used in Qt > 6 without issues.

See https://github.com/qt/qtbase/commit/eb349930eee1ca8f31415dd2269a70d3dfd76257#diff-35536aff6ab7668bdf538b65b5c8f5fa32e81e5405996434c2cc5f59205729f1L2827-R2645
