### ISSUE TITLE
QGIS 3.20.1 unexpectedly ended when running DKI_Jakarta_Basic.qgs project of InaSafe 5.0.1 

### ISSUE THREAD

**Issue by haytastan** [qgis/QGIS#44437]
### What is the bug or the crash?

Crash ID: 54189c0b3c28c1341092ac5f5c4e8a0e62dd5247

Stack Trace

QgsField::QgsField :
QgsFields::operator[] :
QgsGdalLayerItem::setCrs :
QgsVectorLayerEditBuffer::commitChanges :
QgsVectorLayer::commitChanges :
PyInit__core :
PyArg_ParseTuple_SizeT :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyFunction_Vectorcall :
PyVectorcall_Call :
PyObject_Call :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyEval_EvalFrameDefault :
PyFunction_Vectorcall :
PyVectorcall_Call :
PyObject_Call :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyEval_EvalFrameDefault :
PyFunction_Vectorcall :
PyVectorcall_Call :
PyObject_Call :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyEval_EvalFrameDefault :
PyEval_EvalFrameDefault :
PyFunction_Vectorcall :
PyFloat_FromDouble :
PyVectorcall_Call :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QObject::qt_static_metacall :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
PyInit_QtWidgets :
QWidget::event :
PyInit_QtWidgets :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.20.1-Odense
QGIS code revision: 1c3c5cd6
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.1
Running against GDAL: 3.3.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

### Steps to reproduce the issue

1. Install InaSafe 5.01 
2. Run the InaSafe Analysis
3. See the Crash

### Versions

QGIS 3.2.1.01

**Comment by Gustry** [comment]
The QGIS project can't do anything about a third party plugin. You must report the issue in the plugin code repository.
