### ISSUE TITLE
Wrong values on interpolated lines classes usining localized QGIS (using dot as thousands separator)

### ISSUE THREAD

**Issue by Viskovitz** [qgis/QGIS#44443]
### What is the bug or the crash?

Using the interpolated line symbol, if I use the $length function to set the end value QGIS can calculate the maximum value set the color ramp. The problem is when I click on classify the values seems not to take the decimal separator as thousands separator.

https://user-images.githubusercontent.com/792066/127536144-dfdd9747-d184-40e2-b091-333c05bce119.mp4

### Steps to reproduce the issue

1. Set the symbol layer as interpolated line
2. Set the start value to 0
3. Set the end value to `$length`
4. Refresh to calculate the length of the lines
5. Check the classes

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

Versión de QGIS | 3.20.0-Odense | Rama del código de QGIS | Release 3.20
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.8.10
Compilado contra GDAL/OGR | 3.3.0 | Ejecutándose contra GDAL/OGR | 3.3.1
PROJ version | 7.2.1
EPSG Registry database version | v10.008 (2020-12-16)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.36.0
PostgreSQL client version | 12.7
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.6
OS version | openSUSE Tumbleweed
  |   |   |  
Esta copia de QGIS escribe salida de depurado.
  |   |   |  
Active Python plugins | pluginbuilder3gestion_residuossynthwaveservicio_bjhSmart_Mapplugin_reloaderdb_managerprocessing

</body></html>

### Additional context

QGIS is set up in spanish localization (es_ES) running in Opensuse Tumbleweed.

**Comment by gioman** [comment]
I cannot replicate with my own data, @Viskovitz can you attach a sample?

**Comment by uclaros** [comment]
This looks locale related. See how when the *Max. value* is `538.253` the dot is interpreted as a thousand separator but when the value is changed to `538.25` the dot is suddenly interpreted as a decimal separator and everything seems to work ok!

**Comment by Viskovitz** [comment]
It seems to occur only when the length of the line is less than 1000.

https://user-images.githubusercontent.com/792066/127686763-be5a20a7-8e0f-46f9-85ac-610a4d6dfb7a.mp4

**Comment by elpaso** [comment]
I think this was fixed in master https://github.com/qgis/QGIS/pull/43831/files#diff-7453a5c0e198d1c67ee4ce4499e2df710488f83877616fb07944d3dabdb2fd31R392

The logic behind the QGIS implementation of number parsing is:

1. try to interpret the number according to user locale settings (including decimal and thousand separators)
2. if the above 1. fails, try the `C` locale ( `.` as a decimal separator, no thousand separator)

**Comment by elpaso** [comment]
I don't see any bug in current master, not sure if we need to backport the fix to any previous version though.
