### ISSUE TITLE
crash when trying to change raster layer data source

### ISSUE THREAD

**Issue by pecard** [qgis/QGIS#44440]
## User Feedback

Crash while trying to change raster layer source.

(Reload QGIS option never works)

## Report Details

**Crash ID**: [062bc0bd376242c360a2096d240e4634416293f8](https://github.com/qgis/QGIS/search?q=062bc0bd376242c360a2096d240e4634416293f8&type=Issues)

**Stack Trace**
<pre>
QgsRasterIdentifyResult::operator= :
QgsColorRampShaderWidget::setRasterBand :
QgsSingleBandPseudoColorRendererWidget::loadMinMax :
QObject::qt_static_metacall :
QgsRasterMinMaxWidget::load :
QgsRasterMinMaxWidget::doComputations :
QgsRasterLayerProperties::apply :
QObject::qt_static_metacall :
QDialogPrivate::finalize :
QObject::qt_static_metacall :
QDialogButtonBox::qt_static_metacall :
QObject::qt_static_metacall :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.20.1-Odense
QGIS code revision: 1c3c5cd6
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.1
Running against GDAL: 3.3.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

### Steps to reproduce the issue

A temp raster created (with viewshed)
temp .tif file exported to a local folder
do not add the new created tif.
In Qgis , select the temp raster properties, try to change layer data source pointing to the saved tif file
Qgis crash.

### Versions

QGIS Version: 3.20.1-Odense

### Additional context

Reload QGIS should work ?

**Comment by gioman** [comment]
@pecard what are the **detalied** steps to follow to replicate the issue? Have you tried with a new QGIS profile (no 3rd party plugins installed)?
