### ISSUE TITLE
Zooming on layout crashes QGIS

### ISSUE THREAD

**Issue by antoniolocandro** [qgis/QGIS#44445]
### What is the bug or the crash?

When zooming on a layout QGIS crashes

### Steps to reproduce the issue

Well this one probably has to do with the settings in the project and the crash report will probably be more useful which I added as additional context

### Versions

QGIS version
3.20.0-Odense
QGIS code revision
decaadbb31
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.1
PROJ version
8.1.0
EPSG Registry database version
v10.027 (2021-06-17)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
gml_application_schema_toolbox
MemoryLayerSaver
quick_map_services
db_manager
processing

### Additional context

Crash ID: b2404be2ca1eb9e52b4a0d20b1a081f31e6475e1

Stack Trace

initGEOS :
GEOSGeomTypeId_r :
pal::PointSet::offsetCurveByDistance :
pal::FeaturePart::createCurvedCandidatesAlongLine :
pal::FeaturePart::createCandidates :
pal::Pal::extract :
pal::Pal::extractProblem :
QgsLabelingEngine::solve :
QgsDefaultLabelingEngine::run :
QgsMapRendererJob::drawLabeling :
QgsMapRendererCustomPainterJob::doRender :
QgsMapRendererCustomPainterJob::staticRender :
QgsMapRendererCustomPainterJob::renderSynchronously :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.20.0-Odense
QGIS code revision: decaadbb31
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.1
Running against GDAL: 3.3.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22000

**Comment by nyalldawson** [comment]
Can you share the project? I'd love to track this one down (you can send it to me privately if you want)

**Comment by antoniolocandro** [comment]
Sure, is there a way to save project with layers all in one?

**Comment by nyalldawson** [comment]
Try the consolidate plugin

**Comment by antoniolocandro** [comment]
Link sent by email
