### ISSUE TITLE
Unable to load certain plugins

### ISSUE THREAD

**Issue by CommunyAS** [qgis/QGIS#44465]
### What is the bug or the crash?

For various plugins, after installing them both using the QGIS plugin manager or from ZIP, when loading them I get an error notification 
_Couldn't load plugin 'PLUGINNAME' due to an error when calling its classFactory() method 
ModuleNotFoundError: No module named 'plugins.processing'_
(see example screenshot). This happens not with all, but with multiple plugins.

I checked, if all the paths i.e. to python are set correctly (they are).

![Screen Shot 2021-07-30 at 13 15 08 (CEST)](https://user-images.githubusercontent.com/74900017/127694216-75aedb7f-9ab0-4b54-b7ff-da2a28bd6a96.png)

### Steps to reproduce the issue

1. Install plugin using QGIS plugin manager or from ZIP
2. Load plugin

### Versions

QGIS-LTR 3.16.8 on macOS 10.13.6 (High Sierra).

**Comment by gioman** [comment]
@CommunyAS what plugins are we speaking of?

**Comment by roya0045** [comment]
Pretty common error, possible that the plugins are simply not updated or did not follow api changes.

**Comment by CommunyAS** [comment]
Sorry, I attached the wrong screen shot and updated my first entry now (see above).
I have this issue with _Visibility Analysis_ plugin - when loading this plugin resulting in the error log message on the (now correct) screen shot.

I realised that also the GDAL _Viewshed_ routine from the toolbox and GRASS do not work. Regarding GRASS I get this message

> 2021-07-30T20:07:30     WARNING    GRASS init error : Problem in GRASS initialization, GRASS provider and plugin will not work : Module built against version 2021-02-10T17:13:06+00:00 but trying to use version 2021-02-10T17:08:53+00:00. You need to rebuild GRASS GIS or untangle multiple installations.

Might those problems be related?

**Comment by gioman** [comment]
> Sorry, I attached the wrong screen shot and updated my first entry now (see above).
> I have this issue with _Visibility Analysis_ plugin - when loading this plugin resulting in the error log message on the (now correct) screen shot. But I had the issue with other plugins too, but can't remember which ones exactly.

@CommunyAS you must report this to the plugin author, not here.




> Might those problems be related?

seems unrelated to me, anyone is not a QGIS general issue but a local one.
