### ISSUE TITLE
Line interpolation symbology only works when project CRS is equal to layer CRS

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#44464]
### What is the bug or the crash?

If the two CRSs do not match then applying a line interpolation symbology renders nothing.

Rested on master on Windows and Linux.

### Steps to reproduce the issue

Add a line layer and apply a line interpolation symbology "varying color". It only renders if the CRS of the project matches then one of the layer.

### Versions

3.20/master.

**Comment by nyalldawson** [comment]
This was fixed by https://github.com/qgis/QGIS/pull/45164
