### ISSUE TITLE
Open composer crash on a map that work with 3.18

### ISSUE THREAD

**Issue by Michael-cd30** [qgis/QGIS#44461]
## User Feedback

QGis crash when I trie to open the composer on a map that used to work with 3.18.

## Report Details

**Crash ID**: [b2404be2ca1eb9e52b4a0d20b1a081f31e6475e1](https://github.com/qgis/QGIS/search?q=b2404be2ca1eb9e52b4a0d20b1a081f31e6475e1&type=Issues)

**Stack Trace**
<pre>
initGEOS :
GEOSGeomTypeId_r :
pal::PointSet::offsetCurveByDistance :
pal::FeaturePart::createCurvedCandidatesAlongLine :
pal::FeaturePart::createCandidates :
pal::Pal::extract :
pal::Pal::extractProblem :
QgsLabelingEngine::solve :
QgsDefaultLabelingEngine::run :
QgsMapRendererJob::drawLabeling :
QgsMapRendererCustomPainterJob::doRender :
QgsMapRendererCustomPainterJob::staticRender :
QgsMapRendererCustomPainterJob::renderSynchronously :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.20.1-Odense
QGIS code revision: 1c3c5cd6
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.1
Running against GDAL: 3.3.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

### Steps to reproduce the issue

Open the composer

### Versions

3.20.1

### Additional context

I've reinstalled 3.18 and the same map seems to work.

**Comment by gioman** [comment]
@Michael-cd30 please attach the problematic project + necessary data.

**Comment by Michael-cd30** [comment]
Unfortunately, this map is a big one and use data stored on an internal PostreSQL/Postgis.
I'll try to work on a simplified one that I could upload.

**Comment by Michael-cd30** [comment]
It seems that the crash was due to a partially corrupted qgz.
I've reverted the project to a previous version and it seems to work.

I close this one.
