### ISSUE TITLE
Layer actions in one clic

### ISSUE THREAD

**Issue by dd-a** [qgis/QGIS#44473]
### Feature description

Hi !

I have been using actions in QGIS for years and I find them very useful and much easier to create than plugins.  As a reminder, they can have 4 different scopes, which are 'Field', 'Feature', 'Layer' and 'Canvas'.

However, there is one thing I don't understand: when choosing 'Canvas', it is always necessary to click on an layer element after choosing the action to be used in the attributes toolbar (with the action button - the little wheel). Why is this? Wouldn't it be easier to immediately trigger an action by clicking on its name in the toolbar? 
In particular, I have defined a Python action that fetches a file containing data to be imported into a database, with no specific link to a particular entity.

So, have I misunderstood the use of the action?  Am I missing something?  
Or maybe better, would it be possible to have actions not related to any layer ?

**Comment by gioman** [comment]
> So, have I misunderstood the use of the action? Am I missing something?
> Or maybe better, would it be possible to have actions not related to any layer ?

@dd-a questions should not be asked here, use the users or developers mailing lists.

**Comment by dd-a** [comment]
Ok
