### ISSUE TITLE
Clear recent projects 

### ISSUE THREAD

**Issue by antoniolocandro** [qgis/QGIS#44478]
### Feature description

Seems only way to do this is through using python code which is not user friendly , one should have the ability to remove projects from the recent list. The following code removes all https://gis.stackexchange.com/questions/199305/how-to-remove-a-qgis-project-from-the-recent-projects-list but probably would be great to have _also_ the possibility to remove the individual project using a right click and remove option

**Comment by DelazJ** [comment]
This is already available if in the Settings --> Options --> General, you display the "welcome page". You can delete recent projects.

**Comment by agiudiceandrea** [comment]
@antoniolocandro if I understand correctly your request, you can remove projects from the recent projects list using the right-click contextual menu
![image](https://user-images.githubusercontent.com/16253859/127730386-fd0bc074-942e-4e93-a18f-48ccd261dc0b.png)

**Comment by antoniolocandro** [comment]
Although technically correct you can do this, you can only see it on QGIS start. Once you have passed that screen and you want to do this it is not possible as I am not aware on a way to show the recent project panel again

Also it would be more convenient to do it at this level which is probably what most users would try 

![image](https://user-images.githubusercontent.com/4627073/127893529-7a327864-3bbd-451d-8d9d-097dfa4ba43e.png)
