### ISSUE TITLE
Possibility to reorder fields on field list when creating new layer

### ISSUE THREAD

**Issue by antoniolocandro** [qgis/QGIS#44477]
### Feature description

Would be nice to be able to drag the fields in the field list if I wanted to rearrange the order for any reason prior to creating the layer

### Additional context

![image](https://user-images.githubusercontent.com/4627073/127720412-cc4d8e15-7a56-4894-b960-58bad9deb09d.png)

**Comment by alexbruy** [comment]
Duplicates #38241
