### ISSUE TITLE
"Python >= 3.8, DLLs are no longer imported from the PATH. . . . "

### ISSUE THREAD

**Issue by HenryScheyvens** [qgis/QGIS#44480]
### What is the bug or the crash?

When trying to create a ROI using the Semi-Automatic Classification plugin in QGIS, I receive the following message "
             On Windows, with Python >= 3.8, DLLs are no longer imported from the PATH.
             If gdalXXX.dll is in the PATH, then set the USE_PATH_FOR_GDAL_PYTHON=YES environment variable
             to feed the PATH into os.add_dll_directory()."
This message occurred after I had uninstalled earlier versions of QGIS. I uninstalled QGIS and the other programs in the OSGeo4W shell and reinstalled the shell, but I still receive this message. 

### Steps to reproduce the issue

1. Install earlier versions of QGIS
2. Install latest version of QGIS.
3. Uninstall earlier versions of QGIS.

### Versions

QGIS version
3.16.9-Hannover
QGIS code revision
9f8d2f79
Compiled against Qt
5.15.2
Running against Qt
5.15.2
Compiled against GDAL/OGR
3.3.1
Running against GDAL/OGR
3.3.1
Compiled against GEOS
3.9.1-CAPI-1.14.2
Running against GEOS
3.9.1-CAPI-1.14.2
Compiled against SQLite
3.35.2
Running against SQLite
3.35.2
PostgreSQL Client Version
13.0
SpatiaLite Version
5.0.1
QWT Version
6.1.3
QScintilla2 Version
2.11.5
Compiled against PROJ
8.1.0
Running against PROJ
Rel. 8.1.0, July 1st, 2021
OS Version
Windows 10 Version 2009
Active python plugins
qgis_resource_sharing; 
rasterstats; 
SemiAutomaticClassificationPlugin; 
db_manager; 
MetaSearch; 
processing

**Comment by gioman** [comment]
> When trying to create a ROI using the Semi-Automatic Classification plugin in QGI

@HenryScheyvens you must report this to the SCP plugin author, not here.

**Comment by jef-n** [comment]
gdalXXX.dll should be on PATH and QGIS should os.add_dll_directory() already.

**Comment by ALazyPM** [comment]
How's  the problem solved eventually?????
Met the same issue too while import gdal to python
