### ISSUE TITLE
Crash on using Move Label tool while a vector tile layer with labels is visible

### ISSUE THREAD

**Issue by atlight** [qgis/QGIS#44486]
### What is the bug or the crash?

QGIS crashes when using the Move Label tool while a labelled vector tile layer is visible.

### Steps to reproduce the issue

1. Add an online vector tile layer to the map (I am using Mapbox Streets v8)
2. Arrange things so the vector tile layer contains labels. For example, use a vector tile layer with labels in the style (see @gioman's comment below), or set up labelling so that a line layer of the vector tile layer has labels (e.g. the `name` attribute of the `road` layer for Mapbox Streets), and zoom in far enough so that some labels are visible
3. Add a random vector layer (e.g. shapefile) and enable labelling on that layer
4. In the Layers panel, Select the random vector layer you just added
4. Click the "Move a Label, Diagram or Callout" tool on the advanced labelling toolbar
5. Mouse over a vector tile label on the map canvas

### Versions

QGIS version
3.20.1-Odense
QGIS code revision
1c3c5cd6
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.1
PROJ version
8.1.0
EPSG Registry database version
v10.018 (2021-04-02)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 1809

Active Python plugins
awap
interfacecatchment
OSMDownloader
qgis-maptiler-plugin
QNEAT3
db_manager
MetaSearch
processing

### Additional context

This doesn't crash in 3.16.

## Report Details

**Crash ID**: [adfec6e26281a25b8130976c2838d0e394ec0a9e](https://github.com/qgis/QGIS/search?q=adfec6e26281a25b8130976c2838d0e394ec0a9e&type=Issues)

**Stack Trace**
<pre>
QString::QString :
QgsNetworkReplyParser::error :
QgsMapToolLabel::updateHoveredLabel :
QgsMapCanvas::mouseMoveEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.20.1-Odense
QGIS code revision: 1c3c5cd6
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.1
Running against GDAL: 3.3.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by gioman** [comment]
>     2\. Set up labelling so that a line layer of the vector tile layer has labels (e.g. the `name` attribute of the `road` layer for Mapbox Streets), and zoom in far enough so that some labels are visible

I was able to replicate the issue, but enabling manually labels for the vector tiles is not necessary, is enough to use a vector tile layer with a style that has labels, i.e.

https://basemaps.arcgis.com/arcgis/rest/services/World_Basemap_v2/VectorTileServer

https://www.arcgis.com/sharing/rest/content/items/273bf8d5c8ac400183fc24e109d20bcf/resources/styles/root.json?f=pjson

So I guess that the title and description could be improved.

**Comment by atlight** [comment]
Is there a reason why this issue has the `feedback` and `stale` labels? I believe that by changing the title of the issue, I addressed @gioman's comment.
