### ISSUE TITLE
Unnecessary "Classify" button in "Color ramp"-based raster/mesh symbology?

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#44481]
### What is the bug or the crash?

The "Classify" button when symbolizing a raster or mesh layer with color ramp (or color ramp shader widget) seems useless as the classification table updates as soon as you select options. 

### Steps to reproduce the issue

Open a raster symbology properties tab, singleband pseudocolor and play with the options. Things update as soon as you change. No need to classify afaict.
https://user-images.githubusercontent.com/7983394/127728111-14c9099a-7f3a-41ee-8867-78798e3989bf.mp4

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.21.0-Master | QGIS code revision | dc6b97ceda
-- | -- | -- | --
Qt version | 5.12.8
Python version | 3.8.10
GDAL/OGR version | 3.0.4
PROJ version | 6.3.1
EPSG Registry database version | v9.8.6 (2020-01-22)
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
SQLite version | 3.31.1
PostgreSQL client version | 12.7 (Ubuntu 12.7-0ubuntu0.20.04.1)
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.2
OS version | Ubuntu 20.04.2 LTS
  |   |   |  
Active Python plugins | trackable_project_files closest_points MapsPrinter MemoryLayerSaver plugin_reloader layertreeicons db_manager grassprovider MetaSearch processing sagaprovider

</body></html>

**Comment by gioman** [comment]
If you remove/add symbology classes the "classify" button isn't used to "restore" the default one?

**Comment by DelazJ** [comment]
@gioman Indeed, it's used to reset the classification to the active options.
I checked the vector and it's somehow the same behaviour. So probably not an issue...?

**Comment by gioman** [comment]
> So probably not an issue...?

I would say no issue, but maybe let's wait for the opinion of more people :)
