### ISSUE TITLE
QGIS 3.20 crashes with add spreadsheet layer - Mac OSBigSur11.3.1

### ISSUE THREAD

**Issue by purplecacti** [qgis/QGIS#44484]
### What is the bug or the crash?

I cannot get Qgis 3.20 (or previously 3.18) to add a spreadsheet layer.
This works fine with the LTR version.

[The new balloon call outs in 3.20 have me wanting to move to 3.20 so I now am very motivated to try and fix]
I have deleted my user profiles - no luck. Have uninstalled & reinstalled plugin - no luck.

### Steps to reproduce the issue

1. Go to layer/add spreadsheet layer. 
2. Interface pops up. 
3. Click to browse to a spreadsheet file  - QGIS crashes (also if you hit the help button)

### Versions

QGIS version | 3.20.0-Odense | QGIS code revision | decaadbb31
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.8.7
GDAL/OGR version | 3.2.3
PROJ version | 6.3.2
EPSG Registry database version | v9.8.6 (2020-01-22)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.31.1
PDAL version | 2.2.0
PostgreSQL client version | 12.3
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.4
OS version | macOS 11.3
  |   |   |  
Active Python plugins | SpreadsheetLayersprocessingdb_managerMetaSearch

### Additional context

Crash file is about 50 pages - not sure how much of it I need to post... Any help would be very gratefully received.

Process:               QGIS [899]
Path:                  /Applications/QGIS.app/Contents/MacOS/QGIS
Identifier:            org.qgis.qgis3
Version:               3.20.0 (3.20.0 [])
Code Type:             X86-64 (Translated)
Parent Process:        ??? [1]
Responsible:           QGIS [549]
User ID:               501

Date/Time:             2021-07-31 14:51:48.210 +1000
OS Version:            macOS 11.3.1 (20E241)
Report Version:        12
Anonymous UUID:        6BB4255F-DDCA-4D37-AB04-D7D4CF8A8894

Time Awake Since Boot: 150 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000018
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [899]

VM Regions Near 0x18:
--> 
    __TEXT                      104f0f000-104f73000    [  400K] r-x/r-x SM=COW  /Applications/QGIS.app/Contents/MacOS/QGIS

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libpython3.8.dylib            	0x000000011752ecfb _PyFrame_New_NoTrack + 27
1   libpython3.8.dylib            	0x000000011751d893 _PyFunction_Vectorcall + 147
2   libpython3.8.dylib            	0x000000011751f22d method_vectorcall + 413
3   libpython3.8.dylib            	0x000000011751d3bb PyVectorcall_Call + 107
4   QtCore.so                     	0x0000000163f46b47 PyQtSlot::call(_object*, _object*) const + 39
5   QtCore.so                     	0x0000000163f46a56 PyQtSlot::invoke(void**, _object*, void*, bool) const + 374
6   QtCore.so                     	0x0000000163f46aec PyQtSlot::invoke(void**, _object*, void*) const + 12

etc...

**Comment by gioman** [comment]
@purplecacti isn't "spereadsheet layers" a 3rd party plugin? if yes you must report this to the plugin author/s, not here.

**Comment by purplecacti** [comment]
@gioman I believe this is a QGIS issue rather than specific plugin as appears to be a core or packaging issue - see this report also which is the same: QGIS 3.20 on Mac crashes when certain Qt signals are emitted #44182.

I did log it on the plugin GitHub page, but I think it is a global QGIS3.20 issue (see #44182 linked above) which therefore has more significance to QGIS? This is my first time posting - so I appreciate your response and guidance if this is the wrong place to report. Thank you!

**Comment by gioman** [comment]
@purplecacti then close this as https://github.com/qgis/QGIS/issues/44182 is already open.

**Comment by purplecacti** [comment]
@gioman - ok thanks - I hope it is the same! I think it is but am very much out of my depth here and really hoping this can be fixed.....
