### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by sayani2021** [qgis/QGIS#44491]
### What is the bug or the crash?

Crash ID: 1d45458be2b382be5332d09ea61918d521fb8eba

Stack Trace

RtlFreeHeap :
free free.c:51
DllUnregisterServer :
DllUnregisterServer :
CServerContextActivator::CreateInstance actvator.cxx:1027
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1855
CApartmentActivator::CreateInstance actvator.cxx:2323
CProcessActivator::CCICallback actvator.cxx:1786
CProcessActivator::AttemptActivation actvator.cxx:1673
CProcessActivator::ActivateByContext actvator.cxx:1519
CProcessActivator::CreateInstance actvator.cxx:1417
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1855
CClientContextActivator::CreateInstance actvator.cxx:713
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1907
ICoCreateInstanceEx objact.cxx:1645
CComActivator::DoCreateInstance immact.hxx:376
CoCreateInstance actapi.cxx:120
_SHCoCreateInstance :
SHExtCoCreateInstance :
DCA_SHExtCoCreateInstance :
CFSIconOverlayManager::_s_LoadIconOverlayIdentifiers :
CFSIconOverlayManager::LoadNonloadedOverlayIdentifiers :
EnableExternalOverlayIdentifiers :
CFSIconOverlayManager::RefreshOverlayImages :
GetIconOverlayManagerImpl :
CFSFolder::_GetOverlayInfo :
CIconOverlayTask::InternalResumeRT :
CRunnableTask::Run :
CShellTaskThread::ThreadProc :
CShellTaskThread::s_ThreadProc :
ExecuteWorkItemThreadProc :
RtlpTpWorkCallback :
TppWorkerThread :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.16.9-Hannover
QGIS code revision: 9f8d2f79
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.1
Running against GDAL: 3.3.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.3.9600

### Steps to reproduce the issue

go to

### Versions

3.16

### Additional context

crash damp scp builtin option

**Comment by sayani2021** [comment]
please give some solution

**Comment by DelazJ** [comment]
> please give some solution

Please fill the sections correctly: explain what you were doing when the crash happened, provide clear steps to reproduce the crash, and add the about tab of your installation as indicated in the bug report template. Thanks

**Comment by sayani2021** [comment]
[image: image.png]
This is my unexpectedly ended pop-up.
Please give some solution.
Crash Id: 818d81928994f1817fc9b37e96f865eaf596d8d4
<https://github.com/qgis/QGIS/search?q=818d81928994f1817fc9b37e96f865eaf596d8d4&type=Issues>

**Comment by gioman** [comment]
> [image: image.png] This is my unexpectedly ended pop-up. Please give some solution.

@sayani2021 if you want to attach files you must use the GitHub web interface, you cannot reply by email.

And anyway if you want to get some help you must add all the necessary info, as requested herehttps://github.com/qgis/QGIS/issues/44491#issuecomment-890407192
