### ISSUE TITLE
Problem With PyQt5.QtCore with qgis._gui

### ISSUE THREAD

**Issue by connor380** [qgis/QGIS#44492]
### What is the bug or the crash?

Qgis._gui does not import from PyQt5.QtCore correctly. I have tried QGIS 3.20.1 and QGIS 3.16.9, both resulted in the same error. I have also tried uninstalling and reinstalling PyQt5.

Error Message:
C:\Python39\python.exe C:/Users/Connor/AppData/Roaming/JetBrains/PyCharmCE2021.2/scratches/TestProcessingQGIS.py
Traceback (most recent call last):
  File "C:\Users\Connor\AppData\Roaming\JetBrains\PyCharmCE2021.2\scratches\TestProcessingQGIS.py", line 16, in <module>
    import processing
  File "C:\Program Files\QGIS 3.20.1\apps\qgis\python\plugins\processing\__init__.py", line 24, in <module>
    from processing.tools.dataobjects import *  # NOQA
  File "C:\Program Files\QGIS 3.20.1\apps\qgis\python\plugins\processing\tools\dataobjects.py", line 38, in <module>
    from qgis.gui import QgsSublayersDialog
  File "C:\Program Files\QGIS 3.20.1\apps\qgis\python\qgis\gui\__init__.py", line 25, in <module>
    from qgis._gui import *
RuntimeError: qgis._gui cannot import type '����' from PyQt5.QtCore

### Steps to reproduce the issue

Sample Python Code:

import sys
from qgis.core import (
     QgsApplication,
     QgsProcessingFeedback,
     QgsVectorLayer
)

QgsApplication.setPrefixPath('C:\\Program Files\\QGIS 3.20.1\\apps\\qgis', True)
qgs = QgsApplication([], False)
qgs.initQgis()

sys.path.append('C:\\Program Files\\QGIS 3.20.1\\apps\\qgis\\python\\plugins')

import processing
from processing.core.Processing import Processing
Processing.initialize()

layer1 = QgsVectorLayer('[ File Path Here]', 'layer 1', 'ogr')
layer2 = QgsVectorLayer('[ File Path Here]', 'ogr')

params = {
    'INPUT' : layer1,
    'OVERLAY' : layer2,
    'OUTPUT' : '/path/to/output_layer.gpkg|layername=output'
}
feedback = QgsProcessingFeedback()

res = processing.run('qgis:union', params, feedback=feedback)
res['OUTPUT'] # Access your output layer

### Versions

QGIS 3.20.1
Python 3.9.6

**Comment by agiudiceandrea** [comment]
Maybe you will find useful to read https://github.com/qgis/QGIS/issues/34317 and https://gis.stackexchange.com/questions/315204/cannot-import-qgis-gui-into-spyder/350204 in order to find a way to fix your issue.

**Comment by connor380** [comment]
Thank you for your help. I previously tried this, but reinstalling PyQt5 and PyQt5-sip did not fix the problem.

I ended up fixing the problem through the answer in this link: 

https://gis.stackexchange.com/questions/381006/cant-run-a-standalone-qgis-application-importerror-dll-load-failed

The solution that worked for me was using Anaconda and the following .bat file to open the environment:

SET OSGEO4W_ROOT=C:\OSGeo4W
call "%OSGEO4W_ROOT%"\bin\o4w_env.bat
call "%OSGEO4W_ROOT%"\bin\qt5_env.bat
call "%OSGEO4W_ROOT%"\bin\py3_env.bat

path %PATH%;%OSGEO4W_ROOT%\apps\qgis\bin
path %PATH%;C:\OSGeo4W\apps\Qt5\bin
path %PATH%;C:\OSGeo4W\apps\Python39\Scripts
set QGIS_PREFIX_PATH=%OSGEO4W_ROOT:\=/%/apps/qgis
set GDAL_FILENAME_IS_UTF8=YES
rem Set VSI cache to be used as buffer, see #6448
set VSI_CACHE=TRUE
set VSI_CACHE_SIZE=1000000
set PYTHONPATH=%PYTHONPATH%;%OSGEO4W_ROOT%\apps\qgis\python
set PYTHONHOME=%OSGEO4W_ROOT%\apps\Python39
set QT_PLUGIN_PATH=%OSGEO4W_ROOT%\apps\qgis\qtplugins;%OSGEO4W_ROOT%\apps\qt5\plugins

"C:\Program Files\JetBrains\PyCharm Community Edition 2020.3.4\bin\pycharm64.exe"


--- or if using the command prompt---


SET OSGEO4W_ROOT=C:\OSGeo4W
call "%OSGEO4W_ROOT%"\bin\o4w_env.bat
call "%OSGEO4W_ROOT%"\bin\qt5_env.bat
call "%OSGEO4W_ROOT%"\bin\py3_env.bat

path %PATH%;%OSGEO4W_ROOT%\apps\qgis\bin
path %PATH%;C:\OSGeo4W\apps\Qt5\bin
path %PATH%;C:\OSGeo4W\apps\Python39\Scripts
set QGIS_PREFIX_PATH=%OSGEO4W_ROOT:\=/%/apps/qgis
set GDAL_FILENAME_IS_UTF8=YES
rem Set VSI cache to be used as buffer, see #6448
set VSI_CACHE=TRUE
set VSI_CACHE_SIZE=1000000
set PYTHONPATH=%PYTHONPATH%;%OSGEO4W_ROOT%\apps\qgis\python
set PYTHONHOME=%OSGEO4W_ROOT%\apps\Python39
set QT_PLUGIN_PATH=%OSGEO4W_ROOT%\apps\qgis\qtplugins;%OSGEO4W_ROOT%\apps\qt5\plugins

cmd.exe
