### ISSUE TITLE
Crashes when adding callout lines to labels

### ISSUE THREAD

**Issue by tgi-ewe** [qgis/QGIS#44511]
### What is the bug or the crash?

QGIS (Version 3.16.0 - Hannover) crashes after turning on callout lines for labels in "Layer Properties" (shapefile). 

Crash ID: 38dfb627cb1973ee90f669124d0cf7c501d37f30

Stack Trace

GEOSEquals_r :
GEOSEquals_r :
QgsGeos::shortestLine :
QgsGeometry::shortestLine :
QgsCallout::QgsCalloutContext::operator= :
QgsSimpleLineCallout::draw :
QgsCallout::render :
QgsVectorLayerLabelProvider::drawCallout :
QgsVectorLayerLabelProvider::drawLabelBackground :
QgsLabelingEngine::drawLabels :
QgsDefaultLabelingEngine::run :
QgsMapRendererJob::drawLabeling :
QgsMapRendererParallelJob::renderLabelsStatic :
QgsMapRendererCustomPainterJob::renderSynchronously :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.16.0-Hannover
QGIS code revision: 43b64b13f3
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

![Screenshot 2021-08-02 115332](https://user-images.githubusercontent.com/88317728/127842704-18413266-5e75-4c9a-ba46-12dc166c4175.png)

### Steps to reproduce the issue

1. Add a shapefile with attributes as a layer
2. Go to "Layer Properties"
3. Go to "Labels"
4. Click on "Callouts"
5. Check "Draw callouts"
6. Click on "OK"

### Versions

QGIS-Version 3.16.0-Hannover

**Comment by nyalldawson** [comment]
Upgrade to the latest 3.16 patch release -- this was fixed in 3.16.1
