### ISSUE TITLE
crach when trying to change font face from a text box in map composer

### ISSUE THREAD

**Issue by pecard** [qgis/QGIS#44516]
## User Feedback

Change font style in a text box.

## Report Details

**Crash ID**: [b3f6a813cbd0213149c19d8c07ed3f9bed11bfec](https://github.com/qgis/QGIS/search?q=b3f6a813cbd0213149c19d8c07ed3f9bed11bfec&type=Issues)

**Stack Trace**
<pre>
QGraphicsScene::wheelEvent :
QGraphicsScene::wheelEvent :
QGraphicsScene::wheelEvent :
QGraphicsScene::wheelEvent :
QGraphicsScene::wheelEvent :
QGraphicsScene::wheelEvent :
QGraphicsScene::wheelEvent :
QGraphicsScene::drawItems :
QGraphicsView::paintEvent :
QgsLayoutView::paintEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::moveRect :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
QGraphicsScene::~QGraphicsScene :
QObject::event :
QGraphicsScene::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.20.1-Odense
QGIS code revision: 1c3c5cd6
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.1
Running against GDAL: 3.3.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

### Steps to reproduce the issue

1. from map composer
2. create a text box
3. change its position
4. open Font editor
5. try to change face style to bold
6. crashes
7. try to reload fail

### Versions

**QGIS Info**
QGIS Version: 3.20.1-Odense
QGIS code revision: 1c3c5cd6
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.1
Running against GDAL: 3.3.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

### Additional context

working a composition with 6 panels (maps) and 3 text boxes

**Comment by gioman** [comment]
@pecard try with a new QGIS profile, no 3rd party plugins installed. If the problem persist please attach/link a sample project + data we can use to replicate.
