### ISSUE TITLE
qgis 3.20.1 crash

### ISSUE THREAD

**Issue by Andrea-Zep** [qgis/QGIS#44512]
### What is the bug or the crash?

Crash ID: 505fbc57fd3e0aa50e4c665531e1555c13017294

Stack Trace

qt_plugin_query_metadata :
qt_plugin_query_metadata :
qt_plugin_query_metadata :
qt_plugin_query_metadata :
qt_plugin_query_metadata :
qt_plugin_query_metadata :
qt_plugin_query_metadata :
qt_plugin_query_metadata :
qt_plugin_query_metadata :
qt_plugin_query_metadata :
QImageReader::read :
QImageReader::read :
QImage::load :
QTextImageHandler::drawObject :
QTextImageHandler::drawObject :
QTextImageHandler::intrinsicSize :
QTextDocumentLayout::resizeInlineObject :
QTextEngine::shape :
QTextLine::layout_helper :
QTextLine::setLineWidth :
QTextDocumentLayout::idealWidth :
QTextDocumentLayout::layoutFinished :
QTextDocumentLayout::layoutFinished :
QTextDocumentLayout::layoutFinished :
QTextDocumentLayout::ensureLayouted :
QTextDocumentLayout::documentChanged :
QTextEdit::redoAvailable :
QWidget::event :
QFrame::event :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::sendPendingMoveAndResizeEvents :
QWidgetPrivate::show_helper :
QWidgetPrivate::setVisible :
QWidget::setVisible :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidgetPrivate::setVisible :
QWidget::setVisible :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidgetPrivate::setVisible :
QWidget::setVisible :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidgetPrivate::setVisible :
QWidget::setVisible :
QDialog::setVisible :
PyInit__gui :
PyInit_QtWidgets :
PyArg_ParseTuple_SizeT :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyFunction_Vectorcall :
PyFloat_FromDouble :
PyVectorcall_Call :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QObject::qt_static_metacall :
QAbstractItemView::doubleClicked :
QTreeView::mouseDoubleClickEvent :
PyInit__gui :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
PyInit__gui :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.20.1-Odense
QGIS code revision: 1c3c5cd6
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.1
Running against GDAL: 3.3.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

### Steps to reproduce the issue

1 - go to plug-in "visibility analysis"
2 - click on "create viewpoints"
3 - see error

### Versions

QGIS Version: 3.20.1-Odense

**Comment by nicogodet** [comment]
Not related to Qgis it self.
Reporte issue on plugin repo : https://github.com/zoran-cuckovic/QGIS-visibility-analysis/issues
