### ISSUE TITLE
InaSAFE 5.0.1 causes QGIS 3.20.1 to crash

### ISSUE THREAD

**Issue by haytastan** [qgis/QGIS#44515]
### What is the bug or the crash?

Sorry :( It looks something unexpected happened that we didn't handle and QGIS ended unexpectedly.

Keen to help us fix bugs? Follow the steps to help our developers.

You can also send us a helpful bug report using the Copy Report button 
and opening a ticket at QGIS Issue Tracker.

### Steps to reproduce the issue

**When I run the analysis for the Maumere.qgs project  of the plugin InaSafe 5.0.1 QGIS 3.20.1 crashes:**

**Crash ID:** 54189c0b3c28c1341092ac5f5c4e8a0e62dd5247 

**Stack Trace**

QgsField::QgsField :
QgsFields::operator[] :
QgsGdalLayerItem::setCrs :
QgsVectorLayerEditBuffer::commitChanges :
QgsVectorLayer::commitChanges :
PyInit__core :
PyArg_ParseTuple_SizeT :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyFunction_Vectorcall :
PyVectorcall_Call :
PyObject_Call :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyEval_EvalFrameDefault :
PyFunction_Vectorcall :
PyVectorcall_Call :
PyObject_Call :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyEval_EvalFrameDefault :
PyFunction_Vectorcall :
PyVectorcall_Call :
PyObject_Call :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyEval_EvalFrameDefault :
PyEval_EvalFrameDefault :
PyFunction_Vectorcall :
PyFloat_FromDouble :
PyVectorcall_Call :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QObject::qt_static_metacall :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
PyInit_QtWidgets :
QWidget::event :
PyInit_QtWidgets :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

**QGIS Info**
QGIS Version: 3.20.1-Odense
QGIS code revision: 1c3c5cd6
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.1
Running against GDAL: 3.3.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

### Versions

QGIS Version: 3.20.1-Odense
QGIS code revision: 1c3c5cd6
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.1
Running against GDAL: 3.3.1

### Additional context

**The Maumere project data ([Maumere.zip](https://github.com/qgis/QGIS/files/6916594/Maumere.zip)) are downloaded from**
 http://data.inasafe.org/TrainingDataPackages/Run%20Other%20Hazards.zip

**Comment by nicogodet** [comment]
Report this issue on plugin repo : https://github.com/inasafe/inasafe
