### ISSUE TITLE
Composer draw coordinates "format" is missing options

### ISSUE THREAD

**Issue by 016852902FREDY** [qgis/QGIS#44523]
### What is the bug or the crash?

In the composition tool "draw coordinates" it only shows decimal, decimal with suffix, the other options disappeared.

### Steps to reproduce the issue

Click draw coordinates.

In the composition tool "draw coordinates" it only shows decimal, decimal with suffix, the other options disappeared.

### Versions

3.20.1

### Additional context

In the composition tool "draw coordinates" it only shows decimal, decimal with suffix, the other options disappeared.

**Comment by 016852902FREDY** [comment]
![image](https://user-images.githubusercontent.com/86328327/127938505-09915345-1920-4093-a993-a59e0f5c1c30.png)

**Comment by gioman** [comment]
Seems true also on 3.16 and master on Windows, but on master/Linux is ok.

**Comment by rduivenvoorde** [comment]
@016852902FREDY just curious: is your screendump showing how it SHOULD be? Or is it NOT the proper way to show it?

What other options should be there? WIth me it looks like:

![Screenshot-20210803120305-404x169](https://user-images.githubusercontent.com/731673/127997757-81899879-7343-4639-b40f-50a82fa0de6d.png)

**Comment by gioman** [comment]
@rduivenvoorde 

![image](https://user-images.githubusercontent.com/1951107/127998106-bc863fd6-9a05-4213-8fe8-4ac7c1999f82.png)

that (missing) modes are also referred in QGIS 3.16 docs.

**Comment by rduivenvoorde** [comment]
@gioman in 3.16 it also shows just 3 items for me. I will have a look into the commits there, but don't you think that it maybe is deliberatly? That you can actually create everything by using the Custom option?

**Comment by nyalldawson** [comment]
You need to use a grid with a latitude/longitude based crs in order to see the degree unit options

**Comment by rduivenvoorde** [comment]
Ah :-) Thanks Nyall, that is more clear!
