### ISSUE TITLE
macOS versions and the download links are misleading

### ISSUE THREAD

**Issue by multiquadric** [qgis/QGIS#44526]
### What is the bug or the crash?

Using QGIS with macOS, there are prompts to install the last LTR or PR versions. However, the builds are (or were) failing such that the links for the most recent releases in fact fetch the last successful builds, respectively.

It looks like there were some threads closed in this regard. If macOS builds are behind, that's OK. Not great, but one can manage. A process that only prompts the use to download the latest successful builds would be useful.

### Steps to reproduce the issue

See:
https://qgis.org/downloads/macos/pr/?C=M;O=D
and
https://qgis.org/downloads/macos/ltr/?C=M;O=D

### Versions

3.16.8 prompts for an update to 3.16.9
3.20.0 prompt for an update to 3.20.1

**Comment by gioman** [comment]
@multiquadric same as https://github.com/qgis/QGIS-Mac-Packager/issues/136 ?

**Comment by multiquadric** [comment]
@gioman Yes. Issue shows close, but until the build shows up then maybe it should be open? The LTR version does not yet have an Aug 3rd build. The log for the Aug 2nd build, and all of those back to 3.16.8 show fatal errors on build.
https://qgis.org/downloads/macos/ltr/qgis_ltr_final-3_16_9_20210802_155040.log

Thanks

**Comment by agiudiceandrea** [comment]
@multiquadric  please wait until about tomorrow morning (CEST presumably) and check again as written in the comment https://github.com/qgis/QGIS-Mac-Packager/issues/136#issuecomment-891524053

**Comment by multiquadric** [comment]
@agiudiceandrea Still no macOS versions of the latest LTR and PR versions.
`curl -I https://qgis.org/downloads/macos/qgis-macos-ltr.dmg`
`curl -I https://qgis.org/downloads/macos/qgis-macos-pr.dmg`
I'm checking for a new file size rather than follow the d/l links and all.
Logs still show "fatal" errors.

Example:
% curl -s https://qgis.org/downloads/macos/ltr/qgis_ltr_final-3_16_9_20210803_153718.log | tail
/Library/Developer/CommandLineTools/usr/bin/install_name_tool: warning: changes being made to the file will invalidate the code signature in: /Users/admin/qgis/builds/ltr/bundle/QGIS-LTR.app/Contents/PlugIns/crypto/libqca-ossl.dylib
/Library/Developer/CommandLineTools/usr/bin/install_name_tool: warning: changes being made to the file will invalidate the code signature in: /Users/admin/qgis/builds/ltr/bundle/QGIS-LTR.app/Contents/PlugIns/crypto/libqca-softstore.dylib
/Library/Developer/CommandLineTools/usr/bin/install_name_tool: warning: changes being made to the file will invalidate the code signature in: /Users/admin/qgis/builds/ltr/bundle/QGIS-LTR.app/Contents/PlugIns/crypto/libqca-ossl.dylib
/Library/Developer/CommandLineTools/usr/bin/install_name_tool: warning: changes being made to the file will invalidate the code signature in: /Users/admin/qgis/builds/ltr/bundle/QGIS-LTR.app/Contents/PlugIns/crypto/libqca-ossl.dylib
Call fix_binaries_qca_check
Call fix_paths_qca
Call fix_paths_qca_check
Call fix_binaries_qgis
Missing /Users/admin/qgis/builds/ltr/bundle/QGIS-LTR.app/Contents/PlugIns/qgis/libprovider_oracle.so (install_name_change)
FAIL


Thanks for reading.

**Comment by PeterPetrik** [comment]
The macOS packages are ready for use:

Point Release (PR) 3.20.1
https://qgis.org/downloads/macos/pr/qgis_pr_final-3_20_1_20210805_162007.dmg

Long Term Release (LTR) 3.16.9
https://qgis.org/downloads/macos/ltr/qgis_ltr_final-3_16_9_20210806_022813.dmg

and Nightly 3.21.0
https://qgis.org/downloads/macos/nightly/qgis_nightly_master_20210805_123338.dmg
