### ISSUE TITLE
QGIS crash when trying to edit a shapefile

### ISSUE THREAD

**Issue by emortensen92** [qgis/QGIS#44539]
## User Feedback

My QGIS keeps encountering an error when I try to delete vertices from features of a shapefile and unexpectedly ends.

## Report Details

**Crash ID**: [cbbdf4dc1d1c76df53148e01cc03c42d5832a57c](https://github.com/qgis/QGIS/search?q=cbbdf4dc1d1c76df53148e01cc03c42d5832a57c&type=Issues)

**Stack Trace**
<pre>
QgsGeometryValidator::checkRingIntersections :
QgsGeometryValidator::validatePolygon :
QgsGeometryValidator::run :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.16.0-Hannover
QGIS code revision: 43b64b13f3
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

### Steps to reproduce the issue

Toggle editing.
Vertex tool.
Click vertex.
Delete key.
Crash.

### Versions

Hannover 3.16

**Comment by gioman** [comment]
>  QGIS Version: 3.16.0-Hannover

@emortensen92 way to old. Update to the latest 3.16 release. If the problem persist try a new QGIS profile, no 3rd party plugins installed. If the problem persist attach the problematic data.
