### ISSUE TITLE
Bug/Crash about "QGIS unexpectedly ended"

### ISSUE THREAD

**Issue by zyandysta** [qgis/QGIS#44534]
### What is the bug or the crash?

i've found crash like this. i really need help to solve this problem. please email me zyandysta@gmail.com
thank you.

Crash ID: df26706e2d3fa3d46294ebedd865f67c86c29d7d

Stack Trace

QgsField::convertCompatible qgsfield.cpp:383
QgsMemoryProvider::changeAttributeValues qgsmemoryprovider.cpp:626
QgsVectorLayerEditBuffer::commitChanges qgsvectorlayereditbuffer.cpp:542
QgsVectorLayer::commitChanges qgsvectorlayer.cpp:3404
meth_QgsVectorLayer_commitChanges sip_corepart10.cpp:117856
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyFunction_FastCallDict :
PyException_SetTraceback :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyException_SetTraceback :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyException_SetTraceback :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1637
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.16.9-Hannover
QGIS code revision: 9f8d2f7942
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

Some pict of errors in here 
<img width="323" alt="Error 1" src="https://user-images.githubusercontent.com/87923401/127980434-f9502f38-0844-42ed-934c-48859f49e8e4.PNG">
<img width="944" alt="Error 2" src="https://user-images.githubusercontent.com/87923401/127980437-62f5ad23-0b73-4a34-a8a5-3a4fb7985fa8.PNG">
<img width="946" alt="Error 3" src="https://user-images.githubusercontent.com/87923401/127980441-472ccb62-fdc5-4089-a8af-5597ac777428.PNG">
<img width="945" alt="Error 4" src="https://user-images.githubusercontent.com/87923401/127980443-59a22d1a-97fa-4ed4-867d-1c45b5cf7dd6.PNG">

Thank you so much for helping..

### Steps to reproduce the issue

<img width="323" alt="Error 1" src="https://user-images.githubusercontent.com/87923401/127980969-09027dd3-280e-49f6-b417-73b5a158c003.PNG">

<img width="944" alt="Error 2" src="https://user-images.githubusercontent.com/87923401/127980975-2b93b0a5-75ae-4ff2-aed5-4e1570d952b9.PNG">

<img width="946" alt="Error 3" src="https://user-images.githubusercontent.com/87923401/127980979-dfcc71f1-aea8-4b20-bc29-99321123d5b5.PNG">

<img width="945" alt="Error 4" src="https://user-images.githubusercontent.com/87923401/127980987-75159fde-a0c8-44c3-ae8d-2ae011bf480a.PNG">

### Versions

QGIS Info
QGIS Version: 3.16.9-Hannover
QGIS code revision: 9f8d2f7942
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

### Additional context

Email me zyandysta@gmail.com

**Comment by gioman** [comment]
@zyandysta you must report the problem in the InaSafe tracker, not here.
