### ISSUE TITLE
Missing signals in Picture layout item

### ISSUE THREAD

**Issue by nicogodet** [qgis/QGIS#44532]
### What is the bug or the crash?

![Animation](https://user-images.githubusercontent.com/39594821/127969443-8fdb3323-6f4f-4445-8d21-e851bfeb1494.gif)

Regression from 3.18.3

3.20.0 was buggy too but received a patch (https://github.com/qgis/QGIS/pull/43805)

### Steps to reproduce the issue

1. See gif

### Versions

QGIS 3.20.1 OsGeo4W v2

**Comment by nicogodet** [comment]
Not completely fixed.

@nyalldawson you fixed the path issue but my gif shows another issue :
Switch from raster to svg panel signal is missing 
On my GIF, "Flèche du Nord" is SVG, and "Logo" and "Logo client" are raster. As you can see, it does not switch from svg to raster or vice-versa.

**Comment by nicogodet** [comment]
I just compile Qgis with your fix

**Comment by nicogodet** [comment]
![Animation](https://user-images.githubusercontent.com/39594821/129683732-5c08786a-b1db-4edf-bf98-6903b17d5409.gif)

**Comment by gioman** [comment]
> Not completely fixed.

@nicogodet better reopen this?

**Comment by nicogodet** [comment]
@gioman yes or I can create a new issue.

**Comment by gioman** [comment]
> @gioman yes or I can create a new issue.

@nicogodet choose what you think is best.

**Comment by nicogodet** [comment]
@gioman please re-open.
