### ISSUE TITLE
Loading project file runs into crash

### ISSUE THREAD

**Issue by Ergerbolt** [qgis/QGIS#44542]
### What is the bug or the crash?

When i load my project, which i saved with qgis 3.18, qgis runs into a full crash. 
The project file contains data saved in mysql database and shapefiles, which are saved on a nas. 

### Steps to reproduce the issue

-

### Versions

3.20.1

### Additional context

**Crash ID**: [decc32c92cc4e4cbe5a6370711faa794aaf07eea](https://github.com/qgis/QGIS/search?q=decc32c92cc4e4cbe5a6370711faa794aaf07eea&type=Issues)

**Stack Trace**
<pre>
OGRGeometryFactory::createFromWkb :
OGRGeometryFactory::createFromWkb :
S57GenerateDSIDFeatureDefn :
QgsOgrProviderUtils::expandAuthConfig :
QgsVectorLayer::extent :
QgsMapLayerUtils::combinedExtent :
QgsProjectViewSettings::fullExtent :
QgsMapCanvas::projectExtent :
QgsMapOverviewCanvas::updateFullExtent :
QgsMapOverviewCanvas::setLayers :
QgsLayerTreeMapCanvasBridge::setCanvasLayers :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QgsRasterLayer::setDataProvider :
QgsRasterLayer::readXml :
QgsMapLayer::readLayerXml :
QgsProject::addLayer :
QgsProject::_getMapLayers :
QgsProject::readProjectFile :
QgsProject::unzip :
QgsProject::read :
QgisApp::addProject :
QgisApp::fileOpen :
QObject::qt_static_metacall :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.20.1-Odense
QGIS code revision: 1c3c5cd6
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.1
Running against GDAL: 3.3.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by PeterPetrik** [comment]
Hi @Ergerbolt and thanks for bug report. 
- Can you please try to remove layers from your project until you have the QGIS project with only 1 (few) layers that still crashes. 
- Once you have it, can you also move the data from NAS to local drive and verify it still crashes or not? 
- If it crashes even with local files, can you please submit here the QGIS project and data, so we can reproduce the crash and debug it? 
Thanks!
