### ISSUE TITLE
Crash when adding Esri World Imagery via REST

### ISSUE THREAD

**Issue by maphew** [qgis/QGIS#44547]
## User Feedback

Attempted to load "Esri World Imagery" using ArcGIS Server connector, had selected "Low resolution - 15m" raster layer.  ... Project csrs is EPSG:3579. It has 2 layers pre-loaded: waypoints and tracks in a geopackage that had been translated from GPX, still in WGS84 csrs.

## Report Details

**Crash ID**: [951e3255ce8b764ba89ab45f3a19357aa25bd8cf](https://github.com/qgis/QGIS/search?q=951e3255ce8b764ba89ab45f3a19357aa25bd8cf&type=Issues)

**Stack Trace**
<pre>
QgsAnnotation::appearanceChanged :
QgsCoordinateTransform::transformPolygon :
proj_list_operations :
proj_log_error :
proj_list_ellps :
proj_list_ellps :
proj_trans :
pj_phi2 :
proj_list_ellps :
proj_trans :
proj_trans_generic :
QgsCoordinateTransform::transformCoords :
QgsCoordinateTransform::transformBoundingBox :
QgsMapLayerUtils::combinedExtent :
QgsProjectViewSettings::fullExtent :
QgsMapCanvas::projectExtent :
QgsMapOverviewCanvas::updateFullExtent :
QgsMapOverviewCanvas::setLayers :
QgsLayerTreeMapCanvasBridge::setCanvasLayers :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.20.1-Odense
QGIS code revision: 1c3c5cd6
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.1
Running against GDAL: 3.3.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042
@

### Steps to reproduce the issue

1. Open project, last saved in Qgis v3.18.x
2.  Add  layer >> arcgis rest server >> Esri World Imagery (https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer)
3. Connect >> select: Low Resolution 15m Imagery raster
4. CRASH
5. Copy Report
6. Press Reload QGIS button --> crash dialog disappears, Qgis does not reload.

Problem is reproducible. If project csrs is set to WGS84 the crash doesn't happen.

### Versions

v3.20.1

### Additional context

Project file at https://gist.github.com/maphew/c8ad2c98f5fc268470a0981b14921849

**Comment by maphew** [comment]
I'm about to go offline for 2 weeks, so won't be able to follow up until after Aug 15.

**Comment by gioman** [comment]
@maphew no crash here, QGIS master on Ubuntu 20.04.

**Comment by agiudiceandrea** [comment]
No crash using the linked project with QGIS 3.20.1 on Windows 10 (OSGeo4W) even changing the project CRS to EPSG:3579.

**Comment by maphew** [comment]
ok, closing until and unless more substantive info can be brought to bear.
