### ISSUE TITLE
crash when i save a script and use calculate fild

### ISSUE THREAD

**Issue by naddjmerezgui** [qgis/QGIS#44552]
### What is the bug or the crash?

hi i have a problem when i try to save my script qgis v3.2 it crash but save the script and I need to clause to reopen it (the script it work but i need but when i save it qgis crush), and when i add a script to toolbox he doesn't show in toolbox
i install qgis 2.18 first in E: hard drive after that i install 3.2 in I: ,i try install qgis 3.16 and it's the same problem 
this all report detile
Crash ID: a5beb9b6044428853b90e86937b64d93d0bc7efb

Stack Trace

QString::QString :
QgsExpression::functionIndex :
QgsExpression::isFunctionName :
PyInit__core :
PyArg_ParseTuple_SizeT :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyFunction_Vectorcall :
PyVectorcall_Call :
PyObject_Call :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyEval_EvalCodeWithName :
PyEval_EvalCodeEx :
PyEval_EvalCode :
PyEval_GetBuiltins :
PyEval_GetBuiltins :
PyObject_GetBuffer :
PyVectorcall_Call :
PyObject_Call :
PyObject_Call :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyFunction_Vectorcall :
PyEval_EvalFrameDefault :
PyEval_EvalFrameDefault :
PyFunction_Vectorcall :
PyEval_EvalFrameDefault :
PyFunction_Vectorcall :
PyFloat_FromDouble :
PyVectorcall_Call :
PyObject_Call :
PyInit__core :
QgsProcessingProvider::refreshAlgorithms :
PyInit__core :
PyArg_ParseTuple_SizeT :
PyEval_EvalFrameDefault :
PyFloat_FromDouble :
PyEval_EvalFrameDefault :
PyFunction_Vectorcall :
PyFloat_FromDouble :
PyVectorcall_Call :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QObject::qt_static_metacall :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.20.0-Odense
QGIS code revision: decaadbb31
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.0
Running against GDAL: 3.3.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

![Capture](https://user-images.githubusercontent.com/37450120/128103597-ff73db31-86d2-471a-af3d-a5fd26a915e5.PNG)

### Steps to reproduce the issue

idont know

### Versions

QGIS version
3.20.0-Odense
QGIS code revision
decaadbb31
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.0
PROJ version
8.0.1
EPSG Registry database version
v10.018 (2021-04-02)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
attributeBasedClustering
ClosestPoint
clusterpoints
DeepLearningTools
easy_processing_tool
myfiber
openlayers_plugin
pathfinder
path_sorting
QuickOSM
short_path
db_manager
MetaSearch
processing

**Comment by gioman** [comment]
> ### Steps to reproduce the issue
> 
> idont know

@naddjmerezgui we need at least a general idea of what is needed to do to replicate the issue. An in this specific case possibly it also would be needed to have the script you are trying to save.

**Comment by naddjmerezgui** [comment]
> > ### Steps to reproduce the issue
> > idont know
> 
> @naddjmerezgui we need at least a general idea of what is needed to do to replicate the issue. An in this specific case possibly it also would be needed to have the script you are trying to save.

I didn't understand what u mean But this what happen
hi i have a problem when i try to save my script qgis v3.2 it crash but save the script and I need to clause to reopen it (the script it work but i need but when i save it qgis crush), and when i add a script to toolbox he doesn't show in toolbox
i install qgis 2.18 first in E: hard drive after that i install 3.2 in I: ,i try install qgis 3.16 and it's the same problem

**Comment by roya0045** [comment]
If you want help with your script this isn't a qgis issue.

**Comment by naddjmerezgui** [comment]
> If you want help with your script this isn't a qgis issue.

No i want help withe qgis he crush when i save the script

**Comment by gioman** [comment]
> No i want help withe qgis he crush when i save the script

@naddjmerezgui then you must attach the script here and describe in a clear way the steps to follow that lead to the crash.

**Comment by naddjmerezgui** [comment]
https://user-images.githubusercontent.com/37450120/128522161-8b51b635-e2e9-412d-9448-54359cf63a76.mp4

this is the script and I upload a video descrip the problem 
# -*- coding: utf-8 -*-

"""
***************************************************************************
*                                                                         *
*   This program is free software; you can redistribute it and/or modify  *
*   it under the terms of the GNU General Public License as published by  *
*   the Free Software Foundation; either version 2 of the License, or     *
*   (at your option) any later version.                                   *
*                                                                         *
***************************************************************************
"""

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,
                        QgsField,
                       QgsFields,
                       QgsFeatureSink,
                       QgsFeature,
                       QgsFeatureSink,
                       QgsProcessingException,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink)
from qgis import processing
from PyQt5.QtCore import QCoreApplication, QVariant


class clusterandcentre(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    REGULAR_DOMAND = 'REGULAR_DOMAND'
    ADVANCED_DOMAND = 'ADVANCED_DOMAND'
    OUTPUT='OUTPUT'
    def tr(self, string):
        """
        Returns a translatable string with the self.tr() function.
        """
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return clusterandcentre()

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'clusterandcentre'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr('cluster')

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr('ftth')

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'ftth desing'

    def shortHelpString(self):
        """
        Returns a localised short helper string for the algorithm. This string
        should provide a basic description about what the algorithm does and the
        parameters and outputs associated with it..
        """
        return self.tr("cluster and centre by nomber of domand")

    def initAlgorithm(self, config=None):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # We add the input vector features source. It can have any kind of
        # geometry.
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.REGULAR_DOMAND,
                self.tr('reguler domand layer'),
                [QgsProcessing.TypeVectorAnyGeometry]
            )
        )
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.ADVANCED_DOMAND,
                self.tr('advaced domand layer'),
                [QgsProcessing.TypeVectorAnyGeometry]
            )
        )

        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('totale domand layer')
            )
        )
        
    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """

        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.
        regluer_domand = self.parameterAsSource(
            parameters,
            self.REGULAR_DOMAND,
            context
        )
        advanced_domand = self.parameterAsSource(
            parameters,
            self.ADVANCED_DOMAND,
            context
        )
        

        # If source was not found, throw an exception to indicate that the algorithm
        # encountered a fatal error. The exception text can be any string, but in this
        # case we use the pre-built invalidSourceError method to return a standard
        # helper text for when a source cannot be evaluated
        if regluer_domand is None:
            raise QgsProcessingException(self.invalidSourceError(parameters, self.INPUT))
        fields = QgsFields()
        fields.append(QgsField("domand Nember", QVariant.String))
        fields.append(QgsField("domand type", QVariant.String))
        fields.append(QgsField("domand", QVariant.Int))
        
        #   when i try to save qgis crush
        (sink, dest_id) = self.parameterAsSink(
            parameters,
            self.OUTPUT,
            context,
            fields,
            regluer_domand.wkbType(),
            regluer_domand.sourceCrs()
        )
        
        

        # Send some information to the user
        

        # If sink was not created, throw an exception to indicate that the algorithm
        # encountered a fatal error. The exception text can be any string, but in this
        # case we use the pre-built invalidSinkError method to return a standard
        # helper text for when a sink cannot be evaluated
        
       
        i=1
        
        for feat in regluer_domand.getFeatures():
            regular_feature =  QgsFeature()
            regular_feature.setGeometry(feat.geometry())
            
            regular_feature.setAttributes(['home '+str(i),'regular', 1])
            sink.addFeature(regular_feature, QgsFeatureSink.FastInsert)
            i=1+i
        feedback.pushInfo(str(regular_feature))
        for feat in advanced_domand.getFeatures():
            advanced_feature =  QgsFeature()
            
            advanced_feature.setGeometry(feat.geometry())
            advanced_feature.setAttributes(['home '+str(i),'advanced', 6])
            sink.addFeature(advanced_feature, QgsFeatureSink.FastInsert)
            i=1+i
        
        return {self.OUTPUT: dest_id}

**Comment by gioman** [comment]
> this is the script a

@naddjmerezgui can you attach it as a (zippped) file, thanks.

**Comment by naddjmerezgui** [comment]
> > this is the script a
> 
> @naddjmerezgui can you attach it as a (zippped) file, thanks.

[total domand layer.zip](https://github.com/qgis/QGIS/files/6946100/total.domand.layer.zip)
thank u sir for taking time to understand the problem 
the crush it happens to all script not only this

**Comment by gioman** [comment]
>  the crush it happens to all script not only this

@naddjmerezgui have you tried in a new QGIS profile?

**Comment by naddjmerezgui** [comment]
> > the crush it happens to all script not only this
> 
> @naddjmerezgui have you tried in a new QGIS profile?

thank you sir I try a new profile and it work I can save script and add them to the toolbox thank u very match
