### ISSUE TITLE
Can't unselect default value in QGIS Processing script

### ISSUE THREAD

**Issue by kadarivan** [qgis/QGIS#44554]
### What is the bug or the crash?

If I add default value parameter in QgsProcessingParameterFeatureSource in Processing script, I can't remove that parameter in runtime.
I can overwrite with other layer, but unselect (empty value) not working.

### Steps to reproduce the issue

1) open test project
2) start test script
![kép](https://user-images.githubusercontent.com/18245793/128159587-1906ba6d-1ed5-44c9-a2a0-624e85243905.png)

3) remove the 3rd  parameter (kerekpar, optional) 
![kép](https://user-images.githubusercontent.com/18245793/128159420-51387b4b-e66b-49f9-aa42-81ee6615d09f.png)

4) run the script
5) error: The script find the default value of kerekpar parameter
![kép](https://user-images.githubusercontent.com/18245793/128159356-e6a817cb-c10a-4d39-a03e-2ba35ad3bc33.png)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.16.9-Hannover | QGIS code revision | 9f8d2f7942
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | db_manager; MetaSearch; processing

</body></html>

**Comment by nicogodet** [comment]
If I understand well what's here : https://qgis.org/api/qgsprocessingparameters_8cpp_source.html#l00865
It takes the default value of parameter if choosen value is empty.
Not a bug but intended behavior I believe.

**Comment by kadarivan** [comment]
It's a default value for the QgsProcessingParameterFeatureSource, so when a script started, it selected by default.
But after I change it to something else, or leave it empty, the QgsProcessingParameters should get the new (empty or changed) value, as seen in the log screen Input parameters section.
The default parameter should not pass from QgsProcessingParameterFeatureSource to QgsProcessingParameters.

**Comment by nyalldawson** [comment]
@kadarivan 

It's actually an issue in your script.

This part:
```
kerekpar = self.parameterAsVectorLayer(
  parameters,
  self.KEREKPAR,
  context
)
```

should instead be
```
if parameters.get(self.KEREKPAR, None):
  kerekpar = self.parameterAsVectorLayer(
    parameters,
    self.KEREKPAR,
    context
  )
else:
  kerekpar = None
```

**Comment by kadarivan** [comment]
@nyalldawson 

I not agree with the concept, but thanks for your solution.
