### ISSUE TITLE
crashed and ended

### ISSUE THREAD

**Issue by m4umoller** [qgis/QGIS#44559]
### What is the bug or the crash?

Crash ID: 642d164200ed2036ef966144a41cef0dfe930eb6

Stack Trace

QMetaObject::disconnect :
QObject::disconnectImpl :
QgsVertexTool::setHighlightedVertices :
QgsVertexTool::deactivate :
QgsMapCanvas::setMapTool :
QgsPresetSchemeColorRamp::clone :
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.12.3-Bucure?ti
QGIS code revision: 8234261527
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.3

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

### Steps to reproduce the issue

digitazing using polygon draw complement

### Versions

a

### Additional context

a

**Comment by gioman** [comment]
> digitazing using polygon draw complement



>  QGIS Version: 3.12.3-Bucure?ti

@m4umoller too old, please try on the latest 3.16 or 3.20. Also try with a new QGIS profile, no 3rd party plugins installed. If the problem persist please detail all the steps necessary to replicate, and attach sample data if necessary.

**Comment by m4umoller** [comment]
Okthanks

Em qua, 4 de ago de 2021 12:33, Giovanni Manghi ***@***.***>
escreveu:
