### ISSUE TITLE
OGR error: Coordinates with non-finite values are not allowed

### ISSUE THREAD

**Issue by JoaoBarreiro** [qgis/QGIS#44561]
### What is the bug or the crash?

I am facing this error when trying to make a duplicate of a shapefile. It is very strange because just happens on a single layer. Already checked layer validity and everything is ok.

Storage ESRI Shapefile
Encoding windows-1252
Geometry Polygon (MultiPolygonZ)
Extent -8.2623853683471680,37.0835952758789063 : -8.2445211410522461,37.0973205566406250
Feature count 97,295
And the CRS is OGC:CRS84 - WGS 84 (CRS84)

Here is the error I get:
_Export to vector file failed.
Error: Feature write errors:
Feature creation error (OGR error: Coordinates with non-finite values are not allowed)
(...)
Feature creation error (OGR error: Coordinates with non-finite values are not allowed)Stopping after 1001 errors_

### Steps to reproduce the issue

1. Right click on layer
2. Export > Save Feature As...
3. Fill the File Name with a new name (and path)
**4. Error when saving.**

### Versions

The current released version of QGIS is 3.20.1. 
We are working on 3.21-Master. It will go into feature freeze on 2021-09-10 12:00:00 UTC and be released as 3.22 on 2021-10-22 12:00:00 UTC. 
Details on changes can be found on github at https://github.com/qgis/QGIS/commits/master.

**Comment by gioman** [comment]
> * Right click on layer
> 
> * Export > Save Feature As...
> 
> * Fill the File Name with a new name (and path)
>   **4. Error when saving.**

@JoaoBarreiro please attach the layer.

**Comment by JoaoBarreiro** [comment]
> > * Right click on layer
> > * Export > Save Feature As...
> > * Fill the File Name with a new name (and path)
> >   **4. Error when saving.**
> 
> @JoaoBarreiro please attach the layer.

[_edificios_v2.zip](https://github.com/qgis/QGIS/files/6933962/_edificios_v2.zip)

**Comment by gioman** [comment]
> @gioman here it is
> [_edificios_v2.zip](https://github.com/qgis/QGIS/files/6933962/_edificios_v2.zip)

@JoaoBarreiro it works fine on QGIS master on Ubuntu 20.04 which ships with GDAL 3.0.1, but fails on QGIS 3.20 on Windows, which ships with a more recent GDAL release.

On Windows OGR2OGR fails with the same error
```

C:\Users\qgis\Desktop\_edificios_v2>ogr2ogr -f "ESRI Shapefile" test.shp HR_alb_DTM3_edificios_v2.shp
ERROR 6: Coordinates with non-finite values are not allowed
ERROR 1: Unable to write feature 0 from layer HR_alb_DTM3_edificios_v2.
ERROR 1: Terminating translation prematurely after failed
translation of layer HR_alb_DTM3_edificios_v2 (use -skipfailures to skip errors)
```

so if any seems to be an upstream issue, not QGIS's.

**Comment by JoaoBarreiro** [comment]
> > @gioman here it is
> > [_edificios_v2.zip](https://github.com/qgis/QGIS/files/6933962/_edificios_v2.zip)
> 
> @JoaoBarreiro it works fine on QGIS master on Ubuntu 20.04 which ships with GDAL 3.0.1, but fails on QGIS 3.20 on Windows, which ships with a more recent GDAL release.
> 
> On Windows OGR2OGR fails with the same error
> 
> ```
> 
> C:\Users\qgis\Desktop\_edificios_v2>ogr2ogr -f "ESRI Shapefile" test.shp HR_alb_DTM3_edificios_v2.shp
> ERROR 6: Coordinates with non-finite values are not allowed
> ERROR 1: Unable to write feature 0 from layer HR_alb_DTM3_edificios_v2.
> ERROR 1: Terminating translation prematurely after failed
> translation of layer HR_alb_DTM3_edificios_v2 (use -skipfailures to skip errors)
> ```
> 
> so if any seems to be an upstream issue, not QGIS's.

In that sense the solution is to use an older GDAL version (for now)? Any help on installing/using an older GDAL version?
Many thanks

**Comment by gioman** [comment]
> Any help on installing/using an older GDAL version?

@JoaoBarreiro you can try download and install an older Windows QGIS installer (as they ship with older GDAL versions), other than that only if you can compile code, or use a Linux machine.

**Comment by nyalldawson** [comment]
It's actually an issue with your data, not with gdal. You have some features with geometries which have "nan" values in vertices which need to be cleaned up

**Comment by JoaoBarreiro** [comment]
> It's actually an issue with your data, not with gdal. You have some features with geometries which have "nan" values in vertices which need to be cleaned up

What do you mean by vertices with "nan" values? How did you spot that, any help for solving?

**Comment by nyalldawson** [comment]
> How did you spot that, any help for solving?

One way is to copy the features and paste them into a text editor -- you'll be able to spot any features with geometries that contain "nan" values for vertices

**Comment by JoaoBarreiro** [comment]
> > How did you spot that, any help for solving?
> 
> One way is to copy the features and paste them into a text editor -- you'll be able to spot any features with geometries that contain "nan" values for vertices

Yes, I can see that now. But I have no idea what is the meaning of these "nan" and to solve the issue. Any tip?
Thanks

**Comment by JoaoBarreiro** [comment]
I've just seen that when importing the layer to QGIS, it is imported as MultiPolygonZ, but the layer has no Z associated. Any help on solving this? Many thanks!

**Comment by gioman** [comment]
> Yes, I can see that now. But I have no idea what is the meaning of these "nan" and to solve the issue. Any tip?

@JoaoBarreiro "fix geometries" in the processing toolbox seems to work.

**Comment by gioman** [comment]
> Any help on solving this?

@JoaoBarreiro do you want to drop Z?

**Comment by JoaoBarreiro** [comment]
> > Any help on solving this?
> 
> @JoaoBarreiro do you want to drop Z?

After "Fix geometries" I still get all those "nan" on Z. Yes, this shape has no Z associated...

**Comment by JoaoBarreiro** [comment]
> Any help on solving this?
> 
> @JoaoBarreiro do you want to drop Z?

Ok, finally solved the issue! Your "drop Z" hint solved it @gioman. I just used "Drop M/Z values" from toolbox and problem solved. I can export the shapefile now! Wow, many thanks for your support @gioman and @nyalldawson !

**Comment by gioman** [comment]
Cool!
