### ISSUE TITLE
Temporal controller logic wrong 

### ISSUE THREAD

**Issue by CoryAlbrecht** [qgis/QGIS#44589]
### What is the bug or the crash?

Temporal controller nor properly showing objects.

As you can see from the screencaps below, which has February 27th through March 1st, 1809 where there should be one feature, large Indiana territory getting replaced the next day by Illinois Territory and and smaller Indiana Territory.

The label for each feature is made from the `start_date` and `end_date` attributes the the temporal controller was set to use for the layer

`Current Frame: 1809-02-27 00:00:00 ≤ t < 1809-02-28 00:00:00`, correct, shows original Indiana territory feature
![image](https://user-images.githubusercontent.com/8172909/128427895-6b44a05f-d997-4df2-9b6b-4e9c7f87e679.png)

`Current Frame: 1809-02-28 00:00:00 ≤ t < 1809-03-01 00:00:00`, wrong, missing Indiana Territory feature
![image](https://user-images.githubusercontent.com/8172909/128427953-2b28e2ba-77c3-4065-86ba-8b219ae85bd6.png)

`Current Frame: 1809-03-01 00:00:00 ≤ t < 1809-03-02 00:00:00`, correct, displays new features
![image](https://user-images.githubusercontent.com/8172909/128428022-304e686e-9b19-451e-a858-5ab1963d7270.png)

### Steps to reproduce the issue

- create a layer with date-based start and end attributes
- add successive features where the start date of one is the the dat after the end date of another
- turn on "Dynamic Temporal Control" and choose "Separate Fields for Start and End Date/Time"
- set animation range step to 1.0 and the dropdown to "days"
- step through the animation

### Versions

QGIS version
3.20.1-Odense
QGIS code revision
1c3c5cd6
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.1
PROJ version
8.1.0
EPSG Registry database version
v10.018 (2021-04-02)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
MetaSearch
processing

**Comment by nyalldawson** [comment]
This is the expected result -- from the properties page:

![image](https://user-images.githubusercontent.com/1829991/128430608-05489265-10e6-4ac9-b593-c61c9b119123.png)

So the feature with time range of 1805/06/30 to 1809/02/28 is considered as occurring from 1805/06/30 <=t < 1809/02/28, and hence it won't show when the map is showing a range of 1809/02/28 -> ...

**Comment by nyalldawson** [comment]
(see extremely lengthy discussion at https://github.com/qgis/QGIS/pull/40989)

**Comment by CoryAlbrecht** [comment]
But that's not how people expect things to work.

If you say something existed from 1805/06/30 to 1809/02/28, then if you were to time travel to 1809/02/27 you would expect to see it there, Then jump to 1809/02/28, you'd still expect it to be there. Then, when you jump to 1809/03/01, you would expect that it is no longer there. "From X to Y" is inclusive of both points, not synonymous with "from X up until just before Y".

Or if you say that a conference lasts from August 1st to August 5th, you expect there to still be activities on the 5th not that it wrapped up the night before.

If you have a thermometer that you record at YYYY/MM/DD 00:00:00.000 every day and show that on the map as a filled circle with the colour representing the temperature, you'll be wanting to step through at 1 day per step, (not 1 millisecond) and you only want to show `YYYY/MM/DD 00:00:00.000 → YYYY/MM/DD 23:59:59.999` and not `YYYY/MM/DD 00:00:00.000 → YYYY/MM/DD+1 00:00:00.000` because that would mean there'd be two two coloured circles on the map.

With events like that, the `$X ≤ t < $Y` logic works because you're not really wanting `$timestart + $stepsize` but rather `$timeStart + $stepSize - $smallestTimeResolutionUnitPossible` because you have the concept of durations that can be shorter than your frame step size.

But if in your data your duration minimum is the same as your step size, the `$X ≤ t < $Y` logic does not work and gives you the erroneous gaps like I showed above.

Let's expand on that example of a conference by using the map of a conference centre with 4 conference halls. The halls are coloured when they are in use by a conference with a unique colour per conference and grey when unoccupied. Say hall A has one conference (assigned the colour blue) from August 1st to August 5th, then a second difference conference (assigned the colour green) from August 6th to August 9th. With the new logic in QGIS, as you step through day by day, hall A would show blue from the 1st to the 4th, grey on the 5th, green from the 6th to the 8th, and grey on the 9th again.

If that map were on a web site, somebody looking to book a one-day event in Hall A on the 5th would think it's available when it is not. Same thing goes for countries, provinces, states or other political divisions. If you say a territory lasted from 1805/06/30 to 1809/02/28, then when you draw the map for 1809/02/28 you had better see that territory on the map.

When you're dealing with dates and not times, the logic you want is  `$X ≤ t ≤ $Y` or you get this kind of error that QGIS is displaying.

This is a breaking change almost as bad as corrupting people's data.

**Comment by nyalldawson** [comment]
@CoryAlbrecht as you can see by the PR discussion this wasn't something someone changed on whim. Rather it came as the result of extremely lengthy discussions between a whole community of interested people, including experts in their fields like @anitagraser .

Sorry to put it this bluntly, but I'll take Anita's opinion over yours any day of the week.

**Comment by CoryAlbrecht** [comment]
@nyalldawson I read through all the discussion, and I feel that people missed an important use case. The assumption seems to be made that there can and will always be items with a duration of less than step size and unintentionally ignored a very common use case as indicated by the common phrasing "from the 1st to the 7th". 

To put it another way

`Separate Fields for Start and End Date/Time` or `from 2021/08/05 to 2021/08/06`

is not the same as

`Separate Fields for Start and Event Duration` as `2021/08/05 for 1 day`

but they are incorrectly treated the same way. The second one should be visible on only 2021/08/05, but the first one should be visible on 2021/08/05 and 2021/08/06 to align with common expectation.

**Comment by CoryAlbrecht** [comment]
Example illustrating the problem.
[test-temporal.zip](https://github.com/qgis/QGIS/files/6946520/test-temporal.zip)

**Comment by rduivenvoorde** [comment]
> "From X to Y" is inclusive of both points, not synonymous with "from X up until just before Y".

In my opinion your statement isn't right. If what you say would be true, the features on the frame-limits will always be shown twice:
in your case: in the frame: "from 1805/06/30 to 1809/02/28" you want to show '1809/02/28' AND in another frame, say "from 1809/02/82 to 1810/01/01" dito, just because you want to have both limits included in the filter (both as start and as end).

This raises questions about in which 'class' a feature/event should be placed when filtering your data: it would mean that there is actually an overlap in your classes. Though your use case maybe that is ok, but in other use cases, this raises side-effects. As an example: if you have data of exactly one hour length AND your step size is exactly one hour you will always show 2 features (instead of one).

I can understand that you *expect* it to behave different (party because as we speak about periodes we tent to be not very accurate...), but as soon as you accept the 'include start, not including end' model, all is ok, isn't it?

As said earlier, almost all other software cases try to create a filter on exact the same way: including the start, and NOT including the end.

A counter question: I had a look at your shapefiles (note that shapefiles actually do not have the notion of datetime (only date). If you would save the shapefiles to a geopackage (with actual date time column), and I would ask you to add a time (hour) part in your data: what would that be?  00:00 or 12:00 or something else?

**Comment by CoryAlbrecht** [comment]
@rduivenvoorde 

> In my opinion your statement isn't right.

What's not right about it? if I tell you that a convention goes from August 1st to the 7th, you expect to be able to show up on the 7th and find activities still happening, yes?

> If what you say would be true, the features on the frame-limits will always be shown twice:
in your case: in the frame: "from 1805/06/30 to 1809/02/28" you want to show '1809/02/28' AND in another frame, say "from 1809/02/82 to 1810/01/01" dito, just because you want to have both limits included in the filter (both as start and as end).

I'm not sure why you think things would show twice? 

I have a feature, as shown above, that has `start_date='1805/06/30'` and `end_date='1809/02/28'`, or, as one would say it to another person "from 1805/06/30 to 1809/02/28", and then two features who both have the same `start_date='1809/03/01'` and the same `end_date='1816/12/10'`. Again, in common parlance "from 1809/03/01 to 1816/12/10".

If my viewing timeframe is `'1809/02/28'`, I'm not sure why you think things would show twice? The first feature's time rage does not overlap with the second or third. If the time frame is set to `'1809/02/28'` you would only see the first feature, not the second and third, and when you increment the current frame by 1 day to `'1809/03/01'`, you would only see the second and third, not the first.

> I can understand that you expect it to behave different

TimeManager behaved differently. My data worked with it.

> (party because as we speak about periodes we tent to be not very accurate...),

Oh, no, they are accurate. Like saying that convention goes from the 1st to the 7th. Those are the date the convention is happening on.

What it is not is is _precise_, which is a different thing, and not not everything requires precision.

> but as soon as you accept the 'include start, not including end' model, all is ok, isn't it?

No, it is not.

It looks like you have (general you, not specific you) made the temporal controller take a date value and turn it in into a timestamp value by just slapping on "00:00:00.000", trying to increase the precision of that item.

I am mapping historical political divisions, and they get legislated in and out of existence on certain dates, or altered by treaties which take effect on certain dates. Not in and out of existence at specific timestamps. The law that broke off Illinois Territory went into effect on the day of March 1st, 1809. Not the timestamp value of `'1809/03/01 00:00:00.00'`, nor even the timestamp value of `'1809/03/01 12:00:00.000`. It went into effect on the date value of `'1809/03/01'` only. Therefore that previous version of Indiana Territory's last day was Februrary 28th, 1809. Not at the timestamp value `'1809/02/28 23:59:59.999'`. Nor at the timestamp value `'1809/03/01 11:59:59.999'`. It ended on `the date value of '1809/02/28'`.

When I started using temporal data for dynamic timeline maps back with QGIS 2.x and TimeManager, looking at the data I was storing, I chose to use 2 date columns in my PostGIS database because I didn't need finer time resolution that. And I chose to put the date of the first day a territory existed in the first date column (`start_date`) and the date of the last day it existed into the second date column (`end_date`), becaus ethat is what makes sense.

But now, you want a person creating a database like this to not put `start_date='1805/06/30'` and `end_date='1809/02/28'`, the actual first and last days of the territory, but rather `start_date='1805/06/30'` and `end_date='1809/02/28'`; but instead `start_date='1805/06/30'` and `end_date='1809/03/01'` with an end date the day after the actual, true last of the territory existed.

Does that not seem silly to you to have the end_date column for a feature be the day after it's ending day? Because then the column isn't what it's name says it is. Somebody would look at it and go "But It didn't end on 1809/0/01, it ended on 1809/02/28".

And why? Because you didn't see that when you have date-based data, merely tacking on a time of `'00:00:00.000'` to extend it to a timestamp and using the `≤ t <` logic does not work and erroneously does not show features on their last day of existence.

If you want to do to use that  `≤ t <` logic calculation with only timestamps, then you need to remember that with date-based data, only the the start date will be turned into `'YYYY/MM/DD 00:00:00.000'`. The end date really maps to a full timestamp of `'YYYY/MM/DD 23:59:59.999'` when you want to compare them as timestamps instead of dates.

Take that hypothetical convention again.

If it goes from 2021/08/01 to 2021/08/07, it has events on the 1st, the 2nd, the 3r, 4th, 5th, 6th, and 7th. All **7** of those days.

But if you convert that to going from 2021/08/01 00:00:00 to 2021/08/07 00:00:00 and use the `≤ t <` logic, then that's now only **6** days long, not **7**.

> A counter question: I had a look at your shapefiles (note that shapefiles actually do not have the notion of datetime (only date). If you would save the shapefiles to a geopackage (with actual date time column), and I would ask you to add a time (hour) part in your data: what would that be? 00:00 or 12:00 or something else?

I'm not using geopackages, though, so the question is irrelevant, but if for some bizarre reason I **had** to convert everything in my map data from the just-date-only columns I have in PostGIS¹ to format that only did timestamps, I certainly wouldn't just say to you 00:00 , because, as pointed out above, that seems to be what QGIS is doing and it causes this error (in concert with the `≤ t <` logic). I would choose to tack on `'000:00:00.000`' to the start date and `'23:59:59.999'` to the end date to deal with the way the QGIS temporal controller now handles things, because, as described above, of what date-based data _really_ means if you "translate" it into timestamps.

However, since I am not converting my data to a different storage format, I shouldn't have to change any of it.

When making these changes, did anybody test with date-based data to make sure that this assumption of merely tacking on `'00:00:00.000'` to bother start and end dates would work or produce issues like this one I opened here?

¹ Yes, I know, I used shape files in the example illustrating the logic problem. I didn't feel like dumping the entire project. SHP files sufficed to show the issue.

**Comment by nyalldawson** [comment]
@CoryAlbrecht 
looks like the only way to handle both use cases simultanesouly would be to add a new checkbox in the vector layer temporal properties tab for "end field is inclusive".

Contact me at info@north-road.com if you'd like to fund this feature and contribute to QGIS' usability for your particular requirements.

**Comment by CoryAlbrecht** [comment]
@rduivenvoorde 

Here's an interesting bug. I added a virtual column to the layer  called `duration` as `to_int(day(age("end_date", "start_date")) + 1)` and changed the Dynamic Temporal Control Configuration to:

![image](https://user-images.githubusercontent.com/8172909/128650808-feaf5a43-4caa-4827-88f6-e928ec339462.png)

I was intending just to kludge my way around how this temporal controller change broke things for me soI could get some work done, but now, in sequence, I get the following drawn on canvas

1. 1809/02/27
![image](https://user-images.githubusercontent.com/8172909/128650833-d76bf58b-e0c6-42a8-8d5d-0f18971d5927.png)

2. 1809/02/28
![image](https://user-images.githubusercontent.com/8172909/128650851-4a23feaf-0f53-4044-9441-9732a78df1ef.png)

3. 1809/03/01
4. 
![image](https://user-images.githubusercontent.com/8172909/128650866-287301ea-992f-4b28-87c4-810d89b7b82d.png)

Notice in Frame 2 for 1809/02/28 that the label for Indiana Territory appears twice, once with a from date of 1809/03/01 indicating two features being drawn. The label is drawn but the actual feature is hidden behind.

But by since the expression being evaluated is `1809/02/28 000:000:000 ≤ t < 1809/03/01/ 000:000:000`, that feature should not even be drawn because it does not overlap with `t`.

![image](https://user-images.githubusercontent.com/8172909/128651263-07f2af31-65b8-4164-96b0-5203d703e40d.png)

![image](https://user-images.githubusercontent.com/8172909/128651295-49ae59bb-00b4-4875-9146-0931047d2f5d.png)

So there appear to be multiple issues with the new view frame determination with the temporal controller.

**Comment by CoryAlbrecht** [comment]
@rduivenvoorde 

Exact same behaviour takes place when defining a virtual `new_end_date_fime` as `end_date + to_interval('1 day')` and leaving the DTC config as separate fields for start and end. Something's wrong with the feature selection logic when it's showing a feature not in the current time frame view.

**Comment by rduivenvoorde** [comment]
> What's not right about it? if I tell you that a convention goes from August 1st to the 7th, you expect to be able to show up on the 7th and find activities still happening, yes?

No, most software will NOT take the end limit into account. And that is what I mean if I say " we tent to be not very accurate": If I tell you that I worked from 8 to 5, you did not mean I worked till 5.59, I end at 5:00. That is how most people/software will use *those* limits. And that is the reason I really did my best to NOT include the end limit of timeframes.
It is as Nyall tell us: these are two different models, and your model (including the end limit of the timeframe when selecting features) really needs coding.

About 'showing up twice' (taking your model): if I have a convention going from 1 to (including) 10 aug 1900 and another one going from 10 to (including) 20 aug 1900, and I put the timestep length to 1 day (we always filter with a time range, never with an instantaneous time), and the time slider on 10 aug 00:00 1900, then i would have to show BOTH conventions, because the timeframe would 'overlap' both conventions. Taking a timestep of 2 days would have the same result if you let the slider start on 10 aug 00:00 1900.

BUT if that is what you want (in my working area: sensors and measurements that is not what you want), we have to add it to be able to handle both models.
Again: neither model is 'wrong', these are just 2 different models (and do not underestimate the complexity of the code to handle already one model and all the different possible timestamp/sizes, Nyall made it work, it almost broke my brain).

**Comment by rduivenvoorde** [comment]
> Why would this happen with virtual fields?

Not exactly sure what happens here, you really have to check which exact datetimes come out of your expressions (and if possible what they end up in the db).

Other things that did bite me a couple of times is that different dataproviders handle the final 'filter query' differently. Another thing is that QGIS is NOT aware of timezones, and (if I am corrent) uses your local time(time) to create timestamps. This can raise issues when your data defines other timezones (or UTC).
Could this be the case?

**Comment by CoryAlbrecht** [comment]
@rduivenvoorde 

> Not exactly sure what happens here, you really have to check which exact datetimes come out of your expressions (and if possible what they end up in the db).

That's the thing, though—`start_date` is not the field getting modified. We're talking about this

![image](https://user-images.githubusercontent.com/8172909/128738989-0f45b6d7-8790-426d-803a-38656a6c3f11.png)

versus this

![image](https://user-images.githubusercontent.com/8172909/128739043-3ec550c4-01d1-4cfc-9da8-28cefd00d705.png)

where `new_end_date` is `end_date + to_interval('1 day')` as mentioned above. The field `start_date` stays exactly the same in both cases.

And since the `start_date` field is **not** changing, therefore when stepping through with the the temporal controller, when that feature first shows up should not change, correct? It should show show up before it's `start-date`, correct?

**Comment by CoryAlbrecht** [comment]
> Other things that did bite me a couple of times is that different dataproviders handle the final 'filter query' differently. Another thing is that QGIS is NOT aware of timezones, and (if I am corrent) uses your local time(time) to create timestamps. This can raise issues when your data defines other timezones (or UTC).
Could this be the case?

Why would it be? The expression builder for virtual fields is running solely in QGIS after the feature data has been obtained, yes? Also, dates in PostgreSQL don't have timezones. So if it is a weird timezone screw up, then it's got to be inside QGIS when calculating the virual field, yes?

The temporal controller is trying to show `1809/02/28 00:00:00 ≤ t < 1809/03/01/ 00:0:00` which means that something with a  `start_date` of `'1809/03/01'` that gets extended to a timestamp of `'1809/03/01 00:00:00'` falls **outside** that range because it is **equal to** the end limit, not **less than** the end limit.

Further, when you got layer properties, attributes form, it correctly suggests the Date/Time widget:

![image](https://user-images.githubusercontent.com/8172909/128742268-f75a3a97-9cfd-45e3-9806-50bfffd4d073.png)

And in the Fileds panel is sees the new virtual field as a QDate:

![image](https://user-images.githubusercontent.com/8172909/128742401-a2c375b4-33b3-4fad-a9a8-729b52a49e27.png)

And the actual attributes form when displayed shows the expected dates:

![image](https://user-images.githubusercontent.com/8172909/128742646-3e7733d2-992e-4c46-a5fb-345d8b49e2b8.png)

Since you can chose what specific feature the expression builder uses to show you what your expression outputs, we can see that it outputs a `datetime` value.

![image](https://user-images.githubusercontent.com/8172909/128739565-df7a92f0-d372-4871-b0c6-cb4d2dcde5df.png)

I can further refine it and change it to `to_date("end_date" + to_interval('1 day'))` to make doubly sure that it's not a data incompatibility issue:

![image](https://user-images.githubusercontent.com/8172909/128743207-eb8b55aa-0018-4304-921e-bb39af1b9472.png)

However, that does not change the erroneous behaviour.

So, there does seem to be a problem when the temporal controller is working with virtual fields.

**Comment by CoryAlbrecht** [comment]
> About 'showing up twice' (taking your model): if I have a convention going from 1 to (including) 10 aug 1900 and another one going from 10 to (including) 20 aug 1900, and I put the timestep length to 1 day (we always filter with a time range, never with an instantaneous time), and the time slider on 10 aug 00:00 1900, then i would have to show BOTH conventions, because the timeframe would 'overlap' both conventions. Taking a timestep of 2 days would have the same result if you let the slider start on 10 aug 00:00 1900.

OK, I think I see what yo mean, now. Thank you for explaining.

If your first convention goes from August 1st, 1900  to the 10th, and the second one goes from the 10th to the 20th, and your temporal control view starts at August 10th, 1900 at midnight (and is a day long), then showing both of them is **exactly** what one would expect because you said they are both happening on August 10th.

The temporal controller appears to be assuming that **all** dates `'YYYY/MM/DD'` are equivalent to `'YYYY/MM/DD 00:00:00.000'` when converting to time stamps. However, as you've just illustrated here, when dealing with a a from-to/start-end date range that extension is only appropriate for the from/start field. For the to/end field, it should be extended to `'YYYY/MM/DD 23:59:59.999'`

**Comment by rduivenvoorde** [comment]
@CoryAlbrecht FYI: I'm going to try to add an option 'include end' in the Temporal Vector handling code, but don't hold your breath :-)

**Comment by CoryAlbrecht** [comment]
@rduivenvoorde I'm more than happy to help you test it, if you tell me the branch to clone and compile.

**Comment by rduivenvoorde** [comment]
> @rduivenvoorde I'm more than happy to help you test it, if you tell me the branch to clone and compile.

@CoryAlbrecht can you please try my latest version of the PR above?

if you go to the tests of the PR and click the windows build test you should come here: 
https://github.com/qgis/QGIS/pull/44674/checks?check_run_id=3409220790
there you can 'download artifacts' and run the compiled windows version (so no need to compile, unzip all and go to the bin directory and run qgis.exe; you are on Windows yes?)

![Screenshot-20210824115059-1351x1199](https://user-images.githubusercontent.com/731673/130596832-32faad77-8738-4d32-a957-9410e8be9113.png)

**Comment by CoryAlbrecht** [comment]
@rduivenvoorde I've switched from Windows 10 back to Ubuntu 20.04 LTS on my new laptop a couple of weeks ago. Can I check it with a Linux build?

**Comment by CoryAlbrecht** [comment]
@rduivenvoorde 
I cloned your branch and built it, but I don't see what I am supposed to change to go from  `≤ t <` to `≤ t ≤`? I don't notice any extra UI element to make the switch in the panel or in the layer properties tab?

**Comment by Gustry** [comment]
>  I don't notice any extra UI element to make the switch in the panel or in the layer properties tab?

CHeck his pull request description : https://github.com/qgis/QGIS/pull/44674

**Comment by rduivenvoorde** [comment]
@CoryAlbrecht yes, the idea is to NOT change the controllers timerange, but the feature's period (end limit).
So (see layer temporal props), you can (for given layer) tell QGIS that it's feature's event end should be included when tested against the temporal controllers timerange.
Also check the little test project (of which I created a newer in a later commit). You will see the difference between those layers.

In you specific case you should change the temporal properties of  your layers, and use the dropdown to set the 'Limits' to "Include start, Include end".

Let me know if you need more guidance.

**Comment by CoryAlbrecht** [comment]
I downloaded the artifacts from https://github.com/qgis/QGIS/pull/44674/checks?check_run_id=345444663 but I was not able to load my project from PostGIS. When I built from source according to the directions at https://github.com/qgis/QGIS/blob/master/INSTALL.md#3-building-on-gnulinux the resulting binary did not have the Limits drop-down shown at https://github.com/qgis/QGIS/pull/44674 .

![image](https://user-images.githubusercontent.com/8172909/131267475-c75d2c40-210c-41c7-9c59-401ae6950801.png)

**Comment by Gustry** [comment]
> When I built from source according to the directions at https://github.com/qgis/QGIS/blob/master/INSTALL.md#3-building-on-gnulinux the resulting binary did not have the Limits drop-down shown at #44674 .

Which commit are you running in Help -> About -> QGIS Code revision ?

**Comment by CoryAlbrecht** [comment]
@Gustry 
> Which commit are you running in Help -> About -> QGIS Code revision ?

9b6df0140b

I'll delete everything, reclone, and try again with @rduivenvoorde's `TemporalVectorsIncludeEndLimit` branch.

**Comment by CoryAlbrecht** [comment]
I  must have had the wrong branch. :-(

Anyways, @rduivenvoorde's fix works very nicely. :star2:

**Comment by rduivenvoorde** [comment]
Fixed by implementing the possibility to include the feature range end datetime in  #44674
