### ISSUE TITLE
Raster Layer Zonal Stats columns issue when raster has no CRS

### ISSUE THREAD

**Issue by jfbourdon** [qgis/QGIS#44584]
### What is the bug or the crash?

When a raster without any defined CRS is used, the second column normally used to store the area of each region is not always well defined (obviously...) which causes problem depending on the output format:

- **Temporary output**: the _area_ column name is not present thus all folowing column names are shift to the left and the values of the last column (mean) are lost.
- **CSV output**: correctly loaded with a placeholder _field_2_ in the second column for _area_. The file itself however miss the second column name (colnames stored as `zone,,sum,count,min,max,mean`).
- **GPKG output**: the _area_ column name is not present but this time it doesn't cause any shift, all values are where they should be.

### Steps to reproduce the issue

```python
from osgeo import gdal, osr
import numpy as np
import tempfile

tempdir = tempfile.gettempdir()

# Create raster without any CRS
array = np.array([[8, 8, 3, 3],
                  [7, 7, 3, 3],
                  [7, 4, 4, 4]])

raster_noCRS = os.path.join(tempdir, 'raster_no_CRS.tif')
driver = gdal.GetDriverByName('GTiff')
ds = driver.Create(raster_noCRS, xsize=4, ysize=3, bands=1, eType=gdal.GDT_Byte)
ds.GetRasterBand(1).WriteArray(array)
ds = None


# ---
# Run Raster Layer Zonal Stats tool
# with TEMPORARY output
params = {
    'INPUT':raster_noCRS,
    'BAND':1,
    'ZONES':raster_noCRS,
    'ZONES_BAND':1,
    'REF_LAYER':0,
    'OUTPUT_TABLE':'TEMPORARY_OUTPUT'}
table = processing.run("native:rasterlayerzonalstats", params)['OUTPUT_TABLE']

# Resulting column names and values of first feature
table.fields().names()
table.getFeature(1).attributes()
#  ['zone', 'sum', 'count', 'min', 'max', 'mean']
#  [   8.0,   2.0,      16,   2.0,   8.0,    8.0]
#  [   8.0,    16,     2.0,   8.0,   8.0,    8.0]   (expected)


# ---
# Run Raster Layer Zonal Stats tool
# with CSV output
stats_csv = os.path.join(tempdir, 'stats.csv')
params['OUTPUT_TABLE'] = stats_csv
table = processing.run("native:rasterlayerzonalstats", params)
table = QgsVectorLayer(stats_csv)

# Resulting column names and values of first feature
table.fields().names()
table.getFeature(1).attributes()
#  [      'zone',    'field_2',         'sum', 'count',        'min',        'max',       'mean']
#  ['8.00000000', '2.00000000', '16.00000000',     '2', '8.00000000', '8.00000000', '8.00000000']

# In plain text, the CSV looks like that
#  zone,,sum,count,min,max,mean
#  8.00000000,2.00000000,16.00000000,"2",8.00000000,8.00000000,8.00000000
#  4.00000000,3.00000000,12.00000000,"3",4.00000000,4.00000000,4.00000000
#  7.00000000,3.00000000,21.00000000,"3",7.00000000,7.00000000,7.00000000
#  3.00000000,4.00000000,12.00000000,"4",3.00000000,3.00000000,3.00000000


# ---
# Run Raster Layer Zonal Stats tool
# with GPKG output
stats_gpkg = os.path.join(tempdir, 'stats.gpkg')
params['OUTPUT_TABLE'] = stats_gpkg
processing.run("native:rasterlayerzonalstats", params)
table = QgsVectorLayer(stats_gpkg)

# Resulting column names and values of first feature
table.fields().names()
table.getFeature(1).attributes()
#  ['fid', 'zone', 'sum', 'count', 'min', 'max', 'mean']
#  [    1,    8.0,  16.0,       2,   8.0,   8.0,    8.0]
```

### Versions

QGIS version 3.20.0-Odense
QGIS code revision decaadb
Qt version 5.15.2
Python version 3.9.5
GDAL/OGR version 3.3.0
GEOS version 3.9.1-CAPI-1.14.2
Windows 10 Version 1809

**Comment by agiudiceandrea** [comment]
@jfbourdon how do you think the area column should be named if the layer has no valid CRS? Or do you think the are column shouldn't be added to the output table in this case?

**Comment by jfbourdon** [comment]
Humm… the name of the column with a projected CRS is `m2` and with a geographic CRS is `deg2`, so maybe just `unit2` if without a valid CRS? Maybe a more universal keyword like `area` should be used for all cases, that way the table will always be the same.

**Comment by nyalldawson** [comment]
> Maybe a more universal keyword like area should be used for all cases, that way the table will always be the same.

+1 to this. The problem is that we risk breaking plugins and scripts if we change now. So for now I'd say we should just use "area" as the generic name in the invalid CRS case...

**Comment by agiudiceandrea** [comment]
Anyway this reveals some inconsistencies/bugs:
- when the tool creates a memory table layer, the field with an empty name is not added to the layer
- when the tool creates a file based table layer (tested GPKG, CSV, SHP/DBF), the field with an empty name is added to the layer with an empty field name (is this expected?)
- when the layer containing a field with an empty name is added to the map, then:
  - GPKG: the field (and its values) is dropped and not displayed
  - CSV: the field is renamed "field_#" and is displayed with its values
  - SHP/DBF: the field is displayed with an empty name in th layer properties and as "Actions" in the attribute table

**Comment by gioman** [comment]
What would be the unit for a raster with missing CRS, the number of pixels?

**Comment by agiudiceandrea** [comment]
> What would be the unit for a raster with missing CRS, the number of pixels?

Yes, for a raster with missing CRS, the calculated "area" it's actually equal to the number of pixels.

**Comment by jfbourdon** [comment]
> What would be the unit for a raster with missing CRS, the number of pixels?

I forgot to mention that when working with FLT ([ESRI .hdr Labelled](https://gdal.org/drivers/raster/ehdr.html#raster-ehdr)) or BIL ([ENVI .hdr Labelled Raster](https://gdal.org/drivers/raster/envi.html)) style files, geotransform info is stored inside the .hdr auxiliary file and the CRS is in the .prj auxiliary file. That means even without the .prj file, the area can be calculated because the cellsize is available.

My example was with a TIF file, but I encountered the issue with a FLT file. Below is an example more similar to what I encountered. Cellsize is of 5 units and as the `zone` 8 has a `count` of 2, an `area` of 50 (2*5^2) is expected... and it's what we get.
```python
from osgeo import gdal
import numpy as np
import tempfile

tempdir = tempfile.gettempdir()

# Create raster without any CRS but a geotransform
array = np.array([[8, 8, 3, 3],
                  [7, 7, 3, 3],
                  [7, 4, 4, 4]])

raster_geotransform = os.path.join(tempdir, 'raster_geotransform.flt')
driver = gdal.GetDriverByName('EHdr')
ds = driver.Create(raster_geotransform, xsize=4, ysize=3, bands=1, eType=gdal.GDT_Byte)
ds.GetRasterBand(1).WriteArray(array)
ds.SetGeoTransform([55500, 5, 0, 22200, 0, -5])  # cellsize of 5 units
ds = None


# ---
# Run Raster Layer Zonal Stats tool
# with CSV output
stats_csv = os.path.join(tempdir, 'stats_geotransform.csv')
params = {
    'INPUT':raster_geotransform,
    'BAND':1,
    'ZONES':raster_geotransform,
    'ZONES_BAND':1,
    'REF_LAYER':0,
    'OUTPUT_TABLE':stats_csv}
processing.run("native:rasterlayerzonalstats", params)
table = QgsVectorLayer(stats_csv)

# Resulting column names and values of first feature
table.fields().names()
table.getFeature(1).attributes()
#  [      'zone',     'field_2',         'sum', 'count',        'min',        'max',       'mean']
#  ['8.00000000', '50.00000000', '16.00000000',     '2', '8.00000000', '8.00000000', '8.00000000']   (as expected)
```

However, if no geotransform is provided, I think the rows should be filled with `NA` instead of the same values as `count`. It may be simpler to straight fill the `area` column with `NA` as soon as a valid CRS is missing, regardless of any geotransform info.
