### ISSUE TITLE
crash qgis 3.16 hannover

### ISSUE THREAD

**Issue by mo-8** [qgis/QGIS#44582]
### What is the bug or the crash?

crashed when deleting a saved style

### Steps to reproduce the issue

1. go to style manager
2. select 'color ramp'
3. filter by 'all'
4. delete a color ramp
5. click 'close' (crashed on clicking close)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.16.8-Hannover | QGIS code revision | 8c50902ea4
-- | -- | -- | --
Compiled against Qt | 5.14.2 | Running against Qt | 5.14.2
Compiled against GDAL/OGR | 3.2.1 | Running against GDAL/OGR | 3.2.1
Compiled against GEOS | 3.9.1-CAPI-1.14.2 | Running against GEOS | 3.9.1-CAPI-1.14.2
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.4
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | macOS 10.15
Active python plugins | processing; db_manager; MetaSearch

</body></html>

**Comment by gioman** [comment]
Does it happen on a new QGIS profile?

**Comment by mo-8** [comment]
No I only have and use the default profile at the moment

**Comment by mo-8** [comment]
> No I only have and use the default profile at the moment

I started using QGIS 2 days ago for the first time

**Comment by gioman** [comment]
> No I only have and use the default profile at the moment

try settings > user profiles > new profile

**Comment by mo-8** [comment]
Will do. Thanks!
