### ISSUE TITLE
Couldn't save layer after editing

### ISSUE THREAD

**Issue by qgisdev** [qgis/QGIS#44592]
### What is the bug or the crash?

![Gis Errors](https://user-images.githubusercontent.com/88518612/128439880-fd9e04f3-c7e8-4b89-b83d-56b5148d7d7e.JPG)
![Gis Errors2](https://user-images.githubusercontent.com/88518612/128439882-5a0431a8-ec24-4dc6-95a5-3d335f8d3006.JPG)

### Steps to reproduce the issue

![Gis Errors](https://user-images.githubusercontent.com/88518612/128439921-2f301323-a031-4a71-b604-13cf9849a636.JPG)
![Gis Errors2](https://user-images.githubusercontent.com/88518612/128439924-4cf50aac-d4f8-428e-b59b-9679861f3333.JPG)

### Versions

QGIS Info
QGIS Version: 3.16.3-Hannover
QGIS code revision: 94ac9f21b8
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

### Additional context

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment]
>  QGIS Version: 3.16.3-Hannover

@qgisdev upgrade to the latest 3.16 release, try with a new QGIS profile (no 3rd party plugins installed) and if the problem persist add all the necessary infos to allow us try replicate the problem.
