### ISSUE TITLE
Add possibility for gradient fill to use complete geometry not only shown in canvas

### ISSUE THREAD

**Issue by antoniolocandro** [qgis/QGIS#44607]
### Feature description

It seems that for gradient fill the geometry used is what is clipped to the map canvas view, I think an option allowing users to set to canvas extent or layer would be beneficial. I think point pattern fill uses the complete geometry as I didn't see this behaviour. 

Video shows how the color changes a bit, I would leave current behaviour as default and add the other as an option

https://user-images.githubusercontent.com/4627073/128554802-3b03ad82-9cd4-4d0f-b099-7b2d8ee83182.mp4

**Comment by antoniolocandro** [comment]
There is an option present but it doesn't seem to work, I was expecting that when no clipping occurs then it doesn't matter if all the feature are visible in the map canvas but the color scheme shouldn't change

![image](https://user-images.githubusercontent.com/4627073/128566359-09d6078a-4319-4dd6-97e5-40123ab6316c.png)


https://user-images.githubusercontent.com/4627073/128567810-7c42a7a1-a696-4a42-a1a9-4843a3430770.mp4

**Comment by nyalldawson** [comment]
Do you have the gradient set to "viewport" mode? It should be "feature"

**Comment by antoniolocandro** [comment]
This is what I see 
![image](https://user-images.githubusercontent.com/4627073/128569455-c0dc58a7-9109-40ae-aecd-3adadf04a5f9.png)

BTW I am using the default gradient plasma

![image](https://user-images.githubusercontent.com/4627073/128569494-f5477908-32ac-4388-8953-6e017653fc6a.png)

**Comment by antoniolocandro** [comment]
Ha I figure it out! This can be closed but don't know how users can avoid this 

I was doing the changes at level 1 and they needed to be done at level 2

![image](https://user-images.githubusercontent.com/4627073/128569782-19690b36-00d9-4abb-8fa0-df349715bea8.png)

Thanks for helping out
