### ISSUE TITLE
Wrong shape for circles in WGS84 layer

### ISSUE THREAD

**Issue by sigmoe** [qgis/QGIS#44600]
### What is the bug or the crash?

When you draw a circle in WGS84 layer, the final shape drawn is not a circle.
It seems to be an old bug (same problem with QGIS 3.4, 3.10, 3.16).

### Steps to reproduce the issue

See my video attached.
Just draw a circle in a WGS84 layer.

https://user-images.githubusercontent.com/55922863/128487777-42e563cc-b567-4f62-8a9e-0a52373f2532.mp4

### Versions

Version de QGIS
3.16.8-Hannover
Révision du code
8c50902ea4
Compilé avec Qt
5.11.2
Utilisant Qt
5.11.2
Compilé avec GDAL/OGR
3.1.4
Utilisé avec GDAL/OGR
3.1.4
Compilé avec GEOS
3.8.1-CAPI-1.13.3
Utilisé avec GEOS
3.8.1-CAPI-1.13.3
Compilé avec SQLite
3.29.0
Fonctionne avec SQLite
3.29.0
Version du client PostgreSQL
11.5
Version de SpatiaLite
4.3.0
Version de QWT
6.1.3
Version de QScintilla2
2.10.8
Compilé avec PROJ
6.3.2
Fonctionne avec PROJ
Rel. 6.3.2, May 1st, 2020
Version de l'OS
Windows 10 (10.0)
Extensions Python actives
cadastre; 
localiserparcelle; 
SgmDxfImportPro; 
StreetView; 
db_manager; 
MetaSearch; 
processing

**Comment by gioman** [comment]
@sigmoe see:

https://github.com/qgis/QGIS/issues/38493
https://github.com/qgis/QGIS/issues/25167
https://github.com/qgis/QGIS/issues/38830

Closing as duplicate.
