### ISSUE TITLE
QGIS 3.20.1 unexpectedly ended due to InaSafe 5.0.1

### ISSUE THREAD

**Issue by haytastan** [qgis/QGIS#44601]
### What is the bug or the crash?

When I run the InaSAFE analysis, It looks something unexpected happened and QGIS ended unexpectedly.
Crash ID: 54189c0b3c28c1341092ac5f5c4e8a0e62dd5247

### Steps to reproduce the issue

When I run the InaSAFE analysis, It looks something unexpected happened and QGIS ended unexpectedly.

### Versions

QGIS Version: 3.20.1-Odense
QGIS code revision: 1c3c5cd6
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.1
Running against GDAL: 3.3.1

### Additional context

**Stack Trace**

QgsField::QgsField :
QgsFields::operator[] :
QgsGdalLayerItem::setCrs :
QgsVectorLayerEditBuffer::commitChanges :
QgsVectorLayer::commitChanges :
PyInit__core :
PyArg_ParseTuple_SizeT :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyFunction_Vectorcall :
PyVectorcall_Call :
PyObject_Call :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyEval_EvalFrameDefault :
PyFunction_Vectorcall :
PyVectorcall_Call :
PyObject_Call :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyEval_EvalFrameDefault :
PyFunction_Vectorcall :
PyVectorcall_Call :
PyObject_Call :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyEval_EvalFrameDefault :
PyEval_EvalFrameDefault :
PyFunction_Vectorcall :
PyFloat_FromDouble :
PyVectorcall_Call :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QObject::qt_static_metacall :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
PyInit_QtWidgets :
QWidget::event :
PyInit_QtWidgets :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

**Comment by nicogodet** [comment]
This issue is already reported on InaSafe plugin repo. Not a Qgis issue.

**Comment by Gustry** [comment]
@haytastan Please read the previous ticket you have opened.
https://github.com/qgis/QGIS/issues/44515

QGIS is not reponsible of InaSAFE plugin
