### ISSUE TITLE
Be able to use a gradient as Fill Color

### ISSUE THREAD

**Issue by antoniolocandro** [qgis/QGIS#44605]
### Feature description

Currently the only option is to use solid color, would like to be able to use a gradient at this point 

![image](https://user-images.githubusercontent.com/4627073/128553590-574300a2-e4c3-4bb9-b310-d3ac4e319f09.png)

Use case, I have repeating marker boxes that I want to apply the gradient to follow this tutorial in QGIS

https://www.youtube.com/watch?v=R__BJRn1x1w

**Comment by nyalldawson** [comment]
Try the "filled marker" symbol layer type -- that allows what you're after

**Comment by antoniolocandro** [comment]
The use of filled marker provides the gradient option indeed
