### ISSUE TITLE
HACapture Program Font scaling issue

### ISSUE THREAD

**Issue by DaniS2Tech** [qgis/QGIS#44620]
### What is the bug or the crash?

Font appears too large to read (200% scaling for monitor to work, multi monitor setup) on the HACapture program. Other font for File options appears much smaller.

Issue raised by myself, operating via an MSP, on behalf of a supported user.

![image](https://user-images.githubusercontent.com/88673006/128730416-e967a3cc-3082-4ab9-a662-88a802a0fc68.png)

### Steps to reproduce the issue

Open application with scaling at 200% on two monitor setup.

### Versions

QGIS 30.16

### Additional context

I am operating as an MSP helpdesk assistant, raising this issue on behalf of a supported user.

**Comment by gioman** [comment]
> HACapture

@DaniS2Tech is this a 3rd party plugin?

**Comment by DaniS2Tech** [comment]
> > HACapture
> 
> @DaniS2Tech is this a 3rd party plugin?

Thank you for your reply, I will contact the user.

**Comment by DaniS2Tech** [comment]
> > HACapture
> 
> @DaniS2Tech is this a 3rd party plugin?

Hello, yes, it is a plugin.

**Comment by gioman** [comment]
> Hello, yes, it is a plugin.

@DaniS2Tech then you must report the problem to the plugin author/s, not here.
