### ISSUE TITLE
qgis docker deployment image build not working

### ISSUE THREAD

**Issue by Jahn-KSB** [qgis/QGIS#44622]
### What is the bug or the crash?

Building the dockerfile from the docs is not working

failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/sh -c apt-get update     && apt-get install --no-install-recommends --no-install-suggests --allow-unauthenticated -y         gnupg         ca-certificates         wget          locales     && localedef -i en_US -f UTF-8 en_US.UTF-8     && wget -O - https://qgis.org/downloads/qgis-2021.gpg.key | gpg --import     && gpg --export --armor F7E06F06199EF2F2 | apt-key add -     && echo "deb http://qgis.org/debian buster main" >> /etc/apt/sources.list.d/qgis.list     && apt-get update     && apt-get install --no-install-recommends --no-install-suggests --allow-unauthenticated -y         qgis-server         spawn-fcgi         xauth         xvfb     && apt-get remove --purge -y         gnupg         wget     && rm -rf /var/lib/apt/lists/*]: runc did not terminate sucessful

### Steps to reproduce the issue

https://docs.qgis.org/3.16/en/docs/server_manual/containerized_deployment.html

check out the dockerfile, try to build it. I changed the key to the newest since it was added today... but now ot does not work at all  https://qgis.org/downloads/qgis-2021.gpg.key.

### Versions

thi is regarding the qgis-server

**Comment by agiudiceandrea** [comment]
@Jahn-KSB the new "QGIS Archive Automatic Signing Key" contained in https://qgis.org/downloads/qgis-2021.gpg.key has obviously a different fingerprint from the previous one.
The fingerprint of the new gpg key is `46B5721DBBD2996A` (not `F7E06F06199EF2F2`).
See https://qgis.org/en/site/forusers/alldownloads.html#repositories

**Comment by agiudiceandrea** [comment]
@Jahn-KSB if you managed to solve your issue, please report back and close this issue report.
