### ISSUE TITLE
QgsFeatureRequest().setNoAttributes() not working on memory layers

### ISSUE THREAD

**Issue by gacarrillor** [qgis/QGIS#44621]
### What is the bug or the crash?

To improve `QgsVectorLayer.getFeatures()` performance we should use a request and set some flags. A handy method to avoid retrieving field values is `setNoAttributes()`, but this method doesn't seem to work well with memory layers.

I'm using this code snippet:

```
layer = iface.activeLayer()
res = [f for f in layer.getFeatures(QgsFeatureRequest().setNoAttributes())]
print(res[0].attributes())
```

And I can see field values in the result when running on memory layers:

`['abc']`

### Steps to reproduce the issue

1. Create a memory layer with at least one field.
2. Add a feature to it and set a value for the field.
3. Run the code snippet given above in QGIS Python console.
4. See the string field value in the result (which should not be there).

### Versions

I've confirmed this behavior in 3 QGIS versions (3.14.0, 3.16.6, 3.20.0 and a master from 2-3 weeks ago).

**Comment by nyalldawson** [comment]
This is by design. The "no attributes" flag is designed to optimise feature requests in cases where skipping attributes saves time. But the memory provider actually returns only shallow copies of the features stored in memory, so clearing the attributes for these would result in **slower** requests 🙃

**Comment by gacarrillor** [comment]
Thanks for the explanation, I wasn't aware of that!

**Comment by gacarrillor** [comment]
@nyalldawson, do you think it makes sense to document this in the API (perhaps in `QgsFeatureRequest::setNoAttributes()`)?

**Comment by nyalldawson** [comment]
@gacarrillor see https://github.com/qgis/QGIS/pull/44816

**Comment by gacarrillor** [comment]
Nice, thanks!
