### ISSUE TITLE
Crash when clipping a larger layer with a small layer

### ISSUE THREAD

**Issue by tschmetzer** [qgis/QGIS#44635]
### What is the bug or the crash?

Qgis crashes after approx 10s when clipping a larger layer with a small overlay layer. Restarting Qgis or rebooting the computer doesn't help.

![grafik](https://user-images.githubusercontent.com/67278094/128853021-1ea4ad4d-3d58-4dec-8061-49c0e5c3c26c.png)

Input layer (Feature count: 2.923.688, CRS ESRI:54009 - World_Mollweide):
[GHS_SMOD_Polygonized_raster2vector.zip](https://drive.google.com/file/d/1QJqkm585TIgtG7J8skGN3nLj7E7SLELO/view?usp=sharing)

Overlay layer (Feature count: 1, CRS EPSG:4326 - WGS 84 ):
[smod_polygonized_raster2vector_smallMaskLayer.zip](https://github.com/qgis/QGIS/files/6960914/smod_polygonized_raster2vector_smallMaskLayer.zip)

### Steps to reproduce the issue

1. Import both layers into a new qgis project
2. processing tools -> clip
3. choose layers according to the screenshot
4. a crash occurs after several seconds

### Versions

QGIS version | 3.20.1-Odense | QGIS code revision | 1c3c5cd6
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.1
PROJ version | 8.1.0
EPSG Registry database version | v10.027 (2021-06-17)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins | GroupStatslatlontoolsnominatimQuickOSMdb_managerprocessing

**Comment by tschmetzer** [comment]
Thanks for the feedback. Same thing happened for me. Looks like I missed a final confirmation on google drive. Now i was able to receive a download link. 
@gioman Can you please try again?

**Comment by gioman** [comment]
>  @gioman Can you please try again?

@tschmetzer no change, is still not downloadable.

**Comment by nyalldawson** [comment]
I can get the first file, but not the overlay one... Same message as @gioman

**Comment by nyalldawson** [comment]
Sorry, that's the wrong way around. I can get the overlay, not the other layer

**Comment by nyalldawson** [comment]
It's set not to allow download:

![image](https://user-images.githubusercontent.com/1829991/128948437-5f2c947d-3c40-4ab8-9630-d5bd5c23a832.png)

**Comment by tschmetzer** [comment]
Sorry and thanks for the feedback. Looks like I overlooked another permission option. Now it should work. I already tested with a colleague. 
Can you please try again?

**Comment by gioman** [comment]
>  Can you please try again?

@tschmetzer also crash here on master/linux. By the way, the input layer has a gazillion of invalid geometries, and my processing is set to skip them by default. You may want to fix those geometries first and see if the crash comes from there.

**Comment by tschmetzer** [comment]
I'm a bit confused as this layer is an output from a raster processing algorithm. Shouldn't that algorithm produce correct layers?

I may need a couple of weeks until I will be able to spend time on this topic as I need to focus on other priorities for now. Hope it's fine to put this topic on hold until then if my feedback is required :)

**Comment by nyalldawson** [comment]
I think it's actually this libgeos bug https://trac.osgeo.org/geos/ticket/1116 (fixed upstream already). When the invalid geometry is detected that bug is causing geos to dump a MASSIVE wkt string of the polygon out to the debugging logs. It took many minutes on my machine doing this with no end in sight (so I killed the process).

So my suspicion is that QGIS hasn't actually crashed, it's just "not responding" while geos dumps this massive (unwanted) debugging output. 

Solution here is to get an updated version of geos in the installer. A workaround is to repair the geometries using the "fix geometries" tool. 


> I'm a bit confused as this layer is an output from a raster processing algorithm. Shouldn't that algorithm produce correct layers?

I assume by the file names that you used "Polygonize (raster to vector)" to create this. If so, I'd ask upstream on a gdal library ticket whether there's anything which can be done to improve this.

**Comment by gioman** [comment]
As both issues are upstream can we close this?

> Solution here is to get an updated version of geos in the installer

@nyalldawson should be file a ticket on the psgeo4w tracker? what is the GEOS release that includes the fix?

**Comment by nyalldawson** [comment]
@gioman we'll need to wait till the 3.9.2 release -- the fix isn't in a stable geos release yet

**Comment by tschmetzer** [comment]
Do I guess correctly that this ticket should remain open?
@gioman Is there any feedback required from me? If not would you mind removing the feedback label and reopen the ticket?

**Comment by gioman** [comment]
> Do I guess correctly that this ticket should remain open?

@tschmetzer if it is an upstream issue there is no point in keeping it open here, this is how normally we do, see for example https://github.com/qgis/QGIS/issues/44656#issuecomment-927382351

**Comment by tschmetzer** [comment]
> @gioman we'll need to wait till the 3.9.2 release -- the fix isn't in a stable geos release yet

I thought Nyall's answer was referring to your question if this ticket can be closed and I understood we need to wait till the next geos release which isn't available yet. That's why I asked. I didn't mean to question your processes though.
