### ISSUE TITLE
crssync.exe: Process entry point  'clCreateCommandQueueWithProperties'  not found in DLL 'qgis_core.dll'

### ISSUE THREAD

**Issue by tschmetzer** [qgis/QGIS#44639]
### What is the bug or the crash?

During the installation's execution of crssync.exe an error pops up: 
`Process entry point  'clCreateCommandQueueWithProperties'  not found in DLL 'qgis_core.dll'`
![image](https://user-images.githubusercontent.com/67278094/128907068-68b61520-2f67-4cf0-a9f9-28a47e27c222.png)

The installation routine reports success anyways:
![image](https://user-images.githubusercontent.com/67278094/128908065-29814c96-08a3-4ce8-9104-1cdc2ed2f4f8.png)

Manual execution of crssync.exe after install provides the same result:
![qgis_installation_error](https://user-images.githubusercontent.com/67278094/128898761-4346a5e3-a0b2-4380-a60a-b570829c8cf4.PNG)

When checking the $PATH$ Environment variables everything seems correct:
```
C:\OSGeo4W>OSGeo4W.bat
run o-help for a list of available commands
C:\OSGeo4W>set
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\SchmetzerT\AppData\Roaming
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=NORA
ComSpec=C:\WINDOWS\system32\cmd.exe
DellClientSystemUpdatePath=C:\Program Files (x86)\Dell\ClientSystemUpdate\
DriverData=C:\Windows\System32\Drivers\DriverData
EmpirumServer=EMPIRUM1.local.zae-bayern.de
FP_NO_HOST_CHECK=NO
GDAL_DATA=C:\OSGeo4W\share\gdal
GDAL_DRIVER_PATH=C:\OSGeo4W\bin\gdalplugins
HOMEDRIVE=C:
HOMEPATH=\Users\SchmetzerT
JPEGMEM=1000000
LOCALAPPDATA=C:\Users\SchmetzerT\AppData\Local
LOGONSERVER=\\DC1
NUMBER_OF_PROCESSORS=4
O4W_QT_BINARIES=C:/OSGeo4W/apps/Qt5/bin
O4W_QT_DOC=C:/OSGeo4W/apps/Qt5/doc
O4W_QT_HEADERS=C:/OSGeo4W/apps/Qt5/include
O4W_QT_LIBRARIES=C:/OSGeo4W/apps/Qt5/lib
O4W_QT_PLUGINS=C:/OSGeo4W/apps/Qt5/plugins
O4W_QT_PREFIX=C:/OSGeo4W/apps/Qt5
O4W_QT_TRANSLATIONS=C:/OSGeo4W/apps/Qt5/translations
OneDrive=C:\Users\SchmetzerT\OneDrive
OPENSSL_ENGINES=C:\OSGeo4W\lib\engines-1_1
OS=Windows_NT
OSGEO4W_ROOT=C:\OSGeo4W
Path=C:\OSGeo4W\apps\qt5\bin;C:\OSGeo4W\apps\Python39\Scripts;C:\OSGeo4W\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\system32\WBem
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=3a09
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROJ_LIB=C:\OSGeo4W\share\proj
PROMPT=$P$G
PSModulePath=C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\
PUBLIC=C:\Users\Public
PYTHONHOME=C:\OSGeo4W\apps\Python39
PYTHONUTF8=1
QT_PLUGIN_PATH=C:\OSGeo4W\apps\Qt5\plugins
SESSIONNAME=Console
SystemDrive=C:
SystemRoot=C:\WINDOWS
TEMP=C:\Users\SCHMET~1\AppData\Local\Temp
TMP=C:\Users\SCHMET~1\AppData\Local\Temp
USERDNSDOMAIN=LOCAL.ZAE-BAYERN.DE
USERDOMAIN=ZAE-BAYERN
USERDOMAIN_ROAMINGPROFILE=ZAE-BAYERN
USERNAME=schmetzert
USERPROFILE=C:\Users\SchmetzerT
windir=C:\WINDOWS
windows_tracing_flags=3
windows_tracing_logfile=C:\BVTBin\Tests\installpackage\csilogfile.log
```

There are more (probably follow up) errors when trying to execute QGIS afterwards. The error message when trying to start QGIS:
![image](https://user-images.githubusercontent.com/67278094/128908242-d8c192a3-d076-4437-82e7-ac62b0a83021.png)
![image](https://user-images.githubusercontent.com/67278094/128908334-2c1c44b3-b6bc-4522-a88e-6ae97282b2cc.png)

Installations on other computers with the same windows version (10.0.19043) this problem doesn't occur.

### Steps to reproduce the issue

Install QGis using Osgeo4w network installer v2 as described below:

- Express installation
- tested with download.osgeo.org and ftp. osuosl.org (www.norbit.de throws a bunch of other errors with missing files)
- accept all licenses
- install all packages except for LTR

Reinstall using the expert installation selecting all packages with the 'reinstall' option as well as deleting `C:\OSGeo4W` and `C:\Users\<Username>\AppData\Local\Temp\<downloaded install files>`  and doing a fresh install don't help.

### Versions

The Windows system information (sorry that it's in German):
![image](https://user-images.githubusercontent.com/67278094/128898198-ba559e44-f714-483b-938b-ad598aa4a573.png)

**Comment by gioman** [comment]
@tschmetzer just did an express install on a clean Win10 machine, no issues.

**Comment by gioman** [comment]
> Even later the same day I had a successful installation.

@tschmetzer reopen if you can replicate in a consistent way. 

> On the machine in question there was a QGIS 3.14 pi installation that I deinstalled beforehand. Could there be any leftover that causes this problem?

I have testing machines with where frequently I install and uninstall several QGIS versions, and never had issues.

**Comment by tschmetzer** [comment]
On that machine it's absolutely replicable. 
Yet I don't want to keep people busy because of a single event in a million installations.

**Comment by jef-n** [comment]
Reinstalling the opencl package might help.

**Comment by tschmetzer** [comment]
Indeed the root cause was an opencl.dll file that existed several times in various directories and apparently different versions. Once those were deleted and a new version available in the system QGIS worked!
