### ISSUE TITLE
QGIS repeatedly crashes when using measuring tool

### ISSUE THREAD

**Issue by NauticalNeil** [qgis/QGIS#44634]
## User Feedback

Used the measuring distance tool - repeatedly crashes

## Report Details

**Crash ID**: [5b8ebf2cb8a8bc83a3de8aff5739a2c643f0a74f](https://github.com/qgis/QGIS/search?q=5b8ebf2cb8a8bc83a3de8aff5739a2c643f0a74f&type=Issues)

**Stack Trace**
<pre>
QWidget::mapTo :
QWidgetPrivate::moveRect :
QApplication::windowIcon :
QApplication::windowIcon :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.16.3-Hannover
QGIS code revision: 94ac9f21b8
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

### Steps to reproduce the issue

Seems to happen regularly when using the measuring tool to measure a line (for example a length of river). Impossible to predict but does happen fairly regularly (5 times per week)

### Versions

QGIS version
3.16.3-Hannover
QGIS code revision
94ac9f21b8
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
dzetsaka; 
HCMGIS; 
ImportPhotos; 
latlontools; 
Mergin; 
QuickOSM; 
searchlayers; 
db_manager; 
MetaSearch; 
processing

**Comment by gioman** [comment]
>  3.16.3-Hannover

@NauticalNeil too old, update to the latest point release and try with a new QGIS profile, no 3rd party plugins installed.

**Comment by NauticalNeil** [comment]
> ### What is the bug or the crash?
> ## User Feedback
> Used the measuring distance tool - repeatedly crashes
> 
> ## Report Details
> **Crash ID**: [5b8ebf2cb8a8bc83a3de8aff5739a2c643f0a74f](https://github.com/qgis/QGIS/search?q=5b8ebf2cb8a8bc83a3de8aff5739a2c643f0a74f&type=Issues)
> 
> **Stack Trace**
> 
> QWidget::mapTo :
> QWidgetPrivate::moveRect :
> QApplication::windowIcon :
> QApplication::windowIcon :
> QWidget::event :
> QApplicationPrivate::notify_helper :
> QApplication::notify :
> QgsApplication::notify :
> QCoreApplication::notifyInternal2 :
> QCoreApplicationPrivate::sendPostedEvents :
> qt_plugin_query_metadata :
> QEventDispatcherWin32::processEvents :
> UserCallWinProcCheckWow :
> DispatchMessageWorker :
> QEventDispatcherWin32::processEvents :
> qt_plugin_query_metadata :
> QEventLoop::exec :
> QCoreApplication::exec :
> main :
> BaseThreadInitThunk :
> RtlUserThreadStart :
> **QGIS Info**
> QGIS Version: 3.16.3-Hannover
> QGIS code revision: [94ac9f2](https://github.com/qgis/QGIS/commit/94ac9f21b8b7e36d3aa9715922ad15a7bf62fdae)
> Compiled against Qt: 5.11.2
> Running against Qt: 5.11.2
> Compiled against GDAL: 3.1.4
> Running against GDAL: 3.1.4
> 
> **System Info**
> CPU Type: x86_64
> Kernel Type: winnt
> Kernel Version: 10.0.19042
> 
> ### Steps to reproduce the issue
> Seems to happen regularly when using the measuring tool to measure a line (for example a length of river). Impossible to predict but does happen fairly regularly (5 times per week)
> 
> ### Versions
> QGIS version
> 3.16.3-Hannover
> QGIS code revision
> [94ac9f2](https://github.com/qgis/QGIS/commit/94ac9f21b8b7e36d3aa9715922ad15a7bf62fdae)
> Compiled against Qt
> 5.11.2
> Running against Qt
> 5.11.2
> Compiled against GDAL/OGR
> 3.1.4
> Running against GDAL/OGR
> 3.1.4
> Compiled against GEOS
> 3.8.1-CAPI-1.13.3
> Running against GEOS
> 3.8.1-CAPI-1.13.3
> Compiled against SQLite
> 3.29.0
> Running against SQLite
> 3.29.0
> PostgreSQL Client Version
> 11.5
> SpatiaLite Version
> 4.3.0
> QWT Version
> 6.1.3
> QScintilla2 Version
> 2.10.8
> Compiled against PROJ
> 6.3.2
> Running against PROJ
> Rel. 6.3.2, May 1st, 2020
> OS Version
> Windows 10 (10.0)
> Active python plugins
> dzetsaka;
> HCMGIS;
> ImportPhotos;
> latlontools;
> Mergin;
> QuickOSM;
> searchlayers;
> db_manager;
> MetaSearch;
> processing
> 
> ### Additional context
> _No response_

thanks @gioman - will update and test!

**Comment by NauticalNeil** [comment]
Is the latest LTR (3.16.9) ok?

**Comment by gioman** [comment]
> Is the latest LTR (3.16.9) ok?

@NauticalNeil yes, but do it with a new QGIS profile.

**Comment by hauke96** [comment]
Same problem here with QGIS 3.20.1 on Arch Linux. Creating a new profile fixes the problem but it's already enough to remove the `cache` folder inside the profile folder. For me that was `~/.local/share/QGIS/QGIS3/profiles/default/cache`.

I'm glad that this fix is quite easy but: The cache folder only consists of empty sub folders and one of the sub folder again contains empty subfolders:
```
cache/                                                                         
| data8/                                                                        
| | 0/                                                                          
| | 1/                                                                          
| | 2/                                                                          
| | 3/                                                                          
| | 4/                                                                          
| | 5/                                                                          
| | 6/                                                                          
| | 7/                                                                          
| | 8/                                                                          
| | 9/                                                                          
| | a/                                                                          
| | b/                                                                          
| | c/                                                                          
| | d/                                                                          
| | e/                                                                          
| | f/                                                                          
| prepared/
```
All those folders are empty, quite old (from January 11th 2021), have normal permissions (755 on all the folder) and are owned by the user I start QGIS with. As far as I know QGIS has no error log file or something (please correct me if I'm wrong) and I also found nothing on dmesg, journald or any other logs on my system.

**Comment by hauke96** [comment]
I'm using QGIS 3.20.1 on arch linux and I have the same problem: QGIS crashes when I click the measure tool button. Creating a new profile doesn't really help. Here's what I experience:

1. Open QGIS 
2. Create new profile "test". New QGIS window opens.
3. Measuring tool button works in this new profile
4. Close all QGIS windows
5. Open QGIS again. This time "test" is directly the profile QGIS starts with.
6. Click measuring button
7. QGIS crashes even though my new profile "test" is the active profile

So yes, creating a new profile works but only until I close QGIS.

**Comment by gioman** [comment]
> * Open QGIS
> 
> * Create new profile "test". New QGIS window opens.
> 
> * Measuring tool button works in this new profile
> 
> * Close all QGIS windows
> 
> * Open QGIS again. This time "test" is directly the profile QGIS starts with.
> 
> * Click measuring button
> 
> * QGIS crashes even though my new profile "test" is the active profile 

@hauke96 can't replicate on QGIS master/ubuntu 20.04 and on QGIS 3.20/Windows 10.

**Comment by NauticalNeil** [comment]
Installing the latest LTR and new profile seems to have resolved the regular crashes whilst using the measuring tool. Thanks for your help On 21 Aug 2021 08:11, Giovanni Manghi ***@***.***> wrote:


Open QGIS

Create new profile "test". New QGIS window opens.

Measuring tool button works in this new profile

Close all QGIS windows

Open QGIS again. This time "test" is directly the profile QGIS starts with.

Click measuring button

QGIS crashes even though my new profile "test" is the active profile


@hauke96 can't replicate on QGIS master/ubuntu 20.04 and on QGIS 3.20/Windows 10.

**Comment by hauke96** [comment]
I downgraded to 3.16.9 LTR and created a new profile but QGIS still crashes. This also happens when I create a blank profile, open it and click on the measurement tool. However I think it's rather a problem on my machine and my arch setup. I'll keep an eye on that.
