### ISSUE TITLE
graduated renderer legend not rendered in the layout.

### ISSUE THREAD

**Issue by FERRATON** [qgis/QGIS#44637]
### What is the bug or the crash?

See the attached example combining a graduated rendering analysis with a symbol size defined by an attribute.

### Steps to reproduce the issue

unzip alain.zip
load issue.qgz
display demo layout
see png file showing the issue

### Versions

Version de QGIS | 3.16.9-Hannover | Révision du code | 9f8d2f79
[Alain.zip](https://github.com/qgis/QGIS/files/6961848/Alain.zip)

![pb](https://user-images.githubusercontent.com/2129643/128870360-7d382fd2-369c-4fcf-8d99-7f7ef54cdcb5.png)

**Comment by gioman** [comment]
@FERRATON sounds like https://github.com/qgis/QGIS/issues/39882#issuecomment-723669783 right?

**Comment by FERRATON** [comment]
Correct. Putting a non-zero size in the wizard for NULL values solves the problem
Thank you
