### ISSUE TITLE
Paletted Values - Load Color Map and Export Color Map freeze QGIS UI

### ISSUE THREAD

**Issue by ashleysommer** [qgis/QGIS#44630]
### What is the bug or the crash?

I think this is very platform-specific because two colleagues have verified this does not occur for them.

When I attempt to Load Color Map from file, or Export Color Map to File, the QGIS UI freezes unrecoverable.

#### Repro 1
Add a new Raster layer
Change layer styling to "Paletted/Unique values"
Click the "..." dropdown menu
Choose "Load color map from file"
Choose a valid working TXT color map file, click Open
** QGIS GUI Freezes **

#### Repro 2
Add a new Raster layer
Change layer styling to "Paletted/Unique values"
Click "Classify" to generate unique classifications with random colors
Click the "..." dropdown menu
Choose "Export color map to file"
Enter a file name, click Save.
** QGIS GUI Freezes **

#### Outcome
In both of these cases, the whole QGIS GUI is unresponsive, cannot click any button, cannot close QGIS. CPU usage for the process is reported as 0%, but RAM usage is reported very high (2.8GB used).

### Versions

I've replicated this bug on QGIS 3.18 and 3.20
```
QGIS version 3.20.0-Odense
QGIS code revision decaadbb
Qt version 5.15.3
Python version 3.8.8
GDAL/OGR version 3.2.1
PROJ version 6.3.2
EPSG Registry database version v9.8.6 (2020-01-22)
GEOS version 3.8.1-CAPI-1.13.3
SQLite version 3.36.0
PostgreSQL client version 12.2
SpatiaLite version 5.0.1
QWT version 6.1.5
QScintilla2 version 2.11.6
OS version KDE Flatpak runtime

Active Python plugins
MetaSearch
db_manager
processing
```

### Additional context

I'm on Ubuntu 20.04, using the latest official Flatpak distribution of QGIS v3.20

**Comment by gioman** [comment]
> I'm on Ubuntu 20.04, using the latest official Flatpak distribution of QGIS v3.20

@ashleysommer do the others use Flatpak? we don't support flatpack installations.

**Comment by ashleysommer** [comment]
No, my colleagues are both using Windows 10. 

I was under the impression the Flatpak published at flathub is an official supported build: https://flathub.org/apps/details/org.qgis.qgis, but looks like I was wrong.

Seems like I can file an issue at the flathub project's repo here: https://github.com/flathub/org.qgis.qgis

**Comment by ashleysommer** [comment]
I can try in a Ubuntu virtual machine to see if I can replicate the error with a .deb installation.
