### ISSUE TITLE
Can't drag and drop files when QGIS is opened with administrator privileges in Windows 10

### ISSUE THREAD

**Issue by Klemet** [qgis/QGIS#44642]
### What is the bug or the crash?

When QGIS is opened with administrator privileges in Windows 10, it becomes impossible to drag and drop files from Windows explorer to the layer menu, or to the QGIS window in general.

### Steps to reproduce the issue

1. Start QGIS without administrator privileges.
2. Drag and drop a raster file into the layer menu.
3. The raster file is added to the project and displayed in the QGIS window.
4. Quit GIS.
5. Start QGIS with administrator privileges.
6. Drag and drop a raster file into the layer menu.
7. Nothing happens.

### Versions

Tried with QGIS version 3.16.9 and QGIS 3.20.1.

**Comment by m-kuhn** [comment]
This is by design on Windows side, there's not much QGIS could do.
https://superuser.com/a/59106/309886

**Comment by Klemet** [comment]
Fascinating. Thank you, @m-kuhn !
