### ISSUE TITLE
Raster calculator tries to store results to read only location by default

### ISSUE THREAD

**Issue by Klemet** [qgis/QGIS#44643]
### What is the bug or the crash?

When QGIS is launched without administrator privileges on Windows 10, the raster calculator cannot save a raster file, and thus cannot be used. 

The error it returns is `Raster calculator : Could not create destination file`.

### Steps to reproduce the issue

1. Open QGIS without administrator privileges.
2. Open the raster calculator to calculate a a raster.
3. When clicking "Ok" in the raster calculator, the error happens.

### Versions

Tried with QGIS 3.16.9 and QGIS 3.20.1.

**Comment by nicogodet** [comment]
What is the equation ?
Something with ">" ?

**Comment by nyalldawson** [comment]
Make sure you hit the "..." button next to the output layer and pick a valid place to put the created file

**Comment by Klemet** [comment]
@nicogodet : The equation given in the calculator doesn't seem to influence the appearance of the issue : (. Inputing "1" or just the name of a raster still gives the issue.

@nyalldawson : Taking the time to input a particular location for the resulting file does work, even when QGIS is launched without administrator privileges. However, this seems like a regression; before this, it was possible to give a quick name without choosing an output folder, and a temporary file would be created. Now, it seems that the temporary file will not/can not be created unless administrator privileges are given to QGIS (Which, in turn, gives issue #44642 ).

**Comment by roya0045** [comment]
Outputs are created in the default directory, often sys32, which is why it was blocking you.
