### ISSUE TITLE
Pre / Post Execution Script

### ISSUE THREAD

**Issue by ChrisGISv1** [qgis/QGIS#44651]
### What is the bug or the crash?

Hello,
I use QGIS 3.16.3.
I would like to run a script after running a processing model.
In the processing tool options I can specify a path for a script.
However, this script does not work! In QGIS 2.18 it works.
Furthermore, I would like to have this script or this path only in this project, how can this be solved?
Thanks in advance
ChrisGISv1

### Steps to reproduce the issue

![issue](https://user-images.githubusercontent.com/88772838/129010409-4b7ea09c-de8b-4764-9160-4b0bba34591d.PNG)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS-Version | 3.16.3-Hannover | QGIS-Codeversion | 94ac9f21b8
-- | -- | -- | --
Kompiliert gegen Qt | 5.11.2 | Laufendes Qt | 5.11.2
Kompiliert mit GDAL/OGR | 3.1.4 | Läuft mit GDAL/OGR | 3.1.4
Kompiliert mit GEOS | 3.8.1-CAPI-1.13.3 | Läuft mit GEOS | 3.8.1-CAPI-1.13.3
Kompiliert mit SQLite | 3.29.0 | Läuft mit SQLite | 3.29.0
PostgreSQL-Client-Version | 11.5 | SpatiaLite-Version | 4.3.0
QWT-Version | 6.1.3 | QScintilla2-Version | 2.10.8
Kompiliert mit PROJ | 6.3.2 | Läuft mit PROJ | Rel. 6.3.2, May 1st, 2020
BS-Version | Windows 10 (10.0)
Aktive Python-Erweiterungen | pluginbuilder3; plugin_reloader; db_manager; MetaSearch; processing

</body></html>

**Comment by gioman** [comment]
and the model.

**Comment by ChrisGISv1** [comment]
![modell](https://user-images.githubusercontent.com/88772838/129012939-e9708865-345d-4ee1-a62c-d3c643da13aa.PNG)
simple model for testing

and here the script:

import webbrowser
url = 'https://www.Python-lernen.de/'
webbrowser.open_new(url)
print("Passiert etwas?")

**Comment by Gustry** [comment]
> I use QGIS 3.16.3.

Can you upgrade to 3.16.9 as well ?

**Comment by ChrisGISv1** [comment]
@gioman
the model is running, the new layer is loaded and displayed with the specifications from the qml.
But the script won't run.

**Comment by ChrisGISv1** [comment]
> 
> 
> > I use QGIS 3.16.3.
> 
> Can you upgrade to 3.16.9 as well ?

no unfortunately not possible

**Comment by gioman** [comment]
>  simple model for testing

@ChrisGISv1 can you please attach the model file? thanks.

**Comment by roya0045** [comment]
Pretty that the api of the script is outdated and won't work. Just update your script.

**Comment by agiudiceandrea** [comment]
It looks like other users still have the same issue: https://gis.stackexchange.com/questions/500772/qgis-post-execution-script-hook-usage

**Comment by MatthiasWebering** [comment]
I tried the example from the qgis docs https://docs.qgis.org/3.44/en/docs/training_manual/processing/hooks.html

``` python 
import os
import shutil
from processing.core.outputs import OutputVector, OutputRaster, OutputFile

MY_DIRECTORY = 'd:/test/post_processing_hook'

for output in alg.outputs:
    if isinstance(output, (OutputVector, OutputRaster, OutputFile)):
        dirname = os.path.split(output.value)[0]
        shutil.copytree(dirname, MY_DIRECTORY)
```

after that failed i also tried a simple script, that creates a textfile and writes to it

``` python 
from pathlib import Path
MY_DIRECTORY = Path('d:/test/post_processing_hook')

with open(MY_DIRECTORY / 'testfile.txt', 'w') as f:
    "This is a test file created by postprocessing_create_testfile.py"
```

both scripts were added to Settings --> Options --> Processing --> General --> Post-execution script
both scripts were not run

I also tried this with a new profile 

---
<table width='100%' align='center'><tr><td>QGIS version</td><td>3.44.10-Solothurn</td></tr><tr><td>QGIS code revision</td><td><a href="https://github.com/qgis/QGIS/commit/565fe70b">565fe70b</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>5.15.13</td></tr><tr><td>Python version</td><td>3.12.13</td></tr><tr><td>GDAL version</td><td>3.12.4 — <i>Chicoutimi</i></td></tr><tr><td>PROJ version</td><td>9.8.1</td></tr><tr><td>EPSG Registry database version</td><td>v12.029 (2025-10-02)</td></tr><tr><td>GEOS version</td><td>3.14.1-CAPI-1.20.5</td></tr><tr><td>SQLite version</td><td>3.53.0</td></tr><tr><td>PDAL version</td><td>2.10.0</td></tr><tr><td>PostgreSQL client version</td><td>17.3</td></tr><tr><td>SpatiaLite version</td><td>5.1.0</td></td></tr><tr><td>QWT version</td><td>6.3.0</td></tr><tr><td>QScintilla2 version</td><td>2.14.1</td></tr><tr><td>OS version</td><td>Windows 11 Version 2009</td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>custom_news_feed_hydrotec</td><td>v1.2.4</td></tr><tr><td>devtools</td><td>1.3.2</td></tr><tr><td>DissolveWithStats</td><td>0.6</td></tr><tr><td>GeorefExtension</td><td>4.0.0</td></tr><tr><td>hydrotec_config_plugin</td><td>0.1</td></tr><tr><td>hydrotec_toolbox</td><td>0.13</td></tr><tr><td>pluginbuilder3</td><td>3.2.1</td></tr><tr><td>plugin_reloader</td><td>0.9.4</td></tr><tr><td>valuetool</td><td>3.0.15</td></tr><tr><td>wwi_layers</td><td>0.1</td></tr><tr><td>processing</td><td>2.12.99</td></tr></table>

**Comment by agiudiceandrea** [comment]
Maybe @alexbruy could be of help here, since he has written the documentation about pre- and post-execution script hooks https://github.com/qgis/QGIS-Documentation/commit/9a2f41abf1115b5e7bc93c3683e91cb79f8241fe 10 years ago.

**Comment by agiudiceandrea** [comment]
It seems to me the pre- and post-execution script hooks were available in QGIS 2, whereas the functionality has never been implemented since QGIS 3 was released 8 years ago, although there are still the "Post-execution script" and "Pre-execution script" settings in Settings --> Options --> Processing --> General (which are actually meaningless and useless remnants).

If that is actually the case, then I think that, unless some developers want to reintroduce the missing functionality, such settings should be removed from the GUI and the mentions of the functionality should be removed from the docs.
