### ISSUE TITLE
Wrong interpretation of SLD color opacity

### ISSUE THREAD

**Issue by fzadrazil** [qgis/QGIS#44657]
### What is the bug or the crash?

When loading SLD with outline color defined using hexadecimal notation with alpha channel #RRGGBBAA, it is interpreted in wrong order as #AARRGGBB.

### Steps to reproduce the issue

1. Create polygon layer
2. Load style from SLD file with outline color defined as
```
<Stroke>
  <CssParameter name="stroke">#a0b0c07f</CssParameter>
</Stroke>
```

3. This color #b0c07fa0 is set as the outline color instead of #a0b0c0 color with 50% opacity

### Versions

Verze QGISu
3.20.0-Odense
Revize kódu QGISu
decaadbb31
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.0
PROJ version
8.0.1
EPSG Registry database version
v10.018 (2021-04-02)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
Layman
whiteboard
db_manager
MetaSearch
processing

**Comment by gioman** [comment]
> Maybe introducing new settings param which would specify the hexadecimal format that will be used?

@fzadrazil feel free to file a feature request (or maybe we can just change this as feature request).

**Comment by elpaso** [comment]
IMHO this is not an error, looking at https://docs.geoserver.org/stable/en/user/styling/sld/reference/linesymbolizer.html it seems like `stroke` is `#RRGGBB` and `stroke-opacity` if for the alpha.

Feel free to reopen if I am wrong.
