### ISSUE TITLE
Constant crashing

### ISSUE THREAD

**Issue by Jottsalm** [qgis/QGIS#44659]
## User Feedback

I have constant problems crashing the program, e.g. opening new projects. Could you make diagnosis?

## Report Details

**Crash ID**: [f3222c318f1cf3df1b06822aed29f3158b6c77f6](https://github.com/qgis/QGIS/search?q=f3222c318f1cf3df1b06822aed29f3158b6c77f6&type=Issues)

**Stack Trace**
<pre>
RtlpFreeHeapInternal :
RtlFreeHeap :
free free.c:51
DllUnregisterServer :
DllUnregisterServer :
CServerContextActivator::CreateInstance actvator.cxx:881
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1983
CApartmentActivator::CreateInstance actvator.cxx:2189
CProcessActivator::CCICallback actvator.cxx:1640
CProcessActivator::AttemptActivation actvator.cxx:1527
CProcessActivator::ActivateByContext actvator.cxx:1371
CProcessActivator::CreateInstance actvator.cxx:1271
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1983
CClientContextActivator::CreateInstance actvator.cxx:570
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1983
ICoCreateInstanceEx objact.cxx:2031
CComActivator::DoCreateInstance immact.hxx:386
CoCreateInstance actapi.cxx:121
_SHCoCreateInstance :
CreateAndCacheIconOverlay :
CFSIconOverlayManager::GetOverlayIconInformation :
CFSIconOverlayManager::LoadIconOverlayIdentifiers :
CFSIconOverlayManager::_s_LoadIconOverlayIdentifiers :
CFSIconOverlayManager::LoadNonloadedOverlayIdentifiers :
EnableExternalOverlayIdentifiers :
CFSIconOverlayManager::GetFileOverlayInfo :
CFSFolder::_GetOverlayInfo :
CIconOverlayTask::DispatchTasks :
CIconOverlayTask::InternalResumeRT :
CRunnableTask::Run :
CShellTask::TT_Run :
CShellTaskThread::ThreadProc :
CShellTaskThread::s_ThreadProc :
ExecuteWorkItemThreadProc :
RtlpTpWorkCallback :
TppWorkerThread :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.16.9-Hannover
QGIS code revision: 9f8d2f79
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.1
Running against GDAL: 3.3.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

### Steps to reproduce the issue

I have constant problems crashing the program, e.g. opening new projects. 

### Versions

QGIS-i versioon
3.16.9-Hannover
QGIS-i koodiredaktsioon
9f8d2f79
Kompileeritud Qt-le
5.15.2
Töötab Qt-s
5.15.2
Kompileeritud GDAL/OGR-le
3.3.1
Töötab GDAL/OGR-s
3.3.1
Kompileeritud GEOS'i pihta
3.9.1-CAPI-1.14.2
Töötab GEOS'il
3.9.1-CAPI-1.14.2
Compiled against SQLite
3.35.2
Running against SQLite
3.35.2
PostgreSQL-i kliendi versioon
13.0
SpatiaLite'i versioon
5.0.1
QWT versioon
6.1.3
QScintilla2 versioon
2.11.5
Compiled against PROJ
8.1.0
Running against PROJ
Rel. 8.1.0, July 1st, 2021
OS Version
Windows 10 Version 2009
Active python plugins
db_manager; 
MetaSearch; 
processing

**Comment by gioman** [comment]
@Jottsalm try a new QGIS profile, no 3rd party plugins installed.

**Comment by Jottsalm** [comment]
I also tried version 3.20 and same problems.

**Comment by gioman** [comment]
> I also tried version 3.20 and same problems.

@Jottsalm settings > user profiles > new profile

**Comment by Jottsalm** [comment]
New crash:
## User Feedback

s

## Report Details

**Crash ID**: [65637fd21486b4888f13a776bbfcf7576e2d3c70](https://github.com/qgis/QGIS/search?q=65637fd21486b4888f13a776bbfcf7576e2d3c70&type=Issues)


**Stack Trace**
<pre>
RtlpFreeHeapInternal :
RtlFreeHeap :
free free.c:51
DllUnregisterServer :
DllUnregisterServer :
CServerContextActivator::CreateInstance actvator.cxx:881
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1983
CApartmentActivator::CreateInstance actvator.cxx:2189
CProcessActivator::CCICallback actvator.cxx:1640
CProcessActivator::AttemptActivation actvator.cxx:1527
CProcessActivator::ActivateByContext actvator.cxx:1371
CProcessActivator::CreateInstance actvator.cxx:1271
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1983
CClientContextActivator::CreateInstance actvator.cxx:570
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1983
ICoCreateInstanceEx objact.cxx:2031
CComActivator::DoCreateInstance immact.hxx:386
CoCreateInstance actapi.cxx:121
_SHCoCreateInstance :
CreateAndCacheIconOverlay :
CFSIconOverlayManager::GetOverlayIconInformation :
CFSIconOverlayManager::LoadIconOverlayIdentifiers :
CFSIconOverlayManager::_s_LoadIconOverlayIdentifiers :
CFSIconOverlayManager::LoadNonloadedOverlayIdentifiers :
EnableExternalOverlayIdentifiers :
CFSIconOverlayManager::GetFileOverlayInfo :
CFSFolder::_GetOverlayInfo :
CRegFolder::_GetOverlayInfo :
CRegFolder::GetOverlayIndex :
CAutoDestItemsFolder::GetOverlayIndex :
CRegFolder::_GetOverlayInfo :
CRegFolder::GetOverlayIndex :
CNscOverlayTask::_Extract :
CNscOverlayTask::InternalResumeRT :
CRunnableTask::Run :
CShellTask::TT_Run :
CShellTaskThread::ThreadProc :
CShellTaskThread::s_ThreadProc :
ExecuteWorkItemThreadProc :
RtlpTpWorkCallback :
TppWorkerThread :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>


**QGIS Info**
QGIS Version: 3.16.9-Hannover
QGIS code revision: 9f8d2f79
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.1
Running against GDAL: 3.3.1



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

**Comment by Jottsalm** [comment]
Thank you, now it seems to be working.
