### ISSUE TITLE
the combination of a left click and the tabulation key on a selection makes QGIS crash

### ISSUE THREAD

**Issue by varoquiers** [qgis/QGIS#44669]
### What is the bug or the crash?

When selecting multiple objects on a linestring layer, the combination of a left click and the tabulation key on a selection makes Qgis crash.
Crash ID: 03364e9e53adf4eabab9cb4afbfb527b314295a3

### Steps to reproduce the issue

1. select a first linear object
2. maintain the tab key
3. select a new object

### Versions

QGIS Info
QGIS Version: 3.10.12-A Coru�a
QGIS code revision: 75c848ffb1
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4
System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.14393

**Comment by gioman** [comment]
>  QGIS Version: 3.10.12-A Coru�a

@varoquiers 3.10 is EOL you must test on 3-16 or 3.20 and you must test using a new QGIS profile, no 3rd party plugins installed.

**Comment by varoquiers** [comment]
The same bug occurs on Qgis 3.20.1 installed  this morning.

QGIS Info
QGIS Version: 3.20.1-Odense
QGIS code revision: 1c3c5cd6
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.1
Running against GDAL: 3.3.1

**Comment by gioman** [comment]
> The same bug occurs on Qgis 3.20.1 installed this morning.

@varoquiers have you tried on a new QGIS profile (and no 3rd party plugins installed)?

**Comment by varoquiers** [comment]
Yes, i've deleted my old profile before testing and no 3rd party plugins are installed.
It occurs when i want to select several objects with the tab key pressed.

**Comment by gioman** [comment]
Confirmed also on master/linux.
