### ISSUE TITLE
Not possible to edit toolbox model with QGIS LTR which contains an algorithm that is not available

### ISSUE THREAD

**Issue by pathmapper** [qgis/QGIS#44672]
### What is the bug or the crash?

Not possible to edit toolbox model with QGIS LTR which contains an algorithm that is not available.

### Steps to reproduce the issue

1. Add [test_model.zip](https://github.com/qgis/QGIS/files/6976089/test_model.zip) to the processing toolbox
2. Right click the model in the processing toolbox and choose `Edit model...`
3. See error message:

`Cannot edit model: The model you are trying to run contains an algorithm that is not available: native:deletecolumn`

If `Open Existing Model...` from the processing toolbox is used to open the model without adding it to the toolbox, it's possible to edit the model which should be the right behaviour to give the user the opportunity to fix the model.

![grafik](https://user-images.githubusercontent.com/20856381/129213689-9b3855c4-11ee-4056-9025-242a17d303ed.png)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

QGIS version | 3.16.9-Hannover | QGIS code revision | 9f8d2f79
-- | -- | -- | --
Compiled against Qt | 5.15.2 | Running against Qt | 5.15.2
Compiled against GDAL/OGR | 3.3.1 | Running against GDAL/OGR | 3.3.1
Compiled against GEOS | 3.9.1-CAPI-1.14.2 | Running against GEOS | 3.9.1-CAPI-1.14.2
Compiled against SQLite | 3.35.2 | Running against SQLite | 3.35.2
PostgreSQL Client Version | 13.0 | SpatiaLite Version | 5.0.1
QWT Version | 6.1.3 | QScintilla2 Version | 2.11.5
Compiled against PROJ | 8.1.0 | Running against PROJ | Rel. 8.1.0, July 1st, 2021
OS Version | Windows 10 Version 1909
Active python plugins | canvas_clipper; LAStools; plugin_reloader; db_manager; MetaSearch; processing

</body></html>

**Comment by hbvkq** [comment]
I was also prevented from opening my old models that had a grass tool that was renamed (rasterize). I couldn't open or use my model at all

Luckily, 3.20 installs in a new folder so I was able to access my previous qgis installation, remove the renamed algorithms from my models, then open them back in 3.20, an re-do all the model connections using the newer (renamed) grass algo.
