### ISSUE TITLE
Integer fields converted to Double when exporting to ESRI File Geodatabase (gdal-filegdb)

### ISSUE THREAD

**Issue by esnyder-rve** [qgis/QGIS#44676]
### What is the bug or the crash?

When saving a geopackage with an integer field, exporting to a file geodatabase via the gdal-filegdb driver converts the integer field into a double.

### Steps to reproduce the issue

1. Create Geopackage with integer field
2. Export as File Geodatabase

### Versions

QGIS version
3.20.1-Odense
QGIS code revision
1c3c5cd6
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.1
PROJ version
8.1.0
EPSG Registry database version
v10.027 (2021-06-17)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
searchlayers
db_manager
MetaSearch
processing

### Additional context

This was checked with a clean profile.

This is not listed as a known issue with the gdal driver, so it might be an issue with QGIS.

**Comment by gioman** [comment]
> Export as File Geodatabase

@esnyder-rve how exactly did you exported (save as? processing?)?

as far as I see there is no write support for the OpenFileGDB driver
```

ogr2ogr --formats | grep Open
OpenFileGDB -vector- (rov): ESRI FileGDB
```

**Comment by esnyder-rve** [comment]
@gioman it's not the OpenFileGDB driver, but the FileGDB driver [GDAL ESRI File Geodatabase Driver](https://gdal.org/drivers/vector/filegdb.html). This driver provides both read and write access to basic geodatabases. The driver is available in OSGeo4W as gdal-filegdb.
And, I just use the Export -> Save Features As -> ESRI FileGDB
![Screenshot 2021-08-13 081248](https://user-images.githubusercontent.com/61027950/129355439-13cbcbcf-2284-48c7-8c0a-f149ab83c036.png)

**Comment by gioman** [comment]
>  ESRI FileGDB

@esnyder-rve that driver is based on proprietary code from ESRI (in fact when you install that package you must accept their license, see below). So if the driver has an issue it is with ESRI that you should probably complain.


```
Copyright © 2014 ESRI

All rights reserved under the copyright laws of the United States and 
applicable international laws, treaties, and conventions.

You may freely redistribute and use the sample code, with or without 
modification, provided you include the original copyright notice and use 
restrictions.  

Disclaimer:  THE SAMPLE CODE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED 
WARRANTIES, INCLUDING THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS 
FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL ESRI OR 
CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, 
EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; 
OR BUSINESS INTERRUPTION) SUSTAINED BY YOU OR A THIRD PARTY, HOWEVER CAUSED 
AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR 
TORT ARISING IN ANY WAY OUT OF THE USE OF THIS SAMPLE CODE, EVEN IF ADVISED 
OF THE POSSIBILITY OF SUCH DAMAGE.

For additional information, contact:
Environmental Systems Research Institute, Inc.
Attn: Contracts and Legal Services Department
380 New York Street
Redlands, California, 92373
USA

```

**Comment by esnyder-rve** [comment]
Except, if it was a problem with the driver itself, I would suspect GDAL would have documented that in the Known Issues section of the driver documentation [ESRI File Geodatabase Known Issues](https://gdal.org/drivers/vector/filegdb.html#known-issues), but there is no known issue about integers being converted to doubles with the driver.

**Comment by gioman** [comment]
> Except, if it was a problem with the driver itself, I would suspect GDAL would have documented that in the Known Issues section of the driver documentation [ESRI File Geodatabase Known Issues](https://gdal.org/drivers/vector/filegdb.html#known-issues), but there is no known issue about integers being converted to doubles with the driver.

```
c:\Users\qgis\Desktop\training_manual_exercise_data>ogr2ogr -f "FileGDB" o1.gdb teste.gpkg
Warning 1: The output driver does not seem to natively support Integer64 type for field id. Converting it to Real instead. -mapFieldType can be used to control field type conversion.
```

**Comment by gioman** [comment]
> Except, if it was a problem with the driver itself, I would suspect GDAL would have documented that in the Known Issues section of the driver documentation [ESRI File Geodatabase Known Issues](https://gdal.org/drivers/vector/filegdb.html#known-issues), but there is no known issue about integers being converted to doubles with the driver.

@esnyder-rve not a QGIS issue in my opinion.

**Comment by esnyder-rve** [comment]
Huh, that should definitely be a documented issue.

**Comment by gioman** [comment]
> Huh, that should definitely be a documented issue.

@esnyder-rve feel free to file a ticket in GDAL tracker.

**Comment by esnyder-rve** [comment]
Yeah, I'm opening a ticket with GDAL, thanks.

**Comment by esnyder-rve** [comment]
For sake of documentation, the issue on GDAL: https://github.com/OSGeo/gdal/issues/4231
