### ISSUE TITLE
GRASS geoprocessing tools don't work on 3.20.1.

### ISSUE THREAD

**Issue by HugoP27** [qgis/QGIS#44670]
### What is the bug or the crash?

GRASS tools run in QGIS 3.20.1 but keep failing. I then reinstalled QGIS 3.18.3 and opened QGIS with this icon "QGIS Desktop 3.18.3 with GRASS 7.8.5" and the grass processing tools work fine now. 

Thank you for all the great work you do 

### Steps to reproduce the issue

1. I have a point shapefile (EPSG4326)  loaded in QGIS
![image](https://user-images.githubusercontent.com/51097011/129203025-b282dc74-c7d8-429f-928b-b7470dc64a50.png)

2. I then try to run any Grass algorithm, in the example case, v.buffer:
![image](https://user-images.githubusercontent.com/51097011/129203335-3b4fa20f-cb95-4c77-ac41-4e946d95c986.png)

3. I've tried different datasets and other grass algorithms, but the output stays the same. 

4. The error is not in the previous QGIS version

### Versions

3.20.1

### Additional context

My colleague had the same issue and also had to revert back to a previous QGIS version to be able to use GRASS algorithms

**Comment by gioman** [comment]
> My colleague had the same issue and also had to revert back to a previous QGIS version to be able to use GRASS algorithms

@HugoP27 works fine here in my testing environment (clean Win10 machine), probably yours is a local issue depending on some specific configuration of your machines.

![Peek 2021-08-12 15-14](https://user-images.githubusercontent.com/1951107/129212636-0f4b1522-29e8-49ce-bea8-5d21ed7a7e75.gif)

**Comment by HugoP27** [comment]
Thanks @gioman  I'll have a look and try figure out what's going on our side, did you use the standalone installer for 3.20.1?

**Comment by gioman** [comment]
> standalone

@HugoP27 standalone and osgeo4w (v2)
