### ISSUE TITLE
Model with "Drop field(s)" processing algorithm is not working with QGIS LTR 3.16.9 because of "native:" prefix

### ISSUE THREAD

**Issue by pathmapper** [qgis/QGIS#44671]
### What is the bug or the crash?

Model with `Drop field(s)` processing algorithm is not working with QGIS LTR 3.16.9 becaue of `native:` prefix.

### Steps to reproduce the issue

[test_models.zip](https://github.com/qgis/QGIS/files/6975919/test_models.zip) contains two models with the `Drop field(s)` processing algorithm:

- `model_qgis_3_16_9`
- `model_qgis_3_20_1`

Model `model_qgis_3_20_1` is not working with QGIS LTR 3.16.9 despite the `Drop field(s)` algorithm is available.

```
This algorithm cannot be run :-( 
The model you are trying to run contains an algorithm that is not available: native:deletecolumn
```

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

QGIS version | 3.16.9-Hannover | QGIS code revision | 9f8d2f79
-- | -- | -- | --
Compiled against Qt | 5.15.2 | Running against Qt | 5.15.2
Compiled against GDAL/OGR | 3.3.1 | Running against GDAL/OGR | 3.3.1
Compiled against GEOS | 3.9.1-CAPI-1.14.2 | Running against GEOS | 3.9.1-CAPI-1.14.2
Compiled against SQLite | 3.35.2 | Running against SQLite | 3.35.2
PostgreSQL Client Version | 13.0 | SpatiaLite Version | 5.0.1
QWT Version | 6.1.3 | QScintilla2 Version | 2.11.5
Compiled against PROJ | 8.1.0 | Running against PROJ | Rel. 8.1.0, July 1st, 2021
OS Version | Windows 10 Version 1909
Active python plugins | canvas_clipper; LAStools; plugin_reloader; db_manager; MetaSearch; processing

</body></html>

### Additional context

Having a look at the model XML, for the model created with QGIS 3.16.9 the algorithm is named `qgis:deletecolum` while for QGIS 3.20.1 it is named `native:deletecolum`.

According to https://docs.qgis.org/3.16/en/docs/user_manual/processing/console.html#calling-algorithms-from-the-python-console

> qgis:buffer is an alias for native:buffer and will also work

Both test models are working with QGIS 3.20.1, so there it doesn't matter if the algorithm is prefixed with `native:` or `qgis:`.

QGIS 3.16.9 LTR only accepts the `qgis:` prefix.

**Comment by DelazJ** [comment]
> QGIS 3.16.9 LTR only accepts the qgis: prefix.

@pathmapper `native` afaiu refers to algorithms ported to C++, and drop fields was ported to C++ in 3.18 (#40225). It's thus normal that 3.16 does not support `native:deletecolumn` and still only uses `qgis:deletecolumn`

**Comment by Gustry** [comment]
Indeed, from my experience, it works only from algorithms which have been migrated from Python to C++, so from `qgis:` to `native:`. The reverse wasn't implemented `native:` to `qgis:`.

Indeed, it could be nice that the reverse works as well. (whatever `qgis:` or `native:`, they are in QGIS application anyway)

**Comment by gioman** [comment]
> Indeed, it could be nice that the reverse works as well. (whatever `qgis:` or `native:`, they are in QGIS application anyway)

@Gustry so can we make this a feature request?

**Comment by nyalldawson** [comment]
This is by design -- QGIS files **aren't** backwards compatible. If you want to make a model which works flawlessly in 3.16 you need to use QGIS 3.16 to make the model (same as projects, QML, QPT, etc).

**Comment by pathmapper** [comment]
Thank you for the clarification @nyalldawson
