### ISSUE TITLE
list index out of range (Adding Attributes to Rasters)

### ISSUE THREAD

**Issue by ndrogers5** [qgis/QGIS#44673]
### What is the bug or the crash?

When I tried to add attributes to my raster file I received the following error:

An error has occurred while executing Python code: 
IndexError: list index out of range 
Traceback (most recent call last):
  File "C:\Users/12404/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\RasterAttributeTable\dialogs\CreateRasterAttributeTableDialog.py", line 62, in accept
    rat = create_rat_from_raster(
  File "C:\Users/12404/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\RasterAttributeTable\rat_utils.py", line 644, in create_rat_from_raster
    data['Count'].append(histogram_values[i])
IndexError: list index out of range

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.20.0-Odense Odense, decaadbb31 
Python Path:
•	C:/PROGRA~1/QGIS 3.20.0/apps/qgis/./python
•	C:/Users/12404/AppData/Roaming/QGIS/QGIS3\profiles\default/python
•	C:/Users/12404/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
•	C:/PROGRA~1/QGIS 3.20.0/apps/qgis/./python/plugins
•	C:\PROGRA~1\QGIS 3.20.0\bin\python39.zip
•	C:\PROGRA~1\QGIS 3.20.0\apps\Python39\DLLs
•	C:\PROGRA~1\QGIS 3.20.0\apps\Python39\lib
•	C:\PROGRA~1\QGIS 3.20.0\bin
•	C:\PROGRA~1\QGIS 3.20.0\apps\Python39
•	C:\PROGRA~1\QGIS 3.20.0\apps\Python39\lib\site-packages
•	C:\PROGRA~1\QGIS 3.20.0\apps\Python39\lib\site-packages\win32
•	C:\PROGRA~1\QGIS 3.20.0\apps\Python39\lib\site-packages\win32\lib
•	C:\PROGRA~1\QGIS 3.20.0\apps\Python39\lib\site-packages\Pythonwin
•	C:/Users/12404/AppData/Roaming/QGIS/QGIS3\profiles\default/python
•	C:/Users/12404/Desktop/HEC-HMS Practice/QGIS Practice
.

### Steps to reproduce the issue

Pulled gSURRGO mukey raster file into QGIS, and was trying to join attributes to it (and to see what attributes this file already possessed).  I had to install the AddRasterAttributes plugin (which appears to have installed fine).

I right clicked on my clipped tiff file and selected the option to add a "New Attribute Table".

When I clicked either of the 2 options to define the Raster file (either GDAL or VAT DBF) that appeared in the next dialog box I got the error message shown below:

An error has occurred while executing Python code: 
IndexError: list index out of range 
Traceback (most recent call last):
  File "C:\Users/12404/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\RasterAttributeTable\dialogs\CreateRasterAttributeTableDialog.py", line 62, in accept
    rat = create_rat_from_raster(
  File "C:\Users/12404/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\RasterAttributeTable\rat_utils.py", line 644, in create_rat_from_raster
    data['Count'].append(histogram_values[i])
IndexError: list index out of range

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.20.0-Odense Odense, decaadbb31 
Python Path:
•	C:/PROGRA~1/QGIS 3.20.0/apps/qgis/./python
•	C:/Users/12404/AppData/Roaming/QGIS/QGIS3\profiles\default/python
•	C:/Users/12404/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
•	C:/PROGRA~1/QGIS 3.20.0/apps/qgis/./python/plugins
•	C:\PROGRA~1\QGIS 3.20.0\bin\python39.zip
•	C:\PROGRA~1\QGIS 3.20.0\apps\Python39\DLLs
•	C:\PROGRA~1\QGIS 3.20.0\apps\Python39\lib
•	C:\PROGRA~1\QGIS 3.20.0\bin
•	C:\PROGRA~1\QGIS 3.20.0\apps\Python39
•	C:\PROGRA~1\QGIS 3.20.0\apps\Python39\lib\site-packages
•	C:\PROGRA~1\QGIS 3.20.0\apps\Python39\lib\site-packages\win32
•	C:\PROGRA~1\QGIS 3.20.0\apps\Python39\lib\site-packages\win32\lib
•	C:\PROGRA~1\QGIS 3.20.0\apps\Python39\lib\site-packages\Pythonwin
•	C:/Users/12404/AppData/Roaming/QGIS/QGIS3\profiles\default/python
•	C:/Users/12404/Desktop/HEC-HMS Practice/QGIS Practice
.

### Versions

QGIS version
3.20.0-Odense
QGIS code revision
decaadbb31
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.0
PROJ version
8.0.1
EPSG Registry database version
v10.018 (2021-04-02)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
RasterAttributeTable
db_manager
MetaSearch
processing

### Additional context

I'm trying to figure out how to tie gSSURGO soil texture attributes to some sort of spacial file which can be used to derive subbasin characteristics for HEC-HMS hydrologic analysis.

**Comment by roya0045** [comment]
Ask the plugin author. This is not part of qgis itself.

**Comment by ndrogers5** [comment]
Can I get any guidance on how/where to find out who the plugin author is??

**Comment by gioman** [comment]
> Can I get any guidance on how/where to find out who the plugin author is??

@ndrogers5 see details in QGIS plugin manager.

**Comment by roya0045** [comment]
@elpaso can you migrate this to your repo?
