### ISSUE TITLE
More intuitive way to turn on/off several symbol layers

### ISSUE THREAD

**Issue by antoniolocandro** [qgis/QGIS#44677]
### Feature description

It would be nice if instead of having the checkbox down  a small eye on/off symbol would be beside the symbol layer. This is useful when you have several layers and want to check how one looks by hiding the others. 

### Additional context

![image](https://user-images.githubusercontent.com/4627073/129248245-cf472751-a487-4a19-aa2a-6e9c38aa11ee.png)

**Comment by DelazJ** [comment]
Duplicate of #33861?

**Comment by antoniolocandro** [comment]
Yes, can you please merge
