### ISSUE TITLE
Compile fails, 'None' is not a member of 'QgsField::ConfigurationFlags'

### ISSUE THREAD

**Issue by hege-li** [qgis/QGIS#44681]
### What is the bug or the crash?

Building 3.20-git on RHEL7 with GCC 10.2.1 fails here (also tried devtoolset-8 and 9, no difference)

[  0%] Building CXX object src/core/CMakeFiles/qgis_core.dir/qgis_core_autogen/mocs_compilation.cpp.o
In file included from /home/wms/src/qgis-3.20.1-210812/build/src/core/qgis_core_autogen/mocs_compilation.cpp:171:
/home/wms/src/qgis-3.20.1-210812/build/src/core/qgis_core_autogen/EWIEGA46WW/moc_qgsfield.cpp:105:46: error: 'None' is not a member of 'QgsField::ConfigurationFlags' {aka 'QFlags<QgsField::ConfigurationFlag>'}
  105 |       18, uint(QgsField::ConfigurationFlags::None),
      |                                              ^~~~
/home/wms/src/qgis-3.20.1-210812/build/src/core/qgis_core_autogen/EWIEGA46WW/moc_qgsfield.cpp:106:46: error: 'NotSearchable' is not a member of 'QgsField::ConfigurationFlags' {aka 'QFlags<QgsField::ConfigurationFlag>'}
  106 |       19, uint(QgsField::ConfigurationFlags::NotSearchable),
      |                                              ^~~~~~~~~~~~~
/home/wms/src/qgis-3.20.1-210812/build/src/core/qgis_core_autogen/EWIEGA46WW/moc_qgsfield.cpp:107:46: error: 'HideFromWms' is not a member of 'QgsField::ConfigurationFlags' {aka 'QFlags<QgsField::ConfigurationFlag>'}
  107 |       20, uint(QgsField::ConfigurationFlags::HideFromWms),
      |                                              ^~~~~~~~~~~
/home/wms/src/qgis-3.20.1-210812/build/src/core/qgis_core_autogen/EWIEGA46WW/moc_qgsfield.cpp:108:46: error: 'HideFromWfs' is not a member of 'QgsField::ConfigurationFlags' {aka 'QFlags<QgsField::ConfigurationFlag>'}
  108 |       21, uint(QgsField::ConfigurationFlags::HideFromWfs),
      |                                              ^~~~~~~~~~~
make[2]: *** [src/core/CMakeFiles/qgis_core.dir/qgis_core_autogen/mocs_compilation.cpp.o] Error 1

### Steps to reproduce the issue

cmake .. \
  -DCMAKE_BUILD_TYPE=Release \
  -DWITH_SERVER=TRUE \
  -DWITH_SERVER_PLUGINS=FALSE \
  -DWITH_GUI=FALSE \
  -DWITH_DESKTOP=FALSE \
  -DWITH_POSTGRESQL=FALSE \
  -DWITH_BINDINGS=FALSE \
  -DWITH_QTWEBKIT=FALSE \
  -DWITH_QT5SERIALPORT=FALSE \
  -DENABLE_TESTS=FALSE
make

### Versions

Latest 3.20.1+git

**Comment by gioman** [comment]
@hege-li same as https://github.com/qgis/QGIS/issues/44668 ?

**Comment by hege-li** [comment]
@gioman This is different error in different version (3.16 vs 3.20).

**Comment by gioman** [comment]
@hege-li have you asked in the developers mailing list, rather than assuming is a bug?

**Comment by hege-li** [comment]
@gioman I posted both on list too. Are you saying that build system failures are not fixable and they are not bugs? I build dozens of software, but QGis is most difficult to work with, every major version breaks something or increases some dependency version requirement etc. Of course it's clear it's not tested on RHEL/CentOS, I would change to Ubuntu if I could.

**Comment by lbartoletti** [comment]
@hege-li I was able to build QGIS on centos7, but from scratch to have the latest version of dependecies.

I guess you have an old Qt version. What's your version. Minimum required is 5.12.0

**Comment by hege-li** [comment]
@lbartoletti I only see 5.9.7 available on my RHEL7, do you have some external repos on your centos7?

qt5-qtbase.x86_64                  5.9.7-5.el7_9   @rhel-x86_64-server-7

**Comment by hege-li** [comment]
I'll close this anyway, since I did not notice QGIS 5.20 qt5 version dependency was raised from 5.9 -> 5.12.
