### ISSUE TITLE
No pop up

### ISSUE THREAD

**Issue by aliceholvoet** [qgis/QGIS#44687]
### What is the bug or the crash?

No pop-up window appears when I create an new entity in a layer, nor when I try to use the "measure length" tool.
The attribute table and properties window opens correctly 
I'm working with qgis 3.14. I haven't had this problem before (I've been using this version for a long time).
I've tried to connect my computer to another screen, to restart, to try in another Qgis project with another empty layer...

### Steps to reproduce the issue

Go to 'new shapefile layer'
Edit
Create new entity

### Versions

Version de QGIS
3.14.0-Pi
Révision du code
9f7028fd23
Compilé avec Qt
5.11.2
Utilisant Qt
5.11.2
Compilé avec GDAL/OGR
3.0.4
Utilisé avec GDAL/OGR
3.0.4
Compilé avec GEOS
3.8.1-CAPI-1.13.3
Utilisé avec GEOS
3.8.1-CAPI-1.13.3
Compilé avec SQLite
3.29.0
Fonctionne avec SQLite
3.29.0
Version du client PostgreSQL
11.5
Version de SpatiaLite
4.3.0
Version de QWT
6.1.3
Version de QScintilla2
2.10.8
Compilé avec PROJ
6.3.2
Fonctionne avec PROJ
Rel. 6.3.2, May 1st, 2020
Version de l'OS
Windows 10 (10.0)
Extensions Python actives
PointConnector; 
slyr_community; 
db_manager; 
MetaSearch; 
processing

**Comment by gioman** [comment]
@aliceholvoet update to 3.16 or 3.20 (3.14 is EOL), try a new QGIS profile.
