### ISSUE TITLE
Solved: problem installing QGIS Odense on Linux Mint 20.2 Uma

### ISSUE THREAD

**Issue by DButler43** [qgis/QGIS#44686]
### What is the bug or the crash?

Install of QGIS Odense on Linux Mint 20.2 Uma led to install of QGIS Coruna and not Odense, and gave an error message of repository does not have a release file. 
In case useful to anyone (I didn't find this listed in past tissue reports), issue was solved using workaround by Kadaitcha Man [here ](https://forums.linuxmint.com/viewtopic.php?t=334097) of changing the repository reference in Admin "Software Sources" to 'focal' repository -- ie  'https://qgis.org/debian focal main

### Steps to reproduce the issue

Try installing QGIS Odense on Linux Mint 20.2 Uma using the instructions on the QGIS download page https://www.qgis.org/en/site/forusers/alldownloads.html#debian-ubuntu

### Versions

QGIS version | 3.20.1-Odense

**Comment by gioman** [comment]
> Try installing QGIS Odense on Linux Mint 20.2 Uma using the instructions on the QGIS download page https://www.qgis.org/en/site/forusers/alldownloads.html#debian-ubuntu

@DButler43 the command referred there adds the distro name... but for all ubuntu based distros the name should the one of the Ubuntu version used as base as the distribution used. This has nothing to do with QGIS or QGIS code.
