### ISSUE TITLE
GIS crashes when creating a second field in attribute table.

### ISSUE THREAD

**Issue by lucyb95** [qgis/QGIS#44684]
### What is the bug or the crash?

I am trying to populate a blank attribute table with fields. The shapefile has one feature.

I can delete the two fields that are already present when I first create the shapefile (id etc.) and create and populate the first of my necessary fields, or do this the other way around (create my first field and then delete any unnecessary fields).

However when I go to create the second I can name it, select the input type (string etc.) and the length, but when I select OK, GIS crashes immediately. 

I have never previously encountered this issue. This began yesterday (12/08/21) and has continued today. 

### Steps to reproduce the issue

1. Open the attribute table of newly created shapefile. This was created by buffering a site boundary shapefile and exporting the resulting buffer as the shapefile 'Search Area'. 
![GISerror2](https://user-images.githubusercontent.com/88886292/129351068-0a3c6b70-5727-4a0f-b729-fd8f55cce42c.jpg)
 
2. Click on 'Add Field' icon and add in first attribute. The field is successfully added. 
![GISerror1](https://user-images.githubusercontent.com/88886292/129351221-88e24cbc-cc2a-45c5-a45a-2cff64e49200.jpg)

3. Delete the blank id attribute by using the 'Delete Field' icon (successful) and attempt to add a second Field by again using 'Add Field'.  Fill out the name, type, and length.
![GISerror](https://user-images.githubusercontent.com/88886292/129350034-015bf752-fba9-4b74-afeb-8abe8408b7bd.jpg)

4. Click 'OK'. 
5. GIS crashes and closes. 
6

N.B I can either delete the blank fields first or after the first attribute, it still crashes when creating the second. 

### Versions

QGIS version
3.4.15-Madeira
QGIS code revision
e83d02e274
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
2.4.3
Running against GDAL/OGR
2.4.3
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
5.2.0
Running against PROJ
Rel. 5.2.0, September 15th, 2018
Active python plugins
TomBio; 
db_manager; 
MetaSearch; 
processing

### Additional context

I am working with a shapefile of a site buffer, to complete a data search of environmental records. 

To create the shapefile, I buffered a simple site boundary shapefile and exported the resulting buffer as another shapefile, Search Area. I over-wrote my previous Search Area shapefile with this new single buffer. I do this frequently, and have never had any problems populating a blank attribute table in this way.

**Comment by gioman** [comment]
>  3.4.15-Madeira

@lucyb95 way too old, update to 3.16 or 3.20 and try with a new QGIS profile, no 3rd party plugins installed.
