### ISSUE TITLE
QGIS crashing when opening properties of vector file.

### ISSUE THREAD

**Issue by sumansinha23** [qgis/QGIS#44682]
### What is the bug or the crash?

while opting for the properties for any vector file, QGIS is crashing and showing the message ' QGIS unexpectedly ended '. How to fix the problem?

### Steps to reproduce the issue

kindly help.

### Versions

3.10

**Comment by gioman** [comment]
> 3.10

@sumansinha23 3.10 ie EOL, update to the latest 3.16 or 3.20 and try on a new QGIS profile, no 3rd party plugins installed.
