### ISSUE TITLE
Query builder save and load error

### ISSUE THREAD

**Issue by NvBgm** [qgis/QGIS#44691]
### What is the bug or the crash?

After QGIS update to v3.2 I get the following error when loading a query.
'Syntax error unexpected GT'
This is the query I'm using.
'"PACKAGE" < > '07a' AND "PACKAGE" < '13a''
The save option is okay but can't reload it.
Is this a bug or am I missing something elsewhere?

### Steps to reproduce the issue

![error query loading 2021-08-14 132118](https://user-images.githubusercontent.com/8125819/129444783-c06010d1-e233-48e1-917d-7a5c70b037ee.png)

### Versions

QGIS-versie
3.20.2-Odense
QGIS code revisie
9f59a156
Qt versie
5.15.2
Python versie
3.9.5
GDAL/OGR versie
3.3.1
PROJ versie
8.1.0
EPSG-register databaseversie
v10.027 (2021-06-17)
GEOS versie
3.9.1-CAPI-1.14.2
SQLite versie
3.35.2
PDAL versie
2.3.0
PostgreSQL client versie
13.0
SpatiaLite versie
5.0.1
QWT versie
6.1.3
QScintilla2 versie
2.11.5
OS versie
Windows 10 Version 2009

Actieve Python plug-ins
bfvw_tools
changeDataSource
clipper
export_to_sql_server
lizmap
pdokservicesplugin
pluginbuilder3
plugin_reloader
qconsolidate3
qfieldsync
qgis-maptiler-plugin
qgis-plugin-findreplace-main
qgis2web
qtiles
SelectWithin
db_manager
processing

**Comment by DelazJ** [comment]
Not a QGIS bug imho.
There shouldn't be space between `<` and `>`, assuming the operator `<>` is supported. Otherwise you could use `!=` if different is what you were looking for.

**Comment by NvBgm** [comment]
Yes now it is working 100% 
Thank you
