### ISSUE TITLE
Crash when adding new layer to project during Georeferencing

### ISSUE THREAD

**Issue by GIS597** [qgis/QGIS#44698]
### What is the bug or the crash?

i have noticed this problem 4-5 times already. when i am in the middle of georeferncing a raster, and i want to add a new layer to the project from a geopackage, qgis crashes.
version 3.20.1, on windows 10 

### Steps to reproduce the issue

1. georefference a raster,
2. add a new layer from a geopackage
3. crash

### Versions

QGIS version
3.20.1-Odense
QGIS code revision
1c3c5cd6
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.1
PROJ version
8.1.0
EPSG Registry database version
v10.018 (2021-04-02)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
AzimuthMeasurement
DigitizingTools
EasyCustomLabeling
GeometryShapes
HCMGIS
kmltools
latlontools
mmqgis
qgis_resource_sharing
qgsAzimuth
shapetools
SRTM-Downloader
TerrainShading
db_manager
MetaSearch
processing

**Comment by gioman** [comment]
@GIS597 try with a new QGIS profile, no 3rd party plugins installed. If the problem persist please attach the image you want to georef, the GCP table/file and the georef parameters.

**Comment by gioman** [comment]
> * georefference a raster,
> 
> * add a new layer from a geopackage
> 
> * crash

@GIS597 sorry the problem is not while georeferencing. Still try with a new QGIS profile.
