### ISSUE TITLE
SVG paths are not shown for layout items

### ISSUE THREAD

**Issue by nyalldawson** [qgis/QGIS#44703]
### What is the bug or the crash?

SVG paths are no longer shown for existing layout picture items

### Steps to reproduce the issue

1. add a picture to a layout
2. pick an svg path using the file picker
3. click off it, click back on the item
4. the path is missing

### Versions

3.20

**Comment by nyalldawson** [comment]
@3nids this looks like another fallout from the svg widget work

**Comment by nicogodet** [comment]
https://github.com/qgis/QGIS/issues/44532
