### ISSUE TITLE
flatpak phyton libaries

### ISSUE THREAD

**Issue by ThomasStruller** [qgis/QGIS#44701]
### What is the bug or the crash?

To the maintainers of the flatpak for qgis:

thats what i get on startup:
The contour plugin is disabled as it requires python modules numpy and matplotlib which are not both installed
please compile qgis with the phython modules  numphy and mathplotlib. A lot of extensions need these libaries.

on flathub 3.20.2 is adressed, but what I get is 3.16.10 

I am on linux mint 20.2

Thank you for your work

### Steps to reproduce the issue

Starting qgis from the flatpak I get the following:

The contour plugin is disabled as it requires python modules numpy and matplotlib which are not both installed

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS-Version | 3.16.10-Hannover | QGIS-Codeversion | e5b665e9
-- | -- | -- | --
Kompiliert gegen Qt | 5.15.3 | Laufendes Qt | 5.15.3
Kompiliert mit GDAL/OGR | 3.2.1 | Läuft mit GDAL/OGR | 3.2.1
Kompiliert mit GEOS | 3.8.1-CAPI-1.13.3 | Läuft mit GEOS | 3.8.1-CAPI-1.13.3
Kompiliert mit SQLite | 3.32.1 | Läuft mit SQLite | 3.32.1
PostgreSQL-Client-Version | 12.2 | SpatiaLite-Version | 4.3.0a
QWT-Version | 6.1.5 | QScintilla2-Version | 2.11.6
Kompiliert mit PROJ | 6.3.2 | Läuft mit PROJ | Rel. 6.3.2, May 1st, 2020
BS-Version | KDE Flatpak runtime
Aktive Python-Erweiterungen | contour; LAStools; mmqgis; nominatim_locator_filter; quick_map_services; MemoryLayerSaver; qgis2web; MetaSearch; processing; db_manager

</body></html>

**Comment by nicogodet** [comment]
It is written on https://qgis.org/en/site/forusers/alldownloads.html#flatpak to report issues on
https://github.com/flathub/org.qgis.qgis/issues
