### ISSUE TITLE
Possible memory leak in v3.20.1

### ISSUE THREAD

**Issue by kaligrafy** [qgis/QGIS#44714]
### What is the bug or the crash?

On a MacPro 2019, it uses more an more memory until it reached 934GB (112 GB RAM + virtual memory) and crashed.
Did not happen on 3.18 with the same project.

### Steps to reproduce the issue

1. Open a project on macos with v3.20.1

### Versions

3.20.1

**Comment by nyalldawson** [comment]
A sample project and data is required here

**Comment by kaligrafy** [comment]
On my machine, it does this with any project, small or big. I just open a project and the RAM goes up forever until the machine run out of memory. I will try to investigate if there are any call to an url, like aerial imagery tilesets (maybe it tries to download the whole world or something)

**Comment by kaligrafy** [comment]
Well, it seems to be related to XYZ/WMS tiles indeed, because when I deactivate some of them in my projects, the memory does not go mad.

**Comment by gioman** [comment]
> Well, it seems to be related to XYZ/WMS tiles indeed, because when I deactivate some of them in my projects, the memory does not go mad.

@kaligrafy have you tried on a new QGIS profile (no 3rd party plugins installed)?
