### ISSUE TITLE
Function list in the Field Calculator's help disappears when the search tool is used (3.21.0-79) 

### ISSUE THREAD

**Issue by ValPinnaSardinia** [qgis/QGIS#44711]
### What is the bug or the crash?

In the new master version (3.21.0-79), when in the Field Calculator Help panel a word is written in the search text box, all the below list of functions disappears. 
The only way to solve it is to close the Field Calculator and reopen it. 
Also, if a complete function is written in the box test, this will appear (e.g. `array` or `$x`). 

NB. After a few test done by the QGIS Italian community, seems that the issue is replicable only in Windows, while in Linux the issue is absent.  

### Steps to reproduce the issue

1. Open the Field Calculator
2. Digit something in the Help Search Text Box ( a word or only a character) 

### Versions

QGIS Version: Master 3.21.0-79
OS: Windows 10

**Comment by pigreco** [comment]
I confirm

## OSGeo4W64 win 10

**Comment by agiudiceandrea** [comment]
Probably it's related to https://github.com/qgis/QGIS/pull/44476.

**Comment by ValPinnaSardinia** [comment]
> Probably it's related to #44476.
> 
> @ValPinnaSardinia
> 
> > After a few test done by the QGIS Italian community, seems that the issue is replicable only in Windows, while in Linux the issue is absent.
> 
> Do you mean somebody tested a recent master version on GNU/Linux without experiencing the issue? At what commit was the master version tested on Linux built? What Qt version?

That it's what I was meaning. But I just discovered that the test in Ubuntu was done using the LTR version, so no info is available from my side on GNU/Linux environment. Sorry

**Comment by agiudiceandrea** [comment]
> But I just discovered that the test in Ubuntu was wrongly done using the LTR version

I guess it also affects current master on GNU/Linux.
