### ISSUE TITLE
Georeference image conversion bug

### ISSUE THREAD

**Issue by h0wardch3ng** [qgis/QGIS#44727]
### What is the bug or the crash?

Image conversion from png to tif
Compression method is none

### Steps to reproduce the issue

standard
old version is okay

### Versions

3.20.1

### Additional context

![Snipaste_2021-08-17_14-57-54](https://user-images.githubusercontent.com/2175497/129678963-9bda1b73-c19a-4a9c-95a8-375b5066b184.png)

**Comment by roya0045** [comment]
It's almost as if the error message was important.

**Comment by gioman** [comment]
@h0wardch3ng we need more details: the image you are trying to georef, the GCP file, the full georef configs, etc.
