### ISSUE TITLE
CSS issue in print layout when using cascaded HTML elements in HTML frame

### ISSUE THREAD

**Issue by gislars** [qgis/QGIS#44733]
### What is the bug or the crash?

In my print layout I'm using a HTML frame. When I have a construct like the following HTML snippet, I expect the table also using the specified font-size. Instead a different font-size is used. 

```
<div style="font-size: 10px;">
    <table>
        <tbody>
            <tr>
                <td>a</td>
                <td>1</td>
            </tr>
            <tr>
                <td>b</td>
                <td>2</td>
            </tr>
        </tbody>
    </table>
</div>
```
To work around this issue I applied the same CSS to the table element:

```
<div style="font-size: 10px;">
    <table style="font-size: inherit;">
        <tbody>
            <tr>
                <td>a</td>
                <td>1</td>
            </tr>
            <tr>
                <td>b</td>
                <td>2</td>
            </tr>
        </tbody>
    </table>
</div>
```
I don't know what component is parsing/rendering the HTML or how to debug the actual used CSS styles.

### Steps to reproduce the issue

1. Open QGis
2. Create new print layout
3. Add HTML frame
4. Insert following HTML code
```
<div style="font-size: 10px;">
    <table>
        <tbody>
            <tr>
                <td>a</td>
                <td>1</td>
            </tr>
            <tr>
                <td>b</td>
                <td>2</td>
            </tr>
        </tbody>
    </table>
</div>
```
5. Add second HTML frame 
6. Insert following HTML code
```
<div style="font-size: 10px;">
    <table style="font-size: inherit;">
        <tbody>
            <tr>
                <td>a</td>
                <td>1</td>
            </tr>
            <tr>
                <td>b</td>
                <td>2</td>
            </tr>
        </tbody>
    </table>
</div>
```
7. See the different font size in both HTML frames.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.16.10-Hannover | QGIS code revision | e5b665e952
-- | -- | -- | --
Compiled against Qt | 5.12.8 | Running against Qt | 5.12.8
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.8 (Ubuntu 12.8-0ubuntu0.20.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Linux Mint 20.2

</body></html>

**Comment by nyalldawson** [comment]
This is an upstream (qt) issue -- QGIS itself relies entirely on Qt for rendering html content and intrepreting stylesheets/html/etc.
