### ISSUE TITLE
QGIS 3.20.2 Odense crashing at startup

### ISSUE THREAD

**Issue by jannikhuels** [qgis/QGIS#44748]
### What is the bug or the crash?

Starting of QGIS 3.20.2 on 

Microsoft Windows 10.0.19042 

not possible. Installation was performed using the OSGeo4W Installer choosing Quick Installation. I had QGIS 3.16 LTR installed before, which is installed in another folder. 

Startup immediately stops saying "Python Error" :

Crash ID: c71dcbb69c2de1f322676c6b5eb537a5197f27fc

Stack Trace

PyTuple_Size :
PyInit_QtCore :
PyInit_QtWidgets :
QObject::inherits :
QFusionStyle::polish :
QWidget::event :
PyInit_QtWidgets :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidget::ensurePolished :
QWidget::event :
PyInit_QtWidgets :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
QgsMessageViewer::showMessage :
instance :
QgisApp::rotatePointSymbols :
QgsPythonRunner::run :
QgisApp::QgisApp :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.20.2-Odense
QGIS code revision: 9f59a156
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.1
Running against GDAL: 3.3.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

### Steps to reproduce the issue

Start QGIS

### Versions

QGIS 3.20.2

**Comment by gioman** [comment]
> Startup immediately stops saying "Python Error"  

@jannikhuels try deleting manually the 3rd party plugins from your QGIS profile folder.

**Comment by jannikhuels** [comment]
Thanks a lot. Now QGIS is starting properly again. 

Now I just have to find out which plugin caused the issue. Wouldn't it make sense, if possible, to have a more precise error description? E.g. containing the plugins name that causes the issue?

**Comment by jannikhuels** [comment]
And another - possibly related - issue: No script (Menu Raster/Vector and Toolbox) is shown. I expect all are causing issues because of the updated python version?

**Comment by DelazJ** [comment]
> And another - possibly related - issue: No script (Menu Raster/Vector and Toolbox) is shown

Do you have the "Processing" plugin enabled? It's not a third-party plugin, so no need to deactivate it when you want to check issues.

**Comment by gioman** [comment]
>  Wouldn't it make sense, if possible, to have a more precise error description?

@jannikhuels if a plugin returns an error it is indeed shown by QGIS (in the message bar and logs), but if the plugin makes QGIS crash on start there is not much can be done, I think.

**Comment by jannikhuels** [comment]
@gioman Ok. I thought at least QGIS knows which plugins caused the issue. It would have made my debugging much easier. 

@DelazJ thanks a lot. Indeed the processing plugin was deactivated.
