### ISSUE TITLE
Field from joined layer with modified widget settings crashes QGIS when opening form

### ISSUE THREAD

**Issue by andreglauser** [qgis/QGIS#44753]
### What is the bug or the crash?

QGIS crashes when opening a form from a feature in a layer with joined fields from another Layer and customized widget settings for the joined field(s) (ex. Multiline for text).

Opening a form without modified widgets works fine.

### Steps to reproduce the issue

1. Open `no-widget-settings.qgz` from the uploaded example.
2. Open a form from a point with the identify-tool. Should work.
3. Open the layer-settings from points, go to the form-settings, mark multiline as checked for the field `joined_data_name` and press OK
4. Open a form from a point with the identify-tool. QGIS crashes.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

QGIS-Version | 3.16.10-Hannover | QGIS-Codeversion | e5b665e952
-- | -- | -- | --
Kompiliert gegen Qt | 5.11.2 | Laufendes Qt | 5.11.2
Kompiliert mit GDAL/OGR | 3.1.4 | Läuft mit GDAL/OGR | 3.1.4
Kompiliert mit GEOS | 3.8.1-CAPI-1.13.3 | Läuft mit GEOS | 3.8.1-CAPI-1.13.3
Kompiliert mit SQLite | 3.29.0 | Läuft mit SQLite | 3.29.0
PostgreSQL-Client-Version | 11.5 | SpatiaLite-Version | 4.3.0
QWT-Version | 6.1.3 | QScintilla2-Version | 2.10.8
Kompiliert mit PROJ | 6.3.2 | Läuft mit PROJ | Rel. 6.3.2, May 1st, 2020
BS-Version | Windows 10 (10.0)
Aktive Python-Erweiterungen | db_manager; MetaSearch; processing

</body></html>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

QGIS-Version | 3.18.3-Zürich | QGIS-Codeversion | 735cc85be9
-- | -- | -- | --
Kompiliert gegen Qt | 5.11.2 | Laufendes Qt | 5.11.2
Kompiliert mit GDAL/OGR | 3.1.4 | Läuft mit GDAL/OGR | 3.1.4
Kompiliert mit GEOS | 3.8.1-CAPI-1.13.3 | Läuft mit GEOS | 3.8.1-CAPI-1.13.3
Kompiliert mit SQLite | 3.29.0 | Läuft mit SQLite | 3.29.0
PostgreSQL-Client-Version | 11.5 | SpatiaLite-Version | 4.3.0
QWT-Version | 6.1.3 | QScintilla2-Version | 2.10.8
Kompiliert mit PROJ | 6.3.2 | Läuft mit PROJ | Rel. 6.3.2, May 1st, 2020
BS-Version | Windows 10 (10.0)
Aktive Python-Erweiterungen | db_manager; MetaSearch; processing

</body></html>

### Additional context

[widget-settings-for-joined-fields.zip](https://github.com/qgis/QGIS/files/7008711/widget-settings-for-joined-fields.zip)

**Comment by gioman** [comment]
Confirmed on master/linux too.

**Comment by nyalldawson** [comment]
Duplicate of https://github.com/qgis/QGIS/issues/44768
