### ISSUE TITLE
Mbtiles - tiles missing on different zoom levels

### ISSUE THREAD

**Issue by IAmHereAtGithub** [qgis/QGIS#44750]
### What is the bug or the crash?

On the rendered mbtiles there are missing tiles or fragments, sometimes overlapping.

### Steps to reproduce the issue

1. Used 3.20.2-Odense QGIS-Codeversion 9f59a156.
2. Used 'freehand raster georeferencer' to add 5 different .png .
3. Used 'freehand raster georeferencer' with scaling, moving, etc. to fit it above the OSM map.
4. Blend out OSM map.
5. Used 'Raster tools' 'Generate XYZ tiles (MBTILES)' to generate the .mbtiles .
6. Used Extent = Use map canvas extend; min zoom = 12; max zoom = 23, Tile format = png; Save to file ... ; the rest leave default.
7. After the .mbtiles rendering I open it with Tile Server

For example,
Zoom 16 is correct
![TileServer_Zoom16](https://user-images.githubusercontent.com/89143144/129914199-0961843d-0a40-4eaf-92a9-94139753e692.png)
Zoom 17, tiles are missing
![TileServer_Zoom17](https://user-images.githubusercontent.com/89143144/129914193-5d39d325-897b-4102-a47d-0ef736f6404b.png)
Zoom 18 is correct
![TileServer_Zoom18](https://user-images.githubusercontent.com/89143144/129914197-0b3195ac-75ba-496a-9eb2-b2a4a714e186.png)

The same can be seen, if I open the .mbtiles with QGIS again.

I used other QGIS Versions before (3.16.7 / 3.14.16) with the same effect.
If I use different map canvas extent or parameters, the tiles missing on other zoom levels or I have overlaps.

### Versions

QGIS version
3.20.2-Odense
QGIS code revision
9f59a156
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.1
PROJ version
8.1.0
EPSG Registry database version
v10.027 (2021-06-17)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
FreehandRasterGeoreferencer
numericalDigitize
QMetaTiles
quick_map_services
VectorBender
db_manager
MetaSearch
processing

**Comment by gioman** [comment]
@IAmHereAtGithub can you link/attach the file?

> After the .mbtiles rendering I open it with Tile Server

are tiles missing also when using QGIS as viewer?

**Comment by IAmHereAtGithub** [comment]
I can´t attach the original .mbtiles, cause it is customer data.
But I can provide this samples .mbtiles:
[samples.zip](https://github.com/qgis/QGIS/files/7010356/samples.zip)

When I use the QGIS as viewer, at a scale of 1:12956 tiles disappear:
![sample0](https://user-images.githubusercontent.com/89143144/129976270-2e067421-d11a-466a-b848-3e02f3917eb4.png)
![sample1](https://user-images.githubusercontent.com/89143144/129976264-492b1969-a1ab-412f-aff1-799df550a942.png)
![sample2](https://user-images.githubusercontent.com/89143144/129976268-fba1f93f-b01e-46a5-a5ca-7496ac0f005d.png)

**Comment by gioman** [comment]
@IAmHereAtGithub seems the width of the canvas is related, can you confirm?

![Peek 2021-08-19 12-01](https://user-images.githubusercontent.com/1951107/130057923-7735a748-5e0b-4b5d-b82f-1b568cf10e62.gif)

**Comment by IAmHereAtGithub** [comment]
@gioman Yes, I can confirm the behavior you recorded with my QGIS too.

**Comment by IAmHereAtGithub** [comment]
Update:
I use now as a workaround the QGIS 3.20.2 on an Ubuntu system (in hyper-v) which creates .mbtiles correctly.

**Comment by alexbruy** [comment]
Can you test with the latest master? The algorithm recently was ported to C++.
