### ISSUE TITLE
Missing CP949(Korean) encoding at Export Project to DXF menu

### ISSUE THREAD

**Issue by Tom-2** [qgis/QGIS#44756]
### What is the bug or the crash?

There's no CP949(Korean) and UTF-8 encoding at [Export Project to DXF] menu at QGIS 3.16.10. That encoding was there at QGIS 3.10.14. But silently disappeared without any reason. It happened before. See [this github issue](https://github.com/qgis/QGIS/issues/28657?utm_source=pocket_mylist#issue-448448161).

Can anyone fix this issue?

### Steps to reproduce the issue

go to Project > Export Project to DXF menu.

### Versions

QGIS 버전
3.16.10-Hannover
QGIS 코드 리버전
e5b665e9
컴파일시 사용된 Qt
5.15.2
다음 Qt를 이용해서 실행 중입니다
5.15.2
컴파일시 사용된 GDAL/OGR
3.3.1
다음 GDAL/OGR을 이용해서 실행 중입니다
3.3.1
컴파일시 사용된 GEOS
3.9.1-CAPI-1.14.2
다음 GEOS를 이용해서 실행 중입니다
3.9.1-CAPI-1.14.2
SQLite 호환 컴파일
3.35.2
SQLite 호환 실행
3.35.2
PostgreSQL 클라이언트 버전
13.0
SpatiaLite 버전
5.0.1
QWT 버전
6.1.3
QScintilla2 버전
2.11.5
컴파일시 사용된 PROJ
8.1.0
다음 PROJ를 이용해서 실행 중입니다
Rel. 8.1.0, July 1st, 2021
OS 버전
Windows 10 Version 2009
파이썬 플러그인 활성
tmsforkorea; 
db_manager; 
MetaSearch; 
processing

**Comment by agiudiceandrea** [comment]
It seems an issue related to the Qt library version (5.15.2) shipped with the new (v2/msi) OSGeo4W installers, and not with a particular QGIS version.

The same QGIS 3.16.10 version, but installed using the old (v1/exe) OSGeo4W, doesn't suffer of the reported issue.

**QGIS 3.16.10 new (v2/msi) OSGeo4W (Qt 5.15.2)**:
14 codecs listed, CP949 missing, ISO-8859-1 listed two times
```python
QgsDxfExport.encodings()
['ISO-8859-1', 'ISO-8859-1', 'ISO-8859-2', 'ISO-8859-3', 'ISO-8859-4', 'ISO-8859-5', 'ISO-8859-6', 'ISO-8859-7', 'ISO-8859-8', 'ISO-8859-9', 'Shift_JIS', 'Big5', 'CP936', 'GB2312']
```

**QGIS 3.16.10 old (v1/exe) OSGeo4W (Qt 5.11.2)**:
28 codecs listed, CP949 present
```python
QgsDxfExport.encodings()
['ISO-8859-1', 'Big5', 'CP950', 'CP949', 'Shift_JIS', 'GB2312', 'CP936', 'MacRoman', 'CP1258', 'CP1257', 'CP1256', 'CP1255', 'CP1254', 'CP1253', 'CP1252', 'CP1251', 'CP1250', 'CP866', 'CP874', 'CP850', 'ISO-8859-9', 'ISO-8859-8', 'ISO-8859-7', 'ISO-8859-6', 'ISO-8859-5', 'ISO-8859-4', 'ISO-8859-3', 'ISO-8859-2']
```

**Comment by Tom-2** [comment]
I hope there was CP949 at least in msi version. 

How do I add it? I'm not familiar with development. Can anyone add it on behalf? I would appreciate it.

**Comment by agiudiceandrea** [comment]
> I hope there was CP949 at least in msi version. 

@Tom-2 you need to install QGIS 3.16 using the old v1/exe installers.

**Comment by Tom-2** [comment]
But there is no dependency update isn't it? That's why I want to use msi installer 😥

**Comment by agiudiceandrea** [comment]
@Tom-2 please see if the workaround I suggested to an user in the qgis-user mailing list https://lists.osgeo.org/pipermail/qgis-user/2021-November/050121.html could be of some help also for you.

**Comment by agiudiceandrea** [comment]
@Tom-2 please see if the workaround I suggested to an user in the qgis-user mailing list https://lists.osgeo.org/pipermail/qgis-user/2021-November/050126.html could be of some help also for you.

**Comment by Tom-2** [comment]
Thank you so much!!!! It works!!!!

God bless you!

**Comment by Tom-2** [comment]
There's a problem. When I go to  Help > version check, there comes SSL error. :(

**Comment by agiudiceandrea** [comment]
@Tom-2  I think the two issue are completely not related. Anyway you can restore the file backup or modify again the file.

**Comment by Tom-2** [comment]
Yeah. Thank you for the help! I'll test it with another PC tomorrow.

**Comment by borysiasty** [comment]
I'm sure there was never UTF-8 on that list, as it has nothing to do with that DXF version.
