### ISSUE TITLE
QGIS crashes when opening the attribute table of a layer that has a join

### ISSUE THREAD

**Issue by troyaqgis** [qgis/QGIS#44768]
## User Feedback

After adding fields from a join to the form and opening the attribute table, qgis stops working. Attribute table hangs and QGIS crashed window pops up.

## Report Details

**Crash ID**: [bee67f0f695c76d03041dc30002ddb99f52be41e](https://github.com/qgis/QGIS/search?q=bee67f0f695c76d03041dc30002ddb99f52be41e&type=Issues)

**Stack Trace**
<pre>
QLineEdit::setPlaceholderText :
QgsAttributeForm::changeAttribute :
QgsAttributeForm::updateJoinedFields :
QgsAttributeForm::onAttributeChanged :
QObject::qt_static_metacall :
QgsEditorWidgetWrapper::valuesChanged :
QgsExternalResourceWidgetWrapper::createWidget :
QObject::qt_static_metacall :
QLineEdit::qt_static_metacall :
QObject::qt_static_metacall :
QWidgetLineControl::finishChange :
QWidgetLineControl::internalSetText :
QgsTextEditWrapper::setWidgetValue :
QgsEditorWidgetWrapper::setValue :
QgsTextEditWrapper::setFeature :
QgsAttributeForm::resetValues :
QgsAttributeForm::setFeature :
QgsAttributeForm::QgsAttributeForm :
QgsDualView::initAttributeForm :
QObject::qt_static_metacall :
QgsFeatureListView::currentEditSelectionChanged :
QgsFeatureListView::editSelectionChanged :
QObject::qt_static_metacall :
QItemSelectionModel::emitSelectionChanged :
QItemSelectionModel::select :
QItemSelectionModel::select :
QgsFeatureListView::QgsFeatureListView :
QObject::qt_static_metacall :
QTimer::timerEvent :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.20.0-Odense
QGIS code revision: decaadbb31
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.0
Running against GDAL: 3.3.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

### Steps to reproduce the issue

1. go to Layer Proerties (layer name:  **l**  or **a**)
2. add Join
![1](https://user-images.githubusercontent.com/36294360/130051205-2871a9e9-4029-4b8a-be7d-bdbfa9cdac8d.png)

3. go to Attributes Form, select Drag and Drop Designer, add joined fields to form Layout
![2](https://user-images.githubusercontent.com/36294360/130051233-13246098-60f3-48ce-bffc-2ef86c43c9f5.png)

4. save changes
5. go to Attribute Table
6. Attribute Table not answered
![3](https://user-images.githubusercontent.com/36294360/130051266-58774024-7c0c-426f-b4e1-60b9b858cba6.png)

7. QGIS crashed 
![4](https://user-images.githubusercontent.com/36294360/130051298-ca51fdd7-ce20-449a-a02a-65ad9083881c.png)

8. After delete join fields from Form it's OK. (checked on layer: **p**)

### Versions

**QGIS Info**
QGIS Version: 3.20.0-Odense
QGIS code revision: decaadbb31
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.0
Running against GDAL: 3.3.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

### Additional context

x

**Comment by gioman** [comment]
@troyaqgis please try with a new QGIS profile, no 3rd party plugins installed. If the problem persist please attach a sample project + data we can use to try replicate the issue.

**Comment by troyaqgis** [comment]
I tested on a new profile with no plugins installed and problem hasn't been resolved.
How can I attach project and data? I can't attach zip file (error message: "is not included in the list" )

**Comment by gioman** [comment]
> I can't attach zip file 

@troyaqgis you can indeed attach ZIP files here, be sure is really a zip (and not another compressed format with just a zip extension).

**Comment by troyaqgis** [comment]
I still have a problem with uploading the zip. Can I share a file using dropbox transfer?

**Comment by gioman** [comment]
> Can I share a file using dropbox transfer?

@troyaqgis yes

**Comment by troyaqgis** [comment]
[dropbox transfer](https://www.dropbox.com/t/kqDXN8gpizPahlsb)

**Comment by gioman** [comment]
> * go to Attribute Table
> 
> * Attribute Table not answered

Confirmed crash when opening the table of attributes of the described layer. QGIS master/linux.
