### ISSUE TITLE
Polygonize algorithm outputs only NULL values in attribute table

### ISSUE THREAD

**Issue by raymondnijssen** [qgis/QGIS#44779]
### What is the bug or the crash?

When running the Polygonize algorithm on a line layer with the option Keep Fields, the fields are added to the result but the table only contains NULL values. Tested on 3.21, 3.20 and 3.16 and confirmed by someone else.

### Steps to reproduce the issue

1. Open line layer
2. Processing > Polygonize (the QGIS algorithm) 
3. Choose line layer
4. Check "Keep fields"
5. Run
6. Open attribute table of the result 

### Versions

3.16, 3.20, 3.21

### Additional context

Algorithm log:

QGIS version: 3.21.0-Master
QGIS code revision: d16d76155e
Qt version: 5.12.8
Python version: 3.8.10
GDAL version: 3.0.4
GEOS version: 3.8.0-CAPI-1.13.1 
PROJ version: Rel. 6.3.1, February 10th, 2020
Processing algorithm…
Algorithm 'Polygonize' starting…
Input parameters:
{ 'INPUT' : '/home/raymond/tmp/range_lines.gpkg|layername=range_lines', 'KEEP_FIELDS' : True, 'OUTPUT' : 'ogr:dbname=\'/home/raymond/tmp/range_polys.gpkg\' table=\"output\" (geom)' }

Collecting lines…
Noding lines…
Polygonizing…
Execution completed in 0.09 seconds
Results:
{'NUM_POLYGONS': 5,
'OUTPUT': '/home/raymond/tmp/range_polys.gpkg|layername=output'}

Loading resulting layers
Algorithm 'Polygonize' finished

**Comment by raymondnijssen** [comment]
[range_lines.zip](https://github.com/qgis/QGIS/files/7019743/range_lines.zip)

This is the zipped gpkg with the lines I used

**Comment by eemilhaa** [comment]
Was able to reproduce this with 3.21 nightly on Linux (Ubuntu/pop_os 21.04)

**Comment by agiudiceandrea** [comment]
It seems this is by design and it's the very algorithm behaviour since its introduction (QGIS 2.0).
The KEEP_FIELD parameter does what it says to do: "Keep fields from the input layer" (i.e. it only keeps the table structure of the input layer).
Anyway the algorithm documentation incorrectly states: "Check to copy the original attributes of the input layer".

**Comment by raymondnijssen** [comment]
Yes, it's a bit of bummer to realize this "Hey, we only promised you to keep the fields, not the values"... :)

Now it might be hard to program this as a polygon can be based on many lines. But a good guess should be using the outer of the polygon for values, in case this is made of one linestring. (Think building contours, lake sides)

**Comment by agiudiceandrea** [comment]
@raymondnijssen please consider this situation:

![image](https://user-images.githubusercontent.com/16253859/130224958-feeb26de-2035-48f0-8057-11d2c869869b.png)

The "Polygonize" algorithm will create an output layer containing 3 polygon features (A, B, C) from the 2 lines features (1, 2) contained in the input layer: so, it is not always possible to bijectively copy the attributes values of the features in the input layer to the features in the output layer.

Instead, the "Lines to polygons" algorithm will create 2 polygon features from the 2 lines features, so it is possible to copy the attributes values from input layer to the output layer.

**Comment by raymondnijssen** [comment]
Thanks for explaining and @agiudiceandrea, I never knew about the difference between Polygonize and Lines to Polygons.

"... so, it is not always possible to bijectively copy the attributes values of the features in the input layer to the features in the output layer."
I understand, but in some cases it could be possible. For example:
- The polygon's outer is constructed from 1 line
- The polygon is constructed from multiple lines, but some(or all) attributes have the same value
- Pick the value from the longest line (would be more tricky)
- Pick the value from any line (would be more more tricky)

To be honest, I cannot think of a use case where these empty fields would be handy. But as someone added this option, it probably is. To prevent disappointments I added "(empty)" to the description in the GUI:

https://github.com/qgis/QGIS/pull/44809

**Comment by agiudiceandrea** [comment]
> Anyway the algorithm documentation incorrectly states: "Check to copy the original attributes of the input layer".

Docs changed to: "Check to keep the fields (only the table structure, not the values) of the input layer". https://github.com/qgis/QGIS-Documentation/pull/6891
