### ISSUE TITLE
getFeatures(layer) for loop crashes QGIS

### ISSUE THREAD

**Issue by grshennan** [qgis/QGIS#44777]
### What is the bug or the crash?

`weather_l` is a point shapefile layer with 145460 records. This:

```
n = 0
with edit(weather_l):
    for fea in weather_l.getFeatures():
        n += 1
        print(n)
```
causes QGIS to crash after a couple thousand iterations. This:
```
n = 0
with edit(weather_l):
    for fea in weather_l.getFeatures():
        n += 1
print(n)
```
works fine. I've been trying to calculate a field in the shapefile but getting crashes and stripped the problem down to this.

### Steps to reproduce the issue

[Here](https://drive.google.com/file/d/1WJfbK2gN3zse6lguaXaoatMJh9cgYds9/view?usp=sharing) is the csv file I'm using. Below is the code I used to import the csv, convert it to shapefile and add a field. If you change `data_path` to the location of the csv file, run this code and then run the for loop codes (in the problem description) that should reproduce the problem.

```
# Change this to suit
data_path = 'D:\\SPA452Programming\\A2\\5.InterpWeather\\'

# Csv filename has formatting options required for csv import
data_filename_csv = "stations_weather_join.csv?delimiter={}&xField={}&yField={}".format(",", "Lon", "Lat")
data_filename_shp = "weather.shp"

# Load weather csv
weather_l = QgsVectorLayer('file:///' + data_path + data_filename_csv, "weather", "delimitedtext")

# The layer is imported with no crs set, so set it
weather_l.setCrs(QgsCoordinateReferenceSystem(4326, QgsCoordinateReferenceSystem.EpsgCrsId))

# But csv source files are not editable. Need to first save the file as .shp
QgsVectorFileWriter.writeAsVectorFormat(weather_l, data_path + data_filename_shp, "UTF-8", weather_l.crs(), "ESRI Shapefile", layerOptions=['SHPT=POINT'])

# Now re-load the weather data as shapefile and add to map
weather_l = QgsVectorLayer(data_path + data_filename_shp, "Weather Data", "ogr")
QgsProject.instance().addMapLayer(weather_l)

# Add the extra column to the attribute table
vl = weather_l.dataProvider()
vl.addAttributes([QgsField("Rain_D", QVariant.Double)])
weather_l.updateFields()
```

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.16.2-Hannover | QGIS code revision | f1660f9da5
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | gis_cloud_publisher; ImportPhotos; lizmap; qfieldsync; qgis2web; qgiscloud; quick_map_services; db_manager; MetaSearch; processing

</body></html>

### Additional context

First bug report, at the [recommendation](https://gis.stackexchange.com/questions/408731/qgis-python-update-field-crashes-when-in-for-loop) of GIS Stack Exchange. Hope I got it right.

**Comment by gioman** [comment]
> 3.16.2-Hannover 

@grshennan this is slightly old, can you test on the latest point release?

**Comment by nicogodet** [comment]
It crashes (you see the "Uh-OH") or Qgis just hangs ?

I notice that printing too frequently to Console (your `print()`) freeze Qgis after some iteration

**Comment by grshennan** [comment]
> It crashes (you see the "Uh-OH") or Qgis just hangs ?
> 
> I notice that printing too frequently to Console (your `print()`) freeze Qgis after some iteration

Hangs, sorry. I wasn't trying to print to the console, that's just a minimum working example. The actual code is:
```
with edit(weather_l):
    for fea in weather_l.getFeatures():
        context.setFeature(fea)
        if fea['Rainfall'].isalpha():
            fea['Rain_D'] = num_zero.evaluate(context)
            print('num_zero')
        else:
            print(num_float.evaluate(context))
            fea['Rain_D'] = num_float.evaluate(context)
        f['Rain_D'] = num_zero.evaluate(context) if f['Rainfall'].isalpha() else num_float.evaluate(context)
        weather_l.updateFeature(fea)
```
The above probably doesn't work, I'm still trying to finish it. But it if it gets into the if statements it hangs too. It's fine if I put in a break statement to stop it after a few iterations.

**Comment by grshennan** [comment]
> 
> 
> > 3.16.2-Hannover
> 
> @grshennan this is slightly old, can you test on the latest point release?

Will do

**Comment by nicogodet** [comment]
I think it hangs because of print() 
Try without

**Comment by grshennan** [comment]
> 
> 
> I think it hangs because of print()
> Try without

Yeah, I already did, that's what's in the second code example in the bug description. My problem is I can't seem to get it to do anything in the for loop more than a couple thousand times.

**Comment by nicogodet** [comment]
QGis hangs but it will process all the features.
You will get the full print at the end

**Comment by grshennan** [comment]
@gioman, okay I updated and it's getting through the loop now, as long as I don't use the print commands. Brilliant, thanks.

**Comment by nicogodet** [comment]
@gioman BTW is this a known behavior ?
