### ISSUE TITLE
Deleted field referenced in conditional formatting rule causes crash

### ISSUE THREAD

**Issue by edisondotme** [qgis/QGIS#44774]
### What is the bug or the crash?

I think I know what happened. I created a conditional formatting rule using a certain field, then I turned on editing on the layer, deleted the field, and then tried to access the conditional formatting rule to delete it, but when I opened conditional formatting, QGIS locked up and I had to kill it.

### Steps to reproduce the issue

1.) make a conditional formatting rule
2.) Delete the column that the conditional formatting rule referenecs
3.) Try to open conditional formatting rules 

### Versions

**QGIS Info**
QGIS Version: 3.20.2-Odense
QGIS code revision: 9f59a156
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.1
Running against GDAL: 3.3.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

## User Feedback

I think I know what happened. I created a conditional formatting rule using a certain field, then I turned on editing on the layer, deleted the field, and then tried to access the conditional formatting rule to delete it, but when I opened conditional formatting, QGIS locked up and I had to kill it.

This is while working in the attribute table.

I had some field that were the result of a table join as well.

## Report Details

**Crash ID**: [9e6394a4c5c46e90df11b6a88a73e9986e90908e](https://github.com/qgis/QGIS/search?q=9e6394a4c5c46e90df11b6a88a73e9986e90908e&type=Issues)

**Stack Trace**
<pre>
QgsConditionalStyle::QgsConditionalStyle :
QgsFieldConditionalFormatWidget::ruleClicked :
QObject::qt_static_metacall :
QAbstractItemView::mouseReleaseEvent :
QListView::mouseReleaseEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**Comment by gioman** [comment]
> 1.) make a conditional formatting rule
> 2.) Delete the column that the conditional formatting rule referenecs
> 3.) Try to open conditional formatting rules 

@edisondotme I tested with a PostGIS vector, and after deleting the column used to create the rule the rule itself do not show anymore in the formatting options.

**Comment by edisondotme** [comment]
I see, then it must have been some other set of precursor circumstances. I
don't know how to reproduce it then.
