### ISSUE TITLE
v.clean rmdupl tool does not remove duplicates.

### ISSUE THREAD

**Issue by NicolasCadieux** [qgis/QGIS#44775]
### What is the bug or the crash?

In processing, the v.clean rmdupl tool  finds but does not remove the duplicate geometries.  Tested with linestrings.

### Steps to reproduce the issue

Simply open processing, select the v.clean, a vector file with a simple two node line and use the rmdupl tool.  The duplicate geometry is identified in the "Errors files" but is still present in the "Cleaned" output file.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.20.1-Odense | QGIS code revision | 1c3c5cd6
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.1
PROJ version | 8.1.0
EPSG Registry database version | v10.027 (2021-06-17)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins | GroupPointsWithinDistancedb_managerMetaSearchprocessing

</body></html>

Same in LTL 3.16.9

**Comment by gioman** [comment]
@NicolasCadieux tested in native GRASS and the result is the same. It may be a GRASS issue or maybe the necessity of using some specific parameter/tolerance for this specific cleaning tool. Either way it does not seems a QGIS/Processing issue.

**Comment by NicolasCadieux** [comment]
Not a parameter thing."Threshold does not apply (it is ignored), use an arbitrary value (e.g., 0) if v.clean is run with several tools." According to v.clean help file. Should we file a bug report in Grass?

**Comment by gioman** [comment]
> Should we file a bug report in Grass?

@NicolasCadieux at least should be asked in one of their lists/channels.
