### ISSUE TITLE
Unable to Unzip file .qgz

### ISSUE THREAD

**Issue by tyanitaputi** [qgis/QGIS#44785]
### What is the bug or the crash?

Hi,

I created project and saved it to gqz file. I managed to open it two days ago, saved and closed it properly. 
But today, I cannot open it. When I load the project using Project/Open menu, the status is project loaded but nothing appears on my screen so do the layers. I tried to open using Browser window, and it said Unable to unzip file '/dir/aaa.qgz'

Please help to fix this crash. 
Thank you very much in advanced. 

### Steps to reproduce the issue

Unable to unzip file '/dir/aaa.qgz'

### Versions

QGIS version
3.16.0-Hannover
QGIS code revision
43b64b13f3
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
attributeBasedClustering; 
BOS; 
BufferByPercentage; 
easy_processing_tool; 
excel_sync; 
MultiDistanceBuffer; 
realcentroid; 
db_manager; 
MetaSearch; 
processing

**Comment by Gustry** [comment]
> QGIS version
> 3.16.0-Hannover

The latest 3.16 is 3.16.10, you should upgrade, there are a lot of bug fix since this 3.16.0
https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule

**Comment by tyanitaputi** [comment]
T

> > QGIS version
> > 3.16.0-Hannover
> 
> The latest 3.16 is 3.16.10, you should upgrade, there are a lot of bug fix since this 3.16.0
> https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule

I upgraded to version 3.16.10 but I still have the problem. 
Do you have another solution?

**Comment by tyanitaputi** [comment]
> > QGIS version
> > 3.16.0-Hannover
> 
> The latest 3.16 is 3.16.10, you should upgrade, there are a lot of bug fix since this 3.16.0
> https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule

I upgraded to version 3.16.10 but I still have the problem.
Do you have another solution?

**Comment by gioman** [comment]
>  and it said Unable to unzip file '/dir/aaa.qgz'

@tyanitaputi can you unzip the .qgz file with a program like unzip/winrar ?

**Comment by tyanitaputi** [comment]
> > and it said Unable to unzip file '/dir/aaa.qgz'
> 
> @tyanitaputi can you unzip the .qgz file with a program like unzip/winrar ?

I can't. "The archieve is either unknown format or damage"
Does it mean that the file is corrupt?
If yes, is there any way to repair then?

**Comment by gioman** [comment]
>  Does it mean that the file is corrupt?

@tyanitaputi yes



>  If yes, is there any way to repair then?

you may want to try any method could work for a generic corrupted file/zip, but I don't think QGIS itself can do anything here.

**Comment by Gustry** [comment]
It doesn't mean the file is corrupted. Maybe it's just the software not recognising a qgz extension. Can you rename first to zip. The software might just rely on the extension which it doesn't know about qgz.
