### ISSUE TITLE
Feature counter shows 1000 feature for empty gpkg layer

### ISSUE THREAD

**Issue by troyaqgis** [qgis/QGIS#44780]
### What is the bug or the crash?

Feature counter shows 1000 feature for empty gpkg layer. 

### Steps to reproduce the issue

Feature counter shows 1000 feature for empty gpkg layer (layer name: a). For the other layers from the same gpkg, the number of features is correct. I checked the number of features in python and sql. the results can be seen in the screenshots. 

![1](https://user-images.githubusercontent.com/36294360/130204230-e51b37f5-5e88-499f-8522-a80082a47df0.png)
![2](https://user-images.githubusercontent.com/36294360/130204236-7ebe7453-e16e-4d82-8efd-3ed832c2ffec.png)
![3](https://user-images.githubusercontent.com/36294360/130204239-3bed8d30-5165-4e0f-bf72-c45513789b3a.png)
![4](https://user-images.githubusercontent.com/36294360/130204246-ece5be3b-8bb2-406e-a386-18699cf28dcf.png)
![5](https://user-images.githubusercontent.com/36294360/130204249-6b0821fc-5ac8-437f-a576-96975c46e938.png)
![6](https://user-images.githubusercontent.com/36294360/130204251-b9917b8f-3e81-4339-8278-0c3cc72d8606.png)
![7](https://user-images.githubusercontent.com/36294360/130204252-2a96b0b5-dab8-40a0-bde2-0d835f8198c5.png)

Data and project: https://www.dropbox.com/t/SSfN4AMrqWdVQhvS

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.20.2-Odense | QGIS code revision | 9f59a156
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.1
PROJ version | 8.1.0
EPSG Registry database version | v10.027 (2021-06-17)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2004
  |   |   |  
Active Python plugins | db_manager

</body></html>

**Comment by gioman** [comment]
@troyaqgis ogrinfo shows also 1000 feature count, so if any do no seems a QGIS issue:

```
ogrinfo -so dzUrz.gpkg a
INFO: Open of `dzUrz.gpkg'
      using driver `GPKG' successful.

Layer name: a
Geometry: Polygon
Feature Count: 1000
Layer SRS WKT:
PROJCRS["ETRS89 / Poland CS92",
    BASEGEOGCRS["ETRS89",
        DATUM["European Terrestrial Reference System 1989",
            ELLIPSOID["GRS 1980",6378137,298.257222101,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4258]],
    CONVERSION["Poland CS92",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",19,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9993,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",500000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",-5300000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["northing (x)",north,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["easting (y)",east,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["unknown"],
        AREA["Poland"],
        BBOX[49,14.14,55.93,24.15]],
    ID["EPSG",2180]]
Data axis to CRS axis mapping: 2,1
FID Column = fid
Geometry Column = geom
kategoria: String (50.0)
klasa: String (9.0)
klasaKodSkr: String (4.0)
obiekt: String (100.0)
rodzajZmiany: String (50.0)
opisZmiany: String (100.0)
data: DateTime (0.0)
autor: String (25.0)
zrodlo: String (50.0)
eli: String (25.0)
```

**Comment by pathmapper** [comment]
I'm having the same issue (Feature Count for a layer is not matching number of features) with a GPKG created by QGIS, see https://github.com/OSGeo/gdal/issues/4256, but can't reproduce currently. 

From @rouault's comment in https://github.com/OSGeo/gdal/issues/4256#issuecomment-900956122

> The reading side of the GPKG driver behaves fine. It uses the special gpkg_ogr_contents table that is supposed to maintain the number of features up-to-date, and this table advertizes 24 feature for the data table. So a corruption occurred before. Normally this shouldn't happen as there are triggers which maintain the feature count in gpkg_ogr_contents consistent with rows addition/deletion in the data tables.


`gpkg_ogr_contents` table of the GPKG which is provided for this issue:
![image](https://user-images.githubusercontent.com/20856381/130284587-02803280-3bdb-497f-bcdf-2a874446c384.png)


@troyaqgis did you create the GPKG with QGIS, and if yes, are you able to describe how to reproduce this issue?

**Comment by troyaqgis** [comment]
@pathmapper I'm afraid I won't be able to reproduce it. This probably happened on the copied gpkg file created with QGIS, when deleting all features on this layer.
