### ISSUE TITLE
Crash when try to add a ArcGis Map Service

### ISSUE THREAD

**Issue by EriC-Castell** [qgis/QGIS#44784]
## User Feedback

I was trying to add an ArcGis Map Service, then QGIS end unexpectedly.

## Report Details

**Crash ID**: [98f437068e142ab10ad20525f2210b612c74ef53](https://github.com/qgis/QGIS/search?q=98f437068e142ab10ad20525f2210b612c74ef53&type=Issues)

**Stack Trace**
<pre>
QgsAnnotation::appearanceChanged :
QgsCoordinateTransform::transformPolygon :
osgeo::proj::datum::Datum::conventionalRS :
osgeo::proj::datum::Datum::conventionalRS :
_CallSettingFrame handlers.asm:50
__FrameHandler3::CxxCallCatchBlock frame.cpp:1480
RcConsolidateFrames :
osgeo::proj::datum::Datum::conventionalRS :
QgsDatumTransform::transformDetailsFromPj :
QgsDatumTransform::operations :
QgsCoordinateOperationWidget::setDestinationCrs :
QgsDatumTransformDialog::QgsDatumTransformDialog :
QgsDatumTransformDialog::run :
QgisApp::askUserForDatumTransform :
QgisApp::addRasterLayer :
QgisApp::addRasterLayerPrivate :
QgisApp::handleDropUriList :
QgsPluginRegistry::operator= :
QgisApp::identify :
QMetaObject::activate :
QTimer::timerEvent :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32Private::sendTimerEvent :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.16.1-Hannover
QGIS code revision: b381a90dca
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.14393

### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/89274031/130279028-0f4e8f7c-995f-4c58-a7fd-e9cbf0e5755a.png)

### Versions

Versión de QGIS
3.16.1-Hannover
Revisión del código de QGIS
b381a90dca
Compilado contra Qt
5.11.2
Ejecutándose contra Qt
5.11.2
Compilado contra GDAL/OGR
3.1.4
Ejecutándose contra GDAL/OGR
3.1.4
Compilado contra GEOS
3.8.1-CAPI-1.13.3
Ejecutándose contra GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
Versión del cliente PostgreSQL
11.5
Versión de SpatiaLite
4.3.0
Versión de QWT
6.1.3
Versión de QScintilla2
2.10.8
Compilado contra PROJ
6.3.2
Ejecutándose contra PROJ
Rel. 6.3.2, May 1st, 2020
Versión del SO
Windows 10 (10.0)
Active python plugins
qgiscloud; 
quick_map_services; 
SocialActivity; 
db_manager; 
MetaSearch; 
processing

**Comment by gioman** [comment]
>  3.16.1-Hannover 

@EriC-Castell too old, please try with the latest point release. If the problem persist please try with a new QGIS profile, no 3rd party plugins installed. If still persist add the URL of the service.
