### ISSUE TITLE
Regression attachment widget can't set "Relative paths"

### ISSUE THREAD

**Issue by domi4484** [qgis/QGIS#44799]
### What is the bug or the crash?

In the attachment widget configuration the state of the checkbox "Relative paths" it is not remembered.
@troopa81 Maybe introduced there b1fa33386f23a40c1863369a836db03510295b2a?

![Peek 2021-08-23 10-32](https://user-images.githubusercontent.com/9881900/130416528-edcdc01c-86c8-42b3-b720-bf3c33f83df6.gif)

### Steps to reproduce the issue

1. Create a layer with a text field
2. In layer properties choose "Attachment" for the text field
3. Check "Relative paths" checkbox
4. Close/reopen layer properties
5. Checkbox is not set anymore

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.21.0-Master | QGIS code revision | f9b18e453d
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.8.10
GDAL/OGR version | 3.3.0
PROJ version | 7.2.1
EPSG Registry database version | v10.008 (2020-12-16)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.5
PostgreSQL client version | 13.3
SpatiaLite version | 4.3.0a
QWT version | 6.1.6
QScintilla2 version | 2.11.6
OS version | openSUSE Tumbleweed
  |   |   |  
This copy of QGIS writes debugging output.
  |   |   |  
Active Python plugins | plugin_reloaderquick_map_servicesshlocatordocument_management_systemQgisModelBakerfirstaidprocessingsagaprovidergrassproviderMetaSearchdb_manager

</body></html>

**Comment by troopa81** [comment]
> @troopa81 Maybe introduced there b1fa333?

Right! thanks for reporting
