### ISSUE TITLE
QGIS crashes if adding a layer from ODBC:Vertica

### ISSUE THREAD

**Issue by hamzagurani** [qgis/QGIS#44803]
### What is the bug or the crash?

When ı try to get connection with qgis and vertica through to odbc it says "connection successful".However when ı try to add layers it gives error.

"Sorry :( It looks something unexpected happened that we didn't handle and QGIS ended unexpectedly.

Crash ID: 39e7e534ad9887eaa0e6fd32b02eacc834d4b55

## User Feedback

When ı try to get connection with qgis and vertica through to odbc it says "connection successful".However when ı try to add layers it gives error.

## Report Details

**Crash ID**: [39e7e534ad9887eaa0e6fd32b02eacc834d4b55a](https://github.com/qgis/QGIS/search?q=39e7e534ad9887eaa0e6fd32b02eacc834d4b55a&type=Issues)

**Stack Trace**
<pre>
memcpy_repmovs memcpy.asm:114
CPLODBCStatement::Fetch :
SBNSearchFreeIds :
SBNSearchFreeIds :
QgsOgrProviderUtils::GDALOpenWrapper :
QgsOgrProviderUtils::GDALOpenWrapper :
QgsOgrProviderUtils::setSubsetString :
QgisApp::addVectorLayersPrivate :
QgisApp::addVectorLayers :
QgisApp::qt_static_metacall :
QObject::qt_static_metacall :
QgsDataSourceManagerDialog::addVectorLayers :
QObject::qt_static_metacall :
QgsAbstractDataSourceWidget::addVectorLayers :
QgsProjectStorageGuiProvider::QgsProjectStorageGuiProvider :
QObject::qt_static_metacall :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.16.10-Hannover
QGIS code revision: e5b665e9
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.1
Running against GDAL: 3.3.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

### Steps to reproduce the issue

1)Click Layer
2)Choose Datasource Manager
3)Click Vector
4)Choose Database 
5)Check vertica database connection which is work
6)Click Add

### Versions

QGIS 3.16.10

**Comment by gioman** [comment]
@hamzagurani any chance you can provide a test connection to such database?

**Comment by hamzagurani** [comment]
Yes ı can, could you provide your communication information by e-mail guraniakbulut@gmail.com
