### ISSUE TITLE
Windows on VMWare desktops show: 'Oops...could not load qgis_app.dll' after Windows Security update

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS#44806]
### What is the bug or the crash?

'we' have a set of Virtual Desktops (on top of VMware) on which QGIS 3.16 is installed. All running fine (installed in may/juni using QGIS-OSGeo4W-3.16.7-1-Setup-x86_64.exe).

BUT after a (bigger?) Windows Security update, QGIS does not start anymore. It shows this (pretty familiar) dialog:

![Screenshot-20210823145505-397x263](https://user-images.githubusercontent.com/731673/130450676-80ccce58-77af-4f64-9576-3174e9f24dbd.png)

Running 'qgis-ltr' in the osgeo4w command box raises this error.

I checked the env files (on the broken and on a working machine), and they still look exactly the same.

I also tried to check if the directories (bin/lib) are still the same, and that seems the case (I was thinking that some virusscanner was maybe removing dll's or exe's).

Only thing I see is that the working machine does NOT have the vcredist-2013-x64.exe (anymore?). But that does seem odd.

Tried to use 'depends.exe' with qgis.exe, but that (on both machines) shows a lot of issues, but does not reveal something to me.

Any hints on ways to find out WHAT exactly has changed after this update, that breaks the QGIS install?

One 'idea' I had: is it possible that the QGIS installer copied some dll's to the system32 dir, which are changed/removed during such security updates? So my question would be: DOES the installer copy stuff to the windows dirs?

### Steps to reproduce the issue

See above

### Versions

Current version info:

`QGIS version 3.16.7-Hannover QGIS code revision 0471743889 Compiled against Qt 5.11.2 Running against Qt 5.11.2 Compiled against GDAL/OGR 3.1.4 Running against GDAL/OGR 3.1.4 Compiled against GEOS 3.8.1-CAPI-1.13.3 Running against GEOS 3.8.1-CAPI-1.13.3 Compiled against SQLite 3.29.0 Running against SQLite 3.29.0 PostgreSQL Client Version 11.5 SpatiaLite Version 4.3.0 QWT Version 6.1.3 QScintilla2 Version 2.10.8 Compiled against PROJ 6.3.2 Running against PROJ Rel. 6.3.2, May 1st, 2020 OS Version Windows 10 (10.0) Active python plugins JRodos; pdokservicesplugin; pdok_locatieserver_locator_filter; RIVM_PluginConfigManager; SectorPlot; db_manager; MetaSearch; processing`

**Comment by jef-n** [comment]
Try reinstalling opencl

**Comment by rduivenvoorde** [comment]
@jef-n how to (re)install this? We used the standalone installer. Can/should I rerun parts of osgeo4w scripts?

**Comment by rduivenvoorde** [comment]
Ok, I copied a opencl.dll (from C:\Windows\SysWOW64) into the [QGISINSTALL]/bin (else there was not one there to copy)
Renamed etc/postinstall.opencl.bat.done to opencl.bat
And run opencl.bat
Hopefully started QGIS and got:

![Screenshot-20210823173234-390x266](https://user-images.githubusercontent.com/731673/130475461-2801484d-fc92-4eaa-9152-bb111fba95b1.png)

That one is new :-)

**Comment by rduivenvoorde** [comment]
/me hearing the BoomTown Rats singing "I don't like mondays" but instead they sing ... windows 
(https://www.youtube.com/watch?v=-Kobdb37Cwc for the youngsters...)

**Comment by jonnyforestGIS** [comment]
@rduivenvoorde what is the version of Windows in VMWare?
I don't know if this is related but,

Try to whitelist the folder of QGIS to see if this error persists. 
https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26


Another thing, in here they say:
_Beginning in August of 2021 we'll start turning it on by default for consumer customers. You can always choose to turn it off again, if you don't want it, using the process below._
https://support.microsoft.com/en-us/windows/protect-your-pc-from-potentially-unwanted-applications-c7668a25-174e-3b78-0191-faf0607f7a6e

I hope this helps.

**Comment by jef-n** [comment]
SysWOW64 contains the 32-bit version.

**Comment by rduivenvoorde** [comment]
@jef-n huh? SysWOW64 contains 32 bit???? 
(I took that one because I googled and was told that SysWOW64 container 64bits...)

Anyway: I copied the opencl.dll from another (osgeo4w install) folder and ran the opencl.bat script (which just copies it to system32 folder, yes?). And then QGIS is working again!!!

So: what is it with opencl.dll that after some windows updates (this was supposed to be a 'feature update' I was told), the opencl.dll is removed/not working?

Anything we can do to NOT break QGIS after an update (other the copy the dll to c:/windows/system32 ?

**Comment by rduivenvoorde** [comment]
Ok, it appears that after the update the 'old Windows dir' is saved to:
`c:\windows.old\WINDOWS\system32`
and just copying the (during QGIS install installed) `opencl.dll` from there to 
`c:\windows\system32` 

It would be nice to know why that specific dll is not kept after a Windows upgrade?
again fixes QGIS.

**Comment by jef-n** [comment]
> It would be nice to know why that specific dll is not kept after a Windows upgrade?

Indeed.

**Comment by rduivenvoorde** [comment]
Tried microsoft/support and forum. First one kicked me to commercial support, and second one seems to indicate a 'long standing Windows issue":

https://docs.microsoft.com/en-us/answers/questions/527387/our-opencldll-is-removed-after-a-windos-update-bre.html?childToView=527955#comment-527955

So: I'm thinking: 
- QGIS is working if this dll is in the osgeo/qgis/bin dir
- Question: is it the CL stuff only working if the dll is in in system32 (@elpaso) ?
- from the "Oops could not load qgis_app.dll", how many 'suffer' this opencl issue? 
- how many Windows users will use CL (calculations on graphic cards)

Should/could we package the dll in the bin dir? So only people who use OpenCL should maybe copy it to system32?

**Comment by jef-n** [comment]
See #28184.  opencl.dll should only be copied into system32, when there is already an older version present.  Plus if a opencl.dll is present in system32, the copy in osgeo4w's bin is removed (to not mask updates to opencl.dll in system32). dllupdate.exe also leaves use references to opencl.dll in the registry, which should tell windows that it's there for a reason.  But it's apparently ignoring that at least in some cases and still removes the last copy in system32.
