### ISSUE TITLE
Models wont start when opened via browser or drag&drop

### ISSUE THREAD

**Issue by geistiii** [qgis/QGIS#44824]
### What is the bug or the crash?

Models can't be run by opening via the browser or by drap&drop. The GUI of the model appears, but hitting the "run" button doesn't result in action. There's also no error message.

Opening a model in the graphic modeller and starting it from there on the other hand works fine.

See https://gis.stackexchange.com/questions/404482/qgis-3-16-4-graphical-modeler-not-running

### Steps to reproduce the issue

1. Drag & drop any model into the QGIS main window
2. Enter necessary input
3. Run the model --> it wont start.
4. Error log shows nothing.

### Versions

3.16.4
3.16.6

**Comment by gioman** [comment]
> 3.14.4
> 3.14.6

@geistiii 3.14 is EOL, you must test on the latest 3.16 or 3.20.

**Comment by geistiii** [comment]
> > 3.14.4
> > 3.14.6
> 
> @geistiii 3.14 is EOL, you must test on the latest 3.16 or 3.20.

Sorry, I edited the versions to the correct ones (3.16.x)

**Comment by gioman** [comment]
@geistiii 



> Models can't be run by opening via the browser or by drap&drop. The GUI of the model appears, but hitting the "run" button doesn't result in action. There's also no error message.

works fine here on 3.16.10 on Windows


> 3.16.4
> 3.16.6
> ###

still not the latest versions. If the problem persist try a new QGIS profile. If still persist attach a model that does not work for you.

**Comment by pathmapper** [comment]
Already fixed by https://github.com/qgis/QGIS/pull/43716

**Comment by gioman** [comment]
> Already fixed by #43716

right, so @geistiii just update to the latest point release.
