### ISSUE TITLE
Processing: Cannot choose attribute for "Class Identifier" in SAGA Supervised Classification for Grids

### ISSUE THREAD

**Issue by samuel-rosa** [qgis/QGIS#44828]
### What is the bug or the crash?

I am using SAGA-GIS tool _Supervised Classification for Grids_. One of the options of this tool is _Class Identifier_. It serves the purpose of indicating which of the fields of _Training Areas_, an optional input shape, contains the definitions of the classes. The SAGA-GIS version 7.3.0 does not enable the selection of that field. Instead, the dropdown list shows all available shape layers. As a consequence, the classification algorithm does not run.

### Steps to reproduce the issue

The figure below shows the SAGA-GIS tool _Supervised Classification for Grids_. The options _Class Identifier_ does not show the fields contained in the attribute table of the shape _treinamento_.

![Screenshot from 2021-08-24 16-22-36](https://user-images.githubusercontent.com/10142507/130677998-59be9435-f2d5-46cb-b851-a7a62efaeac1.png)

This is different from SAGA-GIS itself as shown in the figure below:

![Screenshot from 2021-08-24 16-35-58](https://user-images.githubusercontent.com/10142507/130678957-86ca893e-907e-444e-9cd0-57f224aee8a0.png)

The shape used is available at <https://cloud.utfpr.edu.br/index.php/s/OoMQk3wRcMJEazJ>

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.16.4-Hannover | QGIS code branch | Release 3.16
-- | -- | -- | --
Compiled against Qt | 5.12.8 | Running against Qt | 5.12.8
Compiled against GDAL/OGR | 3.2.1 | Running against GDAL/OGR | 3.2.1
Compiled against GEOS | 3.9.0-CAPI-1.16.2 | Running against GEOS | 3.9.0-CAPI-1.16.2
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.6 (Ubuntu 12.6-0ubuntu0.20.04.1) | SpatiaLite Version | 5.0.0
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 7.2.1 | Running against PROJ | Rel. 7.2.1, January 1st, 2021
OS Version | Ubuntu 20.04.2 LTS
Active python plugins | togglegroupvisibility; quick_map_services; processing_r; pointsamplingtool; mapbiomascollection; qfieldsync; QuickOSM; processing; db_manager; MetaSearch

</body></html>

### Additional context

I am happy to provide more info if needed.

**Comment by roya0045** [comment]
@samuel-rosa Note that your SAGA version and the one native to qgis are different. You can try the plugin to see if this is better.

**Comment by samuel-rosa** [comment]
@roya0045 I did not understand what you meant by _You can try the plugin to see if this is better_. Could you please provide more detail?

**Comment by samuel-rosa** [comment]
@roya0045  I now see that there is a standalone SAGA plugin provided by NextGen. I was not aware of this and will give a try.

**Comment by samuel-rosa** [comment]
@roya0045, I tested Processing Saga NextGen Provider: works like a charm! Thanks for pointing this plugin out.

I noticed that it is experimental. Will it replace the one native to QGIS?

**Comment by roya0045** [comment]
@samuel-rosa This might shed some light on the situation https://github.com/qgis/QGIS-Enhancement-Proposals/issues/230

**Comment by alexbruy** [comment]
FYI, there is a [QEP](https://github.com/qgis/QGIS-Enhancement-Proposals/issues/230) related to this.

**Comment by roya0045** [comment]
> FYI, there is a [QEP](https://github.com/qgis/QGIS-Enhancement-Proposals/issues/230) related to this.

I linked it previously ;)

**Comment by alexbruy** [comment]
SAGA Provider was not maintained and now remowed from QGIS (see #50834). Users are encouraged to use the 3rd-party plugins instead.
