### ISSUE TITLE
QGIS modules block PyCharm debugging

### ISSUE THREAD

**Issue by MPinter2** [qgis/QGIS#44841]
### What is the bug or the crash?

This simple script demonstrates the issue:

```python
# import qgis.core
# from qgis.core import QgsVectorLayer, QgsVectorDataProvider, QgsPointXY, QgsDistanceArea
# from qgis.utils import iface

def simple():
    x=0
    print(2+2)
```

In PyCharm, set a breakpoint anywhere in simple(), run the debugger, and execution stops at the breakpoint as it should.  Uncomment anyone one of the QGIS imports shown above (which one doesn't matter), and the debugger no longer works.   The debugger doesn't execute or stop at the breakpoint & reports an error (Process finished with exit code 1073741845).  Paths are set correctly; scripts using QGIS modules shown above execute normally within PyCharm.  Runtime errors are reported.  

### Steps to reproduce the issue

QGIS does not need to be running to produce this effect.  This seems to be an adverse interaction between PyQGIS modules & pydevd?

### Versions

QGIS 3.16
Python 3.7
Windows 7 64-bit
PyCharm 2021.2 (Prof ed)

**Comment by Gustry** [comment]
Can you fix the code snippet with 3 backticks and correct indentation ?

```` 
```python
print("hello")
```
````
will render
```python
print("hello")
```

**Comment by roya0045** [comment]
And what if you don't import iface? I don't get why you're trying to debug something that requires an interface, from a code editor.

**Comment by MPinter2** [comment]
> And what if you don't import gui/iface? I don't get why you're trying to debug something that requires an interface, from a code editor.

I should have been clearer. This is a demonstration of a problem encountered in the debugging capabilities of a widely-used editor when at least one or more of those 3 QGIS modules are simply imported.  Debugging is eliminated. This is not meant to demonstrate usage of the modules.  The import of the iface module is sufficient to cause the effect.

**Comment by roya0045** [comment]
Isn't that just because the underlying code is not in python but c++?

**Comment by MPinter2** [comment]
> Can you run some `print()` statements before and after the import?
> 
> I suspect it's crashing during qgis initialisation.

Thanks. Good point, strip down the demonstration even further.  When run by the PyCharm debugger (pydevd), the following script ..
 
 print("Hello world")
 import qgis.core
 print("Hello again")

 displays "Hello World" but not "Hello again", and concludes like so .. (Process finished with exit code 1073741845).  When run by QGIS 3.16/apps/Python37/python.exe, both print statements execute normally. 

 Anyone with experience using Eclipse with pydev for PyQGIS developemnt?  Any troubles with pydev?

**Comment by MPinter2** [comment]
Problem resolved. Carelessly overlooked installation of Remote Debug plugin in QGIS. Debugging in PyCharm now operates perfectly.

**Comment by Gustry** [comment]
Which debugger in the "Remote Debug plugin" did you use to work with PyCharm ?

**Comment by MPinter2** [comment]
> Which debugger in the "Remote Debug plugin" did you use to work with PyCharm ?

I used PyDev (Eclipse).. I believe PyCharm also uses PyDev.
