### ISSUE TITLE
Splash screen freezes on 'QGIS Ready'

### ISSUE THREAD

**Issue by HannesMas** [qgis/QGIS#44855]
### What is the bug or the crash?

QGIS does not launch and freezes on the Splash screen mentioning 'QGIS Ready'. This has been observed by several people in our organization on different versions of QGIS (certainly on 3.16 LTR and 3.18.3)

### Steps to reproduce the issue

We believe it is due to a mapped network drive in Windows (Win10 Enterprise) which is no longer valid. Possibly QGIS tries to connect to such network drive over and over.  

Requesting to implement a timeout when trying to connect to mapped drives and possibly return a message stating the dead network drive.

### Versions

Not possible to copy QGIS version info as it is impossible to launch QGIS.
Certainly occurs in version 3.16LTR and 3.18.3.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by HannesMas** [comment]
@gioman , when I uninstallled 3.18, I removed all of those invalid drives, not sure how to mimic such invalid drive so I'm afraid I can't test it with 3.20 or other versions.

**Comment by gioman** [comment]
@HannesMas reopen if you can replicate with QGIS 3.20
