### ISSUE TITLE
[Mesh] Crash when playing with level of details

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#44863]
### What is the bug or the crash?

I was trying to understand how the mesh "Reduction factor" setting affects the number of 3D "levels of detail". So going back and forth between these two options in the layer prioperties dialog and at some point I got

```
Crash ID: 9114d34e7ebbb5d7d412f55f95d568a3045fb9dd

Stack Trace


QList::size :
QList::count qlist.h:359
QgsMeshDatasetGroupTreeItem::enabledDatasetGroupIndexes qgsmeshdataset.cpp:598
QgsMeshDatasetGroupListModel::rowCount qgsmeshdatasetgrouptreeview.cpp:512
QgsMeshDatasetGroupListModel::data qgsmeshdatasetgrouptreeview.cpp:522
QComboBox::itemText :
QComboBox::initStyleOption :
QComboBox::paintEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:509
QCoreApplication::notifyInternal2 :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::moveRect :
QWidget::event :
QgisApp::event qgisapp.cpp:2120
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:509
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1644
WinMain mainwin.cpp:197
__scrt_common_main_seh exe_common.inl:288
BaseThreadInitThunk :
RtlUserThreadStart :


QGIS Info
QGIS Version: 3.21.0-Master
QGIS code revision: b9e4db1c90
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.1
Running against GDAL: 3.3.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043
```

### Steps to reproduce the issue

I was (heavily) playing with the options in Rendering and 3D tabs
The dataset I was using is https://github.com/lutraconsulting/MDAL/blob/master/tests/data/grib/Madagascar.wave.7days.grb

### Versions

QGIS Version: 3.21.0-Master
QGIS code revision: b9e4db1c90
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.1
Running against GDAL: 3.3.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by PeterPetrik** [comment]
@DelazJ any chance of screencast?

**Comment by vcloarec** [comment]
I can't reproduce when I play with "levels of details" but I have also a crash when I heavily undo/redo during mesh editing with 3D view  and  with the edited mesh as terrain. It could be the same issue... 
The crash happens with a built with Qt 5.12.8 (ubuntu 20.04) and as I don't have debug symbol for this version, I only know the crash could happen in a Qt3DNode. 
When I try to reproduce with a built with Qt 5.15.2 and debug symbol, I don't have any crash...

**Comment by alexbruy** [comment]
Is this still an Issue? I can't reproduce crash on latest master (beb28f6ffd) on Linux.
