### ISSUE TITLE
v.net.alloc missing 'method' option in Processing

### ISSUE THREAD

**Issue by BergWerkGIS** [qgis/QGIS#44877]
### Feature description

I'm aware that v.net.alloc is labeled
"Allocates subnets for nearest centers _**(direction from center)**_"
in the processing toolbox.

But it would be great if the additional `method` parameter could be added:

https://grass.osgeo.org/grass78/manuals/v.net.alloc.html#parameters
> method=string
> * Use costs from centers or costs to centers
> * Options: from, to
> * Default: from

This change would be a great addition as I've found no other tool that integrates with QGIS and allows for calculations "to-centers".
Neither in the default processing toolbox, nor a plugin (QNEAT3, ORS Tools, ...), or pgRouting.

### Additional context

I want to automate which areas can reach services centers, not which areas can be reached from services centers.
This makes a big difference in the resulting area when considering one way streets or service centers close to highway links.

An alternative for my use case would be if the `GRASS shell` could be reached somehow via Python so I can execute the GRASS commands myself.
But I haven't found an API for that.

**Comment by BergWerkGIS** [comment]
I don't know if this is the correct way to do it, but just a little change to [v.net.alloc.txt](https://github.com/qgis/QGIS/blob/1906e19899c59a691968bdd2a27d7e88909d16f6/python/plugins/grassprovider/description/v.net.alloc.txt) made it work for me.

```diff
diff --git a/v.net.alloc.txt b/v.net.alloc.txt
index 07a7679..41d7bd4 100644
--- a/v.net.alloc.txt
+++ b/v.net.alloc.txt
@@ -1,11 +1,12 @@
 v.net.alloc
-Allocates subnets for nearest centers (direction from center)
+Allocates subnets for nearest centers
 Vector (v.*)
 QgsProcessingParameterFeatureSource|input|Input vector line layer (arcs)|1|None|False
 QgsProcessingParameterFeatureSource|points|Centers point layer (nodes)|0|None|False
 QgsProcessingParameterNumber|threshold|Threshold for connecting centers to the network (in map unit)|QgsProcessingParameterNumber.Double|50.0|False|0.0|None
 *QgsProcessingParameterString|center_cats|Category values|1-100000|False|False
 *QgsProcessingParameterEnum|arc_type|Arc type|line;boundary|True|0,1|False
+*QgsProcessingParameterEnum|method|Method|from;to|False|0|False
 *QgsProcessingParameterField|arc_column|Arc forward/both direction(s) cost column (number)|None|input|0|False|True
 *QgsProcessingParameterField|arc_backward_column|Arc backward direction cost column (number)|None|input|0|False|True
 *QgsProcessingParameterField|node_column|Node cost column (number)|None|points|0|False|True
```

If that's really all there is to it, I'll happily provide a PR 😄 

## Examples 

Routing from:
![image](https://user-images.githubusercontent.com/4549888/131254960-46f35cad-b256-4692-82a5-e73dd54671d5.png)

Routing to:
![image](https://user-images.githubusercontent.com/4549888/131254966-99d46900-f7f6-4b05-a81e-c02fe6a35bba.png)

Routing from:
![image](https://user-images.githubusercontent.com/4549888/131255057-bd315c4f-fdae-4209-9aeb-a4bd8e5d2288.png)

Routing to:
![image](https://user-images.githubusercontent.com/4549888/131255064-b312a90d-73c5-43b4-8881-d196b40cc216.png)

**Comment by gioman** [comment]
@BergWerkGIS if you want to give it a try the file to modify is https://github.com/qgis/QGIS/blob/master/python/plugins/grassprovider/description/v.net.alloc.txt if the change works for you locally then you can submit a pull request here.

**Comment by gioman** [comment]
> I'll happily provide a PR

@BergWerkGIS I posted as the same time as you :) yes, the PR is welcome.

**Comment by BergWerkGIS** [comment]
PR #44882
