### ISSUE TITLE
Regression in Attribute Table with Dynamic Temporal Controller

### ISSUE THREAD

**Issue by CoryAlbrecht** [qgis/QGIS#44874]
### What is the bug or the crash?

The attribute table window in 3.20.2 has started showing features which are out of scope with the dynamic temporal controller. This had been fixed with #39076 and #40768.

![image](https://user-images.githubusercontent.com/8172909/131198392-aec104c5-1f24-4e6b-b5f0-4877a79fcaa9.png)

### Steps to reproduce the issue

Just open up an Attribute table window in a project using temporal data..

### Versions

QGIS version | 3.20.2-Odense | QGIS code revision | d61284b348
-- | -- | -- | --
Qt version | 5.12.8
Python version | 3.8.10
GDAL/OGR version | 3.0.4
PROJ version | 6.3.1
EPSG Registry database version | v9.8.6 (2020-01-22)
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
SQLite version | 3.31.1
PDAL version | 2.0.1
PostgreSQL client version | 12.8 (Ubuntu 12.8-0ubuntu0.20.04.1)
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.2
OS version | Ubuntu 20.04.3 LTS
  |   |   |  
This copy of QGIS writes debugging output.
  |   |   |  
Active Python plugins | QGIS3-getWKTLocatePointsgeometry_pasterCanadianWebServicescartolinegenpostgisQueryBuilderClipMultipleLayerspg_metadataGeneralizer3html_table_exportercartography_toolsbettereditordb-style-managerqgis2websplitmultipartqgiscloudshapetoolsQgis2threejsprocessingdb_manager

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
> Just open up an Attribute table window in a project using temporal data..

@CoryAlbrecht before you say is has been fixed, do you mean that it regressed?

**Comment by CoryAlbrecht** [comment]
Yes, "regression" is the word I meant to use, not "reversion". The bug reports mentioned above were fixed and that Attribute Table was working as expected. This is a regression.

**Comment by nyalldawson** [comment]
You need to set the "filter" in the bottom left to "Show Visible Features". That's how this has always worked.

**Comment by CoryAlbrecht** [comment]
OK. My mistake. I didn't remember seeing that, just the option in the application settings.
