### ISSUE TITLE
"Split Feature" not splitting when start or end point is inside a ring

### ISSUE THREAD

**Issue by robert-werner** [qgis/QGIS#44889]
### What is the bug or the crash?

When I try to split feature with ring with starting point **inside** the ring, and ending point **outside the polygon**, the feature does not split at all. 

When I try to split mine feature with ring, but starting point is outside the polygon and ending point is same, the feature successfully splits.

### Steps to reproduce the issue

1. Download the attached SplitFeatureBugReproduce.gpkg and SplitFeatureBugReproduce.qgz file.
2. Import them on QGIS
3. Turn on the Editing mode
4. Turn on the Split Features instrument
5. Left click starting point at 56.12936142,57.51466774 (EPSG:4326)
6. Left click ending point at 56.1262757,57.5130215 (EPSG:4326)
7. Click right mouse button
[SplitFeatureBugReproduce.gpkg.zip](https://github.com/qgis/QGIS/files/7076504/SplitFeatureBugReproduce.gpkg.zip)
[SplitFeatureBugReproduce.zip](https://github.com/qgis/QGIS/files/7076541/SplitFeatureBugReproduce.zip)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.20.1-Odense | QGIS code branch | Release 3.20
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.6
GDAL/OGR version | 3.3.1
Compiled against PROJ | 8.0.1.%3.%4 | Running against PROJ | 8.1.0
EPSG Registry database version | v10.026 (2021-06-10)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.36.0
PDAL version | 2.3.0
PostgreSQL client version | 13.3
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.0
OS version | Manjaro Linux
  |   |   |  
Active Python plugins | ComplexGmlInfogml_application_schema_toolboxSaxonyCadastralParcelsatom_feed_clientquick_map_servicesDataforsyningenSpanish_Inspire_Catastral_Downloaderwfs_2_clientwfsclientKortforsyningeninspireNLvaluetoolkmltoolsdb_managerMetaSearchprocessing

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

**Comment by uclaros** [comment]
This is expected behavior.
When using the *split* tool, the digitized line should divide your geometry in two distinct parts. Your line does not, since it only intersects the outer ring once.

**Comment by robert-werner** [comment]
> This is expected behavior.
> When using the _split_ tool, the digitized line should divide your geometry in two distinct parts. Your line does not, since it only intersects the outer ring once.

Then what tool I can use to slice mine geometry? The example situation is: I want to cut out only a part of geometry.

**Comment by uclaros** [comment]
You need to continue your digitized line so that it intersects the outer ring (or inner ring, or both) more than once.

**Comment by robert-werner** [comment]
> You need to continue your digitized line so that it intersects the outer ring (or inner ring, or both) more than once.

It does not looks convenient, though.
