### ISSUE TITLE
Table of content abnormally closing after using showAttributeTable (Processing plugin)

### ISSUE THREAD

**Issue by eguilley** [qgis/QGIS#44894]
### What is the bug or the crash?

I have recently developed a **_Processing_ plugin** for **QGis 3.16**, which aims to analyze biodiversity data from a specific PostgreSQL data base (https://github.com/lpoaura/PluginQGis-LPOData). It is used by several employees in our company.

For each algorithm, a spatial or non spatial layer is created and its table of content is opened at the end of the code execution, with the following command :

```
iface.showAttributeTable(output_layer)
iface.setActiveLayer(output_layer)
```

Depending on people feedback, **two problems can be faced** here :
    • either the table of content opens up and closes immediately without having displayed the content
    • or the table of content opens up and gets frozen (that means that you can’t even scroll or select action from the window)

I can’t find any error message on QGis desktop after this, so I don’t know what’s happening. Apparently this issue has already been raised but I can’t find it...

Has anyone ever faced this problem ? Any help to fix this ?

### Steps to reproduce the issue

I would like to recommend installing the plugin and trying it, but it can be used only with a specific data base…

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

Version de QGIS | 3.16.9-Hannover | Révision du code | 9f8d2f7942
-- | -- | -- | --
Compilé avec Qt | 5.9.5 | Utilisant Qt | 5.9.5
Compilé avec GDAL/OGR | 2.2.3 | Utilisé avec GDAL/OGR | 2.2.3
Compilé avec GEOS | 3.6.2-CAPI-1.10.2 | Utilisé avec GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compilé avec SQLite | 3.22.0 | Fonctionne avec SQLite | 3.22.0
Version du client PostgreSQL | 10.17 (Ubuntu 10.17-0ubuntu0.18.04.1) | Version de SpatiaLite | 4.3.0a
Version de QWT | 6.1.3 | Version de QScintilla2 | 2.10.2
Version de PROJ.4 : | 493
Version de l'OS | Ubuntu 18.04.5 LTS
Extensions Python actives | plugin_reloader; menu_from_project; GroupStats; scripts_lpo; SpreadsheetLayers; db_manager; processing; MetaSearch

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
@eguilley as stated here https://github.com/qgis/QGIS/issues/new/choose questions should be asked in users/developers mailing lists or gis.stackexchange

**Comment by eguilley** [comment]
Answered here : https://gis.stackexchange.com/questions/409547/table-of-content-abnormally-closing-after-using-showattributetable-processing-p

**Comment by nyalldawson** [comment]
@eguilley just to explain this further -- processing algorithm "processAlgorithm" functions are (by default) run in a background thread, so that you can keep using QGIS while they process away. BUT it's completely forbidden to do any GUI work (such as opening an attribute table dialog) from background threads, as it leads to all kinds of unpredictable behaviour, like the crashes you've been encountering.

Moving the table handling to the post processing step guarantees that it'll be run in the main thread after the algorithm finishes it's heavy lifting on the background thread, hence no more crashes :+1:
