### ISSUE TITLE
event.mapPoint and event.originMapPoint return the same

### ISSUE THREAD

**Issue by 5Nap** [qgis/QGIS#44895]
### What is the bug or the crash?

Looks like there is a bug in originalMapPoint() method:
```
     inline QgsPointXY mapPoint() const { return mMapPoint; }  
     QgsPointXY originalMapPoint() const { return mMapPoint; }
```
And later there is private member ``QgsPointXY mOriginalMapPoint`` which supposed to be returned from originMapPoint()

### Steps to reproduce the issue

Just try to call event.mapPoint and event.originalMapPoint and compare results - it's the same every time.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.20.2-Odense | QGIS code revision | 9f59a15664
-- | -- | -- | --
Qt version | 5.12.8
Python version | 3.8.10
GDAL/OGR version | 3.0.4
PROJ version | 6.3.1
EPSG Registry database version | v9.8.6 (2020-01-22)
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
SQLite version | 3.31.1
PDAL version | 2.0.1
PostgreSQL client version | 12.8 (Ubuntu 12.8-0ubuntu0.20.04.1)
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.2
OS version | Ubuntu 20.04.3 LTS
  |   |   |  
Active Python plugins | QuickWKTgeometry_calculatorautoSavertangent_curve_toollanes_attributespluginbuilder3latlontoolsQuickOSMDigitizingToolsplugin_reloadergives_wayBezierEditingmapswipetool_pluginfeature_generatortile_servicerides_viewerquick_map_servicesconstructortrl_lanestrue_topologyvalidation_errors_inspectordb_managerprocessingvertex_mover

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
From the docs for "mapPoint" : "the point in map coordinates, after snapping if requested in the event. ". So until you've snapped the point it will be identical to the original point. Solution is to call "snapPoint" on the event first.

(or use the QgsMapToolAdvancedDigitizing class and hook into the cadCanvas*events, which automatically apply snapping for you)

**Comment by 5Nap** [comment]
> (or use the QgsMapToolAdvancedDigitizing class and hook into the cadCanvas*events, which automatically apply snapping for you)
Yes, that's exactly what I'm doing.
