### ISSUE TITLE
Won't let me Export Image as a TIF 

### ISSUE THREAD

**Issue by Luuudus** [qgis/QGIS#44916]
### What is the bug or the crash?

The size of the image is 68622 px by 19133 px at a resolution of 300 dpi. 

Crash ID: ab65ebc7596968dcddc6801a094fca23318dcdea

### Steps to reproduce the issue

1. Go to Layout and select Large Landscape
2. Click on Export Image as
3. Select .tiff
4. Save and wait for render to crash...

### Versions

QGIS version 3.16.2-Hannover

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

I will try a new profile now and remove this ticket if that is the issue, however assume it hasn't fixed the issue.

**Comment by gioman** [comment]
@Luuudus duplicate of https://github.com/qgis/QGIS/issues/41971 ?

**Comment by roya0045** [comment]
> @Luuudus duplicate of #41971 ?

Agreed, limit in Qt is still 2^15
