### ISSUE TITLE
In reference to  BR 43796

### ISSUE THREAD

**Issue by stumbles** [qgis/QGIS#44917]
### What is the bug or the crash?

[ 12%] Building CXX object src/core/CMakeFiles/qgis_core.dir/pointcloud/qgseptdecoder.cpp.o
[ 12%] Building CXX object src/core/CMakeFiles/qgis_core.dir/pointcloud/qgseptpointcloudindex.cpp.o
[ 12%] Building CXX object src/core/CMakeFiles/qgis_core.dir/pointcloud/qgsremoteeptpointcloudindex.cpp.o
[ 12%] Linking CXX shared library ../../output/lib/libqgis_core.so
/usr/bin/ld: CMakeFiles/qgis_core.dir/geometry/qgsgeometry.cpp.o: in function `QgsGeometry::makeValid() const':
qgsgeometry.cpp:(.text+0x3cd6): undefined reference to `_qgis_lwgeom_make_valid(QgsAbstractGeometry const*, QString&)'
collect2: error: ld returned 1 exit status
make[2]: *** [src/core/CMakeFiles/qgis_core.dir/build.make:13552: output/lib/libqgis_core.so.3.20.2] Error 1
make[1]: *** [CMakeFiles/Makefile2:2015: src/core/CMakeFiles/qgis_core.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

### Steps to reproduce the issue

Well you use the usual method to build this app.

### Versions

qgis-3.20.2.

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@stumbles if you have issues compiling you should write in the developers mailing list rather than assuming is a bug.
