### ISSUE TITLE
Issue when retrieving demo project with qgis-server 

### ISSUE THREAD

**Issue by Goneiross** [qgis/QGIS#44926]
### What is the bug or the crash?

Hey guys,

I'm trying to install qgis-server to then use it with lizmap. 
I followed the manual but I keep getting errors when I try my config with : http://map.cloud-altetia.fr/qgisserver?MAP=/home/qgis/projects/world.qgs&LAYERS=countries&SERVICE=WMS&REQUEST=GetMap&CRS=EPSG:4326&WIDTH=400&HEIGHT=200 .
With QGIS 3.10 I had a blank image, but now, with version 3.16 I got : 
`
<ServiceExceptionReport version="1.3.0"> 
<ServiceException code="OperationNotSupported">Please add the value of the VERSION parameter</ServiceException>
</ServiceExceptionReport>
`
I already doubled check permissions (-rwxrwxrwx 1 www-data www-data world.qgs) for the project file.
Here are the logs of my latest issue as a file: [log_qgis.txt](https://github.com/qgis/QGIS/files/7099732/log_qgis.txt)

If you had any idea I would be very thankful ! 

### Steps to reproduce the issue

I followed the guide from qgis : [here](https://docs.qgis.org/3.16/en/docs/server_manual/getting_started.html#serve-a-project), on Ubuntu 21.04, and loaded world.qgs.

### Versions

3.16

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
> <ServiceExceptionReport version="1.3.0"> <ServiceException code="OperationNotSupported">Please add the value of the VERSION parameter</ServiceException> </ServiceExceptionReport>

@Goneiross the answer is in the error message, you miss the VERSION parameter

`http://map.cloud-altetia.fr/qgisserver?MAP=/home/qgis/projects/world.qgs&LAYERS=countries&SERVICE=WMS&REQUEST=GetMap&CRS=EPSG:4326&WIDTH=400&HEIGHT=200&version=1.3.0`

**Comment by jef-n** [comment]
See also e2f4fc65c5d8520ed2e2cf22b20697322af99e67

**Comment by Goneiross** [comment]
Oh ooops
But I still got the same issue as with QGIS 3.10 :
![image](https://user-images.githubusercontent.com/8150340/131866757-9b1aea4c-656b-490a-82ab-ddba21cefa67.png)
And here are the logs :  [log_qgis_2.txt](https://github.com/qgis/QGIS/files/7099883/log_qgis_2.txt)

**Comment by gioman** [comment]
@Goneiross https://docs.qgis.org/3.16/en/docs/server_manual/services.html#qgisserver-wms-getmap

**Comment by Goneiross** [comment]
Oh thanks !
Maybe the docs should be modified then ? Here : https://docs.qgis.org/3.16/en/docs/server_manual/getting_started.html#serve-a-project
