### ISSUE TITLE
QGIS crashes when opening a folder in Browser

### ISSUE THREAD

**Issue by HarryEClarke** [qgis/QGIS#44925]
### What is the bug or the crash?

Editing a map in layout Manager, and QGIS crashed without any error message.

Prior to this I had tried to add a raster TIFF file bu using the Browser Panel. However, when I reached the main high level directory, the browser just hung.
I then used Add Layer/ Raster, and was able to successfully add the three TIFF files that I wanted to add, which displayed correctly. I then proceeded to edit the map in Layout Manager (which had already been created). Whilst in the middle of the edit, QGIS crashed.

### Steps to reproduce the issue

Not sure, but I suspect browser panel hanging when trying to brown a directory.
Computer Windows 10, with 32MB of memory of which 21MB is free.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.20.1-Odense | QGIS code revision | 1c3c5cd6
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.1
PROJ version | 8.1.0
EPSG Registry database version | v10.018 (2021-04-02)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins | changeDataSourcequick_map_servicesTomBiodb_managerMetaSearchprocessing

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

Restarted QGIS and repeated edits. Added the three TIFF files via Add Layer, and edit the map in Layout Manager to completion. Everything was OK. The only difference was that I didn't use the Browser Panel.

**Comment by gioman** [comment]
> ### Additional context
> 
> Restarted QGIS and repeated edits. Added the three TIFF files via Add Layer, and edit the map in Layout Manager to completion. Everything was OK. The only difference was that I didn't use the Browser Panel.

@HarryEClarke do you have set of steps to replicate the crash in a consistent way?

**Comment by HarryEClarke** [comment]
The error is reproducible!
Installed latest version 3.20.2, opened a map, and in the Browser panel, clicked on C:, and clicked down to maps folder, clicked on a folder  (OSdata) which contains 14 other folders, and 13 zip files. The busy circle then appears without displaying the contents of the folder.
Running Resource monitor, showed that QGIS was consuming memory at a steady rate. I stopped the program after it had reached 45MB on a 32MB machine!!

This suggests at least two errors in QGIS
1) QGIS is allocating memory without checking error codes, and hence crashes when it runs out of memory
2) QGIS should be displaying contents of folder, and not consuming resources.

**Comment by gioman** [comment]
> (OSdata)

@HarryEClarke can you share/link a copy of this folder?

**Comment by HarryEClarke** [comment]
Sorry that is not possible, the folder is 6.85GB is size, and contains a total of 7,485 files in 129 folders. I enclose a screen shot of the folder that QGIS failed to display
<img width="1152" alt="Folder" src="https://user-images.githubusercontent.com/23401969/131883287-ed8ee9fe-78b8-4d2e-9289-c032a79e261d.png">

**Comment by jef-n** [comment]
If it's a certain file the browser crashes with, [procmon](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) might give a hint.

> Running Resource monitor, showed that QGIS was consuming memory at a steady rate. I stopped the program after it had reached 45MB on a 32MB machine!!

**M**B?

**Comment by gioman** [comment]
> Sorry that is not possible

@HarryEClarke is that open data? can be downloaded from some site?

**Comment by HarryEClarke** [comment]
Some of it is open data that can be downloaded from  https://osdatahub.os.uk/downloads/open
However, the majority is restricted data.

**Comment by gioman** [comment]
> Some of it is open data that can be downloaded from https://osdatahub.os.uk/downloads/open
> However, the majority is restricted data.

Then I can't see how to replicate.

**Comment by HarryEClarke** [comment]
Question is what on earth is QGIS attempting to do???? It should JUST be displaying the contents of the folder. However, it seems that it is trying to load the whole contents of the folder into memory, which is ridiculous.

**Comment by HarryEClarke** [comment]
I have identified the problem, which is the QGIS is attempting to read all the ZIP files for some strange reason.
I moved all the ZIP files into a separate folder, and QGIS was able to properly browse the OSdata folder, and the folders below that. However, if I moved to the folder containing all the ZIP files, then QGIS just sits there consuming memory.

**Comment by gioman** [comment]
> Question is what on earth is QGIS attempting to do????

@HarryEClarke QGIS can load datasources directly from ZIP files, so by default it scans them. Try disable the scan (or use "basic scan") in QGIS general properties > data sources  > scan content of compressed files

**Comment by nyalldawson** [comment]
@HarryEClarke I would very much appreciate if you could test with a nightly prerelease of 3.22 - the way browser file scanning is done has been completely revamped and I'd like confirmation whether this issue is now solved.

**Comment by HarryEClarke** [comment]
@nyalldawson I would do if I knew how to install the prerelease.
I downloaded the OSGeo4W package, and selected advanced install. Then it was asking for a URL, so I tried the QGIS website, browsed to Desktop, but everything was empty. perhaps you could send me some more detailed instructions.

**Comment by gioman** [comment]
@HarryEClarke use this standalone installer (qgis master): https://qgis.org/downloads/weekly/QGIS-OSGeo4W-3.21.0-35-Setup-x86.exe

**Comment by HarryEClarke** [comment]
@nyalldawson / @gioman  I do need some instructions on how to download and install the version of QGIS you would like me to test.

**Comment by gioman** [comment]
@HarryEClarke use this installer https://github.com/qgis/QGIS/issues/44925#issuecomment-913136563 (QGIS master aka QGIS 3.22 to be).

**Comment by HarryEClarke** [comment]
@gioman please answer the question as  #44925 (comment) does not install QGIS master.

**Comment by gioman** [comment]
> @gioman please answer the question as #44925 (comment) does not install QGIS master.

@HarryEClarke I'm not really sure what do you mean (the link you posted is the one of this very ticket). The installer  https://qgis.org/downloads/weekly/QGIS-OSGeo4W-3.21.0-35-Setup-x86.exe will allow you to install QGIS master (a recent weekly build) without needing to use the osgeo4w (network installer) of you are not familiarized with. The weekly installer contains all the latest fixes, so I'm pretty sure it also has the one you should test,

**Comment by HarryEClarke** [comment]
I ran the installer which did not install QGIS. It created a folder under Program(x86) which under the bin folder contained the program OSGeo4W. I tried running that, but it wouldn't install qgis, so I tried qgis-dev which was not the right version.
This may be blindly obvious to qgis developers, but it is not to me. Why so complicated?

**Comment by gioman** [comment]
@HarryEClarke it seems the standalone nightly installers have issues. So use the osgeo4w network install, follow the advanced install and in the "desktop" category select to install the qgis-dev package (and accept all the proposed dependencies). This will install qgis master.

**Comment by gioman** [comment]
@HarryEClarke and when using the network installer you don't need to change any path or select any URL, just use the default options that are presented by the wizard.

**Comment by HarryEClarke** [comment]
@gioman Let me know when there is an installer that actually works.

**Comment by gioman** [comment]
> @gioman Let me know when there is an installer that actually works.

@HarryEClarke the osgeo4w network installer works. Follow the indications I gave you here above.

**Comment by HarryEClarke** [comment]
I have tested this in the latest version of QGIS 3.20.3
With options set to "Scan for contents of files (.zip) in browser dock" to "Basic", QGIS behaves as before, in a steady increase in memory.
With the option set to "No", just the ZIP files in the folder are displayed.

**Comment by gioman** [comment]
> I have tested this in the latest version of QGIS 3.20.3

@HarryEClarke the fix is in 3.22 not 3.20

https://github.com/qgis/QGIS/issues/44925#issuecomment-913044235

**Comment by HarryEClarke** [comment]
@gioman as my previous comment, let me know when an installer that actually works, as I was unable to install from your instructions.
