### ISSUE TITLE
Raster layer not rendering after data-source change when combined with certain layout elements

### ISSUE THREAD

**Issue by MattScorah** [qgis/QGIS#44929]
### What is the bug or the crash?

There are two raster layers in the attached project. When the data-source of either of the rasters is changed that layer no longer renders (either in the main map view or the layout view and any exported images). For that layer nothing is visible. If the project is saved and reopened after the data-source is changed it will draw and export correctly. 

The issue appears to be tied to this specific combination of elements - by removing some of the legends or maps from the layout or the visibility themes used in each map the issue may go away. I've tried to strip away everything from the project that makes no difference to the outcome.

Happy to provide any more info / testing that might help!

[QGISBugReport2.zip](https://github.com/qgis/QGIS/files/7103490/QGISBugReport2.zip)

### Steps to reproduce the issue

1. Open the attached project
2. Right click the layer "NORM" (or "ABS") > Properties > Source tab
3. Change the layer source to the other layer in the same folder (e.g. change NormBurst/WY_2011_Ending_2012_03_01.tif to WY_2012_Ending_2013_03_01.tif
4. Click OK. The layer with the changed data-source will no longer render. 

### Versions

QGIS version
3.18.3-Zürich
QGIS code revision
735cc85be9
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
AnotherDXF2Shape; 
crayfish; 
DataPlotly; 
go2streetview; 
MapsPrinter; 
map_cycler; 
OSMDownloader; 
pluginbuilder3; 
plugin_reloader; 
pointsamplingtool; 
quick_map_services; 
StreetView; 
tuflow; 
valuetool; 
db_manager; 
MetaSearch; 
processing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by elpaso** [comment]
@MattScorah did you check if this issue is bound to the particular projection you are using (GDA)? You could use gdal to transform the layers to a different projection (some UTM for your zone would do) and check if the issue persists.

**Comment by MattScorah** [comment]
@elpaso Thanks for the suggestion.

I have tried this now and can confirm that the following two approaches cause the rendering issue to go away (i.e. the layer renders correctly when the data source is changed):

- Reprojection of the raster datasets into the project projection (which is a projected CRS: Australian Albers, EPSG 3577)
- Changing the project projection to match the rasters (GDA94, EPSG 4283)

Additionally, a strange thing I noticed while doing this: if I delete the two legends from the layout before changing the data source the rendering issue also goes away.

I'd probably describe this as a "workaround" rather than a "fix" (I have many of these layers and so reprojection of all of them isn't an option, and I would really like the layout to be in a projected CRS because undistorted areas is important for these maps, so I was hoping to use the on-the-fly reprojection for this).

Thanks for the help!

**Comment by elpaso** [comment]
@MattScorah thanks for checking, this issue is quite difficult to debug (at least for me), I suspected that projection was involved because i noticed that the projector stage disappeared from the raster pipeline when changing the data source (that's why I asked you to check), this also explains why resetting projections "fixes"the issue.

I'll proceed with the debugging and look closer to the projector stage.

**Comment by elpaso** [comment]
@MattScorah can you please test the artifact from my PR? It fixes the issue for me.

https://github.com/qgis/QGIS/actions/runs/1238129870

**Comment by MattScorah** [comment]
@elpaso I can confirm that this fixes the issue for me as well, thank you for your work on this!
