### ISSUE TITLE
Qgis2threejs Exporter plugin crashes on first use

### ISSUE THREAD

**Issue by jalexispc** [qgis/QGIS#44928]
## User Feedback

I have just installed the Plugin Qgis2threejs and attempted to run it from the menu item Web > Qgis2threejs > Qgis2threejs Exporter. 

Immediately after the Qgis2threejs Exporter window  showed up on my screen I got this unexpected error from QGIS.  

So basically QGIS crashed on the first attempt to load the Qgis2threejs Exporter plug in. 

## Report Details

**Crash ID**: [d1ee07a76bcbe534692ec95dbb079c701e419808](https://github.com/qgis/QGIS/search?q=d1ee07a76bcbe534692ec95dbb079c701e419808&type=Issues)

**Stack Trace**
<pre>
DumpRegistryKeyDefinitions :
DumpRegistryKeyDefinitions :
DrvDescribePixelFormat :
_DescribeDriverPixelFormat :
LoadAvailableDrivers :
_DescribePrimaryPixelFormat :
wglNumHardwareFormats :
wglDescribePixelFormat :
wglChoosePixelFormat :
ChoosePixelFormat :
UserCallWinProcCheckWow :
DispatchClientMessage :
__fnINLPCREATESTRUCT :
KiUserCallbackDispatcherContinue :
NtUserCreateWindowEx :
VerNtUserCreateWindowEx :
CreateWindowInternal :
CreateWindowExW :
QWindowPrivate::create :
QOffscreenSurface::create :
WebCore::ParsedContentRange::headerValue :
WebCore::ParsedContentRange::headerValue :
WebCore::ParsedContentRange::headerValue :
WebCore::smallestRectWithAspectRatioAroundRect :
WebCore::HTMLPlugInElement::getNPObject :
WebCore::JSHTMLElement::pushEventHandlerScope :
WebCore::toJS :
</pre>

**QGIS Info**
QGIS Version: 3.18.1-Z�rich
QGIS code revision: 202f1bf7e5
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

### Steps to reproduce the issue

1- I have just installed the Plugin Qgis2threejs and attempted to run it from the menu item Web > Qgis2threejs > Qgis2threejs Exporter. 
2- Immediately after the Qgis2threejs Exporter window  showed up on my screen I got the unexpected crash from QGIS reported above

### Versions

QGIS version
3.18.1-Zürich
QGIS code revision
202f1bf7e5
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
Anaximandre; 
DEMto3D; 
Qgis2threejs; 
QGIS3_Delft3D_FM; 
db_manager; 
MetaSearch; 
processing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
@jalexispc you must report this in the plugin tracker, not here.
