### ISSUE TITLE
Geocentric data are not displayed properly

### ISSUE THREAD

**Issue by benoitdm-oslandia** [qgis/QGIS#44939]
### What is the bug or the crash?

3d data saved in geocentric projection (eg 4978) are not properly displayed when reprojected to 2D projections (eg 3857).

The main issue is due to clipping mechanisms: for all 3D points, coordinates are trimmed to 2D coordinates by selecting X and Y then clipped and at last reprojected to final CRS. 

This does not work for geocentric projections as the 3 coordinates are mandatory to reproject to final CRS.

For example, to render a linestring we extract the linestring from the geometry 
https://github.com/qgis/QGIS/blob/9ce295ebbd99719e856839a9c2b3c33c921d351f/src/core/symbology/qgssymbol.cpp#L1105
then clipped it from QgsCurve (3d) object to QPolygoneF (2d) 
https://github.com/qgis/QGIS/blob/9ce295ebbd99719e856839a9c2b3c33c921d351f/src/core/symbology/qgssymbol.cpp#L98
just be converting the QgsCurve to QPolygoneF
https://github.com/qgis/QGIS/blob/9ce295ebbd99719e856839a9c2b3c33c921d351f/src/core/qgsclipper.cpp#L43

### Steps to reproduce the issue

Import this dataset in postgis: [test_3d_202109031653.sql.zip](https://github.com/qgis/QGIS/files/7106741/test_3d_202109031653.sql.zip)

## Observations

Here is an example with a sphere (earth sized) in 4978 CRS shown in 4978 project:
![bug_reproject_4978](https://user-images.githubusercontent.com/64401067/132024006-c0ade714-e96e-4c11-8bde-49416a1260df.png)

and in 3857 project:
![bug_reproject_3857](https://user-images.githubusercontent.com/64401067/132023991-80f0d03b-aebf-4a22-b8e1-ae3189aa31c8.png)

## What's expected?

In the 2D view, the sphere in 3857 CRS should shown as flat as it is shown in 4978 CRS (because it is a sphere) not as the orange line.

### Versions

master

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

**Comment by benoitdm-oslandia** [comment]
I have not tried with a new QGIS profile as it is not relevant...

**Comment by alexbruy** [comment]
@benoitdm-oslandia what is state of this issue? I see that there are a few related PRs merged.

**Comment by benoitdm-oslandia** [comment]
@alexbruy indeed I forgot to close this issue! Thanks!
