### ISSUE TITLE
Rubber band regression: points added via addGeometry aren't visible on the canvas

### ISSUE THREAD

**Issue by nirvn** [qgis/QGIS#44934]
### What is the bug or the crash?

Point geometries added to a rubber band via addGeometry aren't displayed on the canvas anymore. That's a regression on master. As a consequence, point geometries aren't flashed on the canvas when focused via the locator's layer features filter, and more.

### Steps to reproduce the issue

Run the following script in the python console:

```
iface.mapCanvas().setExtent(QgsRectangle(-10,-10,10,10))
 
point = QgsGeometry( QgsPoint(0,5) )
rbp = QgsRubberBand( iface.mapCanvas(), QgsWkbTypes.PointGeometry )
rbp.addGeometry( point, QgsCoordinateReferenceSystem(), False )
rbp.setWidth(2)
rbp.setStrokeColor(QColor(255,0,0))
rbp.updatePosition();
rbp.update();
 
line = QgsGeometry( QgsLineString(QgsPoint(-10,0),QgsPoint(10,0)))
rbl = QgsRubberBand( iface.mapCanvas(), QgsWkbTypes.LineGeometry )
rbl.addGeometry( line, QgsCoordinateReferenceSystem(), False );
rbl.setWidth(2)
rbl.setStrokeColor(QColor(255,0,0))
rbl.updatePosition();
rbl.update();
```

Notice only the line is shown while the point is missing:
![image](https://user-images.githubusercontent.com/1728657/131969384-f925f5ac-ab5c-46b3-bc8f-fb96e0c6c3e5.png)

### Versions

QGIS master (3.21)

**Comment by nirvn** [comment]
@gioman , it's not Python-specific, same issue in C++.

**Comment by tudorbarascu** [comment]
I don't know if it's related, but just noticed that adding a Point in the map canvas doesn't show the point while the user is filling the feature form (tested on Master and 3.16.10).
