### ISSUE TITLE
Fit Cells/Nodes selector is missing in SAGA tools

### ISSUE THREAD

**Issue by moet1972** [qgis/QGIS#44932]
### What is the bug or the crash?

In QGIS 3.20 Versions with SAGA 7.8.2 implemented I experience that in several Raster algorithms like Features to Raster, Resampling, Multilevel B-Spline-Interpolation the selector "Fit cells" / "Fit nodes" is missing. The result is that "Fit nodes" is selected by default and the calculated raster is shifted by half of the cell size in both dicections even if XMIN/XMAX/YMIN/YMAX are defined correctly.
In older Versions with SAGA 2.3.2 this selector was there. Without it a lot of SAGA algorithms are not usable

### Steps to reproduce the issue

1. Go to SAGA (7.8.2)
2. Click on Raster - Rasterizing - Features to Raster (or other raster/grid algorithms described above)
3. Fit cells/nodes selector is missing 

### Versions

3.20.2-Odense

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
> In QGIS 3.20 Versions with SAGA 7.8.2

@moet1972 on what OS?

**Comment by moet1972** [comment]
@gioman Windows 10

**Comment by gioman** [comment]
@moet1972 use instead https://github.com/north-road/qgis-processing-saga-nextgen or https://plugins.bruy.me/plugins/plugins.xml#saga The problem is that on Windows are used description files pulled from the SAGA project, which are frequently wrong or sub optimal. There are other tickets with similar issues, and the solution is taking back control on that description files.

**Comment by moet1972** [comment]
@gioman Thank you for your advice, but the problem is still not solved. I tried both plugins: 
SAGA NextGen with SAGA 7.20, 7,60 and 7.91. Here the menu in Processing looks identical with the "build-in" SAGA-menu and the selector "Fit cells/nodes" in the mentioned algorithms is missing as well.
The other plugin "SAGA for Processing" working with SAGA 7.60 does have the "Fit cells/nodes" selector but does create a strange error message when you define the Extent of the Output Raster and without defining the extent the Output Raster will be shifted  as well

**Comment by gioman** [comment]
> Thank you for your advice, but the problem is still not solved. I tried both plugins:
> SAGA NextGen with SAGA 7.20, 7,60 and 7.91. Here the menu in Processing looks identical with the "build-in" SAGA-menu and the selector "Fit cells/nodes" in the mentioned algorithms is missing as well.
> The other plugin "SAGA for Processing" working with SAGA 7.60 does have the "Fit cells/nodes" selector but does create a strange error message when you define the Extent of the Output Raster and without defining the extent the Output Raster will be shifted as well

@moet1972 I see that looking the the 3rd party plugins they seem to have both their own issues (and I'm looking at the resampling tool). Anyway while we try to sort out this problem in core you may want to tweak the description files in your own QGIS installation. Look for example at the files in

C:\Program Files\QGIS 3.20.2\apps\qgis\python\plugins\processing\algs\saga\description

edit the ones you need with a text editor by adding/changing the necessary parameters, look for example at

https://github.com/qgis/QGIS/blob/master/python/plugins/sagaprovider/description/Resampling.txt

for inspiration. Then save and restart QGIS.

**Comment by alexbruy** [comment]
SAGA Provider was not maintained and now remowed from QGIS (see #50834). Users are encouraged to use the 3rd-party plugins instead.
