### ISSUE TITLE
Vertex Editor has shortage of accuracy

### ISSUE THREAD

**Issue by extrame911** [qgis/QGIS#44931]
### What is the bug or the crash?

There are three different nodes in one vector(WGS84), but in Vertex Editor they looks like the same.

### Steps to reproduce the issue

These are the exact coordinates of the first three shape points:
_123.377802,41.707730
123.377824,41.707722
123.377845,41.707714_

But the look the same in vertex editor.

![图片](https://user-images.githubusercontent.com/7876532/131961716-7a65c4f7-065f-4f6e-87e8-f0ee8c901eab.png)
![图片](https://user-images.githubusercontent.com/7876532/131961744-78479c69-63e7-4658-95b9-62226808a38d.png)
![图片](https://user-images.githubusercontent.com/7876532/131961785-d098dd9b-bc4f-4b38-af78-d79a105fa58e.png)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.16.7-Hannover | QGIS code revision | 0471743889
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | db_manager; processing

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
I think that if you want accuracy, you shouldn't use WGS84 CRS but a projected CRS appropriated to your study area.

In latest QGIS release (>3.20), a warning is displayed for WGS84 CRS (#43088).

**Comment by extrame911** [comment]
> projected

I think that is another problem.

If you can draw points at different positions, Vertex Editor is better to show that they have different coordinates.
It is better to keep the consistency between the description and data display, so as not to cause other misunderstandings.

**Comment by agiudiceandrea** [comment]
> a warning is displayed for WGS84 CRS (#43088).

AFAIK, the warning is not about geographic versus projected CRSs, but about CRSs based on a datum ensemble: the warning is diplayed also for some projected CRSs and is not diplayed for some other geographic CRSs.

I think this issue is legit and could be fixed just adding a setting to choose the number of decimal places for the Vertex Editor.

**Comment by extrame911** [comment]
At the equator, 0.0001 degrees≈11 meters.
In WGS84(G1150), the accuracy is less than meter.

**Comment by gioman** [comment]
@extrame911 the number of decimals shown here is higher

![image](https://user-images.githubusercontent.com/1951107/131970950-6101c0af-c410-443d-95e9-209caddfcef6.png)

**Comment by extrame911** [comment]
> 
> 
> > a warning is displayed for WGS84 CRS (#43088).
> 
> AFAIK, the warning is not about geographic versus projected CRSs, but about CRSs based on a datum ensemble: the warning is diplayed also for some projected CRSs and is not diplayed for some other geographic CRSs.
> 
> I think this issue is legit and could be fixed just adding a setting to choose the number of decimal places for the Vertex Editor.

That's exactly what I thought.

**Comment by nicogodet** [comment]
> the warning is not about geographic versus projected CRSs, but about CRSs based on a datum ensemble

Yes, my bad.
Ignore my previous message..

**Comment by gioman** [comment]
@extrame911 please try with a new QGIS profile.

**Comment by extrame911** [comment]
> 
> 
> @extrame911 please try with a new QGIS profile.

I install another version:3.20.2-Odense
That was fixed!
Thank you very much!


![图片](https://user-images.githubusercontent.com/7876532/131972619-d6b0fa99-5f4d-4bf2-b8e1-9fa7f554baf6.png)

**Comment by agiudiceandrea** [comment]
@gioman the issue is still present in QGIS 3.16.10.

**Comment by gioman** [comment]
> @gioman the issue is still present in QGIS 3.16.10.

@agiudiceandrea a dev should say then if the fix is backportable.
