### ISSUE TITLE
Regression: QGIS master won't recognize .osm files as a valid vector dataset

### ISSUE THREAD

**Issue by nirvn** [qgis/QGIS#44947]
### What is the bug or the crash?

.osm datasets won't open in QGIS master anymore. 

@nyalldawson , _maybe_ it has to do with the sublayer revamp.

### Steps to reproduce the issue

Here's a sample dataset:
[test.zip](https://github.com/qgis/QGIS/files/7109205/test.zip)

If I check the test.osm dataset using ogrinfo, sublayers properly show up:

```
INFO: Open of `f.osm'
      using driver `OSM' successful.
1: points (Point)
2: lines (Line String)
3: multilinestrings (Multi Line String)
4: multipolygons (Multi Polygon)
5: other_relations (Geometry Collection)
```

However, if I drag n drop (or open via the data source dialog's vector panel), QGIS throws an error telling me it's an invalid dataset.

### Versions

QGIS master.

**Comment by nyalldawson** [comment]
I can't reproduce -- it all works fine for me.

**Comment by nirvn** [comment]
Hm, can't reproduce on my secondary machine either. Closing, seems issue is localized to my main workstation. Sorry for the noise.
