### ISSUE TITLE
QGIS unexpectedly ended

### ISSUE THREAD

**Issue by kobusburger** [qgis/QGIS#44943]
## User Feedback

I was closing QGIS

## Report Details

**Crash ID**: [84f1f0128c6d76df98959cb9269da052788e8ba6](https://github.com/qgis/QGIS/search?q=84f1f0128c6d76df98959cb9269da052788e8ba6&type=Issues)

**Stack Trace**
<pre>
QgsExpressionContextScope::addVariable :
QgsProject::createExpressionContextScope :
QgsVectorLayerFeatureIterator::createExpressionContext :
QgsVectorLayerFeatureIterator::prepareExpression :
QgsVectorLayerFeatureIterator::prepareFields :
QgsVectorLayerFeatureIterator::QgsVectorLayerFeatureIterator :
QgsVectorLayer::getFeatures :
PyInit__core :
PyArg_ParseTuple_SizeT :
PyEval_EvalFrameDefault :
PyFunction_Vectorcall :
PyVectorcall_Call :
PyObject_Call :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyFunction_Vectorcall :
PyFloat_FromDouble :
PyVectorcall_Call :
PyObject_Call :
QgsPresetSchemeColorRamp::clone :
QgsExpressionFunction::run :
QgsPresetSchemeColorRamp::clone :
QgsExpressionNodeFunction::evalNode :
QgsExpressionNode::eval :
QgsExpression::evaluate :
QgsVectorLayerFeatureIterator::addExpressionAttribute :
QgsVectorLayerFeatureIterator::addVirtualAttributes :
QgsVectorLayerFeatureIterator::fetchFeature :
QgsAbstractFeatureIterator::nextFeature :
QgsVectorLayerJoinInfo::setEditable :
QgsVectorLayerJoinInfo::setEditable :
QgsVectorLayerJoinInfo::setEditable :
QgsMapRendererParallelJob::renderLayerStatic :
QgsArchive::zip :
QgsImageOperation::overlayColor :
QgsImageOperation::stackBlur :
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.20.2-Odense
QGIS code revision: 9f59a156
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.1
Running against GDAL: 3.3.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

### Steps to reproduce the issue

I cannot reproduce the crash

### Versions

QGIS version
3.20.2-Odense
QGIS code revision
9f59a156
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.1
PROJ version
8.1.0
EPSG Registry database version
v10.027 (2021-06-17)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 1909

Active Python plugins
changeDataSource
GeometryShapes
kmltools
latlontools
layer2kmz
networks
profiletool
QGISSortAndNumber-master
QRectangleCreator
db_manager
MetaSearch
processing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@kobusburger try with a new QGIS profile, no 3rd party plugins installed.

**Comment by kobusburger** [comment]
This is not an issue I  can repeat and therefore close it
