### ISSUE TITLE
Failed to load python

### ISSUE THREAD

**Issue by zoydeep** [qgis/QGIS#44957]
### What is the bug or the crash?

Failed to load SIP module and QGIS Tool option doesn't appear after the software loads.

### Steps to reproduce the issue

![Capture](https://user-images.githubusercontent.com/71568227/132211372-81ffbf8e-3b1c-4ae9-b66d-bdf6b952de5e.JPG)

### Versions

3.20.2-1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@zoydeep seems a local issue, not a general one. Just did an installation on a Win10 machine and is ok.

**Comment by zoydeep** [comment]
The issue has been resolved by deleting all the Python folders in installation directories after uninstallation of the existing QGIS. After that a fresh installation of QGIS was done.
