### ISSUE TITLE
Adding a point doesn't show any marker while the user is filling the form

### ISSUE THREAD

**Issue by tudorbarascu** [qgis/QGIS#44967]
### What is the bug or the crash?

Bug.

Adding a Point in the map canvas doesn't show the point while the user is filling the feature form (tested on Master and 3.16.10). For Lines and Polygons it works as it should. Can replicate on Windows and Debian Bullseye.

### Steps to reproduce the issue

1. Add a point in any point layer 
2. There is no marker..  You can see in the picture, that for line.. there is

![pt_bug](https://user-images.githubusercontent.com/3179646/132288375-6a8eb89f-2e40-4a64-a7e8-3aea5765cd37.png)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.21.0-Master | QGIS code revision | ce0d2bd809
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.2
GDAL/OGR version | 3.3.1
PROJ version | 7.2.1
EPSG Registry database version | v10.008 (2020-12-16)
GEOS version | 3.9.1dev-CAPI-1.14.1
SQLite version | 3.34.1
PostgreSQL client version | 13.4 (Debian 13.4-1.pgdg110+1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Debian GNU/Linux 11 (bullseye)
  |   |   |  
Active Python plugins | 

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by uclaros** [comment]
Did you check if #44950 fixes this?

**Comment by tudorbarascu** [comment]
@uclaros Yes, I build from source after the fix was merged.

**Comment by elpaso** [comment]
> @uclaros Yes, I builded the master from source after the fix was merged.

If it's fixed can we close this?

**Comment by uclaros** [comment]
> If it's fixed can we close this?

No, the mentioned PR was not relevant. The bug is there on master.

**Comment by alexbruy** [comment]
Works fine in the latest master (8c62d89729). @tudorbarascu can you re-test?
