### ISSUE TITLE
Locator: QGIS crashes when searching and selecting features in all layers

### ISSUE THREAD

**Issue by romanoe** [qgis/QGIS#44960]
## User Feedback

QGIS crashes when using locator for searching features in all layers. Error appeared with 3.16.10 and not encountered with previous 3.16.X. 

**Project demo:**  [test.zip](https://github.com/qgis/QGIS/files/7116452/test.zip)

![locator_error](https://user-images.githubusercontent.com/32194904/132229027-38641561-1a81-4bfe-8d89-1e48705f81ae.gif)

## Report Details

**Crash ID**: [e5635ddf59142d45652c49902985d76e41c70377](https://github.com/qgis/QGIS/search?q=e5635ddf59142d45652c49902985d76e41c70377&type=Issues)

**Stack Trace**
<pre>
QVariant::toBool :
QgsAllLayersFeaturesLocatorFilter::triggerResultFromAction qgsinbuiltlocatorfilters.cpp:716
QgsLocatorModelBridge::triggerResult qgslocatormodelbridge.cpp:49
QgsLocatorWidget::acceptCurrentEntry qgslocatorwidget.cpp:356
QMetaObject::activate :
QAbstractItemView::activated :
QTreeView::mouseDoubleClickEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1637
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.16.10-Hannover
QGIS code revision: e5b665e952
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

### Steps to reproduce the issue

1. Enter number/id in locator
2. Select feature
3. QGIS crashes

### Versions

3.16.10

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Tested with Postgresql database and shapefiles.

**Comment by gioman** [comment]
Confirmed on 3.16 on Windows but not on master/linux.

**Comment by 3nids** [comment]
fixed in #44973
