### ISSUE TITLE
Problem starting QGIS

### ISSUE THREAD

**Issue by isad7** [qgis/QGIS#44978]
### What is the bug or the crash?

![Qgis 3 10_3 16_3 20](https://user-images.githubusercontent.com/90251666/132326798-75414fb2-b331-4ab7-af4b-e683422d29a8.JPG)

I have some problems with all QGIS 3 versions. I cannot use the software because when I open the software on the desktop this white window appears which blocks the software and I cannot do anything.
Here attached a screenshot

### Steps to reproduce the issue

![Qgis 3 10_3 16_3 20](https://user-images.githubusercontent.com/90251666/132327416-c00da1ec-4087-4f69-8da0-6a47691a1935.JPG)

### Versions

QGIS 3.10, QGIS 3.16, QGIS 3.20

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by uclaros** [comment]
Seems like some plugin of yours is malfunctioning.
Try with a new QGIS profile and start enabling your plugins one by one until you find the offending one.

**Comment by isad7** [comment]
Thank you, it was indeed a plugin problem! the corrupted one was Spectre viewer

**Comment by DelazJ** [comment]
Great! The next step is to report in the plugin issue tracker.
