### ISSUE TITLE
QGIS crashes opening the "server" tab in project properties

### ISSUE THREAD

**Issue by julienIII** [qgis/QGIS#44975]
### What is the bug or the crash?

It crashes almost everytime I want to set parameters of the QGIS project, for the get capabilities

### Steps to reproduce the issue

1.Go to project
2.Click on properties
3.Go to QGIS server
4.Crash

### Versions

Version de QGIS | 3.16.0-Hannover | Révision du code | 43b64b13f3

Compilé avec Qt | 5.11.2 | Utilisant Qt | 5.11.2
Compilé avec GDAL/OGR | 3.1.4 | Utilisé avec GDAL/OGR | 3.1.4
Compilé avec GEOS | 3.8.1-CAPI-1.13.3 | Utilisé avec GEOS | 3.8.1-CAPI-1.13.3
Compilé avec SQLite | 3.29.0 | Fonctionne avec SQLite | 3.29.0
Version du client PostgreSQL | 11.5 | Version de SpatiaLite | 4.3.0
Version de QWT | 6.1.3 | Version de QScintilla2 | 2.10.8
Compilé avec PROJ | 6.3.2 | Fonctionne avec PROJ | Rel. 6.3.2, May 1st, 2020
Version de l'OS | Windows 10 (10.0)
Extensions Python actives | DissolveWithStats; gban; maplibrary; mask; mmqgis; quick_map_services; refFunctions; Thematic-master; db_manager; processing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by Gustry** [comment]
> 3.16.0-Hannover

Too old, upgrade to a latest version 3.16.10 as written https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule

> I  tried with a new QGIS profile

It's maybe linked to a plugin saving properties, please do as well.

**Comment by julienIII** [comment]
I upgraded to the 3.16.10 version, as you advised and I don't have this issue anymore. Thank you!
