### ISSUE TITLE
Warning message 'Cannot create temporary SpatiaLite cache' when adding many WFS-layers

### ISSUE THREAD

**Issue by ralphschulerSZ** [qgis/QGIS#44971]
### What is the bug or the crash?

If you add many WFS-layers, you get following warning messages in the message pane:

![grafik](https://user-images.githubusercontent.com/11614900/132299931-2b854199-be6e-4aab-835e-873586af2068.png)

In consequence of these messages, the attribute table shows no data:

![grafik](https://user-images.githubusercontent.com/11614900/132300168-30905dbf-60ff-44d2-b0cc-87cfbc9622d6.png)

### Steps to reproduce the issue

1. Add a WFS-URL https://map-t.geo.sz.ch/mapserv_proxy
2. Add some layers (70 should be enough)

...or you open the attached QGIS-project file:
[70-wfs-layer-QGIS3.zip](https://github.com/qgis/QGIS/files/7119671/70-wfs-layer-QGIS3.zip)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS-Version | 3.10.5-A Coruña | QGIS-Codeversion | 984615fe1e
-- | -- | -- | --
Kompiliert gegen Qt | 5.11.2 | Laufendes Qt | 5.11.2
Kompiliert mit GDAL/OGR | 3.0.4 | Läuft mit GDAL/OGR | 3.0.4
Kompiliert mit GEOS | 3.8.1-CAPI-1.13.3 | Läuft mit GEOS | 3.8.1-CAPI-1.13.3
Kompiliert mit SQLite | 3.29.0 | Läuft mit SQLite | 3.29.0
PostgreSQL-Client-Version | 11.5 | SpatiaLite-Version | 4.3.0
QWT-Version | 6.1.3 | QScintilla2-Version | 2.10.8
Kompiliert mit PROJ | 6.3.1 | Läuft mit PROJ | Rel. 6.3.1, February 10th, 2020
BS-Version | Windows 10 (10.0)
Aktive Python-Erweiterungen | qfieldsync; QgisModelBaker; db_manager; MetaSearch; processing

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by rouault** [comment]
The issue here is SpatiaLite-Version  4.3.0.  It had a limit of 50 layers simultanously opened. This has been fixed in Spatialite 5. You'll need to update to a more recent QGIS version
