### ISSUE TITLE
Auto-collect all GPS positions in a point layer

### ISSUE THREAD

**Issue by klainkaliber** [qgis/QGIS#44993]
### Feature description

Currently, using the GPS information panel, it is possible to save a line, created from a connected GPS device to the current layer when in edit mode.
Therefore, the user has to (reapeatedly) click the "Add line" button in the panel.

The improvement would be if I am able to specify a point layer that records every position the attached GPS device sends - without explicitly clicking an "Add" button, as long as the GPS sends positions.

Maybe a third button "Add all incoming points to current point layer" would do the job.

A "auto recording" of all incoming points would seem to me a quite obvious feature and I spent some time searching for this (in vein). 
At least for me the check box "automatically save added feature" was quite unintuitive as I still have to click "Add line" - which I would not expect to be needed if it says "automatically".

Even more refined it would be if additional information from the NMEA stream gets recorded like fix type, speed, heading, number of satellites, etc.
That would need a GUI to relate the data to the fields of the point layer (but this would be a minor concern for me).

**Comment by nyalldawson** [comment]
Fixed by https://github.com/qgis/QGIS/pull/50898

**Comment by klainkaliber** [comment]
Great! Thanks!
