### ISSUE TITLE
georeferencing trouble

### ISSUE THREAD

**Issue by jfigueroa222** [qgis/QGIS#44994]
### What is the bug or the crash?

There are some problem with PSAD 56/19 S. When i used this referencing system, that must be un south america, the qgis bring me to europe and whe i use the raster referencig tool, with knowin coordinated, the georeferencing tool, teke my image to some place in the galaxy.
Help!

### Steps to reproduce the issue

Raster
georeferenciador

### Versions

3.20.1

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
> ### Steps to reproduce the issue
> 
> Raster
> georeferenciador

@jfigueroa222 that is vastly uncomplete. Please add all the details:

1) attach/link the image you are georeferencing
2) attach the GCP table
3) list the georef configs (CRS EPSG code, resampling used, algorithm used, etc.).

**Comment by jfigueroa222** [comment]
20210908_Puntos control.qml
<https://drive.google.com/file/d/1i5F2-qgXG6-O1DSb283QTC_ZjFUFyAKI/view?usp=drive_web>
 AMA_VDE_ORTOFOTO.tif
<https://drive.google.com/file/d/1pemd35smTZEiaJ0TeTPDVIYNrxJvsDAY/view?usp=drive_web>

[image: image.png]

**Comment by gioman** [comment]
> 20210908_Puntos control.qml <https://drive.google.com/file/d/1i5F2-qgXG6-O1DSb283QTC_ZjFUFyAKI/view?usp=drive_web> AMA_VDE_ORTOFOTO.tif <https://drive.google.com/file/d/1pemd35smTZEiaJ0TeTPDVIYNrxJvsDAY/view?usp=drive_web>

@jfigueroa222 links are password protected.

**Comment by jfigueroa222** [comment]
try now

**Comment by gioman** [comment]
> try now

@jfigueroa222 still password protected.

**Comment by jfigueroa222** [comment]
https://drive.google.com/file/d/1i5F2-qgXG6-O1DSb283QTC_ZjFUFyAKI/view?usp=sharing
https://drive.google.com/file/d/1pemd35smTZEiaJ0TeTPDVIYNrxJvsDAY/view?usp=sharing

**Comment by gioman** [comment]
@jfigueroa222 

![image](https://user-images.githubusercontent.com/1951107/132574303-43eaf15d-c00a-4699-8500-82cee8229833.png)

**Comment by roya0045** [comment]
Georeferencing an already georeferenced file is indeed problematic, waiting on the fix to be accepted.

I tried with PSAD geographi, and 19S from a non-spatial raster, no issue.

**Comment by kikislater** [comment]
Old issue but some inputs may be:
- georeferencing a georeferenced raster file is not possible directly and not implemented in qgis.
- it works in grass gis with embedded georeferencer
- removing georeference is needed before using gdal_translate with -gcp option and gdal_warp. It could be done in 2 way:
          - gdal_translate with PROFILE=BASELINE option like `gdal_translate -co PROFILE=BASELINE in out`
          - gdal_edit.py with  `-unsetgt` option like `gdal_edit.py  -unsetgt file.tif`
