### ISSUE TITLE
Interpolated line symbol layer not working when the vector layer CRS != project CRS

### ISSUE THREAD

**Issue by nirvn** [qgis/QGIS#45008]
### What is the bug or the crash?

Using the interpolated line symbol layer fails to render anything when the vector layer CRS doesn't match the project CRS.

### Steps to reproduce the issue

1. Create a new project, set its CRS to a meter-based one, make sure the extent's scale is large enough
2. Add a new memory linestring layer, set its CRS to WGS84
3. Add a line across your canvas
4. Open the styling panel, change the symbology's symbol layer to interpolated line
5. Notice how nothing is drawn.
6. The end.

### Versions

QGIS master

**Comment by gioman** [comment]
@nirvn duplicate of https://github.com/qgis/QGIS/issues/44464 ?

**Comment by nirvn** [comment]
Correct.
