### ISSUE TITLE
Copying 'QGIS version' (as proposed in issue tracker) from 'About dialog' contains partial html

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS#45016]
### What is the bug or the crash?

If I copy the version information from my about box (like asked when creating an issue) I get (literally, so INCLUDING the html part!):

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>


QGIS version | 3.18.2-Zürich | QGIS code revision | e3e45fb8dd
-- | -- | -- | --
Compiled against Qt | 5.15.2 | Running against Qt | 5.15.2
Compiled against GDAL/OGR | 3.2.1 | Running against GDAL/OGR | 3.2.2
Compiled against GEOS | 3.9.0-CAPI-1.16.2 | Running against GEOS | 3.9.1-CAPI-1.14.2
Compiled against SQLite | 3.34.1 | Running against SQLite | 3.36.0
PostgreSQL Client Version | 13.2 (Debian 13.2-1) | SpatiaLite Version | 5.0.1
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.6
Compiled against PROJ | 7.2.1 | Running against PROJ | Rel. 7.2.1, January 1st, 2021
OS Version | Debian GNU/Linux bookworm/sid | This copy of QGIS writes debugging output.
Active python plugins | QuickWKT; nominatim_locator_filter; NITK_RS-GIS_17; pdokservicesplugin; plugin_reloader; QuickOSM; HelloWorldPlugin; HCMGIS; GeoCoding; simplesvg; orientation; processing

</body></html>
```

Which is then shown as:

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.18.2-Zürich | QGIS code revision | e3e45fb8dd
-- | -- | -- | --
Compiled against Qt | 5.15.2 | Running against Qt | 5.15.2
Compiled against GDAL/OGR | 3.2.1 | Running against GDAL/OGR | 3.2.2
Compiled against GEOS | 3.9.0-CAPI-1.16.2 | Running against GEOS | 3.9.1-CAPI-1.14.2
Compiled against SQLite | 3.34.1 | Running against SQLite | 3.36.0
PostgreSQL Client Version | 13.2 (Debian 13.2-1) | SpatiaLite Version | 5.0.1
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.6
Compiled against PROJ | 7.2.1 | Running against PROJ | Rel. 7.2.1, January 1st, 2021
OS Version | Debian GNU/Linux bookworm/sid | This copy of QGIS writes debugging output.
Active python plugins | QuickWKT; nominatim_locator_filter; NITK_RS-GIS_17; pdokservicesplugin; plugin_reloader; QuickOSM; HelloWorldPlugin; HCMGIS; GeoCoding; simplesvg; orientation; processing

</body></html>

Instead of the cleaner

QGIS version | 3.18.2-Zürich | QGIS code revision | e3e45fb8dd
-- | -- | -- | --
Compiled against Qt | 5.15.2 | Running against Qt | 5.15.2
Compiled against GDAL/OGR | 3.2.1 | Running against GDAL/OGR | 3.2.2
Compiled against GEOS | 3.9.0-CAPI-1.16.2 | Running against GEOS | 3.9.1-CAPI-1.14.2
Compiled against SQLite | 3.34.1 | Running against SQLite | 3.36.0
PostgreSQL Client Version | 13.2 (Debian 13.2-1) | SpatiaLite Version | 5.0.1
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.6
Compiled against PROJ | 7.2.1 | Running against PROJ | Rel. 7.2.1, January 1st, 2021
OS Version | Debian GNU/Linux bookworm/sid | This copy of QGIS writes debugging output.
Active python plugins | QuickWKT; nominatim_locator_filter; NITK_RS-GIS_17; pdokservicesplugin; plugin_reloader; QuickOSM; HelloWorldPlugin; HCMGIS; GeoCoding; simplesvg; orientation; processing

### Steps to reproduce the issue

- Open About box via Help / About 
- select all text in the TextArea (from bottom to top)
- paste it in the versions box below

Strange note: if I paste it into vim or gedit, I get a clean output

### Versions

(manually cleaned by me)

QGIS version | 3.21.0-Master | QGIS code revision | 4e0d0f6692d
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.7
GDAL/OGR version | 3.2.2
PROJ version | 7.2.1
EPSG Registry database version | v10.008 (2020-12-16)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.36.0
PostgreSQL client version | 13.4 (Debian 13.4-3)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Debian GNU/Linux bookworm/sid
  |   |   |  
This copy of QGIS writes debugging output.
  |   |   |  
Active Python plugins | QuickWKTnominatim_locator_filterNITK_RS-GIS_17pdokservicespluginplugin_reloaderQuickOSMHelloWorldPluginHCMGISGeoCodingsimplesvgorientationsagaproviderprocessinggrassprovider

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by DelazJ** [comment]
@rduivenvoorde duplicate of 43739?
I did not try recently but I don't think my "plugins list" is as cleaned as in your first examples. I actually got the third one (everything attached), which is not a cleaned version (and widen the table and hide the version sha)

**Comment by Gustry** [comment]
IMHO, we should add a button "Copy table content" or similar, it would be easier than "ctrl+a, ctrl+c" etc ... But it has been discussed before already IIRC

**Comment by rduivenvoorde** [comment]
> @rduivenvoorde duplicate of #43739?
> I did not try recently but I don't think my "plugins list" is as cleaned as in your first examples. I actually got the third one (everything attached), which is not a cleaned version (and widen the table and hide the version sha)

Yes definitly... sorry, search for 'version' or 'about'... but missed this one.
