### ISSUE TITLE
Qgis hangs when trying to open a project with a 3D view opened

### ISSUE THREAD

**Issue by kerkovits** [qgis/QGIS#45038]
### What is the bug or the crash?

Qgis hangs if I open the project from the left "Browser" panel.  The geopackage remains locked after I force QGIS to quit. The project opens and closes correctly if I open it by double-click in the Windows Explorer or I drag and drop it from the explorer to QGIS.

[mo.zip](https://github.com/qgis/QGIS/files/7152596/mo.zip)

### Steps to reproduce the issue

On the left "browser" panel navigate to the directory of the project and drag the file onto the map canvas. The project should load with all layers, but QGIS freezes.

### Versions

QGIS verzió | 3.20.3-Odense | QGIS kód változat | 495fbaec
-- | -- | -- | --
Qt verzió | 5.15.2
Python verzió | 3.9.5
GDAL/OGR verzió | 3.3.1
PROJ verzió | 8.1.1
EPSG regisztrációs adatbázis verzió | v10.028 (2021-07-07)
GEOS verzió | 3.9.1-CAPI-1.14.2
SQLite verzió | 3.35.2
PDAL verzió | 2.3.0
Postgresql kliens verzió | 13.0
SpatiaLite verzió | 5.0.1
QWT verzió | 6.1.3
QScintilla2 verzió | 2.11.5
OS verzió | Windows 10 Version 2009
  |   |   |  
Aktív Python modulok | db_managerMetaSearchprocessing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Raster layers are not included due to their large size. Of course, the project would crash the same way if they were present. Just click on "keep missing layers" to load the project. If raster layers are absolutely necessary to reproduce the issue, I can attach them.

**Comment by uclaros** [comment]
Confirmed on Debian too.
It is related to having an open 3d map window on the saved project in combination with opening the project via drag-and-drop through the browser panel.
The project can be opened successfully through the browser panel by right-click > Open Project instead of drag-and-drop.

Any project with an open 3d window will freeze if drag-and-dropped from the browser panel after leaving the following on the log:
```
│2021-09-13T14:35:43.893  Xlib: sequence lost (0x14edf > 0x4ee1) in reply type 0x0!                                                                 │
│2021-09-13T14:35:43.893  Xlib: sequence lost (0x14ee4 > 0x4ee6) in reply type 0x0!                                                                 │
│2021-09-13T14:35:43.901  Xlib: sequence lost (0x14efe > 0x4f00) in reply type 0x0!                                                                 │
│2021-09-13T14:35:43.902  Xlib: sequence lost (0x14f03 > 0x4f05) in reply type 0x0!
````

**Comment by kannes** [comment]
I can confirm this on 3.24 on Archlinux. QGIS eats all CPU cores and hangs seemingly forever.
No messages in my terminal though.

**Comment by nyalldawson** [comment]
This is fixed by https://github.com/qgis/QGIS/pull/54845
