### ISSUE TITLE
QGIS 3.16 crashed on double-clicking feature properties

### ISSUE THREAD

**Issue by jpdupuy** [qgis/QGIS#45039]
### What is the bug or the crash?

Crash ID: 19f66a24b6a983734131cc419654727385eb7331

Stack Trace

QObject::parent :
QLayout::addChildWidget :
QStackedLayout::insertWidget :
QgsVectorLayerProperties::addPropertiesPageFactory :
QgisApp::showLayerProperties :
QgisApp::layerProperties :
QgisApp::layerTreeViewDoubleClicked :
QMetaObject::activate :
QAbstractItemView::doubleClicked :
QTreeView::mouseDoubleClickEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.16.4-Hannover
QGIS code revision: 654e76b3cb
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

### Steps to reproduce the issue

1- open a project 
2- double clic on a feature in the layer panel (to open the properties)
3- see above error message

### Versions

QGIS Version: 3.16.4-Hannover

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by DelazJ** [comment]
@jpdupuy 3.16.4 is a bit old. Please update to 3.16.11 and test again. thanks

**Comment by jpdupuy** [comment]
We are waiting for the next LTR release. I have installed QGIS 3.20 in parallel to QGIS 3.16.4.
I upgraded the latest QFieldSync 4.0.0.Beta-12 and believe this created this issue (since this crash did not happen in the past)

**Comment by jpdupuy** [comment]
I uninstalled the QFIELDSYNC plugin, and it does not crash anymore when I try to open the layer properties.
Therfore you can close this issue

**Comment by DelazJ** [comment]
OK. Thanks for the feedback.
Could be nice to report the issue on the QFieldSync plugin repository if not yet done.
