### ISSUE TITLE
White block by printing WMS

### ISSUE THREAD

**Issue by pdorio** [qgis/QGIS#45042]
### What is the bug or the crash?

Our client has prepared a QGIS project with printing templates. In some cases, printing is successful, in others white boxes appear.

### Steps to reproduce the issue

To reproduce:

1. Open the attached qgz file
2. Open the print template "Katasterkarte".
3. Generate the pdf file

[1631521203_Q_GIS_v2.zip](https://github.com/qgis/QGIS/files/7159294/1631521203_Q_GIS_v2.zip)

### Versions

The QGIS used are 3.16 and 3.10

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@pdorio the WMS Service https://geoservices.buergernetz.bz.it/gsmaster/p_bz-orthoimagery/wms returns code 403, forbidden.

**Comment by pdorio** [comment]
@gioman see the new attachment

**Comment by gioman** [comment]
@pdorio no issues on both Windows and Linux (3.20 and master), can you give it a try on 3.20?

**Comment by gioman** [comment]
![image](https://user-images.githubusercontent.com/1951107/133270085-d64af5ba-eb08-4c05-86ef-c9d8f07b31c3.png)

**Comment by agiudiceandrea** [comment]
No issue with QGIS 3.16 (OSGeo4W v1) on Windows 7.

**Comment by Gustry** [comment]
> The QGIS used are 3.16 and 3.10

Which 3.10 and 3.16?
They both got some bugfixes about cache and blocking network request in layouts IIRC.
Maybe you have some cache issue ? (and not for us, because freshly downloaded)

Everything is alright for me as well on latest 3.16.

**Comment by pdorio** [comment]
@gioman  The customer (provincial user) has encountered this issue on QGIS 3.10 LTR
I have experienced the same issue on version 3.16 LTR.
Unfortunately we cannot upgrade to version 3.20 until all PCs are replaced with 64bit.

@Gustry I emptied the cache

**Comment by gioman** [comment]
>  Unfortunately we cannot upgrade to version 3.20 until all PCs are replaced with 64bit.

@pdorio see above, for others is ok also on 3.16.

**Comment by Gustry** [comment]
@pdorio The full version number X.Y.Z

**Comment by pdorio** [comment]
I am closing the ticket because, using another WMS service, the problem does not exist. The source must be investigated
