### ISSUE TITLE
QGIS randomly crash

### ISSUE THREAD

**Issue by wmeinolf** [qgis/QGIS#45041]
## User Feedback

Loaded QGIS and did some work in Windows Explorer. Since I had random crashes during the last days since 3.20.2 I finally removed old Installer and 3.18 as well as new installer and 3.20. Did registry clean and a fresh install this weekend. Also new profile did not help. What else can I do? 

## Report Details

**Crash ID**: [2c4e219e6236773a0e7860956da5d564e8a7bbc5](https://github.com/qgis/QGIS/search?q=2c4e219e6236773a0e7860956da5d564e8a7bbc5&type=Issues)

**Stack Trace**
<pre>
RtlpFreeHeapInternal :
RtlFreeHeap :
_free_base :
proj_log_level :
proj_destroy :
QgsCoordinateReferenceSystem::removeFromCacheObjectsBelongingToCurrentThread :
QgsProjUtils::crsToSingleCrs :
QThreadStorageData::finish :
QThread::currentThreadId :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.20.3-Odense
QGIS code revision: 495fbaec
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.1
Running against GDAL: 3.3.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

### Steps to reproduce the issue

Random regiular crash, not reproducable.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS-Version | 3.20.3-Odense | QGIS-Codeversion | 495fbaec
-- | -- | -- | --
Qt-Version | 5.15.2
Python-Version | 3.9.5
GDAL-Version | 3.3.1
PROJ-Version | 8.1.1
EPSG-Registraturdatenbankversion | v10.028 (2021-07-07)
GEOS-Version | 3.9.1-CAPI-1.14.2
SQLite-Version | 3.35.2
PDAL-Versio | 2.3.0
PostgreSQL-Client-Version | 13.0
SpatiaLite-Version | 5.0.1
QWT-Version | 6.1.3
QScintilla2-Version | 2.11.5
BS-Version | Windows 10 Version 2009
  |   |   |  
Aktive Python-Erweiterungen | AnotherDXF2Shapeclosest_pointsdisconnected-islandsImportPhotosjoinmultiplelineslizmapmmqgisORStoolsqchainageqgis-bulk-nominatim-masterQgis2threejsqgis2webQuickOSMquick_map_servicesrefFunctionsdb_managerprocessing

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
> AnotherDXF2Shapeclosest_pointsdisconnected-islandsImportPhotosjoinmultiplelineslizmapmmqgisORStoolsqchainageqgis-bulk-nominatim-masterQgis2threejsqgis2webQuickOSMquick_map_servicesrefFunctionsdb_managerprocessing

@wmeinolf so in the new profile you didn't have the above plugins installed, right?

**Comment by wmeinolf** [comment]
Sorry not responding longer time. I found and investigated general issues with my windows installation, which may have caused the crashs. Therefore I close this issue, as it is unlikely related to QGIS.
