### ISSUE TITLE
Using perimeter (Curved) labels doesn't work properly

### ISSUE THREAD

**Issue by jimmyhenne** [qgis/QGIS#45051]
### What is the bug or the crash?

I have a recent project created in QGIS 3.18.1 with polygons (administrative districts) labeled by Using Perimeter (Curved) mode. I labeled the names with orientation dependent position and a small distance so that the polygons are labeled inside. After having updated to 3.20.1 I noticed that the labels aren't placed properly - the orientation is mixed up and is not inside the polygons anymore.

In version 3.18.1 - the map looked like this (labeling correct, they are inside the polygons):
![grafik](https://user-images.githubusercontent.com/34960757/133211014-ec31a5e7-4c87-4442-af44-12553ec87323.png)

Version 3.20.1 - labels are not correct anymore, because they are in- and also outside of the polygons:
(position of red underlined labels is not correct - green underline is the correct position) 
![133211192-e01199a0-bd13-4693-b366-c40bccf43e0c](https://user-images.githubusercontent.com/34960757/133213413-51ed8117-a87c-4d56-843c-a6b7e64fcfdb.png)

### Steps to reproduce the issue

- Import WFS:
https://www.wfs.nrw.de/geobasis/wfs_nw_dvg

- Load Layer:
DVG2 Kreisangehörige Kommunen und kreisfreie Städte

- Label Layer:
single label based on GN using perimeter (curved), click right of line and line orientation dependent position and set some distance
![grafik](https://user-images.githubusercontent.com/34960757/133211572-ff64059f-b913-4da4-bf9b-191b09fcf1ed.png)

For me it looks like the setting "line orientation dependent position" has no effect.
When clicked "Right of line" the polygons are labeled above the line which leads to the fact that the labels of a district is labeled in- and outside instead of just inside.

Zoom to e.g.:
326977,5677864 (EPSG 25832)

I saved a project file reduced to the mentioned layer and settings:
[label_bug.zip](https://github.com/qgis/QGIS/files/7159575/label_bug.zip)

I also tested 3.20.2 but this leads to the same result.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.20.1-Odense | QGIS code revision | 1c3c5cd6
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.1
PROJ version | 8.1.0
EPSG Registry database version | v10.018 (2021-04-02)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 1607
  |   |   |  
Active Python plugins | canvas_clipperDataDrivenInputMaskflurstueck_finderGeoCodingImportPhotosMemoryLayerSaverNNJoinqfieldsyncqgis-maptiler-pluginQuickOSMquick_map_servicesdb_managerprocessing

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

**Comment by gioman** [comment]
@jimmyhenne on 3.20 on Windows seems fine with

![image](https://user-images.githubusercontent.com/1951107/133276369-9f582509-0a07-47f1-a0c8-ffa1992daf6e.png)

**Comment by jimmyhenne** [comment]
@gioman Thanks for your quick response.
I ticked both options as you mentioned and the labels changed but they are still not correct.

![grafik](https://user-images.githubusercontent.com/34960757/133279265-4d796a81-70ff-448a-a6f7-5c984aea7b28.png)
I also added the district label forced inside the polygons to make it more clear.
- The labels 'Willich' are placed inside - correct
- The labels 'Mönchengladbach' are in- and outside - not correct
- The labels 'Korschenbroich' are also placed in- and outside - not correct

The labels should be inside the polygons and curved to its shape - that was working in the project when I created it with 3.18.1

Are the labels in your project placed correctly?

**Comment by pathmapper** [comment]
I can reproduce the issue with `master` on Ubuntu 20.04.3 LTS.

According to `git bisect` this regressed in https://github.com/qgis/QGIS/commit/832d5e95eef9286b5ae58be308096f5481bdc7d3 .

The issues seems to be scale dependent, see the following GIF:

<img src= "https://user-images.githubusercontent.com/20856381/133965535-bc1f3aba-3725-4630-a6c0-47a5dd68d9bf.gif" width="500">

**Comment by gioman** [comment]
> The issues seems to be scale dependent

yes, I also seen the same.
