### ISSUE TITLE
Sub expression produces error in Sum function of Field Calculator

### ISSUE THREAD

**Issue by pantaleoamoroso** [qgis/QGIS#45061]
### What is the bug or the crash?

This aggregate function with arithmetic operation in the sub expression worked in version 3.16 with Field "Tot Ft" as type Integer:
sum("Tot Ft"/5280,"market_name")
Found it produces an error in version 3.20:
  >> Eval Error: Could not calculate aggregate for: Tot Ft / 5280 <<
The sum function works on the Field without error if I remove the arithmetic operation:
sum("Tot Ft","market_name")
However, if I change the Field Name to remove the space so it is "TotFt" The aggregate function does work with the arithmetic  operation also:
sum("TotFt"/5280,"market_name")
Not sure what specifically are all the conditions to cause the error in the sum function with arithmetic operation in the expression, but seems to be related to the syntax of the Field Name, using a space being one factor..   not sure of other characters causing a problem as well

### Steps to reproduce the issue

use arithmetic expression in aggregate sum function in Field Calculator using different Field names with and without space...   i.e.    sum("Field Name"/10) , sum("FieldName"/10)

### Versions

QGIS version
3.20.0-Odense
QGIS code revision
decaadbb31
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.0
PROJ version
8.0.1
EPSG Registry database version
v10.018 (2021-04-02)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 1909

Active Python plugins
ClipMultipleLayers
DataPlotly
flowTrace
GeoCoding
joinmultiplelines
layer2kmz
MultipleLayerSelection
nominatim
QGISSortAndNumber-master
quick_map_services
refFunctions
send2google_earth
db_manager
processing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Problem replicated by separate user with different profile

**Comment by nyalldawson** [comment]
Please text with 3.20.3 --there's been related fixes since 3.20.0

**Comment by agiudiceandrea** [comment]
The issue also occurs with QGIS 3.20.3.
The issue doesn't occur with QGIS 3.21.0-Master (3d4224d410).

**Comment by roya0045** [comment]
This seems fixed in 3.22.

**Comment by agiudiceandrea** [comment]
The issue seems fixed also to me with QGIS 3.22.2.

**Comment by pantaleoamoroso** [comment]
Due to current restrictions in my workplace on software downloads I am not able to verify the fix with 3.21 or 3.22, however, from the comments it appears this has been corrected with those versions..  Many thanks to those who did the follow-up
