### ISSUE TITLE
Incomplete pages in QGIS API Documentation

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/QGIS#45065]
### What is the issue about the documentation?

The QgsVectorLayer Class Reference documentation page (but probably also other pages) for 3.21, 3.20 and 3.16 is incomplete and appears truncated at some point: it completely misses all the relevant documentation about the class and the functions provided.

Compare the incomplete QgsVectorLayer Class Reference pages for:
3.21 https://qgis.org/api/classQgsVectorLayer.html
3.20 https://qgis.org/api/3.20/classQgsVectorLayer.html
3.16 https://qgis.org/api/3.16/classQgsVectorLayer.html

with the complete QgsVectorLayer Class Reference page for 3.14 https://qgis.org/api/3.14/classQgsVectorLayer.html

The incomplete pages also miss the footer of the pages with the "Generated on ,,, for QGIS API Documentation by doxygen 1.9.1" text.

**Comment by uclaros** [comment]
All 4 linked pages render correctly for me, including the doxygen footer. Can you rule out network issues or a cached semi-loaded page?

**Comment by agiudiceandrea** [comment]
@uclaros thanks for checking.
I've made sure it's not a browser cache or a system or proxy cache issue. Maybe it's a cloudflare caching issue towards my ISP (in Italy). I've also tested, with the same results, another machine in another place using another ISP but always in Italy.

Maybe is transient... I will check again in the following days.

**Comment by agiudiceandrea** [comment]
Confirmed as a cloudflare caching issue. The issue is now fixed for 2 out of 3 Italian ISP I've tested, so I think it is being resolved for other Italian ISPs as well.
