### ISSUE TITLE
QGIS Server returns an Internal Server Error or an incomplete image when serving a GetPrint request in PNG format

### ISSUE THREAD

**Issue by endmax** [qgis/QGIS#45071]
### What is the bug or the crash?

When a QGIS project contains a WMS layer that is served via QGIS Server through GetPrint WMS Service the returned image is corrupted.
The same request in PDF format returns a valid PDF file.
[QGISProject.zip](https://github.com/qgis/QGIS/files/7170266/QGISProject.zip)

### Steps to reproduce the issue

Load the project in a QGIS Server installation and send the following request:
https://yourserver/cgi-bin/qgis_mapserv.fcgi?MAP=PrgDigTemplate.qgs&SERVICE=WMS&REQUEST=GetPrint&TEMPLATE=A0_Orizzontale&CRS=EPSG%3a25832&DPI=300&FORMAT=PNG&ATLAS_PK=13

or in PDF to get a valid result

https://yourserver/cgi-bin/qgis_mapserv.fcgi?MAP=PrgDigTemplate.qgs&SERVICE=WMS&REQUEST=GetPrint&TEMPLATE=A0_Orizzontale&CRS=EPSG%3a25832&DPI=300&FORMAT=PDF&ATLAS_PK=13

### Versions

QGIS version
3.16.3-Hannover
QGIS code revision
94ac9f21b8
Compiled against Qt
5.12.8
Running against Qt
5.12.8
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.31.1
Running against SQLite
3.31.1
PostgreSQL Client Version
12.5 (Ubuntu 12.5-0ubuntu0.20.04.1)
SpatiaLite Version
4.3.0a
QWT Version
6.1.4
QScintilla2 Version
2.11.2
Compiled against PROJ
6.3.1
Running against PROJ
Rel. 6.3.1, February 10th, 2020
OS Version
Ubuntu 20.04 LTS
Active python plugins
PluginLoadTimes; 
db_manager; 
processing; 
MetaSearch

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@endmax project takes forever to load here on Desktop (and ultimately it hangs QGIS) and on server it returns

<ServerException>Layer(s) not valid</ServerException>

can it be stripped down to the bare minimum?

**Comment by endmax** [comment]
Yes, It stops for a while around 40% but then it goes to 100%.
Anyway I try to delete unused layers.

**Comment by gioman** [comment]
> but then it goes to 100%.

it hangs and 100% here

**Comment by endmax** [comment]
I've deleted most of the geometries contained in the spatialite db and now the project load in 2-3 seconds on my qgis desktop.
[QGISProject.zip](https://github.com/qgis/QGIS/files/7172034/QGISProject.zip)

**Comment by gioman** [comment]
> I've deleted most of the geometries contained in the spatialite db and now the project loads in 2-3 seconds on my qgis desktop.
> [QGISProject.zip](https://github.com/qgis/QGIS/files/7172034/QGISProject.zip)

@endmax it still freezes QGIS here, tried on both Windows and Linux.

I see that your project contains a single WMS layer from

https://geoservices.provincia.tn.it/arcgis/services/OGC/CTP/ImageServer/WMSServer

isn't just enough to test with a random project containing this WMS layer?

**Comment by endmax** [comment]
An update: with the last uploaded project the result is an Internal Server Error wit PNG format, but PDF is correctly returned (see attached file [pdf.zip](https://github.com/qgis/QGIS/files/7172479/pdf.zip))
The following lines are my QGIS server log for both requests (N.B. changed DPI to 100 for performance reason):

PDF
```
18:16:58 INFO Server[157880]: ******************** New request ***************
18:16:58 INFO Server[157880]: Request URL: https://www.prgtools.it:443/cgi-bin/qgis_mapserv.fcgi?MAP=PROJECTS%2FPrgDigBlazMaster%2FTenno%2F7%2FPrgDigTemplate.qgs&SERVICE=WMS&REQUEST=GetPrint&TEMPLATE=A0_Orizzontale&CRS=EPSG%3A25832&DPI=100&FORMAT=PDF&ATLAS_PK=13
18:16:58 INFO Server[157880]: Environment:
18:16:58 INFO Server[157880]: ------------------------------------------------
18:16:58 INFO Server[157880]: SERVER_NAME: www.prgtools.it
18:16:58 INFO Server[157880]: REQUEST_URI: /cgi-bin/qgis_mapserv.fcgi?MAP=PROJECTS%2fPrgDigBlazMaster%2fTenno%2f7%2fPrgDigTemplate.qgs&SERVICE=WMS&REQUEST=GetPrint&TEMPLATE=A0_Orizzontale&CRS=EPSG%3a25832&DPI=100&FORMAT=PDF&ATLAS_PK=13
18:16:58 INFO Server[157880]: SCRIPT_NAME: /cgi-bin/qgis_mapserv.fcgi
18:16:58 INFO Server[157880]: HTTPS: on
18:16:58 INFO Server[157880]: REMOTE_ADDR: 51.144.115.156
18:16:58 INFO Server[157880]: SERVER_PORT: 443
18:16:58 INFO Server[157880]: QUERY_STRING: MAP=PROJECTS%2fPrgDigBlazMaster%2fTenno%2f7%2fPrgDigTemplate.qgs&SERVICE=WMS&REQUEST=GetPrint&TEMPLATE=A0_Orizzontale&CRS=EPSG%3a25832&DPI=100&FORMAT=PDF&ATLAS_PK=13
18:16:58 INFO Server[157880]: REQUEST_METHOD: GET
18:16:58 INFO Server[157880]: HTTP_ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
18:16:58 INFO Server[157880]: HTTP_USER_AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36
18:16:58 INFO Server[157880]: QGIS_PROJECT_FILE: /home/qgis/projects/world.qgs
18:16:58 INFO Server[157880]: ATLAS_PK:13
18:16:58 INFO Server[157880]: CRS:EPSG:25832
18:16:58 INFO Server[157880]: DPI:100
18:16:58 INFO Server[157880]: FORMAT:PDF
18:16:58 INFO Server[157880]: MAP:PROJECTS/PrgDigBlazMaster/Tenno/7/PrgDigTemplate.qgs
18:16:58 INFO Server[157880]: REQUEST:GetPrint
18:16:58 INFO Server[157880]: SERVICE:WMS
18:16:58 INFO Server[157880]: TEMPLATE:A0_Orizzontale
18:17:04 INFO Server[157880]: WMS Request parameters:
18:17:04 INFO Server[157880]:  - CRS : EPSG:25832
18:17:04 INFO Server[157880]:  - FORMAT : PDF
18:17:04 INFO Server[157880]:  - DPI : 100
18:17:04 INFO Server[157880]:  - TEMPLATE : A0_Orizzontale
18:17:04 INFO Server[157880]:  - ATLAS_PK : 13
18:17:41 INFO Server[157880]: Request finished in 42209 ms
```

PNG
```
18:18:06 INFO Server[157880]: ******************** New request ***************
18:18:06 INFO Server[157880]: Request URL: https://www.prgtools.it:443/cgi-bin/qgis_mapserv.fcgi?MAP=PROJECTS%2FPrgDigBlazMaster%2FTenno%2F7%2FPrgDigTemplate.qgs&SERVICE=WMS&REQUEST=GetPrint&TEMPLATE=A0_Orizzontale&CRS=EPSG%3A25832&DPI=100&FORMAT=PNG&ATLAS_PK=13
18:18:06 INFO Server[157880]: Environment:
18:18:06 INFO Server[157880]: ------------------------------------------------
18:18:06 INFO Server[157880]: SERVER_NAME: www.prgtools.it
18:18:06 INFO Server[157880]: REQUEST_URI: /cgi-bin/qgis_mapserv.fcgi?MAP=PROJECTS%2fPrgDigBlazMaster%2fTenno%2f7%2fPrgDigTemplate.qgs&SERVICE=WMS&REQUEST=GetPrint&TEMPLATE=A0_Orizzontale&CRS=EPSG%3a25832&DPI=100&FORMAT=PNG&ATLAS_PK=13
18:18:06 INFO Server[157880]: SCRIPT_NAME: /cgi-bin/qgis_mapserv.fcgi
18:18:06 INFO Server[157880]: HTTPS: on
18:18:06 INFO Server[157880]: REMOTE_ADDR: 51.144.115.156
18:18:06 INFO Server[157880]: SERVER_PORT: 443
18:18:06 INFO Server[157880]: QUERY_STRING: MAP=PROJECTS%2fPrgDigBlazMaster%2fTenno%2f7%2fPrgDigTemplate.qgs&SERVICE=WMS&REQUEST=GetPrint&TEMPLATE=A0_Orizzontale&CRS=EPSG%3a25832&DPI=100&FORMAT=PNG&ATLAS_PK=13
18:18:06 INFO Server[157880]: REQUEST_METHOD: GET
18:18:06 INFO Server[157880]: HTTP_ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
18:18:06 INFO Server[157880]: HTTP_USER_AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36
18:18:06 INFO Server[157880]: QGIS_PROJECT_FILE: /home/qgis/projects/world.qgs
18:18:06 INFO Server[157880]: ATLAS_PK:13
18:18:06 INFO Server[157880]: CRS:EPSG:25832
18:18:06 INFO Server[157880]: DPI:100
18:18:06 INFO Server[157880]: FORMAT:PNG
18:18:06 INFO Server[157880]: MAP:PROJECTS/PrgDigBlazMaster/Tenno/7/PrgDigTemplate.qgs
18:18:06 INFO Server[157880]: REQUEST:GetPrint
18:18:06 INFO Server[157880]: SERVICE:WMS
18:18:06 INFO Server[157880]: TEMPLATE:A0_Orizzontale
18:18:06 INFO Server[157880]: WMS Request parameters:
18:18:06 INFO Server[157880]:  - CRS : EPSG:25832
18:18:06 INFO Server[157880]:  - FORMAT : PNG
18:18:06 INFO Server[157880]:  - DPI : 100
18:18:06 INFO Server[157880]:  - TEMPLATE : A0_Orizzontale
18:18:06 INFO Server[157880]:  - ATLAS_PK : 13
18:18:46 INFO Server[157822]: Request finished in 119817 ms
```

**Comment by endmax** [comment]
Other update: using JPG instead of PNG I'm able to get a valid response. At this point I guess the problem is because of response size since PDF and JPG are smaller than PNG.
So the question is: what happens after QGIS server process the request ? Is there any know limitation in web server handling the QGIS response and forwarding it to the caller ?

**Comment by gioman** [comment]
> Other update: using JPG instead of PNG I'm able to get a valid response. At this point I guess the problem is because of response size since PDF and JPG are smaller than PNG.
> So the question is: what happens after QGIS server process the request ? Is there any know limitation in web server handling the QGIS response and forwarding it to the caller ?

@endmax have you seen my comment here? https://github.com/qgis/QGIS/issues/45071#issuecomment-920289023 can you further strip down the project that shows the issue?

**Comment by endmax** [comment]
Sorry I did not see your comment.
Here is the project file stripped off a ton of layers. It loads well on four different QGIS desktop, windows and linux as well.
I hope you will be able to open. thank you
[PrgDigTemplate.zip](https://github.com/qgis/QGIS/files/7179140/PrgDigTemplate.zip)

**Comment by endmax** [comment]
> isn't just enough to test with a random project containing this WMS layer?

after my last tests I really think that size of the answer is the problem. Probably the WMS layer itself is only guilty of adding a background that enlarge the response. Maybe I have to look at web server limit on serving a big file.

What do you think ?

**Comment by endmax** [comment]
Using PNG format and changing DPI from 40,80,150 give me a valid result for 40 and 80 DPI and a Server Internal Error for 150 DPI.

**Comment by endmax** [comment]
I've finally found the solution:
change the following line in file /etc/apache2/sites-available/000-default.conf
`FcgidIOTimeout 120`
to
`FcgidIOTimeout 600`
