### ISSUE TITLE
Locator nominatim search never stops

### ISSUE THREAD

**Issue by eurojam** [qgis/QGIS#45082]
### What is the bug or the crash?

Sometimes when using the locator nominatim search, no result will be returned and the the locator continues searching (the wheel continues). All other locator function disappeared. QGIS does not hang but can not be closed in any way.

![locator_nominatim](https://user-images.githubusercontent.com/46351209/133559390-dec05375-f927-46d2-ae81-53d2b4aadbb6.gif)

### Steps to reproduce the issue

using the locator twice or three times with some abritary input...see animation above

### Versions

QGIS-Version | 3.20.3-Odense | QGIS-Codeversion | 495fbaec
-- | -- | -- | --
Qt-Version | 5.15.2
Python-Version | 3.9.5
GDAL-Version | 3.3.1
PROJ-Version | 8.1.1
EPSG-Registraturdatenbankversion | v10.028 (2021-07-07)
GEOS-Version | 3.9.1-CAPI-1.14.2
SQLite-Version | 3.35.2
PDAL-Versio | 2.3.0
PostgreSQL-Client-Version | 13.0
SpatiaLite-Version | 5.0.1
QWT-Version | 6.1.3
QScintilla2-Version | 2.11.5
BS-Version | Windows 10 Version 2009
  |   |   |  
Aktive Python-Erweiterungen | GeoCodingdb_managerMetaSearchprocessing

</body></html>

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by Joonalai** [comment]
I could not reproduce this with QGIS 3.20.2 on Arch.

**Comment by lehtojaa** [comment]
I could not reproduce this either. I have QGIS 3.20.3-Odense on Windows 10 Version 2009, and also all the library versions are the same etc. (up to the active plugins). Did you try this with new profile?

**Comment by eurojam** [comment]
On a new profile the error could not be reproduced.

**Comment by eurojam** [comment]
On a new profile the error could not be reproduced and therefor the issue will be closed
