### ISSUE TITLE
Ver 3.20.3 Crash double clicking a layer to view properties

### ISSUE THREAD

**Issue by HugoHvidSorensen** [qgis/QGIS#45087]
### What is the bug or the crash?

Doubble clicked a tabel to see properties. Qgis stalled showing an error window with the following content.
ATrying to open a vector layer wit polygons. In a geopackage. (It opened without problems in the latest stable version)
"Crash ID: 8f103cffb87c969fab652dcb6819a67f5ac49128

Stack Trace

QgsProcessingDxfLayersWidget::setProject :
QgsEmbeddedSymbolRendererWidget::setContext :
QgsRendererPropertiesDialog::setContext :
QgsVectorLayerProperties::updateSymbologyPage :
QgsVectorLayerProperties::syncToLayer :
QgsVectorLayerProperties::QgsVectorLayerProperties :
QgisApp::showLayerProperties :
QgisApp::layerProperties :
QObject::qt_static_metacall :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QMenu::exec :
QMenu::exec :
QgsLayerTreeView::contextMenuEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.20.3-Odense
QGIS code revision: 495fbaec
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.1
Running against GDAL: 3.3.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043
"

### Steps to reproduce the issue

[SamledeOpmålinger.zip](https://github.com/qgis/QGIS/files/7177359/SamledeOpmalinger.zip)

I was the layer "Anlæg" i doubbleclicked - All layers in the GPKG was opened and shown.

### Versions

QGIS-version
3.20.3-Odense
QGIS-koderevision
495fbaec

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

Nej

**Comment by gioman** [comment]
@HugoHvidSorensen can you please edit the ticket and translate in to English? Thanks.

**Comment by HugoHvidSorensen** [comment]
Tried in English :-)

**Comment by gioman** [comment]
> Tried in English :-) 

@HugoHvidSorensen can you try with a new QGIS profile and no 3rd party plugins installed? Thanks.

**Comment by gioman** [comment]
Also please edit the title.

**Comment by HugoHvidSorensen** [comment]
Just ignore the Issue - I deinstalled and continue with the latest Stable version. Sorry for the inconvenience I have caused.
