### ISSUE TITLE
QGIS upgrade not available through OSGeo4W

### ISSUE THREAD

**Issue by JanChytry** [qgis/QGIS#45091]
### What is the bug or the crash?

I am currently on the `QGIS 3.18.2` installed using OSGeo4W. I would like to upgrade to 3.20.x, however when I open the OSGeo4W setup and navigate through, I cannot find the newer version under Select Packages -> Desktop. It only allows me to upgrade to 3.18.3-1. Please see the image attached below.

Is this some kind of error on my side or QGIS 3.20 has not yet been "added" to OSGeo4W intallers. Or is it standard practice for 3.x versions so I have to make a clean install? 

Thanks!

### Steps to reproduce the issue

Open the OSGeo4W installer, select `Advanced Install` and navigate through to the `Select Packages` section. Look under `Desktop` which regards the desktop QGIS itself. See the image attached below (my case).
![image](https://user-images.githubusercontent.com/24588489/133615365-1c54d655-2383-41bf-acc7-585216bced4f.png)

### Versions

QGIS 3.18.2 (with GRASS 7.8.5)
QGIS 3.20.x

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@JanChytry you must use the new (aka v2) version of osgeo4w. 

![image](https://user-images.githubusercontent.com/1951107/133617486-d683aaeb-ba2f-4f2e-8932-35ddaac70fab.png)

**Comment by JanChytry** [comment]
Of course, missed it. Thanks!
