### ISSUE TITLE
MS SQL layers missing Z coordinate

### ISSUE THREAD

**Issue by nextstopsun** [qgis/QGIS#45093]
### What is the bug or the crash?

Layers rom MS SQL connection get added without Z coordinate and are recognised as 2D geometry types.

### Steps to reproduce the issue

Add any MS SQL table, that has Z coordinate (HasZ() method returns true) to QGIS canvas. 
Z coordinate is ignored.

### Versions

QGIS version | 3.20.0-Odense | QGIS code revision | decaadbb31
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.8.7
GDAL/OGR version | 3.2.3
PROJ version | 6.3.2
EPSG Registry database version | v9.8.6 (2020-01-22)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.31.1
PDAL version | 2.2.0
PostgreSQL client version | 12.3
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.4
OS version | macOS 11.2
  |   |   |  
Active Python plugins | slyr_communityquick_map_servicesnominatim_locator_filterprocessingdb_managerMetaSearch

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

Reading tables from MS SQL database that were created with ArcGIS.

**Comment by PeterPetrik** [comment]
Would it be possible to give me some example dataset that I can run on some ms sql docker image for testing?

**Comment by nextstopsun** [comment]
@PeterPetrik What data format would you like to have?
