### ISSUE TITLE
Attributes - Update All button  - Creates Corrupted Fields - GeoJSON file

### ISSUE THREAD

**Issue by wmorrisett** [qgis/QGIS#45139]
### What is the bug or the crash?

In the Attributes table, after adding a new field, I tried using the Update All button.  Field added: CountyFP20.  Field updated: CountyFP20.  Update value: 065.  When I click the Update All button Attribute fields look good -- CountyFP20 has the correct value.  ...but... clicking the Save Edits button flips the values in two fields:  organization and CountyFP20.  See attached screen shots: before and after.  See attached GeoJSON file I used.  NOTE:  if the GeoJSON is first saved as a GeoPackage, then this problem does not happen.

### Steps to reproduce the issue

[GeoJSON - Edit All problem - 2021-09-19.pdf](https://github.com/qgis/QGIS/files/7192799/GeoJSON.-.Edit.All.problem.-.2021-09-19.pdf)
[TN COIs.zip](https://github.com/qgis/QGIS/files/7192806/TN.COIs.zip)

1. load the GeoJSON file.
2. Open the Attributes Table
3. Add CountyFP20 field, whole number, length 10.
4. Click Save Edits button
5. Select CountyFP20 field from dropdown list, enter value: 065; and click Update All button.  Results look okay.  See screen shot.
6. click Save Edits.  Values of organization field and CountyFP20 fields are flipped -- each field now has wrong values.  See screen shot

### Versions

QGIS version
3.20.2-Odense
QGIS code revision
9f59a156
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.1
PROJ version
8.1.0
EPSG Registry database version
v10.027 (2021-06-17)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
DataPlotly
qconsolidate3
qgis3redistricter-master
quick_map_services
db_manager
processing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by elpaso** [comment]
Confirmed.

**Comment by elpaso** [comment]
I've found the root of the issue: if you run `ogrinfo -al TN\ COIs.geojson` and go to the end of the output you see:

```
OGRFeature(TN COIs):23
  entry_name (String) = University of TN test
  cultural_interests (String) = 
  economic_interests (String) = Test
  comm_activities (String) = 
  other_considerations (String) = 
  custom_response (String) = 
  population (Integer) = 1525
  block_group_ids (StringList) = (1:470370195031)
  CountyFP20 (Integer) = 65
  organization (String) = TN Democrats
  drive (String) = Test TN
```

GDAL thinks that the field is NOT appended but added before `organization`, well it is **appended** if you consider the first record:

```
  entry_name (String) = Seven Points Community
  cultural_interests (String) = 
  economic_interests (String) = 
  comm_activities (String) = 
  other_considerations (String) = The cost of ....
  custom_response (String) = 
  population (Integer) = (null)
  block_group_ids (StringList) = (1:470370156331)
  CountyFP20 (Integer) = 65
```


So, what's happening here is that GDAL reads the fields in sequence and adds the new fields while they appears in the features, even if the new field is correctly appended to the json file (the new field is correctly always the last in all json records).

When QGIS appends the field it is correctly appended to the all json records in the last position but when GDAL encounters the other fields that are **not** in the first record ("organization" and "drive") they are appended to the list of available fields and "CountyFP20" is no longer the last one.

We have two issues here:
1. the new field is appended correctly but GDAL doesn't see it that way
2. the QGIS attribute table always thinks that the new field was appended and does not update the table headers when it's not

I'm not sure if it worth fixing GDAL (this does not seems to be a real "bug" after all, CC @rouault I can probably have a look to the GDAL implementation if you think this has to be fixed  ), if we should implement a (probably complex) patch inside QGIS to maintain a different field order in this case or just fix the attribute table bug (the only real severe bug in this issue) which is the column headers that are not in sync with the data after the column is added in a position that is not the last.

**Comment by elpaso** [comment]
Failing test case:

```python

    def testGeoJson(self):
        """Test issue GH #45139"""

        d = QTemporaryDir()
        json_path = os.path.join(d.path(), 'test.geojson')
        with open(json_path, 'w+') as f:
            f.write("""
            {
                "type": "FeatureCollection",
                "features": [
                    {
                        "type": "Feature",
                        "geometry": {
                            "type": "Point",
                            "coordinates": [11.1215698,46.0677293]
                        },
                        "properties": {
                            "A": "A",
                        }
                    },
                    {
                        "type": "Feature",
                        "geometry": {
                            "type": "Point",
                            "coordinates": [11.1214686,46.0677385]
                        },
                        "properties": {
                            "A": "A",
                            "B": "B",
                        }
                    }
                ]
            }
            """)

        vl = QgsVectorLayer(json_path, 'json')
        self.assertTrue(vl.isValid())
        self.assertEqual(vl.featureCount(), 2)
        self.assertEqual(vl.fields().names(), ['A', 'B'])

        # Append a field
        self.assertTrue(vl.startEditing())
        self.assertTrue(vl.addAttribute(QgsField('C', QVariant.String)))

        for f in vl.getFeatures():
            vl.changeAttributeValue(f.id(), 2, 'C')

        self.assertEqual(vl.fields().names(), ['A', 'B', 'C'])

        features = [f for f in vl.getFeatures()]

        self.assertEqual(features[0].attribute('B'), NULL)
        self.assertEqual(features[0].attribute('C'), 'C')
        self.assertEqual(features[1].attribute('B'), 'B')
        self.assertEqual(features[1].attribute('C'), 'C')


        self.assertTrue(vl.commitChanges())
        self.assertEqual(vl.fields().names(), ['A', 'B', 'C'])


        features = [f for f in vl.getFeatures()]

        self.assertEqual(features[0].attribute('B'), NULL)
        self.assertEqual(features[0].attribute('C'), 'C')
        self.assertEqual(features[1].attribute('B'), 'B')
        self.assertEqual(features[1].attribute('C'), 'C')
```

**Comment by elpaso** [comment]
GDAL failing test case: not sure it is a bug though.


```python
def test_ogr_geojson_field_order():

    filename = '/vsimem/test_ogr_geojson_field_order.json'

    gdal.FileFromMemBuffer(filename, """
        {
            "type": "FeatureCollection",
            "features": [
                {
                    "type": "Feature",
                    "geometry": {
                        "type": "Point",
                        "coordinates": [11.1215698,46.0677293]
                    },
                    "properties": {
                        "A": "A",
                    }
                },
                {
                    "type": "Feature",
                    "geometry": {
                        "type": "Point",
                        "coordinates": [11.1214686,46.0677385]
                    },
                    "properties": {
                        "A": "A",
                        "B": "B",
                    }
                }
            ]
        }
        """)

    def _fnames(layer_def):
        return [layer_def.GetFieldDefn(idx).name for idx in range(layer_def.GetFieldCount())]

    ds = gdal.OpenEx(filename, gdal.OF_VECTOR|gdal.OF_UPDATE)
    assert ds is not None

    layer = ds.GetLayer(0)
    layer_def = layer.GetLayerDefn()

    assert _fnames(layer_def) == ['A', 'B']

    new_field = ogr.FieldDefn('C', ogr.OFTString)

    assert layer.CreateField(new_field, True) == ogr.OGRERR_NONE

    layer_def = layer.GetLayerDefn()

    assert _fnames(layer_def) == ['A', 'B', 'C']

    for fid in range(2):
        feature = layer.GetFeature(fid)
        feature.SetField("C", "C")
        layer.SetFeature(feature)

    for fid in range(2):
        feature = layer.GetFeature(fid)
        assert feature.GetField("C") == "C"

    del ds

    ds = gdal.OpenEx(filename, gdal.OF_VECTOR|gdal.OF_READONLY)
    layer = ds.GetLayer(0)
    layer_def = layer.GetLayerDefn()
    assert _fnames(layer_def) == ['A', 'B', 'C']

    os.unlink(filename)

**Comment by rouault** [comment]
Properties in GeoJSON are stored in a JSON object/dictionary, so their order could be consider as non-significant. The order during serialization or reading is dependent on the JSON implementation. libjson-c that GDAL uses has relative stable properties regarding this. So this could probably be improved in GDAL to insert fields not always at the end, but I agree with @elpaso that QGIS should be made robust to this situation of column order changing.

**Comment by rouault** [comment]
GDAL related improvement: https://github.com/OSGeo/gdal/pull/4552

**Comment by elpaso** [comment]
> GDAL related improvement: [OSGeo/gdal#4552](https://github.com/OSGeo/gdal/pull/4552)

Nice! This probably makes my PR redundant but I'd keep it anyway.
