### ISSUE TITLE
Legend does not takes into account transparency

### ISSUE THREAD

**Issue by denis-or** [qgis/QGIS#45131]
### What is the bug or the crash?

After generating a heatmap raster layer and applying opacity/transparency to a legend item, in the Print Layout the item has no opacity/transparency

I tried it with version 3.16.7-Hannover for Linux and version 3.16.11 for Windows

### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/49842454/133890918-4f1dd0b3-c03e-4132-9a40-aa46200e99b7.png)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

Versão do QGIS | 3.16.7-Hannover | Código da versão do QGIS | 0471743889
-- | -- | -- | --
Compilado sobre Qt | 5.9.5 | Rodando sobre Qt | 5.9.5
Compilado sobre GDAL/OGR | 2.2.3 | Rodando sobre GDAL/OGR | 2.2.3
Compilado sobre GEOS | 3.6.2-CAPI-1.10.2 | Rodando sobre GEOS | 3.6.2-CAPI-1.10.2 4d2925d6
Compilado no SQLite | 3.22.0 | Executando contra SQLite | 3.22.0
Versão do cliente PostgreSQL | 10.16 (Ubuntu 10.16-0ubuntu0.18.04.1) | Versão SpatiaLite | 4.3.0a
Versão do QWT | 6.1.3 | Versão QScintilla2 | 2.10.2
Versão PROJ.4 | 493
Versão SO | Linux Mint 19.3
Ativar complementos python | visualist; DataPlotly; NNJoin; inde; Submission; processing_r; HCMGIS; maps2winbugs; MetaSearch; processing; db_manager

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
Maybe a regression of this https://github.com/qgis/QGIS/issues/16763

**Comment by denis-or** [comment]
> Maybe a regression of this #16763

I really thought about. But, I tried it in two versions, both 3.16, for windows and for linux and did not works.

**Comment by alexbruy** [comment]
Seems fixed in the latest master (8c62d89729ec9a18f2f357dcebdcd483234d11b9)
