### ISSUE TITLE
Drop down menu gray background when switching to "update exisiting field" mode in Field Calculator

### ISSUE THREAD

**Issue by DoubleWhisky** [qgis/QGIS#45137]
### What is the bug or the crash?

Drop down menu stays grayed out when switching to "update exisiting field" mode in Field Calculator. Background of dropdown list should change to white.

![image](https://user-images.githubusercontent.com/63848619/133922574-0af30eb9-d0c4-44f4-a600-021e1905f884.png)

### Steps to reproduce the issue

1. Go to Field Calculator
2. Click on **Update exisiting field** checkbox
3. Observe that background of list deosn't change

### Versions

QGIS version
3.20.3-Odense
QGIS code revision
495fbaec
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.1
PROJ version
8.1.1
EPSG Registry database version
v10.028 (2021-07-07)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
AnotherDXF2Shape
gissupport_plugin
latlontools
MultipleLayerSelection
pobieracz_danych_gugik
qgis_resource_sharing
QuickOSM
QuickWKT
quick_map_services
SpreadsheetLayers
db_manager
MetaSearch
processing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Can't reproduce on windowsvista and fusion style
Can reproduce on windows style only

**Comment by DoubleWhisky** [comment]
> Can't reproduce on windowsvista and fusion style
> Can reproduce on windows style only

I confirm now that this is general bug in windows style visible in plenty of different windows.

**Comment by elpaso** [comment]
Can't reproduce on Linux, tagging as windows.

**Comment by YoannQDQ** [comment]
This is just the default "windows" style for non-editable comboboxes. Note that the drop down arrow is not grayed out.

![image](https://user-images.githubusercontent.com/9693475/235643554-d1448782-9979-4aac-b7b5-2ca8446be381.png)


![image](https://user-images.githubusercontent.com/9693475/235643822-95c1c2e3-9c0d-4021-8aba-9ea48eef3b06.png)
