### ISSUE TITLE
QGIS cannot open CityGML of Project PLATEAU correctly

### ISSUE THREAD

**Issue by mugwort-rc** [qgis/QGIS#45151]
### What is the bug or the crash?

CityGML of Project PLATEAU (Japenese CityGML open data project) uses a compound CRS (EPSG:6697), which cannot be read correctly by versions up to GDAL 3.3.2.

Currently, latitude is displayed as longitude and longitude as latitude in QGIS.

This problem has been fixed (https://github.com/OSGeo/gdal/pull/4505) and will be in the next release (3.3.3?).

### Steps to reproduce the issue

1. Open citygml_compound_crs.gml (Download from https://github.com/OSGeo/gdal/blob/master/autotest/ogr/data/gml/citygml_compound_crs.gml)
2. Coordinate indicate: longitude=35.7092, **latitude=139.8124** (Correct is longitude=139.8124, latitude=35.7092)

### Versions

Name | Value
-------|-------
QGIS version | 3.20.3-Odense
QGIS code revision | 495fbaecaf
Qt version | 5.12.8
Python version | 3.8.10
GDAL/OGR version | 3.0.4
PROJ version | 6.3.1
EPSG Registry database version | v9.8.6 (2020-01-22)
Compiled against GEOS | 3.8.0-CAPI-1.13.1
Running against GEOS | 3.8.0-CAPI-1.13.1 
SQLite version | 3.31.1
PDAL version | 2.0.1
PostgreSQL client version | 12.8 (Ubuntu 12.8-0ubuntu0.20.04.1)
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.2
OS version | Ubuntu 20.04.3 LTS

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
> GDAL/OGR version 	3.0.4

@mugwort-rc so as you say as soon you'll get a build of QGIS with GDAL 3.3.3 you'll also get support for that format. So not really a bug in QGIS code.

**Comment by mugwort-rc** [comment]
Yes. That's correct.
Assuming the GDAL update is released, it would be helpful if you could give me a rough idea of when it will be included in the QGIS release.

**Comment by gioman** [comment]
> Assuming the GDAL update is released, it would be helpful if you could give me a rough idea of when it will be included in the QGIS release.

@mugwort-rc Windows installer is usually quick to get updates. For other platforms it depends, for Ubuntu you'll need to wait for the Ubuntu packagers to update the official repos (unless you use Ubuntugis that could get new GDAL releases sooner). As alternative: compile GDAL and QGIS.

**Comment by mugwort-rc** [comment]
That's very good news.
I'll wait for GDAL to be updated and incorporated into the QGIS release. Thank you.
