### ISSUE TITLE
integration of Point2one plugin in QGIS 3

### ISSUE THREAD

**Issue by Forna73** [qgis/QGIS#45161]
### Feature description

In Qgis 2.X I used Point2one plugin to create tens of polygons or lines in a while starting from a spreadsheets of data. At the end I had a layer with geometries and tables compiled with all data.
In Qgis 3.X this plugin doesn't work anymore, and I read the Author has no time to make it compatible. There is an experimental version, but it doesn't work at 100%. It creates geometries but the table is totally empty... and when you have quite hundred of polygons it could be frustrating to compile the table manually.

To make this in Qgis I must go through at least 2 processes: "Points to line" and "Line to polygon" and at the end I've no table compiled with all data... 

I think that PlugIn should be a MUST to do that kind of work, above all when you have hundreds of data.

**Comment by gioman** [comment]
> I think that PlugIn should be a MUST to do that kind of work, above all when you have hundreds of data.

@Forna73 rather than waiting for someone to port this plugin to QGIS you consider forking the plugin and make the necessary changes to work on QGIS 3, see https://github.com/qgis/QGIS/wiki/Plugin-migration-to-QGIS-3

**Comment by uclaros** [comment]
1. Put all your points on the same layer, use a field to distinguish which point belongs to which polygon. If you have the points in many different layers use the *Merge vector layers* algorithm.
2. Run *Points to path*, use the field in *Path group expression*
3. Run *Lines to polygons*
4. Run *Join attributes by field value* joining back to the points layer, use that same field for the join
5. You have polygons with an attribute table in 4 simple steps, regardless of how big your data is.
6. If on *1* you merged, and want different layers again, use *Split vector layers*

**Comment by Forna73** [comment]
> > I think that PlugIn should be a MUST to do that kind of work, above all when you have hundreds of data.
> 
> @Forna73 rather than waiting for someone to port this plugin to QGIS you consider forking the plugin and make the necessary changes to work on QGIS 3, see https://github.com/qgis/QGIS/wiki/Plugin-migration-to-QGIS-3

Man... I'm a normal user and I don't know a word about programming and so... If I could do something I'd do it.... I'm here because I can't do it. This is  a feature request and since the Plugin made a process much more straight forward than Qgis do now... I'm suggesting to integrate.

**Comment by Forna73** [comment]
> 1. Put all your points on the same layer, use a field to distinguish which point belongs to which polygon. If you have the points in many different layers use the _Merge vector layers_ algorithm.
> 2. Run _Points to path_, use the field in _Path group expression_
> 3. Run _Lines to polygons_
> 4. Run _Join attributes by field value_ joining back to the points layer, use that same field for the join
> 5. You have polygons with an attribute table in 4 simple steps, regardless of how big your data is.
> 6. If on _1_ you merged, and want different layers again, use _Split vector layers_

They are in the same layer....

I'll try with the join... do you know if at the end I can export the polygons in a .shp file or I need to keep the join to have data?

**Comment by alexbruy** [comment]
@Forna73 what you want can be easily achived using Processing model, no need to add yet another tool.

**Comment by Forna73** [comment]
> @Forna73 what you want can be easily achieved using Processing model, no need to add yet another tool.

Ok... I've done thank to uclaros' suggestion, and it took me 8 steps in total..... I didn't know about the _Join attributes by field value_ process, but in any case the plugin would have done it in "1 click"... this would be an improvement... and it already worked in version 2.X

**Comment by uclaros** [comment]
Glad you got your task done!
Now you can combine those 8 steps (I counted 4 including the merge) in a model and be ready for the next time while expanding your QGIS skills at the same time!

**Comment by agiudiceandrea** [comment]
@Forna73 there is a Points2One plugin at https://github.com/ctu-fgis/2020-e-qgis-points2one which supposedly works with QGIS 3
Anyway a created a port of the plugin to QGIS 3 https://github.com/agiudiceandrea/points2one/releases. Feel free to test it and report any issue to https://github.com/agiudiceandrea/points2one/issues

**Comment by Forna73** [comment]
> @Forna73 there is a Points2One plugin at https://github.com/ctu-fgis/2020-e-qgis-points2one which supposedly works with QGIS 3
This is the one I found but it doesn't work well... it creates geometry but any table.

I will try the one you ported.... thanks a lot to support it!

**Comment by agiudiceandrea** [comment]
So, I think this could be closed.
