### ISSUE TITLE
Loading rasters is slower compared to QGIS 2

### ISSUE THREAD

**Issue by gisuserhsharz** [qgis/QGIS#45171]
### What is the bug or the crash?

I am a lecture at the Harz University of Applied Sciences in Germany, Wernigerode.

I load in QGis2  413 tif-files. Together 680 MB (TK10)

I stopped the time at 6 seconds!

I load in QGis3 the same 413 tif-files. Together 680 MB.

I stopped the time at 200 seconds!

Number-Thread are set to all

My question:

Why are QGis3 so slowly?

I can show you a video or sent you the rasterfiles

The overall performance of QGis3 are not better than QGis2

EMail: mwilhelm@hs-harz.de

Yours sincerely,

Michael Wilhelm

### Steps to reproduce the issue

Click on loadrasterfiles
select all files
insert into the project

### Versions

QGis2:  2.18.28
QGis3: 3.20.3

My computer:
Intel NUC 9 Extreme Kit BXNUC9i7QNX - Intel i7-9750H
RAM: Crucial Ballistix SODIMM Schwarz 32GB Kit (2x16GB) DDR4-2666 CL16
SSD:  Samsung 970 EVO Plus SSD 2TB M.2 2280 PCIe 3.0 x4 NVMe

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
> sent you the rasterfiles

@gisuserhsharz yes please.

**Comment by gisuserhsharz** [comment]
Dears Sirs,

I have to have modify the rasterfiles (Copyright).

Now the times are:

QGis2: 4 sec

QGis3: 42 sec

You can load the files from my homepage

http://www.miwilhelm.de/GitHub-QGis.7z



Yours sincerely,

Michael Wilhelm

**Comment by gioman** [comment]
>  http://www.miwilhelm.de/GitHub-QGis.7z

@gisuserhsharz thanks. The rasters are plain tiffs (not geotiffs) with world files. What is the CRS of this layers?

**Comment by gioman** [comment]
@gisuserhsharz also the vector you added seems to have the wrong CRS, it opens as 4326 but then it does not align with other layers as basemaps for example.

**Comment by gioman** [comment]
@gisuserhsharz also the raster you added seem to be the same repeated many times with different names (and a few of them are upside down).
