### ISSUE TITLE
Crash ID: 9ddef99f194fc60612947c4dca2d118d1116c043

### ISSUE THREAD

**Issue by CarinaHe** [qgis/QGIS#45187]
## User Feedback

I wrote a python script to produce a few maps automatically. I only have one layer, after the map production I change the style by loading a .qml-file and export the next map, and so on. I have 7 different .qml-files. They all work, but after two maps, QGIS crashes. It doesn't matter which style-files I use, only the amount makes a difference, after 2 times the crash comes. I tried it on windows and linux, no difference!

## Report Details

**Crash ID**: [9ddef99f194fc60612947c4dca2d118d1116c043]('https://github.com/qgis/QGIS/search?q=9ddef99f194fc60612947c4dca2d118d1116c043&type=Issues')

**Stack Trace**
<pre>
QgsLayerTreeGroup::findLayer :
QgsLayerTreeModel::layerLegendChanged :
QMetaObject::activate :
QMetaObject::activate :
QMetaObject::activate :
QgsVectorLayer::setRenderer :
QgsVectorLayer::readStyle :
QgsVectorLayer::readSymbology :
QgsMapLayer::importNamedStyle :
QgsMapLayer::loadNamedProperty :
QgsMapLayer::loadNamedStyle :
QgsVectorLayer::loadNamedStyle :
QgsVectorLayer::loadNamedStyle :
PyInit__core :
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyEval_EvalCodeEx :
PyEval_EvalCode :
PyArena_Free :
PyRun_StringFlags :
PyImport_Import :
PyImport_Import :
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyImport_Import :
PyImport_Import :
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.1-A Coru�a
QGIS code revision: ef24c526da
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

### Steps to reproduce the issue

# with the help of: https://gis.stackexchange.com/questions/411254/locking-layer-styles-in-qgis-print-layout-using-pyqgis?noredirect=1#comment667915_411254

from pathlib import Path
import sys

file_path ="C:/Users/.../legends/"
source_dir = Path(file_path)
files = source_dir.iterdir()

print(files)

for file in files:
    name = str(file)[len(file_path):]
    name_index = name.index('.')
    name=name[:name_index]
    print(name)
    print(str(file))
   
    project = QgsProject.instance()
    layout = QgsPrintLayout(project)
    layout.initializeDefaults()
    layout.setName(name)
    project.layoutManager().addLayout(layout)
    print('layout manager geladen')
    layer_list = iface.mapCanvas().layers()
    layer = layer_list[0]
    print(layer_list[0])

    
    layer.loadNamedStyle(str(file))
    #layer.triggerRepaint()
    print('layout geändert')

    #map:
    map1 = QgsLayoutItemMap(layout)
    map1.attemptMove(QgsLayoutPoint(55,35, QgsUnitTypes.LayoutMillimeters))
    map1.attemptResize(QgsLayoutSize(240, 240, QgsUnitTypes.LayoutMillimeters))
    map1.setExtent(layer.extent())
    map1.setLayers([layer])
    map1.setScale(10000000)
    layout.addLayoutItem(map1)

    map1.storeCurrentLayerStyles()
    map1.setKeepLayerSet(True)
    map1.setKeepLayerStyles(True)
    print('map')
    # title:

    title = QgsLayoutItemLabel(layout)
    name_title = name.replace("_", " ")
    title.setText(name_title)
    title.setFont(QFont('Arial', 24))
    title.adjustSizeToText()
    layout.addLayoutItem(title)
    title.attemptMove(QgsLayoutPoint(10, 10, QgsUnitTypes.LayoutMillimeters))

    # legend:
    legend = QgsLayoutItemLegend(layout)
    layerTree = QgsLayerTree()
    layerTree.addLayer(layer)
    legend.model().setRootGroup(layerTree)
    layout.addLayoutItem(legend)
    legend.attemptMove(QgsLayoutPoint(10, 40, QgsUnitTypes.LayoutMillimeters))

    # scalebar:
    scalebar = QgsLayoutItemScaleBar(layout)
    scalebar.setStyle('Line Ticks Up')
    scalebar.setUnits(QgsUnitTypes.DistanceKilometers)
    scalebar.setNumberOfSegments(2)
    scalebar.setNumberOfSegmentsLeft(0)
    scalebar.setUnitsPerSegment(250)
    scalebar.setLinkedMap(map1)
    scalebar.setUnitLabel('km')
    scalebar.setFont(QFont('Arial', 14))
    scalebar.update()
    layout.addLayoutItem(scalebar)
    scalebar.attemptMove(QgsLayoutPoint(200, 20, QgsUnitTypes.LayoutMillimeters))
    print('scalebar')
    manager = project.layoutManager()
    layout = manager.layoutByName(name)
    exporter = QgsLayoutExporter(layout)
    fn = 'C:/Users/.../maps/'+name+'.pdf'
#exporter.exportToImage(fn, QgsLayoutExporter.ImageExportSettings())
    exporter.exportToPdf(fn, QgsLayoutExporter.PdfExportSettings())

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS-Version | 3.10.1-A Coruña | QGIS-Codeversion | ef24c526da
-- | -- | -- | --
Kompiliert gegen Qt | 5.11.2 | Laufendes Qt | 5.11.2
Kompiliert mit GDAL/OGR | 3.0.2 | Läuft mit GDAL/OGR | 3.0.2
Kompiliert mit GEOS | 3.8.0-CAPI-1.13.1 | Läuft mit GEOS | 3.8.0-CAPI-1.13.1
Kompiliert mit SQLite | 3.29.0 | Läuft mit SQLite | 3.29.0
PostgreSQL-Client-Version | 11.5 | SpatiaLite-Version | 4.3.0
QWT-Version | 6.1.3 | QScintilla2-Version | 2.10.8
Kompiliert mit PROJ | 6.2.1 | Läuft mit PROJ | Rel. 6.2.1, November 1st, 2019
BS-Version | Windows 10 (10.0)
Aktive Python-Erweiterungen | db_manager; MetaSearch; processing

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
> 3.10.1-A Coruña

@CarinaHe too old and unsupported, test on the latest 3.16 or 3.20.

**Comment by CarinaHe** [comment]
I tried with QGIS 3.20... same result!

**Comment by CarinaHe** [comment]
@gioman I tried with QGIS 3.20... same result!

**Comment by gioman** [comment]
> I tried with QGIS 3.20... same result!

@CarinaHe you should post/ask in the QGIS developers mailing list, a not well written pyqgis code can always lead to crashes.

**Comment by Gustry** [comment]
Can you reduce the script to show which line is crashing ?

**Comment by CarinaHe** [comment]
@Gustry: it crashes between the script line:"layer = layer_list[0]" and "layer.loadNamedStyle(str(file))". I put printstatements there to check... somehow the style-change don't work a third time...
