### ISSUE TITLE
QGIS Crashes when clipping to atlas feature

### ISSUE THREAD

**Issue by Gabriel-Diosan** [qgis/QGIS#45190]
### What is the bug or the crash?

QGIS crashed when attempting to clip to atlas feature in a layout. See below for stack trace. The data involved one aerial photo and a number of vector layers.

I have seen this crash happen on and off in certain projects when using the atlas clipping functionality.

## Report Details

**Crash ID**: [2a1d1a6a69c308d287c005385d42ea2d632aaa22](https://github.com/qgis/QGIS/search?q=2a1d1a6a69c308d287c005385d42ea2d632aaa22&type=Issues)

**Stack Trace**
<pre>
<lambda_f9df9357b59308232c662f60ff03cd78>::operator() qgssymbol.cpp:1156
<lambda_f9df9357b59308232c662f60ff03cd78>::operator() qgssymbol.cpp:1174
QgsSymbol::renderFeature qgssymbol.cpp:1191
QgsFeatureRenderer::renderFeature qgsrenderer.cpp:131
QgsVectorLayerRenderer::drawRenderer qgsvectorlayerrenderer.cpp:462
QgsVectorLayerRenderer::renderInternal qgsvectorlayerrenderer.cpp:403
QgsVectorLayerRenderer::render qgsvectorlayerrenderer.cpp:228
QgsMapRendererCustomPainterJob::doRender qgsmaprenderercustompainterjob.cpp:317
QgsMapRendererCustomPainterJob::staticRender qgsmaprenderercustompainterjob.cpp:267
QtConcurrent::RunFunctionTask<void>::run qtconcurrentrunbase.h:136
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.18.3-Z�rich
QGIS code revision: 735cc85be9
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

### Steps to reproduce the issue

1. Open QGIS with raster and vector layers
2. Create a map layout.
3. Create an atlas based on polygon features.
4. Select the Map and under the Item Properties tab click on the Clipping Settings button and enable Clip to Atlas Feature.
5. QGIS will sometimes crash.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.18.3-Zürich | QGIS code revision | 735cc85be9
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | DataPlotly; GeometryShapes; qfieldsync; db_manager; MetaSearch; processing

</body></html>

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
> 3.18.3-Zürich

Too old
Could you retry with a supported QGIS version?

**Comment by Gabriel-Diosan** [comment]
Retested with QGIS 3.20.3 on Windows 10. Seeing the same crash. 

I also tested using QGIS 3.20.3 on Fedora 34 but did not notice the crash. However there were a few differences on the Linux setup. These were:

1. No aerial photo was being used; and
2. The data was on a local drive and not accessed off a shared network drive.

Hope that helps narrow things down a bit.

**Comment by gioman** [comment]
> Hope that helps narrow things down a bit.

@Gabriel-Diosan 
more or less, can you try the same scenario/project/datasources in Fedora too?

**Comment by nyalldawson** [comment]
Can you share a project which demonstrates this?

**Comment by Gabriel-Diosan** [comment]
@nyalldawson I have a project file in which I can reproduce the crash. Is it best to just upload it here?

@gioman unfortunately I can't. The shared drive is on a corporate network and I am not allowed to connect to it from my Linux machine at home.

**Comment by nyalldawson** [comment]
@Gabriel-Diosan yes please!

**Comment by Gabriel-Diosan** [comment]
[QGIS Test Project.zip](https://github.com/qgis/QGIS/files/7275157/QGIS.Test.Project.zip)

**Comment by Gabriel-Diosan** [comment]
@nyalldawson I have attached the project. When I first enable the clipping QGIS does not crash but once I move to the next map, QGIS crashes. I have also included a screenshot of the crash in the folder. Hope this is helpful in tracking down the issue.

**Comment by nyalldawson** [comment]
@Gabriel-Diosan that archive is missing the "Right_of_ways.gpkg" file which is driving the atlas -- can you upload that one too?

**Comment by Gabriel-Diosan** [comment]
[QGIS Test Project.zip](https://github.com/qgis/QGIS/files/7282132/QGIS.Test.Project.zip)

**Comment by Gabriel-Diosan** [comment]
@nyalldawson apologies. That layer was still accessed off the our corporate network. I have included it in the re-uploaded project. Having the Right_of_ways layer on the local disk still results in a crash for me.
