### ISSUE TITLE
WMS parent layer added via QGIS Browser doesn't use default style

### ISSUE THREAD

**Issue by pathmapper** [qgis/QGIS#45192]
### What is the bug or the crash?

WMS parent layer added via QGIS Browser doesn't use default style.

### Steps to reproduce the issue

1. In QGIS Browser, add the following WMS connection: https://alkisservices.krzn.de/WMS_ALKIS_viersen/ALKIS
2. Open the debug panel to observe the network requests
3. Add layer _Viersen Amtliche Basiskarte 1:2500_ via drag and drop to the layers widget 
4. Inspect the GetMap URL, it contains parameter `STYLES=gelb` but it should be `STYLES=`

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

QGIS version | 3.21.0-Master | QGIS code revision | 8af1fae48c
-- | -- | -- | --
Qt version | 5.12.8
Python version | 3.8.10
GDAL/OGR version | 3.0.4
PROJ version | 6.3.1
EPSG Registry database version | v9.8.6 (2020-01-22)
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
SQLite version | 3.31.1
PostgreSQL client version | 12.8 (Ubuntu 12.8-0ubuntu0.20.04.1)
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.2
OS version | Ubuntu 20.04.3 LTS
  |   |   |  
Active Python plugins | sagaprovidergrassproviderMetaSearchprocessingdb_manager

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

From the [WMS 1.3.0 spec](https://portal.ogc.org/files/?artifact_id=14416):

> 7.3.3.4 STYLES 
> 
>[...]
>A client may request the default Style using a null value (as in “STYLES=”).
>[...]
> If the server advertises several styles for a layer, and the client sends a request for the default style, the choice of 
> which style to use as default is at the discretion of the server. The ordering of styles in the service metadata does 
> not indicate which is the default.

From https://alkisservices.krzn.de/WMS_ALKIS_viersen/ALKIS?SERVICE=WMS&REQUEST=GetCapabilities :

![image](https://user-images.githubusercontent.com/20856381/134292914-261d6759-2f25-4353-a21b-4fb0428ecd57.png)

**Comment by elpaso** [comment]
I think I can fix this, but there is still a different behavior between the browser and the data source manager dialog: in the dialog you have an individual entry for each style while in the browser there isn't. But I guess that it would be a different issue, probably a feature request.

**Comment by pathmapper** [comment]
Just tried the fix, works great, thanks @elpaso :tada: 

> I guess that it would be a different issue, probably a feature request

I think so too.
