### ISSUE TITLE
LineString showing offset in CRS 3857 when using Vertex Tool and "Clip Features to Canvas Extent" is enabled

### ISSUE THREAD

**Issue by beyhh** [qgis/QGIS#45200]
### What is the bug or the crash?

The Vertex Tool highlights a LineString which passes somewhere else than the shown LineString on the Canvas.  
Could it be that QGIS does not properly interpolate between two vertices when drawing the LineString? Only when hovering over the line is it properly displayed it seems...

![2_QGIS_Linestring_Offset_3857](https://user-images.githubusercontent.com/66669404/134319448-97909e54-9018-4be8-9ec6-d2a644cfce66.jpg)
![1_QGIS_Linestring_Offset_3857](https://user-images.githubusercontent.com/66669404/134319451-d31e68b0-e411-48c6-95dd-de4f0935153e.jpg)

The issue seems to be related to the feature "Clip Features to Canvas Extent". Disabling this function under Symbology Advanced settings solves the problem but will cost performance? It would probably be better to update or improve the clipping algorithm _qgsclipper.cpp:514_

![3_QGIS_Clip_features](https://user-images.githubusercontent.com/66669404/134407935-a5f62a30-394f-4232-ad14-08acfdd4ea3c.jpg)

### Steps to reproduce the issue

Create New Project
Project CRS 3857 (automatic when pulling OpenStreetMap XYZ Tiles into canvas)
Create new Vector Layer with LineString geometry (defaults to 4326 - WGS 84)
Draw a long diagonal line with only two points on the canvas (several hundred to thousand of miles long to see the effect more clearly)
Activate the Vertex Tool
Zoom in so that only part of the line just drawn is visible (and not the entire line)
Hover over the line and see that a different line is highlighted that has a considerable (visual) offset from the line shown in QGIS.

### Versions

QGIS version | 3.16.6-Hannover | QGIS code revision | bfd36fddc9
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | AppendFeaturesToLayer; DigitizingTools; latlontools; mmqgis; postgis_geoprocessing; shapetools; splitmultipart; db_manager; MetaSearch; processing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
>  Hover over the line and see that a different line is highlighted that has a considerable (visual) offset from the line shown in QGIS.

@beyhh I cannot replicate on QGIS master. I think I have seen some related PR recently, but can't find it now. Would you mind also test QGIS master?

**Comment by beyhh** [comment]
Hello again,

tried today with this QGIS version:


QGIS version
3.20.3-Odense
QGIS code revision
495fbaec
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.1
PROJ version
8.1.1
EPSG Registry database version
v10.028 (2021-07-07)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 (10.0)

Still the same. Please zoom in so that only a part of the line is visible. Then, with the Vertex Tool selected, try to hover over the line. You will see the red highlighted line has an offset. 
When you disable "Clip Features to Canvas Extent" the problem is solved but in a larger project file with several "world-wide" layers I now get a warning after I disabled this function:

"Insufficient memory for image 1497x887"

Just disabling this useful function is therefore not the best solution it seems. It would be better to update the _qgsclipper_
