### ISSUE TITLE
WFS Layer from QGIS Server is not rendered because of an issue with coordinate axis order

### ISSUE THREAD

**Issue by pathmapper** [qgis/QGIS#45216]
### What is the bug or the crash?

WFS Layer from QGIS Server is not rendered when requested CRS is not matching project CRS and _Only request features overlapping the view extent_ option is set because of an issue with coordinate axis order.

### Steps to reproduce the issue

1. From the QGIS top menu: _Settings_ -> _Options_ -> _CRS_ -> use `EPSG:25832` as default CRS

![image](https://user-images.githubusercontent.com/20856381/134455980-60d6b261-523c-4e63-aff3-daaf05394010.png)

2. From the QGIS top menu: _Layer_ -> _Add Layer_ -> _Add WFS Layer..._ -> make sure the checkbox for _Only request features overlapping the view extent_ is checked

<img src="https://user-images.githubusercontent.com/20856381/126657153-167c4f6e-0865-4608-9f91-dcf0bb476328.png" width="400">

3. Restart QGIS
4. Add WFS connection: https://geo.kreis-viersen.de/ows/abk-material-nrw
5. QGIS Browser: Add layer: `test_layer_epsg_4326` or use the _Add WFS Layer..._ dialog with CRS EPSG:4326
6. See error: `test_layer_epsg_4326` is not rendered and warnings/hints are displayed:

`CRITICAL    Layer test_layer_epsg_4326 : It is likely that there is an issue with coordinate axis order of geometries when interacting with the server. You may want to enable the Ignore axis orientation and/or Invert axis orientation settings of the WFS connection.`

![image](https://user-images.githubusercontent.com/20856381/134455902-29ac5480-006c-47b0-a812-15b59f25293b.png)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

QGIS version | 3.21.0-Master | QGIS code revision | 012f2a51f0
-- | -- | -- | --
Qt version | 5.12.8
Python version | 3.8.10
GDAL/OGR version | 3.0.4
PROJ version | 6.3.1
EPSG Registry database version | v9.8.6 (2020-01-22)
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
SQLite version | 3.31.1
PostgreSQL client version | 12.8 (Ubuntu 12.8-0ubuntu0.20.04.1)
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.2
OS version | Ubuntu 20.04.3 LTS
  |   |   |  
Active Python plugins | sagaprovidergrassproviderMetaSearchprocessingdb_manager

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

This has been reported before in https://github.com/qgis/QGIS/issues/44054 but according to https://github.com/qgis/QGIS/issues/44054#issuecomment-918403489 this isn't a client issue:

> The issue here is on the WFS server. One can see in https://geo.kreis-viersen.de/ows/abk-material-nrw?SERVICE=WFS&REQUEST=GetFeature&VERSION=1.1.0&TYPENAME=test_layer_epsg_4326 that it uses a longitude, latitude order for coordinates, but in WFS 1.1.0, it should respect the EPSG axis order of EPSG:4326 which is latitude, longitude.
> The workaround is to check the "Ignore axis orientation (WFS 1.1/2.0)" checkbox when setting the server.
> In #45044, I've added a hint to the user

From https://github.com/qgis/QGIS/issues/44054#issuecomment-919186443:

> It would be much less ambiguous if QGIS server would use srsName=urn:ogc:def:crs:EPSG::4326 and latitude/longitude order

**Comment by elpaso** [comment]
I don't think this is a bug. QGIS Server is following GeoServer convention as explained in:  https://docs.geoserver.org/stable/en/user/services/wfs/axis_order.html.

**Comment by pathmapper** [comment]
Right, I should have quoted also my comment from https://github.com/qgis/QGIS/issues/44054#issuecomment-919137141 where I mentioned this.

It feels a bit unfortunate that QGIS Desktop is not rendering a WFS layer from QGIS Server while throwing such a warning.

I think there are in general three options now:
1. do nothing
2. change the behavior of QGIS Server
3. change the behavior of QGIS Desktop

@elpaso do you prefer to leave it like it is (option 1)?

**Comment by elpaso** [comment]
Maybe the best solution is to make the server respond with `urn:ogc:def:crs:EPSG::4326` as suggested by @rouault  for WFS 1.1.

**Comment by pathmapper** [comment]
If we assume QGIS server is following GeoServer convention, why is the following request with `SRSNAME=urn:ogc:def:crs:EPSG::4326` returning coordinates in LON/LAT order with `EPSG:4326` representation?

https://geo.kreis-viersen.de/ows/abk-material-nrw?SERVICE=WFS&REQUEST=GetFeature&VERSION=1.1.0&TYPENAME=test_layer_epsg_4326&SRSNAME=urn:ogc:def:crs:EPSG::4326

![grafik](https://user-images.githubusercontent.com/20856381/134897008-7f72f8fe-55f0-475e-8129-5b32c50eee9e.png)

It should be LAT/LON with `urn:ogc:def:crs:EPSG::4326` representation instead.

**Comment by elpaso** [comment]
> If we assume QGIS server is following GeoServer convention, why is the following request with `SRSNAME=urn:ogc:def:crs:EPSG::4326` returning coordinates in LON/LAT order with `EPSG:4326` representation?
> 
> https://geo.kreis-viersen.de/ows/abk-material-nrw?SERVICE=WFS&REQUEST=GetFeature&VERSION=1.1.0&TYPENAME=test_layer_epsg_4326&SRSNAME=urn:ogc:def:crs:EPSG::4326
> 
> ![grafik](https://user-images.githubusercontent.com/20856381/134897008-7f72f8fe-55f0-475e-8129-5b32c50eee9e.png)
> 
> It should be LAT/LON with `urn:ogc:def:crs:EPSG::4326` representation instead.

This may well be a bug.

**Comment by elpaso** [comment]
How does this look?

`SERVICE=WFS&REQUEST=GetFeature&VERSION=1.1.0&SRSNAME=urn:ogc:def:crs:EPSG::4326&TYPENAME=testlayer&FEATUREID=testlayer.0`

```xml
<wfs:FeatureCollection xmlns:wfs="http://www.opengis.net/wfs" xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml" xmlns:ows="http://www.opengis.net/ows" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:qgs="http://www.qgis.org/gml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wfs http://schemas.opengis.net/wfs/1.1.0/wfs.xsd http://www.qgis.org/gml ?MAP=/home/ale/dev/QGIS/tests/testdata/qgis_server/test_project_wfs.qgs&amp;SERVICE=WFS&amp;VERSION=1.1.0&amp;REQUEST=DescribeFeatureType&amp;TYPENAME=testlayer&amp;OUTPUTFORMAT=text/xml; subtype%3Dgml/3.1.1">
<gml:boundedBy>
 <gml:Envelope srsName="urn:ogc:def:crs:EPSG::4326">
  <gml:lowerCorner>44.90139484 8.20345931</gml:lowerCorner>
  <gml:upperCorner>44.90148253 8.20354699</gml:upperCorner>
 </gml:Envelope>
</gml:boundedBy>
<gml:featureMember>
 <qgs:testlayer gml:id="testlayer.0">
  <gml:boundedBy>
   <gml:Envelope srsName="urn:ogc:def:crs:EPSG::4326">
    <gml:lowerCorner>44.90148253 8.20349634</gml:lowerCorner>
    <gml:upperCorner>44.90148253 8.20349634</gml:upperCorner>
   </gml:Envelope>
  </gml:boundedBy>
  <qgs:geometry>
   <Point xmlns="http://www.opengis.net/gml" srsName="urn:ogc:def:crs:EPSG::4326">
    <pos xmlns="http://www.opengis.net/gml" srsDimension="2">44.90148253 8.20349634</pos>
   </Point>
  </qgs:geometry>
  <qgs:id>1</qgs:id>
  <qgs:name>one</qgs:name>
  <qgs:utf8nameè>one èé</qgs:utf8nameè>
 </qgs:testlayer>
</gml:featureMember>
</wfs:FeatureCollection>
```
