### ISSUE TITLE
Saving a shp in a GeoPackage will inherit the geopackage name

### ISSUE THREAD

**Issue by 0verlord84** [qgis/QGIS#45214]
### What is the bug or the crash?

By default, when exporting a shapefile in a GeoPackage will cause the Layer name to inherit the geopackage name (fig below).

![image](https://user-images.githubusercontent.com/43800695/134450873-12fcf048-7b5a-442e-a913-f5bec2956aae.png)

Even if the Layer name is edited, the final layer loaded in the canvas will still retain the GeoPackage name and the chosen name will be appended at the end of the string (pic below)

![image](https://user-images.githubusercontent.com/43800695/134451098-1c810a33-5afb-423d-98ff-a95a22677e8f.png)

### Steps to reproduce the issue

1. Right-click on a shapefile in the Layers panel -> Export -> Save feature as...
2. Choose "GeoPackage" from the Format list and select the GeoPackage of interest
3. Delete the default Layer name and insert any name
4. Make sure the "Add saved file to map" is ticked on
5. Hit ok
6. See in the Layers panel the exported table has the GeoPackage name as a prefix and the input Layer name as a suffix

### Versions

QGIS version
3.16.11-Hannover
QGIS code revision
26cc1c76
Compiled against Qt
5.15.2
Running against Qt
5.15.2
Compiled against GDAL/OGR
3.3.1
Running against GDAL/OGR
3.3.1
Compiled against GEOS
3.9.1-CAPI-1.14.2
Running against GEOS
3.9.1-CAPI-1.14.2
Compiled against SQLite
3.35.2
Running against SQLite
3.35.2
PostgreSQL Client Version
13.0
SpatiaLite Version
5.0.1
QWT Version
6.1.3
QScintilla2 Version
2.11.5
Compiled against PROJ
8.1.1
Running against PROJ
Rel. 8.1.1, September 1st, 2021
OS Version
Windows 10 Version 2009
Active python plugins
AusMap; 
DataPlotly; 
DigitizingTools; 
icsm_ntv2_transformer; 
mapswipetool_plugin; 
Mergin; 
mmqgis; 
pointsamplingtool; 
polygonclickmap; 
postgisQueryBuilder; 
profiletool; 
qgis2web; 
QuickOSM; 
quick_map_services; 
qveg; 
slyr_community; 
tuflow; 
valuetool; 
VectorBender; 
db_manager; 
processing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
> See in the Layers panel the exported table has the GeoPackage name as a prefix and the input Layer name as a suffix

@0verlord84 this is very much by design.

**Comment by uclaros** [comment]
It's indeed by design, though maybe we should consider changing it, since it is different to how layers appear when dragged from a geopackage into QGIS...
Or maybe skip it when geopackage name and layer name are the same.
