### ISSUE TITLE
Photo in a layer tooltip is not displayed

### ISSUE THREAD

**Issue by sigmoe** [qgis/QGIS#45210]
### What is the bug or the crash?

I use a HTML tooltip on a layer in which I want to display a photo (the file name is in a particular field).
In the canvas, when the tooltip appears, the photo isn't displayed. In QGIS 2.18 it works (the photo is displayed), in QGIS 3.16 it doesn't work anymore.

### Steps to reproduce the issue

See my video and my project (with all necessary files) attached to reproduce the issue.

https://user-images.githubusercontent.com/55922863/134391059-973a738f-e255-4ef8-aa8c-12d08a4b928d.mp4
[ReseauxTest.zip](https://github.com/qgis/QGIS/files/7212628/ReseauxTest.zip)

### Versions

Version de QGIS
3.16.8-Hannover
Révision du code
8c50902ea4
Compilé avec Qt
5.11.2
Utilisant Qt
5.11.2
Compilé avec GDAL/OGR
3.1.4
Utilisé avec GDAL/OGR
3.1.4
Compilé avec GEOS
3.8.1-CAPI-1.13.3
Utilisé avec GEOS
3.8.1-CAPI-1.13.3
Compilé avec SQLite
3.29.0
Fonctionne avec SQLite
3.29.0
Version du client PostgreSQL
11.5
Version de SpatiaLite
4.3.0
Version de QWT
6.1.3
Version de QScintilla2
2.10.8
Compilé avec PROJ
6.3.2
Fonctionne avec PROJ
Rel. 6.3.2, May 1st, 2020
Version de l'OS
Windows 10 (10.0)
Extensions Python actives
geograndest; 
SgmDxfImportPro; 
db_manager; 
processing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

With the same project and the same HTML code for the tooltip, in QGIS 2.18 it works (the photo is displayed), whereas in QGIS 3.16 it doesn't work anymore.

**Comment by gioman** [comment]
this

`<img src="file://[% @project_folder  || '/' ||  "Photo" %]" width=148 height=198 />`

works here.

**Comment by sigmoe** [comment]
Thanks for this answer. It works, but with just one / after file:
`<img src="file:/[% @project_folder  || '/' || "Photo" %]" width=148 height=198 />`

**Comment by gioman** [comment]
Here on Linux it must be file://

closing?

**Comment by sigmoe** [comment]
Ok, I'm on Windows.
We can close.
