### ISSUE TITLE
A customisable ribbon for QGIS

### ISSUE THREAD

**Issue by M-Rick** [qgis/QGIS#45225]
### Feature description

For the ones who prefers ribbons than toolbars, the guys of GIAP-PolaMap just released a brand new plugin with this feature.
Unfortunately, the plugin is first aimed to be used with the Polish GIAP services. And it has a theming that not everybody would ever like.

So I just forked it to release a customised version keeping only the amazing part for the rest of us, the ribbon. I cleaned it out from the styles and the polish inside in order to keep the default GUI settings. I removed mostly 2 megabytes of files to repack it in a brand new ribbon plug-in only.  I am not the one using most of ribbons softwares, but at least, now you have a ribbon in QGIS that can customised if you want to.
Anyway, this could be a feature to embed in a future version of QGIS as a preference setting. That doesn't seem big deal to be done, the big part of the work has already been done by the GIAP PolaMap  team.

The plug-in disables all the QGIS toolbars, so don’t forget first to back-up your settings to avoid troubleshooting. The toolbars are back when the plug-in is unactivated.
If you wanna give it a try, just get it from my GitHub space.

https://github.com/M-Rick/QGIS-Ribbon

![Capture d’écran 2021-09-23 à 16 36 14](https://user-images.githubusercontent.com/2520948/134569815-29b0da79-e6c4-4220-a908-c6ef5660a5a8.png)

**Comment by gioman** [comment]
@M-Rick why you don't publish it as a plugin in qgis repository?
