### ISSUE TITLE
Irregular topography after coordinate transformation

### ISSUE THREAD

**Issue by Zetison** [qgis/QGIS#45222]
### What is the bug or the crash?

After performing a coordinate transformation on the EU_DEM data set (obtained [here](https://land.copernicus.eu/imagery-in-situ/eu-dem/eu-dem-v1.1?tab=mapview)) regular discrepancies emerge in the output as illustrated by the following:
Original:
![image](https://user-images.githubusercontent.com/16941906/134496531-082b8abd-6353-4714-aed4-9fb58c659259.png)
Converted
![image](https://user-images.githubusercontent.com/16941906/134496561-50513b16-cf1d-468d-b081-9b9fe461da5e.png)
Visualization in 3D (paraview):
![image](https://user-images.githubusercontent.com/16941906/134496638-f0becf20-7c13-412d-a7b7-13cd15effc43.png)

### Steps to reproduce the issue

[eu_dem_v11_E00N20.zip](https://github.com/qgis/QGIS/files/7216958/eu_dem_v11_E00N20.zip)

1. Extract the eu_dem_v11_E00N20.zip file
2. In QGIS: Layer -> Add Layer -> Add Raster Layer... -> Open the extracted .TIF file and zoom to the main Island (Santa Cruz Das Flores)
3. Right click this layer and click export -> Save as... (set an export file name, and set CRS : "Project CRS: EPSG:4326 - WGS 84", use "Map Canvas Extent" for the extent of the exported file.
4. Observe the irregular topography (by zooming in) compared to the original file.
Right-click

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.10.4-A Coruña | QGIS code branch | Release QGIS code branch.3
-- | -- | -- | --
Compiled against Qt | 5.12.8 | Running against Qt | 5.12.8
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.2 (Ubuntu 12.2-4) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Ubuntu 20.04.3 LTS
Active python plugins | gis4wrf; processing; MetaSearch; db_manager

</body></html>

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

The reason I do not use the latest LTR is that I need to use the GIS4WRF plugin.

**Comment by gioman** [comment]
>     3\. Right click this layer and click export -> Save as... (set an export file name, and set CRS : "Project CRS: EPSG:4326 - WGS 84", use "Map Canvas Extent" for the extent of the exported file.

@Zetison does it happens the same if you create a copy with gdal warp instead (Processing toolbox)?

**Comment by Zetison** [comment]
> > ```
> > 3\. Right click this layer and click export -> Save as... (set an export file name, and set CRS : "Project CRS: EPSG:4326 - WGS 84", use "Map Canvas Extent" for the extent of the exported file.
> > ```
> 
> @Zetison does it happens the same if you create a copy with gdal warp instead (Processing toolbox)?

Thanks for you reply! Yes, gdalwarp reproduces the error. With some trial and errors, the following worked better (for the Norway case):

gdalwarp ~/WPS_DATA/EU_DEM/eu_dem_v11_E40N40.TIF test.tif -te 5.403153641 62.099104746 6.686122391 62.721377390 -tr 0.000485992 0.000224982 -srcnodata "-3.4028234663852886e+38" -dstnodata 0 -t_srs "EPSG:4326" -overwrite -r bilinear

Is the "bilinear" resampling method available in QGIS?

**Comment by gioman** [comment]
> Is the "bilinear" resampling method available in QGIS?

@Zetison yes, with GDAL :)

jokes apart, I'm not sure if the "save raster as..." QGIS functionality has any resampling option, if not probably it would be better to have it, bit this would be a feature request. If GDAL warp is a good enough workaround then please close this ticket and open a feature request for the "save raster as..." functionality.
