### ISSUE TITLE
multi ring constant buffer: rings produced away from the specified central point

### ISSUE THREAD

**Issue by CieloBuio** [qgis/QGIS#45220]
### What is the bug or the crash?

I'm trying to use (as I made months ago, but then with success) the multi ring constant buffer (under: processing tools) to produce a series of rings around a specific coordinate point. 
The problem is that it produces the rings, but not around the specified point. See the example in the screenshot.
<img width="883" alt="multi rings not on Hawaii" src="https://user-images.githubusercontent.com/91252139/134481076-636ea881-c6e3-4f82-ba1b-0e6800931e7f.PNG">
t.

### Steps to reproduce the issue

The problem seems to arise when a coordinate point in WGS84 is converted in some UTM, changing the SR. Here the point that is supposed to be in Chile (coordinates: -70.1916106,-24.5893836), after duplicating it and ghanging the EPSG from 4326 to 5361 ( I need this to have rings in km), has been put in Antartica!
![immagine](https://user-images.githubusercontent.com/91252139/134483753-2e02d3cb-00ce-45f0-b072-aac369b4517e.png)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

Versione di QGIS | 3.16.3-Hannover | Revisione codice QGIS | 94ac9f21b8
-- | -- | -- | --
Compilato con Qt | 5.11.2 | Esecuzione con Qt | 5.11.2
Compilato con GDAL/OGR | 3.1.4 | Esecuzione con GDAL/OGR | 3.1.4
Compilato con GEOS | 3.8.1-CAPI-1.13.3 | Esecuzione con GEOS | 3.8.1-CAPI-1.13.3
Compilato su SQLite | 3.29.0 | In esecuzione su SQLite | 3.29.0
Versione client PostgreSQL | 11.5 | Versione SpatiaLite | 4.3.0
Versione QWT | 6.1.3 | Versione QScintilla2 | 2.10.8
Compilato con PROJ | 6.3.2 | Esecuzione con PROJ | Rel. 6.3.2, May 1st, 2020
Versione SO | Windows 10 (10.0)
Attiva python plugin | gearthview3; layer2kmz; Multi_Ring_Buffer; QuickOSM; quick_map_services; rasterstats; Serval; valuetool; db_manager; MetaSearch; processing

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
> Here the point that is supposed to be in Chile (coordinates: -70.1916106,-24.5893836), after duplicating it and ghanging the EPSG from 4326 to 5361

@CieloBuio so the steps yo have followed were

add the layer in 4326
duplicated it
in the duplicate layer you manually changed its CRS in the "source" panel
buffered the duplicated

if the above its correct then you are doing it wrong.

**Comment by CieloBuio** [comment]
@gioman saying that I'm doing wrong with no suggestions does not help a lot. I may suppose from your writing that there should be one or more additional things to do. May be, exporting the shp imposing the new SR and then using the buffer multi-ring? This works, but why QGis does not recognise the manually changed CSR? Not very intuitive

**Comment by gioman** [comment]
> Not very intuitive

@CieloBuio I was not sure that it was what you did, so I asked before giving you an answer. Easy explanation.

The correct way to do it is to right click on your original vector and select "export", and in the resulting dialog choose where to save the copy, the format for the copy and the CRS for the copy.

**Comment by gioman** [comment]
I guess we can close this?

**Comment by CieloBuio** [comment]
Yes, thank you! But it remains the problem that QGis does not alert you that the procedure is wrong, without exporting in advance. The buffer multi-ring panel asks for a layer to be used to generate the rings, but accept also the 'wrong' temporary and manually changed. Adjusting this may help others wast time.

**Comment by gioman** [comment]
> But it remains the problem that QGis does not alert you that the procedure is wrong

@CieloBuio it does at least in recent versions

![image](https://user-images.githubusercontent.com/1951107/134505382-eb9ddbab-7058-44e9-bdfd-1558d9df2247.png)

**Comment by CieloBuio** [comment]
Thank you. Then I'll update to 3.20 once this will become LTR.
