### ISSUE TITLE
Crash when trying to open layer properties

### ISSUE THREAD

**Issue by steen21** [qgis/QGIS#45249]
### What is the bug or the crash?

Crash

### Steps to reproduce the issue

Add 3DEP 1/3 arc second DEM(s)
Merge DEM(s)
Clip to polygon (using Clip by Extent)
Right-click clipped and merged DEM
Click properties
change render type to single psuedocolor
See error

### Versions

QGIS version
3.16.0-Hannover
QGIS code revision
43b64b13f3
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
closest_points; 
d3datavis; 
numericalDigitize; 
quick_map_services; 
db_manager; 
MetaSearch; 
processing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
>  3.16.0-Hannover

@steen21 way to old. Install the latest 3.16 and reopen if you have the same issue.
