### ISSUE TITLE
WFS connection manager: GetCapabilities document's URLs not being used consistently

### ISSUE THREAD

**Issue by kit-rothwell** [qgis/QGIS#45242]
### What is the bug or the crash?

If you are using a GetCapabilities endpoint that proxies to GeoServer, and you add a layer with the WFS connection manager the majority of URLs (GetFeature, DescribeFeatureType, etc) are using the URLs in the document as expected. But if you open the attribute table and try to edit some data, it will try to use the proxy URL to make the post request. 

Additionally if you double click a layer in the WFS connection manager it will make a DescribeFeatureType request and attempt to use the proxy URL for that as well.

I have used the 'QGIS Network Logger' plugin to observe the requests being made:
![image](https://user-images.githubusercontent.com/91317126/134659946-4f57c5d8-d0fc-48ce-b981-e3773a50f826.png)
You can see in the request list it's generally calling the raw geoserver endpoint which is as expected, except when it attempts to make the post request and then tries to use the URL entered for the connection.

### Steps to reproduce the issue

**Post request issue:**
1. Go to 'Layer' > 'Add Layer' > 'Add WFS Layer'
2. Click on 'New' under Server Connections 
3. Enter a name and the proxy URL used to get the capabilities document in connection details, then click 'OK'
4. Click on 'Connect' under Server Connections and add the layer that appears in the list
5. Go to the Layers panel and right click on the layer that was added then click 'Open Attribute Table'
6. Click on 'Toggle editing mode' button, and then update the data in a cell and attempt to save
7. Observe the commit error that appears at the top of the viewer panel

**DescribeFeatureType issue:**
1. Go to 'Layer' > 'Add Layer' > 'Add WFS Layer'
2. Click on 'New' under Server Connections 
3. Enter a name and the proxy URL used to get the capabilities document in connection details, then click OK
4. Click on 'Connect' under Server Connections and double click the layer that appears in the list
5. Observe the Server exception error dialogue that appears

### Versions

3.20.3-Odense

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Also tried this on 3.12.3 before updating to 3.20.3 to see if the issue was present in the later version.

**Comment by rouault** [comment]
Could you provide a URL to a server that demonstrates the issue ?

**Comment by kit-rothwell** [comment]
> Could you provide a URL to a server that demonstrates the issue ?
@rouault I can provide one privately, do you have an email I could send it to?

**Comment by rouault** [comment]
>  I can provide one privately, do you have an email I could send it to?

even.rouault at spatialys.com

**Comment by kit-rothwell** [comment]
Thanks, I've sent an email

**Comment by rouault** [comment]
https://github.com/qgis/QGIS/pull/45267 fixes the 2 issues with the test server provided privately
