### ISSUE TITLE
“QGIS.app” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by dmatranga-bayer** [qgis/QGIS#45250]
### What is the bug or the crash?

I'm not able to open QGIS 3.20 on MacOS Big Sur 11.6.

Error message: 

```
“QGIS.app” can’t be opened because Apple cannot check it for malicious software.
This software needs to be updated. Contact the developer for more information.

Chrome downloaded this file today at 10:49 AM from qgis.org.
```

![2021-09-24_11-18-31](https://user-images.githubusercontent.com/89213310/134709142-2d278478-c77d-4b98-ac07-4494ce9bd245.png)

### Steps to reproduce the issue

- Download QGIS 3.20 for Mac OS from [](https://qgis.org/en/site/forusers/download.html)
- Install on Mac OS
- In Finder, browse to Applications
- Click on QGIS.app to launch

### Versions

3.20

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@dmatranga-bayer https://github.com/qgis/QGIS/issues/34018#issuecomment-578186707

**Comment by stacianordin** [comment]
I have the same issue.
macOS 12.6
“QGIS.app” can’t be opened because Apple cannot check it for malicious software.
This software needs to be updated. Contact the developer for more information.
Safari downloaded this file today at 09:54.

**Comment by octopoulos** [comment]
Go to System Settings => Privacy and Security => You will see an alert that QGIS.app could not be run with an option to "open anyway".
