### ISSUE TITLE
Support for reading E57 point cloud files

### ISSUE THREAD

**Issue by magnusnil** [qgis/QGIS#45271]
### Feature description

Now that QGIS can read and display point cloud cloud data, it would be great if QGIS would be able to read data in the E57 (.e57) format.

According to https://www.lutraconsulting.co.uk/blog/2021/04/06/qgis-pointcloud-tips/, only .las and .laz are supported at the moment, but I noticed that PDAL can read E57 (https://pdal.io/stages/readers.e57.html#readers-e57), so I´m hoping that this format as well could be featured in QGIS.

**Comment by wonder-sk** [comment]
Do you have any data for testing?

**Comment by magnusnil** [comment]
I´ll ask around to see if I can find any data sets internally. Meanwhile, there are quite a few examples at http://www.libe57.org/data.html. I have tried a few of them successfully with FME 2021.0.

**Comment by magnusnil** [comment]
If you are interested in more data sets for testing, I have a large (1,2 GB uncompressed) e57 file, representing building data. Let me know if you would like a copy.

**Comment by c-mellueh** [comment]
Hi, i'm trying to open an e57 file with the 3.30 release candidate and i get the error "Invalide Datasource"
![image](https://user-images.githubusercontent.com/74136980/229730647-24e548fb-c54c-4eeb-a8ce-cc44d59b149e.png)

Do i need to activate some sort of plugin for the e57 import to work?
