### ISSUE TITLE
Error when saving shapefiles as Mapinfo TAB

### ISSUE THREAD

**Issue by giannastavroulaki** [qgis/QGIS#45288]
### What is the bug or the crash?

Error when trying to save a shapefile (shp) as Mapinfo TAB 

### Steps to reproduce the issue

Export to vector file failed.
Error: Feature write errors:
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)
Feature creation error (OGR error: Faile

### Versions

QGIS version | 3.20.2-Odense | QGIS code revision | 9f59a15664
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.8.7
GDAL/OGR version | 3.2.3
PROJ version | 6.3.2
EPSG Registry database version | v9.8.6 (2020-01-22)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.31.1
PDAL version | 2.2.0
PostgreSQL client version | 12.3
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.4
OS version | macOS 10.15
  |   |   |  
Active Python plugins | pst-10processingdb_managerMetaSearch

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
> Export to vector file failed.
> Error: Feature write errors:
> Feature creation error (OGR error: Failed writing attributes for feature id 1 in /Volumes/Backup Plus/GIS_Data_2020/Attraction Data/test3.tab)

@giannastavroulaki as the error message suggest this is likely an error/limitation of the OGR driver, not a problem in QGIS itself.

You probably can test it by trying to translate your shapefile using ogr2ogr on the command line, see

https://gdal.org/programs/ogr2ogr.html
https://gdal.org/drivers/vector/mitab.html#vector-mitab

probably something like

`ogr2ogr -f MITAB output.tab input.shp`
