### ISSUE TITLE
Identify Results Window "walks" down the screen for each subsequent panel.

### ISSUE THREAD

**Issue by esnyder-rve** [qgis/QGIS#45299]
### What is the bug or the crash?

Not sure if this is a bug or feature request. I do a lot of editing attributes via the Identify Results window form (it's a really great feature btw). When I close the window and identify another feature, the created window moves down a little each time (and eventually off the screen). I have to drag the window back up to "reset" the walking.

### Steps to reproduce the issue

1. Identify feature (with feature form mode)
2. Close form
3. (repeat)

### Versions

QGIS version
3.20.3-Odense
QGIS code revision
495fbaec
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.1
PROJ version
8.1.1
EPSG Registry database version
v10.028 (2021-07-07)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
MetaSearch
processing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Here's a video showing the behavior (with a clean profile).

https://user-images.githubusercontent.com/61027950/135110679-268080bb-a9d0-42f4-8cd3-a77fc3f8f0c1.mp4

**Comment by nicogodet** [comment]
Duplicate https://github.com/qgis/QGIS/issues/44050 ?

**Comment by esnyder-rve** [comment]
Yes, duplicate.
