### ISSUE TITLE
Crash after trying to move labels

### ISSUE THREAD

**Issue by glebpinigin** [qgis/QGIS#45301]
### What is the bug or the crash?

I am trying to move labels, but after several attempts QGIS crashes (already 20 times crashed, i hav reload computer, cleared storage of labeling position in project, nothing worked)

### Steps to reproduce the issue

1. Create project. Add natural earth data from gpkg, add table leyaer to gpkg. Connect some attributes between layer.
2. Create geometry generator that creates piechart on each centroid. Expression is valid and works ok
3. Enable labeling
4. Try to move lables using labeling tool

It seems that labels crash QGIS more often when extent of new position intersects extent of old position

Important: first noticed using CUDA acceleration. But than turned off CUDA and problem's still here

### Versions

3.20.3

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

### Additional context

Log from crash handler:
Crash ID: 19f9eee4a371c7d86c612ecb29c2cf70d1f60531

Stack Trace

QgsVectorLayerJoinBuffer::joinedFeatureOf :
QgsVectorLayerJoinBuffer::changeAttributeValue :
QgsVectorLayer::changeAttributeValue :
QgsMapToolMoveLabel::cadCanvasPressEvent :
QgsMapToolAdvancedDigitizing::canvasPressEvent :
QgsMapCanvas::mousePressEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.20.3-Odense
QGIS code revision: 495fbaec
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.1
Running against GDAL: 3.3.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

**Comment by gioman** [comment]
> New profile

@glebpinigin please try with a new QGIS profile and no 3rd party plugins installed.

**Comment by gioman** [comment]
> * Create project. Add natural earth data from gpkg, add table leyaer to gpkg. Connect some attributes between layer.
> 
> * Create geometry generator that creates piechart on each centroid. Expression is valid and works ok
> 
> * Enable labeling
> 
> * Try to move lables using labeling tool

@glebpinigin if the problem persist please attach a minimal project + data that shows the issue.

**Comment by glebpinigin** [comment]
When i change the profile, all my data links drop and geometry generator creates piecharts with radius of 0. In that case all labels are movable without troubles.

_Not new_ profile is not empy but very close from being empty. I created it literally yesterday and installed only profile tool

I can't send you data which i link, because it;s not my. But I'll try replace used data with quiet similar (it's just numbers) and send to you.
