### ISSUE TITLE
QGIS 3.16.11-Hannover keeps crashing, even after clean install and profile

### ISSUE THREAD

**Issue by UhVo86** [qgis/QGIS#45316]
### What is the bug or the crash?

**Crash ID**: [1a20cd27a61826341e2640a13457fd656fc38850](https://github.com/qgis/QGIS/search?q=1a20cd27a61826341e2640a13457fd656fc38850&type=Issues)

**Stack Trace**
<pre>
QSemaphore::acquire :
QgsTask::waitForFinished :
QgsPointLocator::prepare :
QgsPointLocator::nearestVertex :
QgsSnappingUtils::~QgsSnappingUtils :
QgsSnappingUtils::snapToMap :
QgsMeshCalculatorDialog::useFullLayerExtent :
QgsMapCanvas::mouseMoveEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
multipleProviderMetadataFactory :
QgsAbstractFeatureIterator::nextFeature :
QgsVectorLayerFeatureIterator::fetchFeature :
QgsAbstractFeatureIterator::nextFeature :
QgsPointLocator::rebuildIndex :
QgsPointLocator::init :
QgsSnappingUtils::prepareIndex :
QgsSnappingUtils::snapToMap :
QgsMeshCalculatorDialog::useFullLayerExtent :
QgsMapCanvas::mouseMoveEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.16.11-Hannover
QGIS code revision: 26cc1c76
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.1
Running against GDAL: 3.3.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

### Steps to reproduce the issue

It seems random, but here is the stack:
>00: 0x7FF801377BF0 QSemaphore::acquire
>01: 0x7FFFF3FAF540 QgsTask::waitForFinished
>02: 0x7FFFF3F32670 QgsPointLocator::prepare
>03: 0x7FFFF3F31790 QgsPointLocator::nearestVertex
>04: 0x7FFFF3F85A50 QgsSnappingUtils::~QgsSnappingUtils
>05: 0x7FFFF3F89440 QgsSnappingUtils::snapToMap
>06: 0x7FF803FCC750 QgsMeshCalculatorDialog::useFullLayerExtent
>07: 0x7FF801E1D790 QgsMapCanvas::mouseMoveEvent
>08: 0x7FF807017890 QWidget::event
>09: 0x7FF8070B8C80 QFrame::event
>10: 0x7FF8072DA220 QGraphicsView::viewportEvent
>11: 0x7FF801517330 QCoreApplicationPrivate::sendThroughObjectEventFilters
>12: 0x7FF806FF4890 QApplicationPrivate::notify_helper
>13: 0x7FF806FF2170 QApplication::notify
>14: 0x7FFFF3DE2270 QgsApplication::notify
>15: 0x7FF8015152C0 QCoreApplication::notifyInternal2
>16: 0x7FF806FF57E0 QApplicationPrivate::sendMouseEvent
>17: 0x7FF80703D700 QSizePolicy::QSizePolicy
>18: 0x7FF80703D700 QSizePolicy::QSizePolicy
>19: 0x7FF806FF4890 QApplicationPrivate::notify_helper
>20: 0x7FF806FF2170 QApplication::notify
>21: 0x7FFFF3DE2270 QgsApplication::notify
>22: 0x7FF8015152C0 QCoreApplication::notifyInternal2
>23: 0x7FF800922950 QGuiApplicationPrivate::processMouseEvent
>24: 0x7FF80090EC20 QWindowSystemInterface::sendWindowSystemEvents
>25: 0x7FF80155E220 QEventDispatcherWin32::processEvents
>26: 0x7FF800090750 qt_plugin_query_metadata
>27: 0x7FFFECB153A0 multipleProviderMetadataFactory
>28: 0x7FFFF3E72E00 QgsAbstractFeatureIterator::nextFeature
>29: 0x7FFFF4022E70 QgsVectorLayerFeatureIterator::fetchFeature
>30: 0x7FFFF3E72E00 QgsAbstractFeatureIterator::nextFeature
>31: 0x7FFFF3F32710 QgsPointLocator::rebuildIndex
>32: 0x7FFFF3F305A0 QgsPointLocator::init
>33: 0x7FFFF3F888C0 QgsSnappingUtils::prepareIndex
>34: 0x7FFFF3F89440 QgsSnappingUtils::snapToMap
>35: 0x7FF803FCC750 QgsMeshCalculatorDialog::useFullLayerExtent
>36: 0x7FF801E1D790 QgsMapCanvas::mouseMoveEvent
>37: 0x7FF807017890 QWidget::event
>38: 0x7FF8070B8C80 QFrame::event
>39: 0x7FF8072DA220 QGraphicsView::viewportEvent
>40: 0x7FF801517330 QCoreApplicationPrivate::sendThroughObjectEventFilters
>41: 0x7FF806FF4890 QApplicationPrivate::notify_helper
>42: 0x7FF806FF2170 QApplication::notify
>43: 0x7FFFF3DE2270 QgsApplication::notify
>44: 0x7FF8015152C0 QCoreApplication::notifyInternal2
>45: 0x7FF806FF57E0 QApplicationPrivate::sendMouseEvent
>46: 0x7FF80703D700 QSizePolicy::QSizePolicy
>47: 0x7FF80703D700 QSizePolicy::QSizePolicy
>48: 0x7FF806FF4890 QApplicationPrivate::notify_helper
>49: 0x7FF806FF2170 QApplication::notify
>50: 0x7FFFF3DE2270 QgsApplication::notify
>51: 0x7FF8015152C0 QCoreApplication::notifyInternal2
>52: 0x7FF800922950 QGuiApplicationPrivate::processMouseEvent
>53: 0x7FF80090EC20 QWindowSystemInterface::sendWindowSystemEvents
>54: 0x7FF80155E220 QEventDispatcherWin32::processEvents
>55: 0x7FF800090750 qt_plugin_query_metadata
>56: 0x7FF801511620 QEventLoop::exec
>57: 0x7FF8015141F0 QCoreApplication::exec
>58: 0x7FF80402BB30 main
>59: 0x7FF6C26A4DDC ?
>60: 0x7FF6C26A5266 ?
>61: 0x7FF8847E7020 BaseThreadInitThunk
>62: 0x7FF884A02630 RtlUserThreadStart

### Versions

3.16.11-Hannover

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
So there is no clear way to replicate the crash in a consistent manner?

**Comment by UhVo86** [comment]
No, there is no clear way at least that i know of

**Comment by gioman** [comment]
> No, there is no clear way at least that i know of

then is hard to confirm and troubleshoot the problem.

**Comment by UhVo86** [comment]
It occurs usually when i am doing georeferencing

**Comment by kbhossain** [comment]
even my pc also, my version is QGIS 3.16.12-Hannover, even in 3.20 also
