### ISSUE TITLE
Add database tab to Debugging/Development Tools panel

### ISSUE THREAD

**Issue by mvaaltola** [qgis/QGIS#45319]
### Feature description

Add a new tab to the Debugging/Development tools panel to see database queries made by QGIS. This would help in debugging performance issues when using spatial databases with QGIS, especially in cases where DB logs cannot be accessed.

Ideally the new tab would have similar functionality to the existing and very helpful Network Logger tab that shows network requests made by QGIS to e.g. WMS.

**Comment by nyalldawson** [comment]
GREAT idea!! It would certainly make debugging much much easier.
