### ISSUE TITLE
ProductCode or ProductVersion missing in the .MSI file for Microsoft Intune

### ISSUE THREAD

**Issue by doppino** [qgis/QGIS#45333]
### What is the bug or the crash?

When I try to upload the QGIS-OSGeo4W-3.20.3-1.msi file in Intune for Mass deployment, I receive the following error:
The selected app package does not appear to have either a ProductCode or ProductVersion.
Is it possibile to update the future .msi with these two properties ?

### Steps to reproduce the issue

Home -- > Apps -- > Windows --> Add

### Versions

3.20

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by doppino** [comment]
I checked with Microsoft Orca (Microsoft MSI Editor) and in the property section the two properties seems to be there
![Qgis msi orca](https://user-images.githubusercontent.com/54947849/135414696-14e36bcf-e54e-4005-ad35-83add3b5c7d4.jpg)
.

**Comment by agiudiceandrea** [comment]
See https://github.com/qgis/QGIS/issues/49365

**Comment by macnotiz** [comment]
I've the same issue.

**Comment by macnotiz** [comment]
Well, all to this topic related tickets are in closed state, but the problem still exist. 👎

**Comment by jef-n** [comment]
if no additional information is added that helps to get to the bottom of this, the new bug would have been closed eventually like this one.

**Comment by jef-n** [comment]
https://www.reddit.com/r/Intune/comments/zthr33/the_selected_app_package_does_not_appear_to_have/

**Comment by jef-n** [comment]
The error message is apparently misleading and emitted whenever intune is unable to handle the msi.

Using https://github.com/microsoft/Microsoft-Win32-Content-Prep-Tool is apparently possible to produce an .intunewin package from the .msi that intune will digest:

``
IntuneWinAppUtil.exe -c %TEMP%\msi -s QGIS-OSGeo4W-3.40.14-1.msi -o %TEMP%\intune
``

with the msi in %TEMP%\msi

hth
