### ISSUE TITLE
Graph oriented GeoJSON editing and visual mapping for arborescent data structures

### ISSUE THREAD

**Issue by aourednik** [qgis/QGIS#45330]
### Feature description

An __arborescent data editor__ should be added to QGIS for the unfolding of the full potential of GeoJSON. 
One should also be able to __map visuals to deep GeoJSON "property" objects__. Example: the label editor in layer properties should be able to use an expression like  `concat("name.en",' (',"name.local",')')` to construct labels.

### Additional context

[Graph databases](https://en.wikipedia.org/wiki/Graph_database) exist since 2000 but we are still using flat table models to store and edit geodata in GIS solutions. We should move on and stop wandering in NULL fields.

__Wouldn't GeoJSON be an excellent format for storing and editing deeply arborescent data?__

It has more potential than a flat table with a WKT field currently used by GeoPackage. To use the full potential of the GeoJSON object-oriented format, an appropriate editor should be added to QGIS. Here an [example of such an editor](https://github.com/josdejong/jsoneditor) by @josdejong  

One should also be able to map visuals to JSON object variables. Example: the label editor in layer properties should be able to use an expression like  `concat("name.y1491.en",' (',"name.y1491.local",')')` to obtain a _Constantinople (Κωνσταντινούπολις)_ label from this GeoJSON layer:

```{json}
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "name":{
          "current":{
            "local":"İstanbul",
            "en":"Istabul"
          },
          "y1491":{
            "local":"Κωνσταντινούπολις",
            "en":"Constantinople"
          }
        }
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          29.179687499999996,
          40.91351257612758
        ]
      }
    }
  ]
}

```

**Comment by elpaso** [comment]
Sounds interesting, if you have plans to implement this, I would recommend to create a QEP: https://github.com/qgis/QGIS-Enhancement-Proposals/issues

I doubt that this feature will be implemented quickly and the normal issues get stale and closed automatically after some time.

**Comment by aourednik** [comment]
Thank you @elpaso . I've reposted here: https://github.com/qgis/QGIS-Enhancement-Proposals/issues/233
