### ISSUE TITLE
Magnifier Doesn't Magnify but Instead Just Changes Scale

### ISSUE THREAD

**Issue by ttreker** [qgis/QGIS#45336]
### What is the bug or the crash?

Locking the scale and then changing the magnification doesn't lock the scale and then magnify the image. Instead, it just updates the scale. So, for instance, if you are trying to read street names on OSM and you want to zoom in, it fails to zoom in. Instead it appears to perform a network request for an updated image. For instance if you set the scale to 1:10000, lock it, and then magnify by 200% you get the same view as if you just selected 1:5000 scale. Very briefly, a magnified view appears but then it is replaced with a new view scaled as described.

If you install the QGIS Network Logger you can see the network requests going out as you increase the magnification.

The expectation is that there would not be any new network request, but only that the cached image be magnified.

### Steps to reproduce the issue

1. Start a new, clean project.
2. Add OpenStreetMap layer.
3. Add the QGIS Network Logger plugin
4. Click the QGIS Network Logger button. The logger appears.
5. Zoom to a city or town with some reasonably dense streets.
6. Set the scale to 1:10000
7. Click the lock scale.
8. Note the size of the street name text.
9. Click the "Clear" button in the QGIS Network Logger panel
10. Change the magnification to 200%
11. The canvas will briefly, magnify, increasing the text size, then go blank as then the Network Logger will show a request going out to update the canvas. The canvas will update and the text size will shrink again.
12. Take careful note of the extents and the sizes of objects displayed.
13. Now reset the magnification back to 100%
14. Unlock the scale.
15. Now select the 1:5000 scale.
16. Note the view is identical to the the locked 1:10000 scale at 200% magnification.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.18.3-Zürich | QGIS code revision | 735cc85be9
-- | -- | -- | --
Compiled against Qt | 5.11.3 | Running against Qt | 5.11.3
Compiled against GDAL/OGR | 2.4.0 | Running against GDAL/OGR | 2.4.0
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.27.2 | Running against SQLite | 3.27.2
Compiled against PDAL | 1.8.0 | Running against PDAL | 1.8.0 (git-version: Release)
PostgreSQL Client Version | 11.11 (Debian 11.11-0+deb10u1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.10.4
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Debian GNU/Linux 10 (buster)
Active python plugins | nominatim_locator_filter; QuickOSM; geometry_paster; quick_map_services; joinmultiplelines; profiletool; coordinates_converter; zoomview; qgisnetworklogger; latlontools; db_manager; MetaSearch; processing

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Here is how the 3.16 documentation describes how the magnifier should work:

> On the right side of the scale display, press the lockedGray button to lock the scale to use the magnifier to zoom in or out. The magnifier allows you to zoom in to a map without altering the map scale, making it easier to tweak the positions of labels and symbols accurately. The magnification level is expressed as a percentage. If the Magnifier has a level of 100%, then the current map is not magnified. Additionally, a default magnification value can be defined within Settings ► Options ► Rendering ► Rendering behavior, which is very useful for high-resolution screens to enlarge small symbols.

Clearly, the scale is not staying unaltered as is described above.

Note: Some people (myself included) have a very difficult time reading text and discerning auto-scaling detail if we can't magnify it! It can be pretty frustrating.

Thanks for your consideration of this issue. QGIS is a brilliant piece of opensource software! The efforts of the QGIS team are not taken for granted!

**Comment by gioman** [comment]
> Add OpenStreetMap layer.

@ttreker did you added vector or raster tiles? because with vector tiles magnification seems to work to me.

**Comment by ttreker** [comment]
Thanks for your response!

Just using the standard OSM XYZ tiles. It shouldn't matter. The QGIS magnifier isn't working as described in the docs and, btw, as one would expect it to work (at least as it appears to me right now).

Perusing Google, I see no online version of OSM Vector Tiles, just downloadable. Maybe I am missing something. It may be that I am just not interested in turning this into a research project of getting an OSM basemap as vector tiles. I do not have the disk space to download all of the vector tiles I would like (the path MapTiler seems to take). I am not trying to customize my basemap, just read street names, contour altitudes, peak names, and other POI names clearly. OSM vector tiles is overkill for me at this stage.

Correct me if I have missed something, but I did not write this up with the expectation that someone could give me a work around-- that is what community forums are for. I wrote it up because it appears to be a bug in QGIS and, unless I am mistaken, this is the QGIS bug tracker, not a community forum (please take this statement at face value; it isn't meant to be snarky).

If I am wrong and it is not a bug or I misunderstood and this is not the official QGIS bug tracking system, I would be happy to know that. As it stands, from my evaluation, I believe it to be a bug at this point regardless of whether there is a work-around.

It would be nice were it to be fixed but I understand there are likely other bugs being addressed by the QGIS developer team that are certain to be higher priority. It seems like it could be an easy fix, but I am not down into the guts of the code so I don't really know.

Further, I am not able to get the current version of QGIS running on Debian Buster without a build from scratch so I don't really expect a workable fix for myself any time soon even if someone were to fix this tomorrow. I turned this bug in as an albeit limited way of contributing to the QGIS effort.

**Comment by ttreker** [comment]
Thanks for the response, Giovanni. Sorry it took a while to reply.

What I meant is that it shouldn't matter according to how the magnifier is described in the doc. It may indeed matter if it is or isn't an XYZ tile layer or not as QGIS currently functions. I would go so far as to say that my expectation of a resolution would be that QGIS is fixed so that it corresponds to how the documentation describes the behavior rather than changing the doc to reflect that it only works with vector tile layers or vector layers. Further, two things of note:

1. When you lock the scale and then up the magnification, for a brief moment the screen magnifies as desired, but then it quickly disappears and is replaced by a refreshed view at a new scale (OSM XYZ tiles). This seems to imply it actually is doing the magnification as desired, but with XYZ tiles there is a bug that causes it to also see the event as a scale change so after performing the magnification it subsequently erroneously performs a scale change. (I just played with this again and determined this brief magnification behavior occurs whether the scale is locked or not. The only difference locking the scale seems to make is that you can't change the scale and if you use the zoom tool, the scale value in the drop down doesn't change. Whether the scale is locked or not, the update of the display seems to operate the same).
2. It doesn't seem at all that it would make any sense to not simply magnify what was being displayed under all circumstances always suppressing a refresh at a new scale. First, to not do this just creates a confusing interface and user frustration. Second, it is hard to imagine that doing so is a particularly complicated problem to solve. Heck, there are magnifier utilities to do this in general for most OSes as part of their accessibility options. It doesn't seem like the solution should be that complex.

I can see that it might actually require requerying the server **at the same scale** as there is likely a mapping between the returned bitmap and the resolution and extent of the display window. So to avoid pixelating, one might want to perform the last query before locking, cache the returned bitmap, and map the cached bitmap to the display window as the magnification changes. Of course any vector data overlaying would be handled natively, but none of this sounds particularly complex.

Btw, I chose OSM XYZ for this bug report because it is ubiquitous and so easily repeatable. Where this is really annoying is with the USGS WMS Topo Base Map! You can't scale finer than 1:5000 or the server will return nothing. Reading peak names and contour altitudes at this scale is extremely difficult. Not being able to magnify these maps is pretty annoying.

I will acknowledge, though, the devil is always in the details and with a system as extensive as QGIS priorities with the application of limited developer resources certainly matters.

If I could free up some time I would look into it myself, but I can't right now.

**Comment by ttreker** [comment]
Hello, Elpaso! Sorry I was unable to reply awhile back. I hope this late reply is not too much of an inconvenience or even too late :) (Happy New Year, btw). I was traveling and then got distracted with other issues. For context I used to be a GIS professional on the programming side. I haven't done that in a while and just use QGIS informally but for all sorts of things. My biggest use, though, is with outdoor adventuring, both biking and hiking. The weather turned bad and so I wasn't active on QGIS until just recently. I forgot I had even submitted this. My apologies for dropping the ball and appreciate your efforts!

It looks like there is a pull request that you wanted me to try out. The issue here is that my installation of QGIS is a binary version installed via the QGIS download instructions for Debian on the QGIS web site. Consequently, I don't have as far as I know a QGIS Git repository of which to use to test this pull request. Further, I am not sure where I would find the source files if I do have them or the best procedure to use to replace files safely.

If you would like me to test out the pull request please steer me in the correct direction to do that. I would be happy to but bear in mind that I am reticent to get too bogged down on the technical side for time constraint reasons and would prefer primarily to keep the testing to usability. Having said this, I am not adverse to putting a little effort into setting up a test environment if this is necessary. I little guidance to beeline me in that direction would be appreciated.

Thanks for your efforts!

**Comment by m-kuhn** [comment]
As a short term workaround, I was able to increase zoom (at the expense of some quality) by going to the rendering options and oversample by 0.5 
![image](https://user-images.githubusercontent.com/588407/147906282-88ecf18a-ed56-41f3-8cc8-d3949d38ac87.png)

**Comment by elpaso** [comment]
@m-kuhn maybe you could check out my (now stale) PR.

**Comment by m-kuhn** [comment]
If I understood it correctly, the approach there was dismissed?

**Comment by ttreker** [comment]
Reply to @m-kuhn: Reading the PR I think it was closed do to inactivity by a bot. I didn't see any criticism of the approach unless I missed something.

Reply to @elpaso: I am going to take from your post to @m-kuhn that you assume @m-kuhn has a build environment in which to test your PR. If it wasn't a lot of faffing around and it was something I could do quickly, I would be willing to set one up from your PR. Somehow, though, I suspect getting the environment setup properly to perform a QGIS build with your PR is going to eat some time (which I don't have right now).

I guess I am just asking if there is a way you think I might be able to contribute to testing with limited time to do so?

**Comment by m-kuhn** [comment]
I tend to agree with the comment https://github.com/qgis/QGIS/pull/45555#issuecomment-946103372 that we should reuse the API which has recently been added.

**Comment by elpaso** [comment]
@ttreker if you are on windows, every PR has an automatically built package that you can use for testing, in that particular PR you can find it here: https://github.com/qgis/QGIS/actions/runs/1355557360

**Comment by ttreker** [comment]
Thanks, @elpaso

**Comment by ttreker** [comment]
OK, well I downloaded the QGIS Portable Win64 for the pull request and tested it. It worked which is, of course, no surprise. This is exactly the way it should work and if integrated in a release, would make me very happy! I only tested it with OpenStreetMap XYZ tiles. If you want me to try anything else I would be happy to.

Of course, I am running under Linux as outlined in the opening post of this issue. If you have trouble getting tested on that platform keep me posted and I might consider setting up a build environment to test it.

Thanks for your efforts on this. Clearly this required a bit of hacking judging from a brief perusal of the patched source files.

I hope this isn't too much of a pain getting any issues with it worked out or the PR accepted. I certainly understand if there are higher priorities to attack. QGIS is an amazing piece of software with a plethora of complexity and limited developer resources so if you manage to be able to get this fix into a release the efforts won't be taken for granted.

**Comment by ttreker** [comment]
Opps! I accidentally closed this issue! Sorry!

**Comment by elpaso** [comment]
> I tend to agree with the comment [#45555 (comment)](https://github.com/qgis/QGIS/pull/45555#issuecomment-946103372) that we should reuse the API which has recently been added.

@m-kuhn On what grounds? I am very much into reusing existing APIs and I may be missing something but the magnification factor does not have anything to do with the DPIs, the DPIs are a device property.

**Comment by nirvn** [comment]
@elpaso , it kind of is linked to dpis though. Magnification is using dpi to actualize the "magnified" state, see the ratio bit https://github.com/qgis/QGIS/blob/master/src/core/qgsmapsettings.cpp#L63
