### ISSUE TITLE
geometry generator: QGIS crashes using buffer on difference

### ISSUE THREAD

**Issue by Alissy1** [qgis/QGIS#45342]
### What is the bug or the crash?

Following up the bugreport #45341:

When using the following code to dissolve the clipped polygon features only optically using the geometry generator, QGIS crashes everytime.
```
buffer(
	collect(
		difference( -- Outside Covering Layer 
			$geometry,
			buffer(
				aggregate( 'layer2', 'collect', $geometry),
				0
			)
		)
	),0
)
```

Using the buffer on "normal" (not already processed) features works just fine.
```
buffer(
	collect(
		$geometry
	),0
)
```

Using the difference without buffer and collect also works just like I describes in bugreport #45341.

### Steps to reproduce the issue

1. Open a new QGIS project
2. Load [layer1 and layer2](https://github.com/qgis/QGIS/files/7258945/bugreport_geodata.zip)
3. Style layer1 using the geometry generator and the following code:
```
buffer(
	collect(
		difference(
			$geometry,
			buffer(
				aggregate( 'layer2', 'collect', $geometry),
				0
			)
		)
	),0
)
```
4. Do NOT refresh the map canvas an see how the polygons seem to be dissolved
5. Refresh the map canvas (e.g. pan left/right or zoom in/out)
6. QGIS crashes!

### Versions

QGIS version
3.16.4-Hannover

QGIS code revision
654e76b3cb

Compiled against Qt
5.11.2

Running against Qt
5.11.2

Compiled against GDAL/OGR
3.1.4

Running against GDAL/OGR
3.1.4

Compiled against GEOS
3.8.1-CAPI-1.13.3

Running against GEOS
3.8.1-CAPI-1.13.3

Compiled against SQLite
3.29.0

Running against SQLite
3.29.0

PostgreSQL Client Version
11.5

SpatiaLite Version
4.3.0

QWT Version
6.1.3

QScintilla2 Version
2.10.8

Compiled against PROJ
6.3.2

Running against PROJ
Rel. 6.3.2, May 1st, 2020

OS Version
Windows 10 (10.0)

Active python plugins
albeda_3; 
alkisplugin; 
er_finden; 
er_menu_entries; 
qgis_2_doc; 
qpg_login_manager_3; 
qpg_privilege_manager; 
searchengine; 
simple_filter; 
std_layer_loader; 
street_smart_viewer; 
xplanung; 
DataDrivenInputMask; 
db-style-manager; 
pickLayer; 
qgis2web; 
QuickOSM; 
redLayer; 
db_manager; 
MetaSearch; 
processing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
> QGIS crashes!

@Alissy1 cannot confirm here. Please update to the latest point release (3.16.4 is old) and/or test on 3.20.
