### ISSUE TITLE
Tiles in 3D view keeps on reloading, never finishes when too many visible

### ISSUE THREAD

**Issue by PeterBrodersen** [qgis/QGIS#45353]
### What is the bug or the crash?

When viewing a huge point cloud layer in 3D the render keeps loading and discarding tiles.

A video recording of the issue is available here:
[![YouTube Video](https://img.youtube.com/vi/vpmHa-7Ajlk/0.jpg)](https://www.youtube.com/watch?v=vpmHa-7Ajlk)
https://www.youtube.com/watch?v=vpmHa-7Ajlk

Note the tile count at the top right. At some point it goes back and forth without ever loading everything in.

This also makes the generation of a QGIS animation with such an angle during the interpolation getting stuck and never getting past that frame. There is no error message, only the animation generation progress bar that never advances at a given point.

### Steps to reproduce the issue

1. Download a huge data set. I used a LAZ file of [Amsterdam](https://download.pdok.nl/rws/ahn3/v1_0/laz/C_25GN1.LAZ) (2.5 GiB, which took a couple of hours to generate the EPT folder)
2. View the data set in 3D (View -> New 3D Map View)
3. Tilt the layer down to have many tiles in view

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.20.3-Odense | QGIS code revision | 495fbaec
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.1
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins | geosearch_dkJSONEater-masterKortforsyningenLAStoolsMagneticDeclinationplugin_reloaderdb_managerMetaSearchprocessingtimemanager

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by PeterBrodersen** [comment]
The issue is also present in 3.22.0.

QGIS version | 3.22.0-Białowieża | QGIS code revision | d9022691f1
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.10.0-CAPI-1.16.0
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
geosearch_dk | 1.2.0
JSONEater-master | 0.3
Kortforsyningen | 2.9
LAStools | 1.4
MagneticDeclination | 2.3.1
plugin_reloader | 0.8.2
sparqlunicorn | 0.12.2
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.5
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>

**Comment by PeterBrodersen** [comment]
The pull request #47168 fixed this issue. It works fine in QGIS 3.26.

**Comment by alexanderswerdlow** [comment]
Having this issue on 3.26.1-Buenos Aires.
