### ISSUE TITLE
Cannot find py3_env.bat file and qt5_env.bat file When compiling and building QGIS from source code.

### ISSUE THREAD

**Issue by kuazhangxiaoai** [qgis/QGIS#45355]
### What is the bug or the crash?

Cannot find py3_env.bat file and qt5_env.bat file when runing msvc-env.bat.
I have download qgis_dev_deps from osgeo4w tools.
There is neither py3_env.bat and qt5_env.bat file in my OSGEO4W_ROOT path, and both of them are applied for create suitable environment for QGIS compiling. 
![image](https://user-images.githubusercontent.com/54108453/135619297-28e241b3-0612-4914-970f-049715c712e3.png)

### Steps to reproduce the issue

Cannot find py3_env.bat file and qt5_env.bat file when runing msvc-env.bat.
error:
![image](https://user-images.githubusercontent.com/54108453/135620100-273d318a-0961-4b02-ba92-d5e87f5087c4.png)

### Versions

3.10 

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by roya0045** [comment]
This is not a qgis issue but a build issue.

**Comment by kuazhangxiaoai** [comment]
> This is not a qgis issue but a build issue.

How can I ask a build issue?

**Comment by gioman** [comment]
> How can I ask a build issue?

@kuazhangxiaoai in the developers mailing list.
