### ISSUE TITLE
can not create ShapeFile

### ISSUE THREAD

**Issue by bluemarina** [qgis/QGIS#45359]
### Feature description

i gonna create new shapefile and last step click "OK" but program show  window about "QGIS unexpectedly ended" instead and other details. Honestly, English not my mother tongue it's a Greek to me! to understand about notification infor, Can anyone hand me solve pls.

### Additional context

<img width="960" alt="2021-10-01" src="https://user-images.githubusercontent.com/91743746/135642203-91e34ebb-1072-44a5-99d1-8d782f9d1908.png">

**Comment by gioman** [comment]
> i gonna create new shapefile and last step click "OK"

@bluemarina what are the steps you are following until there? what QGIS version are you using? have you tried with a new QGIS profile (settings > user profiles > new profile)?

**Comment by bluemarina** [comment]
<img width="960" alt="2021-10-01 (1)" src="https://user-images.githubusercontent.com/91743746/135644297-703ca275-b725-4ac0-9690-c7c882ee738f.png">
<img width="960" alt="2021-10-01 (2)" src="https://user-images.githubusercontent.com/91743746/135644308-2627b319-7af6-427f-8b94-554423a8328d.png">  and when i click OK  it show about issue that i query and if i click to close these window it will close program too.
/ My QGIS version is QGIS 3.16 Hannover / I have no idea about new profile i just do assignment following my prof. teaching video so i still not used to other tools.

**Comment by gioman** [comment]
> and when i click OK it show about issue that i query and if i click to close these window it will close program too.

@bluemarina so is seems there is something very wrong with your installation, as following the above steps does not crashes QGIS.



>  I have no idea about new profile i

I wrote it before, follow the menu

settings > user profiles > new profile

create a new profile (choose  a name for it) and in the new QGIS window that will open try again create the shapefile.

**Comment by uclaros** [comment]
Try on a folder that is *not* in OneDrive

**Comment by bluemarina** [comment]
> settings > user profiles > new profile
> 
> create a new profile (choose a name for it) and in the new QGIS window that will open try again create the shapefile.
@gioman It works! thanks a million.^v^
