### ISSUE TITLE
The certificate https://version.qgis.org/version.txt not found

### ISSUE THREAD

**Issue by NLD-ITService** [qgis/QGIS#45377]
### What is the bug or the crash?

When running QGIS Desktop 3.16.0 a message appears "SSL error: https://version.qgis.org/version.txt The certificate of the issuer of a locally found certificate could not be found". 

If ignored, the application works.

![grafik](https://user-images.githubusercontent.com/91880838/135858746-b6ae22f8-cf85-48a2-8ebd-7b5dd071cac7.png)

### Steps to reproduce the issue

Running  QGIS Desktop 3.16.0

### Versions

QGIS Desktop 3.16.0

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

I just wanted to ask. Is it just about renewing the website's security certificate? And that's why the message won't appear again soon?
Or is there a reason for concern since it would already be a security issue?

**Comment by gioman** [comment]
@NLD-ITService duplicate of https://github.com/qgis/QGIS/issues/45011 ?




> QGIS Desktop 3.16.0

this is very old, reports/issues must be tested on current versions, as you stated by checking the checkbox " I'm running a supported QGIS version according to the roadmap.".

**Comment by NLD-ITService** [comment]
First of all, thank you for your reaction. The same message also appears on version 3.16.11.

**Comment by NLD-ITService** [comment]
But this version should work.When the system tries to access the certificate, I assume the certificate should be there.

**Comment by NLD-ITService** [comment]
Thanks in advance

**Comment by pathmapper** [comment]
@NLD-ITService assuming you are on Windows, could you please check that you have all available Windows Updates installed?

**Comment by NLD-ITService** [comment]
@pathmapper 
We work with Windows 10 and use a WSUS in our Windows environment. All current Windows cumulative uptades are installed.

**Comment by NLD-ITService** [comment]
@gioman 
Dear Giovanni,

I specifically installed version 3.16.11 on a test PC. At least when starting, I manage to see.
"https://version.qgis.org/version.txt
Cannot get local issuer certificate: The certificate of the issuer of a locally found certificate could not be found."

Im Browser bekomme ich auf  "https://version.qgis.org/version.txt". 

![grafik](https://user-images.githubusercontent.com/91880838/136006606-4a3263f2-de69-4f1e-9ef3-f11c19e514a9.png)

Are you suggesting that 3.16 will remain "unsafe". So without a security certificate?

**Comment by gioman** [comment]
> Are you suggesting that 3.16 will remain "unsafe". So without a security certificate?

@NLD-ITService I'm not suggesting or imply anything, I'm just saying that bug reports must be done after having tested with the current supported releases.

**Comment by NLD-ITService** [comment]
@gioman 
Thanks for the answer.
Good. I tested with the "current" version 3.16.11. The message exists.

I ask you to help us to continue to work securely with QGIS.

**Comment by gioman** [comment]
> I ask you to help us to continue to work securely with QGIS.

@NLD-ITService this has already been reported (and fixed) here https://github.com/qgis/QGIS/issues/45011

Is to be seen why you still get the message.

**Comment by gioman** [comment]
Seems a different issue https://github.com/qgis/QGIS/issues/45011#issuecomment-934299793 thanks @agiudiceandrea

**Comment by NLD-ITService** [comment]
![grafik](https://user-images.githubusercontent.com/91880838/136029693-baab614c-41e2-46be-aa54-ec83c5381afe.png)
![grafik](https://user-images.githubusercontent.com/91880838/136029822-cf95b65d-330f-46dc-9cc4-c3af2a316840.png)
I have just installed and run version 3.20.3 on a PC.
The problem is the same - both certificates cannot be found.
https://version.qgis.org/
and https://version.qgis.org/.

So the problem is version regardless.

**Comment by andreasneumann** [comment]
This must be a local issue (some mal-functioning ssl certificate cache or similar). I just checked with multiple providers and QGIS / browsers. The certificates are fine. They expire next on November 9 2021 for https://feed.qgis.org/ and December 9 for https://version.qgis.org/ - the relatively short expiration dates are normal with Let's Encrypt. They are renewed quite often.

**Comment by agiudiceandrea** [comment]
The issue doesn't occur on my Windows 10 Home 1903 64 bit using QGIS 3.16.11 (from both OSGeo4W v1 and v2 repository) and QGIS 3.20.3.

**Comment by andreasneumann** [comment]
@NLD-ITService - can you please check what you get, when you open the certificate of https://version.qgis.org/version.txt in your web browser?

Do you get something like this: ?

**Comment by NLD-ITService** [comment]
@andreasneumann
Browser shows that the https://version.qgis.org certificate is valid until December 9th, 2021.
![grafik](https://user-images.githubusercontent.com/91880838/136053572-82276992-d50d-4d2b-8044-e41d2a2200e1.png)

https://feed.qgis.org/
![grafik](https://user-images.githubusercontent.com/91880838/136053872-b8c6a78b-c716-4103-a826-de6bc9db2257.png)
![grafik](https://user-images.githubusercontent.com/91880838/136053930-7af3792f-d5b2-4302-bc79-b803f047d216.png)
![grafik](https://user-images.githubusercontent.com/91880838/136053998-cc02e953-862c-4ec0-af72-24cbfc461278.png)

**Comment by agiudiceandrea** [comment]
Hi @andreasneumann, the issue is not in the validity of the version.qgis.org certificate itself, but it's due the fact that the root or intermediate digital certificate used to sign the version.qgis.org certificate seems to be missing in the local digital certificate file used by the user system.

**Comment by andreasneumann** [comment]
> Hi @andreasneumann, the issue is not in the validity of the version.qgis.org certificate itself, but it's due the fact that the root or intermediate digital certificate used to sign the version.qgis.org certificate seems to be missing in the local digital certificate file used by the user system.

You mean that the Windows system used in this installation doesn't know about the Let's Encrypt root certificate?

If that is the case, then there is nothing that QGIS can do about it, I think. Then the Windows would have to be upgraded.

@NLD-ITService  - for you the error message indicates that something "fishy" goes on with the communication between QGIS client and the QGIS servers. It doesn't harm your data or so. You are then just communicating with the servers unencrypted (like http and not https). And if something really serious would be going on (e.g. some hack on the QGIS infrastructure) you probably wouldn't notice it, because you are used to click away this warning ...

**Comment by andreasneumann** [comment]
@NLD-ITService - apparentyl, web browser run their own OS independent certification system, but QGIS is relying on the one provided by the operating system. This is explains, why the certificates are ok in your browser (screenshots above).

**Comment by pathmapper** [comment]
https://www.techradar.com/news/slack-down-top-websites-see-outages-as-lets-encrypts-ca-certificate-expires

> The solution is for servers to move to newer certificates (which have been available from Let's Encrypt for some time now) and for clients to get updates such that they trust newer certificates.

**Comment by alexbruy** [comment]
As I understand this is not directly a QGIS issue. Can we close this?
