### ISSUE TITLE
QGIS crashing when runing a loop to perfom select by location with PyQGIS

### ISSUE THREAD

**Issue by mirosaide** [qgis/QGIS#45371]
### What is the bug or the crash?

I have written a script to divide United States into a grid of 200 km, then in each grid will contain a certain number of mobile towers with (lat and long). The script must then select each grid and perform select by location and output a shapefile with the assigned id. When I run this for one specif ID, let's (id ==1) the codes does it well, but when I run it to loop for all the grid I get a crash message.

The stack trace message is:
```
Stack Trace


QMap::value qmap.h:656
QgsProcessingAlgorithm::checkParameterValues qgsprocessingalgorithm.cpp:102
meth_QgsProcessingAlgorithm_checkParameterValues sip_corepart4.cpp:93536
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyEval_EvalCodeEx :
PyEval_EvalCode :
PyArena_Free :
PyRun_StringFlags :
PyImport_Import :
PyImport_Import :
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyImport_Import :
PyImport_Import :
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:475
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:475
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1638
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.18.2-Z�rich
QGIS code revision: 515138c171
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

```
I would like to hear your thoughts.
Find the code bellow.

```
from qgis.core import QgsVectorLayer, QgsProject

project = QgsProject.instance()

project.removeAllMapLayers()


countriesPath = "D:/GIS_T/scripting_qgis/ne_10m_admin_0_countries.shp"

usTowersPath = "D:/GIS_T/scripting_qgis/us_towers.shp"

countries = QgsVectorLayer(countriesPath, 'World countries', 'ogr')

us_towers = QgsVectorLayer(usTowersPath, 'US Cell Towers', 'ogr')

currentCellTowerFields = QgsFields()
currentCellTowerFields.append(QgsField("tower_id", QVariant.Int))
currentCellTowerFields.append( QgsField("cell_id", QVariant.Int))
currentCellTowerFields.append(QgsField("cell_centroid_lon", QVariant.Double))
currentCellTowerFields.append(QgsField("cell_centroid_lat", QVariant.Double))
currentCellTowerFields.append(QgsField("tower_lon", QVariant.Double))
currentCellTowerFields.append(QgsField("tower_lat", QVariant.Double))
currentCellTowerFields.append(QgsField("radio", QVariant.String))
currentCellTowerFields.append(QgsField("tower_to_cell_centroid_dist_km", QVariant.Double))

crs = QgsProject.instance().crs()
transform_context = QgsProject.instance().transformContext()
save_options = QgsVectorFileWriter.SaveVectorOptions()
save_options.driverName = "ESRI Shapefile"
save_options.fileEncoding = "UTF-8"


project.addMapLayer(countries)

usLayer = QgsVectorLayer("Polygon", "The US", "memory")
usLayerProvider = usLayer.dataProvider()

countriesLayer = project.mapLayersByName("World countries")[0]

countriesLayer.selectByExpression('"SOVEREIGNT" = \'United States of America\'')


us_features = countriesLayer.getSelectedFeatures()
for feature in us_features:
    usLayerProvider.addFeature(feature)

usLayerProvider.updateExtents()

countriesLayer.removeSelection()
project.removeMapLayer(countries)


#coordenadas do poligno de corte
splitPolygon = QgsVectorLayer("Polygon", "US Mainland Split Polygon", "memory")
splitPolygonProvider = splitPolygon.dataProvider()
splitPolygonFeature = QgsFeature()

#coordenadas tiradas manualmente
splitPolygonFeature.setGeometry(QgsGeometry.fromPolygonXY([[
QgsPointXY(-127.5,52.4),
QgsPointXY(-127.5,14.0), 
QgsPointXY((-127.5 - 60.9) / 2,14.0),
QgsPointXY(-60.9,(52.4 + 14.0) / 2),
QgsPointXY(-60.9,52.4)
]]))

splitPolygonProvider.addFeature(splitPolygonFeature)
splitPolygon.updateExtents()

project.addMapLayer(usLayer)

to_be_clipped = project.mapLayersByName('The US')[0]
project.addMapLayer(splitPolygon)

#execusao do clip
clip_mask = project.mapLayersByName('US Mainland Split Polygon')[0]

main_land_us = processing.run("native:clip",{
'INPUT': to_be_clipped,
'OVERLAY': clip_mask,
'OUTPUT': 'memory:'
})

project.addMapLayer(main_land_us['OUTPUT'])
project.mapLayersByName('output')[0].setName('US Mainland')

project.removeMapLayer(usLayer)
project.removeMapLayer(splitPolygon)

iface.zoomFull()

#adicionamos as torres
project.addMapLayer(us_towers)



to_be_extracted = us_towers #project.mapLayersByName('US Cell Towers')[0]
extract_mask = project.mapLayersByName('US Mainland')[0]
mainLandTowers = processing.run("native:extractbylocation", \
{'INPUT': to_be_extracted,'PREDICATE': 6, 'INTERSECT': extract_mask, \
'OUTPUT': 'memory:'})

project.addMapLayer(mainLandTowers['OUTPUT'])
project.mapLayersByName('output')[0].setName('US Mainland Cell Towers')

#criamos os grids, com as suas dimensoes
us_mainland = project.mapLayersByName("US Mainland")[0]
createdGrid = processing.run("native:creategrid",{
'TYPE': 2,
'EXTENT': us_mainland.id(),
'HSPACING': 1.802,
'VSPACING': 1.802,
'HOVERLAY': 0,
'VOVERLAY': 0,
'CRS': 'EPSG:4326',
'OUTPUT': 'memory:'
})

project.addMapLayer(createdGrid['OUTPUT'])
project.mapLayersByName('output')[0].setName('Grid cells')

#A camada da grelha, composta por celulas
cells = project.mapLayersByName('Grid cells')[0]


#camada das torres
allCellTowers = QgsVectorLayer("Point", \
    "All cell towers", \
    "memory")
#Adicionamos os campos da camada   
allCellTowersProvider = allCellTowers.dataProvider()
allCellTowersProvider.addAttributes([\
    QgsField("tower_id", QVariant.Int),\
    QgsField("cell_id", QVariant.Int),\
    QgsField("cell_centroid_lon", QVariant.Double),\
    QgsField("cell_centroid_lat", QVariant.Double),\
    QgsField("tower_lon", QVariant.Double),\
    QgsField("tower_lat", QVariant.Double),\
    QgsField("radio", QVariant.String),\
    QgsField("tower_to_cell_centroid_dist_km", QVariant.Double)])
allCellTowers.updateFields()

us_mainland_towers = project.mapLayersByName('US Mainland Cell Towers')[0]
to_be_extracted = us_mainland_towers

for i in range(0,3):


    for cell in cells.getFeatures():
        #if (cell.attribute('id') == 1):
        if (cell.attribute('id') == i):
            
            print('ID: ', cell.attribute('id'))
            print('Area: ', cell.geometry().area())
            print('Perimeter: ', cell.geometry().length())
            print('Centroid: ', cell.geometry().centroid())

            cid = str(cell.attribute('id'))
            cell_centroid = cell.geometry().centroid().asPoint()
            cell_centroid_lon = cell_centroid.x()
            cell_centroid_lat = cell_centroid.y()
            #Celula temporaria que usamos para extrair as torres que estao na grelha actual
            tempCell = QgsVectorLayer("Polygon", \
            "Cell " + cid, \
            "memory")
            tempCellProvider = tempCell.dataProvider()
            tempCellProvider.addFeature(cell)
            tempCellProvider.updateExtents()
            project.addMapLayer(tempCell)
            #Celula temporaria dos pontos que estao dentro da grelha temporaria
            tempCellTowers = QgsVectorLayer("Point", \
            "Cell " + cid + " towers", \
            "memory")
            tempCellTowersProvider = tempCellTowers.dataProvider()
            tempCellTowersProvider.addAttributes([\
            QgsField("tower_id", QVariant.Int),\
            QgsField("cell_id", QVariant.Int),\
            QgsField("cell_centroid_lon", QVariant.Double),\
            QgsField("cell_centroid_lat", QVariant.Double),\
            QgsField("tower_lon", QVariant.Double),\
            QgsField("tower_lat", QVariant.Double),\
            QgsField("radio", QVariant.String),\
            QgsField("tower_to_cell_centroid_dist_km", QVariant.Double)])
            tempCellTowers.updateFields()
            
            d = QgsDistanceArea()
            d.setEllipsoid('WGS84')
            #Extracao das torres da celula temporaria actual
            #us_mainland_towers = project.mapLayersByName('US Mainland Cell Towers')[0]
            #to_be_extracted = us_mainland_towers
            extract_mask = tempCell
            extractedTempCellTowers = processing.run("native:extractbylocation", \
            {'INPUT': to_be_extracted,'PREDICATE': 6, \
            'INTERSECT': extract_mask, \
            'OUTPUT': 'memory:'})
            
            project.addMapLayer(extractedTempCellTowers['OUTPUT'])
            extractedTempCellTowers = project.mapLayersByName('output')[0]
            #Contar o nr das torres que foram encontradas na celula temporaria
            count = extractedTempCellTowers.featureCount()
            if (count > 0):
                allTowersCount = allCellTowers.featureCount()
                for ect in extractedTempCellTowers.getFeatures():
                    allTowersCount += 1
                    radio = ect['radio']
                    ect.setAttribute(0, allTowersCount)
                    ect.setAttribute(1, int(cid))
                    ect.setAttribute(2, cell_centroid_lon)
                    ect.setAttribute(3, cell_centroid_lat)
                    towerLoc = ect.geometry().asPoint()
                    ect.setAttribute(4, towerLoc.x())
                    ect.setAttribute(5, towerLoc.y())
                    #print(ect['radio'])
                    #radio = ect.attribute('radio')
                    ect.setAttribute(6, radio)
                    ect.setAttribute(7, d.convertLengthMeasurement(\
                    d.measureLine(towerLoc, cell_centroid), \
                    QgsUnitTypes.DistanceKilometers))
                    tempCellTowersProvider.addFeature(ect)
                    
                tempCellTowersProvider.updateExtents()
                
                if(count == 1):
                    print("Grid Cell", cid, "has", count, "tower")
                else:
                    print("Grid Cell", cid, "has", count, "towers")
               
                writer = QgsVectorFileWriter.create("D:/GIS_T/scripting_qgis/Ids/Cell " + cid + " Towers.shp",currentCellTowerFields,\
                    QgsWkbTypes.Point,crs,transform_context,save_options)

                if writer.hasError() != QgsVectorFileWriter.NoError:
                    print("Error when creating shapefile: ", writer.errorMessage())

                 
                
                #project.addMapLayer(tempCellTowers)
                for tower in tempCellTowers.getFeatures():
                    writer.addFeature(tower)
                    allCellTowersProvider.addFeature(tower)
                allCellTowersProvider.updateExtents()
                del writer
                project.addMapLayer(allCellTowers)
                #iface.showAttributeTable(allCellTowers)
            
            
            else:
                print("Grid Cell ", cid, "has no tower")
                
            project.removeMapLayer(project.mapLayersByName('output')[0])
            project.removeMapLayer(project.mapLayersByName('US Cell Towers')[0])
            project.removeMapLayer(project.mapLayersByName('US Mainland Cell Towers')[0])
            project.removeMapLayer(project.mapLayersByName('Cell ' + cid)[0])
    
```

### Steps to reproduce the issue

[Uploading ne_10m_admin_0_countries.zip…]()

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.18.2-Zürich | QGIS code revision | 515138c171
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | db_manager; MetaSearch; processing

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

The cell towers can be downloaded via this link: https://drive.google.com/file/d/1ZCTKTWZ745_RQPhFA75k1OfExAXeWcT4/view?usp=sharing

**Comment by PeterPetrik** [comment]
HI @mirosaide , thank you for reporting the QGIS crash. As the crash is within your custom Python script, it would be helpful to supply the minimal working example that reproduces the problem. So please try to cut your script to the smallest possible to show the problem (e.g. just have one algorithm that runs and crashes or so).

**Comment by mirosaide** [comment]
Hi peter,

Not sure if I understood what you meant, but the script starts to fail from
the fooling lines:

    for cell in cells.getFeatures():

        if (cell.attribute('id') == i):

            print('ID: ', cell.attribute('id'))
            print('Area: ', cell.geometry().area())
            print('Perimeter: ', cell.geometry().length())
            print('Centroid: ', cell.geometry().centroid())

            cid = str(cell.attribute('id'))
            cell_centroid = cell.geometry().centroid().asPoint()
            cell_centroid_lon = cell_centroid.x()
            cell_centroid_lat = cell_centroid.y()
            #Celula temporaria que usamos para extrair as torres que estao
na grelha actual
            tempCell = QgsVectorLayer("Polygon", \
            "Cell " + cid, \
            "memory")
            tempCellProvider = tempCell.dataProvider()
            tempCellProvider.addFeature(cell)
            tempCellProvider.updateExtents()
            project.addMapLayer(tempCell)
            #Celula temporaria dos pontos que estao dentro da grelha
temporaria
            tempCellTowers = QgsVectorLayer("Point", \
            "Cell " + cid + " towers", \
            "memory")
            tempCellTowersProvider = tempCellTowers.dataProvider()
            tempCellTowersProvider.addAttributes([\
            QgsField("tower_id", QVariant.Int),\
            QgsField("cell_id", QVariant.Int),\
            QgsField("cell_centroid_lon", QVariant.Double),\
            QgsField("cell_centroid_lat", QVariant.Double),\
            QgsField("tower_lon", QVariant.Double),\
            QgsField("tower_lat", QVariant.Double),\
            QgsField("radio", QVariant.String),\
            QgsField("tower_to_cell_centroid_dist_km", QVariant.Double)])
            tempCellTowers.updateFields()

            d = QgsDistanceArea()
            d.setEllipsoid('WGS84')
            #Extracao das torres da celula temporaria actual
            #us_mainland_towers = project.mapLayersByName('US Mainland Cell
Towers')[0]
            #to_be_extracted = us_mainland_towers
            extract_mask = tempCell
            extractedTempCellTowers =
processing.run("native:extractbylocation", \
            {'INPUT': to_be_extracted,'PREDICATE': 6, \
            'INTERSECT': extract_mask, \
            'OUTPUT': 'memory:'})

            project.addMapLayer(extractedTempCellTowers['OUTPUT'])
            extractedTempCellTowers = project.mapLayersByName('output')[0]
            #Contar o nr das torres que foram encontradas na celula
temporaria
            count = extractedTempCellTowers.featureCount()
            if (count > 0):
                allTowersCount = allCellTowers.featureCount()
                for ect in extractedTempCellTowers.getFeatures():
                    allTowersCount += 1
                    radio = ect['radio']
                    ect.setAttribute(0, allTowersCount)
                    ect.setAttribute(1, int(cid))
                    ect.setAttribute(2, cell_centroid_lon)
                    ect.setAttribute(3, cell_centroid_lat)
                    towerLoc = ect.geometry().asPoint()
                    ect.setAttribute(4, towerLoc.x())
                    ect.setAttribute(5, towerLoc.y())
                    #print(ect['radio'])
                    #radio = ect.attribute('radio')
                    ect.setAttribute(6, radio)
                    ect.setAttribute(7, d.convertLengthMeasurement(\
                    d.measureLine(towerLoc, cell_centroid), \
                    QgsUnitTypes.DistanceKilometers))
                    tempCellTowersProvider.addFeature(ect)

                tempCellTowersProvider.updateExtents()

                if(count == 1):
                    print("Grid Cell", cid, "has", count, "tower")
                else:
                    print("Grid Cell", cid, "has", count, "towers")


                writer =
QgsVectorFileWriter.create("D:/GIS_T/scripting_qgis/Ids/Cell " + cid + "
Towers.shp",currentCellTowerFields,\
                QgsWkbTypes.Point,crs,transform_context,save_options)

                if writer.hasError() != QgsVectorFileWriter.NoError:
                    print("Error when creating shapefile: ",
writer.errorMessage())



                    #project.addMapLayer(tempCellTowers)
                    for tower in tempCellTowers.getFeatures():
                        writer.addFeature(tower)
                        allCellTowersProvider.addFeature(tower)
                    allCellTowersProvider.updateExtents()
                    del writer
                    project.addMapLayer(allCellTowers)
                    #iface.showAttributeTable(allCellTowers)

project.removeMapLayer(project.mapLayersByName('output')[0])
                    project.removeMapLayer(project.mapLayersByName('US Cell
Towers')[0])
                    project.removeMapLayer(project.mapLayersByName('US
Mainland Cell Towers')[0])
                    project.removeMapLayer(project.mapLayersByName('Cell '
+ cid)[0])

            else:
                print("Grid Cell ", cid, "has no tower")




*Ramiro Caisse Saide*
*MPhil Research Student*
Department of Physics
University of Mauritius
Contact Number: +258 845672884
Email: ***@***.***




Peter Petrik ***@***.***> escreveu no dia segunda, 4/10/2021
à(s) 22:14:

**Comment by mirosaide** [comment]
Never mind the previous email,

the problem is only here:

us_mainland_towers = project.mapLayersByName('US Mainland Cell Towers')[0]
to_be_extracted = us_mainland_towers

def selecttowers(grid_number):

    for cell in cells.getFeatures():

        if (cell.attribute('id') == grid_number):

            print('ID: ', cell.attribute('id'))
            print('Area: ', cell.geometry().area())
            print('Perimeter: ', cell.geometry().length())
            print('Centroid: ', cell.geometry().centroid())
            cid = str(cell.attribute('id'))
            cell_centroid = cell.geometry().centroid().asPoint()
            cell_centroid_lon = cell_centroid.x()
            cell_centroid_lat = cell_centroid.y()
            #Celula temporaria que usamos para extrair as torres que estao
na grelha actual
            tempCell = QgsVectorLayer("Polygon", \
            "Cell " + cid, \
            "memory")
            tempCellProvider = tempCell.dataProvider()
            tempCellProvider.addFeature(cell)
            tempCellProvider.updateExtents()
            project.addMapLayer(tempCell)
            #Celula temporaria dos pontos que estao dentro da grelha
temporaria
            tempCellTowers = QgsVectorLayer("Point", \
            "Cell " + cid + " towers", \
            "memory")
            tempCellTowersProvider = tempCellTowers.dataProvider()
            tempCellTowersProvider.addAttributes([\
            QgsField("tower_id", QVariant.Int),\
            QgsField("cell_id", QVariant.Int),\
            QgsField("cell_centroid_lon", QVariant.Double),\
            QgsField("cell_centroid_lat", QVariant.Double),\
            QgsField("tower_lon", QVariant.Double),\
            QgsField("tower_lat", QVariant.Double),\
            QgsField("radio", QVariant.String),\
            QgsField("tower_to_cell_centroid_dist_km", QVariant.Double)])
            tempCellTowers.updateFields()

            d = QgsDistanceArea()
            d.setEllipsoid('WGS84')

            #Extracao das torres da celula temporaria actual
            #us_mainland_towers = project.mapLayersByName('US Mainland Cell
Towers')[0]
            #to_be_extracted = us_mainland_towers
            extract_mask = tempCell
            extractedTempCellTowers =
processing.run("native:extractbylocation", \
            {'INPUT': to_be_extracted,'PREDICATE': 6, \
            'INTERSECT': extract_mask, \
            'OUTPUT': 'memory:'})

            project.addMapLayer(extractedTempCellTowers['OUTPUT'])
            extractedTempCellTowers = project.mapLayersByName('output')[0]
            #Contar o nr das torres que foram encontradas na celula
temporaria
            count = extractedTempCellTowers.featureCount()
            #count.updateExtents()
            print('this grid has: ', count, 'towers')

for i in range(0,5):
    selecttowers(i)
*Ramiro Caisse Saide*
*MPhil Research Student*
Department of Physics
University of Mauritius
Contact Number: +258 845672884
Email: ***@***.***




Miro Saide ***@***.***> escreveu no dia segunda, 4/10/2021 à(s)
19:52:

**Comment by PeterPetrik** [comment]
@mirosaide This is most likely not a bug in the pyqgis/QGIS but a problem with your extension. 

I suggest you to install https://plugins.qgis.org/plugins/firstaid/ add breakpoint to your script at begining and step in debugger one line by one line to see exactly where the crash happens (line + inputs). I have strong suspition it is just that you pass non-existent layer pointer or so to processing algorithm. 

Afterwards, you should create a minimal example reproducing the crash (ideally let say 10 lines of code), so QGIS devs can easily simulate the problem.
