### ISSUE TITLE
Crash while moving labels on a polygon shape layer

### ISSUE THREAD

**Issue by wyahnke** [qgis/QGIS#45387]
## User Feedback

I was moving a label on a polygon layer used for building footprints.

## Report Details

**Crash ID**: [528c18d84814c91aad5d1de97df6e9ba0ccadaf2](https://github.com/qgis/QGIS/search?q=528c18d84814c91aad5d1de97df6e9ba0ccadaf2&type=Issues)

**Stack Trace**
<pre>
QgsGeometry::closestVertex :
QgsPointLocator::verticesInRect :
SpatialIndex::TPRTree::Data::Data :
SpatialIndex::TPRTree::Data::Data :
QgsPointLocator::nearestVertex :
QgsSnappingUtils::~QgsSnappingUtils :
QgsSnappingUtils::snapToMap :
QgsMapMouseEvent::snapPoint :
QgsMapToolAdvancedDigitizing::canvasMoveEvent :
QgsMapCanvas::mouseMoveEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.20.1-Odense
QGIS code revision: 1c3c5cd6
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.1
Running against GDAL: 3.3.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

### Steps to reproduce the issue

Click move label button
Select label to move
Click to place label - program crashed here

### Versions

QGIS version
3.20.1-Odense
QGIS code revision
1c3c5cd6
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.1
PROJ version
8.1.0
EPSG Registry database version
v10.018 (2021-04-02)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
MetaSearch
processing

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
> I was moving a label on a polygon layer used for building footprints.

@wyahnke can you replicate in a consistent way?

**Comment by wyahnke** [comment]
@gioman No, I re-opened the program and performed the same actions and it did not crash.
