### ISSUE TITLE
OGR driver can't open GeoJSON from URL in QGIS anymore

### ISSUE THREAD

**Issue by pathmapper** [qgis/QGIS#45409]
### What is the bug or the crash?

OGR driver can't open GeoJSON from URL anymore. This used to work in QGIS 3.18. Seems related to the update of the GDAL/OGR version to 3.3.1 .

### Steps to reproduce the issue

Execute the following code via the Python console in QGIS:

```
url = "https://ogc-api.nrw.de/lika/v1/collections/gebaeude_bauwerk/items?f=json&limit=5000&offset=0&funktion=Carport&gmdschl=05166032"
ogr_layer = QgsVectorLayer(url, "OGC API OGR Driver", "OGR")
```

Results in:

`WARNING    Cannot open https://ogc-api.nrw.de/lika/v1/collections/gebaeude_bauwerk/items?f=json&limit=5000&offset=0&funktion=Carport&gmdschl=05166032.(Driver COUCHDB is considered for removal in GDAL 3.5. You are invited to convert any dataset in that format to another more common one .If you need this driver in future GDAL versions, create a ticket at https://github.com/OSGeo/gdal (look first for an existing one first) to explain how critical it is for you (but the GDAL project may still remove it), and to enable it now, set the GDAL_ENABLE_DEPRECATED_DRIVER_COUCHDB configuration option / environment variable to YES)`

![grafik](https://user-images.githubusercontent.com/20856381/136034919-0c394e48-94a2-4840-86f2-4849108dba11.png)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

QGIS version | 3.20.3-Odense | QGIS code revision | 495fbaec
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.1
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 1909
  |   |   |
Active Python plugins | canvas_clipperLAStoolsplugin_reloaderdb_managerMetaSearchprocessing

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

The data provided by https://ogc-api.nrw.de/lika/v1/collections/gebaeude_bauwerk/items?f=json&limit=5000&offset=0&funktion=Carport&gmdschl=05166032 is in GeoJSON format, so I wonder why the deprecated OGR [CouchDB](https://gdal.org/drivers/vector/couchdb.html#vector-couchdb) driver is used and not the [GeoJSON](https://gdal.org/drivers/vector/geojson.html#vector-geojson) driver.

Data from the URL:
[items.zip](https://github.com/qgis/QGIS/files/7286436/items.zip)

**Comment by gioman** [comment]
> WARNING Cannot open https://ogc-api.nrw.de/lika/v1/collections/gebaeude_bauwerk/items?f=json&limit=5000&offset=0&funktion=Carport&gmdschl=05166032.(Driver COUCHDB is considered for removal in GDAL 3.5. You are invited to convert any dataset in that format to another more common one .If you need this driver in future GDAL versions, create a ticket at https://github.com/OSGeo/gdal (look first for an existing one first) to explain how critical it is for you (but the GDAL project may still remove it), and to enable it now, set the GDAL_ENABLE_DEPRECATED_DRIVER_COUCHDB configuration option / environment variable to YES)

@pathmapper ogrinfo from the command line returns the same error.

**Comment by pathmapper** [comment]
Thanks @gioman, opened an upstream issue https://github.com/OSGeo/gdal/issues/4601.

**Comment by jratike80** [comment]
You can get further by skipping the driver

`ogrinfo "https://ogc-api.nrw.de/lika/v1/collections/gebaeude_bauwerk/items?f=json&limit=5000&offset=0&funktion=Carport&gmdschl=05166032" --config OGR_SKIP COUCHDB -al`

There are still errors but the data are shown
```
ERROR 1: Invalid FeatureCollection object. Missing 'fields' member.
ERROR 1: Layer schema generation failed.
```

**Comment by pathmapper** [comment]
@jratike80 nice finds, we should move the discussion to OSGeo/gdal#4601.

**Comment by pathmapper** [comment]
Fixed upstream by @rouault in https://github.com/OSGeo/gdal/pull/4608 🎉
