### ISSUE TITLE
"QGIS" can't be opened because Apple cannot check it for malicious software

### ISSUE THREAD

**Issue by TomDavies93** [qgis/QGIS#45404]
### What is the bug or the crash?

Just downloaded the most recent version of QGIS, getting this pop up when I try to open it.

"QGIS" can't be opened because Apple cannot check it for malicious software.

This software needs to be updated. Conctact the developer for more information.

### Steps to reproduce the issue

On opening QGIS

### Versions

3.20

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@TomDavies93 https://github.com/qgis/QGIS/issues/34018#issuecomment-578186707

**Comment by Gustry** [comment]
@gioman can you pin the issue? It would maybe more readable

**Comment by gioman** [comment]
> @gioman can you pin and rename the other issue? It would maybe more readable

@Gustry I did it now. Anyway I'm sure we will continue get this report as many people does not look/search the tracker.

**Comment by agiudiceandrea** [comment]
The instructions are also written on the Website just near the link to download the macOS version:

https://qgis.org/en/site/forusers/download.html
> Download for macOS
> Official All-in-one, signed installers
> Mac Installer Packages for macOS High Sierra (10.13) and newer.
> 
> QGIS is not yet notarized as required by macOS Catalina (10.15) security rules. On first launch, please right-click on the QGIS app icon, hold down the Option key, then choose Open.

May the instructions could be improved in some way?
