### ISSUE TITLE
QgsVectorLayerProperties does not appear in C++ / Python API documentation

### ISSUE THREAD

**Issue by jakimowb** [qgis/QGIS#45437]
### What is the issue about the documentation?

By chance and with great joy I discovered that `QgsVectorLayerProperties` can even be used in the Python API (thank's a lot!)

Curiously it does not appear in the C++, qgis.qch or Python documentation, while it's counterpart `QgsRasterLayerProperties` does.

**Comment by nyalldawson** [comment]
This is present now: https://qgis.org/pyqgis/master/gui/QgsVectorLayerProperties.html
