### ISSUE TITLE
Bad_alloc when using Outline: Simple Line with Align dash pattern to line length

### ISSUE THREAD

**Issue by uclaros** [qgis/QGIS#45432]
### What is the bug or the crash?

When using a *Simple Line* style with *Align dash pattern to line length* enabled, and clearing the *stroke width* then qgis freezes and a `std::bad_alloc` pops up after a while.

### Steps to reproduce the issue

1. add a line layer
2. open the layer styling panel
3. Select *Simple Line* style and check *Align dash pattern to line length*
4. Clear the *Stroke width* or hover and scroll the mousewheel down
5. Freeze - std::bad_alloc

### Versions

498c52365d

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Once this happens QGIS cannot close or start a new project, it just freezes until the bad_alloc popup

**Comment by leojat** [comment]
Still happening in 3.28, 3.32 and Master (6339e5fb78).

Can also be triggered by selecting 'Hairline' as _Stroke width_, checking _Align dash pattern to line length_ and then trying to change any other option (e.g. _Offset_, _Stroke style_, etc.)
