### ISSUE TITLE
You need to rebuild GRASS GIS or untangle multiple installations.

### ISSUE THREAD

**Issue by bfpbppr3dowggm** [qgis/QGIS#45435]
### What is the bug or the crash?

GRASS init error: Problem in GRASS initialization, GRASS provider and plugin will not work : Module built against version 2021-08-12T15:48:18+00:00 but trying to use version 2021-10-04T19:41:40+00:00. You need to rebuild GRASS GIS or untangle multiple installations.

### Steps to reproduce the issue

On Start

### Versions

3.20.3

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
> On Start

try disable the GRASS plugin in the plugin manager.

**Comment by bfpbppr3dowggm** [comment]
It was the former. This was a new install, first time on, message popped up
as project screen loaded. I disabled the grass 7 plugin as recommended and
all seems to be working fine. Thanks for the help.
