### ISSUE TITLE
Custom cell size in fixed table not working (Layout)

### ISSUE THREAD

**Issue by B17DtJ** [qgis/QGIS#45431]
### What is the bug or the crash?

When setting "row height" or "column width" with custom values table designer does not respond and jumps back to Automatic. 

### Steps to reproduce the issue

1. Create or open a layout
2. Add fixed Table
3. Go to Item Properties and Edit Table ...
4. Try to change Cell Size

### Versions

QGIS 3.20.3-Odense

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by antoniolocandro** [comment]
Hi I did exactly that for a project today and had no problems. I am running 3.22.1-Białowieża have you checked that version?

**Comment by B17DtJ** [comment]
Hey antoniolocandro,
thanks for pointing this out. I just tried with 3.22.1-Białowieża on a Windows machine and still have no luck. The cell size switches back to automatic and the number field in the cell size editor behaves strangely. Maybe with a future version ...

**Comment by alexbruy** [comment]
This is rather a GUI/UX issue. Cell width and height can be changed, but you have to **select** the cell first and then adjust its dimensions. When table editor is opened there is no selected cell (the light blue rectangle is a focus indicator, not selection)

No selected cells (note that both vertical and horizontal headers are not bold, and there is no blue selection in the table)
![image](https://github.com/qgis/QGIS/assets/776954/ec7b5ca9-d67b-48e5-baab-bf285a79448f)

Cell selected (headers are bold, and there is a blue selection rectangle)
![image](https://github.com/qgis/QGIS/assets/776954/e50532ea-213e-438b-8145-4baf0b16bd1c)

I'd suggest closing this and filing another ticket about confusing UI.

**Comment by antoniolocandro** [comment]
Do not close this until the new feature request is added to not loose the traceability of the request
