### ISSUE TITLE
Performance issue of snapping indexing when adding/relocating features

### ISSUE THREAD

**Issue by kemen209** [qgis/QGIS#45448]
### What is the bug or the crash?

Adding features to vector layer will take up few seconds if snapping is enabled and snapping invisiable feature disabled and number of features goes up to few thousands.

### Steps to reproduce the issue

1. create a empty vector layer.
2. enable the snapping(so QgsPointLocator are created properly) on map canvas for this newly created layer.
3. start to adding(or relocating) vector feature to layer(For this step, i use qgis API to adding/removing features). 
4. It will take few seconds to finish adding feature as the number of features goes up, map/UI will stuck. For version QGIS 3.02 and below, it  has no such lag.

### Versions

v3.0.2+

specially start from commit: 43e905d7fcb4bbaf8851f5f1125d6fc9f9db48e4

### Supported QGIS version

- [x] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

Related info to my bug fix: https://github.com/qgis/QGIS/pull/45447

**Comment by kemen209** [comment]
Questions:

1. In my situation, i used a timer(20HZ) to repeated adding and removing features(about 500+) by API (in order to moving features to new location).
2. I'm not sure that QGIS API is designed for this purpose, but it worked well on version below 3.0.2, until the 'Add support for visible features', by commit: 43e905d7fcb4bbaf8851f5f1125d6fc9f9db48e4.
3. According to my debugging, the startRender and clone to render in the upper commit will take a signification time, which slow down the whole feature adding process.
4. For my situation, if i add a fix(https://github.com/qgis/QGIS/pull/45447), the time will drop down to a acceptable value(enough to finish adding 500 features within 50ms). But now the hotspot is on point-locator's RTree rebuilding.
5. I done some code reading on QgsSnappingUtils, if i only used the temporary locator(create a local locator every time snapping start), the performance issue will totally gone, as it will only search a small area for buiding indexing, and also no need to rebuild the indexing tree every time a feature is been added or updated. So my question is that why we need a dynamiclly changed indexing tree here? and for which circumstances?

**Comment by kemen209** [comment]
Perfomance profile after my bug fix: #45447, hotspot to RTree building.

<img width="1511" alt="Screen Shot 2021-10-07 at 10 10 54" src="https://user-images.githubusercontent.com/5885946/136310562-5207aa44-4cef-48bc-95f7-0e4c44e029e1.png">

**Comment by kemen209** [comment]
Perfomance profile after i only used the temperary locator:

<img width="1519" alt="Screen Shot 2021-10-07 at 10 27 55" src="https://user-images.githubusercontent.com/5885946/136310795-a4c936d3-2376-4e1c-8565-c26aa7ddfef3.png">

**Comment by alexbruy** [comment]
@kemen209 what is the state of this ticket, can it be closed?
