### ISSUE TITLE
Export to Postgresql not possible via processing tools or DB manager if table is geometryless and the DB has no PostGIS extension

### ISSUE THREAD

**Issue by tschmetzer** [qgis/QGIS#45449]
### What is the bug or the crash?

Export is not possible although via drag and drop it is possible with a gpkg file without geometry:

![grafik](https://user-images.githubusercontent.com/67278094/136324929-e7c9388c-5393-4cab-93c0-93b0ad42a1a2.png)
![grafik](https://user-images.githubusercontent.com/67278094/136325197-4ad139e7-56e8-449c-b929-f3d5dabaf1ed.png)

Works:
![grafik](https://user-images.githubusercontent.com/67278094/136325323-697f5e90-3e2f-42cf-ad7a-efeb0208e881.png)

### Steps to reproduce the issue

1. Have a postgresql DB without PostGIS extension
2. HAve a gpkg attribute file without geometry
3. Use processing tool "Export to PostgreSQL" according to screenshot
4. Function _dropgeometrytable()_ does not exist on PostgreSQL Server

Is _dropgeometrytable()_ really required? to import only attributes into the DB? Using just drag and drop works perfectly! The last screenshot shows how I did it.

### Versions

QGIS version | 3.20.1-Odense | QGIS code revision | 1c3c5cd6
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.1
PROJ version | 8.1.0
EPSG Registry database version | v10.027 (2021-06-17)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins | GroupStatsdb_managerMetaSearchprocessing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by tschmetzer** [comment]
> @tschmetzer works fine here, even importing it several times in a raw. I think that your original error may come from the absence of PostGIS, I'm inclined to think that the PostGIS extension is expected by QGIS tools.

Well, on the PostgreSQL server that I am using there is no PostGIS extension been installed and has never been. Do I obligatorily need to even if I want to store only attribute data and if so, why?

Seems like the point is to first find out if the PostGIS extension is actually required or expected to be installed. My notion would be that the PostGIS extension is only required if there is geometric GIS data that needs to be saved. If the user wants to store only attribute data why would QGIS require the DB server to have the PostGIS extension installed? Because that would mean to harass the DB system administrator to install the PostGIS extension although no real geometric data is to be transferred or accessed.

**Comment by gioman** [comment]
> Seems like the point is to first find out if the PostGIS extension is actually required or expected to be installed. My notion would be that the PostGIS extension is only required if there is geometric GIS data that needs to be saved. If the user wants to store only attribute data why would QGIS require the DB server to have the PostGIS extension installed? Because that would mean to harass the DB system administrator to install the PostGIS extension although no real geometric data is to be transferred or accessed.

@tschmetzer but QGIS is a GIS program, so personally I don't find it really strange that some tool needs PostGIS. But anyway I'll leave to a dev to say if this is expected or not.

**Comment by gioman** [comment]
> @gioman Regarding the feedback label: Is there any further feedback required from my part?

it is needed as I'm not sure if this is "won't fix", and as I said I'll leave to a dev to decide.
