### ISSUE TITLE
Check Validity tool only returns one result per feature

### ISSUE THREAD

**Issue by ZSGIS** [qgis/QGIS#45455]
### What is the bug or the crash?

Check Validity Tool, run via Vector tab will only return one issue per attribute when run. This results in a misleading error count when run. There may be hundreds of validity errors located within a few attributes. Would be vastly more helpful in cleaning data to see all errors in one run. 

### Steps to reproduce the issue

click vector dropdown menu, in geometry tools run check validity. Will return three temporary layers. 

### Versions

3.16.8

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
> I'm trying to clean up multiple data sets (that apparently have multiple errors in several features) and having an output that actually shows all the errors would be a huge time saver and help.

@ZSGIS have you tried the "geometry checker" or "topology checker"? those tools are not exposed in the Processing toolbox.

**Comment by alexbruy** [comment]
This is not a bug, it is by design. This tool can use two different validation engines: QGIS and GEOS. The latter can only report one error at once, while QGIS engine reports all errors.
