### ISSUE TITLE
Not possible to set back a raster picture if the SVG picture is invalid

### ISSUE THREAD

**Issue by Gustry** [qgis/QGIS#45477]
### What is the bug or the crash?

* In a layout, if the SVG path is invalid, it's not possible to set back a raster layout item.
* When loading a QML with QgsLayoutItem to a PNG which is unreachable, it's loaded as SVG, and it's not possible to set it back to raster easily.

### Steps to reproduce the issue

1. Add a layout item, it's a SVG by default.
2. Change the path to the SVG to make it wrong. You can add a PNG if you want, it's what I'm doing.
3. Until the SVG path is not valid, it's not possible to switch to raster.

Using QGIS Desktop, steps by step, it doesn't look like an issue. Why would I set an invalid PNG path in the SVG tab.
But it's somehow an issue when you load a QPT from file, with resources which are not available.

The given QML can be loaded. The path is `//192.168.1.100/0_Cartographie/Communication/Logo Eléments V2.PNG` and the path is not reachable. Pictures are loaded as SVG, even if the mode is set to `mode="1"` in the QPT.
https://qgis.org/api/classQgsLayoutItemPicture.html#af4073c25f1189e7b5b3d311ab544b383

QML to replicate the issue, try to change it as a raster
[20210812_modele_carte_elements.qpt.txt](https://github.com/qgis/QGIS/files/7321219/20210812_modele_carte_elements.qpt.txt)

![cant_change_type](https://user-images.githubusercontent.com/1609292/136764581-600ee35a-8e43-45e4-be72-aa4998104ee6.gif)

### Versions

Version de QGIS | 3.21.0-Master | Révision du code | 8498c5549f
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.2.2
PROJ version | 7.2.1
EPSG Registry database version | v10.008 (2020-12-16)
GEOS version | 3.9.0-CAPI-1.16.2
SQLite version | 3.34.1
PostgreSQL client version | 14.0 (Ubuntu 14.0-1.pgdg21.04+1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 21.04
  |   |   |  
Active Python plugins
quick_map_services | 0.19.26
ORStools | 1.4.0
sagaprovider | 2.12.99
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99
MetaSearch | 0.3.5

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
I noticed this too...
Could be linked to https://github.com/qgis/QGIS/pull/44745
