### ISSUE TITLE
Expressions: add a function to calculate the azimuth (bearing) between two points on the ellipsoid

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/QGIS#45474]
### Feature description

While there is the [`azimuth`](https://docs.qgis.org/3.16/en/docs/user_manual/working_with_vector/functions_list.html#azimuth) function which calculates the Cartesian azimuth between two points, but a function to calculate the geodesic azimuth on the ellipsoid is missing.

It could be based to the [`QgsDistanceArea::bearing`](https://qgis.org/api/classQgsDistanceArea.html#a60e46cdcc7541568e2c06787451722a2) function.

It will perform the same ellipsoid based calculation as the "[Measure bearing](https://github.com/qgis/QGIS/pull/43736)" map tool.

**Comment by DelazJ** [comment]
@agiudiceandrea closed by https://github.com/qgis/QGIS/pull/54297?
