### ISSUE TITLE
Failed to load plugin 'qgis-raster-attribute-table-plugin-master' due to an error calling the initGui () method

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#45473]
### What is the bug or the crash?

When starting QGIS master on Win 10 64, I get this message:

![image](https://user-images.githubusercontent.com/7631137/136689935-309c4afa-e634-4005-958b-26c0f678ba18.png)

### Steps to reproduce the issue

I start QGIS master and it happens

![image](https://user-images.githubusercontent.com/7631137/136690107-ded7cd40-5a61-4308-8192-eefab81d3125.png)

### Versions

```
Versione di QGIS 3.21.0-Master
Revisione codice QGIS 8498c5549f
Versione Qt 5.15.2
Versione Python 3.9.5
Versione GDAL/OGR 3.3.1
Versione PROJ 8.1.1
Versione database del Registro EPSG v10.028 (2021-07-07)
Versione GEOS 3.9.1-CAPI-1.14.2
Versione SQLite 3.35.2
Versione PDAL 2.3.0
Versione client PostgreSQL 13.0
Versione SpatiaLite 5.0.1
Versione QWT 6.1.3
Versione QScintilla2 2.11.5
Versione SO Windows 10 Version 2009

Questa copia di QGIS scrive messaggi di debug.

Plugins Python attivi:
DataPlotly 3.8.1
geo_sim_processing 1.2.0
GlobeBuilder v0.6.0
HCMGIS 21.8.28
kmltools 3.1.14
Korto Tools 1.1
mmqgis 2021.9.10
nominatim_locator_filter 0.2.4
processing_r 3.0.0
qconsolidate 1.1.0
qgis_resource_sharing 0.16.0
QuickOSM 2.0.0
quick_map_services 0.19.26
simple_tools 0.4.1
TAF-to-CSV-main 1.2
timezone_expressions v0.2
valuetool 3.0.15
db_manager 0.1.20
grassprovider 2.12.99
MetaSearch 0.3.5
processing 2.12.99
sagaprovider 2.12.99
```

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
Must be reported here https://github.com/noaa-ocs-hydrography/qgis-raster-attribute-table-plugin/issues instead.
