### ISSUE TITLE
Opening a QLR file with double click fails

### ISSUE THREAD

**Issue by christophfriedrich** [qgis/QGIS#45479]
### What is the bug or the crash?

I was supplied with a `.qgs` file by a colleague (@m-mohr) that opened in QGIS perfectly fine. I exported its layer as a `.qlr` file and saved it to disk. Double-clicking on this file to open it in QGIS fails with the message "Invalid data source: \<path> is not a valid data source or is not recognized." (This may not be the exact translation, the German original I see on my screen is: "Ungültige Datenquelle: \<path> ist keine gültige Datenquelle oder wird nicht erkannt.")

![grafik](https://user-images.githubusercontent.com/17781682/136770647-b0aa1a22-0075-466d-9433-32a352a0979c.png)

### Steps to reproduce the issue

0. Download the attached `.txt` file and rename the extension to `.qgs` (I had to rename it due to Github only accepting certain file types)
1. Double-click the `.qgs` file to open it in QGIS
2. In the Layers panel you see one layer, named "openEO"
3. Right-click on the layer name.
4. Select "Export" -> "Save as layer definition file"
5. Save the file
6. Find the file in your explorer
7. Double-click it
8. QGIS opens, but shows the error stated above

[my-test.txt](https://github.com/qgis/QGIS/files/7321571/my-test.txt)

Please note that the data described in the file will expire at some point.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS-Version | 3.20.3-Odense | QGIS-Codeversion | 495fbaecaf
-- | -- | -- | --
Qt-Version | 5.12.8
Python-Version | 3.8.10
GDAL-Version | 3.0.4
PROJ-Version | 6.3.1
EPSG-Registraturdatenbankversion | v9.8.6 (2020-01-22)
Kompiliert mit GEOS | 3.8.0-CAPI-1.13.1 | Läuft mit GEOS | 3.8.0-CAPI-1.13.1
Kompiliert mit SQLite | 3.31.1 | Läuft mit SQLite | 3.35.4
PDAL-Versio | 2.0.1
PostgreSQL-Client-Version | 12.8 (Ubuntu 12.8-0ubuntu0.20.04.1)
SpatiaLite-Version | 4.3.0a
QWT-Version | 6.1.4
QScintilla2-Version | 2.11.2
BS-Version | Ubuntu 20.04.3 LTS
  |   |   |  
Aktive Python-Erweiterungen | processingdb_managerMetaSearch

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

This is the very first thing I tried with my installation, which I downloaded only minutes earlier following [this guide](https://www.qgis.org/de/site/forusers/alldownloads.html#debian-ubuntu), so it's about as fresh as it gets.

**Comment by gioman** [comment]
Confirmed. Works fine from QGIS "add layer" menu or Browser.
