### ISSUE TITLE
Changing manually raster path in picture layout switch to SVG

### ISSUE THREAD

**Issue by nicogodet** [qgis/QGIS#45481]
### What is the bug or the crash?

![export2](https://user-images.githubusercontent.com/39594821/136791756-4d157fb8-e24b-44bf-b5d2-559b457a98b0.gif)

### Steps to reproduce the issue

1. Create a new picture layout
2. In raster mode, define a path to a picture
3. Edit manually the path
4. See it switch to svg mode

### Versions

3.20.3

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
On both, "regression" label could be added.
Everything is fine on 3.16

**Comment by Joonalai** [comment]
I will try to provide fix for this and for the another one (#45477) as well.
