### ISSUE TITLE
[ArcGIS REST] Identify Features HTTP referer

### ISSUE THREAD

**Issue by otofoto** [qgis/QGIS#45482]
### What is the bug or the crash?

Identify Features tool doesn't work for ArcGIS REST services with HTTP referer

Trying to get features results in HTTP Error: Internal Server Error 401

### Steps to reproduce the issue

1. Go to ArcGIS Rest services
2. Add New Connection
3. Provide connection details
4. Provide HTTP referer
5. Add (all layers) to map
5. Zoom to feature
6. Use Identify Features tool 
7. Expected result identify result but got error 401

### Versions

QGIS version
3.20.3-Odense
QGIS code revision
495fbaec
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.1
PROJ version
8.1.1
EPSG Registry database version
v10.028 (2021-07-07)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
BoundingBox
ComplexGmlInfo
firstaid
wfsclient
zoomtopaste
db_manager
MetaSearch
processing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

edit: version upgrade to latest

**Comment by otofoto** [comment]
Same issue in 3.20.3
Error transferring .../MapServer//identify?... - server replied: Internal Server Error

**Comment by otofoto** [comment]
Doesn't seem this example needs referer.
Can't post URL but could send it private.

**Comment by gioman** [comment]
> email sent

@otofoto works fine here on 3.20.3 (sent you screenshot).

**Comment by gioman** [comment]
> All layers is server feature?

@otofoto is for sure not something added by QGIS to the list of available layers.
