### ISSUE TITLE
Polygon to line algorithm does not recognise smooth output in Graphical modeler 

### ISSUE THREAD

**Issue by MMR100** [qgis/QGIS#45503]
### What is the bug or the crash?

In graphical modeler, I want to smooth polygons then extract the lines of theses smoothed polygons.
The algorithm "polygon to lines" does not recognise the output from "smooth algorithm"

### Steps to reproduce the issue

In graphical modeler: 

Create Smooth algorithm .
Then create "polygon to lines" algorithm 
Check in the list of algorithms output: the "smoothed" output is not available.

![image](https://user-images.githubusercontent.com/26409106/137086955-d9c2dc8a-41b7-4f70-bb09-a8a683be6e8b.png)

### Versions

QGIS 3.16.11 

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

### Additional context

In my case, I solved the issue by using first "polygon to lines" then "smooth" algorithm. But the bug would be interesting to solve anyway.

**Comment by nicogodet** [comment]
I confirme on 3.20.3 too.

**Comment by Koyaani** [comment]
According to the documentation, the `outputLayerType` method should only be overridden in the case where the output type is known in advance.

A quick fix could be to delete this method from `QgsSmoothAlgorithm` class. Or, modify the method in `QgsProcessingFeatureBasedAlgorithm` to be able to indicate many wkb types (as for `inputLayerTypes`)...
