### ISSUE TITLE
QGIS desktop crashed after order shape files in settings of join vectorial layers tool in batch mode

### ISSUE THREAD

**Issue by DanCu17** [qgis/QGIS#45501]
### What is the bug or the crash?

While I was ordering vectorial layers (about 19 layers) for clipping or joining, the program crashed and closed.  

### Steps to reproduce the issue

1 Go to Vectorial menu, 
2 data administration tool 
3 join vectorial layers.
4 Ejecute processes by "lots"
5 in parameters, input layers click autofill and open layer selection
6 in multiple selection menu select layers (about 10) and pull it to the bottom or the top of the list.
7 It crashed 

### Versions

Versión de QGIS 3.16.11-Hannover

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

Just to report the crash. I also ordered the shape one by one and it works normally. Sorry for the language mistakes, but I'm not a native speaker.

**Comment by gioman** [comment]
@DanCu17 what operating system?

**Comment by DanCu17** [comment]
Windows 10 Home (64 bits), version 21H1.

**Comment by DanCu17** [comment]
I repeated the steps, and it seems not to crash again. Maybe it was only my device. Thanks.
