### ISSUE TITLE
Wrong documentation of referenced_columns argument in qgsfunction

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#45519]
### What is the bug or the crash?

If you look at the help in the expression function editor tab you'll notice that the referenced_columns argument is described as

https://github.com/qgis/QGIS/blob/2d1aa68f0d044f2aced7ebeca8d2fa6b754ac970/src/gui/qgsexpressionbuilderwidget.cpp#L239-L240

But if you look at the API doc (Thanks to @3nids experimental [pyqgis utils doc](https://qgis.org/pyqgis/master_PR80/utils/qgsfunction.html)), you'll notice that its default value is mentioned as 'empty'.
https://github.com/qgis/QGIS/blob/2d1aa68f0d044f2aced7ebeca8d2fa6b754ac970/python/core/additions/qgsfunction.py#L145-L147

I suspect the latter is wrong because of 
https://github.com/qgis/QGIS/blob/2d1aa68f0d044f2aced7ebeca8d2fa6b754ac970/python/core/additions/qgsfunction.py#L60-L61
 Can anyone confirm?

### Steps to reproduce the issue

Check the code links above

### Versions

master 3.21 at least

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gacarrillor** [comment]
> But if you look at the API doc (Thanks to @3nids experimental [pyqgis utils doc](https://qgis.org/pyqgis/master_PR80/utils/qgsfunction.html)), you'll notice that its default value is mentioned as 'empty'.
> 
> https://github.com/qgis/QGIS/blob/2d1aa68f0d044f2aced7ebeca8d2fa6b754ac970/python/core/additions/qgsfunction.py#L145-L147

@DelazJ, this is no longer the case after https://github.com/qgis/QGIS/pull/52841, so we could close this issue.

_(However, I've spotted a bug there if we set this parameter to `None`, as suggested by the docs. I'll fix that with a PR.)_
