### ISSUE TITLE
qGis Compile

### ISSUE THREAD

**Issue by ranaabhi98** [qgis/QGIS#45513]
### Feature description

Dear Sir,
I tried to compile qGis for Windows . I have Successfully created a Solution file for Visual studio ( Community version 2015 ) .When I opened the Solution file  after that I found so many errors in the code. Please give me a better solution to successfully compile qGis.

**Comment by nicogodet** [comment]
Please ask on developer mailing list for building issue -> https://lists.osgeo.org/mailman/listinfo/qgis-developer
Don't double post (#45514)
