### ISSUE TITLE
Attribute Form Does Not Resize

### ISSUE THREAD

**Issue by jbell6** [qgis/QGIS#45520]
### What is the bug or the crash?

The Attributes Form does not resize. This means that when there are many fields in the Feature Attributes Form the "OK" cannot be clicked to insert the data. 
![image](https://user-images.githubusercontent.com/63289882/137291402-6acf29dd-5a21-4b8d-acde-d5e3b550fa4c.png)
The attached image shows the attribute form with many fields which cannot be resized.

### Steps to reproduce the issue

1. Create a table with 40 fields.
2. In properties create an "Attributes Form".
3. Add all fields to the form layout. Ensure "Show Form on Add Feature" is selected.
4. Make layer editable.
5. Add feature
6. Attempt to resize window.

### Versions

QGIS version
3.16.9-Hannover
QGIS code revision
9f8d2f79
Compiled against Qt
5.15.2
Running against Qt
5.15.2
Compiled against GDAL/OGR
3.3.1
Running against GDAL/OGR
3.3.1
Compiled against GEOS
3.9.1-CAPI-1.14.2
Running against GEOS
3.9.1-CAPI-1.14.2
Compiled against SQLite
3.35.2
Running against SQLite
3.35.2
PostgreSQL Client Version
13.0
SpatiaLite Version
5.0.1
QWT Version
6.1.3
QScintilla2 Version
2.11.5
Compiled against PROJ
8.1.0
Running against PROJ
Rel. 8.1.0, July 1st, 2021
OS Version
Windows 10 Version 1903
Active python plugins
autoSaver; 
batch_gps_importer; 
DigitizingTools; 
FreehandRasterGeoreferencer; 
geoscience; 
gistools; 
ioGAS; 
MagneticDeclination; 
openlayers_plugin; 
qconsolidate3; 
qfieldsync; 
QMetaTiles; 
quick_map_services; 
SentinelHub; 
slyr_community; 
spectral_libraries; 
SuperLabeling; 
db_manager; 
MetaSearch; 
processing; 
ImportPhotos; 
QGeoloGIS; 
vrtbuilderplugin

QGIS version
3.16.11-Hannover
QGIS code revision
26cc1c76
Compiled against Qt
5.15.2
Running against Qt
5.15.2
Compiled against GDAL/OGR
3.3.1
Running against GDAL/OGR
3.3.1
Compiled against GEOS
3.9.1-CAPI-1.14.2
Running against GEOS
3.9.1-CAPI-1.14.2
Compiled against SQLite
3.35.2
Running against SQLite
3.35.2
PostgreSQL Client Version
13.0
SpatiaLite Version
5.0.1
QWT Version
6.1.3
QScintilla2 Version
2.11.5
Compiled against PROJ
8.1.1
Running against PROJ
Rel. 8.1.1, September 1st, 2021
OS Version
Windows 10 Version 1903
Active python plugins
autoSaver; 
batch_gps_importer; 
DigitizingTools; 
FreehandRasterGeoreferencer; 
geoscience; 
gistools; 
ImportPhotos; 
ioGAS; 
MagneticDeclination; 
openlayers_plugin; 
qconsolidate3; 
qfieldsync; 
QGeoloGIS; 
QMetaTiles; 
quick_map_services; 
SentinelHub; 
slyr_community; 
spectral_libraries; 
SuperLabeling; 
vrtbuilderplugin; 
db_manager; 
MetaSearch; 
processing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

It works in QField.

**Comment by alexbruy** [comment]
Duplicates #28521
