### ISSUE TITLE
Raster tiles are clipped based on the gpkg_contents bounding box of a GeoPackage

### ISSUE THREAD

**Issue by albintornqvist** [qgis/QGIS#45530]
### What is the bug or the crash?

I found that QGIS seems to use the bounding box of the gpkg_contents table in an unexpected way. The GeoPackage specification (https://www.geopackage.org/spec/#_contents) says that the bounding box is informative only and is not required to represent the data in the GeoPackage. Therefore I expected that it would not affect the rendering of the tiles. However I found that when I changed the bounding box to be smaller than the content of my tile set, the rendered tiles seem to become clipped. When I import the same data set into the online GeoPackage viewer developed by NGA (https://ngageoint.github.io/geopackage-js/) all tiles are shown and not clipped.

Expected appearence regardless of the bounding box in gpkg_contents:
<img width="541" alt="Screenshot 2021-10-15 at 16 48 22" src="https://user-images.githubusercontent.com/5670130/137507244-ffd6237d-260e-4db2-bf19-a32a79bd1365.png">

Clipped content when the bounding box in gpkg_contents is smaller than the content:
<img width="504" alt="Screenshot 2021-10-15 at 16 48 44" src="https://user-images.githubusercontent.com/5670130/137507325-685fc186-8918-490c-9656-7bf0af4072e5.png">

### Steps to reproduce the issue

Reproduce by dragging this GeoPackage
https://2xper-bucket.s3.eu-west-1.amazonaws.com/b0234e9bf00749c3b1255682e1be00e3/geopackage_too_small_bbox.gpkg 
into QGIS. All data visible in my first image should be visible but they are not. I used Open Street Map as a background.

For comparison, this GeoPackage contains exactly the same data but has a larger bounding box in the gpkg_contents table: https://2xper-bucket.s3.eu-west-1.amazonaws.com/b0234e9bf00749c3b1255682e1be00e3/geopackage_pixelshift_at_15.gpkg

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.16.11-Hannover | QGIS code revision | 26cc1c762f
-- | -- | -- | --
Compiled against Qt | 5.14.2 | Running against Qt | 5.14.2
Compiled against GDAL/OGR | 3.2.1 | Running against GDAL/OGR | 3.2.1
Compiled against GEOS | 3.9.1-CAPI-1.14.2 | Running against GEOS | 3.9.1-CAPI-1.14.2
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.4
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | macOS 11.3
Active python plugins | zoom_level; processing; db_manager; MetaSearch

</body></html>

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@albintornqvist I see what you describe also on QGIS 3.20 on Windows, but if you gdal_translate your raster (to a geotiff for example) the resulting raster is also identical to the one that QGIS shows, so maybe the issue is not in QGIS itself.

**Comment by rouault** [comment]
When using the "Add raster layer" dialog, it is possible to set the USE_TILE_EXTENT option.
