### ISSUE TITLE
 a10a1c9baca25987e4c47448df59f0d332c45a24

### ISSUE THREAD

**Issue by sivansakthi** [qgis/QGIS#45545]
### What is the bug or the crash?

Crash ID: a10a1c9baca25987e4c47448df59f0d332c45a24

Stack Trace

QMetaObject::cast :
QgsLayerTreeModel::parent :
QModelIndex::parent :
QTreeView::drawRow :
QTreeView::drawTree :
QTreeView::paintEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::drawWidget :
QApplication::windowIcon :
QWidget::event :
QgisApp::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.16.3-Hannover
QGIS code revision: 94ac9f21b8
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

### Steps to reproduce the issue

while clicking in Layers panel get hanging and it says need to restart.

After the restart again the same issues.

Please let us know how to fix this issues.

I am tried Quick Attribution plugin

### Versions

3.16

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
"I am tried Quick Attribution plugin" <- nnd without this plugin no crash ?

If so, not a QGIS issue, report this bug on plugin tracker.

**Comment by sivansakthi** [comment]
This is a plugin Issue.

 

Sometimes I captured the Lateral line and save it. After opening only, I can see the Tables not found any Graphics. Please find the attached files to this mail.

 

For Example:

 

 

The Lateralline total count: 20369

 



 

Open the table and find “SS” field and sort ascending and find null values. If I click the null values from ss field zoom. It gives warning as “Cannot Zoom to selected feature(s) No extended could be determined ”

 

Please let me how to recover the lines and table

 

Regards,

Sivansakthi
