### ISSUE TITLE
Attribute table is present and Dont have graphich in LateralLine.

### ISSUE THREAD

**Issue by sivansakthi** [qgis/QGIS#45546]
### What is the bug or the crash?

Sometimes I captured the Lateral line and save it. After opening only, I can see the Tables not found any Graphics
[Lines.zip](https://github.com/qgis/QGIS/files/7362533/Lines.zip)
![Error](https://user-images.githubusercontent.com/92709125/137684776-4566bedf-9475-4afe-ae43-59847af4a221.png)

Open the table and find “SS” field and sort ascending and find null values. If I click the null values from "SS" field zoom. It gives warning as “**Cannot Zoom to selected feature(s) No extended could be determined** ”

Please let me know what need to be done for recover.

### Steps to reproduce the issue

[Lines.zip](https://github.com/qgis/QGIS/files/7362564/Lines.zip)
![Error](https://user-images.githubusercontent.com/92709125/137685159-a459cb0b-a044-422b-bc78-8a2c9217f1d6.png)

### Versions

3.16

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
> Please let me know what need to be done for recover.

@sivansakthi you have NULL geometries, fix them with "remove NULL geometries".

**Comment by gioman** [comment]
> 1. First, click the lateralline shapefiles then go to Toggle Editing button 2. To create a line by using Add line feature button 3. After creating line feature attribute table is open called as Feature Attributes 4. Then fill required attributes by manually. 5. Click OK button. This is the way created line features.

@sivansakthi the above steps will work ok, because you can't trigger the form for attributes to show up unless you draw at least 2 vertexes (1 segment). So probably your workflow is broken somewhere else.
