### ISSUE TITLE
The setting "Do not expose via WMS and WFS" does not work.

### ISSUE THREAD

**Issue by APPUdes** [qgis/QGIS#45567]
### What is the bug or the crash?

In the fields properties, when we select "Do not expose via WMS" or "Do not expose via WFS" for the attributes in the configuration combobox, the WMS and WFS services still display these attributes.

### Steps to reproduce the issue

In the fields properties, select "Do not expose via WMS" or "Do not expose via WFS" for an attribute (see the image below) !
![image](https://user-images.githubusercontent.com/39161930/137898574-7c62797f-3c13-4b98-ade0-2defede13bae.png)

Then add WMS or WFS service in QGIS Desktop and use "Identify Features" ![image](https://user-images.githubusercontent.com/39161930/137898609-32570799-1648-4f71-86d0-04d59c9fa726.png) to show the attributes. You will see that the attribute you set to "Do not expose" is visible.

### Versions

Version QGIS Desktop: 3.20.0-Odense
Version QGIS Server: 3.20.1

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
>  Version QGIS Server: 3.20.1

@APPUdes works fine on a 3.16 server. Can you say if is a 3.20 regression?

**Comment by gioman** [comment]
@APPUdes nevermind, I also tested on a 3.20 Server, still all works as expected.

**Comment by gioman** [comment]
> Do we need to configure a parameter on QGIS server to accept the "Do not expose via WMS" parameter?

@APPUdes no.

**Comment by APPUdes** [comment]
I did the test again and I have the same problem.

My configuration:
![image](https://user-images.githubusercontent.com/39161930/139701943-df4285bf-2171-4aa4-8491-b385a281572b.png)

Service WMS:
![image](https://user-images.githubusercontent.com/39161930/139702024-a9b9384d-fb9b-49c2-8380-a2dbb4bd3a68.png)

**Comment by gioman** [comment]
@APPUdes does it happens only with a uuid field?

**Comment by APPUdes** [comment]
No, same think for the other attributes

**Comment by Gustry** [comment]
> Version QGIS Desktop: 3.20.0-Odense
Version QGIS Server: 3.20.1

QGIS 3.20 is EOL.
Any chance you can try on 3.22 ? (both desktop and server)
Which is the next LTR.

I will try soon on 3.22

**Comment by APPUdes** [comment]
I found the problem. We have to check the parameter "Use attribute form settings for GetFeatureInfo response" in the project properties.

![image](https://user-images.githubusercontent.com/39161930/139909025-249b9c4d-d0a1-4e7b-9650-2d495df0ec9b.png)
