### ISSUE TITLE
Plugin disabled due to crashing of qgis

### ISSUE THREAD

**Issue by pravinyab** [qgis/QGIS#45561]
### What is the bug or the crash?

QGIS crashed

### Steps to reproduce the issue

No plugins are available. Wanted to use Raster reprojection and clipping

### Versions

QGIS desktop 3.4.4 Madeira

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Update to lastest version of QGIS (3.16.11 or 3.20.3) first.

And try with a new profile
