### ISSUE TITLE
HTTPS WMS server (based on Mapserver) on IIS with Negotiate authentication not working

### ISSUE THREAD

**Issue by lucamanga** [qgis/QGIS#45585]
### What is the bug or the crash?

Hello,
with QGIS 3.20.3 I try to connect to a Mapserver WMS Server (under HTTPS) with these credentials:

  username:    DOMAIN\testuser  (i.e.   samedomain\sameuser)
  password:    blabla123!

QGIS repeatedly asks for username and password (doing it on browser, it works perfectly)

### Steps to reproduce the issue

1) add a HTTPS Mapserver WMS server, with authentication on "Basic" (not Configuration) section
2) connect it
3) select a layer
4) after clicking on "Add" button, it asks repeatedly for username and password

### Versions

3.20.3

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by lucamanga** [comment]
Simply I think that QGIS doesn't remember the provided password.

**Comment by gioman** [comment]
@lucamanga works fine here (Mapserver backend, with basic Apache http auth). QGIS 3.20.3
