### ISSUE TITLE
Vector Drop Down Menu disappears after changing language

### ISSUE THREAD

**Issue by RobinKohrs** [qgis/QGIS#45586]
### What is the bug or the crash?

So I switched the language of the qgis interface as described here from german to american english:

https://gis.stackexchange.com/questions/26457/how-can-i-change-the-language-of-the-qgis-interface

After doing so, and after a restart of QGIS, the vector drop down menu only contains the option for the quick OSM plugin like so: 

![Screenshot (9)](https://user-images.githubusercontent.com/48288925/138073723-a6de7ba2-ab71-4b38-8d10-e56e09553749.png)

I changed it back to german and the options came back. I switched it back to english and they were gone again. 
However, by searching for all the vector related tools, I still could use them:)

### Steps to reproduce the issue

1. Go to Settings -> Options -> General 
2. Change language from german to american english
3. Restart QGis
4. Click on the Vector tab

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.20.3-Odense | QGIS code revision | 495fbaec
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.1
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins | HqgisORStoolsQuickOSMquick_map_servicesdb_managerMetaSearchprocessing

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by DelazJ** [comment]
@RobinKohrs Don't you have a vector menu at the far right, after Help?
From the Settings, Options, Processing, Menus, press Reset to default and restart.

**Comment by RobinKohrs** [comment]
I do;) I haven't even seen that sorry... I have two now. And the right one continues to be in german and has all the drop-downs

**Comment by RobinKohrs** [comment]
Worked!;) Thank you very much
