### ISSUE TITLE
Crashing with snapping and WFS

### ISSUE THREAD

**Issue by lifa-lin** [qgis/QGIS#45589]
### What is the bug or the crash?

We’re running a dataset via WFS (Geoserver 2.16) into QGIS.
The user has snap turned on while digitizing/editing, and too often this combo results in QGIS crashing.

However, this crash does not happen when digitizing/editing, but during other operations like panning the map or something similar.

The stack dump mentions “snapPoint”, “snapToMap”, “nearestVertex”, and “closestVertex”, which to me implies the snapping function in action.
It also mentions “canvasMoveEvent”, which to me implies a panning operation.

I expected the snapping operation to be entirely local, i.e. independent of actual data source type, but this apparently only happens when using a WFS data source.

We haven't seen this error while working with non-WFS connections.

### Steps to reproduce the issue

![2021-10-15 10_51_32-Nedbrud _ Microsoft Teams](https://user-images.githubusercontent.com/37143389/138083022-c0581449-a51b-446a-adac-8d63ec58de47.png)

It happens intermittently, and without any further explanation apart from this stack dump.

The user even turned snapping off while panning the map, but the same error occurred repeatedly.

### Versions

3.16.10

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by lifa-lin** [comment]
It's not myself, who experience this problem, so I'll need to ask the person who reported it to me.
He's running Windows 10 btw.

**Comment by lifa-lin** [comment]
Got it.

**Comment by jmckenna** [comment]
If you need a public+maintained WFS service to test this against, you can use mine: https://demo.gatewaygeomatics.com/cgi-bin/wfs_gateway?REQUEST=GetCapabilities&VERSION=1.0.0&SERVICE=WFS

**Comment by lifa-lin** [comment]
Not really the same as #44252. In our case we're also not experiencing the crash while editing.

**Comment by lifa-lin** [comment]
I've finally gotten some feedback that brings this issue forward.
Running QGIS without plugins prevents crashing.
And it seems that disabling all event handlers in my plugin also prevents crashing.
However, that only refocuses my question onto why these event handlers crash QGIS.
These are the event handlers (signals) that I hook onto:
- (project).readProject
- (project).cleared
- (project).layersAdded
- (project).metadataChanged
- (layer).metadataChanged
- (layer).featureAdded
- (layer).attributeValueChanged
None of these ought to be activated when the user is panning or zooming, unless I'm missing something.
