### ISSUE TITLE
Map Tool Identify - crash

### ISSUE THREAD

**Issue by robbitt** [qgis/QGIS#45596]
### What is the bug or the crash?

Using the feature info tool, I clicked and dragged to retrieve info from several vector layers - which crashed QGIS.

Crash ID: 9f3b407c88877d8ba7ad50ed5a3762a7dea5132a

Stack Trace

QString::QString :
QgsMapToolIdentify::formatYCoordinate :
QgsMapToolIdentify::closestPointAttributes :
QgsMapToolIdentify::featureDerivedAttributes :
QgsMapToolIdentify::identifyVectorLayer :
QgsMapToolIdentify::identifyLayer :
QgsMapToolIdentify::identify :
QgsMapToolIdentify::identify :
QgsMapToolIdentifyAction::identifyFromGeometry :
QObject::qt_static_metacall :
QgsIdentifyResultsDialog::formatChanged :
QgsMapToolSelect::setSelectionMode :
QgsMapToolIdentifyAction::canvasReleaseEvent :
QgsMapCanvas::mouseReleaseEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.20.2-Odense
QGIS code revision: 9f59a156
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.1
Running against GDAL: 3.3.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

### Steps to reproduce the issue

1. Launch QGIS Desktop 3.20
2.  Add vector layers
3.  Click Map Info tool and click and drag around several vectors
4.  Crashes QGIS on periodically

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.20.2-Odense | QGIS code revision | 9f59a156
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.1
PROJ version | 8.1.0
EPSG Registry database version | v10.027 (2021-06-17)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins | clippercoordinates_converterlatlontoolsMagneticDeclinationQCopycanvasqgis_resource_sharingsplitmultipartdb_managerMetaSearchprocessing

</body></html>

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
> Crashes QGIS on periodically

@robbitt try with a new QGIS profile, no 3rd party plugins installed.
