### ISSUE TITLE
incorrect line symbology at acute angles with 2 combined simple lines

### ISSUE THREAD

**Issue by Jan-QGIS** [qgis/QGIS#45608]
### What is the bug or the crash?

Hey Guys,

as shown in the picture i created a line symbology that was made of 2 simple lines with offset so they dont overlap.

At acute angles the blue line is not drawed properly. There are "white" areas between the blue and the black line.

If the angle is wider both lines are drawed as expected.

![picture](https://user-images.githubusercontent.com/92924416/138269907-d11bdd36-7ef6-4d4b-8d29-09dc72fe5c68.jpg)

### Steps to reproduce the issue

Line properties:

![1](https://user-images.githubusercontent.com/92924416/138270522-d34e3353-65eb-4303-ad3f-8739f597aff9.jpg)

![2](https://user-images.githubusercontent.com/92924416/138270536-fbadd0c3-4366-4f84-83f0-2ec3d6441932.jpg)
 

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.16.11-Hannover | QGIS code revision | 26cc1c76
-- | -- | -- | --
Compiled against Qt | 5.15.2 | Running against Qt | 5.15.2
Compiled against GDAL/OGR | 3.3.1 | Running against GDAL/OGR | 3.3.1
Compiled against GEOS | 3.9.1-CAPI-1.14.2 | Running against GEOS | 3.9.1-CAPI-1.14.2
Compiled against SQLite | 3.35.2 | Running against SQLite | 3.35.2
PostgreSQL Client Version | 13.0 | SpatiaLite Version | 5.0.1
QWT Version | 6.1.3 | QScintilla2 Version | 2.11.5
Compiled against PROJ | 8.1.1 | Running against PROJ | Rel. 8.1.1, September 1st, 2021
OS Version | Windows 10 Version 2009
Active python plugins | AnotherDXF2Shape; shapetools; db_manager; processing

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

Thank you!

**Comment by roya0045** [comment]
I'm not sure how this is a bug, the gap is smaller than your offset so the line is displayed properly offset. It's debatable if having a weird overlap is better than this approach as this makes more sense.
