### ISSUE TITLE
QgsProcessingParameterMultipleLayers adds an extra list element when reordering inputs

### ISSUE THREAD

**Issue by jorgepsantos2002** [qgis/QGIS#45634]
### What is the bug or the crash?

I was unable to build a virtual raster. There is an issue when I sort my Landsat-8 imagery.
I made a screencast. All bands are listed below.

**Link**: [landsat8 bands](https://drive.google.com/file/d/1uqOjYIKzA-aH7UlEee8g8pICzdu0Ob-8/view?usp=sharing)

### Steps to reproduce the issue

https://user-images.githubusercontent.com/13324913/138537504-e06ce9eb-26ae-4fcd-95fa-71729aa7c347.mp4

### Versions

<table role="table">
<tbody>
<tr>
<th style="width: 111.088px;">Versão do QGIS</th>
<th style="width: 271.288px;">3.16.11-Hannover</th>
<th style="width: 106.262px;">Código da versão do QGIS</th>
<th style="width: 102.162px;"><a class="commit-link" href="https://github.com/qgis/QGIS/commit/26cc1c76" data-hovercard-type="commit" data-hovercard-url="https://github.com/qgis/QGIS/commit/26cc1c76/hovercard"><tt>26cc1c76</tt></a></th>
</tr>
<tr>
<td style="width: 111.088px;">Compilado sobre Qt</td>
<td style="width: 271.288px;">
<p>5.15.2</p>
</td>
<td style="width: 106.262px;">Rodando sobre Qt</td>
<td style="width: 102.162px;">5.15.2</td>
</tr>
<tr>
<td style="width: 111.088px;">Compilado sobre GDAL/OGR</td>
<td style="width: 271.288px;">
<p>3.3.1</p>
</td>
<td style="width: 106.262px;">Rodando sobre GDAL/OGR</td>
<td style="width: 102.162px;">3.3.1</td>
</tr>
<tr>
<td style="width: 111.088px;">Compilado sobre GEOS</td>
<td style="width: 271.288px;">
<p>3.9.1-CAPI-1.14.2</p>
</td>
<td style="width: 106.262px;">Rodando sobre GEOS</td>
<td style="width: 102.162px;">3.9.1-CAPI-1.14.2</td>
</tr>
<tr>
<td style="width: 111.088px;">Compilado no SQLite</td>
<td style="width: 271.288px;">3.35.2</td>
<td style="width: 106.262px;">Executando contra SQLite</td>
<td style="width: 102.162px;">3.35.2</td>
</tr>
<tr>
<td style="width: 111.088px;">Versão do cliente PostgreSQL</td>
<td style="width: 271.288px;">13.0</td>
<td style="width: 106.262px;">Versão SpatiaLite</td>
<td style="width: 102.162px;">5.0.1</td>
</tr>
<tr>
<td style="width: 111.088px;">Versão do QWT</td>
<td style="width: 271.288px;">6.1.3</td>
<td style="width: 106.262px;">Versão QScintilla2</td>
<td style="width: 102.162px;">2.11.5</td>
</tr>
<tr>
<td style="width: 111.088px;">Compilado com PROJ</td>
<td style="width: 271.288px;">8.1.1</td>
<td style="width: 106.262px;">Em execução com PROJ</td>
<td style="width: 102.162px;">Rel. 8.1.1, September 1st, 2021</td>
</tr>
<tr>
<td style="width: 111.088px;">Versão SO</td>
<td style="width: 271.288px;">Windows 10 Version 2009</td>
<td style="width: 106.262px;">&nbsp;</td>
<td style="width: 102.162px;">&nbsp;</td>
</tr>
<tr>
<td style="width: 111.088px;">Ativar complementos python</td>
<td style="width: 271.288px;">AzimuthDistanceCalculator; DsgTools; HCMGIS; mmqgis; quick_map_services; db_manager; MetaSearch; processing</td>
</tr>
</tbody>
</table>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
Not reproducible in latest master.

**Comment by nicogodet** [comment]
Can't reproduce either on 3.24.3 and 3.22.4
