### ISSUE TITLE
Package QGIS for the new Ubuntu Impish release

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS#45641]
### Feature description

See https://lists.osgeo.org/pipermail/qgis-user/2021-October/050087.html

When people upgrade to 21.10/Impish there is no QGIS yet

**Comment by agiudiceandrea** [comment]
It seems QGIS 3.22.0 is now available also for GNU/Linux Ubuntu Impish https://qgis.org/ubuntu/dists/?C=M;O=D

**Comment by rduivenvoorde** [comment]
Ah cool. Thanks. So my take is that we package the lastest QGIS for latest Ubuntu and the the timelines of releases were this time a little off (as in Ubuntu released just a little too early for packaging of QGIS).
Thanks!

**Comment by moovida** [comment]
Interesting, following this: https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule
it should have been an LTR, but in the LTR repo, it is not available for impish.

**Comment by rduivenvoorde** [comment]
Nope, that's a long discussion, but in short: a 3.22.zero is not yet LTR, but a Release candidate.
After 3.22.1 (when bugs are fixed) it will probably in the LTR repo.

**Comment by moovida** [comment]
Thanks a lot for the explanation.

**Comment by agiudiceandrea** [comment]
@moovida as you can see in the table, looking at the "Long Term Repo" column, QGIS 3.22.x will be available in the LTR repositories beginning from QGIS 3.22.4.

**Comment by rduivenvoorde** [comment]
Ah shoot, thanks for correcting me, you are right, it will be true LTR when the new version will be released...

**Comment by moovida** [comment]
Ahhh, thanks @agiudiceandrea , I had not noticed that one.
