### ISSUE TITLE
GDAL/Contour tool on Windows does not set the correct output CRS

### ISSUE THREAD

**Issue by coefficient1900** [qgis/QGIS#45676]
### What is the bug or the crash?

Because I tried to generate some contour lines (GDAL raster extraction) from a DEM (txt-file) I noticed that there is a problem with temporary results or more general with .gpkg. These are not be generated the correct way for the stated algorithm and therefore not shown.

(The test project contains a dem from a txt file and the same dem as tiff.)

[contourtest.zip](https://github.com/qgis/QGIS/files/7419765/contourtest.zip)

### Steps to reproduce the issue

Execute the GDAL "Contour" tool with a dem from a text file (in the example the textdem raster layer) and try to receive a temporary result.

![cont1](https://user-images.githubusercontent.com/86417466/138916610-50e0e795-fcac-4d67-9b65-fae4d4ad58f9.PNG)

You will see the corresponding warnings:

![cont2](https://user-images.githubusercontent.com/86417466/138916953-7d18ff05-7b4f-4a64-bcc4-3d75f425eb21.PNG)

With the tiff generated from the txt-dem, the temporary contour lines will appear. Also the contour lines from the txt-file exist if generated as a shape instead of temporary or .gpkg.

The before mentioned behaviour seems to be valid for QGIS 3.16.11 / 3.16.12 / 3.22.0 on Windows machines.
On windows with QGIS 3.10.14 all worked well, also on Ubuntu with 3.22.0.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.16.11-Hannover | QGIS code revision | 26cc1c76
-- | -- | -- | --
Compiled against Qt | 5.15.2 | Running against Qt | 5.15.2
Compiled against GDAL/OGR | 3.3.1 | Running against GDAL/OGR | 3.3.1
Compiled against GEOS | 3.9.1-CAPI-1.14.2 | Running against GEOS | 3.9.1-CAPI-1.14.2
Compiled against SQLite | 3.35.2 | Running against SQLite | 3.35.2
PostgreSQL Client Version | 13.0 | SpatiaLite Version | 5.0.1
QWT Version | 6.1.3 | QScintilla2 Version | 2.11.5
Compiled against PROJ | 8.1.1 | Running against PROJ | Rel. 8.1.1, September 1st, 2021
OS Version | Windows 10 Version 2009
Active python plugins | db_manager; MetaSearch; processing

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
I'd say this is a won't fix for now, as there is no way to pass CRS to the `gdal_contour`. A ticket should be filled in the GDAL bugtracker to add this option and then it can be fixed in QGIS.

**Comment by coefficient1900** [comment]
On a Windows 11 machine, the temporary contour output is valid with QGIS versions 3.22.16 and 3.28.7. So it seems to be resolved for some cases anyway.
