### ISSUE TITLE
loading SELAFIN file with none dataset as vector layer causes QGIS to hang

### ISSUE THREAD

**Issue by nicogodet** [qgis/QGIS#45674]
### What is the bug or the crash?

Tried on Windows and Linux and on both platform, QGIS hangs after drag & drop a SELAFIN meshlayer.
It hangs with 100% CPU usage.

[test_mesh_3.22.slf.zip](https://github.com/qgis/QGIS/files/7418765/test_mesh_3.22.slf.zip)

~~In general, Drag & Drop of meshlayer seems not well handle by QGIS. Dropping a TELEMAC `.res` open faces as polygon layer for each time step and vertices as point layer for each time step.
Should I create another issue or do we make this current ticket more general ?
![image](https://user-images.githubusercontent.com/39594821/138896958-6987401d-a3eb-4f7f-a361-b347fcedb107.png)
(The layer in screenshot can be sent by email if requested)~~ See first comment

### Steps to reproduce the issue

Drag and drop a meshlayer in QGIS

### Versions

3.22 Linux and Windows

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by vcloarec** [comment]
upstream bug in OGR fixed by https://github.com/OSGeo/gdal/pull/4945
