### ISSUE TITLE
qgis 3.20 download failed

### ISSUE THREAD

**Issue by Fscipioni** [qgis/QGIS#45695]
### What is the bug or the crash?

I am trying to download QGIS 3.20 on my Macbook (version 12.0.1), both with Chrome and Safari, but I receive a message saying "Failed - no file" with Chrome, while Safari downloads something, but then the .dmg file can't be mounted.

### Steps to reproduce the issue

download QGIS 3.20 on a Macbook

### Versions

3.20

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@Fscipioni would you mind testing with the 3.22 installer here? https://qgis.org/downloads/macos/pr/qgis_pr_final-3_22_0_20211022_154850.dmg I have reports that it downloads, install and runs ok on Monterey.

**Comment by Fscipioni** [comment]
yes, this link worked

**Comment by gioman** [comment]
> yes, this link worked

@Fscipioni does it installs and starts as expected?

**Comment by Fscipioni** [comment]
yes, I was able to install and run it on Big Sur. I haven't tried on Monterey

**Comment by gioman** [comment]
>  I haven't tried on Monterey

@Fscipioni please let us know if it works as expected on Monterey.
