### ISSUE TITLE
Browser Panel does not correctly create spatialite db

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#45725]
### What is the bug or the crash?

the browser panel does not create spatialite databases correctly and does not load db already created previously either

![image](https://user-images.githubusercontent.com/7631137/139412961-78d2a753-4a6f-49e1-804a-3cc97980d2a0.png)

### Steps to reproduce the issue

1. in the browser panel select Spatialite
2. right click on spatialite: create database ...
3. enter database name
4. error message appears in the browser panel

## OSGeo4W64 v2 QGIS 3.22.0

QGIS version 3.22.0-Białowieża
QGIS code revision d9022691f1
Qt version 5.15.2
Python version 3.9.5
GDAL/OGR version 3.3.2
PROJ version 8.1.1
EPSG Registry database version v10.028 (2021-07-07)
GEOS version 3.10.0-CAPI-1.16.0
SQLite version 3.35.2
PDAL version 2.3.0
PostgreSQL client version 13.0
SpatiaLite version 5.0.1
QWT version 6.1.3
QScintilla2 version 2.11.5
OS version Windows 10 Version 2009

Active Python plugins db_manager 0.1.20
grassprovider 2.12.99
MetaSearch 0.3.5
processing 2.12.99
sagaprovider 2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
Fixed by https://github.com/qgis/QGIS/pull/45900

**Comment by pigreco** [comment]
i just updated and the master still has the problem
![image](https://user-images.githubusercontent.com/7631137/140604385-946cde88-70b3-4e78-9442-981835239d52.png)

**Comment by nirvn** [comment]
@pigreco , try to delete and re-create the connections to see if it helps.

**Comment by pigreco** [comment]
> @pigreco , try to delete and re-create the connections to see if it helps.

they are new connections, just made with the update

**Comment by nirvn** [comment]
@pigreco , ah, your windows build is _one commit_ behind the fix :) check again tomorrow.

**Comment by pigreco** [comment]
The problem is always present: I updated the master via OSGeo4W v2, I created a new spatialite database using the browser panel
![image](https://user-images.githubusercontent.com/7631137/140889531-b6fa7da5-4022-47f7-a7f0-25ad67ddcf45.png)

**Comment by gioman** [comment]
> The problem is always present

Confirmed.

**Comment by immoblecher** [comment]
Still not working on Ubuntu 20.04, QGIS 3.22.1 (Ubuntu/Debian), code revision 663dcf8fb9. Create a "home" database with "Database does not exist" under it.
![Screenshot from 2021-12-14 09-32-46](https://user-images.githubusercontent.com/25684536/145961886-2690ae0b-f7e7-4f0c-b8b0-8abb928641f0.png)

**Comment by pigreco** [comment]
> Still not working on Ubuntu 20.04, QGIS 3.22.1 (Ubuntu/Debian), code revision [663dcf8](https://github.com/qgis/QGIS/commit/663dcf8fb916ff888ec86db88aa68023ed9e388a). Create a "home" database with "Database does not exist" under it.

it was fixed 7 hours ago, wait for the next update

**Comment by gioman** [comment]
> it was fixed 7 hours ago, wait for the next update

@immoblecher specifically in 3.22.2 or master.
