### ISSUE TITLE
Cannot build QGIS 3.22 from source using MSVC2015

### ISSUE THREAD

**Issue by thanhgis** [qgis/QGIS#45722]
### What is the bug or the crash?

Trying to build two versions of QGIS: 
1) This works fine with QGIS 3.16.12 LTR source: 
https://github.com/qgis/QGIS/blob/release-3_16/INSTALL.md#4-building-on-windows

2) This does not work (with QGIS 3.22 source), with many errors: 
https://github.com/qgis/QGIS/blob/release-3_22/INSTALL.md#4-building-on-windows

As with my skill, the issues are related to using MSVC2017 or higher to build this QGIS version (the c++17 is required). 

### Steps to reproduce the issue

Following up exactly steps in this guidance: 
https://github.com/qgis/QGIS/blob/release-3_22/INSTALL.md#4-building-on-windows

### Versions

QGIS 3.22 

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Is it still not official release of QGIS 3.22 source, so the errors exist?

**Comment by jef-n** [comment]
3.22 is built with MSVC2019.
