### ISSUE TITLE
Record SQL query's to Debugging/Development tool

### ISSUE THREAD

**Issue by ar-siddiqui** [qgis/QGIS#45733]
### Feature description

Debugging Tools are great because they increase the awareness of end-user on how QGIS works and what is going on in the backdrop. 

I am working with PostGIS layers and they are very slow, though some layers only contain 350 odd features still map takes a second or two to render them each time. I am trying to understand what is going on. Is QGIS sending a new query every time I pan? I don't think so but then why QGIS is slow with PostGIS layers after they are loaded, unlike WFS layers. One would assume QGIS would have everything in memory after a layer is loaded and would not communicate with the Database unless you edit a layer and save, or do refresh etc. 

To be able to debug what is going on it would be helpful to have QGIS record DB requests in Debugging Panel as well like how WMS/WFS requests are recorded.

**Comment by uclaros** [comment]
The database is queried on each map extent change to reflect changes in the data as they might have been modified. What is not updated though is the snapping cache.

I'm closing this as it's the same as #45319

**Comment by ar-siddiqui** [comment]
@uclaros thanks for pointing out duplicate. Is there a way to turn of auto refresh? If not I will file a separate feture request for that if it doesn't exist yet.

**Comment by Gustry** [comment]
> Is there a way to turn of auto refresh?

Not the best, but the "rendering" checkbox at the bottom of the main dialog?
