### ISSUE TITLE
Use online SVG icons

### ISSUE THREAD

**Issue by cbertelli** [qgis/QGIS#45739]
### Feature description

I don't know if it's only an interface problem, but I cannot use SVG icons stored on a web server. I think this may suggest some safety concerns – better limiting to https.
Another – maybe better – solution is storing them in the database (PostgreSQL handles XML very well and other DBMS do as well).

### Additional context

Sharing a project using SVGs not already included in QGIS is a nightmare. This asks for a solution. I don't think storing SVGs into projects could be a good idea.
Extending standard icons could be a solution but this also suggests theming them, having several icon sets. Keeping them online helps control and usage.

**Comment by gioman** [comment]
> Another – maybe better – solution is storing them in the database (PostgreSQL handles XML very well and other DBMS do as well).

@cbertelli you can already store SVGs in QGIS projects.

**Comment by gioman** [comment]
@cbertelli as also load SVGs from URLs

![image](https://user-images.githubusercontent.com/1951107/139535607-98c53112-65ad-4939-bf45-adfa3e77157e.png)
