### ISSUE TITLE
QGIS can't correctly save PostGIS layer with JSON field after addition of record(s)

### ISSUE THREAD

**Issue by ar-siddiqui** [qgis/QGIS#45732]
### What is the bug or the crash?

I have a PostGIS layer, which has a non-nullable JSON field. When I try to add record(s) to it it works fine until I hit the save button. I get weird behaviours, I am listing some of them down

1. Layer will save but JSON field will be empty

![image](https://user-images.githubusercontent.com/53625184/139494669-fc568af5-c138-4cce-b9e1-96519a816a66.png)

![image](https://user-images.githubusercontent.com/53625184/139494674-7a670a06-9c90-4482-8e65-3e8ac406a54c.png)

2. Layer will not save returning an error message.

3. Layer will save correctly.

### Steps to reproduce the issue

Load a writable PostGIS layer with a non-nullable JSON field. Add more rows to it and hit save. 

### Versions

QGIS 3.16.11

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@ar-siddiqui I cannot replicate, can you post the SQL for your table?

**Comment by ar-siddiqui** [comment]
I am still encountering this issue 3.22.4.

Here is more debugging info 

```sql
CREATE TABLE staging.collections (
	collection_id serial4 NOT NULL,
	title text NOT NULL,
	description text NOT NULL,
	"source" text NOT NULL,
	notes json NOT NULL,
	s3_prefix text NOT NULL,
	s3_staging_prefix text NOT NULL,
	geocontext_entities _text NULL,
	rfpg json NULL,
	approved bool NOT NULL DEFAULT false,
	rfpg_new text NULL,
	collection_tag text NULL,
	s3_zip_path text NULL,
	CONSTRAINT collections_pkey PRIMARY KEY (collection_id),
	CONSTRAINT collections_title_key UNIQUE (title)
);
```

Record added  with data for `notes`:
![image](https://user-images.githubusercontent.com/53625184/157984416-a40f021f-1ee7-4ac8-9b03-7e01e27608b6.png)

At layer save, error message on `notes` column:
![image](https://user-images.githubusercontent.com/53625184/157984457-1c08c4f6-d83b-49e7-899b-f98f70beaba4.png)

**Comment by ar-siddiqui** [comment]
> @ar-siddiqui I cannot replicate, can you post the SQL for your table?

@gioman SQL posted

**Comment by gioman** [comment]
> @gioman SQL posted

@ar-siddiqui I still can't replicate. You may want send a sample of your table (dump format).
