### ISSUE TITLE
Snapping tolerance widget does not allow to insert a number in C Locale when comma is the decimal separator

### ISSUE THREAD

**Issue by SrNetoChan** [qgis/QGIS#45746]
### What is the bug or the crash?

The snapping tolerance widget (when in map units) does not allow to insert C Locale when the decimal separator of the locale is a comma. Two different behaviors were observed. For PT_pt locale, it was not possible to even insert a dot (.) in the number.

https://user-images.githubusercontent.com/3607161/139561618-1c1db1d9-27f6-413b-8863-d402b30cd10d.mp4

For the IT Locale, it was possible to insert a dot (.) but once you press the enter key or lose focus on the widget the number will ignore the dot as a decimal separator.

https://user-images.githubusercontent.com/3607161/139561629-823c0f21-655b-43ee-9990-8f94df8bbfd3.mp4

### Steps to reproduce the issue

1. In options, set either the Portuguese_Portugal locale or the Italy_Italian locale
2. Go to Project > Snapping Settings
3. If not available, turn the Snapping toolbar visible
4. Change tolerance from pixels to whatever mp units you project is using
5. Try to insert a dot to represent the decimal separator

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.0-Białowieża | QGIS code revision | d9022691f1
-- | -- | -- | --
Qt version | 5.12.8
Python version | 3.8.10
GDAL/OGR version | 3.0.4
PROJ version | 6.3.1
EPSG Registry database version | v9.8.6 (2020-01-22)
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
SQLite version | 3.31.1
PDAL version | 2.0.1
PostgreSQL client version | 12.8 (Ubuntu 12.8-0ubuntu0.20.04.1)
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.2
OS version | Ubuntu 20.04.3 LTS
  |   |   |  
Active Python plugins
qgis2CartTop | 0.1
sagaprovider | 2.12.99
db_manager | 0.1.20
processing | 2.12.99
MetaSearch | 0.3.5
grassprovider | 2.12.99

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by elpaso** [comment]
I cannot reproduce on current master, I think this is now fixed.
