### ISSUE TITLE
Export image only in png format

### ISSUE THREAD

**Issue by aghezz** [qgis/QGIS#45743]
### What is the bug or the crash?

I Have Linux Mint and Qgis 3.16.11 Hannover. When I try to export as an image, Qgis only saves in PNG format, even if I select jpg or jpeg. (es. save to "project.jpg.png"). Similarly, when I try to save the project, the extension is always .qgs even if I set .qgz. 

### Steps to reproduce the issue

![DeepinScreenshot_seleziona-area_20211030202401](https://user-images.githubusercontent.com/25877030/139554162-d1ea0548-3801-450b-9cbf-604f6faaa490.png)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

Versione di QGIS | 3.16.11-Hannover | Revisione codice QGIS | 26cc1c76
-- | -- | -- | --
Compilato con Qt | 5.15.3 | Esecuzione con Qt | 5.15.3
Compilato con GDAL/OGR | 3.2.1 | Esecuzione con GDAL/OGR | 3.2.1
Compilato con GEOS | 3.8.1-CAPI-1.13.3 | Esecuzione con GEOS | 3.8.1-CAPI-1.13.3
Compilato su SQLite | 3.32.1 | In esecuzione su SQLite | 3.32.1
Versione client PostgreSQL | 12.2 | Versione SpatiaLite | 4.3.0a
Versione QWT | 6.1.5 | Versione QScintilla2 | 2.11.6
Compilato con PROJ | 6.3.2 | Esecuzione con PROJ | Rel. 6.3.2, May 1st, 2020
Versione SO | KDE Flatpak runtime
Attiva python plugin | nominatim; quick_map_services; OSMDownloader; QuickOSM; processing; db_manager; MetaSearch

</body></html>

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
@aghezz can't confirm here. QGIS 3.16.12, Mint 20.02. QGIS is installed from the QGIS.org's PPA.

**Comment by kannes** [comment]
Please show the exact steps you take with screenshots.

**Comment by aghezz** [comment]
from print layout, "export as image", write file name "test", choose format file jpeg, but qgis save to png... :(

![DeepinScreenshot_seleziona-area_20211103091052](https://user-images.githubusercontent.com/25877030/140027514-2064fee5-36ef-4510-9d23-564105d6a7fa.png)
![DeepinScreenshot_seleziona-area_20211103091703](https://user-images.githubusercontent.com/25877030/140027691-73c2c6ce-6fed-4dc3-8a82-84b6b164cfe9.png)

(

**Comment by gioman** [comment]
> from print layout, "export as image", write file name "test", choose format file jpeg, but qgis save to png... :( 

@aghezz still working as expected here, same OS and QGIS version.

**Comment by aghezz** [comment]
test on linux mint and qgis 3.22.0-Białowieża

**Comment by gioman** [comment]
> test on linux mint and qgis 3.22.0-Białowieża

@aghezz is a question or a statement?

**Comment by aghezz** [comment]
statement. It is also impossible to save projects in .qgz, projects are only saved in .qgs format despite specifying the .qgz format

**Comment by gioman** [comment]
> statement. It is also impossible to save projects in .qgz, projects are only saved in .qgs format despite specifying the .qgz format

@aghezz can you test installing QGIS using qgis.org's repos instead of flatpak?

**Comment by aghezz** [comment]
already done, the problem remains identified :(

**Comment by gioman** [comment]
< already done, the problem remains identified :( 

@aghezz but not confirmed

**Comment by kannes** [comment]
What does "file filename.jpeg" say when you run that command in the same directory in a terminal? 

Does anything get printed to the terminal if you save a image or project when QGIS was launched in a terminal?

**Comment by gioman** [comment]
> What does "file filename.jpeg

```
file Layout1.jpeg 
Layout1.jpeg: JPEG image data, JFIF standard 1.01, resolution (DPI), density 300x300, segment length 16, comment: "Author: qgis", comment: "Created: 2021-10-30T21:01:59", comment: "Creator: QGIS 3.16.12-Hannover", comment: "Keywords: ", comment: "Producer: QGIS 3.16.12-Hannover", comment: "Subject: ", comment: "Title: ", baseline, precision 8, 3507x2480, components 3
```

**Comment by kannes** [comment]
I meant @aghezz , maybe the written file is just named .jpeg but is a PNG on their system for some weird reason.

**Comment by aghezz** [comment]
problema resta immutato, con versione Odense tutto ok, salva in vari formati, ma usando ultima versione 3.22.0-Białowieża tutti i file esportati dal layout di stampa assumono estensione png anche se imposto jpg. Allo stesso modo, anche i file progetto NON si salvano in formato qgz, ma solo qgs
![da la](https://user-images.githubusercontent.com/25877030/143768439-9343e201-7ca8-4860-84d3-ac513d9ae49d.png)

**Comment by kannes** [comment]
Huh, weird!
Does the same happen in a fresh profile and a completely new project?

**Comment by aghezz** [comment]
succede con profilo vecchio e anche con profilo nuovo... :(

**Comment by gioman** [comment]
> problema resta immutato, con versione Odense tutto ok, salva in vari formati, ma usando ultima versione 3.22.0-Białowieża tutti i file esportati dal layout di stampa assumono estensione png anche se imposto jpg. Allo stesso modo, anche i file progetto NON si salvano in formato qgz, ma solo qgs

@aghezz please post in English. This is likely to be a local issue (as clearly is not a general one), probably at a desktop manager level. Can you test on a different machine?

**Comment by aghezz** [comment]
I tried another version of Qgis (Odense) no problem, it also saves perfectly in jpg. Trying again with .22.0-Białowieża here is again the impossibility to save in jpg, save only in png even if set jpg

**Comment by gioman** [comment]
> Trying again with .22.0-Białowieża here is again the impossibility to save in jpg, save only in png even if set jpg

@aghezz just tested again on 3.22.1 on a Linux Mint 20.2 machine and still cannot confirm.

**Comment by aghezz** [comment]
and what can it depend on? It seems very strange that with Odense everything works perfectly, while with Bielovieza the saving of files in jpg does not work, but only in png

**Comment by gioman** [comment]
> and what can it depend on? It seems very strange that with Odense everything works perfectly, while with Bielovieza the saving of files in jpg does not work, but only in png

@aghezz have you tried o a different machine (it can even be a VM)?
