### ISSUE TITLE
QGIS server leaflet zoom after 19 and language

### ISSUE THREAD

**Issue by cazitouni** [qgis/QGIS#45768]
### What is the bug or the crash?

Impossible to change the language of qgis-server even after setting the environement variable in systemd service
And the webview seem unable to render wms layers after zoom 19.

server is deployed at igp.metrotopic.net is you want to test it 

### Steps to reproduce the issue

Opening a wms layer on wgis-server web and zoom

### Versions

3.22

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
@cazitouni maybe it is just me, but this is really unclear to me.

**Comment by cazitouni** [comment]
Oh sorry, maybe I'm unclear English is not my native language. 

I tired to install and use qgis server on a vps but I actually encounter two problems : 

1  - With the default viewer on the web I'm unable to zoom over zoom 19, the map just disapear. Someone apparently had this issue as well some times ago.  [issue](https://github.com/qgis/QGIS/issues/30031). The map shows well if I look at it in Qgis desktop via WMS. 

2 - It seem impossible on my config to change the language despite modifying the Lang environment variable in the systemd service file related to my qgis server. Everything just seems to stay in english. 

Maybe it's unrelated to Qgis I don't know.

**Comment by gioman** [comment]
> 1 - With the default viewer on the web I'm unable to zoom over zoom 19, the map just disapear. Someone apparently had this issue as well some times ago. [issue](https://github.com/qgis/QGIS/issues/30031). The map shows well if I look at it in Qgis desktop via WMS.

@cazitouni can you provide a URL of a WMS service?



> 2 - It seem impossible on my config to change the language despite modifying the Lang environment variable in the systemd service file related to my qgis server. Everything just seems to stay in english.

@cazitouni language of what? the labels in the WMS layer?

**Comment by cazitouni** [comment]
> > 1 - With the default viewer on the web I'm unable to zoom over zoom 19, the map just disapear. Someone apparently had this issue as well some times ago. [issue](https://github.com/qgis/QGIS/issues/30031). The map shows well if I look at it in Qgis desktop via WMS.
> 
> @cazitouni can you provide a URL of a WMS service?

@gioman https://igp.metrotopic.net/index.html#/map/ca5c9170cce79e4d0d67924e9e164ac3. If I use the wms service in qgis everything's fine
> > 2 - It seem impossible on my config to change the language despite modifying the Lang environment variable in the systemd service file related to my qgis server. Everything just seems to stay in english.
> 
> @cazitouni language of what? the labels in the WMS layer?

Language of the default front-end but maybe it's quite unrelated, but is there a way to change it ?

**Comment by cazitouni** [comment]
Found a solution by adding maxZoom and maxNativeZoom parameters in the wmsSource.source() function of the WebGis.vue and Catalog.vue files.
I don't know if it is the proper way to do it but it just works for me. 

@gioman  Thanks you for the quick answer and all your work on the Qgis project.

**Comment by elpaso** [comment]
Can you make a PR with your changes?

**Comment by cazitouni** [comment]
@elpaso 
I can do that, but I do not guarantee anything, I'm not a pro developer.

Thanks you.
