### ISSUE TITLE
Force close while using GFA

### ISSUE THREAD

**Issue by HanniYolina** [qgis/QGIS#45790]
### What is the bug or the crash?

I tried to use plugin GFA on QGIS but it force closed. 
Data size is only 1kb. So i think it's not about data size. 

Is GFA not supported anymore? 

### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/45839432/139805447-adff1b7a-27f5-4d16-a24e-988065371d1d.png)

### Versions

QGIS 2.18

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@HanniYolina you have to report this to the plugin author/s.
