### ISSUE TITLE
QGIS 3.16.12 crashes when addins any local source layer

### ISSUE THREAD

**Issue by akudekar** [qgis/QGIS#45837]
## User Feedback

Adding shapefiles directly from a local source. Drag ad drop, Add Vector layer, opening a QGS file with shapes all crash

## Report Details

**Crash ID**: [21c755ab40cddf50791191317be623700230182d](https://github.com/qgis/QGIS/search?q=21c755ab40cddf50791191317be623700230182d&type=Issues)

**Stack Trace**
<pre>
QgsStyleProxyModel::QgsStyleProxyModel :
QgsStyleItemsListWidget::setStyle :
QgsSymbolsListWidget::QgsSymbolsListWidget :
QgsSymbolSelectorWidget::layerChanged :
QObject::qt_static_metacall :
QItemSelectionModel::setCurrentIndex :
QAbstractItemView::setCurrentIndex :
QgsSymbolSelectorWidget::loadSymbol :
QgsSymbolSelectorWidget::QgsSymbolSelectorWidget :
QgsSingleSymbolRendererWidget::QgsSingleSymbolRendererWidget :
QgsSingleSymbolRendererWidget::create :
QgsRendererPropertiesDialog::rendererChanged :
QObject::qt_static_metacall :
QWidgetLineControl::`default constructor closure' :
QComboBox::setCurrentIndex :
QComboBox::setCurrentIndex :
QgsRendererPropertiesDialog::syncToLayer :
QgsRendererPropertiesDialog::QgsRendererPropertiesDialog :
QgsLayerStylingWidget::updateCurrentWidgetLayer :
QObject::qt_static_metacall :
QListWidgetItem::`default constructor closure' :
QObject::qt_static_metacall :
QItemSelectionModel::setCurrentIndex :
QListWidget::setCurrentRow :
QgsLayerStylingWidget::setLayer :
QObject::qt_static_metacall :
QgsMapLayerComboBox::layerChanged :
QObject::qt_static_metacall :
QAbstractItemModel::endInsertRows :
QSortFilterProxyModel::insertRows :
QSortFilterProxyModel::sortRoleChanged :
QSortFilterProxyModel::qt_static_metacall :
QObject::qt_static_metacall :
QAbstractItemModel::endInsertRows :
QgsMapLayerModel::addLayers :
QObject::qt_static_metacall :
QgsProject::layersAdded :
QObject::qt_static_metacall :
QgsMapLayerStore::layersAdded :
QgsMapLayerStore::addMapLayers :
QgsProject::addMapLayers :
QgsProject::addLayer :
QgsProject::_getMapLayers :
QgsProject::readProjectFile :
QgsProject::read :
QgisApp::addProject :
QgisApp::openProject :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.16.12-Hannover
QGIS code revision: be6cb030
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.2
Running against GDAL: 3.3.3

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

### Steps to reproduce the issue

Add local source layer

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.16.12-Hannover | QGIS code revision | be6cb030
-- | -- | -- | --
Compiled against Qt | 5.15.2 | Running against Qt | 5.15.2
Compiled against GDAL/OGR | 3.3.2 | Running against GDAL/OGR | 3.3.3
Compiled against GEOS | 3.10.0-CAPI-1.16.0 | Running against GEOS | 3.10.0-CAPI-1.16.0
Compiled against SQLite | 3.35.2 | Running against SQLite | 3.35.2
PostgreSQL Client Version | 13.0 | SpatiaLite Version | 5.0.1
QWT Version | 6.1.3 | QScintilla2 Version | 2.11.5
Compiled against PROJ | 8.1.1 | Running against PROJ | Rel. 8.1.1, September 1st, 2021
OS Version | Windows 10 Version 2009
Active python plugins | lizmap; ORStools; pluginbuilder3; plugin_reloader; qgis-maptiler-plugin; QuickOSM; quick_map_services; VectorMCDA; db_manager; LocalSupplyIndex; MetaSearch; processing

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
> Active python plugins 	lizmap; ORStools; pluginbuilder3; plugin_reloader; qgis-maptiler-plugin; QuickOSM; quick_map_services; VectorMCDA; db_manager; LocalSupplyIndex; MetaSearch; processing

@akudekar please try with a new QGIS profile.

**Comment by elpaso** [comment]
No issues here on linux/master.

**Comment by akudekar** [comment]
@gioman works. Thanks a lot.
