### ISSUE TITLE
Couldn't load plugin 'VectorFieldCalc' due to an error when calling its classFactory() method

### ISSUE THREAD

**Issue by cmegarcia** [qgis/QGIS#45840]
### What is the bug or the crash?

Hi,
I'm having a little not so little issue. I would like to use the Vector menu of QGIS but there are none of the "by default" plugin that work. I get this message error every time I want to use it. Additionally, there is the data management tools that I would like to use that does not show up.
I tried reinstalling the plugins but nothing changed, even if the command say it is successfully installed.
I would greatly appreciate any input on this issue :) 
All the best

Message:
Couldn't load plugin 'VectorFieldCalc' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'gdal' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS31~1.12/apps/qgis-ltr/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/-/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\VectorFieldCalc\__init__.py", line 29, in classFactory
    from .vfc_main import VectorFieldCal
  File "C:\PROGRA~1/QGIS31~1.12/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/-/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\VectorFieldCalc\vfc_main.py", line 17, in 
    from .main_dialog import MainDialog, HelpDialog
  File "C:\PROGRA~1/QGIS31~1.12/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/-AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\VectorFieldCalc\main_dialog.py", line 17, in 
    from .qgis_utils.qgs import *
  File "C:\PROGRA~1/QGIS31~1.12/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/-/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\VectorFieldCalc\qgis_utils\qgs.py", line 16, in 
    from ..pygsf.libs_utils.gdal.gdal import *
  File "C:\PROGRA~1/QGIS31~1.12/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/-/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\VectorFieldCalc\pygsf\libs_utils\gdal\gdal.py", line 12, in 
    import gdal
  File "C:\PROGRA~1/QGIS31~1.12/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'gdal'

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.16.12-Hannover Hannover, be6cb030 

Python Path:
C:/PROGRA~1/QGIS31~1.12/apps/qgis-ltr/./python
C:/Users/-/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/-/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS31~1.12/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS31~1.12\bin\python39.zip
C:\PROGRA~1\QGIS31~1.12\apps\Python39\DLLs
C:\PROGRA~1\QGIS31~1.12\apps\Python39\lib
C:\PROGRA~1\QGIS31~1.12\bin
C:\PROGRA~1\QGIS31~1.12\apps\Python39
C:\PROGRA~1\QGIS31~1.12\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS31~1.12\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS31~1.12\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS31~1.12\apps\Python39\lib\site-packages\Pythonwin
C:/Users/-/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\-\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\vector_tiles_reader\ext-libs
C:/Users/-/Desktop/3_PhD/31_PhD/313_Kersa/5_QGIS-project

<img width="566" alt="Capture" src="https://user-images.githubusercontent.com/93668803/140097282-e2a6172b-c2f0-4a6e-bd84-82af42cc0cde.PNG">
<img width="567" alt="Capture2" src="https://user-images.githubusercontent.com/93668803/140097428-bbfcd83d-f5de-4c28-a1f9-89c7f58a0a8e.PNG">

### Steps to reproduce the issue

1. Plugins
2. Manage and install plugins
3. Installed

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.16.12-Hannover | QGIS code revision | be6cb030
-- | -- | -- | --
Compiled against Qt | 5.15.2 | Running against Qt | 5.15.2
Compiled against GDAL/OGR | 3.3.2 | Running against GDAL/OGR | 3.3.2
Compiled against GEOS | 3.10.0-CAPI-1.16.0 | Running against GEOS | 3.10.0-CAPI-1.16.0
Compiled against SQLite | 3.35.2 | Running against SQLite | 3.35.2
PostgreSQL Client Version | 13.0 | SpatiaLite Version | 5.0.1
QWT Version | 6.1.3 | QScintilla2 Version | 2.11.5
Compiled against PROJ | 8.1.1 | Running against PROJ | Rel. 8.1.1, September 1st, 2021
OS Version | Windows 10 Version 2004
Active python plugins | VectorFieldLayerManager; VectorMCDA; vector_tiles_reader; db_manager; MetaSearch

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@cmegarcia you must report the problem to the plugin author/s, not here.
