### ISSUE TITLE
Replace with displayed values\Use Value Map not working from Data Source Manager

### ISSUE THREAD

**Issue by Sliverfoot** [qgis/QGIS#45842]
### What is the bug or the crash?

When using Export Layer\To File from the Data Source Manager, the function to Select fields to export and their export options\Replace with displayed values\Use Value Map does not work.  It does not replace with displayed values.  But it does work if you do it from the Table of Contents\right-click layer\Export\Save Feature As.

### Steps to reproduce the issue

Use a layer which has a Value Map Widget.  In Data Source Manager right-click on a layer, select Export Layer\To File.  In the Encoding box, under Select fields to export and their export options\Replace with displayed values click the Use Value Map option.  It does not replace with displayed values.  But it does work if you do it from the Table of Contents\right-click layer\Export\Save Feature As.

### Versions

QGIS version
3.22.0-Białowieża
QGIS code revision
d9022691f1
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.2
PROJ version
8.1.1
EPSG Registry database version
v10.028 (2021-07-07)
GEOS version
3.10.0-CAPI-1.16.0
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2004

Active Python plugins
changeDataSource
3.1
clipper
1.0
FreehandRasterGeoreferencer
0.8.3
mapswipetool_plugin
1.2
MultipleLayerSelection
2.0
quick_map_services
0.19.19
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
> In Data Source Manager

@Sliverfoot do you mean the QGIS Browser, correct?

**Comment by Sliverfoot** [comment]
I mean the Data Source Manager:
![image](https://user-images.githubusercontent.com/93669087/140165844-541f43e2-65b8-4615-aff0-f6cddc3262b5.png)

**Comment by Sliverfoot** [comment]
The Data Source Manager and the Browser appear to be the same thing.

**Comment by gioman** [comment]
> I mean the Data Source Manager:

@Sliverfoot yeah, but then (after you open the data source manager) you choose the first option, which is "browser", correct?

**Comment by gioman** [comment]
> The Data Source Manager and the Browser appear to be the same thing.

@Sliverfoot ummm, my take is that you can access the Browser from the datasource manager, but they are not the same thing. Anyway... a layer in the DSM/Browser is **not** a project layer, so QGIS have no idea that it may be loaded in a project and that has some widgets applied to it, this is why you don't get the values replaced...

**Comment by Sliverfoot** [comment]
Are there cases where "Replace with displayed values\Use Value Map" does work from the Browser??

**Comment by gioman** [comment]
> Are there cases where "Replace with displayed values\Use Value Map" does work from the Browser??

@Sliverfoot If I had to guess I would say no.

**Comment by Sliverfoot** [comment]
Then I think it would be a good idea to get rid of that option in the Brower window.

**Comment by gioman** [comment]
> Then I think it would be a good idea to get rid of that option in the Brower window.

@Sliverfoot there are many good reasons why a user could want to export a layer from the datasource manager. Can we close this?

**Comment by Sliverfoot** [comment]
But right now, using my example, the function is available to use in data source manager but in actuality it does not work...and the user would not know this unless they double checked the output.

**Comment by gioman** [comment]
> But right now, using my example, the function is available to use in data source manager but in actuality it does not work...and the user would not know this unless they double checked the output.

@Sliverfoot my take is the user also must understand how things work, in this case that the data source manager shows datasources that are **not** project layers.
