### ISSUE TITLE
Mesh Editing: Unable to start mesh editing

### ISSUE THREAD

**Issue by sharon92** [qgis/QGIS#45864]
### What is the bug or the crash?

QGIS 3.22 is unable to start mesh editing on a 2dm File.

### Steps to reproduce the issue

1. Import existing 2dm File
2. Click on Edit
3. Error: Mesh Editing: Unable to start mesh editing (for both the options "Edit current layer" and "Edit a copy")

### Versions

QGIS version
3.22.0-Białowieża
QGIS code revision
d9022691f1
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.2
PROJ version
8.1.1
EPSG Registry database version
v10.028 (2021-07-07)
GEOS version
3.10.0-CAPI-1.16.0
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2004

Active Python plugins
qgis2web
3.16.0
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
> on a 2dm File.

@sharon92 can you please attach/link your dataset?

**Comment by sharon92** [comment]
[test.txt](https://github.com/qgis/QGIS/files/7473530/test.txt)

@gioman I have renamed the file as txt to upload the attachment. You need to rename again with the extension .2dm

**Comment by saberraz** [comment]
I can confirm the bug. @vcloarec would you mind having a look?

**Comment by vcloarec** [comment]
@sharon92 , you have a quad face that is convex, this is forbidden for mesh editing:

![image](https://user-images.githubusercontent.com/7416892/140304279-acb27770-5f38-4369-abc4-636ac92f7196.png)

If mesh can't start editing, go to "Log messages"--> "General". Here you can see a message with the error in the mesh. 

Be careful, with 2dm, indexing starts at 1, and with QGIS, indexing starts at 0. Here it the face 5691, in the 2dm file, it the face 5692. Remove the line with the face `E4Q 5692 3771 3945 3946 3772`, at line 51714, and you could open the file.

**Comment by sharon92** [comment]
@vcloarec Thanks for pointing this out! In SMS (Aquaveo) I could open and edit it, so I thought this might be a bug in QGIS.

So far, my experience with mesh editing has been great, thanks for all the work!

What annoyed me a little was the fact that saving a mesh file will lose all the existing Model Parameters (for eg. from Hydro_as-2d) and it saves only the geometry of the model. Would this be changed in future, so that it retains the Modell Parameters from the imported file?

**Comment by vcloarec** [comment]
@sharon92 , for my information, what had created this concave face?

> Would this be changed in future, so that it retains the Modell Parameters from the imported file?

Maybe, but it quite tricky to implement for now...

**Comment by saberraz** [comment]
@sharon92 I suggest to close this ticket and open two new ones:
1- How to handle the cases when the mesh contains concave faces: e.g. provide additional tools to automatically remove/fix those faces in QGIS.

2- In regards to removing model parameters: when mesh topology changes, the parameters will no longer be valid. It would be interesting to see how we can apply the parameters from one mesh topology to another one (as @vcloarec mentioned, this will be very tricky to do).

**Comment by sharon92** [comment]
@vcloarec I am in the process of correcting older models, so cases like this is where I would like to use QGIS to correct the elements.

On SMS I can activate Mesh Quality check, highlight these problematic elements, and correct them in editing mode.

![image](https://user-images.githubusercontent.com/51754340/140307491-91672386-e3aa-4050-8509-691ef98ba812.png)

**Comment by sharon92** [comment]
@saberraz 

Okay I will open a feature request?

2.) Yeah for this the Nodestrings and the bridge bottom elevations need to be loaded and updated according to the mesh.
