### ISSUE TITLE
Greate Grid lines output can not be selected as line input in Modeler

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#45867]
### What is the bug or the crash?

When you create lines with the "Create Grid" processing tool in a graphical model, the resulting Algorithm Output is not shown as option in the dropdown of tools that expect lines dialog, e. g. the "Split Layer" for the "Split with lines" tool or the "Input layer" for the "Lines to Polygons" tool.

It is shown as option for the main "Input layer":
![image](https://user-images.githubusercontent.com/7661092/140300112-9f827ad2-74e9-4033-9c9b-9aa4e15b91cc.png)

But not as potential "Split layer":
![image](https://user-images.githubusercontent.com/7661092/140300154-1b492f64-c595-4d2d-98ac-3a0a3fa7fe90.png)

I assume this will be broken for points as well

### Steps to reproduce the issue

1. Use the graphical Modeler
2. Create a Create Grid node and choose Line as Grid Type
3. Create a "Lines to Polygons" node and search for the output of 2 in the "Algorithm Output" list

### Versions

QGIS version | 3.23.0-Master | QGIS code revision | 97b288dceef

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by kannes** [comment]
This should not be affected by a new QGIS profile so I did not test that.

**Comment by kannes** [comment]
I can use the line output from the "Create Grid" tool just fine as input for "Split with lines" if I "Pre-calculated Value" to set the "Split layer" and enter the variable name for the output there (`@Create_grid_OUTPUT` in my case).

**Comment by nicogodet** [comment]
Could be similar to https://github.com/qgis/QGIS/issues/45503 ?

**Comment by kannes** [comment]
That sounds very much related!

I see that the Create Grid algorithm specifies a Polygon type for its output: https://github.com/qgis/QGIS/blob/97b288dceefbda8a91f4eff2f807c78c787c5801/src/analysis/processing/qgsalgorithmgrid.cpp#L67

I *think* the last parameter could be removed, at least that is what the definition for the output of e. g. the "Split by lines" algorithm (which also can return Polygons or Lines) suggests: https://github.com/qgis/QGIS/blob/97b288dceefbda8a91f4eff2f807c78c787c5801/src/analysis/processing/qgsalgorithmsplitwithlines.cpp#L54
