### ISSUE TITLE
Raster Renderer: incorrect boundary value classifying in discrete interpolation with 2-classes

### ISSUE THREAD

**Issue by Kanahiro** [qgis/QGIS#45861]
### What is the bug or the crash?

- boundary value is classified incorrectly in discrete interpolation with 2-classes

### figure 1

![スクリーンショット 2021-11-04 16 39 16](https://user-images.githubusercontent.com/20744195/140275768-5ebf8b23-d1e6-4613-addd-7502891a59a3.png)

- made 1-100 interger raster
- render as discrete interpolation with 2-classes
  - class1: 50 <=
  - class2: 50 <
- **the boundary value `50` is included in class2**, this is incorrect.
  - see `50` pixels in figure 2

### figure 2

![スクリーンショット 2021-11-04 16 39 26](https://user-images.githubusercontent.com/20744195/140276055-b45da58a-a079-4897-a00d-d8364576fe80.png)

### figure 3

![スクリーンショット 2021-11-04 16 39 40](https://user-images.githubusercontent.com/20744195/140276156-d565e535-db95-4f5b-b6ad-f354625ade92.png)

- almost same to figure 1
- a num of classes is only changed, 2 to `3`
  - new class `<= 0` should make no effect on raster rendering
- **the boundary value `50` become included in class1**

These may mean the boundary value is not correctly treated when 2-classes.

### Steps to reproduce the issue

[threshold.zip](https://github.com/qgis/QGIS/files/7473101/threshold.zip)
includes .qgs and .tif

### Versions

I checked QGIS 3.16.10 and 3.22.0, on Windows10 64bit.

QGIS version | 3.16.10-Hannover | QGIS code revision | e5b665e952
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | plugin_reloader; db_manager; MetaSearch; processing

QGISバージョン | 3.22.0-Białowieża | QGISコードリビジョン | d9022691f1
-- | -- | -- | --
Qtバージョン | 5.15.2
Pythonバージョン | 3.9.5
GDAL/OGRバージョン | 3.3.2
PROJバージョン | 8.1.1
EPSG Registry databaseバージョン | v10.028 (2021-07-07)
GEOSバージョン | 3.10.0-CAPI-1.16.0
SQLiteバージョン | 3.35.2
PDALバージョン | 2.3.0
PostgreSQLクライアントバージョン | 13.0
SpatiaLiteバージョン | 5.0.1
QWTバージョン | 6.1.3
QScintilla2バージョン | 2.11.5
OSバージョン | Windows 10 Version 1909
  |   |   |  
Active pythonプラグイン
geospacecds | 3.12
plugin_reloader | 0.8.2
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.5
processing | 2.12.99
sagaprovider | 2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by roya0045** [comment]
I tested and you're right, with the following legend:
![image](https://user-images.githubusercontent.com/12854129/147882576-f496b02d-3489-4b04-9f31-b583851772bd.png)
 7 are included in the 7-13 class and 95 are included in the < 95 class.

Now I don't know if this is because the values are rendered in both classes and the 'last' class renders over the first one, or if the issue is in the UI or min-max handling.

Now what I'm unsure about is wether the `<=` should be changed for `<` and the `>`  changed to `>=` or if the renderer should respect the displayed symbol. @nirvn @nyalldawson  what's your stance on this, fix the UI or fix the render?
