### ISSUE TITLE
Set Layout scale differs from Dynamic text scale

### ISSUE THREAD

**Issue by uclaros** [qgis/QGIS#45877]
### What is the bug or the crash?

On a print layout, the scale returned by Dynamic Text > Map Properties > Scale ( `item_variables('Map 1')['map_scale']` ) is very slightly different from the map scale set on the map item's properties.
When for example setting map scale to 5000,  `item_variables('Map 1')['map_scale']` returns `4999.999994899999`

### Steps to reproduce the issue

Open the layout of the attached project:
[grid_labels.zip](https://github.com/qgis/QGIS/files/7477628/grid_labels.zip)

### Versions

ef3983ce5c on Debian bullseye

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

This is probably related to #45876

**Comment by agiudiceandrea** [comment]
@uclaros, see https://github.com/qgis/QGIS/pull/51768.

**Comment by uclaros** [comment]
Thanks!
