### ISSUE TITLE
Join not working as expected with embedded layers/tables

### ISSUE THREAD

**Issue by romain-jault** [qgis/QGIS#45872]
### What is the bug or the crash?

Hi,

I have created a qgis project with two joined layers. I would like to use it as an integrated project. if the layers are contained in a layer group, the child project doesn't expose the joins between the layers.

### Steps to reproduce the issue

To check if the joins can be integrated into a child project

The functional way with no layer group :
1. Open an QGIS project
2. load layers linked by a foreign key
3. join them in the layer's properties
4. save the project
5. Open a new project
6. Integrate all the layers from the previous project
7. Save the new project
8. reload the new project 
9. you will notice the joins are imported
----------------------------------------------
The problematic way with layer group
1. Open an QGIS project
2. load layers related by a foreign key
3. join them
4. Set the joined layers into a layer group
5. save the project
6. Open a new project
7. Integrated all the layers from the previous project
8. Save the new project
9. reload the new project 
10. you will notice the joins are not imported

### Versions

Version de QGIS 3.20.3-Odense
Révision du code 495fbaec
Version de Qt 5.15.2
Version de Python 3.9.5
Version de GDAL/OGR 3.3.1
Version de GEOS 3.9.1-CAPI-1.14.2
Version de PDAL 2.3.0
Version de l'OS Windows 10 Version 2009

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
> The problematic way with layer group

@romain-jault can you a sample project with sample data? thanks.

**Comment by romain-jault** [comment]
Hello, here I am,

You will find in the zip folder, 2 Qgis projects:
	the main project with 6 layers to simulate joins.
		- 3 layers are in a group
		- the 3 others are not.

The 3 layers are called LAYER_A/LAYER_B/LAYER_C. I have created joins with the layer C and the two others layers. To do so, the layer C contains foreign keys to the 2 others layers. I have joined the columns LAYER_C.FID_A and LAYER_C.FID_B to the OBJECTID columns of the others layers.

	The related project integrates the layers of the main project.

As you can notice in the related project, only the joins of the layers set outside of the group can be seen.

I am available for any other question or observation.

Regards.


[QGIS_ISSUES_45872.zip](https://github.com/qgis/QGIS/files/7482503/QGIS_ISSUES_45872.zip)

**Comment by gioman** [comment]
> Hello, here I am,

@romain-jault thanks, I edited the title to be clearer. It sound ok for you?

**Comment by romain-jault** [comment]
>  Hello, here I am,

@gioman, Hello, sorry for the late answer, no problem for me specially if it can help to improve    @##QGIS.
