### ISSUE TITLE
Broken link to GPKG driver help page in Data Source Manager / Vector

### ISSUE THREAD

**Issue by NReadMMCD** [qgis/QGIS#45875]
### What is the bug or the crash?

In Data Source Manager / Vector page under Options there is a link titled 
GPKG driver help page that currently points to 
https://gdal.org/drivers/vector/geopackage.html
This gives a 404 error.
It looks like the appropriate address should be
https://gdal.org/drivers/vector/gpkg.html#vector-gpkg

### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/74696284/140379223-f2abfe9a-a347-41a5-864d-4b032287a035.png)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.0-Białowieża | QGIS code revision | d9022691f1
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.10.0-CAPI-1.16.0
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 1903
  |   |   |  
Active Python plugins
DataPlotly | 3.7.1
GroupStats | 2.2.5
SpreadsheetLayers | 2.0.1
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.5
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
I think the issue is upstream in the GDAL/OGR library. See https://github.com/OSGeo/gdal/pull/4768.

**Comment by agiudiceandrea** [comment]
Fixed upstream with https://github.com/OSGeo/gdal/pull/4768 and https://github.com/OSGeo/gdal/pull/4773
