### ISSUE TITLE
LAS with extra dimensions fails to get indexed

### ISSUE THREAD

**Issue by ericgyounkin** [qgis/QGIS#45903]
### What is the bug or the crash?

I have a LAS that I have generated using laspy adding an extra float dimension ('uncertainty').  Example file below:

[LAS example with 'uncertainty' dimension added](https://drive.google.com/file/d/1LkY08eGLXjvBrV4eR-UzDVQz2hL_kufS/view?usp=sharing)

This file can be opened in laspy, LASTools and can be converted using 'entwine build' on the console to generate entwine data that can be dragged into QGIS for visualization.  What I can't seem to get work is dragging in the LAS file to QGIS to build the Entwine automatically.  It generates the Entwine directories but no conversion happens. 

### Steps to reproduce the issue

Download [LAS example with 'uncertainty' dimension added](https://drive.google.com/file/d/1LkY08eGLXjvBrV4eR-UzDVQz2hL_kufS/view?usp=sharing)

Drag file into QGIS

Only the bounds/metadata will show for the entwine data

### Versions

QGIS version
3.20.2-Odense
QGIS code revision
9f59a156
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.1
PROJ version
8.1.0
EPSG Registry database version
v10.027 (2021-06-17)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
cruisetools
LAStools
quick_map_services
db_manager
MetaSearch
processing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Any error in log ?

Is it similar to https://github.com/qgis/QGIS/issues/41833 ?

**Comment by wonder-sk** [comment]
Looks like upstream bug in untwine - https://github.com/hobu/untwine/issues/93

**Comment by wonder-sk** [comment]
The issue does not happen upstream anymore with PDAL 2.4 (yet to be released) + laz-perf 3.0 + untwine main branch. We just need to:
- pull new version of untwine to QGIS
- pull new version of laz-perf to QGIS
- update QGIS packaging to use PDAL 2.4 as a minimum

**Comment by alexbruy** [comment]
@ericgyounkin the link to the test data is not working. Can you test with the latest master?
