### ISSUE TITLE
Browser takes long to scan folder with large number of files

### ISSUE THREAD

**Issue by dkelsey** [qgis/QGIS#45914]
### What is the bug or the crash?

hasn't crashed yet... I'm simply waiting for it to return after I clicked my 'Downloads' folder.
722 files in my DL folder, only a handful have anything to do wth Spatial data.
<img width="1533" alt="Screen Shot 2021-11-05 at 9 33 26 PM" src="https://user-images.githubusercontent.com/3906047/140598170-e78fa705-e48a-4bfc-b428-ef80c87bd01b.png">

### Steps to reproduce the issue

1. DL 3.22.0-Białowieża
2. start it.
3. Nav in the left menu and attempt to open my Downloads folder

## EXPECTED
I'd "see" the contents of my Downloads foder and I'd be able to add/import the stupid KML i'm trying to view :)

## Actual
it hangs and never opens.

### Versions

3.22.0-Białowieża

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by dkelsey** [comment]
In the time it too me to file the bug... it finished.

**Comment by gioman** [comment]
@dkelsey do you have many zip files in that folder?

**Comment by dkelsey** [comment]
Thanks @gioman ... there are a few:
```bash

$ ls *.*z*| wc -l
     129
 $ ls *.z*| wc -l
      73
$ ls * | wc -l
    1114
```
I should clarify; after the folder was scanned i was able to quickly find and add the KML to a new project.

**Comment by gioman** [comment]
> there are a few:

So maybe it tool long because of this general setting:

![image](https://user-images.githubusercontent.com/1951107/140622760-06f9bfc8-87a6-43b9-90fc-5b2a2b165337.png)

**Comment by dkelsey** [comment]
Closing.  I'm satisfied.
