### ISSUE TITLE
connection to Postgres 14.x :not possible to connect to schema

### ISSUE THREAD

**Issue by enzococca** [qgis/QGIS#45919]
### What is the bug or the crash?

Bug

### Steps to reproduce the issue

when try to connect to postgres14.x via db manager o browser , the connection works but it doesn't show the schema so I can't see and load  the table and geometry  into QGIS

### Versions

QGIS 3.22-03 via OSGEOW 
Windows 10

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
> QGIS 3.22-03 via OSGEOW
> Windows 10

@enzococca same setup here, and cannot confirm (server is Ubuntu 20.04 with PostgreSQL 14 and PostGIS 3). Works fine in browser, database manager and data source manager and processing.
