### ISSUE TITLE
Qgis unexpectedly ended

### ISSUE THREAD

**Issue by Vale1900** [qgis/QGIS#45934]
### What is the bug or the crash?

I uninstalled Qgis (LTR 3.16.12) because suddenly some functions were no longer active (!)
I reinstalled Qgis in the last LTR (3.16.13)  but when I try to open any project, it crashes, the warning "Qgis unexpectedly ended" appears 

### Steps to reproduce the issue

    Go to 'any Qgis project'
    Click on 'Open'
    Scroll down to '...'
    See error "Qgis unexpectedly ended"

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

Versione di QGIS | 3.16.13-Hannover | Revisione codice QGIS | a8618a94
-- | -- | -- | --
Compilato con Qt | 5.15.2 | Esecuzione con Qt | 5.15.2
Compilato con GDAL/OGR | 3.3.3 | Esecuzione con GDAL/OGR | 3.3.3
Compilato con GEOS | 3.10.0-CAPI-1.16.0 | Esecuzione con GEOS | 3.10.0-CAPI-1.16.0
Compilato su SQLite | 3.35.2 | In esecuzione su SQLite | 3.35.2
Versione client PostgreSQL | 13.0 | Versione SpatiaLite | 5.0.1
Versione QWT | 6.1.3 | Versione QScintilla2 | 2.11.5
Compilato con PROJ | 8.2.0 | Esecuzione con PROJ | Rel. 8.2.0, November 1st, 2021
Versione SO | Windows 10 Version 2009
Attiva python plugin | autoSaver; mmqgis; quick_map_services; db_manager; processing

</body></html>

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@Vale1900 Please try with a new QGIS profile, no 3rd party plugins installed.

**Comment by Vale1900** [comment]
thanks, it worked!
I hope it works even when I reinstall the plugins I need ..
Is it possible to delete the default profile? or make the new profile the new "default profile"? 
Thank you

**Comment by frgis** [comment]
hello, I tried installing QGIS 3.16.3 and Qgis 3.22 and the tool crashes on startup.
I also cannot uninstall versions 3.16.2 and 3.20.3

I am working with a computer on Windows 10

![crash_install](https://user-images.githubusercontent.com/56657014/140724751-a546a59e-319a-4aa0-b7bc-297d2544d469.PNG)

**Comment by gioman** [comment]
>  Is it possible to delete the default profile? or make the new profile the new "default profile"?

@Vale1900 see the manual for the QGIS configs folder location in the system user folder. Then open it, and delete the folder with the profile name you want to get rid of.
