### ISSUE TITLE
[Expression] Using transform in aggregate to pick the polygon parent id seems to need reverse reprojection

### ISSUE THREAD

**Issue by mdouchin** [qgis/QGIS#45936]
### What is the bug or the crash?

The following expression is used in QGIS 3.16 for a point layer **bakeries** in `EPSG:4326`, and a **polygons** in `EPSG:3857` to get the intersecting polygon id. 

It seems to me I should have reverted 4326 and 3857, because I need to reproject the parent geometry (in 3857) into the bakeries geometry projection (4326).
```
aggregate(
	layer:='polygons', 
	aggregate:='max', expression:="id", 
	filter:=intersects(
		$geometry, 
		transform(geometry(@parent), 'EPSG:4326', 'EPSG:3857') 
	) 
)
```

### Steps to reproduce the issue

* Get the attached Geopackage containing the project and layers: 
[test_aggregate_polygon_id_with_transform.gpkg.txt](https://github.com/qgis/QGIS/files/7496379/test_aggregate_polygon_id_with_transform.gpkg.txt)
* Rename it into `test_aggregate_polygon_id_with_transform.gpkg` (Github has not allowed the gpkg extension in attached files...)
* The labels show the computed virtual field `polygon_id` for the bakeries point layer based on the given expression above
* You can change the virtual field expression and replace it by (the more logical to me) following expression

```
aggregate(
	layer:='polygons', 
	aggregate:='max', expression:="id", 
	filter:=intersects(
		$geometry, 
		transform(geometry(@parent), 'EPSG:3857', 'EPSG:4326) 
	) 
)
```
* it wont work: the value of the virtual field `polygon_id` will be `NULL`

### Versions

Version de QGIS | 3.16.11-Hannover | Révision du code | 26cc1c762f
-- | -- | -- | --
Compilé avec Qt | 5.12.8 | Utilisant Qt | 5.12.8
Compilé avec GDAL/OGR | 3.0.4 | Utilisé avec GDAL/OGR | 3.0.4
Compilé avec GEOS | 3.8.0-CAPI-1.13.1 | Utilisé avec GEOS | 3.8.0-CAPI-1.13.1
Compilé avec SQLite | 3.31.1 | Fonctionne avec SQLite | 3.31.1
Version du client PostgreSQL | 12.8 (Ubuntu 12.8-0ubuntu0.20.04.1) | Version de SpatiaLite | 4.3.0a
Version de QWT | 6.1.4 | Version de QScintilla2 | 2.11.2
Compilé avec PROJ | 6.3.1 | Fonctionne avec PROJ | Rel. 6.3.1, February 10th, 2020
Version de l'OS | Ubuntu 20.04.3 LTS
Extensions Python actives | quick_map_services; qgis_resource_sharing; QompliGIS; cadastre; changeDataSource; DataPlotly; QuickWKT; pg_history_viewer; qfieldsync; nominatim_locator_filter; qNote; trackable_project_files; LayerBoard; autoSaver; pg_metadata; lizmap; QuickOSM; lockzoom; SRTM-Downloader; plugin_reloader; french_locator_filter; lizsync; processing; db_manager; MetaSearch

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context
![test_aggregate_polygon_id_with_transform](https://user-images.githubusercontent.com/3492210/140730864-c14c7543-390f-43c9-aec0-df8874a71e22.png)

**Comment by agiudiceandrea** [comment]
@mdouchin
"filter - optional filter expression to limit the features used for calculating the aggregate. Fields and geometry are from the features on the joined layer. The source feature can be accessed with the variable @parent."
https://docs.qgis.org/3.16/en/docs/user_manual/expressions/functions_list.html#aggregate

You are using the expression on the layer "bakeries" (EPSG:4326) and you are "joining" to it the layer "polygons" (EPSG:3857), so, in the aggregate function, `$geometry` refers to the geometry of the joined layer, i.e. "polygons" (EPSG:3857), while `@parent` refers to the features of the source layer, i.e. "bakeries" (EPSG:4326).

Therefore, you need to transform `$geometry` from EPSG:3857 to EPSG:4326

```
aggregate(
	layer:='polygons', 
	aggregate:='max', expression:="id", 
	filter:=intersects(
		transform($geometry, 'EPSG:3857', 'EPSG:4326'), 
		geometry(@parent)
	) 
)
```

or `geometry(@parent)` from EPSG:4326 to EPSG:3857

```
aggregate(
	layer:='polygons', 
	aggregate:='max', expression:="id", 
	filter:=intersects(
		$geometry, 
		transform(geometry(@parent), 'EPSG:4326', 'EPSG:3857') 
	) 
)
```
