### ISSUE TITLE
3D DXF added with QGIS Browser loses the Z property

### ISSUE THREAD

**Issue by ReghardNell** [qgis/QGIS#45938]
### What is the bug or the crash?

3D dxf imports as 2d geometry.

Same file imported in QGIS 3.16 automatically imported as Linestringz imports.

### Steps to reproduce the issue

Pull in DXF file from QGIS browser.

### Versions

QGIS version
3.22.0-Białowieża
QGIS code revision
d9022691f1
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.2
PROJ version
8.1.1
EPSG Registry database version
v10.038 (2021-10-21)
GEOS version
3.10.0-CAPI-1.16.0
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
AnotherDXF2Shape
1.2.3
attributePainter
5.1
AzimuthDistanceCalculator
2.0.2
AzimuthMeasurement
0.2.2
coordinates_converter
1.0
DataPlotly
3.8.1
deactivate_active_labels
0.5
DigitizingTools
1.5.1
latlontools
3.5.9
MultipleLayerSelection
2.0
pcraster_tools
0.0.1
postgisQueryBuilder
2.0.1
profiletool
4.2.1
QuickOSM
2.0.0
quick_map_services
0.19.26
rvt-qgis
0.8.0
scriptrunner3
3.0.5
Serval
3.10.2
SplitPolygon-master
1.2
Submission
0.6
valuetool
3.0.15
volume_calculation_tool
0.2
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

I do not think it is a bug. It is just unclear how one will be able to inport dxf as LinestringZ.

**Comment by gioman** [comment]
@ReghardNell can you attach a sample?

**Comment by ReghardNell** [comment]
Shure.

The file is in a Local South African projection.

When opening the file in QGIS 3.16 i will get 3d geometry ( linestringz )

When I open in QGIS 3.22 I get 2d geometry.

Example dxf in zip file below:

[ss_ramp4_02.zip](https://github.com/qgis/QGIS/files/7499229/ss_ramp4_02.zip)

Hope this helps.

**Comment by gioman** [comment]
@ReghardNell confirmed, probably something related to the changes in how QGIS Browser loads datasources added in 3.22.

**Comment by ReghardNell** [comment]
Thanks @gioman

**Comment by vcloarec** [comment]
Should be fixed by #46034

**Comment by ReghardNell** [comment]
Thanks :+1 :)

**Comment by ReghardNell** [comment]
Tested the latest QGIS 3.22. DXF imports as expected as linestringz.

Thanks :)
