### ISSUE TITLE
Stream Digitize behaviour

### ISSUE THREAD

**Issue by antoniolocandro** [qgis/QGIS#45942]
### What is the bug or the crash?

I am putting here as I do not know if it is an error in the documentation or a bug in the coding, according to this https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/editing_geometry_attributes.html#straight-curve-and-stream-digitizing to be bale to affect the spacing between each vertex Advanced Digitizing needs to be enabled but I tried it and it doesn't seem to care if it is enabled or not. 

### Steps to reproduce the issue

1. Add a layer in QGIS
2. Enable Edit
3. Stream digitize without having Advanced editing on

### Versions

QGIS version
3.23.0-Master
QGIS code revision
ab42fbbda6
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.3
PROJ version
8.2.0
EPSG Registry database version
v10.038 (2021-10-21)
GEOS version
3.10.0-CAPI-1.16.0
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

This copy of QGIS writes debugging output.

Active Python plugins
aixm_styler
0.1
contour
2.0.8
DigitizingTools
1.5.1
latlontools
3.5.8
MemoryLayerSaver
4.0.4
mmqgis
2021.5.16
quick_map_services
0.19.19
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Probably there is no  need to have the Advanced Editing to use this tool as there is no good reason why this should be the default.

**Comment by nyalldawson** [comment]
That's a documentation error -- there's no such requirement

**Comment by antoniolocandro** [comment]
I have added the issue in the documentation tracker so will close here
