### ISSUE TITLE
QGIS Docker / Could not find the Qt platform plugin "offscreen"

### ISSUE THREAD

**Issue by stevo01** [qgis/QGIS#45941]
### What is the bug or the crash?

I try to run "qgis_process run .." in docker container and got error 

```
qt.qpa.plugin: Could not find the Qt platform plugin "offscreen" in "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms"
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Aborted (core dumped)
```

### Steps to reproduce the issue

start the image with command:
`docker run -d --rm -it --name qgis --hostname=qgis qgis/qgis:release-3_22 `

open console with command 
`docker exec -i -t qgis /bin/bash`

set following environment variables for support of "offscreen mode" 
```
export QT_QPA_PLATFORM=offscreen
export QT_QPA_PLATFORM_PLUGIN_PATH=/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms
export QT_DEBUG_PLUGINS=1
```

start processing
```
root@qgis:/# qgis_process run
QFactoryLoader::QFactoryLoader() checking directory path "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() checking directory path "/usr/lib/x86_64-linux-gnu/qt5/plugins" ...
QFactoryLoader::QFactoryLoader() checking directory path "/" ...
QFactoryLoader::QFactoryLoader() checking directory path "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/platforms" ...
QFactoryLoader::QFactoryLoader() checking directory path "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() checking directory path "//platforms" ...
qt.qpa.plugin: Could not find the Qt platform plugin "offscreen" in "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms"
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Aborted (core dumped)
root@qgis:/# 
```

### Versions

qgis: release-3_22
docker: Docker version 19.03.15
os: debian 9.0

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@stevo01 do not seems a problem with QGIS code, this tracker is about it.

**Comment by stevo01** [comment]
Without deep understanding of the qgis code: I assume QGIS it is using a qt method to search and load plugins. This method seems to fail in some environments. 
I would like to support with debugging but I am not shure how to create the docker container with application that includes debug symbols, add a propper debug server and how to debug it via remote connection. 
Every info about a propper setup of a debug environment inside the docker container would be helpful.
