### ISSUE TITLE
Qgis won't load, keeps crashing

### ISSUE THREAD

**Issue by KasperZs** [qgis/QGIS#45945]
### What is the bug or the crash?

I just closed QGIS after finishing building a DEM in a project of mine, and when I went to reopen it, it keeps crashing and wont allow to open the project.

HELP PLEASE!
![Screenshot_1](https://user-images.githubusercontent.com/93952220/140828854-ad1842fa-5329-42d1-badc-c3ac8b7b59e2.png)

Crash ID: 053af966a9362344bcb1f5508a87b17b9b0047be

### Steps to reproduce the issue

1. Open QGIS.

### Versions

3.16 Hannover

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by hay216** [comment]
Having the same problem - QGIS crashes when I try and open it - crash id: 91c5fbfa52ffdfb9f42df9165a3e212ea86c677f

**Comment by gioman** [comment]
@hay216 @KasperZs as requested in the bug report template: pleas try with a new QGIS profile, no 3rd party plugins installed.

**Comment by hay216** [comment]
Thanks Giovanni – much appreciated

K

 T +61 3 62325260
GPO Box 1538, Hobart, Tasmania, 7001
http://people.csiro.au/H/K/Keith-Hayes
https://au.linkedin.com/in/keith-hayes-2a799714
https://scholar.google.com.au/citations?user=_aNBKvyrGigC&hl=en
CSIRO acknowledges the Traditional Owners of the lands that we live and work on across Australia and pays its respect to Elders past and present.
