### ISSUE TITLE
GDAL hillshade tool fails if more than one config options are set

### ISSUE THREAD

**Issue by timlinux** [qgis/QGIS#45957]
### What is the bug or the crash?

GDAL Hillshade tools fails if multiple options are set

Can we alter the behaviour so that the options are radio buttons where they are exclusive?

### Steps to reproduce the issue

If I set two options in the GDAL hillshade tool like this:

![image](https://user-images.githubusercontent.com/178003/140906422-ee215eba-45cd-4f43-988b-1e90e01714b9.png)

I get an error. The generated command is this:

```
gdaldem hillshade /home/timlinux/Downloads/MaseruSRTM/S30E027.hgt /home/timlinux/Downloads/OUTPUT.tif -of GTiff -b 1 -z 1.0 -s 1.0 -alt 45.0 -combined -multidirectional
```

Trying to run on the command line I can see GDAL complains like this:

```
ERROR 6: only one of -multidirectional, -combined or -igor can be used
 Usage: 
```

### Versions

QGIS version | 3.18.3-Zürich | QGIS code branch | Release 3.18
-- | -- | -- | --
Compiled against Qt | 5.15.2 | Running against Qt | 5.15.2
Compiled against GDAL/OGR | 3.2.2 | Running against GDAL/OGR | 3.2.2
Compiled against GEOS | 3.9.0-CAPI-1.16.2 | Running against GEOS | 3.9.0-CAPI-1.16.2
Compiled against SQLite | 3.34.1 | Running against SQLite | 3.34.1
PostgreSQL Client Version | 13.2 | SpatiaLite Version | 5.0.1
QWT Version | 6.1.5 | QScintilla2 Version | 2.11.5
Compiled against PROJ | 7.2.1 | Running against PROJ | Rel. 7.2.1, January 1st, 2021
OS Version | Fedora 34 (KDE Plasma)
Active python plugins | Mergin; SRTM-Downloader; layer-sorting; DataPlotly; SpreadsheetLayers; MetaSearch; db_manager; processing

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
> Can we alter the behaviour so that the options are radio buttons where they are exclusive?

@timlinux I may be wrong but I don't think there is support for mutually exclusive radio buttons, this is one of the reasons why sometimes why need to split tools.

**Comment by nicogodet** [comment]
@gioman Or checking inputs with a python ext script ?

**Comment by DelazJ** [comment]
> I may be wrong but I don't think there is support for mutually exclusive radio buttons

I don't know what these options actually do, but based on the naming, can't "Combine shading" and "Multidirectional shading"  (and igor?) be part of a "shading" combobox option? Then you have one option at a time.

**Comment by gioman** [comment]
> I don't know what these options actually do, but based on the naming, can't "Combine shading" and "Multidirectional shading" (and igor?) be part of a "shading" combobox option? Then you have one option at a time.

possibly yes, you are right, I will have a look at it.
