### ISSUE TITLE
QGIS crashes when `feat.geometry().get()` is used

### ISSUE THREAD

**Issue by geoyee** [qgis/QGIS#45956]
### What is the bug or the crash?

When using pyqgis in QGIS, If the following code is used:
``` python
p = QgsPoint(3,4)
feat = QgsFeature()
feat.setGeometry(p)
print(feat.geometry().get())
```
I can get the right result. But when I use the following code instead:
``` python
mypoint = feat.geometry().get()
print(mypoint)
```
QGIS crashes!

This is a relevant screenshot:

![T%J19 JV}5(QZLVQ((HSMUH](https://user-images.githubusercontent.com/71769312/140900493-e9f78eb0-6c3e-4eaa-9b57-d0a16b777a13.png)

THX, This is a great project!

### Steps to reproduce the issue

1. Open pyqgis console.
2. Input:
``` python
p = QgsPoint(3,4)
feat = QgsFeature()
feat.setGeometry(p)
mypoint = feat.geometry().get()
print(mypoint)
```
3. QGIS unexpectedly ended.

### Versions

QGIS版本
3.16.11-Hannover
QGIS代码版本
26cc1c76
编译时Qt版本
5.15.2
运行于Qt版本
5.15.2
编译时GDAL/OGR版本
3.3.1
运行于GDAL/OGR版本
3.3.1
编译时GEOS版本
3.9.1-CAPI-1.14.2
运行于GEOS版本
3.9.1-CAPI-1.14.2
编译时SQLite版本
3.35.2
运行于SQLite版本
3.35.2
PostgreSQL客户端版本
13.0
SpatiaLite版本
5.0.1
QWT版本
6.1.3
QScintilla2 版本
2.11.5
编译时PROJ版本
8.1.1
运行于PROJ版本
Rel. 8.1.1, September 1st, 2021
操作系统版本
Windows 10 Version 2009
激活python插件
buildseg; 
erpq; 
geocoding; 
pluginbuilder3; 
plugin_reloader; 
db_manager; 
MetaSearch; 
processing; 
CustomToolBar

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

Crash ID: e59f7f72948aba3736a03ad9defeef2e5929e035

Stack Trace

PyInit__core :
PyObject_Repr :
PyFile_WriteObject :
PyFile_WriteString :
PyLong_AsDouble :
PyBytes_Repr :
PyBytes_Repr :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyEval_EvalCodeWithName :
PyEval_EvalCodeEx :
PyEval_EvalCode :
PyEval_GetBuiltins :
PyEval_GetBuiltins :
PyEval_EvalFrameDefault :
PyFloat_FromDouble :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyFloat_FromDouble :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyFloat_FromDouble :
PyEval_EvalFrameDefault :
PyFloat_FromDouble :
PyEval_EvalFrameDefault :
PyFloat_FromDouble :
PyEval_EvalFrameDefault :
PyFunction_Vectorcall :
PyFloat_FromDouble :
PyVectorcall_Call :
PyObject_Call :
PyInit__gui :
QWidget::event :
QFrame::event :
QAbstractScrollArea::event :
PyInit__gui :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processKeyEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.16.11-Hannover
QGIS code revision: 26cc1c76
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.1
Running against GDAL: 3.3.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

**Comment by nicogodet** [comment]
Can confirm on 3.22 too

**Comment by Koyaani** [comment]
The first snippet given doesn't work on 3.22:
```python
p = QgsPoint(3,4)
feat = QgsFeature()
feat.setGeometry(p)
print(feat.geometry().get())
```
But these two, yes:
```python
p = QgsPoint(3,4)
feat = QgsFeature()
feat.setGeometry(p)
geom = feat.geometry()
mypoint = geom.get()
print(mypoint)
```

```python
p = QgsPoint(3,4)
feat = QgsFeature()
feat.setGeometry(p)
mypoint = feat.geometry().constGet()
print(mypoint)
```

**Comment by geoyee** [comment]
> The first snippet given doesn't work on 3.22:
> 
> ```python
> p = QgsPoint(3,4)
> feat = QgsFeature()
> feat.setGeometry(p)
> print(feat.geometry().get())
> ```
> 
> But these two, yes:
> 
> ```python
> p = QgsPoint(3,4)
> feat = QgsFeature()
> feat.setGeometry(p)
> geom = feat.geometry()
> mypoint = geom.get()
> print(mypoint)
> ```
> 
> ```python
> p = QgsPoint(3,4)
> feat = QgsFeature()
> feat.setGeometry(p)
> mypoint = feat.geometry().constGet()
> print(mypoint)
> ```

Is 3.22  a version of QGIS? 
The first snippet given can work on my QGIS:
``` python
p = QgsPoint(3,4)
feat = QgsFeature()
feat.setGeometry(p)
print(feat.geometry().get())
```
But the code below doesn't work:
``` python
p = QgsPoint(3,4)
feat = QgsFeature()
feat.setGeometry(p)
mypoint = feat.geometry().get()
print(mypoint)
```
`feat.geometry().get()` can't be received by a variable`mypoint`.

**Comment by nyalldawson** [comment]
It's caused by the python garbage collector prematurely cleaning up objects.

Store a reference to the geometry in a variable first and it will work as expected:

    geom = f.geometry()
    geom.get().....

**Comment by geoyee** [comment]
> It's caused by the python garbage collector prematurely cleaning up objects.
> 
> Store a reference to the geometry in a variable first and it will work as expected:
> 
> ```
> geom = f.geometry()
> geom.get().....
> ```

THX, I'll look at python garbage collection~
