### ISSUE TITLE
pySimpleGuiQt.main() results in QGIS 3.16.13 crashing

### ISSUE THREAD

**Issue by ThomJea** [qgis/QGIS#45960]
### What is the bug or the crash?

Ok so I have a script I try to run on QGIS. There are several gui and I made them with pySimpleGUIQt, I installed PySimpleGUIQt through OsGeo4W shell with py3_env. The script run in osgeo4w, then I launch Qgis and the script crashes

```
import PySimpleGUIQt as sg
  File "MY_PERSONNAL_PATH_TO_PYTHON37\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "MY_PERSONNAL_PATH_TO_PYTHON37\site-packages\PySimpleGUIQt\__init__.py", line 2, in 
    from .PySimpleGUIQt import *
  File "MY_PERSONNAL_PATH_TO_PYTHON37\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "MY_PERSONNAL_PATH_TO_PYTHON37\site-packages\PySimpleGUIQt\PySimpleGUIQt.py", line 25, in 
    from PySide2.QtWidgets import QApplication, QLabel, QWidget, QLineEdit, QComboBox, QFormLayout, QVBoxLayout, QHBoxLayout, QListWidget, QDial, QTableWidget
  File "MY_PERSONNAL_PATH_TO_PYTHON37\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: DLL load failed: La procédure spécifiée est introuvable.
```

### Steps to reproduce the issue

- Open osgeo4w shell, type `py3_env` to setup the python environment
- Type `python -m pip install PySimpleGUIQt`
- Launch QGIS and open Python console, type `import PySimpleGUIQt`

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

Version de QGIS | 3.16.5-Hannover | Révision du code | 58ba7c1ed6
-- | -- | -- | --
Compilé avec Qt | 5.11.2 | Utilisant Qt | 5.11.2
Compilé avec GDAL/OGR | 3.1.4 | Utilisé avec GDAL/OGR | 3.1.4
Compilé avec GEOS | 3.8.1-CAPI-1.13.3 | Utilisé avec GEOS | 3.8.1-CAPI-1.13.3
Compilé avec SQLite | 3.29.0 | Fonctionne avec SQLite | 3.29.0
Version du client PostgreSQL | 11.5 | Version de SpatiaLite | 4.3.0
Version de QWT | 6.1.3 | Version de QScintilla2 | 2.10.8
Compilé avec PROJ | 6.3.2 | Fonctionne avec PROJ | Rel. 6.3.2, May 1st, 2020
Version de l'OS | Windows 10 (10.0)
Extensions Python actives | closest_points; pluginbuilder3; plugin_reloader; quick_map_services; db_manager; MetaSearch; processing

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
> Launch QGIS and open Python console, type `import PySimpleGUIQt`

3.22.0 and 3.16.13

![image](https://user-images.githubusercontent.com/1951107/140923199-7240cb5e-ef30-45e6-9f3a-53d1ab8c7b55.png)

**Comment by ThomJea** [comment]
Arf...Thank you for the feedback. so it seems that it was bothering everyone for nothing... so I will look into my personal setup...

**Comment by ThomJea** [comment]
Ok, I upgraded to 3.16.13 and now PySimpleGUIQt is loading but Qgis crashes when launching the test `PySimpleGUIQt.main()` which sould display this image https://warehouse-camo.ingress.cmh1.psfhosted.org/bc46cb51bd5cfa472dbee237a8f148202c14b6cd/68747470733a2f2f757365722d696d616765732e67697468756275736572636f6e74656e742e636f6d2f34363136333535352f37313432313835322d37633661643430302d323634622d313165612d396164632d3135663661613432343865382e706e67

**Comment by ThomJea** [comment]
report given by QGIS
## User Feedback

Crash du to the use of PySimpleGUIQt.main() inside the console

## Report Details

**Crash ID**: [251d613e68f4e2c9927f2b7343a679de2891701e](https://github.com/qgis/QGIS/search?q=251d613e68f4e2c9927f2b7343a679de2891701e&type=Issues)


**Stack Trace**
<pre>
MakeQAppWrapper :
SbkQAppTpNew :
PyEval_EvalFrameDefault :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyEval_EvalFrameDefault :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyFunction_Vectorcall :
PyType_GenericNew :
PyType_GenericNew :
PyObject_MakeTpCall :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyEval_EvalCodeWithName :
PyEval_EvalCodeEx :
PyEval_EvalCode :
PyEval_GetBuiltins :
PyEval_GetBuiltins :
PyEval_EvalFrameDefault :
PyFloat_FromDouble :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyFloat_FromDouble :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyFloat_FromDouble :
PyEval_EvalFrameDefault :
PyFloat_FromDouble :
PyEval_EvalFrameDefault :
PyFloat_FromDouble :
PyEval_EvalFrameDefault :
PyFunction_Vectorcall :
PyFloat_FromDouble :
PyVectorcall_Call :
PyObject_Call :
PyInit__gui :
QWidget::event :
QFrame::event :
QAbstractScrollArea::event :
PyInit__gui :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processKeyEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>


**QGIS Info**
QGIS Version: 3.16.13-Hannover
QGIS code revision: a8618a94
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.3
Running against GDAL: 3.3.3



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

**Comment by nyalldawson** [comment]
This is not supported. You must use PyQt for development in QGIS, not other qt python libraries. If it worked in previous versions it was purely by luck.
