### ISSUE TITLE
Export MBTiles to QField

### ISSUE THREAD

**Issue by alpinfra** [qgis/QGIS#45963]
### What is the bug or the crash?

QGIS 3.22.0 crashes when exporting a project containing MBTiles to QField. 
Does not happen with version 3.16.4, here the export finishes successfully

### Steps to reproduce the issue

1. Install Plugin QFieldSync
2. create or load MBTiles file
3. Choose Package Project for QField
4. Click on Create
5. QGIS crashes, but not immediately

### Versions

3.22.0

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@alpinfra must be reported in the qfield sync plugin tracker, not here.
