### ISSUE TITLE
Raster layer exported to GeoPackage with the character 'ß' in the name is not immediately loaded in the project

### ISSUE THREAD

**Issue by T3xtM4rk3r** [qgis/QGIS#45965]
### What is the bug or the crash?

Hi Everyone,

there seems to be an issue with the encoding of the special character ß when exporting a raster layer to a geopackage.
Exporting vectors layer with an ß in it's name works just fine.

Any help with this is really appreciated

### Steps to reproduce the issue

1. Open QGIS 3.16.13
2. Drop raster.zip into Layers Panel
[raster.zip](https://github.com/qgis/QGIS/files/7505651/raster.zip)

3. Right click raster -> Export -> Save As 
![grafik](https://user-images.githubusercontent.com/92782306/140949029-74caa837-da97-417a-8b74-509bb56df7ad.png)

4. The following messages occur 
![grafik](https://user-images.githubusercontent.com/92782306/140949363-f8213946-0bd6-47ae-9747-ff2b5c19a227.png)

5. The geopackage with a ß in its name gets created, but the raster layers name seems to wrongly encoded?
![grafik](https://user-images.githubusercontent.com/92782306/140950045-ee411517-37b4-447c-9efe-60f35e23e4bb.png)

6. Adding the layer to the project using the 'add layer to project' right klick fails with 
2021-11-09T16:06:38     CRITICAL    Invalid Layer : GDAL provider Cannot open GDAL dataset ![grafik](https://user-images.githubusercontent.com/92782306/140950244-f4d82ff5-fbea-42e9-b6a0-b599e78eec2f.png)
but dragging and dropping the geopackage from the explorer directly to the Layers Panel works

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.16.13-Hannover | QGIS code revision | a8618a94
-- | -- | -- | --
Compiled against Qt | 5.15.2 | Running against Qt | 5.15.2
Compiled against GDAL/OGR | 3.3.3 | Running against GDAL/OGR | 3.3.3
Compiled against GEOS | 3.10.0-CAPI-1.16.0 | Running against GEOS | 3.10.0-CAPI-1.16.0
Compiled against SQLite | 3.35.2 | Running against SQLite | 3.35.2
PostgreSQL Client Version | 13.0 | SpatiaLite Version | 5.0.1
QWT Version | 6.1.3 | QScintilla2 Version | 2.11.5
Compiled against PROJ | 8.2.0 | Running against PROJ | Rel. 8.2.0, November 1st, 2021
OS Version | Windows 10 Version 2009
Active python plugins | qlyrx; raster_tracer; slyr_community; SpreadsheetLayers; db_manager; MetaSearch; processing

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
@T3xtM4rk3r everything is fine here on 3.22.0, would you mind give it a try? Thanks.

**Comment by T3xtM4rk3r** [comment]
Hi gioman

i just tried with a freshly installed 3.22.0.

The raster layer itself seems to be saved correctly and add layer to project is working.

![image](https://user-images.githubusercontent.com/92782306/140991731-c000f99a-f15c-4ecb-a475-ebeea95a976d.png)

But during the export I still got several messages in the Log Panel 

![image](https://user-images.githubusercontent.com/92782306/140991604-6960c342-32a3-4df5-a26b-2792cb204884.png)

and

![image](https://user-images.githubusercontent.com/92782306/140991653-d736ddb5-4035-4674-bc3f-8b4d5f1841d7.png)

Unfortunately, at work I'm restricted to using the LTR version.

**Comment by gioman** [comment]
> But during the export I still got several messages in the Log Panel

this is a warning, not error

> and

this is an error, and it seems it the cause why the layer is not added automatically in the project after the export. But then adding it manually or via browser is ok.
