### ISSUE TITLE
[Crash] The same code in editor

### ISSUE THREAD

**Issue by geoyee** [qgis/QGIS#45974]
### What is the bug or the crash?

When I use some code on the console, QGIS returns the correct results for me, but the same code running in editor, **QGIS APP CRASH!**. The difference is:
-  `d4()` is not used in console, and the code is entered line by line
-  `d4()` is used in .py file

CODE:
``` python
import numpy as np


def getgtypes():
    return 'point', 'linestring', 'polygon', \
           'multipoint','multilinestring','multipolygon'

def showgeo(geoms, name="tmp", gtype=None):
    if gtype is None:
        gtype = geoms[0].constGet().geometryType() \
                if isinstance(geoms[0], QgsGeometry) else geoms[0].geometryType()
        gtype = gtype.lower()
    if gtype not in getgtypes():
        raise Exception("gtype should be one of :{" + ','.join(getgtypes()) + "}")
    vl = QgsVectorLayer(gtype, name, "memory")
    pr = vl.dataProvider()
    feats = []
    for geom in geoms:
        feat = QgsFeature()
        feat.setGeometry(geom)
        feats.append(feat)
    pr.addFeatures(feats)
    QgsProject.instance().addMapLayer(vl)
    iface.zoomFull()
    

def d4():
    x = np.random.random(100)*100
    y = np.random.random(100)*100
    l = QgsLineString(x,y)
    mp = QgsMultiPoint()
    _= [mp.addGeometry(p)for p in l]
    gmp = QgsGeometry(mp)
    bbx = gmp.boundingBox()
    gbbx = QgsGeometry.fromRect(bbx)
    showgeo([mp],'随机点')
    feat = QgsFeature()
    feat.setGeometry(gbbx)
    vl = QgsVectorLayer('polygon','外界多边形','memory')
    vl.dataProvider().addFeatures([feat])
    vl.updateExtents()
    QgsProject.instance().addMapLayer(vl)
    iface.zoomFull()

d4()
```

On the previous issue, some code crashes QGIS but not display some error or warning. (Maybe a GC problem.)
Can I get some useful tips when a app crashes?

### Steps to reproduce the issue

1. open QGIS and PY console
2. open editor and paste code (code in **What is the bug or the crash?**)
3. running code
4. crash

![P2WV 6GU~8SKU@9%E(AAXNV](https://user-images.githubusercontent.com/71769312/141057337-9c72297c-7e4c-4549-b44c-bf115fb7dcfc.png)

![BZ7VP)GYA)805AZ7NMM58S5](https://user-images.githubusercontent.com/71769312/141057357-4dd646d0-b459-4dfc-8c88-6f8237cf599b.png)

### Versions

QGIS版本
3.16.11-Hannover
QGIS代码版本
26cc1c76
编译时Qt版本
5.15.2
运行于Qt版本
5.15.2
编译时GDAL/OGR版本
3.3.1
运行于GDAL/OGR版本
3.3.1
编译时GEOS版本
3.9.1-CAPI-1.14.2
运行于GEOS版本
3.9.1-CAPI-1.14.2
编译时SQLite版本
3.35.2
运行于SQLite版本
3.35.2
PostgreSQL客户端版本
13.0
SpatiaLite版本
5.0.1
QWT版本
6.1.3
QScintilla2 版本
2.11.5
编译时PROJ版本
8.1.1
运行于PROJ版本
Rel. 8.1.1, September 1st, 2021
操作系统版本
Windows 10 Version 2009
激活python插件
buildseg; 
erpq; 
geocoding; 
pluginbuilder3; 
plugin_reloader; 
db_manager; 
MetaSearch; 
processing; 
CustomToolBar

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

Crash ID: 8abcf3cf4db03db482f7292a6dae2f28da4550fe

Stack Trace

QgsGeometry::boundingBox :
QgsGdalLayerItem::setCrs :
QgsAbstractFeatureIterator::nextFeature :
QgsVectorLayerFeatureIterator::fetchFeature :
QgsAbstractFeatureIterator::nextFeature :
QgsVectorLayerJoinInfo::setEditable :
QgsVectorLayerJoinInfo::setEditable :
QgsMapRendererParallelJob::renderLayerStatic :
QgsMapRendererParallelJob::renderingFinished :
QgsImageOperation::overlayColor :
QgsImageOperation::stackBlur :
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.16.11-Hannover
QGIS code revision: 26cc1c76
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.1
Running against GDAL: 3.3.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

**Comment by gioman** [comment]
On 3.22.0/Win 10 too.

**Comment by nyalldawson** [comment]
this line

    _= [mp.addGeometry(p)for p in l]

should be

    _= [mp.addGeometry(p.clone()) for p in l]

The rationale is a little tricky, and has to do with ownership of c++ objects. But the linestring has ownership of the point, and you can't then directly add it to the multigeometry.

**Comment by geoyee** [comment]
> this line
> 
> ```
> _= [mp.addGeometry(p)for p in l]
> ```
> 
> should be
> 
> ```
> _= [mp.addGeometry(p.clone()) for p in l]
> ```
> 
> The rationale is a little tricky, and has to do with ownership of c++ objects. But the linestring has ownership of the point, and you can't then directly add it to the multigeometry.

![C9TBWA3DIEYVZRQ5BM {579](https://user-images.githubusercontent.com/71769312/141224108-fa6ea7a9-f059-4b3f-adb7-8ff577ff560d.png)

**Comment by geoyee** [comment]
@nyalldawson QGIS crashes too (in the editor), but this works on the python console. I feel puzzled.
