### ISSUE TITLE
join csv file to vector layer does not work

### ISSUE THREAD

**Issue by KayarBlue** [qgis/QGIS#45985]
### What is the bug or the crash?

According to this video tutorial https://www.youtube.com/watch?v=Fv2lF2B8ygg, creating a join between a vector layer and a CSV file with attributes, should be a simple matter of using Properties --> Joins --> + (to add join), followed by clicking OK when done. This does nothing in QGIS 3.22. After I close the Properties window, the join just disappears. It does not show up in the Attributes table, and when I open Properties again it's not there. 

### Steps to reproduce the issue

Vector Layer --> Properties...
Joins
+ (to add a join)
[do all the things to set up join]
Click Ok on the Join window - the join appears in the Joins list
Click Ok on the Properties window - the join disappears

### Versions

3.22 (I just downloaded it two days ago (Nov 9))

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
> This does nothing in QGIS 3.22.

@KayarBlue works fine here, Please attach your data.

**Comment by KayarBlue** [comment]
[Marine Ecoregions of the World GEN.zip](https://github.com/qgis/QGIS/files/7524357/Marine.Ecoregions.of.the.World.GEN.zip)
[EcoprovPairsRisks_ToVisualise_53.csv](https://github.com/qgis/QGIS/files/7524361/EcoprovPairsRisks_ToVisualise_53.csv)

There's a shapefile buried in the first zip file (sorry about all the clicking, that's how it was when I downloaded it). The link I was trying to join them on was PROV_CODE in the shapefile to Dest in the CSV file. 

Now that you've pointed to the data files as a potential problem, it also occurs to me that I wasn't able to make any other kinds of changes to the shapefile layer either (like displaying on PROV_CODE instead of ECO_CODE which it defaults to)... maybe something is wrong with the shapefile? (I know almost nothing about GIS, I was trying to learn GIS by fiddling with these files.)

**Comment by gioman** [comment]
> There's a shapefile buried in the first zip file (sorry about all the clicking, that's how it was when I downloaded it). The link I was trying to join them on was PROV_CODE in the shapefile to Dest in the CSV file.

@KayarBlue using "Dest" as target field it works just fine.
