### ISSUE TITLE
I can't find the folder "https://qgis.org/ubuntu/dists/focal/main/binary-i386/"

### ISSUE THREAD

**Issue by fgodoyf** [qgis/QGIS#45980]
### What is the bug or the crash?

Missing repository for Ubuntu focal 20.04.3 architecture i386.

### Steps to reproduce the issue

sudo apt update
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://qgis.org/ubuntu focal InRelease' doesn't support architecture 'i386'

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.0-Białowieża | QGIS code revision | d9022691f1
-- | -- | -- | --
Qt version | 5.12.8
Python version | 3.8.10
GDAL/OGR version | 3.0.4
PROJ version | 6.3.1
EPSG Registry database version | v9.8.6 (2020-01-22)
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
SQLite version | 3.31.1
PDAL version | 2.0.1
PostgreSQL client version | 12.8 (Ubuntu 12.8-0ubuntu0.20.04.1)
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.2
OS version | Ubuntu 20.04.3 LTS
  |   |   |  
Active Python plugins
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.5
processing | 2.12.99

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by jef-n** [comment]
i386 is not supported on ubuntu focal anymore. See also [focal release notes](https://wiki.ubuntu.com/FocalFossa/ReleaseNotes#Upgrades_on_i386)
