### ISSUE TITLE
QGIS doesn't handle changes in external spreadsheet / doesn't update VRT-file

### ISSUE THREAD

**Issue by celmi** [qgis/QGIS#45981]
### What is the bug or the crash?

**Expected behaviour**

When a layer is connected to an external spreadsheet-table, and this table gets modified (eg. deletion of columns), QGIS should realize that something's changed (runtime or at least at startup) and either automatically or optionally recreate the VRT-file, so the connected layer retains data-connection and display all relevant data ).

**Current behaviour**

QGIS does nothing. After modification of spreadsheet and reopening the QGIS Project, the attribute table of the corresponding layer will be completely blank / unusable.

### Steps to reproduce the issue

Steps to reproduce:

1. Create Excel-Spreadsheet "test.xlsx", 
	1.1 fill out Columns A, B, C with test-Data
	1.2 save

2. Create new QGIS-Project, 
	2.1 save as test.qgz
	2.2. add layer / Add spreadsheet layer, choose text.xlsx
	--> layer L1 will import just fine, show spreadsheet data

3. Close QGIS

4. Open test.xlsx, delete Column A, save to disk

5. Open QGIS "test.qgz"
	--> attribute-table of layer L1 will be empty (unexpected Failure)

6. Repeat Step 2.2
	QGIS will ask if it may overwrite the VRT-File
	-->VRT-file will be renewed
        --> new layer L2 will import data just fine, attribute table of this new layer L2 will show data
	--> meanwhile attribute table of layer L1 will remain blank

7. Save test.qgz, close file, open file again
	--> QGIS will now use the new VRT for both layers, both L1 and L2 will display data

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS-Version | 3.16.7-Hannover | QGIS-Codeversion | 0471743889
-- | -- | -- | --
Kompiliert gegen Qt | 5.11.2 | Laufendes Qt | 5.11.2
Kompiliert mit GDAL/OGR | 3.1.4 | Läuft mit GDAL/OGR | 3.1.4
Kompiliert mit GEOS | 3.8.1-CAPI-1.13.3 | Läuft mit GEOS | 3.8.1-CAPI-1.13.3
Kompiliert mit SQLite | 3.29.0 | Läuft mit SQLite | 3.29.0
PostgreSQL-Client-Version | 11.5 | SpatiaLite-Version | 4.3.0
QWT-Version | 6.1.3 | QScintilla2-Version | 2.10.8
Kompiliert mit PROJ | 6.3.2 | Läuft mit PROJ | Rel. 6.3.2, May 1st, 2020
BS-Version | Windows 10 (10.0)
Aktive Python-Erweiterungen | SpreadsheetLayers; swiss_locator; db_manager; MetaSearch; processing

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
>     2\. 2.2. add layer / Add spreadsheet layer, choose text.xlsx

@celmi are you using the Spreadsheet Layers plugin?

**Comment by gioman** [comment]
>     5\. Open QGIS "test.qgz"
>         --> attribute-table of layer L1 will be empty (unexpected Failure)

I have tested the workflow up to this point but **not** using any 3rd party plugin, and at this point the table in QGIS shows just ok, without the column removed with MS/Libre Office.

**Comment by gioman** [comment]
>     6\. QGIS will ask if it may overwrite the VRT-File

The VRT is something generated by the spreadsheet layers plugins, you must report this to the author/s, not here.

**Comment by celmi** [comment]
Hello Gioman
Many thanks for taking your time to examine my report. So sorry, I hadn't realized that this functionality is provided by the plugin. 
Can you please help me one last time? HOW did you manage to follow my workflow without this plugin? When I deactivate the plugin, I cannot find an option to add a spreadsheet as a layer. I'd like to learn doing so without the plugin. 
Best regards

**Comment by gioman** [comment]
just drag and drop the xls in QGIS.

**Comment by celmi** [comment]
Thank you for your help, much appreciated.

If there is a drag-and-drop option to add spreadsheets as layers, shouldn't there be a corresponding menu-command for people (similar to the one introduced by the obsolete plugin)? Do you think I should file a feature-request for this?

**Comment by gioman** [comment]
> menu-command for people (similar to the one introduced by the obsolete plugin)?

You use the "add vector" menu. Or if you use CSVs you can use the "add delimited text layer" menu. Or the browser (double click).
