### ISSUE TITLE
 I don't see any vector commands, and I only see three raster commands

### ISSUE THREAD

**Issue by martabevilacqua30** [qgis/QGIS#45998]
### Feature description

for a week the 3.16 version, downloaded with excellence and fully functional, no longer works well. I don't see the vector commands anymore and the raster commands are only three, and the extrusion command, essential for my work, does not appear at all. I have already restarted the application several times, I have tried to uninstall and reinstall it, I have tried both in the display panels and in the system settings, but in any case the problem is not solved, or in any case I do not know what else to do. I am a university student and my other classmates have been experiencing the same problem for a week now. it is urgent for us to solve the problem. how can we do? I await a response soon, cordially

### Additional context

<img width="960" alt="Screenshot (122)" src="https://user-images.githubusercontent.com/94121108/141310530-f81c32ab-9661-4e0a-a92a-bb9a6705e183.png">
<img width="960" alt="Screenshot (121)" src="https://user-images.githubusercontent.com/94121108/141310533-cd1efa8b-cfa9-4012-af25-21645b24cbdd.png">

**Comment by elpaso** [comment]
Try enabling the processing plugin.

**Comment by gioman** [comment]
@martabevilacqua30 processings algs are native, but if the Processing plugin is not active you won't see them in that menus. Please check if Processing is active in QGIS plugin manager.

**Comment by martabevilacqua30** [comment]
Perfect i solved the problem, it was not active, now it works again. thank
you very much for your availability and kindness. with regards, Marta
Bevilacqua

Il giorno gio 11 nov 2021 alle ore 15:17 Giovanni Manghi <
***@***.***> ha scritto:
