### ISSUE TITLE
Layout Grid offset

### ISSUE THREAD

**Issue by Spartacus1** [qgis/QGIS#46001]
### What is the bug or the crash?

The X and Y offset fields in the Print Layout Grid edition features seem not to be working . Changing values have no effect.  

### Steps to reproduce the issue

In Print layout create a coordinate Grid and define the X and Y spacing. After try to change the X and Y offset values and no changes occur. 

### Versions

QGIS 3.18 and newer versions. 

### Supported QGIS version

- [x] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

### Additional context

Using MacOS Monterey.

**Comment by gioman** [comment]
@Spartacus1 Cannot confirm on 3.22.0 and 3.16.3

**Comment by Spartacus1** [comment]
Hi gioman, are you able to use the X and Y offset without any problems? Does the values change the grid? In my case nothing happens.

**Comment by gioman** [comment]
> Does the values change the grid?

@Spartacus1 yes


>  In my case nothing happens.

what is your value for spacing and for offest?

**Comment by Spartacus1** [comment]
I have 10X10 for X and Y spacing for a Projected Grid (meters). For practical reasons, I want an offset of 1 meter in X. Input the value, nothing happens.

**Comment by gioman** [comment]
> I have 10X10 for X and Y spacing for a Projected Grid (meters). For practical reasons, I want an offset of 1 meter in X.

works here.

**Comment by agiudiceandrea** [comment]
@Spartacus1 maybe better to share a project in which the issue occurs and a screencast that show the issue.

**Comment by Spartacus1** [comment]
nice idea agiudiceandrea. Here it goes. In the example, for instance, the offset is useful to drag the 0,0 (axis origin) to the lower left corner. As you can see, does not work at all. 

https://u.pcloud.link/publink/show?code=XZRlqUXZr70INARotDjMeCkuiICqkmKB1FRV
