### ISSUE TITLE
Crash after repositioning of annotation bubbles

### ISSUE THREAD

**Issue by jumkiel** [qgis/QGIS#46000]
### What is the bug or the crash?

Crash ID: 7a1aefcec4b6d5b8154e18fd30378d378135192c

Stack Trace

QgsTemplatedLineSymbolLayerBase::renderPolygonStroke qgslinesymbollayer.cpp:1266
QgsFillSymbol::renderPolygonUsingLayer qgssymbol.cpp:2333
QgsFillSymbol::renderPolygon qgssymbol.cpp:2273
QgsSymbol::renderFeature qgssymbol.cpp:1234
QgsFeatureRenderer::renderFeatureWithSymbol qgsrenderer.cpp:134
QgsRuleBasedRenderer::stopRender qgsrulebasedrenderer.cpp:1003
QgsVectorLayerRenderer::drawRenderer qgsvectorlayerrenderer.cpp:420
QgsVectorLayerRenderer::render qgsvectorlayerrenderer.cpp:317
QgsMapRendererParallelJob::renderLayerStatic qgsmaprendererparalleljob.cpp:353
QtConcurrent::MapKernel >::iterator,QtConcurrent::FunctionWrapper1 const & __ptr64> >::runIteration qtconcurrentmapkernel.h:69
QtConcurrent::MapKernel::iterator,QgsImageOperation::ProcessBlockUsingLineOperation >::runIterations qtconcurrentmapkernel.h:78
QtConcurrent::IterateKernel::iterator,void>::forThreadFunction qtconcurrentiteratekernel.h:256
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.16.13-Hannover
QGIS code revision: a8618a941b
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

### Steps to reproduce the issue

After severeal times of new positioning some annotations.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS-Version | 3.16.13-Hannover | QGIS-Codeversion | a8618a941b
-- | -- | -- | --
Kompiliert gegen Qt | 5.11.2 | Laufendes Qt | 5.11.2
Kompiliert mit GDAL/OGR | 3.1.4 | Läuft mit GDAL/OGR | 3.1.4
Kompiliert mit GEOS | 3.8.1-CAPI-1.13.3 | Läuft mit GEOS | 3.8.1-CAPI-1.13.3
Kompiliert mit SQLite | 3.29.0 | Läuft mit SQLite | 3.29.0
PostgreSQL-Client-Version | 11.5 | SpatiaLite-Version | 4.3.0
QWT-Version | 6.1.3 | QScintilla2-Version | 2.10.8
Kompiliert mit PROJ | 6.3.2 | Läuft mit PROJ | Rel. 6.3.2, May 1st, 2020
BS-Version | Windows 10 (10.0)
Aktive Python-Erweiterungen | ClipMultipleLayers; clipper; contour; MapsPrinter; mask; mmqgis; OSMDownloader; PointConnector; QMetaTiles; qrbarcodeitem; QuickOSM; quick_map_services; shapetools; db_manager; MetaSearch; processing

</body></html>

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
> Aktive Python-Erweiterungen 	ClipMultipleLayers; clipper; contour; MapsPrinter; mask; mmqgis; OSMDownloader; PointConnector; QMetaTiles; qrbarcodeitem; QuickOSM; quick_map_services; shapetools; db_manager; MetaSearch; processing

@jumkiel plase try with a new QGIS profile, no 3rd party plugins installed.
