### ISSUE TITLE
Crash ID: 446c06492f0086acdb2c1bad430a814856643bc8

### ISSUE THREAD

**Issue by janhow** [qgis/QGIS#46008]
### What is the bug or the crash?

Crash ID: 446c06492f0086acdb2c1bad430a814856643bc8

### Steps to reproduce the issue

I press the CRS button it crashes. I add a new layer it ceashes.

### Versions

QGIS version
3.16.13-Hannover
QGIS code revision
a8618a94
Compiled against Qt
5.15.2
Running against Qt
5.15.2
Compiled against GDAL/OGR
3.3.3
Running against GDAL/OGR
3.3.3
Compiled against GEOS
3.10.0-CAPI-1.16.0
Running against GEOS
3.10.0-CAPI-1.16.0
Compiled against SQLite
3.35.2
Running against SQLite
3.35.2
PostgreSQL Client Version
13.0
SpatiaLite Version
5.0.1
QWT Version
6.1.3
QScintilla2 Version
2.11.5
Compiled against PROJ
8.2.0
Running against PROJ
Rel. 8.2.0, November 1st, 2021
OS Version
Windows 10 Version 2009
Active python plugins
QWater; 
SemiAutomaticClassificationPlugin; 
db_manager; 
MetaSearch; 
processing

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@janhow please try with a new QGIS profile, no 3rd party plugins installed.
