### ISSUE TITLE
Crash exporting report

### ISSUE THREAD

**Issue by dario955i** [qgis/QGIS#46002]
### What is the bug or the crash?

Hi, I have a Qgis file with a report.
If I open this report and press export to pdf without entering first in any section, qgis crashes.

If I enter in a group section of the report and then I press export pdf everything goes well.

I have 3.16.12 standalone version and 3.16.13 network version. Crash happens in both versions.

Thanks in advance.

### Steps to reproduce the issue

1. Go to report
2. click on export pdf
3. crash

### Versions

3.16.12 standalone version
3.16.13 network version

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@dario955i please try with a new QGIS profile, no 3rd party plugins installed.

**Comment by dario955i** [comment]
What's the workflow?
Create new  profile > open file?

That's all?

Or I have to uncheck all my plugins?

Il Gio 11 Nov 2021, 18:10 Giovanni Manghi ***@***.***> ha
scritto:

**Comment by gioman** [comment]
> Create new profile > open file?

@dario955i 

settings > user profiles > new profile



> Or I have to uncheck all my plugins?

it not enough, we the need the users to test with a new QGIS profile.

**Comment by dario955i** [comment]
new profile, no plugins. same result: Qgis crashes
thanks

Il giorno gio 11 nov 2021 alle ore 18:34 Giovanni Manghi <
***@***.***> ha scritto:

**Comment by gioman** [comment]
> * Go to report
> 
> * click on export pdf
> 
> * crash

Confirmed with this very simple steps. Also on 3.22.0.

**Comment by gioman** [comment]
This is a regression, it works fine on previous QGIS releases, probably the break happened when moving from osgeo42 v1 to v2.

**Comment by dario955i** [comment]
Please note that of I edit a group of this report and then I press export to pdf, everything works well

I’m not using 3.22, but 3.16.13

I can try also with 3.22 

_

Il giorno 11 nov 2021, alle ore 19:25, Giovanni Manghi ***@***.***> ha scritto:

﻿
This is a regression, it works fine on previous QGIS releases, probably the break happened when moving from osgeo42 v1 to v2.

**Comment by dario955i** [comment]
update: 3.22 crashes as well

Il giorno gio 11 nov 2021 alle ore 20:31 Dario ***@***.***> ha
scritto:

**Comment by jef-n** [comment]
hm, 3.16.13 crashes also on osgeo4w v1 and master on Linux on exporting a fresh empty report.

**Comment by gioman** [comment]
> hm, 3.16.13 crashes also on osgeo4w v1

ok, I didn't had at hand a v1 install of 3.16, only 3.4 and 3.10.

**Comment by romainbh** [comment]
Same bug, happens on QGIS 3.16, 3.18, 3.20, 3.22. Works fine on 3.10.
(tested on W10x64 with OSGeo4W, the old one and the new one)

**Comment by agiudiceandrea** [comment]
@romainbh thanks for checking.
Anyway, this issue should have been already fixed in master, 3.16 and 3.22 branches by https://github.com/qgis/QGIS/commit/4690ed07f0a1c143f0c9c275a939d1e2ffb05f8c, https://github.com/qgis/QGIS/commit/3d236b0b06cce51f4c622e732bbfe6d3fece50c6, https://github.com/qgis/QGIS/commit/11ff1fabf4b47a025fb5bfe7025f56831fb369be.
Could you test using the latest qgis-dev, or qgis-ltr-dev or qgis-rel-dev packages from OSGeo4W v2 or qgis-ltr-dev from OSGeo4W v1?

**Comment by romainbh** [comment]
@agiudiceandrea thanks for your response. 
I've checked with qgis-dev on OSGeo4W v2 and it works! Thank you!
For info, I get however to error messages in the main QGIS window (don't now if it's important):
![image](https://user-images.githubusercontent.com/18001925/142178540-b781c065-9c40-48cc-8ec7-bcb0e96c1606.png)
![image](https://user-images.githubusercontent.com/18001925/142178571-0bd8e234-d79a-4b89-ae9c-b3919d74faa2.png)

**Comment by gioman** [comment]
>  the main QGIS window (don't now if it's important):

@romainbh no it is not, is normal stuff in the master/devs builds.
