### ISSUE TITLE
Vector Field in Modeler

### ISSUE THREAD

**Issue by PierreGravelRNCAN** [qgis/QGIS#46011]
### What is the bug or the crash?

I want to use an attribute as parameter to provide buffer values to the "variable distance buffer" algorithm.
I tried "Vector Field" input in the modeler but it doesn't work. The attribute is present upstream in my workflow in modeler but the attribute is not detected. When I run the modeler, I can not identify or select the layer where the attribute is.
![image](https://user-images.githubusercontent.com/49731624/141482300-9393ff59-58ce-4cec-9cf7-cc39da66aed6.png)

### Steps to reproduce the issue

[NB_Normalization_roadcenterline_to_polygon.zip](https://github.com/qgis/QGIS/files/7528308/NB_Normalization_roadcenterline_to_polygon.zip)

### Versions

I tried with 3.16.1 and 3.20.0

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
> I tried with 3.16.1 and 3.20.0

@PierreGravelRNCAN they are both way too old. Please test on 3.16.3 and/or 3.22.0

**Comment by PierreGravelRNCAN** [comment]
I will. I'm waiting for my IT team install 3.22.0 on my workstation.
Thanks

**Comment by roya0045** [comment]
Just write the name manually, the modeler has no way to know which field will be present in the output of the previous tool and in every  execution. I'm not sure why the field input didn't work though, I assume you did link it to the input of the model and its parent layer?

**Comment by pathmapper** [comment]
To illustrate what I think @roya0045 meant:

<img src="https://user-images.githubusercontent.com/20856381/141510533-33275f15-784a-427c-b1dc-6b01029e7f6f.png" width="500px">

**Comment by PierreGravelRNCAN** [comment]
Oh. Many thanks for the tip pathmapper !
