### ISSUE TITLE
Intersection of polygons creates features from edges when coordinates are rounded to 2 decimal places 

### ISSUE THREAD

**Issue by phidrho** [qgis/QGIS#46017]
### What is the bug or the crash?

My source data (polygons) is always rounded to 2 decimal places.
I was doing some intersections today and got some weird intersected polygons for result - their geometry is an edge between two polygons.

I then tried to randomly draw two polygons in two "New scratch layers" which touch each other and tried to intersect them but there was nothing intersected as expected since they only have the same edge.

The only difference between my real example and this other one - in which I tried to recreate bug - is that coordinates in my input data is strictly rounded to 2 decimal places (rounded to centimeters in projection) and data is coming as Multypolygons instead of Polygons which I used in "New scratch layers".

I tried it on Windows 3.18.3-dev and Linux 3.16.3 and got the same results.
I also tried with shp and gpkg formats as input layers for intersection and got same results in every case. 

### Steps to reproduce the issue

I am attaching project file with sample data.
Intersect layer1 with layer2 - there should be no intersected features as features only touch each other but there are always two features created from edges (see picture).

[sample project and data](https://github.com/qgis/QGIS/files/7530636/qgis_intersection_bug.zip)

![image](https://user-images.githubusercontent.com/1849293/141540674-714602fd-51ff-48d2-a51d-f92298a831e2.png)

### Versions

WINDOWS:

QGIS version
3.18.3-Zürich
QGIS code revision
735cc85be9
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.4.0dev
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
8.1.0
Running against PROJ
Rel. 8.1.0, July 1st, 2021
OS Version
Windows 10 (10.0)
This copy of QGIS writes debugging output.
Active python plugins
ImportPhotos; 
OSMDownloader; 
splitmultipart; 
SplitPolygon-master; 
Submission; 
wfsclient; 
db_manager; 
processing

KUBUNTU 18.04:
QGIS version | 3.16.3-Hannover | QGIS code revision | 94ac9f21b8
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 10.15 (Ubuntu 10.15-0ubuntu0.18.04.1) | SpatiaLite Version | 5.0.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Ubuntu 18.04.6 LTS
Active python plugins | SplitPolygon-master; InvisibleLayersAndGroups; qgis-maptiler-plugin; mmqgis; guided_offline_editing; qgis2web; pluginbuilder3; qfieldsync; MultiMaps; lockzoom; ntv2_transformations; db_manager; processing

</body></html>

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by phidrho** [comment]
possibly related to #35670

**Comment by uclaros** [comment]
This is not a bug, this is most probably your data, though I cannot check them at the moment.
You have to make sure your data is properly noded, ie polygon *e* should have a vertex where *A* and *b* intersect, and *b* should have a vertex where *A* touches it.
You can use *Snap features to layer* algorithm to achieve that, whose performance has been greatly improved in the last releases.

**Comment by phidrho** [comment]
Hi @uclaros,
please check the example that I attached. All data is properly connected to 2 decimal places as I noted above.
One layer comes from ACAD Map where I did topology checking and then exported to shp, other one comes from gml export where all data comes rounded to 2 decimal places which I then converted to gpkg.
The only thing I can do is to install the newest version of QGIS and then try again, but if someone has it already installed I would appreciate it if they can test it, that's why I prepared everything - it's less than 5 minutes of testing time.

**Comment by gioman** [comment]
> This is not a bug, this is most probably your data

@phidrho 

your layer1 have a vertex that is not identical to the correspondent in layer 2

```
501655.96000000002095476 5119794.41999999899417162
501655.96000000002095476 5119794.41999999992549419
```

The results you get are similar to the ones you get by creating a virtual layer (the collectionextaction part is necessary because the straight intersection generates also a point):

```
SELECT b.fid AS gid, 
ST_CollectionExtract(st_intersection(a.geometry,b.geometry),3) AS geometry
FROM lyr1_gpkg a, lyr2_gpkg b;
```

or PostGIS:

```
SELECT b.fid AS gid, 
ST_CollectionExtract(st_intersection(ST_Force2D(a.geom),b.geom),3)::geometry(POLYGON, 3765) AS geom 
FROM lyr1_gpkg a, lyr2_gpkg b;
```

and ogr2ogr:

```
ogr2ogr -f "GPKG" results.gpkg test_data.gpkg -dialect sqlite -sql "SELECT  ST_CollectionExtract(ST_Intersection(a.geom, b.geom),3) AS geometry FROM lyr1_gpkg a, lyr2_gpkg b" -nln intersection
```

**Comment by phidrho** [comment]
> ST_CollectionExtract

Hi @gioman, 

how did you get raw coordinates from data, I tried to get coordinates with geom_to_wkt in the expression editor and got all coordinates rounded to 2 decimal places.

from gpkg:
```
MultiPolygonZ (((
501655.96 5119794.42 0,
501646.94 5119808.23 0,
501646.86 5119808.63 0,
501654.96 5119809.66 0,
501665.02 5119795.56 0,
501655.96 5119794.42 0)))
```

from shp:
```
MultiPolygonZ (((
501655.96 5119794.42 0,
501646.94 5119808.23 0,
501646.86 5119808.63 0,
501654.96 5119809.66 0,
501665.02 5119795.56 0,
501655.96 5119794.42 0)))
```

**Comment by gioman** [comment]
> how did you get raw coordinates from data,

@phidrho plugin "get wkt".


The above test (postgis, ogr) seems to show clearly that the issue in the data, not QGIS.

**Comment by phidrho** [comment]
@gioman
Thanks, it seems I'll have to run `snap points to grid` before running intersection to get identical floating-point presentation of coordinates in all layers.

Coordinates should have been identical, but it seems that software which generated floating-point presentation (AutoCAD Map and GeomFromGML from spatialite in my case) have different algorithms to store coordinates as floating-point which caused "difference".
