### ISSUE TITLE
Some labelling options have disappeared

### ISSUE THREAD

**Issue by ivn951** [qgis/QGIS#46027]
####  Some options have disappeared - see comparison with the same dialog box as in version 3.16.12
**1 - QGIS 3.22.0**

![QGIS_3 22 0_macOS](https://user-images.githubusercontent.com/9998772/141679600-2bfdc0aa-a6cf-4d48-8681-b2531a538597.png)

**2 - 3.16.12 LTR**

![QGIS_3 16 12_macOS](https://user-images.githubusercontent.com/9998772/141679606-49b651e8-1d46-4d49-b1ff-655af5628823.png)

**Comment by roya0045** [comment]
They became the first element.... This is clearly not a bug but just a way to tidy up the UI.

**Comment by ivn951** [comment]
Sorry, but personally I haven't talked about bug, just about missing parts. For the fill and stroke color and stroke width, the features are missing "Expression String Builder".

**Comment by ivn951** [comment]
Sorry, but personally I didn't mention bugs, just missing parts. For the fill and stroke color and stroke width, the "Expression String Builder" functionality is missing.

**Comment by gioman** [comment]
> Sorry, but personally I didn't mention bugs, just missing parts

@ivn951 if it was missing would be a bug.


> For the fill and stroke color and stroke width, the "Expression String Builder" functionality is missing.

it just moved place:

https://user-images.githubusercontent.com/1951107/141741494-8e1bdb18-7425-4fdb-9fd5-a6f2e82b01e1.mp4

**Comment by ivn951** [comment]
@gioman Thanks
