### ISSUE TITLE
10 bit TIFF/PPM not displayed correctly

### ISSUE THREAD

**Issue by boxerab** [qgis/QGIS#46029]
### What is the bug or the crash?

I have decompressed a HiRISE RGB JP2 image
https://hirise.lpl.arizona.edu/ESP_011359_1695

Here is a section of the original JP2:
[ESP_011359_1695-317x91-4.jp2.zip](https://github.com/qgis/QGIS/files/7533986/ESP_011359_1695-317x91-4.jp2.zip)
which displays correctly in QGIS.

Here are three images decompressed from the origin HiRISE:
[grk.zip](https://github.com/qgis/QGIS/files/7533950/grk.zip)

They were generated by decompressing with Grok JPEG 2000 toolkit
https://github.com/GrokImageCompression/grok

For example:
`grk_decompress -i ESP_011359_1695_RGB.NOMAP.JP2 -o grk.bmp -d 1024,1024,2056,2056 -v`

The .tif and .ppm should display in QGIS with the same colours as the .bmp, which was rescaled from 10 bit to 8 bit.
But all three look different.

Here is how the colours should look like (the brown strip in the center of the image) :
https://hirise-pds.lpl.arizona.edu/PDS/EXTRAS/RDR/ESP/ORB_011300_011399/ESP_011359_1695/ESP_011359_1695_MRGB.abrowse.jpg

- GIMP displays the ppm and the bmp files correctly (tiff file won't open because GIMP doesn't support 10 bit)
- Krita displays 10 bit tiff correctly
- GraphicsMagick displays all three files correctly with `gm display grk.*`

### Steps to reproduce the issue

Simply open the three images in the zip file above.

### Versions

QGIS 3.22

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

Decompressing with Kakadu demo app gives the same result as with Grok

**Comment by gioman** [comment]
> The .tif and .ppm should display in QGIS with the same colours as the .bmp, which was rescaled from 10 bit to 8 bit.

@boxerab I would have look at what gdalinfo and gdal_translate return as QGIS uses GDAL to load that formats.

**Comment by boxerab** [comment]
@gioman thanks. So, GQIS uses gdal to load a TIFF file ?

**Comment by gioman** [comment]
> @gioman thanks. So, QGIS uses gdal to load a TIFF file ?

@boxerab yes.

**Comment by boxerab** [comment]
@gioman do you have any sample 10 bit TIFF images that are known to display correctly in QGIS ?
Are there 10 bit TIFF is the test suite, for example ?

**Comment by gioman** [comment]
>  Are there 10 bit TIFF is the test suite, for example ?

@boxerab not sure. Can't you create one with gdal_translate and the NBITS creation option? https://gdal.org/drivers/raster/gtiff.html

**Comment by boxerab** [comment]
@gioman nope, it rejects NBITS=10

**Comment by boxerab** [comment]
@gioman if there are no 10 bit test images, how do you test for 10 bit support ?

**Comment by boxerab** [comment]
@gioman here is some feedback 
I took the 10 bit image `grk.tif` and ran :

`gdal_translate -of GTiff -ot Byte -scale 0 1023 0 255 grk.tif  grk_8.tif`

This gives me the correct colours for the 8 bit TIFF

10 bit

![Screenshot from 2021-11-15 10-02-14](https://user-images.githubusercontent.com/95393/141804352-0a8d7fa0-6984-4c8d-886f-d204aed1664e.png)

8 bit

![Screenshot from 2021-11-15 10-02-29](https://user-images.githubusercontent.com/95393/141804378-9cbe5f89-e296-4d8e-99b8-18087a8d5ab5.png)

**Comment by boxerab** [comment]
> @boxerab I would have look at what gdalinfo and gdal_translate return as QGIS uses GDAL to load that formats.

Please see comment above  : I have provided @gioman with **feedback** for his question about `gdalinfo` and `gdal_translate`

**Comment by agiudiceandrea** [comment]
@boxerab what is the Operative System runnig on your system? What is the version of the GDAL library you are using via command line interface and what the one used by QGIS?

**Comment by boxerab** [comment]
> @boxerab what is the Operative System runnig on your system? What is the version of the GDAL library you are using via command line interface and what the one used by QGIS?

On Ubuntu 20
kernel: 5.11.0-16-generic

```
QGIS version | 3.10.14-A Coruña | QGIS code branch | Release 3.10
Compiled against Qt | 5.15.2 | Running against Qt | 5.15.2
Compiled against GDAL/OGR | 3.2.2 | Running against GDAL/OGR | 3.2.2
Compiled against GEOS | 3.9.0-CAPI-1.16.2 | Running against GEOS | 3.9.0-CAPI-1.16.2
Compiled against SQLite | 3.34.1 | Running against SQLite | 3.34.1
PostgreSQL Client Version | 13.2 (Ubuntu 13.2-1) | SpatiaLite Version | 5.0.1
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.6
Compiled against PROJ | 7.2.1 | Running against PROJ | Rel. 8.0.0, March 1st, 2021
OS Version | Ubuntu 21.04
Active python plugins | processing; MetaSearch
```

**Comment by agiudiceandrea** [comment]
@boxerab to display your grk.tif and grk.ppm 10bits raster layers in the same way the grk.bmp 8 bits raster layer is displayed in QGIS, you need to set the grk.tif and grk.ppm layer symbology to "Multiband color", then set the Min and Max parameters for the RGB bands to 0 and 1023 respectively (the "Contrast enhancement" and the "Min / Max Value Settings" parameters will be automatically set to "Stretch to MinMax" and "User defined" respectively).

This to ensure that QGIS will correctly "scale" the representation of the pixel RGB values from the 10 bits (0-1023) range.

**Comment by boxerab** [comment]
> @boxerab to display your grk.tif and grk.ppm 10 bits raster layers in the same way the grk.bmp 8 bits raster layer is displayed in QGIS, you need to set the grk.tif and grk.ppm layer symbology to "Multiband color", then set the Min parameter to 0 and the Max parameter to 1023 for each of the the RGB bands (the "Contrast enhancement" and the "Min / Max Value Settings" parameters will be automatically set to "Stretch to MinMax" and "User defined" respectively).
> 
> This to ensure that QGIS will correctly "scale" the representation of the pixel RGB values from the 10 bits (0-1023) range.

Thanks, @agiudiceandrea . Yes, this seems to fix the issue. But, there is still a bug.  Why is the original range for Red,
for example, equal to 241 -> 495 ?  This seems way off. How are these numbers generated ?

**Comment by agiudiceandrea** [comment]
@boxerab if you check the layer symbology settings when the layer is loaded in QGIS, probably you will see the following settings
![image](https://user-images.githubusercontent.com/16253859/146251515-d1514b64-9c6b-4b0d-872f-184ca5ce90e2.png)

This means that QGIS will removes "outliers" outside the 2% to 98% of the cumulative count of the value range calculate with an "Estimate" accuracy.

If you change the "Min / Max Value Settings" parameter to "Min / Max" instead of "Cumulative count cut" and apply the settings, you will see the minimum and maximum values of the pixels for each band in the raster calculate with an "Estimate" accuracy.
![image](https://user-images.githubusercontent.com/16253859/146252599-39ed62e9-3100-429a-8232-a3d8744c64a8.png)

If you change the "Accuracy" parameter to "Actual" instead of "Estimate", you will see the actual minimum and maximum values of the pixels for each band in the raster.
![image](https://user-images.githubusercontent.com/16253859/146252925-ff5388e9-352f-414d-a7c3-0b3d096915b9.png)

**Comment by boxerab** [comment]
Thanks, I saw those settings. Stepping back a bit, why does the 8 bit bmp image look so different from the 10 bit tiff image ? The bmp is just a scaled down version of the tiff - I would expect them to look identical.

**Comment by agiudiceandrea** [comment]
The pixels values in grk,bmp are already in the range 0-255 scaled from 0-1023. QGIS will display such layer by default without any  "Contrast enhancement" (No Enhancement).
If you change the symbology of that layer with "Contrast enhancement" set to "Stretch to MinMax" and "Min / Max Value Settings" set to "Cumulative count cut" or "Min / Max" it will look like the grk.tif and grk.ppm with the same settings.

**Comment by boxerab** [comment]
Thanks, I see that effect. Is there a way of loading the 10 bit tiff so that it displays by default with "No Enhancement" set ?

**Comment by agiudiceandrea** [comment]
I think it's not possible.
Anyway a 10 bit tiff will display really incorrect with "Contrast enhancement" set to "No Enhancement" because it's in the 0-1023 range instead of 0-255 range, so its "contrast" needs an "enhancement" i. e. needs to be stretched (actually shrank) from 0-1023 to 0-255.

**Comment by boxerab** [comment]
Thanks. So, I can get the 10 bit image to match the 8 bit by doing the following:

1. set "Min/Max Value Settings" to user defined
1. set range to 0-1023 for all colour bands

It would be nice to have a setting for this, but I suppose most users are happy with the current defaults.
I will close this - thanks @agiudiceandrea  !
