### ISSUE TITLE
MSI windows compilation

### ISSUE THREAD

**Issue by DavidHernandezLopez** [qgis/QGIS#46023]
### What is the issue about the documentation?

Is there a document for MSI-style compilation on windows (vstudio 2015)?
I have followed the current documentation but am getting errors 
C:\OSGeo4W\bin\py3_env.bat
C:\OSGeo4W\bin\qt5_env.bat
...

**Comment by roya0045** [comment]
This isn't the right place for questions, ask on the user or dev mailing list.
