### ISSUE TITLE
Labeling: Size type, meters at scale

### ISSUE THREAD

**Issue by Asfgl** [qgis/QGIS#46038]
### What is the bug or the crash?

QGIS 3.16.13 Seems to not be able to render the label if set too meters at scale.
Points does not have the same issue. This issue was not there on version 3.16.3 and 3.16.11.
![image](https://user-images.githubusercontent.com/60916625/141762105-5857c4a0-4839-43ef-98ea-b0495ac1c709.png)

### Steps to reproduce the issue

When layer is loaded and label is styled with perhaps the size set to 10.00 and size set as points.
Change points to meters at scale.
This will cause the labels to not render at all. 

### Versions

QGIS version
3.16.13-Hannover
QGIS code revision
a8618a94
Compiled against Qt
5.15.2
Running against Qt
5.15.2
Compiled against GDAL/OGR
3.3.3
Running against GDAL/OGR
3.3.3
Compiled against GEOS
3.10.0-CAPI-1.16.0
Running against GEOS
3.10.0-CAPI-1.16.0
Compiled against SQLite
3.35.2
Running against SQLite
3.35.2
PostgreSQL Client Version
13.0
SpatiaLite Version
5.0.1
QWT Version
6.1.3
QScintilla2 Version
2.11.5
Compiled against PROJ
8.2.0
Running against PROJ
Rel. 8.2.0, November 1st, 2021
OS Version
Windows 10 Version 2009
Active python plugins
autoSaver; 
FilterLayersAtOnce-master; 
FreehandRasterGeoreferencer; 
go2streetview; 
HCMGIS; 
mmqgis; 
nominatim; 
refFunctions; 
StreetView; 
VectorBender; 
db_manager; 
MetaSearch; 
processing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

We have not tried different profiles as we have multiple users in office all on 1 or two of their own profiles and we do not believe the issue to be profile related.

**Comment by gioman** [comment]
@Asfgl seems ok here on 3.16.13

![image](https://user-images.githubusercontent.com/1951107/141771441-b82183ea-5614-4ebe-bcf5-3b586fb58036.png)

**Comment by Asfgl** [comment]
With it set to points
![image](https://user-images.githubusercontent.com/60916625/141772019-bcc0d8b4-8bb1-49ea-b423-388d19545b2b.png)

This set to meters at scale
![image](https://user-images.githubusercontent.com/60916625/141772128-87d33a8f-3111-4f30-9dd0-464ef4e7338b.png)

**Comment by gioman** [comment]
> This set to meters at scale

@Asfgl what is the CRS of your project?

**Comment by Asfgl** [comment]
WGS 84 EPSG:4326

**Comment by gioman** [comment]
> WGS 84 EPSG:4326

@Asfgl see https://github.com/qgis/QGIS/issues/26749#issuecomment-926362086

**Comment by gioman** [comment]
Closing?

**Comment by Asfgl** [comment]
Thank you, I read the comment thread now and if the CRS is the issue, using an different build like QGIS 3.16.11 should give the same issue but it does not.
We use the the same project file with set CRS and the same postgres db.
My current solution is to roll-back to previous version. Should I close the issue?
