### ISSUE TITLE
GDAL Polygonize syntax error

### ISSUE THREAD

**Issue by jvdkwast** [qgis/QGIS#46045]
### What is the bug or the crash?

Polygonize (Raster to Vector) gives an error related to a change in the syntax of gdal_polygonize.py.

### Steps to reproduce the issue

1. Go in the main menu to Raster | Conversion | Polygonize (Raster to Vector) or use the tool from the Processing Toolbox
2. Add an input raster, keep the defaults, choose an output filename (tested on shapefile and GeoPackage, error unrelated to format)
3. Run and check error in log.

QGIS version: 3.16.13-Hannover
QGIS code revision: a8618a94
Qt version: 5.15.2
GDAL version: 3.4.0
GEOS version: 3.10.0-CAPI-1.16.0
PROJ version: Rel. 8.2.0, November 1st, 2021
Processing algorithm…
Algorithm 'Polygonize (raster to vector)' starting…
Input parameters:
{ 'BAND' : 1, 'EIGHT_CONNECTEDNESS' : False, 'EXTRA' : '', 'FIELD' : 'DN', 'INPUT' : 'Z:/delineation_Rur/catchment.sdat', 'OUTPUT' : 'Z:/Lesson_4/boundary3.shp' }

GDAL command:
gdal_polygonize.bat Z:/delineation_Rur/catchment.sdat Z:/Lesson_4/boundary3.shp -b 1 -f "ESRI Shapefile" boundary3 DN
GDAL command output:
usage: gdal_polygonize.py [-h] [-q] [-8] [-o [name=value ...]]

[-mask filename] [-nomask] [-b band]

[-of ogr_format]

src_filename dst_filename [dst_layername]

[dst_fieldname]

gdal_polygonize.py: error: unrecognized arguments: boundary3 DN

Execution completed in 0.45 seconds
Results:
{'OUTPUT': 'Z:/Lesson_4/boundary3.shp'}

Loading resulting layers
The following layers were not correctly generated.
• Z:/Lesson_4/boundary3.shp
You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.16.13-Hannover | QGIS code revision | a8618a94
-- | -- | -- | --
Compiled against Qt | 5.15.2 | Running against Qt | 5.15.2
Compiled against GDAL/OGR | 3.4.0 | Running against GDAL/OGR | 3.4.0
Compiled against GEOS | 3.10.0-CAPI-1.16.0 | Running against GEOS | 3.10.0-CAPI-1.16.0
Compiled against SQLite | 3.35.2 | Running against SQLite | 3.35.2
PostgreSQL Client Version | 13.0 | SpatiaLite Version | 5.0.1
QWT Version | 6.1.3 | QScintilla2 Version | 2.11.5
Compiled against PROJ | 8.2.0 | Running against PROJ | Rel. 8.2.0, November 1st, 2021
OS Version | Windows 10 Version 2009
Active python plugins | pcraster_tools; pdokservicesplugin; qgis-maptiler-plugin; QuickOSM; quick_map_services; SpreadsheetLayers; db_manager; MetaSearch; processing

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

Tested on CLI (OSGeo4W shell), same problem.
Found on GDAL website that syntax of gdal_polygonize.py has changed: https://gdal.org/programs/gdal_polygonize.html#gdal-polygonize
It doesn't take the dst filename. Tested on CLI without dst filename and it works then.

![image](https://user-images.githubusercontent.com/1172662/141794252-097d1bde-b24c-4362-a0d8-96d4d0552fd4.png)

However, the output is also different: it creates a folder with the [layer] argument and a file with the [fieldname] argument. So in this case a folder with boundary3 and in that folder the shapefile DN.shp

**Comment by gioman** [comment]
@jvdkwast can you say in what gdal version tue change happened?

**Comment by jvdkwast** [comment]
@gioman Hard to tell. In the last course we have used the old dependencies with QGIS 3.16.11 (due to the SAGA upslope tool issue), which has GDAL 3.1.4. Then it still worked.

**Comment by alexbruy** [comment]
> It doesn't take the dst filename.

Hmm, according to the docs, it does accept destination file name.

**Comment by gioman** [comment]
> Hmm, according to the docs, it does accept destination file name.

Then maybe is a bug in the tool itself.

**Comment by jvdkwast** [comment]
> 
> 
> > It doesn't take the dst filename.
> 
> Hmm, according to the docs, it does accept destination file name.

You're right. I have overlooked the <out_file> argument. It also seems to work when I insert the out name before the [layer] argument as in the docs:
![image](https://user-images.githubusercontent.com/1172662/141797649-8d9d30c1-5902-4e2e-9146-cd9a040e29b1.png)

But it doesn't work if it's at the position where QGIS adds it.

**Comment by gioman** [comment]
> But it doesn't work if it's at the position where QGIS adds it.

Position should not matter, but may be it does in this case.
