### ISSUE TITLE
Automatically generate compiled landing page files via cmake

### ISSUE THREAD

**Issue by m-kuhn** [qgis/QGIS#46040]
### Feature description

Process is described here:
https://github.com/qgis/QGIS/tree/master/resources/server/src/landingpage

See also https://github.com/qgis/QGIS/pull/45802

**Comment by m-kuhn** [comment]
See also https://blog.joeyandres.com/2019/03/07/avoid-re-running-npm-yarn-in-cmake-targets/

CC @elpaso

**Comment by pathmapper** [comment]
Another advantage would be that we don't need to take extra care anymore if there are multiple landingpage PR's open at the same time or for landingpage backports.

I'll submit a PR with a first draft of a possible implementation shortly for feedback and testing the automatic build processes.
