### ISSUE TITLE
QGIS 3.16.0 crashes when trying to edit/create features

### ISSUE THREAD

**Issue by maxf33** [qgis/QGIS#46044]
### What is the bug or the crash?

Under QGIS 3.16.0, the software crashes when trying to edit features. Disabling all snapping options solves the issue. But a specific layer needs to be selected as a "snappable" layer. This is the one that will make QGIS crash.

Creating a new profile does't solve the issue.

### Steps to reproduce the issue

REPORT DETAILS:

Crash ID: 2de7d5831a2a5afe592739bdcad2669ed201cf79

Stack Trace

QgsGeometry::closestVertex :
QgsPointLocator::verticesInRect :
Index::~Index :
Index::~Index :
QgsPointLocator::nearestVertex :
QgsSnappingUtils::~QgsSnappingUtils :
QgsSnappingUtils::snapToMap :
QgsMapMouseEvent::snapPoint :
QgsMapToolAdvancedDigitizing::canvasMoveEvent :
QgsMapCanvas::mouseMoveEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.16.0-Hannover
QGIS code revision: 43b64b13f3
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

### Versions

QGIS version
3.16.0-Hannover
QGIS code revision
43b64b13f3
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
db_manager; 
MetaSearch; 
processing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
> Under QGIS 3.16.0,

@maxf33 way too old and unsupported. Plese try again with 3.16.11 (do not install 3.16.13 as is bugged) and if the problem persist reopen the ticket.

**Comment by gioman** [comment]
@maxf33 you must also try with a new QGIS profile with no 3rd party plugins.

Settings > user profiles > new profile
