### ISSUE TITLE
SHP defined CRS doesn't work (

### ISSUE THREAD

**Issue by mrnapop** [qgis/QGIS#46050]
### What is the bug or the crash?

Exporting to SHP file with a defined CRS does not stay in the file, as in once removed and imported back, or being imported to another GIS system, the layer is of 'unknown' CRS when exporting to CRS 2039, or doesn't change if exported to 3857, even after using 'Reproject layer'/'Assign projection'/'Define Shapefile projection'.

The problem is solved by exporting the SHP from QGIS 2.18, thus meaning the problem is likely with the current version. 

### Steps to reproduce the issue

Create a temp layer, export to SHP, define CRS to 2039 and it stays 'unknown' once removed and imported back, define 3857 and it goes to the default (2039 in my case).
![Capture](https://user-images.githubusercontent.com/52244730/141813443-749fa460-d56f-4874-b66e-11329ec46401.PNG)

### Versions

3.16.13

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
> 3.16.13

@mrnapop 3.16.13 has a very bad regression about projections, use 3.16.11 instead until further notice.
