### ISSUE TITLE
Export to DXF crash on fresh install of QGIS. No plugins installed

### ISSUE THREAD

**Issue by ssuelvesacisa** [qgis/QGIS#46063]
### What is the bug or the crash?

Go to Project, click on Import/Export, and click on Export project to DXF.

Then QGIS begin for 2 o 3 seconds and crash before show Export to DXF dialog. 

It happen to me allways.

QGIS Version 3.22.0_Bialowieza, Windows version 21H1 19043.1348.

## User Feedback

When I press the option Project->Import/Export->Export project to DXF, QGIS Desktop crash before it show Export Dialog.

## Report Details

**Crash ID**: [4c0de3da259ad0a49395c7fa294a91e3768565f3](https://github.com/qgis/QGIS/search?q=4c0de3da259ad0a49395c7fa294a91e3768565f3&type=Issues)

**Stack Trace**
<pre>
pal::LabelPosition::getId :
QgsDiscoverRelationsDialog::relations :
QgsDiscoverRelationsDialog::relations :
QgisApp::dxfExport :
QObject::qt_static_metacall :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.22.0-Bia?owie?a
QGIS code revision: d9022691f1
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.2
Running against GDAL: 3.3.3

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

### Steps to reproduce the issue

Go to Project, click on Import/Export, and click on Export project to DXF.

After 2 o 3 second thinking QGIS crash without show Export dialog.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

Versión de QGIS | 3.22.0-Białowieża | Revisión del código de QGIS | d9022691f1
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
Compilado contra GDAL/OGR | 3.3.2 | Ejecutándose contra GDAL/OGR | 3.3.3
PROJ version | 8.1.1
EPSG Registry database version | v10.038 (2021-10-21)
GEOS version | 3.10.0-CAPI-1.16.0
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

I tried with new profile with same result. No plugins installed. Fresh installation of QGIS.

**Comment by gioman** [comment]
> It happen to me allways.

@ssuelvesacisa not crashing here with some random data. Can you attach here some dataset that makes your QGIS crash? Thanks.

**Comment by ssuelvesacisa** [comment]
More or less I discovered what it's the problem.

My project was create with QGIS 2.18 (Las Palmas), and I opened with the new QGIS 3.22. 

I'd been removing layers to discover that QGIS crash in Export to DXF when I have include Google Satellite or Google Road layers. Its properties are:

Title:	Google Satellite
Credit:	Map data ©2015 Google
URL:	https://mt1.google.com/vt/lyrs=s&x={x}&y={y}&z={z}
yOrigin:	Top (yOriginTop=1)
Zoom range:	0 - 20
Layer Extent:	Not set
------------------------------------------------------
Title:	Google Road
Credit:	Map data ©2015 Google
URL:	https://mt1.google.com/vt/lyrs=m&x={x}&y={y}&z={z}
yOrigin:	Top (yOriginTop=1)
Zoom range:	0 - 20
Layer Extent:	Not set

When I open my project in QGIS 2.18 I can see properties option with right mouse click over these two layers.

 In QGIS 3.22 propertie option dosen't appear and when you mark as visible these two layer, no show it. In QGIS 2.18 works fine.

Removing these layers Export to DXF works!.

**Comment by gioman** [comment]
> In QGIS 3.22 propertie option dosen't appea

@ssuelvesacisa those layer were added with a plugin I guess?

**Comment by ssuelvesacisa** [comment]
Yes, but I'm not sure if was added with "QuickMapServices" or "OpenLayer Plugin", three years ago.

**Comment by gioman** [comment]
> Yes, but I'm not sure if was added with "QuickMapServices" or "OpenLayer Plugin", three years ago.

@ssuelvesacisa you should remove those layers, and re-add them in QGIS 3 using both plugins, then text the export.
