### ISSUE TITLE
QGIS uses very long to start up connecting database with around 7000 geometry table and 6000 other tables

### ISSUE THREAD

**Issue by larsop** [qgis/QGIS#46074]
### What is the bug or the crash?

In the original query [here](https://explain.depesz.com/s/R7ea) and it us using 1,769,178.092 ms.

The problem seems to be related number rows in geometry_columns

If replace the line 

`AND (n.nspname,c.relname,a.attname) NOT IN (SELECT f_table_schema,f_table_name,f_geometry_column FROM geometry_columns) 
`
with 

`AND NOT EXISTS (SELECT 1 FROM geometry_columns WHERE f_table_schema = n.nspname AND f_table_name = c.relname AND f_geometry_column = a.attname)
`

The execution time is down to 394.611 ms and the  [new](https://explain.depesz.com/s/vghG) plan is here

In the query below

```
SELECT c.relname,n.nspname,a.attname,c.relkind,CASE WHEN t.typname IN ('geometry','geography','raster') THEN t.typname ELSE b.typname END AS coltype,obj_description(c.oid) 
FROM pg_attribute a JOIN pg_class c ON c.oid=a.attrelid JOIN pg_namespace n ON n.oid=c.relnamespace JOIN pg_type t ON t.oid=a.atttypid LEFT JOIN pg_type b ON b.oid=t.typbasetype 
WHERE c.relkind IN ('v','r','m','p','f') 
AND has_schema_privilege( n.nspname, 'usage' ) AND has_table_privilege( c.oid, 'select' ) AND (t.typname IN ('geometry','geography','raster') OR b.typname IN ('geometry','geography','raster')) AND n.nspname='prosj_dyrkbarjord' 
AND (n.nspname,c.relname,a.attname) NOT IN (SELECT f_table_schema,f_table_name,f_geometry_column FROM geometry_columns) 
AND (n.nspname,c.relname,a.attname) NOT IN (SELECT f_table_schema,f_table_name,f_geography_column FROM geography_columns) 
AND (n.nspname,c.relname,a.attname) NOT IN (SELECT "r_table_schema","r_table_name","r_raster_column" FROM raster_columns)

```

### Steps to reproduce the issue

Start qgis and connect to a Postgis database

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.16.5-Hannover | QGIS code revision | 58ba7c1ed6
-- | -- | -- | --
Compiled against Qt | 5.14.2 | Running against Qt | 5.14.2
Compiled against GDAL/OGR | 3.2.1 | Running against GDAL/OGR | 3.2.1
Compiled against GEOS | 3.9.1-CAPI-1.14.2 | Running against GEOS | 3.9.1-CAPI-1.14.2
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.4
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | macOS Mojave (10.14)
Active python plugins | poiexport; QuickWKT; pgtopoeditor; qgis_server_render_geojson; processing; db_manager; MetaSearch

</body></html>

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
> If replace the line
> 
> `AND (n.nspname,c.relname,a.attname) NOT IN (SELECT f_table_schema,f_table_name,f_geometry_column FROM geometry_columns) ` with
> 
> `AND NOT EXISTS (SELECT 1 FROM geometry_columns WHERE f_table_schema = n.nspname AND f_table_name = c.relname AND f_geometry_column = a.attname) `

@larsop can you submit a patch?

**Comment by larsop** [comment]
> > If replace the line
> > `AND (n.nspname,c.relname,a.attname) NOT IN (SELECT f_table_schema,f_table_name,f_geometry_column FROM geometry_columns) ` with
> > `AND NOT EXISTS (SELECT 1 FROM geometry_columns WHERE f_table_schema = n.nspname AND f_table_name = c.relname AND f_geometry_column = a.attname) `
> 
> @larsop can you submit a patch?

I can try.

**Comment by gioman** [comment]
> I can try.

that would be very nice!

**Comment by larsop** [comment]
Sorry  I was not able build qgis on my mac running 12.0.1. 

I end with this error. "ld: library not found for -lSystem"

I may try brew upgrade and check if that helps

**Comment by larsop** [comment]
Thanks for merge and back port, then I close it.
