### ISSUE TITLE
Attachment widget: "default path" is completely ignored

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#46077]
### What is the bug or the crash?

The "default path" in the attachment widget (maybe also others) is said to:

`"When not empty, always open the file selector at the root of this path for searching new files. If empty, the last used path of this editor widget will be used. If this editor widget has never been used by the user, the project path will be used."`

but nothing of the above happens, and when clicking the button to look for a file it always default to some folder that is OS dependent.

### Steps to reproduce the issue

Local scenario

postgis geometryless table

text field, with "attachment" widget.

### Versions

QGIS 3.16.13 and 3.22.0 on Win10.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by Djedouas** [comment]
Still present on master.

After investigations, it's because the default file name is `NULL` so it's not an empty filename.

The default path is used if the filename is empty when clicking on the `...` browse button (@gioman can you confirm?).

I will make a pull request to fix that.

**Comment by gioman** [comment]
> browse button (@gioman can you confirm?).

@Djedouas let me check

**Comment by gioman** [comment]
> The default path is correctly used if the filename is empty when clicking on the `...` browse button (@gioman can you confirm?).

@Djedouas yes I confirm, but this do not solves the

`"If empty, the last used path of this editor widget will be used"`

part because if I choose a file that is not in the default path, then when adding a new feature clicking the "..." button does not open the lat used path, but the default one instead.

Also this do not seems to work 

`"If this editor widget has never been used by the user, the project path will be used."`

in a new profile I saved a project and the "..." did not opened the project path/location.

**Comment by Djedouas** [comment]
>  if I choose a file that is not in the default path, then when adding a new feature clicking the "..." button does not open the lat used path, but the default one instead.

In fact what you describe is exactly what is expected : 

`"When not empty` [i.e. when the default path in the widget configuration is not empty] `, always open the file selector at the root of this path for searching new files."`

**Comment by Djedouas** [comment]
> Also this do not seems to work
> 
> "If this editor widget has never been used by the user, the project path will be used."

This behavior is intended when the default path in the widget configuration is empty, is that your case?

It's working on a clean profile for me, clicking on the "..." after having emptied the "NULL" value from the filename

**Comment by gioman** [comment]
> In fact what you describe is exactly what is expected : 

@Djedouas right

**Comment by gioman** [comment]
> This behavior is intended when the default path in the widget configuration is empty, is that your case?

@Djedouas no, it does not work as expected. I just tried again on 3.22.1 with a new profile, and a saved project with the default path empty: when clicking "..." the folder that opens is "C:\OSGeo4W\bin". If I choose a file in a different folder, then adding a new feature will still default to "C:\OSGeo4W\bin". This is not according to the description, or am I wrong?

**Comment by Djedouas** [comment]
> @Djedouas no, it does not work as expected. I just tried again on 3.22.1 with a new profile, and a saved project with the default path empty: when clicking "..." the folder that opens is "C:\OSGeo4W\bin". If I choose a file in a different folder, then adding a new feature will still default to "C:\OSGeo4W\bin". This is not according to the description, or am I wrong?

You're right, this is not according to the description.

I can reproduce this problem if I leave "NULL" in the text zone.

If I clear the text zone each time before clicking on "..." I get the correct behavior.

What I understand and confirm reading the code, is that if there is something in the text zone which is a non-existent path, then Qt will open a pop up in the folder of qgis executable.
