### ISSUE TITLE
Both versions of MAC download wouldn'topen

### ISSUE THREAD

**Issue by Tomaj105** [qgis/QGIS#46085]
### What is the bug or the crash?

I downloaded the newest and the older version of Mac software due to an apparent security issue.
 "Apple can't check it for malicious software" Contact developer for more information.
Please advise. Thx and rgds JCL

### Steps to reproduce the issue

download and sart the software on a Mac with the latets iOS

### Versions

22 and 16

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@Tomaj105 

https://github.com/qgis/QGIS/issues/34018#issuecomment-578186707

**Comment by Tomaj105** [comment]
Grazie, Giovanni :-) Adesso funziona.
Gentili saluti dal Carso

Jurij Clemenz, dr. med.

IDEJE, KONCEPTI IN ZGODBE
Tomaj 105, 6221 Dutovlje, Slovenija
+386 41 635 106
www.ikz.si <https://www.ikz.si/>; ***@***.*** ***@***.***>






To sporočilo in vsi pripeti dokumenti so zaupni in namenjeni izključno naslovniku. Kakršnakoli objava, prenos ali uporaba s strani tretje osebe je prepovedana. Če ste dobili to sporočilo po pomoti, vas prosimo, da o tem obvestite pošiljatelja, prejeto sporočilo pa takoj izbrišete.
This message and all attached documents are exclusively dedicated to the addressee only and confidential. Any use, publication or dissemination of this message and its contents are forbidden. If you accidentally received it, please notify the sender and immediately destroy it.
