### ISSUE TITLE
Random crashes using split features tool

### ISSUE THREAD

**Issue by cesarargul** [qgis/QGIS#46081]
### What is the bug or the crash?

Using the split features tool QGIS randomly crashes just at the moment of cutting the feature.

Screenshot of the crash report:
![imagen](https://user-images.githubusercontent.com/593293/142165600-f3f2cecb-843e-4c7b-8fd7-e9d72b358cb7.png)

### Steps to reproduce the issue

1. Start editing a layer.
2. Select a feature.
3. Activate the split features tool.
4. Draw the cut line.
5. Right click to finish the cut line.

This is the moment when we get the crash. This error seems to happen randomly. After restart QGIS if we try to cut the same feature it will work ok. Sometimes happens at the first cut, sometimes after cutting dozens of lines.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.16.11-Hannover | QGIS code revision | 26cc1c76
-- | -- | -- | --
Compiled against Qt | 5.15.2 | Running against Qt | 5.15.2
Compiled against GDAL/OGR | 3.3.1 | Running against GDAL/OGR | 3.3.1
Compiled against GEOS | 3.9.1-CAPI-1.14.2 | Running against GEOS | 3.9.1-CAPI-1.14.2
Compiled against SQLite | 3.35.2 | Running against SQLite | 3.35.2
PostgreSQL Client Version | 13.0 | SpatiaLite Version | 5.0.1
QWT Version | 6.1.3 | QScintilla2 Version | 2.11.5
Compiled against PROJ | 8.1.1 | Running against PROJ | Rel. 8.1.1, September 1st, 2021
OS Version | Windows 10 Version 2009
Active python plugins | BulkVectorExport; mapswipetool_plugin; nominatim_locator_filter; plugin_reloader; qfieldsync; qgis2web; QgisModelBaker; QPackage; QRealTime; QuickWKT; SerEIEL; shapefile_encoding_fixer; Spanish_Inspire_Catastral_Downloader; ValormasDiagnostico; db_manager; MetaSearch; processing

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

This is also happening in another computer with the 3.16.13 release.

We are now tring the 32bits version since yesterday and seems to work fine at the moment.

**Comment by gioman** [comment]
> Active python plugins 	BulkVectorExport; mapswipetool_plugin; nominatim_locator_filter; plugin_reloader; qfieldsync; qgis2web; QgisModelBaker; QPackage; QRealTime; QuickWKT; SerEIEL; shapefile_encoding_fixer; Spanish_Inspire_Catastral_Downloader; ValormasDiagnostico; db_manager; MetaSearch; processing

@cesarargul you checked that you tried with a new QGIS profile, but the above plugin list says you didn't really. You must try with a new QGIS profile and no 3rd party plugins installed.

**Comment by cesarargul** [comment]
Yes, we tried with a new profile.

In one of the machines we make a clean install, with no plugins. After that we only add a postgis connection.

**Comment by gioman** [comment]
> This is the moment when we get the crash. This error seems to happen randomly. After restart QGIS if we try to cut the same feature it will work ok. Sometimes happens at the first cut, sometimes after cutting dozens of lines.

@cesarargul does it happen only with a specific layer?

**Comment by gioman** [comment]
> At the moment we are working with two layers. One is MultiLineString and the other is a MultiPolygon layer. Crashes take place in both layers.

@cesarargul can you attach here the dump (of a portion) of one of this layers? thanks.
