### ISSUE TITLE
Dual Monitor with different Scaling causes some elements to be enlarged

### ISSUE THREAD

**Issue by cndnflyr** [qgis/QGIS#46102]
### What is the bug or the crash?

I have two monitors, both set to 1920x1080 resolution.  However, my primary monitor has scaling set to 125%. QGIS has been maximized on the secondary monitor (100% scaling).  Some of the elements in QGIS are displaying at 125% scaling, even though it is on the 100% scaled monitor.  Specifically the File Save Dialog and the Symbology Panel symbol selection (both circled in the following screenshot).
![image](https://user-images.githubusercontent.com/5660978/142344857-91e7df13-37c2-41c6-abaa-929b660cea84.png)
I have noticed this in the Symbology panel 

### Steps to reproduce the issue

Change the scaling of two monitors, open a save dialog from QGIS, and drag it back and forth between the monitors. 
Or
Drag QGIS between the monitors with the Symbology Panel docked and showing the symbology items as seen in the screenshot.

### Versions

![image](https://user-images.githubusercontent.com/5660978/142345202-892a3983-c2ea-4d90-9c99-9b0c80088b55.png)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by cndnflyr** [comment]
This has been reported by another user here: https://gis.stackexchange.com/questions/416619/qgis-dialogs-change-size-on-multi-monitor-setup

**Comment by gioman** [comment]
> 

@cndnflyr what operating system?

**Comment by cndnflyr** [comment]
windows 10, 21H1 I think. I'll have to check tomorrow.

**Comment by ejleguiah** [comment]
@cndnflyr have you get the solution for this problem?

**Comment by MSCAU** [comment]
I have an external monitor attached to my laptop (Windows 10) and only display on that (due to the greater size and ergonomics). When I accidentally nudge the dongle / cable, the laptop thinks I've disconnected the external monitor and tries to display on its own monitor for a second before reverting back. If I leave QGIS open across these occurrences, I get this eventually, which is almost unusable: 
![image](https://github.com/qgis/QGIS/assets/6926089/bb1c0b9c-18ca-4db8-8ecf-5bd93859621b)

**Comment by cndnflyr** [comment]
> 

No, I haven't found a solution yet. When I drag a QGIS window to the other monitor, it works ok. But the problem is usually when new windows pop up (Layout, Processing Tools, dialogs, etc.). Dialogs are often way to big for the screen, even though the text is a good size to read, I have to grab the edge and make smaller to be able to see the ok/cancel buttons. 

Current setup, Monitor 1 is my laptop screen, 15", 1920x1080, 125% scale. Monitor 2 is a 27" monitor, HDMI connection, 1920x1080, 100% scale.

**Comment by Mario-Valiante** [comment]
This issue still persists in 3.40 LTS (I am using Windows 11 24H2).
I use two monitors: the laptop display (2560×1440 at 150% scaling) and an external monitor (1920×1080 at 100% scaling).

I have noticed two separate issues that are not systematic, as they do not always occur:

1. Dragging windows from one monitor to the other sometimes causes the icons to become larger or smaller, as if the application attempts to maintain the same scaling on both monitors (e.g., 100% on the 2560×1440 laptop screen and 150% on the 1920×1080 external monitor).
2. Opening the same panel on the same screen (e.g., layer properties, attribute dialog when saving features, etc.) may result in a panel that appears either larger or smaller each time. Eventually, the panel becomes so large or small that I have to manually resize it to access the buttons.
