### ISSUE TITLE
"Reshape Feature" tool ignores "Avoid Overlap" setting from "Project Snapping Options" 

### ISSUE THREAD

**Issue by gimoya** [qgis/QGIS#46106]
### What is the bug or the crash?

If you reshape a polygon with the reshape tool (from the main menu), with "avoid overlap" option set for the layer, that you are editing, the newly produced polygon would still have overlap, if you digitize the one feature over the other feature's area. 

### Steps to reproduce the issue

1. Produce sample polygon layer with 2 features
2. Set "Project Settings" to "avoid overlap" for this layer 
3. Use "Reshape Feature" in Editing Mode
4. Pull a node of one feature over the area of the other feature and save edits
5. Result: Two overlapping features  

### Versions

QGIS version
3.12.3-București
QGIS code revision
8234261527
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
annotationManager; 
AustrianElevation; 
batch_gps_importer; 
FreehandRasterGeoreferencer; 
GeoCoding; 
GroupStats; 
isochrones; 
latlontools; 
networks; 
nominatim_locator_filter; 
ORStools; 
profiletool; 
qchainage; 
Qgis2threejs; 
qgis2web; 
qgiscloud; 
qgis_resource_sharing; 
qlyrx; 
QNEAT3; 
QuickOSM; 
quick_map_services; 
shapetools; 
SplitPolygonShowingAreas; 
SRTM-Downloader; 
track_profile_2_web; 
trail_elevation_stats; 
ViewshedAnalysis; 
db_manager; 
processing

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
>  3.12.3-București

@gimoya please also test on a supported version, like 3.6.11 or 3.22.0

**Comment by DelazJ** [comment]
And I'd add: in a new profile (ie without all these third-party plugins)

**Comment by alexbruy** [comment]
Duplicates #24884.
