### ISSUE TITLE
Server: Can't enable WFS3 API update endpoint (PUT/PATCH) on layers without geometry

### ISSUE THREAD

**Issue by lorenzogrv** [qgis/QGIS#46119]
### What is the bug or the crash?

When setting up the WFS capabilities for a project served through qgis-server, It's not posible to enable WFS Update on layers not having a geometry field.

This feels like a bug because It's possible to enable both "Insert" and "Delete" operations.

### Steps to reproduce the issue

1. Open a project having both layers with and without geometry
2. Go to 'Project' > 'Properties' > 'QGIS Server'
2. Expand 'WFS Capabilities'
3. Observe that layers without geometry can't have de "Update" checkbox, while they can be enabled for 'Insert' and 'Delete'

### Versions

Versión de QGIS | 3.16.13-Hannover | Revisión del código de QGIS | a8618a941b
-- | -- | -- | --
Compilado contra Qt | 5.9.5 | Ejecutándose contra Qt | 5.9.5
Compilado contra GDAL/OGR | 2.2.3 | Ejecutándose contra GDAL/OGR | 2.2.3
Compilado contra GEOS | 3.6.2-CAPI-1.10.2 | Ejecutándose contra GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
Versión del cliente PostgreSQL | 10.18 (Ubuntu 10.18-0ubuntu0.18.04.1) | Versión de SpatiaLite | 4.3.0a
Versión de QWT | 6.1.3 | Versión de QScintilla2 | 2.10.2
Versión de PROJ.4 | 493
Versión del SO | Linux Mint 19.3
Active python plugins | zoomrc; qfieldsync; qgis2web; pgRoutingLayer; GeoCoding; refFunctions; StreetView; OSMDownloader; nominatim; db_manager; MetaSearch; processing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

- I have double-checked it's not related to database GRANTs

**Comment by lorenzogrv** [comment]
Hi again!

I would like to share a bit more research I've done. After fiddling within project's xml source, I've found the section `<WFSTLayers>`, which seems to specify which operations are allowed. An excerpt:

```xml
...
<WFSTLayers>                                                                
      <Delete type="QStringList">                                               
        <value>layer_without_geom_ae4bf7f3_d23c_4b21_93cc_bcc346ac9fd1</value>       
        <value>layer_without_geom_2_b89cd802_2997_4d2e_9e00_c1a228d8c558</value>       
      </Delete>                                                                 
      <Insert type="QStringList">                                               
        <value>layer_with_geom_43c4836c_dc2b_4b85_bc20_20f98c5f1529</value>
        <value>layer_without_geom_3_c08670bf_93f9_4681_9687_6e1c44554a05</value>
        <value>layer_without_geom_2_ae4bf7f3_d23c_4b21_93cc_bcc346ac9fd1</value>
        <value>layer_without_geom_b89cd802_2997_4d2e_9e00_c1a228d8c558</value>
        <value>layer_without_geom_6_cad6bfa2_4b94_4389_aa57_f7b1992f5118</value>
      </Insert>
      <Update type="QStringList">
        <value>layer_with_geom_2_31baaffb_8ddd_4b51_b0ad_1a940460d61b</value>
        <value>layer_without_geom_2_43c4836c_dc2b_4b85_bc20_20f98c5f1529</value>
        <value>layer_without_geom_3_ae4bf7f3_d23c_4b21_93cc_bcc346ac9fd1</value>
        <value>layer_without_geom_4_b89cd802_2997_4d2e_9e00_c1a228d8c558</value>
      </Update>
    </WFSTLayers>
...
```

I've tried to manually edit here the `<Update>` and set the layer ids, but edit operations stay disabled.

I will save some time to create a Project with a reproducible example, and share it here.

**Comment by lorenzogrv** [comment]
I'm still working on a reproducible example

**Comment by pblottiere** [comment]
I cannot reproduce the issue on ArchLinux with master:

![nogeom](https://user-images.githubusercontent.com/9266424/152556297-ce387f3c-7a35-469b-9e4a-5ff62479fe7d.png)

> I'm still working on a reproducible example

Did you have time to work on a reproducible project? It'd be useful for investigating. 

Thanks!

**Comment by lorenzogrv** [comment]
Hello @pblottiere , and sorry for the late answer.

The issue happens with PostGIS-backed layers. I didn't had enough time to provide a complete reproducible example, including SQL to exemplify. The following cap was taken within an empty project, adding a non-geom table from a local postgresql database.

![Captura-qgis](https://user-images.githubusercontent.com/2481215/155101969-dc97c04b-a605-44b0-adf7-876ceaea9c97.png)

**Comment by mulfvik** [comment]
I have the same issue with QGIS versions up to 3.22.13. Would like to reopen this issue and fix this, what it seems to be, bug.
Backend is PostgreSQL/PostGIS

**Comment by pblottiere** [comment]
Due to the recent ping, I'm reopening this issue. 

Thanks to the last input (cf https://github.com/qgis/QGIS/issues/46119#issuecomment-1047591106), I can confirm that the `Update` widget looks strange in case of a PostgreSQL layer without geometry. Actually, the widget looks like a `QLineEdit` in this particular case:

![image](https://github.com/qgis/QGIS/assets/9266424/8f15e0e0-3f7f-413c-96be-e134ab2b3ef6)

I'm taking a look.
