### ISSUE TITLE
Raster calculator crash

### ISSUE THREAD

**Issue by yairlevy** [qgis/QGIS#46110]
## User Feedback

Raster calculator: subtraction between two simple rasters. This is the second time QGIS crashes during this process.

## Report Details

**Crash ID**: [f646874e2a51be67a18f6de95fa8d6a4c520b53e](https://github.com/qgis/QGIS/search?q=f646874e2a51be67a18f6de95fa8d6a4c520b53e&type=Issues)

**Stack Trace**
<pre>
QgsRasterCalculator::processCalculation :
QgisApp::showRasterCalculator :
QObject::qt_static_metacall :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.20.3-Odense
QGIS code revision: 495fbaec
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.1
Running against GDAL: 3.3.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

### Steps to reproduce the issue

1. Go to 'raster/raster calculator'
2. Click on the Raster Bands you would like to subtract to add them in a simple subtraction formula inside the "Raster Calculator Expression" window. Ex: "Raster Band 1" - "Raster Band 2".
3. Press "OK"
4. Process runs until 99% then QGIS crashes.

### Versions

**QGIS Info**
QGIS Version: 3.20.3-Odense
QGIS code revision: 495fbaec
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.1
Running against GDAL: 3.3.1

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

The rasters involved have relatively coarse resolution on a normal size area. Process is run on a brand new powerful laptop. My GIS project has many layers and these are not activated to free resources.

**Comment by gioman** [comment]
>  QGIS Version: 3.20.3-Odense

@yairlevy try 3.22.0 (3.20.3 is EOL) and a new QGIS profile (with no 3rd party plugins installed), if the problem persist attach a sample dataset.
