### ISSUE TITLE
"Create virtual layer" is broken

### ISSUE THREAD

**Issue by Koyaani** [qgis/QGIS#46116]
### What is the bug or the crash?

I can't open the dialog to create a new Virtual Layer.

### Steps to reproduce the issue

Layer > Create Layer > New Virtual Layer.... See error dialog

### Versions

QGIS version | 3.23.0-Master | QGIS code revision | c80ec66ce7
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.2.2
PROJ version | 7.2.1
EPSG Registry database version | v10.008 (2020-12-16)
GEOS version | 3.9.0-CAPI-1.16.2
SQLite version | 3.34.1
PostgreSQL client version | 13.5 (Ubuntu 13.5-0ubuntu0.21.04.1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 21.04

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

I tried with an older build (before 3.22), I didn't have this problem (with 3.22 neither)

**Comment by gioman** [comment]
This is also confirmed in 3.22.1 now.

**Comment by Koyaani** [comment]
@nirvn Do you think this could be related to the PR #45737?

**Comment by mkoenigb** [comment]
For those who are not able to update their QGIS version quickly themselves, I'd like to add the workaround using PyQGIS.
The bug only affects the GUI, so you can still create and modify a virtual layer using Python:

```lang-py
from qgis.core import QgsVectorLayer, QgsProject
initial_query = "Select * from mylayer"
vlayer = QgsVectorLayer("?query={}".format(initial_query), "vlayer", "virtual")
QgsProject.instance().addMapLayer(vlayer)
updated_query = "Select id, buffer(geometry,20) as geometry from mylayer where name = 'string'"
vlayer.setDataSource("?query={}".format(updated_query), "vlayer", "virtual")
```

**Comment by m4x300** [comment]
Thank you @mkoenigb this is a useful work around.  Problem also appears in #46025 and is still present in 3.22.3
