### ISSUE TITLE
QGIS 3.22 hangs or exits

### ISSUE THREAD

**Issue by kobusburger** [qgis/QGIS#46113]
### What is the bug or the crash?

QGIS 3.22 hangs or exits

### Steps to reproduce the issue

QGIS 3.22 hangs or exits when I work on my project (see bug report). 3.20 was stable

### Versions

QGIS version
3.22.0-Białowieża
QGIS code revision
d9022691f1
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.0
PROJ version
8.2.0
EPSG Registry database version
v10.038 (2021-10-21)
GEOS version
3.10.0-CAPI-1.16.0
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
kmltools
3.1.14
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

## User Feedback

I upgraded from 3.20 to 3.22 but 3.22 does not find some  layers and hangs or exits. 3.20 was stable but not 3.22.

## Report Details

**Crash ID**: [d6a57ff9e05abcd0b5e7760678f0f6a9582b9399](https://github.com/qgis/QGIS/search?q=d6a57ff9e05abcd0b5e7760678f0f6a9582b9399&type=Issues)

**Stack Trace**
<pre>
QgsRasterTransparencyWidget::syncToLayer :
QgsRasterTransparencyWidget::QgsRasterTransparencyWidget :
QgsRasterLayerProperties::QgsRasterLayerProperties :
QgisApp::showLayerProperties :
QgisApp::layerProperties :
QObject::qt_static_metacall :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QMenu::exec :
QMenu::exec :
QgsLayerTreeView::contextMenuEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.22.0-Bia?owie?a
QGIS code revision: d9022691f1
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.0
Running against GDAL: 3.4.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

**Comment by gioman** [comment]
@kobusburger have you tried with a new QGIS profile and no 3rd party plugins installed?

**Comment by kobusburger** [comment]
I tried with a new profile with no plugins and QGIS does not hang or exit.
Maybe the previous profile only works on previous versions.
But QGIS still does not recognise two ecw layers, even if I reselect the
ecw files (the other versions do recognise the ecw layers). QGIS 3.22 does
find the ecw files if I click on the path but it still does not load the
files.

**Comment by gioman** [comment]
> But QGIS still does not recognise two ecw layers, even if I reselect the ecw files (the other versions do recognise the ecw layers). QGIS 3.22 does find the ecw files if I click on the path but it still does not load the files.

@kobusburger this could be a separate issue that would need a separate ticket. If you will open it please say how you installed QGIS, with the standalone or network install, and if you used the latter if you did install the gdal-ecw library.
