### ISSUE TITLE
Opening CSV with CSVT file: file types not recognized

### ISSUE THREAD

**Issue by aroche** [qgis/QGIS#46117]
### What is the bug or the crash?

If the file types in the .csvt file are written with an upper-case first letter, [as prescribed by the OGR](https://gdal.org/drivers/vector/csv.html) driver, QGIS fails to correctly assign file types.

If all is written in lower case in .csvt file, it works fine. 

When directly dropping a CSV file with correct CSVT type definition into QGIS, field types are correctly recognized

### Steps to reproduce the issue

1. Create a test.csv file with the following data:
```
id,f1,f2,f3
01,0.3,0.8,1.4
12,0.2,78,13.4
```
2. create a test.csvt with one line as `"String","Real","Real","Real"`
3. Open Data source manager, delimited text and add the test.csv file
4. The first field type is not recognized correctly (Integer instead of String)

### Versions

Version de QGIS | 3.22.0-Białowieża | Révision du code | d9022691f1
-- | -- | -- | --
Version de Qt | 5.15.2
Version de Python | 3.9.5
Version de GDAL/OGR | 3.4.0
Version de Proj | 8.2.0
Version de la base de données du registre EPSG | v10.038 (2021-10-21)
Version de GEOS | 3.10.0-CAPI-1.16.0
Version de SQLite | 3.35.2
Version de PDAL | 2.3.0
Version du client PostgreSQL | 13.0
Version de SpatiaLite | 5.0.1
Version de QWT | 6.1.3
Version de QScintilla2 | 2.11.5
Version de l'OS | Windows 10 Version 1809
  |   |   |  
Extensions Python actives
changeDataSource | 3.1
french_locator_filter | 1.0.0
geometry_paster | 0.1.1
Go2NextFeature3 | 2.00
profiletool | 4.1.8
SpreadsheetLayers | 2.0.1
StreetView | 3.2
valuetool | 3.0.14
ViewshedAnalysis | 1.7
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99
sagaprovider | 2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

Seems to work fine in 3.16

**Comment by kannes** [comment]
It is fine for OGR so looks like it is indeed QGIS-side:
```
$ ogrinfo -so -al test.csv 
INFO: Open of `test.csv'
      using driver `CSV' successful.

Layer name: test
Geometry: None
Feature Count: 2
Layer SRS WKT:
(unknown)
id: String (0.0)
f1: Real (0.0)
f2: Real (0.0)
f3: Real (0.0)

```

**Comment by agiudiceandrea** [comment]
@kannes the bug occurs using the "Delimited Text" importing functionality, which is handled internally by the  QgsDelimitedTextProvider QGIS provider and not through the GDAL/OGR library.

**Comment by agiudiceandrea** [comment]
The attached WinZip archive [testcsv.zip](https://github.com/qgis/QGIS/files/7574682/testcsv.zip) contains the testcsv.csv ad testcsv.csvt files as described in the bug report.

With QGIS 3.16.5 on Windows (OSGeo4W v1) the testcsv layer has the following fields (from Layer Properties -> Fields)

- if imported using the drag and drop from the Browser Panel or from the Windows Explorer / File Explorer or using the Data Source Manager - Vector dialog window:

| Name | Type | Type name
| - | - | - |
| id | QString | String |
| f1 | double | Real |
| f2 | double | Real |
| f3 | double | Real |

- if imported using the Data Source Manager - Delimited Text dialog window:

| Name | Type | Type name
| - | - | - |
| id | QString | text |
| f1 | double | double |
| f2 | double | double |
| f3 | double | double |

**Comment by agiudiceandrea** [comment]
@elpaso I think I've managed to fix the issue. See https://github.com/qgis/QGIS/pull/46141.
