### ISSUE TITLE
QGIS crashes at startup when opening a project

### ISSUE THREAD

**Issue by MartinMartin1975** [qgis/QGIS#46115]
### What is the bug or the crash?

QGIS 3.22.0-3 crashes at startup when opening a project

### Steps to reproduce the issue

Crash ID: 4c56e11bb7dc7222bd9cf0a3320d54bd746eb7da

Stack Trace

QTextCodec::toUnicode :
providerMetadataFactory :
providerMetadataFactory :
providerMetadataFactory :
QgsVectorLayer::setDataProvider :
QgsVectorLayer::readXml :
QgsMapLayer::readLayerXml :
QgsProject::addLayer :
QgsProject::_getMapLayers :
QgsProject::readProjectFile :
QgsProject::unzip :
QgsProject::read :
QgisApp::addProject :
QgisApp::openProject :
QObject::qt_static_metacall :
QMenu::~QMenu :
QObject::qt_static_metacall :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.22.0-Bia�owie�a
QGIS code revision: d9022691f1
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.2
Running against GDAL: 3.3.3

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

### Versions

QGIS-OSGeo4W-3.22.0-3.msi

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@MartinMartin1975 create a new QGIS profile (with no 3rd party plugins in it) and try again.

**Comment by MartinMartin1975** [comment]
Cause of QGIS crashing during project opening discovered.

The problem is caused by large files, e.g. GeoJPG **23000px x 25000px** or GeoJPG **8000px x 15000px**.
QGIS 3.20 Odense opens it, QGIS 3.22 Bialowieza not.

The error is certainly NOT in my project, but in some QGIS 3.22 library.

**Comment by MartinMartin1975** [comment]
**Hopefully this bug will be fixed in QGIS 4.00.**

**Comment by gioman** [comment]
> The problem is caused by large files, e.g. GeoJPG **23000px x 25000px** or GeoJPG **8000px x 15000px**.

@MartinMartin1975 can you share/attach one of those?

**Comment by gioman** [comment]
> **Hopefully this bug will be fixed in QGIS 4.00.**

@MartinMartin1975 there will be a lot of other QGIS 3.* before 4. If is a regression it should be fixed quickly.

**Comment by MartinMartin1975** [comment]
👍 
It's 150 MB and costumer data.
I try it with blank file, sorry. EPSG: 102067, Czech Republic

The problem is not the GeoJPG structure, but purely the size in pixels. A smaller or resampled GeoJPG opens 3.22 without any problem
[_005_006_009_010_GRF_02__GEOJPG.zip](https://github.com/qgis/QGIS/files/7563871/_005_006_009_010_GRF_02__GEOJPG.zip)

**Comment by gioman** [comment]
> It's 150 MB and costumer data. I try it with blank file, sorry. EPSG: 102067, Czech Republic
> 
> The problem is not the GeoJPG structure, but purely the size in pixels. A smaller or resampled GeoJPG opens 3.22 without any problem [_005_006_009_010_GRF_02__GEOJPG.zip](https://github.com/qgis/QGIS/files/7563871/_005_006_009_010_GRF_02__GEOJPG.zip)

@MartinMartin1975 tested here, no crash.

**Comment by MartinMartin1975** [comment]
I see, you can load the file into the EMPTY project.

Try loading the file into a **LARGE complex** project in **QGIS 3.20 Odense**, it will be OK.
Then try opening that project in **QGIS 3.22 Bielovieza**. You'll see that QGIS 3.22 will crash.

I've tried loading it multiple times into multiple projects and multiple PC in QGIS 3.20 and then opening it in QGIS 3.22 and it always crashes in 3.22. I'm sure I'm not the only one who noticed this error. Probably some kind of memory problem with the size of buffer?

**Why am I interested in QGIS 3.22?**
**Version QGIS 3.20 is terribly slow**, almost like ArcGISPro2. (Perhaps more users have noticed this???)
I'm hoping that version QGIS 3.22 will be faster.
So I'll stay with QGIS 3.18 waiting for QGIS 4.
Progress is never linear. Just wait a few years.

**Comment by gioman** [comment]
>  Then try opening that project in **QGIS 3.22 Bielovieza**. You'll see that QGIS 3.22 will crash.

@MartinMartin1975 any chance you can put together a shareable minimal project that shows this problem?

**Comment by MartinMartin1975** [comment]
I'm sorry, but it would be quite complicated. The project is not some kind of test, but quite complex and full of data, and without data it probably wouldn't make sense. On the other hand, there are no on-the-fly transformations, the EPSG system is strictly Cartesian, there are no dependencies on plugins. All versions of QGIS that can open *.QGZ files opens my project. 

I'll try to simulate it with some data.
I'm sending a screenshot.

I thought it was a single file problem only, but it's probably a memory problem.
If I delete **one** large file in QGIS 3.20 Odense, it crashes in QGIS 3.22 Bielovieza on **second** large file. If I remove even second large file in QGIS 3.20 it crashes in QGIS 3.22 on the **third** large file........ and so on. 


Try this in your large project with large raster files...

![QGIS-3-22 Screenshot](https://user-images.githubusercontent.com/94619947/142619876-8406cbdb-814b-4216-b04c-99a745c0e50a.jpg)

**Comment by MartinMartin1975** [comment]
QGIS 3.22.1 the same. I'm waiting for QGIS 4 :-)

**Comment by gioman** [comment]
@MartinMartin1975 does the project have CSV files in it?

**Comment by MartinMartin1975** [comment]
OK, thank you,
**I removed one working auxiliary CSV layer and the project loaded properly.**

But you have to admit that the collapse of QGIS, when using CSV layers is a BIG BUG, because all previous versions of QGIS do not have the CSV layer problem. Would it be possible to fix the bug, please?

THANK YOU VERY MUCH, for your helpful advice, I appreciate it, as well as QGIS SW.

Martin

**Comment by gioman** [comment]
@MartinMartin1975 it is already fixed.

**Comment by Gustry** [comment]
Linked to https://github.com/qgis/QGIS/pull/46312 ?

**Comment by gioman** [comment]
> Linked to #46312 ?

it is.
