### ISSUE TITLE
Crash opening 3.16.11

### ISSUE THREAD

**Issue by paulolasa** [qgis/QGIS#46127]
### What is the bug or the crash?

I updated from version 3.16.8 and now it crashes everytime I open the new version.

### Steps to reproduce the issue

Crash ID: 472ea3512682a3798d2cecc71f612973b1cc7185

Stack Trace

QMetaObject::activate :
QHttpMultiPart::qt_metacast :
QSslKey::operator!= :
QSslKey::operator!= :
QMetaObject::activate :
QAbstractSocket::proxyAuthenticationRequired :
QMetaObject::activate :
QAbstractSocket::proxyAuthenticationRequired :
QNetworkProxyQuery::networkConfiguration :
QMetaObject::activate :
QAbstractSocket::disconnected :
QAbstractSocket::canReadLine :
QNetworkProxyQuery::networkConfiguration :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
QEventLoop::exec :
QThread::exec :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

### Versions

QGIS Info
QGIS Version: 3.16.11-Hannover
QGIS code revision: 26cc1c762f
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@paulolasa can you try with a new QGIS profile (no 3rd party plugins installed)? If you can't start QGIS (copy/backup and) delete your QGIS user folder.

**Comment by paulolasa** [comment]
> 
> 
> @paulolasa can you try with a new QGIS profile (no 3rd party plugins installed)? If you can't start QGIS (copy/backup and) delete your QGIS user folder.

Hi there @gioman, I don't have any 3rd party plugins. Sory to ask, how do I delete my QGIS user folder?
Thanks.

**Comment by gioman** [comment]
> Hi there @gioman, I don't have any 3rd party plugins. Sory to ask, how do I delete my QGIS user folder?

@paulolasa `C:\Users\yourusername\AppData\Roaming\QGIS`

**Comment by paulolasa** [comment]
> C:\Users\yourusername\AppData\Roaming\QGIS

Thanks a lot @gioman :) It worked :) I was getting crazy.
