### ISSUE TITLE
Advanced digitizing panel options do not work at intersections

### ISSUE THREAD

**Issue by rswmajor** [qgis/QGIS#46128]
### What is the bug or the crash?

Additional digitizing tools do not work at intersections.
![screenshot-2021-11-19 204652](https://user-images.githubusercontent.com/19249084/142632944-fc1c4d7b-f819-4e4a-bf16-b47bcefd4731.png)
in version 3.18 it works fine

### Steps to reproduce the issue

Additional digitizing tools do not work at intersections

### Versions

3.22

### Supported QGIS version

- [x] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@rswmajor can you please expand on  the concept of "Additional digitizing tools do not work at intersections" and tell us what are the steps to replicate the issue? thanks.

**Comment by rswmajor** [comment]
Create two lines that intersect. Turn on snapping to intersections. Create another line, the first point is anywhere, the second is at the intersection, the third point needs to be placed at an angle or parallel to the previous segment, and the gusset stops working

**Comment by gioman** [comment]
@rswmajor I edited the title. Seems also to me that with snapping on intersection the advanced digitizing panel options are not working on 3.22.

**Comment by rswmajor** [comment]
@gioman , ok, thanks. I noticed that snapping in the case of intersecting lines works from the point with coordinates 0,0, and not from the point of intersection

**Comment by Koyaani** [comment]
This problem seems a bit strange. If I reproduce this issue, create a line through the intersection and then delete this line, the issue disappears afterwards, but only for this intersection. And this even when closing QGIS, creating a new project and loading the layer.
