### ISSUE TITLE
TypeError in MetaSearch when adding WFS data

### ISSUE THREAD

**Issue by BathoryPeter** [qgis/QGIS#46135]
### What is the bug or the crash?

```
TypeError: QMainWindow.addVectorLayer() called with 3 arguments but 2 expected 
Traceback (most recent call last):
  File "/usr/share/qgis/python/plugins/MetaSearch/dialogs/maindialog.py", line 785, in addVectorLayer
    self.iface.mainWindow().addVectorLayer(path, name, 'WFS')
TypeError: QMainWindow.addVectorLayer() called with 3 arguments but 2 expected

```

### Steps to reproduce the issue

1. Open MetaSearch
2. Search for a dataset where Add data button is active
3. In Add data dropdown select Add WFS
4. In New WFS layer from a server dialog select any item from the list
5. Click to Add button
6. A Python error dialog appears

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS verzió | 3.22.0-Białowieża | QGIS kód változat | 1011cc3090
-- | -- | -- | --
Qt verzió | 5.15.2
Python verzió | 3.9.7
GDAL/OGR verzió | 3.2.2
PROJ verzió | 7.2.1
EPSG regisztrációs adatbázis verzió | v10.008 (2020-12-16)
GEOS verzió | 3.9.0-CAPI-1.16.2
SQLite verzió | 3.35.5
PDAL verzió | 2.2.0
Postgresql kliens verzió | 13.4 (Ubuntu 13.4-1)
SpatiaLite verzió | 5.0.1
QWT verzió | 6.1.4
QScintilla2 verzió | 2.11.6
OS verzió | Ubuntu 21.10
  |   |   |  
Aktív Python modulok
QuickWKT | 3.1
GeometryShapes | 0.7
quick_map_services | 0.19.26
latlontools | 3.5.7
numericalDigitize | 0.4.6
grassprovider | 2.12.99
sagaprovider | 2.12.99
processing | 2.12.99
MetaSearch | 0.3.5
db_manager | 0.1.20

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
> 3.22.0-Białowieża



> * Open MetaSearch
> 
> * Search for a dataset where Add data button is active
> 
> * In Add data dropdown select Add WFS
> 
> * In New WFS layer from a server dialog select any item from the list
> 
> * Click to Add button
> 
> * A Python error dialog appears

@BathoryPeter confirmed also on Win10. Does not happen on 3.16.13, regression.

**Comment by jonnyforestGIS** [comment]
I can confirm this behaviour in a QGIS fresh install.
