### ISSUE TITLE
WMS client shows wrong number os available CRSs for a lyer

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#46139]
### What is the bug or the crash?

This is on 3.16.13 as on 3.22 the list is **completely** wrong (see https://github.com/qgis/QGIS/issues/45918)

Available 5 --> but they are 4

![Screenshot 2021-11-20 140652](https://user-images.githubusercontent.com/1951107/142729408-499a9892-e879-490c-ade6-9e507ece8dca.png)

### Steps to reproduce the issue

Use the WMS client to connect to a WMS service that publishes layer in a specific number of CRSs, compare the "available" number with the real number of CRSs.

### Versions

QGIS 3.16.13. The service where I observed this is based on QGIS Server.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by jgrocha** [comment]
Hi @gioman 

I've done two tests and both worked as expected. One against Geoserver and another using MapProxy. I was not able to reproduce this issue with current master. Does not seems to be a client error.

**Example**

These are the CRS reported by the WMS Server (MapProxy in this case):

```xml
<Layer queryable="1">
<Title>MapProxy Proxy for QGIS Server by Geomaster</Title>
<CRS>EPSG:4326</CRS>
<CRS>EPSG:3763</CRS>
<CRS>EPSG:5016</CRS>
<CRS>EPSG:3061</CRS>
<CRS>EPSG:3857</CRS>
<EX_GeographicBoundingBox>
<westBoundLongitude>-38.79721887103212</westBoundLongitude>
<eastBoundLongitude>-5.955256885433881</eastBoundLongitude>
<southBoundLatitude>29.23999995500943</southBoundLatitude>
<northBoundLatitude>43.070000030542275</northBoundLatitude>
</EX_GeographicBoundingBox>
```

When I connect to this service, 5 CRS are reported.
![Screenshot from 2021-11-20 16-54-22](https://user-images.githubusercontent.com/163681/142734610-d03d5f99-a29a-4e84-a372-36af43ebf62e.png)

Since you are using QGIS Server, the problem might be in QGIS Server. Can you copy and paste here the capabilities document (the part that contains the available CRS) provided by the server?

**Comment by gioman** [comment]
> . I was not able to reproduce this issue with current master.

@jgrocha it seems weird to me you were not able to reproduce with master considered this https://github.com/qgis/QGIS/issues/45918 (which I also tested against Mapserver).

**Comment by gioman** [comment]
@jgrocha this is what the GetCapabilities/GetProjectInfo shows
```

<CRS>CRS:84</CRS>
<CRS>EPSG:5015</CRS>
<CRS>EPSG:4326</CRS>
<CRS>EPSG:3857</CRS>
<CRS>EPSG:32626</CRS>
```

I don't know where that `<CRS>CRS:84</CRS>` comes from considered how the project is set up:

![image](https://user-images.githubusercontent.com/1951107/142735926-b1c97614-866f-4388-901a-2351abd84944.png)

I agree that this seems more a server issue.

**Comment by jgrocha** [comment]
> @jgrocha this is what the GetCapabilities/GetProjectInfo shows
> 
> ```
> 
> <CRS>CRS:84</CRS>
> <CRS>EPSG:5015</CRS>
> <CRS>EPSG:4326</CRS>
> <CRS>EPSG:3857</CRS>
> <CRS>EPSG:32626</CRS>
> ```
> 
> I don't know where that `<CRS>CRS:84</CRS>` comes from considered how the project is set up:
> 

Right now, the `<CRS>CRS:84</CRS>` is added unconditionally to the output.

https://github.com/qgis/QGIS/blob/1d1d59d7fb069b90f0498d98f7c74708b8f841e3/src/server/services/wms/qgswmsgetcapabilities.cpp#L1407

As far as understand, **it is not mandatory**. From the [WMS 1.3.0 specification](https://portal.ogc.org/files/?artifact_id=14416):

_A WMS must support at least one CRS, and maps from multiple servers may be overlaid only if all the selected
servers have at least one CRS in common. This International Standard does not mandate support for any
particular Layer CRS(s). Instead, it only defines how CRSs are identified and discusses several optional Layer
CRSs, in this clause and in Annex B. Map providers may support the CRSs that are most useful and appropriate
to their geographic locale or information community. To maximize interoperability among servers, providers
should also support geographic coordinates by geocentric coordinate systems such as “CRS:84” (see 6.7.3.2),
“EPSG:4326” (see 6.7.3.3) or other ITRF-based systems._

Who creates the project should decided if he wants to provide such CRS or not.

If you think this is annoying (publishing a project with x CRS and the server returns x+1), we can remove `<CRS>CRS:84</CRS>` from the output. But it is almost irrelevant to have it there.

Maybe @rldhont, @elpaso, @sbrunner, @pblottiere or others can add they point of view.

**Comment by gioman** [comment]
> If you think this is annoying

@jgrocha for the casual user (and also for who set up a service) is **annoying** and **confusing**.
