### ISSUE TITLE
Crash when pressed "create new spatialite layer"

### ISSUE THREAD

**Issue by yiusinglau** [qgis/QGIS#46148]
### What is the bug or the crash?

The program crashes when I hit the "create new spatialite layer" button. 
`Warning: QObject::connect(QgsProviderMetadata, QgsProviderConnectionModel): invalid null parameter
Warning: QObject::connect(QgsProviderMetadata, QgsProviderConnectionModel): invalid null parameter
QGIS died on signal 11Could not attach to process.  If your uid matches the uid of the target
process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
ptrace: Operation not permitted.
No thread selected
No stack.
gdb returned 256
Aborted (core dumped)`

### Steps to reproduce the issue

1. Start the program
![image](https://user-images.githubusercontent.com/68449259/142758281-bc2fc3bb-c10a-4a8c-92d5-6a963f2eb46e.png)
2. Click on "new spatialite layer"
![image](https://user-images.githubusercontent.com/68449259/142758311-9816a14f-1d94-4477-bd7d-6474347a04c5.png)
![image](https://user-images.githubusercontent.com/68449259/142758370-2db15109-0e94-4a4c-ab2e-ca7c7d3b972f.png)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.0-Białowieża | QGIS code revision | d9022691f1
-- | -- | -- | --
Qt version | 5.12.8
Python version | 3.8.10
GDAL/OGR version | 3.0.4
PROJ version | 6.3.1
EPSG Registry database version | v9.8.6 (2020-01-22)
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
SQLite version | 3.31.1
PDAL version | 2.0.1
PostgreSQL client version | 12.8 (Ubuntu 12.8-0ubuntu0.20.04.1)
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.2
OS version | Ubuntu 20.04.2 LTS
  |   |   |  
Active Python plugins
sagaprovider | 2.12.99
grassprovider | 2.12.99
processing | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.5

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
@yiusinglau can't replicate on QGIS 3.22 (installed from QGIS.org's repos) and Linux Mint 20.2.
