### ISSUE TITLE
Exluding a print layout in project propteries -> server do not avoid that a GetPrint request can be done for that layout

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#46140]
### What is the bug or the crash?

According to the docs https://docs.qgis.org/3.22/en/docs/server_manual/getting_started.html#wms-capabilities

_" If you want to exclude any print layout from being published by the WMS, check checkbox Exclude layouts and click the signPlus button below. Then, select a print layout from the Select print layout dialog in order to add it to the excluded layouts list."_

As a fact an excluded layout will now show in the GetProjectSettings response, but will continue to work for GetPrint requests.

### Steps to reproduce the issue

Create a project with a print layout  and enable its server capabilities.

Exclude the print layout from the WMS capabilities.

Serve the project with QGIS Server.

With a browser send a GetPrint request using the excluded layout --> QGIS server will return the layout, but should not.

### Versions

QGIS Desktop and Server 3.16.13 and 3.22.0

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by pblottiere** [comment]
Confirmed on ArchLinux with master. I'm taking a look.

**Comment by gioman** [comment]
@pblottiere thanks!
