### ISSUE TITLE
QGIS crashes with combination of marker line and simple line

### ISSUE THREAD

**Issue by aetherman21** [qgis/QGIS#46147]
### What is the bug or the crash?

Hi,

Qgis is crashing everytime i combine a simple line and a marker line (with markers on central point of segments or on every vertex) in the symbology option. It happens with different vectorial databases.
This problem doesnt happens when i only put marker line (without simple line)

## Report Details

**Crash ID**: [edd74f6208274aabd76d490c68ce098a9d3a52ac](https://github.com/qgis/QGIS/search?q=edd74f6208274aabd76d490c68ce098a9d3a52ac&type=Issues)

**Stack Trace**
<pre>
QgsTemplatedLineSymbolLayerBase::renderPolylineVertex :
QgsTemplatedLineSymbolLayerBase::renderPolyline :
QgsMarkerLineSymbolLayer::renderPolyline :
QgsLineSymbol::renderPolylineUsingLayer :
QgsLineSymbol::renderPolyline :
QgsSymbol::renderFeature :
QgsFeatureRenderer::renderFeature :
QgsVectorLayerJoinInfo::setEditable :
QgsVectorLayerJoinInfo::setEditable :
QgsMapRendererParallelJob::renderLayerStatic :
QgsMapRendererParallelJob::renderingFinished :
QgsImageOperation::overlayColor :
QgsImageOperation::stackBlur :
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

### Steps to reproduce the issue

1. Add a vector database
2. Symbology
3. Add symbol layer
4. Select "marker line"
5. Select "on central point of segments" or "on every vertex".
6. Click OK and try to moove on the map if Qgis havn't already crashed.

### Versions

**QGIS Info**
QGIS Version: 3.16.13-Hannover
QGIS code revision: a8618a94
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.0
Running against GDAL: 3.4.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
> * Add a vector database
> 
> * Symbology
> 
> * Add symbol layer
> 
> * Select "marker line"
> 
> * Select "on central point of segments" or "on every vertex".
> 
> * Click OK and try to moove on the map if Qgis havn't already crashed.

@aetherman21 no crash here on QGIS 3.16.13 on Win10 with the above steps. Have you really tested on a new QGIS profile (with no 3rd party plugins)? If yes then please share a vector that in your case makes QGIS crash.

**Comment by aetherman21** [comment]
Hello,
Yes, i have tested with a new Qgis Profile, I've also made a new installation of 3.16 without any plugin.
There is my shapefile.

[data.zip](https://github.com/qgis/QGIS/files/7576183/data.zip)

**Comment by gioman** [comment]
> There is my shapefile.
> 
> [data.zip](https://github.com/qgis/QGIS/files/7576183/data.zip)

@aetherman21 still no crash here. You may want to add a screencast of the steps you are following, there may be some subtle detail in play.

**Comment by aetherman21** [comment]
Hello,

Thx for your help, here's a video of the process with the crash.

https://youtu.be/aASTWUpKr1E

**Comment by gioman** [comment]
> Thx for your help, here's a video of the process with the crash.

@aetherman21 yes, confirmed on 3.16.14, works fine on 3.22.1. Not sure if there was a fix about this that was not backported.

**Comment by aetherman21** [comment]
Okay, i'm trying on 3.22 then.

Thanks,
Pierre

**Comment by claasleiner** [comment]
I confirm the bug. When using marker lines, QGIS 3.16.14 crashes. The problem does not occur with 3.16.11 and 3.22. 
(GIS 3.16.14 // Ubuntu 16.04 with UbuntuGis dependencies. )
Claas Leiner

**Comment by claasleiner** [comment]
QGIS crashes when Polygon-Layer symbolized  with marker line (#46147)
The problem persists in qgis 3.16.15.
A polygon layer that is symbolized with a marking line causes QGIS to crash immediately. This is a serious problem because the marker lines are an important symbology tool.
Claas Leiner

**Comment by gioman** [comment]
> This is a serious problem because the marker lines are an important symbology tool.

@claasleiner not all fixes can be backported, maybe this is one of those cases.

**Comment by m-kuhn** [comment]
could you add a .qml file to trigger this issue?
