### ISSUE TITLE
Wrong GetPrint result when printing more than one map object

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#46142]
### What is the bug or the crash?

This is the scenario:

I have a project with 2 vector layers:

caop2019_sma (polygon)
caminhosflorestais_sma (lines)

one raster layer:

tinras_sma (a digital elevation model)

and one xyz baselayer that is not really important in this case.

I have one print layout with two map objects, map0 and map1 (more on the map objects ids in GetProjectSettings VS print composer in a separate ticket).

If I make a GetPrint with just one map object in the request then it all works as expected. Problems seems to arise when doing a GetPrint with both map objects and some specific combination of layers for map0 and map1.

1) if the raster layer is contained in both "LAYERS" list for map0 and map1 then the result is correct, for example:

`https://server/cgi-bin/qgis_mapserv.fcgi?map=/mnt/projecto.qgs&service=WMS&version=1.3.0&REQUEST=GetPrint&FORMAT=pdf&SRS=EPSG:5015&TRANSPARENT=true&DPI=150&TEMPLATE=horizontal_A4&map0:LAYERS=tinras_sma,caminhosflorestais_sma&map0:extent=658738.6370041518,4086597.012992168,679692.0389517528,4100615.836676158&map1:LAYERS=tinras_sma,caop2019_sma,caminhosflorestais_sma&map1:extent=662640.20483752,4088783.0770092523,668332.3820446859,4091691.262091459`

![image](https://user-images.githubusercontent.com/1951107/142737531-b970424e-63ce-410f-a4a1-8fb2ee04c36d.png)

2) if "LAYERS" for map0 contains the raster and "LAYERS" for map1 does not, then the result for map0 is **wrong**.  Example:

`https://server/cgi-bin/qgis_mapserv.fcgi?map=/mnt/projecto.qgs&service=WMS&version=1.3.0&REQUEST=GetPrint&FORMAT=pdf&SRS=EPSG:5015&TRANSPARENT=true&DPI=150&TEMPLATE=horizontal_A4&map0:LAYERS=tinras_sma&map0:extent=658738.6370041518,4086597.012992168,679692.0389517528,4100615.836676158&map1:LAYERS=caop2019_sma,caminhosflorestais_sma&map1:extent=662640.20483752,4088783.0770092523,668332.3820446859,4091691.262091459`

In this case map0 has only the raster layer, while map1 has the two vector layers, and this is the output:

![image](https://user-images.githubusercontent.com/1951107/142737608-a83a9536-2ab1-470a-bbbc-fe69b8b1f505.png)

where for map0 it shows the xyz layer, and the polygon vector one (and should show **only** the raster).

As soon as the raster is added to the LAYERS for map1, then the result for map0 is correct:

`https://server/cgi-bin/qgis_mapserv.fcgi?map=/mnt/projecto.qgs&service=WMS&version=1.3.0&REQUEST=GetPrint&FORMAT=pdf&SRS=EPSG:5015&TRANSPARENT=true&DPI=150&TEMPLATE=horizontal_A4&map0:LAYERS=tinras_sma&map0:extent=658738.6370041518,4086597.012992168,679692.0389517528,4100615.836676158&map1:LAYERS=tinras_sma,caop2019_sma,caminhosflorestais_sma&map1:extent=662640.20483752,4088783.0770092523,668332.3820446859,4091691.262091459`

![image](https://user-images.githubusercontent.com/1951107/142737687-6a414d08-b195-4b79-994d-ef2bb8cf87ed.png)

### Steps to reproduce the issue

See above.

### Versions

Used QGIS Desktop 3.16.13 and QGIS Server 3.16.13 and 3.22.0

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by elpaso** [comment]
@gioman can you check if this is still an issue? I have the feeling that I fixed if a few months back.
