### ISSUE TITLE
Style Manager Problems/Symbology 

### ISSUE THREAD

**Issue by earthvandy** [qgis/QGIS#46145]
### What is the bug or the crash?

Hi! 
I need to do the symbology of my project but the **style manager** doesn't display the items styles. I tried to import them but it’s like they are downloaded but I can’t see them nor use them.

### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/94769218/142745907-af2f7669-c377-4778-ac3c-61cc87fd598c.png)
![image](https://user-images.githubusercontent.com/94769218/142745923-6aaa20c4-aa42-4e42-bb44-acbe9e6c1a5c.png)
"It already exists"
![image](https://user-images.githubusercontent.com/94769218/142745943-8ea208b1-0fb0-4405-8e36-046477bd29e1.png)

### Versions

Versión de QGIS
3.16.11-Hannover
Revisión del código de QGIS
26cc1c76
Compilado contra Qt
5.15.2
Ejecutándose contra Qt
5.15.2
Compilado contra GDAL/OGR
3.3.1
Ejecutándose contra GDAL/OGR
3.3.1
Compilado contra GEOS
3.9.1-CAPI-1.14.2
Ejecutándose contra GEOS
3.9.1-CAPI-1.14.2
Compiled against SQLite
3.35.2
Running against SQLite
3.35.2
Versión del cliente PostgreSQL
13.0
Versión de SpatiaLite
5.0.1
Versión de QWT
6.1.3
Versión de QScintilla2
2.11.5
Compilado contra PROJ
8.1.1
Ejecutándose contra PROJ
Rel. 8.1.1, September 1st, 2021
Versión del SO
Windows 10 Version 2009
Active python plugins
MetaSearch; 
processing

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@earthvandy can you please try with a new QGIS profile?
