### ISSUE TITLE
"Add virtual layer" do not open the correct dialog

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#46157]
### What is the bug or the crash?

Instead it opens:

![image](https://user-images.githubusercontent.com/1951107/142856835-9f38b5b2-61f8-4fcf-8ad5-0c818ce0a912.png)

### Steps to reproduce the issue

See above.

### Versions

QGIS 3.22.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by roya0045** [comment]
Isn't this a duplicate ?

**Comment by gioman** [comment]
@roya0045 of what other ticket?

**Comment by roya0045** [comment]
#46116

**Comment by gioman** [comment]
@roya0045 no, is a different issue.

**Comment by jonnyforestGIS** [comment]
I can confirm this behavior:

![addvirtualLayer](https://user-images.githubusercontent.com/4480601/142945857-a4ccd6c7-0419-404a-85ba-cd814b334294.gif)

**Comment by nirvn** [comment]
On it.
