### ISSUE TITLE
notify signal from postgresql not working?

### ISSUE THREAD

**Issue by grassu** [qgis/QGIS#46159]
### What is the bug or the crash?

SELECT pg_notify('qgis', 'xyz');   
in Postgresql db is not refreshing the corresponding QGIS Layer. 

### Steps to reproduce the issue

- add postgis-Layer to qgis-project
- activate "refresh layer on notify" checkbox on layer
- add renderer on column xyz
- Executing UPDATE value ... in postgres for column xyz
- execute "SELECT pg_notify('qgis', '');"
--> unfortunately, nothing happens!
--> but after panning manually, the layer refreshes and is rendered according to the updated value

### Versions

QGIS 3.16.7
Postgresql 12.8

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@grassu this https://kartoza.com/en/blog/using-pgnotify-to-automatically-refresh-layers-in-qgis/ works for me on 3.22.1 and 3.16.14
