### ISSUE TITLE
referenced_columns parameter of Python expression function decorator is not properly documented

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#46161]
### What is the issue about the documentation?

https://docs.qgis.org/3.22/en/docs/user_manual/expressions/expression.html#function-editor mentions the optional keyword argument "referenced_columns" to the `@qgsfunction` decorator.

It says
> referenced_columns=[list]: An array of attribute names that are required to the function. Defaults to
> [QgsFeatureRequest.ALL_ATTRIBUTES].

The actual purpose of the parameter is unclear. Access to attributes that are not referenced in this list will actually work or not depending on the provider. The parameter can be used to **make sure** that access to certain attributes will always work (default value). 

-----

Some discussion around this in https://lists.osgeo.org/pipermail/qgis-developer/2021-November/064319.html

Please assign this to me, I will do these changes when I find the time.

**Comment by kannes** [comment]
Oops, this should also go to https://github.com/qgis/QGIS-Documentation/issues I presume!

**Comment by kannes** [comment]
Note to self, related https://github.com/qgis/QGIS/issues/46162

**Comment by m-kuhn** [comment]
> referenced_columns=[list]: An array of attribute names that are required for the function. This is used by the expression engine and providers to prepare the request and omit attributes that are not needed to improve performance.
Defaults to
[QgsFeatureRequest.ALL_ATTRIBUTES].

Something like that?

**Comment by kannes** [comment]
I will steal that with a little change
```
referenced_columns=[list]: An array of attribute names that are required by the function. This is used by the expression engine and providers to prepare the request and potentially omit attributes that are not needed to improve performance.
Defaults to [QgsFeatureRequest.ALL_ATTRIBUTES].
```
![image](https://user-images.githubusercontent.com/7661092/143297871-1ad8dd72-69cd-470a-9417-39b2793a5c28.png)

**Comment by m-kuhn** [comment]
Bring it on!

**Comment by kannes** [comment]
Will do, some day in December ;)

Just noticed that https://qgis.org/pyqgis/3.22/core/qgsfunction.html does not properly explain the parameter either and differs on what the default supposedly is.

**Comment by m-kuhn** [comment]
[Best to look it up in the code](https://github.com/qgis/QGIS/blob/master/python/core/additions/qgsfunction.py)

**Comment by kannes** [comment]
Fix via https://github.com/qgis/QGIS/pull/52841, thanks @YoannQDQ
