### ISSUE TITLE
Attribute-based rotation of symbols in DXF

### ISSUE THREAD

**Issue by FlorianTimm** [qgis/QGIS#46176]
### What is the bug or the crash?

When exporting layers with symbols with attribute-based rotation the rotation is interpreted counterclockwise instead of clockwise, like it is interpreted in QGIS itself. To get the correct rotation you have to use (360 - rotation) as value.

### Steps to reproduce the issue

1. Create point layer with rotation directions as attribute
2. Visualize them using attribute-based rotation
3. Export as DXF

### Versions

3.22.0

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

**Comment by gioman** [comment]
> Export as DXF

@FlorianTimm did you used the "export project to DXF" functionality or did you just "save as..." your vector?

**Comment by FlorianTimm** [comment]
I used "export project to DXF" with "symbol layer symbology"
