### ISSUE TITLE
Passwords cannot be saved into keychain on macOS

### ISSUE THREAD

**Issue by FelisPimeja** [qgis/QGIS#46175]
### What is the bug or the crash?

The issue is similar to https://github.com/qgis/QGIS/issues/40541
On MacOS 12.0.1 Monterey QGIS (3.22.0-Białowieża and 3.16.14-Hannover) can not use keychain to store passwords when connecting to Postgresql 14.

### Steps to reproduce the issue

In QGIS with new clean profile:
1. Create new connection to PostgreSQL 14 database
2. Enter user/password
3. Click "Convert to Configuration" Button -> No errors
4. Restart QGIS
5. Try to connect through newly created connection
6. "Enter CURRENT master authentication password" window pops up
7. Enter Master password
8. Get errors in console: 

```
CRITICAL    Authentication Manager : Retrieving password from your Keychain failed: The user name or passphrase you entered is not correct. (OSStatus -25293).
CRITICAL    Authentication Manager : Storing password in your Keychain failed: The user name or passphrase you entered is not correct. (OSStatus -25293).
WARNING    Authentication Manager : Master password could not be written to your Keychain
```
![image](https://user-images.githubusercontent.com/874261/142998247-01246880-812f-4704-a73c-0061b06ed9c8.png)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.0-Białowieża | QGIS code revision | d9022691f1
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | 12.3
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 12.0
  |   |   |  
Active Python plugins
QuickOSM | 1.16.0
osminfo | 0.7.0
quick_map_services | 0.19.11.1
BivariateRenderer | 0.3
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.5

</body></html>

PostgreSQL 10.13 (Ubuntu 10.13-1.pgdg18.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit

PostgreSQL 14.1 (Ubuntu 14.1-1.pgdg21.10+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.2.0-7ubuntu2) 11.2.0, 64-bit

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

I tried to fully reset QGIS Master password and turn off/on "Integrate master password within keychain" preferences option with no luck.

**Comment by gioman** [comment]
@FelisPimeja Just tested on QGIS 3.22 on macOS catalina + pgsql 14: works fine. My macmini can't update do Big Sur or Catalina, so I cannot say if this is confirmed on the latest iteration of Apple OS.

**Comment by marcbou** [comment]
issue persists on MacOS 12.2.1 with latest QGIS-Dev nightly build

**Comment by gioman** [comment]
> issue persists on MacOS 12.2.1 with latest QGIS-Dev nightly build, possiblity related to the fact that the app isn't correctly signed. seeing this message from securityd in the logs:

@marcbou just tested on 3.22 and Monterey (M1 mac mini): all works ok.

**Comment by bonyar** [comment]
<img width="595" alt="Screen Shot 2022-06-01 at 5 31 06 PM" src="https://user-images.githubusercontent.com/92639802/171523599-35a2040e-b250-4149-b788-6b1a52976338.png">
I don't know if it will help anyone but changing this setting in the keychain worked for me. I don't get the error when opening qgis.

**Comment by tholub** [comment]
> <img alt="Screen Shot 2022-06-01 at 5 31 06 PM" width="595" src="https://user-images.githubusercontent.com/92639802/171523599-35a2040e-b250-4149-b788-6b1a52976338.png">
> 
> I don't know if it will help anyone but changing this setting in the keychain worked for me. I don't get the error when opening qgis.

This also fixed it for me. Not exactly a QGIS issue but it would be nice to get a more helpful error message and a pointer to Keychain Access.

**Comment by JackCA** [comment]
I'm seeing this on 3.28.0-Firenze -- above fixes work but don't seem safest

**Comment by Dargy13** [comment]
> <img alt="Screen Shot 2022-06-01 at 5 31 06 PM" width="595" src="https://user-images.githubusercontent.com/92639802/171523599-35a2040e-b250-4149-b788-6b1a52976338.png">
> 
> I don't know if it will help anyone but changing this setting in the keychain worked for me. I don't get the error when opening qgis.

Thank you very much !!! you saved my (pro)Life 🤗 It works perfectly now 🙏

**Comment by Dargy13** [comment]
> <img alt="Screen Shot 2022-06-01 at 5 31 06 PM" width="595" src="https://user-images.githubusercontent.com/92639802/171523599-35a2040e-b250-4149-b788-6b1a52976338.png">
> 
> I don't know if it will help anyone but changing this setting in the keychain worked for me. I don't get the error when opening qgis.

Thank you very much 🙏 it works perfectly now 🤗

**Comment by ptycharly** [comment]
Thank you for this option but in my case the issue is persistant. I work on Qgis 3.34.0 under mac os Ventura 13.5.1.

**Comment by seancarmody** [comment]
> > <img alt="Screen Shot 2022-06-01 at 5 31 06 PM" width="595" src="https://user-images.githubusercontent.com/92639802/171523599-35a2040e-b250-4149-b788-6b1a52976338.png">
> > I don't know if it will help anyone but changing this setting in the keychain worked for me. I don't get the error when opening qgis.
> 
> Thank you very much 🙏 it works perfectly now 🤗

This worked for me, but the first time I tried I had QGIS open and initially I thought it hadn't worked but I discovered that the Keychain Access setting had reverted but when I closed QGIS and reset it, the change persisted and my problem has been solved. Thanks!

**Comment by jeabraham** [comment]
Still a bug, but the workaround still works.  Perhaps the workaround could be documented in the error message?

**Comment by stibinator** [comment]
Bug still bugging, workaround working for me, this seems like a bit of a security fail..?

**Comment by jeabraham** [comment]
Actually I had to change the keychain entry to allow ALL APPS to access the item, and I had to do it while QGIS was closed.
