### ISSUE TITLE
DB Manager in QGIS 3.22 not able to open psql table without geometry

### ISSUE THREAD

**Issue by jhpoosthoek** [qgis/QGIS#46186]
### What is the bug or the crash?

In the QGIS 3.22 Standalone for Windows version the DB Manager cannot add PostGIS geometry less tables anymore to the Canvas. In QGIS 3.20 this works.

An Python Error window opens with the error: 'PGTable' object has no attribute 'geometryType'

### Steps to reproduce the issue

Go to DB Manager
Double click on the PostGIS provider.
Open a PostGIS server (which must have been added in QGIS)
Browse to a table without a geometry
Right click on the table and select Add to Canvas
This causes an error and opens the Python Error window.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.0-Białowieża | QGIS code revision | d9022691f1
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
Compiled against GDAL/OGR | 3.3.2 | Running against GDAL/OGR | 3.3.3
PROJ version | 8.1.1
EPSG Registry database version | v10.038 (2021-10-21)
GEOS version | 3.10.0-CAPI-1.16.0
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
attributeBasedClustering | 2.2
b4udignl2 | 2.2.0
BGTImport | 3.16
buienradar_plugin | 1.3
cartogram3 | 3.0.4
CityJSON-loader | 0.7.2
covid19_tracker | 0.2
disconnected-islands | 2.0.2
eu_mapper | 0.1
firstaid | 2.1.5
FS3 | 1.0.1
gdrive_provider | 1.0.1
GeodynGem | 3.0
geopunt4Qgis | 2.2.6
GroupStats | 2.2.5
ImportPhotos | 3.0.3
IPyConsole | version 2.0
LAStools | 1.4
maplibrary | 1.1
mmqgis | 2021.9.10
nominatim_locator_filter | 0.2.4
OnlineRoutingMapper | 0.9
openlayers_plugin | 2.0.0
partial_histogram | 1.2
pdokbaggeocoder | 0.6.6
pdokservicesplugin | 3.7.2
pdok_locatieserver_locator_filter | 0.2.1
pluginbuilder3 | 3.2.1
plugin_reloader | 0.9.1
pointsamplingtool | 0.5.3
processing_r | 3.1.0
profiletool | 4.2.1
qgis-maptiler-plugin | 2.0.0
Qgis2threejs | 2.6
qgis2web | 3.16.0
qgiscloud | 3.3.12
qgis_resource_sharing | 0.16.0
QNEAT3 | 1.0.4
QNeighborhood | 0.1.1
qtiles3 | 1.6.0
QuickPrint | 3.6.1
QuickWKT | 3.1
RuimtelijkePlannen | 3.5.0
SpreadsheetLayers | 2.0.1
test_module_name | 0.1
vector_tiles_reader | 3.2.2
db_manager | 0.1.20
MetaSearch | 0.3.5
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
Update to 3.22.1 - this is fixed
