### ISSUE TITLE
Issue warning when Saving/Overwriting imported Mesh

### ISSUE THREAD

**Issue by sharon92** [qgis/QGIS#46188]
### What is the bug or the crash?

When a 2dm Mesh file is imported and saved, the file loses its Model Parameters.
The output 2dm file only consists of the mesh data.

Here a warning is necessary that should warn the user that the Model Parameters are going to be deleted and overwritten. And an option to backup the original file should be provided.

### Steps to reproduce the issue

1. Import 2dm File
2. Edit Mesh
3. Save Mesh

### Versions

QGIS version
3.22.0-Białowieża
QGIS code revision
d9022691f1
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.2
PROJ version
8.1.1
EPSG Registry database version
v10.028 (2021-07-07)
GEOS version
3.10.0-CAPI-1.16.0
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2004

Active Python plugins
pluginbuilder3
3.2.1
qgis2web
3.16.0
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
You do not have this popup when you edit your file ?
![image](https://user-images.githubusercontent.com/39594821/143233073-e9cc028d-146e-490d-915b-7fc275d340b4.png)

try upgrade to 3.22.1 also

**Comment by sharon92** [comment]
@nicogodet where can I install 3.22.1 from?

**Comment by gioman** [comment]
> @nicogodet where can I install 3.22.1 from?

@sharon92 https://qgis.org/downloads/QGIS-OSGeo4W-3.22.1-1.msi

**Comment by vcloarec** [comment]
@sharon92 , you should have this message with 3.22.0.

**Comment by sharon92** [comment]
@vcloarec you are right, this message pops up when I import the file. Saving the changes don't pop another warning, which is okay I think.

**Comment by nicogodet** [comment]
Correct behavior should be:

- Import : no warning
- Press edit button : warning
- Press save button : no warning as you have already been warned

Is this what you have ?

**Comment by sharon92** [comment]
@nicogodet yes this is the current behaviour. I edited the mesh and after a while I forgot about the fact that I deleted the model datasets and saved it. So I need to remember this for the next time.
