### ISSUE TITLE
Using "pan map" tool after measure tool add a new (wrong) measure point

### ISSUE THREAD

**Issue by arno974** [qgis/QGIS#46204]
### What is the bug or the crash?

When using the measuring tool, it is sometimes necessary to move and therefore to use the moving tool. After moving and reactivating the measurement tool, a measurement point corresponding to the click of the move button is added to the measure line and then produce a false measure result.

https://user-images.githubusercontent.com/425243/143387635-8be65152-1e75-4b5e-816a-34c4531d6a61.mp4

### Steps to reproduce the issue

1- Start a measure
2- Activate the move button and go somewhere else
3- Activate again the measure tool and finish your measure
4- Look at the corresponding measure line. A point corresponding to the click on the move button is added to the measure line.

### Versions

3.16.11

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
@arno974 have you tried use the spacebar (keeping it pressed) to move/pan the map without needing to select the move/pan tool?

**Comment by arno974** [comment]
Hi @gioman,

I didn't know this shortcut thanks ! Indeed using the spacebar no additional point is added. While your solution works, it does not resolve the problem. Tell me if I'm wrong, but activating a button (move, zoom) should not add an "artificial" point to the measure line. Forgot to mention that this happens with all buttons (move, zoom). 
For people with a laptop and no mouse, this can be annoying as they rely on the use of these buttons.
