### ISSUE TITLE
Crash when open a project saved with older version

### ISSUE THREAD

**Issue by Mario211125** [qgis/QGIS#46207]
### What is the bug or the crash?

Crash ID: d1f7afe8399d52daab504182ca4d3f9b8b3ed3c1

Stack Trace

QTextCodec::toUnicode :
providerMetadataFactory :
providerMetadataFactory :
providerMetadataFactory :
QgsVectorLayer::setDataProvider :
QgsVectorLayer::readXml :
QgsMapLayer::readLayerXml :
QgsProject::addLayer :
QgsProject::_getMapLayers :
QgsProject::readProjectFile :
QgsProject::unzip :
QgsProject::read :
QgisApp::addProject :
QgisApp::openProject :
QgsTemporalControllerDockWidget::temporalController :
QObject::qt_static_metacall :
QAbstractItemView::activated :
QAbstractItemView::mouseDoubleClickEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.22.1-Bia?owie?a
QGIS code revision: 663dcf8fb9
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.0
Running against GDAL: 3.4.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

### Steps to reproduce the issue

Just open a project

### Versions

since 3.22.0, also 3.22.1

works well with all versions up to 3.20.3

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
@Mario211125 same as https://github.com/qgis/QGIS/issues/46152 ?

**Comment by Gustry** [comment]
Same crash ID as #46152 and #46219

**Comment by Mario211125** [comment]
First: sorry about my poor english!
only crash when opening the complete project.
If I open the files seperatly in 3.22.1 no problem.
When QGis is opening the project and reading the layers/data it crashes for example at the layer xyz5 but reading the layer xyz1 to xyz4. You will see the loading bar stopping at layer xyz5 and then crash.
The layer xyz5 is a csv-file. After deleting xyz5 in QGis 3.20.1 an reopening in 3.22.1 new crash at layer for ex. xyz7.
Layer xyz7 is a shape-file and can be opend solo in 3.22.1
If I have time this weekend I will play around.
I can not attach the files, sorry because of secuity reasons.

**Comment by gioman** [comment]
> The layer xyz5 is a csv-file.

@Mario211125 see https://github.com/qgis/QGIS/issues/46219
