### ISSUE TITLE
During vertex indexing QGIS crashes when using tool that utilizes indexed vertices

### ISSUE THREAD

**Issue by andywicht** [qgis/QGIS#46218]
### What is the bug or the crash?

During vertex indexing QGIS crashes when using tool that utilizes indexed vertices such as Vertex Tool or Move Feature especially on larger layers (reproducible on e.g. US blockgroups, part of this zip file: https://www2.census.gov/geo/tiger/TGRGDB21/tlgdb_2021_a_us_substategeo.gdb.zip -> convert e.g. to gpkg)

This is especially dangerous when editing in a remote PostGIS DB, because indexing might take longer and hence increases the timeframe when the crash can be triggered.

If you select the tool and wait until the indexing is finished, everything works as expected.

### Steps to reproduce the issue

Do this using a fresh profile without 3rd party plugins:

1. load above mentioned large file
2. start editing
3. zoom to random feature in the middle of the layer
4. enable snapping
5. select "Move Feature" or "Vertex Tool"
6. QGIS will start indexing (blue bar at the bottom pops up)
7. While the blue progress bar is visible start moving features around
8. QGIS will crash (crash report below)

### Versions

Crash ID: 528c18d84814c91aad5d1de97df6e9ba0ccadaf2

Stack Trace

QgsGeometry::closestVertex :
QgsPointLocator::verticesInRect :
SpatialIndex::TPRTree::Data::Data :
SpatialIndex::TPRTree::Data::Data :
QgsPointLocator::nearestVertex :
QgsSnappingUtils::~QgsSnappingUtils :
QgsSnappingUtils::snapToMap :
QgsMapMouseEvent::snapPoint :
QgsMapToolAdvancedDigitizing::canvasMoveEvent :
QgsMapCanvas::mouseMoveEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.16.11-Hannover
QGIS code revision: 26cc1c76
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.1
Running against GDAL: 3.3.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

### Supported QGIS version

- [x] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

### Additional context

Let me know if I can provide any more specific context. I tried to be as detailed as possible above.

Cheers

**Comment by gioman** [comment]
> * select "Move Feature" or "Vertex Tool"
> 
> * QGIS will start indexing (blue bar at the bottom pops up)
> 
> * While the blue progress bar is visible start moving features around
> 
> * QGIS will crash (crash report below)

@andywicht I tried this workflow using the "block_group" layer, as it is the largest in the geodatabase you linked, and cannot replicate. The indexing operation started and finished in a matter of a couple of seconds (on a 10 years old laptop with a pedestrian SSD) leaving basically no time to do any operation while it was running. QGIS 3.16.14 on Windows 10.

**Comment by andywicht** [comment]
@gioman 
here a screencast of the behavior, maybe that makes my description more clear:
![qgis_crash](https://user-images.githubusercontent.com/21099522/143617963-51c104c6-b053-482a-9c40-2f4f95d6beb7.gif)

This is on a not even 3 year old Dell i7-8665U 16GB RAM with SSD laptop.
QGIS crashes the moment you see the popup in the lower right corner that it finished indexing.

I observe this instability for quite some versions now and could never pinpoint it. I always thought it was an issue with the Vertex Tool but it seems to be a robustness issue of the indexing (layman's speak of course... I am not a software developer)

**Comment by gioman** [comment]
@andywicht for some reason today I can replicate.

**Comment by gioman** [comment]
It is something that was introduced in 3.12 as it works well up to 3.10.

**Comment by andreasneumann** [comment]
@andywicht  Is it specific to this particular geometry, or does it happen with other data sets as well?

**Comment by andywicht** [comment]
@andreasneumann I randomly zoomed somewhere. That happens with any geometry.

@gioman glad you could replicate the behaviour. I was starting to fear that it was something even more obscure and specific to my machine.

**Comment by gioman** [comment]
> That happens with any geometry.

@andywicht but also with other layers?

**Comment by andywicht** [comment]
@gioman yes. I think as soon as the layer is sufficiently large and the indexing takes some time, this occurs. This block group layer was just the first large open data layer that came to my mind.

**Comment by andywicht** [comment]
@gioman can I provide you with any more info?

**Comment by gioman** [comment]
I don't, sometimes is just difficult to keep track of everything.
