### ISSUE TITLE
QGIS crash afther reload project

### ISSUE THREAD

**Issue by NvBgm** [qgis/QGIS#46210]
### What is the bug or the crash?

QGIS crash

### Steps to reproduce the issue

Reload a project

### Versions

QGIS-versie
3.22.1-Białowieża
QGIS code revisie
663dcf8fb9
Qt versie
5.15.2
Python versie
3.9.5
GDAL/OGR versie
3.4.0
PROJ versie
8.2.0
EPSG-register databaseversie
v10.038 (2021-10-21)
GEOS versie
3.10.0-CAPI-1.16.0
SQLite versie
3.35.2
PDAL versie
2.3.0
PostgreSQL client versie
13.0
SpatiaLite versie
5.0.1
QWT versie
6.1.3
QScintilla2 versie
2.11.5
OS versie
Windows 10 Version 2009

Actieve Python plug-ins
bfvw_tools
1.3
changeDataSource
3.1
ClipMultipleLayers
3.2.0
export_to_sql_server
0.4
lizmap
3.6.3
pdokservicesplugin
3.7.2
pluginbuilder3
3.2.1
plugin_reloader
0.8.2
qconsolidate3
0.2.0
qgis-maptiler-plugin
2.0.0
qgis-plugin-findreplace-main
1
qgis2web
3.16.0
qtiles
1.7.0
quick_map_services
0.19.26
SelectWithin
0.4
db_manager
0.1.20
processing
2.12.99

### Supported QGIS version

- [x] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@NvBgm same as https://github.com/qgis/QGIS/issues/46207 ?

**Comment by NvBgm** [comment]
@Gioman  No this is not only with older version projects but also with projects just made in last version

**Comment by elpaso** [comment]
@NvBgm we need a way to reproduce the issue (and/or a stack trace). 

Can you attach a small project with data that shows the issue?

**Comment by elpaso** [comment]
@NvBgm ... and of course try first with a new profile as mentioned in the issue template.

**Comment by NvBgm** [comment]
@Elpaso  I think my problem is solved.
I have made a new profile and i don't get any crashes nou
I hoop it wil stay that way..
Thanks all.
