### ISSUE TITLE
QGIS crashed opening projects with csv files and "System" encoding

### ISSUE THREAD

**Issue by Mariones42** [qgis/QGIS#46219]
## User Feedback

Hello,

I found the following problem: I have a fairly complex project that involves various sources of information (gpkg, shp, csv). When I try to open it, QGIS gives an error and closes.

I debugged the project by opening it by segments until I found where the error was and apparently it is associated with the encoding of the csv files: in my project the files have “System” encoding, but when I looked for it in QGIS I can't find it.

To check this I manually modified the encoding in the qgs file and was able to open it correctly.

In summary, since there is no "System" encoding, QGIS gives an error when opening the project as it tries to open the csv with that encoding and cannot.

Thank you

## Report Details

**Crash ID**: [d1f7afe8399d52daab504182ca4d3f9b8b3ed3c1](https://github.com/qgis/QGIS/search?q=d1f7afe8399d52daab504182ca4d3f9b8b3ed3c1&type=Issues)

**Stack Trace**
<pre>
QTextCodec::toUnicode :
providerMetadataFactory :
providerMetadataFactory :
providerMetadataFactory :
QgsVectorLayer::setDataProvider :
QgsVectorLayer::readXml :
QgsMapLayer::readLayerXml :
QgsProject::addLayer :
QgsProject::_getMapLayers :
QgsProject::readProjectFile :
QgsProject::unzip :
QgsProject::read :
QgisApp::addProject :
QgisApp::openProject :
QgsTemporalControllerDockWidget::temporalController :
QObject::qt_static_metacall :
QAbstractItemView::activated :
QAbstractItemView::mouseDoubleClickEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.22.1-Bia?owie?a
QGIS code revision: 663dcf8fb9
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.0
Running against GDAL: 3.4.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Steps to reproduce the issue

Only I open the project and in some point QGIS crashes. 
As I mentioned in the bug/crash report I think that is related with the lack of "System" encoding option

### Versions

3.22.0 and 3.22.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

I can open the project in QGIS 3.16.14 without problems.

**Comment by gioman** [comment]
@Mariones42 can you please share/attach a minimal project with the CSV file that is causing the crash? thanks.

**Comment by Mariones42** [comment]
Hi,
Please find below a zip file with the example.
[QGIS_debugging.zip](https://github.com/qgis/QGIS/files/7604978/QGIS_debugging.zip)

**Comment by Gustry** [comment]
Same crash ID as #46207 and #46152

**Comment by gioman** [comment]
> Same crash ID as #46207 and #46152

@Gustry  correct, but this seems to be the incriminating report. I confirm the crash, but as a fact if the QGS file is manually edited and for the CSV the encoding is changed from System to UTF-8 (note that my system is in English, so for me System should mean UTF-8) then the crash is gone.

**Comment by gioman** [comment]
And also confirmed no crash on 3.16.14.
