### ISSUE TITLE
Use of the character '%' in Expression

### ISSUE THREAD

**Issue by Ducarouge** [qgis/QGIS#46213]
### What is the bug or the crash?

If i follow the doc of the LIKE operator : 
'1%' LIKE '1\\%' → 1

But when i execute it return 0

### Steps to reproduce the issue

go to 'Select features using an expression' and run the code :  '1%' LIKE '1\\%'

### Versions

test in 3.16 and 3.22

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
@Ducarouge returns 1 here.

**Comment by troopa81** [comment]
it returns 0 in master

the thing is when you write your ticket @Ducarouge the backslashs have been removed, you have to had another one
So '1%' LIKE '1\\%' → 1 do return 0 instead of 1
