### ISSUE TITLE
PCRaster plugin leads to crash of QGIS

### ISSUE THREAD

**Issue by ebrudler** [qgis/QGIS#46227]
### What is the bug or the crash?

applying teool create ldd leads to crash
a573919ad860cbb9df0bd4bce11551b46e72585b

### Steps to reproduce the issue

   aerhth

### Versions

3.16.14

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by Gustry** [comment]
You must open the issue on the plugin repository.
The QGIS project can't do anything about it.

And you must describe the issue, how to replicate etc.

**Comment by gioman** [comment]
@ebrudler you must report this to the plugins author/s, not here.
