### ISSUE TITLE
PCRaster Plugin leads to crash

### ISSUE THREAD

**Issue by ebrudler** [qgis/QGIS#46228]
### What is the bug or the crash?

applying the PCRaster "create LDD"

### Steps to reproduce the issue

a573919ad860cbb9df0bd4bce11551b46e72585b

### Versions

3.16.14

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
Please report this issue in the plugin bugtracker.
