### ISSUE TITLE
crash when using expression

### ISSUE THREAD

**Issue by jevick** [qgis/QGIS#46223]
### What is the bug or the crash?

Clicking on Expression builder for custom labelling causes crash

### Steps to reproduce the issue

NA

### Versions

3.10

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

It was working well before, this suddenly happened. Restarting the machine does not help.

**Comment by nyalldawson** [comment]
3.10 is very old, and no longer supported. Please try in 3.22 or 3.16.
