### ISSUE TITLE
Forms break when upgrading from 3.16 to 3.22/Master for Virtual fields

### ISSUE THREAD

**Issue by tudorbarascu** [qgis/QGIS#46231]
### What is the bug or the crash?

![problem](https://user-images.githubusercontent.com/3179646/143569034-7bb95e8f-a8ec-4439-abad-f673af719784.gif)

I upgraded a project that I use and the form doesn't behave well (e.g. The id doesn't get the default value - 9999) but gets the value of a virtual field?

I attached a project to reproduce as in the above screenie.

[data.zip](https://github.com/qgis/QGIS/files/7608201/data.zip)

### Steps to reproduce the issue

Open the project in 3.16 the form is good.

1. Open the project in 3.22 or Master.
2. Add a new feature for the regulamente layer
3. The id field should have gotten the default value (9999) but instead it gets the data that should have been outputted in the virtual "regulament" field.

If I delete the custom expressions, everything works alright.

Adding again another expression e.g. concat that **references a field** breaks the form again.

I've bisected the bad commit to d2a5a9d53afd986c34b7ed5f04f6bd10741ff4ff

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.1-Białowieża | QGIS code revision | 5db90ccd71
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.2
GDAL/OGR version | 3.4.0
PROJ version | 7.2.1
EPSG Registry database version | v10.008 (2020-12-16)
GEOS version | 3.10.0-CAPI-1.16.0
SQLite version | 3.34.1
PostgreSQL client version | 14.1 (Debian 14.1-1.pgdg110+1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Debian GNU/Linux 11 (bullseye)
  |   |   |  
Active Python plugins
pluginbuilder3 | 3.2.1
QuickWKT | 3.1
searchlayers | 3.0.5
db_manager | 0.1.20
sagaprovider | 2.12.99
processing | 2.12.99
grassprovider | 2.12.99

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
> I've bisected the bad commit to [d2a5a9d](https://github.com/qgis/QGIS/commit/d2a5a9d53afd986c34b7ed5f04f6bd10741ff4ff)

@domi4484 ping
