### ISSUE TITLE
Extra bytes attributes get loaded but QGIS parses values as zeros

### ISSUE THREAD

**Issue by wonder-sk** [qgis/QGIS#46234]
### What is the bug or the crash?

The following file contains a couple of "extra bytes" attributes - Amplitude, Reflectance, Deviance. The file gets correctly indexed by untwine and the extra attributes can be selected for rendering, but all values from those attributes are read as zero (I have verified in CloudCompare they are not zeros):
https://filkassen.statens-it.dk/u/zUxXZINMV3_fTFdm/1km_6210_527.laz?l

This happens for both identify tool and rendering - looks like we are not parsing the values correctly.

### Steps to reproduce the issue

1. load the test file in QGIS
2. set attribute by ramp rendering e.g. to Reflectance
3. all points get the same color (as if the all values were zero)

### Versions

3.22

**Comment by djes** [comment]
I think there's the problem with NIR (infrared) too in v1.4 las/laz files.
