### ISSUE TITLE
Crash setting elevation layer in 3d view

### ISSUE THREAD

**Issue by janhec** [qgis/QGIS#46232]
## User Feedback

View -> 3d view setting the elevation layer to AHN2_5.
Layers: AHN2_5 (WCS, PDOK)
Opentopo (PDOK)
(that's all).

## Report Details

**Crash ID**: [3f900df900945e8a2e21945f317ab5b65e551a87](https://github.com/qgis/QGIS/search?q=3f900df900945e8a2e21945f317ab5b65e551a87&type=Issues)

**Stack Trace**
<pre>
OGRSpatialReference::GetWGS84SRS :
OGRSpatialReference::operator= :
GDALRegister_GTiff :
GDALRegister_GTiff :
GDALGetProjectionRef :
QgsRasterDataProvider::block :
QgsDemTerrainGenerator::writeXml :
QgsTerrainDownloader::dataSource :
QgsTerrainDownloader::dataSource :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.22.1-Bia?owie?a
QGIS code revision: 663dcf8fb9
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.0
Running against GDAL: 3.4.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Steps to reproduce the issue

Install PDOK plugin
Start a project with EPSG:28992
Load AHN2_5m through the PDOK plugin;
Load opentopo as maplayer (connect with pdok, scroll down to find opentopo (png));
Zoom to an area in NL, Schiphol, Kaagbaan;
optionally: props of ANH2_5m, transparency, add add. nodata value -3.4028234663852886e+38
min max of AHN2_5 should be -6.3453 311.462 (or very nearly so, no extreme values)
deselect (view of) layer AHN2_5m
Select View-> new 3d map view
enlarge the window to a useful size (nothing extreme here)
select options (wrench), configure
check Terrain and set Type to DEM
choose AHN2_5m as elevation layer
wait for crash or hopefully, a view that can be handled.

### Versions

QGIS version
3.22.1-Białowieża
QGIS code revision
663dcf8fb9
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.0
PROJ version
8.2.0
EPSG Registry database version
v10.038 (2021-10-21)
GEOS version
3.10.0-CAPI-1.16.0
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
inspireNL
2.6
pdokservicesplugin
3.7.2
Qgis2threejs
2.6
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@janhec 

1) try with a new QGIS profile, no 3rd party plugins installed

2) if the problem persist attach/link a project (with data)

**Comment by roya0045** [comment]
This seems to be an online dataset, I'm not sure if qgis is made to handle big online datasets in the 3d viewer as opposed to a file source.

**Comment by gioman** [comment]
> I'm not sure if qgis is made to handle big online datasets in the 3d viewer as opposed to a file source.

yeah, but also should not crash :)
