### ISSUE TITLE
The icon cursor freezes if both the spacebar and the mouse wheel are pressed while panning

### ISSUE THREAD

**Issue by ValPinnaSardinia** [qgis/QGIS#46233]
### What is the bug or the crash?

I have realised that if, while you are using the space bar for pan in the map canvas,  you press the mouse wheel, the mouse cursor icon freezes to the "closed hand" and also if a new tool is selected, the icon keeps this aspect. 

The only way to resolve the issue is to restart the software.

The issue was confirmed in several PCs and in different QGIS versions.

### Steps to reproduce the issue

1. Create a new map. 
2. Press the space bar to pan in the canvas.
3. While keeping pressing the space bar, press the mouse wheel. 
4. Now the cursor icon should be frozen to the 'closed hand' icon. Try selecting a different tool and the icon will not change.

### Versions

Issue recorded on 3.16.14 and 3.22.1

Windows 10
 

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by skampus** [comment]
hi, I confirm this issue on Windows 10:
- QGIS 3.22.1-Białowieża - Revisione codice QGIS 663dcf8fb9
-  QGIS 3.16.14-Hannover - Revisione codice QGIS 42791986

**Comment by pigreco** [comment]
I also confirm on OSGeo4W v2
