### ISSUE TITLE
Make minimum and maximum available in aggregate

### ISSUE THREAD

**Issue by m-kuhn** [qgis/QGIS#46230]
The other issue I see your PR raise is why the aggregate function doesn't have minimum and maximum as aggregate parameter (all the other parameters name matches an existing aggregate function) instead of min and max.

_Originally posted by @DelazJ in https://github.com/qgis/QGIS/issues/46211#issuecomment-979800050_

**Comment by m-kuhn** [comment]
Should be added as aliases for consistency.

**Comment by gioman** [comment]
@m-kuhn is this a bug report?

**Comment by m-kuhn** [comment]
A nice to have with low effort. On the edge :-)
