### ISSUE TITLE
Crash when loading or saving project with MySQL layer with empty geometries

### ISSUE THREAD

**Issue by nsauzay** [qgis/QGIS#46246]
### What is the bug or the crash?

The project loads fine on 3.10.14, and save works also
The project can be loaded on 3.16.14 but any attempt to save it leads to a crash (even without any change)
The project can not be loaded on 3.22.1, it leads to the crash also
I manage to change layer encoding to remove th 'system's one but the behaviour is the same.

### Steps to reproduce the issue

0e460833cdb296e8095f31e576927bf58e62eb49

### Versions

3.16.14
3.22.1
loads and save fine on 3.10.14

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Crash ID: 0e460833cdb296e8095f31e576927bf58e62eb49

Stack Trace

OGRGeometryFactory::createFromWkb :
OGRGeometryFactory::createFromWkb :
S57GenerateDSIDFeatureDefn :
QgsOgrProviderUtils::expandAuthConfig :
QgsVectorLayer::extent :
QgsMapLayer::writeLayerXml :
QgsProject::writeProjectFile :
QgsProject::zip :
QgsProject::write :
QgisApp::fileSave :
QObject::qt_static_metacall :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.16.14-Hannover
QGIS code revision: 42791986
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.0
Running against GDAL: 3.4.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

**Comment by gioman** [comment]
@nsauzay can you share the project (with the data)? or maybe create a minimal shareable version that shows the same behavior?

**Comment by nsauzay** [comment]
I manage to isolate the layer that leads to the crash. The definition file is attached.
It's a layer based on a mysql database on a server with geographical information.
when I start with a new project and I import the layer from the joined definition file the behaviour is reproduced :
    on 3.16 crashes  on saving the project after import
        3.22 crashes on importing the layer.
[couche crash.zip](https://github.com/qgis/QGIS/files/7611957/couche.crash.zip)

**Comment by gioman** [comment]
> on 3.16 crashes on saving the project after import
> 3.22 crashes on importing the layer.
> [couche crash.zip](https://github.com/qgis/QGIS/files/7611957/couche.crash.zip)

@nsauzay I cannot replicate. Using 3.16.14 and 3.22.1 on Win 10, after having added your layer definition file.

**Comment by nsauzay** [comment]
I basically mentionned the layer point to a mysql database, when the link is cut to the database server, the application does not crash. How can I provide you more infos ?

**Comment by gioman** [comment]
> I basically mentionned the layer point to a mysql database, when the link is cut to the database server, the application does not crash. How can I provide you more infos ?

@nsauzay your description is unclear: do you get the crashes when the connection to this mysql layer is working, or when is not working?

**Comment by nsauzay** [comment]
when the connection is working i get the crashes. 
When the connection is not working I'm able to load and save the projects.

**Comment by nsauzay** [comment]
When I try to add this single layer directly in a new project in QGis 3.22 from mysql, i get the application to crash ...

**Comment by nsauzay** [comment]
by the way mysql server is on ubuntu server  and has version 5.6.44

**Comment by nsauzay** [comment]
Looking forward, I notice I had in the fetched mysql table one line with a null geometry. This seems to lead to a crash of QGis. Removing the null geometry lines in the database solved the trouble

**Comment by nsauzay** [comment]
The problem occurs when the mysql datatable contains a line with null geometry. When the line is filtered or removed from the table, the application does not crash anymore

**Comment by nyalldawson** [comment]
Can you share a sql dump of a mysql database which can be used to reproduce this issue?

**Comment by nyalldawson** [comment]
(This is an upstream (GDAL) bug by the way, but I'm happy to look into it if you can provide a reproducible data set)

**Comment by nsauzay** [comment]
Hello please find a database dump in order to reproduce the crash.
As mentionned, the mysql server is on ubuntu and has version 5.6.44
Regards
[basecrash.sql.zip](https://github.com/qgis/QGIS/files/7617182/basecrash.sql.zip)

**Comment by paulwittle** [comment]
I think I'm getting similar issues to this but only when I switch project. So I load the project and it is fine but if I load another project first then load the same project I loaded a minute ago the QGIS system just disappears completely. I'm experiencing this when using Windows and project files that reference both MSSQL and Oracle layers.

**Comment by nsauzay** [comment]
just a precision, on my side, on 3.16, the crash occurs when quitting the project while on 3.22 it is on loading the trouble

**Comment by nsauzay** [comment]
... the project, sorry

**Comment by paulwittle** [comment]
I've just done a quick test and it is MSSQL for me as well. I created a blank project with OSM basemap and a GeoPackage layer. I then created a copy of that project and added an Oracle layer. Then I created a copy of the second project and added a single MSSQL layer. I can load the and switch between the first two but the third one causes a crash.

**Comment by nsauzay** [comment]
Just a remark, on my side, it's mysql and not mssql,

**Comment by paulwittle** [comment]
Ah sorry, my bad the acronyms are so similar I missed we were talking about different applications. They may well be separate issues then. I can raise my one separately if that is useful.

**Comment by nsauzay** [comment]
I'm not sure, it depends where the bug is located. It seems in any case that the behaviour is the same.
