### ISSUE TITLE
Ongoing issues with vertex tool

### ISSUE THREAD

**Issue by kairom13** [qgis/QGIS#46244]
### What is the bug or the crash?

I have experienced a variety of issues while using the vertex tool. I haven't found a specific way to reproduce the issues and crashes I have experienced, but they're always while I'm using the tool. Some examples of issues I've had:

- disappearing vertices (in the image the line segment is highlighted but the vertices are not)
![image](https://user-images.githubusercontent.com/35545260/143669458-fc8fc924-7222-4d5f-bab9-f70828024ee6.png)
- random crashes while using the tool
- weird glitches where a ghost version of a previous polygon remains (the image shows the vertex tool showing a polygon boundary that isn't actually there) 
![image](https://user-images.githubusercontent.com/35545260/143669742-c35c34c1-2f50-4141-922f-b3552d3db525.png)
- the tool shows the boundaries of a different polygon than the one it's closest to.
![image](https://user-images.githubusercontent.com/35545260/143669775-f8961b2b-1aab-4ec6-8a70-8c37ea8f7584.png)

My request is for a more in-depth analysis and review of the code that governs the vertex tool to ensure that it is working as intended.

### Steps to reproduce the issue

The issue always arises after continued use of the vertex tool along with other digitizing features (like splitting and merging features, etc). My guess is that there is an update/communication issue where the geometry data that's changed by splitting/merging/etc is not properly sent/received by the vertex issue, thus leading to disconnects, glitches, and crashes

### Versions

3.22.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
@kairom13 the question is the same as in https://github.com/qgis/QGIS/issues/46203#issuecomment-978867209

Have you really tried with a new QGIS profile and no 3rd party plugins?



> My request is for a more in-depth analysis and review of the code that governs the vertex tool to ensure that it is working as intended.

It does not work like that, especially if there is no clear way to replicate it it is unlikely that any dev will have a look at this. If we find a clear path to replicate (on profile that has no 3rd party plugins, thus excluding a problem caused by bad code QGIS isn't responsible for) then it is another story.

**Comment by kairom13** [comment]
@gioman Yes. I'm using a new profile with no 3rd party plugins (which I don't use anyways). I've update the reproducibility to reflect that I always have this issue after a while of editing geometries, even if there's not an exact method for reproducing the specific issues I have experienced.

I do wonder how much of the issue has to do with the size of the layer I'm editing? I have nearly 600 features with an average of like 500 vertices per feature, a few of which are likely invalid (due to other errors that are introduced by issues with QGIS's functions for editing geometries).
