### ISSUE TITLE
Reprojecting -180 to 180 dg raster to polar projection bilinear/cubic blurry

### ISSUE THREAD

**Issue by andskog** [qgis/QGIS#46254]
### What is the bug or the crash?

Reprojecting a raster with a -180 to 180 degrees longitudal extent, to a polar projection, using the Warp tool, and with e.g. bilinear or cubic rather than nearest neighbour resampling method, creates blurry/stretched segments around the 180dg meridian. In the attached screenshots, the upper result is 3995 nearest neighbour, which is all good, followed by buggy 3995 bilinear, both viewed in a 3995 project CRS. The third result is 3413 bilinear viewed in a 3413 project CRS. The bug seems to affect only the warp tool, while when setting bilinear resampling on zoomed in/out rendering of the original 4326 raster dataset in the Symbology properties, it looks all good.

### Steps to reproduce the issue

1. Extract a -180 to 180 dg northern section (65 to 70 dg N) of e.g. ETOPO1 GeoTIFF.
2. Select Raster / Projections / Warp
3. Set output CRS to e.g. 3995, resampling method Bilinear, and resolution 1000 m, and run.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.0-Białowieża | QGIS code revision | d9022691f1
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.4.0
PROJ version | 8.2.0
EPSG Registry database version | v10.038 (2021-10-21)
GEOS version | 3.10.0-CAPI-1.16.0
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
latlontools | 3.5.9
grassprovider | 2.12.99
processing | 2.12.99
sagaprovider | 2.12.99
![polar](https://user-images.githubusercontent.com/76013985/143786623-a67cb8dc-a820-4133-a512-3bb334bac2ef.png)

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
> Select Raster / Projections / Warp 

@andskog The GDAL based tools in the Processing toolbox are "just" a GUI for the equivalent GDAL command line based tools. If with the same set of options you get the same results in the CLI then is something you may want to report to GDAL, not here.

**Comment by andskog** [comment]
Ah, of course. It does indeed reproduce in command line with gdal. Will report to GDAL, thanks.
