### ISSUE TITLE
Missing ssl module in QGIS 3.22 on Windows (used when installing a 3d party python package)

### ISSUE THREAD

**Issue by axelande** [qgis/QGIS#46276]
### What is the bug or the crash?

I've just upgraded from 3.16 to 3.22 and I have written several plugins (e.g https://github.com/axelande/geodatafarm3/blob/master/GeoDataFarm.py#L41-L54) that uses third party python packages. To install them I have a script that looks like this:

```
import platform
import subprocess
import sys
try:
    import matplotlib
except ModuleNotFoundError:
    print('installing matplotlib')
    if platform.system() == 'Windows':
        subprocess.call([sys.exec_prefix + '/python', "-m", 'pip', 'install', 'matplotlib'])
    else:
        subprocess.call(['python3', '-m', 'pip', 'install', 'matplotlib'])
```

But when I now launch QGIS 3.22 I get this error upon launch:

WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/matplotlib/

### Steps to reproduce the issue

Run QGIS 3.22 from the start menu, open the Python console and paste:

```
import platform
import subprocess
import sys
try:
    import matplotlib
except ModuleNotFoundError:
    print('installing matplotlib')
    if platform.system() == 'Windows':
        subprocess.call([sys.exec_prefix + '/python', "-m", 'pip', 'install', 'matplotlib'])
    else:
        subprocess.call(['python3', '-m', 'pip', 'install', 'matplotlib'])
```

### Versions

3.22.1 (Python 3.9)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
Possibly better suited for https://trac.osgeo.org/osgeo4w/report/1?sort=ticket&asc=0&page=1

**Comment by axelande** [comment]
I don't have a osgeo4w trac account so I can't report it there but I assume that this is related: https://trac.osgeo.org/osgeo4w/ticket/715

**Comment by alexbruy** [comment]
Can we close this? Seems it was fixed some time ago.
