### ISSUE TITLE
Expression builder does not work to with vector points in the 3D view (single point) 

### ISSUE THREAD

**Issue by milderchild** [qgis/QGIS#46282]
### What is the bug or the crash?

When you bring in a .shp or points with XYZ data into QGIS and try to use the expression string builder (billboard symbol>simple marker>data defined override>edit) the expression builder just doesn't seem to work. Brings up an error: 'No feature was found on this layer to evaluate the expression.' despite he layer having feature information. 

For an example see: https://gis.stackexchange.com/questions/417216/color-rgbr-g-b-doesnt-colour-points-of-a-3d-billboard-in-qgis?noredirect=1#comment679629_417216

### Steps to reproduce the issue

1. add a bunch of points with xyz and feature info
2. import as txt or shp.
3. go to properties > 3d view > billboard> sinle symbol 
4. click billboard symbol
5. click on the simple marker
6. go to any of the data defined override dropdowns on the right > edit
7. enter a valid expression 
8. see error. scratch head confused. give up. open a beer. 

### Versions

QGIS version
3.16.9-Hannover
QGIS code revision
9f8d2f79
Compiled against Qt
5.15.2
Running against Qt
5.15.2
Compiled against GDAL/OGR
3.3.1
Running against GDAL/OGR
3.3.1
Compiled against GEOS
3.9.1-CAPI-1.14.2
Running against GEOS
3.9.1-CAPI-1.14.2
Compiled against SQLite
3.35.2
Running against SQLite
3.35.2
PostgreSQL Client Version
13.0
SpatiaLite Version
5.0.1
QWT Version
6.1.3
QScintilla2 Version
2.11.5
Compiled against PROJ
8.1.0
Running against PROJ
Rel. 8.1.0, July 1st, 2021
OS Version
Windows 10 Version 2009
Active python plugins
AnotherDXF2Shape; 
coordinate_capture; 
FreehandRasterGeoreferencer; 
go2streetview; 
LAStools; 
NLSgpkgloader-master; 
profiletool; 
Qgis2threejs; 
quick_map_services; 
scriptrunner3; 
db_manager; 
MetaSearch; 
processing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
> When you bring in a .shp or points with XYZ dat

@milderchild please attach a sample



> Active python plugins
> AnotherDXF2Shape;
> coordinate_capture;
> FreehandRasterGeoreferencer;
> go2streetview;
> LAStools;
> NLSgpkgloader-master;
> profiletool;
> Qgis2threejs;
> quick_map_services;
> scriptrunner3;

Please also try on a new QGIS profile, no 3rd party plugins installed.
