### ISSUE TITLE
Point pattern fill symbol clipping

### ISSUE THREAD

**Issue by Xeenych** [qgis/QGIS#46307]
### Feature description

Please add an option to hide clipped symbols in point pattern fills.
When the symbols are large enough or, then it looks awful
![20211028032420_327](https://user-images.githubusercontent.com/11345848/144202167-a44010a9-e53c-4979-b18d-206225726dc5.jpg)

### Additional context

QGIS 3.22.1

**Comment by nyalldawson** [comment]
This is available in 3.24
