### ISSUE TITLE
Crash with Raster Image Marker and meters at scale

### ISSUE THREAD

**Issue by baswein** [qgis/QGIS#46304]
### What is the bug or the crash?

QGIS Crashes when zooming in on a point file with a raster image marker that is selected and set to meters at scale or map units. 

### Steps to reproduce the issue

1. Add a point layer and create a point
2. Set the style to raster image marker and link a raster image (I tried jpeg, png and svg)
3. Set the units to map units or meters at scale
4. Select the point 
5. Zoom in and then zoom out 
6. QGIS crashes. 

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.23.0-Master | QGIS code revision | 8e46f2ca6a
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.4.0
PROJ version | 8.2.0
EPSG Registry database version | v10.038 (2021-10-21)
GEOS version | 3.10.0-CAPI-1.16.0
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
This copy of QGIS writes debugging output.
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.5
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Tried on 3.16.7, 3.22.1 and 3.23 master 
Text from crash report. 
## Report Details

**Crash ID**: [8b337cfaac2b2d50239c18b8f4994502bfb09d84](https://github.com/qgis/QGIS/search?q=8b337cfaac2b2d50239c18b8f4994502bfb09d84&type=Issues)

**Stack Trace**
<pre>
QgsGlowEffect::setRamp :
QgsImageOperation::overlayColor :
QgsImageOperation::overlayColor :
QgsImageOperation::stackBlur :
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.22.1-Bia?owie?a
QGIS code revision: 663dcf8fb9
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.0
Running against GDAL: 3.4.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

**Comment by roya0045** [comment]
Why does the stack trace mention the glow effect, did you have anything else going on in your symbology? I also think a sample project will be requested to replicate.

**Comment by baswein** [comment]
@roya0045 - I don't know what the stack trace glow effect means. That report was from early on in my troubleshooting. QGIS is not currently giving me any crash reports. Could it be the selection highlight? 
Here is a GIF of it in action: 
![2021-12-01_08-31-18](https://user-images.githubusercontent.com/15817745/144243925-dd30ba09-a792-4473-9e8e-03750511d3d4.gif)
Here is a simple sample project:
[Raster_marker_test_file.zip](https://github.com/qgis/QGIS/files/7634256/Raster_marker_test_file.zip)

**Comment by gioman** [comment]
I can replicate the crash with the provided project and steps on 3.22.1 and master, but not on 3.16.14

**Comment by baswein** [comment]
Thanks for the quick fix!
