### ISSUE TITLE
Multi Edit applies attributes automatically when opened from attibute table with selected features

### ISSUE THREAD

**Issue by LeneFischer** [qgis/QGIS#46306]
### What is the bug or the crash?

Working with a geopagkage in the attribute table
Selecting rows
_Toggle Multi edit mode_ and it gives this error: 
![Capture](https://user-images.githubusercontent.com/9905437/144184382-29a6b268-c09e-4ad4-99d8-c28b8723c01b.JPG)

Seems as if field no 4 is shown

If I go to _Attribute Form_ and make the _fid_ HIDDEN it solve the problem ...
![Capture2](https://user-images.githubusercontent.com/9905437/144184552-65786567-425f-4754-a0de-4a015faf0c0d.JPG)

File with data 
[data_marker_vandloeb_soe.zip](https://github.com/qgis/QGIS/files/7631405/data_marker_vandloeb_soe.zip)

### Steps to reproduce the issue

1. Select features
2. Open Attribute table
3. Toggle Multi Edit Mode

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.20.2-Odense | QGIS code revision | 9f59a156
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.1
PROJ version | 8.1.0
EPSG Registry database version | v10.027 (2021-06-17)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins | DatafordelerDataforsyningenDigitizingToolsgeosearch_dkKortforsyningenmapswipetool_pluginMerginprofiletoolQuickOSMquick_map_servicesStreetViewSubmissionvaluetooldb_managerprocessing

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by uclaros** [comment]
The problem is that when opening multi-edit from the attribute table for the first time in an edit session, all fields are applied to the selected features automatically, overwriting existing data. The fid constraint on the geopackage prevents the real damage to be saved and seen in this case.
The format seems irrelevant, I can replicate on memory layers and shapefiles.

**Comment by roya0045** [comment]
when switching the call to `save` the attributes get executed 5 times. This will be annoying to fix 'safely'.

**Comment by nyalldawson** [comment]
Fallout from https://github.com/qgis/QGIS/pull/45532
