### ISSUE TITLE
Add "open form button" in Select Features form (F3)

### ISSUE THREAD

**Issue by lucalanteri** [qgis/QGIS#46317]
### Feature description

Is it possible to add a button in "Select features" form (F3) that directly open the form  (if only one feature is selected) or open the table in form view and with features filtered in case more than one features is selected ?
Maybe that the second option could be fine also when only one feature is selected.

Now to perform this action, I have to:
- do my search
- press select features button
- close F3 form
- open the table 
- switch to form view
- change from "Show all features to "Show selected Features" 

thanks

**Comment by uclaros** [comment]
> * open the table
> 
> * switch to form view
> 
> * change from "Show all features to "Show selected Features"

FYI, you can open the attribute table with shift+F6 to go directly to *Show selected features* mode, a toolbar button has been also added for that function.
