### ISSUE TITLE
Still snapping to embedded polygons when snapping of layer is disabled in advanced configuration

### ISSUE THREAD

**Issue by lindacamathias** [qgis/QGIS#46316]
### What is the bug or the crash?

Still snapping on embedded polygons when advanced configuration is chosed in advanced snapping settings and snapping in all layers are disabled. it does not snap on embedded lines nor points when snapping is disabled, it happens only with embedded polygon layers. 

I observed that it does not take into account the snapping tolerance set in the project snapping options and neither the settings in the global options under digitizing when snapping mistakenly. 
![snap_embed_poly](https://user-images.githubusercontent.com/77726342/144278635-f47fd074-1c56-4760-bd13-1af6c08b3762.gif)

### Steps to reproduce the issue

1. embed polygon layer (and maybe also line and/or points for control)
2. create a digitizing layer
3. go to project snapping settings and choose advanced configuration
3.  disable snapping in all layers (or at least the embedded ones)
4.  change to digitize modus  and check whether it's snapping or not
  --> you will see it keeps snapping  to the embedded polygon layer

### Versions

tested with 3.16.14  and 3.22.1 (same behaviour)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
> 5\. change to digitize modus  and check whether it's snapping or not
>         --> you will see it keeps snapping  to the embedded polygon layer

@lindacamathias I cannot replicate with the provided steps. If you haven't done it already please try on a new QGIS profile.

**Comment by lindacamathias** [comment]
thanks for your fast feedback! 
a new profile didn't change anything. i did some further research and it looks like there's a "zombie" in my project. it snaps to the layer even if it's completely removed out of the project. i suspect the bug with the  joins in the embedded layers may have caused the problems  (https://github.com/qgis/QGIS/issues/44162 ).
copy all the layers to a virgin project seems to solve the issue for the moment. i'll report in case i find out sth more

**Comment by gioman** [comment]
> i'll report in case i find out sth more

reopen if necessary.
