### ISSUE TITLE
Getting numpy ndarray from QgsRasterLayer using PyQGIS

### ISSUE THREAD

**Issue by geoyee** [qgis/QGIS#46324]
### Feature description

QGIS would rock even more if we can getting numpy ndarray from QgsRasterLayer using pyqgis.

In [gis.stackexchange](https://gis.stackexchange.com/questions/317464/converting-qgsraster-object-to-array/317650#317650), I found that many people have the same needs as me: how to converting QgsRaster object to array.

I can get a **QgsRasterLayer** from `iface.activeLayer()` now, but I want to get a image ndarray from this QgsRasterLayer. 

It seems that **traversal QgsRasterBlock** and **reloading in GDAL** are the only two methods I have seen so far. I hope there is an attribute can get array directly, like this, ex:
``` python
raster = iface.activeLayer()  # This is a QgsRasterLayer
array = raster.array  # This is a ndarray
array = cv2.xxxxxx(array)  # We can use other image function to deal with this array
```

**Comment by eurojam** [comment]
I would also appreciate such a feature, it would open an easy access to the possibilities of numpy arrays and the use of numpy and scipy within the processig algorith.0,
