### ISSUE TITLE
Georeferencer freezes QGIS

### ISSUE THREAD

**Issue by Despert1** [qgis/QGIS#46327]
### What is the bug or the crash?

Each time I run the calculation linked to the georeferencer, it freezes for the computer. I can place my points, and choose the parameters but after the program freezes. I uninstalled and reinstalled QGIS (Hannover) but without success the problem persists.

### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/95301708/144402945-40a3a9d6-4d54-4c48-bb95-f701ba721fab.png)

### Versions

I am using both Hanover and version 3.22.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
@Despert1 please add/attach the raster you want to georef, the gcp table and georef parameters.

**Comment by Despert1** [comment]
I've do it but same problem. I use Qgis since 8 years ant when a use georferencer I've the same method. It' the first time that my comuter freezes.

**Comment by gioman** [comment]
@Despert1 please add/attach the raster you want to georef, the gcp table and georef parameters.

**Comment by mbodnar-GS** [comment]
I have this happen to my user profile eventually and have to create a new profile to get the georeferencer to work again. I cannot determine why the georeferencer becomes corrupted in the user profile and hangs when starting the georeference transformation. A new profile is a certain fix but can be time consuming when needing to reinstall and configure a suite of plugins.

**Comment by RinceWND** [comment]
> I have this happen to my user profile eventually and have to create a new profile to get the georeferencer to work again. I cannot determine why the georeferencer becomes corrupted in the user profile and hangs when starting the georeference transformation. A new profile is a certain fix but can be time consuming when needing to reinstall and configure a suite of plugins.
> 
> LTR 3.16

Thank you so much for this! I just backed-up my profile folder, wiped it out, and tried my failed georeference again... And it worked lika a charm! Then I started digging into what was the problem, copying back files from my backup, and it turned out it was `QGIS3.ini`. After some further investigation of my settings I found out that for me the culprit was this specific line of a [SemiAutomaticClassificationPlugin] block: "threadsValue=4". If it's set to anything other than `1` the georeferencer freezes. Have no idea how this line of a plugin can impact the georeferencer but it seems like it happens on startup, since when I set "threadsValue" via the plugin's GUI georeferencing seem to work until I restart QGIS. (3.22.1 Bielowieza, btw)

**Comment by gioman** [comment]
> [SemiAutomaticClassificationPlugin]

@RinceWND this is why we always ask to check/test with a new QGIS profile and no 3rd party plugins installed.

**Comment by Spartacus1** [comment]
For now, temporarly disable the SACP, if you have it installed, before doing a georeferencing session.

**Comment by PavlosDem99** [comment]
> > I have this happen to my user profile eventually and have to create a new profile to get the georeferencer to work again. I cannot determine why the georeferencer becomes corrupted in the user profile and hangs when starting the georeference transformation. A new profile is a certain fix but can be time consuming when needing to reinstall and configure a suite of plugins.
> > LTR 3.16
> 
> Thank you so much for this! I just backed-up my profile folder, wiped it out, and tried my failed georeference again... And it worked lika a charm! Then I started digging into what was the problem, copying back files from my backup, and it turned out it was `QGIS3.ini`. After some further investigation of my settings I found out that for me the culprit was this specific line of a [SemiAutomaticClassificationPlugin] block: `threadsValue=4`. If it's set to anything other than `1` the georeferencer freezes. Have no idea how this line of a plugin can impact the georeferencer but it seems like it happens on startup, since when I set "threadsValue" via the plugin's GUI georeferencing seem to work until I restart QGIS. (3.22.1 Bialowieza, btw)
> 
> And if I deactivate the plugin, even when the .ini file has the parameter set to 4, the georeferencer works normally. The plugin's initialisation routine messes things up...? This is supported by the fact that if I start QGIS with the plugin deactivated I can georeference w/o problems, however if I then go and activate the plugin the next georeferencing then freezes. And just for "scientific" exhaustiveness: if I start QGIS with the plugin activated (and `threadsValue` set to 4) and then disable it before georeferencing, it still freezes.

Amazing tips  ! It's working perfectly
