### ISSUE TITLE
Virtual Layers - Can't add or modify an existing

### ISSUE THREAD

**Issue by TonyShep** [qgis/QGIS#46334]
### What is the bug or the crash?

Virtual Layers showing "Cannot get virtual layer select dialog from provider" when adding a new or modifying an existing.

It makes existing project files almost nu-usable!

After installing V3.22

![Virtual-Lry-Error](https://user-images.githubusercontent.com/54558128/144484072-e29afc6f-5abe-497b-af34-a464c234f985.jpg)

### Steps to reproduce the issue

Layer -> Create Layer -> New Virtual Layer

OR

See existing Virtual Layer in Layers List, right click and "Edit Virtual Layer"

### Versions

3.22.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by pigreco** [comment]
I confirm

## OSGeo4W v2 QGIS 3.22.1 and master

**Comment by nyalldawson** [comment]
Duplicate of https://github.com/qgis/QGIS/issues/46116

**Comment by TonyShep** [comment]
Is there a temporary workaround?
