### ISSUE TITLE
Vector Layer disappears if its not displayed to its full extent

### ISSUE THREAD

**Issue by sonicnkt** [qgis/QGIS#46333]
### What is the bug or the crash?

I just did a "clean" install of QGIS 3.16.3 (Flatpak) on Linux. 
I choose the LTE Flatpak because this is the Version i have to use at Work on Windows 10.

I tried to open several of my existing projects and always have the same issue, whenever i zoomed  in close enough that the whole layer isn't displayed anymore (past layer extent) it disappears. This only happens to vector layers, raster works fine. 

~~Tried gpkg as well as shape layers, happens with both.  It also doesn't matter if a open an existing project or create a new one.~~

**Update:**
It only happens with geopackages containing vector data that i created previously on a windows qgis installation (same LTE version). Shape files behave normally.

I found this Issue #18004 looking for a solution and this seems to be the same problem, only problem is that i cant find those ".qix" files mentioned in the issue. 

### Steps to reproduce the issue

1. Install QGIS LTE from flathub
2. Open an existing project with vector layers or create a new one and add those exisiting gpkg's
3. Zoom in past the layer extent
4. See Layers dissappearing

### Versions

3.16.13-Hannover - Flatpak/Flathub

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Since it sometimes matters...
Running Manjaro with KDE, Xorg and NVIDIA Drivers

**Comment by nyalldawson** [comment]
I've also seen this happen if a geometry has a NaN value for a vertex

**Comment by sonicnkt** [comment]
Ok i was wrong, it seems it only happens with my existing geopackages and not existing shape files.
Newly created layers work fine as well.

I will update the original issue accordingly...

I also noticed if i try to edit those gpkg i get the following error:
```
Datenanbieterfehler:
      OGR-Fehler beim Löschen des Objekts 17: sqlite3_exec(DELETE FROM "osm_cut_buildings" WHERE "fid" = 17) failed: no such module: rtree
`` 

So it seems the flatpak version is missing some sqlite features, can't say if this is related in any way to the main issue tho

**Comment by gioman** [comment]
> Flatpak/Flathub

@sonicnkt no problem whatsoever on Win10 and Ubuntu 20.04 (QGIS installed from QGIS.org's repos).

**Comment by sonicnkt** [comment]
@gioman Yeah this problem seems to be related to flatpak only. I choose that because there is no official supported LTR release for Manjaro. Like i said im not having any issues on windows 10 either.

**Comment by gioman** [comment]
> Is the flatpak not officially supported?

it not maintained by the QGIS project, so you should report the issue on flathub and not here.

**Comment by sonicnkt** [comment]
Sorry the issue link on flathub led me here but i know found the specific github page for the flatpak release. 
I guess this can be closed then. 
Sorry!
