### ISSUE TITLE
Support for OGC API Records in the default connections of MetaSearch

### ISSUE THREAD

**Issue by bo-lu** [qgis/QGIS#46336]
### Feature description

Background: Currently the default connections (i.e., connections-default.xml) only allow for CSW endpoints in the MetaSearch plugin. 

Feature: We would like to add support for OGC API Records endpoints for early adopters.

**Comment by gioman** [comment]
@bo-lu like https://github.com/qgis/QGIS/pull/44812 ?

**Comment by tomkralidis** [comment]
Merged into master.
