### ISSUE TITLE
Icon for QGZ files in MacOS

### ISSUE THREAD

**Issue by vdhatterwal** [qgis/QGIS#46342]
### Feature description

There is no icon associated with QGZ file in Mac OS and it shows up as plain file.

Due to this it becomes difficult to loacte the QGZ file among the various other files in Finder window.

<img width="1032" alt="Icon not shown for QGZ files in Finder Mac OS" src="https://user-images.githubusercontent.com/6457168/144533858-a1026891-02f3-4174-9ffd-259673ab0fa3.png">

### Additional context

Windows displays the icons for QGZ files in Explorer, but this problem seems to be occuring in Mac OS only.

**Comment by gioman** [comment]
@vdhatterwal looks fine on QGIS 3.22 on macOS Catalina.

**Comment by vdhatterwal** [comment]
> @vdhatterwal looks fine on QGIS 3.22 on macOS Catalina.

Sorry, I forgot to mention that I am using QGIS LTR 3.16.13 on macOS Monterey.

**Comment by Spartacus1** [comment]
Select one of those files and use the System's Get Info or keystroke "command+I". From the info window, in the menu "Open with" select the QGIS app and then hit button "Change all". Icons should then change to the generic QGZ icon (if not, force the finder to quit).

**Comment by vdhatterwal** [comment]
> Select one of those files and use the System's Get Info or keystroke "command+I". From the info window, in the menu "Open with" select the QGIS app and then hit button "Change all". Icons should then change to the generic QGZ icon (if not, force the finder to quit).

I tried changing the file icon and then clicked Change All button as well. But once the project is saved again, it loses the icon again. Nothing works for the LTR branch till date.

**Comment by Diego635** [comment]
I have the same issue. I tried all the proposed solutions but it still doesn't show any icon on qgz files
