### ISSUE TITLE
Corrupted xslx files when entering long table names

### ISSUE THREAD

**Issue by m-kuhn** [qgis/QGIS#46345]
### What is the bug or the crash?

When using "vector layer" -> "export features as", qgis allows specifying a layer name.

XSLX allows a maximum of 31 characters as sheet names. If more are provided, Excel complains about a corrupted file when opening the resulting file.
Excel will propose to fix the file and does so apparently successfully.

Still the message is irritating and the sheet name should directly be trimmed to 31 characters max.

![image](https://user-images.githubusercontent.com/588407/144551826-be26d837-68f1-4d2e-a1f4-a21c7b4c1159.png)

![image](https://user-images.githubusercontent.com/588407/144551896-c0b69388-129a-4fb4-b9b2-d50b76635c2b.png)

![image](https://user-images.githubusercontent.com/588407/144551914-2d656c11-6742-42f3-9a45-57c302a2f38d.png)

![image](https://user-images.githubusercontent.com/588407/144551950-d97a15be-e5dd-40aa-b596-61fc1c76451a.png)

### Steps to reproduce the issue

1. Open vector layer
2. Export features as xslx
3. Enter long name

### Versions

3.16
I don't have an excel around to test newer versions

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by Houska1** [comment]
Confirmed persists through current 3.23 Master osgeo4w

**Comment by roya0045** [comment]
I can do a quick fix.
