### ISSUE TITLE
Advanced digitizing works wrong with Snapping

### ISSUE THREAD

**Issue by axyzdile** [qgis/QGIS#46352]
### What is the bug or the crash?

bug

### Steps to reproduce the issue

1. Start edit layer in some projection (example Pulkovo 1995 GK Zone 11N) with advanced digitizing enabled.
2. Try to "snap" to point in another projection (for example: WGS-1984)
3. advanced digitizing will show and use ("copy data") WGS_1984 coordinates Instead of Pulkovo 1995 GK Zone 11N.
 3.1 It'is ok when you just "create one vertex" in feature, although "advanced digitizing" still show "WGS 1984" coordinates
 3.2 It's bug when you start to change **d, a** parametres in "advanced digitizing bar" - it creates blueprint with wrong coordinates.
4. it is imposible to work and create any right features cause for example WGS x,y = 115, 57 not even acceptable in Pulkovo 1995 GK Zone 11N.

Reason: **QGIS “on the fly” CRS transformation** doesn't work in 
snapping -> click -> *there should be CRS transformation but here just x,y copying" -> advanced digitizing

Full Video with bug: https://youtu.be/VIMkMosS1QY

https://user-images.githubusercontent.com/64549817/144590088-3da8e449-26ca-444e-9915-82e6ecbe72c6.mp4

### Versions

3.20, 3.22 possible almost all 3+

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
> Full Video with bug: https://youtu.be/VIMkMosS1QY

@axyzdile can you also add a sample project (with all the necessary snapping configs) with sample data? thanks.

**Comment by axyzdile** [comment]
[QGIS digitizing BUG.zip](https://github.com/qgis/QGIS/files/7649039/QGIS.digitizing.BUG.zip)


> > Full Video with bug: https://youtu.be/VIMkMosS1QY
> 
> @axyzdile can you also add a sample project (with all the necessary snapping configs) with sample data? thanks.

**Comment by axyzdile** [comment]
> > > Full Video with bug: https://youtu.be/VIMkMosS1QY
> > 
> > 
> > @axyzdile can you also add a sample project (with all the necessary snapping configs) with sample data? thanks
[QGIS digitizing BUG.zip](https://github.com/qgis/QGIS/files/7649060/QGIS.digitizing.BUG.zip)
.

**Comment by gioman** [comment]
@axyzdile possibly related to https://github.com/qgis/QGIS/issues/46128

Can you please check on 3.16.14 if it works ok? Thanks.

**Comment by axyzdile** [comment]
> @axyzdile possibly related to #46128
> 
> Can you please check on 3.16.14 if it works ok? Thanks.

**It works absolutely correctly in 3.16.14.**


P.S.: rechecked it once more time with 3.22 with absolutely cleared profile and there is still bug. with 3.16 - everything fine.

**Comment by antoniolocandro** [comment]
I can confirm, this is still the case with latest nightly, works ok with the QGIS LTR 3.16.15. It seems that in the LTR the engine automatically reprojects to the map srid in use but in the 3.22+ it is just taking the value as per the projection of the layer which is not always the case. I think the behaviour of the QGIS LTR is the desirable one.

Also I have hit an issue when with intersection it report NaN like it can't determine the value but in the LTR it works OK.

**Comment by elpaso** [comment]
I tried your test project but could not reproduce on curent master/linux:

![immagine](https://user-images.githubusercontent.com/142164/152822888-8c8d6210-30fb-450f-942f-e9b5411c0387.png)

**Comment by antoniolocandro** [comment]
Updated today to latest master, tried and got the same issue and even displays some weird behaviour. Attached video showing it, I think the problem persists and 3.16 doesn't have this issue


https://user-images.githubusercontent.com/4627073/153460716-3c445061-4d67-44da-9813-5ec0373debc8.mp4




QGIS version
3.23.0-Master
QGIS code revision
15a77662d4
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009




This copy of QGIS writes debugging output.




Active Python plugins
DigitizingTools
1.5.1
latlontools
3.5.9
MemoryLayerSaver
4.0.4
mmqgis
2021.9.10
quick_map_services
0.19.26
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99

**Comment by antoniolocandro** [comment]
Here is the issue showing NaN

![image](https://user-images.githubusercontent.com/4627073/153461099-197ecdad-3fae-47f4-93c6-ccae34dfa241.png)

**Comment by gioman** [comment]
> I tried your test project but could not reproduce on curent master/linux:

@elpaso I have tried master o Windows with the attached project, and I also see very weird things happening. Probably the same or related to https://github.com/qgis/QGIS/issues/46128
