### ISSUE TITLE
Weird/wrong behavior when adding a new record in form view of the table of attributes

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#46365]
### What is the bug or the crash?

I'm observing a wrong/weird behavior when adding a new record to a table in form view. As it is not easy to describe in words where the mandatory screencast:

https://user-images.githubusercontent.com/1951107/144707166-a206b472-66d6-4a2c-aa3b-9d1d6863bf63.mp4

Basically while filling the form, the moment I try to fill a "text edit" field QGIS has an hiccup the moment I press the first keystroke and a few moments later he focus moved to another already existing record (at 00:22 in the above video).

This is very annoying as it breaks/interrupts the workflow of adding records in form view.

### Steps to reproduce the issue

See above.

### Versions

3.16.14 / 3.22.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by elpaso** [comment]
Can you please attach a small test project with the smallest set of fields and features to reproduce the issue?

**Comment by gioman** [comment]
> Can you please attach a small test project with the smallest set of fields and features to reproduce the issue?

@elpaso in the meantime I further developed that form, and right now can't replicate what I described back in December.
