### ISSUE TITLE
Open the vector tool box 

### ISSUE THREAD

**Issue by MarilliaCalado** [qgis/QGIS#46368]
### What is the bug or the crash?

I cannot access the vector in my qgis program. I've already done the updates and it's the most up-to-date software possible. I already uninstalled and installed it again, tried restarting the laptop, but it's not a problem with the internal system.

### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/95546886/144723530-f248d88e-6300-42d4-abb2-5055a1937d25.png)
![image](https://user-images.githubusercontent.com/95546886/144723544-505c2e26-9c03-42bd-bf92-97c150cf39f7.png)
![image](https://user-images.githubusercontent.com/95546886/144723550-a810dcd1-aeab-4a26-b909-beb4039a84b3.png)
![image](https://user-images.githubusercontent.com/95546886/144723557-4cbb4672-7a36-4866-8154-95b2f6767d40.png)
![image](https://user-images.githubusercontent.com/95546886/144723562-6d198d65-cc4c-4fdc-ab91-d6d9d603866e.png)
![image](https://user-images.githubusercontent.com/95546886/144723576-5560db29-792e-436b-a7fc-bff38d13cede.png)
![image](https://user-images.githubusercontent.com/95546886/144723586-85502555-a052-4af0-80e0-0be1dbc2c363.png)
![image](https://user-images.githubusercontent.com/95546886/144723591-c8d8d40b-b640-48f3-98a5-5834b807c7ff.png)
![image](https://user-images.githubusercontent.com/95546886/144723594-43653915-eab8-431a-bae5-eb3aee71b300.png)
![image](https://user-images.githubusercontent.com/95546886/144723600-aa8fd910-c465-4866-9506-50523cb87e13.png)
![image](https://user-images.githubusercontent.com/95546886/144723602-588a13cf-f563-4b05-ac89-c78f0e76b90c.png)
![image](https://user-images.githubusercontent.com/95546886/144723609-44249290-b26f-4d62-9e07-bfdf4560e420.png)
![image](https://user-images.githubusercontent.com/95546886/144723614-f28bb0fe-4ecd-49fb-b5d7-ca6ae9410cc6.png)

### Versions

Versão do QGIS
3.16.13-Hannover
Código da versão do QGIS
a8618a94
Compilado sobre Qt
5.15.2
Rodando sobre Qt
5.15.2
Compilado sobre GDAL/OGR
3.4.0
Rodando sobre GDAL/OGR
3.4.0
Compilado sobre GEOS
3.10.0-CAPI-1.16.0
Rodando sobre GEOS
3.10.0-CAPI-1.16.0
Compilado no SQLite
3.35.2
Executando contra SQLite
3.35.2
Versão do cliente PostgreSQL
13.0
Versão SpatiaLite
5.0.1
Versão do QWT
6.1.3
Versão QScintilla2
2.11.5
Compilado com PROJ
8.2.0
Em execução com PROJ
Rel. 8.2.0, November 1st, 2021
Versão SO
Windows 10 Version 2009
Ativar complementos python
quick_map_services; 
SemiAutomaticClassificationPlugin; 
db_manager

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
> I cannot access the vector in my qgis program

@MarilliaCalado activate the Processing plugin in the plugin manager.

**Comment by MarilliaCalado** [comment]
Thank you!

> > I cannot access the vector in my qgis program
> 
> @MarilliaCalado activate the Processing plugin in the plugin manager.

The problem was solved! Thank you!
