### ISSUE TITLE
Ignore out of range option in interpolated symbol renderer creates artifacts if start value is out of range

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#46362]
### What is the bug or the crash?

In line symbol interpolated rendering type, if start value is lower than min value and you check "Ignore out of range", then you get weird lines from the start point to the top left corner of the canvas for every feature whose start point satisfies this condition.

In the attached screen cast I'm using a field but i realized afterwards that using direct numbers generates the same issue as well as having start value greater than the max value. No issue afaict with end value being lower than min value or greater than max.

### Steps to reproduce the issue

![interpolated](https://user-images.githubusercontent.com/7983394/144698839-e680d560-d923-48d4-9403-31e128894e66.gif)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.0-Białowieża | QGIS code branch | Release 3.22
-- | -- | -- | --
Qt version | 5.12.8
Python version | 3.8.10
GDAL/OGR version | 3.0.4
PROJ version | 6.3.1
EPSG Registry database version | v9.8.6 (2020-01-22)
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
SQLite version | 3.31.1
PostgreSQL client version | 12.8 (Ubuntu 12.8-0ubuntu0.20.04.1)
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.2
OS version | Ubuntu 20.04.3 LTS
  |   |   |  
Active Python plugins
trackable_project_files | v1.2.2
MapsPrinter | 0.6
MemoryLayerSaver | 4.0.4
db_manager | 0.1.20
processing | 2.12.99

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by elpaso** [comment]
What is the expected behavior of "out of range" ? Should it skip the points of the line which are (interpolated) out of range?

**Comment by DelazJ** [comment]
Yes, from my understanding. See https://docs.qgis.org/3.22/en/docs/user_manual/style_library/symbol_selector.html#line-symbols (not the most direct URL but...)
@vcloarec might know better.

**Comment by elpaso** [comment]
@DelazJ do you know if is there a reason for calling it "Clip out of range values" here?

![immagine](https://user-images.githubusercontent.com/142164/152385087-04305d9a-54a7-4919-be45-d9ac072619b2.png)

**Comment by elpaso** [comment]
I see the behavior is different indeed, the varying width do not render at all the lines segments where one of the two points are out of range while the varying color interpolates, I'm not sure if they should behave the same.
