### ISSUE TITLE
QgsTriangle::angles() fails to correctly return the value of angles greater than 90° deg

### ISSUE THREAD

**Issue by nicogodet** [qgis/QGIS#46370]
### What is the bug or the crash?

Actually the function code strangely subtract 90 to such angles:

https://github.com/qgis/QGIS/blob/dd0cd13a00998bc153c0b6519ea75038b57a6df5/src/core/geometry/qgstriangle.cpp#L397-L403
   angles.append( ( a1 > M_PI_2 ? a1 - M_PI_2 : a1 ) );
   angles.append( ( a2 > M_PI_2 ? a2 - M_PI_2 : a2 ) );
   angles.append( ( a3 > M_PI_2 ? a3 - M_PI_2 : a3 ) );

In fact, the correct value of the angle is 90.05074766261984076 deg. and 
not 0.05074766261984076.

Thanks @agiudiceandrea for digging into this issue and @lbartoletti I can't assign you to this issue (no right).

### Steps to reproduce the issue

```python
>>> triangle = QgsTriangle()
>>> triangle.setExteriorRing(QgsLineString([QgsPoint(78598.328125, 330538.375, 0), QgsPoint(78606.3203125, 330544, 0), QgsPoint(78601.46875, 330550.90625, 0), QgsPoint(78598.328125, 330538.375, 0)]))
>>> triangle.angles()
[0.7119509950830287, 0.0008857138004074727, 0.85795961791146]
>>> [math.degrees(a) for a in triangle.angles()]
[40.79178723839677, 0.05074766261984076, 49.157465098983366]
```

### Versions

Qgis 3.22.1 OSGeo4w v2

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

https://lists.osgeo.org/pipermail/qgis-developer/2021-December/064349.html

**Comment by agiudiceandrea** [comment]
@gioman I don't think this is about "Expressions"

**Comment by agiudiceandrea** [comment]
I've found that the value of the angles returned by `QgsTriangle().angles()` are incorrect also for angles NOT grater than 90° deg. and it seems to depend on the order of the triangle vertices in some circumstances (but not always).

For the following equilateral triangle, it do depends on the order of the vertices:

```python
tri = QgsTriangle( QgsPoint( 0, 0 ), QgsPoint( 1, math.sqrt(3) ), QgsPoint( 2, 0 ) )
print([round(math.degrees(i),3) for i in tri.angles()])
[30.0, 30.0, 30.0] # INCORRECT
```
```python
tri = QgsTriangle( QgsPoint( 2, 0 ), QgsPoint( 1, math.sqrt(3) ), QgsPoint( 0, 0 ) )
print([round(math.degrees(i),3) for i in tri.angles()])
[60.0, 60.0, 60.0] # CORRECT
```

Instead, for the following right triangle, it doesn't:

```python
tri = QgsTriangle( QgsPoint( 0, 0 ), QgsPoint( 0, 3 ), QgsPoint( 4, 0 ) )
print([round(math.degrees(i),3) for i in tri.angles()])
[90.0, 36.87, 53.13] # CORRECT
```
```python
tri = QgsTriangle( QgsPoint( 4, 0 ), QgsPoint( 0, 3 ), QgsPoint( 0, 0 ) )
print([round(math.degrees(i),3) for i in tri.angles()])
[36.87, 53.13, 90.0] # CORRECT
```

While it does for the following scalene triangle:
```python
tri = QgsTriangle( QgsPoint( 0, 0 ), QgsPoint( 1, 3 ), QgsPoint( 3, 0 ) )
print([round(math.degrees(i),3) for i in tri.angles()])
[18.435, 37.875, 33.69] # INCORRECT
```
```python
tri = QgsTriangle( QgsPoint( 3, 0 ), QgsPoint( 1, 3 ), QgsPoint( 0, 0 ) )
print([round(math.degrees(i),3) for i in tri.angles()])
[56.31, 52.125, 71.565] # CORRECT
```
