### ISSUE TITLE
format_number() not working as expected if locale is not EN_US

### ISSUE THREAD

**Issue by dingausmwald** [qgis/QGIS#46373]
### What is the bug or the crash?

Don't know what the problem is exactly.
Just wanted to set the precision for a length column.
As default value in the layer properties, for format_number($length,2) i get 0.
Setting format_number($length,2) in the attribute table and update selected does work.

Setting the precision for a geopackage does not work either. I get 0 as precision after refactoring fields and saving as geopackage.

### Steps to reproduce the issue

Set default value format_number($length,2). Update geometry.
safe geopackage with precision 2 for a double or int64 field.

### Versions

3.16.14

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
> Set default value format_number($length,2). Update geometry.
> safe geopackage with precision 2 for a double or int64 field.

@dingausmwald 

In a int field you surely won't get any decimal.

Having created a real/double field in  GPKG, the expression

format_number($length,2)

returns 2 decimals here.

No problems too in saving with "save as..." and with refactor fields.

**Comment by dingausmwald** [comment]
Have you tried on windows?

**Comment by gioman** [comment]
> Have you tried on windows?

@dingausmwald yes

**Comment by dingausmwald** [comment]
Stumbled over this bug again, did some further testing and created a testfile. Still happens in 3.16.15
This bug only happens when you modify an existing line feature. round($length,2) does update the length field. format_number($length,2) doesn't.
Creating a new feature is no problem. Just modifying an existing feature sets the length field to 0 AFTER saving the modification. Before saving, the length gets updated properly.

The testfile contains a default style with 3 length (laenge) fields. One with round($length,2), one with $length and one with format_number($length,2). The latter produces the bug
[Trassen.zip](https://github.com/qgis/QGIS/files/7852524/Trassen.zip)
.

**Comment by gioman** [comment]
> The latter produces the bug

@dingausmwald works fine here


![image](https://user-images.githubusercontent.com/1951107/149093291-c84f89d1-b4b9-4b1d-8af6-2fc90cb4649f.png)

**Comment by dingausmwald** [comment]
Allright. When i saw your decimal symbol, i also checked this by changing our locale settings (settings/general/locale) from de_DE ( , ) to en_US ( . ). Now it does work as expected. So its the language in which the number is formatted in qgis. Setting the language in format_number doesn't make a difference.

I also reported a similar bug with format_date. When set this to german date format (dd.MM.yyyy), qgis wasn't able to filter dates (f.e. "from" and "between" a date) with the filter function in the attribute table. Maybe there could be some work done so the individual languages are fetched better. Or at least a hint that when using format_number or format_date, some functions in qgis do not work as expected.

**Comment by gioman** [comment]
> Now it does work as expected.

@dingausmwald I edited the title.

**Comment by elpaso** [comment]
`format_date` and `format_number` are locale-aware.

Works fine here on master:

```python
In [30]: print(QgsExpression('format_number(1234567, 3, \'fr\')').evaluate())
1 234 567,000
In [36]: QgsExpression('format_number(1234567, 3, \'C\')').evaluate()
Out[36]: '1,234,567.000'
In [32]: QgsExpression('format_date(@d, \'d MMMM yyyy\',\'fr\')').evaluate(ctx)
Out[32]: '12 janvier 2022'
In [34]: QgsExpression('format_date(@d, \'d MMMM yyyy\',\'en\')').evaluate(ctx)
Out[34]: '12 January 2022'
```

**Comment by dingausmwald** [comment]
With windows or linux? Me working with windows 10 x64.
Like said, the calculation works all the way, until the layer (geopackage) is saved, and just for modifying an existing geometry. For newly created this also works as expected.

**Comment by gioman** [comment]
> Like said, the calculation works all the way, until the layer (geopackage) is saved, and just for modifying an existing geometry. For newly created this also works as expected.

Another important detail: it does not not work when settings/general/locale is not EN_us. In this case the locale parameter of `format_date ` does not help.

**Comment by gioman** [comment]
@dingausmwald your fields are numeric, but `format_date` returns a string. If the string happens to represent a decimal number with the "." as separator, then it can be saved into the field, But if the separator is "," it cannot. That is why you see the correct value before saving, but after saving is gone.

**Comment by dingausmwald** [comment]
You mix something up here. In german date format there is still a "." as separator, but the order is different. The similarity i saw here was more the incompatibility to qgis and non en_US encodings.

**Comment by gioman** [comment]
> You mix something up here

@dingausmwald yeah, in my previous comment I meant "format_number". But the bottom line is that the "format" functions return a string, that you usually cannot store into a numeric field. I just tested by changing the locale to de_de and the decimal separator is ",", which cannot be stored in a numeric field, and as a fact that value become 0 upon saving edits.

**Comment by dingausmwald** [comment]
Makes sense. Valid from the developer point of view, a bit irritating for the end user. This is ofc no mager bug, but there seem to be an internal translation when the string matches the numeric format. Maybe this could be adapted to different locale settings, but i can imagine this has nothing to do with qgis itself but python or the file format. Now that I know I use round instead of format_number. Thank you for your work and attention.
