### ISSUE TITLE
Qgis 3.22.1 Crashes and closes without messages

### ISSUE THREAD

**Issue by jorgealmerio** [qgis/QGIS#46389]
### What is the bug or the crash?

Hi all,

When I try to open the attached file with Qgis 3.22.1. It simply closes the Qgis application without any message!
The same file (attached) is easily opened with Qgis 3.18.3.

### Steps to reproduce the issue

1. Open Qgis 3.22.1 Application
2. Open the attached file
[01_Agua_Plancton_0111.zip](https://github.com/qgis/QGIS/files/7662209/01_Agua_Plancton_0111.zip)
.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

Versão do QGIS | 3.22.1-Białowieża | Código da versão do QGIS | 663dcf8fb9
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.4.0
PROJ version | 8.2.0
EPSG Registry database version | v10.038 (2021-10-21)
GEOS version | 3.10.0-CAPI-1.16.0
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
changeDataSource | 3.1
coordinator | 0.4
GroupStats | 2.2.5
plugin_reloader | 0.8.2
qhecras | 0.1
quick_map_services | 0.19.26
QWater | 3.2.0
rivergis | 3.0
SpreadsheetLayers | 2.0.1
uteis | 3.4
grassprovider | 2.12.99
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
@jorgealmerio already fixed (it was a problem with CSVs).

**Comment by jorgealmerio** [comment]
Sorry for the noise!
