### ISSUE TITLE
QGIS ended unexpectedly

### ISSUE THREAD

**Issue by Salvathours** [qgis/QGIS#46388]
### What is the bug or the crash?

Crash ID: a16948419904c9c6675c209e5a8746492570d1e4

Stack Trace

QMimeType::staticMetaObject :
QgsMapCanvas::cancelJobs qgsmapcanvas.cpp:287
QgsMapCanvas::~QgsMapCanvas qgsmapcanvas.cpp:262
QgsMapCanvas::`scalar deleting destructor' :
QgisApp::~QgisApp qgisapp.cpp:1904
QgisApp::`vector deleting destructor' :
main main.cpp:1659
WinMain mainwin.cpp:197
__scrt_common_main_seh exe_common.inl:288
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.23.0-Master
QGIS code revision: 8e46f2ca6a
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.0
Running against GDAL: 3.4.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22000

### Steps to reproduce the issue

Crash ID: a16948419904c9c6675c209e5a8746492570d1e4

Stack Trace

QMimeType::staticMetaObject :
QgsMapCanvas::cancelJobs qgsmapcanvas.cpp:287
QgsMapCanvas::~QgsMapCanvas qgsmapcanvas.cpp:262
QgsMapCanvas::`scalar deleting destructor' :
QgisApp::~QgisApp qgisapp.cpp:1904
QgisApp::`vector deleting destructor' :
main main.cpp:1659
WinMain mainwin.cpp:197
__scrt_common_main_seh exe_common.inl:288
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.23.0-Master
QGIS code revision: 8e46f2ca6a
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.0
Running against GDAL: 3.4.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22000

### Versions

3.22.1

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@Salvathours  steps to replicate? have you tried with a new QGIS profile (and no 3rd party plugins)?

**Comment by Salvathours** [comment]
I see that your name is italian name, is it possible to speek in Italian,
Giovanni?

Il giorno lun 6 dic 2021 alle ore 15:27 Giovanni Manghi <
***@***.***> ha scritto:

**Comment by gioman** [comment]
> I see that your name is italian name, is it possible to speek in Italian, Giovanni?

@Salvathours not here on Github. Feel free to contact me, you can find me in the official QGIS Telegram channel.

**Comment by gioman** [comment]
> Why have 4 versions of Qgis been installed?

@Salvathours because since always each installation of a major version number (3.10, 3.12, etc.) is independent from the others (but they all share the QGIS users/profile folders).

**Comment by Salvathours** [comment]
I don't know, I just wanted to upgrade the previous version. The
osgeo4w-setup.exe installer did everything.
After the installation I found myself with 4 versions installed.
[image: image.png]

Il giorno lun 6 dic 2021 alle ore 17:48 Giovanni Manghi <
***@***.***> ha scritto:

**Comment by gioman** [comment]
> After the installation I found myself with 4 versions installed.

@Salvathours because if you select all packages in the osgeo4w installer you get exactly that. Current, LTR, dev and  ltr-dev.

**Comment by Salvathours** [comment]
I thought the installation of all packages referred to the new version.
Anyway, I uninstall everything and try again to install version 3.22.1 only.
Thank you very much Giovanni.

Il giorno lun 6 dic 2021 alle ore 17:58 Giovanni Manghi <
***@***.***> ha scritto:
