### ISSUE TITLE
Measurement Window does not close after usage

### ISSUE THREAD

**Issue by friedpa** [qgis/QGIS#46386]
### What is the bug or the crash?

I am using the measurement tool under "Ansicht",  but after I took the measurement the window cannot be closed anymore.

### Steps to reproduce the issue

1. Goto: "Ansicht" (English "View")
2. Goto: "Messen" (English "Measure")
3. perform the measurement
4. Press ESC
5. Try to close window 

### Versions

QGIS-Version | 3.22.1-Białowieża | QGIS-Codeversion | 663dcf8fb9
Qt-Version | 5.15.2
Python-Version | 3.9.2
GDAL-Version | 3.2.2
PROJ-Version | 7.2.1
EPSG-Registraturdatenbankversion | v10.008 (2020-12-16)
GEOS-Version | 3.9.0-CAPI-1.16.2
SQLite-Version | 3.34.1
PDAL-Versio | 2.2.0
PostgreSQL-Client-Version | 13.4 (Debian 13.4-0+deb11u1)
SpatiaLite-Version | 5.0.1
QWT-Version | 6.1.4
QScintilla2-Version | 2.11.6
BS-Version | Debian GNU/Linux 11 (bullseye)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
> * Goto: "Ansicht"
> 
> * Goto: "Mssen"


@friedpa that in English is?

**Comment by friedpa** [comment]
"Ansicht" -> "View"
"Messen" -> "Measure"

**Comment by gioman** [comment]
> "Ansicht" -> "View"
> "Messen" -> "Measure"

@friedpa ok thanks. But I cannot replicate here. Please try with a new QGIS profile (no 3rd party plugins installed). If the problem persist then attach a minimal/sample project + data that we can use to replicate the problem.
