### ISSUE TITLE
QHis hangs opening attribute table of WFS layer

### ISSUE THREAD

**Issue by Bregtje77** [qgis/QGIS#46390]
## User Feedback

i just had a layer of earth (WMS) with some layers over it (WFS), then favorite the zoomed section, then tried making a new spatial layer but canceled it, sinds then selected layers won't show (rad line on top with warning), deleted that. Wanted to ad another layer and than uh-oh! 

What is it i do wrong, it happens several times, dit remove the whole package, and downloaded it again to start fresh. But it still occures.

## Report Details

**Crash ID**: [e9788c823f86a2837c76456bc830b8845bec7735](https://github.com/qgis/QGIS/search?q=e9788c823f86a2837c76456bc830b8845bec7735&type=Issues)

**Stack Trace**
<pre>
QMutex::lock :
multipleProviderMetadataFactory :
QObject::qt_static_metacall :
QgsNetworkAccessManager::sslErrorsOccurred :
QgsNetworkAccessManager::onReplySslErrors :
QObject::qt_static_metacall :
QNetworkReply::sslErrors :
QTcpServer::proxy :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
QEventDispatcherWin32::processEvents :
QEventLoop::exec :
multipleProviderMetadataFactory :
multipleProviderMetadataFactory :
multipleProviderMetadataFactory :
multipleProviderMetadataFactory :
multipleProviderMetadataFactory :
QgsDataItem::runCreateChildren :
QgsDataItem::runCreateChildren :
QgsDataItem::removeChildItem :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.20.3-Odense
QGIS code revision: 495fbaec
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.1
Running against GDAL: 3.3.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

Well, that i quess is the whole story

### Steps to reproduce the issue

started on an empty plate. 
got the latst google earth in WMS. 
Clicked on that so i had a background.
Got a new layer with the borders of the county's (provincies).
found on the internet a bag of data from within the selected area. (trusted normal site, government).
downloaded that bag to qgis, as wfs. 
added some of the data to my template. Worked just fine.
Then i got to zoom into a specific area, and safed ones i found it, it to favorite place.
I played a bit with measuring the m2's of the area. Did'nt see how i could safe that. 
I tried to make that selection work using new layer spatial and vector but did not see how it works. 
Then i zoomed out a little and clicked away some useless layers from the bag with several theme's of the surrounding. 
And then to me out of the blue all layers won't load becouse of wrong witdh and hight i think, can not realy read what's in the red line with warning that apears. 
And then i quess i downloaded an other bag of info as wfs, and than suddenly, when i choose one, it crashes.

### Versions

The latest long term version as far as i know

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

Started with an empty desktop, with plenty of space. So i don't think it remembers me from previous atempts, which i had but on an other device

**Comment by gioman** [comment]
> QGIS Version: 3.20.3-Odense

@Bregtje77 too old, update to 3.22.1 and try with a new QGIS profile (no 3rd party plugins installed).

**Comment by Bregtje77** [comment]
Thank you Gioman, i go try to find that version. 
Do i have to remove all former installation of qgis before that?

**Comment by gioman** [comment]
> Do i have to remove all former installation of qgis before that?

Not necessarily. But still please test on a new QGIS profile (if just the update does not solve).

**Comment by Bregtje77** [comment]
I must say, i don't understand what you mean by QGis profile.. I do not log in, think it's only the computer it remembers of recognises?

**Comment by gioman** [comment]
> I must say, i don't understand what you mean by QGis profile.. I do not log in, think it's only the computer it remembers of recognises?

@Bregtje77 settings > user profiles > new profile

**Comment by Bregtje77** [comment]
downloading the 3.2.2.1 version now

**Comment by gioman** [comment]
It is 3.22.1 not 3.2.2

**Comment by Bregtje77** [comment]
yes sorry, typed that wrong. 3.22.1 is installing. Thank you

**Comment by Bregtje77** [comment]
tomorrow evening i try this version, if it happens again i will come back here. 
If not i will tell that too.

**Comment by Bregtje77** [comment]
thank you for helping.

**Comment by Bregtje77** [comment]
there i am again, next try. 
Loading an quite heavy layer results in QGIS (no reaction) little blue circle in stead of mouse. 
I quess i better ask my brother to take a look at this. It's like the computer can't compare with needed speed i quess.

**Comment by gioman** [comment]
> Loading an quite heavy layer results in QGIS (no reaction) little blue circle in stead of mouse.

@Bregtje77 can you provide a clear series of steps to replicate the issue (attaching a sample project/data if necessary)?

**Comment by Bregtje77** [comment]
Wish i could copy the log, but won't work as it has crashed. Today, the only things i do to make it crash: 

Click on map QGIS 3.22.1
Choose QGIS Desktop 3.22.1
Click on 'new project'.
Select panel browser
select panel layers
choose a background layer WMS card of the Netherlands, Google Earth compatible (befor i selected several other cards, same story)
It loads well, i can zoom in and out without problems.
Then i select a databundle from a bigger bundle from government open data service that's added to my browser
It loads well, no problems, can also zoom in and out.
Then i right click to see the 'attribute table (want to select some and not show all).
That won't show, in stead it crashes. 

Don that twice now. Waiting won't help, it don't stop crashing. 
So i click it away. 
When i check the log when i start again, it shows nothing.. 
If it did i could copy paste it and show it. 

I got an empty and strong desktop, got that to run QGIS in stead of my old laptop. 
I realy do not understand what goes wrong....

**Comment by pixelbart80** [comment]
Hi, I'm Bregtje's brother who happens to be a (C#/.Net) developer but knows nothing about GIS software. I just looked into the problem, this is the shortest repro:
1. Add WFS dataset from https://geoportaal.fryslan.nl/arcgis/services/ProvinciaalGeoRegister/PGR2/MapServer/WFSServer
2. Add a layer, for example 'Dijken'
3. Right click, Open Attribute Table
4. QGIS hangs

I could reproduce it on her computer (Mac Mini 2012, i7, integrated graphics, 16GB, Win10 Pro NL) but it works fine on my box (AMD Ryzen 5 3600, 48GB, Radeon Pro WX3100, Win10 Pro EN)

If I have time, I'll try to either reproduce it on my box or try to debug it on her machine. I have some time off during the holidays, maybe I can find time to look into it a bit more.

**Comment by gioman** [comment]
> * Add WFS dataset from https://geoportaal.fryslan.nl/arcgis/services/ProvinciaalGeoRegister/PGR2/MapServer/WFSServer
> 
> * Add a layer, for example 'Dijken'
>
> * Right click, Open Attribute Table
> 
> * QGIS hangs



@pixelbart80 cannot replicate on 3 different OSes. Probably a local issue.

**Comment by Bregtje77** [comment]
Made new profile, did not know how to but saw it while brother was hoovering (helping from distance)over it yesterday!
So new profile, old databases gone, added some new databases. Looks like it's okay now. Maybe it had to do with a databundle having uncertificated ehm, something. I ignored the warning, think there may have been a problem. 
And not having the right version of QGIS.
It looks like everything is fine now!

Very much thanks for your help!
