### ISSUE TITLE
Crashes when shutting down.

### ISSUE THREAD

**Issue by phire-1solutions** [qgis/QGIS#46391]
### What is the bug or the crash?

when I shut down, the applications terminates in an abnormal manner.

## User Feedback

when clkosing the application, this always happens.

## Report Details

**Crash ID**: [2bba35ac54ec3f66db08369439704d5a7beb5523](https://github.com/qgis/QGIS/search?q=2bba35ac54ec3f66db08369439704d5a7beb5523&type=Issues)

**Stack Trace**
<pre>
GDALDestroyDriver :
dal::GDALRasterDriver::deregisterGDALDrivers :
dal::Client::~Client :
calc::DataStorageId::setId :
<lambda_f03950bc5685219e0bcd2087efbe011e>::operator() :
__crt_seh_guarded_call<int>::operator()<<lambda_7777bce6b2f8c936911f934f8298dc43>,<lambda_f03950bc5685219e0bcd2087efbe011e> &,<lambda_3883c3dff614d5e0c5f61bb1ac94921c> > :
execute_onexit_table :
calc::vs2CsfVs :
calc::vs2CsfVs :
LdrpCallInitRoutine :
LdrShutdownProcess :
RtlExitUserProcess :
ExitProcessImplementation :
exit_or_terminate_process :
common_exit :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.20.2-Odense
QGIS code revision: 9f59a156
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.1
Running against GDAL: 3.3.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

OS Name	Microsoft Windows 10 Pro
Version	10.0.19043 Build 19043
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	PH1S-01
System Manufacturer	ASUS
System Model	System Product Name
System Type	x64-based PC
System SKU	SKU
Processor	11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz, 3504 Mhz, 8 Core(s), 16 Logical Processor(s)
BIOS Version/Date	American Megatrends Inc. 0605, 11/03/2021
SMBIOS Version	3.3
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	ASUSTeK COMPUTER INC.
BaseBoard Product	ROG MAXIMUS XIII EXTREME GLACIAL
BaseBoard Version	Rev 1.xx
Platform Role	Desktop
Secure Boot State	Off
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\Windows
System Directory	C:\Windows\system32
Boot Device	\Device\HarddiskVolume1
Locale	United States
Hardware Abstraction Layer	Version = "10.0.19041.1151"

Time Zone	AUS Eastern Daylight Time
Installed Physical Memory (RAM)	128 GB
Total Physical Memory	128 GB
Available Physical Memory	78.8 GB
Total Virtual Memory	199 GB
Available Virtual Memory	131 GB
Page File Space	70.8 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	Off
Virtualization-based security	Not enabled
Device Encryption Support	Elevation Required to View
Hyper-V - VM Monitor Mode Extensions	Yes
Hyper-V - Second Level Address Translation Extensions	Yes
Hyper-V - Virtualization Enabled in Firmware	No
Hyper-V - Data Execution Protection	Yes

### Steps to reproduce the issue

I just have to shut the application down and it dies.

### Versions

QGIS version
3.20.2-Odense
QGIS code revision
9f59a156
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.1
PROJ version
8.1.0
EPSG Registry database version
v10.027 (2021-06-17)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
AusMap
autoSaver
AzimuthDistanceCalculator
Coordtransform
ee_plugin
LAStools
latlontools
mgrs
pcraster_tools
pointsamplingtool
QuickOSM
rvt-qgis
ViewshedAnalysis
db_manager
MetaSearch
processing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
Known issue with the pcraster tools plugin -- see https://github.com/jvdkwast/qgis-processing-pcraster/issues/35
