### ISSUE TITLE
GDAL Translate not respecting -a_srs for TFW files

### ISSUE THREAD

**Issue by Saijin-Naib** [qgis/QGIS#46417]
### What is the bug or the crash?

Choose Translate, set a different SRS as the override AND/OR ``-a_srs EPSG:4326`` in Additional command-line parameters, and the generated TFW will have coordinates in the layer's original SRS.

### Steps to reproduce the issue

1. Run Translate from Processing Toolbox
2. Setup Override CRS as EPSG:4326
3. Add ``-co TFW=YES`` to additional command-line parameters
4. Observe that TFW CRS is input layer's original CRS (in this case, EPSG:32615
5. Add ``-a_srs EPSG:4326`` to additional command-line parameters
6. Observer that the new TFW is still in the wrong SRS

QGIS History Item
```
"""
Double-click on the history item or paste the command below to re-run the algorithm
"""

processing.run("gdal:translate", {'INPUT':'C:/Users/USERNAME/AppData/Local/Temp/processing_BxRQJM/6516c5016b0d4816a6bcb0cbdabd618a/OUTPUT.tif','TARGET_CRS':QgsCoordinateReferenceSystem('EPSG:4326'),'NODATA':None,'COPY_SUBDATASETS':False,'OPTIONS':'','EXTRA':'-co TFW=YES -a_srs EPSG:4326','DATA_TYPE':0,'OUTPUT':'TEMPORARY_OUTPUT'})
```

### Versions

QGIS version
3.22.1-Białowieża
QGIS code revision
663dcf8fb9
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.0
PROJ version
8.2.0
EPSG Registry database version
v10.038 (2021-10-21)
GEOS version
3.10.0-CAPI-1.16.0
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
CalculateGeometry
0.6.4
cartography_tools
1.2.1
ImportPhotos
3.0.3
kmltools
3.1.15
LAStools
1.4
loadthemall
3.3.0
MemoryLayerSaver
4.0.4
pdaltools-master
0.1.5
photo2shape
3.0
processing_fusion
3.0
Projestions
1.0.1
qgis-maptiler-plugin
2.0.0
qgis2web
3.16.0
qgissprp
0.5.0
slyr
3.18.0
zoom_level
0.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

![image](https://user-images.githubusercontent.com/19295950/145323317-c5d30bdd-35df-4a1c-a4f8-e018181715cf.png)

Thread exploring this in usage:  
https://community.opendronemap.org/t/is-there-a-way-to-produce-world-and-projection-files/9771/14?u=saijin_naib

**Comment by agiudiceandrea** [comment]
@Saijin-Naib have you read the gdal_translate documentation at https://gdal.org/programs/gdal_translate.html#cmdoption-gdal_translate-a_srs?

It states that "no reprojection is done":

> -a_srs <srs_def>
> Override the projection for the output file.
> 
> The coordinate reference systems that can be passed are anything supported by the OGRSpatialReference.SetFromUserInput() call, which includes EPSG Projected, Geographic or Compound CRS (i.e. EPSG:4296), a well known text (WKT) CRS definition, PROJ.4 declarations, or the name of a .prj file containing a WKT CRS definition.
> 
> Note
> 
> No reprojection is done.

Anyway, I think this issue is about the GDAL library.

**Comment by gioman** [comment]
> Observer that the new TFW is still in the wrong SRS

@Saijin-Naib not sure, but I would not expect to have the world file updated (if the input is a geotiff).

**Comment by Saijin-Naib** [comment]
Hmm, so do you both think the proper flow would be Warp with -co TFW=YES to get a different export CRS in the TFW?

**Comment by gioman** [comment]
> Hmm, so do you both think the proper flow would be Warp with -co TFW=YES to get a different export CRS in the TFW?

Possibly yes.

**Comment by Saijin-Naib** [comment]
Yep, your workflow works Giorgio.

I still feel like Translate should spit out the TFW in the CRS I choose, but I'm likely not understating the history behind the syntax of how it works.
