### ISSUE TITLE
An example on how to change the size of the layout or automatically resize the layout pyqgis as standalone.

### ISSUE THREAD

**Issue by CodingLappen** [qgis/QGIS#46413]
### What is the issue about the documentation?

Hello, 

I ran into an issue about the PyQgis or even maybe the C++ Documentation. 
I wanted to render a picture of small highlighted in Germany and wanted to add Labels to the
small regions on it. So the graphical version of qgis you can resolve the issue by scaling the layout and
map up. That feature is either not directly available or not available at all. 
Can somebody help me out on this?

**Comment by gioman** [comment]
@CodingLappen is this a feature request? a bug report? a request of support?

**Comment by CodingLappen** [comment]
I don't actually know tbh.
