### ISSUE TITLE
Image cut off at bottom when exporting large image

### ISSUE THREAD

**Issue by NickVaughn** [qgis/QGIS#46416]
### What is the bug or the crash?

When exporting a very large image (10416 x 41664) from a map layout, the bottom ~ 1/5th of the image is cut-off (as in no values are written).

### Steps to reproduce the issue

1. Create layout with custom size (24 x 96 inches) with a specified dpi of 424 (this is probably too specific, I think it just has to be above a certain number of pixels).
2. asdf
3. Read dialog box saying "To create an image of 10416x41664 requires about 1301 MB of memory. Proceed?"
4. Check available memory and see that more than 80 Gb of memory are available on the machine.  Click OK. Set image file name, then keep specified dpi, width and height.
5. Wait a minute and see that layout was "Successfully exported".
6. Check image in image viewer, and get disappointed that bottom of image is blank. Check in a couple other image viewers and see the same thing (either all black at bottom or just transparent). Bang head on desk.
7. Give up and reduce the dpi to 325. Try again.
8. Be somewhat happy that at least there is a whole image, even if it is not the resolution you were hoping for.

### Versions

Both QGIS 3.16.14 and 3.22.0.
Windows Server 2016 v1809 build 17763.2237.

Here's the About dialog text for 3.22.0:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
QGIS version
3.22.0-Białowieża
QGIS code revision
d9022691f1
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.0
PROJ version
8.2.0
EPSG Registry database version
v10.038 (2021-10-21)
GEOS version
3.10.0-CAPI-1.16.0
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows Server 2016 Version 1809




Active Python plugins
autoSaver
2.4
BezierEditing
version 1.3.1
coordinate_capture
0.2
ee_plugin
0.0.4
plaingeometryeditor
3.0.0
planet_explorer
2.0.0
profiletool
4.1.8
QGIS3-getWKT
1.4
QuickWKT
3.1
quick_map_services
0.19.11.1
spectral_libraries
1.1.3
temporalprofiletool
2.0.3
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99


### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

_No response_

**Comment by gioman** [comment]
@NickVaughn the data missing, it comes from an external/remote service like a WMS, or is a local layer?

**Comment by roya0045** [comment]
Related to #41045, should be closed imo.

**Comment by gioman** [comment]
Agree, closing as duplicate.

**Comment by NickVaughn** [comment]
Yeah, sorry. Definitely a duplicate. I looked but couldn't find an existing bug. Probably just didn't use the right keywords.
