### ISSUE TITLE
TypeError: unable to convert a Python 'QgsVectorLayer' object to a C++ 'QgsVectorLayer*' instance

### ISSUE THREAD

**Issue by sweco-sedalh** [qgis/QGIS#46420]
### What is the bug or the crash?

In a PyQGIS toolbox script I sometimes (around half to one third of runs) get the following error (first row provided for context):

```
Results: {'OUTPUT': 'Remaining_fields_d9650de6_fcef_43a4_92a4_227261f8dda8'}
TypeError: unable to convert a Python 'QgsVectorLayer' object to a C++ 'QgsVectorLayer*' instance

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "A:\30034460-Elfiskeregistret\execute.py", line 140, in processAlgorithm
processed = self._processJoinByLocations(base, processed, context, feedback)
File "A:\30034460-Elfiskeregistret\execute.py", line 295, in _processJoinByLocations
processed = processing.run("native:joinbynearest", dict(
File "C:\OSGeo4W/apps/qgis/./python/plugins\processing\tools\general.py", line 108, in run
return Processing.runAlgorithm(algOrName, parameters, onFinish, feedback, context)
File "C:\OSGeo4W/apps/qgis/./python/plugins\processing\core\Processing.py", line 158, in runAlgorithm
if not alg.validateInputCrs(parameters, context):
SystemError: <built-in method validateInputCrs of QgsProcessingAlgorithm object at 0x000001F3D9A32550> returned a result with an error set

Execution failed after 6.95 seconds
```

While happening very regularly it's not 100% reproducible, and when running the script standalone (using the "harness" below) it hasn't happened at all yet, only when ran in the full QGIS from the processing toolbox. This, combined with a semi-reproducible crash for which I'll open a separate issue, has also made it basically impossible to produce a minimal reproducible sample.

Based on the error it seems that the error is in the Python/C++ (SIP?) layer, though I don't know enough about SIP to be able to tell why it can't perform the conversion which it quite obviously should be able to.

<details>
<summary>Harness for standalone</summary>

```python
if __name__ == '__main__':
    class MyFeedBack(QgsProcessingFeedback):
        def setProgressText(self, text):
            print(text)

        def pushInfo(self, info):
            print(info)

        def pushCommandInfo(self, info):
            print(info)

        def pushDebugInfo(self, info):
            print(info)

        def pushConsoleInfo(self, info):
            print(info)

        def reportError(self, error, fatalError=False):
            print(error)

    QgsApplication.setPrefixPath('C:/OSGEO4~1/apps/qgis')
    qgs = QgsApplication([], False)
    qgs.initQgis()
    try:
        Processing.initialize()

        print(Processing.runAlgorithm(ElfiskeExecute(), dict(
            ...parameters...
        ), feedback=MyFeedBack()))
    finally:
        qgs.exitQgis()
```

</details>

The code at the error (the last `Results:` line before the error in the log above is for the `native:deletecolumn` algorithm, so the issue is with the `native:joinbynearest` algorithm):

```python
        processed = processing.run("native:deletecolumn", dict(
            INPUT=processed,
            COLUMN=["lan_LANKOD", "kommuner_KOM_NAMN", "kommuner_ID",
                    "lufttemperatur_med_PK51RN_ID", "lufttemperatur_jan_INTERVALL", "lufttemperatur_jul_INTERVALL",
                    "avrinning_INTERVALL", "nederbord_INTERVALL", "bergart_typområde",
                    "biogeoregioner_Bioreg", "fire12_Region", "limnekoreg_ekoreg", "limnvtyp_ekoreg",
                    "svar_haro_HARO", "svar_aro_AROID"],
            OUTPUT='TEMPORARY_OUTPUT'
        ), context=context, feedback=feedback)["OUTPUT"]

        processed = processing.run("native:joinbynearest", dict(
            INPUT=processed,
            INPUT_2=base + '|layername=svar_linjer',
            FIELDS_TO_COPY=["UUID", "MS_CD", "EU_CD", "VISS_MS_CD", "VERSION", "URL_VISS"],
            DISCARD_NONMATCHING=False,
            PREFIX='',
            NEIGHBORS=1,
            MAX_DISTANCE=None,
            OUTPUT='TEMPORARY_OUTPUT'
        ), context=context, feedback=feedback)["OUTPUT"]
```

Where `processed` is the output from a previous algorithm (`native:fieldcalculator` to be exact) and `base` is the filename of a GeoPackage. I have verified that both of these have the expected type and value before the call to `native:joinbynearest`.

### Steps to reproduce the issue

As mentioned, I have tried to produce a minimal reproducible example but because of the randomness in the errors it's basically impossible.

### Versions

QGIS version
3.22.1-Białowieża
QGIS code revision
663dcf8fb9
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.0
PROJ version
8.2.0
EPSG Registry database version
v10.038 (2021-10-21)
GEOS version
3.10.0-CAPI-1.16.0
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 1909

Active Python plugins
firstaid
2.1.5
processing_wbt
1.3.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
@sweco-sedalh why this should be a QGIS bug rather than a problem in your script?

**Comment by sweco-sedalh** [comment]
@gioman Because I'm just passing in what QGIS gives me from one native processing algorithm to another. So either the first one (`native:deletecolumn`) has the wrong return value, or the second (`native:joinbynearest`) doesn't handle it's input values correctly.

If this usage (`OUTPUT` of one algorithm to the `INPUT` of another) is incorrect I'd be happy to be corrected and shown the right way.

Furthermore, since it works some runs (without any changes in my script) I reason that there must be a difference in QGIS's state between runs.

**Comment by gioman** [comment]
@sweco-sedalh can you please attach your script?

**Comment by sweco-sedalh** [comment]
@gioman https://gist.github.com/sweco-sedalh/1da7de6072ef0a74fe9b3bfdd46d4a0d

I can't really share the data in the open (because of licensing restrictions), but I could send (an excerpt of) it to you privately if needed.

**Comment by alexbruy** [comment]
It is definitely not a QGIS bug, but issue in your code. You have to set `is_child_algorithm=True` in script steps.

**Comment by sweco-sedalh** [comment]
@alexbruy I see, never seen that parameter before, what does it do?
