### ISSUE TITLE
Crash in QgsProcessingAlgorithm::checkParameterValues

### ISSUE THREAD

**Issue by sweco-sedalh** [qgis/QGIS#46421]
### What is the bug or the crash?

```
Crash ID: f738d6a9c29c091f6d4d59196b62907e088a2876


Stack Trace


QgsProcessingAlgorithm::checkParameterValues qgsprocessingalgorithm.cpp:103
PyInit__core :
PyArg_ParseTuple_SizeT :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyFunction_Vectorcall :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyFunction_Vectorcall :
PyEval_EvalFrameDefault :
PyEval_EvalFrameDefault :
PyFunction_Vectorcall :
PyFloat_FromDouble :
PyVectorcall_Call :
PyObject_Call :
PyInit__core :
QgsProcessingAlgorithm::runPrepared qgsprocessingalgorithm.cpp:533
QgsProcessingAlgRunnerTask::run qgsprocessingalgrunnertask.cpp:66
PyInit__core :
QgsTask::start qgstaskmanager.cpp:81
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.22.1-Bia?owie?a
QGIS code revision: 663dcf8fb9
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.0
Running against GDAL: 3.4.0



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363
```

The crash seems to be on [this](https://github.com/qgis/QGIS/blob/final-3_22_1/src/core/processing/qgsprocessingalgorithm.cpp#L103) line. Provided that the stacktrace is correct the only reason I can see for a crash on that specific line would be `def` being null (thus triggering a segfault), but can that really be the case?

### Steps to reproduce the issue

Sometimes (around one third of runs) the above crash will happen at some point in this loop in my script:

```python
        for name, expression, type, length in (
                ('LAN', '\"lan_LANKOD\"', 2, 2),
                ('KOMMUN', '\"kommuner_KOM_NAMN\"', 2, 50),
                ('KOMMUNNR', '\"kommuner_ID\"', 2, 4),
                ('MEDTEMPAR', '\"lufttemperatur_med_PK51RN_ID\"', 1, 0),
                ('MEDTJAN', '\"lufttemperatur_jan_INTERVALL\"', 2, 12),
                ('MEDTJULI', '\"lufttemperatur_jul_INTERVALL\"', 2, 12),
                ('AVRINNING', '\"avrinning_INTERVALL\"', 2, 12),
                ('NEDERBORD', '\"nederbord_INTERVALL\"', 2, 12),
                ('TYPOMRADE', '\"bergart_typområde\"', 2, 50),
                ('HK', 'if(\"bergart_typområde\" IN (\'Fjällkedjan, ö HK\', \'Sedimentär berggrund, Jämtland, ö HK\', \'Sydsvenska höglandet, ö HK\', \'Urberggsomr inom Norrlandsterräng, ö HK\'), 1, 0)', 1, 0),
                ('GEOLOGICAL', 'if(\"bergart_typområde\" IN (\'Fjällkedjan, ö HK\', \'Mellansvenska sänkan, u HK\', \'Norrlandskustens urberg, u HK\', \'Sydsvenska höglandet, ö HK\', \'Urberggsomr inom Norrlandsterräng, ö HK\', \'Väst- och sydostkusten, u HK\'), \'Siliceous\', \'Calcareous\')', 2, 12),
                ('BIOREG', '\"biogeoregioner_Bioreg\"', 2, 10),
                ('FIRE12', '\"fire12_Region\"', 0, 0),
                ('LIMNEKOREG', '\"limnekoreg_ekoreg\"', 1, 0),
                ('LIMNVTYPREG', '\"limnvtyp_ekoreg\"', 1, 0),
                ('HAROID', '\"svar_haro_HARO\"', 1, 0),
                ('AROID', '\"svar_aro_AROID\"', 2, 13)
        ):
            processed = processing.run("native:fieldcalculator", dict(
                INPUT=processed,
                FIELD_NAME=name, FORMULA=expression,
                FIELD_TYPE=type, FIELD_LENGTH=length, FIELD_PRECISION=0,
                OUTPUT='TEMPORARY_OUTPUT'
            ), context=context, feedback=feedback)["OUTPUT"]
```

Where `processed` is the `OUTPUT` of `native:joinattributesbylocation` which (also in a loop) adds all the layers used by the expressions here.

The other two thirds of times this works fine and the script either completes successfully or I hit my other bug (#46420).

### Versions

QGIS version
3.22.1-Białowieża
QGIS code revision
663dcf8fb9
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.0
PROJ version
8.2.0
EPSG Registry database version
v10.038 (2021-10-21)
GEOS version
3.10.0-CAPI-1.16.0
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 1909

Active Python plugins
firstaid
2.1.5
processing_wbt
1.3.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
@sweco-sedalh please attach your script.

**Comment by sweco-sedalh** [comment]
@gioman https://gist.github.com/sweco-sedalh/1da7de6072ef0a74fe9b3bfdd46d4a0d

I can't really share the data in the open (because of licensing restrictions), but I could send (an excerpt of) it to you privately if needed.

**Comment by elpaso** [comment]
If you attach a self-contained test script and data to this issue, the chances of a developer having a look will increase dramatically.

**Comment by impiaaa** [comment]
I'm also getting a crash in `checkParameterValues` when calling `processing.run`, though I'm using a different processing algorithm (dissolve), and the input layer I'm giving it is a materialized layer rather than an output layer. The script is [here](https://github.com/impiaaa/SV-OSM/blob/9d2437750d3e41e8a0d70fd7f160fec8afa199f3/ohm/datedissolve.py) and the data is [here](https://hub.arcgis.com/datasets/MROSD::mrosd-land/). I haven't tried creating a minimal test case, partly because the last version of the script worked fine (even though it also passed a materialized layer to `processing.run`). QGIS version is 3.22.4-Białowieża.
