### ISSUE TITLE
Crash while working on Layouts

### ISSUE THREAD

**Issue by EnkiKudo** [qgis/QGIS#46434]
### What is the bug or the crash?

I'm working on Layouts for an Project and it happens from time to time while i delete some old text or Lines/Arrows, that QGIS just crashes with the following Crashreport.

```
Crash ID: 7585f550144e873eeef72adb09e0324315dd27f6


Stack Trace


QGraphicsItem::dragMoveEvent :
QGraphicsEffectSource::draw :
QgsLayoutEffect::draw :
QGraphicsScene::drawItems :
QGraphicsScene::drawItems :
QGraphicsView::paintEvent :
QgsLayoutView::paintEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QApplication::windowIcon :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
QGraphicsScene::~QGraphicsScene :
QObject::event :
QGraphicsScene::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.16.4-Hannover
QGIS code revision: 654e76b3cb
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043
```

This keeps happening since the last 3 LTR Versions. Even tried a fresh installation. 

### Steps to reproduce the issue

Mostly happens when i duplicate an Layout and than begin to delete things i don't need for the new one, but also if i make new Layouts und just throw some textes and arrows in there and than deleting them. (tried it out to see if it has something to do with the duplicated Layout or not)

### Versions

3.16.4
3.10 and i don't know what we had befor that. (My Administartor also doesn't know anymore)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
> 3.16.4
> 3.10

@EnkiKudo they are both too old and unsupported. You must try on 3.16.14 or 3.22.1, with a new QGIS profile (and no 3rd party plugins installed).

**Comment by EnkiKudo** [comment]
> > 3.16.4
> > 3.10
> 
> @EnkiKudo they are both too old and unsupported. You must try on 3.16.14 or 3.22.1, with a new QGIS profile (and no 3rd party plugins installed).

I asked my Administrator and he said, that we can only install the LTS wich our main Office approved on, so thats it for 3.22.1 for now. but when i look into the dokumentation it says that all 3.16 are LTS. not only the subversion 14 but also 4.

**Comment by gioman** [comment]
@EnkiKudo 3.16 is the LTR, but you must stay up to date with point releases, and now we are at 3.16.14 as previous releases don't have the latest bug fixes and they will never get them.

**Comment by EnkiKudo** [comment]
I understand that but the problem is that i am working in an State Office and our Head Admins get thier orders from the Ministry. I can't say them what to to and as long as the Mimistry doesn't say we should get a newer Version i am stuck on this. I will try it out when i am at Home with the 3.22.1 and tell you if it still crashes if i do this but that is all i can do. so it would be nice if someone could help me with it even thought i am using the 3.16.4. Or at least the ones that are responsible for the QGIS Website that they should write more then Long therm lelease (most stable) 3.16. Because the Head Admins look after that and not in the fineprint(even thought it is on top of the same page....)

**Comment by gioman** [comment]
> i am at Home with the 3.22.1

you can also test 3.16.14 and see if there is any difference. Do it with a new QGIS profile.
