### ISSUE TITLE
Virtual layer data source gets lost when saved with a Filter

### ISSUE THREAD

**Issue by T3xtM4rk3r** [qgis/QGIS#46437]
### What is the bug or the crash?

Hi everyone,

I'm having some troubles when working with virtual layers. 

When a Filter is set to a virtual layer, the data source of the virtual layer seems to be missing after reopening the project file.

### Steps to reproduce the issue

[vrt_test.zip](https://github.com/qgis/QGIS/files/7692062/vrt_test.zip)

- download the zip file containing a geopackage with a project file, a point layer and a table
- open project vrt_test_project from vrt_test.gpkg, two out of three points should be visible 
- Set a Filter on the virtual_layer using "ID" = 'P2' and one points remains

![grafik](https://user-images.githubusercontent.com/92782306/145561391-98073c77-ac19-48c9-9530-e99a0a523f1f.png)

- save the project, close the project, open the project again
- the virtual layer is not availlable any more

![grafik](https://user-images.githubusercontent.com/92782306/145561239-3bfe19e4-97ff-4c39-b6d7-363b4aa5b4a7.png)

I could not test the behaviour under qgis 3.22.1  because of the virtual layer provider bug mentioned here https://github.com/qgis/QGIS/issues/46116
 
![grafik](https://user-images.githubusercontent.com/92782306/145560394-e3582943-800e-4bd8-83c8-26ed544e612b.png)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS-Version | 3.16.14-Hannover | QGIS-Codeversion | 42791986
-- | -- | -- | --
Kompiliert gegen Qt | 5.15.2 | Laufendes Qt | 5.15.2
Kompiliert mit GDAL/OGR | 3.4.0 | Läuft mit GDAL/OGR | 3.4.0
Kompiliert mit GEOS | 3.10.0-CAPI-1.16.0 | Läuft mit GEOS | 3.10.0-CAPI-1.16.0
Kompiliert mit SQLite | 3.35.2 | Läuft mit SQLite | 3.35.2
PostgreSQL-Client-Version | 13.0 | SpatiaLite-Version | 5.0.1
QWT-Version | 6.1.3 | QScintilla2-Version | 2.11.5
Kompiliert mit PROJ | 8.2.0 | Läuft mit PROJ | Rel. 8.2.0, November 1st, 2021
BS-Version | Windows 10 Version 2009
Aktive Python-Erweiterungen | db_manager; MetaSearch; processing

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
Confirmed here too.

**Comment by T3xtM4rk3r** [comment]
Hello,

after updating the issue doesn't occur in QGIS 3.22.2 but is still valid for QGIS 3.16.15.

**Comment by gioman** [comment]
> after updating the issue doesn't occur in QGIS 3.22.2 but is still valid for QGIS 3.16.15.

@T3xtM4rk3r the bug is fixed then, is up to the developers choose if the fix can be backported to the LTR release.
