### ISSUE TITLE
QGIS 3.22.1 crushing at start

### ISSUE THREAD

**Issue by pilipr** [qgis/QGIS#46442]
### What is the bug or the crash?

Crash ID: 157e2f86c7fdd1361989be12298a29553dcacd5e

Stack Trace

QTextCodec::toUnicode :
providerMetadataFactory :
providerMetadataFactory :
providerMetadataFactory :
QgsVectorLayer::setDataProvider :
QgsVectorLayer::readXml :
QgsMapLayer::readLayerXml :
QgsProject::addLayer :
QgsProject::_getMapLayers :
QgsProject::readProjectFile :
QgsProject::read :
QgisApp::addProject :
QgisApp::openProject :
QObject::qt_static_metacall :
QMenu::~QMenu :
QObject::qt_static_metacall :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.22.1-Bia?owie?a
QGIS code revision: 663dcf8fb9
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.0
Running against GDAL: 3.4.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Steps to reproduce the issue

Crash ID: 157e2f86c7fdd1361989be12298a29553dcacd5e

Stack Trace

QTextCodec::toUnicode :
providerMetadataFactory :
providerMetadataFactory :
providerMetadataFactory :
QgsVectorLayer::setDataProvider :
QgsVectorLayer::readXml :
QgsMapLayer::readLayerXml :
QgsProject::addLayer :
QgsProject::_getMapLayers :
QgsProject::readProjectFile :
QgsProject::read :
QgisApp::addProject :
QgisApp::openProject :
QObject::qt_static_metacall :
QMenu::~QMenu :
QObject::qt_static_metacall :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.22.1-Bia?owie?a
QGIS code revision: 663dcf8fb9
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.0
Running against GDAL: 3.4.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Versions

Crash ID: 157e2f86c7fdd1361989be12298a29553dcacd5e

Stack Trace

QTextCodec::toUnicode :
providerMetadataFactory :
providerMetadataFactory :
providerMetadataFactory :
QgsVectorLayer::setDataProvider :
QgsVectorLayer::readXml :
QgsMapLayer::readLayerXml :
QgsProject::addLayer :
QgsProject::_getMapLayers :
QgsProject::readProjectFile :
QgsProject::read :
QgisApp::addProject :
QgisApp::openProject :
QObject::qt_static_metacall :
QMenu::~QMenu :
QObject::qt_static_metacall :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.22.1-Bia?owie?a
QGIS code revision: 663dcf8fb9
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.0
Running against GDAL: 3.4.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@pilipr 

does it crash at opening a project? if yes, does the project have CSV tables in it?
Have you tried with a new QGIS profile»

**Comment by pilipr** [comment]
Thank you for your reply, it surely does have CSV table in it. Never thought about it. Had not tried new profile, that was next logical thing to do. Will try to remove table first.

**Comment by gioman** [comment]
> t surely does have CSV table in it.

@pilipr this was already fixed. you must wait until 3.22.2 for the fix (use 3.16.14 in the meantime).
