### ISSUE TITLE
"Repack failed" when files are on SMB share

### ISSUE THREAD

**Issue by pbridoux** [qgis/QGIS#46456]
### What is the bug or the crash?

Open a .shp from a smb network drive, go to modify mode, separate several entities and save : it fails with the folowing errors

CRITICAL  Layer Montagne_noire: OGR [3] error 1: REPACK of layer 'Montagne_noire' failed.
CRITICAL  Layer Montagne_noire: Cannot reopen data source /...NETDISK.../Montagne_noire.shp in read-only mode

(approximately traduced from french)

### Steps to reproduce the issue

(0. verify that "Enable snapping by default" option is ON)
1. open a .shp from a smb network drive
2. go to modify mode
3. separate several entities
4. save the layer

### Versions

Version de QGIS | 3.18.3-Zürich | Révision du code | 735cc85be9
-- | -- | -- | --
Compilé avec Qt | 5.11.3 | Utilisant Qt | 5.11.3
Compilé avec GDAL/OGR | 2.4.0 | Utilisé avec GDAL/OGR | 2.4.0
Compilé avec GEOS | 3.7.1-CAPI-1.11.1 | Utilisé avec GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compilé avec SQLite | 3.27.2 | Fonctionne avec SQLite | 3.27.2
Compiled against PDAL | 1.8.0 | Running against PDAL | 1.8.0 (git-version: Release)
Version du client PostgreSQL | 11.11 (Debian 11.11-0+deb10u1) | Version de SpatiaLite | 4.3.0a
Version de QWT | 6.1.4 | Version de QScintilla2 | 2.10.4
Compilé avec PROJ | 5.2.0 | Fonctionne avec PROJ | Rel. 5.2.0, September 15th, 2018
Version de l'OS | Debian GNU/Linux 10 (buster)
Extensions Python actives | MetaSearch; db_manager; processing

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Problem is systematically reproduced : on different workstations / same server, on different servers / same workstation, as soon as we change entities and want to save the layer on a network share.

Problem disapears when files are on a local disk. Problem also disapears with a new profile and once this was found, we could investigate and finally relate it to the "Enable snapping by default" option :

Starting QGis with the option ON ... Repack failed systematically (on smb share)
Starting QGis with the option OFF ... save OK (in all cases)

Should I consider the error messages worth of trust ? Investigate in the OGR direction ? Or the Samba one (because of "Cannot reopen ... in read-only mode) ? Or the solution is elsewhere ?

**Comment by gioman** [comment]
> CRITICAL Layer Montagne_noire: Cannot reopen data source /...NETDISK.../Montagne_noire.shp in read-only mode

@pbridoux is your share read/write or read only?

**Comment by pbridoux** [comment]
Yes, the share is read/write. And without the faulty qgis option, user's are absolutly able to write files in it.

**Comment by gioman** [comment]
@pbridoux check if you can change your data with OGR, example

ogrinfo -dialect sqlite -sql "update foo set columnname='bar'" /path/to/foo.shp

**Comment by pbridoux** [comment]
@gioman yes, your command has worked perfectly, my column has been changed, even without closing the layer in qgis.

**Comment by gioman** [comment]
> 3.18.3-Zürich

@pbridoux in the meantime I will try on a smb share, can you also try on a supported version? 3.18 is EOL and unsupported, use 3.16.14 or 3.22.1

**Comment by gioman** [comment]
@pbridoux just tested editing a shapefile on a SMB share on Windows 10 and had no issues whatsoever. QGIS 3.22.1.

**Comment by pbridoux** [comment]
I had the exact same results with Debian 11 and QGis 3.22.1 : works OK when we start qgis with the option OFF, "Repack failed" when we start with the option ON. I was told (not verified myself) that version 3.16 had the trouble too.

Ok for the Windows test, but I really have to find a solution that works with Debian. Thank's...

**Comment by gioman** [comment]
> Ok for the Windows test, but I really have to find a solution that works with Debian. Thank's...

@pbridoux same results on Mint 20.2, starting QGIS with that option ON.

**Comment by pbridoux** [comment]
Installed Mint 20.2 + Qgis 3.22.1. Open smb share. Open layer. Make changes. Save OK.
Activate the option. Close and restart Qgis. Open layer. Make changes. Save : Repack failed. ;((

May be the way I mount my smb share ? Would you please expose your mount line ? Mine is :

//server/share on /home/local_user/share type cifs (rw,nosuid,nodev,relatime,vers=3.1.1,cache=strict,username=domain_user,domain=mydomain,uid=1000,forceuid,gid=1000,forcegid,addr=192.168.1.1,file_mode=0755,dir_mode=0755,soft,nounix,serverino,mapposix,rsize=4194304,wsize=4194304,bsize=1048576,echo_interval=60,actimeo=1,user=local_user)

**Comment by gioman** [comment]
> Installed Mint 20.2 + Qgis 3.22.1. Open smb share. Open layer. Make changes. Save OK.
> Activate the option. Close and restart Qgis. Open layer. Make changes. Save : Repack failed. ;((

@pbridoux followed this steps, still ok here.




> Would you please expose your mount line ?

`sudo mount -t cifs //ip/share ~/smb_share -o uid=***,username=***,password=***`

**Comment by pbridoux** [comment]
Your line is the command to mount the share. I would like to see the result given by `mount | grep share`. Thank's.

**Comment by gioman** [comment]
> I would like to see the result given by `mount | grep share`. Thank's.

@pbridoux 

`//ip/share on /home/username/smb_share type cifs (rw,relatime,vers=2.1,cache=strict,username=***,uid=1000,forceuid,gid=0,noforcegid,addr=IP,file_mode=0755,dir_mode=0755,soft,nounix,serverino,mapposix,rsize=1048576,wsize=1048576,bsize=1048576,echo_interval=60,actimeo=1)`

**Comment by pbridoux** [comment]
Unfortunately, I still have the trouble. I'll inverstigate the share and samba server config... and will be back ;). Thank's.
