### ISSUE TITLE
Unable to use feature geometry in expressions with geometry generator symbol types

### ISSUE THREAD

**Issue by nmoyroud** [qgis/QGIS#46455]
### What is the bug or the crash?

I need to place SVG Marker on centroid of polygons, but i cannot achieve that because of a bug with QGIS expressions in geometry generator symbol types (tested with QGIS 3.16 and QGIS 3.22).

``

### Steps to reproduce the issue

1. load a polygon layer
2. symbol layer type = geometry generator
3. geometry type = Point / MultiPoint
4. expression = centroid($geometry)
5. marker symbol  = SVG Marker
6. Error : I'm unable to use expressions based on feature geometry for the fields values of SVG Marker

For example with :
size width expression = 0.4 * $perimeter
or
rotation expression = main_angle($geometry)

Previews of values are ok in Expression String Builder window but not taken into account in the fields of the SVG Marker.
If I type the same values hardcoded directly into the fields it's ok. But that's not useful for me because I need different sizes / rotation for different features in my layer.
I tested with geometry generator but without changing the type of geometry of my layer and expression values work correctly. But it's not useful for my use case !
I think the problem is caused by the change of geometry type, and maybe QGIS erase the geometry of feature with the one of the new symbol. But in my case it's a problem because $perimeter and main_angle have no meaning in the context of a point.
For me it's a bug because $perimeter, $geometry and all variables linked to geometry should always refer to the geometry of layer features, not the geometry of generated symbols.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.1-Białowieża | QGIS code revision | 663dcf8fb9
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.4.0
PROJ version | 8.2.0
EPSG Registry database version | v10.038 (2021-10-21)
GEOS version | 3.10.0-CAPI-1.16.0
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 1909
  |   |   |  
Active Python plugins
AppendFeaturesToLayer | 1.1.0
db-style-manager | 0.8
latlontools | 3.4.3
lizmap | 3.4.4
mmqgis | 2020.1.16
networks | 2.5.15
nominatim | 1.2.5
nominatim_locator_filter | 0.2.3
numericalDigitize | 0.4.4
ORStools | 1.2.3
pgRoutingLayer | 3.0.0
plugin_reloader | 0.8.2
Qgis2threejs | 2.4.2
qgis2web | 3.15.1
qgis_resource_sharing | 0.16.0
QuickOSM | 2.0.0-beta1
quick_map_services | 0.19.11.1
SRTM-Downloader | 3.1.9
StreetView | 3.2
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.5
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

I know that there is a centroid fill symbol type for this need, but I can't use it because my SVG Markers should be placed on the whole polygon and not only the visible portion of polygons (as centroid fill only do it).

**Comment by gioman** [comment]
> rotation expression = main_angle($geometry)

yep, in the expression preview seems to show the correct values, but then they are not applied in the symbology property.

**Comment by roya0045** [comment]
The $geometry becomes the one made by the geometry generator, which is good otherwise you would never be able to get back that geometry.  That's even more important with multiple geometry generator symbology.

The best solution would be to make a virtual field with the elements you want. Or you can use `get_feature` or `get_feature_by_id` to exit the current scope. 

I honesty don't see this as a bug, other than something like `$original_geometry` could be added but that's finnicky to implement.

**Comment by nmoyroud** [comment]
Ok I understand your point of view. But I don't agree with your conclusion... Everywhere in QGIS `$geometry` and `geometry()` function refer to the geometry of entities. For example when we use centroid fill symbol type, `$geometry` always refer to the geometry of entity, not the one of centroid. So it's not consistent to do it differently in geometry generator, at least it's not what the user would expect !

You're right maybe it can be useful to have access to the geometry of generated symbol, but I think it's useful to access easily to geometry of entities, without using some hack in the expression editor. But anyway I will give a try to your solution with `get_feature` or `get_feature_by_id`. 

So my proposal for geometry generator symbol is to let `$geometry` access to geometry of entities (as everywhere in QGIS) and add a new variable `$symbol_geometry` to give access to the geometry of generated symbols. But I don't know what is the complexity to implement this !

**Comment by nyalldawson** [comment]
> So my proposal for geometry generator symbol is to let $geometry access to geometry of entities (as everywhere in QGIS) and add a new variable $symbol_geometry to give access to the geometry of generated symbols. But I don't know what is the complexity to implement this !

This cannot be done without breaking existing projects. A new variable would have to be introduced for the original feature geometry instead.

But personally I'd rather see "geometry($currentfeature)" work for this use case instead.

**Comment by gioman** [comment]
> So my proposal for geometry generator symbol is to let `$geometry` access to geometry of entities (as everywhere in QGIS) and add a new variable `$symbol_geometry` to give access to the geometry of generated symbols. But I don't know what is the complexity to implement this !

@nmoyroud we can change this to feature request. Can you edit the title and description to better reflect this change? thanks.

**Comment by roya0045** [comment]
> > So my proposal for geometry generator symbol is to let $geometry access to geometry of entities (as everywhere in QGIS) and add a new variable $symbol_geometry to give access to the geometry of generated symbols. But I don't know what is the complexity to implement this !
> 
> This cannot be done without breaking existing projects. A new variable would have to be introduced for the original feature geometry instead.
> 
> But personally I'd rather see "geometry($currentfeature)" work for this use case instead.

I think using `geometry()` to get the displayed geometry and not the stored geometry is quite useful. If you have to convert polygon to centroids and draw lines and liking it to the nearest centroid, without transforming the dataset, that can be useful.

I think that simply exposing the stored geometry as an attribute or another variable may be sufficient and would allow the options to use both the stored and generated geometries.

**Comment by nmoyroud** [comment]
The most important thing is to give access to both geometry, whatever variable name. For me it's better if $geometry has the same meaning in all QGIS contexts, but if you think it's better with another variable name for retro-compatibility, I don't care  :-)

**Comment by nmoyroud** [comment]
Ok just in case it could help someone, I did the job for rotation of my generated symbol with the following expression : `main_angle (geometry(get_feature_by_id(@layer , $id)))`
Thanks to roya0045 for the indication !

I agree with nyalldawson for `geometry($currentfeature)` solution.

**Comment by nyalldawson** [comment]
> For me it's better if $geometry has the same meaning in all QGIS contexts, but if you think it's better with another variable name for retro-compatibility, I don't care :-)

To explain the rationale here:

We want symbols to be re-usable cleanly whether or not they are used as a subcomponent of a "parent" symbol. So imagine I make some type of "wavy line" line symbol type, which uses a `wave_randomized($geometry,....)` generator expression to get a wavy line symbol. This works fine if the feature being rendered is a line feature. But if you then wanted to use that same wavy line symbol for the lines in a line pattern fill, or for rendering the borders of a polygon, or for a callout line symbol, or ... then the symbol would break and have unpredictable results if $geometry suddenly becomes a polygon geometry.

So $geometry is always treated as "the shape being drawn RIGHT NOW", whether or not that's a feature's geometry, a subcomponent shape of some more complex parent symbol, or hatch line in a scalebar, a label callout line, or anything!

**Comment by roya0045** [comment]
@antoniolocandro did you try Nyall's PR or just master?

**Comment by antoniolocandro** [comment]
Oh right! used dev version @roya0045, I normally install via OSGEO4W @gioman I think the patch required me to do something else so I would wait it lands there to try it out.

**Comment by DelazJ** [comment]
>  I think the patch required me to do something else so I would wait it lands there to try it out.

From memory, i don't think you need anything special t
