### ISSUE TITLE
Rule Based Symbology issue when field used for filter has a "-" in its name

### ISSUE THREAD

**Issue by benderbernd** [qgis/QGIS#46459]
### What is the bug or the crash?

When one creates a symbology by categorizing features in a layer, everything works as it should. When, however, one converts the categories into rules by switching to "Rule-Based" Symbology while the field name contains a hyphen ("-"), I noticed a bug. In my case, the field name which the categorisation bases on is not framed in double quotation marks as it should be, rendering the symbology useless until one adds the quotation marks by hand.

Categorized: 
![grafik](https://user-images.githubusercontent.com/96077143/145863756-60731d0f-0c85-452a-8c54-a97ba1b50a0e.png)

Rule-Based (Wrong Syntax):
![grafik](https://user-images.githubusercontent.com/96077143/145863852-ebaf2695-1a45-4183-8476-37b644c05208.png)

### Steps to reproduce the issue

1. Create a Categorized Symbology by field value
2. Switch Symbology type from "Categorized" to "Rule-Based"
3. Inspect the outcoming Expression for missing quotation marks in field names

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.1-Białowieża | QGIS code revision | 663dcf8fb9
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.4.0
PROJ version | 8.2.0
EPSG Registry database version | v10.038 (2021-10-21)
GEOS version | 3.10.0-CAPI-1.16.0
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
GroupStats | 2.2.2
ImportPhotos | 2.2.2
latlontools | 3.4.6
mmqgis | 2019.8.11
nominatim_locator_filter | 0.2.3
OnlineRoutingMapper | 0.9
ORStools | 1.4.0
qchainage | 3.0.1
qfieldsync | v3.2.0
QGISSortAndNumber-master | 1.0
qgis_resource_sharing | 0.16.0
QgsWcpsClient1 | 2.0
QuickOSM | 1.14.1
shapetools | 3.3.10
slyr_community | 3.1.0
wps | 3.0.0
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.5
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by roya0045** [comment]
If you try with a field that doesn't have a '-' ? I recall there was something to this effect around.

**Comment by gioman** [comment]
> If you try with a field that doesn't have a '-' ? I recall there was something to this effect around.

@roya0045 this was the ticket

https://github.com/qgis/QGIS/issues/44379

@benderbernd can you see if this a similar case that was not fixed?

**Comment by roya0045** [comment]
@gioman Thanks Gio! I assume it's the same thing, though instead of checking the expression logic it would be the 'conversion' step. But that's just my guess without looking into it.

**Comment by benderbernd** [comment]
@gioman @roya0045 Thanks for investigating! It indeed seems like @gioman pointed out. The issue does not come up when there's no "-" in the field name.

**Comment by roya0045** [comment]
Might be failing this check , unsure what else could be the issue. https://github.com/qgis/QGIS/blob/4e50050de03de7edd4f7e1227ed039c9fe85734d/src/core/symbology/qgsrulebasedrenderer.cpp#L1330

**Comment by agiudiceandrea** [comment]
> Might be failing this check , unsure what else could be the issue.
> 
> https://github.com/qgis/QGIS/blob/4e50050de03de7edd4f7e1227ed039c9fe85734d/src/core/symbology/qgsrulebasedrenderer.cpp#L1330

@roya0045, it seems to be so...

```python
testExpr = QgsExpression('fieldname')
testExpr.isField()
True

testExpr = QgsExpression('field_name')
testExpr.isField()
True

testExpr = QgsExpression('field-name')
testExpr.isField()
False

testExpr = QgsExpression('"field-name"')
testExpr.isField()
True
```

**Comment by nyalldawson** [comment]
@agiudiceandrea it should be using QgsExpression::expressionToLayerFieldIndex instead -- that's a more precise test

**Comment by benderbernd** [comment]
@nyalldawson @agiudiceandrea Nice that the issue can be tracked down. Is it an easy fix to implement in the next update?
All the best and thank you for the great work!

**Comment by roya0045** [comment]
@nyalldawson @agiudiceandrea if neither of you has the time I can work on it in the coming days.
