### ISSUE TITLE
Trying to add GPKG from data source manager crashes QGIS master

### ISSUE THREAD

**Issue by antoniolocandro** [qgis/QGIS#46463]
### What is the bug or the crash?

QGIS crashes on attempting loading GPKG

### Steps to reproduce the issue

Just open a project and try to connect to any GPKG

### Versions

Crash ID: e10c77374c81f737a92ad1beef84829d40f49742

Stack Trace

QTreeViewPrivate::widthHintForIndex :
QTreeView::sizeHintForColumn :
QTreeView::resizeColumnToContents :
QgsMaskingWidget::qt_static_metacall :
QgsMaskingWidget::qt_static_metacall :
QgsMaskingWidget::qt_static_metacall :
QgsMaskingWidget::qt_static_metacall :
QObject::qt_static_metacall :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsSettingsEntryDouble::QgsSettingsEntryDouble :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsSettingsEntryDouble::QgsSettingsEntryDouble :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
QgisApp::projectTemporalRangeChanged :
QgisApp::projectTemporalRangeChanged :
QgisApp::projectTemporalRangeChanged :
QgisApp::projectTemporalRangeChanged :
QgisApp::projectTemporalRangeChanged :
QObject::qt_static_metacall :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsSettingsEntryDouble::QgsSettingsEntryDouble :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsSettingsEntryDouble::QgsSettingsEntryDouble :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
QgisApp::projectTemporalRangeChanged :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.23.0-Master
QGIS code revision: 54b385f6d6
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.0
Running against GDAL: 3.4.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22518

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

QGIS 3.22.1 works OK

**Comment by gioman** [comment]
@antoniolocandro just updated to the latest master on osgeo4w and is fine here.

**Comment by antoniolocandro** [comment]
updated today this is now my report after just clicking connect

Python Stack Trace
Windows fatal exception: access violation

Current thread 0x00000524 (most recent call first):

Stack Trace
No stack trace is available.

QGIS Info
QGIS Version: 3.23.0-Master
QGIS code revision: 4e50050de0
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.0
Running against GDAL: 3.4.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22518

**Comment by antoniolocandro** [comment]
I do not know if it makes a difference I am using the osgeo4w installer

Using the database db  or browser manager doesn't have the crashing issue just the unified one, here is a video on the crashing

https://user-images.githubusercontent.com/4627073/146038321-5f7998e6-58ee-49fe-a30e-f2ddf752de86.mp4

**Comment by gioman** [comment]
> I do not know if it makes a difference I am using the osgeo4w installer

@antoniolocandro have you tried a different machine?

**Comment by antoniolocandro** [comment]
Let me see if I can test on my son's laptop, will report tomorrow. At least for now I have a workaround by using the browser.

**Comment by gioman** [comment]
@antoniolocandro You didn't specified it was in the data source manager. I can confirm now.

**Comment by antoniolocandro** [comment]
> @antoniolocandro You didn't specified it was in the data source manager. I can confirm now.

I left the most important piece of information apparently! At least the video helped you out notice it

**Comment by roya0045** [comment]
Ok so your first version contained only the changes from the reworked UX and your latest version contains the latest change to the file, now strangely that breaks the stacktrace. See https://github.com/qgis/QGIS/commits/master/src/gui/providers/ogr/qgsogrdbsourceselect.cpp

**Comment by antoniolocandro** [comment]
Sorry I can't follow what you are telling me. Something I need to do?

**Comment by roya0045** [comment]
> @antoniolocandro You didn't specified it was in the data source manager. I can confirm now.

Did you get the crash only linux too? My build on ubuntu is wonky and I didn't a crash, so I'm not sure if it's windows only or whatever is problematic with my build didn't trigger the crash (though it seems related to qt and not ogr...)
