### ISSUE TITLE
Tools and toolbox not available after recent download 

### ISSUE THREAD

**Issue by LukeKR84** [qgis/QGIS#46482]
### What is the bug or the crash?

Hello, I work on linux (Ubuntu 20.04) and I recently discovered that my version of QGIS no longer had any vector or raster tools available in its interface. The toolbox option had also completely disappeared. It may have happened after a recent "sudo apt update" entered on the linux bash terminal, but I'm not sure. I have uninstalled and reinstalled several versions of QGIS but the problem remains. At the time I was working on 3.20, but the same problem recurred on versions 3.22 and 3.16 the Hanover LTR. Is this a recurring theme with Linux users?

### Steps to reproduce the issue

Install QGIS on a linux operating system, preferably Ubuntu 20.04

### Versions

Current version installed 3.16 :

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

Version de QGIS | 3.16.14-Hannover | Révision du code | 4279198632
-- | -- | -- | --
Compilé avec Qt | 5.12.8 | Utilisant Qt | 5.12.8
Compilé avec GDAL/OGR | 3.0.4 | Utilisé avec GDAL/OGR | 3.0.4
Compilé avec GEOS | 3.8.0-CAPI-1.13.1 | Utilisé avec GEOS | 3.8.0-CAPI-1.13.1
Compilé avec SQLite | 3.31.1 | Fonctionne avec SQLite | 3.31.1
Version du client PostgreSQL | 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1) | Version de SpatiaLite | 4.3.0a
Version de QWT | 6.1.4 | Version de QScintilla2 | 2.11.2
Compilé avec PROJ | 6.3.1 | Fonctionne avec PROJ | Rel. 6.3.1, February 10th, 2020
Version de l'OS | Ubuntu 20.04.3 LTS
Extensions Python actives | veloroutes_voies_vertes; quick_map_services; QuickOSM; joinmultiplelines; MultiDistanceBuffer; Submission; Multi_Ring_Buffer; db_manager

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
> Is this a recurring theme with Linux users?

@LukeKR84 no, you likely have a local issue. It seems you don't have the python3-qgis package installed, or have issues with it.

**Comment by gioman** [comment]
> @LukeKR84 no, you likely have a local issue. It seems you don't have the python3-qgis package installed, or have issues with it.



> veloroutes_voies_vertes; quick_map_services; QuickOSM; joinmultiplelines; MultiDistanceBuffer; Submission; Multi_Ring_Buffer; db_manager

@LukeKR84 no sorry that could not be otherwise you would not have this extensions enabled. Maybe you just have the "processing" plugin disabled?

**Comment by LukeKR84** [comment]
> > @LukeKR84 no, you likely have a local issue. It seems you don't have the python3-qgis package installed, or have issues with it.
> 
> > veloroutes_voies_vertes; quick_map_services; QuickOSM; joinmultiplelines; MultiDistanceBuffer; Submission; Multi_Ring_Buffer; db_manager
> 
> @LukeKR84 no sorry that could not be otherwise you would not have this extensions enabled. Maybe you just have the "processing" plugin disabled?

I'll look into that. When I say that I don't have the tools available, I mean the basic stuff like intersection, clip etc ... Strangely enough, as you quite correctly described, the plugin extensions I installed a while ago are still there.

**Comment by LukeKR84** [comment]
@gioman You wouldn't happen to know what terminal commands I would need to enter to check : 
a) If the processing plugin is either installed or disabled?
b) the command needed to enable or install it?

**Comment by gioman** [comment]
@LukeKR84 first check if "processing" is enabled.

**Comment by LukeKR84** [comment]
How would I do that?

**Comment by LukeKR84** [comment]
@gioman OK, I'm really sorry for the fuss, I've just solved the problem ! All I had to do was click on processing in extensions and the problem's solved. Thank you for all your help! It was indeed, very basic and simple, not a problem with version of QGIS at all.

**Comment by Gustry** [comment]
Side note, it would be nice, at the end of the start process (after all python plugins initialization), if QGIS could check if Processing is enabled :) Otherwise, having a warning. Processing is so important in QGIS ;-)
