### ISSUE TITLE
WFS provider doesn't recognize CRS strings other than OGC URNs

### ISSUE THREAD

**Issue by GregNed** [qgis/QGIS#46485]
### Feature description

The WFS provider only seems to understand `OGC URN`s e.g. `urn:ogc:def:crs:EPSG::4326`, and it won't recognize an `ESPG ID` like `ESPG:4326` or a `CRS ID` like `CRS:84`. This holds both when the CRS is set via `QgsDataSourceUri.setParam('SRSNAME', <CRS>)` and by just adding it to the `url` (as set by `QgsDataSourceUri.setParam('url', <url>)`. The WFS provider will just ignore it and set a default SRSNAME  of `urn:ogc:def:crs:EPSG::4326`. Here's my code:
```
uri = QgsDataSourceUri()
uri.setParam('url', 'https://services.sentinel-hub.com/ogc/wfs/<my_service_endpoint>')
uri.setParam('SRSNAME', 'EPSG:3857')
uri.setParam('TYPENAME', 'DSS2')
uri.setParam('BBOX', <some bbox>)
layer = QgsVectorLayer(uri.uri(), 'layername', 'wfs')
QgsProject.instance().addMapLayer(layer)
```
The network debugger shows that `EPSG:3857` was ignored and a default of WGS84's OGC URN was used instead:

![image](https://user-images.githubusercontent.com/29100825/145976246-a01283ff-938f-41f3-996c-9b389d72787f.png)

Stack
QGIS version 3.22.1-Białowieża
QGIS code revision 663dcf8fb9
Qt version 5.12.8
Python version 3.8.10
GDAL/OGR version 3.0.4
PROJ version 6.3.1
EPSG Registry database version v9.8.6 (2020-01-22)
OS version Ubuntu 20.04.3 LTS

**Comment by rouault** [comment]
This is simply a usage issue here. The SRSNAME and TYPENAME parameters should be in lower case. And the BBOX parameter isn't a valid one for a WFS URI (a WFS URI is not a WFS GetFeature URL). 

https://github.com/qgis/QGIS/pull/48550 should make things more obvious
