### ISSUE TITLE
Strange GDAL crash when closing QGIS

### ISSUE THREAD

**Issue by dkonda** [qgis/QGIS#46487]
### What is the bug or the crash?

Exiting QGIS causes a GDAL related crash to occur. Crash report is pasted below.

Crash ID: 2bba35ac54ec3f66db08369439704d5a7beb5523

Stack Trace

GDALDestroyDriver :
dal::GDALRasterDriver::deregisterGDALDrivers :
dal::Client::~Client :
calc::DataStorageId::setId :
::operator() :
__crt_seh_guarded_call::operator(), &, > :
execute_onexit_table :
calc::vs2CsfVs :
calc::vs2CsfVs :
LdrpCallInitRoutine :
LdrShutdownProcess :
RtlExitUserProcess :
ExitProcessImplementation :
exit_or_terminate_process :
common_exit :
BaseThreadInitThunk :
RtlUserThreadStart :

### Steps to reproduce the issue

Crash occurs every time QGIS is closed.

### Versions

QGIS Info
QGIS Version: 3.22.1-Bia?owie?a
QGIS code revision: 663dcf8fb9
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.0
Running against GDAL: 3.4.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

### Additional context

A fresh profile solves the problem, I would however like to know the source of the issue, in order to avoid it in the future.

**Comment by gioman** [comment]
> A fresh profile solves the problem, I would however like to know the source of the issue, in order to avoid it in the future.

you must look into 3rd party plugins, likely.

**Comment by jef-n** [comment]
This is related to pcraster, which uses GDAL C++ API.
