### ISSUE TITLE
Proximity (Raster distance) tool generates incorrect distances

### ISSUE THREAD

**Issue by MarByteBeep** [qgis/QGIS#46490]
### What is the bug or the crash?

For some reason, beyond my knowledge/capabilities, the Proximity (Raster distance) tool reports incorrect values. Since I'm new to QGIS, it might be that I've overlooked some trivialities. I suspect I probably did something wrong with the CRS settings, but it could very well be a bug or some UI-confusion. That's why I decided to post it here. 

The bug does use a plugin, QuickOSM, but I suspect this isn't the culprit. I described the reproduction steps as best as I could.

### Steps to reproduce the issue

Prerequisites: QuickOSM

1. Create a new/blank project
2. Set CRS to EPSG:3857
3. Add new WMS connection: https://service.pdok.nl/brt/achtergrondkaart/wmts/v2_0?request=getcapabilities&service=wmts
4. Addthe `grijs->EPSG:3857` layer to the project
5. Set scale to 1:262144
6. Launch `QuickOSM` plugin
7. Select `Land use and nature/Land use/Military` preset
8. Type `'t Harde` in the `in` field and hit `Run`
9. Observe the screen looks like this:

![image](https://user-images.githubusercontent.com/58225562/146014505-d7779957-ec80-4762-acea-130e321837a8.png)

Since the Proximity (Raster distance) tool requires a rasterized layer to work with, let's rasterize it.

10. Select the `landuse_military_'t Harde` layer containing the vectorized features and make sure it is the only visible layer.
11. Select the `Convert Map to Raster` tool from the ToolBox
12. Enable `Make background transparant`
13. Draw a minimum extend around the features like so

![image](https://user-images.githubusercontent.com/58225562/146017344-169d9aed-ded8-459e-a8c9-42b5238299f3.png)

14. Hit `Run`
15. There should be a new layer named `Output Layer` that looks like this:

![image](https://user-images.githubusercontent.com/58225562/146017539-8148b371-d2e8-475a-b835-8e33ab0c90ff.png)

16. Verify that the CRS of this new layer is EPSG:3857
17. Run the `Raster->Analyze->Proximity (Raster Distance)` tool
18. Select the output layer and set the following values:

![image](https://user-images.githubusercontent.com/58225562/146017987-07aac13d-4888-44bd-8153-488839a5196a.png)

(we we will have a 3 km radius around the original shape)

After hitting run, we now ended up with the following result:

![image](https://user-images.githubusercontent.com/58225562/146018163-2e5fd4a2-a7d2-4b76-9ab6-035650964a5e.png)

19.  We can get rid of the black -1 values by selecting the newly generated proximity layer and add `-1` to the `Transparency->Additional No Data Value` field (no idea as to why this hasn't been done automatically, but okay :)
20. Ensure the `Output Layer` is drawn in front of the proximity layer, so we see where the original shape used to be
21. Now measure from an edge of that original shape to the boundary of the proximity layer and observe it is way way less than the 3000 meters that I specified: 1769 meters. When I sample the proximity layer at the exact point it reports 2900 meters.

![image](https://user-images.githubusercontent.com/58225562/146019200-2a0baa08-2ae8-4be5-aafe-117ee7675913.png)

What steps am I missing? 

### Versions

QGIS version
3.22.1-Białowieża
QGIS code revision
663dcf8fb9
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.0
PROJ version
8.2.0
EPSG Registry database version
v10.038 (2021-10-21)
GEOS version
3.10.0-CAPI-1.16.0
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
BGTImport
3.16
inspireNL
2.6
QuickOSM
2.0.0
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

This is the raster used for the proximity operation

[test_layer.zip](https://github.com/qgis/QGIS/files/7712622/test_layer.zip)

_No response_

**Comment by gioman** [comment]
> What steps am I missing?

@MarByteBeep attach the necessary data (preferably directly the raster used for the proximity operation).

**Comment by MarByteBeep** [comment]
> > What steps am I missing?
> 
> @MarByteBeep attach the necessary data (preferably directly the raster used for the proximity operation).

Thanks for the reply. I added the following file, and included it the initial report.

[test_layer.zip](https://github.com/qgis/QGIS/files/7712622/test_layer.zip)

Hope this helps?

**Comment by gioman** [comment]
> Hope this helps?

@MarByteBeep this is likely because your data is in CRS 3857, which you cannot rely on for measurements. If you use for example a UTM CRS:

![image](https://user-images.githubusercontent.com/1951107/146028259-5224b6ac-1963-4c58-b8d2-ab7c4f99fe01.png)

**Comment by gioman** [comment]
> I'd like to be able to do this type of proximity rendering all around the globe, using a CRS that works accurately enough for me (100 meters more or less doesn't really matter).

@MarByteBeep there isn't a single projected CRS that will work in a precise way for the whole globe (as far as I know).

**Comment by MarByteBeep** [comment]
@gioman ok, which leaves open the question: how can we have a difference between the UTM CRS you used and EPSG:28992? If the real distance to the town's center is 3km, how do I get to that value using the transform you proposed?

Also what I don't seem to understand is why that Proximity tool cannot seem to use the ellipsoid distances as reported in the measurement tool. Look at the image below. I have drawn a number of 3km lines from that edge in a EPSG:3857 CRS and the ellipsoid measurements are correctly reporting 3000 meters where I expect them. Yet the generated distance map is something totally different. Why?

![image](https://user-images.githubusercontent.com/58225562/146035041-76a1e4e6-17b3-4a68-951c-e5d8bf25e57b.png)

**Comment by gioman** [comment]
> ok, which leaves open the question: how can we have a difference between the UTM CRS you used and EPSG:28992? If the real distance to the town's center is 3km, how do I get to that value using the transform you proposed?

@MarByteBeep because the right UTM for your CRS is just one. I don't know which is, I just used one that was likely to prove that 3857 is wrong.

**Comment by gioman** [comment]
> Also what I don't seem to understand is why that Proximity tool cannot seem to use the ellipsoid distances as reported in the measurement tool. Look at the image below.

@MarByteBeep because that tool is "just" a GUI for 

https://gdal.org/programs/gdal_proximity.html

which does not know anything about QGIS configs (other the input CRS/name/path).

**Comment by MarByteBeep** [comment]
Got it. Would it be possible for that proximity tool to use that ellipsoid calculation for its distance? And if possible, would this be helpful for others as well? I probably don't understand the matter too well, as it seems weird that this isn't configurable and I seem to be the only one asking this :)
