### ISSUE TITLE
Crash after loading custom WMS layer

### ISSUE THREAD

**Issue by MarByteBeep** [qgis/QGIS#46503]
## User Feedback

I believe I started a new project and then loaded a custom WMS layer. And then boom.

## Report Details

**Crash ID**: [a4986ee325f49faf8c13194c18a354473fd077d1](https://github.com/qgis/QGIS/search?q=a4986ee325f49faf8c13194c18a354473fd077d1&type=Issues)

**Stack Trace**
<pre>
memcpy_repmovs memcpy.asm:114
QgsRasterDataProvider::block :
QgsSingleBandColorDataRenderer::block :
QgsBrightnessContrastFilter::block :
QgsHueSaturationFilter::block :
QgsRasterResampleFilter::block :
QgsRasterProjector::block :
QgsRasterIterator::readNextRasterPartInternal :
QgsRasterDrawer::draw :
QgsRasterLayerRenderer::render :
QgsMapRendererParallelJob::renderLayerStatic :
QgsMapRendererParallelJob::renderingFinished :
QgsMapRendererParallelJob::renderingFinished :
QgsMapRendererParallelJob::takeLabelingResults :
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.22.1-Bia?owie?a
QGIS code revision: 663dcf8fb9
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.0
Running against GDAL: 3.4.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

### Steps to reproduce the issue

N/A

### Versions

QGIS version
3.22.1-Białowieża
QGIS code revision
663dcf8fb9
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.0
PROJ version
8.2.0
EPSG Registry database version
v10.038 (2021-10-21)
GEOS version
3.10.0-CAPI-1.16.0
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
BGTImport
3.16
inspireNL
2.6
QuickOSM
2.0.0
quick_map_services
0.19.27
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@MarByteBeep you must try on a new QGIS profile, and if the problem persist post here the WMS URL.

**Comment by MarByteBeep** [comment]
Will do. Close it for now and report back when I can repro it!
