### ISSUE TITLE
QGIS unexpectedly ended

### ISSUE THREAD

**Issue by doomsday89** [qgis/QGIS#46507]
### What is the bug or the crash?

Crash ID: 0075dccc9bc924efdec372c641f7087e479db1bb

Stack Trace

QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QRasterPaintEngine::penChanged :
QPolygonF::united :
QRasterPaintEngine::drawImage :
QPainter::drawImage :
QPainter::drawImage :
QgsWmsProvider::draw qgswmsprovider.cpp:923
QgsWmsProvider::readBlock qgswmsprovider.cpp:996
QgsRasterDataProvider::block qgsrasterdataprovider.cpp:212
QgsSingleBandColorDataRenderer::block qgssinglebandcolordatarenderer.cpp:62
QgsBrightnessContrastFilter::block qgsbrightnesscontrastfilter.cpp:119
QgsHueSaturationFilter::block qgshuesaturationfilter.cpp:123
QgsRasterResampleFilter::block qgsrasterresamplefilter.cpp:164
QgsRasterProjector::block qgsrasterprojector.cpp:815
QgsRasterIterator::readNextRasterPartInternal qgsrasteriterator.cpp:130
QgsRasterDrawer::draw qgsrasterdrawer.cpp:60
QgsRasterLayerRendererFeedback::onNewData qgsrasterlayerrenderer.cpp:61
QgsWmsProvider::draw qgswmsprovider.cpp:966
QgsWmsProvider::readBlock qgswmsprovider.cpp:996
QgsRasterDataProvider::block qgsrasterdataprovider.cpp:212
QgsSingleBandColorDataRenderer::block qgssinglebandcolordatarenderer.cpp:62
QgsBrightnessContrastFilter::block qgsbrightnesscontrastfilter.cpp:119
QgsHueSaturationFilter::block qgshuesaturationfilter.cpp:123
QgsRasterResampleFilter::block qgsrasterresamplefilter.cpp:164
QgsRasterProjector::block qgsrasterprojector.cpp:815
QgsRasterIterator::readNextRasterPartInternal qgsrasteriterator.cpp:130
QgsRasterDrawer::draw qgsrasterdrawer.cpp:60
QgsRasterLayerRenderer::render qgsrasterlayerrenderer.cpp:321
QgsMapRendererParallelJob::renderLayerStatic qgsmaprendererparalleljob.cpp:353
QtConcurrent::MapKernel::iterator,QtConcurrent::FunctionWrapper1 >::runIteration qtconcurrentmapkernel.h:69
QtConcurrent::MapKernel::iterator,QgsImageOperation::ProcessBlockUsingPixelOperation >::runIterations qtconcurrentmapkernel.h:78
QtConcurrent::IterateKernel::iterator,void>::forThreadFunction qtconcurrentiteratekernel.h:256
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.16.14-Hannover
QGIS code revision: 4279198632
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

### Steps to reproduce the issue

add OpenStreetMap
change CRS into (source in properties)

### Versions

QGis 3.16.14 Hannover

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
> add OpenStreetMap

@doomsday89 how? meaning, from what source and from where in QGIS.

Have you tried with a new QGIS profile?
