### ISSUE TITLE
Graphical Modeler: "rasterize mesh dataset" does not allow to choose inputs

### ISSUE THREAD

**Issue by JonnyFri** [qgis/QGIS#46517]
### What is the bug or the crash?

While building a .model3 in the graphical modeler I found out, that the in german, Netzdatensatz rastern Tool, (i.e. Tin-Dataset-Rasterize, might be wrong just my translation) does not work. I used the TIN and TIN-Dataset input, but it won´t let me pick a Dataset. There are no displayed Datasets. If I start the tool from the Toolbox it works, but if i put the tool into an empty model it stops working again. My take is, that there might be some sort of bug in relation to the Model-Builder with this explict tool. First time experiencing this sort of Problem in the builder.

### Steps to reproduce the issue

1. Go to 'Graphical Modeler'
2. Then click onto the 'Rasterize Tin Dataset' algo
3. Try using it through the modeler
4. Compare it to using it through the toolbox

### Versions

3.22.0

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by JonnyFri** [comment]
![image](https://user-images.githubusercontent.com/96238971/146365478-66283ece-b965-439c-81d2-a14ea9097bcf.png) (Toolbox)
![image](https://user-images.githubusercontent.com/96238971/146365699-82ef0e47-e749-420f-881b-d67b4737fcee.png)
(Model-Builder)

**Comment by gioman** [comment]
It is "rasterize mesh dataset".

**Comment by alexbruy** [comment]
Not reproducible, I can easily create model with the "Rasterize mesh dataset" algorithm and it works from the modeler and from the toolbox. Please, provide exact steps needed to reproduce the issue.

**Comment by JonnyFri** [comment]
@alexbruy 
1. Just create a model with 2 inputs : meshlayer and mesh dataset
2. Run the model and try to select a dataset

**Comment by alexbruy** [comment]
Sorry I still don't see what is wrong. Here is my model, both layer and dataset are used as inputs for an algorithm.

![model](https://user-images.githubusercontent.com/776954/150950829-c64d83ee-1970-4242-a040-eb88302fbce9.png)

**Comment by JonnyFri** [comment]
Here you can see the Mesh im trying to rasterize and the datasets wthin:
![image](https://user-images.githubusercontent.com/96238971/150951856-511e28cc-f4b8-4049-b03e-f81dbfa97f09.png)
Here you can see that none of my datasets gets recognized within the model:
![image](https://user-images.githubusercontent.com/96238971/150952230-c407a99b-df12-4a08-8628-1919a5ed6e65.png)
Im trying my best to communicate the Problem :D

**Comment by alexbruy** [comment]
After playing a bit more, I think I realize what is wrong. Maybe it's only me, but issue description isn't precise.

The problem is that "Mesh Dataset Group" does not allow to choose parent "Mesh Layer" parameter. So it is not about unability to choose inputs.

**Comment by JonnyFri** [comment]
I think you just pointed it out exactly. It lets me choose within the datasets but it shows none because it isnt connected to the mother mesh. But it works fine if I use it from the toolbox. Only if I want to build it into my model it stops working.

**Comment by alexbruy** [comment]
Closing as duplicate of #46920.

**Comment by lhklaura** [comment]
was this solved? because I have the exact same problem
