### ISSUE TITLE
Crash when using vertex tool to move elements with categorical symbols from multiple gpkg layers

### ISSUE THREAD

**Issue by FabienDiot** [qgis/QGIS#46522]
### What is the bug or the crash?

When moving several elements with categorical symbols from multiple layers with the vertex tool, QGis freezes until the process is killed. No error nor warning is displayed either in the qgis consol or in DebugView (even when using the nightly build).

This only happens with geopackage. After converting the project to shape files, the elements can be moved without crashing QGis.
The crash also goes away when replacing all the categorical symbols by the default unique symbols.

The crash is somewhat inconsistant and it sometimes takes several trials for it to happen.

### Steps to reproduce the issue

I have been able to successfully recreate the crash with a minimalistic example composed of 4 layers with a single vertex each:
- create  a new project
- add 4 GPKG layers with a single field each, point geometry
- change symbolism from unique symbol to categorical based on the value of the field of each layer (a single symbol for all values of the field is enough)
- add one point to each layer
- move the 4 vertices with the vertex tool

Here is a sample project: [example_project.zip](https://github.com/qgis/QGIS/files/7728381/example_project.zip)

### Versions

QGis versions : 3.20.3 and 3.23.0
New profile without any extensions

Regular version used:
QGIS 3.20.3-Odense revision 495fbaec
Qt 5.15.2
Python 3.9.5
GDAL/OGR 3.3.1
Proj 8.1.1
EPSG Registry Database  v10.028 (2021-07-07)
GEOS 3.9.1-CAPI-1.14.2
SQLite 3.35.2
PDAL 2.3.0
PostgreSQL client 13.0
SpatiaLite 5.0.1
QWT 6.1.3
QScintilla2 2.11.5
OS Windows 10 2009
No Active Python extensions

Nightly buid:
QGIS 3.23.0-Master revision  25337c25b2
Qt 5.15.2
Python 3.9.5
GDAL/OGR 3.4.0
Proj 8.2.0
EPSG Registry Database v10.038 (2021-10-21)
GEOS 3.10.0-CAPI-1.16.0
SQLite 3.35.2
PDAL 2.3.0
PostgreSQL client unknown
SpatiaLite 5.0.1
QWT 6.1.3
QScintilla2 2.11.5
OS Windows 10 2009
This copy of QGIS has debugging output
No Active Python extensions

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
Is this still an issue? I can't reproduce with the latest master (94b62accf2a1cfc892bc9097cd4dd5f8a1f60ab0)
