### ISSUE TITLE
Qt: QXcb Connection: XCB Error

### ISSUE THREAD

**Issue by enzedrailmaps** [qgis/QGIS#46526]
### What is the bug or the crash?

Messages are randomly displayed reading "Qr: QXcbConnection: XCB error"

e.g. Qt: QXcbConnection: XCB error: 3 (BadWindow), sequence: 47437, resource  id: 14680650, major code: 40 (TranslateCoords), minor code: 0

### Steps to reproduce the issue

Unknown sequence of steps or causes. Messages seem to appear more or less randomly.

### Versions

QGIS version
3.16.14-Hannover
QGIS code revision
8ad98bd2b7
Compiled against Qt
5.15.2
Running against Qt
5.15.2
Compiled against GDAL/OGR
3.4.0
Running against GDAL/OGR
3.4.0
Compiled against GEOS
3.10.1-CAPI-1.16.0
Running against GEOS
3.10.1-CAPI-1.16.0
Compiled against SQLite
3.36.0
Running against SQLite
3.36.0
PostgreSQL Client Version
14.1 (Debian 14.1-3)
SpatiaLite Version
5.0.1
QWT Version
6.1.4
QScintilla2 Version
2.11.6
Compiled against PROJ
8.2.0
Running against PROJ
Rel. 8.2.0, November 1st, 2021
OS Version
Debian GNU/Linux bookworm/sid
This copy of QGIS writes debugging output.
Active python plugins
processing; 
db_manager; 
MetaSearch

QGIS version
3.16.14-Hannover
QGIS code revision
8ad98bd2b7
Compiled against Qt
5.15.2
Running against Qt
5.15.2
Compiled against GDAL/OGR
3.4.0
Running against GDAL/OGR
3.4.0
Compiled against GEOS
3.10.1-CAPI-1.16.0
Running against GEOS
3.10.1-CAPI-1.16.0
Compiled against SQLite
3.36.0
Running against SQLite
3.36.0
PostgreSQL Client Version
14.1 (Debian 14.1-3)
SpatiaLite Version
5.0.1
QWT Version
6.1.4
QScintilla2 Version
2.11.6
Compiled against PROJ
8.2.0
Running against PROJ
Rel. 8.2.0, November 1st, 2021
OS Version
Debian GNU/Linux bookworm/sid
This copy of QGIS writes debugging output.
Active python plugins
processing; 
db_manager; 
MetaSearch

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Running LTR nightly

**Comment by gioman** [comment]
> Running LTR nightly

@enzedrailmaps if is a nightly it is build with debug symbols so those messages are normal in the message bar.

**Comment by enzedrailmaps** [comment]
So how do you know what is a bug and what isn't?
