### ISSUE TITLE
QuickMapServices Contributed Pack

### ISSUE THREAD

**Issue by sspp11** [qgis/QGIS#46529]
### What is the bug or the crash?

I've correctly installed QuickmapServices plugin but when I try to get the Contributed Pack Qgis shows the error below:

**Error on getting contrib pack: 403**

How can I risolve this issue?

Thanks in advance

### Steps to reproduce the issue

![Cattura](https://user-images.githubusercontent.com/96287585/146519321-803778cd-f3b3-4efa-b05d-411b45991b92.PNG)

### Versions

3.22.1-Białowieża

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
@sspp11 you must report it to the plugin author/s, not here.
