### ISSUE TITLE
JPEG JFIF filter in "Open GDAL Supported Raster Dataset(s)" dialog lists wrong files

### ISSUE THREAD

**Issue by enzedrailmaps** [qgis/QGIS#46527]
### What is the bug or the crash?

When attempting to add raster files to a project.
The filter for JPEG files shows XML files as well
e.g.
1.jpg
1.jgw
1.xml
1.jpg.aux.xml
Should filter down to 1.jpg but instead it shows 1.jpg and 1.jpg.aux.xml

### Steps to reproduce the issue

1. click on "Open Data Source Manager"
2. in the left hand side click "Raster"
3. next to "Raster datasets" click ...
4. at the bottom of the dialog box click next to Filter and select JPEG JFIF
5. 

### Versions

QGIS version
3.16.14-Hannover
QGIS code revision
8ad98bd2b7
Compiled against Qt
5.15.2
Running against Qt
5.15.2
Compiled against GDAL/OGR
3.4.0
Running against GDAL/OGR
3.4.0
Compiled against GEOS
3.10.1-CAPI-1.16.0
Running against GEOS
3.10.1-CAPI-1.16.0
Compiled against SQLite
3.36.0
Running against SQLite
3.36.0
PostgreSQL Client Version
14.1 (Debian 14.1-3)
SpatiaLite Version
5.0.1
QWT Version
6.1.4
QScintilla2 Version
2.11.6
Compiled against PROJ
8.2.0
Running against PROJ
Rel. 8.2.0, November 1st, 2021
OS Version
Debian GNU/Linux bookworm/sid
This copy of QGIS writes debugging output.
Active python plugins
processing; 
db_manager; 
MetaSearch

QGIS version
3.16.14-Hannover
QGIS code revision
8ad98bd2b7
Compiled against Qt
5.15.2
Running against Qt
5.15.2
Compiled against GDAL/OGR
3.4.0
Running against GDAL/OGR
3.4.0
Compiled against GEOS
3.10.1-CAPI-1.16.0
Running against GEOS
3.10.1-CAPI-1.16.0
Compiled against SQLite
3.36.0
Running against SQLite
3.36.0
PostgreSQL Client Version
14.1 (Debian 14.1-3)
SpatiaLite Version
5.0.1
QWT Version
6.1.4
QScintilla2 Version
2.11.6
Compiled against PROJ
8.2.0
Running against PROJ
Rel. 8.2.0, November 1st, 2021
OS Version
Debian GNU/Linux bookworm/sid
This copy of QGIS writes debugging output.
Active python plugins
processing; 
db_manager; 
MetaSearch

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

LTR nightly
New issue since 3.16.8 does not have this problem.

**Comment by gioman** [comment]
> New issue since 3.16.8 does not have this problem.

@enzedrailmaps do you see it also in QGIS Browser?

**Comment by enzedrailmaps** [comment]
The browser use a different filter e.g.
1.jpg
1.xml

**Comment by gioman** [comment]
@enzedrailmaps I tested on Windows 10 and Mint 20.2 and cannot confirm. Also the browser showing xml files is correct as they cab be datasources.

**Comment by gioman** [comment]
![image](https://user-images.githubusercontent.com/1951107/146655047-ffc9b3ab-b0ba-434c-ad16-90c38d5c94a3.png)

**Comment by enzedrailmaps** [comment]
The result in the browser is the same as for 3.16.8

**Comment by gioman** [comment]
> The result in the browser is the same as for 3.16.8

@enzedrailmaps what you see in the browser is correct. And probably what you see in the "add raster" dialog it depends on your desktop manager.

**Comment by enzedrailmaps** [comment]
a jpg.aux.xml file is not recognised as a valid datasource by Qgis, and the extra entries in the path mean only half as many layers can be added at one time.

**Comment by enzedrailmaps** [comment]
OK, it looks like a new issue in the bookworm file open dialog, I don't see this in 3.23 on bullseye.
I assume it will be part of the new KDE components for bookworm.

**Comment by enzedrailmaps** [comment]
The inference is that this is an issue with the desktop environment or perhaps the Qt framework and not a matter for the Qgis project to concern itself with.
As an end user I am not privy to questions of software design implementation that are relevant to this software package.
It is not really realistic for me to file a bug report with the maintainers of any of the relevant components: Debian, KDE or Qt, for the simple fact that it is not clear whether the issue lies within any of these particular packages, and generally they do not wish to receive bug reports from end users.
At a guess the specific dialog box is implemented in the Qt framework and it could still be a programming issue if Qt have issued a documentation update requiring a particular design change to the specification of file filters.
Regardless of the details at some level it would come down to whether the relevant package is in the Debian or Qgis software repositories which is not something that I could be expected to know.

**Comment by gioman** [comment]
@enzedrailmaps debian bullseye:


left, QGIS with JPG filter

right, debian file manager

![image](https://user-images.githubusercontent.com/1951107/151612166-4436e9e8-f464-402c-a1cb-c613ad6678d5.png)

so, can't confirm your obsevations.

**Comment by gioman** [comment]
QGIS 3.22.3 which is at the moment the only version that will get fixes (as there will not be another 3.16 release).
