### ISSUE TITLE
Misleading Warning When Uninstall Experimental Plugin?

### ISSUE THREAD

**Issue by ismailsunni** [qgis/QGIS#46538]
### What is the bug or the crash?

When I want to uninstall an experiment plugin, I got this warning message:
![image](https://user-images.githubusercontent.com/1421861/146581838-5904554a-1560-49b1-8b8a-39a0da1cfea6.png)

Although, the version of the plugin is available in the QGIS plugin repo. I think it's misleading and makes the user hesitate to remove it or makes the plugin developer not sure if the plugin is really in the repo or not.

Or is it the expected behavior for an experimental plugin?

### Steps to reproduce the issue

1. Install any plugin with an experimental flag (e.g. Chinese Postman Solver)
2. Click Uninstall Plugin
3. The warning message shows up

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.1-Białowieża | QGIS code revision | 663dcf8fb9
-- | -- | -- | --
Qt version | 5.12.8
Python version | 3.8.10
GDAL/OGR version | 3.0.4
PROJ version | 6.3.1
EPSG Registry database version | v9.8.6 (2020-01-22)
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
SQLite version | 3.31.1
PDAL version | 2.0.1
PostgreSQL client version | 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.2
OS version | Ubuntu 20.04.3 LTS
  |   |   |  
Active Python plugins
quick_map_services | 0.19.27
plugin_reloader | 0.9.1
latlontools | 3.5.9
profile-manager | version 0.2
pgRoutingLayer | 3.0.1
QuickWKT | 3.1
QuickOSM | 2.0.0
numericalDigitize | 0.4.6
grassprovider | 2.12.99
sagaprovider | 2.12.99
db_manager | 0.1.20
processing | 2.12.99
GeoKKP-GIS | 1.1.2
chinesepostman | 0.3.0

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by roya0045** [comment]
I think the message means that if you remove it, you may not be able to reinstall it from your repositories.

It could be phrased better.

**Comment by agiudiceandrea** [comment]
It seems the warning is added here when the plugin "status" metadata is "orphan"
https://github.com/qgis/QGIS/blob/6d3cec6dcf5c94d6aa347fa3488a284f36463008/python/pyplugin_installer/installer.py#L411-L412

The status "orphan" is defined as:
"orphan = installed and not available to download;"
"Only locally available", "category: plugins that are only locally available"

**Comment by gioman** [comment]
By the way, just installed and removed that plugin and I didn't get that message.

**Comment by ismailsunni** [comment]
@agiudiceandrea yes, I also found that. And based on that definition, the current behavior for an experimental plugin is not correct.

@gioman did you try with an experimental plugin?

**Comment by gioman** [comment]
> @gioman did you try with an experimental plugin?

@ismailsunni yes

**Comment by ismailsunni** [comment]
@gioman can you tell me which plugin? I tried other experimental plugins (e.g. 3D City Builders, A-Maps), and it still gives me the behavior. Also, could you try the Chinese Postman Solver plugin? It's strange if it doesn't happen on your QGIS (or only happens in mine)

**Comment by gioman** [comment]
@ismailsunni nevermind, now I also see the error.
