### ISSUE TITLE
No LTR version for Ubuntu impish

### ISSUE THREAD

**Issue by katagen** [qgis/QGIS#46537]
### What is the bug or the crash?

I need to install qgis server on Ubuntu impish.
When I add the lines for one of the repositories:
`deb     https://qgis.org/ubuntu-ltr impish main`
`deb-src https://qgis.org/ubuntu-ltr impish main`
I have an error that impish release is not found.

If I go to the repository: https://qgis.org/ubuntu-ltr
I can see that there is no impish distribution?
![Capture d’écran 2021-12-17 à 16 43 11](https://user-images.githubusercontent.com/37768582/146570434-f72068e7-3f60-46a2-940f-fdba94e214ee.png)
But it should exists, cause on qgis.org, they mention it? No?
![Capture d’écran 2021-12-17 à 16 48 17](https://user-images.githubusercontent.com/37768582/146571121-6666cc11-fa12-4b7e-be5c-e526ba322d88.png)

### Steps to reproduce the issue

Describe above.

### Versions

Not relevant

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by jef-n** [comment]
impish' sip is too new for 3.16.
