### ISSUE TITLE
Change of behaviour or memory leak in PyQGIS API 

### ISSUE THREAD

**Issue by Arturo-at-tyc-gis** [qgis/QGIS#46533]
### What is the bug or the crash?

This issue relates to a custom plugin I'm making. This plugin has a custom button for **creating features on a vector layer**  that prompts a **custom form**. On saving the feature the code below produces different output wether used in versions 3.16.4, 3.22.0 or 3.22.1:

```
def on_save_click(self):
    attributes = self.form_instance._get_new_feature_attributes()

    # INFO: unstable in QGIS 3.22
    self.feature.setFields(self.layer.fields())
    for idx, field_name in enumerate(self.feature_fields_names):
        if field_name in attributes.keys():
            value = attributes[field_name]
            self.feature.setAttribute(idx, value)

    added_features = self.layer.dataProvider().addFeatures([self.feature])
    self.layer.triggerRepaint()

    self.logger.info('[CREATE] response from the data provider {}'.format(added_features))

    if added_features:
        self.form_instance.show_dialog('Éxito', 'Entidad creada con éxito')
    else:
        self.logger.error('Error commiting changes to feature {}'.format(self.feature_id))

    if added_features:
        self.disconnect_widgets()
        self.dialog.close()
```

- On **3.16.4** the code works seamlessly and the feature is added to the layer (with or without `self.feature.setFields(self.layer.fields())`).
- On **3.22.1** the program crashes on the line right after the comment `self.feature.setFields(self.layer.fields())`, it seems to be unable to access the feature or its fields. Without the line it crashes anyway right on the for loop.
- On **3.22.4** there are two scenarios:
  - Without the line `self.feature.setFields(self.layer.fields())` it throws a KeyError on the line `self.feature.setAttribute(idx, value)` like if the feature didn't have fields.
  - With the line `self.feature.setFields(self.layer.fields())` it throws exception unknown right on this line.

I suspect there's something wrong either with the feature or with the feature returned by *QgsMapToolDigitizeFeature* and passed to the controller (bit of code shown above).

When crashes in version **3.22.0** this is the stack trace:

QString::operator= :
QgsGeometry::QgsGeometry :
QgsFeature::deleteAttribute :
QgsFeature::setFields :
PyInit__core :
PyArg_ParseTuple_SizeT :
PyEval_EvalFrameDefault :
PyFunction_Vectorcall :
PyFloat_FromDouble :
PyVectorcall_Call :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QObject::qt_static_metacall :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
PyInit_QtWidgets :
QWidget::event :
PyInit_QtWidgets :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

### Steps to reproduce the issue

1. Creating a custom creation button
2. Instantiating a QgsMapToolDigitizeFeature
3. Passing the feature to a custom form class
4. Saving the feature directly to the data provider

### Versions

3.16.4, 3.22.0, 3.22.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

I tried with a new profile and it worked on version **3.22.0** (just created it no additional configuration).

All QGIS versions were for Windows.

**Comment by alexbruy** [comment]
Is this still an issue?
