### ISSUE TITLE
[ERROR] Can not make qgis.db private copy

### ISSUE THREAD

**Issue by wtrfilesx** [qgis/QGIS#46540]
### What is the bug or the crash?

h2. User Feedback

Every time the QGIS software is launched, receive an error message indicating "Can not make qgis.db private copy" and the program crashes.

h2. Report Details

*Crash ID*: 9dd447e8923a898061d2ea6718b134d43fc7e2b3

*Stack Trace*
<pre>
QList<QItemSelectionRange>::size :
QgsMessageBar::pushMessage :
QgsMessageBar::pushInfo :
QgisApp::showSystemNotification :
QgisApp::authMessageOut :
QMetaObject::activate :
QgsAuthManager::messageOut :
QgsAuthManager::authDatabaseConnection :
QgsAuthManager::sslCertCustomConfigByHost :
QgsNetworkAccessManager::createRequest :
QNetworkAccessManager::get :
QgsVectorLayerLoadStyleDialog::updateLoadButtonState :
QgsVectorLayerLoadStyleDialog::updateLoadButtonState :
QgisApp::QgisApp :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.4.4-Madeira
QGIS code revision: commit:73c31df831
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.0
Running against GDAL: 2.4.0

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Steps to reproduce the issue

Upon launching, asked to select whether or not I would like to import settings from QGIS 2. Regardless of the option selected, receive an error indicating "Can not make qgis.db private copy." Upon clicking OK, window pops up indicating that QGIS Crashed.
<img width="452" alt="Untitled" src="https://user-images.githubusercontent.com/96313861/146597411-8039ac8a-2e24-4d3f-a6cd-601d3c48d4c2.png">
<img width="535" alt="Untitled2" src="https://user-images.githubusercontent.com/96313861/146597430-9bcc8727-2308-4d07-bff1-897bc09e7d74.png">
.

### Versions

Unable to access the QGIS Help menu since the program will not load correctly. Software indicates QGIS Desktop 3.4.4

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
> QGIS Version: 3.4.4-Madeira

@wtrfilesx too old, and unsupported. Update to 3.16.14 or 3.22.1 and try again.
