### ISSUE TITLE
Osgeo4w: Python version in httpd.d\httpd_qgis.conf does not reflect current 3.9 version

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS#46558]
### What is the bug or the crash?

The example httpd_qgis.conf to be able to use qgis-mapserver easy with apache, does not reflect the current python state in osgeo4w

In httpd_qgis.conf Python37 is mentioned, while in osgeo4w Python39 is packaged.

### Steps to reproduce the issue

Using a vanilla Windows:

- install apache + mod_fcgi
- include httpd_qgis.conf
- you will get a fcgi error/500

Renaming all Python37 to Python39 (as THAT is the package I see in osgeo4w) fixes this.

Earlier the use of the (example conf file) made it a relative easy to start with QGIS in apache on Windows...
This seems an easy fix to make it work again.

### Versions

3.22

Note: I tried to find osgeo4w tracker, but https://trac.osgeo.org/osgeo4w/newticket was not working (I get a timeout when trying POST the ticket)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by jef-n** [comment]
downstream issue [OSGeo4W #711](https://trac.osgeo.org/osgeo4w/ticket/711)

**Comment by rduivenvoorde** [comment]
Thanks @jef-n !!
