### ISSUE TITLE
Adding virtual fields cripples form view

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#46557]
### What is the bug or the crash?

This is my starting point, on a geopackage:

![image](https://user-images.githubusercontent.com/1951107/146671493-9a23af73-b935-45f4-adbc-7b3f70f6e82d.png)

Now I add a virtual field, cloning the column "di", this how it shows in form view:

![image](https://user-images.githubusercontent.com/1951107/146671551-c10393de-22b1-4094-a891-984ecb0d1886.png)

And  if I add another virtual field:

![image](https://user-images.githubusercontent.com/1951107/146671570-290ff5e9-eaa6-49ed-b2c0-666c60920fdd.png)

This happens on 3.22.1 but not on 3.16.14, so regression.

### Steps to reproduce the issue

See above.

### Versions

3.22.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nirvn** [comment]
@gioman , can you attach a simple test project (a gpkg and a project file)?

**Comment by gioman** [comment]
> @gioman , can you attach a simple test project (a gpkg and a project file)?

@nirvn here it is

[sample.zip](https://github.com/qgis/QGIS/files/7740670/sample.zip)

**Comment by nirvn** [comment]
@gioman ,

![image](https://user-images.githubusercontent.com/1728657/146672615-d7e9609b-ab23-4538-9441-ed46fc02f5e2.png)

That's on QGIS master.

**Comment by nirvn** [comment]
I'm wondering if that's been "silently" fixed, can you try against QGIS master (or upcoming 3.22.2)?

**Comment by gioman** [comment]
> I'm wondering if that's been "silently" fixed, can you try against QGIS master (or upcoming 3.22.2)?

@nirvn true, updated with osgeo4w and problem is gone. Thanks for noticing.

**Comment by nirvn** [comment]
@3nids , I'm wondering whether this explains why I couldn't reproduce that issue of yours. It has been :magic_wand: fixed ;)

**Comment by nirvn** [comment]
@gioman , updated to 3.22.2 or master? If the latter, it'd still be important to check that 3.22.2 is also fixed.

**Comment by gioman** [comment]
@nirvn updated both, and tested on 3.22.2 too. So I guess we are good.

**Comment by domi4484** [comment]
@gioman it was introduced with #43900 and fixed with  #46267
