### ISSUE TITLE
When dragging a guide in a layout, cursor icon freezes if right mouse button is pressed before releasing left mouse button

### ISSUE THREAD

**Issue by GisUsers** [qgis/QGIS#46568]
### What is the bug or the crash?

While working on a layout and dragging a guide (from top or left ruler), if the right mouse button is pressed before releasing left mouse button the cursor icon freezes and does not revert back to normal pointer.

The only way to resolve the issue is to restart the software.

The issue only seems to affect Windows platform.
Tested on Windows 10 Pro (Version	10.0.19044 Build 19044) in:
QGIS 3.16.15
QGIS 3.22.2
QGIS 3.23.0-Master (6c93b2adfe)

The issue is NOT present on Fedora 35 in:
QGIS 3.23.0-Master (6a05593f82)

### Steps to reproduce the issue

1. Create a new layout
2. In the layout, drag a guide from the top (or left) ruler
3. Before releasing the left mouse button, press the right mouse button
4. Left-click elsewhere on the layout

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

QGIS version | 3.22.2-Białowieża | QGIS code revision | 1601ec46d0
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.4.0
PROJ version | 8.2.0
EPSG Registry database version | v10.038 (2021-10-21)
GEOS version | 3.10.0-CAPI-1.16.0
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.5
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Might be related to https://github.com/qgis/QGIS/issues/46233

**Comment by SebastienPeillet** [comment]
Confirmed with Ubuntu 21.04
