### ISSUE TITLE
configure which fields of a layer are shown in the identify results and which not

### ISSUE THREAD

**Issue by lindacamathias** [qgis/QGIS#46572]
### Feature description

it would be nice to have the possibility to configure which fields of a layer should be shown in identify results and  especially which not

### Additional context

![image](https://user-images.githubusercontent.com/77726342/146796880-7284e0c4-759f-4edb-8354-652639f8206c.png)

**Comment by jgrocha** [comment]
@lindacamathias Let us know more about your feature request.

- [ ] Have you tried to make the field **Hidden** (in the layer properties → attribute form)? Is this enough for your use case?
- [ ] You can choose to show your own form when the user uses the identify tool. Have you tried that? Is it suitable for you?

**Comment by lindacamathias** [comment]
well, it's just a nice to have, not really important in my current work .. but i remember having that option in arcgis and found it really useful back then.
The specific use case i have right now is that i've multiple overlapping polygons in one layer which i have to analyze. I want to gain a quick overview over the the data for which the identify tool is ok but could be improved. 
About your questions/suggestions: 
- I know i can hide a field in the attribute form via drag and drop designer. But it's still not hidden in the identifiy results.  
- if i choose "auto-open form for single feature results" (is it that what you meant ?) i get a result only when there's only one polygon, but there are often overlapping ones. 

that's a screenshot from the data  (not created nor designed by me), just for illustration purpose.
![image](https://user-images.githubusercontent.com/77726342/146816283-974f6b7b-9310-493d-98b7-9996eab2d078.png)

**Comment by jgrocha** [comment]
Even without creating a form, changing the Widget Type to **Hidden** should hide the field from the Identify Results.

![Screenshot from 2021-12-20 18-49-16](https://user-images.githubusercontent.com/163681/146817660-f2ae38d4-b905-4f48-835e-9b451a7de481.png)

**Comment by lindacamathias** [comment]
oh yes, that hidden widget type does the job! great, thanks!  

i think it would be worth making it findable more intuitively for everybody. for me personnally i would look for that in the layer properties section, in a new "theme" identify where fields can be made visible or not maybe ?

**Comment by jgrocha** [comment]
Thanks for the feedback @lindacamathias 

The feature request can be accomplished in QGIS, so I'll close this issue. 

Feel free to open another issue regarding the interface and usability issues that you have raised. Maybe it is better to discuss it on the mailing list before open another issue.
