### ISSUE TITLE
QGIS Crash when deleting Group or Lyer in Table of content with pyQGIS

### ISSUE THREAD

**Issue by wmeinolf** [qgis/QGIS#46576]
## User Feedback

Crash when deleting Group from TOC via pyqgis script in toolbox.

```
from qgis.core import QgsProcessing
from qgis.core import QgsProcessingParameterBoolean
from qgis.core import QgsProcessingAlgorithm
from qgis.core import QgsProcessingMultiStepFeedback
from qgis.core import QgsProject
from qgis.core import QgsLayerTreeGroup
import processing


class Test(QgsProcessingAlgorithm):

    def initAlgorithm(self, config=None):
        self.addParameter(QgsProcessingParameterBoolean('VERBOSE_LOG', 'Ausführliche Protokollierung', optional=True, defaultValue=False))

    def processAlgorithm(self, parameters, context, model_feedback):
        # Use a multi-step feedback, so that individual child algorithm progress reports are adjusted for the
        # overall progress through the model
        feedback = QgsProcessingMultiStepFeedback(10, model_feedback)
        results = {}
        outputs = {}


########### Layer Im TOC sortieren

        root = QgsProject.instance().layerTreeRoot()

        # Insert Group

        ftthgruppeTemp = root.addGroup("Group")
        
        # clone the group
        ftthgruppe = ftthgruppeTemp.clone()
        # move the node (along with sub-groups and layers) to the top
        root.insertChildNode(0, ftthgruppe)
        # remove the original node
        root.removeChildNode(ftthgruppeTemp)

        return results

    def name(self):
        return 'Layer Move Test 2'

    def displayName(self):
        return 'Layer Move Test 2'

    def group(self):
        return 'Test'

    def groupId(self):
        return 'Test'

    def createInstance(self):
        return Test()
```

## Report Details

**Crash ID**: [78182cf1f9b886a057f5b2f13ea679004d6b97e7](https://github.com/qgis/QGIS/search?q=78182cf1f9b886a057f5b2f13ea679004d6b97e7&type=Issues)

**Stack Trace**
<pre>
QgsLayerCapabilitiesModel::toggleSelectedItems :
QMetaCallEvent::placeMetaCall :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
PyInit_QtWidgets :
PyArg_ParseTuple_SizeT :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyFunction_Vectorcall :
PyFloat_FromDouble :
PyVectorcall_Call :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QObject::qt_static_metacall :
QAbstractItemView::doubleClicked :
QTreeView::mouseDoubleClickEvent :
PyInit__gui :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
PyInit__gui :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.22.2-Bia?owie?a
QGIS code revision: 1601ec46d0
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.0
Running against GDAL: 3.4.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Steps to reproduce the issue

(1) Create temporary Layer
(2) Start attached script from processing tool box

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS-Version | 3.22.2-Białowieża | QGIS-Codeversion | 1601ec46d0
-- | -- | -- | --
Qt-Version | 5.15.2
Python-Version | 3.9.5
GDAL-Version | 3.4.0
PROJ-Version | 8.2.0
EPSG-Registraturdatenbankversion | v10.038 (2021-10-21)
GEOS-Version | 3.10.0-CAPI-1.16.0
SQLite-Version | 3.35.2
PDAL-Versio | 2.3.0
PostgreSQL-Client-Version | 13.0
SpatiaLite-Version | 5.0.1
QWT-Version | 6.1.3
QScintilla2-Version | 2.11.5
BS-Version | Windows 10 Version 2009
  |   |   |  
Aktive Python-Erweiterungen
disconnected-islands | 2.0.2
GeoCoding | 2.18
lizmap | 3.6.5
mmqgis | 2021.9.10
ORStools | 1.5.0
Qgis2threejs | 2.6
QuickOSM | 2.0.0
quick_map_services | 0.19.27
refFunctions | 1.6
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.5
processing | 2.12.99

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

[Group Move Test.zip](https://github.com/qgis/QGIS/files/7748074/Group.Move.Test.zip)

**Comment by wmeinolf** [comment]
Forgot to mention, that it also with new profile crash

**Comment by Djedouas** [comment]
The default behavior of a QGIS processing is to be executed in his own thread, so it does not block the GUI while it runs.

Your algorithm is not thread-safe because it plays with the GUI (removing a group from the TOC) which is in the main thread.

To avoid the crash, you need to use the [`FlagNoThreading`](https://qgis.org/api/classQgsProcessingAlgorithm.html#a6a8c21fab75e03f50f45e41a9d67dbc3a229dea6cedf8c59132196dee09d4f2f6) flag of `QgsProcessingAlgorithm`:


>Algorithm is not thread safe and cannot be run in a background thread, e.g. for algorithms which manipulate the current project, layer selections, or with external dependencies which are not thread-safe. 

---

So in your class you must add this method so that your algorithm has the `FlagNoThreading` flag:

```python
def flags(self):
    return super().flags() | QgsProcessingAlgorithm.FlagNoThreading
```

Tested with QGIS 3.22, no crash.

**Comment by wmeinolf** [comment]
@Djedouas : Thanks for the explanation, I was not aware of that. 

I inserted the method. The close button dissapeared, so it cant put in background. I can confirm, no crash with 3.22.


Thanks a lot!
