### ISSUE TITLE
Unable to use or see processing tool 

### ISSUE THREAD

**Issue by SnehalSadalage** [qgis/QGIS#46581]
### What is the bug or the crash?

Crash ID: 8e87fe8952ed15a98f798cfa6a8d6fd2712d145b

Stack Trace

QgsProcessingRegistry::removeProvider :
QgsProcessingRegistry::~QgsProcessingRegistry :
QgsProcessingParameterTypeString::operator= :
QgsValidityCheckResult::QgsValidityCheckResult :
QgsApplication::~QgsApplication :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.18.1-Z�rich
QGIS code revision: 202f1bf7e5
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22000

### Steps to reproduce the issue

updated my system to windows 11

### Versions

3.18.1

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by Gustry** [comment]
You must try with a new QGIS Profile and upgrade your QGIS version.
It looks like coming from a plugin.

**Comment by gioman** [comment]
> QGIS Version: 3.18.1-Z�rich

@SnehalSadalage and update to a supported version.
