### ISSUE TITLE
cbbdf4dc1d1c76df53148e01cc03c42d5832a57c

### ISSUE THREAD

**Issue by Sheigt** [qgis/QGIS#46589]
### What is the bug or the crash?

cbbdf4dc1d1c76df53148e01cc03c42d5832a57c

### Steps to reproduce the issue

sudden loss

### Versions

3.22

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by DelazJ** [comment]
@Sheigt There's nothing devs can do with such a report. You need to explain what you were doing when QGIS crashes, paste the full stack trace, indicate the operating system... Please read correctly the instructions and fill them.

**Comment by gioman** [comment]
Reopen when details are added and the title edited.
