### ISSUE TITLE
QGIS doesn't open my QGZ anymore, CRC-Error?

### ISSUE THREAD

**Issue by uluku** [qgis/QGIS#46584]
### What is the bug or the crash?

since a couple of months i work on a project in QGIS 3.16.13 with win 10. All my data is storaged on a flashdrive.

Since yesterday when i try to open my project suddenly i receive this error message:

"cannot read unzipped qgs project"

I also cant open my QGZ file with a text editor. When i try to unzip it i get a Crc-Error, with "tag-mismatch". As well doesn't work to repair my archive with 7-zip or winrar.

actually its a very frustrating situation for me. it would so helpful if someone can share informations to repair my QGZ.

### Steps to reproduce the issue

![grafik](https://user-images.githubusercontent.com/96499104/146994794-4850bac3-eef5-43f7-ae03-c0c4215e43d5.png)

### Versions

3.16.13

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
@uluku this is not a QGIS bug, as we discussed on Telegram. Your QGZ file is corrupted. I tried to repair it, and something come out, but the QGS file within the QGZ is truncated, and likely useless.
