### ISSUE TITLE
Vector tile sprites sometimes missing

### ISSUE THREAD

**Issue by blacha** [qgis/QGIS#46587]
### What is the bug or the crash?

When importing a vector style containing sprites with a `maxzoom` filter they do not appear in QGIS.

### Steps to reproduce the issue

Expected output using maplibre 
![image](https://user-images.githubusercontent.com/1082761/147006626-0f26ea17-6b72-4a6a-82fc-089b87072cdc.png)
https://basemaps.linz.govt.nz/?s=topographic&i=topographic#@-41.3333194,174.8111000,z15.4554

QGIS output 
![image](https://user-images.githubusercontent.com/1082761/147006639-0da5e229-df91-4dde-bddf-a4e6d0269175.png)

Vector tiles:
https://basemaps.linz.govt.nz/v1/tiles/topographic/EPSG:3857/{z}/{x}/{y}.pbf?api=d01fn790hgwf9w552d462epyste

Style Json

https://basemaps.linz.govt.nz/v1/tiles/topographic/EPSG:3857/style/topographic.json?api=d01fn790hgwf9w552d462epyste

### Versions

QGIS version | 3.22.1-Białowieża | QGIS code revision | 663dcf8fb9
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.7
GDAL/OGR version | 3.2.2
PROJ version | 7.2.1
EPSG Registry database version | v10.008 (2020-12-16)
GEOS version | 3.9.0-CAPI-1.16.2
SQLite version | 3.35.5
PDAL version | 2.2.0
PostgreSQL client version | 13.5 (Ubuntu 13.5-0ubuntu0.21.10.1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 21.10
  |   |   |  
Active Python plugins
TerrainShading | 0.9
qgis-maptiler-plugin | 1.1.4
profiletool | 4.1.8
track_profile_2_web | 1.3
db_manager | 0.1.20
sagaprovider | 2.12.99
grassprovider | 2.12.99
MetaSearch | 0.3.5
processing | 2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by blacha** [comment]
I have a few (around 5) other minor rendering differences between mapbox and QGIS, wondering how/if you want them reported, Is this format ok?

**Comment by nyalldawson** [comment]
> Is this format ok?

Yes please

**Comment by nyalldawson** [comment]
Is this a valid style?

The relevant rule is:

```
{
      "filter": [
        "all",
        [
          "==",
          "class",
          "grass"
        ],
        [
          "==",
          "grass_type",
          "golf_course"
        ]
      ],
      "layout": {
        "icon-rotation-alignment": "viewport",
        "icon-pitch-alignment": "viewport",
        "visibility": "visible",
        "text-field": "{name}",
        "text-size": 9,
        "text-anchor": "left",
        "icon-size": 1.2,
        "icon-image": "golf_course_pnt_dual",
        "text-font": [
          "Open Sans Italic"
        ],
        "text-justify": "left",
        "text-max-width": 6,
        "text-offset": [
          0.5,
          0
        ],
        "icon-anchor": "right"
      },
      "maxzoom": 20,
      "paint": {
        "text-halo-blur": 0.5,
        "text-color": "rgba(27, 77, 29, 1)",
        "text-halo-color": "rgba(255, 255, 255, 1)",
        "text-halo-width": 1.5
      },
      "id": "Landcover-GolfCourse-Symbol",
      "source": "LINZ Basemaps",
      "source-layer": "landcover",
      "type": "symbol",
      "minzoom": 12
    }
```

i.e. a symbol type graphic. However the matching features in the tiles are polygons, so we're trying to draw a polygon using a point marker symbol... which is illegal in QGIS.

Looking at the mapbox specs I'm not sure this is officially supported at all. From https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#symbol:

"A symbol style layer renders icon and text labels at points or along lines on a map"

There's no mention there of symbols being usable for polygon features at all.

"

**Comment by nyalldawson** [comment]
Hmm... those mapbox specs are ambiguous at best!

It's never stated explicitly in https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#layout-symbol-symbol-placement, but given that the "Line" and "Line-Center" options DO state " Can only be used on LineString and Polygon geometries" then it would imply that "Point" placement can be used with any geometry type! Then the question is what does "The label is placed at the point where the geometry is located" **actually** mean for a polygon? :upside_down_face: (I'm assuming centroid)

**Comment by blacha** [comment]
> Hmm... those mapbox specs are ambiguous at best!
> 
> It's never stated explicitly in https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#layout-symbol-symbol-placement, but given that the "Line" and "Line-Center" options DO state " Can only be used on LineString and Polygon geometries" then it would imply that "Point" placement can be used with any geometry type! Then the question is what does "The label is placed at the point where the geometry is located" **actually** mean for a polygon? upside_down_face (I'm assuming centroid)

Ahh that could actually explain a few rendering issues we have had we label placement inside of maplibre, I did not know its not a intended use case to add a symbol for a polygon.

Looking at a few zoom scales with tile outlines it looks approx centeroid per tile? 

z17
![image](https://user-images.githubusercontent.com/1082761/147011505-d0fa55b9-c11e-45d4-bffb-bc7816058b63.png)

z15
![image](https://user-images.githubusercontent.com/1082761/147011523-207fee78-d691-42c5-868e-db6b343f87b2.png)


I will follow up with the creators of this stylejson (I'm just reporting the issues they have told me about)

**Comment by nyalldawson** [comment]
> Looking at a few zoom scales with tile outlines it looks approx centeroid per tile?

I agree -- that's what I've done in https://github.com/qgis/QGIS/pull/46590. That PR fixes both the missing icon and the missing label.

**Comment by pathmapper** [comment]
Some background in https://github.com/qgis/QGIS/pull/46590#issuecomment-999300246.

> Is this a valid style?

To validate a style there's `gl-style-validate` from

https://www.npmjs.com/package/@mapbox/mapbox-gl-style-spec
or
https://www.npmjs.com/package/@maplibre/maplibre-gl-style-spec

**Comment by blacha** [comment]
> Some background in [#46590 (comment)](https://github.com/qgis/QGIS/pull/46590#issuecomment-999300246).
> 
> > Is this a valid style?
> 
> To validate a style there's `gl-style-validate` from
> 
> https://www.npmjs.com/package/@mapbox/mapbox-gl-style-spec or https://www.npmjs.com/package/@maplibre/maplibre-gl-style-spec


Thanks! I did not know that tool existed.

The latest mapbox version of it is broken https://github.com/mapbox/mapbox-gl-js/issues/10965

Installing v13.18 then validating the style json returns no errors. No errors are returned with the maplibre version either
