### ISSUE TITLE
Append style name when saving multiple styles, instead of a meaningless numbering

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#46597]
### What is the bug or the crash?

I tend to use multiple styles in a vector layer, and I tend to provide them with a meaningful name.
When you save several styles at once from a vector layer dialog to eg QML, files are generated with a numerical suffix _1, _2, ... that does not help anyhow to know what is stored where.
I would expect the output files to instead be appended with the style name.

### Steps to reproduce the issue

1. Open a vector layer properties and create and name different styles
2. From the style menu, click the "Save all styles" button (you'd probably need to close/reopen the dialog to have it appear - see #46596) 
3. Fill in the necessary information (let's say filename=region.qml)
4. Press OK
1. You get in the output folder files such as region.qml, region_1.qml, region_2.qml... Try to guess which output corresponds to any of your created style without opening the files.

Instead of numbering, I suggest to append the style name to the output file, that is eg region_popsize.qml, region_admlevel, ...

### Versions

Tested on 3.22+ (but I think it has always been so)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by AlisterH** [comment]
Readers of this ticket may wish to try the "GeoPRoc.com PRocessing Algorithms" plugin from the repository at https://www.geoproc.com/be/plugins.xml
