### ISSUE TITLE
QGIS crashes when Polygon-Layer symbolized  with marker line 

### ISSUE THREAD

**Issue by claasleiner** [qgis/QGIS#46604]
### What is the bug or the crash?

In addition to the error (# 46147):
QGIS crashes immediately when a polygon layer is symbolized with a marker line. 
The problem persists in qgis 3.16.15.
A polygon layer that is symbolized with a marking line causes QGIS to crash immediately. This is a serious problem because the marker lines are an important symbology tool.
Claas Leiner

### Steps to reproduce the issue

Load an Polygon-Layer
symbolize Polygon as Marker-Line
zoom out and in:
QGIS crashed

### Versions

QGIS 3.16.15 with ubuntugus dependencies (Linux XUbuntu 20.04)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
Confirmed also on Windows, no crash on 3.22.2

**Comment by roya0045** [comment]
So it's specific to 3.16?

**Comment by gioman** [comment]
> So it's specific to 3.16?

@roya0045 apparently.

**Comment by rhurlin** [comment]
Hmm, I tried to reproduce the error with QGIS 3.16.15 on FreeBSD [1]. It looks like the described error does not occur here.

If more information about the context on FreeBSD (Qt version, etc.) is needed, please ask. I am also happy to do some testing.

[1] https://www.freshports.org/graphics/qgis-ltr

**Comment by claasleiner** [comment]
There is Geopackage with Marker-Line-Style, that crashes qgis
[marker_line.zip](https://github.com/qgis/QGIS/files/7768052/marker_line.zip)

**Comment by rhurlin** [comment]
> There is Geopackage with Marker-Line-Style, that crashes qgis [marker_line.zip](https://github.com/qgis/QGIS/files/7768052/marker_line.zip)

Hi @claasleiner,
Thanks for the test data. I loaded the geopackage data into QGIS 3.16.15 on FreeBSD, then loaded the `marker_line_test style` and then repeatedly zoomed in and out and moved the section. So far everything works fine with LTR on my box.
