### ISSUE TITLE
QGIS crashing on macOS when a shapefile is encoded with ISO-8859-1 rather than UTF-8

### ISSUE THREAD

**Issue by afitzgerrell** [qgis/QGIS#46620]
### What is the bug or the crash?

When adding a shapefile which, in troubleshooting, I noticed had ISO-8859-1 encoding to QGIS Hannover v.3.16.15, it crashes immediately. This happens regardless of dragging and dropping the .shp file or adding it via the Data Source Manager. I tried in the Data Source Manager changing encoding from Automatic to UTF-8, but upon clicking Add the crash is immediate. 

I was able to successfully add the shapefile to QGIS A Coruña v3.10.11 without issue, and that's where looking at the shapefile's properties I noticed the encoding varied from other shapefiles I had that opened fine in Hannover. To test that the encoding was the root, or seemingly the root of the crashing, from A Coruña I exported the shapefile, setting the encoding to UTF-8, to a new shapefile. With the shapefile now encoded at UTF-8, I was able to pop it into Hannover on my mac without issue.

I work on a MacBook Pro, Intel: macOS Big Sur at v11.6.2.
I checked and on my windows VM, I'm able to add the shapefile to Hannover without issue, so this seems to be a macOS specific issue.
![encoding_ISO-8859-1_not_UTF-8](https://user-images.githubusercontent.com/8062694/147258231-24dca70e-56e1-4001-a776-146ea69a8a18.png)

### Steps to reproduce the issue

Open a new, empty install of QGIS Hannover v.3.16.15 and either drag and drop or click the Open Data Source Manager button and add the HMA GlacierAvg shapefile (attached as HMA_GlacierAvg_dH_GeodeticMassBalance_Himalayas_2000-2016.zip). Blink and GGIS will no longer be running. 

In case it's helpful, I've also attached the same shapefile but exported and saved with UTF-8 encoding (HMA_exported_to_UTF-8.zip).

[HMA_GlacierAvg_dH_GeodeticMassBalance_Himalayas_2000-2016.zip](https://github.com/qgis/QGIS/files/7770030/HMA_GlacierAvg_dH_GeodeticMassBalance_Himalayas_2000-2016.zip)
[HMA_exported_to_UTF-8.zip](https://github.com/qgis/QGIS/files/7770067/HMA_exported_to_UTF-8.zip)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.16.15-Hannover | QGIS code revision | e7fdad6431
-- | -- | -- | --
Compiled against Qt | 5.14.2 | Running against Qt | 5.14.2
Compiled against GDAL/OGR | 3.2.1 | Running against GDAL/OGR | 3.2.1
Compiled against GEOS | 3.9.1-CAPI-1.14.2 | Running against GEOS | 3.9.1-CAPI-1.14.2
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.4
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | macOS 11.6
Active python plugins | pointsamplingtool; processing; db_manager; MetaSearch

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by afitzgerrell** [comment]
I also heard from a coworker who works on a Windows machine that she just updated to 3.16.15 and adding the HMA_GlacierAvg_dH_GeodeticMassBalance_Himalayas_2000-2016.shp crashes qgis right out of the gates.

I've attached images of the Windows VM I access where adding the shapefile does _not_ crash qgis as well as my coworker's Windows details where qgis does crash with that shapefile.

<img width="597" alt="my coworker's Windows OS details" src="https://user-images.githubusercontent.com/8062694/147265144-cba57ba3-f79d-46ee-a51c-6f6e8d225639.png">

![my WindowsVM details](https://user-images.githubusercontent.com/8062694/147265146-7d7370ed-2863-44fd-9b16-52b76547c383.png)

**Comment by gioman** [comment]
> and adding the HMA_GlacierAvg_dH_GeodeticMassBalance_Himalayas_2000-2016.shp crashes qgis right out of the gates.

@afitzgerrell I cannot confirm here on Win10 and Linux. Will test on macOS tomorrow.

**Comment by afitzgerrell** [comment]
Hi,
Per the bot notice, I may have misunderstood , but my perception was that I'm awaiting feedback on developer testing this issue in macOS. I am quite interested in pursuing a fix for macOS if warranted, if possible.

**Comment by gioman** [comment]
> Hi,
> Per the bot notice, I may have misunderstood , but my perception was that I'm awaiting feedback on developer testing this issue in macOS. I am quite interested in pursuing a fix for macOS if warranted, if possible.

@afitzgerrell I forgot to test this on macOS, will do it later today.

**Comment by gioman** [comment]
@afitzgerrell confirmed on 3.16.15 but ok on 3.22.2

**Comment by afitzgerrell** [comment]
Thank you, @gioman !! Just at the moment I'm not able to connect to the main QGIS site to download 3.22.2, but as soon as I can, I'll verify that this is no longer an issue.

I apologize for the lengthy gap until my response. I'd missed seeing your comment until today.

**Comment by afitzgerrell** [comment]
I've verified that I can now add our HMA files (encoded with ISO-8859-1 rather than UTF-8) to QGIS at 3.22.2 without causing it to crash.  Thank you for your help!!
