### ISSUE TITLE
Layers are shifted in print composer when masking is enabled

### ISSUE THREAD

**Issue by ShenLY00** [qgis/QGIS#46626]
### What is the bug or the crash?

Grids in layout view will have scale errors when the line mask is enabled

### Steps to reproduce the issue

Grids in layout view will have scale errors when the line mask is enabled

### Versions

3.22

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@ShenLY00 other than the title and QGIS version this report lacks all the other mandatory infos, please add them.

**Comment by ShenLY00** [comment]
If the line is masked, the position and scale of the grid in the layout view will be wrong.
![QQ截图20211224151245](https://user-images.githubusercontent.com/96603656/147328675-afd86452-7ef9-4eda-8216-da48d5dee90f.jpg)

**Comment by ShenLY00** [comment]
Sorry, my English is not very good. I don't know if I have express it clearly.

**Comment by lieti** [comment]
I can confirm that bug. On different PC, with different version of QGIS 3.22.x, with/wihout blank profile, everything on WIN10.
Sample data and project with screenshots of error are on [this ](https://drive.google.com/file/d/1blxPIclm2BuQz5NUmM9XMBiXahZoOHRj/view?usp=sharing)link (5 MB).

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>


QGIS version | 3.22.2-Białowieża | QGIS code revision | 1601ec46d0
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.4.0
PROJ version | 8.2.0
EPSG Registry database version | v10.038 (2021-10-21)
GEOS version | 3.10.0-CAPI-1.16.0
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
changeDataSource | 3.1
czech_slovak_freegeodata | 0.4
latlontools | 3.5.9
mapswipetool_plugin | 1.2
Mergin | 2021.4.2
nominatim | 1.4.1
qgis-maptiler-plugin | 2.0.0
QRectangleCreator | 0.3
send2google_earth | 0.3.1
processing | 2.12.99

</body></html>

**Comment by lieti** [comment]
Exports from map composer seems OK.
![pokus](https://user-images.githubusercontent.com/34206797/147416087-0b8db38d-f37b-4dad-8bc5-8f5482ac79a9.jpg)


But it is hard to make any map composition with that shift in map composer.

**Comment by gioman** [comment]
It is ok on 3.16 and earlier, so it seems a regression.

**Comment by uclaros** [comment]
Could you check if it is the same as  #44426?

**Comment by gioman** [comment]
> Could you check if it is the same as #44426?

@uclaros yes it is, thanks for the heads up. I guess that is already fixed then.
