### ISSUE TITLE
Problem of inserting an .mnt file in qjis 3.22

### ISSUE THREAD

**Issue by Yannyl85** [qgis/QGIS#46622]
### Feature description

Hi support,

I want to put my *RAF20.mnt* ( in attachment) in QJIS 3.22 of my customer who use W11 but i have an error message and it doesn't work.
When i use QJIS 3.10 on my computer in W10, i have no problem.

The RAF20.mnt file is a notepad file where I copy the geoid data provided by IGN and whose extension I change to .mnt.
QJIS correctly retrieves the data except at my client's. I think it's due to W11. What can you do ? 

Can you help me?

Thank you for your anwser

Regards
[RAF20.txt](https://github.com/qgis/QGIS/files/7770311/RAF20.txt)
,

**Comment by gioman** [comment]
@Yannyl85 Hi, is QGIS not QJIS.





> When i use QJIS 3.10 on my computer in W10, i have no problem.

QGIS 3.10 used older version of the GDAL/OGR library. In newer versions of this library a number of drivers have been removed. This is likely the explanation of what you are seeing.

See here https://gdal.org/drivers/raster/index.html

"The following drivers have been retired and moved to the https://github.com/OSGeo/gdal-extra-drivers repository: BPG, E00GRID, EPSILON, IGNFHeightASCIIGrid, NTv1"

and also https://lists.osgeo.org/pipermail/gdal-dev/2021-January/053260.html
