### ISSUE TITLE
QGIS is blocking OpenShot video editor launching

### ISSUE THREAD

**Issue by mix-vl** [qgis/QGIS#46633]
### What is the bug or the crash?

QGIS creates a segmentation fault for OpenShot video editor
[1.txt](https://github.com/qgis/QGIS/files/7776696/1.txt)

### Steps to reproduce the issue

When QGIS is installed, OpenShot does not launching. A  segmentation fault occurs. 

### Versions

QGIS 3.18.3

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

system -  AltLinux 9.1 x32 bit / AltLinux 9.2 x64 bit

**Comment by jef-n** [comment]
Looks like a packaging issue on AltLinux.    Is `/usr/lib64/python3/site-packages/qgis` in PYTHONPATH?   But we don't ship packages for AltLinux and 3.18 is EOL anyway. 3.16 (LTR) and 3.22 are supported.
