### ISSUE TITLE
QGIS crashing on Windows when generating MBTiles (feedback)

### ISSUE THREAD

**Issue by jarraunfot** [qgis/QGIS#46636]
### What is the bug or the crash?

Generating MBTiles, 10% in 24 h. Not posible to cancel the task, when closing QGis crashes.

Report
## User Feedback

Crash ID: 42735c438bb9e98f3520e762ed64aaf28eb581bf

Stack Trace

PyFunction_Vectorcall :
PyVectorcall_Call :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QObject::qt_static_metacall :
QgsProcessingAlgRunnerTask::executed :
QgsProcessingAlgRunnerTask::finished :
PyInit__core :
QgsTaskManager::taskStatusChanged :
QObject::qt_static_metacall :
QgsTask::statusChanged :
QgsTask::processSubTasksForTermination :
QObject::event :
PyInit__core :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.22.2-Bia?owie?a
QGIS code revision: 1601ec46d0
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.0
Running against GDAL: 3.4.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

Generating MBTiles, 10% in 24 h. Not posible to canael the task 

## Report Details

**Crash ID**: [42735c438bb9e98f3520e762ed64aaf28eb581bf](https://github.com/qgis/QGIS/search?q=42735c438bb9e98f3520e762ed64aaf28eb581bf&type=Issues)

**Stack Trace**
<pre>
PyFunction_Vectorcall :
PyVectorcall_Call :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QObject::qt_static_metacall :
QgsProcessingAlgRunnerTask::executed :
QgsProcessingAlgRunnerTask::finished :
PyInit__core :
QgsTaskManager::taskStatusChanged :
QObject::qt_static_metacall :
QgsTask::statusChanged :
QgsTask::processSubTasksForTermination :
QObject::event :
PyInit__core :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.22.2-Bia?owie?a
QGIS code revision: 1601ec46d0
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.0
Running against GDAL: 3.4.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

## User Feedback

Crash ID: 42735c438bb9e98f3520e762ed64aaf28eb581bf

Stack Trace

PyFunction_Vectorcall :
PyVectorcall_Call :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QObject::qt_static_metacall :
QgsProcessingAlgRunnerTask::executed :
QgsProcessingAlgRunnerTask::finished :
PyInit__core :
QgsTaskManager::taskStatusChanged :
QObject::qt_static_metacall :
QgsTask::statusChanged :
QgsTask::processSubTasksForTermination :
QObject::event :
PyInit__core :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.22.2-Bia?owie?a
QGIS code revision: 1601ec46d0
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.0
Running against GDAL: 3.4.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

Generating MBTiles, 10% in 24 h. Not posible to canael the task 

## Report Details

**Crash ID**: [42735c438bb9e98f3520e762ed64aaf28eb581bf](https://github.com/qgis/QGIS/search?q=42735c438bb9e98f3520e762ed64aaf28eb581bf&type=Issues)

**Stack Trace**
<pre>
PyFunction_Vectorcall :
PyVectorcall_Call :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QObject::qt_static_metacall :
QgsProcessingAlgRunnerTask::executed :
QgsProcessingAlgRunnerTask::finished :
PyInit__core :
QgsTaskManager::taskStatusChanged :
QObject::qt_static_metacall :
QgsTask::statusChanged :
QgsTask::processSubTasksForTermination :
QObject::event :
PyInit__core :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.22.2-Bia?owie?a
QGIS code revision: 1601ec46d0
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.0
Running against GDAL: 3.4.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

### Versions

QGIS Version: 3.22.2-Bia?owie?a

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@jarraunfot you must be more specific: what tool you are using? what extent? what levels? what format?
