### ISSUE TITLE
"Couldn't load SIP module. Python support will be disabled."

### ISSUE THREAD

**Issue by CoryAlbrecht** [qgis/QGIS#46630]
### What is the bug or the crash?

This window appears when starting QGIS, no plugins get loaded
```
Couldn't load SIP module.
Python support will be disabled.


Traceback (most recent call last):
  File "", line 1, in 
  File "/usr/lib/python3/dist-packages/qgis/__init__.py", line 78, in 
    from qgis.PyQt import QtCore
  File "/usr/lib/python3/dist-packages/qgis/PyQt/QtCore.py", line 24, in 
    from PyQt5.QtCore import *
ImportError: /lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by /home/cory/.local/lib/python3.8/site-packages/PyQt5/QtCore.abi3.so)


Python version:
3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0]

QGIS version:
3.22.1-Białowieża 'Białowieża', bb2df7203b

Python path:
['/usr/share/qgis/python', '/home/cory/.local/share/QGIS/QGIS3/profiles/default/python', '/home/cory/.local/share/QGIS/QGIS3/profiles/default/python/plugins', '/usr/share/qgis/python/plugins', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/home/cory/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3.8/dist-packages']
```

### Steps to reproduce the issue

1. Start QGIS.

That's all.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.1-Białowieża | QGIS code revision | bb2df7203b
-- | -- | -- | --
Qt version | 5.12.8
Python version | 3.8.10
GDAL/OGR version | 3.0.4
PROJ version | 6.3.1
EPSG Registry database version | v9.8.6 (2020-01-22)
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
SQLite version | 3.31.1
PDAL version | 2.0.1
PostgreSQL client version | 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.2
OS version | Ubuntu 20.04.3 LTS
  |   |   |  
This copy of QGIS writes debugging output.
  |   |   |  

</body></html>     

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
> Start QGIS.

@CoryAlbrecht this is not a general QGIS issue. How have you installed QGIS on Ubuntu? are you  using QGIS.org's repos? With or without Ubuntugis? have you tried removing all qgis related packages and re-install them again?

**Comment by nicogodet** [comment]
Qt version	5.12.8

Too old for QGIS 3.22

**Comment by DelazJ** [comment]
> Qt version 5.12.8
>
> Too old for QGIS 3.22

@nicogodet You sure? The [Readme](https://github.com/qgis/QGIS/blob/master/INSTALL.md#2-overview)  does not state that. And on my self-compiled versions on Ubuntu 20.04, I never made a particular change to dependencies so assume they use the distribution version.
@CoryAlbrecht might have done something particular (in relation with his thread about missing versions in the website?) that he'd need to find out and explain to help crash reproduction.

**Comment by nicogodet** [comment]
@DelazJ I had issues with old Qt version and SIP but it might be unrelated here indeed.

**Comment by jef-n** [comment]
>   File "/usr/lib/python3/dist-packages/qgis/PyQt/QtCore.py", line 24, in 
>     from PyQt5.QtCore import *
> ImportError: /lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by /home/cory/.local/lib/python3.8/site-packages/PyQt5/QtCore.abi3.so)

Your private PyQt5's Qt install apparently conflicts with the installed system Qt.

**Comment by CoryAlbrecht** [comment]
@gioman I use QGIS's repos to install QGIS. Currently using:

```
deb [arch=amd64] http://qgis.org/ubuntu-nightly-release focal main
deb-src [arch=amd64] http://qgis.org/ubuntu-nightly-release focal main
```

And yes, I have tried removing QGIS, using apt purge, and reinstalling.

**Comment by CoryAlbrecht** [comment]
@jef-n 

> > File "/usr/lib/python3/dist-packages/qgis/PyQt/QtCore.py", line 24, in
> > from PyQt5.QtCore import *
> > ImportError: /lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by /home/cory/.local/lib/python3.8/site-packages/PyQt5/QtCore.abi3.so)
> 
> Your private PyQt5's Qt install apparently conflicts with the installed system Qt.

I am not a proficient Python user, so any new modules would have to have been installed by some app, like how QGIS does. I don't use pip to add new modules myself. Can pip tell me what it was that installed the different version?

Also, I believe that like Perl or NodeJS, Python allows you to have multiple module versions on the system and to specify which one to load, yes? Would it be appropriate

**Comment by jef-n** [comment]
> Can pip tell me what it was that installed the different version?

Not that I know.   Maybe is was a plugin you installed. Some try to install dependencies they need - and that might miss conflicts like this.  You should identify the plugin and report the issue there.
