### ISSUE TITLE
Crash: QGIS unexpectedly ended .

### ISSUE THREAD

**Issue by houssemtebibi** [qgis/QGIS#46669]
## User Feedback

Crash ID: 3ff61dcbf140a7041dd888836ffc24951465e64e

Stack Trace

VSIFCloseL :
IOGREditableLayerSynchronizer::IOGREditableLayerSynchronizer :
IOGREditableLayerSynchronizer::IOGREditableLayerSynchronizer :
IOGREditableLayerSynchronizer::IOGREditableLayerSynchronizer :
OGREditableLayer::SyncToDisk :
QgsOgrProviderUtils::setSubsetString :
QgsOgrProviderUtils::databaseDrivers :
QgsVectorLayerEditBuffer::commitChanges :
QgsVectorLayer::commitChanges :
QgisApp::toggleEditing :
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.18.0-Z�rich
QGIS code revision: bdef9fb328
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

## Report Details

**Crash ID**: [3ff61dcbf140a7041dd888836ffc24951465e64e](https://github.com/qgis/QGIS/search?q=3ff61dcbf140a7041dd888836ffc24951465e64e&type=Issues)

**Stack Trace**
<pre>
VSIFCloseL :
IOGREditableLayerSynchronizer::IOGREditableLayerSynchronizer :
IOGREditableLayerSynchronizer::IOGREditableLayerSynchronizer :
IOGREditableLayerSynchronizer::IOGREditableLayerSynchronizer :
OGREditableLayer::SyncToDisk :
QgsOgrProviderUtils::setSubsetString :
QgsOgrProviderUtils::databaseDrivers :
QgsVectorLayerEditBuffer::commitChanges :
QgsVectorLayer::commitChanges :
QgisApp::toggleEditing :
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.18.0-Z�rich
QGIS code revision: bdef9fb328
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

### Steps to reproduce the issue

Go to 'Attribute Table '
Click on 'Edit table'
Scroll down to 'Save '
See error

### Versions

 3.18.0

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
3.18.0 is EOL
Upgrade to 3.22
