### ISSUE TITLE
Vector Import specific to .GEN files fails to load

### ISSUE THREAD

**Issue by mikeshasko** [qgis/QGIS#46660]
### What is the bug or the crash?

The ESRI .GEN (Ascii vector files) returns a failed to load message under qGIS 3.2.2 (Win 10 Enterprise)

The same file works fine under qGIS 2.18.9 (Win 7 Pro)

### Steps to reproduce the issue

Add vector file

### Versions

QGIS version
3.22.2-Białowieża
QGIS code revision
1601ec46d0
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.0
PROJ version
8.2.0
EPSG Registry database version
v10.038 (2021-10-21)
GEOS version
3.10.0-CAPI-1.16.0
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
@mikeshasko please attach a sample.

**Comment by mikeshasko** [comment]
@gioman 

Vector GEN format.

Rename the .txt to .gen

[F027_10000_UniquePaths.txt](https://github.com/qgis/QGIS/files/7805143/F027_10000_UniquePaths.txt)

**Comment by gioman** [comment]
@mikeshasko 

```
ogrinfo -so F027_10000_UniquePaths.gen
ERROR 1: Driver ARCGEN is considered for removal in GDAL 3.5. You are invited to convert any dataset in that format to another more common one. If you need this driver in future GDAL versions, create a ticket at https://github.com/OSGeo/gdal (look first for an existing one first) to explain how critical it is for you (but the GDAL project may still remove it), and to enable it now, set the GDAL_ENABLE_DEPRECATED_DRIVER_ARCGEN configuration option / environment variable to YES.
FAILURE:
Unable to open datasource `F027_10000_UniquePaths.gen' with the following drivers.
```
