### ISSUE TITLE
Better backup system

### ISSUE THREAD

**Issue by Ipickedausername** [qgis/QGIS#46681]
### Feature description

Hello, 

Would it be possible to make a backup version of the current layer, anytime this layer is saved. The backup layer would be saved in a special folder. And, when QGIS is lauched, after 'x' days, theses layers are automatically deleted (with a warning message or not). 

The author of the plugin "Backup layer" : Josef Källgården has made a real good work, according to me. 
I searched a way to execute his plugin for each saving of every layer, unsuccessfuly. 

Since I don't know of python is working, it's difficult to evaluate the difficulty to develop this king of idea, but, it seems not to be that hard, especially with the working basis of "Backup layer". 

Thank you for your attention ! 
Bye !

**Comment by gioman** [comment]
@Ipickedausername seems to me that this would be better suited for an improvement in the current "backup layer" plugin.

**Comment by Ipickedausername** [comment]
Hello, 

I first submitted this idea on the "backup layer" github project, but I didn't have an answer.
