### ISSUE TITLE
Editing Shapefiles and moving

### ISSUE THREAD

**Issue by GisCarmo** [qgis/QGIS#46690]
### What is the bug or the crash?

Hi all

I'm experience a bug that is really annoying

From time to time, when I'm editing shapefiles (points, lines, polygons) the bugs that I report bellow appear, the only solution that I found is closing and opening the project again, but this happen a lot

- When I select a feature to move it, the Qgis moves a other unselected feature from the same shapefile
- When I select a feature to edit the atribute table, the Qgis edits a unselected feature
- Some times, when a move a point feature and save that edit, it's impossible to edit that point again
- When I try to edit a vertex from a line, the Qgis doesn't  let me edit the vertex 

### Steps to reproduce the issue

.

### Versions

QGIS version
3.16.9-Hannover
QGIS code revision
9f8d2f7942
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
coordinate_capture;
coord_list;
disconnected-islands;
latlontools;
qfieldsync;
refFunctions;
StreetView;
swish_cable_maker;
db_manager;
MetaSearch;
processing

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
> 3.16.9-Hannover

@GisCarmo upgrade to 3.16.15 and try with a new QGIS profile, no 3rd party plugins installed (settings > user profiles > new profile).

**Comment by GisCarmo** [comment]
> > 3.16.9-Hannover
> 
> @GisCarmo upgrade to 3.16.15 and try with a new QGIS profile, no 3rd party plugins installed (settings > user profiles > new profile).

Thank's for your answer, Yes I already upgraded tou 3.16.15 and the bugs still appear.

**Comment by gioman** [comment]
> and the bugs still appear

@GisCarmo then you have to attach a sample project + sample data and detail exactly how to replicate what you are experiencing.
