### ISSUE TITLE
a Gdal raster dataset 'Open Options' are not shown in 'Datasource manager > Raster' dialog

### ISSUE THREAD

**Issue by faridcher** [qgis/QGIS#46698]
### What is the bug or the crash?

I expect QGIS to show the three Gtiff driver ['Open Options'](https://gdal.org/drivers/raster/gtiff.html#open-options) when a `tif` file is selected in the 'Datasource manager > Raster' dialog:

![img1](https://user-images.githubusercontent.com/9982519/148151089-89585362-859a-416a-be4f-9b6e92e72805.jpg)

Amazingly they are shown when the `tif` file is selected in Vector tab (screenshot below) even though QGIS refuses to add it to the project. 

![img2](https://user-images.githubusercontent.com/9982519/148151101-1fff023b-223b-45b5-9e78-2999132e25df.jpg)

### Steps to reproduce the issue

try to add  [lc.tif](https://github.com/qgis/QGIS/files/7811651/lc.zip) via the dialog.

### Versions

3.16.15

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
@faridcher works as expected here (3.22.2)

![image](https://user-images.githubusercontent.com/1951107/148219466-cf2c0ade-4b5d-46ba-90f3-5ebcbaf6141e.png)

**Comment by gioman** [comment]
But confirm not working on 3 .16.15, maybe is simply something that was added and not backported.

**Comment by faridcher** [comment]
@gioman  I agree. thank you for testing. BTW due to its importance, I think it should be backported to LTRs.

**Comment by agiudiceandrea** [comment]
See https://github.com/qgis/QGIS/pull/41277 by @nirvn

**Comment by nyalldawson** [comment]
You need to update to at least 3.18 to see this.
