### ISSUE TITLE
QGIS crashes exporting time series from points

### ISSUE THREAD

**Issue by fcideco** [qgis/QGIS#46709]
## User Feedback

This  tool was working yesterday.

## Report Details

**Crash ID**: [b4bca9b002474352615a2734b77959c072b64cdc](https://github.com/qgis/QGIS/search?q=b4bca9b002474352615a2734b77959c072b64cdc&type=Issues)

**Stack Trace**
<pre>
QgsTriangularMesh::update :
QgsMeshContours::operator= :
QgsProcessingAlgorithm::prepare :
QgsProcessingAlgRunnerTask::QgsProcessingAlgRunnerTask :
PyInit__core :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyFunction_Vectorcall :
PyFloat_FromDouble :
PyVectorcall_Call :
PyObject_Call :
PyInit__gui :
QObject::qt_static_metacall :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
PyInit_QtWidgets :
PyArg_ParseTuple_SizeT :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyFunction_Vectorcall :
PyFloat_FromDouble :
PyVectorcall_Call :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QObject::qt_static_metacall :
QAbstractItemView::doubleClicked :
QTreeView::mouseDoubleClickEvent :
PyInit__gui :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
PyInit__gui :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.22.2-Bia?owie?a
QGIS code revision: 1601ec46d0
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.0
Running against GDAL: 3.4.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

### Steps to reproduce the issue

Loaded Selafin Mesh from Telemac2D results (Sorry, can't share the mesh)

Selected 2 variables (Depth and Velocity)

10 h time step

Points from shapefile

Results either to temporary file  or to disk

### Versions

3.22.2

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Can not reproduce here on Qgis 3.22.2 OSGeo4W

Try to restart QGIS
Try to only load the shapefile and mesh

If you still have the issue try to reproduce the bug on a dataset (mesh and shapefile) that you can share.

**Comment by fcideco** [comment]
Thanks, 
Point layer had ghost points. They were erased but where still on the table.

Working now.

**Comment by nicogodet** [comment]
Qgis should not crash but skip invalid features.

**Comment by fcideco** [comment]
You are right, but the option was not set to skip.
After I cleaned the points layer and selected the option to skip (to be sure), it worked as expected.

**Comment by gioman** [comment]
> Qgis should not crash but skip invalid features.

agree. let's keep this open then.

**Comment by vcloarec** [comment]
@fcideco, two questions:
Is the bug appear when exporting contours ? The `QgsMeshContours` in the trace inspires me that.
Is it during mesh edition?

**Comment by fcideco** [comment]
Hi,
I was exporting Velocity (the scalar) and depth only. Contours export works on its own.

**Comment by vcloarec** [comment]
The processing tool you use is not clear. Can you precise?

**Comment by PeterPetrik** [comment]
Can we please add clear reproduce steps?
1. data set to load to reproduce the problem
2. reproduce steps (e.g. which processing alg and which inputs)
thanks a lot
