### ISSUE TITLE
QGIS Crashes after after loading a form with PyQt5

### ISSUE THREAD

**Issue by hcanobra** [qgis/QGIS#46710]
### What is the bug or the crash?

When I create an action to execute this Python code, the firs time works fine, but the second time when I close the window QGIS crashes.

from PyQt5.QtWidgets import QApplication, QWidget

# Only needed for access to command line arguments
import sys

# You need one (and only one) QApplication instance per application.
# Pass in sys.argv to allow command line arguments for your app.
# If you know you won't use command line arguments QApplication([]) works too.
app = QApplication(sys.argv)

# Create a Qt widget, which will be our window.
window = QWidget()
window.show()  # IMPORTANT!!!!! Windows are hidden by default.

# Start the event loop.
app.exec()

# Your application won't reach here until you exit and the event
# loop has stopped.

### Steps to reproduce the issue

1) on a Shape file, to to Layer Properties
2) Action List
3) Create an action
4) Python Type, under code I add.

from PyQt5.QtWidgets import QApplication, QWidget

# Only needed for access to command line arguments
import sys

# You need one (and only one) QApplication instance per application.
# Pass in sys.argv to allow command line arguments for your app.
# If you know you won't use command line arguments QApplication([]) works too.
app = QApplication(sys.argv)

# Create a Qt widget, which will be our window.
window = QWidget()
window.show()  # IMPORTANT!!!!! Windows are hidden by default.

# Start the event loop.
app.exec()

# Your application won't reach here until you exit and the event
# loop has stopped.

5) Ok, Apply, Ok
6) Run Feature acction... Select the action.
7) First event runs fine, second event crashes QGIS

### Versions

3.22.0

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
You can't create a second QApplication inside qgis -- that's always going to crash. You'll need to refactor your code to avoid this.

Closing as this is not a qgis bug
