### ISSUE TITLE
Display problem of my region 's Reference coordinate system

### ISSUE THREAD

**Issue by Savedbygrace98** [qgis/QGIS#46713]
### What is the bug or the crash?

Anytime, I want to do a map layout with the coordinate reference system of my region (use CRS of the project), QGIS stops responding and I can't continue it unless I close the layout window. Precisely, When I want to give the intervals X and Y. The CRS of my region is WGS 84 / UTM zone 30N. I'm in Ivory Coast. The only solution I found for this, is to use the CRS WGS84. With it, there is no issue but it doesn't correspond to my region.

### Steps to reproduce the issue

1 - Download any shapefile related to the CRS of Ivory Coast (WGS 84 / UTM zone 30N)
2 - Import the shapefile in Qgis
3 - Set the project with the CRS of the shapefile
4 - Use the option: "New print layout"
5 - Select the icon: "Add a map" and put it on the white page
6 - Go to Item properties
7 - Next, go to "Grid" / add a grid (+) / Modify it
8 - Change the value of the interval (x, y) (You can use any value)
9 - And press enter. You'll see yourself the bug.

### Versions

QGIS Version 3.22 

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
@Savedbygrace98 

what is the scale for your map object in the print layout? and the interval value?

That CRS is in meters, if you are looking at an extent at country/region level and you are using an interval that is a small value (like 1), it means that you are asking QGIS to draw a whole lot of grid lines, and that takes time. As they are meters you may want to use higher values, i.e. 50000 for a 50km grid spacing.

**Comment by Savedbygrace98** [comment]
Thank you ! It works. I would like to know how to display my coordinates in a degree minute second. Or is it possible to convert a shapefile with UTM coordinates (meters) to degree minute second?

**Comment by gioman** [comment]
> I would like to know how to display my coordinates in a degree minute second. Or is it possible to convert a shapefile with UTM coordinates (meters) to degree minute second?

add a grid to your map object, set the CRS for the grid to WGS 84 and use ddMMSS as format for values.

**Comment by Savedbygrace98** [comment]
Thank you! I saved the same shapefile with different coordinate systems. The one with the CRS WGS 84 (in ddMMSS) and the other with the CRS WGS 84 / UTM zone 30N (in meters) and the files overlay each other. I didn't know it before. Can you explain to me why is it like this? I'm amazed.
