### ISSUE TITLE
tables with more than 1 geometry column cant "zoom to" within the attributes window

### ISSUE THREAD

**Issue by glw** [qgis/QGIS#46712]
### What is the bug or the crash?

If you have a table with multiple geometry columns you can not zoom to the selected feature, using the "zoom to" button when a geometry exists in the alternate column. If no geometry exists in the alternate column it will "zoom to" without issue.

### Steps to reproduce the issue

create a table with 2 geometry columns (geom1, geom2).

In QGIS this will show in the browser as:
table.geom1
table.geom2

Add table.geom1 to layers. Open attributes and select a row where a geometry exists in geom2. Then click the "zoom to" button. An error bar will appear on the map screen. 

The expected behavior would be that it would zoom to the feature in the geom1 column regardless of there being a geometry in column geom2.

Further details in the Additional context box.

### Versions

QGIS version
3.4.15-Madeira
QGIS code revision
e83d02e274
Compiled against Qt
5.5.1
Running against Qt
5.5.1
Compiled against GDAL/OGR
2.2.2
Running against GDAL/OGR
2.2.2
Compiled against GEOS
3.5.1-CAPI-1.9.1
Running against GEOS
3.7.1-CAPI-1.11.1 27a5e771
PostgreSQL Client Version
9.5.2
SpatiaLite Version
4.3.0a
QWT Version
6.1.2
QScintilla2 Version
2.9.1
PROJ.4 Version
492

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

![image](https://user-images.githubusercontent.com/556205/148318834-87571af4-5cb0-400a-8333-ef6928e9276b.png)

![qgis_multigeom_zoomto](https://user-images.githubusercontent.com/556205/148321120-14bcc7c8-f21c-4f5a-b2a0-43991c0e4cab.gif)

**Comment by gioman** [comment]
@glw tested here with my own data (on postgis) and can't confirm.

**Comment by glw** [comment]
Hi @gioman , thanks for looking into it. 

Couple quick questions for you. Same version (I assume so)? And I forgot to mention Im on Ubuntu Xenial. Were you testing in that platform?

Thanks again!

**Comment by gioman** [comment]
> Couple quick questions for you. Same version (I assume so)? And I forgot to mention Im on Ubuntu Xenial. Were you testing in that platform?

@glw QGIS 3.22.2 on Windows and Ubuntu (Mint) 20.2. PostgreSQL 12 on Ubuntu Server 20.04.

**Comment by gioman** [comment]
> 3.4.15-Madeira

@glw I see now that you use a completely outdated and unsupported version, you must upgrade.

**Comment by glw** [comment]
Ah ok, I think this is because my Ubuntu version is a bit old now. For Xenial, 3.4.15 was that last update for LTR.

Thanks!

**Comment by glw** [comment]
hi @gioman So I have attempted the same operation on a new install of QGIS this time 3.22.2 and 3.22.3. But I am still unable to zoom to a point that has 2 geometry columns with geometries in them.

![image](https://user-images.githubusercontent.com/556205/150201969-1276f282-5577-4b14-8c20-d1132878c3b8.png)

My current install:

QGIS version
3.22.3-Białowieża
QGIS code revision
1628765ec7
Qt version
5.12.8
Python version
3.8.10
GDAL/OGR version
3.0.4
PROJ version
6.3.1
EPSG Registry database version
v9.8.6 (2020-01-22)
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
SQLite version
3.31.1
PDAL version
2.0.1
PostgreSQL client version
12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)
SpatiaLite version
4.3.0a
QWT version
6.1.4
QScintilla2 version
2.11.2
OS version
Zorin OS 16

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
sagaprovider
2.12.99
MetaSearch
0.3.5
