### ISSUE TITLE
QGIS - Crash during launch of project

### ISSUE THREAD

**Issue by cathsaigh** [qgis/QGIS#46711]
### What is the bug or the crash?

qgis.bin crashed with SIGABRT in proj_crs_alter_geodetic_CRS()

### Steps to reproduce the issue

Project, Open, "File.qgs"

### Versions

QGIS version 3.22.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by troopa81** [comment]
Could you please share your project file ?

**Comment by gioman** [comment]
@cathsaigh does your project contains a CSV? If yes please update to 3.22.2, it has been fixed there.

**Comment by cathsaigh** [comment]
Here is the project file
[Pollinator-Meadow.zip](https://github.com/qgis/QGIS/files/7823444/Pollinator-Meadow.zip)
e

**Comment by gioman** [comment]
> Here is the project file

@cathsaigh your project has a CSV, update to 3.22.2
