### ISSUE TITLE
Layer order panel : bring added layer to front (top of the order list)

### ISSUE THREAD

**Issue by dukytony** [qgis/QGIS#46726]
### Feature description

Anytime I create or add a new layer (any layer type), the layer order panel puts it by default at the bottom of the list (behind all other layers). So I have to move it manually at the top of the list if i want to see it on the map. Is there a way to bring it to front by default?

**Comment by andreasneumann** [comment]
Hi @dukytony  - the Swiss QGIS user group has this on the radar to have this fixed - most likely for QGIS 3.26.

Proposal is pending and it depends on the priorization (votes) of the Swiss QGIS users.

cc @nirvn @m-kuhn

**Comment by alexbruy** [comment]
Duplicates #29291.

**Comment by dukytony** [comment]
Where can i vote for this ? :p

**Comment by m-kuhn** [comment]
https://qgis.ch/en/association/membership-application ;-)

**Comment by dukytony** [comment]
well, can't vote because I'm not swiss. But please consider this guys, you would make a happy belgian qgis enthusiast here! All the best!

**Comment by m-kuhn** [comment]
I've heard exceptions have been made before for country rules.
I'll hand in a vote for you :point_up:
