### ISSUE TITLE
Trouble updating QGIS

### ISSUE THREAD

**Issue by tahuahua** [qgis/QGIS#46733]
## User Feedback

I have tried to update to the new versionof 3.22, but it keeps saying that bgspawn.exe file is in use and wont let me Retry or Continue.

As the update wont proceed, the whole programme has since become unstable.

## Report Details

**Crash ID**: [9691103ab0a6a911685ffb299081e07810a00fa6](https://github.com/qgis/QGIS/search?q=9691103ab0a6a911685ffb299081e07810a00fa6&type=Issues)

**Stack Trace**
<pre>
QtPrivate::QStringList_join :
CPLStringList::empty :
QgsRasterLayer::htmlMetadata :
QgsRasterLayerProperties::updateInformationContent :
QgsRasterLayerProperties::sync :
QgsRasterLayerProperties::QgsRasterLayerProperties :
QgisApp::showLayerProperties :
QgisApp::layerTreeViewDoubleClicked :
QMetaObject::activate :
QAbstractItemView::doubleClicked :
QTreeView::mouseDoubleClickEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.12.2-Bucure?ti
QGIS code revision: 8a1fb33634
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

### Steps to reproduce the issue

![Screenshot 2022-01-07 105228](https://user-images.githubusercontent.com/97260455/148460495-009be8f5-b884-4918-9638-d32cf4c5c99b.jpg)

### Versions

3.12.2 Bucuresti

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
Hi @tahuahua, have you read the notice on the download page?
"**CAUTION: Upgrades of old setups using the new repository are not supported. You need to do a fresh install or use a different directory.**"

![image](https://user-images.githubusercontent.com/16253859/148507563-7992d542-f1fd-4d13-b58b-fadf8238a930.png)

Maybe it could help you to fix your issue.

**Comment by tahuahua** [comment]
Many thanks Andrea

So of the following, which is recommended?



Andrew
