### ISSUE TITLE
«Feature has too many attributes» warning when adding features to memory layer with python

### ISSUE THREAD

**Issue by cxcandid** [qgis/QGIS#46756]
### What is the bug or the crash?

QGIS gives warning messages when adding features to a memory layer that is joined to another layer.
This bug seems to be a regression - see bug report 18784: https://issues.qgis.org/issues/18784

### Steps to reproduce the issue

1. Create memory layer with attributes
2. Join memory layer with another layer
3. Add features to memory layer (`memoryLayer.dataProvider().addFeature(<feature>)`)

### Versions

QGIS version
3.22.2-Białowieża
QGIS code revision
1601ec46d0
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.0
PROJ version
8.2.0
EPSG Registry database version
v10.038 (2021-10-21)
GEOS version
3.10.0-CAPI-1.16.0
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
There's not enough detail here. What features are you adding to the provider? If you are adding direct to the provider (ie not via the vector layer) then it's your responsibility to remove the attributes from the joined layer.

**Comment by cxcandid** [comment]
@nyalldawson hope the following python console code clarifies what I mean.
 ```python
layer1= iface.addVectorLayer("Point?crs=epsg:3857&field=id:integer&field=label_x:double&field=label_y:double","layer1","memory")
layer2 = iface.addVectorLayer("NoGeometry?crs=EPSG:3857&field=id:integer&field=name:string(50)","layer2","memory")
f = QgsFeature(layer2.fields())
f['id'] = 1
f['name'] = 'Test1'
layer2.dataProvider().addFeature(f)
joinObj = QgsVectorLayerJoinInfo()
joinObj.setJoinLayerId = layer2.id()
joinObj.setJoinFieldName = 'id'
joinObj.setTargetFieldName = 'id'
joinObj.setMemoryCache = True
joinObj.setJoinLayer(layer2)
layer1.addJoin(joinObj)

f = QgsFeature(layer1.fields())
f.setGeometry(QgsGeometry.fromPointXY(QgsPointXY(0,0)))
f['id'] = 1
layer1.dataProvider().addFeature(f)
```
![message](https://user-images.githubusercontent.com/58068164/148682352-64de744f-cc02-4718-9574-8beb25bba5e8.JPG)

I guess it's my fault here, but how can I add features without producing warning messages.
There was no warning message in earlier versions of QGIS.

**Comment by cxcandid** [comment]
Ok, found the error in my code: *layer1.fields()* includes the joined fields as well

After changing the code it works now without warning message:

```python
layer1= iface.addVectorLayer("Point?crs=epsg:3857&field=id:integer&field=label_x:double&field=label_y:double","layer1","memory")
fields = layer1.fields()
layer2 = iface.addVectorLayer("NoGeometry?crs=EPSG:3857&field=id:integer&field=name:string(50)","layer2","memory")
f = QgsFeature(layer2.fields())
f['id'] = 1
f['name'] = 'Test1'
layer2.dataProvider().addFeature(f)
joinObj = QgsVectorLayerJoinInfo()
joinObj.setJoinLayerId(layer2.id())
joinObj.setJoinFieldName('id')
joinObj.setTargetFieldName('id')
joinObj.setUsingMemoryCache(True)
joinObj.setJoinLayer(layer2)
layer1.addJoin(joinObj)

f = QgsFeature(fields)
f.setGeometry(QgsGeometry.fromPointXY(QgsPointXY(0,0)))
f['id'] = 1
layer1.dataProvider().addFeature(f)
```
