### ISSUE TITLE
Extract points from pointcloud to a vector layer

### ISSUE THREAD

**Issue by APOS80** [qgis/QGIS#46757]
### Feature description

To have use for pointcloud it would be great just to have the abillity to extract points from one to use in a vector layer and make mesh/raster.

**Comment by saberraz** [comment]
This will be likely added in 3.26. if not, ping me for an estimate for this feature.

**Comment by APOS80** [comment]
Forgot something else, it would be nise to also have the ability to snapp on poinst in the pointcloud.

**Comment by wonder-sk** [comment]
To be addressed in https://github.com/qgis/QGIS/pull/49280

**Comment by uclaros** [comment]
Implemented in #49280
