### ISSUE TITLE
Mesh contour reappears after hiding it in layer properties

### ISSUE THREAD

**Issue by nicogodet** [qgis/QGIS#46753]
### What is the bug or the crash?

When I want to hide the display of a mesh contour using layer properties, it reappears after hitting "Apply" then "OK".
![export6](https://user-images.githubusercontent.com/39594821/148579806-cf3945aa-4194-4c54-bc0f-2a5a2227a8f6.gif)

OK from Layer Styling panel

### Steps to reproduce the issue

1. Open meshlayer properties window
2. Disable mesh contour display
3. Hit "Apply" then "OK"

### Versions

3.22.2

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by roya0045** [comment]
That's weird because ok and accept are the same thing in the base dialog...

**Comment by roya0045** [comment]
Ok, did some minimal testing, when you hit apply a second time, the setting is reset.
