### ISSUE TITLE
Consider making som plugins part of QGis

### ISSUE THREAD

**Issue by APOS80** [qgis/QGIS#46758]
### Feature description

Some plugins has functionality that can benefit most people and I think it would be a good idea to make them a part of QGis.

Plugins like Qad and MapSwipeTool.

Qad has CAD functionality and could be integrated with the advanced digitizing toolbar.

MapSwipeTool is great for visualy compare files, i even think its standard in ArcGis.

Besides that i love what your doing with QGis.

**Comment by roya0045** [comment]
@gioman do you think this is a valid FR request? Replicating some aspect is one thing but integrating external plugins just because they are useful, that's another thing interely.

**Comment by APOS80** [comment]
Valid? It’s a request.

**Comment by nyalldawson** [comment]
In terms of including more plugins, it has been discussed and it's a "wontfix". Plugins help distribute the maintainence and are a good solution for edge use cases/features. 

Better to file individual feature requests covering each functionality you think should be copied from the plugins to qgis core instead.
