### ISSUE TITLE
Resource Sharing is giving me an WinError 32, don't know what to do 

### ISSUE THREAD

**Issue by KasperZs** [qgis/QGIS#46759]
### What is the bug or the crash?

When I try to download any pack from resource sharing plugin it gives me this error:

Error: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\tuma2\\AppData\\Roaming\\QGIS\\QGIS3\\profiles\\default \\resource_sharing\\repositories\\github.com\\rjhale1971\\NPS_Map_Symbols\\.git\\objects\\pack\\pack-2bc659d9a5bf121ede36c348754037d453d1ef81.idx'

### Steps to reproduce the issue

go to resource sharing 
search for svg
try to download a pack 
and there you go "error"

### Versions

QGIS 3.16 Hannover

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by Gustry** [comment]
This is linked to the plugin "Resource sharing", not QGIS.

The QGIS project can't do anything about a third party plugin. You must report the issue in the plugin code repository.

**Comment by KasperZs** [comment]
Installed 3.22 opened the file with it and it worked, but still don't understand why it happended with 3.16

**Comment by KasperZs** [comment]
ok! thank you @Gustry
