### ISSUE TITLE
QGIS unexpectedly ended

### ISSUE THREAD

**Issue by cshanewoodard** [qgis/QGIS#46754]
### What is the bug or the crash?

since upgrading to 3.22 I have been seeing these errors often when closing QGIS.  QGIS does not crash while I'm using it, but will give this error when I click the X (top right) to close the program.  

It does not happen every time, but maybe up to 50%.  The error does not seem to happen if I have not made any changes to the project, and seems to happen less if I save my updates often.  Complex project with many layers may cause the error more often than simple projects with just a few layers, but I do not have any hard facts on that.

## User Feedback

I've been getting this error when i try to close QGIS since upgrading to this version.  It does not happen every time I close, but is it often (maybe half the time).

## Report Details

**Crash ID**: [6f7bb1e2207b67793f1a4ada1054453ffcb7095a](https://github.com/qgis/QGIS/search?q=6f7bb1e2207b67793f1a4ada1054453ffcb7095a&type=Issues)

**Stack Trace**
<pre>
QObject::blockSignals :
QgsMapCanvas::cancelJobs :
QgsMapCanvas::~QgsMapCanvas :
QgsPluginRegistry::operator= :
QgisApp::~QgisApp :
QgsPluginRegistry::operator= :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.22.2-Bia?owie?a
QGIS code revision: 1601ec46d0
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.0
Running against GDAL: 3.4.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

### Steps to reproduce the issue

simply closing QGIS via the x in the top right may cause the error

### Versions

seems to be happening since I started running 3.22.  I know i have upgrade at least once within this version (maybe twice).  currently running 3.22.2

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@cshanewoodard you must test with a new QGIS profile

settings > user profiles > new profile

**Comment by cshanewoodard** [comment]
@gioman, I started to create a new profile, but the first go was quite complicated for the projects I work in.  The projects typically have many (10-50) database layers, and when I created the new profile it wanted me to log into each database layer independently as it does not move the saved authentication.  This would be a lot of work across many projects, and since the issue is intermittent, I'm honestly not sure it's worth my time to have to set up a second copy of each project.  I'll play with the new profile a bit more, but I might not be able to help much more in troubleshooting depending on how much extra effort the new profile turns out to be.

**Comment by cshanewoodard** [comment]
As I am paying more attention to this now, I believe the error happens mostly when I have unsaved changes in a project.  For example, I had a project just now where I had created an annotation layer.  I saved the project and then exited QGIS and did not have get the error.

I then needed to go back into the project and look at the data.  While I was in the project I deleted the annotation options and then clicked the top right window "X" to close the program without saving first.  When I did this, I got the error.

**Comment by gioman** [comment]
> As I am paying more attention to this now, I believe the error happens mostly when I have unsaved changes in a project. For example, I had a project just now where I had created an annotation layer. I saved the project and then exited QGIS and did not have get the error.
> 
> I then needed to go back into the project and look at the data. While I was in the project I deleted the annotation options and then clicked the top right window "X" to close the program without saving first. When I did this, I got the error.

@cshanewoodard can you provide a clear path (and eventually a sample project+sample data) that leads to the crash?

**Comment by cshanewoodard** [comment]
I'll try some stuff out over the weekend and see if I can find a way to
recreate the issue consistently.

Shane - sent from mobile device

**Comment by thymaro** [comment]
I have a very similar issue. Should I open a separate bug report or is the standard practice to aggregate issues when enough similarity is given? Here's the report:

## User Feedback

Alright, the crashes upon closing seem to be related to something in my QGIS profile. 

I moved the files in "C:\Users\MyName\AppData\Roaming\QGIS\QGIS3\profiles" to another folder. I started another session with a "fresh" default profile, did some edit to a project, saved the changes and closed the application, no error occured. I reinserted the regular "default" profile into the profiles folder and the crashes upon closing reappeared. 

This happens every time. It happens with every project and every project complexity (I don't have complex projects with hooks to external data, almost everything is local).

## Report Details

**Crash ID**: [2bba35ac54ec3f66db08369439704d5a7beb5523](https://github.com/qgis/QGIS/search?q=2bba35ac54ec3f66db08369439704d5a7beb5523&type=Issues)


**Stack Trace**
<pre>
GDALDestroyDriver :
dal::GDALRasterDriver::deregisterGDALDrivers :
dal::Client::~Client :
calc::DataStorageId::setId :
<lambda_f03950bc5685219e0bcd2087efbe011e>::operator() :
__crt_seh_guarded_call<int>::operator()<<lambda_7777bce6b2f8c936911f934f8298dc43>,<lambda_f03950bc5685219e0bcd2087efbe011e> &,<lambda_3883c3dff614d5e0c5f61bb1ac94921c> > :
execute_onexit_table :
calc::vs2CsfVs :
calc::vs2CsfVs :
LdrpCallInitRoutine :
LdrShutdownProcess :
RtlExitUserProcess :
ExitProcessImplementation :
exit_or_terminate_process :
common_exit :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.16.16-Hannover
QGIS code revision: f5778a89
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.1
Running against GDAL: 3.4.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Steps to reproduce the issue

Closing QGIS will cause the error, independent of changes to a project.

### Versions

This started after the upgrade from 3.16.15 (osgeo4w_v1, i.e. old dependencies) to 3.16.16 (osgeo4w_v2, new dependencies). I removed the old version via osgeo4w_v1, but left everything else untouched (models repo, profiles, plugins etc.)

### Supported QGIS version

- [x] I'm running a supported QGIS version according to the roadmap.

New profile

- [x] I tried with a new QGIS profile, cf. above.

**Comment by thymaro** [comment]
Nevermind, I just found out what the issue is by following the Crash ID. I didn't know the crash ID would help me with this, but it did.

> This is related to pcraster, which uses GDAL C++ API.
> 
> _Originally posted by @jef-n in https://github.com/qgis/QGIS/issues/46487#issuecomment-993503912_

Disabling the PCRaster plugin doesn't help resolve the issue. What is the recommended course of action?

**Comment by gioman** [comment]
> Disabling the PCRaster plugin doesn't help resolve the issue. Uninstalling PCRaster via osgeo4w_v2 resolves the issue. What is the recommended course of action from here?

@thymaro disabling the plugin could not be enough, especially if you don't restart QGIS. The suggest path is always to try with a new QGIS profile: settungs > user profiles > new profile

**Comment by gioman** [comment]
> Should I open a separate bug report or is the standard practice to aggregate issues when enough similarity is given? Here's the report:

@thymaro keep everything in the already existing ticket, thanks.

**Comment by gioman** [comment]
> QGIS Version: 3.16.16-Hannover

@thymaro there is not point at this stage to keep trying on 3.16, is EOL, there will not be another 3.16 release and there will not be any more bug fixes. At this point things must be tested on 3.22(.3) and/or master.

**Comment by thymaro** [comment]
OK, as I have already tried with a new profile and that worked, I will wait for the new LTR and report again, if i behaves the same way. For now, I have disabled and uninstalled PCRaster. (I don't really need it at the moment, I think.)
