### ISSUE TITLE
Diagrams not showing when switching its type

### ISSUE THREAD

**Issue by joaquinmunoz** [qgis/QGIS#46769]
### What is the bug or the crash?

Diagrams not showing when switching its type

### Steps to reproduce the issue

1. Take a layer (polygon) with some features and numeric fields
2. Open Layer Properties, and select Diagrams
3. Choose 'Pie Chart' and add some numeric fields to 'Assigned attributes'
4. Click Apply and OK

- Pie charts are shown in the map for each feature

5. Open again Layer Properties, and select Diagrams
6. Choose 'Histogram' (or any diagram type)
7. Click Apply and OK

- No diagrams are shown in the map

8. Open again Layer Properties, and select Diagrams
9. Choose again 'Pie Chart'
10. Click Apply and OK

- Neither is shown in the map
![qgis_bug2](https://user-images.githubusercontent.com/25054877/148754712-3b3975c4-cb82-4b61-b7e4-dabd61a4100e.gif)

### Versions

QGIS version | 3.22.2-Białowieża | QGIS code revision | 1601ec46d0
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | 12.3
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 11.6
  |   |   |  
Active Python plugins
batch_gps_importer | version 1.0.1
QuickOSM | 2.0.0-beta3
freehandEditing3 | version 1.1.0
profiletool | 4.2.1
DataPlotly | 3.8.1
AzimuthMeasurement | 0.2.2
joinmultiplelines | Version 0.4.1
quick_map_services | 0.19.27
nominatim | 1.4.1
geometry_paster | 0.1.1
GeoCoding | 2.18
poiexport | 3.0.3
OSMDownloader | 1.0.3
openlayers_plugin | 2.0.0
trail_elevation_stats | 0.2
valuetool | 3.0.15
mmqgis | 2021.9.10
Spanish_Inspire_Catastral_Downloader | 1.1
Mergin | 2021.5.1
BufferByPercentage | 0.3.3
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.5

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by roya0045** [comment]
A note for investigation, [the apply function](https://github.com/qgis/QGIS/blob/93399e33a31c92867e17c221cc74fe40f4b82c14/src/gui/vector/qgsdiagramproperties.cpp#L795) seed to be unconnected to anything , connection it to `accept` and `apply` might solve it?

**Comment by roya0045** [comment]
I can confirm on windows too. Though I'm unsure what causes this...

**Comment by roya0045** [comment]
Ok, it seems that using histogram is the faulty one. Switching between others is fine (though the stacked bars is broken and shows empty space with many categories).

**Comment by roya0045** [comment]
@nyalldawson I've looked into this and what I found up to now is that the mLabels stored in qgslabelingenging are deleted when switching to the histogram and never get repopulated.

I'll keep digging but if you have a clue or a hint feel free to let me know as I'm not familiar with pal.

**Comment by roya0045** [comment]
Ok, it's the interpolation settings that get corrupted as it seems to be a one way change.

**Comment by roya0045** [comment]
Ok found the issue, seems to be a big UX/UI issue. I'll try to come up with a PR to fix this.

**Comment by gacarrillor** [comment]
@joaquinmunoz, histograms need that you define a maximum field value on your own and an associated bar length to apply a linear interpolation for the rest of the values.

This will happen even if you don't set the Pie diagram in the first place (steps 3 and 4 in your description).

I wouldn't necessarily consider this a bug, would you @joaquinmunoz?
