### ISSUE TITLE
attribute value changes by itself

### ISSUE THREAD

**Issue by allkite** [qgis/QGIS#46767]
### What is the bug or the crash?

Hello, I'm using the 3.16 version. After copying and pasting this value as it is, the attribute value changes by itself after save.

MultiPolygon (((14145841.3354800958186388 4532195.19267785362899303, 14145833.60976920835673809 4532186.87709185667335987, 14145820.12384528294205666 4532199.54157770797610283, 14145809.52223314717411995 4532209.49743743520230055, 14145817.23698188178241253 4532217.80327145662158728, 14145825.77212320268154144 4532209.78839229978621006, 14145829.92799015156924725 4532214.23514356464147568, 14145831.87527215294539928 4532212.39505381509661674, 14145832.90893152728676796 4532211.41829440556466579, 14145830.85423165559768677 4532209.21986189298331738, 14145832.97053673677146435 4532207.21254365425556898, 14145830.74436020664870739 4532204.83052949327975512, 14145832.49918318353593349 4532203.3001410998404026, 14145832.62013693153858185 4532203.41027653310447931, 14145841.3354800958186388 4532195.19267785362899303)))  12800248  225  17  0  1  258791  38231

### Steps to reproduce the issue
[38231_상계역센트럴푸르지오.zip](https://github.com/qgis/QGIS/files/7837601/38231_.zip)
https://docs.google.com/spreadsheets/d/1sZB78n08GqU-7pSqQt22s1IC9yuw5e1Gm6omhPPs1-Q/edit?usp=sharing
![image](https://user-images.githubusercontent.com/97434017/148735426-e3e68d2f-18bb-4db9-a140-e735a2857a63.png)
->
![image](https://user-images.githubusercontent.com/97434017/148735456-1a05147c-c6a4-437b-ace3-0005786155a3.png)

https://user-images.githubusercontent.com/97434017/148736993-90e17855-6ff1-4778-8e3c-225ef3d6d539.mp4

### Versions

QGIS 버전
3.16.5-Hannover
QGIS 코드 리버전
58ba7c1ed6
컴파일시 사용된 Qt
5.11.2
다음 Qt를 이용해서 실행 중입니다
5.11.2
컴파일시 사용된 GDAL/OGR
3.1.4
다음 GDAL/OGR을 이용해서 실행 중입니다
3.1.4
컴파일시 사용된 GEOS
3.8.1-CAPI-1.13.3
다음 GEOS를 이용해서 실행 중입니다
3.8.1-CAPI-1.13.3
SQLite 호환 컴파일
3.29.0
SQLite 호환 실행
3.29.0
PostgreSQL 클라이언트 버전
11.5
SpatiaLite 버전
4.3.0
QWT 버전
6.1.3
QScintilla2 버전
2.10.8
컴파일시 사용된 PROJ
6.3.2
다음 PROJ를 이용해서 실행 중입니다
Rel. 6.3.2, May 1st, 2020
OS 버전
Windows 10 (10.0)
파이썬 플러그인 활성
ale; 
AttributesJoinByLine; 
cartolinegen; 
FreehandRasterGeoreferencer; 
geo_sim_processing; 
joinmultiplelines; 
networks; 
pgtopoeditor; 
Qgis2threejs; 
QNEAT3; 
shapetools; 
SRTM-Downloader; 
tmsforkorea; 
visualist; 
db_manager; 
MetaSearch; 
processing

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
> Steps to reproduce the issue

@allkite we need more details, and also a small dataset we can use to try replicate the issue.

**Comment by allkite** [comment]
[38231_상계역센트럴푸르지오.zip](https://github.com/qgis/QGIS/files/7837582/38231_.zip)
https://docs.google.com/spreadsheets/d/1sZB78n08GqU-7pSqQt22s1IC9yuw5e1Gm6omhPPs1-Q/edit?usp=sharing  @gioman

**Comment by allkite** [comment]
Thank you. I added it. @gioman

**Comment by gioman** [comment]
> Thank you. I added it. @gioman

@allkite can you add the layer/datasource (even empty) you are pasting in in QGIS?

**Comment by allkite** [comment]
https://docs.google.com/spreadsheets/d/1sZB78n08GqU-7pSqQt22s1IC9yuw5e1Gm6omhPPs1-Q/edit?usp=sharing 
I used it. @gioman
