### ISSUE TITLE
"Rotate" triangles in mesh

### ISSUE THREAD

**Issue by APOS80** [qgis/QGIS#46760]
### Feature description

I´m used to be able to rotate triangles in my software at work and i think its missing in QGis-Mesh editing.
Sometimes QGis doesnt draw triangle verteses as you want and then its good to be able to edit that.

Lets say you got a mesh made from four points, theres two ways QGis can put the triangles and then it can be useful to be able
to correct a mistake by changing from what corners to split the square.

Its a common problem when theres lines of dots on two sides but its farther between tha lines than between the points.

**Comment by nicogodet** [comment]
You mean this ?

![Animation2](https://user-images.githubusercontent.com/39594821/148652892-d005c0b5-8846-4a8a-ad55-e8bf8c2931e1.gif)

**Comment by APOS80** [comment]
Oh, thanks. Didn’t know that!

**Comment by nicogodet** [comment]
@APOS80 So this solve this feature request ?
If it does, you can close it

**Comment by APOS80** [comment]
Yes!
