### ISSUE TITLE
ctrl-click on Mac not working

### ISSUE THREAD

**Issue by 64mien** [qgis/QGIS#46771]
### What is the bug or the crash?

Functions that require right-click on Windows, such as closing polygons, should use ctrl-click on Mac but this does not work.

### Steps to reproduce the issue

For example: use Select Features by Polygon and try to close the polygon. It’s impossible.

### Versions

QGIS-LTR 3.16.15 with MacOS Catalina 10.15.7

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

I started using QGIS-LTR 3.16.12 in Oct 2021 and this problem did not arise. In Jan 2022 the problem occurred while I was still using the same version, so I would guess a Mac system update might be what broke it. Installing 3.16.15 has not solved it.

There’s been a previous bug report #31279 referring to this problem but it is full of unhelpful comments which is why I'm making this new report.

There’s a suggestion in #31279 by @thayeray that when @PeterPetrik repackaged with latest qt that fixed the problem last time it cropped up. Could that be the fix here?

I’d be really grateful for a fix, my workflow has ground to a halt.

Thanks all.

**Comment by gioman** [comment]
@64mien for what I have understand is fixed on 3.22

**Comment by 64mien** [comment]
Help!

**Comment by 64mien** [comment]
I don’t understand what the point of this forum is. I raise an issue, it gets ignored for 14 days then closed automatically. I mean, what is the point?

**Comment by gioman** [comment]
> I don’t understand what the point of this forum is. I raise an issue, it gets ignored for 14 days then closed automatically. I mean, what is the point?

@64mien hi. This is not a forum, is a bug tracker. When a report is made is possible that a feedback is requested. If not feedback is left then the report is put in "stale" condition. Then is closed after 42 days if no feedback is left. In this case was left a comment saying that the bug was/is fixed in the 3.22 release. This means that the reporter is supposed to test and then confirm or not.

**Comment by gioman** [comment]
> it is with the LTR which is 3.16.

@64mien there will not be a new 3.16 release (3.22 will become LTR), so there are no new bug fixes for it.

**Comment by 64mien** [comment]
@gioman I thought the aim was to offer a new but possibly more buggy version alongside an older but more stable version with the LTR designation, so surely the LTR has to be maintained too?

Also I don’t think it’s a bug fix that’s actually needed, I think it might be a package issue to do with QT. This was referenced previously and I really hoped someone who had fixed that problem before might know if it’s the same thing over again.

**Comment by gioman** [comment]
> so surely the LTR has to be maintained too?

@64mien and it does, but not when it slated to be end of life. From certain point of view the LTR is already 3.22.

**Comment by 64mien** [comment]
Thanks @gioman 

Can report that ctrl-click on Mac is indeed fixed on 3.22 and would recommend that to anyone with this problem.

Closing issue.

**Comment by j9brown** [comment]
I'm seeing this problem on 3.24.3.  So is this broken again?

**Comment by thayeray** [comment]
Can you give detail about your operating system, and which QGIS packager version you are using?
-T

    On Monday, June 13, 2022 at 06:52:06 PM EDT, Jeff Brown ***@***.***> wrote:  
 
 


I'm seeing this problem on 3.24.3. So is this broken again?

**Comment by j9brown** [comment]
My apologies, I deleted my comment after realizing my error.  I was drawing
polygons onto a layer that was behind an opaque one so they would vanish
each time I closed them.  All’s well.  Thanks!

**Comment by brendam** [comment]
Any kind of right click on Mac trackpad (ctrl-click or two fingers or right bottom corner of trackpad) seems to act as esc and clear the polygon instead of closing it in QGIS Version 3.26.3 ​ on MacBook Pro (13-inch, M1, 2020) with MacOS Monterey 12.6. Reverted to QGIS Version 3.22.11 LTR and it works as expected.
