### ISSUE TITLE
Saga tool do not work

### ISSUE THREAD

**Issue by ThirstyH** [qgis/QGIS#46785]
### What is the bug or the crash?

When I try to use every SAGA tool such as fill sink(wang & liu) etc... , I got a error message below.

And, When I search a saga tool using 'processing toolbox', every SAGA tool is turned light gray color. (usually it means that 'disabled or inactive')

### Steps to reproduce the issue

1. SAGA

2. Terrain Analysis - Hydrology

3. Fill Sink (wang & liu)

4.
The following layers were not correctly generated.
• C:/Users/Y14135/AppData/Local/Temp/processing_DjLFpd/008a1a423b3540bca3ae1fcb2947a969/WSHED.sdat
• C:/Users/Y14135/AppData/Local/Temp/processing_DjLFpd/19ac58f6934b419a807c7a4465ba49e1/FILLED.sdat
• C:/Users/Y14135/AppData/Local/Temp/processing_DjLFpd/3af7e91cc6e84836aba1950499d55380/FDIR.sdat
You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.

### Versions

QGIS version
3.16.15-Hannover
QGIS code revision
e7fdad6431
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
AusMap; 
geomelwatershed-master; 
db_manager; 
MetaSearch; 
processing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
@ThirstyH works fine here. Are you using osgeo4w v1? if yes then please replace your installation with osgeo4w v2.
