### ISSUE TITLE
Bug:  "Tab" key not working in the Feature Attributes dialogue box for attributes with a Value Relation

### ISSUE THREAD

**Issue by emonshaugen-foreflight** [qgis/QGIS#46780]
### What is the bug or the crash?

Bug:  when creating a feature (line, point or polygon),  and tabbing through the Feature Attributes diaglogue box, the "tab" key will skip any attributes with Value Relations.  This is a regression from previous versions of QGIS where you could tab through the attributes to get to the attribute you wanted to change (whether or not the attribute was associated with a Value Relation).

### Steps to reproduce the issue

1.  Create a feature in a shapefile that contains an attribute with a Value Relation.
2.  When the Feature Attributes dialogue box opens up, hit the "tab" key until you get to the attribute with the Value Relation.
3.  This attribute will be skipped when tabbing through.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.16.2-Hannover | QGIS code revision | c6ac5a6052
-- | -- | -- | --
Compiled against Qt | 5.14.2 | Running against Qt | 5.14.2
Compiled against GDAL/OGR | 3.1.2 | Running against GDAL/OGR | 3.1.2
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.4
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | macOS 10.16
Active python plugins | FreehandRasterGeoreferencer; QuickOSM; scriptrunner3; clipper; quick_map_services; latlontools; raster_tracer; shapetools; foreflight_plugin; processing; db_manager; MetaSearch

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
> This attribute will be skipped when tabbing through.

@emonshaugen-foreflight just tested on 3.16.15 on macOS Catalina (Intel) and Monterey (M1) and cannot confirm.
