### ISSUE TITLE
qgis server support 3D?

### ISSUE THREAD

**Issue by gengyanlei** [qgis/QGIS#46788]
### What is the issue about the documentation?

![image](https://user-images.githubusercontent.com/22360785/148907011-bde7c655-7002-4cd3-94fc-d3e6efe53829.png)
![image](https://user-images.githubusercontent.com/22360785/148907071-4bd104c7-5c12-4a10-b82a-c3c03a04384d.png)

Does the qgis-desktop publishing service require the help of qgis2three.js?

**Comment by Gustry** [comment]
Your question is not clear.

As stated in the table, QGIS Server doesn't support 3D.
You can make a static export of your map with the qgis2three.js plugin to have some 3D, but it's a static webpage. QGIS Server is not involded in this process.

 This page is a bug tracker. If you want to ask question, gis.stackexchange.com is a better place, or QGIS mailing list.
