### ISSUE TITLE
If "estimated metadata" option is checked, feature count for tables/postgis do not work

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#46790]
### What is the bug or the crash?

In a PostGIS connection enable the "estimated metadata" option.

Add a geometryless table to a project.

Try enable "feature count" (this should be renamed "record count" for this type of tables) > nothing happen

If the option is unchecked than "feature count" works, but curiously the count is wrong (in my case geometryless tables, not views or MT, with a PK).

### Steps to reproduce the issue

See above.

### Versions

3.22.2 on Windows 10.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by m-kuhn** [comment]
Regressiin?

**Comment by gioman** [comment]
> Regressiin?

@m-kuhn I think so.

**Comment by elpaso** [comment]
@gioman I'm testing on master and it seems that feature count also always shows 0 for geometry tables and not only for geometryless, can you confirm that?

**Comment by elpaso** [comment]
Anyway, I'm not sure this is a bug, when use estimated metadata is set, row count is also estimated and it can be wrong.

**Comment by elpaso** [comment]
@troopa81 would you mind having a look here? When estimated metadata is set we use this to get the count and this might be 0 for small tables https://github.com/qgis/QGIS/blob/master/src/providers/postgres/qgspostgresprovider.cpp#L3776

**Comment by elpaso** [comment]
@troopa81 I'm not sure but we may be implement a better logic without big performance penalties with:
```
if estimated:
  count = <current logic>
  if count == 0:
    # precise count
    count = <select count(*) from ....>
```

rationale: if the estimated count is 0 we could probably run a real count without spending too much time because the table is probably either empty or containing a small set of features.

Also the estimated SQL could probably be enhanced as explained in https://stackoverflow.com/questions/7943233/fast-way-to-discover-the-row-count-of-a-table-in-postgresql/7945274 "Safe and explicit" paragraph.

**Comment by elpaso** [comment]
See my draft PR https://github.com/qgis/QGIS/pull/46963 if that's acceptable I will attempt to write a test.

**Comment by gioman** [comment]
> I'm testing on master and it seems that feature count also always shows 0 for geometry tables and not only for geometryless, can you confirm that?

@elpaso well, I don't know what to say. I tested now again 3.22.3 and master and in both it seems to work as expected, so I'm a bit at loss on why a few days back on 3.22.2 I was seeing what I described.


> It may depend on the individual table though, because it is an estimate.

I understand that "use estimated metadata" speed up things, but I also think that we should never show something to the users that we known it may be wrong.  So either the "feature count" should be disabled if the table was loaded from a connection with   "use estimated metadata" ON, or we should flag such layers/tables in the TOC with a specific icon. My 2c.

**Comment by elpaso** [comment]
@gioman fair point, I see two options here:

1. always execute the (possibly slow) real `count()` when feature->count() is request, ignoring the estimate md setting
2. work on the GUI/UX by disabling the feature count in the legend (but there might be other things that rely on feature->count() that might report wrong results) and/or warn the user about using approximate feature count.

I would go for the first option, feature count is not always required but when it happens we'd better return the correct result in any situation.

CC @m-kuhn

**Comment by troopa81** [comment]
@elpaso Estimated metadata is useful when you have big table and you don't want to block your QGIS when counting feature. I would go for option 2 (we can add a "~" before the number with a tooltip "Estimated count of X").

> rationale: if the estimated count is 0 we could probably run a real count without spending too much time because the table is probably either empty or containing a small set of features.

Is it sure? Can we not fall on some situation where a lots of insert have been made and the statistics are not up to update, and the estimated is still 0, and so the real count would be slow.

**Comment by elpaso** [comment]
> @elpaso Estimated metadata is useful when you have big table and you don't want to block your QGIS when counting feature. I would go for option 2 (we can add a "~" before the number with a tooltip "Estimated count of X").
> 
> > rationale: if the estimated count is 0 we could probably run a real count without spending too much time because the table is probably either empty or containing a small set of features.
> 
> Is it sure? Can we not fall on some situation where a lots of insert have been made and the statistics are not up to update, and the estimated is still 0, and so the real count would be slow.

Yes, I guess you are right: VACUUM or ANALIZE are needed to update stats.

**Comment by m-kuhn** [comment]
My gut feeling is:
- explicitly communicate that the number is not correct (or that no correct number is available)
- closeby offer a (discoverable) possibility to recalculate statistics
