### ISSUE TITLE
laz point clouds loaded with offsets

### ISSUE THREAD

**Issue by AlexZanini70** [qgis/QGIS#46804]
### What is the bug or the crash?

.laz point cloud files are displayed in the wrong location, shift of 0.005 applied in x, y and z
-0.005m to X, 0.005m to Y, 0.005m to Z

![immagine](https://user-images.githubusercontent.com/97609991/149155771-59849d29-279b-4150-8d19-d8638acc5f27.png)

### Steps to reproduce the issue

1) Drag and drop the .laz file or using the Browser panel
2) Processing tools - las2txt to export the xyz
3) Layer - Add Layer - Add Delimited Text Layer for the xyz file

double checked with other softwares and the coordinates in the exported xyz are correct
xyz exported using pdal (in conda) and lastools match with values in source .laz file

### Versions

QGIS 3.22.2

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by Jean-Roc** [comment]
May be linked to https://github.com/hobu/untwine/issues/88

**Comment by roya0045** [comment]
> May be linked to [hobu/untwine#88](https://github.com/hobu/untwine/issues/88)

Nice find, I was also thinking this could  probably be an upstream error and not in qgis directly.

**Comment by alexbruy** [comment]
Can't reproduce with the latest master (94b62accf2a1cfc892bc9097cd4dd5f8a1f60ab0).
