### ISSUE TITLE
SVG symbols not found

### ISSUE THREAD

**Issue by molig** [qgis/QGIS#46805]
### What is the bug or the crash?

In layer properties are only displayed default symbols even if but in "SVG path" window I added other directories with many svg file

### Steps to reproduce the issue

![Screenshot 2022-01-12 16 03 56](https://user-images.githubusercontent.com/63057226/149167308-ce656d31-15c7-4fbe-b825-07f0d1012f6b.png)
![Screenshot 2022-01-12 16 05 21](https://user-images.githubusercontent.com/63057226/149167309-a0798e79-fd35-4204-9f5c-4369c4c17c35.png)

### Versions

Versione di QGIS | 3.22.2-Białowieża | Revisione codice QGIS | 1601ec46d0
-- | -- | -- | --
Versione Qt | 5.15.2
Versione Python | 3.9.5
Versione GDAL/OGR | 3.4.0
Versione PROJ | 8.2.0
Versione database del Registro EPSG | v10.038 (2021-10-21)
Versione GEOS | 3.10.0-CAPI-1.16.0
Versione SQLite | 3.35.2
Versione PDAL | 2.3.0
Versione client PostgreSQL | 13.0
Versione SpatiaLite | 5.0.1
Versione QWT | 6.1.3
Versione QScintilla2 | 2.11.5
Versione SO | Windows 10 Version 2009
  |   |   |  
Plugins Python attivi
azimuth_distance_measurement | 0.3
kmltools | 3.1.15
numericalDigitize | 0.4.6
qgis_resource_sharing | 0.16.0
quick_map_services | 0.19.27
zoomtopaste | 3.0.3
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.5
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Please, read the documentation : https://docs.qgis.org/3.16/en/docs/user_manual/style_library/symbol_selector.html#the-symbol-layer
