### ISSUE TITLE
QGIS ends unexpectedly every time I try to change the geometry of a polygon

### ISSUE THREAD

**Issue by GatorochParkerGIS** [qgis/QGIS#46806]
### What is the bug or the crash?

QGIS ends unexpectedly every time I try to change the geometry of a polygon.

I tried to move a node. I have tried many times before, in different ways, but I always get this message telling me "something unexpected happened".

### Steps to reproduce the issue

The geometry had faults, two lines were crossing eachother in a polygon. This time I tried to fix it by moving one node so that the lines would no longer cross eachother. 

(I am now aware of a tool that can do this. It would, however, be nice to be able to touch a polygon without the program crashing :) )

## Report Details

**Crash ID**: [2c27e49adbcac83bea72180c3aeb7822a1e7333a](https://github.com/qgis/QGIS/search?q=2c27e49adbcac83bea72180c3aeb7822a1e7333a&type=Issues)

**Stack Trace**
<pre>
QgsSymbolLayerWidget::`vftable' :
QgsGeometryValidator::checkRingIntersections :
QgsGeometryValidator::run :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.16.0-Hannover
QGIS code revision: 43b64b13f3
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

### Versions

3.16.0-Hannover

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by GatorochParkerGIS** [comment]
I appreciate any help that I can get :)

**Comment by roya0045** [comment]
Please update to a recent version to validate if the issue is present.

**Comment by gioman** [comment]
@GatorochParkerGIS update to 3.16.15 and try with a new QGIS profile.
