### ISSUE TITLE
Vertex Tool does not set Z coordinate on points reliably

### ISSUE THREAD

**Issue by m-kuhn** [qgis/QGIS#46808]
### What is the bug or the crash?

In a layer that does have Z coordinates but contains points without Z coordinates, the Z value is not added on snapping.

The following video has one 3D point and one 2D point on the same layer

![Peek 2022-01-12 19-40](https://user-images.githubusercontent.com/588407/149193891-0cb3f196-a001-4f53-a4ce-5eacf5fb4201.gif)

### Steps to reproduce the issue

[snapalt.zip](https://github.com/qgis/QGIS/files/7856623/snapalt.zip)

### Versions

master

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by Koyaani** [comment]
I tried to reproduce the issue on master without success. @m-kuhn Could you tell me if the problem is still present? Or if it is me who doesn't understand the issue...

**Comment by m-kuhn** [comment]
@3nids did you already fix this?
The attached file should demonstrate the problem from the video.

**Comment by domi4484** [comment]
@m-kuhn I just tried to reproduce with master and the problem is still there. Interesting it happens only with the point on the left. With the point on the right Z is always added.

**Comment by m-kuhn** [comment]
@domi4484 if you export the geometry of the two features to WKT (via python console) is there a difference?

**Comment by domi4484** [comment]
Yes, one is a Point and the other a PointZ. So on snap it should be upgraded.
```
'Point (-0.97840558091899033 0.15115529474019473)'
'PointZ (-0.84424200049928655 0.13457672873867527 nan)'
```

**Comment by domi4484** [comment]
If the original point doesn't have a Z value, it is not promoted to 3D.
This is done in `QgsPoint::moveVertex`, and there we don't know if the point is in a 2D or 3D layer. So I think the point should be upgraded earlier but I am not sure where. Maybe in `QgsVectorLayerEditUtils::moveVertex`? 🤔

**Comment by m-kuhn** [comment]
That sounds good to me. A 2D point on a 3D layer can be promoted whenever touched.

**Comment by domi4484** [comment]
@m-kuhn  Is it reasonable to assume that a polygone or line doesn't have mixed (with and without Z) points?

The current API of QgsGeometry and QgsAbstractGeometry can only add Z (or M) to all the points at once. So if it possible to have polygons or lines with mixed point it would be needed to expande the api with a vertex parameter. Like in this draft PR #51271

Otherwise, if the assumption is correct, what value should be added for Z for the "other" points? The same of the snapped point? Or `0`? Or `NaN`. I would say `NaN`.

**Comment by nyalldawson** [comment]
@domi4484 

> Is it reasonable to assume that a polygone or line doesn't have mixed (with and without Z) points?

That's correct. There's some ad-hoc workarounds for this used, such as nan values or some user defined "null" value (eg -9999). But generally it's all or nothing.

**Comment by domi4484** [comment]
Ok thanks
