### ISSUE TITLE
Crimea should be not a part of Russia in world_map.gpkg

### ISSUE THREAD

**Issue by dubravat** [qgis/QGIS#46810]
### What is the bug or the crash?

The bug is about the "world_map.gpkg" located in the https://github.com/qgis/QGIS/tree/master/resources/data.

This GeoPackage contains data incorrectness: Crimea is a part of Russia.
I believe you understand why it is wrong.

Therefore, I am kindly asking you to apply the corresponding changes.
Please, make Crimea a part of Ukraine.

### Steps to reproduce the issue

I was able to observe it here: https://gis.stackexchange.com/a/420610/99589

### Versions

QGIS 3.20 Odense

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by jef-n** [comment]
The data originates from natual-earth (see [README_world_map.md](../blob/master/resources/data/README_world_map.md))

**Comment by Andygol** [comment]
ping @alexbruy

**Comment by m-kuhn** [comment]
Upstream issue

https://github.com/nvkelso/natural-earth-vector/issues/680

**Comment by Andygol** [comment]
Why do you use NEd when it exists other sources for boundaries?

https://www.geoboundaries.org/downloadCGAZ.html (RE https://twitter.com/osm_ua/status/1368103088263954436?s=20&t=WR0ZQY1mxBMCfygAGitXuA)

**Comment by m-kuhn** [comment]
@Andygol I don't think there was a large process about pros and cons of different data sources conducted. At the time of inclusion the main idea was to make qgis better by having a world dataset ready for users.

If you think something else would be better, the best is to provide options/reasons/a comparison and an updated dataset ideally in the same format as currently present.

**Comment by Andygol** [comment]
@m-kuhn what about to approve this PR https://github.com/qgis/QGIS/pull/48120 ?

**Comment by m-kuhn** [comment]
I think there are open questions to be addressed.

**Comment by Symbian9** [comment]
> I think there are open questions to be addressed.

Which one open? Crimea is Ukraine de jure since 1991:

- https://en.wikipedia.org/wiki/Crimea#Ukraine_(de_jure_since_1991,_de_facto_1991%E2%80%932014)
  - https://en.wikipedia.org/wiki/United_Nations_General_Assembly_Resolution_68/262
  - https://en.wikipedia.org/wiki/United_Nations_General_Assembly_resolution_A/73/L.47

**Comment by m-kuhn** [comment]
Technical ones
https://github.com/qgis/QGIS/pull/48120#issuecomment-1092106542 and subsequent

**Comment by arminiusresistance** [comment]
@dubravat 
@m-kuhn 
I believe the occupied areas of Palestine since 1948 are not part of Israel. We can use other open source tools which tell the real true maps.
