### ISSUE TITLE
Non retention of pop-up window placement and size

### ISSUE THREAD

**Issue by peterc1950** [qgis/QGIS#46819]
### What is the bug or the crash?

I'm using Windows 10 and I find it very frustrating that every time I open a pop-up window it is a different size and/or it is in a different place on the screen. It seems not to resize on my main screen, but does move down each time until the buttons dissapear, but on the other secondary they usually end up too large and the buttons are off the sceen at the bottom straight away. I've seen a comment that other programs do this, but none I use have this issue.

### Steps to reproduce the issue

Using more than 1 screen, open a pop-up and move it to a different screen to the main QGIS desktop. Close and open the pop-up again and it is either resized and/or moved to a diffent place on the screen

### Versions

Current using 3.22.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
> Using more than 1 screen, open a pop-up and move it to a different screen to the main QGIS desktop. Close and open the pop-up again and it is either resized and/or moved to a diffent place on the screen

@peterc1950 just tested with "settings > options" and cannot confirm. Using  a laptop and a external 2k monitor. QGIS 3.22.2 on Windows.

**Comment by peterc1950** [comment]
Try 'Identify features' (Ctrl-Shift-I) on an element. This is where I really noticied it first and have been using it a lot lately.

**Comment by nicogodet** [comment]
duplicates https://github.com/qgis/QGIS/issues/44050 ?

**Comment by peterc1950** [comment]
It looks like it could be a duplicate of #44050

**Comment by gioman** [comment]
> Try 'Identify features' (Ctrl-Shift-I) on an element.

@peterc1950 identify form/dialog works ok for me.

**Comment by gioman** [comment]
> @peterc1950 identify form/dialog works ok for me.

Correction: size is ok. position is slightly lower compared to the one defined manually the first time.

**Comment by peterc1950** [comment]
All the pop-ups in the Vector -> Geometry Tools are particularly bad ones. Always too wide and too low and I have to resize every time.

**Comment by peterc1950** [comment]
Try with the pop up on a smaller resolution screen or one with larger scale. My main is 1920 x 1080 as is my secondary screen which is my laptop with a scale of 125% (as recommended!!)

**Comment by gioman** [comment]
> My main is 1920 x 1080 as is my secondary screen which is my laptop

@peterc1950 unclear. Is  1920 x 1080 your main screen (laptop) or the external one? is 125% scaling on the main or secondary?

**Comment by peterc1950** [comment]
@glowman Sorry, to be clear, my main display is my monitor with 100% scaling and my laptop is my secondary display with scaling of 125%.

**Comment by gioman** [comment]
> @glowman Sorry, to be clear, my main display is my monitor with 100% scaling and my laptop is my secondary display with scaling of 125%. It is when the pop-up is on my laptop where the issue is noticeable

@peterc1950 tested also this scenario, still all ok on my machine.

**Comment by peterc1950** [comment]
@glowman Hmm, this is what I see
![QGIS Window](https://user-images.githubusercontent.com/97673494/149519004-7704feaa-7525-4359-b498-6d6be1d12438.jpg)

**Comment by gioman** [comment]
> Does the window need to be this big in the first place?

@peterc1950 can't you resize it? if you resize it it does not stick?

**Comment by peterc1950** [comment]
@gioman Yes, I can resize it and it does stick, for a while at least. However, something, not yet identified as it could be after numerous other actions, resets it. Certainly it's resets every time I start the computer, so I will try to narrow it down. Even so, I still think the windows inital size could be reduced to something consideraly smaller in line with others in QGIS.

Issue #44050 still applies though with pop-ups moving down the screen each time they are opened until the buttons dissapear and could be related.

**Comment by gioman** [comment]
> Issue #44050 still applies

@peterc1950 this still applies and is confirmed by multiple users. What you describe in this ticket is not confirmed, not by me at least. It could be very well something very specific to your setup, still not a general issue.

**Comment by peterc1950** [comment]
@gioman Ok, understood, but I think it would be good to make the pop-up window initially smaller anyway, so perhaps a suggestion. Thanks for the feedback.

**Comment by gioman** [comment]
> the pop-up window initially smaller anyway

@peterc1950 that is another point: by default here it is not large as show (on multiple systems and 3 differents OSes).
Have you tried with a clean QGIS profile?

**Comment by peterc1950** [comment]
@gioman Hmmm!! I had tried a new profile and it's true, the window starts off as a normal size. Then after a couple of edits using the feature attribute pop-up, the line-to-polygon changed to oversize again. Resizing it worked repeatedly, even after again using the feature attribute. So, it is not something consistently reproducible and as you suggest may be something to do with my set-up. If I do find a way it is reproducible, I will note it.

**Comment by nanometrenat** [comment]
This solution helped for me:  https://github.com/qgis/QGIS/issues/45613#issuecomment-949824338
