### ISSUE TITLE
repeatedly crash issues in QGIS

### ISSUE THREAD

**Issue by FORFOR** [qgis/QGIS#46822]
## User Feedback

Crash ID: f1c4dc9d5e92e63f83782d3bb3daec3fee43bbe8

Stack Trace

QgsTemplatedLineSymbolLayerBase::renderPolylineVertex :
QgsTemplatedLineSymbolLayerBase::renderPolyline :
QgsHashedLineSymbolLayer::renderPolyline :
QgsLineSymbol::renderPolylineUsingLayer :
QgsLineSymbol::renderPolyline :
QgsSymbol::renderFeature :
QgsFeatureRenderer::renderFeature :
QgsMeshDatasetGroupTreeItem::setIsEnabled :
QgsMeshDatasetGroupTreeItem::setIsEnabled :
QgsMapRendererParallelJob::renderLayerStatic :
QgsMapRendererParallelJob::renderingFinished :
QgsImageOperation::overlayColor :
QgsImageOperation::flipImage :
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.16.15-Hannover
QGIS code revision: e7fdad6431
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

## Report Details

**Crash ID**: [f1c4dc9d5e92e63f83782d3bb3daec3fee43bbe8](https://github.com/qgis/QGIS/search?q=f1c4dc9d5e92e63f83782d3bb3daec3fee43bbe8&type=Issues)

**Stack Trace**
<pre>
QgsTemplatedLineSymbolLayerBase::renderPolylineVertex :
QgsTemplatedLineSymbolLayerBase::renderPolyline :
QgsHashedLineSymbolLayer::renderPolyline :
QgsLineSymbol::renderPolylineUsingLayer :
QgsLineSymbol::renderPolyline :
QgsSymbol::renderFeature :
QgsFeatureRenderer::renderFeature :
QgsMeshDatasetGroupTreeItem::setIsEnabled :
QgsMeshDatasetGroupTreeItem::setIsEnabled :
QgsMapRendererParallelJob::renderLayerStatic :
QgsMapRendererParallelJob::renderingFinished :
QgsImageOperation::overlayColor :
QgsImageOperation::flipImage :
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.16.15-Hannover
QGIS code revision: e7fdad6431
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

### Steps to reproduce the issue

open a project in QGIS 3.16.15 witn an already styled layers
try to zoom in or out
or create new one and try to apply layer style 

### Versions

3.16.15

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

it rashes when i zoom in or out just after opening a old project wich was made in an other station

**Comment by gioman** [comment]
@FORFOR have you really tested with a new QGIS profile? if yes then you must add more info, or even better a sample project+data.

**Comment by FORFOR** [comment]
what doest it mean QGIS profile i work on QGIS without any profile 
i uploaded my project that i made it on QGIS 13.16.8 on a work station in a company with a local network 
cos i extracted it to visualize the whole project in my personal PC equiped with QGIS 3.16.15 last Long term version running in 64 bits on Legion Lenovo recently Bought.

**Comment by FORFOR** [comment]
[Uploading test.zip…]()

**Comment by gioman** [comment]
> what doest it mean QGIS profile i work on QGIS without any profile

@FORFOR settings > user profiles > new profile

and when QGIS starts with the new profile do **not** install any 3rd party plugin before testing again.

**Comment by FORFOR** [comment]
@gioman 
ah okay
plugin or extensions i don't use the them for now
i got mention that now i just installed the older version of QGISv 3.16.0 and it is working fabulously, but still don't understand the prob with QGIS though.
Thanks anyway

**Comment by gioman** [comment]
> plugin or extensions i don't use the them for now

@FORFOR it is not always a matter of plugins, something are other (legacy) configs. Using a new profile ensures that your are using QGIS as it was just installed.

**Comment by stefaneidelloth** [comment]
I use QGIS 3.22.2 and try to run some python scripts. QGIS often crashes. Sometimes while typing. Sometimes the script is executed and then QGIS crashes.
