### ISSUE TITLE
On crash, QGIS deletes the shx, cpg and prj files

### ISSUE THREAD

**Issue by TehemGo** [qgis/QGIS#46838]
### What is the bug or the crash?

When QGIS crashes (which can happen on any processing that ran smoothly just minutes earlier -- this time around it was Filter, ten minutes earlier it was Concave Hull... tomorrow it may be another one),
QGIS _may_ corrupt the layer the crash-causing processing was applied on, and delete its shx, cpg and files.
The dbf and shp files are still there but QGIS can't open them (message : "2022-01-14T21:19:11     WARNING    Cannot open xxx.shp.(Unable to open xxx.shx or xxx.SHX. Set SHAPE_RESTORE_SHX config option to YES to restore or create it.)")

It looks like Bug #15570 https://issues.qgis.org/issues/15570, except no "xxx_packed.shx" files are created.

As it is, because I haven't found the SHAPE_RESTORE_SHX option yet, the layers are unusable for good.

### Steps to reproduce the issue

Wait for QGIS to crash.
After the crash, check the layers that were open before it -- the layer the processing was applied onto may be corrupt and unloadable, because its shx, prj and cpg files, which were there until the crash, have disappeared.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.18.3-Zürich | QGIS code revision | 735cc85be9
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | BezierEditing; LAStools; latlontools; numericalDigitize; profiletool; Qgis2threejs; quick_map_services; db_manager; MetaSearch; processing

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
> 3.18.3-Zürich

@TehemGo this is outdated and unsupported. You must upgrade to 3.22.2 and try again with a new QGIS profile and no 3rd party plugins installed (settings > user profiles > new profile). If the problem persist attach sample data.

**Comment by lieti** [comment]
I can confirm this bug. It happened to me few days ago. I was bit surprised and I was considering it like weird mistake from my side.
Unfortunately no way to reproduce this bug.  I was probably executing "map to raster function". I´m pretty sure that damaged SHP was not in edit mode (it was simple single feature polygon with EPSG:5514) I believe that it was on this configuration:

QGIS version
3.22.2-Białowieża
QGIS code revision
1601ec46d0
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.0
PROJ version
8.2.0
EPSG Registry database version
v10.038 (2021-10-21)
GEOS version
3.10.0-CAPI-1.16.0
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009




Active Python plugins
changeDataSource
3.1
processing
2.12.99

**Comment by gioman** [comment]
> I can confirm this bug. It happened to me few days ago. I was bit surprised and I was considering it like weird mistake from my side.
> Unfortunately no way to reproduce this bug. I was probably executing "map to raster function". I´m pretty sure that damaged SHP was not in edit mode (it was simple single feature polygon with EPSG:5514) I believe that it was on this configuration:

@lieti same advice as here https://github.com/qgis/QGIS/issues/46838#issuecomment-1013482203

**Comment by lieti** [comment]
Yes, I understand that without it it is kind of "anectodal" bug report
Unfortunately like I wrote, I´m not able to reproduce this bug again, it happened to me once.
