### ISSUE TITLE
Unable to edit the destination coordinates in the GCP table of the Georeferencer

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#46836]
### What is the bug or the crash?

Trying to change the destination coordinates in the gcp table, the text is reset every time. Note that the columns size also are reset.

https://user-images.githubusercontent.com/7983394/149552768-696f3170-6173-49c5-bf17-f80ecd131490.mp4

Works fine if I change source values.

### Steps to reproduce the issue

See above

### Versions

master 3.23

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
see also #32960 @DelazJ

**Comment by roya0045** [comment]
Was that ever a thing? By searching I see no instances where the values from the `QgsLayoutItemTextTable` are used to update the GCP. And that table is made to read data, even prior to my changes I can't see where this was actually possible in `qgsgeorefmainwindow.cpp` Maybe the bug is that it gives the impression of being a writable thing?

**Comment by DelazJ** [comment]
I don't know if it ever worked, but the "Add gcp points" dialog allows you to enter destination coordinates, instead of clicking on the map. Now let's assume that you enter a wrong destination coordinate. How do you fix that?

**Comment by roya0045** [comment]
Yeah it looks doable. Now when it comes to changing dest coords, the issue is: if a transformation has been applied already, does the user wants to change the final coords or the input coords. Both are distinct and now it should change input.

**Comment by roya0045** [comment]
Ok I tested and it works as intended. I think the problem is that the data shown and edited is the transformed coord but in fact it changes the gcp coord (associated with the original crs).

One way to test is within the same CRS and with small round number ( between 0 and 1000).

**Comment by roya0045** [comment]
@Delaz I can't confirm either on linux or windows, it's just that output crs with long coords that get shortened make it hard to see.

**Comment by DelazJ** [comment]
@roya0045 I'm not sure whether I misunderstand but isn't my video above a confirmation? I change the thousand digit so even with the shortened notation here, it should display some change to the value. And when I double-click after a first change, still the original value.

**Comment by gioman** [comment]
> I'm not sure whether I misunderstand but isn't my video above a confirmation? I change the thousand digit so even with the shortened notation here, it should display some change to the value. And when I double-click after a first change, still the original value.

I see the same here.

**Comment by roya0045** [comment]
I'm not sure if this is because the output crs is not set or just something else. I'll try tomorrow without setting a destination crs to see if that's the issue but I'm not sur how it could be the case. Maybe the problem is the crs used (I'm not sure why all values are the same in the table.) If you could try a version with my proposed fix that could clear things up as I got it to work properly on both 3.23 and 3.22.2.

**Comment by DelazJ** [comment]
> I'm not sure if this is because the output crs is not set or just something else. 

In this case, it was set, same as the one of the points (but different from project's). FYI  i was doing this exercise https://docs.qgis.org/testing/en/docs/training_manual/forestry/map_georeferencing.html.
> I'm not sure why all values are the same in the table

Because I did enter the same values, hoping that I could edit them afterwards. I didn't want to do calculation at the beginning and just added the points with fake values in the hope I could fill in the right destination values based on the screenshot of the lesson. Fail.
So, just ignore that.

**Comment by DelazJ** [comment]
> If you could try a version with my proposed fix that could clear things up as I got it to work properly on both 3.23 and 3.22.2.

You mean #46842? Will do later in the next week. Thanks

**Comment by roya0045** [comment]
Try with any crs that has shorter coords and it shows up fine. I really can't replicate.

**Comment by gioman** [comment]
> Try with any crs that has shorter coords and it shows up fine.

@roya0045 but that is not just a specific case? It should work for any case.

**Comment by roya0045** [comment]
> > Try with any crs that has shorter coords and it shows up fine.
> 
> @roya0045 but that is not just a specific case? It should work for any case.

If the value had a more significant change ( set it to 10 or - something) then maybe it would appear fine. It's possible that the formatted number is what is displayed when editing it instead of the real value. And that could be why the minor changes (less than 1%) were not apparent.

**Comment by uclaros** [comment]
I can confirm this is kind of messed, and the level of messed depends on the selected target crs.
With an undefined target crs I cannot change the values (it definitely used to work before merging the transformations PR)
When setting crs to 2100 it works, typing in values get properly updated.
When changing to 4326, the values are transformed but when I try to edit them the values I enter are interpreted as 2100 coords, so the values do change but not to what I type in. Changing back to 2100 I see the values I previously typed.

**Comment by roya0045** [comment]
@uclaros the values changed are the point coords and not the transformed ones. The best options would be to add two columns to have both the original point coords and the transformed coords displayed alongside, maybe even the crs.

**Comment by roya0045** [comment]
I'll show both and the gcp crs authid in the table. PR should be up in a few days depending on other eventual PR, should also fix the notation thing.
