### ISSUE TITLE
GCP table in the Georeferencer shows coordinates in scientific notation

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#46835]
### What is the bug or the crash?

I'm trying to georeference an image and after some points this is what the table shows (check the dest x and y)
![image](https://user-images.githubusercontent.com/7983394/149550927-a1a47457-d257-4693-b21c-6c7f21b0573c.png)

### Steps to reproduce the issue

see above

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.23.0-Master | QGIS code revision | df64116867
-- | -- | -- | --
Qt version | 5.12.8
Python version | 3.8.10
GDAL/OGR version | 3.0.4
PROJ version | 6.3.1
EPSG Registry database version | v9.8.6 (2020-01-22)
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
SQLite version | 3.31.1
PostgreSQL client version | 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.2
OS version | Ubuntu 20.04.3 LTS
  |   |   |  
This copy of QGIS writes debugging output.
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
see also https://github.com/qgis/QGIS/issues/32960 @DelazJ

**Comment by roya0045** [comment]
What is the destination crs? (@gioman I just now saw that you pinged me, but I didn't fiddle with the table.) I'll try to see if something can be done. I'm also unsure why the scientific notation, must be coming from another part of code used to display numbers.

**Comment by roya0045** [comment]
I assume the trick would be to not format number as `QString::number( ( *gcpIt )->transCoords().y(), 'f', 3 ) ` is the default. Which seem to have been there since a long time. 

It's changeable easily though.

**Comment by DelazJ** [comment]
> What is the destination crs? 

Epsg 2392. I was trying to update https://docs.qgis.org/testing/en/docs/training_manual/forestry/map_georeferencing.html

**Comment by roya0045** [comment]
Ok the issue is in gcpmodel instead. The problem is qt not cooperating when formatting long floats...

**Comment by roya0045** [comment]
Data is parsed through `QgsStandardItem` at https://github.com/qgis/QGIS/blob/c5a56d6f83e08b77967326add5ad215e3a0c948e/src/app/georeferencer/qgsgcplistmodel.cpp#L138 
And that just converts the number to string, the conversion relies on QT formatting the number at https://github.com/qgis/QGIS/blob/c5a56d6f83e08b77967326add5ad215e3a0c948e/src/app/georeferencer/qgsgcplistmodel.cpp#L42

**Comment by roya0045** [comment]
Should be fixed.
