### ISSUE TITLE
Selectable Styles Added on Layers Property Aren't Saved or Copied

### ISSUE THREAD

**Issue by ttreker** [qgis/QGIS#46848]
### What is the bug or the crash?

Adding selectable style collections from the styles button on the Layer Properties dialog aren't saved when either saving style files or copying styles from the Layer Context Menu. I assume that this is a bug since the documentation seems to imply that all layer properties should be saved when saving or copying. This sure seems to be a layer property. If it is one would expect that it would be saved (hence adding this as a bug and not a feature request). Being able to copy quickly selectable collections of layer/style properties from one layer to another is a real time saver. Btw, it does work when duplicating a layer:

![Style Save Bug](https://user-images.githubusercontent.com/5962712/149645846-8f83ec20-67c0-4cfe-bf5c-76095719da7a.png)

### Steps to reproduce the issue

1. Pick a suitable layer and create a duplicate of it for later in this procedure.
2. Bring up the Layer Properties Dialog on the original layer.
3. Configure some unique styles as desired and click the _OK_ button on the dialog.
4. Bring the same dialog up again, click the _Style_ button next to the _Help_ button in the lower left of the Layer Properties dialog.
5. Click the _Add..._ menu item, enter a new style name and click the _OK_ button.
6. Click the _OK_ button on the Layer Properties dialog.
7. Repeat steps 2 to 6 a time or two more for good measure.
8. Check the Layer Context menu _Styles_ menu to see that the selectable style items have been added along with the default.
9. From this same menu select _Copy Style_ and then _All Style Categories_.
10. Bring up the context menu on the duplicate layer created above and select _Paste Style_ then _All Style Categories_.

Note that styles have been properly transfered but not the added selectable styles. This is the bug.

If you save the styles from the _Style_ button menu on the Layer Properties dialog the _Save All_ button will save 3 separate style files using the provided file name as the root of the name of these three files with numbers (not even the names of the added styles). No style selection names are associated in any way with these saved collections of styles which means you have to rename and add each of these files all over again for each layer, a time consuming process.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.18.3-Zürich | QGIS code revision | 735cc85be9
-- | -- | -- | --
Compiled against Qt | 5.11.3 | Running against Qt | 5.11.3
Compiled against GDAL/OGR | 2.4.0 | Running against GDAL/OGR | 2.4.0
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.27.2 | Running against SQLite | 3.27.2
Compiled against PDAL | 1.8.0 | Running against PDAL | 1.8.0 (git-version: Release)
PostgreSQL Client Version | 11.11 (Debian 11.11-0+deb10u1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.10.4
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Debian GNU/Linux 10 (buster)
Active python plugins | nominatim_locator_filter; profiletool; qgisnetworklogger; latlontools; db_manager; MetaSearch; processing

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

I didn't try with a new profile for this particular bug. Last time I created a new profile to test and went back to my old profile things got a bit screwed up. I lost configuration even though I had save. I am leery of creating a new profile to test this but if anyone insists I will.

I know this is a gray area between bug and feature request. Given the save styles saves three files, I can see the potential issue here, but certainly the Copy/Paste styles should work even if saving the styles in one file with the style names is a feature request given the way it works now, copying and pasting the styles from layer to layer should work within the running system.

Thanks for consideration of this issue. I expect it won't be the highest priority but it would be nice to consider this issue for future versions.

I don't know about other users but I tend to have a plethora of layers while hacking away with similar schemas in differing datastores or memory layers. It would be really nice to quickly be able to apply consistent styles to them.

**Comment by ttreker** [comment]
I know one shouldn't pile lots of issues into one issue report but I have played around a little bit more with the _Add-Styles_ and have perceived a general flakiness that is difficult to characterize. This has lead me to believe that perhaps the whole feature should be revisited and rethought out. Here are some other issues (without great detail) just to maybe backup this thinking:

1. On the Layer Properties dialog, select an added style doesn't do anything. Nothing changes. To change to a different added style you have to leave the dialog and change it from the layer context menu then come back into the Layer Properties dialog.
2. You can't update an added style. You can only remove it or rename it.
3. If you remove the current style, what style goes with what name rotates or shuffles so that the names no longer match the original styles that had been associated with them!

The whole system is just rather flaky. Here is a list of some of the ways I think is should work:

- Add, update, remove a layer's "added" styles (I am not using "saved" styles here because that means something different).
- Should be able to select the added style in the Layer Properties dialog, make some changes and then resave it (an update)
- All alternative styles should be saved with the layer properties, saved in a single external store (file, DB, etc. when using save instead of add) under a single name that associates the originally chosen name with each property set. You should be able to load them all as a set of added layers as originally stored or select which to load.
- Instead of name a layer "default" you should be able to set a layer set as the default.
- Copying the styles from the context menu should copy all of these added sets to different layer.
- It is difficult to describe all this because of nomenclature. What is "add" adding? A properties set? It isn't just styles, right? There is external saving and there is adding with a name? A rework of nomenclature might be in order. In fact, if the nomenclature is clearly thought out this could help spec out how it should really all work.

So maybe this is just a feature request. If this system were to work this way it would be really nice.

Right now, honestly, it just seems unusable.

(Btw, no compaints here! QGIS is an absolutely brilliant piece of work that I do not take for granted. Its breadth and depth astounds me. The bulk of it works amazingly well and it just keeps getting better over the years. I offer reporting these issues as a way to give back, not gripe. I have no expectations of any responsiveness to this issue by the QGIS team. I don't know where this would fit into your priorities. I am just offering my perspective. Thanks for your efforts)

**Comment by DelazJ** [comment]
>  I assume that this is a bug since the documentation seems to imply that all layer properties should be saved when saving or copying.

Can you provide the doc link, please? Just to get sure we understand the same thing, and whether the docs is not misleading people.
> No style selection names are associated in any way with these saved collections of styles which means you have to rename and add each of these files all over again for each layer, a time consuming process

Lucky, you! Changes done in #46598. Could get back to it by the end of next week
> Copy/Paste styles

Here's IMHO the mistake. You do **NOT** copy styles. You copy **style categories**, that is categories of the active style, properties stored in the active style. 
> 3.18.3-Zürich

I can understand you are reluctant to use a new profile, though I'm surprised it could break anything on another profile (profiles ignore each other). But this version is unmaintained. You need 3.22
> I know one shouldn't pile lots of issues into one issue report but[...]

Then don't do it!
This leads to a waste of time for the developers. Hard to tell now what this report is really about.
> 1. On the Layer Properties dialog, select an added style doesn't do anything. Nothing changes. To change to a different added style you have to leave the dialog and change it from the layer context menu then come back into the Layer Properties dialog.

What do you mean by "nothing changes"? Having played with that widget 3 weeks ago, I can say there's no need to go through the layer context menu to switch active style.
> 2. You can't update an added style. You can only remove it or rename it.

Not true. The active style auto updates. Any changes you do on the layer properties are directly saved in the active style. In the docs.
> 3. If you remove the current style, what style goes with what name rotates or shuffles so that the names no longer match the original styles that had been associated with them!

Never noticed this. But you'd need to check if it's still the case in a supported version.

**Comment by ttreker** [comment]
"Then don't do it!
This leads to a waste of time for the developers. Hard to tell now what this report is really about."

Fair enough. Sorry about that. I won't do that again.

I am reviewing your comments and will work up a focused and clear response to avoid wasting your time...

**Comment by ttreker** [comment]
Doc link:
https://docs.qgis.org/3.16/en/docs/user_manual/introduction/general_tools.html#manage-custom-style
Relevant quote:
"A style stores **any information set in the layer properties dialog** to render or interact with the layer (including symbology, labeling, fields and form definitions, actions, diagrams…) for vector layers, or the pixels (band or color rendering, transparency, pyramids, histogram …) for raster."

My logic was, when reading this, the added names were references to sets of properties and so this set of references was a property itself being on the Layer Properties Dialog and so would be stored with the layer properties. On retrospect I can see this could quite plausibly lead to a circular reference within the layer properties. Still, I hope you can see, from a usability standpoint, why it could seem reasonable to expect that these references would be able to be copied from one layer to the next given creating new layers from existing data is a common occurrence in QGIS. Having to redefine these sets on each new layer isn't the most ideal. This expresses my thinking that lead to this report.

I am not sure how the doc could have made this clearer.

> Here's IMHO the mistake. You do NOT copy styles. You copy style categories, that is categories of the active style, properties stored in the active style.

I am not certain I follow what you think I don't understand, but maybe I have already cleared this up.

> I can understand you are reluctant to use a new profile, though I'm surprised it could break anything on another profile (profiles ignore each other). But this version is unmaintained. You need 3.22

I can provide nothing repeatable about the fresh-profile issue other than I lost all my spatial bookmarks and plugins and this was the only thing I could think of that did that. I save all the time so it wasn't that. I created a fresh profile for my last bug report which you guys fixed and merged just recently. 

Regarding 3.22 I would absolutely love to upgrade to it. Short of building QGIS from scratch I am not sure how to go about doing it. I am on Debian Buster and have followed the QGIS instructions for upgrading to 3.22 many times. It never upgrades, it always leaves me at 3.18. I haven't gone to the community for solutions to that problem so unless you have a quick one I don't expect you to waste your time on it.

> What do you mean by "nothing changes"? Having played with that widget 3 weeks ago, I can say there's no need to go through the layer context menu to switch active style.

I click it, I can see the dot briefly jump to the style set, nothing changes, I open the menu again and the dot is still on the same style.

> Not true. The active style auto updates. Any changes you do on the layer properties are directly saved in the active style. In the docs.

That makes sense now. Had I been able to change styles without leaving the dialog I am sure I would have picked up on this. I was just looking for an explicit update menu item, but it is now clear that isn't necessary.

Upshot:

- Doc may be somewhat nebulous but probably not incorrect.
- I need to get on 3.22 somehow (don't really want to go down the build path, rather a repository solution)
- I'll chalk the other issues up to a need for upgrade.

Thanks for your patience and time, @DelazJ. I'm usually better at discerning community support issues from bugs. This was really closer to a community support issue in retrospect but it looked like a bug to me at the time.

From my perspective this issue is closed.

**Comment by gioman** [comment]
> Short of building QGIS from scratch I am not sure how to go about doing it. I am on Debian Buster and have followed the QGIS instructions for upgrading to 3.22 many times

@ttreker as stated here https://qgis.org/en/site/forusers/alldownloads.html#id15 with Buster you'll get only up to 3.18 as GDAL is too old for 3.22.

> I can provide nothing repeatable about the fresh-profile issue other than I lost all my spatial bookmarks and plugins and this was the only thing I could think of that did that.

when you create a new profile you don't delete/loose anything, you just create a new fresh profile, and can always open QGIS with the old one.

**Comment by ttreker** [comment]
> @ttreker as stated here https://qgis.org/en/site/forusers/alldownloads.html#id15 with Buster you'll get only up to 3.18 as GDAL is too old for 3.22.

I just built GDAL 3.41 to run ogr2ogr in order to import gpx data into PostGIS. So far imports have worked. Should I expect some issues running GDAL 3.4.1 on Buster? Why won't QGIS build on Buster with the latest GDAL?

Does QGIS compile in its own GDAL libraries or expect a GDAL package dependency of Linux? I am assuming the former as the reported GDAL version in QGIS is different than what is in my library path.

Re: the profile issue, I really don't know why I lost config. It was a week or two before I noticed missing config so I only got paranoid that it was the profile switching. I didn't demonstrate any kind of repeatable issue.

At this point I will assume it wasn't a profile issue and if I post another bug report I'll first test with a fresh profile.

Are you supporting 3.18 still? If it is the only thing installable on Buster or Unbuntu I would assume you are.

If you are still supporting 3.18 on Buster and providing updates to the repository then I would like to leave the following issue open:

> On the Layer Properties dialog, select an added style doesn't do anything. Nothing changes. To change to a different added style you have to leave the dialog and change it from the layer context menu then come back into the Layer Properties dialog.

Assuming you can give this a priority, that is. I will use this feature.

**Comment by gioman** [comment]
> Does QGIS compile in its own GDAL libraries or expect a GDAL package dependency of Linux? I am assuming the former as the reported GDAL version in QGIS is different than what is in my library path.

@ttreker no, is the latter. QGIS istalled from repos uses dependencies as available on a specific distribution. What you have in your path is probably GDAL that have you compiled yourself. And honestly, compiling QGIS is not more difficult than compiling GDAL.

> Are you supporting 3.18 still?

no.

**Comment by gioman** [comment]
> If it is the only thing installable on Buster or Unbuntu

Only for Ubuntu 18.04, and in this case because Python is too old there.

**Comment by ttreker** [comment]
Ok. I'll look into building it soon. Thanks for your help.

Btw, I just added a fresh profile and am on the verge of testing the issue of the active styles not being selectable on the Layer Properties dialog. I'll let you know how it goes.

Your web site install instructions conflate Debian and Ubuntu, btw.

You imply there might be Python issues? If I build QGIS from scratch is it going to use the GDAL I just built? How about Python? Am I going to run into dependency issues?

Or is it just you haven't had the resources to keep the builds on these systems up to date in your repositories because the user base on these platforms isn't that deep?

**Comment by ttreker** [comment]
Just tested it on a fresh profile and the problem still exists. I added a single vector layer and an OSM layer.
I added three Styles. I can switch them from the context menu but not in the Layer Properties dialog. I select them and they stay in place.

**Comment by ttreker** [comment]
thanks for your help!

**Comment by gioman** [comment]
> Just tested it on a fresh profile and the problem still exists.

@ttreker you still need to check on 3.22. You can use a VM for that if you have troubles upgrading on Buster.

**Comment by ttreker** [comment]
OK! I'll look for a VM

**Comment by gioman** [comment]
> am guessing you had some VM-type approach in mind.

@ttreker with your preferred virtualization software, install Debian/Ubuntu/etc and then in it install QGIS with the qgis.org's repos.

**Comment by ttreker** [comment]
Ok, that sounds reasonable, but it implies there is an active Github 
branch not yet released for Debian:

  * Is there?
  * What branch would that be?
  * Debian Buster or Bullseye?

**Comment by gioman** [comment]
> but it implies there is an active Github branch not yet released for Debian:

@ttreker is much simpler than you are thinking: just install  in a new VM a OS were you know QGIS 3.22 is supported (in your case Bullseye), then in it add the qgis.org's repos (https://qgis.org/en/site/forusers/alldownloads.html#repositories) and install QGIS.

**Comment by ttreker** [comment]
Got it!
I run Buster in a VM so I'll just snapshot it and upgrade to Bullseye.

This is the first time anyone has mentioned that 3.22 runs on Bullseye. Up to this point I was under the impression QGIS 3.22 wasn't running on any version of Debian. Further, earlier it was mentioned that building QGIS wasn't any more difficult than building GDAL which I had mentioned I had just recently done.

Hence this is why I thought you guys were steering me in the direction of building QGIS to test it.

Two questions:

1. Is building QGIS from a repo really pretty straight forward? I'll consider it if it is mostly just the build time. If it leads to dependency hell regularly I am not inclined. But...
2. Containers can minimize OS dependency conflicts. What are the Docker images used for? Is there doc on bringing them up anywhere?

**Comment by gioman** [comment]
> 1. Is building QGIS from a repo really pretty straight forward?

@ttreker no build/compilation whatsoever, with the repos you install deb packages.

**Comment by ttreker** [comment]
I didn't make myself clear. There are two issues here:

The first:
How to get the test of the _Active Style_ system done on 3.22 in order to close this bug report.

The answer:
I am going to upgrade my Buster VM to Bullseye to test it. I know how to install from the apt repos.

I'll post my results here within the next couple of days. If the problem is resolved we can close this.

The Second:
Regarding the future: I think I might have an interest in building QGIS from scratch if it is primarily just an issue with build time and not dependency hell. So my questions in the last post pertain to the future, not testing the _Active Style_ bug.

I can navigate the build environment just fine via your docs. I just want to know if I am opening a can of worms or I can expect that, in general, builds should go smoothly (just take time). (Bear in mind, I really don't recall ever seeing a QGIS update when upgrading with apt. I would like to keep current!)

Also, containerizing can provide nice isolation, minimize dependency issues and ensure necessary toolsets are installed so I am inquiring about your containers.

**Comment by ttreker** [comment]
Upgrade isn't quite stable, but was able to get a clean QGIS running and 
the /Active Style /menu switch worked on QGIS 3.22.

I am having issues with PostGIS/Postgresql so I can't yet test the full 
up project. This may take some time to work out the issues.

Thanks for all your help

For reference:

QGIS version

	

3.22.3-Białowieża

	

QGIS code revision

	

1628765ec7 <https://github.com/qgis/QGIS/commit/1628765ec7>

Qt version

	

5.15.2

Python version

	

3.9.2

GDAL/OGR version

	

3.2.2

PROJ version

	

7.2.1

EPSG Registry database version

	

v10.008 (2020-12-16)

GEOS version

	

3.9.0-CAPI-1.16.2

SQLite version

	

3.34.1

PDAL version

	

2.2.0

PostgreSQL client version

	

13.5 (Debian 13.5-0+deb11u1)

SpatiaLite version

	

5.0.1

QWT version

	

6.1.4

QScintilla2 version

	

2.11.6

OS version

	

Debian GNU/Linux 11 (bullseye)


	
	
	

Active Python plugins

nominatim_locator_filter

	

0.2.4

qgis_resource_sharing

	

0.16.0

profiletool

	

4.2.1

qgisnetworklogger

	

0.2.0

latlontools

	

3.5.10

grassprovider

	

2.12.99

sagaprovider

	

2.12.99

db_manager

	

0.1.20

MetaSearch

	

0.3.5

processing

	

2.12.99

**Comment by gioman** [comment]
> and the /Active Style /menu switch worked on QGIS 3.22.

@ttreker can we close this?

**Comment by ttreker** [comment]
Yes, the switch worked.

Yes, you can close it.

(There may be another bug report coming soon. So far I can't get even a 
simple project from 3.18 to load without hanging QGIS on 3.22 Bullseye. 
Only newly created projects work so far.)
