### ISSUE TITLE
QGIS crash when opening a project file

### ISSUE THREAD

**Issue by HarryEClarke** [qgis/QGIS#46843]
## User Feedback

Opening a project

## Report Details

**Crash ID**: [e2c9ca8552cd85ce1188006825b7e771aec1c0d8](https://github.com/qgis/QGIS/search?q=e2c9ca8552cd85ce1188006825b7e771aec1c0d8&type=Issues)

**Stack Trace**
<pre>
QMetaObject::disconnect :
QObject::disconnectImpl :
QgsMapCanvas::stopPreviewJobs :
QgisApp::addProject :
QgisApp::fileOpen :
QObject::qt_static_metacall :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QMenu::metaObject :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.22.2-Bia?owie?a
QGIS code revision: 1601ec46d0
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.0
Running against GDAL: 3.4.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

### Steps to reproduce the issue

1. Open project A and view data
2. Save Project A changes (minor)
3. Open project B
4. QGIS crashes, but does not reload
5. Manually restart QGIS
6. Open  project B (without problems)

### Versions

The current released version of QGIS is 3.22.2. 
We are working on 3.23-Master. It will go into feature freeze on 2022-01-14 12:00:00 UTC and be released as 3.24 on 2022-02-18 12:00:00 UTC. 
Details on changes can be found on github at https://github.com/qgis/QGIS/commits/master. 

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
> * Open project A and view data
> 
> * Save Project A changes (minor)
> 
> * Open project B
> 
> * QGIS crashes, but does not reload
> 
> * Manually restart QGIS
> 
> * Open  project B (without problems)

@HarryEClarke you really have to test with a new QGIS profile:

settings > user profiles > new profile

and do not install any 3rd party plugin. Thanks.
