### ISSUE TITLE
Qt5 error in containerized version of QGIS

### ISSUE THREAD

**Issue by lgorenstein** [qgis/QGIS#46841]
### What is the bug or the crash?

I am trying to run containerized version of QGIS on a high-performance computing cluster.  Docker is not supported on the cluster (due to elevated privileges), but Singularity containers are embraced - so I am using Singularity's built-in feature to pull down QGIS container from DockerHub and convert it to Singularity format.

Conversion goes without a hitch, but execution throws a weird Qt5 error:
```
$ singularity pull qgis-3.16.sif docker://qgis/qgis:release-3_16     # generates qgis-3.16.sif
$ singularity exec qgis-3.16.sif qgis
/usr/bin/qgis: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
```

Which is clearly not true:
```
$ singularity exec qgis-3.16.sif find /usr -name 'libQt5Core.so.5*' -ls
   122133      0 lrwxrwxrwx   1 root     root           20 Jan  5 13:54 /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 -> libQt5Core.so.5.12.8
   122134      0 lrwxrwxrwx   1 root     root           20 Jan  5 13:54 /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.12 -> libQt5Core.so.5.12.8
   122135   5391 -rw-r--r--   1 root     root      5519624 Jan  5 13:54 /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.12.8
```
(note that these are inside of the container, just as they should).

It appears that this very error when running Qt5 applications in some kind of virtualized environment (Docker, Virtualbox, WSL1) is a fairly known thing.  E.g.:
  * https://stackoverflow.com/questions/63627955/cant-load-shared-library-libqt5core-so-5
  * https://github.com/linuxserver/docker-qbittorrent/issues/103
  * https://askubuntu.com/questions/1034313/ubuntu-18-4-libqt5core-so-5-cannot-open-shared-object-file-no-such-file-or-dir

For all of them, the (very bizarre, but working) solution seems to add one extra command to the Dockerfile:
```
strip --remove-section=.note.ABI-tag /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
```
and the problem disappears.

I was wondering if you'd be willing to add such a line to the QGIS container script.

### Steps to reproduce the issue

(assuming you have Singularity installed)
```
$ singularity pull qgis-3.16.sif docker://qgis/qgis:release-3_16
$ singularity exec qgis-3.16.sif qgis
/usr/bin/qgis: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
```

Observed the same for 3.22 as well.

### Versions

3.16 and 3.22 (per Docker tags)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
> I was wondering if you'd be willing to add such a line to the QGIS container script.

@lgorenstein you can submit a Pull Request and have it reviewed by QGIS core devs.

**Comment by lgorenstein** [comment]
@gioman I do not have a suitable Docker infrastructure to test - but happy to make a PR.
