### ISSUE TITLE
Faulty output from rasterizer

### ISSUE THREAD

**Issue by APOS80** [qgis/QGIS#46846]
### What is the bug or the crash?

bug

### Steps to reproduce the issue

Make a polygon scratch layer, add a column for integer values.
Make som polygons with integer values.

Open rasterize and chose the columns with values for use
set aditional fields.

Even though the range of values is 0-2 you get values in the millions.

### Versions

QGIS version
3.22.2-Białowieża

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
> Open rasterize

@APOS80 there are several tools to rasterize a vector in the Processing toolbox, which one you used?

**Comment by APOS80** [comment]
the one under raster>convert>rasterize

**Comment by APOS80** [comment]
Tested with the lts version.

it seems that setting an extent other than the vector layer used gives it t he wrong pixel values

**Comment by gioman** [comment]
> raster>convert>rasterize

@APOS80 that tool defaults to float32, change the output data type with the "output data type" option.

**Comment by APOS80** [comment]
Managed it now, i think the problem can be that theres different projections

**Comment by gioman** [comment]
> Managed it now, i think the problem can be that theres different projections

@APOS80 can I close this?
