### ISSUE TITLE
Possibility to store settings used in Processing Toolbox - Aggregate

### ISSUE THREAD

**Issue by magerlin** [qgis/QGIS#46849]
### Feature description

Came across the Aggregate algorithm in the Processing Toolbox. And wow - this can replace a lot of calculations/programming I have previously done outside QGIS. 

But as Aggregate is actually doing your "programming" it would be very nice to be able to save "the programming" for later re-use:

![image](https://user-images.githubusercontent.com/1887531/149651100-cf44161d-ab09-4d5c-a38a-6a665559fa14.png)

**Comment by nyalldawson** [comment]
The best way to do this is to encapsulate those parameter values inside a simple model, which just runs the Aggregate algorithm with your desired configuration
