### ISSUE TITLE
File cannot open 

### ISSUE THREAD

**Issue by veraloo** [qgis/QGIS#46857]
### What is the bug or the crash?

File cannot open after import the layer of Google KMZ

### Steps to reproduce the issue

The following is the report of crashing. 

QgsProcessingDxfLayersWidget::setProject :
QgsEmbeddedSymbolRendererWidget::setContext :
QgsRendererPropertiesDialog::setContext :
QgsLayerStylingWidget::updateCurrentWidgetLayer :
QObject::qt_static_metacall :
QListWidgetItem::`default constructor closure' :
QObject::qt_static_metacall :
QItemSelectionModel::setCurrentIndex :
QListWidget::setCurrentRow :
QgsLayerStylingWidget::setLayer :
QObject::qt_static_metacall :
QgsMapLayerComboBox::layerChanged :
QObject::qt_static_metacall :
QAbstractItemModel::endInsertRows :
QSortFilterProxyModel::insertRows :
QSortFilterProxyModel::sortRoleChanged :
QSortFilterProxyModel::qt_static_metacall :
QObject::qt_static_metacall :
QAbstractItemModel::endInsertRows :
QgsMapLayerModel::addLayers :
QObject::qt_static_metacall :
QgsProject::layersAdded :
QObject::qt_static_metacall :
QgsMapLayerStore::layersAdded :
QgsMapLayerStore::addMapLayers :
QgsProject::addMapLayers :
QgsProject::addLayer :
QgsProject::_getMapLayers :
QgsProject::readProjectFile :
QgsProject::unzip :
QgsProject::read :
QgisApp::addProject :
QgisApp::fileOpen :
QObject::qt_static_metacall :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

### Versions

3.20

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
This issue is already fixed -- please update to a newer QGIS version
