### ISSUE TITLE
Rendering order in layer styling is not respected

### ISSUE THREAD

**Issue by antoniolocandro** [qgis/QGIS#46852]
### What is the bug or the crash?

I have a point layer of which I create a geometry generator in order to create a line. The points were to be shown on top of the line as per the symbol ordering however only one of the points is shown on top of the line and the other is below the geometry generated line.

### Steps to reproduce the issue

Video attached and sample points

https://user-images.githubusercontent.com/4627073/149668394-6d973e9c-1401-4fed-a2d4-0f703d9d8578.mp4

[point.zip](https://github.com/qgis/QGIS/files/7877356/point.zip)

### Versions

QGIS version
3.22.3-Białowieża
QGIS code revision
1628765ec7
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.0-CAPI-1.16.0
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
DigitizingTools
1.5.1
latlontools
3.5.9
MemoryLayerSaver
4.0.4
mmqgis
2021.9.10
quick_map_services
0.19.26
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
> [point.zip](https://github.com/qgis/QGIS/files/7877356/point.zip)

@antoniolocandro can you also add the style, or even better the project, within the sample GPKG? thanks.

**Comment by antoniolocandro** [comment]
Here is the attached project, I noticed that as I zoom in and out on the lower corner the point symbology sometimes renders correctly on the top, so maybe is a default option on the rendering 

[project.zip](https://github.com/qgis/QGIS/files/7882929/project.zip)

**Comment by gioman** [comment]
@antoniolocandro enable symbol levels

![image](https://user-images.githubusercontent.com/1951107/150170618-1e2d21d8-bc78-463b-a94f-d0706e02a3cd.png)

**Comment by antoniolocandro** [comment]
Ok that works! However I would be expecting that to be the default based on my symbol positioning, points on the top and line on the bottom. As it currently stands it seems that the visibility positioning is not being honored, also if I invert and put the line on the top it doesn't matter that symbol levels are not enabled the line works as expected check sample 2 from the attached file
[point2.zip](https://github.com/qgis/QGIS/files/7898948/point2.zip)

Seems to me that lines are treated with preference over points but inconsistently. I would think most users would expect the ordering of the symbols to influence the visibility. At least I know the workaround solution in the mean time

**Comment by antoniolocandro** [comment]
Can we remove the stale label, do not know what else to provide

**Comment by antoniolocandro** [comment]
again asking to remove the stale label please

**Comment by gioman** [comment]
> again asking to remove the stale label please

@antoniolocandro the stale label is removed as soon as a comment is left. What you need here is to confirm that this is a bug or if is the expected behavior.

**Comment by antoniolocandro** [comment]
In my opinion this is a bug, users will not expect that symbol levels need to be enabled in order for it to work. The expected behaviour is the symbol ordering to be respected

**Comment by antoniolocandro** [comment]
I still believe this is a bug
