### ISSUE TITLE
'QGIS Unexpectedly Ended' after using QField Sync

### ISSUE THREAD

**Issue by MaLyneEcology** [qgis/QGIS#46878]
### What is the bug or the crash?

I created a project in QGIS and all the shapefiles I need.  I then created a basemap usng MBTiles.  I then want to export this to my tablet so I selected 'Package for QField'.  I select the folder I want it to be saved into and click 'create'.  Then I get the error message saying 'QGIS unexpectedly ended'.  I've tried uninstalling the plugin and reinstalling.  I have tried uninstalling QGIS and reinstalling.  Nothing seems to work, I keep getting the same error message.  

Please could someone advise, thanks.  

Crash ID: 69743e41dbb4efc045eac61a8f81a6718f59c39b 

Stack Trace

QgsDefaultRasterLayerLegend::createLayerTreeModelLegendNodes :
QgsLayerTreeModel::addLegendToLayer :
QgsLayerTreeModel::refreshLayerLegend :
QgsLayerTreeModel::layerLegendChanged :
QObject::qt_static_metacall :
QObject::qt_static_metacall :
QObject::qt_static_metacall :
QgsRasterLayer::setRendererForDrawingStyle :
QgsRasterLayer::setDataProvider :
QgsRasterLayer::readXml :
QgsMapLayer::readLayerXml :
PyInit__core :
PyArg_ParseTuple_SizeT :
PyEval_EvalFrameDefault :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyFloat_FromDouble :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyFunction_Vectorcall :
PyFloat_FromDouble :
PyVectorcall_Call :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QObject::qt_static_metacall :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.16.15-Hannover
QGIS code revision: e7fdad64
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.0
Running against GDAL: 3.4.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

### Steps to reproduce the issue

Click on 'Plugins'

Go to 'QFieldSync'

Click on 'Package for QField'

Click on '...' in the Export Directory and select a folder.

Click on 'Create' 

See error message saying 'QGIS unexpectedly ended'

### Versions

QGIS Version: 3.16.15-Hannover

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
@MaLyneEcology you must report in the qfieldsync repo, not here.
