### ISSUE TITLE
Something simpler than SQL to filter a WFS layer

### ISSUE THREAD

**Issue by magerlin** [qgis/QGIS#46888]
### Feature description

In current versions of QGIS you need to know about SQL querying to filter a WFS layer. 

I would say that a lot of (potential) QGIS users do not necessarily know anything about SQL and it is in general not needed to know anything about SQL to work with QGIS.

I can see that is adds a lot of flexibility to the filtering but I think the average user would prefer a solution like when filtering a shp file:

![image](https://user-images.githubusercontent.com/1887531/150080104-dac57ca5-847b-4074-8ebb-66080ad2363e.png)

**Comment by pathmapper** [comment]
related: 

- https://lists.osgeo.org/pipermail/qgis-developer/2021-October/064180.html
- https://github.com/qgis/QGIS/issues/42800
