### ISSUE TITLE
Attributes Form and Attribute Table rounds real value to integer if "Range" widget type is used

### ISSUE THREAD

**Issue by phidrho** [qgis/QGIS#46884]
### What is the bug or the crash?

On data input through Attribute Form - if datatype is Real (double) - no decimal places are shown so user cannot know the exact data value on input. This happens after Attribute Form is customized to use "Range" widget type.
It also affects attribute table data presentation. Data is correctly saved (as double), but is only displayed - as integer.

I have tested this on layer stored in GeoPackage (attached) on newly created profile.
![number presentation](https://user-images.githubusercontent.com/1849293/149975038-1cec2f80-aaf4-41a1-8cb0-7fcbc1c69077.png)
![Attributes Form settings](https://user-images.githubusercontent.com/1849293/149975149-8bcbe2fa-ae10-46e3-a6bd-bf43a454b805.png)

### Steps to reproduce the issue

Use my [test.zip](https://github.com/qgis/QGIS/files/7890599/test.zip) with stored styling or:

- create a new layer with Real field on GeoPackage layer.
- set Attribute form to use "Range" Widget type
- create new features through attribute form
- check value on attribute table

### Versions

Windows 10

QGIS version
3.22.3-Białowieża
QGIS code revision
1628765ec7
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.0-CAPI-1.16.0
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by elpaso** [comment]
Did you try to set "Precision" in the advanced options?

**Comment by phidrho** [comment]
Didn't see that option.
That's it. I'm closing bug report.
