### ISSUE TITLE
SSL error when accessing the URL

### ISSUE THREAD

**Issue by ArturKhalilov** [qgis/QGIS#46889]
### What is the bug or the crash?

Good afternoon,
when connecting to QGIS, such a sign comes out. How to solve the problem?
Does not open the desired file, only you can close it.

SSL Errors
* Unable to Get Local Issuer Certificate: 
* Unable to Verify First Certificate: 

![image](https://user-images.githubusercontent.com/98011757/150081546-0d60125e-db43-4b5c-8284-4558e31c312a.png)

### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/98011757/150081870-3d79768c-411a-4c39-a2c9-93396356ef28.png)

### Versions

QGIS-OSGeo4W-3.16.9-1-Setup-x86_64

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by elpaso** [comment]
Have a look to https://docs.qgis.org/testing/en/docs/user_manual/auth_system/auth_workflows.html?highlight=ssl#ssl-server-exceptions

**Comment by ArturKhalilov** [comment]
Thank you)
