### ISSUE TITLE
New Illinois Projection

### ISSUE THREAD

**Issue by wellerc** [qgis/QGIS#46895]
### Feature description

I work for the State of Illinois at the Department of Transportation. Illinois has a new 33 zone projection that will be sanctioned in legislation this year. It is not yet NGS sanctioned, however it will be. ESRI and EPSG has already adopted these zones into their systems. They can be found here: https://clearinghouse.isgs.illinois.edu/data/reference/ics83-33-zone

We are extending this invite for QGIS to have these in their software as well.

Questions: cassidy.weller@illinois.gov or john.mellor@illinois.gov

**Comment by roya0045** [comment]
QGIS mostly relies on Proj, so as proj gets updated, the update will eventually find their way in QGIS.

I'm not sure there is much to be done if the changes are in the epsg database, they will be in QGIS eventually.

**Comment by nyalldawson** [comment]
Closing as an upstream request (which is already implemented in Proj)
