### ISSUE TITLE
It's not possible to edit imported table like .xlsx or .csv 

### ISSUE THREAD

**Issue by piwipiwipiwi** [qgis/QGIS#46894]
### What is the bug or the crash?

<img width="822" alt="Ohne Titel" src="https://user-images.githubusercontent.com/98036040/150156288-12203766-4cc3-43c2-aa60-a5a6dbeb926c.png">

### Steps to reproduce the issue

Add spreadsheet layer
Import table 
click on properties layer

It's not possible to edit imported table

### Versions

<img width="900" alt="Version" src="https://user-images.githubusercontent.com/98036040/150156324-6275c297-349b-498d-b161-f19530e7d2c4.png">

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@piwipiwipiwi this

[test.xlsx](https://github.com/qgis/QGIS/files/7898477/test.xlsx)

works just fine (added using QGIS, not the "spreadsheet layer" plugin). But you can find other XLSXs files where you cannot toggle editing. I guess it depends how they are created (the above was created from scratch on LibreOffice).

**Comment by gioman** [comment]
> It's no problem with windows QGIS version 3.10.

@piwipiwipiwi can you elaborate?

**Comment by piwipiwipiwi** [comment]
QGIS version 3.10 works well.
The problem appears with MacOS version 3.22.

**Comment by gioman** [comment]
> QGIS version 3.10 works well.

@piwipiwipiwi attach a sample xlsx.
