### ISSUE TITLE
Yellow Error on opening "Used a ballpark transform" 

### ISSUE THREAD

**Issue by Grgsj** [qgis/QGIS#46905]
### What is the bug or the crash?

Upon opening a project file in 3.22.3 I get a yellow error at the top of the map screen:

Used a ballpark transform from EPSG:26910 to EPSG:4326

Detail box:  Ballpark Transform Occured

An alternative, ballpark-only transform was used when transforming coordinates between EPSG:26910 - NAD83 / UTM zone 10N and EPSG:4326 - WGS 84. The results may not match those obtained by using the preferred operation:
+proj=pipeline +step +inv +proj=utm +zone=10 +ellps=GRS80 +step +proj=hgridshift +grids=WO +step +proj=unitconvert +xy_in=rad +xy_out=deg
Possibly an incorrect choice of operation was made for transformations between these reference systems. Check the Project Properties and ensure that the selected transform operations are applicable over the whole extent of the current project.

My project CRS is EPSG:29610

I would appreciate advice on how to correctly set the transformation or otherwise address the error

### Steps to reproduce the issue

Opening a new project file in 3.22.3 (also other versions)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.3-Białowieża | QGIS code revision | 1628765ec7
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.0-CAPI-1.16.0
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
autoSaver | 2.6
BezierEditing | version 1.3.2
FreehandRasterGeoreferencer | 0.8.3
Generalizer3 | 1.0
lftools | 1.4.1
mapflow | 1.5.2
qad | 3.0.4
qfieldsync | v3.4.4
SplitPolygonShowingAreas | 0.13
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.5
otbprovider | 2.12.99
processing | 2.12.99
sagaprovider | 2.12.99
CustomToolBar | 1.1

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

When I set up the new profile I got a red error that the WO file was missing.  I followed the instructions and downloaded the WO.TIF and renamed it in the proj directory under the new profile.  This removed the error but still gives me the Yellow ballpark transform error as before

**Comment by gioman** [comment]
> I would appreciate advice on how to correctly set the transformation or otherwise address the error

@Grgsj for support use the users/developers mailing lists, the telegram channel or gis stackexchange.

**Comment by Grgsj** [comment]
Can you please clarify how I am to address this error message with those other platforms?

**Comment by gioman** [comment]
> Can you please clarify how I am to address this error message with those other platforms?

@Grgsj The same way you did it here. This place is for bug reports and feature requests, not support.
