### ISSUE TITLE
New extract labels algorithm doesn't honor line layer labels rotation

### ISSUE THREAD

**Issue by antoniolocandro** [qgis/QGIS#46915]
### What is the bug or the crash?

The new algorithm mentions the following "Extracted label information include its position (served as point geometries), the associated layer name and feature ID, as well as label rotation, text, alignment, font family, size, weight, etc." https://github.com/qgis/QGIS-Documentation/issues/7260 

However when trying with a line the labels are always horizontal and do not follow line placement, do not know if this is a bug "intended" or a limitation as it is not stated as such in the proposal. It seems it works accurately with point layers at the moment

### Steps to reproduce the issue

See attached video
https://user-images.githubusercontent.com/4627073/150369909-116a9818-f097-490b-894d-f5743c4e8b16.mp4

Sample project configuration

[extract_labels_test.zip](https://github.com/qgis/QGIS/files/7906487/extract_labels_test.zip)

### Versions

QGIS version
3.23.0-Master
QGIS code revision
c5a56d6f83
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.0-CAPI-1.16.0
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

This copy of QGIS writes debugging output.

Active Python plugins
MemoryLayerSaver
4.0.4
quick_map_services
0.19.27
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Not running supported version intentionally

**Comment by nirvn** [comment]
@antoniolocandro , saving the output as shapefile means the attribute names will be clipped to 10 characters (a limitation of the format), which in turn will transform the "LabelRotation" field (used as data-defined property) to "LabelRotat", invalidating the data-defined property.

See the truncated names here:
![image](https://user-images.githubusercontent.com/1728657/151133606-00448799-2f59-4431-8f5d-0f1d7d3a8b0c.png)

You can correct the data-defined property by updating its definition to the truncated field:
![image](https://user-images.githubusercontent.com/1728657/151133856-873c92be-13dd-4094-85cf-c19726d963f5.png)

Closing as this is not really a bug on our part but a limitation of the data format.

**Comment by antoniolocandro** [comment]
I understand what you are saying but in my opinion as shapefile format is not deprecated for support within QGIS it should  be supported, doing so would require "just" a check if the format is a shapefile and adjust accordingly for the truncated names as mentioned in your post . Not doing so will probably cause confusion to many users since even if we don't want to the shapefile is a common GIS format.

If this was a plugin I wouldn't mind the dropped support but in this case I really think it should be added as the algorithm is part of core, the mapping of the original names to truncated ones could be saved in some central location so this could be used by other algorithms.

May I ask that consideration be given again for this as it could lead to dropping shapefile support for other algorithms as well. Unfortunately I can't do the coding myself. If this is not to be added I would suggest that then the QGIS project make a statement that shapefile is not a supported format and that it is added to the documentation and the help when the use of the shapefile format is not to be used.

**Comment by gioman** [comment]
> I understand what you are saying but in my opinion as shapefile format is not deprecated for support within QGIS it should be supported, doing so would require

@antoniolocandro I think you are missing the point: if you want to output as SHP you must ensure that the fields used for data defined rotation (or other property) are at max 10 chars long, because that is the limit in the format.

**Comment by andreasneumann** [comment]
Hm @antoniolocandro - I think we should not cripple ourselves in QGIS (for the remainder of our short lives) just because one popular format doesn't support long column names ...

Time to move on ...

**Comment by antoniolocandro** [comment]
> > I understand what you are saying but in my opinion as shapefile format is not deprecated for support within QGIS it should be supported, doing so would require
> 
> @antoniolocandro I think you are missing the point: if you want to output as SHP you must ensure that the fields used for data defined rotation (or other property) are at max 10 chars long, because that is the limit in the format.

I am not doing the output the algorithm is ;)

**Comment by gioman** [comment]
> I am not doing the output the algorithm is ;)

Processing tools default output format is GPKG.

**Comment by antoniolocandro** [comment]
@andreasneumann I disagree but understand your point, you did mention in your answer it is a popular format, there are other much lesser used formats included in QGIS.

Can QGIS make a statement algorithms may not work with shapefiles or something about support deprecation for the format? I think this sets the expectations for people that use the software and will reduce the frustration of unsupported format being used. As a minimum the help of the algorithm should have a statement that output to shapefile would require adjustment of the user for field name.

P.S. not trying to push something in one direction but make it clear what to expect for other users. I now know that I might need workarounds to use the format and know what to expect

**Comment by andreasneumann** [comment]
@antoniolocandro - if you really need this functionality for shape files, you can first generate a geopackage and then create a small model that renames attribute names and adjusts the data defined settings accordingly.

A note in the help/documentation may help to avoid frustration.
