### ISSUE TITLE
Mesh dataset input in modeler can not be linked to a parent mesh

### ISSUE THREAD

**Issue by nicogodet** [qgis/QGIS#46920]
### What is the bug or the crash?

In modeler, we can add an mesh dataset input but we can not define a parent mesh.
So when model is started, mesh dataset selection is always empty.

![image](https://user-images.githubusercontent.com/39594821/150407887-7cabb04e-2cb3-441f-9743-686d940f7129.png)
![image](https://user-images.githubusercontent.com/39594821/150407938-5d93dc8f-eb21-4ecb-ac25-efd6049807b6.png)
![image](https://user-images.githubusercontent.com/39594821/150407951-807fddd9-9dc3-4368-b2ec-b78fecac2b2e.png)

### Steps to reproduce the issue

1. Just create a model with 2 inputs : meshlayer and mesh dataset
2. Run the model and try to select a dataset

### Versions

windows 3.22.3

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
could be linked https://github.com/qgis/QGIS/issues/46517

**Comment by JonnyFri** [comment]
I cant help, but i sure have the same problem. So i can confirm its reproducible. I hope someone can help :D

**Comment by saberraz** [comment]
@JonnyFri you can always ping the developers (info@lutraconsulting.co.uk) of this feature if you want a quick solution? :) 

Note that we ported the processing algorithms from Crayfish plugin out of our own budget (https://www.qgis.org/en/site/forusers/visualchangelog318/index.html#mesh) So, any funding the improve them is highly appreciated.

**Comment by JonnyFri** [comment]
@saberraz Thank you for the help, its my first ticket I did open here. I´d really like to help, how do I ping them?

**Comment by saberraz** [comment]
Drop them an email and ask for a quote to fixing this issue :)

**Comment by alexbruy** [comment]
Seems works fine. Or I don't understand steps to reproduce the issue
![model](https://user-images.githubusercontent.com/776954/150951199-1e24152f-db84-4f80-a7e2-97658bce197e.png)

**Comment by alexbruy** [comment]
After playing a bit more, I think I realize what is wrong. Maybe it's only me, but issue description a bit difficult to interpret. The problem is that "Mesh Dataset Group" does not allow to choose parent "Mesh Layer" parameter when building a model. Sorry for the noise

**Comment by nicogodet** [comment]
@alexbruy I wrote the issue after a long day. I could improve the description a bit...

**Comment by JonnyFri** [comment]
I´d really appreciate if someone else might contact Lutra Consulting. I dont think that im capable of explaining the issue correctly.

**Comment by alexbruy** [comment]
@nicogodet I think it is not needed, maybe I had difficulties to understand it because of my English or because I don't use meshes all the time.

BTW, seems it is the same as #46517.
