### ISSUE TITLE
Digitizing crashes

### ISSUE THREAD

**Issue by tnewkirk78** [qgis/QGIS#46936]
## User Feedback

Continuing to get digitizing errors

## Report Details

**Crash ID**: [735b3500083eb5388d7b38e6ed2d86e57275acb3](https://github.com/qgis/QGIS/search?q=735b3500083eb5388d7b38e6ed2d86e57275acb3&type=Issues)

**Stack Trace**
<pre>
QMutex::lock :
QgsVectorLayerFeatureSource::QgsVectorLayerFeatureSource :
QgsFeaturePool::getFeatures :
QgsFixAttributeDialog::reject :
QgsFixAttributeDialog::reject :
QObject::qt_static_metacall :
QgsVectorLayer::beforeCommitChanges :
QgsVectorLayer::commitChanges :
QgisApp::saveEdits :
QObject::qt_static_metacall :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.16.16-Hannover
QGIS code revision: f5778a89
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.1
Running against GDAL: 3.4.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Steps to reproduce the issue

Repeated crashes using basic digitizing tools (i.e., vertex editor, ring delete, merge) 

### Versions

Hanover 3.16.16

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@tnewkirk78 you must test with a new QGIS profile and no 3rd party plugins installed.

settings > user profiles > new profile

**Comment by tnewkirk78** [comment]
QGIS unexpectedly ended as I attempted to load the project file. 

Crash ID: 7f356d2c2cdce1493fad79c94972822d1c548917


Stack Trace


QActionPrivate::sendDataChanged :
QAction::setEnabled :
QObject::qt_static_metacall :
QgsProject::layerWasAdded :
QObject::qt_static_metacall :
QgsMapLayerStore::layerWasAdded :
QgsMapLayerStore::addMapLayers :
QgsProject::addMapLayers :
QgsProject::addLayer :
QgsProject::_getMapLayers :
QgsProject::readProjectFile :
QgsProject::unzip :
QgsProject::read :
QgisApp::addProject :
QgisApp::fileOpen :
QObject::qt_static_metacall :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QMenu::metaObject :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.16.16-Hannover
QGIS code revision: f5778a89
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.1
Running against GDAL: 3.4.1



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

**Comment by gioman** [comment]
> QGIS unexpectedly ended as I attempted to load the project file.

@tnewkirk78 with  a new QGIS profile? if yes then you must detail how to get the crash, possibly also adding a sample project with data.

**Comment by roya0045** [comment]
Can you add the feature that was being modified to an empty project? Curious to know if the initial crash corrupted something or if the second one is unrelated.
