### ISSUE TITLE
custom python function is executed 3 times, when adding feature in an empty layer

### ISSUE THREAD

**Issue by Falmarin** [qgis/QGIS#46935]
### What is the bug or the crash?

Any code in a python macro for attributes forms is executed 3 times, when no features had been added to the layer.

### Steps to reproduce the issue

1. create empty point layer
2. Associate the python code below:
from PyQt5.QtWidgets import QApplication, QMainWindow, QWidget
counter = 0
def increaseCounter(dialog,layerid,featureid):
    global counter
    counter = counter + 1
    print(counter)
3. Add a feature and click ok
4. In the python console following code is printed:
1 is printed, when the feature is created and the form opens
2 is printed, when the form is accepted
3 is printed, when the form is accepted and the layer had been empty

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.2-Białowieża | QGIS code revision | 1601ec46d0
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.7
GDAL/OGR version | 3.2.2
PROJ version | 7.2.1
EPSG Registry database version | v10.008 (2020-12-16)
GEOS version | 3.9.0-CAPI-1.16.2
SQLite version | 3.35.5
PDAL version | 2.2.0
PostgreSQL client version | 13.5 (Ubuntu 13.5-0ubuntu0.21.10.1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Pop!_OS 21.10
  |   |   |  
Active Python plugins
plugin_reloader | 0.9.1
pluginbuilder3 | 3.2.1
orchis_field | 0.1.3
mmqgis | 2021.9.10
processing | 2.12.99
db_manager | 0.1.20

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by roya0045** [comment]
I'm unsure if this is a bug, it seems normal to want a script to execute at any of those three points.
