### ISSUE TITLE
"Activate" checkbox missing for OTB in 3.22.3

### ISSUE THREAD

**Issue by lindsay-richards** [qgis/QGIS#46945]
### What is the bug or the crash?

The "activate" button for orfeo toolbox in the providers menu is missing in release 3.22.3. T Attempting to specify the installation paths for OTB also results in the paths being deleted any time the options window is closed. his issue does not exist in other versions I have tested (3.16 and 3.18).

### Steps to reproduce the issue

1: Launch QGIS 3.22
2: Download Orfeo Toolbox if not installed
3: Go to Settings > Options > Providers > OTB
4: Specify the paths for OTB application folder and OTB folder
5: The activate button is not visible at the top of the OTB options where it is in other versions. The activate button for other plugins should appear normal.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.3-Białowieża | QGIS code revision | 1628765ec7
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
Compiled against GEOS | 3.10.0-CAPI-1.16.0 | Running against GEOS | 3.10.2-CAPI-1.16.0
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
geoscience | 1.5
PghydroTools | 3.2
pointsamplingtool | 0.5.3
qfieldsync | v3.4.4
Qgis2threejs | 2.6
qgis2web | 3.16.0
qProf | 0.4.4
QuickOSM | 2.0.0
quick_map_services | 0.19.27
SemiAutomaticClassificationPlugin | 7.10.5
TerrainShading | 0.9.3
db_manager | 0.1.20
grassprovider | 2.12.99
otbprovider | 2.12.99
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

This problem occurred on a totally fresh installation and also occurs on a fresh profile. Version 3.16.16 LTR was installed using an identical process and does not exhibit the same issue.

**Comment by alexbruy** [comment]
It is not a bug. OTB provider is a separate plugin now and should be activated in the Plugin Manager.

**Comment by bravemaster3** [comment]
Hey, @lindsay-richards 
Did you finally manage to get your OrfeoToolBox working?
I saw the answer of @alexbruy , but despite the OTB provider activated in the plugin manager, I still do not see any OTB tools in the Processing toolbox.
I also went in the toolbox options, and for OTB, there is no button for activating it unlike other toolboxes such as GRASS.
I have no idea also what to set (if I have to) for the options like "geoid", application folder.... 
Any help will be greatly appreciated as I urgently need to do some classifications.
I have the lasted version of QGIS (3.22), installed today (2022-05-04) along with several other tools using OSGeo4W. I made sure to uninstall all previous installations and removed the OSGeo4W folder before installing it again.

Thanks,
Koffi

![image](https://user-images.githubusercontent.com/39010414/166627644-10a0d424-b60a-407a-8ee8-e6d3382c3949.png)

![image](https://user-images.githubusercontent.com/39010414/166627567-8a7a5af9-9cb9-4255-ab0f-d766370c4874.png)

**Comment by troopa81** [comment]
@bravemaster3 You have to install the OTB provider AND [OTB](https://www.orfeo-toolbox.org/) itself AND properly configure the OTB folder path and application folder path. In your screenshot I can see the paths are not configured. 

Be careful also about [compatibility](https://www.orfeo-toolbox.org/CookBook/QGISInterface.html#compatibility-between-qgis-and-otb-versions) between OTB and QGIS

**Comment by bravemaster3** [comment]
> @bravemaster3 You have to install the OTB provider AND [OTB](https://www.orfeo-toolbox.org/) itself AND properly configure the OTB folder path and application folder path. In your screenshot I can see the paths are not configured.
> 
> Be careful also about [compatibility](https://www.orfeo-toolbox.org/CookBook/QGISInterface.html#compatibility-between-qgis-and-otb-versions) between OTB and QGIS

Thanks you very much for your response. I misunderstood the documentation. I thought when it says that OTB provider is now part of QGIS, it meant one does no longer have to install OTB separately. I am unpacking the installation files. Then, I guess it should work.
Thank you for the warning about versioning. 

Best regards,
Koffi

**Comment by grossman808** [comment]
> > @bravemaster3 You have to install the OTB provider AND [OTB](https://www.orfeo-toolbox.org/) itself AND properly configure the OTB folder path and application folder path. In your screenshot I can see the paths are not configured.
> > Be careful also about [compatibility](https://www.orfeo-toolbox.org/CookBook/QGISInterface.html#compatibility-between-qgis-and-otb-versions) between OTB and QGIS
> 
> Thanks you very much for your response. I misunderstood the documentation. I thought when it says that OTB provider is now part of QGIS, it meant one does no longer have to install OTB separately. I am unpacking the installation files. Then, I guess it should work. Thank you for the warning about versioning. For anyone that may be wondering about these, read more[ here](https://docs.qgis.org/3.22/en/docs/user_manual/processing/3rdParty.html#troubleshoot) about the steps of installation of OTB and how to set it up in QGIS.
> 
> Best regards, Koffi


![OTB](https://user-images.githubusercontent.com/122285430/211342823-061b92cb-1ca5-44a7-a890-e03939f63f3b.JPG)
![otb2](https://user-images.githubusercontent.com/122285430/211342846-6aef5b13-509c-4ae2-8aee-2c1632967062.JPG)


Hello Koffi, I was having same challenge as you and have gone through the documentation you posted but still need some pointers. 

Tried installing the OTB, this is where I got stuck running the mapla.bat launcher 
[not a programmer by any stretch, perhaps with limited knowledge but a desire to get OTB 8.1.0 & processing OTB provider 1.4.2 working with QGIS 3.26.3]. Cookbook doesn't help me at this point.. 

Also, while installing the Processing OTP provider, 'New' doesn't show up on the left pane as it should after adding and connecting the CNES plugin repository....

Please, what am I getting all wrong? Is this possibly a compatibility issue?

**Comment by grimav1916** [comment]
Hi, to all, need assistance about the OTB toolbox. I did all the procedures listed above with regards activation & installation but when I go into settings to insert the folder path and the application path this notification comes up. Any of you out there has encounter this issue? I have versions 3.16.7, 3.28.10, & 3.30.3

Thanks
Victoria

![Screenshot 2023-09-06 112520](https://github.com/qgis/QGIS/assets/144262951/2bc9452f-9ab6-4285-98fa-b8c9dc6ca001)
