### ISSUE TITLE
project dont open

### ISSUE THREAD

**Issue by Geoscope19** [qgis/QGIS#46948]
### What is the bug or the crash?

Sorry I don’t speak English :-(

Unable to open a file or project. 
1. open qgis : alert message (x 6) 
2. open file or project : message quit

### Steps to reproduce the issue

1. Message open qgis : 
"Une erreur est survenue lors de l'éxécution du code Python: 
NotImplementedError: QgsProcessingAlgorithm.name() is abstract and must be overridden 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~2.3/apps/qgis/./python/plugins\processing\script\ScriptUtils.py", line 69, in loadAlgorithm
    alg = algfactory.instances.pop().createInstance()
IndexError: pop from empty list
During handling of the above exception, another exception occurred:
NotImplementedError: QgsProcessingAlgorithm.name() is abstract and must be overridden

Version de Python : 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Version de QGIS : 3.22.3-Białowieża Białowieża, 1628765ec7 
Chemin Python :
    • C:/PROGRA~1/QGIS32~2.3/apps/qgis/./python 
    • C:/Users/-/AppData/Roaming/QGIS/QGIS3\profiles\default/python 
    • C:/Users/-/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins 
    • C:/PROGRA~1/QGIS32~2.3/apps/qgis/./python/plugins 
    • C:\Program Files\QGIS 3.22.3\bin\python39.zip 
    • C:\PROGRA~1\QGIS32~2.3\apps\Python39\DLLs 
    • C:\PROGRA~1\QGIS32~2.3\apps\Python39\lib 
    • C:\Program Files\QGIS 3.22.3\bin 
    • C:\PROGRA~1\QGIS32~2.3\apps\Python39 
    • C:\PROGRA~1\QGIS32~2.3\apps\Python39\lib\site-packages 
    • C:\PROGRA~1\QGIS32~2.3\apps\Python39\lib\site-packages\GDAL-3.4.1-py3.9-win-amd64.egg 
    • C:\PROGRA~1\QGIS32~2.3\apps\Python39\lib\site-packages\win32 
    • C:\PROGRA~1\QGIS32~2.3\apps\Python39\lib\site-packages\win32\lib 
    • C:\PROGRA~1\QGIS32~2.3\apps\Python39\lib\site-packages\Pythonwin 
    • C:/Users/-/AppData/Roaming/QGIS/QGIS3\profiles\default/python 
    • C:\Users\-\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools 
    • C:\Users\-\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools"

---------------

2. Message open project :
"Crash ID: a151034d3904f1c6d5f95845df00c0aa1f75f14d

Stack Trace

QgsStyleProxyModel::QgsStyleProxyModel :
QgsStyleItemsListWidget::setStyle :
QgsSymbolsListWidget::QgsSymbolsListWidget :
QgsSymbolSelectorWidget::layerChanged :
QObject::qt_static_metacall :
QItemSelectionModel::setCurrentIndex :
QAbstractItemView::setCurrentIndex :
QgsSymbolSelectorWidget::loadSymbol :
QgsSymbolSelectorWidget::QgsSymbolSelectorWidget :
QgsSingleSymbolRendererWidget::QgsSingleSymbolRendererWidget :
QgsSingleSymbolRendererWidget::create :
QgsRendererPropertiesDialog::rendererChanged :
QObject::qt_static_metacall :
QWidgetLineControl::`default constructor closure' :
QComboBox::setCurrentIndex :
QComboBox::setCurrentIndex :
QgsRendererPropertiesDialog::syncToLayer :
QgsRendererPropertiesDialog::QgsRendererPropertiesDialog :
QgsLayerStylingWidget::updateCurrentWidgetLayer :
QObject::qt_static_metacall :
QListWidgetItem::`default constructor closure' :
QObject::qt_static_metacall :
QItemSelectionModel::setCurrentIndex :
QListWidget::setCurrentRow :
QgsLayerStylingWidget::setLayer :
QgisApp::setMapStyleDockLayer :
QObject::qt_static_metacall :
QgisApp::activeLayerChanged :
QgisApp::onActiveLayerChanged :
QObject::qt_static_metacall :
QgsLayerTreeView::currentLayerChanged :
QgsLayerTreeView::onCurrentChanged :
QObject::qt_static_metacall :
QItemSelectionModel::setCurrentIndex :
QAbstractItemView::setCurrentIndex :
QgsLayerTreeView::setCurrentLayer :
QgisApp::addProject :
QgisApp::openProject :
QgsTemporalControllerDockWidget::temporalController :
QObject::qt_static_metacall :
QAbstractItemView::activated :
QAbstractItemView::mouseDoubleClickEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QgsPresetSchemeColorRamp::clone :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QgsPresetSchemeColorRamp::clone :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.22.3-Bia?owie?a
QGIS code revision: 1628765ec7
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.1
Running against GDAL: 3.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043"

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.3-Białowieża | QGIS code revision | 1628765ec7
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.0-CAPI-1.16.0
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
cadastre | 1.13.5
DigitizingTools | 1.5.1
GeometryShapes | 0.7
ImportPhotos | 3.0.3
plaingeometryeditor | 3.0.0
PluginLoadTimes | 3.0.1
Qgis2threejs | 2.6
TerrainShading | 0.9.3
grassprovider | 2.12.99
sagaprovider | 2.12.99

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@Geoscope19 try with a new QGIS profile

settings > user profiles > new profile

**Comment by Geoscope19** [comment]
@gioman gioman

I tried, it crashes too, here’s the error message : 
Crash ID: 8e7c51288c3a3dfa67f466d55a9fbdac779a4569

Stack Trace

QXmlStreamStringRef::~QXmlStreamStringRef :
QgsUserProfileManager::loadUserProfile :
QgisApp::newProfile :
QObject::qt_static_metacall :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QgsPresetSchemeColorRamp::clone :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QgsPresetSchemeColorRamp::clone :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.22.3-Bia?owie?a
QGIS code revision: 1628765ec7
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.1
Running against GDAL: 3.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

**Comment by gioman** [comment]
> I tried, it crashes too

@Geoscope19 does it happen with any project or just with a specific one?

**Comment by Geoscope19** [comment]
@gioman for all project, and even with a single layer

**Comment by agiudiceandrea** [comment]
@Geoscope19 using the new QGIS user profile, is the first Python error message ("NotImplementedError: QgsProcessingAlgorithm.name() is abstract and must be overridden") still displayed?

**Comment by gioman** [comment]
> @gioman for all project, and even with a single layer

@Geoscope19 you seems to have a local issue, because of course is not a QGIS general one. You may also try to manually remove the `C:/Users/-/AppData/Roaming/QGIS` folder (back it up first if you have custom scripts, projections, etc.).

**Comment by Geoscope19** [comment]
I uninstalled all qgis version and installed 3.22: everything was blocked (open file, project, change user..).
I uninstall the 3.22 and installed the 3.16.16 : qgis open file / project.
I’m waiting for the next version on February 18th to update with the 3.24... we’ll see how it works.
With version 3.16.16 I still have error messages when opening (see attached file
![Sans titre](https://user-images.githubusercontent.com/81222128/150782752-1bbd72e6-6352-4f21-a12f-1fe88c816c6b.png)
).
I will test remove C:/Users/-/AppData/Roaming/QGIS

**Comment by gioman** [comment]
> (see attached file).

@Geoscope19 the error you show in the above picture comes from a 3rd party plugi, which also seems to be in a very weird location "d:\...". There definitely something wrong in your setup, not QGIS.
