### ISSUE TITLE
"QGIS (3.22) unexpectedly ended" while opening a 3.16 project

### ISSUE THREAD

**Issue by AlexFTL** [qgis/QGIS#46968]
### What is the bug or the crash?

Hi everyone, i've got several QGIS 3.16 projects. Today I got a new PC and my admin got me QGIS 3.22.1.
Some of the projects are starting with no problems. Others crash with the message "QGIS unexpectedly ended".
Unfortunately I can't copy the report, because the button is just grey.

This is the text:

Crash ID: cb7693dcad64c51efc6698503ad3c9c6ef814c10
Stack Trace

QTextCodec::toUnicode :
providerMetadataFactory :
providerMetadataFactory :
providerMetadataFactory :
providerMetadataFactory :
QgsVectorLayer::setDataProvider :
QgsVectorLayer::readXml :
QgsMapLayer::readLayerXml :
QgsProject::addLayer :
QgsProject::_getMapLayers :
QgsProject::readProjectFile :
QgsProject::unzip :
QgsProject::read :
QgisApp::addProject :
QgisApp::openProject :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.22.1-Bia?owie?a
QGIS code revision: 663dcf8fb9
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.0
Running against GDAL: 3.4.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

Are there any ideas for solving the problem?

Thanks, Alex

### Steps to reproduce the issue

1. open a 3.16 project
2. QGIS crashs

### Versions

QGIS-Version
3.22.1-Białowieża
QGIS-Codeversion
663dcf8fb9
Qt-Version
5.15.2
Python-Version
3.9.5
GDAL-Version
3.4.0
PROJ-Version
8.2.0
EPSG-Registraturdatenbankversion
v10.038 (2021-10-21)
GEOS-Version
3.10.0-CAPI-1.16.0
SQLite-Version
3.35.2
PDAL-Versio
2.3.0
PostgreSQL-Client-Version
13.0
SpatiaLite-Version
5.0.1
QWT-Version
6.1.3
QScintilla2-Version
2.11.5
BS-Version
Windows 10 Version 2009

Aktive Python-Erweiterungen
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
> QGIS 3.22.1

@AlexFTL upgrade to 3.22.3 and try again.
