### ISSUE TITLE
After import of esri wrong coordination system RD2008 expected Amersfoort / RD New 

### ISSUE THREAD

**Issue by DianaIDDSArcheologie** [qgis/QGIS#46973]
### What is the bug or the crash?

Problem:
When importing the shape files from X PAD v4.6.011 into QGIS v3.20 the coordinate system is incorrect at: "RD 2008"

See attached the shape files I import into QGIS:
[ESRI_SHAPE_from_X_PAD-V4.6.011_Points_Maaiveld.zip](https://github.com/qgis/QGIS/files/7926966/ESRI_SHAPE_from_X_PAD-V4.6.011_Points_Maaiveld.zip)

Expected:
After import coordinate system is "Amersfoort / RD New".

Extra information on tools used
GNSS - GEOMAX - Zenith40 gsm
Android application communicating with the GNSS: X_PAD-V4.6.011
Export files using ESRI formot. Example of the results from X-PAD can be found in the attached zip.

Picture of the screen in QGIS where I have to change the coordinate system for each of the ESRI / Shape files I import into QGIS in order to show them correctly.
![image](https://user-images.githubusercontent.com/98336509/150818154-414fd68e-e89e-46e4-84bd-ef5a2d80b405.png)

### Steps to reproduce the issue

1) Import the Points_Maaiveld.shp file from the zip:
[ESRI_SHAPE_from_X_PAD-V4.6.011_Points_Maaiveld.zip](https://github.com/qgis/QGIS/files/7927064/ESRI_SHAPE_from_X_PAD-V4.6.011_Points_Maaiveld.zip)

2) Observe coordinate system in the properties of the imported points. 

Currently wrong default coordinate system:  RD 2008
Expected coordinate system: Amersfoort RD New

### Versions

QGIS-versie
3.20.3-Odense
QGIS code revisie
495fbaec
Qt versie
5.15.2
Python versie
3.9.5
GDAL/OGR versie
3.3.1
PROJ versie
8.1.1
EPSG-register databaseversie
v10.028 (2021-07-07)
GEOS versie
3.9.1-CAPI-1.14.2
SQLite versie
3.35.2
PDAL versie
2.3.0
PostgreSQL client versie
13.0
SpatiaLite versie
5.0.1
QWT versie
6.1.3
QScintilla2 versie
2.11.5
OS versie
Windows Server 2016 Version 1809

Actieve Python plug-ins
zwaarde_uitlezen
db_manager
MetaSearch
processing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

I think this might have started when we started using v3.20.3 (for me a couple of months)

**Comment by DelazJ** [comment]
> gioman added the Feedback label 23 minutes ago 

@gioman I think you wanted to also add that 3.20.3 is unsupported anymore and that @DianaIDDSArcheologie should test with 3.22.3 and report if the issue is still true.
In the meantime, I tested on 3.22.0 on macos Catalina (same version of proj), and I'm also given a custom CRS "RD 2008 + Unknown VCS from AcInfo Workstation".

**Comment by gioman** [comment]
@DelazJ @DianaIDDSArcheologie 

correct, i was about to answer but had to leave abruptly to go do a COVID test. 

Also using the latest gdal/OGR (using ogrinfo from the command line) shipped with QGIS 3.22.3 the result is the same, indicating that is either OGR that cannot read correctly the CRS of that shapefile or that the program that generated the shapefile did not correctly write the CRS.

**Comment by gioman** [comment]
```
ogrinfo -so Points_Maaiveld.shp Points_Maaiveld
INFO: Open of `Points_Maaiveld.shp'
      using driver `ESRI Shapefile' successful.

Layer name: Points_Maaiveld
Metadata:
  DBF_DATE_LAST_UPDATE=2049-01-01
Geometry: 3D Point
Feature Count: 1
Extent: (104509.753260, 488439.252915) - (104509.753260, 488439.252915)
Layer SRS WKT:
COMPOUNDCRS["RD 2008 + Unknown VCS from ArcInfo Workstation",
    PROJCRS["RD 2008",
        BASEGEOGCRS["RD 2008",
            DATUM["AMERSFOORT2008",
                ELLIPSOID["BESSEL1841",6377397.155,299.15281285,
                    LENGTHUNIT["metre",1,
                        ID["EPSG",9001]]]],
            PRIMEM["Greenwich",0,
                ANGLEUNIT["Degree",0.0174532925199433]]],
        CONVERSION["unnamed",
            METHOD["Unknown"],
            PARAMETER["False_Easting",155000,
                LENGTHUNIT["Meter",1]],
            PARAMETER["False_Northing",463000,
                LENGTHUNIT["Meter",1]],
            PARAMETER["Central_Meridian",5.388,
                ANGLEUNIT["Degree",0.0174532925199433]],
            PARAMETER["Scale_Factor",0.9999079,
                SCALEUNIT["unity",1,
                    ID["EPSG",9201]]],
            PARAMETER["Latitude_Of_Origin",52.156,
                ANGLEUNIT["Degree",0.0174532925199433]]],
        CS[Cartesian,2],
            AXIS["(E)",east,
                ORDER[1],
                LENGTHUNIT["Meter",1]],
            AXIS["(N)",north,
                ORDER[2],
                LENGTHUNIT["Meter",1]]],
    VERTCRS["Unknown VCS from ArcInfo Workstation",
        VDATUM["Unknown"],
        CS[vertical,1],
            AXIS["gravity-related height (H)",up,
                LENGTHUNIT["metre",1,
                    ID["EPSG",9001]]]]]
Data axis to CRS axis mapping: 1,2,3
PT_NAME: String (255.0)
PT_CODE: String (100.0)
PT_DESCR: String (255.0)
PT_X-EAST: Real (12.3)
PT_Y-NORTH: Real (12.3)
PT_ELEV: Real (9.3)
PT_PHOTO: String (50.0)
Werkput: Integer (9.0)
Opmerking: String (255.0)
```

**Comment by nyalldawson** [comment]
There's something quite broken in the original CRS definition as written by X PAD. See the contents of the .prj file:

```
PROJCS["RD 2008", GEOGCS["RD 2008", DATUM["AMERSFOORT2008", SPHEROID["BESSEL1841", 6377397.155, 299.152812850]], PRIMEM["Greenwich", 0.0], UNIT["Degree", 0.0174532925199433]], PROJECTION["Unknown"], PARAMETER["False_Easting", 155000.000], PARAMETER["False_Northing", 463000.000], PARAMETER["Central_Meridian", 5.388], PARAMETER["Scale_Factor", 0.999907900], PARAMETER["Latitude_Of_Origin", 52.156], UNIT["Meter", 1.0]],VERTCS["Unknown VCS from ArcInfo Workstation", VDATUM["Unknown"], PARAMETER["Vertical_Shift", 0.0], PARAMETER["Direction", 1.0], UNIT["Meter", 1.0]]
```

Specifically see the term  `PROJECTION["Unknown"]`.

Basically the CRS written by XPad is broken. This isn't a QGIS (or Proj) issue.

**Comment by DelazJ** [comment]
>  correct, i was about to answer but had to leave abruptly to go do a COVID test.

I hope everything is fine!

**Comment by DianaIDDSArcheologie** [comment]
Thank you for the reactions! I'll rapport it to XPAD.
