### ISSUE TITLE
Support reading of PAM image format

### ISSUE THREAD

**Issue by boxerab** [qgis/QGIS#46980]
### Feature description

PAM is an extension of PNM format that supports alpha channel for monochrome or RGB.
http://davis.lbl.gov/Manuals/NETPBM/doc/pam.html

It is a simple, uncompressed format that still allows for alpha.

Here is some code that [parses a PAM header](https://github.com/GrokImageCompression/grok/blob/1992ce175720d09aed3a3993edd9393e463355d3/src/bin/image_format/PNMFormat.cpp#L469)

**Comment by gioman** [comment]
@boxerab better suited for https://github.com/OSGeo/gdal ?

**Comment by boxerab** [comment]
@gioman yes indeed, I will open it there. gdal unfortunately has poor PNM support.
