### ISSUE TITLE
MultiPart post network request stopped working

### ISSUE THREAD

**Issue by raymondnijssen** [qgis/QGIS#46989]
### What is the bug or the crash?

One of my plugins stopped working in QGIS master, because some of the requests seem invalid. Specifically requests that post data data with a file as multipart content do not work

### Steps to reproduce the issue

Not easy to reproduce by clicking, but I wrote a script to test this. I posted it on the developer mailing list: https://lists.osgeo.org/pipermail/qgis-developer/2022-January/064437.html

### Versions

Well it depends on the versions. I've been building many to get close to the date it broke:
14 sep: works
1 oct: works
1 dec: works
7 dec: broken
16 dec: broken
1 jan: broken
23 jan: broken

Here's the output for my December 7 build:

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.23.0-Master | QGIS code revision | be5613883c
-- | -- | -- | --
Qt version | 5.12.8
Python version | 3.8.10
GDAL/OGR version | 3.0.4
PROJ version | 6.3.1
EPSG Registry database version | v9.8.6 (2020-01-22)
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
SQLite version | 3.31.1
PDAL version | 2.0.1
PostgreSQL client version | 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.2
OS version | Ubuntu 20.04.3 LTS
  |   |   |  
Active Python plugins
ImaerPlugin | version 3.1.0
plugin_reloader | 0.9.1
pdokservicesplugin | 3.7.3
qgis_3d_ams | 0.1
QuickOSM | 2.0.0
firstaid | 2.1.5
QCopycanvas | 0.5
sagaprovider | 2.12.99
processing | 2.12.99

</body></html>

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
Is this a qgis bug? Looking at the sample code I suspect it's a pyqt/qt bug. Can you reproduce with a standalone pyqt script run outside of qgis?

**Comment by m-kuhn** [comment]
It's a qgis bug, we are experiencing the same.

Sending data through `QgsNetworkAccessManager` with post and multipart fails with error 99.
The same works with `QNetworkAccessManager`.

QgsNetworkAccessManager (no headers printed)
```
from PyQt5.QtCore import *
from PyQt5.QtNetwork import *

url = QUrl('https://www.opengis.ch')
request = QNetworkRequest(url)
# request.setAttribute(QNetworkRequest.FollowRedirectsAttribute, True)
multi_part = QHttpMultiPart(QHttpMultiPart.MixedType)

reply = QgsNetworkAccessManager.instance().post(request, multi_part)
print(reply.error())
def prn():
    for header in reply.rawHeaderList():
        print(str(header))

reply.finished.connect(prn)
```

QNetworkAccessManager (headers print fine)

```
from PyQt5.QtCore import *
from PyQt5.QtNetwork import *

url = QUrl('https://www.opengis.ch')
request = QNetworkRequest(url)
# request.setAttribute(QNetworkRequest.FollowRedirectsAttribute, True)
multi_part = QHttpMultiPart(QHttpMultiPart.MixedType)

nam = QNetworkAccessManager()

reply = nam.post(request, multi_part)
print(reply.error())
def prn():
    for header in reply.rawHeaderList():
        print(str(header))

reply.finished.connect(prn)
```

It is connected to https://github.com/qgis/QGIS/blob/aa730d6a44deffd376784ec4b6893696df519746/src/core/network/qgsnetworkaccessmanager.cpp#L358, commenting this line fixes the issue

**Comment by raymondnijssen** [comment]
Thank you Matthias, just tried  and it works again!
