### ISSUE TITLE
pyqtSlot decorator has problems with layerChanged in Qgis 3.22

### ISSUE THREAD

**Issue by XavierCLL** [qgis/QGIS#46995]
### What is the bug or the crash?

Hi everyone!

I opened a question in [qgis-developer list](https://lists.osgeo.org/pipermail/qgis-developer/2022-January/064381.html) few days ago without any response, but I think this is a Qgis issue: 

I've developed some Qgis plugins, everything was fine until I updated to Python 3.10 version, some of these plugins have problems with the  `pyqtSlot` with the function `layerChanged`, an example code:

```python
self.myLayerComboBox.layerChanged.connect(self.myConnectMethod)

@pyqtSlot(QgsMapLayer)
def myConnectMethod(self, layer)
     pass
```

The error is:

`TypeError: decorated slot has no signature compatible with layerChanged(QgsMapLayer*)`

I think there is an issue with `layerChanged` using this decorator because the decorator `pyqtSlot` works well with other functions. Or that pyqtSlot no longer necessary? or has the syntax changed for that decorator? because removing the decorator works well.

That error don't happen with Python < 3.10 Qgis 3.22.2 on Archlinux. But I have a user who informs me the same issue with Qgis 3.22 Python 3.9.5 on Windows. Here is another report: https://github.com/SMByC/AcATaMa/issues/12

Thanks!

Xavier

### Steps to reproduce the issue

Please see the example code to reproduce the error as a Qgis plugin, or install and open [this version of the plugin](https://plugins.qgis.org/plugins/AcATaMa/version/19.11.21/) or [this one](https://plugins.qgis.org/plugins/ThRasE/version/21.9.5/)

### Versions

Qgis 3.22

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
Not a bug, your decorator signature states that it accepts `QgsMapLayer` while `layerChanged` signal has a `QgsMapLayer*` argument. Specifying correct argument in a slot decorator fixes the issue.

**Comment by XavierCLL** [comment]
That is using the special combobox from Qgis called [QgsMapLayerComboBox](https://api.qgis.org/api/classQgsMapLayerComboBox.html). I had fixed it without using pyslot, but if you want to use slot and to expand the explanation from @alexbruy, the correct decorator is:

```python
self.myLayerComboBox.layerChanged.connect(self.myConnectMethod)

@pyqtSlot("QgsMapLayer*")
def myConnectMethod(self, layer)
     pass
```
