### ISSUE TITLE
Environment custom variables check/uncheck option

### ISSUE THREAD

**Issue by antoniolocandro** [qgis/QGIS#47005]
### Feature description

I got some environment variables that I sometimes want to turn off but it seems the only way to do so is to remove completely 

In the sample I have two variables and let's say I want to not use the second one for testing or some other reason, it would be great if I could just uncheck it 
![image](https://user-images.githubusercontent.com/4627073/151071276-39a5892b-0a05-4958-a529-e7c6be48aa40.png)

### Additional context

When deleting a variable I need to store in a text file to save the configuration, having this option within QGIS would make it faster to use or not some variables.

**Comment by agiudiceandrea** [comment]
@antoniolocandro, something like a "skip" option for "Apply"?

**Comment by antoniolocandro** [comment]
> @antoniolocandro, something like a "skip" option for "Apply"?

Yes! exactly. Some way to not use the variable but keep it there for the future. I do not know if this would be useful for others but it adds a convenience function to not need to delete a variable in order to skip it
