### ISSUE TITLE
QGIS crashes while loading big GeoJSON (450,000 Points)

### ISSUE THREAD

**Issue by erobiquee** [qgis/QGIS#47011]
### What is the bug or the crash?

QGIS crashes while loading big GeoJSON (450,000 Points):

Crash ID: a76049e8968479de50ae8662306e113ca37eba6a

Stack Trace

geos::noding::snapround::MCIndexSnapRounder::computeVertexSnaps :
geos::noding::snapround::MCIndexSnapRounder::computeVertexSnaps :
GEOSEquals_r :
OGRToOGCGeomType :
OGRLayer::FilterGeometry :
sqlite3_extension_init :
QgsSQLiteExpressionCompiler::operator= :
QgsAbstractFeatureIterator::nextFeature :
QgsVectorLayerFeatureIterator::fetchFeature :
QgsAbstractFeatureIterator::nextFeature :
QgsVectorLayerJoinInfo::setEditable :
QgsVectorLayerJoinInfo::setEditable :
QgsMapRendererParallelJob::renderLayerStatic :
QgsMapRendererParallelJob::renderingFinished :
QgsImageOperation::overlayColor :
QgsImageOperation::flipImage :
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

### Steps to reproduce the issue

Load file (drag&drop or Layer -> Add Layer -> Add vector layer...)

### Versions

QGIS Info
QGIS Version: 3.16.3-Hannover
QGIS code revision: 94ac9f21b8
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

and

QGIS version
3.18.0-Zürich
QGIS code revision
bdef9fb328
Compiled against Qt
5.12.8
Running against Qt
5.12.8
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.31.1
Running against SQLite
3.31.1
Compiled against PDAL
2.0.1
Running against PDAL
2.0.1 (git-version: Release)
PostgreSQL Client Version
12.6 (Ubuntu 12.6-0ubuntu0.20.04.1)
SpatiaLite Version
4.3.0a
QWT Version
6.1.4
QScintilla2 Version
2.11.2
Compiled against PROJ
6.3.1
Running against PROJ
Rel. 6.3.1, February 10th, 2020
OS Version
Ubuntu 20.04.3 LTS
Active python plugins
MetaSearch; 
processing; 
db_manager

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
> 3.18.0-Zürich

@erobiquee way too old. Upgrade to 3.22.3 and try again. Reopen if it still crashes. If it does then link/attach the offending datasource.

**Comment by gioman** [comment]
Also do not forget to try with a new QGIS profile

settings > user profiles > new profile

**Comment by erobiquee** [comment]
@gioman thanks for the hint! That solved the problem, at least on Windows.
