### ISSUE TITLE
Closing a QGIS settings dialog gives an error on master

### ISSUE THREAD

**Issue by LKajan** [qgis/QGIS#47014]
### What is the bug or the crash?

I'm trying to change the default language of a qgis. When opening the settings dialog, changing the language and closing the dialog it gives an error about Invalid custom coordinate system definition.

![settings-bug](https://user-images.githubusercontent.com/1225021/151144986-20811e55-2598-4188-9cdd-a8a8473a4f97.gif)

### Steps to reproduce the issue

1. Open the qgis settings dialog
2. Change any setting
3. Close the settings dialog
-> An error is shown about invalid custom crs
-> The setting changed is not saved

### Versions

QGISin versio
3.23.0-Master
QGIS-koodin versio
159a3e9987
Qt:n versio
5.15.2
Python-versio
3.9.5
GDAL/OGR:n versio
3.4.1
PROJ-versio
8.2.1
EPSG-rekisteritietokannan versio
v10.041 (2021-12-03)
GEOS-versio
3.10.2-CAPI-1.16.0
SQLite-versio
3.35.2
PDAL-versio
2.3.0
PostgreSQL:n asiakkaan versio
unknown
SpatiaLite-versio
5.0.1
QWT-versio
6.1.3
QScintilla2-versio
2.11.5
Käyttöjärjestelmän versio
Windows 10 Version 2009

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
> 3.23.0-Master

@LKajan does it happen on a current release (3.22.3)?

**Comment by LKajan** [comment]
> does it happen on a current release (3.22.3)?

No. Only in current Master. I see now that Custom Projections is moved to the settings dialog in master. Must be something to do with that.

**Comment by roya0045** [comment]
No stacktrace or anything that would point to the cause of crash?

**Comment by LKajan** [comment]
> No stacktrace or anything that would point to the cause of crash?

Every time a settings dialog is opened there is an empty custom coordinate system entry created. Without deleting it this error comes when closing the dialog. No stacktrace in logs or anything.

**Comment by agiudiceandrea** [comment]
> Every time a settings dialog is opened there is an empty custom coordinate system entry created. Without deleting it this error comes when closing the dialog. No stacktrace in logs or anything.

I can confirm using QGIS 3.23.0-Master (e7f3bf4458c16b07d831edf4de7250172a998ed8 MinGW64 Windows Build) on Windows 10.

**Comment by agiudiceandrea** [comment]
See the thread https://lists.osgeo.org/pipermail/qgis-developer/2022-January/064454.html

**Comment by pigreco** [comment]
the problem is still present in 3.22.4, 3.24.0 and 3.25 master

https://user-images.githubusercontent.com/7631137/155880387-b8c6ae8c-fc12-4bb6-949d-72ecf24cee74.mp4
