### ISSUE TITLE
Distance lock and y-lock not working together in advanced digitizing

### ISSUE THREAD

**Issue by LKajan** [qgis/QGIS#47013]
### What is the bug or the crash?

When using Advanced Digitizing tools and its parameter locking features to digitize a 10 meter long horizontal line, new vertex to be added is not snapping to the two "guide" line intersection.
![d-y-locks-not-working](https://user-images.githubusercontent.com/1225021/151136285-5b176046-b5a4-45c7-9c54-0b49ad1cf625.gif)

### Steps to reproduce the issue

1. Activate Advanced digitizing tools
2. Start digitizing a new line
3. Click to set a first vertex
4. Set y-coordinates to be relative (Shift+y)
5. Lock relative y to 0 -> horixontal guide line appears (btw. how do you call these "guide" lines?)
6. Lock distance to 10 -> round guide line appears
7. Now the bug can be seen. New vertex can be digitized to anywhere on the horizontal guide line and it is not snapping to the intersection of these two guide lines.

### Versions

QGIS version
3.23.0-Master
QGIS code revision
159a3e9987
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

### Supported QGIS version

- [x] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Os version in the Help->About says this is Windows 10 2009 but actually I'm running a Windows 11 21H2

**Comment by roya0045** [comment]
I can't reproduce on current master on Ubuntu 21.10

**Comment by antoniolocandro** [comment]
I can confirm not working on windows as described. Distance parameter is completely ignored

QGIS version
3.23.0-Master
QGIS code revision
15a77662d4

**Comment by roya0045** [comment]
And now I can't make it work on the same build...

**Comment by roya0045** [comment]
Ok found the issue to this, it's because the previous point is used as the center instead of the current point. The rubberband seem to use a distinct code that also has some issues as it can shift up or down the points found. I'm not sure if this should be in this issue or another one.
