### ISSUE TITLE
Some digitizing tools cause an OGR error when "Automatically create transaction groups..." is checked

### ISSUE THREAD

**Issue by jrosleo** [qgis/QGIS#47026]
### What is the bug or the crash?

Using some digitizing tools (add ring, fill ring, etc.) on a layer stored in GeoPackage cause an OGR error (failed to execute update: database table is locked) when "Automatically create transaction groups where possible" is checked.

### Steps to reproduce the issue

1. On browser panel right clic on GeoPackage and select "Create database...".
2. Add a polygon table (EPSG:4326 - WGS 84) with a text data field named "code". Let defaults advanced options intact.
3. On "Project\Properties..." menu option, clic "Data Sources" and check "Automatically create transaction groups where possible".
4. Toggle Editing the layer.
5. Add a polygon feature.
6. Clic on "Save layer edits".
7. Clic on "Add a ring".
8. Draw a ring polygon and right-clic.
9. An error is showed: "Layer test: OGR error setting feature 1: failed to execute update: database table is locked".

### Versions

QGIS version
3.22.3-Białowieża
QGIS code revision
1628765ec7
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
Compiled against GEOS
3.10.0-CAPI-1.16.0
Running against GEOS
3.10.2-CAPI-1.16.0
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
DataPlotly
3.8.1
pluginbuilder3
3.2.1
QgisModelBaker
v7.0.2
qgis_versioning
1.0
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
Confirmed here too.

**Comment by jrosleo** [comment]
It still fails in version 3.26.3 but it works fine with the [buffered transaction groups](https://github.com/qgis/QGIS-Enhancement-Proposals/issues/203) option enabled proposed by @m-kuhn and sponsored by Canton Glarus. I don't know if this issue will be fixed for the "Automatic Transaction Groups" option. @m-kuhn, any suggestions?

**Comment by m-kuhn** [comment]
The buffered transaction groups were the main plan to fix this. If possible I would stick to this.

**Comment by jrosleo** [comment]
Ok, thank you very much,
