### ISSUE TITLE
raster processing tools

### ISSUE THREAD

**Issue by MUSA-2022** [qgis/QGIS#47022]
### What is the bug or the crash?

The clip raster function does not run.
This error message comes up: 
"2022-01-26T16:57:03     WARNING    Failed to load C:/OSGeo4W/apps/qgis-ltr/plugins/grassrasterprovider7.dll (Reason: Cannot load library C:\OSGeo4W\apps\qgis-ltr\plugins\grassrasterprovider7.dll: No se puede encontrar el módulo especificado.)"

Yet, the plugin is in the right folder. 

### Steps to reproduce the issue

1. Load a raster. 
2. Extraction
3. Clip raster by >

### Versions

QGIS version
3.16.13-Hannover
QGIS code revision
a8618a94
Compiled against Qt
5.15.2
Running against Qt
5.15.2
Compiled against GDAL/OGR
3.4.0
Running against GDAL/OGR
3.4.0
Compiled against GEOS
3.10.0-CAPI-1.16.0
Running against GEOS
3.10.0-CAPI-1.16.0
Compiled against SQLite
3.35.2
Running against SQLite
3.35.2
PostgreSQL Client Version
13.0
SpatiaLite Version
5.0.1
QWT Version
6.1.3
QScintilla2 Version
2.11.5
Compiled against PROJ
8.2.0
Running against PROJ
Rel. 8.2.0, November 1st, 2021
OS Version
Windows 10 Version 2009
Active python plugins
calcarea2; 
FreehandRasterGeoreferencer; 
LoadQSS; 
db_manager; 
MetaSearch; 
processing; 
quick_map_services; 
ee_plugin

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

Thanks,

**Comment by alexbruy** [comment]
Looks like a packaging or local issue.

**Comment by gioman** [comment]
> 3\. Clip raster by >

@MUSA-2022 what does happen at this step?

**Comment by agiudiceandrea** [comment]
It seems to me the reported warning belongs to the "GRASS 7".

Both the "Clip raster by extent" and the "Clip raster by mask layer" algorithms are GDAL algorithms: they do not depend on the "GRASS 7" plugin.
