### ISSUE TITLE
QGIS is using a custom TMPDIR variable causing troubles with GRASS processing tools

### ISSUE THREAD

**Issue by M-Rick** [qgis/QGIS#47048]
### What is the bug or the crash?

I have troubles when using grass processing tools. I discovered that it's using a custom cache path `/private/var/folders/gs/gzbw4skj6_s7qnb9j96gw9h80000gn/T/`

After looking at the QGIS settings, I finally discovered that QGIS was loading a TMPDIR directory path variable.
![Capture d’écran 2022-01-28 à 11 55 29](https://user-images.githubusercontent.com/2520948/151538736-d5d1eb64-0d85-4e77-b204-ea19fa7fe648.png)

I cannot find a way to remove this once for all.

I tried to create a new user TMPDIR variable. It is loaded, but GRASS processing tools are still using the default one.
I tried a new QGIS profile even created a blank new user profile.
I tried QGIS 3.16 / 3.22 And I'm running macOS Mojave 10.14 and macOS BigSur 11.6

`Version de QGIS : 3.22.3-Białowieża
Révision du code : 1628765ec7
Version de Qt : 5.15.2
Version de Python : 3.9.5
Version de GDAL : 3.3.2
Version de GEOS : 3.9.1-CAPI-1.14.2
Version de Proj : Rel. 8.1.1, September 1st, 2021
Version de PDAL : 2.3.0 (git-version: Release)
Algorithme commencé à: 2022-01-28T11:45:51
Démarrage de l'algorithme 'v.generalize'…
Paramètres en entrée:
{ '-l' : True, '-t' : False, 'GRASS_MIN_AREA_PARAMETER' : 0.0001, 'GRASS_OUTPUT_TYPE_PARAMETER' : 0, 'GRASS_REGION_PARAMETER' : None, 'GRASS_SNAP_TOLERANCE_PARAMETER' : -1, 'GRASS_VECTOR_DSCO' : '', 'GRASS_VECTOR_EXPORT_NOCAT' : False, 'GRASS_VECTOR_LCO' : '', 'alpha' : 1, 'angle_thresh' : 3, 'beta' : 1, 'betweeness_thresh' : 0, 'cats' : '', 'closeness_thresh' : 0, 'degree_thresh' : 0, 'error' : 'TEMPORARY_OUTPUT', 'input' : '/Users/aymeric/Desktop/Setram.gpkg|layername=Setram', 'iterations' : 1, 'look_ahead' : 7, 'method' : 0, 'output' : 'TEMPORARY_OUTPUT', 'reduction' : 50, 'slide' : 0.5, 'threshold' : 1, 'type' : [0,1,2], 'where' : '' }
 
g.proj -c wkt="/private/var/folders/gs/gzbw4skj6_s7qnb9j96gw9h80000gn/T/processing_NneHAU/5b2092f169164688aadd2a03842630f8/crs.prj"
v.in.ogr min_area=0.0001 snap=-1.0 input="/Users/aymeric/Desktop/Setram.gpkg" layer="Setram" output="vector_61f3c95fc51252" --overwrite -o
g.region n=48.0782026 s=47.9061746 e=0.3360741 w=0.0704268
v.generalize input=vector_61f3c95fc51252 type="line,boundary,area" method="douglas" threshold=1 look_ahead=7 reduction=50 slide=0.5 angle_thresh=3 degree_thresh=0 closeness_thresh=0 betweeness_thresh=0 alpha=1 beta=1 iterations=1 -l output=outputa315f6afaff24396b6ec0f06f5d6aa55 error=errora315f6afaff24396b6ec0f06f5d6aa55 --overwrite
v.out.ogr type="auto" input="outputa315f6afaff24396b6ec0f06f5d6aa55" output="/private/var/folders/gs/gzbw4skj6_s7qnb9j96gw9h80000gn/T/processing_NneHAU/8aa5929e21af43a3b8bc45dd07cea0a6/output.gpkg" format="GPKG" --overwrite
v.out.ogr type="auto" input="errora315f6afaff24396b6ec0f06f5d6aa55" output="/private/var/folders/gs/gzbw4skj6_s7qnb9j96gw9h80000gn/T/processing_NneHAU/bbd3cb9c531d48c3a0129e694990587c/error.gpkg" format="GPKG" --overwrite
Default locale settings are missing. GRASS running with C locale.
Starting GRASS GIS...
Cleaning up temporary files...
Executing </private/var/folders/gs/gzbw4skj6_s7qnb9j96gw9h80000gn/T/processing_NneHAU/grassdata/grass_batch_job.sh> ...
Default region was updated to the new projection, but if you have multiple mapsets `g.region -d` should be run in each to update the region from the default
Projection information updated
Over-riding projection check
Check if OGR layer <Setram> contains polygons...
0..2..4..6..8..10..12..14..16..18..20..22..24..26..28..30..32..34..36..38..40..42..44..46..48..50..52..54..56..58..60..62..64..66..68..70..72..74..76..78..80..82..84..86..88..90..92..94..96..98..100
Creating attribute table for layer <Setram>...
Column name <color:ncs> renamed to <color_ncs>
Column name <color:hlc> renamed to <color_hlc>
Column name <color:cmyk> renamed to <color_cmyk>
DBMI-SQLite driver error:
Error in sqlite3_prepare():
near "to": syntax error
DBMI-SQLite driver error:
Error in sqlite3_prepare():
near "to": syntax error
ERROR: Unable to create table: 'create table vector_61f3c95fc51252 (cat integer, full_id text, osm_id text, osm_type text, color_ncs text, color_hlc text, true text, type text, network text, name text, width text, via text, to text, service text, route_type text, route_text_color text, route_short_name text, route_long_name text, route_id text, route_color text, route text, oneway text, offset text, from text, color_cmyk text, bus text, agency_id text)'
WARNING: Unable to open vector map <vector_61f3c95fc51252@PERMANENT> on level 2. Try to rebuild vector topology with v.build.
ERROR: Unable to open vector map <vector_61f3c95fc51252>
ERROR: Vector map <outputa315f6afaff24396b6ec0f06f5d6aa55> not found
ERROR: Vector map <errora315f6afaff24396b6ec0f06f5d6aa55> not found
Execution of </private/var/folders/gs/gzbw4skj6_s7qnb9j96gw9h80000gn/T/processing_NneHAU/grassdata/grass_batch_job.sh> finished.
Cleaning up default sqlite database ...
Cleaning up temporary files...
Default locale settings are missing. GRASS running with C locale.
Starting GRASS GIS...
Cleaning up temporary files...
Executing </private/var/folders/gs/gzbw4skj6_s7qnb9j96gw9h80000gn/T/processing_NneHAU/grassdata/grass_batch_job.sh> ...
ERROR: Vector map <outputa315f6afaff24396b6ec0f06f5d6aa55> not found
ERROR: Vector map <errora315f6afaff24396b6ec0f06f5d6aa55> not found
Execution of </private/var/folders/gs/gzbw4skj6_s7qnb9j96gw9h80000gn/T/processing_NneHAU/grassdata/grass_batch_job.sh> finished.
Cleaning up default sqlite database ...
Cleaning up temporary files...
Execution completed in 2.05 secondes
Résultats :
{'error': '/private/var/folders/gs/gzbw4skj6_s7qnb9j96gw9h80000gn/T/processing_NneHAU/bbd3cb9c531d48c3a0129e694990587c/error.gpkg', 'output': '/private/var/folders/gs/gzbw4skj6_s7qnb9j96gw9h80000gn/T/processing_NneHAU/8aa5929e21af43a3b8bc45dd07cea0a6/output.gpkg'}
 
Chargement des couches de résultat
Les couches suivantes n'ont pas été générées correctement. • /private/var/folders/gs/gzbw4skj6_s7qnb9j96gw9h80000gn/T/processing_NneHAU/8aa5929e21af43a3b8bc45dd07cea0a6/output.gpkg • /private/var/folders/gs/gzbw4skj6_s7qnb9j96gw9h80000gn/T/processing_NneHAU/bbd3cb9c531d48c3a0129e694990587c/error.gpkg Vous pouvez vérifier le Panel de messages du journal dans la fenêtre principale de QGIS pour trouver plus d'informations à propos de l'exécution de l'algorithme.
`

### Steps to reproduce the issue

Apply any of the grass processing tools on a layer.
It will bring errors with unresolving paths.
Whatever the algorithm used, it's always the same error happening. The temporary layer cannot be found.
I tried with a local file instead of a temporary layer, same result happening.

### Versions

Version de QGIS | 3.22.2-Białowieża | Révision du code | 1601ec46d0
-- | -- | -- | --
Version de Qt | 5.15.2
Version de Python | 3.9.5
Version de GDAL/OGR | 3.3.2
Version de Proj | 8.1.1
Version de la base de données du registre EPSG | v10.028 (2021-07-07)
Version de GEOS | 3.9.1-CAPI-1.14.2
Version de SQLite | 3.35.2
Version de PDAL | 2.3.0
Version du client PostgreSQL | 12.3
Version de SpatiaLite | 5.0.1
Version de QWT | 6.1.6
Version de QScintilla2 | 2.11.5
Version de l'OS | macOS 11.6
  |   |   |  
Extensions Python actives
ORStools | 1.5.2
QuickOSM | 2.0.0
gban | 1.1
QNEAT3 | 1.0.4
amil | 1.1.1
qgis_report_wizard | 1.0.1
latlontools | 3.6.2
OpenTripPlannerPlugin-master | 1.0
anyways_impact_toolbox | 0.6.4
Qgis2threejs | 2.6
mobilityareas | 0.1
valhalla | 2.2.1
GTFS-GO-master | 2.2.0
ProjectPackager | 0.5.1
GTFS_Loader | 1.0.0
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.5

Version de QGIS | 3.16.15-Hannover | Révision du code | e7fdad6431
-- | -- | -- | --
Compilé avec Qt | 5.14.2 | Utilisant Qt | 5.14.2
Compilé avec GDAL/OGR | 3.2.1 | Utilisé avec GDAL/OGR | 3.2.1
Compilé avec GEOS | 3.9.1-CAPI-1.14.2 | Utilisé avec GEOS | 3.9.1-CAPI-1.14.2
Compilé avec SQLite | 3.31.1 | Fonctionne avec SQLite | 3.31.1
Version du client PostgreSQL | 12.3 | Version de SpatiaLite | 4.3.0a
Version de QWT | 6.1.4 | Version de QScintilla2 | 2.11.4
Compilé avec PROJ | 6.3.2 | Fonctionne avec PROJ | Rel. 6.3.2, May 1st, 2020
Version de l'OS | macOS 11.6
Extensions Python actives | ORStools; QuickOSM; gban; QNEAT3; amil; qgis_report_wizard; latlontools; OpenTripPlannerPlugin-master; anyways_impact_toolbox; Qgis2threejs; mobilityareas; valhalla; GTFS-GO-master; ProjectPackager; GTFS_Loader; processing; db_manager; MetaSearch

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
> I have troubles when using grass processing tools.

@M-Rick I have just tested a few GRASS/Processing tools on macOS Montery and they worked fine. Can you eleborate about your issues?

**Comment by gioman** [comment]
> Well each time I try a GRASS processing tool,

@M-Rick weird, try with a new QGIS profile (you have checked the option in the ticket template, but have quite a few 3rd party plugins installed).

**Comment by M-Rick** [comment]
No change

**Comment by M-Rick** [comment]
I did some tries.
If I create a memory layer with no field it will work.
It seems to happen with datas imported from OSM files.
You can give a look at this file. None of the GRASS tools are working on this line.
[Test GRASS.geojson.zip](https://github.com/qgis/QGIS/files/8010957/Test.GRASS.geojson.zip)

**Comment by gioman** [comment]
> It seems to happen with datas imported from OSM files.

@M-Rick have you tried with anything else than geojson? or does it happen only with geojsons?

**Comment by M-Rick** [comment]
> 

Yes, at the beginning I was using GPKG. I made a GeoJSON only to export.
I tried to copy paste in a memory player as well.

**Comment by gioman** [comment]
@M-Rick you must remove the "fid" column from your data before processing it with GRASS tools, or as a workaround set the tool to output to something (i.e. SHP) that is not GPKG.

**Comment by M-Rick** [comment]
> @M-Rick you must remove the "fid" column from your data before processing it with GRASS tools, or as a workaround set the tool to output to something (i.e. SHP) that is not GPKG.

I have other datas with a fid column and it works.
[Test 2.geojson.zip](https://github.com/qgis/QGIS/files/8011085/Test.2.geojson.zip)

**Comment by gioman** [comment]
@M-Rick your layer has columns named "to" and "from", which are reserved words. Also columns with ":" in its name are invalid.
