### ISSUE TITLE
Rule-based styling no longer aligns patterns

### ISSUE THREAD

**Issue by goney3** [qgis/QGIS#47111]
### What is the bug or the crash?

Rule-based styling used to always align with each other along polygons in QGIS since forever, however more recent QGIS versions display chaotically instead of a unified pattern being displayed. This makes it very difficult for overlays in municipal use cases of QGIS.

The rule based lines repeating as usual in 3.8

![The rule based lines repeating as usual in 3.8](https://i.ibb.co/KsRf6JW/Screenshot-2022-01-31-143920.png)

The rule based lines going haywire in current version

![The rule based lines going haywire in current version](https://i.ibb.co/8gcqgkk/Screenshot-2022-01-31-143949.png)

### Steps to reproduce the issue

1. Make a Line Pattern Fill that makes up a crosshatch pattern in rule-based in an older QGIS version (I tested 3.8 because that was the oldest version I had on-hand).
2. Use that same symbology rule-based in a newer version of QGIS.
3.  Notice how the lines no longer repeat nicely with each other but go with individual polygons that don't line up.
4.  Notice how there is no easy to find setting or option to adjust this behavior.
5.  Please fix.

Example images of behavior is provided above for reference.

### Versions

Versions used (that I had available): 

**Working correctly in:** 3.8.1

**Not working correctly in:** 3.18.3, 3.20.3, 3.22.3

**Not tested:** 3.10, 3.12, 3.14, 3.16

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

We use the rule based classifications in a municipal environment where we need multiple styles for each polygon since it pulls from our parcel tracking system (as a joined database table view). We have had success in using earlier versions of QGIS. But with the slowdown of the pandemic we didn't start getting back into zoning changes until recently and noticed that our Zoning maps are now broken. I have tried looking for solutions online but have come up empty handed, I looked through the QGIS changelog website to see any mention of a change like this, and haven't been able to find what broke or how to switch it back to how it used to work. I hope this is an easier fix to go with whatever change was implemented. Thank you.

**Comment by nyalldawson** [comment]
On latest versions you must set the line pattern fill "Alignment" to "Align Pattern to Map Extent":

![image](https://user-images.githubusercontent.com/1829991/151900532-0397f924-976b-4091-a58a-0974f6f565a2.png)

**Comment by nyalldawson** [comment]
@goney3 yes, 3.24+
