### ISSUE TITLE
GDAL: "Clip vector by mask layer" takes forever as it does not seem to consider the mask layer's extent

### ISSUE THREAD

**Issue by tschmetzer** [qgis/QGIS#47147]
### What is the bug or the crash?

I've been testing the "Clip vector by mask layer" and the "Clip vector by extent" tool of the GDAL processing suite I encountered very long processing times (>10 min) with "Clip vector by mask layer" which could easily be avoided by considering the clipped layer's extent. I was using a large vector point layer (20GB) as input. The mask layer (New scratch layer) consists of only the one simple geometry shown in the screenshot.
Clipping the layer just by another layer's extent was a matter of seconds. 

Why not process the vector layer's features only within the mask layer's extent? At least the user should be offered to limit the calculation to the mask layer's extent by adding the -spat option.

![image](https://user-images.githubusercontent.com/67278094/152150175-13237117-633d-49f7-a618-dcff24a20f78.png)

![image](https://user-images.githubusercontent.com/67278094/152148175-c9044619-1982-46e4-b247-3711cf49143a.png)

Not sure if this is a feature request though or a matter to be forwarded to GDAL.

### Steps to reproduce the issue

1. Load a large vector point layer and create a very simple vector mask layer as shown in the screenshot
2. Use the GDAL algorithm "Clip vector by mask layer"
3. Observe it takes very long to process.

### Versions

QGIS version
3.22.3-Białowieża
QGIS code revision
1628765ec7
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
Compiled against GEOS
3.10.0-CAPI-1.16.0
Running against GEOS
3.10.2-CAPI-1.16.0
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@tschmetzer 

> Why not process the vector layer's features only within the mask layer's extent?

you can do a spatial selection before running the tool



> At least the user should be offered to limit the calculation to the mask layer's extent by adding the -spat option.

using a mask or an extent are two different things. The bbox/extent of a polygon is not the polygon, is a different (rectangular one).


You must test the GDAL command with the mask (the one that QGIS shows you at the bottom of the tool dialog) from the command line, and see if the performance is the same.

**Comment by tschmetzer** [comment]
> @tschmetzer
> 
> > Why not process the vector layer's features only within the mask layer's extent?
> 
> you can do a spatial selection before running the tool

Of course the user could do that. But that's not the point.

> > At least the user should be offered to limit the calculation to the mask layer's extent by adding the -spat option.
> 
> using a mask or an extent are two different things. The bbox/extent of a polygon is not the polygon, is a different (rectangular one).

Thanks for the clarification. I am aware of the difference between bbox/**extent** and the polygon **mask**.
 
> You must test the GDAL command with the mask (the one that QGIS shows you at the bottom of the tool dialog) from the command line, and see if the performance is the same.

I don't have any doubt about QGIS passing the right command to gdal/ogr2ogr. The results would be the same.

Point is: If the vector layer was limited to the mask layer's extent while processessing a lot of time could be saved:
![grafik](https://user-images.githubusercontent.com/67278094/152219141-3fad2694-bb67-486d-960b-cfaab2db1c66.png)

No idea why the comparison with the geometry index is so slow when processed but that's probably a different discussion and I am not an expert.

**Comment by alexbruy** [comment]
@tschmetzer in this case QGIS acts only as a frontend for GDAL tool. So this report should be filed upstream.

Also note that you can easily apply a filter by creating a model from two tools. The model then will act as any other algorithm.

**Comment by gioman** [comment]
> I don't have any doubt about QGIS passing the right command to gdal/ogr2ogr. The results would be the same.

@tschmetzer but is that is the case then is not a QGIS problem. For this GDAL tools QGIS acts as a GUI.

**Comment by nyalldawson** [comment]
You could also use the native qgis "clip" tool and compare the performance.

**Comment by gioman** [comment]
> No idea wether that's worth the effort knowing QGIS probably has better native algorithms.

@tschmetzer that's not really the point to me (as anyway  there are cases where non native tools are more efficient). The point here is that on QGIS side this is easly solvable with a spatial selection, that you can wrap in a very simple model that you can expose as a custom tool.

**Comment by tschmetzer** [comment]
> > No idea wether that's worth the effort knowing QGIS probably has better native algorithms.
> 
> @tschmetzer that's not really the point to me (as anyway there are cases where non native tools are more efficient). The point here is that on QGIS side this is easly solvable with a spatial selection, that you can wrap in a very simple model that you can expose as a custom tool.

Of course one can do a spatial (pre)selection and add it as a custom tool. If the guideline/maxime is to keep functions atomic (i.e. simple logic without any amentments) then I understand. 
My argument based on a usability perspective was to provide a function that fulfills its purpose without having to concern about an algorithm that stupidly processes things that are totally out of context.
Keeping the atomic function in mind and not wanting to overload/pollute the list of available processing algorithms I still think my feature request wouldn't be a bad idea. Or would this be inconsistent with other functionalities then?

**Comment by gioman** [comment]
> If the guideline/maxime is to keep functions atomic (i.e. simple logic without any amentments) then I understand.

it is the case.

**Comment by tschmetzer** [comment]
Understood.

So what to do with the ticket? Options:
- File an upstream ticket to gdal (which might not get accepted as such)
- Feature request to create a new model/algorithm combining clip and extent
- Close as not a bug

My only concern if only closed as "not a bug" with no further action the user won't be informed about a very slow (atomic) algorithm in advance

**Comment by gioman** [comment]
@tschmetzer I'll leave one of the Processing developers / maintainers to take action here @alexbruy .

**Comment by alexbruy** [comment]
Personally I'd be in favour of closing this as wontfix, as there is a modeler where one can easily create models to satisfy any type of filtering they need.
