### ISSUE TITLE
Add support for ArcGIS Online "X-Esri-Authorization" header to ESRI Token Auth method

### ISSUE THREAD

**Issue by ehallein** [qgis/QGIS#47142]
### What is the bug or the crash?

When using the ArcGIS rest server connection to connect to ArcGIS Online with either Esri token or OAuth2, only public layers are displayed, private layer do not appear. No errors are given. It seems the token is not sent correctly

### Steps to reproduce the issue

Create a new OAuth 2.0 application on developers.argis.com

In QGIS
Go to Layer, add Layer, click on Add ArcGIS REST server layer
Click New
Add ArcGIS Online service url
select ESRI token under authentication 
Add Temporary Token from ESRO OAuth 2.0 application 
press connect
only public layers will be  shown.

The same happens if using OAuth2 authentication with clientID and secret with arcgis online sharing/rest/oauth2/authorize and sharing/rest/oauth2/token urls.  Login occurs in browser, but QGIS doesn't appear to send token when connecting

### Versions

3.22.3

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

process was followed from here https://north-road.com/2020/06/04/securely-accessing-enterprise-arcgis-portal-sites-through-qgis/

**Comment by nyalldawson** [comment]
@ehallein 

Can you make sure that in your oath2 setup you have these settings:

Access method: Header
Token header: X-Esri-Authorization

**Comment by ehallein** [comment]
> @ehallein
> 
> Can you make sure that in your oath2 setup you have these settings:
> 
> Access method: Header Token header: X-Esri-Authorization

Yep, that fixed the OAuth 2 side.  Is there an option for the token Authentication to ass this?

thanks

**Comment by nyalldawson** [comment]
Note in current versions, but 3.24 (coming soon) has a new authentication type for custom headers which you could use for this.

Changing this to a feature request to add a "X-Esri-Authorization" option to the ESRI token auth method

**Comment by DelazJ** [comment]
@gioman not sure this requires a feedback label. Initial issue seems solved and the report turned into feature request.

**Comment by gioman** [comment]
I added the label to be sure that the reporter will test with the new release and leave further feedback.
