### ISSUE TITLE
QGIS seg faults when trying to find an option

### ISSUE THREAD

**Issue by CoryAlbrecht** [qgis/QGIS#47155]
### What is the bug or the crash?

When try to search for an option via the text control in the upper left corner of the options window, as soon as you type the third character the entire app segfaults.

### Steps to reproduce the issue

1. Start QGIS from command line
2. Open Menu→Settings→Options
3. Start typing into the search control
4. See the error `Segmentation fault (core dumped)` on the console

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.3-Białowieża | QGIS code revision | d1a4af7218
-- | -- | -- | --
Qt version | 5.12.8
Python version | 3.8.10
GDAL/OGR version | 3.0.4
PROJ version | 6.3.1
EPSG Registry database version | v9.8.6 (2020-01-22)
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
SQLite version | 3.31.1
PDAL version | 2.0.1
PostgreSQL client version | 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.2
OS version | Ubuntu 20.04.3 LTS
  |   |   |  
This copy of QGIS writes debugging output.
  |   |   |  
Active Python plugins

</body></html>QGIS version
3.22.3-Białowieża
QGIS code revision
[d1a4af7218](https://github.com/qgis/QGIS/commit/d1a4af7218)
Qt version
5.12.8
Python version
3.8.10
GDAL/OGR version
3.0.4
PROJ version
6.3.1
EPSG Registry database version
v9.8.6 (2020-01-22)
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
SQLite version
3.31.1
PDAL version
2.0.1
PostgreSQL client version
12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)
SpatiaLite version
4.3.0a
QWT version
6.1.4
QScintilla2 version
2.11.2
OS version
Ubuntu 20.04.3 LTS

This copy of QGIS writes debugging output.

Active Python plugins

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by ismailsunni** [comment]
Hmm, strange, I tried to replicate it, but everything seems fine here. I have the same version as you. The only difference is the QGIS Code revision. Mine is 1628765ec7

**Comment by gioman** [comment]
> * Start QGIS from command line
> 
> * Open Menu→Settings→Options
> 
> * Start typing into the search control
> 
> * See the error `Segmentation fault (core dumped)` on the console

@CoryAlbrecht also can't confirm. QGIS 3.22.3 from QGIS.org's repos and Ubuntu 20.04.

**Comment by agiudiceandrea** [comment]
https://github.com/qgis/QGIS/commit/d1a4af72184c35582a979075d3255aa585cd0bc9 seems a recent nightly build of the branch 3.22 after the release of 3.22.3

**Comment by gioman** [comment]
> [d1a4af7](https://github.com/qgis/QGIS/commit/d1a4af72184c35582a979075d3255aa585cd0bc9) seems a recent nightly build of the branch 3.22 after the release of 3.22.3

so @CoryAlbrecht has not reported the correct version(?).

**Comment by agiudiceandrea** [comment]
It is the About window that reports the version that way.
I can confirm it is a nightly build of the 3.22 branch (at https://github.com/qgis/QGIS/commit/d1a4af72184c35582a979075d3255aa585cd0bc9) after the release of 3.22.3 (at https://github.com/qgis/QGIS/commit/1628765ec7d40ded50bbaf1cd08220bb390e8783) for Ubuntu 20.04 Focal Fossa available  from https://qgis.org/ubuntugis-nightly-release/ (see https://qgis.org/ubuntugis-nightly-release/pool/main/q/qgis/) or https://qgis.org/ubuntu-nightly-release/ (see https://qgis.org/ubuntu-nightly-release/pool/main/q/qgis/)

**Comment by agiudiceandrea** [comment]
If confirmed the bug at https://github.com/qgis/QGIS/commit/d1a4af72184c35582a979075d3255aa585cd0bc9 but not at https://github.com/qgis/QGIS/commit/1628765ec7d40ded50bbaf1cd08220bb390e8783 then it means that something introduced the bug between the two commits: https://github.com/qgis/QGIS/compare/1628765...d1a4af7

**Comment by roya0045** [comment]
A full trace would be more helpful to find, and to prevent having that issue in the next release. @gioman should the crash label be added?

**Comment by roya0045** [comment]
Just tested on master, on ubuntu 21.10; cannot get a crash.

**Comment by agiudiceandrea** [comment]
Not confirmed using QGIS 3.22 nightly build (QGIS code revision 8cdf9cfa60, more recent then https://github.com/qgis/QGIS/commit/d1a4af72184c35582a979075d3255aa585cd0bc9) on Windows (OSGeo4W v2).

**Comment by CoryAlbrecht** [comment]
> > [d1a4af7](https://github.com/qgis/QGIS/commit/d1a4af72184c35582a979075d3255aa585cd0bc9) seems a recent nightly build of the branch 3.22 after the release of 3.22.3
> 
> so @CoryAlbrecht has not reported the correct version(?).

I can only report what QGIS gives me in the about page. The timestamp on /usr/bin/qgius is Jan 31 19:08

**Comment by CoryAlbrecht** [comment]
Updates just now. Still happening

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>


QGIS version | 3.22.3-Białowieża | QGIS code revision | 926f9dad44
-- | -- | -- | --
Qt version | 5.12.8
Python version | 3.8.10
GDAL/OGR version | 3.0.4
PROJ version | 6.3.1
EPSG Registry database version | v9.8.6 (2020-01-22)
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
SQLite version | 3.31.1
PDAL version | 2.0.1
PostgreSQL client version | 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.2
OS version | Ubuntu 20.04.3 LTS
  |   |   |  
This copy of QGIS writes debugging output.
  |   |   |  
Active Python plugins
QGIS3-getWKT | 1.4
geometry_paster | 0.1.1
postgisQueryBuilder | 2.0.1
ClipMultipleLayers | 3.2.0
cartography_tools | 1.2.1
bettereditor | 1.5.0
quick_map_services | 0.19.27
db-style-manager | 0.8
splitmultipart | 1.0.0
pg_raster_import | 1.0.10
grassprovider | 2.12.99
processing | 2.12.99
db_manager | 0.1.20
sagaprovider | 2.12.99

</body></html>QGIS version
3.22.3-Białowieża
QGIS code revision
[926f9dad44](https://github.com/qgis/QGIS/commit/926f9dad44)
Qt version
5.12.8
Python version
3.8.10
GDAL/OGR version
3.0.4
PROJ version
6.3.1
EPSG Registry database version
v9.8.6 (2020-01-22)
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
SQLite version
3.31.1
PDAL version
2.0.1
PostgreSQL client version
12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)
SpatiaLite version
4.3.0a
QWT version
6.1.4
QScintilla2 version
2.11.2
OS version
Ubuntu 20.04.3 LTS




This copy of QGIS writes debugging output.




Active Python plugins
QGIS3-getWKT
1.4
geometry_paster
0.1.1
postgisQueryBuilder
2.0.1
ClipMultipleLayers
3.2.0
cartography_tools
1.2.1
bettereditor
1.5.0
quick_map_services
0.19.27
db-style-manager
0.8
splitmultipart
1.0.0
pg_raster_import
1.0.10
grassprovider
2.12.99
processing
2.12.99
db_manager
0.1.20
sagaprovider
2.12.99

**Comment by CoryAlbrecht** [comment]
Raw copy of what Ctrl+A gets in the About window
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.3-Białowieża | QGIS code revision | 926f9dad44
-- | -- | -- | --
Qt version | 5.12.8
Python version | 3.8.10
GDAL/OGR version | 3.0.4
PROJ version | 6.3.1
EPSG Registry database version | v9.8.6 (2020-01-22)
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
SQLite version | 3.31.1
PDAL version | 2.0.1
PostgreSQL client version | 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.2
OS version | Ubuntu 20.04.3 LTS
  |   |   |  
This copy of QGIS writes debugging output.
  |   |   |  
Active Python plugins
QGIS3-getWKT | 1.4
geometry_paster | 0.1.1
postgisQueryBuilder | 2.0.1
ClipMultipleLayers | 3.2.0
cartography_tools | 1.2.1
bettereditor | 1.5.0
quick_map_services | 0.19.27
db-style-manager | 0.8
splitmultipart | 1.0.0
pg_raster_import | 1.0.10
grassprovider | 2.12.99
processing | 2.12.99
db_manager | 0.1.20
sagaprovider | 2.12.99

</body></html>QGIS version
3.22.3-Białowieża
QGIS code revision
[926f9dad44](https://github.com/qgis/QGIS/commit/926f9dad44)
Qt version
5.12.8
Python version
3.8.10
GDAL/OGR version
3.0.4
PROJ version
6.3.1
EPSG Registry database version
v9.8.6 (2020-01-22)
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
SQLite version
3.31.1
PDAL version
2.0.1
PostgreSQL client version
12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)
SpatiaLite version
4.3.0a
QWT version
6.1.4
QScintilla2 version
2.11.2
OS version
Ubuntu 20.04.3 LTS




This copy of QGIS writes debugging output.




Active Python plugins
QGIS3-getWKT
1.4
geometry_paster
0.1.1
postgisQueryBuilder
2.0.1
ClipMultipleLayers
3.2.0
cartography_tools
1.2.1
bettereditor
1.5.0
quick_map_services
0.19.27
db-style-manager
0.8
splitmultipart
1.0.0
pg_raster_import
1.0.10
grassprovider
2.12.99
processing
2.12.99
db_manager
0.1.20
sagaprovider
2.12.99
```

**Comment by gioman** [comment]
> QGIS3-getWKT
> 1.4
> geometry_paster
> 0.1.1
> postgisQueryBuilder
> 2.0.1
> ClipMultipleLayers
> 3.2.0
> cartography_tools
> 1.2.1
> bettereditor
> 1.5.0
> quick_map_services
> 0.19.27
> db-style-manager
> 0.8
> splitmultipart
> 1.0.0
> pg_raster_import

@CoryAlbrecht try with a new QGIS profile.

**Comment by gioman** [comment]
> This copy of QGIS writes debugging output.

@CoryAlbrecht also in a normal installation on Ubuntu, you should not see the above message.

This is how it looks now by installing with QGIS.org's repos

![image](https://user-images.githubusercontent.com/1951107/152789682-843c22ca-093a-41c6-ba16-40d69b6988e2.png)

**Comment by agiudiceandrea** [comment]
> Updated from:
> 
> ```
> # Release Nightly
> deb [arch=amd64] http://qgis.org/ubuntu-nightly-release focal main
> deb-src [arch=amd64] http://qgis.org/ubuntu-nightly-release focal main
> ```

> > This copy of QGIS writes debugging output.

> in a normal installation on Ubuntu, you should not see the above message.

@gioman, he has installed a nightly build, which is a debug build, so its normal to see the "QGIS writes debugging output" message.

**Comment by gioman** [comment]
> @gioman, he has installed a nightly build, which is a debug build, so its normal to see the "QGIS writes debugging output" message.

@agiudiceandrea yes I know. I'm just saying that he should also test on the current release.

**Comment by agiudiceandrea** [comment]
> @agiudiceandrea yes I know. I'm just saying that he should also test on the current release.

Testing on a nightly build is useful to spot a regression bug in advance (I think they are meant for this very purpose), before the next version is released. If the reported issue were confirmed, it would show up in the next point release.

Anyway, I've also tested with a fresh user profile on a nightly build of the same branch (but more recent of his and on Windows) without experiencing the issue.

**Comment by gioman** [comment]
> Testing on a nightly build is useful to spot a regression bug in advance (I think they are meant for this very purpose), before the next version is released. If the reported issue were confirmed, it would show up in the next point release (if not reported and fixed in time).

@agiudiceandrea yes sure, I always do that.

**Comment by uclaros** [comment]
@CoryAlbrecht are you using a translated user interface?

**Comment by CoryAlbrecht** [comment]
@uclaros No.

**Comment by CoryAlbrecht** [comment]
Still happens in 3.24 Tisler.

**Comment by agiudiceandrea** [comment]
> Still happens in 3.24 Tisler.

@CoryAlbrecht, are you using a nightly developer build of QGIS 3.24.0 or a regular release build? Have you tried with a new QGIS profile (without plugins other than the core ones)?

**Comment by gioman** [comment]
> are you using a nightly developer build of QGIS 3.24.0

@agiudiceandrea by the details in other tickets is still using the nightly instead of regular releases. And this still seems pretty much a local issue as no one else can replicate (and I did tested again on ubuntu 20.04, win10 and macOS Monterey).

**Comment by uclaros** [comment]
@CoryAlbrecht Please try with a new profile, since nobody can reproduce the crash it can be caused by some plugin that adds a custom page in settings. If it still crashes please attach here the stack trace.

**Comment by CoryAlbrecht** [comment]
@uclaros @agiudiceandrea I have tried both with all plugins disabled and with a brand new profile.
I even deleted `~.local/share/QGIS` to mimic a brand new install.

**Comment by uclaros** [comment]
That's quite strange!
Since no one else can reproduce this, we can't do much without at least a stack trace!

**Comment by CoryAlbrecht** [comment]
I just used gdb and it sput out the following:

```
Thread 1 "qgis.bin" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe1356440 (LWP 3475317)]
0x00007ffff3072909 in QAtomicOps<int>::ref<int> (_q_value=...) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_cxx11.h:265
265	        return ++_q_value != 0;
(gdb) 
Continuing.

Thread 1 "qgis.bin" received signal SIGSEGV, Segmentation fault.
__GI_raise (sig=<optimized out>) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) 
Continuing.
QGIS died on signal 11../../src/app/qgscrashhandler.cpp:71 : (handleCrash) [11499ms] /tmp/qgis-crash-info-3475317
../../src/app/qgscrashhandler.cpp:124 : (handleCrash) [0ms] /usr/bin/qgiscrashhandler
[Detaching after fork from child process 3475793]
[Detaching after fork from child process 3475794]
Could not attach to process.  If your uid matches the uid of the target
process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
warning: process 3475317 is already traced by process 3475296
ptrace: Operation not permitted.
No thread selected
No stack.
gdb returned 256

Thread 1 "qgis.bin" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	in ../sysdeps/unix/sysv/linux/raise.c
(gdb) 
Continuing.

Thread 1 "qgis.bin" received signal SIGABRT, Aborted.
__GI_raise (sig=<optimized out>) at ../sysdeps/unix/sysv/linux/raise.c:50
50	in ../sysdeps/unix/sysv/linux/raise.c
(gdb) 
Continuing.
Couldn't get registers: No such process.
Couldn't get registers: No such process.
(gdb) [Thread 0x7fff57cd7700 (LWP 3475781) exited]
[Thread 0x7fff584d8700 (LWP 3475780) exited]
[Thread 0x7fff5ccd9700 (LWP 3475779) exited]
[Thread 0x7fff444d0700 (LWP 3475778) exited]
[Thread 0x7fff41ccf700 (LWP 3475777) exited]
[Thread 0x7fff3f4ce700 (LWP 3475776) exited]
[Thread 0x7fff3eccd700 (LWP 3475775) exited]
[Thread 0x7fff3438a700 (LWP 3475744) exited]
[Thread 0x7fff34b8b700 (LWP 3475743) exited]
[Thread 0x7fff3538c700 (LWP 3475742) exited]
[Thread 0x7fff35b8d700 (LWP 3475741) exited]
[Thread 0x7fff3638e700 (LWP 3475740) exited]
[Thread 0x7fff36b8f700 (LWP 3475739) exited]
[Thread 0x7fff37390700 (LWP 3475738) exited]
[Thread 0x7fff37b91700 (LWP 3475737) exited]
[Thread 0x7fffb2fff700 (LWP 3475704) exited]
[Thread 0x7fffc1a4a700 (LWP 3475703) exited]
[Thread 0x7fffc22dd700 (LWP 3475701) exited]
[Thread 0x7fffc2ade700 (LWP 3475700) exited]
[Thread 0x7fffc32df700 (LWP 3475699) exited]
[Thread 0x7fffc3c8d700 (LWP 3475698) exited]
[Thread 0x7fffcd821700 (LWP 3475353) exited]
[Thread 0x7fffdda9f700 (LWP 3475351) exited]
[Thread 0x7fffde4e4700 (LWP 3475350) exited]
[Thread 0x7fffdece5700 (LWP 3475349) exited]
[Thread 0x7fffe049f700 (LWP 3475348) exited]

Program terminated with signal SIGABRT, Aborted.
The program no longer exists.


```

**Comment by CoryAlbrecht** [comment]
As soon as I type the third character into the search field, that happens.

**Comment by CoryAlbrecht** [comment]
[qgis-crash-info-3475317.gz](https://github.com/qgis/QGIS/files/8187800/qgis-crash-info-3475317.gz)

**Comment by gioman** [comment]
@CoryAlbrecht are you still using the nightly instead of the current release? And more importantly, have you tried on a different machine so to exclude a local issue?
