### ISSUE TITLE
Plugin manager changelog is one version behind

### ISSUE THREAD

**Issue by Houska1** [qgis/QGIS#47172]
### What is the bug or the crash?

This is minor but has persisted for some time.

When using QGIS' plugin manager to browse upgradeable plugins, the changelog shown is only up to the changes in the *previous* version, i.e. doesn't include what is in the changelog for the most recent version you are considering upgrading to. This is in spite of the plugin's changelog.md being up to date.

### Steps to reproduce the issue

In the plugin manager, navigate to a recently upgraded plugin, e.g. (today) R Processing Provider. The changelog in the window (see pic) lists changes up to the *previous* version, 3.1.0 in this instance. It misses the line added in that Plugin's website/pages/changelog.md, for 3.1.1.
![Screen_Capture_-_3_Feb__6_49_am](https://user-images.githubusercontent.com/48919900/152347774-c962e174-d68a-483a-bfd8-6dfc38c154a4.png)
Ditto for at least some other plugins when they get updated; I've noticed it for Lat Lon Tools in particular.

In contrast, a mature plugin, last updated some time ago, like Quick Map Services, does have the up-to-date changelog reflected in the plugin manager.

### Versions

3.23 Master, OSGeo4W. Though I'm pretty sure it happens on 3.22 and earlier too.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by Houska1** [comment]
Commenting to stress that the full changelog seems to become reflected later, some time after the plugin upgrade happens. So if someone looks at this bug report in several days/weeks/months, it's likely to be fine for the example I pasted above (R Provider) if it's been a while since that plugin was updated. Need to look for recently upgraded plugins.

**Comment by agiudiceandrea** [comment]
@Houska1 this is a plugin issue: as you can see, the plugin's metadata.txt misses the 3.1.1 changelog entry: https://github.com/north-road/qgis-processing-r/blob/master/processing_r/metadata.txt

**Comment by Houska1** [comment]
OK, when I see it elsewhere I'll bug the plugin authors there too. :)
