### ISSUE TITLE
Crash on digitizing tool in relation editor widget

### ISSUE THREAD

**Issue by signedav** [qgis/QGIS#47193]
### What is the bug or the crash?

When using digitizing tool in relation editor widget the form disappears, the map tool to digitize appears on the canvas and on finalizing the digitizing the form reappears. This works, but when creating a 2nd debt geometry this leads to a crash. Means having a relation editor widget connecting to a child layer having a relation editor widget connecting to a child geometry layer.

### Steps to reproduce the issue

Having Layer "package" 0..* "asset" 0..* "Flaechen". "flaechen" is a polygon layer.

1. Creating a "package" feature
2. Creating with relation editor a "asset" feature
3. Creating with relation editor a "flaechen" feature -> *crash*
![crash](https://user-images.githubusercontent.com/28384354/152491566-9ff11028-9b32-4220-b57c-07407b7cc95e.gif)

Similar behavior on creating a feature with the relation reference widget, but without crash. There the second map tool is just not available (changes to canvas but digitizing is not active).

[nested_geom_crash.zip](https://github.com/qgis/QGIS/files/8001847/nested_geom_crash.zip)

### Versions

QGIS 3.16.16
QGIS master 31ac4082f849c14e0aa6c6c16ca93e63c59756c0

### Supported QGIS version

- [x] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
@signedav please add a sample project with data. Also test first 3.22.3, as 3.16 is EOL and won't get any bug fix anyway.

**Comment by signedav** [comment]
I tested on master. And I attached test data.

**Comment by gioman** [comment]
@signedav crash confirmed with your project.
