### ISSUE TITLE
bands of blanks pixels on bottom and top

### ISSUE THREAD

**Issue by vcloarec** [qgis/QGIS#47203]
### What is the bug or the crash?

With raster layer, from WMS provider or GDAL provider, bands of blanks pixels on the bottom and and the left have appeared when rendering. This is related only for raster layers, vector layers are good.

Some pictures from my screen:
![image](https://user-images.githubusercontent.com/7416892/152626834-2466751d-f286-49aa-a54f-2776d67e1b5f.png)

![image](https://user-images.githubusercontent.com/7416892/152626862-7877bed8-9de8-4733-946a-4c9b3dd847e0.png)

![bands](https://user-images.githubusercontent.com/7416892/152627131-736d2eaa-2886-4773-912c-a0610c786d32.gif)

This affects 3.22.3 and master on kubuntu.

After investigation through past commits, it this seems to come from https://github.com/qgis/QGIS/pull/46816
ping @nyalldawson 

### Steps to reproduce the issue

Load a raster layer

### Versions

3.22.3 and master

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by vcloarec** [comment]
duplicated:  https://github.com/qgis/QGIS/issues/46917#issuecomment-1017702695

**Comment by vcloarec** [comment]
still here with 3.24

**Comment by nyalldawson** [comment]
Can you share a sample project which demonstrates this issue?

**Comment by vcloarec** [comment]
Issue not here anymore with 3.26
