### ISSUE TITLE
 QGIS 3.16.16 error message "Could not find the matplotlib module. Make sure the matplotlib is installed"

### ISSUE THREAD

**Issue by MH-Mueller** [qgis/QGIS#47224]
### What is the bug or the crash?

When I start QGIS 3.16.16, the message "Could not find the matplotlib module. Make sure the matplotlib is installed" pops up, but I explicitply checked to install it, using the network installer.

### Steps to reproduce the issue

![grafik](https://user-images.githubusercontent.com/99172156/152752858-65389078-e0a6-45ed-95c6-92e0b42c732e.png)

## Report Details

**QGIS Info**
QGIS Version: 3.16.16-Hannover
QGIS code revision: f5778a89
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.1
Running against GDAL: 3.4.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
This looks like an issue with some plugin, QGIS itself does not use matplotlib. The issue should be reported to plugin authors.
