### ISSUE TITLE
UI miss alignement in terrain shading

### ISSUE THREAD

**Issue by nicogodet** [qgis/QGIS#47227]
### What is the bug or the crash?

![image](https://user-images.githubusercontent.com/39594821/152796695-5a7f94b4-c7a7-46e3-9310-22f482a4c5f4.png)

### Steps to reproduce the issue

Trivial

### Versions

3.22.3

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
This fix is pretty simple, I can take care of it.
I just wonder if there is any tests along with this UI ?

**Comment by nyalldawson** [comment]
@nicogodet no need to worry about tests for this -- change away!
