### ISSUE TITLE
QGIS will crash when testing connection to Oracle

### ISSUE THREAD

**Issue by nomad5000** [qgis/QGIS#47225]
### What is the bug or the crash?

When testing a connection to an oracle database, Qgis crashes.

### Steps to reproduce the issue

1. right click the Oracle buton in the browser
2. select new connection
3. then click tes connection without filling in anything.

4. Then it crashes.

### Versions

Qgis LTR 3.16
This happens with setup on MAC OS

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
> Qgis LTR 3.16

@nomad5000 3.16 is EOL and will not receive any new bug fix. You must test on 3.22.3, with a new QGIS profile (settings > user profiles > new profile).

**Comment by gioman** [comment]
Nevermind, I tested on 3.22.3 on macOS 12 and I confirm. Does not happen on Windows.

**Comment by ahojjat** [comment]
I`m having the same issue on Mac, any solution?

**Comment by morganb240** [comment]
@nomad5000 @ahojjat any solution?

**Comment by nomad5000** [comment]
Use Windows

**Comment by mattca** [comment]
Also confirmed here on 3.26.3-Buenos Aires. I tried with new QGIS profile to no avail.

**Comment by troopa81** [comment]
Fixed by #53201
