### ISSUE TITLE
DWG importer usability issues

### ISSUE THREAD

**Issue by roya0045** [qgis/QGIS#47230]
### What is the bug or the crash?

I'm not sure if this should be a bug or a feature request, or many small bugs/UX issues.

1. The destination GPKG must be selected first.
2. The destination must already exist, it cannot be created in the dialog
3. It might or might not work without any apparent reason  (Error: Could Not Open Layer List), even with the same dataset that was ok moments ago.
4. Setting the CRS doesn't seem useful as it gets overwrote( or I just didn't get to change it the one time it worked)
5. The source pth cannot be changed and the separator are always unix style
6. The process starts right away when the two layers are 'valid'
7. You need to specific a group to contain all the other groups for the export in the project.

### Steps to reproduce the issue

1. Project
2. Import/Export
3. Import Layers from DWG/DXF

### Versions

Old 3.19 could retry with something recent at some point.

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
> The destination GPKG must be selected first.

@roya0045 yes, what do you suggest here?



> The destination must already exist, it cannot be created in the dialog

When importing? no, the dialog creates the target gpkg if does not exist,




> It might or might not work without any apparent reason (Error: Could Not Open Layer List), even with the same dataset that was ok moments ago.

Can you post a sample?

> The process starts right away when the two layers are 'valid'

what do you mean?

> You need to specific a group to contain all the other groups for the export in the project.

yes, because importing a dwg/dxf can result in very large number of layers being added to the project, having them grouped is not only handy, is basically mandatory.

**Comment by roya0045** [comment]
> @roya0045 yes, what do you suggest here?
> 
Selecting the dwg to import first, and then set the destination (in and then out, not the opposite)
> When importing? no, the dialog creates the target gpkg if does not exist,
You're right you can create a new one, with an existing one if created from the browser it sometimes just doesn't work.
> Can you post a sample?
I think the main issue comes from using an already existing geopackage sometimes. It should be replicable with sample dwg, the gpkg seems the be the main blocker not the dwg source. (tested also with a sample from https://knowledge.autodesk.com/support/autocad/downloads/caas/downloads/content/autocad-sample-files.html)
> what do you mean?
There is no way to 'start' the process. If you are not doing this locally and across a vpn it can brick QGIS for 10 mins and this doesn't allow you to change the crs once the IN and OUT are set, you are forced to do it after the destination is set but before loading the source, or you'll have to start again.
> yes, because importing a dwg/dxf can result in very large number of layers being added to the project, having them grouped is not only handy, is basically mandatory.
It can but they are already grouped individually. It doesn't make sense to force a single 'layer' to be nested into two groups. The user should have the choice to export them under a single group or not, like for any batch import.

**Comment by gioman** [comment]
> Selecting the dwg to import first, and then set the destination (in and then out, not the opposite)

@roya0045 good for a feature request I guess.



> I think the main issue comes from using an already existing geopackage sometimes. It should be replicable with sample dwg, the gpkg seems the be the main blocker not the dwg source. (tested also with a sample from https://knowledge.autodesk.com/support/autocad/downloads/caas/downloads/content/autocad-sample-files.html)

so what are the steps to replicate?




> There is no way to 'start' the process. If you are not doing this locally and across a vpn it can brick QGIS for 10 mins and this doesn't allow you to change the crs once the IN and OUT are set, you are forced to do it after the destination is set but before loading the source, or you'll have to start again.

I don't understand, Once QGIS hsa finished parsing the DWG and the user filled the "group name" then the OK" button become active, and must be pressed manually. Or are you referring the the parsing process itself, that starts when the DWG is selected? If is the latter then what would be the suggestion? Add a "parse" DWG button? I guess that would also be good for a feature request.




> It can but they are already grouped individually. It doesn't make sense to force a single 'layer' to be nested into two groups. The user should have the choice to export them under a single group or not, like for any batch import.

maybe another feature request?

**Comment by roya0045** [comment]
> @roya0045 good for a feature request I guess.

Sure, though the whole thing would need a lift to fit the QGIS way, the goal of this was just to have a ticket for that widget. I don't mind converting this to a single FR to modernize the widget with the listed elements as outstanding.

> so what are the steps to replicate?

1. In the browser create a gpkg (you can remove or leave the layer you are forced to create)
2. In the dwg importer set the new gpkg as the destination
3.  load a dwg to import
4. Error

> I don't understand, Once QGIS hsa finished parsing the DWG and the user filled the "group name" then the OK" button become active, and must be pressed manually. Or are you referring the the parsing process itself, that starts when the DWG is selected? If is the latter then what would be the suggestion? Add a "parse" DWG button? I guess that would also be good for a feature request.

The ok only imports the data selected, everything is written to the destination gpkg regardless if you add it to the project or not. Even if you hit Cancel, everything is in the geopackage now.

Also selecting a single element from the list can lead to importing nothing and just creating an empty group (the one blocking you from creating ok), that only happens if the 'layer' imported is not a geospatial layer (I have no clue how a dwg can lead to have so many table dataset but that's out of scope).

> maybe another feature request?

Fair

**Comment by roya0045** [comment]
![dwg_importer_reowrk](https://user-images.githubusercontent.com/12854129/154870479-70a73489-7f0a-42fe-9141-77bf6954b73f.gif)
Here is a demo of the reworked widget with most fixes addressed. Using the sublayer dialog allow to group if needed or just import all. Gpkg are reusable (didn't check for the integrity of other layers though). Importing can be done by hitting OK or Import. UI is more intuitive.

**Comment by gioman** [comment]
> Here is a demo of the reworked widget with most fixes addressed. Using the sublayer dialog allow to group if needed or just import all. Gpkg are reusable (didn't check for the integrity of other layers though). Importing can be done by hitting OK or Import. UI is more intuitive.

nice!
