### ISSUE TITLE
QGIS unexpectedly ended when you load wfs

### ISSUE THREAD

**Issue by geodourados** [qgis/QGIS#47231]
### What is the bug or the crash?

Crash ID: [fba85e11445e9e3f0e20d5d4dd482137df1c4f8d](https://github.com/qgis/QGIS/search?q=fba85e11445e9e3f0e20d5d4dd482137df1c4f8d&type=Issues)

Stack Trace

QMetaObject::cast :
PyInit__core :
PyArg_ParseTuple_SizeT :
PyEval_EvalFrameDefault :
PyFunction_Vectorcall :
PyFloat_FromDouble :
PyVectorcall_Call :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QObject::qt_static_metacall :
QItemSelectionModel::setCurrentIndex :
QAbstractItemView::setCurrentIndex :
QgisApp::autoSelectAddedLayer :
QgisApp::identifyMapTool :
QObject::qt_static_metacall :
QgsLayerTreeRegistryBridge::addedLayersToLayerTree :
QgsLayerTreeRegistryBridge::layersAdded :
QObject::qt_static_metacall :
QgsProject::legendLayersAdded :
QgsProject::addMapLayers :
QgsProject::addMapLayer :
QgsMeshSelectByExpressionDialog::zoomToSelected :
QgisApp::addVectorLayer :
QgisApp::qt_static_metacall :
QObject::qt_static_metacall :
QgsDataSourceManagerDialog::addVectorLayer :
QgsDataSourceManagerDialog::addProviderDialog :
QObject::qt_static_metacall :
QgsAbstractDataSourceWidget::addVectorLayer :
providerGuiMetadataFactory :
QObject::qt_static_metacall :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
QgisApp::dataSourceManager :
QgisApp::identifyMapTool :
QObject::qt_static_metacall :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.22.3-Bia?owie?a
QGIS code revision: 1628765ec7
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.1
Running against GDAL: 3.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22000

### Steps to reproduce the issue

https://geodourados.dourados.ms.gov.br/geoserver/dourados/wfs

### Versions

Versão do QGIS
3.22.3-Białowieża
Código da versão do QGIS
1628765ec7
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
Compilado sobre GEOS
3.10.0-CAPI-1.16.0
Rodando sobre GEOS
3.10.2-CAPI-1.16.0
Compilado no SQLite
3.35.2
Executando contra SQLite
3.37.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
Add_a_point_road_sign
1.0.1
AnotherDXF2Shape
1.2.3
autonumbering
0.2
autoSaver
2.4
AzimuthDistanceCalculator
2.0.2
AzimuthMeasurement
0.2.2
BackupLayer
0.3
batchvectorlayersaver
0.9
bulkvectorexportwithstyle
0.6
Cadastral_Divisions-main
1.0
CalcArea
1.3.0
cbers4a
0.3.1
citygen
0.3
ConstraintChecker
1.2
db-style-manager
0.8
db_style_reloader
0.3
dimensioning
0.2
DsgTools
4.2.0
EasyCustomLabeling
2.1
excel_sync
3.6
FastVersion
3.4.0
FragScape
2.0.6
FreehandRasterGeoreferencer
0.8.3
geometric_attributes
0.3
gisquick-qgis-plugin
2.0.1
go2streetview
8.3
GroupStats
2.2.5
group_transparency
0.2
HCMGIS
21.8.28
ImageServerConnector
2.1.1
inde
1.1
instantprint
3.0.0
InvisibleLayersAndGroups
2.1
itemmap_cropper
0.1
LAStools
1.4
lizmap
3.6.3
lrs
1.2.1
mapbiomas-api
0.3.1
mapbiomasalert
1.2
mapbiomascollection
1.3
MapsPrinter
0.8
mapswipetool_plugin
1.2
MBTiles2img
0.4
MemoryLayerSaver
4.0.4
menu_from_project
v2.0.1
minkowskiDimCalculator
2.0
mmqgis
2021.9.10
moving_feature
2.0
multilayerselect
1.4.1
MultiMaps
1.1
nominatim
1.4.1
numericalDigitize
0.4.6
openlayers_plugin
2.0.0
ORStools
1.4.0
osgb-plugin
0.1
OSMDownloader
1.0.3
ParallelLineConstruction
0.2
planet_explorer
2.1.1
pluginbuilder3
3.2.1
polygonclickmap
0.7
postgisQueryBuilder
2.0.1
powerpan
2.0
qfieldsync
v4.0.0-beta16
qgis-maptiler-plugin
2.0.0
qgis2web
3.16.0
QGISSortAndNumber-master
1.0
QGIS_Dashboard-master
0.1
qgis_versioning
1.0
qgsAzimuth
0.9.15
QNeighborhood
0.1.1
qNote
2.2
QRectangleCreator
0.3
QTRANUS
1.0.2
QuickMultiAttributeEdit3
version 3.0.3
QuickOSM
2.0.0
QuickPrint
3.6.1
quick_map_services
0.19.26
QVisualize
0.5
QWater
3.1.8
QWeather
3.2.1
QWeb
0.2.1
realcentroid
1.0.3
refFunctions
1.6
report
1.0.0
searchlayers
3.0.4
SelectByRelationship
0.3.2
SelectWithin
0.4
send2google_earth
0.3.1
SentinelHub
2.0.0
slyr_community
3.1.0
splitmultipart
1.0.0
SplitPolygon-master
1.2
SpreadsheetLayers
2.0.1
SRTM-Downloader
3.1.15
StandardDistance
1.0.1
StreetView
3.2
Submission
0.6
SuperLabeling
ver.1.4
SwapVectorDirection
0.9
table2style
2.1
timemanager
3.4
toggleactivelayer_plugin
1.3
togglegroupvisibility
0.3
TurnGray
3.0.0
unique_values_viewer
0.2
usgs_stream_mapper
0.2
valuetool
3.0.15
VectorFieldCalc
1.5.4
web2qgis
0.2.0
workbench
0.0.4
xyToPoint
2.0
XYZHubConnector
1.8.10
zoomview
1.1.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
@geodourados you checked that you have tested with a new QGIS profile, but clearly did not. Please do it. If the problem persist, then add more details, as the detailed steps to follow that lead to the crash.
