### ISSUE TITLE
GDAL Raster Calculator writing files correctly but logging overwrite errors

### ISSUE THREAD

**Issue by ar-siddiqui** [qgis/QGIS#47233]
### What is the bug or the crash?

When using the GDAL raster calculator and overwriting the output file, this is what is happening in different QGIS and different use cases.
In 3.22.2 `--overwrite` argument is passed to GDAL and not in 3.16.5.
GDAL has successfully processed and written data despite messages in 3.16.5 but not in 3.22.2.
Note: sometimes you have to refresh the map to see changes. 

Case | 3.16.5 | 3.22.2
-- | -- | --
Output file not loaded in canvas but exist | ERROR 1:   C:\\Users\\asiddiqui\\Desktop\\plugin_test\\Runoff Local.tif, band 1: Write   operation not permitted on dataset opened in read-only mode 0.. Block writing failed | No Error   Message
Output file loaded in canvas | ERROR   1: C:\\Users\\asiddiqui\\Desktop\\plugin_test\\Runoff Local.tif, band 1:   Write operation not permitted on dataset opened in read-only mode 0.. Block writing failed | [WinError   32] The process cannot access the file because it is being used by another   process: 'C:\\\\Users\\\\asiddiqui\\\\Desktop\\\\plugin_test8\\\\Runoff Local.tif'     Process returned error code 0

### Steps to reproduce the issue

Overwrite a file using the GDAL raster calculator.

### Versions

QGIS version: 3.22.2-Białowieża
QGIS code revision: 1601ec46d0
Qt version: 5.15.2
Python version: 3.9.5
GDAL version: 3.4.0
GEOS version: 3.10.0-CAPI-1.16.0
PROJ version: Rel. 8.2.0, November 1st, 2021
PDAL version: 2.3.0 (git-version: 9f35b7)

QGIS version: 3.16.15-Hannover
QGIS code revision: e7fdad64
Qt version: 5.15.2
GDAL version: 3.4.0
GEOS version: 3.10.0-CAPI-1.16.0
PROJ version: Rel. 8.2.0, November 1st, 2021

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

This might be related to work on #42447

**Comment by gioman** [comment]
> [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\asiddiqui\\Desktop\\plugin_test8\\Runoff Local.tif' Process returned error code 0

@ar-siddiqui this is very expected on Windows. Another example, you generated a PDF and have it opened in a PDF reader, of you try to overwrite it you'll get a similar error message, regardless of the software you are using. A different story is Linux. Anyway this has nothing to do with the "overwrite" option, that works as expected (also on Windows) unless your data source is opened somewhere... like in QGIS.

**Comment by ar-siddiqui** [comment]
I did more testing and update the original issue post.

I see your point but when we get a similar error in windows for PDF, it doesn't write the file and fail the command. Here multiple mixed things are happening, files are being written successfully in 3.16.5 despite messages.

But when --overwrite is passed in 3.22.2 it is failing on most occasions (it is writing successfully sometimes when you call it as part of another larger algorithm)

I think this needs to be consistent with other QGIS procedures which overwrite the files after warnings.

**Comment by ar-siddiqui** [comment]
> > But when --overwrite is passed in 3.22.2 it is failing on most occasions
> 
> @ar-siddiqui even when the existing raster is not opened in QGIS or other program?
@gioman only when it is open in QGIS, but that's an issue since a lot of the time you would have datasets open in QGIS.

**Comment by gioman** [comment]
> @gioman only when it is open in QGIS, but that's an issue since a lot of the time you would have datasets open in QGIS.

@ar-siddiqui but then I argue that the message you are getting now is totally expected. Not sure why before it was different.

**Comment by ar-siddiqui** [comment]
Agree, it is weird behaviour, with `--overwrite` flag GDAL is raising errors and failing. Without it, it is logging error but not failing. See below I tested outside QGIS to confirm the behaviour.

For the following test file was open in QGIS.
![image](https://user-images.githubusercontent.com/53625184/153031530-51018bb2-0f76-4179-bd86-7027ea0fc1b2.png)

**Comment by gioman** [comment]
> Agree, it is weird behaviour, with `--overwrite` flag GDAL is raising errors and failing. Without it, it is logging error but not failing. See below I tested outside QGIS to confirm the behaviour.

maybe then you may want to ask in the gdal list/tracker(?).

**Comment by ar-siddiqui** [comment]
Ok yes, but should QGIS
- revert back the addition of the `--overwrite` flag that happened sometime after 3.16.5, till GDAL fixes the issue?
- implement a check that if the file is already loaded in Canvas a QGIS and then do something about it. This is to make the behaviour consistent with other QGIS algorithms where even if a file is loaded in QGIS (which is the case most often) still QGIS is able to overwrite it. This would still need to happen even if the GDAL issue is fixed?

**Comment by gioman** [comment]
> revert back the addition of the `--overwrite` flag that happened sometime after 3.16.5, till GDAL fixes the issue?

@ar-siddiqui this was added on purpose

https://github.com/qgis/QGIS/commit/bf9efccff26f8df1691681038dca4ed4c47a1353#diff-9b9ea5b26c42204c8f88ba4336e298b6ef198ab2f0ce62a8e23ac91c55c6c197

you may want to raise a question in that PR.

**Comment by ar-siddiqui** [comment]
Ok, so an issue has been filed with GDAL https://github.com/OSGeo/gdal/issues/5270

Another thing to find out is what is the source of the error messages for 3.16.5.

I run the same command on GDAL and did not get those error messages returned by QGIS

![image](https://user-images.githubusercontent.com/53625184/153276307-ea045311-66c9-4e21-a671-df15c26fdfd1.png)

![image](https://user-images.githubusercontent.com/53625184/153276332-f82c5190-4baf-4546-91a2-ab25c2bef54b.png)

**Comment by ar-siddiqui** [comment]
@gioman 

GDAL has made it clear through this commit that passing `--overwrite` flag explicitly is what is causing the issue.
https://github.com/rouault/gdal/commit/477c9301b97bb4f7fab3d517f301ac59e1fe2eab

I suggest QGIS should not pass `--overwrite` flag all the time but only when explicit creation is desired because passing `--overwrite` explicitly means we will always fail the process if the file is opened in QGIS (which is most often the case).

On the other hand, if this flag is not passed, GDAL will still update (different than overwrite) when it can open. 

The problem with passing the flag is that if a user doesn't want to pass `--overwrite` for any reason, there is no way to remove that, but one can always pass the `--overwrite` additionally if one wants to.

**Comment by gioman** [comment]
@nicogodet hi, can you remember why the --overwrite parameter was added here https://github.com/qgis/QGIS/commit/bf9efccff26f8df1691681038dca4ed4c47a1353#diff-9b9ea5b26c42204c8f88ba4336e298b6ef198ab2f0ce62a8e23ac91c55c6c197 ?

**Comment by nicogodet** [comment]
Because in case we try to output to an existing file, dialog asks if we want to overwrite the file but the option was not passed to gdal command.

If I remember well, I had issues with clip raster with mask layer and I raised a GH issue that was fixed by the commit you mentioned. But I didn't tried to output to an existing file that's loaded in QGIS.

**Comment by nicogodet** [comment]
For gdal calc only ?
