### ISSUE TITLE
unexpectedly end

### ISSUE THREAD

**Issue by gf-champlain** [qgis/QGIS#47253]
## User Feedback

unknow 

inconnue !

## Report Details

**Crash ID**: [940da8b284a337381d7ed4d5c81af46c33039af2](https://github.com/qgis/QGIS/search?q=940da8b284a337381d7ed4d5c81af46c33039af2&type=Issues)

**Stack Trace**
<pre>
QMimeType::staticMetaObject :
QgsMapCanvas::cancelJobs :
QgsMapCanvas::~QgsMapCanvas :
QgsPluginRegistry::operator= :
QgisApp::~QgisApp :
QgsPluginRegistry::operator= :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.22.3-Bia?owie?a
QGIS code revision: 1628765ec7
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.1
Running against GDAL: 3.4.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Steps to reproduce the issue

?

### Versions

22.3

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@gf-champlain fill the ticket with all the requested infos, not before trying with a new QGIS profile, if the problem persist then reopen.
