### ISSUE TITLE
Plugins and web connection error on newly installed 3.16 

### ISSUE THREAD

**Issue by MatanGolan** [qgis/QGIS#47255]
### What is the bug or the crash?

Hi
I have just installed the 3.16 on a computer which earlier versions (deleted) were installed on. 
 I recieve this message. No plugins appear. 

### Steps to reproduce the issue

2022-02-08T17:59:37     INFO    Application state:
             QGIS_PREFIX_PATH env var: C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr
             Prefix: C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr
             Plugin Path: C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/plugins
             Package Data Path: C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/.
             Active Theme Name: default
             Active Theme Path: C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./resources/themes\default\icons/
             Default Theme Path: :/images/themes/default/
             SVG Search Paths: C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./svg/
              C:/Users/Matan Golan/AppData/Roaming/QGIS/QGIS3\profiles\Matan Golan/svg/
             User DB Path: C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./resources/qgis.db
             Auth DB Path: C:/Users/Matan Golan/AppData/Roaming/QGIS/QGIS3\profiles\Matan Golan/qgis-auth.db
             
2022-02-08T18:00:33     WARNING    HTTP fetch https://feed.qgis.org/?lang=en failed with error Operation canceled
2022-02-08T18:00:33     WARNING    News feed request failed [error: Operation canceled]

2022-02-08T17:59:33     WARNING    Failed to load C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/plugins/grassplugin7.dll (Reason: Cannot load library C:\PROGRA~1\QGIS3~1.16\apps\qgis-ltr\plugins\grassplugin7.dll: The specified module could not be found.)
2022-02-08T17:59:33     WARNING    Failed to load C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/plugins/grassprovider7.dll (Reason: Cannot load library C:\PROGRA~1\QGIS3~1.16\apps\qgis-ltr\plugins\grassprovider7.dll: The specified module could not be found.)
2022-02-08T17:59:33     WARNING    Failed to load C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/plugins/grassrasterprovider7.dll (Reason: Cannot load library C:\PROGRA~1\QGIS3~1.16\apps\qgis-ltr\plugins\grassrasterprovider7.dll: The specified module could not be found.)
2022-02-08T17:59:33     INFO    Loaded DB Manager (package: db_manager)
2022-02-08T17:59:34     INFO    Loaded MetaSearch Catalog Client (package: MetaSearch)
2022-02-08T17:59:37     INFO    Loaded Processing (package: processing)

### Versions

QGIS version
3.16.16-Hannover
QGIS code revision
f5778a89df
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
db_manager; 
MetaSearch; 
processing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
@MatanGolan you probably have some messed up installation folder. Do a cleanup, uninstall QGIS, remove leftover folders, remove the QGIS3 folders in your Windows user folder. The re-install.

**Comment by MatanGolan** [comment]
> @MatanGolan you probably have some messed up installation folder. Do a cleanup, uninstall QGIS, remove leftover folders, remove the QGIS3 folders in your Windows user folder. The re-install.

Hi Gioman
I did what you suggested, and downloaded the set up again (note - on the download page their are two links for the 3.16 stand alone 64 bit, the second installer weights 400Mb. Now I've downloaded the one above it - 1Gb. Wierd). 

Any way, I've installed the new one, changed the user name from dafault - But the plugins still do not show. 
Name: QGIS Official Plugin Repository
URL: https://plugins.qgis.org/plugins/plugins.xml
parameters : ?qgis=3.16

Any new ideas?

**Comment by gioman** [comment]
> Now I've downloaded the one above it - 1Gb. Wierd).

@MatanGolan it is a complete new package/installer, based on more recent dependencies



> Any new ideas?

no, but you clearly have local issues, is not  general QGIS bug.

**Comment by MatanGolan** [comment]
> 
> no, but you clearly have local issues, is not general QGIS bug.

I think it's something webby - as even the XYZ tile>OpenStreetMap is not uploading. (CRS is correct in the project).
Any idea what can cause this? is their any logging from the QGIS to a browser to detect what is the problem?

I',m clueless. And need it for work.

**Comment by agiudiceandrea** [comment]
@MatanGolan can you connect to any XYZ or OGC Web service (WMS/WFS/WCS) using QGIS?
If not, probably your system is behind a proxy. In this case you have to properly set the proxy connection details in QGIS.

**Comment by MatanGolan** [comment]
> @MatanGolan can you connect to any XYZ or OGC Web service (WMS/WFS/WCS) using QGIS? If not, probably your system is behind a proxy. In this case you have to properly set the proxy connection details in QGIS.

@agiudiceandrea thank you. no, I cannot. Can you please send me a link to a tutorial or other explanation about setting the proxy connection?

**Comment by agiudiceandrea** [comment]
@MatanGolan please read the user manual: https://docs.qgis.org/3.22/en/docs/user_manual/introduction/qgis_configuration.html#network-settings
