### ISSUE TITLE
Wrong raster representation for layer styling "Mean +/- standard deviation" 

### ISSUE THREAD

**Issue by tschmetzer** [qgis/QGIS#47273]
### What is the bug or the crash?

For layer styling "Mean +/- standard deviation" the representation is wrong. Lower bounds are missing. The graphical representation should make use of the whole range of the color ramp and Min/Max boundaries.
Note: Min is automatically set to negative values. No idea if this is right or wrong.
![image](https://user-images.githubusercontent.com/67278094/153205105-e9f32d9a-4aa5-4a03-a140-f4931605d567.png)

I am no statistics expert but setting the lower boundary to 0 right after choosing the "Mean +- standard deviation" seems to produce reasonable results:
![image](https://user-images.githubusercontent.com/67278094/153205694-aedd0f69-9c76-4393-acf9-55a86a09f89d.png)

For Layerstyling min/max the representation is correct:
![image](https://user-images.githubusercontent.com/67278094/153203065-7e73fb5b-f008-4fad-afa6-ef7cddfc1985.png

The TIF's properties:
![image](https://user-images.githubusercontent.com/67278094/153207157-cea7de21-37aa-41b6-9a5d-79c21c2ca2f9.png)

### Steps to reproduce the issue

1. Unzip [raster_stddev_bug.compressed.tif.zip](https://github.com/qgis/QGIS/files/8032938/raster_stddev_bug.compressed.tif.zip) and load TIF into QGIS
2. Choose Layer styling "singleband pseudocolor"
3. Expand Min/Max value settings
4. Choose Mean +/- standard deviation

### Versions

QGIS version
3.22.3-Białowieża
QGIS code revision
1628765ec7
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
Compiled against GEOS
3.10.0-CAPI-1.16.0
Running against GEOS
3.10.2-CAPI-1.16.0
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
[...]

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by roya0045** [comment]
Min is set to MEAN - ( 2*st_dev) in your example. The negative values are expected even if outside of the values present in the raster they are present within the selected st_dev range. I don't think this is a bug and clapping this to 0 will not work with raster that have negative values.

**Comment by tschmetzer** [comment]
Alright, negative values for Min make totally sense then. Why are these negative values not represented graphically?

**Comment by gioman** [comment]
> Why are these negative values not represented graphically? Looks like a clear bug to me.

@tschmetzer because the raster has no such values?

**Comment by tschmetzer** [comment]
Exactly. The raser has no negative values. The Min...Max bandwith has been adjusted to the range -14258,9941017...37201,1529593 by the "Mean+/- stddev" option. The Min and the Max value of the color ramp seem to have been adjusted accordingly. 
By selecting the "Mean+/- stddev" option I was expecting the full range of the color ramp to be used. Isn't this the idea of this function? This function seems to work on the pure pixel values and doesn't adapt its upper and lower boundaries to the actual raster Min..Max range.

**Comment by gioman** [comment]
> . Isn't this the idea of this function?

@tschmetzer good question. Personally what I don't expect is to see represented pixels values/colors for pixels that do not exist in the raster. So the symbology makes sense to me, but really don't know why that method extends the min values and what is expected from that.

**Comment by tschmetzer** [comment]
My best guess would be that the algorithm just does its work without any further consideration of boundaries
