### ISSUE TITLE
Can't open postgrest geojson service

### ISSUE THREAD

**Issue by sigeal** [qgis/QGIS#47280]
### Feature description

I have a PostgreSql stored procedure which returns a geojson feature collection created with json_build_object function. This web service opens fine in OpenLayers, however, when I try to open it in QGIS, with data source manager -> vector -> protocol -> geojson : 
![addgeojson](https://user-images.githubusercontent.com/247591/153418104-5a611cb2-ad4d-4c5b-ac87-0c08be006c9e.png)

I get the following error :
> Invalid data source: [myurl]/rpc/wod_geojson is not a valid or recognized data source.

This is the query wrapped in a plpgsql function called my_geojson :
`SELECT json_build_object(
    'type', 'FeatureCollection',
    'features', json_agg(
        json_build_object(
            'type', 'Feature',
            'id', id,
            'geometry', ST_AsGeoJSON(ST_Transform(geometry, 4326))::json,
            'properties', json_build_object(
                'lib', lib
            )
        )
    )
)::json my_geojson FROM (SELECT ROW_NUMBER() OVER() id, * FROM mytable) tmp`

This is the url I use to call the service:
`http://mydomain:3000/rpc/my_geojson`

I tested a similar geojson REST service served with pg_featureserv, and it works fine...

### Additional context

Server Environment :
    PostgreSQL version: 10.19
    PostgREST version: 9.0.0
    Operating system: Ubuntu 16.04

Client Environment :
    QGIS version: 3.16.16
    Operating system: Windows 10

**Comment by gioman** [comment]
> QGIS version: 3.16.16



@sigeal try on 3.22.3, as 3.16 is EOL.   

anyway, is this a bug report or a feature request?

**Comment by sigeal** [comment]
Same problem with QGIS 3.22.3
It's more a question than a feature request, as I don't know if it's a PostGrest or a QGIS problem.
What does QGIS check to declare a service invalid ? Can it be a http header problem ?
Here is headers I have when I check the service in a browser :
`Content-Range   0-0/*
Content-Type    application/geo+json
Date    Wed, 09 Feb 2022 11:02:26 GMT
Server  postgrest/9.0.0
Transfer-Encoding   chunked
Vary    Accept-Encoding`

**Comment by gioman** [comment]
> It's more a question

@sigeal questions should be directed in the users or developers mailing lists.

**Comment by sigeal** [comment]
Done. Thank you for your comment and sorry for the noise

**Comment by gioman** [comment]
@sigeal do you have new infos?

**Comment by sigeal** [comment]
Further testing, I discovered that I can open my postgrest geojson service using Python :
```
myLayer= QgsVectorLayer('http://mydomain:3000/rpc/wod_geojson, 'myLayer', 'ogr')
QgsProject.instance().addMapLayers([myLayer])
```

**Comment by sigeal** [comment]
Also, testing with ogrinfo on command line, it fails with 404 error , but adding `Accept: application/json` header makes it work.

**Comment by alexbruy** [comment]
@sigeal so it is a matter of adding correct headers so that GDAL can correctly handle responce, right? In that case should we close this?
