### ISSUE TITLE
QGIS Project is empty

### ISSUE THREAD

**Issue by ulfboge** [qgis/QGIS#47287]
### What is the bug or the crash?

When working in a project that has been saved frequently, an error message pops up saying something in line with that the "zip function doesn't work and the project won't save. The next time I start QGIS and the project, the project file is empty.

### Steps to reproduce the issue

Click the save button.

### Versions

QGIS version
3.22.3-Białowieża

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by roya0045** [comment]
More details will be needed, was there many people working on the project at the time or other things that could cause a lock at some point?

**Comment by gioman** [comment]
> “Python error: Couldn't load plugin 'LDMP' due to an error when calling its classFactory() method See message log (Python Error) for more details.”

@ulfboge this is a 3rd party plugin. Please test your scenario using a new QGIS profile

settings > user profiles > new profile

**Comment by ulfboge** [comment]
Thank you @gioman! That fixed that error message.

**Comment by gioman** [comment]
Reopen if/when you have a clear way to replicate the problem reported in the original description.
