### ISSUE TITLE
COGs stop rendering after being added

### ISSUE THREAD

**Issue by Samweli** [qgis/QGIS#47293]
### What is the bug or the crash?

When adding COGs in QGIS as map layers, QGIS stops rendering them after sometime later.

### Steps to reproduce the issue

1. Open QGIS Data Source manager.
2. Go to Raster source provider, select Protocol:HTTPS or cloud for source type
3. Add https://naipeuwest.blob.core.windows.net/naip/v002/fl/2019/fl_60cm_2019/27080/m_2708063_sw_17_060_20191215.tif and https://naipeuwest.blob.core.windows.net/naip/v002/fl/2019/fl_60cm_2019/28080/m_2808060_sw_17_060_20191215.tif as COGs.
4. Keep repeating adding the COGs, at somepoint QGIS stops rendering the layers and shows a blank map
5. See one of the errors occured
![cog_layer_error](https://user-images.githubusercontent.com/2663775/153497222-d393ce86-8ba6-43b8-aba8-14769b856c2f.png)

### Versions

QGIS 3.22

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
> Keep repeating adding the COGs, at somepoint QGIS stops rendering the layers and shows a blank map

@Samweli how many times? I have added both tens of times and can't replicate.
