### ISSUE TITLE
Pretty Breaks don't respect the number of classes

### ISSUE THREAD

**Issue by roya0045** [qgis/QGIS#47290]
### What is the bug or the crash?

I'm not sure if this is a bug or if using the classification 'Pretty Break' should use the number of classes as a suggestion or if the classficiation should be made more flexible to fit more strictly the number of classes.

Other wise this can lead to cases where you get 7 classes when you specify anything between 6 and 12 classes, requesting 2 classes gives 3,  requesting 3 to 5 gives 5 classes, 1 gives 1 (at least).

### Steps to reproduce the issue

Use pretty Breaks in graduate styling with data that has a low value range.

### Versions

Tested on 3.19 master, behaviour should have change since then, will test on fresh master when possible.

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by pjshelton** [comment]
I disagree that this is a bug.  I am not sure of the exact algorithm that QGIS uses, but if it follows other programs (like R statistics), Pretty breaks tick marks last non zero char is one of 1,2, or 5.
For small ranges and small class numbers there can be cases where no sequence of numbers has the exact requested number of bins

**Comment by pjshelton** [comment]
This is still an open question.
