### ISSUE TITLE
QGIS won't start at MacOS Big Sur version 11.5.1

### ISSUE THREAD

**Issue by BartJutte** [qgis/QGIS#47294]
### What is the bug or the crash?

“QGIS-LTR” can’t be opened because Apple cannot check it for malicious software. The software needs to be updated.

The above error message occurs after installation of QGIS-LTR version 3.16 and QGIS version 3.22. It looks like Apple has tightened its security which blocks opening the program itself. It does install itself on the Mac with both downloaded versions.

### Steps to reproduce the issue

1. Download QGIS on Mac that runs OS Big Sur
2. Install QGIS (move icon to install)
3. Open programme from apps section
4. See error message “QGIS-LTR” can’t be opened because Apple cannot check it for malicious software.

### Versions

not possible to make a screenshot. QGIS-LTR version 3.16 and QGIS version 3.22

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@BartJutte, have you read the advice on the [download page](https://qgis.org/en/site/forusers/download.html) of the QGIS Web site?

> QGIS is not yet notarized as required by macOS Catalina (10.15) security rules. On first launch, please right-click on the QGIS app icon, hold down the Option key, then choose Open.

![image](https://user-images.githubusercontent.com/16253859/153502124-05bae6dc-d9a4-4fee-b7c7-a0ecd977b804.png)
