### ISSUE TITLE
QgsProcessingParameterFile extension option

### ISSUE THREAD

**Issue by tsw-apropos** [qgis/QGIS#47304]
### What is the bug or the crash?

As noted in issue #45633 which the author closed incorrectly, it is not possible to select files and have them passed into the function if the files do not have extensions. On Linux machines, a supported platform binary files DO NOT HAVE EXTENSIONS.

This means that although the fileFilter parameter can be set to '*' and the file can be selected, it won't be passed to the function, but instead an error will be raised 'Wrong or missing parameter value'.

The author stated when closing #45633 that "In latest QGIS versions if no extension is set, a default file filter will be used." This IS THE PROBLEM. An option needs to exist to allow no extension to be set so that plugin developers who want their users to work outside the world of Windows with binary files can do so.

### Steps to reproduce the issue

See above

### Versions

3.2

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
Duplicates #45633
