### ISSUE TITLE
QGIS is not loading KMZ files with a rotation correctly

### ISSUE THREAD

**Issue by bblasjo** [qgis/QGIS#47308]
### What is the bug or the crash?

I have several supplied KMZ files that contain geo-referenced PDFs and if the PDFs are oriented with north being up they load into QGIS correctly, but if north is not up they load correctly to the location, but they are not correctly rotated.

### Steps to reproduce the issue

Drag and drop a KMZ with geo-referenced rotated PDF in it into QGIS, it will load to the correct location but the rotation is not honered.

The files I have are propitiatory, so I am unable to post the actual files or screen prints without getting permission first. But I was able to load an existing KMZ with geo-referenced rotated PDF in it into Google Earth, rotate it, and save it. Then re-load that into GE and the rotation is still there, but when I load the same file into QGIS the rotation is ignored. So that should help in replicating the issue.

### Versions

QGIS version
3.22.0-Białowieża
QGIS code revision
d9022691f1
Qt version
5.15.2
Python version
3.9.5
Compiled against GDAL/OGR
3.3.2
Running against GDAL/OGR
3.3.3
PROJ version
8.1.1
EPSG Registry database version
v10.038 (2021-10-21)
GEOS version
3.10.0-CAPI-1.16.0
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
geoscience
1.5
HCMGIS
21.8.28
kmltools
3.1.15
mmqgis
2021.9.10
quick_map_services
0.19.26
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Since these same KMZs load correctly in Google Earth I was not sure if the problem was a mal-formed KMZ or that QGIS wasn’t handling rotated KMZs correctly.

But recently, I gained access to Esri’s ArcGIS On-Line and discovered the same KMZs load correctly there as well, indicating the problem is not with the KMZs but with how QGIS handles KMZs that have a rotation.

I tried using the ‘KML Tools’ plug-in as a work around, but that plug-in appears to only handle vector data.

I have also tried to search QGIS’ support page as well as the internet for KMZ rotation issues, but was unable to find anything pertinent.

The files I have are propitiatory, so I am unable to post the actual files or screen prints without getting permission first. but I was able to load a KMZ into Google Earth, rotate it, and save it. Then re-load that into GE and the rotation is still there, but when I load the same file into QGIS the rotation is ignored.

Can someone please replicate my issue to see if this is really a bug in QGIS or not?

I would like to see the problem fixed so I can continue using QGIS and not have to buy an Esri license to work with these files (I am assuming Desktop and/or Pro handle it properly).

**Comment by gioman** [comment]
> Drag and drop a KMZ with geo-referenced rotated PDF in it into QGIS, it will load to the correct location but the rotation is not honered.

@bblasjo attach a sample, thanks.

**Comment by bblasjo** [comment]
OK, I think I created a non-propitiatory KMZ that demonstrates the issue.

To create a non-rotated KMZ I:
-took a snapshot of the I10/I215 interchange in San Bernardino, CA and washed it out in a paint program so it will contrast with the background satellite image and saved it as "I10_I215interchange.png"
-created an "image overlay" in GoogleEarth that references this PNG and entered the extent of this image
-exported it as a KMZ called "I10_I215interchange.kmz" (attached)

To create the rotated KMZ I:
-took the washed out .png file and rotated it 90 degrees (left) in the same paint program and saved it as "I10_I215interchange-rotated90.png"
-created a new "image overlay" in GoogleEarth that references this new PNG and used the same extents as above for this image (I know since this image is not perfectly square doing this will distort it somewhat but that is not what is at issue) AND set a 90 degrees rotation in the opposite (right) direction
-exported it as a KMZ called "I10_I215interchange_rotated90.kmz" (also attached)

To demonstrate the problem:
If you load these two images into Google Earth they both load properly (the interchange is mostly symmetrical but there is a cloverleaf transition ramp and surface roads in the NE corner of the interchange that are unique) 

Now load those same two KMZ files into QGIS by dragging and dropping the files into QGIS and you will see that "I10_I215interchange.kmz" file load correctly (as it should), but while the "I10_I215interchange_rotated90.kmz" file loads in the correct location it is rotated 90 degrees to the left. Thus demonstrating  that QGIS does not honor the rotating setting in a KMZ file and indicating my discovery of a probable bug in QGIS.

Please let me know if there is anything else I need to supply
[Rotated KMZ demo files.zip](https://github.com/qgis/QGIS/files/8051758/Rotated.KMZ.demo.files.zip)

**Comment by bblasjo** [comment]
Your comment, while it does point out where the problem lies, does not help me resolve the problem I am having.

I have reported a problem I am having trying to do something with your software and the only response I get is a short message pointing to, what I am assuming is, a sub-module and say the problem lies with it with no information on how to get it resolved, is unhelpful to me as the user. What am I supposed to do with this information, find who created GDAL_TRANSLATE and report the bug to them myself?

I reported a problem I am having with your QGIS software, and if the problem lies in a sub-module that you are utilizing, you have the knowledge, expertise and (I feel) responsibility to report the bug to whomever is supporting the sub-module you are utilizing.

Let me know if I can further help in supplying information to you, but I feel that reporting this problem to the proper entity lies squarely in QGIS' court.

If my understanding of the situation ins incorrect please give more information as to why.

**Comment by gioman** [comment]
> If my understanding of the situation ins incorrect please give more information as to why.

@bblasjo just a couple of notes here. There is no "you" in Open Source, only "we" and that includes you to. So QGIS is yours software too. Also, is pretty normal to not re-invent the wheel all the time so as in many other projects, QGIS makes use of a few underlying geospatial libraries/packages, most notably GDAL, PROJ and GEOS. We don't fork them, we use the upstream releases, so if by bad luck one release of those libraries is affected by a bug and we use that release in QGIS, we are affected too.



> What am I supposed to do with this information, find who created GDAL_TRANSLATE and report the bug to them myself?

Short answer, yes, I think that you should report/inquiry GDAL (a library to read/write a large amount of raster and vector formats) about this problem, because it seems (I'm not 100% sure) that the problem is there, specifically in the KML driver https://gdal.org/drivers/vector/kml.html (that then is used by QGIS).

https://github.com/OSGeo/gdal/issues
