### ISSUE TITLE
QGIS 3.22 vs MacBook Pro 2019/Monteray

### ISSUE THREAD

**Issue by goranbengtsson** [qgis/QGIS#47317]
### What is the bug or the crash?

Hi. I'm experiencing issues with QGIS 3.22 on my Macbook Pro (16 ince, 2019) and Monteray. The checkpoints I put out in the Georeference window end up in the wrong place at random. In addition, zoom does not work properly. Anyone else experiencing the same problem? 
<img width="481" alt="qgis1" src="https://user-images.githubusercontent.com/84369114/153702019-411eb5dc-c747-456e-9528-d0063523bbaa.png">
<img width="613" alt="qgis2" src="https://user-images.githubusercontent.com/84369114/153702028-a3ee483c-abdb-4310-ba78-d90dc7a1604e.png">
<img width="844" alt="qgis3" src="https://user-images.githubusercontent.com/84369114/153702033-387c82dc-711e-4527-a55e-0aa2348836b6.png">

### Steps to reproduce the issue

<img width="481" alt="qgis1" src="https://user-images.githubusercontent.com/84369114/153702075-46497c44-461c-40c0-99ef-485d906e1cb5.png">
<img width="613" alt="qgis2" src="https://user-images.githubusercontent.com/84369114/153702079-b3e2d030-8ecd-4038-85a5-b23234b1c638.png">
<img width="844" alt="qgis3" src="https://user-images.githubusercontent.com/84369114/153702080-fa640b6e-be9c-4ba3-983d-9d41deccce70.png">

### Versions

QGIS 3.22

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@goranbengtsson same as https://github.com/qgis/QGIS/issues/47213 and https://github.com/qgis/QGIS/issues/46882 ?

**Comment by goranbengtsson** [comment]
Not quite sure but it seems to be the same problem. Is there any solution to this problem? Any update in 3.22?
Br
Göran Bengtsson


På 12 februari 2022 kl. 09:58:29, Giovanni Manghi ***@***.***) skrev:

@goranbengtsson same as #47213 and #46882 ?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gioman** [comment]
> Any update in 3.22?

@goranbengtsson use 3.16, wait for 3.24, see also https://github.com/qgis/QGIS/issues/47212#issuecomment-1036057885

**Comment by goranbengtsson** [comment]
Thank’s!
/göran

Skickat från min iPhone
