### ISSUE TITLE
Qgis crashes after push node tool

### ISSUE THREAD

**Issue by LeFagnard** [qgis/QGIS#47312]
### What is the bug or the crash?

Every time I activate the node tool on a shape layer, the program returns an error, either it closes itself or it gives me the error encoding screen to send you.
All the work done until then is lost.

### Steps to reproduce the issue

Click on a shape layer
Click on Switch to edit mode button  OR Click on Add a linear entity
Click on node button button
see error

## Report Details

**Crash ID**: [b70efe43e6d4f61355b2eb44e347d935aaf1c95f](https://github.com/qgis/QGIS/search?q=b70efe43e6d4f61355b2eb44e347d935aaf1c95f&type=Issues)

**Stack Trace**
<pre>
QVariant::~QVariant :
QgsExpressionNode::prepare qgsexpressionnode.cpp:38
QgsExpressionNodeFunction::prepareNode qgsexpressionnodeimpl.cpp:1017
QgsExpressionNodeIndexOperator::prepareNode qgsexpressionnodeimpl.cpp:1686
QgsExpressionNodeBinaryOperator::prepareNode qgsexpressionnodeimpl.cpp:681
QgsRuleBasedRenderer::Rule::startRender qgsrulebasedrenderer.cpp:426
QgsRuleBasedRenderer::Rule::startRender qgsrulebasedrenderer.cpp:436
QgsRuleBasedRenderer::Rule::startRender qgsrulebasedrenderer.cpp:436
QgsRuleBasedRenderer::Rule::startRender qgsrulebasedrenderer.cpp:436
QgsRuleBasedRenderer::startRender qgsrulebasedrenderer.cpp:961
QgsPointLocator::rebuildIndex qgspointlocator.cpp:942
QgsPointLocatorInitTask::run qgspointlocatorinittask.cpp:34
QgsTask::start qgstaskmanager.cpp:81
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.16.13-Hannover
QGIS code revision: a8618a94
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.0
Running against GDAL: 3.4.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

## Report Details

**Crash ID**: [0d11022e80281a9f4c3f571544c932b9055d09e0](https://github.com/qgis/QGIS/search?q=0d11022e80281a9f4c3f571544c932b9055d09e0&type=Issues)

**Stack Trace**
<pre>
QXmlStreamStringRef::~QXmlStreamStringRef :
QgsRuleBasedRenderer::Rule::startRender qgsrulebasedrenderer.cpp:505
QgsRuleBasedRenderer::startRender qgsrulebasedrenderer.cpp:961
QgsPointLocator::rebuildIndex qgspointlocator.cpp:942
QgsPointLocatorInitTask::run qgspointlocatorinittask.cpp:34
QgsTask::start qgstaskmanager.cpp:81
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.16.13-Hannover
QGIS code revision: a8618a94
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.0
Running against GDAL: 3.4.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

### Versions

3.6.13-Hannover
but I tryed to install 3.16.16, finishes well but after restart, version 3.16.13 is always there. No trace of the update.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

**Comment by gioman** [comment]
@LeFagnard you must test on 3.22.3, as 3.16 is EOL. Also you must test on a new QGIS profile

settings > user profiles > new profile

with no 3rd party plugins installed.

If the problem persist then list the detailed steps to follow that are lading to the crash, attaching sample project/data if necessary.

**Comment by LeFagnard** [comment]
Same error in 3.22.3, but program closes without possibility to enter error message in new window.
Can not attach project. The files and maps are on a server.

Steps as above (translated from a french version of QGis):
Click on a shape layer
Click on Switch to edit mode button OR Click on Add a linear entity
Click on node button button

**Comment by gioman** [comment]
> Can not attach project. The files and maps are on a server.
> 
> Steps as above (translated from a french version of QGis): Click on a shape layer Click on Switch to edit mode button OR Click on Add a linear entity Click on node button button

@LeFagnard it is the crash/project dependent? there are still too few infos/data here to allow us troubleshoot this,

**Comment by roya0045** [comment]
If you can share the project with some sample data and the layer with the rulle-based renderer settings. As this seems to be where the crash occurs.
