### ISSUE TITLE
QGIS 3.22 closes when exiting internal window

### ISSUE THREAD

**Issue by CitySelby** [qgis/QGIS#47314]
### What is the bug or the crash?

Hi,

This bug occurs with and without plugins in Fedora 34, I tried fully removing and reinstalling to see if that fixed it but no dice. Whenever I click the 'x' to close an internal window, including in 'New [any] Layer', 'Save as', and the attribute panel, the program will stall for a few seconds before simply closing wholesale or giving an error:not-responding popup that prompts me to either wait or force-close. Regardless of which option is picked, the program closes with no apparent crash report that I can find as a non-proficient Linux user.

### Steps to reproduce the issue

1. Open any project
2. Go to 'Add Layer: New Vector Layer', 'View Attribute Table', or any option that gives an internal window
3. Click the 'x' at the top right to close the window
4. See program stall and possibly give 'not-responding' error before closing

### Versions

</head><body>

QGIS version | 3.22.3-Białowieża | QGIS code branch | Release 3.22
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.9
GDAL/OGR version | 3.2.2
PROJ version | 7.2.1
EPSG Registry database version | v10.008 (2020-12-16)
GEOS version | 3.9.0-CAPI-1.16.2
SQLite version | 3.34.1
PDAL version | 2.2.0
PostgreSQL client version | 13.4
SpatiaLite version | 5.0.1
QWT version | 6.1.5
QScintilla2 version | 2.11.5
OS version | Fedora 34 (Workstation Edition)
QGIS code branch | [Release 3.22](https://github.com/qgis/QGIS/tree/release-3_22)
Qt version | 5.15.2
Python version | 3.9.9
GDAL/OGR version | 3.2.2
PROJ version | 7.2.1
EPSG Registry database version | v10.008 (2020-12-16)
GEOS version | 3.9.0-CAPI-1.16.2
SQLite version | 3.34.1
PDAL version | 2.2.0
PostgreSQL client version | 13.4
SpatiaLite version | 5.0.1
QWT version | 6.1.5
QScintilla2 version | 2.11.5
OS version | Fedora 34 (Workstation Edition)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
> with and without plugins

@CitySelby but have you really tried with a new QGIS profile?

settings > user profiles > new profile

**Comment by CitySelby** [comment]
> > with and without plugins
> 
> @CitySelby but have you really tried with a new QGIS profile?
> 
> settings > user profiles > new profile

I did, made a second one that was only different by name, still had the same problem.

**Comment by gioman** [comment]
> I did, made a second one that was only different by name, still had the same problem.

@CitySelby how did you installed on Fedora?

**Comment by CitySelby** [comment]
> @CitySelby how did you installed on Fedora?

Standard terminal command, 'sudo dnf install qgis'.

Previously I had installed the version including Grass but never used it, and was having the issues in that program environment first; remove was same version as install, I thought it might've been an issue stemming from something during an upgrade which is why I tried a fresh install.

**Comment by gioman** [comment]
I don't have a Fedora machine at hand, @timlinux @nyalldawson any tip on how troubleshoot this?

**Comment by CitySelby** [comment]
> I don't have a Fedora machine at hand, @timlinux @nyalldawson any tip on how troubleshoot this?

At this point would it be easier to switch to a different distro? I'm replacing my laptop soon and was thinking about trying something different, in school for planning/GIS. I'm assuming Ubuntu might have better/easier support?

**Comment by gioman** [comment]
> At this point would it be easier to switch to a different distro?

@CitySelby Fedora is well supported, if fact some prominent QGIS dev uses it. It seems more like you are hitting some local issue.
