### ISSUE TITLE
Possible incorrect proj definition for EPSG:6527 New Jersy State plane feet NAD83(2011)

### ISSUE THREAD

**Issue by newcomb-d** [qgis/QGIS#47310]
### What is the bug or the crash?

A geotiff image created in EPSG:6527 New Jersy State plane feet NAD83(2011) had a severe offset when viewing in a third party commercial GIS.  Examination of the QGIS proj4 definition
Proj4
+proj=tmerc +lat_0=38.8333333333333 +lon_0=-74.5 +k=0.9999 +x_0=150000 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=us-ft +

But If you go further up in the definition, you see this X offset:

PARAMETER["False easting",492125,
            LENGTHUNIT["US survey foot",0.304800609601219],
            ID["EPSG",8806]],

There is a   similar x offset with the WKT and  proj4 definition in epsg.io.

If I reproject the image using the gdalwarp utility in QGIS to a meters -based projection ( EPSG:5070) , the third party software sees the image in the correct location.

how does an x offset go from 492125 to 150000 ?  Why does it offset in a y direction.  I admit my knowledge of projections is limited.

 

### Steps to reproduce the issue

Go to 75.1078356°W 39.2610910°N 
Set projection to EPSG:6527
Digitize the boundary of the lake as a polygon
rasterize the polygon to a 100ft pixel size as a geotiff file.
Open the raster layer in ArcGIS.
The raster layer will be ~ 36km south of where it should be

### Versions

QGIS 3.22.3 proj 8.21

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
> Digitize the boundary of the lake as a polygon

@newcomb-d can you just attach here this vector? thanks.



> Open the raster layer in ArcGIS.

Most of us do not have access to that software. Something else more accessible we can use to compare?

**Comment by newcomb-d** [comment]
Well, if it's a proj issue, then current open source software using the same proj library will probably be affected as well.


________________________________
From: Giovanni Manghi ***@***.***>
Sent: Friday, February 11, 2022 6:52 PM
To: qgis/QGIS ***@***.***>
Cc: Newcomb, Doug ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [qgis/QGIS] Possible incorrect proj definition for EPSG:6527 New Jersy State plane feet NAD83(2011) (Issue #47310)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Digitize the boundary of the lake as a polygon

@newcomb-d<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnewcomb-d&data=04%7C01%7Cdoug_newcomb%40fws.gov%7Cc1c1d344238d4350bf8708d9edb98daa%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637802203469011795%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=gRCehMX2i275aMjEEVC29C7BMD5%2Fhfih0rM9H%2BIBvN0%3D&reserved=0> can you just attach here this vector? thanks.

Open the raster layer in ArcGIS.

Most of us do not have access to that software. Something else more accessible we can use to compare?

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fqgis%2FQGIS%2Fissues%2F47310%23issuecomment-1036792117&data=04%7C01%7Cdoug_newcomb%40fws.gov%7Cc1c1d344238d4350bf8708d9edb98daa%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637802203469011795%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=3YyBkgw6XjQSfjeboM8VJhi7shvtDma8dG6Eis1H9CM%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABSYN7TS4MKBP44RGWLHXZDU2WOKRANCNFSM5OFJNR3Q&data=04%7C01%7Cdoug_newcomb%40fws.gov%7Cc1c1d344238d4350bf8708d9edb98daa%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637802203469011795%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=CBcZEImw28VTnwqZvc6JfEnu5Lej6eKgRKYfUI417rc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cdoug_newcomb%40fws.gov%7Cc1c1d344238d4350bf8708d9edb98daa%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637802203469011795%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=BMH22iG2hF76tk0ts6Z6CI%2F7K7Dbl0p7KAmdh5Di%2BGg%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cdoug_newcomb%40fws.gov%7Cc1c1d344238d4350bf8708d9edb98daa%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637802203469011795%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=KQUpyTkQ3j9Hk1ID8d084j%2BDk1dSoFwEoDP0jsakctY%3D&reserved=0>.

**Comment by gioman** [comment]
> Well, if it's a proj issue, then current open source software using the same proj library will probably be affected as well.

@newcomb-d you have not added the polygon, if you sent it by attaching to your email reply it won't work, you must use the GitHub web interface.
