### ISSUE TITLE
Setting page margins for SVG map export in QGIS Print Composer

### ISSUE THREAD

**Issue by dukytony** [qgis/QGIS#47328]
### Feature description

is there a way to setup the print composer so that when you export your map to SVG it cuts everything that's out of the page margins?

Everytime I export my map to SVG (my page is 240x180mm), when i open it with Inkscape, there are polygons and lines that are drawn out of the page limits.

**Comment by troopa81** [comment]
Which version of QGIS are you using? I manage to make the clipping (cutting everything outside the map extent) work with master. 

Could you share a project sample ?

**Comment by gioman** [comment]
> is there a way to setup the print composer so that when you export your map to SVG it cuts everything that's out of the page margins?

@dukytony please ask questions on the users or developers mailing list. If then you are sure that is a missing feature, file the request here.

**Comment by dukytony** [comment]
Hi, I'm using QGIS 3.22.2.

I can't really share this data unfortunately but this would be easily reproduced. it's just a gpkg with polygons.

Any tips on how to cut everything outside the map extent?

Thanks a lot for your help!

**Comment by gioman** [comment]
> but this would be easily reproduced. it's just a gpkg with polygons.

@dukytony then please put together a sample project with some random data that can be used to try replicate the problem.

**Comment by dukytony** [comment]
Hello!

So I made a very simple dataset.

you will find the project and gpkg file

You will find the svg export result (with polygons drawn outside the page margins) and some screenshot of the print composer and result in inkscape.

there you go : https://www.grosfichiers.com/9eFVx4YHj7e_pjX2cye7eK8

Thanks a lot for all your help guys!

Have a nice day!

**Comment by gioman** [comment]
> there you go : https://www.grosfichiers.com/9eFVx4YHj7e_pjX2cye7eK8

@dukytony this is the result here on master, with the "crop to content" option active

![test](https://user-images.githubusercontent.com/1951107/154475104-8da378e6-f339-4733-b812-c8c3d053faa9.svg)

**Comment by dukytony** [comment]
This is the result i get when "crop to content" is activated in inkscape. (the black background is set in inkscape).




![image](https://user-images.githubusercontent.com/96209495/154482188-d319405c-d885-48ed-a776-b8d83cf17cc7.png)

**Comment by dukytony** [comment]
am I doing something wrong?

**Comment by gioman** [comment]
> am I doing something wrong?

@dukytony nothing, any software -except inkscape- where I opened the resulting SVG show it cropped as expected.

**Comment by gioman** [comment]
maybe this configures as bug? @troopa81 ?

**Comment by troopa81** [comment]
I assume you choose to export in SVG, not in PDF. If so, the issue comes from Qt (the framework we use for widgets and map rendering) which doesn't support fully the SVG standard. See https://doc.qt.io/qt-5/svgrendering.html: *only the static portion of the SVG Tiny 1.2 profile is supported.* This doesn't include clip-path, used to crop content. 

I tried to export in PDF with QGIS master, and then imported the result in Inkscape and it works well.

**Comment by dukytony** [comment]
Yeah I export to SVG because the goal is to be able to edit the map afterwards in Inkscape.
So if I export to pdf and open in it inkscape, It rasterizes the polygons and i cant edit them.
The only method that's working is to draw a rectangle in the print composer and use the crop parameters of the map to use the rectangle as canvas for cropping. Then the exported svg in cropped right. I wonder why this is working and not the "crop to content" thing.

A "crop top page" for svg export would surely be a very usefull feature request I think.

Thanks a lot for all your hard work guys!

**Comment by troopa81** [comment]
> So if I export to pdf and open in it inkscape, It rasterizes the polygons and i cant edit them.

Not if you check the option *Always export as vectors* in the PDF export dialog. You can then import the PDF file in Inkscape and edit what you want. 

> The only method that's working is to draw a rectangle in the print composer and use the crop parameters of the map to use the rectangle as canvas for cropping.

You mean this way ?

![clip](https://user-images.githubusercontent.com/14358135/154959453-05ad7fc0-ca32-4676-8511-b1c43e4215de.png)

I tried to export this configuration and it didn't clip in SVG. I'm curious of what parameters you set to make it work

**Comment by dukytony** [comment]
okay for pdf exporting

it works if you set clip before rendering

**Comment by troopa81** [comment]
OK, Indeed, it clips the geometry before the rendering and so there is no use of Qt::ClipPath, and so it works.
