### ISSUE TITLE
Add a method to pyqgis to set group as an active node in layer tree

### ISSUE THREAD

**Issue by ar-siddiqui** [qgis/QGIS#47337]
### Feature description

Currently, there is a way to set a map layer as active layer programmatically `iface.setActiveLayer()` but there is no equivalent way of setting a group as an active node. There is this answer on SE 

https://gis.stackexchange.com/a/383321/142232

But this doesn't work if your group is a nested group.

This feature is useful if you are writing processing scripts that add layers to the currently selected node.

**Comment by gacarrillor** [comment]
Thanks for reporting, fixed by https://github.com/qgis/QGIS/pull/59045
