### ISSUE TITLE
WMS provider Cannot calculate extent error adding a WMTS layer from QGIS server

### ISSUE THREAD

**Issue by endmax** [qgis/QGIS#47349]
### What is the bug or the crash?

When I try to add a WMTS layer in QGIS DESKTOP from QGIS WMS/WMTS server  I get the following error:
 

`  CRITICAL    Invalid Layer : WMS provider Cannot calculate extent
             Raster layer Provider is not valid (provider: wms, URI: contextualWMSLegend=0&crs=EPSG:25832&dpiMode=7&featureCount=10&format=image/png&layers=Sistema_Ambientale&styles=default&tileMatrixSet=EPSG:25832&url=http://172.20.14.68/cgi-bin/qgis_mapserv.fcgi?MAP%3DPROJECTS%2Fgeodbapp07%2FSfruz%2F61%2FPrgDigTemplate.qgs%26SERVICE%3DWMTS%26VERSION%3D1.3.0%26REQUEST%3DGetCapabilities`

Looking at WMTS capabilities the bounding box is wrong.

```
<ows:WGS84BoundingBox>
   <ows:LowerCorner>11.106366 46.320153</ows:LowerCorner>
   <ows:UpperCorner>inf inf</ows:UpperCorner>
</ows:WGS84BoundingBox>
<ows:BoundingBox crs="EPSG:25832">
   <ows:LowerCorner>-505646.9 0</ows:LowerCorner>
   <ows:UpperCorner>-505646.899 0</ows:UpperCorner>
</ows:BoundingBox>
```

### Steps to reproduce the issue

Use the attached project with corresponding data file and publish it to a QGIS Server.
Then add a WMTS layer pointing to that server project.
[PrgDigTemplateMinimal.zip](https://github.com/qgis/QGIS/files/8062260/PrgDigTemplateMinimal.zip)

### Versions

QGIS version
3.16.13-Hannover
QGIS code revision
a8618a941b
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows Server 2016 (10.0)
Active python plugins
PluginLoadTimes; 
plugin_reloader; 
prg_dig; 
sipaf_gis; 
db_manager

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@endmax should not be everything in 3857 (I think is mandatory for WMTS, but not 100% sure)? If you use it

![image](https://user-images.githubusercontent.com/1951107/154022082-0a99fe4d-cbfb-4251-b7ed-4b3088d6cac1.png)

![image](https://user-images.githubusercontent.com/1951107/154022343-d0335f77-9304-4d29-9909-60c201ffc7cf.png)

**Comment by endmax** [comment]
@gioman  bounding box in WMTS capabilities is wrong because there are layers with no data. 
In my project there are layers with no data that are bounded to empty spatialite tables. They have a wrong bounding box.
If a group layer contains such a layer it's bounding box is also worng and WMTS does not run as expected in CRS 25832.
I've no idea why 3857 runs well and if it is the only CRS that it is possible to use (maybe only with QGIS ?).
Removing empty layers solves the problem BUT it is not the right way to go because I need all my layers and I don't know in advice if they will be empty at the moment I'm going to publish my project to QGIS server.
As a temporary work around I can use 3857 but I think this is a bug.

Furthermore using the following tile matrix the result is not ovelapped with the vector source:
Top = 5136991.00
Left = 659150.00
MinScale = 1000000.00
LastLevel = 18
![image](https://user-images.githubusercontent.com/2227603/154287120-75ee90d1-6478-4082-b1df-7c730659cf6f.png)

**Comment by gioman** [comment]
I'll leave to some QGIS Server developer to comment further.

**Comment by endmax** [comment]
Anybody could take a look?
thank you

**Comment by endmax** [comment]
> I'll leave to some QGIS Server developer to comment further.

Hi @gioman 
I think I could debug this bug but I've no time to setup a development evironment. Is there around a docker container with  QGIS with a development environment ready to use ?

**Comment by gioman** [comment]
https://hub.docker.com/r/qgis/qgis

**Comment by endmax** [comment]
> https://hub.docker.com/r/qgis/qgis

@gioman sorry I was thinking about a VM vith a complete developing environment to debug QGIS server (IDE, c++ compiler, linker etc...)  The right question is about a VM image and not a docker image.

**Comment by elpaso** [comment]
@endmax I did an attempt a few years ago but it's unmaintaned: https://github.com/elpaso/qgis-dev-vagrant

**Comment by elpaso** [comment]
I cannot reproduce this issue using your test project.
