### ISSUE TITLE
Unable to load min/max values when defining a line interpolated rendering, in style manager

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#47346]
### What is the bug or the crash?

When creating a line symbol in the style manager, using the interpolated renderer, the load min/max values based on the start and end values button does not work with custom values. 

### Steps to reproduce the issue

1. From the style manager, create a line layer
2. Select the interpolated line symbol
3. Turn the width and color options into varying mode
4. Enter values for start value and end values (for width and/or color)
5. Press the load button. The corresponding min and max value fields are supposed to be filled but in this case, the fields are (made) empty
6. Same process while symbolizing a layer: min/max are filled with entered start and end values

https://user-images.githubusercontent.com/7983394/153894552-4c49bb28-2781-4a41-8984-11dbbd9f0ebe.mp4

.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.1-Białowieża | QGIS code branch | Release 3.22
-- | -- | -- | --
Qt version | 5.12.8
Python version | 3.8.10
GDAL/OGR version | 3.0.4
PROJ version | 6.3.1
EPSG Registry database version | v9.8.6 (2020-01-22)
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
SQLite version | 3.31.1
PostgreSQL client version | 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.2
OS version | Ubuntu 20.04.3 LTS
  |   |   |  
Active Python plugins
trackable_project_files | v1.2.2
MapsPrinter | 0.9
MemoryLayerSaver | 4.0.4
db_manager | 0.1.20
processing | 2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
Works fine in the latest master (94b62accf2a1cfc892bc9097cd4dd5f8a1f60ab0).
