### ISSUE TITLE
Raster Calculator crashes working on Google Earth Satellite image

### ISSUE THREAD

**Issue by Pachuquero** [qgis/QGIS#47350]
### What is the bug or the crash?

Crash ID: [f741c96ff4808a439c79e70a77f9d114630b0d87](https://github.com/qgis/QGIS/search?q=f741c96ff4808a439c79e70a77f9d114630b0d87&type=Issues)

Stack Trace

QgsRasterCalculator::processCalculation :
QgisApp::showRasterCalculator :
QObject::qt_static_metacall :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QMenu::metaObject :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

### Steps to reproduce the issue

I was using Raster Calculator (RC) on a Google Earth Satellite image part which I was displaying with Band Rendering R 0-174, G 0-174, B 0-183 and Contrast Enhancement 'Stretch to MinMax'. 

![dopus_2022-02-14_11-00-37](https://user-images.githubusercontent.com/5184994/153910706-20cb2a6f-ac4b-4e20-9539-fb0f97584f28.png)

In RC I selected the same and added Band 4 > 183. The aim was to eliminate raster lighter values that did not correspond to woody vegetation in the image.

![dwm_2022-02-14_11-02-24](https://user-images.githubusercontent.com/5184994/153911188-c1b4a83f-2536-4de1-a577-c4a950e64c68.png)

Screen cap just before hitting Enter...

![Raster Calculator crash](https://user-images.githubusercontent.com/5184994/153911584-9c7005d7-3817-4e32-bb02-5a6d917abe20.jpg)

### Versions

QGIS Info
QGIS Version: 3.22.3-Bia?owie?a
QGIS code revision: 1628765ec7
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.1
Running against GDAL: 3.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by Pachuquero** [comment]
Instead of the duplicated image this one should have been included...

**Comment by gioman** [comment]
@Pachuquero try on a new QGIS profile, no 3rd party plugins installed.

If the problem persist then link/attach a sample project with data, and post the formula you are using.
