### ISSUE TITLE
R.resamp.interp

### ISSUE THREAD

**Issue by AdriZacarias97** [qgis/QGIS#47355]
### What is the bug or the crash?

ERROR 6: C:\Users\tst\AppData\Local\Temp\processing_ScLhNv\6997694c65d54801bb9994fafe7beb30\output.tif, band 1: SetColorTable() only supported for Byte or UInt16 bands in TIFF formatERROR 6: C:\Users\tst\AppData\Local\Temp\processing_ScLhNv\6997694c65d54801bb9994fafe7beb30\output.tif, band 1: SetColorTable() only supported for Byte or UInt16 bands in TIFF format

### Steps to reproduce the issue

Al intentar interpolarizar datos raster, me da ese error.
Los datos del raster están en formato Archivo TIF.

### Versions

Versión de QGIS
3.22.3-Białowieża
Revisión del código de QGIS
1628765ec7
Versión Qt
5.15.2
Versión de Python
3.9.5
Versión de GDAL/OGR
3.4.1
Versión de PROJ
8.2.1
Versión del registro de base de datos EPSG
v10.041 (2021-12-03)
Versión GEOS
3.10.0-CAPI-1.16.0
Versión de SQLite
3.35.2
Versión de PDAL
2.3.0
Versión del cliente de PostgreSQL
13.0
Versión de SpatiaLite
5.0.1
Versión de QWT
6.1.3
Versión de QScintilla2
2.11.5
Versión del SO
Windows 10 Version 2009

Complementos activos de Python
quick_map_services
0.19.26
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

al intentar realizar la Media del NDVI, no me carga la capa de salida que fue realizada a partir de los datos raster anteriormente mencionados. 
Espero que la información sirva, no soy entendida de la parte informática

**Comment by alexbruy** [comment]
The error message is self-explanatory, you should use Byte or UInt16 data type for your output file. Also this is not a QGIS issue, as the same message you will get when running GRASS directly.

**Comment by AdriZacarias97** [comment]
muchas gracias, veré la forma de cambiar el tipo de datos y de comunicar este problema a la gente que me suministró los datos ráster

**Comment by DejfCold** [comment]
@alexbruy the error is self-explanatory, but how is this not qgis issue when qgis doesn't have an option to set this parameter? Maybe it's there somewhere hidden or I'm just stupid, but then it's not a functional problem but a UX one.

![image](https://user-images.githubusercontent.com/12591578/158071160-16d3280a-0709-4588-a119-e1269cf8ebe4.png)

QGIS 3.24.0-Tisler
