### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by marinebiss** [qgis/QGIS#47356]
### What is the bug or the crash?

Crash ID: [3801195e1301e40a0c57fe421378dcfb82a7ed1c](https://github.com/qgis/QGIS/search?q=3801195e1301e40a0c57fe421378dcfb82a7ed1c&type=Issues)

Stack Trace

QgsProcessingDxfLayersWidget::setProject :
QgsEmbeddedSymbolRendererWidget::setContext :
QgsRendererPropertiesDialog::setContext :
QgsLayerStylingWidget::updateCurrentWidgetLayer :
QObject::qt_static_metacall :
QListWidgetItem::`default constructor closure' :
QObject::qt_static_metacall :
QItemSelectionModel::setCurrentIndex :
QListWidget::setCurrentRow :
QgsLayerStylingWidget::setLayer :
QObject::qt_static_metacall :
QgsMapLayerComboBox::layerChanged :
QObject::qt_static_metacall :
QAbstractItemModel::endInsertRows :
QSortFilterProxyModel::insertRows :
QSortFilterProxyModel::sortRoleChanged :
QSortFilterProxyModel::qt_static_metacall :
QObject::qt_static_metacall :
QAbstractItemModel::endInsertRows :
QgsMapLayerModel::addLayers :
QObject::qt_static_metacall :
QgsProject::layersAdded :
QObject::qt_static_metacall :
QgsMapLayerStore::layersAdded :
QgsMapLayerStore::addMapLayers :
QgsProject::addMapLayers :
QgsProject::addLayer :
QgsProject::_getMapLayers :
QgsProject::readProjectFile :
QgsProject::unzip :
QgsProject::read :
QgisApp::addProject :
QgisApp::openProject :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.20.3-Odense
QGIS code revision: 495fbaec
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.1

### Steps to reproduce the issue

When opening my project

### Versions

QGIS 3.20

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
Please, provide more details and attach sample data.

**Comment by gioman** [comment]
> QGIS 3.20

@marinebiss too old and unsupported. Whatever you are doing try first on 3.22.3 on a new QGIS profile:

settings > user profiles > new profile

**Comment by gioman** [comment]
@marinebiss Also please use meaningful titles.
