### ISSUE TITLE
When Browser Window is open QGIS runs extremely slow

### ISSUE THREAD

**Issue by StubMandrel** [qgis/QGIS#47369]
### What is the bug or the crash?

The browser window saps so many system resources it virtually halts QGIS when switching between functions. Bearing in mind there is no requirement for the browser window to be self-updating regularly this is mysterious behaviour.

The real bug is that you can only find this out bys searching for reasons why QGIS runs so badly. Thjere really ought to be a standard message that pops up when you open the browser window:

"WARNING the browser window is a major system resource hog, always close it when not actively using it".

### Steps to reproduce the issue

1. Open browser window
2. Try to do something useful
3. Get frustrated and bored doing things like wait two minutes to be able to enter an ID and Name after creating a new polygon.
4. Close browser window.
5. Work normally.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.18.2-Zürich | QGIS code revision | 515138c171
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | db_manager; MetaSearch; processing

</body></html>QGIS version
3.18.2-Zürich
QGIS code revision
[515138c171](https://github.com/qgis/QGIS/commit/515138c171)
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
db_manager; 
MetaSearch; 
processing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

It's well known that creating a new profile doesn't solve this.

**Comment by gioman** [comment]
> 3.18.2-Zürich

@StubMandrel fixed in supported / recent versions. 3.18 is too old and unsupported, update to 3.22.3
