### ISSUE TITLE
QGIS crashed when trying to use $uuid

### ISSUE THREAD

**Issue by rodreras** [qgis/QGIS#47374]
### What is the bug or the crash?

I'm trying to use `$uuid` function to update a column in my point layer, but whenever I write it down, QGIS crashes.

I tried with different types for the column, tried in a geopackage layer and a scratch layer. All of them crashed. 

### Steps to reproduce the issue

1. Create a Scratch Layer, or use one from your geopackage
2. Create a new column with the name of your desire
3. Go to the field calculator
4. Choose the option `update existing field` and select the column name from 2
5. type `$uuid`
6. QGIS will crash.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.3-Białowieża | QGIS code revision | 1628765ec7
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.7
GDAL/OGR version | 3.2.2
PROJ version | 7.2.1
EPSG Registry database version | v10.008 (2020-12-16)
GEOS version | 3.9.0-CAPI-1.16.2
SQLite version | 3.35.5
PDAL version | 2.2.0
PostgreSQL client version | 13.5 (Ubuntu 13.5-0ubuntu0.21.10.1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Pop!_OS 21.10
  |   |   |  
Active Python plugins
SRTM-Downloader | 3.1.15
qfieldsync | v3.4.4
inde | 1.1
qgis_resource_sharing | 0.16.0
qProf | 0.4.4
Qgis2threejs | 2.6
ana_data_acquisition | 1.0
lftools | 1.4.1
ee_plugin | 0.0.4
quick_map_services | 0.19.27
mapbiomascollection | 1.4
geoscience | 1.5
SentinelHub | 2.0.0
db_manager | 0.1.20
sagaprovider | 2.12.99
MetaSearch | 0.3.5
grassprovider | 2.12.99
processing | 2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

This won't compromise my workflow, but I think it's such a weird bug. I hope you guys can verify it!

**Comment by gioman** [comment]
> Active Python plugins 			
> SRTM-Downloader 	3.1.15 		
> qfieldsync 	v3.4.4 		
> inde 	1.1 		
> qgis_resource_sharing 	0.16.0 		
> qProf 	0.4.4 		
> Qgis2threejs 	2.6 		
> ana_data_acquisition 	1.0 		
> lftools 	1.4.1 		
> ee_plugin 	0.0.4 		
> quick_map_services 	0.19.27 		
> mapbiomascollection 	1.4 		
> geoscience 	1.5 		
> SentinelHub 	2.0.0 		
> db_manager 	0.1.20 		
> sagaprovider 	2.12.99 		
> MetaSearch 	0.3.5 		
> grassprovider 	2.12.99 		
> processing 	2.12.99

@rodreras you must test on a new QGIS profile with no 3rd party plugins installed. If the problem persist add steps and data to allow us try replicate.

**Comment by rodreras** [comment]
I tried with another profile and still crashed. You can check the profile information below.

I'm also uploading the zipfile with my geopackage inside. The layer I was trying to perform this operation is named `coleta_pontos_campo`, and the field is `uuid`
[geopackage.zip](https://github.com/qgis/QGIS/files/8073663/geopackage.zip)

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>


Versão do QGIS | 3.22.3-Białowieża | Código da versão do QGIS | 1628765ec7
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.7
GDAL/OGR version | 3.2.2
PROJ version | 7.2.1
EPSG Registry database version | v10.008 (2020-12-16)
GEOS version | 3.9.0-CAPI-1.16.2
SQLite version | 3.35.5
PDAL version | 2.2.0
PostgreSQL client version | 13.5 (Ubuntu 13.5-0ubuntu0.21.10.1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Pop!_OS 21.10
  |   |   |  
Active Python plugins
db_manager | 0.1.20
sagaprovider | 2.12.99
MetaSearch | 0.3.5
grassprovider | 2.12.99
processing | 2.12.99

</body></html>Versão do QGIS
3.22.3-Białowieża
Código da versão do QGIS
[1628765ec7](https://github.com/qgis/QGIS/commit/1628765ec7)
Qt version
5.15.2
Python version
3.9.7
GDAL/OGR version
3.2.2
PROJ version
7.2.1
EPSG Registry database version
v10.008 (2020-12-16)
GEOS version
3.9.0-CAPI-1.16.2
SQLite version
3.35.5
PDAL version
2.2.0
PostgreSQL client version
13.5 (Ubuntu 13.5-0ubuntu0.21.10.1)
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Pop!_OS 21.10




Active Python plugins
db_manager
0.1.20
sagaprovider
2.12.99
MetaSearch
0.3.5
grassprovider
2.12.99
processing
2.12.99

**Comment by gioman** [comment]
> I'm trying to use `$uuid` function to update a column in my point layer, but whenever I write it down, QGIS crashes.

@rodreras crash confirmed here too on windows.

**Comment by agiudiceandrea** [comment]
@rodreras are you sure the function is `$uuid`? It seems to me it is `uuid()` https://docs.qgis.org/3.22/en/docs/user_manual/expressions/functions_list.html#uuid

**Comment by gioman** [comment]
> @rodreras are you sure the function is `$uuid`? It seems to me it is `uuid()` https://docs.qgis.org/3.22/en/docs/user_manual/expressions/functions_list.html#uuid

@agiudiceandrea maybe, but the issue here is that as soon as you start writing "$uuid" QGIS crashes.

**Comment by rodreras** [comment]
@agiudiceandrea yep, you're right! The function is `uuid()` and I was trying the wrong way with `$uuid`.
Still, I think that crashing for writing the wrong function might harm some people's projects. Luckily mine was already saved.
Despite aiming for one thing, I could discover an unexpected error :rofl:
