### ISSUE TITLE
ESC does not cancel add feature process in relation editor / relation reference widget

### ISSUE THREAD

**Issue by signedav** [qgis/QGIS#47387]
### What is the bug?

When creating a child (or a parent) feature with geometry in the relation editor widget (or relation reference widget) the dialog gets hidden and the map canvas are available with the digitizing tool. When digitizing and then press ESC it used to cancel the process and go back to the dialog of the parent. This is not the case anymore. Now it cancels the current rubberband but is still in the map tool and the parent is still invisible. Only possibility to cancel is when you press right click, then the child's attributeform opens and then you are able to press cancel (or escape) to come back.

### Steps to reproduce the issue

(The process I did in the screencast)
1. Create a feature with a reference to child table with geometry (and with it a relation editor widget in the form)
2. Add a child feature with geometry
3. Digitize something with the rubberband
4. Press escape -> rubberband disappears but process is not canceled (what would be expected)
5. Digitize something again
6. Press escape -> rubberband disappears but process is not canceled (what would be expected)
7. Digitize something again
8. Press right mouse key -> child form opens
9. Press cancel -> process is canceled
![cancelwithescape](https://user-images.githubusercontent.com/28384354/154234613-e0be0a31-b244-4ea9-b8d1-ee625074bd16.gif)

#### The project used
[cancel_geom.zip](https://github.com/qgis/QGIS/files/8078640/cancel_geom.zip)

### Versions

Master from ef85926a5d52ac918f2f0042f0487de0d66ce5bd
Used to work in 3.16 - did not test yet with versions in between

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by elpaso** [comment]
Maybe related to 697ddcd08ae
