### ISSUE TITLE
Mesh calculator crash when using max_aggr

### ISSUE THREAD

**Issue by mattfack** [qgis/QGIS#47394]
### What is the bug or the crash?

When I use max_aggr function to export a dat file qgis crashes without any message.

It works only if I create the on-the-fly dataset group

### Steps to reproduce the issue

1. open qgis
2. load  a mesh dataset
3. open mesh calculator
4. set the extent (both time and space)
5. use the formula max_aggr()
6. click calculate

### Versions

under QGIS 3.22.1, 3.22.3 do not work
with QGIS 3.12.2 works

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by vcloarec** [comment]
@mattfack  should be fixed by #47423, thanks to have reported it!
