### ISSUE TITLE
CI tests are unstable (fail for no reason occasionally)

### ISSUE THREAD

**Issue by strk** [qgis/QGIS#47395]
### What is the bug or the crash?

This check: https://github.com/qgis/QGIS/runs/5215357499?check_suite_focus=true
Run for this PR: https://github.com/qgis/QGIS/pull/47393
Triggered a `child aborted` crash, as reported here: https://cdash.orfeo-toolbox.org/viewTest.php?onlyfailed&buildid=92938

The PR changes an unrelated part of the codebase, and CDash reports the test as being "unstable" which I'm only guessing it means it sometimes fails ?

### Steps to reproduce the issue

Trigger CI runs

### Versions

master

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by strk** [comment]
Differet test failed: https://github.com/qgis/QGIS/runs/5217090116?check_suite_focus=true
For completely different PR: https://github.com/qgis/QGIS/pull/47396

The test this time is `test_analysis_processingalgs`

**Comment by strk** [comment]
The first test which was failing was `test_3d_3drendering`

**Comment by strk** [comment]
`test_analysis_processingalgs` failed again in https://github.com/qgis/QGIS/runs/5218106125?check_suite_focus=true (for https://github.com/qgis/QGIS/pull/47401)

**Comment by strk** [comment]
Another two:
```
The following tests FAILED:
	129 - test_core_networkaccessmanager (Timeout)
	286 - test_analysis_processingalgs (Timeout)
```
In https://github.com/qgis/QGIS/runs/5219178739?check_suite_focus=true
For PR https://github.com/qgis/QGIS/pull/47403

**Comment by strk** [comment]
Another example: https://github.com/qgis/QGIS/runs/6559824555?check_suite_focus=true#step:13:715

**Comment by strk** [comment]
Happened again (eptprovider): https://github.com/qgis/QGIS/runs/6632345861?check_suite_focus=true#step:13:438

**Comment by strk** [comment]
@Pedro-Murteira I'm not sure `Crash/Data Corruption` is a valid label here, unless you saw this happening in production ? This is more about testsuite / CI

**Comment by strk** [comment]
I can reproduce locally using a dockerized test setup to reflect the one used in CI. Here's how it goes:
```
root@fcd574dd3ef8:~/QGIS/build-ci# xvfb-run ctest --output-on-failure -R eptprovider
Test project /home/src/qgis/qgis/src/ci/build-ci
    Start 321: test_provider_eptprovider
1/1 Test #321: test_provider_eptprovider ........Child aborted***Exception:   0.37 sec
********* Start testing of TestQgsEptProvider *********
Config: Using QtTest library 5.12.8, Qt 5.12.8 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 9.3.0)
PASS   : TestQgsEptProvider::initTestCase()
PASS   : TestQgsEptProvider::filters()
PASS   : TestQgsEptProvider::encodeUri()
PASS   : TestQgsEptProvider::decodeUri()
PASS   : TestQgsEptProvider::preferredUri()
PASS   : TestQgsEptProvider::layerTypesForUri()
PASS   : TestQgsEptProvider::uriIsBlocklisted()
PASS   : TestQgsEptProvider::querySublayers()
PASS   : TestQgsEptProvider::brokenPath()
PASS   : TestQgsEptProvider::testLazInfo()
PASS   : TestQgsEptProvider::validLayer()
PASS   : TestQgsEptProvider::validLayerWithEptHierarchy()

=== Received signal at function time: 0ms, total time: 187ms, dumping stack ===
PASS   : TestQgsEptProvider::attributes()
=== End of stack trace ===
QFATAL : TestQgsEptProvider::calculateZRange() Received signal 11
         Function time: 0ms Total time: 187ms
FAIL!  : TestQgsEptProvider::calculateZRange() Received a fatal error.
   Loc: [Unknown file(0)]
Totals: 13 passed, 1 failed, 0 skipped, 0 blacklisted, 188ms
********* Finished testing of TestQgsEptProvider *********

```

The test environment is setup using the new .ci/run_tests.sh script:
```
 .ci/run_tests.sh  --interactive
```

Works also within a worktree with PR #48752 (which fail CI for this eptprovider issue, at the moment)

**Comment by strk** [comment]
Reading the code I suspect QgsTask::cancel() is doing too many non-mutex-protected reads (mOverallStatus).
It would help if thread access to variables would be fully documented because it's not clear which threads are supposed to read which variables and how.

\cc @nyalldawson as the original author of that class, according to git log

**Comment by strk** [comment]
@benoitdm-oslandia did that run used code including commit 842d56ff72586ed18a11b2427b14e6a9708ab4bb ?

**Comment by strk** [comment]
@benoitdm-oslandia did your code also include the merge of #48769 ? See https://github.com/qgis/QGIS/pull/48769/files#r887685390

By the way, I think test_provider_eptprovider crashes would be best discussed in 
https://github.com/qgis/QGIS/issues/48778

**Comment by benoitdm-oslandia** [comment]
@strk 
> did your code also include the merge of https://github.com/qgis/QGIS/pull/48769 ?

I wasn't by the time I posted my message but this is now working. May be it is just luck... I just launch a new rebase against master and push to check if the workflow is running fine. I will keep you in touch.

**Comment by strk** [comment]
A single success in CI does not indicate the problem is solved. The best way to test instabilities is to run tests in a loop.
For test_provider_eptprovider you can use something like:
```
while :; do 
   xvfb-run ctest --output-on-failure -R eptprovider || break
done
```

Again, please let's move this discussion in https://github.com/qgis/QGIS/issues/48778 and if you see a DIFFERENT test failing, consider filing a new issue as a spin-off of this one.

**Comment by strk** [comment]
@benoitdm-oslandia incidentally, in case you have troubles running tests locally, I've been working on the .ci/run_tests.sh script which lets you build and run tests in a docker environment similar to the one used by the CI. The would also work in worktrees with https://github.com/qgis/QGIS/pull/48654 - if you test that a review will help merging that in.
