### ISSUE TITLE
QGIS has no complete menu 

### ISSUE THREAD

**Issue by CarFil74** [qgis/QGIS#47397]
### What is the bug or the crash?

After installation of QGIS (e.g. 3.16) on a Windows 7 Ultimate, the function menu is not complete. For example, the VECTOR menu just shows geometry control, GPS instruments, and topologic validator. The same version on another PC (Windows 7) shows Geoprocessing, Geometry, Analysis, ...and so on. 

### Steps to reproduce the issue

![immagine](https://user-images.githubusercontent.com/99810945/154273466-50e476f2-c045-43a1-bf35-678ca79a9bb2.png)

### Versions

![immagine](https://user-images.githubusercontent.com/99810945/154273715-08c01392-bf03-41e9-a637-6e18bf5eaf9d.png)

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@CarFil74 Windows 7 is not supported anymore, it can't handle the Python version QGIS needs for some of its functionalities.
