### ISSUE TITLE
data defined override _ Setting a variable Offset X,Y

### ISSUE THREAD

**Issue by fischerteamplan** [qgis/QGIS#47402]
### What is the bug or the crash?

am trying to set a variable offset X,Y using data defined override, which sounds not being working properly. It has no influence on the symbol size.

### Steps to reproduce the issue

define a value called @FT_FaktorVersatz (see screenshots in pdf)
use the value in setting the offset X,Y
[Bug_QGIS_offset.pdf](https://github.com/qgis/QGIS/files/8081017/Bug_QGIS_offset.pdf)

changing the value of the variable @FT_FaktorVersatz has no influence on the offset.

### Versions

QGIS version
3.16.8-Hannover
QGIS code revision
8c50902e
Compiled against Qt
5.15.2
Running against Qt
5.15.2
Compiled against GDAL/OGR
3.3.0
Running against GDAL/OGR
3.3.0
Compiled against GEOS
3.9.1-CAPI-1.14.2
Running against GEOS
3.9.1-CAPI-1.14.2
Compiled against SQLite
3.35.2
Running against SQLite
3.35.2
PostgreSQL Client Version
13.0
SpatiaLite Version
5.0.1
QWT Version
6.1.3
QScintilla2 Version
2.11.5
Compiled against PROJ
8.0.1
Running against PROJ
Rel. 8.0.1, March 5th, 2021
OS Version
Windows 10 Version 2009
Active python plugins
db_manager; 
MetaSearch; 
processing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context
[QGIS_test.zip](https://github.com/qgis/QGIS/files/8081327/QGIS_test.zip)

_No response_

**Comment by gioman** [comment]
> [Bug_QGIS_offset.pdf](https://github.com/qgis/QGIS/files/8081017/Bug_QGIS_offset.pdf)

@fischerteamplan better attach a self contained sample project+data that shows the issue.

**Comment by fischerteamplan** [comment]
@gioman thank you, is now attached (see QGIS_test.zip)

**Comment by fischerteamplan** [comment]
it worked ... many thanks!
