### ISSUE TITLE
Rotation calculated in expression for Geometry Generator symbol is not applied to markers

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#47408]
### What is the bug or the crash?

I have a Marker symbol placed by a Geometry Generator. I want to rotate that symbol with an expression. It does not rotate.

I can see the value in the preview display of the expression editor dialog (add spaces somewhere to make it update)!
I can also see the rotation value being correctly calculated if I display it as label to the layer.

Red shows the value calculated for the marker arrows to use:
![image](https://user-images.githubusercontent.com/7661092/154364430-e01b797d-8b44-45e4-9f97-52aeb2d791e8.png)

### Steps to reproduce the issue

0. Use "world" easter egg to load ne_110m_admin_0_countries
1. Set the layer to update every 0.1 seconds to better see the issue
2. Use this Geometry Generator as symbol
```
with_variable(
	'biggest_geom',
	geometry_n(order_parts($geometry, 'area($geometry)', ascending:=False), 1),
	line_interpolate_point(
	  boundary(@biggest_geom), 
	  perimeter(@biggest_geom)*(round(epoch(now())/100)%100/100)
	)
)
```
3. Use a Simple Marker for it
4. Use this expression for the marker rotation
```
with_variable(
	'biggest_geom',
	geometry_n(order_parts($geometry, 'area($geometry)', ascending:=False), 1),
	line_interpolate_angle(
	  boundary(@biggest_geom), 
	  perimeter(@biggest_geom)*(round(epoch(now())/100)%100/100)
	)
)
```
5. The markers do not rotate

Here is an example project: [bug report.qgz.zip](https://github.com/qgis/QGIS/files/8083849/bug.report.qgz.zip)

### Versions

3.22.3 and master

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

Maybe the same issue as https://github.com/qgis/QGIS/issues/46455? That's the only related issue I could find.

**Comment by nyalldawson** [comment]
> Maybe the same issue as https://github.com/qgis/QGIS/issues/46455? That's the only related issue I could find.

Correct -- the $geometry in the rotation expression is the point geometry, not the original polygon geometry

**Comment by nyalldawson** [comment]
Closing as duplicate
