### ISSUE TITLE
Export to vector file failed. Error: Creation of data source failed (OGR error: Failed to create KML file lte.kml: lte.kml: Permission denied)

### ISSUE THREAD

**Issue by MedozTorky** [qgis/QGIS#47419]
### What is the bug or the crash?

Export to vector file failed.
Error: Creation of data source failed (OGR error: Failed to create KML file lte.kml: lte.kml: Permission denied)

### Steps to reproduce the issue

Go to 'output layer'
Click on 'export' then Save feature as ..
format KeyHole Markup Language [KML]

Then Error
Export to vector file failed.
Error: Creation of data source failed (OGR error: Failed to create KML file lte.kml: lte.kml: Permission denied)

### Versions

3.18.3

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@MedozTorky are you defining an output path/folder when you have write permissions?



> 3.18.3

Is unsupported, update to 3.22.3

**Comment by MedozTorky** [comment]
Yes output path defined, by the way i will update and see thanks

**Comment by alexbruy** [comment]
Seems duplicate of #35651.

**Comment by MedozTorky** [comment]
Hi all

Sorry for the late reply

I was suspected already closed.

The issue rectified after using the latest version

Thanks alot and sorry again
