### ISSUE TITLE
Profile issue causes line drawing tools to create nodes without mouse clicks

### ISSUE THREAD

**Issue by enzedrailmaps** [qgis/QGIS#47410]
### What is the bug or the crash?

When attempting to draw a line in a linestring layer, instead of waiting for a mouse click, nodes are "automatically" inserted into the line.
The issue goes away if a new profile is created, but then returns at a later date.
No plugins are installed except for the default plugins which can't be removed.

### Steps to reproduce the issue

The profile and a sample project will be attached to this bug report in subsequent comments.
Steps to reproduce are
open the project
select the linestring layer
put the layer into edit mode
click the button to add a feature
try to draw a new feature by moving the mouse.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.3-Białowieża | QGIS code revision | 1628765ec7
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.2
GDAL/OGR version | 3.2.2
PROJ version | 7.2.1
EPSG Registry database version | v10.008 (2020-12-16)
GEOS version | 3.9.0-CAPI-1.16.2
SQLite version | 3.34.1
PDAL version | 2.2.0
PostgreSQL client version | 13.5 (Debian 13.5-0+deb11u1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Debian GNU/Linux 11 (bullseye)
  |   |   |  
Active Python plugins
MetaSearch | 0.3.5
processing | 2.12.99
db_manager | 0.1.20
grassprovider | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.22.3-Białowieża
QGIS code revision
[1628765ec7](https://github.com/qgis/QGIS/commit/1628765ec7)
Qt version
5.15.2
Python version
3.9.2
GDAL/OGR version
3.2.2
PROJ version
7.2.1
EPSG Registry database version
v10.008 (2020-12-16)
GEOS version
3.9.0-CAPI-1.16.2
SQLite version
3.34.1
PDAL version
2.2.0
PostgreSQL client version
13.5 (Debian 13.5-0+deb11u1)
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Debian GNU/Linux 11 (bullseye)

Active Python plugins
MetaSearch
0.3.5
processing
2.12.99
db_manager
0.1.20
grassprovider
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
Maybe you've pressed "r" to enter the stream digitising mode?

**Comment by enzedrailmaps** [comment]
Oh! that must be it :)
Thankyou
And have a nice day
