### ISSUE TITLE
scale bar is real?

### ISSUE THREAD

**Issue by pianolente** [qgis/QGIS#47429]
### What is the bug or the crash?

When I am in the print layout and I add the scale bar to the map I noticed that if I change the unit multiplier the size of the bar remains unchanged, in the sense that it is not proportional to the new scale.
So isn't the scale bar really proportionate to the size of the map?

### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/99924188/154578135-3eba0514-4766-4c68-bd50-4593ca52471b.png)

### Versions

The current released version of QGIS is 3.22.3. 
We are working on 3.23-Master. It will go into feature freeze on 2022-01-14 12:00:00 UTC and be released as 3.24 on 2022-02-18 12:00:00 UTC. 
Details on changes can be found on github at https://github.com/qgis/QGIS/commits/master. 

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
> So isn't the scale bar really proportionate to the size of the map?

@pianolente attach a sample project with data (and a layout).

**Comment by DelazJ** [comment]
> I noticed that if I change the unit multiplier the size of the bar remains unchanged,

Yes, but didn't the numbers change? Note that it's up to you to fix the displayed unit.

**Comment by pianolente** [comment]
Ok I understand maybe what you mean; the fixed width must be adjusted manually (I assume having a certain reference on the map).
Did I get it right?

**Comment by DelazJ** [comment]
Hmm... Your scale should be associated to an existing map item (check in the scale item properties). So when you zoom in/out that map, the map scale change and the scale bar size should follow. But If you change the multiplier value in scale bar properties, the length of the bar is still the same while the distance values displayed above is divided by the multiplier.
If not the case (and maybe I misunderstand your "issue") then share a project with data and layout as suggested by @gioman above.

**Comment by pianolente** [comment]
How do you share a project with data and layout  ?

**Comment by pianolente** [comment]
> > So isn't the scale bar really proportionate to the size of the map?
> 
> @pianolente attach a sample project with data (and a layout).

How can I do this?

**Comment by gioman** [comment]
> @gioman How can I do this?

@pianolente create project (with composer and sample data) that shows what you describe, zip everything and attach it here.

**Comment by pianolente** [comment]
it's a pretty big project ... I'm doing an aerial survey of my whole city with the drone made up of several maps to be merged into one, here are the individual maps and the project file https://1drv.ms/u/s!AjuuAQV3dN2fhdczKwIsl2XO5nRXxg?e=OIzFXU

**Comment by gioman** [comment]
> it's a pretty big project

@pianolente you don't need to attach your project, but **a** project, a sample one, with the bare minimum necessary to show what you describe.

**Comment by gioman** [comment]
> * does the scale bar really respect the length in meters?
> 
> * when I change the map scale for the print layout, does the scale bar re-scale faithfully?

@pianolente do you have any evidence of the contrary? what you show in your screencast seems ok to me.

**Comment by pianolente** [comment]
yes I did further tests, I had perhaps not understood this function well (when I tried to make changes to the layout); thanks for your attention I think the thread may be closed
