### ISSUE TITLE
Crash switching from editing line layer to point layer

### ISSUE THREAD

**Issue by KMahony93** [qgis/QGIS#47420]
## User Feedback

Each time I switch between editing a line layer and a point layer, the app crashes. Even when I have switched off editing on the line layer. 

## Report Details

**Crash ID**: [fb4fae13599918da36e4451ebb68dfb602d18312](https://github.com/qgis/QGIS/search?q=fb4fae13599918da36e4451ebb68dfb602d18312&type=Issues)

**Stack Trace**
<pre>
QgsMapCanvas::setMapTool :
QgisApp::activateDeactivateLayerRelatedActions :
QMetaObject::activate :
QgisApp::activeLayerChanged :
QgisApp::onActiveLayerChanged :
QMetaObject::activate :
QgsLayerTreeView::currentLayerChanged :
QgsLayerTreeView::onCurrentChanged :
QMetaObject::activate :
QItemSelectionModel::setCurrentIndex :
QAbstractItemView::mousePressEvent :
QTreeView::mousePressEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.16.2-Hannover
QGIS code revision: f1660f9da5
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Steps to reproduce the issue

Toggle editing of line layer
Switch off toggle editing of line layer
Click point layer
See error

### Versions

QGIS version
3.16.2-Hannover
QGIS code revision
f1660f9da5
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
ImportPhotos; 
NNJoin; 
quick_map_services; 
ViewshedAnalysis; 
db_manager; 
processing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

I did not try with another profile, however this was reproduced on a colleagues profile

**Comment by gioman** [comment]
> Active python plugins
> ImportPhotos;
> NNJoin;
> quick_map_services;
> ViewshedAnalysis;

@KMahony93 you must use a supported version (which right now is basically only 3.22.3) and you must try with a new QGIS profile (no 3rd party plugins installed).

**Comment by KMahony93** [comment]
Thank you @gioman. Issue resolved with V3.22.3, did not need to try new profile.
