### ISSUE TITLE
can't enable GDAL VRT Pixel Functions

### ISSUE THREAD

**Issue by janzandr** [qgis/QGIS#47439]
### What is the bug or the crash?

Can't use VRT raster with VRT Pixel Functions in QGIS 3.22. 
In QGIS 3.18 it works fine.

### Steps to reproduce the issue

1. Enable VRT Pixel Functions:
```
>>>from osgeo import gdal
>>>gdal.SetConfigOption('GDAL_VRT_ENABLE_PYTHON', 'YES')
>>>gdal.GetConfigOption('GDAL_VRT_ENABLE_PYTHON')
'YES'
```
2. Open a VRT with a Python VRT Pixel Function to get the error.
![image](https://user-images.githubusercontent.com/45030715/154765630-99302b0d-938e-40d7-a924-4846d81856f1.png)

![image](https://user-images.githubusercontent.com/45030715/154765549-0e47dc9f-b166-40b1-993e-206588cc4bab.png)

Here is a simple VRT for testing:
```
<VRTDataset rasterXSize="100" rasterYSize="100">
  <VRTRasterBand dataType="Float32" band="1" subClass="VRTDerivedRasterBand">
    <PixelFunctionLanguage>Python</PixelFunctionLanguage>
    <PixelFunctionType>ufunc</PixelFunctionType>
    <PixelFunctionCode>
      <![CDATA[

def ufunc(in_ar, out_ar, *args, **kwargs):
    out_ar[:] = 42

  ]]>
    </PixelFunctionCode>
  </VRTRasterBand>
</VRTDataset>
```

Note that in **QGIS 3.18**, everythings works fine:
![image](https://user-images.githubusercontent.com/45030715/154766866-ae37db4b-0825-4a45-906e-5a4dc0201af6.png)

### Versions

QGIS version
3.22.3-Białowieża
QGIS code revision
1628765ec7
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
Compiled against GEOS
3.10.0-CAPI-1.16.0
Running against GEOS
3.10.2-CAPI-1.16.0
Compiled against SQLite
3.35.2
Running against SQLite
3.37.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
BitFlagRenderer
0.4.20200817T093838.master
changeDataSource
3.1
DataPlotly
3.8.1
ee_plugin
0.0.4
enmapboxplugin
3.9.20211123T125541.master
force4qgis
1.0.1
InvisibleLayersAndGroups
2.1
rasterdataplotting
1.6.3
rastertimeseriesmanager
1.8
timeseriesviewerplugin
1.17.20210312T143004.master
zoomview
1.1.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by janzandr** [comment]
Also note that GDAL can read the same VRT correctly:
```
>>>ds = gdal.Open(r'C:\Users\Andreas\Downloads\test.vrt')
>>>ds
<osgeo.gdal.Dataset; proxy of <Swig Object of type 'GDALDatasetShadow *' at 0x0000021CEE382F00> >
ds.ReadAsArray()
array([[42., 42., 42., ..., 42., 42., 42.],
       [42., 42., 42., ..., 42., 42., 42.],
       [42., 42., 42., ..., 42., 42., 42.],
       ...,
       [42., 42., 42., ..., 42., 42., 42.],
       [42., 42., 42., ..., 42., 42., 42.],
       [42., 42., 42., ..., 42., 42., 42.]], dtype=float32)
```

**Comment by gioman** [comment]
> Note that in **QGIS 3.18**, everythings works fine:

Just tested on 3.22.3 and I get the same you describe for 3.18, also no error message

![image](https://user-images.githubusercontent.com/1951107/154812504-d2b704d0-de2f-4125-9e26-c65fc2eea4e4.png)

**Comment by janzandr** [comment]
Any suggestions what to try next?

**Comment by gioman** [comment]
> Any suggestions what to try next?

@janzandr a new QGIS profile.

**Comment by janzandr** [comment]
Yes, I tried that.
I also installed and tested on QGIS 3.23.

**Comment by gioman** [comment]
> Yes, I tried that.

@janzandr now? because at the time of your report you didn't

```
Active Python plugins
BitFlagRenderer
0.4.20200817T093838.master
changeDataSource
3.1
DataPlotly
3.8.1
ee_plugin
0.0.4
enmapboxplugin
3.9.20211123T125541.master
force4qgis
1.0.1
InvisibleLayersAndGroups
2.1
rasterdataplotting
1.6.3
rastertimeseriesmanager
1.8
timeseriesviewerplugin
1.17.20210312T143004.master
zoomview
1.1.1
```

**Comment by janzandr** [comment]
I copied the versions info from my default profile.
But I also tested on a fresh profile.

**Comment by janzandr** [comment]
I installed OSGeo4W in a new folder. Now it is working.
