### ISSUE TITLE
Choose user profile on QGIS startup

### ISSUE THREAD

**Issue by MartinMap** [qgis/QGIS#47446]
### Feature description

It would be great to have the possibly to choose the user profile on QGIS startup (if there exists more the one).

### Additional context

According to [this question on gis.stackexchange.org](https://gis.stackexchange.com/questions/397994/can-qgis-ask-for-the-preferred-user-profile-on-startup) the user [J. Monticolo](https://gis.stackexchange.com/users/93097/j-monticolo) coded a small startup script to give me the possibility to chose the profile I need. I use this very often and I'm sure, a lot of users would enjoy this too!
![Terminal_001](https://user-images.githubusercontent.com/6401482/154846481-5d5d47e1-6f93-4db8-8c75-4d64f1ac2d66.png)

**Comment by antoniolocandro** [comment]
If this gets added I would suggest it was an option to turn on/off either globally or per project, I wouldn't want to select a profile each time I run QGIS as that would be an extra click each time if I didn't want to go to a different profile. It would be nicer if one could change profile within the project without requiring a restart but I think that is not possible last I recall.
