### ISSUE TITLE
Overlapping Point Labelling

### ISSUE THREAD

**Issue by rmhudson1** [qgis/QGIS#47443]
### Feature description

I have multiple points in a shapefile that share the exact same location. Each of these points has a unique label that I would like to display. Currently QGIS will overlay each label on top of one-another, making them entirely unreadable. 
Ultimately I want to display a list of document titles that are associated with a specific facility, providing a visual overview of which documents exist and what their status is (which will be done through labelling formulas). 
It would be ideal for overlapping labels to be stacked on top of one-another, such that all labels are left-aligned and viewed as a 'grouping' of related identifiers.

**Comment by gioman** [comment]
@rmhudson1 have you considered the point displacement renderer?

![image](https://user-images.githubusercontent.com/1951107/154812024-1251bf5e-368b-41aa-90e0-7b727efbf268.png)

**Comment by rmhudson1** [comment]
Hi @gioman, thanks for the suggestion. This almost gets me to where I'd like to be, but the concentric display won't quite work for what I am attempting to achieve. The Grid layout is one step closer, but I am not able to find a way to control the layout of the grid itself; it seems that QGIS automatically assigns the row/column quantities. I would be aiming to have a grid with 20 rows, and a single column, or 50 rows with a single column, etc.
I will do some additonal testing with this feature to see if I can find a solution. Thank you.

**Comment by gioman** [comment]
> . I would be aiming to have a grid with 20 rows, and a single column, or 50 rows with a single column, etc.

seems a nice idea for an improvement of the renderer.
