### ISSUE TITLE
named parameters no longer work in the get_feature function

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#47462]
### What is the bug or the crash?

In QGIS 3.24.0 the parameters named in the `get_feature` function no longer work after introducing [this feature](https://github.com/qgis/QGIS/pull/43352)

### in QGIS 3.22
```
get_feature (
layer:= 'risk_area',
attribute:= 'Risk',
value:= 'R2')
```

`<feature: 1>`

### in QGIS 3.24.0

the expression gives an error if the named parameters are used:

```
get_feature (
layer:= 'risk_area',
attribute:= 'Risk',
value:= 'R2')
```

```
Parser Errors:
No value specified for QgsExpressionFunction::Parameter 'attribute(s)' for get_feature
```

### Steps to reproduce the issue

how to reproduce it:

1. load any two vector layers into QGIS;
2. start the field calc in one of the two layers;
3. type the expression above, with and without named parameters

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
The "attribute" parameter was wrongly renamed "attribute(s)".

**Comment by roya0045** [comment]
> The "attribute" parameter was wrongly renamed "attribute(s)".

Thanks! I thought the keyword was taken elsewhere, I'll push a fix soon.

**Comment by nyalldawson** [comment]
Fixed by https://github.com/qgis/QGIS/pull/47483
