### ISSUE TITLE
option to update field missing in Field Calculator in modeller

### ISSUE THREAD

**Issue by Thibaultsdis83** [qgis/QGIS#47464]
### What is the bug or the crash?

I want to update a field with the "field calculator" in the modeleur in Qgis 3.16.16. The problem it's the line to choise between update or create the field not exist. This line is present in Qgis 2.18

### Steps to reproduce the issue

![qgis3 16 16_modeleur](https://user-images.githubusercontent.com/100135946/154957603-33984c74-3a30-4310-9ffb-b5f69b8a2634.png)

### Versions

3.16.16

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
@Thibaultsdis83 to update fields you can now use the "refactor fields" tool.
