### ISSUE TITLE
QGIS disappears after crash

### ISSUE THREAD

**Issue by acgkt** [qgis/QGIS#47468]
### What is the bug or the crash?

QGIS crashes after I try to save a vector layer, and then I can no longer find the executive file on my computer. It just disappears. I don't manage to find it after that, I don't know if I don't look in the right place or not, but it has been happening with every version I downloaded (3.16.15, 3.16.16, 3.22.3)...

### Steps to reproduce the issue

QGIS crashes while trying to save a layer.

### Versions

3.22.3, 3.16.15, 3.16.16.

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
> QGIS crashes after I try to save a vector layer

@acgkt try with a new QGIS profile (settings > user profiles > new profile). If the problem persist describe in detail the steps that are lading to the crash (attaching sample data if necessary).

**Comment by acgkt** [comment]
> > QGIS crashes after I try to save a vector layer
> 
> @acgkt try with a new QGIS profile (settings > user profiles > new profile). If the problem persist describe in detail the steps that are lading to the crash (attaching sample data if necessary).

Hi. I have tried removing QGIS with the installation file and reinstalling it again, and did what you did. QGIS didn't crash for a few days, hence no reply from me. But just now, it crashed and disappeared again.
Basically, what happens is that I am working on QGIS, and when I'm typing a title for my file name to save it, QGIS freezes (I can see it by the letters no longer being typed in), crashes, and the app disappears totally from its original file (and the programs list on Windows), cf attached screenshots.
![image](https://user-images.githubusercontent.com/100154859/155691143-aa5e12e2-7152-4415-b86c-418eab26d2ea.png)
![image](https://user-images.githubusercontent.com/100154859/155691245-16149604-4b3c-4109-8f38-6f28c1f95a2a.png)

I don't know what to do, because I really don't understand what causes this. My old 3.8 QGIS worked fine (except the vectors operations disappeared from its window so that's why I tried to upgrade to better versions in the first place...).

**Comment by gioman** [comment]
@acgkt as you can guess, this is not a general QGIS issue, but rather something very specific to your machine. Very hard to say what could be.

**Comment by acgkt** [comment]
> @acgkt as you can guess, this is not a general QGIS issue, but rather something very specific to your machine. Very hard to say what could be.

I use so, I'll continue looking if I can find anything. :( Thanks for the help eitherway!

**Comment by Smgpina** [comment]
I had the same isue today. Qgis crashed and my file desappear. I don't find it anywhere... can someone help me? please! It was a week work... Tks
