### ISSUE TITLE
Custom properties on Annotation Layers not persisted

### ISSUE THREAD

**Issue by CodeBardian** [qgis/QGIS#47463]
### What is the bug or the crash?

Properties set with `setCustomProperty` function on a `QgsAnnotationLayer` are not persisted and therefore not available after reloading the project. 

The `<customproperties>` xml tag is not written to the project file when saving the project, because `QgsMapLayer::writeCustomProperties` is never called from `QgsAnnotationLayer::writeXml`.

### Steps to reproduce the issue

Consider this small example script, which can be pasted in the console: 

```py
a_layer = QgsAnnotationLayer('Annotation Layer', QgsAnnotationLayer.LayerOptions(QgsProject.instance().transformContext()))
v_layer =  QgsVectorLayer("Point?crs=EPSG:4326", 'Vector Layer', "memory")

QgsProject().instance().addMapLayer(a_layer)
QgsProject().instance().addMapLayer(v_layer)
a_layer.setCustomProperty('mycustomproperty', 'test')
v_layer.setCustomProperty('mycustomproperty', 'test')

print(a_layer.customProperty('mycustomproperty')) # prints test
print(v_layer.customProperty('mycustomproperty')) # prints test
```
However, after saving and reloading the project the custom property is not available anymore:

```
>>> iface.activeLayer().customProperty('mycustomproperty')  # custom property on vector layer is still there
'test'
>>> iface.activeLayer().customProperty('mycustomproperty')  # custom property on annotation layer is None
None
```

### Versions

3.22.3 (judging by the source files, it also happens on master)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by rustyjux** [comment]
I'm not sure if this post is helpful or QGIS GitHub standard practice, but I am experiencing the same issue in 3.22.3 where my Rendering settings (Scale Visibility) are not preserved following reloading the project.

**Comment by CodeBardian** [comment]
> I'm not sure if this post is helpful or QGIS GitHub standard practice, but I am experiencing the same issue in 3.22.3 where my Rendering settings (Scale Visibility) are not preserved following reloading the project.

That definitely is a related problem. Setting scale dependent visibility on Annotation Layers is not preserved after project reload, because the respective entries in the project file (`hasScaleBasedVisibilityFlag`, `minScale` and `maxScale`) are never actually written.

**Comment by mblesius** [comment]
This problems stills exists in QGIS 3.24.3.
I first noticed it when I was working with Geospatial PDFs. The _PDF Group_ of a layer is also stored in a custom property and it was missing for the Annotation layers when I reloaded my projects.
