### ISSUE TITLE
Problem viewing external file from WebDAV Storage

### ISSUE THREAD

**Issue by sigmoe** [qgis/QGIS#47466]
### What is the bug or the crash?

When a WebDAV Storage is associated to a field, if you try to view the file linked to the field value in the form, there's an error message like that:
_Error opening //c/Users/Etienne/AppData/Local/Temp/mySMnV.jpg: Nom de réseau introuvable
Failed to load URL file://c/Users/Etienne/AppData/Local/Temp/mySMnV.jpg._

This problem occurs on Windows. It seems to be a problem of path for a temporary file that is formatted for Linux and not for Windows.

### Steps to reproduce the issue

See my video attached

https://user-images.githubusercontent.com/55922863/154991757-dbfd9257-32e7-4c5d-b285-8c786bf1021f.mp4

### Versions

QGIS version
3.22.3-Białowieża
QGIS code revision
1628765ec7
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.0-CAPI-1.16.0
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Problem on Windows

**Comment by troopa81** [comment]
Thanks for reporting, I will fix this one
