### ISSUE TITLE
Scale bar in km seems wrong

### ISSUE THREAD

**Issue by wkitlasten** [qgis/QGIS#47469]
### What is the bug or the crash?

The scale bar is incorrect when I choose to display it in km. The distance covered by the scale bar is 2km, not 2000 km.

![image](https://user-images.githubusercontent.com/14982084/155031822-f4efc40d-5d7d-4fe2-a721-3e2ec974e0dc.png)

When I try to set the "segment width" to 2 units, the scale bar essentially collapses:

![image](https://user-images.githubusercontent.com/14982084/155031333-ea5c5e3d-394d-4ffc-97aa-82bea73910a0.png)

The only way to get the scale bar to display properly is to use meters.
![image](https://user-images.githubusercontent.com/14982084/155031382-7e19ded1-e459-4f75-bf6c-88b33ca338d4.png)

### Steps to reproduce the issue

Go to Layout
Add item > Add scale bar
In Item properties set scalebar units to kilometers

### Versions

QGIS version
3.10.2-A Coruña
QGIS code revision
d4cd3cfe5a
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.3
Running against GDAL/OGR
3.0.3
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.0
Running against PROJ
Rel. 6.3.0, January 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
area_weighted_average; 
QPackage; 
quick_map_services; 
rasterstats; 
MetaSearch; 
processing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

Probably a simple conversion faction buried somewhere.

**Comment by nyalldawson** [comment]
You need to share a sample project -- there's many factors which could be in play which mean that your scale bar is actually correct.

**Comment by gioman** [comment]
> 3.10.2-A Coruña

@wkitlasten and also you need to upgrade to a supported version.
