### ISSUE TITLE
Uncaught KeyError: 'MENU_shapetools:createarc'


### ISSUE THREAD

**Issue by matiasvaldivia** [qgis/QGIS#47478]
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "/usr/share/qgis/python/plugins/processing/gui/ConfigDialog.py", line 307, in resetMenusToDefaults
    setting = ProcessingConfig.settings["MENU_" + alg.id()]
KeyError: 'MENU_shapetools:createarc'

```
processing 2.12.99, QGIS 3.20.1-Odense on Linux 5.13.0-28-generic

**Comment by gioman** [comment]
> processing 2.12.99, QGIS 3.20.1-Odense on Linux 5.13.0-28-generic

@matiasvaldivia update to 3.22.3, create a new QGIS profile (settings > user profiles > new profile). Reopen if you still get the error.
