### ISSUE TITLE
Qgis no response

### ISSUE THREAD

**Issue by Ehespinosa** [qgis/QGIS#47479]
### What is the bug or the crash?

After doing any operation with Qgis stops responding

### Steps to reproduce the issue

1. Open Qgis.
2. Open project
3. Add Layer
4. Close 

### Versions

3.22

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

the registry of my computer (OS Fedora 34) shows this.
Process 3598 (qgis) of user 1000 dumped core.

Stack trace of thread 3598:
#0  0x00007f18723982a2 raise (libc.so.6 + 0x3d2a2)
#1  0x00007f18723818a4 abort (libc.so.6 + 0x268a4)
#2  0x000055d595f9cdc5 _Z9qgisCrashi (qgis + 0x11dc5)
#3  0x00007f1872398320 __restore_rt (libc.so.6 + 0x3d320)
#4  0x00007f17c0970210 _ZN24QGnomePlatformDecoration22updateButtonHoverStateE6Button (libqgnomeplatformdecoration.so + 0x7210)
#5  0x00007f17c0970574 _ZN24QGnomePlatformDecoration15processMouseTopEPN15QtWaylandClient19QWaylandInputDeviceERK7QPointF6QFlagsIN2Qt11MouseButtonEES6_INS7_16KeyboardModifierEE (libqgnomeplatformdecoration.so + 0x7574)
#6  0x00007f17c0970815 _ZN24QGnomePlatformDecoration11handleMouseEPN15QtWaylandClient19QWaylandInputDeviceERK7QPointFS5_6QFlagsIN2Qt11MouseButtonEES6_INS7_16KeyboardModifierEE (libqgnomeplatformdecoration.so + 0x7815)
#7  0x00007f1853474009 _ZN15QtWaylandClient14QWaylandWindow30handleMouseEventWithDecorationEPNS_19QWaylandInputDeviceERKNS_20QWaylandPointerEventE (libQt5WaylandClient.so.5 + 0x8d009)
#8  0x00007f1853474424 _ZN15QtWaylandClient14QWaylandWindow11handleMouseEPNS_19QWaylandInputDeviceERKNS_20QWaylandPointerEventE (libQt5WaylandClient.so.5 + 0x8d424)
#9  0x00007f185346351d _ZN15QtWaylandClient19QWaylandInputDevice7Pointer15flushFrameEventEv (libQt5WaylandClient.so.5 + 0x7c51d)
#10 0x00007f1864f5bc04 ffi_call_unix64 (libffi.so.6 + 0x6c04)
#11 0x00007f1864f5b107 ffi_call (libffi.so.6 + 0x6107)
#12 0x00007f18533d2d10 wl_closure_invoke.constprop.0 (libwayland-client.so.0 + 0x6d10)
#13 0x00007f18533d342b dispatch_event.isra.0 (libwayland-client.so.0 + 0x742b)
#14 0x00007f18533d361c wl_display_dispatch_queue_pending (libwayland-client.so.0 + 0x761c)
#15 0x00007f1853467853 _ZN15QtWaylandClient15QWaylandDisplay13flushRequestsEv (libQt5WaylandClient.so.5 + 0x80853)
#16 0x00007f1874699430 _Z10doActivateILb0EEvP7QObjectiPPv (libQt5Core.so.5 + 0x2da430)
#17 0x00007f187469bb8a _ZN15QSocketNotifier9activatedE17QSocketDescriptorNS_4TypeENS_14QPrivateSignalE (libQt5Core.so.5 + 0x2dcb8a)
#18 0x00007f187469c3a3 _ZN15QSocketNotifier5eventEP6QEvent (libQt5Core.so.5 + 0x2dd3a3)
#19 0x00007f1875137443 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5 + 0x1ae443)
#20 0x00007f1873175c33 _ZN14QgsApplication6notifyEP7QObjectP6QEvent (libqgis_core.so.3.22.3 + 0x9e3c33)
#21 0x00007f18746657d8 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5 + 0x2a67d8)
#22 0x00007f18746b763f _ZL28socketNotifierSourceDispatchP8_GSourcePFiPvES1_ (libQt5Core.so.5 + 0x2f863f)
#23 0x00007f186acec4cf g_main_context_dispatch (libglib-2.0.so.0 + 0x554cf)
#24 0x00007f186ad404f8 g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0xa94f8)
#25 0x00007f186ace9c03 g_main_context_iteration (libglib-2.0.so.0 + 0x52c03)
#26 0x00007f18746b6bb8 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2f7bb8)
#27 0x00007f18746641e2 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2a51e2)
#28 0x00007f187466c724 _ZN16QCoreApplication4execEv (libQt5Core.so.5 + 0x2ad724)
#29 0x000055d595f97a1e main (qgis + 0xca1e)
#30 0x00007f1872382b75 __libc_start_main (libc.so.6 + 0x27b75)
#31 0x000055d595f9b73e _start (qgis + 0x1073e)

Stack trace of thread 3613:
#0  0x00007f18743b3a8a __futex_abstimed_wait_common64 (libpthread.so.0 + 0x15a8a)
#1  0x00007f18743ad2c0 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf2c0)
#2  0x00007f182f28824b util_queue_thread_func (i965_dri.so + 0x24924b)
#3  0x00007f182f287d0b impl_thrd_routine (i965_dri.so + 0x248d0b)
#4  0x00007f18743a7299 start_thread (libpthread.so.0 + 0x9299)
#5  0x00007f187245b353 __clone (libc.so.6 + 0x100353)

Stack trace of thread 3618:
#0  0x00007f18724505bf __poll (libc.so.6 + 0xf55bf)
#1  0x00007f186ad4048c g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0xa948c)
#2  0x00007f186ace9c03 g_main_context_iteration (libglib-2.0.so.0 + 0x52c03)
#3  0x00007f18746b6c2e _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2f7c2e)
#4  0x00007f18746641e2 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2a51e2)
#5  0x00007f18744a72ca _ZN7QThread4execEv (libQt5Core.so.5 + 0xe82ca)
#6  0x00007f18744a84c6 _ZN14QThreadPrivate5startEPv (libQt5Core.so.5 + 0xe94c6)
#7  0x00007f18743a7299 start_thread (libpthread.so.0 + 0x9299)
#8  0x00007f187245b353 __clone (libc.so.6 + 0x100353)

Stack trace of thread 3623:
#0  0x00007f18743b3a8a __futex_abstimed_wait_common64 (libpthread.so.0 + 0x15a8a)
#1  0x00007f18743ad2c0 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf2c0)
#2  0x00007f1872618b10 _ZNSt18condition_variable4waitERSt11unique_lockISt5mutexE (libstdc++.so.6 + 0xd3b10)
#3  0x00007f1870489aa0 _ZN7bmalloc9AsyncTaskINS_4HeapEMS1_FvvEE13threadRunLoopEv (libQt5WebKit.so.5 + 0x2180aa0)
#4  0x00007f1870489bef _ZN7bmalloc9AsyncTaskINS_4HeapEMS1_FvvEE16threadEntryPointEPS4_ (libQt5WebKit.so.5 + 0x2180bef)
#5  0x00007f187261ecd4 execute_native_thread_routine (libstdc++.so.6 + 0xd9cd4)
#6  0x00007f18743a7299 start_thread (libpthread.so.0 + 0x9299)
#7  0x00007f187245b353 __clone (libc.so.6 + 0x100353)

Stack trace of thread 3616:
#0  0x00007f18724505bf __poll (libc.so.6 + 0xf55bf)
#1  0x00007f186ad4048c g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0xa948c)
#2  0x00007f186ace9c03 g_main_context_iteration (libglib-2.0.so.0 + 0x52c03)
#3  0x00007f18746b6bb8 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2f7bb8)
#4  0x00007f18746641e2 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2a51e2)
#5  0x00007f18744a72ca _ZN7QThread4execEv (libQt5Core.so.5 + 0xe82ca)
#6  0x00007f18744a84c6 _ZN14QThreadPrivate5startEPv (libQt5Core.so.5 + 0xe94c6)
#7  0x00007f18743a7299 start_thread (libpthread.so.0 + 0x9299)
#8  0x00007f187245b353 __clone (libc.so.6 + 0x100353)

Stack trace of thread 3611:
#0  0x00007f18743b3a8a __futex_abstimed_wait_common64 (libpthread.so.0 + 0x15a8a)
#1  0x00007f18743ad5c4 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf5c4)
#2  0x00007f18744adf9a _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt5Core.so.5 + 0xeef9a)
#3  0x00007f18744ab794 _ZN17QThreadPoolThread3runEv (libQt5Core.so.5 + 0xec794)
#4  0x00007f18744a84c6 _ZN14QThreadPrivate5startEPv (libQt5Core.so.5 + 0xe94c6)
#5  0x00007f18743a7299 start_thread (libpthread.so.0 + 0x9299)
#6  0x00007f187245b353 __clone (libc.so.6 + 0x100353)

Stack trace of thread 3610:
#0  0x00007f18743b3a8a __futex_abstimed_wait_common64 (libpthread.so.0 + 0x15a8a)
#1  0x00007f18743ad5c4 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf5c4)
#2  0x00007f18744adf9a _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt5Core.so.5 + 0xeef9a)
#3  0x00007f18744ab794 _ZN17QThreadPoolThread3runEv (libQt5Core.so.5 + 0xec794)
#4  0x00007f18744a84c6 _ZN14QThreadPrivate5startEPv (libQt5Core.so.5 + 0xe94c6)
#5  0x00007f18743a7299 start_thread (libpthread.so.0 + 0x9299)
#6  0x00007f187245b353 __clone (libc.so.6 + 0x100353)

Stack trace of thread 3607:
#0  0x00007f18724505bf __poll (libc.so.6 + 0xf55bf)
#1  0x00007f186ad4048c g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0xa948c)
#2  0x00007f186aceba93 g_main_loop_run (libglib-2.0.so.0 + 0x54a93)
#3  0x00007f186952dd9a gdbus_shared_thread_func.lto_priv.0 (libgio-2.0.so.0 + 0x110d9a)
#4  0x00007f186ad1ac42 g_thread_proxy (libglib-2.0.so.0 + 0x83c42)
#5  0x00007f18743a7299 start_thread (libpthread.so.0 + 0x9299)
#6  0x00007f187245b353 __clone (libc.so.6 + 0x100353)

Stack trace of thread 3605:
#0  0x00007f18724505bf __poll (libc.so.6 + 0xf55bf)
#1  0x00007f186ad4048c g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0xa948c)
#2  0x00007f186ace9c03 g_main_context_iteration (libglib-2.0.so.0 + 0x52c03)
#3  0x00007f1852adf3ed dconf_gdbus_worker_thread (libdconfsettings.so + 0x73ed)
#4  0x00007f186ad1ac42 g_thread_proxy (libglib-2.0.so.0 + 0x83c42)
#5  0x00007f18743a7299 start_thread (libpthread.so.0 + 0x9299)
#6  0x00007f187245b353 __clone (libc.so.6 + 0x100353)

Stack trace of thread 3604:
#0  0x00007f18724505bf __poll (libc.so.6 + 0xf55bf)
#1  0x00007f186ad4048c g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0xa948c)
#2  0x00007f186ace9c03 g_main_context_iteration (libglib-2.0.so.0 + 0x52c03)
#3  0x00007f186ace9c51 glib_worker_main (libglib-2.0.so.0 + 0x52c51)
#4  0x00007f186ad1ac42 g_thread_proxy (libglib-2.0.so.0 + 0x83c42)
#5  0x00007f18743a7299 start_thread (libpthread.so.0 + 0x9299)
#6  0x00007f187245b353 __clone (libc.so.6 + 0x100353)

Stack trace of thread 3602:
#0  0x00007f18724505bf __poll (libc.so.6 + 0xf55bf)
#1  0x00007f186ad4048c g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0xa948c)
#2  0x00007f186ace9c03 g_main_context_iteration (libglib-2.0.so.0 + 0x52c03)
#3  0x00007f18746b6bb8 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2f7bb8)
#4  0x00007f18746641e2 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2a51e2)
#5  0x00007f18744a72ca _ZN7QThread4execEv (libQt5Core.so.5 + 0xe82ca)
#6  0x00007f186a29bb6b _ZN22QDBusConnectionManager3runEv (libQt5DBus.so.5 + 0x1bb6b)
#7  0x00007f18744a84c6 _ZN14QThreadPrivate5startEPv (libQt5Core.so.5 + 0xe94c6)
#8  0x00007f18743a7299 start_thread (libpthread.so.0 + 0x9299)
#9  0x00007f187245b353 __clone (libc.so.6 + 0x100353)

Stack trace of thread 3620:
#0  0x00007f18724505bf __poll (libc.so.6 + 0xf55bf)
#1  0x00007f186ad4048c g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0xa948c)
#2  0x00007f186ace9c03 g_main_context_iteration (libglib-2.0.so.0 + 0x52c03)
#3  0x00007f18746b6bb8 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2f7bb8)
#4  0x00007f18746641e2 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2a51e2)
#5  0x00007f18744a72ca _ZN7QThread4execEv (libQt5Core.so.5 + 0xe82ca)
#6  0x00007f18744a84c6 _ZN14QThreadPrivate5startEPv (libQt5Core.so.5 + 0xe94c6)
#7  0x00007f18743a7299 start_thread (libpthread.so.0 + 0x9299)
#8  0x00007f187245b353 __clone (libc.so.6 + 0x100353)

Stack trace of thread 3617:
#0  0x00007f18724505bf __poll (libc.so.6 + 0xf55bf)
#1  0x00007f186ad4048c g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0xa948c)
#2  0x00007f186ace9c03 g_main_context_iteration (libglib-2.0.so.0 + 0x52c03)
#3  0x00007f18746b6bb8 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2f7bb8)
#4  0x00007f18746641e2 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2a51e2)
#5  0x00007f186b68898a _ZN3QCA10SyncThread3runEv (libqca-qt5.so.2 + 0xbe98a)
#6  0x00007f18744a84c6 _ZN14QThreadPrivate5startEPv (libQt5Core.so.5 + 0xe94c6)
#7  0x00007f18743a7299 start_thread (libpthread.so.0 + 0x9299)
#8  0x00007f187245b353 __clone (libc.so.6 + 0x100353)

Stack trace of thread 3615:
#0  0x00007f18743b3a8a __futex_abstimed_wait_common64 (libpthread.so.0 + 0x15a8a)
#1  0x00007f18743ad2c0 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf2c0)
#2  0x00007f182f28824b util_queue_thread_func (i965_dri.so + 0x24924b)
#3  0x00007f182f287d0b impl_thrd_routine (i965_dri.so + 0x248d0b)
#4  0x00007f18743a7299 start_thread (libpthread.so.0 + 0x9299)
#5  0x00007f187245b353 __clone (libc.so.6 + 0x100353)

Stack trace of thread 3614:
#0  0x00007f18743b3a8a __futex_abstimed_wait_common64 (libpthread.so.0 + 0x15a8a)
#1  0x00007f18743ad2c0 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf2c0)
#2  0x00007f182f28824b util_queue_thread_func (i965_dri.so + 0x24924b)
#3  0x00007f182f287d0b impl_thrd_routine (i965_dri.so + 0x248d0b)
#4  0x00007f18743a7299 start_thread (libpthread.so.0 + 0x9299)
#5  0x00007f187245b353 __clone (libc.so.6 + 0x100353)

Stack trace of thread 3612:
#0  0x00007f18743b3a8a __futex_abstimed_wait_common64 (libpthread.so.0 + 0x15a8a)
#1  0x00007f18743ad2c0 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf2c0)
#2  0x00007f182f28824b util_queue_thread_func (i965_dri.so + 0x24924b)
#3  0x00007f182f287d0b impl_thrd_routine (i965_dri.so + 0x248d0b)
#4  0x00007f18743a7299 start_thread (libpthread.so.0 + 0x9299)
#5  0x00007f187245b353 __clone (libc.so.6 + 0x100353)

**Comment by gioman** [comment]
@Ehespinosa 

setting > user profiles > new profile (and do not install any 3rd party plugin before testing with the new profile).
