### ISSUE TITLE
QGIS 3.22.3 bug when zooming XYZ tiles > OpenStreetMap.

### ISSUE THREAD

**Issue by bartclaeys** [qgis/QGIS#47472]
### What is the bug or the crash?

Zoom In button gives unexpected results.

### Steps to reproduce the issue

How to reproduce:

- Open QGIS, open XYZ Tiles, double tap OpenStreetMap.
- Use the Zoom In button in the menu bar and select US west coast.

Result: Map zooms into the ocean, when panning to the right I see Argentina.

### Versions

QGIS 3.22.3

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
Same as https://github.com/qgis/QGIS/issues/47212 ?
