### ISSUE TITLE
3d map view don't render all point feature

### ISSUE THREAD

**Issue by lispon** [qgis/QGIS#47476]
### What is the bug or the crash?

In qgis 3.16.16, 3d map view don't render all point feature, always leave 1 or 2 feature not render.
But in qgis 3.22.3, this issue has been resolved.
Unfortunately, I need qgis 3.16.16 in Debian 11.

### Steps to reproduce the issue

1. all point temporary layer
2. set layer styling: 3d view->single symbol ...
3. add 3D map view
4. add 1 point feature (then the 3D map view don't render 3D symbol)
5. add 4 point feature, as the picture show.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.16.16-Hannover | QGIS code revision | f5778a89
-- | -- | -- | --
Compiled against Qt | 5.15.2 | Running against Qt | 5.15.2
Compiled against GDAL/OGR | 3.4.1 | Running against GDAL/OGR | 3.4.1
Compiled against GEOS | 3.10.0-CAPI-1.16.0 | Running against GEOS | 3.10.2-CAPI-1.16.0
Compiled against SQLite | 3.35.2 | Running against SQLite | 3.35.2
PostgreSQL Client Version | 13.0 | SpatiaLite Version | 5.0.1
QWT Version | 6.1.3 | QScintilla2 Version | 2.11.5
Compiled against PROJ | 8.2.1 | Running against PROJ | Rel. 8.2.1, January 1st, 2022
OS Version | Windows 10 Version 2009
Active python plugins | db_manager; MetaSearch; processing

</body></html>QGIS version
3.16.16-Hannover
QGIS code revision
[f5778a89](https://github.com/qgis/QGIS/commit/f5778a89)
Compiled against Qt
5.15.2
Running against Qt
5.15.2
Compiled against GDAL/OGR
3.4.1
Running against GDAL/OGR
3.4.1
Compiled against GEOS
3.10.0-CAPI-1.16.0
Running against GEOS
3.10.2-CAPI-1.16.0
Compiled against SQLite
3.35.2
Running against SQLite
3.35.2
PostgreSQL Client Version
13.0
SpatiaLite Version
5.0.1
QWT Version
6.1.3
QScintilla2 Version
2.11.5
Compiled against PROJ
8.2.1
Running against PROJ
Rel. 8.2.1, January 1st, 2022
OS Version
Windows 10 Version 2009
Active python plugins
db_manager; 
MetaSearch; 
processing

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

![图片](https://user-images.githubusercontent.com/46800881/155106431-0506e272-bdca-4271-a68b-abb8ddd62c1b.png)

![图片](https://user-images.githubusercontent.com/46800881/155106588-1aae9258-ef8e-482a-975e-b40aa9623325.png)

**Comment by nyalldawson** [comment]
Qgis 3.16 is end-of-life. It's no longer supported.
