### ISSUE TITLE
problem on QGIS forms, in modification of several entities

### ISSUE THREAD

**Issue by vidarusny** [qgis/QGIS#47485]
### What is the bug or the crash?

I am using a QGIS project with custom forms on table.  all attributes are in tab container in forms. 
But when I use "Modify the Attributes os all Selected Features Simultaneously" some attributes are a red icon.
![image](https://user-images.githubusercontent.com/32432122/155180497-60895fce-9252-406a-9b16-670dd90d3cdf.png)

### Steps to reproduce the issue

1. activate editing mode 
2. select features
3.  click on "Modify the Attributes os all Selected Features Simultaneously"
4. forms open with red icon on some attributes

### Versions

QGIS version
3.16.11-Hannover
QGIS code revision
26cc1c76
Compiled against Qt
5.15.2
Running against Qt
5.15.2
Compiled against GDAL/OGR
3.3.1
Running against GDAL/OGR
3.3.1
Compiled against GEOS
3.9.1-CAPI-1.14.2
Running against GEOS
3.9.1-CAPI-1.14.2
Compiled against SQLite
3.35.2
Running against SQLite
3.35.2
PostgreSQL Client Version
13.0
SpatiaLite Version
5.0.1
QWT Version
6.1.3
QScintilla2 Version
2.11.5
Compiled against PROJ
8.1.1
Running against PROJ
Rel. 8.1.1, September 1st, 2021
OS Version
Windows Server 2016 Version 1809
Active python plugins
admin_plugin; 
Discovery; 
vigie_plugin; 
AnotherDXF2Shape; 
flowTrace; 
profiletool; 
StreetView; 
db_manager; 
MetaSearch; 
processing

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

All attributes accept null values.
All problematic attribut are in Value relation mode.
All problematic attributes have a filter expression.
![image](https://user-images.githubusercontent.com/32432122/155182337-4d3409e7-ec85-49ea-b606-8dda02a48c4c.png)
I have several attributes working very well in the same configuration but without filter expression

If the attributes are null icon is green, when attributes have a value sometimes is red, sometimes is green.

**Comment by gioman** [comment]
@vidarusny duplicate of https://github.com/qgis/QGIS/issues/47223 ?


Also 3.16 is EOL, please update to 3.22.

**Comment by vidarusny** [comment]
This a prod version of my project, I can't change easily. I come back when test version of environnement will up to date.
