### ISSUE TITLE
QGis on Mac | problem with scale settings | no matching scale of main map and print layout

### ISSUE THREAD

**Issue by malinbaru** [qgis/QGIS#47487]
### What is the bug or the crash?

Today I had a very serious problem with QGIS 3.16.13-Hannover on macOS Montery 12.2.1. I set my main map to 1:50,000 scale and then wanted to create a print layout from the map. Also on a scale of 1:50,000. However, the map image looked much less finely resolved there than in the main map - the resolution there was more like that of a scale of 1:10,000. However, 1:50,000 was set in the footer and also secured with the lock. As a test, when I clicked the "Set map to main map scale" setting in the layout window, the map in the layout jumped to a scale of 1:14,000. So it was not possible to set the main map to its real scale. Does anyone know this problem and how to solve it?

### Steps to reproduce the issue

1. go to the main map
2. set the scale to 1:50,000 in the footer
3. create a new print layout (with custom extent)
4. insert the map of the main map
5. set the scale to 1:50,000 as well
6. now the map has a lower resolution than the main map with the same settings

### Versions

QGIS 3.16.13-Hannover on macOS Montery 12.2.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

As additional information:
- all layers were created in the same format and in the same coordinate system (UTM Zone 32N)
- when I start QGIS, I generally have the problem that it does not open the projects in the previously saved extent, but for example at a scale of 1:13 somewhere over the sea near Africa
- the exported PDF from the main map appeared just as over-resolved as the map image on the Mac
- the exported PDF from the print layout appeared in the correct set scale

**Comment by gioman** [comment]
@malinbaru 3.16 is EOL, please test with 3.22.3

**Comment by malinbaru** [comment]
I did but it still happens
<img width="1080" alt="Bildschirmfoto 2022-02-22 um 19 33 21" src="https://user-images.githubusercontent.com/58854671/155196513-6f49e0ba-f810-4835-986f-544e20366145.png">

**Comment by gioman** [comment]
> I did but it still happens

@malinbaru attach a sample project that shows what you describe.

**Comment by malinbaru** [comment]
I'm sorry I can't share the files, there work-related. But It happens every time, even if I simple add an OSM-Basemap from QuickMapServices.

**Comment by malinbaru** [comment]
I'm quite sure that it doesn't depend on the data, but on the program/version etc. I only experienced this on Mac, maybe this information helps. The same data used with another device worked fine.

**Comment by gioman** [comment]
> But It happens every time, even if I simple add an OSM-Basemap from QuickMapServices.

@malinbaru I didn't said to attach your project, but a project, even a simple one with generic data, that shows what you describe. This way we are sure that we are testing the very same scenario.

**Comment by malinbaru** [comment]
[Test-Data.zip](https://github.com/qgis/QGIS/files/8119358/Test-Data.zip)
 
I hope this helps

**Comment by gioman** [comment]
> [Test-Data.zip](https://github.com/qgis/QGIS/files/8119358/Test-Data.zip)
> 
> I hope this helps

@malinbaru tried your steps on 3.22.3 on macOS Catalina, and can't replicate.

**Comment by gioman** [comment]
> now the map has a lower resolution than the main map with the same settings

unless I am misunderstanding what you mean here.

**Comment by gioman** [comment]
![image](https://user-images.githubusercontent.com/1951107/155201519-d9229f4e-d281-4008-8dd6-82861e3f184b.png)


![image](https://user-images.githubusercontent.com/1951107/155201820-f39cbf8c-ec29-4fd4-9729-10bff489f77e.png)

**Comment by malinbaru** [comment]
No it's right, but with this data you see the problem form starting the Projekt -  with the coordinate settings. I saved it zoomed on the line-data. But when I open again, it shows the sea. I'll add a layout setting to the data-package.

**Comment by malinbaru** [comment]
[Test-Data.zip](https://github.com/qgis/QGIS/files/8119585/Test-Data.zip)
<img width="1080" alt="Bildschirmfoto 2022-02-22 um 20 19 35" src="https://user-images.githubusercontent.com/58854671/155203433-f5a4a32a-cd2e-40f8-a4c6-e351821
<img width="1201" alt="Bildschirmfoto 2022-02-22 um 20 19 50" src="https://user-images.githubusercontent.com/58854671/155203459-b9ab9032-21e6-4038-b2e5-c700561d8cca.png">
0e82d.png">
<img width="1201" alt="Bildschirmfoto 2022-02-22 um 20 19 56" src="https://user-images.githubusercontent.com/58854671/155203448-b1170d59-1e52-4de9-a947-2ad968426f64.png">

<img width="1080" alt="Bildschirmfoto 2022-02-22 um 20 19 42" src="https://user-images.githubusercontent.com/58854671/155203440-3b96b31b-7e01-4494-9b01-b1160087ef26.png">

**Comment by gioman** [comment]
> I saved it zoomed on the line-data. But when I open again, it shows the sea.

@malinbaru it open zoomed in the right place here. Please try with a new QGIS profile.

**Comment by josbel96** [comment]
I have a similar problem every time I click on the scale drop down button 
![Screenshot 2023-04-15 at 15 26 17](https://user-images.githubusercontent.com/88201523/232226848-4183964d-33da-457b-b679-8169f69dd6fc.png)
