### ISSUE TITLE
Translation of tags in Transifex

### ISSUE THREAD

**Issue by skampus** [qgis/QGIS#47486]
### Feature description

hi,
with the PR  [33197 ](https://github.com/qgis/QGIS/pull/33197), many Search Tags on expression functions have been added.
They appear, in Transifex, as single word with:
Context = QgsExpression
Resource = qgis-application

the use of tags helps the search of functions and modules and tags have been already present since a long time and they are grouped as single string, formed by a series of words separated by a comma.
In this way, it is easy for translators to recognize this string and identify it as a tag.

As Italian community of translators, we have decided not to translate the tags because the function is in any case traceable in Italian through the words contained in the guide of the function itself and users accustomed to English terminology can continue to searching for them in English  (for example, en: _merge_ --> en: _fondi_).

The recently introduced tags, instead, are a single word and therefore difficult to recognize in their function (see New Tags picture)

I ask therefore if it is possible, even for the new tags, to group them in strings formed by words separated by commas, as it was until now (see Old Tags picture).

Thank you and ciao!

stefano 

**New Tags**

![image](https://user-images.githubusercontent.com/4558522/155127181-76646af9-3b3f-4a60-98e1-2794dfedc742.png)
 
**Old Tags**

![image](https://user-images.githubusercontent.com/4558522/155189896-7df8e780-8bb4-49dc-a5b0-7a2b84c42f91.png)

**Comment by karl-magnus** [comment]
Agree! If they should be translated a context is important. I translated them by searching in the expressions and saw where they came from. And it seems these single words are quite random words from the description. Not very well suited as search keywords.
