### ISSUE TITLE
Point cloud file not loading when pathname with accented characters

### ISSUE THREAD

**Issue by sigmoe** [qgis/QGIS#47481]
### What is the bug or the crash?

When you try to load a point cloud file (from the data source manager or by drag and drop), the file is not correctly loaded in QGIS if the pathname contains accented characters (French accented characters).

### Steps to reproduce the issue

See my video attached

Uploading QGIS-BugPointCloud.mp4…

### Versions

Version de QGIS
3.22.3-Białowieża
Révision du code
1628765ec7
Version de Qt
5.15.2
Version de Python
3.9.5
Version de GDAL/OGR
3.4.1
Version de Proj
8.2.1
Version de la base de données du registre EPSG
v10.041 (2021-12-03)
Version de GEOS
3.10.0-CAPI-1.16.0
Version de SQLite
3.35.2
Version de PDAL
2.3.0
Version du client PostgreSQL
13.0
Version de SpatiaLite
5.0.1
Version de QWT
6.1.3
Version de QScintilla2
2.11.5
Version de l'OS
Windows 10 Version 2009

Extensions Python actives
SgmCrm
version 3.0.1
SgmExpressionFunctions
3.0.3
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by sigmoe** [comment]
The video showing the problem:
https://user-images.githubusercontent.com/55922863/155144198-93aeb430-ed23-4a56-9a59-725247c6d39c.mp4

**Comment by nicogodet** [comment]
I believe I already report this.

**Comment by nicogodet** [comment]
Here #41833

**Comment by sigmoe** [comment]
I agree, this is the same problem
