### ISSUE TITLE
QGIS 3.24.0 has the splash screen without release candidate

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#47488]
### What is the bug or the crash?

![image](https://user-images.githubusercontent.com/7631137/155196145-2164cf75-d2e0-4f5a-8245-e4efa9aef923.png)

### Steps to reproduce the issue

- download QGIS version 3.24.0 from OSGeo4W v2
- start the program
- the splashscreen does not have the writing in question

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

email: https://lists.osgeo.org/pipermail/qgis-developer/2021-March/063243.html?fbclid=IwAR0VNZ60bbk9o1waEqUdZgCKNdGowOJWWcCKEvNlIbIovm03bBWma_dimd0

ticket OSGe04W: https://trac.osgeo.org/osgeo4w/ticket/731?fbclid=IwAR037Wa-dJDLDE9VPmMwFUEGSwH1tGnc0_Y8Mm-YQr3PIHZ_Cao85xoypws#ticket

**Comment by kannes** [comment]
What exactly do you mean? What is missing in your opinion?

**Comment by pigreco** [comment]
> What exactly do you mean? What is missing in your opinion?

QGIS 3.22.0:

![image](https://user-images.githubusercontent.com/7631137/155203072-cd59937c-c40a-4d6e-ba26-5f61f54b4a79.png)

QGIS 3.20.0

![image](https://user-images.githubusercontent.com/7631137/155203095-838a7aa9-dc6f-41fd-ad6a-04deead5824b.png)

**Comment by agiudiceandrea** [comment]
https://lists.osgeo.org/pipermail/qgis-psc/2022-February/009715.html

**Comment by pigreco** [comment]
@jef-n 
in OSGeo4W

![image](https://user-images.githubusercontent.com/7631137/155360494-8a642355-3882-4c6d-99bf-72f47085a579.png)

**Comment by pigreco** [comment]
![image](https://user-images.githubusercontent.com/7631137/155397530-be811e40-fe7f-4bd4-8961-2897819738ef.png)
