### ISSUE TITLE
Processing: support for GRASS 8

### ISSUE THREAD

**Issue by AndrewWiggins** [qgis/QGIS#47508]
### Feature description

I have Qgis 3.22.1-3, running on Manjaro kde ; I have Grass 8.1.dev working. 

As it is, Grass doesn't appear in the Qgis processing toolbox. The grass provider plugin does not support Grass 8.

It would be nice to be able to work with Grass 8 in Qgis.

**Comment by nicogodet** [comment]
I suggest to update your QGIS, a PR has been merged since 3.22.1 : https://github.com/qgis/QGIS/pull/47151

**Comment by AndrewWiggins** [comment]
> I suggest to update your QGIS, a PR has been merged since 3.22.1 : #47151

I went from the **stable** to the **unstable** branch in Manjaro, and updated Qgis to version 3.24. GRASS is now detected, and the processing toolbox shows GRASS.  I have switched back to the **stable** branch.
