### ISSUE TITLE
"Select Features by Value" not working with boolean data

### ISSUE THREAD

**Issue by Meibes** [qgis/QGIS#47507]
### What is the bug or the crash?

The "Select Features by Value" does not work with boolean data. checking or unchecking the corresponding checkbox and clicking on "select" does not select any features. In fact it seems like the selection process is not even started, at least there is no message providing information about the amount of selected features.

cheers

### Steps to reproduce the issue

1. add a layer with boolean data (i was using postgis-data)
2. open "select features by value"
3. check/uncheck the boolean field checkbox
4. hit "select"

### Versions

QGIS-Version
3.16.16-Hannover
QGIS-Codeversion
f5778a89
Kompiliert gegen Qt
5.15.2
Laufendes Qt
5.15.2
Kompiliert mit GDAL/OGR
3.4.1
Läuft mit GDAL/OGR
3.4.1
Kompiliert mit GEOS
3.10.0-CAPI-1.16.0
Läuft mit GEOS
3.10.0-CAPI-1.16.0
Kompiliert mit SQLite
3.35.2
Läuft mit SQLite
3.35.2
PostgreSQL-Client-Version
13.0
SpatiaLite-Version
5.0.1
QWT-Version
6.1.3
QScintilla2-Version
2.11.5
Kompiliert mit PROJ
8.2.1
Läuft mit PROJ
Rel. 8.2.1, January 1st, 2022
BS-Version
Windows 10 Version 2009
Aktive Python-Erweiterungen
db_manager; 
processing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
Confirmed also on 3.22.4

**Comment by Meibes** [comment]
the issue still persists in 3.22.5 - if i check/uncheck a boolean checkbox, neither of the blink/zoom/select buttons seem to do anything.


QGIS-Version
3.22.5-Białowieża
QGIS-Codeversion
c2723178
Qt-Version
5.15.2
Python-Version
3.9.5
GDAL-Version
3.4.1
PROJ-Version
8.2.1
EPSG-Registraturdatenbankversion
v10.041 (2021-12-03)
GEOS-Version
3.10.2-CAPI-1.16.0
SQLite-Version
3.37.2
PDAL-Version
2.3.0
PostgreSQL-Client-Version
13.0
SpatiaLite-Version
5.0.1
QWT-Version
6.1.3
QScintilla2-Version
2.11.5
BS-Version
Windows 10 Version 2009

Aktive Python-Erweiterungen
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99
