### ISSUE TITLE
default style not correctly displayed in Layers panel

### ISSUE THREAD

**Issue by janzandr** [qgis/QGIS#47506]
### What is the bug or the crash?

When opening a raster with a default _Paletted/Unique values_ style (stored as QML sidecar file), the style is loaded correctly, but the legend in the _Styles_ panel is not correct:
![image](https://user-images.githubusercontent.com/45030715/155296254-b81fc345-e531-4a66-90d3-461e8a8f4a3a.png)

![image](https://user-images.githubusercontent.com/45030715/155296123-b880ccd8-792d-4d27-8d8b-255c6fd47542.png)

### Steps to reproduce the issue

1. Open a raster with _Paletted/Unique values_ as default style (stored as QML sidecar file).
2. Legend in Styles panel is incorrect.

### Versions

QGIS-Version
3.22.3-Białowieża
QGIS-Codeversion
1628765ec7
Qt-Version
5.15.2
Python-Version
3.9.5
GDAL-Version
3.4.1
PROJ-Version
8.2.1
EPSG-Registraturdatenbankversion
v10.041 (2021-12-03)
Kompiliert mit GEOS
3.10.0-CAPI-1.16.0
Läuft mit GEOS
3.10.2-CAPI-1.16.0
Kompiliert mit SQLite
3.35.2
Läuft mit SQLite
3.37.2
PDAL-Version
2.3.0
PostgreSQL-Client-Version
13.0
SpatiaLite-Version
5.0.1
QWT-Version
6.1.3
QScintilla2-Version
2.11.5
BS-Version
Windows 10 Version 2009

Aktive Python-Erweiterungen
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by janzandr** [comment]
In addition, when the layer is created in a processing algorithm: even the default style isn't loaded correctly:
![image](https://user-images.githubusercontent.com/45030715/155299278-5d3f7ec6-0a15-4712-970f-77869f38b79a.png)

The user needs to manually click _Style > Restore Default_ in the _Layer Properties_. 
This is very inconvinient.

**Comment by nicogodet** [comment]
Still valid in 3.22.4 and 3.24.0 (and master I think but not tested)
