### ISSUE TITLE
Cannot order column by clicking on the header, if is of type timestampz

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#47517]
### What is the bug or the crash?

![image](https://user-images.githubusercontent.com/1951107/155386415-fdc821c4-6481-488a-94e4-032532f91a35.png)

I have a postgis table with a column that was defined as timestampz.

In the table of attributes clicking on the header of this column does nothing, is not ordered ASC or DESC as other fields, also the small black arrows pointing up or down do not show when clicking on the header.

### Steps to reproduce the issue

See above.

### Versions

3.22.4
3.24.0

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
Upon further tests this seems to happen only on certain tables, not all. I will try to figure out what is the source of the issue when it manifest itself.

**Comment by MrChebur** [comment]
@gioman 
I think that this is caused by changes in the format of the layers. So the layers saved in earlier versions of QGIS are not sorted, but the same data newly uploaded to the project are sorted normally.

**Comment by tudorbarascu** [comment]
Well, I also encountered this but I haven't actually determined when exactly is this exhibited.
A workaround that works is to:
- add new layer that points to the same datasource of the layer in question
- Right click on the added layer -> Styles -> Copy Style -> Attribute Table Settings
- Right click on the layer with problems -> Styles -> Paste Style -> Attribute Table Settings
- Remove the newly added layer
- The sort now works

There is indeed a problem somewhere but I haven't had the time to check it out in details.

**Comment by tudorbarascu** [comment]
@gioman  I cannot reproduce anymore. I think this can be closed.

**Comment by alexbruy** [comment]
@tudorbarascu, @gioman is this still valid?
