### ISSUE TITLE
Tranparceny/alpha value for SVG fill color (in labelling) always reverts to 1.0

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#47525]
### What is the bug or the crash?

Add labels to a layer and add a AVG backgroud

Then for that background try set the fill color as rgba, for example

rgba( 255, 0, 0, 0.5 )

to try give 50% transparency to the fill color. 

Upon OK the transparency is not applied and if the color properties are opened again the rgba value reverted to

rgba( 255, 0, 0, 1.00 )

### Steps to reproduce the issue

See above.

### Versions

3.22.3
3,24,0

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by Djedouas** [comment]
The alpha channel is not supported for SVG background yet.

Therefore, it should not be possible in the dropdown list to select #RRGGBBAA or rgba().
