### ISSUE TITLE
SVG used as symbols stored with absolute paths even if project is declared as relative

### ISSUE THREAD

**Issue by antoniolocandro** [qgis/QGIS#47528]
### What is the bug or the crash?

Project is set up to save paths are relative, when using SVG for symbology however the path is stored as absolute. The data and style is stored in a GPKG so I do not know if that makes any difference

![image](https://user-images.githubusercontent.com/4627073/155550855-75f3dc8d-f10f-4b13-bbde-898cbbccc658.png)

### Steps to reproduce the issue

1. Set Project to save to relative path
2. Create a GPKG
3. Create a layer
4. Use SVG as Symbols
5. URL is set as absolute 

### Versions

QGIS version
3.22.4-Białowieża
QGIS code revision
ce8e65e9
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
aixm_styler
0.1
changeDataSource
3.1
contour
2.0.8
DigitizingTools
1.5.1
latlontools
3.5.8
MemoryLayerSaver
4.0.4
mmqgis
2021.5.16
QPackage
1.5
quick_map_services
0.19.19
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Using plugins but should not conflict with the behaviour described here

**Comment by gioman** [comment]
> URL is set as absolute

@antoniolocandro do you mean inside the "layer_styles" table within the GPKG?

**Comment by gioman** [comment]
Related to https://github.com/qgis/QGIS/issues/29559 ?

**Comment by antoniolocandro** [comment]
Could be but I dont get the coment about the style saved in databases requiring to be absolute, at the end when I explored the style saved in the GPKG it is just the blob XML stored which I suppose QGIS then extracts and re-use. Also I think if a user select relative paths they expect everything to work as relative, nice to have are individual tweaking of parameters of course

**Comment by antoniolocandro** [comment]
> > URL is set as absolute
> 
> @antoniolocandro do you mean inside the "layer_styles" table within the GPKG?

Yes, see the example here

![image](https://user-images.githubusercontent.com/4627073/155597995-4a33a352-be3d-49fd-9c78-3187adc9580f.png)

**Comment by antoniolocandro** [comment]
Can't get to make it work with relative paths but probably I am doing something wrong

**Comment by gioman** [comment]
> Could be

I think is exactly the same.
