### ISSUE TITLE
QGIS runs out of memory when loading (raster) MBTiles file

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#47527]
### What is the bug or the crash?

QGIS generated a (raster) MBTiles file that will crash QGIS or your system because it makes QGIS eat all RAM. **Save your work before opening this!**

I created this MBTiles file in QGIS by loading 'world', zooming to Germany, setting the project CRS to EPSG:3035, opening the processing tool to generate XYZ MBTiles, chose the map extent and zoom levels 6-9 (I think, didn't check the result).

### Steps to reproduce the issue

1. Download and extract http://0x0.st/oK93.7z
2. Save your work
3. Open the MBTiles file you extracted
4. QGIS will be killed or the system will crash

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.25.0-Master | QGIS code revision | f3657c8860
-- | -- | -- | --
Qt version | 5.12.8
Python version | 3.8.10
GDAL/OGR version | 3.0.4
PROJ version | 6.3.1
EPSG Registry database version | v9.8.6 (2020-01-22)
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
SQLite version | 3.31.1
PDAL version | 2.0.1
PostgreSQL client version | 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.2
OS version | Ubuntu 20.04.4 LTS
  |   |   |  
This copy of QGIS writes debugging output.
  |   |   |  
...
</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

Another user in IRC reproduced this with 3.24 on Win10

**Comment by lpsSec** [comment]
I had the same problem 'runs out of memory' by running MBTiles over osgEarth.

OS: openSuse 15.4
GDAL: 3.6.3
Proj: 9.2.1
SQLite: 3.39.3

**Comment by alexbruy** [comment]
Link to the dataset is not working, but I followed steps to create my own MBTIles file and can't reproduce with the latest master (94b62accf2a1cfc892bc9097cd4dd5f8a1f60ab0) on Linux.

**Comment by kannes** [comment]
Thanks for re-trying, I now tried to reproduce it with 3.32.3-Lima and was also unsuccessful. Yay, a bug report to close :)
