### ISSUE TITLE
QGIS application not working on macOS Monterey 12.2

### ISSUE THREAD

**Issue by KEGviegand** [qgis/QGIS#47538]
### What is the bug or the crash?

I can install the software on my machine, but as soon as I open it the icon is jumping in the dock below where all the applications are located.

Also getting this error message.
"QGIS.app can't be opened because Apple can't scan if the software is malicious."

Tried:
 
Allow apps downloaded from:
"App store and identified developers"
"Open anyways"

### Steps to reproduce the issue

1. Install the software.
2. Open the software.
3. The icon is jumping in the docking bar on macOS
4. Software is closing and is not opening

### Versions

Tried 2 version.

QGIS Standalone installer version 3.24

QGIS Standalone installer version 3.22 LTR

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
@KEGviegand search this tracker for the same subject and you'll find the answer, that by the way is also on the download page in qgis site.
