### ISSUE TITLE
Cannot use setAttributes on a memory layer

### ISSUE THREAD

**Issue by sickel** [qgis/QGIS#47536]
### What is the bug or the crash?

I was to import some data from a fixed length text file, so I wrote a script to do this, I manually created a memory layer with a few attributes to import the data into. For each line, I created a point object and an array with the attribute data and I fed those and the layer into this function:

def addGeomToLayer(layer,geom,attribs):
    vpr = layer.dataProvider()
    f = QgsFeature()
    f.setGeometry(geom)
    f.setFields(layer.fields())
    f.setAttributes(attribs)
    print(f.attributes())
    vpr.addFeatures([f])

After I had read through the file, all the points were in but only the first element of the attribs array. All other fields where Null and I had an error message "Feature has too many attributes (expecting 1, received 6)" This happened after the addFeatures call. 

When saving the memory layer to postgis and reading the (at first empty) postgis layer into postgres, it worked flawlessly. 

### Steps to reproduce the issue

Create a  memory point layer EPSG 4326 with one text field, three float field and two more text fields and make that layer the active.

Then:

layer = qgis.utils.iface.activeLayer()
geom=qgsPoint(60,60)
attribs=['txt',3,4,5,'more txt','even more']
vpr = layer.dataProvider()
f = QgsFeature()
f.setGeometry(geom)
f.setFields(layer.fields())
f.setAttributes(attribs)
vpr.addFeatures([f])

This will return (True, [<qgis._core.QgsFeature object at ....]) in the console but a Feature has too many attributes error in the map window. When opening the Attribute table, only the first attribute has a value, all others are NUKK

The same code works fine with a postgis data provider, I have not tested with other types.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.24.0-Tisler | QGIS code revision | 6b44a42058
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
Arraymaker | 0.1
GroupStats | 2.2.5
localcoordinates | 0.3
MultiDistanceBuffer | 3.2.4
openlayers_plugin | 2.0.0
pluginbuilder3 | 3.2.1
plugin_reloader | 0.9.1
processing_r | 3.1.1
qchainage | 3.0.1
QCopycanvas | 0.5
qgisSpectre | 0.92
spiral_arms | 0.1
splitmultipart | 1.0.0
db_manager | 0.1.20
processing | 2.12.99
pg_raster_import | 1.0.10

</body></html>QGIS version
3.24.0-Tisler
QGIS code revision
[6b44a42058](https://github.com/qgis/QGIS/commit/6b44a42058)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
Arraymaker
0.1
GroupStats
2.2.5
localcoordinates
0.3
MultiDistanceBuffer
3.2.4
openlayers_plugin
2.0.0
pluginbuilder3
3.2.1
plugin_reloader
0.9.1
processing_r
3.1.1
qchainage
3.0.1
QCopycanvas
0.5
qgisSpectre
0.92
spiral_arms
0.1
splitmultipart
1.0.0
db_manager
0.1.20
processing
2.12.99
pg_raster_import
1.0.10

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
Not reproducible in latest master (2c8e784625): feature created without any errors and all attributes are filled with correct values.
