### ISSUE TITLE
QgsProcessingLayerPostProcessorInterface not post processing layer each time

### ISSUE THREAD

**Issue by ar-siddiqui** [qgis/QGIS#47533]
### What is the bug or the crash?

I am trying to use `QgsProcessingLayerPostProcessorInterface` to style and rename layers. I have had my share of issues with it [details here](https://gis.stackexchange.com/questions/423650/qgsprocessinglayerpostprocessorinterface-only-processing-the-last-layer), but I was able to finally achieve what I wanted to do. 

Now the issue that I am facing is that `QgsProcessingLayerPostProcessorInterface` will post-process layers sometimes and sometimes not. My plugin code is not changing, yet `QgsProcessingLayerPostProcessorInterface` is not behaving the same way each time. I have done enough investigation with my code to think that this issue might be with the `QgsProcessingLayerPostProcessorInterface` itself. 

I have also tested this on different QGISs and different computers.

### Steps to reproduce the issue

Here is the testing script on how I am applying `QgsProcessingLayerPostProcessorInterface`.

```python
from qgis.core import QgsProcessing
from qgis.core import QgsProcessingAlgorithm
from qgis.core import QgsProcessingParameterField
from qgis.core import QgsProcessingParameterVectorLayer
from qgis.core import QgsProcessingUtils
import processing

from qgis.core import (
    QgsRasterBandStats,
    QgsSingleBandPseudoColorRenderer,
    QgsGradientColorRamp,
    QgsProcessingLayerPostProcessorInterface,
    QgsProcessing,
)
from qgis.PyQt.QtGui import QColor


def run_alg_styler(display_name, layer_color1, layer_color2):
    """Create a New Post Processor class and returns it"""
    # Just simply creating a new instance of the class was not working
    # for details see https://gis.stackexchange.com/questions/423650/qgsprocessinglayerpostprocessorinterface-only-processing-the-last-layer
    class LayerPostProcessor(QgsProcessingLayerPostProcessorInterface):
        instance = None
        name = display_name
        color1 = layer_color1
        color2 = layer_color2

        def postProcessLayer(self, layer, context, feedback):
            if layer.isValid():
                layer.setName(self.name)

                prov = layer.dataProvider()
                stats = prov.bandStatistics(
                    1, QgsRasterBandStats.All, layer.extent(), 0
                )
                min = stats.minimumValue
                max = stats.maximumValue
                renderer = QgsSingleBandPseudoColorRenderer(
                    layer.dataProvider(), band=1
                )
                color_ramp = QgsGradientColorRamp(
                    QColor(*self.color1), QColor(*self.color2)
                )
                renderer.setClassificationMin(min)
                renderer.setClassificationMax(max)
                renderer.createShader(color_ramp)
                layer.setRenderer(renderer)

        # Hack to work around sip bug!
        @staticmethod
        def create() -> "LayerPostProcessor":
            LayerPostProcessor.instance = LayerPostProcessor()
            return LayerPostProcessor.instance

    return LayerPostProcessor.create()


class Style_output_layers(QgsProcessingAlgorithm):
    def initAlgorithm(self, config=None):
        self.addParameter(QgsProcessingParameterVectorLayer('Inputpolygons', 'Input_polygons', types=[QgsProcessing.TypeVectorPolygon], defaultValue=None))
        self.addParameter(QgsProcessingParameterField('Burnfields', 'Burn_fields', type=0, parentLayerParameterName='Inputpolygons', allowMultiple=True, defaultToAllFields=True,))

    def processAlgorithm(self, parameters, context, feedback):
        results = {}
        outputs = {}
        in_layer = self.parameterAsVectorLayer(parameters, 'Inputpolygons', context)
        fields = self.parameterAsFields(parameters, 'Burnfields', context)
        for index, field in enumerate(fields):
            if feedback.isCanceled():
                break
            # Rasterize
            alg_params = {
                    'BURN': 0,
                    'DATA_TYPE': 5,
                    'EXTENT': in_layer.extent(),
                    'EXTRA': '',
                    'FIELD': field,
                    'INIT': None,
                    'INPUT': parameters['Inputpolygons'],
                    'INVERT': False,
                    'NODATA': -9999,
                    'OPTIONS': '',
                    'UNITS': 1,
                    'HEIGHT': 90,
                    'WIDTH': 90,
                    'OUTPUT': 'TEMPORARY_OUTPUT',
                    }
        
            outputs[f'Outlayer{field}'] = processing.run('gdal:rasterize',
                                                        alg_params,
                                                        is_child_algorithm=True,
                                                        context=context,
                                                        feedback=feedback)
            results[f'Rasterized_{field}'] = outputs[f'Outlayer{field}']['OUTPUT']
            self.handle_post_processing(
                outputs[f'Outlayer{field}']['OUTPUT'], f'Rasterized_{field}', context
            )
        return results
        
    def postProcessAlgorithm(self, context, feedback):
        return {}

    def name(self):
        return 'style_output_layers'

    def displayName(self):
        return 'style_output_layers'

    def group(self):
        return 'Models'

    def groupId(self):
        return 'Models'

    def createInstance(self):
        return Style_output_layers()
        
    def handle_post_processing(self, layer, display_name, context) -> None:
            layer_details = context.LayerDetails(
                display_name, context.project(), display_name
            )
            context.addLayerToLoadOnCompletion(
                layer,
                layer_details,
            )
            if context.willLoadLayerOnCompletion(layer):
                context.layerToLoadOnCompletionDetails(layer).setPostProcessor(
                    run_alg_styler(display_name, (0,0,255), (255,0,0))
                )        
        
        
```

### Versions

3.16.5 & 3.22.2

QGIS version
3.16.15-Hannover
QGIS code revision
e7fdad64
Compiled against Qt
5.15.2
Running against Qt
5.15.2
Compiled against GDAL/OGR
3.4.0
Running against GDAL/OGR
3.4.0
Compiled against GEOS
3.10.0-CAPI-1.16.0
Running against GEOS
3.10.0-CAPI-1.16.0
Compiled against SQLite
3.35.2
Running against SQLite
3.35.2
PostgreSQL Client Version
13.0
SpatiaLite Version
5.0.1
QWT Version
6.1.3
QScintilla2 Version
2.11.5
Compiled against PROJ
8.2.0
Running against PROJ
Rel. 8.2.0, November 1st, 2021
OS Version
Windows 10 Version 1909
Active python plugins
changeDataSource; 
mapswipetool_plugin; 
pluginbuilder3; 
plugin_reloader; 
QNSPECT; 
searchlayers; 
valuetool; 
db_manager; 
processing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

More context:
https://gis.stackexchange.com/questions/423650/qgsprocessinglayerpostprocessorinterface-only-processing-the-last-layer

**Comment by Djedouas** [comment]
Hi,

This might be a threading issue.

The `LayerPostProcessor` class can be defined at the module level, but it must be instantiated in the main thread.

That is to say, not during the processing, which is launched in its own thread, or even in other threads if the processing is called by another processing.

For example, defining the `LayerPostProcessor` class in the python file at the module level and instantiating the `LayerPostProcessor` class in the `__init__` method of `Style_output_layers`

```python
def __init__(self):
    super().__init__()
    self.styler  = LayerPostProcessor()
```

But that is not a good solution with your example because you have one styler per output layer (the display_name is different each time). That mean that we should know in advance (in the __init__ method) all the display_name and the number of styler to instantiate.

I would suggest, if the processing does not require to be threaded (if you are OK with QGIS being frozen during the process), to flag the algorithm as mono-threaded, to make it more reliable.

Try with this method added to `Style_output_layers` :

```python
def flags(self):
    return QgsProcessingAlgorithm.FlagNoThreading | QgsProcessingAlgorithm.FlagCanCancel | QgsProcessingAlgorithm.FlagSupportsBatch
```

(the other flags are default flags when the `flags` method is not overriden)

**Comment by Djedouas** [comment]
Great!

I was indeed thinking of using a list or dictionary object, but it was too long right here to test and explain in this issue 😄 

Thanks,

Closing the issue.

**Comment by ar-siddiqui** [comment]
> Great!
> 
> I was indeed thinking of using a list or dictionary object, but it was too long right here to test and explain in this issue 😄
> 
> Thanks,
> 
> Closing the issue.

So there is no underlying issue with pyQGIS?

**Comment by Djedouas** [comment]
No, that's the way it works with multithreaded processing

**Comment by AlisterH** [comment]
> ### What is the bug or the crash?
> I am trying to use `QgsProcessingLayerPostProcessorInterface` to style and rename layers. I have had my share of issues with it [details here](https://gis.stackexchange.com/questions/423650/qgsprocessinglayerpostprocessorinterface-only-processing-the-last-layer), but I was able to finally achieve what I wanted to do.

It might have been good to post an answer to your question on stackexchange explaining how you solved the problem...
