### ISSUE TITLE
Refresh Button in Attribute Table is grayed out after updating  a field used to calculate a virtual field

### ISSUE THREAD

**Issue by bru500** [qgis/QGIS#47534]
### What is the bug or the crash?

If often edit data in the attribute table and I have virtual fields calculated of other fields. If I edit a field, the virtual fields don't get updated automatically. But the refresh button in the attribute table is greyed out. So I have to close and reopen the attribute table every time, I need to see the recalculated virtual fields. This takes a lot of time, especially to find the element I was working on in a long attribute table. The button to refresh the attribute table should be available.

### Steps to reproduce the issue

Create a virtual field calculated by an other field. Edit the field in the attribute table. The virtual field is not updated. The refresh button for the attribute table is greyed out and not available. The only way to recalculate the virtual field is to close and reopen the attribute table.

### Versions

QGIS 3.16.16 and QGIS 3.22.4

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
Maybe I miss something, but I can't find refresh button in the attribute table in the lates master (94b62accf2a1cfc892bc9097cd4dd5f8a1f60ab0). However, pressing `F5` key or using "Refresh" button on the "Map Navigaiton" toolbar refreshes virtual fields in the attribute table.

**Comment by bru500** [comment]
Sorry, I did mean the Button "Reload the table" next to "save edits" in the attribute table toolbar (non docked).
In QGIS 3.28.9, the button is not greyed out any more, after I leave edit mode. So my Issue can be closed as completed.
F5 with focus on the Attribut Table Window does not refresh (I use non docked). 
OK, I see, that F5 works if I click in the main QGIS window bevore. 
Thank you!
