### ISSUE TITLE
Layout Manager does not respect dynamic temporal controller

### ISSUE THREAD

**Issue by CoryAlbrecht** [qgis/QGIS#47543]
### What is the bug or the crash?

The Layout Manager does not respect filtering by the Dynamic Temporal Controller. All features from all times are show in an overlapping mess.

![image](https://user-images.githubusercontent.com/8172909/155820347-abd1c599-3c66-4c2e-b74b-03e54ec59d31.png)

### Steps to reproduce the issue

1. Open a project with temporal data.
2. Create a new layout and add a map to the page.
3. Wait for it to render.
4. See that all features from all times are shown in the temporal data layers.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.24.0-Tisler | QGIS code revision | 5d5f89f5c9
-- | -- | -- | --
Qt version | 5.12.8
Python version | 3.8.10
GDAL/OGR version | 3.0.4
PROJ version | 6.3.1
EPSG Registry database version | v9.8.6 (2020-01-22)
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
SQLite version | 3.31.1
PDAL version | 2.0.1
PostgreSQL client version | 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.2
OS version | Ubuntu 20.04.4 LTS
  |   |   |  
This copy of QGIS writes debugging output.
  |   |   |  
Active Python plugins
QGIS3-getWKT | 1.4
geometry_paster | 0.1.1
postgisQueryBuilder | 2.0.1
ClipMultipleLayers | 3.2.0
cartography_tools | 1.2.1
bettereditor | 1.5.0
quick_map_services | 0.19.28
db-style-manager | 0.8
splitmultipart | 1.0.0
pg_raster_import | 1.0.10
grassprovider | 2.12.99
processing | 2.12.99
db_manager | 0.1.20
sagaprovider | 2.12.99

</body></html>QGIS version
3.24.0-Tisler
QGIS code revision
[5d5f89f5c9](https://github.com/qgis/QGIS/commit/5d5f89f5c9)
Qt version
5.12.8
Python version
3.8.10
GDAL/OGR version
3.0.4
PROJ version
6.3.1
EPSG Registry database version
v9.8.6 (2020-01-22)
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
SQLite version
3.31.1
PDAL version
2.0.1
PostgreSQL client version
12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)
SpatiaLite version
4.3.0a
QWT version
6.1.4
QScintilla2 version
2.11.2
OS version
Ubuntu 20.04.4 LTS

This copy of QGIS writes debugging output.

Active Python plugins
QGIS3-getWKT
1.4
geometry_paster
0.1.1
postgisQueryBuilder
2.0.1
ClipMultipleLayers
3.2.0
cartography_tools
1.2.1
bettereditor
1.5.0
quick_map_services
0.19.28
db-style-manager
0.8
splitmultipart
1.0.0
pg_raster_import
1.0.10
grassprovider
2.12.99
processing
2.12.99
db_manager
0.1.20
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

This is very frustrating that so many things were broken by the dynamic temporal controller, and that they remain unfixed more than a year after its introduction.

**Comment by nyalldawson** [comment]
Not a bug -- this is already supported. Look in the documentation for how to achieve this.

**Comment by CoryAlbrecht** [comment]
@nyalldawson  There's nothing in the docs about the layout at either https://docs.qgis.org/3.16/en/docs/user_manual/print_composer/composer_items/composer_items_options.html#layout-item-options or https://docs.qgis.org/testing/en/docs/user_manual/print_composer/composer_items/composer_items_options.html about temporal anything.

**Comment by gioman** [comment]
> @nyalldawson There's nothing in the docs about the layout at either https://docs.qgis.org/3.16/en/docs/user_manual/print_composer/composer_items/composer_items_options.html#layout-item-options or https://docs.qgis.org/testing/en/docs/user_manual/print_composer/composer_items/composer_items_options.html about temporal anything.

@CoryAlbrecht https://docs.qgis.org/testing/en/docs/user_manual/print_composer/composer_items/composer_map.html#temporal-range
