### ISSUE TITLE
"Meters at Scale" spinbox is limited to a maximum 100000

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#47548]
### Feature description

When using "Meters at Scale" for the size of something in a style the user is not able to choose a size > 100000 when using the spinbox UI control. Using an expression one can set a higher value.

100000 is not big enough for some cases (e.g. scaling a centroid symbol to a big country or something on bigger planets).

Please remove the limit from the spinbox or if there has to be one, set it to something huuuuuuuge :)
This probably also applies to other spinboxes, I did not check.

### Additional context

Tested in 3.25 master

**Comment by kannes** [comment]
I should be able to do this, please assign it to me.

**Comment by kannes** [comment]
To reproduce:
1. Load "world"
2. Set a centroid fill
3. Set the marker size to "Meters at scale" and 100000 as value
4. Try to increase the value using the controls -> Does not work
5. Enter a higher value -> Value is entered but not actually used

**Comment by agiudiceandrea** [comment]
Hi @kannes, have you eventually fixed this bug?

**Comment by kannes** [comment]
Sorry, didn't get around doing this last week.

Couldn't find my old branch, not sure what I had made back then but it definitely wasn't enough. To properly fix this issue one needs to change _many_ `QDoubleSpinBoxes` to a higher value.

To find all affected places related to the "Meters at Scale" where I got into trouble I used `grep --text -Ri qgsunitselectionwidget | sed 's#:.*##' | sort | uniq` (actually outputs some false positives too):

> app/mesh/qgsmaptooleditmeshframe.cpp
> app/mesh/qgsmaptooleditmeshframe.h
> app/pointcloud/qgspointcloudelevationpropertieswidget.cpp
> app/qgselevationshadingrenderersettingswidget.cpp
> gui/annotations/qgsannotationitemwidget_impl.cpp
> gui/callouts/qgscalloutwidget.cpp
> gui/CMakeLists.txt
> gui/effects/qgspainteffectwidget.cpp
> gui/mesh/qgsmeshrenderermeshsettingswidget.cpp
> gui/mesh/qgsmeshrendererscalarsettingswidget.cpp
> gui/mesh/qgsmeshrenderervectorsettingswidget.cpp
> gui/pointcloud/qgspointcloudrendererpropertieswidget.cpp
> gui/qgstextformatwidget.cpp
> gui/qgsunitselectionwidget.cpp
> gui/qgsunitselectionwidget.h
> gui/symbology/qgsarrowsymbollayerwidget.cpp
> gui/symbology/qgsellipsesymbollayerwidget.cpp
> gui/symbology/qgsgraduatedsymbolrendererwidget.cpp
> gui/symbology/qgsheatmaprendererwidget.cpp
> gui/symbology/qgsinterpolatedlinesymbollayerwidget.cpp
> gui/symbology/qgspointclusterrendererwidget.cpp
> gui/symbology/qgspointdisplacementrendererwidget.cpp
> gui/symbology/qgssymbollayerwidget.cpp
> gui/symbology/qgssymbolslistwidget.cpp
> gui/symbology/qgssymbolslistwidget.h
> gui/symbology/qgsvectorfieldsymbollayerwidget.cpp
> ui/annotations/qgsannotationlinetextwidgetbase.ui
> ui/callouts/widget_ballooncallout.ui
> ui/callouts/widget_curvedlinecallout.ui
> ui/callouts/widget_simplelinecallout.ui
> ui/effects/widget_blur.ui
> ui/effects/widget_glow.ui
> ui/effects/widget_shadoweffect.ui
> ui/effects/widget_transform.ui
> ui/mesh/qgsmeshrenderermeshsettingswidgetbase.ui
> ui/mesh/qgsmeshrendererscalarsettingswidgetbase.ui
> ui/mesh/qgsmeshrenderervectorsettingswidgetbase.ui
> ui/pointcloud/qgspointcloudelevationpropertieswidgetbase.ui
> ui/pointcloud/qgspointcloudrendererpropsdialogbase.ui
> ui/qgsdecorationcopyrightdialog.ui
> ui/qgsdecorationimagedialog.ui
> ui/qgsdecorationnortharrowdialog.ui
> ui/qgsdecorationscalebardialog.ui
> ui/qgsdecorationtitledialog.ui
> ui/qgsdiagrampropertiesbase.ui
> ui/qgselevationshadingrenderersettingswidget.ui
> ui/qgsgraduatedsymbolrendererwidget.ui
> ui/qgspointdisplacementrendererwidgetbase.ui
> ui/qgstextformatwidgetbase.ui
> ui/qgsunitselectionwidget.ui
> ui/symbollayer/qgsarrowsymbollayerwidgetbase.ui
> ui/symbollayer/qgsgeometrygeneratorwidgetbase.ui
> ui/symbollayer/qgsheatmaprendererwidgetbase.ui
> ui/symbollayer/qgsinterpolatedlinesymbollayerwidgetbase.ui
> ui/symbollayer/qgspointclusterrendererwidgetbase.ui
> ui/symbollayer/widget_animatedmarker.ui
> ui/symbollayer/widget_ellipse.ui
> ui/symbollayer/widget_filledmarker.ui
> ui/symbollayer/widget_fontmarker.ui
> ui/symbollayer/widget_gradientfill.ui
> ui/symbollayer/widget_gradientline.ui
> ui/symbollayer/widget_hashline.ui
> ui/symbollayer/widget_linepatternfill.ui
> ui/symbollayer/widget_markerline.ui
> ui/symbollayer/widget_pointpatternfill.ui
> ui/symbollayer/widget_randommarkerfill.ui
> ui/symbollayer/widget_rasterfill.ui
> ui/symbollayer/widget_rasterline.ui
> ui/symbollayer/widget_rastermarker.ui
> ui/symbollayer/widget_shapeburstfill.ui
> ui/symbollayer/widget_simplefill.ui
> ui/symbollayer/widget_simpleline.ui
> ui/symbollayer/widget_simplemarker.ui
> ui/symbollayer/widget_svgfill.ui
> ui/symbollayer/widget_svgmarker.ui
> ui/symbollayer/widget_symbolslist.ui
> ui/symbollayer/widget_vectorfield.ui

Unfortunately one cannot "unlimit" the `QDoubleSpinBox`... :( And it looks like there is no standard or consensus in QGIS on a good maximum value (not even for the "Meters at Scale" ones). 

To be honest, I am not sure if I can pick up this issue. If someone else wants to, please go ahead.

https://doc.qt.io/qt-5/qdoublespinbox.html#details says "The displayed value of the QDoubleSpinBox is limited to 18 characters (...)". It might make sense to use 18 9s then.

PS: https://github.com/search?q=repo%3Aqgis%2FQGIS+9999&type=code ;)

**Comment by kannes** [comment]
Actually, let me just close this for now.

If someone _else_ is watching the issue waiting for a fix, feel welcome to comment. If you say which widgets exactly you need changed, I can do it ;)
