### ISSUE TITLE
gdal:warpreproject unexpected type handling

### ISSUE THREAD

**Issue by cefect** [qgis/QGIS#47547]
### What is the bug or the crash?

passing np.int32 parameters (instead of int) does not throw an error or recognize the input for gdal:warpreproject

### Steps to reproduce the issue

```
ins_d = {
     #other parameters
      'TARGET_RESOLUTION': np.int32(100)} 
processing.run('gdal:warpreproject', ins_d)

```
does not throw an error and the gdalwarp command does not recognize the input
`gdalwarp -of GTiff ...`

while
```
ins_d = {
     #other parameters
      'TARGET_RESOLUTION': int(100)} 
processing.run('gdal:warpreproject', ins_d)

```
prepares the gdal command as expected:
`gdalwarp -tr 100.0 100.0 -of GTiff ...`

### Versions

QGIS version
3.16.14-Hannover
QGIS code revision
42791986
Compiled against Qt
5.15.2
Running against Qt
5.15.2
Compiled against GDAL/OGR
3.4.0
Running against GDAL/OGR
3.4.0
Compiled against GEOS
3.10.0-CAPI-1.16.0
Running against GEOS
3.10.0-CAPI-1.16.0
Compiled against SQLite
3.35.2
Running against SQLite
3.35.2
PostgreSQL Client Version
13.0
SpatiaLite Version
5.0.1
QWT Version
6.1.3
QScintilla2 Version
2.11.5
Compiled against PROJ
8.2.0
Running against PROJ
Rel. 8.2.0, November 1st, 2021
OS Version
Windows 10 Version 2009
Active python plugins
canflood; 
firstaid; 
latlontools; 
MapsPrinter; 
menu_from_project; 
PluginLoadTimes; 
processing_taudem; 
processing_wbt; 
profiletool; 
db_manager; 
processing

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

This issue is especially  nasty as visually inspecting the inputs does not show the type change. My expectation would be that the processing handler at least throws an error.
maybe this should be a feature request? Either way, I hope this issue is helpful for others.

**Comment by gioman** [comment]
@cefect is not really clear to me how to replicate the problem. Is a script? if yes post it, if not please try clarify.

**Comment by cefect** [comment]
Apologies, I was trying to keep the post succinct. The below should reproduce the issue (run with the built-in interpreter and your own raster file).
```
rlay_fp = 'C:\raster.tif'
import numpy
class MyFeedback(QgsProcessingFeedback):
    def pushDebugInfo(self, info):
        print(info)
    def pushCommandInfo(self, info):
        print(info)

ins_d =  {
     'DATA_TYPE' : 0,#use input
     'EXTRA' : '',
     'INPUT' : rlay_fp,
     'MULTITHREADING' : False,
     'NODATA' : None,
     'OPTIONS' : '',
     'OUTPUT' : 'TEMPORARY_OUTPUT',
     'RESAMPLING' : 5,
     'SOURCE_CRS' : None,
     'TARGET_CRS' : None,
     'TARGET_EXTENT' : None,
     'TARGET_EXTENT_CRS' : None,
     'TARGET_RESOLUTION' : numpy.int32(100),
}
 
res_d = processing.run('gdal:warpreproject', ins_d, feedback=MyFeedback())
```

returns
`gdalwarp -r average -of GTiff C:\raster.tif  C:/.../OUTPUT.tif`

**Comment by gioman** [comment]
> 'TARGET_RESOLUTION' : numpy.int32(100),

@cefect sorry, maybe dumb question as I'm not very proficient in Python, but why you want to do the above rather than just

`'TARGET_RESOLUTION' : 100`

? The data type of the output is set with `DATA_TYPE' : 0,#use input` not in the resolution parameter.

**Comment by cefect** [comment]
The implementation is part of a larger module that was typesetting the
resolution parameter  as numpy type. This is not related to the output data
type of the raster.

Admittedly this is probably a rare use case, but I’d still expect the
processor to either recognize the input or throw an error.
