### ISSUE TITLE
Base maps blurry when magnified over 100%

### ISSUE THREAD

**Issue by jvose001** [qgis/QGIS#47552]
### What is the bug or the crash?

I like to zoom to 250% when using QGIS as I find it lines up better with what exported images look like. However, when I do this in 3.22 and 3.24, base maps look like crap and are super blurry. This issue is not present in 3.10 and 3.16. My shapefile layers look fine, it only seems to affect base maps from QMS.

### Steps to reproduce the issue

1) Load a base map in any way (using XYZ tiles, QMS, etc.).
2) Magnify to anything over 100%

What it looks like in 3.10: 
![image](https://user-images.githubusercontent.com/7132108/155864751-af223dfa-25d8-4cad-8efd-563567bce007.png)

What it looks like in 3.22: 
![image](https://user-images.githubusercontent.com/7132108/155864761-3ba3f3d2-eab5-4cce-b883-772f3f38e7f3.png)

### Versions

3.22

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by jvose001** [comment]
I've been really annoyed at this issue and somehow I stumbled upon a setting in "Canvas and Legend" called "Respect screen DPI". I checked that box and it fixed my issue. No idea what any of that means. It looks like that feature wasn't available in 3.10, so maybe that's why it changed. I guess I'll close this.

**Comment by jvose001** [comment]
How do I open this back up? I thought I solved my issue but I in fact did not.

**Comment by nyalldawson** [comment]
This is by design -- the old behaviour was a bug. Magnifying the view should cause the raster tiles to be magnified themselves, not fetched at different zoom level.

**Comment by nyalldawson** [comment]
@jvose001 sounds like you should consider using the layout designer to create and preview your exports
