### ISSUE TITLE
An option to make magnifying exhibit the "old" behavior

### ISSUE THREAD

**Issue by jvose001** [qgis/QGIS#47553]
### Feature description

Magnifying the map canvas used to not make base maps look blurry. It now does. I have been informed that this is actually intended. This boggles my mind, and frankly has me extremely frustrated. I would really like it if there could at least be an option to have magnifying the map canvas not just zoom in on the base map raster tiles, but actually fetch it at the closer zoom.

### Additional context

Here is my closed bug report with my issue: https://github.com/qgis/QGIS/issues/47552

**Comment by uclaros** [comment]
That's what the magnifier is supposed to do: magnify what's already on your canvas!
To achieve what you want, you can kind of force a specific zoom level to be fetched by going to XYZ layer's properties and select a *Min. zoom level* in the *Source* tab.

**Comment by jvose001** [comment]
Figured out that my issue was that the DPI in the layout was set to 300. I changed it to 100 and now the map canvas looks like the layout.
