### ISSUE TITLE
Slowness and high RAM consumption

### ISSUE THREAD

**Issue by patrickazevedo** [qgis/QGIS#47551]
### What is the bug or the crash?

I made a comparison between stable versions 3.16 (MSI and EXE) and found that the EXE version runs naturally on the computer. However, when using the MSI version, I noticed crashes and high memory consumption. All these events are organized in the map composer. With the stable 3.22 release, testing was performed and the problem still persists.
Opening the same project in both softwares and the MSI crashed the PC.

Could you explain to me what it could be.

My PC:
Processor: Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
Mother Plant: PCWARE - IPMH310G
Memory: Hyperx DDR4 16GB
Video Card: NVIDIA GEFORCE GTX 1050 Ti
SSD: 250GB

### Steps to reproduce the issue

Compositor de mapas, depois de adicionas 3 ou 4 camadas, a lentidão começa aparecer na verão MSI.

### Versions

Qgis versões MSI e EXE

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@patrickazevedo thanks for the report, but as it is put down is really hard to try replicate the problem, so

1) please try with a new QGIS profile (settings > user profiles > new profile)

and

2) if the problem persist, then write down a detailed list of steps to follow to replicate the problem, and of necessary link/attach a sample project with sample data.
