### ISSUE TITLE
Unable to copy data stored in `JSON` fields in the attribute table

### ISSUE THREAD

**Issue by MrChebur** [qgis/QGIS#47569]
### What is the bug or the crash?

When copying data stored in `json` format (recently appeared in QGIS) - the data of this field remain empty.

### Steps to reproduce the issue

1. Download this geopackage file: [test data.zip](https://github.com/qgis/QGIS/files/8152910/test.data.zip).
2. Open the attrubute table.
3. Copy all data (using Ctrl+C or corresponding button).
4. Paste the results into notepad.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.24.0-Tisler | QGIS code revision | 6b44a42058
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
AppendFeaturesToLayer | 1.2.0
DigitizingTools | 1.5.1
Go2NextFeature3 | 2.1
latlontools | 3.6.2
loadthemall | 3.3.0
MapsPrinter | 0.9
PluginLoadTimes | 3.0.1
qgsAzimuth | 0.9.15
rasterstats | 0.4.3
valuetool | 3.0.15
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
otbprovider | 2.12.99
processing | 2.12.99

</body></html>QGIS version
3.24.0-Tisler
QGIS code revision
[6b44a42058](https://github.com/qgis/QGIS/commit/6b44a42058)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
AppendFeaturesToLayer
1.2.0
DigitizingTools
1.5.1
Go2NextFeature3
2.1
latlontools
3.6.2
loadthemall
3.3.0
MapsPrinter
0.9
PluginLoadTimes
3.0.1
qgsAzimuth
0.9.15
rasterstats
0.4.3
valuetool
3.0.15
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
otbprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

![notepad++_AfU3fj3Cds](https://user-images.githubusercontent.com/20655102/155976138-c2f83588-ea74-45e4-9624-766f76c4c1c3.gif)

**Comment by ismailsunni** [comment]
Also doesn't work for list type.

**Comment by ismailsunni** [comment]
A workaround is to use GeoJSON as the format to copy.
Options -> Data Sources -> Copy feature as --> GeoJSON.
