### ISSUE TITLE
3.24.0-Tisler Couldn't load plugin 'MetaSearch'

### ISSUE THREAD

**Issue by andrew-c-duncan** [qgis/QGIS#47566]
### What is the bug or the crash?

Just installed QGIS 3.24.0. On opening get the error report "Couldn't load plugin 'MetaSearch' due to an error when calling its classFactory() method"

[Couldn't load plugin MetaSearch.txt](https://github.com/qgis/QGIS/files/8151071/Couldn.t.load.plugin.MetaSearch.txt)

### Steps to reproduce the issue

Just launched QGIS from the applications. MacOS Monterey 12.2.1, MacBook Pro (2017)

### Versions

QGIS version | 3.24.0-Tisler | QGIS code revision | e6ab9473e0
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 12.2
  |   |   |  
Active Python plugins
icsm_ntv2_transformer | 1.1.1
SelectWithin | 0.4
clipper | 1.2
qProf | 0.4.4
ntv2_transformations | 0.20
disconnected-islands | 2.0.2
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20

QGIS version
3.24.0-Tisler
QGIS code revision
[e6ab9473e0](https://github.com/qgis/QGIS/commit/e6ab9473e0)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.2
PROJ version
8.1.1
EPSG Registry database version
v10.028 (2021-07-07)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.11.5
OS version
macOS 12.2

Active Python plugins
icsm_ntv2_transformer
1.1.1
SelectWithin
0.4
clipper
1.2
qProf
0.4.4
ntv2_transformations
0.20
disconnected-islands
2.0.2
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
db_manager
0.1.20

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
Duplicates #47444. Please search bugtracker before posting new issue, often bugs are already reported.
