### ISSUE TITLE
Bring back Ignore shapefile encoding option. 

### ISSUE THREAD

**Issue by ACalleros** [qgis/QGIS#47575]
### Feature description

As a non English speaker sometimes vector files contain special characters like accents or ñ that don't get rendered. The usual solution was to go to Settings > data management and check Ignore shapefile encoding. In the newest version there's no such option. Please bring it back. 

### Additional context

![image](https://user-images.githubusercontent.com/36737154/156046835-7f70e96c-303e-4e4f-8b51-9f8f60ce0acc.png)

**Comment by nyalldawson** [comment]
You can control this on a layer by layer basis now -- look under the "source" tab in layer properties, and set the correct encoding option there.

**Comment by ACalleros** [comment]
I can't, it has been greyed out. 
![image](https://user-images.githubusercontent.com/36737154/156049495-01c5d6ef-cd1c-492d-93fa-e001dc1dd80e.png)

**Comment by nyalldawson** [comment]
@ACalleros which qgis version are you using? Can you copy all the details from the about screen please?

**Comment by gioman** [comment]
> I can't, it has been greyed out.

@ACalleros you sure is a shapefile and not another type of vector?
