### ISSUE TITLE
Small bug in OSGeo4W installer for Windows

### ISSUE THREAD

**Issue by Ellebjerg** [qgis/QGIS#47572]
### What is the bug or the crash?

When installing a newer version of QGIS with the OSGeo4W installer, the existing shortcuts in the start menu are not renamed or replaced. Instead new ones are added. Both the link named 3.16.X and the one named 3.22.4 work to open the latest ltr, but it is confusing for the users to have both links.

### Steps to reproduce the issue

Install QGIS with the OSGeo4W installer for Windows and look in the OSGeo4W folder in the start menu.

### Versions

3.22 (it was the same for 3.16)

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Should be reported [here](https://trac.osgeo.org/osgeo4w/query?status=assigned&status=closed&status=new&status=reopened&col=id&col=summary&col=status&col=type&col=priority&col=component&col=resolution&col=time&col=changetime&col=reporter&desc=1&order=id&report=12)

**Comment by gioman** [comment]
> Should be reported [here](https://trac.osgeo.org/osgeo4w/query?status=assigned&status=closed&status=new&status=reopened&col=id&col=summary&col=status&col=type&col=priority&col=component&col=resolution&col=time&col=changetime&col=reporter&desc=1&order=id&report=12)

correct.
