### ISSUE TITLE
Problems with GRASS GIS integration

### ISSUE THREAD

**Issue by oskeng** [qgis/QGIS#47571]
### What is the bug or the crash?

GRASS tools can be opened from the processing toolbox.

Core plugin is activated by default but there is no entry for GRASS in the Plugins menu. 

GRASS data are not recognized in browser and cannot be read (which is what I primarily need)

GRASS is not specified as available data provider under "Help/About/Providers"

GRASS is listed under "Settings/Options/Processing/Providers" but there is no option to set the path to the install.

### Steps to reproduce the issue

1. Build grass gis from source.
2. Build qgis 3.24 from source.

Issues as described above.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.24.0-Tisler | QGIS code branch | Release 3.24
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.10.2
GDAL/OGR version | 3.3.2
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.9.2-CAPI-1.14.3
SQLite version | 3.36.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.5
QScintilla2 version | 2.13.0
OS version | Fedora Linux 35 (KDE Plasma)
  |   |   |  
Active Python plugins
db_manager | 0.1.20
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
MetaSearch | 0.3.6

</body></html>QGIS version
3.24.0-Tisler
QGIS code branch
[Release 3.24](https://github.com/qgis/QGIS/tree/release-3_24)
Qt version
5.15.2
Python version
3.10.2
GDAL/OGR version
3.3.2
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.9.2-CAPI-1.14.3
SQLite version
3.36.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.5
QScintilla2 version
2.13.0
OS version
Fedora Linux 35 (KDE Plasma)

Active Python plugins
db_manager
0.1.20
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Not unlikely that I am simply doing something wrong. If so, a reply to this may be educational for others experiencing the same issue.

**Comment by alexbruy** [comment]
> Core plugin is activated by default but there is no entry for GRASS in the Plugins menu.

Which plugin? There are two of them. From the provided information it looks like you are talking about GRASS provider, which does not create any entries in the Plugins menu. 

> GRASS is listed under "Settings/Options/Processing/Providers" but there is no option to set the path to the install.

That's correct behaviour, we use the same GRASS which is shipped with QGIS by default.

**Comment by oskeng** [comment]
> Which plugin? There are two of them. From the provided information it looks like you are talking about GRASS provider, which does not create any entries in the Plugins menu.

From what I understand, grass integration consists of one plugin (for working with grass) and the provider (for browsing data). As described, neither works as intended. The plugin should (?) add an entry in the Plugins menu (at least it used to do that) for creating new mapset etc. And while the provider is not listed under "Help/About/Providers", it is listed under "Settings/Options/Processing/Providers", indicating that it is found but not loaded (?). In any way, I cannot browse grass data.

> That's correct behaviour, we use the same GRASS which is shipped with QGIS by default.

I added that information since I found several suggestions for similar issues relating to changing the grass path in that location. Good to know that this is no longer possible.

**Comment by gioman** [comment]
> From what I understand, grass integration consists of one plugin (for working with grass) and the provider (for browsing data). As described, neither works as intended.

@oskeng the provider: works, I just tested on Ubuntu 20.04 with both QGIS and GRASS  installed from repos. GRASS data can be read without issues from the Browser.

the GRASS plugin: is abandoned and unmaintained, it may still works or maybe not. Is in discussion to be removed

GRASS within the Processing toolbox: works and is supported.

Likely your issue comes from the fact that you are compiling and probably something is not set as it should. If you compile yourself and something do not works you should inquiry the developers mailing list rather than file a ticket here.

**Comment by oskeng** [comment]
Thanks @gioman. I will send an inquiry to the mailing list and see if can get it sorted out. Closing.
