### ISSUE TITLE
strpos returns null when input value is NULL

### ISSUE THREAD

**Issue by roya0045** [qgis/QGIS#47587]
### What is the bug or the crash?

According to the doc and rightfully, strpos should return 0 when the string cannot be found. 

But when it comes to NULL strpos returns NULL instead of 0, this derogate from the expected behaviour as 0 should be the fallback value instead of giving out NULL.

### Steps to reproduce the issue

Use strpos with a field that contain NULL or with a NULL directly as an input.

### Versions

Old master 2.19, issue should be unchanged.

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
Can you check what postgres gives in the same situation?

**Comment by roya0045** [comment]
> Can you check what postgres gives in the same situation?

If we intent do replicate that behavior then it seems to work the same (only validated on an online postgres sim).

**Comment by uclaros** [comment]
A null field is expected to return null in all operations like comparison, substring or concatenate so I would expect it to also return null in strpos.

**Comment by nyalldawson** [comment]
Current behaviour looks fine to me:

## Postgres:

![image](https://user-images.githubusercontent.com/1829991/156260333-9c451210-b137-43af-9d05-ffa8d379b5f1.png)


## QGIS:

![image](https://user-images.githubusercontent.com/1829991/156260565-05fc5833-22a6-4ab6-9727-3bdf2e30c267.png)

**Comment by roya0045** [comment]
> A null field is expected to return null in all operations like comparison, substring or concatenate so I would expect it to also return null in strpos.

I don't agree with that, if a function aims to modify or manipulate a variable then returning NULL is excpected if the input is NULL, but if the functions aims to provide information about the input, the output should not be NULL.

The goal if the function is to provide the position of the subtext, wether the input is NULL or '' the result should still be the same and indicate that the subtext is not present. 

I don't mind closing but I don't fully agree with the design choices in postgres (same goes for the || operator order).

**Comment by uclaros** [comment]
> I don't agree with that, if a function aims to modify or manipulate a variable then returning NULL is excpected if the input is NULL, but if the functions aims to provide information about the input, the output should not be NULL.

I wouldn't expect `'a' = null` to evaluate to `false` and I don't think it's a postgres thing! You can wrap your fields in `coalesce`s to treat nulls as empty strings or zeros or whatever.

**Comment by roya0045** [comment]
It seems microsoft sql is the sam with `CHARINDEX` and nulls. I'll close this then as it's not a bug.
