### ISSUE TITLE
Multipart to Singlepart feature could not be written

### ISSUE THREAD

**Issue by martinvanbuuren** [qgis/QGIS#47607]
### What is the bug or the crash?

After the update to QGIS 3.24.0 Tisler, the 'Multipart to Singleparts' yields errors stating the features could not be written. As a result, no data was written to the result set (memory layer called Single_parts).

In the previous version of QGIS, running Multipart to Singleparts on the same dataset worked like a charm.

```
QGIS version: 3.24.0-Tisler
QGIS code revision: e6ab9473e0
Qt version: 5.15.2
Python version: 3.9.5
GDAL version: 3.3.2
GEOS version: 3.9.1-CAPI-1.14.2
PROJ version: Rel. 8.1.1, September 1st, 2021
PDAL version: 2.3.0 (git-version: Release)
Algorithm started at: 2022-03-02T09:58:56
Algorithm 'Multipart to singleparts' starting…
Input parameters:
{ 'INPUT' : 'postgres://dbname=\'stamdata_nl\' host=127.0.0.1 port=5433 sslmode=disable authcfg=v936t9f key=\'tid\' srid=28992 type=MultiPoint checkPrimaryKeyUnicity=\'1\' table="demandpoints"."pc4" (geopunten_verzameling_primair)', 'OUTPUT' : 'TEMPORARY_OUTPUT' }
Feature could not be written to Single_parts_45aa0dae_29f2_445d_a6ef_55b4c2f1baf5: Could not store attribute "geopunten_verzameling_volledig": Could not convert value "" to target type
Feature could not be written to Single_parts_45aa0dae_29f2_445d_a6ef_55b4c2f1baf5: Could not store attribute "geopunten_verzameling_volledig": Could not convert value "" to target type
Feature could not be written to Single_parts_45aa0dae_29f2_445d_a6ef_55b4c2f1baf5: Could not store attribute "geopunten_verzameling_volledig": Could not convert value "" to target type
Feature could not be written to Single_parts_45aa0dae_29f2_445d_a6ef_55b4c2f1baf5: Could not store attribute "geopunten_verzameling_volledig": Could not convert value "" to target type
...
Feature could not be written to Single_parts_45aa0dae_29f2_445d_a6ef_55b4c2f1baf5: Could not store attribute "geopunten_verzameling_volledig": Could not convert value "" to target type
Message log truncated
```

### Steps to reproduce the issue

1. Go to vector -> Geometrie-gereedschappen -> Multiparts to Singleparts
2. Select a layer of geometry type Point(MultiPoint). In my case:
```
= Information from provider =
Storage | PostgreSQL database with PostGIS extension
Encoding |  
Geometry | Point (MultiPoint)
Extent | 13611.5550000000002910,306922.0769999999902211 : 277709.4521417830837891,613137.8767019889783114
Feature count | 4.069
= Coordinate Reference System (CRS) =
Name | EPSG:28992 - Amersfoort / RD New
Units | meters
Method | Oblique Stereographic Alternative
Celestial body | Earth
Reference | Static (relies on a datum which is plate-fixed)
```
3. Click Run.

### Versions

QGIS version | 3.24.0-Tisler | QGIS code revision | e6ab9473e0
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 12.2
  |   |   |  
Active Python plugins
contour | 2.0.8
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

QGIS version
3.24.0-Tisler
QGIS code revision
[e6ab9473e0](https://github.com/qgis/QGIS/commit/e6ab9473e0)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.2
PROJ version
8.1.1
EPSG Registry database version
v10.028 (2021-07-07)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.11.5
OS version
macOS 12.2

Active Python plugins
contour
2.0.8
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
@martinvanbuuren I imported your data in pgsql 14, loaded in QGIS 3.24.0 and the tool ran without issues, on Windows. Will try later on macOS.

**Comment by gioman** [comment]
@martinvanbuuren no issues on 3.24 on macOS Monterey (M1).

**Comment by martinvanbuuren** [comment]
Thanks for checking, @gioman. I’ll try uninstalling and reinstalling tomorrow morning to see if that resolves the problem. I’ll keep you updated.

**Comment by martinvanbuuren** [comment]
Hey @gioman,

As promised a quick update:
- Uninstalling and a fresh install from homebrew did not resolve the problem.
- Uninstalling and a fresh install from the QGIS installer from the website did not resolve the problem.

Tomorrow I'll try importing only the required fields in a new postgis table. Hopefully that'll resolve the problem. To be continued.

Kind regards,

~Mart
PS. I'm at an Intel Mac, though I don't expect that to make any difference.

![Schermafbeelding 2022-03-03 om 14 31 13](https://user-images.githubusercontent.com/62382424/156589918-79df11f3-2d89-4b03-8bd7-640d2f71c4de.png)

**Comment by martinvanbuuren** [comment]
@gioman Hereby a link to the pg_dump of the table: https://nas.darkarmada.nl:8080/f/3d3256990b114e7eaa81/?dl=1 (789MB, link is 7 days valid)

**Comment by gioman** [comment]
> @gioman Hereby a link to the pg_dump of the table: https://nas.darkarmada.nl:8080/f/3d3256990b114e7eaa81/?dl=1 (789MB, link is 7 days valid)

@martinvanbuuren can you please add the dump (pg_dump -Fc) of the **just** the table? the one you sent implies creating a db, schemas, users...

**Comment by martinvanbuuren** [comment]
@gioman Thanks for your patients, some high priority work came in-between letting me work during the weekend and leaving me with no free time until now. 

A new pg_dump with flags -Fc is done, and available by the following link:
https://nas.darkarmada.nl:8080/f/498bbbcbd03040f18671/?dl=1 (download 161 MB, decompressed 789 MB, link expires in 7 days).

**Comment by gioman** [comment]
@martinvanbuuren thank you for your time, but still cannot be restores cleanly. First he says there are missing schemas, which can be created manually, but then:

```
pg_restore: connecting to database for restore
pg_restore: creating TABLE "demandpoints.pc4"
pg_restore: while PROCESSING TOC:
pg_restore: from TOC entry 284; 1259 213019 TABLE pc4 martinvanbuuren
pg_restore: error: could not execute query: ERROR:  type "bag.geometry" does not exist
LINE 35:     geopunten_verzameling_volledig bag.geometry,
                                            ^
Command was: CREATE TABLE demandpoints.pc4 (
    pc4 text,
    buurt_code_primair text,
    buurt_codes text,
    buurt_naam_primair text,
    buurt_namen text,
    wijk_code_primair text,
    wijk_codes text,
    wijk_naam_primair text,
    wijk_namen text,
    woonplaats_primair text,
    woonplaatsen text,
    gemeente_code_primair text,
    gemeente_codes text,
    gemeente_naam_primair text,
    gemeente_namen text,
    provincie_naam_primair text,
    provincie_namen text,
    veiligheidsregio_code_primair text,
    veiligheidsregio_codes text,
    veiligheidsregio_naam_primair text,
    veiligheidsregio_namen text,
    jeugdregio_code_primair text,
    jeugdregio_codes text,
    jeugdregio_naam_primair text,
    jeugdregio_namen text,
    ggd_regio_code_primair text,
    ggd_regio_codes text,
    ggd_regio_naam_primair text,
    ggd_regio_namen text,
    regionale_eenheid_code_primair text,
    regionale_eenheid_codes text,
    regionale_eenheid_naam_primair text,
    regionale_eenheid_namen text,
    geopunten_verzameling_volledig bag.geometry,
    geopunten_verzameling_primair bag.geometry,
    geopunt_zwaartepunt_volledig bag.geometry,
    geopunt_zwaartepunt_primair bag.geometry,
    zwaartepunt_primair_rd_x double precision,
    zwaartepunt_primair_rd_y double precision,
    zwaartepunt_primair_wgs84_longitude double precision,
    zwaartepunt_primair_wgs84_latitude double precision
);


pg_restore: error: could not execute query: ERROR:  relation "demandpoints.pc4" does not exist
Command was: ALTER TABLE demandpoints.pc4 OWNER TO martinvanbuuren;

pg_restore: processing data for table "demandpoints.pc4"
pg_restore: from TOC entry 4636; 0 213019 TABLE DATA pc4 martinvanbuuren
pg_restore: error: could not execute query: ERROR:  relation "demandpoints.pc4" does not exist
Command was: COPY demandpoints.pc4 (pc4, buurt_code_primair, buurt_codes, buurt_naam_primair, buurt_namen, wijk_code_primair, wijk_codes, wijk_naam_primair, wijk_namen, woonplaats_primair, woonplaatsen, gemeente_code_primair, gemeente_codes, gemeente_naam_primair, gemeente_namen, provincie_naam_primair, provincie_namen, veiligheidsregio_code_primair, veiligheidsregio_codes, veiligheidsregio_naam_primair, veiligheidsregio_namen, jeugdregio_code_primair, jeugdregio_codes, jeugdregio_naam_primair, jeugdregio_namen, ggd_regio_code_primair, ggd_regio_codes, ggd_regio_naam_primair, ggd_regio_namen, regionale_eenheid_code_primair, regionale_eenheid_codes, regionale_eenheid_naam_primair, regionale_eenheid_namen, geopunten_verzameling_volledig, geopunten_verzameling_primair, geopunt_zwaartepunt_volledig, geopunt_zwaartepunt_primair, zwaartepunt_primair_rd_x, zwaartepunt_primair_rd_y, zwaartepunt_primair_wgs84_longitude, zwaartepunt_primair_wgs84_latitude) FROM stdin;
pg_restore: warning: errors ignored on restore: 3

```

Can you please attach the dump of **just** the problematic table/layer (so we can restore it in a whatever schema/db with a whatever owner)?

**Comment by alexbruy** [comment]
From the error message it seems that problem is with attributes, not geometries. Is it possible that input layer has fields with the data type which is not supported by QGIS or memory provider?
