### ISSUE TITLE
Different behavior when pressing the back button in the processing tools.

### ISSUE THREAD

**Issue by MrChebur** [qgis/QGIS#47602]
### What is the bug or the crash?

When you press the back button in the processing tools of different tools, their behavior is different.

![1](https://user-images.githubusercontent.com/20655102/156310575-5041fe2c-b6a4-41fb-b393-11f36fa5d902.png)

For example:
1. In the `Merge` tool, pressing the back button saves the changes you made.
2. In the tool `Reclassify by table` pressing the back button does NOT save the changes made.

It is suggested to unify the behavior when pressing this button (save everywhere or not save everywhere).

See this [mp4 video ](https://user-images.githubusercontent.com/20655102/156310697-974ccfcf-60aa-4def-ae89-0263e3cf6e1e.mp4) as example of different behavior (Don't open in a browser, download to your local drive).

 

### Steps to reproduce the issue

1. Open the `Merge` tool.
2. Set any parameters of the `Input layers` and press `back` (the changes will be saved).
3. Open the `Reclassification by table` tool.
2. Set any parameters of the `Table Reclassification` and press `back` (the changes will NOT be saved).

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.24.0-Tisler | QGIS code revision | 6b44a42058
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
AppendFeaturesToLayer | 1.2.0
DigitizingTools | 1.5.1
Go2NextFeature3 | 2.1
latlontools | 3.6.2
loadthemall | 3.3.0
MapsPrinter | 0.9
PluginLoadTimes | 3.0.1
qgsAzimuth | 0.9.15
rasterstats | 0.4.3
valuetool | 3.0.15
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
otbprovider | 2.12.99
processing | 2.12.99

</body></html>QGIS version
3.24.0-Tisler
QGIS code revision
[6b44a42058](https://github.com/qgis/QGIS/commit/6b44a42058)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
AppendFeaturesToLayer
1.2.0
DigitizingTools
1.5.1
Go2NextFeature3
2.1
latlontools
3.6.2
loadthemall
3.3.0
MapsPrinter
0.9
PluginLoadTimes
3.0.1
qgsAzimuth
0.9.15
rasterstats
0.4.3
valuetool
3.0.15
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
otbprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
I can confirm.
It's even more annoying when you spent few minutes to define the reclassification table and you miss click on return button instead of OK 😄

**Comment by MrChebur** [comment]
@nicogodet 
Yes, the fix is confirmed.
