### ISSUE TITLE
QGIS extremely slow

### ISSUE THREAD

**Issue by GeoKeys** [qgis/QGIS#47616]
### What is the bug or the crash?

Extremely slow.  I have been an irregular user, and upgraded from QGIS v3.16 to 3.24 Tisler yesterday.  Since the upgrade, it takes 2 to 3 minutes to open, and 30 to 40 seconds to do anything after I click. 

Any suggestions?

### Steps to reproduce the issue

Uninstalled all software using OSGEO4W, removed OSGEO and downloaded the new version of OSGEO and tried to re-install. 

### Versions

QGIS version
3.24.0-Tisler
QGIS code revision
6b44a42058
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
Anaximandre
1.2
AusMap
1.1
DigitizingTools
1.5.1
DirectionalSlope
1.3.2
flowTrace
1.1.1
FreehandRasterGeoreferencer
0.8.3
GeodesicDensifier
1.2
geoscience
1.5
localmaxfilter
1.5.7
profiletool
4.2.2
qad
3.0.4
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
otbprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Everything else on the computer is running fine. It is a reasonably spec'd machine: Alienware R4, Intel(R) Core(TM) i7-7820HK CPU @ 2.90GHz   2.90 GHz, 32 GB RAM, Windows 10 Pro.

**Comment by alexbruy** [comment]
Looking at the provided information, you did not tried with the new profile as there are lot of 3rd party plugins are active. Please try with the new profile.

Also please use meaningful titles for tickets.

**Comment by GeoKeys** [comment]
Hi,

I did try the new profile. I assumed that uninstalling and reinstalling would have cleared all the plugins.  In checking, the only plugins are the core plugins - none of the exported list above from Help about are listed:

![image](https://user-images.githubusercontent.com/100812714/156522421-e5b22644-eb52-4677-96eb-7b54fca16c5a.png)

**Comment by gioman** [comment]
> I did try the new profile.

@GeoKeys and you still have the issue you described?

**Comment by GeoKeys** [comment]
Yes, the same problem.  Maybe remove the osgeo again and just install using the standalone?

**Comment by gioman** [comment]
> Maybe remove the osgeo again and just install using the standalone?

@GeoKeys if there is an issue, it won't change a thing. Sof if you still have this issue with a new QGIS profile please attach a sample project with data that demonstrates it. Also, why you have closed the ticket?
